### ISSUE TITLE
first 'run' command stalls playback

### ISSUE THREAD

**Issue by bitingsock** [mpv-player/mpv#10005]
### Important Information

Provide following Information:
- mpv version: shinchiro mpv-x86_64-20220320-git-f871294
- Windows Version: 10
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/
- If known which version of mpv introduced the problem: don't know but at least a year
- Possible screenshot or video of visual glitches

https://0x0.st/oNyk.mp4

### Reproduction steps

Send a `run` command. this can be from a key binding, lua trigger or the ~console

### Expected behavior

The command is run without interruption

### Actual behavior

The first time `run` is sent it stalls playback for a bit. Subsequent calls work as expected, even with different arguments.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/8322040/log.txt)

**Comment by stax76** [comment]
Not on my system.

**Comment by bitingsock** [comment]
If anyone else experiences this: for me, it was Windows Defender causing the problem.
