### ISSUE TITLE
mpv updater.bat giving an error

### ISSUE THREAD

**Issue by neemanthnub** [mpv-player/mpv#10006]
### Important Information

Provide following Information:
- mpv version - shinchiro mpv-x86_64-20220320-git-f871294
- Windows Version - 10
- Source of the mpv binary - https://sourceforge.net/projects/mpv-player-windows/files/64bit/
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches - ![cmd_ldenHrA5O8](https://user-images.githubusercontent.com/92370174/159492031-af0c07a5-da17-423a-8e6d-01774e58a52c.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
 By running updater.bat with administrator permissions, it finds a newer build and installs it

### Actual behavior
It is throwing an error saying "Cannot bind argument to parameter 'Path' because it is an empty string.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it o the github issue, and replace this text with a link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Dudemanguy** [comment]
We do not distribute this build or bat file. I presume this is from @shinchiro's repo.

**Comment by monarc99** [comment]
updater.bat is part of shinchiro windows package.

report it here: https://github.com/shinchiro/mpv-packaging/issues

**Comment by Obegg** [comment]
My guy... did you read the text? just press 1 for daily updates.
![image](https://user-images.githubusercontent.com/13978119/159506138-6fa3e87c-3b12-4f51-8c1a-77a43885a8c7.png)

**Comment by BrianG61UK** [comment]
But we want weekly updates. Pressing 1 does not work!
