### ISSUE TITLE
Frame drops in the File/Playlist Loop

### ISSUE THREAD

**Issue by krisxsee** [mpv-player/mpv#10016]
### Important Information

- mpv version: 0.34.1
- macOS Version: 12.3 (Monterey)
- MacBook 560 
- Source of the mpv binary or bundle: [stolendata](https://github.com/mpv-player)
- Video: 2160x2160, 28mbps, h.264, 88mb

### Reproduction steps

--no-config: the same

### Expected behavior
When I play the video without File/Playlist Loop, it looks really good and smooth (60fps).

### Actual behavior
I like your special seamless looping feature so much 🚀
But with a playing in this mode, I sometimes have frame drops on the second or third cycle.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/8355214/mpv.log)

### Sample files

[Download Sample from Google Drive](https://drive.google.com/file/d/1oNN60fFSWWknLLfYbSDI6PcFy1LHfC8o/view?usp=sharing)

**Comment by Akemi** [comment]
your reproduction steps are incomplete. what loop options do you use exactly?

your log is incomplete, i don't see any file playing and looping.

**Comment by Dudemanguy** [comment]
No follow up and unclear issue = closed.
