### ISSUE TITLE
Fallback to Shift+PageUp/Down (10 min seek) when normal PageUp/Down reports "Chapter: (unavailable)"

### ISSUE THREAD

**Issue by d3fault** [mpv-player/mpv#10012]
I agree that PageUp/Down being mapped to Chapter Next/Previous is better behavior, but when chapters are unavailable rather than just saying "Chapter: (unavailable)" and doing nothing mpv should fallback to the old behavior of seeking +/- 10 minutes. Perhaps a message saying that we're seeking 10 mins, instead of jumping chapters, is warranted (so people expecting the chapter jump behavior know what's going on).

In my experience nearly all video files do not have chapters set up.

**Comment by hooke007** [comment]
> In my experience nearly all video files do not have chapters set up.

That sounds ridiculous. Countless dvd/bd/rip/remux videos have chapters.

**Comment by paulguy** [comment]
I'm not a dev so i don't have any say in things but I have different TV series i watch on my PC sometimes with and without chapters and i'll often use it to skip over opening sequences when there are and while it wouldn't be a _big_ deal, I kinda prefer it to do nothing in the cases that there are no chapters.  Especially for if i'm watching stuff when i'm half asleep and easily mixed up on what i'm doing heh.

**Comment by guidocella** [comment]
You can use this script:

```lua
mp.add_key_binding('PGUP', function ()
    mp.command(mp.get_property('chapter') and 'add chapter 1' or 'seek 600')
end)

mp.add_key_binding('PGDWN', function ()
    mp.command(mp.get_property('chapter') and 'add chapter -1' or 'seek -600')
end)
```

**Comment by d3fault** [comment]
Sweet that script works perfectly @guidocella , thanks!

**Comment by d3fault** [comment]
@thebombzen I don't consider this to be "completed" just because someone provided a hacky workaround. please re-open.



> > In my experience nearly all video files do not have chapters set up.
> 
> That sounds ridiculous. Countless dvd/bd/rip/remux videos have chapters.

Your experience differs. I usually watch videos I get off websites and other alternative sources. Regardless of which is more common, there are a *significant* amount of video files that do not have chapters set up.


Not having the fallback gives the experience that functionality has been removed (since mplayer fork). Having a fallback would adhere to the [Pit of Success](https://blog.codinghorror.com/falling-into-the-pit-of-success/) design philosophy.

**Comment by thebombzen** [comment]
Just bind another key, adding this behavior will only serve to confuse users.
