### ISSUE TITLE
diffferent color between gpu and gpu-next

### ISSUE THREAD

**Issue by soldivelot** [mpv-player/mpv#10017]
### Important Information

- mpv version: mpv 0.34.0-233-gf871294204
- Windows Version: Windows 11 21H2
- Source of the mpv binary: builds by shinchiro

gpu:
![mpv-shot0004](https://user-images.githubusercontent.com/84898012/160251041-8d859801-3a35-4b6a-b5ee-2033fc6af8dc.jpg)

gpu-next:
![mpv-shot0003](https://user-images.githubusercontent.com/84898012/160251051-b23ac99d-3c46-4f84-a06e-0c07c0e136f5.jpg)

same picture from madvr:
![20220327_012125](https://user-images.githubusercontent.com/84898012/160251115-cb95da21-3c68-49a5-adbf-fec791cbc59e.png)

clip info:

```
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0010 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 363 cd/m2
```

### Reproduction steps

mpv.conf

gpu:

```
vo=gpu
```

gpu-next:

```
vo=gpu-next
```

### Expected behavior

`gpu` and `gpu-next` should have close colors.

### Actual behavior

`gpu` is biased towards green and `gpu-next` is biased towards blue.

result from madvr looks same like `gpu` produced. they looks more natural

i've tried to specify `target-prim` and `target-trc` but nothing helped.

**Comment by ValZapod** [comment]
>tried to specify target-prim and target-trc but nothing helped.

But gpu-next requires those... What?

**Comment by hooke007** [comment]
the different implement of `--tone-mapping` `--tone-mapping-mode` should be the main cause

**Comment by LaserEyess** [comment]
https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU#general-differences

https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU#differences-in-option-behavior

**Comment by ValZapod** [comment]
> gpu-next requires those... What?

Even when you use SDR screen you still need to --target-trc gamma2.2, because of different default.

**Comment by soldivelot** [comment]
> the different implement of `--tone-mapping` `--tone-mapping-mode` should be the main cause

> https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU#general-differences
> 
> https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU#differences-in-option-behavior

I add `tone-mapping-mode=rgb` with `gpu-next` and now they have the same color, thanks.
