### ISSUE TITLE
[minor] warn about vtt being partially implemented

### ISSUE THREAD

**Issue by pirate486743186** [mpv-player/mpv#10015]
yea i deleted the template :P

just warn in the terminal and manual, that vtt (subtitle format) is partially implemented. I digged through the config and manual for what was broken,.... until i finally find out that it's simply not fully implemented -_- beh ... and it seams it will remain like this for a while.

**Comment by CounterPillow** [comment]
> and it seams it will remain like this for a while.

because vtt is a horrible format that should not exist

**Comment by ValZapod** [comment]
vtt you mean from here??

https://p-events-delivery.akamaized.net/1001azawzugclrwbvehhawhkerzwfetq/vod_main_QXfNLMWGxcNjjtymsofuJLttKvwNuuVE/cc/en/en.m3u8

which is just apple event in hevc and atmos:  https://events-delivery.apple.com/1402uekefjejgldkvaqrqxgjmtehwhez/m3u8/vod_index-VEPhheWQmQZLrgakajRXoUbKAmmjVXxZ.m3u8

**Comment by zhongfly** [comment]
I suggest you read the discussion here to understand why mpv only partially supports vtt:
https://github.com/mpv-player/mpv/issues/7214

**Comment by ValZapod** [comment]
And there is this: https://trac.ffmpeg.org/query?status=!closed&keywords=~vtt

**Comment by pirate486743186** [comment]
yes yes, now i know vtt is bloated and stuff.
The point is, simple users simply see vtt not working properly without any explanation.
We should be getting a warning.

**Comment by pirate486743186** [comment]
@sfan5
The issue is about adding a warning.

I already knew about vtt. The point is that it took me quite some time to find out what was broken, when a simple warning in the terminal would have indicated what it was.

**Comment by sfan5** [comment]
I don't think that's needed but regardless this'd be FFmpeg's responsibility since the subtitle format parsing/decoding resides in there.
