### ISSUE TITLE
How to detect if video is upscaled in auto profiles?

### ISSUE THREAD

**Issue by CrHasher** [mpv-player/mpv#10021]
I have this WHEN condition in a LUMA up-scaler:
```
//!WHEN OUTPUT.w LUMA.w / 1.100 > OUTPUT.h LUMA.h / 1.100 > *
```

And this auto profile:
```
[add-sharpness]
profile-restore=copy
profile-cond=(width < 2560 and height < 1440) # Display size (aka. if any type of up-scaling is used)
glsl-shader="~~/shaders/adaptive-sharpen-0_1.glsl"
```
Problem with this is that adaptive-sharpen-0_1.glsl is applied even when the LUMA up-scaler is not used example when displaying video windowed 1:1.

A partial fix:
```
[add-sharpness]
profile-restore=copy
profile-cond=fullscreen and (width < 2560 and height < 1440) # Display size (aka. if any type of up-scaling is used)
glsl-shader="~~/shaders/adaptive-sharpen-0_1.glsl"
```
Now its only applied when in fullscreen still not ok, but better.

What I would need is something like:
```
current-video-display-width / actual-video-width > 1.1 and current-video-display-height / actual-video-height > 1.1
```

What I tried so far but doesn't work:
```
dwidth / width > 1.1 and dheight / height > 1.1
osd-width / width > 1.1 and osd-height / height > 1.1
```

**Comment by guidocella** [comment]
There are `display-width` and `display-height` properties. They should be written as `display_width` and `display_height` in profile conditions.

**Comment by hooke007** [comment]
> detect if video is upscaled

`profile-cond=osd_width > width and osd_height > height`

**Comment by Doofussy2** [comment]
I use `video-params`

https://mpv.io/manual/master/#command-interface-video-params

**Comment by CrHasher** [comment]
@hooke007 This works:
```bash
[fsrcnn]
profile-restore=copy
profile-cond=(osd_width and osd_height and width and height) and (osd_width / width > 1.1) and (osd_height / height > 1.1)
glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"	# Prescaler based on layered convolutional networks (MOD - Scale video even for factor 1.1)
glsl-shader="~~/shaders/adaptive-sharpen-0_1.glsl"
```

@Doofussy2 can you paste your `profile-cond` here for reference please?

Another annoyance is adding auto profiles always at the end of mpv.conf couldn't there be a end-tag for this like [end] or [-]?
```bash
[fsrcnn]
profile-restore=copy
profile-cond=(osd_width and osd_height and width and height) and (osd_width / width > 1.1) and (osd_height / height > 1.1)
glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"	# Prescaler based on layered convolutional networks (MOD - Scale video even for factor 1.1)
glsl-shader="~~/shaders/adaptive-sharpen-0_1.glsl"
[end] # or similar
```

**Comment by Doofussy2** [comment]
You aren't setting a value after your first conditions, so that probably isn't doing anything. The rest would be much the same as using `video-params`.

**Comment by Dudemanguy** [comment]
Question was answered.
