### ISSUE TITLE
How does the format "ass-events" work?

### ISSUE THREAD

**Issue by FlafyDev** [mpv-player/mpv#10028]
I've seen the script [mpv_chapters.js](https://github.com/zxhzxhz/mpv-chapters/blob/master/mpv_chapters.js) that to draw stuff to the osd it used the `create_osd_overlay` function with the format "ass-events". Later in the script it changes the position of the text by appending `"{\\pos(x,y)}"` to the `.data` string. My question is how did the author of the script knew what to append to the string? Is the syntax documented somewhere or will I have to look into mpv's code?

**Comment by oe-d** [comment]
[https://aegi.vmoe.info/docs/3.1/ASS_Tags/](https://aegi.vmoe.info/docs/3.1/ASS_Tags/)
Is this what you're looking for?

To see how the strings are formatted just add print(assdraw.data) before assdraw.update() and check the console.

**Comment by TheAMM** [comment]
https://mpv.io/manual/master/#command-interface-ass-events
They are are ASS events, as in, Dialogue events defined by the ASS/SSA specs.
