### ISSUE TITLE
vo_gpu-next: lrc's rendering freeze when playing audio files

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#10022]
### Important Information

Provide following Information:
- mpv version
 https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20220327
- Windows Version
 win11 21h2
- Source of the mpv binary
 https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20220327
- If known which version of mpv introduced the problem
 N/A
- Possible screenshot or video of visual glitches
 N/A

### Reproduction steps

1. run **mpv.exe** (only `vo=gpu-next` in **mpv.conf**)
2. play a audio file (mp3) with LRC

### Expected behavior

All lyrics would be rendered.

### Actual behavior

After rendering one frame of the lyric, it stopped and never switch to the next sentence , only if I kept resizing the window.

### Log file

Before quitting , I was resizing the window.
[mpv.log](https://github.com/mpv-player/mpv/files/8358911/mpv.log)

### Sample files

[sample_LRC.zip](https://github.com/mpv-player/mpv/files/8358903/sample_LRC.zip)
If I play the video with LRC, it works well.

**Comment by NaiveInvestigator** [comment]
The subtitles also only update if the sub visibility is changed.

**Comment by haasn** [comment]
How do I reproduce this? I tried loading the subtitle file with `--sub-file=sample.lrc` but it just prints "Subtitle with unknown duration" and never shows anything, even with `--vo=gpu`.

**Comment by hooke007** [comment]
Try to play a mp3 with cover. No freezing if `vid=no`

**Comment by Dudemanguy** [comment]
Is this still an issue? I tried to reproduce on a flac file and it played fine and the lyrics showed.

**Comment by hooke007** [comment]
works on mpv-x86_64-v3-20230109-git-8439c08

**Comment by NaiveInvestigator** [comment]
it still happens for me tho, I am using shinchiro's build too. 

Using mpv-x86_64-20230220-git-9a752e8

**Comment by hooke007** [comment]
Probably open another issue, I cannot reproduce my issue.
