### ISSUE TITLE
Dolby Vision stopped working with the latest build

### ISSUE THREAD

**Issue by mnisius** [mpv-player/mpv#10037]
### Important Information

Provide following Information:
- mpv version: mpv-x86_64-20220401-git-deedc3d
- Platform and Version: Windows 10
- Source of the mpv binary: shinchiro 

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Play Video with Dolby Vision and vo=gpu-next

### Expected behavior
Colors look correct

### Actual behavior
Green tint with strange purple Colors. Looks like before DV support was available

If I revert back to mpv-x86_64-20220326-git-84821db all is fine and the DV Video looks like it should

**Comment by quietvoid** [comment]
Can reproduce.

Logs:  
Not working (master, deedc3d418f03222d8b7cb64de51fc383ca356f1): [deedc3d418.log](https://github.com/mpv-player/mpv/files/8400156/deedc3d418.log)
Working (1c2dde91d369987199782f4914f56019e5a2272c): [84821dbcb6.log](https://github.com/mpv-player/mpv/files/8400155/84821dbcb6.log)
