### ISSUE TITLE
How to keep osd message on screen

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#10045]
How do I keep the message on screen indefinitely? Also how do I clear a message?

**Comment by garoto** [comment]
Can't be done out-of-the-box elegantly and with a single keybind as far as I'm aware. Needs a lua script with  `mp.create_osd_overlay` or `mp.set_osd_ass`  I'm guessing.

**Comment by Hrxn** [comment]
Uh, depending on what you actually want do to..
Isn't it possible to repurpose  `--osd-playing-msg=` for this? Or is this also a temporary message by default?

FWIW, there's also `--osd-msg1=`, `--osd-msg2=`, and `--osd-msg3=`, which are enabled by the OSD level setting.

I suggest to try to set any of these to some output you want, and then use keybinds to toggle the OSD level..
Not sure, have not tested this myself yet, but I believe this should work.

**Comment by guidocella** [comment]
`cycle-values osd-msg1 "message" ""`

**Comment by Hrxn** [comment]
Not sure, OSD level 1 is normally active given presence of user interaction (i.e. mouse cursor moved, etc.)
Is that really persistent, as soon as it's set to a custom value in the config or something?

Another relevant question here:
Consider that you have set `osd-msg1` to some pretty huge message string containing lots of property expansions etc., wouldn't it be better (performance-wise, or else) to keep that option unchanged, and instead changing OSD level on user input, e.g.
`cycle-values osd-level 0 1`
or something?

**Comment by guidocella** [comment]
`cycle-values osd-level 0 1` would hide every other OSD message too.

**Comment by Hrxn** [comment]
Wasn't this the intent of OP?
Keep message on screen indefinitely, then clear message on user interaction, e.g. key press, @cerealXDD ?

**Comment by cerealXDD** [comment]
Yes, exactly

**Comment by cerealXDD** [comment]
I was able to achieve a desired result with cycle-values osd-msg1 msg, and
cycle-values osd-level 0 1. Thanks everyone
