### ISSUE TITLE
Tone mapping and color space conversion computed on hdr passthrough

### ISSUE THREAD

**Issue by Shashank066** [mpv-player/mpv#10043]
### Important Information

Provide following Information:

- mpv version 
 0.34.0-233-gf871294204

- Windows Version
 Windows 11
 
- Source of the mpv binary
Windows builds by shinchiro

### Reproduction steps

Config for hdr passthrough

```
vo = gpu-next
target-colorspace-hint=yes
d3d11-exclusive-fs=yes
d3d11-output-csp=pq
target-trc=pq
target-prim=bt.2020
hdr-compute-peak=no
opengl-pbo=yes
```
Windows 11 is set to hdr mode. Running a hdr video on hdr display. Using lg cx in 10 bit rgb mode with hdmi 2.1.

### Expected behavior
I guess tone mapping and color space conversions shouldn't be done, since it's handled by tv if hdr passthrough is working correctly.

### Actual behavior
Still shows tone mapping,color space conversion on second page of stats.

![Stats](https://user-images.githubusercontent.com/8770783/161381000-e92fa779-cf9a-4a4c-b54c-d91c96d9ef08.jpg)

Anyway to know if hdr passthrough is working correctly.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/8402365/log.txt)

**Comment by haasn** [comment]
I can't reproduce this even with the same settings.

**Comment by Shashank066** [comment]
Unfortunately for me, no matter what I try I can't get hdr passthrough to work. Tried both HDMI 2.1 on Intel and Nvidia. Tried reading existing hdr issues, Google search results, mpv manual, different videos and configuration combinations.

**Comment by Shashank066** [comment]
1 of the things I notice is mouse cursor is hidden when playing on hdr monitor. Does that mean hdr pass through was successful?

**Comment by Andy2244** [comment]
I'm seeing the same with latest git, `vo = gpu-next` always reports tone mapping, in contrast `vo = gpu` does not with the same HDR pass-through settings.

**Comment by ValZapod** [comment]
At least in HGIG tonemapping must be done on source device.

d3d11-exclusive-fs=yes will  ot work unless you turn off fullscreen optimisations in exe properties.

d3d11-output-csp=pq is not needed.

target-colorspace-hint=yes does not work in gpu-next?

**Comment by Shashank066** [comment]
> At least in HGIG tonemapping must be done on source device as per Google spec.
> 
> d3d11-exclusive-fs=yes will not work unless you turn off fullscreen optimisations in exe properties. And even then it will lead to 4:2:0 on LG C9, CX. You need to edit edid to change the behaviour.
> 
> d3d11-output-csp=pq is not needed, because in HDR mode it is autoselected since d3d11 commit and in SDR it will work, but will not allow for HDR, because wddm 2.7 broke it.
> 
> target-colorspace-hint=yes does not work in gpu-next(?)

Thanks. Most of these options were copied from other users config in issues.

HGIG tonemapping is more suited for games I think. It disables motion interpolation on lg cx. Dynamic tone mapping on works good instead for movies.

Disabled exclusive fullscreen now. Doesn't seem to provide any benefit. Although d3d11-exclusive-fs=yes didn't cause 4:2:0 on LG CX even after turning off fullscreen optimisations in exe properties.

wiki for gpu-next mentions  target-colorspace-hint as an option
 [https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU](url)

I don't have an understanding about hdr passthrough and if need for tone mapping and color space conversion is required on source device. Hdr video seems to display correct.

**Comment by ValZapod** [comment]
>didn't cause 4:2:0 on LG CX even after turning off fullscreen optimisations in exe properties.

Did you check hidden HDMI menu? It causes 4:2:0 120 fps it on my LG C9 that caises a problem, since it is buggy on C9, only working since CX.

>space conversion is required on source device.

That one is not needed on source device, it is done only on WebOS. That is why target-prim=bt.2020 is done (though it should be a default). Tonemapping may be done on source device.

**Comment by Hrxn** [comment]
`--gpu-context=` is set?
`--gpu-api=` is set?

**Comment by ValZapod** [comment]
> `--gpu-context=` is set?

winvk is very buggy, so the default d3d11 is better since it got implemented

>--gpu-api= is set?

No need to set either.

**Comment by Shashank066** [comment]
> Did you check hidden HDMI menu? It causes 4:2:0 120 fps it on my LG C9 that causes a problem, since it is buggy on C9, only working since CX.
Yes did check with hidden menu. Checked again now with more options. 
With Nvidia 3060ti just have to select 10 bit in Nvidia control panel and 10 bit rgb works for all refresh rate and configurations.

With UHD 770 even on hdmi 2.1, 10 bit RGB only works until 30hz 4k. Above 30hz switches to 8bit.

**Comment by ValZapod** [comment]
> even on hdmi 2.1,

This is hdmi 2.0b. Yes, same here on my 2080 ti.
