### ISSUE TITLE
Default volume level is always the highest possible

### ISSUE THREAD

**Issue by MahmoudHelmi** [mpv-player/mpv#10046]
Hello, 
Whenever I open any videos using MPV, I find that the default sound volume is always the  highest possible (the maximum output of my speakers!!!), even when the PC volume settings itself are adjusted to be low! This doesn't happen with any other players on my PC. I literally have to run and hurry to decrease the volume (using "/") once the video starts. This happens in each single video, and it is very annoying. I want the volume to be permanently adjusted to a low level, so that I do not hear an explosive sound that can literally awaken all the building I live in each time I start a video. How can I fix this (I don't have extensive programming knowledge, so simple steps are appreciated)

**Comment by garoto** [comment]
cool story bro, now how about searching the manual for `volume` huh? Sounds like a pretty good idea for me.

**Comment by MahmoudHelmi** [comment]
> cool story bro, now how about searching the manual for `volume` huh? Sounds like a pretty good idea to me.

I have already done so. I searched every instance of the word "volume" in the pdf manual before asking my question, but I didn't find what I want.

**Comment by Hrxn** [comment]
You simply put `volume=23` (for example) into your config file?

**Comment by ValZapod** [comment]
> I find that the default sound volume is always the highest possible (the maximum output of my speakers!

Which is the correct behaviour, volume can and must be only manipulated in the output device. That means that the windows and the player are playing at max and you control on AVR or TV. Sigh. Because if you control in mpv loudness normalisation is impossible, if you control in windows same in the case of bitstreaming, morover when you bitstream atmos there is only two way mute and sound, there is no waupy to control sound in Dolby Atmos. Sigh.

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#configuration-files
https://mpv.io/manual/master/#options-volume

**Comment by paulguy** [comment]
It sounds like somehow mpv might be adjusting their output volume, unless they just individually configure every application with its own volume level when they allow volume adjustment.  In which case they probably should figure out adjusting their speaker volume or using the windows volume control in 1 place and leaving all applications at "100%".

**Comment by Dudemanguy** [comment]
I think we're good here.
