### ISSUE TITLE
Individual OSD duration

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#10048]
Is it possible to give individual duration for each instruction? not general OSD duration.

For example 3 seconds on screen to this in mpv.conf
**--osd-playing-msg="${filename} (${playlist-pos-1}/${playlist-count})"**

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/pull/10013

**Comment by Hrxn** [comment]
Yeah, like this
```
<Your Keybind> show-text "[${playlist-pos-1}/${playlist-count}] : ${filename}\nTitle: ${media-title}" 4000
```

4000 means a duration of  4000 ms.. obviously.

**Comment by jimmy-1000** [comment]
> Yeah, like this
> <Your Keybind> show-text "[${playlist-pos-1}/${playlist-count}] : ${filename}\nTitle: ${media-title}" 4000 
> 4000 means a duration of 4000 ms.. obviously.

Thanks but not for input.conf with keybinding. But for mpv.conf, so that each video that is reproduced (automatic mode = --keep-open=no) shows the information on screen without typing a key.

**Comment by Hrxn** [comment]
You mean like in #10045 .. but not permanently displayed?

**Comment by jimmy-1000** [comment]
> You mean like in #10045 .. but not permanently displayed?

No, only 3 or 4 seconds. But only that instruction, not global OSD messages.

**Comment by guidocella** [comment]
Doing this with `osd-playing-msg` depends on https://github.com/mpv-player/mpv/pull/10013, so for now you need to use a script instead:

```lua
mp.register_event("file-loaded", function()
        mp.command("show-text '${filename} (${playlist-pos-1}/${playlist-count})' 3000")
end)
```

**Comment by jimmy-1000** [comment]
> Doing this with `osd-playing-msg` depends on #10013, so for now you need to use a script instead:
> 
> ```lua
> mp.register_event("file-loaded", function()
>         mp.command("show-text '${filename} (${playlist-pos-1}/${playlist-count})' 3000")
> end)
> ```

Thanks guidocella! You did it by a lua script. I think it's the only way.

**Comment by guidocella** [comment]
`osd-playing-msg-duration` can now be used with a new enough mpv.

**Comment by jimmy-1000** [comment]
> `osd-playing-msg-duration` can now be used with a new enough mpv.

Hi guidocella. Can you give me one example? How combine that with this --osd-playing-msg="${filename}" ?

**Comment by hooke007** [comment]
```
osd-playing-msg="${filename}"
osd-playing-msg-duration=3000
```

**Comment by jimmy-1000** [comment]
> ```
> osd-playing-msg="${filename}"
> osd-playing-msg-duration=3000
> ```
Thanks hooke007 for you help.
