### ISSUE TITLE
Better OSC (bar below)

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#10056]
Improvement of the bar below.
1. Name or title below is unnecessary because it is at the top of window.
2. Buttons of Next and Previous are best placed down among the others.
3. With the above two changes, the bar can be reduced to half its width.
4. Playing time next to duration time. This is the normal and natural in most players.

![Imagen1](https://user-images.githubusercontent.com/78575427/161844892-75cd9cf5-d017-4685-89a0-81783fc7a81b.jpg)

**Comment by hooke007** [comment]
It's your preference, not "Improvement".

**Comment by jimmy-1000** [comment]
> It's your preference, not "Improvement".

If you prefer a messy and redundant bar...

**Comment by Francicoria** [comment]
1. When are you considering fullscreen users?
2. Totally personal preference;
3. Who cares about bar height if after 2 second of mouse inactivity the bar disappears?
4. VLC, which is a really big project, has the same behavior.

**Comment by jimmy-1000** [comment]
> 1. When are you considering fullscreen users?
> 
>     2. Totally personal preference;
> 
>     3. Who cares about bar height if after 2 second of mouse inactivity the bar disappears?
> 
>     4. VLC, which is a really big project, has the same behavior.

1. There is not problem in full screen mode.
2. Many people in forums say is the correct and logic bar.
3. Two seconds is your preference, many people change that.
4. VLC is trash. It has a lot of failures, bugs, and lack of good and useful features.

**Comment by dyphire** [comment]
> If you prefer a messy and redundant bar...

Just your personal point of view.

> Name or title below is unnecessary because it is at the top of window.

I have to ask you an important question. Where are the features of display target chapter at the title when seekbar hover/drag? This is a feature update of mpv's osc: https://github.com/mpv-player/mpv/commit/76b1ac57a4f49ff2c7f18b7e46aefa7fb3362984.
Are you sure this is an improvement rather than a regression?


In my opinion, you may just want to get a better osc layout on the video aspect ratio is less than 1.

**Comment by jimmy-1000** [comment]
> > ...

OK, Due to my proposal has not been liked, I will close this topic.
