### ISSUE TITLE
Apple M1: Application crashes when user resizes window while video playback

### ISSUE THREAD

**Issue by edgarfauquier** [mpv-player/mpv#10053]
### Important Information

mpv version: 0.34.1
macOS version: M1 Big Sur Version 11.5.2

### Reproduction steps

Crash happens when application is run with _--vo=gpu_, and window is manually resized by the user while video is playing.

### Expected behavior

Window to be resized (app not crashing).

### Actual behavior

Application crashes. Segmentation fault shown in the log file.

### Log file

[report.txt](https://github.com/mpv-player/mpv/files/8411108/report.txt)

**Comment by Akemi** [comment]
from your log:

```
[   0.058][w][vo/gpu] opengl cocoa backend is deprecated, use vo=libmpv instead
```
