### ISSUE TITLE
0.34.1 - inconsistent but frequent crash when quitting on macOS

### ISSUE THREAD

**Issue by gokieks** [mpv-player/mpv#10058]
mpv version: 0.34.1 build by stolendata - https://laboratory.stolendata.net/~djinn/mpv_osx/
macOS version: 11.6.5 (x86-64) - note that I am running a hackintosh, but I've been running mpv on such for many years so I do not believe it has any bearing on the issue I'm experiencing.

Reproduction: open any video file and then quit via Cmd-Q.

Expected results: clean exit.

Actual results: frequently, but not every time, the "mpv quit unexpectedly" dialogue will pop up (report attached).  When this happens, next time opening a file in mpv will result in the "The last time you opened mpv, it unexpectedly quit while reopening windows.  Do you want to try to reopen its windows again?" dialogue, which I must then deal with before the new file will play, which is very annoying.

Additional information: on 0.34.0 which I was using previously (also stolendata build), I would also occasionally get the "mpv quit unexpectedly" dialogue, but much less frequently, and when opening a file again would not get the "do you want to reopen windows" dialogue.

Crash log: https://gist.github.com/gokieks/7568d9184e1543a2fe4e248639baf4e2

**Comment by Akemi** [comment]
the crash happens in none mpv code somewhere in the graphics opengl stack. this seems to be an OS/driver bug.
