### ISSUE TITLE
[gpu-next] hdmv_pgs_subtitle wrong subtitles durations

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#10051]
### Important Information

Provide following Information:
- mpv version ```mpv 0.34.0-242-g083ae8e736```
- Windows Version ```Windows 10 Pro x64 21H2 19044.1586```
- Source of the mpv binary ```shinchiro - github``` (https://github.com/shinchiro/mpv-winbuild-cmake/releases)

### Reproduction steps
Set ```vo=gpu-next```
Play mkv file with subtitles as ```hdmv_pgs_subtitle```

### Expected behavior
Subtitles duration should be correct

### Actual behavior
Subtitles duration are not correct

It's easier to see it for yourself (using this script: https://github.com/ekisu/mpv-webm)

https://user-images.githubusercontent.com/13978119/161499812-634929dc-839c-40d8-9880-9ac11edf8641.mp4

https://user-images.githubusercontent.com/13978119/161499844-2a6aab5b-a3d6-4fbd-a07b-52dc532168d6.mp4

It seems like what's happening here is the duration of the subtitle of the top of the screen (signs/songs) is overriting the duration of the low screen subtitles (text).
Or (which I don't think is the case), since there are two subtitle tracks to choose from (```sid=1``` and ```sid=2```), which 1 repesents the full subtitles (signs/songs + text) and 2 repesents only the signs/songs, then it's possible they overlap?

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/8407955/log.txt)

**Comment by Obegg** [comment]
If needed - I can extract the subtitle track from the mkv file using mkvtooltix and upload the final mks file here.

**Comment by ValZapod** [comment]
Same happens in chrome on android that uses ffmpeg in full, so its issue. On the second video the moment "Fairy Tail" vanishes, "Erza ..." comment vanishes, even though it was only present for less than halph a second.

**Comment by Obegg** [comment]
If what you are saying is correct and it's a bug on ffmpeg - I have no idea how to report this issue, [ffmpeg bug reports](https://ffmpeg.org/bugreports.html) are so complicated to read and understand, so, I can't report it.

**Comment by Dudemanguy** [comment]
Could you post a sample of this for testing purposes? I think the linked commit does fix this but not 100% sure.

**Comment by Flo56958** [comment]
> Could you upload a sample of this for testing purposes? I think the linked commit does fix this but not 100% sure.

@Dudemanguy i have two comparisons between your fix and master (video and audio removed)

https://github.com/mpv-player/mpv/assets/13511426/2dcf6b9c-17e4-48f3-ab8a-e6bf4d4d42c6
https://github.com/mpv-player/mpv/assets/13511426/a20d205b-4582-4572-b4ea-ba74b58bcd25

**Comment by Dudemanguy** [comment]
Woops fixed by 02a80f850b5403da89fefed7b32b3f3dfb82f647.
