### ISSUE TITLE
4K. High load and low FPS

### ISSUE THREAD

**Issue by guglovich** [mpv-player/mpv#10064]
### Important Information

Provide following Information:
- mpv version: 034.1
- Linux Distribution and Version: Arch
- Source of the mpv binary: repository
- Window Manager and version: xfwm 4.16.1-3
- GPU driver and version: Mesa 22.0.1-3
- Possible screenshot or video of visual glitches
![изображение](https://user-images.githubusercontent.com/54148165/162285739-8dab9daa-3d62-4f17-9640-de8233f0eb8c.png)

### Reproduction steps

Problem when playing .MOV video with resolution 3840x2160 and bitrate 50015 kb/s, CPU is running at 100%, video and audio are out of sync, video 1-2 FPS. With VLC there is no cpu consumption at all and no load. Apparently, the problem is that the processing is carried out entirely on the CPU

### Expected behavior
Processing should be handled by the video card

### Actual behavior
Low FPS and high load CPU

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/8446153/output.txt)

### Sample files
https://ru.files.fm/f/n3wnm3xva

**Comment by Dudemanguy** [comment]
You just need to enable hwdec (it's off by default). ``--hwdec=auto-safe" or you can hit ctrl+h.

**Comment by guglovich** [comment]
> You just need to enable hwdec (it's off by default). `--hwdec=auto-safe` or you can hit ctrl+h.

Why is such an important option disabled by default and not the other way round?

**Comment by Dudemanguy** [comment]
Compatibility mainly.

>Is it possible to switch on permanently in the config?
Sure. Just ``hwdec=auto-safe`` in your mpv config.
