### ISSUE TITLE
Short question about the mpv info

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#10073]
This video has its filename "Natural World.mkv", and it has inside some video-tracks.
Each video stream has its name, for example the track one is "Naturaleza".
Why does mpv say _unknown_ in each one of them when I change video-track?

![prev](https://user-images.githubusercontent.com/78575427/162594239-772f4f5d-cf6d-4523-8d84-7056a595f0e1.png)

**Comment by hooke007** [comment]
Maybe no metadate.

**Comment by jimmy-1000** [comment]
> Maybe no metadata (vid Language).

I think you are right 👌
