### ISSUE TITLE
vdpau screenshots broken since 0.3.11

### ISSUE THREAD

**Issue by japanese-bird** [mpv-player/mpv#1007]
When the SAR is different from the DAR, mpv with vdpau seems to have some problems taking screenshots now.

Say for example the SAR might be 720x480, and the DAR is 720x540, with vdpau output mpv will play the video correctly at 720x540, but it will produce a 720x540 screenshot with the actual image only being 720x480, and a black bar filling the rest of it to 720x540. This happens with or without vdpau hardware decoding.

Expected result being it takes the screenshot properly at DAR. This happens with every version after 0.3.11.

Happens on ffmpeg-2.3.1 and a version built from git today, and nvidia-drivers-343.13. (Does not happen when using 0.3.11 with these.)

**Comment by markfilipak-windows** [comment]
Apparently, this is broken again.
A snapshot of DVD (720x480) is 720x540 from both the actual DVD & an MKV made from it.
Expected: 720x480.

C:\CMD & tiny apps\MPV>mpv -V
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.19.101
   libavcodec      58.30.100
   libavformat     58.18.100
   libswscale      5.2.100
   libavfilter     7.31.100
   libswresample   3.2.100
ffmpeg version: 4.1+1209.ge320f9576a
