### ISSUE TITLE
MPV not working in TTY with Nvidia gpu

### ISSUE THREAD

**Issue by FilippoMutta** [mpv-player/mpv#10074]
### Important Information
mpv 0.34.1-4 directly from the Arch repos.
Arch Linux 5.16.4.-arch1-1
Nvidia GPU driver 510.60.02-11
Using Nvidia DKMS 510.60.02-1

### Reproduction steps
1. Using KMSCON, logging in.
2. Typing "mpv --no-config --vo=drm --log-file=mpv.log video.mp4"
### Expected behavior
The video should play
### Actual behavior
Obtaining error and no video or audio output:
> [vo/drm] VT_GETMODE failed: Inappropriate ioctl for device
> [vo/drm] Failed to set up VT switcher. Terminal switching will be unavailable.
> [vo/drm] Cannot set CRTC: Invalid argument
> Error opening/initializing the selected video_out (--vo) device.
### Log file
[mpv log file](https://0x0.st/obD4.log)
### Sample files
Any H.264 will do.

**Comment by sfan5** [comment]
You need to enable this feature in the driver: https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting

**Comment by FilippoMutta** [comment]
> sfan5

Had already enabled it.

**Comment by sfan5** [comment]
Kmscon probably prevents other applications from using DRM then? I can only say this works fine for me.

**Comment by FilippoMutta** [comment]
> Kmscon probably prevents other applications from using DRM then? I can only say this works fine for me.

You're right about that. Tried with getty, it works fine!
