### ISSUE TITLE
Segmentation fault with lavfi-complex

### ISSUE THREAD

**Issue by Dudemanguy** [mpv-player/mpv#10079]
### Important Information
- mpv version: mpv 0.34.0-253-g2cafe5137f (git master)
- If known which version of mpv introduced the problem: f61eda0f5e9f8085003c4c31111db525a438cbc1
- Window Manager and version: Sway 1.7
- GPU driver and version: amdgpu 

### Reproduction steps
Use lavfi-complex with an image or video. eg:
```
mpv --no-config --lavfi-complex='[vid1] [vid2] vstack [vo]' image.png --external-file=image.png
```

### Expected behavior
The image/video is stacked vertically.

### Actual behavior
mpv segfaults. It seems like `vo` is NULL here when you trigger lavfi-complex. The line that triggers this is:
https://github.com/mpv-player/mpv/blob/2cafe5137f1544df130face8f748cc571ddf0445/video/decode/vd_lavc.c#L703

This stupid patch stops it from crashing but it would mean no film grain with lavfi complex.
```
diff --git a/video/decode/vd_lavc.c b/video/decode/vd_lavc.c
index 9fb7b7cd2a..1684c14856 100644
--- a/video/decode/vd_lavc.c
+++ b/video/decode/vd_lavc.c
@@ -700,7 +700,7 @@ static void init_avctx(struct mp_filter *vd)
         av_opt_set(avctx, "x264_build", "150", AV_OPT_SEARCH_CHILDREN);
 
     if (ctx->opts->film_grain != 0 /*CPU*/) {
-        if (p->vo->driver->caps & VO_CAP_FILM_GRAIN) {
+        if (p->vo && p->vo->driver->caps & VO_CAP_FILM_GRAIN) {
             avctx->export_side_data |= AV_CODEC_EXPORT_DATA_FILM_GRAIN;
         } else if (ctx->opts->film_grain == 1 /*GPU*/) {
             MP_WARN(vd, "GPU film grain requested, but VO does not support "
```
A workaround for now is to use `--vd-lavc-film-grain=cpu`.

### Log file
[Log file](https://0x0.st/ob7v.log)

**Comment by Warblefly** [comment]
Also crashing on mingw-w64 Windows 11 with lavfi-complex. About to test the patch, above.

**Comment by jeeb** [comment]
The decoder probably gets initialized before the VO is initialized, and thus there is a segfault most likely.
