### ISSUE TITLE
Want old timeline back

### ISSUE THREAD

**Issue by unculcated** [mpv-player/mpv#10071]
### Important Information

**Provide following Information:**

iMac (Retina 4K, 21.5-inch, 2017)
mpv 0.32.0-750-ge1536193cb
macOS Version Monterey 12.3

source -  https://github.com/jnozsc/mpv-nightly-build

 **HERE IS THE QUESTION**

**How do I get the simple timeline back instead of the one I have below??**

![new timeline](https://user-images.githubusercontent.com/12836650/162591280-06d7eeee-d08b-46b8-a8b8-5d65058d2f01.png)

**The one I want below**

![mpv-screenshot-34cd36ae](https://user-images.githubusercontent.com/12836650/162591275-82717f00-abf5-4cbc-9d84-363a8e5c2591.jpg)

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#on-screen-controller-layout

**Comment by unculcated** [comment]
I just put these in my conf and it did not work

--script-opts=osc-layout=slimbox

--script-opts=osc-seekbarstyle=bar

**Comment by hooke007** [comment]
I do not let you set `slimbox`
Just need to 
> delete script-opts=osc-layout=box

to recover to `bottombar`

**Comment by unculcated** [comment]
Didn't work. Here is my conf file

# place this file in ~/.mpv/
# gpu high profile with even more quality scalers
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell

delete script-opts=osc-layout=box

# color
icc-profile-auto



# osc use box
script-opts=osc-layout=box

tscale=box
tscale-window=quadric
tscale-clamp=0.0
tscale-radius=1.02



# If the video is larger than 90% of the screen width or 80% of the screen height, make the window smaller until either its width is 90% of the screen, or its height is 80% of the screen.
autofit-larger=90%x80%

# HEVC hardware decoder
hwdec=auto

# try to fix retina scale
hidpi-window-scale=yes

# Deactivates the automatic graphics switching and forces the dedicated GPU.
macos-force-dedicated-gpu=yes

# hdr, well not work
#target-peak=450
#tone-mapping=mobius

**Comment by hooke007** [comment]
Why added `delete script-opts=osc-layout=box` in your conf?

You only need to remove `script-opts=osc-layout=box`.

**Comment by unculcated** [comment]
whew, I was getting lost. Thank you!!!
