### ISSUE TITLE
Random lagging/stuttering issue

### ISSUE THREAD

**Issue by naufalkharits** [mpv-player/mpv#10081]
### Info
- Use [mpvnet 5.7.0.0](https://github.com/stax76/mpv.net/releases/tag/v5.7.0.0) as frontend
- Use [libmpv DLL](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/) build by shinchiro

### Specs:
- Windows 11
- i7 8750H
- 1070 Max-Q

### mpv.conf file
[mpv.zip](https://github.com/mpv-player/mpv/files/8463127/mpv.zip)

---

### Issue
So, been while I'm not updating my mpvnet (5.4.9.0).
Deciding to update to the latest version (5.7.0.0), which uses the new dll: mpv-2.dll.

I got a random stuttering issue with the new version, the video sometimes lags about 1-sec.
I have no idea why that happen, but I tried as [suggested by mpvnet builder](https://github.com/stax76/mpv.net/issues/404#issuecomment-1094218490) to replace the new DLL with the old one.
Problem solved, then I tried more deep testing, and I found that [mpv-dev-x86_64-20210919](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/) is the limit. Above this version will produce this issue.

Testing with 2 methods:
1. Use default settings with changed the lang setting (see the config file that I attached before).
2. Same as default settings, with additional changes the hwdec set to "Yes". (doesn't have any impact, still the same).

**Comment by CounterPillow** [comment]
Where is your config file? Also, we cannot help you if you can't reproduce your issue in mpv proper.

**Comment by GitNaufal** [comment]
Sorry, my bad.
I'll repeat.

**Comment by GitNaufal** [comment]
### Important Information

Provide following Information:
- mpv.net 5.7.0.0
- mpv 0.34.0-208-gb1fb4b783b
- Windows 11 22000.593

### Reproduction steps
1. Tested with 2 videos from different sources (online and offline).
- Online source from indexes & offline source from my external HDD.
- Both have a stuttering issue.
- See the log, I attached both.

2. Tested with --no-config first.
- No impact, still the same.
- Sorry no log for this one at the moment, I forgot to activate the log.

### Expected behavior
Video will not be stuttering, both online & offline.

### Actual behavior
Video has random stuttering, minor, but it is noticeable. So annoying for a smooth experience..

### Log file

[online.txt](https://github.com/mpv-player/mpv/files/8466656/online.txt)
[offline.txt](https://github.com/mpv-player/mpv/files/8466657/offline.txt)

**Comment by JayXT** [comment]
I've got the same issue with mpv player. With upgrade to Debian 12 and mpv 0.35.1 from the official repositories, occasionally video lags for a couple of seconds here and there. It stabilizes if I put video on pause and replay the same fragment, or sometimes by itself. But without exception it happens sporadically again and again.

**Comment by naufalkharits** [comment]
> I've got the same issue with mpv player. With upgrade to Debian 12 and mpv 0.35.1 from the official repositories, occasionally video lags for a couple of seconds here and there. It stabilizes if I put video on pause and replay the same fragment, or sometimes by itself. But without exception it happens sporadically again and again.

Do you have tried different version?

**Comment by JayXT** [comment]
No, I plan to use only the version from the official repos. Besides, as far as I know, it's currently the latest stable release of mpv.

**Comment by naufalkharits** [comment]
> No, I plan to use only the version from the official repos. Besides, as far as I know, it's currently the latest stable release of mpv.

The idea of trying different version is to find the latest build that your system can run mpv without any issues. Or you can try the nightly one.

**Comment by JayXT** [comment]
Using hwdec=auto option at first sight seemed to solve the stuttering problem in my case. Other options that might help I'm going to add if the issue gets reproduced again are:

pulse-latency-hacks=yes
demuxer-readahead-secs=5

I'm not sure why hwdec is set to no by default. In 2023 it only makes sense to take advantage of hardware decoders.

**Comment by CounterPillow** [comment]
> I'm not sure why hwdec is set to no by default. In 2023 it only makes sense to take advantage of hardware decoders.

Then tell hardware vendors to make less buggy hardware decoders instead of queefing about how it's le current year.

**Comment by CounterPillow** [comment]
mpv already has several mechanisms to only select some hwdecs and only for some codecs (hwdec=auto-safe, hwdec-codecs=), so those could be adjusted, but the bigger issue is that one person's experience doesn't mean that the defaults should be changed when things like hwdec still manage to cause GPU resets, or on some systems cause implicit YUV-to-RGB conversion with probably bilinear chroma upscaling. Reporting a bug for those doesn't mean the hardware or drivers will magically change. AMD's driver team is too busy adding a buggy HDR implementation, and the yuv-to-rgb stuff in some other vendors (i forget who) decoder paths is probably a hardware limitation.

**Comment by Jules-A** [comment]
> mpv already has several mechanisms to only select some hwdecs and only for some codecs (hwdec=auto-safe, hwdec-codecs=)

Oh wow, I must be blind, I completely missed that... That said afaik it doesn't support using a different types of hwdec for specific codecs?

**Comment by Dudemanguy** [comment]
Is this still an issue on an up to date mpv?

**Comment by naufalkharits** [comment]
No update, switched to mpv instead mpvnet.
I'll close this issue, thank you.
