### ISSUE TITLE
GPU-NEXT error message.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#10083]
### Important Information

Provide following Information:
- mpv version: mpv-build-git
- Linux Distribution and Version: Arch
- Source of the mpv binary: AUR
- If known which version of mpv introduced the problem: git
- Window Manager and version: Mutter42.0
- GPU driver and version: Mesa Gallium driver 22.0.1 for AMD Radeon RX 580 Series (polaris10, LLVM 13.0.1, DRM 3.44, 5.17.1-zen1-1-zen)
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

```mpv --no-config --vo=gpu-next <video>```

### Expected behavior

No error message.

### Actual behavior

```[vo/gpu-next] Tried calling `pl_swapchain_resize` with unknown size! This is forbidden for OpenGL. The first call to `pl_swapchain_resize` must include the width and height of the swapchain, because there's no way to figure this out from within the API.```

### Log file

[gpu-next.txt](https://github.com/mpv-player/mpv/files/8465874/gpu-next.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Dudemanguy** [comment]
Seems to be gnome and wayland specific. Fortunately harmless otherwise.

**Comment by Dudemanguy** [comment]
So this is funky. `vo=gpu` also does a 0x0 resize but it doesn't log anything in this case. I haven't yet figured out why `vo->dwidth/dheight` is 0 at this stage in wayland but in xorg it's the actual value. Very odd.

**Comment by lavilao** [comment]
Oh I also get this error but its harmless aparently
