### ISSUE TITLE
feature: subtitle delay / sub-step reset

### ISSUE THREAD

**Issue by chapmanjacobd** [mpv-player/mpv#10087]
### Expected behavior of the wanted feature
Sometimes I accidentally trigger the very useful sub-step feature. 

I want to bind a button that will reset the subtitle delay to `0 ms`

### Alternative behavior of the wanted feature
I tried the following but it didn't seem to work...

```
# input.conf
Ctrl+DOWN sub-delay 0 # reset subtitle delay (?)
```

**Comment by Dudemanguy** [comment]
I think you want:
```
Ctrl+DOWN set sub-delay 0
```
