### ISSUE TITLE
gpu-next: audio only files get 180° rotated video

### ISSUE THREAD

**Issue by mxsrm** [mpv-player/mpv#10095]
### Important Information

Provide following Information:
- mpv 0.34.0-264-g1a597ea987
- EndeavourOS Linux / ArchLinux @ 5.17.2-arch3-1
- AUR mpv-git
- xfce 4.16

### Reproduction steps

`mpv --no-config --force-window --vo=gpu-next audio_only_file.opus`

### Expected behavior

The GUI is correctly oriented.

My other system is a MacOS one, so I have no other version with `gpu-next` to test. That's why I added "os:linux".

### Actual behavior

The GUI is rotated by 180°:

![gpunexterror](https://user-images.githubusercontent.com/7951225/163257806-095dac52-de69-474c-a9b8-42474e9a287e.png)

`--vo=gpu` works as expected.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/8484236/log.txt)

### Sample files

Any audio only files work.

**Comment by quietvoid** [comment]
FWIW this doesn't happen if mpv picks up an album cover in the same directory as the audio file.
So `--force-window` causes this.

**Comment by mxsrm** [comment]
Starting it from thunar / folder and not from console triggers this too (without explicit `--force-window`).

Tested with a fresh `mpv` folder and `mpv.conf` only containing

`vo=gpu-next`

**Comment by BlueSwordM** [comment]
Yeah, I also have a similar issue. I was wondering why I was getting an issue for albums without covert art, and no issues for those with cover art :)

**Comment by ValZapod** [comment]
Flip presentation, looks like same happens here: https://bes.github.io/chrome-video-stutter/

haasn already fixed something like this.

**Comment by BlueSwordM** [comment]
This issue has been fixed with git mpv and ffmpeg.

We can close this now.

**Comment by quietvoid** [comment]
It's not fixed for me on 9ffaa6b81b.

**Comment by christoph-heinrich** [comment]
Still not fixed in the latest master b29878e3a19fa944b9ef044b9cef776ab3c89af7. I was about to open an issue about this.
The image is not rotated 180° but flipped horizontally.
Minimal reproduction example: `mpv --no-config --idle=yes --force-window=yes --vo=gpu-next`

**Comment by quietvoid** [comment]
This has been fixed by https://github.com/haasn/libplacebo/commit/669139cd48424821c3adc57c61d6bc265631e69a

**Comment by mxsrm** [comment]
I can confirm that as of today libplacebo+git + mpv-git fixed the bug.
