### ISSUE TITLE
How to make conditional auto profiles that matches to both video name and pixel format?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#10099]
Hi,

I am trying to create conditional profile that will only use my custom deband
**only** if it matches to both video name and pixel format.
İf someone could please help me I would appreciate it.

I did try myself. 
To make one but it didn't work.

```
[Summertime Rendering gpu-hq]
profile-cond=string.match(get("filename", ""), "%[SlyFox%] Summertime Rendering")~=nil and p["video-params/pixelformat"]~=yuv420p
profile=DebandProfile
```

**Comment by hooke007** [comment]
```
profile-cond = filename:match("%[SlyFox%] Summertime Rendering")~=nil and p["video-params/pixelformat"]~="yuv420p"
```

**Comment by erickyun** [comment]
> ```
> profile-cond = filename:match("yourfilename")~=nil and p["video-params/pixelformat"]~="yuv420p"
> ```

it isn't working like I want.
With this if the file name matches the profile will be excuted even if the pixelformat is yuv420p10.

I want the profile only be excuted if matches both filename and pixelformat.

Example:
mpv.conf:
```
profile-cond = filename:match("Summertime")~=nil and p["video-params/pixelformat"]~="yuv420p"
```

and the file I play name is Summertime.mkv but pixelformat is yuv420p10 .
I want mpv to not excute the profile because pixelformat does not match.

**Comment by hooke007** [comment]
I am confused that you show the example `p["video-params/pixelformat"]~="yuv420p"` (`~=` means **not equal to**).

you should write `p["video-params/pixelformat"]=="yuv420p"` to match yuv420p

**Comment by erickyun** [comment]
> I am confused that you show the example `p["video-params/pixelformat"]~="yuv420p"` (`~=` means **not equal to**).
> 
> you should write `p["video-params/pixelformat"]=="yuv420p"` to match yuv420p

I didn't notice it.
Thanks that worked. :)
