### ISSUE TITLE
vo_gpu-next: Scaled subtitles appearing more transparent when resized.

### ISSUE THREAD

**Issue by TemAccount** [mpv-player/mpv#10098]
### Important Information

Provide following Information:
- mpv 0.34.0-265-g305332f8a0
- Windows 11 22H2 (OS Build 22598.1)
- [Source of the mpv binary](https://github.com/zhongfly/mpv-winbuild/)

### Reproduction steps

mpv.conf
```
vo=gpu-next
profile=gpu-hq
```

* Launch a 1080p video with .ass subtitles. 
* Go fullscreen, scaling the subtitles to 2560x1440
* Subtitle sign goes transparent.

### Expected behavior
Subtitles to not get _more_ transparent when scaling / resizing larger. To have similar behavior to current default ``vo=gpu``.

### Actual behavior
Subtitle sign becomes transparent.

With ``vo=gpu-next`` set.
![link](https://i.imgur.com/vwwIod3.png)

No ``vo=gpu-next`` set, using the default ``vo=gpu``.
![link2](https://i.imgur.com/A7GsJop.png)

Displaying without scaling the video/subs larger (no fullscreen) shows the subtitles fine. Similarly, removing ``profile=gpu-hq`` with ``vo=gpu-next`` present _while going fullscreen_ seems to fix the problem. So perhaps indication custom settings / scalers set don't play nicely with resizing subtitles on gpu-next.

### Sample files

```
Dialogue: 0,0:00:00.00,0:00:02.98,Basic_Sign,Text,0,0,0,,{\fs16\u1\be1}Imperial Capital Odin\N{\fs20\u0\b1}Imperial Navy Fleet Admiral's Mansion
```

[Legend of the Galactic Heroes - Die Neue These - 29 (1080p) [60F42AC7]_track3_eng.zip](https://github.com/mpv-player/mpv/files/8495795/Legend.of.the.Galactic.Heroes.-.Die.Neue.These.-.29.1080p.60F42AC7._track3_eng.zip)

**Comment by hooke007** [comment]
Looks like the thicker/deeper border/shadow.

**Comment by haasn** [comment]
I can't reproduce this. Is it still an issue?
