### ISSUE TITLE
Subtitles are not visible over black bars with vo=gpu-next & video-sync=display-resample

### ISSUE THREAD

**Issue by mnisius** [mpv-player/mpv#10105]
### Important Information

Provide following Information:
- mpv version: mpv-x86_64-20220416-git-305332f
- Platform and Version: Windows 10
- Source of the mpv binary: shinchiro 

### Reproduction steps
Play a Video with back bars on full screen or with maximized window
and add this 2 options to your config : 
 vo=gpu-next & video-sync=display-resample

### Expected behavior
Subtiles are visible 

### Actual behavior
Subtiles are hidden behind the black bars  

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/8500469/output.txt)

Here are 2 Screenshots to show the issue. First Screenshot shows that subs are visible if there are no black bars and on the second shot you can see the subtitle behind the black bar. 
![visible](https://user-images.githubusercontent.com/56688244/163687947-3d4c349d-03d8-4530-8a90-3c9fa66602e6.png)
![invisible](https://user-images.githubusercontent.com/56688244/163687950-0bc9ddb1-5326-4f70-bcaa-cb22dd6e0aad.png)

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/9923 https://github.com/mpv-player/mpv/issues/9928

**Comment by mnisius** [comment]
Is there any workaround for this? Can I somehow force the subtitles to be displayed in the visible portion of the video? And will there be a fix for this? Because this makes vo=gpu-next  more or less unusable for me because I always watch with subtitles and many videos have black bars...

**Comment by hooke007** [comment]
sub-use-margins=no

**Comment by Dudemanguy** [comment]
Closed since it's a duplicate.
