### ISSUE TITLE
Cache is only filled when video is paused

### ISSUE THREAD

**Issue by Temtaime** [mpv-player/mpv#10108]
### Important Information

Provide following Information:
- mpv version **master**
- Windows Version **11**
- Source of the mpv binary **Windows builds by shinchiro**
- If known which version of mpv introduced the problem **no**
- Possible screenshot or video of visual glitches **none**

### Reproduction steps
Try to play a file from samba network drive.

### Expected behavior
It plays smoothly, cache is always full and filled on about ~100 mbit/s.

### Actual behavior
It shutters and freezes, network activity is 3mbit/s.
When video is paused, cache is populated at ~100 mbit/s. Playing from cache is OK, but cache is running out soon.

### Log file
Which options should i use to collect a log file?

### Sample files
Don't think that it is relevant.

**Comment by Hrxn** [comment]
> Try to play a file from samba network drive.

I think you might need to be a bit more specific here..

What system, which SMB protocol version, some protocol settings, maybe?

**Comment by Temtaime** [comment]
Hello.
Samba PC is ubuntu 20.04. smb v2.
PC where i'm trying to run mpv is windows 11.

```
[global]
        log file = /var/log/samba/log.%m
        max log size = 50

        read raw = yes
        write raw = yes
        use sendfile = yes
        socket options = TCP_NODELAY

        map to guest = Bad User
        acl allow execute always = True

        oplocks = yes
        level2 oplocks = no

        printing = bsd
        printcap name = /dev/null

        ea support = no
        map hidden = no
        map system = no
        map archive = no
        map readonly = no
        store dos attributes = no

        strict locking = no
        kernel change notify = no

[pub]
        path = /share/pub
        guest ok = yes
        read only = no
        force user = qbittorrent
        force group = qbittorrent
```

**Comment by garoto** [comment]
Going on a stretch here, but perhaps a bus bottleneck between the audio chip and the network controller is taking place? I had lots of weird audio crackling and popping with underruns being logged in mpv console, when playing media from a HTTP server at ~300mbit/s while using my mobo PCI-connected PHY Realtek interface. Switching to the Intel one that sits on a PCIe bus in the same mobo fixed the issue for me.

**Comment by Temtaime** [comment]
Thanks, i'll provide logs in days.
I don't think it is a case for me.
I think the problem is that mpv generates too many seeks and/or tries to read very small blocks from file when playing video. Is there any way it can bypass a cache?

**Comment by garoto** [comment]
Perhaps investigate `--stream-buffer-size`, since the option was concocted from a very busy issue dealing with CIFS poor performance (https://github.com/mpv-player/mpv/issues/7408 and https://github.com/mpv-player/mpv/issues/6802).
