### ISSUE TITLE
change the "log 2" in document to "log(2)" or "logarithm of 2"

### ISSUE THREAD

**Issue by rezad1393** [mpv-player/mpv#10100]
in this section:
```
--video-zoom=<value>

    Adjust the video display scale factor by the given value. The parameter is given log 2. For example, --video-zoom=0 is unscaled, --video-zoom=1 is twice the size, --video-zoom=-2 is one fourth of the size, and so on.
```
this way user when user wants to search for it it doesn't get confused with log ,as in record.

**Comment by Dudemanguy** [comment]
"log 2" and so on is pretty common math terminology. One could make it more explicit I suppose, but the following sentence explains it pretty clearly, so I don't think there's a need.

**Comment by rezad1393** [comment]
yes and no.
log 2 in math means nothing.
log 2 in nowadays word is actually means log(2) which is log of number 2 in base of 10, or the number that 10 needs to be raised to that power to result is 2.
which is different from what you mean, because you mean log of a number in base 2. which is a number that 2 needs to be raised to that power to result is the intended zoom level.
even I reported it wrong.
I should have written log2(Z) with Z for zoom level, or something like that.

**Comment by rezad1393** [comment]
that's why I asked for normal zoom levels option instead of logarithm in option.
is log is required in internal mpv (I am not a programmer so I don't know why log is needed but I assume it is)
then just use a normal level facing user then internally convert it to log.

**Comment by Dudemanguy** [comment]
It was implemented on a log scale in this commit: https://github.com/mpv-player/mpv/commit/c0e13d54a85663ff8ac87d2910f1688978ea1f60. Basically the reasoning is that it made the zooming behavior more consistent and predictable.

**Comment by rezad1393** [comment]
> It was implemented on a log scale in this commit: [c0e13d5](https://github.com/mpv-player/mpv/commit/c0e13d54a85663ff8ac87d2910f1688978ea1f60). Basically the reasoning is that it made the zooming behavior more consistent and predictable.

having read that I understand that user wanted incremental increases so a logarithmic method was used but I dont understand the reason that integer or percentage option was removed.
and I dont understand what is good about ( It coincidentally also makes it
really easy to get clean power of 2 ratios (e.g. 2x, 4x, 8x and their
inverses).

**Comment by rezad1393** [comment]
![chart](https://user-images.githubusercontent.com/7523164/163623848-2c0b6d1c-ef86-4d35-94d6-ba2ac3c01427.png)

**Comment by haasn** [comment]
It could be changed from "log 2" to "log base 2", I suppose. I personally think this usage is common and clear enough as it is, but I don't see the harm in either variant.

**Comment by emanuele6** [comment]
"log base two" sounds weird, "log two" is the common way of referring to the logarithmic scale and logarithm function in base 2.
I would never interpret "log 2" logarithm of the value 2 (especially not in base 10).
In mathematics and technical fields, people usually call `log(x)` "log of x" and assume base `e`, they don't call it "log x" (which would be intereted as "logarithm in base x (of ...)") and assume base 10.

**Comment by rezad1393** [comment]
https://www.google.com/search?q=log+2
0.30102999566

**Comment by emanuele6** [comment]
Your base10 vs base-e argument is kind of irrelevant (scientific calculators also use `ln` and `log`, and have done so for a very long time).

In my comment, I have noted that it is fair, to think of "log 2" as "logarithm of 2" if it's an expression (the parentheses are omitted in this case) and not prose, that is clearly the case for your google calculator example.

> you can use log2(x) and that would be better.

> my main point that got lost in the argument was for replacing the word log with logarithmic.

That doesn't make sense, I think you are not understanding that "log 2" is referring to a logarithmic scale in that sentence, not to the logarithm function with base2, the "log 2 scale"; "this value is in log x" is common ways of saying that a value is scaled using a certain logarithmic function.

We can reword the sentence to make it more clear, but we shouldn't make up terminology that means nothing and nobody will understand: "the parameter is given logarithmic 2".

> > Adjust the video display scale factor by the given value. The parameter is given log 2.
> 
> You may interpret "log 2" as "the logarithm of 2" if you think "log 2" is not prose, but a mathematical expression, but in this sentence, it doesn't make much sense to think that "log 2" refers to the constant value of "the logarithm of 2", it is clearly referring to the logarithmic scale, in my opinion.

Also, as I said, I really don't get how you can think that "log 2" is a constant in this context...

**Comment by ValZapod** [comment]
ISO standards specify ln as base e, lg as base 10, log as base 2 and log_base as everything else. Everything else, especially how number theory people do it and how USA does it is wrong. Alsways has been.

**Comment by rezad1393** [comment]
can the word log be replaced with the word logarithm?
that's all.

**Comment by rezad1393** [comment]
> ISO standards specify ln as base e, lg as base 10, log as base 2 and log_base as everything else. Everything else, especially how number theory people do it and how USA does it is wrong. Alsways has been.
> 
> > "log base two" sounds weird, "
> 
> No, you saying it sounds weird sounds weird.

If you really really believe that, you can prove it and remove the 2 from the docs.
the everybody would see the "log" and would according to "_ISO standards_" understand that it mean log 2 and nothing else.

I am not an American. but I know that many math professors and asked them if log with no number meant 2 and those who answered, asked for "log in what base?"

I just asked for change in docs of mpv, from word log to word logarithm. because I wanted to search code for the logarithmic part and had to search for the word log. which was not the log I needed cause the code if full of the words log which means "records" not the math abbreviation of logarithm.

I am gonna unfollow this ticket. it seems that changing a word or adding parentheses is akin to killing a baby here.
