### ISSUE TITLE
Feature request: Integer zoom levels that are not powers of 2

### ISSUE THREAD

**Issue by rezad1393** [mpv-player/mpv#10101]
based on my issue here
https://github.com/mpv-player/mpv/issues/10097
I need to be able to zoom video at integer levels, but mpv only allows cycling zoom levels with option that are log(2) of zoom levels.
so 
0> no zoom
1> zoom at 2X
2> zoom at 4X

but as explained on that issue referenced at top, for a 600x350 video to zoom to 3X n in cycling or any other video that I need to zoom to 3X there is no option.
can this be fixed?
I imagine that this is not a fundamental thing and just a choice made by devs, so can you change this so users can zoom at whatever levels they want?

**Comment by Dudemanguy** [comment]
You can pass float values to `--video-zoom` so it can be anything within log2(-20) and log2(20).

**Comment by rezad1393** [comment]
> You can pass float values to `--video-zoom` so it can be anything within log2(-20) and log2(20).

the log2(3) would not be exact right?

**Comment by rezad1393** [comment]
also the issue I raised in that ticket about integer zooms, am I correct about it and image fidelity? 
as in non integer zoom can lead to not perfect pixel match? as zoom-outs already do.
