### ISSUE TITLE
Why does GPU-NEXT change brightness immedietly for HDR movies?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#10106]
In the past, we noticed that it looked bad when we were watching HDR videos, but GPU-NEXT does it again, why?
The brightness/gamma stuff changes dramatically, at least it is noticeable, it is really unnatural.

**Comment by LaserEyess** [comment]
It's really hard to understand what you're talking about without, a the very least, a single picture. But have you [read this](https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU) to see if one of the points there is what you're seeing?

**Comment by Doofussy2** [comment]
Sounds like `hdr-compute-peak`

**Comment by laichiaheng** [comment]
> It's really hard to understand what you're talking about without, a the very least, a single picture. But have you [read this](https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU) to see if one of the points there is what you're seeing?

allow-delayed-peak-detect
It doesn't act like vo=gpu does.
