### ISSUE TITLE
Raised blacks with Inverse tone mapping bt.2446a

### ISSUE THREAD

**Issue by carycary246** [mpv-player/mpv#10113]
Wondering if this is the intended behavior with the inverse tone map. Tested this config on an LG C1 oled and noticed that with inverse tone mapping enabled, the blacks were not true black compared to just playing it normally in SDR. The blacks look slightly lifted, similar to how an IPS panel looks which ruins the contrast of the image.

vo=gpu-next
profile=gpu-hq
gpu-api=d3d11
gpu-context=d3d11
d3d11-output-format=rgb10_a2
d3d11-output-csp=pq
tone-mapping=bt.2446a
inverse-tone-mapping=yes
dither-depth=10
target-trc=pq
target-prim=bt.2020
target-peak=800

**Comment by Doofussy2** [comment]
You're confusing metadata passthrough and tone-mapping. Tone-mapping doesn't use `pq` transfer. The `d3d11-output` should be negated, both lines. And `target-trc`. Windows is gonna get all kinds of confused.

**Comment by carycary246** [comment]
> 

From what I tried with your suggestion, negating the d3d11-output lines has no effect on raised blacks and target-trc is necessary for the colors to display properly. If the issue is with metadata, then is there a function that allows it to passthrough without raising black floor?

**Comment by Doofussy2** [comment]
You need to choose between letting your TV use the metadata and mpv tone mapping.  I'd suggest letting your TV do the work.

Are you running Windows in HDR?

If in HDR, just use:

```
vo=gpu
profile=gpu-hq
gpu-api=d3d11
gpu-context=d3d11
d3d11-output-format=rgb10_a2
d3d11-output-csp=pq
target-trc=pq
target-prim=bt.2020
```

If you want tone-mapping, try:

```
vo=gpu-next
profile=gpu-hq
gpu-api=d3d11
tone-mapping=bt.2446a
inverse-tone-mapping=yes
dither-depth=10
target-prim=bt.2020
target-peak=800
```

You can't mix them. The Windows swapchain will make a mess. Tone-mapping is always to SDR. And the target peak will be subjective.  

I really don't understand why you want to tone-map, if you have an HDR TV and run Windows in HDR. Tone-mapping is necessary when metadata passthrough isn't possible. Your LG OLED TV will do the best job at applying the metadata, correctly.

**Comment by carycary246** [comment]
Thanks for the clarification. HDR is on in Windows but the idea with the inverse tone mapping is to expand the SDR to make greater use of the HDR range, similar to the effect of Window's auto HDR in games to achieve more impactful highlights. 

I tested both outputs with your suggested config but seems both result in lifted blacks. In the second config with tone mapping, colors are washed out and not correct.

**Comment by Doofussy2** [comment]
So this is about SDR to HDR?

**Comment by Doofussy2** [comment]
I'm not sure hassn has adjusted the black point for that use case.

**Comment by carycary246** [comment]
I see, so no way to correct this unless the black point is adjusted. Hopefully hassn will be able to take a quick look at this as from my understanding, it would just need to match the black point of the original metadata to prevent the raised black floor.

**Comment by quietvoid** [comment]
Since you say this happens in regular HDR (passthrough?), it's possible the default black point is simply defaulted to something non-zero.
IIRC, it might default to 0.005 nits for output in PQ. At least that's the behaviour in `plplay`.

**Comment by ValZapod** [comment]
> , it might default to 0.005 nits for output in PQ. At least that's the behaviour in `plplay`.

That is horrible. BT.709 is scene refferred, so no black point defined, it is just blackest black so 0.0001 nits in PQ. With Adobe RGB and sRGB that are display referred there is a black pont defined, for Adobe RGB 0.5557 cd/m2 at the black point.

**Comment by hengyu95** [comment]
I'm curious if you managed to get anywhere with this?

I also noted this option in the documentation:

--inverse-tone-mapping
If set, allows inverse tone mapping (expanding SDR to HDR). Not supported by all tone mapping curves. Use with caution. (--vo=gpu-next only)


But I've got no luck with getting any SDR content to look right in HDR mode. Not sure how this flag is supposed to work here.

**Comment by mnisius** [comment]
@carycary246 

just add 

`target-colorspace-hint=yes`

to your config you will get true black and a working SDR to HDR Conversation

**Comment by haasn** [comment]
The output levels are now correctly tagged on the swapchain, the same as happens for native HDR video.

**Comment by haasn** [comment]
After more discussing it seems as this may not be enough, because some monitors do not correctly tone-map the black point *down* as intended. I will fix it in a different way.

**Comment by f7el** [comment]
@mnisius my subtitles are looking like this. is that something mpv can improve?
![image](https://github.com/mpv-player/mpv/assets/10247894/50631e9b-5709-4c32-882a-160937b157c7)

**Comment by f7el** [comment]
it actually looks more gray on the video vs the screenshot
