### ISSUE TITLE
Audio/Video desynchronisation messages by seeking through frames.

### ISSUE THREAD

**Issue by Roseoid** [mpv-player/mpv#10121]
### Important Information

Provide following Information:
MPV Version: 0.34.0
Microsoft Windows 11 Home Version 10.0.22000 Build 22000
Chocolatey
N/A
![image](https://user-images.githubusercontent.com/90016591/164354759-d3b275db-66b3-44ad-999f-3e2a2fe68c07.png)

### Reproduction steps

1. Open the video
2. Seek through frames ( , and .)

### Expected behavior
Outputs no warning messages.

### Actual behavior
Outputs "Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field)."

### Log file
https://0x0.st/oT8k.txt

### Sample files
N/A

(If desynchronization is already resolved after seeking through frames, then in my opinion it still isn't necessary to output the message.)

**Comment by probe2k** [comment]
I'd say, the issue still persists with the latest version of mpv.

**Comment by outragedline** [comment]
it still happens to me in mpv and in vlc, i think its because of the video resolution but i dont know how to change the resolution of a file

**Comment by Dudemanguy** [comment]
Old + can't reproduce still so closing.
