### ISSUE TITLE
unable to load the non-UTF-8 ass subtitles

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#10120]
### Important Information

Provide following Information:
- mpv version
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20220420
- Windows Version
win11 release
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20220420
- If known which version of mpv introduced the problem
N/A
- Possible screenshot or video of visual glitches
https://github.com/libass/libass/issues/614

### Reproduction steps

run mpv and load the subtitle.

### Expected behavior

subtitles successfully loaded.

### Actual behavior

Loaded failed.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/8524942/mpv.log)

### Sample files

[test.ass.zip](https://github.com/mpv-player/mpv/files/8524946/test.ass.zip)

**Comment by thebombzen** [comment]
Did you try `--sub-codepage`?

**Comment by hooke007** [comment]
fixed by ffmpeg.
