### ISSUE TITLE
"HDR peak" in display stats uses unclear unit

### ISSUE THREAD

**Issue by dechamps** [mpv-player/mpv#10127]
mpv 0.34, Windows 11, all defaults, HDR output

In the display stats (using the `i` key, `stats/display-stats` script binding), the "HDR peak" value (which I assume is the peak luminance value sent as metadata to the display) uses an unspecified, unclear exotic unit.

It looks like the units is nits divided by 203 - so 1000 nits is 4.93, 4000 nits is 19.7, and 10000 nits is 49.3. This is very obscure and confusing.

It would be nice if the value shown was expressed in nits directly.

**Comment by haasn** [comment]
I actually agree. In `vo_gpu_next` we switched to using nits everywhere. The stats display just hasn't really been updated as it's still based on the `vo_gpu` architecture.

The reason for these 'exotic' values is that it's relative to the SDR peak. So an SDR value has a brightness of 1.0.
