### ISSUE TITLE
gpu-dumb-mode unnecessarily gets disabled by video-sync=display-resample

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#10135]
When I play a 23.976fps video at 48Hz with `--video-sync=display-resample`, I explicitly need to set `--gpu-dumb-mode=yes` to achieve 0.6W lower SoC power consumption with fullscreen video (3.8W vs. 4.4W, it's reliably reproducible). Despite of forcing `gpu-dumb-mode=yes`, `--video-sync=display-resample` still works as expected and makes playback smooth (verified with judder test video). There is no difference in power consumption with forced `gpu-dumb-mode` on/off without `--video-sync=display-resample`.

Config:
```
vo=gpu-next
gpu-api=opengl
gpu-context=wayland
hwdec=vaapi
video-sync=display-resample
#gpu-dumb-mode=yes
```

Logs:
[dumbmode-offdefault.txt](https://github.com/mpv-player/mpv/files/8558787/dumbmode-offdefault.txt)
[dumbmode-on.txt](https://github.com/mpv-player/mpv/files/8558788/dumbmode-on.txt)

mpv 6407095871b8f177996a6ec3ee9a8c4f06bd63ee
mesa 22.0.2m Intel Gemini Lake SoC

**Comment by haasn** [comment]
Interesting idea. Yeah, we should probably detect no-op configs and disable input caching in this case.

**Comment by haasn** [comment]
Oh, incidentally, I think I slightly misunderstood this issue. You're not interested in `--interpolation`, you're merely interested in single-frame redraw caching. (And specifically, disabling it if there's nothing significant to cache)

**Comment by haasn** [comment]
https://code.videolan.org/videolan/libplacebo/-/merge_requests/240 needs testing

Not sure if I'm happy with this approach. Feels kinda clunky and brittle.

**Comment by aufkrawall** [comment]
Yep, with that MR applied, SoC power consumption is as low as it was with forced `gpu-dumb-mode`. If you'd come up with something that you like better, I'd give it a whirl too.

**Comment by aufkrawall** [comment]
Thanks @haasn !

I've noticed that `--gpu-dumb-mode=yes` also prevents hooks like

```
//!HOOK MAINPRESUB
//!BIND HOOKED

const float min = 16.0 / 255.0;
const float max = (235.0 - 16.0) / 255.0;

vec4 hook()
{
    return (HOOKED_texOff(0) * max) + min;
}
```
from working (that was kindly provided by another dev some time ago). Since even ICC profile correction works with `--gpu-dumb-mode`, I suppose it should be doable also for such rather simple conversions (directly in libplacebo?)? I also think it would be somewhat neat to have range conversions for PC -> TV and vice versa by default with some keybinding in mpv, e.g. shift + l (not to be confused with `--video-output-levels`), as wrong range levels is a rather common screw up with random web content.

**Comment by haasn** [comment]
@aufkrawall impossible in the v1 shader system, see https://code.videolan.org/videolan/libplacebo/-/issues/174
