### ISSUE TITLE
Lua: cannot receive unicode from cmd.exe in subprocess command

### ISSUE THREAD

**Issue by CogentRedTester** [mpv-player/mpv#10139]
### Important Information
I am trying to call `cmd.exe` to read the contents of a directory with the `dir` command. I am aware that `mp.utils` has a function to read directories, but I was hoping to implement an asynchronous directory read with `mp.command_native_async`. I also would rather not use powershell because of the slow startup time.

The problem is that unicode characters aren't captured by the subprocess command, I just get question marks back. I already came across this problem when trying to do the same thing in powershell, but I was able to solve it using `[Console]::OpenStandardOutput().Write()`, which I found in the `console.lua` code. Hence it is *possible* to get unicode from the subprocess command, but I don't know if it can be done from `cmd`.

Provide following Information:
- mpv version: 0.34.0-276-g9d133eb00b (Shinchiro Build 2022-04-24)
- Windows Version: 10 Build 19043.1645

### Reproduction steps

You can easily test this by running mpv from a directory that contains unicode filenames with this script loaded:
```lua
local mp = require "mp"
local utils = require "mp.utils"

mp.command_native_async({
    name = "subprocess",
    playback_only = false,
    capture_stdout = true,
    args = {"cmd", "/c", "dir", "/b"}
}, function(_, response)
    print(utils.to_string(response))
end)
```

`io.popen` has the same result:
```lua
local i = io.popen("cmd /c dir /b", "r")
if i then print(i:read("*a")) end
```

### Attempts

I've been trying to do some research on the topic, [this stackoverflow answer](https://stackoverflow.com/a/47843552) was pretty informative, but it looks like something that should be fixed on the mpv side.

In Windows Terminal `cmd` outputs unicode correctly, from the old `conhost` it shows the little invalid text characters
![image](https://user-images.githubusercontent.com/57207260/165482659-3ac2f85c-cc07-48a5-b545-05ff849913da.png)

When piping the output to a file with `dir /b > test.txt` we get the same invalid output as mpv:
![image](https://user-images.githubusercontent.com/57207260/165482941-766b6ddf-2250-461d-b14b-f5d215a9908b.png)

However, when I change the codepage to unicode
```bat
chcp 65001
dir /b > test.txt
```
it outputs correctly:
![image](https://user-images.githubusercontent.com/57207260/165483288-e24f0453-6b40-43c9-a816-7639dfa7ed8e.png)

Hence I then tried to run `cmd /c chcp 65001 > nul & dir /b > test.txt`, but that failed in the mpv subprocess command. It did work in the terminal and in `io.popen`, but only after being run the second time. This implied that `io.popen` was actually changing the codepage for `mpv` instead of just the command it was running, which turned out to be correct. When I set `chcp 65001` in the terminal *before* opening mpv unicode is correctly returned from both `io.popen` *and* `subprocess`.

![image](https://user-images.githubusercontent.com/57207260/165486417-fb89d9fc-e221-49aa-820b-b32faa3646c8.png)

I don't know if it is possible to change the codepage for just the process spawned by `subprocess`, but I figured out through testing in the terminal that `cmd /c chcp 65001 > nul & cmd /c dir /b > test.txt` is able to change the code page and run the dir command successfully in one line. However, this still did not correctly write the unicode when run in `subprocess`.

I'm not sure where exactly the issue lies here or whether it is viable to fix, but I thought I'd share my findings and check if anyone knew a solution.

### Log file

I don't think a log file will be useful in this case, but I'll upload it [here](https://github.com/mpv-player/mpv/files/8570750/log.txt)

### Sample files

Github doesn't seem to want to let me upload files with unicode names, but just create a random file called `👀.txt` or something.

**Comment by thebombzen** [comment]
What happens if you use `winapi.short_path`? 
https://stevedonovan.github.io/winapi/api.html#short_path

**Comment by stax76** [comment]
Short paths by default work only on the C drive.

**Comment by stax76** [comment]
In C# I get correct Unicode characters with this:

```C#
using (Process p = new Process())
{
    p.StartInfo.UseShellExecute = false;
    p.StartInfo.FileName = "cmd";
    p.StartInfo.Arguments = "/c chcp 65001 > nul & cmd /c dir /b";
    p.StartInfo.WorkingDirectory = @"D:\Work\Test";
    p.StartInfo.RedirectStandardOutput = true;
    p.StartInfo.StandardOutputEncoding = Encoding.UTF8;
    p.Start();
    string str = p.StandardOutput.ReadToEnd();
    Console.WriteLine(str);
    Console.ReadKey();
}
```

It's not printed correctly in the console, but the debugger shows the str variable has the correct data.

In mpv I couldn't make it work either. Maybe it's a mpv issue, I'm not really an expert in this topic.

**Comment by thebombzen** [comment]
What if you wrap your command line in `winpty` first? msys can occasionally do weird things

**Comment by stax76** [comment]
[CogentRedTester](https://github.com/CogentRedTester) builds user scripts, so no msys.

**Comment by qwerty12** [comment]
I have a workaround but it requires mpv to be linked against LuaJIT (or `mp_to_utf8()` to be made available to scripts...). shinchiro's Windows builds do indeed use LuaJIT.

If you start cmd with `/U`, it will write UTF-16 output, which Windows can turn into UTF-8.
This works here if mpv is started by Windows Terminal (console already attached) and will print the correct text there, and if started by Explorer - the OSD message shows the text correctly. Though there are "squares" after each filename, something I noticed to be the case with the original test script.

```lua
local mp = require "mp"
local ffi = require 'ffi'
ffi.cdef[[
int WideCharToMultiByte(unsigned int CodePage, unsigned int dwFlags, const wchar_t *lpWideCharStr, int cchWideChar, char *lpMultiByteStr, int cbMultiByte, const char *lpDefaultChar, bool *lpUsedDefaultChar);
]]

local function WideCharToMultiByte(WideCharStr)
    if WideCharStr then
        local utf8_size = ffi.C.WideCharToMultiByte(65001, 0, WideCharStr, -1, NULL, 0, NULL, NULL) --CP_UTF8
        if utf8_size > 0 then
            local utf8_path = ffi.new("char[?]", utf8_size)
            local utf8_size = ffi.C.WideCharToMultiByte(65001, 0, WideCharStr, -1, utf8_path, utf8_size, NULL, NULL)
            if utf8_size > 0 then
                return ffi.string(utf8_path, utf8_size)
            end
        end
    end

    return nil
end

mp.command_native_async({
    name = "subprocess",
    playback_only = false,
    capture_stdout = true,
    args = {"cmd", "/U", "/c", "dir", "/b"}
}, function(_, response)
    if response.stdout then
        local str = WideCharToMultiByte(ffi.cast("wchar_t*", response.stdout))
        if str then
            print(str)
            mp.osd_message(str)
        end
    end
end)
```

**Comment by CogentRedTester** [comment]
@qwerty12 I can confirm that this method does indeed work! The `\0` character added to the end of the string was breaking a number of things, but it is simple to add a wrapper function to remove it.

**Comment by CogentRedTester** [comment]
I've adapted it into a single function that also removes the trailing `\0` character. I've also changed the `NULL`s for `nil`s since I assume that's what you were going for.

```lua
--this is a LuaJit module this addon will not load if not using LuaJit
local ffi = require 'ffi'
ffi.cdef([[
    int WideCharToMultiByte(unsigned int CodePage, unsigned int dwFlags, const wchar_t *lpWideCharStr, int cchWideChar, char *lpMultiByteStr, int cbMultiByte, const char *lpDefaultChar, bool *lpUsedDefaultChar);
]])

--converts a UTF16 string to a UTF8 string and removes the trailing `\0` character
--this function was adapted from https://github.com/mpv-player/mpv/issues/10139#issuecomment-1117954648
local function utf8(WideCharStr)
    WideCharStr = ffi.cast("wchar_t*", WideCharStr)
    if not WideCharStr then return nil end

    local utf8_size = ffi.C.WideCharToMultiByte(65001, 0, WideCharStr, -1, nil, 0, nil, nil) --CP_UTF8
    if utf8_size > 0 then
        local utf8_path = ffi.new("char[?]", utf8_size)
        local utf8_size = ffi.C.WideCharToMultiByte(65001, 0, WideCharStr, -1, utf8_path, utf8_size, nil, nil)
        if utf8_size > 0 then
            return ffi.string(utf8_path, utf8_size):sub(1, -2)
        end
    end
end
```

**Comment by CogentRedTester** [comment]
I do wonder if it would be possible to convert UTF-16 to UTF-8 in pure Lua. Lua does allow you to see and set the individual bytes of a string. I've done a quick search and come up with nothing, but it might be possible to adapt something from another language.

**Comment by qwerty12** [comment]
@CogentRedTester 

> The `\0` character added to the end of the string was breaking a number of things, but it is simple to add a wrapper function to remove it.

Oh, nice.

> Edit: how common are non-LuaJit windows builds?

Not that I have the most solid of reasoning, but as far as I can tell, not at all? shinchiro's SourceForge page says "17,842 [downloads] This Week" + ~200 downloads on average of his nightlies on GitHub. The Scoop and Chocolatey pages on https://mpv.io/installation/ install shinchiro's builds. The modified mpv builds on GitHub often use shinchiro's build scripts. The one GitHub repo where `pacman` packages are built for MSYS2 also uses LuaJIT. If someone uses media-autobuild_suite to build mpv, they'll get LuaJIT. 
The mpv-2.dll used by mpv.net (which very well may be the most popular mpv frontend on Windows) also uses LuaJIT.
The MSYS2 package does use the original PUC-Rio Lua interpreter, but I would surmise there's not many people who install MSYS2 for its mpv. Plus, it uses Lua 5.1 so there's probably already some scripts out there that don't work with it, `ffi` or not.

> I've also changed the `NULL`s for `nil`s since I assume that's what you were going for.

Indeed. :) I see the LuaJIT FFI tutorial says "You can simply use nil to pass a NULL pointer".
There's actually another mistake I've spotted (for the benefit of 32-bit mpv users): in `ffi.cdef`, `int WideCharToMultiByte` should be `int __stdcall WideCharToMultiByte`.

**Comment by thebombzen** [comment]
It looks like this has been solved.
