### ISSUE TITLE
Debanding with gpu-next is worse

### ISSUE THREAD

**Issue by eXmendiC** [mpv-player/mpv#10134]
### Important Information

Provide following Information:
- mpv version: 20220424-git-9d133eb
- Platform and Version: Windows 10 21H2 (19044.1645)
- Source of the mpv binary: shinchiro's build

### Reproduction steps
Just turn on debanding with vo=gpu-next and compare it against vo=gpu.

### Expected behavior
Same debanding quality, because the wiki doesn't say it's different:
https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU

### Actual behavior
Debanding is much worse, especially when adding some static noise.

### Log file
https://pastebin.com/w33QwPGv

### Comparisons
https://slow.pics/c/3MmP9ALa (without static noise)
https://slow.pics/c/Rr4TS0Yd (with static noise - making it more obvious)

Settings apart from "vo" are the same.

### Sample files
https://streamable.com/52y42i (it's a re-encoded clip, but that's actually better for testing debanding)

**Comment by ValZapod** [comment]
The first screenshot pair has purple line on the very top left chnage it color, indicated some color maangment.

**Comment by eXmendiC** [comment]
> The second screenshot pair has purple line on the very top left changing its color, indicated some color managment.
> 
> Is not debanding highly integrated into avc/hevc standards, AV1 did improve on it further, but... I though it is only needed for mpeg2/4.
> 
> Also the first pair has moved one of pictures.
> 
> I also quite do not understand what is the point of adding noise and THEN debanding. H.274 that describes film grain in HEVC/AVC actually descibed additional debanding/deblocking https://code.videolan.org/videolan/libplacebo/-/issues/188
> 
> It looks like debanding just desaturates some colors if you are sure color mangment does not happen.

I get your point that debanding makes more sense before adding noise, but that's an unchangable mpv behaviour. At least I'm not aware of adding a shader after the function "deband=yes" takes place. Adding an external deband shader would solve it. However, this has nothing to do with the actual problem. The screenshot with the noise is just to make the difference between gpu and gpu-next more visible. Even if I deband before the noise the problem is still there as you can see in the comparison without any noise shader.

**Comment by Hrxn** [comment]
"much worse"..?

Sorry, I don't see it. Based on the example without added static noise, I'd say gpu-next looks a bit better.

**Comment by garoto** [comment]
> Adding an external deband shader would solve it.

https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/shaders/deband-pre.glsl

**Comment by eXmendiC** [comment]
> "much worse"..?
> 
> Sorry, I don't see it. Based on the example without added static noise, I'd say gpu-next looks a bit better.

Definitely not. It's more noticeable with motion, if you have problems spotting the left over banding in the comparison. I recommend using the sample video file and see for yourself. 
```
deband-iterations= 4
deband-threshold=50
deband-range=16
deband-grain=0
```

> > Adding an external deband shader would solve it.
> 
> https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/shaders/deband-pre.glsl

Thanks. I'm gonna try that out. It shouldn't solve the problem of this issue, but at least could make it less obvious.

Maybe the overall "issue" is that the values are just working different. However, the wiki doesn't say anything about it.

**Comment by eXmendiC** [comment]
Edit 2:
Apperently the default behavior for mpv with "vo=gpu" is to apply debanding before other shaders like upscaling / adding noise.
See: https://cdn.discordapp.com/attachments/939092660914896916/1025521526184869999/unknown.png
However, with "vo=gpu-next" not only the debanding is worse, but also the approach to do it afterwards.
See: https://cdn.discordapp.com/attachments/939092660914896916/1025523406462001162/unknown.png
Anyway, that makes gpu-next still pretty much useless for content that needs (heavy) debanding.

**Comment by haasn** [comment]
Should be fixed by https://github.com/haasn/libplacebo/commit/67f8fe5de92a29f2268ec28d6cb7c3ca0b63d8e5
