### ISSUE TITLE
Inconsistent seek with re-encoded libaom-av1 files

### ISSUE THREAD

**Issue by xfzv** [mpv-player/mpv#10140]
I've re-encoded some video files to AV1 with the following `ffmpeg` options:

```bash
   ffmpeg \
        -hide_banner                \
        -map 0                      \
        -c:v libaom-av1             \
        -cpu-used 7                 \
        -crf 42                     \
        -b:v 0                      \
        -tiles 3x2                  \
        -row-mt 1                   \
        -frame-parallel 1           \
        -c:a libopus                \
        -b:a 32k                    \
        -vbr on                     \
```

and I'm getting inconsistent seek with mpv for any of them. I don't have the issue with VLC with the same file (or any re-encoded AV1 file).

- Consistent seek (1 minute) with **VLC**:

https://user-images.githubusercontent.com/78810647/165580712-35160a81-1657-4ceb-a3f2-788cfd0bfcf9.mp4

- Inconsistent seek (supposed to be 1 minute too) with **mpv**:

https://user-images.githubusercontent.com/78810647/165581403-274c4b15-113f-461c-80f0-c477480be6d6.mp4

Notice how VLC seek is very consistent, whereas mpv jumps randomly: 
- from 00:06:54 to 00:09:45
- from 00:20:13 to 00:23:54
- from 00:23:54 to 00:25:32

These are the biggest jumps I noticed on this specific file, but most of the seeks aren't accurate either, although the gap is less important. Same behavior for all the files I've re-encoded to AV1, not just this one. It looks like the issue is more noticeable with bigger files with higher resolutions and FPS though. The videos don't show any backward seek but I'm getting the same inconsistent jumps with mpv too, while they're also consistent with VLC.

### Important Information

```
% mpv --version
mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1
```

```
% vlc --version
VLC media player 3.0.17.3 Vetinari (revision 3.0.13-8-g41878ff4f2)
VLC version 3.0.17.3 Vetinari (3.0.13-8-g41878ff4f2)
Compiled by portage on localhost (Apr 27 2022 18:32:02)
Compiler: gcc version 11.3.0 (Gentoo 11.3.0 p4)
This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute it under the terms of the GNU General Public License;
see the file named COPYING for details.
Written by the VideoLAN team; see the AUTHORS file.
```

I also tried with [mpv-git](https://aur.archlinux.org/packages/mpv-git) or [mpv-9999 (Gentoo)](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-video/mpv/mpv-9999.ebuild) but it doesn't make any difference.

- Linux Distribution and Version : Arch Linux / Gentoo
- Source of the mpv binary :
    - Arch Linux: [community repository](https://archlinux.org/packages/community/x86_64/mpv/)
    - Gentoo: [media-video/mpv](https://packages.gentoo.org/packages/media-video/mpv)
- Window Manager and version : kwin 5.24.4
- GPU driver and version : NVIDIA GTX 970 / proprietary drivers (Gentoo : 510.68.02 / Arch: 510.60.02)

### Expected behavior

Seeking should be consistent, just like with VLC.

### Actual behavior

Seeking isn't consistent.

### Log file

[output.log](https://github.com/mpv-player/mpv/files/8575429/output.log) from my Gentoo system (`mpv --log-file=output.log <file_name>`) without any `mpv.conf` file. I didn't use  `--no-config` because I had to use:

```
LEFT seek -60
RIGHT seek 60
```

in `input.conf` in order to be able to seek 1 minute forward/backward with left/right keys.

Please let me know if I forgot any important information.

**Comment by hooke007** [comment]
Are u sure your clip has enough keyframes to seek within 1 minute? If not, why not use `seek 60 exact`.

**Comment by xfzv** [comment]
> Are u sure your clip has enough keyframes to seek within 1 minute? If not, why not use `seek 60 exact`.

I didn't know about `exact`, I should have read `man mpv` more carefully. I can confirm than using `seek 60 exact` instead of `seek 60` works as expected.

Thank you! :disguised_face:
