### ISSUE TITLE
Client API issue using overlay-add in dual monitor setup with different DPI

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10145]
There might be a client API issue using `overlay-add` in a dual monitor setup with different DPI, but possibly it would be difficult to describe, reproduce and debug, so this is not intended as bug report, I just post in case somebody wants to take a quick look anyway, otherwise please ignore like me.

https://github.com/stax76/mpv.net/issues/397

mpv.net covers the original OSC logo with its own logo using `overlay-add`, it has some minor cosmetic issues (original logo is still seen sometimes) but never bothered me enough to find a better solution.

https://github.com/stax76/mpv.net/blob/master/src/Misc/CorePlayer.cs#L1316

Are there maybe user scripts using `overlay-add`? With that, maybe I can reproduce it with mpv.

**Comment by garoto** [comment]
> Are there maybe user scripts using overlay-add?

TheAMM's mpv_thumbnail_script is one.

**Comment by stax76** [comment]
That works fine in mpv and also in mpv.net, I need to take another look at my code.
