### ISSUE TITLE
lua: mp.get_property_native only nil as output?

### ISSUE THREAD

**Issue by mitzsch** [mpv-player/mpv#10154]
I´m trying to get a lua script working that calls an external program when a specific video parameter is matched. But somehow I´m stuck with getting it to work. To see what is really going on I just wrote a very basic script that should only print the video's primaries and the width but all I get is `nil`.  I mean on the `print(test1)` it would be fine as there is no reference but the other two? Is this supposed to be working? Or is there something fundamentally wrong with my script?

script:
```
require "mp.msg"
require "mp.options"

mp.get_property_native("video-params/primaries", prim)
print (prim)

mp.get_property_native("width", wdth)
print (wdth)

print (test1)
```

Thanks! :)

**Comment by mitzsch** [comment]
Many thanks! 

May I ask what the script should look like then? Sorry for the dumb question I´m unfortunately not that familiar with lua... 

Is running `mpv file.mkv --script="path\to\script.lua" ` working then, when the script and the video file are loaded at the same time? (I´m probably overcomplicating it in my head)

**Comment by guidocella** [comment]
`video-params/primaries` seems to be unavailable on `file-loaded` so you can use

```lua
mp.observe_property("video-params/primaries", "string", function (_, primaries)
    if primaries == nil then
        return
    end

    print(primaries, mp.get_property("width"))
end)
```

**Comment by mitzsch** [comment]
Awesome! Many thanks now it works and I understand this a little bit more. Thanks so much! :)
