### ISSUE TITLE
${current-tracks/audio/demux-bitrate} in kilobits ?

### ISSUE THREAD

**Issue by nullnullnullnull0** [mpv-player/mpv#10156]
I want to display the audio bitrate in kilobits in the titlebar, but when using ${packet-audio-bitrate}, it always jumps between bitrate and "unavailable", ${current-tracks/audio/demux-bitrate} working well, but it shows bits instead of kilobits, is there any way to make ${current-tracks/audio/demux-bitrate} show in kilobits.

**Comment by guidocella** [comment]
```lua
mp.observe_property('current-tracks/audio/demux-bitrate', 'native', function (_, bitrate)
    if bitrate then
        mp.set_property('title', bitrate / 1000)
    end
end)
```

**Comment by nullnullnullnull0** [comment]
> ```lua
> mp.observe_property('current-tracks/audio/demux-bitrate', 'native', function (_, bitrate)
>     if bitrate then
>         mp.set_property('title', bitrate / 1000)
>     end
> end)
> ```
This method is a bit slow, opening a new file takes 1 to 2 seconds to refresh the title bar.

**Comment by thebombzen** [comment]
Why can't you just divide it by 1000?

**Comment by nullnullnullnull0** [comment]
> Why can't you just divide it by 1000?

Using "title="${current-tracks/audio/demux-bitrate}"" in mpv.conf is faster than using "observe_property" in lua.

**Comment by nullnullnullnull0** [comment]
Most software displays the audio bit rate in kilobits, I think it is more user-friendly to display kilobits.
