### ISSUE TITLE
Dont restart video on next frame?

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#10159]
If I press . near the end of a video it restarts the video at the first frame. How do I stop this behaviour and just stop on the last frame?

**Comment by garoto** [comment]
Not the standard player behavior. Most likely doings of a script. Test with `--no-config`.

**Comment by hooke007** [comment]
> it restarts the video at the first frame

seems you were using `loop` , or it was impossible. With no-config it would just terminate the process at the end of the video.

**Comment by cerealXDD** [comment]
> > it restarts the video at the first frame
> 
> seems you were using `loop` , or it was impossible. With no-config it would just terminate the process at the end of the video.
> 
> > just stop on the last frame
> 
> `keep-open=always`

I was using loop. Thank you, keep-open worked when I disabled loop inside the player.
