### ISSUE TITLE
vo=gpu_next HDR passthrough settings

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#10158]
- Windows 10 Pro x64 
- [Latest MPV from shinchiro](https://github.com/shinchiro/mpv-winbuild-cmake/releases)

`libplacebo` [last PR](https://code.videolan.org/videolan/libplacebo/-/merge_requests/239) `d3d11/swapchain: add support for configuring swap chain color space`
Is supposed to trigger the HDR to the TV using `gpu-api=d3d11`, but it's only working with `gpu-api=vulkan`

I have a few questions.
1) Why isn't HDR triggered when using `gpu-api=d3d11`? (MPV version is `mpv 0.34.0-287-g90d291dce7` and `built on Tue May  3 01:22:54 UTC 2022`, also `Initialized libplacebo v4.204.0 (API v204)`)
2) Should I enable HDR mode in Windows before opening MPV? (It may be more accurate? Buggy?)
3) Should I use any settings for HDR, because till now I used the following:
```
[HDR]
profile-cond=p["video-params/primaries"] == "bt.2020"
profile-restore=copy
target-trc=pq
target-prim=bt.2020
tone-mapping=bt.2390
d3d11-output-csp=pq
gamut-mapping-mode=auto
```

**Comment by jeeb** [comment]
So, after my MR got merged in libplacebo, `--vo=gpu-next --target-colorspace-hint=yes` should now work with d3d11.

With HDR content the swap chain should be flagged as HDR, and with SDR content the swap chain should get flagged as SDR. `d3d11-output-csp` and `d3d11-output-format` will effectively get overridden by libplacebo after this. You can think of swap chain as the window, effectively. As long as this happens, everything is as expected.

Now, then regarding what people tend to often expect, which is display output reconfiguration. About a year or two ago MS started making sure that at least with d3d the swap chain color space would not affect how the display output is configured. The only way a user is supposed to configure it, is through the Windows settings application. Before that various driver vendors did reconfiguration based on fullscreen window's swap chain configuration, and thus if people expected that to happen - it would no longer do so as they updated their drivers. MS also does not provide official API to switch the configuration, so the application has no official way of requesting a reconfiguration. If you want HDR, you should always have your display configured as HDR through Windows settings. This issue with users' wishes not matching MS's wishes has also popped elsewhere, such as madVR's issue tracker.

This does not seem to affect other graphics APIs, such as Vulkan, though. MS seems to have much less say on what the driver vendors can or cannot do on that side. So if you do the same, but with `--gpu-api=vulkan` - at least on nvidia you will get the display configuration switching to HDR with HDR content.

I hope this clarifies what the current expectation is with regards to HDR swap chains on Windows.

**Comment by Obegg** [comment]
Great explanation! Love it! Wow! I really appreciate it! I really don't want to close this "issue" because of this explanation, I want more people (if and when) to know this, so I don't know if I should close it or not.

So on Windows, which one should I use?
`--vo=gpu-next --target-colorspace-hint=yes --gpu-api=vulkan`
Or `--vo=gpu-next --target-colorspace-hint=yes --gpu-api=d3d11` and set the display to HDR? (which is more steps)
I understand that Vulkan does set the display to HDR when needed but I have no idea if the video will be displayed better (color accuracy and etc) or worse compared to d3d11, which is the native API for Windows. (Native usually means better optimized, but since Vulkan seems to trigger the HDR on the display that means Vulkan is the better choice?)

**Comment by jeeb** [comment]
The output of either graphics API should be the same. d3d11 just has better co-operation with other d3d11 based things, such as d3d11va hardware decoding.

**Comment by Doofussy2** [comment]
So if this works automatically as you intend it, will the trc  also switch from pq to srgb? Or will it be sRGB with pq transfer?

**Comment by Doofussy2** [comment]
At first basic test, it looks like the `target-peak` is set to 203 for everything. Not good!

**Comment by Doofussy2** [comment]
Something is very wrong. If I set `target-trc=pq` and `target-prim=bt.2020`, the picture is all washed out. I think everything might be coming out srgb and I can't override it!

**Comment by Doofussy2** [comment]
Oh my! Everything is now stuck on `target-trc=srgb`. It's all broken. Unusable :(

**Comment by ZaquL** [comment]
> Something is very wrong. If I set `target-trc=pq` and `target-prim=bt.2020`, the picture is all washed out. I think everything might be coming out srgb and I can't override it!

You must omit those after the latest libplacebo commit for HDR screen to get the same result as before. Or it will color manage stuff even further.

**Comment by Doofussy2** [comment]
> > Something is very wrong. If I set `target-trc=pq` and `target-prim=bt.2020`, the picture is all washed out. I think everything might be coming out srgb and I can't override it!
> 
> You must omit those after the latest libplacebo commit for HDR screen to get the same result as before. Or it will color manage stuff even further.

Yes, I understand the intension of that commit. You didn't read everything or you misunderstood. It's wrong with **_any_** or **_no_** config. The target peak (in my case) is off by ~500 nits. Which means I have to make an auto-profile for SDR and/or HDR just for the `target-peak`. Which is then screwed for Dolby Vision, as there is no property to make an auto-profile for DV. And if `target-trc` is no longer usable, which is what you ostensibly saying, then this is even more wrong.

**Comment by Doofussy2** [comment]
And just for the record, I very much don't like having no control of the picture. This was always my favorite part of mpv, the options. Now, I have none. My configs are pretty much, useless.

**Comment by Doofussy2** [comment]
Ooooooo.... I think I know what's happening. I had made an ICC and it was system default. It had an sRGB profile. It appears that libplacebo uses that, regardless. It was something that I thought about and did apply `icc-profile=no`, but it didn't change the output. On reading another thread on here, (I was using DisplayCal), I uninstalled it and removed the ICC, resetting Windows to default. Now, I get different results. What appear to be what I would expect. I'm still testing, but @haasn, is this what you're working on with how ICCs are used in libplacebo? I'm reticent to make another profile.

**Comment by Doofussy2** [comment]
Awwww, my very bad. Please accept my apologies. I re-read the above posts and discovered I missed a vital piece of information, `target-colorspace-hint=yes`. That appears to work as expected. Sometimes I need a slap around the head. 

Dolby Vision is still far too bright, but that's a separate issue. 

Feel free to delete my earlier rubbish.

**Comment by Doofussy2** [comment]
And for the DV stuff, as it's read as bt.709, I added a `target-peak` value to my SDR auto profile. That appears to correct the over brightness issue.

**Comment by jeeb** [comment]
> Awwww, my very bad. Please accept my apologies. I re-read the above posts and discovered I missed a vital piece of information, `target-colorspace-hint=yes`. That appears to work as expected. Sometimes I need a slap around the head.
> 

To be honest during the working week it went like this:

1. You see a person yelling vaguely that **everything** is broken.
2. You check that things still work as you expect in the two cases that were recently changed with my libplacebo MR (SDR and HDR with hint passing enabled).
3. You decide that your mental power isn't enough to start arguing, and ignore responding to the comments for now.

This is why it's important to list the specifics of things when you say something is not working. You may notice during that time such things that you have since noticed, as well as you give actual things - as opposed to just generic  "everything's broken".

> Dolby Vision is still far too bright, but that's a separate issue.
> 
> Feel free to delete my earlier rubbish.

You can yourself click the three dots on the top right of posts and select to hide them, I can at least do the same on my issue comments in glfw, where I do not have any special rights, so I would expect the same to work here as well.

**Comment by Obegg** [comment]
@jeeb can you please delete all of their messages here and lock the issue? they ruined the beauty of your explanation, I want to restore that beauty so other people will know it.

**Comment by Doofussy2** [comment]
> @jeeb can you please delete all of their messages here and lock the issue? they ruined the beauty of your explanation, I want to restore that beauty so other people will know it.

I deleted them. I'm very sorry.

**Comment by ZaquL** [comment]
> So if you do the same, but with `--gpu-api=vulkan` - at least on nvidia you will get the display configuration

So you did break Dolby Vision after all (profile 5 that is, not 8), since a normal HDR movie triggers HDR in vulkan (or even pq'ed AVIF image from #10247):
mpv.com --target-colorspace-hint=yes  -hwdec=d3d11va --gpu-api=vulkan  -vo=gpu-next

Yet that does not happen with dolby vision content. Wow, just wow.

Since it is not tagged as PQ you got consfused that is not PQ. Ha. But in fact it is.
