### ISSUE TITLE
Tearing/video corruption when zoom/scaling is used

### ISSUE THREAD

**Issue by nazar-pc** [mpv-player/mpv#10151]
### Important Information

Provide following Information:
- mpv version: 0.33.1/.34.1
- Linux Distribution and Version: Ubuntu 21.10
- Source of the mpv binary: from default repositories / https://non-gnu.uvt.nl/debian/impish/mpv/ (I tried both with the same result, that is why 2 versions)
- Window Manager and version: Qtile 0.21.0 with Compton (also tried Picom, same issue)
- GPU driver and version: amdgpu (Linux 5.17.4-xanmod1)
- Possible screenshot or video of visual glitches [MPV tearing](https://user-images.githubusercontent.com/928965/166168724-1b4750ff-6be3-478a-b18f-56a502b2f546.png)

### Reproduction steps

1. Play HEVC video with resolution 1080p and 10-bit HDR
2. Through SMPlayer
3. Increase zoom to 1.25

### Expected behavior

No visual artifacts

### Actual behavior

Tearing, typically on the same part of the screen:
<details>

![MPV tearing](https://user-images.githubusercontent.com/928965/166168724-1b4750ff-6be3-478a-b18f-56a502b2f546.png)

</details>

Interestingly, no tearing is present when zoom/scaling is not used.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/8599960/mpv.log)

### Sample files

No right now

**Comment by CounterPillow** [comment]
> Through SMPlayer

can you reproduce it without smplayer?

**Comment by nazar-pc** [comment]
> can you reproduce it without smplayer?

I basically never use it on its own, but I just tried and can't reproduce with just MPV. The closest thing to it is to press Right arrow key and hold it to switch frames quickly, then it does introduce artifacts in some cases on jumps, but probably unrelated.

**Comment by CounterPillow** [comment]
SMPlayer uses some way of embedding mpv in its window that (if I recall correctly) the mpv players explicitly disagree with using due to issues like this, so if you cannot reproduce this with just mpv then it's very likely this is actually an SMPlayer issue.
