### ISSUE TITLE
MPV HDR support on Linux

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#10168]
I saw a line in ArchWiki: https://wiki.archlinux.org/title/HDR_video_playback#mpv
`HDR support is native and all the configurations are set to correct values by default. You can adjust the peak brightness using --target-peak. `
1. Does that mean MPV player can show HDR effect on a HDR capable TV in SDR mode now? 
2. According to that article, does it mean we can watch HDR content natively on Linux Xorg now?
3. How can Gnome and KDE be so poor at supporting HDR color profile in Wayland?
4. MPV still can have HDR color profile support even GDM and SDDM don't support it, does it correct? How about the 10bit color?
5. According to the MPV manual, target-peak should not be used to SDR content, so we need to change the config every time we watch videos?

**Comment by lavilao** [comment]
I was going to say the typical "linux does not have hdr support" answer but after reading the page it seems to imply that there IS experimental support for hdr on linux, ironically I always though it was going to be a wayland exclusive thing but is only on x11 for now.

**Comment by laichiaheng** [comment]
@lavilao Does it mean that MPV can passthrough HDR videos by adding '--vo=gpu-next' on X11?

**Comment by LaserEyess** [comment]
That entire arch wiki article is completely wrong, you can tell in the first paragraph it is just making shit up:

> Red Hat has hired people to work on improving HDR and developers at X.org are also working on improving HDR on Linux. See [the roadmap](https://gitlab.freedesktop.org/wayland/weston/-/issues/467).
>
That link says absolutely nothing that bullet point says at all. It is about Wayland, not Xorg, and no one there even works for redhat.

**Comment by laichiaheng** [comment]
@LaserEyess But we still can see the HDR effect with `target-peak` if TV brightness is high enough in SDR mode, right?

**Comment by LaserEyess** [comment]
`--target-peak` controls tonemapping, which in this case would be HDR->SDR, but the TV brightness really doesn't affect anything. It's not HDR, it's SDR.

**Comment by laichiaheng** [comment]
@LaserEyess Should we change the target-peak if TV brightness is over 203nits? It says that it leads to very unexpected results for SDR content.
I'm confused now, I thought that we would see similar HDR effect on SDR mode if TV brightness were high enough.

**Comment by LaserEyess** [comment]
You're confusing a few different things here. There is no "HDR Effect" here, you are playing back content as tonemapped HDR->SDR. What happens when you set `--target-peak` is that you are telling mpv to ignore whatever display capabilities are present and just assume that a peak is a certain amount of nits. See also: https://mpv.io/manual/master/#options-target-peak

And, as an aside, I also should have RTFM, setting `--target-peak` on SDR displays may do bad things, but the default, `auto`, should be fine. This is pretty much the limit of my knowledge of HDR so maybe someone else can chime in. Bottomline is: just play the video on your monitor, it will work and tonemapping will make it look as good as possible.

**Comment by lavilao** [comment]
sorry @laichiaheng acording to @LaserEyess the arch wiki article is wrong (wich makes sense otherwise reddit would be full of "linux supports hdr now" posts) so no hdr on linux for now. I guess we are all humans, even archlinux users that write on the wiki can make mistakes xD

**Comment by Doofussy2** [comment]
> `--target-peak` controls tonemapping, which in this case would be HDR->SDR, but the TV brightness really doesn't affect anything. It's not HDR, it's SDR.

That's a little ambiguous. If an HDR video is mastered at 1000 nits and you specify `target-peak=1001`, there shouldn't be any peak adjustments by the player, and as long as the color gamut isn't changed, tone-mapping shouldn't happen. And if there is, that would be bad. The video should be passed to the swapchain (provided it supports the media). This is what is broken with the latest build for Windows. It isn't working correctly.

**Comment by thebombzen** [comment]
It appears this question is answered. If tonemapping is broken then please open a separate issue for that.

**Comment by laichiaheng** [comment]
@LaserEyess Hi, I have another question. Am I able to play HDR videos in SDR mode with high peak brightness and high contrast instead of low contrast flat image?

**Comment by thebombzen** [comment]
If you're playing them in SDR mode then it'll be tonemapped downward. There's no "peak brightness" or "high contrast"

**Comment by andrewfader** [comment]
Is there a way to fix the colors for HDR video on wayland?

**Comment by lavilao** [comment]
I think I found it! Legends spoke that if you use the amdvlk driver and use mpv or kodi on a tty (aka drm mode) hdr should work. Has anyone tested this?

**Comment by lavilao** [comment]
it is said here https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1325825-wayland-1-21-alpha-finally-introduces-high-resolution-scroll-wheel-support by [Quackdoc](https://www.phoronix.com/forums/member/115212-quackdoc)

**Comment by LaserEyess** [comment]
I posted something about this already, see #8648, specifically [this comment ](https://github.com/mpv-player/mpv/pull/8648#issuecomment-884119804) and more importantly [this comment](https://github.com/mpv-player/mpv/pull/8648#issuecomment-884122947). Yes it requires AMDVLK, it is not portable and not implementable on any other hardware or driver. That PR is a real solution for DRM which is hardware and driver independent.

@andrewfader open a new issue and be sure to fill out the issue template.

**Comment by lavilao** [comment]
certainly implement that vulkan extension on mesa would be the best for intel and amd users, I am surprised nvidia had not implemented hdr on their driver, maybe now on the new open source one.

**Comment by lavilao** [comment]
on coment #2 I thought mpv would already did this, I guess I was wrong. I am not an HDR users so cant really test.

**Comment by andrewfader** [comment]
created https://github.com/mpv-player/mpv/issues/10241

**Comment by andrewfader** [comment]
@LaserEyess turned out my problem was solved with gpu-next thanks!

**Comment by laichiaheng** [comment]
> I posted something about this already, see #8648, specifically [this comment ](https://github.com/mpv-player/mpv/pull/8648#issuecomment-884119804) and more importantly [this comment](https://github.com/mpv-player/mpv/pull/8648#issuecomment-884122947). Yes it requires AMDVLK, it is not portable and not implementable on any other hardware or driver. That PR is a real solution for DRM which is hardware and driver independent.
> 
> @andrewfader open a new issue and be sure to fill out the issue template.

None of them have been merged, so sad.

**Comment by laichiaheng** [comment]
> I think I found it! Legends spoke that if you use the amdvlk driver and use mpv or kodi on a tty (aka drm mode) hdr should work. Has anyone tested this?

Do I need to remove vulkan-radeon?

**Comment by lavilao** [comment]
unless you really know what are you doing and know your way with env variables yes, you will have to uninstall vulkan-radeon

**Comment by laichiaheng** [comment]
@lavilao How to make it work? I don't see any HDR settings in KODI.

**Comment by lavilao** [comment]
sorry, I dont use kodi anymore so I dont know if it has any HDR settings
