### ISSUE TITLE
libmpv allow using idle property

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10162]
If I set idle=no in code or in conf, mpv_initialize returns an error.

Could this restriction maybe be removed? In mpv.net, I try to support as many mpv features as possible.

**Comment by Dudemanguy** [comment]
I don't believe there is a restriction. On the [simple](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/simple/simple.c) libmpv example, I can add `mpv_set_option_string(ctx, "idle", "yes");` and `mpv_set_option_string(ctx, "force-window", "yes");` before it initializes and it works normally.

**Comment by stax76** [comment]
It can be set to yes, which is the default for libmpv, the problem is that it cannot be set it to no.

**Comment by Dudemanguy** [comment]
Oh I see, you're correct. Let me dig into this a bit.

**Comment by stax76** [comment]
It solves my problem, but I had to use a workaround, with idle=no mpv.net received the shutdown event and I think the core shuts down too, it does this before I have a chance to load files. As a workaround, I store the idle=no value and set idle=yes after mpv_initialize and mpv.net behaves as if idle was set to no. In the manual, I describe as follows:

The mpv property idle can be used and mpv.net functions accordingly, but Lua scripts always see `idle=yes` because mpv.net has to set it to function correctly, this is a difficult to overcome libmpv limitation.

Maybe I could have overcome the issue by creating a new client handle with mpv_create_client and wait to initialize it after files are loaded, referring to this code:

https://github.com/mpv-player/mpv/blob/master/player/client.c#L607

It still can be tried.

Even though I have a VS Code dev environment with working debugger, the code generally is difficult to understand for me, it's very complex, and I'm not very experienced with C.

So my current implementation might break a script or too, are there any scripts using the idle property for something important? In mpv.net the idle default is yes, and personally I use keep-open=always.
