### ISSUE TITLE
av not sync in fragment mp4 after seeking

### ISSUE THREAD

**Issue by fastfading** [mpv-player/mpv#10167]
### Important Information

Provide following Information:
- mpv version   0.34.1
- macOS Version   11.6.5
- Source of the mpv binary or bundle        brew install mpv
- If known which version of mpv introduced the problem   0.34.1
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
play the video,    do some seek,    some times  a/v will not sync after seek. not always happen.

vlc has the same issue,  but vlc fix it  in vlc 3.0.18,    hope  mpv could fix it too
vlc issue ticket:
https://code.videolan.org/videolan/vlc/-/issues/26719

it is a fragment mp4 format.

after seeking there was a a/v sync issue

this file is generated with mp4box

mp4box -dash 30000 -profile onDemand nomal.mp4 -out normal.mpd

this video play well in below players

* QT quick time player Version 10.5 (1086.4.2) mac ok
* IINA 1.1.2 mac ok
* ffplay 4.0 ok
* gpac 1.1 ok
* firefox ok
* safari Version 15.3 (16612.4.9.1.8, 16612) ok
* chrome version 98.0.4758.109 ok
* potplayer 220302(1.7.21620) windows ok
* window 10 media player ok
* windows 10 movie and tv ok
* ACG Player 1.15.17606 ok
* SM Player 22.2.0 ok
* adobe premier 2022 OK

### Sample files
https://mega.nz/file/bTBQxaoI#2wbbFjjGQi1xs-KdkrW4DtZtM6sppMj6KqbehUR5_FM

**Comment by fastfading** [comment]
not only in mac , but also in windows

**Comment by Dudemanguy** [comment]
I can't reproduce on linux with git master for whatever it's worth.

**Comment by fastfading** [comment]
so， is it fixed ？  could you make new release for mac and windows，  so I can verify it

**Comment by fastfading** [comment]
“play the video, do some seek, some times a/v will not sync after seek. not always happen.”
and pls try more times  ， this happen occasionally  when you seek to a particular position.

**Comment by Dudemanguy** [comment]
I've seeked through that video a million times without any issues on my end. Not sure if there's something special you need to do to trigger whatever you're seeing.

**Comment by Dudemanguy** [comment]
p.s. there's been a new release since then. Do you still have this issue?

**Comment by fastfading** [comment]
it seems there is no issue in  mpv mac 0.35 version ,  thanks

**Comment by Dudemanguy** [comment]
Glad to hear.
