### ISSUE TITLE
Add option to display time remaining in OSD to be calculated based on current playback rate.

### ISSUE THREAD

**Issue by jtgd** [mpv-player/mpv#10160]
### Expected behavior of the wanted feature
Either add another entry in the OSD cycle of states, or command line switch, or other key, to display time remaining based on current playback speed. Should be updated each time the speed is changed.

This would make it nice to be able to scale the playback speed to fit the time I have to watch.

**Comment by dexeonify** [comment]
Isn't this already implemented? On a 1 minute video for example, if I set the playback speed to 2x, the remaining time will show 30s. You might have to play/pause to update the OSC.

**Comment by jtgd** [comment]
You are quite right. Idon't know how I failed to notice this. Sorry for the noise.
