### ISSUE TITLE
how to limit streaming video quality

### ISSUE THREAD

**Issue by lodgerz** [mpv-player/mpv#10169]
Hello, how can i limit streaming video quality?
I have tried to add this on mpv.conf:

ytdl-format=bestvideo[height<=?480]+bestaudio

But it works only with youtube. For other streaming video, for example iptv, doesn't work and i have to type manually this:

mpv --vid=3 https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718

**Comment by thebombzen** [comment]
You might need to show all formats with `script-opts-append=ytdl_hook-all_formats=yes` so it can select the bestvideo and bestaudio with those resolutions.

**Comment by lodgerz** [comment]
> `bestvideo[height<=?480]+bestaudio/best[height<=?480]/worst`

it doesn't work.


> You might need to show all formats with `script-opts-append=ytdl_hook-all_formats=yes` so it can select the bestvideo and bestaudio with those resolutions.

thanks for reply but i can't understand. where should i use that command?
This is an example of iptv streaming:
```
$ mpv https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718
 (+) Video --vid=1 (h264 1280x720 25.000fps) (2793 kbps)
     Video --vid=2 (h264 1024x576 25.000fps) (2137 kbps)
     Video --vid=3 (h264 768x432 25.000fps) (1365 kbps)
 (+) Audio --aid=1 --alang=ita (*) (aac 2ch 44100Hz) (1365 kbps)
     Audio --aid=2 --alang=V.O (aac 2ch 44100Hz) (1365 kbps)
     Audio --aid=3 --alang=des (aac 2ch 44100Hz) (1365 kbps)
     Audio --aid=4 (aac 2ch 44100Hz) (2793 kbps)
     Audio --aid=5 (aac 2ch 44100Hz) (2137 kbps)
     Audio --aid=6 (aac 2ch 44100Hz) (1365 kbps)
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
AV: 00:00:00 / 00:00:01 (18%) A-V:  0.117 Cache: 0.7s/285KB

Exiting... (Quit)
```

**Comment by thebombzen** [comment]
Place that line in your `mpv.conf`.

**Comment by lodgerz** [comment]
> Place that line in your `mpv.conf`.

done, but mpv still plays video with max resolution (1280x720). maybe i have to type some key to change video resolution?

**Comment by thebombzen** [comment]
Try removing the `?` so you have `bestvideo[height<=480]+bestaudio/best[height<=480]/worstvideo+bestaudio/worst`

**Comment by lodgerz** [comment]
> Try removing the `?` so you have `bestvideo[height<=480]+bestaudio/best[height<=480]/worstvideo+bestaudio/worst`

no difference. it plays always on 720p

**Comment by thebombzen** [comment]
Post your mpv version and a log file, then, cause that sounds like a bug.

**Comment by lodgerz** [comment]
> Post your mpv version and a log file, then, cause that sounds like a bug.
mpv 1:0.34.1-3
log:
[logz.txt](https://github.com/mpv-player/mpv/files/8642106/logz.txt)

**Comment by garoto** [comment]
ffmpeg is picking the stream first, before the ytdl hook. Use `--hls-bitrate=min` I guess.

**Comment by garoto** [comment]
> mpv --hls-bitrate=min "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=308718"
	[ 76.218671]    cplayer:      Video --vid=1 (h264 1280x720 25.000fps) (2793 kbps)
	[ 76.219383]    cplayer:      Video --vid=2 (h264 1024x576 25.000fps) (2137 kbps)
	[ 76.219910]    cplayer:  (+) Video --vid=3 (h264 768x432 25.000fps) (1365 kbps)
	[ 76.220342]    cplayer:  (+) Audio --aid=1 --alang=ita (*) (aac 2ch 44100Hz) (1365 kbps)
	[ 76.220770]    cplayer:      Audio --aid=2 --alang=V.O (aac 2ch 44100Hz) (1365 kbps)
	[ 76.221191]    cplayer:      Audio --aid=3 --alang=des (aac 2ch 44100Hz) (1365 kbps)
	[ 76.221610]    cplayer:      Audio --aid=4 (aac 2ch 44100Hz) (2793 kbps)
	[ 76.222070]    cplayer:      Audio --aid=5 (aac 2ch 44100Hz) (2137 kbps)
	[ 76.222488]    cplayer:      Audio --aid=6 (aac 2ch 44100Hz) (1365 kbps)
	[ 76.297450]    cplayer: AO: [wasapi] 48000Hz stereo 2ch float
	[ 76.298724]    cplayer: VO: [gpu] 768x432 yuv420p
	[ 84.543431] statusline: AV: 00:00:08 / 00:00:10 (80%) A-V:  0.000 ct:  0.091 Cache: 1.6s/340KB
	[ 84.576116] ffmpeg/demuxer: hls: Changing ID3 metadata in HLS audio elementary stream is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
	[619.031403] statusline: (Paused) AV: 00:00:08 / 00:08:00 (2%) A-V:  0.000 ct:  0.091 Cache: 471s/97MB
	[622.005222]    cplayer:
	[622.005830]    cplayer: Exiting... (Quit)

**Comment by lodgerz** [comment]
> ffmpeg is picking the stream first, before the ytdl hook. Use `--hls-bitrate=min` I guess.

Thank you! i put "--hls-bitrate=480" on mpv.conf and now it works. Also with youtube video.

**Comment by thebombzen** [comment]
This appears to be solved.
