### ISSUE TITLE
Various questions about full screen, subtitles, scaling, performance, etc.

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#10174]
These are a bundle of questions I have gathered with the use of mpv over time.  Will post feature requests or bug reports as necessary following your kind response. Thanks in advance for your fantastic work! (Version information down below.)

1. Is it a known issue that quite often, you have to open (ie. double-click) a video file twice in Finder for mpv to open it?

2. Is there an option to automatically make videos smaller than the screen resolution play in a window, while videos larger or equal to the screen resolution play full screen?

3. Is there an option to make the “I” display show whether the current frame is a key frame, or more generally, I, P or B? (Very helpful when determining start and end points for stream copying with FFmpeg.)

4. When playing a 10 bit video on an 8 bit system (eg. the internal screen of a MacBook or an external monitor/TV), where in the chain does the conversion happen? In the mpv core, in FFmpeg or other external libraries, or in the macOS core?

5. Impressively, I can play 2160p / HEVC / BT.709 / 30 FPS videos on a Mac Mini 2011 (with hardware playback), *almost* without frame drops. How can I get rid of the last frame drops? I've already used “ffmpeg -tune fastdecode”.

6. Is it a known issue that if you fiddle with F and Cmd+1/2/3, occasionally it says “Window scale: 0.500", though the video is at 100%? (Haven’t found a reliable reproduction.) PS! When testing this, the entire window went off-screen. Window → Zoom brought it back as a 160x96 window that couldn’t be resized, and had a Firefox icon(!) in “Force Quit Applications”.

7. When will a new binary release come that includes the fix for #8490? Asking because my own compiled version a) mysteriously does not auto-load subtitles, b) lacks sftp:// support, and c) insists on using Homebrew FFmpeg instead of my own compiled FFmpeg. (I can go into details on these if a binary release is far ahead.)

8. When using “Video-zoom” or “Pan-scan”, why do subtitles grow larger when the video grows smaller (and vice versa)? In full screen, using `--sub-scale-with-window=yes` prevents this, but in window mode, neither this or its evil twin `--sub-scale-by-window` seem to make any difference (or seem to give any control over scaling whatsoever, for that matter).

9. When using the setting `--sub-use-margins`, why do the black borders have Z-priority in front of the subtitles? Because if you want to move the subtitles into the black area using R, they are hidden. (My use case is that I want subtitles either completely inside the video, or completely outside -- or possibly, the first line inside and the second outside.)

10. Is there a plug-in that lets you crop videos by creating a semi-transparent mask that shows the cropped area, displaying the crop values in the middle of the screen, and letting you adjust the cropping values in steps of 8 using the cursor keys? (If not, could you point me to tips on how to draw such a mask in Lua? The rest should be easy enough...)

```
$ mpv --version
mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Sat Jan  8 16:50:23 CET 2022
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.1

MACBOOK AIR 2017
ProductName:	macOS
ProductVersion:	12.3.1
Model Identifier: MacBookAir7,2
Processor Name: Dual-Core Intel Core i5
Processor Speed: 1,8 GHz
Total Number of Cores: 2
Memory: 8 GB

MAC MINI 2011
ProductName:	Mac OS X
ProductVersion:	10.13.6
Model Identifier: Macmini5,1
Processor Name: Intel Core i5
Processor Speed: 2,3 GHz
Total Number of Cores: 2
Memory: 8 GB

```

**Comment by CounterPillow** [comment]
> 4. When playing a 10 bit video on an 8 bit system (eg. the internal screen of a MacBook or an external monitor/TV), where in the chain does the conversion happen? In the mpv core, in FFmpeg or other external libraries, or in the macOS core?

mpv's GPU rendering, it's called dithering. The `gpu-hq` profile turns on dithering (`dither-depth=auto`). There are various options in mpv to control how the dithering works, see `mpv --list-options | grep dither`.

> 5. Impressively, I can play 2160p / HEVC / BT.709 / 30 FPS videos on a Mac Mini 2011 (with hardware playback), almost without frame drops. How can I get rid of the last frame drops? I've already used “ffmpeg -tune fastdecode”.

Set --vd-lavc-threads to a really high number like 100 if you're decode bottlenecked, apparently that works for short clips. If the rendering is bottlenecked, you're out of luck, unfortunately.

**Comment by Akemi** [comment]
1. no
2. see the docs and the various _autofit(-*)_ options
3. no
6. it's window scale not fullscreen scale. it changes the dimensions of the window previous to fullscreen. something going off screen could happen, i am not confident in saying that the window resizing code is completely without errors, since we had some edge cases before. the firefox icon things sounds more like a problem on your end.
7. we don't provide binaries or bundles. you have to ask the one bundling it.
8. my guess, you are changing the video dimensions and the subtitles scale with it
9. you are probably using another options that prevents this. since this should work.
10. there are various crop script here https://github.com/mpv-player/mpv/wiki/User-Scripts

closing since the questions have been answered. if more specific issues occur, please open a news issue specific to that issue.

**Comment by haasn** [comment]
> When playing a 10 bit video on an 8 bit system (eg. the internal screen of a MacBook or an external monitor/TV), where in the chain does the conversion happen?

It depends on the bit depth of the render surface. A verbose log will tell you
