### ISSUE TITLE
How to build single mpv-2.dll with MSYS2? 

### ISSUE THREAD

**Issue by avpnvpn** [mpv-player/mpv#10172]
Sorry for asking such a silly question since I only have basic C language knowledge and I am not a Linux guy.

I was able to build mpv-2.dll using MSYS2 following the steps described [here](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md).  But the output was 1 DLL required another 98 DLLs in mingw32/bin (libxxx.dll).

My question is how can I build one single mpv-2.dll just like I downloaded from the official site using Windows?

TIA

**Comment by xuleiisprogrammer** [comment]
I also encountered this problem，Online waiting

**Comment by xuleiisprogrammer** [comment]
@guidocella @hooke007 @Dudemanguy   Could you help us?

**Comment by jeeb** [comment]
@xuleiisprogrammer please refrain from modifying the wiki in the manner you have just done. You renamed a page - and it is not meant for asking questions, it is meant for when you have both the question and the answer, and you think that the answer is large enough to care about. Please, do not do it again.

As for the topic, In general, this is just a case of making every dependency built static that you are linking against. Whether that actually makes sense or not is a separate concern. Starting with the possible non-system C/C++ runtime libraries (generally with mingw-w64 the GNU C++ standard library and the mingw-w64 pthreads wrapper is what you might get), then zlib, lua(jit) and FFmpeg.

It's the same for *nix and Windows to be honest, same goal. Nothing really specific to mpv.

**Comment by avpnvpn** [comment]
> @xuleiisprogrammer please refrain from modifying the wiki in the manner you have just done. You renamed a page - and it is not meant for asking questions, it is meant for when you have both the question and the answer, and you think that the answer is large enough to care about. Please, do not do it again.
> 
> As for the topic, In general, this is just a case of making every dependency built static that you are linking against. Whether that actually makes sense or not is a separate concern. Starting with the possible non-system C/C++ runtime libraries (generally with mingw-w64 the GNU C++ standard library and the mingw-w64 pthreads wrapper is what you might get), then zlib, lua(jit) and FFmpeg.
> 
> It's the same for *nix and Windows to be honest, same goal. Nothing really specific to mpv.

Thank you for replying. I understood that it might not be the perfect place to ask such a question and I do agree this question is not really about mpv itself. I tried google but had no luck. It will be great if somebody happens to know how to do that and update the wiki, you know, following the steps but getting a different result could be an issue. 

Yeah, I need to improve my MinGW knowledge.

**Comment by avpnvpn** [comment]
Thank you for your concern. No, I don't have a special reason for that. Just a curiosity. Actually, I was thinking to debug it using Visual Studio but I knew that was not possible, by now.

**Comment by stax76** [comment]
mabs can do it:

https://github.com/m-ab-s/media-autobuild_suite


using wsl2 the mxe guide worked for me:

https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#example-with-mxe

config is:

DEST_OS=win32 TARGET=x86_64-w64-mingw32.static ./waf configure --enable-libmpv-shared --enable-static-build

**Comment by avpnvpn** [comment]
> mabs can do it:
> 
> https://github.com/m-ab-s/media-autobuild_suite
> 
> using wsl2 the mxe guide worked for me:
> 
> https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#example-with-mxe
> 
> config is:
> 
> DEST_OS=win32 TARGET=x86_64-w64-mingw32.static ./waf configure --enable-libmpv-shared --enable-static-build

I will give it a try. Thank you!

**Comment by stax76** [comment]
For myself, I wrote down a modification of the MXE guide here:

https://github.com/stax76/mpv.net/wiki/Building-mpv-libmpv-using-wsl2-and-Ubuntu

**Comment by xuleiisprogrammer** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/
I have succeeded，method is  wsl2+meson+ninja 
![image](https://user-images.githubusercontent.com/27334397/180588608-8ccd8edd-f404-445b-9285-844d6863d40e.png)

**Comment by xuleiisprogrammer** [comment]
but I want to get the pdb file of the mpv-2.dll
![image](https://user-images.githubusercontent.com/27334397/180588711-87b106bf-deb0-41b5-8759-6326a71c871e.png)

**Comment by xuleiisprogrammer** [comment]
Because I will apply mpv-2.dll  in VS2017 engineering project,I need Matching PDB file，eg:mpv-2.pdb
I try the cv2pdb tool ,but I failed @stax76 Cloud you help me ?

**Comment by stax76** [comment]
I can only guess without being really sure, maybe somebody else can verify it:

For debug symbols usable in VS, you need to build with the MS compiler, which isn't supported by mpv or the MS compiler.

**Comment by xuleiisprogrammer** [comment]
execuse me,https://github.com/stax76/mpv.net/wiki/Building-mpv-libmpv-using-wsl2-and-Ubuntu,Can you compile single mpv-2.dll   Independent of other libraries according to your method @stax76  ,Can you share your library file：mpv-2.dll

**Comment by stax76** [comment]
https://www.mediafire.com/file/6x3sba12x7y7dq6/mpv-debug-2022-07-26.7z/file

**Comment by xuleiisprogrammer** [comment]
![image](https://user-images.githubusercontent.com/27334397/181153455-0bd6c279-2116-4657-bcc2-41fdc2a5ed6b.png)

wow，First, I use cv2pdb to parse the PDB from your  library file mpv-2.dll,second，I use ChkMatch.exe -c check whether they matches，the result is Matched ,so your method is perfect ,it can help me get the pdb file of mpv-2.dll,I will give it a try. Thank you! @stax76

**Comment by xuleiisprogrammer** [comment]
![image](https://user-images.githubusercontent.com/27334397/181175670-1f0cecaf-145d-40f6-a5f5-0e31a8478fe7.png)
How to solve this problem? @stax76

**Comment by stax76** [comment]
Apparently it needs Python to be installed.

https://www.google.com/search?q=install+python+linux

**Comment by xuleiisprogrammer** [comment]
![image](https://user-images.githubusercontent.com/27334397/181239109-7d899171-ca3b-441b-a59c-0f67b4d07e51.png)
thank you help me ,but I also encounter this problem,I didn't find a solution @stax76

**Comment by xuleiisprogrammer** [comment]
Did you summarize all the problems you encountered during the compilation process? Could you share your solutions

**Comment by stax76** [comment]
I remember there were some issues, but unfortunately didn't note every command.
