### ISSUE TITLE
meson doesnt actually export symbols

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#10171]
Running the dll library through gendef, the .def file doesnt has `mpv_*` symbols. Also is it possible to generate .def file like with waf?

**Comment by sfan5** [comment]
Relevant PR that should have fixed this: #9463

**Comment by shinchiro** [comment]
https://github.com/mpv-player/mpv/blob/3458651010a68c2384a19ba485e81e22c825782f/libmpv/client.h#L30-L36

If I pass `--default-library=both` when building, should not `MPV_EXPORT __declspec(dllexport)` is defined too in mingw? or I'm wrong

**Comment by sfan5** [comment]
I briefly checked another project and it always uses `__declspec(dllexport)` on Windows regardless of compiler. Not sure what's correct.

**Comment by Dudemanguy** [comment]
Regarding the .def file, microsoft recommends using [__declspec](https://docs.microsoft.com/en-us/cpp/build/reference/exports?redirectedfrom=MSDN&view=msvc-170) instead. Apparently, .def can export by ordinal values but that doesn't matter for us.
