### ISSUE TITLE
`--ao=lavc` causes segmentation fault

### ISSUE THREAD

**Issue by UnkwUsr** [mpv-player/mpv#10175]
### Important Information

Provide following Information:
- mpv version: tested on latest release 1:0.34.1-4 and git commit (3458651010a68c2384a19ba485e81e22c825782f)
- Linux Distribution and Version: arch linux
- Source of the mpv binary: official arch repositories and self-builded from git
- If known which version of mpv introduced the problem: don't know
- Window Manager and version: i3 version 4.20.1
- GPU driver and version: amdgpu 22.0.0-1
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Run `mpv your_any_media_file --ao=lavc`.

### Expected behavior
No segmentation fault.

### Actual behavior
Segmentation fault.

### Log file

https://0x0.st/omTe.txt

The issue will be closed for ignoring the issue template.

### Sample files
Any media file.

### Some more details
I was just exploring mpv builtin profiles and found interesting one named `encoding`:
https://github.com/mpv-player/mpv/blob/3458651010a68c2384a19ba485e81e22c825782f/etc/builtin.conf#L32-L41
Tried it, and got segfault. Then explored that this is caused by lavc audio driver (`--ao=lavc`). Don't even know what is lavc. Seems like it is also not documented in man page.

**Comment by UnkwUsr** [comment]
Probably it is not only linux related

**Comment by Dudemanguy** [comment]
Old one, but this is definitely just a bug. `lavc` is used internally for encoding mode. You're not supposed to be able to select it on the cli, but this is possible for some reason.
