### ISSUE TITLE
Profiles Don't Work

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#10177]
### Important Information

Provide following Information:
- mpv version:  0.34.1
- macOS Version: 12.3.1
- Source of the mpv binary or bundle: Official mpv site
- If known which version of mpv introduced the problem: This one
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
 Profile: "[SubsPlease]
profile-desc=Enable deband for rips by SubsPlease
profile-cond=string.match(p.filename, "SubsPlease")~=nil
deband=yes"
only enables deband when "SubsPlease" is contained in the title of the file.

### Actual behavior
Deband is always enabled (even though "deband=no" is in my mpv.conf)

**Comment by hooke007** [comment]
cannot reproduce. where is your log?

> only enables deband when "SubsPlease" is contained in the title of the file.

You didn't set `profile-restore=copy` so it's Impossible.

**Comment by george-emerald** [comment]
And to reproduce you should change "SubsPlease" to something else and see if it only enables deband when the filename contains that something else.

**Comment by george-emerald** [comment]
Do I need a lua script for this to work?

**Comment by hooke007** [comment]
At least post your mpv.conf?

**Comment by george-emerald** [comment]
###########
# General #
###########

volume=100 # Makes the default volume 100%
volume-max=200 # Allows for volume amplification if needed

save-position-on-quit # Makes mpv remember where you left off

alang=jpn,eng # This makes sure it doesn't choose the dub on anime
slang=jpn,enm,eng # This makes sure it chooses the full subs and the honorifics track if available

hwdec=off # Software decoding is higher quality


########
# Misc #
########

border=yes # Hide the window title bar
msg-color=yes # Colour log messages on terminal
term-osd-bar=yes # Display a progress bar on the terminal
no-hidpi-window-scale # Used on 5K iMac to prevent OSX scaling
force-window=immediate
cursor-autohide=1000 # Autohide the cursor after 1s
deinterlace=no # Global reset of deinterlacing to off
fbo-format=rgba16f


##########
# Deband #
##########

deband=no # Turns off debanding by default
deband-iterations=2
deband-threshold=64
deband-range=17
deband-grain=12


#########
# Video #
#########

fullscreen = yes

profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=ewa_lanczossharp
dither-depth=auto
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes
 
vd-lavc-dr=yes

gpu-api=vulkan
vulkan-async-compute=yes
vulkan-async-transfer=yes
vulkan-queue-count=1


##############
# Colorspace #
##############

# see https://github.com/mpv-player/mpv/wiki/Video-output---shader-stage-diagram

icc-contrast=1000 # hides warnings about ICC errors; disable for OLED displays
# icc-profile-auto=yes # enable for OLED displays
target-prim=auto
# target-prim=bt.709
# target-prim=bt.2020 # target Rec.2020 (wide color gamut) for HDR TVs
target-trc=auto
gamma-auto
vf=format=colorlevels=full:colormatrix=auto
video-output-levels=full


##########
# Dither #
##########

dither-depth=auto
temporal-dither=yes


#############
# Subtitles #
#############

sub-font="Gandhi Sans"
sub-bold=yes
sub-font-size=50
sub-color="#FFFFFF"
sub-border-size=2.3
sub-border-color="#FF000000"
sub-shadow-color="#A0000000"
sub-shadow-offset=0.5
sub-pos=90

blend-subtitles=yes

sub-ass-vsfilter-blur-compat=yes # Backward compatibility for vsfilter fansubs
sub-auto=fuzzy # External subs don't have to match the file name exactly to autoload
sub-file-paths-append=ass # Search for subtitles in these relative subdirectories
sub-file-paths-append=srt
sub-file-paths-append=sub
sub-file-paths-append=subs
sub-file-paths-append=subtitles
sub-file-paths-append=eng subs
sub-file-paths-append=english subtitles
embeddedfonts=yes # Use embedded fonts for SSA/ASS subtitles
sub-fix-timing=no # Do not alter subtitle timing in any way. This was intended to fix gaps.

#########################
# Motion Interpolation  #
#########################

video-sync=display-resample # If audio and video go out of sync, instead of dropping frames, resample
                            # the audio
interpolation=yes
tscale=oversample # Make motion appear smoother by changing the way that frames are shown so that the
                  # source framerate jives better with your display's refresh rate

################
# Anti-Ringing #
################

scale-antiring=0.7 # Luma upscale deringing
dscale-antiring=0.7 # Luma downscale deringing
cscale-antiring=0.7 # Chroma upscale deringing


#######################
# Screenshot settings #
#######################

screenshot-format=png # Set screenshot format
screenshot-png-compression=0 # Range is 0 to 9. 0 being no compression.
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes # This produces a huge 48 bit-depth image


############ 
# Profiles #
############

[4k60] # 4K @ 60fps (3840x2160 UHDTV)
profile-desc=cond:((p["video-params/w"]>1920 and p["video-params/h"]>1080) and p["estimated-vf-fps"]>=31)
deband=no # turn off debanding because presume wide color gamut
interpolation=no # turn off interpolation because already 60fps 

[4k30] # 4K @ 30fps (3840x2160 UHDTV)
profile-desc=cond:((p["video-params/w"]>1920 and p["video-params/h"]>1080) and p["estimated-vf-fps"]<31)
deband=no # turn off debanding because presume wide color gamut

[full-hd60] # 1920x1080 @ 60fps (progressive ATSC)
profile-desc=cond:((p["video-params/w"]==1920 and p["video-params/h"]==1080) and not p["video-frame-info/interlaced"] and p["estimated-vf-fps"]>=31)
interpolation=no # turn off interpolation because already 60fps 

[full-hd30] # 1920x1080 @ 30fps (progressive Blu-ray)
profile-desc=cond:((p["video-params/w"]==1920 and p["video-params/h"]==1080) and not p["video-frame-info/interlaced"] and p["estimated-vf-fps"]<31)

[full-hd-interlaced] # 1920x1080i @ 30fps (HDTV, interlaced Blu-rays)
profile-desc=cond:((p["video-params/w"]==1920 and p["video-params/h"]==1080) and p["video-frame-info/interlaced"])
vf=bwdif # apply FFMPEG's bwdif deinterlacer

[hd] # 1280x720 @ 60 fps (HDTV, Blu-ray - progressive)
profile-desc=cond:(p["video-params/w"]==1280 and p["video-params/h"] == 720)
interpolation=no # turn off interpolation because already 60fps 

[sdtv-pal] # 352x576, 480x576, 544x576, 720x576 @ 30fps (PAL broadcast or DVD - interlaced)
profile-desc=cond:((p["video-params/w"]==352 or p["video-params/w"]==480 or p["video-params/w"]==544 or p["video-params/w"]==720) and p["video-params/h"] == 576)
vf=bwdif # apply FFMPEG's bwdif deinterlacer

[sdtv-ntsc] # 640x480, 704x480, 720x480 @ 30fps (NTSC DVD - interlaced)
profile-desc=cond:((p["video-params/w"]==640 or p["video-params/w"]==704 or p["video-params/w"]==720) and p["video-params/h"]==480)
vf=bwdif # apply FFMPEG's bwdif deinterlacer

[SubsPlease]
profile-desc=Enable deband for rips by SubsPlease
profile-cond=string.match(p.filename, "SubsPlease")~=nil
profile-restore=copy
deband=yes

[TTGA]
profile-desc=Enable deband for Remixes by TTGA
profile-cond=string.match(p.filename, "TTGA")~=nil
profile-restore=copy
deband=yes

[HorribleSubs]
profile-desc=Enable deband for rips by HorribleSubs
profile-cond=string.match(p.filename, "HorribleSubs")~=nil
profile-restore=copy
deband=yes


Deband is set to no as you can see.

**Comment by hooke007** [comment]
because you set `profile=gpu-hq` behind `deband=no`

**Comment by george-emerald** [comment]
You're right! Thanks, man! I hope it turns on deband when it should, though. What options am I missing now that I removed profile-gpu-hq though? Also, how do you make your code appear greyed out?

**Comment by hooke007** [comment]
> make your code appear greyed out

https://www.markdownguide.org/basic-syntax/#code

And do NOT copy other's weird conf. You'd better read the manual first to get the answer.

**Comment by george-emerald** [comment]
Also, another question. Is there any way for me to make mpv select a subtitle track if some string is in its name?

My config is an amalgamation of a lot of configsw and my own tweaking. I tried to look at yours but it's in Chinese characters. Are you Japanese?

**Comment by hooke007** [comment]
> select a subtitle track if some string is in its name

No idea.

> Are you Japanese?

No

**Comment by george-emerald** [comment]
Anyway, thanks for the help, man. Have a great day!
