### ISSUE TITLE
Profile for folder name

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#10184]
Let's say you have a folder called "Inuyasha" and all the video files are only numbers (`1.mkv` and etc),
I want to apply `gamma=-6` for all files inside "Inuyasha" folder, can it be done using profile (`mpv.conf`) or using lua script?

**Comment by guidocella** [comment]
Place this in mpv.conf after all the options that don't belong to any profile:

```
[Inuyasha]
profile-cond=(working_directory .. path):match('Inuyasha') ~= nil
gamma=-6
```

`--use-filedir-conf` (https://mpv.io/manual/stable/#per-file-options) is another option.

**Comment by Obegg** [comment]
Thank you!
