### ISSUE TITLE
Include only files which match pattern

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#10182]
How can I include files which match a lua pattern?

Using https://github.com/mpv-player/mpv/issues/2595#issuecomment-808091722 by @guidocella I came up with:

 ```lua
mp.observe_property('playlist-count', 'number', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        if not playlist[i].filename:match('%.mp4$') then
            mp.commandv('playlist-remove', i-1)
        end
    end
end)
```

I changed the condition to remove if the pattern does not match. Which would only include .mp4 files in this case. But the code doesnt work. I just get a message 'exiting no files played...'. 

Does anyone have a way they're doing this? I would be very grateful if someone could provide me with a solution. Because I debugged this and can't figure it out. Thanks!

**Comment by guidocella** [comment]
That code works for me. Maybe you're playing directories and they get excluded before expanding them?

**Comment by cerealXDD** [comment]
> That code works for me. Maybe you're playing directories and they get excluded before expanding them?

I am playing a directory. How can I wait for the playlist to load all the files from the directory?

But yeah it works with mpv <file1> <file2> etc.. But not when I put in mpv <dir>.

**Comment by cerealXDD** [comment]
Ok, I can just do mpv <dir>/*. This is good enough for me. Thanks a lot!
