### ISSUE TITLE
Message to continue playing (as on VLC)

### ISSUE THREAD

**Issue by PenguinAnt** [mpv-player/mpv#10198]
Hello,
For recently opened media files, VLC displays a banner during the first few seconds of playback that offers to resume playback where it left off.  Would it be possible to incorporate an improvement of this type in MPV?

**Comment by LaserEyess** [comment]
This already exists with mpv, see https://mpv.io/manual/master/#watch-later.

**Comment by PenguinAnt** [comment]
Thank you.
