### ISSUE TITLE
vo_gpu-next: Black screen after opening video

### ISSUE THREAD

**Issue by ProxyVT** [mpv-player/mpv#10190]
### Important Information

Provide following Information:
- mpv version: `mpv 0.34.0-292-g3458651010`
- Windows Version: `Microsoft Windows 7 Professional Build 7601 (32-bit)`
- Source of the mpv binary: `Scoop (git)` https://github.com/lukesampson/scoop-extras/blob/master/bucket/mpv-git.json
- If known which version of mpv introduced the problem: `mpv-git (20220508)`

### Reproduction steps:
1. `mpv --no-config --vo=gpu-next --player-operation-mode=pseudo-gui`
2. `mpv --no-config --vo=gpu-next <video>`

### Expected behavior:
1. mpv starts in pseudo-gui mode without any glitches.
2. mpv opens video without any errors or visual artifacts.

### Actual behavior:
1. mpv crashes on startup and popup window appears with the message "mpv has stopped working".
2. mpv opens video with black screen with no image.
3. duplicated error messages in terminal: `[vo/gpu-next] IDXGISwapChain_ResizeBuffers(p->swapchain, 0, w, h, p->csp_map.d3d11_fmt, desc.Flags): Параметр задан неверно. (E_INVALIDARG, 0x80070057) (../../../../../sr
c_packages/libplacebo/src/d3d11/swapchain.c:150)`

### Log file:
1. [pseudo-gui-msg.txt](https://github.com/mpv-player/mpv/files/8687213/pseudo-gui-msg.txt)
2. [video-msg.txt](https://github.com/mpv-player/mpv/files/8687215/video-msg.txt)

**Comment by thebombzen** [comment]
Can you reproduce this with Shinchiro's builds?

**Comment by thebombzen** [comment]
Thanks, that makes it easier to test, since I wasn't sure if it was a 32-bit-specific issue.

**Comment by ProxyVT** [comment]
> Thanks, that makes it easier to test, since I wasn't sure if it was a 32-bit-specific issue.

It seems that problem was solved in version 0.35.0, now both mpv-git and release work correctly with --vo=gpu-next.
