### ISSUE TITLE
Issue regarding hardware acceleration vaapi-copy.  hwdec=vaapi works. hwdec=vaapi-copy doesn't work.

### ISSUE THREAD

**Issue by hmm5** [mpv-player/mpv#10195]
mpv version:  
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0

Linux Distribution: Manjaro
Source of the mpv binary: manjaro repository

GPU driver and version:  
vainfo: VA-API version: 1.14 (libva 2.14.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD

I have two issues with using vaapi hardware acceleration.  

(1) If I use --hwdec=vaapi-copy or --hwdec=vaapi or using auto/autocopy, I get an error e.g. "[ffmpeg/video] h264: No support for codec h264 profile 100.
[ffmpeg/video] h264: Failed setup for format vaapi: hwaccel initialisation returned error."  Therefore hw decoding isn't enabled.  I can tell it's not enabled because intel-gpu-top and cpu show no difference.  But after the video starts, and I ctrl-h to force vaapi, hw decoding works. and intel-gpu-top/cpu shows a difference.  Is there a way to ignore the ffmpeg error and still automatically enable vaapi without having to ctrl-h every time?  Software/cpu decoding works fine, but it produces more heat and uses more energy so I would rather use hardware acceleration.

(2) vaapi-copy doesn't seem to work with ctrl-h, which is necessary because sometimes I crop videos on the fly.

**Comment by CounterPillow** [comment]
post a full log file

**Comment by hmm5** [comment]
Seems to be working now.  Not sure what was causing the error, but my laptop has a discrete ATI 8790m card in it.  A lot of config setups tell you to blacklist the radeonsi driver, etc.  I found out that the AMDGPU hardware acceleration driver still has not been completed, after setting things like radeon.si_support=1, and deleting other amdgpu entries in grub, as well as deleting stuff in modprobe.d, vaapi-copy started working with no issues.
