### ISSUE TITLE
Can I make screenshot directory by the name of current video

### ISSUE THREAD

**Issue by IamSVP94** [mpv-player/mpv#10204]
- mpv version: 0.32.0
- Linux Distribution and Version: Ubuntu 20.04.4 LTS
- Source of the mpv binary: snap

Now I have next conf file:
`screenshot-directory=~/Pictures/mpv/`
What I want:
`screenshot-directory=~/Pictures/mpv/%f`

Can I mkdir for every new screenshots by the name of current video?
For example:
Now I watch video "1.mp4" and I want to save screenshots to "/Pictures/mpv/1/"
Next I will watch video "2.mp4" and I want to save screenshots to "/Pictures/mpv/2/"

But I can't save it, because "1/" and "2/" dirs does not exist yet.
Is that possible to create it automaticly?

**Comment by hooke007** [comment]
`screenshot-template=~~/%F/%P`

https://mpv.io/manual/master/#options-screenshot-template
