### ISSUE TITLE
Cannot play 23.976 content on 50hz or 75hz display smoothly by default.

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#10205]
### Important Information
- mpv version: 0.34
- Linux Distribution and Version: Archlinux
- Source of the mpv binary: Archlinux Packages
- Window Manager and version: kwin with or without complsitor
- GPU driver and version mesa intel on mesa 22.0.2

### Reproduction steps
```mpv  /tmp/out23976.mp4  --video-sync=display-resample --video-sync-max-video-change=10 --fs --ao=null  -v -v --log-file=/tmp/out.log --no-config```

### Expected behavior
mpv to resample the audio to about 75/23.976 and then play smoothly.

### Actual behavior
microstutters

### Log file
[out.log](https://github.com/mpv-player/mpv/files/8717443/out.log)

### Sample files
http://wpage.unina.it/aorefice/sharevari/out23976.mkv

On a side note, if i do the math and play the file with --speed=1.04195862529196 (74.946/23.976/3) and without any video-sync option, it plays smoothly without any A-V desync.
```[statusline] AV: 00:00:06 / 00:06:00 (2%) x1.04 A-V:  0.000```

**Comment by haasn** [comment]
Intentional. See `--video-sync-max-video-change`

**Comment by kokoko3k** [comment]
Excuse me, but I don't understand.
As you can see from my post, I've set it to 10 which should be more than enough.
Am i missing something?

**Comment by kokoko3k** [comment]
Since I've already stated that i've set 10% to  video-sync-max-video-change and enabled video-sync=display-resample alongside it in the first post, could you please reopen this?
Thanks.
