### ISSUE TITLE
video-sync-max-factor default value prevents smooth video play of 23.975 content on 75hz display.

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#10209]
### Important Information
- mpv version: 0.34
- Linux Distribution and Version: Archlinux
- Source of the mpv binary: Archlinux Packages
- Window Manager and version: kwin with or without compositor
- GPU driver and version intel on mesa 22.0.2

### Reproduction steps
Set display to 75hz.

```mpv  /tmp/out23976.mp4  --video-sync=display-resample --video-sync-max-video-change=10 --fs --ao=null  -v -v --log-file=/tmp/out.log --no-config```

(or test on 60hz display with artificial similar ratio: ```mpv  /tmp/out23976.mkv --video-sync=display-resample  --video-sync-max-video-change=10 --ao=null --fps=19 --no-correct-pts```)

Please, note i used **--video-sync=display-resample --video-sync-max-video-change=10**
and, according to manpage, the _"Maximum speed difference in percent that is applied to video"_ is 10%, which is more than enough to accomodate the video for my case, since _"It tries multiples as well"_.
So with a multiple of 3: 75/(23.976*3)=1.04270937604271, i'm under 5%.

### Expected behavior
mpv to resample the audio to about 75/23.976, **speed-up the video** and then play smoothly.

### Actual behavior
microstutters

### Log file
[out.log](https://github.com/mpv-player/mpv/files/8717443/out.log)

### Sample files
http://wpage.unina.it/aorefice/sharevari/out23976.mkv

### Notes
I already opened [this](https://github.com/mpv-player/mpv/issues/10205), but failed to specify the problem correctly.
Now i narrowed down the issue to video-sync-max-factor, so i'm opening a new issue to cut down the noise.
Indeed, **adding video-sync-max-factor in a range between 1 and 3 makes the video to play smooth*,but unfortunately not only the manpage is not very clear on how this parameter works, but it also states that that option is for just for testing and can change in future releases, so it is not something one can count on.
I found it to fix the issue by pure trial and error, and luck, and i'm not even sure it is supposed to fix my specific issue.

(As a side note, but this is another issue i found,  I've removed the audio track by remuxing the sample file linked before and all of the video-sync options, and video-sync-max-factor still apply, Shouldn't they work just to mantain audio-video sync?)

**Comment by kokoko3k** [comment]
In video.c:
```  double scale = ratio * factor / rint(ratio * factor); ```
That factor basically prevents the player to sync to integer multiples and the default vaule of "5" gives me a Vsync ratio of 3.2.
From what i understand this kinda conflicts with video-sync-max-video-change, or at least caps it.
Also, manpages about video-sync-max-video-change suggests:
"The  default  settings  are  not  loose enough to speed up 23.976 fps video to 25 fps. We consider the pitch
change too extreme to allow this behavior by default. **Set this option to a value of 5 to enable it.**"
Which would not work alone, at least when display refresh rate is "about" 3X the source content fps.

**Comment by Dudemanguy** [comment]
I believe 67321b14402838eade127fa1d788a41906129b70 is relevant here if you want to give this another try. It directly affects this usecase (selecting a speed based on `video-sync-max-video-change`) so you may not need video-sync-max-factor anymore?

>I'm fine with the code, but I think that the manpage should be clearer in explaining how video-sync-max-factor works and that the option should not be removed or considered just for testing purposes, as it actually allows a legitimate use case.

Yes, I don't see a reason why this needs to be removed either. It looks legitimate and it's very little code. I'll put that on my TODO list.

**Comment by Dudemanguy** [comment]
No followup so closing. Feel free to make a new issue if this still exists.
