### ISSUE TITLE
YouTube subtitle bug

### ISSUE THREAD

**Issue by RafeeDaBoy** [mpv-player/mpv#10200]
### Important Information

Provide following Information:
- **mpv version:**
```mpv --version
mpv 0.34.0-292-g3458651010 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Tue May 10 05:31:48 +06 2022
FFmpeg library versions:
   libavutil       57.24.101
   libavcodec      59.27.100
   libavformat     59.23.100
   libswscale      6.6.100
   libavfilter     8.38.100
   libswresample   4.6.100
FFmpeg version: N-106844-g0a58fdfd3e
```
- **Linux Distribution and Version:** MX Linux 21
- **Source of the mpv binary:** https://github.com/mpv-player/mpv-build
- **If known which version of mpv introduced the problem:** 0.34.0-292-g3458651010
- **Window Manager and version:** KWin
- **GPU driver and version:** nvidia-driver 510.47.03

### Reproduction steps

Play a YouTube video in mpv. My run command `mpv mpv https://www.youtube.com/watch?v=wwMQ4nyJp5g`

### Expected behavior
Subtitles appearing in 2 lines
![image](https://user-images.githubusercontent.com/69535896/168697852-566df370-2c22-4894-a59d-8f88216eee90.png)

### Actual behavior
All the subtitle lines appearing at once
![image](https://user-images.githubusercontent.com/69535896/168698001-146f2948-a642-46ad-8e89-064bd2d20479.png)

### Log file
```
mpv https://www.youtube.com/watch?v=wwMQ4nyJp5g
Resuming playback. This behavior can be disabled with --no-resume-playback.
[auto_profiles] Applying auto profile: Youtube 
 (+) Video --vid=1 (*) (vp9 3840x2160 60.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
     Subs  --sid=1 --slang=en 'vtt' (webvtt) (external)
File tags:
 Uploader: Gamers Nexus
 Channel_URL: https://www.youtube.com/channel/UChIs72whgZI9w6d6FhwGGHA
[vaapi] libva: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
sh: 1: playerctl: not found
[SimpleHistory] Added the below into history
[SimpleHistory] Tear-Down: Sapphire's Excellent Cooler Design on AMD's Hottest GPU (6950 XT Nitro+ Pure) 🕒 00:00:00 
sh: 1: dunstify: not found
sh: 1: polybar-msg: not found
AO: [pulse] 48000Hz stereo 2ch float
Using hardware decoding (vdpau-copy).
VO: [gpu] 3840x2160 nv12
(Paused) AV: 00:03:49 / 00:17:23 (22%) A-V: 0.000000

```

### mpv config:

```script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp

###General###
profile=gpu-hq
vo=gpu
hdr-compute-peak=no
gpu-api=opengl
hwdec=auto
hwdec-codecs=all
fbo-format=rgba16hf
linear-downscaling=no
correct-downscaling=yes
keep-open=yes
save-position-on-quit=yes
autofit=40%
slang=en,eng,english,English,ENG,EN


###Screenshots###
screenshot-format=png
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes
screenshot-png-compression=0
screenshot-png-filter=0
screenshot-directory='~~desktop/'


###OSD/OSC###
osc=no
border=no
osd-font-size=30


###Subtitles###
sub-scale=0.8
sub-auto=fuzzy
ytdl-raw-options=sub-lang="en",write-sub=,write-auto-sub=
demuxer-mkv-subtitle-preroll=yes
sub-ass-vsfilter-blur-compat=no


###Dither and Deband###
dither-depth=auto
dither=fruit
deband=no
deband-iterations=2
deband-threshold=20
deband-range=16


###Interpolation###
interpolation=no
###tscale=box###
###tscale-window=sphinx###
###tscale-radius=0.8###
###tscale-clamp=0.0###
###video-sync=display-resample###
###blend-subtitles=yes###

[Youtube]
profile-cond=path:match('youtu.?be') ~= nil
vo=gpu
scale=ewa_lanczossharp
dscale=lanczos
cscale=lanczos
```

**Comment by hooke007** [comment]
` (+) Subs  --sid=1 --slang=en 'vtt' (webvtt) (external)`
Just another vtt issue

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/10035
https://github.com/mpv-player/mpv/issues/7214

**Comment by RafeeDaBoy** [comment]
It was a yt-dlp issue. I used apt and happened to install an old version of yt-dlp. Installed the latest version from the github page and it's fixed now

**Comment by avih** [comment]
> It was a yt-dlp issue

It wasn't. Youtube changed how they serve sub files, and as a result the yt-dl extraction broke.

yt-dlp updated their extractor to match the new youtube change, and how it works - https://github.com/yt-dlp/yt-dlp/issues/2956

So the solution is indeed to update yt-dlp, but only because youtube itself made a change which resulted in this issue.
