### ISSUE TITLE
Allow control over OSC logo

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10201]
**1. Completely hide the logo**

Allow to completely hide the logo and logo caption via `showlogo` option.

Use cases:

1. mpv.net covers the OSC logo with its own logo via overlay-add, which doesn't always work correctly.
2. some users might not like the logo design.

**2. Hide and show the logo via script message**

Use cases:

There are many menu scripts that conflict with the logo, personally I use file-browser (excellent script) and ogm (on screen menu), but there must be many like various bookmark scripts etc. Disabling the osc temporarily altogether would not work because the initial state (always, never, auto) cannot be accessed and thus be restored.

**3.  Allow replacing the logo with an image file**

Allow replacing the logo with an image file and scale option, default is 0.5 which is half the height of the window. mpc has such a feature (without scale option).

**Comment by Dudemanguy** [comment]
>Disabling the osc temporarily altogether would not work because the initial state (always, never, auto) cannot be accessed and thus be restored.

Hmm, how come? Can't you just save whatever the value of the osc property is first somewhere, turn it off, and then restore back the old value? Number 3 is not likely to happen. The mpv logo is actually just ASS that's compiled into the executable so it's not really setup for "user-friendly" tinkering. `overlay-add` is supposed to be good enough for this usecase though.

**Comment by stax76** [comment]
> Hmm, how come? Can't you just save whatever the value of the osc property is first somewhere, turn it off, and then restore back the old value?

From the client API I think I can only get the state after startup by reading the conf file and also the script-opts property, so it's a bit inconvenient, slow and don't cover the use case that the user might change the state after startup.

I proposed an okay solution here:

https://github.com/CogentRedTester/mpv-file-browser/issues/55

There are probably many scripts with that issue, one of mine here:

https://github.com/stax76/mpv-scripts/blob/main/src/osm.lua

For 1., if there are no objections, I can build it and send a PR when I have time.

**Comment by CogentRedTester** [comment]
It seems like the OSC stores the current visibility state in the `shared-script-properties` property:

![image](https://user-images.githubusercontent.com/57207260/169005716-d49e36de-7739-416a-b782-45b86d6d5474.png)

I tested and it gets updated when you cycle the visibility mode with a keybind.

**Comment by Dudemanguy** [comment]
Oh my mistake, I mixed up `osc` with `osc-visibility` (different things). Anyways, it looks like `shared-script-properties` (which I also didn't know about; the documentation is worded to be very negative for some reason) does what you need from this discussion? You can write to it so it would let you hide the OSC completely temporarily.

**Comment by Dudemanguy** [comment]
How so? I mean it's not hard of course, but is there value in letting `osc-visibility` be on (always or auto) and having a hypothetical `showlogo` and `showdropmsg` both be false? Seems like that would be the same thing as putting `osc-visibility` to `never`.

**Comment by dyphire** [comment]
> How so? I mean it's not hard of course, but is there value in letting `osc-visibility` be on (always or auto) and having a hypothetical `showlogo` and `showdropmsg` both be false? Seems like that would be the same thing as putting `osc-visibility` to `never`.

The option of adding `showlogo` seems to be a good choice. It will allow users to customize simple logo scripts instead of modifying OSC scripts for this purpose.

**Comment by CogentRedTester** [comment]
From a quick look in the code and some brief testing it would probably be as simple as modifying the following code (and adding the option obviously):

Converting this: https://github.com/mpv-player/mpv/blob/f20dbcd620ace15ff132d49e873adcb0d9527595/player/lua/osc.lua#L2575-L2605

To this:
```lua
        if (user_opts.hide_logo) then
            render_wipe()
        else
            -- render idle message
            msg.trace("idle message")
            local icon_x, icon_y = 320 - 26, 140
            local line_prefix = ("{\\rDefault\\an7\\1a&H00&\\bord0\\shad0\\pos(%f,%f)}"):format(icon_x, icon_y)

            local ass = assdraw.ass_new()
            -- mpv logo
            for i, line in ipairs(logo_lines) do
                ass:new_event()
                ass:append(line_prefix .. line)
            end

            -- Santa hat
            if is_december and not user_opts.greenandgrumpy then
                for i, line in ipairs(santa_hat_lines) do
                    ass:new_event()
                    ass:append(line_prefix .. line)
                end
            end

            ass:new_event()
            ass:pos(320, icon_y+65)
            ass:an(8)
            ass:append("Drop files or URLs to play here.")
            set_osd(640, 360, ass.text)
        end

        -- I admit I don't know what this is for, so I'm not sure if it can be disabled too
        if state.showhide_enabled then
            mp.disable_key_bindings("showhide")
            mp.disable_key_bindings("showhide_wc")
            state.showhide_enabled = false
        end
```

**Comment by Dudemanguy** [comment]
I see, that was informative. We don't like touching the osc much because it's complicated but this part is thankfully trivial.

**Comment by Dudemanguy** [comment]
Made a PR for this. I made the actual logo and the message text (Drop files...) separate options since the santa hat is already a separate option.

**Comment by stax76** [comment]
> Made a PR for this. I made the actual logo and the message text (Drop files...) separate options since the santa hat is already a separate option.

With that, I can add the mpv.net overlay logo without having to worry that the osc logo is still sometimes visible, thanks!

Regarding the overlap problem, the auto profile solution works well and is interesting as it shows advanced mpv concepts, the downside is that it requires user configuration. Here is another idea without user configuration:

mpv would provide a new property `screen-owner`, if a client wants to show a large and persistent overlay, he should set this to his client name before showing the overlay, and clear it after closing the overlay. Clients should observe this property and hide or exit if somebody else takes ownership.

If this could work, maybe provide this too, if it's not difficult to build, script authors have then a choice to decide which model they prefer and support.

**Comment by stax76** [comment]
My last idea tried to solve a problem that doesn't even exist, the problem at hand is really only that an overlay script can overlap with the osc logo. So here is the next idea:

A new osc message called `osc-hidelogo`:

`script-message osc-hidelogo`

Hides the osc logo until next time times the player enters idle state. This way, scripts that show overlays only have to send the message before adding the overlay, no action is needed closing the overlay. mpv.net and other osc scripts can easily receive the message and act upon.

**Comment by Dudemanguy** [comment]
For something like that, I think we could follow the `script-message osc-visibility` model which does alter the value of `user_opts.visibility`. The only thing though is that I think this one would just be a straight on/off. And `osc-logovisibility` (or something like that) would hide everything unconditionally (mpv logo, text and santa hat). The only thing is, though, if I add that to my PR above, I'd be tempted to just collapse `showlogo` and `showidlemsg` into one single option that turns it all off and on for simplicity's sake. I'll think about it.

**Comment by Dudemanguy** [comment]
@stax76: Is it okay to close this one now? I know the third request isn't technically fulfilled.

**Comment by stax76** [comment]
Yes, it's fine, thank you for improving the osc, I close it.
