### ISSUE TITLE
sub-ass-override Overrides Italics

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#10213]
### Important Information

Provide following Information:
- mpv version : 0.34.1
- macOS Version: 12.4
- Source of the mpv binary or bundle: Stable builds on mpv.io
- If known which version of mpv introduced the problem: this one
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
Italics remain when sub-ass-override=force is on, just with the specified styling.

### Actual behavior
Italics do not remain. Italics are negated and normal font is used. However, for some reason, if the italics are on subtitles that are on the top part of the screen, the italics remain.

### Log file

Make a log file made with -v -v or --log-file=output.txt. If you use the Bundle
from a version later than 0.32 a default log is created for your last run at
~/Library/Logs/mpv.log. You can jump to that file via the Help > Show log File…
menu. Paste the log to https://0x0.st/ or attach it to the github issue, and
replace this text with a link to it.

For some reason, I can't attach it to the issue or upload it to the specified site.

In the case of a crash please provide the macOS Crash Report (Backtrace).

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by george-emerald** [comment]
So, you're saying it's working as intended? Is there no way to retain italics when the ass script has italics?

**Comment by hooke007** [comment]
Yes.
If you want to modify some style of ASS. I think you should use https://mpv.io/manual/master/#options-sub-ass-force-style

**Comment by george-emerald** [comment]
Well, thanks for the clarification. Implementing what you're suggesting would be too hard with how I use sub-ass-override=force, but thanks anyway.
