### ISSUE TITLE
audio pitch changes even when using video-sync=display-resample

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#10210]
### Important Information
- mpv version: 0.34
- Linux Distribution and Version: Archlinux
- Source of the mpv binary: Archlinux Packages
- Window Manager and version: kwin with or without compositor
- GPU driver and version intel on mesa 22.0.2

### Reproduction steps
Set display to 60 hz
With the linked file you find later, try:
```for fps in 29 31 30 ; do mpv /tmp/out$fps.mkv --endpos=1 --video-sync=display-resample --video-sync-max-video-change=10 --audio-pitch-correction=yes -v -v --log-file=/tmp/out$fps.log; done```

### Expected behavior
since video-sync-max-video-change is the _Maximum  speed  difference in percent that is applied to video[...]_ , as expected mpv changes the playing speed:
```
grep -i compensation /tmp/out*.log
/tmp/out29.log:[   3.911][v][cplayer] Compensation factor: 0.999680
/tmp/out30.log:[   4.541][v][cplayer] Compensation factor: 1.003276
/tmp/out31.log:[   1.267][v][cplayer] Compensation factor: 0.972540
```
So, as the manpage suggests, i expect:
_--audio-pitch-correction=<yes|no>
If this is enabled (default), playing with a speed different from normal automatically inserts the scaletempo2 audio filter. For details, see audio filter section._

### Actual behavior
...but still, you'll hear a sine played at 3 different pitches.

### Log file
[out29.log](https://github.com/mpv-player/mpv/files/8727557/out29.log)
[out31.log](https://github.com/mpv-player/mpv/files/8727558/out31.log)
[out30.log](https://github.com/mpv-player/mpv/files/8727559/out30.log)

### Sample files
http://wpage.unina.it/aorefice/sharevari/out23976.mkv

### Notes
The issue does not depend on "--no-correct-pts --fps=$fps" as i explicitely tested with 3 files previously set to 29,30 and 31 fps, it is the same.
I also tried to manually adding scaletempo, scaletempo2 but the result didn't changed.

**Comment by haasn** [comment]
> If this is enabled (default), playing with a speed different from normal automatically inserts the scaletempo2 audio filter. For details, see audio filter section.

You are still playing with *speed* 1.0 as far as this section of the manual is concerned. That option only affects what happens to the `--speed` option.

Motivating reason: Small changes in pitch are much much less obvious than using scaletempo etc. with small factors.

**Comment by kokoko3k** [comment]
Any hope for it to affect speed changes made by video-sync=display-resample too?
It can change speed considerably.
I'm asking because by default it allows 1% pitch changes which is already enough to be heard.
Maybe it is ok for musical content, but imo voices sound weird.
But it become really evident when it is configured to  play 24fps on 50hz.
