### ISSUE TITLE
About autoload.lua

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#10218]
Hi, how can I add a line (or if somebody here can modify thist lua) so that it indicates _"Last file loaded"_ or _"This is the last file"_ or something like that when mpv reach the last file of current playlist and I press **playlist-next** key, of course mpv in mode keep-open always.

**Comment by hooke007** [comment]
What does this request have to do with autoload script?

```
[test_profile]
 profile-cond = p.playlist_current_pos + 1 == p.playlist_count
 profile-restore = copy
 osd-playing-msg = "the last file!!!!!!!!!!!!!!!"
```
