### ISSUE TITLE
Bash completion script

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#1021]
I wrote a script that generates a completion script for the Bash shell: [mpv-bash-completion](https://github.com/2ion/mpv-bash-completion). In doing so, it parses the output of mpv --list-options. It offers ATM:
- Regular option completion
- option argument completion
- For options that take floats or integer numbers from within a certain range as arguments (X to Y), the X and Y boundaries are offered as default completions. Floats always are marked by including a dot (.0) if not already present
- For flag-type options, "yes" or "no" completion options are offered
- Regular file name completion.

The script depends on Bash and standard UNIX utilities. I'm not sure whether this is ready to be included into TOOLS so I didn't open a pull request, but it might be fit for a link on the wiki.

**Comment by haasn** [comment]
If “it doesn't work on OS X” was grounds for removing a feature from mpv, mpv would have no features.

**Comment by 2ion** [comment]
On Sun, Oct 08, 2017 at 06:36:46AM +0000, Niklas Haas wrote:
> If “it doesn't work on OS X” was grounds for removing a feature from
> mpv, mpv would have no features.

Are you suggesting to take up the work on a pull request again? In its
current state, the completion generator is not even close to being as
small and handy as zsh.pl (in exchange for enabling more features in
Bash).
