### ISSUE TITLE
Get RGB value of pixel where mouse is?

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#10214]
How can I get the RGB value of the pixel where mouse is?

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/9899#issuecomment-1047880567

Is that not the answer?

**Comment by cerealXDD** [comment]
> [#9899 (comment)](https://github.com/mpv-player/mpv/issues/9899#issuecomment-1047880567)
> 
> Is that not the answer?

Yeah
