### ISSUE TITLE
Auto-Execute .lua script when 2 conditions met

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#10224]
I use the script [delete_file.lua](https://github.com/zenyd/mpv-scripts/blob/master/delete_file.lua) which allows me to delete video files.

I want to use this script (```script-binding delete_file/delete_file```) automatically when 2 conditions are met:
1) When video files are about to finish (15 seconds before the video ends)
2) For video files only found in ```D``` drive (not folder name, but drive name)

I have no idea how it can be achieved, but it would be very useful for me if it were to be automated.

**Comment by dyphire** [comment]
You should send a request to the script developer to open the issue tracker in the right place, not here.

**Comment by Obegg** [comment]
Well, since I don't need to change anything with the script (functions) I wasn't sure. All I need is to automatically use the command (from input.conf) ```script-binding delete_file/delete_file``` when conditions are met, which I believe is possible, but have no idea how. So since it's a more general question regarding using auto-scripts with mpv that's the reason I ask here and not there (it doesm't have to be a specific .lua script, it can be any other script which needed to be automated the same way. ).

**Comment by dyphire** [comment]
> Well, since I don't need to change anything with the script (functions) I wasn't sure. All I need is to automatically use the command (from input.conf) when conditions are met, which I believe is possible, but have no idea how. 

It is impossible to implement your request without modifying the script or creating another script for it.

You need to know that the `key_binding` and `script_message` of the script( it belongs to input.conf) cannot be used in the conditional auto-profiles.
 The `script-opts` for script can be use in the conditional auto-profiles(it is a parameter of mpv.conf).

**Comment by guidocella** [comment]
```lua
local function delete_file(_, time_pos)
    if time_pos and time_pos > mp.get_property_native('duration') - 15 then
        os.remove(mp.get_property('path'))
    end
end

mp.register_event('file-loaded', function ()
    if require 'mp.utils'.join_path(mp.get_property('working-directory'), mp.get_property('path')):match('^D:\\') then
        mp.observe_property('time-pos', 'native', delete_file)
    else
        mp.unobserve_property(delete_file)
    end
end)
```

**Comment by Obegg** [comment]
@guidocella 
Thank you! I really appriciate it!
It does work as I described but I wanted the option to "undelete", so in other words - a way to intergrate this script onto delete_file.lua (basically mark it as to delete using CTRL+DELETE)
The script you posted uses ```os.remove``` which doesn't wait for me to exit the player (unlike delete_file.lua).
I did some testing (even though I have no idea what I'm doing):
```
-- Test Auto-Delete
local function read_time(_, time_pos)
if time_pos and time_pos > mp.get_property_native('duration') - 15 then
   local work_dir1 = mp.get_property_native("working-directory")
   local file_path1 = mp.get_property_native("path")
   local s1 = file_path1:find(work_dir1, 0, true)
   local final_path1
   if s1 and s1 == 0 then
      final_path1 = file_path1
   else
      final_path1 = utils.join_path(work_dir1, file_path1)
   end
   if not contains_item(del_list, final_path1) then
      table.insert(del_list, final_path1)
   end
end
end

mp.register_event('file-loaded', function ()
    if require 'mp.utils'.join_path(mp.get_property('working-directory'), mp.get_property('path')):match('^D:\\') then
        mp.observe_property('time-pos', 'native', read_time)
    else
        mp.unobserve_property(read_time)
    end
end)

-- End test
```
I pasted this onto delete_file.lua but now my problem is that when I resume the playback of the video file it keeps changing from "undeleting current file" to "deleting current file" so it's undecicive. I need it to decide once and that's it.

**Comment by guidocella** [comment]
Just use `mp.command('script-binding delete_file/delete_file')`

**Comment by Obegg** [comment]
Thank you!!!!!!!!!!

**Comment by Obegg** [comment]
Hey, after using the script for a while, I noticed it sometimes errors.
This is the current script:
```
local function read_time(_, time_pos)
	if time_pos and time_pos > mp.get_property_native('duration') - 55 then
		mp.command('script-binding delete_file/delete_file')
		mp.unobserve_property(read_time)
	end
end

mp.register_event('file-loaded', function ()
	if require 'mp.utils' then
		mp.observe_property('time-pos', 'native', read_time)
	else
		mp.unobserve_property(read_time)
	end
end)
```

The errors I get (sometimes, not always) are:
```
delete_file_auto.lua:2: attempt to perform arithmetic on a nil value
```
(Line 2 is ```if time_pos and time_pos > mp.get_property_native('duration') - 55 then```)

**Comment by guidocella** [comment]
```lua
local function read_time(_, time_pos)
    if time_pos and time_pos > mp.get_property_native('duration', math.huge) - 55 then
        mp.command('script-binding delete_file/delete_file')
        mp.unobserve_property(read_time)
    end
end

mp.register_event('file-loaded', function ()
    mp.observe_property('time-pos', 'native', read_time)
end)
```
