### ISSUE TITLE
Keyboard Control cheatsheet / F1 help

### ISSUE THREAD

**Issue by MrSauna** [mpv-player/mpv#10222]
Just read a post on reddit complaining about the GUI. It occurred to me that mpv is missing a help menu. I use mpv for all my linux needs but still have to often consult google/manual for basic keyboard shortcuts. 

### Expected behavior of the wanted feature

1. Having some button on the GUI and a few shortcuts that lead to the help menu. I suggest "?" key and F1 for shortcuts and a clickable help button on GUI.

2. The help menu itself. It should include the basics in nicely readable manner. Here's something I found on google which is too graphic but has relevant information nicely grouped. https://i.pinimg.com/originals/74/cc/c5/74ccc5ed4e2a3c3d35cb7f2d8cd28ce8.jpg. 

### Alternative behavior of the wanted feature

Any pragmatic solution solving the need for looking up manual/google for basic shortcuts.

**Comment by Dudemanguy** [comment]
You can open up stats (`shift+i`), hit `4`, and see a list of all keybindings.

**Comment by MrSauna** [comment]
Not inaccessible in the sense of the sense of having to press two buttons but that it's hard to find.

I'm noticing that mpv installation in Arch has cut sections from the manual. For example that section. But that's not the main problem.

Previous to this my main problem was I've never heard of that menu. I've skimmed through the manual online and searched for keywords like shortcuts, cheatsheet and keyboard control (as per manual section title). Having that in more accessible place would make mpv a more approachable to new users (I've been using this for two years and even looked at the manual. Some random windows user will have no change). Also that manual section is pretty deep in the manual and in a weakly topical place... I think you get the point.

I also think that even if someone manages to find that it's not exactly a cheatsheet that's easy for anyone to get open.

**Comment by Dudemanguy** [comment]
That page hasn't even existed for a full year yet. If you want to improve the docs, that's perfectly fine but the feature is there.

**Comment by MrSauna** [comment]
@Dudemanguy 
Improving the docs is one alternative way but it's getting a bit sidetracked from my main request. Having a common F1/? shortcut to a cheatsheet is another thing and  I believe that it could greatly improve mpv for new users.

First good example that comes to mind is htop implementing just this.

**Comment by Dudemanguy** [comment]
>edit: also a list of all shortcuts and a cheatsheet are different things.

I don't agree. That page tells me exactly what keybindings do what. What else do you need? But feel free to open up a PR binding that stats page to F1 by default. Nothing currently uses it so it wouldn't be unreasonable.

**Comment by MrSauna** [comment]
Cheatsheet is something more minimal. They often have less information than a complete listing and might also have information from a different topic altogether.

**Comment by guidocella** [comment]
The manual does mention the keybinding list at the very beginning: "See also --input-test for interactive binding details by key, and the stats built-in script for key bindings list (including print to terminal)."

We discussed binding ? to show the bindings page directly when it was added but the problem is that you then have to explain how to hide the page, and there's no `stats/display-toggle-page-` script message yet.
