### ISSUE TITLE
ytdl_hook ignores http_headers in some scenarios

### ISSUE THREAD

**Issue by felixonmars** [mpv-player/mpv#10225]
### Important Information

Provide following Information:
- mpv version: 0.34.1
- Platform and Version: Arch Linux x86_64
- Source of the mpv binary: https://github.com/archlinux/svntogit-community/blob/packages/mpv/trunk/PKGBUILD

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Play any bilibili video with yt-dlp >= 2022.02.03.

### Expected behavior

Video plays as usual.

### Actual behavior

Video doesn't play with a 403 error.

### Log file

[test.log](https://github.com/mpv-player/mpv/files/8768046/test.log)

This only happens after yt-dlp upgraded to 2022.02.03 or higher, so it was considered a regression in yt-dlp and reported at https://github.com/yt-dlp/yt-dlp/issues/3788. However, yt-dlp is indeed setting `http_headers` correctly but `ytdl_hook` ignores it.

I did some investigation into yt-dlp's change, turns out [this commit](https://github.com/yt-dlp/yt-dlp/commit/f8580bf02f66ff6606d667de3172aeacc40c01fc) changed it from a single video track to a combined track of video and audio. This change made ytdl_hook go into another branch that doesn't set HTTP headers at all.

Currently `ytdl_hook` only calls `set_http_headers` when 1) the json is a playlist 2) `youtube-dl (single)`. But in this case, it's now `youtube-dl (separate)`.

**Comment by felixonmars** [comment]
I have made a simple hack to get around this problem:

```
diff --git a/player/lua/ytdl_hook.lua b/player/lua/ytdl_hook.lua
index 26913763df..b911cbf0bb 100644
--- a/player/lua/ytdl_hook.lua
+++ b/player/lua/ytdl_hook.lua
@@ -563,6 +563,7 @@ local function add_single_video(json)
         then
             format_info = "all_formats (separate)"
             res = formats_to_edl(json, all_formats, true)
+            set_http_headers(json["requested_formats"][1].http_headers)
             -- Note: since we don't delay-load muxed streams, use normal stream
             -- selection if we have to use muxed streams.
             if res and res.muxed_needed then
@@ -573,6 +574,7 @@ local function add_single_video(json)
         if (not res) and has_requested_formats then
             format_info = "youtube-dl (separate)"
             res = formats_to_edl(json, requested_formats, false)
+            set_http_headers(json["requested_formats"][1].http_headers)
         end
 
         if res then
```

Bilibili plays normally after this. But I am not an expert here, I am not sure whether `requested_formats` is always present and whether I should iterate over it to find an actual http_headers (maybe it's not set on every track?).

Attaching log after this change:

[fixed.log](https://github.com/mpv-player/mpv/files/8768232/fixed.log)

**Comment by pukkandan** [comment]
> +            set_http_headers(json["requested_formats"][1].http_headers)

If there is no `http_headers` in the requested format, you should also look for the same key directly in the infodict too. Otherwise, some other sites may not work correctly. Any `http_headers` in the infodict applies to all formats, and the headers in the `requested_formats` overrides it for the specific format

PS: the same applies to subtitles too

**Comment by zhongfly** [comment]
related to https://github.com/mpv-player/mpv/issues/9978 and https://github.com/mpv-player/mpv/issues/8786
This problem has not been solved for a long time.

**Comment by christoph-heinrich** [comment]
[This](https://gist.github.com/zhongfly/e95fa433ca912380f9f61e0910146d7e/0f46340621415ae93a91a7f3eb60d013c5bdf542#file-ytdl_hook_plus-lua) supposedly has fixed that, I'll look into it later.
