### ISSUE TITLE
Can't Use option ytdl-raw-options-append

### ISSUE THREAD

**Issue by CANNONGH** [mpv-player/mpv#10228]
I want to use yt-dlp's "cookies-from-browser" option, but when I type "ytdl-raw-options-append = cookies-from-browser = chrome" and run it, it says "[ytdl_hook] yt-dlp: error: no such option: --cookies-from-browser".
I can execute "yes-playlist=" etc. normally, but I don't know why.

**Comment by CounterPillow** [comment]
works for me. Include a --log-file and state what version of mpv and yt-dlp you're using.

**Comment by CANNONGH** [comment]
`[   0.004][v][cplayer] mpv 0.34.0-300-g9022b1b51d Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[   0.004][v][cplayer]  built on Sun May 22 12:11:51 2022
[   0.005][v][cplayer] FFmpeg library versions:
[   0.005][v][cplayer]    libavutil       57.24.101
[   0.005][v][cplayer]    libavcodec      59.28.100
[   0.005][v][cplayer]    libavformat     59.24.100
[   0.005][v][cplayer]    libswscale      6.6.100
[   0.005][v][cplayer]    libavfilter     8.38.100
[   0.005][v][cplayer]    libswresample   4.6.100
[   0.005][v][cplayer] FFmpeg version: git-2022-05-21-27cffd16
[   0.005][v][cplayer] 
[   0.005][v][cplayer] Configuration: meson build -Dprefix=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build64/install/mingw
[   0.005][v][cplayer] List of enabled features: build-date cplayer cuda-hwaccel cuda-interop d3d11 d3d9_hwaccel d3d_hwaccel direct3d dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob_win32 iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-next luajit manpage-build noexecstack openal optimize pdf-build plain-gl rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc_combined spirv-cross stdatomic threads uchardet vapoursynth vector vulkan wasapi win32 win32-desktop win32-executable win32-internal-pthreads zimg zlib
[   0.005][v][cplayer] Command line options: 'https://vrv.co/watch/G6752923R/Love-Live-Sunshine:Catch-the-Transfer-Student' '--log-file=value'
[   0.005][v][cplayer] mpv 0.34.0-300-g9022b1b51d Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[   0.005][v][cplayer]  built on Sun May 22 12:11:51 2022
[   0.005][v][cplayer] FFmpeg library versions:
[   0.005][v][cplayer]    libavutil       57.24.101
[   0.005][v][cplayer]    libavcodec      59.28.100
[   0.005][v][cplayer]    libavformat     59.24.100
[   0.005][v][cplayer]    libswscale      6.6.100
[   0.005][v][cplayer]    libavfilter     8.38.100
[   0.005][v][cplayer]    libswresample   4.6.100
[   0.005][v][cplayer] FFmpeg version: git-2022-05-21-27cffd16
[   0.005][v][cplayer] 
[   0.005][v][cplayer] Configuration: meson build -Dprefix=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build64/install/mingw
[   0.005][v][cplayer] List of enabled features: build-date cplayer cuda-hwaccel cuda-interop d3d11 d3d9_hwaccel d3d_hwaccel direct3d dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob_win32 iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-next luajit manpage-build noexecstack openal optimize pdf-build plain-gl rubberband sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc_combined spirv-cross stdatomic threads uchardet vapoursynth vector vulkan wasapi win32 win32-desktop win32-executable win32-internal-pthreads zimg zlib
[   0.005][d][global] config path: '' -> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config'
[   0.005][d][global] user path: '~~home/' -> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config'
[   0.005][d][global] user path: '~~old_home/' -> ''
[   0.005][d][global] config path: 'encoding-profiles.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/encoding-profiles.conf'
[   0.005][d][global] config path: 'mpv.conf' -> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/mpv.conf'
[   0.005][d][global] config path: 'config' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/config'
[   0.005][v][cplayer] Reading config file D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/mpv.conf
[   0.005][v][cplayer] Applying profile 'default'...
[   0.005][v][cplayer] Setting option 'ytdl-raw-options-append' = 'cookies-from-browser = "chrome:C:\Users\CANNON\AppData\Local\CentBrowser\User Data\Default"' (flags = 4)
[   0.005][v][cplayer] Setting option 'log-file' = 'value' (flags = 8)
[   0.006][d][global] config path: 'input.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/input.conf'
[   0.006][d][global] user path: 'value' -> 'value'
[   0.006][d][osc] Loading lua script @osc.lua...
[   0.007][d][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.007][d][stats] Loading lua script @stats.lua...
[   0.007][d][osc] loading mp.defaults
[   0.007][d][ytdl_hook] loading mp.defaults
[   0.007][d][console] Loading lua script @console.lua...
[   0.007][d][stats] loading mp.defaults
[   0.007][d][auto_profiles] Loading lua script @auto_profiles.lua...
[   0.007][d][console] loading mp.defaults
[   0.007][d][auto_profiles] loading mp.defaults
[   0.007][d][global] config path: 'scripts' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/scripts'
[   0.007][v][cplayer] Waiting for scripts...
[   0.007][d][osc] loading @osc.lua
[   0.007][d][ytdl_hook] loading @ytdl_hook.lua
[   0.007][d][stats] loading @stats.lua
[   0.007][d][console] loading @console.lua
[   0.008][d][auto_profiles] loading @auto_profiles.lua
[   0.008][d][auto_profiles] Exiting...
[   0.008][d][ytdl_hook] reading options for ytdl_hook 
[   0.008][d][global] config path: 'script-opts/ytdl_hook.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/script-opts/ytdl_hook.conf'
[   0.008][d][ytdl_hook] script-opts/ytdl_hook.conf not found. 
[   0.008][d][global] config path: 'lua-settings/ytdl_hook.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/lua-settings/ytdl_hook.conf'
[   0.008][d][ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[   0.008][d][stats] reading options for stats 
[   0.008][d][console] reading options for console 
[   0.008][d][global] config path: 'script-opts/stats.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/script-opts/stats.conf'
[   0.008][d][stats] script-opts/stats.conf not found. 
[   0.008][d][global] config path: 'script-opts/console.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/script-opts/console.conf'
[   0.008][d][global] config path: 'lua-settings/stats.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/lua-settings/stats.conf'
[   0.008][d][console] script-opts/console.conf not found. 
[   0.008][d][stats] lua-settings/stats.conf not found. 
[   0.008][d][global] config path: 'lua-settings/console.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/lua-settings/console.conf'
[   0.008][d][console] lua-settings/console.conf not found. 
[   0.009][d][global] config path: 'fonts' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/fonts'
[   0.009][d][osd/libass] ASS library version: 0x1600000 (runtime 0x1600000)
[   0.009][v][osd/libass] libass API version: 0x1600000
[   0.009][v][osd/libass] libass source: commit: a2b39cde4ecb74d5e6fccab4a5f7d8ad52b2b1a4
[   0.009][d][osc] reading options for osc 
[   0.009][d][global] config path: 'script-opts/osc.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/script-opts/osc.conf'
[   0.009][d][osc] script-opts/osc.conf not found. 
[   0.009][d][global] config path: 'lua-settings/osc.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/lua-settings/osc.conf'
[   0.009][d][osc] lua-settings/osc.conf not found. 
[   0.010][v][osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 4.3.0 (COMPLEX)
[   0.010][d][global] config path: 'subfont.ttf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/subfont.ttf'
[   0.010][d][global] config path: 'fonts.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/fonts.conf'
[   0.010][v][osd/libass] Setting up fonts...
[   0.011][v][osd/libass] Using font provider directwrite (with GDI)
[   0.011][v][osd/libass] Done.
[   0.011][d][cplayer] Run command: define-section, flags=64, args=[name="input_stats", contents="", flags="default"]
[   0.011][d][cplayer] Run command: enable-section, flags=64, args=[name="input_stats", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.011][d][cplayer] Run command: define-section, flags=64, args=[name="input_forced_stats", contents="", flags="force"]
[   0.011][d][cplayer] Run command: enable-section, flags=64, args=[name="input_forced_stats", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.011][d][cplayer] Run command: define-section, flags=64, args=[name="input_console", contents="", flags="default"]
[   0.011][d][cplayer] Run command: enable-section, flags=64, args=[name="input_console", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.011][d][cplayer] Run command: define-section, flags=64, args=[name="input_forced_console", contents="", flags="force"]
[   0.011][d][cplayer] Run command: enable-section, flags=64, args=[name="input_forced_console", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.012][d][cplayer] Run command: define-section, flags=64, args=[name="showhide", contents="mouse_move script-binding osc/__keybinding1\nmouse_leave script-binding osc/__keybinding2\n", flags="force"]
[   0.012][d][cplayer] Run command: define-section, flags=64, args=[name="showhide_wc", contents="mouse_move script-binding osc/__keybinding3\nmouse_leave script-binding osc/__keybinding4\n", flags="force"]
[   0.012][d][cplayer] Run command: enable-section, flags=64, args=[name="showhide", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.012][d][cplayer] Run command: enable-section, flags=64, args=[name="showhide_wc", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.012][d][cplayer] Run command: define-section, flags=64, args=[name="input", contents="mbtn_left script-binding osc/__keybinding5\nshift+mbtn_left script-binding osc/__keybinding6\nmbtn_right script-binding osc/__keybinding7\nmbtn_mid script-binding osc/__keybinding8\nwheel_up script-binding osc/__keybinding9\nwheel_down script-binding osc/__keybinding10\nmbtn_left_dbl ignore\nshift+mbtn_left_dbl ignore\nmbtn_right_dbl ignore\n", flags="force"]
[   0.012][d][cplayer] Run command: enable-section, flags=64, args=[name="input", flags=""]
[   0.012][d][cplayer] Run command: define-section, flags=64, args=[name="window-controls", contents="mbtn_left script-binding osc/__keybinding11\n", flags="force"]
[   0.012][d][cplayer] Run command: enable-section, flags=64, args=[name="window-controls", flags=""]
[   0.012][d][cplayer] Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-visibility=auto"]
[   0.012][v][cplayer] Set property: shared-script-properties -> 1
[   0.012][d][cplayer] Run command: disable-section, flags=64, args=[name="input"]
[   0.012][d][cplayer] Run command: disable-section, flags=64, args=[name="window-controls"]
[   0.012][d][cplayer] Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-margins=0.000000,0.000000,0.000000,0.000000"]
[   0.012][v][cplayer] Set property: shared-script-properties -> 1
[   0.012][v][cplayer] Done loading scripts.
[   0.012][d][global] config path: 'watch_later' -> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/watch_later'
[   0.012][v][cplayer] Running hook: ytdl_hook/on_load
[   0.012][v][ytdl_hook] ytdl:// hook 
[   0.012][v][ytdl_hook] not a ytdl:// url 
[   0.012][d][cplayer] Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-margins=0.000000,0.000000,0.000000,0.000000"]
[   0.012][v][cplayer] Set property: shared-script-properties -> 1
[   0.012][v][ffmpeg] Opening https://vrv.co/watch/G6752923R/Love-Live-Sunshine:Catch-the-Transfer-Student
[   0.012][d][osc] osc_init 
[   0.013][d][cplayer] Run command: change-list, flags=64, args=[name="shared-script-properties", operation="append", value="osc-margins=0.000000,0.000000,0.000000,0.000000"]
[   0.013][v][cplayer] Set property: shared-script-properties -> 1
[   0.013][d][global] config path: 'fonts' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/fonts'
[   0.013][d][osd/libass] ASS library version: 0x1600000 (runtime 0x1600000)
[   0.013][v][osd/libass] libass API version: 0x1600000
[   0.013][v][osd/libass] libass source: commit: a2b39cde4ecb74d5e6fccab4a5f7d8ad52b2b1a4
[   0.013][v][osd/libass] Shaper: FriBidi 1.0.12 (SIMPLE) HarfBuzz-ng 4.3.0 (COMPLEX)
[   0.014][d][global] config path: 'subfont.ttf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/subfont.ttf'
[   0.014][d][global] config path: 'fonts.conf' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/fonts.conf'
[   0.014][v][osd/libass] Setting up fonts...
[   0.014][v][osd/libass] Using font provider directwrite (with GDI)
[   0.014][v][osd/libass] Done.
[   0.014][d][cplayer] Run command: define-section, flags=64, args=[name="input_osc", contents="", flags="default"]
[   0.014][d][cplayer] Run command: enable-section, flags=64, args=[name="input_osc", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.014][d][cplayer] Run command: define-section, flags=64, args=[name="input_forced_osc", contents="", flags="force"]
[   0.014][d][cplayer] Run command: enable-section, flags=64, args=[name="input_forced_osc", flags="allow-hide-cursor+allow-vo-dragging"]
[   0.043][d][ffmpeg] tcp: Starting connection attempt to 13.227.57.116 port 443
[   0.054][d][ffmpeg] tcp: Successfully connected to 13.227.57.116 port 443
[   0.409][d][ffmpeg] tcp: Starting connection attempt to 13.227.57.116 port 443
[   0.423][d][ffmpeg] tcp: Successfully connected to 13.227.57.116 port 443
[   0.481][d][ffmpeg] resize stream to 131072 bytes, drop 0 bytes
[   0.481][v][ffmpeg] Mime-type: 'text/plain; charset=utf-8'
[   0.481][d][ffmpeg] Stream opened successfully.
[   0.481][v][demux] Trying demuxers for level=normal.
[   0.481][d][demux] Trying demuxer: disc (force-level: normal)
[   0.481][d][demux] Trying demuxer: edl (force-level: normal)
[   0.482][d][demux] Trying demuxer: cue (force-level: normal)
[   0.482][d][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.482][d][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.482][d][demux] Trying demuxer: mkv (force-level: normal)
[   0.482][d][demux] Trying demuxer: libarchive (force-level: normal)
[   0.482][d][demux] Trying demuxer: lavf (force-level: normal)
[   0.486][v][lavf] No format found, try lowering probescore or forcing the format.
[   0.486][d][demux] Trying demuxer: mf (force-level: normal)
[   0.486][d][demux] Trying demuxer: playlist (force-level: normal)
[   0.486][d][demux] Trying demuxer: null (force-level: normal)
[   0.486][v][demux] Trying demuxers for level=unsafe.
[   0.486][d][demux] Trying demuxer: disc (force-level: unsafe)
[   0.486][d][demux] Trying demuxer: edl (force-level: unsafe)
[   0.486][d][demux] Trying demuxer: cue (force-level: unsafe)
[   0.486][d][demux] Trying demuxer: rawaudio (force-level: unsafe)
[   0.486][d][demux] Trying demuxer: rawvideo (force-level: unsafe)
[   0.486][d][demux] Trying demuxer: mkv (force-level: unsafe)
[   0.486][d][demux] Trying demuxer: libarchive (force-level: unsafe)
[   0.486][d][ffmpeg] resize stream to 262144 bytes, drop 0 bytes
[   0.486][d][demux] Trying demuxer: lavf (force-level: unsafe)
[   0.488][d][ffmpeg] resize stream to 131072 bytes, drop 0 bytes
[   0.489][v][lavf] No format found, try lowering probescore or forcing the format.
[   0.489][d][demux] Trying demuxer: mf (force-level: unsafe)
[   0.489][d][demux] Trying demuxer: playlist (force-level: unsafe)
[   0.489][d][demux] Trying demuxer: null (force-level: unsafe)
[   0.489][d][ffmpeg] AVIOContext: Statistics: 15751 bytes read, 0 seeks
[   0.489][v][cplayer] Opening failed or was aborted: https://vrv.co/watch/G6752923R/Love-Live-Sunshine:Catch-the-Transfer-Student
[   0.489][v][cplayer] Running hook: ytdl_hook/on_load_fail
[   0.489][v][ytdl_hook] full hook 
[   0.489][d][global] config path: 'yt-dlp.exe' -/-> 'D:/Desktop/mpv-x86_64-20220522-git-9022b1b/portable_config/yt-dlp.exe'
[   0.489][v][ytdl_hook] No youtube-dl found with path yt-dlp.exe in config directories 
[   0.489][d][ytdl_hook] Running: yt-dlp --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --cookies-from-browser   "chrome:C:\Users\CANNON\AppData\Local\CentBrowser\User Data\Default" --all-subs --no-playlist -- https://vrv.co/watch/G6752923R/Love-Live-Sunshine:Catch-the-Transfer-Student 
[   0.489][d][cplayer] Run command: subprocess, flags=64, args=[args="yt-dlp,--no-warnings,-J,--flat-playlist,--sub-format,ass/srt/best,--format,bestvideo+bestaudio/best,--cookies-from-browser , \"chrome:C:\\Users\\CANNON\\AppData\\Local\\CentBrowser\\User Data\\Default\",--all-subs,--no-playlist,--,https://vrv.co/watch/G6752923R/Love-Live-Sunshine:Catch-the-Transfer-Student", playback_only="yes", capture_size="67108864", capture_stdout="yes", capture_stderr="yes", detach="no", env="", stdin_data="", passthrough_stdin="no"]
[   1.569][v][ytdl_hook] Found youtube-dl with path yt-dlp.exe in PATH 
[   1.569][v][ytdl_hook] status: 2 
[   1.569][v][ytdl_hook] reason:  
[   1.569][v][ytdl_hook] stdout:  
[   1.569][v][ytdl_hook] stderr: Usage: yt-dlp [OPTIONS] URL [URL...]
[   1.569][v][ytdl_hook] 
[   1.569][v][ytdl_hook] yt-dlp: error: no such option: --cookies-from-browser 
[   1.569][v][ytdl_hook]  
[   1.570][e][ytdl_hook] Usage: yt-dlp [OPTIONS] URL [URL...]
[   1.571][e][ytdl_hook] 
[   1.571][e][ytdl_hook] yt-dlp: error: no such option: --cookies-from-browser 
[   1.571][e][ytdl_hook] youtube-dl failed: unexpected error occurred 
[   1.571][v][cplayer] finished playback, unrecognized file format (reason 4)
[   1.572][e][cplayer] Failed to recognize file format.
[   1.572][i][cplayer] 
[   1.573][i][cplayer] Exiting... (Errors when loading file)
[   1.573][d][ytdl_hook] Exiting...
[   1.573][d][console] Exiting...
[   1.573][d][stats] Exiting...
[   1.573][d][cplayer] Run command: change-list, flags=64, args=[name="shared-script-properties", operation="remove", value="osc-margins"]
[   1.573][v][cplayer] Set property: shared-script-properties -> 1
[   1.574][d][osc] Exiting...
`

**Comment by CANNONGH** [comment]
mpv version is [mpv-x86_64-20220522-git-9022b1b].
yt-dlp version is 2022.05.18

**Comment by thebombzen** [comment]
Your yt-dlp version is probably older than that. Update to the latest release of yt-dlp and mpv, and try again.

**Comment by error-reporting** [comment]
> mpv version is [mpv-x86_64-20220522-git-9022b1b]. yt-dlp version is 2022.05.18

use ytdl-raw-options-append="cookies-from-browser=chrome" for config and --ytdl-raw-options-append=cookies-from-browser=chrome for cli
