### ISSUE TITLE
Any news on the next "0.X.Y" release?

### ISSUE THREAD

**Issue by versedwildcat** [mpv-player/mpv#10226]
Hello,
Seeing how it's been over 300 commits and nearly 5 months since [v0.34.1](https://github.com/mpv-player/mpv/releases/latest), I was wondering if there are any plans for the next release.
It would be more convenient to have a more recent version included in most package managers. 
Thanks!

**Comment by 24fpsDaVinci** [comment]
would be great if there was a release around major linux releases

**Comment by bqv** [comment]
+1, any explanation at least? @Dudemanguy? @jeeb?

**Comment by versedwildcat** [comment]
<3
