### ISSUE TITLE
About Steam deck fixed refresh rate

### ISSUE THREAD

**Issue by lavilao** [mpv-player/mpv#10238]
This is something that I have always asked myself about, can I just set my display refresh rate to 48hz so I can watch anime at 48fps without jitter/judger? I always thought that I could not because if you can then what is the atractive of VRR monitors, surely there must be a really bad reason why normal displays cant do that, yet valve did it on a comercial product. That make me think a lot so my question is can I just set my screen refresh rate to any arbitrary refresh rate I want? My laptop screen is a 60hz(59.989) and has another 40hz mode (although is only on windows 10, on linux it only shows 60hz), so can I do it on x11 or wayland? thanks in advice

**Comment by Dudemanguy** [comment]
Sure you can. I personally set my refresh rate to 48hz myself. Whether or not this actually works depends highly on your monitor, window manager, etc.

**Comment by lavilao** [comment]
Thanks for answering, with xrandr and cvt right? I have done a little research and the ways to set a custom resolution/ refresh rate on wayland are... ew.

**Comment by Dudemanguy** [comment]
You might need to setup a custom modeline in xorg. It's been a while since I've done it but yeah xrandr and cvt are what is normally used. With wayland, it's compositor dependent. Sway/wlroots supports custom modes. I'm not sure about the rest.

**Comment by lavilao** [comment]
sway would not even recognize lower resolutions than native on my laptop (although it did worked on my old crt), and apparently mesa 22 broke kde and gnome ability to recognize my display 40hz mode (just installed ubuntu 20.04 and it is right there) maybe now it will work
