### ISSUE TITLE
Subtitles within sub directories

### ISSUE THREAD

**Issue by indeedwatson** [mpv-player/mpv#10231]
In my config file I have the options:

```
sub-file-paths=sub:subtitles:Subs:subs
sub-auto=all
```

But I noticed some subs were not being picked up, so I double check and it turns out that the subtitles are in:

`videos/series name/Subs/series name ep 01/english.srt`
`videos/series name/Subs/series name ep 02/english.srt`
`videos/series name/series name ep 01.mkv`
`videos/series name/series name ep 02.mkv`
`etc...`

Is there any way to have mpv pick them up automatically?

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/issues/9767#issuecomment-1022207724

**Comment by indeedwatson** [comment]
@guidocella Thanks! That worked.
