### ISSUE TITLE
the display of subtitles is crooked in the screenshot when using --vo=gpu-next in 4k video

### ISSUE THREAD

**Issue by AdventurerRussia** [mpv-player/mpv#10237]
when you use --vo=gpu-next and take a screenshot of a 4k video on a full hd screen, the subtitles are captured crookedly and are small at the top left
---
--vo=gpu-next
![mpv-shot0230-min](https://user-images.githubusercontent.com/14019010/170768693-a19f7cf3-dd6f-4821-831e-688a4f40a710.png)
off --vo=gpu-next
![mpv-shot0233-min](https://user-images.githubusercontent.com/14019010/170768745-221429a6-c835-41fe-b96a-03f5f145cf5a.png)
--------
[cplayer] mpv 0.34.0-301-gdefb02daa4 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri May 27 01:10:12 2022
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       57.25.100
[cplayer]    libavcodec      59.32.100
[cplayer]    libavformat     59.24.100
[cplayer]    libswscale      6.6.100
[cplayer]    libavfilter     8.39.100
[cplayer]    libswresample   4.6.100
[cplayer] FFmpeg version: git-2022-05-26-0dcbe1c1
----
Выпуск	Windows 11 Pro
Версия	21H2
Дата установки	‎13.‎04.‎2022
Сборка ОС	22000.708
Взаимодействие	Windows Feature Experience Pack 1000.22000.708.0

**Comment by snylonue** [comment]
probably related issue #9923
