### ISSUE TITLE
Hardware decoding not working with nvidia gpu

### ISSUE THREAD

**Issue by Zabooby** [mpv-player/mpv#10243]
I have a geforce mx450 which supports hardware decoding if you check [here](https://en.wikipedia.org/wiki/Nvidia_NVDEC) but it doesn't seem to work with mpv even though in task manager its says mpv is using the dedicated graphics. I should note that hwdec works fine with integrated graphics.

Relevant part of mpv conf:

```
profile=gpu-hq

hwdec=auto

vo=gpu
```
[nvidia](https://imgur.com/gallery/nZvW5iw)

[integrated](https://imgur.com/gallery/s9Ygw3P)

mpv 0.34.0-300-g9022b1b51d - version
11- windows version
shinchiro- source of the mpv binary

I have also tried with a fresh install but it didn't work.

Could someone explain how to get the log file (I'm quite new to mpv)

Thanks!

Logs
https://pastebin.com/raw/rBQZXuzH

**Comment by thebombzen** [comment]
`mpv --log-file=mpv-sucks.log`

**Comment by Zabooby** [comment]
I put this in my mpv.conf right?

**Comment by thebombzen** [comment]
either `--log-file=mpv-sucks.log` on the command line, or you could put something like `log-file=~/Desktop/mpv-sucks.log` in mpv.conf to put the log file on your desktop or something.

**Comment by Zabooby** [comment]
Yup I've got the log file updating the op.

**Comment by thebombzen** [comment]
Please upload the file to a paste site like https://pastebin.com/ or equivalent rather and provide a link, rather than embedding in the issue directly.

**Comment by Zabooby** [comment]
I added a link to pastebin

**Comment by Zabooby** [comment]
Also I did this on a fresh install not my current setup as the log file was huge. But I get the issue anyway so it should be fine.

**Comment by jeeb** [comment]
The relevant bits regarding decoder initialization with hwdec are:
```
[   8.868][v][vd] Opening decoder h264
[   8.868][v][vd] Looking at hwdec h264-d3d11va...
[   8.868][v][vo/gpu] Loading hwdec drivers for format: 'd3d11'
[   8.868][v][vo/gpu] Loading hwdec driver 'd3d11-egl'
[   8.868][v][vo/gpu] Loading failed.
[   8.868][v][vo/gpu] Loading hwdec driver 'd3d11va'
[   8.879][v][vd] Trying hardware decoding via h264-d3d11va.
[   8.880][v][vd] Pixel formats supported by decoder: cuda dxva2_vld d3d11va_vld d3d11 yuv420p
[   8.880][v][vd] Codec profile: Main (0x4d)
[   8.882][v][vd] Requesting pixfmt 'd3d11' from decoder.
[   8.882][d][ffmpeg/video] h264: Decoder GUIDs reported as supported:
[   8.882][d][ffmpeg/video] h264: {33fcfe41-de46-4a49-861b-ac71110649d5} 103 106 107
[   8.882][d][ffmpeg/video] h264: {914c84a3-4078-4fa9-984c-e2f262cb5c9c} 103 106
[   8.882][d][ffmpeg/video] h264: No decoder device for codec found
[   8.882][e][ffmpeg/video] h264: Failed setup for format d3d11: hwaccel initialisation returned error.
[   8.882][v][vd] Pixel formats supported by decoder: cuda dxva2_vld d3d11va_vld yuv420p yuv420p
[   8.882][v][vd] Codec profile: Main (0x4d)
[   8.882][v][vd] Requesting pixfmt 'yuv420p' from decoder.
[   8.882][d][ffmpeg/video] h264: Reinit context to 1920x1088, pix_fmt: yuv420p
[   8.887][v][vd] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
```

**Comment by Zabooby** [comment]
So what's causing it to load because hwdec works fine with integrated graphics?

**Comment by thebombzen** [comment]
What's your NVidia Driver version?

**Comment by jeeb** [comment]
You can see it listing the "Decoder GUIDs reported as supported".

Compare that to my GTX 1080:
```
[ffmpeg/video] h264: Decoder GUIDs reported as supported:
[ffmpeg/video] h264: {86695f12-340e-4f04-9fd3-9253dd327460} 103 106
[ffmpeg/video] h264: {ee27417f-5e28-4e65-beea-1d26b508adc9} 103 106
[ffmpeg/video] h264: {6f3ec719-3735-42cc-8063-65cc3cb36616} 103 106
[ffmpeg/video] h264: {1b81bea4-a0c7-11d3-b984-00c04f2e73c5} 103 106
[ffmpeg/video] h264: {1b81bea3-a0c7-11d3-b984-00c04f2e73c5} 103 106
[ffmpeg/video] h264: {32fcfe3f-de46-4a49-861b-ac71110649d5} 103 106
[ffmpeg/video] h264: {d79be8da-0cf1-4c81-b82a-69a4e236f43d} 103 106
[ffmpeg/video] h264: {f9aaccbb-c2b6-4cfc-8779-5707b1760552} 103 106
[ffmpeg/video] h264: {1b81be68-a0c7-11d3-b984-00c04f2e73c5} 103 106
[ffmpeg/video] h264: {5b11d51b-2f4c-4452-bcc3-09f2a1160cc0} 103 106
[ffmpeg/video] h264: {107af0e0-ef1a-4d19-aba8-67a163073d13} 104 106
[ffmpeg/video] h264: {20bb8b0a-97aa-4571-8e99-64e60606c1a6} 104 106
[ffmpeg/video] h264: {15df9b21-06c4-47f1-841e-a67c97d7f312} 103 106
[ffmpeg/video] h264: {efd64d74-c9e8-41d7-a5e9-e9b0e39fa319} 103 106
[ffmpeg/video] h264: {ed418a9f-010d-4eda-9ae3-9a65358d8d2e} 103 106
[ffmpeg/video] h264: {9947ec6f-689b-11dc-a320-0019dbbc4184} 103 106
[ffmpeg/video] h264: {33fcfe41-de46-4a49-861b-ac71110649d5} 103 106 107
[ffmpeg/video] h264: {463707f8-a1d0-4585-876d-83aa6d60b89e} 103 106
[ffmpeg/video] h264: {6affd11e-1d96-42b1-a215-93a31f09a53d} 103 106
[ffmpeg/video] h264: {914c84a3-4078-4fa9-984c-e2f262cb5c9c} 103 106
[ffmpeg/video] h264: Reinit context to 1920x1040, pix_fmt: d3d11
```

**Comment by Zabooby** [comment]
On the nvidia control panel it says the driver version is 512.95

**Comment by jeeb** [comment]
For the record, there are some laptop devices where for whatever reason on the nvidia silicon the hardware decoding functionality has either been disabled or ripped off. I would first check out the drivers and then something like [DXVA checker](https://bluesky-soft.com/en/DXVAChecker.html) to get a (hopefully) clear view of the capabilities.

**Comment by philipl** [comment]
You can read the official nvidia support [matrix](https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new) and it says that the MX450 has no hardware decode or encode support.

**Comment by Zabooby** [comment]
I see, is there a way to let nvidia graphics run mpv while letting intel xe graphics do hwdec? Or is it only one or the other?

**Comment by philipl** [comment]
There's no efficient way. If you use `d3d11va-copy` it will decode with the Intel and render with nvidia but it will do a wasteful memcpy in the middle from the iGPU's memory (which is physically system memory) to the CPU's system memory and then to the nvidia GPU's memory. That will increase your CPU consumption by some amount, although probably not significantly if you're not dealing with 4K content. If your priority is power consumption, you need to do everything on the iGPU.

**Comment by Zabooby** [comment]
So if I want the best quality with no concern about power consumption would I want to use both or would using dgraphics with no hwdec be best?

**Comment by philipl** [comment]
Yes, if you want to prioritise using fancy shaders that the igpu can't handle, I would use d3d11va-copy + dgpu.

**Comment by Zabooby** [comment]
Ok, thanks for all the help!

**Comment by Zabooby** [comment]
> Yes, if you want to prioritise using fancy shaders that the igpu can't handle, I would use d3d11va-copy + dgpu.

I have been using (full config [here](https://github.com/Zabooby/mpv-config)):
```
profile=gpu-hq
hwdec=d3d11va-copy
vo=gpu
```

to decode with the Intel integrated gpu and render with nvidia gpu like we discussed above but I just noticed this message in the console. Any ideas why?
![image](https://user-images.githubusercontent.com/78969986/209969780-96e3f93f-557e-4275-b052-84985985975a.png)
