### ISSUE TITLE
How to select english subtitles on YouTube with "--slang"

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#10245]
Hi,
It seems there has been some changes from youtube.com regarding their subtitle track names : 
The command `mpv --slang=eng,en` does not work anymore.

The subtitle track names are not always the same : 
```shell
$ yt-dlp --list-subs https://www.youtube.com/watch?v=6vfqYwfTqlE https://www.youtube.com/watch?v=iT88jBAoVIM https://www.youtube.com/watch?v=ThsYX4RBtbw | egrep "captions|English from"
[info] Available automatic captions for 6vfqYwfTqlE:
en-en-nP7-2PuUl7o      English from English - en               vtt, ttml, srv3, srv2, srv1, json3
[info] Available automatic captions for iT88jBAoVIM:
en-it      English from Italian               vtt, ttml, srv3, srv2, srv1, json3
[info] Available automatic captions for ThsYX4RBtbw:
en-en      English from English               vtt, ttml, srv3, srv2, srv1, json3
```

### Log file

[mpv_question_10245.log](https://github.com/mpv-player/mpv/files/8792192/mpv_question_10245.log)

**Comment by amnah** [comment]
```slang="eng,en,en-en"```

**Comment by sebma** [comment]
> `slang="eng,en,en-en"`

@amnah This does not work on the first two videos I gave above.

**Comment by amnah** [comment]
you can just add the extra language strings ... (the ones you listed in your first post)

**Comment by sebma** [comment]
@amnah OK. That would give : 

`slang=eng,en,en-en-nP7-2PuUl7o,en-en,en-it,fra,fre,fr,fr-en-nP7-2PuUl7o,fr-en,fr-it`

It works now, thanks :+1:

**Comment by garoto** [comment]
> The subtitle track names are not always the same

It almost looks like an intentional change to break subtitle parsing by 3rd party utilities. Crazy talk I know, but imagine google actually "being evil" in 2022.

```
en-US-cvfXDfbeED0 English (United States) - Captions vtt, ttml, srv3, srv2, srv1, json3
en-1JJtFDtHuZg English - French Speakers Only vtt, ttml, srv3, srv2, srv1, json3
en-shN438sLfcs English - Full Closed Captions vtt, ttml, srv3, srv2, srv1, json3
en-nP7-2PuUl7o English - en vtt, ttml, srv3, srv2, srv1, json3
```

**Comment by sebma** [comment]
Here is an automated way to generate the `slang` string : 
```shell
$ for lang in en fr de;do printf "%s,%s-en,%s-it,%s-en-nP7-2PuUl7o," $lang $lang $lang $lang;done | sed "s/,$/\n/"
en,en-en,en-it,en-en-nP7-2PuUl7o,fr,fr-en,fr-it,fr-en-nP7-2PuUl7o,de,de-en,de-it,de-en-nP7-2PuUl7o
```

**Comment by torontal7** [comment]
This is a pure stupidity! There must be enough to give "--slang=en" to select automatically ANY English subtitles. How the hell would we know what is the exact name og the English sub name in ceratain video? I wrote in my mpv.conf file "slang,en,eng,enUS,en-US=" but in this video [https://www.youtube.com/watch?v=Zus-uWC9qfM](https://www.youtube.com/watch?v=Zus-uWC9qfM) the name is "en-GB" so my config did not work! If I correct my mpv.conf maybe tomorrow will be problem with a Canadian English video... So, the only acceptable way should be to give a two letter language code (en, it, pl, hu ...) and this should select any subvariant of the language.

**Comment by kasper93** [comment]
It should already work like that in the recent version of mpv.

**Comment by torontal7** [comment]
If so, that is very good, I use now version 0.32.0.
