### ISSUE TITLE
Allow setting a key to identify a file when using water later features

### ISSUE THREAD

**Issue by snylonue** [mpv-player/mpv#10242]
Currently, mpv uses the path (or filename) to find a watch later config.
However, when it comes to real urls extracted from video platforms, which changes often, it won't work any more.

### Expected behavior of the wanted feature
Add something like `--watch-later-key=<key>` and use it instead of a path to identify a file.

### Alternative behavior of the wanted feature
Haven't come up with one.

### Log file
[mpv-fr.log](https://github.com/mpv-player/mpv/files/8791172/mpv-fr.log)

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/issues/9346#issuecomment-953400563

**Comment by snylonue** [comment]
> [#9346 (comment)](https://github.com/mpv-player/mpv/issues/9346#issuecomment-953400563)

Thanks. It seems satisfying my need in most cases.
