### ISSUE TITLE
vaapi-wayland commit adds tranparent border to gpu VO

### ISSUE THREAD

**Issue by kattjevfel** [mpv-player/mpv#10240]
### Important Information

Provide following Information:
- mpv version: defb02daa4
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: https://github.com/kattjevfel/pkgbuilds/blob/master/mpv-katt-git/PKGBUILD
- If known which version of mpv introduced the problem: defb02daa4
- Window Manager and version: KDE Plasma (Wayland) 5.24.90
- GPU driver and version: mesa 22.1.0
- Possible screenshot or video of visual glitches:

9022b1b51d:
![2022-05-28_00-04-04](https://user-images.githubusercontent.com/6226312/170794770-4e13c8ca-435f-4bac-9bf3-d67a55bbc333.png)

defb02daa4:
![2022-05-28_00-02-18](https://user-images.githubusercontent.com/6226312/170794613-41fb5cda-8c6c-4509-bbfe-611ba1b354c5.png)

### Reproduction steps

After upgrading to defb02daa4, I now get a transparent border around the video, as seen above. This is reproducible with --no-config.

### Expected behavior

No added border

### Actual behavior

A transparent border shows up both when windowed and in fullscreen.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/8789948/output.txt)

### Sample files

This happens on all videos I've tried thus far.

**Comment by Quackdoc** [comment]
happens with border=off too, adds a transparent border around the window so you can see desktop background

**Comment by Dudemanguy** [comment]
Apparently the mere act of creating subsurface (which is unconditionally done in wayland common) causes this on KDE for some unknown reason (???). It doesn't really make sense because nothing is done with the subsurface. It just happens to exist. This initial position when creating one is 0, 0 (top left corner) so it shouldn't be visible at all either. Kind of seems like a Plasma bug to me unless I'm missing something in the spec here.

>when I focus MPV via cursor, then click off, it resizes, or when I scroll on the task bar to cycle it resizes the window on both focus gained and focus lost

I cannot reproduce this.

**Comment by Quackdoc** [comment]
> I cannot reproduce this.

probably just my setup compounding the issue then, I just did a fresh arch install and KDE has been particularly buggy, but I did recompile and try latest and reverted again and it's certainly related

**Comment by Dudemanguy** [comment]
That commit has nothing to with focusing or resizing on vo GPU so that doesn't really make sense. Then again OP's bug doesn't really make sense either.

**Comment by kattjevfel** [comment]
> Seems like a Plasma bug to me (doesn't happen is sway or weston) unless I'm missing something in the spec here.

I honestly wouldn't know where to report this in their jungle of components. But if it really is an upstream bug I guess this can be closed, but I leave that to someone better knowledgeable than myself.

**Comment by CounterPillow** [comment]
The right component for this on KDE's side would likely be kwin.

**Comment by kattjevfel** [comment]
I made a bug report on KDE's kwin tracker: https://bugs.kde.org/show_bug.cgi?id=454535.
