### ISSUE TITLE
gpu-next "Failed creating framebuffer" with linux kernel 5.18.0-4-MANJARO-ARM and x265 files

### ISSUE THREAD

**Issue by brett-mahar** [mpv-player/mpv#10251]
### Important Information

- mpv version: self-built on May 30th master branch (libplacebo-git installed first)
- Linux Distribution and Version: Manjaro 5.18.0-4-MANJARO-ARM (aarch64)
- Source of the mpv binary: github source tree
- If known which version of mpv introduced the problem
- Window Manager and version: sway v1.7 /wayland 
- GPU driver and version: mesa-git 22.2.0_devel.154536.f2e36463218-1
- Possible screenshot or video of visual glitches: video output is a purple screen

### Reproduction steps

mpv --vo=gpu-next --no-config any_x265_vid.mkv

>> outputs a solid purple screen (plays as normal with --vo=gpu, or by reverting to kernel linux-5.17.9-2-aarch64 or earlier)

Computer is RockPi4B+ (Rockchip 3399)

### Expected behavior
normal video
### Actual behavior
purple screen
### Log file

Attached
[output.txt](https://github.com/mpv-player/mpv/files/8801133/output.txt)

The issue will be closed for ignoring the issue template.

**Comment by Dudemanguy** [comment]
Does this issue still exist for you on an up-to-date kernel?

**Comment by Dudemanguy** [comment]
No followup so closing.
