### ISSUE TITLE
How do I enable proper OSC?

### ISSUE THREAD

**Issue by Layerex** [mpv-player/mpv#10259]
Suddenly (after updating), my OSC became this:
![screen](https://user-images.githubusercontent.com/59440032/171698118-dd0e8026-58bb-479c-842d-6367ebd1e292.png)
How do I revert it to be like OSC here:
![mpv-screenshot-34cd36ae](https://user-images.githubusercontent.com/59440032/171697941-250d06d0-e097-4dc6-aa4b-a2a80c8b1b62.jpg)

**Comment by avih** [comment]
It changed over the years.

mpv is currently version 0.34.1, and the last version with the old default OSC layout was 0.21 some years ago.

https://mpv.io/manual/master/#on-screen-controller-layout

Use `--script-opts-add=osc-layout=box` at the command line ot at your `mpv.conf`.

**Comment by avih** [comment]
Actually, it's the same OSC in both your screenshots, except yours is with missing font or some such.

I don't recall exactly how to handle it. Reopening for now.

**Comment by Layerex** [comment]
`fonts.conf` was broken
