### ISSUE TITLE
Vulkan contexts don't support vaapi on RX 580

### ISSUE THREAD

**Issue by Quackdoc** [mpv-player/mpv#10253]
### Important Information

Provide following Information:
- mpv version : mpv 0.34.0-308-gf235bfbf36 
- Linux Distribution and Version : Arch linux
- Source of the mpv binary :  built from AUR
- If known which version of mpv introduced the problem : N/A
- Window Manager and version : Plasma wayland - Kwin ver 5.24.5-2
- GPU driver and version : rx580 both AMDVLK and RADV (mesa-git)
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Build and install libplacebo-git

Build and install mpv

Run MPV  with `--no-config --hwdec=vaapi --gpu-context=waylandvk -vo=gpu -gpu-api=vulkan -v` and there is no video acceleration 
 
Run MPV with `--no-config --hwdec=vaapi --gpu-context=wayland -vo=gpu -gpu-api=opengl -v` and video acceleration works

### Expected behavior

Expected video acceleration to work 

### Actual behavior

Fails with this error 
```
[vo/gpu/vaapi-egl] VAAPI libplacebo interop requires support for PL_HANDLE_DMA_BUF import.

[vo/gpu/vaapi-egl] VAAPI hwdec only works with OpenGL or Vulkan backends.
```

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/8804517/log.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by haasn** [comment]
Missing support for DRM modifiers. Make sure you're on the latest version of mesa, and if not, open an upstream bug.

**Comment by Quackdoc** [comment]
I presume it is this one? `VK_EXT_image_drm_format_modifier`? will make an issue upstream thanks
