### ISSUE TITLE
Selectively merge files in playlist?

### ISSUE THREAD

**Issue by ApolloBian** [mpv-player/mpv#10257]
I use mpv in the following scenario. I have my video files stored in a  object storage system and access them through http. However, the object storage system forces object size to be less than 4GB. This means some of my videos have to be split into several files, for example:
```text
original videos         |    object storage
------------------------------------------------------------------------------
video1.mp4  (3.2G)      |    [video1.mp4]
video2.mp4  (9.7G)      |    [video2-1.mp4, video2-2.mp4, video2-3.mp4]
```
However, the --merge-files option states that  all files passed to mpv are concatenated. There doesn't seem to be a way to selectively merge files in a playlist.
Is it possible to achieve this with some special playlist format? I did some search through old issues but didn't seem to find any discussion about merging files in playlist. 
### Expected behavior of the wanted feature
supports playlist semantics that allows to concatenate some files as one. Maybe a json file will be a good option, e.g:
```json
[
    "video1.mp4",
    {"orig_files":  ["video2-1.mp4", "video2-2.mp4", "video2-3.mp4"],
     "merged_name": "video2.mp4"
     }
]
```

**Comment by occivink** [comment]
look into the 'edit decision list' format supported by mpv https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst

**Comment by ApolloBian** [comment]
> look into the 'edit decision list' format supported by mpv https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst

This works! Thanks!
