### ISSUE TITLE
Batch create screenshots from terminal?

### ISSUE THREAD

**Issue by 3k2** [mpv-player/mpv#10261]
Hey,

I have been trying to batch create screenshot for files from terminal but I can't seem to get it work. 

`mpv --no-audio --start=00:01:30 --frames=1 /path/to/video/file --o=/path/to/screenshot.png`

this does work for a single file but I am trying to create for 10-50 files screenshots with different names so I tried.

`mpv --no-audio --frames=1 *.mp4 --screenshot-template=%tx --o=/home/kisu/pictures`

[screenshot section in the wiki](https://mpv.io/manual/stable/#screenshot)

any advice how to do this with mpv?

**Comment by hooke007** [comment]
It's not screenshot at all. It was only transcoding one frame to a picture. screenshot ought to be a playing-mode option (could not work for encoding mode)

**Comment by Dudemanguy** [comment]
You can use `--vo=image`. It takes screenshots of every frame.

**Comment by Hrxn** [comment]
> You can use `--vo=image`. It takes screenshots of every frame.

This is what I've used in the past, but isn't this a VO that simply decodes the stream and then directly writes to image files? So, isn't "screenshot" a bit of a misnomer here?

**Comment by Dudemanguy** [comment]
Yeah true. Depends on what exactly OP wants to do I suppose.

**Comment by 3k2** [comment]
Sorry I should have explained in more detail but the idea is that I have like 50 videos I need to take full size screenshot of the video. I was wondering is there a solution like terminal command to take screenshot of each video. Rather than opening the files one by one and using screenshot hotkey?

**Comment by Dudemanguy** [comment]
If you just want to dump the frames into image files, then `vo=image` can accomplish that for you easily without much work. If you actually need to take a screenshot (not sure what "full size" here means exactly) via the `screenshot` command (or `screenshot-to-file`) and want to do it semi-automatically, your best bet would probably be to make a script that takes screenshots for you at the intervals you need.

**Comment by thebombzen** [comment]
You can also consider just using FFmpeg for that.
```
ffmpeg -ss 12:35 -i input.mkv -map v -frames:v 1 shot.png
```
this extracts the frame from 12:35 in, and saves it to `shot.png`. You can script this with something like:
```
for video in *.mkv; do ffmpeg -ss 12:35 -i "$video" -map v -frames:v 1 shot-"$video".png; done
```

**Comment by thebombzen** [comment]
Did that solve the problem?
