### ISSUE TITLE
wl_surface@6: error 2: Buffer size (629x460) is not divisible by scale (2)

### ISSUE THREAD

**Issue by primalmotion** [mpv-player/mpv#10263]
## info 
- version 
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0

- Linux Distribution and Version
Arch

- Source of the mpv binary
Arch repo

- If known which version of mpv introduced the problem
Sway/wlroots > May 30 revisions

## description 

mpv (and imv) broke with latest wlroots/sway:

```
mpv Downloads/recording-2022-06-04_10:06:19.mp4 
 (+) Video --vid=1 (*) (h264 1258x920 57.407fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[ffmpeg] AVHWDeviceContext: Failed to query surface attributes: 20 (the requested function is not implemented).
[vo/gpu/vaapi-egl] failed to retrieve libavutil frame constraints
Cannot load libcuda.so.1
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [gpu] 1258x920 vaapi[nv12]
wl_surface@6: error 2: Buffer size (629x460) is not divisible by scale (2)
[vo/gpu/wayland] Error occurred on the display fd, closing

Exiting... (Quit)
```

According to @emersion, this is a bug on mpv side (see https://github.com/swaywm/sway/issues/7050)

**Comment by Dudemanguy** [comment]
I made a dummy video with a 629x460 and it worked for me on a newly built sway/wlroots. I'm using mpv from master though not 0.34.1. Could you try the latest master and see if you still get this?

**Comment by primalmotion** [comment]
ok I will give it another go later today

**Comment by Dudemanguy** [comment]
Oh and yeah I normally run scale 2. I assume that's what you do as well.

**Comment by primalmotion** [comment]
I'm not sure. if you mean sway scaling, I'm using 1.3 here

**Comment by Dudemanguy** [comment]
>I'm using 1.3 here

Cool, just checked using that and same result (still worked) which is expected because sway will tell mpv to scale up to the nearest integer (2 in this case).

**Comment by primalmotion** [comment]
I just tried with latest mpv master, but the problem still happens

```
❱ mpv --version                                  
mpv 0.34.0-312-g969bdf5f41 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Mon Jun 06 06:03:22 2022
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0

❱ mpv Downloads/recording-2022-06-04_10:06:19.mp4
 (+) Video --vid=1 (*) (h264 1258x920 57.407fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
Using hardware decoding (vaapi).
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1258x920 vaapi[nv12]
wl_surface@7: error 2: Buffer size (629x460) is not divisible by scale (2)
[vo/gpu/wayland] Error occurred on the display fd, closing

Exiting... (Quit)
```

**Comment by Dudemanguy** [comment]
Could you share whatever sample file you're using?

**Comment by primalmotion** [comment]
https://user-images.githubusercontent.com/208711/172221281-0b8f15dd-5590-41d4-9f7a-3c5ffe58648f.mp4

(careful, it's the most interesting recording ever :) )

**Comment by Dudemanguy** [comment]
OK, I was able to reproduce it now. It only happens with opengl for some reason.

**Comment by Dudemanguy** [comment]
@primalmotion: Can you confirm if the following diff fixes it?

```
diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
index 1c8d2097c8..ac975982a7 100644
--- a/video/out/wayland_common.c
+++ b/video/out/wayland_common.c
@@ -1924,7 +1924,6 @@ int vo_wayland_reconfig(struct vo *vo)
         wl->current_output = find_output(wl);
         if (!wl->current_output)
             return false;
-        set_surface_scaling(wl);
         wl_surface_commit(wl->surface);
         configure = true;
     }
@@ -1946,7 +1945,6 @@ int vo_wayland_reconfig(struct vo *vo)
         do_minimize(wl);
 
     if (configure) {
-        wl->window_size = wl->vdparams;
         wl->geometry = wl->window_size;
         wl_display_roundtrip(wl->display);
         wl->pending_vo_events |= VO_EVENT_DPI;
```

**Comment by primalmotion** [comment]
I confirm it works with that patch

**Comment by Dudemanguy** [comment]
Great, I'm not really sure why the wayland event orders are different in opengl only but less code is good.

**Comment by Dudemanguy** [comment]
This is sway/wlroots specific. Now sure in theory, the width/height calculations from the VO could be adjusted to make sure they are perfect integer multiples, but that's not really worth it when the fractional scale protocol sidesteps all this nonsense. Unfortunately support for that is not in a sway release yet, but hopefully soon. It works fine in sway/wlroots master.

**Comment by emersion** [comment]
> This is sway/wlroots specific

Not really, the spec says that a protocol error is sent on invalid scale like this one.

**Comment by Dudemanguy** [comment]
As far as I know, wlroots is the only one who actually enforces that. Anyways, considering that 1215x2160 is the correct size ( (2160 / 1280) * 720), it's not a problem with the fractional scale protocol which doesn't have this limitation, and the old integer scaling method is basically legacy in everything but name, it's not worth worrying about further imo.

**Comment by emersion** [comment]
It isn't legacy no: the fractional scale protocol might get supersededadn replace with something else (we've been talking about limitations of this approach)  whereas integer scale won't go away since its in core Wayland.
