### ISSUE TITLE
[meta] Can you open the Github 'discussions' on this repo?

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#10264]
an example repo with the discussions open: https://github.com/yt-dlp/yt-dlp/discussions

While the 'question' tag/category is enabled, the issues is not an optimal fit for subjective topics, I feel. May also reduce the maintainer burden by lowering the amount of created issues.

**Comment by CounterPillow** [comment]
I agree this would be a good idea, I don't like the question template's existence as some people use it to report actual issues and then not include log files.

We'd need people we can trust who will moderate the discussions pages though, things will probably get out of hand quickly when someone asks what "the best user shader" is or whatever.

**Comment by thebombzen** [comment]
Another issue is people whose questions are answered don't say so, and then the issues stay open, cluttering open issues.

**Comment by hooke007** [comment]
> We'd need people we can trust who will moderate the discussions pages though, things will probably get out of hand quickly when someone asks what "the best user shader" is or whatever.

That's quite important. And make a rule to prevent large amounts of simple questions such as "how to set volume/speed/sat". A bad example is reddit/mpv, which is full of those kinda terrible threads.

**Comment by stax76** [comment]
It's enabled in the staxrip and mpv.net repo, has a like issues a Pin feature, what if necessary can be used to pin rules or guidelines.

**Comment by garoto** [comment]
Implementing shithub discussions would only increase the janitorial workload needed from the current members, with zero detectable benefits whatsoever. Gimmicky feature from a doomed platform.

**Comment by 07416** [comment]
> > We'd need people we can trust who will moderate the discussions pages though, things will probably get out of hand quickly when someone asks what "the best user shader" is or whatever.
> 
> That's quite important. And make a rule to prevent large amounts of simple questions such as "how to set volume/speed/sat". A bad example is reddit/mpv, which is full of those kinda terrible threads.

A comprehensive, pinned easy-to-read FAQ alone should prevent most of the such questions from being asked.

I'd also prohibit sharing entire config files and instructing people to use one as it is.

**Comment by kasper93** [comment]
https://github.com/mpv-player/mpv/discussions have fun!
