### ISSUE TITLE
Normalize filename before storing

### ISSUE THREAD

**Issue by tewe** [mpv-player/mpv#1027]
Playback position is saved in `~/.mpv/watch_later/*` where \* is the MD5 of the filename _as it was passed to mpv_. This is a problem if you launch mpv in different ways, that may use different representations of the same unicode filename.

For instance, dragging a japanese file from the Finder into a Terminal window on the Mac uses a different normal form than copypasting the filename, so playback will not resume.

The solution is converting all filenames to the same normal form (no matter which) before calculating the hash.

**Comment by qmega** [comment]
Just had an idea: Why not do the conversion before calling mpv, so mpv doesn't have to care? Try adding something like this to your path before mpv:
```python
#!/usr/bin/env python

MPV = '/path/to/real/mpv'

from os import execv
from sys import argv
from unicodedata import normalize

try:
    unicode
except NameError: # Python 3
    unicode = lambda x, y: x # will already be unicode

execv(MPV, [MPV] + [normalize('NFD', unicode(arg, 'utf-8')) for arg in argv[1:]])
```
That's assuming Finder uses NFD and Terminal uses NFC. If it's the other way around, change the first argument to normalize().
