### ISSUE TITLE
Subtitles are still not visible over black bars with vo=gpu-next & video-sync=display-resample

### ISSUE THREAD

**Issue by mnisius** [mpv-player/mpv#10272]
Hi sorry maybe I understood something wrong because I thought this was fixed by this: https://github.com/mpv-player/mpv/pull/10266 and my last report was closed as a duplicate however subtitles are still not visible if I watch a video with black bars 😢

### Important Information
Provide following Information:

- mpv version: mpv-x86_64-20220607-git-cd3b4ed
- Platform and Version: Windows 10
- Source of the mpv binary: shinchiro

### Screenshot
![grafik](https://user-images.githubusercontent.com/56688244/172464918-74087e67-5299-4314-aaf3-ff15a34e61e9.png)

### Reproduction steps
Play a Video with back bars on full screen or with maximized window
and add this 2 options to your config :
vo=gpu-next & video-sync=display-resample

### Expected behavior
Subtiles are visible

### Actual behavior
Subtiles are hidden behind the black bars

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/8855985/output.txt)

**Comment by haasn** [comment]
Oh, that commit just fixes it for screenshots, not during playback with `display-resample`.

**Comment by ekce** [comment]
With regard to the os:win label, this issue occurs in linux as well.

**Comment by PhyX-Meow** [comment]
Similar issue here, `video-sync=display-resample` causes subtitles in a hdr video look dark on my pc. Seems it break some functionality related to subtitle rendering of gpu-next vo.

**Comment by NaiveInvestigator** [comment]
This also starts occurring even we if only add `vo=gpu-next` in `mpv.conf`.

**Comment by escape0707** [comment]
I tested some srt subtitles (or ass subtitles with --sub-ass-override=on) and it works. But I still can't see ass subtitles when it's out of the video part. Is it because the way ass get rendered is different from srt ones, so it haven't and won't work since before and in the future?
