### ISSUE TITLE
Wayland wm_class reports none instead of default mpv

### ISSUE THREAD

**Issue by justinesmithies** [mpv-player/mpv#10280]
### Important Information

Provide following Information:
- mpv version - mpv 0.34.0-323-g661b5542de
- Linux Distribution and Version - Arch Linux 
- Source of the mpv binary - AUR ( mpv-git)
- If known which version of mpv introduced the problem
- Window Manager and version - Qtile git master - Wayland
- GPU driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
When running mpv it used to set the wayland app_id as default 'mpv' and since the last update or so it is set to None

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
Wayland app_id set to default of 'mpv'

### Actual behavior
Wayland app_id set to 'None'

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Dudemanguy** [comment]
It definitely *should* work and is set to "mpv" by default. For example `for_window [app_id="mpv"] floating enable` triggers in my sway config.

**Comment by justinesmithies** [comment]
Nope i definately get an app_id of None and it did work until recentlyas i use the app_id to float the mpv window at a set size.

output from 'qtile cmd-obj -o cmd -f windows'

`{'float_info': {'height': 1608, 'width': 3840, 'x': 976, 'y': 557},
  'floating': False,
  'fullscreen': False,
  'group': '\uf120 ₂',
  'height': 501,
  'id': 7,
  'maximized': False,
  'minimized': False,
  'name': 'Róisín O - Heart + Bones (Official Video) - mpv',
  'width': 922,
  'wm_class': None,
  'x': 976,
  'y': 557}]`

Yet all other windows have their app_id set correctly like kitty for example.

**Comment by Dudemanguy** [comment]
Can you post a `WAYLAND_DEBUG` log?

**Comment by justinesmithies** [comment]
Even if i try setting it using this option it still outputs None 
mpv --wayland-app-id='mpv' 'https://www.youtube.com/watch?v=Bi9rNPcOjDY'

**Comment by justinesmithies** [comment]
> Can you post a `WAYLAND_DEBUG` log?

I'm looking into it as I'm not 100% sure how to get a 'WAYLAND_DEBUG' log ??

**Comment by Dudemanguy** [comment]
Oh sorry, it's just `WAYLAND_DEBUG=1 mpv file.mkv 2> output.log`

**Comment by justinesmithies** [comment]
[output.log](https://github.com/mpv-player/mpv/files/8881978/output.log)

Here is the wayland debug log

**Comment by Dudemanguy** [comment]
>[1900806.463]  -> xdg_toplevel@19.set_app_id("mpv")

Looks like a compositor bug to me. That request is sent by us from our end. I don't know why or how an update would affect this. Nothing on that end should have changed recently.

**Comment by justinesmithies** [comment]
It can't be as i have just installed the normal mpv package from the arch repo and it works as expected the app_id is set to mpv. Yet if i install the Arch AUR mpv-git which is your git master it no longer works I get None

**Comment by Dudemanguy** [comment]
You can see from the log that the app id is clearly set to mpv. Now whether or not the compositor actually works is a separate matter. There's been a ton of changes since 0.34 so it's hard to say what exactly is different, but the bug should be on the compositor side. The `set_app_id` request can be sent at any time as long as the `xdg_toplevel` is valid. In fact, you should even be able to update it at runtime (if you open the console with \` and type `set wayland-app-id foo` it should update it (note that this only operates on changes so typing `mpv` again wouldn't work because internally it is already set to `mpv`). I'd assume there's some race condition or so on the compositor side.

**Comment by qmega** [comment]
@justinesmithies Whether it's an mpv issue or not, if there's an mpv version it works on your system and one that doesn't, bisecting could help narrow down the cause.

Also, Arch's community/mpv builds with waf while aur/mpv-git uses meson, so there's a possibility for difference there, though unlikely.

If you can build 0.34.1 yourself and that still behaves the way you want, a bisect should make it a lot clearer what's going on.

**Comment by Dudemanguy** [comment]
>bisecting could help narrow down the cause

A wild guess from me would be changing the initial `wl_surface_commit` so it acts before the app_id is set (note: this shouldn't matter but there's a chance).

**Comment by justinesmithies** [comment]
Right I've found the last AUR package where mpv still works correctly any mpv-git package after this one fails.

`mpv-git-0.34.0_315_ga4f0db051a-1-x86_64.pkg.tar.zst`

Hopefully this should help you track down the issue ???

**Comment by Dudemanguy** [comment]
Yeah so that makes it basically exactly what I guessed. Does this stupid patch work?

```
diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
index 865a073716..698cec1ec8 100644
--- a/video/out/wayland_common.c
+++ b/video/out/wayland_common.c
@@ -1905,13 +1905,13 @@ int vo_wayland_init(struct vo *vo)
     wl->opts = mp_get_config_group(wl, wl->vo->global, &wayland_conf);
     wl->display_fd = wl_display_get_fd(wl->display);
 
+    update_app_id(wl);
+    mp_make_wakeup_pipe(wl->wakeup_pipe);
+
     wl->frame_callback = wl_surface_frame(wl->surface);
     wl_callback_add_listener(wl->frame_callback, &frame_listener, wl);
     wl_surface_commit(wl->surface);
 
-    update_app_id(wl);
-    mp_make_wakeup_pipe(wl->wakeup_pipe);
-
     return true;
 }
 ```

**Comment by justinesmithies** [comment]
Yes that patch does fix my issue and thank you ;)

**Comment by Dudemanguy** [comment]
Just FYI, I think the compositor you are using is unable to update the app id during runtime which I would consider a bug. It seems like it can only read it before the `wl_surface` is committed so this is a workaround but one that should be harmless (it incidentally worked like this before anyway so whatever I guess).
