### ISSUE TITLE
How to make my own command line option?

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#10283]
How can I make my own command line options?

For example lets say I want mpv to only open images, I type in `mpv.com --images media/` and I will handle the option in a lua script.

**Comment by Dudemanguy** [comment]
Command line options require code changes in mpv itself to implement. You couldn't just make your own like that. Instead what you can do is simply use the `--script` or `--scripts` option to pass the lua script you want. Then the lua script can only keep images in the playlist or whatever you wish to do.

**Comment by cerealXDD** [comment]
> Command line options require code changes in mpv itself to implement. You couldn't just make your own like that. Instead what you can do is simply use the `--script` or `--scripts` option to pass the lua script you want. Then the lua script can only keep images in the playlist or whatever you wish to do.

Is there a shortform for scripts/scripts? Like -s? Also when I pass the script do I need the absolute path of the script or will mpv recognize the script from the scripts folder?

**Comment by Dudemanguy** [comment]
No short switch (way too many options start with an `s`). There's several shorthands you can use for paths however. Check the [manual](https://github.com/mpv-player/mpv/blob/master/DOCS/man/mpv.rst#paths) on it.

**Comment by garoto** [comment]
> (Windows)

Investigate `doskey macros`. Here's a few links from a search engine to give you an idea:

https://gist.github.com/postcog/5c8c13f7f66330b493b8
https://kwilson.io/blog/getting-your-macro-on-with-doskey/
https://dev.to/dendihandian/commands-alias-using-doskey-29f9
