### ISSUE TITLE
Tag audio file while it's playing

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10289]
I tried to tag a .mp3 and .opus file while it was playing with the following editor:

https://github.com/Martchus/tageditor

It unexpectedly worked, but why?

I thought mpv opens audio files while playing, and while a file is open, another app cannot write to it.

**Comment by bitraid** [comment]
mpv opens files with share write (that's how, for example, you can start playing a file while it's being downloaded by another program):
https://github.com/mpv-player/mpv/blob/602995fd40f03440f5fa64113b6188cb46ffcc9c/osdep/io.c#L381-L384
https://github.com/mpv-player/mpv/blob/602995fd40f03440f5fa64113b6188cb46ffcc9c/osdep/io.c#L461

**Comment by stax76** [comment]
I see, thanks.
