### ISSUE TITLE
What is the best luma and chroma upscaling method for MPV in 2022?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#10281]
Hi, I have a question, what is the best luma and chroma upscaling method for MPV player in 2022?
As I remember, the best Chroma upscaling method was KrigBilateral.glsl shader? The best Luma upscaling method was FSRCNNX shader, am I correct?
What is the best upscaling suggestion in 2022?

**Comment by CounterPillow** [comment]
"best" is subjective

**Comment by laichiaheng** [comment]
@CounterPillow But there must be some way to see them, right?

**Comment by igv** [comment]
Nothing better has been invented yet. Maybe in the future when everyone will be running tensor cores. 

> But there must be some way to see them, right?

Yes, use [PieAPP](https://github.com/prashnani/PerceptualImageError#pieappv01-win64-command-line-executable), objectively the best metric.
Btw, see the latest comments for [adaptive-sharpen](https://gist.github.com/igv/8a77e4eb8276753b54bb94c1c50c317e), where PieAPP was used for evaluation.

**Comment by hooke007** [comment]
The so-called “best” cannot match everyone’s preference.

**Comment by yeezylife** [comment]
Just use KrigBilateral and trust in igv!!!

**Comment by Hrxn** [comment]
Okay, for those who don't want to bother reading themselves, according to the comments linked above, the best™ method is:

`FSRCNNX+dscale-lanczos+AS-0_1-luma-2022-05`

Which I assume from the context is:
- FSRCNNX (variant/version not further specified here)
- `--dscale=lanczos`
- AdaptiveSharpen, luma only version, update from May 2002 
    (I assume that's the one from the gist, albeit this being the RGB one?)

**Comment by igv** [comment]
AS-0_1-luma-2022-05 is [this](https://gist.github.com/HolyWu/39e610f2eccf1ed72c0a9c507bc5eaa6) with changes from May 7.
