### ISSUE TITLE
Is --demux-lavf-o=decryption_key=<key> still working?

### ISSUE THREAD

**Issue by C0ldF** [mpv-player/mpv#10298]
Hello, is --demux-lavf-o=decryption_key=<key> still working?

ffplay can run live mpd stream with the key using -cenc_decryption_key

i want know if mpv can run too.

**Comment by jeeb** [comment]
`ffmpeg -h demuxer=mp4` shows the decryption key option, which is why it works (with MP4).

the DASH demuxer `ffmpeg -h demuxer=dash` has decided to call the option something else :) .

In other words, I expect either to work within their specific contexts.

**Comment by markg85** [comment]
(couple years later) I had this exact same question and was just about to open a bug for it.
Turn out this is the command you're looking for:
`mpv --stream-lavf-o=cenc_decryption_key=<key> <video>`
