### ISSUE TITLE
mpv drops frames after video playback is resumed

### ISSUE THREAD

**Issue by dmi-dmi-dmi** [mpv-player/mpv#10295]
### Important Information

Provide following Information:
- mpv version: 0.34.1-dirty
- Linux Distribution and Version: ArchLinux
- Source of the mpv binary: [distribution package](https://archlinux.org/packages/community/x86_64/mpv/)
- If known which version of mpv introduced the problem: not sure
- Window Manager and version: xfwm4 4.16.1-3
- GPU driver and version: amdgpu

### Reproduction steps

When I play a video (no matter which one as this happens even with light h264 720p videos), pause it and unpause I see that mpv drops frames causing A-V desync in the first 20-30 seconds after resume. 

For a year mpv worked just fine for me and this started happening out of the blue a few days ago. No packages were update for more than 10 days so I am really puzzled with what is happening.

Issue can be reproduced with `--no-config` flag.  

### Expected behavior

Video plays without dropping frames after unpause

### Actual behavior

Frame dropes when video is unpaused

### Log file

[Log file](https://0x0.st/ouQJ.txt)

UPD: For some reason `[statusline]` messages were not included into the log file so here is the relevant excerpt from the console output - [link](https://0x0.st/ouQy.txt) where you can see `Dropped` counter increases after unpause

**Comment by dmi-dmi-dmi** [comment]
So after reviewing log I posted here I noticed that each time I unpause it says `[v][vo/gpu/x11] Disabling screensaver.`

Running `mpv` with `--stop-screensaver=no` seems to resolve the problem. I tried it with 10+ videos and it works without dropping frames.

I suppose the culprit here is not mpv but I want to be sure. Is there any way I can manually confirm that disabling screensaver actually takes a lot of time/cpu?

**Comment by dmi-dmi-dmi** [comment]
> No packages were update for more than 10 days so I am really puzzled with what is happening.

I am using mpv on a shared laptop and turns out there was a package ugprade (performed by someone else who has never done this in the past). I was just unaware of it.

I reviewed pacman log and spotted that there was `libpulse` upgrade from 15.0 to 16.0. a week ago. This upgrade is the reason for stuttering in mpv.

Running `mpv --ao=alsa ..` resolves the problem completely.

**Comment by maiphi** [comment]
Why has this been closed? Switching to ALSA is not a fix, just a workaround. So unless it is clear that the bug is in libpulse and not in mpv, the issue should be reopened.

mpv version: 0.34.1
libpulse version: 16.1

**Comment by ncfavier** [comment]
FWIW, see [`--pulse-latency-hacks`](https://mpv.io/manual/master/#audio-output-drivers-pulse-latency-hacks). This fixed the issue for me.

**Comment by maiphi** [comment]
> FWIW, see [`--pulse-latency-hacks`](https://mpv.io/manual/master/#audio-output-drivers-pulse-latency-hacks). This fixed the issue for me.

Thanks! This indeed seems to solve the problem without bypassing pulseaudio (at least after a couple of hours watching videos I'm pretty confident that it does).

**Comment by sajadspeed** [comment]
> FWIW, see [`--pulse-latency-hacks`](https://mpv.io/manual/master/#audio-output-drivers-pulse-latency-hacks). This fixed the issue for me.

I have been looking for a solution for almost several months, thank you very much, thank you.
