### ISSUE TITLE
Config Profile Issue

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#10296]
### Important Information

Provide following Information:
- mpv version: latest
- macOS Version: latest
- Source of the mpv binary or bundle: mpv.io
- If known which version of mpv introduced the problem: latest
- Possible screenshot or video of visual glitches: unneeded

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
Profile only works with 720p sources that have frame rate higher than one. And, KrigBilateral isn't applied.

### Actual behavior
Profile works whenever upscale is done.
Profile:
[SD Video Upscale]
profile-desc=cond:(get('height', math.huge) < 720) and (get('estimated-frame-count', math.huge) > 1)
profile-restore=copy
glsl-shaders-clr
glsl-shaders-append="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl" 

### Log file

Make a log file made with -v -v or --log-file=output.txt. If you use the Bundle
from a version later than 0.32 a default log is created for your last run at
~/Library/Logs/mpv.log. You can jump to that file via the Help > Show log File…
menu. Paste the log to https://0x0.st/ or attach it to the github issue, and
replace this text with a link to it.

In the case of a crash please provide the macOS Crash Report (Backtrace).

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by hooke007** [comment]
If you were using the outdated `auto-profiles.lua`, you'd better delete it and use mpv's native function instead.

**Comment by george-emerald** [comment]
@guidocella, it's the same thing.

@hooke007, I'm not using that. I'm using the native function.

**Comment by hooke007** [comment]
It’s not the same thing.
And where is your log?

**Comment by george-emerald** [comment]
They both set the condition.

I don't know how to make one.

**Comment by george-emerald** [comment]
Yes, but I'm not using profile-desc, I'm using profile-desc=cond:

**Comment by hooke007** [comment]
Don’t waste our time here. There’s nothing called `profile-desc=cond:` in mpv.
Post your log via option. `log-file=~~desktop/mpv.log`

**Comment by george-emerald** [comment]
But, I've seen it used quite a bit. I can change it if you think therein lies the problem.

Where do I enter that code?

**Comment by hooke007** [comment]
mpv.conf

**Comment by george-emerald** [comment]
I put it there, yet I don't see any log file on my desktop.

**Comment by george-emerald** [comment]
Fixed. Some other line in my config was messing with it.
