### ISSUE TITLE
6 channel audio with jack audio devices cause a leak to other unintended audio devices to output the remaining channels.

### ISSUE THREAD

**Issue by mez0ru** [mpv-player/mpv#10299]
### Important Information

Provide following Information:
- mpv version
0.34.1
- Linux Distribution and Version
Fedora 36
Linux fedora 5.17.13-300.fc36.x86_64 SMP PREEMPT Mon Jun 6 14:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Source of the mpv binary
RHEL DNF package manager
- If known which version of mpv introduced the problem
Not sure, I just discovered it this morning.
- Window Manager and version
KDE plasma 5.24.4
- GPU driver and version
Nvidia 470.129.06
- Possible screenshot or video of visual glitches
Audio issue, so it's not applicable.
Btw, I use PipeWire 0.3.52

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

Run mpv with -ao=jack option and play any video or audio that contains 6 channel surround sound audio.

### Expected behavior
The audio only outputs to my default audio device.

### Actual behavior
Audio leaks to other output devices, for example I have a monitor that have speakers, it receives audio through displayport, and a usb headphones, I'm using my headphones as the default device. So the audio should output to my headphones only, however doing the reproduction steps will unexpectedly output the remaining 5th and 6th channels to the monitor. In my headphones I can hear just the 1st and 2nd channels, the other 3rd and 4th channels are leaked to the next audio device by the order shown in my kde audio devices panel, since the monitor is listed the third in the row, I think it that's the reason it outputs the 5th and 6th channels to it. 

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.
[output.txt](https://github.com/mpv-player/mpv/files/8928172/output.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

I used a sample from [https://www.jensign.com/bdp95/7dot1voiced/index.html](https://www.jensign.com/bdp95/7dot1voiced/index.html) but any sample that contain 6 audio channels will do.

**Comment by Zipdox** [comment]
Just add `jack-port=system` to your config. And `audio-channels=stereo` if you want multichannel downmixed to stereo.

**Comment by Zipdox** [comment]
It's fixed? Please close the issue then.
