### ISSUE TITLE
There should be completely new default key bindings

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#103]
The current key bindings (see https://github.com/mpv-player/mpv/blob/master/etc/input.conf for current mappings) are a bit dated. Many useless things are mapped on prominent spots (think of all the brightness etc. controls on the keys 1-9), while more useful commands like chapter skipping have awkward bindings on most keyboard layouts. Some commands are pretty much deprecated (like the controls for TV?) and should be removed entirely.

We should think about a good set of default bindings with sensible mappings. They should work on most of the common keyboard layouts.

There was some discussion on IRC and in other tickets, but nothing conclusive. This issue is for suggesting and discussing new bindings.

**Comment by sheharyarn** [comment]
I use VLC a lot and I'm trying to keep it very similar to VLC's keybinds:

### [dotfiles](https://github.com/sheharyarn/dotfiles) / [MPV](https://github.com/sheharyarn/dotfiles/tree/master/OSX/MPV) / [input.conf](https://github.com/sheharyarn/dotfiles/blob/master/OSX/MPV/input.conf)

**Comment by wm4** [comment]
For anyone who may find here, this is continued in: https://github.com/mpv-player/mpv/issues/973
