### ISSUE TITLE
Using Intel's fixed hardware scalers with vo=gpu sw decode

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#10306]
Is it possible to have the software decoder output in a format that's compatible with `vf=scale_vaapi`? The output looks pretty good to me, and I'd like to save on resources by using this method for all video formats.

As an aside, is it possible to have this option dynamic? As in not having to call the vf with a fixed number every time?

**Comment by lavilao** [comment]
vo=gpu and vo=gpu-next combined with hwdec=vaapi are the things you are looking for... I think

**Comment by philipl** [comment]
I'd be surprised if `vf=scale_vaapi` did anything better than scaling in `vo=gpu[-next]`. If you're doing anything fancier than bilinear, it's being handled by shader code, just in the driver instead of in mpv. But if you want to do something like this you can use `vf=format=fmt=vaapi` to upload your sw decoded output.

**Comment by kkanungo17** [comment]
@lavilao I was talking about the cases where hwdec=vaapi doesn't support the codec of the file.

@philipl That vf fails with an error, am I using it wrong?

[mpv.log](https://github.com/mpv-player/mpv/files/8936156/mpv.log)

**Comment by lavilao** [comment]
@kkanungo17 if the file is not decoded through vaapi then I dont think is possible to use scale_vaapi.

**Comment by philipl** [comment]
Yeah. There's no concept of upload to vaapi, due to the nature of the API. Just don't worry about it and let `vo=gpu` do your scaling. It's not worth trying to micro-optimise this stuff.

**Comment by kkanungo17** [comment]
Huh. Sadge.
