### ISSUE TITLE
mp3 file hangs

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10307]
- mpv version
- Source of the mpv binary

I tried various mpv and libmpv builds from different sources, including zhongfly libmpv build from today, bug is present everywhere, in both mpv and mpv.net

- Windows Version

Windows 11 latest version

### Reproduction steps

There is this one MP3 file, when I start mpv or mpv.net with this file it plays OK, it hangs when another file was played before (tested with different files). It loads or starts as indicated in the title bar of the window, but it will only play when for instance the mouse is moved. I used mpv.exe instead of mpv.com, so pseudo-gui profile. My config and script folder is empty.

### Expected behavior

File plays

### Actual behavior

File hangs

### Log file

[mpv-log.txt](https://github.com/mpv-player/mpv/files/8936141/mpv-log.txt)

### Sample files

I hope it can be reproduced easily, the file:

[sample.zip](https://github.com/mpv-player/mpv/files/8936152/sample.zip)

**Comment by stax76** [comment]
I tried if I can reproduce it with wsl2, and while I can show cover art and even some video files, there are UI issues, so I tried without UI using `mpv --no-audio-display`, with that in wsl2 no problem, but on native Windows using `mpv --no-audio-display` it's still happening even without any window shown, it plays only when I pause and unpause.

I found another MP3 file where it also happens, and I believe I found what triggers it, happens whenever the sampling rate changes from 44.100 to 48.000.

[sample-44100.zip](https://github.com/mpv-player/mpv/files/8937207/sample-44100.zip)

**Comment by garoto** [comment]
https://github.com/mpv-player/mpv/issues/8904#issuecomment-860790548

**Comment by stax76** [comment]
Duplicate of #8904
