### ISSUE TITLE
json ipc documentation doesn't list properties, commands, events

### ISSUE THREAD

**Issue by crumblingstatue** [mpv-player/mpv#10308]
https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst contains references to things like `List of Input Commands`, `List of Events`, `Properties`,  but they all seem to be dead links.

Where can I find this information?

**Comment by stax76** [comment]
There are many things in the manual, but you can also query it, for instance in the console using the print-text input command:

print-text ${property-list}

Or use a script:

https://github.com/CogentRedTester/mpv-search-page

**Comment by CounterPillow** [comment]
The links aren't dead, you're just looking at the documentation source files instead of the built documentation: https://mpv.io/manual/master/#json-ipc

**Comment by crumblingstatue** [comment]
Thank you!
The confusion stems from the GitHub page being highly prioritized over the website when searching for "mpv json ipc"
