### ISSUE TITLE
Yellowish colors

### ISSUE THREAD

**Issue by rtentser** [mpv-player/mpv#10319]
### Important Information

Manjaro KDE

Provide following Information:
- mpv version

```
mpv 0.34.0-325-g602995fd40 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Mon Jun 13 12:26:01 2022
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0
```

- Linux Distribution and Version

Manjaro Linux 21.3.0

- Source of the mpv binary

mpv-git package

- If known which version of mpv introduced the problem
- Window Manager and version

kwin 5.24.5

- GPU driver and version

mesa 22.1.1 (RX 6600)

- Possible screenshot or video of visual glitches

ffplay:
![ffplay](https://user-images.githubusercontent.com/34958119/174818855-ccc3d4c6-e136-4ea3-9fd7-468e958c91bb.png)

mpv --no-config:
![mpv](https://user-images.githubusercontent.com/34958119/174818878-d77ad0ed-8703-4706-9d43-0b6cc37617de.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

I've just run a movie and decided to compare

### Expected behavior

Same colors as in ffplay as mpv based on ffmpeg?

### Actual behavior

Slighty more yellow

### Log file

Can add if needed

### Sample files

Can add if needed

**Comment by haasn** [comment]
I can reproduce this but it appears to be an ffmpeg bug. `ffplay` always seems to decode with BT.601 matrix, even if the source is tagged with BT.709. You can work around it with `ffplay -vf colormatrix=bt709:bt601`.

**Comment by rtentser** [comment]
Yes, it changes ffplay's colors, thanks!
