### ISSUE TITLE
mpv performance is bad with --gpu-context=x11vk or --gpu-api=vulkan

### ISSUE THREAD

**Issue by Gigas002** [mpv-player/mpv#10326]
### Important Information

mpv version:

```zsh
mpv 0.34.0-353-g230d490eca Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Wed Jun 22 12:49:46 2022
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0
```

linux destribution and version:

```zsh
Operating System: Manjaro Linux
Kernel: Linux 5.18.5-1-MANJARO
Architecture: x86-64
```

source of mpv binary: mpv-git from AUR: https://aur.archlinux.org/packages/mpv-git/

window manager: x11, KDE Plasma 5.25.0

GPU driver: proprietary nvidia driver 515.48.07

introduced in: https://github.com/mpv-player/mpv/commit/3d459832a88a9bd2835b339cf6ca98f84aad0115

### Reproduction steps

`mpv --no-config --gpu-context=x11vk 1.mp4`

or

`mpv --no-config --gpu-api=vulkan 1.mp4`

gives the same result

### Expected behavior

Video plays without issues

### Actual behavior

Very poor performance with a lot of dropped frames

### Log file

`--gpu-context=x11vk` log: https://0x0.st/ouFh.txt

`--gpu-api=vulkan` log: https://0x0.st/ouFF.txt

Additional info: continuation of discussion in #10320

After rebuilding several times I found out the commit, where this behavior was introduced (see above).

**Comment by Gigas002** [comment]
If it was meant to run as `mpv --no-config --x11-present=no --gpu-api=vulkan 1.mp4`, then the result is the same.

**Comment by Gigas002** [comment]
No, doesn't seem to fix anything...

Btw, how can I apply this patch? `git am mpv.patch` and `git apply mpv.patch` are both failing (I've ended up editing source file myself)

**Comment by Dudemanguy** [comment]
`git apply -3 mpv.patch` should work.

Hmm, I don't understand how the behavior could have possibly changed for you. Especially not in the `--no-config` case. With opengl, is your performance any worse with the above mentioned commit or do you only see a regression in vulkan?

**Comment by Gigas002** [comment]
It's only affecting the `mpv --no-config --gpu-api=vulkan` and `mpv --no-config --gpu-context=x11vk`. When running just `mpv --no-config` everything works perfectly well.

**Comment by Dudemanguy** [comment]
It really shouldn't have anything to do with that commit then. Just to make sure, could you try this (it just comments out all the new stuff)?

```
diff --git a/video/out/vulkan/context_xlib.c b/video/out/vulkan/context_xlib.c
index 3392145e1a..ce48a64116 100644
--- a/video/out/vulkan/context_xlib.c
+++ b/video/out/vulkan/context_xlib.c
@@ -32,7 +32,7 @@ static bool xlib_check_visible(struct ra_ctx *ctx)
     return vo_x11_check_visible(ctx->vo);
 }
 
-static void xlib_vk_swap_buffers(struct ra_ctx *ctx)
+/*static void xlib_vk_swap_buffers(struct ra_ctx *ctx)
 {
     vo_x11_present(ctx->vo);
     present_sync_swap(ctx->vo->x11->present);
@@ -42,7 +42,7 @@ static void xlib_vk_get_vsync(struct ra_ctx *ctx, struct vo_vsync_info *info)
 {
     struct vo_x11_state *x11 = ctx->vo->x11;
     present_sync_get_info(x11->present, info);
-}
+}*/
 
 static void xlib_uninit(struct ra_ctx *ctx)
 {
@@ -76,8 +76,8 @@ static bool xlib_init(struct ra_ctx *ctx)
 
     struct ra_vk_ctx_params params = {
         .check_visible = xlib_check_visible,
-        .swap_buffers = xlib_vk_swap_buffers,
-        .get_vsync = xlib_vk_get_vsync,
+        //.swap_buffers = xlib_vk_swap_buffers,
+        //.get_vsync = xlib_vk_get_vsync,
     };
 
     VkInstance inst = vk->vkinst->instance;
```

**Comment by Gigas002** [comment]
Yes, this patch fixes the problem

**Comment by Dudemanguy** [comment]
Quite unexpected, but thanks for all the testing. I guess we need to narrow down if it's `swap_buffers` or `get_vsync` doing it to you (or maybe both but I hope not). Could you undo everything and then try each one of these separately with the usual `--no-config --gpu-api=vulkan`?

```
diff --git a/video/out/vulkan/context_xlib.c b/video/out/vulkan/context_xlib.c
index 3392145e1a..e3cd21bad1 100644
--- a/video/out/vulkan/context_xlib.c
+++ b/video/out/vulkan/context_xlib.c
@@ -38,11 +38,11 @@ static void xlib_vk_swap_buffers(struct ra_ctx *ctx)
     present_sync_swap(ctx->vo->x11->present);
 }
 
-static void xlib_vk_get_vsync(struct ra_ctx *ctx, struct vo_vsync_info *info)
+/*static void xlib_vk_get_vsync(struct ra_ctx *ctx, struct vo_vsync_info *info)
 {
     struct vo_x11_state *x11 = ctx->vo->x11;
     present_sync_get_info(x11->present, info);
-}
+}*/
 
 static void xlib_uninit(struct ra_ctx *ctx)
 {
@@ -77,7 +77,7 @@ static bool xlib_init(struct ra_ctx *ctx)
     struct ra_vk_ctx_params params = {
         .check_visible = xlib_check_visible,
         .swap_buffers = xlib_vk_swap_buffers,
-        .get_vsync = xlib_vk_get_vsync,
+        //.get_vsync = xlib_vk_get_vsync,
     };
 
     VkInstance inst = vk->vkinst->instance;
```

```
diff --git a/video/out/vulkan/context_xlib.c b/video/out/vulkan/context_xlib.c
index 3392145e1a..b83313df65 100644
--- a/video/out/vulkan/context_xlib.c
+++ b/video/out/vulkan/context_xlib.c
@@ -32,11 +32,11 @@ static bool xlib_check_visible(struct ra_ctx *ctx)
     return vo_x11_check_visible(ctx->vo);
 }
 
-static void xlib_vk_swap_buffers(struct ra_ctx *ctx)
+/*static void xlib_vk_swap_buffers(struct ra_ctx *ctx)
 {
     vo_x11_present(ctx->vo);
     present_sync_swap(ctx->vo->x11->present);
-}
+}*/
 
 static void xlib_vk_get_vsync(struct ra_ctx *ctx, struct vo_vsync_info *info)
 {
@@ -76,7 +76,7 @@ static bool xlib_init(struct ra_ctx *ctx)
 
     struct ra_vk_ctx_params params = {
         .check_visible = xlib_check_visible,
-        .swap_buffers = xlib_vk_swap_buffers,
+        //.swap_buffers = xlib_vk_swap_buffers,
         .get_vsync = xlib_vk_get_vsync,
     };
 
```

**Comment by Gigas002** [comment]
Second patch (that comments `.swap_buffers`) fixes the problem

**Comment by Gigas002** [comment]
Commenting `//present_sync_swap(ctx->vo->x11->present);` fixes problem; `//vo_x11_present(ctx->vo);` isn't

**Comment by Dudemanguy** [comment]
Thank you very much. I guess that means I must make that function more restrictive since somehow it's affecting you.

**Comment by Dudemanguy** [comment]
@Gigas002: More patches for you. Could you apply this patch, play a video as usual but redirect the stdout to some file and upload it somewhere? Basically, it's just checking the timings.

```
diff --git a/video/out/present_sync.c b/video/out/present_sync.c
index 16d7416d43..aa4e8de803 100644
--- a/video/out/present_sync.c
+++ b/video/out/present_sync.c
@@ -47,6 +47,8 @@ void present_sync_swap(struct mp_present *present)
     int64_t ust = present->current_ust;
     int64_t msc = present->current_msc;
 
+    printf("current_ust: %" PRId64 "\n", ust);
+    printf("last_ust: %" PRId64 "\n", present->last_ust);
     // Avoid attempting to use any presentation statistics if the ust is 0 or has
     // not actually updated (i.e. the last_ust is equal to current_ust).
     if (!ust || ust == present->last_ust) {
```

**Comment by Gigas002** [comment]
Should I apply it to the latest commit in repo, or to the commented `//present_sync_swap(ctx->vo->x11->present);` version?

**Comment by Dudemanguy** [comment]
Oh sorry. Against the last commit in the repo please.

**Comment by Gigas002** [comment]
Well this log doesn't seem to be very interesting: https://0x0.st/ouCD.txt

**Comment by Dudemanguy** [comment]
That's actually what's supposed to happen. The mystery is how on earth can this cause a performance drop. All the function does is see that the ust 0 is 0, sets some values, and returns.

**Comment by Gigas002** [comment]
That's how it looks:

https://user-images.githubusercontent.com/24297712/174939307-1f97e26e-0637-4b4f-9e08-bce1d17ee0e1.mp4

**Comment by Dudemanguy** [comment]
I guess I'll semi-refactor how this is handled to avoid calling present-related functions when it's not needed. Although, I'm still confused how this could cause a problem in the first place. In the meantime, I'll pull in #10310 since it's related.

**Comment by monarc99** [comment]
@Gigas002 

i have a similar system (manjaro, kde, compiled mpv with same versions , only graphic card is different - nvidia 1060), i don't have the problems.

the only difference could be, i use nvidia modesetting
(https://wiki.archlinux.org/title/NVIDIA#DRM_kernel_mode_setting)

maybe modesetting must be enabled on nvidia systems. 

lsmod  | grep nvidia
nvidia_uvm           1196032  4
nvidia_drm             65536  8
nvidiafb               61440  0
vgastate               20480  1 nvidiafb
nvidia_modeset       1146880  20 nvidia_drm
fb_ddc                 16384  1 nvidiafb
drm_kms_helper        192512  3 drm_dp_helper,nvidia_drm,i915
i2c_algo_bit           20480  2 nvidiafb,i915
nvidia              40816640  1906 nvidia_uvm,nvidia_modeset
drm                   552960  16 drm_dp_helper,drm_kms_helper,nvidia,drm_buddy,nvidia_drm,i915,ttm

xrandr --listproviders
Providers: number : 1
Provider 0: id: 0x1b7 cap: 0x1, Source Output crtcs: 4 outputs: 8 associated providers: 0 name:NVIDIA-0

**Comment by Dudemanguy** [comment]
>maybe modesetting must be enabled on nvidia systems.

I wouldn't expect this, but then again I wouldn't expect this entire issue to begin with. Everything OP has provided indicates it's working as expected (minus the random performance hit of course...)

@Gigas002: If you don't mind, could you track down what actual line in `present_sync_swap` (it's in `present_sync.c`) is the culprit? At least, I'm assuming something in there is what's inexplicably causing a slowdown for you since we know that calling that function is what kills your performance.

**Comment by Gigas002** [comment]
> Commenting `//present_sync_swap(ctx->vo->x11->present);` fixes problem; `//vo_x11_present(ctx->vo);` isn't

Goddammit... Sorry for mistake, but after several tests I've found out that I've swapped these two. The `//vo_x11_present(ctx->vo);`.
