### ISSUE TITLE
Having trouble adding key binding

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#10325]
My lua script doesn't recognize Alt+o
```
mp.add_key_binding('Alt+o', function ()
  mp.command("cycle-values osd-level 0 1")
end)
```

**Comment by stax76** [comment]
I would add this to check the osd-level value:

print(mp.get_property("osd-level"))

And I would check if it works with `add_forced_key_binding`.

Your problem might be that `Alt+o` is already defined by mpv defaults or by user bindings, which you can check with:

`mpv.exe --input-test`

**Comment by cerealXDD** [comment]
> You can use print to print to the terminal:
> 
> `print(mp.get_property("osd-level"))`
> 
> With `mpv.exe --input-test` you can start mpv with pseudo-gui profile and input test mode where you can test what binding `Alt+o` has. Note that you have to use the .exe file extension to enable the pseudo-gui profile.
> 
> One reason why your code isn't working might be that `Alt+o` is already assigned by mpv defaults or by user bindings.
> 
> You can also try `mp.add_forced_key_binding` which would overwrite mpv defaults and user bindings.
> 
> You can step through the code using a debugger:
> 
> https://github.com/stax76/mpv.net/wiki/Extending-mpv-and-mpv.net-via-Lua-scripting

Thanks I'll give it a try

**Comment by cerealXDD** [comment]
> You can use print to print to the terminal:
> 
> `print(mp.get_property("osd-level"))`
> 
> With `mpv.exe --input-test` you can start mpv with pseudo-gui profile and input test mode where you can test what binding `Alt+o` has. Note that you have to use the .exe file extension to enable the pseudo-gui profile.
> 
> One reason why your code isn't working might be that `Alt+o` is already assigned by mpv defaults or by user bindings.
> 
> You can also try `mp.add_forced_key_binding` which would overwrite mpv defaults and user bindings.
> 
> You can step through the code using a debugger:
> 
> https://github.com/stax76/mpv.net/wiki/Extending-mpv-and-mpv.net-via-Lua-scripting
If I have a keybinding in input.conf will a keybinding in lua script override it?

**Comment by cerealXDD** [comment]
Ok add_forced_key_binding works for me. Going to close this
