### ISSUE TITLE
[help] How can I open video on the ongoing video player?

### ISSUE THREAD

**Issue by avatar-lavventura** [mpv-player/mpv#10329]
When I run, it opens video on a new video mpv player:

```bash
FILE="video.mp4"
(&>/dev/null mpv "$FILE" --start=25% --geometry=0%:50 --autofit=1700 &)
```

So I had to close on going video and open new one:

```bash
pkill -f mpv
FILE="video.mp4"
(&>/dev/null mpv "$FILE" --start=25% --geometry=0%:50 --autofit=1700 &)
```

Is there any way to force to open a video on ongoing mpv player?

**Comment by thebombzen** [comment]
You can also just drag and drop a video file from Finder onto the player.

**Comment by avatar-lavventura** [comment]
> You can also just drag and drop a video file from Finder onto the player.

I cannot do that I have to open videos from terminal without using GUI or dragging.
