### ISSUE TITLE
OpenGL error: GL_INVALID_OPERATION

### ISSUE THREAD

**Issue by christoph-heinrich** [mpv-player/mpv#10324]
- mpv 0.34.0-353-g230d490eca
- Arch Linux
- compiled from source
- introduced in 661b5542de21d46d4d7c4693e564f4eec0526812
- KDE Plasma 5.25.1 using Wayland
- Mesa 22.1.2 AMD R9 380

I get the following error when using `--vo=gpu-next` and OpenGL:
`[vo/gpu-next] gl_fb_query: OpenGL error: GL_INVALID_OPERATION`
Other then that message, everything seems to be working as expected.

### Reproduction steps

`mpv --no-config --idle=yes --force-window=yes --vo=gpu-next --gpu-api=opengl`
Does not happen with `--gpu-api=vulkan`.

### Expected behavior
No errors when everything is working fine.
### Actual behavior
`[vo/gpu-next] gl_fb_query: OpenGL error: GL_INVALID_OPERATION`

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/8952233/output.txt)

**Comment by Dudemanguy** [comment]
Ah yeah, that message is from libplacebo. It's harmless but perhaps scary looking.

**Comment by christoph-heinrich** [comment]
For future reference: As discussed in IRC, using `apitrace` was not successful. Neither the Arch package (1.5.10) nor any custom compiled version showed where this error occurs. A [fix](https://github.com/anholt/libepoxy/commit/dbfa4b209c0712b67dfeb8366c2ebe8503063b52) got [reverted](https://github.com/anholt/libepoxy/commit/622ca393c38a92e2fac9f877bbcf65f97782d206) again because it caused a bunch of new problems. Regardless I tried reverting the revert, which also didn't help.

**Comment by Dudemanguy** [comment]
That seems logical. The framebuffer likely doesn't exist the very first time that gets called.

**Comment by bsmith75** [comment]
I’m still getting this error with `vo=gpu-next` and `gpu-context=wayland` in mpv 0.35.1 on a fully-updated Manjaro installation.  Despite the error, mpv plays videos normally. 

```
[vo/gpu-next/libplacebo] gl_fb_query: OpenGL error: GL_INVALID_OPERATION
```

I have tried running `mpv -v` and saw no other messages concerning this error.
