### ISSUE TITLE
Mpv can't start any video

### ISSUE THREAD

**Issue by Gigas002** [mpv-player/mpv#10320]
### Important Information

mpv version:

```zsh
mpv 0.34.0-352-gb29878e3a1 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Tue Jun 21 03:34:56 2022
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: n5.0
```

linux destribution and version:

```zsh
Operating System: Manjaro Linux
Kernel: Linux 5.18.5-1-MANJARO
Architecture: x86-64
```

source of mpv binary: mpv-git from AUR: https://aur.archlinux.org/packages/mpv-git/

window manager: x11, KDE Plasma 5.25.0

GPU driver: proprietary nvidia driver 515.48.07

### Reproduction steps

`mpv --no-config`

### Expected behavior

Video starts

### Actual behavior

Errors:

```zsh
 (+) Video --vid=1 (*) (h264 1280x720 59.940fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
amdgpu: amdgpu_device_initialize failed.
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
amdgpu: amdgpu_device_initialize failed.
[vo/gpu] Failed to create GBM surface.
[vo/gpu] Failed to setup GBM.
[vo/gpu-next] Can't handle VT release - signal already used
[vo/gpu-next/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
amdgpu: amdgpu_device_initialize failed.
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-13)
amdgpu: amdgpu_device_initialize failed.
[vo/gpu-next] Failed to create GBM surface.
[vo/gpu-next] Failed to setup GBM.
Error opening/initializing the selected video_out (--vo) device.
Video: no video

Exiting... (Errors when loading file)
```

Also, when I run `mpv` as usual, without `--no-config` it screams about options parsing error:

```zsh
Error parsing option gpu-context (option parameter could not be parsed)
/home/gigas/.config/mpv/mpv.conf:27: setting option gpu-context='x11vk' failed.
```

Commenting the option doesn't help much:

```zsh
 (+) Video --vid=1 (*) (h264 1280x720 59.940fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[vo/gpu-next] Failed initializing any suitable GPU context!
Error opening/initializing the selected video_out (--vo) device.
Video: no video

Exiting... (Errors when loading file)
```

### Log file

Log: https://0x0.st/ouRL.txt

### Sample files

Any video file

**Comment by Gigas002** [comment]
Thank you, now it works, though performance somehow became extremely bad (with `--no-config` everything's OK)

**Comment by Gigas002** [comment]
After some experiments, it seems, like the mentioned option `gpu-context='x11vk'` makes performance really bad. It's still not great without it, but much better

**Comment by Dudemanguy** [comment]
>After some experiments, it seems, like the mentioned option gpu-context='x11vk' makes performance really bad. It's still not great without it, but much better

Just to be clear. Do you use `--video-sync=display-resample`? I was going to guess that maybe this was your problem. If it's specifically only related to using `x11vk` though, then it sounds like something else.

**Comment by Gigas002** [comment]
Yes, I'm using this option, but commenting it didn't help at all.

**Comment by Gigas002** [comment]
Here's the new log: https://0x0.st/ouRg.txt

**Comment by Dudemanguy** [comment]
Looking at it again, the auto-detection for the libxpresent stuff is actually bugged (and possibly kicking in for you depending on the order of the providers actually). Although I guess you have a different issue. If this started recently and it's not result of some driver update or something, feel free to open up a new issue.

P.S. Could you post the output of `xrandr --listproviders` for me?

**Comment by Gigas002** [comment]
Well, this wasn't an issue two of three days ago. Here's the output of  `xrandr --listproviders`:

```zsh
Providers: number : 2
Provider 0: id: 0x53 cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 4 outputs: 1 associated providers: 1 name:Unknown AMD Radeon GPU @ pci:0000:06:00.0
Provider 1: id: 0x1f5 cap: 0x2, Sink Output crtcs: 4 outputs: 1 associated providers: 1 name:NVIDIA-G0
```

I'll open a new issue tomorrow then, thanks for your help!

**Comment by Dudemanguy** [comment]
Thanks, so yeah assuming the provider order is the same when mpv tries to detect it (presumably it is anyway), then it's acting as intended for you (i.e. not being used because you have a nvidia GPU). So indeed, it shouldn't be related for you. Nothing else recently changed that should have to do with this though so it's hard to say.
