### ISSUE TITLE
vo=gpu-next D3D11 - PNGs are rendered green with deband active

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#10323]
When opening a PNG file with these settings, it is rendered green:
```
vo=gpu-next
gpu-api=d3d11
deband
keep-open=yes
```

It doesn't happen with

- gpu-api=vulkan
- with deband disabled
- with `vo=gpu`

Log:
[output.txt](https://github.com/mpv-player/mpv/files/8952155/output.txt)

mpv build:
[mpv-x86_64-20220619-git-c1a46ec.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220619-git-c1a46ec.7z/download)

Windows 11, Nvidia driver 512.95

**Comment by quietvoid** [comment]
Seems to be a duplicate of https://github.com/mpv-player/mpv/issues/10239

**Comment by aufkrawall** [comment]
Right, I even remember having seen that ticket. Oops.
