### ISSUE TITLE
How can I unset ab-loop properties? 

### ISSUE THREAD

**Issue by crumblingstatue** [mpv-player/mpv#10334]
I can set `ab-loop-a` and `ab-loop-b` in my mpv integration, but how can I unset it after?
I tried calling `mpv_set_property` with `MPV_FORMAT_NONE`, but I get the error `unsupported format for accessing property`.

**Comment by avih** [comment]
The docs mention it https://mpv.io/manual/master/#options-ab-loop-a

Set `ab-loop-a` and/or `ab-loop-b` to `no`.

**Comment by crumblingstatue** [comment]
The interesting thing is that they are not set to no by default.
They are unset by default.
Does that mean they only support being set to no after they were set, but they cannot be cleared?

**Comment by crumblingstatue** [comment]
Does this also mean there is no generic mechanism to clear properties? Each property has its own way of being "unset"?

**Comment by crumblingstatue** [comment]
Thank you for the help and clarification!
