### ISSUE TITLE
gpu-next - mpv's own window background image is mirror-inverted with OpenGL

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#10336]
```
vo=gpu-next
gpu-api=opengl
gpu-context=win
```

causes this when starting mpv.exe or Linux binary via XDG starter:
![mirror-inverted](https://user-images.githubusercontent.com/13510490/175755903-4c68030a-f2b7-4ca3-9dd4-825546bb0286.png)

Not sure how I would provide logs for this. Happens with both Nvidia and Intel Mesa Iris driver.
Doesn't happen with Vulkan & D3D11.
Has been the case since OpenGL backend was added for gpu-next afair and still happens with recent git-master builds.

**Comment by haasn** [comment]
Can reproduce
