### ISSUE TITLE
How to get the info that the file was played to the end?

### ISSUE THREAD

**Issue by ZaxonXP** [mpv-player/mpv#10339]
Hi,

I am trying to write the script to listen to the podcast and move to the next file only when the currently played will end.
But how to get the info from mpv that the file was played to the end and not exited using `Q` key presss?

Kind regards,
Piotr

**Comment by guidocella** [comment]
```lua
mp.register_event('end-file', function (event)
    if event.reason == 'eof' then

    end
end)
```

**Comment by ZaxonXP** [comment]
Thanks! I can work with that. :)
