### ISSUE TITLE
gpu-next "s" screenshots are different from "PrtSc"

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#10335]
### Important Information

Provide following Information:
- mpv version: 8da6b355f84381f932281a290a7a416ea4e7b3f2
- Windows Version: `19044.1766`
- Source of the mpv binary: [`shinchiro 20220624`](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20220624)
- If known which version of mpv introduced the problem: `Unknown`
- Possible screenshot or video of visual glitches
![diff_s_PrtSc](https://user-images.githubusercontent.com/67395204/175658371-24b45e52-d42d-4967-ac2e-6fc51d6e827a.png)

### Reproduction steps

Play an SDR video on an SDR display where the resolution of the video matches the display's and go full-screen. Have set `vo=gpu-next`, `screenshot-format=png`, and `screenshot-high-bit-depth=no`. Press `s` to save a screenshot, then press `PrtSc` to copy your screen to the clipboard and save it as a png with Paint. Then use ImageMagick `magick compare s.png PrtSc.png -compose src diff.png`. Gray pixels are identical, red ones are different. With `vo=gpu`, you will get a completely gray result. With `vo=gpu-next`, as visible above, there are many differences.

### Expected behavior

`s` and `PrtSc` should yield identical outputs under these circumstances. This _does_ occur with `vo=gpu`.

### Actual behavior

As visible in the picture, there are discrepancies.
With `vo=gpu`, `s`, `S-s` (as long as there are no subs visible), `C-s`, and `PrtSc` all agree with each other. With `vo=gpu-next`, the first three do agree but `PrtSc` dissents.

### Log file

https://pomf2.lain.la/f/f0z5wrm.txt

### Sample files

Any video that matches the constraints for the expected behavior to be valid as described in the reproductions steps should do.

**Comment by ZaquL** [comment]
Please recheck again with lastest master.

**Comment by Dudemanguy** [comment]
I could not reproduce this myself (difference image was gray as expected), the user is now a ghost, and this is pretty old so I will assume this has been fixed.
