### ISSUE TITLE
vo_dmabuf_wayland doesn’t display the OSD whatsoever

### ISSUE THREAD

**Issue by linkmauve** [mpv-player/mpv#10342]
### Important Information

Provide following Information:
- mpv version: 3a2838c88d
- Linux Distribution and Version: ArchLinux latest
- Source of the mpv binary: built from source
- If known which version of mpv introduced the problem: probably the one introducing vo_vaapi_wayland
- Window Manager and version: Weston master
- GPU driver and version: Mesa master (iris)
- Possible screenshot or video of visual glitches: ![wayland-screenshot-2022-06-27_19-03-37](https://user-images.githubusercontent.com/7755816/175996910-d97ca72a-13e7-474e-91af-73ec4347dcbd.png)

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

It is reproducible

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

1. `mpv --vo=vaapi-wayland some-file.mkv`
2. Move the mouse, or press o, or have a subtitle track, or pretty much anything which displays on the OSD.

### Expected behavior

The OSD would show up just like in vo_wlshm or vo_gpu.

### Actual behavior

No OSD gets displayed in any case.

### Log file

[mpv-sucks.txt](https://github.com/mpv-player/mpv/files/8994298/mpv-sucks.txt)

### Sample files

Any video file works.

**Comment by Dudemanguy** [comment]
This is known. See #10322.

**Comment by Dudemanguy** [comment]
Technically now called `vo_dmabuf_wayland` for the record (just noting it here; problem still exists).
