### ISSUE TITLE
[minor cosmetic] audio only can rewind to "-00"

### ISSUE THREAD

**Issue by pirate486743186** [mpv-player/mpv#10346]
### Important Information

I don't think this matters (expected to be universal)
- mpv version 0.32.0
- Debian 11/64bits
- Debian repos

### Reproduction steps

just run any audio file, or video file with --no-video. Pause, then rewind to the beginning with the arrow key. It will show "-00" (terminal and gui).

### Expected behavior

It should have shown "00"

### Actual behavior

It shows "-00"

### Other

Yes, this is really minor. I couldn't find it in the issues, so even if already fixed, it will be documented.

**Comment by thebombzen** [comment]
Do note that negative zero and positive zero actually `==` each other in IEEE floating point rules, so this is entirely cosmetic.

**Comment by tucak** [comment]
Hi,

It does not seem to be purely cosmetic. If I `quit-watch-later` while paused at "-00", the file in "watch_again" will have a non-zero negative "start" value. Resuming from it makes mpv seek to the end of the file. If I am trying to continue a playlist, this makes it skip the file where I quit, which is pretty annoying.

I can reproduce it easily on 0.36.0:
1. Open some audio file, pause it and rewind it to "-00".
2. Quit, saving to watch later.
3. Try to open it again.

What should happen: the file opens at the very beginning, paused.

What actually happens: mpv exits with "End of file".
