### ISSUE TITLE
Set A-B loop individually

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#10340]
I know the letter l is mapped to ab-loop, but I want to set a-b loop points individually

For example, a is set to the a point, b is set to the b point, and l to clear

Anyone know if this is possible

**Comment by guidocella** [comment]
```
a set ab-loop-a ${=time-pos}
b set ab-loop-b ${=time-pos}
l set ab-loop-a no; set ab-loop-b no
```

**Comment by cerealXDD** [comment]
> a set ab-loop-a ${=time-pos}
> b set ab-loop-b ${=time-pos}
> l set ab-loop-a no; set ab-loop-b no

Thanks
