### ISSUE TITLE
How do I unset loop in mpv for life and tell it to ignore the keypresses for either l or L (happens accidently quite a bit.)

### ISSUE THREAD

**Issue by shirishag75** [mpv-player/mpv#10359]
I have made the following config file, please see if it's any good or not. 

```
alang=eng,en,english
slang=en,eng, english
sub-scale=1.00
save-position-on-quit
l ignore
L ignore
```

I am using mpv 0.34.1 on FFmpeg version: 5.0.1-3 on Debian tessting. 

I also looked up https://defkey.com/mpv-media-player-shortcuts but this one isn't at all obviously comprehensive on all the keyboard shortcuts that mpv provides.

**Comment by guidocella** [comment]
`slang=en,eng, english` shouldn't have a space.

Keybindings like `l ignore` go in `input.conf`, which is a different file from `mpv.conf`.

**Comment by shirishag75** [comment]
> `slang=en,eng, english` shouldn't have a space.
> 
> Keybindings like `l ignore` go in `input.conf`, which is a different file from `mpv.conf`.

Done - 

```
~/.config/mpv$ cat input.conf 
l ignore
L ignore
```

Now my question is how do I tell mpv to clear the loop of a particular media file that I'm playing or rather forget its history altogether.

**Comment by guidocella** [comment]
`sed -i '/^ab-loop-/d' ~/.config/mpv/watch_later/*`
