### ISSUE TITLE
How do I cancel autoplay the next episode in a list?

### ISSUE THREAD

**Issue by rockyyee** [mpv-player/mpv#10355]
When I play a list, I want to play the next episode manually.
I can't find some options, pls hlep me.

**Comment by garoto** [comment]
`keep-open=always` probably.

```
--keep-open=<yes|no|always>
[...]
  always Like yes, but also applies to files before the last
         playlist entry. This means playback will never
         automatically advance to the next file.
```

**Comment by rockyyee** [comment]
> `keep-open=always` probably.
> 
> ```
> --keep-open=<yes|no|always>
> [...]
>   always Like yes, but also applies to files before the last
>          playlist entry. This means playback will never
>          automatically advance to the next file.
> ```

Thanks bro
