### ISSUE TITLE
Display only the bottom line of Youtube Auto Subs

### ISSUE THREAD

**Issue by barraIhsan** [mpv-player/mpv#10361]
So if you watch youtube video (and turn on the auto sub) with mpv, you notice that the subtitle has 2 lines.

The first line is just like the previous subtitle, so after the subtitle is playing, it will moved to the first line.

![image](https://user-images.githubusercontent.com/57800056/177023750-f1157a58-1666-4778-917d-3031faefeff2.png)

Is there an option to hide the first line? Or only show the bottom line of the subs?

### Log file
https://0x0.st/oQqx.txt

**Comment by ZaquL** [comment]
What video is that?

**Comment by garoto** [comment]
Val, step away from the Vodka bottle and stop bumping old useless issues with useless inquiries.

**Comment by barraIhsan** [comment]
> same problem here. did you find a way?

nope

**Comment by phineas-pta** [comment]
it's an youtube issue with webvtt see yt-dlp/yt-dlp#1734
