### ISSUE TITLE
Visual c++ runtime library Assertion Failed! error when using MPV with SVP 4

### ISSUE THREAD

**Issue by Ekramhadidi** [mpv-player/mpv#10360]
### Important Information

Provide following Information:
**- mpv version**
 mpv 0.33.0-209-gf2afae55e9 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Jul  4 10:21:51 +08 2021
 FFmpeg library versions:
 libavutil       57.0.100
 libavcodec      59.3.100
 libavformat     59.4.100
 libswscale      6.0.100
 libavfilter     8.0.103
 libswresample   4.0.100
 FFmpeg version: git-2021-07-03-70874e02

**- Windows Version**
  21h1
**- Source of the mpv binary**
 i got  a prepacked mpv from a blog

**- If known which version of mpv introduced the problem**
this version and even earlier ones packed with SVP 4

**- Possible screenshot or video of visual glitches**
[https://prnt.sc/Rwt4i6LQjTsz](url)
[https://prnt.sc/1B5VI0TwQlwC](url)

> If you're not using git master or the latest release, update.
> Releases are listed here: https://github.com/mpv-player/mpv/releases
> 

### Reproduction steps
this error only happens when svp tries to inject into mpv when playing specific video files. those that say "unknown frame rate" in the error. 
mpv can play those files just fine when svp code is disabled or svp is not running. svp can successfully inject into mpc-hc when playing those files with no errors. which makes me think this is a problem related to how svp interacts with mpv during certain playbacks. 

i don't know what steps are necessary to reproduce this error. all i did was install svp with mpv and found that some anime video files are giving me this error. pressing _Ignore_ option closes the error message and the video plays just fine but svp is not injected into mpv. 
 
**### Expected behavior**
svp injecting successfully into mpv when playing those files like the rest.
**### Actual behavior**
runtime error. causing svp not to work with mpv during certain playbacks
**### Log file**
  [logmpv.txt](https://github.com/mpv-player/mpv/files/9033657/logmpv.txt)
 
### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
This issue tracker isn't svp support. We cannot provide support for proprietary third party software.

**Comment by Ekramhadidi** [comment]
> This issue tracker isn't svp support. We cannot provide support for proprietary third party software.

do i take it that the log file i have provided does not indicate anything wrong with my mpv? only on svp side?

**Comment by thebombzen** [comment]
> this error only happens when svp tries to inject into mpv when playing specific video files

Sounds like it's not an mpv problem.
