### ISSUE TITLE
Change every Instance of "Mobius" to "Morbius"

### ISSUE THREAD

**Issue by DNDEBUG** [mpv-player/mpv#10365]
I'm not sure if this was a misspelling but
but i believe the word "Mobius" should be changed to "Morbius" to match the title of the 300 Morbilion dollars masterpiece of a movie released in March 10, 2022 ([Plaza Carso](https://en.wikipedia.org/wiki/Plaza_Carso))
    April 1, 2022 (United States)
    (according to wikipedia)
# MORBIUS
![image](https://user-images.githubusercontent.com/98880063/177227814-56d68cb9-ec4b-4c97-94c1-e354d659e574.png)

Morbius Is the movie ever made and the mpv devs changing "Mobius" to "Morbius" would be a great change for mpv
for the fact that one can use hardware acceleration while watching Morbius on MPV

**Comment by paulguy** [comment]
It'd be more funny to change subs to susses.  Even though it's the older meme, it's far less in the grave than this meme.

**Comment by haasn** [comment]
Patches welcome (tm)

**Comment by CounterPillow** [comment]
cringe forced meme

**Comment by DNDEBUG** [comment]
> Patches welcome (tm)

hell nah
you do it
and do if for free
