### ISSUE TITLE
PNG - Crash

### ISSUE THREAD

**Issue by Ichisich** [mpv-player/mpv#10362]
- mpv 0.34.0-365-g369168b9be
- Windows 10 21H2 (Build 19044.1766)
- Windows builds by shinchiro
- First encountered: 3a2838c

Opening PNG files with certain aspect ratios and heights crashes mpv. 
The terminal shows the following:
![terminal](https://user-images.githubusercontent.com/31080003/177035005-f4207bb5-8f78-4e9c-a4d9-f298c6b39ed2.png)

I tested multiple scaled files, and it gets quite messy.
Firstly, every file which is not a PNG or has a height of 1080pixel (with one exception) doesn't crash.
Secondly, only `gpu-api=d3d11` is affected.

I tried to see a pattern, but here we go | (+)=works | (-)=crashes | x-axis=height (in pixel) | y-axis=aspect ratio
![tab](https://user-images.githubusercontent.com/31080003/177039190-2d45ba4a-c75a-40e2-9e0f-bae56fe9eae2.png)

**Comment by dyphire** [comment]
This look like a zimg issue, try use `--sws-allow-zimg=no` to test again.
refer https://github.com/shinchiro/mpv-winbuild-cmake/issues/227#issuecomment-1167244058, It has not actually been fixed.

**Comment by Ichisich** [comment]
Yes, `sws-allow-zimg=no` prevents crashing.

**Comment by swiftarm** [comment]
Coming in to say `sws-allow-zimg=no` fixed my issue too. I kept getting  `[ao/wasapi] Under-run: Device delay: -0.2 us` when trying to screenshot certain videos after updating to the newest version (mpv 0.34.0-365-g369168b9be). 

Not 100% sure this is the correct github page for the version of MPV I have, but it fixed my problem.

**Comment by ZaquL** [comment]
https://github.com/sekrit-twc/zimg/issues/182#issuecomment-1175800898

**Comment by thebombzen** [comment]
Can you reproduce this still with master?
