### ISSUE TITLE
Advanced Subtitle Picking

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#10377]
Hi, I'd like to propose a new feature taken from LAV Filters. Add advanced subtitle picking. I'd like the ability to pair audio and subtitles so no subtitles are displayed for languages I speak.

**Comment by thebombzen** [comment]
Does `--subs-with-matching-audio=no` work for you?

**Comment by george-emerald** [comment]
What does that do? If it's English it won't show English subtitles?

**Comment by george-emerald** [comment]
I checked and it doesn't work, because it can choose other languages.

**Comment by george-emerald** [comment]
Fixed this by install the sub-select script. I'd recommend anyone having the same question do the same.

**Comment by zotabee** [comment]
> sub-select script

I imagine that's its the following project ?! : https://github.com/CogentRedTester/mpv-sub-select
