### ISSUE TITLE
[vo/gpu] errors

### ISSUE THREAD

**Issue by nicolaasjan** [mpv-player/mpv#10370]
### Important Information

Provide following Information:
- mpv version: 0.34.0-366-g659ab2f946
- Linux Distribution and Version: Linux Mint 20.3
- Source of the mpv binary: https://github.com/mpv-player/mpv-build.git
- If known which version of mpv introduced the problem: Not sure. **0.34.0-321-g7ff4a27eb6** was alright.
- Window Manager and version: Compiz 0.9.14.1
- GPU driver and version: Intel i965 driver for Intel(R) Haswell Desktop - 2.4.0
- Possible screenshot or video of visual glitches: N/A

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

`mpv --no-config https://www.youtube.com/watch?v=WJtjZ-SkioM`

### Expected behavior: 
Video should play.

### Actual behavior:

```
 (+) Video --vid=1 (*) (vp9 1280x720 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Uploader: Lewis's Tech
 Channel_URL: https://www.youtube.com/channel/UCLZxPVkEvf9XuifStuHK_gA
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu] Failed to commit ModeSetting atomic request (-13)
[vo/gpu/opengl] Failed to set CRTC for connector 58: Permission denied
Error opening/initializing the selected video_out (--vo) device.
Video: no video


Exiting... (Errors when loading file)
```

### Log file:
https://0x0.st/oQ9E.txt

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
You compiled without x11 support because xpresent is now required. Install the xpresent development package and rebuild

**Comment by nicolaasjan** [comment]
Thanks! 👍️
Now it works:

```
mpv https://www.youtube.com/watch?v=WJtjZ-SkioM
 (+) Video --vid=1 (*) (h264 1280x720 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
File tags:
 Uploader: Lewis's Tech
 Channel_URL: https://www.youtube.com/channel/UCLZxPVkEvf9XuifStuHK_gA
Using hardware decoding (vaapi).
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1280x720 vaapi[nv12]
AV: 00:00:21 / 00:22:28 (2%) A-V:  0.000 Cache: 0.8s/61KB
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Packet corrupt (stream = 0, dts = 673673).
[ffmpeg] NULL: Invalid NAL unit size (736 > 499).
[ffmpeg] NULL: missing picture in access unit with size 503

Exiting... (Quit)
```

**Comment by mlindner** [comment]
Note: On archlinux this package is named "libxpresent".
