### ISSUE TITLE
support for mouse key combinations

### ISSUE THREAD

**Issue by pc00per** [mpv-player/mpv#10375]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
Add support for mouse key combinations such as `MBTN_RIGHT+WHEEL_UP`. Should be able to assign more inputs & do much more with just mouse.

Edit: As per https://mpv.io/manual/master/#input-conf-syntax:

    a-b-c show-text "command run after a, b, c have been pressed"

I could streak mouse buttons, but can't use them continuously, as `WHEEL_UP` needs holding `MBTN_RIGHT`

**Comment by pc00per** [comment]
> I did a quick test: both Shift+`WHEEL_DOWN` and Ctrl+`MBTN_LEFT` works.

Thank you !
> As for `MBTN_RIGHT+WHEEL_UP`, what you are looking for is `MBTN_RIGHT-WHEEL_UP`.

This does work, but the problem is that I had to lift MBTN_RIGHT for each trigger (For ex, you put volume, or pan-zoom on it, you would expect hold right-click + wheeling)
> Quoted from https://mpv.io/manual/master/#input-conf-syntax:
> 
> > a-b-c show-text "command run after a, b, c have been pressed"

**Comment by avih** [comment]
mpv doesn't support combinations of arbitrary keys.

The only supported combinaions are of any group of modifiers (shift, alt, control, meta) plus a key or mouse thing.

**Comment by pc00per** [comment]
> mpv doesn't support combinations of arbitrary keys.
> 
> The only supported combinaions are of any group of modifiers (shift, alt, control, meta) plus a key or mouse thing.

Was about to say if it would be great to be able to make any mouse key arbitary? Doing that would bring lots of possibilities for mouse key combinations right.
