### ISSUE TITLE
how to set `x11vk` for xorg & `waylandvk` gpu-context for wayland ?

### ISSUE THREAD

**Issue by pc00per** [mpv-player/mpv#10374]
Auto mode selects `opengl` gpu-contexts that have the issue
`[vo/gpu/opengl] after creating texture: OpenGL error INVALID_OPERATION.`
vulkan gpu-contexts won't have this issue.

Problem is, how to incorporate vulkan gpu-contexts automatically in config file when switching display servers ?
Something like `auto-vulkan` is needed.

**Comment by pc00per** [comment]
@Dudemanguy Tqvm

**Comment by pc00per** [comment]
Btw, vulkan on wayland is not yet florished. It has stutter issues. I'd probably stick with opengl for now.

**Comment by Dudemanguy** [comment]
There's not supposed to be any difference in theory. Depends mostly on your drivers.

**Comment by pc00per** [comment]
> There's not supposed to be any difference in theory. Depends mostly on your drivers.

Nvidia. So yep, nvdec on wayland/vulkan stutters. This might not be the case on intel/amd hardware.
