### ISSUE TITLE
Windows Compilation with LGPL FFMpeg

### ISSUE THREAD

**Issue by ChrisLambert1** [mpv-player/mpv#10383]
Hi all,
thank you for developing mpv and for detailed descriptions about the build process!
But there is one question I have no answer right now, 'cause of not understanding the complete build process as described
by the howto https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md.
Therefor I setup the environment with MSYS2 under windows, but my goal is to include a LGPL version of FFmpeg.
As far as I understood the documentation, MSYS2 is pulling specific wheels / prebuilds and if I see right the FFmpeg wheel is only as GPL version available (https://packages.msys2.org/base/mingw-w64-ffmpeg).

So I think I have to build FFmpeg on my own, an would try to build it according to the Cross-compilation tutorial with MXE.
In the tutorial the line 
make gcc ffmpeg libass jpeg lua luajit invokes the build and having a look on the FFmpeg site, compiling the FFmpeg without any command (Compile FFmpeg without "--enable-gpl" and without "--enable-nonfree / https://ffmpeg.org/legal.html) should lead to a LGPL build of FFmpeg?

Is my understanding correct, or did I missed there something?
Regards,
Chris

**Comment by thebombzen** [comment]
Yes, FFmpeg is LGPL by default, so provided you don't use `--enable-gpl` or `--enable-nonfree` it will only compile LGPL code.

**Comment by ChrisLambert1** [comment]
Thank you for the answer, so I'll have to give the mxe tutorial a try for the build process and provide feedback if it worked for me.

**Comment by alexmercerind** [comment]
> Thank you for the answer, so I'll have to give the mxe tutorial a try for the build process and provide feedback if it worked for me.

I actually use LGPL version of libmpv on Windows. But, I have disabled video output completely in my builds.

Repository: https://github.com/harmonoid/harmonoid-custom-codec
Builds: https://github.com/harmonoid/harmonoid-custom-codec/releases/tag/0.34.0-196-g4629fe557f

P.S. I'm sure it is going to take you a lot of attempts to figure the right configuration out. There are a lot of CMake dependencies which tend to be broken at times.

**Comment by ChrisLambert1** [comment]
Another question while I'm thinking about a possible LGPL FFmpeg integration:
There is a LGPL build available for download from ffmpeg.org (https://github.com/BtbN/FFmpeg-Builds/releases) and now I wonder if following approach would work:
1) Compile mpv with **--enable-lgpl with shared libs** for Win64bit
2) Exchange build shared libs from the mpv build process with downloaded shared libs from the ffmpeg shared libs lgpl build

Could this way work?

**Comment by CounterPillow** [comment]
That depends on whether the two builds have the same ABI, which depends on a variety of factors, such as used compiler, version of the code, configuration, etc.

If you have been hired to build a proprietary application that uses libmpv and therefore require to use LGPL I urge you to do your job and figure these things out yourself instead of badgering volunteers who graciously let you use their code in the first place.

**Comment by adlerzei** [comment]
@ChrisLambert1 Did you get any results?

**Comment by ChrisLambert1** [comment]
@adlerzei Hi, there are too possibilities that worked for me with pros and cons.
1st: Using lgpl prebuild is working in general, but you cant be sure whats inside the build.
2st: use m-ab-s (Project in git available) suite to build everything thats needed. But build process takes sometime, also build is done by using daily source code of used dependencies. That leads to failed builds often.
