### ISSUE TITLE
D3D11 breaks with certain PNG files

### ISSUE THREAD

**Issue by jiangzhenjerry** [mpv-player/mpv#10386]
### Important Information
- This issue could be somewhat related to #10239 
- mpv version: mpv-x86_64-20220703-git-369168b
- Windows Version: Windows 11 x64
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/
- If known which version of mpv introduced the problem: mpv-x86_64-20220626-git-3a2838c

### Reproduction steps
- No specific flags are needed. In Windows, the default `gpu-api` is `d3d11` already. Just run `mpv.exe` without any flags and open the image below.
- **Optional:** You may want to add `--keep-open` so that you can differentiate between a normal quit and a crash.

### Expected behavior
The Image should open without any problem.

### Actual behavior
Recap #10239 (before mpv-x86_64-20220626-git-3a2838c): In most cases the image will be displayed correctly. The image is displayed with a heavy tint **only if** `--vo=gpu-next, --deband` is specified; otherwise fine.

Now (starting mpv-x86_64-20220626-git-3a2838c): MPV immediately crashes and quits, as long as I'm using `d3d11`. The only workaround is to switch to another gpu-api, for example, `--gpu-api=opengl`.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/9074901/output.txt)

### Sample files
![Cover](https://user-images.githubusercontent.com/9311082/178066675-d39d19a9-cced-4341-8f17-457c1e8ff957.png)

**Comment by dyphire** [comment]
dup https://github.com/mpv-player/mpv/issues/10362

**Comment by jiangzhenjerry** [comment]
True. Closing this issue. Thanks!
