### ISSUE TITLE
Dolby Vision property

### ISSUE THREAD

**Issue by Doofussy2** [mpv-player/mpv#10390]
I want to make an auto-profile exclusively for Dolby Vision, but I haven't found a property that would allow this. Is there such a property?

**Comment by haasn** [comment]
Not currently. I remember looking into this but I don't remember exactly what the conclusion was. Some things are unfortunately very hard to support as properties because DoVi records are attached to individual frames, rather than the stream.

However, the config record is present at the stream-level, so we should be able to make a property for its presence or absence. I don't remember why I didn't.

**Comment by dyphire** [comment]
> Not currently. I remember looking into this but I don't remember exactly what the conclusion was. Some things are unfortunately very hard to support as properties because DoVi records are attached to individual frames, rather than the stream.
> 
> However, the config record is present at the stream-level, so we should be able to make a property for its presence or absence. I don't remember why I didn't.

Maybe we just need to create a property for the profile of Dolby Vision, such as dolbyvision-profile.

**Comment by Doofussy2** [comment]
The reason I need the profile at all, is because when running Windows in HDR, Dolby Vision is way too bright (low target-peak) and I have to specify the `target-peak` for it to display correctly. Presently, DoVi is initially read as bt.709., so I have a profile for bt.709 with `target-peak=1000` specified, which corrects it. But this in turn, makes the SDR media too dark. Still watchable, but obviously not correct. Regardless of this I would still prefer to be able to make a profile for DoVi.

**Comment by mdannp** [comment]
I am using this, which works as long as filenames are named accordingly:
[DV]
profile-desc=DV
profile-cond=filename ~= nil and (filename:upper():match"[.]DV[.]" ~= nil or filename:upper():match"[.]DOVI[.]" ~= nil) and p["video-params/gamma"]~=nil and p["video-params/gamma"]~="pq" 
# .. your profile settings

**Comment by ZaquL** [comment]
Ah, what is the point. You need to retag with format it as PQ and BT.2020 (and in some cases full range) for it to even work and teigger HDR in vulkan (d3d11 is not autotrigger thingy, dumb Microsoft).

**Comment by dyphire** [comment]
After this commit https://github.com/mpv-player/mpv/commit/3cf71fd7c7f5d4052b67ebdf11ff416a9beffbeb, the following auto-profile can be used to the video of Dolby Vision Profile 5.
```ini
[DoVi]
profile-cond=p["hdr-metadata"] ~= nil and p["video-params/gamma"] == "bt.1886"
profile-restore=copy
# ... your profile settings
```

**Comment by dyphire** [comment]
> SDR video also causes this profile to be triggered.

Indeed, it's confusing.

**Comment by Doofussy2** [comment]
There's nothing in that commit that uniquely identifies Dolby vision metadata. It's for HDR10 and HDR10+

**Comment by dyphire** [comment]
> hdr-metadata/max-luma and hdr-metadata/max-pq-y should be able to be used to differentiate between HDR (including DVP5)/SDR video, which is the main use case for the DV attribute, but for some reason this one has no effect.
> 
> ```
> [HDR]
> profile-cond=p["hdr-metadata/max-luma"] > 203 or p[" hdr-metadata/max-pq-y"] ~= nil
> profile-restore=copy
> target-trc=pq
> target-prim=bt.2020
> ```

I attempted to use this sub property of `hdr-metadata/max-pq-y` for auto-profile at the beginning, but it not work.

**Comment by Doofussy2** [comment]
> > hdr-metadata/max-luma and hdr-metadata/max-pq-y should be able to be used to differentiate between HDR (including DVP5)/SDR video, which is the main use case for the DV attribute, but for some reason this one has no effect.
> > ```
> > [HDR]
> > profile-cond=p["hdr-metadata/max-luma"] > 203 or p[" hdr-metadata/max-pq-y"] ~= nil
> > profile-restore=copy
> > target-trc=pq
> > target-prim=bt.2020
> > ```
> 
> I attempted to use this sub property of `hdr-metadata/max-pq-y` for auto-profile at the beginning, but it not work.

That would include all HDR. I am looking for a property that will exclusively apply to Dolby Vision.

**Comment by haasn** [comment]
> hdr-metadata/max-luma and hdr-metadata/max-pq-y should be able to be used to differentiate between HDR (including DVP5)/SDR video, which is the main use case for the DV attribute, but for some reason this one has no effect.
> 
> ```
> [HDR]
> profile-cond=p["hdr-metadata/max-luma"] > 203 or p[" hdr-metadata/max-pq-y"] ~= nil
> profile-restore=copy
> target-trc=pq
> target-prim=bt.2020
> ```

Can somebody explain to me what the point of this profile is supposed to be? Why would you need to distinguish between HDR and SDR profiles?

**Comment by Doofussy2** [comment]
My request is specifically for Dolby Vision. The reason is, in my case the tone mapped result is too bright, and I want to adjust it.

**Comment by dyphire** [comment]
> After some experimentation, I've found that these properties are not available when the video is not playing, thus causing the return value to always be nil, so it may be necessary to have the conditional profile delay loading. I think a lua script is needed instead of a profile.

I have an idea to make it work properly.
```ini
[DoVi-profile 5]
profile-cond=p["estimated-vf-fps"] > 1 and p["video-params/gamma"] == "bt.1886" and mp.get_property("hdr-metadata/max-pq-y") ~= nil
profile-restore=copy
# ... your profile settings
```

**Comment by dyphire** [comment]
> > > > hdr-metadata/max-luma and hdr-metadata/max-pq-y should be able to be used to differentiate between HDR (including DVP5)/SDR video, which is the main use case for the DV attribute, but for some reason this one has no effect.
> > > > ```
> > > > [HDR]
> > > > profile-cond=p["hdr-metadata/max-luma"] > 203 or p[" hdr-metadata/max-pq-y"] ~= nil
> > > > profile-restore=copy
> > > > target-trc=pq
> > > > target-prim=bt.2020
> > > > ```
> > > 
> > > 
> > > Can somebody explain to me what the point of this profile is supposed to be? Why would you need to distinguish between HDR and SDR profiles? If you override `target-trc`/`target-prim` without actually enabling HDR mode, output will just be wrong. If you _are_ enabling HDR mode, it should already have set the right output colorspace for you.
> > 
> > 
> > The goal is to output HDR video in HDR mode and output SDR video in SDR mode, mainly to address the DoVi P5 trope. I've set target-colorspace-hint=yes before this profile, so it won't cause wacky colors
> 
> Ah, so it's a work-around for `--target-colorspace-hint` not taking into account DV metadata? Then that should be fixed instead of hacking around it with properties. Incidentally, this is the same fix as [#12221 (comment)](https://github.com/mpv-player/mpv/issues/12221#issuecomment-1695977524)

Yes, fixing it is much better than using this hacker method.

**Comment by danbezerra** [comment]
I would also take advantage of a DV property on my scenario:
1. All HDR content is tone mapped to SDR BT.2020 (projector user here)
2. I want to avoid DV metadata when handling P7 MKV rips (potential issue with FEL brightness) so I use vf=format:dolbyvision=no as part of my HDR profile and rely on hdr-compute-peak.
3. However , for DV Profile 5 I have to re-enable DV support. All other HDR settings from my HDR profile would still apply.

Today, as others have said, DV P5 will fallback to my SDR bt.709 profile, which is wrong and messes up with my Blu-ray profile. I think there could be two ways to properly address this limitation:

a. a new setting that would allow me to turn off dolby vision support only when a 2nd video layer is present (P7). This way I could share my HDR profile with both HDR and DV (P5, P7...) files.
b. a new setting that would indicate that a given file is DV P5, allowing me to create a profile specific for this scenario.

**Comment by Kapppa** [comment]
Any update on this being possibly implemented?

**Comment by dyphire** [comment]
> Any update on this being possibly implemented?

The following auto-profile can be used for DoVi P5.
```ini
[DoVi-P5]
profile-cond=p["video-out-params/max-luma"] > 203 and p["video-params/gamma"] == "bt.1886"
profile-restore=copy
...
```

Other non P5 DoVi videos can only be treated as HDR for processing.

**Comment by kasper93** [comment]
> profile-cond=p["video-out-params/max-luma"] > 203 and p["video-params/gamma"] == "bt.1886"

After merge of https://github.com/mpv-player/mpv/pull/13458 this has been fixed and will no longer use dummy values on `video-*-params`

Now you should do something like this for P5. Alternatively you can use `video-out-params` if you want it to be affected by `--vf=format:dolbyvision=no`. Depends on use case.
```
[DoVi-P5]
profile-cond=get("video-params/colormatrix") == "dolbyvision" and get("video-params/colorlevels") == "full"
profile-restore=copy

```

**Comment by kasper93** [comment]
`track-list/N/dolby-vision-profile` and `track-list/N/dolby-vision-level` has been added, is this enough for you. Or you want something else?

**Comment by steo86** [comment]
I tried to get it working with the follolwing profile condition:

**[DolbyVision]
profile-desc=DolbyVsion
profile-cond=p["video-params/gamma"]=="pq" and (p["track-list/N/dolby-vision-profile"] ~= nil or p["track-list/N/dolby-vision-level"] ~= nil)**

but it´s not working even in logfile dolby vision is detected.

**[   8.578][d][mkv] |  + Track number: 1
[   8.578][d][mkv] |  + Track type: Video
[   8.578][d][mkv] |  + Video track
[   8.578][d][mkv] |   + Display width: 3840
[   8.578][d][mkv] |   + Display height: 2160
[   8.578][d][mkv] |   + Pixel width: 3840
[   8.578][d][mkv] |   + Pixel height: 2160
[   8.578][d][mkv] |  + Codec ID: V_MPEGH/ISO/HEVC
[   8.578][d][mkv] |  + CodecPrivate, length 795
[   8.578][d][mkv] |  + LanguageBCP47: en
[   8.578][d][mkv] |  + Default flag: 0
[   8.578][d][mkv] |  + Default duration: 41.708ms ( = 23.976 fps)
[   8.578][d][mkv] |  + Dolby Vision - version: 1.0, profile: 7, level: 6, RPU: 1, EL: 1, BL: 1, ID: 6
[   8.578][w][mkv] Dolby Vision enhancement-layer playback is not supported.**

How should the profile condition look like?
