### ISSUE TITLE
SFVIP issue with MAC  accessfor sever premium-ott

### ISSUE THREAD

**Issue by djmxx** [mpv-player/mpv#10393]
Hello,

Could you pleqse investigate whu SFVIP version 1.2.4.8 sopped working with MAC's for this server
http://premium-ott.net:8000

windows 10 64 bits

It used to work fine with MAC's but now it stopped, probably sever hardened their security for MAC access which requires an update to SFVIP to handle thse changes

Thanks a lot

**Comment by CounterPillow** [comment]
this is the mpv bug tracker, not whatever "SFVIP" is
