### ISSUE TITLE
Is there any way for MPV to report if frame drop is taking place so I can parse/use it somewhere?

### ISSUE THREAD

**Issue by rizzini** [mpv-player/mpv#10397]
I'm trying to make smarter usage of my CPU power due to better control my temperatures. Having this kind of report would help to determine how much power I'd need to give to my system while running MPV. I'm on Linux, Arch.

Appreciated it, guys. Keep it up.

**Comment by Dudemanguy** [comment]
`frame-drop-count` is a property you can access.

**Comment by haasn** [comment]
See also `--dump-stats` if you need an even greater insight into what mpv is doing.

**Comment by rizzini** [comment]
Awesome, guys! This is exactly what I need. `--dump-stats` fitted like glove. Happily closing this issue.
