### ISSUE TITLE
vo=gpu crashes during window resize on macOS

### ISSUE THREAD

**Issue by rcombs** [mpv-player/mpv#10406]
### Important Information

- mpv 7ff4a27eb600dc01d20547880056c13d6cf3e9e7, built locally
- macOS version 12.4 (21F79)

### Reproduction steps

Play any video with `-vo gpu` (as required for `wid` embedding on macOS) on an M1-series Mac and drag-resize the window (or otherwise resize the view) while playback is in progress.

### Expected behavior

Playback should continue normally during and after a view resize.

If we want to drop the vo=gpu path on macOS, we should support `wid` embedding with the libmpv vo there.

### Actual behavior

The video flashes black during the resize, and mpv may crash in the GL driver. My rough guess is that this is some sort of a race condition, but I don't know exactly where.

### Log file

Crash dumps:
https://gist.github.com/3cd5e648f4e352556164e9ce8ed279d8
https://gist.github.com/12db4679fe63cb18940f50e66d956df8
https://gist.github.com/690f3a42249356a22c06cc252df116e5

(Note 1st and 3rd happen on the vo draw thread, while the 2nd happens on an internal driver thread)

mpv log (from third crash):
https://gist.github.com/2f3c90551d3fad3372fc71643ef3c542

### Sample files

N/A, happens on any file

**Comment by Akemi** [comment]
the old cocoa backend ist deprecated and not maintained. so going to close this issue.

wid embedding is and always was the lowest priority for cocoa-cb/the libmpv macOS backend but can be a feature request.

```
[vo/gpu] opengl cocoa backend is deprecated, use vo=libmpv instead
```

**Comment by rcombs** [comment]
Is there any supported way to do wid embedding on macOS, then? We moved to it to simplify our GL interactions and solve some problems we had with GL embedding, and it'll be essential for Vulkan/Metal support (unless Vulkan/Metal support is added to the vo_gpu API natively).

**Comment by Akemi** [comment]
there isn't. like i said you can make a feature request for the cocoa-cb backend, but this old backend is deprecated/dead if none wants to take over the maintainer burden and fix all the problems.

there is the moltenvk WIP PR. though it shares the code with the cocoa-cb backend and doesn't support wid embedding either atm.

**Comment by rcombs** [comment]
I dealt with this in our fork with https://github.com/plexinc/mpv/commit/67722e6c197b8bf8b9c3a082d6c4bc472d3e5d76.
