### ISSUE TITLE
How can I use ffmpeg which installed locally(such as ~/local) rather than installed in my system(such as /usr) while building mpv

### ISSUE THREAD

**Issue by AlanKing95** [mpv-player/mpv#10402]
### mpv version and platform versions

mpv: the latest version
platform: linux

### Reproduction steps

./bootstrap.py configure
./waf configure

### Expected behavior

configure OK

### Actual behavior

Checking for FFmpeg/Libav present                                         : no ('libavcodec' not found) 
FFmpeg/Libav development files not found.

configure FAILED

### Log file

Checking for FFmpeg/Libav present                                         : no ('libavcodec' not found) 
FFmpeg/Libav development files not found.

### Others

I tried "LD_LIBRARY_PATH=-L~/local/lib ./waf configure " and some other ways, but they all not worked.
For some reason, I don't want to installed FFmpeg in my system dir, can I build mpv with local FFmpeg?

**Comment by qyot27** [comment]
`PKG_CONFIG_PATH=~/.local/lib/pkgconfig [regular waf configuration]`

**Comment by Deshdeepak1** [comment]
I am getting this error while doing so

/home/deshdeepak/mpv/build/mpv: error while loading shared libraries: libpostproc.so.57: cannot open shared object file: No such file or directory

I did
```bash
export PKG_CONFIG_PATH=/home/deshdeepak/ffmpeg-n6.1/lib/pkgconfig
meson setup build
meson compile -C build
```

```bash
[deshdeepak@archlinux mpv]$ ls ~/ffmpeg-n6.1/lib/
libavcodec.so            libavformat.so            libswresample.so
libavcodec.so.60         libavformat.so.60         libswresample.so.4
libavcodec.so.60.31.102  libavformat.so.60.16.100  libswresample.so.4.12.100
libavdevice.so           libavutil.so              libswscale.so
libavdevice.so.60        libavutil.so.58           libswscale.so.7
libavdevice.so.60.3.100  libavutil.so.58.29.100    libswscale.so.7.5.100
libavfilter.so           libpostproc.so            pkgconfig
libavfilter.so.9         libpostproc.so.57
libavfilter.so.9.12.100  libpostproc.so.57.3.100
````

**Comment by qyot27** [comment]
You don't have `~/ffmpeg-n6.1/lib` in your `LD_LIBRARY_PATH`, which needs to be set every single time mpv runs, since you didn't install FFmpeg to an area that the system would automatically pick it up from.

Maybe abuse rpath when building, but I have no idea if meson lets you do that.

**Comment by Deshdeepak1** [comment]
Thanks. That works, mpv plays. But it doesn't work under proxychains (gets stuck). 

My main reason to use another ffmpeg , is that my os (arch linux) official ffmpeg get stuck, when trying to  when run under proxychains , while commands like curl , wget, etc works quite well. 

So commands like`proxychains ffplay https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4`  get stuck .  And so did mpv.

But the static build of ffmpeg works quite well. I used this to build the mpv , but mpv still get stuck.


- ffplay
![image](https://github.com/mpv-player/mpv/assets/36617998/44f347f3-d1a5-4cd2-95cb-3d25c792dbdd)

- ffplay with proxychains
![image](https://github.com/mpv-player/mpv/assets/36617998/03737752-ea58-4736-95f8-ba8b4124dc71)

- mpv
![image](https://github.com/mpv-player/mpv/assets/36617998/fa482897-e059-4282-9366-dbdb9622cb97)

- mpv with proxychains 
![image](https://github.com/mpv-player/mpv/assets/36617998/8f7978fe-0fa4-4d9b-b000-63009b8cab3f)
