### ISSUE TITLE
MPV Failed to initialize decoder for codec HEVC (Opensuse Leap 15.4)

### ISSUE THREAD

**Issue by MetaStazz** [mpv-player/mpv#10408]
### Important Information

Provide following Information:
mpv 0.34.1+git.20220203T182214.5d31c7310c (built on Jun  7 2022)
MPV from opensuse:multimedia Repo
FFmpeg library versions:
libavutil       56.70.100
libavcodec      58.134.100
libavformat     58.76.100
libswscale      5.9.100
libavfilter     7.110.100
libswresample   3.9.100
FFmpeg version: 4.4.2

Opensuse 15.4 (64bits), KDE 5.90, Plasma 5.24.4
Kernel 5.14.21-150400.22-default
Mesa Intel(R) HD Graphics 630 (KBL GT2)
OpenGL ES 3.2 - Mesa 21.2.4
X.Org 1.20.3 driver i915 intel

### Reproduction steps

Open a video from folder (with my config), Crash...
Open video from command line (with my config), Crash...
Open video from command line (with --no-config), Crash...

### Expected behavior
Playing video...(like on Leap 15.3)

### Actual behavior
Crash !!! Not playing any video (mp4, avi, mkv)...
Error: Failed to initialize a decoder for codec 'hevc'.

### Log file
From command : `mpv --no-config --log-file=mpv_sucks.log ~/Videos/MPVtest.mkv`
The video is a MPEG-H Part2/HEVC (H.265), Opus, 1980p. (working in Kodi and VLC)

[mpv_sucks.log](https://github.com/mpv-player/mpv/files/9091171/mpv_sucks.log)

**Comment by MetaStazz** [comment]
HA shit sorry I just resolved it !!!
I downgraded ffmpeg 4.4.2 from opensuse:multimedia:libs to 4.4 from Packman and now it work !!

**Comment by ZaquL** [comment]
> ffmpeg 4.4.2 from opensuse:multimedia:libs to 4.4

The current version is already 5.1.
