### ISSUE TITLE
How to alleviate color banding in a video?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#10401]
For instance Futurama (Amazon source, S02E07 pictured) clearly suffers from color banding:

![mpv-shot0016](https://user-images.githubusercontent.com/14923168/178217570-d99bd4ef-150a-43d7-b7a1-094de1021830.png)

Is there a on-demand toggle to make the banding less obvious, similar to what [the Reshade's deband shader](https://github.com/crosire/reshade-shaders/blob/slim/Shaders/Deband.fx) (a Windows program for computer games) can achieve?

I don't see anything related  [in the manual](https://mpv.io/manual/stable/).

**Comment by 07416** [comment]
> https://mpv.io/manual/stable/#options-deband. Isn't that it?

I've been under the impression that the setting is enabled by default (and I'm not certain how it functions) — so it seems after running `mpvv --deband <file-path>`:

![mpv-shot0017](https://user-images.githubusercontent.com/14923168/178226237-66f930c8-27c0-4b14-9ead-e4f57ebbeba5.png)

Sorry for missing the configuration settings, I'll try changing and will compare screenshots.

**Comment by haasn** [comment]
Note also `--dither-depth=auto`, which you probably want to be using in addition to debanding.
