### ISSUE TITLE
Profile Doesn't Work

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#10403]
### Important Information

Provide following Information:
- mpv version: Latest
- macOS Version: Latest
- Source of the mpv binary or bundle: mpv.io
- If known which version of mpv introduced the problem: This one
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

`[SD Video Upscale]
profile-desc=Upscales DVD or otherwise SD sources using the best available luma and chroma upscalers
profile-cond=(get('height', math.huge) < 720) and (get('estimated-frame-count', math.huge) > 1)
profile-restore=copy
glsl-shaders-clr
glsl-shaders-append="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl" `

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
Profile only works with SD sub-720p video.

### Actual behavior
Profile works all the time.

### Log file
https://pastebin.com/raw/uJrRDfGu
In the case of a crash please provide the macOS Crash Report (Backtrace).

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by christoph-heinrich** [comment]
I couldn't get the frame count to work, but other than that, this should work:

```
[SD Video Upscale]
profile-desc=Upscales DVD or otherwise SD sources using the best available luma and chroma upscalers
profile-cond=height < 720
profile-restore=copy
glsl-shaders-append="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl"
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
```

**Comment by thebombzen** [comment]
> `profile-desc=Upscales DVD or otherwise SD sources`
What did you expect to happen
