### ISSUE TITLE
Subtitles not rendering with libass

### ISSUE THREAD

**Issue by bl4ckb0ne** [mpv-player/mpv#10413]
### Important Information

Provide following Information:
- mpv version : `0.34.1`
- Linux Distribution and Version: AlpineLinux edge
- Source of the mpv binary: https://pkgs.alpinelinux.org/package/edge/community/x86_64/mpv
- Window Manager and version: `sway 1.7`
- GPU driver and version: `AMD RADV POLARIS10` with `mesa-21.3.9`

### Reproduction steps

I open the file on mpv using the command line, subs track is detected and the video is playing without any issue. Subs are forced but are not renderer, toggling them off and on again does nothing.

```
$ mpv redacted.mkv 
 (+) Video --vid=1 (*) (hevc 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (eac3 6ch 48000Hz)
 (+) Subs  --sid=1 --slang=eng (*) (f) 'English [Forced]' (ass)
AO: [alsa] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p10
AV: 00:00:42 / 01:02:00 (1%) A-V: -0.000
```

### Expected behavior

Subtitles should be rendering

### Actual behavior

Subtitles are not rendering, no errors message available

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/9105438/log.txt)

### Sample files

File has a size of 605M, can provide upon request

**Comment by thebombzen** [comment]
Can you reproduce this with `--no-config` and truncate the sample to a size of, say 10M, and still reproduce the issue?

**Comment by bl4ckb0ne** [comment]
I made a sample with the following commande `ffmpeg -ss 00:00:00 -i input.mkv -c copy -t 00:2:00 sample.mkv` which weights 25M, the issue is still present with `--no-config` on both the original and the sample.

**Comment by thebombzen** [comment]
Can you upload the sample?

**Comment by bl4ckb0ne** [comment]
There you go https://a.uguu.se/ZBVMyspX.mkv
The file will expire in 48h, let me know if you missed it.

**Comment by thebombzen** [comment]
The subtitle track in the video has no dialogue lines, so of course none will display.

**Comment by bl4ckb0ne** [comment]
Havent thought about checking the sub file, thanks for your time :)
