### ISSUE TITLE
Any way to undo scaling that is encoded into the video? debilinear & debicubic

### ISSUE THREAD

**Issue by lextra2** [mpv-player/mpv#10418]
I want to undo bilinear upscaling that has been encoded into a video.
De-bilinear down to 1280x720 and then let `scale=spline36` do the rest.
Would be useful for older animes.

[Something like this](https://github.com/Irrational-Encoding-Wizardry/descale) is what I'm talking about.

**Comment by snylonue** [comment]
mpv supports vapoursynth as a [filter](https://mpv.io/manual/master/#video-filters-vapoursynth)
Or you can write a [shader](https://mpv.io/manual/master/#options-glsl-shaders), which can be easier to use in my opinion.

**Comment by hooke007** [comment]
`vf=scale=w=1280:h=720:flags=bilinear`

**Comment by Akemi** [comment]
> vf=scale=w=1280:h=720:flags=bilinear

that's not descaling or debilinear but just scaling down. it doesn't use the inverse kernel.

**Comment by Dudemanguy** [comment]
Old but mpv is not really the right tool for this. I guess you could theoretically use a shader or a vapoursynth filter, but I would suggest not involving mpv at all for this.
