### ISSUE TITLE
Proper name syntax for --vulkan-device

### ISSUE THREAD

**Issue by joonpark72** [mpv-player/mpv#10411]
Hello, I am trying to use vulkan as --gpu-api and specify a specific iGPU in --vulkan-device but cannot figure out how to provide the name in a proper syntax.  These are my devices on my PC: https://imgur.com/a/LHTi3hU.  How should I phrase the name so MPV will know to use Intel iGPU?  Thank you for your help.

**Comment by haasn** [comment]
From that image, it should be `--vulkan-device='Intel(R) UHD Graphics 630'`.

**Comment by joonpark72** [comment]
Thanks for the reply.   However, I have already tried that permutation and getting an error.  Please take a look: https://imgur.com/4ONoE06.

**Comment by haasn** [comment]
Uhh, try with double quotes `"` maybe? Weird shell if it doesn't accept `'`...
