### ISSUE TITLE
osc-scalewindowed & osc-scalefullscreen do not take effect when playing audio files

### ISSUE THREAD

**Issue by xiakele** [mpv-player/mpv#10423]
### Important Information
Provide following Information:
- mpv version `0.34.1`
- Linux Distribution and Version `Archlinux 5.18.12-arch1-1`
- Source of the mpv binary `via pacman`
- Window Manager and version  `kwin_x11 5.25.3`
- Possible screenshot or video of visual glitches
![video](https://user-images.githubusercontent.com/68417688/179364914-b8caca8f-4936-4159-9e7a-f9faa0df2826.png)
![audio](https://user-images.githubusercontent.com/68417688/179364916-fb95ff59-f2e6-4aa4-af6d-4983fd2bd3c4.png)
(both windows are at the same size)
### Reproduction steps
1. create ~/.config/mpv/script-opts/osc.conf
2. add the following config:
   - `vidscale=no`
   - `scalewindowed=0.5`
   - `scalefullscreen=0.5`

### Expected behavior
osc scaling is set to 0.5 when playing either audio or video files

### Actual behavior
- osc scaling is set to 0.5 when playing video files 
- the scaling does not change when playing audio files

### Log file
video: `https://0x0.st/o13A.log`
audio: `https://0x0.st/o13m.log`

**Comment by dexeonify** [comment]
Use `scaleforcedwindow` to change the scale of the OSC on a force window. In this case, audio files.

**Comment by xiakele** [comment]
> Use `scaleforcedwindow` to change the scale of the OSC on a force window. In this case, audio files.

Thanks, it did work!
So does it mean that mpv is "forced" to create a window when playing audio files, and there's no chance that I can adjust the scale respectively? (I'm new to mpv)

**Comment by dexeonify** [comment]
> So does it mean that mpv is "forced" to create a window when playing audio files

Yes, by default mpv does not create a window if you play audio files. You can test it out by typing `mpv <your_music_file>` in your terminal. If you open mpv through the file manager (or any other means listed in the following docs), it will start in a [Pseudo GUI mode](https://mpv.io/manual/master/#pseudo-gui-mode).

> there's no chance that I can adjust the scale respectively?

Not sure if I understand, didn't the option worked?

**Comment by xiakele** [comment]
> Yes, by default mpv does not create a window if you play audio files. You can test it out by typing `mpv <your_music_file>` in your terminal. If you open mpv through the file manager (or any other means listed in the following docs), it will start in a [Pseudo GUI mode](https://mpv.io/manual/master/#pseudo-gui-mode).

Thanks for the explanation!

> Not sure if I understand, didn't the option worked?

I'm just wondering if I can separately adjust the osc scale for windowed and fullscreen when playing audio files. Sorry for the confusion.

**Comment by dexeonify** [comment]
> I'm just wondering if I can separately adjust the osc scale for windowed and fullscreen when playing audio files. Sorry for the confusion.

Just did a quick test, I don't believe you can. It seems that audio files (or any forced window) only follows the value of `scaleforcedwindow` regardless of the other options.

**Comment by xiakele** [comment]
> It seems that audio files (or any forced window) only follows the value of `scaleforcedwindow` regardless of the other options.

OK, I understand it fully now. Thanks again for replying! Closing this issue.
