### ISSUE TITLE
--hwdec=nvdec causes floating point exception (nvdec-copy works)

### ISSUE THREAD

**Issue by m00nwtchr** [mpv-player/mpv#10429]
### Important Information

- mpv 0.34.1-dirty
- Arch Linux
- https://archlinux.org/packages/community/x86_64/mpv/
- dwl (https://github.com/djpohly/dwl)
- NVIDIA proprietary 515.57

### Reproduction steps

```
mpv "https://www.youtube.com/watch?v=YQHsXMglC9A" --hwdec=nvdec --no-config
```

### Expected behavior
The video plays.

### Actual behavior

> floating point exception (core dumped)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/9129408/output.txt)

**Comment by philipl** [comment]
You should use master rather than 0.34.1. The log ends when loading the vaapi-on-nvdec driver and that doesn't work with 0.34.1 and is likely the source of your problem. Worst case, master has better logging.

**Comment by m00nwtchr** [comment]
Ah, yeah looks like on master it works.
