### ISSUE TITLE
Can MPV-android decode Dolby Vision BL+EL+RPU and passthrough to TV?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#10430]
MPV on PC seems to be able to decode DV BL+EL+RPU, how about Android?

**Comment by quietvoid** [comment]
Should be at https://github.com/mpv-android/mpv-android

I don't think it even supports HDR10 passthrough at the moment.

**Comment by ZaquL** [comment]
>EL

Nope, it cannot do it yet, FEL for sure. What?

**Comment by ZaquL** [comment]
That is now possible with https://github.com/erazortt/DoViBaker

FEL is chroma siting and otherwise aligned, so better than FEL repo of @quietvoid
