### ISSUE TITLE
How can I `Show file in Finder` from the mpv?

### ISSUE THREAD

**Issue by avatar-lavventura** [mpv-player/mpv#10446]
I have many videos that are playing in a playlist and all are shuffled. 

From the opened video in `mpv` is it possible to, open it from the `Show in Finder` or find the file's full path?

**Comment by Akemi** [comment]
you can get the path via script and the `path` property (https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst) for example.

**Comment by avatar-lavventura** [comment]
Will the path of the new video printed out when I open next video in the playlist?

**Comment by Akemi** [comment]
i am not sure what you mean. you can basically do anything with a script.

**Comment by avatar-lavventura** [comment]
How this is related with the script when I press `>>` button on the gui?
