### ISSUE TITLE
drop-frames increase when rendering ASS with `display-resample`

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#10447]
### Important Information

Provide following Information:
- mpv version
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20220724
- Windows Version
win11 release
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20220724
- If known which version of mpv introduced the problem
N/A
- Possible screenshot or video of visual glitches

### Reproduction steps

1. start mpv with `--video-sync display-resample`
2. play a video and load the subtitle(with crazy effects)

### Expected behavior

less drop frames if possible (`video-sync=audio`)
![Snipaste_2022-07-24_18-26-32](https://user-images.githubusercontent.com/41094733/180658983-40cb6f3d-fa21-41cd-8513-db875a25266f.jpg)

### Actual behavior

drop frames increased dramatically(`video-sync=display-resample`)
![Snipaste_2022-07-24_18-25-39](https://user-images.githubusercontent.com/41094733/180659003-63bfb3d3-d855-4765-b796-86d3027cc560.jpg)

### Log file

[mpv-test(audio).log](https://github.com/mpv-player/mpv/files/9176286/mpv-test.audio.log)
[mpv-test(display-resample).log](https://github.com/mpv-player/mpv/files/9176287/mpv-test.display-resample.log)

### Sample files

[ultra_sub.zip](https://github.com/mpv-player/mpv/files/9176271/ultra_sub.zip)

**Comment by Dudemanguy** [comment]
Just seeing this now, but this is expected I think. `display-resample` is inherently more gpu-intensive because it always redraws on every vblank. So if you give mpv heavy options (like loading the subtitle file), then it will start dropping frames faster than on the default `--video-sync=audio` which is considerably less taxing.

**Comment by hooke007** [comment]
Agreed but I comparing with the similar(maybe) config in madvr(smoothmotion) with libass-ported xysubfilter sub-renderer. It barely loses frames. Not sure if https://github.com/mpv-player/mpv/issues/10690 would improve this issue.

**Comment by Dudemanguy** [comment]
Ah yeah then that would be just a performance optimization thing in general. I think the main difference is that interpolation (smoothmotion) in madvr doesn't require drawing on every vblank like mpv does hence the performance difference.
