### ISSUE TITLE
Play all videos on YouTube Subscriptions

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#10448]
I use YouTube a lot, and to this day every time I want to see a video I go to https://www.youtube.com/feed/subscriptions and manually drag and drop each video one by one.
Is there any other way, easier way, to watch all videos on my subscriptions?

**Comment by guidocella** [comment]
You can use a terminal youtube client like https://github.com/trizen/youtube-viewer

**Comment by garoto** [comment]
`$ mpv --ytdl-raw-options=cookies=cookies_all_20220724164642.txt ytdl://:ytsubs`

**Comment by guidocella** [comment]
yt-dlp has also `--cookies-from-browser BROWSER` so you don't have to extract them.

**Comment by Obegg** [comment]
> You can use a terminal youtube client like https://github.com/trizen/youtube-viewer

I use Windows.

> yt-dlp has also `--cookies-from-browser BROWSER` so you don't have to extract them.

`yt-dlp --cookies-from-browser firefox`
I got
`[Cookies] Extracting cookies from firefox`
`[Cookies] Extracted 590 cookies from firefox`

Now what do I do from here? How did it help my issue?
How can I play all my subscriptions?

**Comment by guidocella** [comment]
See garoto's comment.

**Comment by Obegg** [comment]
Ok, so I got it to work.
I added this line to my `mpv.conf`:
`ytdl-raw-options=cookies-from-browser=firefox`
and I now use the command `mpv ytdl://:ytsubs`.

Problem now is that it takes very long time to load, I'm not sure why, but if I have to guess it's because there's a lot of videos on the playlist.
What can be done to fix that?

**Comment by guidocella** [comment]
You can try `ytdl-raw-options=playlist-end=20`

**Comment by Obegg** [comment]
Thank you!
Issue solved by adding to `mpv.conf` the following line:
`ytdl-raw-options=cookies-from-browser=firefox,playlist-end=100`
and I use `mpv ytdl://:ytsubs` from `cmd`.
