### ISSUE TITLE
Open Containing Folder

### ISSUE THREAD

**Issue by blueray453** [mpv-player/mpv#10459]
I have a keybinding like 

    p run "/bin/sh" "-c" "xdg-open \"$(dirname \"$(echo '{ \"command\": [\"get_property\", \"path\"] }' | socat - /tmp/mpv-socket | jq -r \".data\")\")\""

I use it to open the directory of the running file in default file explorer.

Am I over complicating, or is there any simpler way.

One more thing, i am using osc. Does it have a right click (context menu). I want to add this command to a context menu. Will it be possible?

[output.txt](https://github.com/mpv-player/mpv/files/9209832/output.txt)
,

**Comment by guidocella** [comment]
`p run sh -c 'xdg-open "$(dirname "$0")"' ${path}`

There is no context menu by default, but there are scripts to add one in the wiki.

**Comment by blueray453** [comment]
> `p run sh -c 'xdg-open "$(dirname "$0")"' ${path}`

Can you please check the command. It is not doing anything.

**Comment by guidocella** [comment]
Your mpv is too old to support single quotes in input.conf, use double quotes and escape the nested double quotes.

**Comment by blueray453** [comment]
What is `${path}` here? Is it the `["get_property", "path"]` or is it something else? Where is the documentation for these variables?

**Comment by blueray453** [comment]
The bellow code works:

    p run sh -c "xdg-open \"$(dirname \"$0\")\"" ${path}

Thank you very much.

**Comment by guidocella** [comment]
https://mpv.io/manual/master/#property-expansion
