### ISSUE TITLE
HDR Android tablet MPV

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#10457]
### Important Information
Hi there I am trying to get hdr videos working on my tablet in full hdr as the screen supports hdr 10 however when I add lines to my config such as - - target prim by.2020 and I change the output and trc to PQ everything gets washed out can someone please help me I’m very new to mpv 
Provide following Information:
- mpv version
- Platform and Version
- Source of the mpv binary

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by philipl** [comment]
You should file an issue in the https://github.com/mpv-android/mpv-android/ project.
