### ISSUE TITLE
Two URL at the same time

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#10454]
I was trying to play two internet videos at the same time using **--lavfi-complex** but I see that **--external-file=** rejects URLs, it says:
_Can not open external file https://www.youtube.com/..._
_Pad vid2 is not connected to anything._

Any idea to resolve this or is it not possible to do it?

**Comment by guidocella** [comment]
`--external-file=$(yt-dlp -f best -g https://www.youtube.com/...)`

**Comment by jimmy-1000** [comment]
> `--external-file=$(yt-dlp -f best -g https://www.youtube.com/...)`

Thanks but sadly doesn't work. I'm using Windows.

**Comment by snylonue** [comment]
> > `--external-file=$(yt-dlp -f best -g https://www.youtube.com/...)`
> 
> Thanks but sadly doesn't work. I'm using Windows.

Powershell supports such syntax.

**Comment by jimmy-1000** [comment]
> > > `--external-file=$(yt-dlp -f best -g https://www.youtube.com/...)`
> > 
> > 
> > Thanks but sadly doesn't work. I'm using Windows.
> 
> Powershell supports such syntax.

I did tests with Powershell 6.0 but not working.
