### ISSUE TITLE
Use shaders on everything in a certain folder on Linux

### ISSUE THREAD

**Issue by jaredreardon** [mpv-player/mpv#10450]
Pretty much as the title says, I've been trying to get a setup that works well with Anime4K shaders. I got them working properly and now I'm trying to get a setup where they automatically apply to everything in my anime folder on my Linux machine (so it'd be /home/user/videos/anime) and I can't seem to get it working to where the shaders automatically apply to videos in that folder or subfolders of the anime folder.

I found this online, which solved this for someone else, but this solution hasn't been working on my end:

```
[Anime4k]
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('Anime') ~= nil
profile-restore=copy
glsl-shaders="~~/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl;~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl;~~/shaders/Anime4K_Upscale_DTD_x2.glsl;~~/shaders/Anime4K_RA_CNN_M.glsl"
```

Anyone have any advice? I'm kinda lost on this and would greatly appreciate any help anyone would care to offer!

**Comment by guidocella** [comment]
Replace `match('Anime')` with `match('anime')`.

**Comment by jaredreardon** [comment]
> Replace `match('Anime')` with `match('anime')`.

I just tried that and am having the same issue, unfortunately.

**Comment by guidocella** [comment]
Replace every `;` in `glsl-shaders` with `:` (`;` is  the separator for Windows).

**Comment by jaredreardon** [comment]
> Replace every `;` in `glsl-shaders` with `:` (`;` is the separator for Windows).

If you had given me 1000 guesses I probably never would have figured out that this was all my issue was. Thank you very much for the help, works like a charm!
