### ISSUE TITLE
Full hdr

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#10458]
### Important Information
Hi I was wondering how to get full hdr on mpv without the use of tone mapping I am very new and have tried lots of different things including setting the output and target to pq and setting the target prim to bt.2020 however when I apply these settings the picture gets washed out need help 
Provide following Information:
- mpv version
- Platform and Version
- Source of the mpv binary

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by quietvoid** [comment]
You didn't provide any info from the issue template, we don't know what your OS is.

**Comment by Jamie666123** [comment]
My operations system is Android tablet  I was told by someone else to put it in Android mpv thread but no one has replied on there 

> You didn't provide any info from the issue template, we don't know what your OS is.

**Comment by Jamie666123** [comment]
The screen is capable of displaying hdr10

**Comment by quietvoid** [comment]
It is a `mpv-android` issue, there's no HDR passthrough support at the moment.

**Comment by Jamie666123** [comment]
> It is a `mpv-android` issue, there's no HDR passthrough support at the moment.

Do you know of any video players which do on a android tablet already tried the main ones like Vlc

**Comment by quietvoid** [comment]
ExoPlayer based apps like [Just](https://github.com/moneytoo/Player) might work.

**Comment by Jamie666123** [comment]
> ExoPlayer based apps like [Just (Video) Player](https://github.com/moneytoo/Player) might work.

Tried this player already any other exo players you know of if you c

**Comment by Jamie666123** [comment]
Could give me a list it

**Comment by Jamie666123** [comment]
Would really help
