### ISSUE TITLE
please look into youtube video playback

### ISSUE THREAD

**Issue by Sundal** [mpv-player/mpv#1046]
Can you guys take a look at youtube video playback feature, it started to work badly or not at all lately.

I get errors like:
   [ffmpeg] tls: Error in the push function.
   Failed to open https://www.youtube.com/watch?v=***********.

if i replace https with http i get errors like:
   [cache] Connection lost! Attempting to reconnect (1)...
   [ffmpeg] tls: Error in the push function.
   [cache] Connection lost! Attempting to reconnect (2)...
   [ffmpeg] tls: Error in the push function.
   [cache] Connection lost! Attempting to reconnect (3)...
   [ffmpeg] tls: Error in the push function.
   [cache] Connection lost! Attempting to reconnect (4)...
   [cache] Connection lost! Attempting to reconnect (5)...
   [cache] !!! read_filepos differs !!! report this bug...
   [cache] !!! read_filepos differs !!! report this bug...
   [cache] !!! read_filepos differs !!! report this bug...
   [cache] !!! read_filepos differs !!! report this bug...
   [cache] !!! read_filepos differs !!! report this bug...
   [cache] !!! read_filepos differs !!! report this bug...
   [cache] !!! read_filepos differs !!! report this bug...
   Failed to recognize file format.
or
   [ffmpeg] tls: Error in the push function. most of the time

I also got the latest version: mpv -version
   mpv git-dad90f6 (C) 2000-2014 mpv/MPlayer/mplayer2 projects
    built on 2014-08-27T19:30:57
   ffmpeg library versions:
      libavutil       54.7.100
      libavcodec      56.0.101
      libavformat     56.3.100
      libswscale      3.0.100
      libavfilter     5.0.103
      libavresample   2.1.0

I can view video on the site without issues and sometimes it plays in mpv too but without any cache it behaves erratic. This feature used to work wonderfully a while back with caching and everything.

**Comment by wm4** [comment]
This has been implemented ages ago.
