### ISSUE TITLE
How to load cache for a complete youtube video?

### ISSUE THREAD

**Issue by Akhilesh-T** [mpv-player/mpv#10466]
While streaming a youtube video, the cache loads only about 5mins. Is there any way to load it like 20mins?

I have put the following two commands in _mpv.conf_, but with no success
```
cache = yes
cache-secs = 1200
```

**Comment by guidocella** [comment]
Increase `demuxer-max-bytes`.

**Comment by Akhilesh-T** [comment]
Thanks for your reply. I don't know the default value. How much should I set it?

**Comment by guidocella** [comment]
The default is 150MiB, you can see it with `mpv --h=demuxer-max-bytes`. You can increase it as much as you like as long there's enough memory for other processes.

**Comment by Akhilesh-T** [comment]
I set it to 1GiB and now it's working as intended. Thanks a lot.

**Comment by Kubra2003** [comment]
How can I'll cache a deleted YouTube video after deletion?
