### ISSUE TITLE
Is there any way to display the onscreen controller when moving the cursor over the entire window/screen area

### ISSUE THREAD

**Issue by SerggIvanenko** [mpv-player/mpv#10476]
This is not a feature request or a bug report, but rather a question that I couldn't find an answer to, is it possible to show the On Screen Controller even when moving the cursor at the top of the window/screen, the On Screen Controller is only displayed when the cursor is moving at the bottom of the window with a border somewhere in the middle. On the screenshot, I tried to visually represent the question. I will be grateful for the answer.

![11](https://user-images.githubusercontent.com/108337138/182204384-5a0c00a1-420e-4e00-bfff-0a8f91e5fd8c.png)

**Comment by CounterPillow** [comment]
`--script-opts=osc-deadzonesize=0`

See https://mpv.io/manual/master/#on-screen-controller

**Comment by SerggIvanenko** [comment]
> `--script-opts=osc-deadzonesize=0`
> 
> See https://mpv.io/manual/master/#on-screen-controller

Perfectly. It magnificently worked. Thank you very much for your reply.
