### ISSUE TITLE
Sub-Pos Doesn't Work As Intended

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#10479]
### Important Information

Provide following Information:
- mpv version: latest
- macOS Version: 12.4
- Source of the mpv binary or bundle: mpv.io
- If known which version of mpv introduced the problem: this one
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
sub-pos only affects srt sub with no styling or when sub-ass-override is seto to force. only sub-ass-pos should affect ass subtitles

### Actual behavior
All subs are affected. There's also no way to restore the placement that's in the ass settings. Removing the line puts them at the bottom of the frame. I want it to only work for srt subs or when sub-ass-override=force is enabled, like sub-font.

### Log file

https://pastebin.com/ybY6QJNU

**Comment by hooke007** [comment]
It's already in the doc
https://mpv.io/manual/master/#options-sub-pos
```
Warning

Text subtitles (as opposed to image subtitles) may be cut off if the value of the option is above 100. This is a libass restriction.

This affects ASS subtitles as well, and may lead to incorrect subtitle rendering in addition to the problem above.

Using can achieve this in a better way.--sub-margin-y
```

**Comment by george-emerald** [comment]
So, how do I make it so that the ass subs are rendered nromally and only the srt subs are affected? sub-margin-y? How do I use that?

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#options-sub-margin-y
I don't understand, is there anything unclear in the doc?

**Comment by george-emerald** [comment]
But it says if I wanna raise the subtitles I should use sub-pos. I just want my ass subs to be rendered according to their own styling. If I remove sub-pos now, they're all rendered at the bottom of the screen.

**Comment by hooke007** [comment]
So use it. `--sub-margin-y`

**Comment by george-emerald** [comment]
The problem is that removing sub-pos places all subs at the bottom of the screen.

**Comment by hooke007** [comment]
Do you really tried? why not set a huge value to make it top? `sub-margin-y=600`

**Comment by hooke007** [comment]
> the ass subs are rendered nromally and only the srt subs are affected

From your previous comment, `sub-margin-y` is the answer.

>  removing sub-pos places all subs at the bottom of the screen.

Is there any issue here? ASS's rendering follow the ass file's `script info`, which works properly.
