### ISSUE TITLE
App not loading mp4 fully while watching

### ISSUE THREAD

**Issue by kitkatz2000** [mpv-player/mpv#10472]
Hello! I have been trying to watch an mp4 on MPV and it keeps freezing every few seconds while I'm trying to watch it. I have had this issue before where the mp4 will pause, but it usually comes back to the proper work flow afterwards. it seems to pause every 3-4 seconds and I have tried some of the other tactics that were recommended on this website but none of them seem to work(?) if anyone has any advice for this it would be greatly appreciated, thank you!

Provide following Information:
- mpv-latest.tar.gz
- macOS Monterey version 12.4
- Source of the mpv binary or bundle
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

Reproduction steps:
-  /Applications/mpv.app/Contents/MacOS/mpv --no-config --log-file=mpv.log /Volumes/ShotDeck\ 1/Inside\ Out/Inside\ Out\ \(2015\).mkv 

Expected behavior:
- smooth playback running from frame to frame with no glitches

Actual behavior:
- pausing every few seconds
- having to download the video file in random bursts from hard drive

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/9231107/mpv.log)
(Log for mpv file, opened app twice)

**Comment by CounterPillow** [comment]
mpv assumes that local files can be read quickly enough. If this is not the case for you, explicitly set `cache=yes` in your config and the caching mechanism will be activated

**Comment by kitkatz2000** [comment]
how do i change this setting in my mpv app?

**Comment by kitkatz2000** [comment]
update: it was the hard drive that was causing the issues, thank you for your help though I really appreciate it!
