### ISSUE TITLE
Hdr support 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#10487]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file

Hi was just wondering and just a quick question if there are any app versions of mpv player anywhere third party or whatever which support hdr passthrough and full hdr support

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by daddy-cool** [comment]
for Windows this works out of the box when you setup mpv like this:
```
target-colorspace-hint
vo = gpu-next
gpu-api = vulkan
```

**Comment by mdannp** [comment]
> target-colorspace-hint
> vo=gpu-next
> gpu-api=vulkan
> hwdec=auto-safe

works the same way on Win10
