### ISSUE TITLE
How do I reduce subtitle canvas size?

### ISSUE THREAD

**Issue by bpsib** [mpv-player/mpv#10486]
How can I reduce the size of the canvas the subtitles appear on so they don't obstruct information? This is a big problem when watching BBC sport from Freeview. They get in the way of the scoring and time information and can't move them down. They also get in the way of editor names on the news unless I move them up.
![mpv-shot0002](https://user-images.githubusercontent.com/5899155/182895014-da66c3a6-1b43-4b34-adc5-bb5c7e57f647.jpg)
I have tried reducing the size using the `sub-scale` option but that doesn't work properly. The end up looking like this:
![mpv-shot0005](https://user-images.githubusercontent.com/5899155/182895435-ad44e818-febe-49aa-a0f6-5ee6b513983d.jpg)

**Comment by thebombzen** [comment]
Does using `--sub-pos` fix the problem, or `--sub-margin-y`?

**Comment by bpsib** [comment]
> Does using `--sub-pos` fix the problem, or `--sub-margin-y`?

Makes no difference.

**Comment by thebombzen** [comment]
What about `--sub-pos`?

**Comment by bpsib** [comment]
I rather have the canvas shrunk just like what TV's do than them just moved. I take it that mpv doesn't have such an option. Is it possible at all using ffmpeg's filters? I know mpv supports ffmpeg's audio and video filters but does it support subtitle filters?

**Comment by thebombzen** [comment]
Try using `--filter-complex` with `sub2video` and see if you can get something out of that. Do note that `sub2video` and `overlay` is much slower in software than doing so in hardware.

**Comment by bpsib** [comment]
> Try using `--filter-complex` with `sub2video` and see if you can get something out of that. Do note that `sub2video` and `overlay` is much slower in software than doing so in hardware.

I have no idea how to go about doing that. Can someone help such as providing an example?
