### ISSUE TITLE
Cannot use mpv in X if a Wayland compositor is running in another VT.

### ISSUE THREAD

**Issue by lovelacehq** [mpv-player/mpv#1048]
I was testing out mpv in Weston on another VT, which worked wonderfully. I CTRL+ALT+F1'd back to X and tried to play mpv there for a moment, while Weston was still running. I got this:

```
Playing: [Filename Redacted].mkv
[stream] Video (+) --vid=1 'H.264 720p BD' (h264)
[stream] Audio (+) --aid=1 --alang=jpn (*) 'AAC LC 2.0 200Kbps' (aac)
[stream] Subs  (+) --sid=1 --slang=eng (*) 'Styled Subtitles' (ass)
File tags:
 TITLE: [Title Redacted]
wl_drm@20: error 0: authenicate failed
[vo/opengl] OpenGL context creation failed!
Segmentation fault
```

After exiting Weston and switching back to X, mpv worked again. I guess if authentication fails, it doesn't try to use the X backend?

Also, curiously, there is a typo in that authentication error. It says "authenicate".

**Comment by nkuttler** [comment]
Woah, that was unexpected. I have the same problem on debian unstable with mpv version `0.20.0-1+b1` and weston 1.11.0-1 running. Fortunately killing the weston sesssion fixes this problem.

```
Playing: <any file>
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
wl_drm@15: error 0: authenicate failed
Segmentation fault
```
