### ISSUE TITLE
GLib-GIO-CRITICAL after sending SIGINT (flatpak installation)

### ISSUE THREAD

**Issue by pabloab** [mpv-player/mpv#10488]
### Important Information

Provide following Information:

-   ```
    flatpak run io.mpv.Mpv --version
    mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
     built on UNKNOWN
    FFmpeg library versions:
       libavutil       56.70.100
       libavcodec      58.134.100
       libavformat     58.76.100
       libswscale      5.9.100
       libavfilter     7.110.100
       libswresample   3.9.100
    FFmpeg version: 4.4
    ```
- Linux Distribution and Version: Ubuntu 20.04.4 LTS
- Source of the mpv binary: https://flathub.org/apps/details/io.mpv.Mpv
- If known which version of mpv introduced the problem
- Window Manager and version: GNOME Shell 3.36.9
- GPU driver and version: driver: nvidia v: 510.85.02

### Reproduction steps

1. Run `flatpak run io.mpv.Mpv   anyvideo.webm` (same with avi and any format I tried)
2. Press <kbd>Ctrl+C</kbd> (send SIGINT)

### Expected behavior

Just to stop.

### Actual behavior

Stops and this is sent to stdout:

```
(process:2): GLib-GIO-CRITICAL **: 18:25:10.679: g_dbus_connection_emit_signal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
(process:2): GLib-GIO-CRITICAL **: 18:25:10.685: g_dbus_connection_unregister_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
(process:2): GLib-GIO-CRITICAL **: 18:25:10.685: g_dbus_connection_unregister_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

Doesn't happen with `--no-config`. Not sure which config file should be modified. This is a fresh MPV flatpak install without any tunning.

I believe is a mpv issue and not from Flatpak because I could only reproduce it with mpv, tried first several other flatpak installed programs.

### Log file

```
[cplayer] Exiting... (Quit)

(process:2): GLib-GIO-CRITICAL **: 19:27:42.344: g_dbus_connection_emit_signal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
[ytdl_hook] Exiting...
[console] Exiting...

(process:2): GLib-GIO-CRITICAL **: 19:27:42.345: g_dbus_connection_unregister_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(process:2): GLib-GIO-CRITICAL **: 19:27:42.345: g_dbus_connection_unregister_object: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
[mpris] Exiting...
[vo/gpu/x11] Enabling screensaver.
[stats] Exiting...
[cplayer] Run command: change-list, flags=64, args=[name="shared-script-properties", operation="remove", value="osc-margins"]
[cplayer] Set property: shared-script-properties -> 1
[osc] Exiting...
[vo/gpu] flushing shader cache
[vo/gpu/x11] uninit ...
```

### Sample files

The issue happen with any file. Even with just `flatpak run io.mpv.Mpv --ytdl-format=best "https://youtu.be/jfKfPfyJRdk"`

**Comment by CounterPillow** [comment]
The flatpak probably includes either the mpris dbus script or something else that uses dbus.

mpv itself does not utilise dbus in any way, therefore you're at the wrong place here.

**Comment by pabloab** [comment]
Seems you're right about [mpris on flathub's package](https://github.com/flathub/io.mpv.Mpv/search?q=mpris). I can't reproduce the issue using the `--no-config` option, isn't that a reason to believe the solution could come from mpv side?

**Comment by CounterPillow** [comment]
No, `--no-config` disables all non-internal scripts, including the mpris script this bundles.

**Comment by pabloab** [comment]
OK, I [opened the issue there](https://github.com/flathub/io.mpv.Mpv/issues/81). Thanks!
