### ISSUE TITLE
`playlist-remove current` does not work correctly

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10491]
### Important Information

Provide following Information:
- mpv version
different old and new build from yesterday tried

- Windows Version
11

- Source of the mpv binary
shinshiro

### Reproduction steps

1. Put 3 files in playlist (mp3 or mkv)
2. Navigate to last file in playlist, this is important
3. run `playlist-remove current`

mpv process dies

config and scripts was disabled (autoload.lua script might interfere here)

Using Lua there is an issue too, here the problem happens when 2 files are in the playlist, the process does not die, but the file isn't removed from the playlist. I tried to rewrite it but couldn't get anything that works, the code seems correct.

```Lua
function playlist_remove_current()
    local count = mp.get_property_number("playlist-count")
    local pos   = mp.get_property_number("playlist-pos")
    local new_pos = 0

    if pos == count - 1 then
        new_pos = pos - 1
    else
        new_pos = pos + 1
    end

    mp.set_property_number("playlist-pos", new_pos)
    mp.command("playlist-remove " .. pos)
end

mp.add_forced_key_binding("KP0", "playlist_remove_current", playlist_remove_current)
```

**Comment by thebombzen** [comment]
>mpv process dies

can you post a log?

**Comment by stax76** [comment]
I looked at the log, and apparently it exits regularly, I was thinking the process died but missed validating that assumption.

```
[  36.560][d][cplayer] Run command: script-binding, flags=73, args=[name="console/_console_2"]
[  36.560][d][cplayer] video EOF (status=4)
[  36.560][d][cplayer] Run command: playlist-remove, flags=73, args=[index="current"]
[  36.560][v][cplayer] EOF code: 2  
[  36.560][d][ad] Uninit decoder.
[  36.560][d][ao/wasapi] Thread Reset
[  36.560][d][vd] Uninit decoder.
[  36.560][d][cplayer] Terminating demuxers...
[  36.561][d][cplayer] Done terminating demuxers.
[  36.561][v][cplayer] finished playback, success (reason 2)
[  36.561][i][cplayer] 
[  36.561][i][cplayer] Exiting... (End of file)
[  36.561][d][ytdl_hook] Exiting...
[  36.561][d][console] Exiting...
[  36.561][d][stats] Exiting...
[  36.561][d][cplayer] Run command: change-list, flags=64, args=[name="shared-script-properties", operation="remove", value="osc-margins"]
[  36.562][v][cplayer] Set property: shared-script-properties -> 1
[  36.562][d][osc] Exiting...
[  36.565][d][ao/wasapi] Uninit wasapi
[  36.565][d][ao/wasapi] Thread Reset
[  36.565][d][ao/wasapi] Thread shutdown
[  36.576][d][ao/wasapi] Thread uninit done
[  36.576][d][ao/wasapi] Thread return
[  36.576][d][ao/wasapi] Uninit wasapi done
[  36.576][d][vo/gpu] flushing shader cache
[  36.586][v][vo/gpu/win32] uninit
```
I think the script causes a bug, it happens when only 2 files are left in the playlist, the script sets the pos to 0 and removes pos 1, and that does not work.

**Comment by stax76** [comment]
I must have made a mistake while testing, Lua code works now, mpv.net has an equivalent for autoload.lua built in and that was causing the behavior, I'm sorry!😳
