### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#10492]
I get this issue trying to load a dll in my lua script. How do I solve this issue? Did anyone else have this issue? I've verified my dll is 32 bit.

This is my code
```assert( package.loadlib( "lfshostx64.dll", "luaopen_lfs" ) )```

The error I get is: %1 is not a valid Win32 application. 

I can run a dll in lua without mpv so I don't know what is the problem.

Thanks

**Comment by stax76** [comment]
Is your mpv build also 32 bit? It cannot be mixed.

**Comment by cerealXDD** [comment]
> Is your mpv build also 32 bit? It cannot be mixed.

Yes, I tested it on an mpv 32 bit by shinchiro.
