### ISSUE TITLE
Requiring a dll crashes mpv?

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#10494]
I'm trying to use luafilesystem in one of my lua scripts. My code is ```require('lfs')``` but then mpv just exits without a message and none of the code ahead even runs. Does someone know what is happening? I am using mpv 32 bit for windows.

**Comment by cerealXDD** [comment]
[lfs.zip](https://github.com/mpv-player/mpv/files/9273261/lfs.zip)
Could someone try downloading my dll and try requiring it in a random lua script to see what happens? You need to use mpv 32 bit

**Comment by avih** [comment]
You already opened one issue for this - https://github.com/mpv-player/mpv/issues/10492 please don't keep opening new issues for the exact same problem.

I'm not very familiar with lua binary modules, but If this is a lua dll, then it probably needs to be built for the exact same lua which mpv uses.

At the other issue you mentioned you use shinchiro's build, and this uses luajit (not sure which exact version), so your dll probably needs to be compatible with luajit (32, if indeed you use 32 bit mpv).

**Comment by cerealXDD** [comment]
> You already opened one issue for this - #10492 please don't keep opening new issues for the exact same problem.
> 
> I'm not very familiar with lua binary modules, but If this is a lua dll, then it probably needs to be built for the exact same lua which mpv uses.
> 
> At the other issue you mentioned you use shinchiro's build, and this uses luajit (not sure which exact version), so your dll probably needs to be compatible with luajit (32, if indeed you use 32 bit mpv).

Sorry about that. I should have included it in the same issue. Ok, so I'll try to make the binary compatible with luajit and see if that works
