### ISSUE TITLE
allow for loading a playlist from a Lua table of paths

### ISSUE THREAD

**Issue by resolritter** [mpv-player/mpv#10493]
#### Problem

The `loadlist` command only accepts a `file` as its argument

https://github.com/mpv-player/mpv/blob/37927b65f719aac817717c88c10b05ca7246248a/player/command.c#L5175-L5178

I'm building a playlist through Lua code, so I'd like to load it from a table of paths as in `{"/path/to/file", "/path/to/file2"}`, but that's not possible at the moment. My workaround is to write that table to a file (`file:write(table.concat(playlist, "\n"))`) and call `loadlist` with the file, which is inconvenient.

#### Solution

Provide a Lua API to load a playlist from a table.

**Comment by stax76** [comment]
You can use [loadfile](https://mpv.io/manual/master/#command-interface-[%3Coptions%3E]]) for each file, that's what I use in mpv.net:

```C#
if (i == 0)
    CommandV("loadfile", file);
else
    CommandV("loadfile", file, "append");
```

**Comment by avih** [comment]
It's also possible to load a playlist file as a direct string, like so:
```lua
mp.commandv("loadlist", "memory:///path/to/file1\n/path/to/file2\n...")
```
The string can be of a plain playlist, or m3u, or any other format which mpv supports.

**Comment by resolritter** [comment]
I didn't know about `memory://`! That works perfectly for my use-case, thank you!
