### ISSUE TITLE
YCCK jpeg: CMYK icc profiles using Little CMS (Fogra 39, etc)

### ISSUE THREAD

**Issue by ZaquL** [mpv-player/mpv#10509]
Feature request, not an issue, mind you.

Some samples:

[jpeg ](https://github.com/mozilla/mozjpeg/issues/31#issue-30015839) (Coated FOGRA39 (ISO 12647-2:2004))

https://upload.wikimedia.org/wikipedia/en/2/25/Channel_digital_image_CMYK_color.jpg (U.S. Web Coated (SWOP) v2)

https://newsgroup.xnview.com/download/file.php?id=2449 (Europe ISO Coated FOGRA27)

http://towerofbabel.free.fr/test/SLW_LOGO_CMYK.jpg

It is kinda obvious on gpu-next:

[vo/gpu-next] Invalid ICC profile: not RGB

**Comment by ZaquL** [comment]
Why?

**Comment by thebombzen** [comment]
You created an issue 4 days ago that ignored the issue template and then marked it yourself as having ignored the issue template. There's nothing more to be done. If you want to open an issue without ignoring the issue template then do that.

**Comment by ZaquL** [comment]
But I wanted to open as feature request. It just did not work

**Comment by haasn** [comment]
Not feasible.

**Comment by ZaquL** [comment]
Mmm, no, ffmpeg supports CMYK and even YCCK and so does Little CMS, which
is also (due to your patches) part of ffmpeg now.

**Comment by ZaquL** [comment]
Are you sure it cannot be done? https://github.com/mm2/Little-CMS/blob/9e97cac287f69bf71e35602dbfc372335679f9fa/utils/jpgicc/jpgicc.c#L666
