### ISSUE TITLE
[Question] Hiding "Volume:" text from OSD

### ISSUE THREAD

**Issue by Akhilesh-T** [mpv-player/mpv#10500]
I have already hidden the OSD bar but also want to hide the text `Volume:` so that only the numbers are visible when seeking volume.

Please let me know if there is any way to do it.

**Comment by guidocella** [comment]
Add these bindings to input.conf:

```
9 no-osd add volume -1; show-text ${volume}%
0 no-osd add volume 1; show-text ${volume}%
```

**Comment by Akhilesh-T** [comment]
This works for me. Thanks a lot.
