### ISSUE TITLE
32 audio channels for DTS-X

### ISSUE THREAD

**Issue by TheBestKmanEver** [mpv-player/mpv#10505]
i would like if you can possibly add another 16 channels for a total of 32 for use of when i am playing DTS-X content which has up to 32 available channels, yes i am aware it's overkill but i am overkill like that

**Comment by ZaquL** [comment]
Even 16 channels are impossible. 24 channels of aac too.

**Comment by TheBestKmanEver** [comment]
There's already 16 channels available and i am able to use them just fine
with HRTF

**Comment by ZaquL** [comment]
What head related transfer function are you using?

Also are you sure ffmpeg does not downscale 16 channels to 9 channels as it usually does?

Same of that file you are using would be nice, you know. I have my own though, but still.

32 channels, is that something dolby tools produce or dts tools produce?

**Comment by TheBestKmanEver** [comment]
![image](https://user-images.githubusercontent.com/35676228/184064554-ba620be6-b976-4bfe-bb4f-4599d28435ca.png)
MPV is outputting 16 channels to Pipewire which downmixes it for OpenAL to use the HRTF, also the HRTF im using is SCUT KEMAR,

**Comment by mitzsch** [comment]
Do you have the DTS-X stream decoded as 32 individual PCM substreams? If not, even if you would be able to output 32 channels, it would not work. FFmpeg has no DTSX decoder. The only way you would be able to get DTSX (inside a DTS-HD HRA or MA stream) is with audio passthrough to an AVR that supports DTSX decoding.
