### ISSUE TITLE
stats.conf not working

### ISSUE THREAD

**Issue by ahloiscreamo** [mpv-player/mpv#10503]
Hello,

I followed this line on wiki 

> This script can be customized through a config file script-opts/stats.conf placed in mpv's user directory and through the --script-opts command-line option. The configuration syntax is described in [ON SCREEN CONTROLLER](https://mpv.io/manual/stable/#on-screen-controller).

I create stats.conf and put it in .config/mpv/scripts-opts/stats.conf
stats.conf containing-
#Text style
font = "LexendDeca"
font_mono = "monospace",   -- monospaced digits are sufficient
font_size = 12,
font_color = "FFFFFF",
border_size = 3,
border_color = "242d4f",
shadow_x_offset = 0.0, 
shadow_y_offset = 0.0, 
shadow_color = "242d4f", 
alpha = "11",

i fired up mpv and nothing change, i expected the stat's font and border color to change.

- mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
- Linux artix 5.18.16-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 04 Aug 2022 18:20:10 +0000 x86_64 GNU/Linux
- Artix repo
- i3 version 4.20.1 (2021-11-03) © 2009 Michael Stapelberg and contributors

**Comment by avih** [comment]
> I followed this line on wiki
>> This script can be customized through a config file script-opts/stats.conf ...

no, you didn't:

> I create stats.conf and put it in .config/mpv/scripts-opts/stats.conf

script-opts, not scripts-opts
