### ISSUE TITLE
[Linux X11] Error opening/initializing the selected video_out (--vo) device.

### ISSUE THREAD

**Issue by acedogblast** [mpv-player/mpv#10506]
Provide following Information:
- mpv version: mpv master-git 0.34.0-399-g52aed495cb
- Linux Distribution and Version: KDE Neon 5.25
- Source of the mpv binary: local built using mpv-build script
- If known which version of mpv introduced the problem: mpv master-git 0.34.0-399-g52aed495cb is the only one I tested
- Window Manager and version: X11 version number:  11.0 - X.Org version: 1.20.13
- GPU driver and version: Mesa 21.2.6
- Possible screenshot or video of visual glitches

### Reproduction steps
Build shaderc, then libplacebo and install both.
Build mpv with [mpv-build script](https://github.com/mpv-player/mpv-build) with --enable-libdav1d for ffmpeg_options.
Open any video file.
### Expected behavior
Video player GUI opens and playes video.

### Actual behavior
No GUI comes up and error message in terminal: `[cplayer] Error opening/initializing the selected video_out (--vo) device.`
Tried using -vo=gpu instead but got this error:
 `[vo/gpu] Failed initializing any suitable GPU context!
[cplayer] Error opening/initializing the selected video_out (--vo) device.`

### Log file
[log.txt](https://0x0.st/o2ZZ.txt)

### Sample files
N/A

**Comment by acedogblast** [comment]
There does not seem to be any useful info in the log as far as I can tell. I have a working build of mpv 0.34.0-198-gbc9805c71a which is before the added dependence of libplacebo.

**Comment by thebombzen** [comment]
What happens if you use `--vo=gpu --gpu-api=opengl`?

**Comment by Dudemanguy** [comment]
99% chance you need to install libxpresent.

**Comment by acedogblast** [comment]
@thebombzen 
./mpv --vo=gpu --gpu-api=opengl test.mp4 
Error parsing option gpu-api (option parameter could not be parsed)
Setting commandline option --gpu-api=opengl failed.
Exiting... (Fatal error)

**Comment by acedogblast** [comment]
@Dudemanguy Do I have to rebuild once I installed libxpresent-dev?

**Comment by Dudemanguy** [comment]
Yes.

**Comment by acedogblast** [comment]
@Dudemanguy Thanks that fixed it.
