### ISSUE TITLE
Can I keep OSC from hiding when the mouse leaves the window?

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#10512]

**Comment by guidocella** [comment]
Del changes when the OSC is displayed.

**Comment by oltodosel** [comment]
> Del changes when the OSC is displayed.

I already set `visibility=always` in `osc.conf`. OSC still disappears.

**Comment by oltodosel** [comment]
Solved.
I had a trailing space after `visibility=always` in `osc.conf` and it caused the problem.
