### ISSUE TITLE
Load next video on playlist before current video ends?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#10516]
Is mpv able to load next video file before the current one ends?
It will make loading times shorter.

Lets say I watch YouTube and the current video ends - I need to wait a bit for mpv to load the next video.
This is the current behavior, I'm asking if there's an option to make it faster.

**Comment by guidocella** [comment]
`--prefetch-playlist`

**Comment by Obegg** [comment]
Got it, so maybe there's a lua script for that?

**Comment by thebombzen** [comment]
You'd have to write one yourself to make it work with ytdl-hook URLs.
