### ISSUE TITLE
gpu-next, libplacebo 4.208, av1 generate grain assertion failed

### ISSUE THREAD

**Issue by 24fpsDaVinci** [mpv-player/mpv#10522]
- mpv version
latest git master
- Linux Distribution and Version
fedora 36
- Source of the mpv binary
git master
- Window Manager and version
wayland
- GPU driver and version
intel XE igpu

### Reproduction steps
with gpu-next, libplacebo 4.208.0 release:
play any av1 file

### Expected behavior
play av1 file

### Actual behavior
mpv: ../src/shaders/film_grain_av1.c:312: generate_grain_y: Assertion `shift >= 0' failed.
mpv quits

issue only occurs with gpu-next, plays fine with vo=gpu

**Comment by haasn** [comment]
Can't reproduce, can you provide a stack trace and/or sample file?

In theory that assertion should only ever get hit if `data->grain_scale_shift` contains invalid values.

**Comment by 24fpsDaVinci** [comment]
> Can't reproduce, can you provide a stack trace and/or sample file?
> 
> In theory that assertion should only ever get hit if `data->grain_scale_shift` contains invalid values.

when i split the file using ffmpeg stream copy, the original error disappears but the video is now black. I tested the same command with big buck bunny and it plays correctly, so it seems the video file is the issue and something is not compatible with gpu-next. its a large file, i wish i could upload it for further inspection.

```
Writing application                      : mkvmerge v63.0.0 ('Everything') 64-bit
Writing library                          : libebml v1.4.2 + libmatroska v1.6.4 / Lavf58.76.100

Video
ID                                       : 1
Format                                   : AV1
Format/Info                              : AOMedia Video 1
Format profile                           : Main@L5.0
Codec ID                                 : V_AV1
Duration                                 : 6 min 20 s
Bit rate                                 : 4 616 kb/s
Width                                    : 3 840 pixels
Height                                   : 1 920 pixels
Display aspect ratio                     : 2.000
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.026
Stream size                              : 209 MiB (70%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
```

**Comment by thebombzen** [comment]
Can you provide a small sample, and/or a stack trace?

**Comment by 24fpsDaVinci** [comment]
> Can't reproduce, can you provide a stack trace and/or sample file?
> 
> In theory that assertion should only ever get hit if `data->grain_scale_shift` contains invalid values.



> Can you provide a small sample, and/or a stack trace?

i recompiled mpv using ffmpeg latest snapshot, the problem is resolved. I guess its an issue with ffmpeg-5.0.1-11.fc36. thanks
