### ISSUE TITLE
Choppy hardware decoding and huge VRAM consumption

### ISSUE THREAD

**Issue by weter11** [mpv-player/mpv#10526]
### Important Information
- mpv version: 0.34.0-386-g284fecc0bd built on Wed Jul 27 20:06:56 UTC 2022
- Linux Distribution and Version: Ubuntu 22.04
- Source of the mpv binary: https://launchpad.net/~savoury1/+archive/ubuntu/mpv
- Window Manager and version Xfwm 4.16
- GPU driver and version: nvidia 515.48.07

### Reproduction steps

`mpv --hwdec=nvdec --vo=gpu-next '2021 OLED 8K The Wild2 8K HDR 60fps.webm'`
When player decode this video, encoded in 4320p60 AV1 used VRAM reported by nvidia-smi is 6904MiB. For comparison firefox uses only 2173MiB. Also in firefox video playback smooth. But in mpv fps varies based on image complicity in a range of 50-60, with `--vd-lavc-dr=no` frame drops less frequent, with `vd-queue-enable=yes` frame drop absent, but with this option 8k videos, encoded in vp9 on YT crash with hardware decoding and mpv start play  8k vp9 with software decoder, which is very huge load for my 5800H.
Is #9675 about that now player copy textures a lot more than it needed and that create problems for playback?

### Expected behavior
Smooth playback
### Actual behavior
Choppy playback and frame drops
### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/9333999/mpv.log)
### Sample files

(https://www.youtube.com/watch?v=YJg4G7oeqs4)

**Comment by philipl** [comment]
There's a lot to consider here.

- Your firefox data point is probably orthogonal. Firefox will be playing a lower resolution version of the video. The youtube website will pick a resolution to fit your window, and your log shows your display is 1080p so even fullscreen it won't be a larger size. You also won't be getting hardware decoding unless you're using https://github.com/elFarto/nvidia-vaapi-driver.
- I've got a 3090 and a 4k display here and I also see a lot of framedrops. The frame timings don't show anything excessive, which means the time is being lost on the hardware side. Maybe it really is the GPU memcpys, but those are so cheap that I find it quite hard to believe.

Pragmatically, on a 1080p display, you should play the 1080p version of the stream.

**Comment by philipl** [comment]
And for the record, using ffmpeg to decode the video into a black hole, nvdec can hit 110+ fps, so it's not a limitation of the hardware decoder itself.

**Comment by philipl** [comment]
I also saw that `vd-queue-enable=yes` stops the frame drops.

**Comment by weter11** [comment]
nvidia-vaapi-driver instaled. I forgot that screen resolution has effect.
I disable internal screen, only my TV 2160p120. Now nvidia-smi report 6902MiB for mpv with opened firefox, 7150 MiB with closed, total memory usage 95%, so decoding limited by 8GiB VRAM now. fps not changed, with `vd-queue-enable=yes` its smooth, without 50-60fps. But with `vd-queue-enable=yes` decoding vp9 files have errors

`mpv --no-config --vd-queue-enable=yes --hwdec=nvdec --vo=gpu-next '8K HDR • Chris Pratt vs. Dinosaurs - Jurassic World ᵈᵗˢ⁻ʰᵈ.webm' 

```
 (+) Video --vid=1 (*) (vp9 8192x4608 23.976fps)
Using hardware decoding (nvdec).
VO: [gpu-next] 8192x4608 cuda[nv12]
V: 00:00:00 / 00:02:23 (1%)
[ffmpeg/video] vp9: No decoder surfaces left
Error while decoding frame (hardware decoding)!
[ffmpeg/video] vp9: No decoder surfaces left
Error while decoding frame (hardware decoding)!
[ffmpeg/video] vp9: No decoder surfaces left
Error while decoding frame (hardware decoding)!
Falling back to software decoding.
[ffmpeg/video] vp9: Not all references are available
[ffmpeg/video] vp9: Not all references are available
Error while decoding frame!
[ffmpeg/video] vp9: Not all references are available
```
Is it possible to limit mpv using `vd-queue-enable=yes` only for av1 streams as a temporary solution?
Also about vp9 video, memory usage for decoding firefox 2171MiB, mpv 2673MiB.

**Comment by weter11** [comment]
Also I tried such config:
```
[8k]
hwdec=nvdec
profile-cond=height >= 3500
vd-queue-enable=yes
ad-queue-enable=yes
target-colorspace-hint
[8k_vp9]
vd=vp9
hwdec=nvdec
profile-cond=height >= 3500
target-colorspace-hint`
```
But player always using `vd-queue-enable=yes`.

**Comment by thebombzen** [comment]
> Is it possible to limit mpv using `vd-queue-enable=yes` only for av1 streams as a temporary solution?

You can always do this with auto-profiles if you want to.

**Comment by n-buna404** [comment]
Refer https://github.com/mpv-player/mpv/issues/8941#issuecomment-865333317
Example
```
[av1]
profile-cond=p["video-format"]=="av1"
vd-queue-enable=yes
```

**Comment by weter11** [comment]
Thanks, didn't know about auto-profiles, now everything working. Interesting how RTX3050 decode 8k streams in hardware with its 4GB VRAM. Don't know is it really firefox display lower quality, I did screenshots of 4k and 8k videos to compare quality and both mpv and firefox show absolutely the same picture on my 4k TV. Also for me strange that hardware decoder need 15-31x more VRAM than software, for 8k videos it's a bit of problem, if some memory used by other apps, when you try to decode some videos cuda simply show that there not enough memory to decode videos.

**Comment by ZaquL** [comment]
> [ffmpeg/video] vp9: No decoder surfaces left

Youtube deleted all SDR and HDR vp9 videos. replacing then with AV1, so to check this Chris Pratt vs. Dinosaurs - Jurassic World ᵈᵗˢ⁻ʰᵈ.webm file is needed. Some other old file I checked was only 7 680x4 320 pixels, not 8192x4608. Maybe that is the issue. https://www.youtube.com/watch?v=h-eUuuIT-9s only has 7 680x4 320  av1. Dunno why delete them, considering some 4k60 streams are 16 **Gebibytes** in size!
