### ISSUE TITLE
dolyvision stream can't recognize video stream

### ISSUE THREAD

**Issue by lcksk** [mpv-player/mpv#10537]
### Important Information
All dolbyvision  contents on some  app can't recognize video when playing with mpv. There are two streams in content, but mpv can only play audio stream. However, with ffplay or vlc can correctly detect audio and video,
```
Input #0, mpegts, from '/home/work/dolby_hevc_aac.ts':
  Duration: 00:00:04.00, start: 0.125000, bitrate: 4457 kb/s
  Program 1 
  Stream #0:0[0x100]: Video: hevc (Main 10) (DOVI / 0x49564F44), yuv420p10le(pc), 3840x1616 [SAR 1:1 DAR 240:101], 24 fps, 24 tbr, 90k tbn, 24 tbc
    Side data:
      DOVI configuration record: version: 1.0, profile: 5, level: 6, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 0
  Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, 5.1, fltp, 256 kb/s
```

Provide following Information:
- mpv version 
  git-master
- Linux Distribution and Version 
  debian 10
- Source of the mpv binary 
  git master
- If known which version of mpv introduced the problem 
  none
- Window Manager and version 
  none 
- GPU driver and version 
  none
- Possible screenshot or video of visual glitches 
  none

### Reproduction steps
Use this [dolby_hevc_aac.zip](https://github.com/mpv-player/mpv/files/9356266/dolby_hevc_aac.zip) attached file to reproduce：

mpv --no-config --msg-level=all=trace --log-file=~/Desktop/dolby_mpv.log   dolby_hevc_aac.ts

### Expected behavior
Recognize all audio and video streams instead of only audio
### Actual behavior
Only audio is recognized, and video is ignored during playback
### Log file
[dolby_mpv.zip](https://github.com/mpv-player/mpv/files/9356297/dolby_mpv.zip)

### Sample files
[dolby_hevc_aac.zip](https://github.com/mpv-player/mpv/files/9356266/dolby_hevc_aac.zip)

**Comment by lcksk** [comment]
After a bit of in-depth debugging, I am not sure if it is caused by MPV or ffmpeg. It seems that the memory passed to the hevcdec probe function is damaged. I'm not sure whether this is a problem unique to my personal environment, or common one. Anyone can help confirm it?

**Comment by ZaquL** [comment]
> refuses to play it because it has no timing information, so it wouldn't know how to sync it:
> 
> > `[ffmpeg/demuxer] mpegts: start time for stream 0 is not set in estimate_timings_from_pts`

This is a very common warning for video streams, it is not important. Moreover, the problem only happens in mpv, so a bug is in mpv, no warning in ffplay. And third, the fix for this is just ffmpeg -i file .ts -c copy -strict unofficial file.mp4 and then back to ts. Dolby Vision is applied now.

Mpv is not the only one with buggy behaviour, vlc also cannot play it.

**Comment by lcksk** [comment]
> Mpv is not the only one with buggy behaviour, vlc also cannot play its video track, only audio.

My bad, indeed vlc can't play video. 
I remember I tried :
 ffmpeg -i dolby_hevc_aac.ts -vcodec copy -an dolby_hevc_aac_no.ts ,
Maybe I used the transcoded file（dolbyvision metadata may be destroyed） to play with vlc, and then got the wrong result.

> mpv recognizes stream 0, but refuses to play it because it has no timing information, so it wouldn't know how to sync it:

stream 0 is not recognized while execute estimate_timings() timings,. I dump AVFormatContext *ic  as follows:
----
     ic->streams[0]->codecpar    0x7fffd8037380
        codec_type               AVMEDIA_TYPE_DATA
        codec_id                 AV_CODEC_ID_BIN_DATA
        codec_tag                1230393156
        extradata                0x0
        extradata_size           0
        format                   -1
        bit_rate                 0
        bits_per_coded_sample    0
        bits_per_raw_sample      0
        profile                  -99
        level                    -99
        width                    0
        height                   0
        sample_aspect_ratio      struct
        field_order              AV_FIELD_UNKNOWN
        color_range              AVCOL_RANGE_UNSPECIFIED
        color_primaries          AVCOL_PRI_UNSPECIFIED
        color_trc                AVCOL_TRC_UNSPECIFIED
        color_space              AVCOL_SPC_UNSPECIFIED
        chroma_location          AVCHROMA_LOC_UNSPECIFIED
        video_delay              0
        channel_layout           0
        channels                 0
        sample_rate              0
        block_align              0
        frame_size               0
        initial_padding          0
        trailing_padding         0
        seek_preroll             0
        ch_layout                struct

     ic->streams[1]->codecpar    0x7fffd8021940
        codec_type               AVMEDIA_TYPE_AUDIO
        codec_id                 AV_CODEC_ID_AAC
        codec_tag                15
        extradata                0x0
        extradata_size           0
        format                   -1
        bit_rate                 259713
        bits_per_coded_sample    0
        bits_per_raw_sample      0
        profile                  -99
        level                    -99
        width                    0
        height                   0
        sample_aspect_ratio      struct
        field_order              AV_FIELD_UNKNOWN
        color_range              AVCOL_RANGE_UNSPECIFIED
        color_primaries          AVCOL_PRI_UNSPECIFIED
        color_trc                AVCOL_TRC_UNSPECIFIED
        color_space              AVCOL_SPC_UNSPECIFIED
        chroma_location          AVCHROMA_LOC_UNSPECIFIED
        video_delay              0
        channel_layout           0
        channels                 0
        sample_rate              0
        block_align              0
        frame_size               0
        initial_padding          0
        trailing_padding         0
        seek_preroll             0
        ch_layout                struct

----

codec_ type = AVMEDIA_ TYPE_ DATA
codec_ id = AV_ CODEC_ ID_ BIN_ DATA

We can notice that the audio has been detected as aac, but the video is still _BIN_DATA type, 
this is because dolbyvision is encapsulated in private mpegts data.


After further debugging, the difference between ffplay and mpv is: 
when detecting video, 
int avformat_find_stream_info(AVFormatContext *ic, AVDictionary **options)
{
  ...
          analyzed_all_streams = 0;
        if (!missing_streams || !*missing_streams)
            if (i == ic->nb_streams) {
                analyzed_all_streams = 1;
                /* NOTE: If the format has no header, then we need to read some
                 * packets to get most of the streams, so we cannot stop here. */
=>                if (!(ic->ctx_flags & AVFMTCTX_NOHEADER)) {
                    /* If we found the info for all the codecs, we can stop. */
                    ret = count;
                    av_log(ic, AV_LOG_DEBUG, "All info found\n");
                    flush_codecs = 0;
                    break;
                }
            }
   ...
}    

ic->ctx_flags AVFMTCTX_NOHEADER flags is canceled,
Because these mpegts.c part code logic,but ffplay never executes the following code.
----
/* handle one TS packet */
static int handle_packet(MpegTSContext *ts, const uint8_t *packet, int64_t pos)
{
   ...
           // stop find_stream_info from waiting for more streams
        // when all programs have received a PMT
        if (ts->stream->ctx_flags & AVFMTCTX_NOHEADER && ts->scan_all_pmts <= 0) {
            int i;
            for (i = 0; i < ts->nb_prg; i++) {
                if (!ts->prg[i].pmt_found)
                    break;
            }
            if (i == ts->nb_prg && ts->nb_prg > 0) {
                av_log(ts->stream, AV_LOG_DEBUG, "All programs have pmt, headers found\n");
 =>             ts->stream->ctx_flags &= ~AVFMTCTX_NOHEADER;
            }
        }
   ...
----

I don't know what causes this difference and how to fix it .

**Comment by ZaquL** [comment]
> dolbyvision metadata may be destroyed

That is not enough, you need to not only -c copy but to copy the header with -strict unofficial.

**Comment by lcksk** [comment]
It can also be reproduced on windows. It seems that the label of "os:linux" should be deleted.

**Comment by lcksk** [comment]
Fortunately, I found some useful information, which is actually related to the following two submissions of ffmpeg upstream:
- https://github.com/FFmpeg/FFmpeg/commit/e971eef8c0d2ebe461bb17f19a590b53511cc8f2 Set -scan_all_pmts 1 in ffmpeg, ffplay and ffprobe if not set by user.Fixes ticket [#3762.](http://trac.ffmpeg.org/ticket/3762)
- https://github.com/FFmpeg/FFmpeg/commit/58df81b02779c9c87cbf5403cfdbb437d5344669 avformat/mpegts: remove obsolate hacks for detecting streams with bad PMTs. Ffmpeg/ffprobe/ffplay sets scan_all_pmts to 1 when finding the streams, that
should be enough to handle files for which some early PMTs miss some streams.Fixes ticket [#9782](http://trac.ffmpeg.org/ticket/9782).

So it should be the latest change that caused the current problem. From the submission 8 years ago, we had better set scan_all_pmts = 1, it's better to keep consistent with ffmpeg/ffprobe/ffplay,  right?

**Comment by ZaquL** [comment]
> had better set scan_all_pmts = 1, it's better to keep consistent w

Yes, I can confirm ffplay.exe -scan_all_pmts 0 filets does not play a video and gives a warning.

**Comment by lcksk** [comment]
> > had better set scan_all_pmts = 1, it's better to keep consistent w
> 
> Yes, I can confirm ffplay.exe -scan_all_pmts 0 file.ts does not play a video and gives the warning.

Thanks for confirm that.

**Comment by lcksk** [comment]
After careful consideration, I think it is better to set option instead of hard coded modification demux_lavf.c, considering that there are various use scenarios, such as UDP over mpegts, RTP over mpegts, DVB, HLS and other different protocols, they have different requirements for delay and stream quality.Different use scenarios are better to use different options, so it is better to configure them through options to avoid disrupting some scenarios.

The following options are for reference when someone encounters the same problem in the future. I think it is time to close this problem and the corresponding pr。

```
demuxer-lavf-o=seg_format_options=scan_all_pmts=1,scan_all_pmts=1
```
set scan_all_pmtss = 1 can only affect the scene where mpegts is the top-level demuxer. If mpegts is the sub demuxer, scan_all_pmts  should be propagated to mpegts.
