### ISSUE TITLE
[vo/gpu-next/vulkan/libplacebo] Failed opening ICC profile... ignoring when icc-intent=3

### ISSUE THREAD

**Issue by 24fpsDaVinci** [mpv-player/mpv#10532]
### Important Information

- mpv version
git master
- Linux Distribution and Version
fedora 36
- Source of the mpv binary
git master
- If known which version of mpv introduced the problem
- Window Manager and version
wayland
- GPU driver and version
intel xe
- Possible screenshot or video of visual glitches

### Reproduction steps
set icc-intent=3
issue only occurs under gpu-next

### Expected behavior
activate absolute rendering intent

### Actual behavior
[vo/gpu-next/vulkan/libplacebo] Failed opening ICC profile... ignoring
color management disabled

**Comment by thebombzen** [comment]
Could you perhaps provide a log and/or a sample?

**Comment by 24fpsDaVinci** [comment]
> Could you perhaps provide a log and/or a sample?

[log.txt](https://github.com/mpv-player/mpv/files/9338652/log.txt)
[BigBuckBunny-AV1.webm](https://user-images.githubusercontent.com/3499141/184680258-f233078d-6b24-4610-85f3-f353b539f9b0.webm)

**Comment by haasn** [comment]
This is a known issue. The problem is that Little CMS refuses to detect a black point in absolute colorimetric intent, and I'm not entirely sure why. I still have to investigate it further.

For now I recommend just using relative colorimetric.

**Comment by 24fpsDaVinci** [comment]
as a workaround, i am using --lut and --lut-type with a pre-generated .cube file
