### ISSUE TITLE
HDR tone mapping 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#10530]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file

Hi there I was wondering if anyone could provide me with there config they are using for hdr tone mapping with the most accurate colour reproduction 

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by haasn** [comment]
The most *accurate* tone mapping method is `--vo=gpu-next --tone-mapping=clip --gamut-mapping-mode=clip`.

This will guarantee 100% accuracy for all representable colors, and hard clip all out-of-gamut colors.

**Comment by Jamie666123** [comment]
> The most _accurate_ tone mapping method is `--vo=gpu-next --tone-mapping=clip --gamut-mapping-mode=clip`.
> 
> This will guarantee 100% accuracy for all representable colors, and hard clip all out-of-gamut colors.

Can you use this without gpu-next as it dosent work on my device

**Comment by haasn** [comment]
> > The most _accurate_ tone mapping method is `--vo=gpu-next --tone-mapping=clip --gamut-mapping-mode=clip`.
> > This will guarantee 100% accuracy for all representable colors, and hard clip all out-of-gamut colors.
> 
> Can you use this without gpu-next as it dosent work on my device

I think so, though I'm not 100% sure.

**Comment by thebombzen** [comment]
Did you try `--vo=gpu --tone-mapping=clip --gamut-mapping-mode=clip`?

**Comment by Jamie666123** [comment]
> Did you try `--vo=gpu --tone-mapping=clip --gamut-mapping-mode=clip`?

Yes but it seems to be over saturating and too bright with some very bright parts of films

**Comment by haasn** [comment]
> Yes but it seems to be over saturating and too bright with some very bright parts of films

That is expected when the source contains colors you simply cannot represent on the display device.

**Comment by Jamie666123** [comment]
> > Yes but it seems to be over saturating and too bright with some very bright parts of films
> 
> That is expected when the source contains colors you simply cannot represent on the display device. There is no way to accurately tone-map in this case, and your only question is what subjective trade-off you prefer.

Any other ways I can try I am very new to this really any other decent trade offs I can try to get as close as possible thanks

**Comment by thebombzen** [comment]
You can try a different tonemapping algorithm, such as `--tone-mapping=reinhard`. You can view a list of algorithms supported with `--tone-mapping=help`.

**Comment by Jamie666123** [comment]
Should I keep tone mapping mode clip on each algorithm that I try

**Comment by thebombzen** [comment]
I'd leave it on auto (the default).

**Comment by Jamie666123** [comment]
> I'd leave it on auto (the default).

Ok thanks and there isn’t anything else I might be able to add to the config to help?

**Comment by mdannp** [comment]
try this for vo=gpu:

```
tone-mapping=bt.2390
gamut-mapping-mode=clip
tone-mapping-mode=auto
tone-mapping-param=2.0
target-peak=auto # or adjust it
```

**Comment by damian101** [comment]
> The most _accurate_ tone mapping method is `--vo=gpu-next --tone-mapping=clip --gamut-mapping-mode=clip`.
> 
> This will guarantee 100% accuracy for all representable colors, and hard clip all out-of-gamut colors.

This statement is actually incorrect, because gpu-next tonemapping is broken, produces highly inaccurate results.

**Comment by Hrxn** [comment]
This statement is actually a joke, because it was meant to be a joke.
