### ISSUE TITLE
Multiline options in mpv.conf

### ISSUE THREAD

**Issue by github-account1111** [mpv-player/mpv#10536]
The formatting for longer option strings can get very unwieldly and barely readable:
![image](https://user-images.githubusercontent.com/5728319/184972417-54b12c75-a6ab-4c4e-a2fa-0f9502d7306b.png)
I would like to have something like this instead, with newlines and indentation:
![image](https://user-images.githubusercontent.com/5728319/184972527-c0de0b9f-59e6-40ee-b4ba-521163de285c.png)

Is there a syntax for that?

**Comment by christoph-heinrich** [comment]
I used to use something very similar (generated with a little fish script).
I think you can achieve the same with a fairly basic `format` and `format-sort`.
```
--ytdl-format=b[ext=mov]/bv+ba/b
--ytdl-raw-options=format-sort=[fps,res,vcodec,acodec,quality]
```
I'm not sure about the syntax for the sorting part, because I have mine in my yt-dlp/config, but you get the idea.

**Comment by github-account1111** [comment]
Thanks for all the tips!

I'm using a slightly modified version of https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/blob/master/scripts/Archivist%20Scripts/Archivist%20Scripts/Unique/Unique.sh
Why would they use those long format selection strings if the same result is achievable with `format` & `format-sort`?

>I'm not sure about the syntax for the sorting part, because I have mine in my yt-dlp/config

Are you saying your mpv sees your yt-dlp config so there's no need to duplicate those options?
How does one achieve that?

> \> h265 \> h264

Wouldn't you need to account for "hevc" and "avc" being sometimes used for those codecs respectively?
Or is that taken care of now?

**Comment by christoph-heinrich** [comment]
> I'm using a slightly modified version of https://github.com/TheFrenchGhosty/TheFrenchGhostys-Ultimate-YouTube-DL-Scripts-Collection/blob/master/scripts/Archivist%20Scripts/Archivist%20Scripts/Unique/Unique.sh Why would they use those long format selection strings if the same result is achievable with `format` & `format-sort`?

I don't know why they don't use that. I think that repo has been around for much longer then yt-dlp, and youtube-dl does not support sorting, so maybe they just left things as they were when transitioning to yt-dlp to avoid accidentaly breaking things.

> Are you saying your mpv sees your yt-dlp config so there's no need to duplicate those options? How does one achieve that?

mpv calls yt-dlp without the `--ignore-config` option, so any configuration in `.config/yt-dlp/config` gets loaded.
Now by default it does pass `--format=bestvideo+bestaudio/best`, but if you use `ytdl-format=ytdl` it does not do that, and so the format configuration from your yt-dlp config file will apply.

> Wouldn't you need to account for "hevc" and "avc" being sometimes used for those codecs respectively? Or is that taken care of now?

I don't understand what you mean. If you want to avoid them, you could add `[vcodec?!^=hevc][vcodec?!^=avc]` to your formats.
By default it prefers av01, vp9.2 and vp9 over them.

**Comment by github-account1111** [comment]
>I don't understand what you mean.

YouTube lists H264 as `avc...`, and Vimeo lists H265 as `hevc...`, so wouldn't `h265` and `h264` end up getting ignored?
Or is there a hard-coded list that accounts for those discrepancies?

**Comment by christoph-heinrich** [comment]
I don't know, I've never noticed any unexpected behavior in that regard, but a quick grep over the yt-dlp codebase didn't reveal any definition of aliases.
The man page has this though:
```
E.g.  +codec:avc:m4a (equivalent to +vcodec:avc,+acodec:m4a) sets the video codec preference to h264 > h265 > vp9 >  vp9.2
>  av01  >  vp8  > h263 > theora and audio codec preference to mp4a > aac > vorbis > opus > mp3 > ac3 > dts.
```
Suggesting that it should work.
It's probably best if you test it out and if it doesn't work, open an issue over at [yt-dlp](https://github.com/yt-dlp/yt-dlp/issues).

**Comment by github-account1111** [comment]
Turns out I was just confused about how the whole format sorting thing works.
Only parameter order can be redefined.
Sorting _within_ each parameter is predefined, and only a single element within each parameter can be reordered.

There's an issue (https://github.com/yt-dlp/yt-dlp/issues/2260) requesting multiple elements within each parameter to be reorderable.
