### ISSUE TITLE
Mute audio based on bad words in subtitles

### ISSUE THREAD

**Issue by navyfrog** [mpv-player/mpv#10539]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
Example of feature is Google Chrome extension: Stream Clean
It would be great to have the ability to auto-mute the audio when a bad word is detected in the subtitles. It would need a file or list of bad words that can be edited to the user's preferences.  MPV could then detect the bad word based on that file/list and mute the audio for that string of subtitle and star **** the bad word in the subtitle. If possible, have the option to always show the subtitles or only be shown if a bad word was detected.
The above extension is used for streaming sites like Netflix, but there is nothing available for downloaded video files with subtitles.
Not all of us want to listen to swearing and blasphemy.

### Alternative behavior of the wanted feature
Same as above, but subtitles could remain visible 100% of the time, even if no bad word was detected.

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by CounterPillow** [comment]
fuck no, subtitles don't contain per-word timing information so unless you want to mute an entire subtitle line you'd be shit out of luck. If you want to mute the entire god damn subtitle line, write a script for it, this isn't something for core mpv functionality to do.

**Comment by navyfrog** [comment]
Funny (I think). 
Thanks for the feedback.  Any recommendations for a script writer?

**Comment by haasn** [comment]
> fuck no, subtitles don't contain per-word timing information so unless you want to mute an entire subtitle line you'd be shit out of luck. If you want to mute the entire god damn subtitle line, write a script for it, this isn't something for core mpv functionality to do.

As a rough approximation you could count the number of characters (syllables?) in the subtitle line and only mute that corresponding relative portion of the subtitle's display time. With some luck it might turn out to be reasonably accurate?

**Comment by navyfrog** [comment]
> > fuck no, subtitles don't contain per-word timing information so unless you want to mute an entire subtitle line you'd be shit out of luck. If you want to mute the entire god damn subtitle line, write a script for it, this isn't something for core mpv functionality to do.
> 
> As a rough approximation you could count the number of characters (syllables?) in the subtitle line and only mute that corresponding relative portion of the subtitle's display time. With some luck it might turn out to be reasonably accurate?

Thanks but it doesn't need to be that accurate. As an example, the Google Extension mutes the entire subtitle line that includes the bad word.

**Comment by stax76** [comment]
If you need test files, try David Goggins.

**Comment by garoto** [comment]
> If you need test files, try David Goggins.

Damn, you're cringe.

**Comment by hooke007** [comment]
> mutes the entire subtitle line that includes the bad word.

```ini
[mute4word]
 profile-cond = sub_text:match("fxxk")~=nil
 profile-restore = copy
 mute = yes
```

**Comment by navyfrog** [comment]
> > mutes the entire subtitle line that includes the bad word.
> 
> ```ini
> [mute4word]
>  profile-cond = sub_text:match("fxxk")~=nil
>  profile-restore = copy
>  mute = yes
> ```

Thank you very much! Just need to learn how to implement this...but will do some research. Thanks!

**Comment by jtaala** [comment]
Hey @navyfrog, I had a similar need so wrote a small js script that should meet your requirements.

See [mpv script to mute on specific words](https://github.com/jtaala/mpv-mute-on-specific-subtitle-words).

It will mute during the "bad" word(s) subtitle (and hide that subtitle) until it passes, at which time it will restore volume and subtitle visibilty.

**Comment by navyfrog** [comment]
> Hey @navyfrog, I had a similar need so wrote a small js mpv script that should meet your requirements.
> 
> See [mpv script to mute on specific subtitle words](https://github.com/jtaala/mpv-mute-on-specific-subtitle-words).
> 
> It will mute during the "bad" word(s) subtitle (and hide that subtitle) until it passes, at which time it will restore volume and subtitle visibilty.

Thank you so much! I will give it a go tomorrow.  I really appreciate it.
