### ISSUE TITLE
how to display current frame number in display information？can show it by type i ?

### ISSUE THREAD

**Issue by baoxin1100** [mpv-player/mpv#10538]
I want to know which frame is currently playing, how can I display it?

**Comment by Akemi** [comment]
property `estimated-frame-number`, see https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst#property-list

though mpv is not a frame server and doesn't know about frames. so, like the property name suggests, it is only an estimated number.

you can display it, for example, with a keybinding like this (shift+i).
```
I show_text "${estimated-frame-number}" 
```

**Comment by baoxin1100** [comment]
> Thank you, this solved my problem perfectly

thank you so much, you solve my problem

**Comment by baoxin1100** [comment]
> property `estimated-frame-number`, see https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst#property-list
> 
> though mpv is not a frame server and doesn't know about frames. so, like the property name suggests, it is only an estimated number.
> 
> you can display it, for example, with a keybinding like this (shift+i).
> 
> ```
> I show_text "${estimated-frame-number}" 
> ```

Thank you, this solved my problem perfectly
