### ISSUE TITLE
How do you apply a chromakey to a video overlay, and toggle/play it at runtime?

### ISSUE THREAD

**Issue by codecnotsupported** [mpv-player/mpv#10535]
Hi, I'm trying to apply a chromakey to a video overlay to a video. I need to able to play the overlay at runtime.
```
Overlay video (paused) -> ChromaKey -\
                                      +-> Overlaid video -> Time passes -> Unpause overlay video
Video -------------------------------/
```
I've seen it's possible to toggle at runtime by using transparency [as seen here](https://github.com/mpv-player/mpv/issues/5559#issuecomment-399703390).
I'm quite new to video filters, though I've read a bit of [mpv](https://github.com/mpv-player/mpv/blob/master/DOCS/man/vf.rst) & [FFMPEG](https://ffmpeg.org/ffmpeg-filters.html) documentation regarding the subject, however I remain confused as how to apply them.
Some pointers would be useful.

[Log file](https://github.com/mpv-player/mpv/files/9352913/output.txt)

**Comment by thebombzen** [comment]
You can't pause playback on some input files and not others.

**Comment by codecnotsupported** [comment]
> You can't pause playback on some input files and not others. You're better off generating this in advance and then just playing it back as a finished video.

That's going to be difficult if the video is live, e.g. a stream.
