### ISSUE TITLE
linux 5.19.2 breaks vaapi

### ISSUE THREAD

**Issue by lavilao** [mpv-player/mpv#10547]
### Important Information

Provide following Information:
- mpv version:  0.34.1-dirty
- Linux Distribution and Version:  manjaro lastest
- Source of the mpv: binary on manjaro repo
- If known which version of mpv introduced the problem: linux 5.19.2
- Window Manager and version: Gnome 42.3
- GPU driver and version: Mesa 22.1.6
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

play any hardware accelerated video

### Expected behavior
it plays

### Actual behavior
the gpu hangs and the video shows severe artifacts/corruption
### Log file
[output.txt](https://github.com/mpv-player/mpv/files/9376352/output.txt)

**Comment by lavilao** [comment]
This is more of a warning to rolling release distros users than a proper issue of mpv because the problem is on the kernel not on mpv.

**Comment by thebombzen** [comment]
Mesa has their own bug tracker. https://gitlab.freedesktop.org/mesa/mesa/-/issues

**Comment by lavilao** [comment]
is a mesa issue? Weird, thanks for the info.

**Comment by Xathros1** [comment]
> I don't think is a mesa issue, it happens when the kernel is updated to 5.19.2. But I Guess this is not the place to put this issue, sorry for inconvenience

Hey, I'm running Tumbleweed and seem to have a similar issue. 

I've already tried a older kernel, and that didn't fix it for me - so Kernel seems unrelated.

Screen1: with vaapi
https://ibb.co/sKJBV7k
screen2: without vaapi
https://ibb.co/dr5JpRw

Have you tried maybe using a older mesa version? Did that fix it for you?

**Comment by lavilao** [comment]
@Xathros1 going to 5.18 fixed it for me, no need to change mesa

**Comment by lavilao** [comment]
in case someone cares issue seems solved in 5.19.12
