### ISSUE TITLE
Minimizes when --ontop is used and Win+d is pressed

### ISSUE THREAD

**Issue by github-account1111** [mpv-player/mpv#10549]
### Important Information

Provide following Information:
- mpv version 0.34.0-376-g70fa9502f3
- Windows Version 10
- Source of the mpv binary Sourceforge
- If known which version of mpv introduced the problem N/A
- Possible screenshot or video of visual glitches N/A

### Reproduction steps

1. Open a video with `--ontop`.
1. Press Win+d.

### Expected behavior

Mpv window is still on top.
See the popup video players in Edge and Firefox.

### Actual behavior

Mpv window is minimized.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/9379211/output.txt)

### Sample files

Any video file should do.

**Comment by hooke007** [comment]
> the popup video players in Edge and Firefox.

PIP window doesn't support minimizing.

> Mpv window is minimized.

Why should it be the unexpected behavior ?
win+d would force any window which support minimizing to be minimized.

**Comment by github-account1111** [comment]
>Why should it be the unexpected behavior ?

Because when I tell a program to stay on top I expect it to consistently stay on top?

>PIP window doesn't support minimizing.

Could be because it shouldn't minimize in the first place from a usability standpoint, so no need to implement.

**Comment by thebombzen** [comment]
On top means it renders above other windows when it is not minimized. Minimizing it will still minimize it.

**Comment by github-account1111** [comment]
Where did you get the "when it is not minimized" part, and why is that the rule?
Usability-wise, someone who wants an always on top window will probably expect it to always be on top, won't they?
Otherwise why make it always-on-top?

If I want to focus on the video I'd expect Win-d to minimize everything, and the video itself to remain.
Otherwise is neither usable nor consistent.

**Comment by thebombzen** [comment]
> Usability-wise, someone who wants an always on top window will probably expect it to always be on top, won't they?

Not if they minimize it.

**Comment by github-account1111** [comment]
_Including_ if they minimize it.
Always means always.

I'm more interested in actual usability, not semantics.

**Comment by ZaquL** [comment]
> _Including_ if they minimize it.

That is not what happens with task manager.

**Comment by Hrxn** [comment]
> _Including_ if they minimize it. Always means always.
> 
> I'm more interested in actual usability, not semantics.

That's not how it works on Windows, since ever, and for that matter, on other operating systems as well.

Have you actually used a computer before?

**Comment by thebombzen** [comment]
> That is not what happens with task manager.

This. If you set Task Manager to be always on top, and then you minimize it, it will still minimize. This is because Windows itself will allow you to minimize windows flagged as "Always On Top" which is a feature provided by windows. If you want always-on-top windows to be unable to be minimized you'd have to take up an issue with Microsoft and their desktop environment.

**Comment by github-account1111** [comment]
>Have you actually used a computer before?

Not sure what's up with the snarkiness.
If you paid any attention to the usernames on adjacent GH projects you'd know I've in fact used computers quite extensively.

Like I said, I was going off of PIPs in both Firefox and Chromium browsers because they roughly replicate how one would use mpv with URLs.
Task Manager simply didn't come to mind for which I apologize.

Would a feature request for something like this make sense?
The use-case is still sensible, isn't it?

**Comment by ZaquL** [comment]
> going off of PIPs in both Firefox and Chromium browsers because they roughly replicate

I do not think mpv's option is using Windows 10 PiP API. The fact if the matter, it is a compicated thing and it does not minimize because of the way its API behaves.
