### ISSUE TITLE
About changelog

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#10548]
Where are the changelogs when new versions are released?
I download from here:
https://sourceforge.net/projects/mpv-player-windows/files
but I don't see these notes.
Here there are:
https://github.com/mpv-player/mpv/releases
But they ended on 3 Jan 2022

**Comment by Akemi** [comment]
they ende because there hasn't been a new release since then.

**Comment by dexeonify** [comment]
The commit message _is_ the changelog, if you are using the Git build of mpv.
