### ISSUE TITLE
gpu-next no longer works on Windows 7 after 9ffaa6b (Apr 29th)

### ISSUE THREAD

**Issue by iamtherobin** [mpv-player/mpv#10541]
### Important Information
When using gpu-next with build [3458651.7z ](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220508-git-3458651.7z/download), video output has seized to function.

Provide following Information:
- Windows 7 x64
- AMD Radeon RX480 using last driver provided by AMD
- Last working version for me [git-9ffaa6b.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220501-git-9ffaa6b.7z/download)
- Exception code c0000005 and gpu-next issue starts with [git-3458651.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220508-git-3458651.7z/download)
- gpu-next issue continues with [d2467f6.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220724-git-d2467f6.7z/download)

### Reproduction steps

Create an mpv.conf with the following:
> log-file=mpv.log
> vo=gpu-next

Launch mpv.exe with above config.

### Expected behavior

Using [git-9ffaa6b.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220501-git-9ffaa6b.7z/download) everything works as expected. mpv.exe loads and I see the "Drop files or URLs to play here". Video and audio output works when a video is loaded.

### Actual behavior

Starting with [3458651.7z ](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220508-git-3458651.7z/download) this creates an immediate crash launching mpv.exe with c0000005 on my system (Windows 7 x64). No video output if launched directly with a video, but audio will play.

Starting with [d2467f6.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220724-git-d2467f6.7z/download) mpv.exe will launch with no video loaded, but will still not produce any video output when a video dropped into it (audio still plays). The "Drop files or URLs to play here" notice does not show (window is blank).

Using video output other than gpu-next, video output functions in all versions.

### Log file

Here is a log file with no video loaded. mpv.exe is launched and closed using the above config.

Working version 9ffaa6b81b: https://pastebin.com/y5txkpZa
No video output version d2467f61be: https://pastebin.com/80CktxsB

**Comment by thebombzen** [comment]
What happens if you use a build of mpv directly, and not through smplayer?

**Comment by iamtherobin** [comment]
Exact same issue using mpv directly. As long as gpu-next is being called, there is no video output. In fact, using mpv directly, the initial "Drop files or URLs to play here" message does not show up when using gpu-next.

**Comment by iamtherobin** [comment]
Ok small update. I found that mpv.exe will crash immediately upon launching with exception code c0000005 if gpu-next is used starting from 3458651 with no video loaded. If launch it with a video, I get the blank screen with playing audio instead (either loading the video through SMPlayer or launching mpv.exe directly with the target file).

The issue with mpv.exe throwing a c0000005 is fixed in build d2467f6. From this build, mpv.exe will open using gpu-next, but no video output will work (even the Drag files or URLs to play here does not show). I am assuming [this ](https://github.com/mpv-player/mpv/commit/8ef744d1b7f64b3b7d814ee4d9376d6538befb73) commit fixed the exception code error.

I am providing new log files with no video loaded and will update the initial issue. The mpv.conf only has vo=gpu-next and the log file set. I simply lauch mpv.exe and close it.

mpv 0.34.0-285-g9ffaa6b81b: https://pastebin.com/y5txkpZa
mpv 0.34.0-384-gd2467f61be: https://pastebin.com/80CktxsB

**Comment by iamtherobin** [comment]
Could commit https://github.com/mpv-player/mpv/commit/76f888f5551f486b6d0c9b9c3a0f17e1e0bf9d71 be the issue? It seems the only commit introduced into the build that began the issues that has anything to do with video output.

**Comment by Dudemanguy** [comment]
That code wouldn't even compile on windows.

**Comment by CounterPillow** [comment]
I'm assuming it's more that something in a library version or other build option shinchiro uses changed, and not an mpv code change in of itself.

That being said, should gpu-next really care about supporting the new Windows XP?

![image](https://user-images.githubusercontent.com/308818/185292992-ee17d5bc-98c2-4835-bbc8-772b2855fccf.png)

**Comment by haasn** [comment]
Fixed by https://code.videolan.org/videolan/libplacebo/-/merge_requests/276

**Comment by fabiorug** [comment]
i have crashes on windows 7 64 bit with https://github.com/zhongfly/mpv-winbuild
it starts from 20 August 2022

**Comment by zhongfly** [comment]
> i have crashes on windows 7 64 bit with https://github.com/zhongfly/mpv-winbuild it starts from 20 August 2022

Maybe your crash is not related to this issue.

The 8.20 or 8.21 build is actually build for x86_64-v3(although its filename is x86_64).It means old cpus (don't support AVX2) will crash.
You can download the 8.22 build or newer.The "x86_64" builds(for example:mpv-**x86_64**-20220822-git-6c1f01d.7z) are compatible with old cpus just like before,and the new "x86_64-v3" builds(for example:mpv-**x86_64-v3**-20220822-git-6c1f01d.7z) are for modern cpus.

**Comment by iamtherobin** [comment]
The bug is fixed with the swapchain fallback merge. @zhongfly [mpv-x86_64-20220822-git-6c1f01d.7z](https://github.com/zhongfly/mpv-winbuild/releases/download/2022-08-22/mpv-x86_64-20220822-git-6c1f01d.7z) build above is working both with my SMPlayer config and directly with mpv.exe

Here is a log showing the fallback is working: https://pastebin.com/73808qhh
