### ISSUE TITLE
Fullscreen geometry

### ISSUE THREAD

**Issue by github-account1111** [mpv-player/mpv#10543]
### Expected behavior of the wanted feature

Instead of a centered video:
![image](https://user-images.githubusercontent.com/5728319/185292556-523c45fe-4211-43f4-950a-5aeb204bd9c4.png)
I think an option to move the video all the way up in fullscreen would be useful:
![image](https://user-images.githubusercontent.com/5728319/185292868-ce3a4219-50f5-442d-8157-23608db9db04.png)
It's more ergonomic because it puts less strain on your neck as you're less likely to have to look down.

**Comment by ma-zsola** [comment]
Try `--video-align-y=-1` option.
https://mpv.io/manual/master/#options-video-align-y
