### ISSUE TITLE
under gpu-next mapping SDR content into PQ makes the image look washed out and raises the black point

### ISSUE THREAD

**Issue by EndlesslyFlowering** [mpv-player/mpv#10558]
### Important Information

Provide following Information:
- mpv version 0.34.0-409-gb669a20bb5
- Windows 10 x64 19043.1889
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files
- I think gpu-next always behaved like this

### Reproduction steps

the following config is used:

```
profile=gpu-hq
vo=gpu-next
gpu-api=d3d11
gpu-context=d3d11
d3d11-output-format=rgb10_a2
d3d11-output-csp=pq
dither-depth=10
target-prim=bt.2020
target-trc=pq
target-colorspace-hint=yes
```

### Expected behavior

same behaviour as using `vo=gpu` with the exact same config which produces correct results.

### Actual behavior

black point is raised and the image looks washed out.

### Notes

the issue is hardware agnostic as other people I have talked to also have the same behaviour.
I attached screenshots of how it looks with `vo=gpu-next` and `vo=gpu`.
This also affects `inverse-tone-mapping` where the raised black point is especially aggravating for content with black bars.
JXR screenshots:
[gpu.zip](https://github.com/mpv-player/mpv/files/9387273/gpu.zip)
[gpu-next.zip](https://github.com/mpv-player/mpv/files/9387277/gpu-next.zip)
screenshots taken with mpv's screenshot function:
`vo=gpu`:
![gpu](https://user-images.githubusercontent.com/19245343/185753906-969ed2a7-b98c-4330-851a-d24b85c04438.png)
`vo=gpu-next`:
![gpu-next](https://user-images.githubusercontent.com/19245343/185753915-4af54bd1-80ec-470a-9df5-e3e824a502f9.png)

**Comment by quietvoid** [comment]
Would be useful if you provided screenshots in a more common format.

**Comment by EndlesslyFlowering** [comment]
I added screenshots taken with mpv's screenshot function.

**Comment by quietvoid** [comment]
This seems caused by `libplacebo` defaulting to 0.005 nits black point.
Probably the same issue as https://github.com/mpv-player/mpv/issues/10113#issuecomment-1104473663

Example reproduction: https://slow.pics/c/UdYppY5c
CLI: `mpv --no-config --vo=gpu-next --target-prim=bt.2020 --target-trc=pq --profile=gpu-hq`
For the default `plplay` image, I had disabled tone mapping so that may be why there's a difference with the `gpu-next` image.

**Comment by EndlesslyFlowering** [comment]
I heard about the 0.005 nits black point before. I think that SDR is standardized like that.
There should be an option to change this though as playing back videos in SDR while my OLED is in SDR is also 100% black as in the pixel is turned off. While mapping SDR into PQ the blackpoint now is 0.005 nits which is stupid.

This still leaves the washed out look though :( .

**Comment by haasn** [comment]
> I heard about the 0.005 nits black point before. iirc SDR is standardized like that.

SDR is standardized at 0.12 nits. But I know where this issue stems from, it comes from libplacebo not correctly forwarding the active swapchain configuration to the swapchain frames.

I'll fix it.

**Comment by EndlesslyFlowering** [comment]
> But I know where this issue stems from, it comes from libplacebo not correctly forwarding the active swapchain configuration to the swapchain frames.

Does this affect both the blackpoint and the washed look?

**Comment by haasn** [comment]
Actually, I take what I said back. That 0.005 nits is hardcode is a bug exclusive to vulkan, the d3d11 code correctly forwards the luminance data to the renderer.

Something else must be going on. It would be useful if you could set up a debugger so we can see what the actual values being computed/sent are.

**Comment by EndlesslyFlowering** [comment]
Sure if you could point me to a guide or something which explains what I need to do.

**Comment by haasn** [comment]
Idk how it works on Windows as I only use gdb on Linux. Though you could at least upload a log, for now

**Comment by EndlesslyFlowering** [comment]
here you go:
[mpv.log](https://github.com/mpv-player/mpv/files/9387665/mpv.log)

**Comment by haasn** [comment]
Okay, so what I think is going on is that the swapchain is being *configured* with a black point of 0.000 nits (because nothing ever sets it). So whether or not it gets correctly reflected back to the swapchain frame is irrelevant, because there's no hint attached. This lack of metadata then gets inferred to 0.005 nits later on in the pipeline.

The result is a confusion, where windows thinks we're rendering to 0.000 nits black, and libplacebo thinks we're rendering to 0.005 nits black.

I've submitted [this MR](https://code.videolan.org/videolan/libplacebo/-/merge_requests/278) which ought to fix the issue.

**Comment by haasn** [comment]
Though, we might also want to re-think whether or not we want to default HDR to 0.005 nits or not. Another value might be better, including absolute zero (or something effectively equivalent to it like 1e-6).

I don't remember where I got this number from, but I think it was informed by the capabilities of typical HDR panels at the time. What do modern OLED panels look like?

**Comment by EndlesslyFlowering** [comment]
> What do modern OLED panels look like?

The main selling point of OLED is having individually lit pixels with no backlight. So 100% black means the pixel is off and no light at all is emitted. This includes all OLEDs.
When you are used to that pixel being off and it suddenly is 0.005 nits especially with something like black bars it is a big annoyance. This also affects cropped black bars as they get added back in for a full 16:9 frame and they are 0.005 nits again.

**Comment by haasn** [comment]
```diff
diff --git a/src/colorspace.c b/src/colorspace.c
index 761793b9..27adb252 100644
--- a/src/colorspace.c
+++ b/src/colorspace.c
@@ -421,7 +421,7 @@ void pl_color_space_infer(struct pl_color_space *space)
 
     if (space->hdr.min_luma <= 0 || space->hdr.min_luma > 100) {
         if (pl_color_transfer_is_hdr(space->transfer)) {
-            space->hdr.min_luma = 0.0050f; // Typical HDR black
+            space->hdr.min_luma = 1e-6; // Avoid numerical issues
         } else {
             space->hdr.min_luma = space->hdr.max_luma / 1000; // Typical SDR contrast
         }
```

If you can try out this patch, it removes the 0.005 nits default for HDR.

**Comment by EndlesslyFlowering** [comment]
> I don't remember where I got this number from, but I think it was informed by the capabilities of typical HDR panels at the time.

You probably got them from the "Mastering display luminance" which is attached in the HDR metadata in movies. There are ones which are 0.005-1000 nits and 0.005-4000 nits which are LCD based and there is also one 0-1000 nits Sony OLED too which sadly only rarely gets used these days. I think modern LCDs with dimming zones also reach 0.005 nits or similar values while OLEDs always have been 0 nits.

> If you can try out this patch, it removes the 0.005 nits default for HDR.

I'll try and compile mpv for myself. I have never done it before though.

**Comment by hooke007** [comment]
For modern OLED, black depth should be less than 0.0005 nits. The pixel could not be "off" because of some technology restrict.

**Comment by ZaquL** [comment]
> What do modern OLED panels look like?

It does not matter though, when tonemapping is done on TV, TV tonemapps linear luminance and the black point, of course in practice 64 Y' in PQ means 0, black body. While next one 65 is supposed to be close to 0.00005, 66 is 0.00017. See https://wswartzendruber.net/uploads/pq-values.txt
Note that this is for 10 bit, 12 bit is quite different. Full range is different too, of course.

What should be considered though is that SDR is scene referred, so its 0 is  65 PQ. sRGB and Adobe RGB do have a black point which assigns to 65 a bigger (quite bigger) value, since those are (some reference) display referred.

> There are ones which are 0.005-1000 nits and 0.005-4000 nits which are all LCD based

Dolby Pulsar dual LCD with 12 bit panel, yes. And yes, LG without various black bugs can very simply do darker as you can see with Dolby Vision for Pulsar clip (in fact it can very simpy do 0.00006 nits, 65): https://www.avsforum.com/threads/spears-munsil-uhd-hdr-benchmark-disc-discussion.3075780/page-46#post-59699132

>The pixel could not be "off" because of some technology restrict.

It can, but that is still not 100% black body. There is no simple way to achieve that, maybe one can try the black box approach when the light comes to a closed box painted with black color (in fact that is better than some chemicals used in Vantablack).

**Comment by EndlesslyFlowering** [comment]
> If you can try out this patch, it removes the 0.005 nits default for HDR.

the if else statement ends up on else for mapping SDR into PQ with the config provided. Removing the if else statement and the else case like this makes it work:
```c
     if (space->hdr.min_luma <= 0 || space->hdr.min_luma > 100) {
         space->hdr.min_luma = 1e-6; // Avoid numerical issues
     }
```

**Comment by haasn** [comment]
> > If you can try out this patch, it removes the 0.005 nits default for HDR.
> 
> the if else statement ends up on else for mapping SDR into PQ with the config provided. Removing the if else statement and the else case like this makes it work:
> 
> ```c
>      if (space->hdr.min_luma <= 0 || space->hdr.min_luma > 100) {
>          space->hdr.min_luma = 1e-6; // Avoid numerical issues
>      }
> ```

What?? But you have `target-trc=pq` in your config, so how can it be picking the SDR branch?

**Comment by EndlesslyFlowering** [comment]
> What?? But you have `target-trc=pq` in your config, so how can it be picking the SDR branch?

I tested with this and it definitely does:
```c
    if (space->hdr.min_luma <= 0 || space->hdr.min_luma > 100) {
        if (pl_color_transfer_is_hdr(space->transfer)) {
            space->hdr.min_luma = 1e-6;
        } else {
            space->hdr.min_luma = 10.0f;
        }
    }
```
now the picture is even brigther and more washed out:
![mpv-shot0010](https://user-images.githubusercontent.com/19245343/185812159-956bb972-45d4-402d-a67f-d8a5c1f33dbe.png)

**Comment by haasn** [comment]
Hmm, but is this applying to the source or the destination color space? Maybe the SDR->PQ mapping is not correctly adjusting the black point as it should? Can you post another log with this tweak?

**Comment by EndlesslyFlowering** [comment]
> Hmm, but is this applying to the source or the destination color space? Maybe the SDR->PQ mapping is not correctly adjusting the black point as it should? Can you post another log with this tweak?

[mpv.log](https://github.com/mpv-player/mpv/files/9390301/mpv.log)
From my testing the HDR branch will be used for native HDR content displayed in PQ and the else branch will be used for SDR content mapped into PQ.

**Comment by EndlesslyFlowering** [comment]
OK I kinda have figured out what is going on. Both branches are applied for SDR->PQ. And at different stages it seems?
With the tweaked build the black levels are actually almost accurate, a bit too high though. So I made another build with these values:
```c
    if (space->hdr.min_luma <= 0 || space->hdr.min_luma > 100) {
        if (pl_color_transfer_is_hdr(space->transfer)) {
            space->hdr.min_luma = 1.0f; // Typical HDR black
        } else {
            space->hdr.min_luma = 10; // Typical SDR contrast
        }
    }
```
![mpv-shot0017](https://user-images.githubusercontent.com/19245343/185841389-64af8f1e-6bbf-4a46-8623-d065462cc5e4.png)
the black bars are pretty much perfectly 1.0 nits and the whole image is brightened. My guess is that the else branch gets executed first (in SDR space?) because of the brightened image and then afterwards the black levels are pulled back down to the HDR branch.
dithering and debanding were disabled to get an accurate reading of the black bars.
[mpv_.log](https://github.com/mpv-player/mpv/files/9391337/mpv_.log)

**Comment by haasn** [comment]
> The black bars are pretty much perfectly 1.0 nits and the whole image is brightened. My guess is that the else branch gets executed first (in SDR space?) because of the brightened image and then afterwards the black levels are pulled back down to the HDR branch. I guess the image is otherwise left untouched because it is too bright?

Okay, looking at this case (since it seems to be the most informative), here is the relevant part (the tone mapping algorithm) extracted:

First the conversion to linear light:
```glsl
[   0.212][d][vo/gpu-next] [ 81] const float _const_5_2 = 0.39907047152519226074; 
[   0.212][d][vo/gpu-next] [ 82] const float _const_6_2 = 0.44666817784309387207; 
...
[   0.212][d][vo/gpu-next] [102] // pl_shader_linearize           
[   0.212][d][vo/gpu-next] [103] color.rgb = max(color.rgb, 0.0); 
[   0.212][d][vo/gpu-next] [104] color.rgb = _const_6_2 * pow(color.rgb + vec3(_const_5_2), vec3(2.4)); 
```

This gives us a black level of `0.446 * pow(0.399, 2.4) = 0.04926`, which is exactly 10 nits. As expected. So the input (SDR) signal is now scaled from 10 nits to 203 nits.

Now for the tone mapping bits:
```glsl
[   0.242][d][vo/gpu-next] [ 29] const float _const_17_5 = 1.00000000000000000000; 
[   0.242][d][vo/gpu-next] [ 30] const float _const_18_5 = 0.04926108196377754211; 
[   0.242][d][vo/gpu-next] [ 31] const float _const_19_5 = -0.04663212597370147705; 
[   0.242][d][vo/gpu-next] [ 32] const float _const_20_5 = 1.04663217067718505859; 
...
[   0.242][d][vo/gpu-next] [ 93] color.rgb = clamp(color.rgb, _const_18_5, _const_17_5); 
[   0.242][d][vo/gpu-next] [ 94] #define tone_map(x) (_const_20_5 * (x) + _const_19_5) 
[   0.242][d][vo/gpu-next] [ 95] float ct_scale = 1.0 - 3.0 * _const_21_5;                      
[   0.242][d][vo/gpu-next] [ 96] float ct = _const_21_5 * (color.r + color.g + color.b);        
[   0.242][d][vo/gpu-next] [ 97] color.rgb = ct_scale * color.rgb + vec3(ct);          
[   0.242][d][vo/gpu-next] [ 98] color[0] = tone_map(color[0]); 
[   0.242][d][vo/gpu-next] [ 99] color[1] = tone_map(color[1]); 
[   0.242][d][vo/gpu-next] [100] color[2] = tone_map(color[2]); 
[   0.242][d][vo/gpu-next] [101] ct = _const_21_5 * (color.r + color.g + color.b);          
[   0.242][d][vo/gpu-next] [102] color.rgb = (color.rgb - vec3(ct)) / ct_scale;    
[   0.242][d][vo/gpu-next] [103] #undef tone_map 
```

So we first clamp to the range [10, 203] nits, as expected. We then define a tone mapping function as a linear map from `[10, 203]` to `[1, 203]`, again as expected. So this should stretch the black level down to 1 nits, as intended. (The CT stuff can be ignored)

We then delinearize this `[1, 203]` scaled signal straight into PQ, in theory giving us an output image that exactly has the requested `[1, 203]` output range. (Which your compositor should then further process into the correct monitor range, if the swapchain was tagged with the right metadata - something that [this MR](https://code.videolan.org/videolan/libplacebo/-/merge_requests/278) should implement)

I don't see anything obviously wrong there. It's possible that the only subjective difference in brightness you see from adjusting the SDR default is purely the result of the way BT.1886 responds to changes in the monitor black point. I suspect that if you repeat your testing with `--vf=format:gamma=gamma2.2`, the chosen SDR levels would no longer affect the output image at all.

**Comment by EndlesslyFlowering** [comment]
> I suspect that if you repeat your testing with `--vf=format:gamma=gamma2.2`, the chosen SDR levels would no longer affect the output image at all.
yes it doesn't affect the output image anymore.

> Which your compositor should then further process into the correct monitor range
I don't think Windows does this. Windows 11 just clips everything above your monitors range when set to HDR (if the correct metadata is provided...).

I made a new build based off of the latest mpv and libplacebo with [your MR](https://code.videolan.org/videolan/libplacebo/-/merge_requests/278) and your suggested patch for the HDR branch so that black levels are at `1e-6`. While the black point is not raised anymore which is great the image sadly remains just as washed out as before. The config in the first post with `vo=gpu` and `target-peak=90` which is about the same max brightness I set my OLED in SDR to gets really close in terms of matching the SDR output. This is probably down to processing differences of the TV. Trying `target-peak=90` with `vo=gpu-next` just washes the image out and makes it unwatchable in my eyes. screenshots with mpv's screenshot function 
I don't know what else to say than "this can't be right".

Here are some screenshots captured with the Game bar's screenshot function which gives HDR .jxr screenshots and then viewed in "HDR + WCG Image Viewer" to better illustrate the issue (these images are far from accurate but show the issue well):
[gpu.log](https://github.com/mpv-player/mpv/files/9397898/gpu.log):
![gpu](https://user-images.githubusercontent.com/19245343/186027703-362ee935-ede0-43cc-8504-d1813b9e832e.png)
[gpu-next.log](https://github.com/mpv-player/mpv/files/9397899/gpu-next.log):
![gpu-next](https://user-images.githubusercontent.com/19245343/186027747-60827635-d158-43f1-9ad1-50ec0d502e1b.png)

**Comment by ZaquL** [comment]
> Game bar's screenshot function which gives HDR .jxr

Nvidia broke it.

**Comment by EndlesslyFlowering** [comment]
OK well. I talked with some people and using `vf=format:gamma=gamma2.4` instead of the default BT.1886 makes gpu-next behave like gpu.
BT.1886 grabs this black point `space->hdr.min_luma = space->hdr.max_luma / 1000; // Typical SDR contrast` like you described which is definitely not 0 nits and works with it.
Thanks for sticking with my confusion :) 
I hope the patch for adjusting the black levels in HDR to 1e-6 will be merged soon as it is direly needed for inverse tone mapping or just mapping SDR into PQ!

**Comment by haasn** [comment]
I still don't understand why that patch would be needed for PQ output if we set the correct HDR metadata on the display device. The compositor/display should be in charge of tone-mapping the black point from the level we set to the level of the display.

**Comment by haasn** [comment]
@EndlesslyFlowering something else I'd be curious about you trying:

```diff
diff --git a/src/shaders/colorspace.c b/src/shaders/colorspace.c
index 24aa0c60..3a32c13c 100644
--- a/src/shaders/colorspace.c
+++ b/src/shaders/colorspace.c
@@ -1306,7 +1306,7 @@ static void tone_map(pl_shader sh,
 
     bool can_fixed = !params->force_tone_mapping_lut;
     bool is_noop = can_fixed && (!fun || fun == &pl_tone_map_clip);
-    bool pure_bpc = can_fixed && src_max == dst_max;
+    bool pure_bpc = false; // can_fixed && src_max == dst_max;
     bool dynamic_peak = false;
 
     if (state && !(is_noop || pure_bpc)) {
```

You might want to combine this with tone mapping function like `--tone-mapping=bt.2390`. Maybe this produces better results for the BT.1886 -> PQ conversion?

**Comment by EndlesslyFlowering** [comment]
> I still don't understand why that patch would be needed for PQ output if we set the correct HDR metadata on the display device. The compositor/display should be in charge of tone-mapping the black point from the level we set to the level of the display.

For native HDR content it doesn't end up 0.005 nits. From my testing it is first mapped to that though and later changed back to something close to 0 or even 0 as changing it to 1e-6 very slightly changes black levels.
For SDR mapping into PQ it doesn't and just relies on that value.

**Comment by haasn** [comment]
Oh, I guess I should keep this open until I know for sure where the bug lies.

**Comment by EndlesslyFlowering** [comment]
> @EndlesslyFlowering something else I'd be curious about you trying:
> 
> ```diff
> diff --git a/src/shaders/colorspace.c b/src/shaders/colorspace.c
> index 24aa0c60..3a32c13c 100644
> --- a/src/shaders/colorspace.c
> +++ b/src/shaders/colorspace.c
> @@ -1306,7 +1306,7 @@ static void tone_map(pl_shader sh,
>  
>      bool can_fixed = !params->force_tone_mapping_lut;
>      bool is_noop = can_fixed && (!fun || fun == &pl_tone_map_clip);
> -    bool pure_bpc = can_fixed && src_max == dst_max;
> +    bool pure_bpc = false; // can_fixed && src_max == dst_max;
>      bool dynamic_peak = false;
>  
>      if (state && !(is_noop || pure_bpc)) {
> ```
> 
> You might want to combine this with tone mapping function like `--tone-mapping=bt.2390`. Maybe this produces better results for the BT.1886 -> PQ conversion?

I used bt.2309: brightness wise it lands between the default BT.1886 and overwriting to 2.4. when overwriting this one to 2.4 it's darker than the normal 2.4 overwrite. The colours look a bit worse. Accuracy compared to previously is also worse.
Checked with another person and they confirm my findings.

**Comment by haasn** [comment]
Btw, I fixed a long-time issue where debanding raised the black point unnecessarily.

**Comment by EndlesslyFlowering** [comment]
nice, thanks!
I actually wanted to make a github issue because of this 😃 
with:
```ini
dither-depth=10
deband=yes
```
it's only switching between `0/1023` and `1/1023` for both mapping SDR into PQ (with the 1e-6 patch) and normal HDR passthrough. Depending on the OLED model and manufacturer the pixel might not turn on. On my LG 55C9 they are off.

**Comment by haasn** [comment]
So, I've decided to merge the ~~1e-6~~ [*1e-7* patch](https://code.videolan.org/videolan/libplacebo/-/merge_requests/282). That means the only remaining issue you have is an unexpectedly bright result due to BT.1886 still being adapted for SDR monitors despite your monitor being an OLED.

That is tracked in https://code.videolan.org/videolan/libplacebo/-/issues/223, but for now you can simulate it with `--vf=format=gamma2.4`. With that option, is your issue fully resolved?

**Comment by EndlesslyFlowering** [comment]
Yeah the issue is resolved with the current workaround! Thank you 🙂 
Like you mentioned in the 1e-7 MR, I know of no display that actually lowers the black point. Since the black point is not known.
And thanks for tracking the BT.1886 issue. Hopefully a good solution for that will be found.

**Comment by haasn** [comment]
Reopening since a work-around is not a solution.

**Comment by EndlesslyFlowering** [comment]
OK I found another issue that can't be fixed with `vf=format=gamma=gamma2.4`. 
With inverse tone mapping that overwrite crushes shadow detail way too much. Which means you are again stuck with this black point from the else branch being used: `space->hdr.min_luma = space->hdr.max_luma / 1000;`.
Changing the else branch to also use `1e-7` "fixes" this. (I did this before so that you wouldn't need that 2.4 gamma overwrite)
Interestingly enough you can safely use `vf=format:gamma=gamma2.4` for inverse tone mapping with this "fix".

I guess this is somewhat being tracked by the BT.1886 issue.

**Comment by haasn** [comment]
> I guess this is somewhat being tracked by the BT.1886 issue.

Yeah, exactly, I consider those two the same issue.

**Comment by haasn** [comment]
@EndlesslyFlowering https://code.videolan.org/videolan/libplacebo/-/merge_requests/284 should fix your BT.1886 black point issues.

**Comment by EndlesslyFlowering** [comment]
> @EndlesslyFlowering https://code.videolan.org/videolan/libplacebo/-/merge_requests/284 should fix your BT.1886 black point issues.
> 
> Could I ask you to test it, please?

Yeah sure 🙂. Made a test build with that patch:
SDR->PQ mapping now looks correct compared to `vo=gpu`.
invsere tone mapping now looks correct, no desaturation or else.
Compared against the SDR source colours also look correct.
Using `vf=format:gamma=gamma2.4` also doesn't produce issues for both SDR->PQ mapping and inverse tone mapping. It looks the same as not using it.

This looks great! Thank you very much 👍 

On a side note since you mentioned fixing debanding so it doesn't raise true black (0,0,0) anymore. Like I mentioned it still jitters between 0 and 1. Is there anything that can be done about that rather than disabling debanding or cropping the black bars?

**Comment by haasn** [comment]
> They have already disabled debanding which mitigates that issue.

They could just disable deband grain, probably.

> Like I mentioned it still jitters between 0 and 1. Is there anything that can be done about that rather than disabling debanding or cropping the black bars?

We could make the cutoff more aggressive. I'll throw you a patch. Feel free to open a separate issue to discuss it.
