### ISSUE TITLE
no window display when with gpu-api=vulkan and nvidia GPU in wayland

### ISSUE THREAD

**Issue by CoelacanthusHex** [mpv-player/mpv#10552]
### Important Information

Provide the following Information:
- MPV version: test in 0.34.1 and HEAD(https://github.com/mpv-player/mpv/commit/37aea112c15958052bcc6d0582593edf3bfead8f)
- libplacebo version: test in 4.208.0 and HEAD(https://github.com/haasn/libplacebo/commit/6ed1b0097460472c375a3e5ec22af0c1632123b9)
- Linux Distribution and Version: Arch Linux
- Window Manager and version: KDE Plasma 5.25.4 Wayland
- GPU driver and version: Nvidia 515.65.01 with Nvidia open source kernel driver
- GPU: NVIDIA GeForce RTX 3050 Laptop GPU

### Reproduction steps

`mpv --no-config --gpu-api=vulkan` with Nvidia GPU in Wayland (in three vulkan gpu context, only waylandvk happened)
if Nvidia is not default, please specify Nvidia GPU with `--vulkan-device=`

### Expected behavior

display window and play video and audio

### Actual behavior

no window display but display tray icon and play audio
and I found 
```
[vo/gpu/vulkan/libplacebo] vk->CreateSwapchainKHR(...): VK_ERROR_INITIALIZATION_FAILED (../src/vulkan/swapchain.c:577)
[vo/gpu/vulkan/libplacebo] Failed (re)creating swapchain!
```

### Log file

https://0x0.st/oLEp.txt

### Sample files

Any file with both video and audio.

**Comment by Dudemanguy** [comment]
Gonna assume this is just NVIDIA being NVIDIA.

**Comment by CoelacanthusHex** [comment]
It looks like some other conditions are needed for this to happen.

**Comment by suppai** [comment]
According to https://forums.developer.nvidia.com/t/negativo17-wayland-vkcreateswapchainkhr-returns-vk-error-initialization-failed/215593:

```
[ekurzinger](https://forums.developer.nvidia.com/u/ekurzinger)
[Employee](https://forums.developer.nvidia.com/g/Employee)
[Jun 8](https://forums.developer.nvidia.com/t/negativo17-wayland-vkcreateswapchainkhr-returns-vk-error-initialization-failed/215593/4)

There is an ABI incompatibility between the 515 driver and previous versions of our egl-wayland library which might be the cause of this. Updating to the latest version, 1.1.10, should resolve the issue if that is the case.

Going forward this should never happen again as we’ve eliminated the driver <=> egl-wayland ABI which the Vulkan WSI depended on. However, doing so required one final breaking change, unfortunately.
```

**Comment by Dudemanguy** [comment]
I assume nvidia fixed this upstream by now.

**Comment by Gigas002** [comment]
Still reproducible on current setup: 

```
mpv 0.35.0-391-gec58670a0d Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Fri May 19 01:52:15 2023
libplacebo version: v5.264.0-256-ga28c2b49
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```

- Linux Distribution and Version: Arch Linux
- Window Manager and version: KDE Plasma 5.27.5 Wayland
- GPU driver and version: Nvidia 530.41.03 proprietary
- GPU: NVIDIA GeForce RTX 3060 Laptop GPU

Commands: `mpv --no-config --gpu-api=vulkan` or `mpv --no-config --gpu-context=waylandvk`
