### ISSUE TITLE
How to kown the "real time"

### ISSUE THREAD

**Issue by NeilTohno** [mpv-player/mpv#10557]
Because I use " vf="spp=6:0:hard"" in mpv, I noticed "slow motion", and I don't known the "real time" (How much time it actually took to play the video).

https://github.com/NeilTohno/mpv_config2/blob/main/portable_config/input.conf
https://trac.ffmpeg.org/wiki/Postprocessing

example，
[![sqZLu.png](https://imglink.win/image/2022/08/20/sqZLu.png)](https://imglink.org/image/sqZLu)

Thanks.

**Comment by thebombzen** [comment]
Huh?

**Comment by NeilTohno** [comment]
> What are you actually asking?


Thanks, I have edited the content.

**Comment by thebombzen** [comment]
You still haven't asked a coherent question.

**Comment by NeilTohno** [comment]
> Thanks, I have edited the content.

Sorry for my poor english, I have edited the content again.

**Comment by NeilTohno** [comment]
> You still haven't asked a coherent question.

I‘m sorry for my poor english, I have edited the content again.

**Comment by qyot27** [comment]
You mean benchmarking?  So you just get the raw speed numbers in terms of how many frames the decoder can crunch through when it isn't limited to the idea that it's for playing back at a watchable speed.

It looks like any such options were removed from mpv, but with ffmpeg itself you can do:
```
ffmpeg -benchmark -i input.ext -f null /dev/null
```
or just
```
ffmpeg -i input.ext -f null /dev/null
```
or under bash, you can get the process timing info by using the `time` command:
```
time ffmpeg -benchmark -i input.ext -f null /dev/null
```
`/dev/null` would be `NUL:` on Windows.
