### ISSUE TITLE
How to create auto profile that will load based on videos codec and pixelformat?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#10551]
Hi,

I'm trying to create an auto profile that will load ONLY when the video info contains both H264 and yuv420p10

I did try myself but it didn't work? İf someone could please help me I would appreciate it.

```
[H264 10Bit]
profile-cond=p["video-codec"]=="h264" and p["video-params/pixelformat"]=="yuv420p10"
vf=format=yuv420p
```

**Comment by guidocella** [comment]
`~=` is not equal, you need `==` to check equality.

**Comment by erickyun** [comment]
> `~=` is not equal, you need `==` to check equality.

but this doesn't also work?
```
profile-cond=p["video-codec"]=="h264" and p["video-params/pixelformat"]=="yuv420p10"
```

I tried only `p["video-params/pixelformat"]=="yuv420p10` that seems to work but I want the auto profile to only load if it is AVC/h264 video. I don't want the profile to load for HEVC/h265

**Comment by guidocella** [comment]
Use `video-format`.

**Comment by erickyun** [comment]
> Use `video-format`.

Thank you for your answer that worked for me.
