### ISSUE TITLE
Is it possible to run as a SRT-stream receiver server (listen to incoming connections)?

### ISSUE THREAD

**Issue by z-s-e** [mpv-player/mpv#10560]
With ffmpeg one can do something like `ffmpeg -i "srt://0.0.0.0:9998?pkt_size=1316&mode=listener" output.mkv` to receive such a stream. I'm wondering if I can use mpv to directly play those back live. Thanks

**Comment by thebombzen** [comment]
You can use `av://` to play back anything that libavdevice supports.

**Comment by z-s-e** [comment]
Hm, I just tried `mpv "srt://0.0.0.0:9998?pkt_size=1316&mode=listener"` again, and it worked. I could have sworn that it didn't previously, but never mind then. Thx
