### ISSUE TITLE
[Guide]  Better out of the box experience for (good) HDR displays 

### ISSUE THREAD

**Issue by mnisius** [mpv-player/mpv#10565]
# Better out of the box experience for (good) HDR displays 

I have an HDR display (Sony LCD TV. 1500 nits brightness) and I struggled to get the a good picture out of mpv for different kind of videos. Because of that I played with a lot of different config values and thought it may help others if I share my knowledge. I hope it is ok if I submit it as a github issue. 

This guide will distinguish between SDR, HDR and Dolby Vision because currently I need different Settings for each of them. 

#### Base Config

```properties
#Because I want high quality
profile=gpu-hq
# Because it can play DoVi and is faster
vo=gpu-next 
#Hardware acceleration (faster, less energy consumption) 
hwdec=auto-copy 
#interpolation because 24hz videos look way better 
video-sync=display-resample 
interpolation=yes 
#HDR passtrough: Important for HDR & DoVi playback, no downside for SDR so always on
target-colorspace-hint=yes
```
#### Toggle SDR/HDR with one click 
I recommend this very convenient tool to toggle between SDR and HDR mode in Windows 
https://github.com/res2k/HDRTray

## Play HDR videos
With my base config HDR should just work. 

 * Activate HDR mode in Windows
 * Play HDR video
 * Enjoy

## Play Dolby Vision videos
I don't know why but DoVi videos are played like SDR videos. 
To force proper HDR output you need this config

```properties
[HDR_MODE:DOVI]
profile-restore=copy
#Automatically enables profile if DoVi video is played. Seems to work but maybe there a better way? 
profile-cond=(p["video-dec-params/gamma"] == "auto")
target-trc=pq
target-prim=bt.2020
#Adjust this to the peak brightness of your display. e.g. 800 for LG CX
target-peak=1500 
#Only necessary if you are switching between different profiles like me SDR_TO_HDR tonemap profile
tone-mapping-mode=auto
```
With this config you can 

 * Activate HDR mode in Windows
 * Play DoVi video
 * Enjoy

## Play SDR videos
**SDR videos in Windows HDR Mode look washed out and the black level is rasied!**

The easiest way to get good looking SDR video playback is quite simple. 

### The correct way 
 * Activate SDR Mode in Windows
 * Play SDR video
 * Enjoy

### SDR mode like picture in HDR mode 
If you want to have hdr mode ebaled but still want your video to look as it would in SDR Mode you can use this profile

```properties
[HDR_MODE:SDR]
profile-restore=copy
target-trc=pq
target-prim=bt.2020
#Seems to be some kind of magic number, higher values do not have any effect 
target-peak=207 
tone-mapping=bt.2390
tone-mapping-mode=rgb
inverse-tone-mapping=yes
```

 * Activate HDR Mode in Windows
 * Play SDR video
 * Activate Profile: [HDR_MODE:SDR]
 * Enjoy

### SDR to HDR Tone mapping 
Did you know that you can tonemap your sdr movies to hdr movies with mpv? Well now you do. 😀
I really like this effect and watch a lot if movies and tv shows with this settings. See for yourself if you like it or not

```properties
[HDR_MODE:SDR_HDR_EFFECT]
profile-restore=copy
target-trc=pq
target-prim=bt.2020
# Higher value = stronger effect
target-peak=406 
tone-mapping=spline
# All other values make the colors look awful in my opinion. 
tone-mapping-mode=rgb 
inverse-tone-mapping=yes
```

 * Activate HDR Mode in Windows
 * Play SDR video
 * Activate Profile: [[HDR_MODE:SDR_HDR_EFFECT]]
 * Enjoy

## How to activate profiles on runtime
You have to edit your input.conf file like this. 
I added shortcuts to play with the target-peak as well. 
```
CTRL+1         apply-profile HDR_MODE:DOVI
CTRL+Shift+1   apply-profile HDR_MODE:DV restore

CTRL+2         apply-profile HDR_MODE:SDR
CTRL+Shift+2   apply-profile HDR_MODE:SDR restore

CTRL+3         apply-profile HDR_MODE:SDR_HDR_EFFECT
CTRL+Shift+3   apply-profile HDR_MODE:SDR_HDR_EFFECT restore

CTRL+WHEEL_UP      add target-peak 1
CTRL+WHEEL_DOWN    add target-peak -1
```

**Comment by mnisius** [comment]
Well I don't have a blog and I thought an issue would give other people the possibility to comment, discuss and maybe improve this guide. I mean this is also for questions why not for guides? 

But sure I can also create a wiki page. Can anyone do this or how does that work?

**Comment by ZaquL** [comment]
> ```ini
> Seems to be some kind of magic number, higher values do not have any effect 
> ```

203 nits is the SDR level in HSR 1000 nits render. 10000 nits will have a different media point.

**Comment by laichiaheng** [comment]
Can we see this article in WIKI?
Can it work on Linux? I know that MPV can pass-through HDR contents in DRM mode.

**Comment by GrabbenD** [comment]
Bump
Are there any newer versions of this guide?

**Comment by mnisius** [comment]
Hey no. Did you have any problems with the guide ? I mostly used this config with maybe small adjustments like enabling vulkan before I sold my tv.

**Comment by gsarkardev** [comment]
I had to set `gpu-api=vulkan` when playing HDR media, otherwise the content played incredibly choppily. I have Nvidia MX250 card, with i5 10210U. Leaving this in case this benefits someone else.

**Comment by 103Sakamoto** [comment]
Thanks a lot! Saved my life for the SDR config, was bother by the brightness shifts.

**Comment by Nope12369** [comment]
Can't get the profile keybinds to work. will leaving the sdr to hdr tone map settings on all the time mess with native HDR videos? or does it only affect SDR ones
