### ISSUE TITLE
mpv drop frames in the end of all videos when draining AO

### ISSUE THREAD

**Issue by osama-re** [mpv-player/mpv#10566]
- mpv version: master 6c1f01d
- nixos-unstable
- the problem was introduced in 52aed49
- the problem still exist with bf5c19e
- Sway (master)

mpv drop frames in the end of all videos.

Reverting commits 52aed49, bf5c19e solves the issue.

[log file](https://0x0.st/o9ST.txt)

**Comment by philipl** [comment]
@t-8ch

**Comment by sfan5** [comment]
Can't really confirm this, opening a new video seems to be reset the displays stats but I didn't see anything in the log either.
Tested by `mpv -v sample.mp4{,,,}` or `mpv sample.mp4` and dropping a different video on mpv

**Comment by philipl** [comment]
I tried playing a random normal video and it dropped the last three frames at the end. So there's something going on. Maybe it's specific to the end of a video with nothing queued up after it.

**Comment by osama-re** [comment]
> Maybe it's specific to the end of a video with nothing queued up after it.

No, i tried with a playlist, mpv is dropping frames int the end off all videos.

**Comment by t-8ch** [comment]
Which AOs are you using?

Maybe we are draining the ao on the wrong thread and blocking the playthread?

**Comment by t-8ch** [comment]
I can reproduce it only on pull AOs `pipewire` and `jack`. On `pulse` and `alsa` it's fine.

**Comment by osama-re** [comment]
I compiled with ```pipewire```, but in the log it's using ```pulse```?

**Comment by osama-re** [comment]
On my system ```pulse``` is enable through ```pipewire``` emulation.

**Comment by t-8ch** [comment]
@osama-re You need to explicitly specify pipewire if you want to use it with `--ao=pipewire`.

**Comment by t-8ch** [comment]
I can resolve this issue and not break ao_is_playing(pull_ao) with this change:
```patch
diff --git a/player/audio.c b/player/audio.c
index 92408ebf99..06ea1262a6 100644
--- a/player/audio.c
+++ b/player/audio.c
@@ -945,8 +945,6 @@ void fill_audio_out_buffers(struct MPContext *mpctx)
                           (opts->gapless_audio && !ao_untimed(ao_c->ao))))
         {
             MP_VERBOSE(mpctx, "audio EOF reached\n");
-            if (mpctx->ao)
-                ao_drain(mpctx->ao);
             mpctx->audio_status = STATUS_EOF;
             mp_wakeup_core(mpctx);
         }
diff --git a/player/playloop.c b/player/playloop.c
index 91badf0647..a63e9b6142 100644
--- a/player/playloop.c
+++ b/player/playloop.c
@@ -1190,6 +1190,8 @@ static void handle_eof(struct MPContext *mpctx)
         !mpctx->stop_play)
     {
         mpctx->stop_play = AT_END_OF_FILE;
+        if (mpctx->ao)
+            ao_drain(mpctx->ao);
     }
 }
```

It feels fairly ugly however to put it directly into the playloop.

**Comment by philipl** [comment]
@t-8ch While that change does avoid dropped frames, in the process of testing this, I've come to realise that the original change (and your patch here) do break gapless audio playback - which we thought might happen but which I tested and didn't notice problems originally. This time I tested again and there was an audible gap.

So we need to take a different approach.

One thing I noticed in my testing is that if a vo change is required when switching between files (eg, files have cover art), then ao reinitialization happens even without your original patch. IT's only when there's no vo that it goes wrong. So maybe there is some necessary logic that only happens when a vo is in use.

**Comment by philipl** [comment]
uau did some investigation and concluded that the original problem of the ao not reinitialising was due to a lack of a wakeup event in `ao_read_data` when it needs draining.

```patch
diff --git a/audio/out/buffer.c b/audio/out/buffer.c
index 2a69596597..11bd14f733 100644
--- a/audio/out/buffer.c
+++ b/audio/out/buffer.c
@@ -193,6 +193,7 @@ int ao_read_data(struct ao *ao, void **data, int samples, int64_t out_time_us)

     if (pos < samples && p->playing && !p->paused) {
         p->playing = false;
+        ao->wakeup_cb(ao->wakeup_ctx);
         // For ao_drain().
         pthread_cond_broadcast(&p->wakeup);
     }
diff --git a/player/audio.c b/player/audio.c
index 92408ebf99..5c26148acb 100644
--- a/player/audio.c
+++ b/player/audio.c
@@ -945,8 +945,8 @@ void fill_audio_out_buffers(struct MPContext *mpctx)
                           (opts->gapless_audio && !ao_untimed(ao_c->ao))))
         {
             MP_VERBOSE(mpctx, "audio EOF reached\n");
-            if (mpctx->ao)
-                ao_drain(mpctx->ao);
+            //if (mpctx->ao)
+                //ao_drain(mpctx->ao);
             mpctx->audio_status = STATUS_EOF;
             mp_wakeup_core(mpctx);
         }
```

**Comment by t-8ch** [comment]
@philipl  This indeed fixes the issues and looks like the better fix. Thanks to uau!

**Comment by osama-re** [comment]
i tested #10569, and the issue is gone.
