### ISSUE TITLE
Loop ONLY short videos by X times?

### ISSUE THREAD

**Issue by masterofobzene** [mpv-player/mpv#10562]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

-----------------------------------------------------------------------------------------

Is there any way to tell mpv to loop only videos shorter than XX:XX, by X times until next?

**Comment by hooke007** [comment]
```ini
[loop_1]
profile-cond = p.duration<=60
profile-restore = copy
loop = 4
```

**Comment by UnixCro** [comment]
The first thing I asked was the same question, but with a bit of logic I came up with the idea of simply changing the `--loop` parameter in the console to `--loop=X`. Life can be so easy …
