### ISSUE TITLE
Profile for dropped frames

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#10567]
I'm using mpv with the most demanding video settings and user shaders,
and often times there are dropped frames,
for example: on 60fps videos, so I have a profile for that:
```
[60fps]
profile-cond=p["container-fps"]>49
glsl-shaders-remove="~~/FSRCNNX_x2_16-0-4-1.glsl"
profile-restore=copy
```
Problem is that it's not just 60fps videos, and I rather not create a profile for each one of the conditions that cause mpv to drop frames.
It would be easier to create a profile that will detect X number of dropped frames.
I found this `decoder-frame-drop-count` and `frame-drop-count`, but I have no idea which one to choose and how to correctly use it in a profile, and I would like some help with that.

**Comment by Obegg** [comment]
```
[Dropped Frames]
profile-cond=p["frame-drop-count"]>10
glsl-shaders-remove="~~/FSRCNNX_x2_16-0-4-1.glsl"
profile-restore=copy
```

**Comment by hooke007** [comment]
note:
The num of `frame-drop-count` would be cleaned each time you seek.

**Comment by Obegg** [comment]
True, I've noticed that, it's a good solution so far, I like it.
