### ISSUE TITLE
mpv freezes on macOS Ventura beta 13.0 Beta 5 (22A5331f) after update

### ISSUE THREAD

**Issue by MrCrispyBacon** [mpv-player/mpv#10579]
Hi there, 
just updated yesterday my macbook pro with the new macOS Ventura 13.0 Beta 5, version 22A5331f….and  Im using the mpv 0.34.1 and it’s freezing my mac as soon as I start watching a movie with it….
I’ve been using mpv for years and yesterday I was on macOS Ventura 13 Beta 4….so something changed  the behavior of mpv 0.34.1 as Apple continues to update macOS Ventura….mpv  freezes the image and keeps freezing completely the mac when on fullscreen after a few seconds of starting a movie or something....
I removed mpv, reinstalled  it, removed the mpv.config, same thing happened... installed it with Homebrew and continues to  freeze all the time…have to close mpv because snowballs and freezes…

Please, can anyone be kind to help me with this issue?

A attached my log file link + a vid of the issue
Thanks in advance

Video:
https://user-images.githubusercontent.com/112277451/187046269-51030d5a-574a-4c90-bf2c-388958c912f3.mp4

 
mpv log file:
https://drive.google.com/file/d/1lmsPRHSq-80qK0YZeZ_W_LslPzNHdQ-K/view?usp=sharing

**Comment by Akemi** [comment]
i am not going to support a beta OS. please report the issue again if it still persists on a release or golden master version of macOS.

**Comment by Coeur** [comment]
Confirmed,
- current MPV (0.34.1 and from sources) is broken on macOS Ventura.
- IINA works: https://github.com/iina/iina
- VLC works: https://code.videolan.org/videolan/vlc

**Comment by selsta** [comment]
@Coeur IINA has the same issue for me.

**Comment by ViktoriiaKh** [comment]
Calling CATransaction.flush() from the background thread causes the UI freeze
https://github.com/mpv-player/mpv/blob/211ce69f74214f8f9d2225df5b683718bab2f60d/video/out/mac/gl_layer.swift#L220

**Comment by stolendata** [comment]
@MrCrispyBacon @Coeur @selsta 

Since the issue popped up with Beta 5, but did not manifest in Beta 4, it's best to wait for Ventura release candidate to see what happens.

**Comment by ViktoriiaKh** [comment]
The issue has appeared in macOS 13.0 Beta (22A5331f). It is Beta **6**. There is a typo in the issue title and description.
Here is a sample of the mpv process [Sample of mpv.txt](https://github.com/mpv-player/mpv/files/9444623/Sample.of.mpv.txt).

**Comment by MrCrispyBacon** [comment]
**IINA 1.3.0 Build 132 and mpv 0.34.1 have the same issue on macOS Ventura 13.0 beta 7 (22A5342f)** 

Problem not solved yet....guess updates for both apps will be an option as  continuously lagging and freezing tons....That's a bugger!!!

**Comment by low-batt** [comment]
From the descriptions coming in so far I'm unclear on whether this is exactly the same problem that Beta 6 had, or if Apple reverted that change, but then attempted to accomplish the change in a different way and introduced a similar regression. One person indicated it is not just mpv and IINA that are having trouble with Beta 7.

Apple doesn't usually care about problems in 3rd party software. You have to bombard Apple with feedback to get noticed. Please report this to Apple using the Feedback Assistant app and be sure to mention it is a regression.

I've been checking the mpv project to see if anyone is discussing Beta 7 yet. So far I've only seen your same post to the mpv issue.

**Comment by Coeur** [comment]
The issue appeared in Beta 6.
The issue was reported, but too late for Beta 7. Hopefully next build.

**Comment by low-batt** [comment]
@Coeur Thank you for the update. Some of the reports I was hearing made it sound like there was a different problem in Beta 7. Glad to hear a confirmation it is the same problem and a fix is still on the way.

**Comment by Coeur** [comment]
Verified fixed on Beta 8 (22A5352e). 🎉

**Comment by low-batt** [comment]
Great news! Thanks for confirming.

**Comment by MrCrispyBacon** [comment]
after Ventura beta 8 is even worst as completely freezes the mac with no possibility of controlling it...forcing shutdown is impossible!

[mpv.log](https://github.com/mpv-player/mpv/files/9639537/mpv.log)

**Comment by ddddavid-he** [comment]
I thought it was finally fix in beta 8, but it crashed again today and even froze the entire macOS system.

**Comment by Coeur** [comment]
I did not experience such thing, @MrCrispyBacon and @ddddavid-he. But don't forget to fill a Feedback Assistant.

**Comment by MrCrispyBacon** [comment]
mpv and IINA same result....freezing macOS system...and Ventura final version will be released in October and nothing changed...for more that we can complain about it,  the issue is still here and absolutely nothing is being done...

Start updating the apps because Apple won't fix it!!!

**Comment by Akemi** [comment]
> #10579
> 
> mpv and IINA same result....freezing macOS system...and Ventura final version will be released in October and nothing changed...for more that we can complain about it, the issue is still here and absolutely nothing is being done...and at the moment is worst than ever!
> 
> Start updating the apps because Apple won't fix it!!!
> 
> Meanwhile Im downloading VLC coz way too much inconvenience

aren't you being a bit overdramatic here? surely something has been done. see PR #10585 from @Coeur and the reasoning why it hasn't been merged in the comments. so there is a solution for you, just build the linked PR. otherwise you have to wait for the usual release cycle.

you have to understand you are on a beta OS and you can't expect everything to work there. if you have problems it's you own damn fault or the one of Apple.

on a side note, you behave like a total jerk with such statements towards all the people that try to solve the problem or already have a solution for it.

i am locking the comments because i am have no desire to prolong this any further. just open a new issue of the problem still persists on a GM release or the actual release.
