### ISSUE TITLE
Cannot change volume when using Wiimote

### ISSUE THREAD

**Issue by nike4613** [mpv-player/mpv#10577]
### Important Information

mpv version: 0.34.0 (chocolatey build 2021.11.01)
Window 10 21H2

### Reproduction steps

1. Set up a Wiimote to act as a cursor with a Dolphin bar
2. Attempt to change the volume in mpv

### Expected behavior

Able to change the volume

### Actual behavior

Unable to change the volume

### Known workarounds

- Use a PS3 controller instead

**Comment by LaserEyess** [comment]
Can you capture the keycodes used by the wiimote when pressing the "volume buttons"?

**Comment by nike4613** [comment]
Figured out a solution, turns out that the Dolphin bar has an option to bind buttons to the mouse instead of the keyboard, and there are scroll wheel bindings.
