### ISSUE TITLE
All tone mapping algorithms 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#10570]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I am just wondering if someone can list all the tone mapping algorithms what are supported by mpv when using vo=gpu as tonemapping-help does not work on my device 

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by CounterPillow** [comment]
```
mpv --tone-mapping=help
```

**Comment by Jamie666123** [comment]
> mpv --tone-mapping=help

This dose seem to do anything

**Comment by Jamie666123** [comment]
Dosent

**Comment by hooke007** [comment]
Isn't it in the doc?
https://mpv.io/manual/master/#options-tone-mapping

**Comment by CounterPillow** [comment]
> This dose seem to do anything

Yes it does.
