### ISSUE TITLE
Limiting watch later count

### ISSUE THREAD

**Issue by Akhilesh-T** [mpv-player/mpv#10583]
Is there a way to limit the watch later/recent files list, say 100?

**Comment by avih** [comment]
mpv doesn't have such option.

However, you can delete all watch later files except for the 100 newst ones with this shell line:
```sh
cd ~/.config/mpv/watch_later/ && ls -1tr | head -n -100 | xargs -d '\n' rm -f --
```

See this for explanation https://superuser.com/a/554512
