### ISSUE TITLE
Is it possible to enable OpenType tabular figures for the OSD font?

### ISSUE THREAD

**Issue by enkeling** [mpv-player/mpv#10586]
‘Segoe UI Variable’ is the new system font for Windows. The previous ‘Segoe UI’ used tabular numbers by default, whereas this new version uses proportional numbers by default which make the width of the time counters change every second. You can see it in the attached screenshots.

### Expected behavior of the wanted feature

In CSS you can set the property `font-variant-numeric: tabular-nums;` on elements such as timers to get a clean behaviour. Or `font-feature-settings` to toggle Opentype features. In XAML you set `Typography.NumeralAlignment`. Maybe it would be possible to have options to use tnum for OSD and pnum for subtitles?

### Alternative behavior of the wanted feature
I saw in mpv/player/lua/stats.lua that you use monospace to gain tabular figures in the timers. Maybe it would be alternatively possible to set the OSD to have monospace timers?

### Screenshots
![mpv-proportional](https://user-images.githubusercontent.com/71015677/187254342-2f50a3ee-458a-41f0-b63f-9397a256b4b9.png)
![mpv-tabular](https://user-images.githubusercontent.com/71015677/187254352-527c3482-a20e-49ac-8b7b-4fdb141b1ff5.png)

**Comment by avih** [comment]
> Is it possible to enable OpenType tabular figures for the OSD font?

You can choose any font you want for the OSD, but you can't make it use one font for some codepoints, and another font for other codepoints.

Use `--osd-font=whatever` to change the OSD (and OSC) font.
