### ISSUE TITLE
Why is WM_CLASS `"gl", "mpv"` in X11? Would it be possible to change to "mpv" ?

### ISSUE THREAD

**Issue by Eolien55** [mpv-player/mpv#10580]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
(not relevant)

On X11, mpv has a WM_CLASS of  `"gl", "mpv"`. This causes problem with [scripts that thrive to be compatible on both X11 and Wayland](https://todo.sr.ht/~mil/sxmo-tickets/529). Is it possible to change WM_CLASS to `"mpv", "mpv"`?

**Comment by Dudemanguy** [comment]
On x11, the WM_CLASS is basically set as "rendering-backend" (gl, mpvk, etc.), "mpv". It's always been like this as far as I know (contrary to what that issue says about this being a recent change). I'm not actually sure why this would be a problem for any script reading xprops though? You still have the "mpv" string in there which I presume is what one would normally want.

**Comment by Eolien55** [comment]
Oh, I thought it was somewhat recent due to the script not working.

The script takes the app_id for wayland and the first part of WM_CLASS to match against different applications names.

This issue doesn't really makes sense then
