### ISSUE TITLE
gpu-next absolute colorimetric icc or lut produces red tint

### ISSUE THREAD

**Issue by 24fpsDaVinci** [mpv-player/mpv#10581]
mpv master
libplacebo master
fedora 36

under vo=gpu-next, #ffffff white has visible red tint when icc-intent=3 or a lut based profile with absolute colorimetric using lut-type=conversion

does not occur under vo=gpu

![gpu-next](https://user-images.githubusercontent.com/3499141/187199556-ffb1f940-c416-4193-a272-614e7ee5a1c3.jpg) 
vo=gpu-next
![gpu](https://user-images.githubusercontent.com/3499141/187199557-21b5dcea-3019-4fea-8dcb-d3b578e9ed18.jpg)
vo=gpu

**Comment by haasn** [comment]
insufficient information to reproduce

**Comment by 24fpsDaVinci** [comment]
> insufficient information to reproduce
steps to reproduce:
1. set icc profile,  icc-intent=3, vo=gpu-next

alternate steps to preproduce:
1. generate a 3dlut using above icc using option absolute colorimetric + white point scaling
3. set lut, lut-type=conversion, vo=gpu-next

**Comment by haasn** [comment]
> set icc profile, icc-intent=3, vo=gpu-next

works for me (tm)

**Comment by 24fpsDaVinci** [comment]
> 

are you also getting the same issue?

**Comment by 24fpsDaVinci** [comment]
> > set icc profile, icc-intent=3, vo=gpu-next
> 
> works for me (tm)

sorry, not sure what you mean. are you also getting the same issue?

**Comment by 24fpsDaVinci** [comment]
> Using the ICC Profile you provided, I get this:
> 
> ```
> $ mpv --no-config av://lavfi:color=white --vo=gpu-next --gpu-api=vulkan --icc-profile=2.2\ M-S\ XYZLUT+MTX1553.icc --icc-intent=3
>  (+) Video --vid=1 (wrapped_avframe 320x240 25.000fps)
> VO: [gpu-next] 320x240 yuv420p
> [vo/gpu-next/vulkan/libplacebo] Failed opening ICC profile... ignoring
> V: 00:00:02 / 00:00:03 (65%)
> ```
> 
> so I can't reproduce it but it can't read the ICC profile you provided.

sorry about that, I reuploaded the profile.
[profile-reupload.zip](https://github.com/mpv-player/mpv/files/9447411/profile-reupload.zip)

**Comment by thebombzen** [comment]
```
$ sha256sum 2.2\ M-S\ XYZLUT+MTX1553.icc 2.2M-SXYZLUT+MTX1553.icc 
c0ba5d0eef2dbf9f28d29c3cc8ee2776ef420b83b31e2f2308c6199e792499c4  2.2 M-S XYZLUT+MTX1553.icc
c0ba5d0eef2dbf9f28d29c3cc8ee2776ef420b83b31e2f2308c6199e792499c4  2.2M-SXYZLUT+MTX1553.icc
```
Profile is the same

**Comment by 24fpsDaVinci** [comment]
> ```
> $ sha256sum 2.2\ M-S\ XYZLUT+MTX1553.icc 2.2M-SXYZLUT+MTX1553.icc 
> c0ba5d0eef2dbf9f28d29c3cc8ee2776ef420b83b31e2f2308c6199e792499c4  2.2 M-S XYZLUT+MTX1553.icc
> c0ba5d0eef2dbf9f28d29c3cc8ee2776ef420b83b31e2f2308c6199e792499c4  2.2M-SXYZLUT+MTX1553.icc
> ```
> 
> Profile is the same

i thought the original file was corrupt, here is a different profile.
[profile3.zip](https://github.com/mpv-player/mpv/files/9447466/profile3.zip)

**Comment by thebombzen** [comment]
Same problem.

**Comment by 24fpsDaVinci** [comment]
> 

I included some more info, i still cannot produce the same results as you with icc-intent=3 and the same profile, here is
[mpv.log](https://github.com/mpv-player/mpv/files/9447954/mpv.log)

![mpv-shot0001](https://user-images.githubusercontent.com/3499141/187299851-a4832859-0c3c-4789-ab1a-a04afe3ab4e1.jpg)
`mpv --no-config --gpu-api=vulkan --keep-open --icc-profile="/home/xps13/.local/share/icc/DellXPSNoCCSS 2022-08-26 20-55 2.2 M-S XYZLUT+MTX1553.icc" --vo=gpu-next --icc-intent=3 /home/xps13/Downloads/187288583-ee183aa2-e656-4023-9004-e403ca0a6274.png`

![mpv-vogpu](https://user-images.githubusercontent.com/3499141/187301746-b10b2412-ed3d-4a06-8bfa-5fe7053883af.jpg)
`mpv --no-config --gpu-api=vulkan --keep-open --icc-profile="/home/xps13/.local/share/icc/DellXPSNoCCSS 2022-08-26 20-55 2.2 M-S XYZLUT+MTX1553.icc" --vo=gpu --icc-intent=3 /home/xps13/Downloads/187288583-ee183aa2-e656-4023-9004-e403ca0a6274.png`

![Screenshot from 2022-08-29 17-11-13](https://user-images.githubusercontent.com/3499141/187299894-84d7f14d-d0be-483a-9986-0d8370c13333.png)
overlayed on top of your absolute colorimetric image

**Comment by 24fpsDaVinci** [comment]
for future references, for gpu-next and icc-intent=3, the icc profile has to be created with explicit chromaticity coordinates, no idea why "as measured" profile in displaycal works with vo=gpu but not gpu-next. the solution also applies to lut profiles. closing now thank you.
