### ISSUE TITLE
gpu-next: Invisible subtitles when video track(s) are disabled

### ISSUE THREAD

**Issue by MoSal** [mpv-player/mpv#10594]
### Important Information

| software | version |
| -- | -- |
| mpv | 0f30b0757fb969455119d83d3f29dec3d66f6c9c |
| libplacebo | 0f30b0757fb969455119d83d3f29dec3d66f6c9c |

### Reproduction steps

```
mpv --no-config --no-video --force-window=immediate  --vo=gpu-next --sid=1 tos_sample.mkv
```

### Expected behavior

Subtitles show up as expected without ` --vo=gpu-next`.

### Actual behavior

Subtitles are not shown.

`video-sync` does not need to be set to `display-resample` to trigger this issue ;)

### Sample files

Not sample-specific, but here is one anyway:
https://archive.org/download/unsorted_files/tos_sample.mkv

**Comment by thebombzen** [comment]
I can reproduce this with `$ mpv --no-config --no-video --force-window=immediate --sid=1 --vo=gpu-next tos_sample.mkv` but not with `$ mpv --no-config --no-video --force-window=immediate --sid=1 --vo=gpu tos_sample.mkv`.

**Comment by hooke007** [comment]
Reason: https://github.com/mpv-player/mpv/pull/9870
