### ISSUE TITLE
Unable to bind F13 key onwards in input.conf

### ISSUE THREAD

**Issue by rp1231** [mpv-player/mpv#10595]
### Important Information

Provide following Information:
- mpv version:
- Windows Version: Windows 11
- Source of the mpv binary: Shinichiro's builds

### Reproduction steps

Try to bind F13-F24 keys onwards to any option

### Expected behavior
The option should work if you press the F13-F24 keys

### Actual behavior
It doesn't work

### Log file

```
[input] Unknown key 'F17' at C:/Program Files/MPV/MPV-EASY Player/mpv/mpv/input.conf:7
[input] Unknown key 'F18' at C:/Program Files/MPV/MPV-EASY Player/mpv/mpv/input.conf:8
mpv 0.34.0-438-g0f30b0757f Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Wed Aug 31 06:21:29 2022
FFmpeg library versions:
   libavutil       57.34.100
   libavcodec      59.42.103
   libavformat     59.30.100
   libswscale      6.8.104
   libavfilter     8.46.103
   libswresample   4.9.100
FFmpeg version: git-2022-08-29-4fce3bab6
```

**Comment by hooke007** [comment]
What's its keyname in `mpv --input-test --force-window --idle` ?

**Comment by hooke007** [comment]
There is no msg showed that you clicked f13. Don't move your mouse and just click `f13`.

**Comment by haasn** [comment]
@hooke007 it's `0x21ff81` on my end. (In `xev` I get `keysym 0x1008ff81, XF86Tools`)

**Comment by t-8ch** [comment]
There does not seem to be any support in mpv for F>12
https://github.com/mpv-player/mpv/blob/master/input/keycodes.c#L66

It should be fairly straight forward to add though.
At least up to F31. Then there will be keycode conflicts.

**Comment by haasn** [comment]
Adding the definitions to mpv will not solve the problem, you also have to update all the platform-specific code to integrate it into the windowing systems.

Do a search through the repository for `MP_KEY_F` to find a list of locations that need to be updated, with details possibly depending on the platform. Off hand I can tell you that X11, for example, goes up to `XK_F35`.

**Comment by t-8ch** [comment]
Indeed! But somebody will have to do it.

The fastest way forward will probably be to do it yourself.

Sep 1, 2022 14:09:38 rp1231 ***@***.***>:

**Comment by t-8ch** [comment]
Indeed! But somebody will have to do it.

The fastest way forward will probably be to do it yourself.
