### ISSUE TITLE
av_md5_sum: trying to replicate watch_later hashes in python

### ISSUE THREAD

**Issue by chapmanjacobd** [mpv-player/mpv#10609]
Good day,

I'm trying to understand this part of the code: https://github.com/mpv-player/mpv/blob/d433c5d655b79c957dde329b7fa6f58e7f16021d/player/configfiles.c#L215

I read in an old issue that the `watch_later` filenames are md5 hashes of the file path, but maybe that has changed since that was written.

Is `av_md5_sum()` referencing this ? https://ffmpeg.org/doxygen/0.5/md5_8c-source.html

Is there a known way to replicate that hash function in python? 

I'm assuming `md5sum` and python md5 are the same....

```
.config/mpv/watch_later $ cat AF10B54FA2B1240EC99019F982A2E407 
# /home/xk/d/77_Library/Star Wars - Episode I A Vergence in the Force.mkv
start=3178.775000
fullscreen=yes
af=scaletempo=speed=tempo,acompressor=ratio=4,loudnorm
$ realpath '/home/xk/d/77_Library/Star Wars - Episode I A Vergence in the Force.mkv' | md5sum
a9c3ea9df22b62ed7ea9a183d977d8a1  -
```

```
AF10B54FA2B1240EC99019F982A2E407
a9c3ea9df22b62ed7ea9a183d977d8a1
```

they do not seem to match... ?

My reason for doing this is that I plan on computing the hash of an arbitrary list of files (fewer than 120 paths) and check if there are any matches in the `watch_later` folder. I'm exploring the idea of bubbling up some of that info or using it to prioritize playing unfinished files in my small CLI media center https://github.com/chapmanjacobd/lb/ This happens before `mpv` is loaded

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

Here is my `mpv/config`:

```
script-opts=''
script-opts-append=osc-title=${filename}
script-opts-append=autocrop-auto=no
script-opts-append=excerpt-no-pause-on-file-loaded=1
script-opts-append=osc-windowcontrols=no
script-opts-append=ontop-level=window
ontop=yes
screenshot-directory=~/d/92_Cool/
screenshot-template=mpv-%F-%P
keepaspect
watch-later-options-remove=pause
write-filename-in-watch-later-config
geometry=100%:100%
autofit=50%x40%
alang=ja,jp,jpn,de,deu,ger,eng,en,enUS,en-US,English
slang=en,eng
blend-subtitles=yes
volume=100
volume-max=200
demuxer-mkv-subtitle-preroll=yes
sub-ass-vsfilter-blur-compat=no
sub-fix-timing=yes
sub-auto=fuzzy
sub-gauss=1.0
sub-gray=yes
quiet=yes
save-position-on-quit
demuxer-seekable-cache=yes
demuxer-max-bytes=500MiB
demuxer-readahead-secs=180
af="scaletempo2,lavfi=[pan=1c|c0=0.5*c0+0.5*c1],volume=replaygain-track"
sub-fix-timing=yes
replaygain=track
```

**Comment by avih** [comment]
> they do not seem to match... ?

Probably because you confused `realpath` var name at the mpv source code with the unix command `realpath`.

By default, the md5 is of the exact argument mpv was invoked with, for instance if you run
```sh
mpv path/to/foo.mkv
```
then to get the watch-later file name you need:
```sh
printf %s path/to/foo.mkv | md5sum | tr a-z A-Z
```
and if you invoked exactly the same file differently, e.g. `path/../path/to/foo.mkv` then this is exactly the string you'd need for the md5.

**Comment by avih** [comment]
> $ realpath '/home/xk/d/77_Library/Star Wars - Episode I A Vergence in the Force.mkv' | md5sum
> a9c3ea9df22b62ed7ea9a183d977d8a1  -

Also, the realpath command adds a newline - which md5sum will calculate into the result too. You need the md5 to be calculated only on the name which mpv got, without additional newline.

**Comment by kolayne** [comment]
> Probably because you confused `realpath` var name at the mpv source code with the unix command `realpath`.
> 
> By default, the md5 is of the exact argument mpv was invoked with, for instance if you run
> 
> ```shell
> mpv path/to/foo.mkv
> ```
>
> and if you invoked exactly the same file differently, e.g. `path/../path/to/foo.mkv` then this is exactly the string you'd need for the md5.

@avih, and why is that the behavior? It breaks the playback resume in so many cases:
- Using a different path for the same file (e.g. absolute/relative path, or even accidentally typing a double slash in the path instead of a single one),
- First playing a video by symlink and then playing the same file directly,
- Playing a symlink after it has changed (which may be overcame with `--resume-playback-check-mtime` but it's an additional option I need to manually enable),
- and, probably, more.

Is there any reason why the `realpath()` from stdlib.h is not used?

**Comment by chapmanjacobd** [comment]
Normalizing the path but *not* resolving symlinks might be a good compromise

Similar to:

```
realpath -se
```

https://unix.stackexchange.com/questions/577426/how-can-i-make-realpath-never-resolve-symlinks
