### ISSUE TITLE
Play/Pause with TWS headphones put on/take off

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#10606]
TWS headphones support put on to play, take off to pause, It works with Youtube in edge browser. But with MPV, take off triggered the `PLAYPAUSE` in `input.conf`, put on does nothing.

**Comment by thebombzen** [comment]
Do you know what key is triggered at all when you put on these headphones?

**Comment by Natural-Harmonia-Gropius** [comment]
I don't know.

With `mpv --input-test --force-window --idle` when I take off it only shows `PLAYPAUSE`. nothing with put on.
```
[input] Key PLAYPAUSE is bound to:
[input] 1.  'cycle pause' in <builtin>:1 (default)
[input] 2.  'cycle pause' in D:/OneDrive/应用/mpv/portable_config/input.conf:80
```

**Comment by Natural-Harmonia-Gropius** [comment]
I think it's not a KeyboardEvent, mpv have same behaviors as `window.addEventListener("keydown", (event) => { console.log(event) });`

Should this issue keep open?

**Comment by thebombzen** [comment]
You can use some third-party software like AutoHotKey to log all events to see what sort of event it looks like, but if mpv doesn't have it registered then `--input-test` won't be able to detect it. See recent patches about F13 through F25 as an example. (Windows doesn't have this feature built-in, unfortunately.)

**Comment by Natural-Harmonia-Gropius** [comment]
[Media Session API](https://chromestatus.com/feature/5639924124483584) can handle this.

might be useful: https://github.com/WebKit/WebKit/blob/main/Source/WebCore/platform/audio/PlatformMediaSession.h

**Comment by qwerty12** [comment]
One of the plugins that integrate mpv with Windows' media controls might enable this as a "side effect": 

* https://github.com/datasone/MPVMediaControl

* https://github.com/x0wllaar/MPV-SMTC

**Comment by Natural-Harmonia-Gropius** [comment]
> * https://github.com/datasone/MPVMediaControl

it Works
