### ISSUE TITLE
cache-pause-initial doesn't work on FLAC audio stream 

### ISSUE THREAD

**Issue by hyperknot** [mpv-player/mpv#10619]
### Important Information

Provide following Information:
- mpv version: mpv 0.34.1
- macOS Version: 11.6.8
- Source of the mpv binary or bundle: https://laboratory.stolendata.net/~djinn/mpv_osx/

### Reproduction steps
I'm trying to wait for buffering for 10 seconds when starting an internet radio stream (audio-only). It works on most streams but not on the following FLAC stream: http://stream.radioparadise.com/flacm

Command is simply: 
```
mpv http://stream.radioparadise.com/flacm
```

I tried everything in the config:
```
cache-pause-initial=yes
cache-pause-wait=10

# just in case
cache=yes
cache-secs=10
cache-pause=yes
demuxer-thread=yes
demuxer-readahead-secs=10
demuxer-cache-wait=yes
demuxer-max-bytes=3M
demuxer-max-back-bytes=3M
```

### Expected behavior
It should wait for 10 secs before starting playback.

### Actual behavior
It starts playing immediately. Randomly it actually displays buffer is 10s/1M but it must be fake, as it starts playing immediately (~0.3 sec).

It displays: `Invalid audio PTS: 0.371519 -> 10104429.180227` as a warning.

### Log file
[mpvout.log](https://github.com/mpv-player/mpv/files/9502004/mpvout.log)

**Comment by ZaquL** [comment]
> http://stream.radioparadise.com/flacm

Is that MQA stream? Because normal flac is just on http://stream.radioparadise.com/flac

**Comment by hyperknot** [comment]
m is just for metadata (artist - track). The behaviour is the same with the non-m version.

**Comment by thebombzen** [comment]
That's not what `--cache-pause-initial` and `--cache-pause-wait` do. It waits for 10 seconds of *available* audio to exist before it starts playing. It doesn't wait 10 seconds of real time.

**Comment by hyperknot** [comment]
That's what I want, 10 seconds of available audio so that network condition fluctuations won't break the audio stream. Currently mpv starts playing instantly on that FLAC stream, waiting absolutely nothing. There is absolutely no available audio stream on that radio stream.
