### ISSUE TITLE
How many Lua/JS scripts are too many?

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10613]
I use mpv.net for video, audio and images and need a lot of functionality. So far I have about 10 mpv scripts, most self authored, but I still need more functionality and wonder if it would cause performance or stability issues if a user had 20-40 scripts? What I do at the moment is putting small features I expect not being popular in a single private script. I currently learn to use (Ubuntu) Linux and find it quite enjoyable, I will have to use it regularly in order to gain a deeper understanding, which means I need to port various functionality from C# to Lua and will end up with more mpv scripts. Here is an example mpv.net feature I will add to my private script, I called it 'Quick Bookmark', it's probably not described very quell because I'm not good at writing:

> On the first press a bookmark is saved, on the second press it is restored and removed. When a new file is loaded the bookmark is removed.

```C#
public static void QuickBookmark()
{
    if (App.QuickBookmark == 0)
    {
        App.QuickBookmark = (float)Core.GetPropertyDouble("time-pos");

        if (App.QuickBookmark != 0)
            Core.Command("show-text 'Bookmark Saved'");
    }
    else
    {
        Core.SetPropertyDouble("time-pos", App.QuickBookmark);
        App.QuickBookmark = 0;
    }
}
```

Some of my scripts are only 20-30 lines of code, most are 100-200 lines.

https://github.com/stax76/mpv-scripts

**Comment by avih** [comment]
> How many Lua/JS scripts are too many?

When you feel it degrades performance - that's too many.

mpv doesn't have a counter or a threshold where it degrades things above some numebr of scripts. So as long as you have enough system resources to run them, that's not too many.

Each script runs in its own thread and typically uses few hundreds KB of RAM, and very little CPU (depending on each script, obviously).

Bottom line, don't worry about it until things start degrading.
