### ISSUE TITLE
Mpv Temporarily Stops Playback After Resuming from a Paused State

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#10616]
### Important Information

Provide following Information:
- mpv version: 0.34.1 (latest)
- macOS Version: 12.5.1 (latest)
- Source of the mpv binary or bundle: mpv.io
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

If I pause a video on mpv and leave it paused for some time, when I resume playback the video starts initially, then stops for a bit then starts again. It wasn't reproducible with --no-config, but I didn't leave it paused that long so I'm not certain it's not reproducible.

### Expected behavior

Video resumes normally after it is paused.

### Actual behavior

Video resumes, then stops, then resumes again.

### Log file

https://pastebin.pl/view/raw/21d5ff79

**Comment by Akemi** [comment]
is it always reproducible? what kind of video was it, local or remote? is the log from a run with the problem? if it's not reproducible of --no-config which options cause the problem?

for now it sounds more like a system hiccup, like bottlenecked io, cache, etc

**Comment by Akemi** [comment]
please try to reproduce it with --no-config if possible. i would like to narrow down the source of the problem.

problem could be related to any of the scripts you are using like mpv_thumbnail_script for example, for example.

**Comment by george-emerald** [comment]
I'm sure it's not mpv_thumbnail_script because the problem existed before I installed it.

**Comment by george-emerald** [comment]
I'm trying to reproduce it with --no-config right now, however. I'll get back to you as soon as I've done it.

**Comment by george-emerald** [comment]
It's not reproducible with --no-config as far as I can tell.

**Comment by Akemi** [comment]
then it would be really helpful which option, script, etc is causing your problem. that would help narrowing down the problem.

**Comment by george-emerald** [comment]
And how would I find that out?

**Comment by Akemi** [comment]
look what is in your config and try everything that is in there alone and in combinations.

**Comment by george-emerald** [comment]
You want me to disassble my entire config and look at each thing by itself? That's an insane amount of work plus I'd risk losing my conifg.

**Comment by Akemi** [comment]
i am not sure why you would risk losing your config? make a backup or use mpv on the command line with --no-config and setting the option on the command line.

guess how much work it would be for me, without knowing your config, trying to reproduce your problem and then finding the problematic option? if you don't want to look at it that's fine by me, but then the possibility of solving the problem at hand are very slim.

**Comment by christoph-heinrich** [comment]
You could do a binary search with your config.

Delete the first half of your config, if the problem still persists, restore first half and delete second half.
Once you found which half causes the problem, delete the first half of that half etc.

**Comment by george-emerald** [comment]
Honestly both the terminal and the binary search are way too much work, since in order to reproduce the problem I have to leave the video on a paused state for a while. I guess I just have to live with it.

**Comment by george-emerald** [comment]
For anyone wondering, I did end up fixing this. As @Akemi initially suggested it's cause by cache. I fixed it by enabling cache (for some reason it's not on by default in the Mac OS builds) and extending its capacity.

**Comment by garoto** [comment]
> I fixed it by enabling cache.

Share exactly what you added to your .conf that fixed your very specific issue. Anything `cache` related is disabled for anything that mpv detects as being "local media".

**Comment by george-emerald** [comment]
This is what I added:
```
cache # Enable caching
demuxer-max-bytes=500M # Increase the cache size
demuxer-max-back-bytes=100M
```

**Comment by george-emerald** [comment]
It could also be fixed with `no-cache-pause` since `cache-pause` is the cause, but I think my solution is better and much less forceful. This would just force it to continue playing without any cached data, which is sure to cause issues.

**Comment by Cananbolt** [comment]
I too have the same problem. There is like a 1-second audio delay when unpaused for a certain amount of time. Unfortunately, I tried both methods (that worked for you) which I put onto mpv.conf, but it didn't work. Were you able to find another solution? It happens all the time, which is super inconvenient cause I have to rewind a couple of seconds because I missed the audio.
