### ISSUE TITLE
Resize mpv window freely without being locked to aspect ratio

### ISSUE THREAD

**Issue by jupiter104** [mpv-player/mpv#10610]
### Expected behavior of the wanted feature
Being able to resize mpv windows both horizontally and vertically without being locked to a specific aspect ratio.

For instance, I was playing an audiobook mp3 file and it has a square shaped album cover image. I'm unable to resize the window horizontally. As a result, I end up with a horizontally long window and black boxes on the sides as shown in the screenshot below.

![1428](https://user-images.githubusercontent.com/24752210/188296504-704d0bb9-c816-4d69-bea8-b4d697cdd8eb.jpg)

**Comment by avih** [comment]
https://mpv.io/manual/master/#options-no-keepaspect-window

**Comment by jupiter104** [comment]
> https://mpv.io/manual/master/#options-no-keepaspect-window

Thank you. This is working great.
