### ISSUE TITLE
Supporting .itt text files

### ISSUE THREAD

**Issue by mbarton96** [mpv-player/mpv#10622]
Expected Behavior of the Feature:

I would like to be able to use the MPV player to show .itt file formats with the increase in streaming channels that require a variety of subtitle formats it has become more of an importance to be able to support further file formats. It would be nice to be able to play back the .itt files in the same way that .srt files are able to be played now plus the added functionality of being able to dictate where the titles are viewed. Either in the top or bottom third of the screen.

Alternative Behavior:

No top or bottom options. Just the ability to view the files in the player.

**Comment by thebombzen** [comment]
You'd need to add an ITT decoder to libavcodec first, which is outside the scope of mpv.
