### ISSUE TITLE
Have the track selection in the OSC hidden sometimes

### ISSUE THREAD

**Issue by ColonelGerdauf** [mpv-player/mpv#10621]
### Expected behavior of the wanted feature

What I am hoping for is for MPV to have a mechanism that can prohibit the user from selecting the audio track of "none" in the OSC, specifically when audio is playing. 

That is an example use case where "none" will cause more problems than it is worth. When you hit "none" on the OSC when music is playing, the music stops in its tracks, and any other audio that you play via MPV will get instantly skipped. Especially when the appropriate settings are not in place, this will lead to an immediate shutdown of MPV as a program immediately after it launches. This will be a major nuisance, especially for those that choose to use MPV or one of the many front-end packages as a mainstay music player.

### Alternative behavior of the wanted feature

Alternatively, though less ideal, an option can be provided to users to selectively hide or show the track button in the default OSC, on a general basis.

**Comment by thebombzen** [comment]
Does this solve the issue? https://github.com/viniciusbm/mpv-cycle-through-existing/blob/master/cycle-through-existing.lua
