### ISSUE TITLE
Question Concerning Config

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#10623]
I have a question about the code in mpv.conf. I'd like to know if all options by themselves and set to yes are equivalent. For example, I know `sub-bold` and `sub-bold=yes` are exactly the same thing, but does that work for all options that are set to yes? I want to know so I can clean up the code a bit.

**Comment by CounterPillow** [comment]
From the manual:

> Every flag option has a no-flag counterpart, e.g. the opposite of the --fs option is --no-fs. **--fs=yes is same as --fs**, --fs=no is the same as --no-fs.

as in, yes, this is true for every yes/no option.

**Comment by george-emerald** [comment]
Oh OK. Thanks, now I can clean up the code!
