### ISSUE TITLE
Little crackling/popping on Linux ARM64.

### ISSUE THREAD

**Issue by HanoJing** [mpv-player/mpv#10639]
### Important Information

- mpv version: 0.34.1-r1
- Linux Distribution and Version: Gentoo GNU/Linux ARM64; Kernel: 5.19.7 (SolidRun Vendor Kernel (https://github.com/SolidRun/linux-stable/tree/linux-5.19.y-cex7-dev)
- Source of the mpv binary: Gentoo GNU/Linux `gentoo` repository
- Window Manager and version: Suckless' dwm (https://github.com/bakkeby/dwm-flexipatch)
- GPU driver and version: AMDGPU AMD Radeon RX580 XFX driver from linux-firmware-20220815

### Reproduction steps

Play music, hear little poppling/crackling

### Expected behavior
Sound plays without poppling/crackling
### Actual behavior
Sound plays with little poppling/crackling
### Log file

https://0x0.st/oOHy.txt

### Important Notes

Motherboard: SolidRun HoneyComb LX2K
CPU: NXP LayerScape LX2160A ARM Cortex-A72
GPU: AMD Radeon RX580 XFX

I use the 5.19.7 SolidRun Vendor Kernel that only works with a recent and specific UEFI image.
The Sound didn't crackle/pop with the 5.15.10 Vendor Kernel and the older UEFI image.
I am able to reproduce crackling/popping on the PINE64 RockPro64 too (https://www.pine64.org/rockpro64/) but a lot less than what I get on the HoneyComb.
I am not able to reproduce this issue on a Thinkpad X230 both with just alsa running and pipewire running.

The issue disappears on my HoneyComb when I open SuperTuxkart for example but not neccesarily when the GPU is under higher load.

Crackling/popping happens especially with the song: `Clean Bandit ft. Ellie Goulding - MAMA (Kertscher Remix)`

I verified that this only happens with mpv. This does not happen with Freetube, Youtube in Firefox, nor ffplay.

The same popping/crackling is reproducible on Void Linux (mpv version: 0.34.1 and armtix(mpv version: 0.34.1-5)(https://armtixlinux.org) aswell as Fedora 36 (mpv version:0.34.1-3).

on my HoneyComb, I get sound from my GPU, over Displayport, to 3.5mm headphone jack speakers.
On The RockPro64 I get sound over its Analog output, straight to the 3.5mm jack.

I tried some options out, regarding audio, to maybe set a value that the GPU likes. It maybe fixable this way.

Thank you all very much in advance.

**Comment by thebombzen** [comment]
What happens if you use `--ad=mp3`?

**Comment by HanoJing** [comment]
That doesn't sadly doesn't fix it. By the way, all the Music I test with is in the mp3 format.

**Comment by thebombzen** [comment]
Also, what happens if you play the song off youtube, from mpv? e.g. `mpv 'ytdl://https://www.youtube.com/watch?v=yNWFtWDnD8A'`

**Comment by HanoJing** [comment]
Thanks alot for the idea! 

Playing it like this: `mpv 'ytdl://https://www.youtube.com/watch?v=yNWFtWDnD8A'` does not cause crackling as the graphics card is under higher load. 

Playing it like this: `mpv --no-video 'ytdl://https://www.youtube.com/watch?v=yNWFtWDnD8A'` does cause crackling.

**Comment by HanoJing** [comment]
The fix for this is to set `amdgpu.pcie_gen_cap=0x4` in the `GRUB_CMDLINE_LINUX_DEFAULT=` in `/etc/default/grub`.

**Comment by flightmansam** [comment]
I have the same symptoms using mpv on ARM (unrelared to the bug but for context I am using the app [Feishin](https://github.com/jeffvli/feishin/issues/968)).

```
Model:          Apple MacBook Pro (16-inch, M1 Pro, 2021)
Distro:         Fedora Linux Asahi Remix 42 (Forty Two [Adams])
Kernel:         6.14.8-400.asahi.fc42.aarch64+16k
Kernel build:   #1 SMP PREEMPT_DYNAMIC Fri May 30 20:27:54 UTC 2025
```
I think it had something to do with pipewire though... 

I was able to fix by adding the parameter `--audio-device=pulse`
