### ISSUE TITLE
How to set Auto Conditional Profile for mkv files that are 30fps or below?

### ISSUE THREAD

**Issue by Cananbolt** [mpv-player/mpv#10632]
### Important Information

Provide following Information:

mpv-0.34.1-x86_64
Windows 10
https://sourceforge.net/projects/mpv-player-windows/files

### Reproduction steps
Using this in mpv.conf

```
[profile_for_mkv_files]
profile-desc="profile for .mkv files"
profile-cond=filename:match"[.]mkv$" ~= nil 
and get("specified-fps", <31
and get("estimated-vf-fps")<31)
profile-restore=copy
~Any shaders
```
### Expected behavior
Only mkv files that are **30 fps and below** are affected by the shaders

### Actual behavior
**All** mkv files are affected

**Comment by thebombzen** [comment]
```
[profile_for_mkv_files]
profile-desc=cond:(string.match(get("filename", ""), "%.mkv$")~=nil) and (tonumber(get("container-fps", 0)) <= 30)
```

**Comment by Cananbolt** [comment]
Unfortunately, this did not work

**Comment by hooke007** [comment]
`profile-desc` did nothing in a profile

It might be `profile-cond=string.match(get("filename", ""), "%.mkv$")~=nil) and tonumber(get("container-fps", 0)) <= 30`

**Comment by Cananbolt** [comment]
Unfortunately, this too did not work. Thank you for trying.

**Comment by hooke007** [comment]
Emm, no idea. Perfectly works here.

**Comment by Cananbolt** [comment]
> Emm, no idea. Perfectly works here.

I tried it again, and this time, it worked perfectly. Thank you so much.
