### ISSUE TITLE
Wayland: transparent border

### ISSUE THREAD

**Issue by rtentser** [mpv-player/mpv#10638]
### Important Information

- mpv 0.34.0-464-gb9c7e5b5ff
- Manjaro KDE
- Source of the mpv binary: chaotic-aur
- kwin/wayland
- mesa 22.1.6, radeon

![Screenshot_20220913_005616](https://user-images.githubusercontent.com/34958119/189725862-2db7b096-8bd3-4d2c-bd07-df3f9d7d82fc.png)

![Screenshot_20220913_010349](https://user-images.githubusercontent.com/34958119/189724883-ac5e9899-e97a-4a4a-b52f-0eae868279d6.png)
bf5779ae.png)

### Reproduction steps

Run plasma wayland session, start some video in mpv. 

### Expected behavior

No transparent borders

### Actual behavior

There will be transparent border at upper and left of window (most noticeable at fullscreen). Not reproduceable in plasma x11.

**Comment by christoph-heinrich** [comment]
What's your kwin version? I've experienced the same thing a few months ago, but it has been fixed since then.

**Comment by rtentser** [comment]
5.24.6

**Comment by christoph-heinrich** [comment]
I think that's duplicate of #10240.

I'm surprised that your on such an old version on Manjaro, since it's based on Arch, which currently has 5.25.5.

**Comment by Dudemanguy** [comment]
Yeah I'm pretty certain this is that old plasma bug that was later fixed. Feel free to reopen it if I'm wrong.

**Comment by rtentser** [comment]
Thanks!

**Comment by rtentser** [comment]
Yeah, the update helped
