### ISSUE TITLE
Official binary and build packages added as Windows ARM64

### ISSUE THREAD

**Issue by RockLakeGrass** [mpv-player/mpv#10631]
### Expected behavior of the wanted feature

There is a built Windows ARM64 binary package

I have built MPV binary packages from CLANGARM in MSYS2, but there are still some problems, such as the lack of lua51.

Attachment: Self-Built binary package
[mpv-2.zip](https://github.com/mpv-player/mpv/files/9542082/mpv-2.zip)

**Comment by avih** [comment]
> There is a built Windows ARM64 binary package

mpv does not provide binaries for any platform, including Windows ARM64.

> but there are still some problems, such as the lack of lua51

You can also use lua 5.2 or luajit.
