### ISSUE TITLE
Crash on using vf=vapoursynth with vulkan api

### ISSUE THREAD

**Issue by Silver-Fullbuster** [mpv-player/mpv#10637]
### Important Information

Provide following Information:
- mpv version - 
```
mpv 0.34.0-455-g535cd6f313 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sun Sep 11 12:26:47 2022
FFmpeg library versions:
   libavutil       57.36.101
   libavcodec      59.42.104
   libavformat     59.30.101
   libswscale      6.8.112
   libavfilter     8.48.100
   libswresample   4.9.100
FFmpeg version: git-2022-09-10-925ac0da3
```
- Windows Version - Windows 10 21H2 - Build 19044.1889
- Source of the mpv binary - Shinchiro Weekly Builds (x86_64 v3)
- If known which version of mpv introduced the problem - mpv-x86_64-v3-20220911-git-535cd6f

Last working version - mpv-x86_64-v3-20220904-git-d433c5d

### Reproduction steps

`mpv --no-config --vf=vapoursynth=double.vpy -gpu-api=vulkan <video-file> --log-file=D:\mpvlog.txt`

Using d3d11 works
Using vulkan without vapoursynth works
Using both vulkan and vapoursynth crashes

### Expected behavior

Video plays normally

### Actual behavior

MPV crashes with no error in logfile

### Log file

[mpvlog.txt](https://github.com/mpv-player/mpv/files/9544870/mpvlog.txt) 

Working with d3d11:
[mpvlog2.txt](https://github.com/mpv-player/mpv/files/9544891/mpvlog2.txt)

### Sample files

[double.vpy.txt](https://github.com/mpv-player/mpv/files/9544874/double.vpy.txt)

**Comment by haasn** [comment]
Can't reproduce, it works for me. Can you try running mpv from the command line to see if it prints any error before crashing?

**Comment by Silver-Fullbuster** [comment]
No errors when using the CLI, it simply crashes without an error

**Comment by Silver-Fullbuster** [comment]
The latest build from Shinchiro no longer reproduces the issue, closing
