### ISSUE TITLE
Streaming and Seeking Problem

### ISSUE THREAD

**Issue by emrakyz** [mpv-player/mpv#10642]
- Platform: High-end desktop PC (nvidia GPU) with a low ping ethernet network connection (100 megabits/s).
- OS: Arch Linux with the standard linux kernel and linux-headers; all recently updated.
- Using cloudflare DNS (1.1.1.1). I have also tried default DNS or VPN connections.
- I recently installed 'MPV' and 'ffmpeg' through Arch Linux Package Manager with `pacman -Syyu ffmpeg mpv`. Then I also recently installed 'yt-dlp' through GitHub.
- I don't use any scripts for MPV and my mpv.conf file has:
```
--vo=gpu
--gpu-api=vulkan
--hwdec-codecs=all
--hwdec=nvdec
--cache=yes
--sub-font='Arial'
--sub-scale=0.7
--cache-secs=1200
--script-opts-append=ytdl_hook-try_ytdl_first=yes
```
Normally, MPV works great. But for streaming content from the network; downloading speed is really slow and seeking takes considerably longer time than on the browser. The speeds I get:

Downloading speed in 'yt-dlp': **~13.000kbps**
Streaming speed on the browser (librewolf): **~5.000kbps** / Seeking is instant (**0.01s**) even in **8K60FPS** videos.
Streaming speed on MPV: **~250kbps** / Seeking can take **up to 15** seconds for longer videos (3hr 1080p video). It's impossible to watch a video with 2.14x speed without stuttering.

Downloading with yt-dlp and piping it to MPV with `yt-dlp 'https://www.youtube.com/watch?v=abc' -o - | mpv -` seems to solve the issue but then I can't see the sections of the video and can't seek ahead.

I am aware that this problem has nothing to do with MPV directly but I am hoping to get recommendations from the developers and the other users in terms of improvements. I don't mind power efficiency or high network bandwidth usage if that would be the case. 

Thanks for the great software.

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/issues/8655#issuecomment-1199733728

**Comment by emrakyz** [comment]
> [#8655 (comment)](https://github.com/mpv-player/mpv/issues/8655#issuecomment-1199733728)

`--ytdl-format=best` works amazing. Instant seeking and extremely fast downloading speed. Is this because of we don't need ffmpeg here since we have a a video that also has audio?

It's sad that the biggest resolution with audio and video on YouTube is 720p. I wish to find a way for higher resolutions too.

Thanks!

**Comment by guidocella** [comment]
Youtube just decided not to throttle the streams with both video and audio, presumably for compatbility with old devices that can only play those.

For 1080p someone needs to implement downloading 10MB at a time in ffmpeg.
