### ISSUE TITLE
video track behavior in a playlist 

### ISSUE THREAD

**Issue by JimPancakes** [mpv-player/mpv#10641]
I have a playlist which contains videos that each have 3 video tracks in them.
Just want to know if when I change to the second video track of the current video, can mpv automatically take that into account and later go directly to the second video track of the next item in the playlist?

Is there anything in mpv that can help me get even a little close to something like that?

**Comment by thebombzen** [comment]
If you use `mpv --vid=2 video1.mkv video2.mkv video3.mkv` (or `mpv --vid=2 playlist.m3u`) then it will apply `--vid=2` to all of them.

**Comment by JimPancakes** [comment]
> If you use `mpv --vid=2 video1.mkv video2.mkv video3.mkv` (or `mpv --vid=2 playlist.m3u`) then it will apply `--vid=2` to all of them.

Thank you.

Any way to put this code in the playlist file itself or is this just for the mpv.conf file?
I am on Windows, sorry for not mentioning that.

**Comment by thebombzen** [comment]
You can't set arbitrary options in playlist files. However, if the video language is tagged, you could always do something like `--vlang=eng,en`

**Comment by guidocella** [comment]
You can enable `use-filedir-conf` in `mpv.conf` and create a `playlist.m3u.conf` file with `vid=2`.
