### ISSUE TITLE
memory command usage

### ISSUE THREAD

**Issue by yangpenglove** [mpv-player/mpv#10643]
### Important Information

Provide following Information:
- mpv version latest 0.34.1
- macOS Version 12.4
- Source of the mpv binary or bundle
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

I am using mpv on macOS with qt, I want to use mpv to play video file but cached in memory, after checking documents, I found "memory" command, but when I tried to use it, mpv report "Command 'memoey' not found.".

My question is how to pass a data to mpv and play it. thanks very much.  

### Expected behavior
Play video buffer
### Actual behavior
Command 'memoey' not found.
### Log file

Here is code sample:

QFile mediaFile(file);
mediaFile.open(QFile::ReadOnly);
auto bytes = mediaFile.readAll();
QVariantList params;
params <<"memory" << bytes;
mpv::qt::command_variant(_mpv, params);

Make a log file made with -v -v or --log-file=output.txt. If you use the Bundle
from a version later than 0.32 a default log is created for your last run at
~/Library/Logs/mpv.log. You can jump to that file via the Help > Show log File…
menu. Paste the log to https://0x0.st/ or attach it to the github issue, and
replace this text with a link to it.

In the case of a crash please provide the macOS Crash Report (Backtrace).

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Akemi** [comment]
i don't think there is a memory command. there is a memory protocol though (memory:// https://github.com/mpv-player/mpv/blob/master/stream/stream_memory.c)

**Comment by yangpenglove** [comment]
Thanks Akemi, finally I find mpv_stream_cb_add_ro is what I want.

**Comment by Akemi** [comment]
you are welcome, even though i didn't really do much. can this issue be closed then?

**Comment by yangpenglove** [comment]
yes, please close it.
