### ISSUE TITLE
Log playback of each video

### ISSUE THREAD

**Issue by snoitallicso** [mpv-player/mpv#10651]
As example log like:

```
16-09-2022 14:23-14:33 /home/user/Downloads/video1.mp4
16-09-2022 14:40-14:51 /home/user/Downloads/video1.mp4
16-09-2022 15:00-15:20 /home/user/Downloads/video1.mp4
17-09-2022 15:00-16:40 /home/user/Downloads/cinema.mkv
```

I propose to log the playback time (even with acceleration) or the played time (absolute).

```
16-09-2022 14:23-14:33 20min /home/user/Downloads/video1.mp4
16-09-2022 14:40-14:51 11 min /home/user/Downloads/video1.mp4
16-09-2022 15:00-15:20 40min /home/user/Downloads/video1.mp4
17-09-2022 15:00-16:40 25 min /home/user/Downloads/cinema.mkv
```

It is also important to ignore just rewind or forward and backward steps

**Comment by stax76** [comment]
I wrote a script this week, which has the columns 1, 3 and 4.

https://github.com/stax76/mpv-scripts/blob/main/history.lua

In the wiki is:

https://github.com/yuukidach/mpv-scripts/blob/master/history-bookmark.lua
https://gist.github.com/Abject-Web/3f4f0e85dad73303b9dd1ef1f55c3147
https://gist.github.com/garoto/e0eb539b210ee077c980e01fb2daef4a
https://github.com/Eisa01/mpv-scripts#simplehistory
https://github.com/hacel/recent

**Comment by Dudemanguy** [comment]
I don't think history-type functionality like this is likely to make into core mpv, but I think various userscripts do the job for you and are the right solution.
