### ISSUE TITLE
Gnome wayland, cannot open new video by drag and drop files into MPV window

### ISSUE THREAD

**Issue by truongan** [mpv-player/mpv#10650]
### Important Information

Provide following Information:
- mpv version: 
```
$ mpv --version
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100 (runtime 57.28.100)
   libavcodec      59.18.100 (runtime 59.37.100)
   libavformat     59.16.100 (runtime 59.27.100)
   libswscale      6.4.100 (runtime 6.7.100)
   libavfilter     8.24.100 (runtime 8.44.100)
   libswresample   4.3.100 (runtime 4.7.100)
FFmpeg version: n5.1.1
```
- Linux Distribution and Version: ``` archlinux ```
- Source of the mpv binary: Archlinux's official repository: https://archlinux.org/packages/community/x86_64/mpv/
- Window Manager and version:
```
$ gnome-shell --version
GNOME Shell 42.4
```
- GPU driver and version
```
$ vulkaninfo 
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.226
```

### Reproduction steps
1. Make sure wayland is running, I don't encounter this issues on Xorg
2. Open any video in mpv
3. While the video is playing, open a file manager (nautilus is the default on gnome, but thunar had also been tried). 
4. Drag and drop another video file into mpv window

### Expected behavior
MPV switch to playing the newly dropped file.
### Actual behavior
The current video kept playing as if no Drag-and-drop had happened
### Log file

Make a log file made with --log-file=output.txt and here it is:
[output.txt](https://github.com/mpv-player/mpv/files/9585318/output.txt)

**Comment by Dudemanguy** [comment]
I'm fairly sure this works on the master branch. Could you try it real quick?

**Comment by truongan** [comment]
> I'm fairly sure this works on the master branch. Could you try it real quick?

Confirm! I just try a quick git build with the help of Archlinux AUR and the problem was gone. I should have searched the closed issue more carefully next time.
