### ISSUE TITLE
Implement mp.template_string

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#10656]
Like the `show-text "foo bar ${property}"` will print a parsed string in osd, that what I want to call a function to get that parsed string.

```js
function mp.template_string(string) {
    return `string`
}

mp.template_string("${property_name}")
```

**Comment by avih** [comment]
https://mpv.io/manual/master/#command-interface-expand-text

```lua
function mp.template_string(str) {
    return mp.command_native({"expand-text", str})
}
```

For example of usage from a script, see also the DOCS for `expand-path`.
