### ISSUE TITLE
file picker do not list subtitle files (.ass)

### ISSUE THREAD

**Issue by Waa11a** [mpv-player/mpv#10660]
### Important Information

Provide following Information:
- mpv version 2022-07-30-release
- Platform and Version android 12 
- Source of the mpv binary google play and fdroid

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
file picker should list subtitle files

### Actual behavior
file picker dont list subtitle files

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by sfan5** [comment]
Please file Android issues on this repo: https://github.com/mpv-android/mpv-android.
In fact this issue already exists there mpv-android/mpv-android#573

**Comment by Waa11a** [comment]
> Please file Android issues on this repo: https://github.com/mpv-android/mpv-android. In fact this issue already exists there [mpv-android/mpv-android#573](https://github.com/mpv-android/mpv-android/issues/573)

oh sorry i didn't know that. thank!
