### ISSUE TITLE
How to force sub font in mkv embedded sub font

### ISSUE THREAD

**Issue by Rafee-M** [mpv-player/mpv#10666]
I was wondering if there was a way to force the default font over the subtitle font embedded in a mkv file. Current config for subtitles:
```sub-scale=0.8
sub-auto=fuzzy
ytdl-raw-options=sub-lang="en",write-sub=,write-auto-sub=
demuxer-mkv-subtitle-preroll=yes
sub-ass-vsfilter-blur-compat=no
sub-ass-override=force
embeddedfonts=no```

**Comment by thebombzen** [comment]
You need to set a default font with `sub-font=` as well, otherwise it won't know what to override the built-in styles with.

**Comment by RafeeDaBoy** [comment]
What is the name of the default font used by mpv, couldn't seem to find the name anywhere

**Comment by thebombzen** [comment]
It picks your system's default font, you can see what it picks inside a log file.

**Comment by RafeeDaBoy** [comment]
Window's default font seems to be Segoe UI, but I can't seem to find it in the [log file](https://gist.github.com/RafeeDaBoy/b7aa0e492dfbc5b986826f5f4c5f03b6)

**Comment by infini667** [comment]
Did it work? I would like to use the exact same default subtitle style (srt) for the embedded mkv subtitles... is it possible? I already tried lots of options...
