### ISSUE TITLE
When Unpaused the Audio Cuts Out for a Few Seconds

### ISSUE THREAD

**Issue by Cananbolt** [mpv-player/mpv#10673]
## Important Information

Provide following Information:

mpv-0.34.1-x86_64
Windows 10
https://sourceforge.net/projects/mpv-player-windows/files

# Reproduction steps
When I pause a video for more then 5 seconds, when I go to unpause it the audio cuts out for about 2 seconds (the video is still playing) making me rewind the audio that I missed.

# Expected Behavior
When I unpause a video, I'd like the audio to play right away and not 2 seconds later.

**Comment by thebombzen** [comment]
Please provide a log file.

**Comment by Cananbolt** [comment]
Actually I just found a solution for the time being
`<Keybind> cycle pause ; seek -0.5 exact`

And I'm sorry I'm not too sure how to find a log file.
