### ISSUE TITLE
[gpu-next] error-diffusion errors

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#10676]
### Important Information
- mpv version ```mpv 0.34.0-483-g56e24d535e```
- Windows Version ```Windows 10 Pro x64 21H2```
- Source of the mpv binary ```shinchiro github```
- Possible screenshot or video of visual glitches
![image](https://user-images.githubusercontent.com/13978119/192075172-0bf6d3e6-0903-4016-8186-844d2aa049be.png)

### Reproduction steps
```mpv --no-config --vo=gpu-next --dither=error-diffusion```

### Expected behavior
No errors

### Actual behavior
Errors

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/9638485/log.txt)

**Comment by thebombzen** [comment]
Please upload a log file. "will upload later" is not a log file.

**Comment by Obegg** [comment]
> Please upload a log file. "will upload later" is not a log file.

Sorry about that, here, uploaded a log file.

**Comment by haasn** [comment]
Does error diffusion work with `--vo=gpu --gpu-api=d3d11`?

**Comment by haasn** [comment]
Also, two patches you can try:

```diff
diff --git a/src/shaders/dithering.c b/src/shaders/dithering.c
index 6643880f..8f13faff 100644
--- a/src/shaders/dithering.c
+++ b/src/shaders/dithering.c
@@ -422,7 +422,7 @@ bool pl_shader_error_diffusion(pl_shader sh, const struct pl_error_diffusion_par
 
         // Main block loop, add barrier here to have previous block all
         // processed before starting the processing of the next.
-         "for (uint block_id = 0; block_id < %s; block_id++) {                  \n"
+         "for (uint block_id = 0u; block_id < %du; block_id++) {                \n"
          "barrier();                                                            \n"
         // Compute the coordinate of the pixel we are currently processing,
         // both before and after the shift mapping.
@@ -439,7 +439,7 @@ bool pl_shader_error_diffusion(pl_shader sh, const struct pl_error_diffusion_par
          "vec4 pix_orig = texelFetch(%s, ivec2(x, y), 0);                       \n"
          "vec3 pix = pix_orig.rgb;                                              \n",
          ring_buffer_size,
-         SH_UINT(blocks),
+         blocks,
          SH_UINT(height),
          kernel->shift,
          SH_INT(width),
```

and

```diff
diff --git a/src/shaders/dithering.c b/src/shaders/dithering.c
index 6643880f..2d141035 100644
--- a/src/shaders/dithering.c
+++ b/src/shaders/dithering.c
@@ -431,8 +431,7 @@ bool pl_shader_error_diffusion(pl_shader sh, const struct pl_error_diffusion_par
          "int y = int(id %% height), x_shifted = int(id / height);              \n"
          "int x = x_shifted - y * %d;                                           \n"
          // Proceed only if we are processing a valid pixel.
-         "if (x < 0 || x > %s)                                                  \n"
-         "    continue;                                                         \n"
+         "if (x >= 0 && x <= %s) {                                              \n"
          // The index that the current pixel have on the ring buffer.
          "uint idx = uint(x_shifted * %s + y) %% %s;                            \n"
          // Fetch the current pixel.
@@ -531,6 +530,6 @@ bool pl_shader_error_diffusion(pl_shader sh, const struct pl_error_diffusion_par
         }
     }
 
-    GLSL("} \n"); // end of main loop
+    GLSL("}} \n"); // end of main loop
     return true;
 }
```

**Comment by Obegg** [comment]
> Does error diffusion work with `--vo=gpu --gpu-api=d3d11`?

Yes, it does.

> Also, two patches you can try:
> 
> ```diff
> diff --git a/src/shaders/dithering.c b/src/shaders/dithering.c
> index 6643880f..8f13faff 100644
> --- a/src/shaders/dithering.c
> +++ b/src/shaders/dithering.c
> @@ -422,7 +422,7 @@ bool pl_shader_error_diffusion(pl_shader sh, const struct pl_error_diffusion_par
>  
>          // Main block loop, add barrier here to have previous block all
>          // processed before starting the processing of the next.
> -         "for (uint block_id = 0; block_id < %s; block_id++) {                  \n"
> +         "for (uint block_id = 0u; block_id < %du; block_id++) {                \n"
>           "barrier();                                                            \n"
>          // Compute the coordinate of the pixel we are currently processing,
>          // both before and after the shift mapping.
> @@ -439,7 +439,7 @@ bool pl_shader_error_diffusion(pl_shader sh, const struct pl_error_diffusion_par
>           "vec4 pix_orig = texelFetch(%s, ivec2(x, y), 0);                       \n"
>           "vec3 pix = pix_orig.rgb;                                              \n",
>           ring_buffer_size,
> -         SH_UINT(blocks),
> +         blocks,
>           SH_UINT(height),
>           kernel->shift,
>           SH_INT(width),
> ```
> 
> and
> 
> ```diff
> diff --git a/src/shaders/dithering.c b/src/shaders/dithering.c
> index 6643880f..2d141035 100644
> --- a/src/shaders/dithering.c
> +++ b/src/shaders/dithering.c
> @@ -431,8 +431,7 @@ bool pl_shader_error_diffusion(pl_shader sh, const struct pl_error_diffusion_par
>           "int y = int(id %% height), x_shifted = int(id / height);              \n"
>           "int x = x_shifted - y * %d;                                           \n"
>           // Proceed only if we are processing a valid pixel.
> -         "if (x < 0 || x > %s)                                                  \n"
> -         "    continue;                                                         \n"
> +         "if (x >= 0 && x <= %s) {                                              \n"
>           // The index that the current pixel have on the ring buffer.
>           "uint idx = uint(x_shifted * %s + y) %% %s;                            \n"
>           // Fetch the current pixel.
> @@ -531,6 +530,6 @@ bool pl_shader_error_diffusion(pl_shader sh, const struct pl_error_diffusion_par
>          }
>      }
>  
> -    GLSL("} \n"); // end of main loop
> +    GLSL("}} \n"); // end of main loop
>      return true;
>  }
> ```

I'm sorry, I don't know what to do with it :(

**Comment by bjin** [comment]
I just did a quick look, based on error message it could be similar to #6814. For that issue, spirv-cross generated redundant statement which confused the control flow analysis of hlsl compiler.

**Comment by Obegg** [comment]
How can I know it's working properly, since there is no indication of "dithering" on the stats overlay? ("frame timing")

**Comment by haasn** [comment]
@Obegg turns out this is a limitation/bug of the mpv pass timing mechanism. I may rewrite it in order to correspond to `gpu-next`'s design (instead of `gpu`'s), but I was planning on doing that when we were closer to deprecating `gpu`.

**Comment by haasn** [comment]
> How can I know it's working properly, since there is no indication of "dithering" on the stats overlay? ("frame timing")

there should be now (mpv master)

**Comment by Obegg** [comment]
> > How can I know it's working properly, since there is no indication of "dithering" on the stats overlay? ("frame timing")
> 
> there should be now (mpv master)

Now I see "dithering", yes, is it possible to specify which dithering algorithm/kernel or such thing isn't needed?

**Comment by haasn** [comment]
> > > How can I know it's working properly, since there is no indication of "dithering" on the stats overlay? ("frame timing")
> > 
> > 
> > there should be now (mpv master)
> 
> Now I see "dithering", yes, is it possible to specify which dithering algorithm/kernel or such thing isn't needed?

I mean, it would trivially be possible:

```diff
diff --git a/src/shaders/dithering.c b/src/shaders/dithering.c
index 87bbc917..7940863a 100644
--- a/src/shaders/dithering.c
+++ b/src/shaders/dithering.c
@@ -116,7 +116,6 @@ void pl_shader_dither(pl_shader sh, int new_depth,
         return;
     }
 
-    sh_describe(sh, "dithering");
     GLSL("// pl_shader_dither \n"
         "{                    \n"
         "float bias;          \n");
@@ -206,6 +205,14 @@ done: ;
         }
     }
 
+    static const char *names[PL_DITHER_METHOD_COUNT] = {
+        [PL_DITHER_WHITE_NOISE]     = "white noise",
+        [PL_DITHER_BLUE_NOISE]      = "blue noise",
+        [PL_DITHER_ORDERED_FIXED]   = "ordered",
+        [PL_DITHER_ORDERED_LUT]     = "ordered",
+    };
+
+    sh_describef(sh, "%s dithering", names[method]);
     switch (method) {
     case PL_DITHER_WHITE_NOISE: {
         ident_t prng = sh_prng(sh, params->temporal, NULL);
```

But I honestly don't see the value here. This description is usually long enough (threatening to cut off the actual graph on my end), and usually you would know what dither method you picked in your configs, no? Since it's not like there's an "auto" dither mode, nor does dithering depend in any way on the screen resolution - with the exception of error diffusion, but that's already treated as a separate pass (named "error diffusion" in the stats)...
