### ISSUE TITLE
The combination of `set fullscreen no; set window-maximized no` doesn't work properly

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [mpv-player/mpv#10687]
### Important Information

Provide following Information:
- mpv version master
- Windows Version Windows11 22622.601
- Source of the mpv binary shinchiro
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
mpv.conf
```ini
fullscreen
window-maximized

autofit-larger=100%x88%
autofit-smaller=66%
```
input.conf
```ini
ESC                 set fullscreen no; set window-maximized no
```
First time to press ESC. See the border.
![image](https://user-images.githubusercontent.com/50797982/192475715-37234e39-4b1f-463f-aab2-eeee3d9ce2f6.png)
Second time to press ESC. It fills the screen.
![image](https://user-images.githubusercontent.com/50797982/192475895-1a86fa80-0ebd-46ac-8b72-96d8ee3639f9.png)

And with `no-border`, It's even stranger.

First time to press ESC. Position and size are fine, But the icons indicate that the state is not right at this time.
![image](https://user-images.githubusercontent.com/50797982/192476213-958641db-fa37-4593-8b5c-6169f91cffc0.png)
Second time to press ESC.
![image](https://user-images.githubusercontent.com/50797982/192476279-20f5e7d5-6a57-481a-aad1-a8569234804f.png)
Third time to press ESC. Also fills the screen.
![image](https://user-images.githubusercontent.com/50797982/192476442-2940e412-be3a-4dd5-9b58-9f8f0ac8a916.png)
The icon works fine without of this scenario.
![image](https://user-images.githubusercontent.com/50797982/192477402-5518dd22-59c2-496b-807d-dfe7ca3b04b1.png)

Please keep the video playing while trying to reproduce, as it behaves differently when paused 🙃.

### Expected behavior

Window have correct size and position.
![image](https://user-images.githubusercontent.com/50797982/192476103-76782837-efdb-4e93-a08f-d9280e451bca.png)

### Actual behavior

Wrong size and position.

### Log file

If needed, I will upload it.

### Sample files

Any video.

**Comment by hooke007** [comment]
related https://github.com/mpv-player/mpv/issues/10229
