### ISSUE TITLE
mpv dont minimize with toggle desktop in ubuntu

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#10682]
I use super + D to toggle who desktop.

But i want mpv not to get affected by this

reason is, I am showing mpv on another screem. I want that screen to keep showing the video.

**Comment by Dudemanguy** [comment]
If the window manager/compositor minimizes mpv, there's not really anything we can do. The window is going to minimize. I don't know much about ubuntu, but it would be nicer if you could change the shortcut so it only affects applications on one screen or something like that. I suppose it might also be possible to write a script that automatically refocuses mpv after it gets minimized but I wouldn't know how to do that off the top of my head.
