### ISSUE TITLE
Question about sub-ass-vsfilter-aspect-compat option

### ISSUE THREAD

**Issue by TheOneric** [mpv-player/mpv#10680]
In libass during https://github.com/libass/libass/pull/645 (and also before) it was proposed to prefer the values from `ass_set_storage_size` for PAR calculation over the value from `ass_set_pixel_aspect`. Reasoning being that to achieve correct ASS rendering, those need to match anyway, non-matching values might lead to bizarre results and non-ASS subs (which have been on-the-fly converted) most likely won't set either value.
However, it was observed this would break mpv's `sub-ass-vsfilter-aspect-compat=no` option unless the — misleadingly named — `sub-ass-vsfilter-blur-compat` option which controls whether storage size is passed is also set to `no`. Notably, `sub-ass-vsfilter-aspect-compat` even has its own hot key `V` by default for some reason.

So we are wondering what the specific usecases for this option are,  i.e. what type of file needs this *(the [commit message](https://github.com/mpv-player/mpv/commit/9e6933440ae59c523fce85b64d6f52f444910003) of the introducing commit or the doc aren't very helpful)* and whether you'd mind the option to be merged with `blur-compat` — perhaps under a new, non-misleading name like `sub-ass-discard-video-info`.

For reference here is the most relevant comment on this by @astiob from libass' tracker: https://github.com/libass/libass/pull/645#pullrequestreview-1119327502
> […] but here’s an argument (for the sake of it) against preferring storage size over an explicitly set PAR: it turns mpv’s `sub-ass-vsfilter-aspect-compat` toggle (which apparently was historically so important that it has its own hot key `V`!) into a no-op unless `sub-ass-vsfilter-blur-compat` is also disabled.
> My weak counter-argument to this argument is that I suspect that subtitles that did want this toggle to be disabled had `PlayResX` equal to a desqueezed width and should therefore start working correctly now (regardless, indeed, of the PAR setting, even if the API keeps working)… except the actual text will get stretched. I have never encountered a file like this myself, so I can’t tell how relevant this really is; but it kinda feels wrong to break this mpv feature given the emphasis mpv puts on it. Maybe we should ask mpv people and maybe they’ll just say they’d actually love to merge it into `blur-compat`?

**Comment by dyphire** [comment]
https://github.com/mpv-player/mpv/issues/6517 This issue mentioned an example of use `sub-ass-vsfilter-aspect-compat=no` options to get correct rendering.

**Comment by astiob** [comment]
I can only guess, but perhaps the linked issue involved a standalone subtitle file downloaded from a subtitle-only website and played with an independently obtained video file. This does, indeed, sound like a valid use case for this toggle. But still, it seems this use case would be satisfied by a merged option that sets both `aspect-compat=no blur-compat=no`.

Is there a use case for `aspect-compat=no blur-compat=yes`?

However, even if not _that,_ it seems to me that there is a use case for `aspect-compat=yes blur-compat=no`: this should most closely match MPC-HC’s internal subtitle renderer, in case some subtitle file targets that. So the two options shouldn’t be completely merged into a single Boolean toggle, but perhaps a tri-state toggle would work best. (Then again, we may have just broken this ISR-matching case on libass’s side, as I mentioned on #libass IRC.)

By the way, the linked issue no longer produces the reporter’s expected output in both windowed and full-screen mode, after libass (in response to complaints from the mpv side) [changed](https://github.com/libass/libass/commit/d60f2dce1dcafaed0e21406213e66072f3036752) `ScaledBorderAndShadow: no` to act as `yes` when `blur-compat=no` in 2020, which I’m personally not happy about.

**Comment by TheOneric** [comment]
@kasper93 afaict the confusing/superfluous options still exist so not sure why this is closed

Are there any plans to drop them or reasons why this can't happen?

**Comment by kasper93** [comment]
> Are there any plans to drop them or reasons why this can't happen?

The issue tracker is not for questions or discussions anymore. It was closed as there is no action to be taken here. I can reopen it for you, as there are valid concerns in this ticket, maybe someone who knows ASS will pick this up.

**Comment by Jasaj4** [comment]
FYI, it appears that the `sub-ass-vsfilter-aspect-compat` option was deprecated in version 0.38.
The correct syntax now is `sub-ass-use-video-data=none`. I’ve tested it and it works well.

`sub-ass-use-video-data=none` is equivalent to `sub-ass-vsfilter-aspect-compat=no` and `sub-ass-vsfilter-blur-compat=no`

Thanks to this thread I had to waste my time and effort on this issue.
