### ISSUE TITLE
Any way to install mpv-build-git like Arch Linux on Fedora?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#10685]
I had some issue for my Arch Linux PC this morning, and I reinstalled my OS with Fedora.
When I was using Arch Linux, I could install latest MPV (mpv-build-git) player via AUR, I need some latest feature which is not included in the release version, then I saw Copr, others said that it was like the equivalent of AUR on Fedora, but I always get 504 bat gateway when I search `mpv git`.

Is there any way to install mpv-build-git easily on Fedora?
Or just teach us how to build mpv-build-git on Fedora.

**Comment by lavilao** [comment]
from source I think? although if fedora is like debian that separates the headers from libraries (example libplacebo and libplacebo-dev) is going to be a really annoying experience.

**Comment by laichiaheng** [comment]
@lavilao I have found the way to do it.
1. `cd ~/mpv-build/mpv`
2. `sudo dnf builddep mpv`
3. `waf configure`
4. `cd ..`
5. `sudo ./install`

Do you know how to build the git master version of MPV player?

**Comment by lavilao** [comment]
Sure, I use manjaro and this is how I do it:
download the source code decompress it on some folder and enter the folder on a terminal. The commands are like the ones you have with a few exceptions:
cd ~/mpv-master
./bootstrap.py
waf configure
waf

by this point you should have a mpv binary on mpv-master/build, however keep in mind that mpv activates its features at compile time and only if it detects the needed libraries, example the vapoursynth option will only be available if at the compile time you have installed the vapoursynth package so READ THE TERMINAL OUTPUT from waf configure.

**Comment by laichiaheng** [comment]
@lavilao So I should download mpv-git instead of mpv-build?

**Comment by lavilao** [comment]
Thats the way I do it, I have never used mpv-build so I could be wrong/it could be easier with it. So yes download mpv-git

**Comment by laichiaheng** [comment]
> Thats the way I do it, I have never used mpv-build so I could be wrong/it could be easier with it. So yes download mpv-git

I give up, I need to build libplacebo-git to enable gpu-next, too complicated.

**Comment by lavilao** [comment]
I would usually tell you "stop, dont give up!" but the last time I compiled it if it wasn't because manjaro ships libplacebo 208 (if fedora ships it you are saved) I would not be able to have gpu-next because (at that time) mpv-git could not be compiled against libplacebo-git (dont know now, it could be fixed and its very easy to compile libplacebo), so yes compiling a package on anything other than arch derivatives is a pain (sorry if it sounded too fanboy but its my opinion).

**Comment by lavilao** [comment]
Also now that I check, on mpv-build there is a file to compile master (git) instead of release, did you tried that?

**Comment by laichiaheng** [comment]
@lavilao Thanks a lot!!
I didn't see the extra information below.
