### ISSUE TITLE
[Question] dither depth and error-diffusion

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#10691]
I have a few questions regarding dither.

1) Most screens are 8-bit or 10-bit, but on Windows there's this option that says 12-bit
![image](https://user-images.githubusercontent.com/13978119/192641517-4435efab-a0f8-4f7a-8f40-f6dffa4887c3.png)
so should I set `dither-depth=12`?

2) There are a lot of different algorithms for `error-diffusion` such as `sierra-lite`, `floyd-steinberg`, `jarvis-judice-ninke`, `atkinson`.
Which one is the "best" (without thinking about performance)?
It doesn't matter if it's very demanding from the CPU/GPU as long as it's the "best".

**Comment by haasn** [comment]
Quality is subjective. Personally I find the flickering associated with error diffusion on moving images to be one of the most intrusive artifacts. I would absolutely never use error diffusion for anything other than **still images**. Furthermore, note that error diffusion is not currently gamma aware. So when dithering to a very low bit depth (<=4), I would also always use `fruit`, even for still images. Also, the difference is subjectively basically non-existant for higher bit depths (>= 8), so you might as well go with what's fastest.

(Yes, I'm aware that the above considerations combine to "never use error diffusion", but that is at least part of the reason why I think it's such a pointless anti-feature)

**Comment by Obegg** [comment]
This point of view changed my point of view, I did not know this and/or noticed any artifacts.
Based on that, I take it that the "best" is `dither=no`.
Is dithering that bad and unnecessary? 
Is turning it off makes the video "original to source" (sort of say)?

**Comment by haasn** [comment]
@Obegg at 12 bit dithering is pretty pointless but to be on the safe side I would still use `--dither=ordered` on `--vo=gpu-next`. It's extremely fast, to the point of basically being free. (On `--vo=gpu` I would stick with `--dither=fruit`)

>  Is turning it off makes the video "original to source" (sort of say)?

No, turning it off introduces rounding artifacts / banding. But at 12 bit they're imperceptible.

**Comment by Obegg** [comment]
Thank you!
I now use:
```
vo=gpu-next
dither=ordered
dither-depth=12
```

**Comment by haasn** [comment]
No, nothing has changed.

**Comment by geextahslex** [comment]
dither off:
![dither off f](https://github.com/mpv-player/mpv/assets/139760266/10ebb7b1-e6bf-4c05-9bbb-1b4526177f40)
dither on: (dither-depth=8, dither=fruit)
![dither on](https://github.com/mpv-player/mpv/assets/139760266/7a81f02b-c9e6-41ac-8eee-f52191fa5f62)

**Comment by geextahslex** [comment]
Glad to hear that. What I see? dither on/off = night and day difference, especially in motion. Deband goes one step further. Not a must but nice to have.

**Comment by geextahslex** [comment]
I felt the same way and had them turned off. But then I realised how much of an impact there actually is. Maybe try going with "vo=gpu-next"

**Comment by geextahslex** [comment]
@Obegg oh okay, I thought "profile=gpu-hq"

**Comment by geextahslex** [comment]
@Obegg Wow I didn't even know that you can tune it to performance. Mpv is truly magnificent ^^

**Comment by JohnChristianD** [comment]
> at 12 bit dithering is pretty pointless but to be on the safe side I would still use `--dither=ordered` on `--vo=gpu-next`. It's extremely fast, to the point of basically being free. (On `--vo=gpu` I would stick with `--dither=fruit`)

Any reason you disrecommend ordered dithering on vo=gpu?
