### ISSUE TITLE
Wrong colors in HDR screen capture created with OBS 28.0.2

### ISSUE THREAD

**Issue by jansol** [mpv-player/mpv#10696]
### Important Information

Not sure if I made a mistake in the recording process, if OBS produced a bad file or it is an actual MPV bug, but VLC plays it correctly and MPV does not so linked a 2s sample clip of the recording.

Provide following Information:
- mpv version: `eba4ce5c2d103cb79c2bf7491e5de9a65190e7c2, also occurs on 0.34.1`
- Linux Distribution and Version: `NixOS unstable`
- Source of the mpv binary: `built using nixpkgs derivation with source revision changed to git HEAD`
- If known which version of mpv introduced the problem: `unknown`
- Window Manager and version: `KDE Plasma Wayland 5.25.5`
- GPU driver and version: `mesa 22.2.0+0d66ed49b412551b843fb8db5ccc1ce6bc4f5f7f`
- Possible screenshot or video of visual glitches: `see below`

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Use OBS 28.0.2 to record gameplay on Windows 11 with AutoHDR active. Source colorspace set to BT.2100 (PQ) and video output set to use P010 format and BT.2100 (PQ) color.

Didn't have mpv on Windows so results are from Linux. VLC played the file correctly on both platforms. Issue **does** happen with `--no-config`.

### Expected behavior

Similar to original appearance and vlc (3.0.17.3, with libplacebo v4.208.0) output:

![vlcsnap-2022-09-28-23h37m00s698](https://user-images.githubusercontent.com/2588851/192885119-38e83e78-6082-4ea9-b172-0b2dc67ee986.png)

### Actual behavior

Stylized tonemapping:

![mpv-shot0006](https://user-images.githubusercontent.com/2588851/192885178-196c8b14-d79b-4061-bf4a-2d0f76228936.png)

### Log file

[mpvlog.txt](https://github.com/mpv-player/mpv/files/9668870/mpvlog.txt)

### Sample files

https://0x0.st/o4Tc.mkv

**Comment by ZaquL** [comment]
No, we behave correctly, the pink color is correct.

Color range                 : Full
Color primaries             : BT.2020
Transfer characteristics    : PQ
**Matrix coefficients         : YCgCo**
Mastering display color pri : Display P3
MasteringDisplay_ColorPrima : R: x=0.320000 y=0.000000, G: x=0.690000 y=0.000000, B: x=0.060000 y=0.000000, White point: x=0.312700 y=0.329000
Mastering display luminance : min: 0.0000 cd/m2, max: 1500 cd/m2
Maximum Content Light Level : 1500
MaxCLL_Original             : 1500 cd/m2
Maximum Frame-Average Light : 1500
MaxFALL_Original            : 1500 cd/m2

**Comment by jansol** [comment]
Ah, that issue is old enough that it slipped my check for existing ones.

> Matrix coefficients : YCgCo

> [4340]: It's entirely possible that this file is YCbCr in disguise (mistagged as YCgCo), and that it works in QuickTime etc. because they ignore the YCgCo tag; this combined with the previous fact would explain why it produced a seemingly correct output when I swapped the B/G channels for the YCgCo matrix.

> No, [vlc] plays video incorrectly, it does not even support YCgCo

That would make sense I guess. Time to poke OBS some more.

**Comment by ZaquL** [comment]
> That would make sense I guess. Time to poke OBS some more.

Did you cut this video and maybe tagged it incorrectly?

**Comment by ZaquL** [comment]
In fact chrome that supports YCgCo behaves the same.

![image](https://user-images.githubusercontent.com/104958042/192893042-3d5d4242-0ae0-4a7f-9d7e-04b252a37352.png)

**Comment by jansol** [comment]
I did clip the sample from a 30min recording with ffmpeg, but the original file behaves the same way so I imagine it is already mistagged there.

**Comment by ZaquL** [comment]
> I did clip the sample from a 30min recording with ffmpeg, but the original file behaves the same way so I imagine it is already mistagged there.

please encode small file and attach that. I will try to fix obs.

**Comment by ZaquL** [comment]
I think there is an off-by-one in OBS, it must be 9. 

![image](https://user-images.githubusercontent.com/104958042/192895552-673612fc-17b1-4aaf-a2a7-8791375d0048.png)

**Comment by ZaquL** [comment]
I just checked, my HDR is recorded with (BTW, remove full range, nothing supports it, besides davinci), all correct.

**Frame rate mode             : Constant
Frame rate                  : 60.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0 (Type 2)
Bit depth                   : 10 bits
Default                     : No
Forced                      : No
Color range                 : Limited
Color primaries             : BT.2020
Transfer characteristics    : PQ
Matrix coefficients         : BT.2020 non-constant
Mastering display color pri : Display P3
Mastering display luminance : min: 0.0000 cd/m2, max: 10000 cd/m2
Maximum Content Light Level : 10000
Maximum Frame-Average Light : 10000**

**Comment by ZaquL** [comment]
In fact even with Auto HDR using cracked Minecraft Bedrock UWP edition (with RTX and stuff) it does not do YCgCo.

**Comment by jansol** [comment]
Okay, tried here are two clips straight from OBS:
[Color range: Limited](https://0x0.st/o4mr.mkv)
[Color range: Full](https://0x0.st/o4ms.mkv)

Looks like switching it to full color range has some weird side effects.

**Comment by ZaquL** [comment]
Yes, it is full range that somehowm corrupts matrix. Strange, but it does not happen on my PC, maybe you will desribe your settings that you have changed? YOU NEVER suppose to record in full range, only Dolby Vision profile 5 is really full range and some very very rare cameras that record in sLog3-cine. All Blu-rays are limted (no profile 5 on Blu-ray), all Youtube, all satellities, just saying. HDR is even for so likes limited.

**Comment by ZaquL** [comment]
Still, it looks like something you were using made it wrong,

<matrix_coefficients>BT.2020 non-constant</matrix_coefficients>
<matrix_coefficients_Source>Container</matrix_coefficients_Source>
<matrix_coefficients_Original>YCgCo</matrix_coefficients_Original>
<matrix_coefficients_Original_Source>Stream</matrix_coefficients_Original_Source>

**Comment by jansol** [comment]
> desribe your settings

Here you go, let me know if I forgot anything relevant:
![image](https://user-images.githubusercontent.com/2588851/193144836-1b31c9be-c5dd-4a22-9c6f-29c92afd64ea.png)
![image](https://user-images.githubusercontent.com/2588851/193144903-c24bebbd-01b4-4898-b710-2ad79a70edbe.png)
![image](https://user-images.githubusercontent.com/2588851/193145170-8f069490-13f1-4e99-978c-92d90b25b193.png)
And for the Game Capture source:
![image](https://user-images.githubusercontent.com/2588851/193145274-f5de02c7-aa7a-46d7-94df-d62ee82ddda4.png)

**Comment by ZaquL** [comment]
AMD! That is the difference. I use nvidia.

**Comment by jansol** [comment]
Coincidentally the AMD encoder was just rewritten for 28.0.0...
