### ISSUE TITLE
undefined reference to `vkCreateWaylandSurfaceKHR'

### ISSUE THREAD

**Issue by mrturcot** [mpv-player/mpv#10697]
compile fails

```
/mpv/build/../video/out/vulkan/context_wayland.c:87: undefined reference to `vkCreateWaylandSurfaceKHR'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

I ran "meson build" then "meson compile -C build" (please see attached logs). I am currently using Gentoo, I have emerged/compiled and have installed version 0.34.1-r1 already working fine with all necessary dependencies. I don't have wayland enabled on my system so not sure if this issue is related as why I cannot build from git source?

meson_build.log - https://hastebin.skyra.pw/sifaquhofo.nestedtext
meson_compile.log - https://hastebin.skyra.pw/zuyuvimusa.rust

**Comment by CoelacanthusHex** [comment]
> I don't have wayland enabled on my system so not sure if this issue is related as why I cannot build from git source?

According to the log, wayland feature was enabled, you should disable it by `-Dwayland=disabled` if you don't want to use wayland.

**Comment by mrturcot** [comment]
> > I don't have wayland enabled on my system so not sure if this issue is related as why I cannot build from git source?
> 
> According to the log, wayland feature was enabled, you should disable it by `-Dwayland=disabled` if you don't want to use wayland.

Awesome that was it thanks
