### ISSUE TITLE
seekbar change position instead of middle

### ISSUE THREAD

**Issue by syedidiflipt** [mpv-player/mpv#10707]
Hi

when i try to  seek i see the seek bar in the middle. how to change its possition

![image](https://user-images.githubusercontent.com/102683804/193471290-a041767e-67ca-4e4c-8e7c-e522786f6b24.png)

**Comment by guidocella** [comment]
`--osd-bar-align-y=<-1-1>`

**Comment by syedidiflipt** [comment]
can you show me the full command

```
 $ mpv --script-opts=osd-bar-align-y=<-1-1> 1.mp4                              
zsh: no such file or directory: -1-1
```

**Comment by syedidiflipt** [comment]
tries but no luck

```
 $ mpv --script-opts=osd-bar-align-y=\<-1-1\> 1.mp4
 (+) Video --vid=1 (*) (h264 1280x720 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
[ffmpeg] AVHWDeviceContext: Failed to query surface attributes: 20 (the requested function is not implemented).
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz stereo 2ch float
[nextfile] on_loaded: 1.mp4 
VO: [gpu] 1280x720 vaapi[nv12]
[nextfile] on_loaded: 1.mp4 
(Paused) AV: 00:00:26 / 01:32:38 (0%) A-V:  0.000


```

![image](https://user-images.githubusercontent.com/102683804/193472185-7c3d18a3-ec7d-481e-80e4-904fa0db91e2.png)

**Comment by guidocella** [comment]
`mpv --osd-bar-align-y=.9 foo.mp4`

**Comment by FinnRaze** [comment]
--osd-bar-align-y=[-1,-1]
Position of the OSD bar. -1 is top, 0 is centered, 1 is bottom. Fractional values (like 0.5) are allowed.
Write the code in mpv.conf.
