### ISSUE TITLE
gpu-next: green/purple tint on Dolby Vision P5 videos with tone-mapping=bt.2446a

### ISSUE THREAD

**Issue by diamondburned** [mpv-player/mpv#10700]
I'm trying to play back a Dolby Vision Profile 5 video with a regular SDR display. I thought that adding `tone-mapping=bt.2446a` will allow that [per this comment on nyaa.si](https://nyaa.si/view/1578114#com-7); however, that's not working as intended.

### Important Information

- mpv git commit b9c7e5b (reported as 0.34.0-UNKNOWN, libplacebo git commit `deccd2c`)
- Linux distribution: NixOS 21.11, Nixpkgs unstable `7e52b35fe98` (only for mpv and libplacebo)
- Source of the mpv binary: N/A, built from source [(build logs)](https://gist.github.com/diamondburned/25e581d9c7e3b467f60d79baf02ec54e)
- Window Manager and version: GNOME Wayland v42.3
- GPU driver and version: Intel Iris Xe Integrated Graphics w/ i5-1240P ([glxinfo](https://gist.github.com/diamondburned/b0ac6ff1e6a25203c8318b8c0e527ff5), [vulkaninfo](https://gist.github.com/diamondburned/aac3d68f4836fc66c472226f9db08933))

### Reproduction steps

1. Download the "Glass Blowing @59.94fps: Dolby Vision Profile 5 UHD for iOS – Dolby Atmos" linked in the Sample files section.
2. Play by running `mpv --no-config --vo=gpu-next --gpu-api=vulkan --hwdec=no --tone-mapping=bt.2446a ./iOS_P5_GlassBlowing2_3840x2160@59.94fps_15200kbps.mp4`.

### Expected behavior

The video plays back with the right colors. The screenshot below is replicated by playing back a Dolby Vision Profile 8.1 video.

<img width="400" alt="Image of a frame in a video with proper colors" src="https://user-images.githubusercontent.com/8463786/193408681-57b0dfda-2e95-471a-a0af-57473d9e9205.png" />

### Actual behavior

The video plays back with false colors. The screenshot below is replicated by playing back the Profile 5 video link linked below.

<img width="400" alt="Image of a frame in a video with a purple-green tint" src="https://user-images.githubusercontent.com/8463786/193408436-5ceefe74-7229-4a1c-9ce9-b97140f3b402.png" />

### Log file

https://gist.github.com/diamondburned/a343ba90207bda207f2b139709fb4f69

### Sample files

- "Glass Blowing @59.94fps: Dolby Vision Profile 5 UHD for iOS – Dolby Atmos" video from [Dolby Developer's Dolby Vision streams website](https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/).
    - Direct link: [`iOS_P5_GlassBlowing2_3840x2160%4059.94fps_15200kbps.mp4`](http://media.developer.dolby.com/DolbyVision_Atmos/mp4/iOS_P5_GlassBlowing2_3840x2160%4059.94fps_15200kbps.mp4).

**Comment by nyanmisaka** [comment]
> [   0.008][v][cplayer] FFmpeg version: 4.4.2

You need at least FFmpeg 5.0 for Dolby Vision support.

**Comment by haasn** [comment]
> I'm trying to play back a Dolby Vision Profile 5 video with a regular SDR display. I thought that adding tone-mapping=bt.2446a will allow that [per this comment on nyaa.si](https://nyaa.si/view/1578114#com-7); however, that's not working as intended.

This is completely orthogonal. The correct answer is to upgrade to new-enough FFmpeg, as pointed out.

**Comment by diamondburned** [comment]
Sorry. Is this documented anywhere?

**Comment by nyanmisaka** [comment]
https://github.com/haasn/libplacebo/blob/fbe867f66d9c698a2092b0eb70dca5c93ef75b00/src/include/libplacebo/utils/libav.h#L32-L35

**Comment by diamondburned** [comment]
This isn't really documentation. Is there not a warning in mpv?

**Comment by nyanmisaka** [comment]
> <dolbyvision=yes|no>
Whether or not to include Dolby Vision metadata (default: yes). If disabled, any Dolby Vision metadata will be stripped from frames.

It seems this part is not well documented explicitly in [mpv docs](https://mpv.io/manual/master/#video-filters-%3Cdolbyvision). You can open a PR for it.

**Comment by diamondburned** [comment]
It's more like a warning about FFmpeg versions. I did poke around with `dolbyvision=yes|no`, but the fact that I didn't see any warnings in either case made me think it wasn't it.
