### ISSUE TITLE
Why is there a green line at the bottom of the image when using d3d11va-zero-copy=yes?

### ISSUE THREAD

**Issue by CCCAUCHY** [mpv-player/mpv#10719]
According to the `manual.pdf`, the bottom and right edges can not be processed correctly, why not just drop those pixels or replace them by black pixels?

**Comment by CounterPillow** [comment]
How would you be able to tell when a specific driver starts returning garbage data for a sampled pixel, considering that this is not consistent?

**Comment by CCCAUCHY** [comment]
> How would you be able to tell when a specific driver starts returning garbage data for a sampled pixel, considering that this is not consistent?

Why not crop the image by one pixel width at the bottom and right edge when the image display?

**Comment by thebombzen** [comment]
Again, because there's no way to tell when a specific driver starts returning garbage data, considering that it is not consistent. We're not just gonna crop every image for that reason.

**Comment by CCCAUCHY** [comment]
> Again, because there's no way to tell when a specific driver starts returning garbage data, considering that it is not consistent. We're not just gonna crop every image for that reason.

I mean we should crop the display area, or overlay a one-pixel-width black line at the bottom and right edge of a screen or a window of Windows.
