### ISSUE TITLE
Can't save screenshots as jxl

### ISSUE THREAD

**Issue by roland-rollo** [mpv-player/mpv#10714]
### Important Information

Provide following Information:
- mpv version
mpv 0.34.0-496-ga2de6524ff Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Mon Oct 03 06:56:03 2022
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: n5.1.2

cjxl v0.7.0 f95da131 [AVX2,SSE4,SSSE3,Unknown]
Copyright (c) the JPEG XL Project

- Platform and Version
Arch Linux

- Source of the mpv binary
AUR git package

### Reproduction steps

I added to my mpv config option to save screenshots as jxl
```
screenshot-format=jxl
```

### Expected behavior

It should save screenshots as jxl image files.

### Actual behavior
But if I try screenshot something it show me this:
```
[cplayer] Starting screenshot: '/home/roland/mpv-shot0001.jxl'
[cplayer] using 8 threads for scaling
[statusline] AV: 00:00:06 / 00:06:49 (2%) A-V:  0.000
[cplayer] Using zimg.
[cplayer] Could not open libavcodec encoder for saving images
[cplayer] Error writing file '/home/roland/mpv-shot0001.jxl'!
[cplayer] Error writing screenshot!
```
For webp and other I don't see this message.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
Your ffmpeg is likely built without libjxl support, as Arch's package is.

**Comment by roland-rollo** [comment]
Thanks. I will check this.
