### ISSUE TITLE
over the windows

### ISSUE THREAD

**Issue by wita74** [mpv-player/mpv#10711]
Tell me how to make the player on top of all windows and where and what should I enter?

**Comment by CounterPillow** [comment]
shift+t, or `--ontop`. (does not work on wayland)

**Comment by wita74** [comment]
> шифт+т или `--ontop`. (не работает на вайленде)

I saw it in the instructions. Only shift+t and onstop don't work, what is it? Where to enter (I tried config, it doesn't work) and most importantly, I don't understand exactly how

**Comment by thebombzen** [comment]
That's how you do it, you push Shift+T, you launch with `--ontop` or you put `ontop=yes` in your config. If it doesn't work, and you're not on wayland, then you should open a separate issue to report this bug.
