### ISSUE TITLE
How to get `input-bindings` from mouse click?

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#10723]
This script only print `MBTN_LEFT ignore`, but when I set options.bind to keyboard key e.g. z or space, It will work as expected.

```lua
local opt = require("mp.options")
local options = {
    bind = "MBTN_LEFT",
}
opt.read_options(options)

local original = ""

function get_key_binding(key)
    for _, v in ipairs(mp.get_property_native("input-bindings")) do
        print(v.key, " ", v.cmd)
        if v.key == key then
            return v.cmd
        end
    end
    return "ignore"
end

function keydown(key_name, key_text, is_mouse)
    original = get_key_binding(options.bind)
end

function keyup()

end

function event_handler(event, is_mouse, key_name, key_text)
    if event == "down" then
        keydown(key_name, key_text, is_mouse)
    elseif event == "up" then
        keyup(key_name, key_text, is_mouse)
    elseif event == "press" then
        keypress(key_name, key_text, is_mouse)
    elseif event == "repeat" then
        keyrepeat(key_name, key_text, is_mouse)
    else
        print(event, key_name, key_text, is_mouse)
    end
end

mp.add_forced_key_binding(options.bind, nil, function(e)
    event_handler(e.event, e.is_mouse, e.key_name, e.key_text)
end, {
    complex = true
})
```

**Comment by christoph-heinrich** [comment]
There is no point in setting complex for the left mouse button, as button up it will fire immediately after button down.

**Comment by Natural-Harmonia-Gropius** [comment]
My ultimate goal is to handle double click and long press in one script, so I want them to have consistent event behavior.

**Comment by christoph-heinrich** [comment]
Using complex for the left mouse button is not helpful. I'd use a normal keybinding, save the last click event time in a variable, set a timer and observe `mouse-pos`.

On mouse left down, `mouse-pos/hover` becomes false and when the click ends, it becomes true again. So if the time between two clicks is short enough, it's a double click. If the timeout triggers, it's a long click, and the `mouse-pos/hover == true` is used to for killing the timer.

**Comment by christoph-heinrich** [comment]
This works.
``` lua
local last_click = nil
local long_click_timeout = mp.add_timeout(0.5, function()
	last_click = nil
	print("long click")
end)
long_click_timeout:kill()
mp.observe_property('mouse-pos/hover', 'native', function(_, hover)
	if hover and last_click then
		long_click_timeout:kill()
	end
end)
mp.add_key_binding('mbtn_left', 'uosc_mouse', function()
	local now = mp.get_time()
	if last_click and now - last_click < 0.2 then
		last_click = nil
		long_click_timeout:kill()
		print('double click')
	else
		last_click = now
		long_click_timeout:resume()
	end
end)
```

**Comment by christoph-heinrich** [comment]
``` Lua
local last_click = nil
local long_click_timeout = mp.add_timeout(0.5, function()
    last_click = nil
    print("long click")
end)
long_click_timeout:kill()
mp.observe_property('mouse-pos', 'native', function(_, mouse)
    print(mouse, last_click)
    if mouse.hover and last_click then
        long_click_timeout:kill()
    end
end)
mp.add_key_binding('mbtn_left', 'uosc_mouse', function(tab)
    local now = mp.get_time()
    if tab.event == 'up' then
        if last_click and now - last_click > 0.01 then
            long_click_timeout:kill()
        end
    elseif last_click and now - last_click < 0.2 then
        last_click = nil
        long_click_timeout:kill()
        print('double click')
    else
        last_click = now
        long_click_timeout:resume()
    end
end, {complex = true})
```
I think this works without problems.

**Comment by Natural-Harmonia-Gropius** [comment]
The main thing is not to distinguish between single, double click and press, I want the command of these events to follow input.conf. So I opened this issue.

Nice code, But I foresee using a queue with a debounced processing to implement event handling so as not to burn my brain when I review in the future.

**Comment by avih** [comment]
> ```lua
> function get_key_binding(key)
>     for _, v in ipairs(mp.get_property_native("input-bindings")) do
>         print(v.key, " ", v.cmd)
>         if v.key == key then
>             return v.cmd
>         end
>     end
>     return "ignore"
> end
> ```

This only prints the first binding which it finds for `key`, but there could be more than one, e.g. a default one, one at input.conf, one or more from scripts, etc.

So first thing, to see all of them, just remove the return inside the loop so you'll see it probably prints more than one.

Then, if you want to know which one is the active binding for `key`, then you need to sort them, similar to what `stats.lua` does at page 4 (shift+i, then 4) - https://github.com/mpv-player/mpv/blob/master/player/lua/stats.lua#L434-L447

**Comment by Natural-Harmonia-Gropius** [comment]
Oh, I'm sorry for the trouble I caused you by asking such a question. My mind is in a mess.
