### ISSUE TITLE
Help with Script

### ISSUE THREAD

**Issue by Cananbolt** [mpv-player/mpv#10727]
Below I have the script to pause mpv whenever it is not in focus.

[pause_when_not_focused.txt](https://github.com/mpv-player/mpv/files/9740524/pause_when_not_focused.txt)

This is great, but I would like it to be only activated when video is on. In other words, files such as mp3 (and any other files) that has no video, would **NOT** pause mpv, when it is not focused.

**Comment by christoph-heinrich** [comment]
`mp.get_property_native("current-tracks/video")` gives you a table with information about the currently selected video track.
I think it returns `nil` when there is currently no video track selected.
Pictures also count as video track, so you might want to check the `image` and `albumart` table entries.

**Comment by guidocella** [comment]
You can append this profile to `mpv.conf`:

```
[focus-lost]
profile-cond=get('current-tracks/video/image') == false and not focused
profile-restore=copy
pause
```

**Comment by Cananbolt** [comment]
> `mp.get_property_native("current-tracks/video")` gives you a table with information about the currently selected video track. I think it returns `nil` when there is currently no video track selected. Pictures also count as video track, so you might want to check the `image` and `albumart` table entries.

How can I implement this into the lua script. I apologize I'm not too familiar with lua

**Comment by guidocella** [comment]
You don't need a Lua script to pause an focus. That conditional profile does it. But in Lua you would use `mp.get_property_native("current-tracks/video/image")`.

**Comment by Cananbolt** [comment]
> You can append this profile to `mpv.conf`:
> 
> ```
> [focus-lost]
> profile-cond=get('current-tracks/video/image') == false and not focused
> profile-restore=copy
> pause
> ```

This works however for whatever reason it messes with mpv_thumbnail_script_server

**Comment by christoph-heinrich** [comment]
I can't tell you why thumbnail generation breaks with this, but you could try using https://github.com/po5/thumbfast instead.

**Comment by Cananbolt** [comment]
> > You can append this profile to `mpv.conf`:
> > ```
> > [focus-lost]
> > profile-cond=get('current-tracks/video/image') == false and not focused
> > profile-restore=copy
> > pause
> > ```
> 
> this works great, doesn't pause music, pauses video, but it doesn't pause image slideshow when i use mpv to "play back" a photo album. how would you modify it for it to do that? shouldn't /video/image pause for images?

As I mentioned above, this works however for whatever reason it messes with mpv_thumbnail_script_server.

It does not generate any thumbnails, when this conditioner profile is active. Thanks for the help though

**Comment by guidocella** [comment]
> this works great, doesn't pause music, pauses video, but it doesn't pause image slideshow when i use mpv to "play back" a photo album. how would you modify it for it to do that? shouldn't /video/image pause for images?

`profile-cond=get('current-tracks/video/albumart') == false and not focused`

**Comment by markifi** [comment]
> ('current-tracks/video/albumart') == false and not focused`
that works and pauses image slideshows. apologies OP for hijacking the thread for my purposes. i see this was also mentioned above I didn't know where to include it because I'm new to these configs. cheers

**Comment by Cananbolt** [comment]
> > ('current-tracks/video/albumart') == false and not focused`
> > that works and pauses image slideshows. apologies OP for hijacking the thread for my purposes. i see this was also mentioned above I didn't know where to include it because I'm new to these configs. cheers

Hey no worries, glad you got what you were looking for.

**Comment by Cananbolt** [comment]
> You can append this profile to `mpv.conf`:
> 
> ```
> [focus-lost]
> profile-cond=get('current-tracks/video/image') == false and not focused
> profile-restore=copy
> pause
> ```

I switched over to thumbfast and this works perfectly. Thanks for the help
