### ISSUE TITLE
MPV doesn't support network streams?

### ISSUE THREAD

**Issue by NomaanMalick** [mpv-player/mpv#10725]
I want to stream [this URL](https://ddy1.vhls.ru.com/ddy1/premium369/tracks-v1a1/mono.m3u8?|User-agent=Sportzfy&Referer=https://streamservicehd.click/&cookie=Sportzfy=#Intent;package=com.genuine.leone;end) using MPV on my PC, but copy-pasting the URL to MPV results in a blank MPV window and using `mpv URL` just returns a message saying **'User-agent' is not recognized as an internal or external command, operable program or batch file.**. 

![cookie=Sportzfy=#Intent;package=com genuine leone;end - mpv 10_8_2022 1_07_10 PM](https://user-images.githubusercontent.com/46681247/194696020-dd43f13f-d4f7-4a50-8706-95d4ed9e0378.png)

![Administrator_ Command Prompt - mpv  --script-opts=iptv=1 https___ddy1 vhls ru com_ddy1_premium369_tracks-v1a1_mono m3u8 10_8_2022 1_00_53 PM (1)](https://user-images.githubusercontent.com/46681247/194696001-7e55cfed-624c-4d67-ad37-a35587997d8f.png)

![Administrator_ Command Prompt 10_8_2022 1_01_53 PM](https://user-images.githubusercontent.com/46681247/194696038-ce8cfd6f-ae01-40c2-aa8f-77141b42ccf6.png)

On my phone, I use [this app](https://play.google.com/store/apps/details?id=com.genuine.leone) to automatically play the stream whenever I click the link. I wonder if it is possible to enable this functionality in MPV.

**Comment by guidocella** [comment]
You need to quote the url and also pass it as `--referrer`: `mpv --referrer='https://ddy1.vhls.ru.com/ddy1/premium369/tracks-v1a1/mono.m3u8?%7CUser-agent=Sportzfy&Referer=https://streamservicehd.click/&cookie=Sportzfy=#Intent;package=com.genuine.leone;end' 'https://ddy1.vhls.ru.com/ddy1/premium369/tracks-v1a1/mono.m3u8?%7CUser-agent=Sportzfy&Referer=https://streamservicehd.click/&cookie=Sportzfy=#Intent;package=com.genuine.leone;end'`

**Comment by NomaanMalick** [comment]
> You need to quote the url and also pass it as `--referrer`: `mpv --referrer='https://ddy1.vhls.ru.com/ddy1/premium369/tracks-v1a1/mono.m3u8?%7CUser-agent=Sportzfy&Referer=https://streamservicehd.click/&cookie=Sportzfy=#Intent;package=com.genuine.leone;end' 'https://ddy1.vhls.ru.com/ddy1/premium369/tracks-v1a1/mono.m3u8?%7CUser-agent=Sportzfy&Referer=https://streamservicehd.click/&cookie=Sportzfy=#Intent;package=com.genuine.leone;end'`

It doesn't seem to be working.

![cmd_MdmJZmht9e](https://user-images.githubusercontent.com/46681247/194698766-29637102-5c61-445c-9d6d-496d97ca9eee.png)

**Comment by guidocella** [comment]
You only specified the referrer without the url to play. And it seems that windows cmd requires double quotes.

**Comment by NomaanMalick** [comment]
> You only specified the referrer without the url to play. And it seems that windows cmd requires double quotes.

I see. I only entered the URL once when I needed to enter it twice. Thank you very much!

**Comment by NomaanMalick** [comment]
> You only specified the referrer without the url to play. And it seems that windows cmd requires double quotes.

Hey, can you tell me why [this URL](https://live11p.hotstar.com/hls/live/2024720/icct20wc2022/eng/1540018960/15mindvrm0222826533cfb34fe3bf21986d8555110f18october2022/master_6.m3u8|User-agent=Hotstar;in.startv.hotstar/12.3.7.1141 (Android/10)-M&Cookie=hdntl=exp=1666152186~acl=*icct20wc2022*~id=494d4d5bb86bb5f865ab35d630bcccae~data=ip%3dhkedV7reM2XGUWdDW9pKEr-userid%3dS8ErwELFxykq369VU3DaiErk6rucZwl5aXBwWWgcOUtS-did%3devs9Tfyjlqm1KS1qk1kSPDGiL9YSlTYoSHRbv5agfmJHFFLvOYurXiL-cc%3din-~hmac=dc0051be1950890d1ae7be10b554383ce7a3ec17f7c2fee5cb95d384e7177427) doesn't stream with MPV 
![cmd_3RJRMoeJ2Y](https://user-images.githubusercontent.com/46681247/196368197-1b12c587-8842-445e-85ba-c8bb25e5a80d.png)
but works flawlessly with MX Player on my Android?

https://user-images.githubusercontent.com/46681247/196368712-86979e10-b954-46c7-8ba5-0be76d311394.mp4

**Comment by guidocella** [comment]
It probably requires cookies to authenticate you that only MX Player sends.

**Comment by NomaanMalick** [comment]
> It probably requires cookies to authenticate you that only MX Player sends.

Thanks! I take it that it is not possible to play links like these on PC.

**Comment by guidocella** [comment]
It depends on whether you can extract MX Player's cookies or headers.

**Comment by NomaanMalick** [comment]
> It depends on whether you can extract MX Player's cookies or headers.

How would one go about doing exactly that?

**Comment by guidocella** [comment]
No idea, I don't know anything about MX Player.

**Comment by NomaanMalick** [comment]
> No idea, I don't know anything about MX Player.

Okay, thanks!
