### ISSUE TITLE
Deinterlacing seems to default to a CPU-hungry method on vaapi

### ISSUE THREAD

**Issue by realh** [mpv-player/mpv#10726]
### Important Information

Provide following Information:
- mpv version
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100 (runtime 57.28.100)
   libavcodec      59.18.100 (runtime 59.37.100)
   libavformat     59.16.100 (runtime 59.27.100)
   libswscale      6.4.100 (runtime 6.7.100)
   libavfilter     8.24.100 (runtime 8.44.100)
   libswresample   4.3.100 (runtime 4.7.100)
FFmpeg version: n5.1.2

- Linux Distribution and Version: Arch Linux x86_64
- Source of the mpv binary: Arch package: community/mpv 1:0.34.1-5
- If known which version of mpv introduced the problem: unknown
- Window Manager and version: gnome-shell 42.5 (xorg)
- GPU driver and version: intel-media-driver 22.4.4

### Reproduction steps

My config file contains:
```
vo=gpu
hwdec=vaapi
sub-scale=1
```

I was trying to use mpv to watch a DVB recording (H.264 1080i in a ts) on a 1080p screen. Although combing is barely noticeable at this resolution, enabling deinterlacing with D makes the picture look more stable and fluid. It's kind of shimmery and jerky without deinterlacing.

### Expected behavior

The man page says that with vaapi enabled, using deinterlacing by pressing D should enable the vavpp filter, which should keep the CPU load low.

### Actual behavior

Pressing D results in high CPU usage, almost 100% of a core. The PC is an Intel NUC, so its cooler is inadequate and it starts dropping frames badly due to thermal throttling after a few minutes. If I add `vf=vavpp=interlaced-only` to the config, I get an improvement in picture quality comparable to using D, but without the high CPU load. However, the D key still toggles the other deinterlacing mode, without making a noticeable difference to the picture now, but having a similar big effect on the CPU load as without `vf=vavpp`.

### Log file

First log without `vf=vavpp=interlaced-only`, second log with.

[mpv-no-vavpp.log](https://github.com/mpv-player/mpv/files/9739701/mpv-no-vavpp.log)
[mpv-vavpp.log](https://github.com/mpv-player/mpv/files/9739703/mpv-vavpp.log)

### Sample files

I don't have time to find a good clip to demonstrate the difference in picture quailty and isolate it just at the moment, but if you need one, let me know and I'll do it later.

**Comment by philipl** [comment]
The vaapi deinterlacing was deliberately disabled because of problems on AMD, which are largely sorted out now. It's been reenabled in master for quite a while.

**Comment by haasn** [comment]
It's worth pointing out that recent versions of `libplacebo` have GPU deinterlacing that we could figure out a way to integrate into mpv somehow.
