### ISSUE TITLE
Hybrid graphics (AMD + Intel ) --vaapi-device=/dev/dri/renderD129 doesnt work

### ISSUE THREAD

**Issue by brunogm0** [mpv-player/mpv#10721]
### Important Information

- mpv version  0.34.1
- Linux Garuda Dragonized Gaming Edition 220909 -- updated to latest
- Source of the mpv binary: community/mpv 1:0.34.1-5  [Installed]
- Kwin X11 
- radeon  i965 kernel 5.19.11-zen1-1-zen

### Reproduction steps

 AMD CAICOS old discrete gpu as primary;  dev/dri/renderD128
Intel Ivybridge Integrated as secondary;  dev/dri/renderD129

vainfo by default "sees" CAICOS  gpu: 
```
LIBVA_DRIVER_NAME=radeonsi vainfo
vainfo:` VA-API version: 1.16 (libva 2.15.0)
vainfo: Driver version: Mesa Gallium driver 22.1.7 for AMD CAICOS (DRM 2.50.0 / 5.19.11-zen1-1-zen, LLVM 14.0.6)
vainfo: Supported profile and entrypoints
VAProfileMPEG2Simple            : VAEntrypointVLD
VAProfileMPEG2Main              : VAEntrypointVLD
VAProfileMPEG4Simple            : VAEntrypointVLD
VAProfileMPEG4AdvancedSimple    : VAEntrypointVLD
VAProfileVC1Simple              : VAEntrypointVLD
VAProfileVC1Main                : VAEntrypointVLD
VAProfileVC1Advanced            : VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264Main               : VAEntrypointVLD
VAProfileH264High               : VAEntrypointVLD
VAProfileNone                   : VAEntrypointVideoProc
```

to correct detect  Intel:
```
LIBVA_DRIVER_NAME=i965 vainfo --display drm --device /dev/dri/renderD129
vainfo: VA-API version: 1.16 (libva 2.15.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Ivybridge Desktop - 2.4.1
vainfo: Supported profile and entrypoints
VAProfileMPEG2Simple            : VAEntrypointVLD
VAProfileMPEG2Simple            : VAEntrypointEncSlice
VAProfileMPEG2Main              : VAEntrypointVLD
VAProfileMPEG2Main              : VAEntrypointEncSlice
VAProfileH264ConstrainedBaseline: VAEntrypointVLD
VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
VAProfileH264Main               : VAEntrypointVLD
VAProfileH264Main               : VAEntrypointEncSlice
VAProfileH264High               : VAEntrypointVLD
VAProfileH264High               : VAEntrypointEncSlice
VAProfileH264StereoHigh         : VAEntrypointVLD
VAProfileVC1Simple              : VAEntrypointVLD
VAProfileVC1Main                : VAEntrypointVLD
VAProfileVC1Advanced            : VAEntrypointVLD
VAProfileNone                   : VAEntrypointVideoProc
VAProfileJPEGBaseline           : VAEntrypointVLD
```

Naturally tested in ffmpeg with -hwaccel_device /dev/dri/renderD129  works OK!

Went to test in mpv with:
 LIBVA_DRIVER_NAME=i965  mpv --no-config --vaapi-device=/dev/dri/renderD129 -hwdec=yes   -Any Sample file -

EDIT:
  Tested the other way "LIBVA_DRIVER_NAME=radeonsi mpv --no-config --vaapi-device=/dev/dri/renderD129"   correct hw decode with AMD gpu (renderD128)

the expected error for the previous test as demonstrated by vainfo:
```
LIBVA_DRIVER_NAME=radeonsi vainfo --display drm --device /dev/dri/renderD129
crocus: driver missing
libva error: /usr/lib/dri/radeonsi_drv_video.so init failed
vaInitialize failed with error code 2 (resource allocation failed),exit
```
### Expected behavior

like vainfo to correct initialize the vaapi device , then play

### Actual behavior

the error log is the same as "LIBVA_DRIVER_NAME=i965 vainfo" so expected driver with wrong  device:
```
LIBVA_DRIVER_NAME=i965 vainfo
DRM_IOCTL_I915_GEM_APERTURE failed: No such file or directory
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
libva error: /usr/lib/dri/i965_drv_video.so init failed
vaInitialize failed with error code -1 (unknown libva error),exit
```

 the previous command LIBVA_TRACE:
```
[ctx       none]==========va_TraceInitialize
[22771.926371][ctx       none]=========vaInitialize ret = VA_STATUS_ERROR_UNKNOWN, unknown libva error
[22771.926374][ctx       none]==========va_TraceTerminate
[22771.926383][ctx       none]=========vaTerminate ret = VA_STATUS_SUCCESS, success (no error)
```

### Log file
https://0x0.st/oy1Q.txt

**Comment by philipl** [comment]
`hwdec=vaapi` can only work with the device that is driving the desktop. We identify which render node to use based on which GPU is providing the wayland/x11/gl/vulkan/etc.

If you have working PRIME, so that you have the option of doing render offload to the Intel GPU, then you can turn that on and it will use the Intel VAAPI.

**Comment by brunogm0** [comment]
Since my current PC is a Dell SFF,   iGpu just has VGA or DP (cannot use without adaptor to HDMI). But tried to change iGP as primary in BIOS  with the VGA cable ( many problems about the resolution being artificially limited);
 It boots but at the SDDM login goes black screen but Tty2..3..4 works  after many tries could not proceed in the expected way to desktop.    

Only got desktop by using DVI-hdmi adapter on the AMD card.

    It appears that one have to first load by  "/dev/dri/by-path/pci-0000:00:02.0-render"  since nothing changed between cards even if intel goes first in mkinicpio and the BIOS change;  /dev/dri/renderD129 only works after the previous "initialization" and verified with kernel debug interface renderD129 name is Intel card.   

   Then VAAPi still gets errors init I965 without the LIBVA_DRIVER_name=i965;    Supplying the variable gets vaapi working "somewhat" (logs are a bit convoluted as what is the actual device in use by vaapi-copy after mpv goes to cuda and the like...) as half of the video gets green + magenta artefacts but its not freezing like with AMD card.

Lastly removing the AMD card works perfectly with this file[this sample file](https://blurbusters.com/wp-content/uploads/2019/01/battlefield_1080p_120fps_8mbps.mp4)  that first gave green artefacts and with AMD CAICOS slows to a craw.   
  
Sorry but this VGA with iGPU and my TV is now forcing a wrong resolution of 800x600@56hz by default after SDDM-login.  so had to write this in a linux-live boot.

**Comment by philipl** [comment]
As I said, if you want to use the secondary GPU (whichever one it is) for vaapi, you must also use it to render the application. That means getting PRIME working - which may be true out of the box, or not, depending on your distro (not one I am familiar with).

Here's the arch wiki page on it, which is detailed, but you'll obviously have to adapt it to your distro specifics.

https://wiki.archlinux.org/title/PRIME

Closing as this is a system configuration issue, and not mpv specific.

**Comment by brunogm0** [comment]
Thanks for the help!  
 for other people that search something like this  try Kwin-Wayland  it works both AMD and Intel at the same time.
