### ISSUE TITLE
Mpv cannot exit automatically

### ISSUE THREAD

**Issue by linch0318** [mpv-player/mpv#10722]
### Important Information

Provide following Information:
-  0.34.1
-  win10 21h2

### Reproduction steps

D:\mpv\mpv --start=6544.643 --end=6700.435 videofile
After playing, the interface does not respond and cannot exit automatically
Mpv cannot exit automatically when playing video clips longer than two minutes

**Comment by CounterPillow** [comment]
where is your log file?

**Comment by linch0318** [comment]
> 

[mpv.log](https://github.com/mpv-player/mpv/files/9733277/mpv.log)

**Comment by Dudemanguy** [comment]
Is this still a problem?

**Comment by Dudemanguy** [comment]
No response + old mpv version = close
