### ISSUE TITLE
libavcodec not found (meson)

### ISSUE THREAD

**Issue by mastermach50** [mpv-player/mpv#10739]
mpv - v0.34.1
Windows 10 - 19044.2006 - 21H2
---
I'm new to building stuff by myself. Sorry for any idiocy

### Setup:
- I have Visual Studio Community 2019 with Desktop Development with C++ installed
- I have python 3.8
- I have MSYS2 MinGW
- I did install meson as per the instructions on their site ([this](https://mesonbuild.com/SimpleStart.html))

### Problem:
Running meson build give an error as libavcodec was not found

### Expected behavior
The command runs sucessfully

### Actual behavior
libavcodec not found
```
E:\MPV\mpv>meson build
The Meson build system
Version: 0.63.3
Source dir: E:\MPV\mpv
Build dir: E:\MPV\mpv\build
Build type: native build
Project name: mpv
Project version: 0.34.0-UNKNOWN
C compiler for the host machine: cc (gcc 10.3.0 "cc (Rev5, Built by MSYS2 project) 10.3.0")
C linker for the host machine: cc ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (E:\MSYS2\mingw64\bin\python3.EXE)
Found pkg-config: E:\MSYS2\mingw64\bin\pkg-config.EXE (1.7.4)
Found CMake: C:\Program Files\CMake\bin\cmake.EXE (3.23.3)
Run-time dependency libavcodec found: NO (tried pkgconfig and cmake)

meson.build:19:0: ERROR: Dependency "libavcodec" not found, tried pkgconfig and cmake

A full log can be found at E:\MPV\mpv\build\meson-logs\meson-log.txt
```
### Log file
https://gist.github.com/MasterMach50/dcd479d1d36ef22982d7b564f10f26d8

> I know this is due to missing dependency, but how can I solve this and where can I get the file?

**Comment by MasterMach50** [comment]
I can't change the label to meson

**Comment by LaserEyess** [comment]
libavcodec is part of ffmpeg, you do not have ffmpeg installed.

**Comment by MasterMach50** [comment]
I do have ffmpeg installed, but onli the binaries
i.e ffmpeg.exe, ffprobe.exe, ffplay.exe

**Comment by LaserEyess** [comment]
I think you need to read https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md

Essentially, you need libraries and development headers for all of mpv's dependencies. Usually windows builds do not provide this as most people do not expect you to do development work on Windows, so you're mostly on your own. There are other people who have done a lot of the hard work for you and I think as a starting point you should try their scripts. See for example [shinchiro's build scripts](https://github.com/shinchiro/mpv-winbuild-cmake).

**Comment by PhilippKuhn** [comment]
Hi I have the same problem with Ubuntu 22.04 and FFmpeg installed
