### ISSUE TITLE
Question about bitrate

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#10738]
I get the bitrate of the video by using ${packet-video-bitrate} but as you know, this give me a variable value depending of the segment or scene of the video. Is there a way to obtain the average value like other players and applications do? For example MPC-HC, Avidemux and Freemake Video Converter all give me the same value, it never changes.

**Comment by dexeonify** [comment]
You can always calculate the average bitrate by dividing the file size by duration. This is how Thumbnailer does it:
```lua
local duration, file_size = mp.get_property_native('duration'), mp.get_property_native('file-size')
local bitrate = file_size / duration
```

**Comment by hooke007** [comment]
I'm not sure how other players get the currect video-track's average bitrate.
file_size / duration == the file's average bitrate which including all tracks and attachments.

**Comment by jimmy-1000** [comment]
Sadly don't work.
