### ISSUE TITLE
How to set custom property?

### ISSUE THREAD

**Issue by cerealXDD** [mpv-player/mpv#10732]
Can I set a custom property on the command line or in mpv.conf or in a lua script?

For example can I set 'myproperty' to true

**Comment by guidocella** [comment]
You can only set custom `script-opts`.

**Comment by cerealXDD** [comment]
> You can only set custom `script-opts`.

How do set them? I did 
```
print(mp.set_property('script-opts/hi', 'lol'))
print(mp.get_property('script-opts/hi'))
```
in a lua script and it didnt work.

I also tried ```script-opts=hi=lol``` in mpv.conf and then ```print(mp.get_property('script-opts/hi'))``` in a lua script and it didnt work either

**Comment by guidocella** [comment]
`mp.get_opt(key)`

**Comment by Hrxn** [comment]
@guidocella Is there an equivalent when using IPC?

i.e. this example here:
`echo '{ "command": ["get_property", "playback-time"] }' | socat - /tmp/mpvsocket`

Is there an `"get_opt"` counterpart to `"get_property"`?

**Comment by guidocella** [comment]
`echo '{ "command": ["get_property", "script-opts"] }' | socat - /tmp/mpvsocket | jq -r '.data["key"]'`

**Comment by Hrxn** [comment]
Thanks..

Being able to use `'{ "command": ["get_opt", "key"] }'` would have been nice, but this works as well 😄
