### ISSUE TITLE
How to delete the dmabuf descriptor created by mpv

### ISSUE THREAD

**Issue by 1156175523** [mpv-player/mpv#10737]
### Important Information

Provide following Information:
- mpv version : 0.34.1
- Linux Distribution and Version : Centos 7.6 
  Linux i3-10100 5.4.17-2136.302.7.2.1.el7uek.x86_64 #2 SMP Tue Jan 18 13:44:44 PST 2022 x86_64 x86_64 x86_64 GNU/Linux

### Reproduction steps
When I use the hard decode function, I find that the dmabuf descriptor does not close

### Expected behavior
delete the dmabuf descriptor when quit mpv instance 
### Actual behavior
dmabuf descriptor not delete
![1](https://user-images.githubusercontent.com/33503157/194993180-bb45d4cb-1a73-44d2-b157-c7357d2f2d27.jpg)

### Log file
[mpv-hwdec.log](https://github.com/mpv-player/mpv/files/9750933/mpv-hwdec.log)

### Sample files

```
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <mpv/client.h>
#include <unistd.h>
#include <thread>

static inline void check_error(int status)
{
    if (status < 0) {
        printf("mpv API error: %s\n", mpv_error_string(status));
        exit(1);
    }
}

int stopFunc(mpv_handle* prm)
{
    sleep(25); 
    mpv_handle* pMpv = prm;
    mpv_command_string(pMpv, "quit");
    printf("\033[35mQuit Over!!\033[0m\n");
    return 0;
}

int main(int argc, char *argv[])
{
    if (argc != 2) {
        printf("pass a single media file as argument\n");
        return 1;
    }

    mpv_handle *ctx = mpv_create();
    if (!ctx) {
        printf("failed creating context\n");
        return 1;
    }

    // Enable default key bindings, so the user can actually interact with
    // the player (and e.g. close the window).
    check_error(mpv_set_option_string(ctx, "input-default-bindings", "yes"));
    mpv_set_option_string(ctx, "input-vo-keyboard", "yes");
    int val = 1;
    check_error(mpv_set_option(ctx, "osc", MPV_FORMAT_FLAG, &val));

    //set hardware decode
    check_error(mpv_set_option_string(ctx, "vo", "gpu"));
    check_error(mpv_set_option_string(ctx, "hwdec", "vaapi"));
    check_error(mpv_set_option_string(ctx, "log-file", "mpv-hwdec.log"));

    // Done setting up options.
    check_error(mpv_initialize(ctx));

    // Play this file.
    const char *cmd[] = {"loadfile", argv[1], NULL};
    check_error(mpv_command(ctx, cmd));

    #if 1
    //stop mpv instance later
    std::thread(stopFunc, ctx).detach();
    #endif

    // Let it play, and wait until the user quits.
    while (1) {
        mpv_event *event = mpv_wait_event(ctx, 10000);
        printf("[%s|%d] eventid[%d], event: %s\n", __FUNCTION__, __LINE__, event->event_id, mpv_event_name(event->event_id));
        if (event->event_id == MPV_EVENT_SHUTDOWN)
            break;
    }

    mpv_terminate_destroy(ctx);

    while(1)
    {
        sleep(1);
        printf("debug......\n");
    }
    return 0;
}
```

**Comment by philipl** [comment]
Can you retry with master?

**Comment by 1156175523** [comment]
Thank you for your reply
I encountered the following problems when compiling the latest version of code
What should I do
v0.34.1 mpv is ok
![2](https://user-images.githubusercontent.com/33503157/195011150-d9fa4f99-cbbf-4a1b-ad0a-30e1e27aa4fc.jpg)

**Comment by philipl** [comment]
You need to install libxpresent-dev (or whatever your distro does for headers)

**Comment by 1156175523** [comment]
I found that my system does not support intalled libxpresent-dev
But I found a way to avoid problems：
--gpu-hwdec-interop=no
Based on the above example, adding this configuration will not create dmabuf

**Comment by philipl** [comment]
If you say so, but I see this: https://rhel.pkgs.org/9/epel-x86_64/libXpresent-devel-1.0.0-15.el9.x86_64.rpm.html

Disabling hwdec-interop disables hwdec. I assume you actually wanted hwdec.
