### ISSUE TITLE
Video Stuck?

### ISSUE THREAD

**Issue by lavara123** [mpv-player/mpv#10731]
Provide following Information:
- mpv 0.34.1-dirty
- Linux ArchLinux 5.19.13-arch1-1
- Source of the mpv binary: https://archlinux.org/packages/community/x86_64/mpv/
- Window Manager and version: XFCE 4.16
- NVIDIA Corporation TU117 [GeForce GTX 1650] (rev a1)

- LOG File: https://0x0.st/oty4.txt

- Possible screenshot or video of visual glitches

https://user-images.githubusercontent.com/12005386/194844661-05b032de-92b7-4ba1-946f-46363c5b4dd3.mp4

If the above video is not playing, watch it from the link below
[VIDEO URL](https://dl.dropboxusercontent.com/s/z88omjowxoxipw4/194844661-05b032de-92b7-4ba1-946f-46363c5b4dd3.mp4)

[Alternative URL](https://www.dropbox.com/s/z88omjowxoxipw4/194844661-05b032de-92b7-4ba1-946f-46363c5b4dd3.mp4?dl=0)

**3-5 seconds minor stuttering occurs when the video is paused and started**

**Comment by thebombzen** [comment]
Please attach a log file, and your out2.mp4 appears to be corrupt.

**Comment by lavara123** [comment]
> Please attach a log file, and your out2.mp4 appears to be corrupt.

i updated the issue

**Comment by thebombzen** [comment]
The video you provided didn't even show you using mpv to play the clip.....

**Comment by lavara123** [comment]
> The video you provided didn't even show you using mpv to play the clip.....

Because I changed the design. This is mpv player

**Comment by thebombzen** [comment]
I wonder if this is related to #10716

**Comment by lavara123** [comment]
> I wonder if this is related to #10716

No my display 165 Hz.

I also have this problem with --no-config. 3-5 seconds of minor stuttering then back to normal

**Comment by lavara123** [comment]
@thebombzen It was fixed by uninstalling pulseaudio and installing pipewire instead.

**Comment by thebombzen** [comment]
Looks like it was a pulseaudio bug then.
