### ISSUE TITLE
(Dual Graphics) ibEGL warning: DRI2: failed to authenticate / vulkan: No DRI3 support detected - required for presentation

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#10744]
Hello , 
build mpv with vapoursynth support on ubuntu 20.04
but playback is giving errors;

the system in question has intel graphics hd 620 + amd radeon rx 550; amdgpu driver are installed for opencl and vulkan;

`mpv
mpv 0.34.0-508-gb3d77397eb Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Wed Oct 12 22:27:24 CEST 2022
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: n5.1.2
`

error is the following

libEGL warning: DRI2: failed to authenticate
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

libEGL warning: DRI2: failed to authenticate
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

vulkan: No DRI3 support detected - required for presentation
Note: you can probably enable DRI3 in your Xorg config
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

`glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa/X.org (0xffffffff)
    Device: llvmpipe (LLVM 14.0.1, 256 bits) (0xffffffff)
    Version: 22.1.0
    Accelerated: no
    Video memory: 15716MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Mesa/X.org
OpenGL renderer string: llvmpipe (LLVM 14.0.1, 256 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 22.1.0-devel
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 22.1.0-devel
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.1.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
`

**Comment by CounterPillow** [comment]
>  OpenGL renderer string: llvmpipe (LLVM 14.0.1, 256 bits)

your graphics acceleration is completely broken.

**Comment by mrkapqa** [comment]
hmm, alright, i installed amdgpu, it gave no error, dont know whats going on there.
will have to check, thanks.
