### ISSUE TITLE
Invalid value for option tone-mapping: bt.2446a

### ISSUE THREAD

**Issue by gan-of-culture** [mpv-player/mpv#10740]
### Important Information

Provide following Information:
- mpv version: mpv 0.34.1-dirty
- Linux Distribution and Version: Arch Linux x86_64 | 5.19.13-arch1-1
- Source of the mpv binary: [AUR](https://www.archlinux.de/packages/community/x86_64/mpv)
- If known which version of mpv introduced the problem
- Window Manager and version: DWM | dwm-6.2
- GPU driver and version: Nvidia | Driver Version: 515.76
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

Add the following lines to mpv.conf:
vo=gpu-next
gpu-api=vulkan
hwdec=no
tone-mapping=bt.2446a

I looked into the [docs](https://mpv.io/manual/master/#options-tone-mapping) for more information.

### Expected behavior

mpv runs normally with new tone-mapping settings.

### Actual behavior

Adding tone mapping to mpv.conf stops mpv from starting due to error.

![error.png](https://media.discordapp.net/attachments/554672804578983957/1029482137017122846/unknown.png)

My full config file:
[mpv_conf.txt](https://github.com/mpv-player/mpv/files/9759374/mpv_conf.txt)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/9759333/log.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by quietvoid** [comment]
The option isn't available in version 0.34.1.

**Comment by gan-of-culture** [comment]
Using `mpv-git` fixed my issue. Thanks!
