### ISSUE TITLE
Local video buffering

### ISSUE THREAD

**Issue by sharklasers996** [mpv-player/mpv#10743]
### Important Information

Provide following Information:
- mpv 0.34.1-dirty
- ArchLinux 5.19.13-arch1-1
- Source of the mpv binary: https://archlinux.org/packages/community/x86_64/mpv/

### Reproduction steps

Just playing video from a hard drive

### Actual behavior

At random points in playback, video starts to lag as if it were buffering (video is locally stored), after several seconds it plays normally again. This seems to happen when audio is eac3.

### Log file

I was trying out different options and was getting following message:
```
[cplayer] Audio device underrun detected.
[cplayer]
[cplayer] Audio/Video desynchronisation detected! Possible reasons include too slow
[cplayer] hardware, temporary CPU spikes, broken drivers, and broken files. Audio
[cplayer] position will not match to the video (see A-V status field).
```
But that was a while ago and I can't remember which option made this message show up, without any options behavior is the same (buffering) and whole log can be found here: https://0x0.st/ovjI.log

When message above was issued there were no CPU spikes (at least nothing that htop showed), files aren't broken either - I could play them fine on a different machine.

### Sample files

The video is quite large, around 5Gb, I'm not sure where I could upload it

**Comment by christoph-heinrich** [comment]
I wonder if that's related to https://github.com/mpv-player/mpv/issues/10290.

I have recently noticed the same kind of hanging I had in the issue above when I activate a noise gate, but I haven't looked into it so far.

**Comment by sharklasers996** [comment]
Apparently the issue was that the video I was playing was on an external HDD connected through USB 3.0, moving files to internal HDD fixed the issue, although I'm not entirely sure of the root cause - slow USB or HDD speed?
