### ISSUE TITLE
osc-visibility=dynamic | show osc always in windowed and auto in fullscreen

### ISSUE THREAD

**Issue by navakelvin** [mpv-player/mpv#10741]
### Expected behavior of the wanted feature
The idea is that OSC is "always" visible when you're windowed, and "auto" (visible on mouseover) when you're fullscreen. I think that is ideal behavior.

This value can be called dynamic.

osc-visibility=dynamic

### Alternative behavior of the wanted feature
None, just the one described.

**Comment by guidocella** [comment]
```
[fullscreen]
profile-cond=not fullscreen
profile-restore=copy
script-opts-append=osc-visibility=always
```

Add this to `mpv.conf`.

**Comment by navakelvin** [comment]
> 

This worked very well! Thank you sir.

In addition to that how to make "o" show OSC instead of OSD?

**Comment by guidocella** [comment]
This script will show the OSC for 1 second:

```lua
mp.add_forced_key_binding('o', nil, function ()
    mp.command('script-message osc-visibility always ""')
    mp.add_timeout(1, function ()
        mp.command('script-message osc-visibility auto ""')
    end)
end)
```

You need to put in `~/.config/mpv/scripts` with a `.lua` extension.

**Comment by navakelvin** [comment]
This would work fine. Although excuse me, could it be recreated more similarly to OSD?, That is:

Show OSC while "o" is pressed.

If "o" is released, run mp.add_timeout to return to "auto" in one second.

**Comment by navakelvin** [comment]
> ```lua
> mp.add_key_binding('o', nil, function ()
>     mp.commandv('script-message', 'osc-visibility', require 'mp.utils'.shared_script_property_get('osc-visibility') == 'auto' and 'always' or 'auto', "")
> end)
> ```

This alternates OSC with the letter "o".

I think it's a good option, thanks for the help sir!
