### ISSUE TITLE
[Windows] Accept Global Media Key Controls

### ISSUE THREAD

**Issue by MasterMach50** [mpv-player/mpv#10749]
How can I make mpv accept media key controls (play/pause/next/prev) globally?
I did see solutions for this on mac and linux but not for windows, not anything that feels native at least.

I currently have an AutoHotKey script to do this but it has its limitations and problems.

>I am fine with recompiling mpv for this

**Comment by stax76** [comment]
What kind of limitations and problems?

Here is another issue with AutoHotKey code example:

https://github.com/mpv-player/mpv/issues/9336

In mpv.net a global hotkey feature exist, it's based RegisterHotkey, so has limitations as well.

**Comment by MasterMach50** [comment]
> What kind of limitations and problems?
In AutoHotKey I am  currently using `ControlSend` to send inputs to mpv without activating its window (similar to your script), but I am using an if statement to make sure that either mpv or the player currently active gets the play/pause instruction so for proper usability.

Relevant sections in my script:

**Comment by stax76** [comment]
You can try sending commands using JSON IPC:

https://mpv.io/manual/master/#command-prompt-example

To hide the cmd window, you can use my run-hidden tool:

https://github.com/stax76/run-hidden

It's generally not a feature easy to do, on Windows there is RegisterHotkey which does not cover everything, and a powerful hook API which I would not use as it can make the system unstable when used incorrectly, additionally there is a special WM_APPCOMMAND API for media keys, it's complicated, AutoHotKey deals with all this very nicely and stable, so it's complicated, on Linux maybe even more.

**Comment by MasterMach50** [comment]
So I did hear about mpv.net for windows, it seems fine but what I need is a lightweight player to play some songs while I am playing, so it needs to use as less ram as possible.

Will mpv.net be better in this case?

**Comment by MasterMach50** [comment]
Ok, will do. Thanks for your help

**Comment by BESHOI** [comment]
works for me after i changed mpv.exe to mpv.com

**Comment by BESHOI** [comment]
I recently noticed that the next and previous some times miss with the speed of track instead of next and previous, so i tweaked it a little bit [gist link](https://gist.github.com/BESHOI/9c65f98efb3726d419ad09347dfb7f67l).
