### ISSUE TITLE
Cycling to video stream 0 completely hide mpv, but it still plays the audio!

### ISSUE THREAD

**Issue by markg85** [mpv-player/mpv#10750]
### Important Information

Provide following Information:
```
mpv 0.34.1-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100 (runtime 57.28.100)
   libavcodec      59.18.100 (runtime 59.37.100)
   libavformat     59.16.100 (runtime 59.27.100)
   libswscale      6.4.100 (runtime 6.7.100)
   libavfilter     8.24.100 (runtime 8.44.100)
   libswresample   4.3.100 (runtime 4.7.100)
FFmpeg version: n5.1.1
```
(Archlinux build)

### Reproduction steps
Play a video and press "SHIFT + _" repeatedly till you're on stream 0

### Expected behavior
MPV should either stay with a black tiny screen or whatever. But visible in some way/shape or form. 

### Actual behavior
Bye bye mpv. Gone! It still plays the audio. But MPV is gone from the progress manager, gone from the taskbar, completely gone. Yet it still runs. You can still find it with `ps -aux | grep mpv` and can still kill it with `killall mpv`.

### Additional info
I happen to have a need to adjust the audio delay because of bluetooth earbuds. For that i have to hit `SHIFT <plus> +` or `SHIFT <plus> -` that `-` key happens to be `_` when you press shift which cycles through videos. Thus causing me to really often do the accidental key combination there.

Sidenote here. I strongly suggest to **remove** the video cycle command from `_`. It makes logical sense to have + and - (the two keys after your top numeric keys) be the ones to increase and decrease audio delays. But the multivalue of the `-` key makes that key currently unusable as decrease. The numpad `-` key does work because it only has one value. But some keyboards don't have a numpad block so relying on that is annoying at best.

**Comment by CounterPillow** [comment]
use the `force-window` option

**Comment by markg85** [comment]
That might work if i had known about it before.
Thing is, it's not a default.

If anything at all, an MPV that is completely hidden from the taskbar and even a progress explorer is a bug in my mind. If `force-window` prevents that then perhaps it should be the default.

**Comment by Dudemanguy** [comment]
`force-window` is actually set if you are launching mpv in a pseudo-gui mode (i.e. like with `mpv.desktop`). Typical GUI file managers and the like are supposed to use that. For example, it works for me out of the box when launching a video with `dolphin`. I think you probably should just check your system configuration.

**Comment by markg85** [comment]
Hmm, you are right.
Playing a video from a filebrowser (aka, clicking it which uses .desktop stuff) gives a usability as i'd expect it.
Playing the same on the CLI gives me the described behavior.

I would **still** recommend to enable `force-window` always! And only allow the user to explicitly **disable** it.

**Comment by Dudemanguy** [comment]
Well yes, the described behavior on the CLI is completely intended. If there is no problem with the `.desktop` style of launching mpv, then there's no bug here. You're always welcome to use what configuration you like of course.
