### ISSUE TITLE
Updater doesn't work on Windows 11

### ISSUE THREAD

**Issue by evoserver** [mpv-player/mpv#10759]
-- mpv version mpv-x86_64-20221016-git-cdcbd73
-- Windows 11 22H2 (build 22621.674)

Updater.bat doesn't work. Since Windows 11 the following message appears:

Running script without administrator privileges
Checking Windows PowerShell version -- 5
Fetching RSS feed for mpv
Formato del percorso non valido. (Invalid format of path)

The same happens with administrator privileges.

**Comment by avih** [comment]
The mpv project does not distribute binary builds and does not maintain `updater.bat`.

You didn't say where you downloaded it from, but assuming you downloaded from here https://sourceforge.net/projects/mpv-player-windows/files/ then you should report it here https://github.com/shinchiro/mpv-winbuild-cmake/

Either way, the mpv project has no control over updater.bat.

**Comment by User32bit** [comment]
try delete "settings.xml" in folder with mpv.exe
