### ISSUE TITLE
What is "after creating texture: OpenGL error INVALID_OPERATION"?

### ISSUE THREAD

**Issue by HubKing** [mpv-player/mpv#10754]
My conf file is simple

```
gpu-context=wayland
vo=gpu
hwdec=nvdec
```
It seems that if I use `hwdec=nvdec`, mpv outputs the following for any video

> [e][vo/gpu/opengl] after creating texture: OpenGL error INVALID_OPERATION.

The video seems to be playing fine, so I am not sure what this is. Is this an ignorable error? I am using Wayland + Nvidia's proprietary driver (520.56.06).

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/9795243/output.txt)

**Comment by Dudemanguy** [comment]
Similar to #10324 but this one is actually different. Anyways, if the video works fine you can safely ignore it. Interesting that this would only happen with `hwdec=nvdec`.

**Comment by philipl** [comment]
Yeah, I don't see why it would be related to `hwdec=nvdec`. The location of the error looks related to the output surface rather than any of the video textures. Try with `vo=gpu-next` and/or `gpu-apu=vulkan`. Those are preferable anyway.

**Comment by sfan5** [comment]
More importantly try with `gpu-debug` to get a better indicator where and what kind of error happened.

**Comment by Dudemanguy** [comment]
Possibly doesn't happen anymore since I just moved the egl surface back to where it used to be. Depends on how related this issue was to #10324.
