### ISSUE TITLE
Support for Windows on Arm?

### ISSUE THREAD

**Issue by Glavo** [mpv-player/mpv#10752]
### Expected behavior of the wanted feature

Provides native support for the Windows on Arm platform.

### Alternative behavior of the wanted feature

It is also good to use the Arm64EC ABI as an alternative if this is not possible due to some dependencies.

**Comment by sfan5** [comment]
As far as I know there is nothing preventing mpv from running on Windows/ARM.
Have you tried and ran into problems?

**Comment by Glavo** [comment]
> As far as I know there is nothing preventing mpv from running on Windows/ARM. Have you tried and ran into problems?

Sorry I didn't really try to compile before this.

Just now I tried compiling on my WoA's device and I failed on `waf install`. Here is the log:

[err.log](https://github.com/mpv-player/mpv/files/9795152/err.log)

**Comment by sfan5** [comment]
Looks like an unfortunate naming conflict. Try adding `#undef MemoryBarrier()` to the top of `ra_gl.c`.

**Comment by qyot27** [comment]
Has GCC/Binutils finally added support for AArch64 PE?  Because last I knew, that was one of the largest problems trying to do either native builds with MSys2 or cross-compiles with GCC/MinGW-w64 proper.

[llvm-mingw](https://github.com/mstorsjo/llvm-mingw) supports WoA, though.  I stopped at ffmpeg, but ffplay was able to be built.

**Comment by Glavo** [comment]
> Looks like an unfortunate naming conflict. Try adding `#undef MemoryBarrier` to the top of `ra_gl.c`.

@sfan5 Thanks for your help, I managed to get mpv running on my Snapdragon 850 machine.

![image](https://user-images.githubusercontent.com/20694662/196095854-8cf2521d-119b-4d48-8bec-c80019dd3555.png)

Will the fixes for the aforementioned issues make their way into the mainline?

**Comment by Glavo** [comment]
> Has GCC/Binutils finally added support for AArch64 PE? Because last I knew, that was one of the largest problems trying to do either native builds with MSys2 or cross-compiles with GCC/MinGW-w64 proper.
> 
> [llvm-mingw](https://github.com/mstorsjo/llvm-mingw) supports WoA, though. I stopped at ffmpeg, but ffplay was able to be built.

I am using `mingw-w64-clang-aarch64` to compile. 

This works fine, the only thing that bothers me is that it doesn't seem to be possible to cross-compile on an x86 host.

**Comment by sfan5** [comment]
> Will the fixes for the aforementioned issues make their way into the mainline?

It would be helpful if you opened a PR with the fix since you're also the one who tested it.

**Comment by cowmix** [comment]
Given this: https://github.com/xfangfang/wiliwili/issues/138

Should this issue be closed now?

**Comment by sfan5** [comment]
dunno. Maybe if you tell us what's being discussed in that issue?

**Comment by kasper93** [comment]
Native Windows ARM builds are working fine without any limitations.

**Comment by cowmix** [comment]
@kasper93  - are there any binary distros of the ARM64 builds?
