### ISSUE TITLE
Bug related to Ctrl+h  Toggle hardware video decoding on/off

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#10756]
Ctrl+h (toggle hardware video decoding on/off) doesn't work with the last versions
of mpv posted for Windows, mpv crashes!

### Info:
- mpv version: 0.35.0
- Windows Version: Windows 7 64 bits
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/
- Version of mpv introduced the problem: last versions
- Last version mpv toggle hardware video decoding works: 0.34.0-436-g211ce69f74

### Reproduction steps
Reproduce your issue with --no-config: the issue continues.

### Log file

[logA.txt](https://github.com/mpv-player/mpv/files/9803362/logA.txt)
[logB.txt](https://github.com/mpv-player/mpv/files/9803385/logB.txt)

**Comment by llyyr** [comment]
Are those logs supposed to be when you run `mpv --no-config`? 

`[   0.055][v][cplayer] Setting option 'hwdec' = 'dxva2-copy' (flags = 4)`

**Comment by benrg** [comment]
I am having what I think is the same problem, on a old laptop with GMA 4500 graphics running Win 7 64-bit.

The autoselected hwdec method in working versions is `dxva2-copy`. In newer mpv versions, if I specify `--hwdec=auto` (or press Ctrl+h), mpv silently crashes, but if I specify `--hwdec=dxva2-copy` it still works.

The last SourceForge build that doesn't crash is `0.34.0-468-gba81e4ed88`. The first that does crash is `0.34.0-483-g56e24d535e`.

Looking at the commit history between those versions I see a series of commits by @philipl related to hardware decoding: e50db4292795de511531e764d7e609c1a37a204f, 5629ed81eed90f95a04bb3d8ff64f135bd186651, 989d873d6ec57171a55f432d6f87a9e5a61a706c, 7b84e6fa8988f31e297cbc3adcd8a81e18e63bc8, f221666ade9a60195a37d809973fbc18391306ed. I would guess that one of those is the culprit.

The `-v` log of the crashing version ends abruptly after `[vo/gpu] Loading hwdec driver 'd3d11va'`. The next line in the working version says `[vd] Could not create device.` and it goes on to try other drivers.

[log-works.txt](https://github.com/mpv-player/mpv/files/10121354/log-works.txt)
[log-broken.txt](https://github.com/mpv-player/mpv/files/10121355/log-broken.txt)

**Comment by jimmy-1000** [comment]
> `--hwdec=auto`

It's correct, mpv crashes with --hwdec=auto.

**Comment by jeeb** [comment]
As it seems like I cannot reproduce it on my Win10 system, would be interesting to see the gdb backtrace of these if there could be debug symbols available. For example with https://megumin.fushizen.eu/builds/gdb-8.0.1.7z .

See https://github.com/mpv-player/mpv/issues/9562#issuecomment-986292169 for an example of how to call gdb (you might have to utilize mpv.exe specifically as mpv.com is just a wrapper which outputs the logs).

**Comment by Dudemanguy** [comment]
Is this still an issue?

**Comment by jimmy-1000** [comment]
> Is this still an issue?

Yes, even with the latest mpv.

**Comment by jimmy-1000** [comment]
Fixed in 0.36
