### ISSUE TITLE
applying some extra settings when playing videos from a specific directory

### ISSUE THREAD

**Issue by snoobysnoofy** [mpv-player/mpv#10764]
Like I want to apply `brightness=-10` `contrast=-10` `speed=1.8` while playing my video lectures, they all are in sub-directories inside `~/a/std/`, because they are too bright I want to play with lower brightness, and I want this settings with my other settings in `mpv.config` files.

I don't want this extra settings to be applied when I am watching some other videos so I can't add them in my main mpv.config file.

How can I do this, I also saw mpv profiles, but they can't be activated using GUI.

**Comment by guidocella** [comment]
https://mpv.io/manual/master/#runtime-profiles

Example:

```
[std]
profile-cond(working_directory .. path):match('std') ~= nil
brightness=-10
```
