### ISSUE TITLE
suggestion: ignore wayland desktop fractional scaling factor for video output?

### ISSUE THREAD

**Issue by rezad1393** [mpv-player/mpv#10768]
when I run mpv in a wayland desktop with a fractional scaling, the mpv would see a weird resolution for output.

this is a know bug(not implemented feature) of wayland. 

this made me think that maybe mpv can (at least for now) ignore fractional scaling for video output , or at least when video is full screen.

 so that a on physical screen of, say 1080p, mpv would output would see a 1080p screen regardless of scaling factor.

because scaling factor is not zoom and unlike zoom should only apply to element (scalar like svg and boxes) and not to a picture (video) that cant be zoomed with 100% image fidelity .

**Comment by Dudemanguy** [comment]
It's currently impossible. Right now there are only two choices: listen to whatever scale factor the compositor gives us (the default). If the compositor is doing fractional scaling, then mpv will get a weird resolution. The other option is to completely ignore the scale factor from the compositor (i.e. force a scale factor of 1, you can do this by setting `--no-hi-dpi-window-scale`). The problem with doing this is that the compositor will still scale the mpv window anyway if it is set to any scale factor other than 1. Your only hope is for the fractional scaling protocol so we can finally have a way as a client to opt out of all compositor-side scaling guaranteed.

**Comment by rezad1393** [comment]
oh.
thanks for explaining.

**Comment by rezad1393** [comment]
wait I didn't get the second part.
I thought the compositor didn't do scaling for image.
can mpv get that physical dimensions of my monitor is 1080p or does mpv doesn't see that?
if it does then can it set the dimensions of the video player to that for at least the fullscreen mode? 
are you telling me that mpv cant be like game in fullscreen?

**Comment by Dudemanguy** [comment]
>I thought the compositor didn't do scaling for image.

No. The compositor will always scale the image if fractional scaling is on.

**Comment by rezad1393** [comment]
> > I thought the compositor didn't do scaling for image.
> 
> No. The compositor will always scale the image if fractional scaling is on. There's no way to avoid this.

how do game avoid this? or they dont?

**Comment by Dudemanguy** [comment]
Most games work via x11 which is another can of worms in and of itself, but regardless, they don't.

**Comment by rezad1393** [comment]
> > I thought the compositor didn't do scaling for image.
> 
> No. The compositor will always scale the image if fractional scaling is on. There's no way to avoid this.

sorry 
I didnt know that.
I tought that wayland capable games in full screen would see a complete (non-scaled) window set to physical screen.
maybe I am confusing it with x11 compositors disabling decoration on fullscreen apps.

**Comment by Dudemanguy** [comment]
I'm not really interested in dragging this on forever. Let me repeat again: we **cannot** guarantee that compositor will **not** scale the buffer in the fractional scaling case. Fullscreen, physical dimensions, etc. doesn't matter. Again, the **compositor** does this. Not us. There's nothing we can do about it currently.
