### ISSUE TITLE
[Question] Volume normalization

### ISSUE THREAD

**Issue by GeryHasd32** [mpv-player/mpv#10767]
Does anyone know how to enable volume normalization like the one implemented in SMPlayer?

Thanks for the answer.

**Comment by CounterPillow** [comment]
There are two ffmpeg filters for this which you can use through the `--af` option:
* dynaudnorm: https://ffmpeg.org/ffmpeg-filters.html#dynaudnorm
* loudnorm: https://ffmpeg.org/ffmpeg-filters.html#loudnorm

**Comment by richardpl** [comment]
and speechnorm: https://ffmpeg.org/ffmpeg-filters.html#speechnorm

**Comment by GerryHasd32** [comment]
> There are two ffmpeg filters for this which you can use through the `--af` option:
> 
> * dynaudnorm: https://ffmpeg.org/ffmpeg-filters.html#dynaudnorm
> * loudnorm: https://ffmpeg.org/ffmpeg-filters.html#loudnorm



> and speechnorm: https://ffmpeg.org/ffmpeg-filters.html#speechnorm

Thank you, of course, for the set of links to help informations, but I'm interested in a ready-made, tested variant that works adequately, so that you can write the appropriate parameter in mpv.conf, and not read the documentation and sort through options.

I tried several blanks earlier (I saw them somewhere on github or reddit) with both dynaudnorm and loudnorm, but none of them gave me the desired result.

SMPlayer is built on mpv, so this parameter should work with it as well, maybe someone was looking for it, let me know.

**Comment by richardpl** [comment]
The only normalization I see in code of smplayer is volnorm, very fragile and abandoned filter from mpv side. The only other filter used in smplayer is acompressor without any parameters provided.

**Comment by GerryHasd32** [comment]
> The only normalization I see in code of smplayer is volnorm, very fragile and abandoned filter from mpv side. The only other filter used in smplayer is acompressor without any parameters provided.

Maybe he is very fragile filter, but I was satisfied with his work in the SMPlayer.

Perhaps you know of another ready-made, tested and working parameter for mpv.conf?

**Comment by hooke007** [comment]
I check the lateset version of smplayer and get the following info from log.
```
--af-add=lavfi=[acompressor]
--af-add=@aeq:lavfi=[firequalizer=gain='cubic_interpolate(f)':zero_phase=on:wfunc=tukey:delay=0.027:gain_entry='entry(0,0);entry(62.5,0);entry(125,0);entry(250,0);entry(500,0);entry(1000,0);entry(2000,0);entry(4000,0);entry(8000,0);entry(16000,0)']
```

**Comment by lf94** [comment]
It'd be great if there was simply 3 options to invoke sensible parameters for these three filters! Such as `--normalize="loudnorm"`, etc.

**Comment by richardpl** [comment]
Never use loudnorm in single-pass, it is very bad.

**Comment by lf94** [comment]
It was just a suggestion for a syntax that could be used; and yeah that's even better to only show filters that are most fitting for this case :) I wouldn't know, but people like you do! :D

**Comment by lf94** [comment]
I want to be clear, this option is vital for when playing through personal collections (which I've gone back to doing after abandoning Spotify and Youtube Music). The volume range is extremely variable. Passing a `--normalize` would be so nice on any device.

**Comment by lf94** [comment]
I did a quick 30 minute search around the web for invocations of dynaudnorm (seems to be the appropriate filter for this kind of problem), for anyone curious:

```
dynaudnorm=p=1/sqrt(2):m=100:s=12:g=15
dynaudnorm=f=150
dynaudnorm=f=200
dynaudnorm=p=0.9
dynaudnorm=g=7
dynaudnorm (bare, no parameters applied)
```

**Comment by lf94** [comment]
Using just dynaudnorm on its own is actually sufficient! Testing it here and really there's nothing particularly wrong with it. I would suggest just updating documentation to reflect this, or to make a --normalize option that is just an alias for --af=dynaudnorm.

**Comment by richardpl** [comment]
dynaudnorm is dynamic normalization, and that may not be always wanted, but with big frame sizes and/or gausssize you will get behavior that is very similar but never same to offline normalization in 2 pass.

**Comment by lf94** [comment]
Right, but for the average case I think it's suitable - it's certainly doing the job here!

**Comment by geextahslex** [comment]
I use loudnorm for youtube `af=lavfi=[loudnorm=I=-20]` and dynaudnorm for movies/series `af=lavfi=[dynaudnorm=p=0.65:m=2:f=100:g=15:s=30]`

Dynaudnorm is awesome as it sounds very natural and does not jump all over the place. It works for movies but also music

Loudnorm is not predictable without 2pass, so it can jump up or down and you can notice that. But both have a different sound, sometimes the one works better and vice versa. From what I have read (and also tested myself on 2pass) loudnorm has more treble (sounds brighter) as it weights this frequency more (K-weighting filter) so it is kinda also an "Equalizer"

It's good to have a choice and pick the one that fits more.
