### ISSUE TITLE
Disabling default keybinds in file "input.conf" with one liner

### ISSUE THREAD

**Issue by Arisa-Snowbell** [mpv-player/mpv#10766]
I expect something like if I place "default-keybinds ignore" at first line in input.conf it will disable all default keybinds that are baked into MPV at compile time.
The command argument that is available to us is very impractical for me.
If I do not use the command argument, I must put every default keybind by its own and put ignored, which just bloats the input.conf, and it becomes messy.
And when I don't want the config to be messy, so I don't put ignore to every default keybind I press some random key which I have no idea what it does, so I am forced to restart MPV every time that happens, very inconvenient.

**Comment by avih** [comment]
> I expect something like if I place "default-keybinds ignore"

It's unclear why you would expect this. It's not documented anywhere that input.conf supports such things, and it does not follow the documented syntax of input.conf.

However, it is documented that you can do that with an option from CLI or at mpv.conf - https://mpv.io/manual/master/#options-no-input-builtin-bindings

**Comment by Arisa-Snowbell** [comment]
???
this was feature request

**Comment by avih** [comment]
> this was feature request

And what is this request? that it's not good enough at mpv.conf and you want to support it also at input.conf?
