### ISSUE TITLE
mujs new release breaks mpv build

### ISSUE THREAD

**Issue by zhongfly** [mpv-player/mpv#10765]
### mpv version and platform versions

git master([48ad227](https://github.com/mpv-player/mpv/commit/48ad2278c7a1fc2a9f5520371188911ef044b32c))
archlinux

### Reproduction steps

I'm using https://github.com/shinchiro/mpv-winbuild-cmake to build mpv.
Follow its documentation to setup the build environment and update dependencies, so mujs will use the latest git master([c907989](https://github.com/ccxvii/mujs/commit/c907989bac544843a90aa44669bc60c4e01b043e)) and also the latest release 1.3.1.
Starting the build.

### Expected behavior
Build Success

### Actual behavior
The build failed

### Log file

```
../../../../../src_packages/mpv/player/javascript.c: In function 'get_obj_properties':
../../../../../src_packages/mpv/player/javascript.c:1056:20: error: too few arguments to function 'js_nextiterator'
 1056 |     while ((name = js_nextiterator(J, -1)))
      |                    ^~~~~~~~~~~~~~~
In file included from ../../../../../src_packages/mpv/player/javascript.c:28:
/__w/mpv-winbuild/mpv-winbuild/mpv-winbuild-cmake/build64/install/x86_64-w64-mingw32/include/mujs.h:183:13: note: declared here
  183 | const char *js_nextiterator(js_State *J, int idx, char buf[12]);
      |             ^~~~~~~~~~~~~~~
[211/498] Compiling C object libmpv-2.dll.p/demux_demux_libarchive.c.obj
[212/498] Compiling C object libmpv-2.dll.p/stream_stream_libarchive.c.obj
ninja: build stopped: subcommand failed.
```
This illustrates that [the latest changes to mujs](https://github.com/ccxvii/mujs/commit/c907989bac544843a90aa44669bc60c4e01b043e) require changes to the mpv code as well

**Comment by avih** [comment]
Yes, mujs seems to have changed the public API, I presume accidentally.

I've contacted them and will update here once I have more info. I'm guessing they'll unbreak the API is a future commit, but let's wait and see.

Thanks for the report.

**Comment by avih** [comment]
Also

> mujs new release breaks mpv build

It's not a "new mujs release" which breaks. The last mujs release is from 9 days ago, and that's not broken in mpv.

The last mujs commit on master from 4 _hours_ ago does break mpv currently, and this can happen with building using developer snapshots of the source code between releases.

Regardless though, I'll update here once I have more info.

**Comment by zhongfly** [comment]
> It's not a "new mujs release" which breaks. The last mujs release is from 9 days ago, and that's not broken in mpv.

The last mujs release I said is https://github.com/ccxvii/mujs/releases/tag/1.3.1

**Comment by avih** [comment]
OK, so there was indeed an API change, which had some tags (1.3.1 and later 1.4).

Later, the tags were removed, and the commit which broke the API was replaced (force-pushed).

The state now is that 1.3.1 is the latest tag, which points to the (current) latest commit on master, and which includes the bugfix for https://github.com/ccxvii/mujs/issues/166 but without the previous API breakage.

So both mujs master and the 1.3.1 mujs tag should now work with mpv without any changes on the mpv side.

Can you please confirm this?

**Comment by zhongfly** [comment]
build success now

**Comment by avih** [comment]
Thanks.
