### ISSUE TITLE
The Whole OS crashes when putting computer to sleep/suspend when theres a video playing on mpv

### ISSUE THREAD

**Issue by RadioactiveRadio** [mpv-player/mpv#10778]
### Important Information

- mpv version : 0.34.1
- Linux Distribution and Version : Kubuntu 22.04 LTS
- Source of the mpv binary : Default Ubuntu Repository
- If known which version of mpv introduced the problem
- Window Manager and version : Kde Plasma 5.24.4
- GPU driver and version : Nvidia Proprietory drivers Version 515
- Possible screenshot or video of visual glitches : ![8KhjzVm - Imgur](https://user-images.githubusercontent.com/106451902/197495688-2c6143d5-20fd-458b-8cd7-1c6029c2bbe5.jpg)

Reproduction steps : Step 1 : Play video on mpv (both play/paused)
                             Step 2 : Put computer to sleep. (Same Behaviour on no-config)

Expected behavior : Computer Sleeps and wakes up Normally

Actual behavior : System crashes and has to be force shut off and started again only when playing videos on mpv.

Log file : Can't provide a  relevant log file due to the system crashing when the issue occurs

**Comment by RadioactiveRadio** [comment]
Wow, that was fast

So is there a way to run mpv on cpu to get around this ? Auto suspend is making it worse.

**Comment by thebombzen** [comment]
Your options are to possibly change your video output to vulkan perhaps, but otherwise, no. mpv shouldn't even be able to bring the system down, and it's a panic in `nvidia_uvm` as stated from the log.

Auto-suspend shouldn't be going off when there's a video playing, anyway, because mpv supports the idle inhibit protocol.

**Comment by RadioactiveRadio** [comment]
Thanks. Also how would i change my video output to vulkan? Sorry if it's a stupid question but i'm not very tech savvy.

**Comment by philipl** [comment]
You might also check if you have video memory preservation turned on.

https://download.nvidia.com/XFree86/Linux-x86_64/520.56.06/README/powermanagement.html

This is necessary for playback to survive a suspend/resume cycle, But my understanding is that if it's not configured, you don't crash the kernel - just your app.
