### ISSUE TITLE
Allow setting environment variables from script

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#10772]
### Expected behavior of the wanted feature

I want to write a Rofi script controlling mpv, the way Rofi is designed, it does not allow passing arguments from command line to the script, I need to get large pieces of data into the Rofi script, like all input bindings, right now it looks like I have to resort to passing the data as files, environment variables would have been a more efficient solution I believe, or maybe there is something I'm missing.

**Comment by avih** [comment]
subprocess allows an `env` value which can set env vars...

Is this not enough?

If that's not enough, can you be more specific with an example (lua/js script) where you wish to pass env vars to comething but it's not supported?

**Comment by stax76** [comment]
That was it, what I missed, thanks.

I can't get it working however, code is:

Lua:

```Lua
mp.register_script_message("show-rofi-menu", function (mode)
    if mode == "bindings" then
        mp.command_native({
            name = "subprocess",
            playback_only = false,
            detach = true,
            env = {
                'mpv_rofi_menu_mode=bindings',
                'mpv_rofi_menu_bindings=aaaaaaaaaaaaaaaaaaaaaaaaaa'
            },
            args = { 'rofi', '-modi', 'mpv-menu:/home/frank/.config/rofi/mpv-rofi-menu.py', '-show', 'mpv-menu' },
        })
    end
end)
```

Python:

```
#!/usr/bin/env python3

import os

print(os.getenv("mpv_rofi_menu_bindings"))
print("aaaaaaa")
```

The Rofi menu shows `None` instead of the mpv_rofi_menu_bindings value.

So there is something wrong with the env var passing, maybe a stupid mistake somewhere, I'm still kind of a lua, python, Linux noob...

Unrelated to that, I think I have to convert the input bindings JSON to Base64 in order to pass it, it's about 82 kB in Base64 format, hopefully there isn't a size limit somewhere, and it's not slow to encode and decode.

(Another minor unrelated issue is I don't know yet what is the best file system location for the Python script, making it customizable is easy to do, did that before in other scripts.)

**Comment by avih** [comment]
With your edits and changes, it's not clear to me what the current issue is. I guess it's no longer a request to "Allow setting environment variables from script", right?

> ```lua
>         mp.command_native({
>             name = "subprocess",
>             playback_only = false,
>             detach = true,
>             env = {
>                 'mpv_rofi_menu_mode=bindings',
>                 'mpv_rofi_menu_bindings=aaaaaaaaaaaaaaaaaaaaaaaaaa'
>             },
>             args = { 'rofi', '-modi', 'mpv-menu:/home/frank/.config/rofi/mpv-rofi-menu.py', '-show', 'mpv-menu' },
>         })
> ```

Your invocation seems to set only two vars, which means that the program will see only exactly these two env vars. It won't see others, like `$HOME`. Whether or not that's important to the program depends on the program. Some would care, some won't.

If you want to append two vars to the env instead of replacing it, then, like the docs mention, you need to use `utils.get_env_list()`, and append to this list (or replace elements in it), and then use it in subprocess.

**Comment by stax76** [comment]
I don't seem to be able of making the code work. Also struggling with a larger real live problem since a while and feeling not particular well today. Need to quit for today. Thank you trying to help avih.

**Comment by avih** [comment]
Right, feel well, and ping me here if you need further help. Do also mention if it's solved

**Comment by stax76** [comment]
Thanks, after a break code works now, among the things was a poorly named function, I remember that I had exactly the same problem with it before, finally renamed it now, making it clearer what it does.

**Comment by avih** [comment]
Nice.
