### ISSUE TITLE
reset `start` in watch later cache file when EOF

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#10776]
1. start mpv with `save-position-on-quit=yes` and `keep-open=yes`
2. play a video and let it reach the end
3. exit and re-run mpv to play the same file
4. the video paused at the last frame

### Expected behavior of the wanted feature

the video should start from the 00:00:00 instead of 'paused at the last frame'

### Log file

N/A
Not a bug

**Comment by thebombzen** [comment]
I don't see why changing this behavior is better than the existing behavior. If someone pushes Shift+Q when paused on the last frame, ideally it should restore back to where they were.

**Comment by hooke007** [comment]
I opened every file in my device, all of them paused at the last frame, I believe nobody would think it is a reasonable behavior.

**Comment by thebombzen** [comment]
This is exactly what I'd expect to happen if you had `save-position-on-quit=yes` set when running mpv.

**Comment by dexeonify** [comment]
There's a workaround for this in https://github.com/mpv-player/mpv/issues/2045#issuecomment-1125025340

**Comment by hooke007** [comment]
> ...unless you want to save the other states and only change the start paramater?

Yes and that's why I renamed the issue's title.

**Comment by hooke007** [comment]
Do you mean ——
```
[no saving start eof]
profile-cond=eof_reached
watch-later-options-remove=start
```
But `start` would never be removed.
