### ISSUE TITLE
Streaming stops

### ISSUE THREAD

**Issue by zecarlosalmeida** [mpv-player/mpv#1077]
Hi.
I use mpv to playback various radios streamings, but sometimes the streaming stops, and i have to run the command again. My command is: mpv.exe -loop inf --no-video -ao dsound:device=1   http://sl.dnip.com.br:25690 -cache=64.
Thanks.

**Comment by c-e-p-x-u-o** [comment]
--network-timeout=2 make mpv to restart a stream on disconnect, but only once
with --loop-playlist it restart only 3 (three) times instead of infinity.

workaround:
while true; do mpv --network-timeout=2 http://stream; done
