### ISSUE TITLE
Question: How to disable "watchlater" for specific URLs?

### ISSUE THREAD

**Issue by mortyobnoxious** [mpv-player/mpv#10780]
How can i disable watchlater data for certain urls?
For example like this:
`http://127.0.0.1:6878/ace/getstream?id=`

I tried profiles like this, but it always resume where it left.
```
[AceStream]
profile-cond=path:match('getstream') ~= nil
no-resume-playback
```

**Comment by guidocella** [comment]
`no-resume-playback` doesn't have effect at the time profile conditions are evaluated, but you can avoid saving watch later config files on certain paths with `save-position-on-quit=no`.

**Comment by mortyobnoxious** [comment]
That doesn't work, too.

On the console, it says it applied the profile but still resumes.
