### ISSUE TITLE
sub-blur does not blur subtitles if sub-border-size > 0

### ISSUE THREAD

**Issue by FuzzyWuzzyBMP** [mpv-player/mpv#10784]
If `sub-border-size > 0`, only the border is blurred, leaving the subtitles themselves distractingly sharp. Issue occurs with both SRT and ASS subtitles.

### Reproduction steps & actual behavior
Example mpv.conf files, and the result for SRT subtitles:
```
sub-border-size=2.5
sub-blur=1.0
```
![sharp](https://user-images.githubusercontent.com/13451773/197657106-b13192b8-4f8c-42e3-8e86-f5e58ed4cf26.jpg)

```
sub-border-size=0
sub-blur=1.0
```
![blurry](https://user-images.githubusercontent.com/13451773/197657069-b8b8a224-6a91-4a2d-bc2c-e40b87fa857f.jpg)

### Expected behavior
Both the subtitles and the border would be blurred when `sub-border-size > 0`. Or, ideally, there would be distinct flags for subtitle vs. border blur, e.g. `sub-blur` and `sub-border-blur`

### Important Information
mpv version: 0.34.1
Platform: Ubuntu 22.04
Source of the mpv binary: default apt repository

**Comment by hooke007** [comment]
Not a bug

https://aeg-dev.github.io/AegiSite/docs/3.2/ass_tags/#:~:text=Blur%20edges

**Comment by hooke007** [comment]
Regardless of whether this is a bug report or feature request, it should be created in the [libass](https://github.com/libass/libass) repo instead.

**Comment by FuzzyWuzzyBMP** [comment]
I'll do so, thanks. Shall I leave this issue open so that, once libass fixes the issue, mpv can be brought in sync?

**Comment by TheOneric** [comment]
> leaving the subtitles themselves distractingly sharp.

If your blur overrides aim at making subs appear similar to the video resolution, there's a much better way. Setting `--blend-subtitles=video` will actually render subs at video resolution and then scale them together with the decoded video frame.

**Comment by DreamHollow** [comment]
It might not hurt to clarify that this is more of a suggestion than a bug, considering the issue is still flagged as open.

**Comment by FuzzyWuzzyBMP** [comment]
Closing as some flavor of wontfix, since this is how the libass library behaves, which already supports a, somewhat involved, method of blurring both text and borders, per https://github.com/libass/libass/issues/656#issuecomment-1295996795

As much as it would be the right thing to have such a look by default, that is an uphill battle I don't currently wish to wage.

**Comment by FuzzyWuzzyBMP** [comment]
Closing as some flavor of wontfix, since this is how the libass library behaves, which already supports a, somewhat involved, method of blurring both text and borders, per https://github.com/libass/libass/issues/656#issuecomment-1295996795

As much as it would be the right thing to have such a look by default, that is an uphill battle I don't currently wish to wage.
