### ISSUE TITLE
[ASS Subtitle] Normalize timestamps like Aegisub

### ISSUE THREAD

**Issue by moi15moi** [mpv-player/mpv#10783]
### Expected behavior of the wanted feature
MPV should maybe normalize the timestamps of the video to display an .ass file.

> What means normalize the timestamps?

It means the first frame will have a timestamps of 0 ms.

Example:
If the timestamps look like this:
```
# timestamp format v2
10000
10042
etc...
```

Then, the normalize timestamps would look like that:
```
# timestamp format v2
0
42
etc...
```

[Here is how Aegisub implemented it](https://github.com/TypesettingTools/Aegisub/blob/8336c7d97cdec30103f301c446d7b970480abbf3/libaegisub/common/vfr.cpp#L48-L53)

> Why should it normalize the timestamps?

[Aegisub](https://github.com/TypesettingTools/Aegisub), the most used program for editing .ass subtitle, normalize the timestamps.
This means that currently, **if the first video timestamps does not start at 0**, the subtitle will not be render at the exact same frame between MPV and Aegisub.

> Why it should maybe not normalize the timestamps?

Currently, there is an issue opened about this problem on Aegisub repos.
See: https://github.com/TypesettingTools/Aegisub/issues/21

But, [since 2010](https://github.com/TypesettingTools/Aegisub/commit/1dedfb18cd62f006c39f76ce298f4a3157607271), Aegisub has always normalize the timestamps, so if mpv does not normalize it, it can cause an different timing rendering.

> Then, what should mpv does? Should it implement the normalize option or not?

I created this issue, because I wanted to let know the mpv developpers about this possible problem.
I am not 100% sure if it should normalize the timestamps like Aegisub or not.

> How to test the different rendering between Aegisub and MPV?

The easiest solution is to use an mkv video and apply this command with [mkvmerge](https://mkvtoolnix.download/):
```mkvmerge --output OUTPUT.MKV --sync VIDEO_ID:ANY_NUMBER_ABOVE_0 INPUT.MKV```

It will delay the timestamps. The important is that the first timestamps does not start at 0 and if the video fps is 24000/1001, you should at least wrote >42ms to see an difference between Aegisub rendering and mpv rendering.

Then, open Aegisub and create a few lines and save the subtitle.

Finally, open the video and the .ass subtitle with MPV and you will be able to see that the subtitles will not be rendered at the same frame.

**Comment by thebombzen** [comment]
mpv does rebase start times. `--rebase-start-time=yes` is on by default and it shifts it so the start of playback is at timestamp 0.

**Comment by moi15moi** [comment]
I should have mentionned it, but yes, [--rebase-start-time=yes](https://mpv.io/manual/master/#options-rebase-start-time) seems to be the equivalent of what I am talking about.


Here is an sample to test what I said: [Sample.zip](https://github.com/mpv-player/mpv/files/9942555/Sample.zip)
MPV - The subs will be not sync with the video.
Aegisub - The subs will be sync to the video.
The first timestamps of this video is ``1000 ms``.

> Are you attempting to play back a file where the video stream doesn't start at timestamp 0 but the subtitle stream does? That's a corrupt file and it's the fault of whoever muxed it.

I said that Aegisub always normalize/rebase the timestamps, so the ass subtitle stream will always start at 0. That's not really corrupt, it is only like that the Aegisub works.

**Comment by thebombzen** [comment]
You'll have to remux the input file as `--rebase-start-time` slides the timestamps of all tracks equally to prevent any of them from desyncing.

**Comment by moi15moi** [comment]
> Remux the input file as `--rebase-start-time`.

What do you mean?
Can you provide an example?




> Alternatively you can set `--sub-delay`.

I don't think this is an good idea. Any .ass works like that. I don't see why the user should be the one to apply an delay when mpv should do it automatically.

**Comment by thebombzen** [comment]
`ffmpeg -i input.mkv -map 0 -c copy output.mkv`
Would be one way to do it.

If you're using aegisub you're authoring a file, so you are not an end user. And the reason it doesn't do it automatically is, as I explained, `mpv` slides the timestamps of all tracks equally to prevent any of them from desyncing.

**Comment by moi15moi** [comment]
> `ffmpeg -i input.mkv -map 0 -c copy output.mkv` Would be one way to do it.

I just tested it and it doesn't work, but, anyways, ``mkvmerge --output OUTPUT.MKV --sync VIDEO_ID:FIRST_TIMESTAMPS_*_-1 INPUT.MKV`` does what you mean.

> And the reason it doesn't do it automatically is, as I explained, `mpv` slides the timestamps of all tracks equally to prevent any of them from desyncing.

Ok, so in brief, you are saying that it is not mpv job to works has Aegisub.
Then, the issue is closed.
