### ISSUE TITLE
Configuration checks for too low Pipewire version

### ISSUE THREAD

**Issue by TheOneric** [mpv-player/mpv#10786]
**mpv version**: 050f5e7915045a28ada36c55bf817b8f909020ae
**build system** tested waf, but meson appears to be affected as well

### Reproduction steps

Have libpipewire-0.3 development files installed, for a version lower  than `0.3.44` and run `./waf configure`. *(In my case it's `0.3.19`.)* It will autodetect Pipewire support, but during building fail with
```
../audio/out/ao_pipewire.c: In function ‘init’:
../audio/out/ao_pipewire.c:464:9: error: ‘PW_KEY_TARGET_OBJECT’ undeclared (first use in this function)
  464 |         PW_KEY_TARGET_OBJECT, ao->device,
      |         ^~~~~~~~~~~~~~~~~~~~
../audio/out/ao_pipewire.c:464:9: note: each undeclared identifier is reported only once for each function it appears in
```

This macro was added in [pipewire@9935f921c](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/9935f921c512f1b3eec9f1608e86d13560ffa27c) first contained in release `0.3.44`.

### Expected behavior

Either raise the version checked during configuration or `#ifdef` usage of newer symbols than what's checked in configuration.
If raising the checked version to `0.3.44` (effectively disabling pipewire) the build succeeds again for me.

### Relevant Config Log file excerpt
```
Checking for PipeWire audio output
['/usr/bin/pkg-config', 'libpipewire-0.3 >= 0.3.0', '--libs', '--cflags', 'libpipewire-0.3']
out: -D_REENTRANT -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -lpipewire-0.3

yes
```

**Comment by jeeb** [comment]
Yup, seems like a version bump was forgotten in 5e49c09f2ea2bcf6d993abf0fe839d5d7e0cad15 .
