### ISSUE TITLE
gpu-api=none or gpu-context=wldmabuf crashes with vo_gpu or vo_gpu_next

### ISSUE THREAD

**Issue by llyyr** [mpv-player/mpv#10793]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.34.1+git.20221026T222031.e0c4193e Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Wed Oct 26 12:00:00 2022
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.2
```

### Expected behavior

mpv should output an error message that wldmabuf can only be used with vo_dmabuf_wayland

### Actual behavior

vo_gpu crashes with ```mpv: ../video/out/vo_gpu.c:302: preinit: Assertion `p->ctx->swapchain' failed.```
vo_gpu_next segfaults with no error message

**Comment by Dudemanguy** [comment]
I'm leaning towards reworking the ra_ctx creation in a way that doesn't expose these pointless options on the cli.

**Comment by llyyr** [comment]
Yeah, you can't actually use wldmabuf so that might be for the best
