### ISSUE TITLE
Phillips Hue sync not working with hdr

### ISSUE THREAD

**Issue by MER42** [mpv-player/mpv#10790]
### Important Information

Provide following Information:
- mpv version: x86_64-20221016
- Windows Version: Win 10 pro 19043.2130

# High quality video rendering for fast computer. 
profile=gpu-hq 
deband=no
gpu-api=vulkan
spirv-compiler
target-trc=auto
target-colorspace-hint
vo=gpu-next

audio-channels=6

With this settings hdr (which is what i got the player for) works fine (i guess) but syncing my room lights wont work anymore.
Im pretty sure it has to do with the target colorspace hint cause when i added it everytime i go to full screen my monitor turns black for 2 seconds and then show picture again. without it it works but hdr looks bad. same with hue sync. works without the parameter but thats not the experience i wanted to have
please help :))

**Comment by LaserEyess** [comment]
And why do you think this is an mpv issue?

**Comment by MER42** [comment]
because it works once i delete the line with targe colorspace hint

**Comment by MER42** [comment]
but then colors wont look as good

**Comment by MER42** [comment]
and also if i click something on my second monitor while mpv is in full screen hdr is switched of

**Comment by Dudemanguy** [comment]
There is pretty close to a 0% chance that mpv has anything to do with your lamp.
