### ISSUE TITLE
mpv loses audio/sub sync (and laggy video) when pause/resume the video

### ISSUE THREAD

**Issue by evilsh3ll** [mpv-player/mpv#10795]
### Important Information

Provide following Information:
- mpv version: mpv (1:0.34.1-5)
- Linux Distribution and Version: Arch Linux (all software up to date)
- Source of the mpv binary: Arch Linux Community Repository
- If known which version of mpv introduced the problem: I don't know but I have this problem for 2-3 months
- Window Manager and version: Xfwm4 (XFCE)
- GPU driver and version: NVIDIA 520.56.06 (dkms package)
- Possible screenshot or video of visual glitches: it's an audio/subtitle problem

The problem is seems not OS related because if I use another OS or if I open the same video but using VLC player, the problem doesn't show up

### Reproduction steps
Reproducing the issue isn't deterministic, it seems a buffer related problem. Anyway:
1) open a video and watch for 10-20min
2) pause and play the video again.
### Expected behavior
The video should play as was before
### Actual behavior
After playing again the video, its audio/subtitles will be be out of sync and the video will be laggy. After about 10-15s the video returns normal.
### Log file
I played the file until 2m:30s than I pause the video and after playing again it got desynced. Then after around 10s it returns synced.
Log: https://bin.disroot.org/?047d12929996d5a1#2Febx6DaqaDp5HGaGEuRUT2qYWLBRpF5h8e371j4etSS
### Sample files
I don't know, every file has this problem. It seems that very small files (maybe video of a few megabytes) have this problem more rarely or don't have the problem at all.

**Comment by qyot27** [comment]
Stock Ubuntu 22.04 did this (or at least something very similar) to me before I took steps to switch it to using pipewire.  Since pipewire is now the default on 22.10, I've not had to do the same.  So I mean, it's not out of the question that something within the last year broke pulse's handling of this sort of thing.

**Comment by stax76** [comment]
I'm getting it too in Ubuntu 22.04, what steps did you take? What I found so far is a guide here:

https://askubuntu.com/questions/1333404/how-to-replace-pulseaudio-with-pipewire-on-ubuntu-21-04

Hopefully I won't do something wrong and create an even bigger issue, my Linux experience isn't more than a couple of weeks.

**Comment by qyot27** [comment]
I'd followed https://ubuntuhandbook.org/index.php/2022/04/pipewire-replace-pulseaudio-ubuntu-2204/

**Comment by stax76** [comment]
I had tried the accepted answer at the askubuntu thread, which did not work, the answer below suggested the project which worked:

https://github.com/pipewire-debian/pipewire-debian/

**Comment by evilsh3ll** [comment]
> I'm having a very similar problem, and had it for a long time. Except the a/v lag is easier to trigger, and seems to fix itself after a few seconds. Also Arch Linux. All videos (network and local) are affected.
> 
> Try
> 
> ```
> ao=alsa
> ```
> 
> It seems to have fixed it. And even though I'm using pulseaudio, everything is still working, bluetooth speakers etc.

ok but where should I put the `ao=alsa` configuration?

**Comment by evilsh3ll** [comment]
> I'm having a very similar problem, and had it for a long time. Except the a/v lag is easier to trigger, and seems to fix itself after a few seconds. Also Arch Linux. All videos (network and local) are affected.
> 
> Try
> 
> ```
> ao=alsa
> ```
> 
> It seems to have fixed it. And even though I'm using pulseaudio, everything is still working, bluetooth speakers etc.

this mpv config seems to fix the problem

**Comment by evilsh3ll** [comment]
update:


> > I'm having a very similar problem, and had it for a long time. Except the a/v lag is easier to trigger, and seems to fix itself after a few seconds. Also Arch Linux. All videos (network and local) are affected.
> > Try
> > ```
> > ao=alsa
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems to have fixed it. And even though I'm using pulseaudio, everything is still working, bluetooth speakers etc.
> 
> this mpv config seems to fix the problem

update: this config doesn't solve the problem, it seems that 70-80% works but sometimes it keeps happening (most frequent in big size videos)

**Comment by evilsh3ll** [comment]
> > I'm having a very similar problem, and had it for a long time. Except the a/v lag is easier to trigger, and seems to fix itself after a few seconds. Also Arch Linux. All videos (network and local) are affected.
> > Try
> > ```
> > ao=alsa
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems to have fixed it. And even though I'm using pulseaudio, everything is still working, bluetooth speakers etc.
> 
> this mpv config seems to fix the problem

update: this config doesn't solve the problem, it fixes audio desync but lag after play/pause of the video is still present

**Comment by evilsh3ll** [comment]
> I'm having a very similar problem, and had it for a long time. Except the a/v lag is easier to trigger, and seems to fix itself after a few seconds. Also Arch Linux. All videos (network and local) are affected.
> 
> Try
> 
> ```
> ao=alsa
> ```
> 
> It seems to have fixed it. And even though I'm using pulseaudio, everything is still working, bluetooth speakers etc.
update: this config doesn't solve the problem, it fixes audio desync but lag after play/pause of the video is still present. Do you think the problem is related to pulseaudio?

**Comment by arsalanrez** [comment]
`ao=alsa`  is already removed from MPV until release 0.23.0

problem exist in _Arch linux_ but I check it on **win 10** there is _no any problem_ like that on it.

**Comment by evilsh3ll** [comment]
I can confirm too that the latest version of mpv in archlinux (updated to today) still has this problem

**Comment by Dudemanguy** [comment]
If anyone has this problem, it's because of pulseaudio. You can workaround it with `--pulse-latency-hacks` or use another `ao`.
