### ISSUE TITLE
Новый драйвер Nvidia+Lively Wallpaper+mpv

### ISSUE THREAD

**Issue by Tappachka** [mpv-player/mpv#10809]
Lively Wallpaper использует mpv для воспроизводства "Живых обоев" зацикленного видео.
После установки драйвера от Nvidia версии 522,25 появляется проблема загрузки GPU на 100%
Процесс mpv, Lively, Диспетчер окон рабочего стола . загружается на 100% в производительности 100% 3D
Если отключить процессы mpv, Lively то нагрузка полностью уходит на Диспетчер окон рабочего стола = 100%
После переустановки драйвера от Nvidia скачав с сайта производителя видеокарты, версии  496.13, проблема уходит и процесс mpv, Lively загружают GPU как обычно на 4-5%.
27,10,2022 вышел новый драйвер от Nvidia 526,47, после обновления проблема возвращается загрузки GPU на 100%
Вновь откатил драйвер на 496.13.
Видеокарта GIGABYTE GeForce® GTX 1660 Ti OC 6G
ОС Windows 10 Pro 21H2 19044.2130
_____________________________________________________
Lively Wallpaper uses mpv to reproduce the "Live Wallpaper" of a looped video.
After installing the driver from Nvidia version 522.25, there is a problem loading the GPU at 100%
mpv process, Lively, Desktop Window Manager . loaded at 100% in 100% 3D performance
If you disable mpv, Lively processes, then the load completely goes to the Desktop Window Manager = 100%
After reinstalling the Nvidia driver by downloading from the video card manufacturer's website, version 496.13, the problem goes away and the mpv process, Lively loads the GPU as usual by 4-5%.
27,10,2022 a new driver from Nvidia 526,47 was released, after the update, the problem returns GPU loading to 100%
Rolled back the driver to 496.13 again.
GIGABYTE GeForce ® GTX 1660 Ti OC 6G graphics card
OS Windows 10 Pro 21H2 19044.2130
![версии  496 13](https://user-images.githubusercontent.com/116968991/198844558-8afba6e5-9dc6-4848-ab89-c62fa0219bb2.png)
![версия 526,47 диспетчер 1](https://user-images.githubusercontent.com/116968991/198844566-8fc37c56-bece-4c54-be68-66c705e1e44a.png)
![версия 526,47 диспетчер 2](https://user-images.githubusercontent.com/116968991/198844576-bbca1ab5-219e-4056-a193-3143df21d61e.png)
![версия 526,47 диспетчер 3](https://user-images.githubusercontent.com/116968991/198844579-c78dd3f0-b2e4-4fe3-b316-d15eb71a9450.png)
![версия 526,47](https://user-images.githubusercontent.com/116968991/198844585-92a71b58-f068-4d13-8d3b-001e1ba293ed.png)

**Comment by hooke007** [comment]
Shouldn't it be a driver issue?
Can you reproduce the issue by using the mpv alone?

**Comment by Tappachka** [comment]
I wrote to nvideo, but unfortunately, due to US sanctions, they refuse to consider the letter. If there is time, I will try to reproduce it.

**Comment by Tappachka** [comment]
Скачал последнюю версию 32-бит mpv. Без записи экрана при воспроизведении ситуация аналогичная 100%
![Без записи экрана](https://user-images.githubusercontent.com/116968991/198872735-5d1dce90-d211-44ef-9df1-9409ff7d9e22.png)
драйвер 496.13 
![нормальный драйвер](https://user-images.githubusercontent.com/116968991/198873150-1f32f39d-4644-40f1-b5a1-3c5ba219d830.png)

При записи с помощью OBS нагрузка распределяется иначе. Все же 10-20% много
https://www.youtube.com/watch?v=pkKR6V-F6QM
Проблема однозначно в драйвере

Downloaded the latest version of 32-bit mpv. Without recording the screen during playback, the situation is similar 100%
driver 496.13
When writing with OBS, the load is distributed differently. Still 10-20% is a lot
The problem is definitely in the driver

**Comment by Dudemanguy** [comment]
Closing since it's a driver problem.
