### ISSUE TITLE
mpv without jack? jack/jack.h: No such file or directory

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#10804]
I have some audio problems and I wanted to avoid all of jack, pipewire as well as pulseaudio so only alsa support.

However had when I try to compile mpv, it tells me I need to have jack:

    ../audio/out/ao_jack.c:41:10: fatal error: jack/jack.h: No such file or directory

Is there a way without that as a mandatory dependency?

**Comment by Dudemanguy** [comment]
Post your actual configure/build log, but no jack is not required. It's a build option.
