### ISSUE TITLE
gpu-next: background transparency seems unimplemented

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#10815]
### Important Information

```
mpv 0.34.0-555-gd3a28f12c9 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sun Oct 30 02:27:54 2022
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: n5.1.2
```
Compiled from master on archlinux + wayland + intel GPU

### Reproduction steps

Run the following command

```
mpv --no-config --pause --vo=gpu-next --background=0/0 --alpha=yes --geometry=1000x400 any_image.png
```
The input image must have a different aspect ratio than the specified geometry, such that the background (or "black bars" as referred to in the manual) is visible.
Note that other alpha values trigger the same bug.

### Expected behavior

The black bars are entirely transparent, since a background alpha of 0 is specified.

### Actual behavior

The black bars are visible and entirely opaque.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/9896182/log.txt)

**Comment by haasn** [comment]
Does it work with `--gpu-api=vulkan`?

**Comment by occivink** [comment]
With `--vo=gpu-next` it does not, but with `--vo=gpu` it does.
