### ISSUE TITLE
mpv no longer builds for windows under mxe

### ISSUE THREAD

**Issue by mrdaemon** [mpv-player/mpv#10813]
### mpv version and platform versions

Building for windows using latest version of mxe for 64 bits setup according to documentation.
Previous environment was scrapped and started fresh after initial encounter of issue (fresh checkout of mxe repo), but issue remains.

Building mpv from master at commit 89bd6ead6c6f710c42ce2f6f4c5abdb157090761 (head at the time of writing).

Build environment is Ubuntu 20.04.5 LTS, on wsl 1.

### Reproduction steps

Setup mxe environment as per documentation, fresh clone of `mxe` repo under `/opt/toolchains/mxe`, configuration is as follows:

```
$ cat /opt/toolchains/mxe/settings.mk
JOBS := 17
MXE_TARGETS := x86_64-w64-mingw32.static
```

Dependencies installed:

`$ make gcc ffmpeg libass jpeg lua luajit`

Clean build using the following steps:

```
(mpv) $ git pull
(mpv) $ rm -rf waf .waf3-2.0.24-c88b74123ce8b9d1a27999f7cf96dff0/ build/
```

Build using the following shell script for consistency:
```
$ cat cross-build.sh
#!/usr/bin/env bash

export PATH="/opt/toolchains/mxe/usr/bin:$PATH"

export DEST_OS=win32
export TARGET=x86_64-w64-mingw32.static

if [ ! -f ./waf ] ; then
    ./bootstrap.py || exit 1
fi

./waf configure && ./waf build && strip ./build/mpv.exe

ls -lh build/mpv.exe &&
file build/mpv.exe
```

### Expected behavior

A shiny, humongous, static PE binary for windows that I can then put somewhere in `%PATH%`.

### Actual behavior

Build failure:

```
[128/229] Compiling audio/out/ao_wasapi.c
../video/fmt-conversion.c:70:21: error: 'AV_PIX_FMT_VULKAN' undeclared here (not in a function); did you mean 'AV_PIX_FMT_CUDA'?
   70 |     {IMGFMT_VULKAN, AV_PIX_FMT_VULKAN},
      |                     ^~~~~~~~~~~~~~~~~
      |                     AV_PIX_FMT_CUDA

../common/encode_lavc.c: In function 'encode_lavc_init':
../common/encode_lavc.c:158:23: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  158 |     p->muxer->oformat = ctx->oformat;
      |                       ^
../common/encode_lavc.c: In function 'find_codec_for':
../common/encode_lavc.c:752:56: warning: passing argument 1 of 'av_guess_codec' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  752 |         codec = avcodec_find_encoder(av_guess_codec(ctx->oformat, NULL,
      |                                                     ~~~^~~~~~~~~
In file included from ../common/encode_lavc.h:28,
                 from ../common/encode_lavc.c:27:
/opt/toolchains/mxe/usr/x86_64-w64-mingw32.static/include/libavformat/avformat.h:2704:58: note: expected 'AVOutputFormat *' but argument is of type 'const AVOutputFormat *'
 2704 | enum AVCodecID av_guess_codec(ff_const59 AVOutputFormat *fmt, const char *short_name,
      |                                          ~~~~~~~~~~~~~~~~^~~

Waf: Leaving directory `/home/xxx/src/mpv/build'
Build failed
 -> task in 'objects' failed with exit status 1 (run with -v to display more information)
```

This worked previously using this exact process, but I cannot pinpoint the exact change in which it stopped working, as I don't have the builds automated in any meaningful way, unfortunately.

### Log file

Configure output: [configureoutput.txt](https://github.com/mpv-player/mpv/files/9894360/configureoutput.txt)
config.log:  [config.log](https://github.com/mpv-player/mpv/files/9894361/config.log)

**Comment by thebombzen** [comment]
This is because the mimimum required version of libavutil that we allow is `56.12.100` but `AV_PIX_FMT_VULKAN` was added in libavutil `56.39.100`. We either need to increase our minimum requirement, or guard this entry with an `#ifdef`.
