### ISSUE TITLE
[meta] roalty-free, open video files (for benchmarking)?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#10818]
When reporting issues, I'd prefer using open-source video — which anyone can access, and I'm allowed to share direct download links in the issue template. 

Should be available with generic download tools (`wget`, `curl`...) and/or via torrent, to account for users who aren't running a graphical environment. For coverage, both H.264/x264 and H.265/x265 video in  the 1080p and 2160p resolutions and separate [24/30/60/120P](https://en.wikipedia.org/wiki/24p) formats, when available.

To start, the [Big Buck Bunny (2008) download page](https://peach.blender.org/download/) points to a plain HTTPS web server (2160p@60fps available).

**Comment by CounterPillow** [comment]
* Netflix's official sample stuff http://download.opencontent.netflix.com/
* the entire [FFmpeg FATE test suite](https://ffmpeg.org/fate.html) (over rsync)

> to account for users who aren't running a graphical environment.

yeah, wouldn't want to exclude people on a VT100 from a video player issue tracker.
