### ISSUE TITLE
gpu-next: Failed opening ICC profile with --vo=gpu-next on Windows

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#10814]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.34.0-551-gf594482451 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sun Oct 30 12:22:20 2022
FFmpeg library versions:
   libavutil       57.39.101
   libavcodec      59.51.100
   libavformat     59.34.101
   libswscale      6.8.112
   libavfilter     8.49.101
   libswresample   4.9.100
```
- Windows Version
win11 22H2
- Source of the mpv binary
built based on shinchiro
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

### Reproduction steps
![Upper_Left](https://user-images.githubusercontent.com/61936050/198882183-b8ccf74d-f26f-494d-9073-cfb39d7d8067.jpg) ![Upper_Right](https://user-images.githubusercontent.com/61936050/198881041-5ef2ff4a-1ba3-4ff9-a5a7-e6f61cdae129.jpg)

Open the example picture with `--no-config --vo=gpu-next --icc-profile-auto`

### Expected behavior
The icc profile should works on Windows, just like `--no-config --vo=gpu --icc-profile-auto`.
![gpu1](https://user-images.githubusercontent.com/61936050/198882211-e5f043e1-05fb-4bb4-b0ae-50c62e9dc148.png)
![gpu2](https://user-images.githubusercontent.com/61936050/198881196-5e5600e9-1123-4308-a71e-e429e16c1c2d.jpg)

### Actual behavior
The icc profile does not work with `vo=gpu-next` on Windows.
![gpu-next1](https://user-images.githubusercontent.com/61936050/198887371-55cb3330-3a18-4b1e-9838-edfd2e9cc5d0.png)
![gpu-next2](https://user-images.githubusercontent.com/61936050/198881286-270f4361-a3a0-410a-97d8-88930517ed51.jpg)

### Log file
[test.log.txt](https://github.com/mpv-player/mpv/files/9896000/test.log.txt)

**Comment by haasn** [comment]
The description of this issue is wrong. From your log:

```
[   9.249][v][vo/gpu-next/libplacebo] Opening ICC profile..
[   9.250][w][vo/gpu-next/libplacebo] Failed opening ICC profile... ignoring
```

**Comment by dyphire** [comment]
> The description of this issue is wrong. From your log:
> 
> ```
> [   9.249][v][vo/gpu-next/libplacebo] Opening ICC profile..
> [   9.250][w][vo/gpu-next/libplacebo] Failed opening ICC profile... ignoring
> ```

You are right. I missed it. I have corrected the correct title and description of the issue.

The real issue here is that the icc file is not used correctly with --vo=gpu-next on Windows, and the log will complains `ICC profile too wide to handle!`
```
[   3.649][v][vo/gpu-next/libplacebo] Opening ICC profile..
[   3.649][d][vo/gpu-next/libplacebo] Using fixed 3DLUT size: 64x64x64
[   3.650][e][vo/gpu-next/libplacebo] ICC profile too wide to handle!
[   3.650][w][vo/gpu-next/libplacebo] Failed opening ICC profile... ignoring
[   3.650][d][vo/gpu-next/libplacebo] LUT cache invalidated, regenerating..
```
But it won't happen with --vo=gpu on Windows.
[gpu.log](https://github.com/mpv-player/mpv/files/9896026/gpu.log.txt)

**Comment by haasn** [comment]
https://code.videolan.org/videolan/libplacebo/-/merge_requests/319 should fix both issues

**Comment by dyphire** [comment]
> https://code.videolan.org/videolan/libplacebo/-/merge_requests/319 should fix both issues

By quickly building and testing, I can confirm that the icc profile can work on the  example image.
```
[  62.980][v][vo/gpu-next/libplacebo] Opening ICC profile..
[  62.981][w][vo/gpu-next/libplacebo] Detected profile gamma (2.227) very far from pure power response (stddev=0.7), suspected unusual or broken profile. Ignoring, but results may be poor.
```
But the issue of `ICC profile too wide to handle` has not been fixed.
Another sample image is required to reproduce it:
![Upper_Left](https://user-images.githubusercontent.com/61936050/198886617-12c5f1a6-9d37-41e0-81c6-c83736ef8af7.jpg)

The test log:
[fix_icc_wide.log](https://github.com/mpv-player/mpv/files/9896157/fix_icc_wide.log.txt)

**Comment by haasn** [comment]
Hmm. I can *force* it to accept this image but the resulting 3DLUT is generated as solid black. I don't actually know why this is the case, I would need to investigate it further.

It looks like a possible LittleCMS bug. Note that the offending image is also rendering broken/incorrectly inside `vo_gpu`, though in a less bad way. I could investigate it more but I anticipate the upstream response will probably be "this is a broken profile", or something.

I'll put it somewhere on my priority list. But for now, with [this MR](https://code.videolan.org/videolan/libplacebo/-/merge_requests/319), the issue should at least be fixed *in practice*, i.e. for non-synthetic test profiles.

**Comment by dyphire** [comment]
> I'll put it somewhere on my priority list. But for now, with [this MR](https://code.videolan.org/videolan/libplacebo/-/merge_requests/319), the issue should at least be fixed _in practice_, i.e. for non-synthetic test profiles.

Unfortunately, the new [commit](https://code.videolan.org/videolan/libplacebo/-/merge_requests/319/diffs?commit_id=a617d0a2339564fc487b58345f38eaa27bf6c7be) of [that MR](https://code.videolan.org/videolan/libplacebo/-/merge_requests/319) did not work as expected but crashed.
![image](https://user-images.githubusercontent.com/61936050/199269087-a3e03bd1-b079-4a79-a4cb-749932ec560a.png)

This is test log file: [too-wide-icc.log](https://github.com/mpv-player/mpv/files/9911617/too-wide-icc.log.txt)

**Comment by haasn** [comment]
Thanks, weirdly on my end I get different symptoms but the source is the same: NaNs in the gamma estimation on this profile, because it maps black to a negative luminance number.

Anyway, I updated the MR, now we at least render an image. It's again weirdly too bright compared to the reference image (in e.g. firefox), but this now matches the `vo_gpu` result, so at least it's now in the hands of LittleCMS to explain this brightness bug.

**Comment by dyphire** [comment]
> Anyway, I updated the MR, now we at least render an image. It's again weirdly too bright compared to the reference image (in e.g. firefox), but this now matches the `vo_gpu` result, so at least it's now in the hands of LittleCMS to explain this brightness bug.

I can confirm that the MR is working properly.
```
[vo/gpu-next/libplacebo] Detected profile gamma (3.197) very far from pure power response (stddev=1.3), suspected unusual or broken profile. Ignoring, but results may be poor.
[vo/gpu-next/libplacebo] ICC profile too wide to handle, colors may be clipped!
```
As for the brightness, I'm not sure whether it's related to icc profile v4. These test pictures are from https://www.color.org/version4html.xalter
