### ISSUE TITLE
Dropping url file to udp://localhost:9998/ causes crash to desktop

### ISSUE THREAD

**Issue by shodanx2** [mpv-player/mpv#10820]
### Important Information

Provide following Information:
- mpv version
0.34.0-551-gf594482451
- Windows Version
- 10
- Source of the mpv binary
- mpv.io
- If known which version of mpv introduced the problem
- first time user
- Possible screenshot or video of visual glitches
- crash to desktop 

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior

application displays video stream

### Actual behavior

crash to desktop

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to

[mpv.log](https://github.com/mpv-player/mpv/files/9908575/mpv.log)

https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

[localhost  9998 udp_2.zip](https://github.com/mpv-player/mpv/files/9908578/localhost.9998.udp_2.zip)

actual file content

```
[{000214A0-0000-0000-C000-000000000046}]
Prop3=19,2
[InternetShortcut]
IDList=
URL=udp://localhost:9998/
```

Note : video feed to produce stream is by running this command

ffmpeg -f lavfi -i ddagrab -c:v h264_nvenc -cq 18 -f mpegts udp://localhost:9998

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/

or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
```
[   2.377][v][cplayer] Opening failed or was aborted: C:\Users\shodan\Desktop\localhost  9998 udp.url
[   2.377][v][cplayer] Running hook: ytdl_hook/on_load_fail
[   2.377][v][ytdl_hook] full hook 
[   2.377][v][cplayer] finished playback, unrecognized file format (reason 4)
[   2.377][e][cplayer] Failed to recognize file format.
[   2.377][i][cplayer] 
[   2.377][i][cplayer] Exiting... (Errors when loading file)
```

That's not a crash at all, mpv likely just doesn't support you dropping shortcut files onto it, which are not the same as opening a link.

**Comment by shodanx2** [comment]
When I started the application, it only says to drop files or url in the window

I don't know of another way to drop an url into an application than creating .url file (at least in windows)

And since there isn't any text box to manually enter an url ...

Also, the application disappears without an error message

![image](https://user-images.githubusercontent.com/10621885/199211031-b9fa4b96-d722-45a6-8d36-b20a84972f8c.png)
