### ISSUE TITLE
`--vo=gpu-next --gpu-api=vulkan -cscale=ewa _lanczos` doesn't work. screen is solid green

### ISSUE THREAD

**Issue by nobodyatandnothing** [mpv-player/mpv#10823]
### Important Information
mpv acb7db Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Wed Nov 02 03:18:23 2022
FFmpeg library versions:
   libavutil       57.40.100
   libavcodec      59.51.101
   libavformat     59.34.101
   libswscale      6.8.112
   libavfilter     8.49.101
   libswresample   4.9.100
FFmpeg version: git-2022-11-01-2537fdc
Clear Linux OS;  version: 37560

built from source
problem intoroduced within the last few commits
sway version 1.7
Trying display: wayland
libva info: VA-API version 1.16.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_16
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.16 (libva 2.16.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 22.6.0 ()
`mpv --no-config --vo=gpu-next --gpu-api=vulkan 'https://www.you
tube.com/watch?v=ZIFhglHn3W0'`
screenshot:
![mpv-shot0002](https://user-images.githubusercontent.com/91722596/199423985-631cb727-6ef3-442f-8716-94fc6ab5d0a2.jpg)

 `mpv --no-config --vo=gpu-next --gpu-api=vulkan --cscale=ewa
_lanczos 'https://www.youtube.com/watch?v=ZIFhglHn3W0'`
screenshot:
![mpv-shot0001](https://user-images.githubusercontent.com/91722596/199423618-b10ef052-f326-4f52-8970-e1426c7ed525.jpg)

logfile:
[output.txt](https://github.com/mpv-player/mpv/files/9917498/output.txt)

**Comment by haasn** [comment]
It works fine on my end. I don't see any error in your log either. 

If it got introduced recently, can you try bisecting it, please?

**Comment by kkanungo17** [comment]
Can confirm the same issue.
Log: [mpvlog.txt](https://github.com/mpv-player/mpv/files/10410705/mpvlog.txt)

**Comment by haasn** [comment]
Maybe the problem is exclusive to intel. I don't have any intel hardware to test on, unfortunately.

Maybe @kkanungo17 can bisect it?

**Comment by t-8ch** [comment]
Can also reproduce it on intel.
Was not able to bisect.
It seems that the issue happens IFF a polar filter is used.

**Comment by kkanungo17** [comment]
I'll try, but it's going to be a bit hard since it has been a while. At least for current libplacebo, mpv commit 70fa9502f3 still exhibits the same issue.

**Comment by kkanungo17** [comment]
Yeah this is probably a graphics driver issue. Even with mpv commits going back to Feb 2022 and libplacebo v4.208 the problem persists.

**Comment by t-8ch** [comment]
It's weird that the same shaders seem to work with `vo_gpu`.

**Comment by t-8ch** [comment]
For me this seems to work now,

**Comment by kkanungo17** [comment]
Yeah, works for me now as well. But so many things have updated since then I have no idea what fixed it.
