### ISSUE TITLE
build failure with --enable-wayland with current git master

### ISSUE THREAD

**Issue by tgurr** [mpv-player/mpv#10828]
### mpv version and platform versions

Git master: 445a3561d38552a452c242237f8cc04223d728b4 fails to build while compiling `v0.34.1` works fine as well as git master when passing `--disable-wayland`.

### Reproduction steps

1. `git clone https://github.com/mpv-player/mpv.git`
2. `env PKGCONFIG=x86_64-pc-linux-gnu-pkg-config ./waf --verbose --jobs=1 configure --prefix=/usr/x86_64-pc-linux-gnu --confdir=/etc/mpv --libdir=/usr/x86_64-pc-linux-gnu/lib --datadir=/usr/share --docdir=/usr/share/doc/mpv-scm --htmldir=/usr/share/doc/mpv-scm/html --mandir=/usr/share/man --enable-manpage-build --disable-html-build --disable-pdf-build --enable-iconv --enable-jpeg --enable-libavdevice --enable-libmpv-shared --disable-javascript --disable-pthread-debug --disable-sdl2 --disable-sdl2-gamepad --disable-ta-leak-report --disable-tests --disable-uchardet --lua=lua-5.2 --disable-vapoursynth --enable-dvbin --enable-libarchive --disable-libbluray --disable-cdda --disable-dvdnav --disable-jack --disable-rubberband --disable-audiounit --disable-coreaudio --disable-openal --disable-opensles --disable-oss-audio --disable-sdl2-audio --disable-wasapi --disable-zimg --disable-alsa --enable-pipewire --disable-pulse --disable-caca --disable-lcms2 --disable-sdl2-video --disable-sixel --disable-spirv-cross --disable-drm --enable-egl --enable-gl --enable-plain-gl --enable-shaderc --enable-vulkan --enable-wayland --enable-gl-wayland --disable-vaapi-wayland --enable-x11 --enable-xv --enable-egl-x11 --enable-gl-x11 --disable-vaapi-x11 --disable-vaapi-x-egl --enable-vdpau-gl-x11 --disable-android --disable-cocoa --disable-d3d11 --disable-direct3d --disable-egl-angle --disable-gl-cocoa --disable-gl-win32 --disable-ios-gl --disable-macos-10-11-features --disable-macos-10-12-2-features --disable-macos-10-14-features --disable-macos-cocoa-cb --disable-macos-media-player --disable-macos-touchbar --disable-rpi --disable-rpi-mmal --disable-swift --disable-tvos --disable-uwp --disable-videotoolbox-gl --disable-d3d-hwaccel --disable-d3d9-hwaccel --disable-gl-dxinterop-d3d9 --enable-cuda-hwaccel --enable-cuda-interop --disable-vaapi --enable-vdpau`
3. `./waf build`
4. See error: /usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: video/out/gpu/context.c.33.o:(.data.rel.ro+0x1d0): undefined reference to `ra_ctx_wldmabuf'

### Expected behavior

Build without any error.

### Actual behavior

Run into build failure
```
/usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ld: video/out/gpu/context.c.33.o:(.data.rel.ro+0x1d0): undefined reference to `ra_ctx_wldmabuf'
collect2: error: ld returned 1 exit status
```

Passing `--disable-wayland` in the above command makes mpv compile without any errors.

### Log file
Complete build log: [mpv-build.log](https://github.com/mpv-player/mpv/files/9933255/mpv-build.log)

**Comment by Dudemanguy** [comment]
Does this fix it for you?

```
diff --git a/video/out/gpu/context.c b/video/out/gpu/context.c
index a7bb4175cc..2203b5cad9 100644
--- a/video/out/gpu/context.c
+++ b/video/out/gpu/context.c
@@ -114,7 +114,7 @@ static const struct ra_ctx_fns *contexts[] = {
 #endif
 
 /* No API contexts: */
-#if HAVE_WAYLAND
+#if HAVE_DMABUF_WAYLAND
     &ra_ctx_wldmabuf,
 #endif
 };
```

**Comment by tgurr** [comment]
> Does this fix it for you?

Yes, it does, compiled fine or me with the patch applied and passing `--enable-wayland`.
