### ISSUE TITLE
delayed and mistimed frames on AMD, Wayland (not on Xorg), Gnome

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#10835]
### Important Information

Provide following Information:
- mpv version 0.34.1
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100
FFmpeg version: 5.0.1

- Linux Distribution and Version: Fedora 36
- Source of the mpv binary: RPM Fusion
- Window Manager and version: GNOME Display Manager 42.0
- GPU driver and version: `amd-gpu-firmware.noarch`                           `20221012-141.fc36`

### Reproduction steps

    mpv --no-config --mute=yes --video-sync=display-resample --fs=yes --log-file=/tmp/mpv.txt 

Play the file, inspect the stats (the I key).

### Expected behavior
No delayed and mistimed frames.

### Actual behavior
Frequent delayed and mistimed frames, clear stuttering every few seconds with or without `video-sync=display-resample`. Some dropped frames.

### Log file
[mpv.txt](https://github.com/mpv-player/mpv/files/9946476/mpv.txt)

**Comment by Dudemanguy** [comment]
Does this happen if you use xorg? What about if you compile mpv from master?

**Comment by 07416** [comment]
@Dudemanguy I apologize for the major delay. I reproduced now with mpv 0.35.0 and Fedora 37, Wayland and Xorg. Xorg appears to only get dropped/delayed/mistimed frames **at the start of playback**, within a handful of seconds.

    mpv --no-config --mute=yes --video-sync=display-resample --fs=yes --log-file=/tmp/mpv.txt

mpv 0.35.0 and Fedora 37, Wayland:
[mpv.txt](https://github.com/mpv-player/mpv/files/10096819/mpv.txt)

mpv 0.35.0 and Fedora 37, Xorg: [mpv.txt](https://github.com/mpv-player/mpv/files/10097872/mpv.txt)

---

* mpv 0.35.0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.2

* Linux Distribution and Version: Fedora 37

* Source of the mpv binary: RPM Fusion

* Window Manager and version: GNOME Display Manager 43.0

* GPU driver and version: `amd-gpu-firmware.noarch`                           `20221109-144.fc37`

@sfan5 Can you please reopen the issue?

**Comment by Dudemanguy** [comment]
I tried GNOME 43.1 briefly and could not reproduce (RX 550 and also upscaling to 4k).

**Comment by 07416** [comment]
around 15 minutes of Gemini Man (4K at 59.940fps) playback:

Xorg: [mpv.txt](https://github.com/mpv-player/mpv/files/10148539/mpv.txt)
Wayland: [mpv.txt](https://github.com/mpv-player/mpv/files/10148575/mpv.txt)

**Comment by Dudemanguy** [comment]
Do you see this behavior in any other compositor (sway/wlroots, weston, etc.)?

**Comment by 07416** [comment]
Closing as stale — sorry for taking the contributors' time. I'm not absolutely certain which RPM Fusion packages are needed for optimal playback on Fedora and I've only ever played video at 60Hz (seemingly not trivial to automate switching on Wayland). At least any judder isn't obvious with 24P content anymore (I watched 'Invisible Demons' (2021) recently, has prominent tracking shots).

I'll likely get a dedicated video playback machine and try to report back whether the issue persists or not.

**Comment by 07416** [comment]
this report was created on the same hardware, may be considered as the same issue: https://github.com/mpv-player/mpv/issues/9924
