### ISSUE TITLE
cannot change sub height after toggling sub-ass-override=force

### ISSUE THREAD

**Issue by AdventurerRussia** [mpv-player/mpv#10834]
### Important Information
after enabling sub-ass-override "force"
and then I changed the height of the subtitles and as I switched back to the original design of the ass subtitles, their position was reset and it became impossible to change their height when their design is original.
I recorded a video of how it happens https://youtu.be/ASDhD5drp6E

- Platform and Version
Выпуск	Windows 11 Pro
Версия	22H2
Дата установки	‎22.‎10.‎2022
Сборка ОС	22621.755
Взаимодействие	Windows Feature Experience Pack 1000.22636.1000.0

- Source of the mpv binary
last build from here
https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

**Comment by hooke007** [comment]
Cannot reproduce and where is your log?

**Comment by thebombzen** [comment]
It sounds like they're saying the keybind to increase/decrease sub height stops working after toggling sub-ass-override=force on and off (also can be done with a keybind).

**Comment by AdventurerRussia** [comment]
> It sounds like they're saying the keybind to increase/decrease sub height stops working after toggling sub-ass-override=force on and off (also can be done with a keybind).
yes that's right

**Comment by hooke007** [comment]
Still cannot reproduce and log?

**Comment by hooke007** [comment]
If you were using the built-in shortcuts. That's not a bug.
https://github.com/mpv-player/mpv/blob/25906514c3aec87589833043f6281584946c98b4/etc/input.conf#L126

As I said, you shouldn't use `no`. Try `yes` instead.

**Comment by AdventurerRussia** [comment]
> 



> Still cannot reproduce and log?



> Still cannot reproduce and log?

I didn't add anything to the config file at all, I just downloaded a clean build and showed that by default, when changing the style to the u key, then after returning to the subtitles style, it is impossible to move it down or up. here I was preparing a log I'm sorry for the delay https://fex.net/ru/s/fxmyerr

**Comment by hooke007** [comment]
The built-in shortcuts is not suitable for your case. Add the command as I said and rebind it to one <key>

**Comment by AdventurerRussia** [comment]
I mean, why does it not come out after switching to the u key and returning back to shift the subtitles, and also why they are reset to the default location, and not the value that I raised or lowered using the r and t keys

**Comment by hooke007** [comment]
Because the default value is `yes`. More details you could get from doc.

https://mpv.io/manual/master/#subtitles
> Subtitles in ASS format are normally not changed intentionally, but overriding them can be controlled with --sub-ass-override.

**Comment by AdventurerRussia** [comment]
> 

I went through all the options for the --sub-ass-override= key, and still after switching to the original style of subtitles, and not that mpv can't move them, and after restarting the player, they can't be moved either. Only if you specify --watch-later-options-remove=sub-ass-override, then everything works after reboot,

**Comment by AdventurerRussia** [comment]
it would be fine if they cannot be moved while the player is running, but after a reboot it is also impossible if the save file browsing history option is specified.

**Comment by hooke007** [comment]
You just need add 
```
u cycle-values sub-ass-override "force" "yes"
```
into you input.conf.

And then click it to activate `yes`.

**Comment by AdventurerRussia** [comment]
> ```
> u cycle-values sub-ass-override "force" "yes"
> ```

so I'm sorry that I took your time, everything is working as it should now, but honestly, this logic of subtitles looks like a bug. 
and the key parameter that you gave me looks like it should work in the player by default.
thanks again for your time.
I have no right to tell you, but maybe it's worth doing a survey about the behavior of subtitles. Because the way it now works by default is very strange.

**Comment by hooke007** [comment]
The options in watch_later cache files would be applied after the loading of every file. While the options mpv.conf were set when starting the mpv.
As a personal advice, you could use the 'whitelist' (i.e. `watch-later-options=aid,sid` ) to only save the properties you like.

**Comment by thebombzen** [comment]
It is indeed a bug if toggling it on and off removes the functionality.

**Comment by hooke007** [comment]
I don't see any bug here. `no` works as its desciption.
