### ISSUE TITLE
Modify frame data before rendering 

### ISSUE THREAD

**Issue by yangpenglove** [mpv-player/mpv#10831]
Hello, 

Is there a way to get frame data before rendering on opengl context? I want to add some specical filter on mpv but they are not ffmpeg filters, I checked document and found it seems mpv_render_context_get_info can get the next frame, but I am not sure I can modify the data of MPV_RENDER_PARAM_SW_POINTER. 

I googled but cannot find any sample codes, do we have some samples?

Thanks

**Comment by Dudemanguy** [comment]
I'm not particularly familiar with the rendering API so I can't help you with examples, but I believe the answer is "yes". At least as far as I know, the purpose of the rendering API is to give you direct access to the surface on the graphics API level (or software).
