### ISSUE TITLE
How to install MPV on Windows 8

### ISSUE THREAD

**Issue by Abbasi85** [mpv-player/mpv#1083]
Hi, I want to install MPV player on windows 8. I tried my best to install MPV player but does not succeeded. Plz help me

**Comment by FireRed69** [comment]
> Just grab one of the “latest” archives matching your OS version (probably 64-bit) from http://mpv.srsfckn.biz and unpack that at an appropriate location. Then you just open files with `mpv.exe`. That’s all. Note that just double-clicking mpv.exe will do nothing as mpv does not have any file to play at that point. It is not mpv’s task to provide a file browser, so just drag and drop files to the executable or associate file types with it using Windows’ “Open with…” context menu entry.
> 
> Just make sure to pick a proper place to unpack since Windows (at least 7, not sure if they’ve fixed that in 8) makes it kinda hard to fix program associations if you move the .exe somewhere else afterwards.
> 
> Hope that helps.

Is there any other archive, can't find any windows 8 versions
