### ISSUE TITLE
command_native args should also accept full commands as strings

### ISSUE THREAD

**Issue by duarm** [mpv-player/mpv#10830]
### Expected behavior of the wanted feature

both calls fail because `args` is a string and/or because each parameter is required to be a new field,
```lua
		mp.command_native_async({
			name = 'subprocess',
			playback_only = false,
			args = [[notify-send -t 3000 'test']],
		})
		mp.command_native_async({
			name = 'subprocess',
			playback_only = false,
			args = { [[notify-send -t 3000 'test']] },
		})
```

this version below works.
```lua
		mp.command_native_async({
			name = 'subprocess',
			playback_only = false,
			args = { 'notify-send', '-t', '3000', 'kdqkwdqk' },
		})
```

it would help a lot if it could also behave like os.execute(), that is, accepting a normal string which would be ran as is

**Comment by sfan5** [comment]
```lua
args = { 'sh', '-c', [[notify-send -t 3000 'test']] },
```
or whatever the windows-equivalent is if you care about that.

**Comment by avih** [comment]
Full command as a string is typically executed by the system shell, and is subject to shell quoting, which can differ between OSs - that's how lua's `os.execute` works.

If you're on unix/linux/bsd/osx/etc then it would be trivial to wrap your function with something which takes a string and then calls subprocess with `args` of
```lua
{ 'sh', '-c', YOUR_STRING_HERE }
```

The above is pretty much equivalent to what `os.execute` does.

On windows it would probaby be (untested):
```lua
{ 'cmd.exe', '/C', YOUR_STRING_HERE }
```

Note that `cmd.exe` has diffetent quoting rules for the string than `sh` on *nix (`os.execute` also has this issue).

**Comment by duarm** [comment]
good enough, thanks
