### ISSUE TITLE
Documentation not clear for "sub-ass-styles"

### ISSUE THREAD

**Issue by j77h** [mpv-player/mpv#10845]
From https://mpv.io/manual/master/

```
--sub-ass-styles=<filename>
 
    Load all SSA/ASS styles found in the specified file
    and use them for rendering text subtitles.
```
From my efforts to get this to work,
I think the last line should say "ASS" instead of "text":
`     and use them for rendering ASS subtitles,`
followed by this extra line:
`     when sub-ass-override is set to yes.`

I did not find any way to get `--sub-ass-styles=<filename>`
to influence the rendering of subtitles from SRT or VTT files.

I'm reporting as if the document is at fault, but you might 
conclude that this feature *should* operate on non-ASS text files,
which is what the document led me to expect.

**Comment by DreamHollow** [comment]
I'm going to take a crack at cleaning this up and see what I can do based on the information you provided.

These suggestions make sense to me.

**Comment by DreamHollow** [comment]
You might want to clarify what you mean by this.

Your choice of explanation is slightly confusing; do you mean to say that the explanation of how MPV handles SSA/ASS subtitle styles isn't well clarified?

**Comment by j77h** [comment]
> do you mean to say that the explanation of how MPV handles SSA/ASS subtitle styles isn't well clarified?

Nothing so broad as that. 

Simply that `sub-ass-styles` followed by "for rendering TEXT subtitles" 
seems to mean that `sub-ass-styles` can be used to style non-ASS kinds of subtitle file (SRT, VTT, etc).

But it doesn't work that way, it applies only to ASS files. 
(Only when sub-ass-override is set to yes, naturally.)

**Comment by Dudemanguy** [comment]
P.S. if you want to open a PR to improve the wording, feel free.
