### ISSUE TITLE
When opening a long video vertically, window alignment problems

### ISSUE THREAD

**Issue by Cerastia** [mpv-player/mpv#10843]
Usually, when opening a file, it is set to open in the middle of the right.
Like the options below...

autofit=35%x60%
geometry=100%:45%

Normal videos (horizontal long videos) are fine, but vertically long videos are aligned with a margin on the right.
I want to know if there is a separate option to remove the margin and attach it to the right.

**Comment by Dudemanguy** [comment]
Can you clarify what you mean by "aligned with a margin on the right"?
