### ISSUE TITLE
Cache network streams to RAM on mpv-android

### ISSUE THREAD

**Issue by RafeeDaBoy** [mpv-player/mpv#10840]
On PC mpv seems to cache video on system RAM by default, but is it the same for mpv-android? If not then is it possible to enable caching on system memory exclusively? It shouldn't be an issue the my phone has 12GB of RAM available.

**Comment by hooke007** [comment]
Here is not the repo of mpv-android.
Post your thread there. https://github.com/mpv-android/mpv-android

**Comment by sfan5** [comment]
The demuxer cache is also active on mpv-android but with a lower default.
You can configure [`--demuxer-max-bytes`](https://mpv.io/manual/master/#options-demuxer-max-bytes) in mpv.conf as usual.

**Comment by RafeeDaBoy** [comment]
My bad and thanks a lot for the info!
