### ISSUE TITLE
meson.build fails if gnustep-gui installed

### ISSUE THREAD

**Issue by ddawson** [mpv-player/mpv#10847]
### mpv version and platform versions

mpv 0.34.0-567-gc416a38ef2 (basis of 0.34.1_p20221105 in Gentoo)
Gentoo profile default/linux/amd64/17.1/desktop/plasma/systemd

### Reproduction steps

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

1. Install gnustep-gui (including whatever provides headers on your distro).
2. Attempt to configure the mpv build with `meson setup build`.

### Expected behavior

Either make the AppKit-related components work on Linux, or do more to make sure the OS really is MacOS X and disable the relevant components otherwise.

### Actual behavior

The macos-touchbar check passes, because gnustep-gui provides an AppKit implementation that allows the test program to compile. However, for some reason, the build is later apparently unable to find an Objective-C compiler.

Passing `-Dmacos-touchbar=disabled` doesn't work, because the build just overrides it.

### Log file

[meson-log.txt](https://github.com/mpv-player/mpv/files/9990684/meson-log.txt)

**Comment by Dudemanguy** [comment]
Can you confirm if #10848 does the trick for you?

**Comment by ddawson** [comment]
> Can you confirm if #10848 does the trick for you?

Yes, that fixes it.
