### ISSUE TITLE
HDR videos just display as a red screen

### ISSUE THREAD

**Issue by jconnolly837** [mpv-player/mpv#10857]
### Important Information
- mpv 0.34.1, also tested git master with same result
- Void Linux, kernel 5.19.17_1
- Void repo
- i3wm 4.21.1
- i915, mesa-22.1.7_1
- Screenshot:
![2022-11-12-154314_1920x1980_scrot](https://user-images.githubusercontent.com/26425730/201495733-2ec280c5-4c89-4419-9f65-9020cbcc2c15.png)

"If you're not using git master or the latest release, update. Releases are listed here: https://github.com/mpv-player/mpv/releases"
I tried building from git master and am encountering the exact same issue. 

### Reproduction steps

Using `--no-config` changes nothing.

Some Youtube videos, such as https://www.youtube.com/watch?v=LXb3EKWsInQ, cause the video played in MPV to be completely red. UI elements are still functional. Downloading the video with yt-dlp first and playing locally changes nothing.

### Expected behavior
Video to play clearly, without artifacts
### Actual behavior
Video is entirely red
### Log file
[mpvlog.txt](https://github.com/mpv-player/mpv/files/9996018/mpvlog.txt)

**Comment by haasn** [comment]
Does `--vf=format=gamma=bt.1886` make the red go away?

**Comment by jconnolly837** [comment]
Yes, `--vf=format=gamma=bt.1886` makes the red go away. Though the video plays now, it looks kinda washed out/lifeless 
compared to viewing on Youtube. 
![2022-11-12-160225_1920x1980_scrot](https://user-images.githubusercontent.com/26425730/201496327-825d417d-cd02-4716-8376-35aec36c57e1.png)
![2022-11-12-160532_1920x1980_scrot](https://user-images.githubusercontent.com/26425730/201496382-05f76787-acc1-46f2-b678-93eb4974e9cb.png)

**Comment by jeeb** [comment]
Checked with a recent'ish build I made based off of 25906514c3aec87589833043f6281584946c98b4 on Windows+nvidia and a downloaded version of the clip (yt-dlp formats were 337+251), and I cannot reproduce it with either the default gpu-api d3d11 or opengl, so doesn't seem like a general problem at least.

Of course windows doesn't have EGL, does it? So that plus the different GPU driver.

**Comment by haasn** [comment]
Can you try `--gpu-api=vulkan` and/or `--vo=gpu-next`?

**Comment by jconnolly837** [comment]
My GPU, Intel 945GM, doesn't support vulkan.
`--gpu-api=vulkan`
![vulkan](https://user-images.githubusercontent.com/26425730/201497144-a4c6e8d7-d762-4891-b86b-866e96200344.png)
`--vo=gpu-next` failes to load
```
[james@voidD620 ~]$ mpv https://www.youtube.com/watch?v=LXb3EKWsInQ --vo=gpu-next
 (+) Video --vid=1 (*) (vp9 1920x1080 59.940fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Uploader: Jacob + Katie Schwarz
 Channel_URL: https://www.youtube.com/channel/UCYq-iAOSZBvoUxvfzwKIZWA
[vo] Video output gpu-next not found!
Error opening/initializing the selected video_out (--vo) device.
Video: no video

Exiting... (Errors when loading file)
```
`--vo=gpu-next` with `-v`
[vo.txt](https://github.com/mpv-player/mpv/files/9996075/vo.txt)

**Comment by haasn** [comment]
What about `--tone-mapping=clip`?

**Comment by jconnolly837** [comment]
![2022-11-12-172623_1920x1980_scrot](https://user-images.githubusercontent.com/26425730/201498565-134a0837-c65f-43b2-8e8b-91a06ddf6b89.png)
And again with `-v`. Time/buffer info didn't get sent to the log file, but played fine in the terminal. 
[log.txt](https://github.com/mpv-player/mpv/files/9996207/log.txt)

**Comment by haasn** [comment]
Finally, what about `--tone-mapping=clip --vf=format=gamma=hlg`?

**Comment by jconnolly837** [comment]
![2022-11-12-174204_1920x1980_scrot](https://user-images.githubusercontent.com/26425730/201498914-74f9dca1-bdf0-423b-8120-33349cadf375.png)
With `-v`
[log.txt](https://github.com/mpv-player/mpv/files/9996222/log.txt)

**Comment by haasn** [comment]
Doesn't seem like it can be narrowed down to something more specific than 'any HDR video', I guess. There's probably little we can do to work around it then, either.

I guess at this point your only hope is that Mesa fixes the bug eventually, which is unlikely as active development goes into more recent hardware. (But you could try submitting a ticket nonetheless)

**Comment by jconnolly837** [comment]
I'm not well versed in this stuff. How do you know it's a Mesa bug?
