### ISSUE TITLE
HW Decode HEVC Rext

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#10851]

**Comment by zhongfly** [comment]
I think `qsv-copy` is invaild value for hwdec optoion, https://mpv.io/manual/master/#options-hwdec

**Comment by lavilao** [comment]
> I think `qsv-copy` is invaild value for hwdec optoion, https://mpv.io/manual/master/#options-hwdec

me too. I think is for transcoding only

**Comment by philipl** [comment]
There's no real reason to use `qsv`. Use vaapi on Linux and d3d11va on windows.

**Comment by ZaquL** [comment]
> d3d11va currently can't decode hevc rext 

You just need to apply 

https://patchwork.ffmpeg.org/project/ffmpeg/list/?series=527
