### ISSUE TITLE
VT_GETMODE failed: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by Visone-Selektah** [mpv-player/mpv#10865]
### Important Information

Provide following Information:
- mpv version 0.35.0
- Linux Distribution and Version venomlinux 4.0
- Source of the mpv binary compile from sources
- If known which version of mpv introduced the problem 0.35.0
- Window Manager and version dwm 6.4
- GPU driver and version It happens both with intel 1915 and amdgpu, both latest releases
- Mesa 22.2.3 with vaapi enabled

### Expected behavior
- Play the video using vaapi
### Actual behavior
- Broke
### Log file
{{{
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu] Failed to commit ModeSetting atomic request (-13)
[vo/gpu/opengl] Failed to set CRTC for connector 79: Permission denied
Error opening/initializing the selected video_out (--vo) device.
[vo/gpu] Can't handle VT release - signal already used
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu] Failed to commit ModeSetting atomic request (-13)
[vo/gpu/opengl] Failed to set CRTC for connector 79: Permission denied
Error opening/initializing the VO window.
Video: no video

Exiting... (Errors when loading file)

}}}

**Comment by sfan5** [comment]
You built mpv without X11 support, make sure you have all necessary dependencies installed (notably `libxpresent`) and try again.

**Comment by Visone-Selektah** [comment]
Hi!
Thanks!!!!! 
That was my bad!!! Sorry!!
