### ISSUE TITLE
mpv 0.35.0: error marshalling arguments for get_xdg_surface (signature no): null value passed for arg 1

### ISSUE THREAD

**Issue by satmandu** [mpv-player/mpv#10868]
### Important Information

Provide following Information:
- mpv version
Broken version: (0.35.0)
```
mpv 5d9389 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Mon Nov 14 11:07:47 2022
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: eacfcba
```

working version: (0.34.1)
```
mpv --version
mpv 349e437 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on Fri Oct  7 11:28:25 UTC 2022
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: eacfcba
```
- Linux Distribution and Version
Chromebrew (I am the maintainer for this binary)
- Source of the mpv binary
  - me
- If known which version of mpv introduced the problem
  - Last worked w/ version `0.34.1`
- Window Manager and version:  ChromeOS Exo Wayland environment.
- GPU driver and version
(The older version has no issues with this.)
```
glxinfo -B
name of display: :0
*** MESA_GLSL_CACHE_DISABLE is deprecated; use MESA_SHADER_CACHE_DISABLE instead ***
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) UHD Graphics 615 (AML-KBL) (0x591c)
    Version: 22.3.0
    Accelerated: yes
    Video memory: 15906MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 615 (AML-KBL)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.3.0-rc2 (git-38cb64bfe9)
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.3.0-rc2 (git-38cb64bfe9)
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 22.3.0-rc2 (git-38cb64bfe9)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

(This made no difference.)

### Expected behavior

Play video

### Actual behavior
```
curl -OLf https://filesamples.com/samples/video/mkv/sample_640x360.mkv
mpv sample_640x360.mkv 
 (+) Video --vid=1 (*) (h264 640x360 29.970fps)
error marshalling arguments for get_xdg_surface (signature no): null value passed for arg 1
Error marshalling request: Invalid argument
Segmentation fault (core dumped)
```
gdb:
```
(gdb) run sample_640x360.mkv
Starting program: /usr/local/bin/mpv sample_640x360.mkv
Failed to read a valid object file image from memory.
[New LWP 12621]
[New LWP 12622]
[New LWP 12623]
[New LWP 12624]
[New LWP 12625]
[New LWP 12626]
[LWP 12626 exited]
[New LWP 12627]
[LWP 12627 exited]
[New LWP 12628]
[New LWP 12629]
 (+) Video --vid=1 (*) (h264 640x360 29.970fps)
[New LWP 12630]
[New LWP 12631]
[LWP 12630 exited]
error marshalling arguments for get_xdg_surface (signature no): null value passed for arg 1
Error marshalling request: Invalid argument

Thread 12 "mpv/vo" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 12631]
```
ffplay is playing the file fine.

### Log file
Broken log file:
[output.txt](https://github.com/mpv-player/mpv/files/10007828/output.txt)

Working log file:
[output2.txt](https://github.com/mpv-player/mpv/files/10007846/output2.txt)

### Sample files

https://filesamples.com/samples/video/mkv/sample_640x360.mkv

**Comment by Dudemanguy** [comment]
I think this is a compositor bug although it's a very weird one. So based on this:
>error marshalling arguments for get_xdg_surface (signature no): null value passed for arg 1

As well as this from the broken log file:
```
[   0.039][v][vo/gpu/wayland] Registered for protocol wl_shm
[   0.039][v][vo/gpu/wayland] Registered for protocol zwp_linux_dmabuf_v1
[   0.039][v][vo/gpu/wayland] Registered for protocol wl_subcompositor
[   0.039][v][vo/gpu/wayland] Registered for protocol wl_output
[   0.039][v][vo/gpu/wayland] Registered for protocol wl_data_device_manager
[   0.039][v][vo/gpu/wayland] Registered for protocol wp_viewporter
[   0.039][v][vo/gpu/wayland] Registered for protocol wp_presentation
[   0.039][v][vo/gpu/wayland] Registered for protocol wl_seat
[   0.039][v][vo/gpu/wayland] Registered for protocol zxdg_decoration_manager_v1
[   0.039][v][vo/gpu/wayland] Registered for protocol zwp_idle_inhibit_manager_v1
[   0.039][v][vo/gpu/wayland] Registered for protocol xdg_wm_base
```

The compositor never actually registers the `wl_compositor` protocol with mpv (you'll notice it does in 0.34.1). Now as for why on earth that suddenly happens is beyond me, but things will definitely break. `wl_compositor` is what actually creates the `wl_surface`, so in your case it's NULL (because it's never created) which is why you get that error. This section of the code between 0.34.1 and 0.35 is not actually very different. The only thing is that 0.35 also creates some subsurfaces but this shouldn't matter.

**Comment by Dudemanguy** [comment]
Wait actually I just remembered that I bumped the wl_compositor version from 3 to 4 in this commit (https://github.com/mpv-player/mpv/commit/8a8580e05cbca61919e4ee431b7ec77cd11f6982). Does ChromeOS Exo really not support version 4? This dates back to [2015](https://gitlab.freedesktop.org/wayland/wayland/-/commit/3384f69ecf043d62a4e036c0353c2daa01d7c4d0) but that would explain what you see. I guess we could use a more elegant error message there.

**Comment by Dudemanguy** [comment]
We use `wl_surface_damage_buffer` in several places which is pretty old and actually predates the wayland-client version mpv currently depends on by several versions (1.10 was the first version with it). I'll make sure this potential error is handled more gracefully, but you're going to need version 4 for mpv.

**Comment by satmandu** [comment]
Ah, so just build without Wayland support then?

**Comment by Dudemanguy** [comment]
Yeah that would be the way to go for now.

**Comment by Dudemanguy** [comment]
Not a fix per se, but as discussed, mpv requires wl_compositor version 4 to work (which should error out gracefully now) on wayland.
