### ISSUE TITLE
Multiple errors and GUI player no longer starts after updating to 0.35.0

### ISSUE THREAD

**Issue by xfzv** [mpv-player/mpv#10861]
### Important Information

- mpv version: 0.35.0
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: Arch Linux community repository
- If known which version of mpv introduced the problem: 0.35
- Window Manager and version: KDE Plasma / Kwin 5.26.3 (X11)
- GPU driver and version: NVIDIA GeForce GTX 970 / NVIDIA proprietary drivers - 520.56.06-10 (from Arch Linux repos)

### Reproduction steps

1. Update to 0.35.0 on Arch Linux (currently in testing repository as I'm writing this)
2. Try to open any video from the file manager: the GUI player doesn't start and only the audio is played
3. Try to open any video from the terminal:

```console
mpv --no-config 1.mp4
 (+) Video --vid=1 (*) (h264 2560x1440 23.976fps)
File tags:
 Artist: NA
 Comment: https://filesamples.com/samples/video/mp4/sample_2560x1440.mp4
 Date: 20221111
 Title: sample_2560x1440
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] No primary DRM device could be picked!
[vo/gpu/opengl] Failed to find a usable DRM primary node!
[vo/gpu/opengl] Failed to create KMS.
VO: [gpu] 2560x1440 yuv420p
[vo/gpu/libplacebo] vk->CreateSwapchainKHR(vk->dev, &sinfo, PL_VK_ALLOC, &p->swapchain): VK_ERROR_UNKNOWN (../src/vulkan/swapchain.c:583)
[vo/gpu/libplacebo] Failed (re)creating swapchain!
Could not initialize video chain.
Video: no video

Exiting... (Errors when loading file)
```

With another file:

```console
mpv --no-config 2.mp4
 (+) Video --vid=1 (*) (av1 640x480 25.000fps)
 (+) Audio --aid=1 (*) (opus 2ch 48000Hz)
[vo/gpu] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/opengl] No primary DRM device could be picked!
[vo/gpu/opengl] Failed to find a usable DRM primary node!
[vo/gpu/opengl] Failed to create KMS.
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [gpu] 640x480 yuv420p
[vo/gpu/libplacebo] vk->CreateSwapchainKHR(vk->dev, &sinfo, PL_VK_ALLOC, &p->swapchain): VK_ERROR_UNKNOWN (../src/vulkan/swapchain.c:583)
[vo/gpu/libplacebo] Failed (re)creating swapchain!
Could not initialize video chain.
Video: no video
(Paused) A: 00:00:01 / 00:22:22 (0%)
```

### Expected behavior

The video player shows up and the videos play normally.

### Actual behavior

When opening any video from the file manager, the GUI player no longer starts and there's no video playback, I'm only getting the audio track.

Downgrading to 0.34.1 from Arch Linux repo solves the issue.

### Log file

[output.log](https://github.com/mpv-player/mpv/files/9998139/output.log)

### Sample files

Used [this sample video](https://filesamples.com/samples/video/mp4/sample_2560x1440.mp4) for the first terminal output.

**Comment by LaserEyess** [comment]
This is an arch packaging issue. Your mpv was not built with Xorg support.
