### ISSUE TITLE
Why mpv parse the input.conf on startup?

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#10877]
https://github.com/Natural-Harmonia-Gropius/InputEvent/pull/21

```ini
SPACE           cycle pause                                                                 #@click
SPACE           no-osd set speed 1; set pause no                                            #@press
SPACE           ignore                                                                      #@release
SPACE           no-osd add speed ${?speed==4.00:0}${!speed==4.00:0.1}; show-text ${speed}   #@repeat
```
![image](https://user-images.githubusercontent.com/50797982/202155663-f5c5bd5f-c04d-4d3d-8ad9-88c79314966d.png)

As the example in this PR, I used a user script to take over this part of input.conf, so the parsing check or security check is performed by the user script.

Is it possible to change input to lazy parsing or just don't do that? I want the default executor parses the commands after it is triggered by the user.

**Comment by Dudemanguy** [comment]
Well I mean of course mpv is going to parse its own config files. For your user script, why not just have it read a different file for whatever fancy thing you want to do?
