### ISSUE TITLE
Sometimes video from youtube videos are not loaded (only sound is loaded)

### ISSUE THREAD

**Issue by soredake** [mpv-player/mpv#10873]
### Important Information

Provide following Information:
- mpv 0.35.0-1-g2f747341f9
- Windows 11 Pro
- https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
- Wait for a day or so without playing youtube
- Do `.\mpv.com --no-config https://www.youtube.com/watch?v=GJVVzZ4YhuA` or `.\mpv.com --no-config https://www.youtube.com/watch?v=iyzimrkLwuw`
- You (maybe) will receive error `Could not read init fragment.
EDL: source file 'edl://!mp4_dash,init=<very long url> has unknown duration.` that will prevent video from loading.

### Expected behavior
Video should load.

### Actual behavior
Only audio is loaded because of this error.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/10014612/log.txt)

### Sample files

https://www.youtube.com/watch?v=GJVVzZ4YhuA
https://www.youtube.com/watch?v=iyzimrkLwuw

**Comment by soredake** [comment]
Initially reported here https://github.com/yt-dlp/yt-dlp/issues/985#issuecomment-1152968978

**Comment by qyot27** [comment]
There's no need to wait a day at all.  This seems to happen fairly regularly - in my case, the *overwhelming* majority of times this happens are with short (<1-2 min) VTuber highlight clips.  Typically, you can re-launch mpv multiple times (quit if it fails loading video, try again) and it eventually works - although sometimes the video then freezes mid-stream while the audio continues to the end.  Other channels that feature wildly different content (read: not livestreaming-related) either do this extremely rarely or don't ever exhibit the same behavior.

So part of it may simply be the kinds of videos that attract a *lot* of traffic onto YT's servers in the first place, coupled with a negotiation issue on yt-dlp's end.

**Comment by soredake** [comment]
> Typically, you can re-launch mpv multiple times

That's what i'm doing too, and putting `ytdl-raw-options=extractor-args="youtube:player_client=android"` helped with this issue slightly (youtube serverside throttling i guess?).

**Comment by soredake** [comment]
Reported here https://github.com/yt-dlp/yt-dlp/issues/5592

**Comment by krichbanana** [comment]
For one video, I captured both a failure and success for loading the video stream with `mpv --msg-level=all=trace <yt url>`.

This attempt to read the init fragment fails: notice chunked transfer encoding + no byte range in response + no bytes read in statistics.
```
[ffmpeg] https: request: GET <path> HTTP/1.1
[ffmpeg] User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36
[ffmpeg] Accept: */*
[ffmpeg] Range: bytes=0-
[ffmpeg] Connection: close
[ffmpeg] Host: rr4---sn-vgqsknll.googlevideo.com
[ffmpeg] Icy-MetaData: 1
[ffmpeg] 
[ffmpeg] 
[ffmpeg] https: header='HTTP/1.1 206 Partial Content'
[ffmpeg] https: http_code=206
[ffmpeg] https: header='Last-Modified: Mon, 21 Nov 2022 09:18:22 GMT'
[ffmpeg] https: header='Content-Type: video/webm'
[ffmpeg] https: header='Date: Mon, 21 Nov 2022 09:18:23 GMT'
[ffmpeg] https: header='Expires: Mon, 21 Nov 2022 09:18:23 GMT'
[ffmpeg] https: header='Cache-Control: private, max-age=21291'
[ffmpeg] https: header='Content-Range: bytes 0-/*'
[ffmpeg] https: header='Transfer-Encoding: chunked'
[ffmpeg] https: header='Connection: keep-alive'
[ffmpeg] https: header='Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"'
[ffmpeg] https: header='Vary: Origin'
[ffmpeg] https: header='Cross-Origin-Resource-Policy: cross-origin'
[ffmpeg] https: header='X-Content-Type-Options: nosniff'
[ffmpeg] https: header='Server: gvs 1.0'
[ffmpeg] https: header=''
[ffmpeg] resize stream to 131072 bytes, drop 0 bytes
[ffmpeg] Mime-type: 'video/webm'
[ffmpeg] Stream opened successfully.
[ffmpeg] https: Chunked encoding data size: 329
[ffmpeg] AVIOContext: Statistics: 0 bytes read, 0 seeks
Could not read init fragment.
```

This attempt succeeds: notice that the length of the fragment is declared in the response headers (incidentally, we connected to the same host, with the same resolved IP.)
```
[ffmpeg] https: request: GET <path> HTTP/1.1
[ffmpeg] User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.74 Safari/537.36
[ffmpeg] Accept: */*
[ffmpeg] Range: bytes=0-
[ffmpeg] Connection: close
[ffmpeg] Host: rr4---sn-vgqsknll.googlevideo.com
[ffmpeg] Icy-MetaData: 1
[ffmpeg] 
[ffmpeg] 
[ffmpeg] https: header='HTTP/1.1 206 Partial Content'
[ffmpeg] https: http_code=206
[ffmpeg] https: header='Last-Modified: Mon, 21 Nov 2022 09:18:22 GMT'
[ffmpeg] https: header='Content-Type: video/webm'
[ffmpeg] https: header='Date: Mon, 21 Nov 2022 10:26:20 GMT'
[ffmpeg] https: header='Expires: Mon, 21 Nov 2022 10:26:20 GMT'
[ffmpeg] https: header='Cache-Control: private, max-age=21297'
[ffmpeg] https: header='Content-Range: bytes 0-328/329'
[ffmpeg] https: header='Accept-Ranges: bytes'
[ffmpeg] https: header='Content-Length: 329'
[ffmpeg] https: header='Connection: keep-alive'
[ffmpeg] https: header='Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"'
[ffmpeg] https: header='Vary: Origin'
[ffmpeg] https: header='Cross-Origin-Resource-Policy: cross-origin'
[ffmpeg] https: header='X-Content-Type-Options: nosniff'
[ffmpeg] https: header='Server: gvs 1.0'
[ffmpeg] https: header=''
[ffmpeg] resize stream to 131072 bytes, drop 0 bytes
[ffmpeg] Mime-type: 'video/webm'
[ffmpeg] Stream opened successfully.
[ffmpeg] AVIOContext: Statistics: 329 bytes read, 0 seeks
[memory] Opening memory://
[memory] resize stream to 131072 bytes, drop 0 bytes
[memory] Stream opened successfully.
```

I assume FFmpeg can read a chunked response just fine, and I didn't notice any error reported, except from what I presume came from the EDL processor regarding the init fragment. I am confused as to why it fails to load, though; I thought FFmpeg would have reported an error if the message was truncated/empty.

I don't think yt-dlp is able to work around this; the error occurs after the video URL is extracted, somewhere in mpv/ffmpeg. If mpv was able to detect and retry this error, I think that would be the most ideal solution.

**Comment by soredake** [comment]
@sfan5 i've tried reporting this to yt-dlp but without luck, i can't reproduce this with only yt-dlp, should i report this issue to ffmpeg?

**Comment by sfan5** [comment]
Reporting this elsewhere without isolating the issue first will not help.

**Comment by soredake** [comment]
I don't really know how to do this, and this report is closed now so less people will see it, so it seems this will not be fixed.
