### ISSUE TITLE
mpv 0.35.0: File handeling issue fellow up in Total Commander in internal Linking

### ISSUE THREAD

**Issue by blackcrack** [mpv-player/mpv#10872]
### Important Information
filehandeling in WinNT(or other?) because name: 
"this is the movie name.mov" or avi or an other Video-file
have troubles with the space in the Filename : file not found
by adding internal linking at the TotalCommander
Provide following Information:
- mpv version  : 0.35.01 from https://sourceforge.net/projects/mpv-player-windows/files/
- Windows Version: Windows7 Pro Updated (ESU)
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/
- If known which version of mpv introduced the problem : I guess all up tho this actual version
- Possible screenshot or video of visual glitches: nope, nothing, no glinches.. it's the file-handling

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

Open total-commander, create an internal link for fileformats of Video,
and use the [path\to\mpv.exe "%1"____]
close, 
navigate to an "path/where/it is/store on/video file with name.avi" 
and doubleklick it
nothing happens, only a silence errror
right mouse key : open with the internal linking
nothing happens, only a silence errror

save exactly this file without spaces, maybe with "_" instead " " in the name,
doubleklick it, 
opens the files instantly and is found it quick as possible :)

best

**Comment by stax76** [comment]
This is very likely a user or Total Commander problem, you can use the following tool to debug your command line:

https://github.com/stax76/show-args

Post a screenshot of what this tool outputs.
