### ISSUE TITLE
Bundle installation in osx/macOS

### ISSUE THREAD

**Issue by Atemu** [mpv-player/mpv#10878]
Hi, we're [upgrading our packaging to use mpv's meson build in Nixpkgs](https://github.com/NixOS/nixpkgs/pull/201379) and something I've noticed is that mpv doesn't install a bundle by default.

We run `TOOLS/osxbundle.py` in our packaging script and then install the generated bundle "manually" to the output prefix. I'm wondering whether that's the intended way.

If it is, wouldn't it be better if the meson build built and installed the bundle automagically `if darwin`?

cc @Dudemanguy @Akemi

**Comment by Akemi** [comment]
yes that's intended. the bundle creation is and was always something that wasn't part of the build process for various reasons. one of them is, that the script is kinda a clusterfuck and isn't really robust. it should be rewritten imo if it should be part of the build and installation process.
