### ISSUE TITLE
meson: install macOS app bundle

### ISSUE THREAD

**Issue by Atemu** [mpv-player/mpv#10879]
### Expected behavior of the wanted feature

Currently, there is the osxbundle.py tool which packagers must "manually" execute in their packaging scripts.

As a packager, I want generation and and installation of the `mpv.app` bundle on macOS/Darwin to be integrated into the build system so that I have a standardised, clean and less error-prone way to distribute them to users.

### Alternative behavior of the wanted feature

The bundle could be a separate install target rather than being integrated into the regular install target.

**Comment by Akemi** [comment]
just a head up, i added a custom target in my PR https://github.com/mpv-player/mpv/pull/13529

**Comment by Atemu** [comment]
Thank you!
