### ISSUE TITLE
`vaExportSurfaceHandle` errors with `--hwdec=drm --vo=dmabuf-wayland`

### ISSUE THREAD

**Issue by mahkoh** [mpv-player/mpv#10885]
### Important Information

Provide following Information:
- mpv version: 0.35 and current master
- Linux Distribution and Version: 6.0.8-arch1-1
- Source of the mpv binary: repository, compiled from source
- Window Manager and version: https://github.com/mahkoh/jay/ current master
- GPU driver and version: mesa 22.2.3-1

### Reproduction steps

- Download https://github.com/SPBTV/video_av1_samples/blob/master/spbtv_sample_bipbop_av1_960x540_25fps.mp4
- play with `--hwdec=drm --vo=dmabuf-wayland`

### Expected behavior

Video plays normally.

### Actual behavior

Video output is blank, the following messages are logged:

```
[vo/dmabuf-wayland] Allocate buffer pool entry : 3
[vo/dmabuf-wayland] vaExportSurfaceHandle() failed (an unsupported memory type was supplied)
[vo/dmabuf-wayland] Failed to import
[vo/dmabuf-wayland] Free buffer pool entry : 3
```

### Log file

https://0x0.st/oIge.txt

---------

`--hwdec=vaapi` works fine: https://0x0.st/oIgO.txt

**Comment by mahkoh** [comment]
This error looks like it originates from this function returning DRM_FORMAT_INVALID:

https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/gallium/frontends/va/surface.c#L1375-1401

```c
static uint32_t pipe_format_to_drm_format(enum pipe_format format)
{
   switch (format) {
   case PIPE_FORMAT_R8_UNORM:
      return DRM_FORMAT_R8;
   case PIPE_FORMAT_R8G8_UNORM:
      return DRM_FORMAT_GR88;
   case PIPE_FORMAT_R16_UNORM:
      return DRM_FORMAT_R16;
   case PIPE_FORMAT_R16G16_UNORM:
      return DRM_FORMAT_GR1616;
   case PIPE_FORMAT_B8G8R8A8_UNORM:
      return DRM_FORMAT_ARGB8888;
   case PIPE_FORMAT_R8G8B8A8_UNORM:
      return DRM_FORMAT_ABGR8888;
   case PIPE_FORMAT_B8G8R8X8_UNORM:
      return DRM_FORMAT_XRGB8888;
   case PIPE_FORMAT_R8G8B8X8_UNORM:
      return DRM_FORMAT_XBGR8888;
   case PIPE_FORMAT_NV12:
      return DRM_FORMAT_NV12;
   case PIPE_FORMAT_P010:
      return DRM_FORMAT_P010;
   default:
      return DRM_FORMAT_INVALID;
   }
}
```

So any format other than these should never work with mesa vaapi if I'm reading the code correctly.

For some reason --hwdec=drm tries to use another format whereas --hwdec=vaapi correctly chooses NV12.

**Comment by philipl** [comment]
`--hwdec=drm` doesn't work on any desktop hardware. It's only relevant for SoCs. That's why it fails.

**Comment by mahkoh** [comment]
I see. I only read https://mpv.io/manual/master/#video-output-drivers-dmabuf-wayland and was wondering why it didn't work.
