### ISSUE TITLE
after Installer.bat mpv cant be run from cmd.

### ISSUE THREAD

**Issue by Theo1996** [mpv-player/mpv#10889]
### Important Information

Provide following Information:
mpv 0.34.0-572-g25906514c3
- Windows 7 64 bit

### Reproduction steps

run installer.bat
try to run mpv from cmd

### Expected behavior
mpv runs just fine from cmd, as if I manually added the dir to system PATH vars

### Actual behavior
mpv doesn't exist as a command
### Sample files

none

**Comment by CounterPillow** [comment]
That batch file is not distributed by the actual mpv project, please contact the person providing you with Windows builds for support.
