### ISSUE TITLE
How do I know which deinterlacer is being used?

### ISSUE THREAD

**Issue by Jeronimo17** [mpv-player/mpv#10883]
When I deinterlace (d key) either without HW or with VAAPI or NVDEC I see that it doubles the FPS (this is perfect) but I don't see anywhere if BOB, YADIF, or LINEAR or another method is being used.

Is it possible to see it like in VLC?

(I am on Linux)

Thank you

**Comment by hooke007** [comment]
> I don't see anywhere if BOB, YADIF, or LINEAR or another method is being used.

Are you sure? It's yadif

https://mpv.io/manual/master/#options-deinterlace

**Comment by Jeronimo17** [comment]
Yes I think it is, I have read that guide, but I can't confirm if it is active in the information panel (i or I key) or launching mpv with the -v parameter, I don't read it anywhere.

**Comment by philipl** [comment]
If you're doing software decoding, then it uses `yadif`. This is documented. If you're using hw decoding, it uses whatever hw deinterlacer is provided. For `nvdec`, that happens to be a cuda implementation of yadif. For vaapi (what you are using), it's whatever the hardware vendor provided. On Intel it seems to be a pretty high quality spatial-temporal algorithm. For AMD, it's hot garbage.

**Comment by Jeronimo17** [comment]
I have seen that the CPU consumption increases a lot, I don't know if the deinterlacing is done by CPU or HW.

**Comment by Jeronimo17** [comment]
_[cplayer] mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects_

**Comment by Jeronimo17** [comment]
Even so, I insist, wouldn't it be interesting to show it in some way as well as the decoding HW?
