### ISSUE TITLE
Meson sets global config path incorrectly

### ISSUE THREAD

**Issue by hurzl** [mpv-player/mpv#10882]
... even with --keep-open=no, both on "Enter" or ">" keys.
Expected: 0.34 closed the program when I pressed "Enter" on single file or on last file on playlist.

FreeBSD 13.1
mpv 0.35.0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Thu Nov 17 04:25:08 2022

**Comment by CounterPillow** [comment]
Where is your `--log-file`? Do not ignore the issue template please.

**Comment by hurzl** [comment]
[mpvlog.txt](https://github.com/mpv-player/mpv/files/10029523/mpvlog.txt)

**Comment by sfan5** [comment]
`[   1.281][d][cplayer] Run command: playlist-next, flags=73, args=[flags="weak"]`

```
       playlist-next <flags>
              Go to the next entry on the playlist.

              First argument:

              weak (default)
                     If the last file on the playlist is currently played, do nothing.

              force  Terminate playback if there are no more files on the playlist.
```

This is working as intended and the keybindings for this have not changed in years.

**Comment by hurzl** [comment]
So before 0.35 it wasn't?

In /usr/local/etc/mpv/input.conf I have
`ENTER playlist_next force`
Apparently this was obeyed by 0.34, but not by 0.35 (without --no-config of course)

**Comment by sfan5** [comment]
A look into `config.h` reveals that meson.build sets the config path incorrectly:
<pre>
~/mpv $ grep CONFDIR build/config.h 
#define MPV_CONFDIR "etc/mpv"
</pre>

for comparison (waf):
<pre>
/tmp/mpv $ grep CONFDIR build/config.h
#define MPV_CONFDIR "/usr/local/etc/mpv"
</pre>

**Comment by Dudemanguy** [comment]
Oh so this is actually different defaults that I guess favors Linux distros over BSDs. Meson uses the `sysconfdir` [option](https://mesonbuild.com/Builtin-options.html) which will default to `etc` + `/mpv`. If the prefix is set to `/usr`, then this path becomes `/etc/mpv`. Apparently on waf, the default is always just the `prefix` + `/etc/mpv`.

**Comment by sfan5** [comment]
My example is with prefix set to `/usr/local`, the path set by meson is just plain wrong and not even absolute.

**Comment by Dudemanguy** [comment]
Apparently it magically works if you just join the paths of `prefix` and `sysconfdir` and it doesn't result in `/usr/etc` for the `-Dprefix=/usr` case.

**Comment by brad0** [comment]
I happened to notice this commit. For OpenBSD we use prefix=/usr/local and sysconfdir=/etc

**Comment by Dudemanguy** [comment]
If you were already explicitly setting the path anyway, it will work the same way before and after this commit. This just makes the default not a wrong path in some cases.

**Comment by brad0** [comment]
> If you were already explicitly setting the path anyway, it will work the same way before and after this commit. This just makes the default not a wrong path in some cases.

Well we just converted over to using Meson. But with that commit it appears as if the path is now hardcoded so if we use prefix=/usr/local and sysconf=/etc that the path is /usr/local/etc/mpv instead of /etc/mpv. I don't mind whichever is the default. Just as long as there is a way of overriding the path.

**Comment by Dudemanguy** [comment]
I don't know about how the ports work but essentially you'll want to pass: `meson setup build -Dprefix=/usr/local -Dsysconfdir=/etc`
