### ISSUE TITLE
vo_gpu-next: unnecessary process of `reconfigure swap chain format`

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#10881]
### Important Information

Provide following Information:
- mpv version
git
- Windows Version
10 latest release
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20221116
- If known which version of mpv introduced the problem
N/A

### Reproduction steps

start with `vo=gpu-next`

### Expected behavior

My display-depth is 8 bit
No step of reconfigure swap chain format

### Actual behavior

```
[   0.165][v][vo/gpu-next/libplacebo] Attempting to reconfigure swap chain format: R8G8B8A8_UNORM -> R10G10B10A2_UNORM
```

### Log file

[test.log](https://github.com/mpv-player/mpv/files/10024199/test.log)

**Comment by haasn** [comment]
As far as I can tell, this is intentional behavior. The code is written to prefer 10-bit backbuffer formats over 8-bit even for SDR.

Why is this an issue for you?

**Comment by hooke007** [comment]
Maybe not a issue just I feel strange because it behaves different with vo=gpu.
I'm not sure if it means libplacebo always output 10 bit.

**Comment by haasn** [comment]
>  I'm not sure if it means libplacebo always output 10 bit.

Just to be sure, what happens when you do `--dither-depth=auto`? What depth does it dither to?

**Comment by hooke007** [comment]
[gpu-next_dither_tmp.log](https://github.com/mpv-player/mpv/files/10024435/gpu-next_dither_tmp.log)

**Comment by haasn** [comment]
It's dithering to 10-bit depth as expected, and matching the configured format. I'd say everything is working as intended.

**Comment by dyphire** [comment]
> It's dithering to 10-bit depth as expected, and matching the configured format. I'd say everything is working as intended.

I don't think this is consistent with the description and expectation of [--dither-depth](https://mpv.io/manual/master/#options-dither-depth).
Even when I use --dither-depth=8, vo=gpu-next still chooses to dither to 10-bit depth. 
This is log file of `--vo=gpu-next --dither-depth=8`: [depth.log](https://github.com/mpv-player/mpv/files/10029601/depth.log)
```
[   0.253][v][vo/gpu-next/libplacebo] Initial swap chain configuration: format: R10G10B10A2_UNORM, color space: RGB_FULL_G22_NONE_P709.
[   0.283][v][vo/gpu-next/libplacebo] Attempting to reconfigure swap chain format: R8G8B8A8_UNORM -> R10G10B10A2_UNORM
```
It ignores the explicit choices of users. Is this expected? 
What if people had a 12bit display and used --dither-depth=12? If --vo=gpu-next still chooses to dither to 10-bit depth, the output accuracy of the format of textures will be insufficient.

**Comment by haasn** [comment]
> Even when I use --dither-depth=8, vo=gpu-next still chooses to dither to 10-bit depth.
> This is log file of `--vo=gpu-next --dither-depth=8`: [depth.log](https://github.com/mpv-player/mpv/files/10029601/depth.log)

That log file shows it dithering to 8 bit precision. You can see this in the actual shader:

```
[  13.787][d][vo/gpu-next/libplacebo] [ 68] const float scale = 255.0; 
[  13.787][d][vo/gpu-next/libplacebo] [ 69] color = vec4(255.0) * color + vec4(bias); 
[  13.787][d][vo/gpu-next/libplacebo] [ 70] color = floor(color) * vec4(1.0 / 255.0); 
```

**Comment by dyphire** [comment]
> That log file shows it dithering to 8 bit precision. You can see this in the actual shader:
> 
> ```
> [  13.787][d][vo/gpu-next/libplacebo] [ 68] const float scale = 255.0; 
> [  13.787][d][vo/gpu-next/libplacebo] [ 69] color = vec4(255.0) * color + vec4(bias); 
> [  13.787][d][vo/gpu-next/libplacebo] [ 70] color = floor(color) * vec4(1.0 / 255.0); 
> ```

Now I know how to check the dither depth of --vo=gpu-next in the log. Obviously, my previous understanding was wrong.
But to be honest, the `pl_shader_dither` is not obvious. We can find `Reported display depth:` in the log to determine the dither depth simply and intuitively in --vo=gpu. Whether related log output can be optimized for --vo=gpu-next?


> I don't think this is consistent with the description and expectation of [--dither-depth](https://mpv.io/manual/master/#options-dither-depth).
> > auto
Automatic selection. If output bit depth cannot be detected, 8 bits per component are assumed.

It is still necessary to modify its relevant description of `--dither-depth=auto` to clarify the expected behavior under --vo=gpu-next.

**Comment by haasn** [comment]
> Automatic selection. If output bit depth cannot be detected, 8 bits per component are assumed.

This is correct for `gpu-next` as well, I'm not sure what led you to believe otherwise.

> Whether related log output can be optimized for --vo=gpu-next?

I guess we can, but I'm a bit reluctant to add a log print-out for it because `pl_renderer` is meant to be sort of stateless. But I guess I can add a one-time print-out if it changes.
