### ISSUE TITLE
How to prevent the seekbar from showing up in UX while fast forwarding

### ISSUE THREAD

**Issue by TheRabidWolverine** [mpv-player/mpv#10888]
This is a general MPV issue on Mac OS X, persisting for a long time, whenever I seek forward or backwards, a snapshot of the seek bar shows up momentarily in the video area obstructing the view. Any way to stop this from happening?

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/118490229/202581287-45011469-57ce-468a-ac39-6bce2846b4f5.png">

**Comment by christoph-heinrich** [comment]
[no-osd-bar](https://mpv.io/manual/master/#options-osd-bar)

**Comment by Dudemanguy** [comment]
`--no-osd-on-seek` as well if it's specifically just seeking you're looking to hide.

**Comment by TheRabidWolverine** [comment]
> [no-osd-bar](https://mpv.io/manual/master/#options-osd-bar)

Buddy can you tell me where to configure this or add it as config option? Clicking "Preferences" from Main menu shows an alert that there is no config file found. How to add one such file, and how to add this no-osd-bar as an option there?

**Comment by christoph-heinrich** [comment]
> Clicking "Preferences" from Main menu

I've never used macOS but I don't think it has a main menu, which indicates that you're using some mpv player based on libmpv instead of mpv directly.

For mpv the config file would be in `~/.config/mpv/mpv.conf`, where you simply add a line with `no-osd-bar`. If that's the same for whatever frontend you're using, I don't know.

**Comment by TheRabidWolverine** [comment]
> > Clicking "Preferences" from Main menu
> 
> I've never used macOS but I don't think it has a main menu, which indicates that you're using some mpv player based on libmpv instead of mpv directly.
> 
> For mpv the config file would be in `~/.config/mpv/mpv.conf`, where you simply add a line with `no-osd-bar`. If that's the same for whatever frontend you're using, I don't know.

Yes yes, just did it myself. Thanks a ton! This was a really annoying feature for me for years, finally it is gone now! :)

**Comment by Akemi** [comment]
> I've never used macOS but I don't think it has a main menu, which indicates that you're using some media player based on libmpv instead of mpv directly.

on a side note, it has https://github.com/mpv-player/mpv/blob/master/osdep/macosx_menubar.m
