### ISSUE TITLE
multi GPU and --vulkan-device

### ISSUE THREAD

**Issue by cHunter789** [mpv-player/mpv#10898]
Hi,
I have two discrete GPU in my system and when I type: _mpv --vulkan-device=help_ it will give me:

Available vulkan devices:
  'NVIDIA T1000' (GPU 0, ID 10de:1fb0)
  'NVIDIA T1000' (GPU 1, ID 10de:1fb0)

The devices have the same names (NVIDIA T1000). No way to use GPU1. I missed something, or maybe it's a wrong in conception of --vulkan-device?

**Comment by sfan5** [comment]
Yep that sounds like an issue, `vulkan-device` should probably also accept a number.

**Comment by hooke007** [comment]
So [d3d11-adapter](https://mpv.io/manual/master/#options-d3d11-adapter) need to be improved too?
