### ISSUE TITLE
mpv 0.35.0.1 memory leak when playing video from youtube

### ISSUE THREAD

**Issue by wbtcpip2** [mpv-player/mpv#10894]
mpv 0.35.0.1
windows 22h2
yt-dlp_x86.exe (2022.11.11)

from command line i run:
mpv https://youtu.be/jKxREG_asQs

video play normally but memory usage increase constantly, it starts with approx 200MB and it leaks approx 1 MB every 3 seconds.

**Comment by CounterPillow** [comment]
almost like it's caching the video or something

**Comment by Dudemanguy** [comment]
It's just video caching.
