### ISSUE TITLE
the sound disappears when rewinding with an external audio track

### ISSUE THREAD

**Issue by AdventurerRussia** [mpv-player/mpv#10896]
for example, if you connected an external track and decided to rewind, the sound disappears for a few seconds, and the video also starts to slow down a little and accelerate for a few seconds. 
when rewinding, such things do not happen, the sound is immediately reproduced.
here on the video you can see that the sound disappears for a few seconds when rewinding. https://youtu.be/WqgfNAfRlmU
moreover, the weaker the computer or the more tracks, the longer the sound disappears when rewinding
a friend with a weak computer has already written this to me

latest build from
https://sourceforge.net/projects/mpv-player-windows/files/64bit/

without scripts and settings except --audio-file-auto=fuzzy

log
https://fex.net/ru/s/lrvnzrv

Выпуск	Windows 11 Pro
Версия	22H2
Дата установки	‎22.‎10.‎2022
Сборка ОС	22621.819
Взаимодействие	Windows Feature Experience Pack 1000.22636.1000.0

**Comment by AdventurerRussia** [comment]
https://github.com/mpv-player/mpv/issues/1824#issuecomment-93369730

**Comment by Frozen1084** [comment]
I am also troubled by this problem.
Using the "hr-seek=yes" parameter solves the problem, but it causes a new lag, and fast forward and rewind in 4K video becomes very sluggish.

**Comment by AdventurerRussia** [comment]
> I am also troubled by this problem. Using the "hr-seek=yes" parameter solves the problem, but it causes a new lag, and fast forward and rewind in 4K video becomes very sluggish.

yes, thank you very much, this solved the problem, and on 4k video I did not see any problems for myself. 
And I don't watch it very often.
