### ISSUE TITLE
Color issues with gpu-next and debanding displaying 8-bit rgb image

### ISSUE THREAD

**Issue by xnoreq** [mpv-player/mpv#10903]
### Important Information

Provide following Information:
- mpv version
mpv 0.35.0-12-gba20f60add
- Platform and Version
Windows 10
- Source of the mpv binary
[shinchiro](https://github.com/shinchiro/mpv-winbuild-cmake/releases)

### Reproduction steps

`mpv.com --no-config --vo=gpu-next --deband=yes test.png`

test.png:
![test](https://user-images.githubusercontent.com/4028859/202917855-df9f2604-9ec0-4b07-8b4d-8b557a2e8f35.png)

### Expected behavior
![test](https://user-images.githubusercontent.com/4028859/202917855-df9f2604-9ec0-4b07-8b4d-8b557a2e8f35.png)

### Actual behavior
![grafik](https://user-images.githubusercontent.com/4028859/202917866-b5f93423-7c72-4ef8-98aa-653f5e358955.png)

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/10239

**Comment by xnoreq** [comment]
@hooke007 Thanks, closing.
