### ISSUE TITLE
Can mpv sync video to audio that is being shortened on the go with silenceremove AF ?

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#10900]
Maybe there is a command that I can send with `mp.command()` every N seconds that would force `mpv` to skip video forward to the correct position?
I know it will look ugly. I don't care.

**Comment by Dudemanguy** [comment]
You can use a script with a periodic timer. For example with a lua script (untested).

```
local timer = mp.add_periodic_timer(5, function()
    -- called every 5 seconds
    mp.command() -- whatever command you want here.
end)
```

**Comment by oltodosel** [comment]
Your answer does not help at all.
I need THE command that would sync video to the audio, not how to send that unknown to me command.

**Comment by Dudemanguy** [comment]
I thought the question was about wanting to send some command every N seconds like seeking a certain amount or such. There is no "sync video to the audio" command (not sure what this means really) so the answer to your question is "no" then.
