### ISSUE TITLE
meson: build detection issues on OpenBSD

### ISSUE THREAD

**Issue by brad0** [mpv-player/mpv#10906]
Meson is not able to find iconv. Looking at the Meson log it does not appear to be utilizing the pkg-config file.

```
Run-time dependency iconv found: NO (tried builtin and system)

../../pobj/mpv-0.35.0/mpv-0.35.0/meson.build:605:0: ERROR: Dependency "iconv" not found, tried builtin and system
```

```
Running compile:
Working directory:  /home/ports/pobj/mpv-0.35.0/build-amd64/meson-private/tmp0arqvwug
Command line:  cc /home/ports/pobj/mpv-0.35.0/build-amd64/meson-private/tmp0arqvwug/testfile.c -o /home/ports/pobj/mpv-0.35.0/build-amd64/meson-private/tmp0arqvwug/output.exe -O2 -pipe -g -D_FILE_OFFSET_BITS=64 -O0 -Werror=implicit-function-declaration

Code:
 #include <iconv.h>

int main() {
    iconv_open("","");
}
Compiler stdout:

Compiler stderr:
 /home/ports/pobj/mpv-0.35.0/build-amd64/meson-private/tmp0arqvwug/testfile.c:1:10: fatal error: 'iconv.h' file not found
#include <iconv.h>
         ^~~~~~~~~
1 error generated.

Running compile:
Working directory:  /home/ports/pobj/mpv-0.35.0/build-amd64/meson-private/tmpe2s2p9ga
Command line:  cc /home/ports/pobj/mpv-0.35.0/build-amd64/meson-private/tmpe2s2p9ga/testfile.c -E -P -O2 -pipe -g -D_FILE_OFFSET_BITS=64 -P -O0 -Werror=implicit-function-declaration

Code:

        #ifdef __has_include
         #if !__has_include("iconv.h")
          #error "Header 'iconv.h' could not be found"
         #endif
        #else
         #include <iconv.h>
        #endif
Compiler stdout:


Compiler stderr:
 /home/ports/pobj/mpv-0.35.0/build-amd64/meson-private/tmpe2s2p9ga/testfile.c:4:12: error: "Header 'iconv.h' could not be found"
          #error "Header 'iconv.h' could not be found"
           ^
1 error generated.

Running compile:
Working directory:  /home/ports/pobj/mpv-0.35.0/build-amd64/meson-private/tmpfau0706l
Command line:  cc /home/ports/pobj/mpv-0.35.0/build-amd64/meson-private/tmpfau0706l/testfile.c -o /home/ports/pobj/mpv-0.35.0/build-amd64/meson-private/tmpfau0706l/output.exe -O2 -pipe -g -D_FILE_OFFSET_BITS=64 -O0 -Werror=implicit-function-declaration -Wl,--start-group -liconv -Wl,--end-group -Wl,--allow-shlib
-undefined

Code:
 int main(void) { return 0; }

Compiler stdout:

Compiler stderr:
 ld: error: unable to find library -liconv
cc: error: linker command failed with exit code 1 (use -v to see invocation)

Run-time dependency iconv found: NO (tried builtin and system)

../../pobj/mpv-0.35.0/mpv-0.35.0/meson.build:605:0: ERROR: Dependency "iconv" not found, tried builtin and system
```

```
../../pobj/mpv-0.35.0/mpv-0.35.0/meson.build:719:0: ERROR: C shared or static library 'atomic' not found
```

OpenBSD and FreeBSD do not use libatomic.

**Comment by Dudemanguy** [comment]
`iconv` is a custom [meson dependency](https://mesonbuild.com/Dependencies.html). I guess maybe report upstream to meson if that doesn't work and it's supposed to be found somewhere. How does `libatomic` work on BSD? Is it like dl and provided by the libc?

**Comment by eli-schwartz** [comment]
libc of any description does not typically install pkg-config files for internally implemented functions (maybe they should) and GNU libiconv is maintained by someone who thinks that adding a text file to your git repo called `*.pc` results in your software no longer being Free Software as the FSF defines it, because pkg-config "entices users to give up their freedom to modify and replace the software if they so choose". (This is because he feels it's difficult / unknowable to use it for cross compilation, and also unlike the sacred autotools `*.m4` files you cannot specify options like "bundled" or "system" :roll_eyes:.)

So it's unlikely that GNU libiconv will ever include pkg-config files either. And I think that's the only generally-in-use standalone iconv? So, not sure what pkg-config file you're expecting meson to pick up.

**Comment by brad0** [comment]
> `iconv` is a custom [meson dependency](https://mesonbuild.com/Dependencies.html). I guess maybe report upstream to meson if that doesn't work and it's supposed to be found somewhere. How does `libatomic` work on BSD? Is it like dl and provided by the libc?

OpenBSD / FreeBSD use compiler-rt instead of the GNU run-time libgcc + libatomic. The atomic functions are within compiler-rt. You don't have to add anything when linking.

**Comment by brad0** [comment]
> libc of any description does not typically install pkg-config files for internally implemented functions (maybe they should) and GNU libiconv is maintained by someone who thinks that adding a text file to your git repo called `*.pc` results in your software no longer being Free Software as the FSF defines it, because pkg-config "entices users to give up their freedom to modify and replace the software if they so choose". (This is because he feels it's difficult / unknowable to use it for cross compilation, and also unlike the sacred autotools `*.m4` files you cannot specify options like "bundled" or "system" 🙄.)
> 
> So it's unlikely that GNU libiconv will ever include pkg-config files either. And I think that's the only generally-in-use standalone iconv? So, not sure what pkg-config file you're expecting meson to pick up.

The whole point of building GNU iconv standalone is that the libc implementation does not have said functions. Of course a libc won't have pkg-config files. 

My mistake, I thought both iconv and gettext had pkg-config files but I see now I was wrong.

That is some typical and expected FSF / GNU lunacy.

**Comment by eli-schwartz** [comment]
> The whole point of building GNU iconv standalone is that the libc implementation does not have said functions. Of course a libc won't have pkg-config files.

That particular tangent of mine was philosophical musing about if GNU libc for Linux, which does provide iconv and gettext functions, would provide pkg-config files. :)

> That is some typical and expected FSF / GNU lunacy.

Well, at least one GNU maintainer, who does admittedly acknowledge that in so doing, he doesn't speak on behalf of the GNU project as a whole -- it's a personal opinion.

Other GNU projects do provide pkg-config files. I guess they are non-free. :rofl:

**Comment by Dudemanguy** [comment]
>OpenBSD / FreeBSD use compiler-rt instead of the GNU run-time libgcc + libatomic. The atomic functions are within compiler-rt. You don't have to add anything when linking.

Well for the stdatomic part, this should do the trick I think.

```
diff --git a/meson.build b/meson.build
index c2916d5fb9..0eb10d4fe1 100644
--- a/meson.build
+++ b/meson.build
@@ -716,10 +716,11 @@ if features['sdl2-gamepad']
     sources += files('input/sdl_gamepad.c')
 endif
 
-stdatomic = cc.find_library('atomic', required: get_option('stdatomic'))
-features += {'stdatomic': stdatomic.found()}
+stdatomic_dep = cc.find_library('atomic', required: false)
+features += {'stdatomic': cc.has_header_symbol('stdatomic.h', 'atomic_int', dependencies: stdatomic_dep,
+                                               required: get_option('stdatomic'))}
 if features['stdatomic']
-    dependencies += stdatomic
+    dependencies += stdatomic_dep
 endif
 
 uchardet_opt = get_option('uchardet').require(
```

**Comment by brad0** [comment]
With the dl fix and this patch it looks like we're good to go. I just submitted my diff to convert our port from WAF to Meson.

**Comment by Dudemanguy** [comment]
What about iconv? Was there any lingering issues with that still?

**Comment by brad0** [comment]
> What about iconv? Was there any lingering issues with that still?

I'm good there. It was the only piece that appears to not have a pkg-config file. For that we typically add in LOCALBASE/include and LOCALBASE/lib to CPPFLAGS / LDFLAGS or in this case CFLAGS / LDFLAGS for Meson.

**Comment by Dudemanguy** [comment]
Great, thanks for testing. I'll whip up a PR in a bit.
