### ISSUE TITLE
Make sub-seek faster

### ISSUE THREAD

**Issue by JohnFinn** [mpv-player/mpv#10904]
When using `sub-seek` command (`no-osd sub-seek -1` or `no-osd sub-seek 1` to be more percise) there is a noticeable timeout (~0.5 seconds) before it finishes. This can be very annoying when using this feature a lot.

UPD: `seek` at the same file works instantly (tested wit up, down, left, right keyboard arrows. Didn't override these)

### Expected behavior of the wanted feature
`sub-seek` is as fast as `seek` 

### Alternative behavior of the wanted feature
`sub-seek` is 10% slower than `seek` (or the timeout is unnoticeable to a human)

**Comment by hooke007** [comment]
Unless it tries to seek keyframes, or it's impossible.

**Comment by JohnFinn** [comment]
> Unless it tries to seek keyframes, or it's impossible.

That's a strong statement, can you explain why?

**Comment by hooke007** [comment]
Isn't it a common sense that seeking keyframes is always faster than non-keyframes?

**Comment by JohnFinn** [comment]
> Isn't it a common sense that seeking keyframes is always faster than non-keyframes?

I don't know. I have zero experience with video.

The way I understand `sub-seek` works is that it uses `seek` under the hood. And if `seek` finishes instantly, than `sub-seek` might work as fast.

**Comment by hooke007** [comment]
`sub-seek` is similar to `seek x exact` https://mpv.io/manual/master/#command-interface-seek-%3Ctarget%3E-[%3Cflags%3E]
`seek` would be slow if using exact or `hr-seek` https://mpv.io/manual/master/#options-hr-seek

**Comment by Dudemanguy** [comment]
I don't think this is feasibly actionable either. `sub-seek` has to work by doing exact seeks under the hood which is just fundamentally slower than keyframe seeks. If you configure your `seek` commands to do exact seeks, you'll notice that it's slower as well.

**Comment by JohnFinn** [comment]
> I don't think this is feasibly actionable either. `sub-seek` has to work by doing exact seeks under the hood which is just fundamentally slower than keyframe seeks. If you configure your `seek` commands to do exact seeks, you'll notice that it's slower as well.

How much accuracy does keyframe `seek` sacrifice by the way? Maybe if the error is unnoticeable to a human, a non-exact version of `sub-seek` can be created and will be sufficient.

**Comment by Dudemanguy** [comment]
>How much accuracy does keyframe seek sacrifice by the way?

A ton. If you pay attention to the standard seek commands, they can be off by multiple seconds depending on the video (i.e. your seek 10 might end up being closer to seek 7 or something). For subtitles, you can't just assume they're all going to be magically on key frames (that's what the keyframe seek does) so, mpv has to do an exact seek to go to the next subtitle with `sub-seek`. And it's just slower.

**Comment by escape0707** [comment]
Sorry for replying on an old thread here, but is there anyway to "make some buffer larger" / "decode ahead" / sacrifice more RAM and make exact seek within, say +5s, faster?

 I'm watching many lecture videos with many dialogs recently, and some lecturers speak while writing on whiteboard. I don't want to wait for them to finish writing, so I bind my mouse wheel to sub-seek 1 for this. It could be better if I can insta seek for the next sentence if it's just 1-5s ahead.

**Comment by kasper93** [comment]
https://mpv.io/manual/master/#command-interface-sub-seek

> For embedded subtitles (like with Matroska), this works only with subtitle events that have already been displayed, or are within a short prefetch range. See [Cache](https://mpv.io/manual/master/#cache) for details on how to control the available prefetch range.

You can control cache and make it as long as you need.

**Comment by escape0707** [comment]
@kasper93 I've tried `--demuxer-readahead-secs=20 --cache=yes` but the 0.5s latency when skipping to next subtitle's timestamp is not improved. Could you please point out which config you are referring to exactly for me?

**Comment by au-summer** [comment]
Same problem even after setting the `big-cache` profile as in documentation, i.e.
```
cache=yes
demuxer-max-bytes=512MiB
demuxer-readahead-secs=20
```
in mpv.conf
