### ISSUE TITLE
Black screen with wlroots (sway) WLR_RENDERER=vulkan

### ISSUE THREAD

**Issue by kkost** [mpv-player/mpv#10909]
Attempting to use the new dmabug-wayland with Vulkan. When using sway with WLR_RENDERER=vulkan set, mpv only displays black with no errors, but spams this with -v set:

```
[statusline] AV: 00:00:00 / 00:21:18 (0%) A-V:  0.000
[vo/dmabuf-wayland] Allocate buffer pool entry : 20
[vo/dmabuf-wayland] NV12(0100000000000002) is not supported.
[vo/dmabuf-wayland] Failed to import
[vo/dmabuf-wayland] Free buffer pool entry : 20
[statusline] AV: 00:00:00 / 00:21:18 (0%) A-V:  0.000
[vo/dmabuf-wayland] Allocate buffer pool entry : 19
[vo/dmabuf-wayland] NV12(0100000000000002) is not supported.
[vo/dmabuf-wayland] Failed to import
[vo/dmabuf-wayland] Free buffer pool entry : 19
[statusline] AV: 00:00:00 / 00:21:18 (0%) A-V:  0.000
[vo/dmabuf-wayland] Allocate buffer pool entry : 18
[vo/dmabuf-wayland] NV12(0100000000000002) is not supported.
[vo/dmabuf-wayland] Failed to import
[vo/dmabuf-wayland] Free buffer pool entry : 18
...
```

Config-
```
gpu-context=waylandvk
gpu-api=vulkan
vulkan-device='Intel(R) UHD Graphics 620 (KBL GT2)'
hwdec=vaapi
hwdec-codecs=all
vo=dmabuf-wayland
```

**Comment by Dudemanguy** [comment]
Is your issue implying that it works normally when not using the vulkan renderer? Well anyways, your log indicates the compositor doesn't support the format so this simply won't work. Eventually, we'd like to get some better format probing in here to error out in cases like this but that takes a bit more work.

**Comment by kkost** [comment]
Sorry wasn't clear - correct that it works when not using WLR_RENDERER=vulkan . So you're saying wlroots/sway has some work to around it? And yah I get it :) really just trying to see if I could get all the new shinies working together. In any case, not a gamebreaker for me (works with vo=gpu or by not using vulkan for wlroots). Thanks!

**Comment by Dudemanguy** [comment]
Yeah wlroots's vulkan renderer would need to get support for that format. It's a bit niche so not too surprising its not there yet.
