### ISSUE TITLE
MPV 0.35 SUBTITLE right to left no working,its show revers in Hebrew ,mpv 0.34 working good

### ISSUE THREAD

**Issue by YOYO48** [mpv-player/mpv#10910]
### Important Information

Provide following Information:
- mpv version 0.35
- Windows Version win11
- Source of the mpv binary
- If known which version of mpv introduced the problem in mpv 0.34 work good
![CaptureItPlus638046728431641198](https://user-images.githubusercontent.com/118776337/203169014-68186d10-8da5-4902-8dbb-839c944bd10f.jpeg)

THIS IS MPV 0.34 OK
![CaptureItPlus638046736613333339](https://user-images.githubusercontent.com/118776337/203170802-fcbd3131-122f-402b-9de7-668e32462a76.jpeg)

**Comment by YOYO48** [comment]
SOMEONE?

**Comment by jeeb** [comment]
@YOYO48 please do not re-post the same issue. You can already see that your initial duplication caused the issue being closed. Repeat offenses will not help your cause. Also please for such types of issues provide sample files for testing and `--log-file=mpv.log` for both working and non-working cases, as was most likely noted by the issue template.

Just as a simple guess, as mpv does very little other than passing on text and styling to libass for subtitle rendering, this is most likely a thing related to the configuration of libass in the build you are using, and whatever is working underneath it: Freetype, Fribidi and Harfbuzz.

You should thus check with the builder who built your binaries regarding which versions and configurations libass and its dependencies were built with (Freetype, Fribidi and Harfbuzz are the general dependencies).

**Comment by YOYO48** [comment]
hi
i found the problem,and i fix it.
the line in config. file
sub-spacing=0.5   * i remove this line and its fix
thanks

**Comment by jeeb** [comment]
Quickly checking, this affects the Spacing entry in libass's Style structure utilized for these lines. I think you might want to make sure you check that your libass is built with fribidi and harfbuzz and then possibly checking with the libass people whether they can see the same issue with current latest (master) version of libass?

**Comment by YOYO48** [comment]
thanks man,this issue solved👍👍

**Comment by jeeb** [comment]
OK, so libass already had this reported and that this is a compatibility thing to match behavior with ye olde VSFilter https://github.com/libass/libass/issues/626#issuecomment-1166374335
