### ISSUE TITLE
`cache-dir` in `mpv.conf` doesn't support `~` as `C:\Users\username`

### ISSUE THREAD

**Issue by brian6932** [mpv-player/mpv#10917]
### Important Information

- mpv 0.35.0-15-gf10b24e3c5
- Windows 10
- `mpv-git` scoop package which uses sourceforge.net

### Reproduction steps

Could also be a feature request depending on how you look at it. `glsl-shaders`, `screenshot-directory`, and every other dir `mpv.conf` setting seems to support `~` as `C:\Users\username` (although they only work with `/`, not `\`).

### Expected behavior

```ini
screenshot-directory = ~/Downloads
cache-dir = ~/AppData/Local/Temp
```
should work fine

### Actual behavior

```ini
screenshot-directory = ~/Downloads
cache-dir = C:\Users\username\AppData\Local\Temp
```
Doesn't work, you have to use an absolute path, breaking portability of the conf

**Comment by Dudemanguy** [comment]
`[   0.010][d][global] user path: '~/testing' -> '/home/user/testing'`

Works for me and I see no reason why it shouldn't in your case as of master.
