### ISSUE TITLE
On macOS "window-scale" or "current-window-scale" do not follow resizing apps like BetterTouchTool or Magnet

### ISSUE THREAD

**Issue by LampPrinter** [mpv-player/mpv#10924]
mpv version - 0.35
macOS Version - 13.0

Pinch to resize gesture modifies "window-scale" in MPV.
When using an app like BetterTouchTool or Magnet to maximise or snap the MPV window to sides, "window-scale" or "current-window-scale" do not get updated.

So, now if I do the pinch to resize gesture, the window jumps back to the original "window-scale" saved value. Not ideal behaviour.

I hope I was able to explain the issue.

This is not a problem in IINA.

**Comment by elzii** [comment]
What are the default binds for this? Would like to change in input.conf, but not seeing anything in keycodes.h, etc.
