### ISSUE TITLE
Ok but where dahek is this mystical `~/.config/` folder actually though???

### ISSUE THREAD

**Issue by tdbe** [mpv-player/mpv#10922]
So here's the situation:
- UI of program has almost no buttons, no options, and tons of hidden features (e.g. scroll but only on top of the speaker icon as the only way to change volume lol)
- pdf manual implies there may be key bindings but doesn't tell you what those are or where.
- [website says](https://mpv.io/manual/master/#files) "usually ~/.config/mpv/input.conf".

Thanks mate, so let's say I am a non wizard computer user, like, you know, 99% of humans. WHERE IS THIS FILE?? :)
I am in windows, and installed it via chocolatey. But I don't have a PhD in how linux to windows paths work, or chocolatey, or wtf ~ is and how to duckduckgo it.

The backend, open source nature, scriptability, responsiveness of the algos in mpv-player seem stellar. 
I actually installed mpv because vlc was slideshow choking with various 4k videos on a gaming PC, no matter what settings I was told to tweak. And in mpv it worked flawlessly out the box as it should. 

But there is literally 0 ux T_T
Where is the input.conf file location? Pls provide examples for as many platforms/installations as possible, so normal humans can get a clue.

**Comment by bitraid** [comment]
>[website says](https://mpv.io/manual/master/#files) "usually ~/.config/mpv/input.conf".

Before that, it also says "For Windows-specifics, see [FILES ON WINDOWS](https://mpv.io/manual/master/#files-on-windows) section."

**Comment by bitraid** [comment]
You have to create the files - see https://github.com/mpv-player/mpv/raw/master/etc/mpv.conf and https://github.com/mpv-player/mpv/raw/master/etc/input.conf.
`~/` is also explained in the [manual](https://mpv.io/manual/master/#paths).

**Comment by LaserEyess** [comment]
If mpv is too complicated for you to figure out, you can try https://github.com/mpvnet-player/mpv.net. It's for windows users.

**Comment by CounterPillow** [comment]
tfw the filter is working

**Comment by N-R-K** [comment]
> so let's say I am a non wizard computer user, like, you know, 99% of humans. WHERE IS THIS FILE?

The solution here seems obvious - become top 1% of humans by figuring out where this file is :mage_man:

**Comment by tdbe** [comment]
> You have to create the files - see https://github.com/mpv-player/mpv/raw/master/etc/mpv.conf and https://github.com/mpv-player/mpv/raw/master/etc/input.conf. `~/` is also explained in the [manual](https://mpv.io/manual/master/#paths).

"~/	user home directory root (similar to shell, $HOME)" --- So does this mean `c:/users/USERNAME/`? Still unclear for non wizards ;)

Anyway, I gave up as soon as I heard I have to create the config files. I've done enough steps, I have the clown wig on and everything (in this case the fake wizard hat), and now I have to make the files? I think there's something very wrong / misaligned when you need to search a 10,000 line manual just to get started with basic feature parity to all other media players.

**Comment by tdbe** [comment]
> If mpv is too complicated for you to figure out, you can try https://github.com/mpvnet-player/mpv.net. It's for windows users.

Omg THANK YOU SO MUCH. I had no idea this existed. It's not that it's too complicated, it's that I have a different dayjob than to do the hours of research/labour to get basic functionality. So this mpv.net is great. Actually has "Options" 👍
