### ISSUE TITLE
HDMI Connection as a Profile Condition

### ISSUE THREAD

**Issue by george-emerald** [mpv-player/mpv#10925]
I'd like to know if it's possible to use an HDMI connection as a profile condition. I want audio passthrough to only be enabled when I'm connected to my sound system, so I don't have to edit my config every time I disconnect it. The line I'd like to put under the condition is `audio-spdif=dts, ac3`.

**Comment by Dudemanguy** [comment]
You can use the `display-names` property for something like this. The actual string in this property will vary depending on your OS/windowing system/etc, but I'm going to assume that anything with an HDMI connection will be called something like `HDMI-0` or `HDMI-A-0` or something similar. In that case, this would work in your conf.

```
[passthrough]
profile-cond=string.match(display_names[1], "HDMI") ~= nil
profile-restore=copy
audio-spdif=dts, ac3
```
