### ISSUE TITLE
Slow startup for youtube videos

### ISSUE THREAD

**Issue by j-ace-svg** [mpv-player/mpv#10927]
### Important Information
- mpv version: 0.34.1
- Linux Distribution and Version: Pop!_OS (based on Ubuntu/Debian)
- Source of the mpv binary: installed from apt
- Window Manager and version: default Pop!_OS Gnome
- GPU driver and version: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)

### Reproduction steps
Load a youtube video in mpv (I usually do it with a keybinding in qutebrowser but it works directly from the command line too).

### Expected behavior
mpv shouldn't take too long to load.

### Actual behavior
mpv takes around 4-5 seconds to load.

### Log file
Output from `strace -cw mpv https://www.youtube.com/watch?v=tgbpNuOfFQM --log-file=log_tmp --no-config`
[mpv_log.txt](https://github.com/mpv-player/mpv/files/10089726/mpv_log.txt)
[strace_log.txt](https://github.com/mpv-player/mpv/files/10089727/strace_log.txt)

At first glance in the mpv log a good 1-2 seconds is taken up by repeated executions of `Run command: disable-section, flags=64, args=[name="window-controls"]`, another decent 1.5 seconds is taken up by `yt-dlp` downloading the video but that's pretty consistent with my normal youtube load times.

**Comment by CounterPillow** [comment]
> At first glance in the mpv log a good 1-2 seconds is taken up by repeated executions of Run command: disable-section, flags=64, args=[name="window-controls"]

What makes you think these don't happen concurrently with the critical path?

It's most likely waiting for yt-dlp (python interpreter startup is dogshit slow) and video data. You can always set --force-window=immediate to have it show a window immediately, which alleviates some of the annoyances of long loading times for me.

**Comment by j-ace-svg** [comment]
> What makes you think these don't happen concurrently with the critical path?

Sorry, I'm not sure what you mean by that.

> It's most likely waiting for yt-dlp (python interpreter startup is dogshit slow) and video data.

I'm not familiar with the internals and whatnot, but it would seem that the first part (0.610 to 2.192, subprocess using yt-dlp) would have the loading of the video and launching of yt-dlp, no?

Again, this was all first glance things that caught my eye, I don't know the internals of this program or (outside of guessing from the description) the different steps/stages in the log.

**Comment by j-ace-svg** [comment]
(Sorry about that close, that was a misclick)

> What makes you think these don't happen concurrently with the critical path?

Sorry, I'm not sure what you mean by that.

> It's most likely waiting for yt-dlp (python interpreter startup is dogshit slow) and video data.

I'm not familiar with the internals and whatnot, but it would seem that the first part (0.610 to 2.192, subprocess using yt-dlp) would have the loading of the video and launching of yt-dlp, no?

Again, this was all first glance things that caught my eye, I don't know the internals of this program or (outside of guessing from the description) the different steps/stages in the log.

**Comment by sfan5** [comment]
from your log:
<pre>
[   0.023][v][ffmpeg] Opening https://www.youtube.com/watch?v=tgbpNuOfFQM
^ mpv tries to load the URL
[   0.610][v][cplayer] Opening failed or was aborted: https://www.youtube.com/watch?v=tgbpNuOfFQM
^ it realizes thats a html page and not a video file
[   0.610][d][cplayer] Run command: subprocess, flags=64, args=[args="yt-dlp,--no-warnings,-J,...
^ defers to yt-dlp
[   2.195][v][edl] Opening edl://!new_stream;!no_clip;!no_chapters;...
^ receives the real video URL from yt-dlp
[   2.698][v][cplayer] Opening done: edl://!new_stream;!no_clip;!no_chapters;...
^ all streams loaded
[   2.818][v][cplayer] first video frame after restart shown
^ first video frame shown
</pre>

**Comment by adisib** [comment]
It has been recommended to use something like this to speed up loading if you use mpv with youtube a lot:
`script-opts=ytdl_hook-ytdl_path=yt-dlp,ytdl_hook-try_ytdl_first=yes,ytdl_hook-exclude="%.webm$|%.ts$|%.mp3$|%.m3u8$|%.m3u$|%.mkv$|%.mp4$|%.VOB$"`

**Comment by j-ace-svg** [comment]
Thank you, that has improved startup times a lot. Out of curiosity since I noticed that in some instances in the log it looks like mpv tries brute forcing to see which application is available for a certain task, do you know what it's doing when it logs `Run command: disable-section, flags=64, args=[name="window-controls"]`? (And if it's trying to brute force something, is there a command line arg/options I can use to preset it?)

**Comment by Dudemanguy** [comment]
>Out of curiosity since I noticed that in some instances in the log it looks like mpv tries brute forcing to see which application is available for a certain task, do you know what it's doing when it logs Run command: disable-section, flags=64, args=[name="window-controls"]?

This was actually just a bug in the osc code. It was mistakenly spamming mpv with a bunch of input commands unnecessarily. There was no real performance impact but it's been fixed in the master branch. Original question seems answered so closing.
