### ISSUE TITLE
cycle-values window-scale start from 1.0 first

### ISSUE THREAD

**Issue by brucmao** [mpv-player/mpv#10929]
```
w     cycle-values window-scale "1.0" "1.5" "2.0" "0.5" ; show-text "Scale: ${window-scale}"
```
Every time I start mpv and press the w shortcut key, the Scale starts at 1.5
How to change the Scale start from 1.0 first

**Comment by hooke007** [comment]
It should be `current-window-scale` instead of `window-scale`
