### ISSUE TITLE
0.35 introduced !impl->polling' failed at ../spa/plugins/support/loop.c:872 impl_clear()

### ISSUE THREAD

**Issue by zenny** [mpv-player/mpv#10921]
### Important Information

See https://github.com/trizen/pipe-viewer/issues/145

This was introduced by mpv 0.35. The bug did not exist in 0.34, fyi

**Comment by sfan5** [comment]
duplicate of #10859

it's not quite clear whether this is mpv or pipewire's fault but if you upgrade pipewire to 0.3.60 the error goes away.
