### ISSUE TITLE
osd-bar shadow

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#10923]
Is it possible to modify osd-bar's shadow?

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#options-osd-shadow-color
https://mpv.io/manual/master/#options-osd-shadow-offset

**Comment by Max-Enrik** [comment]
I don't see any changes.

`osd-shadow-color=1.0/0.0/0.0`
`osd-shadow-offset=1`

![mpv issue - osd bar shadow](https://user-images.githubusercontent.com/3518174/203905807-8bd70e47-3795-4438-b754-cfa275908c25.png)

**Comment by hooke007** [comment]
It’s osc. Not osd-bar

**Comment by Max-Enrik** [comment]
Couldn't do it myself.
`a cycle_values options/font_color "1/0/0"`

**Comment by hooke007** [comment]
i do not understand what you were doing.

**Comment by Max-Enrik** [comment]
I want to add a shadow and modify its color of it.

**Comment by hooke007** [comment]
Impossible by options.

**Comment by Max-Enrik** [comment]
Oh! Hope there is a chance to modify them.

**Comment by Max-Enrik** [comment]
Where to look to modify them?

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua

**Comment by Max-Enrik** [comment]
Thank you so much more, I have to look at it closely later.

**Comment by avih** [comment]
> ![mpv issue - osd bar shadow](https://user-images.githubusercontent.com/3518174/203905807-8bd70e47-3795-4438-b754-cfa275908c25.png)

We call this OSC, not OSD.

There are no configurable shadows at the OSC.

These are the configurable things at the OSC: https://mpv.io/manual/master/#configuration

**Comment by Max-Enrik** [comment]
@avih - thank you!
I have checked them out.

Its color is white. If a video background is white, I can't see OSC at all.
I have chosen that screenshot so that you can see what I was talking about. _(I didn't know what it was called.)_

I still didn't make time to look closely `osc.lua` file.

**Comment by avih** [comment]
> s color is white. If a video background is white, I can't see OSC at all.
> I have chosen that screenshot so that you can see what I was talking about.

Not sure what you mean, the backgound in your screenshot orange and purple, not white.

Regardless, try `--script-opts-add=osc-boxalpha=40`. The default is 80, opaque is 0, fully transparent is 255. You can also put it in your `osc.conf` at your `script-opts/` directory, or at `mpv.conf`. Check the docs how to use script options.

**Comment by Max-Enrik** [comment]
I set 255 for full transparency.
I think `--script-opts-add=osc-boxalpha=40` can work well until I found how to add shadow, color, and border to the OSC.

These didn't work. `input.conf`
`a script-opts-add=osc-boxalpha=40`
`a script-message cycle-cmd "script-message osc-boxalpha 40"`

**Comment by avih** [comment]
> These didn't work. `input.conf`
> `a script-opts-add=osc-boxalpha=40`
> `a script-message cycle-cmd "script-message osc-boxalpha 40"`

Don't guess. Read the docs please.

[`script-opts`](https://mpv.io/manual/master/#options-script-opts) is [list option](https://mpv.io/manual/master/#list-options), and these can be changed with the [`change-list`](https://mpv.io/manual/master/#command-interface-change-list) command.

**Comment by Max-Enrik** [comment]
I am trying to achieve them shortly/cheat. :  )

**Comment by Max-Enrik** [comment]
No clue. It can't be done myself.

**Comment by Max-Enrik** [comment]
Oh! I need help. lol

**Comment by Max-Enrik** [comment]
@avih - thank you, I highly appreciate your replies.

mpv.conf

`[oscbalpha]`
`profile-desc="OSC Back Alpha"`
`script-opts-add=osc-boxalpha=40`

input.conf

`a script-message cycle-cmd "apply-profile oscbalpha" "apply-profile oscbalpha restore"`

**Restore** doesn't apply.
