### ISSUE TITLE
Media Title into screenshot file name.

### ISSUE THREAD

**Issue by Max-Enrik** [mpv-player/mpv#10930]
### Important Information

- mpv version 34
- Windows Version 10 x64

mpv.conf

`[scr_title]`
`profile-desc="Screenshot with Title"`
`screenshot-template="%{media-title}-%01n"`

input.conf
`s script-message cycle-cmd "apply-profile scr_title"`

My expectation is video title into a screenshot file name.

**Comment by stax76** [comment]
I do it like this:

`screenshot-to-file '/home/username/Desktop/mpv screenshot ${time-pos} ${filename}.jpg'`
