### ISSUE TITLE
Something changed that broke youtube playback?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#10934]
I'm using ```mpv-x86_64-v3-20221126-git-e97e0e4.7z``` (https://github.com/shinchiro/mpv-winbuild-cmake/releases)
And YouTube videos don't work.

But when I use ```mpv-x86_64-v3-20221124-git-ead8469.7z```
YouTube videos work.

**Comment by CounterPillow** [comment]
why did you submit this as a question? With literally no information like log files?

**Comment by Obegg** [comment]
> why did you submit this as a question? With literally no information like log files?

To know if it's only issue on my PC (also didn't see any open issues about it) - if it is then I can probably solve it.

**Comment by llyyr** [comment]
Works on my machine™

If you want a different answer, fill out the issue template. Or at least try to see if it works with yt-dl or yt-dlp, if it still doesn't then the issue belongs there

**Comment by bitraid** [comment]
See https://github.com/shinchiro/mpv-winbuild-cmake/issues/292.
