### ISSUE TITLE
Secondary Subtitle Positioning

### ISSUE THREAD

**Issue by InklingGirl** [mpv-player/mpv#10938]
Hello, turning on secondary subtitles via `secondary-sid` overlaps them w/ the other subtitles. I'm able to move the elevation of both subtitles w/ `sub-pos`, which leads me to think I should be able to adjust their elevations independently of each other's, but I can't see how. Is there a way to do this? Thank you.

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/3022
https://github.com/mpv-player/mpv/issues/7622

**Comment by InklingGirl** [comment]
@hooke007 https://github.com/mpv-player/mpv/issues/3022#issuecomment-460058021 I ripped my subtitles perfectly fine & they play perfectly fine on their own, but neither of the tools here can merge them, presumably because they're bitmaps. How can I merge them?

**Comment by hooke007** [comment]
i mean dup

**Comment by InklingGirl** [comment]
how kind of you

**Comment by InklingGirl** [comment]
Does anyone have any advice?

**Comment by garoto** [comment]
Secondary sub rendering is|was always sub-par regarding user configurable options. There's nothing you can do about it. These are all the options and properties related to secondary subs:

	> mpv --list-properties | rg secon
	[  0.013668]    cplayer:  secondary-sid
	[  0.013697]    cplayer:  secondary-sub-text
	[  0.013714]    cplayer:  secondary-sub-start
	[  0.013726]    cplayer:  secondary-sub-end
	[  0.017800]    cplayer:  secondary-sub-visibility

	> mpv --list-options|rg -v deprecated|rg seco
	 --secondary-sid                  Choices: no auto (or an integer) (0 to 8190) (default: no)
	 --secondary-sub-visibility       Flag (default: yes)

Perhaps limited by libass shenanigans, but mostly likely not in this case. If only wm4 didn't had a nervous breakdown, this could be a non-issue anymore... holy shit.

**Comment by Dudemanguy** [comment]
Closing since duplicate as noted.

**Comment by InklingGirl** [comment]
Pffft, works perfectly in VLC 4.0, just fork the code from that.

**Comment by zestyping** [comment]
If you want the subtitles stacked together on the bottom of the screen, you can also merge the subtitle files into one file.  I used https://subtitletools.com/merge-subtitles-online and the results were great!  It even lets you select an alternate colour for one of the files.

**Comment by InklingGirl** [comment]
Hm, interesting!

**Comment by dejafait** [comment]
It is now possible, see `secondary-sub-pos`.

**Comment by InklingGirl** [comment]
hhmmm
