### ISSUE TITLE
Feature to lock/unlock the OSD controls and keyboard shortcuts

### ISSUE THREAD

**Issue by mrjpaxton** [mpv-player/mpv#10933]
Hello everyone.

I was looking around to see if there was a command or ability for the OSD to lock playback controls and keybinds, but I could not find anything!

I was hoping for a feature to lock all OSD controls (or at least the ones that manipulate playback of the video, but still allow hotkeys that show information about the video, like the "o" and "i" keybinds, for example).

Why would such a feature be useful? Two reasons for me.

**Number 1:** I use a tiling window manager like i3/SwayWM that has a floating window feature, and I like to work on multimedia projects (audio/video/graphics editing) in the background, but I also multitask by idly listening or watching a small floating video on my screen. For that, I pop open mpv on a video URL and have it floating on top of my other window(s), so I do not have to pull my browser tab as a floating window over instead, which is very cumbersome. And I like mpv's stream caching system better anyway once it's tuned and configured to my liking.

However, sometimes by mistake--especially if I am using a tablet--my mouse will nudge over and make the window active again. When I press certain hotkeys, it will make the video will jump to another position, and then I will lose my place in the video. That can be pretty dang frustrating.

**Number 2:** If mpv is ever going to have a chance to work well for mobile GNU/Linux users, think of the Pinephone, Librem 5, etc... or whatever will come out next. There really NEEDS to be a feature to lock accidental finger presses and fat thumbing of controls. It's a good forward-thinking, future-proofing feature. **VLC on Android already has a feature like this for its video player.** So for mpv to also have this would be an excellent addition for better mobile support!

---

### Expected behavior of the wanted feature
Initially, when a key combination is pressed (such as Ctrl+L, but this can be user-configured) it will lock all OSD and keybind controls until Ctrl+L is pressed again. Essentially, Ctrl+L acts as a toggle.

It would be a good idea to have the Ctrl+L keybind **unset by default** so that new users do not accidentally use Ctrl+L, and don't understand what is going on. Should be manually able to be bound first.

For mobile mpv users in the future, a medium-sized lock icon should appear somewhere, by default, on the top-left or top-right of the video (position of the lock graphic could be user-configured) that will also allow toggling the OSD lock/unlock feature. Maybe a small text description next to the lock or below it (dependent on its position) could say: "Press here or use Ctrl+L to unlock controls."

The SVG/vector lock icon size could be configured, such as: "small", "medium", or "large", or it could be pixel (px) or point (pt) size.

The OSD lock icon and text description should only be displayed on mouse activity (mouse movement/button presses) on the active mpv window, and should fade away after a default delay of about 5-10 seconds.

Possible positions of the lock might be: "top", "left", "bottom", "right", "top-left", "top-right", "bottom-right", "bottom-left", and "center".

A boolean option that displays the lock and text description, or not, that could be set to "true" (default), or "false". Perhaps display of the text description and lock can be separated, too.

### Alternative behavior of the wanted feature
(Request for comments)

### Log file
http://0x0.st/oUl4.txt

Looking forward to hearing any feedback!

**Comment by mrjpaxton** [comment]
Okay, since nobody is working on this, and I thought it might be a good idea to have it as a user script anyway,  so I'm making a very simple script for myself.

I'm trying to do this:

```
local mp = require 'mp'

local toggled = true;

function osd_lock()
    if toggled then
        mp.add_forced_key_binding("right", nil)
        mp.add_forced_key_binding("left", nil)
        mp.add_forced_key_binding("up", nil)
        mp.add_forced_key_binding("down", nil)
        mp.add_forced_key_binding("p", nil)
        mp.add_forced_key_binding("MBTN_LEFT", nil)
        mp.osd_message("Locked", 10)
    else
        mp.remove_key_binding("right")
        mp.remove_key_binding("left")
        mp.remove_key_binding("up")
        mp.remove_key_binding("down")
        mp.remove_key_binding("p")
        mp.remove_key_binding("MBTN_LEFT")
        --mp.add_forced_key_binding("left", mp.command("seek +5 exact"))
        --mp.add_forced_key_binding("right", mp.command("seek -5 exact"))
        --mp.add_forced_key_binding("up", mp.command("seek +15 exact"))
        --mp.add_forced_key_binding("down", mp.command("seek +15 exact"))
        --mp.add_forced_key_binding("p", mp.command("no-osd cycle pause"))
        --mp.add_forced_key_binding("MBTN_LEFT", mp.command("no-osd cycle pause"))
        --mp.add_forced_key_binding("left", mp.commandv("seek", "+5", "exact"))
        --mp.add_forced_key_binding("right", mp.commandv("seek", "-5", "exact"))
        --mp.add_forced_key_binding("up", mp.commandv("seek", "+15", "exact"))
        --mp.add_forced_key_binding("down", mp.commandv("seek", "+15", "exact"))
        --mp.add_forced_key_binding("p", mp.commandv("no-osd", "cycle", "pause"))
        --mp.add_forced_key_binding("MBTN_LEFT", mp.commandv("no-osd", "cycle", "pause"))
        mp.osd_message("Unlocked", 10)
    end
    toggled = not toggled
end

mp.add_key_binding("ctrl+l", osd_lock
```

But the problem is that `mp.command` (and similar) aren't able to remap the keys back. When it goes back to the unlocked state, and an`mp.command` thing is enabled, the Lua script crashes with this?

```
[osdlock]
[osdlock] stack traceback:
[osdlock]       mp.defaults:225: in function 'fn'
[osdlock]       mp.defaults:60: in function 'handler'
[osdlock]       mp.defaults:365: in function 'handler'
[osdlock]       mp.defaults:486: in function 'call_event_handlers'
[osdlock]       mp.defaults:520: in function 'dispatch_events'
[osdlock]       mp.defaults:479: in function <mp.defaults:478>
[osdlock]       [C]: in ?
[osdlock]       [C]: in ?
[osdlock] Lua error: mp.defaults:225: attempt to call upvalue 'fn' (a boolean value)
```

What am I doing wrong here? Is there another approach to this? Maybe I could somehow reload or restart the script so that it reloads the default keybinds from the user's `input.conf` and mpv's default input configurations.

**Comment by SeppNel** [comment]
Don't know if you still care, but I had the same problem because of my cats, so I fixed and expanded your script.

````
local mp = require 'mp'

local toggled = true
local osd_time = 2

function osd_lock()
    if toggled then
        mp.add_forced_key_binding("right", nil)
        mp.add_forced_key_binding("left", nil)
        mp.add_forced_key_binding("up", nil)
        mp.add_forced_key_binding("down", nil)
        mp.add_forced_key_binding("p", nil)
        mp.add_forced_key_binding("SPACE", nil)
        mp.add_forced_key_binding("MBTN_RIGHT", nil)
        mp.add_forced_key_binding("PAUSE", nil)
        mp.add_forced_key_binding("MOUSE_MOVE", nil)
        mp.add_forced_key_binding("s", nil)
        mp.add_forced_key_binding("d", nil)
        mp.add_forced_key_binding("w", nil)
        mp.add_forced_key_binding("e", nil)
        mp.add_forced_key_binding("z", nil)
        mp.add_forced_key_binding("x", nil)
        mp.add_forced_key_binding("m", nil)
        mp.add_forced_key_binding("q", nil)
        mp.add_forced_key_binding("ESC", nil)
        mp.add_forced_key_binding("1", nil)
        mp.add_forced_key_binding("2", nil)
        mp.add_forced_key_binding("3", nil)
        mp.add_forced_key_binding("4", nil)
        mp.add_forced_key_binding("5", nil)
        mp.add_forced_key_binding("6", nil)
        mp.add_forced_key_binding("7", nil)
        mp.add_forced_key_binding("8", nil)
        mp.add_forced_key_binding("9", nil)
        mp.add_forced_key_binding("0", nil)
        mp.add_forced_key_binding("i", nil)
        mp.add_forced_key_binding("o", nil)
        mp.add_forced_key_binding("v", nil)
        mp.add_forced_key_binding("f", nil)
        mp.add_forced_key_binding("r", nil)
        mp.add_forced_key_binding("t", nil)
        mp.add_forced_key_binding("l", nil)
        mp.add_forced_key_binding("j", nil)
        mp.add_forced_key_binding("u", nil)
        mp.add_forced_key_binding(",", nil)
        mp.add_forced_key_binding(".", nil)
        mp.add_forced_key_binding("`", nil)
        mp.add_forced_key_binding("DEL", nil)
        mp.add_forced_key_binding("PGUP", nil)
        mp.add_forced_key_binding("PGDWN", nil)
        mp.osd_message("Locked", osd_time)
    else
        mp.add_forced_key_binding("left", nil, function() mp.command("seek -5") end)
        mp.add_forced_key_binding("right", nil, function() mp.command("seek 5") end)
        mp.add_forced_key_binding("up", nil, function() mp.command("seek 60") end)
        mp.add_forced_key_binding("down", nil, function() mp.command("seek -60") end)
        mp.add_forced_key_binding("p", nil, function() mp.command("cycle pause") end)
        mp.add_forced_key_binding("SPACE", nil, function() mp.command("cycle pause") end)
        mp.add_forced_key_binding("MBTN_RIGHT", nil, function() mp.command("cycle pause") end)
        mp.add_forced_key_binding("PAUSE", nil, function() mp.command("cycle pause") end)
        mp.add_forced_key_binding("MOUSE_MOVE", nil, function() mp.command("script-binding osc/__keybinding1 ") end)
        mp.add_forced_key_binding("s", nil, function() mp.command("screenshot") end)
        mp.add_forced_key_binding("d", nil, function() mp.command("cycle deinterlace") end)
        mp.add_forced_key_binding("w", nil, function() mp.command("add panscan -0.1") end)
        mp.add_forced_key_binding("e", nil, function() mp.command("add panscan +0.1") end)
        mp.add_forced_key_binding("z", nil, function() mp.command("add sub delay -0.1") end)
        mp.add_forced_key_binding("x", nil, function() mp.command("add sub delay +0.1") end)
        mp.add_forced_key_binding("m", nil, function() mp.command("cycle mute") end)
        mp.add_forced_key_binding("q", nil, function() mp.command("quit") end)
        mp.add_forced_key_binding("ESC", nil, function() mp.command("set fullscreen no") end)
        mp.add_forced_key_binding("1", nil, function() mp.command("add contrast -1") end)
        mp.add_forced_key_binding("2", nil, function() mp.command("add contrast 1") end)
        mp.add_forced_key_binding("3", nil, function() mp.command("add brightness -1") end)
        mp.add_forced_key_binding("4", nil, function() mp.command("add brightness 1") end)
        mp.add_forced_key_binding("5", nil, function() mp.command("add gamma -1") end)
        mp.add_forced_key_binding("6", nil, function() mp.command("add gamma 1") end)
        mp.add_forced_key_binding("7", nil, function() mp.command("add saturation -1") end)
        mp.add_forced_key_binding("8", nil, function() mp.command("add saturation 1") end)
        mp.add_forced_key_binding("9", nil, function() mp.command("add volume -2") end)
        mp.add_forced_key_binding("0", nil, function() mp.command("add volume 2") end)
        mp.add_forced_key_binding("i", nil, function() mp.command("script-binding stats/display-stats") end)
        mp.add_forced_key_binding("o", nil, function() mp.command("show progress") end)
        mp.add_forced_key_binding("v", nil, function() mp.command("cycle sub-visibility") end)
        mp.add_forced_key_binding("f", nil, function() mp.command("cycle fullscreen") end)
        mp.add_forced_key_binding("r", nil, function() mp.command("add sub-pos -1") end)
        mp.add_forced_key_binding("t", nil, function() mp.command("add sub-pos 1") end)
        mp.add_forced_key_binding("l", nil, function() mp.command("ab-loop") end)
        mp.add_forced_key_binding("j", nil, function() mp.command("cycle sub") end)
        mp.add_forced_key_binding("u", nil, function() mp.command("cycle-values sub-ass-override \"force\" \"no\" ") end)
        mp.add_forced_key_binding(",", nil, function() mp.command("frame-back-step") end)
        mp.add_forced_key_binding(".", nil, function() mp.command("frame-step") end)
        mp.add_forced_key_binding("`", nil, function() mp.command("script-binding console/enable") end)
        mp.add_forced_key_binding("DEL", nil, function() mp.command("script-binding osc/visibility") end)
        mp.add_forced_key_binding("PGUP", nil, function() mp.command("add chapter 1") end)
        mp.add_forced_key_binding("PGDWN", nil, function() mp.command("add chapter -1") end)
        mp.osd_message("Unlocked", osd_time)
    end
    toggled = not toggled
end

mp.add_key_binding("ctrl+l", osd_lock)
````

Hope this helps

**Comment by mrjpaxton** [comment]
@SeppNel - Yeah, I still care! I just need to remember to check this issue. Very good attempt, but I see that @guidocella has the code much cleaner and less redundant, so that's great. I'm glad you know your way around this Lua stuff.

However, I really want the indicator. It appears there's a couple ways of doing this. The "Locked" indicator can display for a few seconds, and disappear, along with "Unlocked" getting shown, or another way is to use the `osd-overlay` to permanently display "Locked". I tried to use a lock text icon (Emoji), but it would not work, so I gave up on that. It might be possible to use a vector lock image like VLC on Android, not sure how. Here's the code again so far:

```
local locked = false

--local ov = mp.create_osd_overlay('ass-events')
--ov.data = [[{\a7\fs32}]] .. "Locked"

mp.add_key_binding('Ctrl+l', 'inhibit-input', function ()
    if locked then
        for _, binding in pairs(mp.get_property_native('input-bindings')) do
            mp.remove_key_binding(binding.key)
        end
        --ov:remove()
        mp.osd_message("Unlocked", 5)
    else
        for _, binding in pairs(mp.get_property_native('input-bindings')) do
            if binding.owner ~= mp.get_script_name() then
                mp.add_forced_key_binding(binding.key, binding.key, nil)
            end
        end
        --ov:update()
        mp.osd_message("Locked", 5)
    end

    locked = not locked
end)
```

For the permanent message, uncomment (remove the "--") on all the lines, and comment out the `mp.osd_message()` lines. Otherwise, it can be left as is.
