### ISSUE TITLE
How to launch mpv with the stats overlay enabled?

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#10937]
https://mpv.io/manual/stable/#stats

I typically monitor the stats when benchmarking — when writing a log file `--log-file=`, the keypresses (i and I) presumably appear in the log, and drawing the overlay / reading the key events may have some initial performance impact. It would be optimal to start with the stats overlay on, when needed, by using a command-line flag.

**Comment by stax76** [comment]
To my knowledge, it cannot be done from the command line, it would involve writing a script that sends an input command.

**Comment by edmundlaugasson** [comment]
Actually I'm looking the same command-line parameter, what to write into `~/.config/mpv/script-opts/stats.conf`. Checked also documentation https://mpv.io/manual/master/#stats but there is only shortcut key SHIFT+I to show permanently. Only stats showing duration for temporary showing is possible for now to configure while I is pressed.
I could turn on OSC permanently via `~/.config/mpv/script-opts/osc.conf` with `visibility=always` - similarly could also stats be always visible. Tried that OSC parameter - didn't work with stats.

**Comment by mexicancartel** [comment]
Stumbled upon this issue today. It makes sense to enable stats for audio files by default since there is nothing on screen while its playing fullscreen

**Comment by guidocella** [comment]
On master you can use `--input-commands='script-message display-stats-toggle'`.

**Comment by mexicancartel** [comment]
Can I use it in mpv.conf or input.conf?

**Comment by Danny3** [comment]
I've put it like this in mpv.conf:
```
# Show statistics
input-commands=         'script-message display-stats-toggle'
```
And I can confirm that it works, the statics are shown immediately as MPV opens.
Now I can continue  my tries to find why it drops frames more easily.
