### ISSUE TITLE
How do I tune ewa_lanczos to look like haasnsoft on gpu-next?

### ISSUE THREAD

**Issue by Uranite** [mpv-player/mpv#10932]
Hello, I want to use haasnsoft but it's removed on gpu-next because it is replicated by tuning ewa_lanczos, so how do I tune ewa_lanczos to look like haasnsoft on vo=gpu-next?

**Comment by hooke007** [comment]
Try this
```
 scale      = ewa_hanning
 scale-blur = 1.11
```

**Comment by erickyun** [comment]
> Try this
> 
> ```
>  scale      = ewa_hanning
>  scale-blur = 1.11
> ```

Hi, I was wondering the same thing. Do we also need to change scale-radius= to get haasnsoft on gpu-next?

**Comment by erickyun** [comment]
> No. "haasnsoft" uses the true jinc radius, and all of the named filters were updated to use the true jinc radius in [12a4f2d](https://github.com/mpv-player/mpv/commit/12a4f2d51eec1168cc03dcedc5283d7d087e3fc3).

Thank you for your response. 🙂

**Comment by rainlycoris** [comment]
To say something beside the point, This [note](https://github.com/mpv-player/mpv/blob/12a4f2d51eec1168cc03dcedc5283d7d087e3fc3/video/out/filter_kernels.c) said
> Blur parameter picked to match orthogonal and diagonal contributions

What does that mean?

**Comment by rainlycoris** [comment]
Yes, I just want to know what is orthogonal and diagonal contributions and how get this value.
