### ISSUE TITLE
Question about font selection

### ISSUE THREAD

**Issue by EmperorPenguin18** [mpv-player/mpv#10947]
One video file I have gives the output:
```
[sub/ass] [0xaaaafe9f7390]: Warning: no style named 'Furigana' found, using 'Default'
```
and then proceeds to play fine and the subtitles look great.

I looked up Furigana and it seems to be some sort of educational thing? I'm not really sure. My question is, is there a way to fix this warning, and potentially get an experience with this file closer to what the creator intended?

**Comment by zhongfly** [comment]
The subtitle of video has problem, ask video marker for help.

**Comment by zhongfly** [comment]
This is not the problem of mpv, and not related to mpv

**Comment by EmperorPenguin18** [comment]
Okay thanks
