### ISSUE TITLE
Generate GitHub Actions artifacts for Linux and macOS

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#10945]
I see that there are build scripts for Windows, Linux and macOS on the Actions page, however generated artifacts are only for Windows. It would be nice to have artifacts for Linux and macOS as well

### Expected behavior of the wanted feature
Available GitHub Actions artifacts for Linux and macOS

### Alternative behavior of the wanted feature
Compile mpv manually

**Comment by kasper93** [comment]
Windows and macOS artifacts are available. https://nightly.link/mpv-player/mpv/workflows/build/master

Linux artifact won't ever happen, because portable linux binaries are not something that makes sense anyway.
