### ISSUE TITLE
mpv won't open or play any GIF files

### ISSUE THREAD

**Issue by ice051128** [mpv-player/mpv#10949]
### Important Information
- mpv version: 0.35.0
- Windows Version: Windows 10
- Source of the mpv binary: Official
- If known which version of mpv introduced the problem: No
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps: 
Double click as usual on any GIF files.

### Expected behavior
Play the GIF file.

### Actual behavior
mpv won't open and play the GIF file even tho it's registered on Windows 10 as the default app for videos. Even though I have set it to open GIF with mpv, it doesn't launch at all.

**Comment by CounterPillow** [comment]
> Source of the mpv binary: Official

mpv doesn't provide official binaries.

Also, where log file?
