### ISSUE TITLE
pausing MPV player for mere 5 seconds then continue playing the video results in dropped frames

### ISSUE THREAD

**Issue by YousefSaber** [mpv-player/mpv#10954]
played a 30FPS 1080p video locally on my computer and pausing for mere 5 seconds led to 49 frames drops 

This is the [log file](https://drive.google.com/file/d/1EetWrtQ0hFH4xV9pB-VmnylifVv39Uwn/view?usp=share_link)

can't reproduce the issue on windows machine.

**Comment by YousefSaber** [comment]
can't reproduce the problem on my Windows machine.

**Comment by Dudemanguy** [comment]
Is there something particular about whatever file you're playing? This log looks incredibly busy.

**Comment by Dudemanguy** [comment]
Will assume this is the same as #12057 (OP also uses pulseaudio) which is a much better issue so closing this one.
