### ISSUE TITLE
Accelerated H264 on Wayland on the Raspberry Pi 4 with hwcodec=v4l2m2m, possible?

### ISSUE THREAD

**Issue by vanfanel** [mpv-player/mpv#10956]
### Important Information

Provide following Information:

Raspberry Pi OS aarch64 (Debian 11 aarch64)
mpv: Built from latest GIT sources: 77e7f5de2c01361a88c501fcd78b51c2fe2d9df0
FFmpeg: always latest GIT code from rpi-ffmpeg fork: https://github.com/jc-kynesim/rpi-ffmpeg
Window Manager: Sway 1.8rc-1 (WLRoots based)
GPU driver: MESA vc4 (Raspberry Pi 4). Latest stable MESA version 22.2.2

### Reproduction steps

mpv with this `~/.config/mpv/mpv.conf` configuration can play videos with a VERY low CPU usage (~10%) but shows a blue screen (almost there!! Why does this fail to display frames??):

```
vo=gpu
hwdec=v4l2m2m
```

The cause for this behavior seems to be this message on the command console:
```
[   0.513][f][vo/gpu/drmprime] unsupported DRM image format yuv420p
[   0.513][e][vo/gpu] Initializing texture for hardware decoding failed.
```

Using `hwdec=v4l2m2m-copy` instead, video plays but CPU usage is high (~80%) and there are a lot of frame drops.

### Expected behavior

Accelerated H264 video using `hwcodec=v4l2m2m` should play in a Wayland context.

### Actual behavior

Accelerated H264 video using `hwcodec=v4l2m2m` in a Wayland context only shows a blue screen.
Resorting to `hwcodec=v4l2m2m` video plays, but is way too slow because of CPU usage.

### Log files
[log.txt](https://github.com/mpv-player/mpv/files/10144448/log.txt)

So the question is: Is  `hwcodec=v4l2m2m` supposed to work on the Pi4 on Wayland?
If not, why? If yes, how?

Thanks!

**Comment by vanfanel** [comment]
It seems to be possible to use `hwcodec=v4l2m2m` if mpv is built with Vulkan support and I use this config:

```
vo=gpu
gpu-api=vulkan
fs=yes
hwdec=v4l2m2m
```

..but CPU usage is very high (~100%) and there are continuously dropped frames.

**Comment by EmperorPenguin18** [comment]
I've seen this behaviour as well plus I have been trying HEVC #10773. I haven't tried with Vulkan but I'll give it a shot tonight. What version of ffmpeg are you using? You don't mention in your original comment.

**Comment by vanfanel** [comment]
> 

I always use latest GIT code.

**Comment by EmperorPenguin18** [comment]
Could you provide compilation instructions? I wasn't able to figure it out. Up to now I've been using [this](https://archlinuxarm.org/packages/aarch64/ffmpeg-rpi) instead.

I tried `gpu-api=vulkan` and I got the same behaviour. I think it is due to mpv falling back to the wlshm video output which is in software.

**Comment by vanfanel** [comment]
> Could you provide compilation instructions? I wasn't able to figure it out. Up to now I've been using [this](https://archlinuxarm.org/packages/aarch64/ffmpeg-rpi) instead.
> 
> I tried `gpu-api=vulkan` and I got the same behaviour. I think it is due to mpv falling back to the wlshm video output which is in software.

Of course. These are for Raspberry Pi OS aarch64:

-Install dependencies:
`sudo apt-get install libv4l-dev --no-install-recommends`

-Clone the right branch on the repo:
`git clone --depth 1 https://github.com/jc-kynesim/rpi-ffmpeg.git -b test/4.3.5/rpi_main`

-Configure the sources with:
```
CFLAGS="-march=native -mtune=native" \
CXXFLAGS="-march=native -mtune=native" \
./configure --disable-network --disable-debug --disable-muxers --disable-indevs \
--disable-outdev=fbdev --disable-outdev=oss --disable-doc --disable-bsfs --disable-ffprobe --disable-sdl2 \
--disable-stripping \
--disable-thumb \
--disable-mmal \
--enable-sand \
--enable-v4l2-request \
--enable-libdrm \
--enable-epoxy \
--enable-libudev \
--enable-vout-drm
```

**Comment by EmperorPenguin18** [comment]
Building ffmpeg worked but when building mpv against it I get this:
```
Dependency libavcodec found: NO found 58.91.100 but need: '>= 58.134.100'
```

**Comment by EmperorPenguin18** [comment]
Good news I got further than the blue screen

Bad news the colours are all messed up

Give me some time I should be able to figure it out

**Comment by vanfanel** [comment]
@EmperorPenguin18 



Please, what branch of rpi-ffmpeg should I use? I was using https://github.com/jc-kynesim/rpi-ffmpeg/tree/test/4.3.5/rpi_main, but it seems that MPV can't build against it:
meson.build:19:0: ERROR: Invalid version of dependency, need 'libavcodec' ['>= 58.134.100'] found '58.91.100'.

**Comment by vanfanel** [comment]
@EmperorPenguin18 

I tried https://github.com/jc-kynesim/rpi-ffmpeg/tree/dev/5.1.2/rpi_import_1, which is the only that made sense to me above 4.3.5, and I get no video on MPV with the default configuration.

If you get it to work after building ffmpeg from sources (not in a hurry!) can you please post instructions, too? You're my only hope with this. Video playblack on the Pi seems to be a mess right now...

**Comment by EmperorPenguin18** [comment]
You can use the same ffmpeg as me on Debian with these instructions
```
cd ~
wget http://mirror.archlinuxarm.org/aarch64/alarm/ffmpeg-rpi-4.4.2-3-aarch64.pkg.tar.xz
tar -xvf ffmpeg-rpi-4.4.2-3-aarch64.pkg.tar.xz
cd $MPV_BUILD_DIRECTORY
PKG_CONFIG_PATH=~/usr/lib/ffmpeg-rpi/pkgconfig/ meson build && ninja -C build
```

When I tried those steps myself I got this error:
```
meson.build:1224:4: ERROR: Problem encountered: gl enabled but no OpenGL video output could be found!
```
but I assume you know how do compile mpv correctly on Raspberry Pi OS so hopefully these instructions help you.

**Comment by vanfanel** [comment]
@EmperorPenguin18 Thanks!! Will try those steps ASAP!!
Will that ffmpeg + current mpv suffice to get accelerated video on Wayland? As in, smooth H264 1080p playback on Wayland. Or is there another missing piece?

**Comment by EmperorPenguin18** [comment]
That's what did it for me on Manjaro, so unless the stack differs in some significant way (mesa maybe?) then it should work. I could already get smooth H264 playback with software decoding with the binary shipped by Manjaro, but this is a stepping stone to me figuring out how to get HEVC working as well.

**Comment by vanfanel** [comment]
The problem here is that I am not willing to install a binary package for ffmpeg, and that's not a solution after all. I hadn't noticed that the instructions use a binary package...
I would need to build a working version of ffmpeg from sources. Did you find a version/branch that does the job?
My understanding is that, since there's no 4.4.2-3 branch on https://github.com/jc-kynesim/rpi-ffmpeg/branches, the archlinux package is upstream ffmpeg...

**Comment by EmperorPenguin18** [comment]
Got it working building from source on the 5.1.2 branch on Raspberry Pi OS. Also yes the Arch package sort of uses upstream but also adds in a giant patch from jc-kynesim's fork.

> @EmperorPenguin18
> 
> I tried https://github.com/jc-kynesim/rpi-ffmpeg/tree/dev/5.1.2/rpi_import_1, which is the only that made sense to me above 4.3.5, and I get no video on MPV with the default configuration.
> 
> If you get it to work after building ffmpeg from sources (not in a hurry!) can you please post instructions, too? You're my only hope with this. Video playblack on the Pi seems to be a mess right now...

Could you give a little more detail on this problem? My guess is you're missing some optional build dependencies.

**Comment by vanfanel** [comment]
@EmperorPenguin18 This is how I am building https://github.com/jc-kynesim/rpi-ffmpeg/tree/dev/5.1.2/rpi_import_1:
```

./configure --disable-network --disable-debug --disable-muxers --disable-indevs \
--disable-outdev=fbdev --disable-outdev=oss --disable-doc --disable-bsfs --disable-ffprobe --disable-sdl2 \
--disable-stripping \
--disable-thumb \
--disable-mmal \
--enable-sand \
--enable-v4l2-request \
--enable-libdrm \
--enable-epoxy \
--enable-libudev \
--enable-vout-drm
```

What are you configure options for building this branch of rpi-ffmpeg?

And also, what are you configure options for building MPV?

If I replicate your configure options, and given we have the same MESA version, we should have the same results :)

**Comment by EmperorPenguin18** [comment]
My ffmpeg configure command:
```
CFLAGS="-march=native -mtune=native" CXXFLAGS="-march=native -mtune=native" ./configure --prefix=/usr/lib/rpi-ffmpeg --disable-network --disable-debug --disable-muxers --disable-indevs --disable-outdev=fbdev --disable-outdev=oss --disable-doc --disable-bsfs --disable-ffprobe --disable-sdl2 --disable-stripping --disable-thumb --disable-mmal --enable-sand --enable-v4l2-request --enable-libdrm --enable-epoxy --enable-libudev --enable-vout-drm
```
And this was the end of the meson output:
```
Message: List of enabled features: alsa av-channel-layout build-date cplayer cplugins debug dmabuf-interop-gl dmabuf-wayland drm egl egl-drm egl-helpers ffmpeg gbm gl gl-wayland glibc-thread-name glob glob-posix gpl iconv javascript jpeg jpegxl lcms2 libarchive libass libavdevice libbluray libdl libm librt linux-fstatfs luajit memfd_create noexecstack pipewire posix rubberband sixel stdatomic threads vaapi vaapi-drm vaapi-egl vaapi-wayland vector vt.h wayland zlib
Build targets in project: 33

mpv 0.35.0-UNKNOWN

    d3d11     : NO
    gpu-next  : NO
    javascript: YES
    libmpv    : NO
    lua       : YES
    opengl    : YES
    vulkan    : NO
    wayland   : YES
    x11       : NO
```

The mpv command I do is `./mpv --no-config --hwdec=auto Tears_400_x264.mp4` but swap out the filename for whatever. Your flags instead of calling it 'hwdec: v4l2m2m' do something I've never seen mpv do and say 'V4L2 mem2mem H.264 decoder wrapper'. I think that's where your problem is because my flags get ~10% cpu usage and yours are more like ~20% for me.

**Comment by vanfanel** [comment]
@EmperorPenguin18 Ah! Those exact rpi-ffmpeg build flags did the job! Now I get ~10% CPU usage on decoding 1080p H264 content! How awesome, this is almost omxplayer level of performance!
I also use these on the mpv config file:
```
hwdec=auto
vo=gpu
```

Do you happen to know how video smoothness in PAL content (~25/50 FPS) on a 60Hz display can be improved?
I have been experimenting with --video-sync options to no avail, and I see no differente.
Ideal solution would be telling MPV to set a multiple refresh rate: omxplayer could do that, and in fact Kodi can do it, too. But I don't know if MPV is able of that in Wayland....

**Comment by EmperorPenguin18** [comment]
I don't know why that would be. I used to have screen tearing but Wayland fixed that for me. If you think it is an mpv issue you could open a separate thread on GitHub. For now if the main issue of this thread is resolved for you then lets leave it, we've already been commenting on a closed issue for a few days now. I'm still gonna keep working on mpv and the pi but will track my progress with the HEVC thread so use that one from now on.

**Comment by vanfanel** [comment]
@EmperorPenguin18 You are right, sir. You have helped me a lot! Thanks, really, things look fantastic around here with MPV on Wayland and that's thanks to your in-depth study of the problem!
