### ISSUE TITLE
How do I tune ewa_lanczos to look like ewa_lanczossoft on gpu-next?

### ISSUE THREAD

**Issue by Xathros1** [mpv-player/mpv#10955]
Hello, I want to use ewa_lanczossoft but it's removed on gpu-next because it is replicated by tuning ewa_lanczos, so how do I tune ewa_lanczos to look like ewa_lanczossoft on vo=gpu-next?

**Comment by hooke007** [comment]
```
 scale      = ewa_lanczos
 scale-blur = 1.015
```

**Comment by Xathros1** [comment]
thanks!
