### ISSUE TITLE
I wonder if there are other options for "reset-on-next-file"

### ISSUE THREAD

**Issue by carman11** [mpv-player/mpv#10966]
When I drag a file to the mpv with the mouse, the playback will continue the Settings of the previous file, such as ab-loop.I hope I can cancel ab-loop when playing the next file, but reset-on-next-file=ab-loop doesn't seem to work, so is there any way to solve it?

I wonder if there are other options for "reset-on-next-file"

**Comment by guidocella** [comment]
`reset-on-next-file=ab-loop-a,ab-loop-b`

**Comment by carman11** [comment]
> `reset-on-next-file=ab-loop-a,ab-loop-b`

Thanks, :)
