### ISSUE TITLE
mpv secondary-sid blocks sub selection cycle in osc

### ISSUE THREAD

**Issue by lxhg** [mpv-player/mpv#10968]
### Important Information
- mpv version:
```
$ mpv --version
mpv 0.35.0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.2

```
- Linux Distribution and Version:
  Debian testing
- Source of the mpv binary
  deb https://www.deb-multimedia.org bookworm main non-free
- Window Manager and version
```
$ kwin --version
kwin 5.26.3
```
- GPU driver and version
nvidia blob 510.85.02

### Reproduction steps
mpv Starship_Troopers.mpeg --no-config --sid=1 --secondary-sid=2

### Expected behavior
When you click subs icon it should cycle through availible subs

### Actual behavior
On sub switch when next sub id is used by secondary-sid it displays error in terminal:
"Track 2 is already selected."
And you are unable to cycle to the next sub stream in that direction.

### Log file
https://0x0.st/okIl.txt

### Sample files
https://samples.ffmpeg.org/sub/subcc/ClosedCaptions/Starship_Troopers.vob

---
I should note that cycle with j/J works fine - it just skips over subs that used as secondary. So I made some modifications to osc to add button for secondary subs and made it use mp.commandv('cycle') to switch both subs. Here is diff against master https://0x0.st/oklS.diff

**Comment by guidocella** [comment]
Fixed by 1a558bf5c2.
