### ISSUE TITLE
--d3d11va-zero-copy=yes with hdr10, the video causes a green stripe of 1 pixel at the bottom of the screen

### ISSUE THREAD

**Issue by AdventurerRussia** [mpv-player/mpv#10963]
I noticed that when watching an HDR 10 video, a green stripe appears at the bottom of the screen, I found out by brute force that the --d3d11va-zero-copy and --hwdec=d3d11va parameter causes this if they are used together
-
I checked on a clean build only with these keys

--d3d11va-zero-copy=yes
--tone-mapping=bt.2446a
--vo=gpu-next
--hwdec=d3d11va
--log-file=~~global/mpv.log

last build. https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/
log https://fex.net/ru/s/at7aee3

Имя устройства	DESKTOP-884EQSO
Процессор	AMD Ryzen 3 5300U with Radeon Graphics            2.60 GHz
Оперативная память	8,00 ГБ (доступно: 7,33 ГБ)
Код устройства	6CE0BADE-A012-4D65-9B92-02BE6C3DC232
Код продукта	00330-80000-00000-AA269
Тип системы	64-разрядная операционная система, процессор x64
Перо и сенсорный ввод	Для этого монитора недоступен ввод с помощью пера и сенсорный ввод

Выпуск	Windows 11 Pro
Версия	22H2
Дата установки	‎22.‎10.‎2022
Сборка ОС	22621.900
Взаимодействие	Windows Feature Experience Pack 1000.22638.1000.0

![image](https://user-images.githubusercontent.com/14019010/205481460-0b01ee0b-20de-4cc4-8cbe-5ab1b14f0e43.png)
![image](https://user-images.githubusercontent.com/14019010/205481464-024d27c4-fadc-4476-a233-a4c4c7e1c51d.png)
![image](https://user-images.githubusercontent.com/14019010/205481470-35fe72eb-eb51-4ec7-b1a5-f66b12ec361d.png)

**Comment by dexeonify** [comment]
Well yeah, it's mentioned in the [manual](https://mpv.io/manual/master/#options-d3d11va-zero-copy).
> This may increase performance and reduce power usage, but can cause the image to be sampled incorrectly on the bottom and right edges due to padding (...)
