### ISSUE TITLE
Pipewire: mpv not shown in pavucontrol when using some audio filters

### ISSUE THREAD

**Issue by sleeksorrow** [mpv-player/mpv#10960]
### Important Information

- mpv version: 0.35
- Linux Distribution and Version: Kubuntu 22.10
- Source of the mpv binary: Built with mpv-build
- If known which version of mpv introduced the problem: 0.35
- Window Manager and version: KDE Plasma 5.26.4
- GPU driver and version: Nvidia 525.60.11
- pipewire version: 0.3.58

### Reproduction steps

When using some audio filters together with ao=pipewire, mpv does not show up in client list of pavucontrol. Specifically I identified "volnorm" and "dynaudnorm" to be affected at least.

Works: `mpv --no-config /usr/share/sounds/Oxygen-Sys-App-Error.ogg`
Works: `mpv --no-config --af=earwax /usr/share/sounds/Oxygen-Sys-App-Error.ogg`
Fails: `mpv --no-config --af=dynaudnorm /usr/share/sounds/Oxygen-Sys-App-Error.ogg`
Fails: `mpv --no-config --af=volnorm /usr/share/sounds/Oxygen-Sys-App-Error.ogg`

Additional info: When pavucontrol fails to show the playing mpv process, it's still shown with `pactl list clients short`

### Expected behavior

mpv should always be shown in pavucontrol when playing audio through pipewire

### Actual behavior

mpv does not show up in pavucontrol when using audio filter "volnorm" or "dynaudnorm".

### Log file

[verbose.log](https://github.com/mpv-player/mpv/files/10147296/verbose.log)

### Sample files

none, every file with audio works for reproduction for me.

**Comment by CounterPillow** [comment]
Why would this be an mpv issue rather than a pavucontrol issue if it's shown in `pactl`?

**Comment by sleeksorrow** [comment]
I described this behavior to experts to answer exactly this question. Behavior change through changing command line options might be a clue, isn't it?

**Comment by CounterPillow** [comment]
> Behavior change through changing command line options might be a clue, isn't it?

Consider that adding filters might change output parameters (sample rate, etc.) which then might cause a bug in the other application. Unless it's somehow shown that mpv implements the pipewire protocol incorrectly, I wouldn't assume this to be an mpv bug.

**Comment by monarc99** [comment]
Same problem here. pavucontrol is part of pulseaudio?

if i use ao=pipewire:  mpv choose doublep as audio format. mpv plays the sound, but i cannot see it in the kde mixer. 
if i use ao=pulse:  mpv choose floatp. Everything is fine.

if i force the audio format with --audio-format=floatp, i can see mpv in the mixer on both - pulse and pipewire.

is doublep not supported in pulseaudio and related mixers (kde) ?
Added audio-format=floatp to mpv.conf as workaround for me.

**Comment by sleeksorrow** [comment]
>is doublep not supported in pulseaudio and related mixers (kde) ?

Nice catch. I can confirm that KDE Plasma Volume Mixer is also affected on my machine.

**Comment by Nokodoko** [comment]
Also confirming that mpv does not populate with pavucontrol/pulseaudio.'

**Comment by t-8ch** [comment]
I think the problem is that pulseaudio does not know about 64bit double samples.
So pipewire does not report the sinks via the pulse protocol as it would have no way to represent the sampleformat.

The correct test via pactl is: `pactl list sink-inputs`.

Anyways, this is not really an issue of mpv.

**Comment by t-8ch** [comment]
This MR for pipewire should fix it: https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1499/
(Or some better replacement that comes of it)
