### ISSUE TITLE
https://giveupgithub.org

### ISSUE THREAD

**Issue by rihaq** [mpv-player/mpv#10977]
I think code.videolan.org is best alternative. About @sfan5  accusing gitlab for having too much js, fyi github uses non-free js. I know gitlab isn't best but its user-friendly. Other alternative like cgit,sr.ht,codeberg.
I hate the hypocrisy of mpv of using ancient stone-age irc instead of matrix/discord/telegram, yet its still on m$ owned proprietary non-free js "github"

**Comment by CounterPillow** [comment]
nice meme
