### ISSUE TITLE
[Gnome wayland] missing direct scanout for vo=gpu[-next]

### ISSUE THREAD

**Issue by Mershl** [mpv-player/mpv#10971]
### Important Information

- mpv version: 0.35.0
- Linux Distribution and Version; Fedora 37
- Source of the mpv binary: Flathub
- Window Manager and version: Gnome/mutter 43.1 Wayland session
- GPU driver and version: mesa 22.2.3 + mesa 22.1.7

### Reproduction steps

On Gnome 43.1 Wayland session (important as 43.1 fixed missing direct scanout in general on AMDGPUs):
1. open looking glass (ALT+F2 -> `lg`)
2. switch to tab FLAGS
3. enable the debug flag `PAINT_DAMAGE_REGION` (under ClutterDrawDebugFlags)
4. run `mpv --no-config <some_media_file>`
5. switch to fullscreen mode (shortcut F)

### Expected behavior

4. while in windowed mode every frame update should show a red rectangle overlay indicating the compositor being active
5. while in fullscreen mode no damage region should be visible, the compositor is inactive and indicates using direct scanout

Note: direct scanout is used on the same system while using `vo=sdl`.

### Actual behavior

direct scanout is not used while in fullscreen mode with default settings or `vo=gpu-next`.

### System information (--no-config)

vo: gpu
ao: pipewire

**Comment by Dudemanguy** [comment]
We are certainly setting the entire wl_surface as opaque by default which, as far as I know, should be all we need to do. I can double check GNOME later, but I'm fairly certain sway/wlroots does direct scanout as usual for me.

**Comment by Dudemanguy** [comment]
Well I can confirm the behavior you described in GNOME. It's worth noting that forcing xwayland (e.g. `--gpu-context=x11egl`) appears to also use direct scanout. I don't think there's anything we can do though. mpv is marking the entire surface/region as opaque which should be good enough. Maybe open an issue upstream?

**Comment by Mershl** [comment]
opened https://gitlab.gnome.org/GNOME/mutter/-/issues/2550

**Comment by Dudemanguy** [comment]
Fixed upstream now.

**Comment by Mershl** [comment]
I can confirm it worked as expected now. The fix is included in Gnome 43.2-2 and 43.3 (to be released).
