### ISSUE TITLE
Ability to get histogram data.

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#10974]
### Expected behavior of the wanted feature

I'm using [custom shaders](https://github.com/Natural-Harmonia-Gropius/mpv_config/blob/main/portable_config/shaders/hdr-toys/tone-mapping/piecewise.glsl) for tone mapping.
https://github.com/mpv-player/mpv/pull/10827 gives the ability to change parameters at runtime.
I want to go further to get the exact luminance informations of frame to control the `shoulderStrength`.

This is the position I want it to work.

```ini
[hdr]
profile-cond=get("video-params/sig-peak") > 1
profile-restore=copy
target-trc=pq
target-prim=bt.2020
glsl-shader=~~/shaders/hdr-toys/utils/clip_both.glsl
glsl-shader=~~/shaders/hdr-toys/transfer-function/pq_to_l.glsl
glsl-shader=~~/shaders/hdr-toys/transfer-function/l_to_linear.glsl
glsl-shader=~~/shaders/hdr-toys/utils/exposure.glsl
glsl-shader=~~/shaders/hdr-toys/utils/crosstalk.glsl
glsl-shader=~~/shaders/hdr-toys/utils/chroma_correction_hsv.glsl
# get_histogram_data
glsl-shader=~~/shaders/hdr-toys/tone-mapping/piecewise.glsl    # use_histogram_data
glsl-shader=~~/shaders/hdr-toys/tone-mapping/heatmap.glsl
glsl-shader=~~/shaders/hdr-toys/utils/crosstalk_inverse.glsl
glsl-shader=~~/shaders/hdr-toys/gamut-mapping/bt2407_matrix.glsl
glsl-shader=~~/shaders/hdr-toys/transfer-function/linear_to_bt1886.glsl
```

**Comment by haasn** [comment]
At this point, why not just estimate the histogram in your own shader?

**Comment by Natural-Harmonia-Gropius** [comment]
How to do it? Not familiar with glsl ......

**Comment by haasn** [comment]
Err, no, that's completely not the way to do it. You need to use a compute shader, have each work group compute a local histogram then write that (using atomic integer addition) to a shader storage buffer shared between all work groups. (This also needs to be initialized to 0 by an earlier pass)

And then you can evaluate its result, preferably also in a separate sub-pass done only once, and generate your LUT which you can sample from a later pass.
