### ISSUE TITLE
Request a lua script

### ISSUE THREAD

**Issue by carman11** [mpv-player/mpv#10976]
Dear friends, I have a request for you to help me write a lua script
Requirements:
When the mpv plays flac, MP3, wav, dsf, and other audio files, the taskbar displays a music symbol, or any other symbol. Like this:
https://files.catbox.moe/x6w6vs.png
https://files.catbox.moe/fjm75g.png

When an mpv plays a video file such as MP4, flv, wmv, mkv, and avi, it is replaced with other symbols. Like this:
https://files.catbox.moe/myt1xc.png
https://files.catbox.moe/fpk71n.png

This is my current setup in mpv.conf
Title = ♬ ${media - the title}

**Comment by carman11** [comment]
Light weight:
https://files.catbox.moe/ywuu8p.png
https://files.catbox.moe/1gxxpn.png

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/wiki/FAQ#How_do_I_create_a_Conditional_auto_profile_that_applies_to_all_videos_or_all_audio

You can use these to set different titles.

**Comment by carman11** [comment]
> 

Thank. The rules is Too much for me
