### ISSUE TITLE
Mac: keybindings doesn't work when vo=gpu-next

### ISSUE THREAD

**Issue by eko5624** [mpv-player/mpv#10978]
### Important Information

Provide following Information:
- mpv version: https://github.com/eko5624/mpv-macos-intel/releases/tag/mpv-0.35.0-30-g4574dd5dc6
- macOS Version: 13.0.1 (22A400) macbookpro 13.3 2017 

### Reproduction steps
vo=gpu-next

### Expected behavior
keybindings should work.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/10182197/mpv.log)

**Comment by Akemi** [comment]
gpu-next isn't really supported on macOS and uses the old deprecated gpu cocoa backend.

```
[   0.138][w][vo/gpu-next] opengl cocoa backend is deprecated, use vo=libmpv instead
```
