### ISSUE TITLE
mpv will can add the checker in background for DNxHR (has alpha)?

### ISSUE THREAD

**Issue by manuelsongokuh** [mpv-player/mpv#10983]
hi

i tested file mov: codec qtrle has alpha, mpv show the background style checker , this is very important to know if there is alpha or not alpha..

so i have other file MOV:  codec DNxHR, has alpha , but background is color black.. so i wish that mpv will add feature make it in style checker..? is it possible for aff feature? or problem from ffmpeg?

**Comment by CounterPillow** [comment]
https://mpv.io/manual/master/#options-alpha

**Comment by manuelsongokuh** [comment]
i checked file mpv.conf
alpha=yes   not work tiles
alpha=blend-tiles  not works tiles
alpha=blend  not works tiles

what i will do..? ( i wish mpv make it tiles (checker) for DNxHR (include alpha)

**Comment by CounterPillow** [comment]
What you should be doing is ask ffmpeg to fix alpha for your format

**Comment by manuelsongokuh** [comment]
ah, that is issue to FFmpeg? ok
