### ISSUE TITLE
Debanding does not work when using gpu-next

### ISSUE THREAD

**Issue by NotMithical** [mpv-player/mpv#10981]
### Important Information

Provide following Information:
- mpv version: mpv 0.35.0-30-g4574dd5dc6
- Windows Version: 22H2, OS build 19045.2251
- Source of the mpv binary: Windows build from sourceforge
- If known which version of mpv introduced the problem: Only recently installed MPV, have not changed version
- Possible screenshot or video of visual glitches: Not sure what image hosting service to use, my usual one badly compressed the screenshots I have.

### Reproduction steps
Enable and configure debanding in config file with vo=gpu and then with vo=gpu-next

### Expected behavior
Low contrast gradients have debanding applied.

### Actual behavior
When switching from vo=gpu to vo=gpu-next, low contrast gradients no longer have debanding applied. Changing debanding iterations and range have no affect on performance.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/10190683/output.txt)

**Comment by CounterPillow** [comment]
Please make your logfile one of you actually trying to play back a file, so we can see it initialise the VO and whether it applies the options.

**Comment by NotMithical** [comment]
Sorry about that, here it is.
[output.txt](https://github.com/mpv-player/mpv/files/10190774/output.txt)

**Comment by NotMithical** [comment]
Update: Debanding wasn't working because I had gpu-dumb-mode=yes in the config file due to a misunderstanding on my part as to what this did. Everything now works as expected.
