### ISSUE TITLE
[Question] How to change OSC seekbar font size in slimbox layout?

### ISSUE THREAD

**Issue by sun95n** [mpv-player/mpv#10992]
Hi. I am in love with the slimbox design. But the font size when you mouse over the search bar is too small for my eyes. Is there a way to change it?

![01](https://user-images.githubusercontent.com/120290802/206956685-d48841b2-05d4-4cae-a90c-8cff05fd23a5.jpg)

**Comment by hooke007** [comment]
fontsize is hardcoded in the script.

**Comment by hooke007** [comment]
I don't think it would happen because of the design purposes. (Different elements use different fontsize)
https://github.com/mpv-player/mpv/blob/f9d0b0c08a35e67976a8c71ac16a832781c2313a/player/lua/osc.lua#L75-L93

**Comment by hooke007** [comment]
I thought you've read "how to use the script in mpv".
https://mpv.io/manual/master/#script-location
