### ISSUE TITLE
When the pointer moves to the bottom of the player, the OSC will be displayed.

### ISSUE THREAD

**Issue by carman11** [mpv-player/mpv#10993]
When the pointer moves to the bottom of the player, the OSC will be displayed.
How to achieve this?

**Comment by ma-zsola** [comment]
https://mpv.io/manual/master/#on-screen-controller-deadzonesize

You can set it in your mpv.conf file
`--script-opts=osc-deadzonesize=1`

**Comment by carman11** [comment]
> https://mpv.io/manual/master/#on-screen-controller-deadzonesize
> 
> You can set it in your mpv.conf file `--script-opts=osc-deadzonesize=1`

It doesn't seem to work. My idea is that osc displays when the pointer moves to the bottom of the mpv.

**Comment by dexeonify** [comment]
What doesn't work? The OSC still displays before your cursor touches the bottom of the screen? `deadzonesize=1` is already the best you can do - it will only show the OSC if you hover over it. Any more than that you might have to modify the osc script file.

**Comment by carman11** [comment]
> What doesn't work? The OSC still displays before your cursor touches the bottom of the screen? `deadzonesize=1` is already the best you can do - it will only show the OSC if you hover over it. Any more than that you might have to modify the osc script file.

It turns out that I filled in the content wrong, thank you
