### ISSUE TITLE
libmpv and directshow device

### ISSUE THREAD

**Issue by wbtcpip2** [mpv-player/mpv#10996]
i know how to open a directshow device with the loadfile command:

"av://dshow:video=Full HD 1080P PC Camera"

but how to pass further options like video size and framerate and a an audio source .... like in ffmpeg

ffplay -f dshow -video_size 1280x720 -framerate 30 -i video="XX":audio="YY"

thank you for helping me

**Comment by CounterPillow** [comment]
try setting the `demuxer-lavf-o` option with the ffmpeg options you use.
```
demuxer-lavf-o=video_size=1280x720,framerate=30
```

**Comment by wbtcpip2** [comment]
thank you

**Comment by wbtcpip2** [comment]
unfortunately do not work
mpv_set_property_string return "property not found" for "demuxer-lavf-o=video_size=1280x720,framerate=30"

**Comment by CounterPillow** [comment]
That's on you, the property is called demuxer-lavf-o, the things after the first = is the value you should set it to.

**Comment by wbtcpip2** [comment]
oh yes, it works now! thank you! libmpv it's really a nice library!
