### ISSUE TITLE
iHD VAAPI Failed to create mapper

### ISSUE THREAD

**Issue by wael444** [mpv-player/mpv#11005]
- mpv version: `9d0b0c`
- ffmpeg version: `5.1.2`
- KISS Linux
- Source of the mpv binary: KISS, self-compiled
- X11
- GPU driver and version: 
  - iHD: 22.5.4
  - mesa: 22.2.4

### Expected behavior
Video is decoded with my iGPU via VAAPI 

### Actual behavior
Segmentation fault

### Log file

https://0x0.st/onpw.txt

Currently, i want to use my Intel iGPU for video/VAAPI de/en-coding. my primary gpu is an NVIDIA (`520.60.11`) graphics card, and i am using it as my primary graphics card for X11 and Linux.

**Comment by CounterPillow** [comment]
> my primary gpu is an NVIDIA (520.60.11) graphics card, and i am using it as my primary graphics card for X11 and Linux.

you'll probably need to use `hwdec=vaapi-copy` then, I don't think you can import an Intel vaapi buffer into a dGPU without doing a copyback to system memory.

**Comment by wael444** [comment]
well, i do not see any usage of my intel igpu with `nvtop`, so i assume its just only using my nvidia gpu at that point.

**Comment by wael444** [comment]
so would that basically mean it's 'working'?

**Comment by CounterPillow** [comment]
If you show a log file I can answer that question better.

**Comment by philipl** [comment]
You can only use vaapi-copy indeed. The display and decode gpus must match for zero copy to work. So either live with that, and the higher CPU load, switch to nvdec on nvidia gpu, or switch your primary gpu to the Intel and use render offload for the nvidia.

**Comment by CounterPillow** [comment]
`[   0.050][i][vd] Using hardware decoding (vaapi-copy).`

Yep, it's working.

**Comment by wael444** [comment]
thank you1111111111!!!!!!!!!!!!!!!!!
