### ISSUE TITLE
libmpv win32 - handles leak and memory leak when using hwdec=d3d11va

### ISSUE THREAD

**Issue by wbtcpip2** [mpv-player/mpv#11003]
libmpv 0.35.0-33-gcf349d68e3 win32 32bits
(downloaded from https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-i686-20221211-git-cf349d6.7z/download )

nvidia gpu gtx750 (the same happens with another computer with gtx1650)

when setting hwdec=d3d11va there is a memory leak and handles leak every time an mpvhandle is destroyed

steps to reproduce the problem:

1) mpv_create
2) mpv_set_property_string(mpvhandle, "config", "no")
3) mpv_set_property_string(mpvhandle, "hwdec", "d3d11va")
4) mpv_initialize
5) mpv_set_property(mpvhandle, "wid", MPV_FORMAT_INT64, myform.hwnd)
6) mpv_command "loadfile", "anyh264videofile.mp4"
7) wait a while and destroy with mpv_destroy

repeat all the steps in a loop without exiting the main process and you'll see the handles number growth as well as memory usage

if you remove MPVSetPropertyString(mpvhandle, "hwdec", "d3d11va") no more leaks

the mpv logs do not show anything wrong

since I develop an application that needs to run without restarting I am unable to use hardware decoding.

moreover, since I have to play some videos on different forms at the same time, I have to continuously create and destroy mpvhandle

hope you can check and fix this leak.

thank you

**Comment by Dudemanguy** [comment]
Possibly fixed by this https://github.com/mpv-player/mpv/pull/9792? Looks harmless enough but if anyone could actually confirm that would be great.

**Comment by wbtcpip2** [comment]
#9792 fix has never be merged. why? it's an important fix

**Comment by avih** [comment]
Is this the same issue as https://github.com/shinchiro/mpv-winbuild-cmake/issues/301 ?

If yes, I presume these apply here too?

> you have a memory leak of 768 KB at every loop .... approx 768 MB after 1024 loop
> 
> the memory leak started on April 12, 2020 with this version: https://master.dl.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-i686-20200412-git-530a086.7z?viasf=1 mpv-version=mpv 0.32.0-352-g530a0863b8 ffmpeg-version=git-2020-04-12-f1894c206
> 
> the previous version has no memory leak: mpv-version=mpv 0.32.0-328-gc5f8ec76b1 ffmpeg-version=git-2020-04-05-8b1f07ef5

Is it fixed by https://github.com/mpv-player/mpv/commit/3447463008cc940a13d0787f8533503c3fbfbb58 ?

**Comment by wbtcpip2** [comment]
sorry for having created some confusion. there was 2 different problems.
one handle leak when using d3d11va hwdec and i hope this has been fixed (i have to test)

the second problem is a memory leak after mpv_destroy #9860 and https://github.com/shinchiro/mpv-winbuild-cmake/issues/301
i don't think is related with d3d11va because it occurs without playing anything just initialize and destroy libmpv

**Comment by Dudemanguy** [comment]
The d3d11va leak should be fixed so I'm closing this one. The other issue is still open and should be something else completely.
