### ISSUE TITLE
how to play sRGB video on rec709 calibrated screen?

### ISSUE THREAD

**Issue by p0las** [mpv-player/mpv#11001]
I have videos encoded using "output - sRGB" OCIO colour profile. On sRGB calibrated screen I get the correct gamma when using:

target-trc=bt.1886

but I expected it to be correct for "srgb" setting. This setting however crushes the blacks too much.

I think the problem is that MPV assumes the video is rec709so when I set the target to rec709 it gets no correction and looks correct. I see no option to set the source gamma. How can I tell MPV that my video has sRGB gamma? The end goal is to tell MPV that the video is sRGB and the target rec709.
thank you!

**Comment by haasn** [comment]
`--vf=format=gamma=srgb` can be used to override the source gamma.

But in reality, you should tag your files with correct metadata.

**Comment by p0las** [comment]
fair enough. I assumed that oiiotool, which we use, tags the media correctly but I will double check it. thank you. the above flag fixes my problem.
is there a way to use it in a config file?

**Comment by dexeonify** [comment]
Use `vf-append format=gamma=srgb` in your mpv.conf file. See https://mpv.io/manual/master/#video-filters.

**Comment by ZaquL** [comment]
>tags the media correctly but I will double check it. thank you. the above flag fixes my problem.

Why assume? Look into mediainfo report for transfer. It must say sRGB, not BT.709.
