### ISSUE TITLE
How do I know if the mpv is loaded in order to execute the load file? 

### ISSUE THREAD

**Issue by UrealToby** [mpv-player/mpv#11009]
I'm using qt to develop an MPV-based program, and if I load it directly after determining that `mpv_initialize(mpv) >= 0`, it will play in a separate window,instead of in the controls in my application.

**Comment by wbtcpip2** [comment]
mpv_set_property_string(mpvhandle, "wid", hwnd)

**Comment by UrealToby** [comment]
I'm using opengl, but thanks to you, I know what to do.
