### ISSUE TITLE
[Question] Recommended options for low end PC

### ISSUE THREAD

**Issue by sun95n** [mpv-player/mpv#11000]
Hi. I use mpv as my default media player. It consumes between `80 to 100 MiB of RAM` and `50 to 60% of CPU` when watching a `.webm (vp9) video with 1920x1080 resolution.`

And well, I was wondering if I could reduce this amount by using some options from the [manual](https://mpv.io/manual/stable/).

This is my mpv version and libraries:

```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.7-0ubuntu0.1
```

The relevant options in my `mpv.conf` file:

```
hwdec=auto
hwdec-codecs=all
vo=gpu
```
My terminal output when running `glxinfo -B`

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 2000 (SNB GT1) (0x106)
    Version: 21.2.6
    Accelerated: yes
    Video memory: 1536MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 2000 (SNB GT1)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 21.2.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.0 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```
And the Linux Mint system info window:

![001](https://user-images.githubusercontent.com/120290802/207180654-27e1fdd9-086d-4b1a-a43d-50388f471c93.png)

**Comment by CounterPillow** [comment]
Generally speaking, no, not really. The defaults make a reasonable tradeoff between performance and quality. If you don't mind your OSC potentially breaking and HDR being broken, you can try using the VAAPI VO on X11 with `vo=vaapi`. Whether this is more efficient in terms of power draw or CPU resources depends on your platform's VAAPI implementation though.

> mpv 0.32.0

Upgrade, and try the gpu-next VO, it should be more efficient on the GPU. I don't think your hardware will support Vulkan though.

> Intel Celeron

try `vd-lavc-dr=no`. Might lower your CPU usage, might raise it, depends on hardware.

> It consumes between 80 to 100 MiB of RAM

the majority of RAM usage will be cache when it's enabled (by default the case for network streams, and defaults to 150 MiB), see `demuxer-max-bytes` and `demuxer-max-back-bytes`. The other large part will be the libass glyph cache, there's no options to control it though from what I know.

> .webm (vp9) video with 1920x1080 resolution.

FFmpeg's VP9 decoder is highly optimised, but your FFmpeg is severely out of date because you are running some "stable" distro, so I don't know if all the SIMD improvements for it are in your version of FFmpeg.

I recommend you use [mpv-build](https://github.com/mpv-player/mpv-build/) to get an up-to-date FFmpeg, libass, libplacebo, and mpv, and then see if that changes things for the better.

**Comment by lavilao** [comment]
first of all, ram usage is not relevant in this context (video player) given your ammount of ram (you have more than I!), what impacts on performance it going to be cpu and gpu usage so dont worry about ram. As @CounterPillow said, its recommended you upgrade to a new mpv version, you are using mint so I guess you can try the mpv flatpak with ```vo=gpu-next```. I dont know in your case but in mine (intel celeron n3050) ```vd-lavc-dr=no``` improves performance (less droped frames). If you can (ONLY IF YOU CAN!) I would recommend you to upgrade to mint 21 as a newer kernel, compositor version and drivers might bring a beneffit to performance (again ONLY IF YOU CAN!, dont feel preassured).

**Comment by llyyr** [comment]
> In the past I have tried these options included in the gpu-hq profile. I noticed a 20% drop with the problem that videos larger than 1280x720 slow down.

You're probably not upscaling the video so scale/cscale aren't applicable in that scenario anyway. Idk if dscale=mitchell is cheaper than dscale=bilinear however, that seems hard to believe.

Unfortunately there's not much to be done since HD 2000 only has hardware decoding for H264/AVC and VC-1, try to consume content that's h264 whenever you can. VP9 decoding might have marginal improvements if you update your ffmpeg but that's about it

**Comment by hooke007** [comment]
Most gpu options' default values are friendly enough to hardware. Change them (i.e. `cscale=spline36`) usually means higher performance comsumption and may make your suffer more stress.

**Comment by monarc99** [comment]
You could try these options from my twitch profile. I use it to reduce the delay of the stream to the chat.
Maybe the limit the cpu usage.

deband=no

sws-allow-zimg=yes
sws-scaler=bilinear
sws-fast=yes
zimg-scaler=bilinear
zimg-dither=no

dither-depth=no
scale=bilinear
cscale=bilinear
dscale=bilinear
scale-antiring=0
cscale-antiring=0
dither-depth=no
correct-downscaling=no
sigmoid-upscaling=no

**Comment by CounterPillow** [comment]
@monarc99 99% of these options make absolutely 0 sense considering what the defaults already are and what they do to each other. sws only applies to software rendering. ditto with zimg. scale bilinear and no dithering is already the default. Ditto for the rest. Don't give cargo-cult advice.

**Comment by garoto** [comment]
With this CPU, it's better to restrict your media consumption to x264 and 720p tops, adding `gpu-dumb-mode=yes` to your .conf will also help greatly regarding framedrops.

**Comment by hooke007** [comment]
If he doesn't change any gpu rendering options, `gpu-dumb-mode` would do nothing.

**Comment by garoto** [comment]
> If he doesn't change any gpu rendering options, gpu-dumb-mode would do nothing.

Confidently incorrect.

**Comment by hooke007** [comment]
So show your evidence.
Tested with No config, `gpu-dumb-mode` was set silently and automatically.
```
[   0.198][v][vo/gpu] No advanced processing required. Enabling dumb mode.
```

**Comment by garoto** [comment]
Yep, tested here and I stand corrected.

**Comment by stax76** [comment]
I wasn't able to fluently play 4K 60fps with NVIDIA GT 1030 until I used:

```
d3d11va-zero-copy=yes  # Windows
hdr-compute-peak=no
```

**Comment by sergeevabc** [comment]
Could you suggest a few keys that will make decoding easier for a vintage laptop ( Core2Duo SSE3 2 GHz, 4 GB RAM, no GPU, Windows 7 x64), please?

**Comment by CounterPillow** [comment]
@sergeevabc no

**Comment by butterw** [comment]
from https://github.com/mpv-player/mpv#system-requirements
"[...]mpv does not go out of its way to break on older hardware or old, unsupported operating systems, but development is not done with them in mind. Keeping compatibility with such setups is not guaranteed. If things work, consider it a happy accident."
sergeevabc: if the current release doesn't work for you, try (much) older versions or a different player.

**Comment by sergeevabc** [comment]
@butterw, I asked not about a compatible release, but about **keys**.

**Comment by butterw** [comment]
In general with weak laptops you need hwdec + hardware scaling.

**Comment by sergeevabc** [comment]
@guidocella, che carino, grazie.

With `--profile=fast` alone, I was able to watch 1920x1080 HEVC 30fps film with subtitles, making small pauses every now and then to cool down the laptop's processor. Perhaps there are some other keys that I should try?

**Comment by llyyr** [comment]
`--vd-lavc-dr=no` might also help since your processor is so old

**Comment by sergeevabc** [comment]
Hmm, has the `--fast` switch been removed?

```
[11:56] $ mpv.com --version
Unknown profile 'fast'.
Error parsing option profile (option parameter could not be parsed)
mpv v0.36.0-174-g83c0e980 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Aug 27 2023 00:39:28
libplacebo version: v6.292.0-231-g612071d-dirty
FFmpeg version: N-111823-g358919506
FFmpeg library versions:
   libavutil       58.17.100
   libavcodec      60.23.100
   libavformat     60.10.100
   libswscale      7.3.100
   libavfilter     9.11.100
   libswresample   4.11.100
```

**Comment by hooke007** [comment]
>mpv v0.36.0-174-g83c0e980
