### ISSUE TITLE
Build error with Homebrew - err: Package iconv was not found in the pkg-config search path

### ISSUE THREAD

**Issue by getswifty1** [mpv-player/mpv#11012]
### mpv version and platform versions

macos Ventura 13.1 and Homebrew 3.6.15

brew.sh tells me the version brew will try to install currently is 0.35.0

I have Xcode installed already Version 14.2 (14C18)

### Reproduction steps

Run command to install mpv as a formula with brew

`brew install mpv`

### Expected behavior

mpv installs correctly as a formula with homebrew:

### Actual behavior

`brew install mpv` fails when building mpv because it can't find `iconv.pc`. This `iconv.pc` seems to be a dependency of `libarchive` but it can't find the file in the system as `libarchive` doesn't include it anymore and others are having this same issue with Linux:

https://github.com/libarchive/libarchive/issues/1819 

I tried finding this `iconv.pc` file with `find / -name "iconv.pc"` but it doesn't exist in the system. I manually built `libarchive` but it also didn't generate any `iconv.pc` file.

### Log file

Attached config.log and brew installation output

[config.log](https://github.com/mpv-player/mpv/files/10241254/config.log)
[brew-install.log](https://github.com/mpv-player/mpv/files/10241302/brew-install.log)

Relevant lines:

````

-------------------------------------------------------------------------
Checking for libarchive wrapper for reading zip files and more
['/Users/user/homebrew/Library/Homebrew/shims/mac/super/pkg-config', 'libarchive >= 3.4.0', '--libs', '--cflags', 'libarchive', '>=', '3.4.0']
err: Package iconv was not found in the pkg-config search path.
Perhaps you should add the directory containing `iconv.pc'
to the PKG_CONFIG_PATH environment variable
Package 'iconv', required by 'libarchive', not found

from /private/tmp/mpv-20221215-93480-1f2lki: The configuration failed
no ('libarchive >= 3.4.0' not found)


````

**Comment by CounterPillow** [comment]
and why report this to mpv? The homebrew formula isn't maintained by mpv.

**Comment by getswifty1** [comment]
@CounterPillow Isn't the homebrew formula trying to build the official mpv code? There is nothing in the logs that tells me homebrew is building a fork of mpv

**Comment by CounterPillow** [comment]
The problem appears to be with libarchive, not mpv's code. What competent distributions in such cases usually do is not ship the broken version but patch it or wait for an upstream fix. [Even Arch Linux managed to do this right](https://github.com/archlinux/svntogit-packages/commit/2fcd92532fcc68c86498e2c647b5362b3c8c1204). Homebrew, however, blindly bumped libarchive without checking whether it actually works.

Not an mpv problem.

**Comment by getswifty1** [comment]
@CounterPillow oh I see so homebrew is building it with this libarchive feature but libarchive is broken, so I should've brought this up to them then.

Anyway the issue is resolved for me, turns out I was using an unsupported installation method for homebrew (install anywhere). I reinstalled homebrew globally and it works now.

**Comment by Kagami** [comment]
Just remove iconv from `Requires.private` at `/opt/homebrew/opt/libarchive/lib/pkgconfig/libarchive.pc`
