### ISSUE TITLE
Can the top bar be hidden?

### ISSUE THREAD

**Issue by carman11** [mpv-player/mpv#11011]
[https://files.catbox.moe/a613hg.png](url)

**Comment by avih** [comment]
Add to your config file:
```
script-opts-add=osc-windowcontrols=no
```

See https://mpv.io/manual/master/#on-screen-controller-windowcontrols
and https://mpv.io/manual/master/#files

**Comment by carman11** [comment]
> ```
> script-opts-add=osc-windowcontrols=no
> ```

Thank you very much
