### ISSUE TITLE
gpu-api=vulkan appears completely broken with mesa-22.3.1-1 release

### ISSUE THREAD

**Issue by 24fpsDaVinci** [mpv-player/mpv#11026]
### Important Information

- mpv version: master, libplacebo master
- Linux Distribution and Version: Fedora 37
- Window Manager and version: wayland 
- GPU driver and version: intel gpu

### Reproduction steps
plays fine with --no-config
as soon as gpu-api=vulkan is applied heavy stuttering, AV desync and playback at 1-2fps 
this issue only appeared in mesa-22.3.1

### Expected behavior
no stuttering

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/10254880/output.txt)

**Comment by Dudemanguy** [comment]
Report upstream then? I don't have this mesa version yet myself.

**Comment by 24fpsDaVinci** [comment]
> I don't have this mesa version yet myself.

it was built today for f37
https://koji.fedoraproject.org/koji/buildinfo?buildID=2101768

**Comment by 24fpsDaVinci** [comment]
appears to be fixed after rebuilding libva to latest release

**Comment by q234rty** [comment]
`gpu-api=vulkan` works fine for me under Arch Linux, mesa 22.3.1 and amdgpu. I assume the issue is related to ANV?

**Comment by 24fpsDaVinci** [comment]
> `gpu-api=vulkan` works fine for me under Arch Linux, mesa 22.3.1 and amdgpu. I assume the issue is related to ANV?

yes appears to be related to these changes
https://www.phoronix.com/news/Mesa-22.3-ANV-Faster-Mesh-Shade
