### ISSUE TITLE
User shaders: main hook, why sdr is not in range [0.0, 1.0]

### ISSUE THREAD

**Issue by garamond13** [mpv-player/mpv#11023]
I did some tests with following setup.

windows 10, nvidia

config:
vo=gpu-next
gpu-api=d3d11
//user shader

the user shader used for the test:

```
//!HOOK MAIN
//!BIND HOOKED

#define FLT_EPSILON 1.192092896e-07

vec4 hook()
{
    vec4 c = HOOKED_texOff(0.0);
    if (c.r > (1.0 + FLT_EPSILON) || c.g > (1.0 + FLT_EPSILON) || c.b > (1.0 + FLT_EPSILON)) //is it > 1.0
        return vec4(1.0, 0.0, 0.0, 1.0); //red
    else if (c.r < -FLT_EPSILON || c.g < -FLT_EPSILON || c.b < -FLT_EPSILON) //else is it < 0.0
        return vec4(0.0, 0.0, 1.0, 1.0); //blue
    else
        return vec4(0.0, 0.25, 0.0, 1.0); //if its in range, dark green
}
```
test video: https://www.youtube.com/watch?v=Z4j5rJQMdOU

test results (without and with user shader):
![2022-12-18 20 10 6seVk](https://user-images.githubusercontent.com/98652255/208315172-7efb57de-e6b2-445f-b1fe-75a44f8f4922.png)
![2022-12-18 20 10 Wc8Xp](https://user-images.githubusercontent.com/98652255/208315178-aa826560-8bfc-44a2-8e44-922bb2199939.png)

Clamping to [0.0, 1.0] inside the shader gives green output only, as expected.

**Comment by haasn** [comment]
Looking at the generated shaders, nothing is happening that shouldn't - the conversion is a pure 3x3 matrix multiplication + vec3 offset. The generated matrix is this, exactly:

```
[vo/gpu-next/libplacebo] matrix:
[vo/gpu-next/libplacebo] 1.164384	0.000000	1.792741
[vo/gpu-next/libplacebo] 1.164384	-0.213249	-0.532909
[vo/gpu-next/libplacebo] 1.164384	2.112402	0.000000
[vo/gpu-next/libplacebo] offset:
[vo/gpu-next/libplacebo] -0.972945	0.301483	-1.133402
```

**Comment by haasn** [comment]
The matrix coefficients match exactly the results I find online, e.g. https://www.silicondust.com/yuv-to-rgb-conversion-for-tv-video/

```
const mat3 YCbCrToRGBmatrix = mat3(
1.1643835616, 0.0000000000, 1.7927410714,
1.1643835616, -0.2132486143, -0.5329093286,
1.1643835616, 2.1124017857, 0.0000000000
);

const vec3 YCbCrToRGBzero = vec3(-0.972945075, 0.301482665, -1.133402218);
```
