### ISSUE TITLE
MPV 0.35 SUBTITLE right to left no working,its show revers in Hebrew ,mpv 0.34 working good

### ISSUE THREAD

**Issue by YOYO48** [mpv-player/mpv#11028]
### Important Information
Provide following Information:

mpv version 0.35
Windows Version win11
Source of the mpv binary
VER 0.35 NOT OK
![203169014-68186d10-8da5-4902-8dbb-839c944bd10f](https://user-images.githubusercontent.com/118776337/208448591-1edfbe8e-0a84-47c8-ab50-54119ca79120.jpeg)
VER 0.34 WORK OK
![203170802-fcbd3131-122f-402b-9de7-668e32462a76](https://user-images.githubusercontent.com/118776337/208448722-c09fe858-ed7f-4446-86e7-8ff2dce7d8ca.jpeg)

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/10910
