### ISSUE TITLE
mpv on Mac with Apple Silicon

### ISSUE THREAD

**Issue by rgaufman** [mpv-player/mpv#11035]
Are there any semi-official or unofficial builds of mpv for Mac Apple Silicon? - or simple to follow build instructions?

I tried homebrew but this does not build the mpv.app bundle for /Applications, just the command line executable.

I also looked in https://mpv.io/installation/ but all the binaries there are Intel and not for Apple Silicon.

I also tried: https://github.com/deus0ww/homebrew-tap - but this fails with mpv: SHA256 mismatch.

Any suggestions?

**Comment by Akemi** [comment]
i don't know of any build. sadly brew removed the possibility to generate an app bundle because of brew cask.

**Comment by rgaufman** [comment]
So there’s no solution for Apple silicon / M1?

**Comment by CounterPillow** [comment]
Yes there is, you can build it yourself.

**Comment by rgaufman** [comment]
Where can I find instructions for this?

**Comment by Akemi** [comment]
```
brew install --HEAD mpv
```

should still work?

**Comment by rgaufman** [comment]
No go:

```
Roman-Mac-Mini-M1.local ➜  TetherX  brew install --HEAD mpv

Warning: Treating mpv as a formula. For the cask, use homebrew/cask/mpv
==> Fetching mpv
==> Cloning https://github.com/mpv-player/mpv.git
Updating /Volumes/Data/home/hackeron/Library/Caches/Homebrew/mpv--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 874e28f4a4 vo_kitty: Introduce modern sixel alternative
==> python3.10 bootstrap.py
==> python3.10 waf configure --prefix=/opt/homebrew/Cellar/mpv/HEAD-874e28f --enable-html-build --enable-javascript --enable-libmpv-shared --enable-lua --enable-libarchive --enable-uchardet --confdir=/opt/homebrew/etc/mpv --datadir=/opt/homebrew/Cellar/mpv/HEAD-874
Last 15 lines from /Volumes/Data/home/hackeron/Library/Logs/Homebrew/mpv/02.python3.10:
Checking for Linux's input-event-codes.h                                  : no
Checking for Lua                                                          : yes (version found: luajit)
Checking for Javascript (MuJS backend)                                    : yes
Checking for SSA/ASS support                                              : yes
Checking for zlib                                                         : yes
Checking for Bluray support                                               : yes
Checking for dvdnav support                                               : disabled
Checking for cdda support (libcdio)                                       : disabled
Checking for uchardet support                                             : yes
Checking for librubberband support                                        : yes
Checking for libzimg support (high quality software scaler)               : yes
Checking for LCMS2 support                                                : yes
Checking for VapourSynth filter bridge                                    : yes
Checking for libarchive wrapper for reading zip files and more            : no ('libarchive >= 3.4.0' not found)
You manually enabled the feature 'libarchive', but the autodetection check failed.

Do not report this issue to Homebrew/brew or Homebrew/core!

mpv's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
Roman-Mac-Mini-M1.local ➜  TetherX  brew install libarchive
Warning: libarchive 3.6.2 is already installed and up-to-date.
To reinstall 3.6.2, run:
  brew reinstall libarchive
```

**Comment by Akemi** [comment]
then homebrew is getting worse and worse. dunno, if they don't want to fix and don't accept reports we can't do anything about it. quite useless for a package manager.

**Comment by rgaufman** [comment]
Ok, but what is the recommended (or any) method to install mpv on Apple silicon Mac? Are there instructions anywhere?

**Comment by Akemi** [comment]
first of all there isn't really a difference in building mpv on arm oder intel based macs. you just need to proper dependencies. 

we have a readme that explains our current two build systems and what needs to be done to configure and build mpv. you just need to install the dependencies. alternatively use https://github.com/mpv-player/mpv-build if you don't want to build all dependencies yourself.

if you are looking for a step-by-step guide, you would need to look for one yourself.

**Comment by rgaufman** [comment]
I must not be the only person with an Apple Silicon Mac that wants to run mpv, so just something, anything, that gets me from not having mpv to having mpv for Apple silicon :) - I’ll have a look at the links, thank you, I already have all dependencies through homebrew.

**Comment by rgaufman** [comment]
Ah, this works now and I have a native Apple mpv.app bundle, excellent!  - https://github.com/deus0ww/homebrew-tap/issues/9
