### ISSUE TITLE
Easiest method to create a playlist with powershell (with over 32k chars parameter)

### ISSUE THREAD

**Issue by Chris763454357** [mpv-player/mpv#11033]
I have a powershell script that builds an array of files, I can then launch MPV and send that array as a parameter. This will open up MPV with the playlist built. Example:

`Start-Process  mpv.exe $myArray`

This works great, expect when $myArray is ~ 32767 characters or larger, nothing happens because the 'filepath' limit in windows is 32767 characters.

It seems JSON IPC would solve this issue, but it seems like overall kill. Any simple suggestions on how I can solve this problem?

**Comment by sfan5** [comment]
Write it a file as plaintext (one line = one entry) and use `--playlist`.

**Comment by Chris763454357** [comment]
wow, that works very well. Thank god I posted first before learning the JSON IPC thing.
