### ISSUE TITLE
Shuffle on mpv.conf

### ISSUE THREAD

**Issue by Cananbolt** [mpv-player/mpv#11038]
On mpv.conf I have the following...

[profile_for_music]
profile-cond=require 'mp.utils'.join_path(working_directory, path):match('Music') ~= nil
keep-open=no
loop-playlist
shuffle
script-opts-add=osc-visibility=always

Unfortunately the shuffle command does not do anything. Is there another command in mpv.conf to shuffle playlists?

**Comment by CounterPillow** [comment]
Don't use the question template for reporting bugs.

**Comment by guidocella** [comment]
`--shuffle` needs to be specified when starting mpv, the profile condition is evaluated too late.

**Comment by Cananbolt** [comment]
I see, thank you. Are there any commands that shuffles a playlist for a profile condition?

**Comment by guidocella** [comment]
Actually when I try it myself shuffle does work when matching the path. It may differ depending on how fast things are evaluated. Are you sure that profile is being applied at all?

Note that `shuffle` is an option, not a command, and there are no other options for mpv.conf to shuffle the playlist entries. There is the `playlist-shuffle` command for input.conf and scripts though.

**Comment by Cananbolt** [comment]
loop-infinite and script-opts-add=osc-visibility=always

Does work, it's only shuffle that does not work for some reason.

**Comment by garoto** [comment]
mpv is full of race conditions when parsing configs and command line options and lua scripts. It changes depending on how fast or slow a computer is regarding I/O speed and CPU capabilities.
