### ISSUE TITLE
mpv: symbol lookup error: mpv: undefined symbol: ass_track_set_feature

### ISSUE THREAD

**Issue by hista** [mpv-player/mpv#11042]
### Important Information

Provide following Information:
- mpv version: 0.35.0-4
- Linux Distribution and Version: debian sid
- Source of the mpv binary: deb https://deb.debian.org/debian/ sid
- If known which version of mpv introduced the problem
- Window Manager and version: openbox 3.6.1-10
- GPU driver and version: i915
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

mpv --no-config -v -v

### Expected behavior
working
### Actual behavior
mpv: symbol lookup error: mpv: undefined symbol: ass_track_set_feature

### Log file

mpv: symbol lookup error: mpv: undefined symbol: ass_track_set_feature

### Sample files

No sample files needed to reproduce this issue.

**Comment by CounterPillow** [comment]
report it to Debian, they need to rebuild mpv.

**Comment by hista** [comment]
Thanks for your quick answer, I have reported it to Debian.
