### ISSUE TITLE
[Question] How to add custom options to umpv script?

### ISSUE THREAD

**Issue by sun95n** [mpv-player/mpv#11043]
Hi. Does anyone know how to add custom options to the [umpv](https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv) script without editing line [83](https://github.com/mpv-player/mpv/blob/657fd2804c75fd4c838012ecbf5ce4536e4d487b/TOOLS/umpv#L83)? Something like opening a terminal and running: `umpv [options]` without showing an error.

I also read the description and it says that: `This only takes filenames as arguments. Custom options can't be used; the script interprets them as filenames.` So how do I avoid that behavior?

**Comment by snylonue** [comment]
Try `MPV=mpv --foo=bar umpv`.

I haven't tested this though.
