### ISSUE TITLE
MPV crashes with segmentation fault on laptop sleep while streaming Youtube video

### ISSUE THREAD

**Issue by OrdoFlammae** [mpv-player/mpv#11045]
### Important Information

Provide following Information:
- mpv version: 0.35.0
- Linux Distribution and Version: NixOS 22.11
- Source of the mpv binary: Nix Package Database
- This problem was introduced between versions 0.34.1 and 0.35.0
- Window Manager and version: XMonad 0.17.1
- GPU driver and version: Mesa 22.2.3
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

1. Run mpv with a youtube video link: `mpv --no-config <youtube-url>`
2. Send laptop to sleep (close the lid)
3. mpv crashes with segmentation fault (I don't know if this is immediately before sleep or immediately after sleep)

### Expected behavior
No segmentation fault

### Actual behavior
Segmentation fault

### Log file

[Log File](https://0x0.st/o5Y2.txt)
### Sample files

N/A

### Notes
- This was not happening with my previous installation of MPV, but it could be a dependency update as well.
- This bug does not appear when running MPV on a file instead of a stream.

**Comment by t-8ch** [comment]
Does it work with`--ao=pulse`?
Does it work on latest master (without special options)

**Comment by t-8ch** [comment]
Are you using libjack from pipewire?

**Comment by OrdoFlammae** [comment]
> Does it work with`--ao=pulse`? Does it work on latest master (without special options)

Yes, it does work with those options. I don't know if it works on the latest master, I couldn't get it to build properly, having issues with missing some "zink" library.

**Comment by t-8ch** [comment]
Then it is most likely a duplicate of #10959.

Since mpv 0.35 the PipeWire audio output is the default.
You are not actually using the PipeWire audio server which due to bugs in libpipewire and mpv trigger this crash.

You should be able to work around it in *one* of the following ways:
* Use mpv from master
* Use the PipeWire audio server instead of PulseAudio
* Install mpv with jack bindings and use the jack library from PipeWire (you don't actually have to use it)
* Run mpv with explicit `--ao=pulse`

**Comment by OrdoFlammae** [comment]
Thanks! I appreciate it. Sorry for the duplicate.

**Comment by t-8ch** [comment]
This seems to especially affect NixOS users. Maybe NixOS can backport 417d5c833c7a376de83fd24a0965cedfec83f022 until one of the other fixes properly fixes it there.

**Comment by OrdoFlammae** [comment]
Yeah, I'm going to open a bug on the Nixpkgs repo and see if they can add a config check there or something like that. It seems like the sort of thing that they should be able to fix in the wrapper.

**Comment by t-8ch** [comment]
Could you send a link to the discussion in case somebody else reads this issue?
(And my curiosity)

**Comment by OrdoFlammae** [comment]
NVM, it looks like I misunderstood, it was a related crash that got patched over that they were discussing. It looks like the base issue was fixed in a future version of pipewire that will be merged in to Nix very soon, however.
