### ISSUE TITLE
building libmpv with MSYS2

### ISSUE THREAD

**Issue by wbtcpip2** [mpv-player/mpv#11057]
### Reproduction steps

i'm following all the steps described here: https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#native-compilation-with-msys2
my goal is to build mpv and libmpv for windows 32 bits using MSYS2
All the described steps are successfully until i try to compile both libmpv and mpv with this command:
/usr/bin/python3 waf configure CC=gcc.exe --check-c-compiler=gcc --enable-libmpv-shared --prefix=$MSYSTEM_PREFIX
the process complete the config then it stalls, the prompt do not appears anymore

![2022-12-28_164055](https://user-images.githubusercontent.com/99482352/209836660-732af688-c39b-4e04-8996-d5ed1691a849.jpg)

if i try to close the consolle i see there are 2 sub processes stalled:
![2022-12-28_164200](https://user-images.githubusercontent.com/99482352/209836795-e31fe60a-2c69-4e4d-9d0a-9f8abcd458a7.jpg)

### Expected behavior
build mpv and libmpv win32 binaries

### Actual behavior
stall during compile

### Log file
[config.log](https://github.com/mpv-player/mpv/files/10314978/config.log)

**Comment by LaserEyess** [comment]
Does meson work?

**Comment by wbtcpip2** [comment]
if there is a guide on how to build mpv with meson on windows i will try

**Comment by LaserEyess** [comment]
```shell
meson setup $_builddir -Dlibmpv=true
meson compile -C $_builddir
```

**Comment by wbtcpip2** [comment]
D:\Meson>meson setup mpv-0.35.0 -Dlibmpv=true
The Meson build system
Version: 1.0.0
Source dir: D:\Meson\mpv-0.35.0
Build dir: D:\Meson
Build type: native build
Project name: mpv
Project version: 0.35.0
WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

do i need visual studio to compile with meson?

**Comment by LaserEyess** [comment]
If you're using MSYS2 it should autodetect the GNU toolchain, but you can do `CC=/path/to/gcc` to override it. You will also need to install ninja, but that should be included with meson.

**Comment by wbtcpip2** [comment]
D:\Meson>meson CC="D:\msys64\mingw32\bin\"
Traceback (most recent call last):
  File "mesonbuild\mesonmain.py", line 193, in run
  File "mesonbuild\msetup.py", line 308, in run
  File "mesonbuild\msetup.py", line 77, in __init__
  File "mesonbuild\msetup.py", line 161, in validate_dirs
  File "mesonbuild\msetup.py", line 132, in validate_core_dirs
  File "os.py", line 215, in makedirs
  File "os.py", line 215, in makedirs
  File "os.py", line 215, in makedirs
  File "os.py", line 225, in makedirs
OSError: [WinError 123] La sintassi del nome del file, della directory o del volume non è corretta: 'D:\\Meson\\CC=D:'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.

**Comment by LaserEyess** [comment]
```shell
CC=gcc.exe meson setup builddir -Dlibmpv=true
ninja -C builddir
```

**Comment by wbtcpip2** [comment]
D:\Meson>meson CC=gcc.exe meson setup mpv-0.35.0 -Dlibmpv=true
usage: meson [-h] {setup,configure,dist,install,introspect,init,test,wrap,subprojects,rewrite,compile,devenv,env2mfile,help} ...
meson: error: unrecognized arguments: setup mpv-0.35.0

**Comment by wbtcpip2** [comment]
according to this https://mesonbuild.com/SimpleStart.html i must install visual studio so i'm proceeding

**Comment by wbtcpip2** [comment]
how i can download libavcodec?

D:\Meson>meson setup mpv-0.35.0 -Dlibmpv=true
The Meson build system
Version: 1.0.0
Source dir: D:\Meson\mpv-0.35.0
Build dir: D:\Meson
Build type: native build
Project name: mpv
Project version: 0.35.0
C compiler for the host machine: cl (msvc 19.34.31937 "Microsoft (R) C/C++ Optimizing Compiler versione 19.34.31937 per x86")
C linker for the host machine: link link 14.34.31937.0
Host machine cpu family: x86
Host machine cpu: x86
Program python3 found: YES
Did not find pkg-config by name 'pkg-config'
Found Pkg-config: NO
Found CMake: C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.EXE (3.24.202208181)
Run-time dependency libavcodec found: NO (tried cmake)

mpv-0.35.0\meson.build:19:0: ERROR: Dependency lookup for libavcodec with method 'pkgconfig' failed: Pkg-config binary for machine 1 not found. Giving up.

**Comment by LaserEyess** [comment]
mpv can't be built with MSVC, which doesn't support C99. You have to use gcc. You mistyped the command I gave you, `CC=gcc.exe` comes *before* `meson`, it is exporting an environment variable. Basically, the waf guide for MSYS is 99% of what you want, except for the very last part.

Instead of:
```shell
/usr/bin/python3 waf configure CC=gcc.exe --check-c-compiler=gcc --enable-libmpv-shared --prefix=$MSYSTEM_PREFIX
/usr/bin/python3 waf install
```
do
```shell
CC=gcc.exe meson setup $builddir -Dlibmpv=true
meson compile -C $builddir
meson install --prefix=$MSYSTEM_PREFIX
```
Note that it is not `meson CC=gcc.exe meson setup` but rather `CC=gcc.exe meson setup`.

As for your first issue, that is likely a waf bug, the only thing I can say to that your log looks fine. I think that is either a waf issue or an MSYS2 issue, but basically the build configured just fine and then waf itself hung, so basically it isn't an mpv issue.

**Comment by wbtcpip2** [comment]
thank you. the problem is with the first command line

D:\Meson>CC=gcc.exe meson setup $builddir -Dlibmpv=true
"CC" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.

where do i have to enter those commands? in a standard shell? or still i have to use msys2?

msys2 do not know meson:

# CC=gcc.exe meson setup mpv-0.35.0 -Dlibmpv=true
-bash: meson: command not found

**Comment by LaserEyess** [comment]
This is for MSYS2, you have to install meson. https://www.msys2.org/docs/package-management/

**Comment by wbtcpip2** [comment]
i have installed:
Packages (1) mingw-w64-x86_64-python-3.10.9-1
and
Packages (1) mingw-w64-x86_64-meson-1.0.0-1

now i get:
# CC=gcc.exe meson setup mpv -Dlibmpv=true
ERROR: This python3 seems to be msys/python on MSYS2 Windows, but you are in a MinGW environment
ERROR: Please install and use mingw-w64-x86_64-python3 and/or mingw-w64-x86_64-meson with Pacman

i'm running msys2 MINGW32 because i want to build a 32 bits mpv
msys2 must be run under mingw? or under MSYS?

**Comment by LaserEyess** [comment]
I don't think I can help you any further, you have to set up the environment yourself. The following links should help:

 - https://www.msys2.org/docs/environments/
- https://www.msys2.org/docs/package-naming/

Just remember the following:
1. You want to use the MINGW32 environment
2.  you want to install `mingw-w64-i686-` packages
3. Commands **must** be run inside the msys2 MINGW32 shell.

**Comment by wbtcpip2** [comment]
thank you appreciate your help ... but it's a mess i give up

Packages (1) mingw-w64-i686-python-3.10.9-1 installed
Packages (2) mingw-w64-i686-ninja-1.11.1-2  mingw-w64-i686-meson-1.0.0-1 installed ans still says that
ERROR: This python3 seems to be msys/python on MSYS2 Windows, but you are in a MinGW environment
ERROR: Please install and use mingw-w64-x86_64-python3 and/or mingw-w64-x86_64-meson with Pacman

mission impossible

**Comment by RivenSkaye** [comment]
This seems to be an issue with Waf hanging up, there's a [related issue open in m-ab-s](https://github.com/m-ab-s/media-autobuild_suite/issues/2346) and sending SIGKILL seems to be the only solution once you're sure the step in the process is finished. I tried EOF and SIGQUIT as well, but they don't seem to be doing anything.
Would be nice if someone else could figure out where/how Waf hangs up to open an issue on [their GitLab](https://gitlab.com/ita1024/waf/-/issues)
