### ISSUE TITLE
Audio crackling for vast majority of my .mp3 files

### ISSUE THREAD

**Issue by zDEFz** [mpv-player/mpv#11055]
### Important Information

Provide following Information:
- mpv version
mpv 0.35.0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: n5.1.2
- Linux Distribution and Version
Arch Linux x86_64 Kernel 6.1.1-arch1-1
- Source of the mpv binary
https://aur.archlinux.org/packages/mpv-vapoursynth
/usr/bin/mpv
- If known which version of mpv introduced the problem
- Window Manager and version
sway version 1.7
- GPU driver and version
edac_mce_amd           57344  0
amdgpu              10739712  101
gpu_sched              49152  1 amdgpu
drm_buddy              20480  1 amdgpu
video                  65536  1 amdgpu
drm_ttm_helper         16384  1 amdgpu
ttm                    94208  2 amdgpu,drm_ttm_helper
drm_display_helper    212992  1 amdgpu
- Possible screenshot or video of visual glitches
Audio clip. Broken = https://pomf.lain.la/f/e9zho64.m4a . At 5-6s I repeat the file via keyboard
VLC playback. Working = https://pomf.lain.la/f/fyfyc2fl.m4a
Source file= https://pomf2.lain.la/f/4wg6xrw3.mp3

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

I am on the latest version

### Reproduction steps
1. Play the source file https://pomf2.lain.la/f/4wg6xrw3.mp3 via `mpv 4wg6xrw3.mp3`

### Expected behavior
Audio is clean

### Actual behavior
Audio crackles. See https://pomf.lain.la/f/e9zho64.m4a . At 5-6s I repeat the file via keyboard
### Log file

Not OK `mpv -log-file=no-conf-no-videor.log --no-config --no-video cut.mp3`
 -> https://0x0.st/o55P.log
OK  `mpv -log-file=no-config-no-video-aopulse.log --ao=pulse cut.mp3`
 -> https://0x0.st/o55Z.log
OK  `mpv -log-file=no-video-no-config-alsa.log --ao=alsa cut.mp3`
 -> https://0x0.st/o55q.log

The issue will be closed for ignoring the issue template.

### Sample files
https://pomf2.lain.la/f/4wg6xrw3.mp3

### Additional info
Playing back .opus files, flac files and other files works without issue
Sample: https://pomf2.lain.la/f/x4hbpger.opus
Command: `mpv -log-file=no-config-no-video-aopulse.log cut.opus`
Log: https://0x0.st/o55A.log

**Comment by avih** [comment]
> Command: mpv -log-file=no-config-no-video-aopulse.log cut.opus
> Log: https://0x0.st/o55A.log

This log file name suggests you used the options `--no-config` and `--no-video` at the command line, but the log file you linked has this:
```
Command line options: '-log-file=normal.log' 'cut.opus'
```

So either you didn't actually use `--no-config`, or you uploaded an incorrect log file.

The goal of using `--no-config` is to ensure nothing at your config files interferes.

**Comment by zDEFz** [comment]
Thank you ! 
Yea. I'm sorry. All these little details. Yea, I uploaded an incorrect file!

mpv -log-file=normal.log --no-config --no-video cut.opus -> https://0x0.st/o551.log

**Comment by t-8ch** [comment]
Can you check with pw-dump or pw-top which samplerate pipewire is using on the hardware?
Same for pulse.

**Comment by zDEFz** [comment]
@t-8ch can you instruct me how to dump pipewire-pulse? I do not have pipewire-alsa, so pulse makes sense

### crackling
mpv --loop --no-config --no-video cut.mp3 -> https://0x0.st/o5RY.json
during: pw-dump > tmp4

#### no crackling
mpv --loop --no-config --no-video --ao=pulse cut.mp3 -> https://0x0.st/o5Rl.json
during: pw-dump > tmp5


### pactl-info
% pactl info                                  
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 2145
Tile Size: 65472
User Name: def
Host Name: archlinux
Server Name: PulseAudio (on PipeWire 0.3.63)
Server Version: 15.0.0
Default Sample Specification: float32le 2ch 192000Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.usb-RME_ADI-2_DAC__51080054__B0557DE7E9AE0C8-00.analog-stereo
Default Source: alsa_output.usb-RME_ADI-2_DAC__51080054__B0557DE7E9AE0C8-00.analog-stereo.monitor
Cookie: dd24:dc81

**Comment by qmega** [comment]
Just a hunch that's not too likely to work, but does increasing `link.max-buffers` to `64` in `~/.config/pipewire/pipewire.conf` (and restart pipewire daemon) help by any chance?

**Comment by t-8ch** [comment]
One difference are the audio formats used:
pulse: F32LE, pipewire: F32P

**Comment by t-8ch** [comment]
@zDEFz
Please try to convert the the mp3 to raw PCM with `ffmpeg -i 4wg6xrw3.mp3 test.wav` and then play that with `pw-play -v test.wav` and provide the outputs.

**Comment by zDEFz** [comment]
> Just a hunch that's not too likely to work, but does increasing `link.max-buffers` to `64` in `~/.config/pipewire/pipewire.conf` (and restart pipewire daemon) help by any chance?

Did not help.

> @zDEFz Please try to convert the the mp3 to raw PCM with `ffmpeg -i 4wg6xrw3.mp3 test.wav` and then play that with `pw-play -v test.wav` and provide the outputs.

ffmpeg -i cut.mp3 cut.wav -> pw-play -v cut.wav  -> https://0x0.st/o5Fp.txt
No crackling when playing back the raw PCM.

**Comment by zDEFz** [comment]
@avih  helped me figuring something. The following reproduces the issue
mpv --no-config av://lavfi:sine=frequency=1000:sample_rate=44100

Putting it to 48000 and the issue is gone!
mpv --no-config av://lavfi:sine=frequency=1000:sample_rate=48000

**Comment by qmega** [comment]
If it's to do with pipewire's resampler, then this could help:
```
audio-swresample-o=resampler=soxr,precision=28
audio-samplerate=192000
audio-format=float
```
Basically using mpv to resample instead of pipewire. (AFAIK, soxr is one of the better resamplers around anyway, in terms of artifacting and cpu usage, with the downside of above-average latency which shouldn't matter for a media player as long as the A/V sync compensates for it.)

Even if that works, I suppose there's still an issue with your system somewhere, but if matching PW's sample rate avoids the issue then that could give a better idea of where to look...

**Comment by zDEFz** [comment]
> 

--audio-samplerate=192000 -> works!

I found out about another thing! I have PianoTeq 8, a VST tool, and if it runs before mpv has been invocated, pipewire plays fine. BUT it does realtime audio-scheduling while turned on, and it forces ALSA output through PipeWire Media Server as well as 44100Hz@256 samples. Sometimes I need more sampling rate and sampling size, though.

**Comment by avih** [comment]
> Basically using mpv to resample instead of pipewire

We already know this works. The goal is not to work around the issue. The goal is to fix the issue so that it sounds good even if mpv outputs 44.1KHz.

**Comment by t-8ch** [comment]
Does it also work with *only* `audio-format=float`?

The resampling in pipewire should in general be fine. `--ao=pulse` is also using pipewire via pipewire-pulse which uses the same resampling code.

**Comment by zDEFz** [comment]
> Does it also work with _only_ `audio-format=float`?
> 
> The resampling in pipewire should in general be fine. `--ao=pulse` is also using pipewire via pipewire-pulse which uses the same resampling code.

It does not work with only `audio-format=float`. I did issue `mpv -log-file=44100-sine.log --end=5 --audio-format=float av://lavfi:sine=frequency=1000:sample_rate=44100`

**Comment by qmega** [comment]
> The resampling in pipewire should in general be fine. `--ao=pulse` is also using pipewire via pipewire-pulse which uses the same resampling code.

Could the buffer size be the difference? Resampler has to look at multiple samples and several people have had crackling issues -- e.g. #9992 -- that were fixed by a larger buffer.

I guess there was a convo on IRC that I didn't see, but if it hasn't been tried, setting mpv's `pipewire-buffer` higher might be worth a shot. As far as I can tell, nobody ever figured out a way to determine optimal buffer size, and clearly different values work better for different people.

FWIW, I have an RME ADI-2 (which is what appears to be used in the report logs) and I can't reproduce the issue with pipewire at 192kHz (or with the `default.clock.allowed-rates` setting in the json dump) and the provided sample mp3 on Arch Linux (though Arch doesn't really imply any particular standard environment). Could it be a CPU performance issue?

**Comment by zDEFz** [comment]
>> Could it be a CPU performance issue?

Somewhere in the ether I wrote that running PianoTeq 8 forces pipewire to start in exclusive realtime  mode. 
When the program runs, no issues appear.  Other than that, the issue doesn't happen in VLC and the issue is very recent.
I doubt its a performance issue. I have a AMD 5800x3D CPU and a AMD 6950XT GPU.
The Interface itself works very well at very low buffer size.


![screenshot_2022-12-28_16-23-17_719231692](https://user-images.githubusercontent.com/24463722/209834058-8cb89e9f-1a58-43ee-88f5-e4b78af492d6.png)

**Comment by zDEFz** [comment]
Try me. Necrofantasia at 10 times speed at 192khz/256 samples with Pedal down all the way, not a single xrun and still a lot of headroom! https://transfer.sh/mHiSz8/screenshot_2022-12-28_16-47-05_763131651.png

**Comment by t-8ch** [comment]
Does a larger --pipewire-buffer help?
Are errors shown in pw-top?

**Comment by zDEFz** [comment]
> Does a larger --pipewire-buffer help? Are errors shown in pw-top?

`mpv cut.mp3 --pipewire-buffer=800` no effect

nothing of interest there, no

```
I   28      0      0   0.0us   0.0us  0.00  0.00    0                  Dummy-Driver
S   29      0      0    ---     ---   ---   ---     0                  Freewheel-Driver
S   36      0      0    ---     ---   ---   ---     0                  Midi-Bridge
R   44     16  44100   7.5us   0.7us  0.02  0.00    0    S32LE 2 44100 alsa_output.usb-RME_ADI-2
R   56  35280  44100   3.6us   0.8us  0.01  0.00    0     F32P 2 44100  + mpv
```

**Comment by zDEFz** [comment]
@t-8ch any new instructions?

**Comment by t-8ch** [comment]
Updates should be fine.

Can you provide the output produced with "PIPEWIRE_DEBUG=D"?

**Comment by zDEFz** [comment]
> Updates should be fine.
> 
> Can you provide the output produced with "PIPEWIRE_DEBUG=D"?

How do I do that?

**Comment by t-8ch** [comment]
Exactly

**Comment by zDEFz** [comment]
PIPEWIRE_DEBUG=D mpv -log-file=pw-debug.log --no-config --no-video mpv cut.mp3 -> https://0x0.st/oRas.log

**Comment by t-8ch** [comment]
This is only the mpv log, did nothing else get printed? We need the pipewire log

**Comment by zDEFz** [comment]
> This is only the mpv log, did nothing else get printed? We need the pipewire log

not sure what you wanted to make me do. Guessed.

`PIPEWIRE_DEBUG=D mpv --loop -log-file=pw-debug.log --no-config --no-video mpv cut.mp3`
`pw-dump` during problematic playback  > https://0x0.st/oRa1.log

**Comment by t-8ch** [comment]
> not sure what you wanted to make me do. Guessed.

Sorry, I was on my phone.

```sh
PIPEWIRE_DEBUG=D mpv --no-config --no-video cut.mp3 > pw.log 2>&1
```

**Comment by zDEFz** [comment]
> > not sure what you wanted to make me do. Guessed.
> 
> Sorry, I was on my phone.
> 
> Try this:
> 
> ```shell
> PIPEWIRE_DEBUG=D mpv --no-config --no-video cut.mp3 > pw.log 2>&1
> ```

https://0x0.st/oRaf.log

**Comment by t-8ch** [comment]
@zDEFz What happens if you remove the 44100 from your custom `clock.allowed-rates` config?

@qmega Could you provide a pipewire log when playing to your DAC?
```sh
PIPEWIRE_DEBUG=D mpv --no-config --no-video cut.mp3 > pw.log 2>&1
```

**Comment by qmega** [comment]
With pipewire locked to 192000: [pw-192.log](https://github.com/mpv-player/mpv/files/10328449/pw-192.log)
With `clock.allowed-rates` set to `[ 44100 48000 96000 192000 ]`: [pw-allowed-rates2.log](https://github.com/mpv-player/mpv/files/10328450/pw-allowed-rates2.log)
I noticed Spa:Pod:Object:Param:Latency:minRate and Spa:Pod:Object:Param:Latency:maxRate are higher on my side (by a factor of 4 at 44100, and more at 192k, even adjusting for sample rate). I'm not sure what would be responsible for that. My pipewire config is pretty close to default: [pipewire.conf.txt](https://github.com/mpv-player/mpv/files/10328453/pipewire.conf.txt)
(Granted, I know little to nothing about pipewire internals. Ignore me if you know what you're looking for. Happy to test anything else if it'd help.)

One more thing I thought of, since forcing realtime scheduling came up... On the Arch machine in question, is `rtkit` installed / `rtkit-daemon` running? They are for me and pipewire uses them by default if I understand correctly.

**Comment by zDEFz** [comment]
> @zDEFz What happens if you remove the 44100 from your custom `clock.allowed-rates` config?

Then the issue disappears.

>One more thing I thought of, since forcing realtime scheduling came up... On the Arch machine in question, is rtkit installed / rtkit-daemon running? They are for me and pipewire uses them by default if I understand correctly.

Yes.

```
 rtkit-daemon.service - RealtimeKit Scheduling Policy Service
     Loaded: loaded (/usr/lib/systemd/system/rtkit-daemon.service; disabled; preset: disabled)
     Active: active (running) since Sat 2022-12-31 18:36:50 CET; 20h ago
   Main PID: 1026 (rtkit-daemon)
      Tasks: 3 (limit: 38402)
     Memory: 732.0K
        CPU: 184ms
     CGroup: /system.slice/rtkit-daemon.service
```

**Comment by t-8ch** [comment]
It seems to be this DAC can be configured. What sample rates do you have it configured at?
How is this configuration done?
How is the DAC connected to the computer?

**Comment by zDEFz** [comment]
> It seems to be this DAC can be configured. What sample rates do you have it configured at? How is this configuration done? How is the DAC connected to the computer?

>What sample rates do you have it configured at? 
You cannot set sample rates on the device itself. Like any other Sound Card, frequency and samplerates are set by the default driver for windows, linux, and mac. In actual usage, one would open the program of choice and pick the desired values. See screenshot posted before. Manual: https://www.rme-audio.de/downloads/adi2dac_e.pdf

> How is this configuration done?
Clarify which. This headphone amplifier (ADI 2 DAC FS) is essentially a DSP with headphone amp. There is no option t

>How is the DAC connected to the computer?
Immediately through USB

**Comment by qmega** [comment]
USB for me too. I've actually got a pretty weird setup where there's a fiber-optic extender and a hub between the computer and the DAC. It still acts as a normal USB device AFAIK, though.

The device does have a bunch of configuration but sample rate is negotiated through standard USB Audio protocol. It does display which sample rate is being used, and I can see it going at 192 and 44.1 when pipewire is configured each way.

FWIW, my firmware (SETUP > Options > Remap Keys / Diag. > SW Version) is `51 | 06/2022`.

**Comment by zDEFz** [comment]
> USB for me too. I've actually got a pretty weird setup where there's a fiber-optic extender and a hub between the computer and the DAC. It still acts as a normal USB device AFAIK, though.
> 
> The device does have a bunch of configuration but sample rate is negotiated through standard USB Audio protocol. It does display which sample rate is being used, and I can see it going at 192 and 44.1 when pipewire is configured each way.
> 
> FWIW, my firmware (SETUP > Options > Remap Keys / Diag. > SW Version) is `51 | 06/2022`.

Mine is the latest. I updated firmware yesterday. Yea. You can if you use fibre-optic-extender set a clock size, samplerates and dsp rate. But I do not use that SPDIF thingy.

**Comment by qmega** [comment]
> if you use fibre-optic-extender set a clock size, samplerates and dsp rate. But I do not use that SPDIF thingy.

To clarify, I have a fiber-optic _USB_ extender (TechLogix MOFO-USB321-15), a hub plugged into that, and the DAC plugged into the hub. My computer is in a different room from my desk.

I do not use the optical SPDIF input on the DAC either. I'm running over USB and the computer sets the rate.

**Comment by zDEFz** [comment]
You know what is weird?

running 'vlc cut.mp3' results in a `period_buffer` of `32` at 44100 Hz and `mpv cut.mp3` results at a `period_buffer` of `8`, leading to crackle.

actual vlc:

```
access: MMAP_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 44100 (44100/1)
period_size: 32
buffer_size: 2048
```

**Comment by zDEFz** [comment]
> `default.clock.*quantum` is in samples at `default.clock.rate`, and is apparently scaled accordingly when running the graph at alternate rates. So your min-quantum of 16 at 192k looks pretty extreme (less than a tenth of a millisecond). I did some trial and error on my own setup by setting min, max, and default quantum to the same value to force it, and 128 is the lowest power of two that didn't give me really messed up sound. Maybe you could go lower with your direct USB connection, but probably not 16. I don't really understand what quantum-limit does but that looks low too. How did you come up with your quantum values?

As far as I can remember, I do use the default config, apart of allowing other values than `48000` see here https://github.com/PipeWire/pipewire/blob/master/src/daemon/pipewire.conf.in



> When you did that pw-play test with the raw PCM before, it looks like it picked a latency of 100ms. What if you use pw-play's `--latency` flag to try to get it to use the same period as mpv? If that can repro the issue then maybe it's not really to do with mpv -- or maybe mpv should be requesting a higher latency.
> 

reproducible. ` pw-play --latency 16 cut.wav` = crackling.
Interesting that by today, `pw-play cut.wav` does not result in crackling, `mpv cut.wav` does however.
Reason? it picks the `period_size` of `8`

**Comment by t-8ch** [comment]
Can you provide a pipewire debug log of the working `pw-play`?
`PIPEWIRE_DEBUG=D pw-play --latency 16 cut.wav`

> and it run without crackling

Seems to run at 48000. What happens with pw-play with low latency and 48000?

**Comment by t-8ch** [comment]
`pw-play --latency` does the same as `mpv --pipewire-buffer`.
Can you doublecheck the effect of `mpv --pipewire-buffer=100` to match the default of pw-play?

**Comment by zDEFz** [comment]
> PIPEWIRE_DEBUG=D pw-play --latency 16 cut.wav

that was at `44100`.
PIPEWIRE_DEBUG=D pw-play --latency 16 cut.wav -> crackling
PIPEWIRE_DEBUG=D pw-play --latency 16  --rate 48000 cut.wav -> crackling
PIPEWIRE_DEBUG=D pw-play --latency 16  --rate 48000 cut.wav -> crackling
PIPEWIRE_DEBUG=D pw-play --latency 32 --rate 44100 cut.wav -> OK
PIPEWIRE_DEBUG=D pw-play --latency 32 --rate 48000 cut.wav -> OK

PIPEWIRE_DEBUG=D mpv --pipewire-buffer=100 cut.wav -> crackling
PIPEWIRE_DEBUG=D mpv --pipewire-buffer=1024 cut.wav -> crackling
PIPEWIRE_DEBUG=D mpv --pipewire-buffer=1024 cut.wav -> crackling
PIPEWIRE_DEBUG=D mpv --pipewire-buffer=2000 cut.wav -> crackling

PIPEWIRE_DEBUG=D mpv --audio-samplerate=44100 cut.wav -> crackling
PIPEWIRE_DEBUG=D mpv --audio-samplerate=48000 cut.wav -> OK

PIPEWIRE_DEBUG=D mpv --audio-samplerate=44100 --pipewire-buffer=32 cut.wav -> crackling
PIPEWIRE_DEBUG=D mpv --audio-samplerate=44100 --pipewire-buffer=2000 cut.wav -> crackling

**Comment by zDEFz** [comment]
I propose to change the line with  at `pipewire.conf' at https://github.com/PipeWire/pipewire/blob/master/src/daemon/pipewire.conf.in#L32 from `default.clock.min-quantum = 16` to `default.clock.min-quantum = 32` to get rid of the annoying issue

**Comment by t-8ch** [comment]
To be honest I'm a bit out of my depth here. I'll try to understand it, but maybe it would help to open a ticket for pipewire directly.

**Comment by zDEFz** [comment]
> To be honest I'm a bit out of my depth here. I'll try to understand it, but maybe it would help to open a ticket for pipewire directly.

Here we go: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2925

**Comment by qmega** [comment]
> Should I close this issue? By now I think its not MPV related, but interesting to know.

I think you were right to increase/remove your quantum-limit, but...

I still don't think we understand why mpv's `--pipewire-buffer` doesn't reproduce pw-play's result, and I wish we did. Is mpv not filling its buffer efficiently or something? If I remember correctly, it was mentioned somewhere else that some people get crackling when `--pipewire-buffer` is too *high*, which doesn't make any sense to me... so I can definitely believe ao_pipewire is doing something wrong.

Maybe that's more of issue #9992, though...

**Comment by t-8ch** [comment]
As for filling buffers not efficiently, could you *remove* the following code from `audio/out/ao_pipewire.c:158`:
```c
#if PW_CHECK_VERSION(0, 3, 49)
    if (b->requested != 0)
        nframes = MPMIN(b->requested, nframes);
#endif
```

**Comment by zDEFz** [comment]
> As for filling buffers not efficiently, could you _remove_ the following code from `audio/out/ao_pipewire.c:158`:
> 
> ```c
> #if PW_CHECK_VERSION(0, 3, 49)
>     if (b->requested != 0)
>         nframes = MPMIN(b->requested, nframes);
> #endif
> ```

I did exactly that. But isnt it confusing? The if is already commented out at the source. I did remove those lines, compiled it and saw no difference.

PKGBUILD
https://0x0.st/oR3p.txt

`makepkg -si --skippgpcheck --skipinteg `

No warranty I did it right. But it compiled and installed.

**Comment by t-8ch** [comment]
It is easier to just run it from the git checkout, no need for a full package

**Comment by zDEFz** [comment]
> It is easier to just run it from the git checkout, no need for a full package

Is that described in the wiki? I never did that! / don't know how to

**Comment by t-8ch** [comment]
It's described in the readme of mpv, just skip the install step.

**Comment by zDEFz** [comment]
@t-8ch that was vastly simpler. `./mpv --no-config --no-video "/stor/MusicLibrary/Unsorted/Ronald Jenkees 2007/cut.wav"` => crackling

`context.properties` in pipewire.conf
``` 
 default.clock.rate = 192000
    default.clock.allowed-rates = [ 44100 48000 96000 192000 ]
    default.clock.quantum = 512
    default.clock.min-quantum = 16
    default.clock.max-quantum = 2048
    default.clock.quantum-limit = 512
    settings.check-quantum = false
    settings.check-rate = false
```

**Comment by zDEFz** [comment]
Nice diff of `pw-dump`

https://0x0.st/oR3F.html

**Comment by t-8ch** [comment]
@zDEFz That diff is nice.
Can you build mpv from this branch and do it again?
https://github.com/t-8ch/mpv/tree/pipewire-debug

**Comment by zDEFz** [comment]
> @zDEFz That diff is nice. Can you build mpv from this branch and do it again? https://github.com/t-8ch/mpv/tree

@t-8ch what? Works in debug branch with the aforementioned lines to remove.
Amazing! Did you change anything? I double checked it even. I have the same config and the old one is crackling still.

https://0x0.st/oRIb.html

**Comment by t-8ch** [comment]
Yes, these two lines are the only changes.
Can you find out if it can be fixed by a single of those lines?

**Comment by zDEFz** [comment]
> Yes, these two lines are the only changes. Can you find out if it can be fixed by a single of those lines?

Removing `PW_KEY_NODE_ALWAYS_PROCESS, "true",` fixes the issue for me. Changing ` .options.buffer_msec=20` to `100` doesnt have any effect whatsoever.

**Comment by t-8ch** [comment]
Nice, AFAIK this has been always there, I'll have to investigate why.

This is probably useful information for the  pipewire ticket.

**Comment by zDEFz** [comment]
> Nice, AFAIK this has been always there, I'll have to investigate why.
> 
> This is probably useful information for the pipewire ticket.

Can you please comment on the ticket? I feel that I had a hard time explaining. 
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2925

**Comment by t-8ch** [comment]
As an additional check, what happens with `pw-play -v -P node.always-process=true build/cut.wav`

**Comment by zDEFz** [comment]
> As an additional check, what happens with `pw-play -v -P node.always-process=true cut.wav`

crackling.

**Comment by zDEFz** [comment]
Guys, we did it! https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2925#note_1714233 Issue is fixed :)

`node.always-process=true` ... "it makes sure that the node is always attached to a running driver"
We don't need to change anything. It was a bug in pipewire. Strangely, after the change, I feel that my audio sounds... different? Or even better? Could be bias, though.

**Comment by t-8ch** [comment]
@zDEFz FYI the fix for this is now in the regular ArchLinux pipewire package: https://github.com/archlinux/svntogit-packages/commit/3a4eb53f2b4cd87769a3b537c1fcc64d716a1e9b

**Comment by qmega** [comment]
@zDEFz You can probably close this now. Seems like it's all resolved.

While I'm here, you might be interested in this: (Definitely off-topic for mpv tracker at this point. Feel free to email me if you want to discuss, though keep in mind I have no idea what I'm doing.)
I finally got around to doing latency testing on my setup, and found out the properties I'd been trying to apply to the device to reduce latency were having no effect because they needed to be applied to the sink and source nodes instead. Doing so shaved something like 2ms off my measured latency! Could help with your piano thing. Furthermore I was actually able to run pipewire functionally with a quantum as low as 16 @ 192kHz (while without these tweaks the lowest I could go was 128).
`~/.config/wireplumber/main.lua.d/51-rme-adi-2-dac.lua`:
```lua
table.insert(alsa_monitor.rules, {
    matches = {
        {
            { "node.name", "matches", "alsa_output.usb-RME_ADI-2_DAC_*" },
        },
        {
            { "node.name", "matches", "alsa_input.usb-RME_ADI-2_DAC_*" },
        },
    },
    apply_properties = {
        ["api.alsa.disable-batch"] = true,
        ["api.alsa.headroom"]      = 0,
    },
})
```

**Comment by zDEFz** [comment]
@qmega unfortunately I cannot test anything lower than 192/128 samples (0.7ms) in exclusive mode via Pianoteq 8. https://modartt.com Free trial available. The application crashes hangs then appears to be an issue with pipewire. To test, I just chosen ALSA as device type and then default ALSA output (PipeWire Media Server)  Do you have IRC? Would you like to join #pipewire on irc (OFTC.NET) ? I'm aliased bluetail there . Also when looking at `pw-top`, timings seem to jump to 0 and back to something else. Might be worth giving a shot together to figure what is happening. 

By the way, such low latency is probably unrealistic because it would mean you get bad performance and fast overruns/xruns / crackling. Its even shown in PianoTeq 8. https://0x0.st/ohXM.png
I close this issue, I will leave you a email later this day.
