### ISSUE TITLE
The menu that says "Drop files or URLs to play here" does not appear!

### ISSUE THREAD

**Issue by Idhtft** [mpv-player/mpv#11063]
### Important Information

Provide following Information:
- mpv version: 0.34.0
- Platform and Version: Windows 10 Pro
- Source of the mpv binary: I don't know

When I run mpv.exe, the menu that says "Drop files or URLs to play here" does not appear if I run mpv from the start menu, instead it opens and lists png files in system32. How can I fix that?

**Comment by CounterPillow** [comment]
uninstall whatever stupid script you added that does that.

**Comment by snylonue** [comment]
Can you provide a log?

**Comment by Idhtft** [comment]
> uninstall whatever stupid script you added that does that.

Understood sir, [this](https://github.com/jonniek/mpv-playlistmanager) was the source of the problem.
