### ISSUE TITLE
Is pipewire a hard dependency?

### ISSUE THREAD

**Issue by user451421541757324** [mpv-player/mpv#11064]
I'm currently on Arch Linux with a pure (functioning) ALSA setup.

I used mpv for years with ALSA only, but weeks ago after a new mpv release (when upgrading) I was asked to install pipewire package. I didn't want to do that since ALSA was functioning good. I was able to install mpv without the pipewire package, but mpv did not start.

So I was wondering if pipewire is an absolutely necessary dependency for mpv, or maybe it was a choice of the Arch Linux maintainers.

**Comment by sfan5** [comment]
It's not.

**Comment by eworm-de** [comment]
To clarify this... Pipewire is a build time dependency, so if mpv is built with pipewire it's not optional for that build.

**Comment by user451421541757324** [comment]
> so if mpv is built with pipewire it's not optional for that build

Would it be possible to make it optional? Or would it require too much work?

**Comment by sfan5** [comment]
To expand on that: if your mpv is built with pipewire it becomes a dependency to *start* mpv but you are not forced to use pipewire for audio playback.
Having pipewire installed also doesn't mean that you have to use it as audio server. You can mask the `pipewire.socket` unit if you absolutely want to avoid it.

**Comment by user451421541757324** [comment]
> Having pipewire installed also doesn't mean that you have to use it as audio server

Sure, I can do that but my concern mostly was with the presence of the new package. Many users have found themselves having an extra package, which by the way is a useless package since mpv works great without it.

Yes it's just a single package, what harm can it do? However, if all developers thought like this, distros would be a dependency hell. I believe that having a low number of dependencies benefits all users.

**Comment by avih** [comment]
> Many users have found themselves having an extra package, which by the way is a useless package since mpv works great without it.

You can build mpv however you want. If you don't need pipewire then you can build without pipewire.

If you use your distro mpv package, then you get whatever the distro mpv maintainer decided to do. If you think they don't need to include pipewire then you can complain to them. The mpv project does not require to build with pipewire.

**Comment by CounterPillow** [comment]
The trouble here really isn't in mpv, the problem is that at least Arch doesn't split pipewire into client lib and server like pulse is split. This means that if something is built against pipewire, you need to have the pipewire package including its server installed (though not running). Contrast this to pulseaudio, where you can have libpulse without pulseaudio.

However, whether your distro cares about you specifically not wanting a tiny dependency installed on your system to split the package in two is another question.

Personally I suggest not caring this much.
