### ISSUE TITLE
Simple script for showing and hiding the OSC, but whit a catch

### ISSUE THREAD

**Issue by houman-rzk** [mpv-player/mpv#11068]
Hello.

I want to write a Lua script for mpv that **shows the OSC for five seconds and then hides it**, but also **hides the OSC if I run the script when the OSC is visible**.

I believe that what my script has to do is something like this:
1. Stop other executions of the script
2. Get the current value of 'osc-visibility' ('auto'/'always'/'never')
3. If (osc-visibility == always) then set it to 'auto'; else set it to 'always', wait 5 seconds and set it to 'auto'

I have searched various online sources and have read [what I believe to be] all the relevant sections of the manual. With the gathered information I have managed to write something, but it's incomplete:
```
function show_osc()
    { Kill all running show_osc's }
    wait = 5 

    visibility = { get_current_osc_visibility_value() }

    if visibility == "always" then
        mp.command("script-message osc-visibility auto")
    else
        mp.command("script-message osc-visibility always")
        mp.add_timeout(
            wait,
            function()
                mp.command("script-message osc-visibility auto")
            end
        )
    end
end

mp.add_key_binding("o", "show_osc", show_osc)
```

What should the missing parts be?

Thanks in advance.

**Comment by guidocella** [comment]
`require 'mp.utils'.shared_script_property_get('osc-visibility')` gets you the current OSC visibility. It's not documented.

To disable a timer you call `:kill()` on the object returned by `mp.add_timeout`.

**Comment by houman-rzk** [comment]
Thank you for your response, @guidocella.

I'm sorry, maybe I am not using it correctly, but doing `require 'mp.utils'` and then various 'permutations' of `v = shared_script_property_get('osc-visibility')` on mpv 0.35.0 doesn't get the OSC visibility for me, the script just freezes and doesn't run anything beyond that point. A short example script on how to use this function would be much appreciated.

Anyway, with your advice of using `:kill()` I have managed to complete the script that I initially wanted. It looks like this now:
```
local timeout

function show_osc()
    wait = 5 

    level = mp.get_property("osd-level")
    mp.set_property_number("osd-level", 0)

    if timeout == nil then
        mp.command("script-message osc-visibility always")
        timeout = mp.add_timeout(
            wait,
            function()
                mp.command("script-message osc-visibility auto")
                timeout = nil
            end
        )
    else
        timeout:kill()
        timeout = nil
        mp.command("script-message osc-visibility auto")
    end

    mp.set_property_number("osd-level", level)
end

mp.add_key_binding("o", "show_osc", show_osc)
```

Thank you for your time.

**Comment by guidocella** [comment]
`require 'mp.utils'.shared_script_property_get('osc-visibility')` is all one statement. You can also do

```lua
local utils = require 'mp.utils'
local v = utils.shared_script_property_get('osc-visibility')
```

**Comment by houman-rzk** [comment]
I did not expect that. I thought they were different statements.

Writing my first mpv Lua script has been very illuminating.

Thank you very much.

**Comment by VimWei** [comment]
> `require 'mp.utils'.shared_script_property_get('osc-visibility')` is all one statement. You can also do
> 
> ```lua
> local utils = require 'mp.utils'
> local v = utils.shared_script_property_get('osc-visibility')
> ```


The function 'shared_script_property_get' is undocumented. Can we still use it?

```
Lua error: attempt to call field 'shared_script_property_get' (a nil value)
```

ref: https://github.com/linguisticmind/mpv-scripts/issues/6
