### ISSUE TITLE
Assert hits when encoding file with particular subtitle script (regression)

### ISSUE THREAD

**Issue by rcombs** [mpv-player/mpv#11066]
### Important Information

Provide following Information:
- mpv e97819f88e451623a397b79d101497205fe849f9 through master
- macOS 13.1
- local artisanally-built mpv

### Reproduction steps

Encode affected file with mpv newer than e97819f88e451623a397b79d101497205fe849f9:

```
mpv 'input.mkv' '--start=0:00:00.000' '--end=0:01:29.923' --loop-file=no --no-pause --ovc=libx264 --oac=aac --sid=1 --vid=1 --aid=1 --sub-ass-override=yes --sub-ass-vsfilter-aspect-compat=yes --sub-auto=exact --sub-pos=100 '--sub-delay=0.000000' --video-rotate=0 --deinterlace=no --vf-add=lavfi-eq=contrast=1:saturation=1:brightness=0 --ovcopts-add=b=5337k --ovcopts-add=crf=16 '--o=test.mp4' '--term-status-msg=Encode time-pos: ${=time-pos}\n'
```

Or, with attached sample:

```
mpv 'dummy.mkv' -sub-file sample.ass '--start=0:00:00.000' '--end=0:01:29.923' --loop-file=no --no-pause --ovc=libx264 --oac=aac --vid=1 --aid=1 --sub-ass-override=yes --sub-ass-vsfilter-aspect-compat=yes --sub-auto=exact --sub-pos=100 '--sub-delay=0.000000' --video-rotate=0 --deinterlace=no --vf-add=lavfi-eq=contrast=1:saturation=1:brightness=0 --ovcopts-add=b=5337k --ovcopts-add=crf=16 '--o=test.mp4' '--term-status-msg=Encode time-pos: ${=time-pos}\n'
```

Note this only happens when the input resolution is 1920x1080.

### Expected behavior

Encode finishes normally

### Actual behavior

mpv crashes on this line: https://github.com/mpv-player/mpv/blob/ad65c8855b60df3c95026ee7b315eca31c59f3bc/sub/draw_bmp.c#L174

### Sample files

[sub-crash.ass.zip](https://github.com/mpv-player/mpv/files/10326057/sub-crash.ass.zip)

**Comment by Dudemanguy** [comment]
Should be fixed by #10946 if you want to give it a look.
