### ISSUE TITLE
mpv doesn't run from xfce desktop if vdpau is used [was: MPV not runs from xfce desktop icon]

### ISSUE THREAD

**Issue by kotrs** [mpv-player/mpv#1106]
MPV not runs from desktop (clicking by movie file)  when i add to config file "vo=vdpau". It runs only from command line by command "mpv file_name.mp4" for same user.
What is wrong?

Thank you

**Comment by rrooij** [comment]
This issue was with an old version of mpv. The user didn't bother to update it to a newer version. Can be closed in my opinion.
