### ISSUE TITLE
regression: gl->BufferStorage check in opengl/ra_gl.c breaks software decoding on NXP i.MX8MQ

### ISSUE THREAD

**Issue by josch** [mpv-player/mpv#11073]
### Important Information

Provide following Information:
- mpv version: git HEAD
- Linux Distribution and Version: Debian unstable (all packages in their latest versions)
- Source of the mpv binary: `./waf -v build`
- If known which version of mpv introduced the problem: 2fc327f2fdd48f0cd58a4d4382a7aa57f3fabd77
- Window Manager and version: sway 1.7 on wayland 1.21.0
- GPU driver and version: etnaviv on Linux 6.1.0 and mesa 22.3.1

### Reproduction steps

I'm using the [MNT Reform open hardware laptop](https://shop.mntre.com/products/mnt-reform) with an NXP/Freescale i.MX8MQ with 4x ARM Cortex-A53 cores (1.5 GHz). Since the 0.35.0 release, software decoding of 1080p@30 h264 video is no longer possible without a lot of dropped frames:

```
Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).
```

I bisected mpv git and found that commit 2fc327f2fdd48f0cd58a4d4382a7aa57f3fabd77 introduced the issue on my platform. Specifically, the following patch will make software decoding work fine on my system again:

```diff
--- a/video/out/opengl/ra_gl.c
+++ b/video/out/opengl/ra_gl.c
@@ -590,7 +590,7 @@ static struct ra_buf *gl_buf_create(struct ra *ra,
 {
     GL *gl = ra_gl_get(ra);
 
-    if (params->host_mapped && !gl->BufferStorage)
+    if (params->host_mapped && gl->version < 440)
         return NULL;
 
     struct ra_buf *buf = talloc_zero(NULL, struct ra_buf);
```

### Log file

I attached two log files recorded with -v -v. The file `old.log` is from git HEAD without above patch where video is too slow to be watchable. The file `new.log` is with above patch and everything works fine again.

 * [old.log](https://github.com/mpv-player/mpv/files/10328375/old.log)
 * [new.log](https://github.com/mpv-player/mpv/files/10328376/new.log)

**Comment by CounterPillow** [comment]
Duplicate of #10997

**Comment by josch** [comment]
I can confirm that the `--vd-lavc-dr=no` workaround from #10997 makes playback smooth again on my platform.

**Comment by CounterPillow** [comment]
then close your issue

**Comment by josch** [comment]
Ah sorry, I though the etiquette would be, that the repository owner is the only one to close issues.
