### ISSUE TITLE
Does libmpv support lua script ?

### ISSUE THREAD

**Issue by trump-7575** [mpv-player/mpv#11079]
### Important Information

Provide following Information:
- mpv version  0.34.1
- libmpv version : 0.34.1 ( /usr/include/mpv/client.h : 1.109 )
- Linux Distribution and Version : Ubuntu 22.04 LTS
- Source of the mpv binary : from ubuntu official respository
- If known which version of mpv introduced the problem  : unknown
- Window Manager and version  : not-avail.
- GPU driver and version  :  not-avail.
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1.  Install libmpv 
2.   build an C  example as simple as :
...
 const char *cmd[] = {"loadfile", "/home/trump/11.mp4",  "replace" ,   NULL};
                                                mpv_command( ctx, cmd);
  ...       
  
3.  put a lua script from https://github.com/CogentRedTester/mpv-file-browser and its option to the default dir.  
~/.config/mpv/scripts    and  script-opts

### Expected behavior

The lua script should work during playing the above video clip

### Actual behavior

The lua script doesnot work :  its key binding  "Ctrl+o"  does not work at all. 

### Log file

...
[d][file_browser] loading file /home/trump/.config/mpv/scripts/file-browser.lua
...
[w][input] No key binding found for key 'Ctrl+o'
...

### Sample files

whatever video clips is fine.

=================================================
Even though  the lua script works with mpv :  I double-clicked the video clip 11.mp4 and mpv is launched to play it. In this case , the lua script does work. 
But it doesnot work with libmpv. Is it due to the outdated libmpv or  lua script doesnot work with libmpv at all ?
I had already added the settings into the above C example : 

         mpv_set_option_string( ctx , "config-dir", "/home/trump/.config/mpv"); // set config root
         mpv_set_option_string( ctx , "config", "yes"); // enable config loading

         mpv_set_option_string(ctx, "load-scripts", "yes");
         mpv_set_option_string(ctx, "script", "file-browser");
         mpv_set_option_string(ctx, "include", "file-browser");

If you need more info. , please donot hesitate to let me know.

**Comment by hooke007** [comment]
rebind the key first

**Comment by avih** [comment]
You didn't actually post your program, but you need to set config to "yes" before you initialize, and then it will load the config (and scripts) from the config dir. See this:

https://github.com/mpv-player/mpv/blob/ad65c8855b60df3c95026ee7b315eca31c59f3bc/libmpv/client.h#L434-L447

**Comment by 1156175523** [comment]
maybe you can try this
mpv_set_option_string(mpv, "input-default-bindings", "yes");
There is a difference in the default configuration between the mpv command and libmpv.
you can see with this cmd:
mpv --show-profile=libmpv
