### ISSUE TITLE
mpv/mruby Meson build support

### ISSUE THREAD

**Issue by RivenSkaye** [mpv-player/mpv#11078]
The [mruby branch](https://github.com/mpv-player/mpv/tree/mruby) only provides Waf build files. Is there any chance support for building it with Meson will be added?
Due to [an issue with Waf hanging up](https://github.com/m-ab-s/media-autobuild_suite/issues/2346) opened in mabs, but reproducible outside of the mabs build scripts, I was looking into moving mabs over from one build system to another. All is well with that, except for having to choose between either dropping mruby support, or making that run through Waf instead. Would be nice if the mruby branch were to include Meson support too

**Comment by CounterPillow** [comment]
That branch is someone's experiment from 2017, I don't think anything will be added to it, nor should you run it.

**Comment by RivenSkaye** [comment]
The latest contribution by @pigoz I see is 2019, which is a while back as well at this point. Perhaps the branch would be best off getting pruned or be marked deprecated then?
To be fair, I do like the idea of ruby scripting, more than JS at least. I'll close this issue if the mabs team is OK with removing support for building it, or if a decision is made wrt the branch in this repo

**Comment by sfan5** [comment]
You should definitely be dropping ruby "support", nobody ever said this branch was official. I agree we have too many random ones though.

**Comment by pigoz** [comment]
@RivenSkaye there's no reason for mruby anymore

Years ago I rewrote `ruby-mpv`. I never had the patience to go through with the upstreaming process, and I'm still undecided about a decent api to deal with generating Ass strings.

Anyway you can get my work here: https://github.com/woodruffw/ruby-mpv/pull/3
