### ISSUE TITLE
"tone-mapping=linear" shows total blackness with gpu-next

### ISSUE THREAD

**Issue by jiangzhenjerry** [mpv-player/mpv#11076]
### Important Information

Provide following Information:
- mpv version: Currently [mpv-x86_64-v3-20230101-git-ad65c88.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20230101-git-ad65c88.7z/download). However, this issue begins with [mpv-x86_64-v3-20221106-git-2590651.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20221106-git-2590651.7z/download). Binaries prior to 20221106 work fine.
- Platform and Version: Windows 11 x64
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/

### Reproduction steps

Open any HDR video file with `mpv --vo=gpu-next --tone-mapping=linear`

### Expected behavior

Video should play normally (even though `linear` is not a desirable algorithm).

### Actual behavior

The video is completely black. Nothing can be seen. The file is being played though, as audio can be heard. Other tone-mapping algorithms work fine.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/10329664/output.txt)

### Sample files

N/A. Any HDR video file can do.

**Comment by quietvoid** [comment]
Bisected to commit https://github.com/haasn/libplacebo/commit/43848586370223c99f3d32559f806e81a00ef8b2 for me.
It works before that, and works in `plplay`.

**Comment by quietvoid** [comment]
The fix seems to be something like this
```diff
diff --git a/video/out/vo_gpu_next.c b/video/out/vo_gpu_next.c
index bbce4f2065..caad82b037 100644
--- a/video/out/vo_gpu_next.c
+++ b/video/out/vo_gpu_next.c
@@ -1770,7 +1770,7 @@ static void update_render_options(struct vo *vo)
     p->color_map.tone_mapping_crosstalk = opts->tone_map.crosstalk;
     p->color_map.tone_mapping_mode = tone_map_modes[opts->tone_map.mode];
     if (isnan(p->color_map.tone_mapping_param)) // vo_gpu compatibility
-        p->color_map.tone_mapping_param = 0.0;
+        p->color_map.tone_mapping_param = p->color_map.tone_mapping_function->param_def;
     if (opts->tone_map.gamut_mode != GAMUT_AUTO)
         p->color_map.gamut_mode = gamut_modes[opts->tone_map.gamut_mode];
 
```
