### ISSUE TITLE
[umpv script] Don't recognize quotes when using MPV enviroment variable

### ISSUE THREAD

**Issue by sun95n** [mpv-player/mpv#11089]
Hi. I add [quoting options](https://mpv.io/manual/stable/#escaping-spaces-and-other-special-characters) to [umpv](https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv) just avoiding `''` when editing the script on line [83](https://github.com/mpv-player/mpv/blob/aa8ddfcdf30c4ffb38f3ec5d6663bbabf0b7b4df/TOOLS/umpv#L83).

```
    opts = (os.getenv("MPV") or "mpv").split()
    opts.extend(["--no-terminal", "--force-window", "--input-ipc-server=" + SOCK,
                 "--title=Custom Title With Spaces", "--"])
```
![001](https://user-images.githubusercontent.com/120290802/210462292-c9ea4879-4330-4bf6-853d-e00cb03976df.png)

However if I want to use the [MPV enviroment variable](https://github.com/mpv-player/mpv/blob/aa8ddfcdf30c4ffb38f3ec5d6663bbabf0b7b4df/TOOLS/umpv#L22-L26) i.e. `env MPV='mpv --title=Custom Title With Spaces' umpv File or URL` the behavior is not the same. Note how the title is now split into play entries or `\` and `/` in URLs

![002](https://user-images.githubusercontent.com/120290802/210462269-9e55468a-b88d-45f2-ac75-3b17402dfeed.png)

![32](https://user-images.githubusercontent.com/120290802/210463215-ee287441-e903-432a-8c43-0c0c16ab189f.jpg)

Maybe it could be fixed if `$MPV` didn't split whitespace regardless of quotes but I don't know how to do it. Somebody could help me?
https://github.com/mpv-player/mpv/blob/aa8ddfcdf30c4ffb38f3ec5d6663bbabf0b7b4df/TOOLS/umpv#L81

**Comment by sfan5** [comment]
The solution is [`shlex.split()`](https://docs.python.org/3/library/shlex.html#shlex.split).

**Comment by llyyr** [comment]
`import shlex` then replace opts with `opts = shlex.split((os.getenv("MPV") or "mpv"))`

**Comment by sfan5** [comment]
This is working as designed, the `MPV` variable is for static options that don't change.
Such an usecase is difficult to support in umpv.
