### ISSUE TITLE
Accept webdav:// and webdavs:// urls as an alias for http:// and https://

### ISSUE THREAD

**Issue by kbios** [mpv-player/mpv#11080]
### Expected behavior of the wanted feature

Simply treat webdav:// like http:// and webdavs:// like https:// (This works because webdav is a superset of http)

This would be very useful when using eg dolphin to browse a webdav archive and opening a video from there.

It would allow to add webdav to X-KDE-Protocols in mpv.desktop and thus prevent kio from downloading the whole video before passing it to mpv (which can take several minutes for big files and leaves the user wondering why mpv doesn't open).

**Comment by EzeKees** [comment]
Solution for this?: https://github.com/mpv-player/mpv/issues/10189
