### ISSUE TITLE
Force yuv420p10 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#11094]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hey I was wondering if there is a way to force 10bit hdr video to play at yuv420p10 It only seems to play with yuv420

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by CounterPillow** [comment]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

**Comment by jeeb** [comment]
This doesn't have any context. If a decoder outputs the image as 8bit YCbCr, then generally it means that it can't output 10bit YCbCr with whatever you're feeding it? If there is such capability, it should be a change on the decoder side.
