### ISSUE TITLE
Why does MPV need so many threads?

### ISSUE THREAD

**Issue by StratusFearMe21** [mpv-player/mpv#11092]
As a Rust developer, my knowledge of threads is that if you spawn more threads than your CPU has cores (`$(nrpoc)`), then the performance of you program will suffer. However, MPV seems to spawn *way* more threads than that. With the default options (no `mpv.conf`), and 2 C-Plugins, `htop` said mpv was using 32 threads just to play a simple MP4 video. I understand from developing my own plugin that mpv spawns plugins in a seperate thread, and by disabling `lua` and using `vo=dmabuf-wayland`, I was able to get the number down to 15. But that's still nearly twice the actual amount of CPU cores on my machine (8). So what I'm asking is
- What is mpv using so many threads for?
- Is the performance of mpv impacted by spawning all these threads?
- Besides disabling `lua` and using `vo=dmabuf-wayland`, are there more ways to bring the thread count down?

Thanks in advance for answering :smile:!

**Comment by LaserEyess** [comment]
1. mpv creates a threadpool when starting and uses that for various blocking operations. It is not actually using all of these threads, but they exist in the background for asynchronously running functions (such as lua scripts) and loading files. 

2. Considering it's just an idle threadpool and takes milliseconds to create, I doubt it has a performance impact. Never really tested it.

3. Considering you don't know what these threads are doing, I don't think that's a good idea.

**Comment by maxdunbar** [comment]
Adding to @LaserEyess you can find more information on [thread_pool.c](https://github.com/mpv-player/mpv/blob/8bd0dee531e3dfbc076bc06ab9c2ea0e3b4e2419/misc/thread_pool.c).

also nice planet profile picture :)

**Comment by StratusFearMe21** [comment]
For people in the future who want the answer to this question, I found the answer

This command shows what `mpv` is using it's threads for
```sh
ps -T -p $(pidof mpv)
```
```
    PID    SPID TTY          TIME CMD
  35684   35684 pts/0    00:00:00 mpv
  35684   35685 pts/0    00:00:00 mpv/terminal
  35684   35686 pts/0    00:00:00 mpv/lua script
  35684   35687 pts/0    00:00:00 mpv/lua script
  35684   35688 pts/0    00:00:00 mpv/lua script
  35684   35689 pts/0    00:00:00 mpv/lua script
  35684   35691 pts/0    00:00:00 mpv/SO plugin (
  35684   35692 pts/0    00:00:00 mpv/SO plugin (
  35684   35693 pts/0    00:00:00 mpv/lua script
  35684   35694 pts/0    00:00:00 gmain
  35684   35695 pts/0    00:00:00 pool
  35684   35696 pts/0    00:00:00 gdbus
  35684   35698 pts/0    00:00:00 mpv/demux
  35684   35699 pts/0    00:00:00 mpv/worker
  35684   35700 pts/0    00:00:00 mpv/vo
  35684   35701 pts/0    00:00:00 mpv:cs0
  35684   35702 pts/0    00:00:00 mpv:disk$0
  35684   35703 pts/0    00:00:00 mpv:sh0
  35684   35704 pts/0    00:00:00 mpv:shlo0
  35684   35705 pts/0    00:00:00 mpv:sh1
  35684   35706 pts/0    00:00:00 mpv:sh2
  35684   35707 pts/0    00:00:00 mpv:sh3
  35684   35708 pts/0    00:00:00 mpv:sh4
  35684   35709 pts/0    00:00:00 ao-pipewire
  35684   35710 pts/0    00:00:00 mpv
```

This command, minus 1, shows the number of threads that `mpv` is using
```sh
ps -T -p $(pidof mpv) | wc -l
```
```
25
```
So in this case, `mpv` is using 24 threads

**Comment by sfan5** [comment]
FYI 8 of those threads are created by your video driver and 5 are probably (in)directly created by C plugins, mpv does not ship with any.
