### ISSUE TITLE
cache-on-disk and cache-dir broken

### ISSUE THREAD

**Issue by meidoqt** [mpv-player/mpv#11097]
### Important Information

- mpv version: mpv-x86_64-20230101-git-ad65c88
- windows version: Windows 10 22H2 OS Build 19045.2364
- build source: shinchiro windows builds
- problem introduced with: mpv-x86_64-20221225-git-cb15bc4

### Reproduction steps

- try opening a file or network location with --no-config --cache=yes --cache-on-disk=yes --cache-dir=D:\cache\mpv

### Expected behavior

- files, network locations open normally and use disk cache

### Actual behavior

- files do not open at all, network locations will sometimes open but never use disk cache
- [   1.751][e][timeline] Failed to read cache file: Invalid argument
[   1.751][e][timeline] Failed to retrieve packet from cache.
[   1.752][e][timeline] Failed to read cache file: Invalid argument
[   1.752][e][timeline] Failed to retrieve packet from cache.

### Log file

- [cache.txt](https://github.com/mpv-player/mpv/files/10359946/cache.txt)

**Comment by philipl** [comment]
Can confirm. It is a regression in cb15bc4324327bded956b2c9b78f09bdc2729d98. Will need to investigate why.
