### ISSUE TITLE
codebase question: how do you add a custom video format ?

### ISSUE THREAD

**Issue by TruncatedDinosour** [mpv-player/mpv#11090]
hello mpv devs,

i want to add a custom video format in my local installation of mpv,
i wanna see how it behaves and maybe eventually contribute, although
i am lost in the codebase, ive been grepping through the codebase for
around half an hour and im getting bored of it, so i thought id ask here,
how to i add a custom format, tried grepping for for example `mp4` and stuff
and barely found anything useful, the most useful thing i found is `demux/demux_mf.c` but even then it barely got me anywhere

where do i start looking ? any help is greatly appreciated :)

**Comment by thebombzen** [comment]
You're better off adding it to FFmpeg, which mpv uses to demux and decode most of the formats it can read.

**Comment by TruncatedDinosour** [comment]
> You're better off adding it to FFmpeg, which mpv uses to demux and decode most of the formats it can read.

ah, okay, ill see what can i do :) thanks !
