### ISSUE TITLE
mpv fails to start: VT_GETMODE failed: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by Nekotekina** [mpv-player/mpv#11103]
### Important Information

Provide following Information:
- mpv version: From git bisect, the issue begins with commit 3d459832a88a9bd2835b339cf6ca98f84aad0115
- Linux Distribution and Version: Ubuntu 22.04.1 LTS
- Source of the mpv binary: self-built from git
- Window Manager and version: GNOME 42.5 on X11
- GPU driver and version: amdgpu; AMD Radeon RX 5500 XT (navi14, LLVM 15.0.6, DRM 3.42, 5.15.0-57-generic) (0x7340) Version: 22.3.2

### Reproduction steps

Start any video.

### Actual behavior

MPV fails to start.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/10366021/output.txt)

**Comment by avih** [comment]
> * mpv version: From git bisect, the issue begins with commit [3d45983](https://github.com/mpv-player/mpv/commit/3d459832a88a9bd2835b339cf6ca98f84aad0115)

Like the commit message suggests, mpv now requires the xorg extension xpresent, which you probably didn't have when building mpv, hence your mpv is without xorg/x11 support, hence this issue.

If that is wrong, pleae request to re-open.

**Comment by CounterPillow** [comment]
in other words, install `libxpresent-dev`.

**Comment by avih** [comment]
> Like the commit message suggests, mpv now requires the xorg extension xpresent

Aactually, is says "support xpresent" but it should have said "require xpresent".

Let that be a lesson to write good commit messages.

**Comment by jeeb** [comment]
Also one thing that is recommended is explicitly enabling those features/functionality that you require, that way such failures would appear already at the configuration stage, rather than runtime behavior being different than expected (`--enable-x11` with waf or I think `-Dx11=enabled` with meson).
