### ISSUE TITLE
screenshot-template setting not working while used in mpv.conf 

### ISSUE THREAD

**Issue by yolevtop** [mpv-player/mpv#11106]
- mpv version: mpv-x86_64-20230101-git-ad65c88
- Windows Version: Windows 10 Home 21H2 build 19044.2364
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/

### Reproduction steps

My mpv.conf file looks like this:
screenshot-format=png
screenshot-template=%p
screenshot-directory=C:\mpv

The settings in lines 1 and 3 apply successfully, however screenshot-template doesn't work from the mpv.conf file.
I tried using screenshot-template in the command line, and it worked just fine.

### Expected behavior

Output of a screenshot file named according to %p template, i.e the file name should look like this: 01_11_38.png

Docs reference: https://mpv.io/manual/master/#options-screenshot-template

### Actual behavior

The file name looks like this instead: mpv-shot0001.png

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/10366998/output.txt)

### Sample files

Not necessary for this issue

**Comment by hooke007** [comment]
It should be `screenshot-template="%p"`

**Comment by hooke007** [comment]
ref your log
```
[   0.005][e][cplayer] C:/mpv/mpv/mpv.conf:2: fixed-length quoting expected - put "quotes" around the option value if you did not intend to use this, but your option value starts with '%'
```
