### ISSUE TITLE
MPV Bad Perfomance  with Increased Speed If I do not use --vo=x11 or xv flag

### ISSUE THREAD

**Issue by toprak** [mpv-player/mpv#11101]
### Important Information
I was using --xo=gpu because it came by default, but when I sped up the videos, the videos were very slow, so I thought I would play with the flags a bit, xv and x11 were running fast, but hw acc. was not working in both, while it should work in xv.
EDIT: adding --hdr-compute-peak=no improved perf. any flags like that?
Provide following Information:
- mpv version = 0.35
- Linux Distribution and Version Arch Linux 6.1.3
- Source of the mpv binary Arch Linux Repo
- If known which version of mpv introduced the problem
- Window Manager and version i3wm 4.22
- GPU driver and version libva-intel-driver-2.4.1-2 mesa-amber-21.3.9-3
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
mpv --vo=xv --vd-lavc-dr=no --profile=sw-fast youtube-videos.m3u

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
works fast
### Actual behavior
stuttered videos
### Log file
[output.txt](https://github.com/mpv-player/mpv/files/10365378/output.txt)

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
Try `--vd-lavc-dr=no`
