### ISSUE TITLE
How do I make mpv default srt settings somewhat similar to Netflix's?

### ISSUE THREAD

**Issue by BhaturaGuy** [mpv-player/mpv#11104]
I can't seem get mpv to display srt subs like Netflix's.
`{\be5\3a&H96&}` in aegisub with black border brings the output similar to netflix's, but I am not able to work this around in mpv since it doesn't support ass tags(?)
![image](https://user-images.githubusercontent.com/93109835/211149401-eca5cb36-4007-4f02-bb49-6172cac8859a.png)

**Comment by thebombzen** [comment]
Does `--sub-ass-styles=` solve your problem?

**Comment by garoto** [comment]
.srt subs can't be styled by ASS tags AFAIK, but there are _PLENTY_ of plaintext sub customizations provided.
