### ISSUE TITLE
How to force libmpv to ouput to HDMI instread of LCD at Ubuntu ?

### ISSUE THREAD

**Issue by trump-7575** [mpv-player/mpv#11105]
mpv version 0.34.1
libmpv version : 0.34.1 ( /usr/include/mpv/client.h : 1.109 )
Linux Distribution and Version : Ubuntu 22.04 LTS
Source of the mpv binary : from ubuntu official respository
If known which version of mpv introduced the problem : unknown
Window Manager and version : Gnome( Wayland )
GPU driver and version : not-avail.

### Log file

...
[vo/gpu/wayland] Registered output LCD_NAME
...

[vo/gpu/wayland] Registered output HDMI_MONITOR_NAME
...
[vo/gpu/wayland] Surface entered output HDMI_MONITOR_NAME
...
====================================================
My pc has two display outputs : LCD and HDMI . When I write C/C++ codes with libmpv at Ubuntu 22.04 , I encounter the problem of choosing the right output device : 
 mpv_set_option_string(ctx, "fs-screen" , "0"   );

As you konw , the above fs-screen number may change automatically . Is it possible to list all of the fs-screen-name  with libmpv so that my program can make a judgement ?

**Comment by Dudemanguy** [comment]
>Is it possible to list all of the fs-screen-name with libmpv so that my program can make a judgement ?

Right now, this isn't possible. There's no property that lists the names of all the available displays although potentially this isn't a bad idea. For your use case, it would still be a difficult problem though since there's no way for mpv to know these things without connecting to the display server and actually making a window. Your best bet is probably to code up something to detect these things before starting the mpv ctx.

**Comment by trump-7575** [comment]
mpv  doesnot has this problem at all because I chose the display output via Ubuntu's setting/display control panel. Is it possible for libmpv to check Ubuntu or mpv's setting about this ?

**Comment by Dudemanguy** [comment]
I don't understand. If you are using a setting in the desktop environment to force an application to start on a certain display, then just do that for whatever you are coding with libmpv if that solution is satisfactory to you.

**Comment by trump-7575** [comment]
Maybe my question should be : how to make libmpv respect Ubuntu or Mpv's display output setting instead of hard-code a device name/number at the program ?

**Comment by Dudemanguy** [comment]
There are quite a few different things going on here so let's try to clarify.

I'm not sure what you mean by "mpv's display output setting". By default, there is none. Of course, there are options like `--screen` and `--fs-screen` that influence where mpv may place itself, but the default is nothing. Wherever mpv appears depends on your OS, compositor settings, etc. A libmpv application should be exactly the same in this regard.

As for "Ubuntu's setting", I presume you just mean GNOME. I don't use this myself, but I assume you can just pick an application in the menu somewhere to make it start on a certain display. Just choose whatever application you are making with mpv. I'm not sure what's different here.

**Comment by trump-7575** [comment]
The nature of my quesiton is about the missing setting at libmpv to check Ubuntu's display output setting. 

As I mentioned earlier , Ubuntu provide a display control panel ( setting ) to allow user to choose the primary display output. Afterward , mpv automatically show video at that output.  But this is not the case of libmpv .  At first , I didnot notice this problem.  But sometimes , I found out my program written with libmpv "doesnot work" .  In fact , my program shows video at another display output which is not visible.

So I turned to assigning the fs-screen or screen  with libmpv. Obvisiouly this is not a good idea.  Is there any setting or codes to check the Ubuntu's setting with libmpv  as mpv does?

**Comment by Dudemanguy** [comment]
mpv does not "check Ubuntu's display output setting". The compositor just chooses where to place the window (or window manager if you're using x11). We have no special code for this. libmpv is just mpv compiled as a library, so I'm fairly certain that a simple libmpv example would work the same way.
