### ISSUE TITLE
configure failed on OS X with LuaJIT and workaround

### ISSUE THREAD

**Issue by 191919** [mpv-player/mpv#1110]
`./waf configure` failed on my OS X 10.9.4 with luajit-2.0.3.

The workaround is to configure with the following command line:

`LDFLAGS="-pagezero_size 10000 -image_base 100000000" ./waf configure --lua=luajit`

It is a LuaJIT issue when running on 64-bit OS X and is documented in http://luajit.org/install.html .

> If you're building a 64 bit application on OSX which links directly or indirectly against LuaJIT, you need  to link your main executable with these flags:
> 
> `-pagezero_size 10000 -image_base 100000000`
> 
> Also, it's recommended to rebase all (self-compiled) shared libraries which are loaded at runtime on OSX/x64 (e.g. C extension modules for Lua). See: man rebase

**Comment by Argon-** [comment]
For reference: brew installed luajit does provide these flags now and compilation works so this is no longer an issue.  

    # Package information for LuaJIT to be used by pkg-config.
    majver=2
    minver=0
    relver=5
    version=${majver}.${minver}.${relver}
    abiver=5.1
    
    prefix=/usr/local/Cellar/luajit/2.0.5
    multilib=lib
    exec_prefix=${prefix}
    libdir=${exec_prefix}/${multilib}
    libname=luajit-${abiver}
    includedir=${prefix}/include/luajit-${majver}.${minver}
    
    INSTALL_LMOD=/usr/local/share/lua/${abiver}
    INSTALL_CMOD=/usr/local/${multilib}/lua/${abiver}
    
    Name: LuaJIT
    Description: Just-in-time compiler for Lua
    URL: http://luajit.org
    Version: ${version}
    Requires:
    Libs: -pagezero_size 10000 -image_base 100000000 -L${libdir} -l${libname}
    Libs.private: -Wl,-E -lm -ldl
    Cflags: -I${includedir}

(However, it still doesn't work as mpv fails to initialize it for reasons I don't know yet.)
