### ISSUE TITLE
Running mpv with multiple videos, each with its own audio/subtitles files

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#11102]
When launching mpv with multiple videos, you can elegantly press `<` and `>` to jump between videos:

`$ mpv video-1.mp4 video-2.mp4 video-3.mp4`

But when you have separate audio and subtitles files, and possibly also other separate things that should change per video, the only way I know is to restart mpv for each item, causing a delay for exit and relaunch, the window respositions, etc.

```
for f in {1..9}; do 
  mpv video-$f.mp4 --audio-file=audio-$f.mp4 --sub-file=sub-$f.mp4 --force-media-title="Title $f" --foo=bar-$f
done
```

Is there a way to use playlists etc. to make this work within a single mpv launch, eg.

```
$ cat foo
[
{video: "video1", audio: "audio1"},
{video: "video2", audio: "audio2"},
...
]
$ mpv --playlist=foo
```

**Comment by avih** [comment]
https://mpv.io/manual/master/#per-file-options

**Comment by forthrin** [comment]
@avih: Ah! Thanks! Didn't find this in the manual or the issue tracker, because I didn't guess the right thing to search for. Curly braces it is!
