### ISSUE TITLE
mpv, Discord Live Sharing and sound

### ISSUE THREAD

**Issue by whitebear60** [mpv-player/mpv#11100]
### Important Information

Provide following Information:
- mpv version: mpv 0.35.0-76-g3a6ef81705 built on Fri Jan  6 20:34:57 EET 2023
- macOS Version: Ventura 13.0.1
- Source of the mpv binary or bundle: built with mpv-build
- If known which version of mpv introduced the problem: any 0.35.0 that I've used for about half a year (haven't used mpv before)
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

When ran from terminal, looks like mpv puts sound through terminal, as when I enable Discord's Live Sharing of mpv window that is running from terminal, no sound plays on other side, when screensharing terminal window from which mpv is running, the sound which is produced by mpv, plays.
When ran from *.app (to be more explicit, that which is currently in Homebrew Cask), for example, when playing the file with double-click from Finder, when screensharing through Discord, the sound is playing normally.

To reproduce:
- Run mpv from terminal (for example, `mpv file.mp4`
- Try to screenshare mpv's window in Discord. The sound on the other side shouldn't play
- Try screensharing in Discord the Terminal window from which mpv is running. Now, the sound from mpv should play
- Run mpv (compiled as *.app) from Finder (for example, by double-clicking the video file in Finder, if file associations are configured to open video in mpv)
- Try screensharing in Discord the mpv's window now. The sound should play normally.

### Expected behavior
The sound should share normally both when mpv is running from Terminal, and from *.app from Finder

### Actual behavior
The sound shares normally only when mpv is running from *.app from Finder, when mpv is running from Terminal, the sound is playing through the Terminal window

### Log file
[mpv-log.log](https://github.com/mpv-player/mpv/files/10362569/mpv-log.log)

### Sample files

It seems that this does not depend on what video file is playing

**Comment by whitebear60** [comment]
Hope that you can understand what I wrote, as my English is not ideal... Feel free to ask me if something remains unclear.

**Comment by fizzxed** [comment]
I've also noticed and confirmed the same behavior on

- M2 macOS Ventura 13.3.1
- mpv 0.36.0

It's not really a huge issue, but something to remember when I usually start mpv from command line

**Comment by Akemi** [comment]
i just tested this myself and in both cases, launched via terminal and app bundle, sharing with sound works as expected. maybe discord fixed the problem or it was an OS problem, though it works now.

[original comment]
for now i think this might be expected and discord fetches the wrong audio. the app ist launched from launchd (parent process), which handles launching all apps. when started from the terminal mpv is launched by zsh (or your shell) and it is also its parent process.

mpv app: kernel_task(0) > launchd (1) > mpv
terminal: kernel_task(0) > launchd (1) > Terminal > zsh > mpv
