### ISSUE TITLE
[input] No key binding found for 'Ctrl +='

### ISSUE THREAD

**Issue by ShiroYasha139** [mpv-player/mpv#11117]
I have a video with some audio sync issues so I tried looking for a shortcut, CTRL - works for - ms delay but CTRL + doesn't work for +ms delay

### Important Information

Provide following Information:
- mpv version: mpv 0.35.0-86-g8439c084e1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
- Linux Distribution and Version: Endeavour OS x64
- Source of the mpv binary: AUR (mpv-git)
- If known which version of mpv introduced the problem- Don't know
- Window Manager and version: KWin version: 5.26.5
- GPU driver and version: amdgpu (mesa)
- Possible screenshot or video of visual glitches:  
![image](https://user-images.githubusercontent.com/103560009/211315983-768b4c16-a506-431a-b377-c271951c01a4.png)

### Reproduction steps

- Open any video file
- Press Ctrl +

I have tried using ```--no-config``` but it produced the same result

### Expected behavior
Adjust audio sync by +0.1s when key is pressed 
### Actual behavior
No keybind found
### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

https://0x0.st/o7NU.txt

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by avih** [comment]
> * Press Ctrl +
> [input] No key binding found for 'Ctrl +='

Looks you're pressing control and equal, not control and plus.

At least on my keyboard, the =/+ button is = without shift, and + with shift, so to press control and plus, you need to hold shift too.

If you want, you can add to your input.conf:
```
ctrl+= add audio-delay 0.100
```

So tha control and equal has the same function as control and plus.
You can see the default bindings here https://github.com/mpv-player/mpv/blob/master/etc/input.conf

**Comment by ShiroYasha139** [comment]
> > * Press Ctrl +
> >   [input] No key binding found for 'Ctrl +='
> 
> Looks like you're pressing control and equal, not control and plus.
> 
> At least on my keyboard, the =/+ button is = without shift, and + with shift, so to press control and plus, you need to hold shift too.
> 
> If you want, you can add to your input.conf:
> 
> ```
> ctrl+= add audio-delay 0.100
> ```
> 
> So that control and equal has the same function as control and plus. You can see the default bindings here https://github.com/mpv-player/mpv/blob/master/etc/input.conf
I have a 14inch laptop so no numpad keys there and I have to use the key  =+  in combination with CTRL for using + and using CTRL with it works everywhere.  -0.1s was working with CTRL - and not the same with CTRL +. Kind of weird
But adding that to my input.conf worked. Thank you. And the default bindings will help me in future too. Thanks!
