### ISSUE TITLE
v0.35.1 plans

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#11111]
We have a few regressions and also a bunch of other fixes, so a point release would be good.

Here's a list:
* d8fbe3c79f5f68b597c51f339a3f45ce3dd9b926
* 295ceab3820b07ad92f95f318b102fec957dd4e3
* d3a61cfe9844b78362bfce6e5a8280ad6514dbce
* 8327ac3e6d1686dd753b0ee23f135ebaa13af1b6
* f10b24e3c5c76756544830f2a9ef192f55a7dcdb
* 04f765da6fb407c7ebe1833403a6049e2c9df6ce
* b9b3342369c3e58f9fbb4c78dedbf3418a1ebd59
* e1a04cd8ac407cd188a9e6064677d232ae409e9c
* ead8469454afa63e6e1fdd9e978af765f89379ce
* 7eb8f81091008d4e90dfc758df27342a541327f3
* bca516bd2c282670aa2c92663329e7d5ddf978e0
* 11229e7f7177220dd1607625a3a1bfc9d34a5f51
* 2fa1e7d0b409f2ceb608d9b6c5d90106507595aa
* 64a7fd3a1268588b520b6d93820933b12dbcf650
* f2ba5fdfd3f25ca3443da55d5cfb836ee5035aa9
* f9d0b0c08a35e67976a8c71ac16a832781c2313a
* 27dab30209d60f96afcf679d602c32ca02aed445
* 3447463008cc940a13d0787f8533503c3fbfbb58
* 7614e68233a0db1803f807afd47a52c66b4ebb3a
* ad65c8855b60df3c95026ee7b315eca31c59f3bc
* 39f7f83351524cdbd87c5ae420b838530314b525
* 2e9c43f9318d416fc26f20aa55841ee7fcfeee4a
* fee6847aa7dfea721ef217824100eebfd0d7aa26
* d1d2370d073e9b70a181696e57075545b4802517
* 4bbb1ccfd75aa5f2a5d4674d86433d334b9f22c8
* c153eb7d01508a3cd21f3e90cf7e00ad15b3a5d3
* 3a6ef8170551e8eab9ef89143db04e2e0d7ec567
* 96773f39e17f59bcf6bb383e521853aea19c8177
* e43393c4da0c72dd974cc5ff08952f7614b3958f
* 356096b9546e93456cab799f7634fc4f89952202
* 95a76f069204946a7e1cd263810c2f170f6fe0e5
* 9a9039deb25c4e3e189f3963b60b2108d35de0f8
* 6cdce9e18e4cd199c1342db6e6d1db03828ad860
* 8c617765fe88a5d5597fb58d4b593161049de710
* f8c17f55f975ea3b46ba7cea299f1a8e5d980b4c ＊
* c7ea0cd68f2cd68edea2f64060c1bcb483005a50 ＊
* 2531a89fcb93d7c7578cec4c5536c37244f08d39 ＊
* 9b59d39a3ab64da0e9489ee4ce2062d4503e7cc5 ＊
* 0d44ae319dfd5209eb0733caafdcbcf67d228cf3

**Comment by t-8ch** [comment]
https://github.com/mpv-player/mpv/commit/b5373079f20aeeba8ac80e773f3cc05692dbb51f is broken and got reverted on `master`. Please drop it.

**Comment by Dudemanguy** [comment]
More wayland presentation fixes that should go in: 4bbb1ccfd75aa5f2a5d4674d86433d334b9f22c8 and aa8ddfcdf30c4ffb38f3ec5d6663bbabf0b7b4df

Not a fix or anything but it makes my life easier when looking at user logs: d3a61cfe9844b78362bfce6e5a8280ad6514dbce

**Comment by t-8ch** [comment]
https://github.com/mpv-player/mpv/commit/7eb8f81091008d4e90dfc758df27342a541327f3 and https://github.com/mpv-player/mpv/commit/d8fbe3c79f5f68b597c51f339a3f45ce3dd9b926 would also be nice for user logs

**Comment by EzeKees** [comment]
Solution for this?: https://github.com/mpv-player/mpv/issues/10189
