### ISSUE TITLE
Best HDR to SDR tonemap settings for vo=gpu

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#11116]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I was wondering if anyone could provide me with what they think are the best tonemapping options to use for hdr for vo=gpu for the most accurate for the best way of retaining most of the hdr colours and colour accuracy 
Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by Jamie666123** [comment]
New to the whole tonemapping thing was just wondering the best options for retaining hdr colour and the best hdr colour accuracy

**Comment by Natural-Harmonia-Gropius** [comment]
It depends on the content creator's color grading, there is no ultimate answer.
