### ISSUE TITLE
Is there a way to force scaled resolution to be only divisible by 2?

### ISSUE THREAD

**Issue by elexor** [mpv-player/mpv#11127]
Sometimes mpv will scale video to a vertical or horizontal resolution that's not divisible by 2.

Why does this matter? it's breaks vapoursynth compatibility, many things won't work in a vapoursynth script with a resolution like 853x480.

Is there a way to round to the nearest divisible resolution? partial fix is disabling aspect ratio handling in the config file with video-aspect-override=0

**Comment by thebombzen** [comment]
What happens if you insert a scale filter using something like `-2:480`?

**Comment by elexor** [comment]
do you mean like this? vf=scale=-2:480,vapoursynth=filter.vpy doesn't do anything still 720x480 => 853x480

vf=scale=854:480,vapoursynth=filter.vpy works, but I'm looking for something automatic that will work with any video I might encounter.
