### ISSUE TITLE
`--vo=gpu-next --hwdec=mediacodec` results in solid purple screen

### ISSUE THREAD

**Issue by StratusFearMe21** [mpv-player/mpv#11125]
### Important Information

- mpv version
    - [`mpv` git commit `05bc366d18c72e94ee07448e2cfa28102e9c0766`](https://github.com/mpv-player/mpv/commit/05bc366d18c72e94ee07448e2cfa28102e9c0766)
- Platform and Version
    - [`mpv-android` git commit `1ced83d345cad18d468486b21462aa96ede40aa9`](https://github.com/mpv-android/mpv-android/commit/1ced83d345cad18d468486b21462aa96ede40aa9)
    - Built with `libplacebo` [(this commit)](https://code.videolan.org/videolan/libplacebo/-/commit/d0f2e68bde5ba89097f4f698606eb9033b909357)  linked to `libmpv.so`
- Source of the mpv binary
    - Built from source from git using `mpv-android` build scripts

### Reproduction steps

- [Install my APK](https://0x0.st/o71z.apk) which includes `libplacebo`
    - Alternatively, compile [this branch](https://github.com/StratusFearMe21/mpv-android/tree/libplacebo) of `mpv-android` from source
- Go to `Settings>Advanced>Edit mpv.conf`
- Add this line
```
vo=gpu-next
```
- Play a video
- Turn on software decoding, notice that it works now

### Expected behavior

The video plays like how `vo=gpu` would with hardware decoding turned on

### Actual behavior

A solid purple screen is shown. The video is still playing, and the audio still works, but the screen is purple

![Screenshot_20230110_230736_mpv.png](https://user-images.githubusercontent.com/57533634/211715653-80e533b0-4152-4a20-87d0-0949ee68bbd9.png)

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/10388779/log.txt)

**Comment by sfan5** [comment]
This part could be wrong, pretty sure it works on vo_gpu tho.
https://github.com/mpv-player/mpv/blob/865a159244d27ccbb537c5c734a93f86d22f9149/video/out/hwdec/hwdec_aimagereader.c#L143-L151

**Comment by StratusFearMe21** [comment]
I think it could also be because the `vo` just never reads any variable with the name `glsl_extensions`
```
./deps/mpv/video/out/hwdec/hwdec_aimagereader.c:148:        hw->glsl_extensions = es3_exts;
./deps/mpv/video/out/hwdec/hwdec_aimagereader.c:150:        hw->glsl_extensions = es2_exts;
./deps/mpv/video/out/gpu/hwdec.h:44:    const char **glsl_extensions;
./deps/mpv/video/out/gpu/video.c:903:        const char **exts = hwdec->glsl_extensions;
./deps/mpv/video/out/opengl/hwdec_d3d11egl.c:140:    hw->glsl_extensions = gl->es == 200 ? es2_exts : es3_exts;
```

**Comment by haasn** [comment]
Does this patch help?

```diff
diff --git a/video/out/vo_gpu_next.c b/video/out/vo_gpu_next.c
index e88f5c8f9f..386acc1400 100644
--- a/video/out/vo_gpu_next.c
+++ b/video/out/vo_gpu_next.c
@@ -495,6 +495,11 @@ static pl_tex hwdec_get_tex(struct priv *p, int n)
             .height = ratex->params.h,
         };
 
+        if (ratex->params.non_normalized)
+            par.target = GL_TEXTURE_RECTANGLE;
+        if (ratex->params.external_oes)
+            par.target = GL_TEXTURE_EXTERNAL_OES;
+
         ra_gl_get_format(ratex->params.format, &par.iformat,
                          &(GLenum){0}, &(GLenum){0});
         ra_gl_get_raw_tex(ra, ratex, &par.texture, &par.target);
```

It's not a full solution as I'm not sure why you sometimes randomly include `GL_OES_EGL_image_external_essl3` instead of `GL_OES_EGL_image_external`. I think I need to also include support for `GL_NV_EGL_stream_consumer_external` in libplacebo...

**Comment by haasn** [comment]
Possibly in conjunction with this patch:

```diff
diff --git a/src/dispatch.c b/src/dispatch.c
index 93007b8..55cde8b 100644
--- a/src/dispatch.c
+++ b/src/dispatch.c
@@ -374,8 +374,11 @@ static void generate_shaders(pl_dispatch dp, const struct generate_params *param
         ADD(pre, "#extension GL_ARB_shader_storage_buffer_object : enable\n");
     if (has_texel)
         ADD(pre, "#extension GL_ARB_texture_buffer_object : enable\n");
-    if (has_ext)
+    if (has_ext) {
+        if (gpu->glsl.gles && gpu->glsl.version >= 300)
+            ADD(pre, "#extension GL_OES_EGL_image_external_essl3 : enable\n");
         ADD(pre, "#extension GL_OES_EGL_image_external : enable\n");
+    }
     if (has_nofmt)
         ADD(pre, "#extension GL_EXT_shader_image_load_formatted : enable\n");
     if (has_gather)
```

**Comment by sfan5** [comment]
> I'm not sure why you sometimes randomly include `GL_OES_EGL_image_external_essl3` instead of `GL_OES_EGL_image_external`

The external oes stuff is a different extension in GLSL ES 1.0 (GLES 2.0) than in GLSL ES 3.x (GLES 3.x).

**Comment by haasn** [comment]
> > I'm not sure why you sometimes randomly include `GL_OES_EGL_image_external_essl3` instead of `GL_OES_EGL_image_external`
> 
> The external oes stuff is a different extension in GLSL ES 1.0 (GLES 2.0) than in GLSL ES 3.x (GLES 3.x).

According to the documentation of the `essl3` extension, it *depends* on the former. So I think correct would be to enable both.

Actually, because enabling a non-existant extension is a harmless warning, we might as well do this:

```c
    if (has_ext) {
        ADD(pre, "#extension GL_OES_EGL_image_external : enable\n");
        ADD(pre, "#extension GL_OES_EGL_image_external_essl3 : enable\n");
        ADD(pre, "#extension GL_NV_EGL_stream_consumer_external : enable\n");
    }
```

**Comment by haasn** [comment]
> Does this patch help?
> 
> ```diff
> diff --git a/video/out/vo_gpu_next.c b/video/out/vo_gpu_next.c
> index e88f5c8f9f..386acc1400 100644
> --- a/video/out/vo_gpu_next.c
> +++ b/video/out/vo_gpu_next.c
> @@ -495,6 +495,11 @@ static pl_tex hwdec_get_tex(struct priv *p, int n)
>              .height = ratex->params.h,
>          };
>  
> +        if (ratex->params.non_normalized)
> +            par.target = GL_TEXTURE_RECTANGLE;
> +        if (ratex->params.external_oes)
> +            par.target = GL_TEXTURE_EXTERNAL_OES;
> +
>          ra_gl_get_format(ratex->params.format, &par.iformat,
>                           &(GLenum){0}, &(GLenum){0});
>          ra_gl_get_raw_tex(ra, ratex, &par.texture, &par.target);
> ```
> 
> It's not a full solution as I'm not sure why you sometimes randomly include `GL_OES_EGL_image_external_essl3` instead of `GL_OES_EGL_image_external`. I think I need to also include support for `GL_NV_EGL_stream_consumer_external` in libplacebo...

Actually, this patch should not be needed, because we already set the right sampler target.

**Comment by jeeb** [comment]
> Possibly in conjunction with [this patch](https://code.videolan.org/videolan/libplacebo/-/merge_requests/343):
> 
> ```diff
> diff --git a/src/dispatch.c b/src/dispatch.c
> index 93007b8..55cde8b 100644
> --- a/src/dispatch.c
> +++ b/src/dispatch.c
> @@ -374,8 +374,11 @@ static void generate_shaders(pl_dispatch dp, const struct generate_params *param
>          ADD(pre, "#extension GL_ARB_shader_storage_buffer_object : enable\n");
>      if (has_texel)
>          ADD(pre, "#extension GL_ARB_texture_buffer_object : enable\n");
> -    if (has_ext)
> +    if (has_ext) {
> +        if (gpu->glsl.version >= 300)
> +            ADD(pre, "#extension GL_OES_EGL_image_external_essl3 : enable\n");
>          ADD(pre, "#extension GL_OES_EGL_image_external : enable\n");
> +    }
>      if (has_nofmt)
>          ADD(pre, "#extension GL_EXT_shader_image_load_formatted : enable\n");
>      if (has_gather)
> ```

Just built with this MR, and d3d11egl is now correctly able to work with `--hwdec=d3d11va --vo=gpu-next --gpu-context=angle`

**Comment by haasn** [comment]
Fixed by https://github.com/haasn/libplacebo/commit/87f052376194a8e30dab4cb65c3f23485f90f10a

**Comment by StratusFearMe21** [comment]
@haasn, can confirm this did fix the issue, thank you!

**Comment by StratusFearMe21** [comment]
This backend seems to initialize way faster then the gpu output on Android.
