### ISSUE TITLE
Subtitle files don't work with audio-only files

### ISSUE THREAD

**Issue by vbmvbm** [mpv-player/mpv#1112]
I don't know if I'm missing something, but I can't make mpv load subtitles with audio-only files. It shows 

```
[stream] Subs  (+) --sid=1 'myfilename.srt' (srt) (external)
```

but the subtitles are not shown. Is there any way to enable that? I don't care if the image shown is the album art (if present) or just a black screen, as long as the subtitles are shown.

Thanks

**Comment by bentley** [comment]
For a music file, is it possible to force subtitles to display in the terminal _without_ disabling cover art (`--no-audio-display`, etc.)?

**Comment by wm4** [comment]
No, there's currently no option to force this.

**Comment by lachs0r** [comment]
This appears to work fine now.
