### ISSUE TITLE
Libmpv doesnot respect Ubuntu's primary display setting

### ISSUE THREAD

**Issue by trump-7575** [mpv-player/mpv#11128]
- mpv version  :   0.34.1
- libmpv version : 0.34.1 ( /usr/include/mpv/client.h : 1.109 )
- Linux Distribution and Version  :  Ubuntu 22.04 LTS
- Source of the mpv binary  : from ubuntu official respository
- If known which version of mpv introduced the problem : unknown
- Window Manager and version  :  Gnome( Wayland )
- GPU driver and version :  not avail.
- Possible screenshot or video of visual glitches  : none

### Reproduction steps

just compile official example https://github.com/mpv-player/mpv-examples/blob/master/libmpv/simple/simple.c
with  log enabled : 
    mpv_set_option_string(ctx, "log-file", "mpv_log.txt");       
    mpv_request_log_messages(ctx, "v");

The keys to reproduce this issue :  
1. Your PC should has 2 display outputs . Please confirm it at Ubuntu's setting control panel . You should see 2 monitors ( marked with "1" and "2" ) side by side at setting/Displays
2. Choose monitor "2" as Primary Display . Choose "Join Displays" as display mode.
3.  Reboot your pc and try again. This issue happens randomly.

### Expected behavior
The built binary should show video at the Primay Display ( monitor "2" )

### Actual behavior
Sometimes , the built binary "doesnot work" . Only a mpv icon shows up at the docker( a section at ubuntu's desktop ) but no video.
If you check the mpv log file, you will find out the video is shown at the other display output with the following log : 
[v][vo/gpu/wayland] Surface entered output  monitor "1"
### Log file
...
[v][vo/gpu/wayland] Registered output monitor "1"
...
[v][vo/gpu/wayland] Registered output monitor "2"
...
[v][vo/gpu/wayland] Surface entered output  monitor "1"
...
### Sample files

Whatever video clip is fine.

=============================================================
Please note that mpv doesnot have this problem. Mpv always shows video at the Primary Display( monitor "2") . I know libmpv has commands "fs-screen"  and  "screen"  to choose the output displays . However , hard-code a device name/number is not a good idea at all. Is there any walk-around to fix this issue ?

**Comment by Dudemanguy** [comment]
Could you try updating to 0.35 if possible and then recompiling the example again? Lots of stuff changed under the hood there.
