### ISSUE TITLE
Use CPU instead of GPU?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#11129]
Is there any option to use the CPU instead of GPU?

**Comment by CounterPillow** [comment]
for which task exactly? Decoding? That's the default. Rendering? Either use a VO that isn't gpu, or set your OpenGL to use a software rendering driver

**Comment by Obegg** [comment]
For video decoding, but I would like to use ```gpu-next```, is it possible?

**Comment by hooke007** [comment]
> Decoding? That's the default. 

He had already answered your question.
