### ISSUE TITLE
vf-metadata not always filled with a graph filter

### ISSUE THREAD

**Issue by Ashyni** [mpv-player/mpv#11136]
### Important Information
- mpv 0.35.0-94-g865a159244
```
built on Thu Jan 12 04:55:10 2023
 libplacebo version: v5.234.0
 FFmpeg version: git-2023-01-12-f84de13d2
 FFmpeg library versions:
    libavutil       57.43.100
    libavcodec      59.56.100
    libavformat     59.35.100
    libswscale      6.8.112
    libavfilter     8.53.100
    libswresample   4.9.100
```
- Platform and Version: Windows 11
- Source of the mpv binary : shinchiro release

### Reproduction steps
vf-metadata.lua to test it.
```
local function collect_metadata(fn, data)
    if data then
        print(string.format("%s w=%s:h=%s:x=%s:y=%s", fn, data["lavfi.cropdetect.w"], data["lavfi.cropdetect.h"],
            data["lavfi.cropdetect.x"], data["lavfi.cropdetect.y"]))
    end
end

local function update_time_pos(fn, timestamp)
    collect_metadata("vf-metadata/lavfi.00", mp.get_property_native("vf-metadata/lavfi.00"))
end

local function cleanup()
    mp.msg.info("Cleanup.")
    mp.unobserve_property(collect_metadata)
    mp.unobserve_property(update_time_pos)
    mp.commandv("vf", "remove", "lavfi")
end

local function on_start()
    mp.msg.info("File loaded.")

    -- mp.commandv("vf", "add", "lavfi=[split[a][b];[b]cropdetect[b];[b][a]overlay]") -- works fine
    mp.commandv("vf", "add", "lavfi=[split[a][b];[b]cropdetect[b];[a][b]overlay]") -- fails

    mp.observe_property("vf-metadata/lavfi.00", "native", collect_metadata)
    mp.observe_property("time-pos", "number", update_time_pos)
end

mp.register_event("end-file", cleanup)
mp.register_event("file-loaded", on_start)
```

### Expected behavior
vf-metadata always filled if cropdetect can provide the metadata.

### Actual behavior
vf-metadata not always filled with a graph filter.
`lavfi=[cropdetect]` Works fine
`lavfi=[split[a][b];[b]cropdetect[b];[a][b]overlay]` Fails
`lavfi=[split[a][b];[b]cropdetect[b];[b][a]overlay]` Works fine
`lavfi=[split[a][b];[b]cropdetect[b];[a][b]mix]` Fails
`lavfi=[split[a][b];[b]cropdetect[b];[b][a]mix]` Fails
`lavfi=[split[a][b];[b]cropdetect[b];[a][b]hstack]` Fails
`lavfi=[split[a][b];[b]cropdetect[b];[b][a]hstack]` Fails

### Log file
`lavfi=[split[a][b];[b]cropdetect[b];[a][b]overlay]`:
```
[   1.397][v][ffmpeg] Parsed_cropdetect_1: x1:1919 x2:0 y1:1079 y2:0 w:-1904 h:-1072 x:1914 y:1078 pts:334000 t:0.334000 crop=-1904:-1072:1914:1078
[   1.430][i][vf_metadata] vf-metadata/lavfi.00 w=nil:h=nil:x=nil:y=nil
```
`lavfi=[split[a][b];[b]cropdetect[b];[b][a]overlay]`:
```
[   1.511][v][ffmpeg] Parsed_cropdetect_1: x1:1919 x2:0 y1:1079 y2:0 w:-1904 h:-1072 x:1914 y:1078 pts:500000 t:0.500000 crop=-1904:-1072:1914:1078
[   1.512][i][vf_metadata] vf-metadata/lavfi.00 w=-1904:h=-1072:x=1914:y=1078
```

**Comment by richardpl** [comment]
Not mpv issue.
There is no sensible way to pick conflicting metadata from several filters when you use filters that take more than single input.
What if both inputs provide cropdetect metadata? which one to pick then?

**Comment by Ashyni** [comment]
> Not mpv issue. There is no sensible way to pick conflicting metadata from several filters when you use filters that take more than single input. What if both inputs provide cropdetect metadata? which one to pick then?

Hello, 
I understand the way vf-metadata works right now is limited to one of the same filters per mpv label, but that's not what i'm trying to do here.

There is only one filter chain and one cropdetect filter active here, the second filter chain command is commented in the test script,
and it's working one way, i'm sure something can be done.

If you want more context on what i'm doing with it, here is the current full chain i'm using with [dynamic-crop.lua](https://github.com/Ashyni/mpv-scripts/tree/development) to collect data ahead in real time:
```
@label:lavfi=[split[a][b];[b]trim=start=0.3,setpts=PTS-0.3/TB,cropdetect=reset=1[b];[b][a]overlay=eval=init:format=auto
```
but only overlay in a specific input order works, and it adds auto_scale filter that generate error `auto_scale_0: Failed to process command. Continuing with existing parameters.` when sending a command to the entire chain, which is another limitation with graph and vf-command.
So i'm trying with mix to have something more lightweight, but both input orders fail.

**Comment by richardpl** [comment]
I'm sure there is big language barrier here, but I will try to explain once more: The overlay filter takes 2 inputs, mix filter 2 or more inputs, same as hstack. From which path/input pad the overlay filter should pick metadata? Metadata is  stored with each output frame. Obviously one can add another option to mix/overlay/hstack to pick metadata from specific input pad but i very dislike that approach. Another approach is just copy metadata from all input pads, this may not be correct to do depending on case by case.

**Comment by Ashyni** [comment]
Ok, i think i understand, just tested by adding metadata filter at the end and just after cropdetect,
`lavfi=[split[a][b];[b]cropdetect[b];[a][b]mix,metadata=mode=print]`
`lavfi=[split[a][b];[b]cropdetect,metadata=mode=print[b];[a][b]mix]`
The metadata is not keep by mix/overlay or others filter of that type and `vf-metadata` can only target the end of the graph, so not mpv issue, got it.
I want to talk more to find a proper solution on ffmpeg side then, but that's not the place.
Thank you for your time.
