### ISSUE TITLE
The d3d11 API tends to make GPU run at unnecessarily higher frequency, so more power-hungry

### ISSUE THREAD

**Issue by msoxzw** [mpv-player/mpv#11137]
### Important Information

- mpv version: 0.35.0
- Windows Version: Windows 10 22H2
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files

### Reproduction steps

mpv --no-config --gpu-api=d3d11 --profile=gpu-hq --scale=ewa_lanczossharp --cscale=ewa_lanczossharp
mpv --no-config --gpu-api=vulkan --profile=gpu-hq --scale=ewa_lanczossharp --cscale=ewa_lanczossharp
mpv --no-config --gpu-api=opengl --profile=gpu-hq --scale=ewa_lanczossharp --cscale=ewa_lanczossharp

Observe GPU clock and power via hardware monitoring tool, e.g. [HWiNFO](https://www.hwinfo.com/)

### Expected behavior

Among d3d11, vulkan, and opengl, the difference of GPU clock and power should be negligible, when the mpv runs with a moderate workload.

### Actual behavior

The GPU clock and power of d3d11 is measurably higher than that of vulkan or opengl.

The intel GPU with eDRAM that I use operates at 1050 MHz when d3d11 is used, while it operates at 500 MHz if vulkan or opengl is used.

Additionally, madVR also uses d3d11 API by default, and makes GPU run at 500 MHz with a moderate workload.

**Comment by hooke007** [comment]
Could not reproduce on my side.(nv gpu)

**Comment by Jules-A** [comment]
Depends on platform and drivers, on my RX570 DX11 is more efficient than MPV's Vulkan or OpenGL renderer with the rather heavy shaders I use. It may be less efficient at default but I haven't tested yet.

**Comment by msoxzw** [comment]
@Jules-A

The d3d11 API is also more efficient on my system. Actually, under same workload, GPU usage varies depending on GPU clock speed. For instance, 60% usage at 500 MHz is equivalent to 30% usage at 1000 MHz, but the former consumes less electricity than the latter.

I could select GPU power plan among Maximum Battery Life, Balanced, and Maximum Performance, to change GPU frequency to some degree, and accordingly, power usage changes:


Power Usage | Maximum Battery Life | Balanced | Maximum Performance
-- | -- | -- | --
d3d11 | 1.8 W | 3.3 W | 3.3 W
vulkan | 2.0 W | 2.0 W | 3.5 W

If gpu-next is used, GPU power usage is increased from 3.3 W to 5.0 W.

**Comment by msoxzw** [comment]
This issue will be disappeared if video is played via [mpc-qt](https://github.com/mpc-qt/mpc-qt/releases/tag/v23.02) based on libmpv. To tax GPU under moderate workload, highest preset in mpc-qt is used. As a result, there might be bugs hidden in the official pseudo gui.

**Comment by Dudemanguy** [comment]
mpc-qt uses opengl so that doesn't apply.

**Comment by msoxzw** [comment]
I believe that the needless high GPU clock is ascribed to compute shaders, a.k.a DirectCompute in DirectX, which will also occurs if any one of error diffusion dithering algorithms are used in madVR.

In mpv, the `ewa_lanczos` filter is implemented via either compute shader or regular sampler, the former of which runs measurably faster, which may help explain why the `ewa_lanczos` filter in mpv is more efficient than the equivalent `Jinc` filter in madVR.

However, the complete behavior of dynamic voltage and frequency scaling of GPU depends upon GPU vendor, microarchitecture, and even specific SKU. For example, except for too light or too heavy workload, my GPU usage hovers around 80% while its frequency varies between minimum to maximum depending on workload.
