### ISSUE TITLE
Best tonemapping algorithm hdr accuracy 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#11146]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I was wondering which tonemapping algorithm would be the best to use for hdr movies for the best hdr accuracy mobius or bt.2390 I can only use vo=gpu

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by Dudemanguy** [comment]
Don't open duplicates. #11116
