### ISSUE TITLE
Target peak too dark

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#11149]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I am playing tonemapped hdr content and I heard that the best way yo do this is to set the target peak as the brightest your screen can display my screen is capable of 400nits in total so I therefore added target-peak=400 however with certain hdr movies they seem to be appearing too dark I don’t understand this as I have set target peak to what my display can handle was wondering if I can do anything to help 

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by Jamie666123** [comment]
Was also wondering what the lowest target peak number would be for tonemapped hdr to still be worth it and look better than sdr

**Comment by Natural-Harmonia-Gropius** [comment]
In content grading, the default 203 nit is considered the peak of SDR. Therefore, playback should follow it, not the actual peak of your monitor.

**Comment by Jamie666123** [comment]
> In content grading, the default 203 nit is considered the peak of SDR. Therefore, playback should follow it, not the actual peak of your monitor.

But wouldn’t this mean I am losing out on some of the hdr effect I thought the whole point in being able to set the target peak was to set it to the maximum your display can handle for the best quality possible
