### ISSUE TITLE
mpv embark a version of libx265 compiled only in 10bit, which prevent converting to HEVC 8 bits

### ISSUE THREAD

**Issue by msnbcorp** [mpv-player/mpv#11147]
Working with SVP, I noticed that conversion from a 8 bits video to x265 8bits, don't work anymore.
I make my way through the process and discovered that this simple command line : 

./mpv.com ./vids.mkv --no-config --o=output.mkv --no-audio --no-sub --no-sub-auto --of=matroska --ovc=libx265 --ovcopts=profile=main

cause this bug : 

_(+) Video --vid=1 (*) (h264 1920x1080 25.000fps)
     Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
VO: [lavc] 1920x1080 yuv420p
[vo/lavc] Opening encoder: libx265 H.265 / HEVC [libx265]
x265 [error]: main profile not supported, internal bit depth 10.
**[ffmpeg] libx265: Invalid or incompatible profile set: main.**
[vo/lavc] Could not initialize encoder.
Could not initialize video chain.
Video: no video_

[encode] no data written to target file
Exiting... (Interrupted by error)

After digging, it seems that the version of libx265 in mpv is compiled only with 10 bits.

When not trying to force a profile, here is part of the output : 

_x265 [info]: build info [Windows][GCC 12.2.1][64 bit] **10bit**_

Which we can compare with the version embedded, for example, with ffmpeg : 

_x265 [info]: build info [Windows][GCC 9.3.1][64 bit] **8bit+10bit**_

A look on the documentation of libx265 explain the problem : 

> Profile, Level, Tier
> --profile, -P <string>
> Enforce the requirements of the specified profile, ensuring the output stream will be decodable by a decoder which supports that profile. **May abort the encode if the specified profile is impossible to be supported by the compile options chosen for the encoder** (a high bit depth encoder will be unable to output bitstreams compliant with Main or MainStillPicture).

I have try to force with option like  --vf=format=fmt=yuv420p  with no success. 

I think this is not the desired behaviour. The version of liibx265 embeded in mpv should be compiled in 8bit 10 bit.

**Comment by zhongfly** [comment]
https://mpv.io/installation/
> Windows
> All binary packages are unofficial third-party builds.

Also, you ignored issue template.

**Comment by msnbcorp** [comment]
(Don't understand what « [ignored-issue-template] » mean here ... )

Ok, thanks for the answer, I understand that binary package are unofficial third-party builds, on the paper. In practical i think it's quite strange that 3 of the builds I have tested have the same bug currently ... 

So, if In uderstand well, libx265 is not included in mpv from here, but only from the build made by other third-party mpv-users ?

**Comment by zhongfly** [comment]
The mpv build that is widely used on windows comes from shinchiro/mpv-winbuild-cmake, and the files distributed by Scoop and Chocolatey also come from it, so it's only natural that they have the same problem

**Comment by zhongfly** [comment]
issue template: you should choose one in https://github.com/mpv-player/mpv/issues/new/choose,and fllow the template

**Comment by msnbcorp** [comment]
Ok, it's noted. I will make a bug report on shinchiro I guess, thanks :)
