### ISSUE TITLE
How do I convert --gamma-factor values to --gamma values?

### ISSUE THREAD

**Issue by fighuass** [mpv-player/mpv#11153]
I've always had --gamma-factor set to 1.1, but for some reason it seems to be deprecated and I'll have to switch to --gamma, but I have no idea what the equivalent value there is.

**Comment by sommio** [comment]
The value close to it is `format=gamma=gamma2.2`, `gamma-factor=1.1` just makes gamma2.4 look like gamma2.2 (2.4/1.1=2.18).

**Comment by sommio** [comment]
> The value close to it is `vf=format=gamma=gamma2.2`, `gamma-factor=1.1` just makes gamma2.4 look like gamma2.2 (2.4/_1.1_=2.18).

**Comment by marioaelius** [comment]
On my laptop I solved the problem with::
--target-trc=gamma2.8
