### ISSUE TITLE
[ao/pipewire] Could not connect to context '(null)': Host is down

### ISSUE THREAD

**Issue by 0pLuS0** [mpv-player/mpv#11156]
### Important Information

Provide following Information:
- mpv version ```0.35.0```
- Linux Distribution and Version ```Slackware 15.0```
- Source of the mpv binary ```mpv-0.35.0.tar.gz```
- If known which version of mpv introduced the problem ```0.35.0```
- Window Manager and version ```Openbox 3.6.1```
- GPU driver and version ```nvidia-driver-525.78.01```

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

```I tried using --no-config I still see the same issue.```

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
mpv won't play a video

```I have pipewire-0.3.44 and pipewire-native-jack-0.3.44 installed.```

### Actual behavior
When running mpv from the command line I get this back at the terminal;

(+) Video --vid=1 (*) (h264 688x572 25.000fps)
 (+) Audio --aid=1 (*) (ac3 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
[vaapi] libva: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Using hardware decoding (vdpau-copy).
[ao/pipewire] Could not connect to context '(null)': Host is down
zsh: segmentation fault  mpv 

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

[output.txt](https://github.com/mpv-player/mpv/files/10422350/output.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by 0pLuS0** [comment]
Ok, I have this working.

What I did in Slackware was these steps.

cd /etc/xdg/autostart
cp pipewire-media-session.desktop.sample pipewire-media-session.desktop
cp pipewire-pulse.desktop.sample pipewire-pulse.desktop
cp pipewire.desktop.sample pipewire.desktop

chmod +x pipewire-media-session.desktop
chmod +x pipewire-pulse.desktop
chmod +x pipewire.desktop

By the way pulseaudio.desktop is not executable.

cd /etc/pulse 
client.conf 
autospawn = no

I logged out and logged back in and it's working, here's the output from the command line;

(+) Video --vid=1 (*) (h264 688x572 25.000fps)
 (+) Audio --aid=1 (*) (ac3 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
[vaapi] libva: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Using hardware decoding (vdpau-copy).
AO: [pipewire] 48000Hz stereo 2ch doublep
VO: [gpu] 688x572 => 751x572 nv12
AV: 00:00:03 / 00:30:20 (0%) A-V:  0.003 DS: 6.291/53 Cache: 1815s/460MB

**Comment by 0pLuS0** [comment]
One last thing, is this message a bug?

```[vaapi] libva: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)```

THANKS

**Comment by Dudemanguy** [comment]
Try updating your pipewire version. If I recall correctly, there was a bug somewhere that got fixed in pipewire. Not having pipewire running shouldn't crash mpv obviously.

>[vaapi] libva: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

That just means vaapi doesn't work on your system for whatever reason.

**Comment by 0pLuS0** [comment]
I didn't need to updated pipewire as I mentioned, I have it working, if you look up at my last reply before the vaapi one.

I thought libva handles the vaapi for mpv?

THANKS
