### ISSUE TITLE
Audio and video lagging after pause

### ISSUE THREAD

**Issue by sajadspeed** [mpv-player/mpv#11158]
### Important Information

Provide following Information:
- mpv 0.35.0
- Debian GNU/Linux bookworm/sid
-  KDE Plasma 5.26.3
- Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)

### Expected behavior
Video playback without lag after play.
### Actual behavior
After replaying, the video and sound are not synchronized for a few seconds, and after about 10 seconds, it is fixed.
### Log file
I don't know if it has anything to do with it, but when I fast forward the movie, it gives this error in the terminal:
`[ffmpeg/audio] aac: env_facs_q 255 is invalid`

Of course, there is no problem in playing the video, it is just displayed.

**Comment by dubhater** [comment]
I see this too.

- mpv 0.35.0
- KDE Plasma 5.26.5
- Arch Linux installed yesterday
- AMD Athlon Gold 3150U

It happens with both X11 and Wayland.

I just got this laptop, so at first I thought it was something to do with the AMD graphics or the audio, because I didn't see this problem with my old laptop (Intel 7020U). More likely it's a regression in mpv 0.35. The old laptop has 0.34.1.

**Comment by dubhater** [comment]
I have pause=yes in the config. When mpv opens I hear a noise in the headphones--the audio device wakes up from sleep or something. If I wait about six seconds, there is another noise--the audio device goes back to sleep. If I then resume the video, mpv will drop frames (says so in the status line) and the audio and video are out of sync for a few seconds. However, if I resume the video before the audio device goes back to sleep, there are no dropped frames and no sync problem.

The other laptop with the Intel 7020U also has that noise in the headphones when the audio device wakes up and goes to sleep, but mpv 0.34.1 doesn't have any problem with it.

The ``-v`` option doesn't print anything new when the problem happens.

**Comment by sajadspeed** [comment]
Thank you very much for your explanation.
Now I played a video with different `--gpu-contexts` but still the problem is still there.
Do you have a suggestion to solve this problem?

By the way, I also use KDE Plasma 5.26.3.
Now, even though I don't know exactly what the `--gpu-contexts`, `--vo`, `--gpu-api` parameters are, I tried to try with different values, but it didn't work.
