### ISSUE TITLE
Guidelines on using "d3d11va" or "nvdec"

### ISSUE THREAD

**Issue by jiangzhenjerry** [mpv-player/mpv#11151]
- Platform: Windows 11 x64
- GPU: NVIDIA RTX 4090

May I get a little help on understanding the pros and cons of "d3d11va" vs "nvdec" for hardware decoding on Windows? Basically, the difference between the following two:

`mpv --vo=gpu-next, --hwdec` (defaults to `--hwdec=d3d11va` on Windows)
`mpv --vo=gpu-next, --hwdec=nvdec --gpu-api=opengl`

To try to push mpv harder, I am testing on a video of 4K H265 10-bit 59.94Hz, playing it on fullscreen mode, and using `nvidia-smi` to record GPU usage. The former is around 20%-35% GPU usage, and the latter is around 30%-45%. Both are playing fine, so I am curious about what exactly I gain by using `nvdec` and ~10% more GPU?

**Comment by jiangzhenjerry** [comment]
Thanks. I did try `--gpu-api=vulkan --hwdec=nvdec`, but the GPU usage was huge (60+%) so I immediately stopped using it. `--gpu-api=opengl --hwdec=nvdec` is at least reasonable.

**Comment by ZaquL** [comment]
--gpu-api=d3d11 -vo=gpu-next does not support -hwdec=nvdec, while --gpu-api=vulkan -vo=gpu-next does not support -hwdec=d3d11va, use them the opposite way.

>but the GPU usage was huge (60+%) so I immediately stopped using it 

That is not huge. That is just nvdec chip, for H265 10-bit 59.94Hz that is nothing.

**Comment by jiangzhenjerry** [comment]
> --gpu-api=d3d11 -vo=gpu-next does not support -hwdec=nvdec, while --gpu-api=vulkan -vo=gpu-next does not support -hwdec=d3d11va, use them the opposite way.

Thanks @ZaquL for your reply. Maybe my wording caused some confusion, but just to clarify, I ever say I used `--gpu-api=d3d11 --vo=gpu-next --hwdec=nvdec` or `--gpu-api=vulkan --vo=gpu-next --hwdec=d3d11va`.

> That [60%+] is not huge. That is just nvdec chip, for H265 10-bit 59.94Hz that is nothing.

I'm not sure I agree with that. Let me reiterate and see if I can reduce the confusion this time. Here are what I've tried:

1. `--vo=gpu-next, --hwdec=d3d11va --gpu-api=d3d11`: GPU usage 20%-35%
2. `--vo=gpu-next, --hwdec=nvdec --gpu-api=opengl`: GPU usage 30%-45%
3. `--vo=gpu-next, --hwdec=nvdec --gpu-api=vulkan`: GPU usage 60+%

Option 2 is also using `nvdec` (with `opengl`) but the GPU usage is much lower than Option 3. I wouldn't expect RTX 4090 to spend 60+% just decoding H265 10-bit 59.94Hz, so I gave up on `nvdec`+`vulkan`.

My original question is, what's the difference between Option 1 and  Option 2? Any pros and cons?

**Comment by ZaquL** [comment]
>I wouldn't expect RTX 4090 to spend 60+% just decoding H265 10-bit 59.94Hz, so I gave up on nvdec+vulkan.

What 60% you are talking about? Show a screenshot.

**Comment by jiangzhenjerry** [comment]
>...observe the load of different GPU engines through the task manager. In some cases, it may be more accurate than the value returned by nvidia-smi.

Thanks. I will definitely give it a try. I heard that nvidia-smi was more accurate that Windows Task Manager, but maybe there are exception cases.

**Comment by jiangzhenjerry** [comment]
> You can also try benchmarking hwdec performance instead of watching GPU load

Thanks for this suggestion! Definitely a new thing for me to learn. Using this approach, I actually don't see a significant difference between `nvdec`+`winvk` vs `d3d11va`+`d3d11`. Both give me 650-710 fps on a test video that I tried. Does it mean there is really not much difference between the two approaches?

**Comment by jiangzhenjerry** [comment]
> taskmgr will be affected by Hardware-Accelerated GPU Scheduling, turning off Hardware-Accelerated GPU Scheduling can get very accurate results

Ah I see, thanks a lot!

**Comment by ZaquL** [comment]
>Does it mean there is really not much difference between the two approaches?

It would be a bug if there was. And the difference should be only at display pipeline. When you decode faster than real time you do not use display or vsync or many other things.

**Comment by CrendKing** [comment]
> You can also try benchmarking hwdec performance instead of watching GPU load

For some reason, with this config, I can only disable VSync for D3D11. Both Vulkan and OpenGL still capped at my display refresh rate. `opengl-swapinterval=0` and `vulkan-swap-mode=immediate` have no effect.

**Comment by CrendKing** [comment]
> You may need to check the NVIDIA control panel, which may force an override of the application selection

Bingo! My "Vertical Sync" was set to "On". Changing to "Use the 3D application setting" (default) works now. Somehow D3D11 ignores that setting 🤔
