### ISSUE TITLE
Oversaturated while paused + osd visible

### ISSUE THREAD

**Issue by radozd** [mpv-player/mpv#11152]
mpv 0.34.0
windows 11
mpv.net

I don't think this is a big problem because `-no-config` solves it.
But I can't find the specific option to blame. Tried to remove all of them with no luck.
No matter if it is HDR movie or not.

screenshots + log:
[log.txt](https://github.com/mpv-player/mpv/files/10420431/log.txt)
![mpv1](https://user-images.githubusercontent.com/60126193/212547076-e8a35664-0efe-42c0-9481-9c3b02ccbc88.jpg)
![mpv2](https://user-images.githubusercontent.com/60126193/212547078-d6849fcb-fbfe-49d2-8098-b556fd149ae0.jpg)
![mpv3](https://user-images.githubusercontent.com/60126193/212547079-36995c2e-9c11-47cf-afc5-85f2edbca994.jpg)

Forgot to add one more screenshot showing playback + osd == colors are still ok.
Is it possible to fix?

![mpv4](https://user-images.githubusercontent.com/60126193/212547475-c59b540c-4a0a-44ac-bfa2-d58f7eff284c.jpg)

**Comment by christoph-heinrich** [comment]
Since `--no-config` solves it for you, you can try creating an empty directory and then start mpv with `--config-dir=<path to that dir>` to effectively only use defaults. Then find what's causing it by gradually adding parts of your normal config to this one until the problem starts occurring again.

**Comment by radozd** [comment]
> Then find what's causing it by gradually adding parts of your normal config to this one until the problem starts occurring again.

Right. I've tried that with no luck. I've commented out ALL of my few manual settings, deleted all config files. Same.
I've guessed that --no-config has disabled something else.

Still which option could produce this weird effect?

**Comment by alpozcan** [comment]
I have the same problem on Windows 11 & Intel Iris Plus 655 iGPU
https://ixpeering.dl.sourceforge.net/project/mpv-player-windows/64bit-v3/mpv-x86_64-v3-**20241013-git-228f386**.7z

**Comment by llyyr** [comment]
> I have the same problem on Windows 11 with an Intel Iris Plus 655 iGPU.

Open a new ticket and fill out the ticket form
