### ISSUE TITLE
Builtin double left click keybinding (MBTN_LEFT_DBL) can't be overwritten

### ISSUE THREAD

**Issue by christoph-heinrich** [mpv-player/mpv#11154]
### Important Information

Provide following Information:
- 0.35.0-121-g4493225455
- Arch Linux
- compiled from source

### Reproduction steps

1. Create a `test.lua` with the content
``` lua
mp.add_key_binding('MBTN_LEFT_DBL', nil, function() mp.command("show-text test") end)
```
3. run `mpv --no-config --force-window --idle --script=test.lua`
4. double left click

Replacing `MBTN_LEFT_DBL` with `MBTN_RIGHT_DBL` and then double right click works as expected.
Making it a forced keybind doesn't help.

The keybinding does show up in the `Active key bindings:` page of stats.lua, but it still calls the builtin keybinding instead of the one from the script.

### Expected behavior
Shows text "test"
### Actual behavior
Cycles fullscreen
### Log file
[log.txt](https://github.com/mpv-player/mpv/files/10420917/log.txt)

**Comment by christoph-heinrich** [comment]
You're right, it seems to have to do with the deadzone in osc. Adding `--script-opts=osc-deadzonesize=0` and opening a file makes it work everywhere.

By mimicking what osc.lua is doing I got it to work.
``` lua
mp.set_mouse_area(0, 0, 1000, 1000,"showhide")
mp.set_key_bindings({{"mouse_move", function(e) end}}, "showhide")
mp.enable_key_bindings("showhide")
mp.add_forced_key_binding('mbtn_left_dbl', nil, function() mp.command("show-text test") end)
```
`mpv --no-config --force-window --idle --script=test.lua --no-osc`

But I have no idea why that's necessary and it really shouldn't be.

**Comment by sfan5** [comment]
Can confirm the bug and that `mouse_move ignore` works around it.

@christoph-heinrich since you already investigated it can you try to find a fix for this?

**Comment by christoph-heinrich** [comment]
I'm not familiar with the relevant parts of the code, but I'll have a look when I have some time.

**Comment by christoph-heinrich** [comment]
The Problem here is that the active section is selected based on the [MOUSE_MOVE](https://github.com/mpv-player/mpv/blob/6234a709202282d8a8bfffd0ee4f9d80561dd4b9/input/input.c#L504-L505) keybind, with a fallback to `default`, combined with the feature that input sections "stick" while a mouse button is down. [This if](https://github.com/mpv-player/mpv/blob/6234a709202282d8a8bfffd0ee4f9d80561dd4b9/input/input.c#L424-L431) is responsible for that.

Without binding to `MOUSE_MOVE` in the script, the active mouse section is `default`, and so thanks to that if it prefers mouse keybindings from the default section if there is one available. The builtin keybindings have a `MBTN_LEFT_DBL` binding, but not one for `MBTN_RIGHT_DBL`, which is why it works fine for the right mouse button.

Now we could modify that if to exclude the `default` section to make my example work. The problem with that is that if two scripts bind to `MBTN_LEFT_DBL` and one of them also binds to `MOUSE_MOVE`, that one will be preferred even if the other one should have higher priority based on binding order.

I don't know how we should proceed form here.
We could somehow change to mouse section selection to choose based on any mouse keybindings, but that's not as easy as it sounds.

wm4 wanted to remove input sections 13815bf25179da6dd450141fa6c1ab67a4b00b6b, so if we were to actually remove them, that problem would go away (along with simplifying input handling). AFAIK the only user of input sections is osc.lua, so if we were to change that we could remove them completely. There might be user scripts that rely on them, but they have been deprecated for so long at this point, that breaking them should be fine.

That commit mentions the need for some replacement, but with the `mouse-pos` property (which has been added a month after the deprecation of input sections a7686679564de584eaa720a6f682c8bd8ad062e6) that's not really necessary anymore. Scripts can simply watch `mouse-pos` and add/remove keybindings based on the mouse position. That's what is already done in [uosc](https://github.com/tomasklaen/uosc), which is proof that this works well in practice.
