### ISSUE TITLE
Remove compositor lacks support message under wayland & gnome

### ISSUE THREAD

**Issue by pflanzenandi** [mpv-player/mpv#11160]
The Flatpak version got patched a couple month ago and the message is unnecessary since then. Not sure about the .deb version. 

`[vo/gpu-next/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback`

**Comment by Dudemanguy** [comment]
The mutter MR is still [open](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/111), so as far as I know, this still hasn't been implemented.

**Comment by t-8ch** [comment]
With PR #11161 we could future-proof the warning, to go away as soon as it works.

**Comment by pflanzenandi** [comment]
> The mutter MR is still [open](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/111), so as far as I know, this still hasn't been implemented.

I was talking about [this](https://github.com/Guldoman/mpv_inhibit_gnome) gotten patched into the flatpak version of mpv. Not sure if this is the same script/patch then what you linked.

**Comment by Dudemanguy** [comment]
>I was talking about [this](https://github.com/Guldoman/mpv_inhibit_gnome) gotten patched into the flatpak version of mpv. Not sure if this is the same script/patch then what you linked.

That's a cplugin. It indeed does what it says it does, but it's not applicable to what the warning indicates (i.e. mutter does still like idle inhibit).

**Comment by Dudemanguy** [comment]
Closing since unfortunately, this is still an issue but if mutter ever fixes it, the message will just be dead code.
