### ISSUE TITLE
Shell expansion

### ISSUE THREAD

**Issue by agguser** [mpv-player/mpv#11169]
`Shell expansion` should be supported wherever `Property expansion` is supported, e.g. with `$(…)`:
```
show-text "uppercase title: $(<<<${media-title} tr 'a-z' 'A-Z')"
```

**Comment by avih** [comment]
No.

mpv needs to expand properties quickly, e.g. to update the window title, possibly many times per second, and while the mpv properties expansion syntax looks similar to (posix) shell, it's an internal expansion code, with limited functionality, which doesn't rely on external programs.

Supporting expansion via external programs, like parsing your here-string via a shell or translating it using `tr`, is completely out of scope for mpv property expansion.

If you need to process some values, you can do that either using an mpv lua/js script, or using an external program, like shell, which an mpv script can invoke and then do something with its output.
