### ISSUE TITLE
Unsupported hwdec: nvdec

### ISSUE THREAD

**Issue by 0pLuS0** [mpv-player/mpv#11164]
### Important Information

Provide following Information:
- mpv version ```0.35.0```
- Linux Distribution and Version ```Slackware 15.0```
- Source of the mpv binary ```mpv-0.35.0.tar.gz```
- If known which version of mpv introduced the problem ```0.35.0```
- Window Manager and version ```Openbox 3.6.1```
- GPU driver and version ```nvidia-driver-525.78.01```

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

If I run mpv with no config this is the output;

(+) Video --vid=1 (*) (h264 688x572 25.000fps)
 (+) Audio --aid=1 (*) (ac3 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 688x572 => 751x572 yuv420p
AV: 00:00:02 / 00:30:20 (0%) A-V:  0.000 Cache: 586s/150MB

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
I thought with an nvidia gpu I could use nvdec and it's the best choice of performance too?

### Actual behavior
When I use ```hwdec=nvdec``` I get back at the term;

```Unsupported hwdec: nvdec```

This is the output at the term using ```hwdec=nvdec```;

 (+) Video --vid=1 (*) (h264 688x572 25.000fps)
 (+) Audio --aid=1 (*) (ac3 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
```Unsupported hwdec: nvdec```
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 688x572 => 751x572 yuv420p
AV: 00:00:01 / 00:30:20 (0%) A-V: -0.097 DS: 5.913/29 Cache: 1816s/460MB

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

[output.txt](https://github.com/mpv-player/mpv/files/10430437/output.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by thebombzen** [comment]
Is your FFmpeg built with nvcodec-headers? if not, then nvdec won't work.

**Comment by 0pLuS0** [comment]
If I use 0.34.1 I don't see this message at the term.

Is the terminal output of infomation between 0.34.1 and 0.35.0 different?

**Comment by 0pLuS0** [comment]
I realized later after posting this, that I needed to update Vulkan and FFmpeg for 0.35.1.

I compiled vulkan-sdk-1.3.204.0 and FFmpeg 5.1.2 and now when I run mpv from the term it's all good!

mpv /media/MyPassport/My\ Videos/Movies/Star\ Trek/12.\ Into\ Darkness\ \(2013\)\ 1080p.mp4
 (+) Video --vid=1 (*) (h264 1920x800 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 6ch 48000Hz)
Using hardware decoding (nvdec).
AO: [pulse] 48000Hz 5.1 6ch float
VO: [gpu] 1920x800 cuda[nv12]
AV: 00:00:01 / 02:12:06 (0%) A-V: -0.100 DS: 6.125/26 Cache: 3278s/1800MB
[+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]

Exiting... (Quit)
