### ISSUE TITLE
Configuration file location on Steam Deck?

### ISSUE THREAD

**Issue by zohozer** [mpv-player/mpv#11166]
I do installed the MPV 0.35 using the "Discover" app on my Steam Deck. I do created a "mpv.conf" and I placed the file in "/home/deck/.var/app/io.mpv.Mpv/config/mpv.conf".

The problem it is that seems that MPV can't read my config file. It wrong the location or what other cause can be?

Also I do try to launch MPV from Konsole and seems that MPV it is not accesible from the command line.

Any help will be aprecciated. Best regards.

**Comment by CounterPillow** [comment]
Your best bet is to ask the person who created the Flatpak for support, as mpv as a project does not distribute that officially.

**Comment by CounterPillow** [comment]
Actually now that I read the flatpak page, it seems clear what your mistake is.

You used the path `/home/deck/.var/app/io.mpv.Mpv/config/mpv.conf` but should have used the path `/home/deck/.var/app/io.mpv.Mpv/config/mpv/mpv.conf`

**Comment by zohozer** [comment]
Thank you for support. I do moved the config file into `/home/deck/.var/app/io.mpv.Mpv/config/mpv/mpv.conf` and now it is readable by MPV.

Do you know also why I can't launch MPV from Konsole app? Before I had an Ubuntu system and there I was able to just type `mpv` in terminal to open MPV.

**Comment by hooke007** [comment]
Here is the proper place. https://github.com/flathub/io.mpv.Mpv/issues

**Comment by CounterPillow** [comment]
> Do you know also why I can't launch MPV from Konsole app? Before I had an Ubuntu system and there I was able to just type mpv in terminal to open MPV.

Flatpak doesn't quite work like that, unfortunately. You could put this in your .bashrc:
```
alias mpv='flatpak run io.mpv.Mpv'
```

(didn't test this but should work, dunno if steamdeck lets you mess with your bashrc)
