### ISSUE TITLE
script-opts/script.conf: allow same-line comments to work with mp.options.read_options

### ISSUE THREAD

**Issue by eugenesvk** [mpv-player/mpv#11170]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request
I searched for `comments in script options`, scrolled a few pages, couldn't find anything

### Expected behavior of the wanted feature

If I try to configure some lua script by editing script-opts/script.conf, which gets loaded by via
```lua
local options = require 'mp.options' 
options.read_options(opts, nil, function() end)
```
Like so:
```
enabled=yes # should correctly parse this as a boolean, ignoring the comments
```

I get an error `Error: Can't convert 'yes # should correctly...' to boolean!`
because (as far I as understood it) https://github.com/mpv-player/mpv/blob/fd2f1a6f9af5087ca8e6e878176db6308fd4b45a/player/lua/options.lua#L4 
doesn't strip comments in

https://github.com/mpv-player/mpv/blob/fd2f1a6f9af5087ca8e6e878176db6308fd4b45a/player/lua/options.lua#L6

That's rather unexpected and also different from the regular `mpv.conf` syntax, where I can easily add comments on the same line for better readability
Also, spaces before `=` seem to break the parser as well, which is also a weird difference vs the default .conf

### Log file

https://gist.github.com/eugenesvk/ac0c63eb37d001bcbc45dc0e3f9a443b

**Comment by avih** [comment]
> That's rather unexpected

Perhaps, to some, if they didn't read the docs of [`mp.read_options`](https://mpv.io/manual/master/#mp-options-functions):
> The config file will be stored in script-opts/identifier.conf in mpv's user folder. Comment lines can be started with # and stray spaces are not removed. Boolean values will be represented with yes/no.


> and also different from the regular `mpv.conf` syntax
> Also, spaces before = seem to break the parser as well

True, because it's a different parser.

The `mpv.conf` parser is rather complex, and can get complex quickly when the values need quoting or other special chars.

The script-opts conf parser is, in contrast, very simple:
```
# COMMENT
NAME=VAL<newline>
```
If a line begins with `#` then it's ignored.

Else, everything right before the first `=` is the name, everything right after it, including leading spaces, till end of line or end of file, is the value.

It can hold spaces , dollar, quotes, hash sign, and other special (literal) chars without issues.

If we added support for spaces before/after the `=`, or ffor `#` at the middle of the line to start a comment, then the parsing rules become complex quickly. We would need to support quoting, and escaping, and existing `.conf` files will stop working because they're without quoting etc.

So I don't think it should be changed.

However, if you think the existing docs are not clear enough, and/or that they can be made better in some ways, then you can open a PR with your suggested changes.

**Comment by eugenesvk** [comment]
> > That's rather unexpected
> 
> Perhaps, to some, if they didn't read the docs of [`mp.read_options`](https://mpv.io/manual/master/#mp-options-functions):

How do you think the user is expected to know to read these docs for a simple config file, especially after getting used to the same config type from `mpv.conf`?

Also,↓
> 
> > The config file will be stored in script-opts/identifier.conf in mpv's user folder. Comment lines can be started with # and stray spaces are not removed. Boolean values will be represented with yes/no.

doesn't make it clear, I've read it once I got the error, but stil got non the wiser, e.g., I don't consider ` = ` to be `stray spaces` (and the regular config file example is the same in the docs with comments starting with the new line, but allows placing them on the same line, so that's doesn't jump out either)


> > and also different from the regular `mpv.conf` syntax
> > Also, spaces before = seem to break the parser as well
> 
> True, because it's a different parser.

So why can't you use the same parser since it already exists?

> We would need to support quoting, and escaping, and existing `.conf` files will stop working because they're without quoting etc.

no they wouldn't: you could add a version requirement for the new files to opt into the much user friendly syntax, so that all the old files continue to work 


> However, if you think the existing docs are not clear enough, and/or that they can be made better in some ways, then you can open a PR with your suggested changes.

That doesn't help much as it's already too late by then. The proper solution is not have such a big inconsistency in the first place

**Comment by avih** [comment]
> How do you think the user is expected to know to read these docs for a simple config file
> especially after getting used to the same config type from `mpv.conf`?

It's not always simple, and every config file format has its own rules, especially when it comes to quoting, delimiters, escaping, special characters, and comments. One needs to read the docs in order to use config files.

> So why can't you use the same parser since it already exists?

Technically speaking, the `mpv.conf` parser is complex and not available to scripts. I don't think it can easily be exposed as a module to parse arbitrary config files into a key-value list. So it's not a matter of "just use the existing one".

Personally, I also think the current script-opts parser works well for the typical needs of scripts, and it's easier (to the user) to end the value at the end of the line than to handle quoting and escapes.

Also, as you noticed, the error message was reasonaby useful and descriptive, which allowed you to immediately understand what the issue is.

As I said, if you feel like the docs could be improved, for instance adding a note near the `mpv.conf` syntax docs, or anything else, then you can open a PR. Same goes for parsing error messages.

**Comment by hooke007** [comment]
> How do you think the user is expected to know to read these docs for a simple config file, especially after getting used to the same config type from 

Then just use mpv.conf instead of lua scripts's conf files.

https://mpv.io/manual/master/#options-script-opts

```
script-opts-append = scriptname-script_optname=value # comment
```

**Comment by eugenesvk** [comment]
> It's not always simple, and every config file format has its own rules, especially when it comes to quoting, delimiters, escaping, special characters, and comments. One needs to read the docs in order to use config files.

You've missed the most relevant part of the question — `mpv.conf`. There is simply no reason to expect someone to treat the same file extension used for the same purpose in the same application to be a totally different format and go read the docs on what this format is

> I don't think it can easily be exposed as a module to parse arbitrary config files into a key-value list.

So you don't know? Also, if it's so complicated, why not just use one of the many JSON+comments-like formats with readily available modules-parsers? You already have incompatible formats, but at least you can switch to something much more common and ergonomic (also more pleasant to edit due to syntax highlighting)

> Personally, I also think the current script-opts parser works well for the typical needs of scripts, and it's easier (to the user) to end the value at the end of the line than to handle quoting and escapes.

What is so 'atypical' in this table that cleanly separates keys form values from description?
```
show_distance    	= yes    	# whether to show the length of the lines between the two points
show_coordinates 	= yes    	# whether to show the coordinates of the two points
coordinates_space	= image  	# the coordinate space of the text shown. Can be "image", "window", "both"
show_angles      	= degrees	# can be "degrees", "radians", "both", or "no"
# and a few more lines...
```
How is breaking the config for a simple ` ` make it easier, __especially__ when it contradicts the `mpv.conf` the user is used to?


> Also, as you noticed, the error message was reasonaby useful and descriptive, which allowed you to immediately understand what the issue is.

Wow, that's some wishful thinking and the opposite of what happened.
First, I wouldn't even see this error in the normal use as I launch MPV as a GUI app. I only saw it since I was tweaking someone's script, so used cli.
Second, the `size =36` error of `.conf:4 unknown key 'size ', ignoring` is the opposite of useful and descriptive (why are you ignoring a perfectly fine key? is it the script that expects a `font_size` instead and has a typo in its config or what?).
After wasting some time trying to change the configs, then checking the loader in the script and trying to do some parsing in a non-mpv lua script to check for syntax errors and wasting more time with printf statements, trying to see why `yes` is so special (this is also neither useful/descriptive `Error: Can't convert 'yes #comment' to boolean!` — why can't you convert it, it's obvioulsy `true`?), etc. did I realize just how broken and inconsistent the parser is (I don't actually remember now that level of user hostility from a simple key-value config)

> We can't go back in time, and changing the format will be considerable work and will have backward compatibility issues.

The current solution has "now compatibility" issues as well, so a fix with temporary backward compatibility is an improvement (and again, current scripts will continue to work as is). Re. work — what do you think about integrating a popular existing library?


> And it's not that bad. You just didn't know how it works, and now you do.

Yeah it is that bad. Even with my current knowledge I can't achieve what I want — a nice clean table for a config just like I can in my `mpv.conf`. Also, it's too much of a waste of user's time to go through this learning experience. And part of your assessment is based on a glaring misassessment of how helpful the

**Comment by eugenesvk** [comment]
> Then just use mpv.conf instead of lua scripts's conf files.

Thanks for the suggestion, but besides the fact that I'd have to do a lot of manual editing prepending all those `script-opts-append = scriptname-`, this doesn't resolve the ` `-white-spacing issue, so I'd still be unable to replicate my nicely formatted tables in `mpv.conf` that separate keys from values from comments

**Comment by eugenesvk** [comment]
FYI I've gone via the most obvious route of just using an existig parsing library to read configs, turned out to be not that complicted, though unfortunately had to drop the default `read_options` completely; and since it's pure lua, the parsers are dated, so requires an extra quote to avoid including comments, but for the simple configs work well enough

Now I can have these nice syntax-highlighted tables

<img width="472" alt="mpv1" src="https://user-images.githubusercontent.com/12956286/217527647-047d1734-ac4b-49f8-8125-f301e65eb71e.png">

instead of this grey mess
<img width="472" alt="mpv0" src="https://user-images.githubusercontent.com/12956286/217527667-30a7432a-d05d-4801-acf7-41e5a3045ac4.png">

https://github.com/eugenesvk/mpv-image-viewer/blob/3f4c5483543e1ceb02fbe78acb76cb48a42b5369/scripts/mpvi/lib/std.lua#L121
