### ISSUE TITLE
mjp2 wrong colors

### ISSUE THREAD

**Issue by kasper93** [mpv-player/mpv#11179]
- mpv built from v0.35.0-125-g099bc31584
- libplacebo v5.229.1-80-g9074fd7

Ok, so not much to write, I will post few screenshots to outline the situation.

Test file: https://0x0.st/ohOe.jp2
I have longer sample if you want.

## Not Expected

`./mpv --no-config --scale=ewa_lanczos --gpu-api=vulkan --vo=gpu-next` (same with `--gpu-api=opengl`)
not scaled, oversaturated:
![image](https://user-images.githubusercontent.com/1126053/213525105-30ff5bec-b7b8-4afa-8cf9-b126cb89d090.png)

when scalling kicks in this happens, just resize window:
![image](https://user-images.githubusercontent.com/1126053/213525156-5270763a-f8e1-4d8a-aa6a-11471e0e8d97.png)

`./mpv --no-config --scale=ewa_lanczos --gpu-api=d3d11 --vo=gpu`
`./mpv --no-config --scale=ewa_lanczos --gpu-api=d3d11 --vo=gpu-next`
![image](https://user-images.githubusercontent.com/1126053/213526803-a8739dbe-d57a-48d1-a50a-0a993d38a311.png)

## Expected

`./mpv --no-config --scale=ewa_lanczos --gpu-api=vulkan --vo=gpu`  (same with `--gpu-api=opengl`)
works ok, with and without scaling
![image](https://user-images.githubusercontent.com/1126053/213525936-aeb2af75-a5fa-4079-ade2-4c2dd1a80709.png)

ffmpeg conversion to rgb look slightly more correct:
![a](https://user-images.githubusercontent.com/1126053/213531388-79ee881a-868e-448d-8ede-a0280c1ed77e.png)

**Comment by haasn** [comment]
Should be significantly improved now in `--vo=gpu-next` with git master libplacebo.
