### ISSUE TITLE
Downmix to 2.1 help

### ISSUE THREAD

**Issue by kraM1tt** [mpv-player/mpv#11171]
I have a 2.1 system but it's a passive subwoofer so Windows only detects 2.0. In MPC-HC I can mix LFE and surrounds back in.

![image](https://user-images.githubusercontent.com/89113987/213266079-1f0b015d-e53e-4086-a89f-04e0646ddda1.png)

I can't get it to work in mpv as I'd like to switch over to it for the HDR functionality (and I don't like how much system resources MadVR uses)

> hwdec = auto
> save-position-on-quit = yes
> ad-lavc-downmix = yes
> audio-channels = 2.1

What am I doing wrong? I can confirm it's not working with the Fraunhofer Channel ID test video. LFE stays silent and only surrounds are mixed in, which I'm gathering is done by Windows, since LFE typically isn't included in a Stereo mixdown because there is no subwoofer, but I have an 80hz crossover on the speakers so it's fine.

**Comment by ZaquL** [comment]
>I have a 2.1 system but it's a passive subwoofer 

Who told you such lies? That is 2.0 system. Subwoofer must connect to a separate channel.

>only detects 2.0

How would windows know there is a subwoofer there? It is not a separate LFE channel.

>In MPC-HC I can mix LFE and surrounds back in.

**That must be the default anyway**, bone headphones e.g. have no problem playing LFE mixed with L + C + R.

**Comment by kraM1tt** [comment]
I know it's not technically a 2.1, but physically it is.

I know why windows doesn't detect it as 2.1.

The default settings of MPC-HC is to let Windows handle the downmix, which since it see's 2.0, Dolby guidelines are to drop the LFE channel.

I run crossover at 80hz but also a HPF to the L and R physical speakers so they receive a minimal amount of LFE information.

**Comment by ZaquL** [comment]
>I know it's not technically a 2.1, but physically it is.

(Before edit.) It is NOT. LFE2 in DTS:X requires a second subwoofer, you cannot just use LFE1 and be done with it.

>Dolby guidelines are to drop the LFE channel.

They are afraid it will demage the subwoofer, see IMAX enchanced specifically added metadata about crossover and capability of subwoofer for this.

**Comment by kraM1tt** [comment]
Ok but I don't use DTS:X or go by their guides, I exclusively watch Dolby content, which only requires 1 sub for LFE
