### ISSUE TITLE
Frames are dropped if the video was paused too long

### ISSUE THREAD

**Issue by dubhater** [mpv-player/mpv#11188]
I have pause=yes in the config. When mpv opens I hear a noise in the headphones--the audio device wakes up from sleep or something. If I wait about six seconds, there is another noise--the audio device goes back to sleep. If I then resume the video, mpv will drop frames (says so in the status line) and the audio and video are out of sync for a few seconds. However, if I resume the video before the audio device goes back to sleep, there are no dropped frames and no sync problem.

### Important Information

Provide following Information:
- mpv version: 0.35.0-4
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: Arch Linux package in community repo
- If known which version of mpv introduced the problem: maybe 0.35.0, who knows
- Window Manager and version: KWin 5.26.5-2
- GPU driver and version: amdgpu from kernel 6.1.6, no xf86-video-* packages
- Possible screenshot or video of visual glitches: not applicable
- pipewire version: 0.3.64
- sound card: onboard Realtek ALC257
- X11 or Wayland: it doesn't matter
- compositor bypassed or not: it doesn't matter

### Reproduction steps

It is reproducible with --no-config.

- Run ``mpv --no-config video.mkv``.
- Pause the video.
- Wait until you hear the sound card go to sleep. That's about six seconds with this laptop.
- Resume the video.

### Expected behavior
The video should play smoothly and in sync with the audio.

### Actual behavior
The video is out of sync with the audio for a few seconds and frames are dropped. Then the video plays correctly.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/10469267/mpv.log)

### Sample files

Any file seems to work, including this one: https://www.youtube.com/watch?v=WA4iX5D9Z64

**Comment by OverShifted** [comment]
Does it happen with pulseaudio or alsa?
You can use `--ao=[pulse|alsa]`. Even though they might still be handled by pipewire if `pipewire-pulse` and/or `pipewire-alsa` are installed.

**Comment by dubhater** [comment]
@OverShifted Thanks for the question. It was very helpful.

It turns out pulseaudio still gets installed by default in Arch Linux, even though it's abandoned and deprecated as far as I know. I installed pipewire-pulse and now the problem is gone. On the old laptop I replaced it ages ago when it started to malfunction.

**Comment by t-8ch** [comment]
Are you using ao_pulse or ao_pipewire now?

**Comment by OverShifted** [comment]
@dubhater  Your welcome.
> ... even though it's abandoned and deprecated as far as I know. 

A lot of distros are switching to pipewire, but pulseaudio still has a lot of users (probably more than pipewire).
I switched to pipewire because of [this](https://www.reddit.com/r/openSUSE/comments/w8fl8k/mpv_stutters_drops_frames_when_resume_from_pause/) [issue](https://github.com/mpv-player/mpv/issues/10295), but ended up switching back to pulseaudio because of random little drops in audio. Then I decided to test a solution for pipewire's problem, and switch to pipewire again, but I had a new problem. My laptop's internal speakers didn't work (only headset etc). Now, I am using pulseaudio again.

**Comment by dubhater** [comment]
@t-8ch I am still using ao_pulse.

**Comment by t-8ch** [comment]
@dubhater In your original log ao_pipewire was tried first (and failed).
Now that you uninstalled pulse, native pipewire should work.
Could you post another log?

**Comment by dubhater** [comment]
Sorry, I am not using ao_pulse after all. I just assumed without checking.

Here is the new log: [mpv-no-pulse.log](https://github.com/mpv-player/mpv/files/10519891/mpv-no-pulse.log)

**Comment by t-8ch** [comment]
Thanks for confirming. 
For completeness' sake, what happens with an explicit ao_pulse now?
Does the issue reproduce? 
Would `--pulse-latency-hacks` fix it.
This seems like #10295
