### ISSUE TITLE
audio-device= changes all the time

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [mpv-player/mpv#11189]
Hi, kinda new to mpv.. I want to use my Nvidia HDMI as my audio device.

So Im using a config using this: audio-device=wasapi/{00285d9d-82e4-4129-aab6-8f460d681536}
My problem is that the device name seems to change quite often. On driver updates etc. Is there a more "permanent" way to set this?

**Comment by kevmitch** [comment]
You can use `--audio-device=help` with cmd.exe to get the device name and use that instead

```
c:\Program Files\mpv>mpv.com --audio-device=help
List of detected audio devices:
  'auto' (Autoselect device)
  'wasapi/{f4901a72-cee1-4817-b37f-1d5f121e3895}' (Headphones (Sonata BHD))
  'openal' (Default (openal))
  'sdl' (Default (sdl))

c:\Program Files\mpv>mpv.com --audio-device="wasapi/Headphones (Sonata BHD)" track.flac
```
