### ISSUE TITLE
Start playback again when the space bar is pressed at the end of a video.

### ISSUE THREAD

**Issue by HubKing** [mpv-player/mpv#11183]
### Expected behavior of the wanted feature
By default, MPV closes itself when the video has reached its end. This behaviour is not like other popular video players, so the user could set `keep-open` to keep the window open. When the video has reached its end, pressing the space bar does not restart the playback from the beginning, unlike other popular video players such as VLC. 

This is especially confusing because MPV stops at the last frame and it may look like the video is paused, instead of having reached the end, and the progress bar (pseudo-UI) is not visible unless the mouse is over its window. 

Since pressing the space bar currently does nothing in this state, how about making it restart the playback from the beginning? I can't think of any down side, and it can be helpful to at least some users.

### Alternative behavior of the wanted feature
N/A

### Log file
N/A

**Comment by llyyr** [comment]
You can use a Lua script for this

```lua
mp.observe_property("pause", "bool", function(name, value)
    if value == true and mp.get_property("eof-reached") == "yes" then
        mp.command("no-osd seek 0 absolute")
    end
end)
```

**Comment by HubKing** [comment]
Well, I guess I can use that script, but don't most other media players restart from the beginning when you press the space bar when the video has ended? What would be the downside of that, compared to the current behaviour of doing nothing?

**Comment by Dudemanguy** [comment]
By default, space bar toggles pause. Making that randomly do a seek instead under a specific circumstance that not everyone might want doesn't sound worth it. The scripting solution is adequate if you want this behavior.

**Comment by K0stov** [comment]
@llyyr Thank you for your script. I would’ve loved to see this made official.

**Comment by Vozf** [comment]
>seek instead under a specific circumstance
That's what basically all the other video players are doing and that's what everyone expects from a spacebar after the video has ended
Why would one need to use some kind of script for that

**Comment by K0stov** [comment]
@Vozf Agreed. When a video finishes, it is technically paused. There's nothing "random" about making it replay by pressing space.

@Dudemanguy Will you reconsider this? There's really no downside. As it stands, space is useless when the video is over, and the player is less intuitive.

**Comment by xZabuzax** [comment]
> You can use a Lua script for this
> 
> ```lua
> mp.observe_property("pause", "bool", function(name, value)
>     if value == true and mp.get_property("eof-reached") == "yes" then
>         mp.command("no-osd seek 0 absolute")
>     end
> end)
> ```

Thank you, that script worked perfectly!

It's really, and I mean REALLY silly how a simple feature like this requires a freaking script when any other player on the planet already has that feature implemented into the player without using scripts.

I'm using MPV.net v7.1.1.0 which already comes with a GUI to configure plenty of things, but this simple feature wasn't in it.

**Comment by HubKing** [comment]
> It's really, and I mean REALLY silly how a simple feature like this requires a freaking script when any other player on the planet already has that feature implemented into the player without using scripts.

One thing that I have learnt is that the developers of MPV seem to have a strong, uncompromising philosophy on what MPV should be/behave like.

**Comment by KryptoSynth** [comment]
If anyone prefers behavior more consistent with other players (playback pauses at the end of the file and only resets to the beginning when Space is pressed), then they can use this script:

```
mp.add_key_binding("Space", function()
    if mp.get_property_native("eof-reached") then
        mp.command("no-osd seek 0 absolute ; set pause no")
    else
        mp.command("cycle pause")
    end
end)
```

**Comment by ayeluke** [comment]
> > One thing that I have learnt is that the developers of MPV seem to have a strong, uncompromising philosophy on what MPV should be/behave like.
> 
> I don't know where you see that when we disagree on changes all the time. Anyway, this conditional profile does it if you don't want to add a script:
> 
> ```
> [replay]
> profile-cond=eof_reached and pause
> input-commands=seek 0 absolute
> ```

how to use it?put it into mpv.conf or input.conf

**Comment by guidocella** [comment]
mpv.conf

**Comment by c02y** [comment]
> > One thing that I have learnt is that the developers of MPV seem to have a strong, uncompromising philosophy on what MPV should be/behave like.
> 
> I don't know where you see that when we disagree on changes all the time. Anyway, this conditional profile does it if you don't want to add a script:
> 
> ```
> [replay]
> profile-cond=eof_reached and pause
> input-commands=seek 0 absolute
> ```

This config has two problems 
1. it automatically seeks to the beginning of the video immediately after it reaches the ending
2. it only works once, when it reaches the video's ending again, Space does nothing

But the ideal solution is, it will stop at the ending of the video, Space will replay the video from the beginning, this process is able to be repeated.

This is exactly what the following script does.

> If anyone prefers behavior more consistent with other players (playback pauses at the end of the file and only resets to the beginning when Space is pressed), then they can use this script:
> 
> ```
> mp.add_key_binding("Space", function()
>     if mp.get_property_native("eof-reached") then
>         mp.command("no-osd seek 0 absolute ; set pause no")
>     else
>         mp.command("cycle pause")
>     end
> end)
> ```

**Comment by guidocella** [comment]
It also needs `profile-restore=copy` to work multiple times.

```
[replay]
profile-cond=eof_reached and pause
profile-restore=copy
input-commands=no-osd seek 0 absolute
```

 The script is better if you're willing to add it.

**Comment by c02y** [comment]
> It also needs `profile-restore=copy` to work multiple times.
> 
> ```
> [replay]
> profile-cond=eof_reached and pause
> profile-restore=copy
> input-commands=no-osd seek 0 absolute
> ```
> 
> The script is better if you're willing to add it.

Yeah, it still seeks to the beginning of the file without display OSD. Any way to make it pause at the end, then the config and the script would be identical?

**Comment by guidocella** [comment]
That needs a script.

**Comment by Honghe** [comment]
> You can use a Lua script for this
> 
> mp.observe_property("pause", "bool", function(name, value)
>     if value == true and mp.get_property("eof-reached") == "yes" then
>         mp.command("no-osd seek 0 absolute")
>     end
> end)

The script is in conflict with my config, that is my `keep-open-pause=yes` not works.
```
keep-open=yes  
keep-open-pause=yes
```

So I use this script instead, using `add_forced_key_binding`:
```
mp.add_forced_key_binding("SPACE", "replay-if-eof", function()
    local eof = mp.get_property("eof-reached")
    if eof == "yes" then
        mp.commandv("seek", "0", "absolute+exact")
        mp.set_property_bool("pause", false)
    else
        mp.command("cycle pause")
    end
end, {repeatable = false})
```
