### ISSUE TITLE
symbol lookup error: /lib/x86_64-linux-gnu/libva-x11.so.2: undefined symbol: va_fool_postp

### ISSUE THREAD

**Issue by MoonlightCCU** [mpv-player/mpv#11185]
### Important Information

Information:
- mpv version: 0.34.1-1ubuntu3
- OS: Ubuntu 22.04.1 LTS x86_64
- Source of the mpv binary: [jammy (22.04LTS)](https://packages.ubuntu.com/jammy/mpv) (video): video player based on MPlayer/mplayer2 [universe]
0.34.1-1ubuntu3: amd64 arm64 armhf ppc64el s390x
- Host: HP Laptop 14-dq0xxx 
- Kernel: 5.15.0-58-generic 
- Shell: bash 5.1.16 
- Resolution: 1366x768 
- DE: GNOME 42.5 
- WM: Mutter 
- CPU: Intel Pentium Silver N5030 (4)  
- GPU: Intel GeminiLake [UHD Graphics]   
- Driver: "i915"
- Driver Modules: "i915"
                             
![image](https://user-images.githubusercontent.com/123143963/213630688-127a3ed7-c10e-4ab5-ae55-2a91a805bb6e.png)

I had this error after installing libva 2.17.0 from https://github.com/intel/libva and I think it's because in the realease 2.15.0 the va_fool support has been removed https://github.com/intel/libva/releases/tag/2.15.0

**Comment by sfan5** [comment]
You can indeed not replace random parts of your system without ensuring it fits with the rest (and recompiling as necessary).
