### ISSUE TITLE
Audio Choppy/Stutters as if it was dropping frames when playing video files

### ISSUE THREAD

**Issue by metalune1** [mpv-player/mpv#11187]
### Important Information

Provide following Information:
- mpv 0.35.0 ffmpeg 4.4.3
- voidlinux (rolling release) (glibc version)
- voidlinux repositories
- i3 version 4.22
- unsure, it's an old radeon driver for "AMD ATI Mobility Radeon X1300"

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
It is since I am on this laptop, it's a Lenovo ThinkPad T60, there are no issues with other media playback application like `musikcube` or `vlc` I also tried to switch between `pipewire` and `pulseaudio` but to no avail, also played around with the buffer sizes for all of them. Nothing has worked so far, there are no real steps to reproduce.

it works on pure audio files, (mp3, even high bitrate flac) but as soon as I try to play a video file with it, it starts to sounds crackly or as if it was dropping video & audio frames together (but it doesn't actually drop video frames)

Please tell me what to do so I can try to narrow down the issue, I know that this is probably not reproducible on other systems :/

### Expected behavior
Smooth playback like on pure audio files

### Actual behavior
Choppy audio playback, sounds somewhat stuttery, with tons of little hickups in between, sounds as if it was dropping every couple ms some audio information

### Log file
`https://0x0.st/ohv8.txt`

### Sample files
Downloaded version of this, with highest settings: https://odysee.com/@BrodieRobertson:5/chromium-fixes-decade-old-linux-scroll:0

**Comment by Dudemanguy** [comment]
What version of pipewire are you on? Sounds similar to #11055 which was fixed upstream (no clue if it's the same issue).

**Comment by metalune1** [comment]
> What happens with --no-config and/or --no-video

--no-config makes no difference as mentioned, but indeed, `--no-video` does fix it, that's quite interesting. Since the computer is really old, I suppose the video playback interferes with the audio playback.

**Comment by metalune1** [comment]
> What

I'm using version 0.3.63

**Comment by t-8ch** [comment]
What's the CPU usage, does hwdec help?

**Comment by metalune1** [comment]
CPU Usage is around 70%-90% but I don't know what hwdec codecs my card supports so what value should I give it?

**Comment by Dudemanguy** [comment]
>I'm using version 0.3.63

Give 0.3.64 a try if you can.

**Comment by metalune1** [comment]
But it's not using pipewire anymore, I have it already uninstalled :/

**Comment by t-8ch** [comment]
What's the output of "vainfo"?
Try "hwdec=auto" or "hwdec=vaapi"

**Comment by metalune1** [comment]
hwdec set to auto (with vaapi it only does the r300 driver missing thing)
```
r300: driver missing
[vaapi] libva: /usr/lib64/dri/r600_drv_video.so init failed
[ffmpeg] AVHWDeviceContext: Cannot load libcuda.so.1
[ffmpeg] AVHWDeviceContext: Could not dynamically load CUDA
r300: driver missing
[vaapi] libva: /usr/lib64/dri/r600_drv_video.so init failed
r300: driver missing
[vaapi] libva: /usr/lib64/dri/radeonsi_drv_video.so init failed
[ffmpeg/video] h264: Failed setup for format vdpau: hwaccel initialisation returned error.
```

**Comment by t-8ch** [comment]
What about vainfo?
I have a T400 and it can't do software decoding.
And in hardware not all h264 codecs

**Comment by metalune1** [comment]
How do I run `vainfo` ? There is no such command on my system

**Comment by metalune1** [comment]
ok, figured it out, this is the result:
```
libva info: VA-API version 1.17.0
libva info: Trying to open /usr/lib64/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_16
r300: driver missing
libva error: /usr/lib64/dri/r600_drv_video.so init failed
libva info: va_openDriver() returns 2
libva info: Trying to open /usr/lib64/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_16
r300: driver missing
libva error: /usr/lib64/dri/radeonsi_drv_video.so init failed
libva info: va_openDriver() returns 2
vaInitialize failed with error code 2 (resource allocation failed),exit
```

**Comment by metalune1** [comment]
I now managed to figure out that trying to get hwdec to work is pointless, I ran `VDPAU_DRIVER=radeonsi vdpauinfo` and it showed me that nothing except MPEG1 and MPEG2 is supported, and none of the video files I have use that anyways, they use VP1 or H264 or similar

**Comment by metalune1** [comment]
I figured out something, it is **directly** linked to the video FPS.
when I try to play any video with `--no-correct-pts --fps 1` then the crackle/pop only happens once a second, and if I do the same with `--fps 15` then approx 15 times a second.

**Comment by t-8ch** [comment]
How is CPU usage on other players?

**Comment by metalune1** [comment]
oh shit now its' happening on vlc too... what the hell, I guess this isn't related to mpv directly after all. But to answer your question, the CPU usage goes to 100% and there are frames being dropped left and right

**Comment by metalune1** [comment]
Closing this as I have figured out the problem.
The reason why the audio sounded choppy is because the CPU usage is way too high, I now need to figure out if maybe this gets better if I just use an external sound card or if the issue perists, if so I'll just have to look out to avoid high cpu usage, however that may be...

**Comment by t-8ch** [comment]
On my T400 I went with media with lower resolution/FPS

**Comment by MacGyverNL** [comment]
@metalune1 Can you please try running with
```
PIPEWIRE_CONFIG_NAME=client-rt.conf mpv
```
and report back how that affects your issue? High CPU usage by itself shouldn't make audio unplayable. Using client-rt.conf makes the audio thread more responsive, hopefully eliminating the audio *crackle* at least, but it may have side-effects when the system is under heavy load that I'd be curious to know about.

See https://github.com/mpv-player/mpv/pull/11329 for a PR that would make this the default, and https://github.com/mpv-player/mpv/issues/9992#issuecomment-1435785244 for the rationale behind it.
