### ISSUE TITLE
Don't remember the end position for save-position-on-quit option

### ISSUE THREAD

**Issue by HubKing** [mpv-player/mpv#11184]
### Expected behavior of the wanted feature
I have set `save-position-on-quit` in the mpv.conf to watch videos that I had stopped in the middle. I have also set `keep-open` so that I could drag and drop another video file after watching one to the end.

The problem is that MPV stops at the last frame of a video when the video has reached its end, and if I re-open the video later by drag-and-drop, it restores that state (last frame, paused). 

Maybe this is correct in "computer sense", but not in the common sense of human users, in my opinion. No human users would want to remember the "end" position of a video to watch it later. The last position should not be remembered, and next time the user opens the video, it should be played from the beginning (not paused).

### Alternative behavior of the wanted feature
N/A

### Log file
N/A

**Comment by dexeonify** [comment]
The reason for the behaviour and workaround are mentioned in #2045

**Comment by dyphire** [comment]
dup https://github.com/mpv-player/mpv/issues/10776, fixed by https://github.com/mpv-player/mpv/commit/6471afecd0277138efdb3a80dec12dbfff75c72f.
