### ISSUE TITLE
Default Ass Fonts are bad.

### ISSUE THREAD

**Issue by artivision** [mpv-player/mpv#11190]
Good day, the default Fonts for ASS inside MKV are really a bad choice. So when i try to deactivate ASS for the sake of my fonts, then Subs with custom positions go down with the normal ones. Is there an option to force my fonts but no completely disable ASS? Is there an option to disable ASS wile keeping their positions?

**Comment by snylonue** [comment]
Does [`--sub-ass-force-style`](https://mpv.io/manual/master/#options-sub-ass-force-style) help?

**Comment by artivision** [comment]
> Does [`--sub-ass-force-style`](https://mpv.io/manual/master/#options-sub-ass-force-style) help?

It does work, but it is incomplete. The manual only describes FontName and Bold nothing about Border, Shadow, Color, Position, or anything else. Also those function don't have the same names as the non-ass names.

**Comment by thebombzen** [comment]
```
sub-font="Open Sans SemiBold"
sub-font-size=48
sub-border-size=3.0
sub-shadow-offset=1
sub-border-color="#FF111111"
sub-shadow-color="#00101010"
sub-color="#FFFFFFFF"
```
etc.
