### ISSUE TITLE
Get only scaled window dimensions on launch

### ISSUE THREAD

**Issue by eugenesvk** [mpv-player/mpv#11191]
Let's say I have a script that only needs to align a picture to a side of a screen on launch, but then ignore all subsequent OSD changes. So I `mp.observe_property` `osd-dimensions` and do the alignment on the first non-empty OSD property. However, this doesn't work since with the auto-enabled-by-default `hidpi-window-scale` property I seem to be get __two__ non-zero OSD property notifications, which matches the log that says that the window size is set __twice__ (see below for more details)

### Expected behavior of the wanted feature

Have an ability to only get the final OSD size on launch. Or set a config that would read the "scaling" config before window creation and only create the scaled window

### Alternative behavior of the wanted feature

Window size is set twice, pre-scaled and scaled

### Log file

- input file (not attached): 80×200 screenshot (scaled resolution of 40×100) on a Mac with "retina" resolution scaled to 50%
- a simple `tst.lua` script to print out properties [gist](https://gist.github.com/eugenesvk/ee27f889a93d31edfe94dac48a1aabdc)
```
[tst] {"w":0,"h":0,"par":0.000000,"aspect":0.000000,"mt":0,"mb":0,"ml":0,"mr":0}	 ←Δ osd-dimensions
[tst] 1.000000                                                                  	 ←Δ window-scale
[tst] nil                                                                       	 ←Δ current-window-scale
[tst] nil                                                                       	 ←Δ display-hidpi-scale
 (+) Video --vid=1 (png 80x200 1.000fps)
[tst] 2.000000 	 ←Δ display-hidpi-scale
VO: [libmpv] 80x200 rgba
[tst] {"w":80,"h":201,"par":1.000000,"aspect":0.398010,"mt":0,"mb":1,"ml":0,"mr":0}	 ←Δ osd-dimensions
```
↑↑↑ this is the first non-zero OSD size, but
↓↓↓ it changes right away to a "double" and stays this way
```
[tst] 1.002500                                                                            	 ←Δ current-window-scale
[tst] {"w":160,"h":402,"par":1.000000,"aspect":0.398010,"mt":101,"mb":101,"ml":40,"mr":40}	 ←Δ osd-dimensions
```
↑↑↑ how to detect only this change (but NOT all subsequent OSD changes), or set only this 'scaled' size on mpv launch?

- [log](https://gist.github.com/eugenesvk/ce65731b4d7a1ba86532e4791249839d)

**Comment by christoph-heinrich** [comment]
A simple timeout after startup could work `mp.add_timeout(1, function() local dim = mp.get_property_native("osd-dimensions") end)`

Depending on your needs you could also reset a timer every time it gets updated and then take the result once the timeout expires.
```lua
local timeout, dim
local function observer(_, val)
    if not val then return end
    timeout:kill()
    timeout:resume()
    dim = val
end
timeout = mp.add_timeout(0.1, function()
   -- do something with dim
end)
timeout:kill()
mp.observe_property("osd-dimensions", "native", observer)
```
I didn't actually try this, but it should be pretty close.

**Comment by eugenesvk** [comment]
Thanks for the suggestion, I did add a **timeout**, but it's still not a **clean solution**: if the user quickly presses some OSD changing button on launch, I need to filter this action out and not do anything as it's not automatic OSD setup, which I use to move the image around
To counter this I've also added a **count-of-two condition**, which only reacts to the first two OSD changes (and ignores the the timeout after that), which hopefully only catches those 1) non-scaled and 2) scaled events, nothing else. But then not every setup has those two, so it's still not a clean solution

Do you know of a clean way to separate between user-driven OSD changes and these automatic changes on startup?

**Comment by christoph-heinrich** [comment]
I don't think that is possible, but I don't think that's a problem as long as you only react to it in the very beginning.

P.S. I've edited my code example because I've forgotten to unobserve the property (even though that was the reason I've structured it that way).

**Comment by Dudemanguy** [comment]
A bit old but I think you simply just have to wait for two notifications if you have a `display-hidpi-scale` value that's not equal to 1. If hidpi scaling is used, I'm pretty sure it's just always going to scale twice like that. If it's equal to 1 then you only need to check the first one.
