### ISSUE TITLE
OSX: key bindings: modifiers are ignored when scrolling with the trackpad

### ISSUE THREAD

**Issue by eugenesvk** [mpv-player/mpv#11195]
### Expected behavior of the wanted feature

These should work (apparently they do with an external mouse, but not with MacBook's trackpad)
```
WHEEL_UP      	add video-zoom  0.1
Shift+WHEEL_UP	add video-zoom -0.1
```

### Alternative behavior of the wanted feature

This is ignored (for a trackpad)
```
Shift+WHEEL_UP	add video-zoom -0.1
```

### Log file

[log](https://gist.github.com/eugenesvk/90776fabcfaac6aa43533976cc051390)

**Comment by avih** [comment]
The key names can differ between systems and different VOs, try `mpv --input-test --idle` to check the name which mpv sees when you scroll the wheel with shift.

If this does help you bind the right key, please request to re-open.

**Comment by eugenesvk** [comment]
It doesn't help, I've already done than, and mpv doesn't track the modifiers, the input test names are identical for both keybinds: just the `WHEEL_UP`

**Comment by eugenesvk** [comment]
Though when trying with an external mouse, it does catch Shift, so it seems to only bug with the laptop's trackpad. Interesting

**Comment by avih** [comment]
> It doesn't help, I've already done than

OK, next time, if you have further info, please share it.

@Akemi do wheel events support modifiers on OSX?

**Comment by Akemi** [comment]
both wheel events, precise and none-precise, use the same underlying event on the OS level and should support modifiers.

the normal scroll wheel uses this (https://github.com/mpv-player/mpv/blob/c4db110c8e60b5f590d89edd10ab376e55930e43/osdep/macosx_events.m#L139-L143) wrapper to retrieve/use the modifiers.

the trackpad (precise scrolling) uses the mp_input_put_wheel (https://github.com/mpv-player/mpv/blob/6265724f3331e3dee8d9ec2b6639def5004a5fa2/osdep/macos/mpv_helper.swift#L79-L81) function directly without retrieving/using the modifiers. one can probably do the same with as above to make it work.

i assume modifiers already work using this function on other platforms?

**Comment by avih** [comment]
> @avih i assume modifiers already work using this function on other platforms?

Not sure what "using these functions" means, but on Windows modifiers with mouse wheel are identified.

**Comment by Akemi** [comment]
"this function", the one i named "mp_input_put_wheel". if our internal function doesn't work with modifiers then this wouldn't be a mac problem only.

**Comment by avih** [comment]
> "this function", the one i named "mp_input_put_wheel". if our internal function doesn't work with modifiers then this wouldn't be a mac problem only.

The win32 code has this function:
https://github.com/mpv-player/mpv/blob/92a6f2d687e90452c9080a2e0b471ced7557518f/video/out/w32_common.c#L458-L466
called from:
https://github.com/mpv-player/mpv/blob/92a6f2d687e90452c9080a2e0b471ced7557518f/video/out/w32_common.c#L1276-L1283

And we know that modifiers are identified correctly with mouse wheel on Windows, so to me it looks that yes, this function does support modifiers too.
