### ISSUE TITLE
[vo/dmabuf-wayland] vaExportSurfaceHandle() failed (an unsupported memory type was supplied)

### ISSUE THREAD

**Issue by dvoloshyn** [mpv-player/mpv#11198]
### Update
Just checked the docs and found out that only Weston and Sway are supported.
How can I help to make Gnome Wayland supported as well?

### Important Information

- mpv version 
```
mpv 0.35.0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: n5.1.2
```
- Linux Distribution and Version
`Linux 6.1.1-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Dec 21 23:21:50 UTC 2022 x86_64 GNU/Linux`
- Source of the mpv binary
https://software.manjaro.org/package/mpv
- Window Manager and version
Gnome 43.2 Wayland
- GPU driver and version
in kernel amdgpu, Mesa 22.3.1

### Reproduction steps
Open av1 (mkv) or vp9 (webm) video with `mpv --no-config --vo=dmabuf-wayland [video file].`

### Expected behavior
Video is playing

### Actual behavior
Black screen with errors in logs

### Log file
[mpv-all-trace-av1.log](https://github.com/mpv-player/mpv/files/10479795/mpv.log)
[mpv-all-trace-vp9.log](https://github.com/mpv-player/mpv/files/10479832/mpv.log)

### Sample files
Downloaded from https://youtu.be/5tK_3s-74r4
4k 30fps av1
4k 30fps vp9

**Comment by Dudemanguy** [comment]
>How can I help to make Gnome Wayland supported as well?

We should make a better error message, but there's nothing you can do short of patching mutter to support these formats.
