### ISSUE TITLE
--vo gpu gives inferior results compared to --vo vaapi, at least playing HDR-files

### ISSUE THREAD

**Issue by berndbb** [mpv-player/mpv#11194]
### Important Information

**- mpv version:** 
_mpv --version
mpv 0.35.0-76-g3a6ef81705 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Wed Jan 04 11:55:46 2023
libplacebo version: v4.208.0
FFmpeg version: n5.0.1
FFmpeg library versions:
   libavutil       57.17.100
   libavcodec      59.18.100
   libavformat     59.16.100
   libswscale      6.4.100
   libavfilter     8.24.100
   libswresample   4.3.100_

**- Linux Distribution and Version**
_uname -r
5.15.86-1-lts_
on archlinux

**- Source of the mpv binary**
_built with aur-script ("mpv-git")_

**- If known which version of mpv introduced the problem**
_unknown_

**- Window Manager and version**
_Xfce 4.16 from archlinux repository_

**- GPU driver and version**
[glxinfo.txt](https://github.com/mpv-player/mpv/files/10472616/glxinfo.txt)

**- Possible screenshot or video of visual glitches**
![Screenshot_left-VAAPI_right_GPU](https://user-images.githubusercontent.com/6196442/213878533-433fbeea-5ac7-47ae-86d7-d5357836dfc1.png)

### Reproduction steps

[1080p_HDR_sample.zip](https://github.com/mpv-player/mpv/files/10472643/1080p_HDR_sample.zip)

Using:
`mpv --no-config --hwdec=vaapi-copy -vo=vaapi 1080p_HDR_sample.mkv`
the video output seems fine to me.
But mpv reports:
_[vo/vaapi] Warning: this compatibility VO is low quality and may have issues with OSD, scaling, screenshots and more.
[vo/vaapi] vo=gpu is the preferred choice in any case and includes VA-API support via hwdec=vaapi or vaapi-copy._

So I switch to
`mpv --no-config --hwdec=vaapi-copy -vo=gpu 1080p_HDR_sample.mkv`
Now I experience too strong colours (red faces or sunburn-effect) and the movement is skippy or stuttering (although mpv doesn't report dropped frames)

**### Expected behavior**
Using vo=gpu as the recommended choice shouldn't produce inferior playback

So this is maybe more a question than a report of a problem:
Is my hardware too weak to use --vo=gpu or should --vo=gpu always produce at least the same quality as --vo=vappi?

**### Actual behavior**
`--vo vaapi `gives better results than recommended `--vo gpu`.

**### Log file**
[log_vo_gpu.txt](https://github.com/mpv-player/mpv/files/10472659/log_vo_gpu.txt)

**### Sample files**
[1080p_HDR_sample.zip](https://github.com/mpv-player/mpv/files/10472643/1080p_HDR_sample.zip)

**Comment by LaserEyess** [comment]
1. Why are you using `--hwdec=vaapi-copy`? That is explicitly slower than `--hwdec=vaapi`
2. Do you *really* think the left screenshot looks better than the right? Actually?

**Comment by berndbb** [comment]
Actually using vaapi-copy is just a reference from other use-cases. But it is no game changer to use hwdec=vaapi.

Well, point 2 may be is debatable. The vaapi output could be considered to be a little too bright overall and the colours are not like those of a Mary Poppins Technicolor cinema experience meaning for some people they look pale. But I consider the more realistic output to be the one of vaapi, whereas vo=gpu looks to me more like those 8bit video games we had some decades ago.

I can try to add another example where it is more obvious that the colours of va=gpu are too much to be true. Especially the skin looks like everyone has returned from summer holidays and forgot about sun protection.

**Comment by CounterPillow** [comment]
The VAAPI VO does not support HDR, it simply clips off the high range components and doesn't do any tonemapping.
Hollywood's shitty mastering is not mpv's problem.

**Comment by rubyFeedback** [comment]
I remember fefe once complain about something similar. For users it is super-difficult to be able to tell where a problem originates from in this regard. Of course the best would be for mpv to choose the ideal settings as-is, so the user does not have to worry; it's then just the question what the best option is. This can also depend on hardware. For instance, I never had any problem with my last computer (~5 years old) and video stuff. With my current one, I have problems (nvidia, even with the firmware extracted I still have issues).

**Comment by CounterPillow** [comment]
That morbidly obese stain upon the Earth fefe came to complain that vo_gpu wasn't performing well for him (probably because he was on a problematic Intel GPU and didn't set --vd-lavc-dr=no), provided zero log files, and just brigaded the issue tracker with his disgusting G*rman lusers. Please don't advertise his blog any further.

> At the end, it is the movement being fluid and without stuttering which makes vo=vaapi my favourite.

Set --vd-lavc-dr=no, you're on a low-end Intel GPU.

**Comment by mindrunner** [comment]
> Do you really think the left screenshot looks better than the right? Actually?

I was thinking the same... I might prefer the right one (more colors). Also, if I play the sample with `vlc`, I see the more colorful version gets rendered.

Not sure what's going on, but the Video makes my whole system behaving in a weird way.

Playing it with `mpv` the whole desktop becomes very laggy/unresponsive. (swaywm).

Playing it with `vlc` just made the whole session crash. After restarting sway, it immediately froze again and I needed to reboot the computer. Not sure if that is related, but seems very odd. Never had such a system crash in months...

**Comment by berndbb** [comment]
Yes, on my low-end intel GPU vlc decides too for the colourful version.
It seems that I chose to believe the pale version is better just to have proper movement. 

Here is another example:
![Screenshot_2160p_HFR_compare](https://user-images.githubusercontent.com/6196442/213889015-68de489a-dffd-4f38-aeb7-504bf6e91e2c.png)

As CounterPillow wrote, the above image seems to result from vaapi just leaving out some information and the second image shows Hollywoods taste for strong sunbathing.

So case closed, I am experiencing my poor Hardware and Hollywood's "shitty mastering"?

**Comment by Dudemanguy** [comment]
`vaapi` doesn't tonemap and `gpu` does. That's the difference you are seeing. You're welcome to prefer the non-tonemapped image, but it's less accurate to what's actually in the file.
