### ISSUE TITLE
MPV 0.35 SUBTITLE right to left no working in Hebrew

### ISSUE THREAD

**Issue by YOYO48** [mpv-player/mpv#11196]
### Important Information
mpv version 0.35
Windows Version win11
Source of the mpv binary
If known which version of mpv introduced the problem in mpv 0.34 work good
![203169014-68186d10-8da5-4902-8dbb-839c944bd10f](https://user-images.githubusercontent.com/118776337/213931491-ab9430f2-079e-45e1-acb0-34a492fcc0d9.jpeg)
THIS IS MPV 0.34 OK
![203170802-fcbd3131-122f-402b-9de7-668e32462a76](https://user-images.githubusercontent.com/118776337/213931502-333f7e76-8c3c-4f57-9b58-825f99f83739.jpeg)

**Comment by sfan5** [comment]
https://github.com/mpv-player/mpv/issues/10910 https://github.com/mpv-player/mpv/issues/11028
