### ISSUE TITLE
osd-font and stats.conf font doesn't change

### ISSUE THREAD

**Issue by chromer030** [mpv-player/mpv#11208]
### Important Information

Provide following Information:
- mpv version : 0.35.0
- Linux Distribution and Version : ArchLinux
- Source of the mpv binary : Arch Linux Repository
- Window Manager and version : KDE 5.26.5
- GPU driver and version : Intel GPU

### Reproduction steps

Whatever font i set in mpv.conf or using cli `mpv --osd-font=` doesn't change the font and mpv still uses the default one.
stats.conf has same issue : `font=` doesn't apply.

Tried Fonts :
- Roboto
- IBM Plex Serif
and bunch of others.

### Expected behavior
osd and stats.conf font change based of specified parameters

in `mpv -v` there is no error.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/10501913/log.txt)

The issue will be closed for ignoring the issue template.

**Comment by avih** [comment]
> Whatever font i set in mpv.conf or using cli `mpv --osd-font=` doesn't change the font and mpv still uses the default one.
> stats.conf has same issue : `font=` doesn't apply.

You mention `osd-font` and stats font, but your log shows setting of `osd-font` and `sub-font`:
```
Setting option 'osd-font' = 'Roboto' (flags = 4)
...
Setting option 'sub-font' = 'Shabnam Bold'  (flags = 4)
```

You didn't mention whether `sub-font` works or not, does it work?

In general, mpv passes the font name to [libass](https://github.com/libass/libass), and libass is responsible for finding the font by name and then loading it.

It would seem that for some reason libass can't find some or all of your fonts, but that's outside the control of mpv.

> Are you using a variable font? Try using regular fonts.

Variable font is perfectly regular and should work as well. Please don't add noise.

**Comment by avih** [comment]
> ### Log file
> 
> [log.txt](https://github.com/mpv-player/mpv/files/10501913/log.txt)

Your log shows you ran exactly this: `mpv --log-file=log.txt`

This doesn't load any file, doesn't open a window, and can't have any font problem because there's no text rendering at all.

Please provide a log where the problem actually happens, preferably where the mpv command starts with `--no-config` to remove noise from your config files, and set the required font from additional options at the command line.

**Comment by chromer030** [comment]
@avih , thank you for your explanations.
sub font is OK.
New log file with `$ mpv --no-config --osd-font='Roboto' --script-opts=stats-font='Roboto' video.mkv --log-file=txt
`

[Log.txt](https://github.com/mpv-player/mpv/files/10509887/Log.txt)

**Comment by avih** [comment]
> New log file with `$ mpv --no-config --osd-font='Roboto' --script-opts=stats-font='Roboto' video.mkv --log-file=Log.txt `
> 
> [Log.txt](https://github.com/mpv-player/mpv/files/10509887/Log.txt)

```
...
[   0.886][v][osd/libass] fontselect: (Roboto, 400, 0) -> /usr/share/fonts/Shabnam/Shabnam.ttf, 0, Shabnam
[   0.886][v][osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/Shabnam/Shabnam.ttf, 0, Shabnam
[   0.887][v][osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> /usr/share/fonts/Shabnam/Shabnam.ttf, 0, Shabnam
```

To me that looks as if all font names end up using `/usr/share/fonts/Shabnam/Shabnam.ttf`.

I don't know why that is, but i'm guessing this is maybe how your fontconfig is set up. Either way, that's between fontconfig and libass, and outside the control of mpv.

> sub font is OK.

Do you mean that you can choose any font for `sub-font` and it works like you configured it, even "Roboto"? or that it only works correctly when you choose the font "Shabnam" ?

**Comment by chromer030** [comment]
Thanks to you i found what makes the problem , in `local.conf` i need to prepend Shabnam font in order to render this language's characters in a better font as the default one is really bad  :

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
	<match target="pattern"> 
		<edit name="family" mode="prepend"> 
		<string>Noto Color Emoji</string> 
		</edit> 
	</match> 
	 <match>
  		<edit name="family" mode="prepend">
		<string>Shabnam</string>
  		</edit>
	</match>
</fontconfig>

```
So i should change my font config for affecting just Persian language not all.

Thanks very much for your explanations and troubleshooting. You are awesome.

**Comment by astiob** [comment]
I don’t know Fontconfig very well, but (based on the log and the local.conf excerpt) I think your Fontconfig configuration overrides every single font family request with Noto Color Emoji, and then overrides every single font on your system (including Noto Color Emoji) with Shabnam.

If you just want to make Fontconfig prioritize Shabnam over other fonts, I think pattern modification isn’t the right tool, not even one limited to a specific language. It’s meant to enable generic aliases like `serif` and `sans-serif`, or font-specific aliases like `Helvetica` for `Arial`, etc. If you have a particular font that is bad, you could exclude that particular font using `<rejectfont>` or just add a better font ahead of it in the font list/with higher priority.

**Comment by astiob** [comment]
@chromer030 Do you actually have Noto Color Emoji installed?

**Comment by astiob** [comment]
Sorry, that ping seems irrelevant. Actually testing the config in libass, I see it prepends _both_ Shabnam (first) and Noto Color Emoji (second) to each request. So then it naturally picks Shabnam.

**Comment by chromer030** [comment]
@astiob 
Thank you for your great guide.
I changed fontconfig from `prepend` pattern to `prefer` pattern and issue solved not only in mpv but in some other apps too.
I need to use `Noto Color Emoji` for adapting emoji support in system-wide KDE , because in some qt apps emoji is broken but with this pattern it comes back.

With following fontconfig in local.conf , the issue is fixed and there is no obligation (`prepend`) anymore to break font rules :
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
	<alias>
		<family>sans-serif</family>
		<prefer>
		<family>Roboto</family>
		<family>Shabnam</family>
		<family>Noto Color Emoji</family>
		</prefer>
	</alias>
	<alias>
		<family>serif</family>
		<prefer>
		<family>Roboto</family>
		<family>Shabnam</family>
		<family>Noto Color Emoji</family>
		</prefer>
	</alias>
	<alias>
		<family>monospace</family>
		<prefer>
		<family>Roboto Mono</family>
		<family>Shabnam</family>
		<family>Noto Color Emoji</family>
		</prefer>
	</alias>
</fontconfig>

```
