### ISSUE TITLE
gpu-api=vulkan doesn't work with vo=gpu on AMD RX 6700XT

### ISSUE THREAD

**Issue by hrzhu** [mpv-player/mpv#11205]
### Important Information

Provide following Information:
- mpv git master built with mpv-build
- Kubuntu 22.04
- mesa 22.2.5 from kisak ppa

### Reproduction steps
Open file with `mpv --no-config --vo=gpu --gpu-api=vulkan`. 

### Expected behavior
Video plays just fine.

### Actual behavior
It takes quite a while for mpv window to appear and it makes my DE laggy. The video playback is extremely laggy. No problem with `mpv --no-config --vo=gpu-next --gpu-api=vulkan` BTW.

### Log file

[mpv.log](https://0x0.st/oF8L.log)

**Comment by hrzhu** [comment]
Windows build(https://jaist.dl.sourceforge.net/project/mpv-player-windows/release/mpv-0.35.1-x86_64-v3.7z) has the same problem.

**Comment by thebombzen** [comment]
What happens if you add `--gpu-context=x11vk`?

**Comment by hrzhu** [comment]
Adding `--gpu-context=x11vk` doesn't fix the problem.
I have one more observation. The problem only happens with `--vulkan-device='AMD Radeon RX 6700 XT (RADV NAVI22)' ` which is my default device.
With `mpv --no-config --vo=gpu --gpu-api=vulkan --vulkan-device='llvmpipe (LLVM 15.0.6, 256 bits)'`, it just works fine.
With `mpv --no-config --vo=gpu --gpu-api=vulkan --vulkan-device='Intel(R) Graphics (RKL GT1)'`, video plays fine despite of some warnings:
``` 
[vo/gpu/libplacebo] Storable format 'bgr565' has no matching GLSL format qualifier but read/write without format is not supported.. disabling
[vo/gpu/libplacebo] Storable format 'rgb565' has no matching GLSL format qualifier but read/write without format is not supported.. disabling
[vo/gpu/libplacebo] Storable format 'bgr5a1' has no matching GLSL format qualifier but read/write without format is not supported.. disabling
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:785: FINISHME: support more multi-planar formats with DRM modifiers
```
To use vulkan with my RX 6700 XT, I have to use `--vo=gpu-next`.

**Comment by hrzhu** [comment]
https://github.com/haasn/libplacebo/commit/36ed28fc340983b4c4d4f2e0dea0d4619affd266 fixed the issue on Linux. Still waiting for a new Windows build with that libplacebo commit included, I'll close this if it also works on Windows.
