### ISSUE TITLE
Can't use "\0" in str:gmatch for a lua script

### ISSUE THREAD

**Issue by Anskrevy** [mpv-player/mpv#11204]
### Important Information

Provide following Information:
- mpv version = 0.35.0
- Platform and Version = Arch Linux
- Source of the mpv binary = Official Arch repository

### Reproduction steps
I'm writing a lua script that uses this split function 
```
function split(str, sep)
    local t = {}
    local sub = '\0'
    for substr in str:gsub(sep, sub):gmatch("([^" .. sub .. "]+)") do
        table.insert(t, substr)
    end
    return t
end
```
This function works just fine if run directly through lua using the interactive flag.
But I get the following error from mpv when I try and use this function in a script
```
split:  /home/anskrevy/.config/mpv/scripts/split.lua:30: in function 'split'                      
split:  /home/anskrevy/.config/mpv/scripts/split.lua:14: in function 'handler'                    
split:  mp.defaults:510: in function 'call_event_handlers'                                        
split:  mp.defaults:552: in function 'dispatch_events'                                            
split:  mp.defaults:503: in function <mp.defaults:502>                                            
split:  [C]: at 0x55ed6a44d590                                                                    
split:  [C]: at 0x55ed6a44da50                                                                    
split: Lua error: /home/anskrevy/.config/mpv/scripts/split.lua:30: malformed pattern (missing ']')
```
### Expected behavior
I would expect the function to work like it does in lua and return a table of the split string.

### Actual behavior
mpv can't seem to parse the script.

This function and the script as a whole works fine if I set `sub` to `'\n'`.

**Comment by christoph-heinrich** [comment]
Works in lua (interpreter) but doesn't work in luajit.

**Comment by Anskrevy** [comment]
You're right, my bad. Replacing `'\0'` with `'%z'` solved it.
