### ISSUE TITLE
OSC titles messed up by multiline strings

### ISSUE THREAD

**Issue by ALTree** [mpv-player/mpv#11209]
### Important Information

- mpv version **0.35.0**
- Linux Distribution and Version **Debian on a 6.1.0-1 kernel**
- Source of the mpv binary **debian package**
- Window Manager and version **xfwm4 4.18.0**

### Reproduction steps

When opening a file with a multiline title in its Metadata, the title strings leave the OSC area to float in the middle of the screen in a big font. Good file:

![good](https://user-images.githubusercontent.com/3586803/214637198-d6914ecb-abc8-451c-a23d-03ee78cd71f8.png)

Change metadata to include a multiline title:
```
$ ffmpeg -i obayashi.webm -metadata title="


a multiline title" -c copy bug.webm
```
```
$ ffprobe bug.webm |& grep -m1 -A3 Metadata:
  Metadata:
    title           : 
                    : 
                    : a multiline title
```

Result:

![bad](https://user-images.githubusercontent.com/3586803/214638328-e1549450-b1a8-4d1d-88f4-b17e68c60776.png)

Reproducible on `--no-conf`.
[out.log](https://github.com/mpv-player/mpv/files/10502046/out.log)

I've actually seen this in the wild on a file I was playing.

**Comment by guidocella** [comment]
This would be fixed by https://github.com/mpv-player/mpv/pull/10149
