### ISSUE TITLE
Question on mpv configs on GitHub

### ISSUE THREAD

**Issue by Zabooby** [mpv-player/mpv#11218]
I have been updating my personal [config](https://github.com/Zabooby/mpv-config) and have been looking at other peoples setups. One thing I noticed was how often people add settings to their mpv.conf when the setting is already on by default as stated in the [manual](https://mpv.io/manual/stable/).

Is there a reason for this, are the defaults stated in the manual wrong or don't apply if for example you use profile=gpu-hq/gpu-next or vo=gpu or do people just not read the manual?

**Comment by adisib** [comment]
Defaults can change. If you want something a specific way then specifying it prevents the possibility of things changing after an update.

**Comment by llyyr** [comment]
They're copying configs without knowing what it does, defaults don't actually change that often.

**Comment by Zabooby** [comment]
> They're copying configs without knowing what it does, defaults don't actually change that often.

How am I supposed to know when defaults do change, are there certain settings that cause this (profile= or vo=)?

**Comment by hooke007** [comment]
> when defaults do change

You've answered your question.

> read the manual

**Comment by Zabooby** [comment]
Ok thanks, people should really read the manual, the amount of configs with pointless settings is so high and it just grows as other people copy their configs.
