### ISSUE TITLE
mpv ignores keyboard inputs under sway/wlroots with more than 1 seat configured

### ISSUE THREAD

**Issue by chron-isch** [mpv-player/mpv#11217]
### Important Information

Provide following Information:
- mpv 0.35.0
- Archlinux
- Tried with the repository version, self-build 0.35.0 as well as mpv-git
- swaywm 1.8 / wlroots 0.16.1
- Intel Corporation HD Graphics 615 / i915

### Reproduction steps

Sway/wlroots allows you to create seats to group input devices together. In my case I wanted to have a separate seat for my touchscreen and stylus.

```
swaymsg seat seat1 attach 1267:9754:ELAN9038:00_04F3:261A_Stylus
swaymsg seat seat1 attach 1267:9754:ELAN9038:00_04F3:261A
```
```
smsg -t get_seats
Seat: seat1
  Capabilities: 5
  Devices:
    ELAN9038:00 04F3:261A
    ELAN9038:00 04F3:261A Stylus

Seat: seat0
  Capabilities: 3
  Devices:
    Microsoft Surface Type Cover Touchpad
    Microsoft Surface Type Cover Mouse
    Microsoft Surface Type Cover
    Microsoft Surface Type Cover Consumer Control
    Microsoft Surface Type Cover Consumer Control
    Logitech MX Master 2S
    Logitech MX Master 2S
    HID 046a:0076
    HID 046a:0076
    HID 046a:0076
    AT Translated Set 2 keyboard
    Intel HID switches
    Intel HID 5 button array
    Intel HID events
    Lid Switch
    Power Button
    Video Bus
```

The problem also occurs if you simply create a new seat for a second keyboard/mouse.

```
swaymsg seat seat_new attach $INPUT_DEVICE
```
Where $INPUT_DEVICE is the device identifier from `swaymsg -t get_inputs`.

The moment the second seat is created mpv stops responding to keyboard inputs.

### Expected behavior
mpv should still respond to keyboard inputs.

### Actual behavior
mpv stops responding to keyboard inputs.

The moment I remove the second seat everything works again.

### Log file
Couldn't find anything related to the issue, you can find the logfile here.
https://0x0.st/oFQy.log

**Comment by Dudemanguy** [comment]
Yeah I don't think we try to handle multi-seat stuff at all.

**Comment by Dudemanguy** [comment]
By the way, do you know if multi-seat works in xorg too? I know X11 has the same feature, but I'm not sure how it works there or if mpv even has to do anything special to handle it like it would in wayland.

**Comment by chron-isch** [comment]
Sorry, I have no idea. I've been using wayland/sway for 2+ years now but I guess I could pull out an old machine and give it a try if I've got some spare time tomorrow.
