### ISSUE TITLE
mpv DUMMY: OK to use name and icon?

### ISSUE THREAD

**Issue by vitorgalvao** [mpv-player/mpv#11213]
On macOS I want mpv as a CLI tool installed via Homebrew. But I also want the app bundle so I can associate it to file types. I’ve tried multiple approaches over the years and I have never been quite satisfied.

So I created [mpv DUMMY](https://github.com/vitorgalvao/mpv-dummy/). The README explains everything, but it’s essentially an app bundle to open the CLI version of mpv. The app is signed and notarised.

I want it to work for me as a replacement to any other mpv bundle, so while the bundle identifier is different, the name is `mpv.app` and I’m using mpv’s icon. **Is that OK?** I try to make it clear in the README what the app is, always capitalise “DUMMY”, and I’m not using the icon anywhere in the repo (only the downloaded app).

Soft ping to @pigoz and @tenzerothree, considering the [commit which introduced the icons](https://github.com/mpv-player/mpv/commit/303096bcb2b5f52ea51d5d7ddb738689b08a0a2f).

**Comment by sfan5** [comment]
I don't see anything problematic with using the mpv icon and name for something that literally opens mpv.
Do you plan to contribute this to Homebrew?

**Comment by vitorgalvao** [comment]
> I don't see anything problematic with using the mpv icon and name for something that literally opens mpv.

Thank you. Feel free to close the issue at will whenever you feel is appropriate / are satisfied with the outcome.

> Do you plan to contribute this to Homebrew?

There is a threshold (number of stars/forks) for new additions, which mpv DUMMY doesn’t yet pass on account of being so new. I’m OK with having it in Homebrew Cask when it passes that threshold, but I’m also OK with not having it there if that is the wish of the mpv maintainers. I very much made this for my own use, but I know there’s a niche (even if just a handful of people) who have been looking for a solution to the same problem.
