### ISSUE TITLE
The --watch-later-directory command does not work on my Android phone

### ISSUE THREAD

**Issue by deedeenelson994** [mpv-player/mpv#11220]
Adding the --watch-later-directory command to mpv.conf does nothing. It works on LDPlayer (both rooted and non-rooted) and my Android TV box (MeCool KM2), but it does not work on my phone. It's a Samsung S22 Ultra with all the latest updates installed. Does anyone have any idea what might be causing it not to work on my phone?

Mpv version: 2022-07-30-release

**Comment by avih** [comment]
Please provide a log of when the value is set and yet not used [correctly].

**Comment by deedeenelson994** [comment]
> Please provide a log of when the value is set and yet not used [correctly].
> 
> Also, you should first try in https://github.com/mpv-android/mpv-android

Here's my mpv.conf:

--save-position-on-quit
--watch-later-directory=/storage/emulated/0/watchlater
--resume-playback-check-mtime
--write-filename-in-watch-later-config
--ignore-path-in-watch-later-config

**Comment by avih** [comment]
> Also, you should first try in https://github.com/mpv-android/mpv-android
