### ISSUE TITLE
Feature request: refresh subtitles

### ISSUE THREAD

**Issue by lucmp** [mpv-player/mpv#11229]
I translate subtitles and I don't like the existing subtitle editors. I wish I could write in another application and check my work in mpv. The problem is, I translate a few subtitles, I view that part, I fix problems, improve the translation, watch again, OK, proceed, do that a thousand times in one movie or episode. I can't view the scene with changed subtitles until I reload the entire video again. And seek to that exact point again. Every single time. That is just an option.
What I want is a "refresh subtitles" command that will reload the subtitle file without reloading the video. Ideally, I should be able to "hook" it to the rewind command so every time I rewind a few seconds, mpv will reload the subtitle file. That would be excellent.

**Comment by christoph-heinrich** [comment]
I don't know if this will work, but you can try the reload functionality built into [quality-menu](https://github.com/christoph-heinrich/mpv-quality-menu).

Otherwise what will certainly work is [restarting mpv](https://github.com/stax76/mpv-scripts/blob/e8ff33e18197e10e458e0392b337b5da4a420049/misc.lua#L490-L512), but you might have to extend it depending on your needs.

**Comment by dyphire** [comment]
https://mpv.io/manual/master/#command-interface-sub-reload
Doesn't it work?

**Comment by lucmp** [comment]
> https://mpv.io/manual/master/#command-interface-sub-reload Doesn't it work?

Yes, it works! I couldn't find it in the manual.
OK then. This is solved. Sorry and thank you.

**Comment by lucmp** [comment]
Requested feature already exists.

**Comment by slrslr** [comment]
> https://mpv.io/manual/master/#command-interface-sub-reload

If anyone is wondering how to enable it exactly on Linux, then this worked:

run:
`nano ~/.config/mpv/input.conf # opens a file in editor`
Insert new line into opened file:
`r sub-reload`
re-open mpv and hit "r" key when needed to reload currently used subtitle file.

Note that "r" seems to have been previously used to re-locate the subtitle line vertically.
