### ISSUE TITLE
Hardware decoding memory cannot be released

### ISSUE THREAD

**Issue by DSxiaolong** [mpv-player/mpv#11228]
Example code：mpv-examples-master\libmpv\qt\qtexample.pro

Hardware decoding: `mpv_set_option_string(mpv, "hwdec", "auto");`

 version :  [mpv-x86_64-20221023-git-395b37b.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20221023-git-395b37b.7z/download)

 issue:  `mpv_terminate_destroy(mpv);`   Unable to free all memory   。    Open and close the playback window several times, and the memory will keep rising

**Comment by kasper93** [comment]
You need to provide more info. I've checked and I don't see anything special. But I can only guess your setup. What does it mean "keep rising"? 5MB or 500MB? What hwdec you are actually using? Please use `mpv-examples/libmpv/simple/simple.c` to minimize testcase and provide more details about your setup.

**Comment by Dudemanguy** [comment]
Most likely, this is just `d3d11va` leaking which was fixed after his linked mpv version. Please update.
