### ISSUE TITLE
Hardware decoding not working with d3d11va-copy

### ISSUE THREAD

**Issue by Zabooby** [mpv-player/mpv#11222]
Important Information:

- mpv 0.35.0-129-g92a6f2d687
- Windows 11
- Shinchiro binary
- GeForce mx450 (dedicated graphics)
-  intel iris xe graphics (integrated graphics) 
- My full [config](https://github.com/Zabooby/mpv-config)
![image](https://user-images.githubusercontent.com/78969986/215275440-a23d0cba-c177-468a-945e-2c3bbf66368d.png)

My mx450 does not support hwdec so I wanted the mx450 to run mpv while letting intel xe graphics do hwdec and was told `d3d11va-copy` could do this. Since then I didn't have a brain to actually check if it was working until now, when I get the error above. 

For more context see my old issue  #10243. 

Log file:
https://pastebin.com/Rtw2m2Yd

**Comment by Zabooby** [comment]
I tried it and get this error:
![image](https://user-images.githubusercontent.com/78969986/216761377-5176a706-32b8-4491-bc95-8f9084a85992.png)
Logs: 
https://pastebin.com/7JWyj1AS
Is there a reason why `hwdec=d3d11va-copy` isn't working for me?

**Comment by thebombzen** [comment]
It's attempting to use the same GPU (the nvidia GPU) to do hardware decoding, which it doesn't support. You can try setting `hwdec=auto-copy` but ideally you're playing a 1080p H.264 video, so you shouldn't need or want hardware decoding at all.

**Comment by Zabooby** [comment]
> It's attempting to use the same GPU (the nvidia GPU) to do hardware decoding, which it doesn't support. You can try setting `hwdec=auto-copy` but ideally you're playing a 1080p H.264 video, so you shouldn't need or want hardware decoding at all.

Would `hwdec=auto-copy` try and use the integrated gpu instead? Also what video file type should I use to test if hardware decoding is working the way I want it to?

**Comment by FinnRaze** [comment]
```
hwdec=d3d11va-copy
d3d11-adapter=NVIDIA
```

**Comment by Zabooby** [comment]
Ok it works now, when I check the task manager it says GPU 1 is being used which is the nvidia one. 

However in the windows graphics settings and Nvidia control panel, I set mpv to use the integrated graphics doesn't this mean mpv will use the integrated graphics to hardware decode **and** run mpv, instead of letting the nvidia graphics to run mpv?

Also what does `d3d11-adapter=NVIDIA` do

I also get this error now 
![image](https://user-images.githubusercontent.com/78969986/218983739-e5f1a909-9892-465c-9504-1f5dc1896a64.png)

Logs:
https://pastebin.com/W7rsysxS

**Comment by FinnRaze** [comment]
The option `d3d11-adapter` appoints a GPU to do rendering so you can see "3D engine" active in taskmanager.
Hardware decoders utilizing the D3D11 rendering abstraction's helper functionality to receive a device,such as D3D11VA or DXVA2's DXGI mode, will be affected by this choice,but the MX-series GPUs don't support hwdec,so it would just do rendering job.

mpv tries to output videos through the appointed GPU ,while the MX-series GPUs don't have any video output,which causes this error.mpv would automatically select an usable output,so this error doesn't matter.

**Comment by Zabooby** [comment]
> The option `d3d11-adapter` appoints a GPU to do rendering so you can see "3D engine" active in taskmanager. Hardware decoders utilizing the D3D11 rendering abstraction's helper functionality to receive a device,such as D3D11VA or DXVA2's DXGI mode, will be affected by this choice,but the MX-series GPUs don't support hwdec,so it would just do rendering job.
> 
> mpv tries to output videos through the appointed GPU ,while the MX-series GPUs don't have any video output,which causes this error.mpv would automatically select an usable output,so this error doesn't matter.

Just to confirm before I close this issue, `d3d11-adapter` basically is used in place of the windows graphics and Nvidia control panel settings, so that `hwdec=d3d11va-copy` can work. Aka it effectively does the same thing.

**Comment by FinnRaze** [comment]
Not exactly.If you appointed Nvidia GPU in Windows graphics or Nvidia control panel settings,and the GPU is unable to do hwdec,mpv would drop to software decode even though you have `hwdec=d3d11va-copy`
