### ISSUE TITLE
gpu_next: //!PARAM in shader can't be parsed

### ISSUE THREAD

**Issue by pintassilgo** [mpv-player/mpv#11238]
### Important Information

Provide following Information:
- mpv version: 0.35+git.20221222.657fd280, but also tested with 0.35.1 flatpak
- Platform and Version: openSUSE Tumbleweed Plasma Wayland
- Source of the mpv binary: openSUSE official repo, also tested with flathub's flatpak

GPU: Radeon RX 570

### Reproduction steps

Save this folder as mpv config:
https://github.com/Natural-Harmonia-Gropius/mpv_config/tree/main/portable_config

Play a HDR video. The result is not as expected (very wrong colors) because the shaders aren't working.

More information here:
https://github.com/Natural-Harmonia-Gropius/mpv_config/issues/14

### Expected behavior

Video should have good colors, as this config promises to produce great HDR to SDR tone mapping results.

### Actual behavior

Video has very wrong colors because the shaders aren't working. From the log, some shaders aren't working due to mpv (or libplacebo, I don't no) not being able to recognize some comands like `//!PARAM`.

libplacebo is also in its latest version, v5.229.2.

### Log file

https://pastebin.com/jmhYuUgp

### Sample files

The HDR example video I used: `https://www.youtube.com/watch?v=hVvEISFw9w0`

**Comment by haasn** [comment]
libplacebo version unfortunately too old. You need the latest experimental version built from git master. This functionality hasn't made its way into any stable release yet.
