### ISSUE TITLE
Now Playing menu bar item not behaving properly on macOS 

### ISSUE THREAD

**Issue by hotsno** [mpv-player/mpv#11233]
### Important Information

- mpv version
  - 0.34.0-501-g161bdd9359
- macOS Version
  - Ventura 13.2
- Source of the mpv binary or bundle
  - Built from source [using this guide](https://gist.github.com/dbrookman/74b8bcfb37a23452f7137b83bca9580f)
- If known which version of mpv introduced the problem
  - Always been an issue IIRC
- Possible screenshot or video of visual glitches
<img width="393" alt="image" src="https://user-images.githubusercontent.com/71658949/215349368-52594a48-1f08-4f62-b3c3-88b6075f9f7a.png">

### Reproduction steps

Open .mkv or .mp3 file in mpv from terminal using `mpv --no-config <path to file>` or open said file in mpv from Finder. Check Now Playing menu bar item (enabled in macOS by default, but make sure it's enabled).

### Expected behavior

Progress bar should update in the Now Playing menu bar item. There should be a current and end timestamp. You should be able to navigate the progress using the progress bar bar. It should show the title of what is being played.

### Actual behavior

Progress bar shows no progress. No current/end timestamps show. Can't navigate progress using the progress bar bar. No title is shown.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/10530593/output.txt)

**Comment by hotsno** [comment]
Now that I think about it this is most likely not a bug but should be a feature request 🙂

**Comment by akshatakulkarni25** [comment]
hey @hotsno , can i work on this issue.

**Comment by Akemi** [comment]
we actually already had a pr for this #11265 though it was closed.

also feel free to work on this and open a PR.

**Comment by flightmansam** [comment]
Yep can confirm this is still broken. I would be nice to get the currently playing metadata shown if possible (album artwork, title, etc). I am happy to work on this, any idea where I should start looking? Are there mpv command line arguments related to this?

**Comment by Akemi** [comment]
it's not broken. it's just not intended to work because it was not implemented.

see the PR linkes a comment above yours. nor commands.

**Comment by mjec** [comment]
@flightmansam are you (interested in) working on this? If not I might take a stab at it this weekend

**Comment by flightmansam** [comment]
I have to be honest I haven't got the foggiest clue where to start on this! If you have an idea please go for it!

**Comment by Menghini** [comment]
I would also like to see this feature implemented.

**Comment by flightmansam** [comment]
@mjec how did you go with this?

**Comment by Akemi** [comment]
opened a PR #13450 for the requested feature + some more.
