### ISSUE TITLE
`blend-subtitles=video` equivalent

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#11231]
Is there a way to get `--blend-subtitles=video` behaviour with `gpu-next`? Just any way to render subtitles at video resolution would do, I don't use interpolation.

**Comment by Dudemanguy** [comment]
Is `---no-sub-scale-by-window` what you're looking for?

**Comment by kkanungo17** [comment]
For ASS subtitles it doesn't really seem to do anything different, even with `sub-ass-override=scale/force` set.

But even going by the description, the option basically fixes the font size, but that's not what I want. Like `blend-subtitles=video` I want the subtitles to render at video resolution first, then the whole thing to be scaled afterward.
