### ISSUE TITLE
Segmentation fault when requesting hardware decoding

### ISSUE THREAD

**Issue by nicolaasjan** [mpv-player/mpv#11239]
### Important Information

Provide following Information:
- mpv version: `0.35.0-173-g4bcefa5be3`
- Linux Distribution and Version: `Linux Mint 20.3 MATE`
- Source of the mpv binary: Local compile
- If known which version of mpv introduced the problem: unknown, but `0.35.0-114-g50169e05d8` was alright.
- Window Manager and version: `Compiz 0.9.14.1+20.04.20220820-0ubuntu1`
- GPU driver and version: `i965-va-driver 2.4.0-0ubuntu1`
- Possible screenshot or video of visual glitches: `N/A`

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

With my [default config](https://0x0.st/oFwQ.conf
), MPV now quits with a segmentation error and video doesn't open (link or local file)
When commenting out `hwdec=auto` video plays fine (software decoded; 1080p; h264/aac)

### Expected behavior

Video should play hardware decoded, when setting `hwdec=auto`, like it did in the past.

### Actual behavior

Video doesn't play at all.

### Log file

https://0x0.st/oFwu.txt

The issue will be closed for ignoring the issue template.

**Comment by nicolaasjan** [comment]
Strange thing is, the older working version has a much larger file size: 38.7MB vs. 31.7MB.

**Comment by nicolaasjan** [comment]
> As you already have limited it to a quite small commit range you should be able to bisect this quite fast.

Unfortunately I have no idea how to do that.
I'm not a programmer. 🙁

**Comment by t-8ch** [comment]
1) Download the mpv sources
1) `git bisect start`
1) `git checkout 4bcefa5be3`
1) Compile and test. If it works: `git bisect good`, if not: `git bisect bad`
1) `git checkout 50169e05d8`
1) Compile and test. If it works: `git bisect good`, if not: `git bisect bad`
1) git will automatically checkout a new version
1) Compile and test. If it works: `git bisect good`, if not: `git bisect bad`
1) Repeat from 7. until git tells you the first bad commit (should be after 8 repetitions)

**Comment by nicolaasjan** [comment]
This will not work, I'm afraid...
When running: `meson setup build`, this happens:

`meson.build:19:0: ERROR: Dependency lookup for libavcodec with method 'pkgconfig' failed: Invalid version, need 'libavcodec' ['>= 58.134.100'] found '58.54.100'.`  
  
I previously compiled MPV with the [mpv-build](https://github.com/mpv-player/mpv-build) scripts and that always worked.

Guess I'll have to keep using my "old" version?

**Comment by t-8ch** [comment]
You should be able to do the same with mpv-build:

Execute all the `git bisect` and `git checkout` commands in the `mpv` subdirectory of `mpv-build`.
Compile with `./build` from mpv-build

**Comment by Dudemanguy** [comment]
I can reproduce and unsurprisingly the culprit is the commit in question.

**Comment by nicolaasjan** [comment]
> I can reproduce and unsurprisingly the culprit is the commit in question.

So, can this be fixed somehow?

**Comment by Dudemanguy** [comment]
>So, can this be fixed somehow?

Of course.

**Comment by nicolaasjan** [comment]
Working now.
Many thanks @Dudemanguy. 👍️
