### ISSUE TITLE
Tearing issue with mpv

### ISSUE THREAD

**Issue by iZel345** [mpv-player/mpv#11234]
### Important Information

Provide following Information:
- The last version of MPV.
- Windows Version 21H2.
- Source of the mpv binary : Sourceforge
- If known which version of mpv introduced the problem : I don't know.
- Possible screenshot or video of visual glitches : Not possible.

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releasesd

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Actual behavior
I got some very bad tearing issue with mpv, but I don't have tearing with other media player.
I'm with AMD hardware.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by CounterPillow** [comment]
Was having the same issue but rotating my potted plant 90°, drawing a summoning circle, rubbing two sticks together and grunting animalistically totally solved the problem for me you should try it too despite you not providing any information that could lead me to believe we are experiencing any of the same issues I will just pointlessly make "same :)" posts

**Comment by oboff** [comment]
> Was having the same issue but rotating my potted plant 90°, drawing a summoning circle, rubbing two sticks together and grunting animalistically totally solved the problem for me you should try it too despite you not providing any information that could lead me to believe we are experiencing any of the same issues I will just pointlessly make "same :)" posts

same :)

**Comment by iZel345** [comment]
It's just my screen which has a issue, close the issue.
