### ISSUE TITLE
AVIF screenshot support

### ISSUE THREAD

**Issue by arm64-v9a** [mpv-player/mpv#11245]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
 screenshot-format = avif
### Alternative behavior of the wanted feature
Not applicable
### Log file
```
[   0.000][f][cplayer] Invalid value for option screenshot-format: avif
[   0.000][i][cplayer] Valid values are:
[   0.000][i][cplayer]     jpg
[   0.000][i][cplayer]     jpeg
[   0.000][i][cplayer]     png
[   0.000][i][cplayer]     webp
[   0.000][i][cplayer]     jxl
```
Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by BuyMyMojo** [comment]
With chrome regretfully removing jxl support having avif support for screenshots would be a nice to have.

Discord recently added av1 video support (For just webcams I think?) so avif support on the messaging platform could be soon-ish™️ which is another use case

**Comment by cloud11665** [comment]
I can take a look into this.
