### ISSUE TITLE
HDMI audio out of sync after unpausing

### ISSUE THREAD

**Issue by bpsib** [mpv-player/mpv#11240]
### Important Information ### 
Provide following Information:

- mpv version: 0.35.1
- Windows Version: Windows 11
- Source of the mpv binary: Sourceforge
- If known which version of mpv introduced the problem: unknown

I have found an annoying bug when using HDMI audio on Windows 11. The audio ends up 300ms ahead after unpausing mpv. Pressing left and right fixes it until it's paused again.

### Reproduction steps
Open any video when connected to an HDMI monitor with sound.
Pause the player and then unpause.

### Expected behavior
Video should not lag behind the audio

### Actual behavior
Video lags behind approx. 300ms the audio

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/10537192/output.txt)

**Comment by Doofussy2** [comment]
Try adding --audio-stream-silence=yes to your config

https://mpv.io/manual/master/#options-audio-stream-silence

**Comment by bpsib** [comment]
I have just found the sync problem occurs when playing YouTube videos in the browser and is worse as so this isn't really an issue with mpv at all. There must be some hardware/driver issue with my PC that causes a brief lag when a video plays. Using --audio-stream-silence=yes is a workaround for now and leaving a paused mpv video open with this option on also fixes the sync problem in the browser.
