### ISSUE TITLE
C header 'linux/input-event-codes.h' not usable when Wayland enabled

### ISSUE THREAD

**Issue by simonbcn** [mpv-player/mpv#11242]
### mpv version and platform versions
git version
Arch Linux

### Reproduction steps
```
  local _meson_options=(
    --auto-features auto
    --prefix /usr
    --libexecdir lib
    --sbindir bin
    --buildtype release
    --wrap-mode nodownload
    -Dstrip=true
    -Db_lto=true
    -Db_pie=true

    -Dlibmpv=true

    -Dcaca=disabled
    -Dcdda=enabled
    -Ddvbin=enabled
    -Ddvdnav=enabled
    -Dlibarchive=enabled
    -Djack=disabled
    -Dvaapi-wayland=enabled
    -Degl-wayland=enabled
    -Dwayland=enabled
  )

meson setup "${_meson_options[@]}" build mpv
```

### Actual behavior
```
Run-time dependency xkbcommon found: YES 1.5.0

mpv/meson.build:987:0: ERROR: C header 'linux/input-event-codes.h' not usable

A full log can be found at /tmp/makepkg/mpv/src/build/meson-logs/meson-log.txt
```

### Log file
[meson-log.txt](https://github.com/mpv-player/mpv/files/10539254/meson-log.txt)

**Comment by Dudemanguy** [comment]
Well yes, you need those headers on your system if you want to build with wayland. What's the bug here?

**Comment by simonbcn** [comment]
```
❯ locate linux/input-event-codes.h
/usr/include/linux/input-event-codes.h
/usr/lib/modules/6.1.8-xanmod1-1/build/include/uapi/linux/input-event-codes.h
/usr/lib/modules/6.1.8-zen1-1-zen/build/include/uapi/linux/input-event-codes.h
```

With same configuration on `waf` compiles.

**Comment by Dudemanguy** [comment]
Oh I see, the flags you are passing are being used in the header check as well and it apparently is an error to have an unused flag here which causes the check to fail.

**Comment by Dudemanguy** [comment]
The actual answer is that we're mistakenly using `cc.check_header` when we should actually just be using `cc.has_header`. As for where the flags themselves come from, I'm not sure. I assume clang just does it by default or something? At least for mpv, it doesn't have to be a problem. As for the freebsd bug, I don't *think* it's actually the same thing because the header really isn't in the available path.

**Comment by Dudemanguy** [comment]
#11243 should fix this.

**Comment by eli-schwartz** [comment]
> What is the point of treating these warnings as errors?

Well, for example, it's important to tell the compiler to:
- actually error when functions being checked for don't exist
- actually error when "has_arguments" being checked for aren't had

etc.

All these arguments should, ostensibly, be necessary to make Meson reliably detect various things in the compiler check methods. It could be there's a mistake there, I suppose.

A more interesting question might be, why:
- are you using `-mcpu=native` when every single mpv source file, compiled with this option, will emit a warning that it isn't used
- are you using -fuse-ld=lld at compile time instead of link time

**Comment by simonbcn** [comment]
> * are you using `-mcpu=native` when every single mpv source file, compiled with this option, will emit a warning that it isn't used

I use the Arch Linux build system, using `PKGBUILD` and `makepkg.conf` files. The `CFLAGS`, `CXXFLAGS`, `LDFLAGS`,... are defined generically for all packages. They do not have to give errors since they are valid flags. If later the compilation of a package uses them or not is a matter of the package in question and the compiler, but they are still valid and do not have to emit any error.

> 
> * are you using -fuse-ld=lld at compile time instead of link time

This is my mistake. I had added it in the CFLAGS as well, I have already removed it.

**Comment by simonbcn** [comment]
> #11243 should fix this.

Thanks, I'll test it when it is merged in master branch.

**Comment by eli-schwartz** [comment]
> The `CFLAGS`, `CXXFLAGS`, `LDFLAGS`,... are defined generically for all packages. They do not have to give errors since they are valid flags. If later the compilation of a package uses them or not is a matter of the package in question and the compiler, but they are still valid and do not have to emit any error.

But you are using $CFLAGS that are soft-incompatible with your $CC? And it doesn't matter whether they apply to all packages -- what matters is that you manually added this one -- it's not the default your system shipped with.

Again: for the same reason that Meson's internal checks disliked this flag, running `ninja` in that build recipe will also pass this flag for *every* C source file, and *every* C source file will noisily produce a build warning.

**Comment by eli-schwartz** [comment]
> That's right, I added those flags to get optimized binaries for my system, that's why they are available, right?

Since -mcpu is literally ignored by clang, except for generating a warning that it is being ignored... no?



> When Clang gets to the step of compiling the real `mpv` code, that will be when it will be able to tune the compiled code for my processor architecture.

No, because it emits
```
warning: argument unused during compilation: '-mcpu=native' [-Wunused-command-line-argument]
```

when building the real mpv code, too. For every single file. Which is noisy, and incidentally prevents ninja from collapsing lines that don't have any output.

**Comment by eli-schwartz** [comment]
And lest you think that this is a clang issue, GCC will also warn you:

```
gcc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
```

The difference is that GCC doesn't error out with -Wunused-command-line-argument during configure-time checks.

**Comment by simonbcn** [comment]
Ok, thanks. It is quite confusing and, IMHO, poorly documented in Clang the use of these parameters. I think they wanted to make a GCC-compatible compiler and now they have a hodgepodge of unused or misused options.
I have tuned them and now it works properly.
For Clang: `-march=znver2 -mtune=native....`
For GCC (_the same ones I already had, this compiler is very well documented_): `-march=native -mtune=native...`

**Comment by eli-schwartz** [comment]
Heh. :)

I frequently bemoan the fact that I can run `man gcc` and search for any compiler argument to see if it exists and what it ostensibly does, and yet for `man clang` I basically get nothing. :(
