### ISSUE TITLE
Make sub-text non experimental

### ISSUE THREAD

**Issue by fat-fellow** [mpv-player/mpv#11256]
Could you guys consider `sub-text` and other fields like `secondary-sub-text`, `sub-text-ass` as non experimental anymore?

https://mpv.io/manual/stable/#command-interface-sub-text

It's been 6 years since the property was introduced first time .
https://github.com/mpv-player/mpv/commit/7af6e64db748f71b472cd2b70ef7ebbe9da97859

Hope this change will unblock this issue
https://github.com/iina/iina/issues/4168

I am not sure if it should be a feature request. Thank you in advance!

**Comment by Dudemanguy** [comment]
Yeah, that is probably a lie at this point. I doubt anyone is going to remove those.

**Comment by Dudemanguy** [comment]
Closed by #11263.
