### ISSUE TITLE
How do I know if my config change has been applied?

### ISSUE THREAD

**Issue by 12932** [mpv-player/mpv#11254]
I have made changes to my input.conf file to re-bind scroll up and scroll down to audio volume change, my config file (named input.conf) looks like this:

```
WHEEL_UP add volume 5
WHEEL_DOWN add volume -5
```

But when I re-launch mpv, nothing happens when I scroll while playing a video file. This makes me wonder if my config file is even being used, there is currently no way for me to tell, as a user, if my config changes have taken effect

**Comment by CounterPillow** [comment]
It'll tell what configs it loads in the output of `mpv -v`.

e.g. you should see something like:
```
[input] Parsing input config file /home/foo/.config/mpv/input.conf
[input] Input config file /home/foo/.config/mpv/input.conf parsed: 17 binds
```

**Comment by hooke007** [comment]
BTW, stat's page4 would show the binding info.

**Comment by 12932** [comment]
> BTW, stat's page4 would show the binding info.

I'm on Windows 10

**Comment by hooke007** [comment]
So what? [stats](https://mpv.io/manual/master/#stats) is mpv internal script.

**Comment by 12932** [comment]
You said stat which I mistook for the Linux binary `stat`

**Comment by 12932** [comment]
Okay, my situation was that I had portable_config directory, and that I had mpv.conf inside it, but input.conf outside it.

mpv -v revealed that it was loading mpv.conf from inside this directory, which made me realise that it would not use input.conf (this is as documented), but I feel like the mpv -v flag should indicate this, especially for cases where nothing exists in the portable_config directory (which nothing would be reported at all)

I've made an issue for this here
https://github.com/mpv-player/mpv/issues/11254

**Comment by Hrxn** [comment]
#11255  actually
