### ISSUE TITLE
How to properly parse "mark-watched" in the config

### ISSUE THREAD

**Issue by Melechtna** [mpv-player/mpv#11251]
I'm trying to set things up so that when using MPV, YouTube keeps track of what I've watched so I can keep my recommendations up to date. Doing this manually works fine, but I can find no combination of append, add, or just options within the config, that'll let this work automatically without having to pass the flag.

As shown in the log file, it expects something on the other end of mark-watched, but adding yes or true, returns an error about this not being valid, so I don't know what it wants.

### Log file

```Expected '=' and a value.
Error parsing option ytdl-raw-options-append (option parameter could not be parsed)
/home/melechtna/.config/mpv/mpv.conf:23: setting option ytdl-raw-options-append='mark-watched' failed.```

**Comment by avih** [comment]
mpv doesn't keep track of what you've played, and it has no options related to such feature.

If youtube-dl or yt-dlp or some other utility know how to communicate this to youtube, then you should write a script which invokes this notification to youtube once the file starts/ends/whatever-you-want.

Either way, that's outside the scope of mpv, and inside the scope of you customizing it with a script of your own to do such things.

**Comment by Melechtna** [comment]
> mpv doesn't keep track of what you've played, and it has no options related to such feature.
> 
> If youtube-dl or yt-dlp or some other utility know how to communicate this to youtube, then you should write a script which invokes this notification to youtube once the file starts/ends/whatever-you-want.
> 
> Either way, that's outside the scope of mpv, and inside the scope of you customizing it with a script of your own to do such things.

This is mostly false, as I just managed to scrape up enough information to get this going. MPV uses youtube-dl and yt-dlp, though mostly yt-dlp(?) since DL is depreciated. Both of which however, can be made to report back to youtube for exactly what I'm looking for.

MPV can, in its conf, interface and pass options to either, which is what I was asking about, so thanks for closing this clearly knowing nothing about what you're responding too.

As for how to do this, for anyone that's trying to work this out themselves. You have to create a config at ~/.config/mpv/mpv.conf. From there, you want to make sure that you default it to yt-dlp, since that one seems best for interfacing with everything, like so

```
script-opts=ytdl_hook-ytdl_path=yt-dlp
ytdl-raw-options=config-location="~/.config/mpv/yt-dlp.conf"
```

Then from there, create the yt-dlp.conf in the same location as mpv.conf, though really you could put it anywhere, and add these options

```
--cookies-from-browser=brave
--mark-watched
```

Adjust which browser is being used, to whichever one is logged into your youtube account, and it'll just work, this includes with the plugin play-with-mpv.

**Comment by qmega** [comment]
The ytdl_hook script has a non-intuitive way of parsing argument-less options (though it is [documented](https://mpv.io/manual/master/#options-ytdl-raw-options)) because it uses mpv's key/value list option type. Basically, every option in `--ytdl-raw-options` requires a value, and if the value is empty, the script passes it without the `=` (which means it's impossible to actually set an option to an empty string value). This could be fixed but would probably break compatibility with existing configs.

Your original approach using mpv.conf should work like this:
```
ytdl-raw-options-append=mark-watched=
```

**Comment by Melechtna** [comment]
> The ytdl_hook script has a non-intuitive way of parsing argument-less options (though it is [documented](https://mpv.io/manual/master/#options-ytdl-raw-options)) because it uses mpv's key/value list option type. Basically, every option in `--ytdl-raw-options` requires a value, and if the value is empty, the script passes it without the `=` (which means it's impossible to actually set an option to an empty string value). This could be fixed but would probably break compatibility with existing configs.
> 
> Your original approach using mpv.conf should work like this:
> 
> ```
> ytdl-raw-options-append=mark-watched=
> ```

I'll give that a shot, I would prefer a single conf method, thank you.

**Comment by Melechtna** [comment]
Not sure when or why, but this seems to have stopped working, and I can't figure out how to correct it

**Comment by LolPopGames** [comment]
> Not sure when or why, but this seems to have stopped working, and I can't figure out how to correct it

It WORKS! As I think, when we multiple times using `ytdl-raw-options` the last overrides the first, so we need to do them in one line, separated by a comma:

```
ytdl-raw-options=cookies-from-browser=firefox,mark-watched=
```

I've tested and this line works for me.
