### ISSUE TITLE
6.1 audio FLAC issue

### ISSUE THREAD

**Issue by Idislikeusernames12** [mpv-player/mpv#11252]
### Important Information

Provide following Information:
- latest version of MPV
- Windows 11

I have no idea why I can only hear the music clearly but the voices in the movie I am listening to are muffled

**Comment by maxdunbar** [comment]
Make sure to follow the [issue template](https://github.com/mpv-player/mpv/blob/master/.github/ISSUE_TEMPLATE/2_bug_report_windows.md).

**Comment by po5** [comment]
Set `audio-channels=2` for a louder downmix.
