### ISSUE TITLE
mpv -v should indicate that it is trying to load config from the portable_config directory if it exists

### ISSUE THREAD

**Issue by 12932** [mpv-player/mpv#11255]
### Important Information

Provide following Information:
- mpv version
mpv 0.35.0
- Windows Version
Windows 10
- Source of the mpv binary
Chocolatey
- If known which version of mpv introduced the problem
Unknown
- Possible screenshot or video of visual glitches
NA

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Install mpv, and then create a directory called `portable_config` in the same directory the mpv executable is located. Do not put anything in this directory (for the sake of showing that mpv will ignore all config files in this situation, without indicating it). Run mpv with the -v flag (for verbose output)

### Expected behavior
mpv should indicate that it is attempting to load config from the portable_config directory, even if none exists

### Actual behavior
mpv prints some debug output, but doesn't indicate that it's attempting to load config from the `portable_config` directory

### Log file

```
C:\ProgramData\chocolatey\lib\mpv.install\tools>mpv -v
[cplayer] Command line options: '-v'
[cplayer] mpv 0.35.0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Mon Nov 14 04:47:57 2022
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       57.42.100
[cplayer]    libavcodec      59.52.102
[cplayer]    libavformat     59.34.101
[cplayer]    libswscale      6.8.112
[cplayer]    libavfilter     8.50.100
[cplayer]    libswresample   4.9.100
[cplayer] FFmpeg version: git-2022-11-14-3ab11dc5b
[cplayer]
[cplayer] Configuration: meson configure build -Dprefix=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build64/install/mingw -Dbuildtype=release -Doptimization=3
[cplayer] List of enabled features: av-channel-layout build-date cplayer cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel direct3d dos-paths dvdnav egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg jpegxl lcms2 libarchive libass libavdevice libbluray libm libmpv-shared libplacebo libplacebo-next luajit manpage-build noexecstack openal pdf-build plain-gl rubberband rubberband-3 sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc spirv-cross stdatomic threads uchardet vapoursynth vector vulkan wasapi win32 win32-desktop win32-executable win32-internal-pthreads zimg zlib
[cplayer] Built with NDEBUG.
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] mpv 0.35.0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Mon Nov 14 04:47:57 2022
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       57.42.100
[cplayer]    libavcodec      59.52.102
[cplayer]    libavformat     59.34.101
[cplayer]    libswscale      6.8.112
[cplayer]    libavfilter     8.50.100
[cplayer]    libswresample   4.9.100
[cplayer] FFmpeg version: git-2022-11-14-3ab11dc5b
[cplayer]
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer]
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer]
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer]
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
```

**Comment by hooke007** [comment]
```
mpv -v -v
```

**Comment by 12932** [comment]
> ```
> mpv -v -v
> ```

Is this documented anywhere?

**Comment by Dudemanguy** [comment]
`-v     Increment verbosity level, one level for each -v found on the command line.`

**Comment by 12932** [comment]
One verbosity level isn't enough to show the directory config is being loaded from? I feel like that's quite important

**Comment by thebombzen** [comment]
It does show it if there's actually a config being loaded from it.

**Comment by 12932** [comment]
> It does show it if there's actually a config being loaded from it.

Consider the case where mpv.conf is defined inside portable_config, but an input.conf is defined outside, there's no way for a user to see that their input.conf isn't being loaded

**Comment by thebombzen** [comment]
You were already told exactly how a user can see that information.

**Comment by 12932** [comment]
> You were already told exactly how a user can see that information.

So, in your opinion, you believe that two levels of verbosity is appropriate for displaying the config directory that mpv is trying to load config files from (overriding everything else)?

**Comment by Hrxn** [comment]
Considering that `portable_config` is already sufficiently "advanced" user stuff, making the leap to verbosity levels is not too far off. Not that I disagree with you, though. I believe config sources to be very important info.

**Comment by thebombzen** [comment]
> > You were already told exactly how a user can see that information.
> 
> So, in your opinion, you believe that two levels of verbosity is appropriate for displaying the config directory that mpv is trying to load config files from (overriding everything else)?

Given that it doesn't actually load anything from that directory? Yes.
