### ISSUE TITLE
AV1 Film Grain videos crash with `deband=yes` on `vo=gpu-next`

### ISSUE THREAD

**Issue by Bl4cKn1gh7** [mpv-player/mpv#11264]
### Important Information

Provide following Information:
- mpv version: 0.35.0-196-gbc7a126237
- Linux Distribution and Version: Arch Linux linux-tkg 6.1.6-273-tkg-bmq
- Source of the mpv binary: [mpv-amd-full-git](https://aur.archlinux.org/packages/mpv-amd-full-git) from AUR
- If known which version of mpv introduced the problem: 0.35.0-139-g5510d9f663
- Window Manager and version: gnome-desktop 1:43.1-1.1
- GPU driver and version mesa: 22.3.4-1.1

### Reproduction steps

Playing any AV1 video with film grain along with --deband=yes causes mpv to crash on gpu-next, on both opengl and vulkan backends.

`mpv -v --no-config --vo=gpu-next --log-file=mpv-log.txt --deband=yes /mnt/Media/Movies/Tenet.mkv`

results in:

mpv: ../src/shaders/film_grain_av1.c:312: generate_grain_y: Assertion `shift >= 0' failed.
[1]    989682 IOT instruction (core dumped)  mpv -v --no-config --vo=gpu-next --log-file=mpv-log.txt --deband=yes

### Expected behavior

Plays AV1 Film Grain videos

### Actual behavior

Crashes immediately

### Log file

[mpv-log.txt](https://github.com/mpv-player/mpv/files/10590704/mpv-log.txt)
[mpv-log-vulkan.txt](https://github.com/mpv-player/mpv/files/10590754/mpv-log-vulkan.txt)

**Comment by haasn** [comment]
Update libplacebo version to at least 5.229.2
