### ISSUE TITLE
Animated JPEG XL support

### ISSUE THREAD

**Issue by Oblomov** [mpv-player/mpv#11267]
### Expected behavior of the wanted feature

The JPEG XL format supports animation (like GIF or APNG), but “playing” such a file with mpv
```
mpv 0.35.0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.2
```
results in only the first frame being played, and the rest ignored. The expected behavior in this case would be to play the animation similarly to how it's done for GIF and APNG.

### Alternative behavior of the wanted feature

None.

### Log file

[mpv log file](http://0x0.st/oC2x.log).

**Comment by thebombzen** [comment]
This would have to be added to FFmpeg first.

**Comment by Oblomov** [comment]
Good point. I submitted the issue upstream at https://trac.ffmpeg.org/ticket/10167
