### ISSUE TITLE
vo_dmabuf-wayland: flickering with certain AOs

### ISSUE THREAD

**Issue by t-8ch** [mpv-player/mpv#11260]
### Important Information

Provide following Information:
- 0.35.1 / bc7a1262376677b8185daebf7db7c1cc5b30762f
- Linux Distribution: ArchLinux
- Source of the mpv binary: repo and self-built
- If known which version of mpv introduced the problem: N/A
- Window Manager and version: sway 1.8
- GPU driver and version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.0

### Reproduction steps

`mpv --no-config --vo=dmabuf-wayland $VIDEO --ao=null`

Reproduces with: --ao=[null,pipewire,jack,alsa]
Works with: --ao=[sndio,pulse] --no-audio

Observations:
* most of the AOs that don't work are using libpipewire, except the null AO
* The issue reproduces in around 80% of cases
* Other VOs work correctly
* Seeking (but *not* pausing) fixes the issue

### Expected behavior

Video plays back correctly

### Actual behavior

Video flickers.
It seems like the order of frames is incorrect leading to a flickering effect.
Static parts of the video look correct.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/10579475/log.txt)

### Sample files

Seems to happen with all files.

**Comment by t-8ch** [comment]
It seems to be linked to the stutter mentioned in `draw_frame()` in `vo_dmabuf_wayland.c`.
If I force a buffer reset from `resize()` then the stuttering goes away.

**Comment by philipl** [comment]
@boxerab

**Comment by boxerab** [comment]
@t-8ch can you test this on this PR branch ?

https://github.com/mpv-player/mpv/pull/11261

**Comment by t-8ch** [comment]
The PR doesn't seem to work.

This works for me:
```diff
diff --git a/video/out/vo_dmabuf_wayland.c b/video/out/vo_dmabuf_wayland.c
index 565fe50a97d9..0526fa0646ca 100644
--- a/video/out/vo_dmabuf_wayland.c
+++ b/video/out/vo_dmabuf_wayland.c
@@ -208,6 +208,8 @@ static void resize(struct vo *vo)
 
     vo->want_redraw = true;
     p->resized = true;
+    p->want_reset = true;
+    p->reset_count = 0;
 }
 
 static void draw_frame(struct vo *vo, struct vo_frame *frame)
```

**Comment by t-8ch** [comment]
New PR state works, thanks!

**Comment by t-8ch** [comment]
There are however a lot of new memory leaks that are not on `master`.

**Comment by t-8ch** [comment]
[log.txt](https://github.com/mpv-player/mpv/files/10581995/log.txt)

**Comment by boxerab** [comment]
Yes, can you try pulling the latest now from this branch ?

**Comment by t-8ch** [comment]
Works without leaks, thanks!

**Comment by Dudemanguy** [comment]
Fixed by #11261.

**Comment by t-8ch** [comment]
Works nicely, thanks @boxerab !

**Comment by t-8ch** [comment]
Thinking about this some more I am really wondering why the AO made a difference in the first place.
Especially ao=null vs no-audio.

That feels like an issue in core code.

**Comment by Dudemanguy** [comment]
Indeed, it was pretty weird but so is `dmabuf-wayland` itself anyways.
