### ISSUE TITLE
[ffmpeg] NULL: Invalid NAL unit size ?

### ISSUE THREAD

**Issue by lavara123** [mpv-player/mpv#11268]
Provide following Information:
- mpv 0.35.1
- Linux ArchLinux 6.1.9-arch1-1
- Source of the mpv binary: https://archlinux.org/packages/community/x86_64/mpv/
- Window Manager and version: XFCE 4.18
- NVIDIA Corporation TU117 [GeForce GTX 1650] (rev a1)

Some videos freeze after 3 seconds and when I close them, I see this error in the terminal
```diff
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Packet corrupt (stream = 1, dts = 114000).
- [ffmpeg] NULL: Invalid NAL unit size (9936 > 761).
- [ffmpeg] NULL: missing picture in access unit with size 765

```

### Log file

https://0x0.st/oCLJ.txt

### Sample files

http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

**[a new improvement]**
I get the same error if I use the -v trace flag using ffplay

```bash
ffplay -v trace 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
```
ffplay command output
![Ekran görüntüsü_2023-02-04_22-51-38](https://user-images.githubusercontent.com/12005386/216787064-c61cce0e-f177-4a33-8888-e934f8545888.png)

https://user-images.githubusercontent.com/12005386/216793340-c058c3ca-35ca-4dc9-ade4-e2c3af5a9605.mp4

If the video does not open, you can watch it here
https://streamable.com/22e0em

**Comment by christoph-heinrich** [comment]
[\*cough\*](https://github.com/tomasklaen/uosc/issues/446#issuecomment-1416780071) Find out which part of your config causes the problem [\*cough\*](https://github.com/tomasklaen/uosc/issues/446#issuecomment-1416782991)

**Comment by lavara123** [comment]
> [*cough*](https://github.com/tomasklaen/uosc/issues/446#issuecomment-1416780071) Find out which part of your config causes the problem [*cough*](https://github.com/tomasklaen/uosc/issues/446#issuecomment-1416782991)

my mpv.conf ??

```
# required so that the 2 UIs don't fight each other
osc=no
# uosc provides its own seeking/volume indicators, so you also don't need this
osd-bar=no
# uosc will draw its own window controls if you disable window border
border=no

script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp
```

**Comment by lavara123** [comment]
@christoph-heinrich 

i discovered something
I get the same error if I use the -v trace flag using ffplay

`ffplay -v trace 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'`

**Comment by christoph-heinrich** [comment]
> `ffplay -v trace 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'`

That's weird, I have the same ffmpeg version and yet that command works fine for me.
I also don't get an error in mpv with that video.

Nothing in that log stands out to me either besides that ffmpeg error :neutral_face:

**Comment by lavara123** [comment]
> > `ffplay -v trace 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'`
> 
> That's weird, I have the same ffmpeg version and yet that command works fine for me. I also don't get an error in mpv with that video.
> 
> Nothing in that log stands out to me either besides that ffmpeg error 😐

What operating system/distribution are you using?

**Comment by christoph-heinrich** [comment]
> What operating system/distribution are you using?

Arch

**Comment by lavara123** [comment]
> > What operating system/distribution are you using?
> 
> Arch

Are you currently using pulseaudio? I switched to pipewire because I had the following problem in pulseaudio before

https://github.com/mpv-player/mpv/issues/10731

I'm starting to suspect pipewire

**Comment by ZaquL** [comment]
You are saying as if ffmpeg did not fix 10 bugs in h264 (native decoder) in the last 1 year alone.

ffmpeg -i https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 -f null -

here produces no warnings.


>-v trace 

WHY? Those warnings in h264 are above trace level.

**Comment by christoph-heinrich** [comment]
> Are you currently using pulseaudio? I switched to pipewire because I had the following problem in pulseaudio before

pipewire

**Comment by kasper93** [comment]
Can you download the file and play locally? Something is unstable on your end, because this file is correct and doesn't have any errors. So the question is why your system produces them.

**Comment by lavara123** [comment]
> You are saying as if ffmpeg did not fix 10 bugs in h264 (native decoder) in the last 1 year alone.
> 
> ffmpeg -i https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 -f null -
> 
> here produces no warnings.
> 
> > -v trace
> 
> WHY? Those warnings in h264 are above trace level.

Why does it only break when including -v trace?

**Comment by ZaquL** [comment]
It does not break it here. It may break it for you, outputing to virtual terminal is slowest operation on Linux/Windows.

**Comment by lavara123** [comment]
> It does not break it here. It may break it for you, outputing to virtual terminal is slowest operation on Linux/Windows.

The main problem is that if it doesn't do it in mpv, why should I add -v trace and watch the video?

**Comment by ZaquL** [comment]
-v trace is not mpv's option (I suppose you can send it to ffmpeg's subcomponent...)

**Comment by lavara123** [comment]
> http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

When I download the video and run it, neither ffplay nor mpv gives a problem.

**Comment by lavara123** [comment]
I also added the video of the event above, it goes into a loop there and can't get out. this ffmpeg issue is related to "-v trace"

**Comment by thebombzen** [comment]
I cannot reproduce this.

**Comment by lavara123** [comment]
> 

I'm using the version from the Arch Linux repository

https://archlinux.org/packages/extra/x86_64/ffmpeg/

**Comment by thebombzen** [comment]
Do you get the same error if you use `https` instead of `http`? That would rule out your ISP dropping packets.

**Comment by lavara123** [comment]
> Do you get the same error if you use `https` instead of `http`? That would rule out your ISP dropping packets.

yes, that's the problem, why is it such a bullshit?

**Comment by ZaquL** [comment]
Wgy do you think everybody obsessed to migrate to https? ISPs can manipulate http, insert adds...

**Comment by thebombzen** [comment]
Do you mean that switching solved the problem or you got the same problem?

**Comment by lavara123** [comment]
> Do you mean that switching solved the problem or you got the same problem?

Solved 👍 I'm closing the issue

**Comment by Blazzycrafter** [comment]
I have a similar problem...

version windows....
mpv conf does not exist (empty(default))

for veo anime streams (.m3u8)
i do not make a new problem BECAUSE 

1. the stupid rule with the templates (i don't know in which issue i pump this....)
2. i would think it's a "general problem" *or its an network issue*....
3. did i mention that there are too much FUK templates?

Result?
i will run the streams on veo blank again and deactivate my tampermonkey sript again (to capturn the master.m3u8)

Translated with www.DeepL.com/Translator (free version)

**Comment by 111100001** [comment]
had the same problem with this url `https://www.bilibili.com/video/BV1HJ411n7QW/?p=2`  but then i found out the 1080p quality on the website was corrupted at 7:39 minute. changing to 720p quality fixed it
