### ISSUE TITLE
Using safe file-specific settings without the potentially dangerous --use-filedir-conf

### ISSUE THREAD

**Issue by aleksejrs** [mpv-player/mpv#11278]
I've been using file-specific .conf files and now I have ones with:
* `ss`, `start`, `end`, `length`, `t`
* `aid`, `sid`, `alang`, `slang`
* `volume`, `nosound`, `mute`, `an`, 
* `vf=crop`, `vf=mirror`, `fs`
* `fps`, `speed`, `no-correct-pts`
* `loop`

The files are in the same directory as the file; always per-file and never `mpv.conf`. I don't use the language-related ones much in untrusted directories, but I do use the start/end ones a lot. EDL isn't as good in playlists, because I have to move the file into a separate directory and use a symlink, which complicates backups.

The man page says `--use-filedir-conf` "May be dangerous if playing from untrusted media." Is it much more dangerous than those options? Is there a simple way to allow only those optons?

Thanks.

**Comment by thebombzen** [comment]
The issue with `--use-filedir-conf` is untrusted media might contain a random `mpv.conf` or a `video.mkv.conf` or something that lets someone set arbitrary options which could do nasty things like clobber certain files you don't want clobbered. 

Unfortunately, there's no way to restrict file-specific-configs to only permit certain options. You'll just have to be careful about playing files that have mpv specific configs in their directory that you did not write.

**Comment by thebombzen** [comment]
It can be useful if you enable it for specific use cases but as a general purpose option it should be left off, yes.

**Comment by thebombzen** [comment]
Do note that if you're on *nix there's a trick where you can create a `.m3u` playlist and put a comment at the top that has `#!/usr/bin/env -S mpv --foo=bar --baz=qux` and set the playlist to be executable. Executing the playlist as a script will run `mpv` with those options and the playlist as the first argument. Remaining lines in the `m3u` playlist can be the remaining files in the playlist, or just one file if all you need is one.
