### ISSUE TITLE
 v0.35.0 - requires FFmpeg 4.0 or newer - no libavcodec & libavutil

### ISSUE THREAD

**Issue by 0pLuS0** [mpv-player/mpv#11273]
The Changelog here on Github says for  v0.35.0 - requires FFmpeg 4.0 or newer.

I'm using ffmpeg-4.4.1 when compiling and at the terminal it says this;

no ('libavcodec >= 59.27.100' not found)
no ('libavutil >= 57.24.100' not found) 

If I compile 0.34.1 I don't get these not found, so I'm confused, if FFmpeg 4.0 or newer is the requirement, then why are these missing when using ffmpeg-4.4.1 and there's no lower compatible version?

THANKS

**Comment by Dudemanguy** [comment]
>no ('libavcodec >= 59.27.100' not found)
>no ('libavutil >= 57.24.100' not found)

Neither of these are hard requirements. They are for newer features in the build that require newer ffmpeg but you should be able to compile just fine otherwise.

**Comment by Dudemanguy** [comment]
I don't understand what you're asking. The only requirement for 0.35 is ffmpeg 4.0 and up. This corresponds to libavcodec 58.12.100 and libavutil 56.12.100. The additional messages you are seeing are merely for optional things and the only reason you are even seeing them in the first place is because the waf build is stupid and checks pkg-config again.

**Comment by thebombzen** [comment]
It sounds like what he's asking is "why is the configure script failing with these errors if supposedly only 4.0 is required"?

**Comment by Dudemanguy** [comment]
It's not failing (well he didn't post a log), but it shouldn't be. What's happening is just that jpegxl and av-channel-layout support is checked and aren't enabled since his ffmpeg isn't new enough.

**Comment by thebombzen** [comment]
In that case @0pLuS0 please attach a full build log.

**Comment by 0pLuS0** [comment]
> It sounds like what he's asking is "why is the configure script failing with these errors if supposedly only 4.0 is required"?

YES EXACTLY! LOL 👍 

Here's the Build Log.

[output.txt](https://github.com/mpv-player/mpv/files/10964021/output.txt)

**Comment by thebombzen** [comment]
That is not a build log.

**Comment by 0pLuS0** [comment]
> That is not a build log.

My bad, wasn't paying attention.

Here you go...

[configure-mpv.log](https://github.com/mpv-player/mpv/files/10974951/configure-mpv.log)

[make-mpv.log](https://github.com/mpv-player/mpv/files/10974952/make-mpv.log)

**Comment by Dudemanguy** [comment]
I already explained that a month ago. Those are checks for newer ffmpeg versions. They are not required and you built fine without them.
