### ISSUE TITLE
CPU usage at 100% when using vo=gpu and gpu-api=vulkan

### ISSUE THREAD

**Issue by Ofunniku** [mpv-player/mpv#11270]
### Important Information
- mpv version: **mpv-x86_64-v3-20230108-git-c8a9000 and mpv-x86_64-20230108-git-c8a9000**
- Windows Version: **Windows 10 Pro v22H2 (OS Build 19045.2486), latest updates**
- Source of the mpv binary: **https://sourceforge.net/projects/mpv-player-windows/files/**
- If known which version of mpv introduced the problem: **build 20230108-git-c8a9000**
- Possible screenshot or video of visual glitches: can't capture it.

### Reproduction steps
setting just vo=gpu and gpu-api=vulkan
playback of a file of any resolution with a lot of motion/panning
issue only happens with this combination of settings. switching to vo=gpu-next or gpu-api=d3d11 (or both) does not reproduce the issue

### Expected behavior
Normal video playback

### Actual behavior
CPU usage shoots up to 100%, playback stutters in any scene that isn't relatively static.

### Log file
Output of "--no-config --vo=gpu --gpu-api=vulkan --log-file=output.txt" of  **mpv-x86_64-v3-20230108-git-c8a9000** (broken)
[output.txt](https://github.com/mpv-player/mpv/files/10610777/output.txt)

### Sample files
sample 1 vp8 https://0x0.st/oCV-.webm
sample 1 vp9 https://0x0.st/oCVo.webm
sample 1 hevc https://0x0.st/oCVH.mkv
sample 2 vp8 https://0x0.st/oCVX.webm
sample 3 vp8 https://0x0.st/oCVK.webm
(third sample issue shows up 25 seconds in)

**Comment by Ofunniku** [comment]
Forgot to mention: everything works fine on 20230101-git-ad65c88 and prior on both the "v3" and non-v3 builds, and the issue is present on every version since 20230108-git-c8a9000

**Comment by haasn** [comment]
Can you also upload a log of the working version?

**Comment by Ofunniku** [comment]
@haasn The second one is the working one: https://github.com/mpv-player/mpv/files/10610872/output.txt

**Comment by haasn** [comment]
Okay, I think I know what's going on. I assume `--vd-lavc-dr=no` fixes it?

There's some sort of regression in the logic for deciding where to allocate host-mapped buffers. For some reason it decides to allocate them from VRAM instead of RAM, but only when using `vo_gpu`?

**Comment by haasn** [comment]
```
[v][vo/gpu/libplacebo] Memory heaps supported by device:
[v][vo/gpu/libplacebo]     0: flags 0x0 size 7898M
[v][vo/gpu/libplacebo]     1: flags 0x3 size 4080M
[d][vo/gpu/libplacebo] Memory types supported by device:
[d][vo/gpu/libplacebo]     0: flags 0x1 heap 1
[d][vo/gpu/libplacebo]     1: flags 0x6 heap 0
[d][vo/gpu/libplacebo]     2: flags 0x7 heap 1
[d][vo/gpu/libplacebo]     3: flags 0xe heap 0
[d][vo/gpu/libplacebo]     4: flags 0xc1 heap 1
[d][vo/gpu/libplacebo]     5: flags 0xc6 heap 0
[d][vo/gpu/libplacebo]     6: flags 0xc7 heap 1
[d][vo/gpu/libplacebo]     7: flags 0xce heap 0
```

Working:
```
[d][vo/gpu/libplacebo] Allocating 12550656 memory of type 0xe (id 3) in heap 0
[d][vo/gpu/libplacebo] Allocating 25101312 memory of type 0xe (id 3) in heap 0
[d][vo/gpu/libplacebo] Allocating 50202624 memory of type 0xe (id 3) in heap 0
```

Broken:
```
[d][vo/gpu/libplacebo] Allocating 12550656 memory of type 0x7 (id 2) in heap 1
[d][vo/gpu/libplacebo] Allocating 25101312 memory of type 0x7 (id 2) in heap 1
[d][vo/gpu/libplacebo] Allocating 50202624 memory of type 0x7 (id 2) in heap 1
```

**Comment by haasn** [comment]
So it decides to choose a "device_local | host visible | host_coherent" memory type, instead of the "host visible | host_coherent | host_cached" type, even though the `host_cached` memory property is still requested.. let me try working through the faulty logic.

**Comment by Ofunniku** [comment]
Yep, it works fine with that command.
[output vd-lavc-dr=no.txt](https://github.com/mpv-player/mpv/files/10611161/output.vd-lavc-dr.no.txt)

**Comment by haasn** [comment]
https://code.videolan.org/videolan/libplacebo/-/merge_requests/362 should fix this, do you have any way of testing?

**Comment by Ofunniku** [comment]
Not at the moment, no.

**Comment by Ofunniku** [comment]
I've just updated my player today and can confirm that it is working correctly.
