### ISSUE TITLE
Strange behavior of shader on top of video

### ISSUE THREAD

**Issue by Natural-Harmonia-Gropius** [mpv-player/mpv#11277]
### Important Information

Provide following Information:
- mpv version mpv 0.35.0-196-gbc7a1262
- Platform and Version Windows 11
- Source of the mpv binary shinchiro
- 
### Reproduction steps

Use this config, disable deband and others in following.
https://github.com/Natural-Harmonia-Gropius/mpv_config/pull/16

![image](https://user-images.githubusercontent.com/50797982/217037890-5a1ab497-5b0b-47ad-b124-d0884aafc8f7.png)

### Expected behavior

No dark block on top of video.

### Actual behavior

As the video, blocks on top can be very dark.
It only happens on top of video, any video, any frame.
OSD appear/disappear would make blocks be normal/darker with paused video.

https://user-images.githubusercontent.com/50797982/217033699-ffc544bf-8865-4d69-aedc-274726059e29.mp4

I guess shader gets some really large numbers here.

```glsl
void metering() {
    ivec2 base = ivec2(gl_WorkGroupID) * ivec2(gl_WorkGroupSize);
    for (uint y = gl_LocalInvocationID.y; y < gl_WorkGroupSize.y; y++) {
        for (uint x = gl_LocalInvocationID.x; x < gl_WorkGroupSize.x; x++) {
            vec4 texelValue = texelFetch(HOOKED_raw, base + ivec2(x,y), 0);
            float L = L_sdr * dot(texelValue.rgb, vec3(0.2627, 0.6780, 0.0593));
            atomicMax(L_max, int(L));
        }
    }
}
```

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/10665337/mpv.log)

### Sample files

Any HDR video

**Comment by haasn** [comment]
Your `dynamic1.glsl` shader is broken and has race conditions. You need to do the metering before tone mapping, as a separate pass.
