### ISSUE TITLE
How do I make OSC look like this?

### ISSUE THREAD

**Issue by da3dsoul1** [mpv-player/mpv#11279]
![image](https://user-images.githubusercontent.com/111184581/217303143-ce52f636-50f8-4339-804a-173fa2147e5a.png)
It's from a video of some youtuber, I really like how sleek and refined it looks, could anyone help pinpoint the settings should I use for it to look like that? Thank you very much!

**Comment by da3dsoul1** [comment]
So the difference from the original is that play button is in between of chapter buttons, progress bar is smaller in height, removed sound and full screen buttons and subtitle/audio tracks are on the top row, where the title is. Sadly i'm not tech savvy guy to implement it myself, hence asking for help here.

**Comment by hooke007** [comment]
You cannot did it by script opts. Obviously he directly edited the osc.lua.

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua

**Comment by da3dsoul1** [comment]
> https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua

That's the original OSC

**Comment by jimmy-1000** [comment]
> > https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua
> 
> That's the original OSC, what should I edit?

You need to be a Lua programmer for to do that or if the script exists, you need to look for it. Or wait some good guy here create the lua.

**Comment by FinnRaze** [comment]
edit` function bar_layout(direction)`in osc.lua.It seems they deleted volume&fullscreen buttons,and changed the geo of other elements.
The simplest way is to ask for a copy of modified osc.lua from them.lol

**Comment by da3dsoul1** [comment]
> edit` function bar_layout(direction)`in osc.lua.It seems they deleted volume&fullscreen buttons,and changed the geo of other elements. The simplest way is to ask for a copy of modified osc.lua from them.lol

I asked the youtube and they gave it to me! Thought I found it has an issue: the startup mpv logo looks wide
![image](https://user-images.githubusercontent.com/111184581/217894174-fbea1e25-39eb-45e0-9356-66a512ca8699.png)

I tried looking in to osc.lua, but it's a mess, can somebody help me fix it?
[osc.zip](https://github.com/mpv-player/mpv/files/10699992/osc.zip)

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/commit/cc65b3892d89ae35d31067fba285ab20716a1aee
