### ISSUE TITLE
MPV starts in kwin_wayland compositor instead of X11

### ISSUE THREAD

**Issue by ShiroYasha139** [mpv-player/mpv#11276]
### Important Information
This might be kind of weird issue.
I use Waydroid under kwin_wayland as compositor since it requires wayland, I'm on X11. When kwin_wayland is started, if I launch mpv, it starts in the compositor session instead of default (x11) 

Provide following Information:
- mpv version: mpv 0.35.0-86-g8439c084e1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
- Linux Distribution and Version: EndeavourOS 64bit
- Source of the mpv binary: mpv-git(AUR)
- If known which version of mpv introduced the problem:Don't know
- Window Manager and version:Kwin (x11)
- GPU driver and version: amdgpu(mesa)
- Possible screenshot or video of visual glitches:
![image](https://user-images.githubusercontent.com/103560009/216983443-28d420ae-d909-4306-958c-785fba68d993.png)

### Reproduction steps
Start kwin_wayland
Start mpv

I have tried with --no-config but same result.

### Expected behavior
Run mpv under x11
### Actual behavior
Mpv is started in wayland session
### Log file

https://0x0.st/oCxZ.txt

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by sfan5** [comment]
mpv tries Wayland first, then X11. This is fully intended and natural as usually when using Wayland you have X11 support emulated via Xwayland (= worse experience, features, ...).
Set `gpu-context` if you don't want this.

**Comment by ShiroYasha139** [comment]
Ah, got it. I was using `gpu-context=x11` after reading the wiki blindly, I used `gpu-context=help`, then I realized I should use `gpu-context=x11vk` 
Thanks a lot.

**Comment by sfan5** [comment]
`x11egl` for OpenGL actually, `x11` is obsolete and `x11vk` is for Vulkan
