### ISSUE TITLE
 man page instructions for screenshot template omits ""

### ISSUE THREAD

**Issue by russelld58** [mpv-player/mpv#11285]
### Important Information

Provide following Information:
- mpv version: 0.35.0-r1
- Linux Distribution and Version: Gentoo Linux x86_64 
- Source of the mpv binary: pulled from Calculate binary server http://miroir.linuxtricks.fr/calculate/grp/x86_64
- If known which version of mpv introduced the problem: ? (only found this today in 0.35.0-r1)
- Window Manager and version: not relevant
- GPU driver and version: not relevant
- Possible screenshot or video of visual glitches: not relevant

### Reproduction steps
from terminal command line:

`man mpv`

search for "screenshot-template"
instructions for naming template omit informing the user that "" is required to be around the template parameters in mpv.config in order for template to be used by mpv

eg to name screenshot with file name %f.  

Following this instruction, then mpv.config would have: screenshot-template=%f

This would not name the screenshot with the file name and screenshot file name would be to mpv default.

However, adding "" to envelop the template parameter in mpv.config enables the renaming correctly.  

As in:  screenshot-template="%f"

Please edit the man page for mpv to have this added.

Thanks for your efforts to making mpv a fantastic and useful player!

**Comment by thebombzen** [comment]
You don't need the quotes, so no.

**Comment by russelld58** [comment]
I tried without apostrophes and it didn't work.  
Searched for "mpv screenshot naming example" and found a redit post which has this solution for timestamps 
`screenshot-template="/path/to/use/%F-(%P)-%03n"`
[https://www.reddit.com/r/mpv/comments/rw2cez/take_screenshots_with_timestamp_name/](url)
I adapted this to suit and it worked in Gentoo. I haven't tried other *nix.
If this was in the man page would have saved me an ~hour of faffing about. 
YMMV

**Comment by hooke007** [comment]
> As in: screenshot-template="%f"

That's the reason.
<img width="993" src="https://user-images.githubusercontent.com/41094733/217832520-3c464671-6130-4d21-aae4-92379828e355.png">

**Comment by russelld58** [comment]
thanks for pointing this out
- cheers
