### ISSUE TITLE
mpv: symbol lookup error: mpv: undefined symbol: vkGetPhysicalDeviceDisplayPlanePropertiesKHR

### ISSUE THREAD

**Issue by ShanZeHu** [mpv-player/mpv#11290]
What is the reason for this error when I run mpv and how do I fix it? Can anyone help me?

**Comment by CounterPillow** [comment]
You or your distribution updated one of mpv's dependencies without recompiling mpv.

**Comment by thebombzen** [comment]
Khronos silently broke their ABI, unfortunately, you have to recompile mpv.
