### ISSUE TITLE
Support --input-conf from memory request

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#11298]
I intend to fix a design limitation in mpv.net. The problem is mpv.net generates a large default input.conf file containing all its bindings and also its context menu definition.

The big problem with this is, once the input.conf file is created, control is lost completely, nothing can be changed afterward.

Second problem is localization isn't supported, so I need a complete new design, I imagine something like this:

1. Write the mpv.net default bindings to a string in memory.
2. Append the user bindings defined in input.conf to the string in memory
3. Load the string with [--input-conf](https://mpv.io/manual/master/#options-input-conf)

I think it would help for my use case if --input-conf would support loading from memory via memory prefix, like it's supported in some other features, I looked at the code, and it doesn't seem to be supported.

Right now, I would need to generate a temp file, that could work fine if it doesn't have to be updated on every startup, I can try it and report back how it went.

**Comment by natural-harmonia-gropius** [comment]
Is this what you wanted?
https://github.com/natural-harmonia-gropius/input-event/pull/26

I'm not sure what intl does here, but I think it could be a pre-processing of json.

**Comment by t-8ch** [comment]
It already works for me with the prefix `memory://`.

**Comment by stax76** [comment]
I didn't understand the code then. Thanks for the help!
