### ISSUE TITLE
how can I quickly go to specific percent progress

### ISSUE THREAD

**Issue by probounce** [mpv-player/mpv#11296]
such as I type `(key-bind) 38 <enter>`, it goes to 38%

**Comment by guidocella** [comment]
`% script-message-to console type 'seek  absolute-percent; keypress esc' 6`

**Comment by thebombzen** [comment]
Does that solve your issue?

**Comment by probounce** [comment]
> `% script-message-to console type 'seek absolute-percent; keypress esc' 6`

it worked, real great solution, thanks
