### ISSUE TITLE
`--loop-file` should apply to each file individually

### ISSUE THREAD

**Issue by pedrominicz** [mpv-player/mpv#11291]
### Expected behavior of the wanted feature

The command line option `--loop-file` should apply to each file individually. For example, suppose I have two video files `a.mkv` and `b.mkv`, `mpv --loop-file=5 a.mkv b.mkv` should play `a.mkv` six times in a row then `b.mkv` six times in a row.

Furthermore, it should work with other command line options. For example, `mpv --loop-file=5 --loop-playlist=inf a.mkv b.mkv` should play  `a.mkv` six times in a row then `b.mkv` six times in a row then `a.mkv` six times in a row, etc.

Note that, unlike #7858, I am not trying to use `--loop-file` to create a slideshow. I am aware of `--image-display-duration`. I want to loop multiple video files each a few times in a row. Also, I am pretty sure I could use a Lua script to do this but I think this should not be necessary as I believe what I am proposing is a pretty natural default behavior for `--loop-file` with multiple files.

### Alternative behavior of the wanted feature

N/A

### Log file

N/A

**Comment by christoph-heinrich** [comment]
https://mpv.io/manual/master/#per-file-options

**Comment by haasn** [comment]
Huh, I thought that's how it worked currently. Sounds like a bug.

**Comment by hooke007** [comment]
Ref the previous issue, I don't think it was a bug. https://github.com/mpv-player/mpv/issues/5943#issuecomment-879560743

**Comment by pedrominicz** [comment]
@hooke007 thanks, `--reset-on-next-file` is exactly what I was looking for.

I like the consistency of `--reset-on-next-file=loop-file` with other settings. Instead of making `--loop-file` special as I originally suggested, I think it is better to mention `--reset-on-next-file` on `--loop-file`'s man page section as I believe there are more people who would like the behavior I was looking for.

Just to have it documented in this issue, the behavior I was looking for can be achieved with `mpv --loop-file=5 --reset-on-next-file=loop-file a.mkv b.mkv`.
