### ISSUE TITLE
Use vo=gpu-next for Dolby Vision P5 video in my own macOS App

### ISSUE THREAD

**Issue by shishaozheng** [mpv-player/mpv#11308]
### Important Information

- mpv version:  0.35.1
- macOS Version: Ventura 13.2
- Source of the mpv binary or bundle: https://github.com/mpv-player/mpv/archive/v0.35.1.tar.gz

### Reproduction steps
1. Build the mpv library with the --enable-libplacebo flag to enable playback of Dolby Vision P5 video.
2. Add the mpv library to the Xcode project and create a new NSWindow with a CAOpenGLLayer for rendering.
3. When using vo=libmpv to play normal video, the video image is rendered on the NSWindow with the CAOpenGLLayer correctly. However, when playing Dolby Vision P5 video, the video color is incorrect.
4. When trying vo=gpu-next for Dolby Vision P5 video, the video color is correct but the video image is not rendered on the NSWindow with the CAOpenGLLayer. Instead, a new window of mpv itself pops up and starts playing.

### Expected behavior
When using vo=gpu-next for Dolby Vision P5 video, the video image should be rendered on my own NSWindow with the CAOpenGLLayer with the correct color. This is because vo=gpu-next is based on libplacebo, which supports OpenGL.

### Actual behavior
When using vo=gpu-next for Dolby Vision P5 video, a new window of mpv itself pops up and starts playing.

For vo=gpu-next, should I use MoltenVK for rendering? Is it supports OpenGL? How to prevent the window of mpv itself from popping up and use my own window?

**Comment by Akemi** [comment]
gpu-next uses the old deprecated cocoa backend und is noch supported atm.

**Comment by george-emerald** [comment]
Does this mean it's not supported for newer Mac OS version? Cause I've tried the builds in mpv.io and homebrew ARM and AMD builds and none of them have gpu-next at all. I don't use mpv for Dolby Vision as it tonemaps it and my TV supports it, but I'd like to try it for the faster performance. Is it impossible?
