### ISSUE TITLE
Not able to cycle fullscreen when using `vo=gpu-next`

### ISSUE THREAD

**Issue by nanowavve** [mpv-player/mpv#11301]
### Important Information

Provide following Information:
- mpv version = 0.35.1
- macOS Version = 12.5.1
- Source of the mpv binary or bundle = compiled from `mpv-0.35.1.zip`

### Reproduction steps

1. `mpv --no-config --hwdec=yes --fs=yes --log-file=tlou-no-config.txt video-files/the.last.of.us.2160p.mkv`
2. `mpv --no-config --hwdec=yes --fs=yes --vo=libmpv --log-file=tlou-libmpv.txt video-files/the.last.of.us.2160p.mkv`
3. `mpv --no-config --hwdec=yes --fs=yes --vo=gpu-next --log-file=tlou-gpu-next.txt video-files/the.last.of.us.2160p.mkv`
4. `mpv --no-config --hwdec=yes --fs=yes --vo=gpu-next --tone-mapping=bt.2446a --log-file=tlou-gpu-next-bt2446a.txt video-files/the.last.of.us.2160p.mkv`

### Expected behavior

To be able to full-screen in an out of the currently playing video while using `vo=gpu-next`.

### Actual behavior

For the first two commands there's no issues, but from the third command and onwards I'm stuck in fullscreen and can't exit out by doing a double right-click or by pressing `f` on my keyboard.

### Log file

Installation:
1. `build.txt` = https://0x0.st/s/PpRhftIywGi32WAFbZeQqg/Hrax.txt
2. `compile.txt` = https://0x0.st/s/Wzmd_jKwbRXykGU8yzkzBA/Hra3.txt
3. `install.txt` = https://0x0.st/s/0CLAOD6z24OB8cutzz_Gug/HraY.txt

Playback:

1. `tlou-no-config.txt` = https://0x0.st/s/I_tThbE0C7hGKSNJE-TFNA/Hray.txt
2. `tlou-libmpv.txt` = https://0x0.st/s/A6znIZENn2IT6QEr3LWepg/Hrat.txt
3. `tlou-gpu-next.txt` = https://0x0.st/s/0Y5Xgu_YvScluJX2StWuuQ/Hrav.txt
4. `tlou-gpu-next-bt2446a.txt` = https://0x0.st/s/f7fa_ofzZG9_4aDbrPpXUw/Hraw.txt

**Comment by hooke007** [comment]
I haven’t heard about that gpu-next is really supported for Mac.

**Comment by nanowavve** [comment]
@hooke007 You're right, I don't know how I missed it since I did make sure to do a search, but I just found out this same problem from before: https://github.com/mpv-player/mpv/issues/10978. Thank you regardless.
