### ISSUE TITLE
Segmentation fault when using --audio-device=help

### ISSUE THREAD

**Issue by acedogblast** [mpv-player/mpv#11309]
### Important Information

Provide following Information:
- mpv version 0.35.1
- KDE Neon 22.04
- Last known working version 0.35.0
- Window Manager and version: Wayland

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
mpv -v --audio-device=help --no-config

### Expected behavior
list all available audio devices as specified in https://mpv.io/manual/stable/#audio

### Actual behavior
Segmentation Fault occurs.

### Log file
https://pastebin.com/4CuNStjh

### Sample files

None needed.

**Comment by acedogblast** [comment]
Also to note, --ao=help does work without any issues.

**Comment by t-8ch** [comment]
Can you try get a backtrace to see where exactly it fails?

**Comment by acedogblast** [comment]
I used gdb to get this: https://pastebin.com/tydmRy7G

**Comment by acedogblast** [comment]
Seems to be something going wrong at ao_pipewire.c line 290 on function spa_hook_remove.

**Comment by t-8ch** [comment]
This should not happen with newer versions of pipewire:
https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/1362

It is weird that KDE Neon has a very new version of mpv but an older version of pipewire.

**Comment by acedogblast** [comment]
Well I just built mpv from source and not using pipewire just normal pulseaudio. Is there a way to build mpv without pipewire?

**Comment by t-8ch** [comment]
You can pass `--disable-pipewire` to waf or add `ao=pulse` into your config.
Alternatively try this patch: 
```diff
diff --git a/audio/out/ao_pipewire.c b/audio/out/ao_pipewire.c
index 4880e776f001..9967d7100bbd 100644
--- a/audio/out/ao_pipewire.c
+++ b/audio/out/ao_pipewire.c
@@ -287,7 +287,8 @@ static void uninit(struct ao *ao)
     struct priv *p = ao->priv;
     if (p->loop)
         pw_thread_loop_stop(p->loop);
-    spa_hook_remove(&p->stream_listener);
+    if (p->stream_listener.link.prev)
+        spa_hook_remove(&p->stream_listener);
     spa_zero(p->stream_listener);
     if (p->stream)
         pw_stream_destroy(p->stream);
```

**Comment by acedogblast** [comment]
--disable-pipewire works. Closing.

**Comment by t-8ch** [comment]
Could you also try the patch? Maybe we have to add it as a workaround for old versions of pipewire.

**Comment by acedogblast** [comment]
@t-8ch Just the changes in the merge request does not fix the seg fault.
The diff patch you posted earlier with the merge request does work. Will try with just the diff patch.

**Comment by t-8ch** [comment]
Care to test the new version of the PR?

**Comment by acedogblast** [comment]
The new version of the PR does work.

**Comment by t-8ch** [comment]
Thanks for validating
