### ISSUE TITLE
Resize window if cover image is too small

### ISSUE THREAD

**Issue by maksomp3** [mpv-player/mpv#11311]
Everything works fine, but window is too small

![Screenshot2023-02-14 14-56-27](https://user-images.githubusercontent.com/9934489/218677795-df1d1712-c7ad-4301-8284-5839d1ccedc1.png)

### Expected behavior of the wanted feature
Would be nice to stay to control the program while it playing music from the folder with small-sized image cover.jpeg in it.

### Log file
cover.jeg is size 130*127px

**Comment by thebombzen** [comment]
add `--autofit-smaller=480x480` or something to your mpv.conf.
