### ISSUE TITLE
Add support for multiple image formats

### ISSUE THREAD

**Issue by mayconhvab** [mpv-player/mpv#11315]
I would like the mpv player to have a great ability to obtain support for different image formats, and that it can support going left or right when viewing not only an image (photo) but seeing several photos one after the other, such as if it was a slideshow.
The images that can be added are also like a simple jpg or even an svg, having support for different qualities, thus accepting only the format, and not changing its composition, being that it is HDR 8, HDR 10 or HDR 12, (even being HDR Plus or not).
Keep the original photo or image of yourself, and minimize the use of CPU, GPU or RAM, for and in several factors.
I realized that currently in the latest beta version that I use the mpv player, whenever I see an image, such as from my smartphone camera, the photo or image lasts only a few seconds and then disappears.
I would like to be able to pause the photo and not close the mpv User Interface when displaying this photo or image, add different formats to every platform mpv player, from Windows, to Linux, Android and other platforms that the wonderful software supports .
An example I can give you when having multiple formats, is searching on sites that talk about image formats and Wikipedia, similar to this: image formats
Or: raster image formats
Various information can be added to image formats. As media information and support in rotating the photo left or right, flipping it or even rotating it by degrees.
It can also be added full support for information according to IrfanView and some XnView products. (Not for conversion or editing, but to display photos, actually a photo and image viewer, in the most diverse, advanced and varied images and photos, in their various qualities).
Thank you very much and that's it.

**Comment by garoto** [comment]
Agree, all of this must happen ASAP or else I'm switching to VLC (yet again... *sigh*) or worse, Po..., Pol Pot..., PotPlayer! yeah, that's right! You all have been warned.

**Comment by Dudemanguy** [comment]
mpv supports images.

>I would like to be able to pause the photo

You can already do this. Alternatively, just use `--image-display-duration=inf`.
