### ISSUE TITLE
Add full FFmpeg support

### ISSUE THREAD

**Issue by mayconhvab** [mpv-player/mpv#11314]
First of all I would like to thank you very much for this wonderful audio, video, photos and streaming player.
I would like to see full support added to all formats, codecs, decoders, encoders, mux and demuxers present in FFmpeg, since version 5.1 or even in the most present beta.
I recently got news that FFmpeg version 6.0 will be released by April of this year (year 2023), and I would really like the software to have full compatibility with FFmpeg, so we will have a wonderful player that supports different formats in their highest resolutions, from a simple 144p to an 8K HDR 60 fps.
Many thanks to the whole team!

**Comment by CounterPillow** [comment]
I'm not exactly sure what this is asking? You can build mpv with a git version of FFmpeg right now, which is what will become FFmpeg 6.0.

**Comment by Jules-A** [comment]
Isn't Shinchiro's builds already using FFMPEG master?

**Comment by garoto** [comment]
> Isn't Shinchiro's builds already using FFMPEG master?

No, the real, up-to-date version of ffmpeg is hidden behind a l33t website, where only the illuminati, selected WEF members and Lady Gaga have access to. See how @richardpl, the infamous leader of the croatian branch of the 'Ndrangheta-ffmpeg-git disliked the OPs post? Yeah, mayconhvab is up to something.
