### ISSUE TITLE
Is it possible to use `visual studio 2022`'s `llvm toolchain` to compile mpv ?

### ISSUE THREAD

**Issue by shithappens2016** [mpv-player/mpv#11321]
As the document mentions that msvc cannot compile mpv because it lacks full support for c99/c11.
https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md?plain=1#L176-L178

But the `llvm toolchain` of `visual studio 2022` should support c99 and c11（not `clang-cl` but `clang`).

Is it possible to use `visual studio 2022`'s `llvm toolchain` to compile mpv ?

**Comment by jeeb** [comment]
I would say that theoretically, yes.

I would expect that some inconsistencies between mingw-w64 and MS SDK headers would cause some issues, the clearest example of which I know is the difference between WASAPI headers (mingw-w64 auto-includes and allows different header inclusion order than MS, MS fails with what mingw-w64 succeeds with).

**Comment by kasper93** [comment]
It is good exercise if someone wants to play around. First `clang` build, then `clang-cl` and then `MSVC` which should be transparent to `clang-cl`, if possible due to C support in `MSVC` or lack thereof.

**Comment by minnyres** [comment]
Is there anyone tried to build mpv with MSVC? MSVC team has announced C11 and C17 standard support in MSVC:
https://devblogs.microsoft.com/cppblog/c11-and-c17-standard-support-arriving-in-msvc/
