### ISSUE TITLE
mpv: error while loading shared libraries: libglslang.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by amayra** [mpv-player/mpv#11320]
### Important Information

Provide following Information:
- mpv version : git build
- Linux Distribution and Version : manjaro unstable
- Source of the mpv binary : AUR
- If known which version of mpv introduced the problem : git one
- Window Manager and version : KDE I don't think this is problem here
- GPU driver and version : mesa 22.3.5

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

the problem is mpv don't use "libglslang.so.12" and after building glslang from the GIT doesn't provide " libglslang.so.11" shared libraries even after building again 

### Expected behavior

everything works fine after building glslang before building mpv

### Actual behavior

"mpv: error while loading shared libraries: libglslang.so.11: cannot open shared object file: No such file or directory"

### Log file

there no log file

**Comment by thebombzen** [comment]
Do a clean rebuild and post a build log.

**Comment by amayra** [comment]
> 

[glslang than mpv build.txt](https://github.com/mpv-player/mpv/files/10766739/glslang.than.mpv.build.txt)

**Comment by monarc99** [comment]
try to build mpv-build-git ... libplacebo and maybe ffmpeg have a dependency to glslang

**Comment by thebombzen** [comment]
It's most likely that one of mpv's dependencies requires libglslang.so.11. Check with ldd

**Comment by amayra** [comment]
> Check with ldd

I couldn't find this file

 can you help where I should report this issue look like there only " libglslang.so.12" when you build glslang from git 
 
 i think this something should fix on mpv side to keep working with the last version of glslang in the future

**Comment by arcady-lunarg** [comment]
The major version of glslang was bumped from 11 to 12 after an inadvertent ABI break. Building glslang version 12.x produces libglslang.so.12, while libglslang.so.11 would only be present if building earlier versions. I don't think this is a glslang problem.

**Comment by Dudemanguy** [comment]
It's also not an mpv issue. Complain to your distro if libraries aren't linked properly.
