### ISSUE TITLE
Does MPV begin to show the UI only when the video is ready?

### ISSUE THREAD

**Issue by HubKing** [mpv-player/mpv#11327]
Suppose that there is a video file on a hard disk, and that it takes about 5 seconds for the HDD to spin up. You had opened the directory where the video file is and left it alone for a long time so that the HDD was spun down.

In this case, if you double click the video file to open it with MPV, does the MPV UI first show up and show some sort of loading indicator until the file becomes available, or does the MPV UI not show up at least for 5 seconds until it can start reading the video file?

**Comment by avih** [comment]
mpv does not show the UI (play/pause/seek/etc buttons, i.e. OSC) before playback starts.

Playback starts after enough of the file was read to determine what kind of file it is, and whether mpv can play it.

Whether or not the _windows_ shows up before playback starts depends other things:
- If mpv is launched in pseudo-gui mode or if the option `--show-window=immediate` is set, then the window shows before playback starts. There's no UI inside the window, and there's no any kind of loading message or indication or animation etc. The UI (OSC) becomes available once playback starts - when moving the mouse over it (bottom by default).
- Else, the window shows only when the playback starts, and only if the file is a video or an image or an audio with cover-art image. Specifically, audio without cover-art image plays without a window by default.

**Comment by HubKing** [comment]
> --show-window=immediate

Thanks. I suspected that it was the latter, but I was not sure if it depends on the circumstances (e.g., video output mode, Wayland, GPU, etc), so I asked this question. Ultimately, I was going to ask if there is a way to make the UI show immediately, if that is the case, because I often open the same file 2 or 3 times because the window did not show up immediately and I thought I mis-double-clicked.

**Comment by avih** [comment]
> if there is a way to make the UI show immediately, if that is the case, because I often open the same file 2 or 3 times because the window did not show up immediately and I thought I mis-double-clicked.

add to your `mpv.conf`:
```
force-window=immediate
```
