### ISSUE TITLE
Device does not support timeline semaphores

### ISSUE THREAD

**Issue by xiatutu** [mpv-player/mpv#11334]
1. I installed ffmpeg from :
https://github.com/BtbN/FFmpeg-Builds/releases/ffmpeg-master-latest-win64-gpl.zip
in windows10
I run **"ffmpeg -version"**,  make sure that the version supports vulkan and libplacebo:
"configuration:--enable-vulkan --enable-libplacebo --extra-version=20230219".
And, I run **"ffmpeg -init_hw_device list"**, shows:
Supported hardware device types:
cuda
dxva2
qsv
d3d11va
opencl
**vulkan**
But I run the example: ffmpeg -i $INPUT -init_hw_device vulkan -vf hwupload,libplacebo=format=yuv420p,hwdownload,format=yuv420p $OUTPUT, I get the error:
[AVHWDeviceContext @ 0000020d5fc498c0] **Device does not support timeline semaphores!**
Device creation failed: -40.
Failed to set value 'vulkan' for option 'init_hw_device': Function not implemented
Error parsing global options: Function not implemented.

**Comment by CounterPillow** [comment]
this is the mpv issue tracker, there is no support for standalone ffmpeg usage here.

**Comment by xiatutu** [comment]
> this is the mpv issue tracker, there is no support for standalone ffmpeg usage here.

I see the similar issue in https://github.com/mpv-player/mpv/issues/9589, but there is no solution。
![image](https://user-images.githubusercontent.com/33248045/220057650-68d9d81b-77b7-4fa1-ad34-a91ffedf02e8.png)

I think it's a vf_libplacebo error.

**Comment by hooke007** [comment]
That's off topic.

**Comment by xiatutu** [comment]
> Your vulkan driver does not implement `VK_KHR_timeline_semaphore`, try to update the driver
I have found the error, thanks anyway~
