### ISSUE TITLE
[Lua script] When EOF reached (only on youtube links) - do X

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#11331]
I'm trying to create a lua script that when I open YouTube links (this is the condition, it must only activate when using YouTube) using mpv and it reaches EOF and the state is paused/stopped (meaning that I've finished watching the video, this is another condition) - it will switch window to "Chrome", (this is the action), if that can't be done then I want it to open "C:/Test/Test.exe" (the exe file will do what the script can't)

I can't quite figure out how it can be done, this is why I'm asking for help here.

**Comment by Dudemanguy** [comment]
When you say "reaches EOF and the state is paused/stopped", I assume you mean with like with the `--keep-open` option. In that case, you could just observer the `eof-reached` property. Something like this would work.
```
function do_stuff(name, value)
    if value == true then
		local url = mp.get_property("path")
		if string.match(url, "youtube.com") then
			mp.command_native({
				name = 'subprocess',
				args = {'some', 'args', 'here'},
			})
		end
	end
end

mp.observe_property("eof-reached", "bool", do_stuff)
```
Of course, there are some different formats for youtube links, so you could add more matches in there in a more elegant way. And I presume you have some exe file that does what you need to do so just execute it in a subprocess.

**Comment by guidocella** [comment]
Try disabling Microsoft Defender.

**Comment by Dudemanguy** [comment]
Yeah. Definitely not mpv doing that. Probably an antivirus or whatever delaying execution.
