### ISSUE TITLE
vo_gpu-next: lrc's rendering freeze when playing audio files

### ISSUE THREAD

**Issue by NaiveInvestigator** [mpv-player/mpv#11335]
### Important Information

Provide following Information:
- mpv version
https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-02-19
- Windows Version
Windows 11 Pro
Version:	22H2
OS build:	22623.1325
Experience:	Windows Feature Experience Pack 1000.22639.1000.0

- Source of the mpv binary
https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-02-19
- If known which version of mpv introduced the problem
N/A
- Possible screenshot or video of visual glitches
N/A

### Reproduction steps

   1. run mpv.exe (only vo=gpu-next in mpv.conf)
   2.  play a audio file (mp3 or ogg) with LRC
### Expected behavior
All lyrics would be rendered.
### Actual behavior
Lyrics are not rendered at all unless, sub visibility is changed repeatedly or if I kept resizing the window repeatedly

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/10780502/output.txt)

### Sample files
This occurs in all lrc files for me, so any lrc will work.
the file that is mentioned in log is given below
[1. Number One - Bankai.txt](https://github.com/mpv-player/mpv/files/10780542/1.Number.One.-.Bankai.txt) change extension back to lrc

**Comment by Dudemanguy** [comment]
Can't reproduce is this still a problem?

**Comment by NaiveInvestigator** [comment]
since then i have switched to linux now, so i can't say.

Will close this issue since nobody else seems have this issue.

**Comment by hooke007** [comment]
@Dudemanguy Could you reopen it? I know how to reproduce it now.
[test.log](https://github.com/mpv-player/mpv/files/12164858/test.log)
`mpv --vo=gpu-next --blend-subtitles=video`

**Comment by Dudemanguy** [comment]
Interesting, it doesn't for me so is this d3d11 possibly?

Sidenote: I had to use `--subs-fallback=yes`, wonderful.

**Comment by hooke007** [comment]
> is this d3d11-only possibly

Nope, `gpu-context = win/winvk` also make it freezing.

**Comment by Dudemanguy** [comment]
Not sure why or how I couldn't reproduce it then, but I can now and I see the problem.
