### ISSUE TITLE
4k@60 video drops frames, but works fine when played in browser

### ISSUE THREAD

**Issue by soredake** [mpv-player/mpv#11349]
### Important Information

Provide following Information:
- mpv-x86_64-v3-20230212-git-a40958c
- Windows 11 Pro
- AMD RX 560 gpu
- Browser is firefox
- [Source of the mpv binary](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/)
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

Options that i tried with no luck:
```
vo=gpu-next
vd-lavc-dr=yes
hdr-compute-peak=no
d3d11va-zero-copy=yes
hwdec=auto
gpu-api=opengl
gpu-api=vulkan
vulkan-swap-mode=fifo
vulkan-queue-count=8
```

### Reproduction steps

1) Have amd card like RX 560 and windows 11 installed.
2) Do `.\mpv.com https://www.youtube.com/watch?v=62gncf4HYp0 --start=1:59:45 --fullscreen --pause  --no-config` and watch video for a ~30 seconds
3) Frame will drop at certain moments.

### Expected behavior
No framedrop.

### Actual behavior
Frames are dropped in certain moments.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/10803306/output.txt)

### Sample files
https://www.youtube.com/watch?v=62gncf4HYp0 starting at 1:59:45

**Comment by thebombzen** [comment]
Most browsers use hardware-accelerated video decoding to playback vp9 from youtube. Did you try using `--hwdec=d3d11va --hwdec-codecs=all`?

**Comment by soredake** [comment]
> Most browsers use hardware-accelerated video decoding to playback vp9 from youtube. Did you try using `--hwdec=d3d11va --hwdec-codecs=all`? 

My gpu does not support vp9 decoding.

**Comment by thebombzen** [comment]
Then it is most likely that YouTube is serving you H.264. Try modifying `--ytdl-format`

**Comment by soredake** [comment]
Unfortunately, youtube is serving vp9.

![изображение](https://user-images.githubusercontent.com/5204968/220709710-319222a4-0903-47bf-ab75-14d13996cfcc.png)

**Comment by thebombzen** [comment]
Do you drop frames when you run `mpv --no-config --vo=null --mute "https://www.youtube.com/watch?v=62gncf4HYp0"`

**Comment by soredake** [comment]
@thebombzen yes.

**Comment by Traneptora** [comment]
Then your CPU probably can't decode vp9 fast enough

**Comment by soredake** [comment]
@Traneptora no, i have ryzen 7 1800x, which definitely can decode 4k v9 fast enough, i've played this video in browser, no frame drops, i've played the same video downloaded to disk in vlc, no frame drops either.

**Comment by Traneptora** [comment]
You're dropping frames with the `null` video output which doesn't render any frames, not sure what else there is to check, since you're just decoding and discarding them.

**Comment by mlindner** [comment]
Also experiencing the same problem here. I register over 200% cpu playing a vp9 4k 60fps video from youtube in mpv but only around 150% cpu in firefox.

**Comment by soredake** [comment]
Good news, something changed in mpv or ffmpeg and mpv no longer drops frame with this video and 4k@60 vp9 on my machine.
