### ISSUE TITLE
Auto play at startup

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#11348]
I was using this script https://github.com/AN3223/dotfiles/blob/master/.config/mpv/scripts/always-play-on-startup.lua
```
mp.register_event(
    "file-loaded", function() mp.set_property_bool("pause", false) end
    (
```

And I noticed it no longer works, is there any setting to mpv to make it resume the video playback when I open mpv at startup?
I think it's annoying that I need to open the video file and then resume it (two clicks instead of one)

**Comment by qmega** [comment]
You might just want to set watch-later-options-remove=pause in your config file and get rid of the script, if I understand correctly what you want. (Would not apply to already-saved state, but anything newly saved.)

**Comment by Obegg** [comment]
Yes, Thank you!

**Comment by Obegg** [comment]
So this doesn't fully solve my issue.

When I finish watching a youtube video mpv reach EOF so playback is paused,
and when I drag-drop another youtube link mpv stays at paused state,
so I have to resume it again, which is annoying.

Any workaround for this kind of issue?

**Comment by Haruki021** [comment]
Maybe you can try set keep-open-pause=no

**Comment by Obegg** [comment]
Perfect! Thank you!
