### ISSUE TITLE
vo_gpu-next: `--tone-mapping-visualize` may break the rendering of OSD

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#11345]
### Important Information

Provide following Information:
- mpv version
 https://github.com/mpv-player/mpv/commit/9efce6d4ae26114a23f41f0b3b2d0d9f0281547b
- Platform and Version
 win10 pro 22h2
- Source of the mpv binary
 https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230221

### Reproduction steps

Load the [dovi video](https://github.com/mpv-player/mpv/issues/11344) (metadate's peak is lower than 203) and then set target-peak=100, toggle `tone-mapping-visualize`. After that action, any OSD message would not output any more.

### Expected behavior

OSD's rendering would not be affected.

### Actual behavior

No osc, no console, no osd msg...

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/10795004/mpv.log)

### Sample files

[test2-00.00.04.707-00.00.11.580.zip](https://github.com/mpv-player/mpv/files/10795039/test2-00.00.04.707-00.00.11.580.zip)

**Comment by thebombzen** [comment]
Also tested: `--gpu-api=vulkan` and `--gpu-api=opengl` both break in the same way.

**Comment by haasn** [comment]
Good catch. We probably want to fix it with *this* patch, although it will also disable e.g. inverse tone mapping for overlays. (Maybe that's intended?)

```diff
diff --git a/src/renderer.c b/src/renderer.c
index 6e4976a1..1c4e1272 100644
--- a/src/renderer.c
+++ b/src/renderer.c
@@ -925,8 +925,7 @@ static void draw_overlays(struct pass_state *pass, pl_tex fbo,
 
         sh->res.output = PL_SHADER_SIG_COLOR;
         pl_shader_decode_color(sh, &ol.repr, NULL);
-        pl_shader_color_map(sh, params->color_map_params, ol.color, color,
-                            NULL, false);
+        pl_shader_color_map(sh, NULL, ol.color, color, NULL, false);
 
         bool premul = repr.alpha == PL_ALPHA_PREMULTIPLIED;
         pl_shader_encode_color(sh, &repr);
```
