### ISSUE TITLE
MPV will crash and not responding if a URL is too long

### ISSUE THREAD

**Issue by BoscoFZ** [mpv-player/mpv#11343]
### Important Information

Provide following Information:
- mpv version
https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-02-20

### Reproduction steps

My mpv will crash when a URL is too long like the code bellow

`mpv --no-ytdl "https://scontent-sin6-2.xx.fbcdn.net/v/t39.25447-2/10000000_150747141158559_2304511369673619337_n.mp4?_nc_cat=108&vs=b4d50b4455f0e7b7&_nc_vs=HBksFQAYJEdJQ1dtQUNmdHN5Tkdva0FBSW0zUG9MaFJQc2ZibWRqQUFBRhUAAsgBABUAGCRHSUNXbUFBYTloV1h5UmtEQU1xcWNIU01FdDhhYnJGcUFBQUYVAgLIAQBLB4gScHJvZ3Jlc3NpdmVfcmVjaXBlATENc3Vic2FtcGxlX2ZwcwAQdm1hZl9lbmFibGVfbnN1YgAgbWVhc3VyZV9vcmlnaW5hbF9yZXNvbHV0aW9uX3NzaW0AKGNvbXB1dGVfc3NpbV9vbmx5X2F0X29yaWdpbmFsX3Jlc29sdXRpb24AHXVzZV9sYW5jem9zX2Zvcl92cW1fdXBzY2FsaW5nABFkaXNhYmxlX3Bvc3RfcHZxcwAVACUAHAAAJsjdreOe84MUFZBOKAJDMxgLdnRzX3ByZXZpZXccF0CWL6wIMSbpGDRkYXNoX2k0bGl0ZWJhc2ljX3Bhc3N0aHJvdWdoYWxpZ25lZF9ocTJfZnJhZ18yX3ZpZGVvEgAYGHZpZGVvcy52dHMuY2FsbGJhY2sucHJvZDgSVklERU9fVklFV19SRVFVRVNUGw6IFW9lbV90YXJnZXRfZW5jb2RlX3RhZwZvZXBfaGQTb2VtX3JlcXVlc3RfdGltZV9tcwEwDG9lbV9jZmdfcnVsZQd1bm11dGVkE29lbV9yb2lfcmVhY2hfY291bnQBMBFvZW1faXNfZXhwZXJpbWVudAARb2VtX3JvaV91c2VyX3RpZXIDdWdjHm9lbV9yb2lfcHJlZGljdGVkX3dhdGNoX3RpbWVfcwEwFm9lbV9yb2lfcmVjaXBlX2JlbmVmaXQFMC4wMDAlb2VtX3JvaV9zdGF0aWNfYmVuZWZpdF9jb3N0X2V2YWx1YXRvcgtwcm9ncmVzc2l2ZQxvZW1fdmlkZW9faWQQMTgyNDc5NzA4MTIzOTMzOBJvZW1fdmlkZW9fYXNzZXRfaWQQNTQxNzg0MTQwODMyMDM3MhVvZW1fdmlkZW9fcmVzb3VyY2VfaWQQNTYzODA3NjQxOTY1MTQyOBxvZW1fc291cmNlX3ZpZGVvX2VuY29kaW5nX2lkDzkxODUxMzQ4OTMyOTI2MA52dHNfcmVxdWVzdF9pZA8yZWU5N2Q0ZTBlYjU0MmUlAhwcHBXw5hcbAVUAAhsBVQACHBUCAAAAFoC6twMAJY4CGwiIAXMENTE4OAJjZAoyMDIzLTAyLTAyA3JjYgEwA2FwcAZ1cGxvYWQCY3QZQ09OVEFJTkVEX1BPU1RfQVRUQUNITUVOVBNvcmlnaW5hbF9kdXJhdGlvbl9zCDE0MjAuMDc1AWYCYWQCdHMVcHJvZ3Jlc3NpdmVfZW5jb2RpbmdzAA%3D%3D&ccb=1-7&_nc_sid=41a7d5&_nc_ohc=L_dzb8dbQwcAX8wwXSo&_nc_ht=scontent-sin6-2.xx&edm=APRAPSkEAAAA&oh=00_AfCY25yJxLCTq0lZ1bttybDBFV_-7qbGg7ZZoE3s_1nEig&oe=63F82C10&_nc_rid=897881643295126" -v`

The issue will be ok when i work around by set no title

`mpv --title=NoTitle --no-ytdl "https://scontent-sin6-2.xx.fbcdn.net/v/t39.25447-2/10000000_150747141158559_2304511369673619337_n.mp4?_nc_cat=108&vs=b4d50b4455f0e7b7&_nc_vs=HBksFQAYJEdJQ1dtQUNmdHN5Tkdva0FBSW0zUG9MaFJQc2ZibWRqQUFBRhUAAsgBABUAGCRHSUNXbUFBYTloV1h5UmtEQU1xcWNIU01FdDhhYnJGcUFBQUYVAgLIAQBLB4gScHJvZ3Jlc3NpdmVfcmVjaXBlATENc3Vic2FtcGxlX2ZwcwAQdm1hZl9lbmFibGVfbnN1YgAgbWVhc3VyZV9vcmlnaW5hbF9yZXNvbHV0aW9uX3NzaW0AKGNvbXB1dGVfc3NpbV9vbmx5X2F0X29yaWdpbmFsX3Jlc29sdXRpb24AHXVzZV9sYW5jem9zX2Zvcl92cW1fdXBzY2FsaW5nABFkaXNhYmxlX3Bvc3RfcHZxcwAVACUAHAAAJsjdreOe84MUFZBOKAJDMxgLdnRzX3ByZXZpZXccF0CWL6wIMSbpGDRkYXNoX2k0bGl0ZWJhc2ljX3Bhc3N0aHJvdWdoYWxpZ25lZF9ocTJfZnJhZ18yX3ZpZGVvEgAYGHZpZGVvcy52dHMuY2FsbGJhY2sucHJvZDgSVklERU9fVklFV19SRVFVRVNUGw6IFW9lbV90YXJnZXRfZW5jb2RlX3RhZwZvZXBfaGQTb2VtX3JlcXVlc3RfdGltZV9tcwEwDG9lbV9jZmdfcnVsZQd1bm11dGVkE29lbV9yb2lfcmVhY2hfY291bnQBMBFvZW1faXNfZXhwZXJpbWVudAARb2VtX3JvaV91c2VyX3RpZXIDdWdjHm9lbV9yb2lfcHJlZGljdGVkX3dhdGNoX3RpbWVfcwEwFm9lbV9yb2lfcmVjaXBlX2JlbmVmaXQFMC4wMDAlb2VtX3JvaV9zdGF0aWNfYmVuZWZpdF9jb3N0X2V2YWx1YXRvcgtwcm9ncmVzc2l2ZQxvZW1fdmlkZW9faWQQMTgyNDc5NzA4MTIzOTMzOBJvZW1fdmlkZW9fYXNzZXRfaWQQNTQxNzg0MTQwODMyMDM3MhVvZW1fdmlkZW9fcmVzb3VyY2VfaWQQNTYzODA3NjQxOTY1MTQyOBxvZW1fc291cmNlX3ZpZGVvX2VuY29kaW5nX2lkDzkxODUxMzQ4OTMyOTI2MA52dHNfcmVxdWVzdF9pZA8yZWU5N2Q0ZTBlYjU0MmUlAhwcHBXw5hcbAVUAAhsBVQACHBUCAAAAFoC6twMAJY4CGwiIAXMENTE4OAJjZAoyMDIzLTAyLTAyA3JjYgEwA2FwcAZ1cGxvYWQCY3QZQ09OVEFJTkVEX1BPU1RfQVRUQUNITUVOVBNvcmlnaW5hbF9kdXJhdGlvbl9zCDE0MjAuMDc1AWYCYWQCdHMVcHJvZ3Jlc3NpdmVfZW5jb2RpbmdzAA%3D%3D&ccb=1-7&_nc_sid=41a7d5&_nc_ohc=L_dzb8dbQwcAX8wwXSo&_nc_ht=scontent-sin6-2.xx&edm=APRAPSkEAAAA&oh=00_AfCY25yJxLCTq0lZ1bttybDBFV_-7qbGg7ZZoE3s_1nEig&oe=63F82C10&_nc_rid=897881643295126" -v`

But the window has no title so could you please fix or improve this issue? Thank you so much

### Expected behavior

MPV will load ok with video has title

### Actual behavior

MPV will crash when a URL is too long

MPV will ok when set no title but the window has no title

**Comment by thebombzen** [comment]
Please post a log file with `mpv --log-file=mpv-sucks.log ...` where `...` are the other options you set.
