### ISSUE TITLE
vo_gpu-next: dovi p4's brightness is too high

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#11350]
### Important Information

Provide following Information:
- mpv version
 https://github.com/mpv-player/mpv/commit/c0807e98fbc808b50d58ae88b4ae05b0cd956e69
- Platform and Version
 win10pro 22h2
- Source of the mpv binary
 https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230222

### Reproduction steps

Load a dovi p4 video.

### Expected behavior

Reasonable brightness. 
<img src="https://user-images.githubusercontent.com/41094733/220634963-f0c4c7e1-46d6-4615-b189-68d2e8f2868e.jpg" width=500>

### Actual behavior

<img src="https://user-images.githubusercontent.com/41094733/220634982-97d574f8-e6c2-4608-9512-e2b08d3d8add.jpg" width=500>

### Log file

N/a

### Sample files

https://4kmedia.org/lg-dolby-vision-uhd-4k-demo/

**Comment by quietvoid** [comment]
Profile 4 is deprecated and I don't think the goal was ever to support it properly, so I'm not sure this will be improved on.

**Comment by dyphire** [comment]
> Profile 4 is deprecated and I don't think the goal was ever to support it properly, so I'm not sure this will be improved on. It probably should be falling back to SDR, instead.

I can get relatively normal results without libdovi.
![image](https://user-images.githubusercontent.com/61936050/220637635-51855b4c-4b35-4cb1-a6b2-adc07820dbbe.png)

**Comment by quietvoid** [comment]
Right, but the profile is still only partially supported by libplacebo.
So we should probably ignore the brightness metadata.

**Comment by dyphire** [comment]
> Right, but the profile is still only partially supported by libplacebo. So we should probably ignore the brightness metadata.

I agree with you.

**Comment by quietvoid** [comment]
Should be fixed by https://code.videolan.org/videolan/libplacebo/-/merge_requests/383.
The metadata would be ignored for profile 4.
