### ISSUE TITLE
[QUESTION] Help to make a script: in a playlist, start playback of videos at random times

### ISSUE THREAD

**Issue by masterofobzene** [mpv-player/mpv#11356]
Hi, I need to make a LUA script to play videos from a playlist at random times. 
I've been watching the manual but could not find a way to tell the program to start playback at a random place in the timeline.

Can anybody help?

**Comment by christoph-heinrich** [comment]
For random numbers you can use [math.random()](https://www.lua.org/manual/5.1/manual.html#pdf-math.random), and you probably want to initialize it first with e.g. `math.randomseed(os.time())`.

For setting the start time of the file it's probably best to use one of the [hooks](https://mpv.io/manual/master/#hooks).
`on_load` or `on_preloaded` and then either set the [start time](https://mpv.io/manual/master/#options-start) or  [seek](https://mpv.io/manual/master/#command-interface-seek-%3Ctarget%3E-[%3Cflags%3E]) to the desired time. You'll have to try which combination works. I'd expect `on_load` to only work with `start`, but `on_preloaded` might only work with `seek`.
