### ISSUE TITLE
Where can I download the MacOS libmpv library?

### ISSUE THREAD

**Issue by RealChuan** [mpv-player/mpv#11355]
Help me, where can I download libmpv.dylib, libmpv.a and the header file, just a binary dynamic library with all the dependencies. Just like Windows, links to https://sourceforge.net/projects/mpv-player-windows/files/libmpv/.

I'm developing a qt and libmpv based audio and video player [Qt-Mpv](https://github.com/RealChuan/Qt-Mpv).
I need a dependency library for MacOS.

**Comment by hooke007** [comment]
ref iina , build it by yourself. https://github.com/iina/iina#building-mpv-manually

**Comment by RealChuan** [comment]
Thank you. I'll try

**Comment by Akemi** [comment]
we don't provide any official builds.
