### ISSUE TITLE
Compiled mpv fails to run, missing symbols

### ISSUE THREAD

**Issue by LillyWho** [mpv-player/mpv#11372]
Environment: 
macOS 10.13.3
Xcode 10.1

mpv git rev 9e7c7c2fd128535de4c837eb28c59f1492c12150

MacPorts

Compile options: -Dlibmpv=true -Dprefix=/opt
Meson autodetected ninja, so I used ninja to compile and install.

> [1/2] Installing files.
> Installing libmpv.2.dylib to /opt/lib
> Installing mpv to /opt/bin
> Installing /Users/lilly/mpv/libmpv/client.h to /opt/include/mpv/
> Installing /Users/lilly/mpv/libmpv/render.h to /opt/include/mpv/
> Installing /Users/lilly/mpv/libmpv/render_gl.h to /opt/include/mpv/
> Installing /Users/lilly/mpv/libmpv/stream_cb.h to /opt/include/mpv/
> Installing /Users/lilly/mpv/build/meson-private/mpv.pc to /opt/lib/pkgconfig
> Installing /Users/lilly/mpv/etc/mpv.conf to /opt/share/doc/mpv
> Installing /Users/lilly/mpv/etc/input.conf to /opt/share/doc/mpv
> Installing /Users/lilly/mpv/etc/mplayer-input.conf to /opt/share/doc/mpv
> Installing /Users/lilly/mpv/etc/restore-old-bindings.conf to /opt/share/doc/mpv
> Installing /Users/lilly/mpv/etc/mpv.bash-completion to /opt/share/bash-completion/completions
> Installing /Users/lilly/mpv/etc/_mpv.zsh to /opt/share/zsh/site-functions
> Installing /Users/lilly/mpv/etc/mpv.desktop to /opt/share/applications
> Installing /Users/lilly/mpv/etc/mpv.metainfo.xml to /opt/share/metainfo
> Installing /Users/lilly/mpv/etc/encoding-profiles.conf to /opt/etc/mpv
> Installing /Users/lilly/mpv/etc/mpv-icon-8bit-16x16.png to /opt/share/icons/hicolor/16x16/apps
> Installing /Users/lilly/mpv/etc/mpv-icon-8bit-32x32.png to /opt/share/icons/hicolor/32x32/apps
> Installing /Users/lilly/mpv/etc/mpv-icon-8bit-64x64.png to /opt/share/icons/hicolor/64x64/apps
> Installing /Users/lilly/mpv/etc/mpv-icon-8bit-128x128.png to /opt/share/icons/hicolor/128x128/apps
> Installing /Users/lilly/mpv/etc/mpv-gradient.svg to /opt/share/icons/hicolor/scalable/apps
> Installing /Users/lilly/mpv/etc/mpv-symbolic.svg to /opt/share/icons/hicolor/symbolic/apps
> Installing symlink pointing to libmpv.2.dylib to /opt/lib/libmpv.dylib
>  lilly@Lillys-iMac  ~/mpv/build   master  mpv
> dyld: Symbol not found: __T0So8NSWindowC5LevelV6AppKit01_cdD23NumericRawRepresentableAEWP
>   Referenced from: /opt/local/bin/mpv
>   Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftAppKit.dylib
>  in /opt/local/bin/mpv
> Abort trap: 6
> 

I don't know why mpv even looks for swift in that location, because I've got the command line runtime installed separately in `/usr/lib/swift`

**Comment by Akemi** [comment]
seems more like a macports problem or a wrongly setup build environment or env variables. though without the full logs no idea. we had similar problems previously (#8295).

the SDKs and build tools which are specified wie `xcode-select` are used, if not overwritten via the corresponding env variables, mentioned in the issue above. if anything mismatches it's most likely a problem with macports.

**Comment by LillyWho** [comment]
I've done a rebuild after explicitly setting xcode-select to the command line tools. How that affects swift libraries though, since they are a separate component, I can't say.
[configure.log](https://github.com/mpv-player/mpv/file
[build.log](https://github.com/mpv-player/mpv/files/10831522/build.log)
s/10831516/configure.log)
How MacPorts is supposed to come into this I don't quite see. Since the build config is using pkgconfig, and the MP pkgconfig has its prefix in /opt, it should find all dependencies, and apparently it does. It also does _find_ the swift library it's looking for, but like the error says, it's missing a symbol that mpv is expecting.

The same error occurs even with the xcode SDK set to the command line tools.

**Comment by LillyWho** [comment]
I've run the command you listed in the other issue and for some reason it's pointing towards the 10.14 SDK?? I don't recall installing anything mismatching my macOS version.
``/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk``

**Comment by Akemi** [comment]
the swift libs are not found with pkconfig, that is custom code that uses the various xcode clis to find its dependencies etc. this can be influenced by various env variables that macports set. we already had various issues opened because of incorrectly set variables and/or incorrectly setup build environment from macports.

if you install the newest xcode or command line tools for your OS version it will always have a newer SDK installed than the actual OS (if available). so 10.14 is normal on 10.13.

some general things:
1. we don't give macports support, if the issue can be reproduced without macports it would be different story
2. the issue is most like a wrongly setup build environment
3. build.log ist not sufficient with a build problem, the configure/setup step is also important and its corresponding log
4. you macOS version ist completely outdated and like apple we only support the latest 3 OS versions

**Comment by LillyWho** [comment]
Just for posterity for future googlers, I fixed it by downgrading to Xcode 9.4.1.
