### ISSUE TITLE
Random stuff is shown while opening up MPV

### ISSUE THREAD

**Issue by bhumit070** [mpv-player/mpv#11371]
### Important Information

Provide following Information:
- mpv 0.35.1
- macOS Version 13.2.1
- Source of the mpv binary or bundle  - https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-latest.tar.gz
- If known which version of mpv introduced the problem 0.35.1
- Possible screenshots or video of visual glitches

<img width="1512" alt="Screenshot 2023-02-25 at 4 01 17 PM" src="https://user-images.githubusercontent.com/63059063/221352086-6d684a0f-25a6-41c6-8593-3013cd837c37.png">

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
nothing I just hit mpv FILE NAME

### Expected behavior
It should only show playing info right 

### Actual behavior
it is showing some gibberish stuff

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/10830872/mpv.log)

**Comment by Akemi** [comment]
> If known which version of mpv introduced the problem 0.35.1

previous versions of mpv don't exhibit that problem?

**Comment by bhumit070** [comment]
> > If known which version of mpv introduced the problem 0.35.1
> 
> previous versions of mpv don't exhibit that problem?

Nope I am sorry I don't know which previous version I was using but I am sure it didn't had this problem 
But recently I factory reset my mac and installed latest version of mpv and this stuff is being showed in console

**Comment by globau** [comment]
This is #11018

**Comment by Akemi** [comment]
closing this as a duplicate for now and possible macOS bug.
