### ISSUE TITLE
how to configure mpv.conf for streaming videos without using vp9 codec

### ISSUE THREAD

**Issue by bheeshmpita** [mpv-player/mpv#11381]
what code must be added to the file so that it streams youtube video without vp9 codec and/or uses h264 codec with hwdec. I am using yt-dlp. Instead of terminal i stream yt videos with playwithmpv extension.
OS linuxmint 21 xfce

**Comment by lavilao** [comment]
have you tried using the h264ify extension?

**Comment by bheeshmpita** [comment]
> have you tried using the h264ify extension?

isnt that is useful when i want to stream on website youtube.com itself?  i want to stream yt videos with mpv and i use invidious instances and piped instead of youtube.com

**Comment by 42147** [comment]
Something like this:
`ytdl-format=bestvideo[vcodec^=avc1]+bestaudio`
`hwdec=auto-safe`

**Comment by lavilao** [comment]
> > have you tried using the h264ify extension?
> 
> isnt that is useful when i want to stream on website youtube.com itself? i want to stream yt videos with mpv and i use invidious instances and piped instead of youtube.com

Oh, sorry did not knew you used invidious. I can however recommend you to try pipe-viewer, it supports playback with mpv, streaming from invidious, subscribe to chanels (without yt account), it has a preffer mp4 option so it should also support your usecase of streaming avc videos. If not then @42147 mpv settings should do the trick.

**Comment by bheeshmpita** [comment]
> Something like this: `ytdl-format=bestvideo[vcodec^=avc1]+bestaudio` `hwdec=auto-safe`

It works when i use it in terminal like
`mpv --ytdl-format='bestvideo[height<=?480][fps<=?30][vcodec^=avc1]+bestaudio/best' URL`

but adding `ytdl-format='bestvideo[height<=?480][fps<=?30][vcodec^=avc1]+bestaudio/best'` to mpv.conf and then streaming the video (with extension playwithmpv) still loads the vp9 video.
What am i missing?

**Comment by bheeshmpita** [comment]
fixed it by creating a yt-dlp.conf file with its content as `-S "codec:h264"`
the solution may seem simple but was definitely not, especially for who does not have programming/technical knowledge and can easily get perplexed by different parameters with their permutation and combination possibilities. Hope this can be helpful for others too.
