### ISSUE TITLE
[Documentation, minor] FFMPEG 6.0 support?

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#11387]
Hey guys,

FFMPEG just had its 6.0 release recently. Right now I do not know whether mpv works with it or not;
I am compiling ffmpeg 6.0 first, then a mpv git checkout soon (afterwards), then I will test the new 
ffmpeg with mpv too.

Would it be possible to mention in the documentation which FFMPEG versions are supported? Ideally
in a table layout, but that's not so important, compared to stating somewhere which ffmpeg versions
are supported. If it has no place in the main README then perhaps the wiki could mention it, or
some other file under doc/ or something like that, so that we can find that information. At any
rate, thanks for reading - may mpv continue to play every alien and not-so-alien multimedia 
format out there.

**Comment by Dudemanguy** [comment]
mpv only requires a minimum ffmpeg version. We always try to support the newest version. You'll notice that on the releases page it say something like `This release requires FFmpeg 4.0 or newer.` To my knowledge, there is no problem with ffmpeg 6.0, but if there is we'll fix it.

**Comment by elzii** [comment]
There is. Just upgraded to ffmpeg 6, here's the error when trying to start mpv from cli:

```
dyld[23561]: Library not loaded: /opt/homebrew/opt/ffmpeg/lib/libavcodec.59.dylib
  Referenced from: <E2122403-BEAA-3DA4-87C1-C0D991B18002> /opt/homebrew/bin/mpv
  Reason: tried: '/opt/homebrew/opt/ffmpeg/lib/libavcodec.59.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/ffmpeg/lib/libavcodec.59.dylib' (no such file), '/opt/homebrew/opt/ffmpeg/lib/libavcodec.59.dylib' (no such file), '/usr/local/lib/libavcodec.59.dylib' (no such file), '/usr/lib/libavcodec.59.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/ffmpeg/6.0/lib/libavcodec.59.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/ffmpeg/6.0/lib/libavcodec.59.dylib' (no such file), '/opt/homebrew/Cellar/ffmpeg/6.0/lib/libavcodec.59.dylib' (no such file), '/usr/local/lib/libavcodec.59.dylib' (no such file), '/usr/lib/libavcodec.59.dylib' (no such file, not in dyld cache)
```

As a temporary workaround on macOS, you can run:
```
brew unlink ffmpeg
brew install ffmpeg@5
```

**Comment by Dudemanguy** [comment]
That's a packaging and/or user error. Your mpv needs to be rebuilt to link to the new ffmpeg library if you want to upgrade. It's not an mpv problem.
