### ISSUE TITLE
commit d941564 break the osc-like's scripts previous rendering

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#11383]
### Important Information

Provide following Information:
- mpv version
 https://github.com/mpv-player/mpv/commit/d941564d48e4963b3b69370d0a8313bea2bec678
- Platform and Version
 Any
- Source of the mpv binary
 shinchiro

### Reproduction steps

This commit makes other osc-like script's margin ignored. I think it should be reverted or post another better resolution rather than simply remove the previous codes.

### Expected behavior

![Snipaste_2023-02-27_01-41-50](https://user-images.githubusercontent.com/41094733/221452820-4598899c-2aea-4b8f-9690-af8a687ff771.jpg)

### Actual behavior

![Snipaste_2023-02-27_01-40-06](https://user-images.githubusercontent.com/41094733/221452827-d505e068-ec8c-4ed5-a368-2e63b0e95147.jpg)

### Log file

It's not a bug.

**Comment by Dudemanguy** [comment]
These other scripts should just use `user-data` now. Or is there something I'm missing here?

**Comment by christoph-heinrich** [comment]
Considering what the [docs](https://mpv.io/manual/master/#command-interface-shared-script-properties) have to say about shared-script-properties, I'd say that's a problem of other scripts. I'll make a PR for uosc.

**Comment by hooke007** [comment]
console only observes osc‘s user-date

**Comment by christoph-heinrich** [comment]
There you go https://github.com/tomasklaen/uosc/pull/461

**Comment by hooke007** [comment]
Hava you tested? It doesn’t work.

**Comment by christoph-heinrich** [comment]
Yes I've tested it, it works for me. We can discuss any problems with the PR over there instead of here.

**Comment by hooke007** [comment]
Oh no, I made a sily mistake in my side. closing
