### ISSUE TITLE
current-window-scale returns a nil 

### ISSUE THREAD

**Issue by SacredZenpie** [mpv-player/mpv#11384]
### Important Information

Provide following Information:
- mpv 0.35.0-221-ga40958cd
- Windows 10 LTSC 21H2
- Source of the mpv binary : shinchiro

### Reproduction steps
Trying to get a value for current window scale in lua like so:
local prev_scale = mp.get_property_native("current-window-scale") 

### Expected behavior
a value
### Actual behavior
nil

### Sample and log files
Here are the sample files,
[log-file.txt](https://github.com/mpv-player/mpv/files/10836018/log-file.txt)
[testy.lua.txt](https://github.com/mpv-player/mpv/files/10836022/testy.lua.txt)

**Comment by CounterPillow** [comment]
That is honestly what I expect when mpv hasn't opened a window yet.

**Comment by Dudemanguy** [comment]
If the window isn't actually available yet, you will indeed get nil. Try waiting on something like the `video-reconfig` event instead.

**Comment by SacredZenpie** [comment]
Even if called later (with a keybind for example) it still returns a nil

**Comment by Dudemanguy** [comment]
That's definitely not supposed to happen.

```
function check_window_scale()
	scale = mp.get_property_native('current-window-scale')
	mp.osd_message(scale)
end

mp.add_key_binding("C", "check-window-scale", check_window_scale)
```

This works for me for example. Are you saying that prints nil?
