### ISSUE TITLE
RTX Video Enhancement support

### ISSUE THREAD

**Issue by germn** [mpv-player/mpv#11390]
There was an RTX Video Enhancement release recently.
https://nvidia.custhelp.com/app/answers/detail/a_id/5448

Basically, it allows real-time AI video upscaling on recent RTX video cards.
It would be nice to have this feature available in mpv as well.

There's already a release for MPC with support of this:
https://github.com/emoose/VideoRenderer/releases/tag/rtx-1.0

**Comment by saha1914** [comment]
+

**Comment by JoseHidalgo** [comment]
Just wanted to support this idea. No doubt that a MPV hero will take on this mission. :) The new feature is supposed to work not only on 4xxx cards but on 3xxx cards also.

Caution, there may be some issues to tackle : memory leaks on some HEVC 10bit videos, or the enhancements not working on vertical videos. See here:
https://www.reddit.com/r/nvidia/comments/11e7e2h/comment/jacujw9/?utm_source=reddit&utm_medium=web2x&context=3
https://github.com/emoose/VideoRenderer/issues/1#issuecomment-1450964365

**Comment by askasys-code** [comment]
I'm totally interessed to have this feature in mpv. 
I tried RTX VSR on MPC-BE and almost completely beat many upscalers I use with mpv, like FSRCNNX. It is absolutely worth it.

**Comment by cloud11665** [comment]
I can take a look at this after getting access to a 40 series GPU

**Comment by Myaanee** [comment]
> I can take a look at this after getting access to a 40 series GPU

If you need a tester @ me, I have a 4080

**Comment by NekuSoul** [comment]
> I can take a look at this after getting access to a 40 series GPU

As a side-note to avoid possible misconceptions: RTX Video is also available for the RTX 30xx series.

**Comment by cloud11665** [comment]
I currently have a 2080, and I will have access to a 4070 in ~2-3 weeks

**Comment by j1warren** [comment]
> VideoLAN is expected to release an update to VLC later today (April 12) with RTX Video Super Resolution support.

**Comment by askasys-code** [comment]
Tested on vlc-3.0.19 and it works. Now only mpv remain, I really hope will be supported soon. Maybe with a lua script? A toggle option is mandatory in my opinion, because both MPC-HC and VLC have VSR always full ON and it's annoying.

**Comment by 360hzz** [comment]
yes we are waiting for MPV my RTX 3080

**Comment by saha1914** [comment]
there is already a VSR for VapourSynth
https://github.com/HolyWu/vs-basicvsrpp
only if someone would have build it

**Comment by saha1914** [comment]
> > there is already a VSR for VapourSynth https://github.com/HolyWu/vs-basicvsrpp only if someone would have build it
> 
> This doesn't seem to have anything to do with the NVIDIA VSR based on d3d11vpp.

really sorry ooooppps

**Comment by cloud11665** [comment]
update: I now have access to a 40-series GPU, just need to set up my devenv on windows, and I can take a closer look.

**Comment by deama** [comment]
> update: I now have access to a 40-series GPU, just need to set up my devenv on windows, and I can take a closer look.

Any luck?

**Comment by radozd** [comment]
Aaaaand?

**Comment by kasper93** [comment]
> Aaaaand?

Aaaaand, I can implement that, just need a GPU. We can discuss shipping/payment details. You can find my email in my profile.

**Comment by Holdo** [comment]
@kasper93 RTX VSR 1.5 now works on RTX 2000 series as well, don't need 4000 series.

**Comment by deama** [comment]
> > Aaaaand?
> 
> Aaaaand, I can implement that, just need a GPU. We can discuss shipping/payment details in email. You can find my email address in my profile. (my nick on gmail)

So I guess this was a joke or were you trying to scam someone?

**Comment by kasper93** [comment]
> So I guess this was a joke or were you trying to scam someone?

Scam of what? It has been months and looks like no one capable of adding this feature to mpv cares to do so. Like I said I don't have NVIDIA GPU, nor I intend to buy one, so I won't work on this feature, unless someone contribute the GPU. And since there is constant nagging in here to get it implemented I offered my help and stated my price. I was mostly joking, because I don't expect you guy understand how contracting works, but messages like `Aaaaand?` won't persuade anyone to work on this feature.

Look at my recent commit history in here if you call out scams... If anything I'm scammed of my free time working on this project.

**Comment by deama** [comment]
> > So I guess this was a joke or were you trying to scam someone?
> 
> Scam of what? It has been months and looks like no one capable of adding this feature to mpv cares to do so. Like I said, I don't have NVIDIA GPU, nor I intend to buy one, so I won't work on this feature, unless someone contribute the GPU. And since there is constant nagging in here to get it implemented I offered my help and stated my price. I was mostly joking, because I don't expect you guys understand how contracting works, but messages like `Aaaaand?` won't persuade anyone to work on this feature.
> 
> Look at my recent commit history in here if you call out scams... If anything I'm scammed of my free time working on this project.

I think it looks pretty good.

**Comment by kenpuluma** [comment]
> > So I guess this was a joke or were you trying to scam someone?
> 
> Scam of what? It has been months and looks like no one capable of adding this feature to mpv cares to do so. Like I said, I don't have NVIDIA GPU, nor I intend to buy one, so I won't work on this feature, unless someone contribute the GPU. And since there is constant nagging in here to get it implemented I offered my help and stated my price. I was mostly joking, because I don't expect you guys understand how contracting works, but messages like `Aaaaand?` won't persuade anyone to work on this feature.
> 
> Look at my recent commit history in here if you call out scams... If anything I'm scammed of my free time working on this project.

If you consider two messages between Jun and Oct as "constant nagging" and it bothers you, and you require sponsorship to start your work then probably you shouldn't spend your time for an open source project. Complains like yours won't persuade anyone away from asking for new features, explanations like @Andarwinux's will.

**Comment by tliron** [comment]
> If you consider two messages between Jun and Oct as "constant nagging" and it bothers you, and you require sponsorship to start your work then probably you shouldn't spend your time for an open source project. Complains like yours won't persuade anyone away from asking for new features, explanations like @Andarwinux's will.

People like you make me hate volunteering my work for open source.

Your sense of entitlement is absurd. Nobody owes you this feature. And also nobody owes you an in-depth explanation of the technical or personal or monetary or whatever challenges keep it from being implemented as fast as you might like.

The feature was asked for. The issue was not closed, so it's welcome. If you want it so much, develop it yourself and submit a PR. Otherwise, sit yourself down and wait patiently and politely and gratefully for the project's volunteers to do the work for you, free of charge, while you type "And?".

**Comment by kenpuluma** [comment]
> > If you consider two messages between Jun and Oct as "constant nagging" and it bothers you, and you require sponsorship to start your work then probably you shouldn't spend your time for an open source project. Complains like yours won't persuade anyone away from asking for new features, explanations like @Andarwinux's will.
> 
> People like you make me hate volunteering my work for open source.
> 
> Your sense of entitlement is absurd. Nobody owes you this feature. And also nobody owes you an in-depth explanation of the technical or personal or monetary or whatever challenges keep it from being implemented as fast as you might like.
> 
> The feature was asked for. The issue was not closed, so it's welcome. If you want it so much, develop it yourself and submit a PR. Otherwise, sit yourself down and wait patiently and politely and gratefully for the project's volunteers to do the work for you, free of charge, while you type "And?".

I'm not begging you for development, I'm not even the one who typed "And". I'm just searching online and happened to found this issue, and it looks to me that the discussion was normal until somebody asks for a payment (I guess it's a joke).

If you hate volunteering your work for open source then don't do it, like you said nobody is forcing you.

**Comment by tliron** [comment]
> If you hate volunteering your work for open source then don't do it, like you said nobody is forcing you.

I don't work on mpv, just a huge fan, but I work on many other open source projects. Nobody is forcing me, it's my choice (and in some cases my job), and I don't demand nor expect gratitude. But I definitely don't deserve abuse and disrespect, and I shouldn't have to develop a "thick skin" if my projects become popular. That shouldn't be part of the work. Remember that there are real people behind mpv. Check your attitude and consider your interactions. perhaps do your best to make their work joyful and fun rather than annoying and stressful.

**Comment by N-R-K** [comment]
> [...] probably you shouldn't spend your time for an open source project

This is not your place to state what others should or should not do in their own time.

> the discussion was normal until somebody asks for a payment (I guess it's a joke)

Perhaps you're from some communist utopia but asking for payment for your work is nothing abnormal around the rest of the world.

And if you're so bothered by someone not wanting to spend hundreds of dollars to implement a feature for free for randoms on the internet, then go ahead and be the change you wish to see in the world. Buy yourself a compatible gpu and send the patches.

**Comment by kenpuluma** [comment]
I really don't want to populate the Github issue with meaningless, unrelated messages in a but if you insists ok:

> This is not your place to state what others should or should not do in their own time.
Agreed. Github issue is the place for tracking work and collaboration on the project, not for making jokes and spreading hates and stress.

> Perhaps you're from some communist utopia but asking for payment for your work is nothing abnormal around the rest of the world.
Don't try to change the subject. It's definitely normal for asking payments for anything you have spent time on, lots of people work on open source projects for a living.
But the discussion went pretty off the track and became completely irrelevant about its original topic: "RTX Video Enhancement support" now, people started defending themselves on scam or not scam, be thankful to open source contributors or not , beginning from that payment joke.

If this is how you want this repository looks like, then it's fine, leave people there to fight against each others.

**Comment by kasper93** [comment]
> VSR has no status feedback, so there is no reliable way to confirm VSR is active.

How the driver handles the scaling is indeed not visible. But adding generic d3d11vpp scaling is good either way. Even if not VSR, it would still scale, deepening on vendor with various quality.

Also note that passing frames through video processor can/will also apply other adjustments that they have in pipeline, which in most cases are not wanted.

> This feature was designed primarily for Chromium, which is planning to move to D3D12, so D3D11VPP VSR will certainly be dropped eventually, or even removed from drivers at some point. Adding VSR may not be worth it at this time.

I think you infer too much. d3d11 or d3d12 is only an API, there is no need to remove the scaler from d3d11 video processor to make it work for d3d12 video processor. Unless there would be needed API extension.

> Intel actually also support VSR (Arc only) but like NVIDIA there is no status feedback and Intel's VSR has no gpu control panel switches or options and the effect is much weaker, you never know if VSR is active or not.

Similar situation, we just request the scaling. It is on driver control panel to expose proper feedback/control.

**Comment by haasn** [comment]
Don't listen to paid AMD shills trying to subvert this issue

**Comment by kasper93** [comment]
> @kasper93 RTX VSR 1.5 now works on RTX 2000 series as well, don't need 4000 series.

AMD has it's own upscaling now. You don't even need NVIDIA gpu to implement this. Just the latest AMD ones. (at least for the AMD, probably different guids and so on)

> AMD Video Upscaling – Advanced video upscale algorithm to improve video playback image quality for AMD Radeon™ RX 7000 desktop series GPUs. 

https://www.amd.com/en/support/kb/release-notes/rn-rad-win-24-1-1

...

**Comment by Hrxn** [comment]
I assume this'll be the default setting for Chrome/Edge somewhat soon?

BTW, the description blurb for this flag is:
>Enable/Disable the use of MediaFoundation for non-protected content playback on supported systems. – Windows

Implying that MediaFoundation is already used for Widevine content etc.

**Comment by wadixx** [comment]
MPC-HC, Potplayer and VLC already started using RTX VSR. Can we expect this feature soon?

**Comment by billxc** [comment]
Having study the code of MPC Render, and chromium. The magic code is quite easy

```cpp
    constexpr GUID kNvidiaPPEInterfaceGUID = {
        0xd43ce1b3,
        0x1f4b,
        0x48ac,
        {0xba, 0xee, 0xc3, 0xc2, 0x53, 0x75, 0xe6, 0xf7}};
    constexpr UINT kStreamExtensionVersionV1 = 0x1;
    constexpr UINT kStreamExtensionMethodSuperResolution = 0x2;

    struct {
        UINT version;
        UINT method;
        UINT enable;
    } stream_extension_info = {kStreamExtensionVersionV1,
                                kStreamExtensionMethodSuperResolution,
                                1u};

    hr = ID3D11VideoContext_VideoProcessorSetStreamExtension(p->video_ctx,p->video_proc,&kNvidiaPPEInterfaceGUID,
        sizeof(stream_extension_info), &stream_extension_info);
```

I tried to add this code to `d3d11vpp.c`
But nothing happened, no super res, even no crash.
I am new to MPV, will work to find out if the codes are included in the compile.


https://github.com/mpv-player/mpv/commit/bcaefa61e3b79f28b80e60940ba60454da5becf3

https://github.com/emoose/VideoRenderer/commit/a684e0adff37fbdbe217db464df77beb0e8ca514
https://github.com/chromium/chromium/commit/46f000a1de9e77a90f6ef3c9b6be72f86752304b#diff-993a15e7a79f90944c791b0c616715be012bf762dd8f7a18bc27e8a597fd18fb

**Comment by wadixx** [comment]
> Having study the code of MPC Render, and chromium. The magic code is quite easy
> 
> ```c++
>     constexpr GUID kNvidiaPPEInterfaceGUID = {
>         0xd43ce1b3,
>         0x1f4b,
>         0x48ac,
>         {0xba, 0xee, 0xc3, 0xc2, 0x53, 0x75, 0xe6, 0xf7}};
>     constexpr UINT kStreamExtensionVersionV1 = 0x1;
>     constexpr UINT kStreamExtensionMethodSuperResolution = 0x2;
> 
>     struct {
>         UINT version;
>         UINT method;
>         UINT enable;
>     } stream_extension_info = {kStreamExtensionVersionV1,
>                                 kStreamExtensionMethodSuperResolution,
>                                 1u};
> 
>     hr = ID3D11VideoContext_VideoProcessorSetStreamExtension(p->video_ctx,p->video_proc,&kNvidiaPPEInterfaceGUID,
>         sizeof(stream_extension_info), &stream_extension_info);
> ```
> 
> I tried to add this code to `d3d11vpp.c` and enable the the filter by using `vf set d3d11vpp=deint=no`. But nothing happened, no super res, even no crash. I am new to MPV, will work to find out if the codes are included in the compile.
> 
> [bcaefa6](https://github.com/mpv-player/mpv/commit/bcaefa61e3b79f28b80e60940ba60454da5becf3)
> 
> [emoose/VideoRenderer@a684e0a](https://github.com/emoose/VideoRenderer/commit/a684e0adff37fbdbe217db464df77beb0e8ca514) [chromium/chromium@46f000a#diff-993a15e7a79f90944c791b0c616715be012bf762dd8f7a18bc27e8a597fd18fb](https://github.com/chromium/chromium/commit/46f000a1de9e77a90f6ef3c9b6be72f86752304b#diff-993a15e7a79f90944c791b0c616715be012bf762dd8f7a18bc27e8a597fd18fb)

Looking forward to hearing from you.

**Comment by billxc** [comment]
Update the status: Now the RTX Super Res works, but with a little hard code, and ready for merge.

If you are curious about the code, just refer to https://github.com/billxc/mpv.

This relies on the D3D11VPP filter and seems that it cannot be used together with vapoursynth filter. 
@kasper93 could you help confirm if it is expected, and is there any way to make both filters work together?

**Comment by wadixx** [comment]
> Update the status: Now the RTX Super Res works, but with a little hard code, and NOT ready for merge.
> 
> If you are curious about the code, just refer to https://github.com/billxc/mpv.
> 
> This relies on the D3D11VPP filter and seems that it cannot be used together with vapoursynth filter. @kasper93 could you help confirm if it is expected, and is there any way to make both filters work together?

You are a hero. Hope @kasper93 can merge this into mpv.

**Comment by philipl** [comment]
> Update the status: Now the RTX Super Res works, but with a little hard code, and NOT ready for merge.
> 
> If you are curious about the code, just refer to https://github.com/billxc/mpv.
> 
> This relies on the D3D11VPP filter and seems that it cannot be used together with vapoursynth filter. @kasper93 could you help confirm if it is expected, and is there any way to make both filters work together?

The vapoursynth filter is a CPU filter, so it's never going to work directly. You would need to do a GPU upload/download (depending on the order of operations) to the frames into the right place for the other filter. I expect ffmpeg has upload/download support for d3d11va so it ought to be possible, but you'd need to work out how to construct the correct filter chain yourself, and you may still find additional limitations getting in your way.

A mergeable implementation would require extending the d3d11vpp filter to have a scaling mode with proper specification of the output frame size/format/etc and then a way to select the scaling mode (of which RTX Video is just one of many).

**Comment by wadixx** [comment]
@billxc Any updates on this?

**Comment by billxc** [comment]
> @billxc Any updates on this?

https://github.com/billxc/mpv/releases/tag/MPV-RTX-SuperRes-RC

Not quite ready for merge, but ready for test.

Note: the filter usage is not the final version, and may be changed in the future.

**Comment by philipl** [comment]
@billxc First off, it's great that you're working on this, and thank you for looking at my original feedback. However, after taking an initial look at your tree, it looks like you have written it as a separate filter. For it to be mergeable, the functionality should be added to `d3d11vpp`. Were you just doing it as a separate filter as an initial development step? I can't tell.

Also, the filter's configuration interface should not hard code the "Super Resolution" concept - as I understand it, it's just a generic scaling function and vendors or anyone can write and plug in a scaling algorithm (I see you have added Intel as a second example), so it should just be a `scale` configuration. It should also support taking arbitrary width and height for the scaling output, as that is supported in the general case (does RTX Video only work for fixed resolutions?). Thanks!

Feel free to open a PR - it will be easier to discuss there.

**Comment by kasper93** [comment]
Also to make it scalable for the future we could extend options of `d3d11vpp` with arbitrary GUID that user could provide. Would avoid having to recompile mpv for different variant of the same. I think AMD has some sort of super res too, which has to be enabled, because normally this interface just scales without fancy features.

**Comment by billxc** [comment]
@philipl  @kasper93 
I have created a PR, we can move the discussion there
https://github.com/mpv-player/mpv/pull/14155

**Comment by tmarkov** [comment]
Does this only work for Direct3d (i.e. Windows)?

**Comment by kasper93** [comment]
> Does this only work for Direct3d (i.e. Windows)?

Yes, it works for d3d11, only on Windows.

**Comment by kasper93** [comment]
Well, patches welcome. I don't have hardware to test this. You can send me GPU if you like. Else unless someone fixes it, it will stay in this state. d3d11vp extension is enabled. There might be format constraint, for example it may only work if you do 8-bit to 10-bit conversion or something like that. There are options to control that. It's trivial to fix, if someone sits and test how it works with real hardware.

**Comment by llyyr** [comment]
mpv should just remove this because it doesn't work and isn't an improvement over what's possible with mpv shaders/gpu-next tonemapping. More importantly, Windows _and_ Nvidia users are just the intersection of the worst type of support vampires, rivaled only by some Mac users.

**Comment by kasper93** [comment]
I mean, we should remove Windows support. But this is not something that needs any maintaining, it's is only extension GUID.

> what's possible with mpv shaders/gpu-next tonemapping

Inverse tone mapping is very basic in gpu-next.

**Comment by llyyr** [comment]
> this is not something that needs any maintaining

Lack of necessary hardware among people who can implement and it's current not-working state is the reason, not because the code needs to be constantly updated. 

> Inverse tone mapping is very basic in gpu-next.

RTX scaling is completely useless and inferior to even built in mpv scalers, and hopefully nobody seriously wants to do SDR->HDR conversion. We're decades away from having monitors with no SDR mode. We shouldn't provide obvious footguns to users to shoot their foot with.

**Comment by kasper93** [comment]
Also for the record, RTX Video VSR is confirmed working. Only issue is with RTX Video HDR and it's likely because of other, possibly external, preconditions that have to be made to make it work.

**Comment by Beta-Blaze** [comment]
Hi everyone,

I've been struggling to get RTX Video HDR working in mpv. Despite a lot of effort, I haven't had any success enabling the HDR feature.
Interestingly, RTX Video Super Resolution (VSR) works perfectly fine, including the status overlay showing up on the video.

Has anyone had any luck getting it to work?


Here's my mpv.conf:
```
vo=gpu
d3d11-output-csp=srgb
#d3d11-output-csp=pq
hwdec=d3d11va-copy
d3d11va-zero-copy=yes
#hwdec=nvdec
#hwdec=cuda
gpu-api=d3d11
gpu-context=d3d11
vf=d3d11vpp=nvidia-true-hdr:scaling-mode=nvidia:scale=1.5
priority=high 
d3d11-adapter=NVIDIA  
vd-lavc-dr=yes
target-peak=1000
target-colorspace-hint=yes
```

**Comment by Laesx** [comment]
> Hi everyone,
> 
> I've been struggling to get RTX Video HDR working in mpv. Despite a lot of effort, I haven't had any success enabling the HDR feature. Interestingly, RTX Video Super Resolution (VSR) works perfectly fine, including the status overlay showing up on the video.
> 
> Has anyone had any luck getting it to work?
> 
> Here's my mpv.conf:
> 
> ```
> vo=gpu
> d3d11-output-csp=srgb
> #d3d11-output-csp=pq
> hwdec=d3d11va-copy
> d3d11va-zero-copy=yes
> #hwdec=nvdec
> #hwdec=cuda
> gpu-api=d3d11
> gpu-context=d3d11
> vf=d3d11vpp=nvidia-true-hdr:scaling-mode=nvidia:scale=1.5
> priority=high 
> d3d11-adapter=NVIDIA  
> vd-lavc-dr=yes
> target-peak=1000
> target-colorspace-hint=yes
> ```

Last I tried I couldn't even get VSR to work, does it work with that config?

**Comment by Beta-Blaze** [comment]
> > Hi everyone,
> > I've been struggling to get RTX Video HDR working in mpv. Despite a lot of effort, I haven't had any success enabling the HDR feature. Interestingly, RTX Video Super Resolution (VSR) works perfectly fine, including the status overlay showing up on the video.
> > Has anyone had any luck getting it to work?
> > Here's my mpv.conf:
> > ```
> > vo=gpu
> > d3d11-output-csp=srgb
> > #d3d11-output-csp=pq
> > hwdec=d3d11va-copy
> > d3d11va-zero-copy=yes
> > #hwdec=nvdec
> > #hwdec=cuda
> > gpu-api=d3d11
> > gpu-context=d3d11
> > vf=d3d11vpp=nvidia-true-hdr:scaling-mode=nvidia:scale=1.5
> > priority=high 
> > d3d11-adapter=NVIDIA  
> > vd-lavc-dr=yes
> > target-peak=1000
> > target-colorspace-hint=yes
> > ```
> 
> Last I tried I couldn't even get VSR to work, does it work with that config?

Yes, it works with this config.

For VSR to work enough:
```
vo=gpu
gpu-api=d3d11
gpu-context=d3d11
vf=d3d11vpp=scaling-mode=nvidia:scale=1.5
```

Somewhere I've seen a script that allows you to set the scale parameter automatically.

**Comment by Laesx** [comment]
> Somewhere I've seen a script that allows you to set the scale parameter automatically.

Oh yeah, remembering I think that was the issue I was facing, too finicky to set the scale manually, I'll try and look for the script later, if you find it do let me know though!

**Comment by Beta-Blaze** [comment]
> > Somewhere I've seen a script that allows you to set the scale parameter automatically.
> 
> Oh yeah, remembering I think that was the issue I was facing, too finicky to set the scale manually, I'll try and look for the script later, if you find it do let me know though!

Especially for you)
https://gist.github.com/azumukupoe/a56a78d71cf26a8f682dc06407e615db

**Comment by Zaarrg** [comment]
@Beta-Blaze Did u ever solve the rtx hdr issue ? Having the same issue super resolution works but hdr does not or atleast does not show active (using the config u posted).

**Comment by netExtra** [comment]
Shields up!
I never got RTX HDR working, at least not properly. I've tried gpu-next inverse tone mapping and it works. But Microsoft's Auto HDR is much simpler to implement. Enable, calibrate, done. This results in a natural looking SDR->HDR conversion that works well with MPV. YMMV

**Comment by Andarwinux** [comment]
see 
https://github.com/mpv-player/mpv/pull/14901#issuecomment-2371109415
https://github.com/mpv-player/mpv/issues/11390#issuecomment-2708484791
https://github.com/hooke007/mpv_PlayKit/discussions/286#discussioncomment-14185029

It's not a config problem, RTX **_Video_** HDR never actually worked from the beginning.

**Comment by netExtra** [comment]
> see [#14901 (comment)](https://github.com/mpv-player/mpv/pull/14901#issuecomment-2371109415) [#11390 (comment)](https://github.com/mpv-player/mpv/issues/11390#issuecomment-2708484791) [hooke007/mpv_PlayKit#286 (comment)](https://github.com/hooke007/mpv_PlayKit/discussions/286#discussioncomment-14185029)
> 
> It's not a config problem, RTX **_Video_** HDR never actually worked from the beginning.

I wasn't talking about using RTX HDR in mpv. I was using other GPU tools to enable RTX HDR. So if it never worked in the first place then that would explain some of the issues I was having.
