### ISSUE TITLE
mpv segfault with 4K HDR content on Intel Pentium Silver J5005 (UHD Graphics 605) due to --hdr-compute-peak=auto

### ISSUE THREAD

**Issue by rokezu** [mpv-player/mpv#11397]
### Important Information

Provide following Information:
- mpv version 0.35.1
- Linux Distribution and Version Arch Linux (rolling release up-to-date)
- Source of the mpv binary Arch Linux packagers
- If known which version of mpv introduced the problem 
- Window Manager and version XFCE 4.18
- GPU driver and version 'Mesa Intel(R) UHD Graphics 605 (GLK 3)'  GL_VERSION='4.6 (Core Profile) Mesa 22.3.6'
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

On a Pentium Silver J5005 system, play 4K HDR content, with `--hdr-compute-peak=auto`  or `--hdr-compute-peak=yes`, mpv will crash, use `--hdr-compute-peak=no` , it will work fine. 

So, this is a quick one, I need to explicitly set `--hdr-compute-peak=no` with 4K HDR on an Intel Pentium Silver J5005 integrated GPU, or it will show a few frames (a couple of seconds or less) and crash.  If there is a disallow/block list for GPUs and hdr-compute-peak, please add this one, its shaders might not be very capable for peak computing and 4K content.

### Expected behavior

Don't crash with auto settings on non capable GPUs.

### Actual behavior

mpv crashes.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

(pending)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by thebombzen** [comment]
What command line triggers the crash exactly? Make sure it includes `--no-config`. I can't reproduce this on my Intel HD 5500 integrated GPU with `mpv --no-config --vo=gpu-next --hdr-compute-peak=yes uhd2160-hdr-sample.mkv`

Also please post a log file, which you can do by adding `--log-file=mpv-sucks.log` to your command line, and if possible please post a sample.

**Comment by rokezu** [comment]
Hi, thanks for reviewing this, as for command line options, my conf defaults to `vo=gpu` which will crash, but when using `vo=gpu-next` as in your example, it won't, but then the video becomes a slideshow presentation, setting `--hdr-compute-peak=no` makes it watchable again with `vo=gpu-next`, and won't crash with `vo=gpu`.

The cmd line of the log is:  `mpv --no-config --log-file=mpv-sucks.log uhd2160-hdr-sample.mkv`

Attached is the log of the crash that ends with `Aborted (core dumped)` in the terminal.

[mpv-sucks.log](https://github.com/mpv-player/mpv/files/10883977/mpv-sucks.log)

Can't provide the sample, it is copyrighted work.

**Comment by LaserEyess** [comment]
Somehow I wonder if this is related to #8981.

**Comment by rokezu** [comment]
> Somehow I wonder if this is related to #8981.

Oh, seems to be the same! And it goes back two years to an intel gpu driver/kernel issue all the way. So, nothing else to do on the mpv side.
