### ISSUE TITLE
Memory leak in mpv 0.32.0

### ISSUE THREAD

**Issue by gaamaaresosa** [mpv-player/mpv#11394]
### Important Information
Heavy memory leak while playing and rtmp:// link.

pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

pi@raspberrypi:~ $ mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.51.100
   libavcodec      58.91.100
   libavformat     58.45.100
   libswscale      5.7.100
   libavfilter     7.85.100
   libswresample   3.7.100
ffmpeg version: 4.3.5-0+deb11u1+rpt3

- Linux Distribution and Version
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux

- Source of the mpv binary
sudo apt install mpv -y

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Install and just play any rtmp:// url
Monitor memory in htop
1 MB every 10 seconds leak

**Comment by Dudemanguy** [comment]
Please update, the current version is 0.35.1.

**Comment by gaamaaresosa** [comment]
> Please update, the current version is 0.35.1.

I couldn't find latest binay any where.
Please help me.

I tried this but demand tons of dependencies.

wget http://www.deb-multimedia.org/pool/main/m/mpv-dmo/mpv_0.35.1-dmo1_arm64.deb
sudo dpkg -i mpv_0.35.1-dmo1_arm64.deb

**Comment by CounterPillow** [comment]
Use mpv-build.

Also it's probably not leaking memory but just caching, you can set the cache size with --demuxer-max-bytes and --demuxer-max-back-bytes

**Comment by Dudemanguy** [comment]
You can try [mpv-build](https://github.com/mpv-player/mpv-build).

**Comment by gaamaaresosa** [comment]
> Also it's probably not leaking memory but just caching

Oh! fine, let me play for few hours and test.

> Use mpv-build.

Bit new for own build, I may need build.sh file to auto build.
I build my own ffmpeg with build.sh files

**Comment by gaamaaresosa** [comment]
> You can try [mpv-build](https://github.com/mpv-player/mpv-build).

Got it, thanks

**Comment by CounterPillow** [comment]
no
