### ISSUE TITLE
How to completely disable the mouse?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#11405]
I've [disabled the overlay](https://mpv.io/manual/stable/#options-osc) and would prefer to completely prevent the mouse from interacting with mpv. Can this be done without manually "unbinding" all functions in `input.conf`?

**Comment by Dudemanguy** [comment]
`--no-input-cursor`

**Comment by v4u6h4n** [comment]
Can this be added to the manual please? As far as I can tell it's missing.

**Comment by Dudemanguy** [comment]
https://github.com/mpv-player/mpv/blob/5158a3d779ed5b6bcd41b4a0573847abc08dcb66/DOCS/man/options.rst?plain=1#L4243-L4245

**Comment by v4u6h4n** [comment]
My apologies, I'm referring to the online manual, not the man page.

**Comment by guidocella** [comment]
They are the same manual.

**Comment by v4u6h4n** [comment]
Oh I see, I was searching for `--no-input-cursor`, not `--input-cursor=<yes|no>`.

**Comment by in-plaintext** [comment]
> `--no-input-cursor`

@Dudemanguy  This setting doesn't disable the mouse wheel (seemingly go backward/forward in a playlist) — I've tested on my music folder:

    mpv --no-config --no-video --no-input-cursor ~/Music/

I prefer fully disabling the device as mpv is keyboard-driven.

----

```
mpv v0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0 (v7.349.0)
FFmpeg version: n7.1
FFmpeg library versions:
   libavcodec      61.19.100
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

**Comment by Dudemanguy** [comment]
I'm not sure how that is even possible. There is not even a default binding to go back/forth through a playlist on mouse wheel.

**Comment by in-plaintext** [comment]
> I'm not sure how that is even possible. There is not even a default binding to go back/forth through a playlist on mouse wheel.

My mouse (a wired Microsoft Basic one) is likely in some way misconfigured in Linux — I don't know if this is an mpv issue, will research further.

```
$ lsusb
Bus 003 Device 017: ID 045e:00cb Microsoft Corp. Basic Optical Mouse v2.0
```

**Comment by Dudemanguy** [comment]
You can try `mpv --no-config --no-input-cursor --idle --input-test --force-window`. There should be no mouse events.

**Comment by in-plaintext** [comment]
> You can try `mpv --no-config --no-input-cursor --idle --input-test --force-window`. There should be no mouse events.

My mouse wheel functions as the up/down key.
