### ISSUE TITLE
vo_gpu-next: the peak detection of `hdr-compute-peak` has been broken

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#11406]
### Important Information

Provide following Information:
- mpv version
 https://github.com/mpv-player/mpv/commit/291e05ec1ad1ce66f0071db848f4432633d2ee60
- Platform and Version
  Windows11 22H2

### Reproduction steps

As mentioned there https://github.com/mpv-player/mpv/issues/9800#issuecomment-1454737489, libplacebo‘s recent commit https://github.com/haasn/libplacebo/commit/daed681e04e7ccd36b1302940ec2c2001b9b67ee has broken the normal work of peak detection of `hdr-compute-peak`.

### Expected behavior

![image](https://user-images.githubusercontent.com/61936050/222903840-0f95ce82-97b0-4e53-afd1-07e05f70d571.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/61936050/222903808-16183a22-a2c4-45cf-8571-a87353782c86.png)

### Sample files

test video:  [Aquaman_test.zip](https://github.com/mpv-player/mpv/files/10888410/Aquaman_test.zip)

**Comment by dyphire** [comment]
This commit https://github.com/haasn/libplacebo/commit/fb384881060a1390621a3d177c43c3a8c03bf305 did fix the issue in the example, but I noticed in other test samples that peak detection still seems to have the issue of scene change hysteresis.
test video:  [The.Meg_test.zip](https://github.com/mpv-player/mpv/files/10889195/The.Meg_test.zip)

Actual behavior
`--vo=gpu-next --hdr-compute-peak --allow-delayed-peak-detect=no`
![1](https://user-images.githubusercontent.com/61936050/222918989-b21a21d8-4c2b-4ce7-9c40-482a2af9bdec.jpg)

Expected behavior
Reset the peak detection result by manually switching `hdr-compute-peak=no` and `hdr-compute-peak=yes` under this frame.
![2](https://user-images.githubusercontent.com/61936050/222919137-bafc7e39-30b7-4f75-98b8-a24e0cd023b6.jpg)

This seems to be the limitation of peak detection, rather than the result of a commit mentioned above.

**Comment by dyphire** [comment]
I just noticed another strange behavior of the new peak detection, which sometimes causes unnatural changes in the brightness of the scene. 
test video:  [The.Meg-test.zip](https://github.com/mpv-player/mpv/files/10891891/The.Meg-test.zip)
Abnormal behavior:

https://user-images.githubusercontent.com/61936050/222962698-312cdd01-3211-45ab-8bed-887884f8301a.mp4


It is still caused by this commit https://github.com/haasn/libplacebo/commit/daed681e04e7ccd36b1302940ec2c2001b9b67ee and has not been fixed by [libplacebo/tree/remove_peak](https://github.com/haasn/libplacebo/tree/remove_peak).

**Comment by dyphire** [comment]
> I just noticed another strange behavior of the new peak detection, which sometimes causes unnatural changes in the brightness of the scenes. 

Open a new issues for this: https://github.com/mpv-player/mpv/issues/11412

**Comment by dyphire** [comment]
@haasn The new commit https://github.com/haasn/libplacebo/commit/7d685eb2e938279f749fc05a24f996e9b1941cf0 caused the issue again.

https://github.com/haasn/libplacebo/commit/04b961261569d50c7fc1fde9093b190a8a1b569a
![1](https://user-images.githubusercontent.com/61936050/223616694-3fc0f046-c999-495f-b045-540481f99b7e.jpg)
https://github.com/haasn/libplacebo/commit/7d685eb2e938279f749fc05a24f996e9b1941cf0
![2](https://user-images.githubusercontent.com/61936050/223616717-37c0e79e-588a-4f23-b40c-9b93b01869cc.jpg)

Can you reopen this issue?

**Comment by haasn** [comment]
The fix was wrong (typo / off by 10 in the coefficient)

Fixed the fix. Hopefully it should stay closed now.

**Comment by dyphire** [comment]
> The fix was wrong (typo / off by 10 in the coefficient)
> 
> Fixed the fix. Hopefully it should stay closed now.

I can confirm that the commit https://github.com/haasn/libplacebo/commit/20c074d84634f7fed7ef1e1a92983754a1331611 did fix it.
