### ISSUE TITLE
Target-try=pq

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#11416]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I am watching hdr content on an sdr screen however when I set the target-trc=pq on films it seems to improve the colour I can’t understand this as I was told not to do this setting when watching on a sdr screen as it disables tonemapping however it seems to make the colours more brighter the only problem I have noticed is in hdr test videos with this setting on is the colour red is appearing as pink instead and I have tried setting the target prim to bt.2020 as well however that washes out the colour I was hoping someone could explain for me 

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by natural-harmonia-gropius** [comment]
a screenshot will be better than log.

**Comment by Jamie666123** [comment]
> a screenshot will be better than log.

With target-trc=pq

**Comment by Jamie666123** [comment]
![Screenshot_20230315-152926](https://user-images.githubusercontent.com/110114117/225362540-53be8b13-d506-4cf1-a7f8-6f894cbe9387.jpg)

**Comment by Jamie666123** [comment]
Without 
![Screenshot_20230315-153016](https://user-images.githubusercontent.com/110114117/225363655-db050c8b-0d73-462b-81dc-36f5179f86ea.jpg)
