### ISSUE TITLE
Generic Wayland icon used in window titlebar

### ISSUE THREAD

**Issue by deadmeu** [mpv-player/mpv#11411]
### Important Information

- mpv version: 0.35.1
- Linux Distribution and Version: Arch
- Source of the mpv binary: Flathub
- Window Manager and version: KWin Wayland (KDE Plasma v5.27.2)
- GPU driver and version: Mesa
- Possible screenshot or video of visual glitches: https://i.imgur.com/shBgKgg.png

### Reproduction steps

1. Run a KDE Plasma Wayland session
2. Install MPV from Flathub
3. Open a file using MPV and observe the icon in the top left corner of the window title bar

### Expected behavior
The icon should be a custom MPV icon.

### Actual behavior
The icon is the generic Wayland icon.

This is likely a simple fix. Some programs have been able to resolve it with a one line change:
https://github.com/hluk/CopyQ/commit/1a5b6208ff0baf4012f1452a2e46e40b078e4ff3
https://github.com/Yubico/yubioath-desktop/commit/12cd8bb9a4ea83de913321ff8fac11498b4ccbdc

**Comment by Dudemanguy** [comment]
Those commits use QT which of course mpv doesn't use. I'm pretty sure Plasma had a normal icon the last time I tried it. My guess is that this is a flatpak thing or something. In either case, we don't draw title bars and I'm pretty sure there's no wayland API for this so there's not anything we can do.
