### ISSUE TITLE
Are shaders suitable to HDR?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#11424]
Sorry if it's a dumb question, but I want to know the answer to it and if possible - an explanation.

I use [KrigBilateral.glsl](https://gist.github.com/igv/a015fc885d5c22e6891820ad89555637) which if I understood correctly - improve chroma for the video.
And I've seen examples for why to use it - that's why I use it.
But all of the examples use SDR content, which makes me wonder if shaders (especially this one which improves chroma) is suitable for HDR content?

Currently I use [FSRCNNX](https://github.com/igv/FSRCNN-TensorFlow/releases/tag/1.1), [KrigBilateral.glsl](https://gist.github.com/igv/a015fc885d5c22e6891820ad89555637) and [SSimDownscaler.glsl](https://gist.github.com/igv/36508af3ffc84410fe39761d6969be10), all of them suitable for HDR?
(Don't know if it matters but I use ```vo=gpu-next```)

**Comment by hooke007** [comment]
Scaling does nothing with hdr metadata.

**Comment by Obegg** [comment]
So [KrigBilateral.glsl](https://gist.github.com/igv/a015fc885d5c22e6891820ad89555637) is ok to use with HDR?

**Comment by hooke007** [comment]
Why not?
> Scaling does nothing with hdr metadata.

**Comment by Obegg** [comment]
Because it's chroma (which is colors, right?)
It might change the colors than originally intended if in HDR, no?

**Comment by hooke007** [comment]
I have answered twice. I don't know why you insist that HDR metadate would be affected by chroma.
