### ISSUE TITLE
Borderless window doesn't snap

### ISSUE THREAD

**Issue by musjj** [mpv-player/mpv#11427]
### Important Information

- mpv 0.35.0-306-g291e05ec
- Windows 10
- shinchiro's builds

### Reproduction steps
`mpv --log-file=mpv.log --no-config --force-window --idle --no-border`

### Expected behavior
mpv's window should be able to snap with `--no-border`

### Actual behavior
mpv's window does not snap with `--no-border`. This makes mpv impossible to tile.

I've heard that this isn't possible in Windows, but Wezterm is capable of snapping without window decorations/border.

You can try it in Wezterm using the following config:
```lua
return { window_decorations = "RESIZE" }
```

### Log file

https://0x0.st/HiPz.log

**Comment by kasper93** [comment]
`--snap-window`

**Comment by musjj** [comment]
I forgot to mention that I've tried that, but it doesn't work. The window behavior is identical regardless of that option.

**Comment by kasper93** [comment]
It works for me, snaps with the option, doesn't snap without. Don't know what is the difference for you then.

**Comment by musjj** [comment]
Are you using Windows? If so, can you tell me the mpv version you're using?

**Comment by musjj** [comment]
Thanks for helping clarify the issue, indeed that's the functionality I'm looking for. I'll edit the issue to be more specific.

**Comment by musjj** [comment]
Hmm, never mind I think I'll make a new post since the feature request template has a different format.
