### ISSUE TITLE
No audio when playing youtube videos with yt-dlp (have not tested regular youtube-dl)

### ISSUE THREAD

**Issue by obj-obj** [mpv-player/mpv#11434]
### Important Information

MPV Version: 0.35.1 (latest) from Arch Linux repos

### Reproduction steps

Play a youtube video with yt-dlp installed

### Expected behavior

Audio

### Actual behavior

No audio plays (and pressing `I` shows that no audio track is detected). Running `yt-dlp` manually on the same url downloads with audio fine, and playing the resulting file manually has working audio.

### Log file

I looked at the log file and there's nothing useful (just the normal initialization stuff, the only error is `Cannot load libcuda.so.1` but I don't have cuda installed so that's expected). I've also tried running mpv after deleting all the config files and the issue has persisted.

**Comment by christoph-heinrich** [comment]
Probably  a duplicate of https://github.com/mpv-player/mpv/issues/11392.

**Comment by obj-obj** [comment]
> Probably a duplicate of #11392.

I don't have any EDL errors in my log like they do though

**Comment by obj-obj** [comment]
Bug is fixed already, may have been the EDL issue
