### ISSUE TITLE
How to uninstall Meson manual build?

### ISSUE THREAD

**Issue by HubKing** [mpv-player/mpv#11439]
I used the commands on the front page, because I was told to use a git version to find a bug. I want to remove this git version and go back to the distribution's official package. I want to remove everything from the git's build without trace. How can I do that? 

Also, I think it would be better if you add uninstall instruction below that install example on the front page, so that people could remove the git version.

```
meson setup build
meson compile -C build
meson install -C build
```

**Comment by CounterPillow** [comment]
`ninja -C build uninstall`
