### ISSUE TITLE
Play subtitle automatically if located at the same URL / web location

### ISSUE THREAD

**Issue by dbojan** [mpv-player/mpv#11438]
### Important Information

Provide following Information:
- mpv version: mpv 0.35.0-306-g291e05ec
- Windows Version: 10
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20230305-git-291e05e.7z/download
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

play video file online:
mpv --no-config http://dbojan.royalwebhosting.net/video1.ogg

### Expected behavior
mpv should automatically display subtitles, which are located at: http://dbojan.royalwebhosting.net/video1.vtt
The same way it displays subtitles from local storage: c:\movie.avi, and c:\movie.srt

### Actual behavior
mpv does not display subtitles, unless it is pointed to the subtitles using --sub-file:
mpv --no-config http://dbojan.royalwebhosting.net/video1.ogg --sub-file=http://dbojan.royalwebhosting.net/video1.vtt

Subtitles start at 2 seconds in.
Subtitles should also be displayed if location type is ftp, httpS.
For all supported subtitle types: srt, sub, ass...

### Log file

log without sub file:
[log.txt](https://github.com/mpv-player/mpv/files/10948555/log.txt)

log with sub file:
[logwithsuboption.txt](https://github.com/mpv-player/mpv/files/10948556/logwithsuboption.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Dudemanguy** [comment]
Loading files from local storage is very, very different. It's trivial to simply read all files in a directory and check for matches. Doing this would require mpv to make many random requests to any url which doesn't sound like a good idea. If you know for some reason that subtitles are located on a particular domain, it would make more sense to make a script or maybe even an autoprofile (if possible) for this.

**Comment by dbojan** [comment]
How about turning it off by default, until switch is used?
Something like
--sub-file-url-lookup=yes
or 
--sub-file-http-lookup=yes

**Comment by CounterPillow** [comment]
You might as well just write a script for your hyper specific use case, all you have to do is set the external-files property.

**Comment by Dudemanguy** [comment]
>How about turning it off by default, until switch is used?

Even if we did this, it would still be a subpar solution to making a script because there would still be a ton of request made that are guaranteed to just fail (404). Sure maybe there are .vtt subs, but you would also have to check if there are .ass, .ssa, .srt, etc. It's also worth noting that this could only sanely work with exact matches (but it's still a bad solution of course).
