### ISSUE TITLE
Hide window title/decoration without disabling borders

### ISSUE THREAD

**Issue by musjj** [mpv-player/mpv#11432]
### Expected behavior of the wanted feature

Hide the window title/decoration without disabling borders.

### Alternative behavior of the wanted feature

We can achieve a similar behavior using `--no-border`, but this hides _both_ the window title and border. 
This is undesirable if you're using a tiling window manager on Windows, because mpv cannot snap in this state.

An example of a software that can hide its window title (without disabling borders) is Wezterm. You can try it out by using the following config:
```lua
return { window_decorations = "RESIZE" }
```

Related issue: https://github.com/mpv-player/mpv/issues/11427

### Log file

https://0x0.st/HiPz.log

**Comment by MG240** [comment]
Any updates on this?
