### ISSUE TITLE
[gpu-next] show dither-depth depth in cli output

### ISSUE THREAD

**Issue by mitzsch** [mpv-player/mpv#11433]
### Expected behavior of the wanted feature
Show the dither-depth mpv dithers to when using vo=gpu-next and dither-depth=auto, just like it is with vo=gpu. 
`mpv.com file.mkv -vo=gpu -dither-depth=auto -v` outputs =>` [vo/gpu] Dither to 8.`
the same `mpv.com file.mkv -vo=gpu-next -dither-depth=auto -v` unfortunately does not state what bitdepth it's dithering to - would be helpful to show this value. I guess this is nothing too special, maybe it can be added easily. Thanks! :)

### Alternative behavior of the wanted feature
Give the user any hint about what display dither depth has been detected and is used.

### Log file
I guess not really needed as it can be tested with every file.

**Comment by Obegg** [comment]
Is it possible to add it to [stats.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/stats.lua) too? (instead of showing only "dithering", show the number too)
@haasn

**Comment by mitzsch** [comment]
sorry for pinging you @haasn 

First of all, thanks for having added this feature!

No idea if I´m doing something wrong but somehow it always shows `[vo/gpu-next/libplacebo] Dithering to 10 bit depth` even though the display is just 8-bit and dithering is not enabled. Also, dither-depth=no is not working - the log message is still shown. The only case where the line was not present was with the dither-depth set to an unsupported value (16). 

Is this expected with vo=gpu-next to just have dithering always enabled? (and then default to 10bit as the swap chain seems to be always reconfigured to R10G10B10A2_UNORM?) Or is there something wrong with reporting?

**Comment by haasn** [comment]
Oh, no, it's bug in the message. I print it even if dithering is disabled

**Comment by haasn** [comment]
If the stats display is sufficient, maybe we can just disable the message again

**Comment by haasn** [comment]
Okay, fixed the message again

**Comment by mitzsch** [comment]
works now! Thanks! :)
