### ISSUE TITLE
Is this the expected behaviour of sub-margin-y?

### ISSUE THREAD

**Issue by SacredZenpie** [mpv-player/mpv#11443]
So I was playing with some subtitles customization in mpv.conf and I noticed that sub-margin-y does not position the subtitles the same across different aspect ratios. 

The position is correct on 16:9 aspect ratio and when the window is minimized, but when going to fullscreen on with a video in 2.20 aspect ratio, the subs are position below expected.

I fully apologize if this is something obvious, but needed to be sure.

### Log file

[log-file.txt](https://github.com/mpv-player/mpv/files/10952759/log-file.txt)

**Comment by guidocella** [comment]
Try `--sub-scale-with-window=no`

**Comment by SacredZenpie** [comment]
I've tried with both with and by window options, but no difference
