### ISSUE TITLE
icc-color-profile behaves differently than "equivalent set" of target-prim, target-trc and target-peak config option (os:win)

### ISSUE THREAD

**Issue by Nox996** [mpv-player/mpv#11449]
When experimenting with the "right" settings for HDR content to be displayed on my screen, I found out that mpv behaves differently with a supplied icc profile than with an equivalent set of the three parameters target-prim, target-trc and target-peak.

First, what do I mean by "equivalent".
I own an EIZO CS2740 monitor that I can calibrate using propriety software (ColorNavigator).
I used this software to create monitor settings and a corresponding ICC profile to comply with the "BT.2020" settings.
That is - according to ColorNavigator:
<img width="539" alt="image" src="https://user-images.githubusercontent.com/58203280/224852293-94d01549-84a5-4a5a-8f8b-a0a86b1c3fd0.png">

The corresponding icc profile is attached as well: 
[CS2740(24808080)05BT.2020.icc.zip](https://github.com/mpv-player/mpv/files/10962629/CS2740.24808080.05BT.2020.icc.zip)

As far as my (quite limited) understanding goes, I deemed these monitor settings plus ICC profile **equivalent** in mpv to these parameters (i.e. supplying the icc profile through --icc-profile=xxx should yield the same result as these parameters):
```
target-trc=gamma2.4
target-prim=bt.2020
target-peak=100
```

However, the mpv configuration that uses the icc profile yields a much darker image.
I am attaching two screenshots from mpv plus their configurations here as well:

![equivalent_settings](https://user-images.githubusercontent.com/58203280/224852710-0cedd049-a1b7-4e22-a77a-d5d69acd2732.jpg)
Settings for above screenshot:
```
vo=gpu-next
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample
tone-mapping=bt.2390
tone-mapping-param=0.5
hdr-compute-peak=no

target-trc=gamma2.4
target-prim=bt.2020
target-peak=100


cache=yes
cache-pause-wait=2
cache-pause-initial=yes
```

![icc_profile_bt2020](https://user-images.githubusercontent.com/58203280/224852714-75bfc9eb-db2d-4796-bdb8-8d152aa9297b.jpg)
Settings for above screenshot:
```
vo=gpu-next
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample
tone-mapping=bt.2390
tone-mapping-param=0.5
hdr-compute-peak=no

icc-profile=C:\Windows\System32\spool\drivers\color\CS2740(24808080)05BT.2020.icc


cache=yes
cache-pause-wait=2
cache-pause-initial=yes
```

As can be clearly seen, the first screenshot using the "equivalent" settings yields a brighter image than directly using the icc profile.
What am I understanding in the wrong way? What am I missing?

Thank you very much in advance for your help.

**Comment by kasper93** [comment]
I have a patch locally improving this situation a little. I might send it later.

But now to explain what is happening.

Without ICC profiles libplacebo assumes 1000:1 contrast and 203 nits peak brightness. You can overwrite it with `target-peak` option.
With ICC profiles libplacebo uses contrast from profiles, but forces target peak to 203 nits, because mpv uses default icc params, which forces sdr target white. And `target-peak` option is not wired to that.

So you are seeing difference 100 vs 203 target peak.

**Comment by Nox996** [comment]
Thank you for your reply and the clarification.
It would be great to see this fixed in mpv.

What would your patch improve - and why only "a little"?
