### ISSUE TITLE
Potential security risk from malicious URL

### ISSUE THREAD

**Issue by benmordecai** [mpv-player/mpv#11459]
- mpv version - mpv 0.35.1
- Linux Distribution and Version - Archlinux
- Source of the mpv binary - official 

Common use for mpv is to paste a link from a website (YouTube, Soundcloud, etc.). URLs commonly have `&` symbols for providing tracking data or other server side instructions. However, when pasted into the terminal the `&` symbol is interpreted as an instruction to bash to run the command in the background. Thus a malicious website could structure a URL like `https://www.youtube.com/watch?v=myvideo&[malicious command here]` and cause arbitrary code execution when the user expects to simply play a video and may have never even noticed that the URL has the `&` symbol in it. 

In a non-malicious case, a user can still find themselves in a situation where mpv is playing in the background and the user can't figure out that to regain controls to mpv they will need to hit ctrl-C to escape from the nonsense command after the `&` and then type `fg` to get mpv into the foreground.

**Comment by benmordecai** [comment]
I see, I was thinking there may be a way to hijack the & but you are right that this is done before mpv launches. Perhaps there is a way to document this or have a best practice or something? It seems like a big risk.

**Comment by avih** [comment]
The common practice is to quote arguments properly, and verify visually that what you paste does not esacpe these quotes.

If you're not sure whether or not the thing you paste escapes the quotes, you can do this:
1. Create an empty file and open it in a text editor, let's say it's `suspicious-paste.txt`.
2. Paste the thing into this file (ensure it starts at the begining of the 1st line), and save it.
3. run mpv like so: `mpv "$(cat suspicious-paste.txt)"`

This will ensure that whatever you pasted ends up as one argument which reaches mpv, and does not run malicious stuff at the shell.

Either way, that's between you and the shell, and outside the control of mpv.

**Comment by guidocella** [comment]
If you use zsh you can make it quote pasted urls automatically with

```zsh
autoload -U bracketed-paste-url-magic
zle -N bracketed-paste bracketed-paste-url-magic
```

**Comment by mk-pmb** [comment]
Even easier, make a script or shell alias that reads the argument from clipboard. You can even grep that to ensure it looks roughly like what you expect. e.g.

```bash
alias clmpv='mpv "$(xsel --output --clipboard | grep -m 1 -oPe "^https://\S+")"'
```
