### ISSUE TITLE
save-position-on-quit broken on git

### ISSUE THREAD

**Issue by gyvess** [mpv-player/mpv#11450]
This is a late report as I noticed this over a month ago. I just compiled version 0.35.0-319-g3eb2dfe2eb, but I first encountered this problem as early as February 5th.

Downgrading to official release version 0.35.1 and it works again. git version can read the saved position from that version, but it seems as if it's unable to write its own position with the latest commits. Saving playlist position works, but time within the video itself does not.

**Comment by zhongfly** [comment]
defalut behavior changed
https://github.com/mpv-player/mpv/commit/6471afecd0277138efdb3a80dec12dbfff75c72f
https://mpv.io/manual/master/#options-watch-later-options

**Comment by gyvess** [comment]
I missed that in the commits, sorry. Got it working again, thanks. Closing.
