### ISSUE TITLE
[gpu-next] HDR passthrough minLUM value is wrong

### ISSUE THREAD

**Issue by mitzsch** [mpv-player/mpv#11453]
### Important Information

- mpv version: mpv-x86_64-v3-20230314-git-3a2f8d4
- Windows Version: Windows 10 22H2
- Source of the mpv binary: shinchiro winbuild

I also had version mpv-x86_64-v3-20230303-git-296d40d still on my pc - this version does not show the issue - there the minLUM value is correctly forwarded.

### Reproduction steps and Actual behavior

Run `mpv.com HDR-file-with-metadata.mkv -vo=gpu-next -hwdec=auto -target-colorspace-hint=yes -v -fs` and Windows HDR enabled.

On my HDFury arcana, I checked what values are in the HDMI stream. Every value except the minLUM was correct. The minLUM value should have been `0.0050 cd/m2` but the arcana showed `0.0000 cd/m2`. With the older version (3.3.2023) the minLUM was correct again.

The file's metadata:
```
Video #1
ID                                       : 4113 (0x1011)
Menü-ID                                  : 1 (0x1)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format-Profil                            : Main 10@L5.1@High
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec-ID                                 : 36
Dauer                                    : 3 min 7s
Breite                                   : 3 840 Pixel
Höhe                                     : 2 160 Pixel
Bildseitenverhältnis                     : 16:9
Bildwiederholungsrate                    : 23,976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 1000 cd/m2
Maximum Frame-Average Light Level        : 471 cd/m2
```

### Expected behavior

The minLUM should match the value of the file, like before.

### Sample files

Use any HDR file with proper HDR metadata. In my case, I used the Dolby Core Universe HDR trailer.

**Comment by kasper93** [comment]
After this commit https://github.com/haasn/libplacebo/commit/04b961261569d50c7fc1fde9093b190a8a1b569a HDR metadata is always sanitized. 

libplacebo policy is `// PQ is always scaled down to absolute black, ignoring HDR metadata` therefore you get `min_luma` effectively to be zero.
https://github.com/haasn/libplacebo/blob/23ae2abb91ebc01e9f5aa630827c2a2c0fd556a7/src/colorspace.c#L563-L565

/CC @haasn

**Comment by mitzsch** [comment]
Hm okay, I see. Thanks! I guess there is no way, we could get the correct value passthrough back for those who want untouched metadata passthrough?

**Comment by haasn** [comment]
Hmm, this regression was definitely unintentional.

**Comment by haasn** [comment]
Seems like we need to rewrite that function to explicitly sanitize/strip static HDR10 metadata (duplicating some logic from the infer_ex).

**Comment by haasn** [comment]
https://code.videolan.org/videolan/libplacebo/-/merge_requests/422
