### ISSUE TITLE
MPV doesn't start when using Vulkan api

### ISSUE THREAD

**Issue by XZTence** [mpv-player/mpv#11451]
### Important Information

Provide following Information:
- mpv version
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230314
- Windows Version
10 pro 21H2
- Source of the mpv binary
shinichiro
- If known which version of mpv introduced the problem
 all recent versions

### Reproduction steps

I recently updated mpv to the newest build and now when I try to start mpv using the vulkan gpu api it tries to start then shuts down. this doesn't happen with other api like opengl or d3d11, ONLY with vulkan. my previous build I used which worked fine with vulkan, was from 29 August last year. tried other recent builds and all have the same problem. I prefer to use vulkan because when I play HDR videos it automatically switches windows to HDR, and switches back to sdr when I close the video. other api don't do that.

### Expected behavior
Video starts playing
### Actual behavior
mpv tries to start but closes down

###Log File
https://github.com/mpv-player/mpv/files/10967548/output.txt

**Comment by haasn** [comment]
Log doesn't show anything wrong?

**Comment by XZTence** [comment]
> Log doesn't show anything wrong?

I don't get it either, but it just starts and closes. with --no-config it does start, so I figured it's my config file so I narrowed it down to vulkan being the problem since it works fine using other api, It seems something changed in the api from the previous version I used which makes it incompatible with my config.

**Comment by llyyr** [comment]
what happens if you try to run with `mpv --no-config --gpu-api=vulkan`?

**Comment by XZTence** [comment]
> what happens if you try to run with `mpv --no-config --gpu-api=vulkan`?

Same issue. starts and closes down. tried it without adding --gpu-api=vulkan and it starts normally without any isssues.

**Comment by haasn** [comment]
Does it crash? Do you get any printout if you start mpv from the console?

**Comment by XZTence** [comment]
> Does it crash? Do you get any printout if you start mpv from the console?

No I don't think so, it just closes down. here is how it behaves https://i.imgur.com/4z2L25h.gif

**Comment by XZTence** [comment]
> What's the latest version that works? Try out some builds from [here](https://sourceforge.net/projects/mpv-player-windows/files/)

Okay I tried build ranging from August last year to this month, the most recent build that works is mpv-x86_64-20220904-git-d433c5d. any build after that doesn't work.

**Comment by llyyr** [comment]
There are only 6 commits between those two hashes, and they're all pipewire/metadata so it shouldn't be a mpv bug. There is a relevant change to mpv-winbuild-cmake during those two release though, https://github.com/shinchiro/mpv-winbuild-cmake/commit/43c93f9be1429a87ac18aff494c8d4fa565574d4

Just for curiosity, can you try `mpv --no-config --vo=gpu-next --gpu-api=vulkan`?

**Comment by XZTence** [comment]
> There are only 6 commits between those two hashes, and they're all pipewire/metadata so it shouldn't be a mpv bug. There is a relevant change to mpv-winbuild-cmake during those two release though, [shinchiro/mpv-winbuild-cmake@43c93f9](https://github.com/shinchiro/mpv-winbuild-cmake/commit/43c93f9be1429a87ac18aff494c8d4fa565574d4)
> 
> Just for curiosity, can you try `mpv --no-config --vo=gpu-next --gpu-api=vulkan`?

I actually went and asked there first but they closed it and told me to ask here. I tried it and same issue persists. afaik I always used gpu-next.

**Comment by kasper93** [comment]
> No I don't think so, it just closes down. here is how it behaves https://i.imgur.com/4z2L25h.gif

Add `-v --gpu-debug` to your command line so you can actually see at what point it closes/crashes.

**Comment by XZTence** [comment]
> -v --gpu-debug

I added those and what I got doesn't really indicate what might be causing the crash since everything was green.
[output.txt](https://github.com/mpv-player/mpv/files/10972082/output.txt)

**Comment by XZTence** [comment]
> there's nothing in those logs, you can try `--msg-level=all=trace --gpu-debug` instead

Here is the result :
[output.txt](https://github.com/mpv-player/mpv/files/10972450/output.txt)

**Comment by kasper93** [comment]
Best way would be to attach debugger and see where exactly it crashes, because it looks like it. You can check `%localappdata%\crashdumps` you should find crash dumps there, even without debug info we could at least see in what module it crashes.

**Comment by XZTence** [comment]
> Best way would be to attach debugger and see where exactly it crashes, because it looks like it. You can check `%localappdata%\crashdumps` you should find crash dumps there, even without debug info we could at least see in what module it crashes.

Thanks alot for this suggestion, after taking a look at the crashdump file I found the issue. apparently Bandicam is what it has issues with somehow, Which is weird because I wasn't running it at all, but maybe it was running in the background somehow as a dormant background process. I uninstalled bandicam and instantly it started working again. issue solved.

**Comment by MarioPL98** [comment]
I can confirm, removing Bandicam also worked for me. Any ideas why? I use it almost daily.
