### ISSUE TITLE
mpv with vo=drm on boot doesn't allow to choose display

### ISSUE THREAD

**Issue by dmanlfc** [mpv-player/mpv#11466]
### Important Information

Provide following Information:
- mpv version: 0.34.1
- Linux Distribution and Version: batocera.linux 36
- Source of the mpv binary: buildroot build.
- If known which version of mpv introduced the problem
- Window Manager and version: X11 - 21.1.7
- GPU driver and version: Nvidia 525.89.02
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. Connect two displays
2. invoke mpv player with a script at boot, we use init.d (not systemd)
3. Use the --vo=drm to play splash video (linked below)
4. Only one attached display will show the splash video playing on boot
5. Try to implement --drm-connector option to use the other display
6. On reboot - requested connector for the preferred display is always ignored.

### Expected behaviour

When choosing the --drm-connector option, mpv adheres to the request.

### Actual behaviour

mpv always defaults to the primary connected display.

### Log file

Will provide one if needed.

### Sample files

Example of template to use if mpv player is selected for splash:
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/core/batocera-splash/scripts/Ssplash-mpv.template

Player options used for above: https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/core/batocera-splash/batocera-splash.mk

Splash video used:
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/core/batocera-splash/videos/splash.mp4

**Comment by sfan5** [comment]
> mpv version: 0.34.1

unsupported, you should be using 0.35

> Log file

> Will provide one if needed.

Please do.

**Comment by dmanlfc** [comment]
Thanks @sfan5 I will try the update. I will let you know either way with log file as necessary.

**Comment by dmanlfc** [comment]
[mpv.log](https://github.com/mpv-player/mpv/files/11010954/mpv.log)

`Picked DRM card 0, primary node /dev/dri/card0 as the default.`

**Comment by sfan5** [comment]
In that log file you're using `--screen` which is not used by the DRM backend.

**Comment by dmanlfc** [comment]
Yes it was one of my feeble attempts to make it work.
--drm-connector yields the same result

**Comment by sfan5** [comment]
I can't attempt to diagnose issues with `--drm-connector` using a log file that doesn't use it.

**Comment by dmanlfc** [comment]
@sfan5 closing this one as I figured out what we were doing wrong - the naming conventions didn't match.
Thanks for the guidance, the log helped.
