### ISSUE TITLE
[Question] How to fix "colour space conversion issue, resulting in a green tint"

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#11460]
Hi,

I have movie that has a "color space conversion" problem where the whole movie has green tint because of this problem.

I would appreciate if someone could please tell me what cmd `-vf colorspace or colorprimaries` I need to change to fix the green tint?

Source
[Green Tint İssue (Sample picture from movie)](https://maglit.me/dbmoviesample47secnd)

**Comment by haasn** [comment]
Not enough info provided

**Comment by erickyun** [comment]
> Not enough info provided

What else should I provide sir?

**Comment by haasn** [comment]
log, sample file

**Comment by erickyun** [comment]
> log, sample file


[log.txt](https://github.com/mpv-player/mpv/files/10981851/log.txt)

[sample.mkv.zip](https://github.com/mpv-player/mpv/files/10981854/sample.mkv.zip)

**Comment by haasn** [comment]
In that case, you could fix it with a shader or maybe try `--vf=format:primaries=dci-p3`?

**Comment by erickyun** [comment]
> In that case, you could fix it with a shader or maybe try `--vf=format:primaries=dci-p3`?

Doesn't seem to work sir?

What shader would fix this? Could you please tell me sir?

**Comment by hooke007** [comment]
It was explained in my previous link.

**Comment by zararashigal** [comment]
Still not fixed btw
