### ISSUE TITLE
[Documentation] [Deprecation Policy] Consider being more explicit in regards to deprecations and upcoming changes

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#11475]
Hey there mpv devs,

Right now the README has this:

"Note: Building with waf is considered deprecated and will be removed in the future."

I know both waf and meson, and I am regularly fetching mpv from the git sources, using some
ruby commandline scripts. Then I compile it. It works very, very well. Much better than the older
waf-based system. So cheers on that part.

Looking at the changelog entry, this notice appears to have been added about 2 months ago.

I would like to encourage the mpv devs to consider a specific point in time stating **when**
waf support will be removed. Something like "starting at mpv 0.36.0, waf will no longer be
supported". Or something like that.

I believe that stating the policy would be useful and helpful both for downstream users
as well as distributions, e. g. what they can expect. Right now they know that waf will
eventually be removed, but not know when. I believe it may be better to decide on a
date; whether that is in 4 months, 8 months or 16 months and so forth is a secondary
question. The more important aspect is to document this, in my opinion - aka to make
these policies public and transparent.

On that note I think it would also be nice if the changelog (or a new file) would mention
upcoming deprecation changes. Obviously this may be easier with some project-wide
policy (e. g. "6 months notice of API xyz be removed, then it is removed" or so). Either
way I think it would be beneficial if this is documented somewhere. If you do not want
to explain this in the main README then perhaps on the wiki and/or some doc/ entry.

At any rate thank you for reading this.

**Comment by Dudemanguy** [comment]
We don't really have a set policy on this (for better or worse). Right now, I'm fully expecting that 0.36.0 will be the last mpv release with waf support and it will be removed shortly after that (barring some unforeseen circumstance). When exactly these things will happen is not really set in stone.
