### ISSUE TITLE
Command to re-evaluate and apply auto-profiles on demand instead of only when conditions change

### ISSUE THREAD

**Issue by NotMithical** [mpv-player/mpv#11487]
### Expected behavior of the wanted feature
It would be nice to have a console command, bindable to an input, to re-evaluate the conditions specified in configured auto-profiles and automatically apply or re-apply the appropriate profiles regardless of whether conditions have changed or if said profiles have already been applied.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/11035677/log.txt)

**Comment by NotMithical** [comment]
As a temporary solution I've added auto_profiles.lua from this repo to my scripts folder and added the following line to the end:
`mp.add_key_binding(nil, 'reload-profiles', load_profiles)`
Binding this in my input.conf gives me exactly the function I was looking for. The only issue is that the internal auto_profiles.lua script still runs, which doesn't cause problems but is redundant. Does anyone know if there is a way to disable internal lua scripts?

**Comment by guidocella** [comment]
`load-config-file /home/user/.config/mpv/mpv.conf` now does this.
