### ISSUE TITLE
Add `Alt + j` keybinding to cycle through secondary subtitles

### ISSUE THREAD

**Issue by shvchk** [mpv-player/mpv#11493]
### Expected behavior of the wanted feature
We have `j` to cycle through subtitles, would be nice to have `Alt+j` cycle through secondary subtitles

I suggest adding this to default `input.conf`:
```
Alt+j cycle secondary-sid
Alt+J cycle secondary-sid down
```

**Comment by Dudemanguy** [comment]
Secondary subtitles aren't even added by default, so I don't see why this would be added to the default keybindings. You are free to have this in your own `input.conf` of course.
