### ISSUE TITLE
Cube LUTs aren't working.

### ISSUE THREAD

**Issue by irthomasthomas** [mpv-player/mpv#11490]
I am having trouble getting a .cube LUT to work, can anyone help?

mpv --input-ipc-server=/tmp/mpv1 --keep-open --hwdec=vdpau-copy --video-unscaled=yes --script-opts=osc-timems=yes --script-opts=osc-visibility=always --image-lut='DJI-Mavic-3-D-Log-to-Rec.709-V1.cube' DJI_0792.MP4

3D LUT is from https://terra-1-g.djicdn.com/851d20f7b9f64838a34cd02351370894/mavic%203/DJI%20Mavic%203%20D-Log%20to%20Rec.709%20vivid%20V1.cube

### Log file
https://0x0.st/Hoi9.log

**Comment by hooke007** [comment]
> (Only for --vo=gpu-next)
