### ISSUE TITLE
Vulkan video output causes hangs and freezes

### ISSUE THREAD

**Issue by awused** [mpv-player/mpv#11509]
### Important Information

mpv --version:
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
built on UNKNOWN
FFmpeg library versions:
libavutil 57.28.100
libavcodec 59.37.100
libavformat 59.27.100
libswscale 6.7.100
libavfilter 8.44.100
libswresample 4.7.100
FFmpeg version: 5.1.2

This also reproduces on 0.34.1

* Fedora 37
* Installed from the Fedora official repos
* I haven't tried vulkan output since 0.28 or 0.29, can't say when it started.
* Window manager is i3 (version 4.22 (2023-01-02)), reproduces with and without a compositor
* Nvidia proprietary drivers (525.89.02-1.fc37), this is on a 4090 in case that's relevant

### Reproduction steps

`mpv --no-config --gpu-api=vulkan --gpu-context=x11vk --vulkan-queue-count=8`

Resize the window (dragging, shortcuts, toggling fullscreen) until it freezes.

Repetitive actions aren't required, the bug can trigger off of a single action, but it's not consistent.

### Expected behavior

Normal playback.

### Actual behavior

Resizing or moving the window causes mpv to hang for an extended period, also locking up other Windows. Video playback never recovers, but audio playback can recover. The window is no longer responsive and I need to kill the process.

I had `vulkan-queue-count=4` in my config and after experimentation, higher queue counts seem to lead to more frequent hangs. There are other contributing factors in my config  I haven't narrowed down as reproducing it with `--no-config` and only 4 queues as above isn't very consistent. 

With my full config seems even moving the mouse or selecting other windows can trigger the issue. I first ran into it with `vo=gpu-next` and `hwdec=nvdec-copy` which both might make it worse, as it happened with a full screen video upon selecting another window.

Playback is normal if left alone.

### Log file
[mpv-vulkan.log](https://github.com/mpv-player/mpv/files/11086048/mpv-vulkan.log)

### Sample files

Reproduces on every video I've tested.

**Comment by haasn** [comment]
Can you test if this diff works around the issue?

```diff
diff --git a/src/vulkan/swapchain.c b/src/vulkan/swapchain.c
index 3febf409..ff586173 100644
--- a/src/vulkan/swapchain.c
+++ b/src/vulkan/swapchain.c
@@ -598,6 +598,8 @@ static bool vk_sw_recreate(pl_swapchain sw, int w, int h)
              sinfo.imageExtent.width,
              sinfo.imageExtent.height);
 
+    vk_wait_idle(vk);
+
     // Calling `vkCreateSwapchainKHR` puts sinfo.oldSwapchain into a retired
     // state whether the call succeeds or not, so we always need to garbage
     // collect it afterwards - asynchronously as it may still be in use
```

**Comment by haasn** [comment]
Also, please do all testing with `--gpu-debug`

**Comment by awused** [comment]
That patch didn't seem to help.
[mpv-vulkan.log](https://github.com/mpv-player/mpv/files/11095520/mpv-vulkan.log)

**Comment by awused** [comment]
I think that patch resolves it. Resizing is quite a bit choppier but that seems like a good trade.
[mpv-vulkan.log](https://github.com/mpv-player/mpv/files/11106745/mpv-vulkan.log)
