### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by ns6000** [mpv-player/mpv#11501]
I've been using mpv on windows since the switch from mplayer / mplayer2.

Recently I've updated my very old i5 / gtx1060 / SATA ssd / W10 to brand new Ryzen 7 7700 / rtx3060 / gen4nvme / W11. Since that upgrade, I'm experiencing much slower startups (3+ secs instead of ~500ms). It doesn't matter if the video is 4k Dolby Vision HEVC / Dolby Atmos or 720p xvid / mp3 potato. It's not mpv-version dependent either, I've upgraded and after that used my old binary, which started quickly on the old machine and even that was all of a sudden slow, then I've upgraded to newer builds several times and it's still slow.

Version: mpv 0.35.0-221-ga40958cd
Windows: Windows 11 Pro 22621.1413 (with latest updates and drivers)
Binaries: https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/

There are 2 or 3 big time jumps in the attached log, not sure why though...
[mpv.log](https://github.com/mpv-player/mpv/files/11071114/mpv.log)

**Comment by Dudemanguy** [comment]
Looks like your drivers are really slow for some reason.

**Comment by Dudemanguy** [comment]
We enable shader cache by default now which should significantly speed up start time in your case since you set various scale parameters, etc. Feel free to reopen if it's still slow.
