### ISSUE TITLE
[vo/gpu-next] flickering screen with combination some options

### ISSUE THREAD

**Issue by JiLleON** [mpv-player/mpv#11519]
### Important Information

- mpv version
```
mpv 0.35.0-346-gbdf7b5c3 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Wed Mar 29 12:39:05 2023
libplacebo version: v5.264.0-88-g97d008b
FFmpeg version: N-110125-g0684e5888
FFmpeg library versions:
   libavutil       58.5.100
   libavcodec      60.7.100
   libavformat     60.4.100
   libswscale      7.2.100
   libavfilter     9.5.100
   libswresample   4.11.100
```
- Windows Version
```
Edition	Windows 11 Education
Version	22H2
Installed on	‎11/‎2/‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0
```
- Source of the mpv binary
```
https://github.com/shinchiro/mpv-winbuild-cmake/releases
```
- If known which version of mpv introduced the problem
```
mpv 0.35.0-326-ge1727553 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Fri Mar 17 12:44:59 2023
libplacebo version: v5.264.0-54-g2f629a8
FFmpeg version: N-110024-g14719b793
FFmpeg library versions:
   libavutil       58.3.100
   libavcodec      60.6.101
   libavformat     60.4.100
   libswscale      7.2.100
   libavfilter     9.4.100
   libswresample   4.11.100
```
- Possible screenshot or video of visual glitches
```
https://dropmefiles.com/S0UrG
https://anonfiles.com/W7j2Eah6z5/VID_20230329_mp4
```
### Reproduction steps
```
mpv --no-config --vo=gpu-next --video-sync=display-resample --interpolation=yes --tscale-blur=0.72 --video-latency-hacks=yes "example.mp4"
```
### Expected behavior
video is playing as usual
### Actual behavior
any video that is being played starts to flicker, except for the moment when you pause
### Own observations and notes
Ahem ahem. The problem was detected on March 24th. By rolling back the mpv versions I found out that the problem starts with the version of March 17. The version of March 16 is not subject to such problems. The problem is the combination of options ```--video-latency-hacks=yes``` and ```--tscale-blur=0.72``` (from 0.73 the screen does not flicker, but two or three frames flicker occurs when rewinding video).

My mpv case includes such a selection in config: ```--video-sync=display-resample --interpolation=yes --interpolation-preserve=no --tscale=sphinx --tscale-blur=0.6991556596428412 --tscale-radius=1.0 --tscale-clamp=0.0``` and with such values video flickers. If I remove ```--tscale-radius=1.0```, video stops flickering, but two or three frames flicker when rewinding occurs, as I wrote above.

At the moment I disabled the ```--video-latency-hacks``` option and continue to use mpv with ```--vo=gpu-next```. With ```--vo=gpu``` no such problems were noticed.

I tested with two different driver versions (at first I wasn't sure if the problem is related to mpv, because I was updating drivers that day and knowing nvidia I assumed that maybe something went wrong with nvdec) and the problem occurs with both 531.29 and 531.41.

I also do not know if other systems (not Windows) are prone to similar problems. I don't expect anyone to quickly start fixing this problem (if it really is a problem and not an individual problem with my configuration) because the documentation says that ```this option might be removed without notice once the player's timing code does not inherently need to do these things anymore```, but I thought it was worth reporting this behavior somewhere so people can stumble on this bug and understand what caused this behavior (btw I have a friend who uses my config and he complained to me about this problem after a couple days).
### Log file
```
mpv --no-config --log-file=log.txt --vo=gpu-next --video-sync=display-resample --interpolation=yes --tscale-blur=0.72 --video-latency-hacks=yes "D:\JiLleON\Desktop\Inu ni Nattara Suki na Hito ni Hirowareta 01.mkv"
```
opened the video, watched a few seconds, rewound twice, watched a few more seconds, closed (video flickers)
https://0x0.st/HodS.72.txt

```
mpv --no-config --log-file=log.txt --vo=gpu-next --video-sync=display-resample --interpolation=yes --tscale-blur=0.73 --video-latency-hacks=yes "D:\JiLleON\Desktop\Inu ni Nattara Suki na Hito ni Hirowareta 01.mkv"
```
opened the video, watched a few seconds, rewound two or three times, watched a few more seconds, closed (video does not flicker, but when rewinding two or three frames flicker)
https://0x0.st/Hodj.73.txt

```
mpv --no-config --log-file=log.txt --vo=gpu-next --video-sync=display-resample --interpolation=yes --interpolation-preserve=no --tscale=sphinx --tscale-blur=0.6991556596428412 --tscale-radius=1.0 --tscale-clamp=0.0 --video-latency-hacks=yes "D:\JiLleON\Desktop\Inu ni Nattara Suki na Hito ni Hirowareta 01.mkv"
```
opened the video, watched a few seconds, rewound twice, watched a few more seconds, closed (video flickers)
https://0x0.st/Hode.txt

```
mpv --no-config --log-file=log.txt --vo=gpu-next --video-sync=display-resample --interpolation=yes --interpolation-preserve=no --tscale=sphinx --tscale-blur=0.6991556596428412 --tscale-clamp=0.0 --video-latency-hacks=yes "D:\JiLleON\Desktop\Inu ni Nattara Suki na Hito ni Hirowareta 01.mkv"
```
opened the video, watched a few seconds, rewound two or three times, watched a few more seconds, closed (video does not flicker, but when rewinding two or three frames flicker)
https://0x0.st/Hod2.0.txt

**Comment by JiLleON** [comment]
I forgot to mention. The video with the problem was not being recorded through OBS (as if there were no screen flickers), so I had to record it on my phone. Also recorded with ```--tscale=sphinx --tscale-blur=0.6991556596428412 --tscale-radius=1.0 --video-latency-hacks=yes```, but the problem is exactly the same as with only ```--tscale-blur=0.72 --video-latency-hacks=yes``` instead.

**Comment by aqxa1** [comment]
I can reproduce this with variable frame rate videos, even with `--video-latency-hacks=off`. Using `--vo=gpu` or not using any "display-*" video-sync modes works around the problem.

Enabling `video-latency-hacks` with the settings I use seems to only cause flickering when seeking  on non-vfr videos, at least with the quick tests I did.

**Comment by Dudemanguy** [comment]
So the reason this happens is simply because ``--video-latency-hacks`` only queues one frame and then `vo_gpu_next` tries to interpolate this which naturally doesn't end well. On `vo_gpu`, it's actually no-op, the frame is not considered valid and is never interpolated. So in fact `--video-latency-hacks` silently disables interpolation which makes sense given how it works (how can the VO interpolate frames if there's only 1 frame).

>mpv --no-config --video-sync=display-resample --interpolation=yes --tscale=box --vo=gpu-next --gpu-api=vulkan --gpu-context=x11vk

This works for me on master however.
