### ISSUE TITLE
Setting target-lut on-the-fly doesn't apply the LUT properly

### ISSUE THREAD

**Issue by aqxa1** [mpv-player/mpv#11518]
### Important Information

Provide following Information:
- mpv-git 
- Gentoo AMD64
- git
- Sway
- Mesa-git

### Reproduction steps
1.  `mpv --no-config --vo=gpu-next --target-prim=bt.709 --target-trc=bt.1886 <video-file>`
2. Open console, type `set target-lut "~/.config/mpv/lut/gl850_6500k.cube"`
3. Message on osd:  `target-lut: "~/.config/mpv/lut/gl850_6500k.cube"`
4. No change in video output

On on the other hand, if I run `mpv --no-config --vo=gpu-next --target-prim=bt.709 --target-trc=bt.1886 --target-lut "~/.config/mpv/lut/gl850_6500k.cube" <video-file>` (also works within a profile so issue isn't #9782) output is correctly modified. This applies to all LUT files that I've tested to be clear. I'll add that changing on the fly is also broken when set in `input.conf` (which is my end goal)

### Expected behavior
3D LUT is changed and applied to the output

### Actual behavior
No change in visual output

### Log file
[lut_from_commandline.txt](https://github.com/mpv-player/mpv/files/11095860/lut_from_commandline.txt)
[lut_from_osd.txt](https://github.com/mpv-player/mpv/files/11095862/lut_from_osd.txt)

**Comment by Dudemanguy** [comment]
Yeah I'd expect that this option doesn't work on runtime. How practical that would be to support; not sure. A workaround might be during the video on/off again as stupid as it sounds.

**Comment by aqxa1** [comment]
Yeah, I had that same thought. What command should I use?

**Comment by aqxa1** [comment]
Okay, so that works. Can this be done programmatically? It's a bit awkward since the second toggle needs to be done while focused on the terminal (since there is no video output to respond to).

**Comment by Dudemanguy** [comment]
>It would be cool to be able to automatically switch LUT based on which monitor is used as well but I'm guessing that would get complicated.

It's doable. You could write a script that observes the `display-names` property and set the LUT accordingly when that changes.

**Comment by haasn** [comment]
> Yeah I'd expect that this option doesn't work on runtime. How practical that would be to support; not sure. A workaround might be turning the video off and on again as stupid as it sounds.

Why shouldn't it? `vo_gpu_next.c` has code to support dynamically loading LUTs. Maybe the option update doesn't propagate properly?

**Comment by aqxa1** [comment]
> It's doable. You could write a script that observes the `display-names` property and set the LUT accordingly when that changes.

Okay, I've been meaning to look into the scripting functionality anyway so good to see it's possible.
