### ISSUE TITLE
Vulnerabilities in H.264 Decoders

### ISSUE THREAD

**Issue by udit** [mpv-player/mpv#11513]
Is mpv vulnerable to this?

Research paper: https://wrv.github.io/h26forge.pdf

**Comment by haasn** [comment]
You linked a research paper describing a tool which can be used to find vulnerabilities, not a vulnerability itself.

**Comment by udit** [comment]
Looks like they are preparing the code for release: https://github.com/h26forge/h26forge. Will mpv be tested against vulnerabilities after that?

**Comment by CounterPillow** [comment]
mpv's decoders come from FFmpeg.

FFmpeg is continually automatically fuzzed for vulnerabilities as it is a prime target and relied upon by large corporations such as Google.
