### ISSUE TITLE
Arithmetic on properties? (go to ab-loop-b + 1second)

### ISSUE THREAD

**Issue by l0f4r0** [mpv-player/mpv#11523]
Hi,

Is it possible to make arithmetic on properties and use the result in a command please?

For example, I would like to go to ab-loop-b without looping to ab-loop-a, so I've tried to configure the following in my input.conf... with no avail (error "Failed to set property 'playback-time'"):
`Ctrl+b set playback-time ${ab-loop-b}+1`

Thanks in advance for your help :)

**Comment by thebombzen** [comment]
You're looking for the command `seek` not `set playback-time`

**Comment by l0f4r0** [comment]
I didn't succeed by replacing "set playback-time" with "seek" as belows:
`Ctrl+b seek ${=ab-loop-b} absolute`
Do you know why?

However, I've managed to do what I need with both:
` Ctrl+b set playback-time ${=ab-loop-b}; seek 1 exact`

Is it possible to add a condition as "if ab-loop-b exists then do 'set playback-time ${=ab-loop-b}; seek 1 exact' when Ctrl+b is pressed?
