### ISSUE TITLE
GPU-NEXT is missing with the latest build.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#11527]
### Important Information

Provide following Information:
- mpv version `0.35.0-347-g6e4a76db08`
- Linux Distribution and Version `ArchLinux`
- Source of the mpv binary 'AUR'
- If known which version of mpv introduced the problem 'The latest git version'
- Window Manager and version `Mutter 43.4-1`
- GPU driver and version `Mesa Gallium driver 23.0.1 for AMD Radeon RX 6750 XT (navi22, LLVM 15.0.7, DRM 3.49, 6.2.8-zen1-1-zen)`
- Possible screenshot or video of visual glitches

```
[laichiaheng@Julian-PC ~]$ mpv --vo=
caca            Error           image           null            tct             wlshm           
dmabuf-wayland  gpu             kitty           sdl             vaapi           x11             
drm             help            libmpv          sixel           vdpau           xv              
```
### Reproduction steps

Try to play videos with GPU-NEXT.

### Expected behavior

It works.

### Actual behavior

It doesn't work.

### Log file

[gpu-next.txt](https://github.com/mpv-player/mpv/files/11111962/gpu-next.txt)

**Comment by Dudemanguy** [comment]
The minimum libplacebo version required for gpu-next was bumped. You'll have to update/build libplacebo yourself since Arch likes having an out of date libplacebo.
