### ISSUE TITLE
--length nullifies --save-position-on-quit Is this intended?

### ISSUE THREAD

**Issue by catcake** [mpv-player/mpv#11534]
Is it intended behavior for `--length=[time]` nullify `--save-position-on-quit=yes`?

mpv version
```
mpv.com -V
mpv 0.35.0-348-g0f13c38e Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Fri Mar 31 12:34:47 2023
libplacebo version: v5.264.0-88-g97d008b
FFmpeg version: N-110127-gb75159682
FFmpeg library versions:
   libavutil       58.5.100
   libavcodec      60.7.100
   libavformat     60.4.101
   libswscale      7.2.100
   libavfilter     9.5.100
   libswresample   4.11.100
```

OS version
```
Edition Windows 11 Pro for Workstations
Version 21H2
OS build 22000.1335
Experience Windows Feature Experience Pack 1000.22000.1335.0
```

Binary source:
https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230331/mpv-x86_64-v3-20230331-git-0f13c38.7z

Reproducible command
```
mpv.com \
    --msg-level=all=trace \
    --log-file=./catcake-length-question-log.txt \
    --config=no \
    --load-scripts=no \
    --save-position-on-quit=yes \
    --watch-later-directory=./ \
    --start=5 \
    --length=1 \
    video.mp4
```

### Log file
[catcake-length-question-log.txt](https://github.com/mpv-player/mpv/files/11127821/catcake-length-question-log.txt)

**Comment by Lypheo** [comment]
> --save-position-on-quit
> Always save the current playback position on quit. When this file is played again later, the player will seek to the old playback position on start. **This does not happen if playback of a file is stopped in any other way than quitting.**

**Comment by catcake** [comment]
Thanks for clarification!
