### ISSUE TITLE
Audio handling when switching from system to airpods and back to system

### ISSUE THREAD

**Issue by TheSashmo** [mpv-player/mpv#11533]
- mpv version 0.35.1
- macOS Version 13.2.1 Apple Silicone
- installed from brew
- never noticed the problem before

### Reproduction steps
Tried using no config, same result.

Start mpv with any source.  Switch to airpods or airpods max.  System works just fine.  Take off the airpods and the player pauses, then put the airpods in its case to disconnect from the system, but mpv still stays in a paused state.

### Expected behavior
Expected should continue playing or unpause the signal.  Or in my opinion if its a live streaming URL it should not pause, but reload or pick up at last live point.  Thats just my opinion.

Supposedly there is a workaround by disabling head or ear detection, but it prevents the pausing of the video, but it still breaks when switching the audio back to the system, so not really a workaround.

### Actual behavior
Take off the airpods and the player pauses, then put the airpods in its case to disconnect from the system, but mpv still stays in a paused state.

### Log file
Log file in pastebin (https://pastebin.com/az5ygCPr)

### Sample files
You can try it with any stream or file

**Comment by TheSashmo** [comment]
Yes it does. But other players continue on their own.  Chrome as example watching youtube auto switches between sources without pausing, or the rare quick pause play as it switches.

**Comment by ruihe774** [comment]
@mlindner Is it solved by #13797?

**Comment by ruihe774** [comment]
Not reproducible in my setup anymore. @Akemi we may consider closing this issue if still no response from the OP.

**Comment by kasper93** [comment]
Feel free to reopen if this is still an issue.
