### ISSUE TITLE
8K AV1 Video Support

### ISSUE THREAD

**Issue by carycary246** [mpv-player/mpv#11532]
Wondering if mpv v0.35.1 supports 8K AV1 video playback or if there is a specific configuration needed to make this work.  When I use mpv to play 8k AV1 videos downloaded off Youtube, it is very choppy running at around 10 fps. I have no problems playing in the browser or with Windows built in media player so I should have the required codecs to decode the video. Using no config or enabling hardware decoding with gpu-next didn't make any difference at all.

Example of 8K AV1 video https://www.youtube.com/watch?v=1La4QzGeaaQ

Any clarification would be greatly appreciated. 

no conf and mpv.conf with these lines tested:
```
profile=gpu-hq
vo=gpu-next
gpu-api=d3d11
gpu-context=d3d11
hwdec=nvdec-copy
```
[output.txt](https://github.com/mpv-player/mpv/files/11118705/output.txt)

**Comment by CounterPillow** [comment]
Please don't use the question template to report issues, we can't help you without a config file.

**Comment by carycary246** [comment]
with hwdec=d3d11va output is notably smoother but is still dropping frames. Also noticed sudden brightness changes during playback as a result of this change.

**Comment by carycary246** [comment]
> framedrop=no
Thanks that appears to have fixed the dropped frames. Now lastly HDR was working with no config but to get HDR working with the config I added these lines but it appears to cause sudden brightness changes which I believe is due to target peak. When set to auto it is fine but I believe that would exceed my display peak.
```
d3d11-output-format=rgb10_a2
d3d11-output-csp=pq
tone-mapping=bt.2446a
target-colorspace-hint=yes
dither-depth=10
target-trc=pq
target-prim=bt.2020
target-peak=800 #set this according to your display's max nits
```

**Comment by vvec-converter** [comment]
it is my vvc converter 1080p 30fps = 4k AV1 
https://vvec-converter.github.io/
