### ISSUE TITLE
DD+JOC decode?

### ISSUE THREAD

**Issue by 6hzzz** [mpv-player/mpv#11531]
The world's first open-source Dolby Digital Plus Atmos decoder on the PC:
https://github.com/VoidXH/Cavern/releases/tag/1.6

**Comment by vaisest** [comment]
Is there more information on this? When searching on Google for this topic, the only thing that comes up is this issue. But there are no commits, PRs or any other information linked even though this is closed as completed?

**Comment by sfan5** [comment]
"closed as completed" is something Github made up. This is simply not supported.

I'm not even sure if it would make sense since mpv (nor ffmpeg?) doesn't have any facilities to handle object-based audio.
