### ISSUE TITLE
How to make an auto profile for [display-tags] Title?

### ISSUE THREAD

**Issue by erickyun** [mpv-player/mpv#11542]
Hi,

I have a video file where the filename is example `tvshow s02e01.mkv` but the display-tags Title: name is example `tvshow s02e01 WEB.mkv`

How can I create an auto profile for the `[display-tage] Title:`? 
I want to make an auto profile for where the name has `WEB` in it?
I would appreciate if someone could help me please?

![Inkedmpv-shot0003](https://user-images.githubusercontent.com/71968711/229493230-010f54e6-87a1-42d5-8792-a597ff23918b.jpg)

**Comment by ma-zsola** [comment]
Try this:
--profile-cond=get('media-title', ''):match('WEB')~=nil

**Comment by erickyun** [comment]
> get('media-title', ''):match('WEB')~=nil

Thank you that worked for me. 👍
