### ISSUE TITLE
Proper testing video files

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#11559]
I want to test different settings with mpv and my display, but I need video files that are specifically made for testing different things,
for example 24p judder, video and audio sync, 60fps videos, HDR color accuracy, H.274, black levels, banding, etc.
Is there any official source to download those tests from?

Also, would be helpful, since I use ```vo=gpu-next``` to be able to test whatever is needed by ```libplacebo```,
for example, I've seen this issue https://code.videolan.org/videolan/libplacebo/-/issues/265, but I don't know where to get the ```colors demo``` video file from.

**Comment by llyyr** [comment]
You can use HDR samples provided by netflix https://opencontent.netflix.com/

I don't know what colors demo is referring to though, you could ask in the libplacebo IRC

**Comment by quietvoid** [comment]
`colors demo` is a libplacebo usage example (demo) executable, not a video file.

**Comment by Obegg** [comment]
> You can use HDR samples provided by netflix https://opencontent.netflix.com/
> 
> I don't know what colors demo is referring to though, you could ask in the libplacebo IRC

Never heard of it until now and I doubt that anyone is using this as their ONLY source of testing, yes I understand you can test 4k HDR, but what about more basic testing, as I mentioned 24p judder, audio and video sync, banding, etc...
But it is a good source for HDR testing, thank you.

> `colors demo` is a libplacebo usage example (demo) executable, not a video file. https://github.com/haasn/libplacebo/blob/master/demos/colors.c

Well, I am a noob when it comes to this stuff, I have no idea how to use it, all I see it a lot of lines, and I know I'm supposed to build it somehow, but no idea how, (Windows user).

**Comment by quietvoid** [comment]
> Well, I am a noob when it comes to this stuff, I have no idea how to use it, all I see it a lot of lines, and I know I'm supposed to build it somehow, but no idea how, (Windows user).

It's not what you're looking for, anyways.
