### ISSUE TITLE
[auto_profiles] The conditional auto profiles using the property of `user-data` no longer works

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#11550]
### Important Information

Provide following Information:
- mpv version: https://github.com/mpv-player/mpv/commit/9feeb324eddd9ed73ae667e10275f663d70f7544
- Platform and Version: Windows 11
- Source of the mpv binary: https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230405

### Reproduction steps

Open any file using the following test lua script and conditional auto profile:
test lua script
```lua
mp.register_event("file-loaded", function()
    mp.set_property_native("user-data/test/a", "test")
end)
```
conditional auto profile in mpv.conf
```
[test]
profile-cond=p["user-data/test/a"] == "test"
profile-restore=copy-equal
pause
```
### Expected behavior

The conditional auto profile can work normally

### Actual behavior

Commit https://github.com/mpv-player/mpv/commit/6e4a76db0862303ae7f0f9fd7bdddff128fbd2f0 has broken the normal work of the conditional auto profile that uses property of `user-data`, and it no longer works.

### Log file

[test.log](https://github.com/mpv-player/mpv/files/11157376/test.log)

**Comment by christoph-heinrich** [comment]
If you remove the `return default` introduced by that commit, does it work again?

**Comment by dyphire** [comment]
> If you remove the `return default` introduced by that commit, does it work again?

Yes, that will work again.

**Comment by christoph-heinrich** [comment]
That must mean we're getting `err == "property not found"` while also being able to observe that property?!? wtf

**Comment by dyphire** [comment]
> That must mean we're getting `err == "property not found"` while also being able to observe that property?!? wtf

The issue is that these properties is not always invalid, which is also reflected in internal scripts: https://github.com/mpv-player/mpv/commit/894f0c28ebae55b5dbaed57b817a67e975a6da58

The commit https://github.com/mpv-player/mpv/commit/6e4a76db0862303ae7f0f9fd7bdddff128fbd2f0 clearly did not take this into account.

**Comment by Dudemanguy** [comment]
Oh right, I didn't think about that. How about just adding an exception for specifically user-data? i.e.
```
diff --git a/player/lua/auto_profiles.lua b/player/lua/auto_profiles.lua
index 55394c2e26..e84e8f0d0d 100644
--- a/player/lua/auto_profiles.lua
+++ b/player/lua/auto_profiles.lua
@@ -88,7 +88,7 @@ function get(name, default)
     if not watched_properties[name] then
         watched_properties[name] = true
         local res, err = mp.get_property_native(name)
-        if err == "property not found" then
+        if err == "property not found" and not string.match(name, "user%-data") then
             msg.error("Property '" .. name .. "' was not found.")
             return default
         end
```

I don't think any other property would be expected to act "special" like this and we still get all the benefits of that change for everything else.

**Comment by dyphire** [comment]
> Oh right, I didn't think about that. How about just adding an exception for specifically user-data? i.e.
> 
> ```
> diff --git a/player/lua/auto_profiles.lua b/player/lua/auto_profiles.lua
> index 55394c2e26..e84e8f0d0d 100644
> --- a/player/lua/auto_profiles.lua
> +++ b/player/lua/auto_profiles.lua
> @@ -88,7 +88,7 @@ function get(name, default)
>      if not watched_properties[name] then
>          watched_properties[name] = true
>          local res, err = mp.get_property_native(name)
> -        if err == "property not found" then
> +        if err == "property not found" and not string.match(name, "user%-data") then
>              msg.error("Property '" .. name .. "' was not found.")
>              return default
>          end
> ```
> 
> I don't think any other property would be expected to act special like this and we still get all the benefits of that change for everything else.

LGTM

**Comment by Dudemanguy** [comment]
Thought about it some more. `user-data` isn't the only thing this could happen to. e.g. a track could get loaded later and this would have the same issue. Perhaps we should just remove that `return default` line and downgrade the message to a warning.
