### ISSUE TITLE
Live CSTAR dailymotion is very choppy with mpv; smooth with VLC

### ISSUE THREAD

**Issue by joaopa00** [mpv-player/mpv#11554]
### Important Information

Provide following Information:
- mpv version
-mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.17.100 (runtime 57.28.100)
   libavcodec      59.18.100 (runtime 59.37.100)
   libavformat     59.16.100 (runtime 59.27.100)
   libswscale      6.4.100 (runtime 6.7.100)
   libavfilter     8.24.100 (runtime 8.44.100)
   libswresample   4.3.100 (runtime 4.7.100)
FFmpeg version: 5.1.1-1ubuntu2.1

- Linux Distribution and Version
Ubuntu Kinetic

- Source of the mpv binary
- offcial Ubntu repo
- 
- If known which version of mpv introduced the problem
- Always happened
- 
- Window Manager and version
- KDE PLASMA plasmashell 5.25.5
- GPU driver and version
-    Device: AMD Radeon Vega 8 Graphics (raven, LLVM 15.0.2, DRM 3.47, 5.19.0-38-generic) (0x15d8)
    Version: 22.2.5

### Reproduction steps

Be careful the site is geoblocked

Go to the site https://www.dailymotion.com/video/x5gv5v0 with firefox
open inpstecor/network. And copy the url looking like https://stream-04.sv4.dailymotion.com/sec(3uHXKsK7_-J9YIYIiNPgOATzv7tm50ViU2YsR28h_U3ObFO0LrbFbHq4PD9Yuq25)/p/dm/3/x5gv5v0/d/live-2.m3u

### Expected behavior
smooth streaming

### Actual behavior
Caching every about less 10 seconds. With VLC, streaming is very smooth.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/11163406/output.txt)

**Comment by Dudemanguy** [comment]
Can't reproduce on mpv master with the link in that file.

**Comment by joaopa00** [comment]
reproduce the caching or playing the video?

**Comment by Dudemanguy** [comment]
It plays fine with no apparent problems.

**Comment by joaopa00** [comment]
Big bandwidth?

**Comment by Dudemanguy** [comment]
Yes, I have plenty of bandwidth. But like you said 6Mb/s should be enough for this and if it really was a bandwidth issue, you should have problems with vlc too.

**Comment by joaopa00** [comment]
Any idea to start the debugging, where can be located the problem?

**Comment by Dudemanguy** [comment]
What happens if you use `ffplay` instead of `mpv` on a link?

**Comment by joaopa00** [comment]
same problem

**Comment by Dudemanguy** [comment]
Must be an upstream issue in that case. I'd suggest trying to update mpv and ffmpeg if possible since your versions are quite old. Dunno if anyone knows any clever workarounds.

**Comment by joaopa00** [comment]
need to report to ffmpeg team?

**Comment by Doofussy2** [comment]
Maybe update mpv from 34.1 to 35

**Comment by Dudemanguy** [comment]
>need to report to ffmpeg team?

At least update ffmpeg before doing that.

**Comment by joaopa00** [comment]
no dice with
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer
[cplayer]  built on Fri Mar 10 04:45:53 2023
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       58.2.100
[cplayer]    libavcodec      60.3.100
[cplayer]    libavformat     60.3.100
[cplayer]    libswscale      7.1.100
[cplayer]    libavfilter     9.3.100
[cplayer]    libswresample   4.10.100
[cplayer] FFmpeg version: 6.0

**Comment by joaopa00** [comment]
Why close this bug since it still happens

**Comment by Traneptora** [comment]
Post a log from git master

**Comment by joaopa00** [comment]
Where are  the nighty builds for linux to test the git master?

**Comment by Traneptora** [comment]
It's clearly an upstream problem, test with upstream ffmpeg's nightly builds: https://ffmpeg.org/download.html
