### ISSUE TITLE
vo_gpu_next: impossible to save tone-mapped PNG screenshots

### ISSUE THREAD

**Issue by quietvoid** [mpv-player/mpv#11563]
### Important Information

Provide following Information:
- mpv version: 
```
mpv 0.35.0-357-g1808f264b3 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Mon Apr 10 01:34:50 2023
libplacebo version: v5.264.0-114-gba8a047f
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```

- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: mpv-git PKGBUILD
- Window Manager and version: Sway 1.8.1, wlroots 0.16.2
- GPU driver and version: amdgpu, Linux 6.1.23, AMD Radeon RX 6900 XT (navi21, LLVM 15.0.7, DRM 3.49)
- libplacebo version: libplacebo v5.264.0-114-gba8a047f

### Reproduction steps

- Play HDR clip with `--screenshot-format=png --target-prim=bt.709 --target-trc=bt.1886 --screenshot-tag-colorspace=no`
- Press `s` to save a screenshot

### Expected behavior

The screenshot should be tone-mapped, or at least there should be a setting to control the output colorspace for the screenshots.

### Actual behavior

The screenshot is always BT.2020 and ST 2084, regardless of `screenshot-tag-colorspace` or `screenshot-sw`.
It only seems to affect `--screenshot-format=png` (or at least I only also tested `jpg`, which works fine).

I've bisected the change of behaviour to https://github.com/mpv-player/mpv/commit/16ef237da56afc6b38528c74d006a068e9efc5e3

### Log file

PNG: [mpv.log](https://github.com/mpv-player/mpv/files/11190798/mpv.log)
JPG: [mpv-jpg.log](https://github.com/mpv-player/mpv/files/11190799/mpv-jpg.log)

### Sample files

https://0x0.st/HXxE.mkv

**Comment by quietvoid** [comment]
Fixed by https://github.com/mpv-player/mpv/commit/cbbe2e52210d9885a0897e9c7833267a60456c56, workaround being to continue using `--screenshot-tag-colorspace=no` to have sRGB screenshots that are tone-mapped.

**Comment by quietvoid** [comment]
> Still doesn't work on my end. Works with other formats but not png.

No? What command line are you using?
I just tested on the latest commit and it works fine with the sample in the issue.

> ./build/mpv --no-config --vo=gpu-next --screenshot-format=png --screenshot-tag-colorspace=no HXxE.mkv

The output screenshot is tone-mapped.

**Comment by Maikurosofuto** [comment]
> > Still doesn't work on my end. Works with other formats but not png.
> 
> No? What command line are you using? I just tested on the latest commit and it works fine with the sample in the issue.
> 
> > ./build/mpv --no-config --vo=gpu-next --screenshot-format=png --screenshot-tag-colorspace=no HXxE.mkv
> 
> The output screenshot is tone-mapped.

My mpv.conf is quite extensive but regarding the screenshots:
`screenshot-format=png
screenshot-tag-colorspace=no
screenshot-high-bit-depth=yes
screenshot-png-compression=1                  
screenshot-template="C:\Users\me\Pictures\MPV Screenshots\%F [T%wHh-%wMm-%wSs]"`

And using your command line wielded the same result, a washed out, not tone mapped, screenshot.
I'm using shinchiro's build in sourceforge if that matters.

**Comment by quietvoid** [comment]
The latest sourceforge build seems to be from 2023-04-09, which doesn't have https://github.com/mpv-player/mpv/commit/cbbe2e52210d9885a0897e9c7833267a60456c56.

The release here should have it: https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230411
