### ISSUE TITLE
Command+tab to fullscreen mpv won't hide cursor

### ISSUE THREAD

**Issue by Limero** [mpv-player/mpv#11562]
### Important Information

- mpv version: 0.35.1
- macOS Version: 13.3
- Source of the mpv binary or bundle: Homebrew

### Reproduction steps

Play video with mpv in fullscreen, press command+tab to switch to a different program and then command+tab to switch back to mpv.

### Expected behavior

Cursor should disappear, like it does when mpv is in a window instead of fullscreen

### Actual behavior

Cursor stays on screen until cursor is moved, then it will correctly disappear

### Log file

https://0x0.st/HXvM.txt

### Sample files

Any file

**Comment by Akemi** [comment]
i can't reproduce this on the newest macOS and current master. might have been a problem with that specific macOS or SDK version.

if the issue still persists please open a new issue.
