### ISSUE TITLE
GPU-next not working 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#11573]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there my I have a question about the use of gpu-next as every time I try to use it on my device and I try to open a video using it it goes to open the video but then crashes the device i am using is an android tablet the Lenovo tab p11 plus to be exact was wondering if someone could help me?

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by CounterPillow** [comment]
1. Android issues don't go into this repository, there's an mpv-android repository.
2. You used a question template to report an issue. Don't do that, you provided no information useful to possibly debug this
