### ISSUE TITLE
Option `hidpi-window-scale` on Wayland misbehaving in very specific circumstances

### ISSUE THREAD

**Issue by iczero** [mpv-player/mpv#11571]
### Important Information

Provide following Information:
- mpv version: `0.35.0-359-gcbbe2e5221` (cbbe2e52210d9885a0897e9c7833267a60456c56)
- Linux Distribution and Version: Fedora 37, Linux kernel 6.3.0-rc6+ (drm-tip)
- Source of the mpv binary: built from master (see above)
- If known which version of mpv introduced the problem: most likely the one introducing fractional scaling support on Wayland
- Window Manager and version: kwin_wayland 5.27.4
- GPU driver and version: Mesa 22.3.7, iris/i915
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

1. Configure display with a fractional scale factor (in my case, `125%`)
1. Start mpv on a video smaller than the display with `--no-config --hidpi-window-scale=yes` (default)
1. Bring up stats and notice the current window scale is not 1 or the actual display scale factor (1.25), but rather something odd like 1.067
1. Start mpv on the same video but with `--no-config --autofit-larger='100%' --hidpi-window-scale=yes`
1. Bring up stats and notice the current window scale now matches the actual display scale factor

My display has a resolution of 2560x1600 and I run it with a scale factor of 125%. A video with the resolution 1920x1080 ended up at scale 1.067. A video with the resolution 1787x1185 ended up at scale 1.147.

This is probably a massive nitpick but I have issues and this has been annoying me for the past week. I have worked around the issue simply by setting `--hidpi-window-scale=no --autofit-larger=100%`.

### Expected behavior

mpv starts with the correct scale factor.

### Actual behavior

mpv starts with the wrong scale factor, unless `autofit-larger` or some other options are set.

### Log file

Relevant log lines (please ping if full log is necessary)

Without `autofit-larger`:
```
[vo/gpu] Probing for best GPU context.
[vo/gpu/opengl] Initializing GPU context 'wayland'
[vo/gpu/wayland] Registered for protocol wl_compositor
[vo/gpu/wayland] Registered for protocol xdg_wm_base
[vo/gpu/wayland] Registered for protocol zxdg_decoration_manager_v1
[vo/gpu/wayland] Registered for protocol wp_viewporter
[vo/gpu/wayland] Registered for protocol wp_fractional_scale_manager_v1
[vo/gpu/wayland] Registered for protocol wl_shm
[vo/gpu/wayland] Registered for protocol wl_seat
[vo/gpu/wayland] Registered for protocol wl_data_device_manager
[vo/gpu/wayland] Registered for protocol zwp_idle_inhibit_manager_v1
[vo/gpu/wayland] Registered for protocol wl_subcompositor
[vo/gpu/wayland] Registered for protocol wp_content_type_manager_v1
[vo/gpu/wayland] Registered for protocol zwp_linux_dmabuf_v1
[vo/gpu/wayland] Registered for protocol wl_output
[vo/gpu/wayland] Compositor doesn't support the wp_single_pixel_buffer_manager_v1 protocol!
[vo/gpu/wayland] Compositor doesn't support the wp_presentation protocol!
[vo/gpu/wayland] Registered output California Institute of Technology eDP-1-unknown (0x2f):
[vo/gpu/wayland]        x: 0px, y: 0px
[vo/gpu/wayland]        w: 2560px (340mm), h: 1600px (220mm)
[vo/gpu/wayland]        scale: 2
[vo/gpu/wayland]        Hz: 119.998000
[vo/gpu/wayland] Obtained preferred scale, 1.250000, from the compositor.
[vo/gpu/wayland] Enabling server decorations

[...]

[vo/gpu] reconfig to 1920x1080 yuv420p10 bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vo/gpu/wayland] Reconfiguring!
[vo/gpu] max content size: 2560x1600
[vo/gpu] monitor size: 2560x1600
[vo/gpu] Resize: 2400x1350
[vo/gpu] Window size: 2400x1350 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 2400x1350
[vo/gpu] Video scale: 1.250000/1.250000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Texture for plane 0: 1920x1080
[vo/gpu] Texture for plane 1: 960x540
[vo/gpu] Texture for plane 2: 960x540
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Resizing texture: 16x16
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu/wayland] Handling resize on the egl side
[vo/gpu] Resize: 2048x1207
[vo/gpu] Window size: 2048x1207 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 27) 2048x1152
[vo/gpu] Video scale: 1.066667/1.066667
[vo/gpu] OSD borders: l=0 t=27 r=0 b=28
[vo/gpu] Video borders: l=0 t=27 r=0 b=28
[vo/gpu] Reported display depth: 10
```

When `autofit-larger` is specified:
```
vo/gpu] reconfig to 1920x1080 yuv420p10 bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vo/gpu/wayland] Reconfiguring!
[vo/gpu] max content size: 2560x1600
[vo/gpu] monitor size: 2560x1600
[vo/gpu] Resize: 2400x1350
[vo/gpu] Window size: 2400x1350 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 2400x1350
[vo/gpu] Video scale: 1.250000/1.250000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Texture for plane 0: 1920x1080
[vo/gpu] Texture for plane 1: 960x540
[vo/gpu] Texture for plane 2: 960x540
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Resizing texture: 16x16
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu/wayland] Handling resize on the egl side
[vo/gpu] Resize: 2400x1350
[vo/gpu] Window size: 2400x1350 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 2400x1350
[vo/gpu] Video scale: 1.250000/1.250000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 10
```

**Comment by iczero** [comment]
This is not an issue. The same behavior can be reproduced simply by setting `autofit-larger=80%`. It seems `autofit-larger` apparently defaults to `80%`, but doesn't show up in `--list-options`.

**Comment by Dudemanguy** [comment]
>It seems autofit-larger apparently defaults to 80%

No it definitely does not. What happens if you use `--wayland-configure-bounds=no`?

**Comment by iczero** [comment]
The max window width when wayland-configure-bounds=yes appears to be 2048, which matches the Wayland logical resolution of my display (kwin reports it as 2048x1280).

**Comment by Dudemanguy** [comment]
kwin is apparently very aggressive when setting window bounds. Maybe the auto flag should be adjusted some more because I too would find this extremely unintuitive. I thought the point was just keep the window from being bigger than the monitor resolution.

**Comment by iczero** [comment]
@Dudemanguy I did some testing, kwin_wayland apparently sets `[vo/gpu/wayland] configure_bounds width 2048 height 1207`, which is correct when interpreted as Wayland logical coordinates. When setting the display scale factor to 200% instead, mpv limits itself to only 50% of the screen width. I think the issue may be that mpv is interpreting scaled coordinates from the compositor as physical coordinates.

**Comment by Dudemanguy** [comment]
>I think the issue may be that mpv is interpreting scaled coordinates from the compositor as physical coordinates.

Ah yes, that would explain it indeed. Do you want to open a PR for that patch?
