### ISSUE TITLE
video-aspect always reports video as aspect ratio 1.9999 in profile-cond

### ISSUE THREAD

**Issue by BombchuLink** [mpv-player/mpv#11576]
### Important Information

Provide following Information:
- mpv version
2023/04/09
- Windows Version
Win 10 (latest update)
- Source of the mpv binary
Sourceforge powershell script updater

### Reproduction steps
in mpv.conf add your conditional auto profile
```
[aspect ratio screen set]
profile-desc="Set to other monitor in fullscreen if aspect ratio is 1.333 or less"
profile-cond = video-aspect <= 1.33
fs-screen=1
```
Then run a 4:3 aspect video

### Expected behavior
getting the video aspect ratio to run the profile parameters.

### Actual behavior
all videos are being detected as having an aspect of less than 2 and greater than 1.9999, even though pressing the i key shows the videos actual aspect ratio while loaded.

**Comment by guidocella** [comment]
https://mpv.io/manual/master/#conditional-auto-profiles

You need to use `profile-cond=video_aspect ...`

**Comment by BombchuLink** [comment]
Ah I see, you need to use _ instead of -, sorry I didn't catch that on my own.

It works properly now, and my issue is resolved.
