### ISSUE TITLE
gpu-next/vulkan causes corrupted tone-mapping in fullscreen

### ISSUE THREAD

**Issue by nyanmisaka** [mpv-player/mpv#11578]
### Important Information

Provide following Information:
- mpv version - **0.35.1-4**
- Linux Distribution and Version - **Manjaro, Linux 6.2.10**
- Source of the mpv binary - **Arch/Manjaro repo**
- Window Manager and version - **Gnome 43.4**
- GPU driver and version - **Intel Arc A380, Mesa 22.3/23.0/23.1-git, iHD 23.x**

Also built mpv and libplacebo from sources but the issue remains.

### Reproduction steps
```
hwdec=vaapi
vo=gpu-next
gpu-api=vulkan
```

The vulkan `gpu-api` in gpu-next renderer causes **corrupted tone-mapping** output in **fullscreen** mode. Setting the `gpu-api` to opengl fixes the issue.

### Expected behavior

![Screenshot from 2023-04-13 22-52-23](https://user-images.githubusercontent.com/14953024/231798901-91bf1aae-c58b-48dc-8c06-141d4f1223f5.png)

### Actual behavior

![Screenshot from 2023-04-13 22-42-11](https://user-images.githubusercontent.com/14953024/231797930-1eaf673d-0eb4-4055-bf53-50062cd0fb47.png)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/11223482/output.txt)

### Sample files

Any HDR video clip that needs tone-mapping.

**Comment by nyanmisaka** [comment]
> Im getting this issue with any video at all running the latest mesa on wayland, I think it's actually related to https://gitlab.freedesktop.org/mesa/mesa/-/issues/7536 since norbc fixes it

Thanks for the reminder that this is actually a Mesa ANV issue. 

`INTEL_DEBUG=norbc` fixes the issue perfectly.

**Comment by kasper93** [comment]
Is this still an issue? Looks like fixed upstream.

**Comment by nyanmisaka** [comment]
> Is this still an issue? Looks like fixed upstream.

I don't currently have access to test again. So I'm closing this temporarily.
