### ISSUE TITLE
using gpu-next causes frame drops while the info menu/overlay is shown

### ISSUE THREAD

**Issue by mdannp** [mpv-player/mpv#11579]
### Important Information

using gpu-next causes frame drops while info (Shift+I) is shown.
This bug was introduced somewhere between 
mpv 0.35.0-266-ga194ddaa (doesnt have the issue)
and
mpv 0.35.0-326-ge1727553 (has the issue)
frame drops and stottering appears only while the info menu is shown and stops when the info menu is closed again.

Provide following Information:
- mpv version: mpv 0.35.0-363-gc50f536b
- Windows Version: windows 10
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild/releases
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
mpv <videofile> --no-config --vo=gpu-next

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
no frame drops while info menu is open

### Actual behavior
frames are being dropped and picture stutters while info menu/overlay is visible

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by mitzsch** [comment]
I also have seen this behavior. I could track this down to this commit => https://github.com/mpv-player/mpv/commit/296d40dc6f38401085d005bb4627f8afff46b041. With it reverted everything is "fine" again - no dropped frames while having the info screen open.

**Comment by Dudemanguy** [comment]
Well that's bizarre. That commit is not gpu-next specific at all. It also shouldn't affect anything other than pause.

**Comment by mitzsch** [comment]
I also have no idea why it leads to frame drops, I also only noticed them when having the TV at the same framerate as the file. (in my case 4K@23p - sometimes I noticed every time the info stats were updated a frame would be dropped) In normal desktop mode, I was not able to reproduce the frame dropping.

**Comment by Dudemanguy** [comment]
To be clear, does this only happen with gpu-next? I guess only on windows? I can't reproduce it here (fps matching the monitor as well).

**Comment by mitzsch** [comment]
To be honest, I haven't tested any other vo, just gpu-next, and only on Windows 10 (nvidia rtx 3050). In my testing, it was used in conjunction with target-colorspace-hint=yes and HDR turned on. Next time when I have some time I can try it without target-colorspace-hint=yes and with vo=gpu.

**Comment by cyr123** [comment]
Just FYI, this *may* be the same thing I've noticed recently on my HTPC setup (since switching to mpv-git). With the info screen open the frame drop counter increments about once or twice per second. This is using gpu-next on arch linux. Also running with fps = refresh rate.
