### ISSUE TITLE
Hesitation and back and forth progress shown in progress bar after seeking.  Logs show 'invalid video timestamp'.

### ISSUE THREAD

**Issue by smootharc** [mpv-player/mpv#11577]
- mpv version:

Name         : mpv
Version      : 0.35.1
Release      : 2.fc37
Architecture : x86_64
Size         : 4.5 M
Source       : mpv-0.35.1-2.fc37.src.rpm
Repository   : @System
From repo    : updates

- Linux Distribution and Version:

 Kernel: 6.2.9-200.fc37.x86_64 arch: x86_64 bits: 64 compiler: gcc v: 2.38-25.fc37
 Desktop: Cinnamon v: 5.6.8 tk: GTK v: 3.24.37 wm: muffin dm: LightDM Distro: Fedora release 37
 (Thirty Seven)

- If known which version of mpv introduced the problem:

Unknown.  This a fresh install of Fedora. I have never used Fedora before.  All the video files I have tried exhibit the same behavior on Fedora but don't on Manjaro. Manjaro uses pulseaudio.  Fedora uses pipewire.  Which may not matter because the error messages seem to be video related.

- GPU driver and version

01:05.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] RS780L [Radeon 3000]
	Subsystem: ASUSTeK Computer Inc. Device 8388
	Kernel driver in use: radeon
	Kernel modules: radeon, amdgpu

### Reproduction steps

mpv -v -v --no-config --log-file=mpv.log Videos/Mmda_s01e01_720p-splits.mkv

Press right arrow four times.

### Expected behavior

Seek forward without hesitation.

### Actual behavior

Seeks forward but hesitates and the progress bar bounces back and forth then resumes playing

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/11222010/mpv.log)

**Comment by Dudemanguy** [comment]
Do you have a sample file that shows this problem?

**Comment by Dudemanguy** [comment]
No followup and unclear issue so close.
