### ISSUE TITLE
Target-peak

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#11588]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I am using mpv to tonemap hdr films as my device dosent support hdr my device I am using is sdr screen and is capable of 400 nits maximum brightness I was wondering what I should be setting the target peak to whether I should set it to 400 the maximum or a lower target peak as when I set it too 400 it gives me a darker image however lower target peaks makes it brighter what am I better doing thanks 

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by Jamie666123** [comment]
My config is this
Vo=gpu-next
tonemapping=bt.2446a
Tonemapping mode =luma 
Target-peak=400

**Comment by haasn** [comment]
You could try a different tone-mapping mode, e.g. `bt2390` which is designed for HDR->HDR tone-mapping.

**Comment by lextra2** [comment]
HDR is more about contrast then about nits.
Don't fall for marketing scams.
