### ISSUE TITLE
Is it possible to delay a specific audio channel in mpv?

### ISSUE THREAD

**Issue by RfadnjdExt** [mpv-player/mpv#11586]
I am currently using mpv as my video player and I was wondering if there is a way to delay a specific audio channel in the audio stream. Specifically, I want to delay the surround channel by a certain amount.

I have tried using the --audio-delay option, but this seems to apply the delay to the entire audio stream. I also looked into using the af (audio filter) option with the pan filter, but I am not sure how to apply the delay to only the surround channel.

Is there a way to delay a specific audio channel in mpv? If so, how can I achieve this? Any help or guidance would be greatly appreciated. Thank you!

**Comment by kevinlekiller** [comment]
Looks like it could be done with [adelay](https://ffmpeg.org/ffmpeg-filters.html#adelay)

    $ mpv --af=help | grep adelay
      adelay           Delay one or more audio channels.

If you use a auto-profile for a specific number of channels, then use `af-add=adelay=...`.

For example, delay third channel by 500ms on 8 channel audio:

        [8channelDelayThirdChannel]
        profile-desc=Delay third channel by 500ms on 8 channel audio
        profile-cond=not get("core-idle", default_value) and get("audio-params/channel-count", default_value) == 8
        profile-restore=copy
        af-add=adelay=0|0|500|0|0|0|0|0

**Comment by RfadnjdExt** [comment]
Can I use negative value for the delay?

**Comment by kevinlekiller** [comment]
Set every other channel to a positive value?
