### ISSUE TITLE
Youtube auto-generated subtitles behavior

### ISSUE THREAD

**Issue by tXJtqlb3bbeKD1yW8SV7** [mpv-player/mpv#11584]
While looking for a way to display the auto-generated subtitles when watching a video directly from Youtube, I found this piece of code that I've pasted into my mpv.conf : `ytdl-raw-options=ignore-config=,sub-langs=en,write-auto-subs=`. The subtitles load just fine, but, as you can see in the gif below, they are positioned at the top and not the bottom and, on top of that, are only visible when I hover the mouse over that area. Is there any way that I can make the subtitles behave just like normal ones, staying at the bottom and always visible?

![mpv_vlJovCibXc](https://user-images.githubusercontent.com/88219689/232261487-db7efec8-8903-4297-841b-010eaefc4209.gif)

**Comment by harrisonmg** [comment]
The top subs that only appear on hover are called secondary subs by mpv.

You can select or deselect the secondary sub track via ID with this setting: https://mpv.io/manual/master/#options-secondary-sid

There's a similar setting for the primary sub track, `--sid`. Maybe this helps.

**Comment by Dudemanguy** [comment]
Those are secondary subs as mentioned. They are positioned at the top and you can't really change it. There's an old feature request here: #7622 so closing.
