### ISSUE TITLE
Switchable subtitle colour/font presets via hotkey

### ISSUE THREAD

**Issue by brad86m** [mpv-player/mpv#11587]
For general content, I mostly use white subtitles, but I also watch a lot of older martial arts movies with a yellow subtitle style that I find more suited to that 80s burnt-in VHS look. I change the current settings, but having to do that every time isn't really ideal. Would it be possible to create two presets for sub that can be toggled between via a hotkey ?

**Comment by christoph-heinrich** [comment]
You can have multiple presets and cycle between them using [cycle-values](https://mpv.io/manual/master/#command-interface-cycle-values).

**Comment by brad86m** [comment]
Thank you. Preset as in another altered for subs main config file ?

**Comment by christoph-heinrich** [comment]
I assume you change the color with `sub-color`?
Define a keybinding in your `input.conf` with e.g.
```
x cycle-values sub-color #FFFFFFFF #FFFF0000 #FF00FF00 #FF0000FF
```

**Comment by hooke007** [comment]
Use quotes or it would be parsed as comments
```
F10 cycle-values sub-color "#FFFFFFFF" "#FFFF0000" "#FF00FF00" "#FF0000FF"
```

**Comment by brad86m** [comment]
Absolutely perfect. Thanks guys. So easy to change on the fly, now.
