### ISSUE TITLE
gpu-next: new gamut mapping is too strong

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [mpv-player/mpv#11599]
Note the red ground and blue pillars.

perceptual
![image](https://user-images.githubusercontent.com/50797982/232788430-8861e430-b175-4c95-8110-685642c3d300.png)
![image](https://user-images.githubusercontent.com/50797982/232788307-a3ca67c7-523a-4ec1-b0d1-8fc702437a7b.png)
clip
![image](https://user-images.githubusercontent.com/50797982/232788604-1e671abc-3300-411e-9b7b-d44028362ce8.png)
![image](https://user-images.githubusercontent.com/50797982/232788679-ba583dfa-c114-469d-82be-7caf8299f80f.png)

**Comment by CharlesMengCA** [comment]
Noticed the similar issue. Problem introduced between 20230413 and 20230414
Screenshot taken from shinchiro windows build of above dates.

Sony-Whale-in-Tonga-HDR-UHD.mp4

![mpv-shot0001_0413](https://user-images.githubusercontent.com/58993776/232846158-5268348d-9bef-47eb-a3ff-b084857a0230.jpg)
![mpv-shot0001_0414](https://user-images.githubusercontent.com/58993776/232846163-cf58b357-5813-407c-aa32-72cc6f440f8e.jpg)

**Comment by haasn** [comment]
I plan to add a hue shifting feature to the perceptual mapping function to regain saturation in such extreme scenarios. But that aside, I think the clipped version of these screenshots looks terrible in comparison. YMMV, but what you are seeing is largely the *absence* of severe hue distortion artefacts, which were the exact reason the colorimetric mapping code was introduced..

**Comment by haasn** [comment]
Can you test https://code.videolan.org/videolan/libplacebo/-/merge_requests/441 ?

**Comment by CharlesMengCA** [comment]
Screenshot from your new code
![mpv-shot0001](https://user-images.githubusercontent.com/58993776/233503057-752e8378-ad3a-46e0-8645-f21c77432172.jpg)

**Comment by dyphire** [comment]
> perceptual_hue_shift 
 ![image](https://user-images.githubusercontent.com/50797982/233577938-fbcfa392-ded3-4197-aef8-35de07e1224d.png)

The red ground still looks terrible.

**Comment by haasn** [comment]
@natural-harmonia-gropius can you test https://code.videolan.org/videolan/libplacebo/-/merge_requests/466

Should be significantly more correct

**Comment by dyphire** [comment]
> @natural-harmonia-gropius can you test https://code.videolan.org/videolan/libplacebo/-/merge_requests/466
> 
> Should be significantly more correct

perceptual_hue_shift_v2: https://github.com/dyphire/mpv-winbuild/actions/runs/5081231063
![image](https://github.com/mpv-player/mpv/assets/61936050/55a2b0da-4410-4581-94dd-3f07bf04fd15)
The improvement seems not significant

**Comment by natural-harmonia-gropius** [comment]
Blue looks better. But same as dyphire, red needs improvement.
![image](https://github.com/mpv-player/mpv/assets/50797982/142bc64a-0be1-4093-bfd0-58fd8a79f560)
https://www.youtube.com/watch?v=gkXQlZENK0o
![image](https://github.com/mpv-player/mpv/assets/50797982/7ca3118c-4af9-46d9-b927-3bfe88e19d89)

**Comment by haasn** [comment]
Still seems to be better than the status quo and doesn't regress as much as v1 did. More importantly, it's also numerically stable and does the correct thing overall.

We can continue tweaking it but for now I'm content to merge this branch.

**Comment by CharlesMengCA** [comment]
For the new version, I got this message, could you take a look?

[vo/gpu-next/libplacebo] Spent 1086.000 ms generating shader LUT (slow!)

**Comment by haasn** [comment]
Did you build libplacebo with optimization?

**Comment by CharlesMengCA** [comment]
Same configuration like here: https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/packages/libplacebo.cmake

**Comment by haasn** [comment]
What CPU are you on?

**Comment by CharlesMengCA** [comment]
CPU i7-10700, GPU 1650 Super, nvidia driver 532.03

**Comment by CharlesMengCA** [comment]
Old build, only shown when using -v option
```
[vo/gpu-next/libplacebo] Spent 79.000 ms translating SPIR-V
[vo/gpu-next/libplacebo] Spent 86.000 ms creating pipeline
[vo/gpu-next/libplacebo] Spent 220.000 ms generating shader LUT (slow!)
[vo/gpu-next/libplacebo] Spent 12.000 ms translating SPIR-V
[vo/gpu-next/libplacebo] Spent 17.000 ms creating pipeline
```

new build, shown on the console without the -v option 
```
[vo/gpu-next/libplacebo] Spent 75.000 ms translating SPIR-V
[vo/gpu-next/libplacebo] Spent 1199.000 ms generating shader LUT (slow!)
[vo/gpu-next/libplacebo] Spent 11.000 ms translating SPIR-V
```
Looks like 5 time slower?

**Comment by haasn** [comment]
CPU should be fast enough; is it possible that one of the `math.h` functions we call are very slow on windows?

In particular, we need:

* cosf/sinf
* atan2f
* sqrtf
* powf
* fmaxf/fminf
* fabsf

**Comment by kasper93** [comment]
Yes, I was looking at this few weeks or so ago. 

`powf` in particular is abysmal slow on mingw build, they explicitly link own version of `pow` which is 7-8 times slower than UCRT one. 

(talking about this gem https://github.com/mirror/mingw-w64/blob/eff726c461e09f35eeaed125a3570fa5f807f02b/mingw-w64-crt/math/x86/pow.def.h)

With https://github.com/haasn/libplacebo/commit/20d63f7335174cb54eb3582f406b4843771760e6

MS SDK build:
```
clang version 15.0.1
Target: x86_64-pc-windows-msvc

[vo/gpu-next/libplacebo] Spent 149.000 ms generating shader LUT
```

mingw build:
```
clang version 16.0.4
Target: x86_64-w64-windows-gnu

[vo/gpu-next/libplacebo] Spent 1054.000 ms generating shader LUT (slow!)
```

I spoke about it with mingw guys on IRC and they are aware some math functions are not great and should be replaced (or at least not used in case of UCRT mingw), but I don't really expect much movement in this area.


That say we have three options in order of feasibility :
1. Import some math functions directly from `api-ms-win-crt-math-l1-1-0.dll` (UCRT) before mingw links their math functions. I tested this some time ago (on previous version) and while I didn't get same performance as native clang build, it was only slightly slower. But I replaced only few functions. The issue with that it is not libplacebo job to mess with this... but I guess we have to at this point.
2. Pressure mingw maintainers to fix this math functions fiasco.
3. Use non-mingw libplacebo build. But since everyone is using all-in-one statically linked mpv even if we made build bot for that it is not possible for you to replace it.

**Comment by haasn** [comment]
We use `powf` mainly with fixed exponent, so a fourth option would be to hard-code an approximation of this function. May be faster on all platforms.

**Comment by CharlesMengCA** [comment]
@haasn , with your patch 471. my test video reduced from 1209.000 ms  to  90.000 ms.

[vo/gpu-next/libplacebo] Spent 1209.000 ms generating shader LUT (slow!)

[vo/gpu-next/libplacebo] Spent 90.000 ms generating shader LUT

**Comment by natural-harmonia-gropius** [comment]
I feel good about perceptual v2.

**Comment by natural-harmonia-gropius** [comment]
I have re-checked this scene, Chroma is flat, hue is uneven.

Chroma
hue
![image](https://github.com/mpv-player/mpv/assets/50797982/c5c2f071-70de-47e2-a0a5-0b6b9c8477b4)
![image](https://github.com/mpv-player/mpv/assets/50797982/1fdf8e76-c206-4450-9e44-fc2d0743f318)
