### ISSUE TITLE
Tone mapping bt.2446a

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#11596]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I was just wondering if tonemapping method bt.2446a is supposed to be Dark as it is on my device and is this the best and recommended method for tonemapping hdr content to sdr 

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by haasn** [comment]
BT.2446 is meant to be pretty dark by design, yeah. It's intended for well-ranged HDR 1000 -> SDR tone-mapping.

I actually don't recommend using it anymore, I recommend using spline tone-mapping plus peak detection.

**Comment by Jamie666123** [comment]
> BT.2446 is meant to be pretty dark by design, yeah. It's intended for well-ranged HDR 1000 -> SDR tone-mapping.
> 
> I actually don't recommend using it anymore, I recommend using spline tone-mapping plus peak detection.

By this you mean hdr compute peak?

**Comment by pbiancardi** [comment]
> BT.2446 is meant to be pretty dark by design, yeah. It's intended for well-ranged HDR 1000 -> SDR tone-mapping.
> 
> I actually don't recommend using it anymore, I recommend using spline tone-mapping plus peak detection.

I am curious why spline is now recommended?  BT.2446a seems to more closely match what MadVR is doing with their latest recommended settings?

[url=https://postimg.cc/yWrBGKgF][img]https://i.postimg.cc/yWrBGKgF/2Madvr.png[/img][/url]

[url=https://postimg.cc/svkzVJJx][img]https://i.postimg.cc/svkzVJJx/2spline.png[/img][/url]

[url=https://postimg.cc/K1t24g9N][img]https://i.postimg.cc/K1t24g9N/bt-2446.png[/img][/url]

**Comment by haasn** [comment]
Huh? madVR looks significantly closer to `spline` in that screenshot, not bt.2446a.

As to answer the question, `spline` takes into account scene average brightness, `bt.2446a` doesn't.

**Comment by pbiancardi** [comment]
> Huh? madVR looks significantly closer to `spline` in that screenshot, not bt.2446a.
> 
> As to answer the question, `spline` takes into account scene average brightness, `bt.2446a` doesn't.

I thought spline looks brighter than the other two.  Don't get me wrong I love spline just testing other things.  Appreciate the answer.

**Comment by Jamie666123** [comment]
> > Huh? madVR looks significantly closer to `spline` in that screenshot, not bt.2446a.
> > As to answer the question, `spline` takes into account scene average brightness, `bt.2446a` doesn't.
> 
> I thought spline looks brighter than the other two. Don't get me wrong I love spline just testing other things. Appreciate the answer.

It also looks to me like spline is the brighter of the other think I will stick with bt.2446a and only change depending on the content appreciate the help though

**Comment by geextahslex** [comment]
@haasn 
>I actually don't recommend using it anymore, I recommend using spline tone-mapping plus peak detection.

Which HDR to SDR tone mapping are you recommending now?
