### ISSUE TITLE
Can I loop a video track while a longer audio track continues to play? 

### ISSUE THREAD

**Issue by JimPancakes** [mpv-player/mpv#11597]
I have video file with a shorter video track and a longer audio track. I know I could use ffmpeg to loop the video to the length of the audio file but that would increase the file size.

Does mpv have any function that would disable the sync between the two tracks and just let the video track loop for the duration of the audio one or does anyone know a better solution to this problem?

**Comment by po5** [comment]
Should be possible with EDL? https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst
