### ISSUE TITLE
Is --input-ipc-client=fd:// race-free when forking mpv?

### ISSUE THREAD

**Issue by vl-80** [mpv-player/mpv#11598]
### When is it safe to start writing to the IPC socket when using `--input-ipc-client=fd://<N>` option?

Assuming that the mpv is being forked by another process with the `--input-ipc-client=fd://<N>` option and a file descriptor obtained from a call to `socketpair()`, is it safe to start writing commands to this socket immediately after the mpv was forked (without waiting for some input from the mpv first)?

Theoretically, the controlling process could start writing to the IPC socket while the mpv process is still starting up after being forked.

So, is it guaranteed that there is no race condition and the mpv will read all input from this socket and try to execute the commands even if they were written while the mpv was still starting?

**Comment by sfan5** [comment]
Not 100% sure about `sockpair` but with `pipe` it will behave like a FIFO and mpv will just get the first-written data no matter how later it starts up, no race condition exists.
