### ISSUE TITLE
audio left/right swapped (coreaudio)

### ISSUE THREAD

**Issue by metayan** [mpv-player/mpv#11590]
- mpv built from master (also with Homebrew versions)
- macOS Version 10.15.7
- Issue has been present for several years

```
mpv orks-270-gc50f536bd1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Fri Apr 14 04:34:48 2023
FFmpeg version: n5.1.2-60-g3553421888
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
```

### Reproduction steps

Play any video or audio file with more than one audio channel
```
./build/mpv --no-config test-l.aiff
```
and something like the following is shown
```
 (+) Audio --aid=1 (pcm_s16be 2ch 48000Hz)
AO: [coreaudio] 48000Hz fr-fl (stereo) 2ch s16
```
```
 (+) Audio --aid=1 (*) (ac3 6ch 48000Hz)
AO: [coreaudio] 48000Hz fr-fl (stereo) 2ch floatp
```
Note the `fr-fl` above. It should most likely be `fl-fr`.

### Expected behavior
Left channel from audio stream should go to left output, and vice versa.

### Actual behavior
- The left channel from the audio stream is sent to the right (wrong) output
- The right channel is sent to the left output

### Log files
[output-aac.txt](https://github.com/mpv-player/mpv/files/11245201/output-aac.txt)
[output-mp3.txt](https://github.com/mpv-player/mpv/files/11245202/output-mp3.txt)
[output-mp4.txt](https://github.com/mpv-player/mpv/files/11245203/output-mp4.txt)

Couldn't upload audio test files, but they can easily be generated with
```sh
sox -c 2 -b 16 -n test-l.aiff synth 1 sine 220 sine 0 vol 0.7
sox -c 2 -b 16 -n test-r.aiff synth 1 sine 0 sine 220 vol 0.7
```

### Extra information
Speaker Configuration in Audio MIDI Setup in macOS is set to
- Left  = Channel 1
- Right = Channel 2

### Notes
For a while I used to correct the channels in `mpv` config with
`af-append=pan=[stereo|c0=c1|c1=c0]`
but it's not a good solution, because it messes up audio for some files.

When thoroughly testing different players now, I noticed that `ffplay` also swaps the channels. All other programs I have tested play correctly.

**Comment by Akemi** [comment]
could you please be more specific how you setup your audio output in "Audio MIDI Setup"? i am unable to reproduce this.

**Comment by metayan** [comment]
> could you please be more specific how you setup your audio output in "Audio MIDI Setup"? i am unable to reproduce this.

I use "Built-in Output" with headphones connected.
Format is set to "2 ch 24-bit Integer 48.0 kHz". (Can be set to anything.)
In "Configure Speakers…" I have "Configuration: Stereo" and
Left speaker: Channel 1
Right speaker: Channel 2

When I press the buttons under "Test" there,
"Left" plays in the left ear and "Right" in the right ear.

**Comment by Akemi** [comment]
then the config is not different on my end.

does setting `--audio-channels=stereo` fix the issue on your end?

**Comment by metayan** [comment]
> does setting `--audio-channels=stereo` fix the issue on your end?

No. The channels are still swapped.

Both with and without `--audio-channels=stereo` I get:
```
[ao] Trying audio driver 'coreaudio'
[ao/coreaudio] requested format: 48000 Hz, stereo channels, s16
[ao/coreaudio] selected audio output device: Built-in Output (61)
[ao/coreaudio] input channel layout:
[ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio]  - description 0: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio]  - description 1: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio] mp chmap: fr-fl
[ao/coreaudio] input channel layout:
[ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio] mp chmap: stereo
[ao/coreaudio] Channel layouts:
[ao/coreaudio]  - fr-fl
[ao/coreaudio]  - stereo
[ao/coreaudio]  - mono
[ao/coreaudio] result: fr-fl
```

I suspect that the `fr-fl` should be `fl-fr`, or?

`mpv --audio-channels=help`
shows
```
[...]
Standard layouts:
    empty            ()
    mono             (fc)
    1.0              (fc)
    stereo           (fl-fr)
    2.0              (fl-fr)
[...]
```
Where can the `fr-fl` come from?

**Comment by metayan** [comment]
It's solved.
Must have been some kind of glitch in the system.

Thought to check if `Reaper` and `GarageBand` would play correctly if I swap the channels (Left=2, Right=1) in `Audio/MIDI Setup` and they did, and also `mpv` played correctly. Alright, that seems better than having to "turn" the headphones all the time.

So, just out of curiosity, I set the channels correctly again (Left=1, Right=2), and amazingly – they're not swapped any more.
Another macOS peculiarity, i guess.

Now I get
```
[ao] Trying audio driver 'coreaudio'
[ao/coreaudio] requested format: 48000 Hz, stereo channels, s16
[ao/coreaudio] selected audio output device: Background Music (45)
[ao/coreaudio] input channel layout:
[ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio] mp chmap: stereo
[ao/coreaudio] input channel layout:
[ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio] mp chmap: stereo
[ao/coreaudio] Channel layouts:
[ao/coreaudio]  - stereo
[ao/coreaudio]  - stereo
[ao/coreaudio]  - mono
[ao/coreaudio] result: stereo
```
with or without `--audio-channels=stereo`, which sure looks better.

Thanks for the poke to investigate again.
And mega thanks for `mpv`.

**Comment by Akemi** [comment]
yeah this is what i wanted to mention next. those lines in the log:
```
[ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio]  - description 0: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio]  - description 1: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio] mp chmap: fr-fl
[ao/coreaudio] input channel layout:
[ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio] mp chmap: stereo
```

looked suspiciously wrong, eg the swapped `label <1, 0>` and `label <2, 1>` between stereo and fr-fl. stereo on my end looked the same as in your log. i was really wondering where this layout came from.

even though it still seems weird that you have two identical stereo layouts, it's good the issue could be resolved.

maybe it was some configuration from an older version of macOS, and when you updated it borked somehow.
