### ISSUE TITLE
--untimed option

### ISSUE THREAD

**Issue by pacioc193** [mpv-player/mpv#11591]
We are trying to reproduce the --untimed option in a custom video player. We perform a streaming from ffmpeg with codec h264_nvenc. Using a normal player we have around 1.2 second of delay. Using mpv with --untimed option, we have around 250ms. Could anyone explain how to reproduce this option?

**Comment by CounterPillow** [comment]
Read the source code and do your own work instead of badgering a volunteer project for help with your product

**Comment by pacioc193** [comment]
> Read the source code and do your own work instead of badgering a volunteer project for help with your product

I've read the source code and found the solution. Thanks.
