### ISSUE TITLE
Add support for .pdv (Playdate video format)

### ISSUE THREAD

**Issue by gingerbeardman** [mpv-player/mpv#11595]
### Expected behavior of the wanted feature

- support playback of .pdv (Playdate video format)

**Further info**

- there is currently no way to play back this type of video outside of bundling in a game
- so it's very difficult to preview such files

**Format spec:**

- https://github.com/jaames/playdate-reverse-engineering/blob/main/formats/pdv.md

**Example file**

- [1345488076.pdv.zip](https://github.com/iina/iina/files/11242854/1345488076.pdv.zip)

**Comment by gingerbeardman** [comment]
Oh! OK.

IINA player sent me here, but I will file it at ffmpeg.

**Comment by Traneptora** [comment]
Unless something weird happens, nothing needs to be done once it's added upstream. Also "completed" is just the default, I didn't specifically check that.

**Comment by gingerbeardman** [comment]
Thanks for the follow-up and explanation!

**Comment by gingerbeardman** [comment]
It's coming! ffmpeg just added support (pending new release)

http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=dc2da568cfd281740102032582ca25bbf4449100
