### ISSUE TITLE
Gnome 3.14 / Wayland

### ISSUE THREAD

**Issue by d3xter** [mpv-player/mpv#1159]
Hey guys,

I've tried to run mpv 0.6.0/vo=opengl on gnome 3.14.

Video/Audio playback is fine, but there are 2 major problems:

There is no client side decoration of the playback window, but i'm still able to move the window.

Fullscreen works partially:
The video gets resized to the maximum width or height, but the black bars to fill the screen are missing,
so if the video is too wide, the video playback is placed on the top of the screen and beneath it, the desktop or any window behind it is shown

**Comment by giselher** [comment]
I played a bit with gnoome on wayland and the `wl_shell` interface reports wrong resolutions and frame rates. This will not be fixed any time soon.

**Comment by m13253** [comment]
Latest upgrade (0.8.3-1 -> 0.9.0-2) on ArchLinux made `--vo wayland` and `--vo opengl` unusable on Gnome 3.16.1.
But it works fine on Weston.
```
$ mpv blah.mp4
[vo/opengl/wayland] error occurred on the display fd: closing file descriptor
$ mpv --vo wayland blah.mp4
[vo/wayland/wayland] error occurred on the display fd: closing file descriptor
```

My compositor info, running Gnome 3.16.1. Information is obtained with `weston-info`:
```
interface: 'wl_drm', version: 2, name: 1
interface: 'wl_compositor', version: 3, name: 2
interface: 'wl_shm', version: 1, name: 3
	formats: XRGB8888 ARGB8888
interface: 'wl_output', version: 2, name: 4
	x: 0, y: 0,
	physical_width: 310 mm, physical_height: 170 mm,
	make: 'LGD', model: '0x028d',
	subpixel_orientation: horizontal rgb, output_transform: normal,
	mode:
		width: 1366 px, height: 768 px, refresh: 0 Hz,
		flags: current preferred
interface: 'wl_data_device_manager', version: 2, name: 5
interface: 'xdg_shell', version: 1, name: 6
interface: 'wl_shell', version: 1, name: 7
interface: 'gtk_shell', version: 1, name: 8
interface: 'wl_subcompositor', version: 1, name: 9
interface: 'wl_seat', version: 4, name: 10
	name: seat0
	capabilities: pointer keyboard
	keyboard repeat rate: 33
	keyboard repeat delay: 500
```

**Comment by wm4** [comment]
CC @Cloudef

**Comment by jashandeep-sohi** [comment]
@m13253:
I can second your problem with ``--vo=wayland`,  ``--vo=opengl`` and ``--vo=openg-hq``.
I'm also using Arch & upgraded mpv 0.8.3-1 --> 0.9.0-2.

``--vo=opengl` & `--vo=opengl-hq`` was working before the upgrade.
``--vo-wayland` was segfaulting.

**Comment by Cloudef** [comment]
mpv does not actually draw the black borders. It's compositor drawing black behind fullscreen clients, which gnome doesn't do in this case. I did look around wayland_common.c and it's probably good idea to use ```WL_SHELL_SURFACE_FULLSCREEN_METHOD_SCALE``` ```instead of the WL_SHELL_SURFACE_FULLSCREEN_METHOD_DEFAULT```.

**Comment by mjrh** [comment]
@jashandeep-sohi @m13253 
Arch linuxer here. I ran git bisect:

    c10fb4ce9fcd3dbbf69741eb8499c4cfabbf5412 is the first bad commit
    commit c10fb4ce9fcd3dbbf69741eb8499c4cfabbf5412
    Author: Jari Vetoniemi <mailroxas@gmail.com> 
    Date:   Sun Mar 22 02:48:09 2015 +0200

        vo_wayland: define opaque region
    
        This allows compositor to optimize rendering, as it will know mpv is not
        transparent.

    :040000 040000 4d60543f8cae97d35734bb9100c88c9d5a0811d8 
    2a31ce4bc871988cf6f7c09874ddd5afaa51a3dc M	video

**Comment by jashandeep-sohi** [comment]
@mjrh
I did something similar, but just commented out the commit line, since it was complaining about committing a NULL buffer:
```
struct wl_region *region = wl_compositor_create_region(wl->display.compositor);
if (region) {
    wl_region_add(region, x, y, width, height);
    wl_surface_set_opaque_region(wl->window.video_surface, region);
    //wl_surface_commit(wl->window.video_surface);
    wl_region_destroy(region);
}
```
However, I don't really know what the implications are of not committing right away, so I'm not sure if this is the proper way of fixing it.

**Comment by giselher** [comment]
Fullscreen now works with:  eb6b2b6e

Using `xdg_shell` instead of `wl_shell` will add at least borders and a close button. That is next on my list.

**Comment by jashandeep-sohi** [comment]
:clap: :clap: :clap: :bow:

**Comment by ignisf** [comment]
can confirm, fullscreen works.
