### ISSUE TITLE
`mpv` doesn't stream (directly) from WDA MJPEG Server

### ISSUE THREAD

**Issue by miticollo** [mpv-player/mpv#11607]
I am currently experimenting with Appium, and I am trying to stream my iOS screen on my macOS device.

To achieve this, I used the WDA MJPEG Server from the [WebDriverAgent](https://github.com/appium/WebDriverAgent)Runner.
This server is set up to listen on port 9100. 
After mapping the remote port to a local port on my macOS device using `iproxy 9100:9100`, I opened a browser on http://localhost:9100 and I got this result:

https://user-images.githubusercontent.com/30465144/233343174-404d0152-66d3-4d38-85fb-3e796e863cc4.mov

But I didn't want the strange "refreshing effect".
To resolve this issue, I tried using `mpv  -v -v -v http://localhost:9100` - installed with `brew install mpv` - but it had resulted in the error [`[cplayer] Failed to recognize file format.`](https://pastebin.com/raw/Kf97XakS)

So googling, I found a solution:
```shell
ffmpeg -f mjpeg -i http://localhost:9100 -f rawvideo - | mpv - --demuxer=rawvideo --demuxer-rawvideo-w=750 --demuxer-rawvideo-h=1334
```
which produced a satisfactory result as you can see in the screenshots below

|                                   Screenshot takes with `S` key of `mpv`                                    |                Screenshot takes with [macOS utilities](https://support.apple.com/en-us/HT201361)                |
|:-----------------------------------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------:|
| ![s](https://user-images.githubusercontent.com/30465144/233350312-c64237fd-769a-4e62-9477-db601c47f690.png) | ![macos](https://user-images.githubusercontent.com/30465144/233344010-3b5f124c-0de8-47b8-9f6f-97ca48e05489.png) |

However, I noticed a color difference in the result, and **I am unsure of the cause**.

Finally, **I would like to know if there is a way to stream the video using `mpv` without accessing `ffmpeg`**.

I also experimented with VLC and ran the following command `vlc --avformat-format=mjpeg 'http://localhost:9100'`.
The resulting output is shown in the attached image below.
![vlc](https://user-images.githubusercontent.com/30465144/233348819-e9bba978-7397-4ced-bb7b-28c87ce60ae1.png)

**Comment by CounterPillow** [comment]
try `mpv --demuxer-lavf-format=mjpeg url`

**Comment by CounterPillow** [comment]
yes that's probably the lowest latency you can achieve with mpv.
