### ISSUE TITLE
How can I make mpv stay alive if a http stream disappears?

### ISSUE THREAD

**Issue by TheChymera** [mpv-player/mpv#11601]
I found [this issue](https://github.com/mpv-player/mpv/issues/5793), which seems to be asking the same thing, but (1) no clear answer is provided and (2) of the non-clear answers none seem to work.

I am using mpv to play an audio stream from my mpd server.
The basic command is `mpv http://localhost:8000/mpd.ogg`

This works but whenever the connection drops the command exits and I have to turn it on again after I reconnect.
Is there any way to tell mpv to just stay alive and monitor that stream even if it stops existing temporarily?

**Comment by Traneptora** [comment]
If the connection tends to drop momentarily and momentarily only, what happens if you use `--loop-playlist=force`?

**Comment by Traneptora** [comment]
Does that solve your issue?
