### ISSUE TITLE
How to optimize HDR to SDR tone mapping for projector?

### ISSUE THREAD

**Issue by ANONIMNIQ** [mpv-player/mpv#11605]
Can you guys suggested me the best settings? My GPU is not good enough for MadVR so I try to experiment with mpv and really like the results overall, but still have some issues with the picture in some scenes. I watch on my Xiaomi Mi Laser UST FHD 150 projector. The projector itself supports HDR from HDMI, but results are not great, so I prefer tone mapping. In this scene colors looked really bad on my projector, but they look ok on my TV. I'm not sure how to fix this and to optimize settings for my projector to produce connsistent results.

<a href="https://ibb.co/VHTXMXP"><img src="https://i.ibb.co/KNWCVC3/Screenshot-108.png" alt="Screenshot-108" border="0"></a>
<a href="https://ibb.co/RSCx2Qz"><img src="https://i.ibb.co/pP3t24J/Screenshot-109.png" alt="Screenshot-109" border="0"></a><br />

```
vo = gpu-next
hwdec = auto
tone-mapping = hable
hdr-compute-peak = yes
target-peak= 50
```

**Comment by quietvoid** [comment]
Try `tone-mapping=spline`.

**Comment by ANONIMNIQ** [comment]
I think problem is that picture is too bright and loose detail. In some scenes looks too cartoonish with these color shades.

<a href="https://ibb.co/zXQj3MF"><img src="https://i.ibb.co/k45kL7J/IMG-20230420-202626.jpg" alt="IMG-20230420-202626" border="0"></a>
<a href="https://ibb.co/t3PMKkd"><img src="https://i.ibb.co/ZN16XtZ/IMG-20230420-202540.jpg" alt="IMG-20230420-202540" border="0"></a>
<a href="https://ibb.co/WpQTqqH"><img src="https://i.ibb.co/cXPmMMy/IMG-20230420-200327.jpg" alt="IMG-20230420-200327" border="0"></a>
<a href="https://ibb.co/0fcVLWT"><img src="https://i.ibb.co/GV03D1y/IMG-20230420-200254.jpg" alt="IMG-20230420-200254" border="0"></a>
<a href="https://ibb.co/dbxzd61"><img src="https://i.ibb.co/0BvdgZ8/IMG-20230420-195948.jpg" alt="IMG-20230420-195948" border="0"></a>
<a href="https://ibb.co/0n163rD"><img src="https://i.ibb.co/cyRZdQg/IMG-20230420-195805.jpg" alt="IMG-20230420-195805" border="0"></a>
<a href="https://ibb.co/dgsm3qG"><img src="https://i.ibb.co/0tpsWSh/IMG-20230420-195721-1.jpg" alt="IMG-20230420-195721-1" border="0"></a>
<a href="https://ibb.co/qdNZMBP"><img src="https://i.ibb.co/0cCwjqd/IMG-20230420-195705.jpg" alt="IMG-20230420-195705" border="0"></a>
<a href="https://ibb.co/fQM6vcd"><img src="https://i.ibb.co/52TpF7h/IMG-20230420-195633.jpg" alt="IMG-20230420-195633" border="0"></a>
<a href="https://ibb.co/Gs1Q7xQ"><img src="https://i.ibb.co/wJbhy0h/IMG-20230420-195539.jpg" alt="IMG-20230420-195539" border="0"></a>
<a href="https://ibb.co/0DCVHNL"><img src="https://i.ibb.co/X27kcBP/IMG-20230420-195520.jpg" alt="IMG-20230420-195520" border="0"></a>

**Comment by ANONIMNIQ** [comment]
> Try this for HDR to SDR tonemapping: https://github.com/natural-harmonia-gropius/hdr-toys

Thank you! It's much, much better now. Really close to MadVR actually!

**Comment by aboulfad** [comment]
Would you mind sharing your mpv config file that includes the hdr-toys? I keep getting errors at runtime when I change the tone mapping.

**Comment by Karnbir** [comment]
> Would you mind sharing your mpv config file that includes the hdr-toys? I keep getting errors at runtime when I change the tone mapping.

Try using this portable config for reference. It comes with HDR-Toys installed out of the box: https://github.com/natural-harmonia-gropius/mpv-config/tree/intl

**Comment by aboulfad** [comment]
> > Would you mind sharing your mpv config file that includes the hdr-toys? I keep getting errors at runtime when I change the tone mapping.
> 
> Try using this portable config for reference. It comes with HDR-Toys installed out of the box: https://github.com/natural-harmonia-gropius/mpv-config/tree/intl

Thanks for the suggestion, I previously looked at the portable config, the glsl entry at https://github.com/natural-harmonia-gropius/mpv-config/blob/d17d4acb6d5bfe09cb4ccd4ad6c718a73a742767/portable_config/mpv.conf#L107 uses dynamic. Changing it to anything else yields bunch of errors in console. I’ll create a separate issue.
