### ISSUE TITLE
Build fails when it gets to libplacebo

### ISSUE THREAD

**Issue by HMVocaloid** [mpv-player/mpv#11603]
![image-24](https://user-images.githubusercontent.com/66088611/233244965-5e778a4b-6764-4dd4-8219-332015eaceb5.png)

Build fails at the same line of code with no way for me to skip it. I'm using a Raspberry Pi 4 running Raspbian Buster.

**Comment by CounterPillow** [comment]
> running Raspbian Buster.

Update to Bullseye? Bookworm is almost out.

**Comment by haasn** [comment]
How did you even compile libplacebo, which requires Vulkan 1.3 to build?

**Comment by HMVocaloid** [comment]
I have no idea how it was compiling. I will upgrade the distro though and see if it helps. I just haven't updated cause I didn't think it was necessary.

**Comment by haasn** [comment]
Oh, maybe it built with libplacebo's vendored vulkan headers (which are provided via git submodule)

**Comment by Traneptora** [comment]
Try rebuilding libplacebo after running `git clean -dfx` in its source tree.
