### ISSUE TITLE
User Script to Persist loop-file State

### ISSUE THREAD

**Issue by blueray453** [mpv-player/mpv#11614]
I have written a user script based on https://gist.github.com/blackarcher21/162dc1bef708e90082c6c4f9500c1997 to persist loop-file state. The gist works but the following code does not work.

```lua
local filepath = mp.command_native({"expand-path", "~~/loop-file-state"})

local loadfile = io.open(filepath, "r")

if loadfile then
    set_loop_file = string.sub(loadfile:read(), 11)
    loadfile:close()
    mp.set_property_number("loop-file", set_loop_file)
end

mp.register_event("shutdown",
    function()
        local savefile  = io.open(filepath, "w+")
        savefile:write("loop-file=" .. mp.get_property("loop-file"), "\n")
        savefile:close()
    end
)
```
I searched but could not find a forum which help in writing mpv user scripts. Please help.

**Comment by christoph-heinrich** [comment]
I haven't tested it, but using `mp.set_property_number()` instead of `mp.set_property_bool()` doesn't seem right.

Also please make the link an actual link and use lua syntax highlighting in the code :wink:.

**Comment by blueray453** [comment]
I have updated the question. The link is of a gist. I have fixed it. By lua syntax highlighting, if you mean "```lua", then have fixed it in the update.

**Comment by christoph-heinrich** [comment]
I've now looked at it some more and tested it. Simply replace `mp.set_property_number()` with `mp.set_property()` and it'll work.

**Comment by blueray453** [comment]
Thank you very much.
