### ISSUE TITLE
Keyboard autorepeat doesn't work with "run" command in input.conf.

### ISSUE THREAD

**Issue by drummer315** [mpv-player/mpv#11611]
mpv version: ffmpeg version: 4.3.5-0+deb11u1
linux distribution: Debian GNU/Linux 11

Create a input.conf file containing a line like "d run sh -c date"
Run "mpv --input-conf=input.conf movie.mp4"
Use every combination of "--native-keyrepeat", "--input-ar-delay", "--input-ar-rate" in the command.

While movie is playing, hold down the "d" button.

### Expected behavior

output date to terminal many times.

### Actual behavior

Only outputs date to terminal once.

When I hold down, for example, "0" to adjust volume, auto repeat works.

**Comment by garoto** [comment]
https://mpv.io/manual/master/#command-interface-repeatable

As in `d repeatable run sh -c date`

**Comment by drummer315** [comment]
Thanks!
