### ISSUE TITLE
How to create thumbnails in MPV like Video Thumbnails Maker (or MTN)

### ISSUE THREAD

**Issue by Cerastia** [mpv-player/mpv#11622]
I want to create a preview picture file of 5x4 grid screenshot.

Each Grid image must have an equal interval with each other at the total playback time.
I want the same result even if I use a file with different playback times
(like as Video Thumbnails Maker or MTN output)

I want to know if the above function is possible with the command line by mpv itself.

**Comment by hooke007** [comment]
> I want to know if the above function is possible with the command line by mpv itself.

I’m afraid not.
check https://github.com/noaione/mpv-js-scripts#screenshot-mosaic
