### ISSUE TITLE
Can't hear audio on YouTube Videos through MPV

### ISSUE THREAD

**Issue by HiddenLeveI** [mpv-player/mpv#11629]
### Important Information

Provide following Information:
- mpv version: 2023.03.04
- Linux Distribution and Version: Pop_OS!, latest version and Debian based.
- Source of the mpv binary: Flatpak and Pop_Shop.
- If known which version of mpv introduced the problem: This recent one.
- Window Manager and version
- GPU driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by solarchemist** [comment]
Probably related to https://github.com/mpv-player/mpv/issues/11392.
Haven't tried the suggested fix myself, but others seem contented.

**Comment by HiddenLeveI** [comment]
I meant that my ytdl was up to date, and so was MPV itself at 35.1

**Comment by HiddenLeveI** [comment]
I left windows blank since I don't use Windows, didn't know about my driver, and figured that the issue is self explanatory so didn't need a picture.

**Comment by Jj0YzL5nvJ** [comment]
> I meant that my ytdl was up to date, and so was MPV itself at 35.1

Use the [nightly builds](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest) or ["build" from code](https://github.com/yt-dlp/yt-dlp) (`make yt-dlp`). The last stable version is in fact failing with YouTube.
