### ISSUE TITLE
The macOS system requirements are wrong

### ISSUE THREAD

**Issue by MikeRich88** [mpv-player/mpv#11628]
mpv version: 0.35.1
macOS Version: Mojave 10.14.6 (18G9323)
Source of binary: https://laboratory.stolendata.net/~djinn/mpv_osx/

<img width="488" alt="image" src="https://user-images.githubusercontent.com/7113073/234227388-499dd012-dbd0-4c81-9bc3-7c2156b49738.png">

I decided to power on my old 2015 MacBook Pro. It has been a few years so I updated all the apps as best I could (but I leave the OS on Mojave due to old 32 bit games and such)

The system requirements in this project README.md state, "A not too ancient Linux, Windows 7 or later, or OSX 10.8 or later." but clearly that is inaccurate.

If possible, you/whoever should provide links to the last binar(ies) that do work on various versions of the OS.

I do not know why it says "%@" instead of actual version. It could be a macOS bug or some error in mpv.

**Comment by Akemi** [comment]
you downloaded a version of mpv that is not compiled for your version of the OS. read the information on the download link you posted. for the only 0.35.1 download it says "built for macOS 12 (monterey) and later.". you have to download an older version or build it yourself.

the code support has nothing to do with how the binary/app was built. technically mpv can still support older macOS versions with some ceavats.

we don't provide any prebuilt binaries or app.
