### ISSUE TITLE
mpv + ytdl can not play YouTube video

### ISSUE THREAD

**Issue by HtPsi** [mpv-player/mpv#11631]
Important Information
Provide following Information:

mpv version: latest x64 version

Windows Version 10 lateest updates etc

Source of the mpv binary  :  updated with updater.bat

If known which version of mpv introduced the problem latest

video ===> https://www.youtube.com/watch?v=X7jXBPfFEh4

Reproduction steps
Drag & Drop any YouTube Link like:
https://www.youtube.com/watch?v=X7jXBPfFEh4

The mpv player waits for a moment and shows the thumbnail for a moment ,  and then crashes.

The yt-dlp.exe is already installed using updater.bat, and the yt-dlp.exe file is right in the mpv folder with mpv.exe.

The yt-dlp is running normally, and the video https://www.youtube.com/watch?v=X7jXBPfFEh4 can be downloaded by yt-dlp.
> C:\Users\HtPsi>yt-dlp https://www.youtube.com/watch?v=X7jXBPfFEh4
> [youtube] Extracting URL: https://www.youtube.com/watch?v=X7jXBPfFEh4
> [youtube] X7jXBPfFEh4: Downloading webpage
> [youtube] X7jXBPfFEh4: Downloading android player API JSON
> [info] X7jXBPfFEh4: Downloading 1 format(s): 22
> [download] Destination: UNBELIEVABLE! Tonikaku BARES ALL with hilarious poses ｜ Auditions ｜ BGT 2023 [X7jXBPfFEh4].mp4
> [download] 100% of   30.63MiB in 00:00:05 at 6.06MiB/s

In the cmd,  input the commend 
> mpv --ytdl-format=best https://www.youtube.com/watch?v=X7jXBPfFEh4

the the Log  is as follows:
> [ffmpeg] tcp: Connection to tcp://www.youtube.com:443 failed: Error number -138 occurred
> Failed to open https://www.youtube.com/watch?v=X7jXBPfFEh4.
> [ffmpeg] tcp: Connection to tcp://rr2---sn-a5mekndl.googlevideo.com:443 failed: Error number -138 occurred

I am using a vpn to access youtube, is there something wrong with this?

**Comment by Traneptora** [comment]
It looks like the issue is somehow between FFmpeg's https client and your VPN. What happens if you load up an HTTPS file directly? e.g. `ffplay.exe -i "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"` or something of that form?

**Comment by HtPsi** [comment]
It seems working well with this commend:

> C:\Users\HtPsi>ffmpeg.exe -i "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" dwa.mp4
ffmpeg version N-110399-gf7d64881f Copyright (c) 2000-2023 the FFmpeg 
> .............downloading...................
> [out#0/mp4 @ 000001859899ce00] video:143986kB audio:11630kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.347503%
> frame=17622 fps=200 q=-1.0 Lsize=  156156kB time=00:12:14.23 bitrate=1742.3kbits/s speed=8.33x
> [libx264 @ 00000185983c6500] frame I:176   Avg QP:18.93  size: 50932
> [libx264 @ 00000185983c6500] frame P:6029  Avg QP:22.74  size: 16021
> [libx264 @ 00000185983c6500] frame B:11417 Avg QP:26.45  size:  3669
> [libx264 @ 00000185983c6500] consecutive B-frames: 10.4%  7.2%  7.4% 75.0%
> [libx264 @ 00000185983c6500] mb I  I16..4: 12.4% 54.3% 33.3%
> [libx264 @ 00000185983c6500] mb P  I16..4:  3.2% 11.4%  2.0%  P16..4: 37.3% 15.9%  8.0%  0.0%  0.0%    skip:22.1%
> [libx264 @ 00000185983c6500] mb B  I16..4:  0.5%  1.6%  0.3%  B16..8: 38.8%  4.6%  0.9%  direct: 1.4%  skip:52.0%  L0:48.8% L1:44.4% BI: 6.8%
> [libx264 @ 00000185983c6500] 8x8 transform intra:66.4% inter:70.8%
> [libx264 @ 00000185983c6500] coded y,uvDC,uvAC intra: 53.1% 64.4% 20.0% inter: 12.7% 15.8% 0.8%
> [libx264 @ 00000185983c6500] i16 v,h,dc,p: 36% 28% 12% 25%
> [libx264 @ 00000185983c6500] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 20% 18%  4%  6%  6%  6%  6%  6%
> [libx264 @ 00000185983c6500] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 19% 12%  6%  8%  8%  8%  6%  6%
> [libx264 @ 00000185983c6500] i8c dc,h,v,p: 49% 21% 23%  7%
> [libx264 @ 00000185983c6500] Weighted P-Frames: Y:3.6% UV:1.3%
> [libx264 @ 00000185983c6500] ref P L0: 68.6% 15.4% 13.0%  3.0%  0.1%
> [libx264 @ 00000185983c6500] ref B L0: 94.8%  4.4%  0.8%
> [libx264 @ 00000185983c6500] ref B L1: 97.9%  2.1%
> [libx264 @ 00000185983c6500] kb/s:1606.44
> [aac @ 0000018597d1bf40] Qavg: 551.494

**Comment by HtPsi** [comment]
@Traneptora

It seems working well with this commend:

> C:\Users\HtPsi>ffmpeg.exe -i "https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4" dwa.mp4

> ffmpeg version N-110399-gf7d64881f Copyright (c) 2000-2023 the FFmpeg
> .............downloading...................
> [out#0/mp4 @ 000001859899ce00] video:143986kB audio:11630kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.347503%
> frame=17622 fps=200 q=-1.0 Lsize= 156156kB time=00:12:14.23 bitrate=1742.3kbits/s speed=8.33x
> [libx264 @ 00000185983c6500] frame I:176 Avg QP:18.93 size: 50932
> [libx264 @ 00000185983c6500] frame P:6029 Avg QP:22.74 size: 16021
> [libx264 @ 00000185983c6500] frame B:11417 Avg QP:26.45 size: 3669
> [libx264 @ 00000185983c6500] consecutive B-frames: 10.4% 7.2% 7.4% 75.0%
> [libx264 @ 00000185983c6500] mb I I16..4: 12.4% 54.3% 33.3%
> [libx264 @ 00000185983c6500] mb P I16..4: 3.2% 11.4% 2.0% P16..4: 37.3% 15.9% 8.0% 0.0% 0.0% skip:22.1%
> [libx264 @ 00000185983c6500] mb B I16..4: 0.5% 1.6% 0.3% B16..8: 38.8% 4.6% 0.9% direct: 1.4% skip:52.0% L0:48.8% L1:44.4% BI: 6.8%
> [libx264 @ 00000185983c6500] 8x8 transform intra:66.4% inter:70.8%
> [libx264 @ 00000185983c6500] coded y,uvDC,uvAC intra: 53.1% 64.4% 20.0% inter: 12.7% 15.8% 0.8%
> [libx264 @ 00000185983c6500] i16 v,h,dc,p: 36% 28% 12% 25%
> [libx264 @ 00000185983c6500] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 20% 18% 4% 6% 6% 6% 6% 6%
> [libx264 @ 00000185983c6500] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 27% 19% 12% 6% 8% 8% 8% 6% 6%
> [libx264 @ 00000185983c6500] i8c dc,h,v,p: 49% 21% 23% 7%
> [libx264 @ 00000185983c6500] Weighted P-Frames: Y:3.6% UV:1.3%
> [libx264 @ 00000185983c6500] ref P L0: 68.6% 15.4% 13.0% 3.0% 0.1%
> [libx264 @ 00000185983c6500] ref B L0: 94.8% 4.4% 0.8%
> [libx264 @ 00000185983c6500] ref B L1: 97.9% 2.1%
> [libx264 @ 00000185983c6500] kb/s:1606.44
> [aac @ 0000018597d1bf40] Qavg: 551.494

**Comment by Traneptora** [comment]
If you play that file directly with mpv, does it work well?

**Comment by HtPsi** [comment]
@Traneptora  Yes, still works well.

**Comment by HtPsi** [comment]
@Traneptora  mpv can still work in commend mode like this

> C:\Users\HtPsi>mpv https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4
> C:\Users\HtPsi\AppData\Roaming/mpv/mpv.conf:3: unparsable extra characters: ': jpn, jp, en'
> C:\Users\HtPsi\AppData\Roaming/mpv/mpv.conf:4: unparsable extra characters: ': jpn, jp, en'
> [mpvacious_master] Executing: 'mpv' '--ovc=help'
> [mpvacious_master] Executing: 'mpv' '--oac=help'
>  (+) Video --vid=1 (*) (h264 1280x534 24.000fps)
>  (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
> [mpvacious_master] Read profile list. Defined profiles: subs2srs,subs2srs_english
> AO: [wasapi] 48000Hz stereo 2ch float
> VO: [gpu] 1280x534 yuv420p
> [mpvacious_master] Read config file: subs2srs
> (Paused) AV: 00:02:10 / 00:12:14 (18%) A-V:  0.000 Cache: 561s/161MB

**Comment by HtPsi** [comment]
@Traneptora  The hole Error Log is as follows

> C:\Users\HtPsi>mpv --ytdl-format=best  https://www.youtube.com/watch?v=nsdiw25hXzM
> C:\Users\HtPsi\AppData\Roaming/mpv/mpv.conf:3: unparsable extra characters: ': jpn, jp, en'
> C:\Users\HtPsi\AppData\Roaming/mpv/mpv.conf:4: unparsable extra characters: ': jpn, jp, en'
> [mpvacious_master] Executing: 'mpv' '--ovc=help'
> [mpvacious_master] Executing: 'mpv' '--oac=help'
> [ffmpeg] tcp: Connection to tcp://www.youtube.com:443 failed: Error number -138 occurred
> Failed to open https://www.youtube.com/watch?v=nsdiw25hXzM.
> [ytdl_hook] ERROR: [youtube] nsdiw25hXzM: Unable to download API page: <urlopen error timed out> (caused by URLError(timeout('timed out')))
> [ytdl_hook] youtube-dl failed: unexpected error occurred

**Comment by HtPsi** [comment]
#7519

**Comment by aicynide** [comment]
Use binary fromhttps://github.com/zhongfly/mpv-winbuild

**Comment by HtPsi** [comment]
@aicynide Thank you for advice, but I do not know how to use Actions...
