### ISSUE TITLE
Does not work anymore with zdf country limited videos

### ISSUE THREAD

**Issue by mowgli** [mpv-player/mpv#11637]
Since few weeks I cannot play videos from zdf.de that are country limited (Example: https://www.zdf.de/dokumentation/zdfinfo-doku/containerschiffe-die-dunklen-geschaefte-der-reeder-100.html)

I currently HAVE a host in germany and using yt-dlp with --proxy works well with it. But in mpv, only the video url is fetched with yt-dlp but not the video itself. There IS a http proxy setting but I cannot test it as my proxy is only socks5.

Please implement a way to proxy also the video itself when using yt-dlp.

**Comment by guidocella** [comment]
`yt-dlp -o - $url | mpv -`

**Comment by sfan5** [comment]
Essentially a duplicate of #3373
