### ISSUE TITLE
mpv on Wayland seems to ignore video-sync=display-resample

### ISSUE THREAD

**Issue by vanfanel** [mpv-player/mpv#11647]
### Important Information

- mpv version: latest GIT code 6234a709202282d8a8bfffd0ee4f9d80561dd4b9
- Debian 11 aarch64
- Source of the mpv binary: built from latest GIT source
- Window Manager and version: latest stable labwc Wayland compositor (0.6.2)
- GPU driver and version: mesa-23.0.3 v3d (Raspberry Pi 4)

### Reproduction steps

-Add `video-sync=display-resample` to `~/.config/mpv/mpv.conf`
-Play a video with mpv.
-Pay attention to frame pacing, which is obviously wrong.

### Expected behavior

With the `video-sync=display-resample` config option or the equivalent commandline parameter, mpv should resample the audio and keep the video in sync with the physical screen videomode refresh rate, resulting in smooth playback, which does not happen. 

### Actual behavior

Jerky movement, specially notable in horizontal scrolling scenes.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/11362628/output.txt)

**Comment by Dudemanguy** [comment]
It's definitely not ignored at the very least. Are you sure you're not just having performance issues or something?

**Comment by vanfanel** [comment]
> It's definitely not ignored at the very least. Are you sure you're not just having performance issues or something?

Well, I don't think so. I am using hardware-accelerated v4l2m2m as you can see on the logs, and CPU usage doesn't go over 20%.

**Comment by Dudemanguy** [comment]
So what's actually happening? Are you dropping frames or is this just standard judder?

**Comment by vanfanel** [comment]
Standard judder. I don't see any dropped frames on the console.

**Comment by Dudemanguy** [comment]
Weak hardware/bad drivers probably. mpv is gpu-bound not cpu bound by the way.

**Comment by vanfanel** [comment]
The same videos on the same hardware play perfectly in LibreeElec.
How can it be that they don't play in MPV?

**Comment by Dudemanguy** [comment]
I have no idea what LibreeElec is, but I'm guessing it doesn't have an equivalent of display-resample (that option is more intensive).

**Comment by vanfanel** [comment]
RetroArch has an equivalent to display-resample and it doesn't cause a noticeable CPU usage on a Raspberry Pi 4.

Has someone actually tried mpv on a Pi4 on Wayland, please?

**Comment by Dudemanguy** [comment]
Why do you keep bringing up CPU usage? It's not relevant... Also isn't RetroArch some game emulator frontend?

**Comment by vanfanel** [comment]
> Why do you keep bringing up CPU usage? It's not relevant... Also isn't RetroArch some game emulator frontend?
> 
> Do you drop frames when using `mpv --no-config`?

I brought CPU usage because I guess resampling is done on the CPU.
And I also brought up RetroArch because it's GPU-bound when using Vulkan and shaders.

With `mpv --no-config` no frames are dropped... wow

**Comment by vanfanel** [comment]
It seems that removing `hwdec=v4l2m2m` or `hwdec=auto` from my `~/.config/mpv/mpv.conf` avoids dropped frames.
However CPU usage is doubled (yes, I know mpv is GPU-bounded, just reflecting what I see here).

**Comment by Dudemanguy** [comment]
I don't see a bug here. Just hardware limitations. `display-resample` repaints the frame every vblank, so it's more intensive on your GPU than the default. Apparently, using hwdec (which loads more work on your GPU) at the same time as `display-resample` is too much for it to handle. Not using hwdec, of course, leads to higher CPU usage. Pick your poison basically.

**Comment by vanfanel** [comment]
Aren't there other synchronization options, @Dudemanguy ?

Like, telling mpv to set up a video mode that matches the video stream frame rate?

**Comment by Dudemanguy** [comment]
>Like, telling mpv to set up a video mode that matches the video stream frame rate?

You mean just paint at the same frame as the fps of the video? That's the default. See the `--video-sync` option in the manual.

**Comment by vanfanel** [comment]
Oh, I understand.

Well, thanks anyway. Seems that's not a bug really.
