### ISSUE TITLE
lib\libavfilter.a(vf_libplacebo.o):vf_libplacebo.:(.text+0x2754): undefined reference to `pl_log_create_273'

### ISSUE THREAD

**Issue by LigH-de** [mpv-player/mpv#11643]
### mpv version and platform versions

HEAD #7668361685
GCC 12.2
MSYS2 / MinGW on Windows 10

### Reproduction steps

Run [media-autobuild suite](https://github.com/m-ab-s/media-autobuild_suite) - also reported in [m-ab-s issue 2430](https://github.com/m-ab-s/media-autobuild_suite/issues/2430)

### Expected behavior

Successful compilation

### Actual behavior

```
G:/MABS/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: G:/MABS/local32/lib\libavfilter.a(vf_libplacebo.o):vf_libplacebo.:(.text+0x2754): undefined reference to `pl_log_create_273'
```

The current build of **local##\lib\libplacebo.a** contains a reference to `pl_log_create_274` instead.

### Log file

[logs.zip](https://github.com/mpv-player/mpv/files/11360085/logs.zip)

**Comment by Dudemanguy** [comment]
This is almost certainly just an issue with whatever media-autobuild suite does (mismatching ffmpeg versions?) and not actually an mpv build issue. Feel free to reopen if it's actually an mpv problem.
