### ISSUE TITLE
Slow download speed using yt-dlp and mpv

### ISSUE THREAD

**Issue by ulliss2015** [mpv-player/mpv#11644]
I am experiencing slow download speed when using yt-dlp and mpv to download videos from the internet. The download speed is significantly lower than my internet speed and the speed I can achieve when using only yt-dlp. I have ruled out issues with my computer and network, so I suspect the problem is with either yt-dlp or mpv. I have tried adjusting buffer settings and other options, but the download speed remains slow.

--demuxer-max-bytes=100MiB Do nothing

**Comment by ulliss2015** [comment]
![изображение](https://user-images.githubusercontent.com/37631333/235327959-9860201e-71f0-4131-9d5a-fd942fbb28b0.png)

**Comment by CounterPillow** [comment]
known issue, ffmpeg doesn't implement the range requests or whatever nonsense yt-dlp does to evade YouTube's throttling.

**Comment by ulliss2015** [comment]
That is, should I just wait until it is added to ffmpeg?  The funny thing is that some 10 minutes videos are long to fully load in seconds

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/issues/8655#issuecomment-1199733728

**Comment by ulliss2015** [comment]
Thank's
