### ISSUE TITLE
How to remove the video track information in audio-only playback?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#11645]
When playing an audio file with embedded cover art, mpv prints (a line similar to this) to terminal:

    Video --vid=1 [P] 'cover.jpg' (mjpeg 800x800 1.000fps) (external)

full output:

```
Playing: ~/music-track.flac
     Video --vid=1 [P] 'cover.jpg' (mjpeg 800x800 1.000fps) (external)
 (+) Audio --aid=1 (flac 2ch 44100Hz)
A: 00:03:26 / 00:03:26 (100%) Cache: 0.0s
```

How to always hide or remove the second `Video` line?

As noted in the title, also applies to audio-only playback, `--no-video`.

--- 

[a potentially related issue](https://github.com/mpv-player/mpv/issues/10440)

mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.3

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#options-cover-art-auto

**Comment by 07416** [comment]
@hooke007 Sorry, I didn't realize that the information relating to the embedded artwork still gets printed.

$ mpv --cover-art-auto=no --audio-display=no --no-config 01_Ghosts_I.flac

```
     Video --vid=1 [P] Media Rage JPG Image (mjpeg 1000x1000 1.000fps)
 (+) Audio --aid=1 (flac 2ch 44100Hz)
AO: [pipewire] 44100Hz stereo 2ch s16
(Paused) A: 00:00:00 / 00:02:48 (0%)
```

[01_Ghosts_I.zip](https://github.com/mpv-player/mpv/files/11833345/01_Ghosts_I.zip) ([track source](https://archive.org/details/nineinchnails_ghosts_I_IV))

**Comment by hooke007** [comment]
Pls read carefully.

> See --audio-display how to control display of cover art (this can be used to disable cover art that is part of the file).

**Comment by hooke007** [comment]
Because "it's impossible to remove the built_in tracks."
