### ISSUE TITLE
Is it a bug on Wayland that resize cursor does not appear at the border?

### ISSUE THREAD

**Issue by HubKing** [mpv-player/mpv#11646]
I am using Wayland Gnome. On other applications, the mouse cursor changes to the "resize cursor" when it is near the window border. However, on MPV, the mouse cursor never changes when it is near the border. It only changes when I click MPV near the window border. Is this an intentional design, or some sort of a bug of Wayland Gnome or MPV?

[resize.webm](https://user-images.githubusercontent.com/10900489/235358299-90c7e725-fd90-45f6-a109-bd39a320b31f.webm)

**Comment by Jj0YzL5nvJ** [comment]
That is the normal behavior when you use `--no-border`

https://i.imgur.com/NLYIkQ6.mp4

**Comment by HubKing** [comment]
> That is the normal behavior when you use `--no-border`

But I did not specify that. I have also just tried `mpv --force-window --idle --border`, but it was the same. Maybe border is not supported in Wayland Gnome. 

Is there a way to get the "resize cursor" near the edge areas of the mpv window, when it has no border? Because, currently, resizing is very difficult because I cannot decide whether the mouse is currently on the right position to initiate resizing (if it is inside of that area, window is dragged, if it is outside of the area, mpv loses focus).

**Comment by Dudemanguy** [comment]
GNOME doesn't support borders. There's nothing mpv can do about it. You can use `--wayland-edge-pixels-pointer` to increase the size of the inner border where a resize occurs.

**Comment by RalfJung** [comment]
For quite some time now I thought resizing is just impossible in mpv since the cursor never indicated resizing. If there is some way that the application can control which cursor is shown depending on where over the window it hovers (which other applications do), it would be great if mpv could do that.

**Comment by Jj0YzL5nvJ** [comment]
It depends on your desktop environment, in my example Xfce allows to resize borderless windows from the native menus. I don't know how it's in other environments.

**Comment by Dudemanguy** [comment]
>If there is some way that the application can control which cursor is shown depending on where over the window it hovers (which other applications do), it would be great if mpv could do that.

It's feasible with the cusor-shape protocol.
