### ISSUE TITLE
Fully hardware-accelerated thumbnail api support

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#11640]

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/6919 and more.

**Comment by Traneptora** [comment]
I'm not going to mark it a duplicate of an issue that itself was closed as "I won't implement it" by wm4 since it's still a valid feature request.

**Comment by hooke007** [comment]
So could we think the dev members changed their initial mind?

https://github.com/mpv-player/mpv/issues/3940#issuecomment-355507385

**Comment by Dudemanguy** [comment]
The chances of anyone actually implementing this is pretty low, but it's a valid feature request imo.

**Comment by GalaxySnail** [comment]
What happened here? Why is this issue closed?
