### ISSUE TITLE
How to 'sub-remove' all external tracks?

### ISSUE THREAD

**Issue by j1warren** [mpv-player/mpv#11641]
I have a made a function which scans and adds external subtitles from "Subs/video_name/" folder.

```
    mp.set_property_native("options/sub-auto", "all")
    mp.set_property('sub-file-paths', 'Subs/' .. mp.get_property('filename/no-ext'))
    mp.command("rescan-external-files")
```

But when I change the video file via PgDn button (nextfile.lua - uses `loadfile`) those subtitles stay with the new file.
How can I clean all those subtitles (cause I want to add subs from a folder "Subs/video_name2/" now)?

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/issues/9767#issuecomment-1022207724

**Comment by j1warren** [comment]
@guidocella there's nothing about clearing subs list on `loadfile`, right?

**Comment by guidocella** [comment]
If you set `sub-file-paths` in a hook they will be loaded without `rescan-external-files` and be removed when you change file.
