### ISSUE TITLE
Playback error with `autofit=40%` [vkQueueSubmit2: VK_ERROR_DEVICE_LOST]

### ISSUE THREAD

**Issue by Rafee-M** [mpv-player/mpv#11658]
### Important Information

Provide following Information:
- mpv version 0.35.0-375-g6d422b3e
- Windows Version 10
- Source of the mpv binary [shinchiro on SourceForge](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/)
- If known which version of mpv introduced the problem N/A
- Possible screenshot or video of visual glitches

![image](https://user-images.githubusercontent.com/69535896/235807678-1fb09359-d60a-4586-8631-63af4eb2024d.png)

### Reproduction steps

1. Playing a 9:16 video with `autofit=40%`
2. Screen goes black for a while

### Expected behavior

Normal video playback

### Actual behavior

Video is just a black screen and audio plays back with error.

### Log file
[logmpv.txt](https://github.com/mpv-player/mpv/files/11378358/logmpv.txt)
![image](https://user-images.githubusercontent.com/69535896/235808403-492a2899-9852-4f59-a521-d1769e6eeb6a.png)

**Comment by Rafee-M** [comment]
As `autofit=40%` seems to be the issue, can it be ignored for videos with specific aspect ratios?

**Comment by Rafee-M** [comment]
Fixed with `autofit=70%`

```[Vertical Video]
profile-cond=width <= 960
autofit=70%
```

**Comment by Dudemanguy** [comment]
Well that's a workaround but that doesn't mean this bug is actually fixed. This shouldn't happen clearly.

**Comment by kasper93** [comment]
Please provide log when it actually happens and with `-v -v` or `--log-file=output.log`

**Comment by Rafee-M** [comment]
> Please provide log when it actually happens and with `-v -v` or `--log-file=output.log`, we don't even know what hardware you are running.
I had attached the log file 
[logmpv.txt](https://github.com/mpv-player/mpv/files/11378358/logmpv.txt)

**Comment by Rafee-M** [comment]
Update: The issue might be with the video file

### Error:
The same error happens when going into fullscreen (autofit disabled)

### Cause: 
Shader: NVScaler.glsl (Removing it solves it)

Reason for error:

The [video ](https://user-images.githubusercontent.com/69535896/235807895-24a69a29-8e1f-4133-8948-10a934506a5c.mp4)metadata shows it as 1280x720, where in fact it is 720x1280

Handbrake identifies it as 720x1280, but even though the aspect ratio in windowed playback in mpv is correct, checking the video information shows it as 1280x720. I'm saying this because there are no errors after compressing the video in Handbrake with same video encoding
Maybe because of this mismatch mpv errors out in fullscreen with NVScaler.glsl or with `autofit`

### Relevent files:

#### Handbrake
![image](https://user-images.githubusercontent.com/69535896/236230826-8fdab8b0-932c-4e81-bad4-d2acb896537e.png)
#### File Explorer:
![image](https://user-images.githubusercontent.com/69535896/236231129-53a6786c-f98f-442d-812a-9da0955de36b.png)

#### mpv:
![image](https://user-images.githubusercontent.com/69535896/236231263-3d0cb68f-efe5-4362-8e36-fbc44a881122.png)
