### ISSUE TITLE
Where are the videos from url downloaded ? 

### ISSUE THREAD

**Issue by Bowarc** [mpv-player/mpv#11651]
While using mpv and giving it youtube urls from command line, i found that my disk drive is getting filled fast (was playing long videos)
This means that mpv downloads and save the videos somewhere ?
i just can't find the path.

im on W10
i checked appdata, videos, documents, researched whole drive with video name as key, can't find anything.

Is mpv saving the downloaded files ? and if so, where ?

**Comment by CounterPillow** [comment]
No, mpv doesn't save videos anywhere, they're downloaded to memory.

If something was filling your disk drive it wasn't mpv.

**Comment by ZaquL** [comment]
>line, i found that my disk drive is getting filled fast (was playing long videos)

Turn off page file.

>No, mpv doesn't save videos anywhere, they're downloaded to memory.

Page file is still a real file on SSD.

**Comment by CounterPillow** [comment]
You should not turn off swapping. And by default, the mpv cache is limited to 150 megs, which wouldn't explain his disk filling up.

**Comment by ZaquL** [comment]
I said page file, that would be windows, and yes, there are less programs
on windows that will hate absent page file.
