### ISSUE TITLE
Building ffmpeg for mpv

### ISSUE THREAD

**Issue by akczht** [mpv-player/mpv#11657]
Hi,

I was building mpv for macOS using homebrew and in homebrew ffmpeg built by default builds ffmpeg with all the useful possible build options for ffmpeg, I don't want my mpv to encode media, but for building mpv I didn't want all those options, are there any required set of ffmpeg build options that I should always keep enabled no matter what. I build my ffmpeg just with aribb24 and dav1d support and nothing else, not even openssl, is it fine to have this much barebones ffmpeg for mpv? 

Thanks!

**Comment by Akczht** [comment]
Just to clarify, I will only be watching stuff in mpv and only offline media, so if there are ways to disable the online player, please! do tell.

**Comment by Traneptora** [comment]
Why would you want to disable random components of FFmpeg?

**Comment by Akczht** [comment]
to get a smaller app, eight now my mpv is around 28mb

**Comment by Akczht** [comment]
Yeah seems to me like that too, all the basic functionalities which I use like normal playback work fine.
