### ISSUE TITLE
Option to ignore reading of media 'title' metadata altogether in favour of 'filename' metadata

### ISSUE THREAD

**Issue by infantlogesh7x** [mpv-player/mpv#11653]
Hello,

I generally don't like using media title name since it only displays very little context or mostly the site URL or uploader name as title. It doesn't help me that much. 

> e.g. 'Episode01' ; 'S01E01' ; 'examplesite.com' ; 'uploader_name'

I have already made these changes in `mpv.conf` to not show video title in Window and Taskbar title.

```
script-opts='osc-title=${filename}' #MPV WINDOW NAME - shows filename instead of the title metadata
title='${filename} - mpv' #MPV TASKBAR NAME - shows filename instead of the title metadata
```
I use these 2 scripts with my mpv for my convenience, 
1. [autoload](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua)
2. [playlistmanager](https://github.com/jonniek/mpv-playlistmanager)

Since this commit, 34a04d056764f4f1447d39b60be56f02253831f8 (previously, 5ddf6d479e7a109db660b991ecf545653d284320, 048d4d8b7556f06afb46e7e94852709a1a624aed), the playlist items started displaying media 'title' again.

My request is to have an option to completely ignore reading 'title' metadata altogether in favour of 'filename' since it's easily editable. I _could_ remove the title metadata from the file manually, but it is not feasible for more than 2000 filenames.

**BEFORE**

![06 - PUBG Ninja Montage #8  U-9HjO2SsdI _1080p_00_00_40 267-01-min](https://user-images.githubusercontent.com/93128864/233855304-993ea09b-1457-4522-99ec-5705583bc756.png)

![The Boys (2019) - S03E06 - Herogasm (1080p BluRay x265 Silence)_00_30_16 440-03-min](https://user-images.githubusercontent.com/93128864/235565770-aebf6480-cd06-42b5-99f3-ae126b0f5482.png)

**AFTER**

![06 - PUBG Ninja Montage #8  U-9HjO2SsdI _1080p_00_00_40 267-03-min](https://user-images.githubusercontent.com/93128864/233855310-bd5eb85a-5dee-4256-aaaf-78311fd4be87.png)

![The Boys (2019) - S03E06 - Herogasm (1080p BluRay x265 Silence)_00_30_16 440-02-min](https://user-images.githubusercontent.com/93128864/235565784-c88ceb0c-5068-4512-b007-558682e9839a.png)

### Expected behavior of the wanted feature

1. Similar to `--force-media-title`, an option like `--ignore-media-title` or `--force-media-filename` will be helpful.

### Alternative behavior of the wanted feature

1. To display playlist items as `playlist/N/filename` when `title='${filename} - mpv'` or similar option is used.
2. Similar to `script-opts='osc-title=${filename}'`, an option like `script-opts='osc-playlist=${filename}'` will be helpful.

### Log file

none

Thank you.

**Comment by hooke007** [comment]
Shouldn't is it a script issue?

**Comment by dyphire** [comment]
I have the same issue and need an new option to revert original behavior.
![image](https://user-images.githubusercontent.com/61936050/235577465-47415b27-9fc0-41a6-a029-934cc77f89fd.png)

**Comment by sfan5** [comment]
What I think would be feasible is an option conceptually similar to `--display-tags` that controls which tags are read to set the media title.
This would not only fix the recent undesirable behaviour but also allow you to address the initial use case without having to set `osc-title` and `title` individually.
