### ISSUE TITLE
[vo/gpu-next/libplacebo] broken output when viewing image with very large dimensions

### ISSUE THREAD

**Issue by Touceire** [mpv-player/mpv#11663]
### Important Information
- mpv version
```
mpv 0.35.0-377-ga3eb1633 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Thu May 04 12:55:05 2023
libplacebo version: v5.264.0-228-g730d21a
FFmpeg version: N-110469-gad417eb5f
FFmpeg library versions:
   libavutil       58.6.100
   libavcodec      60.10.100
   libavformat     60.5.100
   libswscale      7.2.100
   libavfilter     9.7.100
   libswresample   4.11.100
```
- Windows Version
```
Microsoft Windows [Version 10.0.19045.2846]
```
- Source of the mpv binary
```
https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230504/mpv-x86_64-v3-20230504-git-a3eb163.7z
```
- Possible screenshot or video of visual glitches
![](https://0x0.st/HZ8w.png)
### Reproduction steps
```
mpv --no-config --vo=gpu-next 13.jxl
```
### Expected behavior
```vo=gpu-next``` should correctly display the image just like ```vo=gpu```.
### Actual behavior
```
[vo/gpu-next/libplacebo] Failed creating texture with emulated texture format: texture dimensions exceed maximum texel buffer size! Try again with a different (non-emulated) format?
[vo/gpu-next/libplacebo] Failed initializing plane texture!
[vo/gpu-next] Failed uploading frame!
[vo/gpu-next/libplacebo] Failed mapping frame id 0 with PTS 0.000000
```
### Log file
https://gist.githubusercontent.com/Touceire/cd9dc6305460861a8d4f608474258678/raw/05e46862e768a2670db3487f2c4cfa258910b06f/gpu-next.log
### Sample files
https://0x0.st/HZ8C.jxl

**Comment by Traneptora** [comment]
This has nothing to do with the input being a `.jxl` file, you can convert it to a PNG and reproduce the issue with the massive PNG.

**Comment by Dudemanguy** [comment]
I'm on amd. It just takes a long time for the image to open (apparently about 17 seconds), but it's fine on my end. No clue if it's helpful but here's my log file (`mpv --no-config --vo=gpu-next`).

https://0x0.st/HN8g.log

**Comment by kasper93** [comment]
I said in the MR that I will implement tiled upload when I have time™. But in generally libplacebo/mpv nominal usecase to view high res images.

**Comment by kasper93** [comment]
@Traneptora: Can you try with https://code.videolan.org/videolan/libplacebo/-/merge_requests/531 ? It should pass the upload fine now.

**Comment by Traneptora** [comment]
@kasper93 I tested `plplay` with https://code.videolan.org/kasper93/libplacebo/-/tree/texel_upload and it works, whereas git master plplay does not.

**Comment by kasper93** [comment]
@Traneptora Thanks.
