### ISSUE TITLE
Refresh/reload defected video

### ISSUE THREAD

**Issue by tunaflsh** [mpv-player/mpv#11672]
Sometimes when playing a video from a URL, it gets some fragments corrupted or skipped, leading to misalignment in audio and video streams or skipped frames.

Is there a way to refresh the video (continuing from the current timestamp), without restarting mpv?

### To Reproduce

1. Play a video from an URL
2. When audio and video streams misalign, restart mpv

### Expected behavior

A way to refresh cache or force yt-dlp to redownload video fragments without restarting mpv.

### Log file

no log files

**Comment by guidocella** [comment]
`write-watch-later-config; playlist-play-index current`

**Comment by tunaflsh** [comment]
It works, thank you!
