### ISSUE TITLE
Resume of playing after reawaken of PC from hibernation

### ISSUE THREAD

**Issue by MikeBossO** [mpv-player/mpv#11679]
Is there a command to **automatically** resume of playing RTSP live stream after waken of PC from hibernation state?

**Detailed description of situation:**
- I'm watching rtsp live stream in MPV
- Thanks to command `--osd-level=3` I see current playback status which is ▶ = playing and playing time is increasing = OK
- Then I turn PC into hibernate state
- I awaken PC and the MPV does not play video. Video is frozen and status of playing is ⏩ = Fast-Forwarding but timer is frozen also
![01](https://github.com/mpv-player/mpv/assets/71265128/bc370991-28d2-4ce5-a8bb-936fa731e29d)
- Resume of playing with SPACE button is not working but by pressing of ENTER (playlist-next) I will resume playing

**Is there way how to automatically resume of playing stream after awaken of PC from hibernation?**

I hope that it could be also helpful in case of some disconnection issue to source of the stream.

I have tried those commands but it didn't help
`--loop-file=inf` `--loop-playlist=inf` `--profile=low-latency`

**Comment by Traneptora** [comment]
Did you try `--loop-playlist=force`?

**Comment by MikeBossO** [comment]
> 

I have tried it now but result is exactly the same. It didn't help.
But thank you for your effort.

**Comment by MikeBossO** [comment]
> Did you try `--loop-playlist=force`?

I have tried it now but result is exactly the same. It didn't help.
But thank you for your effort.
