### ISSUE TITLE
[wayland] cursor size not respected

### ISSUE THREAD

**Issue by mattia-b89** [mpv-player/mpv#11671]
Inside the mpv window, cursor size is not respected and changes;  
I noticed this is a Wayland-only issue, not happening on X11;  

 - mpv 0.35.1
 - Arch Linux x86_64
 - GNOME 44
 - Wayland

Here is a screencast showing the issue:
[Screencast from 2023-05-07 22-24-36.webm](https://user-images.githubusercontent.com/545463/236701318-6c33d577-3421-4164-b13a-b52247005965.webm)
where the cursor become smaller as soon as it goes on.

### Reproduction steps
(Prerequisite: have a different cursor size)
Move the cursor in and out the mpv window in a Wayland environment;

### Expected behavior
Cursor should stay the same

### Actual behavior
Cursor's size changes to a default value

### Log file
Useless: no messages when moving the cursor

**Comment by Dudemanguy** [comment]
There's no sane way to handle this on wayland because cursors are stupid there. Use the `XCURSOR_SIZE` environment variable as a workaround.

**Comment by Dudemanguy** [comment]
Your compositor would need to support cursor-shape-v1 but that will give it complete control over the theme and size.

**Comment by teohhanhui** [comment]
Will this help? 🤔

https://gitlab.gnome.org/GNOME/mutter/-/issues/2633

**Comment by ruihe774** [comment]
> Will this help? 🤔
> 
> https://gitlab.gnome.org/GNOME/mutter/-/issues/2633

This: https://gitlab.gnome.org/GNOME/mutter/-/issues/3276
