### ISSUE TITLE
User-shaders: issue with sqrt()

### ISSUE THREAD

**Issue by garamond13** [mpv-player/mpv#11682]
### Important Information
- mpv 0.35.0-384-g8343b3bd, built on Fri May 12 12:36:34 2023
- Windows 10

### Config
dither-depth=no
hwdec=no
vo=gpu-next
gpu-api="any"
glsl-shaders-append="~~/test.glsl"

### Problem
I'm having issue with `sqrt()` where mathematically and as tested in a c++ sample, should produce exactly the same result or at least within margin of error, but its producing results way beyond margin of error. More specifically I'm talking about `sqrt(2.0 / (M_PI * x))` and `sqrt(2.0 / M_PI / x)` in this function: `#define J1(x) (x < 2.293115733230086 ? (x / 2.0) - (x * x * x / 16.0) + (x * x * x * x * x / 384.0) - (x * x * x * x * x * x * x / 18432.0) : sqrt(2.0 / (M_PI * x)) * (1.0 + 3.0 / (16.0 * x * x) - 99.0 / (512.0 * x * x * x * x)) * cos(x - 3.0 * M_PI_4 + 3.0 / (8.0 * x) - 21.0 / (128.0 * x * x * x)))`. User shader used for testing is Jinc (https://github.com/garamond13/Jinc). Differences are visually very noticeable and the psnr between the same image upscaled 2 times with both `sqrt(2.0 / (M_PI * x))` and `sqrt(2.0 / M_PI / x)` is 37.4621. Now when I change `1.0 + 3.0 / (16.0 * x * x)` into `1.0 + 3.0 / 16.0 / (x * x)` in the above `J1()` psnr is 88.6676. Also I'm getting same issue with `pow(2.0 / (M_PI * x), 0.5)` and `pow(2.0 / M_PI / x, 0.5)`.

### Maybe important, maybe not
Test image was encoded into .mp4 4:4:4.
Used shader was jincUpscaleLuma.glsl.
Settings were: power of blackman a=-0.4 n=0.5, radius=2.7, blur=0.9, ar=1.0, contrast=6.0, midpoint=0.6

**Comment by haasn** [comment]
Smells like order of operations / macro expansion issue.

Use functions, not macros.

**Comment by garamond13** [comment]
Tested with the function both `sqrt(2.0 / (M_PI * x))` and `sqrt(2.0 / M_PI / x)`, inside the function are producing same or within margin of error results as the macro with `sqrt(2.0 / (M_PI * x))`.

The function:
`float J1(float x)
{
    if (x < 2.293115733230086)
        return (x / 2.0) - (x * x * x / 16.0) + (x * x * x * x * x / 384.0) - (x * x * x * x * x * x * x / 18432.0);
    else
        return sqrt(2.0 / (M_PI * x)) * (1.0 + 3.0 / (16.0 * x * x) - 99.0 / (512.0 * x * x * x * x)) * cos(x - 3.0 * M_PI_4 + 3.0 / (8.0 * x) - 21.0 / (128.0 * x * x * x));
}`

I think this should be considered a bug.

### Logs
[function_2_(pi_x).log](https://github.com/mpv-player/mpv/files/11470244/function_2_.pi_x.log)
[function_2_pi_x.log](https://github.com/mpv-player/mpv/files/11470245/function_2_pi_x.log)
[macro_2_(pi_x).log](https://github.com/mpv-player/mpv/files/11470246/macro_2_.pi_x.log)
[macro_2_pi_x.log](https://github.com/mpv-player/mpv/files/11470247/macro_2_pi_x.log)

**Comment by garamond13** [comment]
Think I figured what is going on.
The macro with `sqrt(2.0 / M_PI / x)` will translate the sqrt() into `sqrt(0.18237812817096710205078125f / _595)` and the macro with `sqrt(2.0 / (M_PI * x))` will translate it into `sqrt(0.2251581847667694091796875f * _594)`. The reason why is because the macro is called with `J1(M_PI / B * x)` which will probably be translated into `sqrt(2.0 / M_PI / M_PI / B * x)` and `sqrt(2.0 / (M_PI * M_PI / B * x))` respectively. Now if we do calculations with actual parameters we get `2.0 / pi / pi / 0.9 * x = 0.22515818587186171432 * x` and `2.0 / (pi * pi / 0.9 * x) = 2.0 / (pi * pi / 0.9) / x = 0.1823781305562079886 / x` . 

Now if I put `x` into brackets I get correct results, so `sqrt(2.0 / M_PI / (x))`.

**Comment by haasn** [comment]
That's why I advised to use functions, it avoids such issues. You're also potentially double-evaluating if the compiler isn't smart enough to eliminate common subexpressions.
