### ISSUE TITLE
Support Ctrl+Q to quit

### ISSUE THREAD

**Issue by PanderMusubi** [mpv-player/mpv#11686]
### Important Information

Provide following Information:
- mpv version: 0.34.1-1ubuntu3
- Linux Distribution and Version: Ubuntu 22.04 LTS
- Source of the mpv binary: this repo

### Reproduction steps

Start a movie in MPV and have the focus on the window showing the movie and press `Ctrl+q`.

### Expected behavior

Quit the application, see also https://developer.gnome.org/hig/reference/keyboard.html

### Actual behavior

Application doesn't quit but reports `[input] No key binding found for key 'Ctrl+q'.`

Work around is `Ctrl+c`, which is okay when interacting with the command line terminal mpv is started from. However, from the movie player window, `Ctrl+q` is more appropriate.

### Log file

n/a

### Sample files

n/a

**Comment by quietvoid** [comment]
Just `q` also works.

**Comment by PanderMusubi** [comment]
Ah, okay, thanks. But since most applications work with `Ctrl+q` I hope that can get supported as users expect that to work.

**Comment by avih** [comment]
> Support Ctrl+Q to quit

It's supported, just not enabled by default.

You can do that by adding to your [`input.conf`](https://mpv.io/manual/master/#input-conf):
```
ctrl+q quit
```

You might need to first add this file. See also [FIles](https://mpv.io/manual/master/#files).

**Comment by PanderMusubi** [comment]
Thanks, that works. However, for less-technical users it is perhaps a bridge too far. I'm fine if you don't want to enable this by default. In that case, would it be more appropriate I ask Debian/Ubuntu packagers to support this?

**Comment by N-R-K** [comment]
> for less-technical users it is perhaps a bridge too far

If editing a text file is too difficult for someone, then they won't really have a good time with mpv. Almost entirety of mpv's configuration is done via text files.
