### ISSUE TITLE
What configuration loads subtitle files

### ISSUE THREAD

**Issue by PanderMusubi** [mpv-player/mpv#11687]
When using the following (often used) way for naming directories and files, is it possible to configure mpv to load subtitle files automatically?

    Videos/Movies/Example.2023.1080p.H264/
        Example.2023.1080p.H264.mp4
        Example.2023.1080p.H264.nfo
        Example.2023.1080p.H264.Spanish.srt
        Example.2023.1080p.H264.English.srt

Currently, I use a shell script from the directory `Movies` with e.g. the argument `Example.2023.1080p.H264`

    cd $1
    BASE=$(basename "$PWD")
    mpv $BASE.m?? --sub-files=$BASE.Spanish.srt:$BASE.English.srt --secondary-sid=2

Is there a way to configure mpv that simply running it directly on the movie file will load these two external subtitle files?

**Comment by guidocella** [comment]
`--sub-auto=fuzzy`

**Comment by PanderMusubi** [comment]
Thanks! I've implemented it in `~/.bash_aliases` as

    alias mpvdual='mpv --sub-auto=fuzzy --sid=2 --secondary-sid=1'

in order to get English at the top and the other language at the bottom.

**Comment by PanderMusubi** [comment]
Or add to `~/.config/mpv/mpv.conf`

    sub-auto=fuzzy
    sid=2
    secondary-sid=1

This will also work on the Android version of MPV
