### ISSUE TITLE
Does the built-in stats script cause frame drops?

### ISSUE THREAD

**Issue by timeday1102** [mpv-player/mpv#11688]
### Important Information

Provide following Information:
- mpv 0.35.0
- win10 22H2
- installed by scoop(extras/mpv-git)

### Actual behavior
Does the built-in stats script cause frame drops? 
If I use key ‘I’ to display statistics permanently, dropped frames keep slowly increasing. 
If I don't use the key 'I' or use key 'i' every 10 minutes to display statistics  for a short time, the dropped frames will not increase or only increase by 1.
So, does the built-in stats script cause frame drops? 

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/11471120/log.txt)

**Comment by CounterPillow** [comment]
It can, if your CPU isn't very fast at rendering ASS subtitles.

**Comment by timeday1102** [comment]
> It can, if your CPU isn't very fast at rendering ASS subtitles.

I used Intel 8700 cpu，is the performance of this CPU no longer enough?

**Comment by Dudemanguy** [comment]
It depends on your hardware, configuration, the video you're playing, etc. but yes rendering the stats every frame is a performance hit. It's perfectly possible for you to be able to play video smoothly with it off but for things to go whack if you have it permanently displayed;

**Comment by timeday1102** [comment]
> I only have this problem when using display-sync

I used 'video-sync=audio' property

**Comment by timeday1102** [comment]
> It depends on your hardware, configuration, the video you're playing, etc. but yes rendering the stats every frame is a performance hit. It's perfectly possible for you to be able to play video smoothly with it off but for things to go whack if you have it permanently displayed.

Thank you for answering this question.
