### ISSUE TITLE
Not sure if its an issue, but is there a way to reconnect on a lan-hosted file?

### ISSUE THREAD

**Issue by Battler624** [mpv-player/mpv#11692]
I will preface this saying that I dont have a log, I'll make one if needed but by manually recreating the problem.

The issue I am facing is that when I connect to my [laptop via windows explorer and launch a video that is on that laptop](https://i.imgur.com/mJBLjJ4.png), if by any chance that the connection between me and the laptop gets servered by any chance, the video played no longer continues past what is cached.

Is there a solution to this? is there a command line that force reconnections?

Edit more information
laptop on Win10 LTSC
PC (that I watch from) Win11 
MPV version 0.35.0-67-gad65c8855b

**Comment by Dudemanguy** [comment]
There's no direct way to try to reconnect. You might be able to script together something although I don't know if it'll result in the behavior you want.
