### ISSUE TITLE
In full screen state, the screen flickers when hiding and showing the UI

### ISSUE THREAD

**Issue by Pulck** [mpv-player/mpv#11695]
- mpv 0.35.1
- macOS 13.3.1

if the hidden view uses a self-built CALayer, the screen will flicker when  NSView.isHidden = true
if using NSView's self-generated layer, the screen flickers only when NSView.isHidden = false

**Comment by Akemi** [comment]
i am really not sure what you are reporting here? are you having a problem with mpv or with libmpv? if the latter and mpv doesn't have the problem it's either a problem on your end or macOS.

anyway you ignored the issue template so closing. please report a new issue if this problem still perssist and fill out the issue template properly.
