### ISSUE TITLE
AAC length not detected properly

### ISSUE THREAD

**Issue by superbonaci** [mpv-player/mpv#11697]
### Expected behavior
Be able to detect file length, which is 13:20.3

### Actual behavior
Is detected but not accurately, like 00:12:36

### Log file

https://gist.github.com/superbonaci/d4b023e9597b20175d1371ddbd3ad437

### Sample files

https://0x0.st/HN5K.aac/fools-the-north-wind.aac

**Comment by CounterPillow** [comment]
I mean, it says right there on the console:
> [ffmpeg/demuxer] aac: Estimating duration from bitrate, this may be inaccurate

nothing that can really be done, use a proper container for your audio stream and this won't be an issue.

**Comment by superbonaci** [comment]
New file link:
[fools-the-north-wind.aac.zip](https://code.videolan.org/videolan/vlc/-/issues/28157)
