### ISSUE TITLE
Measure aspect ratio of actual video in the 16:9 window.

### ISSUE THREAD

**Issue by pbiancardi** [mpv-player/mpv#11696]
I am trying to setup MPV for use with a 1.33 anamorphic lens and scope screen.

To do this I need to vertically stretch a scope film to fill the 16:9 picture, this is possible with MPV using video-scale-y=1.33.

I would like to automatically apply video-scale-y=1.33 whenever the actual aspect ratio of a film is greater than 2.00.

I tried this but this only reads the aspect ratio of 1.78 because Blu Ray / UHD is always 1.78 even if the actual film is 2.39 (black bars are included in the reported AR so its always 1.78).

[AnamorphicLens] 
profile-cond = get("video-params/aspect") >= 2 # if aspect ratio >= 2 active the profile 
profile-restore=copy
video-scale-y=1.33

Is there a way that I can replace video-params/aspect with something else that reads the actual films AR instead of just reporting 1.78 all the time?

**Comment by guidocella** [comment]
`profile-cond=width / height >= 2`

**Comment by pbiancardi** [comment]
> profile-cond

Doesn't seem to work, how would I write that into file?

Trying this - 

[Anamorphic Lens]
profile-desc=Engage Anamorphic Lens 
profile-cond=width / height >= 2
profile-restore=copy
video-scale-y=1.33

**Comment by pbiancardi** [comment]
I believe I have figured this out using dynamic-crop.lua

script-opts-append=dynamic_crop-ratios=2.4 2.39 2.35 2.2
script-opts-append=dynamic_crop-new_fallback_timer=0
d3d11va-copy
