### ISSUE TITLE
MPV crashes when using "gpu-next" with Anime4K-GAN shader

### ISSUE THREAD

**Issue by Ptilopsis01** [mpv-player/mpv#11702]
### Important Information

Provide following Information:
- mpv version 0.35.1
- Windows Version win11 22621.1776
- Source of the mpv binary Windows builds by shinchiro
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

### Reproduction steps
add anime4k shaders into the shaders folder
input the code in mpv.conf like below:
```
vo=gpu-next

[profile-low_resolution]
profile-desc=low_resolution
profile-cond=((p["video-params/w"]<1280 and p["video-params/h"]<800) and (p["video-params/w"]>=640 or p["video-params/h"]>=400))
glsl-shaders-clr
glsl-shaders-append="~~/shaders/KrigBilateral.glsl"
glsl-shaders-append="~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_UL.glsl"
glsl-shaders-append="~~/shaders/Anime4K_Restore_GAN_UUL.glsl"
glsl-shaders-append="~~/shaders/Anime4K_AutoDownscalePre_x4.glsl"
glsl-shaders-append="~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_VL.glsl"
glsl-shaders-append="~~/shaders/Anime4K_Clamp_Highlights.glsl"
```
then open a video(480p to trigger the shader) with mpv, and zoom it into fullscreen(large enough), mpv will soon crash.
### Expected behavior
anime4k-GAN shaders can be used in mpv with gpu-next
### Actual behavior
mpv crashes
I'm not sure whether it is the problem of mpv or anime4k
### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/11521751/mpv.log)
[mpv.log](https://github.com/mpv-player/mpv/files/11521820/mpv.log)
here are two different logs
### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Ptilopsis01** [comment]
update: I've found that mpv would crash if there's anime4k_restore shader in use, no matter whether it is GAN.

**Comment by haasn** [comment]
Can you confirm that this crashes for you?

```bash
mpv --no-audio --no-config --vo=gpu-next --glsl-shader=Anime4K/glsl/Restore/Anime4K_Restore_GAN_UUL.glsl FILE.mkv
```

It doesn't for me.

**Comment by Ptilopsis01** [comment]
> Can you confirm that this crashes for you?
> 
> ```shell
> mpv --no-audio --no-config --vo=gpu-next --glsl-shader=Anime4K/glsl/Restore/Anime4K_Restore_GAN_UUL.glsl FILE.mkv
> ```
> 
> It doesn't for me.

It didn't crash when starting with this code, but it crashes with the code I gave above when zoomed into fullscreen

**Comment by Jules-A** [comment]
About 3 weeks ago when I last tried gpu-next I was getting instant crashes when using 'glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_UL.glsl;~~/shaders/Anime4K_Restore_CNN_Soft_UL.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_UL.glsl"' Haven't tested since then though.

**Comment by Ptilopsis01** [comment]
> You can try `gpu-context=winvk`

It also crashes...

**Comment by Jules-A** [comment]
https://github.com/mpv-player/mpv/issues/11702#issuecomment-1555922281 Shaders no longer crash for me and neither do the ones in OP.

**Comment by Traneptora** [comment]
Seems fixed?

**Comment by Ptilopsis01** [comment]
> Seems fixed?

Actually not, it still happens in my device

**Comment by kasper93** [comment]
Could you provide crash dump from `%LOCALAPPDATA%\CrashDumps`? Please use build from https://github.com/zhongfly/mpv-winbuild/releases and note which one exactly you used, so we can match debug symbols.

**Comment by Ptilopsis01** [comment]
> Could you provide crash dump from `%LOCALAPPDATA%\CrashDumps`? Please use build from https://github.com/zhongfly/mpv-winbuild/releases and note which one exactly you used, so we can match debug symbols.

It didn't crash any more after I update mpv into the latest release in the link, thanks a lot

**Comment by Jules-A** [comment]
> It didn't crash any more after I update mpv into the latest release in the link, thanks a lot

Huh? Are you sure you tested a newer Shinchiro build from after my post ~2 weeks ago when I noted that it was fixed for me? Does it still crash with Shinchiro's builds for you?
