### ISSUE TITLE
Pan and Scan mode for 2.35:1 videos cuts subtitles in half on phone display?

### ISSUE THREAD

**Issue by Pentaphon** [mpv-player/mpv#11705]
On a phone, when I enable pan and scan mode to zoom in on 2.35.1 videos in 16:9 ratio with black bars, I can only see half the subtitles. How do I fix this with mpv.conf? Or is this not intended?

Related issue on mpv-android project: https://github.com/mpv-android/mpv-android/issues/679

**Comment by llyyr** [comment]
use `--sub-ass-force-margins=yes` in mpv.conf
