### ISSUE TITLE
Verify name of 3dlut MPV is using?

### ISSUE THREAD

**Issue by pbiancardi** [mpv-player/mpv#11719]
I have (2) different projectors (330 and 660) with different calibration 3dluts and I want to switch between them with profiles and keyboard shortcuts but want to verify the correct 3dlut is being used.  Is there a way to display the name of the 3dlut onscreen?

Alternatively can anyone verify this would be correct.

In mpv.conf I have -

[660]
profile-restore=copy-equal
video-zoom= -0.100
video-pan-x= 0.0
video-pan-y= -0.04
lut=C:\cal\660 Resolve.cube
lut-type=native
[default]

lut=C:\cal\330 Resolve.cube
lut-type=native

In this case will the "330 Resolve.cube" be loaded as default and then switch to "660 Resolve.cube" when 660 profile is active?

Input.conf I have this -

3                   apply-profile 660 restore
4                   ignore
5                   ignore
6                   apply-profile 660

Expected behavior is that when I press 6 the 660 lut is loaded and then when I press 3 it goes back to default 330, is this correct?

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/11518

**Comment by Dudemanguy** [comment]
Should be fixed by 85e84f6d9202c8f24def535a6aa78994c0223298
