### ISSUE TITLE
--gpu-context=waylandvk doesn't play video/audio

### ISSUE THREAD

**Issue by Gigas002** [mpv-player/mpv#11711]
### Important Information

mpv version:

```zsh
mpv 0.35.0-396-ga1a2e27f84 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Tue May 23 10:02:25 2023
libplacebo version: v5.264.0-257-g5fc27c80
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```

linux destribution and version:

```zsh
Operating System: Manjaro Linux
Kernel: Linux 6.3.3-x64v3-xanmod1
Architecture: x86-64
```

source of mpv binary: mpv-git from AUR: https://aur.archlinux.org/packages/mpv-git/

DM: wayland, KDE Plasma 5.27.5

dGPU: NVIDIA GeForce RTX 3060 Laptop; proprietary nvidia driver 530.41.03

iGPU: amdgpu, mesa 23.0.3 (*should I tell `mesa` version when it comes to integrated amdgpu?*)

### Reproduction steps

```sh
mpv video.mp4 --gpu-context=waylandvk --no-config -log-file=noprime_waylandvk.txt
```

or

```sh
prime-run mpv video.mp4 --gpu-context=waylandvk --no-config -log-file=prime_waylandvk.txt
```

### Expected behavior

Video/audio plays

### Actual behavior

Errors and nothing happens.

For `prime-run` version:

```sh
[vo/gpu/wayland] Error occurred on the display fd, closing
```

For just `mpv` version:

```sh
[vo/gpu/libplacebo] vk->CreateSwapchainKHR(...): VK_ERROR_INITIALIZATION_FAILED (../libplacebo/src/vulkan/swapchain.c:615)
[vo/gpu/libplacebo] Failed (re)creating swapchain!
[vo/gpu/libplacebo] vk->CreateSwapchainKHR(...): VK_ERROR_INITIALIZATION_FAILED (../libplacebo/src/vulkan/swapchain.c:615)
[vo/gpu/libplacebo] Failed (re)creating swapchain!
```

At first I noticed the #10552 and thought it's the same error, so I wasn't going to open a new issue. However, while I was trying to configure my wayland session to run on dGPU instead of iGPU I noticed, that the error is changing, so I tried to force-run `mpv` on nvidia gpu with `prime-run` and see the results.

As I said, both attempts fails, but the errors differs. Logs below.

`wayland`, `x11` and `x11vk` works as expected.

### Log file

iGPU (amdgpu): [noprime_waylandvk](https://0x0.st/Hqar.txt)
dGPU (nvidia): [prime_waylandvk](https://0x0.st/Hqas.txt)

**Comment by llyyr** [comment]
Try specifying the device with `mpv --vulkan-device=help`

**Comment by Dudemanguy** [comment]
Looks like it's just upstream since vkcube doesn't work either (https://github.com/NVIDIA/open-gpu-kernel-modules/issues/317). Seems to be dual GPU specific.

**Comment by llyyr** [comment]
PRIME doesn't affect mpv vulkan device selection, in both cases the Nvidia devices is selected so you have to explicitly specify the AMD one

**Comment by rothn** [comment]
This may be a driver issue. I had this after installing an AMD GPU, but after installing the Vulkan drivers, video plays now. See: https://wiki.archlinux.org/title/AMDGPU

**Comment by Gigas002** [comment]
Yeah, I think it was indeed a problem with drivers (nvidia ones in my case). At some point of time it got fixed and now works flawlessly.
