### ISSUE TITLE
not possible to select proper audio stream

### ISSUE THREAD

**Issue by Mi605** [mpv-player/mpv#11713]
### Issue description:

MPV audio stream selection on playback of an multilingual mediathek live stream, fails. It comes up with foreign language stream always, no way to select the proper stream.

### Important Information

Provide following Information:
- mpv version
```
$ mpv --version
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.2-3

```
- Linux Distribution and Version
antiX 23

```
$ lsb
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Codename:	bookworm

$ uname -a
Linux test 6.1.18-antix.1-amd64-smp #1 SMP PREEMPT_DYNAMIC Sat Mar 11 19:13:33 EET 2023 x86_64 GNU/Linux
```
(also: antiX 22 and 21, both debian bullseye based.)

- Source of the mpv binary
```
$ apt-cache policy mpv
mpv:
  Installed: 0.35.1-4
  Candidate: 0.35.1-4
  Version table:
 *** 0.35.1-4 500
        500 http://ftp.de.debian.org/debian bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
```

### Reproduction steps

Check the audio and video streams available first:
```
$ yt-dlp -F 'https://www.ardmediathek.de/live/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw/'
[ARDBetaMediathek] Extracting URL: https://www.ardmediathek.de/live/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw/
[ARDBetaMediathek] Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw: Downloading JSON metadata
[ARDBetaMediathek] 36089960: Downloading m3u8 information
WARNING: [ARDBetaMediathek] Ignoring subtitle tracks found in the HLS manifest; if any subtitle tracks are missing, please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[info] Available formats for 36089960:
ID                              EXT RESOLUTION FPS │   TBR PROTO │ VCODEC        VBR ACODEC     MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
hls-program_audio-Deutsch       mp4 audio only     │       m3u8  │ audio only        unknown    [de] Deutsch
hls-program_audio-Klare_Sprache mp4 audio only     │       m3u8  │ audio only        unknown    [de] Klare Sprache
hls-program_audio-Original      mp4 audio only     │       m3u8  │ audio only        unknown    [mul] Original
hls-910                         mp4 480x270     50 │  911k m3u8  │ avc1.4d401e  911k video only
hls-1460                        mp4 640x360     50 │ 1461k m3u8  │ avc1.4d401f 1461k video only
hls-1900                        mp4 960x540     50 │ 1901k m3u8  │ avc1.4d401f 1901k video only
hls-3660                        mp4 1280x720    50 │ 3661k m3u8  │ avc1.640020 3661k video only
hls-5640                        mp4 1920x1080   50 │ 5641k m3u8  │ avc1.64002a 5641k video only

```

As you can see, there are three audio streams and five video streams available.

Now start mpv playback of this live stream:

```
$ mpv --no-config 'https://www.ardmediathek.de/live/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw/'
EDL: source file 'https://mcdn.one.ard.de/ardone/hls/master-original.m3u8' has unknown duration.
EDL: source file 'https://mcdn.one.ard.de/ardone/hls/master-1080p-5000.m3u8' has unknown duration.
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
AO: [alsa] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: 10:35:35 / 10:35:37 (100%) A-V: -0.000 Cache: 1.6s/1MB

Exiting... (Quit)
```

From the output you can see, MPV recognises only a single audio (and video) stream. Trying to switch the audio to the proper language fails, you can only select between `"none"` and `"1/1 [unknown]"`. MPV always selects the foreign language audio stream automatically (called `„[mul]”` or `„hls-program_audio-Original”` in the yt-dlp stream table above.)

### Expected behavior

All audio streams provided by the station should be selectable using e.g. the `#` shortcut to cycle through the audio streams.

### Actual behavior

You can only switch between `Audio: no` and `Audio (1) unknown` while there are actually three audio streams.
This is even worse since MPV automatically selects the foreign language stream always for some strange reason.

### Log file

Make a log file made with -v -v or --log-file=output.txt...

[log.txt](https://github.com/mpv-player/mpv/files/11558376/log.txt)

### Sample files

./.

**Comment by christoph-heinrich** [comment]
[`--script-opts=ytdl_hook-all_formats=yes`](https://mpv.io/manual/master/#options-all-formats)

**Comment by Mi605** [comment]
@Traneptora The issue is not resolved at all, so please reopen it. Please see details below.

@christoph-heinrich  Many thanks for your proposals. I've checked the first proposal meanwhile, and generally it works on playback, while it fails completely while recording. Moreover the MPV manpage reads clearly:

> Although this mechanism makes it possible to switch streams at runtime, it's not suitable for this purpose for various technical reasons. (It's slow, which can't be really fixed.) In general, this option is not useful, and was only added to show that it's possible.

The manual is true. This command stops playback for at least half a minute on each audio stream change, and then comes back with audio and video out of sync, taking another half minute to resync A-V again. This way you simply can't cycle through all 24 audio streams some programs in the station's huge mediathek  provide, to get the proper language.

And what it is even worse: The recording to a file fails completely with this, it writes a zero bytes file as soon this option is added. Try:
```
$ mpv --script-opts=ytdl_hook-all_formats=yes --stream-record='./test.ts' 'https://www.zdf.de/sender/zdfneo/zdfneo-live-beitrag-100.html'
```
While without this MPV plays and records the wrong language, as initially stated (but the file itself is written fine) :
```
$ mpv --stream-record='./test.ts' 'https://www.zdf.de/sender/zdfneo/zdfneo-live-beitrag-100.html'
```

So this proposed solution turned out to be nonfunctional.

The second option from your proposals actually comes up with the proper language if you can manage to use the proper stream combinations in the command. You'll have to look up the stream in yt-dlp using its F option beforehand. The great drawback: You can't switch the language once MPV playback is running. Example:

```
mpv --ytdl-raw-options=format='hls-3660+hls-program_audio-Deutsch' 'https://www.ardmediathek.de/live/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw/'

```

What makes it fail here is the fact, that this renders drag and drop of the URL to the MPV screen after GUI startup completely nonfunctional, it always comes up with the wrong language of a stream, without any chance to switch it.

So also this proposed solution is nonfunctional.

The third one using the external script was the one which took me some time to figure out how to make it work. But once set up, it looked very promising. After creating an mpv.conf file containing the line `osc=no` it was actually possible to switch the language on the fly in the GUI, and the playback doesn't go out of sync for a minute, it just pauses for a second or two and goes on with the new language. So this is actually the best proposal. Unfortunately it fails also horribly when the recording functionality is used: On each language switch the already written output file is deleted and starts writing from the size of zero bytes again. So if you have to switch the language due to a language switch of the audio stream the station transmits (remember, some of the streams read „[mul]”, meaning „multilingual”), you'll lose all your recording from before. You can observe in file manager the file goes from e.g. 1,3 GiB to 0 Bytes the very moment you have to switch the language.

So also the third proposed solution is nonfunctional.

My next approach to use the `--alang=` option failed completely, even when there are language flags like [de] or [mul] present for some streams.

Let me remind you: Users not familiar with command line operation, just able to drag and drop an URL to the MPV screen, as it reads when starting, simply can't do all the console stuff I have checked out.

Please fix the way MPV deals with these multilingual streams, they are meanwhile most common today, and the current behaviour is simply what I'd call a bug.

**Comment by Traneptora** [comment]
> Let me remind you: Users not familiar with command line operation, just able to drag and drop an URL to the MPV screen, as it reads when starting, simply can't do all the console stuff I have checked out. Please fix the way MPV deals with these multilingual streams, they are meanwhile most common today, and the current behaviour is simply what I'd call a severe bug.

mpv is a command-line media player. I fail to see how a CLI tool requiring the CLI is a bug. Also a "severe" bug is something like a crash or security issue, not the wrong language audio showing up when someone doesn't provide the options required to make the right language show up.

**Comment by christoph-heinrich** [comment]
Why do you want to switch audio streams while recording?

You could try using [`dump-cache`](https://mpv.io/manual/master/#command-interface-dump-cache) because with that you can then stop the recording before switching streams (or use a different filename the second time around) to keep the file instead of overwriting it. You could even make a script to make that process easier if it's something you do often.

`alang` didn't work because it's used for selecting audio tracks, but without setting `all_formats=yes` for the ytdl_hook, there is only one audio track, which gets selected by yt-dlp from all the available audio formats. You'll have to coerce yt-dlp to select your language of choice. You can pass options to it via [`--ytdl-raw-options`](https://mpv.io/manual/master/#options-ytdl-raw-options), or by setting them in the config file of yt-dlp (usually in `~/.config/yt-dlp/config`).

FYI the way that script works is by setting `ytdl-format`, then restarting the current playlist item and seeking to the current playback time. I'm not surprised that doesn't work nicely with recording.

I don't know if there is any way of making switching streams and recording work well together.
When `all_formats=yes` is used, the audio streams are added as tracks in a way where the streams are not opened unless you switch to them. To change that you would have to save the `ytdl_hook.lua` to your script directory, use `--no-ytdl` to prevent the builtin ytdl_hook from being loaded, and then modify that lua file so that it doesn't lazily open those streams. That can be done by removing the `delay_open` for audio streams.
<details>
<summary>Like this (hasn't been tested)</summary>

```diff
diff --git a/player/lua/ytdl_hook.lua b/player/lua/ytdl_hook.lua
index 6a3c6d8530..6757eee8d4 100644
--- a/player/lua/ytdl_hook.lua
+++ b/player/lua/ytdl_hook.lua
@@ -464,11 +464,13 @@ local function formats_to_edl(json, formats, use_all_formats)
                     props = props .. ",w=" .. as_integer(track.width)
                                   .. ",h=" .. as_integer(track.height)
                                   .. ",fps=" .. as_integer(track.fps)
+                    hdr[#hdr + 1] = "!delay_open,media_type=" .. sub.media_type ..
+                        ",codec=" .. (sub.codec or "null") .. props
                 elseif sub.media_type == "audio" then
                     props = props .. ",samplerate=" .. as_integer(track.asr)
+                    hdr[#hdr + 1] = "!media_type=" .. sub.media_type ..
+                        ",codec=" .. (sub.codec or "null") .. props
                 end
-                hdr[#hdr + 1] = "!delay_open,media_type=" .. sub.media_type ..
-                    ",codec=" .. (sub.codec or "null") .. props
 
                 -- Add bitrate information etc. for better user selection.
                 local byterate = 0
```
</details>

If that also doesn't work for you, then there is nothing I can do for you.

It might be easier to download the stream directly with yt-dlp with all the languages you are interested in.

**Comment by Mi605** [comment]
Hello @christoph-heinrich, a happy New Year to you!

Many thanks for all your help from above.

Sorry for abruptly not having replied anymore, that wasn't deliberately. I've had a heavy bicycle accident only a few days after my last posting end of May last year, and only now I can start working on this issue again, which still causes trouble. Please let me know whether you want me to reopen it for further discussion or whether you rather prefer to keep it closed while discussing.

> Why do you want to switch audio streams while recording?
Well , actually it would not be needed precisely while recording, if user could know the wrong audio stream will come up before. This he can only know after the stream has started, and only then he can switch it. There is no difference between normal playing or recording, so he has to switch it even after recording was started.

A bit of background: This is all about a bash script I'm writing, I started with it 3 years ago, in autumn 2021. If you are interested in the details or how mpv is integrated therein, please feel free to look at [aCSTV](https://gitlab.com/Robin-antiX/acstv) on my gitlab space. The script code resides in /bin subfolder, the .deb packages are tailored for antiX linux, working on all full versions from 17 to 23 runit and sysvinit, 32 bit and 64 bit both. aCSTV is an old-school streaming tv script, able to run stutter- and distortion free even on 20 years old single core 32 bit CPU's. (What is not possible when using current tv-apps or trying to play streams directly in browser windows.) MPV is the really great and lightweight base which makes this possible, but we have users who can't do on console, so they need a tailored GUI.
Here a [screenshot](https://i.imgur.com/8Uo4L6l.jpeg) what it looks like (shot is from 2022 still, and don't care for the design, this changes with the sytem wide desktop theme user picks)

>but without setting all_formats=yes for the ytdl_hook, there is only one audio track, which gets selected by yt-dlp from all the available audio formats

Many thanks for this valuable hint. I'll see whether I can make use of this, but I'd rather want have it the user being able to switch between audio streams on the fly and on his own by pressing either the sharp key or clicking the respective icon in the mpv pseudo gui.

> It might be easier to download the stream directly with yt-dlp with all the languages you are interested in.

This is probably true, but that would mean to squeeze the stream two times parallel through the user's internet connection for recording while watching live streams. I'd need to start mpv and yt-dlp parallel on the very same stream the same time.

But you are right about yt-dlp flawlessly writing all audio streams to the file when feeding the very same parameters as when wrapped in --ytdl-raw-options by mpv:

```
$ yt-dlp --merge-output-format ts --no-video-multistreams --audio-multistreams -f 'bestvideo+mergeall' 'https://www.ardmediathek.de/live/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw'

Usage: yt-dlp [OPTIONS] URL [URL...]

yt-dlp: error: invalid merge output format "ts" given

```

OK, there's no way for me to get the raw mpeg transport-stream .ts output file format from yt-dlp obviously (probably I merely don't know how to do it right), so let's have writing yt-dlp the output to it's default mkv multistream container instead in order to get a testing sample:

```
yt-dlp --no-video-multistreams --audio-multistreams -f 'bestvideo+mergeall' 'https://www.ardmediathek.de/live/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw'
...
Ctrl-C

$ ffprobe -hide_banner 'ONE im Livestream 2024-01-02 07_38 [Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw].mkv'
Input #0, matroska,webm, from 'ONE im Livestream 2024-01-02 07_38 [Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw].mkv':
  Metadata:
    ENCODER         : Lavf59.27.100
  Duration: 00:00:20.02, start: 0.000000, bitrate: 3197 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 1k tbn
    Metadata:
      VARIANT_BITRATE : 0
      DURATION        : 00:00:20.020000000
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      VARIANT_BITRATE : 0
      ID3V2_PRIV.COM.APPLE.STREAMING.TRANSPORTSTREAMTIMESTAMP: \x00\x00\x00\x00\xa2\xd4{ 
      ID3V2_PRIV.COM.ELEMENTALTECHNOLOGIES.TIMESTAMP.UTC: 2024-01-02T03:41:01Z
      DURATION        : 00:00:20.010000000
  Stream #0:2: Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      VARIANT_BITRATE : 0
      ID3V2_PRIV.COM.APPLE.STREAMING.TRANSPORTSTREAMTIMESTAMP: \x00\x00\x00\x00\xa2\xd9\xfd 
      ID3V2_PRIV.COM.ELEMENTALTECHNOLOGIES.TIMESTAMP.UTC: 2024-01-02T03:41:05Z
      DURATION        : 00:00:19.989000000
  Stream #0:3: Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      VARIANT_BITRATE : 0
      ID3V2_PRIV.COM.APPLE.STREAMING.TRANSPORTSTREAMTIMESTAMP: \x00\x00\x00\x00\xa2\xd9\xfd 
      ID3V2_PRIV.COM.ELEMENTALTECHNOLOGIES.TIMESTAMP.UTC: 2024-01-02T03:41:05Z
      DURATION        : 00:00:19.989000000
```

That looks ok, all three audiostreams are stored away along with the videostream.

And precisely that is what I'd need to get from mpv output also.

Testing sample from MPV written .ts stream file:

```
$ mpv --stream-record='./test.ts' --ytdl-raw-options=no-video-multistreams=,audio-multistreams= --ytdl-format='bestvideo+mergeall' 'https://www.ardmediathek.de/live/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw'
...
q

$ ffprobe -hide_banner test.ts
Input #0, mpegts, from 'test.ts':
  Duration: 00:01:28.08, start: 7.980000, bitrate: 3608 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Audio: aac ([15][0][0][0] / 0x000F), 0 channels
  Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn
```

This video file written by mpv has merely a single audio stream, and moreover I find this audio stream to be completely empty, zero channels

Moreover mpv produces myriads of error lines on console while processing on recording, but playing the live stream fine to display still:
```
AV: 09:28:36 / 09:28:44 (100%) A-V:  0.000 Cache: 7.9s/2MB
[recorder] Stream 0 has too many queued packets; dropping.
[recorder] Stream 0 has too many queued packets; dropping.
[recorder] Stream 0 has too many queued packets; dropping.
[recorder] Stream 0 has too many queued packets; dropping.
[recorder] Stream 0 has too many queued packets; dropping.
[recorder] Stream 0 has too many queued packets; dropping.
...
```

Applying your patch from above to a copy of ytdl_hook.lua in ~/.config/scripts script directory and adding --no-ytdl to the line does fix it partly already, so this is a first step in the proper direction obviously:

There are no longer any of the above error lines while recording from multistreams with mpv:

```
$ mpv --no-ytdl --stream-record='./test_02.ts' --ytdl-raw-options=no-video-multistreams=,audio-multistreams= --ytdl-format='bestvideo+mergeall' 'https://www.ardmediathek.de/live/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw'
EDL: source file 'https://mcdn.one.ard.de/ardone/hls/master-stereo.m3u8' has unknown duration.
EDL: source file 'https://mcdn.one.ard.de/ardone/hls/master-ks.m3u8' has unknown duration.
EDL: source file 'https://mcdn.one.ard.de/ardone/hls/master-original.m3u8' has unknown duration.
EDL: source file 'https://mcdn.one.ard.de/ardone/hls/master-1080p-5000.m3u8' has unknown duration.
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
     Audio --aid=3 (aac 2ch 48000Hz)
     Subs  --sid=1 --slang=de 'vtt' (webvtt) (external)
[recorder] This is an experimental feature. Output files might be broken or not play correctly with various players (including mpv itself).
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [gpu] 1920x1080 yuv420p
AV: 09:42:15 / 09:42:21 (100%) A-V:  0.000 Cache: 5.5s/1MB
[ffmpeg] tls: Error decoding the received TLS packet.
[ffmpeg/demuxer] hls: keepalive request failed for 'https://mcdn.one.ard.de/ardone/hls/master-1080p-5000/00159/master-1080p-5000-b-20240102T045734_00929.ts' with error: 'Input/output error' when opening url, retrying with new connection

q
Exiting... (Quit)
```

Still there is a single audio stream in the output file merely, but now it has some signals in it at least:
```
$ ffprobe -hide_banner test_02.ts
Input #0, mpegts, from 'test_02.ts':
  Duration: 00:00:31.98, start: 0.000000, bitrate: 3191 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
  Stream #0:0[0x100]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 128 kb/s
  Stream #0:1[0x101]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn
```

It's not an option to run mpv and yt-dlp on the same stream parallel to watch and record the same time. This will exceed bandwidth of many users' internet connection and is a waste of ressources in internet infrastrtucture I won't approve. So I can see two options here: either yt-dlp downloads the file, and mpv reads from the partially downloaded temp file yt-dlp creates, or mpv writes the file properly itself. Both options have failed for me. For the first see above, for the second see below.

I've already checked the workaround by letting yt-dlp taking over the network transport part completely, and having mpv playing from the partial download, but this fails for me.  -- 

Have to swallow my words. Right now while taking the testing samples this actually works. Last time when I have tested this I couldn't make it work at all. But right now it works out of the box, single issue is a slight desync between audio and video.

On a first console:

```
$ yt-dlp --no-video-multistreams --audio-multistreams -f 'bestvideo+mergeall' 'https://www.ardmediathek.de/live/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw'
[ARDMediathek] Extracting URL: https://www.ardmediathek.de/live/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw
[ARDMediathek] Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw: Downloading JSON metadata
[ARDMediathek] Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw: Downloading m3u8 information
[info] Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw: Downloading 1 format(s): hls-main-4+hls-main-program_audio-Original+hls-main-program_audio-Klare_Sprache+hls-main-program_audio-Deutsch
[download] Destination: ONE im Livestream 2024-01-02 16_21 [Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw].mkv
[hls @ 0x55b03e9ac680] Skip ('#EXT-X-VERSION:4')
[hls @ 0x55b03e9ac680] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-01-02T15:16:28.320Z')
[hls @ 0x55b03e9ac680] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-01-02T15:16:32.320Z')
...
[hls @ 0x561de8975d00] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-01-02T15:17:12.320Z')
[hls @ 0x561de8975d00] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-01-02T15:17:16.320Z')
[hls @ 0x561de8975d00] Skip ('#EXT-X-PROGRAM-DATE-TIME:2024-01-02T15:17:20.320Z')
[https @ 0x561de8f87740] Opening 'https://mcdn.one.ard.de/ardone/hls/master-stereo/00001/master-stereo-b-20240102T151720_01106.aac' for reading
frame= 4602 fps= 54 q=-1.0 Lsize=   51539kB time=00:01:32.03 bitrate=4587.7kbits/s speed=1.08x    
video:47189kB audio:4314kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.071338%
Exiting normally, received signal 2.
[ffmpeg] Interrupted by user
[download] 100% of   50.33MiB in 00:01:29 at 574.53KiB/s

Ctrl+C

```

On a second console, while yt-dlp in first console is busy with transport and storing:
```
$ mpv './multistream-test/ONE im Livestream 2024-01-02 16_13 [Y3JpZDovL3dkci5kZS9CZWl0cmFnLTFlNjA0YWFlLTViODctNGMzNC04ZDhmLTg4OWI1ZjE2ZDU3Mw].mkv.part'
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
     Audio --aid=3 (aac 2ch 48000Hz)
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:06 / 00:00:07 (84%) A-V:  0.000
Track switched:
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
     Audio --aid=1 (*) (aac 2ch 48000Hz)
 (+) Audio --aid=2 (aac 2ch 48000Hz)
     Audio --aid=3 (aac 2ch 48000Hz)
AV: 00:00:08 / 00:00:09 (88%) A-V:  0.000 Dropped: 1
Track switched:
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
     Audio --aid=1 (*) (aac 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
 (+) Audio --aid=3 (aac 2ch 48000Hz)
AV: 00:00:10 / 00:00:11 (90%) A-V:  0.000 Dropped: 1
Track switched:
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
     Audio --aid=1 (*) (aac 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
     Audio --aid=3 (aac 2ch 48000Hz)
V: 00:00:11 / 00:00:13 (91%) Dropped: 1
Track switched:
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
     Audio --aid=3 (aac 2ch 48000Hz)
AO: [pipewire] 48000Hz stereo 2ch floatp
AV: 00:00:14 / 00:00:15 (92%) A-V:  0.000 ct: -0.060 Dropped: 1
Track switched:
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
     Audio --aid=1 (*) (aac 2ch 48000Hz)
 (+) Audio --aid=2 (aac 2ch 48000Hz)
     Audio --aid=3 (aac 2ch 48000Hz)
AV: 00:00:19 / 00:00:20 (94%) A-V:  0.000 ct: -0.080 Dropped: 1
Track switched:
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
     Audio --aid=1 (*) (aac 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
 (+) Audio --aid=3 (aac 2ch 48000Hz)
AV: 00:00:21 / 00:00:22 (95%) A-V:  0.000 ct: -0.100 Dropped: 2
Track switched:
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
     Audio --aid=1 (*) (aac 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
     Audio --aid=3 (aac 2ch 48000Hz)
V: 00:00:23 / 00:00:24 (95%) Dropped: 2
Track switched:
 (+) Video --vid=1 (h264 1920x1080 50.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
     Audio --aid=2 (aac 2ch 48000Hz)
     Audio --aid=3 (aac 2ch 48000Hz)
AO: [pipewire] 48000Hz stereo 2ch floatp
AV: 00:00:37 / 00:00:38 (97%) A-V:  0.000 ct: -0.120 Dropped: 2

Exiting... (Quit)

q
```

Works like a charm.
The switching between audio streams works way more smoothly this way compared with mpv itself doing the task of caching a live video stream with multistream-audio.
So I'll try to redesign the recording function within my script accordingly as a workaround for this issue.

All kind of input on this matter welcome.

Best regards
Robin

**Comment by christoph-heinrich** [comment]
I'm glad you got it working, I guess there is nothing more to do here then?

**Comment by Mi605** [comment]
>To change that you would have to save the ytdl_hook.lua to your script directory, use --no-ytdl to prevent the builtin ytdl_hook from being loaded, and then modify that lua file so that it doesn't lazily open those streams. That can be done by removing the delay_open for audio streams.
>Like this (hasn't been tested)

Many thanks @christoph-heinrich for this. For now I've applied this method to my script, it's what the current 1.12 version uses. One audio stream in the record is better then no audiostream in the record when running MPV on streams coming from stations providing audio-multistreams for their live transmissions. But this can't be the conclusive solution.

> I guess there is nothing more to do here then?

Please read the above anaylsis carefully. There is an issue with mpv when running a live video stream with multiple audio streams, the saved file has empty audio and literally thousands of error messages run down the console. This issue is fixed only when applying your patch, placing a modified copy of the internal lua script to user's home folders. Multi-audio is not working flawlessly in mpv itself the way it comes currently. Please keep in mind more and more stations tend to stream at least three parallel audio streams along with the video (default audio, clear voice audio for aurally handicapped people, and original language of the video) and in contrast to the video streams the audio streams need regularly to be switched after playback was started. So user should be able to switch between them on the fly in mpv, regardless whether a recording is running or not.
