### ISSUE TITLE
no-resume-playback not working in mpv.conf when part of a profile

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#11710]
How can you get mpv to not resume playback (--no-resume-playback) only on certain kinds of files. 

This is my mpv.conf:

```
hwdec=vaapi
geometry=40%
title=${filename}
osc=no
border=yes
save-position-on-quit

[audio]
	profile-cond = (filename:match"%.mp3$" or filename:match"%.m4a$") ~= nil
	no-resume-playback
	geometry=25%
```

which looks like it should not resume playback on .m4a and .mp3 files, but would on any other file. However this doesn't work, it resumes playback even on the audio files. 

If I add `no-resume-playback` to the first paragraph of options, it works, but of course then it's working on everything, and I would like videos to resume.

**Comment by guidocella** [comment]
You would have to pass `--no-resume-playback` on the command line as it's evaluated too late in a conditional profile. You can set `save-position-on-quit=no` in that profile instead to avoid saving the playback position for those files.

**Comment by Lypheo** [comment]
You can run arbitrary lua code in the condition, so for files that already have a position saved, you can do 
```lua
	profile-cond = (filename:match"%.mp3$" or filename:match"%.m4a$") ~= nil and mp.command("seek 0 absolute")
```
