### ISSUE TITLE
peak-detect produces too dim result with gpu-next & LG Chess demo

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#11720]
```
vo=gpu-next
hdr-compute-peak=no

```
![mpv-shot0002](https://github.com/mpv-player/mpv/assets/13510490/cc880d77-72ed-4fc3-ad42-fc7270536b58)
Perhaps a bit over-exposed. However, 

```
vo=gpu-next
hdr-compute-peak=yes

```
![mpv-shot0001](https://github.com/mpv-player/mpv/assets/13510490/1948421d-9ad0-4d26-9d19-0431c9b4d370)
apparently is way too dim. It also stays that way in subsequent scenes.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/11577072/output.txt)

### Sample files
https://0x0.st/Hqgu.mkv
It btw. crashes graphics driver/Xorg with VAAPI (HandBrake AMF not able to produce non-broken files?), so better use software decoding.

Latest libplacebo git-master & mpv git-master, same on Windows with D3D11.

**Comment by quietvoid** [comment]
Well this is another of those where the metadata says it's 1000 nits when it's 10 000 nits.

I guess your issue is about the tone mapping being too dark. It's not about peak detection.
Even at 99.9% it's 4000 nits.

**Comment by kasper93** [comment]
> Perhaps mpv needs a control for the histogram percentile.

Maybe, but I think current value is working well enough for normal content and most other content.

Another possible option to add could be clip peak detect to mastering metadata, but it almost never good idea... So I wouldn't even allow this.

> Well this is another of those where the metadata says it's 1000 nits when the encoded signal reaches 10 000 nits.

madVR also measures 10 000 nits for this scene. Not much we can do about it. Those demo files are just overcooked...

> It also stays that way in subsequent scenes.

Not actually an issue for this sample, but libplacebo is little bit slow to adjust peak value on scene changes. There is area to improve here. The issue keeps coming, especially with fades on scene changes.

**Comment by aufkrawall** [comment]
Ok, thanks for your input. No idea if this then should be closed right away or by some commit with more general improvements.

**Comment by dyphire** [comment]
Demo videos are always terrible and need to be tested for peak detect in real videos.

> Not actually an issue for this sample, but libplacebo is little bit slow to adjust peak value on scene changes. There is area to improve here. The issue keeps coming, especially with fades on scene changes.

It seems like this, but overly precise peak detection may sometimes cause flickering scene brightness.

**Comment by ValeZAA** [comment]
>says it's 1000 nits when the encoded signal reaches 10 000 nits.

There are no 10000 nits displays. Is this a joke? What that means (and YOU PERFECTLY know that) is that anything above 1000 nits is not mastered cause cannot even be displayed when mastered and thus YOU MAY want not to output it/compress using good colorimetric method. That also allows to more correcrly use PQ tone mapping.

**Comment by kasper93** [comment]
Expected, see https://github.com/mpv-player/mpv/issues/11720#issuecomment-1564685239
