### ISSUE TITLE
No playback from a link in mpv, but works in VLC

### ISSUE THREAD

**Issue by Rafee-M** [mpv-player/mpv#11726]
### Important Information

Provide following Information:
- mpv version 0.35.0-385-g9e716d63
- Windows Version **10 - 22H2 (build 19045.2604)**
- Source of the mpv binary [shinchiro on SourceForge](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/)
- If known which version of mpv introduced the problem N/A

### Reproduction steps

Paste the link in mpv

### Expected behavior
Video playing back normally

### Actual behavior
mpv closes suddenly
![image](https://github.com/mpv-player/mpv/assets/69535896/c0bc3f63-54e1-4c61-8bc8-9ee74c507336)

In VLC it works fine

### Log file
[logmpv.txt](https://github.com/mpv-player/mpv/files/11582856/logmpv.txt)

### Sample files

The link: https://usa7-nas02-1.shegu.net/vip/p1/movie_mp4_h264/2009/2/9/21489/movie.21489.2009.720p.H264.20191208090259.mp4?KEY1=0x3sfvOtgzxWtdbO9T1OIg&KEY2=1685228740

**Comment by llyyr** [comment]
The url works on my end, is your mpv/ffmpeg/yt-dlp blocked by windows firewall by any chance? The error says it can't resolve the domain name at all

**Comment by bitraid** [comment]
You should wrap the url in double quotes (`"`), otherwise the shell will intercept `&` and process `KEY2=1685228740` as an additional command.

**Comment by Rafee-M** [comment]
> is your mpv/ffmpeg/yt-dlp blocked by windows firewall by any chance?

I don't have any custom firewalls enabled in Windows. But it did work with a VPN for some reason. Might be something on my ISP's side. Thanks!

**Comment by Rafee-M** [comment]
> is your mpv/ffmpeg/yt-dlp blocked by windows firewall by any chance?

I don't have a custom firewall in Windows, but it did work with a VPN. Might be an issue on the ISP's side. Thanks!
>You should wrap the url in double quotes ("), otherwise the shell will intercept & and process KEY2=1685228740 as an additional command.

Thanks! It worked after doing this and using a VPN
