### ISSUE TITLE
vo=gpu-next & gpu-api=opengl leads to upside-down application

### ISSUE THREAD

**Issue by essinghigh** [mpv-player/mpv#11722]
### Important Information

MPV Version:  mpv-x86_64-v3-20230526-git-9fd4ae9
Windows Version: Windows 11 Version 22H2 (OS Build 22621.1413)
MPV Binary Source: shinchiro/mpv-winbuild-cmake
Screenshot(s): 
https://github.com/mpv-player/mpv/assets/72340070/c9ebeea3-3bc0-482a-ba55-55b50b516ab6
https://github.com/mpv-player/mpv/assets/72340070/08bcf773-55df-4dc4-b259-cd9de34e29ca
https://github.com/mpv-player/mpv/assets/72340070/079c6362-d0a4-4f4c-a8b0-a3a3b3c424ac
https://github.com/mpv-player/mpv/assets/72340070/5e2d935d-70d3-4748-bd33-6750ce02e43a

### Reproduction steps

Using --no-config does not reproduce the issue as vo=gpu works fine.

vo=gpu-next
gpu-api=opengl

Using only the above configuration, playback, controls, etc are all upside-down.

### Expected behavior
The entire window should not be upside-down

### Actual behavior
The entire window is upside-down.
I can still click where things like the pause icon would be to pause playback.
This happens with local media, media on network shares, and youtube-dl.
Same thing happens with [images](https://github.com/mpv-player/mpv/assets/72340070/cd718976-98c8-4512-a4a2-9c8ec8cc9fc6)

### Log file

https://github.com/mpv-player/mpv/files/11580228/mpv.log

**Comment by kasper93** [comment]
Fixed by https://github.com/mpv-player/mpv/pull/11162

**Comment by essinghigh** [comment]
Confirming that the changes that have now been merged from #11162 have resolved this.
