### ISSUE TITLE
[vo/gpu-next/vulkan] This is not a libplacebo vulkan gpu api context.

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#11737]
### Important Information
- mpv version:
```
mpv 0.35.0-412-g872b068c Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
built on Mon May 29 12:20:27 2023
libplacebo version: v5.264.0-268-gb8494ff
FFmpeg version: N-110916-g988fd5743
FFmpeg library versions:
libavutil       58.12.100
libavcodec      60.15.100
libavformat     60.5.100
libswscale      7.3.100
libavfilter     9.8.101
libswresample   4.11.100
```
- Windows Version:
```
Edition	Windows 10 Pro
Version	22H2
Installed on	‎28/‎04/‎2023
OS build	19045.2965
Experience	Windows Feature Experience Pack 1000.19041.1000.0
```
- Source of the mpv binary: https://github.com/shinchiro/mpv-winbuild-cmake/releases

### Reproduction steps
```
mpv --no-config --hwdec=vulkan --vo=gpu-next --msg-level=vo=trace --log-file=output.txt "test.mkv"
```

### Expected behavior
`hwdec=vulkan` working

### Actual behavior
`hwdec=vulkan` not working
```
[   0.178][v][vd] Opening decoder hevc
[   0.179][v][vd] Looking at hwdec hevc-vulkan...
[   0.179][v][vo/gpu-next] Loading hwdec drivers for format: 'vulkan'
[   0.179][v][vo/gpu-next] Loading hwdec driver 'vulkan'
[   0.180][e][vo/gpu-next/vulkan] This is not a libplacebo vulkan gpu api context.
[   0.180][v][vd] Could not create device.
[   0.180][v][vd] No hardware decoding available for this codec.
[   0.180][v][vd] Using software decoding.
```

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/11592470/output.txt)

**Comment by Obegg** [comment]
> gpu-context=winvk or hwdec=vulkan-copy

```
mpv --no-config --hwdec=vulkan-copy --vo=gpu-next --msg-level=vo=trace --log-file=hwdec-vulkan-copy.txt "test.mkv"
```
[hwdec-vulkan-copy.txt](https://github.com/mpv-player/mpv/files/11592538/hwdec-vulkan-copy.txt)
All I see with `hwdec=vulkan-copy` is green screen.

**Comment by philipl** [comment]
You need to set --gpu-api=vulkan to use vulkan.

**Comment by philipl** [comment]
We also don't really know what the minimum requirements are for vulkan video on windows for either drivers or hardware. @arm64-v9a got it working but no one else to my knowledge.

**Comment by Obegg** [comment]
> 

```
mpv --no-config --hwdec=vulkan --gpu-api=vulkan --vo=gpu-next --msg-level=vo=trace --log-file=greenscreen.txt "test.mkv"
```
[greenscreen.txt](https://github.com/mpv-player/mpv/files/11592599/greenscreen.txt)
All I see now is green screen.

**Comment by llyyr** [comment]
You're on nvidia so you might need the nvidia workaround ffmpeg branch, and the beta driver I believe

**Comment by philipl** [comment]
Yeah. You either need to install nvidia's vulkan beta driver or recompile ffmpeg with a work-around (see my tree) or it'll just be green. Nvidia things.

**Comment by philipl** [comment]
> The R530+ driver works with your ffmpeg branch, and the Vulkan Beta driver works with the official version. But Vulkan Video+Filters seems to be corrupted regardless of which driver/FFmpeg is used.

Yeah. There's another driver bug that prevents mutli plane images from working in filters and that is what the decoder produces. If you hwupload from nvdec or software decoding, the filters work. Just nvidia things.

**Comment by philipl** [comment]
Closing this as the requirements here are documented in the FAQ now.
