### ISSUE TITLE
Weird Scaled Resolution in wayland with fractional scaling enabled

### ISSUE THREAD

**Issue by fritzrehde** [mpv-player/mpv#11731]
### Important Information

Provide following Information:
- mpv version: 0.35.1-dirty
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: Arch Package Repositories
- If known which version of mpv introduced the problem: maybe one that introduces wayland fractional scaling support
- Window Manager and version: Sway 1.8.1
- GPU driver and version: not sure, using `Intel HD Graphics 630` on a Thinkpad T470p

### Reproduction steps
Use a wayland compositor (wlr-roots based ideally, so not Gnome or KDE with wayland enabled, but sway, hyprland, river etc) with fractional scaling enabled to 1.2/120%. Open a 1080p video and check the video settings using the `i` key. Observe the `Native Resolution`, which would be `1920 x 1080` and then the `Scaled Resolution`.

### Expected behavior
In my naive opinion, `Scaled Resolution` should still just show `1920 x 1080`, as the wayland scaling shouldn't affect the resolution I want the video to play at (I have a 1080p screen on a 14 inch monitor, so I'd expect to get 1080p resolution).

### Actual behavior
I am not sure what to expect the `Scaled Resolution` to be, but for me it shows `3200 x 1800`. I have no clue how this number has come to be. I'm also not even claiming that I don't get 1080p quality, to my eyes I am (though I am not sure how to test given that this `Scaled Resolution` value is so weird). Maybe someone can explain to me how the `Scaled Resolution` is calculated when using wayland fractional scaling in case this isn't a bug but actually the expected behaviour.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/11584431/log.txt)

**Comment by Dudemanguy** [comment]
0.35 was before the fractional scaling protocol was available. What you are seeing is legacy behavior where the compositor essentially lies to mpv to get it to scale to coordinates above the desktop resolution and then the compositor scales back down the buffer to get the final result. This is bad for several reasons, but thankfully we have a proper fractional scaling protocol now that mpv uses. You have to compile mpv from the master branch, but it properly scales the correct resolution (or should anyway).

**Comment by Dudemanguy** [comment]
Oh and sway 1.8.1 doesn't support the fractional scale protocol either. You'd also have to compile that from git master.
