### ISSUE TITLE
Slow or inconsistent launch speed depending on build

### ISSUE THREAD

**Issue by NotMithical** [mpv-player/mpv#11734]
### Important Information

Provide following Information:
- mpv version: 0.35.0-407-g959ef843 AND mpv 0.35.0-385-g9e716d63
- Windows Version: Windows 10 22H2, Build 19045.2965
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/
- If known which version of mpv introduced the problem: Uncertain
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps
1. Download and extract latest and second latest builds from the source above.
2. Attempt to run both mpv executables with --no-config, with or without a file.

### Expected behavior
Both executables open and/or play video quickly.

### Actual behavior
mpv 0.35.0-385-g9e716d63 launches in under a second whereas 0.35.0-407-g959ef843 takes 5-6 seconds. I have tested this with many more builds, including those from different sources, and the versions in which this occurs is wildly inconsistent, as is the time it takes to run. In some cases it may take closer to 20 seconds.

I initially assumed this was due to a recent change but this happens in some older builds as well. If I get a build that launches quickly from sourceforge, I can of course get the same from https://github.com/shinchiro/mpv-winbuild-cmake/releases. But if I get a build from either a day earlier or a day later from github, it fairly consistently takes at least 5 times longer to launch.

Apologies for my wording of this issue, as it is very difficult for me to describe.

### Log file

0.35.0-407-g959ef843 (slow): [output.txt](https://github.com/mpv-player/mpv/files/11587090/output.txt)

0.35.0-385-g9e716d63 (fast): [output.txt](https://github.com/mpv-player/mpv/files/11587094/output.txt)

**Comment by kasper93** [comment]
Your logs doesn't reflect the load speed difference. Would be good to actually have a log when it happens. Do you see the difference with `--no-config`?

I would guess shader cache is not working for you on never builds, and this is what you are seeing. After merge of https://github.com/mpv-player/mpv/pull/10838 cache no longer works old configs and you need to add `--gpu-shader-cache`

**Comment by llyyr** [comment]
If the startup is slow even without a file then it's almost certainly something on your end.

Can you try to start both the slow and fast binary 10 times and see if the results remain consistent?

**Comment by NotMithical** [comment]
> Your logs doesn't reflect the load speed difference. Would be good to actually have a log when it happens.

These logs _are_ from when it happens. I'm aware the logs don't reflect it, the delay seems to occur before logging even begins.


> Do you see the difference with `--no-config`?

`--no-config` does not appear to make any difference. The logs above were also generated with `--no-config`.


> After merge of https://github.com/mpv-player/mpv/pull/10838 cache no longer works with old configs and you need to add `--gpu-shader-cache` option.

Unless I'm mistaken, the "fast" build that I specified above includes that commit, as it was built almost a week after it was merged. Nonetheless, I passed `--gpu-shader-cache` and saw no difference.


> And try to narrow down the first build that is slower.

Believe me, I've tried, but it doesn't just happen consistently after a certain point. I can dig up a build from 3 months ago and get the exact same issue but use one from earlier this month and it may work just fine, then one from days later and the issue is back.


> Can you try to start both the slow and fast binary 10 times and see if the results remain consistent?

Yes, this is consistent. 10/10 times the slow one starts slow and the fast one starts fast.

**Comment by kasper93** [comment]
> These logs are from when it happens. I'm aware the logs don't reflect it, the delay seems to occur before logging even begins.

Ok, then my comment can be ignored as I focused on recent changes that might or in fact does increase load time in certain configuration, but you are not affected by that.

> Believe me, I've tried, but it doesn't just happen consistently after a certain point. I can dig up a build from 3 months ago and get the exact same issue but use one from earlier this month and it may work just fine, then one from days later and the issue is back.

I understand, but if you cannot narrow down the problematic build or other factor that might influence the load time. And it is so hard for you to figure out when it is happening, it is even harder for us to start diagnosing the issue without any concrete thing to grab onto.

You could try procmon to see if there is something that you see there taking longer than expected
https://learn.microsoft.com/sysinternals/downloads/procmon

I would guess the issue is loading mpv and/or it's dependencies, it can happen for example if you load executable form network drive or HDD which need to spin-up. But again this doesn't apply to your description...

**Comment by NotMithical** [comment]
> You could try procmon to see if there is something that you see there taking longer than expected

This made it immediately clear that the problem is my antivirus spending at least 5 seconds reading the file before allowing the process to start. I don't know why it takes so long to check some binaries and doesn't bother with others but that's undoubtedly what's going on. I should've checked that sooner, thank you for your help.
