### ISSUE TITLE
How to change default message position instead of top left?

### ISSUE THREAD

**Issue by gittyup2018** [mpv-player/mpv#11730]
Hi,

I can't seem to find how to set the default OSD message  position/location like when messages like "Speed: 1.0" or "Stay on top: yes" or other messages are shown in the top left corner.  I want to make all those messages centered at the bottom instead of the top left by default.

**Comment by guidocella** [comment]
https://mpv.io/manual/master/#osd

See the `--osd-align-` options.

**Comment by gittyup2018** [comment]
I don't know how I missed that, but the osd-align-x and osd-align-y works perfectly! Thanks a lot!!
