### ISSUE TITLE
`--sub-auto=fuzzy` was broken by `519e56f`

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#11749]
### Important Information

Provide following Information:
- mpv version
latest
- Windows Version
win10 pro 22H2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/
- If known which version of mpv introduced the problem
519e56f
- Possible screenshot or video of visual glitches
N/a

### Reproduction steps

start mpv with `--sub-auto=fuzzy`, now it will automatically load some unrelated subtitles sometimes.

### Expected behavior

No extra subs (tested by f677f8a5)

### Actual behavior

(tested by f7945847) Confirmed that build 519e56f on 05/21 was broken.
```
[   0.019][i][cplayer]  (+) Video --vid=1 (*) (h264 1280x720 24.000fps)
[   0.019][i][cplayer]  (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[   0.019][i][cplayer]  (+) Subs  --sid=1 --slang=dts 'Knives.Out.2019.BluRay.1080p.x264.DTS.ass' (ass) (external)
[   0.019][i][cplayer]      Subs  --sid=2 --slang=mkv '[VCB-Studio] Nishi no Shounen to Seiran no Kishi [02][Ma10p_1080p][x265_flac].mkv.ass' (ass) (external)
```

### Log file

[test_bad.log](https://github.com/mpv-player/mpv/files/11624154/test_bad.log)
[test_ok.log](https://github.com/mpv-player/mpv/files/11624156/test_ok.log)

**Comment by sfan5** [comment]
ping @TAAPArthur
a log with `--msg-level=find_files=trace` might also be useful since that shows the exact results of the relevant code path

**Comment by dyphire** [comment]
On the other hand, the behavior changes for `lang` that https://github.com/mpv-player/mpv/commit/519e56f80f8f251c96682daaa90f409c05277464 attempts to implement have also performed poorly, and now we will will more easily get `lang` properties with unclear meanings such as mkv, dts.

**Comment by TAAPArthur** [comment]
Not home now but I'm surprised by  this issue. Thought my patch would just supply a language for detected subtitles rather than affect what subtitles are detected... Ah I see the issue
```
        if (lang.len && fuzz >= 1)
            prio |= 4; // matches the movie name + a language was matched
```
So anytime we find a lang, we'd automatically consider the sub.

Moving that block under the  `if (bstr_startswith(tmp_fname_trim, f_fname_trim)) {` should avoid the problem. Can send out a patch later tonight

This won't completely resolve the problem (?) mentioned by @dyphire. In that regard the best I could think of at the moment is to ignore the language in this case if it isn't known. Not sure if it really matter; the previous behavior would have lang as unknown right?

**Comment by SeaHOH** [comment]
I am now using [nyfair's Windows build](https://github.com/nyfair/mpv-win64) the latest version [git-20230601](https://github.com/nyfair/mpv-win64/releases/download/bleeding_edge/All-in-One-MPV-git-withoutPython-20230601.7z). I have tried to load subtitles via script, then found some thing fun, I am not sure how long it has happened.

Run command `sub-add` with lua `mp.command` was broken too, but `mp.commandv` is OK.
1. Full file path was fail, only file name was accepted, and only find from current working directory.
1. Flage `cached` has no effect, always load subtitle as new entry even the same file.

**Comment by TAAPArthur** [comment]
@SeaHOH I didn't quite follow all of that, but does your issue still persist with the changes in the linked PR?

**Comment by SeaHOH** [comment]
@TAAPArthur I think it's a different issue, and I can not test your PR at now time. I commented it here because I try to load subtitles myself for bypass this issue, and it's a related issue about load subtitles. I guess its issue caused by the process of join strings.
