### ISSUE TITLE
FFMPEG version: N-110928 Breaks MPV Build w/ Vulkan Enabled

### ISSUE THREAD

**Issue by frkli1965** [mpv-player/mpv#11740]
Just a quick heads up...

Following last night's huge FFMPEG update, mostly revolving around Vulkan related tech, MPV will no longer compile with Vulkan options i.e. vulkan=disabled, vulkan-interop enabled.

With the above disabled, all is well as per usual which is fine by me btw as my AMD GPU tends to run at around 20% whilst watching 4K .mkv videos under OpenGL instead of +40% under Vulkan all else being equal...

Platform is Linux Hyprland (Wayland)
Kernel v6.4.rc4
MESA v23.2.x

FFmpeg version: N-110928-gc4cdd79435
FFmpeg library versions:
   libavutil       58.12.100
   libavcodec      60.16.100
   libavformat     60.5.100
   libswscale      7.3.100
   libavfilter     9.8.101
   libswresample   4.11.100
   
Trace is as follows:-

FAILED: libmpv.so.2.1.0.p/video_out_hwdec_hwdec_vulkan.c.o
ccache cc -Ilibmpv.so.2.1.0.p -I. -I.. -Igenerated -Igenerated/etc -Igenerated/sub -Igenerated/player/javascript -Igenerated/player/lua -Igenerated/wayland -I/usr/local/include -I/usr/local/include/freetype2 -I/usr/include/uuid -I/usr/include/fribidi -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/lua5.2 -I/usr/include/uchardet -I/usr/local/include/vapoursynth -I/usr/include/python3.10 -I/usr/include/x86_64-linux-gnu/python3.10 -I/usr/local/include/AL -I/usr/local/include/pipewire-0.3 -I/usr/local/include/spa-0.2 -I/usr/local/include/libdrm -I/usr/include/x86_64-linux-gnu -I/usr/include/sixel -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -std=c11 -O3 -D_ISOC99_SOURCE -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -Werror=implicit-function-declaration -Wno-error=deprecated-declarations -Wno-error=unused-function -Wempty-body -Wdisabled-optimization -Wstrict-prototypes -Wno-format-zero-length -Wno-redundant-decls -Wvla -Wno-format-truncation -Wimplicit-fallthrough -fno-math-errno -Wformat -Werror=format-security -Wundef -Wmissing-prototypes -Wshadow -Wno-switch -Wparentheses -Wpointer-arith -Wno-pointer-sign -Wno-unused-result -fPIC -D_REENTRANT -pthread -MD -MQ libmpv.so.2.1.0.p/video_out_hwdec_hwdec_vulkan.c.o -MF libmpv.so.2.1.0.p/video_out_hwdec_hwdec_vulkan.c.o.d -o libmpv.so.2.1.0.p/video_out_hwdec_hwdec_vulkan.c.o -c ../video/out/hwdec/hwdec_vulkan.c
../video/out/hwdec/hwdec_vulkan.c: In function ‘vulkan_init’:
../video/out/hwdec/hwdec_vulkan.c:91:34: error: ‘VK_QUEUE_VIDEO_DECODE_BIT_KHR’ undeclared (first use in this function)
   91 |         if ((qf[i].queueFlags) & VK_QUEUE_VIDEO_DECODE_BIT_KHR) {
      |                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../video/out/hwdec/hwdec_vulkan.c:91:34: note: each undeclared identifier is reported only once for each function it appears in
[291/297] Compiling C object libmpv.so.2.1.0.p/video_out_vo_dmabuf_wayland.c.o
ninja: build stopped: subcommand failed.

Keep up the great work btw!!!

**Comment by philipl** [comment]
Please provide your full meson configuration arguments and your meson log.

**Comment by frkli1965** [comment]
Sure, here you go...

[meson-log.txt](https://github.com/mpv-player/mpv/files/11593757/meson-log.txt)

I trust you'll find the Meson config. args. within the log itself.

**Comment by philipl** [comment]
Your vulkan headers are too old (1.3.204). You need at least 1.3.238. I can add an explicit check for that, but you won't be able to build the functionality without updating the headers.

**Comment by frkli1965** [comment]
Ah, thanks for that. I did have much more recent Vulkan headers but due to conflict(s) with Oibaf Mesa drivers I had to rollback to the vanilla version that comes with Jammy.

As my rig doesn't really rely on Vulkan much I tend to prioritise on the latest Mesa drivers instead since they afford me far more bang per buck as it were.

Many thanks for the expeditious feedback all the same and I'll see what I can do with regard to the Vulkan headers but as I've already intimated, I'm not huge a fan of Vulkan especially not of their shoddy installation procedure when it comes to getting the latest offerings on Lunarg... :-)

**Comment by philipl** [comment]
FWIW, I run with kisak ppa and lunarg vulkan headers here just fine.

**Comment by frkli1965** [comment]
OK, thanks Phil, I shall definitely consider the option...

Perhaps MPV could bundle the required Vulkan headers within a subproject (if possible) as 'libplacebo' does? :-)

**Comment by frkli1965** [comment]
Hi Phil,

Sorry to trouble you again but having reviewed my build activities over the past couple of days, I recall that 'hwdec_vulkan.c' compiled successfully in the wee hours at 29/05/2023 00:56:49 BST with Vulkan headers v1.3.204...

Whereas I did not get around to building all of the FFMPEG Vulkan changes of yesterday until late morning (29/05/2023) which suggests perhaps that v1.3.204 is not the root cause of my MPV build problems this evening.

Anyway, I'm confident that it will all come out in the wash in due course so not to worry as I rely solely on OpenGL in any case.

I also note with interest (commit #0131ae4) that I've at least given you some food for thought so glad to have made a small contribution to the MPV cause in any case.

All the best buddy...
