### ISSUE TITLE
show-progress on screen help

### ISSUE THREAD

**Issue by lavinnyv** [mpv-player/mpv#11743]
does any one know how to keep show-progress on screen longer? 

i'm using socat to a remote computer:

echo 'show-progress' | socat - /tmp/mpvsocket
or 
echo '{"command": ["osd-auto", "show-progress"]}' | socat - /tmp/mpvsocket 

both show it for the default time. i've spent hours online searching for this answer.

i've looked at osd-duration=<time> and tried to work that in, but it can't get it to work for me.

**Comment by christoph-heinrich** [comment]
`mpv --no-config --osd-duration=4000 <file>` shows the progress for 4 seconds after pressing `P`.

**Comment by lavinnyv** [comment]
P sends that and i can adjust in my input.conf if i wanted to send a keypress.
shift + o actually holds the time on screen until you toggle it off again with shift + o (keybinding for show-progress)

but i'm trying to send this as a command over the network and i'm sending it to 5 computers - as a test, i send commands to 20+ computers often - each playing a different file. the code i have above sends it to all, but it's too quick on screen to read, the default = 1000ms. i want it on screen longer/control how long.

i do this when i'm just trying to display text: 
echo 'show-text ${playlist} 6000' | socat - /tmp/mpvsocket

the show-text command - i can add the time for duration. but for the show-progress, it's a property and doesn't work the same. 

so i'm looking to control the duration of this command to show the progress. how would it work into either of my commands? 

echo 'show-progress' | socat - /tmp/mpvsocket
or
echo '{"command": ["osd-auto", "show-progress"]}' | socat - /tmp/mpvsocket

i tried adding your code to both of the scripts to test and got parameter errors.

and when i tried just sending this:
echo no-config osd-duration=4000 | socat - /tmp/mpvsocket
or
echo '{"command": ["no-config", "osd-duration=4000"]}' | socat - /tmp/mpvsocket

that also got a parameter error

and this, nothing happened:
echo 'no-config osd-duration=4000' | socat - /tmp/mpvsocket

**Comment by lavinnyv** [comment]
thank you. thank you.

**Comment by addycb** [comment]
close issue?
