### ISSUE TITLE
Spline tonemapping out of gamut options.

### ISSUE THREAD

**Issue by pbiancardi** [mpv-player/mpv#11750]
What is the preferred method of dealing with out of gamut pixels when using spline and hdr-compute-peak= ?

Auto doesn't seem to deal with this scene very well, clip does but I am concerned this may cause other issues.  Is desaturate the way to go?

<img width="960" alt="WARN" src="https://github.com/mpv-player/mpv/assets/133981792/493d6891-0abf-46f8-9870-375c0b8d4624">

<img width="960" alt="aUTO" src="https://github.com/mpv-player/mpv/assets/133981792/cc72a473-8d94-4fba-bb35-590b8b44bd86">

<img width="960" alt="Clip" src="https://github.com/mpv-player/mpv/assets/133981792/1d30fbc8-261f-4d22-a145-105a2bb736c8">

<img width="960" alt="Desat" src="https://github.com/mpv-player/mpv/assets/133981792/ea5cbee9-082b-4717-aac9-5c49896e50b1">

**Comment by haasn** [comment]
I have to still hook up the new gamut mapping API to mpv, to give you more options to play with.

**Comment by MidnightWatcher** [comment]
> I have to still hook up the new gamut mapping API to mpv, to give you more options to play with.

Will this help to address some of the color issues outlined here?

https://www.avsforum.com/threads/madvr-player-support-thread.2215490/page-440#post-62623033
