### ISSUE TITLE
Speedup + shaders with lower GPU usage

### ISSUE THREAD

**Issue by d-patyk** [mpv-player/mpv#11759]
I use https://github.com/bloc97/Anime4K to watch 720p recordings of coding streams in higher resolution. Also I watch them at x1.77 speed.
At x1.00 speed gpu usage is aroung 65%, but at x1.77 speed gpu usage is 100%.
Is it possible to rearrange filters in mpv so that speeding up would be done before applying shaders?

**Comment by Tama47** [comment]
Are you using the Fast shaders?

**Comment by mia-0** [comment]
Increasing playback speed means increasing the frame rate, i.e. reducing the time between frames during which the GPU can idle. So GPU usage is necessarily higher, and there’s nothing that could be rearranged—it’s basically the same as playing a high-fps video.

**Comment by d-patyk** [comment]
Surely if your monitor has a limit of, for example, 60 FPS, rendering in 120 FPS doesn't make any sense.

**Comment by haasn** [comment]
> Surely if your monitor has a limit of, for example, 60 FPS, rendering in 120 FPS doesn't make any sense.

Depends on how correct you want the result to be. The correct thing to do is to render out all 120 fps and then blend them (downsample) to 60 fps, to avoid aliasing.

Are you using `--interpolation`?

**Comment by d-patyk** [comment]
> The correct thing to do is to render out all 120 fps and then blend them (downsample) to 60 fps, to avoid aliasing.
Hm, I didn't know about such a thing, thanks for enlightening me :3

> Are you using `--interpolation`?
No, but if this option was supposed to solve x2 GPU usage with x2 speed - it didn't
