### ISSUE TITLE
Can't play or buffer is too slow on twitter

### ISSUE THREAD

**Issue by memories169** [mpv-player/mpv#11754]
### Important Information

Provide following Information:
- mpv version 0.35.1
- Windows Version 11
- Source of the mpv binary https://github.com/zhongfly/mpv-winbuild/releases

### Reproduction steps

mpv https://twitter.com/TheBabylonBee/status/1664014211956236288

### Log file

[log.txt](https://pastebin.com/dSeAcfzy)

**Comment by gunir** [comment]
Same issue:
```
mpv "https://video.twimg.com/amplify_video/1664007149436149760/vid/1920x1080/YEBErlMgK8y-qvEm.mp4?tag=16"
mpv "https://video.twimg.com/amplify_video/1664007149436149760/vid/640x360/iDGXbadW3wfEl0wI.mp4?tag=16"
```
`mpv "https://video.twimg.com/amplify_video/1664007149436149760/vid/640x360/iDGXbadW3wfEl0wI.mp4?tag=16" --no-config --log-file=twitter.log`


[twitter.log](https://github.com/mpv-player/mpv/files/11635881/twitter.log)

**Comment by gunir** [comment]
> This is almost certainly not an mpv issue. It's either
> 
>     * Twitter broke something
> 
>     * Twitter is maliciously trying to block non-browser viewing
> 
> 
> Either way, it has to be fixed in yt-dlp.

Not really, as  far as I can tell, this is an mpv issue, try with `--no-ytdl`:
`mpv "https://video.twimg.com/amplify_video/1664007149436149760/vid/640x360/iDGXbadW3wfEl0wI.mp4?tag=16" --no-ytdl --no-config --log-file=twitter.log`

Same issue.

**Comment by llyyr** [comment]
I can't open that url in my browser or with curl either, why do you think it's a mpv issue?

**Comment by gunir** [comment]
> I can't open that url in my browser or with curl either, why do you think it's a mpv issue?

I can open that url in:
- pipe from yt-dlp to mpv: https://streamable.com/w7i9vp
- yt-dlp (of course)
- Web browser (Firefox)
![image](https://github.com/mpv-player/mpv/assets/134402102/b527ea56-83b0-472d-a82e-5b08dd5532cf)

Can't:
- MPV

Anyways this is a log with `--no-ytdl`:
```
mpv "https://video.twimg.com/amplify_video/1664007149436149760/vid/640x360/iDGXbadW3wfEl0wI.mp4?tag=16" --no-ytdl --no-config --log-file=twitter.log
 (+) Video --vid=1 (*) (h264 640x360 23.977fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
VO: [gpu] 640x360 yuv420p
AO: [wasapi] 48000Hz stereo 2ch float
AV: 00:00:00 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/16KB
Audio device underrun detected.
AV: 00:00:00 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/16KB
Audio device underrun detected.
AV: 00:00:00 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/13KB
Audio device underrun detected.
AV: 00:00:00 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/13KB
Audio device underrun detected.
AV: 00:00:01 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/12KB
Audio device underrun detected.
AV: 00:00:01 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/12KB
Audio device underrun detected.
AV: 00:00:01 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/11KB
Audio device underrun detected.
AV: 00:00:01 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/33KB
Audio device underrun detected.
AV: 00:00:02 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/59KB
Audio device underrun detected.
AV: 00:00:02 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/62KB
Audio device underrun detected.
(Buffering) AV: 00:00:02 / 01:07:31 (0%) A-V:  0.000 Cache: 0.8s/61KB

Exiting... (Quit)
```
[twitter.log](https://github.com/mpv-player/mpv/files/11636126/twitter.log)

**Comment by LaserEyess** [comment]
> Same issue.

Yes, the issue is on twitter's side. I didn't imply it was a yt-dlp issue, I implied it was a twitter issue. They broke something or they blocked something.

**Comment by garoto** [comment]
The issue here is that twitter is returning mp4 media format that is un-playable with ffmpeg master for reasons unknown to me. `yt-dlp` can fetch the media referenced in OP no problem and mpv will play the resulting file with no issues. Twitter is serving `broken` HLS video content.

See this everyday on nitter instances.

**Comment by gunir** [comment]
> I was able to get satisfactory results by adding the `hls-447` format to my youtube-dl format from what I could find looks like twitter is using some odd encoding sizes. If you take the link and run `youtube-dl -F <link>` you will get a list of the native formats.

Yeah, pretty much how I solved this issue, I used this `bestvideo[height<=720][protocol*=m3u8]+bestaudio/best[height<=720][protocol*=m3u8]`
