### ISSUE TITLE
Bind "#" (hash, pound) in config / escape #

### ISSUE THREAD

**Issue by dnngll** [mpv-player/mpv#11765]
## Hello,

I looked through https://github.com/mpv-player/mpv/wiki, https://github.com/mpv-player/mpv/wiki/FAQ and https://mpv.io/manual/master, but couldn't find an answer on how to bind # to a key. I also tried the usual escape-characters, unfortunately to no result.

How can I bind #? Of course,

`#				cycle-values speed "10.0" "1.0"`

is not working. I am certain I missed the most simple step and am hoping, one of you can point me towards it...

Thanks : )

**Comment by avih** [comment]
> and https://mpv.io/manual/master, but couldn't find an answer on how to bind # to a key

Try near the very begining of the [input.conf syntax](https://mpv.io/manual/master/#input-conf-syntax) section.

Then you can continue to the next section (key names) to learn about other keys.

**Comment by dnngll** [comment]
Aaaargh,

I was hoping it wouldn't be **that** easy *lol*

I was searching for "escape" in https://mpv.io/manual/master, should have gone for "input.conf", "key names" or "binding" maybe...

What upsets me the most, is that I made myself an
```
@echo off
..\mpv.com --input-test --force-window --idle
```
batch-file ages ago, and didn't think of using it!

Thank you for your help @avih , very happy with

`SHARP			cycle-values speed "10.0" "1.0"`

now :)

**Comment by avih** [comment]
> Thank you for your help

You're welcome. Yeah, the manual is very bib and it's not always easy to find what you're looking for. If you have suggestionf for improvements of the relevant docs, do share.

**Comment by dnngll** [comment]
Maybe just adding "hash", "pound", "escape" and/or the likes to that section?

But I want to be honest, for someone altering their config at the beginning they should know. It's even in the sample file. It was just so long ago since I did that...
