### ISSUE TITLE
console.lua: Should console.lua expose a new option to control its minimum msg level?

### ISSUE THREAD

**Issue by catcake** [mpv-player/mpv#11761]
Would a pull request adding a new option to control this behavior (and updating the manual accordingly) be appreciated?

This is in console.lua's `log-message` handler, discarding all `trace` level messages:
https://github.com/mpv-player/mpv/blob/effc68063bc3b4c856d70b8c6800d5bdb072815c/player/lua/console.lua#L828-L832

I generally agree that printing trace-level messages to the console is unhelpful, but it would be nice to have the option, especially when writing scripts.

The option could be something like this:
```ini
script-opts-append=console-minimum_msg_level=trace
```

Using `console-minimum_msg_level=debug` as the default value would preserve the current functionality.

In addition to finalizing the new option's name, a color to style the newly-visible trace messages is necessary. Debug messages are currently #a09f93, so maybe grey darker than this?

**Comment by Traneptora** [comment]
You'd want to rename it `max_message_level` instead of `min_message_level` but yes, send a PR.
