### ISSUE TITLE
Vulkan doesn't work anymore since 29 may builds (amd w11)

### ISSUE THREAD

**Issue by alakittty** [mpv-player/mpv#11763]
### Important Information

Provide following Information:
- mpv version : mpv 0.35.0-427-geffc6806 built on Tue Jun 06 12:42:51 2023 (shichiro x86_64 -3) latest as of time of posting)
- Windows Version : Windows 11 22H2 build 22621.1702
- Source of the mpv binary : [shinchiro](https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230606/mpv-dev-x86_64-v3-20230606-git-effc680.7z)
- If known which version of mpv introduced the problem : vulkan worked fine on shinchiro 28 may build (that was built before you posted that vulkan faq thread)
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

On 28 may build the only config options I used were vo=gpu-next and gpu-api=vulkan, i have amd integrated gpu
When I recieved the 29 may build and vulkan didn't work I digged deeper and found the [faq](https://github.com/mpv-player/mpv/issues/11739) thread here and set the following in my mpv.conf
vo=gpu-next
gpu-api=vulkan
hwdec=vulkan
gpu-context=winvk
it still didnt work and hasnt worked since, though just putting vo=gpu-next mpv works.

### Expected behavior
mpv works with vulkan
### Actual behavior
it doesn't
### Log file

[output.txt](https://github.com/mpv-player/mpv/files/11659760/output.txt)
[privatebin for output if you don't want to download the file](https://privatebin.net/?c73d1d41f03aa9fd#9515UVGg9MD4RvXJRmJ59munYWfha5ZGjsRqzLz9ygej)

### Sample files

well just any video i open doesn't open(throws this error)

**Comment by philipl** [comment]
Your AMD drivers look old. Your reported Vulkan version is 1.2.196 which https://vulkan.gpuinfo.org/ shows is correlated to AMD driver version 2.0.204 which is over a year old at this point. It looks like the latest is 2.0.264. I recommend you upgrade and then try again.

The new functionality requires an expanded set of Vulkan capabilities, and is probably triggering a driver bug.

**Comment by alakittty** [comment]
@philipl  I know this is not the place to ask for it and i apologise for doing so, but i can't find how to upgrade drivers (i have never done that before), i tried searching the web but there are too many guides having many different methods and that baffles me. can you please tell me how to, or link to an accurate guide that a noob can follow?

**Comment by johnattan1** [comment]
> Your AMD drivers look old. Your reported Vulkan version is 1.2.196 which https://vulkan.gpuinfo.org/ shows is correlated to AMD driver version 2.0.204 which is over a year old at this point. It looks like the latest is 2.0.264. I recommend you upgrade and then try again.
 

There is an issue with Vulkan in mpv at the moment. It's not even possible to build libmpv with Vulkan enabled.
I just opened an issue about it: https://github.com/mpv-player/mpv/issues/11766

**Comment by alakittty** [comment]
alright i updated through [amd software](https://www.amd.com/en/support)  now i get this
[ffmpeg/video] hevc: Device does not support the VK_KHR_video_decode_queue extension!
what does this mean? is vulkan working, even if to some extent?

**Comment by johnattan1** [comment]
> alright i updated through [amd software](https://www.amd.com/en/support) now i get this [ffmpeg/video] hevc: Device does not support the VK_KHR_video_decode_queue extension! what does this mean? is vulkan working, even if to some extent? [ouput1.txt](https://github.com/mpv-player/mpv/files/11661296/ouput1.txt) https://privatebin.net/?7eb549f907308235#6mhEfsHZ9W1QNMDbM72Xbgs7K3oj16VLxTM8Kyv4br2L

You need to rebuild mpv from the master branch with appropriate mpv_option to enable Vulkan. (It's usually enabled by default if I remeber correctly)

**Comment by johnattan1** [comment]
> i believe that shinchiro builds already have it enabled

I understand that you're a noob, but can't expect people to spoon-feed you all the answers. 
Read the documentation, learn how to build mpv from source and make it work.
Using linux demands your willingness to apply yourself.

If you're on debian/ubuntu I can even give you the full instructions:


```
apt-get update && apt-get install -y build-essential yasm intltool autoconf libtool devscripts equivs libavutil-dev libavcodec-dev libswscale-dev  python3-dev cython3 g++ make automake pkg-config nasm git libc++-dev
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build
./use-ffmpeg-master
./update
echo "-Dvulkan=enabled" >> mpv_options
mk-build-deps -s sudo -i
./rebuild -j4

```

**Comment by alakittty** [comment]
>Using linux demands your willingness to apply yourself.
@johnattan1 you are mistaken jonathan, i have mentioned multiple times i am using windows, it is even mentioned in the title, and from your texts i get the feeling you don't know what shinchiro builds are. Please refrain from posting your linux related issues in this thread

**Comment by johnattan1** [comment]
Your problem could've been solved with a 5 second google search. Follow your own advice and learn. Imagine developing, hosting and supporting this software for free while having someone enter a forum with the sole purpose of filing bug reports ask how to install a driver. It's just infuriating that you don't see anything wrong with that.

**Comment by Jules-A** [comment]
> @johnattan1 you can stop pulling my leg alright i updated the drivers, now i get this error and am asking about that

I mean if you read the pinned FAQ in issues you would understand: https://github.com/mpv-player/mpv/issues/11739

Honestly don't know how someone can manage to miss a pinned issue.

Anyway if you just want to run in Vulkan, remove Vulkan from hwdec option and do something like auto-safe if software isn't fast enough.

**Comment by Jules-A** [comment]
> one thing to mention though https://vulkan.gpuinfo.org/listdevicescoverage.php?platform=windows&extension=VK_KHR_video_decode_queue states that first AMD Radeon(TM) Graphics driver version to support VK_KHR_video_decode_queue was 2.0.243 and mine is 2.0.262 but still doesn't work.

Ah, that looks like the [22-11-2 Vulkan video decode specific drivers](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-11-2-vlk-video-code-decode) which were also mentioned in the FAQ but according to the driver's patch notes only supported 5000/6000 series. Looking at the extentions supported in that link link you sent, 2.0.243 has Vulkan video decode extension but 2.0.262 does not.

**Comment by philipl** [comment]
Well, you got your drivers upgraded, great. As for what capabilities the AMD drivers have, we don't know. AMD may have published clearer guidance somewhere but all we know for sure is that the one special driver release has the extensions. They may not have integrated them into their mainline drivers yet. Your original problem was crashing initialising Vulkan and that was fixed by the driver upgrade. This issue can be resolved.

**Comment by Jules-A** [comment]
> if you hover over driver(?), it says "first know driver version supporting this feature/extension"

Zzz... Like I said, that specific driver has those extensions but I assume they weren't ready to roll them out to the normal driver releases so they aren't included (you can check for the extension on that page you linked manually).
