### ISSUE TITLE
Issue with conditional auto profiles and geometry

### ISSUE THREAD

**Issue by dnngll** [mpv-player/mpv#11767]
## Hello,

I have an issue with the conditional auto profiles that I was just setting up. I am running _mpv-x86_64-20230101-git-ad65c88.7z_ in portable mode on Windows 10 Pro 22H2. In order to rule everything else out, I deleted all files in the `portable_config`-folder, except for `mpv.conf`.

Now, my plan was to change the window size while playing audio. The weird thing is, that the only thing between `geometry=0:0` working or not is the first line (whether it's in a profile). My (very empty temporary) `mpv.conf`:

#### NOT working (the window is in the middle of the screen):
```
[audioshort]
profile-cond=not vid and duration <= 300
geometry=0:0
```

#### Working:
```
profile-cond=not vid and duration <= 300
geometry=0:0
```
(commenting out the first line will work as well. Am I missing something here?

Thanks in advance

**Comment by guidocella** [comment]
Duplicate of https://github.com/mpv-player/mpv/issues/8379. Geometry runtime changes are not yet implemented on Windows.

**Comment by dnngll** [comment]
Thanks @guidocella ,

didn't find that one!
