### ISSUE TITLE
How can I save the current video stream to disk?

### ISSUE THREAD

**Issue by howarddo2208** [mpv-player/mpv#11777]
I'm trying ytfzf to search and watch YouTube videos from terminal which uses mpv to play the video. Occasionally when I watch a video and see that it is valuable and wanting to save it, but couldn't do so while in mpv and having to download again with youtube-dl. I tried to look for the cached file, but people say it saves directly on RAM. 

Is there any way I can do this, ideally through a keybinding? Thank u guys

**Comment by guidocella** [comment]
Use `dump-cache`: https://mpv.io/manual/master/#input-commands-that-are-possibly-subject-to-change

**Comment by howarddo2208** [comment]
Thank you! I'm able to download with this mapping `shift+d dump-cache 0 no "/home/username/Downloads/mpv/${media-title}.mp4"`.
Btw, is there anyway I can use `$HOME` environment variable inside `input.conf`? I tried but got error from mpv every time

**Comment by guidocella** [comment]
You would have to define the binding in a Lua script instead.
