### ISSUE TITLE
Crashes on fullscreen on GNOME 3.14

### ISSUE THREAD

**Issue by mtngchi** [mpv-player/mpv#1177]
Currently using Debian Jessie, with GNOME 3.14, with the latest mpv version found on the repository (0.6.0-1). Ever since GNOME was updated, mpv started to crash whenever I go fullscreen, crashing gnome-shell alongside. At first I thought it'd only happen when I connect my laptop to my TV via HDMI, but it happens very often even disconnected. I can replicate it 90% of the time.

Tested with other players (SMPlayer, VLC), they worked fine.

i5-2410M 2.3GHz
6 GB RAM
Intel HD 3000

**Comment by mtngchi** [comment]
Tried the workaround. Didn't stop the mpv crash, but it did stop x.org from crashing.

This is really bugging me.

**Comment by wm4** [comment]
Apparently this is tracked in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762809

Good enough for us, closing.
