### ISSUE TITLE
`--gpu-context=wayland` doesn't work on nvidia after `egl-wayland` update to `1.1.12`

### ISSUE THREAD

**Issue by Gigas002** [mpv-player/mpv#11774]
### Important Information

Provide following Information:

mpv version:

```
mpv 0.35.0-435-g309a139e67 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Thu Jun 08 10:52:33 2023
libplacebo version: v5.264.0-289-gd9ad4c34
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```

linux destribution and version:

```
Operating System: Manjaro Linux
Kernel: Linux 6.3.6-x64v3-xanmod1
Architecture: x86-64
```

source of mpv binary: mpv-git from AUR: https://aur.archlinux.org/packages/mpv-git/

DM: wayland, KDE Plasma 5.27.5

dGPU: NVIDIA GeForce RTX 3060 Laptop; proprietary nvidia driver 530.41.03

### Reproduction steps

```
mpv video.mp4 --gpu-context=wayland --no-config -log-file=log.txt
```

### Expected behavior

Video/audio plays. Reproducable only on Nvidia

### Actual behavior

Error:

```
$ prime-run mpv video.mp4 --gpu-context=wayland --no-config -log-file=log.txt
 (+) Video --vid=1 (*) (h264 2560x1440 60.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
AO: [pipewire] 48000Hz stereo 2ch floatp
VO: [gpu] 2560x1440 yuv420p
[destroyed object]: error 7: importing the supplied dmabufs failed
[vo/gpu/wayland] Error occurred on the display fd, closing

Exiting... (Quit)
warning: queue 0x7f4f400dd950 destroyed while proxies still attached:
  zwp_linux_dmabuf_feedback_v1@38 still attached
  zwp_linux_dmabuf_feedback_v1@36 still attached
  zwp_linux_dmabuf_v1@37 still attached
```

It's also seems to fail to kill some processes (the error above is from the second attempt to run without rebooting).

Probably it's just nvidia drivers problem once again, but since no one has reported it and other software seems to work fine I decided to create an issue about it

### Log file

https://0x0.st/HcPc.txt

**Comment by Dudemanguy** [comment]
I haven't kept up with the state of nvidia drivers, but I thought you weren't supposed to use the eglstreams implementation anymore?

**Comment by Gigas002** [comment]
Unfortunately, I don't know in details, how this works. If you meant, that I should be using `GBM` instead of `EGLStreams`, I though so too, judging by info on [arch wiki page](https://wiki.archlinux.org/title/Wayland#Requirements). But at the same time I am sure, that `egl-wayland` package update caused `mpv` to fail in this use case scenario. I tried downgrading/upgrading only this package several times, so I can confirm it.
On the other hand, it seems like nvidia is [going to implement](https://www.phoronix.com/news/NVIDIA-545-Wayland-VLK-PRIME) better support for vulkan on wayland session in 545 drivers, so I hope at least `waylandvk` will work

**Comment by Reireiyan** [comment]
for me on the latest egl-wayland 1.1.12 mpv, started to crash with this error [destroyed object]: error 7: importing the supplied dmabufs failed. Downgrading back to 1.1.11 it started to work like normal.

**Comment by TheComputerGuy96** [comment]
@Gigas002 Can you get a log with `WAYLAND_DEBUG=1` set?

**Comment by Gigas002** [comment]
Sure, [here](https://0x0.st/HcId.txt) it is

**Comment by TheComputerGuy96** [comment]
![Carl Johnson saying "Ah shit, here we go again."](https://tenor.com/6CTN.gif)

**Comment by erik-kz** [comment]
> [3764652.585]  -> zwp_linux_buffer_params_v1@40.add(fd 51, 0, 0, 7680, 50331648, 6316052)

Those last two numbers mean that MPV is rendering using our tiled memory layout, which can't be displayed by an Intel / AMD GPU. This might be a bug in Kwin's implementation of the dma-buf v4 protocol, which the compositor uses to tell our driver which memory layouts it can import. If it's running on a non-NVIDIA GPU it shouldn't be advertising support for NVIDIA format modifiers.

**Comment by erik-kz** [comment]
This did turn out to be a bug in egl-wayland, not Kwin. It should be fixed by https://github.com/NVIDIA/egl-wayland/commit/ea70449fd94b5f866ea6189bf4f41f7c230cccfa

**Comment by Dudemanguy** [comment]
Cool, will close this then.
