### ISSUE TITLE
How do i turn on Hardware acc

### ISSUE THREAD

**Issue by touhamii** [mpv-player/mpv#11770]
Hi there
im on windows 10 with my old cpu i3-4160 who cant run 4k30fps
i have old gpu which is gt 730 who can do the job on other video players but im not sure how to do it ?

  - important note : Deinterlace Was On by mistake so when i turned this off my cpu could turn on  4K videos  (not all espicially 60fps high bitrate even my gt 730 could not)

**Comment by CounterPillow** [comment]
ctrl+h

**Comment by touhamii** [comment]
it's not working sadly

**Comment by CounterPillow** [comment]
ok

**Comment by Traneptora** [comment]
`hwdec=yes`

**Comment by touhamii** [comment]
https://imgur.com/a/eMdQ6zy
that means it worked ?

**Comment by Traneptora** [comment]
Is it playing fine?

**Comment by touhamii** [comment]
hwdec=yes 
seems to be working thank u 

important note : Deinterlace Was On by mistake so when i turned this off my cpu could turn on 4K videos (not all espicially 60fps high bitrate even my gt 730 could not)
