### ISSUE TITLE
`mpv_event_end_file` returns a reason which is not presented in `mpv_end_file_reason`

### ISSUE THREAD

**Issue by Reverier-Xu** [mpv-player/mpv#11779]
### Important Information

Provide following Information:

- mpv version: mpv 0.35.1-dirty Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects built on Fri Apr 21 07:11:25 2023
- Platform and Version: Arch Linux x86_64 rolling
- Source of the mpv binary: from Arch Linux official repository extra/mpv

- [x] If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Hi, I'm writing a media player using libmpv, I found that when I try to load another file using command `load-file` when mpv is playing one, the `MPV_EVENT_END_FILE` signal will be emitted after `MPV_EVENT_FILE_LOADED`, so i add a check here:

https://github.com/Reverier-Xu/BitWave/blob/ba069ba03a1b9214ebe6ebb8ba42f1e67493b7a1/src/player/engine.cc#L84

```c++
        case MPV_EVENT_END_FILE: {
            auto* eventPtr = (mpv_event_end_file*) event;
            if (eventPtr->reason != MPV_END_FILE_REASON_STOP && eventPtr->reason != MPV_END_FILE_REASON_REDIRECT) {
                qDebug() << eventPtr->reason;
                emit ended();
            }
        }
```

your API doc [here](https://github.com/mpv-player/mpv/blob/1c82d6ae7a31f8ef3a3f5120bd50480c312039cf/libmpv/client.h#L1448) described 5 reasons, and the `MPV_END_FILE_REASON_STOP` reason is used for 

> Playback was stopped by an external action (e.g. playlist controls).

But in my case, this API returns 7, which is not presented in this reason enum.

### Expected behavior

the event returns a reason `MPV_END_FILE_REASON_STOP`.

### Actual behavior

the event returns a reason 7 which is not contains in the reason enum.

### Log file

[GitHub gists](https://gist.github.com/Reverier-Xu/e8c0c4d8c766200e70e3c83a395927cf#file-mpv-log-L1086)

**Comment by sfan5** [comment]
> `            auto* eventPtr = (mpv_event_end_file*) event;`

You need to cast `event->data`, not the event itself.
