### ISSUE TITLE
[Android] HDMI Output

### ISSUE THREAD

**Issue by KakarottoCake** [mpv-player/mpv#11772]
### Expected behavior of the wanted feature
When connected to HDMI, output the video to the display connected for accurate screen resolution of desired video. 
### Alternative behavior of the wanted feature
N/A

VLC does this, but their implementation for subs is questionable for anime which is why I would love to see this on MPV

**Comment by CounterPillow** [comment]
You should not report Android issues to this repository, but to https://github.com/mpv-android/mpv-android
