### ISSUE TITLE
icc-cache-dir always empty? how to view lcms2 generated luts?

### ISSUE THREAD

**Issue by 24fpsDaVinci** [mpv-player/mpv#11787]
### Important Information

Provide following Information:
- mpv version: master
- Linux Distribution and Version: fedora 39
- Source of the mpv binary: master

im trying to access the icc 3dlut cache dir. I set icc-3dlut-size and "icc-cache-dir=~/mpv3dluts/" but mpv doesnt seem to save anyting inside. I checked the logs there's nothing about luts as far as i can tell.

does a particular profile required to trigger 3dlut generation by lcms2? do simple edid based matrix profiles trigger 3dlut generation?  I've tried both XYZlut profiles and edid based profiles.

**Comment by Dudemanguy** [comment]
Since 4502522a7aee093c923e79a65e4684ea2634af30, you need to set the `icc-cache`if you want to save cache.

**Comment by 24fpsDaVinci** [comment]
thanks, i can see it now. are these files standard iridas cube files but compresed? is it possible to view the contents?
