### ISSUE TITLE
Request that --merge-files merges files not just durations

### ISSUE THREAD

**Issue by LateAdopter** [mpv-player/mpv#1178]
Like many set top boxes that have a USB PVR capability, my satellite receiver records transport stream in 2GB binary chunks to a FAT32 formatted disk. So there is a single stream spanning multiple files.

In order to play it correctly without discontinuities it is necessary to read the data into the buffer continuously, without modification from the consecutive files.

--merge-files actually plays them as separate files with a discontinuity. The EBU allows random access points to be up to 5 seconds apart, which can be quite significant.

This approach only applies to stream containers like PS and TS with continuous timestamps etc. but, rather than determine this it might be easier for the user to specify a different parameter e.g. --span-files

**Comment by NewUserLinux** [comment]
> mpv ffmpeg://concat:data0001.ts|data0002.ts|data0003.ts|data0004.ts


It does not work in mpv 0:19:0  :(

**Comment by wm4** [comment]
That's ffmpeg's fault.

**Comment by LateAdopter** [comment]
It looks like Rémi Denis-Courmont (VLC) is to blame really...
[url]http://lists.libav.org/pipermail/libav-devel/2016-January/074317.html[/url]

Sad, I guess I'll never have MPV with concat and vavpp motion-compensated at the same time!

**Comment by wm4** [comment]
Also I just tried and it works with ffmpeg.

**Comment by LateAdopter** [comment]
Yes! I tried with Doug McMahon's mpv_0.19.0-xenial_amd64 and it still works.

NewUserLinux, I don't understand your file naming, but I put spaces in my filenames and the protocol doesn't seem to mind. No need for quotes.
I put ffmpeg://concat:data 0001.ts|data 0002.ts in a text file and gave it a .m3u extension, put it in the directory where the files are. With the terminal there I did:
mpv --load-unsafe-playlists *.m3u
That worked OK

**Comment by tobia** [comment]
I can confirm that ffmpeg's concat protocol is the only way I could find to play back segmented video recordings, such as those taken from a DVR or from web stream ripping, without giving up a whole progress bar, correct seeking, and no gaps between the segments.

On Bash I use the following shortcut to generate the url:

    mpv ffmpeg://concat:$(IFS='|'; f=(segment*.ts); echo "${f[*]}")

If the files are numbered without leading zeros, you need to explicitly glob them in increasing number of digits to get the correct sequence:

    mpv ffmpeg://concat:$(IFS='|'; f=(segment{?,??,???}_1_av.ts); echo "${f[*]}")

I have tried a few playlist formats, including hls (m3u8) [as suggested in that same ffmpeg thread](http://lists.libav.org/pipermail/libav-devel/2016-January/074457.html), but none gave me the features listed above: a single progress bar, sane seeking, and gapless playback. (Maybe I didn't do it right. Any suggestions are welcome.)

I don't know what the ffmpeg guys were thinking, to remove this feature! I guess I'll have to keep an old mpv binary around, just to watch my DVR recordings, or maybe re-patch ffmpeg with the concat protocol. Unbelievable! Time to subscribe to their mailing list and rant about it.

**Comment by haasn** [comment]
You could perhaps try something like mpv <(cat *.ext), although seeking in that doesn't work (because it's technically a pipe).

**Comment by krackers** [comment]
Fyi, concat also works well with URLs! It's a nice way to stream a split file:

```
mpv 'lavf://concat:<url_1>|<url_1>'
```

Just be aware that you will need to patch `mpv` to change the default concat protocol whitelist to `concat,file,http,https,tcp,tls` (it seems that _that_ whitelist cannot be overriden by  `--demuxer-lavf-o=protocol_whitelist=...`)
