### ISSUE TITLE
How does mpv/lcms2 generate 3dluts based only on edid matrix profiles?

### ISSUE THREAD

**Issue by 24fpsDaVinci** [mpv-player/mpv#11788]
### Important Information

Provide following Information:
- mpv version: master
- Linux Distribution and Version: fedora 39
- Source of the mpv binary: master

Im trying to duplicate what mpv/lcms2 is doing, generating a 3dlut based on simple 3x3 matrix profiles generated from edid. Is there a particular lcms2 flag or documentation where i can find more information?

thanks

**Comment by haasn** [comment]
I'm not sure what you're confused about, but the source code is [all here](https://code.videolan.org/videolan/libplacebo/-/blob/master/src/shaders/icc.c).
