### ISSUE TITLE
No subtitle rendering after using sub-scale

### ISSUE THREAD

**Issue by sommio** [mpv-player/mpv#11789]
### Important Information

- mpv-git 0.35.0-436-g1c82d6ae7a / mpv 1:0.35.1-6
- Arch Linux
- [archlinuxcn](https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/mpv-git) / [ALHP](https://somegit.dev/ALHP/ALHP.GO)
- Mutter 44.2
- Nvidia 470.182.0

### Reproduction steps

1. `mpv "video.mkv" --no-config --sub-file=Sample.ass --fs=yes --start=2:53 --sub-scale=0.9`
2. `mpv "video.mkv" --no-config --sub-file=Sample.ass --fs=yes --start=2:53`
3. Compare whether to render "Loop througha silky ribbon, my pretender"

### Expected behavior

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/64189793/add24927-5484-4aa2-b075-aca8ec3db298)

### Actual behavior

![mpv-shot0002](https://github.com/mpv-player/mpv/assets/64189793/d9adf9d7-0f2b-4a32-82eb-064cc537f5e9)

### Log file

`mpv "video.mkv" --no-config --sub-file=Sample.ass --fs=yes --start=2:53 --sub-scale=0.9  --log-file=output.txt`
[output.txt](https://0x0.st/Hcd-.txt)

### Sample files

[Sample.ass](https://0x0.st/Hcdo.chs.ass)

**Comment by llyyr** [comment]
Please read the manual for this option.

> This affects ASS subtitles as well, and may lead to incorrect subtitle rendering. Use with care

Karaoke effects aren't simple and there probably isn't any way to not break them when using sub-scale, the next lines are also broken because they don't do the fade in effect

**Comment by sommio** [comment]
`--sub-ass-override=scale` works for me
