### ISSUE TITLE
wrong chapter titles on OSD with backwards chapter seeking

### ISSUE THREAD

**Issue by ProMarbler14** [mpv-player/mpv#11785]
### Important Information

- mpv version: mpv 0.35.0-438-g8ecf2d37eb
- Platform and Version: Arch Linux rolling (ffmpeg version n6.0)
- Source of the mpv: binary compiled using a PKGBUILD from the AUR. It uses mpv git tip.

### Reproduction steps
Attach a ffmetadata chapters file with --chapters-file, followed by an mp4 file to play. Chapters in this case numbered 50 and were 3-5 minutes average.
Seek to one of the chapters, with pgup. (note displayed chapter title)
Seek to the previous chapter before --chapter-seek-threshold (5 seconds) has elapsed. (note displayed chapter title)
(If you do a small seek, but still after the selected chapter start, the seek doesn't remove the issue)

### Expected behavior
Seeking forth should show the title of the chapter seeked to on the OSD (anchored at the top left). Seeking back quickly from that point should display the title of the previous chapter. Repeated chapter seeks backwards should also show the correct title.

### Actual behavior
Seeking to the chapter seeked to shows the correct chapter title on the OSD (anchored at the top left). Chapter-seeking back quickly from that point displays the title of the chapter seeked from (rather than the one seeked to). Repeated chapter seeks backwards usually also shows the next chapter's title (but not always).

**Comment by ProMarbler14** [comment]
[mpv-log.txt](https://github.com/mpv-player/mpv/files/11729626/mpv-log.txt)

**Comment by hubblec4** [comment]
I can confirm these.
The behavior is very random. Sometimes you can jump backwards two or three times and the fourth time it doesn't show the new chapter name.
Jumping forward always works.

**Comment by Dudemanguy** [comment]
Should have been fixed by https://github.com/mpv-player/mpv/pull/12444.
