### ISSUE TITLE
Set maximum cache in seconds or bytes

### ISSUE THREAD

**Issue by gd4c** [mpv-player/mpv#11804]
Can there be a user-set option (parameter/config) to set when mpv stops retrieving stream data?

Currently, it is set to 150MB, which (while being abundant for regular use) is too low if you want to pause and record a stream for offline playback.

Relevant: #1870

**Comment by Traneptora** [comment]
`--demuxer-max-bytes` controls this option.

**Comment by gd4c** [comment]
@Traneptora I tried it and it works. Thanks a lot.
