### ISSUE TITLE
vo=gpu-next: image with icc goes wrong with `--gamut-mapping-mode=perceptual`

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [mpv-player/mpv#11819]
https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230620/mpv-x86_64-v3-20230620-git-ee155d7.7z

`--gamut-mapping-mode=auto`
![image](https://github.com/mpv-player/mpv/assets/50797982/f26cf4a1-0e7d-4404-9ab3-8cc49f6bae9a)

`--gamut-mapping-mode=clip`
![image](https://github.com/mpv-player/mpv/assets/50797982/3b5e5892-f6ef-4627-a086-33e3f7d6f265)

samples:
![rgb-to-gbr-test](https://github.com/mpv-player/mpv/assets/50797982/19c1d141-c41b-47e1-ba6c-54d0289a55eb)

**Comment by haasn** [comment]
Okay, this is an expected result with such 'extreme' test images where the R/G/B vectors almost completely misalign with the source colorspace. You'll notice that `saturation` mode also breaks everything.

I think that the correct solution here would be to add a safety mechanism to the `perceptual` tone-mapper to prevent it from rotating the hue vector at all if it suspects such a profile.
