### ISSUE TITLE
Record the stream in the background from buffer without having to play it

### ISSUE THREAD

**Issue by lamyergeier** [mpv-player/mpv#11816]
I have url for a video (https://....), I want to record the entire stream, without having to play/watch currently. How can I record it without having to play the entire video? Basically I want mpv to buffer entire video and then save it as a file in the background.

The downloaded video would probably be of size 3 GB  (an estimate based on the resolution and length of the video) and I have sufficient RAM of 64 GB. Please specify any other CLI option that is necessary for cache, buffering entire video and recording.

**Comment by guidocella** [comment]
`--stream-dump=<destination-filename>`
