### ISSUE TITLE
libopenh264 is not found even though it is installed

### ISSUE THREAD

**Issue by mqrris** [mpv-player/mpv#11810]
- mpv version
```
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.3
```
- Linux Distribution and Version:
```
Red Hat Enterprise Linux 9.2 (Plow) x8 
5.14.0-284.11.1.el9_2.x86_64
```
### Reproduction steps
```
$ sudo dnf install mpv
$ mpv video.mkv
```
### Expected behavior
To open and play the video.
### Actual behavior
```
(+) Video --vid=1 (h264 1280x720 30.000fps)
(+) Audio --aid=1 'simple_aac' (aac 2ch 48000Hz)
[ffmpeg/video] libopenh264: libopenh264.so.7: cannot open shared object file: No such
file or directory: libopenh264.so.7 is missing, openh264 support will be disabled
Could not open codec.
Decoder init failed for libopenh264
Failed to initialize a decoder for codec 'h264'.
Video: no video

Exiting... (Errors when loading file)
```
### Log file
https://0x0.st/HTOx.txt

### What I tried to do to solve this:
Compiled and installed [openh264](https://github.com/cisco/openh264).
```
$ ls -l /usr/local/lib/
-rw-r--r--. 1 root root 2225680 Jun 19 17:43 libopenh264.a
lrwxrwxrwx. 1 kire kire      16 Jun 19 17:43 libopenh264.so -> libopenh264.so.7
-rwxr-xr-x. 1 root root 1712280 Jun 19 17:43 libopenh264.so.2.3.1
lrwxrwxrwx. 1 kire kire      20 Jun 19 17:43 libopenh264.so.7 -> libopenh264.so.2.3.1
drwxr-xr-x. 3 root root      25 Jun 16 20:34 node_modules
drwxr-xr-x. 2 root root      25 Jun 19 17:43 pkgconfig
drwxr-xr-x. 3 root root      27 Jun 16 04:08 python3.9
```

**Comment by kasper93** [comment]
Check if your `LD_LIBRARY_PATH` includes `/usr/local/lib/`

**Comment by CounterPillow** [comment]
> [ffmpeg/video] libopenh264: libopenh264.so.7: cannot open shared object file: No such
file or directory: libopenh264.so.7 is missing, openh264 support will be disabled

I can't find this message being produced in upstream FFmpeg anywhere, is this a RedHat patch to make it dynamically load openh264 at runtime due to patent bullshit?

Either way, not an mpv problem if the ffmpeg decoder wrapper is supposed to load it and somehow doesn't find it.

**Comment by Dudemanguy** [comment]
This has nothing to do with mpv. It's a distro packaging issue.
