### ISSUE TITLE
Different behiviours when using a CUBE lut vs --icc-profile

### ISSUE THREAD

**Issue by Isaacx123** [mpv-player/mpv#11817]
### Important Information
mpv displays a very washed out image when using --icc-profile instead of a user generated CUBE LUT of similar characteristics. 

Provide following Information:
- mpv 0.35.0-436-g1c82d6ae
- Windows 10 21H2
- Windows builds by shinchiro
- Possible screenshot or video of visual glitches:
https://slow.pics/c/ZTMYoLaC

--icc-profile screenshot:
![icc](https://github.com/mpv-player/mpv/assets/75648063/52deedef-6187-43ae-abdf-d5863db94ab5)

CUBE 3D Lut:
![3dlut](https://github.com/mpv-player/mpv/assets/75648063/2f656c8a-543d-41e8-84bc-4a66204fe756)

### Reproduction steps
First the parameters used in the CUBE Lut:
![image](https://github.com/mpv-player/mpv/assets/75648063/c3f44fac-cf75-4fbb-a702-1150118d9981)

ICC steps:
mpv --no-config --vo=gpu-next --icc-profile="G34WQC #1 2023-06-15 20-06 200cdm2 D6504 sRGB M-S XYZLUT+MTX.icm" --icc-3dlut-size=65x65x65 --log-file="icc.log" --autofit=1920x1080 --screenshot-format=png 00007.mkv

CUBE Lut steps:
mpv --no-config --vo=gpu-next --lut-type=conversion --lut="BT709.cube" --log-file="cube.log" --autofit=1920x1080 --screenshot-format=png 00007.mkv

### Expected behavior
Similar color and gamma reproduction between options. 

### Actual behavior
Washed out image when using the --icc-profile setting

### Log file
[icc.log](https://github.com/mpv-player/mpv/files/11814080/icc.log)
[cube.log](https://github.com/mpv-player/mpv/files/11814082/cube.log)

### Sample files
The video is correctly tagged with all the color information, MediaInfo:
![image](https://github.com/mpv-player/mpv/assets/75648063/bdaafd2f-2c14-45d3-9079-d3a5ddd1b77d)

Sample:
https://files.catbox.moe/yhz4oq.mkv

**Comment by haasn** [comment]
Can you share the ICC profile you used for testing?

**Comment by haasn** [comment]
Also, can you see if adding `--vf=format=gamma=gamma2.4` to the ICC profile makes it equal to the 3DLUT?

**Comment by Isaacx123** [comment]
> Also, can you see if adding `--vf=format=gamma=gamma2.4` to the ICC profile makes it equal to the 3DLUT?

That pretty much resolves the issue:
https://slow.pics/c/2McVDnxa

Now they look identical, ICC:

![icc+2 4](https://github.com/mpv-player/mpv/assets/75648063/890ff547-f371-49c9-a518-0c7970bf8143)

CUBE Lut:


![3dlut-2](https://github.com/mpv-player/mpv/assets/75648063/7e92de9a-92d9-471e-8d63-18ced28ed8dd)

ICC profile and CUBE LUT used:
https://files.catbox.moe/e8ibhr.zip

Could you explain why adding gamma2.4 as a video filter resolves the issue? Was the CUBE LUT was displaying the correct image then, right?

**Comment by natural-harmonia-gropius** [comment]
> Could you explain why adding gamma2.4 as a video filter resolves the issue?

Adjusting "Black output offset" to 0.1 and try again?

**Comment by Isaacx123** [comment]
You mean adjusting the CUBE LUT "Black output offset"?

**Comment by Isaacx123** [comment]
> > Could you explain why adding gamma2.4 as a video filter resolves the issue?
> 
> Adjusting "Black output offset" to 0.1% and try again without this filter?

The DisplaCAL's 3DLUT Maker only allows for 1 digit increments, no decimals.

**Comment by 24fpsDaVinci** [comment]
probably from mpv using media black point tag in the icc profile for bt.1886

```
G34WQC #1 2023-06-15 20-06 200cdm2 D6504 sRGB M-S XYZLUT+MTX.icm

    <mediaBlackPointTag> <XYZArrayType>
      <XYZNumber X="0.00035095" Y="0.00038147" Z="0.00041199"/>
    </XYZArrayType> </mediaBlackPointTag>
```

**Comment by Isaacx123** [comment]
So is my ICC profile wrong? Or is mpv wrong? Is the CUBE LUT correct or wrong? What is the correct behavior here?

**Comment by 24fpsDaVinci** [comment]
nothing is wrong. mpv is correct here, it uses the black point to calculate bt.1886 gamma, you will get crushed shadows without incorporating the black point luminance. 

mpv also generates a 65x65x65 cube lut using lcms2 on the fly. its more flexible than you generating bt709 source cube lut, since it works with bt2020 color space and probably other color space for images.  

the displaycal profile is also correct. theres probably a flag you can add to collink in displaycal to incorporate the black point when calculating bt1886 gamma.

**Comment by Isaacx123** [comment]
>you will get crushed shadows without incorporating the black point luminance.
The thing is that I am seeing plenty of shadow detail with the CUBE LUT.
The LUT generated by --icc-profile just looks plain wrong and washed out, not only do dark scenes look washed out but bright scenes look blown out. 
But you guys say this is normal behavior so I'll close the issue then.

**Comment by 24fpsDaVinci** [comment]
>  The LUT generated by --icc-profile just looks plain wrong and washed out, not only do dark scenes look washed out but bright scenes look blown out.
this is due to you profiling at 200 nits, you should go by the bt709 spec and calibrate/profile to100 nits for sdr content. also make sure theres no lighting in the room since colorimeters can have light leakage from the side which will give you incorrect reading. try the video preset option in displaycal dropdown menu for calibration and profiling.

**Comment by Isaacx123** [comment]
[SDR/HDTV gamma is relative](https://www.avsforum.com/threads/sdr-white-at-400-nits.3072132/post-58159766), I could have calibrated to 600 nits that it shouldn't be any problem, when creating the profile I took into account the room lighting, around 68 lux, the profile has this baked in to into the gamma calculation and finally, yes, I turned down the lights every time I do a calibration.

**Comment by 24fpsDaVinci** [comment]
high luminance = brighter black point which will affect bt.1886 calculation to make your image look 'washed out'. just note that sdr content is mastered at 100 nits you should follow it to get a reference image. the lightspace/colorspace guides do say to calibrate to 100 nits for sdr content, they even calculated 16-255 extended range to be 123.4 nits when using 3dluts.

https://www.lightillusion.com/forums/display-calibration-8/lg-oled-profiling-calibration-guides-775.html

**Comment by Isaacx123** [comment]
You should only calibrate to 100 nits for dark environments (around 5 to 10 lux), I am in a room with an ambient lighting of around 68 lux, this was taken into account during the calibration like I already said, from DisplayCAL's Tone curve/gamma section:
![image](https://github.com/mpv-player/mpv/assets/75648063/62b08f07-7698-4a7d-90fc-fb1caa02e387)

It is worth taking into account that DisplayCAL/ArgyllCMS don't use Black point compensation with LUT profiles like mine, the setting unchecks itself when you select a LUT type profile, from DisplayCAL's documentation:
![image](https://github.com/mpv-player/mpv/assets/75648063/48c7b695-42ff-4450-b536-d3c158f1bf66)

**Comment by 24fpsDaVinci** [comment]
bpc is automatically unchecked in displaycal when choosing XYZ lut because it affects color conversion. 

try the displaycal video preset. and read argyll usage scenarios for tv calibration. 

ambient measurement will cause lower contrast, its how it works. the washed out image is 'correct' for your 200 nits display and 68lux environment

**Comment by Isaacx123** [comment]
It did lower the contrast, from around 2980:1 to 2320:1, still plenty of contrast for not a dark room.
I will use the CUBE LUT, it simply looks correct on my viewing environment.

**Comment by 24fpsDaVinci** [comment]
https://hub.displaycal.net/forums/topic/measure-ambient-light/

**Comment by Isaacx123** [comment]
Yeah I will do it with no ambient lighting measurement.
 
>setting --vf=format=gamma=gamma2.4 will use pure power gamma 2.4 same as above more or less.

This pretty much solved the issue on the --icc-profile side, see this [post](https://github.com/mpv-player/mpv/issues/11817#issuecomment-1600748503) above.

**Comment by Isaacx123** [comment]
Still looks washed out with the new 2.2 gamma profile without ambient lighting measurement:

ICC:

![icc](https://github.com/mpv-player/mpv/assets/75648063/ced06279-4553-4e40-99cf-b8f607d1e1d9)

CUBE:

![cube](https://github.com/mpv-player/mpv/assets/75648063/d8530ed1-8b86-4371-b095-4f2d4c9a2b92)

ICC plus --vf=format=gamma=gamma2.4:

![icc+2 4](https://github.com/mpv-player/mpv/assets/75648063/bba4a0de-12ae-4535-8a1d-761c02103b8c)

LOGS:

[cube.log](https://github.com/mpv-player/mpv/files/11842962/cube.log)
[icc.log](https://github.com/mpv-player/mpv/files/11842963/icc.log)
[icc+24.log](https://github.com/mpv-player/mpv/files/11842964/icc%2B24.log)

Calibration report, ICC profile and CUBE LUT(assumed target whitepoint of 6700K because calibrating using CIE2012 2 degree):
https://files.catbox.moe/xviegu.zip

Settings used on the CUBE LUT:

![image](https://github.com/mpv-player/mpv/assets/75648063/9326d407-8b0c-4ec2-8638-5049f1c2b362)

Reproduction steps:

mpv --no-config --vo=gpu-next --lut-type=conversion --lut="rec709.cube" --log-file="cube.log" --autofit=1920x1080 --screenshot-format=png 00007.mkv

mpv --no-config --vo=gpu-next --icc-profile="G34WQC #1 2023-06-22 18-33 100cdm2 D6504 2.2 F-S XYZLUT+MTX.icm" --icc-3dlut-size=65x65x65 --log-file="icc.log" --autofit=1920x1080 --screenshot-format=png 00007.mkv

mpv --no-config --vo=gpu-next --icc-profile="G34WQC #1 2023-06-22 18-33 100cdm2 D6504 2.2 F-S XYZLUT+MTX.icm" --icc-3dlut-size=65x65x65 --vf=format=gamma=gamma2.4 --log-file="icc+24.log" --autofit=1920x1080 --screenshot-format=png 00007.mkv

**Comment by 24fpsDaVinci** [comment]
how does it look with icc profile + mpv --icc-force-contrast=inf

**Comment by Isaacx123** [comment]
Still elevated blacks:
![icc+inf](https://github.com/mpv-player/mpv/assets/75648063/a18a032c-df7e-4731-9c17-8662e38a0358)

[icc+inf.log](https://github.com/mpv-player/mpv/files/11843259/icc%2Binf.log)

>in displaycal how many neutral patches did you use in profiling step?
I don't know, I selected 425 auto-optimized patches for this profile, for the profile with the ambient light adjustment I select around two thousand auto-optimized patches.

**Comment by 24fpsDaVinci** [comment]
I tested your icc profile and your cube lut on my IPS monitor. mpv and icc profile behavior is correct. 

cube lut on the left, icc profile on the right. github applied some compression but you can see on the left theres lack of shadow detail and faces are too dark. the suit hes wearing is also completely crushed.

![Screenshot from 2023-06-22 22-19-36](https://github.com/mpv-player/mpv/assets/3499141/32a99e8b-01b2-44c9-b957-5dda0f878156)

[screenshot original.zip](https://github.com/mpv-player/mpv/files/11843376/screenshot.original.zip)

**Comment by Isaacx123** [comment]
My profile will never work well on an IPS because of the contrast difference, the reported contrast of the calibration is 2600:1 (according to rtings my monitor has a native contrast of 3100:1), meanwhile the average IPS has a contrast of 1000:1 or lower.
You cannot use my profile to measure near black/shadow detail performance on a display with less than two times the contrast ratio of the profile.
Talking about near black performance, the ICC LUT shows a lot of artifacts at it:

ICC:

![icc2](https://github.com/mpv-player/mpv/assets/75648063/39bbb003-fe95-4254-bad1-07b75980f8d8)

CUBE:

![cube2](https://github.com/mpv-player/mpv/assets/75648063/6b770d64-33e8-491d-ab16-8b4e524b44a2)

**Comment by 24fpsDaVinci** [comment]
> ICC LUT shows a lot of artifacts at it:

you are seeing more detail. the artifacts is from poor encoding job 
https://stackoverflow.com/questions/45103251/grey-squared-artifacts-after-hevc-10-bit-encoding-using-ffmpegs-nvenc-encoder

**Comment by Isaacx123** [comment]
Well, that's an untouched 30Mbit/s 1080p Blu-ray but live concerts are known for their less than sub optimal quality even if it's released on Blu-ray. 
I will trust your judgement, I will use the -icc-profile LUT.
So video calibration is just like audio, once you get some decent gear you can hear show badly compressed and mastered some songs are. 
I will leave the issue open for a couple of days more to see if someone else has something to add.
Thanks for all the information 👍

**Comment by haasn** [comment]
## Frame histograms

### ICC (no override)
```
  Channel statistics:
    Pixels: 2073600
    Red:
      min: 723  (0.0110323)
      max: 51929 (0.792386)
      mean: 6228.93 (0.0950474)
      median: 4132 (0.0630503)
      standard deviation: 7419.26 (0.113211)
      kurtosis: 17.0143
      skewness: 4.04117
      entropy: 0.794268
    Green:
      min: 848  (0.0129397)
      max: 62195 (0.949035)
      mean: 8859.53 (0.135188)
      median: 5700 (0.0869764)
      standard deviation: 9637.61 (0.14706)
      kurtosis: 11.979
      skewness: 3.39355
      entropy: 0.812977
    Blue:
      min: 1318  (0.0201114)
      max: 64822 (0.98912)
      mean: 15479.7 (0.236204)
      median: 10790 (0.164645)
      standard deviation: 12589.3 (0.192101)
      kurtosis: 5.27035
      skewness: 2.35624
      entropy: 0.827375
```

### .cube LUT
```
  Channel statistics:
    Pixels: 2073600
    Red:
      min: 0  (0)
      max: 51428 (0.784741)
      mean: 4438.04 (0.0677201)
      median: 2409 (0.036759)
      standard deviation: 7458.79 (0.113814)
      kurtosis: 18.6573
      skewness: 4.26231
      entropy: 0.768935
    Green:
      min: 52  (0.000793469)
      max: 62431 (0.952636)
      mean: 7084.07 (0.108096)
      median: 3786 (0.0577707)
      standard deviation: 9927.81 (0.151489)
      kurtosis: 12.087
      skewness: 3.40254
      entropy: 0.813705
    Blue:
      min: 260  (0.00396735)
      max: 65532 (0.999954)
      mean: 13918.7 (0.212386)
      median: 9216 (0.140627)
      standard deviation: 13011.9 (0.198548)
      kurtosis: 5.45178
      skewness: 2.37956
      entropy: 0.803806
```

### ICC (override)
```
  Channel statistics:
    Pixels: 2073600
    Red:
      min: 306  (0.00466926)
      max: 51467 (0.785336)
      mean: 4803.38 (0.0732949)
      median: 2833 (0.0432288)
      standard deviation: 7464.09 (0.113895)
      kurtosis: 17.8689
      skewness: 4.15296
      entropy: 0.787166
    Green:
      min: 318  (0.00485237)
      max: 62098 (0.947555)
      mean: 7166.67 (0.109356)
      median: 4201 (0.0641032)
      standard deviation: 9871.54 (0.15063)
      kurtosis: 12.161
      skewness: 3.41814
      entropy: 0.813754
    Blue:
      min: 297  (0.00453193)
      max: 64820 (0.98909)
      mean: 13894.6 (0.212018)
      median: 9069 (0.138384)
      standard deviation: 12962.2 (0.197791)
      kurtosis: 5.31834
      skewness: 2.36532
      entropy: 0.831805
```

Seems like the .cube LUT does possibly clip slightly into the black level (reaches value of 0), but either there's a bug in mpv or this sample is badly mastered. I haven't yet had time to look at the sample in depth.

**Comment by haasn** [comment]
Looking at the histograms in more detail, the .cube LUT only has a single value going down to absolute 0 red, so it seems correctly mastered.

Possibly there's a bug elsewhere in the system, causing mpv to over-estimate the ICC profile effective black point. Keep this open for now, I'll investigate further.

**Comment by Isaacx123** [comment]
Will keep open then.

**Comment by Isaacx123** [comment]
I did an experiment that may be relevant to the issue, I created a synthetic ICC profile with OLED characteristics and a CUBE LUT based on it, profile:
DCI-P3 D65 primaries
100 nits white level, 0.0001 nits black level (one million to one contrast ratio)
BT.1886 gamma

The gamma reproduction was identical between the two settings, ICC LUT:

![icc-oled](https://github.com/mpv-player/mpv/assets/75648063/31db7c84-eb38-4afd-96fb-c5e7ee2ba1b4)

CUBE LUT:

![cube-oled](https://github.com/mpv-player/mpv/assets/75648063/dd39c1a2-9125-4ed0-8ea9-5f9743e380ea)



[cube.log](https://github.com/mpv-player/mpv/files/11854038/cube.log)
[icc.log](https://github.com/mpv-player/mpv/files/11854039/icc.log)

**Comment by 24fpsDaVinci** [comment]
i did a quick test where i opened the same jpeg image in firefox, gimp and mpv. mpv shows format as mjpeg, gamma as bt.1886, colorspace as bt709 primaries when I pressed "i" keyboard shortcut. I also set absolute colorimetric in all three programs. the gamma and blackpoint looked identical in all three programs. Im using latest libplacebo master and mpv master.

**Comment by Isaacx123** [comment]
I have come to the conclusion that I was initially wrong and mpv's LUT is correct and the CUBE LUT is not, I was just confused because I have never seen that much black detail until calibration but two clips make me change my mind and showed mpv doing a better job at near black level than the CUBE LUT:

First example, severed arm:

Reference screenshot taken with the "s" key:

![Beatrice-Raws  Gekijouban Kimetsu no Yaiba Mugen Ressha Hen  BDRip 1920x1080 HEVC DTSHD _01_39_41 809_0001](https://github.com/mpv-player/mpv/assets/75648063/bff7a77a-a049-4ec1-8c07-45c8870034fc)

ICC LUT:

![Beatrice-Raws  Gekijouban Kimetsu no Yaiba Mugen Ressha Hen  BDRip 1920x1080 HEVC DTSHD _01_39_41 809_0002](https://github.com/mpv-player/mpv/assets/75648063/322f2b18-b45a-4c92-9109-9a38d3733924)

CUBE LUT:

![Beatrice-Raws  Gekijouban Kimetsu no Yaiba Mugen Ressha Hen  BDRip 1920x1080 HEVC DTSHD _01_39_41 809_0003](https://github.com/mpv-player/mpv/assets/75648063/d45dea49-16c1-4df3-ad1f-24e304491e30)

In the browser it looks slightly difference/more brighter than in mpv, but in mpv using the CUBE LUT all the detail of the muscle fibers are lost while the ICC LUT preserves them pretty well. 

Second example, chimney gargoyles:

Reference screenshot:

![Beatrice-Raws  Fate Stay Night - Unlimited Blade Works 00  BDRip 1920x1080 HEVC TrueHD _00_01_43 687_0001](https://github.com/mpv-player/mpv/assets/75648063/bc4f4b17-3dd3-4cc3-a750-ccc885e63576)

ICC LUT:

![Beatrice-Raws  Fate Stay Night - Unlimited Blade Works 00  BDRip 1920x1080 HEVC TrueHD _00_01_43 687_0002](https://github.com/mpv-player/mpv/assets/75648063/554292d8-385e-4a2b-a4ce-699b193941a0)

CUBE LUT:

![Beatrice-Raws  Fate Stay Night - Unlimited Blade Works 00  BDRip 1920x1080 HEVC TrueHD _00_01_43 687_0003](https://github.com/mpv-player/mpv/assets/75648063/33ee20f7-67fb-4383-8914-d953302cb0c1)

Again the image looks brighter in the browser, in mpv using the CUBE LUT the gargoyles in the right side of the chimney are completely lost, also the roof of the basement is completely darkened when in the reference screenshot and in the ICC LUT is clearly visible.

So again I was wrong, I am sorry if I wasted too much of your time @haasn 

I'll close the issue now.

**Comment by Isaacx123** [comment]
Another test just to confirm the ICC LUT is correct, a video black level:

ICC LUT:

![1-Black Clipping_00_00_10 886_0002](https://github.com/mpv-player/mpv/assets/75648063/adbb2fd4-eaf0-4c0c-9f36-630689c22206)

CUBE LUT:

![1-Black Clipping_00_00_02 711_0001](https://github.com/mpv-player/mpv/assets/75648063/b26fba45-2544-4ca4-803a-f8f26f523531)

**Comment by NSQY** [comment]
> Well, that's an untouched 30Mbit/s 1080p Blu-ray but live concerts are known for their less than sub optimal quality even if it's released on Blu-ray.

Unfortunately even UHD disks are often full of compression artifacts. 30mbps AVC is even worse, particularly in dark scenes. It's best to always be aware of this when configurating your media player.

**Comment by haasn** [comment]
@Isaacx123 great investigations, thanks and no worries

Always good to hear that we did the correct thing in the end :)
