### ISSUE TITLE
HDR playback (passthrough metadata to display) possible

### ISSUE THREAD

**Issue by Klaus1189** [mpv-player/mpv#11812]
Hey guys,
How do I setup mpv to play HDR video files? -> I want to **passthrough** HDR metadata to TV.

So I can then decide if I want tonemapping in mpv or let my diplay do the tonemapping.

Do I need to enable HDR in windows before playback? 
I would like to have an automatic toggle when starting a HDR file like madVR does.

I have Nvidia GPU

In Kodi my TV displays an OSD info that HDR metadata is received, but I can not get mpv to do this. But I want mpv.

Please help me :)

**Comment by kasper93** [comment]
Have you tried `--target-colorspace-hint`?

**Comment by Klaus1189** [comment]
Yes. But do I know if mpv reads this command in my conf file?

**Comment by Klaus1189** [comment]
I am sure I am doing something wrong. Do I need to install mpv for this featur? I use portable mode for now.

**Comment by adisib** [comment]
> Do I need to enable HDR in windows before playback? I would like to have an automatic toggle when starting a HDR file like madVR does.

For me, it will only automatically enable HDR in windows if using `--gpu-api=d3d11`, otherwise HDR has to be turned on in Windows first.

**Comment by Klaus1189** [comment]
colors are different with "--gpu-api=d3d11" but still no HDR OSD info of the TV.

Please help me :(

**Comment by Klaus1189** [comment]
Any other advices?

**Comment by Doofussy2** [comment]
> > There's no signaling. Your TV won't tell you that it's HDR.
> 
> huh? There is signaling.

My TV has never notified me that it is HDR, when using mpv.

**Comment by kasper93** [comment]
There are pople we use it on daily basis, it works. 

`--target-colorspace-hint` may work better with `--vo=gpu-next --gpu-api=d3d11`, can also try `--gpu-api=vulkan`, but `d3d11` should work better. Go fullscreen and Windows should passthrough HDR metadata to your display.

**Comment by Klaus1189** [comment]
The OSD message I want is also displayed of the TV when enabling the HDR switch in windows.
I want autoswitch to HDR without the need for me to enable HDR in windows.

**Comment by kasper93** [comment]
Check also this comment and thread with detailed testing https://github.com/mpv-player/mpv/issues/10628#issuecomment-1251249474

**Comment by dechamps** [comment]
You might also want to take a look at #10129.
