### ISSUE TITLE
save different parameters before quit

### ISSUE THREAD

**Issue by asklow** [mpv-player/mpv#11814]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
To save different parameters other than position. Such as brightness, contrast, saturation, zoom level, pan&scans, rotation, selected audio stream & subtitile, etc.

### Alternative behavior of the wanted feature
The current `save-position-on-quit` saves only the position metadata. Let the same method, procedure or codebase collect other parameters too, that affect the temporary playback behaviour, inorder to retain the same configuration for a media file.
**[OR]**
Write separate codebase for each metadata such as `save-brightness-on-quit`, `save-sub-on-quit`, etc...

**Comment by Dudemanguy** [comment]
Already exists. See `--watch-later-options`.
