### ISSUE TITLE
Possible to make audio not stutter on high CPU usage?

### ISSUE THREAD

**Issue by HubKing** [mpv-player/mpv#11826]
My CPU has 2 cores and 4 threads. When I install system update, especially from AUR, if I am playing a video on MPV, the audio stutters. This should not be disk I/O, because there was enough cache and I was playing the video from a network storage. The overall CPU usage was about 50%, not 100%, so I guess there is some room there, and when I was using Windows and another video player, I hardly remember hearing audio stuttering under a similar situation.

I wonder if there is a way to make audio not stutter in this situation under Linux.

**Comment by t-8ch** [comment]
Are you using the pipewire AO?

If so, does it also happen on latest master *or* with `PIPEWIRE_CONFIG_NAME=client-rt.conf` set as environment variable?

**Comment by HubKing** [comment]
> Are you using the pipewire AO?

I am not sure but probably I am using Pipewire. It's an Arch-based, and the output of `ps -e | grep pipewire` was

     1274 ?        00:29:23 pipewire
     1276 ?        00:11:46 pipewire-pulse

But to test `PIPEWIRE_CONFIG_NAME=client-rt.conf`, I need to reproduce the AUR update, but since I have already updated everything, I cannot do it right now. I will close this issue for now, and next time I need to update AUR, I will try that. If that doesn't fix the stuttering, I will then come back and re-open this issue.

**Comment by kasper93** [comment]
> But to test PIPEWIRE_CONFIG_NAME=client-rt.conf, I need to reproduce the AUR update, but since I have already updated everything, I cannot do it right now. I will close this issue for now, and next time I need to update AUR, I will try that. If that doesn't fix the stuttering, I will then come back and re-open this issue.

It is runtime flag, no need to rebuild anything.
