### ISSUE TITLE
How to build mpv with Rosetta2 installed Apple Silicon Mac

### ISSUE THREAD

**Issue by xanadu6291** [mpv-player/mpv#11827]
### Important Information

Provide following Information:
- mpv version: Git head (0.35-unkown)
- macOS Version: macOS.13.4.1 Ventura
- Source of the mpv binary or bundle: Git head
- If known which version of mpv introduced the problem: un-related
- Possible screenshot or video of visual glitches: None

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

1.Install Rosetta2 on Apple Silicon Mac
2.Follow following build steps:
git clone https://github.com/mpv-player/mpv.git
cd mpv
export CFLAGS="-arch arm64"
export CPPFLAGS="-arch arm64"
meson setup --prefix ${TARGET} \
--default-library=static \
build
meson compile -C build

While linking target, I get the following warning:
[225/225] Linking target mpv
ld: warning: ignoring file generated/osdep/macOS_swift.o, building for macOS-arm64 but attempting to link with file built for unknown-x86_64

And the resulting binary crashes with the following error:
% mpv ~/Movies/Mayuki\ Ito\ \&\ Remu\ Suzumori\ -\ LOVE\ MY\ LIFE\ \[KNPjbGaLf-0\].webm
dyld[79877]: symbol not found in flat namespace '_OBJC_CLASS_$__TtC11macOS_swift19RemoteCommandCenter'
zsh: abort      mpv 

### Expected behavior
Build mpv with Rosetta2 installed Apple Silicon Mac

### Actual behavior
Can't build mpv with Rosetta2 installed Apple Silicon Mac

### Log file

Make a log file made with -v -v or --log-file=output.txt. If you use the Bundle
from a version later than 0.32 a default log is created for your last run at
~/Library/Logs/mpv.log. You can jump to that file via the Help > Show log File…
menu. Paste the log to https://0x0.st/ or attach it to the github issue, and
replace this text with a link to it.

In the case of a crash please provide the macOS Crash Report (Backtrace).
[mpv-2023-06-24-152118.ips.txt](https://github.com/mpv-player/mpv/files/11855845/mpv-2023-06-24-152118.ips.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Akemi** [comment]
set the target of the swift build via the `--swift-flags=`/`-Dswift-flags=` option (waf/meson). 

example: `--swift-flags=arm64-apple-macosx11.0`/`-Dswift-flags=arm64-apple-macosx11.0`

**Comment by xanadu6291** [comment]
Thank you very much.  Setting -Dswift-flags worked like a charm!!

**Comment by Akemi** [comment]
nice, then i am closing this one.
