### ISSUE TITLE
brightness decrease automatically such as inactive on GNOME

### ISSUE THREAD

**Issue by mattia-b89** [mpv-player/mpv#11834]
### Important Information

```
$ mpv --version
mpv 0.35.1-dirty Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Fri Apr 21 07:11:25 2023
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
FFmpeg version: n6.0
```
- Arch Linux
- binary from official repo
- GNOME 44.2 on Wayland
- mesa 23.1.3 (Intel w/ modesetting driver)

### Reproduction steps

Play any video file and wait without pressing any keys or move the cursor until screen brightness decrease (automatically dim screen when computer is inactive)

### Expected behavior

Brightness stays the same

### Actual behavior

Screen gets dimmer, like the computer is inactive

### Log file

No useful information

**Comment by CounterPillow** [comment]
Tell GNOME to implement the idle-inhibit protocol

**Comment by mattia-b89** [comment]
this one? https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/111

**Comment by mattia-b89** [comment]
this one is the implicated one: https://gitlab.gnome.org/GNOME/mutter/-/issues/20

**Comment by teohhanhui** [comment]
It was merged!

https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3145
