### ISSUE TITLE
Gamut excessively compressed in HDR when using new gamut mapping mode and target peak less then signal peak

### ISSUE THREAD

**Issue by NotMithical** [mpv-player/mpv#11838]
### Important Information

- mpv version: 0.35.0-453-g78285e98
- Windows Version: 10 22H2, build 19045.3154
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/
- If known which version of mpv introduced the problem: Since commit f1600ea
- Screenshot or video of visual glitches:
Target-peak same as signal peak (1000 nits): https://0x0.st/HQV0.jxl
Target-peak 1 nit below signal peak: https://0x0.st/HQVG.jxl
Worth noting that the difference is much more subtle in these screenshots. The image is far more desaturated than shown here.

### Reproduction steps

1. Load a file with bt.2020 primaries with --no-config --vo=gpu-next --target-colorspace-hint and --gamut-mapping-mode=perceptual/relative/etc
2. Set target-peak as little as 1 nit below signal peak

### Expected behavior
Content is tone-mapped while preserving the full gamut.

### Actual behavior
Gamut is heavily compressed/desaturated, almost looking like bt.709 content. In real scenes, tone mapping seems to be affected as well with changing the gamut mapping mode having little to no effect, but I don't know if that's related.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/11873442/output.txt)

**Comment by haasn** [comment]
I will look at it more closely, but I think this can be the result of a source that contains information outside of its stated reference gamut. If gamut mapping is active at all (even a tiny bit), you will see the effect of out-of-gamut parts of the source being processed through the (clipping) 3DLUT.

**Comment by haasn** [comment]
Hi, is this still an issue as of current libplacebo master?

**Comment by NotMithical** [comment]
Nope, it behaves as expected now. Thanks for looking into it!
