### ISSUE TITLE
videos from odysee.com have lag/desync after i installed libvdpau-va-gl1

### ISSUE THREAD

**Issue by internet-police** [mpv-player/mpv#11830]
not shure what to make of this but i wanted to report it anyways

### Important Information
- mpv version: 0.35.1
- Linux Distribution and Version: devuan chimaera (debian 11)
- Source of the mpv binary: github 
- Window Manager and version: i3 version 4.22
- GPU driver and version: xserver-xorg-video-intel/stable,now 2:2.99.917+git20200714-1+deb11u1 amd64
- Hardware: Thinkpad x230 with intel hd graphics 4000

i used to get this message when playing a video:
> [vo/gpu/opengl] Suspected software renderer or indirect context.
> Failed to open VDPAU backend libvdpau_va_gl.so: cannot open shared object file: No such file or directory
> [vo/vdpau] Error when calling vdp_device_create_x11: 1
> [vo/xv] Warning: this legacy VO has bad quality and performance, and will in particular result in blurry OSD and subtitles. You should fix your graphics drivers, or not force the xv VO.

so i installed libvdpau-va-gl1 and that message has gone away
but now when i play something from odysee, even in the lowest quality, it performs very very bad
youtube and everything else works no problem

i removed libvdpau-va-gl1 and the problem is gone

**Comment by CounterPillow** [comment]
don't install libvdpau-va-gl1 then, it's known garbage
