### ISSUE TITLE
Subtitle is by default not displayed. `--slang` is ignored. External subtitle is not selected.

### ISSUE THREAD

**Issue by jiangzhenjerry** [mpv-player/mpv#11836]
### Important Information

Provide following Information:
- mpv version: [MPV 2023-06-25 12:08](https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-06-25)
- Platform and Version: Windows 11 x64
- Source of the mpv binary:  [mpv-x86_64-v3-20230625-git-945d7c1.7z](https://github.com/zhongfly/mpv-winbuild/releases/download/2023-06-25/mpv-x86_64-v3-20230625-git-945d7c1.7z) 

### Reproduction steps

1. Start with empty/default settings.
2. Play a video with `--slang` option, for example, `mpv "path\to\your\video" --slang=en,eng`

### Expected behavior

If there is an external subtitle file, it will be selected and displayed. Otherwise, mpv will display an embedded subtitle matching the preferred language (in the example above, English).

### Actual behavior

No subtitle is displayed. External and internal subtitles are correctly loaded, but none of them are selected and displayed. User has to manually select a subtitle. See the screenshot below. This only happens in today's (6/25/2023) build. [Yesterday's build](https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-06-24) doesn't have this issue.

<img width="1442" alt="sshot-1" src="https://github.com/mpv-player/mpv/assets/9311082/3cbdea6a-6a07-431f-b2e6-45901d1988e7">

### Log file

In this log below, I didn't provide an external subtitle. 33 embedded subtitles are available, but none of them are selected, albeit my setting `--slang=en,eng`

[log.txt](https://github.com/mpv-player/mpv/files/11864065/log.txt)

### Sample files

N/A. Any video file with embedded or external subtitles will suffice.

**Comment by zhongfly** [comment]
Because this commit changed the default value https://github.com/mpv-player/mpv/commit/1669c4698d237eb885aa3f9c5b81983de6009418
If you want the old behavior, set `subs-with-matching-audio` to `yes`

**Comment by jiangzhenjerry** [comment]
Got it, thank you very much! Closing this issue for now...
