### ISSUE TITLE
set correct-downscaling=yes leads to Ortho (vert) and (horiz) downscaling (bicubic) even when no downscaling is needed

### ISSUE THREAD

**Issue by danbezerra** [mpv-player/mpv#11841]
Hello, as mentioned in the title, I'm trying to understand why correct-downscaling=yes triggers Ortho downscaling. Some details:

1. This is only happening for HDR titles (all HDR 4K rips I tried).  4K 709 and 1080p rips don't show the Ortho downscaling in the stats.
2. I'm using a 4K TV and confirmed that no scaling is needed (via stats, native and sized resolution are the same 3840x2160, scale: 1)
3. If I set correct-downscaling=no, I don't see the Ortho downscaling message any longer. But my understanding from the manual is that correct-downscaling may increase quality so I always left it active.
4. I'm using gpu-next, Windows, NVidia.
5. using the last MPV build from https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230627

Attaching my config file as FYI.

Is this normal? Why only on HDR titles? What is it actually downscaling here?
![ortho downscaling](https://github.com/mpv-player/mpv/assets/17623925/c61c2bde-ccb0-4c49-9c41-0dcc64fa8baf)
[mpv.txt](https://github.com/mpv-player/mpv/files/11884876/mpv.txt)

**Comment by lavilao** [comment]
I might be wrong but I think that the scaling done there (the pic) is on chroma aka the colors, maybe hdr does by default some cheap chroma downscaling and with correct-downscaling does the good one?

**Comment by danbezerra** [comment]
Yes, I also believe it's chroma downscaling. But why is the big question. If anything, it should be upscaling from 4:2:0 used in UHD movies via the KrigBilateral shader.

**Comment by haasn** [comment]
The downscaling you see there is the HDR feature extraction pass, used for HDR contrast recovery. If you set `--no-correct-downscaling`, it is forcibly disabled.

This is all working as intended, except for the part where I haven't hooked up the contrast recovery options to mpv yet.
