### ISSUE TITLE
vaapi freezes window when paused

### ISSUE THREAD

**Issue by haarp** [mpv-player/mpv#1184]
Hello,

I'm experiencing the following bug. When using vaapi, the window, when the movie is paused, seems to stop updating. The LUA GUI never shows up even during mouse movement. When other windows are shoved in front of mpv, they still show after being shoved away again. The effect is basically like when you SIGSTOP a process, except the window still responds to input. Unpausing playback works and restores functionality.

Prior to 0.6 (I think) this only happened occasionally, now it happens every time I pause a video.

libva info: VA-API version 0.35.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_35
libva info: va_openDriver() returns 0

**Comment by wm4** [comment]
Leaving this to Intel.
