### ISSUE TITLE
How to execute an action when mpv moves to (changes) another folder in a playlist?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#11855]
Specifically I want to play some chime* to indicate that mpv proceeded to a new folder — I frequently play artist discographies at once and don't have a good way to keep a track of album changes (all in their own directories), outside of constantly looking at terminal of course.

Should also apply to sub-directories.

*for instance any [static sound](https://commons.wikimedia.org/wiki/Category:White_noise)

**Comment by guidocella** [comment]
Observe the `path` property, get the directory with `utils.split_path(path)`, save the last directory in a variable, and whenever it changes use `subprocess` to play a chime by starting another mpv instance, or with `ffplay -nodisp -autoexit foo.opus`.

**Comment by 07416** [comment]
the `path` property, get the directory with `utils.split_path(path)`, save the last directory in a variable, and whenever it changes use `subprocess` to play a chime by starting another mpv instance, or with `ffplay -nodisp -autoexit foo.opus`.

I see, I assume LUA scripting. I'd more than love if anyone is able to spin a script prototype.

**Comment by guidocella** [comment]
```lua
local utils = require 'mp.utils'
local last_dir

mp.observe_property('path', 'string', function (_, path)
    if path == nil then
        return
    end

    local dir = utils.split_path(path)

    if last_dir and dir ~= last_dir then
        mp.command_native({
            name = 'subprocess',
            args = {'ffplay', '-nodisp', '-autoexit', '/path/to/chime.opus'},
        })
    end

    last_dir = dir
end)
```

**Comment by Dudemanguy** [comment]
Question was answered.
