### ISSUE TITLE
Broken HDR peak detection with vo=gpu-next and gpu-api=vulkan

### ISSUE THREAD

**Issue by ProxyVT** [mpv-player/mpv#11864]
### Important Information

Provide following Information:
- mpv version: 

      mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
      built on Tue Jan 01 12:00:00 1980
      FFmpeg library versions:
          libavutil       57.28.100
          libavcodec      59.37.100
          libavformat     59.27.100
          libswscale      6.7.100
          libavfilter     8.44.100
          libswresample   4.7.100
      FFmpeg version: 5.1.3
- Linux Distribution and Version:

      OS: NixOS 23.11pre499022.e18dc963075 (Tapir) x86_64 
      Kernel: 6.1.3 
      DE: Plasma 5.27.6 [KF5 ] [Qt ] (x11)
- Source of the mpv binary: `nixpkgs unstable` via [home-manager](https://github.com/nix-community/home-manager/blob/master/modules/programs/mpv.nix)
- If known which version of mpv introduced the problem: `current mpv release`
- Window Manager and version: `Kwin 5.27.6`
- GPU driver and version:

      GPU: NVIDIA GeForce GTX `660/PCIe/SSE2`
      NVIDIA-SMI 470.182.03
      Driver Version: 470.182.03   
      CUDA Version: 11.4  

### Reproduction steps

`mpv --no-config --vo=gpu-next --gpu-api=vulkan`

### Expected behavior

Video with HDR plays without errors and visual distortions

### Actual behavior

Video plays, but it may look darkened or grayish, as if due to a lack of contrast. Additionally, there are errors in terminal:

      [vo/gpu-next/libplacebo] Found no memory type matching property flags 0x3 and type bits 0x381!
      [vo/gpu-next/libplacebo]   for malloc: ../src/shaders/colorspace.c:1204
      [vo/gpu-next/libplacebo] No slab to serve request for   268 bytes (with alignment 0x30000) in pool 2!
      [vo/gpu-next/libplacebo] Failed creating peak detection SSBO!
      [vo/gpu-next/libplacebo] Failed creating HDR peak detection shader.. disabling
      [vo/gpu-next/libplacebo] Attempting to modify a failed shader!
      [vo/gpu-next/libplacebo] Attempting to modify a failed shader!
      [vo/gpu-next/libplacebo] Trying to dispatch a failed shader.
      [vo/gpu-next/libplacebo] Failed rendering image!
      [vo/gpu-next] Failed rendering frame!

### Log file

[output1.txt](https://github.com/mpv-player/mpv/files/11914453/output1.txt)
[output2.txt](https://github.com/mpv-player/mpv/files/11914456/output2.txt)
[output3.txt](https://github.com/mpv-player/mpv/files/11914459/output3.txt)

### Sample files
[Video1](https://www.youtube.com/watch?v=tO01J-M3g0U&pp=ygUJaGRyIHZpZGVv)
[Video2](https://www.youtube.com/watch?v=rJNBGqiBI7s&pp=ygUIaGRyIDEwODA%3D)
[Video3](https://www.youtube.com/watch?v=MLXvyqJWQ9A&pp=ygUMaGRyIHZpZGVvIDRr)

**Comment by haasn** [comment]
Seems we need a fallback path for this case. I'll add it.

**Comment by haasn** [comment]
Can you test if https://code.videolan.org/videolan/libplacebo/-/merge_requests/486 fixes it?

**Comment by ProxyVT** [comment]
> Can you test if https://code.videolan.org/videolan/libplacebo/-/merge_requests/486 fixes it?

Hey there, apologize for the delay! I finally managed to compile mpv with the latest release of libplacebo 6.292.0, where you fixed this bug. Unfortunately, now none of the videos can being played correctly with vulkan API. If I run `mpv --no-config --vo=gpu-next --gpu-api=vulkan`, console gives the following error:

    [vo/gpu-next/libplacebo] Missing device feature: dynamicRendering
    [vo/gpu-next/libplacebo] Vulkan device does not support all required features!
    [vo/gpu-next/libplacebo] Failed creating logical device!
    [vo/gpu-next/libplacebo] Failed initializing vulkan device
    [vo/gpu-next/libplacebo] Missing device feature: dynamicRendering
    [vo/gpu-next/libplacebo] Vulkan device does not support all required features!
    [vo/gpu-next/libplacebo] Failed creating logical device!
    [vo/gpu-next/libplacebo] Failed initializing vulkan device
    [vo/gpu-next] Failed initializing any suitable GPU context!
    Error opening/initializing the selected video_out (--vo) device.

When I run command without `--vo=gpu-next`, behavior is the same, except player fallback to `vdpau` VO.

**Comment by ProxyVT** [comment]
Tested the master branch of libplacebo. Now, when playing HDR content, there are several errors indicating that fallback buffer will be used, but peak detection is working correctly, so the issue is indeed fixed.

<p>
<details>
<summary>Comparision</summary>


libplacebo 5.264
![mpv-shot0003](https://github.com/mpv-player/mpv/assets/86965169/0a72c70b-5f5d-4a3e-8378-a748371012d1)
libplacebo master
![mpv-shot0002](https://github.com/mpv-player/mpv/assets/86965169/ed5bd5ec-62d2-44bf-8dfe-82176ad645f7)


</details>
</p>
