### ISSUE TITLE
screenshot-jpeg-source-chroma does not work: screenshot is always YUV444.

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#11860]
### Important Information

Provide following Information:
- mpv version: [shinchiro 20230629 2f220c6](https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230629/mpv-x86_64-v3-20230629-git-2f220c6.7z)
- Platform and Version: Windows 11 22621.1928
- Source of the mpv binary: [shinchiro](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230629)

### Reproduction steps
Open any 4:2:0 video, which should be just about any video. You can verify with mediainfo, ffprobe, mkvinfo, etc. Take a screenshot with s, C-s, or S-s, doesn't matter.

### Expected behavior
The screenshot should be 4:2:0 since screenshot-jpeg-source-chroma defaults to yes.

### Actual behavior
The screenshot will always be 4:4:4 regardless of the chroma layout of the video.

I incidentally also tested it with vo=gpu-next, and explicitly setting screenshot-jpeg-source-chroma=yes, and neither changed the behavior. This issue may or may not have anything to do with https://github.com/mpv-player/mpv/issues/11850. I don't know how to investigate which way shinchiro's builds are writing the image, it would be nice if someone on Linux could repro.

### Log file

https://pomf2.lain.la/f/ygo0mvvm.txt

### Sample files

https://pomf2.lain.la/f/k1fahjqe.webm
https://pomf2.lain.la/f/thw5hbdq.jpg

**Comment by hooke007** [comment]
win build without libjpeg could repro it

**Comment by Traneptora** [comment]
Do you have `screenshot-sw=yes`? If not (the default), you have hardware screenshots enabled, and it will be taking it from the hardware buffer, which is typically in RGB. So source chroma *is* actually 4:4:4.

**Comment by sizumam** [comment]
With `screenshot-sw=yes` the screenshot jpeg has 4:2:0 chroma as expected. The current behavior still seems like a bug to me, since the GPU texture is hardly the "source" and you're still wasting bits encoding interpolated chroma not present in the video file.

**Comment by Dudemanguy** [comment]
Don't think this is actually a bug? There's a reasonable enough workaround anyway so closing (plus OP is a ghost).
