### ISSUE TITLE
Corrupted output with vulkan video decoding

### ISSUE THREAD

**Issue by HolyWu** [mpv-player/mpv#11866]
### Important Information

Provide following Information:
- mpv version:
```
mpv 0.35.0-453-g78285e98 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jun 25 12:21:56 2023
libplacebo version: v6.287.0-rc1-14-g9b4e561
FFmpeg version: N-111273-g10f1bbfe1
FFmpeg library versions:
   libavutil       58.13.101
   libavcodec      60.21.100
   libavformat     60.9.100
   libswscale      7.3.100
   libavfilter     9.8.102
   libswresample   4.11.100
```
- Platform and Version: `Windows 11 22H2`
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20230625-git-78285e9.7z/download

### Reproduction steps

`mpv --no-config --vo=gpu-next --gpu-api=vulkan --hwdec=vulkan LIGHT_YEARS_AWAY.mp4`

### Expected behavior

Decoded output without distortion.

### Actual behavior

The decoded output are corrupted/blocky/jumpy.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/11918668/output.txt)

### Sample files

https://github.com/mpv-player/mpv/assets/5151987/55e6dfde-f02b-4bee-8605-e181664fe26e

**Comment by philipl** [comment]
It is driver related at least. Decodes correctly on intel but not nvidia.

**Comment by philipl** [comment]
@cyanreg reports that at least on linux, the beta drivers fix the problem. Either way, it's clearly an nvidia driver problem. I'm going to close as there's nothing we can do.
