### ISSUE TITLE
hwdec fallback failure

### ISSUE THREAD

**Issue by arm64-v9a** [mpv-player/mpv#11865]
### Important Information

Provide following Information:
- [mpv version](https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230630/mpv-x86_64-v3-20230630-git-40a1b00.7z)
- Windows Version 
  23H2
- If known which version of mpv introduced the problem
  N/A
- Possible screenshot or video of visual glitches
  N/A

### Reproduction steps
Requires a Vulkan device that does not support `VK_MESA_video_decode_av1` (NVIDIA RTX3070 LP Windows DCH Driver)

`mpv --no-config --vo=gpu-next --hwdec=vulkan,nvdec --msg-level=vd=trace --gpu-context=winvk AV1_Video.mkv`

### Expected behavior
```
[vd] Codec list:
[vd]     vp9 - Google VP9
[vd]     libvpx-vp9 (vp9) - libvpx VP9
[vd]     vp9_cuvid (vp9) - Nvidia CUVID VP9 decoder
[vd]     vp9_qsv (vp9) - VP9 video (Intel Quick Sync Video acceleration)
[vd] Opening decoder vp9
[vd] Looking at hwdec vp9-nvdec...
[vd] Trying hardware decoding via vp9-nvdec.
[vd] Selected codec: vp9 (Google VP9)
[vd] Pixel formats supported by decoder: dxva2_vld d3d11va_vld d3d11 cuda yuv420p10le
[vd] Codec profile: Profile 2 (0x2)
[vd] Requesting pixfmt 'cuda' from decoder.
Using hardware decoding (nvdec).
```
The av1 video should fall back to nvdec just like the vp9 video
### Actual behavior
```
[vd] Codec list:
[vd]     libdav1d (av1) - dav1d AV1 decoder by VideoLAN
[vd]     av1 - Alliance for Open Media AV1
[vd]     av1_cuvid (av1) - Nvidia CUVID AV1 decoder
[vd]     av1_qsv (av1) - AV1 video (Intel Quick Sync Video acceleration)
[vd] Opening decoder libdav1d
[vd] Looking at hwdec av1-vulkan...
[vd] Trying hardware decoding via av1-vulkan.
[vd] Using underlying hw-decoder 'av1'
[vd] Selected codec: libdav1d (dav1d AV1 decoder by VideoLAN)
[vd] Pixel formats supported by decoder: dxva2_vld d3d11va_vld d3d11 cuda vulkan yuv420p10le
[vd] Codec profile: Main (0x0)
[ffmpeg/video] av1: Device does not support decoding av1!
[vd] Hardware decoding of this stream is unsupported?
[vd] Requesting pixfmt 'yuv420p10le' from decoder.
[ffmpeg/video] av1: Your platform doesn't support hardware accelerated AV1 decoding.
[ffmpeg/video] av1: Failed to get pixel format.
Error while decoding frame (hardware decoding)!
[vd] Falling back to software decoding.
```
This bug should be reproduced on any Vulkan GPU that does not support `VK_MESA_video_decode_av1`
### Log file

N/A

### Sample files

N/A

**Comment by philipl** [comment]
It doesn't fall back properly on Linux either. Looks like the issue is where exactly it fails, and that error path doesn't move on to the next option properly. It should be fixable.

**Comment by hooke007** [comment]
Sth worse more happened here. hwdec fall back cannot work for hevc.

`hwdec=auto-copy,nvdec-copy` directly fall backed to SW for yuv444
[test.log](https://github.com/mpv-player/mpv/files/11925345/test.log)
