### ISSUE TITLE
Repeat button in the osc

### ISSUE THREAD

**Issue by lgbaldoni** [mpv-player/mpv#11878]
### Expected behavior of the wanted feature
When the repeat button is toggled, the media will restart playing from the beginning.

### Alternative behavior of the wanted feature
When the button is clicked, the media will rewind and restart playing (to use with `--keep-open=yes`)

### Log file
Does not apply

**Comment by hooke007** [comment]
both could be easily done by input
```
<key> cycle-values loop-file inf no
```

```
<key> seek 0 absolute-percent ; set pause no
```
