### ISSUE TITLE
Most suitable settings for streaming unfinished file?

### ISSUE THREAD

**Issue by xeon826** [mpv-player/mpv#11884]
Assuming the moov atom is present, and a good amount of the beginning of the file is there as well, are there settings that are more suitable to play an unfinished file? I get odd behavior when doing this sometimes because my best guess is that It seems like mpv wants to prepare a certain portion of the file despite that it's not complete yet, could the solution be to tell mpv to only ready a smaller amount of the file when playing it?

### Log file
https://0x0.st/H1ax.txt

**Comment by snylonue** [comment]
see the description of  `appending://` [protocal](https://mpv.io/manual/master/#protocols)
