### ISSUE TITLE
Bt.2446a or spline

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#11883]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

Hi there just a quick question I was just wondering which tonemapping method people prefer to use out of bt.2446a and spline and if possible which one would get me the closest to the tonemapping which madvr uses 

Thanks,

**Comment by Hrxn** [comment]
User IRC Channel: #mpv on irc.libera.chat

**Comment by haasn** [comment]
I recommend using spline in combination with HDR peak computation, because that curve will take into account the scene average brightness and adjust the exposure as necessary.

**Comment by laichiaheng** [comment]
@haasn Hi, would you recommend the same algorithm for inverse tone-mapping videos?

**Comment by haasn** [comment]
I don't have any recommendations for inverse tone mapping, since it's not a use case that's been well-tested or designed.
