### ISSUE TITLE
Switching input languages doesn't work when mpv is in focus

### ISSUE THREAD

**Issue by rockmor** [mpv-player/mpv#11881]
### Important Information

mpv version: v0.35.1
Windows 11 Pro

### Reproduction steps
Open mpv with Russian layout on
Try to switch the layout, it doesn't change

I use several languages. Sometimes I accidentaly open mpv with Russian input on, and because of that no shortcuts work. The problem is that when I try to switch the input language inside mpv (with either SHIFT+CTRL or SHIFT+ALT), it doesn't work either, so I have to close mpv, switch languages and open it again, which is annoying.
--no-config doesn't resolve the problem.

### Expected behavior
I can freely switch input languages with mpv opened and in focus.

### Actual behavior
I can't.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/11930306/output.txt)

**Comment by avih** [comment]
> I have to close mpv

You can click on the language bar at the task bar and select an input language.

I'm not sure why switching language using keyboard doesn't work when mpv is focused, but I can reproduce it on Windows 10.

**Comment by rockmor** [comment]
@avih 
Thanks for the advice, I didn't think of that for some reason. Not an ideal solution, but it works.

**Comment by avih** [comment]
Yeah, not ideal, but works.

I didn't look at the code, but I'm guessing mpv captures KB events in low level to allow key combinations like ALT+SHIT+some-key etc, and in some way this prevents the system from capturing these combos.

I don't know if both can work together, but if someone finds the time it might be worth looking into.

**Comment by ajariel** [comment]
Win+Space also works to workaround this.

**Comment by Dudemanguy** [comment]
Should have been fixed by #13104.
