### ISSUE TITLE
input.conf one keybind two commands

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#11893]
I want to use `CTRL+Right` to `add chapter 1` for video files that have chapters,
and for the video files that doesn't have chapters I want `CTRL+Right` to do `playlist-next`.

**Comment by guidocella** [comment]
```lua
mp.add_key_binding('CTRL+Right', function ()
    mp.command(mp.get_property('chapter') and 'add chapter 1' or 'playlist-next')
end)
```

**Comment by avih** [comment]
Two comands can be added using `;` to terminate the first command, as documented here https://mpv.io/manual/master/#input-conf-syntax

However, you want a different thing: choose which command to execute based on whether the video has chapters (or maybe whether it's currently at the last chapter).

This cannot be done at `input.conf` alone, but it can be done via a lua/js script, as mentioned above.

**Comment by zhongfly** [comment]
My scipt is made for this https://github.com/zhongfly/command_cond

```
CTRL+Right add chapter 1 #| chapters > 1
CTRL+Right playlist-next
```
