### ISSUE TITLE
Crashes under hyprland after 7beae9ac86e7b501d24e1ee8bd9b2986578d65c7

### ISSUE THREAD

**Issue by q234rty** [mpv-player/mpv#11907]
### Important Information

OS: Arch Linux
mpv version: 7beae9ac86e7b501d24e1ee8bd9b2986578d65c7
Commit which introduced the issue: 7beae9ac86e7b501d24e1ee8bd9b2986578d65c7
Window Manager and version: hyprland 4cc0e6de90844dd340108f132db014ccf8d44ba7
GPU driver and version: amdgpu, radeonsi with mesa 23.1.3

### Reproduction steps

1. Play any video under hyprland

### Expected behavior

The video plays

### Actual behavior

mpv crashes

### Log file

`WAYLAND_DEBUG=1` is set to hopefully make the log more useful.

[mpv_log.txt](https://github.com/mpv-player/mpv/files/12000777/mpv_log.txt)

**Comment by llyyr** [comment]
Yeah mpv tries to use xdg_toplevel version 5 if the compositor advertises it but doesn't implement https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/122
