### ISSUE TITLE
Add .weba to external_files.c/audio_exts[]

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [mpv-player/mpv#11900]
### Expected behavior of the wanted feature
Autoload external audio tracks with .weba extension.

### Alternative behavior of the wanted feature
Turn external_files.c into a script like autoload.lua.
This will allow to modify it easily and it doesn't look like something with strong performance requirements.

**Comment by hooke007** [comment]
It seems to be a invaild unofficial name like `alac`
Ref the official doc `Audio-only files SHOULD have a mime of "audio/webm"`
https://www.webmproject.org/docs/container/

**Comment by natural-harmonia-gropius** [comment]
> this is a non-standard extension
