### ISSUE TITLE
auto-profiles: Requires boolean return value instead of "truthy" value

### ISSUE THREAD

**Issue by FichteFoll** [mpv-player/mpv#11903]
### Important Information

Provide following Information:
- mpv version: mpv 0.35.0-317-g9880b06a37
- Platform and Version: Arch Linux
- Source of the mpv binary: Arch repos

### Reproduction steps

Create the following config file (adjust the find expression to something you can satisfy with a file):
```
[reset-sub-pos]
profile-cond=get("path", ""):find("abc")
profile-restore=copy-equal
sub-pos=100
```

### Expected behavior

[According to the docs](https://mpv.io/manual/master/#conditional-auto-profiles), a profile condition needs to return a "truthy" value to become activated.
Thus, I expected the profile to be activate for a file containing "abc" in its path 

### Actual behavior

The profile is not active. In a verbose log, I found this:

```
auto_profiles: Re-evaluating auto profile reset-sub-pos
auto_profiles: Profile condition did not return a boolean, but nil.
…
auto_profiles: Re-evaluating auto profile reset-sub-pos
auto_profiles: Profile condition did not return a boolean, but number.
```

After I appended ` ~= nil` to the condition, the profile was applied as expected:

```
auto_profiles: Re-evaluating auto profile reset-sub-pos
auto_profiles: Applying auto profile: reset-sub-pos
```

### Log file

The relevant log excerpt has been included above.

### Sample files

Use any (video) file and adjust the profile condition accordingly.

**Comment by guidocella** [comment]
This requires git master.

**Comment by FichteFoll** [comment]
You're right, it appears the documentation at https://mpv.io/manual/stable/#conditional-auto-profiles matches my observations. Looking forward, I'll switch to using the stable documentation.
