### ISSUE TITLE
mpv smi subtitle html tag support 

### ISSUE THREAD

**Issue by KimWoongBin** [mpv-player/mpv#11916]
[Don't](

> url

) ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

Hi. I want to ask a  quick question about an issue about subtitle.

the images that i provided are the subtitle design difference between mpv and potplayer.

![image](https://github.com/mpv-player/mpv/assets/76960610/6f3ad7ad-3137-47da-b312-ea5d8ec268c3)

this is mpv,

![image](https://github.com/mpv-player/mpv/assets/76960610/d7e9cc69-89be-4f81-a19c-5161b214e46c)

and this is potplayer.

as you can see, the subtitle breaks when I use the subtitle with mpv.

how can I fix this issue?

thanks for your help :)

log:
[output.txt](https://github.com/mpv-player/mpv/files/12025808/output.txt)

**Comment by llyyr** [comment]
```
[   0.056][i][cplayer]  (+) Video --vid=1 (h264 1920x1080 23.976fps)
[   0.056][i][cplayer]  (+) Audio --aid=1 (pcm_bluray 2ch 48000Hz)
[   0.056][i][cplayer]      Audio --aid=2 (pcm_bluray 2ch 48000Hz)
```

According to your logs, there isn't any subtitle track at all. Are you sure the logs are for this file? Also try with --no-config, since you have quite a few --sub-* options set

**Comment by KimWoongBin** [comment]
updated log. Plz check. thanks for your help!

**Comment by sfan5** [comment]
You can see in your log that ffmpeg says it can't handle some of the tags it encounters:
<pre>
[ 313.174][w][ffmpeg] sami: Unrecognized tag ruby
[ 313.174][w][ffmpeg] sami: Unrecognized tag rt
</pre>

Since ffmpeg handles the conversion between text subtitle formats and ASS, this feature has to be implemented there.
