### ISSUE TITLE
black bars in gnome 3.14

### ISSUE THREAD

**Issue by blaenk** [mpv-player/mpv#1191]
I'm not sure exactly what's going on here or what information to provide, but in gnome 3.14 when I view a video (any) in windowed mode, it shows black bars on the sides. These are videos that don't themselves include black bars, and which previously worked perfectly fine. I'm not exactly sure when it worked fine, but I think it was before I upgraded to 3.14. It _seems_ like the video itself is fine; it doesn't seem like it's squished from the sides; it seems the correct AR with black bars added to the sides. Full screen works perfectly fine. Resizing the window still seems to "respect the AR," but always has the black bars on the sides.

Some people in IRC suspected it was probably something about "the aspect ratio hint not working," that "the aspect ratio hint was probably accidentally calculated with the title bar in mind."

I'm not exactly sure what that entails, but for what it's worth, I think the title bar decoration in gnome 3.14 changed a bit. Running mpv from the terminal doesn't yield any weird messages or errors.

**Comment by saivert** [comment]
This is fixed in Gnome 3.16 which is in Arch testing repo right now.

**Comment by wm4** [comment]
Is 3.14 still broken? Anyway, good enough.
