### ISSUE TITLE
Failed video output with gpu-api=vulkan

### ISSUE THREAD

**Issue by ProxyVT** [mpv-player/mpv#11912]
### Important Information

Provide following Information:
- mpv version:

      mpv 0.35.0-511-gab300285 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
        built on Sun Jul 09 02:46:33 2023
      libplacebo version: v6.292.0-1-gb959cab-dirty
      FFmpeg version: N-111381-ge52676e20
      FFmpeg library versions:
          libavutil       58.14.100
          libavcodec      60.22.100
          libavformat     60.10.100
          libswscale      7.3.100
          libavfilter     9.8.102
          libswresample   4.11.100
- Windows Version:
     
      OS: Windows 10 (Home) x86_64
      Kernel: 10.0.19045.3086 (22H2)
      CPU: AMD A10-5800K with Radeon(tm) HD Graphics (4) @ 3.793 GHz                                     
      GPU: NVIDIA GeForce GTX 660 (2.00 GiB)
      Driver version: 474.44
- Source of the mpv binary: [mpv-git (scoop)](https://github.com/lukesampson/scoop-extras/blob/master/bucket/mpv-git.json)
- If known which version of mpv introduced the problem: `20230709` (builds by shinchiro).
### Reproduction steps:
1. `mpv --no-config --vo=gpu-next --gpu-api=vulkan`
2. `mpv --no-config --gpu-api=vulkan`
### Expected behavior:
mpv starts video correctly and without any errors with Vulkan API.
### Actual behavior:

- With first step mpv can't play any video and console shows errors:

      [vo/gpu-next/libplacebo] Missing device feature: dynamicRendering
      [vo/gpu-next/libplacebo] Vulkan device does not support all required features!                                                            
      [vo/gpu-next/libplacebo] Failed creating logical device!
      [vo/gpu-next/libplacebo] Failed initializing vulkan device
      [vo/gpu-next] Failed initializing any suitable GPU context!
      Error opening/initializing the selected video_out (--vo) device.                                                                          
      Video: no video

- If we remove `vo=gpu-next` video starts playing, but video output fallback to direct3d:

      [vo/gpu/libplacebo] Missing device feature: dynamicRendering
      [vo/gpu/libplacebo] Vulkan device does not support all required features!                                                                 
      [vo/gpu/libplacebo] Failed creating logical device!
      [vo/gpu/libplacebo] Failed initializing vulkan device
      [vo/gpu-next/libplacebo] Missing device feature: dynamicRendering
      [vo/gpu-next/libplacebo] Vulkan device does not support all required features!                                                            
      [vo/gpu-next/libplacebo] Failed creating logical device!
      [vo/gpu-next/libplacebo] Failed initializing vulkan device
      AO: [wasapi] 48000Hz stereo 2ch float
      VO: [direct3d] 1920x1080 yuv420p

### Log files:

[vo=gpu_next.txt](https://github.com/mpv-player/mpv/files/12015765/vo.gpu_next.txt)
[default_vo.txt](https://github.com/mpv-player/mpv/files/12015770/default_vo.txt)
### Notes:
1. In my case, similar behavior is seen on EndeavourOS with mpv-full-git from aur and on NixOS with latest mpv build from master. The difference is that instead of fallback to `direct3d` mpv works with `vdpau` vo. 
2. It seems that the problem caused by latest `libplacebo` release [6.292.0](https://code.videolan.org/videolan/libplacebo/-/tags/v6.292.0), because when mpv was build with previous releases like [5.264.1](https://code.videolan.org/videolan/libplacebo/-/tags/v5.264.1) or [5.229.2](https://code.videolan.org/videolan/libplacebo/-/tags/v5.229.2), videos with `gpu-api=vulkan` played mostly fine regardless of --vo.

**Comment by sfan5** [comment]
As far as I can tell VK_KHR_dynamic_rendering is part of Vulkan 1.3, while libplacebo claims it is able to work on 1.2. @haasn might want to clarify

**Comment by ProxyVT** [comment]
> https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_dynamic_rendering
> 
> Don't try Vulkan on museum PCs

I agree, it's a bit of marginal. But Vulkan it's the only way I can watch 4K HDR movies without any frame drops.

**Comment by ProxyVT** [comment]
> As far as I can tell VK_KHR_dynamic_rendering is part of Vulkan 1.3, while libplacebo claims it is able to work on 1.2. @haasn might want to clarify

According to [this](https://vulkan.gpuinfo.org/listreports.php?devicename=NVIDIA+GeForce+GTX+660), GTX 660 and other Kepler's supports Vulkan 1.2.175, so it should work in some way

**Comment by ProxyVT** [comment]
> > > https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_KHR_dynamic_rendering
> > > Don't try Vulkan on museum PCs
> > 
> > 
> > I agree, it's a bit of marginal. But Vulkan it's the only way I can watch 4K HDR movies without any frame drops.
> 
> You might consider tweaking some options to improve performance, such as
> 
> ```
> hdr-compute-peak=no
> video-sync=audio
> scale=bilinear
> d3d11va-zero-copy=yes
> deband=no
> ```

I've already tried options you mentioned and even more, but the most efficient was to use `gpu-api=vulkan` in combination with `vd-queue-enable=yes`. Unfortunately, none of the optimization tricks helped me to achieve good performance at high bitrates when I using `d3d11` (Windows) or `opengl` (Linux).

**Comment by ProxyVT** [comment]
And I'm not using `hwdec` option, because this GPU doesn't support H.265 hardware acceleration.

**Comment by ProxyVT** [comment]
> > > As far as I can tell VK_KHR_dynamic_rendering is part of Vulkan 1.3, while libplacebo claims it is able to work on 1.2. @haasn might want to clarify
> > 
> > 
> > According to [this](https://vulkan.gpuinfo.org/listreports.php?devicename=NVIDIA+GeForce+GTX+660), GTX 660 and other Kepler's supports Vulkan 1.2.175, so it should work in some way.
> 
> `VK_KHR_dynamic_rendering` is an optional extension on Vulkan 1.2 and NVIDIA did not implement it for GTX600 series GPUs
> 
> https://vulkan.gpuinfo.org/displayreport.php?id=22205#extensions

I'm not an expert in this terms, but as far as I know Dynamic Rendering was created as a superior to RenderPass mechanism, so maybe it's possible to fallback to this method if `VK_KHR_dynamic_rendering` not supported? At least for as long as Kepler's GPU's will receive security updates.

**Comment by gordboy** [comment]
I see the OP is using nvidia driver 474.44. I had the same thing on driver 470 in linux, and all the badness went away after switching to driver 535.

The guide here specifically mentions that vulkan only really works with drivers 535+

https://github.com/mpv-player/mpv/issues/11739

Hope that helps

**Comment by ProxyVT** [comment]
> I see the OP is using nvidia driver 474.44. I had the same thing on driver 470 in linux, and all the badness went away after switching to driver 535.
> 
> The guide here specifically mentions that vulkan only really works with drivers 535+
> 
> #11739
> 
> Hope that helps

Unfortunately, 470 driver is the last my GPU supported. I read that post and it looks like a new version of Nvidia driver will be required in future mpv release for correct Vulkan performance. As I understand, the main advantage is the development of Vulkan hardware decoding (`hwdec=vulkan`). But I'm not using any hwdec method.

So, maybe it's possible to create some sort of fallback for Kepler's era GPU's, so they still can using `gpu-api=vulkan` without any new features, but not breaking entire Vulkan API functionality on this GPU's.

**Comment by haasn** [comment]
> > > As far as I can tell VK_KHR_dynamic_rendering is part of Vulkan 1.3, while libplacebo claims it is able to work on 1.2. @haasn might want to clarify
> > 
> > 
> > According to [this](https://vulkan.gpuinfo.org/listreports.php?devicename=NVIDIA+GeForce+GTX+660), GTX 660 and other Kepler's supports Vulkan 1.2.175, so it should work in some way.
> 
> `VK_KHR_dynamic_rendering` is an optional extension on Vulkan 1.2 and NVIDIA did not implement it for GTX600 series GPUs
> 
> https://vulkan.gpuinfo.org/displayreport.php?id=22205#extensions

I will make it optional again.

**Comment by ProxyVT** [comment]
> I think users of these ancient GPUs should replace their devices as soon as possible, libplacebo has made too many compromises in terms of compatibility.

Fair point, but different life circumstances may not allow people for upgrading GPU every 2-3 years. And old graphics card often means an old computer, so it's not just a matter of buying new GPU, but rather a new computer, which means entirely different price category.

Moreover, security updates for Kepler will be released until September 2024, so misery with supporting these graphics cards won't last so long.

**Comment by gordboy** [comment]
Once the 535 driver series is actually stable enough to use, then we can start being precious about our rigs.

I have reverted to 470 series, for reasons of overall stability in all areas. So for now, I am willing to forego the pleasures of vulkan rendering in mpv.

vo=gpu
hwdec=nvdec

works just fine for me on GTX1650plus with hevc, h264 &etc

Of course, when everything is vulkan compositors on wayland2.0, then we will be the vanguard, the acme, the very zenith of playing pirated movies on our linux boxes ...

**Comment by ProxyVT** [comment]
> I experience the same behavior of mvp 0.36.0 (Win32 builds by Shinchiro) as described in this issue but with an AMD Radeon Pro 5600M GPU controlled by AMD Radeon Software: Adrenalin Edition 23.9.1 driver (Vulkan version 1.3.250, Vulkan driver version 2.0.270, [full driver details](https://user-images.githubusercontent.com/17095595/271786403-cb6ffada-1912-4dac-890a-5e9c4a2601eb.png)). Is it trying a different driver version the best I can try or is it reverting to **mpv** build older than build `20230709`?

You could try older build and see if this can solve the problem. If it helps, you need to check what commits were made during this period and what broke the Vulkan support for your system.

**Comment by ProxyVT** [comment]
> To add another data point, I have the same issue with mpv 0.36.0 on a Arch system with **Intel GPU**:
> 
> ```
> libplacebo version: v5.264.1
> FFmpeg version: n6.0
> FFmpeg library versions:
>    libavutil       58.2.100
>    libavcodec      60.3.100
>    libavformat     60.3.100
>    libswscale      7.1.100
>    libavfilter     9.3.100
>    libswresample   4.10.100
> ```
> 
> `inxi -Gxx -c`:
> 
> ```
> Graphics:
>   Device-1: Intel CometLake-U GT2 [UHD Graphics] driver: i915 v: kernel arch: Gen-9.5 ports:
>     active: none off: DP-1 empty: DP-2,HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:9b41
>   Display: server: X.org v: 1.21.1.9 compositor: kwin_x11 driver: X: loaded: intel
>     unloaded: modesetting alternate: fbdev,vesa dri: i965 gpu: i915 tty: 178x42
>   Monitor-1: DP-1 model: Dell U3011 res: 1920x1200 dpi: 76 diag: 756mm (29.8")
>   API: EGL v: 1.5 platforms: device: 0 drv: iris device: 1 drv: swrast surfaceless: drv: iris
>     inactive: gbm,wayland,x11
>   API: OpenGL v: 4.6 compat-v: 4.5 vendor: mesa v: 23.2.1-arch1.2 note: console (EGL sourced)
>     renderer: Mesa Intel UHD Graphics (CML GT2), llvmpipe (LLVM 16.0.6 256 bits)
>   API: Vulkan Message: No Vulkan data available.
> ```
> 
> Can't say at the moment if this was an issue with earlier builds as well. Will update the post when I know.

You can try update libplacebo (the latest version at the moment is 6.338). You need to install the mpv-git version from AUR; there may be an option with the latest version of libplacebo there.

**Comment by rothn** [comment]
Why was this closed? I'm still having this issue on v0.38 and I don't see a resolution here.

**Comment by rubyFeedback** [comment]
Interestingly for me:

    mpv --no-config --vo=gpu-next --gpu-api=vulkan foobar.mp4 

did not work but:

    mpv --no-config --gpu-api=vulkan foobar.mp4

worked. There were some warnings and mpv said it will be slow, but at the least I
could play the video. I am using the open source nouveau right now so this may be
a problem. Before that, like 3 days ago, I had manjaro proprietary nvidia and it worked
without problem.

I have little experience with video-related stuff, so the above is black magic to me. I
don't quite know what to do in these cases.

I think I am not the only one who runs into this as this is quite commonly reported
in github issues. Perhaps in the long run the situation for mpv could be simplified.
For instance, to me it was a surprise that a different commandline flag combination
leads to a video shown, even if it may be laggy. Perhaps mpv could get a tiny 
"helper" layer that could guide people to solve these issues. 

For instance when I just used "mpv foobar.mp4" without any other flags, I could hear
audio but did not see any video, and output was:

    ● Video  --vid=1  (h264 1470x956 25 fps) [default]
    ● Audio  --aid=1  (aac 1ch 32000 Hz 126 kbps) [default]
    [vo/gpu/opengl] Suspected software renderer or indirect context.
    [vo/gpu/drm] VT_GETMODE failed: Inappropriate ioctl for device
    [vo/gpu/drm] Failed to set up VT switcher. Terminal switching will be unavailable.
    [vo/gpu/drm] Could not find any preferred mode. Picking the first mode.
    [vo/gpu/drm] Failed to create DRM atomic context, no DRM Atomic support
    [vo/gpu] Failed initializing any suitable GPU context!
    Error opening/initializing the selected video_out (--vo) device.

Such an output is not too terribly useful to me because I have no idea what to do
with any of this. The recommendation in this github issue to use "--no-config --gpu-api=vulkan"
did work; it would be nice if the mpv output could have that. Not necessarily by default,
but as some means to toggle it globally perhaps, and/or a commandline flag, e. g. 
"--user-friendly-layer" and then a helper-layer would be used that is more helpful at
all times. Anyway that is just a suggestion and perhaps future people may learn from
issues like this.
