### ISSUE TITLE
gpu-next: gamut-mapping-mode is always saturation when target-colorspace-hint=yes

### ISSUE THREAD

**Issue by arm64-v9a** [mpv-player/mpv#11943]
### Important Information

Provide following Information:
- mpv version https://github.com/mpv-player/mpv/commit/93f95f61e92499c5fe2975add2e86d89b0a563b5
- Platform and Version Win11 23493.1000
-[ Source](https://github.com/zhongfly/mpv-winbuild/releases/download/2023-07-15/mpv-x86_64-v3-20230715-git-93f95f6.7z) of the mpv binary 

### Reproduction steps
`mpv --no-config --vo=gpu-next --target-colorspace-hint=yes --gamut-mapping-mode=perceptual`
### Expected behavior
![image](https://github.com/mpv-player/mpv/assets/58792941/7def788c-f022-410a-8e28-f2d62ddcf489)
### Actual behavior
![image](https://github.com/mpv-player/mpv/assets/58792941/3c5d7335-0489-433c-96c4-9cdd95b29829)
### Log file
 target-colorspace-hint=no: [log.txt](https://github.com/mpv-player/mpv/files/12061663/log.txt)
 target-colorspace-hint=yes: [log.txt](https://github.com/mpv-player/mpv/files/12061664/log.txt)
### Sample files
Any HDR videos

**Comment by haasn** [comment]
Your log shows no gamut mapping being performed, except for the overlay (i.e. OSD/subtitles), which is currently always hard-coded to use saturation mapping.

So I think this is working as intended.
