### ISSUE TITLE
vo=gpu-next: Add an option to fix the half-pixel shift caused by prescalers such as NNEDI3

### ISSUE THREAD

**Issue by dokur0chan** [mpv-player/mpv#11948]
### Expected behavior of the wanted feature
As of right now, it's impossible to compensate for the half-pixel picture shift caused by prescaler shaders such as [NNEDI3 and RAVU](https://github.com/bjin/mpv-prescalers/tree/master) while using `vo=gpu-next`. This is caused by the option `no-scaler-resizes-only` being no-op in `gpu-next`, which previously was able to correct this picture shift in `vo=gpu`. Source: https://github.com/bjin/mpv-prescalers/issues/25#issuecomment-341595365

Quick demonstration of this pixel shift (switch between `vo` comparisons using ↑ and ↓, and between scaler comparisons with  ← and →) 
https://slow.pics/c/iDCir8Cf

While using `gpu` for the time being is a valid solution, being able to gain the performance and feature benefits of `gpu-next` while using prescalers like NNEDI3 and RAVU would be highly desirable. Having an option that replicates `no-scaler-resizes-only` behavior, or an option that compensates for this picture shift in other ways would be appreciated.
### Alternative behavior of the wanted feature
If `--no-scaler-resizes-only` (or a similar option) cannot be implemented back into `gpu-next` due to fundamental differences between `gpu` and `gpu-next`, then perhaps NNEDI3 should be a built-in prescaler in libplacebo, with the half-pixel shift compensated for. My justification for this is that unlike other prescalers, NNEDI3 is relatively uncontroversial as a luma doubler. This is probably due to its strong anti-aliasing and its propensity to not overly highlight artifacts that are present in low-resolution videos, hence why it's still used for high-quality resizing purposes in applications like AviSynth.

That being said, implementing a built-in prescaler into libplacebo is probably extremely low in the pecking order of priorities, even if there was interest for it. So understandably, I don't expect this to be implemented.
### Log file

N/A

**Comment by haasn** [comment]
This was, to some extent, an intentional decision for *quality* reasons, mainly. Moving an image by a half-pixel makes it less sharp, which you can see to some extent in the linked comparison. So I figured it's better to introduce a half-pixel shift and avoid having to distort the image further, which may somewhat defeat the purpose of using a pre-sharpener in the first place.

But I can relax this, or at least add an option.

**Comment by haasn** [comment]
Can you try on this image, for demonstration purposes?
![linetest](https://github.com/mpv-player/mpv/assets/1149047/48a38ed1-46d7-419d-a1a3-e0fdd339c3f2)

**Comment by dokur0chan** [comment]
> This was, to some extent, an intentional decision for _quality_ reasons, mainly. 

Interesting, I actually wasn't aware that this was the case. Thank you for clarifying this! Out of curiosity: In the issue tracker I linked, the user claims to have  done a comparison with VapourSynth where they claim to have not noticed the pixel-shift. The user didn't actually post a visual comparison for this, because their (admittedly) low quality .gif  has some dark ringing artifacts, which means its most likely just highlighting the difference between lanczos3 vs. nnedi3 in mpv, as clarified in their "PS". Unfortunately I have no idea how to use applications like AviSynth or VapourSynth, so I can't recreate this myself, but assuming the user is telling the truth, does that mean that VapourSynth incurs a quality penalty because it doesn't shift the pixels by default?

> Can you try on this image, for demonstration purposes?

You are correct. `vo=gpu-next` displays this test image much sharper than `--vo=gpu --no-scaler-resizes-only`. All comparison images were scaled in gamma light, so I don't know if this will introduce unintended visual identities vs. the source image, but this should still highlight the difference in sharpness between correcting vs. not correcting for the picture shift.

Simple image doubling comparison + a 4x zoomed in comparison with nearest-neighbor integer scaling
https://slow.pics/c/XGGEd5Us

One interesting thing I've noticed is that the unshifted version has stronger mosquito noise artifact suppression than the sharper output. So maybe this might be a desirable outcome for some users who are watching low-resolution videos or badly mastered DVDs?

**Comment by haasn** [comment]
In principle, it would actually be possible to extend the NNEDI3 user shader to add an extra pass to compensate for the half-shift in the 1:1 scaling case, if this is desired.

In terms of noticing it, I'd say the most likely scenario would be when you continuously resize the window - as you go from the slightly-downscaling case to the 1:1 case to the slightly-upscaling case, the image would jump by a half pixel only in the 1:1 case.

I'll add a "quality trade-off" option to libplacebo, and then I guess we can hook that up to `--scaler-resizes-only`.

**Comment by dokur0chan** [comment]
Either sounds good to me! I'm not entirely sure how other applications correct for the half-pixel shift, but from my understanding, usually the NNEDI3 scaler itself will have a "center shift" parameter which will apply a traditional scaling kernel such as `spline36` to correct the picture back to its original position. I was under the impression that `--no-scaler-resizes-only` basically did the same thing under `vo=gpu`. I think I remember reading that madVR only corrects for it when using a SuperRes algorithm (but I think this is only done because SuperRes itself requires the picture to be unshifted?).

Admittedly my understanding of this is _very_ limited, which is why my feature request is a little bit on the vague side. I think users will be satisfied regardless of whether the option is provided by the user shader or libplacebo itself.

**Comment by haasn** [comment]
What scaler do we want to use to fix subpixel offsets? Upscaler? Downscaler? Bilinear? Bicubic? Something else?

**Comment by haasn** [comment]
So, I wrote https://code.videolan.org/videolan/libplacebo/-/merge_requests/582 to allow forcing this, but in doing so, I noticed something rather.. unfortunate: in the design of libplacebo, the first NNEDI3 pass will introduce a subpixel offset which the second one then strips again while sampling. I should probably make plane hooks explicitly stripping subpixel offsets and re-apply them afterwards, to avoid giving users plane rects with subpixels in them.

Though that may break `OFFSET ALIGN` or something. Whatever.

**Comment by dokur0chan** [comment]
> What scaler do we want to use to fix subpixel offsets? Upscaler? Downscaler? Bilinear? Bicubic? Something else? Orthogonal? Polar?

The ideal solution would probably be to inherent the user's `--scale`/`upscaler` just to be robust. 

But in terms of what would actually provide the best picture... You can correct me if I'm wrong, but correcting these sub-pixel offsets is probably closer to a distortion than an actual "resize". So in that sense, a polar filter would probably produce the better results. Which polar filter specifically? I honest don't know, it would need some testing and eye-excruciating pixel peeping.

**Comment by haasn** [comment]
> > What scaler do we want to use to fix subpixel offsets? Upscaler? Downscaler? Bilinear? Bicubic? Something else? Orthogonal? Polar?
> 
> The ideal solution would probably be to inherent the user's `--scale`/`upscaler` just to be robust.
> 
> But in terms of what would actually provide the best picture... You can correct me if I'm wrong, but correcting these sub-pixel offsets is probably closer to a distortion than an actual "resize". So in that sense, a polar filter would probably produce the better results. Which polar filter specifically? I honest don't know, it would need some testing and eye-excruciating pixel peeping.

That would also allow doing it in a single pass, which is probably better here.

**Comment by haasn** [comment]
> So, I wrote https://code.videolan.org/videolan/libplacebo/-/merge_requests/582 to allow forcing this, but in doing so, I noticed something rather.. unfortunate: in the design of libplacebo, the first NNEDI3 pass will introduce a subpixel offset which the second one then strips again while sampling. I should probably make plane hooks explicitly stripping subpixel offsets and re-apply them afterwards, to avoid giving users plane rects with subpixels in them.
> 
> Though that may break `OFFSET ALIGN` or something. Whatever.

Turns out I was both smarter and more stupid than I thought. I already thought of this and wrote the logic to correctly bind pass textures, but then I was also stupid and forgot to use the updated variable in the loop, so all passes saw the first rect. Fixed by https://code.videolan.org/videolan/libplacebo/-/commit/f6a6f69f216d5f7042a9bce30ea9c9002d31f94f

**Comment by haasn** [comment]
Mapped in c9d5b482c1
