### ISSUE TITLE
/etc/mpv/scripts seemingly ignored by lua after starting when ~/.config/scripts exists

### ISSUE THREAD

**Issue by nekopsykose** [mpv-player/mpv#11949]
### Important Information

Provide following Information:
- mpv version 0.35.1-cab544889a6ce2dd48a5859b54ccfd807518bd92 
- alpine linux edge
- distro packages

### Reproduction steps

- unpack https://github.com/tomasklaen/uosc into /etc/mpv and make sure you don't have ~/.config/scripts
- `mpv somevideo`
- it works and loads the ui
- `mkdir ~/.config/mpv/scripts` (or wherever the config dir is)
- /etc/mpv/scripts is not in the search path (?) despite loading the initial lua, so you get

```
[uosc] 
[uosc] stack traceback:
[uosc] 	/etc/mpv/scripts/uosc.lua:15: in main chunk
[uosc] 	[C]: at 0x56474ddbfe10
[uosc] 	[C]: at 0x56474ddbf510
[uosc] Lua error: /etc/mpv/scripts/uosc.lua:15: module 'uosc_shared/lib/std' not found:
[uosc] 	no field package.preload['uosc_shared/lib/std']
[uosc] 	no file '/usr/share/luajit-2.1.0-beta3/uosc_shared/lib/std.lua'
[uosc] 	no file '/usr/local/share/lua/5.1/uosc_shared/lib/std.lua'
[uosc] 	no file '/usr/local/share/lua/5.1/uosc_shared/lib/std/init.lua'
[uosc] 	no file '/usr/share/lua/5.1/uosc_shared/lib/std.lua'
[uosc] 	no file '/usr/share/lua/5.1/uosc_shared/lib/std/init.lua'
[uosc] 	no file '/usr/share/lua/common/uosc_shared/lib/std.lua'
[uosc] 	no file '/usr/share/lua/common/uosc_shared/lib/std/init.lua'
[uosc] 	no file '/home/demon/.config/mpv/scripts/uosc_shared/lib/std.lua'
[uosc] 	no file '/usr/local/lib/lua/5.1/uosc_shared/lib/std.so'
[uosc] 	no file '/usr/lib/lua/5.1/uosc_shared/lib/std.so'
[uosc] 	no file '/usr/local/lib/lua/5.1/loadall.so'
```

note that interestingly it does find the uosc plugin at all, just the directory is swapped after for the relative package.preload (which seems to try resolve relatively from the user dir)

### Expected behavior

both the user and system dirs are in the include path (is that possible?) so this scenario of two scripts dirs works. if not, then close wontfix :)

**Comment by sfan5** [comment]
> note that interestingly it does find the uosc plugin at all, just the directory is swapped after for the relative package.preload (which seems to try resolve relatively from the user dir)

This means the directory searching order inside mpv is working correctly, but not the right path(s) are added to Lua's search path.

**Comment by sfan5** [comment]
So, if a script is an entire directory mpv adds the folder of the script to the search path so it can `require` its own stuff.
If the script is a single file (like `uosc.lua`) this isn't done.

As it turns out this is a script issue:
https://github.com/tomasklaen/uosc/blob/c8ad77a1a92d0667e1e66f11e84692cd03796ec8/scripts/uosc.lua#L12-L15

uosc populates the search path manually and the path it uses happens to be the wrong one.
This can probably be fixed manually but the easiest way would be to just revert https://github.com/tomasklaen/uosc/commit/4399904bba27b4082bc1be1b8ae810acfa092df4.
