### ISSUE TITLE
Open and close external program

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#11940]
Hi. Using **input.conf** I can open an external program. For example in Windows using a and b keys:

_a run notepad
b run powershell_

But how do I close these programs using input.conf?

**Comment by jimmy-1000** [comment]
> You can't.

😕

**Comment by Dudemanguy** [comment]
mpv's not magic that has full control over external applications. You could do something hacky like a run a pkill or something I guess if windows has something like that.

**Comment by jimmy-1000** [comment]
> You can't.

I did it  😉
