### ISSUE TITLE
mpv only plays one frame of video on vo=gpu, works with vo=xv or x11

### ISSUE THREAD

**Issue by spencermp** [mpv-player/mpv#11942]
### Important Information
mpv ver: 0.35.1
gentoo linux with latest stable dist-kernel
[mpv-build.txt](https://github.com/mpv-player/mpv/files/12060185/mpv-build.txt) (only showing enabled USE flags)
::gentoo ebulid
bspwm 0.9.10
xf86-video-intel

### Reproduction steps

On any video file, launching with the option --vo set to gpu, gpu-next, or any graphical option besides xv and x11 will result in the video failing to play more than one frame.

Resizing the window (such as going in to fullscreen mode) will update to the frame synced with the audio as if the video was playing the whole time, but that also freezes immediately. 

### Expected behavior

Video plays while syncing with audio and displaying on my screen with --vo=gpu

### Actual behavior

Video freezes immediately after first frame loads unless using --vo=xv or --vo=x11

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/12060179/mpv.log)

**Comment by sfan5** [comment]
Does this work with --hwdec=no?

**Comment by spencermp** [comment]
Whoops, forgot I had this open. 

It turns out it's an error with my graphics stack that I'm wrestling with and not mpv.
