### ISSUE TITLE
Multiple HDMI outputs in parallel

### ISSUE THREAD

**Issue by pimboli** [mpv-player/mpv#11941]
mpv version: 0.35.1 // Ubuntu 22.10

I am trying to playback multiple streams on different HDMI outputs with commands like this:

`root@eent:/home/eent# sudo mpv --vo=drm  --drm-connector=HDMI-A-1 --ao=alsa --audio-device=alsa/hdmi:CARD=PCH,DEV=0 https://transcoder5.domain.xxx/rtl-de/index.m3u8?token=`

But it works only on the first output/time I start the mpv command.
If already one instance is running I receive the following error:

[ffmpeg/demuxer] hls: Can't support the subtitle(uri: tracks-t1/mono.m3u8?token=k18-)
     Video --vid=1 (h264 426x240 25.000fps) (1120 kbps)
     Video --vid=2 (h264 1024x576 25.000fps) (3060 kbps)
 (+) Video --vid=3 (h264 1280x720 25.000fps) (6410 kbps) 
 (+) Audio --aid=1 --alang=ger (*) (aac 2ch 48000Hz)
     Audio --aid=2 --alang=ger (aac 2ch 48000Hz)
     Audio --aid=3 (aac 2ch 48000Hz) (1120 kbps)
     Audio --aid=4 (aac 2ch 48000Hz) (3060 kbps)
     Audio --aid=5 (aac 2ch 48000Hz) (6410 kbps)
     Audio --aid=6 (aac 2ch 48000Hz) (210 kbps)
[vo/drm] VT_GETMODE failed: Inappropriate ioctl for device
[vo/drm] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/drm] Cannot set CRTC: Permission denied
Error opening/initializing the selected video_out (--vo) device.
Video: no video

I am using intel onboard gfx.

How can I use parallel outputs on different HDMI ports.

Thanks

**Comment by LaserEyess** [comment]
First, do not run mpv as root, *especially* not while playing a fucking web stream. You are asking, no, **begging** to get ransomwared. 

Second, you ignore the issue template. Please post a log.

**Comment by pimboli** [comment]
Thank you for your feedback. I tested as root because a normal user has no access to DRM output device.
I haven't more logs, the output is exactly what I posted.

It seems that mpv can't open the --vo device if already another instance is running.
Which would make sense. But I thought that each HDMI output could be used individually.

**Comment by LaserEyess** [comment]
That's not true, you're on Ubuntu which means you are using logind, it will give you access to DRM without root. 

Also, you were told how to make logs, but you ignored it:
```
Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.
```
Note the last line.

**Comment by pimboli** [comment]
Ah thanks, misunderstood it.

I exported the logs and uploaded it: 
https://0x0.st/HjLC.txt

Thanks for your thoughts about the DRM master user... I am no expert here, but I will google a bit in this direction.

**Comment by Dudemanguy** [comment]
I don't believe this is a bug. As mentioned, there can only be one master at a time in DRM so trying subsequent commands simply won't work.
