### ISSUE TITLE
SHIFT+BS not working for revert-seek on Wayland

### ISSUE THREAD

**Issue by jerekulmala** [mpv-player/mpv#11945]
### Important Information

Provide following Information:
- mpv ```0.35.1-dirty```
- Linux Distribution and Version: ```archlinux / latest```
- Source of the mpv binary: ```extra/mpv```
- If known which version of mpv introduced the problem
- Window Manager and version: ```swaywm 1.8.1```
- GPU driver and version: ```Intel HD Graphics / i915```
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. Launch mpv on a Wayland compositor.
2. Play a video file.
3. Seek to a different position in the video using any other keybinding.
4. Press SHIFT+BACKSPACE to revert to the previous seek position.

### Expected behavior
When pressing SHIFT+BACKSPACE, the video playback should revert to the previous seek position.

### Actual behavior
When pressing SHIFT+BACKSPACE, it sets speed to 1.00. The video playback does not revert to the previous seek position.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

https://0x0.st/Hj42.txt

The issue will be closed for ignoring the issue template.

#8746 seems related.

**Comment by Dudemanguy** [comment]
Similar to #10286. An input test reveals that the shift key isn't being picked up. I'll check later but I'm going to assume that xkb isn't giving us the modifier key press like in that other issue. I have no idea why that happens.
