### ISSUE TITLE
gpu-next: Black screen after seeking with interpolation enabled and osd-bar=no

### ISSUE THREAD

**Issue by MuPendulum** [mpv-player/mpv#11958]
- mpv 8a6cabce35
- libplacebo 384f8d73e9
- https://github.com/haasn/libplacebo/commit/e91f76515cf0c10b40880eb8b9bc4e5287ec5d01 is the first bad commit
- XFCE 4.18
- RX 6650 XT, mesa 23.1.3

### Reproduction steps

```
--no-config
--vo=gpu-next
--gpu-api=vulkan
--video-sync=display-resample
--interpolation=yes
--osd-bar=no
```

_Quickly_ open a file, pause, and seek forward without using the mouse.
You should be able to reproduce the issue within ten tries.

 - Moving the mouse to display the OSC fixes the black screen
 - Screen may flicker black instead of staying black
 - Screen will flicker black instead if osd-bar is enabled

### Expected behavior

Screen does not flicker or black screen when pausing and seeking with osd-bar=no and interpolation enabled.

### Actual behavior

Screen flickers or black screens when pausing and seeking with osd-bar=no and interpolation enabled.

### Log file

[mpv.log.zip](https://github.com/mpv-player/mpv/files/12073908/mpv.log.zip)

**Comment by llyyr** [comment]
```
[   0.595][d][cplayer] Run command: cycle, flags=73, args=[name="pause", value="1.000000"]
[   0.595][v][cplayer] Set property: pause -> 1
[   0.612][v][vo/gpu-next/x11] Enabling screensaver.
[   0.640][d][cplayer] Run command: seek, flags=73, args=[target="5.000000", flags="relative", legacy="unused"]
[   0.640][v][lavf] queuing seek to 5.334000
[   0.640][v][lavf] execute seek (to 5.334000 flags 4)
[   0.640][v][lavf] seek done
[   0.640][v][file] stream level seek from 1301963 to 4054620
[   0.641][d][ffmpeg/video] h264: Reinit context to 960x544, pix_fmt: yuv420p10le
[   0.657][v][vd] Decoder format: 960x540 [0:1] yuv420p10 auto/auto/auto/auto/auto CL=mpeg2/4/h264
[   0.657][v][vd] Using container aspect ratio.
[   0.657][d][vo/gpu-next/libplacebo] First frame received with non-zero PTS 5.923000
[   0.658][v][cplayer] first video frame after restart shown
[   0.658][d][cplayer] starting video playback
[   0.658][v][cplayer] playback restart complete @ 5.923000, audio=eof, video=playing (paused)
[   2.848][d][cplayer] Run command: quit, flags=73, args=[code="0"]
```
Can't reproduce this. Are you sure it's not just a broken file?

**Comment by MuPendulum** [comment]
> Can't reproduce this. Are you sure it's not just a broken file?
Yes. I tested three different files and could only reproduce with gpu-next, interpolation, osd-bar=no and seeking while paused.

**Comment by llyyr** [comment]
Nope, still can't reproduce even with that sample. If you're able to reproduce it consistently and it worked with a previous version then can you try bisecting which commit broke it?

**Comment by MuPendulum** [comment]
haasn/libplacebo@e91f76515cf0c10b40880eb8b9bc4e5287ec5d01 is the first bad commit

**Comment by llyyr** [comment]
I don't know why `osd-bar=no` would affect anything in this case if that's indeed the bad commit

cc @haasn

**Comment by Dudemanguy** [comment]
It happens with osd-bar=yes too actually. It's just that mpv draws the bar which then causes the full frame to appear but it does flicker black.

**Comment by llyyr** [comment]
Oh yeah I was able to reproduce it with with the Sony Swordsmith HDR sample, it seems to be easier to reproduce with certain type of videos. And can confirm that reverting that commit fixes it as well

**Comment by Artoriuz** [comment]
Can confirm it happens on windows too.
