### ISSUE TITLE
Wayland Tiling Compositor Maximize Requests

### ISSUE THREAD

**Issue by MightyPlaza** [mpv-player/mpv#11954]
mpv version: used v0.35.1 from arch repository (same on latest build from git)
linux distro: tested arch linux fully up to date 
GPU: AMD RX570 (log file is from a fresh QEMU Arch Virtual machine)
Wayland Compositor: Hyprland

last commit to introduce relevant code https://github.com/mpv-player/mpv/commit/db0f9fab67af4776ec82dd491413fe642fb2670a

Issue happens on Wayland, more specifically Hyprland (tiling compositor). 

Using sway or river (tiling compositors), mpv seem to try to resize itself as well (verified with some printf's for debugging in the relevant code bellow) , but nothing happens since those compositors don't support maximizing requests (afaik)

When using weston (non tiling compositor) mpv does not run the relevant code, unlike in the compositors above 

Been trying to fix this on Hyprland's side for a while now, and the behaviour doesn't seem to be caused there, but I could be wrong.

### Relevant code:

(code from video/out/wayland_common.c line 913)
```
case XDG_TOPLEVEL_STATE_TILED_TOP:
case XDG_TOPLEVEL_STATE_TILED_LEFT:
case XDG_TOPLEVEL_STATE_TILED_RIGHT:
case XDG_TOPLEVEL_STATE_TILED_BOTTOM:
case XDG_TOPLEVEL_STATE_MAXIMIZED:
       is_maximized = true;
       break;
```

(code from video/out/wayland_common.c line 935)
```
if (vo_opts->window_maximized != is_maximized) {
         wl->state_change = true;
         vo_opts->window_maximized = is_maximized;
         m_config_cache_write_opt(wl->vo_opts_cache, &vo_opts->window_maximized);
     }
```

### Reproduction steps

To reproduce I recommend Hyprland:
(using other tiling wayland compositor with maximizing support should have the same effect)
(using a tiling wayland compositor without maximizing support seems to produces the same behaviour on mpv's side despite)

Queue up at least 2 videos (different aspect ratio/resolutions seem to be needed) on mpv with ```mpv path/to/video1 path/to/video2```

Wait for the 1st video to end or skip click the next button

### Expected behavior

mpv does not change maximized state

### Actual behavior

mpv get's maximized/de-maximized depending on previous state

### Log file

https://0x0.st/HjId.txt
(QEMU running Hyprland on Arch Linux)

### Sample files

Only requirement seems to be different aspect ratios (Can provide example files if needed)

**Comment by Dudemanguy** [comment]
Oh I see it. We treat tiled and maxmized windows as the same and it seems hyprland allows to to maximize tiled windows (sway doesn't) thus this happens.

**Comment by MightyPlaza** [comment]
works great, thanks for the quick fix
