### ISSUE TITLE
Switching by subtitle is not accurate

### ISSUE THREAD

**Issue by DSxiaolong** [mpv-player/mpv#11963]
Use the latest libmpv. Calling the sub-seek command to switch the subtitle position is inaccurate. The position of the subtitle cannot be accurately positioned.

A suggestion: When switching subtitles, you can switch to the middle of the subtitle time instead of the beginning, which can solve the problem that the subtitles are not displayed due to inaccurate jumps.

sub-seek <skip> <flags>
Seek to the next (skip set to 1) or the previous (skip set to -1) subtitle. This is similar to sub-step, except that it seeks video and audio instead of adjusting the subtitle delay.

【1】
m_mpv->command(QVariantList() << "sub-seek"<<"-1");

【2】
  m_mpv->command(QVariantList() << "sub-seek"<<"1");

**Comment by Traneptora** [comment]
`hr-seek=yes`
