### ISSUE TITLE
how to playback with certain frames disabled ?

### ISSUE THREAD

**Issue by asklow** [mpv-player/mpv#11967]
Is there anyway to disable i-frames, or b-frames, or both, while playback ? If so, how ?

**Comment by llyyr** [comment]
See https://ffmpeg.org/ffmpeg-filters.html#select_002c-aselect

**Comment by Traneptora** [comment]
You might need additional quotes: `'--vf=lavfi="select=eq(pict_type\,I)"'`

**Comment by Traneptora** [comment]
See https://ffmpeg.org/ffmpeg-filters.html#select_002c-aselect
