### ISSUE TITLE
`screenshow-sw` failed

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#11968]
### Important Information

Provide following Information:
- mpv version
[15252e1](https://github.com/mpv-player/mpv/commit/15252e13d5bb367a8f86ffbc5474488b841dc96c)
- Windows Version
22H2
- Source of the mpv binary
toolchain of shinchiro's mpv build
- If known which version of mpv introduced the problem
N/A
- Possible screenshot or video of visual glitches

### Reproduction steps

0. set `--screenshow-sw=yes`
1. load any video
2. run command `screenshot window`

### Expected behavior

No failure

### Actual behavior

screenshot failed

### Log file

[test.log](https://github.com/mpv-player/mpv/files/12096425/test.log)

### Sample files

Any

**Comment by Traneptora** [comment]
Try again with `--no-config` and see if you can reproduce the issue.

**Comment by hooke007** [comment]
Of course.
