### ISSUE TITLE
MPV doesn't respect pulseaudio default sink

### ISSUE THREAD

**Issue by jebaum** [mpv-player/mpv#1196]
mpv doesn't seem to play audio out of whatever is set as the default pulseaudio sink, and instead seems to play out of whichever sink it most recently used until it is explicitly switched.

say I have two sets of speakers, 'A' and 'B', and mpv is playing out of A. if I set the default sink in pulseaudio to B, close mpv, and restart it, it continues to play out of A. if I use pulseaudio to manually switch the mpv source to sink B, it will play out of B. then when I close and restart mpv, it will play out of B again. then if I set the default to A, close and restart, mpv will still be playing out of B.

mplayer and mplayer2 (from the arch 'extra' repo and the aur respectively) do not exhibit this behavior; they play out of whatever the default sink is when they're started.

apologies for the noise if this is somehow not an mpv bug, I'm not very familiar with alsa/pulse

**Comment by tompre** [comment]
This is not a bug in PA. You can disable this behavior in setting restore_device=false.
`load-module module-stream-restore restore_device=false`
in /etc/pulse/default.pa

**Comment by JamesTheAwesomeDude** [comment]
Expanding on @tompre's solution, you can also just comment out the `load-module module-stream-restore` line; this will prevent Pulse from saving stream-specific softvolume and mute overrides.

**Comment by kokoko3k** [comment]
...In my ~/.config/pulse/default.pa, i load module-switch-on-connect, and I just connected an usb headset to my system.
Firefox, kde sounds, mplayer, civilization VI are automatically redirected to it.
mpv, if used with the pulse module, continue to output to loudspeakers, while if used with ao alsa (which, in turn uses pulse via /etc/asound.conf) will be redirected to headsets.
So there is definitely something weird going on.

**Comment by amitbha** [comment]
Same problem ---- mpv 0.33.1.
Change /etc/pulse/default.pa not help.
The app I used, firefox, mocp, etc., will stream audio to default sink except mpv.
If it's bug of pa api, maybe deserve a discuss in irc?
[User Community – PulseAudio](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Community/)

**Comment by Rohlik** [comment]
Have exactly the same problem on my Ubuntu 22.04 desktop where I have pulseaudio server as a default audio server but MPV still use ALSA 😞.

**Comment by hinell** [comment]
@JamesTheAwesomeDude One actually should use `~/.config/pulse/default.pa` instead. The file should actually import the `.include /etc/pulse/default.pa` to be usable.
