### ISSUE TITLE
Auto Select (webvtt) subtitle from YouTube

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#11972]
on `mpv.conf` I added `slang=en`
but on this (example) video from YouTube: https://www.youtube.com/watch?v=HAzZH6wccew
it doesn't select `slang=en` (which is in this case `sid=5`).

How do I make mpv select the English subtitles?

**Comment by llyyr** [comment]
The defaults were changed so you need to put `subs-with-matching-audio=yes` in your config to pick the same subtitle language as the audio track.

**Comment by llyyr** [comment]
That *is* what the option does, it dictates whether mpv is allowed to pick subs with matching audio language or not. Just because it's set to yes doesn't mean it will always pick it, and if it's set to no then it will _never_ pick it.

**Comment by llyyr** [comment]
>  (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
>  (+) Subs  --sid=5 --slang=en 'English' (webvtt) (external)

There's no way to make mpv pick English subs for English audio besides setting that option. Using that option doesn't mean that mpv will _always_ pick matching subtitle language, it will still respect your `--slang` setting. However, not setting it *does* mean that mpv will never pick matching language even if you explicitly specify it in your slang.
