### ISSUE TITLE
Mpv-Android: MPV does not recognise the phone's notch area anymore and just shows a black bar there instead of utilising the full screen

### ISSUE THREAD

**Issue by vinraghav** [mpv-player/mpv#11977]
Mpv Android 2023-06-04 version installed from Google Play Store. 

Mpv Android like most other popular Android media players like VLC and MX player used to play videos in full screen covering the phone notch (punch hole camera) area but now it just shows a lazy black bar there as it it's unable to recognise that part of the screen. See the Red highlighted area on the left of the screen in the image which is the notch area replaced by a black bar.
![Screenshot_20230721-010419__01](https://github.com/mpv-player/mpv/assets/95243737/4c7c9f35-d9eb-4b30-be59-71bb8af89a5b)

Tried clearing cache, removing the config texts and playing different videos. The issue persists. It's not a problem with other players like VLC and MX on my phone. As far as I know, it did not have this issue in the past. It's something happened recently.

**Comment by N-R-K** [comment]
Wrong repo. mpv-android repo is over here: https://github.com/mpv-android/mpv-android

**Comment by vinraghav** [comment]
> Wrong repo. mpv-android repo is over here: https://github.com/mpv-android/mpv-android

Not sure what you mean by that and how it's related to my post.

**Comment by llyyr** [comment]
It means that you should post your issue over on that project. However don't because it has already been reported and fixed https://github.com/mpv-android/mpv-android/commit/69a5b1ec0310fd4a01d52a0f9d2f1f7718b219d8

Build it yourself or wait for a new update

**Comment by vinraghav** [comment]
> It means that you should post your issue over on that project. However don't because it has already been reported and fixed [mpv-android/mpv-android@69a5b1e](https://github.com/mpv-android/mpv-android/commit/69a5b1ec0310fd4a01d52a0f9d2f1f7718b219d8)
> 
> Build it yourself or wait for a new update

Idk when the next update is going to because the app is updated very slow. It has been one and half month since this issue. This issue was fixed using an option in older versions. 
![Screenshot_20230721-064908](https://github.com/mpv-player/mpv/assets/95243737/d722b901-577b-4c92-9e02-3d995d8aa732)

So you see, it's not a bug, it's a removed feature that used to exist previously.

**Comment by vinraghav** [comment]
> The action of mpv-android offers a 32-bit build, if you don't mind 32-bit, you can use it.

Not sure what exactly you mean by that. Besides what do you suggest?
