### ISSUE TITLE
MPV white screen, automatically exits after a few seconds

### ISSUE THREAD

**Issue by cancundeyingzi** [mpv-player/mpv#11981]
### Important Information

Provide following Information:
- mpv version    mpv 0.35.0-486-g0bfafd24 and mpv 0.35.1
- Windows Version    	22H2     22621.1992
- Source of the mpv binary          https://sourceforge.net/
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Hwdec=qsv copy and RTX vsr seem to be incompatible,
After opening RTX vsr, starting mvp will automatically exit
Test steps:
1. Turn on the computer
2. Turn on MPV, normal, turn off MPV
3 Open RTX vsr4
4 browser video playback, detected graphics card power consumption of 200W, RTX vsr correctly turned on, video playback turned off
5. Open MPV, the window is white, and after a few seconds, MPV will automatically exit
### Expected behavior
Play Video
### Actual behavior
MPV automatic exit
### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/12123748/mpv.log)
[mpv-.log](https://github.com/mpv-player/mpv/files/12124788/mpv-.log)

[mpv.conf.txt](https://github.com/mpv-player/mpv/files/12123753/mpv.conf.txt)

**Comment by Traneptora** [comment]
QSV is an intel hwdec, and you're using an NVidia card.
