### ISSUE TITLE
mpv subtitle <ruby> tag support

### ISSUE THREAD

**Issue by KimWoongBin** [mpv-player/mpv#11986]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/12135822/output.txt)

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

expected behavior(potplayer)
![image](https://github.com/mpv-player/mpv/assets/76960610/b2787fdb-daa1-4ac2-b607-562b97f1f116)

exact behavior(mpv)
![mpv-shot0001](https://github.com/mpv-player/mpv/assets/76960610/48f543b1-8bb1-4614-aa52-73c2b77062b1)

Hi, I want to ask how mpv let render subtitle like the image(expected behavior) that I uploaded.

From the log file, I was able to know that the subtitle tag ruby and rt does not support in ffmpeg.

How can i let mpv to render subtitle like the expected behavior?

thx in advance

**Comment by Traneptora** [comment]
As you deduced, this has to be added in FFmpeg.
