### ISSUE TITLE
Linux users with old nvidia-340xx or nvidia-390xx GPUs still use --gl-x11 backend

### ISSUE THREAD

**Issue by Anakievs** [mpv-player/mpv#11987]
### Important Information
Basically I complain against the complete removal of --gl-x11 as mentioned [here](https://github.com/mpv-player/mpv/commit/7831e52238790bf1742b194e0469cf3db5f59bdd). Because this is the way to get hardware acceleration on old nvidia GPUs.

Provide following Information:
- mpv version: future versions (currently 1:0.35.1-8)
- Linux Distribution and Version: Arch Linux, Kernel 6.4.4.arch1-1
- Source of the mpv binary: compiled miself
- Window Manager and version: bspwm
- GPU driver and version: nvidia-340xx-dkms 340.108-33

Thank you!

**Comment by Anakievs** [comment]
You've hurt my feelings. Maybe on PC it's possible to upgrade but in my case it's a laptop and I can't do anything. Probably most of the users of those GPUs are with laptops. The people still make patches for the driver and it compiles with the latest kernel version (6.4.4).

**Comment by llyyr** [comment]
The commit was 3 years ago and it hasn't been removed yet, it will eventually have to go but I don't believe there are any plans to remove it completely. You can just continue building with it explicitly enabled.

**Comment by ua0lnj** [comment]
You need manual add --enable-gl-x11 when configure.
Looks like the developers didn't do it in your case.

**Comment by Anakievs** [comment]
> The commit was 3 years ago and it hasn't been removed yet, it will eventually have to go but I don't believe there are any plans to remove it completely just yet. You can just continue building with it explicitly enabled.

Thank you! I appreciate that.


> You need to manually add --enable-gl-x11 when configuring.

Yes, I know it's not a problem.

**Comment by philipl** [comment]
There isn't an actionable issue here. The functionality is still available as part of the build and hasn't been removed.
