### ISSUE TITLE
How do I delete a file within MPV Linux?

### ISSUE THREAD

**Issue by coolmagnet** [mpv-player/mpv#11985]
After watching a video (either a single file or in a playlist) I would like to create a hotkey to move the file to the trash bin.  I found this [link](https://www.reddit.com/r/mpv/comments/emv85o/comment/j6cpecp/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) that states creating an entry in input.conf:

Del run "trash" "${path}"; playlist_next 

But it does not work, neither does:

Del run "gio trash" "${path}"; playlist_next
Ctrl+D run "gio trash" "${path}"; playlist_next
Del run "gio trash" "${filename}"; playlist_next  

Just looking for something to move the file to the trash bin.  

Thank you

**Comment by Deathcow** [comment]
There's delete_file.lua in [mpv-scripts](https://github.com/zenyd/mpv-scripts) which can also move files to a folder:

https://github.com/zenyd/mpv-scripts/blob/master/delete_file.lua

Should be trivial to set a different move path.

**Comment by Traneptora** [comment]
When you say it "doesn't work" what do you mean? What happens when you try it?

**Comment by Traneptora** [comment]
Also what happens when you use something like:

```
Del run /usr/bin/env trash-put -- "${path}"; playlist-next
```

**Comment by coolmagnet** [comment]
Trying each of the following (not at the same time) in input.conf:

Del run "trash" "${path}"; playlist_next
Del run "gio trash" "${path}"; playlist_next
Del run /usr/bin/env trash-put -- "${path}"; playlist-next

Does not move any files to the trash bin.  It's worth noting that I am running openSUSE XFCE 15.5 and the 'trash' and 'trash-put' command does not exist on my system, however 'gio trash' does work on the command line.

Also, I looked into the:

https://github.com/zenyd/mpv-scripts/blob/master/delete_file.lua

and it either deletes the file or moves the file to another folder.   I don't know how to get it to move to the trash bin.

'gio trash' does exactly what I'm looking for but can't get it to work within MPV.

**Comment by guidocella** [comment]
`Del run gio trash ${path}; playlist-remove current`

**Comment by coolmagnet** [comment]
> `Del run gio trash ${path}; playlist-remove current`

Yes this work perfectly, it can delete a single file or files in a playlist.

Thank you.

**Comment by voidastro4** [comment]
In case someone needs it here is what I use.

`del playlist-next ; run "/bin/sh" "-c" "mkdir -p ./.trash" ; run "/bin/sh" "-c" "mv -- '${path}' ./.trash" ; show-text "moved ${path} to trash"`

**Comment by user-1-2-3-4-5** [comment]
I modified the command above to outright delete files, but `rm` gives the error:

    rm: cannot remove '/home/user/sample.flac': Read-only file system

in my `input.conf`:

    del playlist-remove current ; run "/bin/sh" "-c" "rm -- '${path}'" ; show-text "deleted the ${path}"

I'm using the (unofficial) [mpv Flatpak package](https://github.com/flathub/io.mpv.Mpv) and can't easily install from elsewhere, or build mpv.

The `gio trash` command appears to run into permission issues as well.
