### ISSUE TITLE
--ao=pipewire not working with `pipewire 0.3.75`

### ISSUE THREAD

**Issue by JosefLitos** [mpv-player/mpv#11995]
### Important Information

Provide following Information:
- mpv version: `0.35.1-dirty`
- Linux Distribution and Version: `Archlinux`
- Source of the mpv binary: `archlinux/extra`
- If known which version of mpv introduced the problem: `no`
- Window Manager and version: `sway 1.8.1`
- GPU driver and version: idk, not relevant
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

use latest pipewire release (`0.3.75`)
open something with `mpv --ao=pipewire`

### Expected behavior

play audio

### Actual behavior

no audio (unless specified backup) - pipewire doesn't work with mpv (but works through `pulse` wrapper)

### Log file

```sh
 mpv --ao=pipewire audio.opus
```
```
 (+) Audio --aid=1 (opus 2ch 48000Hz)
[ao] Failed to initialize audio driver 'pipewire'
Could not open/initialize audio device -> no sound.
Audio: no audio

Exiting... (Errors when loading file)
```
### Sample files

any file with audio

**Comment by t-8ch** [comment]
Also reported at https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3374

**Comment by t-8ch** [comment]
This should be fixed by #11996, could you validate?

**Comment by JosefLitos** [comment]
when I try to compile it as described in readme, `meson setup build` gives me:
```
ERROR: Neither source directory 'build' nor build directory None contain a build file meson.build.```

**Comment by q234rty** [comment]
I can confirm that #11996 fixes this for me under pipewire 0.3.75 w/ `ao=pipewire`

**Comment by t-8ch** [comment]
@JosefLitos 

> when I try to compile it as described in readme, meson setup build gives me:

Is your working directory the mpv source directory?

**Comment by JosefLitos** [comment]
yes

**Comment by t-8ch** [comment]
Can you give me a full transcript of your shell?

**Comment by JosefLitos** [comment]
I am not sure what do you mean by that. I am using `fish`.
![image](https://github.com/mpv-player/mpv/assets/54900518/7577e4e0-021c-4bd9-b5fe-a92bac816972)

**Comment by t-8ch** [comment]
You are still on the master branch of my repository.
Which is very old and does not contain the fix nor meson config.

For your convenience I pushed the new bugfix to my master branch.
Please delete your clone and redo the same steps.

**Comment by JosefLitos** [comment]
oh, whoops, I was supposed to `checkout`.

**Comment by JosefLitos** [comment]
yes, works just fine with your patch.

**Comment by hmpfkafka** [comment]
works, thanks for the fix!!
