### ISSUE TITLE
Non-English keybinds that were set in the input.conf no longer work

### ISSUE THREAD

**Issue by gssfaw** [mpv-player/mpv#12009]
### Important Information

Provide following Information:
- mpv version
mpv 0.36.0
- Linux Distribution and Version
Arch Linux  6.4.4-arch1-1
- Source of the mpv binary
Official repository
- If known which version of mpv introduced the problem
In the recent one
- Window Manager and version
sway version 1.8.1
- GPU driver and version
mesa  23.1.4-2

### Reproduction steps
```mpv --no-config --input-conf=input.conf --log-file=output.txt video0.mp4```
Where ```input.conf``` has one line: 
```з cycle pause``` 
"з" - is the Cyrillic letter
### Expected behavior
"з" toggles pause, as it is done by the Latin "p" key.
### Actual behavior
It no longer works that way. 
![20230724_13h39m53s_grim](https://github.com/mpv-player/mpv/assets/95208998/b91ef8d5-2a63-4666-8fc6-20ecda125003)
Here, the screenshot displays that keybind "з" is recognized, but the player does not react to it in any way.

Downgrading only the mpv package to 0.35.1 helps, so it probably wasn't caused by another package update.
### Log file
https://0x0.st/He4S.txt

I tried pressing "з" here a few times, but in the logs I can only see instances of pausing and resuming playback at 3.350 and 6.738. In that interval, I was pressing button "з" key many times, but it was not logged.

### Sample files
happens with every video file

**Comment by christoph-heinrich** [comment]
When you run `--input-test`, does `з` get recognized?

**Comment by gssfaw** [comment]
It does not react to the key presses for some reason. 
I've recorded a video demonstrating it. On the right top corner you can see my current keyboard layout. 
https://github.com/mpv-player/mpv/assets/95208998/a9c13793-8fe3-4ec7-b0cb-d682b21eb60e

**Comment by llyyr** [comment]
If this used to work in the past are you able to bisect? run `git bisect start [bad commit] [good commit]` then follow the instructions

**Comment by christoph-heinrich** [comment]
I bisected it to 1f8013ff3fddd788a517656e09f5ce5d7efd928d, no idea how that actually broke non-english keyboards though.

**Comment by gssfaw** [comment]
This pr fixes it, thank you very much :heart:
