### ISSUE TITLE
hwdec=vulkan gives Unsupported hwdec: vulkan

### ISSUE THREAD

**Issue by adolfotregosa** [mpv-player/mpv#12011]
Hi. Just wanted to try out vulkan hw decoding but... What am I missing ?

![image](https://github.com/mpv-player/mpv/assets/7437931/0ed1d7d4-2151-4122-b220-698acadcbd80)

**Comment by natural-harmonia-gropius** [comment]
--gpu-api=vulkan

**Comment by hooke007** [comment]
> I got this without --gpu-api=vulkan.

Because you were using windows.
For linux, opengl(default) support vulkan hwdec

**Comment by hooke007** [comment]
It seems doc need to be fixed too.
1. Explicitly use `gpu-api=vulkan` is necessary
2. `gpu-next` is not required.
