### ISSUE TITLE
Is it possible to add an image as background instead of black screen?

### ISSUE THREAD

**Issue by rezpower** [mpv-player/mpv#12016]
I was wondering if it's possible to add a wallpaper to load instead of the black screen when you open MPV? This is useful on startup, and also when playing music with no image.
If already possible could you please tell me how to achieve this :)

**Comment by sta-c0000** [comment]
This works (first image is when not playing music, second is when playing drag-dropped music):
(requires full path to image)
```
mpv image.jpg --external-file=image.jpg --force-window --image-display-duration=inf --vid=1
```
If while playing music, then simply this:
```
mpv --external-file=image.jpg --vid=1 music.mp3
```

Can display almost anything / more interesting things using ffmpeg-filters, e.g. frequency spectrum with notes:
```
mpv --lavfi-complex="[aid1]asplit[ao][a]; [a]showcqt=s=1280x720[vo]" music.mp3
```

**Comment by Dudemanguy** [comment]
Question was answered.

**Comment by rezpower** [comment]
Thanks a lot :)
