### ISSUE TITLE
Lua 5.3+ support

### ISSUE THREAD

**Issue by xvitaly** [mpv-player/mpv#12017]
Why doesn't mpv support lua 5.3+?

https://github.com/mpv-player/mpv/blob/ff3739b36e5b169ea948afbb30f73f34383248b3/meson.build#L666-L673

Currently packaged version in most GNU/Linux distributions is 5.3+ or even 5.4.

**Comment by sfan5** [comment]
https://github.com/mpv-player/mpv/wiki/FAQ#why-does-mpv-not-support-lua-53-or-newer
