### ISSUE TITLE
Flathub including MPV library for Flutter app - libmpv.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by tomekit** [mpv-player/mpv#12027]
We've got a Flutter app which depends on `libmpv`. On Ubuntu system it starts fine as long as deps: `apt-get install libmpv-dev mpv` are satisfied.

```
ldd kapsa | grep mpv
	libmpv.so.1 => /lib/x86_64-linux-gnu/libmpv.so.1 (0x00007f72d5a00000)
```

I've tried to bundle the app using Flathub and included `libmpv` as a module: https://github.com/s3drive/flathub/blob/s3drive/io.kapsa.drive.json#L25

App won't start due to: `libmpv.so.1: cannot open shared object file`.

When I go inside the Flatpak bundle: `flatpak run --command=bash --devel io.kapsa.drive` I can see that this build in location `/app/lib` has `libmpv.so` and `libmpv.so.2`, but actually doesn't contain the `libmpv.so.1`.

```
ldd /app/S3Drive/kapsa | grep libmpv
        libmpv.so.1 => not found
```

Do you have an idea why this build: https://github.com/s3drive/flathub/blob/s3drive/io.kapsa.drive.json#L25 ends up with `libmpv.so.2` instead? Can I force Flathub to link to the `libmpv.so.2`?

Wasn't sure if Flathub isn't more suitable place to ask this question, but given that MPV is relatively complex library I've thought I will ask here first.

Bundle commands:
```
git clone --branch=s3drive git@github.com:s3drive/flathub.git
flatpak-builder --force-clean build-dir io.kapsa.drive.json --repo=repo
flatpak build-bundle repo io.kapsa.drive.flatpak io.kapsa.drive
flatpak-builder --user --install --force-clean build-dir io.kapsa.drive.json
flatpak run io.kapsa.drive
```

Related: https://github.com/mpv-player/mpv/issues/6933

**Comment by Traneptora** [comment]
The API version was bumped to 2 in mpv 0.35.0, and the soversion was as well. Why flathub is trying to link against the old version is more a question for flathub than it is for us.

**Comment by sfan5** [comment]
Flathub (or Flatpak) isn't "linking" anything.
In your build script you are including the dynamically linked binary of your app, it depends on `libmpv.so.1`. Then you are including mpv 0.36.0, which provides `libmpv.so.2`. You need to recompile your app to match the runtime dependencies.

**Comment by tomekit** [comment]
Thanks @Traneptora and @sfan5 for your extremely helpful input. Since I have no "easy influence" on version of `libmpv` that my app is using (since I am using external library with that specific version of libmpv being used) it was easier to downgrade for me the MPV to 0.34.1 which resulted in `libmpv.so.1` being generated/
```
-          "url": "https://github.com/mpv-player/mpv/archive/refs/tags/v0.36.0.tar.gz",
-          "sha256": "29abc44f8ebee013bb2f9fe14d80b30db19b534c679056e4851ceadf5a5e8bf6"
+          "url": "https://github.com/mpv-player/mpv/archive/refs/tags/v0.34.1.tar.gz",
+          "sha256": "32ded8c13b6398310fa27767378193dc1db6d78b006b70dbcbd3123a1445e746"
```
... and things started to work.
