### ISSUE TITLE
mpv crashes when dbus is not available

### ISSUE THREAD

**Issue by prettySongbird** [mpv-player/mpv#12022]
### Important Information

Provide following Information:
- mpv version: 0.36.0
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: Arch repo
- If known which version of mpv introduced the problem: 0.36.0
- Window Manager and version: sway 1.8.1
- GPU driver and version: vulkan-radeon | 23.1.4-2
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Run mpv in an environment without dbus or with without access to "/run/dbus"

### Expected behavior

The primary features of mpv should work when dbus is una (everything that does not require dbus) 

### Actual behavior

mpv crashes with the following error:

```
mpv --no-config a.mp4
 (+) Video --vid=1 (*) (h264 1920x1080 24.000fps)
 (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 44100Hz)
dbus[42490]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file dbus-message.c line 1373.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```

Relevant strace:

`connect(26, {sa_family=AF_UNIX, sun_path="/run/dbus/system_bus_socket"}
`

### Log file

Make a log file made with -v -v or [output.txt](https://github.com/mpv-player/mpv/files/12164206/output.txt), paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

### Sample files
Any video file

Not sure if the issue is in mpv or a dependency but mpv 0.35 worked just fine without dbus.

**Comment by t-8ch** [comment]
A logfile would be great as would be a strace log.

**Comment by t-8ch** [comment]
Seems to be a pipewire, not a mpv problem:
```
$ DBUS_SYSTEM_BUS_ADDRESS=/ DBUS_SESSION_BUS_ADDRESS=/ pw-play /usr/share/sounds/freedesktop/stereo/dialog-error.oga 
dbus[47528]: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file dbus-message.c line 1373.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)

```

**Comment by prettySongbird** [comment]
Here is the full strace log 
[mpv-strace.txt](https://github.com/mpv-player/mpv/files/12164346/mpv-strace.txt)

**Comment by t-8ch** [comment]
Should be fixed by https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/55812195ce3b77317e7a2dc642b78271f3a45c8e
in the next pipewire release.

**Comment by prettySongbird** [comment]
> Should be fixed by https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/55812195ce3b77317e7a2dc642b78271f3a45c8e in the next pipewire release.

Yes, that is probably it. Thank you for the quick help
