### ISSUE TITLE
Playlists displayed in osc

### ISSUE THREAD

**Issue by CNhjx** [mpv-player/mpv#12021]
### Expected behavior of the wanted feature
Is it possible to replace the mpv's own playlist with a script-generated playlist?
Clicking the previous video or next video button in osd displays the playlist generated by playlistmanager.lua.
Currently clicking on the "Previous Video" or "Next Video" button in osd displays mpv's own playlist.
![image](https://github.com/mpv-player/mpv/assets/57735696/13936b91-f0fc-4ada-a649-910fa9abd916)

### Log file
[mpv.log.txt](https://github.com/mpv-player/mpv/files/12157310/mpv.log.txt)

**Comment by avih** [comment]
> Is it possible to replace the mpv's own playlist with a script-generated playlist?

There's no such option, and it's unlikely to be added.

However, you can disable the playlist display via `--script-opts-add=osc-playlist_osd=no` - https://mpv.io/manual/master/#on-screen-controller-playlist-osd , and you can write a script which displays whatever you want whenever the track changes, like the playlist from whatever other script you have.
