### ISSUE TITLE
`set dscale ""` at runtime would crash

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#12031]
### Important Information

Provide following Information:
- mpv version
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230726
- Windows Version
22H2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230726
- If known which version of mpv introduced the problem
N/a
- Possible screenshot or video of visual glitches
N/a

### Reproduction steps

0. load a video
1. `set dscale jinc` or bicubic/....etc and make sure mpv was doing dscaling.
2. `set dscale ""`

### Expected behavior

No crash

### Actual behavior

mpv exited at once

### Log file

[test3.log](https://github.com/mpv-player/mpv/files/12176873/test3.log)

### Sample files

N/a

**Comment by natural-harmonia-gropius** [comment]
An additional request:

I'm using gpu-next, and I got this with same steps. if I didn't set `--dscale` it will be same value as `--scale`, I want it fallback to value of `--scale` when I set it to "", also the `--cscale`.
![image](https://github.com/mpv-player/mpv/assets/50797982/1e366694-666d-4d48-b3b9-9f2ac234cb1f)

**Comment by sfan5** [comment]
It looks like the ability to set dscale empty was intentional (to mean dscale=scale) but the functionality behind it broke at some point.

**Comment by Artoriuz** [comment]
In the case you guys make scale imply dscale unless explicitly changed to something else, I think the same could be done for cscale.

**Comment by Dudemanguy** [comment]
I was too lazy to try anything before the meson build was added and it was still present then, so we've had this bug for a while.
