### ISSUE TITLE
--version or -V does not provide the version information

### ISSUE THREAD

**Issue by apsen-github** [mpv-player/mpv#12033]
`mpv --version` or `mpv -V` produces no output.

Windows 11.
Binary from https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20230723-git-ca4192e.7z/download

### Expected behavior

```
--version, -V
Print version string and exit.

```
### Actual behavior

No output.

### Log

[   0.000][d][global] user path: 'output.txt' -> 'output.txt'
[   0.003][v][cplayer] mpv 0.35.0-579-gca4192e2 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[   0.003][v][cplayer]  built on Sun Jul 23 01:30:52 2023
[   0.003][v][cplayer] libplacebo version: v6.292.0-13-gf53badb-dirty
[   0.003][v][cplayer] FFmpeg version: N-111598-gb2ceed406
[   0.003][v][cplayer] FFmpeg library versions:
[   0.003][v][cplayer]    libavutil       58.14.100
[   0.003][v][cplayer]    libavcodec      60.22.100
[   0.003][v][cplayer]    libavformat     60.10.100

**Comment by kasper93** [comment]
Do you have `mpv.com`? Does it work if you do `mpv.com --version`?

**Comment by apsen-github** [comment]
It does work with mpv.com... Interesting... What other functionality is only present in .com but not in .exe?

**Comment by garoto** [comment]
https://github.com/mpv-player/mpv/wiki/FAQ#on-windows-why-does-mpvexe-not-attach-to-the-console-and-what-does-mpvcom-do

**Comment by Dudemanguy** [comment]
Just a windows thing evidently.

**Comment by Hrxn** [comment]
Yeah, you should keep both `mpv.com` and `mpv.exe` on Windows.

If you use mpv on Windows with cmd.exe, Windows Terminal, ConEmu, or whatever else you may prefer, simply typing `mpv` ends up running `mpv.com`, because on any unchanged Windows installation, the `PATHEXT` environment variable is set like this, so this takes precedence:

```
PS C:\Windows\Temp> $env:PATHEXT
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PS C:\Windows\Temp>
```
