### ISSUE TITLE
Broken icon/thumbnail on Yosemite

### ISSUE THREAD

**Issue by kaffeesucht** [mpv-player/mpv#1203]
Clean installed Yosemite, and installed mpv through homebrew.
![screen shot 2014-10-21 at 01 21 49](https://cloud.githubusercontent.com/assets/7694114/4705803/5ce2518e-587f-11e4-8d49-31f3544fe161.png)
but preview is still displaying the correct icon.
![screen shot 2014-10-21 at 01 22 46](https://cloud.githubusercontent.com/assets/7694114/4705835/aa2a16de-587f-11e4-9d42-a2c29dfe7116.png)

**Comment by bodayw** [comment]
Update: I just saw the same issue here. The reason why I didn't see it is because I always use the list view in Finder, in which the "small icons" are properly shown. "Big icons" in the icon view are incorrect like in the OP.

**Comment by selsta** [comment]
`sudo rm -rf /Library/Caches/com.apple.iconservices.store` + a reboot fixes this issue.
