### ISSUE TITLE
default values on mpv.conf

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12042]
Over time I added some options to `mpv.conf` to the point where I think some of them are not necessary ("bloat"),
it can be because some default values have changed and I couldn't keep up with the changes (mainly some settings with `gpu-next`),
now I would like to get rid of some options to my `mpv.conf`, but how can I know what the default values and what are not (considering that the docs are not always up-to-date or correct?)
Is there an easy way to check each setting (without using the docs?) for example something like `--mpv --settings-a=help`?

**Comment by CounterPillow** [comment]
`mpv --list-options`
