### ISSUE TITLE
Subtitles turned off even when enabled in MKV container

### ISSUE THREAD

**Issue by Userblues** [mpv-player/mpv#12043]
Gentoo, ~amd64, mpv-0.36.0. 
I'm pretty sure 0.35.x did not have this problem. I tried studying the man page, but did not find a config option to restore proper functioning. When subtitles are in a separate file then mpv picks them up, but not if subs are embedded and turned on in mkv. Not sure if other operating systems are affected, I have no mpv in my Mac and Windows is long forgotten in my household.

**Comment by llyyr** [comment]
Post the values of the following env vars, if you have any set: LC_ALL, LC_MESSAGES, LANG, LANGUAGE. Also attach a log file.

**Comment by Userblues** [comment]
LANGUAGE is not set
LANG=en_US.utf8
LC_MESSAGES="en_US.utf8"
LC_ALL=

` $ mpv --no-config Lethal_Weapon_1987.mkv 
 (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
     Subs  --sid=1 --slang=eng (*) (subrip)
AO: [alsa] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
AV: 00:00:02 / 01:49:37 (0%) A-V:  0.000 Cache: 1024s/150MB
`
[mpvlog.gz](https://github.com/mpv-player/mpv/files/12206610/mpvlog.gz)

**Comment by llyyr** [comment]
`--subs-with-matching-audio=yes`

**Comment by moritz1000** [comment]
> `--subs-with-matching-audio=yes`

Thank you! I had the same issue since I updated MPV.
```
#Audio language priority
alang=ja,jp,jpn,en,eng,de,deu,ger

#Subtitle language priority
slang=en,eng,de,deu,ger
```
from my `mpv.conf` file did not work anymore.

After adding `subs-with-matching-audio=yes` to my `mpv.conf` everything works as before again!

**Comment by Userblues** [comment]
Thanks. Now I see it in the man page, too. Wasn't searching for right thing.

**Comment by Userblues** [comment]
I'm all for it. I use MPV also with Gaupol and current behavior of MPV is a pure annoyance.

**Comment by Userblues** [comment]
Even worse, now MPV turns subtitles on even if they are turned off in MKV. Really, a player should honor the settings in the media file.
