### ISSUE TITLE
0.36.0: selected application specific audio output is not remembered (by pipewire/wireplumber)

### ISSUE THREAD

**Issue by tgurr** [mpv-player/mpv#12041]
### Important Information
Provide following Information:
- mpv version: 0.36.0
- Linux Distribution and Version: Exherbo Linux
- Source of the mpv binary: Exherbo Package (source-based)
- If known which version of mpv introduced the problem: 0.36.0
- Window Manager and version: Kwin 5.27.6
- GPU driver and version: NVIDIA 535.86.05
- Possible screenshot or video of visual glitches: -
- Pipewire version: 0.3.76
- Wireplumber version: 0.4.14

`/etc/mpv/mpv.conf`:
```
hwdec=auto
cache=no
gpu-api=vulkan
ao=pipewire
vo=gpu-next
```
issue also happens when passing `--no-config`.

### Reproduction steps
With mpv 0.36.0:
1. Play any file with audio, switch audio output to headphones for the application mpv
2. See the setting not being remembered the next time you play another or the same file

![kde-plasma-mpv-0 36 0](https://github.com/mpv-player/mpv/assets/414984/be8a8070-6eed-4f71-ad94-8e6462eafd7b)

### Expected behavior
Like with mpv 0.35.1: Have the selected audio output device for the application mpv being remembered (by pipewire/wireplumber). The reason I'm reporting this here instead of pipewire/wireplumber is the fact that when I downgrade mpv back to 0.35.1 it works like intended again and I also didn't observe this issue with other applications like browsers, games and so on.

![kde-plasma-mpv-0 35 1](https://github.com/mpv-player/mpv/assets/414984/9b2f87fb-23f6-4585-b3a4-9492172bedb6)

### Actual behavior
Selected audio output device for the application mpv 0.36.0 is not being remembered.

### Log file
Nothing in regards to the problem is visible in the mpv logs.

### Sample files
Happens with any file.

**Comment by t-8ch** [comment]
This *should* be the same problem that #11253 tries to fix.
But the problematic commit 535cd6f is also in 0.35, so something else may be going on.

What happens for you with this patch:
```patch
diff --git a/audio/out/ao_pipewire.c b/audio/out/ao_pipewire.c
index 0a39e4e1a596..0e29f69e58a9 100644
--- a/audio/out/ao_pipewire.c
+++ b/audio/out/ao_pipewire.c
@@ -713,6 +713,7 @@ static int control(struct ao *ao, enum aocontrol cmd, void *arg)
                     break;
                 }
                 case AOCONTROL_UPDATE_MEDIA_ROLE: {
+                    break;
                     enum aocontrol_media_role *role = arg;
                     struct spa_dict_item items[1];
                     const char *role_str;
```

**Comment by tgurr** [comment]
> This _should_ be the same problem that #11253 tries to fix. But the problematic commit [535cd6f](https://github.com/mpv-player/mpv/commit/535cd6f3130a179890505535b1cb06998a9cb07f) is also in 0.35, so something else may be going on.
> 
> What happens for you with this patch:

Applying the attached patch indeed appears to fix the issue for me, the selected application specific output device is remembered again.
