### ISSUE TITLE
With --terminal=no (and --hwdec=auto) and standard error (stderr) closed mpv freezes/blocks/hangs

### ISSUE THREAD

**Issue by Earnestly** [mpv-player/mpv#12053]
Edit: Scratch this, the reproduction does not work but the issue may still be lurking.  I'll briefly explain what happened to see if it helps:

I start Xorg with `sx` and pipe both stdout and stderr to `busybox svlogd`, and as `sx` starts my window manager (`i3`) and my `xdg-open` script starts `mpv`, the stderr from mpv is eventually routed to `svlogd` and captured.

For some time now that `svlogd` has been crashing (at least according to my journal, without symbols so no useful trace): 

```
svlogd[983]: segfault at 7ff329e42c27 ip 00000000004c28e5 sp 00007fffddbb0a30 error 4 in busybox[401000+e2000] likely on CPU 3 (core 1, socket 0)
```

It was my belief that this was ultimately causing `mpv` to hang as it had nowhere to write its message (why SIGPIPE didn't stop sx/Xorg I'm not sure).  As a test I closed down Xorg and restarted using `| logger -e` instead of `svlogd` and `mpv` worked; the trouble is that it also worked with `2>&-` and I couldn't deve
lop a reproducer.

---

* Arch Linux

```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 05:49:29 2023
libplacebo version: v5.264.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```

```
mpv --no-config --hwdec=auto /path/to/video 2>&-
```

On my machine when `--hwdec=auto` is used mpv will normally write `Cannot load libcuda.so.1` to standard error but as standard error is closed mpv appears to just hang.

I have tried to bisect this problem back to `0.35.0` but it is still present.  Unfortunately when attempting to bisect further back to `0.34.0` I am no longer able to build due to my version of ffmpeg being too recent (implicit function declaration errors).

Note that when mpv was built prior to the commit https://github.com/mpv-player/mpv/commit/2dc8e70093d9f80a01696f059ff02784bcb7b5f0 it exits 1 instead of hanging.

**Comment by sfan5** [comment]
I'm not sure how svlogd crashing is related but it sounds like you should investigate that first.

> On my machine when `--hwdec=auto` is used mpv will normally write `Cannot load libcuda.so.1` to standard error [...]

FYI this is not mpv's doing but some other library.

I'm also pretty sure that running programs with any of the three stdio files closed violates the expectations of 95% of C code, if not also some standard. So better just don't do that.

**Comment by Earnestly** [comment]
Yeah it may not even be related to stderr being closed at all, but the issue does trigger on that attempted write by some means that I've not yet determined.  Since there is still the possibility of a hang it may be found by someone else but who might have a reproduction for it unlike me.
