### ISSUE TITLE
Gpu-next master android

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#12056]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there just a quick question I was just wondering if there was any news on if gpu-next will be coming to the next update for the android version of MPV I understand that it is present in the vulkan test version however it Is clear now in that version that it is stable enough to add for android users using gpu-api=opengl and gpu- context = android so was wondering if this compatibility will be added to the master version I am only asking as I'm sure others will agree that we would like to be able to use the new HDR tonemapping options and other options which are gpu-next only when android is the only device we have to use MPV and it is now been tested that it can be used and is stable with opengl despite vulkan not being stable yet thanks

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by philipl** [comment]
Questions about Android should be asked in the https://github.com/mpv-android/mpv-android/ project.
