### ISSUE TITLE
smoother `frame-step-back` continuity

### ISSUE THREAD

**Issue by asklow** [mpv-player/mpv#12055]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 05:49:29 2023
libplacebo version: v5.264.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```
- Platform and Version : **`Linux arch 6.4.6-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC, x86_64`**
- Source of the mpv binary : [**`pacman`**](https://archlinux.org/packages/extra/x86_64/mpv/)

### Reproduction steps
Hold `frame-step-back` key. Then compare it with hold `frame-step` key

### Expected behavior
`frame-step` has good continuity, like as it runs normally at the source frame rate. Same behaviour is expecting from `frame-step-back`

### Actual behavior
`frame-step-back` takes a break inbetween the back steps it take. There's no source framerate continuity.

**Comment by dexeonify** [comment]
#4019

**Comment by christoph-heinrich** [comment]
Reversing playback direction doesn't work with all codecs (might be a limitation of the decoder, idk), so that's probably why.

**Comment by hooke007** [comment]
I think the [contents about --play-dir in the manual](https://mpv.io/manual/master/#options-play-dir) already answered your question.
