### ISSUE TITLE
increased brightness of the screenshot in 0.36 version if it is created in png and with --vo=gpu-next

### ISSUE THREAD

**Issue by AdventurerRussia** [mpv-player/mpv#12063]
hello, I updated to 0.36 version and noticed that when I watch an hdr movie and then screenshots too bright started to be created compared to the 0.35.1 version, I found it by brute force.
If you use the keys: 
--screenshot-format=png
--vo=gpu-next 
Then the screenshot picture is too light, there was no such thing in the previous version of the player.
If you save it in jpg format, then the brightness of the screenshot as in the previous version of the player comes out.
also, if you remove the --vo=gpu-next key, then the brightness is as in 0.35.1 version.
https://slow.pics/c/duHqoPmA
on 0001 of the screenshot, the brightness is normal, on 0002 the brightness in the new version of the player
here is a comparison between screenshots and the player
![image](https://github.com/mpv-player/mpv/assets/14019010/622f63d0-4c8f-4735-b3f0-44dbd22ca5fa)
In general, in the new version, screenshots began to be taken like this. Maybe someone knows how to solve it?
player builds https://sourceforge.net/projects/mpv-player-windows/files/release/
no keys other than screenshot format keys and gpu-next

**Comment by quietvoid** [comment]
Try using `--screenshot-tag-colorspace=no` if you want SDR screenshots.

**Comment by AdventurerRussia** [comment]
> Try using `--screenshot-tag-colorspace=no` if you want SDR screenshots.

Oh, it helped, thank you very much
