### ISSUE TITLE
Target-trc question

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#12060]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I was using mpv to tonemap hdr movies however when I add target-trc=pq to the image it seems to greatly improve the colour of the picture and the colours show up a lot brighter and stronger however if I add target-prim=bt.2020 it makes the picture washed out it only seems to improve the colour when target-trc is used on its own without setting a target-prim does this mean this is hdr pass through or not I can show screenshots of content with and without target-trc=pq
Thanks 

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by Traneptora** [comment]
That means your display isn't using BT.2020 primaries.
