### ISSUE TITLE
Select multiple playlist files in one option

### ISSUE THREAD

**Issue by FFFluoride** [mpv-player/mpv#12064]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
Instead of typing `mpv --playlist=[filename] --playlist=[filename] --other-options`
Be able to type something like `mpv --playlists="filename filename filename --other-options"`

**Comment by Traneptora** [comment]
You can just do `mpv filename1 filename2 filename 3 --other-options`

**Comment by FFFluoride** [comment]
Just tried that and that doesn't work for playlists

**Comment by Hrxn** [comment]
Yes, intentional.
Workaround: Use a shell script to concatenate all your desired playlists on the fly, and then simply load that one into mpv. 😄

**Comment by Dudemanguy** [comment]
A string list option can't work here. As mentioned, typical separator characters are totally valid to have in filenames so how would mpv know the difference? Sure having to specify `--playlist=` for each one is a little unwieldy but it gets the job done. Alternatively, if you give your files some sort of known playlist extension (such as m3u), then mpv will always parse them as a playlist by default so you wouldn't need `--playlist=`.
