### ISSUE TITLE
Which version to pick for Windows x64 (release/64bit-v3/64bit)

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12068]
Hi, I am confused on what the difference is and which is the intended version on the website for Windows x64
What does "v3" mean?

Thanks for helping
![version](https://github.com/mpv-player/mpv/assets/139760266/961c8465-10ab-4b03-9204-fad5504af08a)

**Comment by dokur0chan** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Difference-between-x86_64-and-x86_64-v3

**Comment by geextahslex** [comment]
okie dokie, thanks :)

**Comment by hooke007** [comment]
Almost placebo.

**Comment by Hrxn** [comment]
> Almost placebo.

Not sure, I'll believe it when I see good benchmarks.

As a rule of thumb: If your CPU can run x86_64 v3, you should run x86_64 v3
