### ISSUE TITLE
I have a question about 5.1 surround/downmixing

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12065]
Hi, I have a question about 5.1 surround/downmixing
Is there a way to use mpv with AC3Filter? Or a command that gives me the volume control of the surround channels before they get downmixed?
I want to decrease the volume of: left, right, left rear, right rear, to get better speech clarity from the central channel. Which I can do with AC3Filter in MPC.

I am new to mpv and commands in general, sorry if something is wrong with my question.
Thank you :)

A visualization of what I mean
![AC3Filter](https://github.com/mpv-player/mpv/assets/139760266/5f36c7d7-1ef5-4858-a817-5abf44a56255)

**Comment by kasper93** [comment]
Yes, you can configure downmixing, here are some examples https://github.com/mpv-player/mpv/issues/11901#issuecomment-1627675040 and in lavfi documentation https://ffmpeg.org/ffmpeg-filters.html#Mixing-examples
