### ISSUE TITLE
Shader cache files are written to the directory passed to --config-dir

### ISSUE THREAD

**Issue by Aanok** [mpv-player/mpv#12077]
#### mpv version
```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 05:49:29 2023
libplacebo version: v5.264.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```

#### Linux Distribution and Version
Arch Linux, updated as of 2023/08/05.

#### Source of the mpv binary
[Official repo package](https://archlinux.org/packages/extra/x86_64/mpv/).

#### Which version of mpv introduced the problem
0.35. Also libmpv 2.0+ (which is probably obvious).

### Reproduction steps
1. Have a configuration that caches shaders to file (e.g. `profile=gpu-hq`).
2. Launch mpv passing `--config-dir=XXX` and in a way that it opens a window (e.g. `--player-operation-mode=pseudo-gui` or playing any video file).

### Expected behavior
The shader cache files are written to the cache dir (e.g. XDG_CACHE_HOME) and not the config dir.

### Actual behavior
The shader cache files are written to the explicit config dir.

### Log file
[mpv.log](https://0x0.st/H27n.log)

Thanks!

**Comment by Dudemanguy** [comment]
That's expected. Using `--config-dir` overrides all the other directories by design.

**Comment by Aanok** [comment]
Oh gosh. I gotta say it's not very clear from the manual:
```
--config-dir=<path>

    Force a different configuration directory. If this is set, the given directory is used to load configuration files, and all other configuration directories are ignored. This means the global mpv configuration directory as well as per-user directories are ignored, and overrides through environment variables (MPV_HOME) are also ignored.

    Note that the --no-config option takes precedence over this option.
```

Also, where could I go for a feature request of an argument to set the, err, "persistent" cache directory? :P As opposed to the rightfully volatile --cache-dir.

**Comment by Aanok** [comment]
Sorry, I'd missed the second half of your comment. Sorry and thanks!

**Comment by Dudemanguy** [comment]
The manual could be clearer on this. I think we documented the behavior with environment variables but not the `--config-dir` option itself.
