### ISSUE TITLE
44100Hz DTS incorrectly played at 48000Hz when using passthrough results in sped up audio

### ISSUE THREAD

**Issue by bgx90** [mpv-player/mpv#12078]
### Important Information

Provide following Information:
- mpv version: 0.35.1 (latest version in Debian's official repository)
- Linux Distribution and Version: Debian testing (codename: trixie)
- Source of the mpv binary: Debian testing repository
- If known which version of mpv introduced the problem: unknown, it existed in mpv 29.1 according to #6651
- Window Manager and version: Suckless dwm 6.3
- GPU driver and version: X.Org X server -- Nouveau display driver 1:1.0.17-2
- Possible screenshot or video of visual glitches: na

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

**Setup**
1) Using pipewire, wireplumber and pipewire-pulse as the PulseAudio backend
2) AV receiver is connected to computer by HDMI

**In pavucontrol**
1) Under Playback, ensure that no clients are connected
2) Under Configuration, set profile for HDMI device to Digital Stereo
3) Under Output Devices, open the Advanced section under the HDMI device
and enable DTS and AC-3 (Sometimes I have to check, uncheck, and recheck
a box to make it take affect, so I run the command `pactl list sinks`
on the terminal to confirm that the selected formats are listed
in the HDMI sink's formats section.)

IMPORTANT: Close pavucontrol when finished with the above steps.
Leaving pavucontrol open sometimes makes the sound device unavailable for passthrough

**In terminal**
Using pipewire:
1) `mpv --no-config --audio-device='pulse/alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1' --audio-spdif=dts --audio-channels=5.1 surroundTestDTS.dts.wav`
2) `mpv --no-config --audio-device='pulse/alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1' --audio-spdif=ac3 --audio-channels=5.1 surroundTest.ac3`

Using ALSA directly (bypassing pipewire completely):
1) `mpv --no-config --audio-device='alsa/hdmi:CARD=NVidia,DEV=1' --audio-spdif=dts --audio-channels=5.1 surroundTestDTS.dts.wav`
2) `mpv --no-config --audio-device='alsa/hdmi:CARD=NVidia,DEV=1' --audio-spdif=ac3 --audio-channels=5.1 surroundTest.ac3`

### Expected behavior

1) Compressed DTS audio is passed through to the AV receiver.
2) DTS audio is played at the correct speed.
3) Compressed AC-3 audio is passed through to the AV receiver.
4) AC-3 audio is played at the correct speed.

### Actual behavior

1) Compressed DTS audio is passed through to the AV receiver.
2) DTS audio's playback speed is to high (compared to playing
the dts file without passthrough and the identical ac-3 file)
3) Compressed AC-3 audio is passed through to the AV receiver.
4) AC-3 audio is played at the correct speed.

**The issue seems to be that 44100Hz DTS audio is incorrectly played back at 48000Hz when using passthrough.**
 When 44100Hz DTS audio is played with passthrough, mpv reports that it is playing with a sample rate of 48000Hz and the audio is sped up. When playing 44100Hz DTS audio without using passthrough, mpv reports that is is playing with a sample rate of 44100Hz and the audio is played at the correct speed. When playing 44100Hz AC-3 audio with or without using passthrough, mpv reports that it is playing with a sample rate of 44100Hz, and AC-3 always sounds correct.

This seems to be like the behavior observed in #6651 which
was closed without a resolution.

### Log file

[dts_bitstreaming_log.txt](https://github.com/mpv-player/mpv/files/12265364/dts_bitstreaming_log.txt)

### Sample files

DTS sample: https://0x0.st/H2hB.dts.wav
AC-3 sample: https://0x0.st/H2hu.ac3

Original sources of the above files:
https://archive.org/download/5.1SurroundSoundTestFilesVariousFormatsAACAC3MP4DTSWAV/surroundTestDTS.dts.wav
https://archive.org/download/5.1SurroundSoundTestFilesVariousFormatsAACAC3MP4DTSWAV/surroundTest.ac3

**Comment by mitzsch** [comment]
@bgx90 
I know this is now a bit aged, but I created a testing build that should treat DTS 44.1khz correctly. No warranty, however.

https://drive.google.com/file/d/10-vVr4DkNdesFs1WO0SwrDyswGia2svi/view?usp=sharing

Please let me know if this one works!

**Comment by nabsltd** [comment]
Your fix works.
I'm not the OP, but I was having the same issue (although on Windows), and Google brought me here. I downloaded your build, and it fixed the problem for me.

**Comment by mitzsch** [comment]
Awesome, thanks for the feedback, then I will file a pull request...

**Comment by mitzsch** [comment]
@sfan5 
This can be closed now. :)
