### ISSUE TITLE
d3d12va hwdec and d3d12 gpu-context

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#12071]

**Comment by suger520HT** [comment]
> Before requesting a new feature make sure it hasn't been requested yet. [ meta:feature-request](https://github.com/mpv-player/mpv/labels/meta%3Afeature-request)
> 
> ### Expected behavior of the wanted feature
> Implementing d3d12 gpu context and d3d12va hwdec
> 
> Intel has submitted FFmpeg [d3d12 patch v4](https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230719100202.1584-1-tong1.wu@intel.com/), this feature may be merged soon.
> 
> I have built ffmpeg with d3d12va and tested mpv , the performance seems to be very much improved compared to d3d11va-copy, and it is already able to playback 8K 60 FPS videos without frame drop.`hwdec=d3d12va-copy`
> 
> ### Alternative behavior of the wanted feature
> N/A
> 
> ### Log file
> N/A

If the submission is successful, please let me know and can't wait to try it

**Comment by mitzsch** [comment]
It would be nice if d3d12 could be added, especially for this one =>

> performance issues d3d11(va) has on some GPUs, 

 Playing back 8K60HDR AV1 files is a pain with mpv right now. An RTX3050 drops frames like crazy, and an RTX 3060Ti is only slightly better but still drops frames... Only with an ARC A770 I only had one dropped frame... I don´t get it, all Nvidia GPUs tested should be more than capable of playing back 8K60HDR video... If d3d12 would help with that, why not plan to implement this? Also, considering what might come in the future...


@arm64-v9a What hardware have you used for the 8K60 playback test?

**Comment by mitzsch** [comment]
> For 8KHDR videos, any copy hwdec will drop frames, in order to play these videos, you need to use a low-level native hwdec:

Exactly, but even with the native low-level decode I m dropping frames with the Nvidia cards (-copy not even tested...)
Hopefully, this will be better with d3d12 native...

**Comment by kasper93** [comment]
I must say I don't see much incentive to implement d3d12, while Vulkan in first class citizen on Windows anyway. Honestly I view d3d11 as compatibility backed for when the Vulkan is not available. Of course nattiness of video decoding plays a part with it, because `-copy` indeed has some performance penalty.

> the performance seems to be very much improved compared to d3d11va-copy

What difference are we talking about? Can you give us some numbers with `-f null - -benchmark` in ffmpeg or otherwise in mpv. You can also test vaapi on Windows, which is it also slower? I would rather investigate why the performance difference is there first.

Spinning out whole new backend is some work and we need some incentive to work on it, except the fact it is available and has higher version number. I honestly think new backend is not needed, it just more fragmentation of userbase, less testing and so on. It would be fun project, but you have to convince me it is needed and will actually be used by more than 5 people.

**Comment by kasper93** [comment]
I meant unlike opengl which on Windows never got any love. Vulkan seems to have more traction, but I agree VkVideo is hit or miss. Speaking off just for comparison what is the speed on VkVideo in your setup?

**Comment by suger520HT** [comment]
> > but you have to convince me it is needed and will actually be used by more than 5 people.
> 
> There are already five people interested in this, and once the d3d12 is implemented, I can't think of any reason for people to keep using d3d11.

When will it be merged into the main project

**Comment by suger520HT** [comment]
> > Actually  is unusable for me, since videos of 60fps are stuttering like crazy (linked issue: #10716) I'm "forced" to use d3d11`gpu-api=vulkan`
> 
> I can't reproduce it, even with 8K HDR60 video.


Do I need to install the latest driver to use vulkan?

**Comment by suger520HT** [comment]
> > > > Actually  is unusable for me, since videos of 60fps are stuttering like crazy (linked issue: #10716) I'm "forced" to use d3d11`gpu-api=vulkan`
> > > 
> > > 
> > > I can't reproduce it, even with 8K HDR60 video.
> > 
> > 
> > Do I need to install the latest driver to use vulkan?
> 
> There are always a million problems with nvidia's vulkan drivers, I recommend always using the latest drivers. In the past, vkbeta was the best, but vkbeta today is still based on the R525 branch, so its KMD is outdated and I recommend using the latest Studio drivers.

What is the difference between game reday and studio?

**Comment by suger520HT** [comment]
> > > > > > Actually  is unusable for me, since videos of 60fps are stuttering like crazy (linked issue: #10716) I'm "forced" to use d3d11`gpu-api=vulkan`
> > > > > 
> > > > > 
> > > > > I can't reproduce it, even with 8K HDR60 video.
> > > > 
> > > > 
> > > > Do I need to install the latest driver to use vulkan?
> > > 
> > > 
> > > There are always a million problems with nvidia's vulkan drivers, I recommend always using the latest drivers. In the past, vkbeta was the best, but vkbeta today is still based on the R525 branch, so its KMD is outdated and I recommend using the latest Studio drivers.
> > 
> > 
> > What is the difference between game ready and studio?
> 
> No difference on the driver side, just a different workaround profile for some application shit bugs, the studio driver doesn't insert a bunch of workarounds like GRD driver does, which affects benchmark and bug replication


Will it affect the game?

**Comment by Jules-A** [comment]
>now that d3d11 is lagging significantly behind vulkan in video rendering performance.

On my 6700XT, at least comparing performance 1080p upscaled with heavy shaders, I get on average higher fps with D3D11, Vulkan can be faster in some scenes but it will cause my GPU to run close to max so kind of noisy. Not only that but D3D11 is smoother for me. I haven't tried testing with higher res video though and Vulkan seems to be constantly improving, it wasn't that long ago that Vulkan wasn't even an option due to bugs.

**Comment by Jules-A** [comment]
> Unfortunately there is no native hwdec available for AMDGPUs using winvk on Windows, on NVIDIA both nvdec and vulkan are top notch in terms of performance.

Like I said before, I'm just watching 1080p source so decoding performance is irrelevant (actually I'm using software decoding to try and free resources for the GPU)... If you are saying Vulkan decoding performance is better then that's different to rendering.

**Comment by Jules-A** [comment]
> Native hwdec reduces GPU memory bandwidth requirements and reduces DMA engine load, and some GPUs implement GPGPU-assisted hwdownload/hwupload, so it may also reduce the load on the 3D unit. This can improve the performance of heavy shaders running on bandwidth constrained GPUs.

I'm seeing the opposite with D3D11VA though: https://imgur.com/a/6DPQwSG

**Comment by Jules-A** [comment]
> > > Native hwdec reduces GPU memory bandwidth requirements and reduces DMA engine load, and some GPUs implement GPGPU-assisted hwdownload/hwupload, so it may also reduce the load on the 3D unit. This can improve the performance of heavy shaders running on bandwidth constrained GPUs.
> > 
> > 
> > I'm seeing the opposite with D3D11VA though: https://imgur.com/a/6DPQwSG
> 
> As the GPU bandwidth bottleneck has eased, the 3D engine is able to be fully utilized, which is to be expected, and you should notice an increase in fps if the frame rate is unlimited.

Make sure you read the labels on the images, with D3D11va it was able to go to 100% but it kept dropping to 96-98% while with software it was a constant 99%. FPS was lower with hwdec. This is just 1080p H264 though, I have a feeling H265 would be a completely different story but I don't watch any of that content except for videos I've created with ReLive which are higher res and just have basic shaders applied.

**Comment by mitzsch** [comment]
Hopefully, this gets reevaluated and the "on-ice" label gets removed when the d3d12 stuff is merged into ffmpeg...

**Comment by suger520HT** [comment]
"d3d12-adapter=GPU" Has this feature been merged

**Comment by suger520HT** [comment]
gpu-context=d3d12 d3d12-adapter=GPU Are these two options not available

> https://ffmpeg.org/pipermail/ffmpeg-devel/2023-August/313696.html d3d12va will not be available in ffmpeg 6.1
