### ISSUE TITLE
Audio Device wildcard string

### ISSUE THREAD

**Issue by fredngo** [mpv-player/mpv#12085]
### Expected behavior of the wanted feature

The problem is that every time I plug in an external USB device, the audio device string is different.

For example, see the string for the Logitech USB Headset:

```
fred@whale mpv % mpv --audio-device=help
List of detected audio devices:
  'auto' (Autoselect device)
  'coreaudio/AppleUSBAudioEngine:Logitech:Logitech USB Headset:100000:2,1' (Logitech USB Headset)
  'coreaudio/BuiltInSpeakerDevice' (MacBook Pro Speakers)
  'coreaudio/MSLoopbackDriverDevice_UID' (Microsoft Teams Audio)
  'coreaudio/zoom.us.zoomaudiodevice.001' (ZoomAudioDevice)
fred@whale mpv % mpv --audio-device=help
List of detected audio devices:
  'auto' (Autoselect device)
  'coreaudio/AppleUSBAudioEngine:Logitech:Logitech USB Headset:1100000:2,1' (Logitech USB Headset)
  'coreaudio/BuiltInSpeakerDevice' (MacBook Pro Speakers)
  'coreaudio/MSLoopbackDriverDevice_UID' (Microsoft Teams Audio)
  'coreaudio/zoom.us.zoomaudiodevice.001' (ZoomAudioDevice)
```

I would like to be able to place in `mpv.conf` something like:

```
--audio-device="coreaudio/AppleUSBAudioEngine:Logitech:Logitech USB Headset:[0-1]+:2,1"
```

In that case,`[0-1]+` is a regexp to say 0 or 1 at least once. But I don't necessarily care how to specify the wildcard, whatever is easiest!

Then, it won't matter what the audio device string actually is.

### Alternative behavior of the wanted feature

None, really!

### Log file

See the sample console output above.

**Comment by hooke007** [comment]
`--audio-device="coreaudio/(Logitech USB Headset)"`

**Comment by hooke007** [comment]
`--audio-device="coreaudio/Logitech USB Headset"` should work.

**Comment by fredngo** [comment]
> `--audio-device="coreaudio/Logitech USB Headset"` should work.

Did not even think to try that. Will try!

**Comment by fredngo** [comment]
@hooke007 I regret to report back that `--audio-device="coreaudio/Logitech USB Headset"` does not work.

With that string, mpv opens, but crashes when I try to play audio.

This string doesn't work either: ``coreaudio/AppleUSBAudioEngine:Logitech:Logitech USB Headset`

Was really hoping that your string would do what I need it to do!

😞

**Comment by fredngo** [comment]
I got around this problem by purchasing another external USB sound dongle where the audio device string doesn't change, no matter which USB port I plug it into.

Closing the issue, as it no longer affects me personally. If it continues to affect anyone else, you can reopen the issue.
