### ISSUE TITLE
Property display-hidpi-scale is not updated when moving to another monitor

### ISSUE THREAD

**Issue by Erijoda** [mpv-player/mpv#12081]
### Important Information

The issue causes scaling issues for text in console and statistics. 3rd party scripts that uses display-hidpi-scale for correct scaling is also affected.

Provide following Information:
- mpv version: mpv 0.35.1, mpv 0.36.0
- Windows Version: Windows 11 22H2 (22621.1992)
- Source of the mpv binary: Chocolatey package mpvio
- If known which version of mpv introduced the problem: Unknown

### Reproduction steps
Primary monitor is 150% dpi. Secondary monitor(s) 100% dpi.

1. mpv --no-config --force-window --idle
2. open console
3. print-text ${display-hidpi-scale}
4. move window to secondary monitor
5. print-text ${display-hidpi-scale}

### Expected behavior
Expected output to be 1.500 for 150% dpi monitor and 1.000 for 100% dpi monitor.

### Actual behavior
Output is 1.500 for 150% dpi monitor and 1.500 for 100% dpi monitor.

if mpv is opened from explorer on 100% dpi monitor the behavior will be the same except it then outputs 1.000 for both monitors.
When opening mpv from a terminal it will always use primary monitor's dpi regardless of --screen selection.

### Log file
[https://0x0.st/H_ry.txt](https://0x0.st/H_ry.txt)

**Comment by Dudemanguy** [comment]
Completely untested, but it looks like the w32 code handles this but never signals mpv's core for some reason. So in theory this one line is all that is needed.
```
diff --git a/video/out/w32_common.c b/video/out/w32_common.c
index 07ae957be7..08843d6378 100644
--- a/video/out/w32_common.c
+++ b/video/out/w32_common.c
@@ -563,6 +563,7 @@ static void update_dpi(struct vo_w32_state *w32)
 
     w32->dpi = dpi;
     w32->dpi_scale = w32->opts->hidpi_window_scale ? w32->dpi / 96.0 : 1.0;
+    signal_events(w32, VO_EVENT_DPI);
 }
 
 static void update_display_info(struct vo_w32_state *w32)
```
Can anyone confirm?

**Comment by Erijoda** [comment]
> Completely untested, but it looks like the w32 code handles this but never signals mpv's core for some reason. So in theory this one line is all that is needed.
> 
> ```
> diff --git a/video/out/w32_common.c b/video/out/w32_common.c
> index 07ae957be7..08843d6378 100644
> --- a/video/out/w32_common.c
> +++ b/video/out/w32_common.c
> @@ -563,6 +563,7 @@ static void update_dpi(struct vo_w32_state *w32)
>  
>      w32->dpi = dpi;
>      w32->dpi_scale = w32->opts->hidpi_window_scale ? w32->dpi / 96.0 : 1.0;
> +    signal_events(w32, VO_EVENT_DPI);
>  }
>  
>  static void update_display_info(struct vo_w32_state *w32)
> ```
> 
> Can anyone confirm?

It appears to work. Tested by compiling with MSYS2.

0.36.0:
![image](https://github.com/mpv-player/mpv/assets/6853927/f9c87515-a2d3-499f-89b0-1209c67644fd)


self compiled with the added signal_events:
![image](https://github.com/mpv-player/mpv/assets/6853927/0f8d35f0-bd46-4915-aa3b-1b0e56c2dd49)

**Comment by Dudemanguy** [comment]
>It appears to work. Tested by compiling with MSYS2.

Thanks. Should be good then.
