### ISSUE TITLE
mpv wasm+webgpu+webcodecs

### ISSUE THREAD

**Issue by arm64-v9a** [mpv-player/mpv#12088]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
Compile libmpv to wasm, decoding in browser using WebCodecs, and rendering using WebGPU.

```
gpu-api=webgpu
hwdec=webcodecs(-copy)
```

I have no need for this and don't expect this feature to be implemented, it's just an idea, and since FFmpeg has no plans to support WebGPUs/WebCodecs, this will probably never be implemented.

### Alternative behavior of the wanted feature
N/A
### Log file
N/A

**Comment by sfan5** [comment]
> I have no need for this and don't expect this feature to be implemented, it's just an idea

We'll leave it on the "ideas" pile then.
