### ISSUE TITLE
How stretch the video like in MPC-HC?

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12083]
Hi, how do I stretch the video, in mpv, like in MPC-HC when I use Numpad 4/6 or 2/8?
I couldn't find a keyboard shortcut for this function in mpv.

Thank you

**Comment by Traneptora** [comment]
What do you mean by "stretch the video"

**Comment by geextahslex** [comment]
From this
![dfdf](https://github.com/mpv-player/mpv/assets/139760266/145f6b4a-53fb-407a-99b8-ac79ea093a44)
to that
![dfdfdf](https://github.com/mpv-player/mpv/assets/139760266/dd7d35bc-50a3-4114-98b3-5116efed929d)

**Comment by hooke007** [comment]
The similar feature https://mpv.io/manual/master/#options-no-keepaspect however it is limted to the window size.

**Comment by Dudemanguy** [comment]
Do you just want to change the aspect ratio? shift+a cycles through common ones.

**Comment by hooke007** [comment]
aspect ratio is also limited to window size.

**Comment by Dudemanguy** [comment]
Well of course. The pictures he posted are all the same resolution so it seems like to me he just wants to ruin the picture by setting the wrong aspect ratio.

**Comment by hooke007** [comment]
I know what he want. Sth like `video-zoom` but only handling X or Y direction.

**Comment by Dudemanguy** [comment]
There's panscan (w and e) as well. But I don't know what he wants.

**Comment by Motophan** [comment]
@hooke007 @Dudemanguy 
He doesnt want any of that, he wants to stretch the video (like in MPCHC)

**Comment by dokur0chan** [comment]
Goes into mpv.conf:
`--video-aspect-override=16:9`
Could also try this and keep `--geometry` centered.
`--no-keepaspect --no-border --autofit=<insert desired resolution here>`

![image](https://github.com/mpv-player/mpv/assets/139610756/fc5a3220-3a69-4ebb-8161-7bab428b1ddc)

**Comment by Motophan** [comment]
Media Player Classic - Home Cinema (MPC-HC) is a video player that has several options to stretch video. You can stretch the video by right-clicking on the screen while playing a video and selecting “Video Frame” from the pop-up menu. This option allows you to change the zoom level and aspect ratio of the video. Another option is to use the “Pan & Scan” option which also affects aspect ratio. MPC-HC also allows you to rotate, flip, mirror, stretch and zoom the video.

**Comment by hooke007** [comment]
I know what mpc-hc's numpad 2/8 does. That's the behav I described.

**Comment by Motophan** [comment]
Guys, he wants to STRETCH the VIDEO. Not any of that stuff.

**Comment by hooke007** [comment]
> Sth like video-zoom but only handling X or Y direction.

It means `STRETCH`.

**Comment by Dudemanguy** [comment]
I haven't used MPC-HC in like a decade so I have no idea what "stretch the video" is supposed to mean if it's apparently not changing the aspect ratio or panscan. ¯\_(ツ)_/¯

**Comment by Motophan** [comment]
He wouldnt have X Y direction, you dont need to move it around the screen, just increase X or Y irrespective of the other. 

So if you X+1, Y does not go Y+1. It stays Y.
Example: if the window was 640x480 and he stretched it to 820x480 the video output would be 640x480 but scaled to a 820x640 window

**Comment by hooke007** [comment]
I think you don't understand what I am talking about at all.

**Comment by Motophan** [comment]
bruh he doesnt want the video output to be changed since that would introduce black bars

**Comment by hooke007** [comment]
Well I found the feature is there. https://mpv.io/manual/master/#options-video-scale-x

**Comment by geextahslex** [comment]
@hooke007 Wow, amazing, thanks :D

**Comment by kasper93** [comment]
This thread made me giggle inside, what was unclear about "stretching video in one dimension"? 👯 

Since you mention MPC-HC, to mimic it's behavior you can define those key bindings.
```
KP1 add video-zoom -0.01
KP2 add video-scale-y -0.01
KP4 add video-scale-x -0.01
KP5 set video-scale-x 1 ; set video-scale-y 1 ; set video-zoom 0 
KP6 add video-scale-x  0.01
KP8 add video-scale-y  0.01
KP9 add video-zoom 0.01

Alt+KP1 add video-rotate -1 
Alt+KP5 set video-rotate 0
Alt+KP3 add video-rotate 1

Ctrl+KP1 add video-pan-x -0.01 ; add video-pan-y 0.01
Ctrl+KP2 add video-pan-y 0.01
Ctrl+KP3 add video-pan-x 0.01 ; add video-pan-y 0.01
Ctrl+KP4 add video-pan-x -0.01
Ctrl+KP5 set video-pan-x 0 ; set video-pan-y 0
Ctrl+KP6 add video-pan-x 0.01
Ctrl+KP7 add video-pan-x -0.01 ; add video-pan-y -0.01
Ctrl+KP8 add video-pan-y -0.01
Ctrl+KP9 add video-pan-x 0.01 ; add video-pan-y -0.01
```

**Comment by UnkwUsr** [comment]
one more solution using ffmpeg filters: `mpv vid.mp4 --lavfi-complex="[vid1]setdar=8/5[vo]"`, where `8/5` is desired ratio

**Comment by kasper93** [comment]
> one more solution using ffmpeg filters: `mpv vid.mp4 --lavfi-complex="[vid1]setdar=8/5[vo]"`, where `8/5` is desired ratio

You know you can do the same with `--video-aspect-override` and `--video-aspect-method`
