### ISSUE TITLE
MPV auto-resize doesn't work with Wayland

### ISSUE THREAD

**Issue by adam900710** [mpv-player/mpv#12092]
### Important Information

Provide following Information:
- mpv version `0.36.0`
- Linux Distribution and Version `Archlinux` `Latest Rolling`
- Source of the mpv binary `Archlinux official repo`
- If known which version of mpv introduced the problem `Not a regression`
- Window Manager and version `plasmashell 5.27.6`
- GPU driver and version `mesa 23.1.4`

On X11 KDE, the video size is slightly larger than the available space (as the taskbar takes tens of pixels),
thus it would autoresize to smaller scale, when moved by the user.

But this is not the case for Wayland based DE.

### Reproduction steps

1. Prepare a video which is exactly the size of the screen (tested with 1920x1080 video)
2. Play the video with MPV under wayland DE/WM which has an dock/taskbar taking some space, and try moving the window

### Expected behavior

The mpv would be scaled down (to around 720p resolution) to show the full video, no matter if it's X11 or Wayland.

### Actual behavior

The mpv only auto-scaled down when running under X11, but not Wayland.

### Log file
[x11.txt](https://github.com/mpv-player/mpv/files/12269190/x11.txt)

[wayland.txt](https://github.com/mpv-player/mpv/files/12269191/wayland.txt)

**Comment by llyyr** [comment]
mpv does not automagically resize the window, you most likely had some window rule set for mpv on your X11 session that didn't carry over to the Wayland session

**Comment by Dudemanguy** [comment]
There is no code to "auto-scale down" in X11.
