### ISSUE TITLE
gpu-next: Support for //!TYPE DEFINE in user shaders having variable data

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [mpv-player/mpv#12093]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature

https://github.com/natural-harmonia-gropius/hdr-toys/blob/master/gamut-mapping/clip_custom.glsl

These two be equivalent:

![image](https://github.com/mpv-player/mpv/assets/50797982/8af71b60-8fa7-4de5-b1fd-ec41a0c8191d)

### Log file

```
[   0.289][e][vo/gpu-next/libplacebo] Failed parsing variable data: BT709
```

**Comment by haasn** [comment]
This is very hard to support for technical reasons (freeform strings do not fit into the `pl_hook_par` system very well, and also don't interact favorably with min/max values.

Given that we already map colorspace enums to numeric identifiers internally there may be a more elegant way to solve this.

**Comment by natural-harmonia-gropius** [comment]
```
//!PARAM x
//!TYPE enum
A
B
C
```

What about this? put all available items in content of parameter. `x: <0 | 1 | 2>`, default to 0.

**Comment by haasn** [comment]
That would be a clever solution, yes - from the PoV of the C API it would remain an int but gain a list of possible string identifiers

I'll see if I can throw up a quick branch

**Comment by haasn** [comment]
To clarify, you would prefer to have the actual enum text being set in the shader body, rather than the integer?

**Comment by haasn** [comment]
@natural-harmonia-gropius I threw up this MR: https://code.videolan.org/videolan/libplacebo/-/merge_requests/525

The syntax I settled on works like this:

```glsl
//!PARAM example
//!TYPE NAMED DEFINE
A
B
C
```

`A` will be the default value. For consistency and sanity, `example` will continue being an integer inside the shader, but the shader will have a preamble like this:

```glsl
#define example 0 // or whatever set by user
#define A 0
#define B 1
#define C 2
// rest of shader
```

That way you can continue doing checks like `#if example == B`, it will just translate to `example == 2` under the hood. Note that `NAMED` also works for non-defines:

```glsl
//!PARAM thing
//!TYPE NAMED DYNAMIC INT
FOO
BAR
```

This will introduce a named dynamic integer, which you can still test for inside code (e.g. `if (thing == BAR)`).

Finally, as a little bit of extra convenience, you can use the names also inside rpm exprs (e.g. `//!WHEN example FOO =`)

**Comment by natural-harmonia-gropius** [comment]
> To clarify, you would prefer to have the actual enum text being set in the shader body, rather than the integer?

https://code.videolan.org/videolan/libplacebo/-/merge_requests/525/diffs#475fc87674b4dac64e49b76cd6dced6c4218bf55_536_544
LGTM.

> Only thing I haven't settled on (ironically) is the name. Maybe it should be ENUM instead of NAMED, because it also implies various other enum semantics (integer type, minimum/maximum ignored, ...)

I prefer `ENUM`.

Last question, `glsl-shader-opts example=A` will works, right?

**Comment by haasn** [comment]
> Last question, glsl-shader-opts example=A will works, right?

That requires separate support in mpv.
