### ISSUE TITLE
HDR contrast recovery glitching 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#12091]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I am confused as when I set the —hdr-contrast- recovery no matter what I set it too I seem to be getting some weird glitching on the screen as faint outlines of what is happening in the picture when tonemapping hdr to sdr this is my config 

tone-mapping=bt.2446a
target-contrast=1000
target-peak=110
hdr-contrast-recovery=0.5
hdr-compute-peak=auto
vo=gpu-next
gpu-api=OpenGL
gpu-context=android 
gamut-mode=perceptual
tonemapping-Param=2.0

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by kasper93** [comment]
> Hi there I am confused as when I set the —hdr-contrast- recovery no matter what I set it too I seem to be getting some weird glitching on the screen as faint outlines of what is happening in the picture when tonemapping hdr to sdr this is my config

This should be fixed by https://github.com/haasn/libplacebo/commit/f1fbbf001838e8a5848fcd8311ce97e4048e8d04 please update your libplacebo/mpv to version that includes this fix.
