### ISSUE TITLE
Scaler not loading (trailing unused argument)

### ISSUE THREAD

**Issue by Zabooby** [mpv-player/mpv#12090]
### Reproduction steps

`# change-list glsl-shaders toggle ~~/shaders/ravu_Z_ar_r3.hook ; no-osd set set cscale-antiring 0 ; set dscale-antiring 0 ; set cscale-antiring 0 #! Video > Shaders > Neural Scaler > Ravu Zoom ar r3`

I have the above in my `input.conf`, what I'm trying to achieve is that when I click on the ravu scaler in my [uosc ](https://github.com/tomasklaen/uosc) menu it will first set mpv's anti-ringing filters to 0. 

### Expected behavior

The ravu scaler should load with mpv's anti-ringing filters set to 0. 

### Actual behavior

I get a trailing unused argument error in the console and the scaler doesn't load. 

![image](https://github.com/mpv-player/mpv/assets/78969986/49abadb4-6b1f-480e-b925-778e4287f006)

**Comment by natural-harmonia-gropius** [comment]
> no-osd set set cscale-antiring 0

dup set

**Comment by Zabooby** [comment]
> > no-osd set set cscale-antiring 0
> 
> dup set

Damn I'm actually blind, thanks for the quick answer!
