### ISSUE TITLE
`vo=gpu-next`: GPU screenshots of videos with non-square pixels are being captured in 1:1 PAR

### ISSUE THREAD

**Issue by dokur0chan** [mpv-player/mpv#12108]
### Important Information
```
mpv v0.36.0-59-gf6de44dd Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Aug  7 2023 00:24:39
libplacebo version: v6.292.0-131-ga09b834-dirty
FFmpeg version: N-111700-g6b82f3504
FFmpeg library versions:
   libavutil       58.14.100
   libavcodec      60.22.100
   libavformat     60.10.100
   libswscale      7.3.100
   libavfilter     9.10.100
   libswresample   4.11.100
```
- Windows 11 Version 10.0.22621 Build 22621
- [mpv-x86_64-v3-20230807-git-f6de44d](https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230807/mpv-x86_64-v3-20230807-git-f6de44d.7z)
### Reproduction steps

1. Acquire a source that renders with non-square pixels, such as an [anamorphic DVD](https://en.wikipedia.org/wiki/Anamorphic_widescreen)
2. Capture a screenshot using  `--no-config --vo=gpu-next`
3. Capture a screenshot using `--no-config --vo=gpu-next --screenshot-sw=yes`
4. Capture a screenshot using `--no-config --vo=gpu`

### Expected behavior
GPU screenshots are captured in the appropriate DAR as specified by the source regardless of the chosen `vo`.

### Actual behavior
GPU screenshots are captured in 1:1 PAR in `gpu-next`.

-  `--no-config --vo=gpu-next`

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/139610756/9b0e02b9-dec3-494b-94d0-cb1eaaff4db2)

- `--no-config --vo=gpu-next --screenshot-sw=yes`

![mpv-shot0002](https://github.com/mpv-player/mpv/assets/139610756/d56ff931-9687-4b40-86fd-96c9dc7b3ad9)

- `--no-config --vo=gpu`

![mpv-shot0003](https://github.com/mpv-player/mpv/assets/139610756/42f90a6a-fe39-4a8c-bbc8-eb0cc5109c75)

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/12286741/mpv.log)

### Sample files
Can be provided if no one has a video source with non-square pixels.

**Comment by christoph-heinrich** [comment]
There has been a related commit not even an hour ago, can you try if that one fixes it? 983e8f0100b98bd8aed48e5fe86dd5682174b04e

**Comment by Dudemanguy** [comment]
I think you just missed my commit ;). This should be fixed.

**Comment by dokur0chan** [comment]
Whoops. Well this is embarrassing...

**Comment by dokur0chan** [comment]
@Dudemanguy 
https://github.com/mpv-player/mpv/commit/983e8f0100b98bd8aed48e5fe86dd5682174b04e seems to introduce a different kind of bug. Here's a sample file.

https://files.catbox.moe/s476if.mkv

**Comment by Dudemanguy** [comment]
Welp so my original test file didn't have a big enough change in dimensions and I didn't notice that the pixels were slightly off (now that i compare side by side; I can see they are). I've also discovered that gpu-next screenshots don't handle aspect ratio overrides at all either so that's possibly related.

**Comment by Dudemanguy** [comment]
Should actually be right now sorry about that.
