### ISSUE TITLE
mpv with libplacebo-v6.292.0 fails when used with vo=gpu and gpu-api=vulkan on wayland.

### ISSUE THREAD

**Issue by perfStack** [mpv-player/mpv#12103]
### Important Information

Provide following Information:
- mpv version : master-35a6b26b780af4befa4da06a63bebf95571d1279
- Linux Distribution and Version : Arch linux 6.4.8
- Source of the mpv binary : Self compiled from github
- If known which version of mpv introduced the problem : Not a regression
- Window Manager and version : plasmashell 5.27.7
- GPU driver and version : mesa 23.1.5
- Possible screenshot or video of visual glitches: na

Using mpv + libplacebo-v6.292.0 with --vo=gpu and --gpu-api=vulkan fails. libplacebo-v5.264.1 works fine.

### Reproduction steps

mpv --no-config --vo=gpu --gpu-api=vulkan --log-file=/dev/shm/$FILE Test_file.mkv

### Expected behavior

Should work with GPU context 'waylandvk'

### Actual behavior

Fails with both waylandvk and displayvk.
`[   0.092][f][cplayer] Error opening/initializing the selected video_out (--vo) device.`

### Log file
libplacebo-v5.264.1
[mpv_vulkan_libplacebov5.txt](https://github.com/mpv-player/mpv/files/12282476/mpv_vulkan_libplacebov5.txt)

libplacebo-v6.292.0
[mpv_vulkan_libplacebov6.txt](https://github.com/mpv-player/mpv/files/12282478/mpv_vulkan_libplacebov6.txt)

### Sample files

na

**Comment by haasn** [comment]
Can you test https://code.videolan.org/videolan/libplacebo/-/merge_requests/527 ?

I suspect something on your system may be broken though, the layer is clearly listed as supported a few lines above the supposed "layer not present" error message.

You can try running mpv through `VK_LOADER_DEBUG=all` to see where it's going wrong, hopefully.
