### ISSUE TITLE
DTS passthrough broken since commit "ad_spdif: fix segfault due to early deallocation"

### ISSUE THREAD

**Issue by mitzsch** [mpv-player/mpv#12102]
### Important Information

Provide following Information:
- mpv version: all versions after commit https://github.com/mpv-player/mpv/commit/4c3ed843dc8bde419d8c08565159a83cee9e3b9b are affected
- Windows Version: 10 (only platform tested)
- Source of the mpv binary: shinchiro / self compiled

### Reproduction steps / Explanation

Use a build with commit https://github.com/mpv-player/mpv/commit/4c3ed843dc8bde419d8c08565159a83cee9e3b9b applied. Try to pass through a file with a dts core track. The video will play but the receiver will not play any sound, as the dts core track is passthrough as a dts-hd track. When hitting i it says "format: spdif-dtshd" where it should only state "format: spdif-dts".
The log also shows `[ad] Failed to parse codec profile.` with the next line being `[ad] In: profile=-99 samplerate=0`. This `profile=-99` output means `"unknown"` and is interpreted by the ad_spdif.c logic as a dts-hd track and is therefore wrongly handled. 

Any build before that commit will pass through the dts core track just fine and will show `[ad] In: profile=20 samplerate=48000` in the logs. 

### Expected behavior

Pass through the dts (core) track correctly and show the correct `[ad] In: profile= samplerate=` parameters in the log 

### Actual behavior

Passing through the dts core track does not work and the log shows incorrect/unkown `[ad] In: profile= samplerate=` parameters.

### Log file

if needed I can provide it later

### Sample files

Any file with a dts core track will show the issue

**Comment by sfan5** [comment]
Oops, please test:
```diff
diff --git a/audio/decode/ad_spdif.c b/audio/decode/ad_spdif.c
--- a/audio/decode/ad_spdif.c
+++ b/audio/decode/ad_spdif.c
@@ -153,8 +153,7 @@ static int init_filter(struct mp_filter *da)
 {
     struct spdifContext *spdif_ctx = da->priv;
 
-    AVPacket *pkt = spdif_ctx->avpkt = av_packet_alloc();
-    MP_HANDLE_OOM(spdif_ctx->avpkt);
+    AVPacket *pkt = spdif_ctx->avpkt;
 
     int profile = FF_PROFILE_UNKNOWN;
     int c_rate = 0;
@@ -299,14 +298,18 @@ static void process(struct mp_filter *da)
     struct mp_aframe *out = NULL;
     double pts = mpkt->pts;
 
+    if (!spdif_ctx->avpkt) {
+        spdif_ctx->avpkt = av_packet_alloc();
+        MP_HANDLE_OOM(spdif_ctx->avpkt);
+    }
+    mp_set_av_packet(spdif_ctx->avpkt, mpkt, NULL);
+    spdif_ctx->avpkt->pts = spdif_ctx->avpkt->dts = 0;
     if (!spdif_ctx->lavf_ctx) {
         if (init_filter(da) < 0)
             goto done;
         assert(spdif_ctx->avpkt);
     }
 
-    mp_set_av_packet(spdif_ctx->avpkt, mpkt, NULL);
-    spdif_ctx->avpkt->pts = spdif_ctx->avpkt->dts = 0;
     spdif_ctx->out_buffer_len  = 0;
     int ret = av_write_frame(spdif_ctx->lavf_ctx, spdif_ctx->avpkt);
     avio_flush(spdif_ctx->lavf_ctx->pb);
```

**Comment by mitzsch** [comment]
I will test this and report back shortly! Thanks! :)

**Comment by mitzsch** [comment]
Works!
