### ISSUE TITLE
vo=gpu-next causes OSD to bug out in fullscreen, when video AR is smaller than 16:9

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12113]
### Important Information

Provide following Information:
- mpv version: v0.36.0 and git x86 64-v3 "20230806"
- Platform and Version: Windows 7 Build 7601 Service Pack 1
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/

### Reproduction steps
Open video or music. Go fullscreen with double click or hotkey.
When the video aspect ratio is smaller than 16:9 (when black bars are not hardcoded) the OSD bugs out.

### Expected behavior
OSD acts as usual, don't bug out, and disappear after 2 seconds. 

### Actual behavior
OSD bugs out, pulsates/flickers. OSD doesn't disappear after time, it displays all the time.

### Log file
edit: I updated the log file, it's very short now
[output.txt](https://github.com/mpv-player/mpv/files/12311589/output.txt)

### Sample files
Screenshot
![dfdf](https://github.com/mpv-player/mpv/assets/139760266/ae9d06c3-9307-4a0e-b732-13f3f93bc738)

**Comment by hooke007** [comment]
Off topic but I have to point out that
```
[   0.006][e][cplayer] C:/Program Files/MPV/portable_config/mpv.conf:55: setting option hdr-peak-percentile='10' failed.
```
If you want to try the latest feature of libplacebo, do not use the release version. Download git ones instead.

**Comment by geextahslex** [comment]
Okay, what is "git ones" and where do I grab it? I am a noob ^^
Oh and I know that this "hdr-peak-percentile" doesn't work, but I was trying everything out.

**Comment by hooke007** [comment]
https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/ or
https://github.com/shinchiro/mpv-winbuild-cmake/releases

**Comment by geextahslex** [comment]
Workaround:
Hide OSC/OSD items behind the video
osd-bar=no
script-opts=osc-barmargin=78

**Comment by Dudemanguy** [comment]
Is this also windows 7-specific like #12272?

**Comment by geextahslex** [comment]
Yes

**Comment by Dudemanguy** [comment]
Thanks, I suppose we'll close this one for the same reason.
