### ISSUE TITLE
X11 error: BadDrawable with hwdec=vaapi vo=opengl

### ISSUE THREAD

**Issue by kevmitch** [mpv-player/mpv#1211]
With 

    mpv/build/mpv --no-config --hwdec=vaapi --vo=opengl --msg-level=all=trace <h264file>

After hitting the "q" key, I get

    .
    .
    .
    Exiting... (Quit)
    [osc] Exiting...
    [ao/alsa] draining...
    [ao/alsa] uninit: pcm closed
    [input] release all
    [vo/opengl/x11] Enabling screensaver.
    [vo/opengl/x11] X11 error: BadDrawable (invalid Pixmap or Window parameter)
    [vo/opengl/x11] Type: 0, display: 0x7f1a9825d0f0, resourceid: 4a0000d, serial: 141
    [vo/opengl/x11] Error code: 9, request code: 9a, minor code: 4
    [vo/opengl/x11] uninit ...

Other than the error message, no ill behaviour occurs, so this is mostly an aesthetic issue.
The error disappears with "--hwdec=vaapi --vo=vaapi", "--hwdec=vaapi-copy --vo=opengl" and "--hwdec=no --vo=opengl" .

By hacking around with printfs and sleep(1) so as to be sure there isn't some timing fluke, I find that the error triggers right after the call at video/out/x11_common.c:1642:

    if (xss_suspend(mDisplay, !enabled))

If I add --no-stop-screensaver to the above command line I instead get

    .
    .
    .
    Exiting... (Quit)
    [osc] Exiting...
    [ao/alsa] draining...
    [ao/alsa] uninit: pcm closed
    [input] release all
    [vo/opengl/x11] X11 error: BadDrawable (invalid Pixmap or Window parameter)
    [vo/opengl/x11] Type: 0, display: 0x7feac825d0f0, resourceid: 4a0000d, serial: 11d
    [vo/opengl/x11] Error code: 9, request code: 9a, minor code: 4
    [vo/opengl/x11] uninit ...

Which is happening at video/out/x11_common.c:245 :

    XDefineCursor(x11->display, x11->window, 0);

**Comment by wm4** [comment]
We exchanged the vaapi OpenGL interop with a new implementation.
