### ISSUE TITLE
'watch-later-options' bugged and breaks 'save-position-on-quit'

### ISSUE THREAD

**Issue by pflanzenandi** [mpv-player/mpv#12128]
### mpv version and platform versions

`0.36.0`
`Flatpak`
`Debian Based Linux`

### Reproduction steps

`watch-later-options=fullscreen,volume,audio,sub` doesn't work and also breaks `save-position-on-quit=yes`.
These two config file entries worked in `0.35.0`.

### Expected behavior

Save above options and position on quit.

### Actual behavior

Nothing gets saved. No options, no position, although terminal outputs a saving state: 
`AV: 00:00:20 / 02:20:05 (0%) A-V:  0.000 Cache: 27s/48MB Saving state.`

Removing `watch-later-options=fullscreen,volume,audio,sub` makes `save-position-on-quit=yes` work properly.
One option at a time also doesn't work.

Noticed no files are getting created in `/home/me/.var/app/io.mpv.Mpv/config/mpv/watch_later` anymore, but in `/home/me/.var/app/io.mpv.Mpv/.local/state/mpv/watch_later`

### Log file

Upload meson-logs/meson-log.txt

No idea where to find.

**Comment by hooke007** [comment]
1. you didn't add `start` in `watch-later-options`
2. you didn't change some of those props

**Comment by pflanzenandi** [comment]
Cool, thank you! I never needed `start` before.
