### ISSUE TITLE
auto_profiles : property `vf` cannot be used in condition

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#12127]
### Important Information

Provide following Information:
- mpv version
git
- Platform and Version
win10 22H2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230809

### Reproduction steps

```
[test_pf]
 profile-cond = mp.get_property("vf"):find("flip")
 profile-restore = copy
 hue = 50
```

### Expected behavior

The profile will be used automatically when I run command `vf set vflip`

### Actual behavior

Hue never changed.

### Log file

[test.log](https://github.com/mpv-player/mpv/files/12314230/test.log)

**Comment by christoph-heinrich** [comment]
I got it working with `profile-cond = (function() for _, f in ipairs(vf) do if f.enabled ~= false and f.name == "vflip" then return true end end return false end)()`.
Apparently the condition doesn't get reevaluated on `vf` change when mp.get_property gets used.
`vf` or `get("vf")` returns a list of filters, each of which has a field `name` [among others](https://mpv.io/manual/master/#command-interface-vf).

**Comment by natural-harmonia-gropius** [comment]
`mp.get_property` return native type, evileval :p

**Comment by hooke007** [comment]
In Lua script, we could easily did it with observe function.
```lua
function check_vf()
	if mp.get_property("vf"):find("flip") then
		mp.commandv("set", "hue", "50")
	else
		mp.commandv("set", "hue", "0")
	end
end
mp.observe_property("vf", "native", check_vf)
```
I think it is also necessary for auto_profiles to have a simple magpic to simplify handing this.

**Comment by natural-harmonia-gropius** [comment]
try `mp.get_property("${vf}")`

**Comment by hooke007** [comment]
No help.

**Comment by guidocella** [comment]
`profile-cond=vf and mp.get_property("vf"):find("flip")`

**Comment by hooke007** [comment]
mpv doesn't provide the prop that if a filter is actually being uesd (i.e. flip doesn't work with d3d11va native). So do the shaders.
I accept this solution.
