### ISSUE TITLE
dscale, ortho(vert) downscaling, then ortho(horiz) upscaling

### ISSUE THREAD

**Issue by yeezylife** [mpv-player/mpv#12122]
### Important Information

Provide following Information:
- mpv version: shinchiro's latest weekly build([mpv-x86_64-v3-20230806-git-6729285.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20230806-git-6729285.7z/download))
- Windows Version: Windows 11 stable
- Source of the mpv binary: [mpv-x86_64-v3-20230806-git-6729285.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20230806-git-6729285.7z/download)
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches
![mpv-shot0001](https://github.com/mpv-player/mpv/assets/30175425/206e93c6-4a48-4530-9fd8-6d4233211599)

![mpv-shot0002](https://github.com/mpv-player/mpv/assets/30175425/061396b3-2550-4647-ab99-4c726453bcad)

### Reproduction steps

no-config
vo=gpu-next
gpu-api=d3d11
fs
dscale=catmull_rom
glsl-shaders="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
log-file=output.txt

### Expected behavior
I'm testing this dvdrip(720x576) on a 1080p laptop
I was hoping shift+i  2, the downscale lines will look like this:

ortho(vert) downscaling catmull_rom
ortho(horiz) downscaling catmull_rom

since FSRCNNX doubled it to 1440x1152

### Actual behavior
But weirdly the downscaling seems to behave differently, it shows
ortho(vert) downscaling catmull_rom
ortho(horiz) "upscaling" catmull_rom

This seems only happen with this particular file.

### Log file
https://[pastebin.com/raw/HCpGee8x](https://pastebin.com/raw/HCpGee8x)

### Sample files
[Spring.in.a.Small.Town.DVDRip.x264.AC3-PTer.zip](https://github.com/mpv-player/mpv/files/12308786/Spring.in.a.Small.Town.DVDRip.x264.AC3-PTer.zip)

(Only 800kb 5 seconds)

**Comment by hooke007** [comment]
scaled res: 1471(>1440)x1080(<1152)

**Comment by po5** [comment]
You're playing an anamorphic video, as can be seen in your 2nd screenshot. The effective resolution is 1471x1080, not 1440x1080.  
That other file isn't anamorphic, not sure what's that's supposed to show. Both display fine, and the info display is accurate.

**Comment by po5** [comment]
As you correctly identified, FSRCNNX will double to 1440x1152 which means we need to upscale horizontally and downscale vertically to reach 1471x1080, matching the info.  
The square pixel resolution without additional scaling is 785x576, as can be seen by taking a screenshot (on git master). Matches the final AR.
