### ISSUE TITLE
Error when ytdl_hook switches to ffmpeg

### ISSUE THREAD

**Issue by tunaflsh** [mpv-player/mpv#12121]
### Important Information

Provide following Information:
- mpv version **v0.36.0-50-g67292855**
- Platform and Version **Windows 11**
- Source of the mpv binary [`mingw64/mingw-w64-x86_64-mpv`](https://packages.msys2.org/package/mingw-w64-x86_64-mpv?repo=mingw64) or [Windows builds by shinchiro](https://sourceforge.net/projects/mpv-player-windows/files/)

### Reproduction steps

1. Install [`yt-dlp`](https://github.com/yt-dlp/yt-dlp) if you haven't.
2. Create `.netrc` file
```shell
touch .netrc
```
3. Put [HiDive](https://www.hidive.com/) credentials into the `.netrc` file: `machine hidive login <username> password <password>`
Note: yt-dlp/yt-dlp#6493
4. Run `mpv` from the same folder as `.netrc`
```shell
mpv --no-config --log-file=mpv.log --ytdl-raw-options=ignore-config=,netrc=,netrc-location=.netrc "https://www.hidi
ve.com/stream/oshi-no-ko/s01e001"
```

### Expected behavior

Same behavior as loading from non-premium content.
```shell
mpv --no-config "https://www.hidive.com/stream/oshi-no-ko"
```

Or download the video
```shell
yt-dlp --ignore-config --test --output "video.mp4" --netrc --netrc-location .netrc "https://www.hidive.com/stream/oshi-no-ko/s01e001"
```
and load the file.
```shell
mpv --no-config "video.mp4"
```

Both work fine.

### Actual behavior

```shell
Exiting... (Errors when loading file)
```
From the logs it seems like `ytdl_hook` switches to `ffmpeg` at some point and then it receives `HTTP error 404 Not Found` when trying to open the m3u8 file.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/12308539/mpv.log)

### Sample files

No sample files, since the problem is with `ytdl` hook.

**Comment by Tama47** [comment]
I think you should change the title because this issue is related to the ytdl_hook switching to ffmpeg in mpv, rather than not being able to Stream Premium Content from HiDive with yt-dlp. https://github.com/yt-dlp/yt-dlp/issues/8019#issuecomment-1732696992

**Comment by Dudemanguy** [comment]
I can't verify myself, but the ytdl_hook does parse cookies now so I *think* this should work. If not, feel free to reopen.
