### ISSUE TITLE
New buffering/caching system is completely broken

### ISSUE THREAD

**Issue by nick-s-b** [mpv-player/mpv#12137]
### Important Information

Provide following Information:
````
mpv v0.36.0-78-g13c6e060e2 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Aug 11 2023 09:38:32
libplacebo version: v5.264.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
````
- Window Manager and version
i3-wm 4.22-4
- GPU driver and version
 NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2   

### Reproduction steps

Open a large file, say an hour long movie, and then try to scrub through it by holding the arrow keys to skip ahead. Very quickly, mpv will choke and stop rendering frames. It will just freeze.

Even opening a 4K Youtube stream (with yt-dlp installed) will stop playing after a while and you have to quit the mpv and restart the video.

### Expected behavior
Don't choke. Don't freeze when playing files!
And it's nto my computer or the CPU or my memory. I have plenty of RAM. Something has recently changed with mpv's caching and it's now complete trash and totally unstable.

### Actual behavior
It freezes.

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/issues/12076

**Comment by nick-s-b** [comment]
@guidocella thank you. I will close the issue and sub to the other one.
