### ISSUE TITLE
mpv core dumps when you try to change the aspect ratio

### ISSUE THREAD

**Issue by nick-s-b** [mpv-player/mpv#12138]
### Important Information

Provide following Information:
````
mpv v0.36.0-78-g13c6e060e2 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Aug 11 2023 09:38:32
libplacebo version: v5.264.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
````
- Window Manager and version
i3-wm 4.22-4
- GPU driver and version
 NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2   

### Reproduction steps

Open a video file. Hit the "A" key to change the aspect ratio (assuming you have it enabled in input.conf).
````
....
cplayer: Set property: video-aspect-override=16:9 -> 1
*** stack smashing detected ***: terminated
[1]    565168 IOT instruction (core dumped)  mpv -v '/tmp/video_2023-08-11_05-18-09.mp4'
````
Is this change the cause?
https://github.com/mpv-player/mpv/commit/1df0a42a8cb12005311f6a03f3a1c4329c798f8c

### Expected behavior
Don's crash please.

### Actual behavior
It crashes. Hard.

**Comment by sfan5** [comment]
see #12136
