### ISSUE TITLE
some mp4 file with incorrect duration value

### ISSUE THREAD

**Issue by crazyevent** [mpv-player/mpv#12133]
### Important Information

Provide following Information:
- latest
- latest
- latest
![image](https://github.com/mpv-player/mpv/assets/7711704/251b33cf-4e37-40ff-affe-8b10fc496e69)

the real duration is 6 seconds

![image](https://github.com/mpv-player/mpv/assets/7711704/471746eb-532c-48cd-9270-a8e0debd7ae6)

could we compat with such media files?

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by sfan5** [comment]
The duration shows incorrectly in `ffprobe` (your screenshot) so the proper place to raise your bug is with ffmpeg.
It's also possible that the file is just broken.
