### ISSUE TITLE
HDR tonemapping lines in sky 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#12148]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I am doing hdr to sdr tonemapping however I’m some bright parts such as the sky I can see lines on the screen is there anything I can do to fix this my config is below
Vo=gpu-next
HDR-compute-peak=yes
tone-mapping=spline
Gamut mapping=perceptual
target contrast =1500
target peak=400

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by sfan5** [comment]
Do not open bug reports using the 'question' template
