### ISSUE TITLE
User script shorten path to mpv

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12147]
The same way I can use `~~/` in `mpv.conf`
I would like to use the exact same path with a lua script instead of using `C:\\Users\\root\\AppData\\Roaming\\mpv\\`

**Comment by guidocella** [comment]
Use the `expand-path` command.

**Comment by guidocella** [comment]
You need to call `mp.command_native` once for `subprocess` and once for `expand-path`.

**Comment by guidocella** [comment]
You're not doing anything with the return value of `mp.command_native({"expand-path", "~~/"})`. You need to use it as `args`.

**Comment by guidocella** [comment]
`mp.command_native({name = 'subprocess',args = { mp.command_native({"expand-path", "~~/Test.exe"})} })`
