### ISSUE TITLE
mpv takes seconds to open when file contains audio since hardware swap

### ISSUE THREAD

**Issue by FelixKainz** [mpv-player/mpv#12145]
### Important Information

Provide following Information:
- mpv version
`mpv-x86_64-v3-20230806-git-6729285`
- Windows Version
Windows 11 22H2 Build 22621.2134
- Source of the mpv binary
shinchiro
- If known which version of mpv introduced the problem
Not a regression, even `mpv-x86_64-20200105-git-9eb3991` shows same behavior.
The issue appeared after moving to a new PC with the same hard drive and thus windows installation. The output device used here is connected by USB and did not change during that move.

The same behavior appears with non-v3 and 32-bit editions.
- Possible screenshot or video of visual glitches
Not useful in this case.

### Reproduction steps

Play any media file that contains audio, whether a video+audio or audio only file, also with --no-audio-display.

### Expected behavior
MPV opens more or less immediately as it used to and as it does for video-only files.

### Actual behavior
MPV takes multiple seconds to open, which is annoying when going through multiple smaller media files.

### Log file

[webm_opus_wasapi_hardcoded_device.txt](https://github.com/mpv-player/mpv/files/12328404/webm_opus_wasapi_hardcoded_device.txt)
Trying to open an **audio only file** with a **given audio device**: `4 seconds`
[webm_opus_wasapi_hardcoded_device_audio_with_video.txt](https://github.com/mpv-player/mpv/files/12328405/webm_opus_openal_hardcoded_device_audio_with_video.txt)
Trying to open a **video+audio file** with a **given audio device** but with **openal driver**: `4 seconds`
[webm_opus_openal_auto_device_audio_with_video.txt](https://github.com/mpv-player/mpv/files/12328406/webm_opus_openal_auto_device_audio_with_video.txt)
Trying to open a **video+audio file** without given audio device **with openal driver**: `4 seconds`
[webm_opus_openal_auto_device_audio.txt](https://github.com/mpv-player/mpv/files/12328407/webm_opus_openal_auto_device_audio.txt)
Trying to open an **audio only file** with auto output device and **openal driver**: `instantly`
[webm_opus_wasapi_auto_device_audio.txt](https://github.com/mpv-player/mpv/files/12328408/webm_opus_wasapi_auto_device_audio.txt)
Trying to open an **audio only file** with auto output device and **wasapi driver**: `4 seconds`
[mp3_wasapi_auto_device_audio.txt](https://github.com/mpv-player/mpv/files/12328409/mp3_wasapi_auto_device_audio.txt)
Trying to open an **audio only file** with auto output device and **wasapi driver**: `4 seconds`
[video_only_file.txt](https://github.com/mpv-player/mpv/files/12328428/video_only_file.txt)
Trying to open a **video only file**: `instantly`
There seems to be some issue with wasapi but it is not the only one since just switching to openal does not always help.
I don't get it.

The audio device I hardcoded here is the same the `auto` value chooses. It was just an attempt to see if picking the best output device was the cause of the slowdown.

### Sample files

Can be provided if needed, but the audio only files are copyrighted, so cannot post publicly.

**Comment by kasper93** [comment]
From mpv point of view there is nothing we can fix here. It hangs when creating `IMMDeviceEnumerator`, and the significant delay would suggest something in your system is bad. I would suggest disconnecting DAC, removing audio device and its driver, and connecting it again to install device again. If this doesn't help try looking at https://learn.microsoft.com/en-us/sysinternals/downloads/procmon might give more insight where exactly it is hanging.

Related code that apparently takes 4s:
https://github.com/mpv-player/mpv/blob/598e30173d4a6b6414b010647e97809729224374/audio/out/ao_wasapi_utils.c#L833-L836

**Comment by FelixKainz** [comment]
Hi Kasper, thanks for the swift reply.

I forgot to mention that I already tried to disable all audio output devices in Device Manager but the delay did not change. But I can try to physically disconnect everything but what I want the output to be.
I'll also try to reinstall the drivers.

You quoted a WASAPI specific code snippet, but as you can see by the logs above, the delay also appears with --ao=openal. Doesn't that mean the the issue comes from something upstream of the driver? That tells me that nothing WASAPI or OpenAL specific is causing the issue.

**Comment by kasper93** [comment]
> You quoted a WASAPI specific code snippet, but as you can see by the logs above, the delay also appears with --ao=openal. 

I quoted it for simplicity, it is probably exact same or similar thing. We are waiting for device. Bottom line is I don't see mpv at fault here. I'd like to help, but for this one, you needs to investigate yourself.

Also `webm_opus_openal_hardcoded_device_audio_with_video.txt` is mislabeled, it's not openal.

**Comment by FelixKainz** [comment]
> Also webm_opus_openal_hardcoded_device_audio_with_video.txt is mislabeled, it's not openal.
Sorry, corrected it.

Intersting thing though is that PotPlayer, which is also setup to use that device with WASAPI is opening quickly as well. I'll debug further. Thank for your help!

**Comment by FelixKainz** [comment]
> [webm_opus_openal_auto_device_audio.txt](https://github.com/mpv-player/mpv/files/12328407/webm_opus_openal_auto_device_audio.txt)

Do you have a guess why this one scenario works instantly? If the device enumeration is to blame it should also show here I guess.

**Comment by FelixKainz** [comment]
Solved!
I ran an ASUS driver installer once and it installed lots of bloatware >:|
It also installed something called `A-Volute Sonic Studio 3` and once I found out [how to uninstall it](https://rog-forum.asus.com/t5/intel-700-600-series/remove-sonic/td-p/903279/page/2) MPV opens nearly instantanious now!
`238 ms` to be exact: [fast.txt](https://github.com/mpv-player/mpv/files/12345906/fast.txt)

**Comment by FelixKainz** [comment]
Thanks for the help @kasper93!
