### ISSUE TITLE
Using hwdec causes videos to become unplayable on Windows

### ISSUE THREAD

**Issue by xd003** [mpv-player/mpv#12154]
### Important Information

- mpv version - v0.36.0-88-g598e3017
- Windows 11 Pro
- Source of the mpv binary - https://sourceforge.net/projects/mpv-player-windows/files
- If known which version of mpv introduced the problem - Not Known

### Reproduction steps
Using ```hwdec=auto``` or ```hwdec=auto-safe``` ( i haven't tried with other values ) causes the video to get stuck at the same frame after only few seconds of playback, Nothing responds at this point, i have to manually kill mpv from task manager. When i am not using hwdec flag, everything seems to work correctly.

Edit - I tested playing the video on my other laptop
• very same video
• very same mpv release 
• very same windows 11 pro OS
• very same graphics driver ( downloaded from [here](https://www.intel.com/content/www/us/en/download/762755/intel-6th-10th-gen-processor-graphics-windows.html), intel provides common driver for both )

It seems to be working perfectly there with hwdec flag enabled

Specification of Laptop where its working -
CPU - Intel Celeron N3350
GPU - Intel HD Graphics 500

Specification of Laptop wherein the aforementioned issue is happening -
CPU - Intel Core i3-6006U
GPU - Intel HD Graphics 520

### Log file
https://pastes.io/raw/r24hdsvinv

**Comment by xd003** [comment]
> It is recommended to use the latest git master version to reproduce this issue, your version is a bit old

Thanks for the heads up, i have reproduced the issue using the latest git master and updated the same in my post

**Comment by amariami** [comment]
> Using hwdec=auto or hwdec=auto-safe ( i haven't tried with other values )
#--vo=gpu
--vo=gpu-next 
--gpu-api=d3d11 
--hwdec=d3d11va-copy

**Comment by xd003** [comment]
@amariami 
Thanks,i tried with your suggested flags, the video playback no longer gets stuck/crash but i think hardware decoding is not really working because when i checked the gpu section in task manager, only the 3D part was active but Video Decode was always at 0. In my other laptop, both of these are actively used when a video is playing

**Comment by xd003** [comment]
> ```
> --vo=gpu-next
> --gpu-api=d3d11
> --hwdec=d3d11va
> ```
> 
> If this works then it's a problem with vo_gpu, nowadays on Windows everyone uses gpu-next.

It doesn't make mpv stuck or crash at same frame but while video is playing, the video decoder option in gpu section always stays at 0 in task manager. Log - https://pastes.io/raw/i4q4l9yyp3

On another note, i didnt quite understood how to implement your suggestion about changing show engine

**Comment by xd003** [comment]
> your logs indicate that hardware decoding is being used. Perhaps there is a problem with your driver not reporting usage correctly in taskmgr

Thanks for confirmation, i will try playback of some higher end videos to see how my system fares to eliminate any chance of it using software decoding just in case 

Also , would you recommend using the following on all my window machines ? Currently i just have ```vo=gpu``` & ```hwdec=auto-safe``` in other systems where this particular issue didn't happened 
```
--vo=gpu-next
--gpu-api=d3d11
--hwdec=d3d11va
```

**Comment by xd003** [comment]
@arm64-v9a sorry for testing it in bit of a hurry earlier, after some extensive testing, i can confirm that with ```--vo=gpu-next``` & ```gpu-api=d3d11```, if i use ```--hwdec=d3d11va```, the video gets stuck at same frame within 15-20 seconds. There's no issue while using ```--hwdec=d3d11va-copy``` along with those other 2 flags. Any clue what might be causing this weird behaviour ?
Logs - 
[d3d11va](https://pastes.io/raw/nhborzfgaq) 
[d3d11va-copy](https://pastes.io/raw/fmqopjc1uy)

**Comment by xd003** [comment]
Yeah i too couldn't find anything abnormal, maybe a separate issue needs to be opened that mpv is getting stuck but nothing showing up in logs

**Comment by FinnRaze** [comment]
Intel graphics before kaby lake don't support hevc(especially hevc 10bit) well.
https://mpv.io/manual/stable/#options-hwdec
`certain combinations of HEVC and Intel chips on Windows tend to cause mpv to crash, most likely due to driver bugs.`
Same issue on haswell/broadwell/skylake graphics,such as hd4600 hd5500.

**Comment by FinnRaze** [comment]
Some of my discovery on these chips:
dxva2 can work ,but there is color issue

> dxva2 is not safe

`-copy` APIs can work too,but on most situation it comsumes CPU as much as software decoding.
On Win8.1 ,d3d11va can work,but it's still possible to cause mpv crash(much better than on Win10)

**Comment by xd003** [comment]
> Intel graphics before kaby lake don't support hevc(especially hevc 10bit) well. https://mpv.io/manual/stable/#options-hwdec
> > certain combinations of HEVC and Intel chips on Windows tend to cause mpv to crash, most likely due to driver bugs.

Does this apply to certain intel graphic igpu's only and not necessarily all of them before kaby lake ?
i am asking because this issue is happening on Intel graphics 520 but everything seems to be working perfectly fine on intel graphics 500

**Comment by FinnRaze** [comment]
N3350 was launched at the same time with other kabylake chips(i5 7200u for example),maybe there is some improvement.

**Comment by Dudemanguy** [comment]
Seems to just be a driver/hardware issue. Nothing we can really do about that.
