### ISSUE TITLE
gpu-next: CHROMA_SCALED stage apparently not hookable 

### ISSUE THREAD

**Issue by Artoriuz** [mpv-player/mpv#12153]
### Important Information

- mpv version: mpv v0.36.0-88-g598e3017
- Platform and Version: Windows 11 22621.2134
- Source of the mpv binary: Shinchiro

### Reproduction steps

Attempt to execute a shader that hooks into CHROMA_SCALED while using `--vo=gpu-next`. Choice of shader doesn't seem to matter, but I've used this to test: [meme.txt](https://github.com/mpv-player/mpv/files/12330082/meme.txt)

### Expected behavior

With the provided shader, chroma should be inverted if it has been scaled (this screenshot was taken on `vo=gpu`):
![mpv-shot0001](https://github.com/mpv-player/mpv/assets/12078193/a9b37154-a847-464b-afce-8e73393a8fae)

### Actual behavior

Chroma isn't inverted on `gpu-next`:
![mpv-shot0002](https://github.com/mpv-player/mpv/assets/12078193/3ce65908-3bb1-406f-9bad-3923763d4c43)

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/12330092/log.txt)

### Sample files

Anything with chroma subsampling should suffice, and again this was the shader used to confirm the issue: [meme.txt](https://github.com/mpv-player/mpv/files/12330082/meme.txt)

**Comment by llyyr** [comment]
There's also no pass_hook for PL_HOOK_ALPHA_SCALED in libplacebo, along with this

**Comment by haasn** [comment]
Can you test https://code.videolan.org/videolan/libplacebo/-/merge_requests/539 ?
