### ISSUE TITLE
ios-gl hardware acceleration feature cannot be enabled with meson build system

### ISSUE THREAD

**Issue by kasimok** [mpv-player/mpv#12161]
### mpv version and platform versions
MPV Version: mpv-v0.36.0(latest release)
compiler machine: macOS version: 13.4.1 
target OS: iOS 
### Reproduction steps
I'm trying to use the meson build system to build libmpv for iOS.

In the root directory of mpv, I executed 
`/opt/homebrew/bin/meson setup /Users/0x67/Documents/projects/FFmpegKit/.Script/mpv/ios/scratch/arm64 --cross-file=/Users/0x67/Documents/projects/FFmpegKit/.Script/mpv/ios/scratch/arm64/crossFile.meson -Dcplayer=false -Dlibmpv=true -Dlua=disabled -Djavascript=disabled -Dios-gl=enabled -Dcoreaudio=disabled -Daudiounit=disabled -Dmacos-media-player=disabled -Dmanpage-build=disabled -Dswift-build=disabled -Dvapoursynth=disabled`

by the way, all the shell environment variables are correctly set:

```
export CFLAGS="-arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk -target arm64-apple-ios13.0 -mios-version-min=13.0 -fno-common -I/Users/0x67/Documents/projects/FFmpegKit/.Script/gmp/ios/thin/arm64/include"
export PKG_CONFIG_PATH="/Users/0x67/Documents/projects/FFmpegKit/.Script/libfreetype/ios/thin/arm64/lib/pkgconfig:/Users/0x67/Documents/projects/FFmpegKit/.Script/libfribidi/ios/thin/arm64/lib/pkgconfig:/Users/0x67/Documents/projects/FFmpegKit/.Script/libass/ios/thin/arm64/lib/pkgconfig:/Users/0x67/Documents/projects/FFmpegKit/.Script/gnutls/ios/thin/arm64/lib/pkgconfig:/Users/0x67/Documents/projects/FFmpegKit/.Script/gmp/ios/thin/arm64/lib/pkgconfig:/Users/0x67/Documents/projects/FFmpegKit/.Script/FFmpeg/ios/thin/arm64/lib/pkgconfig:/Users/0x67/Documents/projects/FFmpegKit/.Script/nettle/ios/thin/arm64/lib/pkgconfig:/Users/0x67/Documents/projects/FFmpegKit/.Script/harfbuzz/ios/thin/arm64/lib/pkgconfig:/Users/0x67/Documents/projects/FFmpegKit/.Script/png/ios/thin/arm64/lib/pkgconfig:"
export LDFLAGS="-arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk -target arm64-apple-ios13.0 -L/Users/0x67/Documents/projects/FFmpegKit/.Script/gmp/ios/thin/arm64/lib"
export CPPFLAGS="-arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk -target arm64-apple-ios13.0 -mios-version-min=13.0 -fno-common -I/Users/0x67/Documents/projects/FFmpegKit/.Script/gmp/ios/thin/arm64/include"
export PATH="/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/opt/bison/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export CXX="/usr/bin/clang++"
export CXXFLAGS="-arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk -target arm64-apple-ios13.0 -mios-version-min=13.0 -fno-common -I/Users/0x67/Documents/projects/FFmpegKit/.Script/gmp/ios/thin/arm64/include"
export CC="/usr/bin/clang"
export OBJC="/usr/bin/clang"
export LC_CTYPE="C"
```
### Expected behavior

the meson setup command succeeds

### Actual behavior

`meson.build:1752:9: ERROR: No host machine compiler for 'video/out/opengl/hwdec_ios.m'`

I think the meson build system does not know how to build an object-c file. I checked the `meson.build`. It specifies standard c as the compiler

```
project('mpv',
        'c',
        license: ['GPL2+', 'LGPL2.1+'],
        version: files('./VERSION'),
        meson_version: '>=0.62.0',
        default_options: [
            'buildtype=debugoptimized',
            'b_lundef=false',
            'c_std=c11',
            'warning_level=1',
        ]
)

```
I'm new to the meson build system. Please help!
### Log file

[meson-log.txt](https://github.com/mpv-player/mpv/files/12332950/meson-log.txt)

**Comment by Dudemanguy** [comment]
>-Dswift-build=disabled 

I'm pretty sure this is wrong. You always have to use swift if you want to build for any mac-thing. Meson does try to add obj-c as a language but it won't if you disable that option.

**Comment by Akemi** [comment]
> > -Dswift-build=disabled
> 
> I'm pretty sure this is wrong. You always have to use swift if you want to build for any mac-thing. Meson does try to add obj-c as a language but it won't if you disable that option.

you don't. you just won't get some optional feature and cocoa-cb is not working. swift ist completely irrelevant for iOS atm.

**Comment by kasimok** [comment]
> > -Dswift-build=disabled
> 
> I'm pretty sure this is wrong. You always have to use swift if you want to build for any mac-thing. Meson does try to add obj-c as a language but it won't if you disable that option.

@Dudemanguy I'm Building on M1 Mac targeting iOS platform. My macOS version of MPV compiles successfully with MPV. The issue here I guess it meson does not know how to compile objective c files for iOS.

**Comment by Dudemanguy** [comment]
Could you post the meson configure log with that applied? It should have found the found the macos_sdk_version and all that.

**Comment by kasimok** [comment]
> Could you post the meson configure log with that applied? It should have found the found the macos_sdk_version and all that.

meson setup failed
[meson-log.txt](https://github.com/mpv-player/mpv/files/12340333/meson-log.txt)

**Comment by Dudemanguy** [comment]
>Program /Users/0x67/Documents/projects/FFmpegKit/.Script/mpv-v0.36.0/TOOLS/macos-sdk-version.py skipped: feature swift-build disabled

I think something went wrong with applying that patch? It removed the swift-build requirement on that check as you can see so this shouldn't have happened.

**Comment by kasimok** [comment]
> > Program /Users/0x67/Documents/projects/FFmpegKit/.Script/mpv-v0.36.0/TOOLS/macos-sdk-version.py skipped: feature swift-build disabled
> 
> I think something went wrong with applying that patch? It removed the swift-build requirement on that check as you can see so this shouldn't have happened.


Sorry, I checked my wrapper script, enabled swift-build this time: 
[meson-log.txt](https://github.com/mpv-player/mpv/files/12340438/meson-log.txt)

 ERROR: Command cannot have '@INPUT@', since no input files were specified

**Comment by Dudemanguy** [comment]
Hmm, I think that that is from the swift compile command. Not sure why it's saying no input files though. Could you run it again but with `-Dswift-build=disabled`?

**Comment by Dudemanguy** [comment]
@kasimok: okay I think I see what the problem is hopefully. If you could clear all previous patch completely and instead try this one.
```
diff --git a/meson.build b/meson.build
index cbeec06d64..f8fd261cce 100644
--- a/meson.build
+++ b/meson.build
@@ -1487,11 +1487,15 @@ endif
 
 
 # macOS features
-macos_sdk_version_py = find_program(join_paths(source_root, 'TOOLS', 'macos-sdk-version.py'),
-                                    required: get_option('swift-build').require(darwin))
+macos_sdk_version_py = ''
+if darwin
+    macos_sdk_version_py = find_program(join_paths(source_root, 'TOOLS', 'macos-sdk-version.py'),
+                                                   required: true)
+endif
+
 macos_sdk_path = ''
 macos_sdk_version = '0.0'
-if macos_sdk_version_py.found()
+if darwin and macos_sdk_version_py.found()
     macos_sdk_info = run_command(macos_sdk_version_py, check: true).stdout().split(',')
     macos_sdk_path = macos_sdk_info[0].strip()
     macos_sdk_version = macos_sdk_info[1]
@@ -1577,7 +1581,7 @@ if features['macos-media-player']
     swift_sources += files('osdep/macos/remote_command_center.swift')
 endif
 
-if swift.allowed()
+if swift.allowed() and swift_sources.length() > 0
     subdir('osdep')
 endif 
```
It should hopefully build with both `-Dswift-build=disabled` and `-Dswift-build=enabled`.

**Comment by kasimok** [comment]
> @kasimok: okay I think I see what the problem is hopefully. If you could clear the previous patch completely and instead try this one.
> 
> ```
> diff --git a/meson.build b/meson.build
> index cbeec06d64..f8fd261cce 100644
> --- a/meson.build
> +++ b/meson.build
> @@ -1487,11 +1487,15 @@ endif
>  
>  
>  # macOS features
> -macos_sdk_version_py = find_program(join_paths(source_root, 'TOOLS', 'macos-sdk-version.py'),
> -                                    required: get_option('swift-build').require(darwin))
> +macos_sdk_version_py = ''
> +if darwin
> +    macos_sdk_version_py = find_program(join_paths(source_root, 'TOOLS', 'macos-sdk-version.py'),
> +                                                   required: true)
> +endif
> +
>  macos_sdk_path = ''
>  macos_sdk_version = '0.0'
> -if macos_sdk_version_py.found()
> +if darwin and macos_sdk_version_py.found()
>      macos_sdk_info = run_command(macos_sdk_version_py, check: true).stdout().split(',')
>      macos_sdk_path = macos_sdk_info[0].strip()
>      macos_sdk_version = macos_sdk_info[1]
> @@ -1577,7 +1581,7 @@ if features['macos-media-player']
>      swift_sources += files('osdep/macos/remote_command_center.swift')
>  endif
>  
> -if swift.allowed()
> +if swift.allowed() and swift_sources.length() > 0
>      subdir('osdep')
>  endif 
> ```
> 
> It should hopefully build with both `-Dswift-build=disabled` and `-Dswift-build=enabled`.

@Dudemanguy , I know the root cause for this bug, I'll create a PR and refer this case later
