### ISSUE TITLE
Restore default behavior for term-remaining-playtime option

### ISSUE THREAD

**Issue by DanOscarsson** [mpv-player/mpv#12167]
### Important Information

Provide following Information:
- mpv version: a version with --term-remaining-playtime option 
- Platform and Version: linux
- Source of the mpv binary: manual compilation of code from gir

### Reproduction steps

Just play a video and see the lines display in the terminal giving
current position and length of video

### Expected behavior

Just like it has always been: like AV: 00:00:08 / 01:36:08

### Actual behavior

After the recent add of --term-remaining-playtime option
the video length will change depending of playing speed.

mpv have always shown current position and length of file.
When you add new functionality do not change the default
that have existed for a long time.
I have never needed "real" playing time for a video depending of playing speed!
mpv just like many other video players show current position and video length
so you can easily see where the position is in the video.
This new version can result in current position is a value long past video length.
While the GUI may now show remaining real time to play a video I do not think is was so from the beginning and there is no need to change the long time standard on terminal
output because of that.
I suggest you change so the default for terminal display is like it always have been.
Those who want something different could change the option.
I think it also would be better if showing remaining real play time, it is displayed in addition to the normal video length. In the terminal it could be
like: AV: 00:00:08 / 01:36:08 (xx:xx:xx)
and in the GUI somewhere on the screen allowing normal video length always be shown.

Please do not change good things that have existed for a long time and probably many are used to.

**Comment by Dudemanguy** [comment]
I don't think it really made any sense that OSC and the terminal showed completely different times. The OSC has shown the remaining playtime for many years at a minimum. Showing the actual amount of remaining time is a far more sensible imo and matches the OSC, but if you don't like it, you can change it which is why it's an option. I don't think this is something that most users are going to care that deeply about?

>like: AV: 00:00:08 / 01:36:08 (xx:xx:xx)

I guess something like this is another possibility. I didn't think of that.

**Comment by DanOscarsson** [comment]
Shown actual remaining time is not more sensible for me.
When I look at a video I want to see what position I am playing in the video and when the end is. This way I can easily, by just looking at numbers, see if I am near the en or not, and it is easy to see where I am going if I seek.
Yes, you can do that with graphical bar too.
Also I often want to quickly check length of video, which is easy if it is shown.
When looking at a video I have little need of finding out real time left to play. Instead I like to see where I am in the video to see how much of it is left.
It is the same amount left of a video independent of speed. If there is one hour left of the video, it will take one hour to show at normal speed and for example half an hour if speed is 2.
From what I can see the change you did does not show remaining real time.
Instead it shows the time it would take to view the video from beginning to end at the current speed. If you want to show remaining real time to play at current speed you would have to take (video length - current position)/speed.
Or am I mistaken in what you want to show?

**Comment by kxt** [comment]
The OSC shows times in two formats:
- [nominal time position] - [nominal time total],
- [nominal time position] - [real remaining time].

By nominal time, I mean the time the video was recorded/rendered, not considering playback speed. Real time is the wall clock time of playback, with speed being considered.

I find both output reasonable and they make intuitive sense, and I do agree that making the terminal UI behave the same way is a good idea.

However, term-remaining-playtime does not do that. It changes the output from [nominal time position] : [nominal time total] to [nominal time position] : [real total time].

This is both inconsistent with how the OSC works and it also lacks internal consistency: results in outputs that tell me that I'm currently at 00:50:31 of a 00:48:43 long video.

The term-remaining-playtime option does not do what the argument name and manual page suggest: it does not display remaining playtime, it displays total playtime. This is a bug.
