### ISSUE TITLE
Request for A/V delay?

### ISSUE THREAD

**Issue by r004** [mpv-player/mpv#1216]
Hello;
In previous version I could correct defected video files and their out of sync audio by -/+ .
I know it is not a bug but I wonder how could i get it back. it is a useful feature

**Comment by mailinglists35** [comment]
>Read the changelog on the github releases page.

for anyone else reading this in 2019 with no access to the manual page, the more kind answer is:

````
Increasing/decreasing audio delay have been remapped from "+" and "-" to "Ctrl++" and "Ctrl+-".
````

**Comment by CounterPillow** [comment]
>no access to the manual page

If you have internet access, you have access to the manual page: https://mpv.io/manual/master/#interactive-control

**Comment by wm4** [comment]
"Don't teach a man how to fish, instead make him dependent on feeding you" is the kind answer, right.
