### ISSUE TITLE
St2094-40 tonemapping 

### ISSUE THREAD

**Issue by Jamie666123** [mpv-player/mpv#12164]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file
Hi there I just have a quick question on st2094-40 and that is what happens when this tonemapping method is used on content which doesn’t have any dynamic metadata and is it capable of tonemapping Dolby vision 
Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by haasn** [comment]
In the absence of metadata it infers a default spline of {0, X, 1, 1, 1, ... 1} where both X and the order of the spline is picked to make the function pass through a knee point as determined by the same logic used for `st2094-10` and `spline`.

This should give mostly reasonable results, though obviously not as good as having HDR10+ metadata (the whole point of the function).

> is it capable of tonemapping Dolby Vision

DV is converted to normal HDR10 PQ before it passes into the tone mapper, so DV vs non-DV doesn't matter here.
