### ISSUE TITLE
mpv allow clicking through fullscreen, activating windows behind

### ISSUE THREAD

**Issue by bretter** [mpv-player/mpv#1217]
With mpv in fullscreen mode, click anywhere 5 times. The 5th click will bring forward whatever window was behind mpv. At this point it is as if mpv were a "click transparent." Any clicking in mpv will pull forward and put the focus on windows that had previously been behind mpv.

I am experiencing this issue in Gnome 3.14 in Arch Linux with two separate computers.

This problem does not seem to exist in xfce.

**Comment by zoli** [comment]
@bretter did you file a bug? If yes can I see the link?

**Comment by rrooij** [comment]
I can't reproduce this on Gnome 3.16.

**Comment by bretter** [comment]
@zoli, sorry for the long delay! GitHub's notifications are very subtle!

I didn't have to file a bug because one was already open: https://bugzilla.gnome.org/show_bug.cgi?id=738719

I am still experiencing this problem and have adjusted my behavior as a work around until the problem is fixed. Essentially, I only use MPV (the only application that I use in full screen much) in an otherwise empty workspace. Not perfect but if there is nothing behind MPV, there is nothing to steal focus.

**Comment by wm4** [comment]
Just to make sure, this is not with wayland, but with X11, right?

**Comment by bretter** [comment]
@wm4, correct; I am observing this problem with X11. I have not tried launching a wayland session to test this.
