### ISSUE TITLE
Odd run command quoting behavior

### ISSUE THREAD

**Issue by lI-guy-Il** [mpv-player/mpv#12179]
I am trying to use a key input to run a python script on windows:

`<key> run cmd /d /c start python '"C:\path with spaces\script.py"'`

And it doesn't run. Running `cmd /d /c start python '"C:\path with spaces\script.py"'` works.

So I was curious and ran tests:

```
run cmd /d /c start echo '"C:\path with spaces\script.py"'
```
output:
```
"\"C:\path with spaces\""
```

From cmd directly:
```
cmd /d /c start echo '"C:\path with spaces\script.py"'
```
output:
```
"C:\path with spaces\script.py"
```

I tried many combinations of ', ", and ` and never got a working result.

**Comment by natural-harmonia-gropius** [comment]
`\*` is escape character

```js
"\r\n" -> "<newline>"
'"\r\n"' -> "\r\n"
```

**Comment by avih** [comment]
First thing, you can probably use forward slashes `/` instead of backslashes `\`. This typically works everywhere, and can simplify things a lot, because then there are no escaping concerns.

Second thing, you probably don't need to go through cmd.exe. If you use it, then you're subject to cmd.exe quoting, which is very complex. You don't want to deal with that unless you absolutely have to.

And so, one of the following will probably work:
```
run "C:/path with spaces/script.py"
run python "C:/path with spaces/script.py"
run "c:/path/to/python.exe" "C:/path with spaces/script.py"
```

**Comment by lI-guy-Il** [comment]
> First thing, you can probably use forward slashes `/` instead of backslashes `\`. This typically works everywhere, and can simplify things a lot, because then there are no escaping concerns.

Huh? Thats not to do with my problem though, could you elaborate? I'm getting escaped \" after the echo, even though I didn't escape them.

> Second thing, you probably don't need to go through cmd.exe. If you use it, then you're subject to cmd.exe quoting, which is very complex. You don't want to deal with that unless you absolutely have to.

I need to call %appdata%

> ```
> run "C:/path with spaces/script.py"
> run python "C:/path with spaces/script.py"
> run "c:/path/to/python.exe" "C:/path with spaces/script.py"
> ```

None of these worked...

**Comment by avih** [comment]
What's the exact path of your `python.exe` ?

**Comment by lI-guy-Il** [comment]
@avih Does it matter if I can call it via console? I can get python to run, just the environment, not the file, by using `run cmd /d /c start python`

Anyway, it's `C:\Program Files\Python310\python.exe`

**Comment by avih** [comment]
> Does it matter if I can call it via console?

You mean the console inside mpv? yes, it matters, it means mpv can run it. Can you post a screenshot of the console after you typed the command but before you press enter to run it? (and where the run will succeed).

Also, please post a log of mpv when it doesn't run. Especially the third form - the one with full path to python.exe.
