### ISSUE TITLE
VRR (Freesync) Not Working

### ISSUE THREAD

**Issue by Kotaless** [mpv-player/mpv#12178]
### Important Information
- mpv version: v0.36.0-88-g598e3017
- Windows Version: 22621.2134
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/
- AMD Windows Driver Version: 31.0.21023.2012

### Reproduction steps
mpv --no-config 

### Expected behavior
VRR (Freesync) should work like in Media Player
![mediaPlayer](https://github.com/mpv-player/mpv/assets/9118532/cc8bb355-8c6c-472d-b906-23f1422d4e02)

### Actual behavior
VRR (Freesync) not working
![mpv](https://github.com/mpv-player/mpv/assets/9118532/e962f99c-692c-4015-b7c0-fb7e5c51122e)

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/12344157/output.txt)

### Sample files
Any video

**Comment by natural-harmonia-gropius** [comment]
I'm using nvdia card, VRR works with `--gpu-api=vulkan`

**Comment by Kotaless** [comment]
> I'm using nvdia card, VRR works with `--gpu-api=vulkan`

Didn't work with my AMD RX 6600. Maybe it's an AMD issue?

**Comment by adisib** [comment]
They automatically disable it for some specific applications I think. You should be able to add it as a game in Radeon Software and from the game specific graphics settings you can set FreeSync from "AMD optimized" to on.

**Comment by Kotaless** [comment]
> They automatically disable it for some specific applications I think. You should be able to add it as a game in Radeon Software and from the game specific graphics settings you can set FreeSync from "AMD optimized" to on.

This makes sense but I'm using the minimal driver. I'll install the full driver to test it.

**Comment by llyyr** [comment]
You can test by renaming the mpv.exe binary to the same as some video game where VRR works for you. I don't know what they're called but try league or csgo binaries I guess

**Comment by Kotaless** [comment]
> You can test by renaming the mpv.exe binary to the same as some video game where VRR works for you. I don't know what they're called but try league or csgo binaries I guess

Renaming to csgo.exe actually worked. Thank you!

**Comment by llyyr** [comment]
Can you also try naming it something random that's not mpv.exe and see if it works? Try some random gibberish

**Comment by Kotaless** [comment]
> Can you also try naming it something random that's not mpv.exe and see if it works? Try some random gibberish

This also works. Seems like AMD deliberately blocked "mpv.exe".
Adding it as a game and turning Freesync on for that profile also works.

**Comment by amariami** [comment]
> This also works. Seems like AMD deliberately blocked "mpv.exe". Adding it as a game and turning Freesync on for that profile also works.

Could it works while using VSR?

![Screenshot 2023-08-16 160600](https://github.com/mpv-player/mpv/assets/79769464/164bd41b-f0ba-4ba5-bccc-23ace1dcad0c)
![Screenshot 2023-08-16 160433](https://github.com/mpv-player/mpv/assets/79769464/187b18ae-0823-4ce4-9b67-6e4fd6e4d449)

**Comment by amariami** [comment]
> > They automatically disable it for some specific applications I think. You should be able to add it as a game in Radeon Software and from the game specific graphics settings you can set FreeSync from "AMD optimized" to on.
> 
> This makes sense but I'm using the minimal driver. I'll install the full driver to test it.

couldn't find the stable driver you could use [3rd party driver](https://www.amernimezone.com/)

**Comment by amariami** [comment]
> VSR is for video games, mpv already downscales if the video has higher resolution than your display.


I own quite old 50-inch FHD resolution some content might looks blurry. Re-read an old article in the web about [VSR](https://www-jagatreview-com.translate.goog/2015/07/apa-itu-vsr-di-amd-radeon/4/?_x_tr_sl=id&_x_tr_tl=en&_x_tr_hl=id&_x_tr_pto=wapp). maybe it might help when watching a blurry content with upscaling shader
