### ISSUE TITLE
2094-10 "tone-mapping-param" messing up brightness and saturation

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12176]
Provide following Information:
- v0.36.0 and git x86 64-v3 "20230806"
- Windows 7 Build 7601 Service Pack 1
- shinchiro/sourceforge
    
### Reproduction steps
Just watch a HDR video and use 2094-10 as tone mapping

### Expected behavior
Video don't shift in brightness and saturation. Stays uneffected

### Actual behavior
I have a problem with the "tone-mapping-param" with 2094-10. It is constantly shifting around and there is no value to fix it. It somehow resets for every new scene. If you are above (+)0 it effects some scenes and of you are under (-)0 then it effects the others. I just want to not be effected by this "feature".
And this should be possible, because when you use glsl tone mapping (which I don't have for 2094-10), then "tone-mapping-param" never effects the image.

### Sample files
There are conversations, where the one person is "normal" and when the camera goes to the other person in the dialog, then it messes with the brightness, which desaturates the picture.

Screenshots
How the scene plays out
![example2](https://github.com/mpv-player/mpv/assets/139760266/5647c913-0856-4cc5-892c-44555794cf94)

**Comment by geextahslex** [comment]
solved: set "tone-mapping-param" to 0.400-0.500

**Comment by haasn** [comment]
The parameter (adaptation strength) range for `st2094-10` is from 0 to 1, so setting negative values is the same as setting 0.

An adaptation strength of 0 means that the knee point will always be picked to preserve source brightness exactly, subject to the additional anti-clipping constraints (lowest possible knee point is at 10% of the display brightness range). This results in severe loss of near-black detail when the source (PQ) goes down to true black and the display (e.g. 1000:1 contrast TN/IPS) does not.

As you discovered, solution is to just not pick such extreme values. The parameter range is based on what's *legal*, not on what makes sense.
