### ISSUE TITLE
`display-width` and `display-height` returns wrong numbers when queried on secondary displays

### ISSUE THREAD

**Issue by CrendKing** [mpv-player/mpv#12172]
### Important Information

Provide following Information:
- mpv version: [shinchiro build 20230814-git-64db686](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230814)
- Windows Version: 22H2 build 22621.2134
- Source of the mpv binary: shinchiro nightly build
- If known which version of mpv introduced the problem: https://github.com/mpv-player/mpv/commit/a88fdfde0c91c16c84e6057b19bdc2fb9e666e24
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

* Have two displays, both with 2560x1440 resolution.
* `mpv --no-config --screen=<display_idx> <file>`
* In console, `print-text ${display-width}`

### Expected behavior

When `display_idx = 0`, get 2560. When `display_idx = 1`, get 2560.

### Actual behavior

When `display_idx = 0`, get 2560. When `display_idx = 1`, get 5120.

Related issue: https://github.com/mpv-player/mpv/issues/11510#issuecomment-1677918855

**Comment by Dudemanguy** [comment]
So it might be just as simple as this:
```
diff --git a/video/out/w32_common.c b/video/out/w32_common.c
index 08843d6378..e63969c164 100644
--- a/video/out/w32_common.c
+++ b/video/out/w32_common.c
@@ -1848,9 +1848,9 @@ static int gui_thread_control(struct vo_w32_state *w32, int request, void *arg)
         *(double*) arg = w32->display_fps;
         return VO_TRUE;
     case VOCTRL_GET_DISPLAY_RES: ;
-        RECT r = get_screen_area(w32);
-        ((int *)arg)[0] = r.right;
-        ((int *)arg)[1] = r.bottom;
+        RECT monrc = get_monitor_info(w32).rcMonitor;
+        ((int *)arg)[0] = monrc.right;
+        ((int *)arg)[1] = monrc.bottom;
         return VO_TRUE;
     case VOCTRL_GET_DISPLAY_NAMES:
         *(char ***)arg = get_disp_names(w32);
```
Can anybody on windows confirm?

**Comment by CrendKing** [comment]
That change from using `get_screen_area()` to `get_monitor_info()` is nice! I think your diff is good, but it doesn't hurt if someone can verify.

**Comment by Dudemanguy** [comment]
On a second look, I think `get_screen_area` should actually be exactly the same except it takes into account the `--fs-screen=all` case. So really, it's probably just missing subtraction. i.e.
```
diff --git a/video/out/w32_common.c b/video/out/w32_common.c
index 08843d6378..f00188fba9 100644
--- a/video/out/w32_common.c
+++ b/video/out/w32_common.c
@@ -1849,8 +1849,8 @@ static int gui_thread_control(struct vo_w32_state *w32, int request, void *arg)
         return VO_TRUE;
     case VOCTRL_GET_DISPLAY_RES: ;
         RECT r = get_screen_area(w32);
-        ((int *)arg)[0] = r.right;
-        ((int *)arg)[1] = r.bottom;
+        ((int *)arg)[0] = r.right - r.left;
+        ((int *)arg)[1] = r.bottom - r.top;
         return VO_TRUE;
     case VOCTRL_GET_DISPLAY_NAMES:
         *(char ***)arg = get_disp_names(w32);
```

**Comment by CrendKing** [comment]
When `--fs-screen=all` is used, mpv will span both displays, and the `display-width` will be the sum, but I'd argue that's not exactly the display resolution of either screen. At least your previous impl still returns the correct resolution of ONE screen.

If necessary, you could add a clarification to the doc of `display-width` saying that when `--fs-screen=all` is used, the property only returns the initial screen, similar to the `current` clause of [`fs-screen`](https://mpv.io/manual/master/#options-fs-screen): mpv will fallback on what the user provided with the `screen` option.

**Comment by CrendKing** [comment]
> As an aside, I sure hope nobody actually uses --fs-screen=all.

It's like [Rule 34](https://en.wikipedia.org/wiki/Rule_34). If it exists, someone will use it. If it imposes some problem, either programmatically or ideologically, you gotta deprecate and remove it.

**Comment by CrendKing** [comment]
Sorry I forgot that I wasn't able to test because I couldn't get VapourSynth working in my build. Since this doesn't touch VapourSynth, I can test it myself. Here's the result.

With the first version of diff, The `display-width` and `display-height` properties are correctly set to the resolution of the initial display, regardless if it primary or secondary, regardless of their relative placement. And with `--fs-screen=all`, it always returns the resolution of the primary display.

I think it's good to go.

**Comment by CrendKing** [comment]
Tried the nightly and everything works now.
