### ISSUE TITLE
Support C Plugins on Windows

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#12185]
### Expected behavior of the wanted feature

Support C Plugins on Windows, this would allow to interop easily with dotnet using the component object model (COM) (or CLR runtime hosting). I want to build a GUI not as frontend but as extension to the original mpv player. It can be done with JSON RPC, but might not be the best solution for my use case.

Furthermore, it would help certain use cases, if C plugins had the possibility to create as many client handles as they wish, for instance to build a Python, C# or WASI script/extension host.

**Comment by stax76** [comment]
They work only on Linux/BSD.

Related:

https://github.com/lapce/lapce

> Plugins can be written in programming languages that can compile to the [WASI](https://wasi.dev/) format (C, Rust, [AssemblyScript](https://www.assemblyscript.org/))

**Comment by hooke007** [comment]
related https://github.com/mpv-player/mpv/pull/7800

**Comment by kasper93** [comment]
I've added dynamically loading/injecting the mpv's symbols into cplugin. From my testing it works well, you can try it out https://github.com/mpv-player/mpv/pull/12189

**Comment by stax76** [comment]
Thank you for the very fast reaction! I will try it and report back.

**Comment by stax76** [comment]
I have problems making a build with MXE, it seems I have to build a ffmpeg version that is newer than the version provided by MXE, and don't know how to do it, and I don't know how to set the cmake location.

I tried also the tool chain of shinchiro, but with that, couldn't make it either.

The guide I used:

https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md

```
BS /media/frank/Data/Build/Linux/mpv> export PKG_CONFIG=/media/frank/Data/Build/Linux/mxe/usr/bin/x86_64-w64-mingw32.static-pkg-config
BS /media/frank/Data/Build/Linux/mpv> meson setup build --cross-file cross-file
The Meson build system
Version: 1.1.0
Source dir: /media/frank/Data/Build/Linux/mpv
Build dir: /media/frank/Data/Build/Linux/mpv/build
Build type: cross build
Project name: mpv
Project version: 0.36.0-UNKNOWN
C compiler for the host machine: x86_64-w64-mingw32-gcc (gcc 10.0.0 "x86_64-w64-mingw32-gcc (GCC) 10-win32 20220113")
C linker for the host machine: x86_64-w64-mingw32-gcc ld.bfd 2.38
C compiler for the build machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the build machine: cc ld.bfd 2.38
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Found pkg-config: /media/frank/Data/Build/Linux/mxe/usr/bin/x86_64-w64-mingw32.static-pkg-config (0.28)
Dependency libavcodec found: NO found 58.54.100 but need: '>= 58.134.100'
Found CMake: NO
Run-time dependency libavcodec found: NO 

meson.build:19:13: ERROR: Dependency lookup for libavcodec with method 'pkgconfig' failed: Invalid version, need 'libavcodec' ['>= 58.134.100'] found '58.54.100'.

A full log can be found at /media/frank/Data/Build/Linux/mpv/build/meson-logs/meson-log.txt
```

**Comment by kasper93** [comment]
Indeed MXE is outdate, I wouldn't recommend using it. On Windows I would recommend using MSYS2 environment (there is a guide for it too), you don't have to build anything except mpv and maybe libplacebo now, because we just broke compatibility with provided package.

Alternatively you can use this script to build everything https://github.com/mpv-player/mpv/blob/master/ci/build-mingw64.sh except toolchain.

**Comment by zhongfly** [comment]
@stax76 you can try my build https://github.com/zhongfly/mpv-winbuild/actions/runs/5922854644

**Comment by kasper93** [comment]
We also build for each PR, not as fancy as @zhongfly one, but usable https://github.com/mpv-player/mpv/actions/runs/5919727302?pr=12189 No libmpv packaged though, I assumed you would need it, but now I think might not for plugin test only.

**Comment by stax76** [comment]
Thanks, @kasper93 and @zhongfly, I used to make Windows builds with the WAF system, but with Meson so far I wasn't successful.

@kasper93
I did a [small C++ project](https://github.com/staxrip/staxrip/tree/master/Source/FrameServer) 2-3 years ago, but I forget things easily and don't understand any special or advanced C code. If you still have your test code, seeing it would help me, so far I get different errors, depending on where I define MPV_CPLUGIN_DYNAMIC_SYM.

**Comment by kasper93** [comment]
> I get many errors from Visual Studio

Current version uses `__typeof__` to reduce complexity a little and infer function types automatically. This is not supported by MSVC. Since Microsoft ships clang with their build tools now and mpv itself cannot be build with MSVC anyway, I decided that this "limitation" is acceptable.

To build the plugin you can do from VS dev console or with any compiler that would produce PE binary.

`clang plug.c -DMPV_CPLUGIN_DYNAMIC_SYM -IF:/dev/install/include -shared -o plug.dll`

``` C
#include <stdio.h>
#include <windows.h>

#include <mpv/client.h>

__declspec(dllexport)
int mpv_open_cplugin(mpv_handle *handle)
{
    printf("mpv version: %lu\n", mpv_client_api_version());
    // ...
    return 0;
}
```

**Comment by stax76** [comment]
It should be fine, if somebody wants to use something MS specific, it can still be done with a wrapper DLL.
