### ISSUE TITLE
Set default transfer function of .exr files to linear

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [mpv-player/mpv#12180]
### Important Information

Provide following Information:
- mpv version
- Platform and Version
- Source of the mpv binary

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Open an exr file.

### Expected behavior

Input gamma is linear

### Actual behavior

Input gamma is srgb

`vf=format:gamma=linear` can make image looks correct.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

### Sample files

https://github.com/sobotka/Testing_Imagery

**Comment by Traneptora** [comment]
Are OpenEXR files always in linear light? If so, this should be handled by the FFmpeg decoder, not by mpv.

**Comment by Traneptora** [comment]
Upon further inspection, FFmpeg's EXR decoder has a `apply_trc` option, but it defaults to `gamma`, and the gamma value defaults to `1.0`, which means it outputs linear light as linear light, but untagged. This should be changed upstream.

**Comment by Traneptora** [comment]
Test this: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230816052006.53562-1-leo.izen@gmail.com/

**Comment by natural-harmonia-gropius** [comment]
> Test this: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230816052006.53562-1-leo.izen@gmail.com/

Fixed

**Comment by Traneptora** [comment]
Thanks for testing, I'll close this issue when it gets merged upstream.

**Comment by Traneptora** [comment]
Fixed by FFmpeg/FFmpeg@7098bec73bd3.
