### ISSUE TITLE
Anime4k clamp highlights shader behaves strange when playing some jpeg files

### ISSUE THREAD

**Issue by Ptilopsis01** [mpv-player/mpv#12183]
### Important Information

Provide following Information:
- mpv version v0.36.0-80-gdfbdf751
- Windows Version win11 22621.2213
- Source of the mpv binary https://github.com/zhongfly/mpv-winbuild/releases
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches
<img width="1280" alt="屏幕截图 2023-08-16 192229" src="https://github.com/mpv-player/mpv/assets/93318731/f6510b1b-0906-47ad-9707-cc858f4b00bd">
<img width="1280" alt="屏幕截图 2023-08-16 192255" src="https://github.com/mpv-player/mpv/assets/93318731/252f2dfb-b517-44ff-aecb-556a43e65450">

### Reproduction steps

The first picture is what is shown in mpv with Anime4k clamp highlights shader, and the second one is the picture shown with same params, except Anime4k clamp highlights shader (which behaves correctly). I've noticed that this situation happens when the picture is embedded with a gamut file (srgb in this picture), and mpv misidentified its color matrix as bt.601, maybe it's related with this situation 

### Expected behavior

Anime4k clamp highlights shader behaves normally

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/12358863/mpv.log)

### Sample files

[80391478_p0.zip](https://github.com/mpv-player/mpv/files/12358870/80391478_p0.zip)

**Comment by Traneptora** [comment]
Can you reproduce the issue with `--no-config`? You have a lot of weird options in your conf file, like `--linear-downscaling=no` for some reason.

**Comment by Ptilopsis01** [comment]
> Can you reproduce the issue with `--no-config`? You have a lot of weird options in your conf file, like `--linear-downscaling=no` for some reason.

I've just tried with `--no-config --glsl-shaders-append="C:\Users\pc\AppData\Roaming\mpv\shaders\Anime4K_Clamp_Highlights.glsl"` params and it also behaves strange, but I found that when I turned off the HDR mode of Windows, it behaves correctly.
But the problem still exists even I turned HDR off when I use my previous settings.

**Comment by Traneptora** [comment]
The problem is most likely with the shader itself then.
