### ISSUE TITLE
How to achieve a backward cycle hotkey?

### ISSUE THREAD

**Issue by RalfReddings** [mpv-player/mpv#12184]
MPV easily lets you cycle between values with one hotkey. For example using the `h` key to cycle between aspect ratios of `16:9`, `4:3`, `2.35:1`, `-1` and so on:
    
    h cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"
    
It is also possible to do a similar thing with video rotation:
    
    j cycle_values video-rotate 90 180 270 360 0
    

I am looking to achieve a way to cycle backwards, so I can pair the `J` key with another key. `F` will rotate counter clockwise, while `J` rotates clockwise

So with the above example in mind, if the current ration is at `270`, pressing `F` will set the rotation to `180`, while pressing `J` will set it to `360`

I would like to do this with **video-aspect**, **Video-Rotate** etc.

Any help would be greatly appreciated!

**Comment by guidocella** [comment]
`cycle-values !reverse`

**Comment by RalfReddings** [comment]
Thanks!

**Comment by realyukii** [comment]
is this also applied for cycle audio? that by default is `#`

**Comment by guidocella** [comment]
`cycle audio down` cycles audio tracks backwards.
