### ISSUE TITLE
gpu-next: scaler is broken

### ISSUE THREAD

**Issue by cold-nagai** [mpv-player/mpv#12187]
### Important Information

Provide following Information:
<details><summary>mpv --version</summary>

```
mpv v0.36.0-106-g0b4a36476d Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Aug 17 2023 01:06:16
libplacebo version: v6.292.0-166-ge7a22df7
FFmpeg version: N-111774-g082133fc07
FFmpeg library versions:
   libavutil       58.16.101
   libavcodec      60.23.100
   libavformat     60.10.100
   libswscale      7.3.100
   libavfilter     9.11.100
   libswresample   4.11.100
```
</details>

- Arch Linux 6.4.10-arch1-1
- aur/mpv-git
- Hyprland 0.28.0-1
- extra/mesa 1:23.1.5-1
![2023-08-17T01:27:37,374802623+03:00](https://github.com/mpv-player/mpv/assets/126972909/4c15ad52-d27d-4723-adc7-b99a71b71fd3)

### Reproduction steps
Run mpv with --vo=gpu-next and any scaler. 

`mpv --no-config '360p Quality Test [kLZJw_JAaMk].webm' --vo=gpu-next --scale=mitchell`

### Log file
https://0x0.st/HLBk.log

**Comment by kasper93** [comment]
My fault probably, will look tomorrow, although it works fine one my end.

**Comment by bjin** [comment]
Just a quick glance, the problem seems to be `variable ca` is not initialized.

```
[   0.492][d][vo/gpu-next/libplacebo] [ 42] /*ftype*/_d c, ca;
[   0.492][d][vo/gpu-next/libplacebo] [ 43]         ws = /*lut*/_5(vec2(float(0 / 4) / 1.00000000000000000000f, fcoord));
[   0.492][d][vo/gpu-next/libplacebo] [ 44]         ca += ws[0 % 4] * textureLod(/*src_tex*/_2, base + pt * vec2(0.0), 0.0)./*swiz*/_e;
[   0.492][d][vo/gpu-next/libplacebo] [ 45]         ca += ws[1 % 4] * textureLod(/*src_tex*/_2, base + pt * vec2(1.0), 0.0)./*swiz*/_e;
[   0.492][d][vo/gpu-next/libplacebo] [ 46]         ca += ws[2 % 4] * textureLod(/*src_tex*/_2, base + pt * vec2(2.0), 0.0)./*swiz*/_e;
[   0.492][d][vo/gpu-next/libplacebo] [ 47]         ca += ws[3 % 4] * textureLod(/*src_tex*/_2, base + pt * vec2(3.0), 0.0)./*swiz*/_e;
[   0.492][d][vo/gpu-next/libplacebo] [ 48]         ws = /*lut*/_5(vec2(float(4 / 4) / 1.00000000000000000000f, fcoord));
[   0.492][d][vo/gpu-next/libplacebo] [ 49]         ca += ws[4 % 4] * textureLod(/*src_tex*/_2, base + pt * vec2(4.0), 0.0)./*swiz*/_e;
[   0.492][d][vo/gpu-next/libplacebo] [ 50]         ca += ws[5 % 4] * textureLod(/*src_tex*/_2, base + pt * vec2(5.0), 0.0)./*swiz*/_e;

```

**Comment by kasper93** [comment]
> Just a quick glance, the problem seems to be the variable ca is not initialized.

Looks like we did the same in parallel :) https://code.videolan.org/videolan/libplacebo/-/merge_requests/534/

**Comment by bjin** [comment]
It's a quick fix so it doesn't bother me much. Anyway, I retracted mine PR.

**Comment by kasper93** [comment]
Sorry for trouble. As a retrospect I looked why it was working for me, because I tested it beforehand and read the generated spir-v during development to make sure I don't alter any behavior.

Apparently `shaderc` is initializing this variable **implicitly**, hence why it works correctly. Switching to `glslang` immediately exposes the uninitialized variable. I guess a mental note for the future.
