### ISSUE TITLE
20K lines of MPV data in ~/.xsession-errors

### ISSUE THREAD

**Issue by Aiden2368** [mpv-player/mpv#12198]
### Important Information

Provide following Information:
- mpv version: mpv 1:0.36.0-1
- Linux Distribution and Version: Arch Linux 6.4.10-arch1-1
- Window Manager and version: Xfm4

### Issue

MPV works perfectly fine except that it writes a lot of data into `~/.xsession-errors`.  The data looks something like `[KAV: 00:00:33 / 00:00:40 (84%) x2.00 A-V:  0.000 Cache: 5.5s/879KB`.  I have literally 20K lines of just that in my `~/.xsession-errors` file.

**Comment by mia-0** [comment]
That’s your desktop environment (login script?) dumping the stderr output of every child process that isn’t attached to anything else (such as most processes launched from e.g. a file manager) into `~/.xsession-errors`. There’s nothing mpv can do about that.

**Comment by mia-0** [comment]
Furthermore, this should not happen when using the included .desktop file: It sets the player operation mode to `pseudo-gui`, which disables terminal output.

**Comment by Aiden2368** [comment]
I have been running MPV from a custom script. A script which looks like this
```
#!/bin/bash

if [ -z "$1" ]; then
    exit 1
fi

mpv_processes=$(pgrep mpv)

if [ ! -z "$mpv_processes" ]; then
    kill $mpv_processes
fi

mpv --loop-file=inf --speed=$(cat "/home/$USER/Documents/code/customSettings/mpvSpeed") --volume=50.000 --fs "$1"
```
I will add the `--player-operation-mode=pseudo-gui` arg to it and see if that fixes my problem. Consider this issue solved should I not reply within a week. Thank you

**Comment by mia-0** [comment]
You also might want to take a look at [TOOLS/umpv](https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv).
