### ISSUE TITLE
Segmentation fault for any video sample

### ISSUE THREAD

**Issue by vdusr** [mpv-player/mpv#12193]
mpv is crashed with "Segmentation fault" for each video sample.

### Important Information
- mpv version: 
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Wed Aug 09 09:42:46 2023
libplacebo version: v5.264.1
FFmpeg version: 4.4.4
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100

- Linux Distribution and Version: Voidlinux
- If known which version of mpv introduced the problem: 0.36.0. Version 0.35.0 have not this problem. 
- Window Manager and version: LXQT+openbox
- GPU driver and version: Intel imbedded.

### Reproduction steps
The issue s reprodusible for each video file, e.g. http://docs.evostream.com/sample_content/assets/bunny.mp4
- Download video sample, e.g. http://docs.evostream.com/sample_content/assets/bunny.mp4
- $ mpv bunny.mp4 
or
- $mpv --no-config --log-file=output_no-config.txt bunny.mp4

The same problem is reproducible with --no-config.
There is no Segmentation fault with --no-video but also there is no video but audio only :)

### Expected behavior
There is no Segmentation fault 

### Actual behavior
Segmentation fault 

### Log file
[output_no-config.txt](https://github.com/mpv-player/mpv/files/12377309/output_no-config.txt)

### Sample files
The issue s reprodusible for each video file, e.g. http://docs.evostream.com/sample_content/assets/bunny.mp4

**Comment by CounterPillow** [comment]
post a gdb backtrace

**Comment by vdusr** [comment]
$ mpv --no-config bunny.mp4 
 (+) Video --vid=1 (*) (h264 424x240 24.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
libEGL warning: DRI2: failed to authenticate
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu/drm] VT_GETMODE failed: Inappropriate ioctl for device                                                                                             
[vo/gpu/drm] Failed to set up VT switcher. Terminal switching will be unavailable.                                                                         
pci id for fd 14: 1b36:0100, driver (null)                                                                                                                 
MESA-LOADER: failed to open qxl: /usr/lib64/dri/qxl_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
pci id for fd 15: 1b36:0100, driver (null)
kmsro: driver missing
[vo/gpu] Failed to create GBM surface.
[vo/gpu] Failed to setup GBM.                                                                                                                              
[vo/gpu] Failed to commit atomic request: Function not implemented                                                                                         
Segmentation fault

**Comment by vdusr** [comment]
> 

$ gdb --args mpv bunny.mp4 
GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mpv...
(No debugging symbols found in mpv)
(gdb) run
Starting program: /usr/bin/mpv bunny.mp4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[New Thread 0x7ffff03b96c0 (LWP 4202)]
[New Thread 0x7fffefbb86c0 (LWP 4203)]
[New Thread 0x7fffe73b76c0 (LWP 4204)]
[New Thread 0x7fffef3b76c0 (LWP 4205)]
[New Thread 0x7fffeebb66c0 (LWP 4206)]
[New Thread 0x7fffee3b56c0 (LWP 4207)]
[New Thread 0x7fffedbb46c0 (LWP 4208)]
[New Thread 0x7fffed3b36c0 (LWP 4209)]
[New Thread 0x7fffecbb26c0 (LWP 4210)]
[Thread 0x7fffee3b56c0 (LWP 4207) exited]
[New Thread 0x7fffee3b56c0 (LWP 4211)]
[New Thread 0x7fffee3b56c0 (LWP 4212)]
[Thread 0x7fffee3b56c0 (LWP 4211) exited]
[New Thread 0x7fffe6bb66c0 (LWP 4213)]
 (+) Video --vid=1 (*) (h264 424x240 24.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
[New Thread 0x7fffe63b56c0 (LWP 4214)]
[Thread 0x7fffe63b56c0 (LWP 4214) exited]
[New Thread 0x7fffe63b56c0 (LWP 4215)]
libEGL warning: DRI2: failed to authenticate
[New Thread 0x7fffe5bb46c0 (LWP 4216)]
[New Thread 0x7fffe53b36c0 (LWP 4217)]
[New Thread 0x7fffe4bb26c0 (LWP 4218)]
[New Thread 0x7fffc1fff6c0 (LWP 4219)]
[New Thread 0x7fffc17fe6c0 (LWP 4220)]
[New Thread 0x7fffc0ffd6c0 (LWP 4221)]
[New Thread 0x7fffa7fff6c0 (LWP 4222)]
[New Thread 0x7fffa77fe6c0 (LWP 4223)]
[New Thread 0x7fffa6ffd6c0 (LWP 4224)]
[vo/gpu/opengl] Suspected software renderer or indirect context.
[Thread 0x7fffa7fff6c0 (LWP 4222) exited]                                                                                                                  
[Thread 0x7fffa77fe6c0 (LWP 4223) exited]
[Thread 0x7fffc0ffd6c0 (LWP 4221) exited]
[Thread 0x7fffc17fe6c0 (LWP 4220) exited]
[Thread 0x7fffc1fff6c0 (LWP 4219) exited]
[Thread 0x7fffe4bb26c0 (LWP 4218) exited]
[Thread 0x7fffe5bb46c0 (LWP 4216) exited]
[Thread 0x7fffe53b36c0 (LWP 4217) exited]
[Thread 0x7fffa6ffd6c0 (LWP 4224) exited]
[vo/gpu/drm] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/drm] Failed to set up VT switcher. Terminal switching will be unavailable.                                                                         
pci id for fd 14: 1b36:0100, driver (null)                                                                                                                 
MESA-LOADER: failed to open qxl: /usr/lib64/dri/qxl_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri, suffix _dri)
pci id for fd 15: 1b36:0100, driver (null)
kmsro: driver missing
[vo/gpu] Failed to create GBM surface.
[vo/gpu] Failed to setup GBM.                                                                                                                              
[vo/gpu] Failed to commit atomic request: Function not implemented                                                                                         
                                                                                                                                                           
Thread 15 "mpv/vo" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe63b56c0 (LWP 4215)]
0x00007ffff5ebff50 in gbm_surface_destroy () from /usr/lib/libgbm.so.1
(gdb)

**Comment by N-R-K** [comment]
> gbm_surface_destroy

Probably related: https://github.com/mpv-player/mpv/pull/12146

**Comment by Dudemanguy** [comment]
You're trying to probe the drm context for some reason which shouldn't be happening.

> [vo/gpu/opengl] Suspected software renderer or indirect context.

Seems like something's wrong with your drivers dunno.

**Comment by vdusr** [comment]
> Seems like something's wrong with your drivers dunno.
Can you please say how to fix iit?

**Comment by Traneptora** [comment]
What driver are you using?

**Comment by Dudemanguy** [comment]
The segfault should be fixed at least. The broken drivers is a different issue (but not an mpv one).
