### ISSUE TITLE
darkening of the image when skipping the rpu in Dolby Vision TV video in an mp4 container

### ISSUE THREAD

**Issue by AdventurerRussia** [mpv-player/mpv#12205]
Hello, I noticed that in the new version of the player there is a darkening of the frame when the rpu layer is skipped, in short, when the text appears in the console: **Multiple Dolby Vision RPUs found in one AU. Skipping previous.**
there was no such problem in the 0.35.1 version, but it appeared in 0.36.
I recorded a video where the flashing is clearly visible at 0.36 weight https://youtu.be/2z1FC6yzYWA
.
by brute force with another person, we found a flashing problem, videos collected by GPAC-2.3-DEV-rev471-g252bc859-master and versions further cause flashing in the 0.36 version of the player
.
here is a magnet link to a video of such a problem of dark frames if anything https://fex.net/ru/s/13aptlv
.
again, I understand that this is a GPAC problem, and everything is fine on older versions of it, but the new version of your player now gives flashing dark frames when skipping the rpu layer. I decided to report this issue that the new GPAC is causing dark frames
Windows 11 Pro
22H2 22621.2134
assembling: https://sourceforge.net/projects/mpv-player-windows/files/release/
there are only keys in the settings file --vo=gpu-next

**Comment by quietvoid** [comment]
For one, I don't think 0.35.1 supported dynamic brightness metadata from Dolby Vision.
It would be nice to have a proper sample file and not some torrent link, so I could investigate further what's happening.

It does look like a file issue, though. Maybe the same as #11548
