### ISSUE TITLE
slang subtitle setting doesn't work

### ISSUE THREAD

**Issue by Solarunit** [mpv-player/mpv#12202]
`slang` subtitle setting doesn't work anymore, video is playing without subs

Provide following Information:
- mpv version: mpv 0.36.0
- Linux Distribution and Version: Solus
- Source of the mpv binary: Solus repo
- Window Manager and version: Budgie
- GPU driver and version: amdgpu, 4.6 Mesa 23.1.6

I see some subs-related changes in the v0.36.0, maybe it's related

### Reproduction steps

having `slang=English,eng,en` in the config file is ignored, while `alang` still works. Video is playing with disabled subs.

### Expected behavior

When playing video with multiple subs, eng subs should be selected

### Actual behavior

subtitles are disabled for the video.

**Comment by hooke007** [comment]
dup and see https://github.com/mpv-player/mpv/pull/12015

**Comment by Dudemanguy** [comment]
It's because `--subs-with-matching-audio` was set to `no` by default and the video you are playing presumably has english audio.. This was later flipped back `yes` after the release (linked PR).

**Comment by Solarunit** [comment]
So I just can wait for the next release for the fix?
or temporary set `--subs-with-matching-audio` to `yes` ?

**Comment by Dudemanguy** [comment]
You can just set `--subs-with-matching-audio` to `yes` for now, yeah.

**Comment by Solarunit** [comment]
Thanks for the quick response! And restoring old behavior!
