### ISSUE TITLE
Achieving Equivalent HDR to SDR Conversion in ffmpeg as in MPV

### ISSUE THREAD

**Issue by eviluess** [mpv-player/mpv#12200]
Hey there,
I really enjoy using MPV, especially when it converts HDR videos to SDR mode and SDR videos to HDR mode. The conversion quality is so amazing!
Could you please help me understand how to use ffmpeg to achieve similar results as MPV?
I've tried some commands to convert HDR to SDR but the results are not as good as with MPV.
Here is one example command I tried:
`ffmpeg -y -hwaccel cuda -init_hw_device opencl=ocl -filter_hw_device ocl -extra_hw_frames 3 -threads 16 -i hdr.mkv -vf "format=p010,hwupload,tonemap_opencl=tonemap=mobius:param=0.01:desat=0:r=tv:p=bt709:t=bt709:m=bt709:format=nv12,hwdownload,format=nv12" -c:a copy -c:s copy -c:v hevc_nvenc -max_muxing_queue_size 8192 sdr.mkv`
I would really appreciate any suggestions you may have. Thank you in advance!

**Comment by haasn** [comment]
Use `vf_libplacebo`, not `tonemap_opencl`.

**Comment by eviluess** [comment]
Thank you both @arm64-v9a and @haasn ~

I tried the following command and it produces results very close to what MPV looks like:
`ffmpeg -y -init_hw_device vulkan=vulkan -filter_hw_device vulkan -i HDR.mkv -vf "hwupload,libplacebo=iw:ih:format=yuv420p10le:colorspace=bt709:color_primaries=bt709:color_trc=arib-std-b67,hwdownload,format=yuv420p10le" -c:v libx265 -c:a copy sdr.mkv`
I have a question about using color_trc=bt709 - when I try this, the result is too bright and causes some hard clipping. That's why arib-std-b67 looks much better to me. I'm not sure why targeting bt709 doesn't use the bt709 color transfer function properly.
I would appreciate any insights you may have on this. Looking forward to your reply and thank you in advance for the help!

> ffmpeg -y -init_hw_device cuda=cu -init_hw_device vulkan=vk@cu -filter_hw_device vk -hwaccel nvdec -threads 16 -i hdr.mkv -vf "hwupload, libplacebo=colorspace=bt709:color_primaries=bt709:color_trc=bt709:format=nv12,hwupload=derive_device=cuda" -c:a copy -c:s copy -c:v hevc_nvenc -max_muxing_queue_size 8192 sdr.mkv

> Use the `libplacebo` filter, not `tonemap_opencl`.

**Comment by eviluess** [comment]
> Maybe you could try specifying `gamut_mode` and `tonemapping`

Thank you for the tips. I will try them out tomorrow.
By the way, I noticed that using arib-std-b67 in the command line produces results most similar to the MPV does. However, I've checked that the "Transfer Characteristics" of the test video I'm using is PQ, not HLG.
This is confusing to me, because my understanding was that arib-std-b67 should be used for HLG content. The fact that it looks better for my PQ video makes me question whether I fully grasp how to use these parameters correctly.
I'm not sure why arib-std-b67 would look better than bt709 for my PQ source. If you have any insights into what might be going on here and how I should be setting these color parameters properly, I would really appreciate your expertise! Please let me know if I can provide any other details that would help clarify my confusion.
I'm still learning a lot about color spaces, transfer functions, etc. so any additional guidance would be greatly appreciated. Looking forward to testing this further tomorrow.
