### ISSUE TITLE
af=lavfi multitrack confusion (switching different channel layout)

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12209]
Hi, I need some help.

What I want: 
switching Audio Tracks with different channel layouts, triggers desired lavfi options, written in mpv.conf. So when 1st track is stereo then profile "stereo" is used.
When the 2nd audio track is 5.1, then profile "5.1" is used. So the settings switch on the fly.

What I did:
(I added hue changes to make it easy visible if changes occur.)
...................................................................................................................................
[Stereo]
profile-cond=get("audio-params/channel-count") ==2
af=lavfi=[pan=2c|c0=c0|c1=c1]
hue=0

[5.1]
profile-cond=get("audio-params/channel-count") ==6
af=lavfi=[pan=6c|c0=0.8*c0|c1=0.8*c1|c2=c2|c3=c3|c4=0.8*c4|c5=0.8*c5]
hue=-50
...................................................................................................................................

The effect:
The funny thing is that this works when the 2nd track is an extern audio file, and for example .mp3 (ac3 and ogg didn't work)
When I muxed this .mp3 file in the same .mkv container, then it stopped working. So mpv checks better/more often extern audio files?
I don't know what I'm doing wrong. This kinda works and then it kinda doesn't. Am I missing something?

And this works as expected but only with the main audio track, but when you switch to 2nd/3rd audio track (with a different channel layout), then it breaks

Please help, any advice?

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/11541

**Comment by geextahslex** [comment]
Okay, so that means that something is broken?

**Comment by hooke007** [comment]
I think so, but no devs had confirmed it so far.

**Comment by geextahslex** [comment]
solved: add "profile-restore=copy-equal" to every profile

[Stereo]
profile-cond=get("audio-params/channel-count") ==2
profile-restore=copy-equal
af=lavfi=[pan=2c|c0=c0|c1=c1]

[5.1]
profile-cond=get("audio-params/channel-count") ==6
profile-restore=copy-equal
af=lavfi=[pan=6c|c0=0.8c0|c1=0.8c1|c2=c2|c3=c3|c4=0.8c4|c5=0.8c5]
