### ISSUE TITLE
Error with applets that use MPV, Linux Mint 21.2 Cinnamon

### ISSUE THREAD

**Issue by NorfLoud** [mpv-player/mpv#12206]
### Important Information

Linux Mint 21.2 Cinnamon

mpv --version

mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4.2-0ubuntu0.22.04.1

### Reproduction steps

On Linux Mint 21.2 Cinnamon, install the Radio 3.0 applet, add a radio station, launch it and wait for the PC monitor to turn off on the screen saver. Playback will stop.
By default, the screen saver turns on first by timer, then the monitor turns off by timer as well.

### Expected behavior

The radio station will continue playing after the monitor is turned off.

**Comment by sfan5** [comment]
Report this behavior to the developer of the applet first.

mpv 0.34.1 is also old and unsupported.

**Comment by NorfLoud** [comment]
Why do you have an old version in your Linux Mint repositories that is no longer supported?

**Comment by Dudemanguy** [comment]
We are not mint developers or packagers.
