### ISSUE TITLE
Change OSC position 

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12217]
Hi, 
I want to change the OSC position. Move it up on the y-axis, to look like this. 
How can I achieve this?
(I made this in photoshop as an example)
![OSC 2](https://github.com/mpv-player/mpv/assets/139760266/acfa1ecd-5471-407c-bc3e-0bb6f91c7a95)

**Comment by Raza-0007** [comment]
@geextahslex, the setting you are looking for is 

[--osd-bar-align-y](https://mpv.io/manual/master/#options-osd-bar-align-y)

Play with different values to get your desired OCD height.

~Raza

**Comment by geextahslex** [comment]
No this doesnt't effect the OSC position

**Comment by Raza-0007** [comment]
You are right! Sorry about that. I tested it right now and I believe that setting only controls the OSD bar that appears in full screen mode, and not the actual OSC itself.

When I use mpv without a frontend, I normally use it with [uosc](https://github.com/tomasklaen/uosc), so I have limited experience with mpv's default OSC.

I will try to find the answer for you. Hopefully someone else who uses mpv's default OSC will jump in and answer.

~Raza

**Comment by Raza-0007** [comment]
@geextahslex, I may have found what you are looking for. See this link

[OSC- Configurable Options](https://github.com/mpv-player/mpv/blob/master/DOCS/man/osc.rst#configurable-options)

And scroll down to the `valign` option.

**Comment by Raza-0007** [comment]
@geextahslex, I just tested it and I am sorry but the correct option is `barmargin` on the same page linked before.

`barmargin=40`

Should do the trick. You can also play around with the numbers (20-50) is probably what you are looking for.

p.s. note to myself. Test the settings before recommending it to others! :wink:

~Raza

**Comment by geextahslex** [comment]
Wow it really worked. Great!
barmargin=78 solved it 

Thank you very much :)
