### ISSUE TITLE
Question about requirement of FFmpeg 4.4

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12216]
Hi,
the newest release v0.36.0 mentions that "This release requires FFmpeg 4.4 or newer."
What does this actually mean? Is this meant for compiling your own code or to just run mpv as intended?
I don't have FFmpeg 4.4 installed on my PC

Thanks for any answers

**Comment by CounterPillow** [comment]
It's for compiling mpv and for people who distribute mpv to know. When you download a Windows build from someone, the required libraries are included.

**Comment by geextahslex** [comment]
okay, thank you
