### ISSUE TITLE
Vulkan hardware decoding does not work on my AMD GPU.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#12213]
### Important Information

Provide following Information:
- mpv version
```
mpv v0.36.0-152-g3422e5e1e8 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.292.0-200-ge9b39ab1
FFmpeg version: N-111792-gf0b1cab538
FFmpeg library versions:
   libavutil       58.17.100
   libavcodec      60.23.100
   libavformat     60.10.100
   libswscale      7.3.100
   libavfilter     9.11.100
   libswresample   4.11.100
```
- Linux Distribution and Version
`ArchLinux`
- Source of the mpv binary
`AUR`
- If known which version of mpv introduced the problem
`I don't know.`
- Window Manager and version
`Mutter 44.3-1`
- GPU driver and version
`Mesa Gallium driver 23.3.0-devel for AMD Radeon RX 6750 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.4.11-zen2-1-zen)`
- Possible screenshot or video of visual glitches
`Nope`
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. Add `RADV_PERFTEST=video_decode` in `/etc/environment` and log out.
2. Log in again.
3. `mpv --vo=gpu-next --no-config --gpu-api=vulkan --gpu-context=waylandvk --hwdec=vulkan <sample>`

### Expected behavior
Hardware decoding enabled.
### Actual behavior
Software decoding.
VAAPI works.
### Log file

[vulkan_fail.txt](https://github.com/mpv-player/mpv/files/12390251/vulkan_fail.txt)

### Sample files

Any H264 video.

**Comment by philipl** [comment]
You need to additionally pass `--msg-level=ffmpeg=debug` to get the details on why it failed to initialise.

**Comment by laichiaheng** [comment]
> You need to additionally pass `--msg-level=ffmpeg=debug` to get the details on why it failed to initialise.
Here is a new log file.
[test2.txt](https://github.com/mpv-player/mpv/files/12391823/test2.txt)

**Comment by laichiaheng** [comment]
After building MPV with the 'mpv-full-build-git' in AUR, it works!
