### ISSUE TITLE
Some nitpicking about stats.lua

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [mpv-player/mpv#12215]
- Top margin of pages not same
  ![屏幕截图 2023-08-21 164049](https://github.com/mpv-player/mpv/assets/50797982/160f41b2-d19c-4388-94ad-c9df543efcad)
  ![屏幕截图 2023-08-21 164057](https://github.com/mpv-player/mpv/assets/50797982/ddc1b71f-9539-4756-9ae0-2af1c74ad9a8)
  ![屏幕截图 2023-08-21 164106](https://github.com/mpv-player/mpv/assets/50797982/b0f875de-af36-49c5-bea1-388e77173850)
  ![屏幕截图 2023-08-21 164114](https://github.com/mpv-player/mpv/assets/50797982/f51b8f55-112d-4500-a7f9-7c67738365a0)
- Show prompt for pages
  There is no clear prompt to turn pages, I think many users don't know that stats has multiple pages.
  Maybe add 1, 2, 3, 4 with titles on top?
- Show list of glsl-shaders, just like vf
  https://github.com/he2a/mpv-scripts/blob/main/scripts/sview.lua
- Show indicator of --deinterlace
  When this enabled by accident, performance and picture quality suffer greatly, but there is no easy way to know if it is turned on.
- Typo, from Scaled Resolution /n Window Scale to Scaled Resolution (Window Scale)
  e.g. Scaled Resolution: 1600x900 (0.8x)
- Typo, from Pixel Formats \n Primaries, Colormatrix, Levels \n Gamma to Pixel Formats, Colormatrix \n Primaries, Gamma, Levels
  Also reword "HDR peak" to "MaxLum"

**Comment by kasper93** [comment]
@natural-harmonia-gropius: Some changes https://github.com/mpv-player/mpv/pull/12249 that I like. For the reset I don't really know how to nicely display pages and keys to them. Sharder list is mostly on frame timings page. I don't think there is vertical space to list them on main page.
