### ISSUE TITLE
GPU usage with user shaders increased from ~55% to ~90% with 20230820 Shinchiro build

### ISSUE THREAD

**Issue by Jules-A** [mpv-player/mpv#12227]
### Important Information

Provide following Information:
- mpv version - mpv-x86_64-v3-20230823-git-af9b53f
- Windows Version - Windows 10 22H2 (19045.3324)
- Source of the mpv binary - Shinchiro
- If known which version of mpv introduced the problem - 20230820 build is the regressor, builds before that are fine..

### Reproduction steps

[mpv.conf.txt](https://github.com/mpv-player/mpv/files/12416106/mpv.conf.txt)

Tested with 1080p source/shaders.

Modified shaders: Antiring = Clamp_Highlights, Thin_HQ3 = STRENGTH 0.09  ITERATIONS 5.

### Expected behavior

Around 55% GPU usage so video doesn't stutter when other apps require GPU use.

### Actual behavior

Around 90% GPU usage.

### Log file
[mpv OLD build.log](https://github.com/mpv-player/mpv/files/12416119/mpv.OLD.build.log) (~50% usage)

[mpv NEW build.log](https://github.com/mpv-player/mpv/files/12416131/mpv.NEW.build.log) (~85% usage)

### Sample files

Seems to occur on any file, though only tested anime.

If I had to guess it's probably  "split texel transfers into slices" PR but haven't had time to test all builds.

EDIT: After checking logs it looks like it's trying to load my 540p shader profile as well?? I'm really not too sure about how logs are handled but that's what it looks like.
EDIT2: After commenting out other profiles, I can rule out extra shaders being applied.
EDIT3: Tested more builds, 20230820-git-19384e0 is the regressor.

**Comment by haasn** [comment]
Can you post a screenshot of the stats page 2 (timing graphs) for each build?

**Comment by Jules-A** [comment]
> Can you post a screenshot of the stats page 2 (timing graphs) for each build?

<details>
  <summary>Old</summary>

![oldbuild](https://github.com/mpv-player/mpv/assets/1760158/ae95e97b-15ab-46d2-a1e5-c42ea1c03ee1)

</details>


<details>
  <summary>New</summary>

![newbuild](https://github.com/mpv-player/mpv/assets/1760158/804bb14b-2652-4983-8b33-df6ef7026a32)

</details>

**Comment by haasn** [comment]
> EDIT3: Tested more builds, 20230820-git-19384e0 is the regressor.

The libplacebo version in this build would be more useful to know, can you check the verbose log for the line starting with "libplacebo version:"?

**Comment by Jules-A** [comment]
> The libplacebo version in this build would be more useful to know, can you check the verbose log for the line starting with "libplacebo version:"?

GOOD:

[cplayer] mpv v0.36.0-120-g152a95f2 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Aug 19 2023 00:46:44
[cplayer] libplacebo version: v6.292.0-178-g643850d-dirty
[cplayer] FFmpeg version: N-111790-g7e246a5db


BAD:

[cplayer] mpv v0.36.0-131-g19384e07 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Aug 20 2023 00:20:28
[cplayer] libplacebo version: v6.292.0-187-ge78c351-dirty
[cplayer] FFmpeg version: N-111791-g8c789c5da

**Comment by haasn** [comment]
> Weird, that doesn't include the sliced texel PR so I suspect it's not libplacebo but https://github.com/mpv-player/mpv/commit/d2082841df8bc39c585fc9d4be6498d1a296fed8 instead and https://github.com/mpv-player/mpv/commit/2791eb64e8526b97cef4f7c9a907f665b55e199a isn't properly clearing hooks?

Sounds like a good candidate, then. All of those libplacebo commits are basically purely cosmetic changes.

**Comment by haasn** [comment]
Fixed by #12262
