### ISSUE TITLE
Support for cropping videos with hardware decoding enabled

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#12222]
### Expected behavior of the wanted feature

On a MacBook Air M1 with the latest macOS and the latest Git HEAD, it seems not possible to crop videos without disable hardware decoding. This is curious since you can do more advanced things like adjust gamma (and obviously scaling).

Shouldn’t mpv be able to add any effect if using hw decoding (*assuming* they are applied after frame is decoded?) To clarify possible technical limitations, can someone give a simplified explanation of the video pipeline? I assume:

1. Configure GPU (ie. set target width/height and other parameters)
2. Read frame from video stream
3. Feed frame to GPU
4. Fetch decoded frame from GPU
5. Apply effects to frame buffer (brightness, etc.)
6. Send frame buffer to operating system, which in turn renders it in a window (or full screen)

### Alternative behavior of the wanted feature

N/A

### Log file

N/A

**Comment by forthrin** [comment]
1. Link to documentation for this feature?
2. It doesn't seem to work. (OSD does say "videotoolbox-copy", but same CPU hogging as with `hwdec=no`.)

**Comment by sfan5** [comment]
> it seems not possible to crop videos without disable hardware decoding.

What have you tried? Why didn't that work (error messages etc.)?

**Comment by forthrin** [comment]
Oh, so brightness, contrast gamma, etc. is done on the GPU? If so, I understand.

Strange though, that the GPU supports this and not cropping.

Does the limitation to most GPUs, or more specific to macOS / videotoolbox / GPUs embedded in Apple products?

**Comment by kasper93** [comment]
> Does implementation belong in FFmpeg?

Should be extended here:
https://github.com/mpv-player/mpv/blob/af9b53f3a3831531504906882efce0d979506ed3/video/out/vo.c#L1251-L1268
Basically setting `out_src` to the crop that we would like.

**Comment by forthrin** [comment]
@kasper93: Interesting! Is this a minor fix (few lines of code), or something that needs extensive care, testing, etc.?

**Comment by kasper93** [comment]
There is little bit of math to handle correctly. I actually hacked something together and it kinda works, but not fully.

**Comment by forthrin** [comment]
@kasper93: It would be a real benefit to mpv to have this feature. What kind of math is involved? Isn't cropping just simple arithmetic? Could you post the code to have others weigh in how to reach something to commit?

**Comment by kasper93** [comment]
@forthrin You can test with those changes https://github.com/mpv-player/mpv/pull/12246 `--video-crop w:h:x:y` will crop and wil work with hwdec. Not sure with mac vo, but if pan-n-scan works this should too.

**Comment by forthrin** [comment]
@kasper93: Great! I'm really looking forward to testing this. Which Git CLI command will apply your changes as a branch in the `mpv-build/mpv` folder in order to build and try them?

**Comment by forthrin** [comment]
@kasper93: Tested just now and seems to work instantly and flawlessly as expected. A great, new and very useful feature to the number one video player. Thanks for chipping in the necessary lines of code to make this happen.

A potential user gotcha is two differences to `-vf crop`:

1. The syntax is `WxH+X+Y`, rather than `iw:ih:x:y`
2. Leaving out offset values has gravity north-east rather than center.

**Comment by Dudemanguy** [comment]
>The syntax is WxH+X+Y, rather than iw:ih:x:y

This is my fault... I'm used to cropping with imagemagick.

**Comment by kasper93** [comment]
> This is my fault... I'm used to cropping with imagemagick.

After all we changed to `m_geometry`. At least we are consistent.

> Leaving out offset values has gravity north-east rather than center.

Actually I was aiming for this from the start. Works as intended, but indeed maybe I should change it, if nothing else for compatibility with vf=crop.

**Comment by forthrin** [comment]
@Dudemanguy: I'm well versed with IM too. The number separators could be non-digit really (or at least any of `[x+:]`), and I do think centering will make life a lot easier, so I support the change for consistency and simplicity.

**Comment by forthrin** [comment]
@Dudemanguy: Did you update the code to be center-oriented by default, and accept colons as separators?

**Comment by Dudemanguy** [comment]
>center-oriented by default

Yes.

>accept colons as separators

No.

**Comment by forthrin** [comment]
What a relief to update and see the prior working. What's the rationale for holding out on the latter?

**Comment by forthrin** [comment]
Some experiences with this functionality after a few weeks...

When trying to change the `video-crop` property run-time things go awry:

```
$ mpv --video-crop=800x800 1080p.mp4
mp.set_property('video-crop', '1920x1080')
[vo/libmpv] Ignoring invalid --video-crop= for 1920x640 image
(flood)
```

A similar thing happens if applying a `-vf scale` or `-vf crop´ smaller than `--video-crop`.

1. Is the prior a bug, or how does one change `--video-crop` run-time?
2. Suggest to make `--video-crop` resilient to smaller sizes (silently rounding them to the available area).
3. Is there any way to make the `+x+y` values relative to the gravitation (center)? Since they are absolute (relative to top-left), you have to do head math (`(window.width - video.width)/2`), and then add your value to that.

**Comment by kasper93** [comment]
> Is the prior a bug, or how does one change --video-crop run-time?

What is? `1920x1080` crop is invalid for `1920x640` image. And this is what mpv told you.

> Suggest to make --video-crop resilient to smaller sizes (silently rounding them to the available area).

Why? Just fix your script/command line.

> Is there any way to make the +x+y values relative to the gravitation (center)? Since they are absolute (relative to top-left), you have to do head math ((video.width - window.width)/2), and then add your value to that.

No. Current version is compatible with vf cropdetect output and will stay this way.

> Related side note: Shouldn't --hidpi-window-scale affect --geometry as well as --window-scale?

Open new issue, if you have suggestions for improvements.

**Comment by forthrin** [comment]
1. Video is 1920x1080 (indicated by filename). No idea where it gets "640" from, so seems like a bug. Will open issue.
2. Why is nudging too large crop values a bad thing? And why is warning about them a good thing?
3. OK
4. Will open issue

**Comment by forthrin** [comment]
1. Found this to be a mistake.
2. #12587 addresses this. Continuing the conversation there.
3. -
4. Opened as #12588
