### ISSUE TITLE
Support subtitle filtering via text parsing proficient language

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#12229]
### Expected behavior of the wanted feature

https://github.com/mpv-player/mpv/blob/master/sub/filter_sdh.c

Since manipulating strings with C is like trying to hit a nail with a banana, I'd like to propose support for parsing subtitles via a language suitable for easy string handling (ie. built-in regexp, concatenation, termination, memory safety, etc.)

This would make it so much easier for users to extend/improve/tweak subtitle filters.

It seems the obvious built-in default for implementing the existing filter would be a Lua script, since mpv is already dependent on this language, but the user could call any parser/script by a setting in `mpv.conf` (perl, Ruby, etc.)

### Alternative behavior of the wanted feature

N/A

### Log file

N/A

**Comment by Dudemanguy** [comment]
`--sub-filter-regex` and `--sub-filter-jsre` already exist. What are you asking for exactly?

**Comment by forthrin** [comment]
I just might have come down with a mild case of RTFM here. Will check out and report back if it fits all needs

I assume there is no support for:

1. Dedicated scripts? (Filters would have to be entered as a bunch of append statements in `mpv.conf`?)
2. *Changing* text? (Only removing)
3. Writing the parsed subtitles back to a `.srt` file on disk?

**Comment by Dudemanguy** [comment]
Scripts can set those options at any time. Changing text and writing subtitle files seems way out of scope.
