### ISSUE TITLE
Can we specify more than one lavf format?

### ISSUE THREAD

**Issue by bobbybudnick** [mpv-player/mpv#12224]
I am trying to capture both audio and video from a USB HDMI capture device.

I need to convert first to mjpeg to go from 5 fps to 30 fps on the video capture: 
mpv --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video0 --audio-file=av://alsa:plughw:2,0
which results in an audio error but video capture works:
video4linux2,v4l2: Cannot open video device plughw:2,0: No such file or directory
[lavf] avformat_open_input() failed
Can not open external file av://alsa:plughw:2,0.
 (+) Video --vid=1 (mjpeg 1280x720 30.000fps)
VO: [gpu] 1280x720 yuvj422p
V: 00:00:05 / 00:00:05 (96%)
[ffmpeg/demuxer] video4linux2,v4l2: Some buffers are still owned by the caller on close.

The problem seems to be that video4linux2 is trying to decode the "audio-file" portion of the command when the lavf "alsa" format is needed to do this.  

Putting a comma and alsa behind video4linux2:
mpv --demuxer-lavf-format=video4linux2,alsa --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video0 --audio-file=av://alsa:plughw:2,0
which results in a demuxer error:
[lavf] Unknown lavf format [video4linux2,alsa]
Failed to recognize file format.
Exiting... (Errors when loading file)

Even when using the IPC functionality along with audio-add I cannot understand how to manipulate the lavf format options.  2 separate instances of mpv for audio and video go out of sync with each other so that appears to not be an option with this capture device either.  What can I do to move forward?

**Comment by Traneptora** [comment]
> I need to convert first to mjpeg to go from 5 fps to 30 fps on the video capture:

Why?

**Comment by Traneptora** [comment]
> mpv --demuxer-lavf-format=video4linux2,alsa --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video0 --audio-file=av://alsa:plughw:2,0

```
mpv '--{' --demuxer-lavf-format=video4linux2 av://v4l2:/dev/video0 '--}' --audio-file=av://alsa:plughw:2,0
```
