### ISSUE TITLE
Freezes while playing HDR Video 60fps

### ISSUE THREAD

**Issue by sweet-watermelon** [mpv-player/mpv#12233]
### Important Information

- mpv version v0.36.0
- macOS 13.5 - Macbook Pro 16 M1 PRO

### Reproduction steps

I use IINA for playing video, but latest version of mpv also have this problem, i am not using MPV in real life but tested in it before create issue. 

### Expected behavior

Playing video without any freezes

### Actual behavior

Video freeze while playing. Infuse and VLC (without HDR) playing without any freezes. 

### Log file
Nothing special. 

### Sample files

Sorry could not upload to 0x0 because file size larger than 500mb. 

File: https://drive.google.com/uc?export=download&id=1H7gTjX76C60DYlVKPw01B0hK5lrSKL66

LG Chess is a promotional video, in Ultra-HD HDR, for LG 4K TVs.
 
Video Info:
Resolution : 3840 x 2160
File size : 842 MB
Duration : 00:01:53
Format : MP4
Codec : HEVC
Overall bit rate : 62 Mb/s
Bit depth : 10 bits
Frame rate : 60 fps

**Comment by CounterPillow** [comment]
>### Log file
> Nothing special.

You're not the one who is to judge that. Provide a log file.

**Comment by Traneptora** [comment]
> Log file
> Nothing special.
