### ISSUE TITLE
make dark areas more stable

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12234]
Hi, recently I noticed something that I can't unsee
The darkest parts of the image are very "noisy". In fact that is so distracting that I'm only seeing this wobbling shadow mess.
I don't know if there is a mpv function (ffmpeg) that tackle this, or maybe a glsl shader. I would just like to have a stable image.
And this don't really makes sense, that everything in front (lighter regions) is "normal/stable" and the shadows are dancing macarena ^^
In video games there is something like temporal anti aliasing, which takes multiple frames and blends them together, I think that this could kinda help here to smooth this out. When only applied to the darkest regions (srgb 0-26 brightness levels)

This is what it looks like, for demonstrating purposes I boosted the gamma

![demo 1](https://github.com/mpv-player/mpv/assets/139760266/44f69bf0-5e4e-4e45-881c-c736be5694c7)

**Comment by Traneptora** [comment]
It looks like it's an issue with the source itself. You can try enabling temporal dithering with `--temporal-dither=yes`.

**Comment by geextahslex** [comment]
I already tried that, doesn't seem to make a difference

**Comment by geextahslex** [comment]
What kinda helped:

deband=yes
deband-iterations=1
deband-threshold=55
deband-range=20
deband-grain=5

dither-depth=8
dither=fruit

**Comment by monarc99** [comment]
you could try something like this:

glsl-shaders='~~/shaders/LQ/hdeband.glsl:~~/shaders/LQ/nlmeans_light_sharpen_denoise.glsl'
from
https://github.com/AN3223/dotfiles/tree/master/.config/mpv/shaders

**Comment by geextahslex** [comment]
I tried it but I'm on a iGPU and I get like 5 FPS ^^, but thanks anyway
