### ISSUE TITLE
Add possibility to view videos in ProRES quality format (Add player compatibility)

### ISSUE THREAD

**Issue by mayconhvab1** [mpv-player/mpv#12231]
Released a while
ProRES is a video quality generated in several formats that can be viewed in .mkv, .mp4, .webm, .m2ts and other compatible video formats
It is from Apple and can be purchased through the new FFmpeg master builds, the only software I know of that has the ability to play the video format in ProRES is VLC Media Player, but I would really like other playback software to audio and video had this support for this format, as it goes far beyond RGB16 and YUV 4:4:4, making the video contrast quality more vivid and sharper
You can get it in AV Batch Converter software with latest FFmpeg but with mpv 0.36 it doesn't have the ability to play these advanced color video formats sRGB and FULL RGB so to speak in picture style like Photoshop or a raw video
I would like you to add this video format as the quality is exceptional and rewarding for those who use it, but the file size converted with FFmpeg to ProRES can be above 5GB if it is a 2 or 3 minute video clip.
You can view more ProRES information at: https://trac.ffmpeg.org/wiki/Encode/VFX
And also at: https://en.wikipedia.org/wiki/Apple_ProRes (With more extensive quality and different resolutions)
Thank you very much my dear developers, mpv player is a great player and I wish that great audio and video qualities and formats can be added to it.
Thank you very much in advance

**Comment by Isaacx123** [comment]
mpv can play ProRES files just fine.

**Comment by mayconhvab1** [comment]
> mpv pode reproduzir arquivos ProRES perfeitamente.

Yes, you can reproduce it, but I believe not in the same colors that exist in the video formats
For example, if you convert a video that you downloaded from YouTube and convert it to ProRES and play it back in VLC and in mpv, you may notice that the quality in the mpv is not normal, that is, it is not as standard as the video itself, when convert
I think there is a huge difference between HDR 10, RGB, sRGB and YUV 444, or other qualities that it is rare for a video player to play normally and without stuttering

**Comment by Isaacx123** [comment]
>For example, if you convert a video that you downloaded from YouTube and convert it to ProRES

Why would you ever do that? 😂🤦‍♂️

Here, download a real ProRES video and do your tests again:
`wget http://download.opencontent.netflix.com.s3.amazonaws.com/SolLevante/hdr10/SolLevante_HDR10_r2020_ST2084_UHD_24fps_1000nit.mov`

**Comment by Isaacx123** [comment]
Well the issue can be closed then.

Like I said, mpv can play ProRes files just fine:

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/75648063/ad284a35-caa6-4291-9212-45336dc4cc51)

`mpv --no-config --vo=gpu-next --profile=gpu-hq --screenshot-format=png --screenshot-high-bit-depth=no --autofit=1920x1080 --log-file=mpv.log SolLevante_HDR10_r2020_ST2084_UHD_24fps_1000nit.mov`


Log file:
[mpv.log](https://github.com/mpv-player/mpv/files/12422657/mpv.log)
