### ISSUE TITLE
Add support for more audio, video and stream formats available in ffmpeg and ffmplay

### ISSUE THREAD

**Issue by mayconhvab1** [mpv-player/mpv#12230]
hello dear developers
I would like the mpv player to add support for the audio and video formats present in ffmpeg and ffmplay, giving the possibility to also play in GUI using the master versions of FFmpeg present on the official FFmpeg website.
Thus, enabling audio, video and some formats or if possible a large part of streams, it is also possible to add support for ffmpeg and ffmplay as audio and video formats for Windows, Linux and MacOS, I noticed that the mpv player has great support for video and audio formats, making it possible to play them, but I would like this to be more amplified, generating support for audio and video containers with greater qualities and metadata information and codecs present in each format.
Thank you very much in advance
Thank you very much

**Comment by CounterPillow** [comment]
ok?
