### ISSUE TITLE
property time-remaining returning -0.000000 at end of audio file

### ISSUE THREAD

**Issue by Funami580** [mpv-player/mpv#12247]
### Important Information

- mpv version: 0.36.0
- Platform and Version: Artix Linux
- Source of the mpv binary: Artix Linux Repository

### Reproduction steps

Open this file https://send.ephemeral.land/download/1643644c0c2b471e/#vE9wwIGVQxXPMiktjcdV2g. Go to the end, the osc should now show as remaining time "--00:00:00", notice the double minus.

### Expected behavior

Shows "-00:00:00"

### Actual behavior

Shows "--00:00:00"

### More information

Can be found here: https://github.com/mpv-player/mpv/pull/12243

### Sample files

https://send.ephemeral.land/download/1643644c0c2b471e/#vE9wwIGVQxXPMiktjcdV2g

**Comment by llyyr** [comment]
#12248 should've fixed this when seeking to EOF while paused. However, this issue still exists when reaching EOF while playing through the file normally.

As a bonus, the time-pos is also negative at the start when --loop is used and the file loops through with --no-audio-display

**Comment by llyyr** [comment]
Related question, were you using ao_pipewire or ao_pulse or something else?

**Comment by Funami580** [comment]
ao_pipewire

**Comment by Dudemanguy** [comment]
060adf680627586306716f645f240b5df46d4f0b should have fixed this specific issue which was caused by durations not being reported with enough precision. Note that you can get still get -0.00000 for other reasons like with push-based AOs #12322.

**Comment by Funami580** [comment]
Thanks @llyyr !
