### ISSUE TITLE
Playing back LOG/SLOG3/SLOG2/FLOG2 footage in MPV with a LUT

### ISSUE THREAD

**Issue by rgaufman** [mpv-player/mpv#12242]
When you play back LOG footage recorded by a mirrorless camera, it looks really flat and unwatchable. The manufacturers provide LUTs (Look up Tables) that turn this flat footage into REC.709 footage. These LUTs can be loaded in video editing software like Final Cut, Resolve, Premiere etc to make the footage look "normal".

I am not able to find a way to do this with MPV?

### Expected behavior of the wanted feature

For LOG footage to look "normal" using a manufacturer provided LUT.

**Comment by kasper93** [comment]
What format are those LUT files? Have you tried `--lut=<file> --lut-type=native`? 

```
--lut=<file>
    Specifies a custom LUT (in Adobe .cube format) to apply to the colors as part of color conversion. The exact interpretation depends on the value of --lut-type. (Only for --vo=gpu-next)
--lut-type=<value>

    Controls the interpretation of color values fed to and from the LUT specified as --lut. Valid values are:

    auto
        Chooses the interpretation of the LUT automatically from tagged metadata, and otherwise falls back to native. (Default)
    native
        Applied to raw image contents in its native RGB colorspace (non-linear light), before conversion to the output color space.
    normalized
        Applied to the normalized RGB image contents, in linear light, before conversion to the output color space.
    conversion
        Fully replaces the conversion from the image color space to the output color space. If such a LUT is present, it has the highest priority, and overrides any ICC profiles, as well as options related to tone mapping and output colorimetry (--target-prim, --target-trc etc.).
```

**Comment by thisisreallife** [comment]
> What format are those LUT files? Have you tried `--vo=gpu-next --lut=<file> --lut-type=native`?
> 
> ```
> --lut=<file>
>     Specifies a custom LUT (in Adobe .cube format) to apply to the colors as part of color conversion. The exact interpretation depends on the value of --lut-type. (Only for --vo=gpu-next)
> --lut-type=<value>
> 
>     Controls the interpretation of color values fed to and from the LUT specified as --lut. Valid values are:
> 
>     auto
>         Chooses the interpretation of the LUT automatically from tagged metadata, and otherwise falls back to native. (Default)
>     native
>         Applied to raw image contents in its native RGB colorspace (non-linear light), before conversion to the output color space.
>     normalized
>         Applied to the normalized RGB image contents, in linear light, before conversion to the output color space.
>     conversion
>         Fully replaces the conversion from the image color space to the output color space. If such a LUT is present, it has the highest priority, and overrides any ICC profiles, as well as options related to tone mapping and output colorimetry (--target-prim, --target-trc etc.).
> ```

where to specify this command in VLC, like `perference -> video -> filters` ?

**Comment by rgaufman** [comment]
--lut= indeed works beautifully, I added this to my .zshrc to quickly play with a lut when I run mpvl file:

```
mpvl() {
  mpv --lut='/Users/hackeron/SGamut3CineSLog3_To_LC-709.cube' "$@"
}
```
