### ISSUE TITLE
profile condition only for youtube/online streams

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12255]
Hi,
I'm looking for a descent way to have a profile that only triggers when youtube or any online stream is running.
The best I came up with was "profile-cond=string.match(p.filename, "watch")~=nil", all youtube links have "watch" in them but this isn't ideal, when you want to watch for example "watchmen" ^^
Any suggestions?

Thank you

**Comment by llyyr** [comment]
`profile-cond=demuxer_via_network`

**Comment by geextahslex** [comment]
Thank you, that worked
