### ISSUE TITLE
gpu-next: gamut mapping still needs further improvement

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#12259]
### Important Information

Provide following Information:
- mpv version: 32be726
- Windows Version: Win11 22H2
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild/releases
- If known which version of mpv introduced the problem

### Reproduction steps

Use `--no-config --vo=gpu-next` to open the following sample file.

### Expected behavior

the new gamut mapping works well.

### Actual behavior

The new gamut mapping looks fade and has artifacts.
`gamut-mapping-mode=auto`
![image](https://github.com/mpv-player/mpv/assets/61936050/a297d113-1bb8-4312-9b24-8b9e555e6c91)

`gamut-mapping-mode=clip`
![image](https://github.com/mpv-player/mpv/assets/61936050/061ee6bb-b275-4342-9437-6e4c41d99d38)

shader(hdr-toys): https://github.com/natural-harmonia-gropius/hdr-toys
![image](https://github.com/mpv-player/mpv/assets/61936050/80ac70b9-0cb3-47b4-99fc-dc818febfe3a)

madvr
![image](https://github.com/mpv-player/mpv/assets/61936050/97c75b1a-87ab-4456-abc1-2fe91ecd8c5d)

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/12445795/mpv.log)

### Sample files

https://0x0.st/H9yQ.396.mkv

**Comment by haasn** [comment]
Maybe `--libplacebo-opts=perceptual_deadzone=0.5` is more to your liking?

It's possible we could increase the default deadzone size

**Comment by dyphire** [comment]
> Maybe `--libplacebo-opts=perceptual_deadzone=0.5` is more to your liking?

I'm not sure if this is a matter of preference.
`--libplacebo-opts=perceptual_deadzone=0.5`
![image](https://github.com/mpv-player/mpv/assets/61936050/a9a22daf-c170-4369-a1c6-de6162c4bfbc)
As you can see, some parts of the screen look strange.

**Comment by haasn** [comment]
> > Maybe `--libplacebo-opts=perceptual_deadzone=0.5` is more to your liking?
> 
> I'm not sure if this is a matter of preference. `--libplacebo-opts=perceptual_deadzone=0.5` ![image](https://user-images.githubusercontent.com/61936050/263474127-a9a22daf-c170-4369-a1c6-de6162c4bfbc.png) As you can see, some parts of the screen look strange. Excluding this, it does look closer to clip.

Seems to disappear at even higher deadzone values (e.g. 0.80). But now we might be clipping other, less extreme samples.

**Comment by dyphire** [comment]
> > > Maybe `--libplacebo-opts=perceptual_deadzone=0.5` is more to your liking?
> > 
> > 
> > I'm not sure if this is a matter of preference. `--libplacebo-opts=perceptual_deadzone=0.5`
>
> Seems to disappear at even higher deadzone values (e.g. 0.80). But now we might be clipping other, less extreme samples.

Yes, `--libplacebo-opts=perceptual_deadzone=0.8` almost the same as clip.
 
> Edit: e.g. atomic blonde sample seems to clip above 0.7 or so

So, I still believe that the new gamut mapping is worth further improvement to handle these extreme videos correctly.

**Comment by haasn** [comment]
So, the problem with this scene is that the 'dark patch' is somehow much, much closer to being maximally saturated than the brighter regions surrounding it (pictured is graph of `C / Cmax` where Cmax is the maximum possible chromaticity for the given hue):

![problem](https://github.com/mpv-player/mpv/assets/1149047/24350934-06e8-4079-a9c7-a8a2aae35b63)

So the current deadzone logic, which is designed to protect not-so-saturated colors while mapping strongly saturated colors, falls flat on this sample because this region sticks out like a sore thumb on the `C / Cmax` graph.

**Comment by haasn** [comment]
> So the current deadzone logic, which is designed to protect not-so-saturated colors while mapping strongly saturated colors, falls flat on this sample because this region sticks out like a sore thumb on the `C / Cmax` graph.

Seems like it happens from subtle variation of hue:
![problem-hue](https://github.com/mpv-player/mpv/assets/1149047/7d18af2b-4764-4549-997e-21515eae628b)

Which leads to vastly different value of maxC:
![problem-maxC](https://github.com/mpv-player/mpv/assets/1149047/8bb93d54-1279-46f5-b968-dc363bebd26d)

**Comment by haasn** [comment]
Problem can sort of be seen in this graph, it is the 'discontinuity' in the direction of the line going from red to yellow:

![problem-graph](https://github.com/mpv-player/mpv/assets/1149047/38c4fb70-ab55-4418-aa27-e048a26d495b)

If we can figure out a way to reformulate 'perceptual' to avoid these issues it would be a lot cleaner, and allow us to use larger deadzone without the issues you ran into.

**Comment by haasn** [comment]
Pushed some changes that help a bit with this scene to https://code.videolan.org/videolan/libplacebo/-/merge_requests/550

Old
![old](https://github.com/mpv-player/mpv/assets/1149047/dc69811b-9cba-4261-bf39-e0f436d3ad5e)

New
![new](https://github.com/mpv-player/mpv/assets/1149047/7a2a362e-7bd2-4091-a6e0-6354f6e359ae)

It may be possible to increase the perceptual deadzone even further after this change, without regressing that ugly orange patch too much.

**Comment by dyphire** [comment]
> Pushed some changes that help a bit with this scene to https://code.videolan.org/videolan/libplacebo/-/merge_requests/550
> 
> New ![new](https://user-images.githubusercontent.com/1149047/263478909-7a2a362e-7bd2-4091-a6e0-6354f6e359ae.jpg)
> 
> It may be possible to increase the perceptual deadzone even further after this change, without regressing that ugly orange patch too much.

This seems to have improved a lot.

**Comment by haasn** [comment]
Great, then I'll merge it for now. I'll wait for some more feedback from the usual suspects before tuning it further. Possibly we can bump the deadzone up to 0.40 in the future, though I'm worried about this breaking blue/cyan patterns.

If red is the most strongly saturated color in ICtCp, cyan is the least saturated one.

**Comment by dyphire** [comment]
> Great, then I'll merge it for now. I'll wait for some more feedback from the usual suspects before tuning it further. Possibly we can bump the deadzone up to 0.40 in the future, though I'm worried about this breaking blue/cyan patterns.
> 
> If red is the most strongly saturated color in ICtCp, cyan is the least saturated one.

Maybe we can use the video mentioned there to test the performance of blue saturation: https://github.com/mpv-player/mpv/issues/11599#issuecomment-1513486876

https://4kmedia.org/sony-whale-in-tonga-hdr-uhd-4k-demo/
