### ISSUE TITLE
--hdr-compute-peak has no effect when --target-peak is greater than or equal to file's metadata peak

### ISSUE THREAD

**Issue by NotMithical** [mpv-player/mpv#12252]
### Important Information

- mpv version: 0.36.0-165-gce799764
- Windows Version: Windows 10 22H2, build 19045.3391
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild
- Possible screenshot or video of visual glitches:

Showing metadata peak:
![mpvpeak 1000 stats 1](https://github.com/mpv-player/mpv/assets/95518825/4d353004-1c3d-474d-9678-16a70f5fd05e)

With --target-peak=1000:
![mpvpeak 1000 stats 2](https://github.com/mpv-player/mpv/assets/95518825/071aefcc-ca71-466e-a22e-ae0103ca4e6e)

With --target-peak=999:
![mpvpeak 999 stats 2](https://github.com/mpv-player/mpv/assets/95518825/fa89fcaf-a705-49f7-bdf1-05b2cef72d8f)

### Reproduction steps

Attempt to play an HDR video in which measured peak exceeds metadata peak with --no-config --hdr-compute-peak=yes, and target-peak equal to or greater than the video metadata's reported peak, outputting to an HDR display.

### Expected behavior

MPV measures the peak brightness regardless of metadata and tonemaps accordingly.

### Actual behavior

Peak brightness is either not measured at all or is completely ignored, resulting in a blown out or clipped image.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/12444084/log.txt)

### Sample files

https://4kmedia.org/lg-chess-hdr-demo/
(I am aware that demo videos are bizarre when it comes to HDR grading. The issue shows itself elsewhere, its just particularly visible with this video.)

**Comment by haasn** [comment]
This is actually working as intended. If the source contains data significantly above its metadata peak (such as in this example), it is a badly mastered / broken sample.

You can use `--libplacebo-opts=tone_map_metadata=cie_y` to ignore HDR10 metadata and force peak detection.

**Comment by NotMithical** [comment]
> You can use --libplacebo-opts=tone_map_metadata=cie_y to ignore HDR10 metadata and force peak detection.

The results look exactly the same as before with this option.
Log file from running with --no-config --target-peak=1000 --hdr-compute-peak=yes --libplacebo-opts=tone_map_metadata=cie_y: [log.txt](https://github.com/mpv-player/mpv/files/12444379/log.txt)

**Comment by NotMithical** [comment]
Slight mistake. I *had* tested that option with --vo=gpu-next but accidentally used --vo=gpu when generating the log file. The issue persists even with --libplacebo-opts=tone_map_metadata=cie_y and --vo=gpu-next.

Here's the correct log.
[log.txt](https://github.com/mpv-player/mpv/files/12444563/log.txt)

**Comment by haasn** [comment]
Ah, I see, the check in `renderer.c` precludes even this option from overriding the fixed logic:

```c
    if (pass->img.color.hdr.max_luma <= pass->target.color.hdr.max_luma + 1e-6)
        goto cleanup; // no adaptation needed
```

So yeah, peak detection / TM is just always disabled if the static HDR10 peak is lower than the target peak. I'll change this logic, though the question remains open of what we should change it to:

Should we *always* enable peak detection for HDR sources, or only when HDR10 metadata is disabled?

**Comment by kasper93** [comment]
> Should we always enable peak detection for HDR sources, or only when HDR10 metadata is disabled?

Always unless there is dynamic metadata available (HDR10+ or DV). If peak detection is enabled, it should always take precedence over HDR10 static metadata, regardless of `--target-peak` value, which I believe is the problem in this report.

**Comment by dyphire** [comment]
> Should we _always_ enable peak detection for HDR sources, or only when HDR10 metadata is disabled?

I think peak detection should always be applied when `hdr-compute-peak` option is enabled. Isn't it because HDr10 static metadata is unreliable that users use this option to achieve dynamic tone mapping? And from a functional perspective, it should not be disabled peak detection after enabling this option.
