### ISSUE TITLE
Using libmpv can mpv cores share the same log file?

### ISSUE THREAD

**Issue by low-batt** [mpv-player/mpv#12250]
When using `libmpv` and creating multiple cores is it valid to specify the same file in the [log-file](https://mpv.io/manual/stable/#options-log-file) option for each core or must each core have its own log file?

Asking because [IINA](https://github.com/iina/iina) uses multiple cores and _very rarely_ the mpv log file was found to contain a large block of NUL characters (issue https://github.com/iina/iina/issues/4596). This was so rare that until now we could not reproduce it.

I decided to stress test logging. I set [msg-level](https://mpv.io/manual/stable/#options-msg-level) to `all=trace` and hacked the IINA code to simultaneously play the opened video in 10 windows with 10 mpv cores. This test is able to reproduce the problem. I did not attach a log as they are usually 500 MB.

In repeated tests I'm seeing this pattern where the huge block of NUL characters occurs before a log message from FFmpeg with an earlier timestamp:
```text
[  45.483][t][libmpv_render] pass 'color conversion + output to screen': last 40us avg 75us peak 1605us
[  45.483][t][libmpv_render] pass 'drawing osd': last 0us avg 0us peak 0us

--- Many NULs ---

[   7.915][t][ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 1, sample 6105, offset b6d2db, dts 6248448, size 263, distance 0, keyframe 1
[   7.916][t][ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 1, sample 6106, offset b6d3e2, dts 6249472, size 283, distance 0, keyframe 1
```

I am checking the log files for NULs using:
```text
find . -name 'mpv*.log' | xargs hexdump -C | grep -C 5 -E '^.* 00.*\|.*\|'
```

<details>
<summary><b>Searching for NULs:</b></summary>

```text
low-batt@gag 2023-08-25-16-33-43_PVHvW6$ find . -name 'mpv*.log' | xargs hexdump -C | grep -C 5 -E '^.* 00.*\|.*\|'
0021ae10  20 31 36 30 35 75 73 0a  5b 20 20 34 35 2e 34 38  | 1605us.[  45.48|
0021ae20  33 5d 5b 74 5d 5b 6c 69  62 6d 70 76 5f 72 65 6e  |3][t][libmpv_ren|
0021ae30  64 65 72 5d 20 70 61 73  73 20 27 64 72 61 77 69  |der] pass 'drawi|
0021ae40  6e 67 20 6f 73 64 27 3a  20 6c 61 73 74 20 30 75  |ng osd': last 0u|
0021ae50  73 20 61 76 67 20 30 75  73 20 70 65 61 6b 20 30  |s avg 0us peak 0|
0021ae60  75 73 0a 00 00 00 00 00  00 00 00 00 00 00 00 00  |us..............|
0021ae70  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00d97e40  00 00 00 00 00 00 00 00  00 00 00 00 00 00 5b 20  |..............[ |
00d97e50  20 20 37 2e 39 31 35 5d  5b 74 5d 5b 66 66 6d 70  |  7.915][t][ffmp|
00d97e60  65 67 2f 64 65 6d 75 78  65 72 5d 20 6d 6f 76 2c  |eg/demuxer] mov,|
00d97e70  6d 70 34 2c 6d 34 61 2c  33 67 70 2c 33 67 32 2c  |mp4,m4a,3gp,3g2,|
00d97e80  6d 6a 32 3a 20 41 56 49  6e 64 65 78 20 73 74 72  |mj2: AVIndex str|
00d97e90  65 61 6d 20 31 2c 20 73  61 6d 70 6c 65 20 36 31  |eam 1, sample 61|
low-batt@gag 2023-08-25-16-33-43_PVHvW6$ 
```
</details>

As a test I changed IINA to give each mpv core its own log file. With this change I have been unable to reproduce the problem. But the log messages are not properly distributed. All FFmpeg messages are written to the first file:

```text
low-batt@gag 2023-08-25-18-10-14_giTT8v$ ls -la
total 973104
drwxr-xr-x  13 low-batt  staff        416 Aug 25 18:10 .
drwxr-xr-x  19 low-batt  staff        608 Aug 25 18:10 ..
-rw-r--r--   1 low-batt  staff      91672 Aug 25 18:10 iina.log
-rw-r--r--   1 low-batt  staff  484646905 Aug 25 18:10 mpv0.log
-rw-r--r--   1 low-batt  staff    1098459 Aug 25 18:10 mpv1.log
-rw-r--r--   1 low-batt  staff    1068251 Aug 25 18:10 mpv2.log
-rw-r--r--   1 low-batt  staff    1051525 Aug 25 18:10 mpv3.log
-rw-r--r--   1 low-batt  staff    1038852 Aug 25 18:10 mpv4.log
-rw-r--r--   1 low-batt  staff    1023582 Aug 25 18:10 mpv5.log
-rw-r--r--   1 low-batt  staff    1017745 Aug 25 18:10 mpv6.log
-rw-r--r--   1 low-batt  staff    1013438 Aug 25 18:10 mpv7.log
-rw-r--r--   1 low-batt  staff    1009248 Aug 25 18:10 mpv8.log
-rw-r--r--   1 low-batt  staff    1009375 Aug 25 18:10 mpv9.log
low-batt@gag 2023-08-25-18-10-14_giTT8v$ 
```

### Log file

If you really want a 500 MB log file I can supply one.

**Comment by low-batt** [comment]
@kasper93 Closed? I guess that means it is ok for multiple cores to share the same log file and the block of NUL characters was a defect that was fixed by PR #13363? IINA is in the process of upgrading to 0.38.0. If I encounter blocks of NULs I will enter a proper bug report. So far I've not noticed anything, but this problem was rare.

**Comment by kasper93** [comment]
> Closed?

The issue tracker is not for questions or discussions.

> When using libmpv and creating multiple cores is it valid to specify the same file in the [log-file](https://mpv.io/manual/stable/#options-log-file) option for each core or must each core have its own log file?

This is the question for your OS vendor. There is nothing on (lib)mpv side to synchronize writes to a file from different instances of the context. So you might get interleaved output if things write to the same offset. I don't see why it would start writing NULs, but probably when there is seek during another thread write something goes "bad". I suspect the behavior would be different on linux.

Generally I would recommend gathering logs from all mpv instances and synchronizing the writes to a log file on IINA side.

 > If I encounter blocks of NULs I will enter a proper bug report.

Yes, please, with simple reproducible testcase.

**Comment by low-batt** [comment]
Back when I entered this the issue templates offered "question" as a choice. It was that template which applied the `meta:question` label.

If I encounter this again I will check into the expected macOS behavior before entering an issue.

If the OS behavior requires keeping separate logs for each core then the problem with mpv writing all FFmpeg related logs to the file of the first core would need to be addressed, assuming that is still a problem.
