### ISSUE TITLE
mpv via yt-dlp very slowly caching videos from youtube and other services, but pure yt-dlp downloading very fast.

### ISSUE THREAD

**Issue by ilya-indigo** [mpv-player/mpv#12254]
### Important Information
mpv 0.36.0+git.20230730.1bbc7a2c Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Jul 31 2023
libplacebo version: v6.292.1
FFmpeg version: 6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
openSUSE Tumbleweed
https://build.opensuse.org/package/show/multimedia:apps/mpv

### Reproduction steps
`~/.mpv/config`
```
hwdec=none
fs=yes
ytdl-format=bestvideo[height<=1080][fps<=?60][vcodec^=?avc]+bestaudio/best[height<=1080][fps<=?60][vcodec^=?avc]
```
The `--no-config` option has no effect on repeatability.
run mpv with any 1080p60 video (-f299+251), for example `mpv -f299+251 https://www.youtube.com/watch?v=dkihNga60tw`
Wait for 5-10 minutes of playback and observe the cached time.

### Expected behavior
The caching time should be constantly increasing, possibly up to a certain high limit. This has always been the case in the past.

### Actual behavior
For the first 5 minutes the caching works as it should, then it slows down a lot and then quickly depletes to zero and the caching speed is not enough for comfortable viewing.

### Log file
[mpv-log.txt](https://github.com/mpv-player/mpv/files/12444868/mpv-log.txt)

### Additional information ###
I can assume that mpv has nothing to do with it and it's either yt-dlp or youtube or my internet provider.
It's easy to check.
`yt-dlp -f'bestvideo[height<=1080][fps<=?60][vcodec^=?avc]+bestaudio/best[height<=1080][fps<=?60][vcodec^=?avc]' https://www.youtube.com/watch?v=dkihNga60tw`
```
[youtube] Extracting URL: https://www.youtube.com/watch?v=dkihNga60tw
[youtube] dkihNga60tw: Downloading webpage
[youtube] dkihNga60tw: Downloading ios player API JSON
[youtube] dkihNga60tw: Downloading android player API JSON
[youtube] dkihNga60tw: Downloading m3u8 information
[info] dkihNga60tw: Downloading 1 format(s): 299+251
[download] Destination: Indiana Jones and the Temple of Doom (NES) [dkihNga60tw].f299.mp4
[download] 100% of    5.25GiB in 00:09:56 at 9.01MiB/s
[download] Destination: Indiana Jones and the Temple of Doom (NES) [dkihNga60tw].f251.webm
[download] 100% of  174.25MiB in 00:00:18 at 9.18MiB/s
[Merger] Merging formats into "Indiana Jones and the Temple of Doom (NES) [dkihNga60tw].mkv"
```
`5.25GiB in 00:09:56 at 9.01MiB/s` 
I have a 100 MB connection and the average speed is close to the maximum connection speed.
So neither yt-dlp nor youtube nor my provider restricts access to youtube and other video services.
From this I conclude that something is wrong with mpv.
I started to notice such behavior about a month ago, before that it did not happen.

**Comment by llyyr** [comment]
Does `--ytdl-raw-options=format-sort="proto:m3u8"` help?

**Comment by ilya-indigo** [comment]
> Does `--ytdl-raw-options=format-sort="proto:m3u8"` help?
No, unfortunately adding the `ytdl-raw-options=format-sort="proto:m3u8"` option to the mpv config had no effect on playability.

**Comment by sfan5** [comment]
duplicate, see https://github.com/mpv-player/mpv/issues/8655#issuecomment-1199733728

**Comment by ilya-indigo** [comment]
I have a problem not only with youtube, but also with other video services.
Download and launch is not applicable to streaming and live broadcasts.
Why can't caching be hung on yt-dlp or make its own layer for that before ffmpeg?
Does the ffmpeg upstream know about the problem?

I realize that this sounds definitely not like an ffmpeg problem, since ffmpeg's job is encoding and decoding, not splitting requests into pieces to bypass video service limitations.
Maybe there is a layer in ffmpeg to take over the downloading, leaving ffmpeg only decoding?

**Comment by ilya-indigo** [comment]
P.S. I don't agree with closing this problem as the problem in mpv is not solved.
The problem is solved in yt-dlp, but mpv doesn't use that loading mechanism.
This is clearly not ffmpeg's problem, as its job is to decode, which it handles.
If ffmpeg's problem is that it is taking on a task that is not its own and does not provide an interface to implement this functionality on its own, then this problem should be reported to ffmpeg.

**Comment by ilya-indigo** [comment]
That's such a crutch...
```
u="video_url" && n="`yt-dlp -Otitle $u`" && f="/tmp/$n" && yt-dlp --max-filesize 1.8G --sub-langs 'en,ru' --embed-subs --embed-chapters --no-part -f'bestvideo[height<=1080][fps<=?60][vcodec^=?avc]+bestaudio/best[height<=1080][fps<=?60][vcodec^=?avc]' -o"$f" "$u" && mpv --slang=ru "$f"* && rm "$f"*
```

**Comment by Arc-2023** [comment]
also meeting the same problem,while i think tring use code like these help with a cracked aria2c.exe:
```conf
ytdl-raw-options-append=external-downloader=aria2c
ytdl-raw-options-append=downloader-args=aria2c:"-x 256 -k 128k"
```
But it doesn't.

**Comment by fidodido48** [comment]
Same here. Right now, there seems to be only 2 solutions to this -> precaching (and waiting) or downloading. 

There was a time when installing a mitm proxy: https://gist.github.com/ftk/253347b2c9a53bbd6087f086970106b6
helped to workaround this, but sadly it doesn't seem to be working anymore...

mpv.conf precache profile:
```
[ytdl_proxy]
profile-cond=http_proxy:match[[.]] and (path or [[]]):match[[youtu%.?be]]
input-commands=no-osd change-list ytdl-raw-options append proxy=${http-proxy}
cache-secs=1800
cache-pause-initial=yes
cache-pause-wait=30

```
