### ISSUE TITLE
vo=gpu-next Reconfiguring swapchain failed 

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12264]
Hi,
when starting videos this message appears, I don't know what this mean and is this something I should ignore?
![screen](https://github.com/mpv-player/mpv/assets/139760266/1c1d61e9-4810-4e1f-9999-614cfe21c06a)

**Comment by kasper93** [comment]
`DXGI_FORMAT_R10G10B10A2_UNORM ` backbuffer is not supported on your system. Nothing we can do, you can ignore this message.

**Comment by geextahslex** [comment]
Okay but what does this mean? is there any impact on the image quality?

**Comment by geextahslex** [comment]
Okay so this is kinda expected since I'm on a SDR TV, right?

**Comment by kasper93** [comment]
But if this format isn't available either d3d feature level is too low or Windows too old. It doesn't matter what output device is used.

**Comment by geextahslex** [comment]
Okay now I get it, thank you

**Comment by haasn** [comment]
Maybe we shouldn't print a warning if this is expected fallback behavior?
