### ISSUE TITLE
Vulkan core dump

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#12268]
### Important Information

Provide following Information:
- mpv version
```
mpv v0.36.0-180-g902bbdad35 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.292.0-231-g612071d5
FFmpeg version: N-111830-gc48ec95ba3
FFmpeg library versions:
   libavutil       58.17.100
   libavcodec      60.23.100
   libavformat     60.10.101
   libswscale      7.3.100
   libavfilter     9.11.100
   libswresample   4.11.100
```
- Linux Distribution and Version
Arch
- Source of the mpv binary
AUR
- If known which version of mpv introduced the problem
I don't know.
- Window Manager and version
Mutter 44.4
- GPU driver and version
`Mesa Gallium driver 23.3.0-devel for AMD Radeon RX 6750 XT (navi22, LLVM 18.0.0, DRM 3.52, 6.4.12-zen1-1-zen)`
`vulkan-radeon-git:1:23.3.0_devel.177071.5ce6e09ffc7-1`
- Possible screenshot or video of visual glitches
Nope

### Reproduction steps

mpv --no-config --gpu-api=vulkan <sample>

### Expected behavior
Play videos like before.
### Actual behavior
crash
### Log file

[vulkan.txt](https://github.com/mpv-player/mpv/files/12448391/vulkan.txt)

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by llyyr** [comment]
You need to provide a backtrace, or at least the message printed when mpv crashes and a range of versions where it's broken.

**Comment by Dudemanguy** [comment]
Are you building mesa from git master? They accidentally broke vulkan on wayland. Should be fixed by [this](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/24885).

**Comment by llyyr** [comment]
fd.o is down for a day I think, but that URL takes you to this patch https://0x0.st/H9Id.txt

**Comment by laichiaheng** [comment]
Is their gitlab website down?

**Comment by Dudemanguy** [comment]
mesa's website is still down annoyingly enough.

>It happens to mesa 23.1.6 from Arch official repo, too.

Are you positive? Did you try restarting your compositor after upgrading (or just restarting the computer)?

**Comment by laichiaheng** [comment]
> freedesktop's gitlab is still down annoyingly enough.
> 
> > It happens to mesa 23.1.6 from Arch official repo, too.
> 
> Are you positive? Did you try restarting your compositor after upgrading (or just restarting the computer)?

Yes, I have restarted my computer many times.

**Comment by laichiaheng** [comment]
> freedesktop's gitlab is still down annoyingly enough.
> 
> > It happens to mesa 23.1.6 from Arch official repo, too.
> 
> Are you positive? Did you try restarting your compositor after upgrading (or just restarting the computer)?

Oops, it only happens when I try to decode with --hwdec=vulkan.

**Comment by laichiaheng** [comment]
It is solved after building the latest mesa-git.
