### ISSUE TITLE
About watch_later

### ISSUE THREAD

**Issue by jack9603301** [mpv-player/mpv#12270]
I want to ask a question about the principle of mpv, which is related to the operation principle of watch_later. When I use the following command to open a playlist:

```
mpv .
```

Please note that I have set parameters in mpv.conf that it will save the position information of the playlist when it exits, so that it will be restored when the same playlist is opened next time.
However, I'm curious as to how it works because I see the following in the location `~/.local/state/mpv/watch_later`:

```
# ls
182EA0B818AFDA769ABF87D77C9DF092  7C95023CA3DEA41E2FDC74B439C5C355  9BB7B3F0CD2CF7615E6D437876F938EF  E166CE6138962B8FDC4DD2A37AE29AEB  E9A0553BCF8BA07FBF7EE5EE36136E4F
# cat 9BB7B3F0CD2CF7615E6D437876F938EF
# redirect entry
```

I know it's a redirection file, and I just want a certain playlist where it was interrupted last time. However, what I don't understand is that it looks like two hashes. How is this redirection relationship done?

**Comment by Traneptora** [comment]
By default, mpv uses the md5 of the filename rather than the filename itself, as a privacy-preserving measure (that way your entire play history isn't saved to watch_later). You can write the actual filenames as well by using `--write-file-name-in-watch-later-config`.

**Comment by jack9603301** [comment]
@Traneptora Well, I will try, but I'm curious, even in this case, how the redirect relationship between the two hash files is obtained, I know that the program can always parse out their redirect relationship , but I don't know how this is done!

**Comment by Traneptora** [comment]
It needs to have the original playlist available in order to make that work, because if the playlist changes then so will the md5sums of the entries inside of it. The md5sums are not sufficient information to reconstruct the redirects - the original has to do the same thing when played.

**Comment by jack9603301** [comment]
@Traneptora Wait a minute, you mean, it doesn't keep redirects in the file info, it just checks if there is a file in a given directory that matches the md5 info of a particular file stored in the directory, right?

**Comment by Traneptora** [comment]
That's correct, it compares the md5 of the file being played to the md5s in the watch later config, and if it finds a match, then it works.

**Comment by jack9603301** [comment]
Wouldn't this be less efficient, why not do direct file path pointing?

**Comment by Traneptora** [comment]
> By default, mpv uses the md5 of the filename rather than the filename itself, as a privacy-preserving measure (that way your entire play history isn't saved to watch_later).

Also md5sum is fast, and it's not like it's hashing thousands of database entries.

**Comment by jimmy-1000** [comment]
> By default, mpv uses the md5 of the filename rather than the filename itself, as a privacy-preserving measure (that way your entire play history isn't saved to watch_later). You can write the actual filenames as well by using `--write-file-name-in-watch-later-config`.

It's strange but I get:
_Error parsing option write-file-name-in-watch-later-config (option not found)_

**Comment by guidocella** [comment]
It's `--write-filename-in-watch-later-config`

**Comment by jimmy-1000** [comment]
> It's `--write-filename-in-watch-later-config

Thanks guidocella 👌

**Comment by RealYukiSan** [comment]
I comparing my video's md5 checksum (that save the quit position with shift+q)  with the filename on `~/.local/state/mpv/watch_later` but can't find the paired one.

here's the way I check in bash script: [gists](https://gist.github.com/RealYukiSan/06f2f92ced742ee4cf9217c1131afd51)

**Comment by guidocella** [comment]
mpv uses MD5 checksums of file paths, not their contents.

**Comment by RealYukiSan** [comment]
does that mean, it look like something like this: `echo -n "/home/user/path/to/video.mkv" | md5sum`?

**Comment by guidocella** [comment]
Yes.

**Comment by RealYukiSan** [comment]
Does MPV support opening a list of "Watch Later" videos for the user to choose from? Or is there an existing plugin that provides this feature?

**Comment by zhongfly** [comment]
> Does MPV support opening a list of "Watch Later" videos for the user to choose from? Or is there an existing plugin that provides this feature?

What you want sounds like "recent playing" or history record.
https://github.com/stax76/mpv-scripts/blob/main/history.lua
https://github.com/yuukidach/mpv-scripts/blob/master/history_bookmark.lua
If you are using uosc, try this: https://github.com/po5/memo
