### ISSUE TITLE
libMpv Qt/Qml Android Only Sound, No Video

### ISSUE THREAD

**Issue by INotfound** [mpv-player/mpv#12277]
Qt 5.12.12 Android

use example: https://github.com/mpv-player/mpv-examples/tree/master/libmpv/qml

main.qml file -> checkBox state switch  **video to blink**

### Log file

`
8-28 21:23:21.002 19161 19206 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
08-28 21:23:21.053  3247  3366 V MesonHwc: No layers to compose, exit.
08-28 21:23:21.053  3247  3366 V MesonHwc: No layers to compose, exit.
08-28 21:23:23.389 27069 27079 I system_server: Background concurrent copying GC freed 40959(1265KB) AllocSpace objects, 2(104KB) LOS objects, 19% free, 5MB/7MB, paused 595us total 106.132ms
08-28 21:23:33.609 27069 27079 I system_server: Background concurrent copying GC freed 48646(1488KB) AllocSpace objects, 0(0B) LOS objects, 19% free, 5MB/7MB, paused 882us total 102.805ms
08-28 21:23:38.969 27069 27079 I system_server: Background concurrent copying GC freed 50118(1521KB) AllocSpace objects, 0(0B) LOS objects, 19% free, 5MB/7MB, paused 587us total 103.814ms
08-28 21:23:41.608 27069 27079 I system_server: Background concurrent copying GC freed 48407(1472KB) AllocSpace objects, 0(0B) LOS objects, 19% free, 6MB/7MB, paused 870us total 102.700ms
08-28 21:23:44.303 27069 27079 I system_server: Background concurrent copying GC freed 51081(1552KB) AllocSpace objects, 0(0B) LOS objects, 19% free, 5MB/7MB, paused 480us total 101.839ms
08-28 21:23:22.827 27069 27174 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
08-28 21:23:53.801  3318  3414 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
08-28 21:24:07.126 27069 27079 I system_server: Background concurrent copying GC freed 45450(1394KB) AllocSpace objects, 0(0B) LOS objects, 19% free, 5MB/7MB, paused 426us total 104.036ms
08-28 21:24:16.350  3888  3888 I com_touch: type=1400 audit(0.0:384193): avc: denied { ioctl } for path="/dev/vcimov" dev="tmpfs" ino=14457 ioctlcmd=0xec73 scontext=u:r:cimov_clientd:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
08-28 21:24:16.577 19161 19201 W AudioCapabilities: Unsupported mime audio/dtshd
08-28 21:24:16.582 19161 19201 W AudioCapabilities: Unsupported mime audio/ffmpeg
08-28 21:24:16.603 19161 19201 W VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6a
08-28 21:24:16.606 19161 19201 W VideoCapabilities: Unsupported mime video/x-vnd.on2.vp6f
08-28 21:24:16.624 19161 19201 W VideoCapabilities: Unsupported mime video/avs
08-28 21:24:16.628 19161 19201 W VideoCapabilities: Unsupported mime video/avs2
08-28 21:24:16.632 19161 19201 W VideoCapabilities: Unsupported mime video/dolby-vision
08-28 21:24:16.635 19161 19201 W VideoCapabilities: Unsupported mime video/dolby-vision
08-28 21:24:16.654 19161 19201 W VideoCapabilities: Unrecognized profile 4 for video/hevc
08-28 21:24:16.658 19161 19201 W VideoCapabilities: Unsupported mime video/mjpeg
08-28 21:24:16.661 19161 19201 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
08-28 21:24:16.662 19161 19201 I VideoCapabilities: Unsupported profile 2 for video/mpeg2
08-28 21:24:16.662 19161 19201 I VideoCapabilities: Unsupported profile 3 for video/mpeg2
08-28 21:24:16.662 19161 19201 I VideoCapabilities: Unsupported profile 4 for video/mpeg2
08-28 21:24:16.662 19161 19201 I VideoCapabilities: Unsupported profile 5 for video/mpeg2
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 2 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 4 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 8 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 16 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 32 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 64 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 128 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 256 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 512 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 1024 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 2048 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 4096 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 8192 for video/mp4v-es
08-28 21:24:16.666 19161 19201 I VideoCapabilities: Unsupported profile 16384 for video/mp4v-es
08-28 21:24:16.676 19161 19201 W VideoCapabilities: Unsupported mime video/rm10
08-28 21:24:16.680 19161 19201 W VideoCapabilities: Unsupported mime video/rm20
08-28 21:24:16.683 19161 19201 W VideoCapabilities: Unsupported mime video/rm30
08-28 21:24:16.687 19161 19201 W VideoCapabilities: Unsupported mime video/rm40
08-28 21:24:16.691 19161 19201 W VideoCapabilities: Unsupported mime video/vc1
08-28 21:24:16.691 19161 19201 W Utils   : could not parse long range '1-'
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 16 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 32 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 64 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 128 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 256 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 512 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 1024 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 2048 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 4096 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 8192 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 16384 for video/x-vnd.on2.vp8
08-28 21:24:16.696 19161 19201 W VideoCapabilities: Unrecognized level 32768 for video/x-vnd.on2.vp8
08-28 21:24:16.722 19161 19201 W VideoCapabilities: Unsupported mime video/wmv3
08-28 21:24:16.727 19161 19201 W VideoCapabilities: Unsupported mime video/wmv1
08-28 21:24:16.731 19161 19201 W VideoCapabilities: Unsupported mime video/wmv2
08-28 21:24:16.735 19161 19201 W VideoCapabilities: Unsupported mime video/x-ms-wmv
08-28 21:24:16.739 19161 19201 W VideoCapabilities: Unsupported mime video/wvc1
08-28 21:24:16.739 19161 19201 W Utils   : could not parse long range '1-'
08-28 21:24:16.759 19161 19201 I VideoCapabilities: Unsupported profile 4 for video/mp4v-es
08-28 21:24:16.777 19161 19214 I OMXClient: IOmx service obtained
08-28 21:24:16.778  3321  3390 I OMXMaster: makeComponentInstance(OMX.amlogic.avc.decoder.awesome) in omx@1.0-service process
08-28 21:24:16.778  3321  3390 D OmxComponentManagerImpl: support frame mode
08-28 21:24:16.779  3321  3390 D OmxComponentManagerImpl: format support multi-instance
08-28 21:24:16.779  3321  3390 D OmxComponentManagerImpl: getEntryByName_2_num=0, componentName:OMX.amlogic.avc.decoder.awesome
08-28 21:24:16.779  3321  3390 V AmlogicVideoDecoderAwesome: AmlogicVideoDecoder:103 >
08-28 21:24:16.779  3321  3390 V AmlogicVideoDecoderAwesome: initializeState_l:1892 >
08-28 21:24:16.779  3321  3390 V AmlogicVideoDecoderAwesome: media.omx.latency is not set used def=1.000000
08-28 21:24:16.779  3321  3390 D AmlogicVideoDecoderAwesome: AmlogicVideoDecoder, mOmxInstancenum 1, mOmxInstanceID 338
08-28 21:24:16.779  3321  3390 W AmlSysfsUtil: [amsysfs_get_sysfs_str] /sys/module/am_vecm/parameters/dolby_vision_enable failed!
08-28 21:24:16.780  3321  3390 D AmlogicVideoDecoderAwesome: mCheckDvesDone = 1
08-28 21:24:16.780  3321  3390 W OmxLogConf: Can not read property media.omx.log_levels, using 0
08-28 21:24:16.780  3321  3390 W OmxResManage: ResManWrapper init fail!
08-28 21:24:16.780  3321  3390 V AmlogicVideoDecoderAwesome: media.omx.out_buffer1 is not set used def=4
08-28 21:24:16.780  3321  3390 D OmxVideoDecoder: setInputCoding OMX.amlogic.avc.decoder.awesome
08-28 21:24:16.780  3321  3390 D OmxVideoDecoder: mIsLinux49=1, major=4, minor=9
08-28 21:24:16.780  3321  3390 D OmxVideoDecoder: multi dec exist
08-28 21:24:16.780  3321  3390 D OmxVideoDecoder: Use frame mode for multidec.
08-28 21:24:16.780  3321  3390 D OmxVideoDecoder: Use min out buffer size
08-28 21:24:16.780  3321  3390 D OmxVideoDecoder: mSupportPiPVideo = 1
08-28 21:24:16.781  3321  3390 D OmxVideoDecoder: mMustOsdDisplay 0, mAmVideoUsed=0, mSupportPiPVideo=1, mPipVideoUsed=0, mVideoUsedByOmx=0
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT: OMX.amlogic.avc.decoder.awesome : Vendor extensions supported (13)
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.4k-osd{{ enable : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.unstable-pts{{ enable : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.is-mvc{{ enable : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.is-flv{{ nContainIndex : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.dvconfig-box{{ disable : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.profile-level{{ n-profile : Int32 },  { n-level : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.nrdp{{ video-peek-in-tunnel : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.low-latency{{ enable : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.save-mem{{ enable : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.videoLayer{{ type : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.renderByOmx{{ enable : Int32 },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.VideoQos{{ info : String },  }
08-28 21:24:16.781  3321  3390 D OMX-VENDOR-EXT:    vendor.rotation-angle{{ angle : Int32 },  }
08-28 21:24:16.781  3321  3390 D OmxComponentManagerImpl: IncreaseEntryNumByName pEntry->mNum=0, pEntry->mMaxNum:9,componentName:OMX.amlogic.avc.decoder.awesome
08-28 21:24:16.781  3321  3390 I omx_core: OMX_getHandle_num=1
08-28 21:24:16.781  3321  3390 D OmxComponent: mApkName=media.codec
08-28 21:24:16.783 19161 19213 D SurfaceUtils: connecting to surface 0xd858f808, reason connectToSurface
08-28 21:24:16.783 19161 19213 I MediaCodec: [OMX.amlogic.avc.decoder.awesome] setting surface generation to 19620865
08-28 21:24:16.783 19161 19213 D SurfaceUtils: disconnecting from surface 0xd858f808, reason connectToSurface(reconnect)
08-28 21:24:16.783 19161 19213 D SurfaceUtils: connecting to surface 0xd858f808, reason connectToSurface(reconnect)
08-28 21:24:16.784 19161 19214 I AmAVUtils: AmAVUtils::getComponentRole isEncoder :0 mime:video/avc
08-28 21:24:16.784 19161 19214 V AVUtils : AVUtils::getComponentRole
08-28 21:24:16.784  3321  3390 D OmxVideoDecoder: setParameter 1083 0x1000017
08-28 21:24:16.784  3321  3390 D OmxVideoDecoder: setInputCoding video_decoder.avc
08-28 21:24:16.784  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.enableAndroidNativeBuffers"
08-28 21:24:16.784  3321  3390 D OmxVideoDecoder: setParameter 1083 0x7f000000
08-28 21:24:16.784  3321  3390 V OmxVideoDecoder: setParameter 1612 EnableNativeBuffers 1
08-28 21:24:16.784  3321  3390 V OmxVideoDecoder: updatePort mUseNativeBuffers 1
08-28 21:24:16.784  3321  3390 D AmlogicVideoDecoderAwesome: get native buffer info NV:w:640,h:480..
08-28 21:24:16.784  3321  3390 V OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=640,portDef.format.video.nFrameHeight=480
08-28 21:24:16.784  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.allocateNativeHandle"
08-28 21:24:16.784  3321  3390 D OmxVideoDecoder: setParameter 1083 0x7f00000a
08-28 21:24:16.784  3321  3390 E OMXNodeInstance: setParameter(0xf2583bd4:amlogic.avc.decoder.awesome, OMX.google.android.index.allocateNativeHandle(0x7f00000a): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
08-28 21:24:16.784  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.storeANWBufferInMetadata"
08-28 21:24:16.784  3321  3390 D OmxVideoDecoder: setParameter 1083 0x7f00000d
08-28 21:24:16.784  3321  3390 D OmxVideoDecoder: setParameter 1632 OMX_GoogleAndroidStoreANWBufferInMetadata
08-28 21:24:16.784  3321  3390 D OmxVideoDecoder: osd close ANWBufferInMetadat
08-28 21:24:16.784  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.storeMetaDataInBuffers"
08-28 21:24:16.784  3321  3390 D OmxVideoDecoder: setParameter 1083 0x7f000002
08-28 21:24:16.784  3321  3390 D OmxVideoDecoder: setParameter 1618 OMX_IndexAndroidStoreMetadataInBuffers__1
08-28 21:24:16.784  3321  3390 E OMXNodeInstance: setParameter(0xf2583bd4:amlogic.avc.decoder.awesome, OMX.google.android.index.storeMetaDataInBuffers(0x7f000002): Output:1 en=1 type=1) ERROR: BadPortIndex(0x8000101b)
08-28 21:24:16.784 19161 19214 E ACodec  : [OMX.amlogic.avc.decoder.awesome] setPortMode on output to DynamicANWBuffer failed w/ err -2147483648
08-28 21:24:16.785  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.allocateNativeHandle"
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: setParameter 1083 0x7f00000a
08-28 21:24:16.785  3321  3390 E OMXNodeInstance: setParameter(0xf2583bd4:amlogic.avc.decoder.awesome, OMX.google.android.index.allocateNativeHandle(0x7f00000a): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
08-28 21:24:16.785  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.enableAndroidNativeBuffers"
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: setParameter 1083 0x7f000000
08-28 21:24:16.785  3321  3390 V OmxVideoDecoder: setParameter 1612 EnableNativeBuffers 1
08-28 21:24:16.785  3321  3390 V OmxVideoDecoder: updatePort mUseNativeBuffers 1
08-28 21:24:16.785  3321  3390 D AmlogicVideoDecoderAwesome: get native buffer info NV:w:640,h:480..
08-28 21:24:16.785  3321  3390 V OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=640,portDef.format.video.nFrameHeight=480
08-28 21:24:16.785  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.storeANWBufferInMetadata"
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: setParameter 1083 0x7f00000d
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: setParameter 1632 OMX_GoogleAndroidStoreANWBufferInMetadata
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: osd close ANWBufferInMetadat
08-28 21:24:16.785  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.storeMetaDataInBuffers"
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: setParameter 1083 0x7f000002
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: setParameter 1618 OMX_IndexAndroidStoreMetadataInBuffers__1
08-28 21:24:16.785  3321  3390 E OMXNodeInstance: setParameter(0xf2583bd4:amlogic.avc.decoder.awesome, OMX.google.android.index.storeMetaDataInBuffers(0x7f000002): Output:1 en=0 type=1) ERROR: BadPortIndex(0x8000101b)
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: setParameter 1083 0x6000001
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: setParameter nPortIndex 0 CompFmt 0x7 ColorFmt 0
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: setParameter 1083 0x6000001
08-28 21:24:16.785  3321  3390 D OmxVideoDecoder: setParameter nPortIndex 1 CompFmt 0 ColorFmt 0x11
08-28 21:24:16.786  3321  3390 I OmxVideoDecoder: getParameter Component Name OMX.amlogic.avc.decoder.awesome, width 640, height 480 nBufferCountMin:3
08-28 21:24:16.786  3321  3390 D OmxVideoDecoder: setParameter 1083 0x2000001
08-28 21:24:16.786  3321  3390 D OmxVideoDecoder: setParameter nPortIndex 0 nFrameWidth 852 nFrameHeight 480 nSliceHeight 16
08-28 21:24:16.786  3321  3390 V OmxVideoDecoder: updatePort mUseNativeBuffers 1
08-28 21:24:16.786  3321  3390 D AmlogicVideoDecoderAwesome: get native buffer info NV:w:640,h:480..
08-28 21:24:16.786  3321  3390 V OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=640,portDef.format.video.nFrameHeight=480
08-28 21:24:16.786  3321  3390 I OmxVideoDecoder: getParameter Component Name OMX.amlogic.avc.decoder.awesome, width 640, height 480 nBufferCountMin:4
08-28 21:24:16.786  3321  3390 D OmxVideoDecoder: setParameter 1083 0x2000001
08-28 21:24:16.786  3321  3390 D OmxVideoDecoder: media.omx.display_mode=0
08-28 21:24:16.786  3321  3390 D OmxVideoDecoder: setParameter nPortIndex 1 nFrameWidth 864 nFrameHeight 480 nSliceHeight 480
08-28 21:24:16.786  3321  3390 V OmxVideoDecoder: updatePort mUseNativeBuffers 1
08-28 21:24:16.786  3321  3390 D AmlogicVideoDecoderAwesome: get native buffer info NV:w:864,h:480..
08-28 21:24:16.786  3321  3390 V OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=864,portDef.format.video.nFrameHeight=480
08-28 21:24:16.786  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.describeColorAspects"
08-28 21:24:16.786  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.storeMetaDataInBuffers"
08-28 21:24:16.787  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.storeANWBufferInMetadata"
08-28 21:24:16.787  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.prepareForAdaptivePlayback"
08-28 21:24:16.787  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.configureVideoTunnelMode"
08-28 21:24:16.787  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.useAndroidNativeBuffer2"
08-28 21:24:16.787  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.useAndroidNativeBuffer"
08-28 21:24:16.787  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.enableAndroidNativeBuffers"
08-28 21:24:16.787  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.allocateNativeHandle"
08-28 21:24:16.787  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.getAndroidNativeBufferUsage"
08-28 21:24:16.787  3321  3390 D OmxVideoDecoder: setConfig 2275 0x7f00000c
08-28 21:24:16.787  3321  3390 D OmxComponent: getExtensionIndex 1200 name="OMX.google.android.index.describeHDRStaticInfo"
08-28 21:24:16.787  3321  3390 D OmxVideoDecoder: setConfig 2275 0x7f000009
08-28 21:24:16.787  3321  3390 D OmxVideoDecoder: HDRStaticInfo: R=0 0; G=0 0; B=0 0; W=0 0; MaxDisplayLuminance:0, MinDisplayLuminance=0, mMaxContentLightLevel=0, MaxContentLightLevel=0
08-28 21:24:16.787  3321  3390 D OmxVideoDecoder: HDRStaticInfo: all parmeter is 0, set mHasHDRStaticInfo to false
08-28 21:24:16.787 19161 19214 I AmAVUtils: AmAVUtils::isAudioExtendFormat input = video/avc
08-28 21:24:16.787 19161 19214 I AmAVUtils: AmAVUtils::isExtendFormat input = video/avc
08-28 21:24:16.787  3321  3390 I OmxVideoDecoder: getParameter Component Name OMX.amlogic.avc.decoder.awesome, width 852, height 480 nBufferCountMin:3
08-28 21:24:16.787  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.787  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=0 (4k-osd)
08-28 21:24:16.787  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.787  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=1 (unstable-pts)
08-28 21:24:16.788  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.788  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=2 (is-mvc)
08-28 21:24:16.788  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.788  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=3 (is-flv)
08-28 21:24:16.788  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.788  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=4 (dvconfig-box)
08-28 21:24:16.788  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.788  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=5 (profile-level)
08-28 21:24:16.788  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.788  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=5 (profile-level)
08-28 21:24:16.788  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.788  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=6 (nrdp)
08-28 21:24:16.789  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.789  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=7 (low-latency)
08-28 21:24:16.789  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.789  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=8 (save-mem)
08-28 21:24:16.789  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.789  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=9 (videoLayer)
08-28 21:24:16.789  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.789  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=10 (renderByOmx)
08-28 21:24:16.789  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.789  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=11 (VideoQos)
08-28 21:24:16.789  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.789  3321  3390 V OmxVideoDecoder: VendorExt: getConfig: index=12 (rotation-angle)
08-28 21:24:16.789  3321  3390 D OmxVideoDecoder: getConfig 2173 0x6f100004
08-28 21:24:16.789  3321  3390 V OmxVideoDecoder: updatePort mUseNativeBuffers 1
08-28 21:24:16.790  3321  3390 D AmlogicVideoDecoderAwesome: get native buffer info NV:w:864,h:480..
08-28 21:24:16.790  3321  3390 V OmxVideoDecoder: updatePort:portDef.format.video.nFrameWidth=864,portDef.format.video.nFrameHeight=480
08-28 21:24:16.790  3321  3390 I OmxVideoDecoder: getParameter Component Name OMX.amlogic.avc.decoder.awesome, width 864, height 480 nBufferCountMin:4
08-28 21:24:16.790  3321  3390 D OmxVideoDecoder: getConfig 2173 0x700000f
08-28 21:24:16.790  3321  3390 D OmxVideoDecoder: getConfig 2176 nIndex 0x700000f
08-28 21:24:16.790  3321  3390 D OmxVideoDecoder: getConfig OMX_IndexConfigCommonOutputCrop pRect->nWidth=864, pRect->nHeight=480
08-28 21:24:16.790  3321  3390 D OmxVideoDecoder: setConfig 2275 0x7f00000c
08-28 21:24:16.790  3321  3390 D OmxVideoDecoder: getConfig 2173 0x7f00000c
08-28 21:24:16.790  3321  3390 D OmxVideoDecoder: getConfig 2173 0x7f00000c
08-28 21:24:16.790  3321  3390 E OMXNodeInstance: getConfig(0xf2583bd4:amlogic.avc.decoder.awesome, ??(0x7f00000c)) ERROR: UnsupportedSetting(0x80001019)

`

**Comment by DSxiaolong** [comment]
https://github.com/wang-bin/mdk-sdk/wiki/Render-API

**Comment by INotfound** [comment]
help me!!!

**Comment by INotfound** [comment]
only sound no video, the feeling is like fbo rendering on wrong

**Comment by Dudemanguy** [comment]
What are you actually doing? This example has no `video to blink` feature. If you want people to help you, you need to show what code you actually added first.

**Comment by DSxiaolong** [comment]
> help me!!!

Are you using Android? Using libmpv on Androd?
