### ISSUE TITLE
Millisecond information during frame advance

### ISSUE THREAD

**Issue by padhia** [mpv-player/mpv#1227]
Hi,

I posted this on the Google group, but wasn't sure if that was the right forum. 

First, I want to say I just came across this video player and I am impressed by what I have seen so far.

I have been looking for the longest time a player that supports
- Frame level advance (which mpv seems to support with . and , key bindings)
- A way to display frame position, either as frame number, and/or the time code value in milliseconds. 

Does mpv support  displaying current frame position? In fact, if OSD automatically changes to include milliseconds during frame advance mode, that'd be wonderful.

The main reason for requesting this functionality is, to be able figure out information needed to insert chapter markers metadata in an existing video. I use ffmpeg a lot to convert and combine home videos with chapter markers as metadata, and this functionality would really ease a lot of pain.

Thanks

**Comment by paxidently** [comment]
Hi, can I get the number of milliseconds in Lua script or using proprty expansion in show_text command?

**Comment by wm4** [comment]
``show_text `${=time-pos}``, ``mp.get_property_number("time-pos")``

**Comment by seahorse41** [comment]
wm4, Why would showing additional osd information during frame stepping be "annoying"? I would rather see fractions Only when stopped (paused) than all the time which --osd-fractions does when my default is --osd-level=2

**Comment by wm4** [comment]
It's an interesting idea to show the millisecond display only if you're framesteping, but it'd also require additional logic. Maybe you could open a separate feature request - then I won't forget about it and give it some serious consideration.
