### ISSUE TITLE
`libplacebo-opts=preset=high_quality` ignores `glsl-shader="~~/FSRCNNX_x2_16-0-4-1.glsl"`

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12278]
When using `libplacebo-opts=preset=high_quality` with `glsl-shader="~~/FSRCNNX_x2_16-0-4-1.glsl"` (or any other shader)
then mpv will ignore `glsl-shader="~~/FSRCNNX_x2_16-0-4-1.glsl"` and will not use it.

https://github.com/mpv-player/mpv/pull/12195#issuecomment-1696380236

(Sorry for ignoring issue template)

**Comment by haasn** [comment]
Well, the point of `preset` is to discard all options and load a preset. But maybe I should exclude options which are not controllable through `pl_options`? 🤔 

I'll probably fix this inside libplacebo, by changing the way `preset` parsing works.
