### ISSUE TITLE
Allow setting PIPEWIRE_NODE with command line

### ISSUE THREAD

**Issue by kuon** [mpv-player/mpv#12273]
Pipewire target node can be set with `PIPEWIRE_NODE` environment variable, like so:

```
PIPEWIRE_NODE="video" mpv <somefile>
```

This works, but the problem with that is that it requires always launching `mpv` with an environment variable.

It would be better to have a `--pipewire-node` command line flag that could also be set in the mpv config file to always use the same node on each launch.

**Comment by t-8ch** [comment]
@kuon 
This should already happen with `--audio-device`.
(It only works with node names, not node ids, though)

**Comment by kuon** [comment]
Ok, for reference the syntax is `--audio-device=pipewire/video` for `PIPEWIRE_NODE=video`.
