### ISSUE TITLE
Is it possible to make MPV window not disappear if it can't open a file?

### ISSUE THREAD

**Issue by HubKing** [mpv-player/mpv#12274]
If I drag-and-drop a video file onto PotPlayer or VLC, when it can't open the file, it just shows an error message and its window stays open. If I do that to MPV, and MPV can't open the file (e.g., damaged file), MPV's window disappears (`keep-open` in the conf). Can I make it not disappear and maybe just show an error message?

**Comment by ma-zsola** [comment]
You need to add `idle=yes` to your mpv.conf.
