### ISSUE TITLE
Segmentation fault when trying to play local file

### ISSUE THREAD

**Issue by Abbotta4** [mpv-player/mpv#12287]
### Important Information

Provide following Information:
- mpv version **0.36.0**
- Linux Distribution and Version **Gentoo/Linux 6.3.10**
- Source of the mpv binary **media-video/mpv from main gentoo repo**
- If known which version of mpv introduced the problem **At least 0.34.0**
- Window Manager and version **Openbox 3.6.1**
- GPU driver and version **intel, xorg-server version 21.1.8, mesa version 23.1.3**
- Possible screenshot or video of visual glitches **N/A**

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

`mpv --no-config --log-file=test.log test.mkv` exits immediately with a segmentation fault.

### Expected behavior

mpv should play the file

### Actual behavior

mpv crashes immediately with a segmentation fault

### Log file

[test.log](https://github.com/mpv-player/mpv/files/12463804/test.log)

### Sample files

http://0x0.st/HpsN.mkv

**Comment by llyyr** [comment]
You have to provide a backtrace, the logs don't contain any information about why it'd segfault.

That file works for me though

**Comment by CounterPillow** [comment]
>Gentoo

I can already guess what the cause of the problem is. What are your CFLAGS?

**Comment by CounterPillow** [comment]
Okay, surprisingly not insane CFLAGS. The crash is in libavcodec though, so not within mpv itself. Please rebuild with debug symbols enabled, otherwise the backtrace is close to useless.

**Comment by llyyr** [comment]
Does it only crash with that file? What about playing it with ffplay? Either way you need debug symbols, and this is probably an issue with your ffmpeg build, not mpv

**Comment by Abbotta4** [comment]
There are other files that I can play with mpv successfully, but it looks like I can not play the original clip with ffplay either, so this must have to do with ffmpeg/libavcodec. Thank you all for the help.

I added the 'debug' USE to both mpv and ffmpeg, but the backtraces still don't have symbols in them: [backtrace.1.log](https://github.com/mpv-player/mpv/files/12464398/backtrace.1.log)

If the backtrace would still be helpful here, I can try to figure out why symbols are not being loaded and post a proper one. If not, feel free to close and I will probably just revert to ffmpeg 4

**Comment by llyyr** [comment]
Well we know it's not mpv's bug, so you should rebuild ffmpeg with debug symbols instead and try to report the crash there. It also doesn't crash for me with ffmpeg-6, so it's definitely something wrong with your system or ffmpeg build

**Comment by rnpnr** [comment]
For future reference you should check the [gentoo wiki][] if you are
unsure how to enable debug symbols.

Particularly the third line of text:

> Debugging symbols are unrelated to `USE=debug`!

[gentoo wiki]: https://wiki.gentoo.org/wiki/Debugging

**Comment by qyot27** [comment]
Yeah, `--disable-stripping` on FFmpeg or else it'll just remove the debug symbols you built in.

**Comment by Abbotta4** [comment]
Filed with ffmpeg here: https://trac.ffmpeg.org/ticket/10549
