### ISSUE TITLE
select default track subtitles automatically

### ISSUE THREAD

**Issue by JosefLitos** [mpv-player/mpv#12284]
### Important Information

Provide following Information:
- mpv 0.36.0
- Archlinux, kernel any
- Source: pacman

### Reproduction steps

use any video, merge it with a subtitle without a language specified, using the following `ffmpeg` command to make the subtitles set as default:
```bash
ffmpeg -i "$name.mp4" -i "$name.srt" -map 0:v -map 0:a -map 1 -c copy -disposition:s:0 default "$name.mkv"
```

Play the video and see the subtitles not being selected by default.
This behaviour does not change when using `--slang=default`.

### Expected behavior

Select the subtitles by default when no other are available

### Actual behavior

No subtitles get selected even when using `--slang=default`

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12462183/output.txt)

### Sample files

[subs](https://0x0.st/Hpr2.srt)
[video](https://0x0.st/HprL.mp4)
[combined](https://0x0.st/Hpr9.mkv)

**Comment by po5** [comment]
Works fine with `--no-config` here. You're probably on a commit older than #12015, update.

**Comment by JosefLitos** [comment]
I would assume when `subs=default` did nothing, a fallback would do nothing either. Which, after trying it out, in fact did (do nothing), unfortunately. I am on the latest release, so I will probably wait for the next one to fix this.

It is not a major issue - I can still select the track myself, it is just an inconvenience.

**Comment by JosefLitos** [comment]
I've just tried out with archlinux AUR package (`mpv-git`) and still didn't work.

**Comment by temis01** [comment]
I seemed to have the same problem with 0.36 on windows 11 even though my slang was not default but enUS,eng,en,fr
I never use internal sub but external *.srt files

sub-auto was KO
subs-fallback=default KO

This last one alone fixed it for me !
subs-with-matching-audio=yes

**Comment by Dudemanguy** [comment]
>I've just tried out with the AUR package mpv-git and still didn't work.

Are you sure? This works with the sample you provided on master and it should work. The subtitle not having a language shouldn't matter. For 0.36, you need to do `subs-fallback=default` + `subs-with-matching-audio=yes` I believe.

**Comment by JosefLitos** [comment]
As I've already stated, these options have no effect on the result.

**Comment by Dudemanguy** [comment]
If you want to select non-default subtitles anyway, you can use `--subs-fallback=yes`.
