### ISSUE TITLE
get current timestamp in lua script similar to %P

### ISSUE THREAD

**Issue by Omar-Abdul-Azeez** [mpv-player/mpv#12296]
How to obtain the current timestamp in HH:MM:SS.mmm like %P in screenshot template from a lua script?

**Comment by christoph-heinrich** [comment]
`mp.get_property_osd("playback-time/full")`

**Comment by Omar-Abdul-Azeez** [comment]
btw, is there a way to list subproperties? like `full` which is under `playback-time`

**Comment by christoph-heinrich** [comment]
I'm not aware of any, but if it's not documented that means it's not intended to be used by users and could change at any time.
If you're uncomfortable with using undocumented stuff you could instead use `mp.get_property_number("playback-time")` and then calculate hours, minutes, seconds and milliseconds yourself.
