### ISSUE TITLE
Getting information about subtitle styling from the playing video

### ISSUE THREAD

**Issue by SacredZenpie** [mpv-player/mpv#12305]
Is it possible to get ASS subtitle styling information like Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour etc from the current subtitle (for my lua script)?

**Comment by llyyr** [comment]
https://mpv.io/manual/master/#command-interface-sub-ass-extradata

**Comment by SacredZenpie** [comment]
> https://mpv.io/manual/master/#command-interface-sub-ass-extradata

Ive tried but only returns NIL

**Comment by llyyr** [comment]
Then your subtitle format isn't ass? You'd need to provide a sample for me to look further

**Comment by SacredZenpie** [comment]
Here both the log and the sub (Ive renamed it to .txt so I can upload it here but its .ass extracted from an anime)

[Youjo Senki- Movie_track4_[eng].txt](https://github.com/mpv-player/mpv/files/12488425/Youjo.Senki-.Movie_track4_.eng.txt)
[log-file.txt](https://github.com/mpv-player/mpv/files/12488426/log-file.txt)


> Then your subtitle format isn't ass? You'd need to provide a sample for me to look further

**Comment by llyyr** [comment]
This property was only added 4 days ago, you need to update mpv https://github.com/mpv-player/mpv/commit/f9918b53901db2fbc3cfc1be509a32d3ed89556a

**Comment by SacredZenpie** [comment]
Oh, I didnt realize its a new feature, my apologies.
