### ISSUE TITLE
Installing Windows operating system in VMware virtual machine, calling MPV to play video crashes

### ISSUE THREAD

**Issue by DSxiaolong** [mpv-player/mpv#12300]
When installing the Windows operating system in the VMware virtual machine and playing videos using MPV, if hardware decoding is enabled（mpv::qt::set_option_variant(mpv, "hwdec", "auto");）, the video program will flash when loaded. If hardware decoding is turned off, the function will be normal. Can you automatically check if the GPU hardware is functional without flashing and still function properly?

**Comment by Dudemanguy** [comment]
The title claims the video crashes but your description doesn't say anything about it crashing? That should have been fixed by a5b929026100b7508d8fee6dbbea42f3a5db05fc. I don't know what exactly you mean by "flash when loaded" but it's most likely something we have no control over.

**Comment by llyyr** [comment]
If you don't want mpv to explode then use auto-safe, not auto.

**Comment by DSxiaolong** [comment]
> If you don't want mpv to explode then use auto-safe, not auto.

Thank you for your help. I'll try auto safe

**Comment by kasper93** [comment]
> If you don't want mpv to explode then use auto-safe, not auto.

Doesn't matter, we were not checking if hwdec initialized correctly before https://github.com/mpv-player/mpv/commit/a5b929026100b7508d8fee6dbbea42f3a5db05fc and crashing. 

In fact `auto-safe` does nothing interesting on Windows.
