### ISSUE TITLE
Option af-toggle: Label XXX not found

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#12319]
### Reproduction steps

Use the following `mpv.conf`:

```
af=@test:!anull
af-toggle=@test
```

And then run `mpv` on the command line

### Expected behavior

No warning is printed, as this is legal syntax and works correctly (the filter is added disabled, then `af-toggle` correctly enables it)

### Actual behavior

```
$ mpv
Option af-toggle: Label test not found
mpv 0.36.0+git20230826.83c0e980 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
...
```

### Log file

[mpv_sucks.log](https://github.com/mpv-player/mpv/files/12504435/mpv_sucks.log)

**Comment by llyyr** [comment]
Going by the logs, it tries to toggle `test` before even applying the config options

**Comment by Dudemanguy** [comment]
Just for reference there's also #7093 but that involved using a profile.

**Comment by natural-harmonia-gropius** [comment]
https://github.com/mpv-player/mpv/issues/9769 vf also have same issue.
