### ISSUE TITLE
gpu-next: flicker with display-resample and interpolation

### ISSUE THREAD

**Issue by christoph-heinrich** [mpv-player/mpv#12316]
### Important Information

Provide following Information:
- mpv 7f7513132f24344b99645482cd6fd651053d9487 and libplacebo https://github.com/haasn/libplacebo/commit/31082eee7a6dc800df5bd7db6d115efcaaa2dd8c
- Arch linux
- compiled from source

I noticed that problem months ago with a file that had a frame with incorrect pts every few seconds, but didn't look into it any further because it usually doesn't cause any problems (also the video wasn't freely available, so providing a sample might have been problematic).
It came up again when testing https://github.com/mpv-player/mpv/issues/12028.
The whole image flackers occasionally (random intervals) when using opengl, while it only flickers around the border when using vulkan.
Doesn't happen with vo=gpu.
Might be related to #11519
### Reproduction steps

1. Download https://github.com/ferreum/mpv-skipsilence/blob/master/skipsilence.lua
2. `mpv --no-config --script=skipsilence.lua --script-opts=skipsilence-enabled=yes,skipsilence-ramp_constant=4 --vo=gpu-next --video-sync=display-resample --interpolation --gpu-api=opengl "https://www.youtube.com/watch?v=jpKrrchVRGE"`

### Expected behavior
Normal playback without flickering
### Actual behavior
Opengl

https://github.com/mpv-player/mpv/assets/8932183/319fd8ae-52c3-486c-b664-68499a7f49a3

Vulkan

https://github.com/mpv-player/mpv/assets/8932183/a03f1fed-3bc0-4872-b19f-01ca19e6a3b2

### Log file
[opengl log](https://github.com/mpv-player/mpv/files/12504044/full.txt)
[vulkan log](https://github.com/mpv-player/mpv/files/12504043/edge.txt)

### Sample files

[The video from the linked issue](https://www.youtube.com/watch?v=jpKrrchVRGE)

**Comment by llyyr** [comment]
> Render queue underrun.

Might be related to https://github.com/mpv-player/mpv/issues/12101 and https://github.com/mpv-player/mpv/commit/35a6b26b780af4befa4da06a63bebf95571d1279 ?

**Comment by christoph-heinrich** [comment]
> > Render queue underrun.
> 
> Might be related to #12101 and [35a6b26](https://github.com/mpv-player/mpv/commit/35a6b26b780af4befa4da06a63bebf95571d1279) ?

It might be, but there was no mention of flickering in that issue.

**Comment by Myaanee** [comment]
Maybe related to #11465  as well?

**Comment by llyyr** [comment]
This only happens with `--tscale=mitchell --tscale-clamp=1` which were the old defaults, since we use oversample now and hermite is recommended over mitchell for blurrier interpolation this shouldn't be an issue anymore.

**Comment by christoph-heinrich** [comment]
Interesting observation and I can confirm that skipsilence.lua doesn't cause any problems with the current defaults anymore. There is still the occasional weird flicker similar to the edge flicker in the video above with videos that have mistimed frames on vulkan, which I assume is related.

It still happens with `--tscale=mitchell --tscale-clamp=1` for `vo=gpu-next` but not on `vo=gpu`, so there is still something wrong.

**Comment by Dudemanguy** [comment]
Playing that video with those script settings causes a gazillion dropped frames for me. Is my computer just bad or something? Without `skipsilence-ramp_constant=4`, it still drops frames but a lot less. I can confirm that with `--tscale=mitchell --tscale-clamp=1` and with `skipsilence-ramp_constant=4` both `vulkan` and `opengl` have that flickering. Without `skipsilence-ramp_constant=4`, it doesn't flicker. So to me this just seems like gpu-next doesn't quite handle interpolation when you're dropping a bunch of frames as elegantly? I assume we're probably giving libplacebo bad values which cause the flicker.

**Comment by christoph-heinrich** [comment]
> Playing that video with those script settings causes a gazillion dropped frames for me. Is my computer just bad or something?

Are you on a 100Hz+ display? Because when `fps * speed > display-fps` it's normal for the dropped frames to go up.

But I have also noticed dropped frames on speed changes.
When fast forwarding with [evafast](https://github.com/po5/evafast/pull/8) playback is always a bit more choppy then it should be while speeding up and for a few seconds afterwards. I've never looked into why that may be, but probably a frame timing thing.

**Comment by Dudemanguy** [comment]
>Are you on a 100Hz+ display? Because when fps * speed > display-fps it's normal for the dropped frames to go up.

Nah just normal 60Hz. And yeah of course the `--speed=2` setting drops frames, but that script with those settings specifically makes it drop an absurd amount and gives me the AV desync message. Is it just me?

**Comment by Dudemanguy** [comment]
Did a bit more testing and I *think* the root cause of this flicker is when you drop a bunch of frames in short burst. The script with these settings happen to cause this on the video. If you watch the dropped frame counter, anytime there's a big jump in the values, it lines up with a flicker. On the other hand if you load up on comically heavy rendering settings that cause regular frame drops, the flickering artifact doesn't occur since there aren't hand sudden burst. So I don't believe this particular issue is related to anything else.

vo_gpu is more robust against this for whatever reason. I suspect vo_gpu_next could use some extra sanity somewhere to avoid weird edges like this.

**Comment by Dudemanguy** [comment]
Fixes by #12865.

**Comment by Dudemanguy** [comment]
And not actually fixed anymore. Previous commit "fixed" this by accident.

**Comment by christoph-heinrich** [comment]
Fixed by #12890
