### ISSUE TITLE
Whta is meant by dirty-build ?

### ISSUE THREAD

**Issue by capecrusader-121** [mpv-player/mpv#12328]
Hey there while building mpv from source i see the prefix **dirty** behind mpv version

```
mpv 0.36.0-dirty Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
```

What's meant by this prefix dirty ?
Is it something negative ?

I would appreciate if someone clears this up for me, its pestering me and i got nothing valuable while searching in internet.
Thanks.

**Comment by CounterPillow** [comment]
it means your git working tree had uncommitted changes in it.

**Comment by capecrusader-121** [comment]
@CounterPillow  That means, this occurs when mpv is being patched at downstream level ? or is it that upstream has uncommitted changes left for a release tag ?

**Comment by CounterPillow** [comment]
The former.

**Comment by capecrusader-121** [comment]
@CounterPillow  Thanks, got it, patched mpv is termed dirty.

**Comment by CounterPillow** [comment]
To clarify a possible misconception: If the patches are committed to the local working tree (e.g. applied through "git am"), the dirty suffix isn't applied, though the commit hash will be one not found in the upstream git repo. It's specifically for changes that are made to the local working tree without git being involved.
