### ISSUE TITLE
PGS subtitle duration incorrect

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#12327]
### Important Information

Provide following Information:
- mpv version: git master
- Windows Version: Win11 22H2
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild
- If known which version of mpv introduced the problem: https://github.com/mpv-player/mpv/commit/02a80f850b5403da89fefed7b32b3f3dfb82f647, https://github.com/mpv-player/mpv/commit/725b631ec3bdd5016072b5a6aa6a218fb87ffd11

### Reproduction steps

Play videos with PGS subtitles.

### Expected behavior

The duration of PGS subtitles is displayed normally.

### Actual behavior

Since that commit of https://github.com/mpv-player/mpv/commit/02a80f850b5403da89fefed7b32b3f3dfb82f647, the PGS subtitle behavior has been broken, and another commit of  https://github.com/mpv-player/mpv/commit/725b631ec3bdd5016072b5a6aa6a218fb87ffd11 has not been able to fix it.

Before [02a80f8](https://github.com/mpv-player/mpv/commit/02a80f850b5403da89fefed7b32b3f3dfb82f647)

https://github.com/mpv-player/mpv/assets/61936050/354080cc-b3d8-4d96-a917-0ca7175a779b

Now

https://github.com/mpv-player/mpv/assets/61936050/7408dff9-16f7-4cf4-a678-3839a6ab6187

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/12505797/mpv.log)

### Sample file

https://0x0.st/HfPg.mkv

**Comment by Dudemanguy** [comment]
Can you upload the sample file here?

**Comment by dyphire** [comment]
> Can you upload the sample file here?

Unfortunately, my hard disk is broken and the source file has been lost.

**Comment by llyyr** [comment]
Please try to provide a sample, this would be incredibly difficult to fix without one. Anyone else who might have a sample with the same issue is also welcome to post it

**Comment by raziel711** [comment]
I'm also having this same issue with pgs subtitles not having the correct timings.  It's harder to see with dialogue, but it's more apparent with subtitle tracks with a lot of signs.  It also seems to be consistently happening with every track I've tried.

In this example, the subtitle remains on screen for slightly too long.
After https://github.com/mpv-player/mpv/commit/72e417850394a08fab467f55d4e6ae4a9fbcd23a:

https://github.com/mpv-player/mpv/assets/75226602/17874f34-252b-41d8-bf57-8b23ab5908c0

Before https://github.com/mpv-player/mpv/commit/02a80f850b5403da89fefed7b32b3f3dfb82f647:

https://github.com/mpv-player/mpv/assets/75226602/508d6168-1381-4866-bc2f-b4a220def575

In this example, the sign appears too early.
After https://github.com/mpv-player/mpv/commit/72e417850394a08fab467f55d4e6ae4a9fbcd23a:

https://github.com/mpv-player/mpv/assets/75226602/b95670f8-7c27-44d9-ab58-f9c6396cedbe

Before https://github.com/mpv-player/mpv/commit/02a80f850b5403da89fefed7b32b3f3dfb82f647:

https://github.com/mpv-player/mpv/assets/75226602/9576abae-1712-44c8-9f98-5d394575160a

Sample files:
[sample 1.zip](https://github.com/mpv-player/mpv/files/12543243/sample.1.zip)
[sample 2.zip](https://github.com/mpv-player/mpv/files/12543245/sample.2.zip)

Log file (for the mpv-x86_64-v3-20230830-git-15ada7c sample 1 clip):
[log.txt](https://github.com/mpv-player/mpv/files/12543247/log.txt)

**Comment by Dudemanguy** [comment]
Embarrassingly, I just realized there's already an existing `sub-fix-timing` option. It seems to fix the gaps issue and not introduce any negative effects in that sample. Maybe just flip it to yes by default?

**Comment by raziel711** [comment]
I'm not sure if it's related, but the https://github.com/mpv-player/mpv/commit/02a80f850b5403da89fefed7b32b3f3dfb82f647 commit was originally meant to fix the flickering mentioned in https://github.com/mpv-player/mpv/issues/8202, and one thing I noticed is that the flickering with the pgs subs only occurs when the forced-display flag is set to yes.  If you take the video sample in https://github.com/mpv-player/mpv/issues/8202, change the subtitle to no longer be forced, and play that in a pre https://github.com/mpv-player/mpv/commit/02a80f850b5403da89fefed7b32b3f3dfb82f647 build, the flickering doesn't happen even if `sub-fix-timing` is set to no.  Given that, would it be possible to restore the original behavior and see if the issue with forced subs can be fixed?  

If you think using `sub-fix-timing` would be better, would it be possible to add an option so that it only works with pgs or vobsubs?  I think the default is set to no because it can have an adverse effect on ass or srt subtitle timings.

**Comment by Dudemanguy** [comment]
I think that's just a red herring because remuxing the file happens to fix the subtitle durations. #10051 looks like it was the same issue and from the log you can see that the subtitle track is not forced. And indeed, the mere presence of the flag shouldn't matter here.

**Comment by dyphire** [comment]
https://0x0.st/HfPg.mkv
I downloaded the source file again and cut and uploaded it as a sample file.

> Embarrassingly, I just realized there's already an existing `sub-fix-timing` option. It seems to fix the gaps issue and not introduce any negative effects in those samples. Maybe just flip it to yes by default?

This commit of https://github.com/mpv-player/mpv/commit/725b631ec3bdd5016072b5a6aa6a218fb87ffd11 introduced this bug, and enabling this `sub-fix-timing` option  on top of it has no effect. So do you mean to restore this submission and try to fix the original issue by changing the default value of this `sub-fix-timing`  option?

If that's the case, I think it's a good idea. Obviously, this commit was also incorrect.

**Comment by Dudemanguy** [comment]
I mean to revert that commit and then add an auto mode to `sub-fix-timing` so it would only apply to pgs/dvd subtitles.

>I downloaded the source file again and cut and uploaded it as a sample file.

Thanks. So unfortunately, the sub duration of the sample appears to be simply wrong. Maybe you didn't notice it, but the subtitle lingers for about an extra frame. This happens on master with the offending commits reverted. My idea does not appear to negatively impact it at least. Of course, the behavior without the offending commits makes this even worse and more noticeable since it stays on screen for a few ms longer.

**Comment by dyphire** [comment]
> Thanks. So unfortunately, the sub duration of the sample appears to be simply wrong. Maybe you didn't notice it, but the subtitle lingers for about an extra frame. This happens on master with the offending commits reverted. My idea does not appear to negatively impact it at least. Of course, the behavior on master with the bad commits makes this even worse and more noticeable since it stays on screen for a few ms longer.

Yes, I noticed this. Even before https://github.com/mpv-player/mpv/commit/02a80f850b5403da89fefed7b32b3f3dfb82f647 commit, some subtitles of thethe sample file may linger one more frame when playing on mpv.

I have also tried playing this file on MPC-BE, and the subtitle display is normal without any frame lag. They may have found a reliable way to handle it.

**Comment by Dudemanguy** [comment]
VLC seems to have the same problem with this sample at least. I'm not sure how one would attempt to rectify this case, but I guess I'll go ahead and push the changes I had which hopefully get us back to how it originally was but with the gaps issue fixed.

**Comment by kasper93** [comment]
> Thanks. So unfortunately, the sub duration of the sample appears to be simply wrong. Maybe you didn't notice it, but the subtitle lingers for about an extra frame. This happens on master with the offending commits reverted. My idea does not appear to negatively impact it at least. Of course, the behavior on master with the bad commits makes this even worse and more noticeable since it stays on screen for a few ms longer.

I might look at it. I remember we were fixing quite a few of those PGS timing issue back in the day in MPC-HC. And indeed it works better. Might look what it does. PGS subs often have bad timings, especially in DVB-T broadcast. But IIRC MPC-HC is pretty robust in this area.

**Comment by Dudemanguy** [comment]
>PGS subs often have bad timings

I've unfortunately discovered this lately...
