### ISSUE TITLE
--sub-file SUP opened successfully by bdmv/blu-ray but then missclassified by lavf as audio.

### ISSUE THREAD

**Issue by cubicibo** [mpv-player/mpv#12324]
### Important Information
Summary: mpv parameter --sub-file sends the file to all AV codecs. Some binary streams can be missclassified as something else and fail to open. The more general operation of drag-and-drop on the GUI is also affected.

```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 05:10:36 2023
FFmpeg version: 6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```
-running on macOS 12.0.1. However, I expect all platforms to be affected identically by the nature of the issue.

### Reproduction steps
`mpv --sub-file=subs.sup video.mkv`

### Expected behavior
The subtitle file is loaded and plays. Drag-and-drop also works.

### Actual behavior
The stream contained in the stand-alone SUP file is identified as an audio codec by lavf and rejected, despite being given as a `sub-file` by the user (and apparently correctly identified as SUP in the first place, as it is processed by bdmv/bluray appropriately). Drag-and-drop also fails.

Essentially:
```
[   0.073][v][bdmv/bluray] Opening /Users/cibo/Desktop/subs.sup
[   0.073][v][file] Opening /Users/cibo/Desktop/subs.sup
[   0.073][d][file] resize stream to 131072 bytes, drop 0 bytes
[   0.073][d][file] Stream opened successfully.
[   0.073][v][demux] Trying demuxers for level=normal.
[   0.073][d][demux] Trying demuxer: disc (force-level: normal)
[   0.073][d][demux] Trying demuxer: edl (force-level: normal)
[   0.073][d][demux] Trying demuxer: cue (force-level: normal)
[   0.073][d][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.073][d][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.073][d][demux] Trying demuxer: mkv (force-level: normal)
[   0.073][d][demux] Trying demuxer: libarchive (force-level: normal)
[   0.075][d][demux] Trying demuxer: lavf (force-level: normal)
[   0.079][v][lavf] Found 'sup' at score=25 size=2048.
[   0.079][v][lavf] Found 'amrnb' at score=26 size=4096.
[   0.083][e][ffmpeg/audio] amrnb: Corrupt bitstream
[   0.083][w][ffmpeg/demuxer] amrnb: Estimating duration from bitrate, this may be inaccurate
[   0.083][v][lavf] avformat_find_stream_info() finished after 32768 bytes.
[   0.083][v][demux] Detected file format: amrnb (libavformat)
[   0.083][e][cplayer] No sub streams in file /Users/cibo/Desktop/subs.sup.
[   0.083][e][cplayer] Can not open external file /Users/cibo/Desktop/subs.sup.
```

For drag-and-drop, where all of AV codecs must be considered, some regards to the file extension could be handy if lavf finds two close matches?

### Log file
[Log file](https://0x0.st/Hpyx.txt)

### Sample files
[SUP sample](https://0x0.st/Hpyv.sup)

**Comment by llyyr** [comment]
This should work with `--demuxer-lavf-probescore=27`

**Comment by cubicibo** [comment]
Right, thank you. I shall add this to my mpv config.

However, there may still be a more general with the `--sub-file=` parameter. It should only check against subtitle codecs, not exotic families like audio or video. Issue can be closed if maintainers don't believe this is an issue.

**Comment by llyyr** [comment]
> It should only check against subtitle codecs, not exotic families like audio or video.

That'd result files with video/audio/sub streams being unable to be used as just one of them for `--audio-file` or `--sub-file`. I don't think we want that.
