### ISSUE TITLE
Cycling subtitles/audio in a stream causes mpv to re-download the entire file, bug or expected behaviour?

### ISSUE THREAD

**Issue by TheCodingGuy** [mpv-player/mpv#12332]
If I open up a URL to a file with multiple subtitle or audio tracks and cycle/change them, the entire file gets re-download on each cycle or change. Example file can be found [here](https://github.com/ietf-wg-cellar/matroska-test-files#5-multiple-audiosubtitles).

Is this a bug or expected behaviour?

**Comment by Dudemanguy** [comment]
That's expected. Sine #12369 is a handy issue we have open for this topic. I'll close this.
