### ISSUE TITLE
PowerShell auto completion

### ISSUE THREAD

**Issue by kasper93** [mpv-player/mpv#12334]
Title explains everything, autocompletion script for PowerShell. 

Don't know if there are PowerShell enjoyers here, but if you are one feel free to contribute :) https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter

**Comment by Hrxn** [comment]
Love this idea

**Comment by stax76** [comment]
I wrote a PowerShell command line completion script for mpv, it can be found here:

https://github.com/stax76/mpv-scripts

**Comment by kasper93** [comment]
Fixed by #12967
