### ISSUE TITLE
Support for picking GPUs by index number

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#12335]

**Comment by llyyr** [comment]
You can just use profiles for this, I've been doing this since forever.

```
[amdgpu]
vulkan-device=amdsucks 

[i915]
vulkan-device=intelsucks
```
then to explicitly specify one of then, use --profile=amdgpu

**Comment by llyyr** [comment]
Actually, I'm just an idiot because `--vulkan-device=` autocomplete just works now (maybe it didn't before?) so I can get rid of my profiles. If you're using bash or zsh you should have these profiles too. If you're on Powershell then probably write an autocomplete script for it instead #12334
