### ISSUE TITLE
Current time display can be outside of the file while seeking [was: OSD glitchy when seeking with force-window]

### ISSUE THREAD

**Issue by ponyo** [mpv-player/mpv#1233]
To reproduce:
1. use force-window and no-video
2. put the OSD on level 2 so that you see the time
3. pause and seek to near the beginning of the file.
4. press a key that tries to seek backwards past the beginning of the file.

Result:

The OSD shows the wrong time and then fixes it so it ends up looking messy.

**Comment by ponyo** [comment]
Actually, this happens even without seeking. If you start paused at the beginning of the file, time 00:00, and press play mpv throws a minus sign in at the start. This is with an mp4 audio file.

**Comment by wm4** [comment]
That's probably a different problem. Can you post the mp4 file?
