### ISSUE TITLE
dithering confusion

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12336]
Hi,
I'm a bit confused. Dithering is showing no effect on SDR (bt.709) content. Does this only work on HDR content? Is this intended?

Thank you

**Comment by llyyr** [comment]
If you know your monitor's bit depth, then you should set `dither-depth` to that value instead of relying on auto. If you don't then just leave it on auto and hope you don't notice anything. It's year 2023 and we still can't rely on compositors/gpu drivers to correctly dither content.

**Comment by dokur0chan** [comment]
@llyyr is correct. I also want to add that figuring out your display's bit depth isn't really that difficult, you don't need to necessarily rely on `auto` if you're not sure.

On Windblows, just do:
Settings > System > Display > Advanced Display

Or check your output bit-depth in your GPU drivers.

**Comment by geextahslex** [comment]
My SDR TV has 8 bit depth. I use this:
dither-depth=8
dither=fruit
and it works flawlessly on HDR content. But has no visual effect on SDR (bt.709) content. Its shown in the statistics that it is running.

**Comment by dokur0chan** [comment]
The banding in those screenshots are in the source (looks like a web source). You will need `deband=yes` to mitigate that. Dithering will only get rid of color banding when there's a incongruency between the content bit-depth and your output bit-depth.

**Comment by kasper93** [comment]
>  Dither on
> Dither off

more like
> gpu-next
> gpu

Not sure what you are trying to show. I don't think vo gpu shows dithering in passes.

**Comment by geextahslex** [comment]
@kasper93 I use vo=gpu-next

**Comment by geextahslex** [comment]
But on HDR content it has remove artifacts. It makes a smooth transition between the black chunky parts and the surroundings

(watch/compare screenshots in full size) (settings: hwdec=no, vo=gpu-next)
dither off, deband off:
![dither off f](https://github.com/mpv-player/mpv/assets/139760266/10ebb7b1-e6bf-4c05-9bbb-1b4526177f40)
dither on: (dither-depth=8, dither=fruit)
![dither on](https://github.com/mpv-player/mpv/assets/139760266/7a81f02b-c9e6-41ac-8eee-f52191fa5f62)

**Comment by po5** [comment]
Because the extra data to do dithering only exists in high bit depth.

**Comment by geextahslex** [comment]
okay that makes sense. shame
