### ISSUE TITLE
How to test `libplacebo` new `ewa_lanczos4sharpest`?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12339]
I've tried 
```
libplacebo-opts=upscaler=ewa_lanczos4sharpest
libplacebo-opts=scale=ewa_lanczos4sharpest
scale=ewa_lanczos4sharpest
```
It doesn't seem to work, but if I use `libplacebo-opts=preset=high_quality` it will use the new `ewa_lanczossharp`.
So I have no way of testing the new `ewa_lanczos4sharpest`?

Related: https://code.videolan.org/videolan/libplacebo/-/merge_requests/560
Using https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230904

**Comment by llyyr** [comment]
libplacebo-opts=upscaler=ewa_lanczos4sharpest

**Comment by llyyr** [comment]
> Doesn't work, it's using the default scale=spline36 (edit: because I also use profile=gpu-hq)

You might be seeing the chroma down/upscaler being overridden with `cscale=spline36` instead. I might be wrong so @haasn would have to verify, but libplacebo will use the upscaler and downscaler for "plane_upscaler" and "plane_downscaler" by default, but if cscale is specified in mpv then that will get used instead.

**Comment by haasn** [comment]
> > Doesn't work, it's using the default scale=spline36 (edit: because I also use profile=gpu-hq)
> 
> You might be seeing the chroma down/upscaler being overridden with `cscale=spline36` instead. I might be wrong so @haasn would have to verify, but libplacebo will use the upscaler and downscaler for "plane_upscaler" and "plane_downscaler" by default, but if cscale is specified in mpv then that will get used instead.

yes, this. So you should override both, to use both

**Comment by christoph-heinrich** [comment]
> profile=gpu-hq
> vo=gpu-next
> video-sync=display-resample
> libplacebo-opts=preset=high_quality
> glsl-shader="~~/FSRCNNX_x2_16-0-4-1.glsl"
> libplacebo-opts=upscaler=ewa_lanczos4sharpest

You might want to use `libplacebo-opts-append=upscaler=ewa_lanczos4sharpest` instead, as it otherwise will overwrite the `libplacebo-opts=preset=high_quality`
