### ISSUE TITLE
How to use the --sub-file-paths 

### ISSUE THREAD

**Issue by tXJtqlb3bbeKD1yW8SV7** [mpv-player/mpv#12348]
Hi!

Can anyone shed a light at how I can make my old set up with `--sub-paths` work again? Prior to being deprecated, I had in my .conf file `sub-paths=C:\Users\UserName\Downloads\Youtube Subtitles` to auto-load my subtitles. However `sub-file-paths =C:\Users\UserName\Downloads\Youtube Subtitles` doesn't seem to work.

**Comment by Traneptora** [comment]
What do you mean by "it doesn't seem to work"? What happens? Can you post a log file?
