### ISSUE TITLE
Osc tick event

### ISSUE THREAD

**Issue by da3dsoul1** [mpv-player/mpv#12349]
I'm using my own osc spliced from old master.lua and some bits of random code from other people. In logs I get a message "[osc] The 'tick' event is deprecated and will be removed." in yellow color, do I need to worry about it?

Is there any way to fix this? What should I do?
![image](https://github.com/mpv-player/mpv/assets/111184581/0702d148-7c44-4aa4-9abe-5a8d7ec527c3)

**Comment by sfan5** [comment]
If you use a custom osc.lua you also need to maintain it according to updates to mpv.
So you'd need to apply the relevant changes, from a quick look this is at least commit 48f906249ef359c66fc6c5bf4cc5885c8293bf8e
