### ISSUE TITLE
2K or 4K videos with HDR10 downloaded with yt-dlp does not play perfectly

### ISSUE THREAD

**Issue by mayconhvab1** [mpv-player/mpv#12345]
hello developers
I currently use a basic gamer PC with an AMD Radeon R5 220 video card with 2 GB of video RAM, that is, an AMD Radeon R5 220
And when trying to play a video with this following information according to mediainfo:
General
Unique ID : 126781200258183244814378314232600698941 (0x5F612BC6692C163BCB693C449F1BA03D)
Complete name : C:\Users\User\Downloads\yt-dlp\Faces in 8k HDR [NC0WPQd_bds].mkv
Format: Matroska
Format version : Version 4
File size : 212 MiB
Duration: 2 min 59 sec
Overall bit rate : 9 911 kb/s
Framerate: 29,970 FPS
Writing application : Lavf60.11.100
Writing library : Lavf60.11.100
ErrorDetectionType : Per level 1

Video
ID: 2
Format: VP9
Format profile: 2
HDR format : SMPTE ST 2086, HDR10 compatible
Codec ID : V_VP9
Duration: 2 min 59 sec
Width: 2560 pixels
Height : 1440 pixels
Display aspect ratio: 16:9
Frame rate mode : Constant
Frame rate : 29,970 (30000/1001) FPS
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth: 10 bits
Language : English
Default: Yes
Forced: No
Color range: Limited
Color primaries : BT.2020
Transfer characteristics : PQ
Matrix coefficients : BT.2020 non-constant
Mastering display color pri : R: x=0.677980 y=0.321980, G: x=0.245000 y=0.703000, B: x=0.137980 y=0.052000, White point: x=0.312680 y=0.328980
Mastering display luminance : min: 0.0000 cd/m2, max: 1000 cd/m2
Maximum Content Light Level : 1100
Maximum Frame-Average Light : 180

Audio
ID: 1
Format: AAC LC
Format/Info : Advanced Audio Codec Low Complexity
Codec ID : A_AAC-2
Duration: 2 min 59 sec
Channel(s): 2 channels
Channel layout : L R
Sampling rate: 44.1 kHz
Frame rate : 43066 FPS (1024 SPF)
Compression mode : Lossy
Title : ISO Media file produced by Google Inc.
Default: Yes
Forced: No
VENDOR_ID : [0][0][0][0]

I can't reproduce perfectly, because of the many crashes and video taking time to load, can you kindly fix this?
It can also be checked several video compatibilities in 2K, 4K or even 8K for several video cards nVidia, Intel Graphics or AMD Radeon and other capabilities of playing videos in these qualities in HDR format: SMPTE ST 2086, HDR10 compatible

Downloaded using yt-dlp nightly and newer versions of FFmpeg nightly released today

With the VLC media player beta version 3.0.19 of September 5, 2023 I can play these video formats perfectly in HDR10 but in mpv there are several crashes and lack of rendering from what it seems to me

Thank you very much dear ones.

**Comment by mayconhvab1** [comment]
https://upload.disroot.org/r/WDKN1VTo#6HfdJwN6TWTck2/Q2We0xGiwGB6pzu3Iqe5T7YSJY+Q=

apologize for not uploading the video in the first place
I'll leave the video I downloaded with yt-dlp + FFmpeg nightly for review, because with the other players I can play them, some with HDR10 active and others not
Thank you very much in advance
Remembering that it is this video that is experiencing some crashes when playing it on my PC
Thanks in advance

**Comment by CounterPillow** [comment]
Where is your log file?
Backtraces?
Hello?
Stop wasting people's time.

**Comment by mayconhvab1** [comment]
> Onde está seu arquivo de log? Retrocessos? Olá? Pare de atrasar o tempo das pessoas.

You are totally wrong to say that I am wasting my time when the problem is occurring on my PC when playing with mpv
If you are a really polite and helpful person.. teach me how to put log files and rewinds here
Can you do this for me please?

**Comment by Isaacx123** [comment]
Try with:
`mpv --no-config --log-file=mpv.log`

**Comment by mayconhvab1** [comment]
> Experimente com: `mpv --no-config --log-file=mpv.log`

I really didn't understand how to do this. I just went to the folder where the mpv player is installed and typed CMD there, then I pasted the information: mpv --no-config --log-file=mpv.log

Then I wrote according to what is in the video for playback: mpv --no-config --log-file=mpv.log "%userprofile%\Downloads\yt-dlp\Faces 4K.mkv"

Then the file was played, but I couldn't copy the log file, I'm sorry to keep asking you for too much help, but with this method all my problems can be closed to the mpv of errors and can be fixed according to the settings of my PC.
Here is the information, but I believe it was not the result

https://imgur.com/a/e0nesuu

**Comment by Isaacx123** [comment]
You need to add the mpv directory to the PATH system variables to be able to invoke it through the CMD on any working directory.
See this [tutorial](https://www.c-sharpcorner.com/article/how-to-addedit-path-environment-variable-in-windows-11/).

**Comment by amariami** [comment]
> I really didn't understand how to do this.

Edit file mpv.conf in your mpv fokder path with notepad e.g. 

![2023-09-07 190127](https://github.com/mpv-player/mpv/assets/79769464/84dd43d2-6641-43cc-a001-64d7216816e3)

 ```
--no-config
--log-file="C:\Users\mpv\mpv64.txt" 
```

then upload your log file in here

**Comment by llyyr** [comment]
Putting `--no-config` in your mpv.conf doesn't do anything, you have to launch mpv from the command line with those args
