### ISSUE TITLE
Which fbo-format offers best quality 

### ISSUE THREAD

**Issue by YingDoge** [mpv-player/mpv#12342]
Good Morning Just a but confussed here, so what is the idfference between rgba16 vs rgba16f vs rgba16hf  and rgba32f. i have a 4090 and i want to have best quality which one should i chose.  

<img width="623" alt="image" src="https://github.com/mpv-player/mpv/assets/135021273/4a02d5be-dd18-4224-8dbd-cf8824fbe384">

Thanks For helping Out

**Comment by YingDoge** [comment]
> 

No I am Not.

**Comment by haasn** [comment]
Best for quality would be `rgba32f`

**Comment by rainlycoris** [comment]
What is the significance of the alpha channel in `rgba32f`? Is it a waste of space?

**Comment by ruihe774** [comment]
> What is the significance of the alpha channel in `rgba32f`? Is it a waste of space?

No actual difference between `rgba32f` and `rgb32f` imo. The latter is emulated by the GPU driver and its underlying storage is still `rgba32f.

**Comment by rainlycoris** [comment]
Thank you. I understand.
