### ISSUE TITLE
dvd:// doesn't work when connected via RDP

### ISSUE THREAD

**Issue by anthonyvdotbe** [mpv-player/mpv#12347]
### Important Information

Provide following Information:
- mpv version: mpv-x86_64-v3-20230903-git-[67368ac](https://github.com/mpv-player/mpv/commit/67368ac5d207a72dcec1488e112af00198c650db)
- Windows version: 11 (10.0.22621)
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/

### Reproduction steps

Environment: 2 Windows 11 PCs, named Client and Server

1. on Client, use Remote Desktop Connection to log into Server
2. on Server, mount an ISO file of a DVD (I expect a physical DVD would behave the same)
3. on Server, open a PowerShell window and open the DVD in mpv (assuming the assigned drive letter is E)
3.1 first with `& 'C:\Program Files\mpv\mpv.exe' -- 'dvd:///E:'`
3.2 then with `& 'C:\Program Files\mpv\mpv.exe' -- 'E:'`

### Expected behavior

The DVD opens in both steps 3.1 and 3.2

### Actual behavior

The DVD only opens in step 3.2; in step 3.1 the command returns without any window appearing and apparently nothing happening.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12538033/output.txt)

**Comment by Traneptora** [comment]
The log file says: `[   0.075][e][dvdnav] Couldn't open DVD device: E:`. Can you post the log file for step 3.1?

**Comment by anthonyvdotbe** [comment]
The attached log file was for step 3.1. I've attached log files for both steps below:

> & 'C:\Program Files\mpv\mpv.exe' -v -v --log-file=output-3.1.txt -- 'dvd:///E:'

gives: [output-3.1.txt](https://github.com/mpv-player/mpv/files/12559679/output-3.1.txt)

> & 'C:\Program Files\mpv\mpv.exe' -v -v --log-file=output-3.2.txt -- 'E:'

gives: [output-3.2.txt](https://github.com/mpv-player/mpv/files/12559685/output-3.2.txt)

**Comment by Traneptora** [comment]
What happens if you invoke it with `dvd://E:` rather than `dvd:///E:`? There appears to be an extraneous `/` there.

**Comment by anthonyvdotbe** [comment]
It gives a syntax error:

> [   0.011][e][dvdnav] number expected: 'E:'

since the syntax is `dvd://[title][/device]`. In this case `E:` is interpreted as the `title` part.

(complete output: [output-3.3.txt](https://github.com/mpv-player/mpv/files/12564869/output-3.3.txt))

For completeness, here's the log files for steps 3.1 and 3.2 when logged into the PC directly (i.e. without RDP). These cases both work, as expected:

[output-without-rdp-3.1.txt](https://github.com/mpv-player/mpv/files/12564889/output-without-rdp-3.1.txt)
[output-without-rdp-3.2.txt](https://github.com/mpv-player/mpv/files/12564890/output-without-rdp-3.2.txt)

**Comment by kasper93** [comment]
I don't know what to do here in practice. 

`_stat("E://", &statv);` works, `_stat("E:", &statv);` does not work. I would need to dig into Windows internals why exactly this happens over RDP, I suspect it has something to do with possibility to map host drives onto target machine and codepaths work differently. Don't know really, I frankly don't want to spend unreasonable amount of time to understand why Windows does that when there is not really any gain in fixing it.

You seem to request the later to work. I would suggest using `mpv dvd:///E://` which works always.

**Comment by anthonyvdotbe** [comment]
`mpv dvd:///E://` doesn't work either over RDP:

> & 'C:\Program Files\mpv\mpv.exe' -v -v --log-file=output.txt -- 'dvd:///E://'

gives: [output.txt](https://github.com/mpv-player/mpv/files/12616522/output.txt)

What I'm trying to do, is to play a specific DVD title over RDP. As far as I know, the only way to play a given title is with `dvd://`, but `dvd://` doesn't work over RDP.

**Comment by kasper93** [comment]
> mpv dvd:///E:// doesn't work either over RDP:

Works fine on my end. Could you try with backward slash too? `mpv dvd:///E:\`

**Comment by Traneptora** [comment]
What about `mpv dvd:// --dvd-device=E:`?

**Comment by kasper93** [comment]
> What about mpv dvd:// --dvd-device=E:?

It is exactly the same as `mpv dvd:///E:`
