### ISSUE TITLE
mpv android use hw/hw+ when opening a video or foward ,the screen will appear mosaic, black screen, graphic delay

### ISSUE THREAD

**Issue by nabbenbi** [mpv-player/mpv#12344]
https://github.com/mpv-player/mpv/assets/144125138/29dbd1b4-b635-45c7-b0f2-c598d06f969d

Everything works fine when using sw, but I want to find a solution because hw saves battery

**Comment by LaserEyess** [comment]
Wrong repository: https://github.com/mpv-android/mpv-android

**Comment by nabbenbi** [comment]
I'm a newbie and I don't understand what to do

**Comment by nabbenbi** [comment]
@sfan5
