### ISSUE TITLE
Libmpv stays at the last frame

### ISSUE THREAD

**Issue by DSxiaolong** [mpv-player/mpv#12357]
Libmpv version: latest version
Operating system: win10 x64

Can libmpv set to stay at the last frame after playing the video? The interface displays the last frame, not a black screen

**Comment by Dudemanguy** [comment]
I think you want to set the `keep-open` option.

**Comment by DSxiaolong** [comment]
> I think you want to set the `keep-open` option.

Thank you, thank you. I need this
