### ISSUE TITLE
tonemap visualization  does not work in conjuction with the use of --libplacebo-opts=preset

### ISSUE THREAD

**Issue by DeadSix27** [mpv-player/mpv#12359]
### Important Information

tonemap visualization does not work in conjunction with the use of --libplacebo-opts=preset

EDIT: This seems to be more of a libplacebo issue now that I think about it and it seems to only affect presets, correct me if I'm wrong.

Provide following Information:
- mpv version: 826ce82cad315f7a48f9c971d3a5fa005a9eab46
- Windows Version: 11
- Source of the mpv binary: self compiled (and also confirmed on shin's builds)

### Reproduction steps

Play HDR movie with: `mpv.com --no-config --vo=gpu-next --libplacebo-opts=preset=high_quality [file]`
Visualization doesn't show when using Shift-I (persistent stats overlay)

Play HDR movie with: `mpv.com --no-config --vo=gpu-next --libplacebo-opts=upscaler=ewa_lanczos4sharpest [file]`
Visualization DOES show when using Shift-I (persistent stats overlay)

### Expected behavior

Work no matter if using --libplacebo-opts=preset or not.

### Actual behavior

Only works when omitting --libplacebo-opts=preset

**Comment by haasn** [comment]
https://mpv.io/manual/master/#options-libplacebo-opts
> May override the effects of any other options set using the normal options system. 

Loading a preset discards all other options, including those that control the visualization.

**Comment by DeadSix27** [comment]
Question is, how would you use both?
```
libplacebo-opts=preset=high_quality
libplacebo-opts-append=visualize_lut=true
```
this will end up showing the visualization nonstop..
