### ISSUE TITLE
Playing files in mpv over dolphin sftp fills up /tmp and doesnt get cleared.

### ISSUE THREAD

**Issue by SloppyPuppy** [mpv-player/mpv#12363]
### Important Information
NOTE: Unsure if its a bug with dolphin or with mpv
Provide following Information:
- mpv version : 0.36.0-1
- Linux Distribution and Version : Arch Linux (6.4.12-zen1-1-zen, dolphin 23.08.0-1)
- Source of the mpv binary : Arch extra repository
- If known which version of mpv introduced the problem
- Window Manager and version : KDE Plasma 5.27.7, Kwin-X11
- GPU driver and version : mesa 23.1.6-4, lib32-mesa 23.1.6-4, mesa-utils 9.0.0-2
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. Configure a connection profile for a remote machine in .ssh/config
2. Create an entry in dolphin and point it to sftp://PROFILE_NAME
3. Connect to it by clicking on the entry, browse to a media file, open with mpv.

### Expected behavior
Files that are fetched over sftp in dolphin and played in mpv get deleted from /tmp automatically.

### Actual behavior
Files that are fetched over sftp in dolphin and played in mpv don't get deleted from /tmp automatically, and cause other things to stop working prompting a reboot to clear /tmp.

### Log file
Note: the log was edited to replace username (user) and filename(movie.mkv).

[mpv_log.txt](https://github.com/mpv-player/mpv/files/12565273/mpv_log.txt)

P.S I checked out the /tmp folder and the files taking up space are formatted as dolphin.(hash).part, that's how I initially found out what the issue was, however since I had to manually remove them from /tmp so the putter keeps working, rebooting the computer does infact clear /tmp, I know since I had this issue once couple days ago but didnt know the cause, I figure I could make my /tmp larger as a temporary solution, but well that is temporary.
Also reading the log and verbose while creating the log file notes "corrupted file", however this only starts happening once I seek through the video enough to fill /tmp

**Comment by sfan5** [comment]
> Note: the log was edited to replace username (user) and filename(movie.mkv).
> 
> [mpv_log.txt](https://github.com/mpv-player/mpv/files/12565273/mpv_log.txt)

The log doesn't show you playing a file from dolphin via sftp, does it? This is just playing a random mkv file and not related to the issue.

>  P.S I checked out the /tmp folder and the files taking up space are formatted as dolphin.(hash).part, that's how I initially found out what the issue was

mpv does not create files named like this, raise this issue with KDE/dolphin.
