### ISSUE TITLE
How to build mpv having 2 different versions of Lua installed?

### ISSUE THREAD

**Issue by fulalas** [mpv-player/mpv#12365]
I'm not here to judge the devs decision to not support Lua version >5.2.x. I understand and respect this decision.

What I would like to know is if there's a way to have let's say Lua 5.1.5 and Lua 5.4.6 installed at the same time in a way that mpv will look for 5.1.5 during build/runtime, ignoring Lua 5.4.6 installed on the system.

Or maybe a way to statically link **only** Lua.

I'm on Linux.

Thanks in advance!

**Comment by sfan5** [comment]
mpv does not specifically look for Lua 5.4 but you may have to set the `lua` meson option correctly for mpv to find your install of 5.1.
https://github.com/mpv-player/mpv/blob/fe875083b3d30b06ef77745f40570e8f63afec2b/meson_options.txt#L22-L28
