### ISSUE TITLE
Dimensions are incorrect since Shinchiro build 20230910 (be92223)

### ISSUE THREAD

**Issue by Jules-A** [mpv-player/mpv#12373]
### Important Information

Provide following Information:
- mpv version - v0.36.0-274-gbe922231
- Windows Version - Windows 10 22H2 19045.3393
- Source of the mpv binary - Shinchiro (v3)
- If known which version of mpv introduced the problem - 20230910 (be92223)
- Possible screenshot or video of visual glitches

![1](https://github.com/mpv-player/mpv/assets/1760158/28aca899-690b-4e1c-9380-f473cc0b4e0b)
![2](https://github.com/mpv-player/mpv/assets/1760158/b3767141-0042-4d47-9f7a-5dee8ea24105)

### Reproduction steps

Reproducible with -no-config but here's mine: 
[mpv.conf.txt](https://github.com/mpv-player/mpv/files/12568167/mpv.conf.txt)

Literally just play any video that's below native res.

### Expected behavior

Detect correct native resolution and scale to the correct dimensions.

### Actual behavior

Dimensions are completely off causing it to switch to different shader profiles and seems to increase GPU usage a bit. I'm not sure but there may be other consequences like reduced image quality.

### Log file
[mpv.log.txt](https://github.com/mpv-player/mpv/files/12568180/mpv.log.txt)

**Comment by Jules-A** [comment]
Hmm... Actually it looks like the scaled resolution was incorrect (unless that's supposed to happen??) even on prior versions:
![1](https://github.com/mpv-player/mpv/assets/1760158/4a5ab456-b4f7-4a7c-95e4-97404a0a6e57)
![2](https://github.com/mpv-player/mpv/assets/1760158/b23b2829-ee98-44d1-9f38-76c3557350a2)

But it was detecting the native video resolutions correctly before, no idea out "output resolution" as that wasn't tracked in osd before.

**Comment by kasper93** [comment]
Works as expected this are true native dimensions of the video frame.

You can control this by `--vd-apply-cropping`.

Incidentally it will be changed to default for unrelated issue with sampling in certain cases. See: https://github.com/mpv-player/mpv/pull/12367

**Comment by Jules-A** [comment]
> Works as expected this are true native dimensions of the video frame.

I really don't get it but okay... Currently my profiles are based on height: ```
[720-1080p]
profile-desc=Shaders for 720/1080p
profile-cond=height <= 1080
profile-cond=height > 540
dscale=catmull_rom
glsl-shaders="~~/shaders/ravu-zoom-ar-r3g.hook;~~/shaders/nlmeans_light3.glsl;~~/shaders/FSRCNNX_x2_16-0-4-12.glsl;~~/shaders/CAS4.glsl;~~/shaders/Anime4K_Thin_HQ5.glsl;~~/shaders/KrigBilateral.glsl"
``` 
But simply using height appears to use the native pre-cropped values, is that also correct?

**Comment by kasper93** [comment]
There are two types of params. `video-params` that show frame size out of the decoder and `video-out-params` that show frame size after crop, decoder, container (soon) or manual.

It depends what you want to do. And also mentioned `--vd-apply-cropping` changes frame size out of the decoder, because we directing it to apply decoder crop or not.
