### ISSUE TITLE
Why mpv still loads disabled mkv subtitles and why I can't disable embedded subtitles?

### ISSUE THREAD

**Issue by infini667** [mpv-player/mpv#12376]
I'm trying to disable embedded subtitles, but there's no config to disable only embedded subtitles, so I tried to edit a mkv file header to disable the subtitle track. But mpv is loading the subtitle anyway, even if it's disabled. Is it normal for the mpv to do this? I want only external subtitles, I don't want the embedd ones to be loaded. That way I will have to remux all the mkv files to remove the sub tracks. :/
Is there another way to do this? Like a config to disable loading only subtitle tracks from mkv files?

Windows 11 
mpv 0.36.0.174 shinchiro build

Tested with no config and no scripts.

Log: https://pastebin.com/83LCF1kT

**Comment by CounterPillow** [comment]
wow you didn't follow the issue template :/

**Comment by infini667** [comment]
> wow you didn't follow the issue template :/

edited... thanks

**Comment by Dudemanguy** [comment]
Update your mpv. This commit was from when the `--slang=auto` option impacted subtitle selection. It shouldn't do that anymore.

**Comment by infini667** [comment]
> Update your mpv. This commit was from when the `--slang=auto` option impacted subtitle selection. It shouldn't do that anymore.

I think you didn't understand... is not the sub selection, is the sub loading. I don't want to LOAD any embedded subs, only external subs. mpv is still loading (even if it's not selecting) a subtitle track that was DISABLED in the mkv file header (I edited the file header using mkvtoolnix).

**Comment by Dudemanguy** [comment]
Wait what? You're just unhappy that mpv understands there's a subtitle track in your file? If it's not selecting it, why do you care?

**Comment by infini667** [comment]
> Wait what? You're just unhappy that mpv understands there's a subtitle track in your file? If it's not selecting it, why do you care?

Because I want to cycle between 2 and just 2 external subtitles of 2 different languages. Some files have like 10 embedded subtitles and I have to cycle between all of them.

**Comment by Dudemanguy** [comment]
Well there is the enabled flag in mkv. And we do simply ignore I believe. I presume what you've been doing is disabling that flag. Not really sure how desirable actually listening to that flag would be... so I'll just mark it as a feature request for now I guess.

**Comment by infini667** [comment]
Yes... thanks! Or just an option to disable loading embedded subs, in the config file.

**Comment by fidodido48** [comment]
I agree there should be an opt. for more control over subs loading.
For example im using a template which has subs opt. enabled/active, but there are times id like to disable/not load subs at all (ie. listening to yt music) and mpv lacks an easy way to do it, so now i have to write an alias/function/new template...
Would fancy: 
```
--no-load-subs            # disable loading subs completely
--no-load-embed-subs      # disable loading embed/internal subs
--no-load-ext-subs        # disable loading external subs
```
