### ISSUE TITLE
How to listen for libmpv pause status events?

### ISSUE THREAD

**Issue by DSxiaolong** [mpv-player/mpv#12379]
I want to know if libmpv is currently playing or paused. What should I do to obtain real-time event feedback? I don't want to proactively inquire.

  
Just like this:
```cpp
  void MpvWidget::handle_mpv_event(mpv_event *event)
{
    switch (event->event_id)
    {
    case MPV_EVENT_END_FILE:
        {
            qDebug()<<"event-->MPV_EVENT_END_FILE";
            break;
        }
    case MPV_EVENT_START_FILE:
        {
            qDebug()<<"event-->MPV_EVENT_START_FILE";
            break;
        }
    case MPV_EVENT_FILE_LOADED:
        {
            qDebug()<<"event-->MPV_EVENT_FILE_LOADED";
            break;
        }

    default: ;
        // Ignore uninteresting or unknown events.
    }
}
```

**Comment by Dudemanguy** [comment]
You should observe the `pause` property for any changes.

**Comment by DSxiaolong** [comment]
> You should observe the `pause` property for any changes.

Can the pause attribute be actively notified?     

···cpp
//This doesn't work
mpv_observe_property(mpv, 0, "pause", MPV_FORMAT_INT64);
```

**Comment by Dudemanguy** [comment]
After you observe it, you'll receive the `MPV_EVENT_PROPERTY_CHANGE` event which you can then use to determine what property changed and to what value.

**Comment by DSxiaolong** [comment]
> 



> After you observe it, you'll receive the `MPV_EVENT_PROPERTY_CHANGE` event which you can then use to determine what property changed and to what value.

Thank you for your help. I have solved the problem


```cpp
if (strcmp(prop->name, "pause") == 0)
        {
            if (prop->format == MPV_FORMAT_FLAG) {
                int pause = *(int *)prop->data;
                qDebug()<<"pause:"<<pause;
            }
        }
```
