### ISSUE TITLE
Squarish artifacts when using antiring with a Polar downscaler.

### ISSUE THREAD

**Issue by Isaacx123** [mpv-player/mpv#12375]
### Important Information

Polar filters 

Provide following Information:
- mpv v0.36.0-274-gbe922231
- Windows 10 21H2 19044.3324
- [shinchiro daily builds](https://github.com/shinchiro/mpv-winbuild-cmake/releases)
- N/A
- Possible screenshot or video of visual glitches:

Reference screenshot downscaled with Mitchell:

![reference](https://github.com/mpv-player/mpv/assets/75648063/aae90a61-baba-43c2-8b6e-bcdb65599f37)

Screenshot with artifacts downscaled with EWA_RobidouxSharp plus AR at 0.5 strength: 

![ewa_robidouxsharp+ar](https://github.com/mpv-player/mpv/assets/75648063/96676449-f666-4134-9468-dfc0a24c35b1)

Screenshot **without** artifacts downscaled with EWA_RobidouxSharp and **no** AR:

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/75648063/d115ee1d-4bf8-463c-af89-48b0f6a8e70c)

It also happens with non-Cubic/Mitchell-Netravali filters like EWA_Lanczos:

![mpv-shot0002](https://github.com/mpv-player/mpv/assets/75648063/e58d7164-ec70-4a0d-aa36-d00bf67cdeff)

The artifacts become more evident with a higher AR strength, EWA_RobidouxSharp plus AR at 1.0 strength:

![mpv-shot0003](https://github.com/mpv-player/mpv/assets/75648063/e86134f9-08aa-4fdb-b39f-792c482baf64)

Orthogonal filters like Catmull_Rom or Mitchell don't present any issues, Catmull_Rom plus AR at 0.5 strength: 

![mpv-shot0004](https://github.com/mpv-player/mpv/assets/75648063/2deffab1-f588-42f1-834a-173d922a20b9)

### Reproduction steps

mpv --no-config --vo=gpu-next --gpu-api=vulkan --correct-downscaling=yes --linear-downscaling=yes --dscale=mitchell --autofit=1760x990 --log-file=mpv.log --screenshot-format=png --screenshot-high-bit-depth=no test-clip.mkv

mpv --no-config --vo=gpu-next --gpu-api=vulkan --correct-downscaling=yes --linear-downscaling=yes --dscale=ewa_robidouxsharp --scale-antiring=0.5 --autofit=1760x990 --log-file=mpv.log --screenshot-format=png --screenshot-high-bit-depth=no test-clip.mkv

mpv --no-config --vo=gpu-next --gpu-api=vulkan --correct-downscaling=yes --linear-downscaling=yes --dscale=ewa_lanczos --scale-antiring=0.5 --autofit=1760x990 --log-file=mpv.log --screenshot-format=png --screenshot-high-bit-depth=no test-clip.mkv

mpv --no-config --vo=gpu-next --gpu-api=vulkan --correct-downscaling=yes --linear-downscaling=yes --dscale=ewa_robidouxsharp --scale-antiring=1 --autofit=1760x990 --log-file=mpv.log --screenshot-format=png --screenshot-high-bit-depth=no test-clip.mkv

mpv --no-config --vo=gpu-next --gpu-api=vulkan --correct-downscaling=yes --linear-downscaling=yes --dscale=catmull_rom --scale-antiring=0.5 --autofit=1760x990 --log-file=mpv.log --screenshot-format=png --screenshot-high-bit-depth=no test-clip.mkv

### Expected behavior

Downscaling without artifacts while AR is active. 

### Actual behavior

Dithering like squarish artifacts. 

### Log file

[ewa_robidouxsharp+ar50.log](https://github.com/mpv-player/mpv/files/12569966/ewa_robidouxsharp%2Bar50.log)

[catmull_rom+ar50.log](https://github.com/mpv-player/mpv/files/12569971/catmull_rom%2Bar50.log)

### Sample files

https://0x0.st/Hffj.mkv

**Comment by Isaacx123** [comment]
Forgot to add that the artifacts become bigger or smaller depending on the target resolution:

Bigger artifacts at 1046p:
![mpv-shot0002](https://github.com/mpv-player/mpv/assets/75648063/97f6f243-5145-4146-9b95-9632d19185ca)

Smaller artifacts at 810p:
![mpv-shot0001](https://github.com/mpv-player/mpv/assets/75648063/50e6c0e0-193e-411a-93b4-3be6b057aeb9)

**Comment by Artoriuz** [comment]
Can you reproduce it with [this shader](https://github.com/Artoriuz/glsl-pixel-clipper) as well (turn the native AR off if you want to give it a shot)?

**Comment by bjin** [comment]
The following patch fixed the artifacts for me:

~~~diff
diff --git a/src/shaders/sampling.c b/src/shaders/sampling.c
index efa69dd8..53ea52bd 100644
--- a/src/shaders/sampling.c
+++ b/src/shaders/sampling.c
@@ -480,7 +480,7 @@ static void polar_sample(pl_shader sh, pl_filter filter,
             @for (c : comp_mask) {                              \
                 cc = vec2(${float: scale} * c[@c]);             \
                 cc.x = 1.0 - cc.x;                              \
-                ww = cc + vec2(0.07);                           \
+                ww = cc + vec2(0.1);                            \
                 ww = ww * ww;                                   \
                 ww = ww * ww;                                   \
                 ww = ww * ww;                                   \
~~~

It seems that `0.07^33` underflows the range of `float32` by just a little bit, and this issue becoming even more problematic with `--linear-downscaling` (samples much closer to zero).
