### ISSUE TITLE
use mouse scroll to go up or down in audio or subtitle tracks

### ISSUE THREAD

**Issue by rezad1393** [mpv-player/mpv#12377]
right now user clicks on audio or subtitles to go through the those one by one and only in increasing number.

![Screenshot_20230911_083241](https://github.com/mpv-player/mpv/assets/7523164/02803456-5f09-41d3-bef3-4246a97c6772)

so first click goes from selected subtitles to the next one.

now if the media has a lot of audio (or more usual, a lot of subtitles) then the user has to be very careful to select the subtitle by clicking and more more excess click would force him to go back from start of list again.

my suggestion is that when mouse is hovering over subtitle (or audio track) number, then scrolling the mouse would go up/down through the list so user can select the subtitle track easily.

**Comment by rezad1393** [comment]
thank you.

**Comment by plashenkov** [comment]
What's the reason wheel down increases audio track / subtitle number, and wheel up decreases?
