### ISSUE TITLE
sub-ass-override does not switch subtitle appearance while watching

### ISSUE THREAD

**Issue by Niotferdi** [mpv-player/mpv#12386]
### Important Information

Provide following Information:
- mpv version: 0.36
- Windows Version: Windows 10 21H1
- Source of the mpv binary: Sourceforge (shinchiro)

### Reproduction steps

Load a video file accompanied by formatted subtitles in ass format. Use overridden ass styles (`--sub-ass-styles=`). Add the `<KEY> cycle-values sub-ass-override "no" "yes"` option to input.conf to switch the subtitle design between built-in and custom while watching a video. Press this key while watching a video (when it is not paused).

### Expected behavior

By pressing the key, the subtitle design will change from what it was to what the user selected.

### Actual behavior

There is no change in design. The subtitles remain with the same design as they were. Also, the next phrase in the subtitles disappears, or the next 2-3 after the one at the moment the user pressed the key. If you rewind time forward and backward, all the phrases become visible.

You can avoid this by entering `cycle-values sub-ass-override "no" "yes"` when the video is paused, and then reloading the subtitles (for example, `set sid 0`, then `set sid 1`)

### Log file

https://pastebin.com/8Jt5c6AF

**Comment by Dudemanguy** [comment]
`sub-ass-override` seems to require `UPDATE_SUB_HARD`. I'm not sure why it's not already like this actually.
