### ISSUE TITLE
subs-auto=fuzzy and subs-fallback=yes should be default

### ISSUE THREAD

**Issue by raphael-costa** [mpv-player/mpv#12389]
Who are we lying to? The vast majority of people here are using mpv to watch torrented anime.

For many years I oftentimes had to manually select a subtitle track in some torrented anime because mpv would default to not having any selected. Subtitles with file names that differ from the video file itself were also a headache.

Sure, a very minor one.

This suggestion is very low priority but also extremely easy to implement.

As a bonus, I believe hr-seek=yes with a lower SEEK value (I use 3) is more intuitive and it makes it easier to rewatch cool scenes.

**Comment by Dudemanguy** [comment]
`subs-fallback=yes` is not really sensible default since that would also cause subtitles to be enabled regardless of whatever the tags the tracks have or do not have. I'm not sure what anime files you are finding out there that don't tag the sub track as default. Seems strange. You can also just set `--slang`.

`subs-auto=fuzzy` by default is maybe sensible. Dunno, no strong feelings there.

**Comment by raphael-costa** [comment]
Many torrents have an "unknown" sub track, I'm not talking about susplease or those CR rips, I'm mostly referring to some smaller fansub groups who make subtitles for shows that have already ended, you can find plenty of those on animebytes and other private trackers.

Two examples of recent anime I watched are Cautious Hero by NH and Seikon no Qwaser (yep, I know) by Kira-Fansub. These smaller groups are very attractive as they often make higher quality subs, for example Kira-Fansub translated all the Russian parts.

> But then again, one line in your conf isn't going to kill you.

Only a very small percentage of the userbase will dig through the manual to find these well-hidden flags.

**Comment by po5** [comment]
Sounds like you're running into issues with the 0.36 release that has really stupid track selection defaults, update to latest git. Would be easy to check if you provided a log.

**Comment by dyphire** [comment]
This `subs-auto=fuzzy` option may not shoule be the default, as it will bring some unexpected subtitle matching behavior.
For example, if you have these files in the same directory:
```
test.mp4
test.srt
test.en.srt
test.en-US.srt
videoname.mp4
videoname.test.srt
```
This `subs-auto=fuzzy` option will load the subtitle of `videoname.test.srt` for the video file of `test.mp4`.

**Comment by guidocella** [comment]
> This `subs-auto=fuzzy` option may not shoule be the default, as it will bring some unexpected subtitle matching behavior. For example, if you have these files in the same directory:
> 
> ```
> test.mp4
> test.srt
> test.en.srt
> test.en-US.srt
> videoname.mp4
> videoname.test.srt
> ```
> 
> This `subs-auto=fuzzy` option will load the subtitle of `videoname.test.srt` for the video file of `test.mp4`.

We changed the cover-art-auto default from fuzzy to exact because of this: https://github.com/mpv-player/mpv/pull/8943#issuecomment-983504528

**Comment by Dudemanguy** [comment]
>We changed the cover-art-auto default from fuzzy to exact because of this: https://github.com/mpv-player/mpv/pull/8943#issuecomment-983504528

Oh yeah I forgot about this. That's a negative too then. OP if you are indeed having weird subtitle selection because of 0.36 that is supposed to be fixed now. `--subs-fallback` is `default` which should be what most people expect.
