### ISSUE TITLE
Use [--vo] or [--libplacebo-opts] in transcoding

### ISSUE THREAD

**Issue by vslmc** [mpv-player/mpv#12382]
- mpv version v0.36.0-275-g6f83529f
- windows 11 
- build by Shinchiro

Atm it's not possible to encode with mpv while using internal filters like dither , color manipulation/icc profiles, scalers etc all the good stuff.
I think the problem is mpv doesnt support or simply cant use --vo for encoding (i.e. gpu-next)
I noticed the addition of libplacebo-opts , but these can't be used without --vo
Using --vf=libplacebo also is not supported , what i think is strange because ffmpeg can use it; but why not from within mpv?

Any plans to add support for built-in filters ?

I try to get as far away as possible from ffmpeg if i want to encode manually because its just a nightmare to use.
MPV is so freshing easy , just create a perfect readable config , pipe mpv to the encoder of my choice and hit enter. If we just could use it's full potential, that would be great.

I'm sure there is a good reason and propably GPU accel is to blame but the possibility to use filters, vapoursynth and shader in an easy managable way just tickels my brain. (Of course a chain of events would be good as you might want to upload to gpu to decode use shaders and some vapursynth scripts, download to cpu to use filters and some cpu based vs scripts again. Or any order you like)

Thank you for reading

### Reproduction steps

Try any command line arguments I mention above 

### Expected behavior

Working

### Actual behavior

Not working

**Comment by vslmc** [comment]
Thank you for the information , it's not an issue with mpv and I have to wait for the fix

If I can extend my above question I would like to know if it's possible to pipe to another program from within the mpv.config, eather with | and yuf4mpegpipe or a direkt method

**Comment by Dudemanguy** [comment]
`--vo` and `--libplacebo-opts` cannot ever work with encoding. Instead what you can do, as previously mentioned, is use the `vf_libplacebo` instead and pass the equivalent options there.
