### ISSUE TITLE
How can I know if the video has finished playing?

### ISSUE THREAD

**Issue by DSxiaolong** [mpv-player/mpv#12380]
When I set `keep open=yes`, how do I know if libmpv has played to the end of the video and if there is an event notification that can inform me?
`mpv_set_option_string(mpv, "keep-open", "yes");`

```cpp
void MpvWidget::handle_mpv_event(mpv_event *event)
{
    switch (event->event_id)
    {
    case MPV_EVENT_END_FILE:
        {
            qDebug()<<"event-->MPV_EVENT_END_FILE";   //This doesn't work ?
            break;
        } 
    }
}

```

**Comment by Dudemanguy** [comment]
You can observe the `eof-reached` property. It will be true when you're using `keep-open` and playback and finished.

**Comment by DSxiaolong** [comment]
> You can observe the `eof-reached` property. It will be true when you're using `keep-open` and playback and finished.

Thank you for your help. I have resolved it
