### ISSUE TITLE
Capture x,y location of mouse pointer click, with time

### ISSUE THREAD

**Issue by apiszcz** [mpv-player/mpv#12392]
How would one capture the x,y mouse location when the left button is depressed along with the time?
Goal: capture locations with time and write to a file.

**Comment by CounterPillow** [comment]
read the `mouse-pos` property, and the `time-pos` property

**Comment by apiszcz** [comment]
Thank you chatgpt

local file = io.open("clicks.txt", "w")

mp.add_forced_key_binding("MOUSE_BTN0", "capture_click", function()
    local time = mp.get_property_number("time-pos")
    local x, y = mp.get_mouse_pos()
    file:write(string.format("%.2f, %.2f, %.2f\n", time, x, y))
end)

mp.register_event("shutdown", function()
    file:close()
end)

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/issues/9899#issuecomment-1047899437 prints the click position in the source video rather than in the window.
