### ISSUE TITLE
libplacebo integration with mpv

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12402]
(This can be very well be a stupid question, and I am not an expert)

I noticed that libplacebo added ewa_lanczossharp ([merge request](https://code.videolan.org/videolan/libplacebo/-/merge_requests/560))
That means that in order to use it you'll have to use `libplacebo-opts=upscaler=ewa_lanczos4sharpest`
Great, so far I understand.

Now, because that's a libplacebo option, and not a mpv option, you can't use `scale=ewa_lanczos4sharpest`,
So it has to be added by [pull request](https://github.com/mpv-player/mpv/pull/12399) which will copy-paste the values from libplacebo to mpv.
This is the part which I 50% understand and makes me wonder why this feature (in this case: `ewa_lanczos4sharpest`) to be "added" twice.

Can't mpv (or libplacebo) just read one another and be "unified" (if that makes sense)?

I believe this is what's called an API (could be wrong).

I'm not saying that I know what I'm talking about, I'm just saying that it looks like everything that is changing on libplacebo end has to change (again) over on mpv.
I'm just thinking there must be a better way for changes in libplacebo to be integrated with mpv.

Example:
mpv will "read" libplacebo upscalers (which in this case are `const struct pl_filter_config * const pl_filter_configs[] = {` (if I'm not mistaken) from here https://code.videolan.org/videolan/libplacebo/-/blob/master/src/filters.c#L891 )
and it order to use them - mpv will remove the prefix `pl_filter_` to be able to remain backward compatiable with the current `scale` options, and now users will be able to use every upscaler from libplacebo. (please ignore the fact that they already can use them by using `libplacebo-opts=upscaler=`)

This was just an example, I could be entirely wrong and possibly made myself look stupid here, but I do want to help if I can.
This is not the first time I've noticed changes that have to be "applied" twice.

**Comment by haasn** [comment]
This would be considerably easier to do if not for the existence of `vo_gpu`, which `vo_gpu_next` still has to share its options parsing code with. `--scale` is a perfect example, because it goes through `validate_scaler_opt` which only reads from the `vo_gpu` list of scalers to check what the valid values are. So even if libplacebo supports some scalers that mpv doesn't, the fact that `vo_gpu` doesn't support those scalers is exactly what *prevents* `vo_gpu_next` from automatically picking them up.

Without `vo_gpu` we could simply delete all of these options or define a much more lightweight way of mapping them to their libplacebo analogs.

**Comment by llyyr** [comment]
libmpv allows you to use the mpv rendering mechanisms to build your own video player, see downstream projects like Celluloid or Haruna for example which utilize libmpv. Not to mention macOS support on mpv itself currently relies on libmpv. You can't use gpu-next on Mac.

There's also a issues with opengl performance with gpu-next, but this one's minor.

> vo_gpu developer quit while vo_gpu_next developer is active.

There wasn't really a specific "vo_gpu developer", most of the work on it was done jointly by wm4 and haasn.

> So I guess mpv has to keep vo_gpu until libmpv is added to vo_gpu_next?

This is an if, not a when. Based on what I gathered from discussions, nobody is interested in doing the work that comes with trying to integrate gpu-next with libmpv so someone else has to step up for it to get done most likely.
