### ISSUE TITLE
autoload.lua is broken by commit 24cedfe

### ISSUE THREAD

**Issue by danildf** [mpv-player/mpv#12400]
- mpv version 0.36.0
- Gentoo
- Self built

### Reproduction steps

Use latest autoload.lua from commit 24cedfe. Previous commit df3a0fa works fine.

### Expected behavior

Works fine.

### Actual behavior

Throws [autoload] Lua error: /home/traveler/.config/mpv/scripts/autoload.lua:187: attempt to index upvalue 'extensions' (a nil value)

**Comment by christoph-heinrich** [comment]
You use recursive directory loading right?

**Comment by Dudemanguy** [comment]
Works for me. What lua version are you using?

**Comment by danildf** [comment]
Yes, recursive loading.
Lua 5.4.6
