### ISSUE TITLE
How to use vo=dmabuf-wayland?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#12404]
It just keeps saying that I don't have the driver.

### Log file

[dmabuf_fail.txt](https://github.com/mpv-player/mpv/files/12640924/dmabuf_fail.txt)

**Comment by llyyr** [comment]
This ignores the template. It's impossible to help you without knowing your compositor

**Comment by laichiaheng** [comment]
I just try it on Weston, and it works, but it doesn't work in Gnome 44.4

**Comment by llyyr** [comment]
Only GNOME 45 or newer supports [nv12](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2191) and [p010](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3244) which are needed for dmabuf-wayland.

**Comment by laichiaheng** [comment]
Thanks, it solves my problem.
