### ISSUE TITLE
vo_gpu_next: Polar antiringing causes colored speck-like artifacts at fractional scale factors

### ISSUE THREAD

**Issue by dokur0chan** [mpv-player/mpv#12403]
### Important Information
```
mpv v0.36.0-294-g3972fd1b Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sep 16 2023 00:35:06
libplacebo version: v6.292.0-370-gdde4e7c-dirty
FFmpeg version: N-112098-g156f53e98
FFmpeg library versions:
   libavutil       58.24.100
   libavcodec      60.26.100
   libavformat     60.12.101
   libswscale      7.3.100
   libavfilter     9.11.100
   libswresample   4.11.100
```
- Windows 11 Build 22621
- [shinchiro Windows binaries](https://github.com/shinchiro/mpv-winbuild-cmake)
### Reproduction steps
Use a polar filter for `--scale` and `--cscale` and enable antiringing. Scale the video at a fractional factor.

### Expected behavior
Polar antiringing doesn't cause artifacts when fractionally scaling the image.
### Actual behavior
Polar antiringing causes artifacts when fractionally scaling the image.

`--no-config --vo=gpu-next --profile=gpu-hq --scale=ewa_lanczossharp --cscale=ewa_lanczossharp --screenshot-format=png`

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/139610756/b658dc1e-4f35-4a1a-86c7-a8bfc183a6c3)

`--no-config --vo=gpu-next --profile=gpu-hq --scale=ewa_lanczossharp --cscale=ewa_lanczossharp --scale-antiring=0.8 --screenshot-format=png`

![mpv-shot0002](https://github.com/mpv-player/mpv/assets/139610756/2ea266b7-7d55-4505-af8f-705304493a33)

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/12639762/mpv.log)

**Comment by dokur0chan** [comment]
Actually, it seems like I misdiagnosed the issue while testing. Anascaling doesn't matter here. It seems like this is only caused by fractional scale factors in general. The issue is not prevalent at exact whole scale factors such as 1.00x or 2.00x.

`--window-scale=2`

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/139610756/4b0062a6-440a-4c6d-8375-2ea3cdf9deeb)

`--fs` (2.25x factor with black bars cropped just to keep it tidy)

![mpv-shot0002_crop](https://github.com/mpv-player/mpv/assets/139610756/403021db-3bd1-49f1-972c-1fda7c305c9f)

**Comment by bjin** [comment]
I can't reproduce with either `--gpu-api=opengl` and `--gpu-api=vulkan` (on Linux).

Could you please to the following?

1. Post the video clip for testing.
2. Test with  `--gpu-api=opengl` and `--gpu-api=vulkan` on Windows.
3. Remove `--scale=ewa_lanczossharp` and test again.
4. Remove `--cscale=ewa_lanczossharp` and test again.

**Comment by wiwaz** [comment]
I cant seem to reproduce on small scale factors (1080 -> 1440 and such) but trying to upsample SD video for example does show the issue.

**Comment by dokur0chan** [comment]
1. The screenshots for my OP post and the follow-up are technically from different sources, but here's a DVD source that I can still repro this with: https://files.catbox.moe/mss0py.mkv
2. Both backends still produce the issue.
3. Removing `--scale` gets rid of the issue... but if this occurs on the chroma plane I doubt I would be able to notice it anyways.
4. Still causes it. But if you mean getting rid of both `--scale` and `--cscale`, then yeah, it resolves the issue.

**Comment by dyphire** [comment]
Can be replicated

**Comment by bjin** [comment]
https://code.videolan.org/videolan/libplacebo/-/merge_requests/585
