### ISSUE TITLE
A B Loop (Continuously Loop a Section of a Video)

### ISSUE THREAD

**Issue by noctuid** [mpv-player/mpv#1241]
This is a feature that I miss from other media players. I looked through the documentation, input.conf, and issues here and could not find anything, so unless I missed something, there currently is no A B loop feature in mpv.

It would be nice to be able to mark a start and end position to replay. I find this useful, for example, when I'm working on learning a part of something (e.g. to play a certain part of a song; it's pretty tedious to manually go back every 5 seconds). It would also be nice if there was something like `${time-pos-a}` and `${time-pos-b}`, so that the positions could be passed to a shell script.

As for implementation, I think it would be preferable to have separate keys for marking position A and B and for stopping the loop (this way the beginning and ending points could be adjusted within the loop). Having a key that would set A, set B, then stop the loop might also be nice.

**Comment by slrslr** [comment]
@ghost despite MPV states there is AB loop in manual page: "l Set/clear A-B loop points." it never looping for me.
I have tried l, Shift+L toggle different keyb. layout and repeat but no luck.

As a workaround (would be better if it works in MPV out of the box) i did:

`wget -c https://raw.githubusercontent.com/unusualpepe/mpv-multiloop/master/multiloop.lua -P ~/.config/mpv/scripts/`

Start mpv

Shift+M

Shift+1 (or 1 on english keyboard)
Shift+2 (or 2 on english keyboard)
l to start looping

**Comment by avih** [comment]
> despite MPV states there is AB loop in manual page: "l Set/clear A-B loop points." it never looping for me.

It does work. You probably have it bound to something else, either at your `input.conf` or some script force-binds it.

Try `--no-config` to disable all scripts and user key bindings.

Also, if you still have issues with a-b-loop, please file a new issue instead of posting at an irrelevant 7 years old issue.

**Comment by slrslr** [comment]
@avih --no-config worked

so i have located mpv conf file in:
ls -l /home/$(whoami)/.config/mpv
nano /home/$(whoami)/.config/mpv/mpv.conf
and commented out custom lines in it (prefix by \#), especially one starting "l "
and now it works even without --no-config

Hopefully it will help others, thank you.
