### ISSUE TITLE
Container cropping introduces subtitle shift

### ISSUE THREAD

**Issue by LightArrowsEXE** [mpv-player/mpv#12422]
### Important Information

Provide following Information:
- mpv version: v0.36.0-310-ged5c744a
- Platform and Version: Windows 11
- Source of the mpv binary: [link](https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-09-18-ed5c744)

### Reproduction steps

Create a subtitle file (such as an ASS) one, create a video with cropping added in the container metadata and one without, and drag the subtitle in both.

### Sample files

Examples:

Screenshot from Aegisub (latest arch1t3ct version) with subtitle dimensions: 711x480 (the active area of this anamorphic video)):
![image](https://github.com/mpv-player/mpv/assets/42927908/3e98d899-35a9-4a4e-8541-529d84488266)

mpv without container cropping:
![mpv-shot0025](https://github.com/mpv-player/mpv/assets/42927908/3d206756-189e-4525-80a3-21b70bfd0266)

mpv with container cropping (left=4, top=0, right=5, bottom=0):
![mpv-shot0022](https://github.com/mpv-player/mpv/assets/42927908/446b2716-2f52-48d1-8334-513732c64838)

mpv with the previous container cropping and original subtitles shifted to the left by 4 (to match `x`):
![mpv-shot0023](https://github.com/mpv-player/mpv/assets/42927908/84fa43b9-deba-4f19-a360-5bc626bdde84)

**Comment by llyyr** [comment]
Can you provide a sample? `blend-subtitles=yes` fix it?

**Comment by LightArrowsEXE** [comment]
`blend-subtitles=yes` does appear to fix it.
![mpv-shot0026](https://github.com/mpv-player/mpv/assets/42927908/f86bc9fd-5e7a-428e-a84f-93a4d16fefc4)

Video: https://0x0.st/HO25.mkv
Subtitles: https://0x0.st/HO2R.ass

**Comment by kasper93** [comment]
> Nevermind, I forgot to save post-undoing the shift.

Could you explain what is expected behavior for you? As far as I see it works as expected.

Video is 720x480, after cropping 711x480. The rectangle you want to cover after cropping has roughly this coordinates
```
m 154 162 l 289 162 289 324 154 324
```
Works as expected, when playback in mpv.

Are you expecting for subtitles to be rendered according to uncropped video? why?

> Screenshot from Aegisub (latest arch1t3ct version) with subtitle dimensions: 711x480 (the active area of this anamorphic video)):

Yes, but does Aegisub crop to the active area, or you just squished the video to 711x480 which is obviously wrong.

**Comment by llyyr** [comment]
This "bug" doesn't exist on libass 0.16.0 where explicit vector drawing coordinates aren't scaled in the x-axis. See: https://github.com/libass/libass/commit/f08f8ea522d20dd9985544c636e45e4984a0d743

**Comment by LightArrowsEXE** [comment]
> This is also fixed by setting PlayResX to the size before crop is inserted, in this case 720. You can either do this with --sub-ass-force-style=PlayResX=720 or directly in the .ass file.

Can confirm, this fixes the issue both with and without container cropping applied, with the only caveat being that the shape has been slightly stretched, but that's easily avoidable by typesetting with the original video dimensions from the start.

> Unfortunately, I don't know of a way to make the same ass file render the same way across multiple libass versions, this is something you'll have to report to them

Will do. Thanks for the responses 👍

**Comment by kasper93** [comment]
> Can confirm, this fixes the issue both with and without container cropping applied, with the only caveat being that the shape has been slightly stretched, but that's easily avoidable by typesetting with the original video dimensions from the start.

Does `PlayResX=711` work too? I think this is more correct value for such cases.

**Comment by LightArrowsEXE** [comment]
> Does `PlayResX=711` work too? I think this is more correct value for such cases.

Can't test right now, but...

> Are you expecting for subtitles to be rendered according to uncropped video? why?

Sorry, I missed this comment. This was simply me overthinking how to deal with typesetting irt the active area on anamorphic encodes. It works fine if you simply set the ASS resolution to the uncropped/stretched clip (so in this case, 720x480) and typeset as normal. The issue arises when you set it to 711x480 (or whatever the active area may be), in which case it improperly stretches (though it still displays fine in Aegisub, curiously).

> Yes, but does Aegisub crop to the active area, or you just squished the video to 711x480 which is obviously wrong.

Aegisub stretches the video in the window, but it does not respect container cropping. I also talked about this issue with the maintainer of the fork I mentioned in PMs, and there are currently no plans to implement this (which is honestly probably the safer option either way). The resampling gets ignored when you right-click -> save screenshot, hence the first screenshot being squished.

**Comment by kasper93** [comment]
I don't know much about typesetting, but let me know if the cropping becomes a problem at any point. We have to keep compatibility with old files and new files. But it is more on the subtitle side as well we follow the container crop, which is more correct thing to do than before.
