### ISSUE TITLE
Does MPV support DolbyVison profile 7.05 single layer and duel layer playback? as well FEL?

### ISSUE THREAD

**Issue by aaaatheone** [mpv-player/mpv#12425]
I don't know if anybody asked that question before as I searched in google and as well as mpv's guithub but could not find the answer.
The question is does MPV really support DolbyVison profile 7.05 single layer and duel layer video playback? 
because I already have some Dolby samples with profile 7 and new version dolby profile like one is hdr10 4k resolution with 1080p hdr10 hidden FEL extended layer ,both are mt2s files, none of them triggering DolbyVision! From my general point of view, when I toggling dolbyvison on/off, no changes appearing from video, seems like it playing as hdr10 base layer.

I have some sample files, only MEL profile version 8.06 BL+PRU and MEL profile version 5.06 BL+PRU are working but rest of other profile, looks like flat decoding from back support hdr10 only or am i wrong?

**Comment by kasper93** [comment]
EL is not supported. You need `vo=gpu-next` for most out of DV. Mostly only reshaping and brightness information is extracted.

If you have specific question, you can post a sample file and we will tell you what is used from it. Also in recent mpv (git) version you can look at stats screen to see what metadata is available in the video file.

**Comment by aaaatheone** [comment]
@kasper93 
@Andarwinux

Ok here is the screenshot has been taken from movie cut seen(total recall 1990) left hand side is dolbyvision OFF(,HDR10 base layer) and right hand side dolbyvision ON. I don't know which data is taking from file when dolbyvision toggling on and making those movie seens completely different from hdr10 output and its only working with sample file with dolbyvison profile 8 BL+PRU with MEL included on it(SL-P8-MEL)(I am not sure by the way).
Same movie sample files with Dolbyvision profile 7 BL+EL+PRU with FEL included (ST-P7-FEL) is not showing any differences and paying like flat hdr10, it does not matter dolbyvison ON or OFF 

![Dolby and hdr10 MEL test](https://github.com/mpv-player/mpv/assets/145401543/3265e82c-04fb-48ce-9d99-75e544bb8fbe)

and here are those two samples
Dolby profile 8 BL+PRU MEL enhancement layer
`https://drive.google.com/file/d/1JqZQfpH1N_Gp4-dt8Ry7hFG7SUetDo2o/view?usp=sharing`
Dolby profile 7 BL+EL+PRU FEL enhancement layer(maybe MEL back enhancement layer included not sure)
`https://drive.google.com/file/d/1SsBAsqv1fbx6i0mu-dzVUPCjy4tbfIxx/view?usp=sharing`

> 
> Also in recent mpv (git) version you can look at stats screen to see what metadata is available in the video file.

can you show the like where I can download it or do you windows compile of this tool? is this a extension plugin ?

**Comment by aaaatheone** [comment]
Now I downloaded that mpv-dev-x86_64-v3-20230917-git-181eddc.7z but not sure where to put those libmpv-2.dll,libmpv.dll.a and Inlude folder? or do I need to install whole MPV player from this version?

**Comment by Hrxn** [comment]
you don't need the `*-dev-*` variant to just use mpv

**Comment by aaaatheone** [comment]
@Hrxn
@Andarwinux
@kasper93 

Ok after replacing with mpv.exe, the only deference I can see HDR10: and PQ(Y) in mpv's status bar! but how can I see what metadata is available in the video file?

![Untitled](https://github.com/mpv-player/mpv/assets/145401543/bdc7e18e-a213-4514-8e48-3ff5cb91eafc)

**Comment by aaaatheone** [comment]
> 
> If you want to see the metadata recorded in the video file, just turn off the peak detection.
> 
> `hdr-compute-peak=no`
 
It is already hdr-compute-peak=no here in mpv.conf file

**Comment by aaaatheone** [comment]
@Andarwinux

> Then PQ(Y) is what you are looking for.

Thanks for pointed out, I am really noob about it!
So that PQ(Y) indicating , either PRU or MEL or PRU and MEL both reding from file or something other?

**Comment by kasper93** [comment]
>  So that PQ(Y) indicating , either PRU or MEL or PRU and MEL both are reading from file or something other?

RPU values are used. EL is not decoded at all in current version.

**Comment by aaaatheone** [comment]
@kasper93

> RPU values are used. EL is not decoded at all in current version.

Thanks for clear it out, I hope in near future MPV witll support MEL and FEL as well.

**Comment by Myaanee** [comment]
@haasn you're the HDR king, is this something that can be added in the future or is this too hard?

**Comment by quietvoid** [comment]
> Dolby profile 8 BL+PRU MEL enhancement layer
https://drive.google.com/file/d/1JqZQfpH1N_Gp4-dt8Ry7hFG7SUetDo2o/view?usp=sharing

Old broken file, profile 8 shouldn't carry mapping metadata.

> Dolby profile 7 BL+EL+PRU FEL enhancement layer(maybe MEL back enhancement layer included not sure)
https://drive.google.com/file/d/1SsBAsqv1fbx6i0mu-dzVUPCjy4tbfIxx/view?usp=sharing

Broken file, only the first frame has EL.

**Comment by aaaatheone** [comment]
@quietvoid 

>Old broken file, profile 8 shouldn't carry mapping metadata.
It's causing the flashes.

> Broken file, only the first frame has EL.

How do you getting those information? which tool or tools can show us all the info from dolbyvision content? where I should check and find the correct content

**Comment by quietvoid** [comment]
> How do you getting those information? 

By looking at the files 🤷

**Comment by aaaatheone** [comment]
@quietvoid
@Andarwinux 

> > Dolby profile 8 BL+PRU MEL enhancement layer
> > https://drive.google.com/file/d/1JqZQfpH1N_Gp4-dt8Ry7hFG7SUetDo2o/view?usp=sharing
> 
> Old broken file, profile 8 shouldn't carry mapping metadata. It's causing the flashes.
> 
> > Dolby profile 7 BL+EL+PRU FEL enhancement layer(maybe MEL back enhancement layer included not sure)
> > https://drive.google.com/file/d/1SsBAsqv1fbx6i0mu-dzVUPCjy4tbfIxx/view?usp=sharing
> 
> Broken file, only the first frame has EL.


>mediainfo

**By mediainfo I can only see some text information about those contents but can't getting like what quietvoid mentioned above!** maybe I don't know how to check those by mediainfo!.

```
Video
ID                                       : 1
ID in the original source medium         : 4113 (0x1011)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.07.06, BL+EL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 39 s 542 ms
Bit rate                                 : 23.4 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.118
Stream size                              : 110 MiB (100%)
Language                                 : English
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Original source medium                   : Blu-ray


```

```
Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, Blu-ray compatible / SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 39 s 542 ms
Bit rate                                 : 23.5 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 24.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.118
Stream size                              : 111 MiB (100%)
Language                                 : English
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
```
