### ISSUE TITLE
OSD does not work correctly in pseudo-gui mode for audio files with dmabuf-wayland

### ISSUE THREAD

**Issue by Drommer** [mpv-player/mpv#12429]
Following Information:
- mpv 0.36.0_310_ged5c744aa9
- Arch Linux
- AUR (mpv-git package)
- KDE Kwin 5.27.8
- nVidia Optimus (Intel HD 4600 + nVidia GeForce GT 740M with proprietary driver 470.199.2)

The problem occurs when you play audio files of any format if there is no cover art in the file folder or if the cover art is not embedded in the audio file tag. When you open a file, a completely black player window appears with no time slice and no rewind bar. Pressing the Delete hotkey has no effect. 
[log.txt](https://github.com/mpv-player/mpv/files/12666417/log.txt)

**Comment by Dudemanguy** [comment]
That's because the OSD drawing is currently dependent on there actually being frames. Not sure how easy/hard this will be to fix. Will take a look later.

**Comment by Drommer** [comment]
Off topic, but I also noticed that with ``--hwdec=vaapi`` and ``--vf=vavpp:deint`` I see a green screen instead of video. When I disable deinterlacing (hotkey without restart), the image appears. Do I need to create a separate issue or is this a known issue?
