### ISSUE TITLE
Frames dropped when stats page open and FPS=refresh rate

### ISSUE THREAD

**Issue by guyman624** [mpv-player/mpv#12426]
### Important Information

Provide following Information:
mpv v0.36.0-315-g7a76cf4d
Windows 11 22H2
github/updater.bat

### Reproduction steps
specs
i7-12700k
32GB 3600mhz DDR4
RTX 3090

tested on some other machines as well and can reproduce

Set display refresh rate to the FPS of any video. 

Play video with I menu open, count dropped frames.
Play video, open I menu at end or check logs for dropped frames.

### Expected behavior
Video to drop no frames with stats open

### Actual behavior
Video drops frames with stats open

 ```mpv --log-file=log.txt --no-config```

stats closed [log.txt](https://github.com/mpv-player/mpv/files/12656046/log.txt)
stats open [log.txt](https://github.com/mpv-player/mpv/files/12656057/log.txt)

### Sample files
can provide if necessary but any video should work

**Comment by mitzsch** [comment]
Probably related to this commit => https://github.com/mpv-player/mpv/commit/296d40dc6f38401085d005bb4627f8afff46b041
There was an issue opened here, where this was also discussed. I need to find it again.

**Comment by Dudemanguy** [comment]
That commit should have zero change in behavior from before unless you're pausing/unpausing.

**Comment by Dudemanguy** [comment]
Guess I was wrong. There can be an additional redraw request. Does this make any difference?
```
diff --git a/video/out/vo.c b/video/out/vo.c
index faa172f2fd..26dfc8ded6 100644
--- a/video/out/vo.c
+++ b/video/out/vo.c
@@ -1016,7 +1016,7 @@ static bool render_frame(struct vo *vo)
         // no redraw request, then something can change this (i.e. the OSD)
         // while the vo was unlocked. Don't touch in->request_redraw
         // in that case.
-        if (request_redraw)
+        if (request_redraw || !in->paused)
             in->request_redraw = false;
     }
 
```

**Comment by mitzsch** [comment]
I will rebuild mpv and provide a build here.

**Comment by mitzsch** [comment]
https://we.tl/t-5NHrCysA3T 

Please test this build. (I´m currently not at home and cannot test it)

**Comment by guyman624** [comment]
> https://we.tl/t-5NHrCysA3T

This seems to work, tested on 2 machines. Thank you!

**Comment by mitzsch** [comment]
I know I'm a bit late, but also just wanted to post, that it's also fixed on my side! :) Thanks!
