### ISSUE TITLE
Hide Volume OSD

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12430]
I'm [trying](https://mpv.io/manual/master/#osd) to hide to OSD for when I change volume, but I don't see anything related to it.

**Comment by kasper93** [comment]
In your `input.conf` you can prefix command with `no-osd`

**Comment by kasper93** [comment]
No, I mean in your `input.conf`, you can do `no-osd`

```
WHEEL_UP   no-osd add volume  5
```

**Comment by kasper93** [comment]
Then you do 
```
WHEEL_UP   osd-bar add volume  5
```
