### ISSUE TITLE
Use yt-dlp to `mark-watched` on YouTube

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12448]
I'm trying to use `yt-dlp` `--mark-watched` option:
```
--mark-watched                  Mark videos watched (even with --simulate)
```
`mpv.conf`:
```
ytdl-raw-options=mark-watched=
ytdl-raw-options=cookies-from-browser=firefox
```

Doesn't seem to work for me.

Using:
https://github.com/yt-dlp/yt-dlp-nightly-builds/releases ([yt-dlp nightly 2023.09.19.195302](https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2023.09.19.195302))
https://github.com/shinchiro/mpv-winbuild-cmake/releases ([20230919](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20230919))

**Comment by zhongfly** [comment]
```
ytdl-raw-options=a
ytdl-raw-options=b
ytdl-raw-options=c
```
just equal to `ytdl-raw-options=c`
The next line overwrites the previous line

Please read manual: https://mpv.io/manual/master/#options-ytdl-raw-options
Please read the example

**Comment by zhongfly** [comment]
> Ok, I understand (even though the example doesn't mention it), But even if I use
> 
> ```
> ytdl-raw-options=mark-watched=,cookies-from-browser=firefox
> ```
> 
> It doesn't work.

You should read mpv's log or ytdl's log to konw what happened.

**Comment by christoph-heinrich** [comment]
You can try running `yt-dlp` manually with the same parameters as the does ytdl_hook and look at it's output.
Maybe use `--simulate` instead of `-J` and also leave out the `--no-warnings`. Hopefully that will tell you why it's not working.
