### ISSUE TITLE
got some problems when using a edl file

### ISSUE THREAD

**Issue by Asukaaaaaa** [mpv-player/mpv#12449]
I put a http link to a edl file, but when open the file with mpv, it shows this error.

> [ffmpeg] https: HTTP error 403 Forbidden
> [stream] Failed to open https://xxxxxxxxxx

Adding a `--http-header-fileds="referer:https://www.bilibili.com/"` will solve the 403 error for directly opening the http link.
> mpv.com --http-header-fields="referer:https://www.bilibili.com/" https://xxxxxxxxxx  #This works fine😊

But that `--http-header-fileds` option doesn't work for opening a edl file.
> mpv.com --http-header-fields="referer:https://www.bilibili.com/" foo.edl  #This gets a 403 error🙃

Here is my edl file content. The url has a expire time (hours or days), so it may not be able to open successfully.
`# mpv EDL v0`
`%675%https://xy117x157x138x18xy.mcdn.bilivideo.cn:4483/upgcxcode/19/21/183362119/183362119_da8x4-1-30066.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1695282691&gen=playurlv2&os=mcdn&oi=1973113321&trid=000032170fea7c1f4a76b881409a71df3227p&mid=32438483&platform=pc&upsig=849a429ad2f2267de9b3d4609ab17533&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&mcdnid=14002031&bvc=vod&nettype=0&orderid=0,3&buvid=04D6F2FD-0762-450D-8D94-E8A6D9CE054F36754infoc&build=0&f=p_0_0&agrr=0&bw=15247&logo=A0002000`

The reason I want to do this is that the website bilibili.com divides some of its media into 2 files, a video file and a audio file. It seems that using a edl file can easily link the separated files and make multiple media sources into a playlist. So i'm trying to make a test but stucked by the 403 error.

I know there is a Per-File Option can do the same thing like this way: `mpv.com --\{ video1 --audio-file=audio1 --\} --\{ video2 --audio-file=audio2 --\} ......`
But putting all sources into a edl file is a more convenient and better way for me.😅

So does anyone know is it possible to use edl file to make a playlist and how to solve the 403 error? I will be very appreciated for any help.🫡

**Comment by llyyr** [comment]
Why can't you just do `mpv https://www.bilibili.com/video/XXXXXXXXXXXX/` instead and just let yt-dlp handle this? It seems to work for me just fine, and it'll even take care of the issue of direct EDL urls being ephemeral.

**Comment by Asukaaaaaa** [comment]
> Why can't you just do `mpv https://www.bilibili.com/video/XXXXXXXXXXXX/` instead and just let yt-dlp handle this? It seems to work for me just fine, and it'll even take care of the issue of direct EDL urls being ephemeral.

I am trying to write a plugin for a chrome extension named Bilibili-Evolved, and that ext provides me the direct link of each video. For a bangumi, i can get the links of all episodes in one time, so i'm thinking if i can make those links into a playlist and use mpv to play it directly. yt-dlp works badly for bilibili bangumi when i used it months ago,  i may try it later.
