### ISSUE TITLE
regression in seeking streams with no PTS with --no-correct-pts 

### ISSUE THREAD

**Issue by myspaghetti** [mpv-player/mpv#12454]
### Important Information

Provide following Information:
- mpv version: starting with v0.36.0-240-g67368ac5 until latest
- Windows Version: build 22621
- Source of the mpv binary: scoop or sourceforge.net/projects/mpv-player-windows
- If known which version of mpv introduced the problem: v0.36.0-240-g67368ac5 or a few commits earlier. Binary released immediately before v0.36.0-174-g83c0e980, works correctly

### Reproduction steps

Load a live h264 stream with no PTS, such as that generated by an IP camera. Use `--no-correct-pts ` to enable frame-based seeking through the demuxer cache.

### Expected behavior
Seeking works through the demuxer cache.

### Actual behavior
Seeking either doesn't work at all or stops working after seeking backward and forward a few times through the cache.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12686742/output.txt)

**Comment by Dudemanguy** [comment]
It's not really obvious how that could have happened just looking at the range of commits there. I guess maybe e6afc53e7cabf7d36aab4a8b25a6e2688e4449c8? That's the only one that looks vaguely related.

**Comment by llyyr** [comment]
Considering there are no rtsp related ffmpeg commits, it's probably that commit. Can you confirm that reverting it fixes it?

**Comment by llyyr** [comment]
```
[  13.490][v][lavf] queuing seek to 11.986667
[  13.490][v][lavf] cached range 0: 0.020000 <-> 11.950000 (bof=1, eof=0)
[  13.490][v][lavf] discarding unseekable range due to stream 0
[  13.495][v][lavf] execute seek (to 11.986667 flags 0)
[  13.536][v][lavf] seek done
```
Looking at the log file, seeking seems to have worked just fine when seeking within cached region, however the video freezes just as described in #7472 after seeking ahead of cached region even once. Probably because my commit broke the logic that prevented seeking outside of cached region.

**Comment by myspaghetti** [comment]
Issue appears to be resolved in PR, thank you!

(PR build playback is more jerky, frames are unnecessarily skipped when skipping or fast-forwarding, fps appears to be limited to stream fps instead of display fps, but this appears to be a different issue.)

Thank you so much! You addressed this issue remarkably quickly!
