### ISSUE TITLE
Unsupported hwdec: vulkan

### ISSUE THREAD

**Issue by Alleop5** [mpv-player/mpv#12450]
- mpv version - 0.36.0
- Platform and Version - Void Linux - Latest 
- Source of the mpv binary - Void Repos

- CPU: 11th Gen Intel i5-1135G7
- GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]

### Expected behavior

It works with vulkan without errors/warnings

### Actual behavior

MESA-INTEL: warning: ../src/intel//vulkan/anv_formats.c:760: FINISHME: support more multi-planar formats with DRM modifiers
Unsupported hwdec: vulkan
AO: [pipewire] 44100Hz stereo 2ch floatp
VO: [gpu-next] 1920x1080 yuv420p

### Log file

(https://0x0.st/HOlz.txt)

Is the issue really related to the MESA-INTEL warning?

**Comment by llyyr** [comment]
Read the opening post of #11739. Currently you need ffmpeg build from git, and set the right env variables.

**Comment by Alleop5** [comment]
The issue was that I didn't have the vulkan SDK installed. Now it works.

I thought. It gives 0 errors/warnings but doesn't show any real signs of vulkan being used. And the CPU usage is the same as if I didn't use hardware acceleration. Also it just shows "VO: [gpu-next] 1280x720 yuv420p"  so it definitely isn't using hardware acceleration.

Should probably create a new issue. But not sure because of [comment](https://github.com/mpv-player/mpv/issues/11739#issuecomment-1574881230) because that says that 11th Gen probably isn't supported if I'm reading that right.

Yes I did compile libplacebo, ffmpeg and mpv with vulkan support. And yes it still gives the mesa-intel warning even if I don't use hwdec. IDK I'm just too stupid for this. I'll probably open a new issue in a week if I haven't figured it out by then.
