### ISSUE TITLE
User Scripts: Create `.conf` for every script

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12463]
I am aware there is the option to create a `.conf` file for some scripts,
For example: [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua)
By creating `autoload.conf` in `script-opts` folder, and adding `directory_mode=recursive`, it will apply this settings to the script, this is useful when updating the script (the `autoload.lua`) and don't have to change each setting manually after each update.

But, I am trying to do the same for other scripts,
For example: [oled-screensaver.lua](https://github.com/Akemi/mpv-oled-screensaver/blob/master/oled-screensaver.lua)
By creating `oled-screensaver.conf` in `script-opts` folder, and adding `startAfter=1`, it will not apply this settings.
(For clarification: this example should dim the screen after 1sec, rather than the default which is 10sec `startAfter=10`)

I would like to create `.conf` for each script I use in order to avoid the problem of manually changing each setting after each update.
Is it something the developer of each script has to implement or am I doing something wrong?

**Comment by llyyr** [comment]
>oled-screensaver.conf

oled_screensaver.conf

**Comment by llyyr** [comment]
`skip_once=yes`
