### ISSUE TITLE
libultrahdr inclusion

### ISSUE THREAD

**Issue by Zemax27** [mpv-player/mpv#12467]
Google has just released the ultrahdr library to allow support for the new jpeg hdr format. 

https://github.com/google/libultrahdr

The format is similar to apple heic images and will be supported by all android 14 phones. 
I think it would be a great feature for mpv being able to decode and display that format on hdr compatible monitors.

**Comment by guidocella** [comment]
It is ffmpeg that implements codecs.

**Comment by cmahnke** [comment]
See https://trac.ffmpeg.org/ticket/10974
