### ISSUE TITLE
How to include `autoload.lua` in `--no-config`?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12460]
If I hold the key 
```
RIGHT seek  5
```
While not letting go of the key, I expect mpv to start playing the next video file when it reaches the end of the current one, 
but mpv doesn't start playing the next file, instead it waits for me to let go of the key and only then it will start playing the next video file.

I was going to open an issue (with template) about it, but when I use `--no-config` it will not use `autoload.lua` so I have no idea how to do it...

**Comment by christoph-heinrich** [comment]
`--script=<path to autoload.lua>` should work

**Comment by kasper93** [comment]
I think for `--no-config` `~~` is expanded to current directory.

**Comment by kasper93** [comment]
Do you maybe want to use `portable_config` instead? See docs.

**Comment by guidocella** [comment]
`--input-conf=<filename>`

**Comment by christoph-heinrich** [comment]
I suspect what's going on here is that you have `hr-seek=yes` in your mpv.conf.
When using `--no-config` your 1s seek will do a seek based on keyframes, and the last keyframe is before the end of the video, so it will always seek there while you hold the key down. Without reaching the end of the video it also doesn't go to the next one.
