### ISSUE TITLE
regression: choppy fast-forward playback from cache on files with malformed PTS

### ISSUE THREAD

**Issue by myspaghetti** [mpv-player/mpv#12465]
### Important Information
Follow-up on #12454 and PR #12457 

Provide following Information:
- mpv version: build 35c0c3a from PR 12457
- Windows Version: build 22621
- Source of the mpv binary: sourceforge.net/projects/mpv-player-windows g181edd , PR 12457 
- If known which version of mpv introduced the problem: fast-forward playback from cache is good on v0.36.0-303-g181eddc8 , choppy on build 35c0c3a , so somewhere in between

### Reproduction steps
* Play attached malformed rtsp stream with no PTS (encapsulated as mp4 due to upload restrictions on github). Allow cache seeking with mpv options `--cache=yes --correct-pts=no --fps=30`
* Fast-forward with `--speed=8` or similar until performance becomes an issue with the new version.

Fast-forward playback from cache is choppy on build 35c0c3a from PR 12457

Fast-forward playback from cache is good even on a version with cache seeking issues, like v0.36.0-303-g181eddc8 and earlier. 

### Expected behavior
Smooth playback 

### Actual behavior
Choppy playback

### Log file
[good.txt](https://github.com/mpv-player/mpv/files/12700723/good.txt)
v0.36.0-303-g181eddc8 and earlier

[bad.txt](https://github.com/mpv-player/mpv/files/12700724/bad.txt)
35c0c3a

I can see from the logs that the new version is doing a couplemore things with shaders and textures.

### Sample files
https://github.com/mpv-player/mpv/assets/31696646/57f786dc-69e0-4924-bf7f-9dccf36d47f7

Issue is much more apparent on motion in a straight line at a fixed anglar velocity such as a car driving along a straight road across the field of view.

**Comment by llyyr** [comment]
The defaults were changed recently, does `--profile=fast` fix this?

**Comment by myspaghetti** [comment]
`--profile=fast` plays the file but displays a black screen until I press the `I`, key to display stats.

I'll wait for the weekly build on sourceforge and try to reproduce the issue on different machines and operating systems to narrow it down.

**Comment by llyyr** [comment]
> `--profile=fast` plays the file but displays a black screen until I press the `I`, key to display stats.

Fixed by https://github.com/mpv-player/mpv/pull/12459

**Comment by myspaghetti** [comment]
Issue is resolved in v0.36.0-401-g140d0185 with `--profile=fast`
