### ISSUE TITLE
When the video playback speed exceeds 4.0, there will be no sound

### ISSUE THREAD

**Issue by Monster-DP** [mpv-player/mpv#12469]
### Important Information

Provide following Information:
- mpv version mpv-x86_64-20230917-git-181eddc.7z
- Windows Version  Windows 11 专业版 23H2 22631.2338
- Source of the mpv binary   https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20230917-git-181eddc.7z/download
- Possible screenshot or video of visual glitches
![image](https://github.com/mpv-player/mpv/assets/47738288/2b98a929-9378-447d-bea3-fc12aca12417)

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
There is a sound
### Actual behavior
No sound

**Comment by llyyr** [comment]
https://mpv.io/manual/master/#audio-filters-max-speed

**Comment by Monster-DP** [comment]
> https://mpv.io/manual/master/#audio-filters-max-speed

我改如何将让 
min-speed=0.001
max-speed = 12.0 
在配置文件中生效呢

**Comment by Monster-DP** [comment]
> https://mpv.io/manual/master/#audio-filters-max-speed

I don't understand how this command is added to the configuration file, can you help me?

# Editor
profile = SRT-Anime
secondary-sub-override = no
osc = no
vo = gpu
gpu-context = d3d11
hwdec = auto
border = no
autofit-larger = 70
loop-playlist = inf
hr-seek-framedrop = no
interpolation = yes
ao = wasapi
volume = 100
audio-file-auto = fuzzy
sub-auto = fuzzy
osd-bar-w = 100
osd-bar-h = 2
osd-bar-align-y = -1
osd-border-size = 1
osd-font-size = 45
idle = no
autofit = 70
autofit-smaller = 70
save-position-on-quit = yes
demuxer-max-bytes = '200MiB'
osd-on-seek = no
slang = 'chs,sc,zh,zho,chi,cht,tc'
icc-profile-auto = no

# Modify the audio limit for video playback speed
af = scaletempo2[=min-speed=0.001:max-speed = 12.0]

**Comment by llyyr** [comment]
`af=scaletempo2=max-speed=2`

keep in mind that this will result in the filter always being inserted, even if your playback speed is 1.0 which might even be a noop in the filter code but I'm not sure off the top of my head.

There's no better way to do this currently, which admittedly kind of sucks

**Comment by Monster-DP** [comment]
> `af=scaletempo2=max-speed=2`
> 
> 请记住，这将导致始终插入过滤器，即使您的播放速度为 1.0，这甚至可能是过滤器代码中的一个 noop，但我不确定我的头顶。
> 
> 目前没有更好的方法来做到这一点，诚然，这有点糟糕
Thank you very much, it's already great, this can solve my problem, love you ❤️❤️, this player can actually use 6.0 speed to play 4K high bit rate video on my junk notebook and synchronize audio and video, which is really great!!! PotPlayer 3.0 speed will be out of sync, hahahahaha❤️❤️👍👍😁😁

**Comment by Monster-DP** [comment]
> `af=scaletempo2=max-speed=2`
> 
> keep in mind that this will result in the filter always being inserted, even if your playback speed is 1.0 which might even be a noop in the filter code but I'm not sure off the top of my head.
> 
> There's no better way to do this currently, which admittedly kind of sucks
> 
> edit: apparently it is a noop, at 1.0 the audio isn't changed.

I have a question, why do I use the playlist-prev and playlist-next commands to go up and down in the playlist, why do they all play from scratch instead of continuing the last play position, how do I set it up?

**Comment by llyyr** [comment]
https://mpv.io/manual/master/#options-save-position-on-quit

**Comment by Monster-DP** [comment]
> https://mpv.io/manual/master/#options-save-position-on-quit

不是这个 是PotPlayer这个
![image](https://github.com/mpv-player/mpv/assets/47738288/399b4b8c-39a4-4e18-941b-7bfdfb855d1a)
可以记忆任意视频播放位置 不管是如何退出的

**Comment by Dudemanguy** [comment]
Fixed by https://github.com/mpv-player/mpv/commit/2033a3c93e24f65067b05da11b57547eef531762.
