### ISSUE TITLE
Input command prefix for OSD alignment?

### ISSUE THREAD

**Issue by Hrxn** [mpv-player/mpv#12475]
As someone who just started to use `osd-align-x=center` and becoming quite fond of it, I noticed one glaring exception:
It does simply not look right with `show-text ${playlist}` in my opinion.

I know that mpv has input command prefixes, but apparently no `osd-*` command prefix to change alignment (like `osd-align-left`, for example) specifically for a chosen command.

I don't know how feasible it'd be to implement something like this, but if it is somewhat feasible, then please consider this as an official feature request and change the label accordingly.

**Comment by Hrxn** [comment]
Yup, found it in the mpv man page, thanks again. Although the link seems outdated. I mean, the redirect is working, but still, could be fixed.

Also, what about enabling ASS sequence escaping again?
i.e. `show-text ${osd-ass-cc/0}{\\an7}${playlist}${osd-ass-cc/1}`

Or does this have some unintended side effects?

**Comment by guidocella** [comment]
That is redundant unless you put something after `${osd-ass-cc/1}`.

**Comment by Hrxn** [comment]
@guidocella What about the OSC output (e.g. the playlist output when using the `pl prev` and `pl prev` buttons), this also uses the OSD alignment setting from `mpv.conf`, is it possible to also use something like `${osd-ass-cc/0}{\\an7}${osd-ass-cc/1}` here?

**Comment by guidocella** [comment]
Well it's possible if you modify osc.lua, otherwise you have to change `osd-align-x`.

**Comment by Hrxn** [comment]
What do you mean by changing `osd-align-x`, like in `input.conf`?
 By chaining `KEY set osd-align-x left; do-something; set osd-align-x center` or something like this?

**Comment by guidocella** [comment]
Yes, that should work.

**Comment by Hrxn** [comment]
@guidocella Can I ask you one more question here?

I've taken a closer look here, and considering I would make changes to and run a modified `osc.lua`, would that be the right part?

https://github.com/mpv-player/mpv/blob/907443686242dfb9636ac5b604581f484e5fca7f/player/lua/osc.lua#L903-L921

The output message (that what gets ultimately displayed) is defined in the variable `message` in line 910, correct? (Well, it gets re-used in line 917, but I think this is not really relevant here..)
So, what would be neccessary? Can I just add a `{\\an7}` into the string literal in the `string.format` method?


If this doesn't do the trick and changing this would be more involved, I probably won't even bother.
I barely use the OSC at all, and the only thing I really use it for, is making quick and precise seeks in the seekbar.


Also, regarding the suggestion you made here (`show-text ${osd-ass-cc/0}{\\an7}${osd-ass-cc/1}${playlist}`), because I want to continue to use this principle for my other OSD status output, are there some important limitations I need to be aware of?
Some ASS tags I cannot use, for example? Probably not animation stuff, lol.
But changing color, alpha, border, font size, and even font type change tags are okay for the `text` argument, or not?

(It might be even possible to skip the "closing" tag (`${osd-ass-cc/1}`) in many cases, because unlike filenames in the playlist there is probably no risk of accidental ASS tag interpretation for all regular mpv status output and properties etc.)

**Comment by guidocella** [comment]
> The output message (that what gets ultimately displayed) is defined in the variable `message` in line 910, correct? (Well, it gets re-used in line 917, but I think this is not really relevant here..) So, what would be neccessary? Can I just add a `{\\an7}` into the string literal in the `string.format` method?

This works (because the OSC doesn't escape ASS tags yet, which should be fixed eventually):

```lua
local message = string.format('${osd-ass-cc/0}{\\an7}Playlist [%d/%d]:\n', pos, count)
```

> If this doesn't do the trick and changing this would be more involved, I probably won't even bother. I barely use the OSC at all, and the only thing I really use it for, is making quick and precise seeks in the seekbar.

I don't use it at all lol. Do you know that you can show the playlist with F8 without the OSC?

> Also, regarding the suggestion you made here (`show-text ${osd-ass-cc/0}{\\an7}${osd-ass-cc/1}${playlist}`), because I want to continue to use this principle for my other OSD status output, are there some important limitations I need to be aware of? Some ASS tags I cannot use, for example? Probably not animation stuff, lol. But changing color, alpha, border, font size, and even font type change tags are okay for the `text` argument, or not?

Animations don't seem to work, but you are free to use any tag.

If you want, you can avoid the double \ with single quotes (`show-text '${osd-ass-cc/0}{\an7}${osd-ass-cc/1}${playlist}'`)

> (It might be even possible to skip the "closing" tag (`${osd-ass-cc/1}`) in many cases, because unlike filenames in the playlist there is probably no risk of accidental ASS tag interpretation for all regular mpv status output and properties etc.)

It's pretty unlikely for filenames too because \ is not a valid character for filenames on Windows. It's fine to omit `${osd-ass-cc/1}` for personal usage, even if there is as an ASS tag nothing bad will happen.

**Comment by Hrxn** [comment]
> This works (because the OSC doesn't escape ASS tags yet, which should be fixed eventually):
> 
> ```lua
> local message = string.format('${osd-ass-cc/0}{\\an7}Playlist [%d/%d]:\n', pos, count)
> ```
>

Perfect. If that is all, I'm definitely going to try that and play around a bit.
Just because I've never actually done this before:
Custom OSC gets loaded automatically from the `osc.lua` file in the `scripts` directory (if present), the `osc=no` option in `mpv.conf` is not needed anymore, right?

 
> 
> I don't use it at all lol. Do you know that you can show the playlist with F8 without the OSC?
>

Well, this is my keybind for F8:
```
F8                              show-text "${osd-ass-cc/0}{\\an7}${osd-ass-cc/1}${playlist}"
```

Thanks to your helpful advice earlier in this thread 😄.
So yes, I'm aware.
I just asked about the OSC in the first place for consistency's sake for anyone going down the `osd-align-x=center` route.
 

Also, the quick playlist info display from the OSC is something like `[<pos>/<count>]: <title>`,
which is not the same as the default `playlist` property (more useful, IMHO).


> 
> Animations don't seem to work, but you are free to use any tag.
>

That's very nice. I don't even want animations (and stuff like rotate and shear) 😄.
But definitely gonna change the font size. And use bold, italics, underline, and maybe some different font styles and font colors.

 
> If you want, you can avoid the double \ with single quotes (`show-text '${osd-ass-cc/0}{\an7}${osd-ass-cc/1}${playlist}'`)
> 

Okay, so Lua is a programming language that does this differentiation between double- and single-quoted strings (single quoted meaning string interpolation is turned off, and escape sequences as well, apparently), nice, that's good to know.
But `${playlist}` is the interpolation we want in this case? 🤔 
Or does this work because it is not handled by the Lua engine, basically, instead it is done at a later stage by mpv core??


> 
> It's pretty unlikely for filenames too because \ is not a valid character for filenames on Windows. It's fine to omit `${osd-ass-cc/1}` for personal usage, even if there is as an ASS tag nothing bad will happen.

This is a very good point.
On the other hand, there's no harm in "closing" everything properly with `${osd-ass-cc/1}`, right?
Or does this cost a bit of performance?

**Comment by guidocella** [comment]
> Custom OSC gets loaded automatically from the `osc.lua` file in the `scripts` directory (if present), the `osc=no` option in `mpv.conf` is not needed anymore, right?

You should use `osc=no` so you don't load 2 different copies of `osc.lua`.

> Well, this is my keybind for F8:
>
> ```
> F8                              show-text "${osd-ass-cc/0}{\\an7}${osd-ass-cc/1}${playlist}"
> ```
>
> Thanks to your helpful advice earlier in this thread 😄. So yes, I'm aware. I just asked about the OSC in the first place for consistency's sake for anyone going down the `osd-align-x=center` route.

Whoops, I forgot the details of the older posts.

> Also, the quick playlist info display from the OSC is something like `[<pos>/<count>]: <title>`, which is not the same as the default `playlist` property (more useful, IMHO).

`F8 show-text "${osd-ass-cc/0}{\\alpha&HFF}➜ {\\r}${osd-ass-cc/1}[${playlist-pos-1}/${playlist-count}]\n${playlist}"`

> Okay, so Lua is a programming language that does this differentiation between double- and single-quoted strings (single quoted meaning string interpolation is turned off, and escape sequences as well, apparently), nice, that's good to know. But `${playlist}` is the interpolation we want in this case? 🤔 Or does this work because it is not handled by the Lua engine, basically, instead it is done at a later stage by mpv core??

Single and double quotes are the same in Lua, it's how mpv parses input.conf commands and it's documented at https://mpv.io/manual/master/#flat-command-syntax

> This is a very good point. On the other hand, there's no harm in "closing" everything properly with `${osd-ass-cc/1}`, right? Or does this cost a bit of performance?

There is no difference.

**Comment by Hrxn** [comment]
> 
> You should use `osc=no` so you don't load 2 different copies of `osc.lua`.
>

Well, damn. The `README.md` from the [thumbfast](https://github.com/po5/thumbfast) (which obiously needs a custom `osc.lua` to display the thumbnails) does not mention anything like that, so I simply assumed that this behaviour has changed in mpv.

Apparently not, and mpv does always load `osc.lua` from `~~/scripts` (if present), but still keeps its built-in OSC, right?
Maybe it still "works" because the custom `osc.lua` gets loaded after the integrated one, so the changes would be there, you just waste system resources by loading two OSC effectively, no?
 
> 
> `F8 show-text "${osd-ass-cc/0}{\\alpha&HFF}➜ {\\r}${osd-ass-cc/1}[${playlist-pos-1}/${playlist-count}]\n${playlist}"`
>

Yup, thanks for this nice example. I've actually used something like this before, I knew that this could be done - minus the `osd-ass-cc` control switch and the ASS tags 😄.
 

> 
> Single and double quotes are the same in Lua, [..]
>

GUESS WHAT I DID

![lol](https://github.com/mpv-player/mpv/assets/12064918/fda8e613-a1e4-4448-a144-146f0b499a08)


On a second look, that they considered `learnphp.org` as a good source in this case should have been a pretty good tell 🤣 

> [..] it's how mpv parses input.conf commands and it's documented at 
>
> https://mpv.io/manual/master/#flat-command-syntax

Ah, yeah. There it is:

```
Double quotes interpret JSON/C-style escaping, like \t or \" or \\. JSON escapes according to RFC 8259, minus surrogate pair escapes. This is the only form which allows newlines at the value - as \n.

Single quotes take the content literally, and cannot include the single-quote character at the value.
```

Has nothing to with Lua in this case, it's all implemented on mpv's side.

> There is no difference.

Thanks, good to know.
But I will keep the closing tags and do this oderly, to satisfy my OCD 😄.

**Comment by guidocella** [comment]
> Apparently not, and mpv does always load `osc.lua` from `~~/scripts` (if present), but still keeps its built-in OSC, right? Maybe it still "works" because the custom `osc.lua` gets loaded after the integrated one, so the changes would be there, you just waste system resources by loading two OSC effectively, no?

It really displays both OSCs, you can see that it's darker because there are 2 OSCs overlaid.

> GUESS WHAT I DID
>
> ![lol](https://user-images.githubusercontent.com/12064918/277444072-fda8e613-a1e4-4448-a144-146f0b499a08.png)
>
> On a second look, that they considered `learnphp.org` as a good source in this case should have been a pretty good tell 🤣

lol, it's just describing PHP...Lua doesn't even have $ before variables.

**Comment by po5** [comment]
> Well, damn. The `README.md` from the [thumbfast](https://github.com/po5/thumbfast) script (which obviously needs a custom `osc.lua` to display the thumbnails) does not mention anything like that

Those instructions should go in each custom UI's readme, not thumbfast.

There is a lot of misinformation about running custom OSCs, because almost no one is aware of a feature that's been around for 7 years.  
https://github.com/mpv-player/mpv/commit/fb67db8b72a329fd017409338d6742c773ce85bf made it so that `mp.set_property("osc", "no")` at the top of your custom OSC is enough to unload the original one.  
Note that this only worked reliably in practice if your custom OSC was named something other than osc.lua. This was fixed in https://github.com/mpv-player/mpv/commit/1a720377203f7cee2ab949c5aa2bc9e0a2a7e0f2.

Another layer of confusion, but which doesn't matter at all once you're aware of the trick above, is that if you do allow both OSCs to run and your custom OSC is a fork of the official one, you will randomly have the UI disappear. This is explained in greater detail here: https://github.com/po5/thumbfast/issues/80#issuecomment-1527643412

The vanilla OSC fork provided with thumbfast accounts for these issues, that's why there's no need to mention adding `osc=no` in mpv.conf. I guess it doesn't currently account for unreliability with mpv <v0.33.0 since the script is still named osc.lua. Should be renamed.

**Comment by Hrxn** [comment]
Hi @po5, thanks for chiming in 😄

> Those instructions should go in each custom UI's readme, not thumbfast.

Good point. Although the thumfast-ifyed `osc.lua` linked in your repo's README.md probably also counts as a custom UI 😄

In fact, after writing my last comment, I checked the README again, also checked the instructions of uosc, and there is also no mention of anything like `osc=no`, and at this point I was sure that this has to be intentional.

And then I found the `mp.set_property("osc", "no")` at the beginning of your `player/lua/osc.lua`

But thank you again for your comment and actually confirming this.

I wonder if it still might be beneficial of using `osc=no` in your `mpv.conf`, because of mpv's internal order of execution?
Not sure, but I assume that `mpv.conf` gets loaded before anything in `~~/scripts`?

**Comment by po5** [comment]
uosc also disables the osc for you.

The builtin osc.lua does get loaded, if you want to hyper-optimize startup time to an unreasonable degree

**Comment by Hrxn** [comment]
@guidocella 

I've just tested this a bit now
> 
> This works (because the OSC doesn't escape ASS tags yet, which should be fixed eventually):
> 
> ```lua
> local message = string.format('${osd-ass-cc/0}{\\an7}Playlist [%d/%d]:\n', pos, count)
> ```
> 

You don't even need `${osd-ass-cc/0/}` or anything, apparently, just use the ASS tags (with double backslash) as-is, works anywhere in text output in `osc.lua`.

Keeping it like this gets you actually  `$Playlist [...` at the beginning.

For anyone else curios, this part (line 910) is only about the playlist "switcher" from the OSC.

If you want to change the playlist and title info display (clicking on the title/name in the OSC), you need to change this part:

https://github.com/mpv-player/mpv/blob/032b7de97f1c8c28358a96e9ecfac87d6621a4fb/player/lua/osc.lua#L1801

For example, changing alignment and font size `title = string.format('{\\an9\\fs20}[%d/%d] %s', countone(pl_pos - 1),`
