### ISSUE TITLE
De-interlace Algorithms?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12478]
I wanted to test mpv with 480i content to see how it performs,
I've used `deinterlace=yes` but it seems like it's not perfect,
seems like the white text on screen (not subtitles or osd) are "shaking",
so I've been thinking maybe there are other parameters that I can change in mpv that are related to deinterlace,
the content I test is:
```
Scan type                                : MBAFF
Scan type, store method                  : InterleavedFields
Scan order                               : Top Field First
```
(used mediainfo to extract this information)

- Windows 10, NVIDIA GPU, `vo=gpu-next`, `hwdec=no`, latest build by shinchiro

**Comment by philipl** [comment]
With `hwdec=no`, mpv will use the `yadif` deinterlacer from ffmpeg. This is a high quality deinterlacer, but it can shimmer in the way you describe for text. A higher quality alternative is `bwdif` which includes improvements that intend to handle this better.

You can try it with:

```
--vf=bwdif=mode=1
```

to run in the equivalent way that mpv runs `yadif` (frame rate doubling).

When running with `hwdec` on, the deinterlacer is a function of the hw api being used.

**Comment by Doofussy2** [comment]
> For d3d11, you must use d3d11vpp

This pretty much doesn't work. This has been discussed several times.

**Comment by llyyr** [comment]
I don't know what the situation with vulkan hwdec on nvidia is, but it'll automatically insert bwdif on vulan if you enable deinterlace on vulkan
