### ISSUE TITLE
Playing a directory with season subdirectories no longer expand

### ISSUE THREAD

**Issue by kungfubeaner** [mpv-player/mpv#12473]
When starting MPV from the command line such as:

mpv "d:\tv shows\my tv show\"

The play list used to show every episode in the playlist but now the folders are shown instead of the of the actual video files.  Is there an option to get the old functionality back?  I didn't even notice when the behavior changed due to work and lack of time but it was sometime this year.   I haven't updated any user scripts in about 1.5 years so I'm sure it isn't a user script.

 Screenshot here:
 
![screenshot](https://github.com/mpv-player/mpv/assets/11026817/6f41ebaf-5ca0-4019-99dc-f8a8f8145dcf)

**Comment by Dudemanguy** [comment]
That's a feature. We lazy load directories by default now. Use `--directory-mode=recursive` if you want the old behavior back. Note that when you actually reach the Season 2 subdirectory in your playlist, it will simply expand then. It's not like you won't play the files.

**Comment by kungfubeaner** [comment]
Thanks for the help

**Comment by kungfubeaner** [comment]
Wow, that was a fast reply.  Thanks a lot for the help.  Easy fix too.
