### ISSUE TITLE
What is the result of swapping FSRCNNX and Krig shader order?

### ISSUE THREAD

**Issue by CrHasher** [mpv-player/mpv#12483]
Based on your knowledge what is the difference between these settings in mpv?

First:
```
glsl-shader="~~/shaders/KrigBilateral.glsl"
glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
```
Second:
```
glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
glsl-shader="~~/shaders/KrigBilateral.glsl"
```

I'm interested on what LUMA is used to determine CHROMA and what stage exactly.

Thank you!

**Comment by Isaacx123** [comment]
The order of the shaders absolutely matters, specially when using LUMA prescalers like FSRCNNX or RAVU and CHROMA scalers like Krig or Joint.

You want the LUMA prescaler first so the CHROMA scaler can interpolate the information from the scaled LUMA plane, like this:

`mpv --no-config --vo=gpu-next --gpu-api=vulkan --hwdec=no --profile=high-quality --glsl-shader=ravu-lite-ar-r4.hook --glsl-shader=JointBilateral.glsl --autofit=1920x1080 downscale.mkv`

![mpv-shot0001](https://github.com/mpv-player/mpv/assets/75648063/610f097e-eb3d-418d-b7a0-8e97e79b8682)

Otherwise, if you put the CHROMA scaler first it will only get the information from the original LUMA plane (in this case 540p), like this:

mpv --no-config --vo=gpu-next --gpu-api=vulkan --hwdec=no --profile=high-quality --glsl-shader=JointBilateral.glsl --glsl-shader=ravu-lite-ar-r4.hook --autofit=1920x1080 downscale.mkv

![mpv-shot0002](https://github.com/mpv-player/mpv/assets/75648063/f914e5ee-1579-4a17-8b1d-e9a4c857cddd)

That's why you can see ewa_lanczossharp finishing the CHROMA scale to match the LUMA plane.

**Comment by CrHasher** [comment]
> The order of the shaders absolutely matters, specially when using LUMA prescalers like FSRCNNX or RAVU and CHROMA scalers like Krig or Joint.
> 
> You want the LUMA prescaler first so the CHROMA scaler can interpolate the information from the scaled LUMA plane, like this:
> 
> `mpv --no-config --vo=gpu-next --gpu-api=vulkan --hwdec=no --profile=high-quality --glsl-shader=ravu-lite-ar-r4.hook --glsl-shader=JointBilateral.glsl --autofit=1920x1080 downscale.mkv`
> 
> ![mpv-shot0001](https://user-images.githubusercontent.com/75648063/270496335-610f097e-eb3d-418d-b7a0-8e97e79b8682.jpg)
> 

But CHROMA is scaled to what size exactly here? The luma scaler scales LUMA then the CHROMA is scaled to that size? CHROMA plane is already very small why scale it to an upscaled LUMA and give room for more error? The touched LUMA plane sure has better info to accurately scale CHROMA but the scale factor is huge.

My thought process goes like this: Get LUMA do whatever you want with it scale it 2x and downscale, when done then scale chroma to match it using info from final LUMA, this would scale CHROMA less aka. less errors IMO, given how small a CHROMA plane is usually.

> Otherwise, if you put the CHROMA scaler first it will only get the information from the original LUMA plane (in this case 540p), like this:
> 
> mpv --no-config --vo=gpu-next --gpu-api=vulkan --hwdec=no --profile=high-quality --glsl-shader=JointBilateral.glsl --glsl-shader=ravu-lite-ar-r4.hook --autofit=1920x1080 downscale.mkv
> 
> ![mpv-shot0002](https://user-images.githubusercontent.com/75648063/270496702-f914e5ee-1579-4a17-8b1d-e9a4c857cddd.jpg)
> 
> That's why you can see ewa_lanczossharp finishing the CHROMA scale to match the LUMA plane.

Its pretty obvious that this really uses the untouched LUMA info to scale CHROMA, not exactly great or bad, but a "corrected" LUMA would probably be better.

Guess my original question revolves around when CHROMA scaling happens in mpv, before or after LUMA is scaled to final resolution. From the output of mpv my assumption is that scaling to native resolution happens as the final step, but this would also mean with doublers you scale the CHROMA plane to oblivion if you put the CHROMA scaler after the doubler like FSRCNNX.

**Comment by Isaacx123** [comment]
> Guess my original question revolves around when CHROMA scaling happens in mpv, before or after LUMA is scaled to final resolution.

With internal scalers, someone correct me if I am wrong, CHROMA scaling happens before LUMA scaling, it doesn't matter which one you put  first `--scale` or `--cscale`:

`mpv --no-config --vo=gpu-next --gpu-api=vulkan --profile=high-quality -cscale=lanczos --scale=spline36 "[Arid] Kakegurui - NCOP (BDRip 1080p HEVC FLAC) [3AF57FAB].mkv"`

![mpv-shot0002](https://github.com/mpv-player/mpv/assets/75648063/1ef3b7dc-ed15-44c4-a1d2-104e668e2d12)

>but this would also mean with doublers you scale the CHROMA plane to oblivion if you put the CHROMA scaler after the doubler like FSRCNNX

But this is the ideal outcome when using **pre**scalers like FSRCNNX or RAVU, even more so when using CHROMA scalers that interpolate information from the LUMA plane like Krig or Joint.

**Comment by CrHasher** [comment]
> > Guess my original question revolves around when CHROMA scaling happens in mpv, before or after LUMA is scaled to final resolution.
> 
> With internal scalers, someone correct me if I am wrong, CHROMA scaling happens before LUMA scaling, it doesn't matter which one you put first `--scale` or `--cscale`:
> 
> `mpv --no-config --vo=gpu-next --gpu-api=vulkan --profile=high-quality -cscale=lanczos --scale=spline36 "[Arid] Kakegurui - NCOP (BDRip 1080p HEVC FLAC) [3AF57FAB].mkv"`
> 
> ![mpv-shot0002](https://user-images.githubusercontent.com/75648063/270637905-1ef3b7dc-ed15-44c4-a1d2-104e668e2d12.jpg)
> 
> > but this would also mean with doublers you scale the CHROMA plane to oblivion if you put the CHROMA scaler after the doubler like FSRCNNX
> 
> But this is the ideal outcome when using **pre**scalers like FSRCNNX or RAVU, even more so when using CHROMA scalers that interpolate information from the LUMA plane like Krig or Joint.

We are missing something that only an mpv dev could explain (I'm expecting some explanation like this and that has to be done in RGB mode so ...) waiting for somebody who knows more implementation details to jump in with a correct answer here please.

**Comment by haasn** [comment]
I'm not sure what the question is? Everything @CrHasher said seems correct to me

**Comment by haasn** [comment]
> With internal scalers, someone correct me if I am wrong, CHROMA scaling happens before LUMA scaling, it doesn't matter which one you put first `--scale` or `--cscale`:

The LUMA plane is never scaled by mpv. Unless you mean, by a hook, in which case it happens before CHROMA scaling, yes. But that doesn't matter, the order of operations here doesn't affect the relevant question, which has more to do with whether the hook sees the pre-RAVU LUMA texture or the post-RAVU LUMA texture. In this case, the shader order is the deciding factor.

**Comment by haasn** [comment]
> Guess my original question revolves around when CHROMA scaling happens in mpv, before or after LUMA is scaled to final resolution. From the output of mpv my assumption is that scaling to native resolution happens as the final step, but this would also mean with doublers you scale the CHROMA plane to oblivion if you put the CHROMA scaler after the doubler like FSRCNNX.

It seems you are fundamentally misunderstanding the scaling operations that are happening. LUMA is *never* scaled to the final output resolution. In fact, as I said, the luma plane is never scaled (except if by user shaders).

The order of operations is:

1. Apply all LUMA shaders
2. Apply all CHROMA shaders
3. Scale CHROMA to size of LUMA
4. Convert both to RGB
5. Apply main scaler to final output resolution (in RGB colorspace)

**Comment by CrHasher** [comment]
> > Guess my original question revolves around when CHROMA scaling happens in mpv, before or after LUMA is scaled to final resolution. From the output of mpv my assumption is that scaling to native resolution happens as the final step, but this would also mean with doublers you scale the CHROMA plane to oblivion if you put the CHROMA scaler after the doubler like FSRCNNX.
> 
> It seems you are fundamentally misunderstanding the scaling operations that are happening. LUMA is _never_ scaled to the final output resolution. In fact, as I said, the luma plane is never scaled (except if by user shaders).
> 
> The order of operations is:
> 
> 1. Apply all LUMA shaders
> 2. Apply all CHROMA shaders
> 3. Scale CHROMA to size of LUMA
> 4. Convert both to RGB
> 5. Apply main scaler to final output resolution (in RGB colorspace)

@haasn This last answer explains almost all I wanted to know. So all manipulation to LUMA and CHROMA happens first in the order you use the shaders in, then mpv matches CHROMA to LUMA even if that means additional scaling if output of shaders do not output same size LUMA and CHROMA, then scale or dscale with RGB scalers as last step.

Guess the only part that is still not clear is what KrigBilateral does with CHROMA at step 2. when its applied after FSRCNNX that does a 2x on LUMA. From what I see in the shader it checks if CHROMA is smaller then LUMA, which with a x2 shader like FSRCNNX will always be true, the rest of what  does is a mystery to me.

**Comment by Artoriuz** [comment]
On 4:2:0 content you always need to upscale chroma with a 2x scaling factor (doubling it once). 

If you double luma with a prescaler, now you have to upscale chroma with a 4x scaling factor (doubling it twice).

**Comment by CrHasher** [comment]
> On 4:2:0 content you always need to upscale chroma with a 2x scaling factor (doubling it once).
> 
> If you double luma with a prescaler, now you have to upscale chroma with a 4x scaling factor (doubling it twice).

Would be a great idea to test if CHROMA to 4x is actually worse than using original LUMA for CHROMA up-scaling 2x.

**Comment by Isaacx123** [comment]
See the second [example](https://github.com/mpv-player/mpv/issues/12483#issuecomment-1734869748) of my post.
It should be self-explanatory.

**Comment by CrHasher** [comment]
> See the second [example](https://github.com/mpv-player/mpv/issues/12483#issuecomment-1734869748) of my post. It should be self-explanatory.

I don't see it you posted 2 different frames

**Comment by Isaacx123** [comment]
>Otherwise, if you put the CHROMA scaler first it will only get the information from the original LUMA plane (in this case 540p), like this
>That's why you can see ewa_lanczossharp finishing the CHROMA scale to match the LUMA plane.

Krig scores higher than ewa_lanczossharp in quality metrics, does that answer your [question](https://github.com/mpv-player/mpv/issues/12483#issuecomment-1737663272l)?

**Comment by haasn** [comment]
> Guess the only part that is still not clear is what KrigBilateral does with CHROMA at step 2. when its applied after FSRCNNX that does a 2x on LUMA. From what I see in the shader it checks if CHROMA is smaller then LUMA, which with a x2 LUMA shader like FSRCNNX will always be true in above order of shaders, the rest of what Krig does is a mystery to me, I assume it does scaling because a scaling pass on CHROMA is skipped when checking mpv output.
> 
> With:
> 
> ```
> glsl-shader="~~/shaders/KrigBilateral.glsl"
> glsl-shader="~~/shaders/FSRCNNX_x2_8-0-4-1.glsl"
> ```
> 
> It looks like Krig scales CHROMA to original LUMA in step 1 and 2, then FSRCNNX does 2x on LUMA so in step 3. mpv has to match CHROMA to LUMA again before scale and dscale in RGB. So yeah this is the wrong order.

Bingo, this is spot on.

I should point out that the order of operations you see in the stats graph may be misleading. Because when you have a shader with:

```
//!HOOK CHROMA
//!BIND LUMA
```

This is really more like:
```
//!HOOK LUMA
//!SAVE <luma_copy>
... do nothing

//!HOOK CHROMA
//!BIND <luma_copy>
```

The "save" passes are *not* shown in the stats page (they do not actually happen, it just registers the texture - as it was at that point in time - into the per-shader internal texture list). But again, what matters is solely the order shaders are specified in. You can *conceptually* think about it as each shader running independently on all planes, in order. But in terms of the actual dispatch order, libplacebo will run all LUMA hooks first, then all CHROMA hooks.

I hope that made sense. The bottom line is, all shaders get applied in the order you expect them to, based on the order they're defined in.

**Comment by CrHasher** [comment]
Thank you for your time, I now have the info I needed :)
