### ISSUE TITLE
Certain yt-dlp options doesn't work with mpv

### ISSUE THREAD

**Issue by lamyergeier** [mpv-player/mpv#12488]
### Important Information

Provide following Information:
- mpv version: 0.36.0
- Linux Distribution and Version: Fedora 38
- Source of the mpv binary: dnf
- If known which version of mpv introduced the problem
- Window Manager and version: Gnome 44
- GPU driver and version: -
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Following Works: (It downloads the video and subtitles)

```
 yt-dlp --ignore-config --sub-lang='en,en-GB,de' --write-sub --write-auto-sub -- https://www.youtube.com/watch?v=wr6fQ4KpbRM
```

But when used with mpv

```
$ mpv --no-config --fs --ytdl-raw-options=ignore-config=,sub-lang='en,en-GB,de',write-sub=,write-auto-sub= -- https://www.youtube.com/watch?v=wr6fQ4KpbRM
[ytdl_hook] Usage: yt-dlp [OPTIONS] URL [URL...]
[ytdl_hook] 
[ytdl_hook] yt-dlp: error: no such option: --en-GB,de,write-sub 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Exiting... (Errors when loading file)
```

### Log file

Issue with log file creation:

```
$ mpv --log-file=output.txt --no-config --fs --ytdl-raw-options=ignore-config=,sub-lang='en,en-GB,de',write-sub=,write-auto-sub= -- https://www.youtube.com/watch?v=wr6fQ4KpbRM 
Failed to open log file 'output.txt'
[ytdl_hook] Usage: yt-dlp [OPTIONS] URL [URL...]
[ytdl_hook] 
[ytdl_hook] yt-dlp: error: no such option: --en-GB,de,write-sub 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Exiting... (Errors when loading file)
```

**Comment by christoph-heinrich** [comment]
`--ytdl-raw-options=ignore-config=,sub-lang=[en,en-GB,de],write-sub=,write-auto-sub=`

**Comment by Dudemanguy** [comment]
Actually seems like just the wrong options were passed? Feel free to reopen if I'm wrong.
