### ISSUE TITLE
mp.get_property("filename") returns nil?

### ISSUE THREAD

**Issue by mitzsch** [mpv-player/mpv#12481]
### Important Information

Provide following Information:
- mpv version:  mpv v0.36.0-401-g140d0185
- Windows Version: Windows 11 22H2
- Source of the mpv binary: shinchiro

I'm trying to create a lua script that relies on the file name but it's not working. So I rolled back to the simplest design to just print the filename with something like this
```
require "mp.msg"
require "mp.options"

filename = mp.get_property("filename")
print(filename)
```
but it's outputting only nil. What's wrong? mp.observe_property does not work either.

**Comment by llyyr** [comment]
That's because the script is executed before the file is even attempted. See this example (below the hyperlink) https://mpv.io/manual/master/#lua-scripting-utils-to-string(v)

So you can do something like

```lua
function my_fn(event)
    filename = mp.get_property("filename")
    print(filename)
end

mp.register_event("file-loaded", my_fn)
```

**Comment by mitzsch** [comment]
Ah, I see! Adjusted my script and now it works! Many thanks!!!!
