### ISSUE TITLE
Playback speed should affect --image-display-duration

### ISSUE THREAD

**Issue by pcordes** [mpv-player/mpv#12496]
Years ago, `]` and `[` to change video playback speed also affected how quickly MPV would step through playlist entries that were still images.  This broke (or was intentionally changed) several years ago. (Along with right-arrow going to the next jpg with auto-repeat also not working anymore, but that's a separate issue.)

I'm posting this as a feature request rather than bug because I assume the current behaviour is intentional, I just don't like it. :P  (I'm using mpv 0.36 on Arch GNU/Linux.)

### Expected behavior of the wanted feature

`speed=2.0` with `image-display-duration=1` should only pause 0.5 seconds between still images, as if `image-display-duration` was scaled by the `speed` property.

### Alternative behavior of the wanted feature

`[` and `]`, and custom keybinds to set the playback speed, should affect how fast images flip somehow.

I guess as a workaround, I could bind `[` and `]` to also multiply `image-display-duration` as well as `speed` so they just change in lock-step, if that's doable from `input.txt`.  But resetting speed to `1` with backspace would need a way to reset `image-display-duration` to its initial command-line value.  For my own use I might be fine with that, `1` is ok as long as a scale factor can be cranked up to 32x or whatever.

**Comment by guidocella** [comment]
You can already change `image-display-duration` at runtime, there is no reason `speed` should do the same thing.

**Comment by guidocella** [comment]
> Then the default keybinds for [ and ] (and { and }) should do that, including restoring to the original speed with backspace (so other users don't have to script it themselves, among other reasons).

There is no need to make the default keybindings do that because it is not a common use case, you are the first user requesting it.

> I don't want 2 different keybinds for video speed vs. image speed

Keys can be bound to multiple commands separated by `;`.

> I'd rather not have the OSD be messy from showing a change to both speed and image-display-duration. (Or only show the later one.)

Commands can be silenced with the `no-osd` prefix.

> but this now only shows the image duration, not speed. I could do the other order to see the speed instead.

You can set different key bindings for images as shown in the user scripts linked from the wiki to turn mpv into an image viewer.

> But how would I get backspace to restore the original image-display-duration if that was overridden on the command line? Like I wrote in my original feature request, that would be another advantage of using the speed property as a divisor for image-display-duration.

Either just set it to 1 or write a script that saves the original value and provides a keybinding to reset to it.

**Comment by pcordes** [comment]
> You can set different key bindings for images as shown in the user scripts linked from the wiki to turn mpv into an image viewer.

Thanks, that's quite useful; I'd been going to ask about overloading page-up as `add playlist-pos-1  10` for images vs. seek forward by 10 minutes for videos.

It's annoying to have to do a bunch of manual scripting for what I think would be a better default, so I still think the feature-request has merit, but yes most of what I want can be achieved with good-enough results via just binding two `[` / `]`, and `{` / `}`, and backspace.  Fine control isn't needed for images so I won't also change my keybinds for `ctrl+]  multiply speed 1.01`

**Comment by guidocella** [comment]
This is the script by the way:

```lua
local duration = mp.get_property('image-display-duration')

mp.add_key_binding('F1', 'reset-image-display-duration', function ()
    mp.set_property('image-display-duration', duration)
end)
```

Change `F1` to any other key.

**Comment by Dudemanguy** [comment]
I don't think it makes sense to make `speed` work like this.
