### ISSUE TITLE
--vo=dmabuf-wayland rotation is counter-clockwise unlike other VOs

### ISSUE THREAD

**Issue by jbeich** [mpv-player/mpv#12508]
### Important Information

- mpv version: v0.36.0-427-g6b74b55283 (built via ports) + ffmpeg n6.1-dev-2309-g7f685d0f49
- OS version: FreeBSD 15.0-CURRENT amd64 (built on 2023-09-17)
- WM version: sway 1.8.1-194-g8edc48f6d + wlroots 0.16.0-735-g98a745d926
- GPU version: drm-515-kmod-5.15.25_3 (i915) + mesa-23.2.0-branchpoint-4080-g4f96d2f6ba7 (iris, anv) + intel-vaapi-driver 2.3.0-35-gab755cb7

### Reproduction steps

0. Update beyond ed5c744aa9d3
1. `mpv --no-config --video-rotate=90 <file>`
2. `mpv --no-config --hwdec=vaapi --vo=dmabuf-wayland --video-rotate=90 <file>`

### Expected behavior
Rotation is clockwise

### Actual behavior
Rotation is counter-clockwise

**Comment by Dudemanguy** [comment]
Huh, it's a clockwise rotation for me. Sway 1.8.1 here with amdgpu if it matters.

**Comment by jbeich** [comment]
Bisected to https://github.com/swaywm/sway/commit/029b99b48291

**Comment by Dudemanguy** [comment]
Actually looking at the wayland protocol [enums](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_output-enum-transform):

>90
>    1 - 90 degrees counter-clockwise
>270
>    3 - 270 degrees counter-clockwise

So sway was just bugged before and is correct now. We should flip 1 and 3 around in mpv to match the usual behavior.

**Comment by Dudemanguy** [comment]
Mutter 44.5 (maybe 45 fixed this; dunno didn't check) and Kwin 5.27.8 also rotate clockwise instead of counter-clockwise as per the spec. Very funny. I'll flip 1 and 3 in mpv so the direction of the rotation matches what the spec says instead of what actually happens in compositors.
