### ISSUE TITLE
waylandvk: PER→CENT→AGE album coredumps mpv when using waylandvk.

### ISSUE THREAD

**Issue by cold-nagai** [mpv-player/mpv#12512]
### Important Information

Provide following Information:
<details><summary>mpv --version</summary>

```
mpv v0.36.0-432-gf9234d890a Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sep 28 2023 14:09:04
libplacebo version: v6.338.0-6-g2dbac987
FFmpeg version: N-112207-g8eb094adb2
FFmpeg library versions:
   libavutil       58.25.100
   libavcodec      60.27.100
   libavformat     60.13.100
   libswscale      7.3.100
   libavfilter     9.11.100
   libswresample   4.11.100
```
</details>

- Arch Linux 6.5.5-arch1-1
- aur/mpv-git 0.36.0_432_gf9234d890a-1
- extra/hyprland 0.30.0-1
- extra/mesa 1:23.1.8-1
- extra/vulkan-intel 1:23.1.8-1
![sample](https://github.com/mpv-player/mpv/assets/126972909/5d5ec996-5e45-41f7-bc88-900355a5ef9c)

### Reproduction steps
`mpv --no-config '1.06. インマイルームフェス.flac' --vo=gpu-next --gpu-context=waylandvk`

### Log file
https://0x0.st/HV3K.txt

`mpv: ../ta/ta.c:293: void ta_dbg_check_header(struct ta_header *): Assertion `h->canary == CANARY' failed.`

**Comment by Dudemanguy** [comment]
Going to need a full backtrace here.

**Comment by cold-nagai** [comment]
> Going to need a full backtrace here.
gdb with set logging enabled:
https://0x0.st/HV3_.txt

thread apply all backtrace starts at line 364

**Comment by Dudemanguy** [comment]
Guess I should have specified "with debugging symbols" looks like you have libplacebo symbols but not mpv.

**Comment by cold-nagai** [comment]
https://0x0.st/HV3t.txt

**Comment by Dudemanguy** [comment]
There's still no mpv debug symbols there?

**Comment by cold-nagai** [comment]
Turns out i had !debug in my makepkg. Sorry...

https://0x0.st/HV3d.log

**Comment by Dudemanguy** [comment]
Hmm, can't say anything there jumps out at me. I can't reproduce of course. Tried renaming a file to `1.06. インマイルームフェス.flac` and it was fine. Could you upload a sample that has this problem for you? Maybe there's something about the file in particular.

**Comment by cold-nagai** [comment]
Sure. 

https://litter.catbox.moe/22p1ky.flac

**Comment by Dudemanguy** [comment]
Still can't reproduce unfortunately. I used the image in the OP as cover art as well.

**Comment by cold-nagai** [comment]
When running with autoload, mpv picks up external cover. I'll share it as well.

>cplayer:      Video --vid=1 [P] 'cover.png' (png 3000x3000 1.000fps) (external)

https://litter.catbox.moe/vdtl4h.png

**Comment by Dudemanguy** [comment]
Tried that and it still worked for me. I'm not sure what the difference could be here. Drivers? I'm on amd, but you clearly posted an mpv assert so I wouldn't think that would be it.

**Comment by cold-nagai** [comment]
Another one: https://files.catbox.moe/mw6wrn.png

`mpv --no-config --vo=gpu-next --gpu-context=waylandvk 16750721126710.png -v `

`[vo/gpu-next/libplacebo] Rejecting texture format 'rgb8' due to misalignment: Row stride 1984 is not a clean multiple of texel size 3! This is likely an API usage bug.
[vo/gpu-next/libplacebo] Failed picking any compatible texture format for a plane!
[vo/gpu-next] Failed uploading frame!
[vo/gpu-next/libplacebo] Failed mapping frame id 0 with PTS 0.000000
[vo/gpu-next] Failed updating frames!
[vo/gpu-next/wayland] Given DND offer with mime type text/plain;charset=utf-8
[vo/gpu-next/wayland] Received a new DND offer. Releasing the previous offer.
[vo/gpu-next/wayland] Surface entered output BOE 0x06DF (0x32), scale = 1.000000, refresh rate = 60.012000 Hz
[vo/gpu-next/wayland] Obtained preferred scale, 1.000000, from the compositor.
[vo/gpu-next/wayland] Obtained preferred scale, 1.000000, from the compositor.
[vo/gpu-next/wayland] Resizing due to xdg from 646x634 to 1910x1035
[cplayer] first video frame after restart shown
[vo/gpu-next/wayland] Handling resize on the vk side
[cplayer] playback restart complete @ -9223372036854775808.000000, aud
io=eof, video=playing
[cplayer] assuming this is an image
[vo/gpu-next] Window size: 1910x1035 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu-next] Video source: 646x634 (1:1)
[vo/gpu-next] Video display: (0, 0) 646x634 -> (428, 0) 1054x1035
[vo/gpu-next] Video scale: 1.631579/1.632492
[vo/gpu-next] OSD borders: l=428 t=0 r=428 b=0
[vo/gpu-next] Video borders: l=428 t=0 r=428 b=0
[vo/gpu-next] Failed updating frames!
[vo/gpu-next/wayland] Enabling idle inhibitor
[statusline] V: 00:00:00 / 00:00:00 (0%)
[vo/gpu-next] Failed updating frames!
[cplayer] Set property: user-data/osc/margins={"r":0,"b":0,"t":0,"l":0} -> 1
[cplayer] Set property: user-data/osc/margins={"r":0,"b":0,"t":0,"l":0} -> 1
[vo/gpu-next] Failed updating frames!
[statusline] V: 00:00:00 / 00:00:00 (0%)
[cplayer] Set property: user-data/osc/margins={"r":0,"b":0,"t":0,"l":0} -> 1
[vo/gpu-next] Failed updating frames!`

**Comment by Dudemanguy** [comment]
Also worked fine for me. I don't get the libplacebo error messages you get though. https://0x0.st/HW19.log

**Comment by cold-nagai** [comment]
x11vk crashes, outputting bright purple. And x11egl works fine. (all via XWayland)

**Comment by Dudemanguy** [comment]
Possibly a mesa issue? People did report issues with opengl on intel but vulkan worked for them so basically the opposite of you... weird. There is a [kernel bug](https://gitlab.freedesktop.org/drm/intel/-/issues/9118) but I don't know if that's the same thing as what you experience.

**Comment by llyyr** [comment]
> [vo/gpu-next/libplacebo] Rejecting texture format 'rgb8' due to misalignment: Row stride 1984 is not a clean multiple of texel size 3! This is likely an API usage bug. 

This is a known issue with Intel vulkan + libplacebo, it's not reported on the issue tracker but I've reported it to @haasn directly before but never got a reply whether it's a libplacebo issue or not. For whatever reason, libplacebo can't display rgb24 pixel format images on Intel iGPUs. You get a purple screen on gpu-next/plplay, and a blue screen on gpu.

> crashes

I've never seen any crashes related to this, are you sure your original issue and this are related? I highly suspect it's just closing automatically instead of crashing, I don't observe any crashes here.

**Comment by cold-nagai** [comment]
>You get a purple screen on gpu-next/plplay, and a blue screen on gpu.

Exactly.

> I've never seen any crashes related to this, are you sure your original issue and this are related? I highly suspect it's just closing automatically instead of crashing, I don't observe any crashes here.

You're right. 

iGPU… could you please test the original issue i reported on your hardware? 

https://files.catbox.moe/z6y9m1.flac

**Comment by llyyr** [comment]
That file has no embedded cover, and you linked an external cover above that's expired now.

**Comment by cold-nagai** [comment]
Oops.
https://files.catbox.moe/ekcdpl.png

**Comment by llyyr** [comment]
that's a rgb48 file, I can reproduce the coredump on Intel, not on AMD. And also only on gpu-next, not on vo_gpu. And it still displays the image for a second or two before double freeing.

```
$ mpv --vulkan-device=Intel\(R\)\ Graphics\ \(RPL-S\) ekcdpl.png --no-config --vo=gpu-next --image-display-duration=inf --gpu-api=vulkan
 (+) Video --vid=1 (png 3000x3000 1.000fps)
VO: [gpu-next] 3000x3000 rgb48
double free or corruption (fasttop)
```

[trace.log](https://github.com/mpv-player/mpv/files/12800217/trace.log)

**Comment by haasn** [comment]
> The backtrace is entirely in libplacebo [trace.log](https://github.com/mpv-player/mpv/files/12800217/trace.log)

The last frame is inside mpv, in a GPU callback.

**Comment by llyyr** [comment]
Asan output as well: [asan.txt](https://github.com/mpv-player/mpv/files/12803875/asan.txt)

**Comment by kasper93** [comment]
> The last frame is inside mpv, in a GPU callback.

Yes, it is `talloc_free` https://github.com/mpv-player/mpv/blob/7b8a30fc8132203bc93d35ac887682d2044ad5a9/video/out/vo_gpu_next.c#L738-L739

I don't have time now to look at it, but for me it looks like we call it twice after `pl_dispatch_finish` when emulated upload is done with internal dispatch object and again normal dispatch.

**Comment by haasn** [comment]
can you test https://code.videolan.org/videolan/libplacebo/-/merge_requests/607 ?

**Comment by llyyr** [comment]
> can you test https://code.videolan.org/videolan/libplacebo/-/merge_requests/607 ?

That fixes the double free issue.
