### ISSUE TITLE
MPV won't launch/crashed

### ISSUE THREAD

**Issue by vagabondshrimp** [mpv-player/mpv#12519]
### Important Information

Provide following Information:
- mpv version : mpv-x86_64-20230924-git-140d018
- Windows Version : 10
- Source of the mpv binary : Windows builds by shinchiro (releases and git)
- If known which version of mpv introduced the problem : mpv-x86_64-20230924-git-140d018
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. Tried with personal configs, won't launch
2. Re-download and restarted PC
3. Tried with no-config

I can open older version with no problem (for example [mpv-x86_64-20230917-git-181eddc](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20230917-git-181eddc.7z/download) )

### Expected behavior
App works
### Actual behavior
App crashed
### Log file

Cannot provide log files because the app won't launch.

The issue will be closed for ignoring the issue template.

### Sample files
-

**Comment by CounterPillow** [comment]
> Cannot provide log files because the app won't launch.

Yes you can, run mpv.com from the command line with the `--log-file` parameter.

**Comment by vagabondshrimp** [comment]
I did as you said and it didn't show anything. Usually if i type mpv from the command line, it will show the app version etc, but now it's just nothing.

**Comment by zhongfly** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/issues/445

use gcc build   https://github.com/zhongfly/mpv-winbuild/releases/latest

**Comment by vagabondshrimp** [comment]
It works now, thank you!!

> Because of unkown reason, mpv build by clang compiler can't run with some old cpus.
Is it something that can be fixed, or should I expect to use the gcc build from now on?

**Comment by zhongfly** [comment]
> Is it something that can be fixed, or should I expect to use the gcc build from now on? And sorry for the dumb question but, what's the difference between the clang and the gcc build?

Different compiler.There's almost no difference for user.
The clang version may have better performance (but no one has test this yet) and has some extra security checks enabled.

**Comment by Dudemanguy** [comment]
Doesn't seems to be an actual mpv problem but an issue with certain compiler settings on certain CPUs so closing.
