### ISSUE TITLE
`gpu-api=vulkan` in the mpv.conf file breaks the player, it only shows a black screen and no UI.

### ISSUE THREAD

**Issue by Celarye** [mpv-player/mpv#12517]
### Important Information

Provide following Information:
- mpv version
  - mpv-x86_64-20230924-git-140d018
- Windows Version
  - Windows 11 version 22H2 (OS Build 22621.2283)
- Source of the mpv binary
  - Windows builds by shinchiro (releases and git)
- If known which version of mpv introduced the problem
  - /
- Possible screenshot or video of visual glitches
![image](https://github.com/mpv-player/mpv/assets/96624179/eefb84da-6f35-48c1-a52b-f3b52f5aff2f)

### Reproduction steps

1. Use the latest Nvidia drivers
2. Add `gpu-api=vulkan` to your mpv.conf file
*My whole mpv.conf file in case it helps:*
[mpv.conf.txt](https://github.com/mpv-player/mpv/files/12765900/mpv.conf.txt)
3. Try to play a video of any kind

I understand that this issue might be due something on my end but I believe that it is worth making a Github issue for in case someone else has come across the same issue before and knows a fix.

### Expected behavior

The video and UI should show.

### Actual behavior

No video is shown, it just shows a black screen and the UI is gone as well.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12765868/output.txt)

### Sample files

/

**Comment by zhongfly** [comment]
https://github.com/mpv-player/mpv/issues/11739

**Comment by Celarye** [comment]
So I've went trough the linked issue and checked/applied what it told me to do, but without luck.
Here is an updated log file while playing a video:
[output.txt](https://github.com/mpv-player/mpv/files/12767617/output.txt)

**Comment by kasper93** [comment]
Does it also happen with `--hwdec=none`? Could you provide log in this case?

**Comment by Celarye** [comment]
Didn't fix it for me. I also wanna note that I have OBS replay buffer running in the background, not sure if it really matters though, shut it down and it didn't fix the issue. Here is the log file with `--hwdec=none`:
[output.txt](https://github.com/mpv-player/mpv/files/12768632/output.txt)

**Comment by Celarye** [comment]
@Andarwinux I never turned it on in my BIOS (I should probably do that some time), not sure if this is why the log would say that it 'doesn't support' it?

**Comment by kasper93** [comment]
I dunno what to think about those errors. Let's summon @haasn here, maybe he knows.

Seems to fail to allocate few not that big buffers:
```
[   0.411][d][vo/gpu-next/libplacebo] Allocating 258048 memory of type 0x7 (id 4) in heap 2: ../../../../../src_packages/libplacebo/src/gpu/utils.c:1165
[   0.412][e][vo/gpu-next/libplacebo] Allocation of size  252K failed: VK_ERROR_OUT_OF_DEVICE_MEMORY!
```
```
[   0.437][d][vo/gpu-next/libplacebo] Allocating 258048 memory of type 0x7 (id 4) in heap 2: ../../../../../src_packages/libplacebo/src/gpu/utils.c:533
[   0.438][e][vo/gpu-next/libplacebo] Allocation of size  252K failed: VK_ERROR_OUT_OF_DEVICE_MEMORY!
```

Fails to create polar smapler lut:
```
[   0.461][e][vo/gpu-next/libplacebo] No slab to serve request for  1024 bytes (with alignment 0xc00) in pool 3!
[   0.461][e][vo/gpu-next/libplacebo] Failed creating LUT texture!
[   0.461][e][vo/gpu-next/libplacebo] Failed initializing polar LUT!
[   0.462][e][vo/gpu-next/libplacebo] Failed dispatching scaler.. disabling
```

And fails to compile shader: (there is probably missing checks somewhere for previous failures) 
```
[   0.571][e][vo/gpu-next/libplacebo] shaderc output:
[   0.572][e][vo/gpu-next/libplacebo] input:70: error: '' :  syntax error, unexpected LEFT_BRACE, expecting SEMICOLON
[   0.572][e][vo/gpu-next/libplacebo] 
[   0.572][e][vo/gpu-next/libplacebo] shaderc compile status 'error' (1 errors, 0 warnings)
[   0.572][v][vo/gpu-next/libplacebo] Spent 109.418 ms translating SPIR-V (slow!)
[   0.572][e][vo/gpu-next/libplacebo] vk_compile_glsl(gpu, tmp, GLSL_SHADER_COMPUTE, params->glsl_shader, &comp): VK_ERROR_INITIALIZATION_FAILED (../../../../../src_packages/libplacebo/src/vulkan/gpu_pass.c:460)
```

**Comment by haasn** [comment]
Seems like it's trying to use the tiny 256 MB host-visible VRAM to upload textures, instead of RAM. We should probably force host-local memory for texture uploads.

**Comment by haasn** [comment]
Can you test https://code.videolan.org/videolan/libplacebo/-/merge_requests/604 ?

**Comment by Celarye** [comment]
I haven't tried using mpv trough compiling it myself. I'll check it tomorrow.

**Comment by Jules-A** [comment]
> Will this hurt the performance of ReBAR-enabled devices?

Yeah, I'm not a big fan of this, can't it detect how much can be assigned before or check if ReBAR is enabled?

**Comment by haasn** [comment]
> > Seems like it's trying to use the tiny 256 MB host-visible VRAM to upload textures, instead of RAM. We should probably force host-local memory for texture uploads.
> 
> Will this hurt the performance of ReBAR-enabled devices?

Actually I suspect it may _increase_ performance.

**Comment by haasn** [comment]
Hmm, I tested it, the difference is something like 10% in favor of using device memory when available.

So probably we should indeed make this somehow conditional on having sufficient VRAM available. Annoying...

**Comment by haasn** [comment]
```
  dst ram memcpy       : avg 477 μs	2097.904 fps
  dst gpu memcpy       : avg 620 μs	1613.953 fps
```

Seems like using host memory is better in a synthetic throughput test.

**Comment by haasn** [comment]
I think it's hard to really evaluate this because in the end, what's faster depends on too many conflicting factors.

In theory, using GPU VRAM for the transfer is faster as it will make the second memcpy happen entirely in VRAM, which typically has significantly higher bandwidth than system RAM. But OTOH, that will make it now compete with other operations happening in VRAM, whereas using host RAM will compete with e.g. decoding or other system tasks. This synthetic test completely hides that, and probably effectively speeds it up only because now we're hitting both RAM and VRAM rather than being bottlenecked by VRAM copy speed alone.

In the end, I don't really know, but somehow I feel like we want to continue using VRAM unless we have a very small BAR. I think I will go with the more annoying approach of testing this, after all...

**Comment by haasn** [comment]
Side note, the real question here is "Why doesn't host pointer import work?". Normally we should avoid creating upload buffers entirely...

**Comment by Jules-A** [comment]
Hate to be more annoying but would it be possible to be user configurable also or is it possible to get a build of ffmpeg with that change? I think maybe it will it will fix the running out of VRAM (12GB) when using libplacebo from ffmpeg?

**Comment by Celarye** [comment]
> Seems like it's trying to use the tiny 256 MB host-visible VRAM to upload textures, instead of RAM. We should probably force host-local memory for texture uploads.

I'm also quite confused as to why it's limited to only 256MB of VRAM in my case, is this normal for when you have ReBAR disabled?

**Comment by kasper93** [comment]
> I'm also quite confused as to why it's limited to only 256MB of VRAM in my case, is this normal for when you have ReBAR disabled?

Yes, the CPU is limited to access only 256MB chunks of VRAM without rebar.

> In the end, I don't really know, but somehow I feel like we want to continue using VRAM unless we have a very small BAR. I think I will go with the more annoying approach of testing this, after all...

Yep, probably best to utilize VRAM if possible and fallback to other means if BAR is too low. Annoying, but I guess there is lots of annoying feature testing already in libplacebo

**Comment by Celarye** [comment]
I enabled ReBAR and it indeed seems to have fixed my issue.

**Comment by ms178** [comment]
I also see only a black screen since upgrading my mpv-git to a later revision, I am on AMD 6950XT with latest mesa-git. ReBAR is already enabled (with a BIOS mod on my X99 motherboard).

I've only seen the problem with h264 TV streams from my FritzBox with mpv-git so far, older MPEG2 streams still work without issue. I've tried vlc to rule out a mesa/ffmpg issue, vlc doesn't have any problems with the same h264 TV stream.

**Comment by ms178** [comment]
This might have been a Mesa issue, this MR seems to have fixed it for me: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/25511

**Comment by haasn** [comment]
See https://code.videolan.org/videolan/libplacebo/-/merge_requests/646 for hopefully more correct fix

**Comment by candrapersada** [comment]
how to use mpv auto profile if `mesa-intel warning haswell vulkan support is incomplete`
enable `gpu-api=opengl`

**Comment by kasper93** [comment]
> how to use mpv auto profile if `mesa-intel warning haswell vulkan support is incomplete` enable `gpu-api=opengl`

If it causes any real issues, report it, else ignore it.

**Comment by candrapersada** [comment]
Yes but for linux
