### ISSUE TITLE
Change or Enable Subtitles while playing a movie leads to severe frame drops 

### ISSUE THREAD

**Issue by danbezerra** [mpv-player/mpv#12522]
### Important Information

Provide following Information:
- mpv version: 
Only present on the latest Shinchiro build : mpv-x86_64-v3-20230929-git-f9234d8.7z. If rollback to Sept 26th build, all works fine.

- Windows Version: Windows 10 Build 19045
- Source of the mpv binary: Shinchiro build from Sept 29th. 
- If known which version of mpv introduced the problem: Shinchiro build from Sept 29th.
- Possible screenshot or video of visual glitches

### Reproduction steps
1. Make sure you have a build from Sept 29th (Shinchiro build release) or manually compile it yourself.
2. You must stream a video to trigger this bug. Direct play a file won't trigger it. For example, I direct stream a video from my Jellyfin local server using the http://... stream address. The same can be used by Plex I believe. I used a Blu-Ray rip (.MKV file)
3. Once the movie starts to play, try to enable or change subtitles. 

Results: The video starts to skip, halt, freeze once you try to select or change subtitles. Wait a bit doesn't help so it's not a buffer issue. 

No-Config provides the same results - so not an issue with the profile used, HWdec, Shaders, etc.

### Log files
MPV Output log file, with my http address removed: https://0x0.st/HV5n.txt
Screenshot of MPV console: https://0x0.st/HV55.jpg

**Comment by guidocella** [comment]
Already fixed by 3a572c7a88

**Comment by danbezerra** [comment]
yeah, confirmed it's fixed now.
