### ISSUE TITLE
Repeatedly pausing and unpausing causes the audio to cut out

### ISSUE THREAD

**Issue by dokur0chan** [mpv-player/mpv#12520]
### Important Information
```
mpv v0.36.0-453-g84fa7ea4 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sep 30 2023 02:20:52
libplacebo version: v6.338.0-6-g2dbac98-dirty
FFmpeg version: N-112235-g9a3bbf89b
FFmpeg library versions:
   libavutil       58.27.100
   libavcodec      60.27.100
   libavformat     60.13.100
   libswscale      7.4.100
   libavfilter     9.11.100
   libswresample   4.11.100
```

- Windows 11 Version 10.0.22621 Build 22621
- shinchiro Windows binaries
### Reproduction steps

Pause and unpause any video a bunch of times.

### Expected behavior

It works.

### Actual behavior

The audio cuts out completely after a certain point, and there's an A/V desync. Seems to fix itself after making the OSC pop up by moving my mouse, or by seeking.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/12773944/mpv.log)

**Comment by awsms** [comment]
I'm having similar issue since very recent commits on Linux, cache seems to be broken too (everytime i pause/play, all the buffered content is lost).

**Comment by guidocella** [comment]
This only happens with internal subs and is caused by f40bbfec4f

**Comment by awsms** [comment]
> This only happens with internal subs and is caused by [f40bbfe](https://github.com/mpv-player/mpv/commit/f40bbfec4fcd2d9a787a4d98ec7698a646e5607e)

will it be reverted then, or this is here to stay

**Comment by Dudemanguy** [comment]
>the commit reverted

It is now. Not sure if it had anything to do with dokur0chan's issue? I wasn't able to reproduce.

**Comment by dokur0chan** [comment]
I downloaded a git artifact that was made after the commit was reverted, and it seems to have fixed the issue. So unless the issue is build/binary related, that was probably the culprit.
