### ISSUE TITLE
On MacOS cannot use any key inputs while window is being dragged

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#12538]
### Important Information

Provide following Information:
- mpv v0.36.0-465-g0a1e3d8685
- MacOS 12.6.1
- Compiled using meson with latest git

### Reproduction steps
Grab window with the mouse. Hit any key input.

### Expected behavior
Key inputs work

### Actual behavior
Key inputs do not work.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12779504/output.txt)

**Comment by Akemi** [comment]
that doesn't work on Apple's own apps. so i would say the current behaviour is the expected one.

it might not even be possible.
