### ISSUE TITLE
Embedded Subtitles No Longer Autoloading. Have To Press J each Time to Toggle Them On

### ISSUE THREAD

**Issue by kraithus** [mpv-player/mpv#12540]
### Important Information

- mpv version: 0.36.0
- Linux Distribution and Version: Manjaro 23.0.2
- Window Manager: KWin

### Reproduction steps
Download a youtube video with content creator subtitles with options to output file as mp4 and embed subtitles, example video:

yt-dlp --merge-output-format mp4 --embed-subs --embed-metadata "RmTq3cJqyCo"

### Expected behavior
Autoload embedded subtitles. Was working before updating Manjaro on October 1st 2023, prior to this last update was September 5th 2023

### Actual behavior
Does not autoload embedded subtitles

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/12779859/output.txt)

**Comment by guidocella** [comment]
`--subs-with-matching-audio`

**Comment by kraithus** [comment]
> `--subs-with-matching-audio`

This has fixed the issue. But what could have changed when I updated my OS. I just checked and prior to the update I  was on mpv 0.35.1-6. What changed in this new version of mpv?

**Comment by guidocella** [comment]
The default value of `subs-with-matching-audio`. It will change back to `yes` on mpv 0.37.

**Comment by kraithus** [comment]
> The default value of `subs-with-matching-audio`. It will change back to `yes` on mpv 0.37.

Thank you. With that my issue is fully resolved.
