### ISSUE TITLE
playlist-prev skips files after seeking over short videos too quickly.

### ISSUE THREAD

**Issue by Sneakpeakcss** [mpv-player/mpv#12548]
### Important Information

- mpv version - `mpv v0.36.0-455-ge9690727`
- Windows Version - `WIN10 21H2`
- Source of the mpv binary `https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/`
- ~~If known which version of mpv introduced the problem~~
- Possible screenshot or video of visual glitches:

https://github.com/mpv-player/mpv/assets/77424331/7c354b45-56ff-4f09-8e0a-79988241a962

https://github.com/mpv-player/mpv/assets/77424331/2e854012-0dad-4230-b8ca-aab39dae7d55

### Reproduction steps

- Create a playlist containing at least 1 video that's <2min long (sample files included below).
- Hold `up arrow` to seek over the video and keep holding until MPV goes over the short videos.
- Use `playlist-prev` to toggle through, back to the first video.

### Expected behavior
`playlist-prev` should go back through every video in playlist rather than skipping them like they don't exist anymore.

### Actual behavior
The moment you skip over a short video, `playlist-prev` stops detecting videos and loads files out of order, while `playlist-next` still goes properly through all of them, additionally i had scenarios where the player closes out of nowhere while seeking over, but i'm uncertain if this is connected.

### Log file
[mpvLogFile.txt](https://github.com/mpv-player/mpv/files/12788719/mpvLogFile.txt)

### Sample files
[playlist-prev-test-samples.zip](https://github.com/mpv-player/mpv/files/12788674/playlist-prev-test-samples.zip).

**Comment by guidocella** [comment]
Caused by https://github.com/mpv-player/mpv/blob/01c5346d1ada7185710963628012a5c3dcf1ce74/player/loadfile.c#L1903-L1905 and https://github.com/mpv-player/mpv/blob/01c5346d1ada7185710963628012a5c3dcf1ce74/player/loadfile.c#L1954-L1956

I also noticed this gifs shorter than 1 second.

**Comment by guidocella** [comment]
We should just drop `playback_short` and keep only `init_failed`.
