### ISSUE TITLE
vo_dmabuf_wayland: No color correction with HDR content

### ISSUE THREAD

**Issue by rmader** [mpv-player/mpv#12543]
So far `vo_dmabuf_wayland` seems to ignore the HDR metadata, forwarding content to the compositor unconditionally. This is problematic as Wayland compositor right now assume BT709 / sRGB content and there's no way to tell them otherwise. The later will change once the [color management protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/14) lands/gets adopted.

Thus `vo_dmabuf_wayland` should be able to trigger color space conversion from upstream elements, like it already does for pixel formats etc., and use it for any non-BT709 content. Once the color management protocols lands it will be possible to properly negotiate supported HDR modes.

How to test:
 - play BT2020 content, such as [Camp by Sony](https://kodi.wiki/view/Samples)), on a Wayland compositor that supports P010

Expected result
 - colors should look sharp

Observed result:
 - colors look washed out, not as sharp as when using other backends

**Comment by Dudemanguy** [comment]
The amount of colorspace-related code in `vo_dmabuf_wayland` is exactly zero. I'll take a peek later and see what existing things we already have for this.

**Comment by philipl** [comment]
If you are running on Intel hardware, you can use the `tonemap_vaapi` filter to do this. I have a conceptual TODO to hook this up to as an automatic filter if we can detect that it's needed. I don't know if AMD drivers support it - their approach to vaapi is very bare-bones so I'd be surprised if they do.

**Comment by archerallstars** [comment]
I try the `tonemap_vaapi` on Intel iGPU, UHD Graphics 620 (KBL GT2), but the result looks a lot darker than it should've been (I know because I also view the same movie on Prime Video - John Wick 4). Changing the `format` or the `transfer` value as specified on https://ffmpeg.org/ffmpeg-filters.html#tonemap_005fvaapi doesn't help.

And I don't think `tonemap_vaapi` is supported on AMD yet, see: [Mesa issue #3865](https://gitlab.freedesktop.org/mesa/mesa/-/issues/3865).

**Comment by Dudemanguy** [comment]
With #15048, this works now on mutter 47. For any other compositor, they will need to implement `xx-color-management-v4` and the correct format for support to work. e.g. kwin works with this [MR](https://invent.kde.org/plasma/kwin/-/merge_requests/6352).
