### ISSUE TITLE
vo_dmabuf_wayland: Wrong viewport size for background surface on certain resolutions

### ISSUE THREAD

**Issue by rmader** [mpv-player/mpv#12554]
This came up when investigating https://gitlab.gnome.org/GNOME/mutter/-/issues/3024#note_1858689: On certain resolutions, such as 1650x1050, the viewport destination of the black background surface is one pixel to small.

STR:
 - set resolution to `1680`x`1050`
 - play a video in fullscreen mode with `vo_dmabuf_wayland` and `WAYLAND_DEBUG=1`
 - grep for `set_destination`

Observed result: the height of the viewport of the toplevel surface is `1049` instead of `1050`

This is likely a small rounding error.

---

Note: the fact that this is visible on Mutter is a bug in the later - compositors need to ensure that the background is black in fullscreen mode.

**Comment by Dudemanguy** [comment]
Actually it's not dmabuf-wayland specific. All VOs have this rounding error. It's from vo_get_src_dst_rects.
