### ISSUE TITLE
TOOLS/lua/autoload: add option to limit "Adding..." messages

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12551]
I use `autoload.lua` with `directory_mode=recursive`.
I often have many files in other directories.

Current behavior:
Console spams `[autoload] Adding...`

Suggested behavior:
Add the option to limit the number of messages (and display the remaining files added).
Console will only show 5 messages that are related to files added, and if there are more files then include another line that says `[autoload] Added 50 more files`

Reason for suggesting this behavior:
I often use the console for many reasons like to make sure that there are no errors, to see the audio and subtitle tracks mpv selected and etc,
so when I can't see any of that information and it's being replaced by a bunch of `[autoload] Adding...` messages I find it annoying,
but I also don't want to disable `directory_mode=recursive`.

**Comment by Dudemanguy** [comment]
Should it just be changed to `msg.verbose` instead of `msg.info`? This doesn't really seem like useful information to know by default to me.

**Comment by christoph-heinrich** [comment]
> Should it just be changed to `msg.verbose` instead of `msg.info`?

Sounds reasonable.
Maybe some of the already existing verbose messages should be bumped to debug? Otherwise there is no way to see what autoload adds without also getting spammed with `"stopping: not a local path"` or `"stopping: manually made playlist"`

**Comment by christoph-heinrich** [comment]
I can see how `[autoload] Added 50 files` might make sense, but how does limiting it to a few make sense?
I'd either be interested in seeing all the files that were added, or I don't care at all.
