### ISSUE TITLE
Using gpu-hq profile causing frame drops/performance issues 

### ISSUE THREAD

**Issue by xd003** [mpv-player/mpv#12564]
- mpv version - mpv v0.36.0-472-g7b8a30fc
- Windows Version - Windows 11 Pro
- Source of the mpv binary - https://sourceforge.net/projects/mpv-player-windows/files/
- If known which version of mpv introduced the problem - Definitely some commit after mpv 0.36.0 release

As the title indicates using gpu-hq profile is causing frame drops and performance issues for me while running the git version compiled from this commit - https://github.com/mpv-player/mpv/commit/7b8a30fc8132203bc93d35ac887682d2044ad5a9. When i play the very same video using very same setttings on mpv release v0.36.0 , there aren't any frame drop issues whatsoever. Below i am attaching the log file generated with both the mpv versions. If someone can pinpoint any commit after v0.36.0 which might have caused this, i can test with a git version prior to that commit for confirmation

### Log file
[mpv 0.36.0.log](https://github.com/mpv-player/mpv/files/12813416/mpv.0.36.0.log)
[mpv v0.36.0-472-g7b8a30fc.log](https://github.com/mpv-player/mpv/files/12813417/mpv.v0.36.0-472-g7b8a30fc.log)

**Comment by guidocella** [comment]
`gpu-hq` is an alias for the `high-quality` profile since 703f158880 which has more resource-intensive options.

**Comment by kkanungo17** [comment]
The profiles have been updated since 0.36.0 release, the current gpu-hq profile uses much more high quality but more computationally expensive settings, and many of the old gpu-hq settings are now set as default. You just need to add deband=yes to get back essentially the old behaviour back.

**Comment by xd003** [comment]
> The profiles have been updated since 0.36.0 release, the current gpu-hq profile uses much more high quality but more computationally expensive settings, and many of the old gpu-hq settings are now set as default. You just need to add deband=yes to get back essentially the old behaviour back.

Thanks for the information. To be honest, i don't really know much of the technical side like what does deband even do. I just simply used gpu-hq as my system was able to handle it.  Since most of the old gpu-hq settings are not set as default, i guess i will just remove this option from my config altogether
