### ISSUE TITLE
Playback freezes on latest version

### ISSUE THREAD

**Issue by zhengqwe** [mpv-player/mpv#12576]
### Important Information

Provide following Information:
- mpv version
0.36.0
- Windows Version
Windows 10
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20231006/mpv-x86_64-v3-20231006-git-07995f5.7z
- If known which version of mpv introduced the problem
There is no problem with shinchiro' s [20230919](https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230919/mpv-x86_64-v3-20230919-git-7a76cf4.7z) and previous versions, but it appears with [20230922](https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20230922/mpv-x86_64-v3-20230922-git-6eb35f6.7z) and later versions.
- Possible screenshot or video of visual glitches

### Reproduction steps

Play any 4K 60FPS HDR video, the new version severely drops frames. Using `mpv --no-config --vo=gpu-next --hwdec=d3d11va text.mkv`

### Expected behavior
Playback smoothly
### Actual behavior
Playback freezes
### Log file

[20230919](https://github.com/mpv-player/mpv/files/12829594/output.txt)
[20231006](https://github.com/mpv-player/mpv/files/12829602/output.txt)

**Comment by zhongfly** [comment]
try `profile=fast`
Related to 2023.9.20 https://github.com/mpv-player/mpv/commit/703f1588803eaa428e09c0e5547b26c0fff476a7

**Comment by kasper93** [comment]
How many 4k HDR 60fps demos do you watch per day? Default settings will work fine with every real content with your Intel iGPU. 4k HDR 60fps is bit much for this GPU.
