### ISSUE TITLE
NDI Output

### ISSUE THREAD

**Issue by ysnist** [mpv-player/mpv#12578]
I searched the documentation but couldn't find anything about this. I want to stream the source played in MPV Player to the ndi output like in vlc. Its posible ?

**Comment by pinpox** [comment]
@ysnist did you find any solution to this? I'm looking for a way to stream a webcam from a raspberry pi over NDI

**Comment by pinpox** [comment]
@kasper93 was this implemented? If so, are there doc's on it now?

**Comment by kasper93** [comment]
The issue tracker is not for questions or discussions. If you want to request a feature, please create a proper feature request with relevant information to help understand the problem.
