### ISSUE TITLE
OBS Plugin

### ISSUE THREAD

**Issue by ysnist** [mpv-player/mpv#12570]
Are you thinking of making a plugin for OBS for such a great player? This would be a great alternative for everyone. It's really sad that VLC is the only alternative.

**Comment by oplyt** [comment]
Good idea but you've to develop your own😜

**Comment by Dudemanguy** [comment]
I'm not sure what you're asking, but can't you just make a cplugin or something for this? It's not something that will be a core part of the player for sure.

**Comment by oplyt** [comment]
Skill issue

**Comment by kasper93** [comment]
We don't even know what you are expecting from mpv? What are the requirements for "OBS plugin". Also is it a plugin that uses the mpv/libmpv? Do you require some changed in mpv itself to implement that? If we have some description what is missing, we can think about allocating resourced towards resolving this. But throwing buzz words around without explaining what you really want is not going to get anywhere.

**Comment by ysnist** [comment]
I am not a professional developer. I think we should discuss this issue with OBS-Studio developers. We need someone who can develop an OBS-Stuido plugin using the MPV library.
I think it would be a great fit. Depending on VLC only for OBS brings a lot of problems.

**Comment by ysnist** [comment]
Although MPV developers are not aware of it, they do not know how necessary it is for OBS Studio and how thousands of users need mpv. I can assure you that most of the OBS users do not even know about MPV Player.

**Comment by Dudemanguy** [comment]
I'm not sure what needs to be discussed. Feel free to get someone to write your plugin or whatever you want, but it's not going to be here.
