### ISSUE TITLE
Opening a folder keeps subfolders as subfolders

### ISSUE THREAD

**Issue by DarthSpaceLord** [mpv-player/mpv#12585]
As stated by the title, when I open a folder, I expect all files inside the subfolders to be shown in playlistManager. Instead, each subfolder is kept "closed" and must be manually opened to display the internal files. I remember in previous version(s) of mpv, every subfolder's content was displayed by default. I understand that I could move all files into one folder, but I currently have them named, organized, and ordered through the use of these subfolders. Is this a new mpv config option, or is it something to do with playlistManager? I can attach screenshots if necessary, but I figured I would cross that bridge if I need to.

**Comment by guidocella** [comment]
`directory-mode=recursive`

**Comment by DarthSpaceLord** [comment]
Much appreciated, worked instantly. o7
