### ISSUE TITLE
Switching tracks while playing CD doesn't work properly

### ISSUE THREAD

**Issue by Zerogoki00** [mpv-player/mpv#12591]
### Important Information

- mpv version: mpv 0.35.1
- Linux Distribution and Version: Debian 12
- Source of the mpv binary: debian repository
- If known which version of mpv introduced the problem: no
- Window Manager and version: XFCE 4.18

### Reproduction steps

1. Insert audio cd
2. Play it with command `mpv cdda://`
3. Try to switch tracks using `<` and `>` hotkeys
### Expected behavior
MPV is able to switch to next and previous tracks properly

### Actual behavior
MPV says that it switches tracks but it's still playing the same track
`[cdda] Switched to track 2`
(and still playing track 1)

### Log file

[mpv.log](https://0x0.st/HWGV.log)

### Sample files

You will need any Red Book compliant audio CD

**Comment by Dudemanguy** [comment]
Yeah this has been broken for a really long time. I normally rip my CDs, but maybe I'll take a look later if I'm ever bored.

**Comment by Dudemanguy** [comment]
Oh so I just realized that you're actually supposed to seek with chapters for cdda. `<` and `>` won't work because it's not actually a playlist. Not exactly intuitive, but probably not really work changing. `@` and `!` work fine for me. That doesn't change the fact that the log message is completely wrong though.

**Comment by qyot27** [comment]
> Not exactly intuitive, but probably not really worth changing.

Although for anyone that wants to, [betterchapters](https://github.com/Argon-/mpv-config/blob/master/scripts/betterchapters.lua) exists for the 'seek chapters if any, then playlist entries' behavior.

My memory could be very unreliable on this, but I *thought* that used to be the logic used, as I didn't always use that script to accomplish it.  If that was the old seek logic, the change would have happened when `input.conf` got overhauled.

**Comment by Dudemanguy** [comment]
The log shouldn't lie to you anymore as of 3504136d3ff8728ae2ea841bc4309cc07138f113 and you should be able to switch tracks via chapters, so closing.
