### ISSUE TITLE
Duplicate frames and frames dropping with Option + s 

### ISSUE THREAD

**Issue by jjmaybank** [mpv-player/mpv#12605]
**### mpv version and platform versions**

Current build using: [v0.36.0](https://github.com/mpv-player/mpv/releases/tag/v0.36.0)

Frame dropping/duplicates of each frame is occurring with every version of MPV after 0.29.0 last updated in October 2018. Someone else had opened a thread on this issue in 2020 and it was dismissed. This is an occurrence reported by many people who use MPV to take continuous screenshots in order to make gifs on tumblr.com. Not an issue central to only my experience, the type of video being played in the program or my specific operating system. With version 0.29.0, I have taken continuous screenshots with 10 bit 1080p and 4K video without this particular issue. 

Version 0.29.0 was the go-to, but no longer opens with Mac's new operating system Sonoma so we have no choice but to upgrade and face this issue that has not been resolved all these updates later. Maybe a Mac update could patch the problem but not likely considering the date of this particular application. The big problem still lies within the updated builds of this program.

### Reproduction steps

Option + S -- screenshots are taken which are assigned to my BATCH folder, converted into DICOM files, and then loaded into Photoshop using scripts. Once converted back into frames, it's obvious that not every frame has been captured (appears to be every other frame maybe), and additionally, the frames that have been captured are duplicated which makes for a very choppy looking gif on web. I feel the need to clarify that my processes in photoshop have not changed - this is not a PS issue.

### Expected behavior

With previous version 0.29.0, every frame is captured and there are no duplicates. 

### Log file

I do not know how to attach a log file here.. Meson Build file can be found here at the bottom of the latest [v0.36.0](https://github.com/mpv-player/mpv/releases/tag/v0.36.0) source code zip file 

I have tried the following suggested configurations from other threads with no luck:

--pulse-latency-hacks
--fps=60

Any ideas?

**Comment by annagiro** [comment]
I also have been coming across this issue with MPV versions later than 0.29.1. What makes this frame duplication very frustrating is that the continuous screencap does **frame1-frame1-frame3-frame3-etc** (I've noticed this after benchmarking against a converted video on Handbrake that I import directly to Photoshop). The omission of **frames2/4/6/etc** when screencapturing is what concerns me the most.

On the other hand, MPV builds of 0.29.1 and earlier screencap in the **frame1-frame2-frame3-frame4-etc** fashion.

**Comment by cattyms** [comment]
hi, also having this issue. can not get older versions of MPV to work on MacOS Sonoma, and only the newest will work. Newest keeps duplicating frames and causing massive issues.

**Comment by Dudemanguy** [comment]
I can't reproduce on linux. Is this only a problem on mac?

**Comment by cattyms** [comment]
> I can't reproduce on linux. Is this only a problem on mac?

Pretty sure it is linked to Sonoma, as it only began to occur when 0.29.1 could no longer open on MacOS Sonoma. With any version after, only 0.36 is operable. Every time I capture, it is making duplicate frames. I have tried changing the conf file, but no success in the correction.

**Comment by Akemi** [comment]
i also have problems with the cocoa-cb/libmpv backend with my new m2 mac and ventura. it might be related to this.

a log would be nice. are you using display sync? are you on an ARM mac?

**Comment by jjmaybank** [comment]
I have FINALLY found the fix for this issue. Add the follow configs:

framedrop=no

screenshot each-frame
