### ISSUE TITLE
Filter by tag

### ISSUE THREAD

**Issue by jimmy-1000** [mpv-player/mpv#12609]
Is it possible for mpv to only play videos that contain a specific tag?
I'm trying mpv --display-tags but it doesn't work for me.
For example:
mpv --display-tags=dancing C:\Users\Jimmy\Documents\Videos
It plays all the videos in the folder, not the videos with "dancing" tag

**Comment by guidocella** [comment]
https://mpv.io/manual/master/#options-display-tags Read the documentation to see what `--display-tags` does. Filtering by tag is not supported because mpv would have to read every file in the playlist in advance, which is extremely slow.

**Comment by christoph-heinrich** [comment]
You could make a script hat checks the tags for the current file and then goes to the next if it doesn't meet your criteria.
