### ISSUE TITLE
Was error-diffusion implemented for 'gpu-next'?

### ISSUE THREAD

**Issue by CrHasher** [mpv-player/mpv#12608]
My understanding was that error-diffusion is not supported under `gpu-next`, but for some reason if I use it looks like its active:
![Screenshot 2023-10-09 090155](https://github.com/mpv-player/mpv/assets/834518/f133d2b9-f121-466e-94cb-7d170c434158)
Also there is some unknown shader right after.

**Comment by haasn** [comment]
> My understanding was that error-diffusion is not supported under gpu-next

It was added in 1fb5f06c66d07548c15159593643a5b133b148f4
