### ISSUE TITLE
Framedrops with --interpolation=yes and some --tscale filters on gpu-next

### ISSUE THREAD

**Issue by NotMithical** [mpv-player/mpv#12606]
### Important Information

- mpv version: v0.36.0-504-ge17375f1, libplacebo version v6.338.0-30-g7ca8418
- Windows Version: Windows 10 22H2, build 19045.3516
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild
- If known which version of mpv introduced the problem: Suspect it has to do with libplacebo commit 7872af1 or ebd1316 since those have to do with frame mixing and vsync, otherwise somewhere between MPV commits 9cd2a9fc and 5638fcab, or between libplacebo commits 61c1c58 and d322515.
- Possible screenshot or video of visual glitches: 
![sample 1](https://github.com/mpv-player/mpv/assets/95518825/745a3650-ee3b-4e9f-87ce-da92659e3d89)
The artifacts are harder to capture as they appear to last one frame, but a rectangular one can be seen here. Most that I saw with one particular video were all this size and shape, but some were other colors instead of black. The frame dropping is consistent however.

### Reproduction steps

Cannot easily reproduce with --no-config as the issue only seems to occur when frame timings are over a certain threshold (around 6200μs), however in previous versions the same or higher frame timings cause no issues with the same files so I don't believe that's the cause of the issue.

Attempt to play a video in latest MPV with --interpolation=yes and --vo=gpu next with demanding enough settings (or meme shaders if necessary). 

Occurs with some tscale filters, like hermite, sphinx, or even box, but not others like mitchell, oversample, or linear.

### Expected behavior
File plays smoothly and without artifacts.

### Actual behavior
Frequent frame drops and occasionally visual artifacts (visual artifacts seem to vary depending on what file I try to play)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/12842605/output.txt)

**Comment by zhongfly** [comment]
You mean build before [2023-09-25-9cd2a9f](https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-09-25-9cd2a9f) don't has this issue, but builds after [2023-09-26-5638fca](https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-09-26-5638fca) has?

**Comment by NotMithical** [comment]
Apologies, I worded that poorly. Yes, those are the builds I tested and the issue occurs after 5638fca but not before 9cd2a9f.

**Comment by zhongfly** [comment]
So 9cd2a9f is the last work version?

**Comment by NotMithical** [comment]
Correct.

**Comment by NotMithical** [comment]
Disregard the rectangular artifacts, that seems to be a separate issue starting further back, I just hadn't noticed it before for some reason.

**Comment by NotMithical** [comment]
Not sure what change fixed it but I'm no longer getting framedrops.
