### ISSUE TITLE
Libmpv plays encrypted videos

### ISSUE THREAD

**Issue by DSxiaolong** [mpv-player/mpv#12611]
Some video headers are encrypted and need to be skipped. Instead, the header information needs to be read to obtain the start position of the video, and then skipped to read and play the video data normally.
Can libmpv be implemented? It starts playing the video from the specified location in the file, skipping a segment of data in the file header.

**Comment by mlindner** [comment]
You need to add more information. For example, adding a sample file.

**Comment by DSxiaolong** [comment]
> You need to add more information. For example, adding a sample file, or adding log files.

Under normal circumstances, libmpv starts parsing video files from the file header. I want to tell libmpv to start parsing the entire video file from the 2000 byte position of the file. Skip the first 2000 bytes. Can this be achieved?

**Comment by Dudemanguy** [comment]
>Can this be achieved?

Not with libmpv, no.
