### ISSUE TITLE
mpv searches for ffmpeg library versions that don't exist

### ISSUE THREAD

**Issue by limejuicer** [mpv-player/mpv#1261]
I have a problem with my installation of mpv on my Arch Linux machine. I installed mpv via the official repositories and then tried the AUR mpv-git-latest version.
With both versions I encounter the exact same error: Whenever I try to use mpv, I get error messages that some `lib*.so.<number>` couldn't be found.

What I tried after noticing that the library files are in fact inside /usr/lib (where they belong) under for example `libavdevice.so.56` and a symlink called `libavdevice.so` linking to that file, is a little hackish. The mpv error message was `mpv: error while loading shared libraries: libavdevice.so.55: cannot open shared object file: No such file or directory`. So what I did was creating another symlink under the name `libavdevice.so.55` which linkes to `libavdevice.so` which then links to the `libavdevice.so.56` file.

I assumed that this would fix the problem, however I can't find a reason that a program would specify an exact version instead of the favorable symlink without a number following the filename.

What I get instead of the "file not found" error is this:
`mpv: /usr/lib/libswscale.so.2: version `LIBSWSCALE_2' not found (required by mpv)
mpv: /usr/lib/libavdevice.so.55: version `LIBAVDEVICE_55' not found (required by mpv)
mpv: /usr/lib/libavfilter.so.4: version `LIBAVFILTER_4' not found (required by mpv)
mpv: /usr/lib/libpostproc.so.52: version `LIBPOSTPROC_52' not found (required by mpv)
mpv: /usr/lib/libavcodec.so.55: version `LIBAVCODEC_55' not found (required by mpv)
mpv: /usr/lib/libavutil.so.52: version `LIBAVUTIL_52' not found (required by mpv)
mpv: /usr/lib/libavresample.so.1: version `LIBAVRESAMPLE_1' not found (required by mpv)
mpv: /usr/lib/libavformat.so.55: version `LIBAVFORMAT_55' not found (required by mpv)`

Is this a problem on my end? I have `ffmpeg 2.4.3` and `mpv 0.6.2_2185_g9b45b48-2` installed.

**Comment by sicwolf** [comment]
I met similar compile issue when compiling my own application with opencv (libopencv_highgui.so) which use ffmpeg (libswscale.so.2). I suspect the ffmpeg version which opencv is dependent on is not correct, but I don't know how to select the ffmpeg version when compile opencv.
Anybody know how to resolve the issue?

/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `sws_getContext@LIBSWSCALE_2'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `av_sub_q@LIBAVUTIL_52'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `avformat_alloc_context@LIBAVFORMAT_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `av_free@LIBAVUTIL_52'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `avio_close@LIBAVFORMAT_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `av_seek_frame@LIBAVFORMAT_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `avcodec_free_frame@LIBAVCODEC_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `av_codec_get_id@LIBAVFORMAT_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `avcodec_alloc_frame@LIBAVCODEC_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `av_read_frame@LIBAVFORMAT_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `avformat_free_context@LIBAVFORMAT_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `sws_getCachedContext@LIBSWSCALE_2'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `avformat_write_header@LIBAVFORMAT_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `av_guess_format@LIBAVFORMAT_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `av_register_all@LIBAVFORMAT_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `av_write_frame@LIBAVFORMAT_54'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../libopencv_highgui.so: undefined reference to `av_free_packet@LIBAVCODEC_54'
