### ISSUE TITLE
gpu-next and blend-subtitles=yes use high GPU performance

### ISSUE THREAD

**Issue by Hill-98** [mpv-player/mpv#12623]
### Important Information

Provide following Information:
- mpv version: v0.36.0-502-g78719c14
- Windows Version: Windows 11 [10.0.22621.2428]
- Source of the mpv binary: <https://github.com/shinchiro/mpv-winbuild-cmake>
- If known which version of mpv introduced the problem: 20231006-git-07995f5(shinchiro/mpv-winbuild-cmake)
- Possible screenshot or video of visual glitches

use command:`mpv --no-config --vo=gpu-next --interpolation=yes --tscale=oversample --video-sync=display-resample --blend-subtitles=yes --profile=gpu-hq "[DMG&VCB-Studio] BOCCHI THE ROCK! [01][Ma10p_1080p][x265_flac].mkv"`

If I use the `20231005-git-d32f1aa` version, my GPU power is 70W, but if I use `20231006-git-07995f5`, the GPU power rises to 100W.

If no subtitles are loaded or `blend-subtitles=no`, there is no difference in GPU power between the two versions.

Also, if `interpolation=yes`, there is no difference.

My GPU is Intel ARC A750

**Comment by Dudemanguy** [comment]
Probably my fault. I thought I preserved the same amount of redraws but I guess it must be different when interpolation is on.

**Comment by Hill-98** [comment]
Sure, but I'm going to bed and will test it when I wake up.

**Comment by Hill-98** [comment]
@Dudemanguy solved!
