### ISSUE TITLE
gpu-api vulkan: segfault

### ISSUE THREAD

**Issue by cold-nagai** [mpv-player/mpv#12625]
### Important Information

Provide following Information:
<details><summary>mpv --version</summary>

```
mpv v0.36.0-522-g9c9ba3cf30 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Oct 13 2023 01:50:05
libplacebo version: v6.338.0-30-g7ca8418f
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```
</details>

- Arch Linux 6.5.7-arch1-1
- aur/mpv-git 0.36.0-522-g9c9ba3cf30 
- extra/hyprland 0.30.0-1

### Reproduction steps
 mpv --no-config --vo=gpu-next --gpu-api=vulkan

### Log file
https://0x0.st/H4Vn.txt

`segmentation fault (core dumped)`

**Comment by cold-nagai** [comment]
Probably related to https://github.com/mpv-player/mpv/issues/12562

libplacebo-git-6.338.0.30.g7ca8418f-1 rebuild also failed `test.vulkan.c`

**Comment by Dudemanguy** [comment]
Looks like the segfault is in spriv going by that backtrace. But yes probably the same issue.

**Comment by Dudemanguy** [comment]
The libplacebo vulkan test does actually fail for me, but no segfault here.

**Comment by cold-nagai** [comment]
After rebuilding mpv with extra/spirv-tools, i got 

`mpv: symbol lookup error: /usr/lib/libSPIRV.so.13: undefined symbol: _ZN8spvtools23CreateAggressiveDCEPassEbb`

With chaotic-aur/spirv-tools-tkg-git, mpv runs fine, except that it segfaults when toggling deband as well as --gpu-api=vulkan --gpu-context=waylandvk

Am i supposed to use spirv-tools-git with mpv-git?

**Comment by Dudemanguy** [comment]
>Am i supposed to use spirv-tools-git with mpv-git?

No that's not supposed to be needed. I'm on glslang 13 myself. I don't know why you have that message (packaging error?)>

**Comment by cold-nagai** [comment]
This issue is likely caused by glslang-git or spirv-tools-git. I rebuilt mpv-git using only aur sources just to make sure chaotic-aur builds don't cause any problem.

`mpv --no-config --vo=gpu-next --input-conf=~/.config/mpv/input.conf --gpu-api=vulkan --gpu-context=waylandvk 1559397194856.mp4     `              
…
`zsh: segmentation fault (core dumped)  mpv --no-config --vo=gpu-next --input-conf=~/.config/mpv/input.conf`
https://0x0.st/H4nK.txt

— Never displays a single frame, coredumps straight away.


`mpv --no-config --vo=gpu-next --input-conf=~/.config/mpv/input.conf --gpu-api=vulkan --scale=catmull_rom 1559397194856.mp4`                  

`zsh: segmentation fault (core dumped)  mpv --no-config --vo=gpu-next --input-conf=~/.config/mpv/input.conf`
https://0x0.st/H4nO.txt

— Media plays fine with catmull-rom as --scale. coredumps upon `cycle deband`


Should i include mpv verbose as well?

**Comment by Dudemanguy** [comment]
The segfault is somewhere in libSPIRV going by those backtraces which is most likely something we can't do anything about. I doubt it's actually an mpv or libplacebo issue.

**Comment by cold-nagai** [comment]
aur/libplacebo-git defaults to extra/shaderc instead of the shaderc-git fsm. aur/shadec-git fixed the issue.

`Sync Dependency (1): shaderc-2023.4-2`
