### ISSUE TITLE
Arabic Subtitle Encode problem!

### ISSUE THREAD

**Issue by Za7ef-SA** [mpv-player/mpv#1263]
Hello,
I have problem with Arabic subtitle:
In MPC-HC Player everything looks fine:
![mvp](https://cloud.githubusercontent.com/assets/5797362/5007053/6d49fbd6-6a5d-11e4-9045-7dfbeaa50489.png)

but in mpv player i have problem with the encoding:
![mpc-hc](https://cloud.githubusercontent.com/assets/5797362/5006523/2097a0ca-6a55-11e4-84ca-2adaaaf4f406.png)

I think the solve of this problem is allowing the user to change the character encoding, like what other players do.
![MPC-HC Options](https://cloud.githubusercontent.com/assets/5797362/5014298/a7afdcb2-6aa5-11e4-8657-ea075703c36c.png)

**Comment by wm4** [comment]
Nothing new, closing.
