### ISSUE TITLE
Random video glitches or crashes when using D3D11va with Radeon gpus (rx 6600)

### ISSUE THREAD

**Issue by kungfubeaner** [mpv-player/mpv#12637]
### Important Information

Provide following Information:
- mpv version

mpv-x86_64-v3-20231008-git-78719c

- Windows Version

Windows 10  22H2

- Source of the mpv binary

Schinchiro build

If known which version of mpv introduced the problem

Not sure exactly but last few versions where reloading api changed for playlist managers

### Reproduction steps

Use  D3D11va for playback of videos

### Expected behavior

Playback with no video glitching or crashing

### Actual behavior

MPV glitches at random times for a split second or crashes

### Log file

https://0x0.st/H4UP.txt

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by amariami** [comment]
[Cenk's Campaign Is Criminal?](https://youtu.be/ew7rU7lAE9w?si=cxjP5S1NL45QJRyC) working fine `--vo=gpu and --vo-gpu-next` with i-GPU RDNA 2.0 
```
Both Official Adrenaline driver 23.9.3 and Rnd.ID Driver (All in one parameter management >> Clean GPU parameter list >> load AMD fail-safe GPU Parameter) 
```
[vo=gpu](https://github.com/mpv-player/mpv/files/12910637/GPUt.txt)
[vo=gpu-next](https://github.com/mpv-player/mpv/files/12910638/GPU-Next.txt)

**Comment by kungfubeaner** [comment]
I just chose a random video from a yt suggestion suggestion to try lol.  Dunno why Im having those issues and just can't figure it out was fine all year till recently.   Thanks for the reply though.  I'll  try to add in those parameters to my config --vo-gpu etc and see what works
