### ISSUE TITLE
regression: "default" stream in a media not being used in v0.36.0 by default

### ISSUE THREAD

**Issue by h9419** [mpv-player/mpv#12630]
### Important Information

Provide following Information:
- mpv version: mpv-0.36.0-x86_64 and mpv-0.36.0-x86_64-v3
- Windows Version: Windows 11 22H2 (Build 22621.2428)
- Source of the mpv binary: [Windows builds by shinchiro](https://sourceforge.net/projects/mpv-player-windows/files/release/)
- If known which version of mpv introduced the problem: 0.36.0 and 0.36.0-v3. Not reproducible in 0.35.1
- Possible screenshot or video of visual glitches

### Reproduction steps

- Prepare a video with multiple streams of the same kind (e.g. subtitle and the default is not the first). Following is the command used to create a video where the 3rd subtitle stream is set to default
  - `ffmpeg -i "video.h264" -i "sub0.srt" -i "sub1.srt" -i "sub2.srt" -map 0 -map 1 -map 2 -map 3 -disposition:s:0 0 -disposition:s:1 0 -disposition:s:2 default "out.mkv"`
- Open said video in mpv with `--no-config` option

### Expected behavior

MPV plays the video and displays the 3rd subtitle stream (same content as `sub2.srt` file)

### Actual behavior

MPV plays the video and no subtitle is enabled

### Log file

Log file from 0.36.0
- [0.36.0.txt](https://github.com/mpv-player/mpv/files/12902345/0.36.0.txt)

Log file from last version without this problem (0.35.1):
- [0.35.1.txt](https://github.com/mpv-player/mpv/files/12902346/0.35.1.txt)

### Sample files

- Composed video with 3 subtitle streams: [out.mkv](https://0x0.st/H4x0.mkv)
- Subtitle stream 0: [sub0.srt](https://0x0.st/H4xD.srt)
- Subtitle stream 1: [sub1.srt](https://0x0.st/H4xk.srt)
- Subtitle stream 2: [sub2.srt](https://0x0.st/H4xd.srt)
- Video stream to create composed video: [video.h264](https://0x0.st/H4xU.h264)

**Comment by llyyr** [comment]
Can you try master? This should be fixed.

**Comment by h9419** [comment]
Thank you for the quick reply. I don't have the development environment setup for my Windows machine so I am using the git build of [Windows builds by shinchiro](https://sourceforge.net/projects/mpv-player-windows/files/release/). 

Can confirm that the problem have been fixed since at least 20230806-git-6729285. It was reproducible in 20230723-git-ca4192e or older build and release 0.36.0

May I ask whether there's a timeline for the next release?
