### ISSUE TITLE
mpv attempts to access comments (lines starting with '#') as paths in playlist files

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#12631]
### Important Information

- Fedora 38 (Workstation)
- [Flatpak](https://flathub.org/apps/details/io.mpv.Mpv)

```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
libplacebo version: v6.292.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```

### Reproduction steps

1. Use local files, or rip some from the web, e.g. :

```
$ yt-dlp --paths /tmp/music 'https://en.wikipedia.org/wiki/Public_domain_music'
```

2. Write the file paths to a playlist file:

`$ find /tmp/music/ -type f > /tmp/playlist.m3u8`

3. Comment out the first line in the `.m3u8` file by adding the `#` character.

4. Play the playlist in mpv:

`$ mpv --no-config --no-video --playlist=/tmp/playlist.m3u8`

### Expected behavior

mpv silent ignores the lines which have been commented out. Comments in [M3U files](https://en.wikipedia.org/wiki/M3U) appears to be an established standard. 

Preferably the same behavior would be applied to any plaintext file containing paths when using the `--playlist=<path>` flag (I don't always use file extensions on Linux, especially for files of a disposable nature).

### Actual behavior

mpv attempts to read the said lines as files and prints errors:

```
[file] Cannot open file '/tmp/#/tmp/music/Public_domain_music_-_Wikipedia_1-Public_domain_music-1.mkv': No such file or directory
Failed to open /tmp/#/tmp/music/Public_domain_music_-_Wikipedia_1-Public_domain_music-1.mkv.
```

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/12902742/mpv.log)

### Sample files

If needed, can be ripped trivially from [a Wikipedia page](https://en.wikipedia.org/wiki/Public_domain_music) (see above).

**Comment by llyyr** [comment]
This is because you need the `#EXTM3U` header for the file to actually be decoded as a m3u8 playlist.

The error message in your log clues you in that mpv doesn't think it is reading a m3u8 playlist: `[playlist] Reading plaintext playlist.`

**Comment by 07416** [comment]
> The error message in your log clues you in that mpv doesn't think it is reading a m3u8 playlist: `[playlist] Reading plaintext playlist.`

Is it sensible to add support for comments in plaintext playlist files? An mpv config option perhaps?

Would be slightly more convenient to keep redirecting paths directly to new files, as shown in the issue with `find`. But the issue has been more or less resolved, adding the said header makes mpv behave as expected:

```
#EXTM3U
#/tmp/music/Public_domain_music_-_Wikipedia_1-Public_domain_music-1.mkv
/tmp/music/Public_domain_music_-_Wikipedia_2-Public_domain_music-2.mkv
```

**Comment by 07416** [comment]
> This is because you need the `#EXTM3U` header for the file to actually be decoded as a m3u8 playlist.
> 
> The error message in your log clues you in that mpv doesn't think it is reading a m3u8 playlist: `[playlist] Reading plaintext playlist.`

The extension `.m3u` / `.m3u8` is not enough (used in the issue)? Can this behavior, for its part, be changed?

**Comment by guidocella** [comment]
This already works if you use `mpv playlist.m3u8` instead of `mpv --playlist=playlist.m3u8`.

**Comment by 07416** [comment]
> This already works if you use `mpv playlist.m3u8` instead of `mpv --playlist=playlist.m3u8`.

I didn't realize that playlist files can be read without CLI flags since my `ignore.lua` script blocks them from loading. If anyone knows how to change to behavior of the script not to apply when pointed at directly to an excluded filetype, I'm very interested.

The folders I work with often have stray playlist files which just repeat the directory structure (I won't remove any data for archival reasons, for now).

```
-- .bmp, .dib — https://en.wikipedia.org/wiki/BMP_file_format
-- .URL — https://en.wikipedia.org/wiki/Bookmark_(digital)#Storage
-- .jxl — https://en.wikipedia.org/wiki/JPEG_XL
-- .vtx — https://en.wikipedia.org/wiki/Microsoft_Visio
-- .ffp — FLAC fingerprint

local blacklist = {'cue', 'txt', 'pdf', 'log', 'sfv', 'md5', 'nfo', 'm3u', 'm3u8', 'accurip', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'jxl', 'bmp', 'dib', 'part', 'url', 'html', 'htm', 'vtx', 'ffp'}
-- removed archive formats `'rar', 'zip', '7z',`

local temp = {}
for _, ext in pairs(blacklist) do
    temp[ext] = true
end
blacklist = temp

-- Observing playlist instead of playlist-count would call this 3 times
-- unnecessarily on each playlist-entry change, though it would be more correct
-- since it would exclude blacklisted files in single-file directory/playlists,
-- which don't change playlist-count, and files added by calling loadfile with
-- a blacklisted file.

mp.observe_property('playlist-count', 'native', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        if blacklist[playlist[i].filename:lower():match('%.(%w+)$')] then
            mp.commandv('playlist-remove', i-1)
        end
    end
end)
```

**Comment by guidocella** [comment]
```lua
mp.observe_property('playlist-count', 'native', function (_, count)
    if count == 1 then
        return
    end
```
