### ISSUE TITLE
Inputting Unicode characters in mpv console

### ISSUE THREAD

**Issue by undersource** [mpv-player/mpv#12635]
### Important Information

Provide following Information:
- mpv version 1:0.36.0-1
- ArchLinux
- Window Manager Sway/Wayland

### Bug

Inputting Unicode characters (Russian letters in my case) into the mpv console does not work on Wayland, unlike Xorg.

**Comment by Dudemanguy** [comment]
Should have been fixed by https://github.com/mpv-player/mpv/pull/12012.
