### ISSUE TITLE
youtube playback with yt-dlp only works sometimes/randomly

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#12647]
mpv version: v0.36.0 
Platform and Version: Windows 7 Build 7601 Service Pack 1
Source: github
yt-dlp version: 2023.10.13 (latest)

Hi, I spotted some weird behaviour trying run youtube with yt-dlp in mpv.
It works sometimes and sometimes it doesn't. The mpv window opens and thats it.
I thought that maybe over time this will "fix it self" with a newer yt-dlp version, but it is the same since the beginning (few months) so I decided to report this. 
I also reported this on yt-dlp. But I got no answer. Maybe someone here is facing the same weird beheviour.

logfile line 166:"No youtube-dl found with path yt-dlp.exe in config directories" I don't know what this means

Thank you

### Reproduction steps
drag and drop youtube link into mpv or run command "mpv + youtube link"

### Expected behavior
youtube stream starts every time

### Actual behavior
random behaviour, sometimes youtube stream starts, sometimes mpv just opens and thats it

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/12914876/output.txt)

**Comment by llyyr** [comment]
mpv tries running yt-dlp subprocess but stays stuck there. This is probably a network issue rather than a mpv/yt-dlp issue.

You should try running the command in the logs independent of mpv to try to isolate the issue `yt-dlp --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --all-subs --no-playlist -- https://www.youtube.com/watch?v=SMyLyueAmkI`

**Comment by geextahslex** [comment]
ok thank you. I tried to run this command. First nothing happens but after a while there comes a text dump. I think it is cut off because its too long. I saved everything 
[neu 2.txt](https://github.com/mpv-player/mpv/files/12915288/neu.2.txt)

**Comment by llyyr** [comment]
It's probably a network issue or something, either way not a mpv issue.

**Comment by geextahslex** [comment]
I don't know. No other program has any issues with getting a internet connection

**Comment by llyyr** [comment]
You just reproduced the issue using yt-dlp in the command line, how is it a mpv issue?

**Comment by geextahslex** [comment]
solution:
--force-ipv4
