### ISSUE TITLE
Audio playback freezes when using exclusive mode

### ISSUE THREAD

**Issue by zhengqwe** [mpv-player/mpv#12640]
### Important Information

Provide following Information:
- mpv version
0.36.0
- Windows Version
Windows 10
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20231015/mpv-x86_64-v3-20231015-git-78d4374.7z
- If known which version of mpv introduced the problem
don't know, but this problem already existed a few months ago
- Possible screenshot or video of visual glitches

### Reproduction steps
Play any audio file use `mpv --no-config --audio-exclusive=yes`

### Expected behavior
The sound plays normally
### Actual behavior
Sound playback freezes, it sounds like 0.1x speed, and the actual playback speed also seems to be 0.1x
### Log file

[log.txt](https://github.com/mpv-player/mpv/files/12908872/log.txt)

**Comment by amariami** [comment]
related to #12615

**Comment by amariami** [comment]
> but `--ao=openal` will cause exclusive mode not work

`--ao=sdl --af=format=srate=384000:format=double ` AO sdl?
