### ISSUE TITLE
mpv: symbol lookup error when compiled with shaderc

### ISSUE THREAD

**Issue by Lovecraft-github** [mpv-player/mpv#12654]
### Important Information
I tried to compile mpv (build .deb package) with -Dshaderc=enabled and -Dspirv-cross=enabled.
The compilation seems to work fine and produce de .debs like always, but trying to play any video i get this error:
"mpv: symbol lookup error: /lib/x86_64-linux-gnu/libshaderc.so.1: undefined symbol: _ZN7glslang8TProgram10getInfoLogEv"
With --no-config same result
Only way to produce a deb that work is uninstalling shadderc and spirv dependencies or give libplacebo the build option to disable shadercc (with a file libplacebo_options with -Dshaderc=disabled.
Disabling them in mpv_options produce also the crash.

- mpv version
2:2023.10.16.71cf360e33 (package name, --version crash also)
- Linux Distribution and Version 
ubuntu 23.10
- Source of the mpv binary
compilation of deb package with mpv-build repo
- If known which version of mpv introduced the problem
Don't know
- Window Manager and version
Gnome 45.0, Wayland
- GPU driver and version
Tried with default mesa stock (AMD) and oibaf ppa. Same result

### Reproduction steps

Open any video, with my old config or with --no-config.

### Expected behavior

Play the video ;-)

### Actual behavior

Crash

### Log file

Doesn't produce a log, only the error
mpv: symbol lookup error: /lib/x86_64-linux-gnu/libshaderc.so.1: undefined symbol: _ZN7glslang8TProgram10getInfoLogEv)

**Comment by Lovecraft-github** [comment]
Asking myself in case anyone has this issue.
The problem was the shaderc version of ubuntu repositories.
Uninstaling it and building shader from https://github.com/google/shaderc and all works fine.

**Comment by clort81** [comment]
Thank you friend. I had this problem in devuan (debian sid mpv) in May 2025.
