### ISSUE TITLE
Build fail on macOS 10.14

### ISSUE THREAD

**Issue by deus0ww** [mpv-player/mpv#12653]
### Important Information

Provide following Information:
- mpv HEAD
- macOS 10.14.6

### Reproduction steps
Build fail with:
../video/out/mac_common.swift:115:13: error: reference to property 'swapLock' in closure requires explicit 'self.'

Problematic Code in /video/out/mac_common.swift:113:
```
        let signalSwap = { [self] in
            selfswapLock.lock()
            swapTime += 1
            swapLock.signal()
            swapLock.unlock()
        }
```

Fix from @Akemi on IRC:
```
        let signalSwap = {
            self.swapLock.lock()
            self.swapTime += 1
            self.swapLock.signal()
            self.swapLock.unlock()
        }
```

**Comment by Akemi** [comment]
the fix worked? which swift version do you have?

**Comment by deus0ww** [comment]
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin18.7.0

(Installed with Xcode 11.3.1, the last version for macOS 10.14)

**Comment by deus0ww** [comment]
Closing because #12431 and the bump in minimum macOS version (#12723).

**Comment by Akemi** [comment]
reopening since this might be a problem till swift 5.5
