### ISSUE TITLE
need advice on how to find the cause of mpv not triggering lua script

### ISSUE THREAD

**Issue by JunkyardCat** [mpv-player/mpv#12669]
i need advice on how to debug mpv to see why one of my script isnt being fired when pressing the designated key
I'm using windows 10 mpv 0.35.1 and put the script in
%AppData%\Roaming\mpv\scripts\\<folder_name>\script.lua

thanks

**Comment by christoph-heinrich** [comment]
How about you look at [the documentation](https://mpv.io/manual/master/#script-location)
`%AppData%\Roaming\mpv\scripts\<script_name>\main.lua`
