### ISSUE TITLE
Frames stutter and freeze for GIF playback

### ISSUE THREAD

**Issue by myQwil** [mpv-player/mpv#12660]
### Important Information

- mpv version: git 71cf360
- Linux Distribution and Version: ArchLinux 6.5.5-arch1-1
- Source of the mpv binary: built from source
- If known which version of mpv introduced the problem: git c82c55b
- Window Manager and version: KDE KWin 5.27.8-4
- GPU driver and version: NVIDIA GeForce GTX 760 with proprietary driver 470.199.02-5

Ever since the switch was made from microseconds to nanoseconds for frame duration and pts, there have been issues with playback of GIF's and low-framerate videos that don't have an audio stream.

Playback will often freeze, and the only way to unfreeze it is to wake up the display by moving the cursor around.

I have a temporary band-aid solution:
```diff
--- a/video/out/vo.c
+++ b/video/out/vo.c
@@ -785,6 +785,7 @@ bool vo_is_ready_for_frame(struct vo *vo, int64_t next_pts)
         int64_t now = mp_time_ns();
         if (next_pts > now)
             r = false;
+        next_pts *= 0.875;
         if (!in->wakeup_pts || next_pts < in->wakeup_pts) {
             in->wakeup_pts = next_pts;
             // If we have to wait, update the vo thread's timer.

```
Increasing `video-timing-offset` also works, but the amount by which this value needs to be increased, increases the lower the video's framerate is, which is why I went with shrinking `next_pts` proportionally, rather than subtracting a specific amount like `timing_offset`.

### Reproduction steps

Try playing this GIF file in mpv:
![homer](https://github.com/mpv-player/mpv/assets/3401272/3cbb53b4-f373-4117-8a7b-f5a7540561cd)

### Expected behavior

The GIF should play seamlessly from start to finish

### Actual behavior

The GIF stutters and freezes whenever the cursor stops moving, or the OSC stops performing a fade-in/fade-out animation.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/12926149/log.txt)

**Comment by llyyr** [comment]
Bisected to 5d44cf93df47046c779fc4da68a09812a2ce4004 and only happens on x11.

**Comment by myQwil** [comment]
Thanks, that change fixes the problem for me.

**Comment by llyyr** [comment]
Actually, vo=drm is broken too. I only now realized displayvk doesn't use this common code.
