### ISSUE TITLE
Visual glitch in stats.lua with gpu-next

### ISSUE THREAD

**Issue by I2ujbNGakP8KfLKbho0Z** [mpv-player/mpv#12671]
### Important Information

Current mpv version: v0.36.0-549-g78d43740
Windows version: Win10 Pro 22H2 19045.3570
Source of mpv: shinichiro windows build
Problem present since at least v0.36.0-502-g78719c14

Screenshots from different mpv versions that display this issue:
![Screenshot 2023-10-18 212438](https://github.com/mpv-player/mpv/assets/91436030/c05427f2-0782-4744-acb9-6fdbd294e78b)
![Screenshot 2023-10-18 212614](https://github.com/mpv-player/mpv/assets/91436030/678347d5-dc52-4709-bca6-6b24e2dbafff)

Screenshot (including OSD) from within mpv doesn't show display this glitch:
![Fireball - Ep01  DVD-576p Flep _00_00_07 441_000001](https://github.com/mpv-player/mpv/assets/91436030/d31f2ea0-2476-488e-9016-0dd7fb146e58)

### Reproduction steps

With the supplied example file, the visual glitch should be on display if --no-config and --vo=gpu-next are used.
When playback has started, activate the stats interface to see the glitch. It should not be present during normal playback.

This doesn't happen if vo=gpu-next isn't used.

### Expected behavior

Only the stats are displayed when opening them.

### Actual behavior

The stats are displayed. To the right of the stats a weird triangular red to blue gradient appears.

### Log file

[mpvweird1.log](https://github.com/mpv-player/mpv/files/13033351/mpvweird1.log)
[mpvweird2.log](https://github.com/mpv-player/mpv/files/13033353/mpvweird2.log)

These log files are from different versions of mpv, both from playback sessions that displayed the glitch

### Sample files

Example file with this issue: https://0x0.st/HJAd.mkv
I have tried a few files with similar formats, not all of them displayed the issue for me.

**Comment by dokur0chan** [comment]
It's a tear in the fabric of reality.

Goes into stats.conf:
```
plot_tonemapping_lut=no
```

**Comment by I2ujbNGakP8KfLKbho0Z** [comment]
That makes sense, it kind of looked like a diagram with the grid on it but i was confused because it doesn't appear with all files. 
Is there a reason for that?
The file it appears on is not HDR or anything like that.

**Comment by Jules-A** [comment]
> Goes into stats.conf:
> 
> ```
> plot_tonemapping_lut=no
> ```

That doesn't disable it though :/

**Comment by dokur0chan** [comment]
@I2ujbNGakP8KfLKbho0Z 
The graph is used for any tonemapping operation, which includes gamut mapping. You're using a BT.601 DVD source.

@Jules-A 
Werks on my machine. :)

**Comment by I2ujbNGakP8KfLKbho0Z** [comment]
Ah, didn't think about that. Thanks for the answer!

**Comment by Jules-A** [comment]
> @Jules-A Werks on my machine. :)

![image](https://github.com/mpv-player/mpv/assets/1760158/919e002d-c733-47ed-a353-00b28af5a358)

I'm using the latest Shinchiro build, are you sure it's not something else?

**Comment by dokur0chan** [comment]
![image](https://github.com/mpv-player/mpv/assets/139610756/a291eea2-33b2-4310-9965-e3afe37d5ab2)

**Comment by dokur0chan** [comment]
> Though honestly it's a little annoying for the average user to create the folder/file for it just to disable it. 

https://mpv.io/manual/master/#options-script-opts
> Set options for scripts. A script can query an option by key. If an option is used and what semantics the option value has depends entirely on the loaded scripts. Values not claimed by any scripts are ignored.
This is a key/value list option. See [List Options](https://mpv.io/manual/master/#list-options) for details.
```
script-opts=stats-plot_tonemapping_lut=no
```

**Comment by haasn** [comment]
I suppose we could disable this by default unless tone mapping is active? I guess the gamut mapping graph is less useful generally than the tone mapping graph, and even that is only useful to power users. Then again, most of stats.lua is only useful to power users...

🤷🏻

**Comment by kasper93** [comment]
> Then again, most of stats.lua is only useful to power users...

To be honest all other things are labeled, so they are easy to read, even if not all value are fully understand by the users.

`plot_tonemapping_lut` is just a blob that is quite literally impossible to understand. What are the axis? What are the values? What is the range? What does red color mean? What does blue color mean?

I think until someone explains that to you or you read code it is not really realistic to expect average Joe to understand that.

I vote to set `plot_tonemapping_lut=false` by default. With the option for power users to enable it if needed.

Also while we at it, we could disable all other graphs, because they are quite heavy to render. In some cases they cause frame drops alone.
```
    plot_perfdata = false,
    plot_vsync_ratio = false,
    plot_vsync_jitter = false,
```

**Comment by haasn** [comment]
Maybe we could plot the tone mapping graph on a new stats page?

**Comment by Hrxn** [comment]
+1 on new stats page, we still have stats pages 5,6,7,8, and 9 free to use 🤷🏻

**Comment by kasper93** [comment]
> Maybe we could plot the tone mapping graph on a new stats page? This page could also have more detailed printouts of all HDR metadata, histogram, detected values, active tone mapping curve, etc.

I don't think there is enough information to justify yet another page, but I guess they are free. Also it sounds like distant future plan, while right now I would vote to disable plot by default as it looks like it is not useful for majority of users.
