### ISSUE TITLE
Allow libmpv frontends to support the focused property

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#12676]
### Expected behavior of the wanted feature

When I try setting the `focused` property in mpv.net, the error MPV_ERROR_PROPERTY_ERROR is returned. This means scripts that use the focused property cannot be supported.

Now, there are some properties like `window-minimized` and `window-maximized` not having this problem, it allowed me to fully support OSC window functionality like the minimize and maximize buttons in borderless mode.

**Comment by Dudemanguy** [comment]
The focus property is read only so you can't set it. From the linked issue, it appears like the user isn't able to read the property for some reason on mpv.net (his script works in normal mpv)? To my knowledge there's no such restriction. I guess there may be some weirdness with however win32's event loop works.

**Comment by kasper93** [comment]
> I guess there may be some weirdness with however win32's event loop works.

Child windows is probably just not focused. Does `SetFocus(child_hwnd);` help? But then probably you would lose focus on parent window, or maybe not, you need to check. mpv bases focus status on `WM_KILLFOCUS` and `WM_SETFOCUS`.

**Comment by stax76** [comment]
It seems to work when I just forward WM_KILLFOCUS and WM_SETFOCUS to the mpv window. Thanks.
