### ISSUE TITLE
Validating snap maintenance 

### ISSUE THREAD

**Issue by capecrusader-121** [mpv-player/mpv#12678]
Hey there, snap maintainer here.
Recently on requests of users i had sought access to removable-media for mpv snap from snapcraft reviewers as per snapcraft review process automatic access to such plugs must need a publisher vetting, since the snap is currently a 3rd party package is the upstream willing to take over its maintenance/ownership ?  , if not do they have any objections on me maintaining the snap as a community contributor ?

This is needed to process the request. Thanks.

The Request:  https://forum.snapcraft.io/t/autoconnect-request-for-mpv/37326/5

Snap Manifest: https://git.launchpad.net/mpv-snap

Store Page: https://snapcraft.io/mpv

**Comment by capecrusader-121** [comment]
Thanks for confirming. So can this be closed ?

**Comment by Dudemanguy** [comment]
Yup.
