### ISSUE TITLE
Make mpv reload last opened file on startup

### ISSUE THREAD

**Issue by artjomsR** [mpv-player/mpv#12682]
Pretty much title. Most of the time, if I open mpv, it's to continue watching whatever media I was watching before. It would be nice to open that file automatically rather than doing it manually every time.

I also use `save-position-on-quit` which means that mpv would start with a paused state on load. So when I launch mpv and I want to continue watching, I just press play. And if I want to open a new file, I would load it as I normally would.

**Comment by christoph-heinrich** [comment]
There are scripts that keep a history of opened files. I don't know if any of them can automatically open the last file when mpv starts idle, but opening the history with a keybind and choosing the latest file isn't that big of a deal.

**Comment by artjomsR** [comment]
Ok, thank you. I've found https://github.com/Eisa01/mpv-scripts#simplehistory which does what I want
