### ISSUE TITLE
Change the window title with a hotkey?

### ISSUE THREAD

**Issue by RalfReddings** [mpv-player/mpv#12689]
I know I can set the window title for every new window via the **MPV.conf** file with:
    
    --title="window title"
    

But there are many times I need to change the window title, for the active window, on the go. I want to take advantage of Property Expansion by just temporarily showing the properties when I need them and then turning them of, as my PC is slow.

I  have so far tried with no success:
    
    7     --title="window title"
    3     title="window title" 
    

Any help would be greatly appreciated!

**Comment by guidocella** [comment]
https://mpv.io/manual/master/#command-interface-set-%3Cname%3E-%3Cvalue%3E

**Comment by RalfReddings** [comment]
That was what I needed. Thank you!
