### ISSUE TITLE
Properly handle `nil` values in the conditional auto profiles expression?

### ISSUE THREAD

**Issue by Hrxn** [mpv-player/mpv#12695]
Quoting from the mpv manual:

>A more robust way to access properties is using p.property_name or get("property-name", default_value). The automatic variable to property magic will break if a new identifier with the same name is introduced (for example, if a function named pause() were added, pause would return a function value instead of the value of the pause property).

>Note that if a property is not available, it will return nil, which can cause errors if used in expressions. These are logged in verbose mode, and the expression is considered to be false.

So far, I've been using `p.property_name` in my auto profiles, like this, for example:
```
[fps59+]
profile-cond=p.container_fps > 59
# profile-restore=copy
# ...
```
And I guess this is behaving as expected, but I also get these error messages in the verbose information to stdout:
```
[auto_profiles] Profile condition error on evaluating: [string "profile fps59+ condition"]:1: attempt to compare number with nil
```

<br><br>

By the way, I noticed something curious here:

If I do `p.container_fps > 59 `, the result is
```
[..] [string "profile fps59+ condition"]:1: attempt to compare number with nil
```

While with `p.container_fps < 59`, it is
```
[..] [string "profile fps59+ condition"]:1: attempt to compare nil with number
```
Is this normal Lua behavior? I mean, the order of operand 1 - operator - operand 2 has not been changed?

<br><br>

Anyway, how to handle this the right/robust/optimal way? `get("property-name", default_value)` avoids this issue, but I don't think this is really straightforward to use. For example, what is a reasonable default value? 0? 999999? Depending if you want to be above or below?

I don't really know Lua, but I've seen `expr_a ~= nil` in use before, is this the correct way to do this?
Or even a simpler way to check the availability of a value?

Bonus question:
How to use a property like `'video-params/average-bpp'` with `p.property_name`?
`p['video-params/average-bpp']`? 
Or is this not actually functionally equivalent?
Therefore we have to use `get('video-params/average-bpp')`?

**Comment by guidocella** [comment]
> for example, if a function named pause() were added, pause would return a function value instead of the value of the pause property

Realistically no one is going to add functions to `auto_profiles.lua` (which is just a 200-line script) named like existing properties.

> Is this normal Lua behavior? I mean, the order of operand 1 - operator - operand 2 has not been changed?

Apparently so, `nil > 1` and `nil < 1` in Lua's CLI print different errors. I guess `>` is implemented as `<` with the arguments swapped.

> Anyway, how to handle this the right/robust/optimal way?

`msg-level=auto_profiles=status`

> get("property-name", default_value) avoids this issue, but I don't think this is really straightforward to use. For example, what is a reasonable default value? 0? 999999? Depending if you want to be above or below?

You can use 0 and `math.huge` (infinity).

> I don't really know Lua, but I've seen expr_a ~= nil in use before, is this the correct way to do this?

That checks if a property is available. You can use any way you want.

> Or even a simpler way to check the availability of a value?

`profile-cond=container_fps and container_fps > 59` is shorter. Note that in Lua only `nil` and `false` are falsy, and 0 is truthy.

> How to use a property like 'video-params/average-bpp' with p.property_name?
> p['video-params/average-bpp']?
> Or is this not actually functionally equivalent?
> Therefore we have to use get('video-params/average-bpp')?

`video_params['average-bpp']`, `p['video-params/average-bpp]` and `get('video-params/average-bpp')` are all equivalent.

**Comment by Hrxn** [comment]
> > for example, if a function named pause() were added, pause would return a function value instead of the value of the pause property
> 
> Realistically no one is going to add functions to `auto_profiles.lua` (which is just a 200-line script) named like existing properties.

Does this only apply to `auto_profiles.lua`?
Can't any custom script export something like `pause()`, for example?

> 
> > Is this normal Lua behavior? I mean, the order of operand 1 - operator - operand 2 has not been changed?
> 
> Apparently so, `nil > 1` and `nil < 1` in Lua's CLI print different errors. I guess `>` is implemented as `<` with the arguments swapped.
> 

Thanks, that explanation makes sense.

> > Anyway, how to handle this the right/robust/optimal way?
> 
> `msg-level=auto_profiles=status`
> 

Not sure if I get this..
Doesn't this just set the verbosity level to `status` for the module `auto_profiles`?
What is the benefit here?

> > get("property-name", default_value) avoids this issue, but I don't think this is really straightforward to use. For example, what is a reasonable default value? 0? 999999? Depending if you want to be above or below?
> 
> You can use 0 and `math.huge` (infinity).
> 

Ah, okay. Is this "faster" than checking for the availability of a property?

> > I don't really know Lua, but I've seen expr_a ~= nil in use before, is this the correct way to do this?
> 
> That checks if a property is available. You can use any way you want.
> 

Nice, I think I get it now..
So, for example, simply checking the availability of `container_fps`:
```
profile-cond=container_fps
```
is equivalent to
```
profile-cond=container_fps ~= nil
```
?

> > Or even a simpler way to check the availability of a value?
> 
> `profile-cond=container_fps and container_fps > 59` is shorter. Note that in Lua only `nil` and `false` are falsy, and 0 is truthy.
> 

Thanks a lot @guidocella , that is what I'm using now.
But why are you suggesting this, instead of going with the "recommendation" from the manual and using
```
profile-cond=p.container_fps and p.container_fps > 59
```

I mean, that is basically what your first answer in your reply is about, but is there any benefit in not using `p.property_name`? Is it faster without?

> > How to use a property like 'video-params/average-bpp' with p.property_name?
> > p['video-params/average-bpp']?
> > Or is this not actually functionally equivalent?
> > Therefore we have to use get('video-params/average-bpp')?
> 
> `video_params['average-bpp']`, `p['video-params/average-bpp']` and `get('video-params/average-bpp')` are all equivalent.

Good to know!
But, for example, `p.'video-params/average-bpp'` would be invalid Lua syntax?

**Comment by guidocella** [comment]
> Does this only apply to `auto_profiles.lua`? Can't any custom script export something like `pause()`, for example?

Scripts should not export identifiers to the global namespace, and even if they did, you don't normally require modules from `profile-cond`.

> Not sure if I get this.. Doesn't this just set the verbosity level to `status` for the module `auto_profiles`? What is the benefit here?

Not logging errors in `profile-cond` even in verbose mode, instead of making your conditions more verbose.

> Ah, okay. Is this "faster" than checking for the availability of a property?

They are equivalent.

> Nice, I think I get it now.. So, for example, simply checking the availability of `container_fps`:
> 
> ```
> profile-cond=container_fps
> ```
> 
> is equivalent to
> 
> ```
> profile-cond=container_fps ~= nil
> ```
> 
> ?

Yes, they would only differ if `container-fps` was `false`, which it can't be.

> Thanks a lot @guidocella , that is what I'm using now. But why are you suggesting this, instead of going with the "recommendation" from the manual and using
> 
> ```
> profile-cond=p.container_fps and p.container_fps > 59
> ```
> 
> I mean, that is basically what your first answer in your reply is about, but is there any benefit in not using `p.property_name`? Is it faster without?

Because it's shorter, other than the number of characters they are equivalent.

> Good to know! But, for example, `p.'video-params/average-bpp'` would be invalid Lua syntax?

`foo.name` is syntactic sugar for `foo['name']`, but only works when `name` contains only letters, numbers and _, like in Javascript.

**Comment by guidocella** [comment]
Actually that warning in the docs is even more stupid than I thought, because you can define a `local function pause` in `auto_profiles.lua` just fine and it will not be available to profile conditions executed with `load` unless you intentionally omit the `local`. You can see that only `p` and `get` are defined without `local` in that script.

**Comment by Hrxn** [comment]
Thanks again @guidocella , that has been very helpful.

The only thing I still don't get is why using `msg-level=auto_profiles=status` would in any way be considered better or robust.
What do you gain by doing this?
You won't see those (non-critical) profile condition errors, but isn't it better to see them and fix the profile condition expression?

Any way, I think all questions have been answered, so I'm closing this now.

**Comment by guidocella** [comment]
Because conditional profiles are designed to let conditions error and be treated like `false` so you can write shorter conditions, otherwise the errors wouldn't be logged only in verbose mode.

**Comment by Hrxn** [comment]
Fair enough.
But there's no performance difference, even if miniscule?

**Comment by guidocella** [comment]
Whatever difference there may be is meaningless compared to playing a video, especially for a property that changes once per file like `container-fps`.
