### ISSUE TITLE
Is it possible for the mpv player with autoload.lua to wait for some seconds after finishing a video, and before playing the next video?

### ISSUE THREAD

**Issue by Potat0Servers** [mpv-player/mpv#12704]
Or if this function is already usable but I simply didnt figure out how to turn it on

**Comment by Dudemanguy** [comment]
autoload doesn't have such functionality. Instead of adding something specific like this to it, it would make more sense to just make your own script that does a sleep or whatever after a file ends.

**Comment by stax76** [comment]
Why such a behavior?

There is a related, very useful option [keep-open](https://mpv.io/manual/master/#options-keep-open), which can be scripted to enable it only for certain folders (I can post code on request).

**Comment by Potat0Servers** [comment]
> Why such a behavior?
> 
> There is a related, very useful option [keep-open](https://mpv.io/manual/master/#options-keep-open), which can be scripted to enable it only for certain folders (I can post code on request).

Thanks a lot! That was excatly the function I was looking for, the keep-open = always
