### ISSUE TITLE
Video Lags or Gets Stuck When Scrolling Forward

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#1270]
Hi,

These are my specs;

```
Slackware 14.1 x86_64
Openbox 3.5.2
SpaceFM 0.9.4
xorg-server-1.14.3
compton (latest git)
Geforce GTX660M
nvidia-driver-340.58
mpv 0.6.2
```
My ~/.mpv/conf
```
# Write your default config options here!

##################
# video settings #
##################

# Specify default video driver (see --vo=help for a list).
#vo=opengl-hq:lscale=spline36 #(spline36 upscaling filter)
vo=opengl-hq
#vo=vdpau

# hardware decoding - frees up the cpu by decoding h264 and vc1 in the graphics
# card instead of the cpu
hwdec=vdpau

# Start in fullscreen mode by default.
#fs=yes

# force starting with centered window
#geometry=50%x50%
geometry=50%x50%+50%+50% #(Use if DE/WM doesn't allow all windows to center)

# don't allow a new window to have a size larger than 50% of the screen size
#autofit-larger=50%x50%

# Disable the On Screen Controller (OSC).
#osc=no

# Keep the player window on top of all other windows.
#ontop=yes


##################
# audio settings #
##################

# Specify default audio driver (see --ao=help for a list).
ao=alsa

# Disable softvol usage, and always use the system mixer if available.
#softvol=no

# Enable the same volume level for each video
volume=10
```

I noticed on various video formats, I can't say I'm noticing this on any particular one, mp4, mkv, avi...
But I get the feeling it's on higher defintion videos, 720p/1080p...

When I click on a video in SpaceFM and it opens up and plays, sometimes I'll use my mousewheel to scroll forward through a video, I've noticed this happening, either scrolling slow, or fast, the video will not keep up with me scrolling forward, meaning I'll scroll it pretty fast forward and I watch the video lag, and then it catchs up, or it will just stop forwarding and lock up. Eventually if I just sit and wait a few seconds I can start scrolling forward on a video again. Sometimes it just locks up and won't let me and I have to kill mpv.

**Comment by moulei** [comment]
Tired testing again with gdb, playing with some videos, so far good, can't get this to reproduce again, just wanted to let you know...

Keep you posted if it happens again...

**Comment by rrooij** [comment]
It seems like the issue is solved, since the user couldn't reproduce it again since Feb 8.
