### ISSUE TITLE
MPV is not printing its console text on the CMD window it was launched from

### ISSUE THREAD

**Issue by RalfReddings** [mpv-player/mpv#12715]
This used to work before but now for some reason it does not. I tried deleting all my config files to see if some preference was turning of console output, I also copied just the `mpv.exe` to another folder and tried running it. It did not work. 

In all cases, when I open a file with mpv `mpv.exe vid.mp4` no console output is shown at all:
This reddit user, [How to actually show the terminal/console?](https://old.reddit.com/r/mpv/comments/e760qs/how_to_actually_show_the_terminalconsole/) was dealing with a similar issue, they did not seem to solve it though.
Here is a screenshot of my screen:
![|500](https://i.imgur.com/GzpV5XZ.png)

What could be causing this?

**Comment by christoph-heinrich** [comment]
I'm not a windows user, but I think there should also be an executable with a different extension (mpv.com?) that is meant for execution from the command line.

**Comment by Dudemanguy** [comment]
It's a windows thing. You have to use mpv.com if you want console output.

**Comment by RalfReddings** [comment]
@Dudemanguy  That did, thank you

**Comment by zhongfly** [comment]
Just run `mpv xx.mp4`, no need to add extension.
Windows will use `mpv.com` if exist.
