### ISSUE TITLE
Setting up a MPV environment for developing scripts?

### ISSUE THREAD

**Issue by RalfReddings** [mpv-player/mpv#12724]
I am delving into writing scripts for MPV. 

I am struggling with isolating my actual every day MPV executable (and its `/appdata/mpv` files) from an MPV that that I want to use strictly for developing and testing scripts.

    
    c:\users\Ralf\Documents\MPV\Mpv.exe
    c:\users\Ralf\Documents\MPV-Dev\Mpv.exe
    

For example currently both the of the above MPV executables load script files from `/appdata/mpv/scripts`. Is it possible to get `.\MPV-Dev\Mpv.exe` to read scripts from a folder like:
    
    c:\users\Ralf\Documents\MPV-Dev\scripts
    

or just get it to all together to look at another folder in place of  `/appdata/mpv`.

Currently I cant freely edit the files at `/appdata/mpv` as I would like to, as my main MPV copy is relying on it

Any help would be greatly appreciated!

**Comment by guidocella** [comment]
https://mpv.io/manual/master/#options-config-dir

**Comment by llyyr** [comment]
You can use `--script(s)` and `--script-opts` as well if you don't want to use a completely different config directory. https://mpv.io/manual/master/#options-scripts

**Comment by RalfReddings** [comment]
```
mpv "C:\Temp\cat.mp4" --script=C:\temp\exitFullscreen.js
```

The above invocation at the terminal (PowerShell) works for me. [**exitFullscreen**](https://mpv.io/manual/master/#id6) is just an example from the documentation.

I want to use use `--use-filedir-conf` in my main `mpv.conf` file (`/appdata/mpv)` so that I can have a dedicated `mpv.conf` file in the same directory I am opening media from:

My directory structure:
```
C:\Temp\cat.mp4
C:\Temp\exitFullscreen.js
C:\Temp\mpv.conf
```
The content of `mpv.conf` is:
```
--title=MPV-Dev
--load-scripts=no    #I thought this might help, but it makes no difference
--script=C:/Temp/exitFullscreen.js
```

But when I open `C:\Temp\cat.mp4` by double clicking, `exitFullscreen` does not work. But the MPV window is correctly titled `MPV-Dev`. Is there a reason why the script is failing to work with this set up?

**Comment by guidocella** [comment]
`--scripts` has no effect at runtime (the `load-script` command must be used), and evidently when filedir conf files are loaded it is too late for the option to work. It's similar to `--sub-files` / `sub-add`, `--audio-files`/`audio-add`, `--cover-art-files`/`video-add`, though these options do work in filedir configs.

**Comment by RalfReddings** [comment]
@guidocella
I see, I took a look at  `-load-script` in the documents and I gave it a try, `mpv.conf` looks like this now:
```
--title=MPV-Dev
--load-script=C:\Temp\exitFullscreen.js
```

but when I open the `mp4` file, script still does not work. Unless I have misunderstood you. I tried `--load-script` at the terminal and nothing opens:
```
MPV "C:\Temp\Sierra.mp4" --script=C:\temp\exitFullscreen.js         # Works
MPV "C:\Temp\Sierra.mp4" --load-script=C:\temp\exitFullscreen.js    #Does not work. No window opens
```

**Comment by guidocella** [comment]
`load-script` is a command, not an option, you can't use it in `mpv.conf`, but only in `input.conf` / scripts / IPC.

**Comment by guidocella** [comment]
They are in different sections of the manual, and options start with `--`.

**Comment by RalfReddings** [comment]
Got it! cheers.
