### ISSUE TITLE
[RFC] Interest on DRM Prime AFBC Mode?

### ISSUE THREAD

**Issue by hbiyik** [mpv-player/mpv#12721]
AFBC mode is a lossless compressed format of any picture plane format. It generally is necessary for embedded devices, where the resolution is very big and the plane size is quite big ie: 10bit or 16bit.

Most of the arm based SOCs have somehow support on their decoders or gpus to provide AFBC compressed picture fromats, otherwise when 8k hdr 60fps pictures are transfferred over DDR, the bandwidth is literally dead.

I am playing with rockchip device (rk3588) and i think i can already output P010 drm frames, but i think it would be better to do this with AFBC compressed frames.

To my investigation, i think AFBC is provided through DRM modifiers in drmprime, and EGL already supports this. If i can achieve AFBC with mpv drmprime, would you be interested in this functionality to merge?

**Comment by philipl** [comment]
This would only be possible if the frame could still be expressed as an exported vaapi surface with separate layers. We do not supported importing composed layers with OpenGL and we only support OpenGL on currently tested rockchip devices (it's also unclear if panvk supports importing composed layers). But if it can export the frames with separate layers, mpv should just work, once you convince it to use the format (presumably a decoder setting you'd need to fiddle with in ffmpeg).

**Comment by hbiyik** [comment]
ah i see, dmabuf is already parsing the [format_modifier](https://github.com/hbiyik/FFmpeg/blob/e243e8d0010dfdaab0a9e3f9bb94dba7a2c51c69/libavutil/hwcontext_drm.h#L66C14-L66C29)  of av frame and asssigning it to EGL_DMA_BUF_PLANEn_MODIFIER_HI/LO_EXT, so mpv is transparent in that regard, i had never tested it but i think this should already works as you said. Thanks for the tips

https://github.com/mpv-player/mpv/blob/869faadc68b0dedce25527f096b3e370785ce0f3/video/out/hwdec/dmabuf_interop_gl.c#L150
