### ISSUE TITLE
Clarify `container-fps` and `container_fps`

### ISSUE THREAD

**Issue by AlifianK** [mpv-player/mpv#12759]
I tried to make a profile condition that detects if a video is more than 30 fps (I know it's not recommended, but still), I tried using `container-fps` in the property list section, but the log throws `[auto-profiles] Property 'container' was not found`. Tried `fps`, and got a warning about `container-fps-override`, but had no effect. Tried `container-fps-override` but the log throws the first error again. Finally tried `container_fps` found in the video filter section and it finally worked.

Seemed odd to me, so I used `show-text` command on the console, `show-text ${container-fps}` returned the proper number but `show-text ${container_fps}` returned error instead. My question is, is this the intended behavior or a bug?

**Comment by Dudemanguy** [comment]
```
You cannot reference properties with - this way since that would denote a subtraction, 
but if the variable name contains any _ characters, they are turned into -. 
For example, playback_time would return the property playback-time.
```

It's intended and works like this for any property.

**Comment by AlifianK** [comment]
Thank you
