### ISSUE TITLE
Persistent volume

### ISSUE THREAD

**Issue by Bellavene** [mpv-player/mpv#12761]
Hello! Firstly, thank you all. It is the best universal player.
But it lacks one simple thing, let the volume stay intact, in a playlist at least. Or `volume=previous` would be great.
It is so annoying, tried every lua script, does not work right for me.

macos 14

**Comment by po5** [comment]
You want a user script that implements this functionality, such as [mpv-persist-properties](https://github.com/d87/mpv-persist-properties), [remember-props](https://github.com/zenwarr/mpv-config/blob/master/scripts/remember-props.lua), or my very own [celebi](https://github.com/po5/celebi) (you can guess which one I recommend :^)).  

> tried every lua script, does not work right for me.

Have you successfully installed other lua scripts before? Are you following the instruction for these? They're actively used by hundreds of people so they definitely do work.

**Comment by monarc99** [comment]
Or he means something like audio normalization, so that songs/videos that have different volume levels are played at similar levels.

**Comment by Bellavene** [comment]
> You want a user script that implements this functionality, such as [mpv-persist-properties](https://github.com/d87/mpv-persist-properties), [remember-props](https://github.com/zenwarr/mpv-config/blob/master/scripts/remember-props.lua), or my very own [celebi](https://github.com/po5/celebi) (you can guess which one I recommend :^)).
> 
> > tried every lua script, does not work right for me.
> 
> Have you successfully installed other lua scripts before? Are you following the instruction for these? They're actively used by hundreds of people so they definitely do work.

Thank you! By some strange accident, I did not find any mention of yours. It works : ) Both other did not.
One thing bothers me, seeking on videos now is a bit slower, not critical, but you can feel it. I don't know how it could be correlated, but that's what I have immediately seen.

**Comment by Bellavene** [comment]
Excuse me, but celebi script only writes saved volume change between app shutdown and launch. It does not care for changes in a playlist, the volume still resets.

**Comment by guidocella** [comment]
`--reset-on-next-file=volume`

**Comment by Bellavene** [comment]
Thank you, I removed it and voilà.
