### ISSUE TITLE
Is it possible for MPV to gamut map Bt.2020 to dci-p3 but keep it inside a BT.2020 container?

### ISSUE THREAD

**Issue by danbezerra** [mpv-player/mpv#12777]
Here is my scenario: I tone map my UHD rips to SDR BT.2020 as this is the best outcome for my JVC projector, using target-prim=bt.2020 and target-trc = gamma2.4. (also using spline tone mapping).

However, I know my projector only covers the P3 color space, which is smaller than BT.2020. The projector was calibrated to BT.2020 and as far as I know, if I set the target-prim=dci-p3 I would have color related issues unless the projector is properly calibrated to P3.

Question - can MPV gamut map BT.2020 to DCI-P3, but send the information still inside a BT.2020 container? This would allow the gamut compression of any color that falls outside the DCI-P3 triangle while still sending the information in the container expected by the projector.

Thanks

**Comment by danbezerra** [comment]
It may take a couple of days for me to have access to my projector again, but I will give you feedback by mid week. In the meantime, a question just came to my mind: Target-prim=dci-p3 --> Is this the "real" DCI-P3 or is it P3 with D6500 white point (consumer P3, P3-D65)?

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/hdr-toys/blob/master/gamut-mapping/clip.glsl

Can you also test this？Just add this into conf as normal shaders, no profile, no other shaders in hdr-toys. And modify two defines to `FROM P3D65 TO BT2020`

**Comment by danbezerra** [comment]
Another discovery - I just learned that tone mapping to SDR Bt.2020 pushes more of the image to the outside of P3 gamut. Comparing a passthrough HDR with SDR BT.2020 tonemaping (splice), the amount of out of gamut warning increases considerably. So the movie I was using to check is inside P3 when using passthrough, but bleeds once tone mapping is applied.

I also compared that with MadVR tonemapping and the same thing happens - MadVR with tone mapping to SDR BT.2020 had a lot more outside of P3 vs MadVR in HDR passthrough mode.

FYI : For MadVR I used the following shader attached to MPC-HC. It's similar to "warn" mode, and allowed me to compare the results.

https://github.com/aron7awol/gamutShader

So as of now, I will say that the code is working as intended. It was just surprising to me that tone mapping will push more content outside of P3.

**Comment by haasn** [comment]
@danbezerra how are you testing? on my end, with

`--target-trc=gamma2.4 --target-prim=bt.2020 --gamut-mapping-mode=warn --tone-mapping-visualize` +

### `--target-gamut=bt.709`
![mpv-shot0001](https://github.com/mpv-player/mpv/assets/1149047/378d430a-8484-4fd2-b917-bf8178c29f4b)

### `--target-gamut=display-p3`
![mpv-shot0002](https://github.com/mpv-player/mpv/assets/1149047/106f765b-b247-4a43-9fe2-03158ba34fd7)

It expands to the larger gamut as expected.

**Comment by haasn** [comment]
> So as of now, I will say that the code is working as intended. It was just surprising to me that tone mapping will push more content outside of P3.

Ah, okay. Good to hear, then. I suppose I'll polish up the above commit and add it as an option $tomorrow (tm)

**Comment by danbezerra** [comment]
Just for curiosity - do you understand why tone mapping is pushing more content outside of P3?

**Comment by danbezerra** [comment]
> https://github.com/natural-harmonia-gropius/hdr-toys/blob/master/gamut-mapping/clip.glsl
> 
> Can you also test this？Just add this into conf as normal shaders, no profile, no other shaders in hdr-toys. And modify two defines to `FROM P3D65 TO BT2020`
> 
> Hopefully it won't be any different from patch in above.

Not sure it's working as intended. If I leave the following lines on my config:
target-trc=gamma2.4
target-prim=bt.2020
gamut-mapping-mode=warn

Then nothing is reported as outside of the gamut (via the warn line). If I remove the target-prim, then a lot more than MPV native solution is reported as out of P3.  See the screenshots attached.

Perhaps gamut-mapping-mode-warn doesn't work with Shaders? BTW, I don't have any other HDRToys scripts installed.

![mpv native](https://github.com/mpv-player/mpv/assets/17623925/a6623b69-a22d-49cc-bf72-96ff5728f4cb)
![HDRToys](https://github.com/mpv-player/mpv/assets/17623925/4401140f-379f-44c7-b02a-d5d2ae6fb23a)

**Comment by haasn** [comment]
> Just for curiosity - do you understand why tone mapping is pushing more content outside of P3?

I'm not 100% sure, but reducing luminance *generally* pushes content out-of-gamut. We also reduce the chromaticity of the input when tone-mapping, but we use a rough approximation of the native (BT.2020) gamut hull for this. I'd probably have to look at the problem visually to really know what's going on..

**Comment by movieperson** [comment]
I may be having a senior moment, but I can't for the life of me figure out where to find the windows 64 bit mpv.exe that actually contains this fix so I can test it.

Any help would be appreciated.

**Comment by danbezerra** [comment]
You have to build it yourself as the fix was not checked-in yet.

**Comment by kasper93** [comment]
> I may be having a senior moment, but I can't for the life of me figure out where to find the windows 64 bit mpv.exe that actually contains this fix so I can test it.
> 
> Any help would be appreciated.

Builds can be found in PR comment.
https://github.com/mpv-player/mpv/pull/12786#issuecomment-1787943731

**Comment by natural-harmonia-gropius** [comment]
> Not sure it's working as intended. If I leave the following lines on my config: target-trc=gamma2.4 target-prim=bt.2020 gamut-mapping-mode=warn
> 
> Then nothing is reported as outside of the gamut (via the warn line). If I remove the target-prim (since I specified the "From" and "To" in your shader), then a lot more than MPV native solution is reported as out of P3. See the screenshots attached.

Use `target-prim=display-p3`, and compare result with eyes 🫠. Does it looks right?

`gamut-mapping-mode=warn` doing things before hdr-toys so it doesn't work here.
