### ISSUE TITLE
Rotation of movies with metadata orientation set is not possible anymore when lavfi filter is set

### ISSUE THREAD

**Issue by KaFu74** [mpv-player/mpv#12771]
Hello Team,

### Important Information
I'm running an up to date Win10-64bit
Source for mpv exes is https://sourceforge.net/projects/mpv-player-windows/files/64bit/

No issue with mpv-x86_64-20231001-git-e969072
Issue came up with mpv-x86_64-20231008-git-78719c1

### Reproduction steps
A movie with metadata orientation set is required to reproduce

"z_input.conf" contains only one line:
r cycle-values video-rotate "90" "180" "270" "0"

With
"mpv\mpv.exe --no-config --input-conf=z_input.conf movie.mov"
rotation of movie is possible when pressing "r" in both mpv versions

With
"mpv\mpv.exe --no-config --vf-add=lavfi=[eq=1:0:1:1,hue=h=0] --input-conf=z_input.conf movie.mov"
rotation of movie works with first version mentioned above, but not anymore with second version.

Also in a different setting I've added the lavfi filter later with a lua script on pause, then the rotation is removed (set to metadata orientation) using the later version too, but reapplied to the manually selected value when I deleted the lavfi filter.

### Expected behavior
Rotation possible with lavfi filter set

### Actual behavior
Rotation not possible anymore with lavfi filter set

### Log file
[z_log_output.txt](https://github.com/mpv-player/mpv/files/13198000/z_log_output.txt)

Test mp4 with 90 degree rotation set in metadata
https://github.com/mpv-player/mpv/assets/149301721/d29cb815-e237-41ab-b9ed-588a6d7b4ea5

**Comment by KaFu74** [comment]
Test mp4 with 90 degree rotation set in metadata
https://github.com/mpv-player/mpv/assets/149301721/d29cb815-e237-41ab-b9ed-588a6d7b4ea5

**Comment by kasper93** [comment]
> No issue with mpv-x86_64-20231001-git-e969072

Are you sure about that? I tested with v0.36.0 and it does not work there too. There was no changes w.r.t rotation, so probably some other factors affected your testing. I will take a look what can we do to preserve rotation when filtering.

**Comment by KaFu74** [comment]
Thanks for taking a look. Just retested and re-confirmed, rotation works with first mentioned version but not with second. I guess it's not directly mpv related but more ffmpeg related? Maybe there's even a team working on lavfi directly?

**Comment by kasper93** [comment]
Will be fixed by #12789.

**Comment by KaFu74** [comment]
Much appreciated, thanks to both of you :)!

**Comment by KaFu74** [comment]
Hello Team,

a follow-up. Somehow you solution consumes the initial orientation value stored in "track-list/0/demux-rotation". This property is now always zero, and the rotation value is an absolute. Before that the rotation value always had been relative to the metadata orientation.

**Reproducer**

mpv\mpv.exe --no-config --input-conf=z_Rotate_Test_input.conf --script=z_Rotate_Test.lua test.mp4

**z_Rotate_Test.lua**
r cycle-values video-rotate "90" "180" "270" "0"

**z_Rotate_Test.lua**
function show_rotation()
	local message = "1"
	local mpv_rotation_angel = mp.get_property_number('video-rotate')
	message = "Rotation= " .. mpv_rotation_angel
	local mpv_rotation_angel_initial = mp.get_property("track-list/0/demux-rotation")
	if (mpv_rotation_angel_initial == nil or mpv_rotation_angel_initial == "nil property unavailable") then
		mpv_rotation_angel_initial = 0
	end
	message = message .. "\nRotation-Initial= " .. mpv_rotation_angel_initial
	mp.osd_message(message, 5)
end

mp.observe_property("video-rotate", "number", show_rotation)



Test mp4 with 90 degree rotation set in metadata
https://github.com/mpv-player/mpv/assets/149301721/d29cb815-e237-41ab-b9ed-588a6d7b4ea5
