### ISSUE TITLE
Controls to sync two videos together

### ISSUE THREAD

**Issue by vinraghav** [mpv-player/mpv#12787]
Mpv 0.33.0 
Ubuntu 20.04 

I want to watch two videos side by side perfectly synced. So when I pause/play one video, it should happen to the other one too. Similarly, when I save exit (shift q), that should save the exit position of both the videos simultaneuosly. Nomally by doing it manually by switching to each window individually one by one creates sync issues. Sort of like adding subtitles to a video work. Thanks.

**Comment by llyyr** [comment]
`mpv [video 1] --external-file=[video 2] --lavfi-complex='[vid1] [vid2] hstack [vo]'`

**Comment by vinraghav** [comment]
> `mpv [video 1] --external-file=[video 2] --lavfi-complex='[vid1] [vid2] hstack [vo]'`

Hello, I would like the audio controls seprate. Like control both the videos audios separately.

**Comment by vinraghav** [comment]
> `mpv [video 1] --external-file=[video 2] --lavfi-complex='[vid1] [vid2] hstack [vo]'`

@llyyr Running this command, only plays "video 1".

**Comment by llyyr** [comment]
Impossible to help without logs

**Comment by vinraghav** [comment]
> --log-file=mpvsucks.log

@llyyr 

$ mpv --log-file=mpvsucks.log
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Thu Nov 26 06:59:44 UTC 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-22-9208b72

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name

**Comment by vinraghav** [comment]
> Impossible to help without logs, use `--log-file=mpvsucks.log` 

@llyyr Here you go. Let me know if this is what you asked for. 
[mpvlogs.log](https://github.com/mpv-player/mpv/files/13231258/mpvlogs.log)

**Comment by llyyr** [comment]
You have to use the command above for the log to contain any information related to it.

`mpv [video 1] --external-file=[video 2] --lavfi-complex='[vid1] [vid2] hstack [vo]' --log-file=mpv.log`

**Comment by Dudemanguy** [comment]
No follow up but `lavfi-complex` accomplishes this as stated.

**Comment by milahu** [comment]
to stack videos with different resolutions see https://github.com/mpv-player/mpv/issues/3854#issuecomment-571424357
