### ISSUE TITLE
mpv --no-video <youtube-playlist> has no keybord control in terminal anymore

### ISSUE THREAD

**Issue by Baerbeisser** [mpv-player/mpv#12794]
### Important Information

Provide following Information:
- v0.36.0-712-gb6703873cf
- Arch current
- aur/mpv-git

### Reproduction steps

> Try to reproduce your issue with --no-config first. If it isn't reproducible
> with --no-config try to first find out which option or script causes your issue.

I did, even deleted the .config/mpv fodler temporarily.

> Describe the reproduction steps as precise as possible. It's very likely that
> the bug you experience wasn't reproduced by the developer because the workflow
> differs from your own.

I usually use mpv as audio player on folder with ogg files via `mpv --shuffle *.ogg`.
Sometimes, when i want new songs, i do mpv --no-video --shuffle \<youtube playlist URL\>. Last time was a few months ago, so i don't know, when it happened. Now, when i do that (playlist), mpv goes in background process mode, like if it would play an actual video and i have no keyboard control, i have to close the terminal to stop mpv playing.
Playing an audio file (ogg,flac,mp3) and terminal control works as expected. Same while playing a video with `--no-video`.

I use `yt-dlp` as Youtube downloader.

I guess it fetches the video+audio strem instead of only the audio stream? Though it would still have to act on `--no-video` then.
A race condition?

### Expected behavior
Keyboard control in terminal

### Actual behavior
mpv goes in background, no control

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/13241066/output.txt)

**Comment by Dudemanguy** [comment]
Not sure what's actually happening on your machine, but mpv doesn't fork itself or anything like that. I can't reproduce.

**Comment by paulguy** [comment]
Are you by any chance pasting a link with an & in it?

**Comment by Baerbeisser** [comment]
> Are you by any chance pasting a link with an & in it?

I forgot to quote the URL! 🤦
Sorry for taking your time guys. Hope you get a laugh out of this.

**Comment by Baerbeisser** [comment]
> Are you by any chance pasting a link with an & in it?

I forgot to quote the URL! 🤦
Sorry for taking your time guys. Hope you get a laugh out of this.

**Comment by guidocella** [comment]
If you use zsh you should consider using the feature to automatically quote pasted urls

```zsh
autoload -U bracketed-paste-url-magic
zle -N bracketed-paste bracketed-paste-url-magic
```
