### ISSUE TITLE
`vf remove` will cause the mpv to freeze

### ISSUE THREAD

**Issue by verygoodlee** [mpv-player/mpv#12791]
### Important Information

- mpv version [shinchiro's build 20231101](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20231101)
- Windows Version `Win11 23H2`

### Reproduction steps
vf append with label, then remove it by label
for example `input.conf` 
```
a vf append @test:vapoursynth="~~/vs/test.vpy"
b vf remove @test
```

`vf append` works properly，`vf remove` will cause the mpv to freeze，
then you can only use the taskmanager to kill the mpv process

on [20231030](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20231030) before version do not have this problem

**Comment by fidodido48** [comment]
Got a similiar issue using vf vulkan_scale/vaapi_scale erroring out at EOF and basically freezes mpv until fast-forward is pressed (arrow up/down). Just to be clear - the vf works good during playback, but freezes advancement/playlist_continuation/mpv_close at EOF.

Latest Arch upgraded yesterday.
```
mpv v0.41.0 Copyright © 2000-2025 mpv/MPlayer/mplayer2 projects
built on Feb 11 2026 22:07:06
libplacebo version: v7.360.1
FFmpeg version: n8.0.1 (runtime n8.1.2)
```
