### ISSUE TITLE
Add sub-text-all property

### ISSUE THREAD

**Issue by karelrooted** [mpv-player/mpv#12810]
Currently there has property sub-text https://mpv.io/manual/master/#command-interface-sub-text to observe the text of the current sub. It would be nice to have a similar property for the entire subtitle, possibly called sub-text-all

the usage of this feature may be to get the entire embedded subtitle and then translate it and add a translated subtitle track on the fly

### Expected behavior of the wanted feature

add a sub-text-all property to return the current entire subtitle as text

**Comment by po5** [comment]
Not possible for many files to get all subtitle lines without parsing through the entire file, as the data can be scattered across the file near each video/audio data chunk. You'll notice that ffmpeg can extract some subtitles near instantly and others will take a while.

**Comment by llyyr** [comment]
> the usage of this feature may be get the entire embedded subtitle and then translate it and add a translated subtitle track

This is completely out of scope for mpv, you're looking to use something like Aegisub for `.ass` files, and if it's not an `.ass` file then you should convert it with ffmpeg.

**Comment by karelrooted** [comment]
> > the usage of this feature may be get the entire embedded subtitle and then translate it and add a translated subtitle track
> 
> This is completely out of scope for mpv, you're looking to use something like Aegisub for `.ass` files, and if it's not an `.ass` file then you should convert it with ffmpeg.

when try to add bilingual subtitle track on the fly with embedded subtitle, currently have to use ffmpeg to get the entire subtitle, it seems unoptimized when mpv is already loading the file

**Comment by Dudemanguy** [comment]
mpv has the file loaded, but it won't read the entire thing at once of course. It only reads what is necessary for playback. For mpv to do what you want, it would have to read the entire file from beginning to end again which is no different from just using ffmpeg to read the whole thing.

**Comment by karelrooted** [comment]
> mpv has the file loaded, but it won't read the entire thing at once of course. It only reads what is necessary for playback. For mpv to do what you want, it would have to read the entire file from beginning to end again which is no different from just using ffmpeg to read the whole thing.
 
copy that

**Comment by christoph-heinrich** [comment]
What if the property only returns the subtitle lines that mpv already knows about?
That would make [my script](https://github.com/christoph-heinrich/mpv-subtitle-lines) much simpler, faster and more reliable.

**Comment by Dudemanguy** [comment]
mpv only holds onto a couple of subtitle packets at a time. Anything older gets discarded, so I don't think there's any way for this other than reading through all the packets again which I'm not sure we want to do.

**Comment by christoph-heinrich** [comment]
Well we could just not discard them :upside_down_face:

**Comment by Lypheo** [comment]
> Anything older gets discarded
Where? Afaict all events are buffered unless the ASS_Track is flushed which only happens when we reset the sub track.

**Comment by Dudemanguy** [comment]
I thought libass internally discarded stuff after a while. But sure I could be wrong. Feel free to send a patch if it's not so bad.

**Comment by karelrooted** [comment]
I try to add a sub-text-all property,  the commit is at https://github.com/karelrooted/mpv/commit/3cea4a9dde2a54327beddb19c0626a090f495cab. 

I'm not a experience c coder, so the code may need some clean up to conform to mpv's code standard

By the way,  while trying to use the new property to implement bilingual sub on the fly , I found out this approach did not work on my  scenario， loaded current sub partial content， trasnlate it， load new bilingual sub(only contain current partial sub)， and then the current sub track is changing to new biliginual sub , it does not contain the whole subtext, so the process didn't work, have to keep using FFmpeg to load the subtitle,  any other idea to avoid load the same file twice ?

It's not just about saving the celluar data usage, I'm using a clouddisk which limit the concurrent access to the same file, when loading the file twice, sometimes lag happens
