### ISSUE TITLE
`mpv-x86_64-v3-20231106-git-84de84b.7z` build doesn't work

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12818]
(Created the same issue on [mpv-winbuild-cmake](https://github.com/shinchiro/mpv-winbuild-cmake/issues/500) in case this is not a mpv issue)

`mpv-x86_64-v3-20231105-git-7480efa.7z` = No issues.
`mpv-x86_64-v3-20231106-git-84de84b.7z`  = `mpv.exe` have issues.
I tried to debug the issue by using the `log-file` command but mpv doesn't seem to create the file, so I can't debug it.
Weirdly enough when I open Task Manager I do see `mpv.exe`.

It's probably not an issue with `mpv-packaging` because nothing was changed [today](https://github.com/shinchiro/mpv-packaging/pulse/daily).
So my guess it's either [mpv daily changes](https://github.com/mpv-player/mpv/pulse/daily) or it's [mpv-winbuild-cmake daily changes](https://github.com/shinchiro/mpv-winbuild-cmake/pulse/daily).

(Yes, I know I `ignored-issue-template` but I can't provide logs because of this issue)

**Comment by Dudemanguy** [comment]
Do any of today's build artifacts work for you?

* [84de84b](https://github.com/mpv-player/mpv/suites/17921151514/artifacts/1029670141)
* [076be24](https://github.com/mpv-player/mpv/suites/17920983225/artifacts/1029652905)
* [062104d](https://github.com/mpv-player/mpv/suites/17919873595/artifacts/1029573645)
* [6f8d98f8](https://github.com/mpv-player/mpv/suites/17912145217/artifacts/1028925770)

**Comment by Hrxn** [comment]
Can confirm for
- https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20231106
- https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-11-05-84de84b

So https://github.com/mpv-player/mpv/commit/84de84b8aa6023efb3f8fac368d802359657268c

Same on my machine..
Running `mpv` simply does not terminate. Seems like stuck in an infinite loop..

NB; For those not really aware how this works on Windows:
`mpv` actually runs `mpv.com` which then runs `mpv.exe` basically..
But I haven't seen any changes related to `mpv.com` in a long time, so I guess it's the other artifact that's bad.

**Comment by Dudemanguy** [comment]
Are you positive it's actually 84de84b8aa? I would have assumed the windows threading stuff (so 076be248532e3fa0b261addb9c6dc93563d02644 as I linked above).

**Comment by zhongfly** [comment]
@Hrxn It is recommended to use the link file provided by Dudemanguy for testing, there was also an update to mpv-winbuild-cmake 13 hours ago and we need to rule it out.

**Comment by Hrxn** [comment]
I am positive..

But by looking at https://github.com/mpv-player/mpv/commits/master/
Seems here 
84de84b8aa6023efb3f8fac368d802359657268c is the newest commit
076be248532e3fa0b261addb9c6dc93563d02644 is seven commits down from the latest

So the automatic builds from @zhongfly and @shinchiro should include this obviously.

I'm afraid, but it might acutally be the windows threading stuff 😄

**Comment by Hrxn** [comment]
FFS, I cannot download the automatic build artifacts linked by @Dudemanguy above with curl or pwsh.

Only in the browser, apparently, but then they all have the same "wrong" filename, which is annoying.

**Comment by Hrxn** [comment]
Ah, well, nevermind.

Dudemanguy's links above all get me zipfiles with a contained zipfile, and these have the (shortended) SHA commit ID, so it's okay.

**Comment by Hrxn** [comment]
Okay, just tested
https://github.com/mpv-player/mpv/suites/17921151514/artifacts/1029670141

And it does **NOT** show the behaviour mentioned above.
So the windows threading stuff may actually be fine, and the culprit is the cmake stuff that @zhongfly mentioned

**Comment by sevz17** [comment]
Hello, this sounds pretty similar to my problem.
I'm using Gentoo, the problem does not happen when I build mpv directly from git, it only happens when I install it from portage

The last working commit is 3a8b107f6216b38a151d5ca1e9d4f2727e3418f5
 
Here is the output of strace using 174df99ffa53f1091589eaa4fa0c16cdd55a9326: http://0x0.st/HtQg.strace

**Comment by Dudemanguy** [comment]
Can you narrow down whatever compiler flag you're using that makes the difference?

**Comment by sevz17** [comment]
I used the same meson arguments and {C,LD}FLAGS

**Comment by Hrxn** [comment]
To be honest @sevz17, I don't think this is the same issue.

Playback is *working* for me here (Windows 10 22H2 19045.3636)

```
PS C:\> mpv -V
mpv 84de84b Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Nov  5 2023 18:05:11
libplacebo version: v7.341.0
FFmpeg version: git-2023-11-05-44a0148
FFmpeg library versions:
   libavutil       58.31.100
   libavcodec      60.32.102
   libavformat     60.17.100
   libswscale      7.6.100
   libavfilter     9.13.100
   libswresample   4.13.100

PS C:\>
```

This is 84de84b which should be the latest commit.

Only one issue here:
Terminal gets spammed with this
```
[vo/gpu-next/libplacebo] libplacebo compiled without LittleCMS 2 support!
[vo/gpu-next/libplacebo] libplacebo compiled without LittleCMS 2 support!
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu-next] 1920x1080 yuv420p
[vo/gpu-next/libplacebo] libplacebo compiled without LittleCMS 2 support!
[vo/gpu-next/libplacebo] libplacebo compiled without LittleCMS 2 support!
AV: 00:00:00 / 00:24:26 (0%) A-V:  0.000
[vo/gpu-next/libplacebo] libplacebo compiled without LittleCMS 2 support!
AV: 00:00:00 / 00:24:26 (0%) A-V:  0.006
[vo/gpu-next/libplacebo] libplacebo compiled without LittleCMS 2 support!
AV: 00:00:00 / 00:24:26 (0%) A-V:  0.005
[vo/gpu-next/libplacebo] libplacebo compiled without LittleCMS 2 support!
AV: 00:00:00 / 00:24:26 (0%) A-V:  0.005
[vo/gpu-next/libplacebo] libplacebo compiled without LittleCMS 2 support!
```

**Comment by Dudemanguy** [comment]
>EDIT: I just removed the pkg-config paths and the --native-file args that portage add to the meson invocation

That's could be a big difference..., linking to different libraries, etc. who knows what's going on here. I'm not sure whatever you're experiencing is actually the same thing.

**Comment by sevz17** [comment]
Probably, do you want me to open another issue?

**Comment by Dudemanguy** [comment]
Sure feel free to.

**Comment by kasper93** [comment]
Just so we don't wonder around to far.

The root cause of the issue is that we deadlock during init and `AcquireSRWLockExclusive()` due to recursive lock. This mutex has `MP_MUTEX_RECURSIVE` flag set, so it should never call SRW lock. And with my build and as we can see build from mpv's CI it does work correctly and calls `EnterCriticalSection()`. I've looked quickly at the file and I don't see anything obviously wrong, any stupid UB that could explain that miscompilation. I'm almost sleeping rn, so maybe I missed something...

```
ntdll.dll!NtWaitForAlertByThreadId()
ntdll.dll!RtlAcquireSRWLockExclusive()
[Inline Frame] mpv.exe!mp_mutex_lock(mp_mutex * mutex) Line 69
mpv.exe!mp_input_disable_section(input_ctx * ictx, char * name) Line 988
mpv.exe!mp_input_enable_section(input_ctx * ictx, char * name, int flags) Line 1008
mpv.exe!mp_input_init(mpv_global * global, void(*)(void *) wakeup_cb, void * wakeup_ctx) Line 1330
mpv.exe!mp_create() Line 295
```


Can you test with you fancy build bots? Would save me some time setting up everything.

``` diff
diff --git a/osdep/threads-win32.h b/osdep/threads-win32.h
index ef661aa53a..6fd0a27d66 100644
--- a/osdep/threads-win32.h
+++ b/osdep/threads-win32.h
@@ -44,7 +44,7 @@ typedef DWORD              mp_thread_id;
 
 static inline int mp_mutex_init_type_internal(mp_mutex *mutex, enum mp_mutex_type mtype)
 {
-    mutex->use_cs = mtype == MP_MUTEX_RECURSIVE;
+    mutex->use_cs = mtype == MP_MUTEX_RECURSIVE ? 1 : 0;
     if (mutex->use_cs)
         return !InitializeCriticalSectionEx(&mutex->cs, 0, 0);
     InitializeSRWLock(&mutex->srw);
```

**Comment by kasper93** [comment]
Well, shit...
