### ISSUE TITLE
[auto_profiles] using `video-out-params` properties as a condition results in severe OSC lag

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#12825]
### Important Information

Provide following Information:
- mpv version: git master
- Windows Version: Win11 22H2
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-11-06
- If known which version of mpv introduced the problem

### Reproduction steps
1. using `video-out-params` properties as a profile-cond to auto-profiles in mpv.conf, for example:
```
[test]
profile-cond=p["video-out-params/gamma"] == "bt.1886"
profile-restore=copy
target-trc=auto
````
2. Open video and play
3. Open osc for operation

### Expected behavior

The video is playing normally and the osc is also working properly

### Actual behavior

The video is playing normally without any frame drops. the osc severely lags behind.

https://github.com/mpv-player/mpv/assets/61936050/5cee326b-8930-4669-afdf-efe05083709c

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/13267484/mpv.log)

**Comment by sfan5** [comment]
Natural consequence of 84de84b8aa6023efb3f8fac368d802359657268c.

Thinking about this again it's indeed not good. mpv-android for example also observes `video-params` and will now receive useless property updates every frame. (is it possible to observe sub-properties?)

**Comment by kasper93** [comment]
We can revert this. It is not even property update, but `VOCTRL` that staggers the updates.

Probably need new event for image params changes, not all of them cause vo reconfigure, but having it on tick is not good if `VOCTRL` is involved.
