### ISSUE TITLE
Real-time multi-track volume control via lua

### ISSUE THREAD

**Issue by kickaxe60** [mpv-player/mpv#12828]
Sorry if this isn't the correct place but I've scoured the documentation and can't solve my problem. Any help would be appreciated.

I have a karaoke mp4 video that has three audio tracks embedded, one for instrumental, one for lead vocal, and one for backing vocals that I used with ffmpeg to map to different channels.  Sometimes a singer may want a little accompaniment or none at all, so I would like to be able to adjust the lead vocal accordingly. Or perhaps the instrumental and/or backing vocals need to be rolled up or down a bit...  I can play the mp4 with mpv just fine with the following command in my macbook terminal:
mpv --lavfi-complex='[aid1]volume=1[vol1];[aid2]volume=0.3[vol2];[aid3]volume=1[vol3];[vol1][vol2][vol3]amix=inputs=3:duration=first:dropout_transition=3[ao]' karaoke.mp4

So by default, this would play the mp4 with lead vocal at 30% of normal volume.  Works great however;  I would like to start with each track at volume=1 and be able to change the volume of either of the three tracks using hotkeys in a lua script.  When I hit one of the hotkeys for the desired track, it simply goes quiet and I lose all sound.  Can anyone see what's wrong with my script. I know mpv is extremely flexible as I've been able to create a pitch change lua script that works well for karaoke (if anyone wants a copy, I would be willing to share it.)  Perhaps it's not even possible?  What I'm trying to achieve is something like the Karafun player which has volume control for the three tracks but their app is a commercial one and I can't figure out what they're doing as the app coding is all encrypted.  Perhaps there is another player that will do what I'm looking for but I can't find one.  Hopefully I can make mpv do what I'm looking for.  Anyway, thanks for any help or suggestions.

This is my lua script attempt:
-- Define initial volumes for each audio track
local volumes = {
    [1] = 1.0, -- Audio track 1 instrumental
    [2] = 1.0, -- Audio track 2 lead vocal
    [3] = 1.0, -- Audio track 3 backing vocal
}

-- Function to update the volume of a specific audio track
function updateVolume(track, delta)
    if volumes[track] then
        volumes[track] = math.min(2.0, math.max(0.0, volumes[track] + delta))
        mp.set_property("volume", volumes[track], "ao-idx=" .. (track - 1))
        mp.osd_message("Audio Track " .. track .. " Volume: " .. volumes[track], 1)
    end
end

-- Register hotkeys to control audio track volumes
mp.add_key_binding("1", "adjust_volume_track1", function() updateVolume(1, 0.1) end)
mp.add_key_binding("2", "adjust_volume_track2", function() updateVolume(2, 0.1) end)
mp.add_key_binding("3", "adjust_volume_track3", function() updateVolume(3, 0.1) end)
mp.add_key_binding("Shift+1", "decrease_volume_track1", function() updateVolume(1, -0.1) end)
mp.add_key_binding("Shift+2", "decrease_volume_track2", function() updateVolume(2, -0.1) end)
mp.add_key_binding("Shift+3", "decrease_volume_track3", function() updateVolume(3, -0.1) end)

**Comment by guidocella** [comment]
`mp.set_property('lavfi-complex', '[aid1]volume=' .. volumes[1] .. '[vol1];[aid2]volume=' .. volumes[2] .. '[vol2];[aid3]volume=' .. volumes[3] .. '[vol3];[vol1][vol2][vol3]amix=inputs=3:duration=first:dropout_transition=3[ao]')`

**Comment by kickaxe60** [comment]
Hi guidocella, there is still a bit of an issue.  When I launch the mp4, it seems the first track plays at regular volume but the other 2 are muted.  If I hit key 1, 2, or 3 to change volume on either of those tracks, it then activates all tracks but at much lower volumes.  I can then adjust the volume of each track accordingly.  I would prefer that all tracks play at normal volume from the beginning...  It would be a bonus to also be able to toggle mute on either of the 3 tracks with alt-1, alt-2, or alt-3 but I can't seem to get that to work either.  Again, I appreciate your help.  Regards.

**Comment by guidocella** [comment]
Did you remove the `--lavfi-complex` CLI option? Obviously it only plays one track until you set it either on the CLI or in the script in the `file-loaded` event. The initial volumes should be whatever you set in the `volumes` variable. You can mute a track by setting its volume to 0.

**Comment by kickaxe60** [comment]
Doh! Yes indeed, I started just double clicking the file on my desktop when testing out different key combinations instead of using the command line like I had originally.  I also added the mute for each track.  Thanks again for all your help.  Cheers,

**Comment by kickaxe60** [comment]
Hi again guidocella, I have one last question.  With the command you provided ie "mp.set_property('lavfi-complex', '[aid1]volume=' .. volumes[1] .. '[vol1];[aid2]volume=' .. volumes[2] .. '[vol2];[aid3]volume=' .. volumes[3] .. '[vol3];[vol1][vol2][vol3]amix=inputs=3:duration=first:dropout_transition=3[ao]')" it works very well except that the mpv audio hiccups as I change volume up or down.  Just wondering if there is a way to make the transition smooth, like you're turning a knob to adjust volume up or down.  Maybe it's not possible, but thought I would ask.  Thanks again.

**Comment by guidocella** [comment]
You may be able to give labels to the volume filters and change the volumes with `af-command` instead of updating `lavfi-complex`.

**Comment by guidocella** [comment]
It doesn't seem to work unfortunately, with `--vf` and `--af` you can do .e.g `--af=@vol:volume=1` and then `af-command vol volume 3`, but if you try to specify labels in `--lavfi-complex` it fails with `[lavfi] parsing the filter graph failed`.

**Comment by kickaxe60** [comment]
Ok thanks for giving it a shot, much appreciated. Sent from my iPhoneOn Nov 8, 2023, at 2:51 PM, Guido Cella ***@***.***> wrote:﻿
It doesn't seem to work unfortunately, with --vf and --af you can do .e.g ***@***.***:volume=1 and then af-command vol volume 3, but if you try to specify labels in --lavfi-complex it fails with [lavfi] parsing the filter graph failed.

**Comment by kickaxe60** [comment]
Hi guidocella, the jittery volume changes from my bound keys to tracks 1, 2, and 3 got me thinking some more.  Just curious as I don't know enough about MPV but is it possible to map those different tracks to other software like loopback with different channels in order to control those volumes separately and smoothly or perhaps even a hardware device connected like a usb mixer, or maybe you have other suggestions (I'm on a mac). I played with VLC a bit, but I found MPV much more flexible... Anyway, I appreciate you taking the time to answer all my questions.  Take care,

**Comment by guidocella** [comment]
I'm not familiar with such solutions, sorry. The proper solution would be to implement support for filter labels in `lavfi-complex`.

**Comment by kickaxe60** [comment]
Hopefully that will happen.  Do you know if that is on the list of things to do or where would I post such a request?  I'm new to github... thanks.

**Comment by guidocella** [comment]
You can open a new issue selecting Request a new Feature (if you do please close this one), there is no guarantee someone will feel like working on it though.

**Comment by kickaxe60** [comment]
OK will do thanks.
