### ISSUE TITLE
commit 174df99ffa53f1091589eaa4fa0c16cdd55a9326 hangs at start when built from portage

### ISSUE THREAD

**Issue by sevz17** [mpv-player/mpv#12820]
### Important Information

Provide following Information:
- mpv version: 84de84b8aa6023efb3f8fac368d802359657268c
- Linux Distribution and Version: Gentoo (using ~amd64)
- Source of the mpv binary: portage
- If known which version of mpv introduced the problem: commit 174df99ffa53f1091589eaa4fa0c16cdd55a9326
- Window Manager and version: N/A
- GPU driver and version: amdgpu 6.5.10

The binary built from portage does not start, but the built from git works perfectly

When compiling from git I am using the same meson arguments except the pkg-config paths and `--native-file` that portage adds

### Log file

mpv does not even start
strace output: http://0x0.st/HtQg.strace

**Comment by Dudemanguy** [comment]
Going to at least need some build logs or something.

**Comment by sevz17** [comment]
When compiling from portage: http://0x0.st/HtQ7.log.gz;

When compiling from git: http://0x0.st/HtQF.txt

**Comment by llyyr** [comment]
This can be reproduced with `-Dc_args="-DNDEBUG"`, the linked PR above should fix it

**Comment by Dudemanguy** [comment]
Fixed by #12821

**Comment by sevz17** [comment]
Yeah, https://github.com/mpv-player/mpv/issues/12821 fixed the issue, thanks!
