### ISSUE TITLE
Cursor options

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#12824]
Use case:
My subwoofer is causing my mouse to slightly move when the bass is too powerful and I find it annoying when the OSC and my cursor shows up.

Question:
I would like to hide the cursor, but not permanently, maybe something like the same behavior as OSC? 
(When cursor is at the bottom half of the screen mpv shows the OSC, but when the cursor is on the top half of the screen the OSC is hidden)
Or maybe hide the cursor if the speed is slow?
Or maybe completely hide the cursor when it's at the top half of the screen?

Using Windows in case it matters.

**Comment by mia-0** [comment]
It should be possible to write a user script that sets the `cursor-autohide` option to `always` only within a specified window area, or to add that feature to whichever OSC you’re using.

Other than that… Bit of a silly idea but maybe you can fabricobble a sort of ramp at the far end of your desk that lifts the mouse high enough for the sensor to stop registering movement? That’ll work with any software 😜
Could also try a mouse pad with a fabric surface. Those have slightly more stiction; might just be enough to prevent the sensor from picking up the vibration.

**Comment by mia-0** [comment]
You can also use `input.conf` to manually enable/disable the cursor (bound to the `z` key in this example):
```
z cycle-values cursor-autohide 1000 always
```

**Comment by N-R-K** [comment]
> It should be possible to write a user script [...]

I was going to reply that hiding the bar while cursor is at "top" is pretty common and shouldn't require a user script. But then I realized that (a) the builtin OSC already does that and (b) that's not what the OP is asking for.

Now that I've read the OP more carefully, I'd say this is definitely a niche case. I think you should try to solve it at a physical level so you don't need to hack around on each application. And if that's not possible, consider a more global solution which will discard small movements (though keep in mind such things will always add some input latency).

**Comment by mia-0** [comment]
Here’s a quick and dirty user script that should always hide the cursor in the top 5% of the screen when mpv is in fullscreen mode:

```lua
function handle_move()
    if mp.get_property_bool("fullscreen") then
        local x, y = mp.get_mouse_pos()
        local w, h = mp.get_osd_size()
        if y < (h * 0.05) then
            mp.set_property("cursor-autohide", "always")
        else
            mp.set_property("cursor-autohide", 1000)
        end
    end
end

mp.add_key_binding("mouse_move", handle_move)
```

**Comment by N-R-K** [comment]
The `get_mouse_pos` thing is depreciated IIRC. You can observe the "mouse-pos" property instead.

**Comment by mia-0** [comment]
Ah, well I just took that from `osc.lua`

**Comment by mia-0** [comment]
Just to be sure: Save it as `.lua` file in the `scripts` directory of your mpv config path. When using Notepad, make sure the file type is set to `*.*` so that it doesn’t add a `.txt` extension.

**Comment by N-R-K** [comment]
@Obegg does this work?

```lua
function handle_move(prop, m)
	if mp.get_property_bool("fullscreen") then
		local w, h = mp.get_osd_size()
		if m.y < (h * 0.05) then
			mp.set_property("cursor-autohide", "always")
		else
			mp.set_property("cursor-autohide", 1000)
		end
	end
end
mp.observe_property("mouse-pos", "native", handle_move)
```

**Comment by mia-0** [comment]
Both versions work for me on recent mpv, FWIW…

**Comment by kasper93** [comment]
For OSC there is `minmousemove` option (see docs), if someone is adventurous you could add similar option for cursor hiding.
