### ISSUE TITLE
Metadata orientation not set anymore to "track-list/0/demux-rotation"

### ISSUE THREAD

**Issue by KaFu74** [mpv-player/mpv#12836]
Hello Team,

**Important Information**
I'm running an up to date Win10-64bit
Source for mpv exes is https://sourceforge.net/projects/mpv-player-windows/files/64bit/

No issue with mpv-x86_64-20231001-git-e969072
Issue came up with mpv-x86_64-20231008-git-78719c1

"track-list/0/demux-rotation" was not filled anymore after "mpv-x86_64-20231001-git-e969072"

**Reproduction steps**
A movie with metadata orientation set is required to reproduce

mpv.exe --no-config --input-conf=z_Rotate_Test_input.conf --script=z_Rotate_Test.lua test.mp4

**z_Rotate_Test_input.conf**
r cycle-values video-rotate "90" "180" "270" "0"

**z_Rotate_Test.lua**
function show_rotation()
local message = ""
local mpv_rotation_angel = mp.get_property_number('video-rotate')
message = "Rotation= " .. mpv_rotation_angel
local mpv_rotation_angel_initial = mp.get_property("track-list/0/demux-rotation")
if (mpv_rotation_angel_initial == nil or mpv_rotation_angel_initial == "nil property unavailable") then
mpv_rotation_angel_initial = 0
end
message = message .. "\nRotation-Initial= " .. mpv_rotation_angel_initial
mp.osd_message(message, 5)
end
mp.observe_property("video-rotate", "number", show_rotation)

**Test mp4 with 90 degree rotation set in metadata**
https://github.com/mpv-player/mpv/assets/149301721/d29cb815-e237-41ab-b9ed-588a6d7b4ea5

**Expected behavior**
Metadata orientation set to "track-list/0/demux-rotation"

**Actual behavior**
"track-list/0/demux-rotation" always 0

**Comment by kasper93** [comment]
`track-list/0/demux-rotation` shows container metadata, which for this file is 0.  What you want is `video-dec-params/rotate` which shows per frame metadata which is 90.

If you feel like this is a bug you should report it over https://trac.ffmpeg.org/ there is nothing wrong with mpv.

**Comment by KaFu74** [comment]
Then it should be marked as deprecated or removed from the documentation too.

https://mpv.io/manual/stable/#command-interface-track-list/n/demux-rotation

I can quite see where to get the initial orientation from the metadata instead, anyone got any tips?

**Comment by KaFu74** [comment]
Thanks a lot!
