### ISSUE TITLE
set vo at console would make OSD mess

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#12839]
### Important Information

Provide following Information:
- mpv version
git
- Windows Version
win10 22h2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20231107
- If known which version of mpv introduced the problem
N/a
- Possible screenshot or video of visual glitches
<img width=400 src="https://github.com/mpv-player/mpv/assets/41094733/34ee4373-8262-4a1c-a143-552b54fc1404">

### Reproduction steps

`./mpv --no-config --idle=yes --force-window --log-file=osd.log`

load a video and enable the console, input `set vo gpu-next`

### Expected behavior

No crazy OSD.

### Actual behavior

Check the screenshot above.

### Log file

[osd.log](https://github.com/mpv-player/mpv/files/13284457/osd.log)

### Sample files

N/a

**Comment by guidocella** [comment]
Duplicate of https://github.com/mpv-player/mpv/issues/12735

**Comment by hooke007** [comment]
Well, cannot believe so long no one care.
