### ISSUE TITLE
vo_gpu_next: scaler dispatch failure when using polar `--dscale` + `--correct-downscaling` on large images

### ISSUE THREAD

**Issue by dokur0chan** [mpv-player/mpv#12857]
### Important Information
```
mpv v0.36.0-778-g293fe9d7 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Nov  8 2023 00:28:36
libplacebo version: v6.338.0-51-gc59d487-dirty
FFmpeg version: N-112697-gf084e9b0b
FFmpeg library versions:
   libavutil       58.31.100
   libavcodec      60.32.102
   libavformat     60.17.100
   libswscale      7.6.100
   libavfilter     9.13.100
   libswresample   4.13.100
```
- Windows 11 Build 22631.2506
- shinchiro Windows binaries

### Reproduction steps

Open the sample image on a 1080p display (might be reproducible on other resolutions where the downscale factor is lower) with the following command:
```
--no-config --vo=gpu-next --dscale=ewa_lanczos --fs --keep-open=always
```
### Expected behavior

Image is downscaled with polar lanczos.

### Actual behavior
The following error is generated and the image is not downscaled properly.
```
[vo/gpu-next/libplacebo] Polar radius 24.428764 exceeds implementation capacity!
[vo/gpu-next/libplacebo] Failed dispatching scaler.. disabling
[vo/gpu-next/libplacebo] Attempting to modify a failed shader!
[vo/gpu-next/libplacebo] Attempting to modify a failed shader!
[vo/gpu-next/libplacebo] Attempting to modify a failed shader!
[vo/gpu-next/libplacebo] Attempting to modify a failed shader!
[vo/gpu-next/libplacebo] Trying to dispatch a failed shader.
[vo/gpu-next/libplacebo] Failed rendering image!
[vo/gpu-next] Failed rendering frame!
```
The error is not generated if `--correct-downscaling` is disabled. The command also works on `vo_gpu`.

### Log file

[bugpv.log](https://github.com/mpv-player/mpv/files/13301212/bugpv.log)

### Sample files

https://upload.wikimedia.org/wikipedia/commons/a/ad/%28Castelmaurou%29_-_Fa%C3%A7ade_de_la_mairie.jpg

**Comment by kasper93** [comment]
> [vo/gpu-next/libplacebo] Polar radius 24.428764 exceeds implementation capacity!

Limitation of libplacebo with large (down)scale factors.

**Comment by dokur0chan** [comment]
Oops. Duplicate of #12607 it seems. Feel free to close and wontfix if there's no valid use-case for this in libplacebo. I don't really have a stake in the matter either way. Using a polar filter to downscale is just overkill, especially for video content.

_Buuuuuuuuuut..._ if I were (let's say) downscaling a RAW image of a rose that I took with my DSLR... and I wanted to view that image in mpv (hypothetically speaking) using a sharp and **_cough_** mathematically-sound kernel with high moiré suppression... then (theoretically) there could be a possible use-case...
