### ISSUE TITLE
Long CJK subtitles get beyond the screen width

### ISSUE THREAD

**Issue by escape0707** [mpv-player/mpv#12851]
### Important Information

Provide following Information:
- mpv version: 
v0.36.0-766-gf41805081b
- Linux Distribution and Version:
Arch Linux
- Source of the mpv binary: 
AUR/mpv-git
- If known which version of mpv introduced the problem
- Window Manager and version:
mutter 45.1
- GPU driver and version:
mesa 23.2.1, (AMD APU)
- Possible screenshot or video of visual glitches
![image](https://github.com/mpv-player/mpv/assets/11014745/63406fda-6145-4d62-9f93-0af6324f6626)
![image](https://github.com/mpv-player/mpv/assets/11014745/9166fd7f-67c3-4a1a-bf04-729ba6860b08)
Reproducible with `--no-config`, too.

### Reproduction steps

Play a video with (external?) a CJK subtitle track selected. Use a larger font size might make this easier to be reproduced. 

### Expected behavior

When the current line of subtitle is too long, the subtitle is displayed with several lines to maintain visible inside the screen/window.

### Actual behavior

When the current line of subtitle is too long, there is no line breaking measure taken to prevent the subtitle getting out of the screen/window. 

Likely related to #7158

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/13291155/output.txt)

**Comment by llyyr** [comment]
Can you provide a sample? You can extract just the subtitle track with ffmpeg

**Comment by po5** [comment]
Is your subtitle natively ASS or is it getting converted internally by mpv? See #10597  
If it is ASS your subtitle was badly authored, you should specify your own line breaks. I believe libass doesn't want to change the default behavior for compatibility with existing subtitles.

**Comment by guidocella** [comment]
I think you need to compile libass with libunibreak support.

**Comment by guidocella** [comment]
I confirmed that installing `libunibreak` and `libass-git` fixes this. It would be nice if Arch's libass package included libunibreak since it is small.

**Comment by escape0707** [comment]
Sorry, I was watching a movie and didn't realize that so many devs have been answering my question.

> I confirmed that installing libunibreak and libass-git fixes this. It would be nice if Arch's libass package included libunibreak since it is small.

I'll give this a try right now. 

> https://github.com/mpv-player/mpv/pull/10597 should have addressed your issue, since your subtitle is SRT.

Yeah, I thought so when going through the issue mentioned in the OP. I highly doubt that maybe it's a packaging problem specific to Arch as guidocella suggested. Anyway, I'll compile `libass` again.

**Comment by escape0707** [comment]
> I confirmed that installing `libunibreak` and `libass-git` fixes this. It would be nice if Arch's libass package included libunibreak since it is small.

I can confirm that the method you've mentioned can immediately fix my issue. So this is a distro specific issue.

This issue also happens for `mpv-android`, too. But I guess I'll have to file a separate issue there since I can't even find the code in the fix in that repo.

Anyway, thank you so much for the investigation!

**Comment by guidocella** [comment]
It's not really a packaging problem as other distros don't pull libunibreak either yet, it would be an enhancement.

**Comment by escape0707** [comment]
Duly noted. I'll see if there is a way for me to request adding this as a dependency or something else.

**Comment by xrishox** [comment]
Yeah I'm having the same issue with mpv from the fedora repos and with mpv from flathub. I was able to get it working inside of an arch distrobox by installing mpv and libunibreak from the standard repos and libass-git from the aur as suggested above though.

**Comment by guidocella** [comment]
Arch's libass package now includes libunibreak 🎉
