### ISSUE TITLE
file-size and stream-end properties are 0 when opening local files paused

### ISSUE THREAD

**Issue by zeromind** [mpv-player/mpv#12869]
### Important Information

Provide following Information:
- mpv version: v0.36.0-818-g438ead7a3d
- Platform and Version: openSUSE Tumbleweed 20231106
- Source of the mpv binary: built using mpv-build

When opening local files with `pause`, the properties `file-size` and `stream-end` are `0` instead of the actual file's size.
Simply waiting does not result in mpv updating them to the correct value.
Unpausing, or seeking **does** update them.

I've bisected the issue, and found this as first bad commit (from #12757):
```
zeromind@bearmetal:~/src/github.com/mpv-player/mpv-build.test/mpv$ git bisect good
8bbcc87feea7abf256a6c7f511244d09f5520c17 is the first bad commit
commit 8bbcc87feea7abf256a6c7f511244d09f5520c17
Author: NRK <nrk@disroot.org>
Date:   Fri Oct 27 01:24:41 2023 +0600

    timer: remove MP_START_TIME
    
    instead require mp_raw_time_ns() to not return 0, which all current
    implementation already should follow.

 common/msg.c          |  4 ++--
 osdep/semaphore_osx.c |  6 +++---
 osdep/timer.c         | 10 ++--------
 osdep/timer.h         |  3 +--
 4 files changed, 8 insertions(+), 15 deletions(-)
```

### Reproduction steps

1. create `input.conf` to easily check `file-size` and `stream-end` properties: `F2 print-text "file-size: ${=file-size} - stream-end: ${=stream-end}"`
2. open (video) file with mpv, paused `mpv test_file.mkv --no-config --pause --input-conf=input.conf`
3. press F2 key

### Expected behavior

`file-size` and `stream-end` properties are set the actual file's size,
mpv prints e.g. `file-size: 1422859102 - stream-end: 1422859102`

### Actual behavior

`file-size` and `stream-end` properties are both set to `0`,
mpv prints `file-size: 0 - stream-end: 0`
Only unpausing or seeking updates both properties.

### Log file
https://0x0.st/HtFF.txt

**Comment by butterw** [comment]
I've noticed this issue because it breaks one of my scripts (working OK with v0.36 release). 
I don't use pause. When mpv is started to play a video file, the filesize of the initially loaded video is 0.
