### ISSUE TITLE
avif screenshot issue

### ISSUE THREAD

**Issue by CCCAUCHY** [mpv-player/mpv#12881]
### Important Information

- mpv version v0.36
- Windows 10 pro 22H2 19045.3636
- Source of the mpv [binary](https://github.com/eko5624/mpv-win64/releases/download/2023-11-13/static-mpv-20231113.7z)

### Reproduction steps

using config `screenshot-format=avif` then press `s` to save a screenshot.

### Expected behavior

Screenshot saved successfully

### Actual behavior

error

### Log file

`[   1.451][e][screenshot] Could not find encoder 'libaom-av1', for saving images`

### Sample files

every video

**Comment by zhongfly** [comment]
Because the binary you download don't have avif encoder as log said.
You should ask the maintainer of https://github.com/eko5624/mpv-win64 to fix it, not here.

**Comment by hooke007** [comment]
Your build had rav1e only. 

> also have the same issue with config screenshot-avif-encoder=libdav1d

`libdav1d` is a decoder. You didn't use the correct name of rav1e.

**Comment by CCCAUCHY** [comment]
> Because the binary you download don't have av1 encoder as log said. You should ask the maintainer of https://github.com/eko5624/mpv-win64 to fix it, not here.
> 
> You can use shinchiro's build:https://github.com/shinchiro/mpv-winbuild-cmake/releases/latest or my build:https://github.com/zhongfly/mpv-winbuild/releases/latest. Those builds have av1 encoder `rav1e`.

what is the different between shinchiro's and yours?
