### ISSUE TITLE
MPV isn't loading the `/usr/local/etc/mpv` config directory

### ISSUE THREAD

**Issue by ramon-alpal** [mpv-player/mpv#12886]
### Important Information

Provide following Information:
- mpv version: 0.36.0
- Linux Distribution and Version: Artix Linux/Arch Linux
- Source of the mpv binary: distro repositories

### Reproduction steps

I modified a script  on the `/usr/local/etc/mpv` directory but it didn't reload.  But I figured out that the `/usr/local/etc/mpv` directory is no longer loaded - even if the man page seas the contrary (it needs a change)

### Expected behavior

MPV, as the man page seas, should load the config and scripts on the directory `/usr/local/etc/mpv`

### Actual behavior

MPV does not load the config and scripts from the directory `/usr/local/etc/mpv`

### Fix

I ended up using the environment variable `MPV_HOME` and setting it to `/usr/local/etc/mpv`. The section `FILES` on the `man page` should be updated if this is the new expected behavior

**Comment by po5** [comment]
Provide a log file.

**Comment by ramon-alpal** [comment]
Sure here it is: [mpv-log-file.txt](https://github.com/mpv-player/mpv/files/13335317/mpv-log-file.txt)

I've process it with the following command, for obvious reasons:

    sed 's|$HOME|~|g' tmp.txt | tr -s '~' '~' >mpv-log-file.txt

And I used the following to generate the original:

    mpv --log-file=tmp.txt

Also, a found out that the `/usr/local/etc/mpv` directory was copied to the local directory `~/.config/mpv`.  So it was all working, but the scripts weren't "reloading" because the loaded ones are in `~/.config/mpv`. Maybe it's all a distro thing or a MPV thing, but I just wanted to notify you

**Comment by Dudemanguy** [comment]
The docs say.

>The system-wide configuration file 'mpv.conf' is in your configuration directory (e.g. ``/etc/mpv`` **or** ``/usr/local/etc/mpv``),

Most linux distributions including Arch use `/etc` not `/usr/local/etc`. You'll see in your log file that it loads files in `/etc`. This is expected.

**Comment by ramon-alpal** [comment]
So it's a distro thing, ha?  It did work previously.  I was thinking that the `/usr/local/etc/mpv` was a dedicated global directory for the user to set it (with preference over `/etc/mpv`) - because, normally, `/etc/*` configs are overwritten by the package manager.  Cool to know, thanks👍

**Comment by Dudemanguy** [comment]
You can set the system configuration directory at compile time if you ever compiled mpv yourself. If you did not set the `prefix` option, then it would likely end up as `/usr/local/etc/mpv` which would explain why it previously worked.

>normally, /etc/* configs are overwritten by the package manager.

I would certainly not be happy if my package manager did this.

**Comment by ramon-alpal** [comment]
> You can set the system configuration directory at compile time if you ever compiled mpv yourself. If you did not set the `prefix` option, then it would likely end up as `/usr/local/etc/mpv` which would explain why it previously worked.

Thanks but I actually knew a solution from the start:

> I ended up using the environment variable `MPV_HOME` and setting it to `/usr/local/etc/mpv`

I personally prefer it because I don't have to provide `--prefix` (the option you said) every instance I execute MPV, and compiling MPV would require a lot of effort - specially to keep the source code up to date to be able to stream video.

I also launch MPV from a wrapper script, were I mainly check if I can embed MPV to [`tabbed`](https://tools.suckless.org/tabbed/) - so it will open in a "tab" and replace the current window (sort of).  I actually have an issue with it, were, when you execute MPV embedding it to [`tabbed`](https://tools.suckless.org/tabbed/), with the `--wid` option, it will not set the `X11` window name property - but I have a script to circumvent the issue witch basically solves it completely.  But I'll report it eventually - in a new bug report.


> > normally, /etc/* configs are overwritten by the package manager.

> I would certainly not be happy if my package manager did this.

It's not really *exactly* like that, but some do.  But I normally have it all in a local repository and, with a *make file* (sort of), I install it - and normally, all my programs, are configured at `/usr/local/share` anyways

**Comment by Dudemanguy** [comment]
>I actually have an issue with it, were, when you execute MPV embedding it to [tabbed](https://tools.suckless.org/tabbed/), with the --wid option, it will not set the X11 window name property

This is a new option in master right and will be in the upcoming release. If you set `--x11-wid-title` in your config, it will set the window name.

**Comment by ramon-alpal** [comment]
>> I actually have an issue with it, were, when you execute MPV embedding it to [`tabbed`](https://tools.suckless.org/tabbed/), with the `--wid` option, it will not set the `X11` window name property
>
> This is a new option in master and will be in the upcoming release. If you set `--x11-wid-title` in your config, it will set the window name.

Great, that will make everything easier.  But, for now, if I don't want to use MPV compiled from source, I guess I'll have to wait until the Arch/Artix repositories sync - and keep using my MPV `Lua` script.  I've updated the title - I guess a specific bug report isn't no longer needed with that?.  I'll have to make a repository with my script for people that need a solution though
