### ISSUE TITLE
vo=gpu-next issue

### ISSUE THREAD

**Issue by sajinman** [mpv-player/mpv#12892]
i want to the video to look exactly like vo=gpu but using vo=gpu-next.because i want to use the image-lut feature.Here are screenshots : ( 1st one in vo=gpu & 2nd one is vo=gpu-next)
<img width="960" alt="Screenshot 2023-11-15 034826" src="https://github.com/mpv-player/mpv/assets/91364355/7d5d8243-84a9-4d73-b323-622b3d0fd461">
<img width="960" alt="Screenshot 2023-11-15 034744" src="https://github.com/mpv-player/mpv/assets/91364355/15030c42-720a-4da8-bf1c-37b2ed2510be">

**Comment by CounterPillow** [comment]
exceptional contribution, thank you
