### ISSUE TITLE
mpv-2.dll breaks SVP ipc-comms link to Plex HTPC after build 30/10/2023

### ISSUE THREAD

**Issue by netExtra** [mpv-player/mpv#12891]
### Important Information

Provide following Information:
- mpv version: 31/10/2023
- Windows Version: Windows 10 22H2
- Source of the mpv binary: Discovered with personal build confirmed with Shinchiro.

SVP is frame interpolation software that uses IPC to communicate with mpv. The Plex HTPC logs show ipc communications working as expected. Opens an ipc-channel, closes, opens a new channel. But SVP only registers with the first video. 

I checked both mpv and ffmpeg commit logs and this one - [avformat/vf_vapoursynth: simplify xyz format check](https://github.com/FFmpeg/FFmpeg/commit/6aff17a4511189a6765d7874a581d57dede26f01) -  might be interesting because SVP uses vapoursynth. But totally a guess.

### Reproduction steps

Start Plex HTPC.
Play a video then Stop.
Play a 2nd, 3rd,4th video.

### Expected behavior
Video plays and SVP shows up on screen indicating active with interpolated frame rate

### Actual behavior
First video - 
Video plays and SVP shows up on screen indicating active with interpolated frame rate
SVP manager says "1 active video" then display fps and other relevant info.

Next videos - 
Video plays but no SVP indication on screen. 
SVP manager says "no active playback"

### Log file
If a log file is required then it will be provided.

**Comment by kasper93** [comment]
> with personal build

Can you bisect so we don't have to guess where it broke?

**Comment by netExtra** [comment]
> > with personal build
> 
> Can you bisect so we don't have to guess where it broke?

It broke just after the Shinchiro 30/10/2023 build which is the 31/10/2023 build. I

**Comment by kasper93** [comment]
> going back to 30/10/2023. It broke on the 31/10/2023 mpv build.

So basically this range of commits in mpv https://github.com/mpv-player/mpv/compare/0341a6f...cb2b579

I don't know how SVP is integrated, Maybe `-del` removal broke it?

**Comment by Dudemanguy** [comment]
If SVP manager used `-del` in between files to remove the old filter, then it would indeed not work. It should use `-remove` instead which I would think would be preferred and easier to manage anyways.

**Comment by netExtra** [comment]
> > going back to 30/10/2023. It broke on the 31/10/2023 mpv build.
> 
> So basically this range of commits in mpv [0341a6f...cb2b579](https://github.com/mpv-player/mpv/compare/0341a6f...cb2b579)
> 
> I don't know how SVP is integrated, Maybe `-del` removal broke it?

It looks like that might be it. See attached screenshot. These errors only appear when SVP stops working.

![Screenshot 2023-11-14 at 15 55 45](https://github.com/mpv-player/mpv/assets/140253706/0da60342-2008-4257-9e7f-ed6479498caa)
shot.

**Comment by netExtra** [comment]
> Yes that would be it. The `-del` syntax has been deprecated for many years with a warning to use `-remove` instead. We finally removed it recently, so I don't believe there's anything for us to do here.

I assume that SVP with VapourSynth wouldn't be involved here? So is this a Plex or SVP issue?

**Comment by Dudemanguy** [comment]
I don't know. Whatever is responsible for setting/removing filters.

**Comment by netExtra** [comment]
> I don't know. Whatever is responsible for setting/removing filters.

I've checked my config, replaced -clr with -remove and it's still happening. Plex logs show th same error so I will keep plowing through that. Thanks for the steer :)
