### ISSUE TITLE
Mouse scroll wheel left/right are inverted on macOS

### ISSUE THREAD

**Issue by quietvoid** [mpv-player/mpv#12899]
### Important Information

Provide following Information:
- mpv version: 0.36.0 and master
- macOS Version: macOS 14 Sonoma
- Source of the mpv binary or bundle: homebrew
- If known which version of mpv introduced the problem: 

### Reproduction steps
With a mouse, use the scroll wheel and do left/right clicks with:
`mpv --input-test --force-window --idle`

### Expected behavior
- Left scroll clicks seek backwards
- Right scroll clicks seek forwards

### Actual behavior
- Left scroll clicks seek forward and detect as `MOUSE_RIGHT`
- Right scroll clicks seek backward and detect as `MOUSE_LEFT`

### Log file

None for now.

**Comment by Akemi** [comment]
as discussed on irc. from my side there is no log needed, i can reproduce the issue.

thanks again for reporting.
