### ISSUE TITLE
vo_dmabuf_wayland: wrong scale and blurred OSD on gnome 45.1

### ISSUE THREAD

**Issue by crab2313** [mpv-player/mpv#12896]
### Important Information

Provide following Information:
- mpv version
- latest-git
- Linux Distribution and Version
- archlinux rolling
- Source of the mpv binary both prebuild 
- 0.36.0 and manually build git version
- If known which version of mpv introduced the problem
- don't known
- Window Manager and version
- mutter 45.1
- GPU driver and version
- amdgpu thinkpad z13
- Possible screenshot or video of visual glitches
- no

### Reproduction steps

mpv -vo va_dmabuf_wayland <video>.mp4

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior

OSD is not blurred.

### Actual behavior

OSD is blurred. My screen resolution is 2880x1800 with scale factor set to 2. The window is scaled to 1440x810 (not fullscreen but maximized) with following log:

```
[cplayer] VO: Description: Wayland dmabuf video output
[vo/dmabuf-wayland] reconfig to 1920x1080 vaapi[nv12] bt.709/bt.709/bt.1886/limited/display CL=mpeg2/4/h264 crop=1920x1080+0+0
[vo/dmabuf-wayland/wayland] Reconfiguring!
[vo/dmabuf-wayland] Window size: 1920x1080 (Borders: l=0 t=0 r=0 b=0)
[vo/dmabuf-wayland] Video source: 1920x1080 (1:1)
[vo/dmabuf-wayland] Video display: (0, 0) 1920x1080 -> (0, 0) 1920x1080
[vo/dmabuf-wayland] Video scale: 1.000000/1.000000
[vo/dmabuf-wayland] OSD borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland] Video borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland] Window size: 1920x1080 (Borders: l=0 t=0 r=0 b=0)
[vo/dmabuf-wayland] Video source: 1920x1080 (1:1)
[vo/dmabuf-wayland] Video display: (0, 0) 1920x1080 -> (0, 0) 1920x1080
[vo/dmabuf-wayland] Video scale: 1.000000/1.000000
[vo/dmabuf-wayland] OSD borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland] Video borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland/wayland] Obtained preferred scale, 1.000000, from the compositor.
[vo/dmabuf-wayland/wayland] Resizing due to xdg from 1920x1080 to 1440x810
[vo/dmabuf-wayland/wayland] Given DND offer with mime type text/plain
[vo/dmabuf-wayland/wayland] Given DND offer with mime type text/plain;charset=utf-8
[vo/dmabuf-wayland/wayland] Received a new DND offer. Releasing the previous offer.
[cplayer] first video frame after restart shown
[cplayer] playback restart complete @ 0.000000, audio=eof, video=playing
[vo/dmabuf-wayland] Window size: 1440x810 (Borders: l=0 t=0 r=0 b=0)
[vo/dmabuf-wayland] Video source: 1920x1080 (1:1)
[vo/dmabuf-wayland] Video display: (0, 0) 1920x1080 -> (0, 0) 1440x810
[vo/dmabuf-wayland] Video scale: 0.750000/0.750000
[vo/dmabuf-wayland] OSD borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland] Video borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland] Window size: 1440x810 (Borders: l=0 t=0 r=0 b=0)
[vo/dmabuf-wayland] Video source: 1920x1080 (1:1)
[vo/dmabuf-wayland] Video display: (0, 0) 1920x1080 -> (0, 0) 1440x810
[vo/dmabuf-wayland] Video scale: 0.750000/0.750000
[vo/dmabuf-wayland] OSD borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland] Video borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland/wayland] Enabling idle inhibitor
[cplayer] Set property: user-data/osc/margins={"l":0,"r":0,"b":0,"t":0} -> 1
[vo/dmabuf-wayland] Window size: 1440x810 (Borders: l=0 t=0 r=0 b=0)
[vo/dmabuf-wayland] Video source: 1920x1080 (1:1)
[vo/dmabuf-wayland] Video display: (0, 0) 1920x1080 -> (0, 0) 1440x810
[vo/dmabuf-wayland] Video scale: 0.750000/0.750000
[vo/dmabuf-wayland] OSD borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland] Video borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland] Window size: 1440x810 (Borders: l=0 t=0 r=0 b=0)
[vo/dmabuf-wayland] Video source: 1920x1080 (1:1)
[vo/dmabuf-wayland] Video display: (0, 0) 1920x1080 -> (0, 0) 1440x810
[vo/dmabuf-wayland] Video scale: 0.750000/0.750000
[vo/dmabuf-wayland] OSD borders: l=0 t=0 r=0 b=0
[vo/dmabuf-wayland] Video borders: l=0 t=0 r=0 b=0
```

**Comment by Dudemanguy** [comment]
That's a feature. `vo_dmabuf_wayland` is scaled completely by the compositor. Looking blurry is expected.

**Comment by crab2313** [comment]
> That's a feature. `vo_dmabuf_wayland` is scaled completely by the compositor hence the scale value of 1 in the log. Looking blurry is expected.

Can't we use an OSD surface with full resolution and make the text sharp?

**Comment by crab2313** [comment]
> That's a feature. `vo_dmabuf_wayland` is scaled completely by the compositor hence the scale value of 1 in the log. Looking blurry is expected.
So the buffer send to wayland is actually a 1920xx1080 one ?

**Comment by Dudemanguy** [comment]
>Can't we use an OSD surface with full resolution and make the text sharp?

The OSD is a subsurface of the mpv window. I don't believe you can have mismatched scales.

>So the buffer send to wayland is actually a 1920xx1080 one ?

You'd need to look at the wayland debug logs to be sure but probably yeah. The compositor then downscales it. The purpose of this vo is to hand off as much as possible to the compositor and be efficient. It is not for nice looking video. It's not like it's just your text that is blurry.

**Comment by crab2313** [comment]
[mpv.log](https://github.com/mpv-player/mpv/files/13359830/mpv.log)

**Comment by Dudemanguy** [comment]
Yup so create_immed makes 1920x1080 buffers and viewport scales it down. That's intended.

**Comment by crab2313** [comment]
Since the compositor will scale the buffer anyway. Can't we set the scale to 2 and let the compositor scale the buffer to 2880x1800 and render a OSD subsurface with correct resolution.

**Comment by crab2313** [comment]
> Yup so create_immed makes 1920x1080 buffers and viewport scales it down. That's intended.

Thanks for the explanation, I will try to read the code and understand the workflow.

**Comment by Dudemanguy** [comment]
If you want accurate scaling, you should be using gpu or gpu-next. I purposely made `vo_dmabuf_wayland` unaware of hidpi. It doesn't make sense with what the purpose of the VO is.
