### ISSUE TITLE
How to lock window aspect ratio to match video

### ISSUE THREAD

**Issue by Andarwinux** [mpv-player/mpv#12903]
How can I force the window aspect ratio to match video aspect ratio to make sure that no matter how the window is adjusted, there will never be a black border?
`keepaspect-window=yes` does not seem to apply to this issue.

https://github.com/mpv-player/mpv/labels/meta%3Aquestion

**Comment by CounterPillow** [comment]
Locking the window aspect ratio to that of the video is the default behaviour. If that is not the behaviour you're seeing, then you are reporting an issue, not asking a question, and should include the full set of details the issue template asks of you.
