### ISSUE TITLE
Embedded cover art displayed in wrong order

### ISSUE THREAD

**Issue by terr72** [mpv-player/mpv#12900]
### Important Information

Provide following Information:
- mpv 0.34.1-1ubuntu3
- Ubuntu Jammy
- Official Ubuntu Repository
- ...but the problem is not subject to Linux only

### Reproduction steps

1. Open an MP3, FLAC or OPUS audio file which has more than the front cover as embedded cover art.

### Expected behavior

The front cover should be displayed by default.
If not, the cover art order for display should be configurable.

### Actual behavior

mpv displays the last added media item (typically the back or artist image) instead of the front image.

### Sample files

[Sample MP3 file with front & back cover](https://www.file-upload.net/download-15223060/sample_with_covers.mp3.html)

**Comment by guidocella** [comment]
You're using a 2 years old mpv version, the front cover is already displayed by default here (though I don't understand which commit changed it).

**Comment by terr72** [comment]
OK - should've tested the latest version before, but I was only searching the history of the releases and searching the commit descriptions. Closed.
