### ISSUE TITLE
af=rubberband causes hwdec=*-copy performance regression

### ISSUE THREAD

**Issue by Andarwinux** [mpv-player/mpv#12905]
### Important Information

Provide following Information:
- mpv version
latest master
- Windows Version
23H2
- Source of the mpv binary
[mpv-winbuild](https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-11-17-ca45b71)

### Reproduction steps
```
mpv --no-config --vo=gpu-next --hwdec=(vulkan|nvdec|d3d11va|dxva2|cuda|vaapi)-copy --af=rubberband --gpu-context=(d3d11|winvk)
```
If with `--vd-queue-enable=yes`, this problem will not occur.

I would recommend using 8K60 or 4K120 video for reproduction, or using this profile:

```
vo=gpu-next
gpu-context=winvk
hwdec=vulkan-copy
vd-queue-enable=no
af=rubberband
osd-msg1="FPS: ${estimated-display-fps}"
video-sync=display-desync
untimed=yes
video-sync=display-desync
vulkan-swap-mode=immediate
```

### Expected behavior
A-V sync=0
### Actual behavior
A-V desync
### Log file

[log.txt](https://github.com/mpv-player/mpv/files/13394303/log.txt)(vd-queue-enable=no)
[log.txt](https://github.com/mpv-player/mpv/files/13394321/log.txt)(vd-queue-enable=yes)

**Comment by zDEFz** [comment]
actually provide test video so it's easier
