### ISSUE TITLE
Rotation not applied for mkv file

### ISSUE THREAD

**Issue by rom1v** [mpv-player/mpv#12928]
### Important Information

Provide following Information:
- mpv version 0.36.0
- Platform and Version: Debian sid
- Source of the mpv binary: `apt install mpv`

### Reproduction steps

If a rotation is set as a display matrix in an MP4 file, mpv handles it correctly, but in a MKV file, it ignores it:

```bash
ffmpeg -display_rotation 90 -i big_buck_bunny.mp4 -c copy output.mp4
ffmpeg -display_rotation 90 -i big_buck_bunny.mp4 -c copy output.mkv

ffplay output.mp4    # ok
ffplay output.mkv    # ok

mpv output.mp4       # ok
mpv output.mkv       # ko (no rotation applied)

ffmpeg -i output.mkv -c copy remux.mp4
mpv remux.mp4        # ok
```

**Comment by kasper93** [comment]
> mpv version 0.36.0

Works fine with latest master and also you need recent enough ffmpeg libraries.

**Comment by rom1v** [comment]
Thank you for your answer.

Indeed, it works on master, thanks to commit a4bf0bd695da7ac0fea561342c60d954d485af0a :tada:

**Comment by rom1v** [comment]
@rp1231 Wrong repo.
