### ISSUE TITLE
regression - --tscale=sphinx playback dies with 4k 60fps content

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#12927]
When I play a 4k 60fps VP9 video with this config

```
vo=gpu-next
hwdec=d3d11va
gpu-api=d3d11

video-sync=display-resample
interpolation
tscale=sphinx
```

playback only shows a black screen for the first few seconds and the logs are flooded with issues.

```
[ffmpeg] AVHWFramesContext: Static surface pool size exceeded.
[ffmpeg/video] vp9: get_buffer() failed
Error while decoding frame (hardware decoding)!
[ffmpeg] AVHWFramesContext: Static surface pool size exceeded.
[ffmpeg/video] vp9: get_buffer() failed
Error while decoding frame (hardware decoding)!
[ffmpeg] AVHWFramesContext: Static surface pool size exceeded.
[ffmpeg/video] vp9: get_buffer() failed
Error while decoding frame (hardware decoding)!
Attempting next decoding method after failure of vp9-d3d11va.
[ffmpeg/video] vp9: Not all references are available
[ffmpeg/video] vp9: Not all references are available
```

When commenting out `tscale=sphinx`, issue is gone.

Log:
[output.txt](https://github.com/mpv-player/mpv/files/13418958/output.txt)

Broke with
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20231120

Still good with
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20231118

Win 11 23H2

**Comment by guidocella** [comment]
Bisected to 4dcf2d1385.

**Comment by kasper93** [comment]
Could you try build from https://github.com/mpv-player/mpv/pull/12929 ?

For interpolation I would suggest using `--correct-downscaling=no` or `--vo=gpu` until the need of `gpu-next` for bigger radius is resolved. 

There is also this https://github.com/mpv-player/mpv/pull/12917 which is related to unbound number of frames requested too.

**Comment by aufkrawall** [comment]
> Could you try build from #12929 ?

Yep, mpv-x86_64-w64-mingw32 build for that PR works.

**Comment by kasper93** [comment]
@aufkrawall: could you retry new build? I changed the condition, but should work the same in your case.

**Comment by aufkrawall** [comment]
> @aufkrawall: could you retry new build? I changed the condition, but should work the same in your case.

Still works. :)

**Comment by aufkrawall** [comment]
@kasper93 Do you think the underlying issue that occurs with `--correct-downscaling` can be fixed at some point? Hardware decoding still breaks pretty easily when there is hard enough stalling, e.g. by shader compilation (?) when resizing the window a lot.

**Comment by aufkrawall** [comment]
Thanks for the feedback, appreciated.

**Comment by aufkrawall** [comment]
```
tscale=sphinx
tscale-blur=0.65
```

With `tscale-blur` adjustable to a given display, i.e. higher blur value with OLED. Imho you can only start screaming in terror when seeing `oversample` on OLED.

**Comment by aufkrawall** [comment]
@kasper93 Btw. d3d11va still dies on downsizing window during playback with such a config, but for whatever weird reason only (?) with AV1, not with H.264 and HEVC.
