### ISSUE TITLE
Is it possible get the screenshot path from the screenshot command (in lua)

### ISSUE THREAD

**Issue by SacredZenpie** [mpv-player/mpv#12925]
The title basically. Im trying to avoid making a full screenshot script, would much rather rely on MPV and its config to handle everything. So I was wondering if its possible to get the path from the screenshot command for my lua script.

**Comment by stax76** [comment]
I think no, for what do you need it? Maybe there are better ways.

**Comment by SacredZenpie** [comment]
I was planning to use the path with powershell to copy the screenshot to clipboard after screenshot. Currently Im using screenshot to file to achieve that but I was hoping no to rely on my script for filename(s)

**Comment by Sneakpeakcss** [comment]
Wouldn't using `os.time()` or `os.date()` take care of a big chunk of mpv's `screenshot-template` for you ? That shouldn't be too bloaty and work almost the same as screenshot command when it comes to filenames:

```lua
mp.add_key_binding("g", "screenshot-clipboard", function()
    local screenshot_dir = string.gsub(mp.command_native({'expand-path', mp.get_property_native('screenshot-dir')}) .. "\\", "/", "\\")
    local timestamp = os.date("%Y-%m-%d_%H-%M-%S") -- os.time()
    local path = screenshot_dir .. "Screenshot_" .. timestamp .. ".png"
    mp.commandv("screenshot-to-file", path, "video")
    mp.command_native({
    	name = "subprocess",
    	playback_only = false,
    	args = { 'powershell', 'Set-Clipboard -LiteralPath ', "'" .. path .. "'"},
    })
end)

```
```
%f =	local filename = mp.get_property("filename")
%F =	local filename = mp.get_property("filename/no-ext")
etc
```

This doesn't seem that different, and path is still controlled by mpv's `screenshot-dir` config setting.

**Comment by sfan5** [comment]
[manual](https://mpv.io/manual/master/#command-interface-screenshot-%3Cflags%3E) says:
> On success, returns a mpv_node with a filename field set to the saved screenshot location.

You can use this from Lua with `mp.command_native_async`.
