### ISSUE TITLE
How to get the current window size value

### ISSUE THREAD

**Issue by Ptilopsis01** [mpv-player/mpv#12933]
As said above, I want to know how to get the current window size value to trigger different filters in different conditions.

I've tried "video-params/w(h)", "video-out-params/w(h)" and "current-video-scale", but none of them get the value I want.

**Comment by christoph-heinrich** [comment]
https://mpv.io/manual/master/#command-interface-osd-dimensions

**Comment by Ptilopsis01** [comment]
> https://mpv.io/manual/master/#command-interface-osd-dimensions

I've checked this part, but I didn't find the value I want, which should be the height/width of current mpv window

**Comment by christoph-heinrich** [comment]
> I've checked this part, but I didn't find the value I want

Then I have no idea what you mean with "window size".

**Comment by Ptilopsis01** [comment]
> > I've checked this part, but I didn't find the value I want
> 
> Then I have no idea what you mean with "window size".

So which param do you think might be the one I want? Maybe I haven't check it yet.

**Comment by christoph-heinrich** [comment]
`osd-dimensions/w` and `osd-dimensions/h`

**Comment by Ptilopsis01** [comment]
> `osd-dimensions/w` and `osd-dimensions/h`

That works, thanks a lot!
