### ISSUE TITLE
Do i need to manually set `dscale` to `scale` or it will be done automatically?

### ISSUE THREAD

**Issue by soredake** [mpv-player/mpv#12939]
I see no word about `dscale` mirroring `scale` by default on docs:
![изображение](https://github.com/mpv-player/mpv/assets/5204968/7f405079-cfe0-417e-89e6-01d9d9137d87)

But in source code, IIUC `dscale` should mirror `scale` value:
https://github.com/mpv-player/mpv/blob/2a57a6ee4f65b168ecdb4843d6476b8b5f87a62f/video/out/gpu/video.c#L4185-L4186

**Comment by natural-harmonia-gropius** [comment]
dscale=

Just nothing after =, also for cscale

**Comment by kasper93** [comment]
> I see no word about dscale mirroring scale by default on docs:

If you don't set `dscale` the default `hermite` will be used as noted in docs here https://github.com/mpv-player/mpv/blob/5220725ca506bc40f1f0c3f0507fa337605f1dba/DOCS/man/options.rst?plain=1#L5309-L5310

If you manually set it to empty string by `--descale=""` it will fallback to scale value, but this is not intended use and mostly for backward compatibility only. So to not make docs confusing this usage is not mentioned. You should either not set this value or set it to proper name.

**Comment by soredake** [comment]
Understood, thanks!
