### ISSUE TITLE
MPV crash on windows after install of new audio device and switching around

### ISSUE THREAD

**Issue by lhpitn** [mpv-player/mpv#12938]
### Important Information

Provide following Information:
- mpv version
- mpv 0.34.0-265-g305332f8a0 Copyright © 2000-2022 mpv/MPlayer/mplayer2 projects
 built on Sun Apr 17 11:25:20 UTC 2022
FFmpeg library versions:
   libavutil       57.24.101
   libavcodec      59.26.100
   libavformat     59.22.100
   libswscale      6.6.100
   libavfilter     8.33.100
   libswresample   4.6.100
FFmpeg version: git-2022-04-15-4e98cc29

- Windows Version 10 (
- Source of the mpv binary
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

i had some mp4 over network drive playing on mpv, then i paused it, installed this https://download.vb-audio.com/Download_CABLE/VBCABLE_Driver_Pack43.zip from https://vb-audio.com/Cable/ after that it switched my default audio to that output, i switched back to my earphones, then unplugged them it switched to that cable i switched back to my headset, unblugged the usbc  hub/ dongle where headset and mouse is connected, windows switched to the cable, i switched back to speekers, i replugged usb dongle with headset and erphones, i went back to mpv, resumed playback, had no sound swiched off and on the audio layer and it crashed

### Expected behavior

no crachs but audio back

### Actual behavior

crash:
(running mpv from cygwin bash)

$ mpv [...]E{06..10}.*.mp4
 Playing: [...].mp4
 (+) Video --vid=1 (*) (h264 1356x676 24.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1356x676 => 1356x678 yuv420p
AV: 00:36:47 / 00:59:35 (62%) A-V:  0.000 Cache: 839s/149MB
Playing: [...].mp4
 (+) Video --vid=1 (*) (h264 1356x676 24.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)

[input] No key binding found for key 'n'.V:  0.000 Cache: 677s/146MB

AO: [wasapi] 48000Hz mono 1ch float7%) A-V:  0.000 Cache: 467s/101MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 467s/101MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 179s/32MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 179s/32MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 179s/32MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 157s/26MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 157s/26MB

AO: [wasapi] 48000Hz mono 1ch float6%) A-V:  0.000 Cache: 156s/26MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 156s/26MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 156s/26MB

AO: [wasapi] 48000Hz mono 1ch float6%) A-V:  0.000 Cache: 156s/26MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 156s/26MB

AO: [wasapi] 48000Hz mono 1ch float6%) A-V:  0.000 Cache: 155s/26MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 155s/26MB

AO: [wasapi] 48000Hz mono 1ch float6%) A-V:  0.000 Cache: 155s/26MB

AO: [wasapi] 48000Hz stereo 2ch float) A-V:  0.000 Cache: 155s/26MB

Track switched:01:02:09 (96%) A-V:  0.000 Cache: 154s/26MB
 (+) Video --vid=1 (*) (h264 1356x676 24.000fps)
     Audio --aid=1 (*) (aac 2ch 44100Hz)

Track switched:1:02:09 (96%) Cache: 154s/17MB
 (+) Video --vid=1 (*) (h264 1356x676 24.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)

AO: [wasapi] 48000Hz stereo 2ch float.000 Cache: 0.0s

[ao/wasapi] Error finding shared mode format: AUDCLNT_E_DEVICE_INVALIDATED (0x88890004)

[ALSOFT] (EE) Failed to check format support: 0x80070057
[ALSOFT] (EE) Failed to initialize audio client: 0x88890004
[ALSOFT] (EE) Device error: 0x88890004
[ao/openal] Direct channels aren't supported by this version of OpenAL
Segmentation fault

what apcrashivewer is showing:

Process File	Event Name	Event Time	User Name	Exception Code	Exception Code Description	Exception Offset	Fault Module Name	Fault Module Version	Process Path	Report File Size	Report File Path	
mpv.exe	Nicht mehr funktionsfähig	22.11.2023 10:47:46	All Users						C:\mpv\mpv.exe	16.886	C:\Users\All Users\Microsoft\Windows\WER\ReportArchive\AppCrash_mpv.exe_69a1e656d7fa746c4943ab3def75579ac86c6b5_7fa59a4e_83150379-82e8-4c3c-b451-1286d3464ac5\Report.wer	

﻿Version=1
EventType=APPCRASH
EventTime=133451200669363478
ReportType=2
Consent=1
UploadTime=133451200679500899
ReportStatus=268435456
ReportIdentifier=83150379-82e8-4c3c-b451-1286d3464ac5
IntegratorReportIdentifier=d0f83f3b-fceb-498b-8977-7a2ba8075b63
Wow64Host=34404
NsAppName=mpv.exe
OriginalFilename=mpv.exe
AppSessionGuid=0000dc3c-0001-0022-66c9-0b491f1dda01
TargetAppId=W:0006e3907f51be0fde64e444796e0dcc9a9400000000!0000771707f8ca5a1391105a6bb72ea5c028aade09bb!mpv.exe
TargetAppVer=1970//01//01:00:00:00!4a554c9!mpv.exe
BootId=4294967295
TargetAsId=64131
UserImpactVector=271586064
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=73f3909d7ed0ee288ac4bb9a5973e719
Response.BucketTable=4
Response.LegacyBucketId=1928872812021540633
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=mpv.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=2.0.0.0
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=00000000
Sig[3].Name=Fehlermodulname
Sig[3].Value=msvcrt.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=7.0.19041.3570
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=9bf60e04
Sig[6].Name=Ausnahmecode
Sig[6].Value=c0000005
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=000000000005db22
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=10.0.19045.2.0.0.256.48
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=9425
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=94256b10638dcd4b6e2237377fdf96fb
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=aec8
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=aec8d5c25786c73e5f09616ab9e3b563
UI[2]=C:\mpv\mpv.exe
LoadedModule[0]=C:\mpv\mpv.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\system32\hmpalert.dll
LoadedModule[3]=C:\Windows\System32\KERNEL32.dll
LoadedModule[4]=C:\Windows\System32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\System32\ADVAPI32.dll
LoadedModule[6]=C:\Windows\System32\msvcrt.dll
LoadedModule[7]=C:\Windows\System32\sechost.dll
LoadedModule[8]=C:\Windows\System32\RPCRT4.dll
LoadedModule[9]=C:\Windows\System32\bcrypt.dll
LoadedModule[10]=C:\Windows\System32\CFGMGR32.dll
LoadedModule[11]=C:\Windows\System32\ucrtbase.dll
LoadedModule[12]=C:\Windows\System32\GDI32.dll
LoadedModule[13]=C:\Windows\System32\win32u.dll
LoadedModule[14]=C:\Windows\System32\gdi32full.dll
LoadedModule[15]=C:\Windows\System32\msvcp_win.dll
LoadedModule[16]=C:\Windows\System32\USER32.dll
LoadedModule[17]=C:\Windows\System32\IMM32.dll
LoadedModule[18]=C:\Windows\System32\ole32.dll
LoadedModule[19]=C:\Windows\System32\combase.dll
LoadedModule[20]=C:\Windows\System32\OLEAUT32.dll
LoadedModule[21]=C:\Windows\System32\SETUPAPI.dll
LoadedModule[22]=C:\Windows\System32\SHELL32.dll
LoadedModule[23]=C:\Windows\System32\SHLWAPI.dll
LoadedModule[24]=C:\Windows\System32\WS2_32.dll
LoadedModule[25]=C:\Windows\SYSTEM32\AVRT.dll
LoadedModule[26]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[27]=C:\Windows\SYSTEM32\MFPlat.DLL
LoadedModule[28]=C:\Windows\System32\shcore.dll
LoadedModule[29]=C:\Windows\SYSTEM32\OPENGL32.dll
LoadedModule[30]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[31]=C:\Windows\SYSTEM32\AVICAP32.dll
LoadedModule[32]=C:\Windows\SYSTEM32\WINMM.dll
LoadedModule[33]=C:\Windows\SYSTEM32\WSOCK32.dll
LoadedModule[34]=C:\Windows\SYSTEM32\GLU32.dll
LoadedModule[35]=C:\Windows\SYSTEM32\MSVFW32.dll
LoadedModule[36]=C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.3570_none_793094a72440f60b\COMCTL32.dll
LoadedModule[37]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[38]=C:\Windows\System32\bcryptPrimitives.dll
LoadedModule[39]=C:\Windows\SYSTEM32\RTWorkQ.DLL
LoadedModule[40]=C:\Windows\SYSTEM32\windows.storage.dll
LoadedModule[41]=C:\Windows\SYSTEM32\Wldp.dll
LoadedModule[42]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[43]=C:\Windows\SYSTEM32\CRYPTBASE.DLL
LoadedModule[44]=C:\Windows\SYSTEM32\Dwrite.dll
LoadedModule[45]=C:\Windows\SYSTEM32\d3d11.dll
LoadedModule[46]=C:\Windows\SYSTEM32\dxgi.dll
LoadedModule[47]=C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_71f4b6a2a6a2e5e9\igd10iumd64.dll
LoadedModule[48]=C:\Windows\SYSTEM32\apphelp.dll
LoadedModule[49]=C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_71f4b6a2a6a2e5e9\igd10um64xe.DLL
LoadedModule[50]=C:\Windows\System32\CRYPT32.dll
LoadedModule[51]=C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_71f4b6a2a6a2e5e9\IntelControlLib.dll
LoadedModule[52]=C:\Windows\SYSTEM32\DEVOBJ.dll
LoadedModule[53]=C:\Windows\System32\WINTRUST.dll
LoadedModule[54]=C:\Windows\SYSTEM32\MSASN1.dll
LoadedModule[55]=C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_71f4b6a2a6a2e5e9\igdgmm64.dll
LoadedModule[56]=C:\Windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_71f4b6a2a6a2e5e9\igc64.dll
LoadedModule[57]=C:\Windows\SYSTEM32\dxcore.dll
LoadedModule[58]=C:\Windows\SYSTEM32\d3dcompiler_47.dll
LoadedModule[59]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[60]=C:\Windows\system32\uxtheme.dll
LoadedModule[61]=C:\Windows\System32\clbcatq.dll
LoadedModule[62]=C:\Windows\system32\dataexchange.dll
LoadedModule[63]=C:\Windows\system32\dcomp.dll
LoadedModule[64]=C:\Windows\system32\twinapi.appcore.dll
LoadedModule[65]=C:\Windows\system32\explorerframe.dll
LoadedModule[66]=C:\Windows\SYSTEM32\mscms.dll
LoadedModule[67]=C:\Windows\SYSTEM32\USERENV.dll
LoadedModule[68]=C:\Windows\SYSTEM32\ColorAdapterClient.dll
LoadedModule[69]=C:\Windows\System32\MMDevApi.dll
LoadedModule[70]=C:\Windows\SYSTEM32\AUDIOSES.DLL
LoadedModule[71]=C:\Windows\SYSTEM32\powrprof.dll
LoadedModule[72]=C:\Windows\SYSTEM32\UMPDC.dll
LoadedModule[73]=C:\Windows\SYSTEM32\resourcepolicyclient.dll
LoadedModule[74]=C:\Windows\System32\Windows.UI.dll
LoadedModule[75]=C:\Windows\System32\WindowManagementAPI.dll
LoadedModule[76]=C:\Windows\System32\TextInputFramework.dll
LoadedModule[77]=C:\Windows\System32\InputHost.dll
LoadedModule[78]=C:\Windows\SYSTEM32\wintypes.dll
LoadedModule[79]=C:\Windows\System32\CoreMessaging.dll
LoadedModule[80]=C:\Windows\System32\CoreUIComponents.dll
LoadedModule[81]=C:\Windows\System32\PROPSYS.dll
LoadedModule[82]=C:\Windows\SYSTEM32\ntmarta.dll
LoadedModule[83]=C:\Windows\System32\MSCTF.dll
LoadedModule[84]=C:\Windows\SYSTEM32\TextShaping.dll
LoadedModule[85]=C:\Windows\system32\Ninput.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=19045
OsInfo[3].Key=ubr
OsInfo[3].Value=3570
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1031
OsInfo[7].Key=geoid
OsInfo[7].Value=94
OsInfo[8].Key=sku
OsInfo[8].Value=48
OsInfo[9].Key=domain
OsInfo[9].Value=1
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=222415844
OsInfo[15].Key=osinsty
OsInfo[15].Value=1
OsInfo[16].Key=iever
OsInfo[16].Value=11.3570.19041.0-11.0.1000
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=16106
OsInfo[19].Key=svolsz
OsInfo[19].Value=466
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=191206
OsInfo[22].Key=bldtm
OsInfo[22].Value=1406
OsInfo[23].Key=bldbrch
OsInfo[23].Value=vb_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.19041.3570.amd64fre.vb_release.191206-1406
OsInfo[30].Key=buildflightid
OsInfo[31].Key=edition
OsInfo[31].Value=Professional
OsInfo[32].Key=ring
OsInfo[32].Value=Retail
OsInfo[33].Key=expid
OsInfo[34].Key=fconid
OsInfo[35].Key=containerid
OsInfo[36].Key=containertype
OsInfo[37].Key=edu
OsInfo[37].Value=0
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=mpv
AppPath=C:\mpv\mpv.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=45834744B05A35C8E22C56B2596F8141
MetadataHash=-908106922

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

i know that is a very specific issue and thereby not reproducable, but maybe you can look into mpv handling windows events about in stalling new and unplugging replugging various audio devices on the go...

**Comment by lhpitn** [comment]
i know i know, is there a way to auto update under windows?

**Comment by zhongfly** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/releases/latest
Run `updater.bat` , it will download latest mpv.

**Comment by lhpitn** [comment]
```
C:\mpv>updater
Running script with administrator privileges
Checking Windows PowerShell version -- 5
Fetching RSS feed for mpv
Der Pfad hat ein ungültiges Format.

Gewartet wird 2 Sekunden. Weiter mit beliebiger Taste...

```

Error message means sth like path is in an non valid format

**Comment by zhongfly** [comment]
The ones in this link are already new enough for mpv. The main question is whether problems occur on this version as well.

**Comment by lhpitn** [comment]
i cant reproduce it anyway...

**Comment by zhongfly** [comment]
Well, if the problem has been solved, this issue can be closed.

Regarding the use of `updater.bat`:
You can open issue at https://github.com/shinchiro/mpv-packaging/issues

**Comment by lhpitn** [comment]
i thought maybe someone who has more idea of what this could cause could run some tests but if you think its not worth your time close it...

**Comment by Dudemanguy** [comment]
Will assume this was solved.
