### ISSUE TITLE
Audio resampling questions

### ISSUE THREAD

**Issue by raziel711** [mpv-player/mpv#12942]
I am using Windows with WASAPI event mode and I have a couple of questions about how audio resampling is handled.

1. If I want mpv to handle the audio resampling, do I need to set `audio-samplerate` in my mpv.conf, or does mpv handle any resampling already with WASAPI by default?
2. Are there any reasons why the defaults for `audio-resample-filter-size` and `audio-resample-linear` are not the same as ffmpeg's default resampler settings aside from performance/speed considerations?  Also, if I did increase the filter size and use linear interpolation, would it actually have any noticeable improvement in audio quality?

**Comment by amariami** [comment]
1. `--af=format=format=srate=192000 --audio-exclusive=yes`
