### ISSUE TITLE
mpv-0.37.0: quit and save state doesn't save pause state

### ISSUE THREAD

**Issue by Thom1b** [mpv-player/mpv#12943]
- mpv 0.37.0
- Slackware current
- problem introduced since mpv 0.37.0
- KDE/Plasma 5

### Reproduction steps

1. mpv video.mp4
2. <space> to pause the video
3. <Q> to quit and save state
4. mpv video.mp4

### Expected behavior

The video should be in pause state.

### Actual behavior

The video is not in pause state. However, if mpv restore state created by a previous mpv version, the video is in pause state. If I downgrade to mpv-0.36.0 and playing a video with saving state by 0.37.0, pause state is not restored. That's why I think mpv 0.37.0 is not saving pause state.

Hope this will help. Thanks!

**Comment by christoph-heinrich** [comment]
The default watch-later-options were changed in the latest version. You can add `pause` back in with `watch-later-options-append=pause` in your mpv.conf

**Comment by Thom1b** [comment]
Oh OK, it works fine now!
Thanks a lot and sorry for the noise. Bye!

**Comment by KonoVitoDa** [comment]
> The default watch-later-options were changed in the latest version. You can add `pause` back in with `watch-later-options-append=pause` in your mpv.conf

A very unnecessary change imo, but I finally found how to fix it.
