### ISSUE TITLE
About playing small resolution videos with black all around

### ISSUE THREAD

**Issue by Invincible-World** [mpv-player/mpv#12954]
My computer's display screen has a 4k resolution, but some videos only have a resolution of 1080p. When I zoom in on a window or full screen, there is always only a small piece of display in the middle, surrounded by black. How should I change the configuration file or have any Lua script to make the resolution of playing videos smaller, while maintaining the aspect ratio of the screen and filling the player as much as possible instead of having black all around

**Comment by po5** [comment]
https://mpv.io/manual/master/#options-video-unscaled
