### ISSUE TITLE
"Could not initialize video chain." on Ubuntu 22.04.1 with mpv 0.37.0 with nvidia GTX 1060

### ISSUE THREAD

**Issue by peteygao** [mpv-player/mpv#12956]
### Important Information

Provide following Information:
- mpv version:
```
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Nov 21 2023 18:47:46
libplacebo version: v6.338.1
FFmpeg version: 6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```
- Linux Distribution and Version
Ubuntu 22.04.1
```
> uname -svo
Linux #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 GNU/Linux
```
- Source of the mpv binary
Linux Brew via:
```
> brew install mpv
```
- If known which version of mpv introduced the problem
N/A
- Window Manager and version
`GNOME Shell: GDM 42.0`
- GPU driver and version
`nvidia GTX 1060` with `Driver version: 545.23.08`
- Possible screenshot or video of visual glitches
N/A

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior

Show the mpv player window with video playback:
```
> mpv ./video.mp4
```

### Actual behavior

Only the audio plays with no mpv application window whatsoever:
Just terminal output when running MPV:
```
> mpv ~/video.mov
 (+) Video --vid=1 (*) (h264 428x720 30.000fps)
 (+) Audio --aid=1 (*) (aac 1ch 44100Hz)
AO: [pulse] 44100Hz mono 1ch float
VO: [gpu] 428x720 yuv420p
[vo/gpu/libplacebo] vk->CreateSwapchainKHR(...): VK_ERROR_UNKNOWN (../src/vulkan/swapchain.c:620)
[vo/gpu/libplacebo] Failed (re)creating swapchain!
Could not initialize video chain.
Video: no video
```

### Log file

[mpv_log.txt](https://github.com/mpv-player/mpv/files/13455886/mpv_log.txt)

### Sample files

Any video file will do.

**Comment by llyyr** [comment]
Can you try with `--gpu-debug` and vulkan validation layers?

**Comment by Traneptora** [comment]
Do you have Xpresent installed? See: https://bugs.launchpad.net/savos/+bug/1980723

**Comment by peteygao** [comment]
> Do you have Xpresent installed? See: https://bugs.launchpad.net/savos/+bug/1980723

I read that bug report thread before I posted this. The fix was supposedly shipped in a newer mpv build since 2022, so I don’t believe that’s related.

> Can you try with `--gpu-debug` and vulkan validation layers?

Same result with `--gpu-debug`:
```
> mpv --gpu-debug --log-file=./mpv_log.txt ./video.mov
 (+) Video --vid=1 (*) (h264 428x720 30.000fps)
 (+) Audio --aid=1 (*) (aac 1ch 44100Hz)
AO: [pulse] 44100Hz mono 1ch float
VO: [gpu] 428x720 yuv420p
[vo/gpu/libplacebo] vk->CreateSwapchainKHR(...): VK_ERROR_UNKNOWN (../src/vulkan/swapchain.c:620)
[vo/gpu/libplacebo] Failed (re)creating swapchain!
Could not initialize video chain.
Video: no video
```
I’m not quite sure what you mean by “vulkan validation layers” in the context of mpv 🤔. Here’s the new log with debug output:
[mpv log with --gpu-debug](https://github.com/mpv-player/mpv/files/13462182/mpv_log.txt)

**Comment by peteygao** [comment]
Closing this issue for now, given that I'm running `0.34.1` successfully and that this issue might just be a straight up incompatibility between Xorg vs. Wayland.

**Comment by llyyr** [comment]
> Is this issue because mpv >= 0.36.0 requires Wayland >= 1.20? I

mpv has both Xorg and Wayland backends, this is unrelated.

**Comment by Traneptora** [comment]
> I read that bug report thread before I posted this. The fix was supposedly shipped in a newer mpv build since 2022, so I don’t believe that’s related.

The "fix" you refer to was listing Xpresent as a dependency in dpkg. You installed via homebrew. Do you have Xpresent installed? If not, homebrew needs to list it as well.

**Comment by peteygao** [comment]
> > I read that bug report thread before I posted this. The fix was supposedly shipped in a newer mpv build since 2022, so I don’t believe that’s related.
> 
> The "fix" you refer to was listing Xpresent as a dependency in dpkg. You installed via homebrew. Do you have Xpresent installed? If not, homebrew needs to list it as well.

Happy to give that a try when I have a spare moment and report back what I find 👍🏼.

> > Is this issue because mpv >= 0.36.0 requires Wayland >= 1.20? I
> 
> mpv has both Xorg and Wayland backends, this is unrelated.

Gotcha, I stand corrected 👌🏼.

**Comment by Dudemanguy** [comment]
Your mpv was builtin without x11 and wayland support, so the result here is not surprising.
