### ISSUE TITLE
D3D11va random glitches and crashes

### ISSUE THREAD

**Issue by kungfubeaner** [mpv-player/mpv#12962]
### Important Information

Provide following Information:
- mpv version

 mpv-x86_64-v3-20231124-git-e22a2f0

- Windows Version

Windows 10 latest fully updated
Using a Radeon RX 6600 gpu with latest/current drivers 
Ryzen 5600g (integrated gpu unused, in case its relevant) 

- Source of the mpv binary

Github  Schinchiro:  20231124 

- If known which version of mpv introduced the problem

I noticed the problem in June this summer after switching to "auto" for hwdec from dxva2

### Reproduction steps

Use this config:

vo=gpu-next
gpu-api=d3d11
gpu-context=d3d11
hwdec=d3d11va

and run  mpv  "video.mp4"  --log-file=log.txt

### Expected behavior

Expect no random video glitches that last a split second or random crashes

### Actual behavior

Experience random video glitches and crashes that do not happen when using other hwdec like
Example:  dxva2, dxva2-copy, d3d11-va copy all work fine

### Log file

https://0x0.st/HwVT.txt

**Comment by kungfubeaner** [comment]
I tried two more times and keep getting under-run errors,  there are no errors when its a video glitch but when its a crash get the wasapi under run.  Last time it had two at the end  with  on  100ns and one 400ns under-run

**Comment by llyyr** [comment]
Can you try `vo=gpu`? Also try with `--aid=no`

**Comment by kungfubeaner** [comment]
I will try both and also one by one and report back.  Thanks for the help.

**Comment by kungfubeaner** [comment]
So far switching to  vo=gpu there are no more crashes.  I had one random video glitch after 18 mins of video play.  There are no errors in log file when its a video glitch though.  I'll try to add aid=no which disables audio but, for testing purposes I'll try it.

**Comment by kungfubeaner** [comment]
In the mean time,  I wonder if this has anything to do with the FFMPEG issue having to do with max slices:

Small MAX_SLICES makes d3d11va (AVC) not bitperfect and causes artifacts (but not CUDA/NVDEC)

I've read that this bug still exists in FFMpeg 6.0

**Comment by kungfubeaner** [comment]
Just got the random video glitch with  vo=gpu and aid=no.  There were no errors in the log file here:

https://0x0.st/HwWT.txt

**Comment by kungfubeaner** [comment]
Trying out the latest release fom Schinchiro from today/last night and it doesn't seem to crash anymore.  I'm watching a 3.5 hour video and it only stuttered once.  I'm guessing an underrun was bout to happen but instead of crashing the video and audio paused for a millisecond and kept on ticking not bad at all..  Maybe Its just my imagination but it seems this issue was worked on.

**Comment by kungfubeaner** [comment]
Never mind it finally randomly glitched toward the end of the video.  It seems to be a lot less of a problem now though

**Comment by kasper93** [comment]
Does `--correct-downscaling=no` improves the situation for you?

**Comment by kungfubeaner** [comment]
I'll give it a try and report back

**Comment by kungfubeaner** [comment]
Yeah the problem persisted even with --correct-downscaling=no I had to run a few errands before I tested

**Comment by kungfubeaner** [comment]
The latest AMD Radeon driver from 01/2024 seems to have fixed the d3d11va issues.  Maybe it had something to do with VRR who knows.  Going to test for a couple more hours and close this issue after I completely confirm the issue is gone.

**Comment by kasper93** [comment]
Note that 23.12.1 drivers were broke, they had memory corruption in driver. This probably not related to your original issue, but looks like it is also fixed in 24.1.1. Related Firefox issue https://bugzilla.mozilla.org/show_bug.cgi?id=1874474

**Comment by kungfubeaner** [comment]
Yeah seems that something in the code the fixed also fixed this problem in MPV so I'll go ahead and close this.  Thanks for the info.
