### ISSUE TITLE
Optimal rendering of white subtitles for any video background

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#12961]
Using plain white subtitles work fine most of the time.

But the (relatively) few times the video behind is (near-)white, they obviously become illegible.

- Adding a thin transparent black font border helps, but this border has no purpose the rest of the time.
- Adding a transparent background also helps, but is a major visual intrusion.

```
sub-border-color='#33000000'
sub-border-size=1 # font border
```

Two questions:

1. With the current version of mpv, which are the best option values for white subtitles that are as invisible as possible when not needed, and only as visible as needed when required?
2. Would it be possible to make the subtitle renderer more intelligent, ie. trace its surrounding background and render the necessary minimum to make the subtitle stand out?

**Comment by Traneptora** [comment]
> With the current version of mpv, which are the best option values for white subtitles that are as invisible as possible when not needed, and only as visible as needed when required?

Subtitles that dynamically change with the content would have to be mastered to do that. mpv relies on libass to render subtitles which renders exactly as it is told. You'd have to make those kinds of decisions when you create the subtitle file.

> Would it be possible to make the subtitle renderer more intelligent, ie. trace its surrounding background and render the necessary minimum to make the subtitle stand out?

There's no need to come up with methods for rendering subtitles that deviate from spec and that most users would hate.

FWIW, a black border around white subtitles renders fine on all content, not sure why that isn't sufficient.

**Comment by forthrin** [comment]
Yes, I assumed that the subtitle renderer has no concept of its background, and am not surprised if doing so would be a major new undertaking for a not so huge benefit.

For trained eyes used to work with fonts, a border is visible and ugly (and most times unnecessary), even when 1px and transparent. But feel free to share your best settings if you have managed to conjure up some non-intrusive magic.

**Comment by N-R-K** [comment]
The subtitle itself is already far more intrusive than the border. As an mpv trained viewer™ and an aspiring harman trained listener™, I prefer to turn subtitles off and listen with my ears instead of my eyes.

**Comment by forthrin** [comment]
I asked for options, not opinions 🙃

**Comment by llyyr** [comment]
> With the current version of mpv, which are the best option values for white subtitles that are as invisible as possible when not needed, and only as visible as needed when required?

Use a drop shadow or borders.

> Would it be possible to make the subtitle renderer more intelligent, ie. trace its surrounding background and render the necessary minimum to make the subtitle stand out?

Yes, patches welcome.

**Comment by Jules-A** [comment]
I went with ```sub-border-color="#808080"
sub-border-size=1.5
sub-shadow-offset=2
sub-shadow-color="#000000"
sub-ass-override=no```

I thought black would be fine but it's actually annoying sometimes so I went with grey, only problem is it looks bad on grey backgrounds but that's way rarer than on black.

**Comment by forthrin** [comment]
I made this script to find values most resilient against white background (rare), and as invisible as possible for colored background (most times). Admittedly, the test video is a not-so-representative extreme test case. General findings:

- The smaller the border size, the higher the border alpha must be
- Background box is very effective, but intrusive for normal backgrounds
- Shadow is too intrusive for normal backgrounds
- Final settings found were `sub-border-color='#80000000'` and `sub-border-size=0.75`

If someone finds something even better, do post back here.

- PS! If someone has a less repetitive way of writing toggle scripts like this in Lua, please do tell!
- PPS! ASS crashes if passing negative border size.
`(rad >= eps && rad <= OUTLINE_MAX), function ass_outline_stroke, file ass_outline.c, line 1498.`

```cfg
# values used for testing
sub-back-color='#00000000' # background box color
sub-shadow-color='#00000000'
sub-shadow-offset=8 # hack for box padding
sub-border-color='#80000000'
sub-border-size=0.75 # font border
```

```lua
local h = 128
local k = 0
local y = 0.75
local n = 0

function set()
  local f = string.format("#%02x%02x%02x%02x", h, k, k, k)
  mp.set_property('sub-border-color', f)
  mp.set_property('sub-border-size', y)
  local g = string.format("#%02x%02x%02x%02x", n, 0, 0, 0)
  mp.set_property('sub-back-color', g)
  mp.osd_message(f .. ' / ' .. y .. ' / ' .. n)
end

function hp()
  h = math.min(h + 4, 255)
  set()
end

function hm()
  h = math.max(h - 4, 0)
  set()
end

function kp()
  k = math.min(k + 4, 255)
  set()
end

function km()
  k = math.max(k - 4, 0)
  set()
end

function yp()
  y = math.min(y + 0.25, 255)
  set()
end

function ym()
  y = math.max(y - 0.25, 0)
  set()
end

function np()
  n = math.min(n + 4, 255)
  set()
end

function nm()
  n = math.max(n - 4, 0)
  set()
end

mp.add_key_binding('h', nil, hp, {repeatable=true})
mp.add_key_binding('H', nil, hm, {repeatable=true})
mp.add_key_binding('k', nil, kp, {repeatable=true})
mp.add_key_binding('K', nil, km, {repeatable=true})
mp.add_key_binding('y', nil, yp, {repeatable=true})
mp.add_key_binding('Y', nil, ym, {repeatable=true})
mp.add_key_binding('n', nil, np, {repeatable=true})
mp.add_key_binding('N', nil, nm, {repeatable=true})

```

**Comment by Dudemanguy** [comment]
Seems solved by a script.
