### ISSUE TITLE
mpv doesn't fallback to software decoding with 10-bit H.264 videos when using --hwdec=auto-safe

### ISSUE THREAD

**Issue by dokur0chan** [mpv-player/mpv#12964]
### Important Information
```
mpv v0.37.0-8-ge575ec4f Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Nov 23 2023 00:33:12
libplacebo version: v6.338.0-60-g795600a-dirty
FFmpeg version: N-112829-g0008e1c5d
FFmpeg library versions:
   libavutil       58.32.100
   libavcodec      60.34.100
   libavformat     60.17.100
   libswscale      7.6.100
   libavfilter     9.13.100
   libswresample   4.13.100
```
- Windows 11 Build 22631.2506
- shinchiro's binaries
- Possible regression? #12847

### Reproduction steps

Launch any 10-bit H.264/AVC encode with `--hwdec=auto-safe`

### Expected behavior

Video launches and falls back to software decoding, because 10-bit H.264 can't be hardware decoded.

### Actual behavior

mpv crashes.

```
Cannot load nvcuda.dll
[ffmpeg] AVHWDeviceContext: Cannot load nvcuda.dll
[ffmpeg] AVHWDeviceContext: Could not dynamically load CUDA
```

Same thing happens with codecs like VP8.

Same error occurs with `--hwdec=auto` and `--hwdec=yes`.

Specifying a decoder (like `--hwdec=d3d11va`) solves this issue, with mpv properly falling back to software decoding.
### Log file
[itsover.log](https://github.com/mpv-player/mpv/files/13462648/itsover.log)

**Comment by philipl** [comment]
Thanks @Andarwinux. The issue here is the new vaapi-win32 support (you can see it in the logs). It appears the vaapi-win32 driver doesn't have a destroy callback, so the change in #12951 address that.
