### ISSUE TITLE
mpv 0.37.0 - Can't use the latest vulkan-sdk version - complains about libglslang

### ISSUE THREAD

**Issue by 0pLuS0** [mpv-player/mpv#12969]
### Important Information

Provide following Information:
- mpv version - ```0.37.0```
- ffmpeg version - ```ffmpeg-5.1.3```
- Linux Distribution and Version - ```Slackware 15.0```
- Source of the mpv binary - ```Compiled 0.37.0 from source```
- If known which version of mpv introduced the problem - ```vulkan-sdk-1.3.268```
- Window Manager and version - ```Openbox 3.6.1```
- GPU driver and version - ```nvidia-driver-535.113.01```
- Possible screenshot or video of visual glitches - ```N/A```

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

```Running mpv --no-config does nothing, because this is an incorrect lib version issue.```

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
```Be able to use the latest vulkan-sdk?```

```Slackware does not have glslang, the only version comes from vulkan-sdk.``` 

```vulkan-sdk-1.3.268.0 has libglslang.so.13.1.1```

```When I compile mpv 0.37.0 it shows it's compiling against vulkan-sdk-1.3.268, so why won't it use the latest libglslang? Here's the terminal output of this;  Run-time dependency vulkan found: YES 1.3.268.```

```I compiled vulkan-sdk-1.3.268 from source and then compiled mpv against it.```

### Actual behavior
```When trying to use vulkan-sdk-1.3.268 mpv complains;```
```mpv: error while loading shared libraries: libglslang.so.11: cannot open shared object file: No such file or directory```

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

```It won't create a log file, because it can't load the correct libglslang.so.11 version. I ran mpv --log-file=output.txt and then it just spits out the error message and no log is created.```

```mpv: error while loading shared libraries: libglslang.so.11: cannot open shared object file: No such file or directory```

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

```THANKS```

**Comment by kasper93** [comment]
> I compiled vulkan-sdk-1.3.268 from source and then compiled mpv against it.

You have to add built libraries to `PATH` so mpv process can find them.

**Comment by 0pLuS0** [comment]
PATH isn't the problem...

I compiled ffmpeg-5.1.4 and now it works!

**Comment by 0pLuS0** [comment]
Here's a screen shot/eye candy with mpv-0.37.0 with vulkan-sdk-1.3.268, and ffmpeg-5.1.4 in action!

```MPV is amazing, thanks for everything and keep up the great work!```

![openbox-mpv](https://github.com/mpv-player/mpv/assets/36190223/d3675a9e-4bfb-4c82-90e5-9c6f11769fce)
