### ISSUE TITLE
How to make a pull request according to the contribution guidelines

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#12972]
The contribution guidelines state:

> ### Always squash fixup commits when making changes to pull requests
> 
> - If you make fixup commits to your pull request, you should generally squash them with "git rebase -i". We prefer to have pull requests in a merge ready state.
> - We don't squash-merge (nor do we use github's feature that does this) because pull requests with multiple commits are perfectly legitimate, and the only thing that makes sense in non-trivial cases.

I probably don't understand most of it.

There is a pull request I recently made, it has one commit, can I add another commit, or is only one commit allowed?

**Comment by christoph-heinrich** [comment]
You can have multiple commits, but if you want to fix a mistake in one of those commits you shouldn't create a fixup commit and instead change that commit itself.

**Comment by stax76** [comment]
> You can have multiple commits, but if you want to fix a mistake in one of those commits you shouldn't create a fixup commit and instead change that commit itself.

That I could understand much better, thanks. Is it difficult to change an existing commit? Most of the time, when I google something about git, I understand not much of the explanations I read.

**Comment by guidocella** [comment]
`git commit --amend` updates the last commit.

**Comment by Traneptora** [comment]
You can also use `git commit -m fixup` to create a new commit with the simple commit message "fixup" (or whatever). Then you can use `git rebase -i master` to move around or squash commits that have come since the last one on the master branch. You can change the fixup commit to "f" to squash it into the previous one and discard its message.
