### ISSUE TITLE
Cached time (or display) decreses throughout playback 

### ISSUE THREAD

**Issue by SacredZenpie** [mpv-player/mpv#12976]
- mpv-x86_64-20231126-git-6898d5
- Windows 10
- Shinchiro 

```
cache=yes
demuxer-max-bytes=180MiB
demuxer-max-back-bytes=20MiB
demuxer-donate-buffer=no
```
Using the above settings I lose cached time as playback goes. After both back cache and forward cache get filled, as the video continues, the cached seconds (as reported by OSD and OSC) constantly decrease. 
Is this expected behavior and I just lack understanding of MPVs cache, is this just a fault of how the cached time is reported or is this an actual cache bug? 

Example: 
- I open a 1.34gb video 24 mins video, after it plays for a minute the cache time shows 3m10s (both caches are at their size limits)
- at 3 minute mark, the cached time displays 2m46s (the cache sizes did not change)

### Expected behavior
Id expect the cached time to remain the same throughout the whole playback (not counting the start and end of course) 

### Actual behavior
The cached time (or display) decreases

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/13468162/mpv.log)

**Comment by llyyr** [comment]
> Id expect the cached time to remain the same throughout the whole playback (not counting the start and end of course)

Why would you expect that? The bitrate of the video can change such that the same cache _size_ leads to a different cached video length.

**Comment by Traneptora** [comment]
Well if the file doesn't have constant bitrate then the same amount of bytes will correspond to different lengths of time.

**Comment by SacredZenpie** [comment]
It was a indeed a me skill issue, I forgot to take bitrate into account, apologies for wasting your time.
