### ISSUE TITLE
[proposed scripting:ytdl-hook] Show "most replayed" heatmap/statistics chart in/above status line/progress bar

### ISSUE THREAD

**Issue by alopatindev** [mpv-player/mpv#12975]
### Expected behavior of the wanted feature
Most watched aka Hotspot graph:
![Screenshot-20231126-205312_chrome](https://github.com/mpv-player/mpv/assets/415408/1e786858-c9fa-4a87-bfdf-dd2c202a48dc)

Extractable with
```bash
yt-dlp --print '%(heatmap)j' 'https://www.youtube.com/watch?v=BIO8elqCBOs'
```

**Comment by zhongfly** [comment]
This is the job of the osc, the mpv has only the simplest function of osc built in, you need to find or write a custom osc script to achieve this function.

**Comment by alopatindev** [comment]
> here are two examples (noob paint.exe):

Both look cool. I like the first option more, because it's easy (without making affecting the rest of visual design) to make it tall enough, to be easily perceived from any distance. The black rectangular background is unnecessary in my opinion.

The heatmap itself can also be partially transparent.

[Gradient](https://github.com/cyl0/ModernX/blob/d053ea602d797bdd85d8b2275d7f606be067dc21/preview.png)-like upwards transparency is probably unnecessary for this relatively minimalistic visual design and (also this needs extra computational work).

Also heatmap progress highlighting can be implemented to indicate current (or future, after hover and click) progress:

![Screenshot-20231127-003932_feh](https://github.com/mpv-player/mpv/assets/415408/b790044f-7f76-438a-9a7a-50a695fd86db)

**Comment by alopatindev** [comment]
> mpv has only the simplest function of osc built in, you need to find or write a custom osc script to achieve this function

Good point, thanks. Besides osc `yt-dlp` response parsing is needed. It would be awesome to have it as part of `mpv/player/lua/ytdl_hook.lua` (instead of calling `yt-dlp` again from the custom script, repeating similar `yt-dlp` prelude code and so on).

However, it's not necessary to call `yt-dlp` with `--print '%(heatmap)j'` by default; allowing user (or custom script itself) overriding something like `ytdl-raw-options` would be sufficient.

**Comment by Dudemanguy** [comment]
This would be a feature for a separate script not core mpv.
