### ISSUE TITLE
ffmpeg 6.1 breaks MPV streaming radio

### ISSUE THREAD

**Issue by AndyM48** [mpv-player/mpv#12973]
### Versions

```
 mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Sun Jul 23 05:49:29 2023
libplacebo version: v5.264.1
FFmpeg version: n6.0
FFmpeg library versions:
   libavutil       58.2.100
   libavcodec      60.3.100
   libavformat     60.3.100
   libswscale      7.1.100
   libavfilter     9.3.100
   libswresample   4.10.100
```

Arch Linux 6.6.2

Source: Arch extra repository
Problem introduced by upgrade from ffmpeg 6.0-13 to 6.1-1
Window Manager: Openbox 3.6.1

### Reproduction steps

Upgrade ffmpeg to 6.1 and stream radio

### Expected behavior
Radio streams:
```
 (+) Audio --aid=1 (aac 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
A: 00:15:08 / 00:15:08 (97%) Cache: 20s/316KB
```
### Actual behavior
Radio stops streaming: 
```
 (+) Audio --aid=1 (aac 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
A: 00:15:08 / 00:15:08 (100%) Cache: 0.0s
```
### Log file

Let me know if a log file is needed. I will have to upgrade ffmpeg again and lose my radio :)

**Comment by llyyr** [comment]
I'm on ffmpeg git and `m3u` work just fine, you need to provide logs, a sample stream, and try seeing if ffplay from the 6.1 package can play your stream

**Comment by AndyM48** [comment]
Logfile:
[output.txt](https://github.com/mpv-player/mpv/files/13466248/output.txt)

ffplay is running now, I will let you know if it stops.

**Comment by AndyM48** [comment]
One error so far:
![image](https://github.com/mpv-player/mpv/assets/3006039/0eec31bc-a64b-49aa-a40f-70f11b344c65)
Plat continues...

**Comment by AndyM48** [comment]
ffplay stopped - no specific error - restarted.

**Comment by AndyM48** [comment]
Tried to restart but now getting 403 error:
```
$ ffplay  http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d96000.norewind.m3u
ffplay version n6.1 Copyright (c) 2003-2023 the FFmpeg developers
  built with gcc 13.2.1 (GCC) 20230801
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[http @ 0x7efd1c001400] HTTP error 403 ForbiddenB sq=    0B f=0/0   
http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d96000.norewind.m3u: Server returned 403 Forbidden (access denied)
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
```
I will try again later, but cannot do anything for the moment - it's The Archers  :)

**Comment by AndyM48** [comment]
Playback with ffplay is stopping and starting from time to time, with "aq= 0KB" on the play line.

Going back to ffmpeg 6.0 with MPV now, which is rock solid.

**Comment by llyyr** [comment]
If it also happens then ffplay then it's most likely an issue with ffmpeg, you'd need to report a bug over there

**Comment by AndyM48** [comment]
> If it also happens then ffplay then it's most likely an issue with ffmpeg, you'd need to report a bug over there

No, I don't believe that it is a problem with ffmpeg. If I enter the right URL ffplay seems to work correctly. The problem is with MPV and ffmpeg 6.1.

**Comment by llyyr** [comment]
Can you provide a sample stream? How long does it take for the stream to stop buffering?

**Comment by sfan5** [comment]
I just had the exact m3u stream you used running for 7 minutes no issues, with ffmpeg 6.1 and mpv 6898d57d98f1dbe2253585d39a8fa7b57a04d273.
It might not be ffmpeg's issue but it doesn't look like ours either.

Also note that 0.36.0 is unsupported.

**Comment by AndyM48** [comment]
The radio 4 stream I am using is
`http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d48000.norewind.m3u8`
The stream stops after ; sometimes a few minutes, sometimes longer, maybe as long as an hour?

I don't think the ffplay problem was the same, I think there were some problems with the network at that time. The MPV playback problems are definitely not internet problems, they are too consistent and have been apparent since four days now. 

As background info I live in a small village in France and they tend to work on the internet network over the weekends.

If you like I will run ffplay again tomorrow to confirm that it is stable.

**Comment by AndyM48** [comment]
> Also note that 0.36.0 is unsupported.

What is this?

**Comment by sfan5** [comment]
mpv version 0.37.0 was released [a few days ago](https://github.com/mpv-player/mpv/releases). As is written in the issue template we only accept bug reports for the latest version or builds from git.

**Comment by llyyr** [comment]
I got the freeze after 36 minutes on ffmepg-git, reloading the playlist or seeking fixes it

`[ffmpeg/demuxer] hls: skipping 37 segments ahead, expired from playlists`

**Comment by llyyr** [comment]
After testing it a bunch, I'm quite positive this happens because of https://github.com/FFmpeg/FFmpeg/commit/5f810435c2a6d985fabd9e6c025e0da0c99c39a9

Running mpv with `--demuxer-lavf-o=max_reload=1000`, I haven't had it stop buffering for 40+ minutes now with ffmpeg 6.1

**Comment by AndyM48** [comment]
Thank you. No problems with playback this morning :)
