### ISSUE TITLE
LIBMPV - input.conf not loading

### ISSUE THREAD

**Issue by martinrotter** [mpv-player/mpv#12983]
Hello guys.

Integrating libmpv into RSS Guard (feed reader) for podcast reading ability.

I use "mpv_set_option_string" API method like this:

```cpp
  mpv_set_option_string(
      mpv, "config-dir",
      "c:\\Users\\user\\mpv-config-files\\");
```

Inside "mpv-config-files" I have some fairly minimal "input.conf" file just for testing. Yet, it seems that libmpv somehow does not load the file because when hitting sample assigned keyboard button, I get

`[input] No key binding found for key 'p'.`

error. Yet when I do directly this:

```cpp
  mpv_set_option_string(
      mpv, "input-conf",
      "c:\\Users\\user\\mpv-config-files\\input.conf");
```

then config is loaded and shortcuts do work. Not a clue what I do wrong.

**Comment by stax76** [comment]
I'm not sure what is missing, maybe `SetPropertyString("config", "yes");`

In mpv.net: https://github.com/mpvnet-player/mpv.net/blob/main/src/MpvNet/Player.cs#L98

**Comment by martinrotter** [comment]
Thanks for help, it was that. I have other question, will create separate ticket? Or are devs responsive somewhere on discord?
