### ISSUE TITLE
Using mpv with Vulkan without shaderc?

### ISSUE THREAD

**Issue by shmerl** [mpv-player/mpv#12982]
According to documentation (man page), using `--gpu-api=vulkan` seems to be relying on shaderc as a SPIR-V compiler, as note for `--spirv-compiler=<compiler>` says:

```
              NOTE:
                 This option is deprecated, since there is only one reasonable value.  It may be removed in the future.
```

However I managed to run mpv without shaderc using Vulkan, and libplacebo seems to be compiling shaders into SPIR-V just fine. So may be this note is incorrect?

Here is some of what I see when running with `--msg-level=all=debug`:

```
[vo/gpu-next/vulkan] Initializing GPU context 'waylandvk'
...
[vo/gpu-next/libplacebo] Spent 2.067 ms creating vulkan instance
...
[vo/gpu-next/libplacebo] Requested alpha compositing mode: VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR
[vo/gpu-next/libplacebo] Requested surface transform: VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR
...
[vo/gpu-next] Loading hwdec driver 'vaapi'
...
[vo/gpu-next/libplacebo] vertex shader source:
[vo/gpu-next/libplacebo] [  1] #version 450
...
[vo/gpu-next/libplacebo] [ 38]
[vo/gpu-next/libplacebo] [ 39] void main() {
[vo/gpu-next/libplacebo] [ 40] out_color = _1();
[vo/gpu-next/libplacebo] [ 41] }
[vo/gpu-next/libplacebo] Spent 0.796 ms translating SPIR-V
[vo/gpu-next/libplacebo] Spent 0.802 ms translating SPIR-V
[vo/gpu-next/libplacebo] Spent 0.004 ms compiling shader
[vo/gpu-next/libplacebo] Spent 0.070 ms creating pipeline
[vo/gpu-next/libplacebo] Pass statistics: size 0, SPIR-V: vert 0 frag 0 comp 0
```

Here is my configuration in `$HOME/.config/mpv/config`

```
[gpu-vulkan]
vo=gpu-next
gpu-api=vulkan
hwdec=vaapi
gpu-context=waylandvk

[default]
profile=gpu-vulkan
```

Mpv version:
```
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
libplacebo version: v6.338.1
FFmpeg version: 6.1-3
FFmpeg library versions:
   libavutil       58.2.100 (runtime 58.29.100)
   libavcodec      60.3.100 (runtime 60.31.102)
   libavformat     60.3.100 (runtime 60.16.100)
   libswscale      7.1.100 (runtime 7.5.100)
   libavfilter     9.3.100 (runtime 9.12.100)
   libswresample   4.10.100 (runtime 4.12.100)
```

**Comment by sfan5** [comment]
First off, how did you determine that your mpv is built without shaderc?

From a quick look at the source the mpv directly uses shaderc only from [ra_d3d11](https://github.com/mpv-player/mpv/blob/master/video/out/d3d11/ra_d3d11.c). This likely changed sometime during the integration of libplacebo.
In that case libplacebo is interfacing with shaderc and mpv needs not to be built with it.

**Comment by shmerl** [comment]
In my case it's on Debian testing and shaderc isn't installed. So yeah, I'd guess it's libplacebo compiling shaders without it.

**Comment by sfan5** [comment]
1b035402a688a5d116a9014e8930d7863481eeed
