### ISSUE TITLE
Save A-B loops in watch_later files.

### ISSUE THREAD

**Issue by AziRizvi** [mpv-player/mpv#12984]
When the watch_later files are being written for a file, is it possible to save an A-B loop or multiple A-B loops inside it which can then be subsequently loaded up when a file is relaunched again?

If there is no way to currently do this, can this feature be requested?

**Comment by christoph-heinrich** [comment]
`--watch-later-options-append=ab-loop-a --watch-later-options-append=ab-loop-b`

**Comment by christoph-heinrich** [comment]
> Just to clarify, this writes the A point the opening point and the B point that's the closing point, correct?

If you mean the video starts at A when you open it and ends at B, then no. If you mean that the loop starts at A and ends at B then yes.

> Is there no way to save multiple loops?

No.

**Comment by guidocella** [comment]
> Is there no way to save multiple loops?

https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst
