### ISSUE TITLE
libmpv: Hiding parent window closes the player

### ISSUE THREAD

**Issue by martinrotter** [mpv-player/mpv#12995]
I integrate libmpv into C++ application based on Qt libs.

There is some thing happening: my application uses tray icon and user is able to "close" its windows but app is still running. This is technically done in a "Qt way" where windows are not in fact closed but are "hidden" and can be reopened later. No objects are "delete-d" from memory - window is just hidden.

When there is "container" widget in that window and window gets "hidden", then the "mpv_handle" receives "MPV_EVENT_SHUTDOWN" even when the parent window was not actualy close (see above paragraph) -> thus this results in playback being stopped and relevant structs de-initialised.

I was not able to find what is actually causing this, may it be that libmpv "listens" somewhere for "close event" end de-initialises when it should not?

Thanks for help.

**Comment by kasper93** [comment]
We need log and/or the small test case to help. We don't really have a way to guess what is happening, what window messages your application send to mpv child window. Is "Qt way" destroying the native windows maybe and recreate based on internal state? If either `WM_CLOSE`, `WM_NCDESTROY`, `WM_DESTROY` is received by mpv window it will close the player. Maybe it should go into gui less mode, but this is not the case currently.

**Comment by martinrotter** [comment]
Yes, nevermind, I fixed issue by NOT closing parent window and properly hiding it instead. Sorry for false alarms.
