### ISSUE TITLE
Is there any method to let command "dump-cache" dump external audio track with video?

### ISSUE THREAD

**Issue by CharlesChou73** [mpv-player/mpv#12991]
<details>
<summary>Backgroud info about why I have this problem</summary>

[bilibili.com](https://www.bilibili.com/) is a Chinese online video site.

In this site, the video and audio track is in seperated file, and the player combines them.

I use the Tampermonkey script [Play-With-MPV](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv) to play the video in mpv as a stream. The script trans both video and audio track url to mpv, and it works well.
</details>

As is stated above, I play a video stream with seperated audio track.

And when I run the followed script in mpv console
```
dump-cache 0 10 f:/file.mp4
```
I get a video file with no audio track.

Is that expected? Is there anything I can do to dump both video and audio track?

**Comment by zhongfly** [comment]
https://mpv.io/manual/master/#command-interface-dump-cache

**Comment by CharlesChou73** [comment]
Thanks for you answer.

I used to want an all-in-one solution, but it seems impossible. I'll try yt-dlp.

**Comment by zhongfly** [comment]
Maybe other scripts can do this, but I don't know much about it.
