### ISSUE TITLE
What is the difference between `bicubic` and `bicubic_fast`?

### ISSUE THREAD

**Issue by Carl-Robert** [mpv-player/mpv#12992]
There is no mention about this in the manual nor did a search through DDG and this issue tracker provide any information.

I guess `bicubic_fast` has the B and C parameters hardcoded? But to which values? `bicubic` defaults to B=1, C=0 (which I prefer). Does `bicubic_fast` have the same values?

Are there any missing features or quality concerns when using `bicubic_fast`? I suppose if there isn't, then it should be preferred to `bicubic` if the B and C values doesn't differ.

Thanks for taking the time to clarify this.

**Comment by sfan5** [comment]
relevant code: https://github.com/mpv-player/mpv/blob/f7402ff466d1426bd99eaac546d53708cc14c8b3/video/out/gpu/video_shaders.c#L252-L289
