### ISSUE TITLE
Auto pause when mouse is over the lower part of the screen.

### ISSUE THREAD

**Issue by NeonGooRoo** [mpv-player/mpv#12997]
I want an option that would make the video stop automatically when the mouse is hovered in the lower section of the screen, usually where the subtitles are. Preferably it would allow to chose how big the lower part that would make the video pause be.

I am sorry if this feature already exists, I struggled to find it in documentation or on forums

**Comment by KaFu74** [comment]
Here's a lua script which can do that. Copy it to your "scripts" directory and the movie should pause when the mouse is in the lower 10% of the displayed area.

[Pause_on_MousePos.zip](https://github.com/mpv-player/mpv/files/13489914/Pause_on_MousePos.zip)
