### ISSUE TITLE
Add username/password support to youtube-dl integration

### ISSUE THREAD

**Issue by m45t3r** [mpv-player/mpv#1299]
I am trying to use the recently support of youtube-dl to stream Animes from my premium account of Crunchyroll. I can do this using youtube-dl directly, by passing the parameters ```--username``` and ```--password```. But mpv doesn't seem to support any of those parameters, so I can only stream free media from Crunchyroll.

So it would be interesting to have two new parameters, like ```--ytdl-username``` and ```--ytdl--password``` that only send the corresponding parameters to youtube-dl. Maybe even more interesting would be to add something like ```--ytdl-parameters``` and allow the user to pass any custom parameters to youtube-dl directly, at the expense of (possibly) breaking things.

**Comment by ChrisK2** [comment]
Implemented with 633147c9596177d42d9651aaf101a426d754cb7c.
