### ISSUE TITLE
about watch live

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#13008]
When watching the live broadcast, I feel that the video is very vague. I can see pixels, which seems to be much worse than Potplayer. Is it wrong with me?

**Comment by CounterPillow** [comment]
we can't tell because you included absolutely zero information. If you want to report an issue, don't select the question template

**Comment by CounterPillow** [comment]
> That’s it, there are no logs.

Use --log-file=mpv.log to generate them.

Without a log we have no idea what settings you use, or what version you use.
