### ISSUE TITLE
[Question]: How to move and resize a mpv window?

### ISSUE THREAD

**Issue by ahaoboy** [mpv-player/mpv#13004]
Geometry can only be used to adjust the initial position and size of the window. Setting the geometry value after the window has been initialized won't take effect. So, is there any way to move and resize the window in pixel units while playing a video?
```c
  mpv_set_property_string(ctx, "geometry", "0:0");
  const char *cmd[] = {"loadfile", argv[1], NULL};
  check_error(mpv_command(ctx, cmd));
  Sleep(2000);
  mpv_set_property_string(ctx, "geometry", "100:100");

```

I tried using a js script, but it didn't work either.

```js
let w = 100;
let h = 100;
let x = 10;
let y = 10;
mp.add_key_binding('ctrl+a', 'move-left', () => {
  const s = `${w}%x${h}%+${x}+${y}`;
  print('geometry', s);
  mp.set_property_native('geometry', s);
  x += 50;
});

```

**Comment by Akemi** [comment]
it's not implemented for every platform/backend, see https://github.com/mpv-player/mpv/issues/8379 https://github.com/mpv-player/mpv/pull/8383
