### ISSUE TITLE
update.bat broke with windows 23h2

### ISSUE THREAD

**Issue by marat569** [mpv-player/mpv#13002]
### Important Information

Provide following Information:
- mpv version  mpv-x86_64-20231112-git-7cab30c
- Windows Version 23h2 
- Source of the mpv binary -- mpv-x86_64-20231112-git-7cab30c.7z
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches
[https://i.imgur.com/LAPOIfs.png](https://i.imgur.com/LAPOIfs.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

run update.bat
[https://i.imgur.com/LAPOIfs.png](https://i.imgur.com/LAPOIfs.png)

### Expected behavior

the program would well update

### Actual behavior

I get an error saying Open ERROR: Cannot open the file as [7z] archive

### Log file

its update

The issue will be closed for ignoring the issue template.

### Sample files

update.bat and the .ps1 script is all default, hasn't been changed

I also have 7z installed, even got the latest version; but idk for some reason updater.bat doesn't work

**Comment by CounterPillow** [comment]
This script is not part of the upstream mpv project but provided by the person who makes your windows builds. Please do not report issues with it to the mpv project.

**Comment by marat569** [comment]
Sorry

Where can I report it properly?
