### ISSUE TITLE
Set fs-screen-name with Windows Hardware IDs

### ISSUE THREAD

**Issue by sean-mcgauley** [mpv-player/mpv#13010]
### Expected behavior of the wanted feature
MPV plays fullscreen on the listed monitor linked to the ID found in Device manager > Monitor > Details > Hardware IDs  by using fs-screen-name.

**Comment by Dudemanguy** [comment]
Would be fixed by https://github.com/mpv-player/mpv/pull/11543.

**Comment by sean-mcgauley** [comment]
So if I’m understanding correctly
