### ISSUE TITLE
How to launch a video on the background?

### ISSUE THREAD

**Issue by in-plaintext** [mpv-player/mpv#13027]
When benchmarking or troubleshooting video playback (by logging to a file),  the mpv window can be a nuisance when all relevant information is printed to the terminal or written to a log file. 

 Disabling the video track altogether with `--no-video` isn't a solution in this case, naturally.  Launching outside of the graphical environment, with say cron, may not be comparable to any real desktop session.

Does mpv have any dedicated flag for this specific purpose?

---

Linux, Wayland

**Comment by llyyr** [comment]
`vo=null`

**Comment by in-plaintext** [comment]
$ mpv --vo=help
```
Available video outputs:
  gpu              Shader-based GPU Renderer
  gpu-next         Video output based on libplacebo
  vdpau            VDPAU with X11
  wlshm            Wayland SHM video output (software scaling)
  xv               X11/Xv
  sdl              SDL 2.0 Renderer
  dmabuf-wayland   Wayland dmabuf video output
  vaapi            VA API with X11
  x11              X11 (software scaling)
  libmpv           render API for libmpv
  null             Null video output
  image            Write video frames to image files
  tct              true-color terminals
  drm              Direct Rendering Manager (software scaling)
  sixel            terminal graphics using sixels
  kitty            Kitty terminal graphics protocol
```
