### ISSUE TITLE
How to hide the mpv icon when no video playing

### ISSUE THREAD

**Issue by Ptilopsis01** [mpv-player/mpv#13025]
I wonder how to hide the mpv icon when opening mpv with no video playing.

Is there any attibute can do this?

**Comment by Ptilopsis01** [comment]
> Log?

[mpv.log](https://github.com/mpv-player/mpv/files/13536901/mpv.log)

**Comment by llyyr** [comment]
Obviously it doesn't work, you're using uosc not the default osc. Go here https://github.com/tomasklaen/uosc/issues/

**Comment by llyyr** [comment]
You're also using some osc called `modernf.lua`.

Try `mpv --no-config --force-window --idle --script-opts=osc-idlescreen=no` from the command line, if the mpv logo isn't there then it works properly. Anything else isn't an mpv issue, but an issue with your specific setup

**Comment by Ptilopsis01** [comment]
I understand, it's the problem of my osc
thx very much
