### ISSUE TITLE
Adding python path to $env:PATH just for MPV 

### ISSUE THREAD

**Issue by lalishansh** [mpv-player/mpv#13024]
I'm trying to setup VapourSynth and am trying to use a different version than my system python (a.k.a embedded portable python).

Is there a way to do so ??

Currently, I have python path to environment:path in a bat script which lanches mpv.

Though it has become pain to setup by creating symlinks(of mpv) and bat files.

Hoping for better solution.

**Comment by zhongfly** [comment]
https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Setup-vapoursynth-for-mpv

**Comment by lalishansh** [comment]
> [Wiki: Setup vapoursynth for mpv (shinchiro/mpv-winbuild-cmake)](https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Setup-vapoursynth-for-mpv)
> 
> > Download the embeddable file and extract it in same folder as mpv.exe.

so using same dir as **MPV**, but wouldn't help if you have **mpv** installed via chocolatey 🤔

**Comment by AziRizvi** [comment]
> > [Wiki: Setup vapoursynth for mpv (shinchiro/mpv-winbuild-cmake)](https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Setup-vapoursynth-for-mpv)
> > > Download the embeddable file and extract it in same folder as mpv.exe.
> 
> Hi @zhongfly so using same dir as **MPV**, but that wouldn't help if you have **mpv** installed via chocolatey 🤔.
> 
> What about using lua ??

Technically I think you should just be able to locate the mpv.exe file and install to that directory, if I remember correctly, it should be in a folder named tools, the first time I personally installed MPV was via chocolatey before I just began to use Shinchiro and Zhongfly's builds.

If you don't want to go to the trouble of setting everything yourself just download MPV-Lazy by Hooke.
https://github.com/hooke007/MPV_lazy

It comes preinstalled with a portable installation of python and VapourSynth and also comes preinstalled with MVTools, SVP, Rife and AnimeJanai so you basically have everything set up.
