### ISSUE TITLE
How to go about debugging my script?

### ISSUE THREAD

**Issue by RalfReddings** [mpv-player/mpv#13028]
I am not looking to do anything complex like a Visual Studio Code Debugger with a call stack and code stepping support, as such a thing probably does not exist.

But at least, is there a means to know
- what value a variable holds
- what properties/object a call back passed to a function 
- What the current state of MPV [Properties](https://mpv.io/manual/master/#properties) is
and so on. Such as a message box that I can use to print the value of a variable to screen. Or ideally for me, a way to write to a file on disk, values such as variables/objects and even general log messages (during development).

I want to gradually increase my know how of writting MPV scripts with JavaScript, I am also learning JavaScript itself too, so its hard to know what is MPV or JS limitation.

From what I know MPV is using a limited version of JS. Can I least use this JS to create and write files to my disk? I want to create/write to files for logging (variables or objects) and debugging. I would love to see a quick example of this.

For example I made this simple script (a revision of [Exit Fullscreen on Pause](https://mpv.io/manual/master/#javascript) ) that pauses the player when focus is lost:
    
    function on_focus_change(name, value) {
    	if (value == false)
    		mp.set_property("pause", "yes");
    }
    mp.observe_property("focused", "bool", on_focus_change);
    
What does `name` consist of? I had to guess values consists of the `bool` state  of `focused`. 

Any help would be greatly appreciated!

**Comment by butterw** [comment]
I just use print to terminal.

```
function oprint(property) { //property_osd
	var p = mp.get_property_osd(property);
	if (p=="") p='""';
	print(" "+ property +" osd:", p);
}

function rprint(property) { //=property
	var p = mp.get_property(property);
	if (p=="") p='""';
	print(" "+ property, p);
}

function nprint(property) { //property_number
	var p = mp.get_property_number(property);
	if (p=="") p='""';
	print(" "+ property +" number:", p);
}

function fprint(property) { //full print
	oprint(property); rprint(property); nprint(property);
	print();
}

```

**Comment by guidocella** [comment]
`print(name)`

**Comment by RalfReddings** [comment]
These are great. Thank you so much for sharing these with me!

**Comment by butterw** [comment]
Not all javascript string manipulation is available. 
You can look at some examples in https://github.com/mpv-player/mpv/wiki/User-Scripts

**Comment by stax76** [comment]
Print is fine, I've used it and it worked well.

Interesting to know however is that for Lua real debugging support is available, on Linux it's more limited compared to Windows. I've used the debugger successfully for some of my scripts and can say that it works well and is helpful. I wrote something on how to configure it here:

https://github.com/mpvnet-player/mpv.net/wiki/Extending-mpv-and-mpv.net-via-Lua-scripting

**Comment by butterw** [comment]
https://github.com/tsl0922/mpv-debug-plugin allows you to display mpv property values at runtime in a gui, including script user-data properties.

**Comment by RalfReddings** [comment]
@butterw  that utility looks really amazing. Thank you for sharing it with us. Will go through it ASAP.

**Comment by Dudemanguy** [comment]
Question seems thoroughly answered.
