### ISSUE TITLE
How to supply only a mpv.conf file at the terminal?

### ISSUE THREAD

**Issue by RalfReddings** [mpv-player/mpv#13032]
I am looking for a means of supplying my own `mpv.conf` file at terminal, at the same time as I am about to open media with MPV.  When I am developing MPV script, have so far used `--no-config` to avoid MPV from reading `/appdata/` config folder. But 90% I just need it to not read the `mpv.conf` file at or for it to read a specific `mpv.conf` located elsewhere.

The closest I can find to supplying my own config at the terminal is  `--use-filedir-conf`, which is not ideal as it requires me to place a `mpv.conf` in the same location as the media file. I am looking for something like:

    
    mpv c:\temp\my_video.mp4 --conf-file=.\documents\my_conf_file.conf
    

Thanks for any help

**Comment by guidocella** [comment]
`--include=<configuration-file>`

**Comment by Hrxn** [comment]
[`--config-dir`](https://mpv.io/manual/master/#options-config-dir)
