### ISSUE TITLE
Advanced Saturation settings/range

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#13044]
Hi,
I want to make a request for a more advanced saturation setting with specific values like start and end range.
I personally use a high gamma on my system, this introduces a nasty side effect. The colors in the "lows" (0-40 rgb range) get boosted and this looks sometimes ugly like petroleum on water. It would be nice to tackle this inside mpv. The 2nd scenario is content movies/shows that have exaggerated color grading in the "lows" (recent example loki 2nd season). I know that this is intended (art) but it would be nice if we could dial in our own settings.

To be clear, I don't want to replace the normal saturation setting, this could be a added layer on top of the normal settings.

Let me know what you think about it.
Thank you

the issue with boosted gamma for representation purposes
![dfgfdgdf](https://github.com/mpv-player/mpv/assets/139760266/14a06e48-4a5d-47df-97b6-bd6ec87ca72e)

**Comment by Dudemanguy** [comment]
Assuming the shader solved this.

**Comment by geextahslex** [comment]
yes but it's not a mpv build in solution. it's an extern "tweak"
