### ISSUE TITLE
Ravu-lite-ar-r4 versus  when ravu-zoom-ar-r3 will be the better option

### ISSUE THREAD

**Issue by realdevnullius** [mpv-player/mpv#13040]
In follow up of https://artoriuz.github.io/blog/mpv_upscaling.html

Quote: "If you're not only doubling though, ravu-zoom-ar-r3 might be a better option."

I'm a newbie trying to find her way through it all... :) 

"not only"... So what does ravu-zoom-ar-r3 do better? More than 2x zoom? Or is it a sharpening thing?

And in general I'm also curious what the r3 / r4 differences are and what the AR in ar-r3 and ar-r4 is...?  If you guys help me out, I'll add it to my mpv.conf as comments and share them around :)

**Comment by Akemi** [comment]
this is completely the wrong place to ask questions about a blog post not related to am mpv directly. you should ask the author.

questions about ravu, or rather the mpv shaders are best placed where they were actually come from https://github.com/bjin/mpv-prescalers.

ar = anti ringing.
