### ISSUE TITLE
Cursor hidden after running mpv from Ruby script

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#13049]
### Important Information

Provide following Information:
- mpv version: f551a9d
- macOS Version: 14.1.1
- Source of the mpv binary or bundle: Git
- If known which version of mpv introduced the problem: ?

https://github.com/mpv-player/mpv/issues?q=ruby+cursor

### Reproduction steps

```bash
$ cat > foo
puts `mpv --no-config any.mp4`
^D
$ ruby foo
q
$
```

### Expected behavior

Cursor should be displayed.

### Actual behavior

Cursor is hidden.

### Notes

- `printf "\033[?25h"` brings back the cursor (workaround)
- ``ruby -e "puts `mpv --no-config any.mp4`"`` (inline) does not hide the cursor.
- Could be a Ruby issue, but most likely an mpv issue.

**Comment by kasper93** [comment]
Fixed by https://github.com/mpv-player/mpv/pull/12924

**Comment by forthrin** [comment]
Evidently not merged to master yet, but applying the patch manually brought back the cursor. Well done!
