### ISSUE TITLE
Blurry OSD (not sure about video content) with `--vo=dmabuf-wayland` on GNOME + HiDPI

### ISSUE THREAD

**Issue by intelfx** [mpv-player/mpv#13050]
### Important Information

Provide following Information:
- mpv 0.36.0
- Arch Linux
- `extra/mpv 1:0.36.0-1`
- GNOME Shell (Mutter) 45.1
- `Intel(R) UHD Graphics 620 (KBL GT2)`, `Mesa 23.2.1-arch1.2` (I assume iris?)

### Reproduction steps

- Use GNOME on a HiDPI display (200% scaling)
- run `mpv --vo=dmabuf-wayland --hwdec=auto <file>`
  (I used a YouTube video with ytdl-format set according to my panel resolution, that is `--ytdl-format=bestvideo[width<=?2560][height<=?1440][fps<=?60]+bestaudio/best[width<=?2560][height<=?1440][fps<=?60]`)
- press `i` for the OSD

### Expected behavior

- OSD rendered at panel resolution
- "Native resolution" equal to "Scaled resolution" on the OSD

### Actual behavior

- OSD is blurry, as if rendered at 1/2 panel resolution and then upscaled
- "Scaled resolution: 1280x720" on the OSD

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/13600536/mpv.log)

## Screenshot

![Снимок экрана от 2023-12-07 17-04-58](https://github.com/mpv-player/mpv/assets/1158172/66f5207e-6587-4e0f-bf1e-a561250f3932)

**Comment by CounterPillow** [comment]
Not a bug, see #12896

Don't use the dmabuf-wayland VO if you're looking for anything like hidpi scaling.

**Comment by intelfx** [comment]
I still don't really understand it. I've a 2560x1440 panel, in a 2560x1440 mode, with a 2560x1440 video, in full screen, why is there any scaling at all?

**Comment by CounterPillow** [comment]
From the log:

```
[  14.668][d][vo/dmabuf-wayland] max content size: 2560x1440
[  14.668][d][vo/dmabuf-wayland] monitor size: 2560x1440
[  14.671][v][vo/dmabuf-wayland] Window size: 2560x1376 (Borders: l=0 t=0 r=0 b=0)
[  14.671][v][vo/dmabuf-wayland] Video source: 3840x2160 (1:1)
[  14.671][v][vo/dmabuf-wayland] Video display: (0, 0) 3840x2160 -> (57, 0) 2446x1376
[  14.671][v][vo/dmabuf-wayland] Video scale: 0.636979/0.637037
[  14.671][v][vo/dmabuf-wayland] OSD borders: l=57 t=0 r=57 b=0
[  14.671][v][vo/dmabuf-wayland] Video borders: l=57 t=0 r=57 b=0
[  14.671][v][vo/dmabuf-wayland] Window size: 2560x1376 (Borders: l=0 t=0 r=0 b=0)
[  14.671][v][vo/dmabuf-wayland] Video source: 3840x2160 (1:1)
[  14.671][v][vo/dmabuf-wayland] Video display: (0, 0) 3840x2160 -> (57, 0) 2446x1376
[  14.671][v][vo/dmabuf-wayland] Video scale: 0.636979/0.637037
[  14.671][v][vo/dmabuf-wayland] OSD borders: l=57 t=0 r=57 b=0
[  14.671][v][vo/dmabuf-wayland] Video borders: l=57 t=0 r=57 b=0
[  14.690][v][vo/dmabuf-wayland/wayland] Obtained preferred scale, 1.000000, from the compositor.
[  14.690][d][vo/dmabuf-wayland] max content size: 2560x1440
[  14.690][d][vo/dmabuf-wayland] monitor size: 2560x1440
[  14.690][v][vo/dmabuf-wayland/wayland] Resizing due to xdg from 2560x1376 to 1280x720
```

Presumably (and I don't know if this is right, feel free to correct me on this @Dudemanguy) the compositor assumes you want to treat the screen like it has half its resolution to make non-hidpi-aware applications render at the correct size. The dmabuf-wayland VO is non-hidpi-aware by design.

I don't really agree with what appears to be dmabuf-wayland scaling the video down in this case since that's strictly more work than not scaling it down, but it's also not a VO you should be using if you're looking for correct video output anyway.

**Comment by Dudemanguy** [comment]
`dmabuf-wayland` does zero scaling on its own. All scaling is done by the compositor. This is why it looks bad. It's meant for lower power usage (in theory anyway). All mpv does in this case is draw a buffer at the video size and the compositor takes care of the rest. How good/bad it looks is up to the compositor.

**Comment by CounterPillow** [comment]
> > but it's also not a VO you should be using if you're looking for correct video output anyway

> Why?

Compositors do not work on magic pixie dust. If you throw a dmabuf at it, it still needs to somehow transform it from NV12 to RGB, and composite it into the screen somehow (which may involve scaling). Unless you are on some very weird hardware with specialized software, it will do this using the GPU programmable shading pipeline, the same thing mpv's gpu and gpu-next output use to scale and transform and tonemap etc. etc. the image.

The only conceivable way I see where dmabuf-wayland will make a difference in power usage compared to gpu "dumb mode" is if you're trying to display a full screen video on a sophisticated compositor that negotiates a compatible display format with the display controller (including any chroma subsampling) and directly scans out the buffer in that case. I am not aware of any compositor doing this at the moment. (Technically you can also do this non-full-screen on some display controllers with fixed function compositing hardware, but realistically nobody wants to deal with that and its limitations.)

**Comment by intelfx** [comment]
@Dudemanguy 

> All mpv does in this case is draw a buffer at the video size and the compositor takes care of the rest. How good/bad it looks is up to the compositor.

Then shouldn't it be drawing the OSD at the proper size as well?

**Comment by Dudemanguy** [comment]
The OSD is drawn at the video size as well. It's merely some software buffers that overlay the wayland surface. Nothing fancy.
