### ISSUE TITLE
2 Questions about glsl shaders

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#13052]
Hi,
1. Is it possible to keybind a glsl shader, so I can toggle it on and off?
If it is possible, how do I set this up?

2. Is it possible to keybind shader values (like strength, threshold etc.) and edit them on the fly, without closing mpv, changing the settings and the reopen mpv?
If it is possible, how do I set this up?

Thank you to everyone

**Comment by geextahslex** [comment]
Thank you, that helped

**Comment by geextahslex** [comment]
okay I tried this
w cycle-values glsl-shader-opts desat/Strength=0.5 desat/Strength=1
and it didn't show any effect. there was a pop up with the changes but the shader didn't change visually

**Comment by geextahslex** [comment]
okay, so I modified the shader to use "param" on "strength" which now looks like this. and I can toggle it, so it works.
-------------------------------------------------------------------------
//!PARAM Strength
//!TYPE DEFINE
1

//!HOOK MAIN
//!BIND HOOKED
//!DESC Desaturation smooth 


#define Thresh 15/255.
#define w 10/255.
#define CoefLuma vec4(0.2126, 0.7152, 0.0722, 0) //sRGB, HDTV

/* simple threshold with mpv glsl 
Strength*desaturation [0 to1.0], 0: full color, 1: grayscale.
*/

vec4 hook()  {
   vec4 c0 = HOOKED_texOff(0);
   vec3 desaturation = smoothstep(Thresh + w, Thresh - w, c0.rgb);
   // return vec4(desaturation, 1);
   c0.rgb = mix(c0.rgb, vec3(dot(c0, CoefLuma)), Strength*desaturation);

   return c0;
}
--------------------------------------------------------------------------------
and I have this in "input.config":
w cycle-values glsl-shader-opts desat/Strength=0.1 desat/Strength=0.5
but it still doesn't work
I would prefer the option "add" instead of "cycle" as I use it in any other parameter. So I can use "+0.1" and "-0.1" on two keybinds

**Comment by haasn** [comment]
Just a heads up, you probably want `//!TYPE float`, not `//!TYPE DEFINE`. The latter only works for whole-value numbers and triggers shader recompilation on any modification.

**Comment by butterw** [comment]
declare Strength as float:  
//!PARAM Strength
//!DESC Desat Strength
//!TYPE float
//!MINIMUM 0
//!MAXIMUM 1
1.0

Is it possible to use input command add on glsl-shader-opts values ?

**Comment by geextahslex** [comment]
Okay that worked, but also confusing why DEFINE in big letters and float in small letters..but okay
Thank you for that tip that the video have to run to see the "cycle values" changes. That saved us all some time ^^

So the last thing, can we keybind this more organic than cycle values? Like I mentioned with "add"?

**Comment by butterw** [comment]
[vo/gpu-next/libplacebo] Unrecognized GLSL type 'define'!
[vo/gpu-next/libplacebo] Failed to parse user shader:

...then with DEFINE
[vo/gpu-next] The Strength option must be an integer: 0.1

Likely it's possible to write a script that can handle +0.1/-0.1 add operations on glsl-shader-opts (Key/value list). But I don't know if there is way to do it with just input.conf currently. If not, I think this would be a valid feature reques.

If you are just cycling through a couple discrete values the simplest way to do it is to create multiple shaders with different values hardcoded. The//!PARAM bloc is not required and the shader can also work with --vo=gpu.
ex; desat.10.glsl, desat.30.glsl, desat.50.glsl.
It's also makes it simpler to display the shader + parameter value on OSD.
The re-compilation cost is negligible on simple shaders such as this one.

**Comment by geextahslex** [comment]
okay this is the first time I got the feeling that something is more complicated than it needed to be, but maybe in future there will be better solutions

Thank you all for help on this journey :)

**Comment by geextahslex** [comment]
Thats how I did it in the end. 2 keys. one row goes up, the the other down.
Didn't know about the "!reverse" option
Thank you

**Comment by geextahslex** [comment]
A nice workaround ^^
