### ISSUE TITLE
osc-chapterlist not working if osc=no

### ISSUE THREAD

**Issue by Dragoonstorm1** [mpv-player/mpv#13056]
### Important Information

- mpv version = [v0.37.0]
- Windows Version = 22H2
- Source of the mpv binary = https://sourceforge.net/projects/mpv-player-windows/rss?path=/64bit
- If known which version of mpv introduced the problem = Possibly latest... I last updated few months ago
- Possible screenshot or video of visual glitches

### Reproduction steps

Reproduced successfully with -no-config.
mpv.exe -no-config
Load a video file with multiple (preferably named) chapters.
Open console and send "script-message osc-chapterlist"
Works as expected.
Open console and send "set osc no"
Open console and send "script-message osc-chapterlist"
Fails to work anymore.

### Expected behavior
Pretty, Bullet-pointed Chapter List.
I was using this mainly via betterchapter.lua

### Actual behavior
Actually fully breaks and shows no chapter names, and no error messages.

I have always had osc=no to run UOSC or other custom OSC.
But upon updating, it has stopped working.
On debugging I find this behavior to AT LEAST be replicable in this basic form.
There is more to the issue.
Setting osc=yes is not enough to return the bullet points, if other custom OSC's are also in play. It only fixes the issue on vanilla OSC.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/13624165/output.txt)

**Comment by hooke007** [comment]
I do not understand the problem.
You disabled the script first. Why do you think it should still work then?

**Comment by Dragoonstorm1** [comment]
> I do not understand the problem. You disabled the script(osc) first. Why do you think it(osc) should still work then?

but! it has been working all along with osc=no
Until this update

also, isn't osc about the GUI controls like progress bar, next, previous, pause/play, etc? the stuff at the bottom of the screen?
https://github.com/mpv-player/mpv/blob/master/DOCS/man/osc.rst

So why is it controlling on-screen text reports like Chapter list.

(ok I see now, it must be written for displaying Chapter List on clicking Next/Prev OSC buttons. I thought osc-playlist was working with osc=no but that was wrong too, it only worked if i had a script called playlistmanager.lua that rebuilt the osc-playlist view from scratch)


I guess that has turned it into a different issue.

My apologies if this is misdirected.

**Comment by hooke007** [comment]
> So why is it controlling on-screen text reports like Chapter list.

your command `script-message` https://mpv.io/manual/master/#command-interface-script-message

**Comment by Dragoonstorm1** [comment]
> > So why is it controlling on-screen text reports like Chapter list.
> 
> your command `script-message` https://mpv.io/manual/master/#command-interface-script-message
> 
> https://github.com/mpv-player/mpv/blob/443c2487d7dd1039e297abad6398135b3c463018/player/lua/osc.lua#L2736-L2738

No, that's not the answer to that question, but you are right, chapterlist is a module under osc.lua
I was asking why that^ is the case. 


Anyway, seems like my bug report has to pivot around to the fact that modules of osc.lua are now completely not loaded unless osc=yes which didn't seem to be the case before. I could swear i could use osc-chapterlist even with osc=no.

Regardless... Now I guess I wish to find a way to use just the chapterlist part of it without the rest of the actual **on-screen controller** 'GUI' stuff.

> There is more to the issue. Setting osc=yes is not enough to return the bullet points, if other custom OSC's are also in play. It only fixes the issue on vanilla OSC.

This bit is false, it's my fault. Turns out UOSC.lua has a line that forces osc=no now, instead of relying on users doing it in mpv.conf
I assume that was added recently.

Regardless, I still need to turn on OSC=yes to use osc-chapterlist, which i never had to do in the past.

**Comment by Dragoonstorm1** [comment]
Well. This may entirely be my fault.
I think I had the osc.lua file itself in the scripts folder in the past. Had deleted it lately.
Seems like keeping the osc.lua file allows osc-chapterlist to work even if osc=no in config.

I guess that's the end of it.

**Comment by Dragoonstorm1** [comment]
>.< it still renders the entire OSC, which was not the earlier behaviour so. I'm at a loss. sorry for the trouble.

**Comment by guidocella** [comment]
Can't you just use `show-text ${chapter-list}`?

**Comment by christoph-heinrich** [comment]
If you want to retain all the functionality of the osc, but without the interface, you can use the [stripped osc](https://github.com/christoph-heinrich/sosc).

**Comment by Dragoonstorm1** [comment]
> Can't you just use `show-text ${chapter-list}`?

That does something. It's not quite the same in appearance, but it's something.

> If you want to retain all the functionality of the osc, but without the interface, you can use the [stripped osc](https://github.com/christoph-heinrich/sosc).

Thank you I will look into that!
I was trying to strip it down myself already, mostly making a mess of it. Thanks again.
