### ISSUE TITLE
question about Native compilation with MSYS2

### ISSUE THREAD

**Issue by wbtcpip2** [mpv-player/mpv#13069]
Could you please rewiew the instructions at this page: https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md about the native compilation with MSYS2.
In that page the command list is the following:

pacman -Syu
pacman -Su
pacman -S git $MINGW_PACKAGE_PREFIX-{python,pkgconf,gcc,meson}
pacman -S $MINGW_PACKAGE_PREFIX-{ffmpeg,libjpeg-turbo,luajit}
meson setup build -Dlibmpv=true --prefix=$MSYSTEM_PREFIX
meson compile -C build
meson install -C build

maybe i'm worng but it seems you forgot to add the command to install mpv because meson commands fails
could you please review the instructions and add the missing commands?

thank you

**Comment by CounterPillow** [comment]
> maybe i'm worng but it seems you forgot to add the command to install mpv because meson commands fails

Oh really? The meson command fails? Why don't you tell us how it fails?

**Comment by wbtcpip2** [comment]
# meson setup build -Dlibmpv=true --prefix=$MSYSTEM_PREFIX

ERROR: Neither source directory 'build' nor build directory None contain a build file meson.build.

**Comment by llyyr** [comment]
You're right that the guide isn't exactly correct, it's missing a step that should be implicit.

`git clone https://github.com/mpv-player/mpv` then run the meson commands in the folder where mpv is

**Comment by wbtcpip2** [comment]
thank you very much .... this was the missing step (i know it's obvious but I'm not as expert as you)

**Comment by wbtcpip2** [comment]
sorry one more question if possibile

meson setup build -Dlibmpv=true --prefix=$MSYSTEM_PREFIX was successfully executed

but

meson compile -C build

ERROR: Current directory is not a meson build directory: `D:/msys64/home/info/mpv/build`.
Please specify a valid build dir or change the working directory to it.
It is also possible that the build directory was generated with an old
meson version. Please regenerate it in this case.

which is the meson build directory?
