### ISSUE TITLE
Questions about --gpu-context=displayvk

### ISSUE THREAD

**Issue by nehalem501** [mpv-player/mpv#13061]
Hello, I wanted to ask a few things about displayvk.
Does it work only from a TTY or is there a way to have it work from an X11 or Wayland session?
I'm asking because I'd like to have a way to have an "exclusive full screen" mpv running on my TV / projector but keep my regular desktop on my PC screen.
What I mean by "exclusive full screen" is that while mpv is running, nothing else should be displayed on the TV / projector (no cursor, notifications, sound level indicator or anything like that), no matter what I'm doing on the PC screen that displays my desktop.
Also, on Linux, bypassing the compositor gives me the possibility to display HDR which currently is not possible using a desktop environment.

**Comment by philipl** [comment]
It works on Nvidia x11 but I think I never merged the code for that.

**Comment by nehalem501** [comment]
> It works on Nvidia x11
You mean with the proprietary drivers?

When searching on the subject, it seems like what I'm trying to achieve exists with a mechanism called "DRM Leasing". Its primary purpose is VR, but it should work. (It seems like it is already implemented in Xorg and in all major wayland compositors except mutter / gnome)

**Comment by philipl** [comment]
Yes, it requires the proprietary drivers. DRM Leasing is a mechanism in the drm API for stealing a display. There is a Vulkan extension for doing this (`VK_EXT_ACQUIRE_XLIB_DISPLAY`) and nvidia implements it. I never merged the code but you can see my original logic [here](https://github.com/mpv-player/mpv/commit/5da862a81a8252c41d842dba7c25992bd35a49ba). I can't remember why I never merged it - I think there was some difficulty with ordering of initialisation.
