### ISSUE TITLE
consistently crashing gnome wayland desktop debian when quitting mpv, especially fullscreen or zoomed

### ISSUE THREAD

**Issue by zenaan** [mpv-player/mpv#13062]
debian 12/bookworm default desktop gnome wayland - when mpv finishes, either with "q"uit or video (or gif) ending, the whole (gnome/wayland) desktop crashes and have to log back in. This makes mpv almost unusable at the moment for me.

Can reliably repeat this desktop crash, sometimes with a few runs required. Sometimes zooming the video helps make the (whole desktop) crash repeat more reliably.

Laptop, intel, no gpu, docking station with external monitor.

Initially I assumed it might be an intel video driver problem, and reported here:
https://github.com/intel/media-driver/issues/1743

eventually tried reporting a bug against Debian mpv package:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057119

- OS: Debian 12/Bookworm

- Package: mpv
Version: 0.35.1-4

- apt-cache show mutter | grep Version
Version: 43.8-0+deb12u1

- Package: gnome-desktop3-data
Version: 43.2-2

- settings -> about
GNOME Version: 43.6

- xserver-xorg-video-intel/stable,now 2:2.99.917+git20210115-1 amd64 [installed,automatic]
- intel-media-va-driver/stable,now 23.1.1+dfsg1-1 amd64 [installed]

- same mpv "crashing on close" result with
intel-media-va-driver-non-free/stable 23.1.1+ds1-1

- no discrete gpu/dgpu
- Intel i7-10810U
Mesa Intel UHD Graphics (CML GT2)

- laptop
- thunderbolt docking station with external monitor

- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1057119

- Able to test - I reported initially against intel video driver:
https://github.com/intel/media-driver/issues/1743
 [Bug]: wayland/gnome crash, after fullscreen or zoom video, then
quit, mpv, 6.1.0-13-amd64, both intel free and non-free drivers #1743

----
So I just tested by running gdb per the mpv gdb instructions (inside tmux, since the desktop crashes), and in my case the "end" of the mpv process is as follows:

Exiting... (Quit)
[Thread 0x7fffe4db86c0 (LWP 17783) exited]
[Thread 0x7fffe65bb6c0 (LWP 17778) exited]
[Thread 0x7fffe55b96c0 (LWP 17780) exited]
[Thread 0x7fffe5dba6c0 (LWP 17779) exited]
[Thread 0x7fffe6dbc6c0 (LWP 17777) exited]
[Thread 0x7fff9a7fc6c0 (LWP 17797) exited]
[Thread 0x7fff9affd6c0 (LWP 17796) exited]

[Thread 0x7fff92ffd6c0 (LWP 17795) exited]
[Thread 0x7fff9b7fe6c0 (LWP 17794) exited]
[Thread 0x7fff9bfff6c0 (LWP 17793) exited]
[Thread 0x7fffb8dff6c0 (LWP 17792) exited]
[Thread 0x7fffc4ffc6c0 (LWP 17791) exited]
[Thread 0x7fffc57fd6c0 (LWP 17790) exited]
[Thread 0x7fffc5ffe6c0 (LWP 17789) exited]
[Thread 0x7fffc67ff6c0 (LWP 17788) exited]
[Thread 0x7fffccbff6c0 (LWP 17787) exited]
[Thread 0x7fffcf3fe6c0 (LWP 17786) exited]
[Thread 0x7fffe75bd6c0 (LWP 17776) exited]
[Thread 0x7fffcfbff6c0 (LWP 17784) exited]
[Inferior 1 (process 17775) exited normally]
(gdb) thread apply all backtrace

Which seems to show that mpv at least appears to exit normally, but something upstream (re threads/ process within the terminal or desktop or wayland and graphics driver) is crashing.

If anyone can suggest what else I can do to test this, I would appreciate that very much.

----
according to gdb I got a clean exit of mpv

----
[mpv-out.log](https://github.com/mpv-player/mpv/files/13626287/mpv-out.log)
[vainfo.log](https://github.com/mpv-player/mpv/files/13626288/vainfo.log)

**Comment by Dudemanguy** [comment]
This sounds similar to https://github.com/mpv-player/mpv/issues/8812 but I don't know if you're experiencing the same thing. Anyways, 0.35 is too old and not supported and also the compositor crashing cannot be our bug regardless of whatever bad thing mpv may be doing.
