### ISSUE TITLE
Is there a way to display HDR in Gnome with its experimental feature?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#13070]
I've heard that Gnome is able to turn on HDR mode by doing following steps:
1. press `Alt+F2`
2. input `lg`
3. input `global.compositor.backend.get_monitor_manager().experimental_hdr = 'on'`

After doing these steps above, the screen becomes super bright, the color on desktop is really weird, so I know that HDR mode is on.

Here is my question. Can I play HDR videos in this mode with MPV player without tone-mapping to SDR?

Down below is my current HDR config in DRM mode (with amdvlk driver):
```
icc-profile=no
gpu-context=displayvk
target-trc=pq
target-prim=bt.2020
```
I tried to remove `gpu-context=displayvk` and ran this config in Gnome experimental HDR mode, the image seemed to be much brighter than in DRM mode.
### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by llyyr** [comment]
![image](https://github.com/mpv-player/mpv/assets/6298234/5655156d-3f0c-40dd-a294-5fd3456eff4c)

Your question was answered 8 months ago. This only forces one specific HDR mode, if your file happens to have the exact same metadata then it _might_ work(?), otherwise no. Regardless you need `target-colorspace-hint` for it.

You can just run mpv under gamescope instead for HDR.

**Comment by laichiaheng** [comment]
@llyyr I forgot to mention that `target-colorspace-hint` has already in my config.
Isn't gamescope a Steam specific shell?

**Comment by llyyr** [comment]
> Isn't gamescope a Steam specific shell?

No, you can run mpv under it.

`gamescope --hdr-enabled -- mpv --target-colorspace-hint --fs [video]` should hopefully work in a tty.

**Comment by laichiaheng** [comment]
> > Isn't gamescope a Steam specific shell?
> 
> No, you can run mpv under it.
> 
> `gamescope --hdr-enabled -- mpv --target-colorspace-hint --fs [video]` should hopefully work in a tty.

Why is the gamescope HDR looks much saturate than MPV with AMDVLK?

**Comment by kasper93** [comment]
> I figured out that I still need to add `--target-prim=bt.2020`, or should I?

Yes, `--icc-profile=no --target-trc=pq --target-prim=bt.2020 --target-colorspace-hint` for HDR "passthrough"

**Comment by ofarukaydin** [comment]
This is how I got it working in gnome:
1- Install [vk-hdr-layer-kwin6-git](https://aur.archlinux.org/packages/vk-hdr-layer-kwin6-git) from aur
2- Switch to hdr mode with `global.compositor.backend.get_monitor_manager().experimental_hdr = 'on'`
3- run mpv with `ENABLE_HDR_WSI=1 mpv --vo=gpu-next --icc-profile=no --target-trc=pq --target-prim=bt.2020 --target-colorspace-hint --gpu-api=vulkan --gpu-context=waylandvk some-video-path`

**Comment by Mutcholoko** [comment]
> This is how I got it working in gnome: 1- Switch to hdr mode with `global.compositor.backend.get_monitor_manager().experimental_hdr = 'on'` 2- run mpv with `mpv --vo=gpu-next --icc-profile=no --target-trc=pq --target-prim=bt.2020 --target-colorspace-hint --gpu-api=vulkan --gpu-context=waylandvk some-video-path`

Thank you so much for this! It seems to work quite well!! Although now I'm wondering if it's proper HDR (including the pixel brightness changing features) or if it's just the correct color space. Would you have any info on this? Thank you, nonetheless.
