### ISSUE TITLE
Is MPV possible to enable HDR on Plasma6?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#13078]
I've already known that there is no way to play HDR videos on Gnome45 with its experimental HDR feature #13070 
However, KDE Plasma 6 beta has partial supported HDR, they have implemented color management in KWin, I can enable HDR in settings of Plasma 6, but MPV seems still convert HDR to SDR, is there any way to passthrough HDR in Plasma 6? Or it is still not possible for now?

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt, paste
it to https://0x0.st/ or attach it to the github issue, and replace this text
with a link to it.

**Comment by LaserEyess** [comment]
No.

**Comment by laichiaheng** [comment]
OK

**Comment by CounterPillow** [comment]
Please open 3219453849314 more issues about HDR which you know Linux can't do, we all really like them

**Comment by Hrxn** [comment]
Exactly 3219453849314! Not one more!

**Comment by laichiaheng** [comment]
@LaserEyess @CounterPillow @Hrxn 
I was wrong!
MPV does play HDR videos in Plasma6 Wayland, it just needs to install a package which is called `vk-hdr-layer-kwin6-git`, and append `ENABLE_HDR_WSI=1` in `/etc/environment`
After these steps, just run `mpv --vo=gpu-next --target-colorspace-hint --gpu-api=vulkan --gpu-context=waylandvk <video>`, it works!!!

**Comment by nitschis** [comment]
Now that KDE Plasma 6.1 reports the correct HDR values to applications. Any chance HDR could "just work" with mpv?

**Comment by ruihe774** [comment]
We need to wait for [Wayland color management protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/14) to be merged. It is the only cross-desktop way to handle HDR in Wayland.

**Comment by laichiaheng** [comment]
> Now that KDE Plasma 6.1 reports the correct HDR values to applications. Any chance HDR could "just work" with mpv?

Isn't it already working?
![20240706_230921](https://github.com/mpv-player/mpv/assets/9532105/04e26262-515b-4291-9c24-ae0b17eff762)
![20240706_230945](https://github.com/mpv-player/mpv/assets/9532105/b829a1f5-60c7-42cd-b689-20209ff80361)
![20240706_230956](https://github.com/mpv-player/mpv/assets/9532105/d1e7272c-53ba-4c7f-a35d-960e06b6d544)

**Comment by llyyr** [comment]
Kwin has some hacks to make it work through https://github.com/Zamundaaa/VK_hdr_layer

I didn't know they were shipping things they themselves call hacks in vanilla installations though...
