### ISSUE TITLE
LIBMPV - Application using libmpv crashes

### ISSUE THREAD

**Issue by martinrotter** [mpv-player/mpv#13074]
### Important Information

Provide following Information:
- mpv version - https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-v3-20231210-git-443c248.7z/download
- Windows Version - Windows 10 - all updates installed.
- Source of the mpv binary - https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-v3-20231210-git-443c248.7z/download

RSS Guard integrates libmpv for podcasting features. Very small percentage of users reported that RSS Guard does not start and error "0xc0000142" (DLL_INIT_FAILED). Hundreds of user install that same RSS Guard package (which includes "libmpv-2.dll") and do not report problems. It seems issue is related to libmpv-2.dll because the same RSS Guard package without libmpv-2.dll-specific features works fine.

Do you have any previous experience with this? I attach report from Dependency Walker which did not find any clearly missing library.

[rssguard-devbuild-a85aea971-win10.txt](https://github.com/mpv-player/mpv/files/13636209/rssguard-devbuild-a85aea971-win10.txt)

**Comment by zhongfly** [comment]
Which version of mpv introduced the problem ? 
And can you try https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20231210/mpv-dev-x86_64-gcc-20231210-git-443c248.7z ?

**Comment by stax76** [comment]
Or maybe because the CPU is too old? v3 is for modern CPUs.

**Comment by martinrotter** [comment]
> Which version of mpv introduced the problem ? And can you try https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20231210/mpv-dev-x86_64-gcc-20231210-git-443c248.7z ? Is it possible that it is a bug in your code?

Sent the info to user who is having the problem.

Well, hard to say if it is bug in my code. I would rather say it is not. libmpv-related code is very simple.

The user tested SMplayer (which has mpv libs AFAIK) which works. I also tested my RSS Guard app in clean Windows 10 install in VirtualBox which works.

I encourage anyone to test it, simply launch "rssguard.exe". The crash for THE user appeared right on app start as the reported error code is Windows-specific APP_DLL_INIT_FAILED code.

https://github.com/martinrotter/rssguard/releases/download/4.6.2/rssguard-4.6.2-c1ada2fb2-win10.7z

**Comment by zhongfly** [comment]
> I encourage anyone to test it, simply launch "rssguard.exe". The crash for THE user appeared right on app start as the reported error code is Windows-specific APP_DLL_INIT_FAILED code.
> 
> https://github.com/martinrotter/rssguard/releases/download/4.6.2/rssguard-4.6.2-c1ada2fb2-win10.7z

I haven't reproduced the problem.

> Or maybe because the CPU is too old? v3 is for modern CPUs.
You can ask the user what their cpu is and check if the cpu supports the instruction sets `avx` `avx2`
[Difference between x86_64 and x86_64 v3](https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Difference-between-x86_64-and-x86_64-v3)

**Comment by martinrotter** [comment]
Indeed, user now reports that "mpv-dev" dll works and "mpv-dev-v3" does not. Thanks for hinting this out! I did not even know this.

I believe we can close this.

**Comment by kasper93** [comment]
I tested on clean Windows 10/11, seems to work ok.

There is `VSScript.dll` missing (which libmpv depends on), but it is delay loaded, so it silently works.

> mpv-dev-x86_64-v3-20231210-git-443c248.7z

You should be using non-v3 version for distributed builds. Some of the users likely will run your app on hardware without `AVX2` support. It is supported since Haswell ~2015 on desktop CPUs, but some smaller Atoms got it more recently.
