### ISSUE TITLE
The border scaling and thickness of osd-bar are abnormal, and the background color overflows the border.

### ISSUE THREAD

**Issue by 422658476** [mpv-player/mpv#13071]
### Hello everyone, I used mpv's osd-bar to make a progress bar that is always displayed at the bottom of the video. This progress bar has been used normally on the mpv-easy player I made for several years. When mpv released the first 0.37 .0 version (2023-11-26) is still normal. This is what it looks like normally (a whole white progress bar at the bottom)

![right-osd-bar](https://github.com/mpv-player/mpv/assets/37802190/d86619ba-ae67-4a96-83a5-01125cdfeb5a)

However, starting from the second version of mpv 0.37.0, the style of the progress bar that is always displayed becomes abnormal. The phenomenon is that the border of the osd-bar does not become thinner by itself, and the border does not seem to change color. A black background color can also be seen outside the frame.

![wrong-osd-bar](https://github.com/mpv-player/mpv/assets/37802190/08339d50-7ec4-4af3-99c4-7630de949a3e)

How to use this always-displayed bottom progress bar in mpv.

Please open this page

https://github.com/422658476/MPV-EASY-Player/tree/master/portable-data/scripts

Download osd-bar.lua and put it in

mpv\portable_config\scripts

Enter in mpv\portable_config\mpv.conf

```
osd-bar-w=100
osd-bar-h=0.4
osd-bar-align-y=1.00
osd-border-color=0.0/0.0/0.0/0.3
```

I have browsed the mpv manual, and it seems that there is no new setting that can change this border.

This is most likely a bug caused by recent code changes.

If possible, please tell me what settings to change to get it back to how it was before.

Many thanks

**Comment by zhongfly** [comment]
> first 0.37 .0 version (2023-11-26)

mpv create 0.37.0 tag on November 22.
It's not clear what you mean by the first and second.
Please use version code from `mpv --version`

I guess this is what you need to read:
https://github.com/mpv-player/mpv/commit/0c4812aa72f4a34d342ef3939587a95cbfa0bf40

**Comment by 422658476** [comment]
Thank you, based on the changes in the source code, I added the following settings to solve the problem.
osd-bar-border-size=0
This setting is only written in the pdf version of the manual in the mpv folder, so I didn't find it when I checked the web version of the manual. Thank you.

**Comment by zhongfly** [comment]
> I didn't find it when I checked the web version of the manual

https://mpv.io/manual/master/#options-osd-bar-border-size ？

The mpv binary you download is complied from `master` branch, not from 0.37.0 tag.
I'm not going to explain the difference between the meaning of tag and master again.You as a developer should know the difference.

**Comment by 422658476** [comment]
In fact, I really don't know the difference between the two. For me, one is the source code of the stable version, and the other is the source code of the development version.
Because I was not a computer major in school.
It seems weird for 2 Chinese people to speak English  ; )

**Comment by 422658476** [comment]
thanks,the list of these modification records is very detailed and exactly what I needed.
