### ISSUE TITLE
`playlist-next-playlist` and `playlist-prev-playlist` fail to work without adding folders and archive files

### ISSUE THREAD

**Issue by Essoje** [mpv-player/mpv#13075]
`playlist-next-playlist` and `playlist-prev-playlist` will only work with folders and archive files directly, and will fail to trigger pointing directly at media files and media files inside an archive

- mpv v0.37.0-85-g566a96f220
- Linux, Manjaro 23.1.0 Vulcan
- AUR's mpv-build-git

### Reproduction steps

Needs at least input.conf somewhere with keybindings for `playlist-next-playlist` and `playlist-prev-playlist`. And whenever it says one of those keybindings are used, read it as both being used
Also, adding a keybinding for `repeatable show-text ${playlist-path} 1000` will show the current playlist-path, helping in debugging a bit

Download the sample zip file and rename it to archived.zip. Extract it on an empty folder, making sure the folder structure is maintained like the following, which can be checked with `find . -type f`
```
./archived.zip
./picAlpha.png
./folder1/pic2.jpg
./folder1/pic1.jpg
./pic3.png
./folder2/video.mp4
./folder2/animated.gif
```

###### 1.a - Open normally at '.'
`mpv --loop-file=inf --loop-playlist=inf --no-config --input-conf=input.conf .`
###### 1.b - Open normally at './'
`mpv --loop-file=inf --loop-playlist=inf --no-config --input-conf=input.conf ./`
###### 1.c - Open normally at './*'
`mpv --loop-file=inf --loop-playlist=inf --no-config --input-conf=input.conf ./*`

###### 2. Open pointing at specific media files
This will show all files minus `pic3.png` and `archived.zip`, instead showing the `pic3.png` from inside `archived.zip`
`mpv --loop-file=inf --loop-playlist=inf --no-config --input-conf=~/.config/mvi/image-input.conf $(find . -type f -not -name "*.zip" -not -name "pic3.png") "archive://$PWD/archived.zip|/pic3.png"`

###### 3. Open using stdin though `--playlist=-`
`mpvplaylist="$(find . -type f -not -name "*.zip" -not -name "pic3.png")"; mpvplaylist+=$'\n'"archive://$PWD/archived.zip|/pic3.png" ; echo "$mpvplaylist" | mpv --loop-file=inf --loop-playlist=inf --no-config --input-conf=input.conf --no-terminal --playlist=-`

### Expected behavior

Using `playlist-next-playlist` should jump to the first file of the next folder or archive file as long as there's more than one folder or archive file with valid files.
Using `playlist-prev-playlist` should jump to the first file of the previous folder or archived file as long as there's more than one folder or archive file with valid files.
If there's a necessity for `playlist-path` to be set in order for `playlist-next-playlist` to function, then it should be set to the parent folder or archive file of the file, independent of how the file is added to the playlist.
If this is intended behavior, then a way to override that behavior and allow `playlist-next-playlist` to work when adding single files should be added.

###### 1.a - Open normally at `.`
Using `playlist-next-playlist` will jump between `.` and `./archived.zip` until you navigate into './folder1' and './folder2'
###### 1.b - Open normally at `./`
Same as `.`
###### 1.c - Open normally at `./*`
Using `playlist-next-playlist` will jump between './archived.zip', './folder1' and './folder2', and the `playlist-path` of files in root becomes `(unavailable)`
`(unavailable)` behavior responds to `playlist-next-playlist` by stopping at the next (unavailable) picture, effectively going through each `(unavailable)` picture one by one, until the playlist arrives the next valid `playlist-path`, if applicable
###### 2. Open pointing at specific media files
All `playlist-path` become `(unavailable)`, with similar behavior as 1.c but a valid `playlist-path` doesn't exist in this case
###### 3. Open using stdin though `--playlist=-`
All `playlist-path` become `-`
`-` behavior appears to not respond to `playlist-next-playlist` uses, which is likely the correct behavior for only having a singular `playlist-path` in the playlist

### Log files
https://0x0.st/H3gH.zip

### Sample files
https://0x0.st/H3Y9.zip

**Comment by guidocella** [comment]
This is intended because mpv can't know whether a playlist entry is a file or a playlist until it is played. `playlist-next-playlist` docs say "Go to the next entry on the playlist with a different playlist-path." and `playlist-path` docs say "Unavailable if the file was not originally  associated with a playlist in some way."

**Comment by guidocella** [comment]
I don't understand what shuffling has to do with playlist-next-playlist, they are completely unrelated.

**Comment by Essoje** [comment]
It was an example. For readability, here's my point.

- Currently, `playlist-path` is only set by having mpv loading a playlist.
- mpv uses lazy-loading for playlists.
- `playlist-next-playlist` makes use of `playlist-path` to function.
- Based on the above, use cases that don't function properly with lazy-loading or need explicit placement of items in playlist beforehand, you cannot set `playlist-path`, and thus cannot use `playlist-next-playlist`.

It feels like an arbitrary limitation to not have at least a way to set a file to a playlist on a per-file basis over stdin, or to explicitly load all playlist by having a command-line option for that, or to be able to send in multiple playlists through stdin. Any one of those would allow more complex use cases to enjoy `playlist-next-playlist` navigation.

**Comment by guidocella** [comment]
You can manually mark future entries as playlists by using `--playlist=dir/` instead of stdin. However `playlist-path` seem not to work correctly in that case, breaking playlist-next-playlist. e.g. with mpv foo.mp4 --playlist=/some/dir even foo.mp4's playlist-path is set to /some/dir.

**Comment by Dudemanguy** [comment]
Does the `--playlist` trick solve the problem here? I didn't exactly follow all of it, but if it's simply that playlists are lazy loaded hence skipping around doesn't work, that will get around it.

**Comment by Essoje** [comment]
Sorry about not responding here. Yes, it's solved as far as I can tell.
