### ISSUE TITLE
`mp.add_forced_key_binding()` can't overwrite `MBTN_*_DBL` key in input.conf

### ISSUE THREAD

**Issue by verygoodlee** [mpv-player/mpv#13083]
### Important Information
- mpv version
```
mpv v0.37.0-90-g9b001b44 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Dec 13 2023 00:36:31
libplacebo version: v6.338.0-62-g52314e0-dirty
FFmpeg version: N-112963-g03ac6aa62
FFmpeg library versions:
   libavutil       58.32.100
   libavcodec      60.35.100
   libavformat     60.18.100
   libswscale      7.6.100
   libavfilter     9.14.100
   libswresample   4.13.100
```
- Windows Version 
Win10 22H2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20231213

### Reproduction steps
bind `MBTN_*_DBL` key in input.conf, and force bind same key in test.lua
```
# input.conf
MBTN_LEFT_DBL show-text "left_dbl input.conf"
MBTN_RIGHT_DBL show-text "right_dbl input.conf"
```
```lua
-- test.lua
mp.add_forced_key_binding("MBTN_LEFT_DBL", "MBTN_LEFT_DBL", function() 
    mp.commandv("show-text", "left_dbl test.lua")
end)
mp.add_forced_key_binding("MBTN_RIGHT_DBL", "MBTN_RIGHT_DBL", function() 
    mp.commandv("show-text", "right_dbl test.lua")
end)
```
![image](https://github.com/mpv-player/mpv/assets/45035465/fbbb2982-e95e-4f31-b345-d87b3a63272c)

### Expected behavior
show  "left_dbl test.lua" and  "right_dbl test.lua"

### Actual behavior
show "left_dbl input.conf" and "right_dbl input.conf"

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/13657385/log.txt)

**Comment by guidocella** [comment]
Related to https://github.com/mpv-player/mpv/issues/11154 and fixed by adding `mp.add_key_binding("mouse_move", function() end)`, but `MBTN_RIGHT_DBL` also not being rebindable if it's in `input.conf` is a newly discovered bug.
