### ISSUE TITLE
unbiased multi-cultural holiday logo derivatives

### ISSUE THREAD

**Issue by PurryPlatypus** [mpv-player/mpv#13082]
### Important Information

Provide following Information:
- mpv version: **Every version that includes the Santa hat logo derivative of the MPV logo**
- Platform and Version: **x86, but probably ALL - you wouldn't exclude a platform from this kind of bias**
- Source of the mpv binary: **Ubuntu 23.10 deb repo**
- If known which version of mpv introduced the problem: **uncertain, i've encountered the issue in the version stated in the log file below**
- GPU model, driver and version: **irrelevant - pretty sure about that**
- Possible screenshot or video of visual glitches: **afaik, everything works as intended - it's the intention itself, that's faulty - screenshot in sample files, below**

### Reproduction steps

**I don't need to reproduce the issue with --no-config first, because it's a UX / User Experience issue.**

Describe the reproduction steps as precise as possible: **run the MPV player without a file parameter, just the app. You should get a window that says "Drop files or URLs to play here.", with the MPV logo above. see also, sample file, screenshot, below**

### Expected behavior

ALL THE RELIGIOUS HOLIDAYS, including the ones of The Satanic Temple, and Atheist organisations, should be represented equally! Considering the amount of holidays and potential overlaps in the Gregorian calendar (assumption: pobably the calendar used to calculate the present issue), there might need to appear several specially customised MPV logos. I'd like to suggest additionally, to order those special logos, based on the local systems random number generator - introduces a little spice, every time you start the app, you'd get a different sorting - and no-one can blame the MPV devs for being particularly biased, because it's the individual users busyness which kind of RNG / system they run MPV on. Every Date, that doesn't qualify as a religious holiday should have a randomly selected custom MPV logo that incorporates an Atheist organisations logo "amalgamation" - a derivate of the MPV logo and the organisations logo. If none of the dates qualify as "atheist dates", ALL dates should represent at least one randomly selected "Atheist derivative logo".

### Actual behavior

I haven't tested it exhaustively - simulating every single date of a year - but i've run MPV plenty of times, without specifying a file or playlist, outside of the Christian holiday season - i've never seen custom themed MPV logos, incorporating non-Christian symbolism, half-moons, candle holders, big bhody buddy bellys, Sikh daggers, Tao, Dao, or what ever symbolism everyone else prefers to be identified with. This is not "OK" - FLOSS - Free, as in Libre, Open Source Software MUST BE FOR ALL - include everyone - or just exist, without a particular bias!

### Log file

Social/cultural issue - no log file should be required

Make a log file made with -v -v or --log-file=output.txt, attach it to
the issue, and replace this text with a link to it.
**done, see attachment (where's my log file? I DID attach it! The UI/UX doesn't tell me the current attachment status! 3rd try, my bad, uMatrix extension)**

[output.txt](https://github.com/mpv-player/mpv/files/13657004/output.txt)

Without the log file, this issue will be closed for ignoring the issue template.
**_(turn's out, there's gonna be a mandatory [unambiguously redacted] complete logfile - i wouldn't want this issue thrown out auto-magically, for technical issue-filing issues)_**

In the case of a crash, please provide a backtrace. **social/cultural issue - no backtrace**

### Sample files

**see attachments, due to user-unfriendly UX of https://0x0.st/, i'm not using that service**
![Screenshot from 2023-12-13 07-21-30](https://github.com/mpv-player/mpv/assets/34041223/a7d94e6e-d394-4704-8ab2-9f79b900c244)

Sample files needed to reproduce this issue can be attached to the issue
(preferred), or be uploaded to https://0x0.st/ or similar sites.
(Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Akemi** [comment]
as many times https://github.com/mpv-player/mpv/issues?q=is%3Aissue+logo+is%3Aclosed+ before.

just deactivate it by putting `greenandgrumpy=yes` in the osc.conf or `script-opts=osc-greenandgrumpy=yes` in mpv.conf.

**Comment by PurryPlatypus** [comment]
> as many times https://github.com/mpv-player/mpv/issues?q=is%3Aissue+logo+is%3Aclosed+ before.
> 
> just deactivate it by putting `greenandgrumpy=yes` in the osc.conf or `script-opts=osc-greenandgrumpy=yes` in mpv.conf.

And keep the Christian bias in the default config, excluding EVERYONE else? _Making me_  do work and behave and _FEEL_ like _someone who's the bad guy_ in a society _IS NOT_ how inclusion works!

Either EVERYONE gets included in our happy FLOSS family, or no-one gets a special spot!

**Comment by Akemi** [comment]
fell free to open a PR and try not to exclude yourself or everyone else around you. maybe be a more positive person instead of trying to find issues where there are none.
