### ISSUE TITLE
Allow options in script-opts files having space before and after the equals sign

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#13095]
### Expected behavior of the wanted feature

Allow space before and after the equals sign:

`   scale   =   5   `

In mpv.conf spaces are supported, it doesn't work in script-opts files, so it's inconsistent.

I think this is something that can give noobs a hard time, I remember having struggled with it. There is a warning printed in the terminal, but not all noobs check the console output.

**Comment by guidocella** [comment]
The problem with this is that we would then need to implement quoting for when you do want the trailing or leading spaces. https://github.com/mpv-player/mpv/issues/11170 is related.

**Comment by Dudemanguy** [comment]
Honestly the fact that it works in `mpv.conf` is kind of weird and should be considered an accident. I don't think trying to implement this is worth it and I would recommend just not using spaces in the first place.
