### ISSUE TITLE
Option to disable scrubbing though a video with the scroll wheel

### ISSUE THREAD

**Issue by nick-s-b** [mpv-player/mpv#13096]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
On Sept 2nd, @N-R-K [added](https://github.com/mpv-player/mpv/commit/022dbfc977c3d88cf693ce184c2f86073ae12428) and @sfan5 approved what is one of the most annoying features since Google attached tab switching to a scroll wheel a decade ago: **scrubbing through the video with a scroll wheel.** 

I have my scroll wheel configured so it changes volume when I scroll it and I'm perfectly content with that behavior. But now I randomly scrub through a video when I try to raise or lower the volume and I lose the position in a video. 

If you're going to keep this super-annoying feature, please add an option to completely disable it in a .conf file so I don't have to modify the source myself.

Thank you.

**Comment by llyyr** [comment]
That's not the change which does that. It's this one, you can simply rebind those keys in your input.conf https://github.com/mpv-player/mpv/commit/981a9372ff0034178a986f8bc1ec1ad6b973bb6c

**Comment by llyyr** [comment]
Ah, sorry I misinterpreted. But that change should only do anything if you're doing it while hovering the seekbar. Is it really that big of an issue? I guess it's trivial to add a config to disable all scroll-to-cycle keybinds on the osc.

**Comment by hooke007** [comment]
> so I don't have to modify the source myself.

No you needn't.
Just `osc=no` and use the previous version of osc script instead.

**Comment by N-R-K** [comment]
Out of curiosity, are you using a mouse or a trackpad (or something else) @nick-s-b? I'm trying to understand why this is such a problem because for me accidental scroll has never really been an issue.

**Comment by nick-s-b** [comment]
@llyyr:   
>Is it really that big of an issue?

Yes it is. Especially if the window is small since then you can easily move the mouse over the OSD and you will now be scrubbing through the video that you never intended. 

@N-R-K I use both but the biggest issue is when I use my laptop with the trackpad. I don't have much screen real-estate and I keep my windows small so it's really easy to hover the pointer over the seek bar. I've lost the count of  the number of times I've accidentally scrubbed through the video when I just wanted to lower the volume.

Thanks!
