### ISSUE TITLE
Mpv demuxer-max-bytes= is broken with cache-on-disk=yes

### ISSUE THREAD

**Issue by vertexgamer** [mpv-player/mpv#13097]
### Important Information

Provide following Information:
- mpv version: v0.37.0-81-g443c2487 by shinchiro 64bit v3
- Windows Version: 22H2 build 19045.3803
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20231210-git-443c248.7z/download
- GPU model, driver and version: 3090, game ready 546.33
### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Expected behavior
MPV caching only up to the selected amount of memory with --demuxer-max-bytes=10Mib
### Actual behavior
--demuxer-max-bytes=10Mib actually use 18.2GiB of disk space
### Log file
[logfile.txt](https://github.com/mpv-player/mpv/files/13680611/logfile.txt)

### Sample files
[portable_config.zip](https://github.com/mpv-player/mpv/files/13680621/portable_config.zip)

**Comment by vertexgamer** [comment]
Whoops i forgot to write on Reproduction steps.
Anyway as the title says, `demuxer-max-bytes=` works until `cache-on-disk=yes` is added to the config file

**Comment by vertexgamer** [comment]
Fucking say something.....
Is this being worked on?
Will this be ignored because of low priority?
Was it caused by a mistake on my end?
Or is this intended behaviour?

**Comment by kasper93** [comment]
>  Is this being worked on?

**Comment by kasper93** [comment]
> Is this being worked on?

Yes, we dedicated whole mpv organization resources to this issue. Especially during holiday time it is perfect to pull everyone to work on this critical issue as first priority.

**Comment by vertexgamer** [comment]
Thank god someone noticed the issue.
If you need more info or testing feel free to contact me

**Comment by Dudemanguy** [comment]
```
Note that packet metadata is still kept in memory. --demuxer-max-bytes and related options are applied to metadata only. The size of this metadata  varies, but 50 MB per hour of media is typical. The cache statistics will report this metadats size, instead of the size of the cache file. If the metadata hits the size limits, the metadata is pruned (but not the cache file).
```

Working as intended. Disk cache files are deleted after the file is closed anyways.

**Comment by vertexgamer** [comment]
> > Note that packet metadata is still kept in memory. --demuxer-max-bytes and related options are applied to metadata only. The size of this metadata  varies, but 50 MB per hour of media is typical. The cache statistics will report this metadats size, instead of the size of the cache file. If the metadata hits the size limits, the metadata is pruned (but not the cache file).
> 
> Working as intended. Disk cache files are deleted after the file is closed anyways.

Not working as intended!
Read my issue again and take time to play with it.
I will be available tomorrow night additional questions and testing

**Comment by kasper93** [comment]
> The cache file is append-only. Even if the player appears to prune data, the file space freed by it is not reused. The cache file is deleted when playback is closed.

Cache on disk is literally a hack to dump packets into a file in the most simple way. It doesn't support any size limits and reclaiming used memory.

Patches are welcome, but I would just avoid disk cache, there are really no benefits of using it.
