### ISSUE TITLE
libmpv: How to change force-window/idle OSC text?

### ISSUE THREAD

**Issue by martinrotter** [mpv-player/mpv#13099]
![image](https://github.com/mpv-player/mpv/assets/1255302/0b67e10f-314b-496a-8b18-35ed5a68a6e4)

See the screenshot. This is displayed before media file is loaded. Is there any option/property to change the text?

Thanks many times.

**Comment by guidocella** [comment]
There is no option to change only the text, but the text and logo can be hidden with `--script-opts-append=osc-idlescreen=no`.

**Comment by martinrotter** [comment]
Thanks, closing.
