### ISSUE TITLE
Doesn't support windows7?

### ISSUE THREAD

**Issue by longgong** [mpv-player/mpv#13093]
### Important Information

Provide following Information:
- mpv version    mpv-x86_64-20231210-git-443c248
- Windows Version  windows 7

An error occurs when opening the mpv player on Windows 7。
![2023 12 14_windows7_error](https://github.com/mpv-player/mpv/assets/5051456/c42843fe-0392-4434-8345-8c9de659a28c)

**Comment by llyyr** [comment]
> A not too ancient Linux, Windows 10 or later, or macOS 10.15 or later.

No.

**Comment by verygoodlee** [comment]
#12330

**Comment by CardealRusso** [comment]
microsoft itself dont support w7

**Comment by kasper93** [comment]
FWIW, it works with shinchiro's `mpv-x86_64-gcc-` build, which were added for Windows 7 support. There is nothing in mpv that prevents running on Windows 7 currently. But we do not support this platform and it can break anytime.

See: https://github.com/shinchiro/mpv-winbuild-cmake/issues/445

**Comment by denczy** [comment]
> FWIW, it works with shinchiro's `mpv-x86_64-gcc-` build, which were added for Windows 7 support. There is nothing in mpv that prevents running on Windows 7 currently. But we do not support this platform and it can break anytime.
> 
> See: [shinchiro/mpv-winbuild-cmake#445](https://github.com/shinchiro/mpv-winbuild-cmake/issues/445)

It does not work on Windows 7 x64  with the error posted by longgong

**Comment by denczy** [comment]
> ### Important Information
> Provide following Information:
> 
> * mpv version    mpv-x86_64-20231210-git-443c248
> * Windows Version  windows 7
> 
> An error occurs when opening the mpv player on Windows 7。 ![2023 12 14_windows7_error](https://private-user-images.githubusercontent.com/5051456/290395578-c42843fe-0392-4434-8345-8c9de659a28c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MTMwNTYsIm5iZiI6MTcwMzcxMjc1NiwicGF0aCI6Ii81MDUxNDU2LzI5MDM5NTU3OC1jNDI4NDNmZS0wMzkyLTQ0MzQtODM0NS04YzlkZTY1OWEyOGMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMjEzMjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q1NTI2M2NiMWFiYTFhODEwOGU3Y2M1NjczNDhmNzhjNWRkOTQ2YzVkYTU5YzdlYjM3ZjJkNTJiYTE1ZjM1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.OCqyvj4NWi57Klq5OEPsh5pEMx5Brm1OWcD9zgZ41SQ)

it seems lates work build for Windows 7 64 bit is https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20230827-git-83c0e98.7z/download

**Comment by sergeevabc** [comment]
After wading through the swamp of dead links and developers' disdain for less privileged, fortunate, and Window10nightmare-minded users outside of the golden billion, I found a more recent version of MPV that works fine on Windows 7 x64. 

https://github.com/eko5624/mpv-win64/releases
Kudos to @eko5624, he's the hero of the day.

``` console
$ mpv.com --version
mpv v0.37.0-525-g1bf821ebdc Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Mar 11 2024 06:01:20
libplacebo version: v7.347.0 (v6.338.0-102-g0d3542d7)
FFmpeg version: N-114099-gc31d232656
FFmpeg library versions:
   libavutil       59.1.100
   libavcodec      61.1.100
   libavformat     61.0.100
   libswscale      8.0.100
   libavfilter     10.0.100
   libswresample   5.0.100
```

Backup copy of MPV static build 2024-03-11 in case something happens.

**Comment by i486** [comment]
FYI: Latest build on sourceforge (mpv-x86_64-v3-20240317-git-3afcaeb) works fine with [VxKex](https://github.com/vxiiduu/VxKex/)

**Comment by Templayer** [comment]
The newest available portable package in Chocolatey works (with VxKex - but only if I set VxKex on the executable and not on a shortcut to the executable, which is curious), but it CTDs without any error logs when trying to play a live Twitch stream (tested on https://www.twitch.tv/aulddragon - that is also the URL used).

Playing other files (like youtube downloads in .webm) works fine.
