### ISSUE TITLE
about --watch-later-options=

### ISSUE THREAD

**Issue by AdventurerRussia** [mpv-player/mpv#13090]
in version 0.36, everything worked fine before with remembering the stop location
0.37 broke something

I had a parameter and the pause was remembered

`--watch-later-options=secondary-sid,sub-visibility,sub-border-size,sub-ass-override,border,contrast,brightness,gamma,saturation,hue,video-zoom,video-rotate,video-pan-x,video-pan-y,panscan,speed,audio,sub,audio-delay,sub-pos,sub-scale,sub-delay,sub-speed,volume,`

now, just turning on the --watch-later-options= parameter
does not remember the pause without any words

just the line --watch-later-options= causes this
in version 0.36, everything was fine with this. but the new one broke it for some reason.

is there any new separate keys for the pause to be remembered? I just don't understand why the last time is not remembered now.

**Comment by guidocella** [comment]
`--watch-later-options-append=pause`

**Comment by AdventurerRussia** [comment]
> `--watch-later-options-append=pause`

I probably put it wrong, so you opened the video at 10 minutes and closed it, then opened it and it started playing again.

**Comment by guidocella** [comment]
`start` used to be implicitly included in `--watch-later-options`, but you now have to specifiy it, but this changed in 0.36, not 0.37.

**Comment by AdventurerRussia** [comment]
> `start` used to be implicitly included in `--watch-later-options`, but you now have to specifiy it, but this changed in 0.36, not 0.37.

Thank you very much
I also wanted to ask about  in input.conf `u cycle-values sub-ass-override "force" "yes"`

previously, when I clicked, the design immediately changed, now it changes only after restarting the player, everything was fine with this until the new version of the player, the design changed immediately, I went through all the parameters of the configuration file and kind of found that with --autofit= enabled, the design does not change now, but it somehow

It's all very strange,

**Comment by guidocella** [comment]
`u` changed from `cycle-values sub-ass-override force no` to use `cycle-values sub-ass-override force yes`.

**Comment by AdventurerRussia** [comment]
in short, nothing worked, the design also changes after restarting the player,
Thanks for that too

**Comment by llyyr** [comment]
while the `u` keybind did change, it shouldn't have caused sub styles to not update at runtime. Does changing the keybind actually fix the issue somehow?

**Comment by guidocella** [comment]
If you change `sub-ass-override` with `--cache`, subtitles are not updated until the next seek.

**Comment by guidocella** [comment]
It's caused by 062104d16e

**Comment by guidocella** [comment]
Yeah it was actually already broken with ASS subtitles before that commit, the difference I noticed is that with that commit even plain text subtitles disappear with `--cache` by changing `sub-ass-override`.

**Comment by Dudemanguy** [comment]
I think the cache needs to be dropped like what happens when you switch subtitle tracks.
