### ISSUE TITLE
Windows 7 can not open the latest version(from20230924 to latest version)

### ISSUE THREAD

**Issue by gh491** [mpv-player/mpv#13103]
### Important Information

Provide following Information:
- mpv version (from20230924 to latest version)
- Windows Version Windows 7 SP1
It show"The program input point could not be located" GetSystemTimePreciseAsFileTime..."

**Comment by CounterPillow** [comment]
See #13093 and https://github.com/mpv-player/mpv/issues/12330

mpv doesn't support Windows 7.

**Comment by gh491** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by kasper93** [comment]
FWIW, it works with shinchiro's `mpv-x86_64-gcc-` build, which were added for Windows 7 support. There is nothing in mpv that prevents running on Windows 7 currently. But we do not support this platform and it can break anytime.

See: https://github.com/shinchiro/mpv-winbuild-cmake/issues/445
