### ISSUE TITLE
about secondary-sub-pos in input.conf

### ISSUE THREAD

**Issue by AdventurerRussia** [mpv-player/mpv#13115]
in the documentation, it is possible to change their location, but it does not allow changing them through the keys and shows this
https://mpv.io/manual/master/#options-secondary-sub-pos
does the player not know how to change through the keys yet?

![image](https://github.com/mpv-player/mpv/assets/14019010/a577d1a6-4327-48c4-8574-915cce41c16f)

The code did this
```
r add secondary-sub-pos +1
t add secondary-sub-pos -1
```

**Comment by guidocella** [comment]
It requires git master.

**Comment by hooke007** [comment]
Though you already chose to stay with stable version. Then read the proper manual instead. https://mpv.io/manual/stable/
