### ISSUE TITLE
fake hd, 4:3 to 16:9 via mirroring and blurring the edges

### ISSUE THREAD

**Issue by runlow** [mpv-player/mpv#13114]
Hello. There's an effect I sometimes see applied to videos in different aspect ratios than the expected aspect ratio. Instead of the usual black area on the screen, a portion of the corresponding edge is copied to that area, and then blurred.

Example:
https://www.youtube.com/watch?v=pd4Mz8I15CM

What I'm interested in is whether there's some way to have `mpv` do that but for normal viewing (on the fly), and if someone already figured out how to do this. If this is not possible that's OK, just wondering. Part of the difficulty with this for me is that I'm not sure what this effect or filter is called so unsure how to look it up. My knowledge of how the filters work is not sufficient yet either, but still learning. I appreciate any feedback. Thanks in advance.

**Comment by dexeonify** [comment]
[blur-edges.lua](https://github.com/occivink/mpv-scripts#blur-edgeslua) is a script that does just that, but currently it immediately crashes on full-screen (occivink/mpv-scripts#73)

**Comment by hooke007** [comment]
It uses https://ffmpeg.org/ffmpeg-filters.html#boxblur in lavfi-complex.
This is slow because all runs on cpu.
