### ISSUE TITLE
[ffmpeg] Failed to initialise VAAPI connection: -1 (unknown libva error).

### ISSUE THREAD

**Issue by SacredZenpie** [mpv-player/mpv#13110]
- MPV 0.37 shinchiro
- Windows 10 21H2 LTSC
- Issue was not present in 0.36 (and is not present in the least git)
- Notebook GTX 1660ti (latest driver, display over HDMI), IGPU is UHD 630 (not in use due to the video out being on nvidia card)

### Reproduction steps
Play H264 10bit video with hwdec=auto-safe

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/13689673/mpv.log)

**Comment by sfan5** [comment]
That's not a fatal error.

**Comment by CounterPillow** [comment]
You're trying to hardware decode 10-bit H.264, which won't work on most hardware. mpv is correctly trying each available hardware decoding method in order here and then falling back to software decoding, as it should.

**Comment by SacredZenpie** [comment]
Im more than aware the decoding 10 bit h264 doesnt work on most hardware, just noticed that the error msg thats not present in latest git or 0.36. thought it was worth reporting.

**Comment by Dudemanguy** [comment]
I presume the error message is because of the change in behavior with `auto-safe`. The reason git master doesn't have it is because VAAPI is supported on windows now (0.37 didn't). So that's likely the difference.
