### ISSUE TITLE
Documentation on `--replaygain-clip` flag is incorrect

### ISSUE THREAD

**Issue by dweymouth** [mpv-player/mpv#13111]
The documentation on the `--replaygain-clip` parameter [states](https://mpv.io/manual/stable/#options-replaygain-clip):

> Prevent clipping caused by replaygain by automatically lowering the gain (default). Use --replaygain-clip=no to disable this.

This implies that yes means to lower the gain if needed to prevent clipping, and no means allowing clipping to occur. But the [actual implementation](https://github.com/mpv-player/mpv/blob/054dde0424dd657a6426ce6ba50debccf6ba99cb/player/audio.c#L155) is reversed (i.e. yes means "allow clipping").

I would suggest that the *documentation*, rather than the implementation, be updated. Applications using MPV as a playback backend may already use the setting as it's implemented, rather than as it's documented, and changing the documentation would not be a breaking change.

### Important Information

Provide following Information:
- mpv version **0.37.0**

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

N/A - documentation error

**Comment by Dudemanguy** [comment]
Yes indeed the documentation seems backwards. It was added all together in f1c4d20e6577f32018e20efc4ab9da7d4e1ab4ac. I'm going to assume the documentation was just incorrect and the current code implementation was intended (plus it's not a breaking change as you mentioned).
