### ISSUE TITLE
`ytdl:` scheme is not properly constructed

### ISSUE THREAD

**Issue by WovenTales** [mpv-player/mpv#13122]
### Important Information

Provide following Information:
- mpv version: 0.35.1
- Platform and Version: MX Linux 21.3
- Source of the mpv binary: Debian package repo

### Reproduction steps
```shell
$ mpv ytdl:drNdQ_8NKgU
[file] Cannot open file 'ytdl:drNdQ_8NKgU': No such file or directory
Failed to open ytdl:drNdQ_8NKgU.

Exiting... (Errors when loading file)
```

### Expected behavior
This isn't a serious issue, and I don't necessarily expect any action on it, but since I just hit it yet again I wanted to document a minor pain point I have with the CLI.

MPV uses `ytdl:` as if it were a scheme to trigger loading the file through youtube-dl rather than reading the file off disc; I keep expecting this to be patterned as if it were an actual scheme, and trying to load videos via `ytdl:drNdQ_8NKgU` which is technically a relative path but could be subject to scheme-specific processing saying that the payload is a YouTube video ID.

### Actual behavior
Instead it's implemented as a prefix `ytdl://` *requiring* the two slashes, which are [officially used](https://www.rfc-editor.org/rfc/rfc2718#section-2.1.2) to indicate the authority.  If it were strictly read, `ytdl://drNdQ_8NKgU` would not point to a video on YouTube, but instead to the root of some unknown service with an unreadable address -- the most-compliant use would be something like `ytdl://youtube/drNdQ_8NKgU` (which would coexist with other platforms like `ytdl://twitch/2002635362`).

Again, this is more me having too much exposure to URIs and getting tripped up rather than something which actually needs changing.  Given complete control and infinite developer time, my ideal feature *would* be extending the syntax across the range of platforms youtube-dl supports via that authority component, but, A, it's no more difficult to just copy the full URL rather than just the ID and, B, that's actually in the scope of what youtube-dl/yt-dlp should be doing (to define the authorities alongside the actual platforms/URLs supported).  Realistically, the only change I'm asking for is to recognize both `ytld://` and `ytdl:` forms, and even that's not pressing.

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/13693234/mpv.log)

**Comment by po5** [comment]
What problem are you trying to solve?

**Comment by WovenTales** [comment]
Sorry if it wasn't clear: I keep expecting `mpv ytdl:drNdQ_8NKgU` to work (because I know that the ID isn't an authority component and so write out a URI with it as a bare "path"), but it doesn't because only `mpv ytdl://drNdQ_8NKgU` is recognized (in analogy under the assumption that the "prefix part" of `https://youtube.com/...` is `https://` rather than the actual division of `https:` and `//youtube.com/...`).

**Comment by po5** [comment]
We already draw a line in the sand for this, [even for schemes which traditionally do not have `://`](https://mpv.io/manual/master/#protocols)
> `data:` is supported in FFmpeg (not in Libav), but needs to be in the format `data://`. This is done to avoid ambiguity with filenames. You can also prefix it with `lavf://` or `ffmpeg://`.

**Comment by WovenTales** [comment]
I'm not surprised it's being used as a means to distinguish them from filenames, but I hadn't seen that callout.  (I also disagree that it's necessary -- even if you have a file named `data:something`, which would be very unlikely, you could still just point to it as `file:data:something` -- but it's a minor inconvenience on my side for a minor gain on yours, so a net wash.)  The main things I want to underscore are that at that point you're not using "scheme" as it's defined in the context of URIs but rolling your own system (which is fine), and that the "schemes with traditionally..." language is incorrect as *no* URI scheme has the `//`, but, again, all just minor nits being picked over.
