### ISSUE TITLE
truehd audio decoder missing since mpv windows version mpv-x86_64-v3-20231218-git-702b3eb

### ISSUE THREAD

**Issue by maartinsd** [mpv-player/mpv#13138]
Important Information

Provide following Information:
- mpv version: mpv-x86_64-v3-20231219-git-17be6e1
- Platform and Version: Windows 10 Home 22H2 19045.3803

mpv does not play the Dolby TrueHD audio track, video is displayed correctly. I checked with --ad=help: the truehd decoder is missing from the decoder list. In mpv-x86_64-v3-20231211-git-566a96f everything works fine and there is a truehd decoder in the decoder list.

**Comment by CounterPillow** [comment]
What is and isn't enabled in a build (in this case, the underlying ffmpeg build) is up to the person who makes this build for you. In this case, this appears to be shinchiro. It appears the repository where they maintain their build automation is at https://github.com/shinchiro/mpv-winbuild-cmake which I presume is where this issue report is more appropriate.

**Comment by richardpl** [comment]
Failed to find any error that needed this drastic change in that repo.

**Comment by CounterPillow** [comment]
They also did not open a bug report with FFmpeg at all (or even mention what the problem was in the commit that disabled it) so it's truly a mystery why Andarwinux thinks anyone would know what they're talking about, or care for that matter.

**Comment by richardpl** [comment]
Ugh, that is inline and mmx code (two ugly stuff at same time). I bet speed benefits from this code for x86 is today marginal.
