### ISSUE TITLE
Can a libmpv frontend support string list and path list command line options?

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#13132]
Can a libmpv frontend support string list and path list command line options such as `--display-tags-append`?

If so, how does it work? I could, of course, do it with string processing, but would this work for all string list and path list and key/value list options? Where can I find the code in mpv that handles it?

I ask because of a feature request or bug report found [here](https://github.com/mpvnet-player/mpv.net/issues/619).

I checked if ImPlay supports it, it doesn't @tsl0922.

**Comment by tsl0922** [comment]
I didn't know there're some option like it, so it's not supported by ImPlay.

**Comment by stax76** [comment]
> I didn't know there're some option like it, so it's not supported by ImPlay.

In mpv such options are supported on the command line and in mpv.conf. I think it was just recently requested for the first time to support in mpv.net.

**Comment by stax76** [comment]
I believe [change-list](https://mpv.io/manual/master/#command-interface-change-list) is how it's supposed to be done.

**Comment by verygoodlee** [comment]
In this Tampermonkey script, it was also found that mpv.net does not support `--script-opts-append`
https://github.com/LuckyPuppy514/Play-With-MPV/blob/915b64637f49db770ea1d3fe675769b4eab510a5/play-with-mpv.user.js#L2017-L2023
