### ISSUE TITLE
yt-dlp don't load non-cached video

### ISSUE THREAD

**Issue by mooreye** [mpv-player/mpv#13144]
### Important Information

Fedora 39
mpv 0.36.0
yt-dlp 2023.11.16

### Reproduction steps

Run any youtube URL with mpv. Then click on a part of video on OSD that is not yet cached.

### Expected behavior

it will play video from that clicked point

### Actual behavior

It plays only audio while the video freezes.

### Log file
[
[log.txt](https://github.com/mpv-player/mpv/files/13740514/log.txt)
](url)

**Comment by Dudemanguy** [comment]
Sounds like just a yt-dlp issue (the video not being fetched)? Probably google being poopheads or such. I don't think there's anything we can do about it and I cannot reproduce anyways.

**Comment by toprak** [comment]
@Dudemanguy 
I can watch yt videos with mpv+yt-dlp with
```
cache=no
cache-pause=no
cache-pause-initial=no
demuxer-max-bytes=18009999M
demuxer-max-back-bytes=12009999M
demuxer-cache-wait=yes
```
but can't with is it expected? running w11 23h2 mpv 0.37
```
cache=yes
cache-pause=yes
cache-pause-initial=yes
cache-secs=1700
demuxer-max-bytes=18009999M
demuxer-max-back-bytes=12009999M
demuxer-cache-wait=yes
```

**Comment by mooreye** [comment]
> @Dudemanguy I can watch yt videos with mpv+yt-dlp with
> 
> ```
> cache=no
> cache-pause=no
> cache-pause-initial=no
> demuxer-max-bytes=18009999M
> demuxer-max-back-bytes=12009999M
> demuxer-cache-wait=yes
> ```
> 
> but can't with is it expected? running w11 23h2 mpv 0.37
> 
> ```
> cache=yes
> cache-pause=yes
> cache-pause-initial=yes
> cache-secs=1700
> demuxer-max-bytes=18009999M
> demuxer-max-back-bytes=12009999M
> demuxer-cache-wait=yes
> ```

On Linux I can watch with both configs, but the problem with only audio playing on skip to uncached part is present in both.

**Comment by toprak** [comment]
weird

**Comment by guidocella** [comment]
```
[youtube]
profile-cond=path:find('youtu%.?be')
cache=no
```
