### ISSUE TITLE
Toggling specific metadata with a keypress

### ISSUE THREAD

**Issue by Baerbeisser** [mpv-player/mpv#13141]
I use mpv with a "audio-only" conditional profile to play songs.
Now some songs have whole lyrics in the "comments" meta tag.
Shortened Example:

```
Playing: Strangers - Kenya Grace.ogg
[auto_profiles] Applying auto profile: audio-only 
 (+) Audio --aid=1 'Kenya-Grace---Strangers-(Official-Lyric-Video)' (opus 2ch 48000Hz)
File tags:
 Artist: Kenya-Grace
 Comment: Listen to 'Strangers' here: https://majorrecordings.lnk.to/strangers

Follow Kenya Grace:
https://www.instagram.com/kenyagrace
https://www.tiktok.com/@kenyagracebaby
https://www.youtube.com/@kenyagracebaby/

Lyrics:
It always ends the same
-----------------------
and we’ll go back to strangers 

Uh huh uh huh

#KenyaGrace #Strangers
 Date: 20230901
 Title: Kenya-Grace---Strangers-(Official-Lyric-Video)
Title: Kenya-Grace---Strangers-(Official-Lyric-Video)
```
The extensive comments are usually annoying but Lyrics are pretty nice sometimes, which is why i don't want to remove them from the file.

Is there some (script) way to hide the comment tag and show it only on keypress on console?
Or alternatively, a script/tool to load remote/local lyrics?

**Comment by guidocella** [comment]
`display-tags-remove=Comment`
`print-text ${metadata/Comment}`

**Comment by guidocella** [comment]
Regardings your edit, https://github.com/guidocella/mpv-lrc downloads synchronized lyrics
