### ISSUE TITLE
Subtitles freeze with cache=yes

### ISSUE THREAD

**Issue by carycary246** [mpv-player/mpv#13148]
Provide following Information:
- mpv version: latest shinchiro release
- Windows Version: win 11
- If known which version of mpv introduced the problem - no issues with Nov 5 shinchiro build but broken on all builds after

### Reproduction steps
Subtitles will freeze when cycling using default hotkey u to toggle between ass style override 'yes' and 'force' with cache=yes in mpv.conf
No issues with no config

### Expected behavior
Subtitles do not freeze and continue rendering

### Actual behavior
Subtitles freeze and do not return until seek or turning on/off subtitle

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/13747010/output.txt)

**Comment by Dudemanguy** [comment]
Yeah that was discussed a bit [here](https://github.com/mpv-player/mpv/issues/13090#issuecomment-1855916981). I turns out that all of the `UPDATE_SUB_HARD` options are completely broken when using cache and I recently added the ass style override one to that subset of options.
