### ISSUE TITLE
sub: apple subtitle style option configure

### ISSUE THREAD

**Issue by karelrooted** [mpv-player/mpv#13140]
hey there,  I was wondering if anyone already has this apple style subtitle option set up and kindly share the configure

![Screenshot 2023-12-20 at 11 24 25 PM-min](https://github.com/mpv-player/mpv/assets/523980/d2da4b87-467c-4bb1-a6e7-ee1a9c017b9f)

I was trying to duplicate the above apple subtitle style on mpv without luck

the apple subtitle style in swiftui style code is something like this
```swift
Text("example subtitle")
  .font(.caption)
  .foregroundColor(.white)
  .padding()
  .background(Color.black.opacity(0.7))
  .cornerRadius(10)
```

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt,
attach it to the issue, and replace this text with a link to it.

**Comment by natural-harmonia-gropius** [comment]
this is almost same config.

```ini
sub-font-size=36
sub-back-color=0.0/0.0/0.0/0.75
sub-border-size=0
sub-shadow-offset=4
sub-shadow-color=0.0/0.0/0.0/0.0
```

**Comment by karelrooted** [comment]
thanks.. working like a charm..!
