### ISSUE TITLE
Forced subtitles don't play with `subs-with-matching-audio=no`

### ISSUE THREAD

**Issue by dawidpotocki** [mpv-player/mpv#13151]
### Important Information

Provide following Information:
- mpv version: https://github.com/mpv-player/mpv/commit/fe875083b3d30b06ef77745f40570e8f63afec2, 0.37.0 and master
- Platform and Version: Linux
- Source of the mpv binary: Arch Linux, Flathub, own build
- If known which version of mpv introduced the problem: https://github.com/mpv-player/mpv/commit/fe875083b3d30b06ef77745f40570e8f63afec2
- GPU model, driver and version: N/A
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

1. Set the following options:
    ```
    slang=en
    alang=en
    subs-with-matching-audio=no
    ```
2. Play sample video with forced subtitles
3. Forced subtitles don't play because of `subs-with-matching-audio=no`

### Expected behavior

`subs-with-matching-audio=no` doesn't disable forced subtitles.

> If this option is ***set to no***, a ***non-forced subtitle track*** that matches
> the audio language will never be autoselected by mpv regardless of the value
> of --slang or --subs-fallback.
> https://mpv.io/manual/master/#options-subs-with-matching-audio

### Actual behavior

`subs-with-matching-audio=no` disables forced subtitles.

### Possible solution

Adding back `!forced_pick` to the following line:
https://github.com/mpv-player/mpv/commit/fe875083b3d30b06ef77745f40570e8f63afec2b#diff-4f48c8482f05d304fcb498577e82e4db5049cf650e20e7bc1493a0e84457960aR678

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/13751368/output.txt)
```
[   0.002][v][cplayer] Setting option 'slang' = 'en' (flags = 4)
[   0.002][v][cplayer] Setting option 'alang' = 'en' (flags = 4)
[   0.002][v][cplayer] Setting option 'subs-with-matching-audio' = 'no' (flags = 4)

[   0.021][v][mkv] select track 0
[   0.021][v][mkv] select track 1
[   0.021][i][cplayer]  (+) Video --vid=1 (*) (h264 640x480 30.000fps)
[   0.021][i][cplayer]  (+) Audio --aid=1 --alang=eng (*) 'EN' (opus 2ch 48000Hz)
[   0.021][i][cplayer]      Audio --aid=2 --alang=pol (*) 'PL' (opus 2ch 48000Hz)
[   0.021][i][cplayer]      Subs  --sid=1 --slang=eng (*) 'EN' (subrip)
[   0.021][i][cplayer]      Subs  --sid=2 --slang=eng (f) 'EN - Forced' (subrip)
[   0.021][i][cplayer]      Subs  --sid=3 --slang=pol (*) 'PL' (subrip)
[   0.021][i][cplayer]      Subs  --sid=4 --slang=pol (f) 'PL - Forced' (subrip)
```

[output-with-fix.txt](https://github.com/mpv-player/mpv/files/13751367/output-with-fix.txt)
```
[   0.002][v][cplayer] Setting option 'slang' = 'en' (flags = 4)
[   0.002][v][cplayer] Setting option 'alang' = 'en' (flags = 4)
[   0.002][v][cplayer] Setting option 'subs-with-matching-audio' = 'no' (flags = 4)

[   0.016][v][mkv] select track 0
[   0.016][v][mkv] select track 1
[   0.016][v][mkv] select track 4
[   0.016][i][cplayer]  (+) Video --vid=1 (*) (h264 640x480 30.000fps)
[   0.016][i][cplayer]  (+) Audio --aid=1 --alang=eng (*) 'EN' (opus 2ch 48000Hz)
[   0.016][i][cplayer]      Audio --aid=2 --alang=pol (*) 'PL' (opus 2ch 48000Hz)
[   0.016][i][cplayer]      Subs  --sid=1 --slang=eng (*) 'EN' (subrip)
[   0.017][i][cplayer]  (+) Subs  --sid=2 --slang=eng (f) 'EN - Forced' (subrip)
[   0.017][i][cplayer]      Subs  --sid=3 --slang=pol (*) 'PL' (subrip)
[   0.017][i][cplayer]      Subs  --sid=4 --slang=pol (f) 'PL - Forced' (subrip)
```

### Sample files

[Example Matroska file](https://github.com/mpv-player/mpv/files/13751386/example.zip)
(zipped because GitHub doesn't allow putting Matroska files by itself, *sighs*)

**Comment by Dudemanguy** [comment]
Hmm yeah I suppose I forgot that `subs-with-matching-audio=no` actually was supposed to mean forced subtitles not no subtitles. This should probably be made into a tristate option to avoid confusion.
