### ISSUE TITLE
path to subtitle tracks during switching

### ISSUE THREAD

**Issue by AdventurerRussia** [mpv-player/mpv#13156]
Is there any way to show the path to the subtitle file while switching tracks? I have subtitles from different teams in folders with the same names, but the folders have the name of the team, can I just display the path in the notification? 

![image](https://github.com/mpv-player/mpv/assets/14019010/94dda5f0-a85a-4f67-966c-14ae45df156e)

**Comment by guidocella** [comment]
`no-osd cycle sid; show-text ${current-tracks/sub/external-filename:${sid}}`

**Comment by AdventurerRussia** [comment]
> `no-osd cycle sid; show-text ${current-tracks/sub/external-filename:${sid}}`

If I assign it to a key, the path is displayed, can I assign it to an icon in the interface?

**Comment by guidocella** [comment]
You would have to modify `osc.lua`, or use an alternative OSC that allows that.

**Comment by AdventurerRussia** [comment]
> You would have to modify `osc.lua`, or use an alternative OSC that allows that.

I understand these lines need to be changed 
![image](https://github.com/mpv-player/mpv/assets/14019010/d23cc2ac-f7af-4034-81fe-20be733049e9)
