### ISSUE TITLE
Using `❙` in `--term-osd-bar-chars` causes the OSD to be repainted one line higher, eating the terminal screen

### ISSUE THREAD

**Issue by globau** [mpv-player/mpv#13150]
### Important Information

Provide following Information:
- mpv version: **mpv v0.36.0-977-g3250f6e447**
- macOS Version: **14.2.1 (23C71)**
- Source of the mpv binary or bundle: **built locally from git**
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

https://github.com/mpv-player/mpv/assets/872825/c7f00cb4-0731-4db3-a8e4-d58e275661ee

### Reproduction steps

Play an mp3 with `--term-osd-bar-chars=--❙--` - that's U+2759 (Medium Vertical Bar)

`mpv --no-video --no-resume-playback --no-save-position-on-quit --no-config --term-osd-bar '--term-osd-bar-chars=--❙--' Yazoo\ -\ Only\ You\ \[1982\].mp3`

### Expected behavior

OSD remains on the same line.

### Actual behavior

OSD walks up the screen.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/13749053/mpv.log)

### Sample files

N/A

### Notes

* other osd-bar-chars do not have this problem
* this used to work; unfortunately I don't have time to bisect right now
* replacing all osd chars with U+2759 make it chomp up the screen faster
* this is clearly a minor cosmetic issue; there's plenty of viable alternative characters, but it made me chuckle so y'all get to see it too

**Comment by dexeonify** [comment]
Probably one of [these commits](https://github.com/mpv-player/mpv/compare/477a0f8...82451bd). It happens on Windows too. Quite a destructive bug because it can overwrite your entire shell output from your current terminal session, but I guess most people don't change the default `term-osd-bar-chars`.

**Comment by kasper93** [comment]
Will be fixed by #13153
