### ISSUE TITLE
Special character binds are only interpretted in the terminal window, and not mpv

### ISSUE THREAD

**Issue by diniamo** [mpv-player/mpv#13174]
### Important Information

Provide following Information:
- mpv version: 0.36.0, patched for vapoursynth (https://aur.archlinux.org/packages/mpv-vapoursynth-git)
- Linux Distribution and Version: Arch Linux, kernel 6.6.8
- Source of the mpv binary: the aur package above
- Window Manager and version: Wayland/wlroots/**Hyprland**, I follow git v0.33.1-85-gb25b0643
- GPU model, driver and version: Intel N100, also happens on Nvidia Geforce GTX 1660 TI

### Reproduction steps

1. Bind something to a special character (e.g.: öüóőúéáű)
2. Open a video with mpv from a terminal
3. Press the bind in the mpv window
4. Press the bind in the terminal window
5. Observe

### Expected behavior

The bind works both ways

### Actual behavior

The bind doesn't work in the mpv window

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/13782033/log.txt)

**Comment by Dudemanguy** [comment]
Should be fixed in 0.37 (specifically this commit: 48eb77207bff01ae766a9fb33b4e4c35cfad62c9)
