### ISSUE TITLE
Shift+arrow seek has the same effect as arrow alone (verified using input.conf)

### ISSUE THREAD

**Issue by yue-dongchen** [mpv-player/mpv#13176]
### Important Information

Provide following Information:
- mpv version: `0.37.0` (Snap and Flatpak), `0.36.0-1ubuntu1` (apt)
- Linux Distribution and Version: Ubuntu 23.10 with GNOME 45.1
- If known which version of mpv introduced the problem: 🤷
- Window Manager and version: Mutter (Wayland)

### Reproduction steps

Without `input.conf`, `Shift`+`Left`/`Right` seeks by ±5s.
With `input.conf` set to
```
LEFT  seek -20
Shift+LEFT  no-osd seek -1 exact
```
`Shift`+`Left` seeks by -20s.

### Expected behavior
The default behaviour should be the described 1s, and it should be configurable via `input.conf`.

### Actual behavior
As described in the _reproduction steps_.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/13785623/output.txt)
(I forwarded it to about 20s. Then I pressed `Shift+Left`, `Shift+Right`.)

**Comment by sfan5** [comment]
Can't reproduce on X11.

**Comment by Dudemanguy** [comment]
Works for me on sway 1.8.1 and mutter 45.2

**Comment by yue-dongchen** [comment]
Thanks for the replies. I will try sometime with X11.

**Comment by llyyr** [comment]
Can you run mpv with `WAYLAND_DEBUG=1 mpv --no-config --idle --input-test --force-window` and show the terminal output?

cc @xHire

**Comment by xHire** [comment]
Sure.

[mpv_debug.txt](https://github.com/mpv-player/mpv/files/13927813/mpv_debug.txt)

**Comment by llyyr** [comment]
I'm assuming this PGUP keypress was supposed to be Shift+PGUP? According to the wayland debug output, you never pressed Shift.

```
[ 677404.425]  -> wl_display@1.sync(new id wl_callback@43)
[ 677404.436] wl_display@1.delete_id(42)
[ 677404.438] wp_presentation_feedback@42.sync_output(wl_output@22)
[ 677404.440] wp_presentation_feedback@42.presented(0, 21111, 580966000, 16667500, 0, 303328, 7)
[ 677404.443] wl_keyboard@33.key(26896, 21111590, 104, 1)

[input] Key PGUP is bound to:
[input] 1.  'add chapter 1' in <builtin>:1 (default)

[KV: 00:00:00 / 00:00:39 (1%)
[ 677404.576] wl_display@1.delete_id(43)

```

It's probably an issue further up in the stack, mpv never receives a modifier key

**Comment by xHire** [comment]
For comparison, I managed to downgrade to 0.35.0, which was my previous version (where I knew it worked), and re-run the command (again pressing Shift+PgUp, just as before).

[mpv_debug-0.35.0.txt](https://github.com/mpv-player/mpv/files/13928091/mpv_debug-0.35.0.txt)

**Comment by xHire** [comment]
A friend of mine (who is also affected by this bug) noticed (while watching terminal output) that the press of Shift key is properly registered (with 0.37.0):

```
[1387515.192] wl_keyboard@33.key(15970, 4021776, 42, 1)
[1387515.273] wl_keyboard@33.modifiers(15971, 1, 0, 16, 0)
[1387931.503] wl_keyboard@33.key(15972, 4022192, 42, 0)
[1387931.557] wl_keyboard@33.modifiers(15973, 0, 0, 16, 0)
```

The first two lines were emitted when they pressed Shift, the latter when they released it.

**Comment by llyyr** [comment]
Can you try bisecting it? It's hard to say what might've caused it since I can't reproduce it myself

**Comment by xHire** [comment]
```
1f8013ff3fddd788a517656e09f5ce5d7efd928d is the first bad commit
commit 1f8013ff3fddd788a517656e09f5ce5d7efd928d
Author: Dudemanguy <random342@airmail.cc>
Date:   Sat Jul 15 14:20:27 2023 -0500

    wayland: handle modifier keys correctly
```

**Comment by llyyr** [comment]
Are you using any xkb options ( https://github.com/mpv-player/mpv/pull/11946#issuecomment-1637031614 ) or perhaps a non-english keyboard layout?

**Comment by xHire** [comment]
Hm, yes, I use `grp:shifts_toggle` too.

My understanding of all the debugging data is limited, but I don’t think the claim in the last comment (“The compositor doesn't give us the modifier press in the logs with that option enabled for whatever reason.”) is accurate?

Without Shift:

```
[ 129310.937] wp_presentation_feedback@38.sync_output(wl_output@22)
[ 129310.939] wp_presentation_feedback@38.presented(0, 33448, 406616000, 16667500, 0, 936508, 7)
[ 131535.679] wl_keyboard@33.key(59163, 33450630, 104, 1)
[input] Key PGUP is bound to:
[input] 1.  'add chapter 1' in <builtin>:1 (default)
```

With Shift:

```
[ 132561.179] wp_presentation_feedback@38.sync_output(wl_output@22)
[ 132561.182] wp_presentation_feedback@38.presented(0, 33451, 656813000, 16667500, 0, 936703, 7)
[ 132819.634] wl_keyboard@33.key(59165, 33451914, 42, 1)
[ 132819.654] wl_keyboard@33.modifiers(59166, 1, 0, 0, 0)
[ 133554.997] wl_keyboard@33.key(59167, 33452650, 42, 0)
[ 133555.016] wl_keyboard@33.modifiers(59168, 0, 0, 0, 0)
[ 134373.271] wl_keyboard@33.key(59169, 33453468, 42, 1)
[ 134373.291] wl_keyboard@33.modifiers(59170, 1, 0, 0, 0)
[ 134952.033] wl_keyboard@33.key(59171, 33454047, 104, 1)
[input] Key PGUP is bound to:
[input] 1.  'add chapter 1' in <builtin>:1 (default)
```

**Comment by llyyr** [comment]
I can reproduce this issue locally now by configuring my sway input device with

```
    xkb_options "grp:shifts_toggle"
    xkb_layout "us,jp(kana)"
```
mpv receives the modifiers but doesn't handle them properly on Wayland.

> I don’t think the claim in the last comment (“The compositor doesn't give us the modifier press in the logs with that option enabled for whatever reason.”) is accurate?

You're correct.
