### ISSUE TITLE
Crash on opening since using macOS Sonoma; missing libass.9.dylib

### ISSUE THREAD

**Issue by eugeniosz** [mpv-player/mpv#13171]
### Important Information

- mpv 0.37
- macOS 14.2
- downloaded from https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.37.0.tar.gz)

### Reproduction steps

Download the last version (started to crash since 0.32)
### Expected behavior
open as when using macOS Ventura
### Actual behaviour
Crash
### Log file

[MPV libass.9.dylib crash log.txt](https://github.com/mpv-player/mpv/files/13779830/MPV.libass.9.dylib.crash.log.txt)

**Comment by Akemi** [comment]
1. i can't reproduce with that bunde/build
2. the build contains the libass.9.dylib that is supposedly missing, seems like you are not using the right bundle, something is broken on your end
3. this is a problem with that bundle, we don't provide any bundles or build, so this is the wrong place to report issues
