### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by zWhdmB5T** [mpv-player/mpv#13173]
Thank you!

Thank you for your project and software!

Thank you for maintenance in the past and in the future!

Kind regards and season's greetings!

**Comment by po5** [comment]
![image](https://github.com/mpv-player/mpv/assets/42466980/2154a083-b86d-4db8-920f-97a8c2656724)

**Comment by hooke007** [comment]
Unfornately many guy loves and support spam msgs in the issue tracker...

**Comment by kasper93** [comment]
Thank you!
