### ISSUE TITLE
mpv keeps changing gamma values.

### ISSUE THREAD

**Issue by cold-nagai** [mpv-player/mpv#13180]
### Important Information

Provide following Information:
<details><summary>mpv --version</summary>

```
mpv v0.37.0-133-g3bf8564a4f Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Dec 28 2023 23:08:04
libplacebo version: v6.338.0-62-g52314e0e
FFmpeg version: N-113116-gf7f4ff1b86
FFmpeg library versions:
   libavutil       58.36.100
   libavcodec      60.36.100
   libavformat     60.20.100
   libswscale      7.6.100
   libavfilter     9.14.101 (runtime 9.14.102)
   libswresample   4.13.100

```
</details>

- Arch Linux 6.6.8-arch1-1 
- aur/mpv-git

mpv keeps randomly changing gamma values to -3, -5 or -8 when playing some videos. I never changed gamma values, always had watch later reset and went as far as to clean the whole `.local/state/mpv/watch_later/` dir. 
```
reset-on-next-file=profile
save-position-on-quit=yes
watch-later-options=start
```

**Comment by christoph-heinrich** [comment]
`--log-file=IIgnoreIssueTemplates.txt`

**Comment by cold-nagai** [comment]
https://0x0.st/HE1y.log

**Comment by cold-nagai** [comment]
Which mpv options could possibly affect gamma values? The thing is, it even happens with files that don't have a watch_later file because i played them the first time.

**Comment by christoph-heinrich** [comment]
I didn't see gamme being set to -3, -5 or -8 in the log you've posted, but that must be something in your config.
Try creating a new config folder and incrementally add parts of your old config to it until you hit the problem again, that way you can find out what is actually causing the problem.

**Comment by cold-nagai** [comment]
I was switching between mpv-git and 1:0.37.0-3 on Arch and the issue seems to be resolved now. No idea what change caused this behavior in the first place though.
