### ISSUE TITLE
How to get and set the color format of osd_overlay render

### ISSUE THREAD

**Issue by ahaoboy** [mpv-player/mpv#13184]
On my computer, I've set a red background, but the rendering appears blue. Is there an API available to determine which color format is being used, RGB or BGR, and whether it can be set to the desired format?

```js
var ovl = mp.create_osd_overlay()
var bg = "{\\pos(0,0)}{\\p1}{\\c&FF0000&}{\\bord0} m 0 0 l 100 0 l 100 100 l 0 100"
ovl.data = bg
ovl.update()
```

**Comment by guidocella** [comment]
libass uses BGR.
