### ISSUE TITLE
Flatpak MPV override

### ISSUE THREAD

**Issue by lamyergeier** [mpv-player/mpv#13190]
On [mpv  Flathub](https://flathub.org/apps/io.mpv.Mpv) it is mentioned that

> Flatpak: mpv scripts needs write access. Use flatseal app to set home or host write permission

Does this mean

```
			FlatpakId="io.mpv.Mpv"
			flatpak override "${FlatpakId}" --filesystem=host
```

How to use the configuration stored at `~/.config/mpv` with flatpak? What flatpak settings do I need to override?

**Comment by llyyr** [comment]
There is no official mpv flathub, ask here instead https://github.com/flathub/io.mpv.Mpv/issues
