### ISSUE TITLE
ffmpeg with vulkan but no hwdec=vulkan on rpi 4 64 bit

### ISSUE THREAD

**Issue by spookyfirehorse** [mpv-player/mpv#13191]
### Important Information

Provide following Information:
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects

- Platform and Version rpi4
- 
- Source of the mpv binary apt source    debian bookworm 64 bit

- GPU model, driver and version ffmpeg 5.1.4 self compiled apt source ffmpeg sand enabled request enabled 

--prefix=/usr --extra-version=0+rpt1+deb12u1 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --disable-mmal --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sand --enable-sdl2 --disable-sndio --enable-libjxl --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --disable-chromaprint --disable-frei0r --disable-libx264 --enable-libplacebo --enable-vulkan --enable-librav1e --enable-shared --enable-nonfree --enable-libfdk-aac --disable-static --disable-nvdec --disable-nvenc --disable-cuvid --disable-cuda-llvm --disable-cuda-nvcc --disable-ffnvcodec --disable-vdpau --disable-vaapi --cpu=cortex-a72 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libvo_amrwbenc  --enable-libtesseract --enable-version3

mesa and all other default bookworm

working with ffmpeg

    ffmpeg -init_hw_device "vulkan=vk:0" -hwaccel vulkan -hwaccel_output_format vulkan

working with ffmpeg 

    ffmpeg  -hwaccel drm -hwaccel_output_format drm_prime

mpv --hwdec=help

no hwaccel=vulkan

only drm and v4l2m2m

vulkan enabled with this comand

    meson configure build -Dprefix=/usr -Dlibmpv=true -Ddvdnav=enabled -Dsdl2=enabled -Dzimg=enabled -Drpi=disabled -Drpi-mmal=disabled -Degl=enabled -Dwayland=enabled -Degl-wayland=enabled         -Dvaapi=disabled -Dvdpau=disabled -Dvulkan=enabled  -Dcuda-hwaccel=disabled -Dcuda-interop=disabled -Dzlib=enabled 

thanks for all your work

**Comment by CounterPillow** [comment]
Vulkan video requires hardware-specific driver work to enable it, and after a cursory search through mainline mesa I don't see any of that work having been done for RPi's hardware video decoder.

Also, your mpv would be too old to use vulkan hwdec anyway, as at least 0.37 is required for this. ffmpeg 5.1.4 is also too old to contain any vulkan video decode support.

Please see https://github.com/mpv-player/mpv/issues/11739

**Comment by spookyfirehorse** [comment]
i heave running vulkan on my rpi 

also hwaccel vulkan on ffmpeg 5.1.4 

supertuxkart is running on vulkan

supertuxkart --render-driver=vulkan

only install mesa-vulkan driver over apt  and it si running 

i think mesa 20.3  its 2 years ago comes the message from mesa full hwaccel on rpi

greeting from vienna

**Comment by CounterPillow** [comment]
Your ffmpeg fork does not seem to implement vulkan video decoding. It appears to use v4l2-request. Your ability to use Vulkan for 3d graphics rendering has nothing to do with vulkan video decoding.

**Comment by spookyfirehorse** [comment]
i render some vob file with drm hwaccel with ca 100 fps

and with hwaccel 110 fps  thats only i know


ffmpeg   -y  -init_hw_device "vulkan=vk:0" -hwaccel vulkan -hwaccel_output_format vulkan -probesize 400M -analyzeduration 410M  \
    -i example.vob  -ss 00:00:05  \
    -map 0:v   -c:v h264_v4l2m2m  -b:v 3M  -pix_fmt yuv420p -num_capture_buffers 512   -num_output_buffers 64 -bufsize 5M   -maxrate 5M  -aspect 16:9 \
    -c:a libopus     -b:a 128k -map 0:a -af volume=1.5   -movflags +faststart   -f mp4  example.mp4

and no error massage and 110 fps 

ffmpeg   -y  -hwaccel drm -hwaccel_output_format drm_prime -probesize 400M -analyzeduration 410M  \
    -i example.vob  -ss 00:00:05  \
    -map 0:v   -c:v h264_v4l2m2m  -b:v 3M  -pix_fmt yuv420p -num_capture_buffers 512   -num_output_buffers 64 -bufsize 5M   -maxrate 5M  -aspect 16:9 \
    -c:a libopus     -b:a 128k -map 0:a -af volume=1.5   -movflags +faststart   -f mp4  example.mp4

ca 100 fps 

greetings

**Comment by CounterPillow** [comment]
Can you show me the console output of your vulkan hwaccel command?

**Comment by spookyfirehorse** [comment]
ffmpeg  -fflags +genpts  -init_hw_device "vulkan=vk:0" -hwaccel vulkan -hwaccel_output_format vulkan   -i /media/dat/ONLY_LOVERS_LEFT_ALIVE3-1.vob  -c:v h264_v4l2m2m -b:v 2M -num_capture_buffers 512   -num_output_buffers 64 -bufsize 5M    -pix_fmt yuv420p  -af volume=1.5  -c:a libfdk_aac  -movflags +faststart   -b:a 96k -f mp4 test.mp4
ffmpeg version 5.1.4-0+rpt1+deb12u1 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr --extra-version=0+rpt1+deb12u1 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --disable-mmal --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librist --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sand --enable-sdl2 --disable-sndio --enable-libjxl --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --cpu=cortex-a72 --enable-pocketsphinx --enable-librsvg --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --disable-chromaprint --disable-frei0r --disable-libx264 --enable-libplacebo --enable-vulkan --enable-librav1e --enable-shared --enable-nonfree --enable-libfdk-aac --disable-static --disable-nvdec --disable-nvenc --disable-cuvid --disable-cuda-llvm --disable-cuda-nvcc --disable-ffnvcodec --disable-vdpau --disable-vaapi --enable-thumb
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mpeg, from '/media/dat/ONLY_LOVERS_LEFT_ALIVE3-1.vob':
  Duration: 00:25:16.58, start: 0.060000, bitrate: 5287 kb/s
  Stream #0:0[0x1bf]: Data: dvd_nav_packet
  Stream #0:1[0x1e0]: Video: mpeg2video (Main), yuv420p(tv, progressive), 720x576 [SAR 64:45 DAR 16:9], 5000 kb/s, 25 fps, 25 tbr, 90k tbn
    Side data:
      cpb: bitrate max/min/avg: 5000000/0/0 buffer size: 1835008 vbv_delay: N/A
  Stream #0:2[0x80]: Audio: ac3, 48000 Hz, stereo, fltp, 192 kb/s
Stream mapping:
  Stream #0:1 -> #0:0 (mpeg2video (native) -> h264 (h264_v4l2m2m))
  Stream #0:2 -> #0:1 (ac3 (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
[h264_v4l2m2m @ 0x5591b5ea50]  <<< v4l2_encode_init: fmt=0/-1
[h264_v4l2m2m @ 0x5591b5ea50] Using device /dev/video11
[h264_v4l2m2m @ 0x5591b5ea50] driver 'bcm2835-codec' on card 'bcm2835-codec-encode' in mplane mode
[h264_v4l2m2m @ 0x5591b5ea50] requesting formats: output=YU12 capture=H264
Output #0, mp4, to 'test.mp4':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuv420p(tv, progressive), 720x576 [SAR 64:45 DAR 16:9], q=2-31, 2000 kb/s, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc59.37.100 h264_v4l2m2m
  Stream #0:1: Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, s16, 96 kb/s
    Metadata:
      encoder         : Lavc59.37.100 libfdk_aac
frame=    1 fps=0.0 q=0.0 size=       0kB time=00:00:00.02 bitrate=  18.0kbits/s speed=frame=   72 fps=0.0 q=-0.0 size=       0kB time=00:00:02.79 bitrate=   0.1kbits/s speedframe=  156 fps=146 q=-0.0 size=       0kB time=00:00:06.16 bitrate=   0.1kbits/s speed[mpeg @ 0x5591b67b20] New subtitle stream 0:3 at pos:4339726 and DTS:6.64s
[mpeg @ 0x5591b67b20] New subtitle stream 0:4 at pos:4343822 and DTS:6.64s
frame=  229 fps=146 q=-0.0 size=     256kB time=00:00:09.10 bitrate= 230.3kbits/s speedframe=  252 fps=122 q=-0.0 size=     256kB time=00:00:10.00 bitrate= 209.6kbits/s speedframe=  307 fps=119 q=-0.0 size=     256kB time=00:00:12.24 bitrate= 171.3kbits/s speedframe=  376 fps=122 q=-0.0 size=    1024kB time=00:00:14.95 bitrate= 561.0kbits/s speedframe=  443 fps=124 q=-0.0 size=    1792kB time=00:00:17.70 bitrate= 829.1kbits/s speedframe=  515 fps=126 q=-0.0 size=    2560kB time=00:00:20.52 bitrate=1021.9kbits/s speedframe=  584 fps=128 q=-0.0 size=    3328kB time=00:00:23.33 bitrate=1168.2kbits/s speed[mp4 @ 0x5591b443c0] Starting second pass: moving the moov atom to the beginning of the file
frame=  587 fps=127 q=-0.0 Lsize=    3608kB time=00:00:23.48 bitrate=1258.4kbits/s speed=5.08x    
video:3317kB audio:277kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.408125%
Exiting normally, received signal 2.

**Comment by CounterPillow** [comment]
>  Stream #0:1 -> #0:0 (mpeg2video (native) -> h264 (h264_v4l2m2m))

You are using software decoding. Your vulkan arguments have no effect. The reason why it's faster than v4l2-request hwdec is that software decoding on rpi4 is faster than hardware decoding.

In summary:

1. your mpv version (0.35) is too old to use vulkan hwdec
2. your ffmpeg fork (5.1.4) is too old to use vulkan hwdec
3. your mesa is too old to implement vulkan hwdec
4. your hardware has no vulkan hwdec driver anyway

**Comment by spookyfirehorse** [comment]
ok thank you

**Comment by spookyfirehorse** [comment]
good day and hello!


I'm ripping a relatively rare DVD with subtitles into DVDSub format
When I render this film in Debian AMD64 with handbreak, the subtitle is yellowish, so I also rip it with ffmpeg to AMD64 and RPI Aarch64, no matter where the subtitles are white, even if I include the IFO file

Here is my command without video, exact representation, just not yellowish

ffmpeg -probesize 400M -analyzeduration 410M -fflags +genpts+igndts -ifo_palette default.IFO -canvas_size 720x576 -i output.vob -c:a libfdk_aac -b:a 128k -map 0:a:1 -map 0:a:2 -map 0:a:3 -scodec dvdsub -map 0:s:3 -map 0:s:2 -vn -f mp4 test.mp4

Any idea what Handbrake does differently

Greetings from Vienna

**Comment by philipl** [comment]
Sir, this is a Wendy's.

**Comment by spookyfirehorse** [comment]
what does that mean ?


I'm from Vienna

**Comment by CounterPillow** [comment]
It means we are not your personal tech support for completely unrelated things.
