### ISSUE TITLE
mpv shows black & white image instead of original JPEG

### ISSUE THREAD

**Issue by desbma** [mpv-player/mpv#13192]
### Important Information

- mpv version
0.36.0
- Linux Distribution and Version
Arch Linux x86-64 up to date
- Source of the mpv binary
https://archlinux.org/packages/extra/x86_64/mpv/

### Reproduction steps

I am using mpv as an image viewer.
Run `mpv --no-config --image-display-duration=inf --keep-open i.jpg` with the provided file.

### Expected behavior

The original colored image is shown. 

### Actual behavior

A white image is shown, for other images it is a black and white version of the image. It is easily reproducible with images generated by different smartphones.

It seems to be caused by some metadata embedded in the image, because if I run `jpegoptim --strip-all xxx.jpg` on the files, the issue does not happen, same if I extract the image stream and pipe it to mpv with `ffmpeg -i xxx.jpg -map v:1 -c:v copy -f matroska - | mpv -`

### Log file

https://x0.at/mnkH.log

### Sample files

Test image: https://x0.at/1Jrk.jpg

**Comment by guidocella** [comment]
That is a 2-frame video, not an image.

**Comment by desbma** [comment]
> That is a 2-frame video, not an image.

Isn't the black and white frame embedded in some file metadata ? 
`ffprobe` for example only detects a single `mjpeg` stream with a single frame, like all JPEG files.

I forgot to add, all other image viewers I tested display the colored file properly.

**Comment by guidocella** [comment]
It does seem to play as an image even in ffplay. It sounds similar to https://github.com/mpv-player/mpv/issues/9920

**Comment by desbma** [comment]
I'm not sure what you mean by "play as an image", but `ffplay` shows the proper colored image on my system, with a single frame, like it does with any other image file. 

Is there a way to pass a command line argument to make mpv only consider the "main" image ?

**Comment by guidocella** [comment]
I mean that ffplay pauses. You can pass `--pause`.

**Comment by guidocella** [comment]
I found another one of these: https://i.redd.it/2sc79fx2atkc1.jpeg
ffplay pauses on it but mpv plays a dark version as the second frame. Re-encoding it with imagemagick fixes it.

**Comment by guidocella** [comment]
Bisected to 74e62ed2d1

If you remove the jpeg extension from these images, ffplay also plays them incorrectly.

**Comment by kasper93** [comment]
For the record: 

Image formats that encapsulate gain map that can be applied on base image to reconstruct HDR.
https://developer.android.com/media/platform/hdr-image-format
https://helpx.adobe.com/camera-raw/using/gain-map.html

This is basically, what we were seeing. d0aeca59189c44b3999cc7add9d23642a73fe188 make it so we only display base image and ignore any additional information. Actual support for this format may be implemented in the future.
