### ISSUE TITLE
Play online ISO files with mpv using loadfile

### ISSUE THREAD

**Issue by user1121114685** [mpv-player/mpv#13195]
I have compiled libbluray into mpv, but I still cannot play online .iso files. However, the link in the documentation only works for local .iso files. See https://mpv.io/manual/master/#options-dvd-device

eg `mpv loadfile http://127.0.0.1:1234/abc.iso append`

### Log file
`ffmpeg/demuxer, level: error, text: mpegts: max resync size reached, could not find sync byte`

**Comment by po5** [comment]
Use dvd or bd protocol.

**Comment by user1121114685** [comment]
> Use dvd or bd protocol.

bd or dvd does not support online playback of iso files

**Comment by sfan5** [comment]
That is your answer. It is not supported.
