### ISSUE TITLE
MPV 0.37.0 video playback very slow

### ISSUE THREAD

**Issue by shibotto** [mpv-player/mpv#13198]
- mpv 0.37.0
- Artix Linux
- distro package
- Xfce 4.18
- Intel Corporation Atom Processor D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller, i915 (according to lspci)
- Log https://0x0.st/HEn5.txt

Video playback is a (very slow) slideshow since 0.37.0, audio is OK. Please tell me if you need some more information.

MPV 0.37.0

https://github.com/mpv-player/mpv/assets/3816409/0020ca00-c9f1-43d2-8f4a-10a07ce0fa8f

MPV 0.36.0

https://github.com/mpv-player/mpv/assets/3816409/1a5b6038-2d16-4681-a716-7b04d165a5b6

**Comment by guidocella** [comment]
`--profile=fast`

**Comment by shibotto** [comment]
Wow thanks! I knew the fast profile before and I wasn't expecting this at all. What options does it include nowadays? (Or better, where can I watch what options it includes?)

**Comment by guidocella** [comment]
https://github.com/guidocella/mpv/commit/703f158880

**Comment by Hrxn** [comment]
> Wow thanks! I knew the fast profile before and I wasn't expecting this at all. What options does it include nowadays? (Or better, where can I watch what options it includes?)

```
mpv --show-profile=fast
```
