### ISSUE TITLE
Playing some hevc videos on tvOS cause a blue screen

### ISSUE THREAD

**Issue by cxfksword** [mpv-player/mpv#13197]
### Important Information

Provide following Information:
- mpv version
  0.37.0
- Platform and Version
  tvOS 16.6

### Reproduction steps

build a simple tvOS demo and set options to :
```
checkError(mpv_set_option_string(mpv, "hwdec",  "auto-safe"))
checkError(mpv_set_option_string(mpv, "vo", "libmpv"))
```
install demo to AppleTV and play video file:
```
https://github.com/qiudaomao/MPVColorIssue/blob/master/MPVColorIssue/resources/captain.marvel.2019.2160p.uhd.bluray.x265-terminal.sample.mkv?raw=true
```

### Expected behavior

normal hardware decoding  playback

### Actual behavior

<img width="720" alt="SCR-20231231-jhzi" src="https://github.com/mpv-player/mpv/assets/718792/4728e62d-1727-425d-a967-e604aade6a35">

### Log file

[blue_screen.txt](https://github.com/mpv-player/mpv/files/13800023/blue_screen.txt)

### Sample files

https://github.com/qiudaomao/MPVColorIssue/blob/master/MPVColorIssue/resources/captain.marvel.2019.2160p.uhd.bluray.x265-terminal.sample.mkv?raw=true

**Comment by Akemi** [comment]
it works without hwdec?

**Comment by cxfksword** [comment]
my apologies, it's same  as issue #7846
