### ISSUE TITLE
Support for moving through files in the same directory.

### ISSUE THREAD

**Issue by Link0306** [mpv-player/mpv#132]
Hey, I was just wondering if something was possible to do. 

I remember in mplayer2, you could use HOME and END to, as they said, go to the "next/previous playtree entry in the parent list." I admit I do not completely understand what this means exactly, but I was able to use it for moving through files within the same folder. I did like this feature, but unless I'm missing something, there does not seem to be anything with the same functionality in mpv. I do know there are playlists, but that requires you to plan it out before you start anything, and it's even more annoying to make a playlist if you're running mpv via the app bundle.

Now, I did see in the mpv man that is seems the playtree from mplayer2 has been completely removed. So, I understand if this request turns out to be very annoying to implement or just plain impossible, in which case you can just disregard this.

**Comment by wm4** [comment]
This can now be handled with the autoload.lua script: https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua
