### ISSUE TITLE
Hardware full for unknown reasons

### ISSUE THREAD

**Issue by atbsi** [mpv-player/mpv#13200]
mpv ca4192e
win 10 64 22H2  19045.3570
AMD Ryzen 5 5600G with Radeon Graphics

I'm not a programmer and I've been downloading mpv.exe from sourceforge.net.
The last version I used was "mpv-x86_64-v3-20230723-git-ca4192e.7z 	2023-07-23 "
Around October, I downloaded the latest version at sourceforge.net and I realized that mpv playing 4K videos causes the hardware to be full. CPU-40% GPU-95+%
While ca4192e playing 4K basically maintains CPU-10% GPU-15+% (can play two 4K videos at the same time without any stress)
Subsequently, I have been using ca4192e, but almost every month I download the latest version, but without exception, 4K video causes full load.
I can't pinpoint what is causing this, and since I only have this one pc, I don't know if this only occurs on this particular cpu I'm using.

All mpv versions were tested with the default configuration.
The 4K videos used for testing include regular MP4 movies, and youtube 4K VP9 webm videos downloaded locally, like this one:
https://www.youtube.com/watch?v=GQTS5w5IcvM

**Comment by CounterPillow** [comment]
Why didn't you include a log file? Comparing the log file of the working version to the one that doesn't work would probably pinpoint the issue.

**Comment by guidocella** [comment]
`--profile=fast`

**Comment by kasper93** [comment]
> `--profile=fast`

https://github.com/mpv-player/mpv/commit/703f1588803eaa428e09c0e5547b26c0fff476a7

**Comment by atbsi** [comment]
Thank you all for your replies. Playback became normal using the profile parameter. Looks like it was just a configuration issue.
