### ISSUE TITLE
No option for force HW-overlay mode

### ISSUE THREAD

**Issue by chewi** [mpv-player/mpv#13202]
### Important Information

Provide following Information:
- mpv version: v0.37.0-137-g 28b21e4ab7
- Linux Distribution and Version: Gentoo Linux with unreleased ffmpeg package to add jc-kynesim's patches
- Source of the mpv binary: Gentoo Linux "live" package from source
- If known which version of mpv introduced the problem: N/A
- Window Manager and version: None (DRM)
- GPU model, driver and version: Raspberry Pi 4B

### Reproduction steps

```
mpv --no-config --vo=gpu --hwdec=v4l2m2m --drm-draw-plane=overlay --drm-drmprime-video-plane=primary --opengl-es=yes --profile=fast test.mkv
```

### Problem

This isn't an issue, as such, but when testing the new Gentoo Linux ffmpeg package with jc-kynesim's patches, I was initially confused about why the performance was so much better on the Pi 3 than the Pi 4. I eventually found that `--opengl-es=yes` increased the performance a bit and `--profile=fast` (for bilinear filtering) increased it a lot. I realised that this hadn't been necessary on the Pi 3 because its GL/GLES capabilities were insufficient, so it fell back to HW-overlay mode. These lines were present in the log:

```
drmprime hwdec requires at least one dmabuf interop backend.
Using HW-overlay mode. No GL filtering is performed on the video!
```

That all makes sense, but I was surprised by the lack of an option to force HW-overlay mode. Presumably rendering via EGL is more expensive, even with bilinear filtering. HW-overlay mode didn't look noticeably worse to my untrained eye. Kodi does offer this feature with its "PRIME Render Method" option allowing "EGL" or "Direct to Plane".

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/13805030/mpv.log)

**Comment by CounterPillow** [comment]
`--gpu-hwdec-interop=drmprime-overlay` may be what you're looking for.

**Comment by chewi** [comment]
Ah, yes it is. :sweat_smile: Thank you. I had scoured the man page, but it doesn't mention that specific value for that option.
