### ISSUE TITLE
libmpv load/save options/properties

### ISSUE THREAD

**Issue by URUWorks** [mpv-player/mpv#13203]
Hola,
When embedding libmpv in my application, 
is there a way to save the properties/options that are currently being used and then have the command to load them?

Thanks

**Comment by zhongfly** [comment]
you can learn from this script https://github.com/d87/mpv-persist-properties

**Comment by Dudemanguy** [comment]
There's no builtin way or API provided for you. Your application will have to keep track of this itself.
