### ISSUE TITLE
Poor performance in 8K 60fps content

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#13213]
### Important Information

Provide following Information:
- mpv version - v0.37.0-129-g9565675488
- libplacebo version - v6.338.0-62-g52314e0e
- ffmpeg version - N-113113-g56ca0f2918
- Platform and Version - Nobara Linux 38, Linux 6.6.7
- Source of the mpv binary - Manually compiled from source
- GPU model - Intel Iris Xe on i5-11320H
- GPU driver - i915

### Reproduction steps

`mpv "https://www.youtube.com/watch?v=EJr3uAQwGek" --hwdec=auto --no-config --profile=fast`
`mpv "https://www.youtube.com/watch?v=EJr3uAQwGek" --hwdec=no --no-config --profile=fast`

### Expected behavior

No framedrops

### Actual behavior

Heavy framedrops

### Log file

[hwdec.txt](https://github.com/mpv-player/mpv/files/13807712/hwdec.txt)
[no_hwdec.txt](https://github.com/mpv-player/mpv/files/13807711/no_hwdec.txt)

### Additional information

When hwdec is used, CPU as reported by htop is at around 5-10%, GPU render usage as reported by intel_gpu_top is about 1-5%, and GPU Video usage is about 50%.

When hwdec is not used, all CPU cores are pinned at 100%, but GPU render usage stays at 5%, and GPU Video usage is 0, as no hardware decoding is being done.

**Comment by llyyr** [comment]
This is expected without hwdec but it should probably be fine with hwdec I'd imagine. Can you try `--vo=gpu-next --gpu-api=vulkan`? And since you're on Wayland, `vo=dmabuf-wayland` is also worth a shot.

**Comment by llyyr** [comment]
`mpv "https://www.youtube.com/watch?v=EJr3uAQwGek"` by default picks the HDR version of the video, so this makes more sense now. That hardware is too weak to tonemap 8k60, you can instead configure ytdl_hook to request the SDR version of the video instead.

`--ytdl-raw-options=format-sort=[+hdr]`

**Comment by kkanungo17** [comment]
I do keep vulkan enabled in my config, but no, that doesn't really improve much. dmabuf-wayland vo just errors out after a few initial frames with the message `[lavfi] error on filtering (-12)`.

The HDR point is correct, [this link plays fine.](https://www.youtube.com/watch?v=PdzOkN9_F9A) But then I thought tonemapping is done on the GPU? The GPU usage is low according to intel_gpu_top though, unless it's not reporting correctly or I'm misunderstanding it.

**Comment by llyyr** [comment]
> The GPU usage is low according to intel_gpu_top though

FWIW that 8k60 HDR drops frames with hwdec even on my 6600 XT. Works fine without it though. My very uneducated guess would be that this is a memory speed bottleneck rather than a processing one.

**Comment by kkanungo17** [comment]
@llyyr Is tonemapping that memory intensive? Also would be weird that memory doesn't become a bottleneck just because the decoding was done on CPU.

@Andarwinux the first 4 options are already part of `--profile=fast`. The other 2 didn't help much.

**Comment by kkanungo17** [comment]
Hmm... is the HDR metadata also being processed by the hardware decoder? Can you try playing [this link](https://www.youtube.com/watch?v=PdzOkN9_F9A) and see the video decode usage?

**Comment by Jules-A** [comment]
> FWIW that 8k60 HDR drops frames with hwdec even on my 6600 XT. Works fine without it though. My very uneducated guess would be that this is a memory speed bottleneck rather than a processing one.

Huh? I don't even get offered 8k60 on that video (I have HDR disabled), do you mean another video?

**Comment by kkanungo17** [comment]
@Jules-A That video in 8k is only in HDR on youtube, the one without HDR maxes out at 4k.

@Andarwinux Huh, didn't know that. That seems like the most likely answer, especially given the video decode use.

**Comment by kkanungo17** [comment]
Given Steam Deck also apparently has issues with hardware decoding on Moonlight, it may not just be a Windows problem.

**Comment by FreeTheTech101** [comment]
> I dunno, I can't really software decode them (5800X) either even though it seems like @llyyr can play the HDR Redwood video back with software decoding. It might just be a combination of issues.

I gave things a shot with a 3900X since I don't have AV1 hardware decoding, and can confirm it drops frames rapidly despite not taxing the processor. For systems that do have AV1 decoding, I wonder if `hwdec=d3d12va` makes a difference.

**Comment by llyyr** [comment]
> it seems like @llyyr can play the HDR Redwood video back with software decoding

It's with a 13600k though, so your mileage may vary

**Comment by kkanungo17** [comment]
Dunno if it has any bearing on anything, but running `hwdec-extra-frames=64` along with `vd-queue-enable=yes` makes the video run smooth for a second at the beginning. But after that it drops frames as usual.

**Comment by zsh** [comment]
I observed the exact same serious lagging on 8k60p HEVC video in mpv (macOS M2), while quicktime has no issue at playing it, very smooth.

One thing to point out is that mpv has no issue at playing 6k60p HEVC.

**Comment by llyyr** [comment]
> I observed the exact same serious lagging on 8k60p HEVC video in mpv (macOS M2), while quicktime has no issue at playing it, very smooth.

If it's SDR then `--profile=fast`.

**Comment by kkanungo17** [comment]
In conclusion, this seems to be an issue on the hardware side of things, so I'm closing this issue.
