### ISSUE TITLE
Support loading C plugin using relative `config-dir` path

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#13212]
### Important Information

Provide following Information:
- mpv version: maybe week old
- Windows Version: recent Win 11
- Source of the mpv binary: zhongfly

### Reproduction steps

1. Use relative path for `config-dir` on the command line: `--config-dir=.`

Error output:

```
[menu] C plugin error: 'The specified module could not be found.
[menu] '
[menu] Could not load cplugin script ./scripts/menu.dll
```

Using `--config-dir=.` normally works fine, I tried it for instance with uosc.

The reason why I'm doing this is, when I want to test a user script or plugin, I create a new dedicated conf dir, so I don't need to change my main conf dir, keep it clean. I save and keep my test conf dirs, so I can come back later for test 2, test 3 etc.

As a workaround, using the full path works fine (`--config-dir="%~dp0\"` using .bat since this starts 20 times quicker than PowerShell).

More background info can be found here:

https://github.com/mpvnet-player/mpv.net/wiki/The-best-way-to-test-mpv-user-scripts

**Comment by Dudemanguy** [comment]
Are you saying that a relative path to `--config-dir` doesn't work? Isn't this just a shell issue?

**Comment by stax76** [comment]
I don't see the shell involved, the shell isn't supposed to create a full path here. 

> Could not load cplugin script ./scripts/menu.dll

I believe LoadLibrary does not work with the relative path or the forward slashes or both. It can be fixed by calling GetFullPathName before passing it to LoadLibrary.

> If lpFileName specifies a relative path, the entire relative path is appended to every token in the DLL search path. To load a module from a relative path without searching any other path, use [GetFullPathName](https://learn.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-getfullpathnamea) to get a nonrelative path and call LoadLibraryEx with the nonrelative path. If the module is being loaded as a datafile and the relative path starts with "." or "..", the relative path is treated as an absolute path.

https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw

**Comment by Dudemanguy** [comment]
Oh so you're saying it's specific to cplugins on windows then. That would make more sense then. cc @kasper93

**Comment by kasper93** [comment]
This works for you?

``` diff
diff --git a/osdep/io.c b/osdep/io.c
index 13fd0b34f5..617764c16a 100644
--- a/osdep/io.c
+++ b/osdep/io.c
@@ -738,9 +738,23 @@ static void mp_dl_init(void)
 
 void *mp_dlopen(const char *filename, int flag)
 {
-    wchar_t *wfilename = mp_from_utf8(NULL, filename);
-    HMODULE lib = LoadLibraryW(wfilename);
-    talloc_free(wfilename);
+    HMODULE lib = NULL;
+    void *ta_ctx = talloc_new(NULL);
+    wchar_t *wfilename = mp_from_utf8(ta_ctx, filename);
+
+    DWORD len = GetFullPathNameW(wfilename, 0, NULL, NULL);
+    if (!len)
+        goto err;
+
+    wchar_t *path = talloc_array(ta_ctx, wchar_t, len);
+    len = GetFullPathNameW(wfilename, len, path, NULL);
+    if (!len)
+        goto err;
+
+    lib = LoadLibraryW(path);
+
+err:
+    talloc_free(ta_ctx);
     mp_dl_result.errcode = GetLastError();
     return (void *)lib;
 }
```

**Comment by stax76** [comment]
I confirm it works.
