### ISSUE TITLE
no dithering on 30 fps video with display-resample and gpu-next

### ISSUE THREAD

**Issue by tw8sqf3s** [mpv-player/mpv#13229]
### Important Information

Provide following Information:
- mpv version: `0.37.0` / `1c9c2f5` 
- Windows Version: `Windows 10` / `10.0.19045 build 19045` 
- Source of the mpv binary: `chocolatey mpvio` / `rossy | shinchiro`?
- If known which version of mpv introduced the problem: idk, i noticed it in 0.37
- GPU model, driver and version: `Intel® HD Graphics for 4th Generation Intel® Processors`
- Possible screenshot or video of visual glitches: [60fps](https://0x0.st/H63S.jpg), [30fps](https://0x0.st/H63u.jpg)

### Reproduction steps
run mpv with `--no-config --vo=gpu-next --video-sync=display-resample`
for my tests i have used 30fps_normal and 60fps_normal from https://download.blender.org/demo/movies/BBB/

### Expected behavior
there being `dithering (10bit)` in the render pipeline

### Actual behavior
no `dithering (10bit)` in the render pipeline

### Log file
[60fps.log](https://github.com/mpv-player/mpv/files/13843176/60fps.log)
[30fps.log](https://github.com/mpv-player/mpv/files/13843178/30fps.log)

**Comment by haasn** [comment]
It's still there, it's just part of the frame mixing step now, not the rendering step.
