### ISSUE TITLE
LibMPV DLL with LGPL license

### ISSUE THREAD

**Issue by Dingo64** [mpv-player/mpv#13221]
So I read you spent a lot of time and effort re-licensing LibMPV code to LGPL so it can be used in non-GPL programs but I cannot find anywhere a DLL for Windows compiled with -Dgpl=false.
I am not a C/C++ programmer so I cannot build it myself. The whole point of a DLL is that it could be used with any programming language so it would be really nice if you made such an LPGL DLL available for download.

**Comment by zhongfly** [comment]
https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md

Or try this repo https://github.com/shinchiro/mpv-winbuild-cmake , modify these lines https://github.com/shinchiro/mpv-winbuild-cmake/blob/96eec0c273d865c03092a00439c522c2816b1392/packages/mpv.cmake#L35-L55
