### ISSUE TITLE
video playback tearing with -vo=gpu-next --gpu-hwdec-interop=drmprime on RK3288 (Mali T760)

### ISSUE THREAD

**Issue by zhangn1985** [mpv-player/mpv#13220]
### Important Information

Provide following Information:
- mpv version: **0.37**
- Linux Distribution and Version: **Gentoo latest**
- Source of the mpv binary: **0.37**
- If known which version of mpv introduced the problem

- Window Manager and version: **No WM**
- GPU model, driver and version: **mali T760 (RK3288), kernel 6.6.8**
- Possible screenshot or video of visual glitches 

https://github.com/mpv-player/mpv/assets/832666/c3b0ddf4-d407-41eb-bfe5-967729e0180c

https://github.com/mpv-player/mpv/assets/832666/206bac2b-0cfa-4898-9197-5ec43986d76b

**Comment by zhangn1985** [comment]
```bash
VIDEO_CARDS="lima fbdev"
INPUT_DEVICES="libinput evdev"
COMPRESS="bzip2 zstd lz4 lzo lzma"
#AUDIO="flac faad opus ogg vorbis wavpack"
USE="-lcms -glslang -vulkan -man -fortran  -llvm -smartcard -iptables -X -cpudetection -xv -lmdb libsamplerate alsa icu dbus ssl jpeg png gmp ${COMPRESS} ${AUDIO}"
CPU_FLAGS_ARM="edsp neon thumb vfp vfpv3 vfpv4 vfp-d32 v4 v5 v6 v7 thumb2"
ACCEPT_KEYWORDS="~arm"
```
these are my make.conf for H3, 
I enable `lcms glslang vulkan` for RK3288.

**Comment by zhangn1985** [comment]
```
mpv --gpu-hwdec-interop=help
Available hwdecs:
    vaapi
    cuda
    drmprime
    drmprime-overlay
    vulkan
    auto (behavior depends on context)
    all (load all hwdecs)
    no (do not load any and block loading on demand)
```
is this option?

**Comment by zhangn1985** [comment]
after bisect on RK3288, Mali-T760 (build without Vulkan), found:
```diff
diff --git a/filters/f_hwtransfer.c b/filters/f_hwtransfer.c
index 26b1daae..2266e497 100644
--- a/filters/f_hwtransfer.c
+++ b/filters/f_hwtransfer.c
@@ -348,7 +348,8 @@ static bool probe_formats(struct mp_filter *f, int hw_imgfmt, bool use_conversio
         if (!cstr) {
             MP_VERBOSE(f, "hwdec '%s' does not report hwframe constraints. "
                           "Using static metadata.\n", cur->driver_name);
-            cstr = build_static_constraints(cur);
+            //cstr = build_static_constraints(cur);
+               continue;
         }
         bool found = false;
         for (int i = 0; cstr->valid_hw_formats &&
```
this change helps fix `mpv -vo=gpu-next --gpu-hwdec-interop=drmprime`

what this means? is it a bug of  `build_static_constraints`, or GPU lack of some extensions?

**Comment by zhangn1985** [comment]
hi  @philipl , 

you are the author of `build_static_constraints` would you help to check this issue?

when I use `mpv -vo=gpu-next --gpu-hwdec-interop=drmprime xxx.mp4`, on RK3288 (Mali T760) I find tearing video.
(mpv build with `-Dvulkan=disabled`)

after bisect, I find: https://github.com/mpv-player/mpv/commit/71cf360e33e8347d38079c99c90827d95c8d9cda is the commit lead to this issue.

and use above [workaround](https://github.com/mpv-player/mpv/issues/13220#issuecomment-1884631678), mpv can work normally.

I don't understand the detail of `build_static_constraints`, thus not able to do next step.

thank you for your time.

**Comment by philipl** [comment]
Without the logs (which we ask for in the template), it is impossible to know what is really going on. My experience with these rockchip Socs and Lima is that they will sometimes not sync properly and if you try and play the file a few times, it will work eventually. The revert you did should result in the zero-copy interop failing to work, which would avoid the tearing but also significantly reduce performance. The logs would make it clear whether this is happening.

**Comment by zhangn1985** [comment]
@philipl 

I start capture log this morning, and find the issue is gone. after check it related to thermal. thus it's not mpv issue.

**Comment by zhangn1985** [comment]
I will use `mpv -vo=gpu --gpu-hwdec-interop=drmprime-overlay` to play

but `mpv -vo=gpu-next --gpu-hwdec-interop=drmprime-overlay` always segment fault.
