### ISSUE TITLE
Terminal flooded with ffmpeg warnings

### ISSUE THREAD

**Issue by tsjnachos117** [mpv-player/mpv#13234]
### Important Information

Provide following Information:
- mpv version
git-2024-01-04-8b76bae
- Linux Distribution and Version
Mint 21 and Arch (I'll bet other distros, as well as non-GNU/Linux platforms, are affected, too.)
- Source of the mpv binary
Custom build from git master
- If known which version of mpv introduced the problem
Unknown, but it probably happened sometime in December 2023
- Window Manager and version
Cinnamon 6.0.2.
- GPU model, driver and version
Multiple GPUs, likely not a graphics bug.
- Possible screenshot or video of visual glitches
Music/videos play fine, but terminal is flooded with messages.

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Play literally any video using certain video filters. IDK if this problem applies to all filters, or if only certain ones work, but `eq` and `hqdn3d` are known culprits.

### Expected behavior
To not have the terminal flooded with the same message over and over.

### Actual behavior
I get the following warning: `[ffmpeg] mpv_src_in0: Changing video frame properties on the fly is not supported by all filters.` This warning is printed many time per second, drowning out any other terminal output. Removing all filters fixes this issue.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/13846411/log.txt)

PS: I've added an extra line in `~/.mpv/config` as a workaround:

        --msg-level=ffmpeg=error

**Comment by sfan5** [comment]
Can't reproduce.
Zero warnings with `./build/mpv --no-config -vf 'lavfi=[hqdn3d,pp,scale,bwdif,eq]' video.mp4`
or `./build/mpv --no-config -vf hqdn3d,pp,scale,bwdif,eq video.mp4`
ffmpeg 6.1.1, mpv 485221ba22

**Comment by Sneakpeakcss** [comment]
Same thing happens on windows with any filter added, constant flood of ffmpeg warnings (thousands per minute).

Last build that didn't have this issue: [abc2a74](https://github.com/zhongfly/mpv-winbuild/releases/tag/2023-12-31-abc2a74)
[ffmpegflood-abc2a74.txt](https://github.com/mpv-player/mpv/files/13887905/ffmpegflood-abc2a74.txt)
```
[   0.006][v][cplayer] mpv v0.37.0-135-gabc2a748 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[   0.006][v][cplayer]  built on Dec 30 2023 12:08:05
[   0.006][v][cplayer] libplacebo version: v6.338.0-62-g52314e0-dirty
[   0.006][v][cplayer] FFmpeg version: N-113150-ge063c1d07
[   0.006][v][cplayer] FFmpeg library versions:
[   0.006][v][cplayer]    libavutil       58.36.100
[   0.006][v][cplayer]    libavcodec      60.36.100
[   0.006][v][cplayer]    libavformat     60.20.100
[   0.006][v][cplayer]    libswscale      7.6.100
[   0.006][v][cplayer]    libavfilter     9.14.102
[   0.006][v][cplayer]    libswresample   4.13.100
```

And the flooding starts with this one: [28b21e4](https://github.com/zhongfly/mpv-winbuild/releases/tag/2024-01-01-28b21e4)
[ffmpegflood-28b21e4.txt](https://github.com/mpv-player/mpv/files/13887906/ffmpegflood-28b21e4.txt)

```
[   0.004][v][cplayer] mpv v0.37.0-137-g28b21e4a Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[   0.004][v][cplayer]  built on Jan  1 2024 14:04:25
[   0.004][v][cplayer] libplacebo version: v6.338.0-62-g52314e0-dirty
[   0.004][v][cplayer] FFmpeg version: N-113171-g85b8d59ec
[   0.004][v][cplayer] FFmpeg library versions:
[   0.004][v][cplayer]    libavutil       58.36.100
[   0.004][v][cplayer]    libavcodec      60.36.100
[   0.005][v][cplayer]    libavformat     60.20.100
[   0.005][v][cplayer]    libswscale      7.6.100
[   0.005][v][cplayer]    libavfilter     9.16.100
[   0.005][v][cplayer]    libswresample   4.13.100
```
However, in case of [shinchiro builds](https://github.com/shinchiro/mpv-winbuild-cmake) even the mentioned working [abc2a74](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240101) also spams ffmpeg warnings:
[ffmpegflood-shinchiro-20240101-abc2a74.txt](https://github.com/mpv-player/mpv/files/13888237/ffmpegflood-shinchiro-20240101-abc2a74.txt)

```
[   0.004][v][cplayer] mpv v0.37.0-135-gabc2a748 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[   0.004][v][cplayer]  built on Dec 30 2023 00:56:22
[   0.004][v][cplayer] libplacebo version: v6.338.0-62-g52314e0-dirty
[   0.004][v][cplayer] FFmpeg version: N-113168-gb95ee2ec5
[   0.004][v][cplayer] FFmpeg library versions:
[   0.004][v][cplayer]    libavutil       58.36.100
[   0.004][v][cplayer]    libavcodec      60.36.100
[   0.004][v][cplayer]    libavformat     60.20.100
[   0.004][v][cplayer]    libswscale      7.6.100
[   0.004][v][cplayer]    libavfilter     9.16.100
```

But then the same one from day earlier (20231231) [abc2a74](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20231231) works fine again:
[ffmpegflood-shinchiro-20231231-28b21e4.txt](https://github.com/mpv-player/mpv/files/13888295/ffmpegflood-shinchiro-20231231-28b21e4.txt)

```
[   0.004][v][cplayer] mpv v0.37.0-135-gabc2a748 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
[   0.004][v][cplayer]  built on Dec 30 2023 00:56:22
[   0.004][v][cplayer] libplacebo version: v6.338.0-62-g52314e0-dirty
[   0.004][v][cplayer] FFmpeg version: N-113150-ge063c1d07
[   0.004][v][cplayer] FFmpeg library versions:
[   0.004][v][cplayer]    libavutil       58.36.100
[   0.004][v][cplayer]    libavcodec      60.36.100
[   0.004][v][cplayer]    libavformat     60.20.100
[   0.004][v][cplayer]    libswscale      7.6.100
[   0.004][v][cplayer]    libavfilter     9.14.102
[   0.004][v][cplayer]    libswresample   4.13.100
```
Both working builds have the same `N-113150-ge063c1d07` ffmpeg version.

**Comment by llyyr** [comment]
Caused by https://github.com/FFmpeg/FFmpeg/commit/2d555dc82d4ccd3c54c76e2fb3c861a8652de1c6

**Comment by haasn** [comment]
Can you test this diff?

```diff
diff --git a/filters/f_lavfi.c b/filters/f_lavfi.c
index fe7d3e4527..3fa7714be3 100644
--- a/filters/f_lavfi.c
+++ b/filters/f_lavfi.c
@@ -486,6 +486,10 @@ static bool init_pads(struct lavfi *c)
         } else if (pad->type == MP_FRAME_VIDEO) {
             struct mp_image *fmt = pad->in_fmt.data;
             params->format = imgfmt2pixfmt(fmt->imgfmt);
+#if LIBAVFILTER_VERSION_MICRO >= AV_VERSION_INT(58, 16, 100)
+            params->color_space = mp_csp_to_avcol_spc(fmt->params.color.space);
+            params->color_range = mp_csp_levels_to_avcol_range(fmt->params.color.levels);
+#endif
             params->width = fmt->w;
             params->height = fmt->h;
             params->sample_aspect_ratio.num = fmt->params.p_w;
```

**Comment by llyyr** [comment]
Yeah I already worked it out, that diff doesn't work though since the version check isn't right
