### ISSUE TITLE
Playing SDR video without inverse tone mapping in Plasma HDR mode.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#13235]
Question:
1. If I don't apply `--inverse-tone-mapping`, but apply `--target-trc=pq`, `--target-prim=bt.2020`, `--target-peak=366` and `--target-colorspace-hint`, does it only increase the brightness of SDR video?

2. Does it also expand the color space of SDR content to BT.2020 when I apply `--target-colorspace-hint`? Or it is limited in Rec.709?

3. Is the `--inverse-tone-mapping` only an experimental feature?
The image looks so weird to me if I apply `--inverse-tone-mapping`, the white area becomes too bright, the color of skin is weird too. It seems to look better when I play SDR videos in HDR mode without `--inverse-tone-mapping`.

**Comment by Ptilopsis01** [comment]
1. Maybe you need a profile to trigger these options only when the video is HDR
2. I'm not sure, perhaps it depends on your monitor?
3. `--inverse-tone-mapping` expands SDR to HDR, so it's actually different from the original SDR movie, and of course looks strange

**Comment by Ptilopsis01** [comment]
> > 1. Maybe you need a profile to trigger these options only when the video is HDR
> 
> Would you kindly insight me on the syntax for such a profile, @Ptilopsis01?

```
[HDR_video]
profile-desc=HDR_video
profile-cond=(p["video-params/gamma"] == "pq")
...
```
