### ISSUE TITLE
What is the best/official way to extract information about a video to another program?

### ISSUE THREAD

**Issue by randomcoder67** [mpv-player/mpv#13244]
I'm writing a program that plays YouTube videos, and part of this is reading and writing the video times to your YouTube account history via API calls, to keep everything synced between my program and browser/mobile YouTube. 

Setting the start time is easy, but I can't figure out the best way to get the video time on exit?

I noticed the current video time is output to `stderr`, so right now I'm just grabbing that, and then looking for the last "AV:" and reading the value. This is a bit scuffed though, it sometimes doesn't work if the video exits with an error, and it just feel like a hack. 

Is there a more supported/official way to do this?  
I could probably use the `--save-position-on-quit` and `--write-filename-in-watch-later-config` options, however that would require digging through the files to find the correct video. 

It would be good if there was an option that would print the time on exit, then I could use that combined with `--really-quiet`, but I can't find an option like that.

**Comment by guidocella** [comment]
It's available in the `on_unload` hook.

**Comment by randomcoder67** [comment]
> It's available in the `on_unload` hook.

Is it possible to use that in an external script? i.e. could I have a lua script that can be ran from the terminal, which opens mpv, or does it have to be in the scripts directory? 

I tried making a lua script with `local mp = require "mp"` but it didn't work.

**Comment by guidocella** [comment]
`mpv --script=<filename>`
