### ISSUE TITLE
mpv breaks with latest vmaf 3.0 installed

### ISSUE THREAD

**Issue by RAIACAD0564** [mpv-player/mpv#13246]
### Important Information

Provide following Information:
- mpv version 
mpv 1:0.37.0-1
- Linux Distribution and Version 
Arch Linux
Kernel: 6.6.10-arch1-1
- Source of the mpv binary
Arch Linux "Extra" repo
- If known which version of mpv introduced the problem
Experienced in both 0.36.0 and 0.37.0
- Window Manager and version
KDE Plasma 5.27
- GPU model, driver and version
Nvidia GeForce RTX 3070
nvidia-dkms-tkg 535.129.03
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

Simply try to start mpv in any way, either directly or by attempting to play a file. You must have vmaf 3.0.0 or greater installed on your system for this to happen.

### Expected behavior

Opening and/or playing

### Actual behavior

Will fail to launch with the error: mpv: error while loading shared libraries: libvmaf.so.1: cannot open shared object file: No such file or directory
It seems this is caused by "libvmaf.so.1" being renamed to "libvmaf.so.3" in the latest version.

### Log file

Make a log file made with -v -v or --log-file=output.txt, attach it to
the issue, and replace this text with a link to it.

Without the log file, this issue will be closed for ignoring the issue template.

In the case of a crash, please provide a backtrace.

[gdb backtrace.txt](https://github.com/mpv-player/mpv/files/13855869/gdb.backtrace.txt)
[Journalctl attemtping to start through KDE dolphin.txt](https://github.com/mpv-player/mpv/files/13855867/Journalctl.attemtping.to.start.through.KDE.dolphin.txt)

### Sample files

Sample files needed to reproduce this issue can be attached to the issue
(preferred), or be uploaded to https://0x0.st/ or similar sites.
(Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by llyyr** [comment]
You need to update your ffmpeg https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/commit/d543b8a1d6346a3ae11d7d2bc4051ae53ff83044

**Comment by RAIACAD0564** [comment]
Okay, I may take this over to ffmpeg in that case. I am in the latest version off ffmpeg and I'm still experiencing the issue. https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/commit/56d4a18f153aa1b10c46c149299cb7345de68060

**Comment by RAIACAD0564** [comment]
I apologize. I found the issue, I forgot I had the aom-psy-git package installed instead of the regular aom package. Thank you for your help.
