### ISSUE TITLE
`--af=surround` results in audio delay

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#13241]
### Important Information

Provide following Information:
- mpv version:
```
mpv v0.37.0-144-gd8c2e33a Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Jan  5 2024 12:12:13
libplacebo version: v6.338.0-62-g52314e0-dirty
FFmpeg version: N-113224-gde9bc4f20
FFmpeg library versions:
   libavutil       58.36.101
   libavcodec      60.37.100
   libavformat     60.20.100
   libswscale      7.6.100
   libavfilter     9.17.100
   libswresample   4.13.100
```
- Windows Version:
```
Edition	Windows 10 IoT Enterprise LTSC
Version	21H2
Installed on	‎21/‎10/‎2023
OS build	19044.3803
Experience	Windows Feature Experience Pack 1000.19053.1000.0
```
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild/releases ( mpv-x86_64-v3-20240106-git-d8c2e33.7z )
- If known which version of mpv introduced the problem: No
- GPU model, driver and version: NVIDIA GeForce GTX 1650 - Studio Driver Version 546.33
- Possible screenshot or video of visual glitches: No
- Notes: See here https://trac.ffmpeg.org/ticket/10729 and https://github.com/mpv-player/mpv/issues/13030#issuecomment-1842729151 and possible solution here https://github.com/librempeg/librempeg/commit/5d2a66861ef6c736545b80ca05732dcb72e84925

### Reproduction steps
```
mpv --no-config --af=surround:chl_out=5.1(side):focus=1:overlap=1:win_size=65536:win_func=hann sync.mp4 --log-file="~~/af-surround-delay.txt"
```

### Expected behavior
Using `surround` filter with demanding values will NOT result in audio delay.

### Actual behavior
Using `surround` filter with demanding values results in audio delay.

### Log file
[af-surround-delay.txt](https://github.com/mpv-player/mpv/files/13851632/af-surround-delay.txt)

### Sample files
Any video, as an example: https://www.youtube.com/watch?v=TjAa0wOe5k4&pp

**Comment by sfan5** [comment]
No.
