### ISSUE TITLE
(10.14) Mpv fails to build / Snappy (homebrew)

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#13248]
### Important Information

Provide following Information:
mpv via homebrew
(brewi install mpv)
Mac OS 10.14.6

### Reproduction steps

==> Installing dependencies for mpv: snappy, speex, srt, svt-av1, leptonica, libb2, libarchive, pango, tesseract, theora, x264, x265, xvid, asciidoctor, gnu-getopt, xmlto, zeromq, zimg, ffmpeg, shaderc, vulkan-headers, vulkan-loader, libplacebo, luajit, mujs, uchardet, cython, vapoursynth, python-brotli, python-mutagen and yt-dlp
==> Installing mpv dependency: snappy
==> Patching
==> cmake . -DSNAPPY_BUILD_TESTS=OFF -DSNAPPY_BUILD_BENCHMARKS=OFF
==> make install
==> make clean
==> cmake . -DBUILD_SHARED_LIBS=ON -DSNAPPY_BUILD_TESTS=OFF -DSNAPPY_BUILD_BENCHMARKS=OFF
==> make install
Last 15 lines from /Users/rich/Library/Logs/Homebrew/snappy/05.make:
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/llvm_clang++ -DHAVE_CONFIG_H -Dsnappy_EXPORTS -I/tmp/snappy-20240108-39161-fmxapq/snappy-1.1.10 -Wall -Wextra -Werror -fno-exceptions -O3 -DNDEBUG -std=c++11 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIC -MD -MT CMakeFiles/snappy.dir/snappy-stubs-internal.cc.o -MF CMakeFiles/snappy.dir/snappy-stubs-internal.cc.o.d -o CMakeFiles/snappy.dir/snappy-stubs-internal.cc.o -c /tmp/snappy-20240108-39161-fmxapq/snappy-1.1.10/snappy-stubs-internal.cc
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/llvm_clang++ -DHAVE_CONFIG_H -Dsnappy_EXPORTS -I/tmp/snappy-20240108-39161-fmxapq/snappy-1.1.10 -Wall -Wextra -Werror -fno-exceptions -O3 -DNDEBUG -std=c++11 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIC -MD -MT CMakeFiles/snappy.dir/snappy-sinksource.cc.o -MF CMakeFiles/snappy.dir/snappy-sinksource.cc.o.d -o CMakeFiles/snappy.dir/snappy-sinksource.cc.o -c /tmp/snappy-20240108-39161-fmxapq/snappy-1.1.10/snappy-sinksource.cc
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/llvm_clang++ -DHAVE_CONFIG_H -Dsnappy_EXPORTS -I/tmp/snappy-20240108-39161-fmxapq/snappy-1.1.10 -Wall -Wextra -Werror -fno-exceptions -O3 -DNDEBUG -std=c++11 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIC -MD -MT CMakeFiles/snappy.dir/snappy-c.cc.o -MF CMakeFiles/snappy.dir/snappy-c.cc.o.d -o CMakeFiles/snappy.dir/snappy-c.cc.o -c /tmp/snappy-20240108-39161-fmxapq/snappy-1.1.10/snappy-c.cc
[100%] Linking CXX shared library libsnappy.dylib
/usr/local/Cellar/cmake/3.28.1/bin/cmake -E cmake_link_script CMakeFiles/snappy.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/llvm_clang++  -Wall -Wextra -Werror -fno-exceptions -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 1.0.0 -current_version 1.1.10 -o libsnappy.1.1.10.dylib -install_name @rpath/libsnappy.1.dylib "CMakeFiles/snappy.dir/snappy-c.cc.o" "CMakeFiles/snappy.dir/snappy-sinksource.cc.o" "CMakeFiles/snappy.dir/snappy-stubs-internal.cc.o" CMakeFiles/snappy.dir/snappy.cc.o 
Undefined symbols for architecture x86_64:
  "std::__1::__libcpp_verbose_abort(char const*, ...)", referenced from:
      std::__throw_bad_array_new_length[abi:un170006]() in snappy.cc.o
      std::__1::__throw_length_error[abi:un170006](char const*) in snappy.cc.o
ld: symbol(s) not found for architecture x86_64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libsnappy.1.1.10.dylib] Error 1
make[1]: *** [CMakeFiles/snappy.dir/all] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!

**Comment by llyyr** [comment]
> A not too ancient Linux (usually, only the latest releases of distributions are actively supported), Windows 10 or later, or **macOS 10.15 or later**.
