### ISSUE TITLE
libmpv  - different behavior on desktop and mobile platforms

### ISSUE THREAD

**Issue by homov** [mpv-player/mpv#13259]
Different behavior on desktop and mobile (Android) platforms.

libmpv 0.37 (Windows, Linux, Android)

When an error occurs (for example, reading from a source - http error):

- on mobile platforms reports errors and interrupts its work (shutdown event raised)
To continue working, you need to create a new context and initialize it.

- on desktop platforms it does not interrupt work, it simply reports an error. The contexts can be used further.

Using the option _keep-open=yes_ otr _keep-open=always_ do not change behavior on the mobile platform.

Is this a bug or is it by design?

**Comment by Dudemanguy** [comment]
I am not familiar with android, but the desktop behavior is what I would expect. I'm not sure if there is perhaps some limitation with the platform itself that causes this?

**Comment by sfan5** [comment]
You probably want `idle=yes`. But this is just a guess because you ignored the issue template and did not provide all necessary information.
