### ISSUE TITLE
OpenGL mode output doesn't work with smplayer in windows XP

### ISSUE THREAD

**Issue by c384mb** [mpv-player/mpv#1325]
http://sourceforge.net/p/smplayer/bugs/658/

**Comment by c384mb** [comment]
https://sourceforge.net/p/smplayer/bugs/658/#047a

**Comment by wm4** [comment]
>https://sourceforge.net/p/smplayer/bugs/658/#047a

I don't know what that means, and I can't read russian either.

**Comment by c384mb** [comment]
I don't know English lang, I know the English language very few words. And the software translates poorly, but it is necessary to use software translation. To understand what is written on the picture of the Russian language not need to know. If you are using Windows XP and you have the latest version of catalyst you will understand what settings in catalyst resulting in no image when playing through gl. 

Настройки 3D ->Все настройки -> Фильтр -> Стандартное, Edge-detect
Settings 3D -> All Settings -> Filter -> Standard or Edge-detect
