### ISSUE TITLE
Crash on Sway master and hardware acceleration

### ISSUE THREAD

**Issue by stacyharper** [mpv-player/mpv#13255]
### Important Information

- mpv version 

```
mpv 0.37.0-818ce7c51a6b9179307950e919983e0909942098 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.1
FFmpeg version: 6.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

-- sway version

```
sway version 1.9-dev-c5fd8c05 (Jan  9 2024, branch 'master')
```

### Reproduction steps

Build and install Sway master, play a video with hardware acceleration.

Probably related to https://github.com/swaywm/sway/issues/7897, and the drop of wl_drm?

Here my full command is `mpv -v  --no-config --hwdec=auto-safe seedbox/animes/One\ Piece\ KAI\ Saga\ 02\ Baroque\ Works\ VOSTFR\ DVDrip\ FanKai-Knuckalex/One\ Piece\ Kai\ 10\ -\ Arc\ Royaume\ de\ Drum\ -\ part\ 2.mp4  > out.log 2>&1`

### Expected behavior

It works

### Actual behavior

Segmentation fault

### Log file

[out.log](https://github.com/mpv-player/mpv/files/13874470/out.log)

**Comment by llyyr** [comment]
Not our bug, as seen from the sway issue. Should be fixed by https://github.com/intel/libva/pull/790

You can also just revert https://github.com/swaywm/sway/commit/7e69a7076fc8a4eb788e0229b1c99dd0b7b04bb7 temporarily

**Comment by sfan5** [comment]
It still should not be segfaulting however (unless that's literally libva doing it).
Do you have a backtrace?

**Comment by llyyr** [comment]
Yes, it is libva doing it https://github.com/intel/libva/pull/788
