### ISSUE TITLE
--video-sync=display-resample --interpolation freezes video for certain files under certain conditions

### ISSUE THREAD

**Issue by bergfried** [mpv-player/mpv#13256]
### Important Information

Using `mpv 1:0.37.0-1` as currently provided for Arch Linux with `fluxbox 1.3.7+211+g9d8202f3-1` and using `xf86-video-amdgpu 23.0.0-1` for an AMD Radeon RX 550.

This issue seems to be new to mpv 0.37 because

```
pacman -U \
    ffmpeg-2:6.1-3-x86_64.pkg.tar.zst \
    libplacebo-5.264.1-4-x86_64.pkg.tar.zst \
    mpv-1:0.36.0-1-x86_64.pkg.tar.zst \
;
```

works just fine but

```
pacman -U \
    ffmpeg-2:6.1.1-1-x86_64.pkg.tar.zst \
    libplacebo-6.338.1-1-x86_64.pkg.tar.zst \
    mpv-1:0.37.0-1-x86_64.pkg.tar.zst \
;
```

makes the issue apparent.

### Reproduction steps

We need to work through at least 2 different scenarios by calling the following script with either `1` or `2`:

```
#!/usr/bin/env bash

# Disabling at least one of the following lines will make the issue disappear:
video_sync='--video-sync=display-resample'
interpolation='--interpolation'

case "$1" in
  1) scenario=(B.mkv A.mkv B.mkv A.mkv B.mkv) ;;
  2) scenario=(A.mkv B.mkv C.mkv) ;;
  *) exit 1 ;;
esac

mpv --no-config -v -v --log-file=output.log --loop-playlist=inf $video_sync $interpolation -- "${scenario[@]}"
```

### Expected behavior

Video should always be played back alongside audio.

### Actual behavior

In scenario 1, everything seems fine.

Scenario 2 is more difficult:

1. Playback of `A.mkv` works fine.
2. Go forward in playlist to `B.mkv`. `B.mkv` now freezes but audio is fine. Video updates occur only when pausing, seeking, etc.
3. Go forward in playlist to `C.mkv`. Playback of `C.mkv` works fine.
4. Go backwards(!) in playlist to `B.mkv`. Suddenly, `B.mkv` works just fine.
5. Go backwards in playlist to `A.mkv`. Everything is still fine.
6. Go forward in playlist to `B.mkv`. `B.mkv` still works, and it will continue to do so as long as you never go forward in playlist after `C.mkv` (which is only possible because of `--loop-playlist=inf`)
7. Go forward in playlist to `C.mkv`, and now forward yet again to make the player restart the playlist. The issue will now reappear, so back to step 1.

Apparently, when using the combination `--video-sync=display-resample --interpolation` (and possibly others), not everything is reset beween files as needed. Only some files reproduce the issue but most do not. Also, playback order is important.

### Log file

[output.log](https://github.com/mpv-player/mpv/files/13878031/output.log)

Log file produced while switching between playback items of scenario 2 in a way similar to the description for scenario 2.

### Sample files

Use this script for some videos that just happen to reproduce the issue:

```
#!/usr/bin/env bash

yt-dlp --ignore-config --id --remux-video=mkv -- YUY9Y9RFiHY vuo8kD5zF5I -eHJ12Vhpyc
cp -n ./YUY9Y9RFiHY.mkv A.mkv
cp -n ./vuo8kD5zF5I.mkv B.mkv
cp -n ./-eHJ12Vhpyc.mkv C.mkv
```

**Comment by llyyr** [comment]
I can reproduce this with `vo_gpu`. Using `--vo=gpu-next` should fix it

**Comment by llyyr** [comment]
Fixed with the following diff

```diff
diff --git a/player/video.c b/player/video.c
index baa6db8d84..08281ae5cc 100644
--- a/player/video.c
+++ b/player/video.c
@@ -1049,6 +1049,7 @@ static bool video_reconfig_needed(const struct mp_image_params *p1,
            p1->w != p2->w || p1->h != p2->h ||
            p1->p_w != p2->p_w || p1->p_h != p2->p_h ||
            p1->force_window != p2->force_window ||
+           !mp_colorspace_equal(p1->color, p2->color) ||
            p1->rotate != p2->rotate ||
            p1->stereo3d != p2->stereo3d ||
            !mp_rect_equals(&p1->crop, &p2->crop);
```

Introduced by https://github.com/mpv-player/mpv/commit/477a0f83184d18a5cd89261b5f81ee668c7f4441

@kasper93

**Comment by bergfried** [comment]
Thank you very much, @llyyr.

**Comment by kasper93** [comment]
We can do this, if it works for you. I'm not sure why full reconfigure would be required in this case, but I'm not looking into vo_gpu to check why.

``` diff
diff --git a/player/video.c b/player/video.c
index baa6db8d84..e870269c77 100644
--- a/player/video.c
+++ b/player/video.c
@@ -1041,17 +1041,12 @@ static void apply_video_crop(struct MPContext *mpctx, struct vo *vo)
     }
 }
 
-static bool video_reconfig_needed(const struct mp_image_params *p1,
-                                  const struct mp_image_params *p2)
+static bool video_reconfig_needed(struct mp_image_params a,
+                                  struct mp_image_params b)
 {
-    return p1->imgfmt != p2->imgfmt ||
-           p1->hw_subfmt != p2->hw_subfmt ||
-           p1->w != p2->w || p1->h != p2->h ||
-           p1->p_w != p2->p_w || p1->p_h != p2->p_h ||
-           p1->force_window != p2->force_window ||
-           p1->rotate != p2->rotate ||
-           p1->stereo3d != p2->stereo3d ||
-           !mp_rect_equals(&p1->crop, &p2->crop);
+    a.color.hdr = (struct pl_hdr_metadata){0};
+    b.color.hdr = (struct pl_hdr_metadata){0};
+    return !mp_image_params_equal(&a, &b);
 }
 
 void write_video(struct MPContext *mpctx)
@@ -1176,7 +1171,7 @@ void write_video(struct MPContext *mpctx)
 
     // Filter output is different from VO input?
     struct mp_image_params *p = &mpctx->next_frames[0]->params;
-    if (!vo->params || video_reconfig_needed(p, vo->params)) {
+    if (!vo->params || video_reconfig_needed(*p, *vo->params)) {
         // Changing config deletes the current frame; wait until it's finished.
         if (vo_still_displaying(vo))
             return;

```

**Comment by llyyr** [comment]
I forgot about this, sorry. Can you open a PR with that patch? It works fine for me

**Comment by kasper93** [comment]
I don't think this is good "fix" it just forces vo reconfig on file switch, but aren't the same condition would freeze interpolation if the files have similar parameters?
