### ISSUE TITLE
mpv reports incorrect video duration when two streams of different length are remuxed via ffmpeg

### ISSUE THREAD

**Issue by incertia** [mpv-player/mpv#13252]
Provide following Information:
- mpv v0.37.0-135-gabc2a748
- Windows 10
- scoop mpv-git
- If known which version of mpv introduced the problem
-  GPU N/A
- Possible screenshot or video of visual glitches
![image](https://github.com/mpv-player/mpv/assets/1653966/75f12146-9f11-449f-b669-00c4e169a922)

### Reproduction steps

* produce a video with audio longer than video with ffmpeg and shortest
  `$ ffmpeg -i in.mov -itsoffset -23.9 -i in.wav "-c:v" copy "-c:a" pcm_s16le -map "0:v:0" -map "1:a:0" -shortest out.mp4`
* open with mpv

the issue still exists if you allow ffmpeg to re-encode the audio to aac by omitting `-c:a pcm_s16le`

**Comment by llyyr** [comment]
Can you upload that sample file?

**Comment by incertia** [comment]
ffmpeg created file: https://0x0.st/HIqd.mp4
audio: https://0x0.st/HIqR.wav
clipped video from camera: https://0x0.st/HIq7.mov

sorry about the file size

**Comment by llyyr** [comment]
The file is just broken, the video and audio stream report different lengths and `avformat_find_stream_info` reports unknown container length.

It's probably a ffmpeg bug, it needs to set the correct length for both audio and video tracks

**Comment by incertia** [comment]
thanks for the quick turnaround on the fix!

> The problem is caused by ffmpeg using editlist when muxing by default and ffmpeg not supporting reading them(?)

i'm not sure ffmpeg doesn't support reading them because at least if i use `ffprobe -i out.mp4 -show_entries format=duration` or `ffmpeg -i out.mp4 -f null -` they both report the correct duration of either 152.953 or 2:32.95

i was previously unaware of what editlists are, so thanks for bringing that to my attention as well.
