### ISSUE TITLE
`mpv --slang=eng` doesn't enable subtitles in an MKV file

### ISSUE THREAD

**Issue by DUOLabs333** [mpv-player/mpv#13265]
### Important Information

Provide following Information:
- mpv version -- 0.36.0
- Platform and Version --- MacOS, Big Sur
- Source of the mpv binary --- Nixpkgs
- If known which version of mpv introduced the problem --- N/A
- GPU model, driver and version --- N/A
- Possible screenshot or video of visual glitches --- N/A

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
1. Have an MKV file with at least english subtitles embedded.
2. Try playing it with `mpv --slang=eng file.mkv`
### Expected behavior
English subtitles are shown and played

### Actual behavior
No subtitles show on screen

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/13911191/output.txt)

### Additional Information
`--sid=1` does work though.

**Comment by DUOLabs333** [comment]
Adding `--subs-with-matching-audio=yes` makes mkv match expected behavior.

**Comment by llyyr** [comment]
`mpv version -- 0.36.0`

Fixed in 0.37.0

**Comment by DUOLabs333** [comment]
Oh, guess I just have to wait for Nix to update.
