### ISSUE TITLE
Option non-forced subtitles by default

### ISSUE THREAD

**Issue by Piber0** [mpv-player/mpv#13263]
Hi, is there an option to select non-forced subtitles by default (as mpv did by default in the past) ? I'd like to combine it with the `slang` option.

I've tried the `subs-fallback-forced` and `subs-fallback options`, but they make no difference.

Thanks in advance !

**Comment by Dudemanguy** [comment]
If you're on the latest mpv, `--subs-fallback-forced=no` will never select a forced subtitle track. Should be what you want.
