### ISSUE TITLE
Gapless video playback

### ISSUE THREAD

**Issue by ThinkChaos** [mpv-player/mpv#13284]
### Expected behavior of the wanted feature

Not sure if this is a bug, but I chose feature request since I didn't find any issues related to this in the past.  
Currently, when playing multiple files, or using `--loop-file`, `mpv` displays a black screen for an instant between videos. It would be nice to have no pause in the content at all, similar to `--gapless-audio`.

My intended use case is to play a video as a screensaver. I have a video that's a perfect loop, but the black frame(s) make it imperfect. I'm using VLC in the mean time but would like to use mpv so I don't need VLC installed.

### Alternative behavior of the wanted feature

N/A

### Log file

[mpv.txt](https://github.com/mpv-player/mpv/files/13932105/mpv.txt)

**Comment by llyyr** [comment]
Related #10748

**Comment by ThinkChaos** [comment]
As mentioned in #13296, the file I was using had a black frame at the end...  
This can be closed :)
