### ISSUE TITLE
HEAD version not triggering NSWorkspaceDidLaunchApplicationNotification through CLI

### ISSUE THREAD

**Issue by KCAS** [mpv-player/mpv#1328]
Im using HAPU, an anime scrobbler and with the latest HEAD, it was not detecting anything playing when the video was launched through CLI.

when launched through CLI, notice that HAPU still says welcome username.
![screen shot 2014-12-10 at 10 57 58](https://cloud.githubusercontent.com/assets/7694114/5370397/5b441506-805c-11e4-8168-d5f1d7f1798e.png)

when launched normally, it was detected.
![screen shot 2014-12-10 at 10 58 43](https://cloud.githubusercontent.com/assets/7694114/5370409/7848dc4a-805c-11e4-8026-6a33dcda30c2.png)

i brought this up to inket, the one developing HAPU and he noted "Yep! It's a problem in the HEAD version. It's not triggering a system-wide notification NSWorkspaceDidLaunchApplicationNotification when launched. The previous version did."

he also mentioned "Maybe this is it: https://github.com/mpv-player/mpv/commit/73b7d4516bd2b4b06610b16de879e5b7c2cbd7ee"

**Comment by Akemi** [comment]
is this still a problem? is HAPU still around after the death of hummingbird and the rise of kitsu?

**Comment by Argon-** [comment]
Just googled it and according to their forums it does not. What's more, it already stopped working with MAL and Plex some time ago. The developer was last active in 2015, lamenting about not having time to work on it and lacking motivation.
Guess that's to be expected of a proprietary program.

(But honestly, there can't be many people using it anyway, as nearly none of these defects [e.g. MAL being broken] were reported from more than 1-2 people.)

**Comment by inket** [comment]
The real issue here is that mpv is not a good citizen of macOS. And we already established that there is no interest in making it play well with the system at https://github.com/mpv-player/mpv/pull/1346

This should have been closed a long time ago.

**Comment by wm4** [comment]
> The real issue here is that mpv is not a good citizen of macOS. 

Whatever that means.
