### ISSUE TITLE
Dropped frames with --vo=kitty after a cetrain resolution (Kitty/Wezterm/Konsole)

### ISSUE THREAD

**Issue by germaniuss** [mpv-player/mpv#13285]
### Important Information

Provide following Information:
- mpv version: 0.37.0
- Linux Distribution and Version: archlinux, 6.5.9 linux-zen kernel
- Source of the mpv binary: pacman
- If known which version of mpv introduced the problem: not known
- Window Manager and version: Gnome 45/Mutter
- GPU model, driver and version: Intel UHD Graphics 620
![image](https://github.com/mpv-player/mpv/assets/41348282/5642e904-5888-4e67-a7fb-594b4606f54f)
- Possible screenshot or video of visual glitches:
A lot of frames dropped with high resolution
![image](https://github.com/mpv-player/mpv/assets/41348282/3fa49a18-dad1-43c0-99eb-db92f41517be)
A lot less frames dropped with low resolution
![image](https://github.com/mpv-player/mpv/assets/41348282/3591d1cc-c583-48be-8faf-3e7973a1218d)

This might be related to both https://github.com/mpv-player/mpv/issues/13186 and https://github.com/mpv-player/mpv/issues/13273 though that is just speculation on my part.

### Reproduction steps

1. Run any high resolution video with `mpv --no-config --vo=kitty <your-video>` in a supported terminal (I tested `kitty`, `wezterm` and `konsole`)
2. Resize the window to high resolution or fullscreen (it starts dropping frames)
3. Resize the window to a low resolution (there are a lot less dropped frames)

### Expected behavior
No frames to be dropped on high resolutions, same as at low resolutions

### Actual behavior
Frames are being dropped

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/13932476/log.txt)

**Comment by germaniuss** [comment]
Same thing happens with `--vo=sixel`. If I however run it with `--vo=gpu` the problem does not exist (but it does not run in the terminal)

**Comment by llyyr** [comment]
This is a feature request or optimization request for the terminals you're using, there's not much to be done here from mpv's side. Watching videos in the terminal is stupid to begin with, use vo_gpu or vo_gpu_next if you want to watch videos, the terminal VOs are mostly a joke.

**Comment by germaniuss** [comment]
I know it's a stupid idea but since mpv has support for it I want to try anyways, since it's more of an experiment than anything else. I will try out if timg presents the same problem since it seems wierd to me that the same optimization issue exists in every terminal I tried (though it could definitely be the case)

**Comment by germaniuss** [comment]
> I know it's a stupid idea but since mpv has support for it I want to try anyways, since it's more of an experiment than anything else. I will try out if timg presents the same problem since it seems wierd to me that the same optimization issue exists in every terminal I tried (though it could definitely be the case)

It does not happen when running `timg <my-video>` so I am fairly certain this is an mpv issue.

**Comment by germaniuss** [comment]
> `--sws-scaler=fast-bilinear --sws-fast=yes`

Doesn't solve the issue unfortunately

**Comment by germaniuss** [comment]
> `--vo-kitty-use-shm=yes` If this still doesn't work, then mpv's implementation is likely at fault.

That solved it! Thanks a lot!

**Comment by Dudemanguy** [comment]
Seems like the problem was solved.

**Comment by shmerl** [comment]
> That solved it! Thanks a lot!

What version of konsole were you testing it in?

I just tried in 23.08.1, and with `vo-kitty-use-shm` it's not showing any video.

**Comment by germaniuss** [comment]
> > That solved it! Thanks a lot!
> 
> What version of konsole were you testing it in?
> 
> I just tried in 23.08.1, and with `vo-kitty-use-shm` it's not showing any video.

Sorry, I only tested using `vo-kitty-use-shm` in Kitty, it seems to me neither Wezterm nor Konsole implement the shared memory optimization.

**Comment by rouffy-dawg** [comment]
Tried running with the latest version of wezterm that is from releases, as well as compiling it myself from source. None of the two resulted in the video being shown when running with kitty shared memory option. It just stayed a blank terminal with just the audio playing.

**Comment by lvlv6994** [comment]
我在使用--vo-kitty-use-shm 也是不显示，倒是发现视频如果被放大会出现掉帧的现象，用--vo-kitty-width=1000 指定一下宽度会好很多。https://github.com/mpv-player/mpv/commit/874e28f4a41a916bb567a882063dd2589e9234e1#diff-47f65c6ffc9837b14c82867d688ae7f7f0729173f6f9d92b29da3dee44ebdae2R34
