### ISSUE TITLE
Use aria2c to stream video

### ISSUE THREAD

**Issue by Jayant-Goyal** [mpv-player/mpv#13292]
I want to use aria2c to stream videos in mpv. When I paste the link to the video (a direct download link not YouTube or anything else) I want it use aria2c as the downloader instead of ffmpeg which I think it uses by default. Can I do that?

**Comment by llyyr** [comment]
> Can I do that?

no.

**Comment by MoSal** [comment]
If the stream does not require reading demux data from the end for playback, you can pipe with `saldl`.

For example:

```
mpv <(saldl -m --stdout --no-status https://archive.org/download/sherlock-holmes-movies-colorized/Adventures%20of%20Sherlock%20Holmes%201939%20colorized.mp4)
```

This is a use-case I had in mind when I wrote the tool.
