### ISSUE TITLE
The bitrate unit conversion is incorrect

### ISSUE THREAD

**Issue by verygoodlee** [mpv-player/mpv#13306]
### Important Information
- mpv version
```
mpv v0.37.0-174-g92676007 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Jan 16 2024 00:13:13
libplacebo version: v6.338.0-64-g34e019b-dirty
FFmpeg version: N-113344-gbe4fcf027
FFmpeg library versions:
   libavutil       58.36.101
   libavcodec      60.37.100
   libavformat     60.20.100
   libswscale      7.6.100
   libavfilter     9.17.100
   libswresample   4.13.100

```
- Windows Version
Win10 22H2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240117
### Reproduction steps
input.conf show bitrate 
```
# ${=video-bitrate}            return bps
# ${video-bitrate}             return kbps (or mbps, if appropriate)
# ${packet-video-bitrate}      return kpbs
c show-text '${osd-ass-cc/0}${=video-bitrate}\N${video-bitrate}\N${packet-video-bitrate}' 5000
```
![1705540581547](https://github.com/mpv-player/mpv/assets/45035465/f6edae8f-95fd-4125-8092-b534d92f8196)
### Expected behavior
`1 mbps = 1024 kbps = 1024*1024 bps`
So the correct unit conversion in the example is `1118776 bps = 1093 kbps = 1.067 mbps`
### Actual behavior
`1 mbps = 1000 kbps = 1000*1000 bps`

**Comment by verygoodlee** [comment]
I was wrong. I never noticed that bit and Byte had different conversion rules. \
`1 Byte = 8 bit` but `1 kByte != 8 kbit`，which is quite confusing.

**Comment by christoph-heinrich** [comment]
That's the wrong takeaway.

`1 kByte == 1000 Byte` and `1 kbit == 1000 bit`
`1 kiByte == 1024 Byte` and `1 kibit == 1024 bit`

**Comment by verygoodlee** [comment]
but in the operating system, the filesize is never written as ki, only K, `1KB = 1024B`

**Comment by Hrxn** [comment]
Yes, this is technically wrong.

Or, from the OS perspective (i.e. software side, they use KB with base 2, so what would more formally be `KiB`

**Comment by hooke007** [comment]
> but in the operating system, the filesize is never written as ki, only K

No. Check KDE
