### ISSUE TITLE
Greatly diminished ASS subtitle rendering performance on gpu-next with vulkan

### ISSUE THREAD

**Issue by Vodes** [mpv-player/mpv#13303]
### Important Information
- Windows 11 Enterprise (23H2)
- mpv version `v0.37.0-161-gbd35dc8c` (the 2024-01-14 shinchiro build)
- Ryzen 7 5800x, RTX 3060ti (latest, as of writing 546.33, Studio Driver)

### Reproduction steps

Run `mpv --no-config --vo=gpu-next --gpu-api=vulkan H0q_.mkv`

I am not sure if this is limited to windows or not.
No issues when using `gpu-api=d3d11`.

### Actual behavior

[Video of subtitles glitching out](https://0x0.st/H0qf.mp4)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/13967051/output.txt)

### Sample files

[Sample mkv file](https://0x0.st/H0q_.mkv)

**Comment by guidocella** [comment]
I can reproduce the Allocation failed on Linux.

**Comment by Vodes** [comment]
Done a little more testing.



> > [   3.941][e][vo/gpu-next/libplacebo] Allocation of size   56M failed: VK_ERROR_OUT_OF_DEVICE_MEMORY!
> 
> Can't reproduce on linux, can you try seeing if this is a regression or not?

It happens on `0.35.0-348-g0f13c38e`/2023-04-02 but does not happen on `0.35.0-129-g92a6f2d687`/2023-01-22. I'll probably try narrowing it down later/tomorrow if no one else does it before me.

**Comment by Jules-A** [comment]
> This is a known issue with libplacebo not falling back to other types of memory when allocation on memory types with both `HOST_VISIBLE` and `DEVICE_LOCAL` bits fail. There are other issues of mpv sharing the same root cause like #12517.

Ah that's probably why it instantly returns with out of memory (12GB) when trying to encode using libplacebo filter.

**Comment by haasn** [comment]
```
        // We generally prefer VRAM since it's faster than RAM, but any number
        // of other requirements could potentially exclude it, so just mark it
        // as optimal by default.
        if (!(mparams.optimal & VK_MEMORY_PROPERTY_HOST_CACHED_BIT))
            mparams.optimal |= VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
```

Does this fix it?

**Comment by haasn** [comment]
See https://code.videolan.org/videolan/libplacebo/-/merge_requests/646 for better potential fix
