### ISSUE TITLE
Get key state in Lua script

### ISSUE THREAD

**Issue by JimPancakes** [mpv-player/mpv#13308]
Is there anything that can be used in a Lua script close to a mp.get_property_native that would return if a key is currently being pressed?

Something like mp.get_property_native("MBTN_LEFT") and have it return 1 if it's currently being held and 0 if it's not.

**Comment by po5** [comment]
You want to use a [complex keybind.](https://mpv.io/manual/master/#lua-scripting-complex)

**Comment by po5** [comment]
[evafast](https://github.com/po5/evafast/tree/rewrite) has that functionality, it waits for the first `repeat` event. You can also use [a timer](https://mpv.io/manual/master/#lua-scripting-mp-add-timeout(seconds,-fn-[,-disabled])) on which you stop and re-spawn on the `down` event. Read the documentation for complex bindings.

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/input-event

```
MBTN_LEFT       show-text 0        #@click
MBTN_LEFT       show-text 1        #@press
```
