### ISSUE TITLE
No sound in libmpv or mpv flatpak since 0.37

### ISSUE THREAD

**Issue by Sunspark-007** [mpv-player/mpv#13312]
Provide following Information:
- mpv version: v0.37.0
- Linux Distribution and Version: SteamOS 3.4.11
- Source of the mpv binary: flathub
- If known which version of mpv introduced the problem: 0.37.0
- Window Manager and version: KDE Plasma 5.26.1
- GPU model, driver and version: AMD Custom GPU 0405
- Possible screenshot or video of visual glitches: n/a, sound issue

### Reproduction steps

Try to reproduce your issue with --no-config first: Attempted, no change.

### Expected behavior
When a file containing audio is played that audio be played.

### Actual behavior
No audio is played by mpv or frontends using libmpv. 

Audio USED to work on both with 0.36 and earlier.

Audio still works with the system, all web browsers, vlc, games, etc.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/13980847/output.txt)

### Sample files

n/a, this affects 100% of all files/playlists.

in qpwgraph:
![image](https://github.com/mpv-player/mpv/assets/73711243/0b48e96c-7903-45a7-be94-9a4c8ed9f920)

in PulseAudio Volume Control:
![image](https://github.com/mpv-player/mpv/assets/73711243/284b2813-5e0b-40b7-85da-ea32cf1a0018)

**Comment by llyyr** [comment]
You can try specifying `ao=pipewire` or `ao=pulse` explicitly but there is no official mpv flathub, and thus no support here. Ask here instead: https://github.com/flathub/io.mpv.Mpv/issues

**Comment by Sunspark-007** [comment]
@llyyr Thanks! Update, ao=pipewire is silent, but ao=pulse has sound!

My understanding is incomplete.. this is a pipewire system.. shouldn't both options work? 

Since libmpv is being affected as well, do the frontends all need to be notified as well, or is libmpv considered here?

**Comment by llyyr** [comment]
> Since libmpv is being affected as well, do the frontends all need to be notified as well, or is libmpv considered here?

This is probably an issue with the Flatpak, not mpv or libmpv or any frontends using it.

**Comment by Sunspark-007** [comment]
Ok thanks, in addition to the flatpak link you gave me which I opened a bug report at, I also opened one up on the Haruna frontend because it doesn't have command line switches to do anything with audio using the terminal (it uses libmpv and sets the switches internally).

https://bugs.kde.org/show_bug.cgi?id=479724

**Comment by Sunspark-007** [comment]
Update:

Downgrading mpv to 0.36 on SteamOS 3.4.11 restores sound and also fixes 2 other issues I was experiencing.

0.37 will work on 3.5.x as-is.

0.36 uses the 22.08 freedesktop runtime, and 0.37 uses the 23.08 runtime, but surely that can't be the only reason when I have both runtimes installed..

**Comment by Dudemanguy** [comment]
pipewire works fine with mpv and libmpv (I use both daily). I assume there is some sort of permission or configuration issue with flatpak. No idea how that works, but that is out of our control and not something we can fix.
