### ISSUE TITLE
Difficulty Escaping Parentheses in Video Filters

### ISSUE THREAD

**Issue by farsighter** [mpv-player/mpv#13328]
### Important Information

Provide following Information:
- mpv version
mpv 0.32.0
- Linux Distribution and Version
Ubuntu 20.04.4 LTS
- Source of the mpv binary
apt-get
- If known which version of mpv introduced the problem
By the nature of the problem I assume all versions
- Window Manager and version
None
- GPU model, driver and version
Headless server no gpu
- Possible screenshot or video of visual glitches
Not applicable 

### Reproduction steps
I'm currently having trouble applying video filters that include parentheses when using MPV as an encoder. Specifically, I am trying to use the scale and crop filters together in a single command.

The commands I'm attempting to run: any MPV command that includes `--vf=scale=iw/2:-2,crop=iw-mod(iw\,2):ih`
For example:
`mpv --vf=scale=iw/2:-2,crop=iw-mod(iw\,2):ih test.mp4 --ovc=libx264 --oac=aac --o=output.mp4`

Such commands result in a bash syntax error due to the parentheses in the crop filter. The error message is:
bash: syntax error near unexpected token `(' 

I have tried various ways to escape the parentheses, including using single quotes,  double quotes, single backslashe or double backslashes \\, but none of these methods have worked.

According to the documentation and other user discussions, mpv should support the same filter syntax as ffmpeg. Therefore, I believe this is a bug or limitation in mpv's handling of parentheses in the command line.

Could someone please investigate this issue and provide guidance on how to correctly escape parentheses in mpv commands?
Alternatively, if this is a known limitation of mpv, could you please provide a fix,  workaround or alternative method to achieve the same result?

### Expected behavior
Mpv correctly parsing the filters.
### Actual behavior
bash: syntax error near unexpected token `(' 
### Log file
When attempting to run the command  without quotes around the filters ( --vf=scale=iw/2:-2,crop=iw-mod(iw\,2):ih ) the command exits on error without even creating a log file.
When using quotes as in the following command a log file with fatal error is created:
`mpv  --log-file=output.txt --vf='scale=iw/2:-2,crop=iw-mod(iw\,2):ih' test.mp4 --ovc=libx264 --oac=aac --o=output.mp4`
Log file: https://pastebin.com/yhLmLKvf

**Comment by llyyr** [comment]
`vf` doesn't support ffmpeg [expression evaluation](https://ffmpeg.org/ffmpeg-utils.html#Expression-Evaluation). `lavfi-complex` does, use that instead

**Comment by farsighter** [comment]
Thank you very much. Like this it seems to work:
`mpv --vf=lavfi="[scale=iw/2:-2,crop=iw-mod(iw\,2):ih]" test.mp4 --ovc=libx264 --oac=aac --o=output.mp4`
