### ISSUE TITLE
как поменять шрифт плеера и сабов?

### ISSUE THREAD

**Issue by subsubsubsubsubsub** [mpv-player/mpv#13323]
![sshot-002](https://github.com/mpv-player/mpv/assets/73518754/4ce68b3e-749e-477c-925c-2b2000a353f2)

**Comment by haasn** [comment]
https://mpv-io.translate.goog/manual/stable/?_x_tr_sl=auto&_x_tr_tl=ru&_x_tr_hl=en&_x_tr_pto=wapp#options-osd-font

Может быть, это поможет?
