### ISSUE TITLE
`--target-contrast` inneffective with `--target-colorspace-hint` or `--target-trc=pq`

### ISSUE THREAD

**Issue by NotMithical** [mpv-player/mpv#13329]
### Important Information

Provide following Information:
- mpv version: 0.37.0-193-g700f72f8
- Windows Version: Windows 10 22H2, Build 19045.3803
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild
- GPU model, driver and version: Nvidia Geforce RTX 4060, driver version 546.65

### Reproduction steps

Play a PQ video with `--no-config --vo=gpu-next --target-colorspace-hint=yes --target-peak=1000` and attempt to change `target-contrast` at runtime

### Expected behavior
The resulting image has the black point adjusted accordingly as it does when `--target-colorspace-hint=no` or when `--target-trc=` is set to srgb, gamma, or bt.1886.

### Actual behavior
The resulting image does not change at all.

I've reproduced this on another machine running Ubuntu as well, where HDR output isn't supported but there should be a noticeable change in the image regardless.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/13999410/log.txt)

**Comment by haasn** [comment]
This is by design. PQ is always scaled down to absolute zero (0), irrespective of the true monitor contrast.

**Comment by NotMithical** [comment]
> PQ is always scaled down to absolute zero

Just to clarify, this is only for PQ->PQ right? Because when I'm watching an SDR source with `--target-trc=pq`, `--target-contrast` behaves as expected.

**Comment by haasn** [comment]
> > PQ is always scaled down to absolute zero
> 
> Just to clarify, this is only for PQ->PQ right? Because when I'm watching an SDR source with `--target-trc=pq`, `--target-contrast` behaves as expected.

Well, what happens in the case of SDR->PQ is that `target-contrast` effectively controls the *source* contrast, which then gets expanded down to absolute black for PQ output.

**Comment by NotMithical** [comment]
Ah, understood, thank you.
