### ISSUE TITLE
vaapi based encoding

### ISSUE THREAD

**Issue by lvml** [mpv-player/mpv#1333]
In the past, I used ffmpeg to transcode 4k videos to 2k videos, and since that was a very time consuming task I was happy to see how the use of mpv's option --hwdec=vaapi-copy can speed up this process - I now use a script like this:

> mpv --hwdec=vaapi-copy --of=matroska --ofps=24000/1001 --ovc=libx264 --oac=flac --ovcopts=qp=13  --ovcopts=profile=high444 -vf scale=1920:1080,format=fmt=yuv444p --o=somefile.mkv inputfile

I was wondering whether the h.264 encoding, being now the by far most time consuming part of the task (even with x264's preset=ultrafast) could not be accelerated by using the hardware h.264 encoder that is part of the Intel GPU. And in fact, using http://cgit.freedesktop.org/libva/tree/test/encode/h264encode.c I can encode 1080p videos at > 100 fps, the only problem being that "h264encode" expects its input as a raw YUV file, which you really don't want to keep around for any longer-than-a-few-seconds video.

Would it be possible to have mpv support hardware encoding via vaapi, just as the linked example executable does, only with the added comfort of being able to use any kind of video as the input?

**Comment by Brainiarc7** [comment]
Hello there,@lvml, take a look at this:

https://gist.github.com/Brainiarc7/95c9338a737aa36d9bb2931bed379219

Shows you how to achieve the same with ffmpeg and libav.

**Comment by lvml** [comment]
@Brainiarc7: Thanks for pointing this out, I compiled a new ffmpeg version and indeed, on some laptop where I can use this for fast transcoding of camera files to intermediates on the laptop, this really helps. The core i7 can encode 1080p recordings at ~80 fps using the h264_vaapi, while x264 does ~15 fps on the same computer. 2160p recordings are encoded at ~25 fps using h264_vaapi, while x264 does ~3 fps.

Sure, x264 provides much better quality at the same bitrate, but for intermediate clip files, I can spend plenty of bitrate (like 200MBit/s), that's still much better to handle than "uncompressed video", and at such high bitrates, quality is good even from the hardware encoder.

**Comment by lvml** [comment]
@Brainiarc7: But unluckily, at least my core i7 produces encoding errors (areas in the bottom half of the screen with false-color regions) when used with 2160p images - 1080p encoding works fine.

**Comment by lvml** [comment]
Good news: I found that https://git.libav.org/?p=libav.git;a=patch;h=8a62d2c28fbacd1ae20c35887a1eecba2be14371 fixes the 2160p hardware encoding problems I encountered.

**Comment by Brainiarc7** [comment]
Hey there, @lvml , I'm glad it worked out so well for you :-)

Keep it up :-)
