### ISSUE TITLE
Locales of audio and pgs subtitles not detected

### ISSUE THREAD

**Issue by pppbb** [mpv-player/mpv#13341]
### Important Information

Provide following Information:
- mpv version : mpv master
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: built from source, official Arch repository
- If known which version of mpv introduced the problem
- Window Manager and version: gdm, mutter,wayland
- GPU model, driver and version: rtx 4080 545.29.06
- Possible screenshot or video of visual glitches

### Reproduction steps
open Blu-ray 4k film The Batman (for example backup copy from hdd) 

### Expected behavior
Expected audio and subtitles locales to be attached.
### Actual behavior
No locales of audio and subtitle tracks. There is no problem with vlc.
### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/14007689/mpv.log)

**Comment by llyyr** [comment]
```
[   0.069][d][ffmpeg/demuxer] mpegts: parser not found for codec hdmv_pgs_subtitle, packets or times may be invalid.
[   0.070][d][ffmpeg/demuxer] mpegts: parser not found for codec hdmv_pgs_subtitle, packets or times may be invalid.
[   0.078][w][ffmpeg/demuxer] mpegts: Could not find codec parameters for stream 19 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
[   0.078][w][ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[   0.078][w][ffmpeg/demuxer] mpegts: Could not find codec parameters for stream 20 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
[   0.078][w][ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[   0.078][w][ffmpeg/demuxer] mpegts: Could not find codec parameters for stream 21 (Subtitle: hdmv_pgs_subtitle (pgssub) ([144][0][0][0] / 0x0090)): unspecified size
...
```

Hard to debug this without a sample

**Comment by pppbb** [comment]
> Hard to debug this without a sample

How could i provide you a sample?

**Comment by llyyr** [comment]
Trim the file down to a few seconds while keeping all the subtitle tracks with ffmpeg, check if you can still reproduce the issue with the trimmed file then upload it here

**Comment by pppbb** [comment]
> Trim the file down to a few seconds while keeping all the subtitle tracks with ffmpeg, check if you can still reproduce the issue with the trimmed file then upload it here

Its useless because there is no metadata in m2ts file. I remind you its blu-ray disk.

**Comment by llyyr** [comment]
> Its useless because there is no metadata in m2ts file. I remind you its blu-ray disk.

> There is no problem with vlc.

How is VLC inventing metadata out of thin air? And if you're aware that the file has no metadata then why is this a mpv issue?

**Comment by cubicibo** [comment]
Transport streams do have metadata.
TS files periodically include a PSI packet with a program table listing all of the elementary streams.

**Comment by pppbb** [comment]
Update: It is possibly not mpv fault. I played the movie directly from the optical disc and language of audio and pgs subtitles was recognized correctly. When i play the movie from backup copy from hdd the languages are not correctly detected.

**Comment by pppbb** [comment]
> the m2ts has no meadata, correct, but .bdmv and .mpls does have metadata, so we can use that.

I could post .bdmv and .mpls files but unfortunately it is illegal.

**Comment by pppbb** [comment]
I don't know how it happened but it works for me now.
