### ISSUE TITLE
Strange behaviour for user-data value

### ISSUE THREAD

**Issue by tsl0922** [mpv-player/mpv#13344]
### Important Information

Provide following Information:
- mpv version: v0.37.0-198-ga39f9b61
- Platform: Windows 10 22H2
- Source of the mpv binary: shinchiro

### Reproduction steps

**test.lua**
```lua
local msg = require('mp.msg')

local path_prop = 'user-data/menu/dialog/default-path'
local name_prop = 'user-data/menu/dialog/default-name'

mp.set_property(path_prop, 'D:\\')
mp.set_property(name_prop, '1.txt')

msg.info('path: ' .. mp.get_property(path_prop))
msg.info('name: ' .. mp.get_property(name_prop))

msg.info('path: ' .. mp.get_property_native(path_prop))
msg.info('name: ' .. mp.get_property_native(name_prop))
```

Run mpv: `mpv --msg-level=all=info`

### Expected behavior

output:

```
[test] path: D:\
[test] name: 1.txt
[test] path: D:\
[test] name: 1.txt
```

### Actual behavior

output:

```
[test] path: "D:\\"
[test] name: "1.txt"
[test] path: D:\
[test] name: 1.txt
```

only `mp.get_property_native` gives right value, the `mpv_get_property_string(mpv, '...')` C API behaves like `mp.get_property(...)` lua api.

(EDIT: it seems `mpv_get_property(mpv, '...', MPV_FORMAT_NODE)` works fine)

**Comment by po5** [comment]
This is intended: `Converting this property or its sub-properties to strings will give a JSON representation.`

**Comment by tsl0922** [comment]
> If converting a leaf-level object (i.e. not a map or array) and not using raw mode, the underlying content will be given (e.g. strings will be printed directly, rather than quoted and JSON-escaped).

**Comment by po5** [comment]
Raw is get_property_native.

**Comment by stax76** [comment]
I was confused by this too, until CogentRedTester pointed out what's happening.

**Comment by butterw** [comment]
An example would be welcome in the manual to show what this means.

from https://mpv.io/manual/master/#property-list
"**user-data (RW)**
[...]
    Converting this property or its sub-properties to strings will give a JSON representation. If converting a leaf-level object (i.e. not a map or array) and not using raw mode, the underlying content will be given (e.g. strings will be printed directly, rather than quoted and JSON-escaped).
"
