### ISSUE TITLE
Question regarding Intel/Nvidia Laptop

### ISSUE THREAD

**Issue by BEST8OY** [mpv-player/mpv#13356]
Hello
I have a Laptop with this spec:
```
CPU: Intel i5-10210U (8) @ 4.200GHz
GPU: Intel CometLake-U GT2 [UHD Graphics]
GPU: NVIDIA GeForce MX130
OS: Arch Linux
```
The Nvidia GPU doesn't support any hwdec like NVDEC or vulkan (It supports d3d11 but I'm on a Linux OS)
The only hwdec supported by my laptop is vaapi-copy (gpu-next)

**My question is why my Nvidia GPU start working in both software decoding and hwdec=vaapi-copy?**

I couldn't find any information about this!

**Comment by kasper93** [comment]
> My question is why my Nvidia GPU start working in both software decoding and hwdec=vaapi-copy?

GPU is used also to render, not only decode. For Vulkan you can select with this option https://mpv.io/manual/master/#options-vulkan-device for other you will have to figure out how to control GPU selection on your system.

**Comment by BEST8OY** [comment]
> > My question is why my Nvidia GPU start working in both software decoding and hwdec=vaapi-copy?
> 
> GPU is used also to render, not only decode. For Vulkan you can select with this option https://mpv.io/manual/master/#options-vulkan-device for other you will have to figure out how to control GPU selection on your system.

I get and error about this `VK_KHR_video_encode_queue gpu` with both Nvidia and Intel.
They don't seem to support Vulkan because I can't find any parameter containing "video" with "vulkaninfo".

Anyway, I got my answer regarding Nvidia GPU.
Thank You.
