### ISSUE TITLE
support for rtx video hdr

### ISSUE THREAD

**Issue by Hugs288** [mpv-player/mpv#13352]
nvidia just released rtx video hdr in their newest drivers

https://www.nvidia.com/download/driverResults.aspx/218113/en-us/

it can convert sdr content into hdr and from my testing its really good, i would appreciate if this could be implemented.

**Comment by kasper93** [comment]
Have you tried https://mpv.io/manual/master/#options-inverse-tone-mapping ?

**Comment by Hugs288** [comment]
no, ill try it out and see how it compares.

**Comment by CounterPillow** [comment]
Need nvidia CumWorks® AI HDR SuperBlasting 5G Smart Cloud Enhancing (Donut Steel and do not ask for technical details or documentation) on my PenisExploder 4000 via DLL injection into chrome.exe to transform my SDR source into what passes as HDR, so that my 400 nit """HDR""" consoomer monitor/television can then crudely tonemap it down to SDR in its display processor again while cranking the saturation up

**Comment by kasper93** [comment]
> no, ill try it out and see how it compares and post my findings here.

You might also try with `libplacebo-opts=gamut_expansion=yes` for completeness.

**Comment by kasper93** [comment]
need `vo=gpu-next` and set `target-peak` and possibly `target-colorspace-hint`. In short need to configure correctly to output HDR signal and then you can inverse SDR one.

**Comment by Hugs288** [comment]
alright, thanks

**Comment by Hugs288** [comment]
getting rtx video hdr to work has been such a pain in the ass, its very picky about which videos it chooses to alter and sometimes even when it doesnt it puts a load on the gpu anyway -_-, ill try again tomorrow

**Comment by kasper93** [comment]
Here is chromium code to enable appropriate processor through ID3D11VideoProcessor https://github.com/chromium/chromium/commit/b2fae4c98404bec282f24cd7d8a63aced9070fda

Have fun, all it all it is easy patch to make for someone with hardware.

**Comment by aloola18** [comment]
if you are on Windows, you only need to download Nvidia App beta and add mpv.exe, then turn on RTX HDR there. work perfectly for me

![image 1](https://github.com/mpv-player/mpv/assets/38654884/38510809-a2b4-4bf6-9d13-19ea82a9512e)

limitation: RTX HDR doesn't work with multi monitors, you need to turn other monitors off to use it

**Comment by JoaoMXN** [comment]
> if you are on Windows, you only need to download Nvidia App beta and add mpv.exe, then turn on RTX HDR there. work perfectly for me
> 
> ![image 1](https://private-user-images.githubusercontent.com/38654884/321145426-38510809-a2b4-4bf6-9d13-19ea82a9512e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NzQ2MjksIm5iZiI6MTcxMjk3NDMyOSwicGF0aCI6Ii8zODY1NDg4NC8zMjExNDU0MjYtMzg1MTA4MDktYTJiNC00YmY2LTlkMTMtMTllYTgyYTk1MTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDAyMTIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYjU1MDgwN2VmMjA0MDY0MTA3NDQ4ZGY2ZThhMjVlNTBhZTk4MDlhZGM3NTJjZTQ3ZWFiYzNkMmRjNTNkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t-PiTlwCDufHVn4sxOJTI9U6Ir83nlCeVZ3Bo2l9BF0)
> 
> limitation: RTX HDR doesn't work with multi monitors, you need to turn other monitors off to use it

This works with Stremio? I tried putting the stremio.exe but it still the same as not set. Stremio uses MPV under the hood according to the devs.

**Comment by Johnnycyan** [comment]
I will also add if you DO have multiple monitor you can use [NvTrueHDR](https://www.nexusmods.com/site/mods/781) and add mpv to force Nvidia RTX HDR in the application.

You can alternatively do this same step but for the program LosslessScaling and then you will only enable HDR when you enable LosslessScaling on mpv (or any other program)

[NvTrueHDR](https://www.nexusmods.com/site/mods/781) also has an optional config file for [Nvidia Profile Inspector](https://github.com/Orbmu2k/nvidiaProfileInspector) which gives a few more configuration options.

**Comment by kasper93** [comment]
I've added support for this, if anyone wants to try. I don't have hardware to test this on. Might need also set output format with `format` and maybe `d3d11-output-csp`, but I don't know. Someone need to test, what is proper configuration for output. But the processor should be enabled with the above change.

**Comment by R8s6** [comment]
@kasper93 thank you so much for bringing this to mpv on windows!

any chance this could be used on linux desktop (with nvidia 30/40 series gfx card)?
