### ISSUE TITLE
Support WebVTT cue settings

### ISSUE THREAD

**Issue by LordMZTE** [mpv-player/mpv#13353]
Let's consider this simple file `test.vtt`:
```vtt
WEBVTT

00:00.000 --> 00:05.000 align:right
test
```

This is what this looks like when loaded with `mpv some_video.mkv --sub-file=test.vtt`
(bottom of the window shown):
![screenshot](https://github.com/mpv-player/mpv/assets/28735087/0124bc77-f58d-4f57-aaf5-cef357d756ed)

### Expected behavior of the wanted feature
The text should be right-aligned instead of centered as described [here](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#styling_webvtt_cues) and [here](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#cue_settings).

It is perfectly reasonable for MPV to not support full CSS styling, however a certain subset of cue settings (which are optionally included to the right of cue timings) such as `align` seem realistic to implement.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/14042347/mpv.log)

related: #13120

**Comment by llyyr** [comment]
This is a feature request for FFmpeg. https://trac.ffmpeg.org/

**Comment by Akemi** [comment]
dupicate of #7214
reported to ffmpeg https://trac.ffmpeg.org/ticket/8410
kinda related to https://trac.ffmpeg.org/ticket/9064
