### ISSUE TITLE
dmabuf-wayland video at >1.0 speed causes memory leak

### ISSUE THREAD

**Issue by JosefLitos** [mpv-player/mpv#13364]
### Important Information

Provide following Information:
- mpv version: `0.37.0`; the same happens in `0.36.0`
- Linux Distribution and Version: `Archlinux`, kernel `6.7.1`
- Source of the mpv binary Arch `extra` repo
- Window Manager and version: `sway 1.8.1`
- GPU model, driver and version
  - integrated `AMD Radeon Graphics`
  - `Mesa Gallium driver 23.3.3-arch1.1`
- Possible screenshot or video of visual glitches

### Reproduction steps

1. caused by `dmabuf-wayland` → must be run on wayland
2. run cmd bellow and wait until the cache is saturated (150MB)
```sh
mpv --no-config --vo=dmabuf-wayland --speed=2 --pause 'https://www.twitch.tv/videos/2041126076'
```
3. open `htop` and check your entire system memory usage
4. unpause the video and let it play for a few seconds
5. after a short while you'll see your memory usage rapidly increasing ~200+MB/s
6. stop the video as soon as you notice it so you don't run out of memory

### Expected behavior

as without `--vo=dmabuf-wayland`, as in _no mem leaks_

### Actual behavior

after saturating the cache and playing a video back at >1 speed the memory starts leaking. The rate depends on the video playback speed and video quality

mpv reports a desynchronization in video and then it starts leaking massively, but that also causes very noticeable stutter, that I haven't encountered when noticing the leaks at lower video quality (try and see with `--ytdl-format='bv*[height=720]'`

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/14064749/output.txt)

leaks occur after reaching line 529 - video desync

**Comment by Dudemanguy** [comment]
Hmm yes, a dropped frame isn't delivered to the vo and should be freed. Does this fix it?

```
diff --git a/video/out/vo.c b/video/out/vo.c
index 7581d9680e..1a385f8285 100644
--- a/video/out/vo.c
+++ b/video/out/vo.c
@@ -1003,7 +1003,7 @@ static bool render_frame(struct vo *vo)
     wakeup_core(vo);
 
 done:
-    if (!vo->driver->frame_owner)
+    if (!vo->driver->frame_owner || in->dropped_frame)
         talloc_free(frame);
     mp_mutex_unlock(&in->lock);
 
```

**Comment by JosefLitos** [comment]
yes, it shows no increase in overall memory at all, that was surprisingly simple, thank you!
