### ISSUE TITLE
What Does Specifying a Icc Profile Do?

### ISSUE THREAD

**Issue by FriedTofu527** [mpv-player/mpv#13374]
What does the option icc-profile do? When I specify a icc profile using this option, it makes the video extremely dark in certain scenes to the point where almost nothing is visible anymore. I've attached pictures of a dark and a bright scene for comparison.

with icc-profile set:
<img width="1512" alt="Screenshot 2024-01-29 at 3 36 41 AM" src="https://github.com/mpv-player/mpv/assets/62116058/a3230368-5ad5-4db8-b19a-3097c1e23d47">

without icc-profile set:
<img width="1512" alt="Screenshot 2024-01-29 at 3 35 21 AM" src="https://github.com/mpv-player/mpv/assets/62116058/fa9bc424-224a-44e6-9ec0-33f25503b06d">

with icc-profile set:
<img width="1512" alt="Screenshot 2024-01-29 at 4 01 33 AM" src="https://github.com/mpv-player/mpv/assets/62116058/36d5abbb-5897-4e70-a882-4242b1d132c5">

without icc-profile set:
<img width="1512" alt="Screenshot 2024-01-29 at 4 06 36 AM" src="https://github.com/mpv-player/mpv/assets/62116058/4e0c5bb6-45c8-4d9a-9cd9-8d3eadfe9083">

device: 2021 M1 MacBook Pro on Sonoma 14.2
mpv version: v0.37.0-230-gd90a5ff17a
libplacebo version: v6.338.0-65-g741b604c
mpv conf:
```
vo=gpu-next
icc-profile="/Library/ColorSync/Profiles/Displays/Color LCD-37D8832A-2D66-02CA-B9F7-8F30A301B230.icc"
fullscreen=yes
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes
scale=ewa_lanczos
dscale=mitchell
cscale=ewa_lanczos
deband=yes
deband-iterations=4
deband-threshold=32
deband-range=16
deband-grain=16
dither-depth=no
```
Here is the log when icc-profile is set: [output.txt](https://github.com/mpv-player/mpv/files/14084090/output.txt)
Here is the log when Icc-profile is not set: [output1.txt](https://github.com/mpv-player/mpv/files/14084091/output1.txt)

**Comment by FreeTheTech101** [comment]
In a nutshell, ICC profiles should help render colours more accurately on your display. Just out of curiosity, is your source HDR? ICC profiles should be behind a conditional profile to ensure they aren't applied to HDR video, as they're not compatible.

**Comment by FriedTofu527** [comment]
Thanks for the response. Yes, my source is HDR. I will make sure to remove the icc-profile setting when playing HDR video in the future. Also, why are icc profiles not compatible with HDR? Are there other settings I want to configure when playing HDR video like target-colorspace-hint, target-trc, or tone-mapping?

**Comment by FreeTheTech101** [comment]
Most (if not all) vendor provided ICC profiles are not designed for use with HDR. Even in SDR modes, providing a ICC profile to MPV can cause subtitles to [not render correctly](https://github.com/mpv-player/mpv/issues/12610), so depending on your usecase, it might be better to not provide one at all.

Regardless of the content being played, having `target-colorspace-hint=yes` in your config should be safe. For HDR videos specifically, you may want to specify `target-trc`, `target-peak`, `target-contrast`, `target-prim`, and `tone-mapping` depending on your display and the content you are watching.
