### ISSUE TITLE
when using rotate video and hw acceleration, the colors are wrong.

### ISSUE THREAD

**Issue by grandpa1946** [mpv-player/mpv#13377]
### Important Information

Provide following Information:
- mpv version v0.37.0-229-gc6ccabe5
- Windows Version 23H2 22631.2861
- Source of the mpv binary https://github.com/shinchiro/mpv-winbuild-cmake
- If known which version of mpv introduced the problem 
- GPU model, driver and version nvidia geforce rtx 3070, 31.0.15.4665
- Possible screenshot or video of visual glitches

https://github.com/mpv-player/mpv/assets/115040432/6278450e-a4cd-48a2-ae23-b6fec9bc592a

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.
open a video file (only tested with mp4) and use --video-rotate=x and use hw acceleration
### Expected behavior
video plays with hw acceleration without graphical (color) issues
### Actual behavior
the video is changed in color when using hw acceleration 
### Log file

Make a log file made with -v -v or --log-file=output.txt, attach it to
the issue, and replace this text with a link to it.
[output.txt](https://github.com/mpv-player/mpv/files/14101072/output.txt)

Without the log file, this issue will be closed for ignoring the issue template.

In the case of a crash, please provide a backtrace.

### Sample files
https://0x0.st/HDa2.mp4
Sample files needed to reproduce this issue can be attached to the issue
(preferred), or be uploaded to https://0x0.st/ or similar sites.
(Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by kasper93** [comment]
> mpv version v0.37.0-229-gc6ccabe5

Update, the issue has been fixed https://github.com/mpv-player/mpv/commit/e9076896cda821b74eab08d2128790c0d03ea906

**Comment by grandpa1946** [comment]
> > mpv version v0.37.0-229-gc6ccabe5
> 
> Update, the issue has been fixed [e907689](https://github.com/mpv-player/mpv/commit/e9076896cda821b74eab08d2128790c0d03ea906)

thanks!

**Comment by kasper93** [comment]
Interesting it is not recent regression it is something much older.
