### ISSUE TITLE
[vo/gpu/wayland] Unable to load cursor theme! with latest 46alpha adwaita theme in GNOME

### ISSUE THREAD

**Issue by darkblaze69** [mpv-player/mpv#13376]
### Important Information

Provide following Information:
- mpv-full-git 0.37.0.r230.gd90a5ff17a-1
- adwaita-cursors 46.alpha+r11+geaf827dc6-1
- adwaita-icon-theme 46.alpha+r11+geaf827dc6-1
- Linux Distribution and Version: Arch Linux, GNOME
- Source of the mpv binary: AUR

### Reproduction steps
* Run mpv
* The cursor is missing
The log says:
`[vo/gpu/wayland] Unable to load cursor theme!
`

[mpv.log](https://github.com/mpv-player/mpv/files/14088698/mpv.log)

**Comment by Dudemanguy** [comment]
We seem to have some pretty subpar logging here, but what's happening is that either `wl_cursor_theme_load` is unable to load a theme or `wl_cursor_theme_get_cursor` is unable to get the cursor. You can try explicitly setting the `XCURSOR_THEME` environment variable and seeing if anything changes.

**Comment by darkblaze69** [comment]
Tried with XCURSOR_THEME=adwaita, doesn't help.

For the context, some change to cursors happened which revealed brokenness in at least stable Firefox, Chromium and now mpv. Firefox [fixed](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/271) the issue in 123 developer branch, Chromium probably yet to [fix](https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/275)

So maybe needs some up-to-date changes.

**Comment by Dudemanguy** [comment]
Oh I think we might just be using a legacy name. Does this work?

```
diff --git a/video/out/wayland_common.c b/video/out/wayland_common.c
index 2afdd2aa5f..cf1c3787ed 100644
--- a/video/out/wayland_common.c
+++ b/video/out/wayland_common.c
@@ -1893,7 +1893,7 @@ static int spawn_cursor(struct vo_wayland_state *wl)
         return 1;
     }
 
-    wl->default_cursor = wl_cursor_theme_get_cursor(wl->cursor_theme, "left_ptr");
+    wl->default_cursor = wl_cursor_theme_get_cursor(wl->cursor_theme, "default");
     if (!wl->default_cursor) {
         MP_ERR(wl, "Unable to load cursor theme!\n");
         return 1;
```

**Comment by darkblaze69** [comment]
yes, this fixes the issue.
