### ISSUE TITLE
PNG screenshots taking noticeably longer than JPG screenshots

### ISSUE THREAD

**Issue by tranquillity-codes** [mpv-player/mpv#13386]
### Important Information

```
mpv v0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Jan 19 2024 09:09:45
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```
Arch Linux x86_64
`extra/mpv`
##### Window Manager and version
Not applicable, not using Xorg.
##### GPU model, driver and version
- `1002:744c:1458:240e` / https://linux-hardware.org/?id=pci:1002-744c-1458-240e / Radeon 7900 XTX
amdgpu / v6.6.0 / firmware 2023-09-18 / mesa 23.3.4-2
- `8086:a780:1462:7d25` / https://linux-hardware.org/?id=pci:8086-a780-1462-7d25 / UHD Graphics 770 Gen12
i915 / v6.6.0 / firmware 2023-09-18 / mesa 23.3.4-2

### Reproduction steps

Set `screenshot-format` to `png`, notice that the writing of the file takes several orders of magnitude (a few seconds) more than JPG (milliseconds)

### Expected behavior

PNG taking the same amount of time as JPEG

### Actual behavior

PNG taking a few seconds

### Log file
```
[vo/gpu/wayland] Received a new DND offer. Releasing the previous offer.
[cplayer] Run command: screenshot, flags=73, args=[flags="subtitles", legacy="unused"]
[global] user path: 'shot-[Judas] Steins;Gate - S01E01.mkv[00:00:09.927]-0004.png' -> 'shot-[Judas] Steins;Gate - S01E01.mkv[00:00:09.927]-0004.png'
[global] user path: '~/Pictures' -> '/home/ity/Pictures'
[cplayer] Starting screenshot: '/home/ity/Pictures/shot-[Judas] Steins;Gate - S01E01.mkv[00:00:09.927]-0004.png'
[screenshot] input: 1920x1080 [0:0] rgba64 rgb/bt.709/srgb/full/display CL=mpeg1/jpeg
[screenshot] will convert image to rgba64be
[screenshot] using 16 threads for scaling
[screenshot] Using zimg.
[screenshot] mapped color params:
[screenshot]   trc = iec61966-2-1
[screenshot]   primaries = bt709
[screenshot]   range = pc
[screenshot]   colorspace = gbr
[screenshot]   chroma_location = center
[cplayer] Run command: script-binding, flags=73, args=[name="osc/__keybinding4"]
[cplayer] Screenshot: '/home/ity/Pictures/shot-[Judas] Steins;Gate - S01E01.mkv[00:00:09.927]-0004.png'
[vo/gpu] Resizing texture: 1920x1395
```

If someone could share a few pointers as to how I should approach debugging this (I am unfamiliar with mpv's codebase & performance issues are always hard to debug), I will gladly attempt to fix it myself & send a PR ^^

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#options-screenshot-png-compression

**Comment by tranquillity-codes** [comment]
Hi, what about that option? Disabling compression does not fix the PNG encoder, it just works around the issue at the cost of disk space :/

**Comment by sfan5** [comment]
> PNG taking the same amount of time as JPEG

This expectation is wrong, but I can explain to you what happened (despite not having a log file available<i>¹</i>):

Your source video is 10-bit and when you take a screenshot mpv tries to preserve all that color depth in the screenshot.
With PNG there's a simple way to do that, it supports RGB with 16 bits per component. This however bloats up the file size and the encoding process considerably.
When you switch to JPEG, mpv sees that there's no way to fit more than 8 bits into the format and converts the frame appropriately before writing. That's always fast.
In other works, the run times you were comparing are not for the same task or even an equivalent result.

If you don't care about high bit-depth in your screenshots simply set `screenshot-high-bit-depth=no` and the encoding time for PNG should normalize.

<i>¹</i>: You provided a short excerpt of it. This is usually well-intentioned, but in practice users can almost never judge which parts of the log are relevant for a problem at hand. This results in the developer not having important information and most often an issue being ignored.
