### ISSUE TITLE
make libplacebo optional

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#13383]
So I am trying to compile mpv. In the past this worked nice.

Now I get issues with libplacebo, demanding glad, which causes more problems.

Can libplacebo become optional? Do I really need it for mpv?

I think in the past I did not need it so not sure why I now need it.

(Edit: I solved it via git checkout, but I'd really like to have the option to skip libplacebo completely.)

**Comment by kasper93** [comment]
>Can libplacebo become optional?
No.
>Do I really need it for mpv?
Yes.
>I think in the past I did not need it so not sure why I now need it.
I can tell you in the past libplacebo did not exist and if you look further in the past mpv didn't exist or even mplayer. Things are evolve, change.
>Edit: I solved it via git checkout
Wasn't that hard, was it?
>I'd really like to have the option to skip libplacebo completely.
Why?
