### ISSUE TITLE
osc: Error: Can't convert 'true' to boolean!

### ISSUE THREAD

**Issue by Rabcor** [mpv-player/mpv#13394]
### Important Information

- mpv version: 0.37.0
- EndeavourOS Kernel: 6.6.14-2-lts
- Source of the mpv binary: Official Repository
- ![image](https://github.com/mpv-player/mpv/assets/5684325/0829a226-527c-4a46-9c9b-2a49806c4db7)

### Reproduction steps

* Install [osc.lua](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua) to scripts directory
* Configure osc.lua via osc.conf in script-opts
* Launch mpv

Note: In the screenshot and the samplefile, there are some trailing whitespaces after the boolean values that i thought might be causing the issue, but removing them had no impact on this issue.

### Expected behavior

All the settings understood correctly

### Actual behavior

Any boolean settings fail to be understood by mpv

### Log file

[log.log](https://github.com/mpv-player/mpv/files/14138912/log.log)

### Sample files
[osc.conf](https://github.com/mpv-player/mpv/files/14138917/osc.txt)

**Comment by Rabcor** [comment]
> Use `yes` and `no`.

thanks, that worked, I feel like true and false should be parsed though.

**Comment by Dudemanguy** [comment]
I mean that's just how the conf syntax works in general. It's not a bug.

**Comment by Rabcor** [comment]
> I mean that's just how the conf syntax works in general. It's not a bug.

Sure but there's a consistency issue because the lua scripts that we edit with these use true/false not yes/no. Somewhat creates an expectation that the conf file would be the same.
