### ISSUE TITLE
display issue with png monob 1 bit y channel test image using gpu-next

### ISSUE THREAD

**Issue by mightyhuhn** [mpv-player/mpv#13398]
### Important Information

Provide following Information:
- mpv version mpv-x86_64-v3-20231210-git-443c248
- Windows Version 10.0.19044 Build 19044
- Source of the mpv binary updater.bat
- GPU model, driver and version 4060  551.23
![image](https://github.com/mpv-player/mpv/assets/4950090/d0b2c6df-9490-43db-b5c3-d8cba56902d4)

### Reproduction steps
open:
[bw36x36_nv12.zip](https://github.com/mpv-player/mpv/files/14143057/bw36x36_nv12.zip)

GPU next issue only

### Expected behavior
a black and white image
### Actual behavior
white is teal
### Log file
[output.zip](https://github.com/mpv-player/mpv/files/14143102/output.zip)

### Sample files
see above

only happens with gpu-next will work fine with GPU and the following settings
```
profile=gpu-hq
vo=gpu-next
gpu-api=vulkan
fbo-format=rgb32f
screenshot-high-bit-depth=no
volume=25
loop-file=yes
screenshot-format=png
screenshot-directory="D:\synthlut\screenshoots"
autofit=1920

#scale-antiring=0.8 # luma upscale deringing
#dscale-antiring=0.8 # luma downscale deringing
#cscale-antiring=0.8 # chroma upscale deringing

#scale=jinc
#cscale=ewa_lanczossharp

#target-colorspace-hint


#dither=fruit
#dither=error-diffusion
#dither-depth=8
#error-diffusion=floyd-steinberg
#error-diffusion=sierra-lite
deband=no
#target-trc=gamma2.2
#target-trc=bt1886
#target-contrast=1000
#target-peak=100
log-file=D:\test images\output.txt
```

--no-config was of no help because it instantly closes...

**Comment by llyyr** [comment]
You only need `mpv bw36x36_nv12.avi --no-config --vo=gpu-next --gpu-api=vulkan` to reproduce, works fine with vulkan on vo_gpu.

cc @haasn

**Comment by Traneptora** [comment]
Vulkan doesn't support `rgb32f` as a fbo-format. You need to set `fbo-format=rgba32f`

**Comment by mightyhuhn** [comment]
thanks for the info.
while stating facts is never wrong. does this change anything related to the topic?
i got the same result.
the mpv.conf was only added for preproduction in case i missed something.
