### ISSUE TITLE
Timing was not updated for change from us to ns for vo_vdpau

### ISSUE THREAD

**Issue by DanOscarsson** [mpv-player/mpv#13397]
### Important Information

Provide following Information:
- mpv version : build from git
- Linux Distribution and Version: opensuse Leap 15.4
- Source of the mpv binary: github

### Reproduction steps

Compile mpv, play video using --vo=vdpau

### Expected behavior

Video plays.

### Actual behavior

Video does not play, black screen

###
After testing I found that the problem is that when pts was updated to use ns you forgot to update vdpau which has always used ns.
As vdpau is the only one (or are there more) vo that can present frame at requested pts, pts calculations was all wrong.

Below are my changes that hopefully fixes all us to ns changes.
Both pts and duration in vo_frame are now in ns.
Though duration that was changed recently to double in vo_frame from int could have be changed to int64_t as it is also used as an int in vo.c and parts of ns is not needed. But it works as a double also.

If it looks ok, just add to vo_vdpau.c

```

 diff --git a/video/out/vo_vdpau.c b/video/out/vo_vdpau.c
 index d6b261f057..8fb46d157b 100644
 --- a/video/out/vo_vdpau.c
 +++ b/video/out/vo_vdpau.c
 @@ -80,7 +80,7 @@ struct vdpctx {
  
      struct mp_image                   *current_image;
      int64_t                            current_pts;
 -    int                                current_duration;
 +    int64_t                            current_duration;
  
      int                                output_surface_w, output_surface_h;
      int                                rotation;
 @@ -754,8 +754,8 @@ static void flip_page(struct vo *vo)
      struct vdp_functions *vdp = vc->vdp;
      VdpStatus vdp_st;
  
 -    int64_t pts_us = vc->current_pts;
 -    int duration = vc->current_duration;
 +    int64_t pts_ns = vc->current_pts;
 +    int64_t duration = vc->current_duration;
  
      vc->dropped_frame = true; // changed at end if false
  
 @@ -770,10 +770,8 @@ static void flip_page(struct vo *vo)
      }
      vc->vsync_interval = MPMAX(vc->vsync_interval, 1);
  
 -    if (duration > INT_MAX / 1000)
 +    if (duration > INT_MAX)
          duration = -1;
 -    else
 -        duration *= 1000;
  
      if (vc->vsync_interval == 1)
          duration = -1;  // Make sure drop logic is disabled
 @@ -782,8 +780,8 @@ static void flip_page(struct vo *vo)
      vdp_st = vdp->presentation_queue_get_time(vc->flip_queue, &vdp_time);
      CHECK_VDP_WARNING(vo, "Error when calling vdp_presentation_queue_get_time");
  
 -    int64_t rel_pts_ns = (pts_us * 1000) - mp_time_ns();
 -    if (!pts_us || rel_pts_ns < 0)
 +    int64_t rel_pts_ns = pts_ns - mp_time_ns();
 +    if (!pts_ns || rel_pts_ns < 0)
          rel_pts_ns = 0;
  
      uint64_t now = vdp_time;

```

**Comment by Dudemanguy** [comment]
If that works for you, I can push it in a bit.

**Comment by kasper93** [comment]
Please remove `if (duration > INT_MAX)` because it is no longer correct.

**Comment by DanOscarsson** [comment]
Yes I also though the old test for duration was probably not needed any more.
I assume there are checks elsewhere.
The code will be just simpler without it.

@Dudemanguy please push it. It would be easier for me just now.
