### ISSUE TITLE
Various compilation errors related to `vo_rpi.c`

### ISSUE THREAD

**Issue by alopatindev** [mpv-player/mpv#13402]
Greetings!

Is the `vo_rpi.c` abandoned?

Can we have a CI check for this target (rpi aarch64)?

Any alternative way to do (hardware accelerated) video decoding and playback on kms/framebuffer (without X11/Wayland) on RPi right now?

Thanks!

### Important Information
- mpv version: 0.37.0 from Gentoo portage
- Gentoo GNU/Linux on Raspberry PI 4B, aarch64
- meson version 1.3.1

### Log file
```
../mpv-0.37.0/video/out/vo_rpi.c:87:5: error: unknown type name ‘mp_mutex’
   87 |     mp_mutex display_mutex;
      |     ^~~~~~~~
../mpv-0.37.0/video/out/vo_rpi.c:88:5: error: unknown type name ‘mp_cond’
   88 |     mp_cond display_cond;
      |     ^~~~~~~
../mpv-0.37.0/video/out/vo_rpi.c: In function ‘wait_next_vsync’:
../mpv-0.37.0/video/out/vo_rpi.c:479:5: error: implicit declaration of function ‘mp_mutex_lock’; did you mean ‘vcos_mutex_lock’? [-Werror=implicit-function-declaration]
  479 |     mp_mutex_lock(&p->display_mutex);
      |     ^~~~~~~~~~~~~
      |     vcos_mutex_lock
../mpv-0.37.0/video/out/vo_rpi.c:483:13: error: implicit declaration of function ‘mp_cond_timedwait_until’ [-Werror=implicit-function-declaration]
  483 |         if (mp_cond_timedwait_until(&p->display_cond, &p->display_mutex, end))
      |             ^~~~~~~~~~~~~~~~~~~~~~~
../mpv-0.37.0/video/out/vo_rpi.c:486:5: error: implicit declaration of function ‘mp_mutex_unlock’; did you mean ‘vcos_mutex_unlock’? [-Werror=implicit-function-declaration]
  486 |     mp_mutex_unlock(&p->display_mutex);
      |     ^~~~~~~~~~~~~~~
      |     vcos_mutex_unlock
../mpv-0.37.0/video/out/vo_rpi.c: In function ‘control’:
../mpv-0.37.0/video/out/vo_rpi.c:751:10: error: ‘VOCTRL_REDRAW_FRAME’ undeclared (first use in this function)
  751 |     case VOCTRL_REDRAW_FRAME:
      |          ^~~~~~~~~~~~~~~~~~~
../mpv-0.37.0/video/out/vo_rpi.c:751:10: note: each undeclared identifier is reported only once for each function it appears in
../mpv-0.37.0/video/out/vo_rpi.c: In function ‘tv_callback’:
../mpv-0.37.0/video/out/vo_rpi.c:785:5: error: implicit declaration of function ‘mp_cond_signal’ [-Werror=implicit-function-declaration]
  785 |     mp_cond_signal(&p->display_cond);
      |     ^~~~~~~~~~~~~~
../mpv-0.37.0/video/out/vo_rpi.c: In function ‘uninit’:
../mpv-0.37.0/video/out/vo_rpi.c:868:5: error: implicit declaration of function ‘mp_cond_destroy’; did you mean ‘ra_ctx_destroy’? [-Werror=implicit-function-declaration]
  868 |     mp_cond_destroy(&p->display_cond);
      |     ^~~~~~~~~~~~~~~
      |     ra_ctx_destroy
../mpv-0.37.0/video/out/vo_rpi.c:869:5: error: implicit declaration of function ‘mp_mutex_destroy’; did you mean ‘ra_ctx_destroy’? [-Werror=implicit-function-declaration]
  869 |     mp_mutex_destroy(&p->display_mutex);
      |     ^~~~~~~~~~~~~~~~
      |     ra_ctx_destroy
../mpv-0.37.0/video/out/vo_rpi.c: In function ‘preinit’:
../mpv-0.37.0/video/out/vo_rpi.c:889:5: error: implicit declaration of function ‘mp_mutex_init’; did you mean ‘mp_time_init’? [-Werror=implicit-function-declaration]
  889 |     mp_mutex_init(&p->display_mutex);
      |     ^~~~~~~~~~~~~
      |     mp_time_init
../mpv-0.37.0/video/out/vo_rpi.c:890:5: error: implicit declaration of function ‘mp_cond_init’; did you mean ‘mp_time_init’? [-Werror=implicit-function-declaration]
  890 |     mp_cond_init(&p->display_cond);
      |     ^~~~~~~~~~~~
      |     mp_time_init
```

[Full build.log](https://github.com/mpv-player/mpv/files/14151065/build.log)

**Comment by CounterPillow** [comment]
> Is the `vo_rpi.c` abandoned?

Afaik yes, it hasn't seen any active work or even testing in ages, and was mostly useful for earlier RPi models. It's a prime candidate for removal imho.

> Any alternative way to do (hardware accelerated) video decoding and playback on kms/framebuffer (without X11/Wayland) on RPi right now?

Hardware decoding on RPi4 is probably best done through the v4l2-requests kernel uAPI, there exists an FFmpeg fork which implements the use of this API specifically for RPi, see https://github.com/jc-kynesim/rpi-ffmpeg (might need to pick the correct branch, I don't remember which one it is)

Hardware accelerated rendering on a VT can be done two ways; either the full shading pipeline using the 3D GPU with `--gpu-context=drm`, or if you need more performance, you can skip mpv's rendering logic entirely by using hardware overlays, `--gpu-context=drm --gpu-hwdec-interop=drmprime-overlay`.

**Comment by alopatindev** [comment]
Thanks!

(With standard ffmpeg) both `--gpu-context=drm` and `--gpu-context=drm --gpu-hwdec-interop=drmprime-overlay` produce no video output to HDMI-connected display, I get `[vo/gpu/drm] Could not find any preferred mode. Picking the first mode.`

Am I missing anything?
[config.txt](https://github.com/mpv-player/mpv/files/14151147/config.txt)
[kernel-config.txt](https://github.com/mpv-player/mpv/files/14151148/kernel-config.txt)

**Comment by CounterPillow** [comment]
Try running https://gitlab.freedesktop.org/emersion/drm_info to see what direct rendering manager features your video hardware advertises. You can also manually specify a DRM mode in mpv with  the `--drm-mode` option. (See `--drm-mode=help` for a list.)

I know `gpu-context=drm` works on a mainline kernel on Rockchip hardware, so I'm inclined to attribute your troubles to RPoo vendor kernel nonsense.

**Comment by alopatindev** [comment]
Thanks, `--drm-connector=HDMI-A-2` was missing in my case.

I will close this, feel free to reopen for whatever reason.

**Comment by Dudemanguy** [comment]
>Is the vo_rpi.c abandoned?

Kind of. It was missed in the latest refactors. Since we don't have CI coverage and hardly anyone uses it, not too surprising we all forgot about it. A patch to make it compile again is easy, but I'm kind of inclined to just remove it. Reopening the issue for now.

**Comment by timvis** [comment]
I am interested in the feature, since I use a swarm of Rasperry Pi 1 for video installations, also with CRT-TVs. I feed them individually with changing playlists through the ipc-server feature on the network. Also it's avoided that way, them just ending as electronic waste although they are actually still beeing quite useful.

So what is the latest version where the vo=rpi with hwdec=mmal still works?

**Comment by CounterPillow** [comment]
@timvis It sounds like you are using these devices in commercial installations. If you cannot be bothered to invest in maintaining this feature for your own financial gain, you could at least do the legwork to git bisect when it broke yourself.

**Comment by timvis** [comment]
Thanks. Not that I'm getting rich from something that has no customers, because as I said, it's the art and low budget context (my pride hinders me to call it a hobby). Unfortunately, I lack the knowledge to maintain C code. It's never more than a bit of Python and putting things together. And I would also like to mention that I accept donations of old raspberries in order to make something beautiful with them, which would otherwise just sit in the drawers and end up in the trash at some point. ;)

But back to te topic, maybe this is useful information for somebody else: V34.1 still works for RPI and MMAL. Without using any V3D-KMS driver, it can play h264 720p60 or 1030p30 with some overclocking from the command line on RPI 1. The only thing I really miss is the option to fade in or out.

**Comment by kasper93** [comment]
I did not test this, but looking at OP log, it was broken by `mp_thread` refactoring. 

Last working commit should be https://github.com/mpv-player/mpv/commit/062104d and v0.36.0 in terms of stable version.

Fixing it for newer versions would be easy (few names replace), but the issue is that without proper testing and someone to keep an eye on this code, it will break again and again. That's why it has been removed as obsolete vo. If anyone want to restore it, I guess it would be fine, but at this point it is up to someone to step up and do it.

**Comment by cyph84** [comment]
As someone who tried to keep this alive, I'm sad that it's deleted while I wasn't paying attention.

Is anyone else interested in keeping this alive? Those of us who are using it in commercial installs (@timvis ) might want to come together to keep this working for a few more years.

I've not looked at the state of DRM on RPI2/3 for years, but I do agree that's the direction RPI and all other SBCs should be moving towards.

**Comment by CounterPillow** [comment]
You should first check whether you can use DRM on your RPI2/3 boards before suggesting this VO should be brought back. Using NIH'd vendor kernel interfaces when mainline kernel has proper ones is technical debt that shouldn't be shoehorned back into mpv in my opinion.
