### ISSUE TITLE
Question about switch video on  --lavfi-complex

### ISSUE THREAD

**Issue by artmscn** [mpv-player/mpv#13408]
Greetings.

Does anyone know that if there is any solution to switch videos during  --lavfi-complex
i do a 4 videos side by side like:

mpv.exe c:\video1.avi --external-file=c:\video2.avi --external-file=c:\video3.avi --external-file=c:\video4.avi --lavfi-complex="[vid1] [vid2] hstack [t1];[vid3] [vid4] hstack [t2]; [t1] [t2] vstack [vo]"

it works perfectly for 4 videos to check together
but when i want switch to , for example video 2 during the side to side view... it can not do (i can see correct videos load on F8) and i have tried "_" key, it says no.

or is there any solution i can switch or reload the video2 on the current frame?  (save current frame-> close the lavfi-complex -> load the video2 and goto the current frame.)

Thank you for any help~

**Comment by Traneptora** [comment]
One way to do it would be to bind a key (via input.conf) to change `--lavfi-complex` to something like `[vid2] copy [vo]` or something.
