### ISSUE TITLE
mp.commandv("seek", 0.0, "absolute", "exact") seeks to second keyframe directly after loading

### ISSUE THREAD

**Issue by lvml** [mpv-player/mpv#1341]
Directly after a file has been loaded, a mp.commandv("seek", 0.0, "absolute", "exact") seeks to the second keyframe, not the first, as it usually does.

To reproduce, try using this lua script for playing a video with visible changes in the first few frames:

``` lua
function test_on_loaded()
    mp.set_property("pause","yes")
    mp.commandv("seek", 0.0, "absolute", "exact")
end
mp.register_event("file-loaded", test_on_loaded)


function test_key()
    mp.commandv("seek", 0.0, "absolute", "exact")
end
mp.add_key_binding("x", "test_key", test_key)
```

What happenes is that the (paused) display will not show the first key frame, but the second. If you press "x", then, the same seek that was executed upon the event will actually seek back to the first keyframe.

(I read issue #1332 but that is not obviously the same symptom.)

(The reason why this is annoying is that for my excerpt plugin, pausing automatically at the very first frame is the natural thing to do, and users are certainly as confused as I was if that pause is not really at the begin.)

**Comment by wm4** [comment]
Turns out we have to copy an obscure libavcodec field to make this work. See the commit above. I think it works now.

**Comment by lvml** [comment]
Wonderful, thanks a lot! - I just tried this latest patch and it indeed resolved the issue! I had almost lost hope I could ever get rid of the ugly workaround :-)

(Other software in which this annoying bug bothers me is MLT / kdenlive - now that a way to fix it is known I'll try to figure out how to apply it there, too.)

**Comment by lvml** [comment]
(One really odd observation - not about mpv, but about ffplay/ffmpeg: When playing a sample file like the above linked with ffplay, the first frame is shown. When converting via `ffmpeg -i input -c:a copy -c:v copy output.mp4` the result will also play from its first frame. However, when doing the same with MKV target format: `ffmpeg -i input -c:a copy -c:v copy output.mkv` the file "output.mkv" will - both by mpv and ffplay - not show the first frame. Of course the first frame is still included in output.mkv, when converting back to output.mp4 from the same file, display starts with the first frame again.

So it seems like ffmpeg does something wrong when writing MKV files, resulting in a similar symptom.)

**Comment by wm4** [comment]
Maybe something with the timestamps. I don't know.
