### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by tvraman** [mpv-player/mpv#13419]
From Git@HEAD:
Trying to :
: meson setup build
now triggers (as of yesterday)
#+begin_src 
meson setup build
The Meson build system
Version: 1.2.3
Source dir: /home/raman/sourceforge/mpv
Build dir: /home/raman/sourceforge/mpv/build
Build type: native build
Project name: mpv
Project version: 0.37.0-UNKNOWN
C compiler for the host machine: cc (gcc 13.2.0 "cc (Debian 13.2.0-5) 13.2.0")
C linker for the host machine: cc ld.bfd 2.41
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Run-time dependency libavcodec found: YES 60.3.100
Run-time dependency libavfilter found: YES 9.3.100
Run-time dependency libavformat found: YES 60.3.100
Run-time dependency libavutil found: YES 58.2.100
Run-time dependency libswresample found: YES 4.10.100
Run-time dependency libswscale found: YES 7.1.100
Dependency libplacebo found: NO found 6.338.1 but need: '>=6.338.2'
Found CMake: /usr/bin/cmake (3.27.7)
Run-time dependency libplacebo found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency libplacebo

Executing subproject libplacebo 

libplacebo| Project name: libplacebo
libplacebo| Project version: 6.338.1
libplacebo| C compiler for the host machine: cc (gcc 13.2.0 "cc (Debian 13.2.0-5) 13.2.0")
libplacebo| C linker for the host machine: cc ld.bfd 2.41
libplacebo| C++ compiler for the host machine: c++ (gcc 13.2.0 "c++ (Debian 13.2.0-5) 13.2.0")
libplacebo| C++ linker for the host machine: c++ ld.bfd 2.41
libplacebo| Compiler for C supports arguments -Wincompatible-pointer-types: YES
libplacebo| Compiler for C supports link arguments -Wl,--exclude-libs=ALL: YES
libplacebo| Library m found: YES
libplacebo| Program python3 found: YES (/usr/bin/python3)
libplacebo| Run-time dependency threads found: YES
libplacebo| Header "pthread.h" has symbol "pthread_condattr_setclock" with dependency threads: YES
libplacebo| Run-time dependency libunwind found: NO (tried pkgconfig and cmake)
libplacebo| Library execinfo found: NO
libplacebo| Checking for function "backtrace_symbols" with dependency -lexecinfo: YES
libplacebo| Check usable header "dbghelp.h" : NO
libplacebo| Fetching value of define "__MINGW32__" :
libplacebo| Run-time dependency shaderc found: NO (tried pkgconfig, pkgconfig, pkgconfig and system)
libplacebo| Library glslang-default-resource-limits found: NO
libplacebo| Library SPIRV found: NO
libplacebo| Library SPIRV found: NO
libplacebo| Check usable header "d3d11.h" : NO
libplacebo| Check usable header "d3d11_4.h" : NO
libplacebo| Check usable header "dxgi1_6.h" : NO
libplacebo| Run-time dependency spirv-cross-c-shared found: YES 0.54.0
libplacebo| Library version found: NO
libplacebo| Library dl found: YES
libplacebo| Run-time dependency vulkan found: YES 1.3.268
libplacebo| Header "vulkan/vulkan_core.h" has symbol "VK_VERSION_1_3" : YES
libplacebo| Run-time dependency lcms2 found: YES 2.14
libplacebo| subprojects/libplacebo/src/meson.build:179: WARNING: Building without any GLSL compiler (shaderc, glslang), but with APIs required that require one (vulkan, d3d11). This build is very likely to be very limited in functionality!
libplacebo| Run-time dependency dovi found: NO (tried pkgconfig and cmake)
libplacebo| Run-time dependency libxxhash found: NO (tried pkgconfig and cmake)
libplacebo| Configuring config.h using configuration
libplacebo| Configuring config_internal.h using configuration
libplacebo| Run-time dependency glfw3 found: NO (tried pkgconfig and cmake)
libplacebo| Run-time dependency sdl2 found: YES 2.28.4
libplacebo| Run-time dependency sdl2_image found: NO (tried pkgconfig and cmake)
libplacebo| Dependency libavcodec found: YES 60.3.100 (cached)
libplacebo| Dependency libavformat found: YES 60.3.100 (cached)
libplacebo| Dependency libavutil found: YES 58.2.100 (cached)
libplacebo| Has header "nuklear.h" : YES
libplacebo| Check usable header "EGL/egl.h" : YES
libplacebo| Configuring config_demos.h using configuration
libplacebo| Build targets in project: 24
libplacebo| Subproject libplacebo finished.

Dependency libplacebo found: NO found 6.338.1 but need: '>=6.338.2' (overridden)

meson.build:26:13: ERROR: Dependency 'libplacebo' is required but not found.

A full log can be found at /home/raman/sourceforge/mpv/build/meson-logs/meson-log.txt
20:18:32 mpv $ 
#+end_src

**Comment by Dudemanguy** [comment]
It says it right in your log. You need to update your libplacebo to 6.338.2.

**Comment by tvraman** [comment]
But I cant find that version of libplacebo

1. It's checked out as a subproject
2. It builds cleanly
3. The log does warn about name_prefix being set, something that I dont
   understand.

   
--

**Comment by Dudemanguy** [comment]
Assuming your libplacebo directory is just a git repo, check out the v6.338.2 tag instead.

**Comment by tvraman** [comment]
This is a mpv checkout which created libplacebo as a subproject.

Git commands run there show:

git tag 
v6.338.1
13:51:31 libplacebo $ git remote -v
origin	https://code.videolan.org/videolan/libplacebo.git (fetch)
origin	https://code.videolan.org/videolan/libplacebo.git (push)
13:51:40 libplacebo $ git tag 
v6.338.1
13:51:43 libplacebo $ git branch
* (no branch)
13:51:49 libplacebo $ 
--
