### ISSUE TITLE
who is the developer of mpv player 0.37?

### ISSUE THREAD

**Issue by fastrizwaan** [mpv-player/mpv#13410]
https://github.com/flathub/io.mpv.Mpv/pull/387 flathub required developer name of the app. I could not find the author/developer name in wiki or faqs or in Copyright or License file.

Who is the developer of Mpv 0.37? Thanks.

**Comment by CounterPillow** [comment]
https://github.com/mpv-player/mpv/graphs/contributors

**Comment by kasper93** [comment]
> If flathub does not have a concept of a communally developed and maintained software project, maybe flathub needs to reevaluate its own existence.

```
Values might be for example "The GNOME Foundation" or "The KDE Community".
```

well it is pretty clear that you can just use `The mpv Community` or anything... also consider adding urls like

```
<url type="homepage">https://mpv.io/</url>
```

Note, I'm not a maintainer, but I'm speaking from common sense point of view.

**Comment by fastrizwaan** [comment]
added 

<developer_name>mpv-player contributors</developer_name>

or if you suggest any other name, I'd be glad to update. thanks.

**Comment by Traneptora** [comment]
Do keep in mind that being a "maintainer" has wildly varying degrees of contribution. I am a maintainer of mpv but I contribute very little beyond the stll-image subsystems and the bug tracker.

**Comment by fastrizwaan** [comment]
https://flathub.org/apps/io.mpv.Mpv by "The mpv player contributors"

**Comment by Dudemanguy** [comment]
As mentioned earlier, mpv has no single developer and is driven by whoever contributes. So "mpv player contributors" is fitting I think.
