### ISSUE TITLE
Buggy behavior with KDE Plasma panel

### ISSUE THREAD

**Issue by niels0n** [mpv-player/mpv#13415]
### Important Information

Provide following Information:
- mpv version **1:0.37.0-2**
- Linux Distribution and Version **EndeavourOS** 
- Source of the mpv binary **Pacman**
- Window Manager and version **KWin 5.27.10-2 (Plasma 5.27.10)**
- GPU model, driver and version **NVidia with `nvidia-dkms` 545.29.06-3**

### Reproduction steps

1. Play any video with mpv (with or without config, it makes no difference)
2. Make video full screen
3. Wait a couple seconds

### Expected behavior

The panel of Plasma is not affected in any way by the video.

### Actual behavior

Font of the panel of Plasma gets bigger while mpv is playing fullscreen, and returns the right size after mpv is closed (see the central clock in the screenshots, which show the panel with mpv open, in fullscreen and closed). Also, as you can see in the screenshot, the color picker widget (the first after the clock) somehow change it's opacity.
Often, not always (randomly?), the panel become Translucent after closing mpv, even if it is set to be always Opaque.

### Log file

https://privatebin.devol.it/?18a66cd26326431c#3SPMg2xuVx3hKT9sDJmN855oQqtqGP5wq4G1SmzJNVNF

![mpv_closed](https://github.com/mpv-player/mpv/assets/47432766/e78506b8-2bea-4cce-911b-39cca6832706)

![mpv_open](https://github.com/mpv-player/mpv/assets/47432766/a2fc6565-a809-4a91-9ae8-b3148f6c60ac)

**Comment by Dudemanguy** [comment]
I mean we don't control whatever this panel is doing. Report this to KDE instead?

**Comment by niels0n** [comment]
I know you don't. I just thought that maybe you could have an idea, since it's happening just with mpv but okay, I'll report to KDE then.
Thanks anyway.
