### ISSUE TITLE
Is it possible to set a profile-cond for when screenshots are taken?

### ISSUE THREAD

**Issue by KonoVitoDa** [mpv-player/mpv#13420]
I tried with no success:
```
[screenshot]
profile-cond=screenshot_video
profile-restore=copy-equal
osd-duration=1000

[screenshot-subs]
profile-cond=screenshot
profile-restore=copy-equal
osd-duration=1000
screenshot-template="%f_snapshot_%wM.%wS.%wT 【MPV】【SUBS】 (%{current-tracks/sub/title})"
```

And usng the opportunity to make a related question: is it possible to define an auto profile to be activated only when the seek command is used? I would like to reduce the duration of osd-on-seek, while keeping the default osd-duration (2500ms).

**Comment by zhongfly** [comment]
No,you can't.Profile is only work for property.

**Comment by KonoVitoDa** [comment]
I see :(

**Comment by zhongfly** [comment]
> I see :(

You can change the key bindings for screenshots by setting osd-duration to 100 after pressing the screenshot key, then taking a screenshot, then setting osd-duration back to the original value 
Read `input.conf` and `command` section in mpv manual for details.

**Comment by zhongfly** [comment]
example:
```
S set osd-duration 100;screenshot video;set osd-duration 1000
```
ref:
https://mpv.io/manual/master/#command-interface-set-%3Cname%3E-%3Cvalue%3E
https://mpv.io/manual/master/#command-interface-screenshot-%3Cflags%3E

**Comment by KonoVitoDa** [comment]
> ```
> S set osd-duration 100;screenshot video;set osd-duration 1000
> ```

Wow, I didn't know that was possible. I was using:
```
q	apply-profile screenshot ; screenshot video ; apply-profile screenshot restore
Ctrl+q	apply-profile screenshot-subs ; screenshot ; apply-profile screenshot-subs restore```

So the way you suggested would also work to set the value of screenshot-template?

**Comment by KonoVitoDa** [comment]
Okay, it did work:
```

**Comment by KonoVitoDa** [comment]
There's a property called ```seeking```, but I haven't had the time to test if it's what I was looking for.
