### ISSUE TITLE
Problem loading a `.m2ts` file

### ISSUE THREAD

**Issue by Aymkdn** [mpv-player/mpv#13427]
### Important Information

Provide following Information:
- **mpv version**: v0.37.0-241-gfe0c181b
- **Windows Version**: Windows 11
- **Source of the mpv binary**: https://sourceforge.net/projects/mpv-player-windows/files/
- **If known which version of mpv introduced the problem**: I don't think it's a mpv issue
- **GPU model, driver and version**: not relevant

### Reproduction steps

I have a `.m2ts` file that is served by a top-set box throught `http`. When I read it with `mpv` (on my Windows or from my Android TV), the video is loading (see [www_screencapture_com_2024-2-6_18_00.webm](https://github.com/mpv-player/mpv/assets/946315/de153565-228f-41f3-985c-8011bf0e510e)) with some sort of caching.

See the log: [output_fail.txt](https://github.com/mpv-player/mpv/files/14183812/output_fail.txt).

If I server the same file, but from my own Apache server, the video looks normal and there is no "caching/loading" bar like the other one.

See the log: [output_ok.txt](https://github.com/mpv-player/mpv/files/14183833/output_ok.txt)

### Expected behavior

When I open the `m2ts` file from the top-set box webserver, it should load just like the one from the Apache server.

### Actual behavior

It opens with a caching/loading system that makes it impossible to seek another position.

**I need your help to understand what changed on the top-set box webserver that could produce this behavior. Is it because of a mimetype, or another header? Why the same file but served from 2 different places will be loaded differently? I haven't been able to find what could cause it. Thanks**

### Log file

See above.

**Comment by kasper93** [comment]
Probably in first case there is no [Content-Length](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Length) header sent from server and mpv appends data as it arrives. With Content-Length it knows the files size and can do random access to it.

Not a mpv issue.

**Comment by Aymkdn** [comment]
Thanks, but where do you see the "Content-Length" in the logout file?

In the one that works I see the below:
```
[   1.595][d][ffmpeg] resize stream to 131072 bytes, drop 0 bytes
[   1.595][v][ffmpeg] Mime-type: ''
[   1.595][d][ffmpeg] Stream opened successfully.
```

And in the failed one I saw the below:
```
[   0.038][d][ffmpeg] resize stream to 131072 bytes, drop 0 bytes
[   0.038][v][ffmpeg] Mime-type: 'video/vnd.dlna.mpeg-tts'
[   0.038][d][ffmpeg] Stream opened successfully.
```

**Comment by Aymkdn** [comment]
Also I've just checked, and it seems the "Content-Length" is returned:
```
curl --head "http://192.168.0.254:52424/files/Disque%20Dur/Enregistrements/Test.m2ts"
HTTP/1.1 200 OK
Content-Length: 204054144
Server: fbxupnpd/0.1.0
Date: Wed Feb  7 09:21:44 2024
Accept-Ranges: bytes
Cache-Control: no-cache
Content-Type: video/vnd.dlna.mpeg-tts
```

**Comment by Aymkdn** [comment]
I think it was only an intermittent issue with fbxupnpd. After a reboot, it seems to be working correctly again.
