### ISSUE TITLE
Non-ASCII characters sorted before ASCII when natsorting directory contents

### ISSUE THREAD

**Issue by jakanakaevangeli** [mpv-player/mpv#13435]
### Important Information

- mpv version `0.36.0`
- Linux Distribution and Version: `Arch, Linux version 6.6.2`

### Expected behavior

Playing a directory with files `c` and `č`, it is typically expected that ASCII filename `c` be sorted before non-ASCII filename `č`.

### Actual behavior
```sh
% touch c č
% ls
c  č

% mpv .
[file] This is a directory - adding to playlist.

Playing: ./č
Failed to recognize file format.

Playing: ./c
Failed to recognize file format.

Exiting... (Some errors happened)
```

mpv sorts `č` before `c`. This happens on systems where C type `char` is signed and non-ASCII UTF-8 bytes such as `"ć"[0]` are negative:

```sh
% gdb
(gdb) p "č"[0]
$1 = -60 '\304'
(gdb) p "č"[0] < "c"[0]
$2 = 1
```

### Suggested fix

Convert potential non-ASCII string bytes to `unsigned char` before comparison:

```diff
diff --git a/misc/natural_sort.c b/misc/natural_sort.c
index 3e0bab0e3c..0ba52ef5a1 100644
--- a/misc/natural_sort.c
+++ b/misc/natural_sort.c
@@ -51,9 +51,11 @@ int mp_natural_sort_cmp(const char *name1, const char *name2)
                 name2++;
             }
         } else {
-            if (mp_tolower(name1[0]) < mp_tolower(name2[0]))
+            if ((unsigned char) mp_tolower(name1[0]) <
+                (unsigned char) mp_tolower(name2[0]))
                 return -1;
-            if (mp_tolower(name1[0]) > mp_tolower(name2[0]))
+            if ((unsigned char) mp_tolower(name1[0]) >
+                (unsigned char) mp_tolower(name2[0]))
                 return 1;
             name1++;
             name2++;
```

**Comment by Traneptora** [comment]
`mp_natural_sort_cmp` is by design ASCII-only, so values greater than 127, which are not ASCII characters, aren't going to be handled well. `mp_tolower` and company aren't unicode-aware, so casting these to `unsigned char` just obscures the real problem, which is that the function doesn't handle UTF-8.

**Comment by jakanakaevangeli** [comment]
I believe unsigned comparison handles UTF-8 better, as it sorts strings
by Unicode code points. I think this makes sense even if it isn't
perfectly Unicode aware with collation, locale and all that stuff. See
https://en.wikipedia.org/wiki/UTF-8:

> Sorting order: The chosen values of the leading bytes means that a
> list of UTF-8 strings can be sorted in code point order by sorting the
> corresponding byte sequences.

It also makes behavior more consistent across systems. Currently, the
sort order depends on whetter a system treats `char` as signed or
unsigned. An ARM7 RPI I have seems to treat `char` as unsigned and mpv
there sorts my files differently from mpv on my PC.

I think introduction of unsigned comparison is a small price to pay for
these improvements.
