### ISSUE TITLE
[BUG] Specific image file fails to open

### ISSUE THREAD

**Issue by KonoVitoDa** [mpv-player/mpv#13431]
### Important Information

- mpv v0.37.0-241-gfe0c181b
- Windows 10 Home 22H2 19045.3930
- [Source of the mpv binary](https://sourceforge.net/projects/mpv-player-windows/files/)
- NVIDIA GeForce GTX 1650 4GB VRAM | Driver: 551.23

### Reproduction steps
- Try to open the image file "42974757_p0.jpg" (848kb) by any method: terminal, drag and drop, playlist-next/prev, etc.
- File fails to load, and next file in directory is loaded isntead (I use autoload.lua)
### Expected behavior
- Image loads normally, like any other
### Actual behavior
- Image fails to load; it's the first and only one I ever found this issue
### Log file
[output.txt](https://github.com/mpv-player/mpv/files/14188632/output.txt)
[output no-config no-scripts.txt](https://github.com/mpv-player/mpv/files/14188619/output.no-config.no-scripts.txt)

### Sample files
![42974757_p0](https://github.com/mpv-player/mpv/assets/51209382/1df44916-0c2c-4c9d-9c45-9877dd92daef)
Must be this exact file (with 848kb). When I re-downloaded it from the source (Pixiv) or uploaded it to Imgur, the bug stopped to occur. Maybe the file is simply corrupted, but it opened normally on ImageGlass and Photoshop.

**Comment by guidocella** [comment]
mpv detects it as mpegts, but not ffplay. It works with `--demuxer-lavf-format=jpeg_pipe`.

**Comment by KonoVitoDa** [comment]
@guidocella So to always load this kind of file with no errors I just need to add ```demuxer-lavf-format=jpeg_pipe``` to my mpv.conf? Does it change/affect anything in other file formats?

**Comment by guidocella** [comment]
No that would break playing anything other than jpg.

**Comment by KonoVitoDa** [comment]
> No that would break playing anything other than jpg.

Oh, I see. So to don't face this kind of error again on this kind of file, what ```profile-cond``` I'm supposed to use? Make it apply to all jpg files?

**Comment by guidocella** [comment]
I don't think you're gonna find other files like this one, I never encountered them before. I would just specify it manually for this file.

**Comment by KonoVitoDa** [comment]
But if I want to be safe and apply that setting to all JPG files, would this affect them in any negative way?
A profile like this would be enough to avoid this error in the future? Or is there any way to be yet more specific and just apply the profile for files like that one? What property I could use to identify them?
``` 
[jpeg]
profile-cond=(string.match(path, '.jpg') ~= nil or string.match(path, '.jpeg') ~= nil)
profile-restore=copy-equal
demuxer-lavf-format=jpeg_pipe
```

**Comment by guidocella** [comment]
Conditional profiles are evaluated too late to apply `demuxer-lavf-format`. You would have to use the `on_load` hook.

**Comment by Traneptora** [comment]
If you run `ffmpeg -i input.jpg` it will detect it as jpeg by file extension, but doing `ffmpeg -i - <input.jpg` will autodetect it as mpegts in a false positive.

**Comment by KonoVitoDa** [comment]
Should I report the bug to FFmpeg's devs?

**Comment by Traneptora** [comment]
You could open a ticket on their bug tracker about it.
