### ISSUE TITLE
-geometry not positioning window on a secondary display

### ISSUE THREAD

**Issue by lvml** [mpv-player/mpv#1344]
I finally found the cause for the -geometry issue that haunted me the last days, and this time it does not seem to be the window manager's fault:

When I use "mpv -geometry 1920x1080+1920+0" to position the output window on a secondary display, this does not work along with "-vo opengl".

Everything works fine with "-vo x11", "-vo xv" and "-vo vaapi", while the positioning fails with "-vo opengl" and "-vo opengl-old". 

By tedious tracing through the code with gdb I found the relevant branch where the execution differs:
In gl_common.c:982 the flag VOFLAG_HIDDEN is set:

``` C
    if (ctx->config_window(ctx, vo_flags | VOFLAG_HIDDEN)) {
```

As a consequence, in x11_common.c:1362 the following shortcut is taken:

``` C
    if (flags & VOFLAG_HIDDEN)
        return;
```

Something in the code path after this return seems to be required to set the position of the window in case this window is outside of the "current" window.

I removed the "| VOFLAG_HIDDEN", and this made "-geometry 1920x1080+1920+0" work for me along with "-vo opengl". I have not seen any adverse side effects of this change, yet, but I sure don't know why VOFLAG_HIDDEN was used in the first place and whether something better could be done to make the positioning work in every case.

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
