### ISSUE TITLE
Secondary-sub-pos doesn't work for bitmap based subtitles. (hdmv_pgs_subtitle)

### ISSUE THREAD

**Issue by codecnotsupported** [mpv-player/mpv#13440]
### Important Information

Provide following Information:
- mpv version (master, 343a5fd345a84572ea5693a805119067d5b0fbc8)
- Platform and Version: Kubuntu 23.10
- Source of the mpv binary: (local build)
- If known which version of mpv introduced the problem: Unkown
- GPU model, driver and version: `NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2`, Version: `535.154.05`
### Reproduction steps

Have a video with two bitmap subtitles, in my case `hdmv_pgs_subtitle`. 
`mpv --secondary-sid=2 --secondary-sub-pos=0 --sub-pos=100 [Video]`
Example with provided sample:
`mpv --secondary-sid=2 --secondary-sub-pos=0 --sub-pos=100 https://0x0.st/HkhB.mkv`

### Expected behavior
Subtitles at differing positions.

### Actual behavior
Both Subtitles are offset by sub-pos, Secondary-sub-pos is ignored.

### Log file
No relevant log info.

### Sample files
https://0x0.st/HkhB.mkv

**Comment by Dudemanguy** [comment]
That's my bad. I honestly didn't realize secondary subs worked with image subs. I'll fix it in a bit.
