### ISSUE TITLE
looking for st2094-10 glsl shader

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#13442]
does someone have or know where to find the st2094-10 shader as glsl?
I know that it is already implemented in mpv.

Thank you for any help

**Comment by haasn** [comment]
st2094-10 in mpv is not a shader, it's C code:

https://code.videolan.org/videolan/libplacebo/-/blob/master/src/tone_mapping.c?ref_type=heads#L418

**Comment by geextahslex** [comment]
would it be possible to convert it into a glsl shader?

**Comment by haasn** [comment]
Of course, it's just code. What do you need it for?

**Comment by geextahslex** [comment]
I need it for https://github.com/natural-harmonia-gropius/hdr-toys, his pipeline is build (works best) with shaders. There are shaders for: reinhard, bt2446c, bt2390 etc. but obviously st2094-10 is missing, and it's my favourite one ^^

**Comment by haasn** [comment]
cc @natural-harmonia-gropius

**Comment by natural-harmonia-gropius** [comment]
> would it be possible to convert it into a glsl shader?
> Of course, it's just code.

Thank you.

@geextahslex the shader is here, but no `st2094_pick_knee()`, you need to modify `x2` and `y2` manually.

```glsl
//!PARAM L_hdr
//!TYPE float
//!MINIMUM 0
//!MAXIMUM 10000
1000.0

//!PARAM L_sdr
//!TYPE float
//!MINIMUM 0
//!MAXIMUM 1000
203.0

//!PARAM CONTRAST_sdr
//!TYPE float
//!MINIMUM 0
//!MAXIMUM 1000000
1000.0

//!HOOK OUTPUT
//!BIND HOOKED
//!DESC tone mapping (st 2094-10)

const vec3 RGB_to_Y = vec3(0.2627002120112671, 0.6779980715188708, 0.05930171646986196);

float curve(float x) {
    float x1 = 0.0;
    float x2 = 0.7;
    float x3 = L_hdr / L_sdr;

    float y1 = 1.0 / CONTRAST_sdr;
    float y2 = 0.18;
    float y3 = 1.0;

    float a = 1.0 / (x3 * y3 * (x1 - x2) + x2 * y2 * (x3 - x1) + x1 * y1 * (x2 - x3));

    mat3 cmat = mat3(
        x2 * x3 * (y2 - y3), x1 * x3 * (y3 - y1), x1 * x2 * (y1 - y2),
        x3 * y3 - x2 * y2  , x1 * y1 - x3 * y3  , x2 * y2 - x1 * y1  ,
        x3 - x2            , x1 - x3            , x2 - x1
    );

    vec3 coeffs = vec3(y1, y2, y3) * cmat * a;

    float c1 = coeffs.r;
    float c2 = coeffs.g;
    float c3 = coeffs.b;

    return (c1 + c2 * x) / (1.0 + c3 * x);
}

vec3 tone_mapping_y(vec3 RGB) {
    float y = dot(RGB, RGB_to_Y);
    return RGB * curve(y) / y;
}

vec4 hook() {
    vec4 color = HOOKED_texOff(0);

    color.rgb = tone_mapping_y(color.rgb);

    return color;
}
```

**Comment by geextahslex** [comment]
Thank you, I played around with the settings. But there are oversaturated shadows, like in the screenshots blue tint and there is artifacting on the letterbox.
(both L_sdr=150)
reinhard
![reinhard myk](https://github.com/mpv-player/mpv/assets/139760266/97dddb57-3e0d-4011-af8f-6ad973285374)
2094 (y2=0.40)
![reinhard 2094](https://github.com/mpv-player/mpv/assets/139760266/bad365b3-33c0-4fd0-a524-6e05184ce118)

**Comment by natural-harmonia-gropius** [comment]
Try the updated one [st2094-10](https://github.com/natural-harmonia-gropius/hdr-toys/blob/master/shaders/hdr-toys/tone-mapping/st2094-10.glsl), this set x2 and y2 automatically.

I will check artifacts in dark area later.
![image](https://github.com/mpv-player/mpv/assets/50797982/91087a93-733b-41c1-9d57-bb3ca4d8f1f2)

**Comment by geextahslex** [comment]
I looked into it
Ahsoka improved, I think the red seats should desaturate even more to get closer to reinhard.
There is a green tint in the blacks
![2094 new3](https://github.com/mpv-player/mpv/assets/139760266/43a138c8-817f-40f4-a63d-4450a6c03c1e)

You can see the green tint here, I boosted gamma by 50 to make it more visible
![2094 new3 green](https://github.com/mpv-player/mpv/assets/139760266/121ebd98-dcd9-4f42-bdc1-b52725905b45)

Here the blue tint stayed the same
![2094 new](https://github.com/mpv-player/mpv/assets/139760266/675d808b-5c19-47db-bf20-50705e0d2f08)

**Comment by natural-harmonia-gropius** [comment]
> tint

I committed changes, update it.

If artifacts still not fixed, try change `float x2 = clamp(avg, 1.01 * y1, 0.99 * x3);` to `float x2 = clamp(avg, 0.18, 0.99 * x3);` or whatever higher value for middle number.

https://www.desmos.com/calculator/vjruzaxez0 curve here, you could draw reinhard with bpc your self for comparison.

**Comment by geextahslex** [comment]
Okay so I don't know why, the picture gets much darker now.

sigma0.5 here its the same picture as before but much darker
![sigma 1 0 x fff](https://github.com/mpv-player/mpv/assets/139760266/f9eb12f2-b8df-4ec3-8b63-4293f835eb11)

sigma1.0 fixed the green tint in the shadow in the seat
![sigma 1 0 x ddd](https://github.com/mpv-player/mpv/assets/139760266/c9737d80-7323-442f-9a68-5e5e95a834d4)

sigma1.0 it feels the same as before, but it is darker now
![sigma 1 0 x](https://github.com/mpv-player/mpv/assets/139760266/af441d6c-a9f1-4c7e-98a9-5a933cc2b2f8)

**Comment by natural-harmonia-gropius** [comment]
> but much darker

try to change this value to 0.01
![image](https://github.com/mpv-player/mpv/assets/50797982/36abdf30-41d3-43e0-a897-9ccc38ab41f7)

**Comment by geextahslex** [comment]
Okay it's brighter now, still a notch darker than yesterday but the seats look better now, color like reinhard :)

![mckey](https://github.com/mpv-player/mpv/assets/139760266/da62ed93-0ee7-42be-b223-bada6537b64b)

**Comment by geextahslex** [comment]
0.001 also works fine

**Comment by natural-harmonia-gropius** [comment]
OK, I updated them to 1.0 and 0.001

**Comment by geextahslex** [comment]
okay I feel like it's desaturated too much, the lights are no longer red

rienhard
![reino 00](https://github.com/mpv-player/mpv/assets/139760266/19613063-20d1-49c9-9294-ca10702bc4d5)

2094
![2094 latest](https://github.com/mpv-player/mpv/assets/139760266/5c28ce7c-1f88-429d-a9f8-1c846e565cc2)

**Comment by natural-harmonia-gropius** [comment]
> I think something between them both would work the best

adjust sigma, back to 0.5 or try another value.
