### ISSUE TITLE
JavaScript `mp.add_forced_key_binding` doesn't pass `table.key_text` to `fn` parameter

### ISSUE THREAD

**Issue by gaesa** [mpv-player/mpv#13448]
### Important Information

Provide following Information:
- **mpv version**: v0.37.0
- **Platform and Version**: Arch Linux rolling
- **Source of the mpv binary**: Installed by `pacman`
- **If known which version of mpv introduced the problem**
- **Possible screenshot or video of visual glitches**: [Attach any relevant screenshots or videos demonstrating the issue]

If you're not using git master or the latest release, update.
Releases are listed here: [mpv releases](https://github.com/mpv-player/mpv/releases)

### Reproduction steps

Run the following theoretically equivalent Lua and JavaScript scripts separately.

<details>
<summary>lua script</summary>

```lua
local mp = require("mp")
local utils = require("mp.utils")

local function assert(condition, message)
    local msg
    if message ~= nil then
        msg = message
    else
        msg = "Assertion failed"
    end

    if not condition then
        error(msg)
    else
        return
    end
end

local function map(operation, tbl)
    local newTbl = {}
    for i, v in ipairs(tbl) do
        newTbl[i] = operation(v)
    end
    return newTbl
end

local function dump(...)
    print(unpack(map(utils.to_string, { ... })))
end

local function main()
    mp.add_forced_key_binding("k", "testKeyText", function(table)
        dump(table)
        assert(table.key_text ~= nil and table.key_text ~= "")
    end, { complex = true })
end

mp.register_event("file-loaded", main)
```
</details>

<details>
<summary>js script</summary>

```js
"use strict";

function assert(condition, message) {
    if (!condition) {
        throw new Error(message !== void 0 ? message : "Assertion failed");
    } else {
        return;
    }
}

function main() {
    mp.add_forced_key_binding(
        "k",
        "testKeyText",
        function (table) {
            dump(table);
            assert("key_text" in table && table.key_text !== "");
        },
        { complex: true }
    );
}

mp.register_event("file-loaded", main);
```
</details>

### Expected behavior
Both the Lua and JavaScript scripts should pass the `assert` check.

### Actual behavior
The Lua script behaves as expected, but the assertion fails for the JavaScript script.

### Log file
[output_lua.txt](https://github.com/mpv-player/mpv/files/14222800/output_lua.txt)
[output_js.txt](https://github.com/mpv-player/mpv/files/14222802/output_js.txt)

### Sample files

Sample files needed to reproduce this issue can be attached to the issue
(preferred), or be uploaded to https://0x0.st/ or similar sites.
(Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

### My guess

Upon further investigation, I noticed that the file https://github.com/mpv-player/mpv/blob/master/player/javascript/defaults.js doesn't contain the `key_text` property, which seems to be an oversight. It appears that the previous author or contributor may have overlooked this case. In contrast, the `key_text` property is present in https://github.com/mpv-player/mpv/blob/master/player/lua/defaults.lua. This discrepancy may be the root cause of the assertion failure in the JavaScript script.

**Comment by avih** [comment]
Thanks for the report, should be fixed in master.

**Comment by avih** [comment]
Out of curuisity, what use do you have for this?
