### ISSUE TITLE
UndefinedBehaviorSanitizer: Value outside range (video.c)

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#13459]
### Important Information

```
System Version: macOS 14.3 (23D56)
Model Identifier: MacBookAir10,1
mpv version: git-2024-01-06-d8c2e33
FFmpeg version: git-2023-12-11-5fdbc2a
```

### Reproduction steps

Not reproducible. First time happened ever. Happened while fast-forwarding, I think.

4.16e+09 = `0xf7f49000` which is a negative 32 bit int.

### Expected behavior

N/A

### Actual behavior

May be a cascading error. Unclear what is the root issue. Generally, rewind / forward in streamed videos often causes streaming to halt "forever", ie. user must restart the video to make it stream again. TLS errors are also frequent.

### Log file

```
Using hardware decoding (videotoolbox).
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [libmpv] 1920x1080 videotoolbox[nv12]
[ffmpeg] tls: IO error: Connection reset by peer
[ffmpeg] tls: IO error: Broken pipe
[ffmpeg/video] h264: hardware accelerator failed to decode picture
Error while decoding frame (hardware decoding)!
AV: 00:10:39.040 / 00:49:22.389 (22%) A-V:  0.000 Cache: 265s/152MB
../player/video.c:1260:27: runtime error: 4.16e+09 is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../player/video.c:1260:27 in
[ffmpeg] tls: Unknown error
(...) AV: 00:43:33.760 / 00:49:22.389 (88%) A-V:  0.000 Cache: 0.0s
Exiting... (Quit)
```

### Sample files

N/A

**Comment by llyyr** [comment]
Should be fixed by https://github.com/mpv-player/mpv/commit/dd491c7c61508d72e3694ffa743b64c8dd938eff already

**Comment by forthrin** [comment]
Probably right. Will reopen if happens with new build.
