### ISSUE TITLE
Buffering/stopping for a second or two in local video playback

### ISSUE THREAD

**Issue by random-rando** [mpv-player/mpv#13451]
### Important Information

- mpv 0.36
- Void linux kernel 6.6.11_1
- Shipped by distro
- Xfce/xfwm 4.18
- Intel i3 7020u Intel hd 620 Mesa 23.3.2

### Expected behavior

Video play smoothly

### Actual behavior

Video "stutters/stops" every once in a while for a second and then starts playing happens every 30-40 seconds or so

I think the problem is because of my slow hdd (70mb/sec). Doesn't happen when the videos are on ssd but ssd is small so I can't have all videos there.

Is there any way I can get rid of that? :/

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/14228343/log.txt)

**Comment by kasper93** [comment]
By default for local files only 1s ahead is cached. If you storage is not able to keep up you can try different caching options.

For starters you can try `--profile=big-cache` which sets
```
cache=yes
demuxer-max-bytes=123400KiB
demuxer-readahead-secs=20
```

You can read in manual about those option to better understand how to tune them. But this should be enough to smooth any slowdowns that occurs.

**Comment by sfan5** [comment]
Also note that 0.36 is outdated and unsupported.

**Comment by random-rando** [comment]
sry for no response

adding cache fixed it

> By default for local files only 1s ahead is cached. If you storage is not able to keep up you can try different caching options.
> 
> For starters you can try big-cache example profile form manual which sets
> 
> ```
> cache=yes
> demuxer-max-bytes=123400KiB
> demuxer-readahead-secs=20
> ```
> 
> You can read in manual about those option to better understand how to tune them. But this should be enough to smooth any slowdowns that occurs.
