### ISSUE TITLE
When I use a symlink to run mpv, mpv renames itself to mpv

### ISSUE THREAD

**Issue by boffi** [mpv-player/mpv#13469]
When I use a symlink to run mpv, so that I can `killall <alternate-name>`, `mpv` changes back iits name to `mpv`, disrespecting an user's choice.

### Important Information

Provide following Information:
- mpv version

>   mpv 0.37.0+git20231121.2a57a6ee Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
> libplacebo version: v6.338.2
> FFmpeg version: 6.1.1
> FFmpeg library versions:
>    libavutil       58.29.100
>    libavcodec      60.31.102
>    libavformat     60.16.100
>    libswscale      7.5.100
>    libavfilter     9.12.100
>    libswresample   4.12.100

- Linux Distribution and Version

> $ uname -a
> Linux localhost.localdomain 6.6.6-1-default #1 SMP PREEMPT_DYNAMIC Mon Dec 11 09:46:39 UTC 2023 (a946a9f) x86_64 x86_64 x86_64 GNU/Linux
> $ lsb_release -a
> LSB Version:    n/a
> Distributor ID: openSUSE
> Description:    openSUSE Tumbleweed
> Release:        20240208
> Codename:       n/a

- Source of the mpv binary
- If known which version of mpv introduced the problem
- Window Manager and version
> $ kwin_x11 --version
> kwin 5.27.10
> 
- GPU model, driver and version
- Possible screenshot or video of visual glitches

### To reproduce the bug

```
cd $HOME
ln -s /usr/bin/mpv bin/Play
Play --no-terminal Music/Aldous_Harding/Party/06_Horizon.opus & ps
```
### Actual behavior
```
[1] 16098
  PID TTY          TIME CMD
11599 pts/4    00:00:00 bash
16098 pts/4    00:00:00 mpv
16121 pts/4    00:00:00 ps

```
### Expected behavior
```
[1] 16098
  PID TTY          TIME CMD
11599 pts/4    00:00:00 bash
16098 pts/4    00:00:00 Play
16121 pts/4    00:00:00 ps
```

### Log file

See in attachment
[output.txt](https://github.com/mpv-player/mpv/files/14240690/output.txt)

**Comment by sfan5** [comment]
cb829879af8f2c93fd77c47f12c162d4ce580e30 + 98a27b3cd1

I think expecting and application not to name its threads is unreasonable and you should find a different way to satisfy your use case.
However in this case renaming the main thread "mpv" seems a bit pointless as it will already named that.
