### ISSUE TITLE
4K60 HDR playback stutter on Intel UHD 630 on newer builds (v0.36.0-401-g140d0185 (20230924) onwards)

### ISSUE THREAD

**Issue by AndrewKeYanzhe** [mpv-player/mpv#13460]
### Important Information

Provide following Information:
- mpv version
  - v0.37.0-241-gfe0c181b (20240204)
- Windows Version
  - Windows 10 Pro 21H1
- Source of the mpv binary
  - https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/
- If known which version of mpv introduced the problem
  - v0.36.0-401-g140d0185 (20230924)
- GPU model, driver and version
  - Intel(R) UHD Graphics 630. Driver version 30.0.101.1404
- Possible screenshot or video of visual glitches

### Reproduction steps

Play a 4K60 HDR VP9 video (e.g. [The World in HDR in 4K (ULTRA HD) - YouTube](https://youtu.be/tO01J-M3g0U?si=w2nGFE3SN9Uajc5q) downloaded as mkv)

`--no-config` has some stutter on all versions due to software decode etc. Hence I use this minimal config that has 0 frame drops on older mpv versions.

minimal config:
```
vo=gpu
gpu-context=d3d11
hwdec=d3d11va
hwdec-codecs=all

tone-mapping=mobius 
hdr-compute-peak=no
```

### Expected behavior

0 dropped frames. This occurs for older mpv versions, with the last working build being v0.36.0-303-g181eddc8 (20230917)

### Actual behavior
About half of the frames are dropped. This occurs on v0.36.0-401-g140d0185 (20230924) and v0.37.0-241-gfe0c181b (20240204)
![Screenshot (315)](https://github.com/mpv-player/mpv/assets/22613058/136b18dd-acc4-45b5-83ab-d0a188c509f2)

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/14231925/output.txt)

Could this problem be related to this commit https://github.com/mpv-player/mpv/commit/703f1588803eaa428e09c0e5547b26c0fff476a7 where the default rendering quality profile was changed? Is there a way to use the previous default rendering settings on the latest builds?

Lastly, `vo=gpu-next` has worse performance on Intel UHD 630 than `vo=gpu`, when tested on the older v0.36.0-303-g181eddc8 (20230917) build. `vo=gpu-next` stutters while `vo=gpu` is smooth. Here https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU it says `vo=gpu-next` should be faster, so I'm wondering what is the cause of the performance regression. `vo=gpu-next` is needed for Dolby Vision so I hope the performance could be improved to be on par with `vo=gpu`

**Comment by llyyr** [comment]
> Is there a way to use the previous default rendering settings on the latest builds?

`--profile=fast`

**Comment by AndrewKeYanzhe** [comment]
Thanks, I tried `--profile=fast` on build v0.37.0-241-gfe0c181b (20240204) and there is no more stutter. Does this utilise the same rendering quality as the older builds, (e.g. dithering, scaling)?

I also observe that `target-peak=604` works on 
- v0.36.0-303-g181eddc8 (20230917)
- v0.36.0-401-g140d0185 (20230924) 

But it is not working on
- v0.37.0-241-gfe0c181b (20240204)

Do you know what caused this?
