### ISSUE TITLE
hidpi-window-scale=no does not fully disable hidpi window scaling

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#13466]
### Important Information

Provide following Information:
- mpv version = v0.37.0-278-g415085985d
- Linux Distribution and Version = Arch Linux as of a few weeks ago
- Source of the mpv binary = self-compiled
- Window Manager and version = i3 4.23
- GPU model, driver and version Nvidia 3050

### Reproduction steps
Set --hidpi-window-scale=no (or --no-hidpi-window-scale).
Hit alt+1 or the alternative on other OSes to set the window resolution to what should be the native window resolution.

### Expected behavior
Hitting alt+1 with this option should result in no window size change.
Additionally in the info menu the resolution should be reported as being already at 1x.

### Actual behavior
Observe that the resolution is instead doubled.
Additionally observe that in the OSD info menu that can be brought up with 'i', before hitting alt+1, the resolution is reported as being at 0.5x instead of 1x and after hitting alt+1 it is reported as being at 1x instead of 2x. 

### Log
Log not needed to reproduce as this is trivially reproduced on any Linux system.

**Comment by mlindner** [comment]
This is perhaps related to this recent change: https://github.com/mpv-player/mpv/pull/13230

**Comment by sfan5** [comment]
> Log not needed to reproduce as this is trivially reproduced on any system (also verified on MacOS).

"any system" is not quite helpful as this bug would (likely) either be X11-specific, Wayland-specific or macOS-specific.
If it also happens on macOS that's a separate bug.

**Comment by mlindner** [comment]
```diff
diff --git a/video/out/x11_common.c b/video/out/x11_common.c
index 088e0ac34f..939b2dff88 100644
--- a/video/out/x11_common.c
+++ b/video/out/x11_common.c
@@ -612,12 +612,16 @@ static void vo_x11_get_bounding_monitors(struct vo_x11_state *x11, long b[4])
 // but essentially a user-set prefrence value everywhere else)
 static void vo_x11_get_x11_screen_dpi_scale(struct vo_x11_state *x11)
 {
+    // If hidpi_window_scale has been disabled this function should be a noop
+    if (!x11->opts->hidpi_window_scale)
+        return;
+
     int w_mm = DisplayWidthMM(x11->display, x11->screen);
     int h_mm = DisplayHeightMM(x11->display, x11->screen);
     double dpi_x = x11->ws_width * 25.4 / w_mm;
     double dpi_y = x11->ws_height * 25.4 / h_mm;
     double base_dpi = 96;
-    if (isfinite(dpi_x) && isfinite(dpi_y) && x11->opts->hidpi_window_scale) {
+    if (isfinite(dpi_x) && isfinite(dpi_y)) {
         int s_x = lrint(MPCLAMP(2 * dpi_x / base_dpi, 0, 20));
         int s_y = lrint(MPCLAMP(2 * dpi_y / base_dpi, 0, 20));
         if (s_x == s_y && s_x > 2 && s_x < 20) {
@@ -634,6 +638,10 @@ static void vo_x11_get_x11_screen_dpi_scale(struct vo_x11_state *x11)
 // This is always a preference value so it's also more consistent.
 static bool vo_x11_get_xft_dpi_scale(struct vo_x11_state *x11)
 {
+    // If hidpi_window_scale has been disabled this function should be a noop
+    if (!x11->opts->hidpi_window_scale)
+        return true;
+
     XrmInitialize();
     char *resman = XResourceManagerString(x11->display);
     if (!resman)

```

**Comment by mlindner** [comment]
There is a patch to fix the issue. I would submit it myself but I don't have access to the right computer to submit github pull requests at the moment. I can submit it late this week or next week otherwise.

**Comment by Akemi** [comment]
i can not reproduce this on macOS btw, and i am also pretty sure i took care of exactly that case at some point.
