### ISSUE TITLE
osd digits are too small

### ISSUE THREAD

**Issue by gnojus** [mpv-player/mpv#13462]
### Important Information
mpv 0.36.0
Fedora 39
mpv from fedora repos: mpv-0:0.36.0-3.fc39.x86_64
I think it started after upgrading to fedora 39
KDE wayland, with 200% scaling
![mpv-shot0005](https://github.com/mpv-player/mpv/assets/46261165/f1dd2e02-0c9d-456c-b729-d39f86e5373f)

### Expected behavior
Digits in osd are same size as text.
### Actual behavior
Digits are smaller than other text
### Log file
[log.txt](https://github.com/mpv-player/mpv/files/14233341/log.txt)

**Comment by llyyr** [comment]
Downstream Fedora bug https://bugzilla.redhat.com/show_bug.cgi?id=2262410

**Comment by gnojus** [comment]
and can't even remove the google-noto-fonts because KDE depends on it.
Closing then, thanks for the quick reply.
