### ISSUE TITLE
tint between gpu and gpu-next

### ISSUE THREAD

**Issue by mightyhuhn** [mpv-player/mpv#13468]
so i took a screen with vo=gpu-next and vo=gpu the tone curve is barely touched it's mostly get's a green tint in it... and i wondered why?

so played file side by side and the tint was the there too...

so what did i do wrong how do i get the same tint between gpu and gpu-next in playback?
what are the bare minimum config settings for that?
file tested:
[grayscale.zip](https://github.com/mpv-player/mpv/files/14239164/grayscale.zip)
the 3rd bar from the left is the most obvious one to me.

maybe related

https://github.com/haasn/libplacebo/issues/240

the testing done yet is not good enough for an issue. i only test it with a colorimeter and a histogram yet.

edit:
##LOGS
[output gpu-next.zip](https://github.com/mpv-player/mpv/files/14261665/output.gpu-next.zip)
[output gpu.zip](https://github.com/mpv-player/mpv/files/14261666/output.gpu.zip)

my conf currently looks like this: ```
profile=gpu-hq
vo=gpu
gpu-api=vulkan
#fbo-format=rgba32f
screenshot-high-bit-depth=no
volume=25
loop-file=yes
screenshot-format=png
screenshot-directory="D:\synthlut\screenshoots"
#autofit=100%x100%

#scale-antiring=0.8 # luma upscale deringing
#dscale-antiring=0.8 # luma downscale deringing
#cscale-antiring=0.8 # chroma upscale deringing

#scale=jinc
#cscale=ewa_lanczossharp

#target-colorspace-hint

#dither=fruit
#dither=error-diffusion
#dither-depth=8
#error-diffusion=floyd-steinberg
#error-diffusion=sierra-lite
deband=no
#target-trc=gamma2.2
#target-trc=bt1886
#target-contrast=1000
#target-peak=100
log-file=D:\test images\output.txt
```

**Comment by mightyhuhn** [comment]
ok where is it still ignored?

**Comment by kasper93** [comment]
Could you retest with current build? I cannot reproduce this.

**Comment by mightyhuhn** [comment]
all patches i tested where uniform. to the best of my memory the error was GPU-next green been 2 to high for the 3rd bar compared to GPU. checking the logs deband was on but that shouldn't have the power to do this.
