### ISSUE TITLE
Inconsistent behavior of glsl-shader-opts 

### ISSUE THREAD

**Issue by natural-harmonia-gropius** [mpv-player/mpv#13473]
### Reproduction steps

mpv.conf

[flip.glsl](https://github.com/natural-harmonia-gropius/hdr-toys/blob/master/shaders/hdr-toys/utils/flip.glsl)

```ini
vo=gpu-next
glsl-shader=~~/shaders/hdr-toys/utils/flip.glsl
glsl-shader-opts=flip/horizonal=1
glsl-shader-opts=flip/vertical=1
```

input.conf

```ini
z                   set glsl-shader-opts flip/horizonal=0,flip/vertical=0
x                   set glsl-shader-opts flip/horizonal=1
c                   set glsl-shader-opts flip/vertical=1
```

### Expected behavior

After z, x ,c been pressed, the image is as same as startup.

### Actual behavior

On startup
![image](https://github.com/mpv-player/mpv/assets/50797982/900deca1-9e37-4256-b974-dc60fe71d234)

Press z, x, c
![image](https://github.com/mpv-player/mpv/assets/50797982/97862228-fb5c-49aa-8f9e-fa63e2e7f1ce)

**Comment by kasper93** [comment]
```
glsl-shader-opts=flip/horizonal=1
glsl-shader-opts=flip/vertical=1
```
You have to use `-add` or `-append` for subsequent options. `glsl-shader-opts-add=flip/vertical=1`

```
glsl-shader=~~/shaders/hdr-toys/utils/flip.glsl
```

It is really unfortunate that someone decided it is good idea to make an exception for normal list handling for `glsl-shader` which doesn't need `-add`...

**Comment by natural-harmonia-gropius** [comment]
OK, got it.
