### ISSUE TITLE
`input.conf` cycle values of user script?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#13480]
Trying to find a workaround for this one specific issue (in case you care which issue - https://github.com/mpv-player/mpv/issues/13033)
Short summery: skipping to uncached segment of youtube video will result in one of two outcomes - the first is that only audio will play, the second is that audio and video will not play but mpv will continue to cache the rest of the video as if there's no issue.

I'm trying to find a workaround for this issue by `cycle-values` in `input.conf` for a user script,
I use [mpv_sponsorblock](https://github.com/po5/mpv_sponsorblock) and I would love to have a key that will cycle `fast_forward` from `false` to `true` (This is the line - https://github.com/po5/mpv_sponsorblock/blob/master/sponsorblock.lua#L64C5-L64C17)

It's not a solution because it doesn't solve the issue and I would still need to cycle the values manually and reload the video manually, it's far from a perfect solution.

**Comment by guidocella** [comment]
You change script-opts with `change-list script-opts append sponsorblock-fast_forward=yes` and `change-list script-opts append sponsorblock-fast_forward=no`. To cycle it in one keybinding you can keep track of the last value in a script.

**Comment by guidocella** [comment]
You need to call `read_options(options, "sponsorblock", function () end)` to update options at runtime.

**Comment by guidocella** [comment]
No.
