### ISSUE TITLE
Can we make them the same size as other applications?

### ISSUE THREAD

**Issue by SuperBlackWednesday** [mpv-player/mpv#13489]
Icons are unsightly, can we make them the same size as other applications? This icon is much smaller than other software and looks disharmonious. It would be even better if it were transformed into an Apple style square icon

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/8304

**Comment by Akemi** [comment]
i think everything has been said in the previous issues already. 

imo the best way to start a discussion is to make a viable suggestion or rather a proper concept. a issue where be start berating how bad the current logo is, is imo counterproductive.
