### ISSUE TITLE
Featureless purple output with HEVC, VDPAU and gpu-next

### ISSUE THREAD

**Issue by rankinc** [mpv-player/mpv#13486]
### Important Information

- mpv-0.36.0-3.fc39.x86_64 and mpv-nightly-0 0.37.0^443c248-1
- Fedora 39
- Source from Fedora Project and Terra
- Window Manager: gnome-shell-45.4-1.fc39.x86_64
- AMD RX 6600, Mesa 23.3.5

_Do not_ attempt to use Mesa 24+ with RX 6600 until fix for [#10599](https://gitlab.freedesktop.org/mesa/mesa/-/issues/10599) is merged.
Edit: [#27642](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/27642) has now been merged into Mesa 24.1.0-devel.

Note that RX 6600 supports hardware decoding for HEVC:
```
$ vdpauinfo

Decoder capabilities:

name                        level macbs width height
----------------------------------------------------
HEVC_MAIN                      186 139264  8192  4352
HEVC_MAIN_10                   186 139264  8192  4352
HEVC_MAIN_STILL                --- not supported ---
HEVC_MAIN_12                   --- not supported ---
HEVC_MAIN_444                  --- not supported ---
HEVC_MAIN_444_10               --- not supported ---
HEVC_MAIN_444_12               --- not supported ---
```

### Reproduction steps
Your graphics card must support hardware decoding of HEVC.
```
$ mpv --msg-level=vd=debug --vo=gpu-next --profile=gpu-hq --hwdec=vdpau sample_1280x720.hevc
```

### Expected behavior
Video plays correctly, as it already does with VA-API.

### Actual behavior
Video is featureless and purple, and console fills with errors like:
```
VO: [gpu-next] 1280x720 vdpau[yuv420p]
Mesa: error: GL_INVALID_VALUE in glFramebufferTexture2D(invalid level 0)
[vo/gpu-next/libplacebo] Failed creating framebuffer: error code 36055
[vo/gpu-next/libplacebo] gl_tex_destroy: OpenGL error: GL_INVALID_VALUE
[vo/gpu-next] Failed rendering frame!
```

The problem _appears_ to be that the texture object is immutable, but its "immutable levels" attribute is zero. I have no idea how the "immutable levels" attribute should acquire its value, but a value of "1" would allow `gpu-next` to work :shrug:.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/14302587/output.txt)

### Sample files

[sample_1280x720.hevc](https://filesamples.com/samples/video/hevc/sample_1280x720.hevc)

**Comment by sfan5** [comment]
Note that 0.36.0 is outdated and unsupported. Have you tried 0.37.0?

**Comment by rankinc** [comment]
> Note that 0.36.0 is outdated and unsupported. Have you tried 0.37.0?

I tried, but I couldn't find any RPMs that were compatible Fedora 39. Basically, it would need to install into somewhere like `/opt`, along with all of its dependencies (including `libplacebo`), so that it wouldn't conflict with anything.

**Comment by rankinc** [comment]
I think I've managed to install `mpv` 0.37 locally by using `rpm2cpio` on these RPMs:
- mpv-nightly-libs-0 0.37.0^443c248-1.fc39.x86_64.rpm
- mpv-nightly-0 0.37.0^443c248-1.fc39.x86_64.rpm
- libplacebo-6.338.2-1.fc40.x86_64.rpm

(Not sure I needed `mpv-nightly-libs`). And "yes", I can still reproduce this issue using `mpv` 0.37.0^443c248-1.

**Comment by sfan5** [comment]
Well that's good to know.
I have the same GPU as you so I'd be in a good position to verify this bug, but my ffmpeg and mpv is compiled without vdpau as there's generally no reason to use that with AMD. :shrug:

**Comment by rankinc** [comment]
> but my ffmpeg and mpv is compiled without vdpau as there's generally no reason to use that with AMD. 🤷

Then download the RPMs I mentioned above, convert them into `.cpio` files using `rpm2cpio`, and then install them somewhere else, _exactly_ as I did :roll_eyes:.

However, it would actually be more useful if someone with an NVIDIA card (that supports HEVC decoding in hardware) could test this so that we could eliminate Mesa as the problem.

FYI VLC 3.x no longer supports VA-API, which means that VDPAU is the only "hardware acceleration" game in town for VLC until VLC 4 is released.

**Comment by guidocella** [comment]
The sample plays correctly on NVIDIA with `--no-config --vo=gpu-next --gpu-context=x11 --hwdec=vdpau sample_1280x720.hevc`

**Comment by rankinc** [comment]
Fixed in [Mesa 24.1.0-devel](https://cgit.freedesktop.org/mesa/mesa/commit/?id=e1e84b0721312b5b5b085571d6a5e0504f01d4fb).

**Comment by CounterPillow** [comment]
I'm glad the bug you experienced with an out-of-date mpv that was in a component that is not mpv when using an API you should have no reason to use with your hardware but use anyway because of a different application for some reason is now resolved.

**Comment by rankinc** [comment]
> I'm glad the bug you experienced with an out-of-date mpv

And also reproduced with the current 0.37.0 nightly release.

> that was in a component that is not mpv

The problem _could_ have existed in `libplacebo`, which AIUI is also part of `mpv`.

> when using an API you should have no reason to use with your hardware but use anyway

What does that have to do with anything? There was _never_ any reason for that functionality not to work, regardless of how useful you might have thought it was / wasn't.

> because of a different application for some reason is now resolved.

Not quite sure what you're saying here, but since the issue has now been identified as existing in Mesa it seems only polite not to leave this ticket open.
