### ISSUE TITLE
gpu-next: all proprietary options of `gpu-next` cannot be changed during runtime

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#13481]
### Important Information

Provide following Information:
- mpv version: git master
- Platform and Version: Win11 23H2
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild/releases
- If known which version of mpv introduced the problem
- GPU model, driver and version
- Possible screenshot or video of visual glitches

### Reproduction steps

Related: https://github.com/mpv-player/mpv/issues/12265
Recently, I have re examined that issue and further discovered that not only `libplacebo-opts` option cannot be changed during runtime, but all proprietary options of `gpu-next` cannot be changed during runtime.
Through analyzing the code of vo_gpu_next.c, it was found that the reason for this is that these options are only set during vo initialization, and cannot be detected and applied at runtime for changes in related options.
location code:
https://github.com/mpv-player/mpv/blob/023d02c9504e308ba5a295cd1846f2508b3dd9c2/video/out/vo_gpu_next.c#L2188-L2200

### Expected behavior

all proprietary options of `gpu-next` can be changed during runtime.

### Actual behavior

all proprietary options of `gpu-next` cannot be changed during runtime

### Log file

Associated logs in #12265: https://github.com/mpv-player/mpv/files/12448130/profile-test2.log

**Comment by Dudemanguy** [comment]
Yeah those aren't part of the opts cache so runtime changes are never detect like it was intended to do. #11518 is also a subset of this.

**Comment by llyyr** [comment]
Couldn't we just add these options to gl_video_opts or make a new struct for gpu-next?

**Comment by haasn** [comment]
> Couldn't we just add these options to gl_video_opts or make a new struct for gpu-next?

This seems like the correct way forward. Maybe we can also move this struct definition out of `gpu/video.c`, especially if `gpu-next` is going to replace `gpu`.

**Comment by hooke007** [comment]
@Dudemanguy https://github.com/mpv-player/mpv/commit/85e84f6d9202c8f24def535a6aa78994c0223298 It doesn't fix all the options maybe. i.e. `libplacebo-opts=deinterlace=yes` doesn't work at runtime.
