### ISSUE TITLE
--screenshot-jpeg-source-chroma=yes is ignored when making a jpeg screenshot

### ISSUE THREAD

**Issue by mightyhuhn** [mpv-player/mpv#13503]
### Important Information
mpv v0.37.0-58-gf551a9da
nvidia 551.46
windows 19044

### Reproduction steps
mpv --log-file=output.txt --no-config --vo=gpu --screenshot-jpeg-source-chroma=yes --screenshot-high-bit-depth=no --screenshot-tag-colorspace=yes --screenshot-format=jpg --screenshot-directory="yourscreenshotdir" normal420.source

press s to take a screenshot the screenshot will be 4:4:4

### Expected behavior
a 420 screenshot
### Actual behavior
a 444 screenshot
### Log file
[output.zip](https://github.com/mpv-player/mpv/files/14321957/output.zip)

### Sample files
every 8 bit 420 should do:
[chromatest.zip](https://github.com/mpv-player/mpv/files/14321902/chromatest.zip)

if this should work also with jepg xl it does not they are RGB but that could be the decoder. i see no reason this has to work for it.

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/11860

**Comment by mightyhuhn** [comment]
thanks maybe better that it is borrowed behind: screenshot-sw=yes. i forgot the jpg spec with full range and mpeg1 location and such.
mpeg1 chromaloc making this kinda pointless in it self.
maybe avif is still worth a try to add limited range 420 with mpeg2 or UHD bd in it or with other word a lossless image capture using crf=0.
