### ISSUE TITLE
Update FFmpeg and video codecs

### ISSUE THREAD

**Issue by mayconhvab1** [mpv-player/mpv#13511]
Hello dear developers.

I would like new codecs to be added or updated to mpv player.

Update of AOM AV1 (3.8.1) Codec
Update of vpx (1.14.0) Codec

BtbN's FFmpeg can also be upgraded to audio, video and streaming mpv player.

A big hug.

Let's have a great week.

**Comment by llyyr** [comment]
mpv doesn't have any official binaries, you can just build ffmpeg with newer dependencies yourself.

**Comment by mayconhvab1** [comment]
nfortunately, I don't know how to program, I just give tips to companies about some tools I use on a daily basis.

A tool that can be obtained from the mpv player is the possibility of pasting the ffmpeg and ffplay files to the directory where the mpv player was installed, or to the software's root folder.

I believe that, like ffplay, the mpv player will have a great capacity to play various audio and video formats, read images and play streaming.

If you do not use ffmpeg and ffplay in the root folder of the mpv player software after installation, the mpv player can only play the formats purchased and added to the software.

I believe this will make things easier.
