### ISSUE TITLE
Keyboard button names for input.conf

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#13512]
Hi, I would like to know if there is a source/layout for the Keybord button names to use them in the input.config. For example Page Down is PGDWN but how someone is suppose to know this?
I know about https://github.com/mpv-player/mpv/blob/master/etc/input.conf but some keys are not present there.

keys I would like to know:
Insert/Delete
Home (Pos 1)/End

Thank you for any help

**Comment by llyyr** [comment]
https://mpv.io/manual/master/#key-names

> If in doubt - use --input-test to check how a key/combination is seen by mpv.

**Comment by Akemi** [comment]
read the comments at the top of the file. there is a testing mode for keys, eg you press a key and mpv tells you the name of it.

https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L10

**Comment by geextahslex** [comment]
That worked, thanks
