### ISSUE TITLE
h264: Failed setup for format dxva2_vld: hwaccel initialisation returned error

### ISSUE THREAD

**Issue by Samson7** [mpv-player/mpv#13522]
### Important Information

- mpv version: 0.37.0
- Windows Version: Version 22H2 (OS Build 19045.3803)
- Source of the mpv binary: scoop(stable)
- GPU model, driver and version: AMD Radeon R9 290, driver version 27.20.21034.37

### Reproduction steps

when plays any h264 videos mpv drop an error in the console and there is no HWacceleration

### Expected behavior

mpv plays video with HWacceleration

### Actual behavior

mpv plays video with no HWacceleration

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/14346905/output.txt)

### mpv config file

[mpv.txt](https://github.com/mpv-player/mpv/files/14347117/mpv.txt)

### Detailed description

After changing a few settings in the configuration file(mpv.conf), hw acceleration stopped working. I try to revert changes but still got an error(even with fresh mpv installation i got the same error if i add hwdec=auto/auto-copy or dxva2-copy). The thing is, that at the start hwdec=dxva2-copy works well(i even check in task manager that gpu is decoding video). But after i mess up with mpv.conf, hwaccel stop working. This is very strange, other video players have working hwaccel btw.

**Comment by lovelyMircho** [comment]
I M rady

**Comment by Samson7** [comment]
The problem was in the video file, other h264 files plays as expected with hw acceleration

**Comment by CounterPillow** [comment]
The video file uses the Baseline H.264 profile, and your hardware probably only supports ConstrainedBaseline.
