### ISSUE TITLE
fullscreen does not work on OSX for non-native resolutions (created by SwitchResX)

### ISSUE THREAD

**Issue by ptrs2010** [mpv-player/mpv#1352]
Using SwitchResX I created two non-native resolutions for my 4k Samsung Monitor, since Apple does not support this screen natively on my Macbook Pro mid-2012. They are

3840 x 2160 x 28Hz
3200 x 1800 x 40Hz

Using mpv 0.7.1, pressing f the video disappears and only the desktop is shown. When using --fs to use fullscreen from the start I get the same warning a few times:

[vo/opengl] after rendering: OpenGL error INVALID_FRAMEBUFFER_OPERATION.

On the native resolutions fullscreen works fine (up to 2560 x 1440 x 60Hz)

VLC works fine with the non-native resolutions in full screen (but the horrible optimisations makes 4k video quite jittery).

I am using Yosemite 10.10.1

**Comment by Akemi** [comment]
fixed in https://github.com/mpv-player/mpv/commit/a8347eb9ba9e09177da50592fde7f3ae7261ce59
