### ISSUE TITLE
YCgCo color matrix not decoded correctly

### ISSUE THREAD

**Issue by damian101** [mpv-player/mpv#13521]
### Important Information
- mpv v0.37.0-256
- Arch Linux
- built from git
- Nvidia GeForce GTX 1650, driver version: 545.29.06

### Reproduction steps
Play back correctly tagged video encoded in YCgCo color matrix.

### Expected behavior
Video is correctly decoded, like Firefox, Chrome or VLC media player do.
### Actual behavior
Chroma is very wrong.
### Log file
https://pastebin.com/A29mrTF4

### Sample files
[01817.webm](https://github.com/mpv-player/mpv/assets/37085490/6f9a4a41-56cd-44fd-8147-8a26951f77b1)

**Comment by llyyr** [comment]
The file is broken, you can workaround it by passing `--vf=format=colormatrix=bt.709`

> Video is correctly decoded, like Firefox, Chrome or VLC media player do.

Firefox display it "correctly" because they ignore the colorspace metadata, and I haven't tested in VLC. Chrome renders it correctly, the same as mpv because they don't ignore the colorspace anymore.

Using `hwdec=vaapi` also renders it "correctly" for me because I assume something somewhere causes the colorspace to be ignored(?)

**Comment by Artoriuz** [comment]
Happens on d3d11va as well (6600XT if that matters):

https://github.com/mpv-player/mpv/assets/12078193/b3b096e5-6d4c-4a0f-ad64-8eb4e746fc3b

**Comment by damian101** [comment]
Sorry, aparently

> The file is broken, you can workaround it by passing `--vf=format=colormatrix=bt.709`
> 
> > Video is correctly decoded, like Firefox, Chrome or VLC media player do.
> 
> Firefox display it "correctly" because they ignore the colorspace metadata, and I haven't tested in VLC. Chrome renders it correctly, the same as mpv because they don't ignore the colorspace anymore.
> 
> Using `hwdec=vaapi` also renders it "correctly" for me because I assume something somewhere causes the colorspace to be ignored(?)
> 
> edit: the hwdec thing should be an specific av1 vaapi issue. I can't get it to ignore the colorspace with any other combination of codecs/hw decoding

You are correct. Zimg does not support YCgCo apparently, but throws no error when encoding to it. My bad. Closing this.

**Comment by llyyr** [comment]
hwaccel not rendering the file in ycgco colorspace will be fixed by https://ffmpeg.org//pipermail/ffmpeg-devel/2024-February/321825.html

**Comment by jeeb** [comment]
> hwaccel not rendering the file in ycgco colorspace will be fixed by https://ffmpeg.org//pipermail/ffmpeg-devel/2024-February/321825.html

Which is now in FFmpeg master as FFmpeg/ffmpeg@37936b09ce316c32c456539afeb748d472088135 (and release branches all the way to 4.4).
