### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by yuzhen1024** [mpv-player/mpv#13535]
mpv v0.37.0
Arch 6.7.5

```txt
mpv: error while loading shared libraries: libglslang-default-resource-limits.so.13: cannot open shared object file: No such file or directory
mpv: error while loading shared libraries: libSPIRV.so.13: cannot open shared object file: No such file or directory
```

```sh
# Now I do:
sudo ln -s /usr/lib/libglslang-default-resource-limits.so.14 /usr/lib/libglslang-default-resource-limits.so.13
sudo ln -s /usr/lib/libSPIRV.so.14.0.0 /usr/lib/libSPIRV.so.13
```

**Comment by CounterPillow** [comment]
You need to rebuild mpv if the libraries you built it against get an ABI bump.

Symlinking is not the right solution, it is in fact dangerous, as ABI breaks can lead to memory corruption.

**Comment by Traneptora** [comment]
Rebuild mpv or install it from the official repositories.

**Comment by wzqj** [comment]
I'm having the same error on Arch as well with both the 1:0.37.0-2 official extra repository version and mpv-full-git 0.37.0.r360.g7454edc556-1 from chaotic-aur:
`mpv: error while loading shared libraries: libglslang-default-resource-limits.so.13: cannot open shared object file: No such file or directory`

The official glslang package seems to provide the library here and it was recently updated to version 14.0.0-1 on 13 Feb 2024, but I'm not sure why the chaotic-aur version, which was built on 23 Feb 2024, is also failing with the same error, as it should be pulling the most recent glslang package.
