### ISSUE TITLE
Converting FLAC to mkv with video makes the audio louder.

### ISSUE THREAD

**Issue by Alleop5** [mpv-player/mpv#13544]
### Important Information

Provide following Information:
- mpv version: 0.36.0 (I know this is one version out of date. This is what void ships, from the change log this doesn't seem fixed)
- Platform and Version: Void Linux
- Source of the mpv binary: xbps
- If known which version of mpv introduced the problem: Not sure.
- GPU model, driver and version: Intel TigerLake-LP GT2 [Iris Xe Graphics] (Mesa 23.3.5_3)
- Possible screenshot or video of visual glitches: Not possible.

If you're not using git master or the latest release, update. (Can't do that because libplacebo is too out of date. You guys can try it on the latest version, the reproduction steps are pretty obvious)

### Reproduction steps

wget https://0x0.st/H5lw.flac
rename the audio to "CG5 - Sleep Well.flac"
yt-dlp -f bestvideo https://www.youtube.com/watch?v=28I_6qvI3heDk
Rename the video to "Sleep Well.mp4"
ffmpeg -i "Sleep Well.mp4" -i "CG5 - Sleep Well.flac" -c copy main.mkv
Listen to the original FLAC and the newly made main.mkv file. The mkv should be louder. Making it an mp4 doesn't help.

Note: In VLC both files are way too loud. This may be a "the FLAC is way too quiet" issue. Also without the video the mkv is normal volume. It could be that mpv quiets down FLACs on purpose. Though the YouTube video has about the same volume as the FLAC so maybe libavcodec bug? IDK so I'm reporting it here first. --no-video doesn't help.

### Expected behavior

If there's a video (VP9) with audio (FLAC) it's as loud as the original

### Actual behavior

It's way too loud. Atleast like 2-3x as loud. It's unbearable so the log files are cut off at the beginning of his voice because I can't handle that earrape.

### Log files

[good.txt](https://github.com/mpv-player/mpv/files/14392864/good.txt)
[bad.txt](https://github.com/mpv-player/mpv/files/14392866/bad.txt)
Forgot to use no-config in these log files. Doesn't change anything though.

### Sample files

Sample FLAC is at https://0x0.st/H5lw.flac
The video is at https://www.youtube.com/watch?v=28I_6qvI3Dk

**Comment by Dudemanguy** [comment]
It's the same volume for me (last commit on master) although I have no idea why it would have ever been different in the first place.

**Comment by Alleop5** [comment]
Weird. I'll try compiling my own libraries.

**Comment by Alleop5** [comment]
Compiled mpv myself. Libplacebo too. FFmpeg too. Still too loud. Really weird. Can't think of anything else in your setup.
[flac.txt](https://github.com/mpv-player/mpv/files/14394240/flac.txt)
[loud.txt](https://github.com/mpv-player/mpv/files/14394241/loud.txt)

**Comment by Dudemanguy** [comment]
No clue what could be going on then. Maybe someone else can reproduce. I'm also using pipewire.

**Comment by Alleop5** [comment]
Update: It happens with every audio codec with a VP9 stream. Just convert it to any other codec and it works fine.

**Comment by llyyr** [comment]
What if you do `mpv [video] --audio-file=[audio]`?

**Comment by Alleop5** [comment]
1. mpv with audio-file does nothing to the audio. Same loudness.
2. ffplay makes both loud like vlc.
3. Related to the "Compiled mpv myself" message. I did need to update ffmpeg to latest git for that. So in my latest log file is one with an up to date build.

BTW the "loud" one is basically as loud as the YouTube version (so it's probably normal and the audio only files are quiet).
Note: Going to sleep. Wont see the next message until about 10 AM UTC.

**Comment by Dudemanguy** [comment]
The audio only file is stupidly loud for me. I dunno are you positive you don't have some kind of systemwide sound setting that only affects audio files?

**Comment by Alleop5** [comment]
I just use Void Linux with default pipewire. I don't even know how you would go about doing that. Also are both (so the one with only audio and the one with the VP9 stream) files as loud as eachother? Else you might have the literal opposite of me.

**Comment by Dudemanguy** [comment]
OK so now that you mention it, the flac file you linked is *significantly* louder than downloading the VP9 normally and playing that. I don't know how you extracted the flac exactly but for example this: `ffmpeg -i Sleep\ Well.webm -vn -acodec flac out.flac`: works just fine with me and has normal loudness.

**Comment by Alleop5** [comment]
For me they are the same volume. Also you're missing some knowledge about codecs so I won't go over the rest of your message to keep this message short.

You can probably close this as can't repro if this doesn't work:

yt-dlp -f bestaudio -x [insert youtube link here]
yt-dlp -f bestvideo+bestaudio [insert youtube link here]
For me again the one with the video is louder.

**Comment by Dudemanguy** [comment]
Not sure what you're trying to insinuate, but indeed the downloaded opus is the same volume as the downloaded VP9 + opus. The issue was originally about FLAC, but I if you say to close this, I will.
