### ISSUE TITLE
False HDR detection on some SDR files with `--no-config -vo=gpu-next`

### ISSUE THREAD

**Issue by Carl-Robert** [mpv-player/mpv#13552]
### Important Information

Provide following Information:
- mpv version: mpv v0.37.0-337-gbd5b80ba (also on many earlier versions for few months at least)
- Windows Version: Windows 11
- Source of the mpv binary: scoop
- GPU model, driver and version: Nvidia 1660ti 551.52 (also on previous ones at least few months back)
- Possible screenshot or video of visual glitches: see sample file

### Reproduction steps

Play the sample file with `--no-config -vo=gpu-next` (issue is the same with d3d11 and vulkan `--gpu-api`). Using `-vo=gpu` doesn't result in false HDR detection.

### Expected behavior

The SDR file will be played back normally without triggering a false HDR detection.

### Actual behavior

There are frequent bright flashes due to brief HDR tone-mapping.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/14394420/log.txt)

### Sample files

http://0x0.st/H5nn.mkv

This issue is so far specific to YLE Areena broadcasts (a Finnish tax-funded television station). It might be more widespread, but these are the videos I've come across.

**Comment by kasper93** [comment]
The file has mastering display colour volume SEI and it is interpreted as HDR when it pops up for IDR frame.

But recent st2086 specifies that:
> Values outside the specified ranges of luminance and chromaticity values are not reserved by SMPTE, and can be used for purposes outside the scope of this standard.

And ITU H.264 follows that, by specifying, range limit for each of values:
> When display_primaries_x[ c ] is not in the range of 5 to 37 000, inclusive, the normalized x chromaticity coordinate of the colour primary component c of the mastering display is unknown or unspecified or specified by other means not specified in this Specification

and so on. But sanitization of those values is not implemented in FFmpeg, so we use them as if they were valid. But they are clearly not valid and while they probably mean something, we don't know how to read them apparently...

I will send a patch to ignore values out of range, so we don't fail of files like the one from this issue.

**Comment by kasper93** [comment]
Will be fixed by https://github.com/FFmpeg/FFmpeg/commit/1c45104f74e59beb25ce7451c98527f7a3c518f6
