### ISSUE TITLE
Don't exit after playback finished

### ISSUE THREAD

**Issue by mfat** [mpv-player/mpv#13554]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt,
attach it to the issue, and replace this text with a link to it.

**Comment by Dudemanguy** [comment]
`--keep-open`
