### ISSUE TITLE
Quickest / most efficient way to get encoded video + audio output from mpv, piped into ffmpeg.

### ISSUE THREAD

**Issue by twilson90** [mpv-player/mpv#13567]
I'm using mpv as a sort of dynamic playlist that can be modified via socket commands while encoding.
I currently have it set up to encode into h264 + aac in mkv container, which gets piped into ffmpeg, which muxes it into flv and sends it to an rtmp server.

I now have a slightly different setup as I'm serving the video on my own media server as an HLS playlist. This means that I take the MPV output and have to transcode it again into 360p, 480p and 720p.
So now I want to try and give most of the heavy work to FFMPEG.
Whatever MPV outputs I want it to be fast and easy to encode, so it is fast and easy to decode with FFMPEG.
I've tried outputting RAW video and pcm audio (nut/mkv container) but tests showed it was about 3 times slower than just using h264 and aac with the veryfast preset.
Are there any other encoding formats that will perform better for my purposes? It doesn't have to be lossless but if so that's a bonus.
Also keep in mind this is all done on a headless server.

**Comment by twilson90** [comment]
> in my experience the problem with pipes is it's limitation regarding maximum read/write buffer size, at least the stdin/out pipe is limited to 64kb per i/o (at least on windows) which makes handling raw video data very slow because of the locking overhead. You can try if UDP sockets are faster in these regards, i didnt really try myself. If you don't have hardware builtin for the h264 encode, you need to come down with data size easy on the CPU. E.g. make sure you pipe not more than the highest resolution and framerate e.g. 720p25, also make sure you pipe only the needed pixel format and not more e.g. yuv420. After all of that you can try reducing data size further by applying some encoding like huffyuv. If huff doesnt work you can always go for something that is still easy on the cpu but compresses even more like mpeg2 100mbit or more iframe only (as known from ndi speedhq).
> 
> Might i ask how you managed to get it play in realtime and at the same time encode the output? Because so far i only made it encode at full speed (at least using the official builds)

I did some hackery with 'untimed' variable in the source to get it working how I wanted it.
https://github.com/mpv-player/mpv/blob/665a47209869d7a0c4ea860b28910fcd6ca874c8/video/out/vo_lavc.c
I added a new mpv argument '--orealtime' which essentially toggles the untimed variable in vo_lavc.c

**Comment by twilson90** [comment]
So if I understand correctly, there is a builtin limitation for piping lots and lots of data on Windows?
I would assume a UDP sockets would have the same limitation.
What about Linux?

**Comment by emcodem** [comment]
> I added a new mpv argument '--orealtime' which toggles the untimed variable in vo_lavc.c https://github.com/mpv-player/mpv/blob/665a47209869d7a0c4ea860b28910fcd6ca874c8/video/out/vo_lavc.c

Funny enough i came to the same solution but i was not sure if the lavc output should  actually react to the existing commandline switch "--untimed=no"  https://github.com/mpv-player/mpv/issues/13631#issuecomment-1979893637


> So if I understand correctly, there is a builtin limitation for piping lots and lots of data on Windows? I would assume a UDP sockets would have the same limitation. What about Linux?

Hard to tell because i can only guess here whats the bottleneck, measurement in that area is nearly impossible.
Here some benchmarks that i just ran for you, i first test uncomressed yuv420, then libx264 ultrafast, then mpeg2:

```

ffmpeg -t 7200 -f lavfi -i color=c=black:s=1920x1080 -c:v rawvideo -f rawvideo - | ffmpeg -f rawvideo -s 1920x1080 -i - -f null -
old hp workstation z820: 11,4x realtime 
gaming PC recent hardware (win11): 	31,5x realtime
gaming PC recent hardware (mint linux): 30x realtime

ffmpeg -t 7200 -f lavfi -i color=c=black:s=1920x1080 -c:v libx264 -preset ultrafast -f rawvideo - | ffmpeg -i - -f null -
old hp workstation z820: 17x realtime
gaming PC recent hardware (win11): 	66x realtime
gaming PC recent hardware (mint linux): 60x realtime

ffmpeg -t 7200 -f lavfi -i color=c=black:s=1920x1080 -c:v mpeg2video -g 1 -b:v 200M -f rawvideo - | ffmpeg -i - -f null -
old hp workstation z820: 21x realtime
gaming PC recent hardware (win11): 	90x realtime
gaming PC recent hardware (mint linux): 60x realtime
```

Note that i was just booting into live mint linux and i did not install drivers which can potentially explain why i was stuck to 60 realtime max.

**Comment by Arcitec** [comment]
AMD 7800X3D CPU on Fedora Linux 40:

```
ffmpeg -t 7200 -f lavfi -i color=c=black:s=1920x1080 -c:v rawvideo -f rawvideo - | ffmpeg -f rawvideo -s 1920x1080 -i - -f null -
71.5x realtime

ffmpeg -t 7200 -f lavfi -i color=c=black:s=1920x1080 -c:v libx264 -preset ultrafast -f rawvideo - | ffmpeg -i - -f null -
76.2x realtime

ffmpeg -t 7200 -f lavfi -i color=c=black:s=1920x1080 -c:v mpeg2video -g 1 -b:v 200M -f rawvideo - | ffmpeg -i - -f null -
68.2x realtime
```

I also tried using named pipes and the speed is the same. That's done via:

```sh
mkfifo /tmp/whatever
ffmpeg <sender settings> - > /tmp/whatever

# Start receiver in another terminal:
ffmpeg -i /tmp/whatever -f null -
```
