### ISSUE TITLE
--get-title error

### ISSUE THREAD

**Issue by deenbee** [mpv-player/mpv#13581]
### Important Information

Provide following Information:
- mpv version 0.37
- Windows Version: 11
- Source of the mpv binary
- If known which version of mpv introduced the problem
- GPU model, driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Log file

Make a log file made with -v -v or --log-file=output.txt, attach it to
the issue, and replace this text with a link to it.

Without the log file, this issue will be closed for ignoring the issue template.

In the case of a crash, please provide a backtrace.

### Sample files

Sample files needed to reproduce this issue can be attached to the issue
(preferred), or be uploaded to https://0x0.st/ or similar sites.
(Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

code:

char command[256];
  sprintf(command, "yt-dlp -q -o - --extract-audio \"%s\" | mpv --no-video - --get-title", urls[sel - 1]);

error:

Error parsing option get-title (option not found)
Setting commandline option --get-title= failed.

ERROR: unable to write data: [Errno 22] Invalid argument
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument

**Comment by CounterPillow** [comment]
Why would `--get-title` be an option, and what would it do?

**Comment by Dudemanguy** [comment]
`--get-title` is not an option.

**Comment by deenbee** [comment]
> `--get-title` is not an option.

I need get a title of the urls , can help me ?

**Comment by llyyr** [comment]
`--get-title` is a yt-dlp option, not a mpv one

**Comment by deenbee** [comment]
> `--get-title` is a yt-dlp option, not a mpv one

sorry for the incovenient
