### ISSUE TITLE
mpv can't properly parse tile HEIF still images

### ISSUE THREAD

**Issue by Andarwinux** [mpv-player/mpv#13585]
### Important Information

Provide following Information:
- mpv version master
- Windows Version 24H2
- Source of the mpv binary shinchiro
- GPU model, driver and version N/A

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

https://github.com/FFmpeg/FFmpeg/commit/41e349c24a726d0c3bac5830eec9f6940ea41c63 added support for tile HEIF still images, but is parsed as multiple hevc streams in mpv.

### Expected behavior
Should be presented as a single image like ffmpeg cli
### Actual behavior
Presented as multiple images
### Log file
[log.txt](https://github.com/mpv-player/mpv/files/14413643/log.txt)
### Sample files
[iClarified-MacBook-Pro-2023-Grid-Green.zip](https://github.com/mpv-player/mpv/files/14413604/iClarified-MacBook-Pro-2023-Grid-Green.zip)

**Comment by llyyr** [comment]
Your sample doesn't work for me with either ffplay or mpv, but samples from FATE work for me on both ffplay and mpv.

**Comment by Traneptora** [comment]
The sample provided doesn't work in either ffplay or upstream ffmpeg.c (e.g. `ffmpeg -i input.heic out.png`) so this is an upstream bug.
