### ISSUE TITLE
Hi! Friends, triggering the Numeric key area Enter key in the lower right corner of the notebook cannot enable full-screen playback. 

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#13593]
### Important Information

Hi! Friends, triggering the Numeric key area Enter key in the lower right corner of the notebook cannot enable full-screen playback. 

Provide following Information:
- mpv version 0.37.xxx
- Windows Version 10 22H2
- Source of the mpv binary 
- If known which version of mpv introduced the problem
- GPU model, driver and version GTX 610
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

Hi! Friends, triggering the Numeric key area Enter key in the lower right corner of the notebook cannot enable full-screen playback. 

### Reproduction steps

Hi! Friends, triggering the Numeric key area Enter key in the lower right corner of the notebook cannot enable full-screen playback. 

### Expected behavior
Hi! Friends, triggering the Numeric key area Enter key in the lower right corner of the notebook cannot enable full-screen playback. 

### Actual behavior
Hi! Friends, triggering the Numeric key area Enter key in the lower right corner of the notebook cannot enable full-screen playback. 

### Sample files

Hi! Friends, triggering the Numeric key area Enter key in the lower right corner of the notebook cannot enable full-screen playback.

**Comment by zhouxinghong** [comment]
Thank you very much for providing a very good MPV 🎉

**Comment by verygoodlee** [comment]
you need to add `KP_ENTER cycle fullscreen` in input.conf

**Comment by zhouxinghong** [comment]
Thank you so much! 🎉
