### ISSUE TITLE
Floatplane

### ISSUE THREAD

**Issue by MrChuw** [mpv-player/mpv#13597]
I would like to be able to pass cookies from yt-dlp using the "--cookies-from-browser chrome" flag. I tried using a yt-dlp config file but mpv simply ignores it. I wanted to know if there is any way for me to pass the flag so I can watch floatplane videos on the mpv

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/14440540/log.txt)

**Comment by christoph-heinrich** [comment]
You can try `ytdl-raw-options-append=cookies-from-browser=chrome`
