### ISSUE TITLE
OSC is slow to refresh in audio-only mode

### ISSUE THREAD

**Issue by gtm87x** [mpv-player/mpv#1360]
When an audio file with no cover attached is played in a dummy window on Mac OsX, the OSC refresh is slow when switching between fullscreen and windowed mode and vice versa.

Terminal output:
mpv --force-window --audio-display=no myfile.mp3 
Playing: myfile.mp3
[stream] Video     --vid=1 [P] '' (mjpeg)
[stream] Audio (+) --aid=1 (mp3)
Creating non-video VO window.
AO: [coreaudio] 44100Hz stereo 2ch s16
A: 00:00:04 / 00:03:15 (2%)

Exiting... (Quit)
CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces.

**Comment by gtm87x** [comment]
Are problems with commit 4e013af on OsX related to this, by any chance?

**Comment by ChrisK2** [comment]
No, those have something to do with mpv not updating the window properly right after start-up on OS X.

**Comment by gtm87x** [comment]
I don't know if this can properly be considered fixed, but commit ff9c597 practically made the issue really hard to notice anymore now.

**Comment by wm4** [comment]
Yes, though the main issue is still that the OSC should either use its own timer, or listen to ``playback-time`` property updates.

**Comment by thebombzen** [comment]
This doesn't appear to be a bug anymore in 2018.
