### ISSUE TITLE
Increasing playback speeds and seeking during high speeds causes high av desynchronisation and gaps in audio

### ISSUE THREAD

**Issue by mesvam** [mpv-player/mpv#13613]
### Important Information

Provide following Information:
- mpv version: mpv v0.37.0-424-gfa0fccc2
- Platform and Version: Windows 11
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild/releases/tag/2024-02-27-fa0fccc
- If known which version of mpv introduced the problem: somewhere between 74b4c3c and fa0fccc, most likely e3af545
- GPU model, driver and version: GTX 1080
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Set the following keybinds in `input.conf`
```
1 set speed 1
2 set speed 2
3 set speed 4
4 set speed 8
5 set speed 16
```
Play a file that has both video and audio. (Behavior does not happen on audio-only files). Use keybinds to increase the speed, then seek backwards and forwards. Repeat increasing the speed until desynchronization warning appears.

Also pay attention to the duration of the gap in the audio, or optionally record the played audio using another software.

### Actual behavior

- "Audio/Video desynchronisation detected!" warning appears upon seeking at 4x speed or higher, even if `--profile=fast` and/or `--hwdec=auto-safe` is added
- There is a large (~200ms) gap in the audio upon seeking (measured using audio recording)
- When speed is changed, the A-V indicator on the command line status immediately increases to a high value (>600ms desync), then slowly decreases over ~1-2s. The desync is noticeable by visual inspection

### Expected behavior

In previous versions
- You could go up to 8x and even 16x without desynchronization
- There is a small (~35ms) gap in the audio upon seeking (measured using audio recording)
- When speed is changed, the A-V indicator on the command line status only changes slightly (<25ms desync) and quickly decreases down to 0

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/14467768/mpv.log)

### Sample files

Issue applies to any file, but can use this test file with a continuous 1000Hz tone (Volume warning! Loud!): https://github.com/mpv-player/mpv/assets/14833020/4186eb16-98e7-4040-b894-e1368fb49431

**Comment by Dudemanguy** [comment]
Two problems here. One, I did not adjust the pts calculation in `audio_start_ao` which should have been done in 7051e94e4bacd00e53e88835d28e9d9082de3bb3. Second, the `MIN_PAST_FRAMES` check is simply too broad and catches when it shouldn't.

**Comment by Dudemanguy** [comment]
Could you try the build [here](https://github.com/mpv-player/mpv/pull/13614#issuecomment-1974405758)?

**Comment by quietvoid** [comment]
I'm still getting a stutter when changing the speed on #13614, and it doesn't happen on 74b4c3c531bd454484ed5d04c9aad0bc531ccd4b.

**Comment by Dudemanguy** [comment]
Just to be clear, when you say stutter do you mean visually or an audio one?

**Comment by quietvoid** [comment]
It's visual only for me.

**Comment by Dudemanguy** [comment]
OK, yeah that makes sense. The cost of not immediately adjusting av sync to avoid skipping frames results in some visual stutter on the speed change. I'll see if maybe I can smooth it out over the next few frames to make it more imperceptible.

**Comment by mesvam** [comment]
Is it possible to just start both the video and audio in sync? I don't understand why av sync is affected by speed or seeking?

**Comment by Dudemanguy** [comment]
>Is it possible to just start both the video and audio in sync?

It would be nice if it was that simple. Audio and video can start from different positions including after a seek. When you change speed, you modify both the video and audio timings so you have to make sure the sync is still correct.

**Comment by mesvam** [comment]
Yea, I figured it had to be more complicated than that.

I tried the build and video lags a bit, but audio is continuous now.

**Comment by mesvam** [comment]
I'll note that `--mc=1` mitigates ~80% of the ill effects of this, just subjectively
