### ISSUE TITLE
OOOOOmg, can one line of command in a lua script clear my hard drive?

### ISSUE THREAD

**Issue by linhaiqd** [mpv-player/mpv#13610]
I am a beginner in MPV and I found a simple copy time lua script to learn the syntax. I saw a line of code in the script `mp.commandv("run", "powershell", "set-clipboard", text)` that can call the powershell command. I tried to change the powershell command in this line of code to a delete file command` mp.commandv("run", "powershell", "remove-item", "F:\\Folder\\SubFolder\\*.*")` .

Then I opened the video file, loaded the script, and after pressing Ctrl+c, all the files in the command parameter folder address were deleted and unrecoverable. It can delete files in the current folder, subfolders or other directories, as long as the file address is known.

This makes me very afraid of scripts. Do I have to check every third-party script to see if there is such malicious code in it? How can I prevent this kind of code from running in malicious scripts?

I haven't found any discussion or solution to the problem here or online. I appreciate you taking the time to answer this.

Read the script carefully, this is the only way I can think of so far. But I think most people just use MPV scripts as tools, and not everyone can understand the scripts. There should be a checking mechanism in MPV to prevent such deletions from running silently. 

Is there any other way?

**Comment by Traneptora** [comment]
Yes, you should always check scripts you download from the internet before you execute them. This is standard practice.

**Comment by kasper93** [comment]
> Do I have to check every third-party script to see if there is such malicious code in it?

Yes. You have to trust the code you run on your PC. Whether in script form or complied binary downloaded from internet. If you shoot yourself in foot, you cannot blame anyone for that. There are ways (sandboxing) to make script/executable execution separated from other processes and with limited access, but it is outside of mpv scope. mpv does not run any external script, it is not a web browser. All you put in your config is your responsibility. And the same way you can write `rm -rf /` in your terminal, putting same command in lua script and executing it with key bind is exactly the same thing just with extra steps.
