### ISSUE TITLE
Hi friends, mpv cannot play the following link

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#13621]
### Important Information
Hi friends, mpv cannot play the following link, but it can be parsed and downloaded in other tools.
https://ss420.techofra.com/stream/PZrGPPRj7VXSb7vB0kzuzCAfQT6mPhDiYWL/hls1080/PZrGPPR222dfdffe36j7VXSb7vB0kzuzCAfQT6mPhDiYWL1080.m3u8

Provide following Information:
- mpv version MPV v0.37.0-455-g8ba6d8f7
- Windows Version 10 21h2 19044
- Source of the mpv binary
- If known which version of mpv introduced the problem
- GPU model, driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

### Log file

Make a log file made with -v -v or --log-file=output.txt, attach it to
the issue, and replace this text with a link to it.

`
PowerShell> mpv https://ss420.techofra.com/stream/8/22/PZrGPPRj7VXSb7vB0kzuzCAfQT6mPhDiYWL/hls1080/PZrGPPRj7VXSb7vB0kzuzCAfQT6mPhDiYWL1080.m3u8
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://ss420.techofra.com/stream/8/22/PZrGPPRj7VXSb7vB0kzuzCAfQT6mPhDiYWL/hls1080/PZrGPPRj7VXSb7vB0kzuzCAfQT6mPhDiYWL1080.m3u8.
[ytdl_hook] ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
[ytdl_hook] youtube-dl failed: unexpected error occurred
Exiting... (Errors when loading file)
PS F:\develop-tool\PowerShell>
`
The above link can be parsed and downloaded successfully in other download tools.
​

**Comment by guidocella** [comment]
`mpv --referrer=https://ss420.techofra.com https://ss420.techofra.com/stream/8/22/PZrGPPRj7VXSb7vB0kzuzCAfQT6mPhDiYWL/hls1080/PZrGPPRj7VXSb7vB0kzuzCAfQT6mPhDiYWL1080.m3u8`

**Comment by zhouxinghong** [comment]
Thank you very much for your help!🎉👍

In addition, I would like to ask you what is the reason why you cannot use mpv https://xxxxx.m3u8 to play? 😜

**Comment by guidocella** [comment]
Erroring without a referrer from the same domain is a naive protection against scraping.

**Comment by zhouxinghong** [comment]
@guidocella Hello, teacher! Is there a more detailed description of this issue? I wanted to get down to learning how it worked. . .
Once again, thank you very much for your attentive help! 👍🎉🤞

**Comment by guidocella** [comment]
https://webscraping.ai/faq/http/how-does-the-http-referer-header-impact-web-scraping

**Comment by zhouxinghong** [comment]
> https://webscraping.ai/faq/http/how-does-the-http-referer-header-impact-web-scraping

@guidocella OK! Teacher, you are really cool🤞😜
