### ISSUE TITLE
cannot play video from https://cdn-bgocihpmovcae3c6b49a0959a83az1b8.streamfastpro.com

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#13627]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behavior of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt,
attach it to the issue, and replace this text with a link to it.

[Question] Hi! Hello friends, the following link cannot be played in mpv. I don’t know why?
`mpv https://cdn-bgocihpmovcae3c6b49a0959a83az1b8.streamfastpro.com/e4fa4b44f24bcd13a410a7700003c99e/3/2/9hJgSwGENvEGdTCddoYdAg/9hJgSwGENvEGdTCddoYdAg.m3u8
`
This link can be successfully downloaded in other download tools. . .

Don't know why it can't be played in mpv. So ask teachers for help! Thank you very much! 🎉😜

logs
```
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg] crypto: Unable to open resource: https://cdn-bgocihpmovcae3c6b49ao959a83az1b8.streamfastpro.com/e4fa4b44f24bcd13a410a7700003c99e/3/2/9hJgSwGENvEGdTCddoYdAg/9hJgSwGENvEGdTCddoYdAg_000.js
[ffmpeg/demuxer] hls: Failed to open segment 0 of playlist 0
[ffmpeg/demuxer] hls: Segment 0 of playlist 0 failed too many times, skipping
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg] crypto: Unable to open resource: https://cdn-bgocihpmovcae3c6b49ao959a83az1b8.streamfastpro.com/e4fa4b44f24bcd13a410a7700003c99e/3/2/9hJgSwGENvEGdTCddoYdAg/9hJgSwGENvEGdTCddoYdAg_001.js
[ffmpeg/demuxer] hls: Failed to open segment 1 of playlist 0
[ffmpeg/demuxer] hls: Segment 1 of playlist 0 failed too many times, skipping
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg] crypto: Unable to open resource: https://cdn-bgocihpmovcae3c6b49ao959a83az1b8.streamfastpro.com/e4fa4b44f24bcd13a410a7700003c99e/3/2/9hJgSwGENvEGdTCddoYdAg/9hJgSwGENvEGdTCddoYdAg_002.js
[ffmpeg/demuxer] hls: Failed to open segment 2 of playlist 0
[ffmpeg/demuxer] hls: Segment 2 of playlist 0 failed too many times, skipping
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg] crypto: Unable to open resource: https://cdn-bgocihpmovcae3c6b49ao959a83az1b8.streamfastpro.com/e4fa4b44f24bcd13a410a7700003c99e/3/2/9hJgSwGENvEGdTCddoYdAg/9hJgSwGENvEGdTCddoYdAg_003.js
[ffmpeg/demuxer] hls: Failed to open segment 3 of playlist 0
[ffmpeg/demuxer] hls: Segment 3 of playlist 0 failed too many times, skipping
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg] crypto: Unable to open resource: https://cdn-bgocihpmovcae3c6b49ao959a83az1b8.streamfastpro.com/e4fa4b44f24bcd13a410a7700003c99e/3/2/9hJgSwGENvEGdTCddoYdAg/9hJgSwGENvEGdTCddoYdAg_004.js
[ffmpeg/demuxer] hls: Failed to open segment 4 of playlist 0
[ffmpeg/demuxer] hls: Segment 4 of playlist 0 failed too many times, skipping
[ffmpeg] https: HTTP error 404 Not Found
[ffmpeg] crypto: Unable to open resource: https://cdn-bgocihpmovcae3c6b49ao959a83az1b8.streamfastpro.com/e4fa4b44f24bcd13a410a7700003c99e/3/2/9hJgSwGENvEGdTCddoYdAg/9hJgSwGENvEGdTCddoYdAg_005.js
```

**Comment by zhouxinghong** [comment]
mpv version MPV v0.37.0-455-g8ba6d8f7
Windows Version 10 21h2 19044

**Comment by zhongfly** [comment]
A short, no-nonsense issue title is recommended,eg: `cannot play video from streamfastpro.com`.

**Comment by zhouxinghong** [comment]
> A short, no-nonsense issue title is recommended,eg: `cannot play video from streamfastpro.com`.

Ok, thank you!

**Comment by mikucat0309** [comment]
You may need to add Referer & User-Agent header to bypass Hotlink protection

**Comment by zhouxinghong** [comment]
> You may need to add Referer & User-Agent header to bypass hotlink protection

Added Referer to link but doesn't work

**Comment by mikucat0309** [comment]
> Added Referer to link but doesn't work

What is the command you tried?
Try to searching and learning, not just ask for answers.
This will help you understanding more details about Referer: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer

**Comment by zhouxinghong** [comment]
> This will help you understanding more details about Referer

mpv --referrer=https://cdn-bgocihpmovcae3c6b49a0959a83az1b8.streamfastpro.com https://cdn-bgocihpmovcae3c6b49a0959a83az1b8.streamfastpro.com/e4fa4b44f24bcd13a410a7700003c99e/3/2/9hJgSwGENvEGdTCddoYdAg/9hJgSwGENvEGdTCddoYdAg.m3u8

**Comment by zhouxinghong** [comment]
```
PowerShell> mpv --referrer=https://ss271.themoneet.com https://ss271.themoneet.com/stream/0/AC/SvbJ635JA91G08aIrOE1UItEEIwazaKOjNl/hls1080/SvbJ635JA91G08aIrOE1UItEEIwazaKOjNl1080.m3u8
[ffmpeg] https: HTTP error 404 Not Found
Failed to open https://ss271.themoneet.com/stream/0/AC/SvbJ635JA91G08aIrOE1UItEEIwazaKOjNl/hls1080/SvbJ635JA91G08aIrOE1UItEEIwazaKOjNl1080.m3u8.
[ytdl_hook] ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
[ytdl_hook] youtube-dl failed: unexpected error occurred
Exiting... (Errors when loading file)
```

**Comment by huidaoweilai2024** [comment]
[--referer https://](https://streamfastpro.com)
