### ISSUE TITLE
`--untimed` performance regression since commit e3af545

### ISSUE THREAD

**Issue by owl0w1** [mpv-player/mpv#13622]
### Important information

Version information:
- mpv version: current master
- Linux Distribution and Version: Ubuntu 24.04
- Source of the mpv binary: compiled from source
- Version of mpv that introduced the problem: commit e3af545

### Reproduction steps

While setting up fuzzing of mpv, I noticed that execution with benchmark options (`--untimed` and friends) is significantly slower in current master than release 0.37.0. `git bisect` located the problem at commit e3af545.

First bad commit:
1. Check out commit e3af545
2. Build from source
3. Benchmark performance of `--untimed` option

```
user@laptop:~/mpv-e3af545$ hyperfine './build/mpv --vo=null --untimed --ao=null --ao-null-untimed ~/9bitwhite.mkv'
Benchmark 1: ./build/mpv --vo=null --untimed --ao=null --ao-null-untimed ~/9bitwhite.mkv
  Time (mean ± σ):     515.6 ms ±   5.0 ms    [User: 216.0 ms, System: 51.4 ms]
  Range (min … max):   509.9 ms … 527.5 ms    10 runs
 
user@laptop:~/mpv-e3af545$ hyperfine './build/mpv --untimed ~/9bitwhite.mkv'
Benchmark 1: ./build/mpv --untimed ~/9bitwhite.mkv
  Time (mean ± σ):      1.951 s ±  0.018 s    [User: 0.342 s, System: 0.107 s]
  Range (min … max):    1.932 s …  1.982 s    10 runs
```

A 9 second video file took roughly 0.5s to play with `vo=null` and `--untimed` options. With normal video output and `--untimed` option only, it took roughly 1.9s to play.

Last good commit:
1. Check out commit 7051e94, parent of commit e3af545
2. Build from source
3. Benchmark performance of `--untimed` option

```
user@laptop:~/mpv-7051e94$ hyperfine './build/mpv --vo=null --untimed --ao=null --ao-null-untimed ~/9bitwhite.mkv'
Benchmark 1: ./build/mpv --vo=null --untimed --ao=null --ao-null-untimed ~/9bitwhite.mkv
  Time (mean ± σ):     101.7 ms ±   3.1 ms    [User: 206.8 ms, System: 53.0 ms]
  Range (min … max):    95.7 ms … 108.8 ms    27 runs
 
user@laptop:~/mpv-7051e94$ hyperfine './build/mpv --untimed ~/9bitwhite.mkv'
Benchmark 1: ./build/mpv --untimed ~/9bitwhite.mkv
  Time (mean ± σ):      1.618 s ±  0.019 s    [User: 0.375 s, System: 0.093 s]
  Range (min … max):    1.593 s …  1.650 s    10 runs
```

The same 9 second video file took roughly 0.1s to play with `vo=null` and `--untimed` options. With normal video output and `--untimed` option only, it took roughly 1.6s to play.

There is a 5x performance regression in `--untimed` between these two commits.

### Expected behavior

Do not sleep when outputting video frames with `--untimed` enabled.

### Actual behavior

Additional delay other than decoding cost introduced between frames even when `--untimed` is enabled.

### Sample files

The sample file used in reproduction steps: https://github.com/strongcourage/fuzzing-corpus/blob/master/mkv/9bitwhite.mkv

The issue seems to be independent of the input file.

**Comment by llyyr** [comment]
can you try https://github.com/mpv-player/mpv/pull/13614 ?
