### ISSUE TITLE
Suggestion: avisynth in manual

### ISSUE THREAD

**Issue by johnlee1st** [mpv-player/mpv#1362]
I was trying in vain for a while to open avs scripts using mpv when it finally came to my mind that the 64-bit binary of mpv won't work with 32-bit avisynth plugins, doh!

Yes, this is obvious, yet it'd be nice to include a brief note about it in the manual, which would also keep others from making the stupid mistake I made . : )

**Comment by wm4** [comment]
AviSynth is dead and should stay dead.
