### ISSUE TITLE
Can a Plugin retrieve the framebuffer of the "to be rendered image" and corresponding audio?

### ISSUE THREAD

**Issue by emcodem** [mpv-player/mpv#13631]
I would like to use my own rendering module that instead of outputting the data to display and sound device, downscale and encode it to be sent in a continuous udp live transport stream.

However, it looks like tere are no examples for such integration and from what i read so far it seems to be by design that one cannot get the decoded buffers from mpv. 

Is it true that it is not foreseen for a C plugin (or any other method) to retrieve the output data buffers?

**Comment by emcodem** [comment]
small update, so i managed to get the player output encoded and streamed to udp using normal mpc encoding options, it seems to behave good when doing pause and seek as well as switching audio tracks so far. 
However, the vo_lavc seems to force "untimed" output and the option --untimed=no had no effect, so it only worked for me to recompile mpv with the changed vo_lavc.c

Should the --untimed option have an effect on vo_lavc?

**Comment by sfan5** [comment]
mpv is not designed for this and `vo_lavc` is not the solution either.
