### ISSUE TITLE
The cursor doesn't autohide in fullscreen after clicking on the progress bar.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#13630]
### Important Information

Provide following Information:
- mpv version
```
mpv v0.37.0-476-g9ac791c329 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.346.0 (v6.338.0-88-g311a5950)
FFmpeg version: N-113942-g4ed0fea0fa
FFmpeg library versions:
   libavutil       58.40.100
   libavcodec      60.41.100
   libavformat     60.23.100
   libswscale      7.6.100
   libavfilter     9.17.100
   libswresample   4.14.100
```
- Linux Distribution and Version
Arch
- Source of the mpv binary
AUR
- If known which version of mpv introduced the problem
I don't know.
- Window Manager and version
Mutter 45.4
- GPU model, driver and version
`Mesa Gallium driver 24.0.2-arch1.1 for AMD Radeon RX 6750 XT (radeonsi, navi22, LLVM 16.0.6, DRM 3.57, 6.7.7-zen1-1-zen)`
- Possible screenshot or video of visual glitches
![image](https://github.com/mpv-player/mpv/assets/9532105/7deb3ad4-666b-453c-a471-d3de5560f58f)

### Reproduction steps

1. Play the video in fullscreen
2. click the progress bar to adjust the timeline
3. wait for the cursor to disappear.

### Expected behavior
The cursor autohides.
### Actual behavior
It doesn't.
### Log file

[no_hide_cursor.txt](https://github.com/mpv-player/mpv/files/14482608/no_hide_cursor.txt)

### Sample files

Any video.

**Comment by Dudemanguy** [comment]
Are you leaving the cursor over the seek bar after you adjust it? It's not supposed to disappear in that case.

**Comment by laichiaheng** [comment]
> Are you leaving the cursor over the seek bar after you click on it? It's not supposed to disappear in that case.

Nope, the seek bar has already been hidden, but the cursor still shows on the middle of the screen.

**Comment by llyyr** [comment]
Can you check if mpv registers any mouse movements with `--msg-level=input=trace`?
