### ISSUE TITLE
mpv --fullscreen option makes error in debian unstable 

### ISSUE THREAD

**Issue by zhhxiang05** [mpv-player/mpv#13636]
Hardware: macbook m2 
Arch: arm64 
Operating System: debian unstable 
mpv version: 0.37.0 
mpv ffmpeg versio: 6.1.1-1 

I was using the newest version mpv in the newest debian. And I also use mpv in macOS and ubuntu too. 
The macOS mpv and ubuntu mpv are alright, and debian mpv isnot. 

if run bash srcript "mpv demo.mp4", it works. 
if run "mpv --shuffle --loop-playlist=inf demo.mp4", it works. 
if run "mpv --fullscreen --shuffle --loop-playlist=inf demo.mp4", it becomes weired. 

In the beginning, everything works normally. But several minutes later, the mpv paused without any warning. It just 
paused there and react nothing to any keyboard input. And if switch to bash command, the mpv session shall be reactivated. 
It just like mpv session went to sleep without any warning or stderr. 

I have compared my macOS mpv , debian mpv , ubuntu mpv. The mpv version is the same, but the ffmpeg version isnot. 
So I guess 
1.  maybe debian ffmpeg 6.1.1-1 is wrong. Because the old mpv version in debian is OK. That version is ffmpeg 6.1.1 
2.  maybe mpv is OK but debian is wrong. Because recently debian unstable upgraded so many packages , include gnome. 

Because the mpv donot really failed, it just sleep. So I cannot provide log file. But it is easy to reproduce this bug.

**Comment by CounterPillow** [comment]
no log no fix

**Comment by zhhxiang05** [comment]
[mpv.log](https://github.com/mpv-player/mpv/files/14490006/mpv.log)
@CounterPillow here is the testing log. 
In this test, the mpv automatically paused after 1 minutes running.

**Comment by CounterPillow** [comment]
Thank you, the log reveals some interesting things:

```
[   0.180][d][ao/pipewire] Stream state changed: old_state=unconnected state=connecting error=(null)
...
[   0.181][d][ao/pipewire] Stream state changed: old_state=connecting state=paused error=(null)
```

the audio server (in this case pipewire) acting up could definitely trip up mpv's playback loop, as the default video sync is timed to audio playback.

Try reproducing the problem with `--no-audio`.

**Comment by zhhxiang05** [comment]
@CounterPillow  here is the new log. It also paused. 
[mpv.log](https://github.com/mpv-player/mpv/files/14490268/mpv.log)

**Comment by zhhxiang05** [comment]
in a further test, it is only occurs in gnome. The bug doesnot exist in xfce4. And many other bugs occur in the debian unstable gnome now. So I guess it is better to shut down this issue in several days. I will shut this topic after several days testing in xfce desktop.

**Comment by zhhxiang05** [comment]
everything works fine in xfce4. it is a gnome bug.
