### ISSUE TITLE
mpv_command_string() loadfile How do I attach a command?

### ISSUE THREAD

**Issue by lazulkia** [mpv-player/mpv#13656]
After I updated mpv to the latest version (the old version is a few months old), mpv_command_string() does not execute this command:
loadfile "E:\\test.mkv" replace start=+36

The console reports the error as:
[input] The loadfile option must be an integer: start=+36
[input] Command loadfile: argument 3 can't be parsed: option parameter could not be parsed.
[input] Command was defined at main.

I didn't find an update log for this.
What can I change now to make the additional parameter(start=+36) take effect?
Thanks.

**Comment by sfan5** [comment]
The syntax changed in c678033c1d60b48ae02fbbe4815869b9504a17f6, see here:
https://github.com/mpv-player/mpv/blob/0d33394955cb9d90905e8ade8776a3574d694544/DOCS/man/input.rst#L455-L497

**Comment by lazulkia** [comment]
Thanks, now command_string() can't load the "start=+36" command?
