### ISSUE TITLE
Japanese character spacing error

### ISSUE THREAD

**Issue by beschoenen** [mpv-player/mpv#1365]
When playing videos that have Japanese characters in the name a spacing error occurs
Japanese character for to: と/ト
Japanese character for do: ど/ド
notice that the do character have 2 little lines, these lines are displayed as separate characters in mpvs control hud

Image: http://puu.sh/dzLgc/a2e09411d5.png
I'm on OS X Yosemite 10.10.1
mpv was installed via homebrew
mpv settings/info: http://pastebin.com/fjnGA1t5

**Comment by wm4** [comment]
I assume this is fixed.
