### ISSUE TITLE
FFmpeg Channel Layout Changes Break Audio Output With `video-sync=display-resample`

### ISSUE THREAD

**Issue by CounterPillow** [mpv-player/mpv#13662]
### Important Information

Provide following Information:
- mpv version: mpv v0.37.0-514-g78447c4b91
- Linux Distribution and Version: Arch btw, 6.7.8
- Source of the mpv binary: mpv-build
- Window Manager and version: kwin 6.0.1 (Wayland)
- GPU model, driver and version: AMD Radeon Vega 10 Graphics, amdgpu, mesa 24.0.2

### Reproduction steps

```
mpv --no-config --video-sync=display-resample https://www.youtube.com/watch?v=Wy6kZm-lC4g
```

### Expected behavior

I hear the goose.

### Actual behavior

No audio;
```
[ffmpeg] SWR: Input channel layout "" is invalid or unsupported.
[swresample] Cannot open Libavresample context.
[swresample] libswresample failed to initialize.
Cannot convert decoder/filter output to any format supported by the output.
Audio: no audio
```
in console.

### Log file

https://overviewer.org/~pillow/up/4a35281ea6/penis.log

**Comment by CharlesMengCA** [comment]
Same error on window's build.

**Comment by Dudemanguy** [comment]
This is because our usage of libswresample implicitly relied on the stuff ffmpeg just removed. The handling of it needs to be updated as well, namely the channel mappings.

**Comment by Hrxn** [comment]
> Same error on window's build.

Yep.. 
FWIW, this is affected *regardless* of `video-sync=display-resample` on Win32 (cf. #13669)

Curious that these old channel layout options still worked on Linux without that option set, apparently.
Unless I've misunderstood this issue description here..
