### ISSUE TITLE
select preferred audio track by name, not by code

### ISSUE THREAD

**Issue by lvmm** [mpv-player/mpv#13678]
### Expected behavior of the wanted feature
mpv lets one select preferred audio track languages with --alang option by language codes but it doesn't help when video has multiple soundtracks in the same language or when audio tracks have no language code (e.g. natural sounds or sloppy encoding). I'd like to be able to select preferred audio tracks by a substring in its name.

A real-world example: video with 'en' English audio and 'und' Natural audio (mkvinfo output from mkvtoolnix). I'd like mpv select natural audio by default, but setting --alang=und doesn't work which is understandable as und is not in the ISO 639 standard. Something like --aname=natural, perhaps?

```
| + Track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 17745400697106141509
|  + Track type: audio
|  + Codec ID: A_AAC
|  + Codec's private data: size 2
|  + Default duration: 00:00:00.021333333 (46.875 frames/fields per second for a video track)
|  + Language (IETF BCP 47): en
|  + Name: Commentary-SkyF1
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 2
| + Track
|  + Track number: 3 (track ID for mkvmerge & mkvextract: 2)
|  + Track UID: 423696752255660601
|  + Track type: audio
|  + Language: und
|  + Codec ID: A_AAC
|  + Codec's private data: size 2
|  + Default duration: 00:00:00.021333333 (46.875 frames/fields per second for a video track)
|  + Language (IETF BCP 47): und
|  + Name: Natural/Ambient
|  + Audio track
|   + Sampling frequency: 48000
|   + Channels: 2
```

**Comment by po5** [comment]
Try [trackselect](https://github.com/po5/trackselect), it supports selecting audio tracks based on titles and channel count.

**Comment by lvmm** [comment]
Thanks, it does exactly what I need.

**Comment by ZeroHackz** [comment]
> Thanks, it does exactly what I need.

I tried the same within "%APPDATA%/mpv/" I created a scripts directory and placed both files of trackselect repo, it didn't auto select after run. What else did you do or differently than me?

**Comment by lvmm** [comment]
script configuration files should be placed into script-opts, not scripts
