### ISSUE TITLE
Change / adjust defaults about hardware decoding?

### ISSUE THREAD

**Issue by DimanNe** [mpv-player/mpv#13679]
### Important Information

Provide following Information:
- mpv version: **0.36.0**
- Linux Distribution and Version: **Kubuntu 23.10**
- Source of the mpv binary: **apt**
- ~~If known which version of mpv introduced the problem~~
- Window Manager and version: KDE
- GPU model, driver and version: **NVIDIA GeForce RTX 3080, 535.161.07**
- ~~Possible screenshot or video of visual glitches~~

### Reproduction steps

I was experiencing:

1. terrible frame-drops (like dozens dropped frames a second)
2. **terrible** tearing issue 
3. and also some noticeable slow-down (like 0.75)
in mpv (while the video was perfectly fine in vlc).

But then I found this:

> Note
> Use the Ctrl+h shortcut to toggle hardware decoding at runtime. It toggles this option between auto-safe and no.

### This single shortcut fixed all my issue.

I think it really makes sense to change the defaults...
Why it was not using hardware decoding?

**Comment by llyyr** [comment]
See: https://github.com/mpv-player/mpv/issues/12948#issuecomment-1824839451

**Comment by CounterPillow** [comment]
Your distribution, Ubuntu, in fact even overrode mpv's default with their own `/etc/mpv/mpv.conf` in which they foolishly put `hwdec=vaapi` (side note: yes they did that instead of `auto-safe` or something like that), but if it's not on for you anymore that means even they realized the errors of their ways and got rid of it.

**Comment by DimanNe** [comment]
> See: [#12948 (comment)](https://github.com/mpv-player/mpv/issues/12948#issuecomment-1824839451)

I read the comment, it **does** make sense.
But I am not sure it is good idea to just leave it in this state. I was about to drop mpv. If I were in a hurry, I would just come to the conclusion that "_mpv cannot play high-res videos_".

**Comment by Hrxn** [comment]
That simply means you conclusion would be, well, wrong..
