### ISSUE TITLE
adjustable duration between file to next file?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#13693]
Using [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) and noticed something interesting.
mpv will load `1.png` and keep it on screen for roughly for 1 second and then will play `2.png` for 1 second and so on and so on.
I was wondering if I can change the amount of time the picture stays on screen.
Let's say I want to keep pictures on screen for 30 seconds, like a slideshow or a screensaver, is that possible?
What about changing it so it will play though images fast, instead of 1 second then 300ms for example, as a way of skipping though images?

**Comment by Traneptora** [comment]
`--image-display-duration`
