### ISSUE TITLE
Using too many individual scripts with `mp.add_key_binding` breaks keybinds.

### ISSUE THREAD

**Issue by Sneakpeakcss** [mpv-player/mpv#13707]
### Important Information

- mpv version: `mpv-x86_64-v3-20240314-git-5dd2d19`
- Windows Version: `WIN10 22H2`
- Source of the mpv binary: [zhongfly](https://github.com/zhongfly/mpv-winbuild/releases)
- If known which version of mpv introduced the problem: `goes as far as 2022 builds`
- GPU model, driver and version: `RX570 Adrenalin 24.1.1`

 

Seemingly having too many individual scripts that use `mp.add_key_binding` breaks key bindings of other scripts, including default ones like `console.lua`. 

Here's an example with [uosc](https://github.com/tomasklaen/uosc) and `console.lua`:

https://github.com/mpv-player/mpv/assets/77424331/5dd463c6-d741-4ee1-a9cf-9313b3527435

Opening console with `` ` ``  works, but after that it's completely unresponsive, `uosc` is also broken from the start. 

Weirdly enough, doing the same using `JavaScript` scripts 'works' a bit differently: 

https://github.com/mpv-player/mpv/assets/77424331/373e89e4-0b18-49f3-9ae3-a6f71312a663

In this case console works without issues, but other scripts are still breaking. 

### Reproduction steps
1) Download [samplescripts](https://github.com/mpv-player/mpv/files/14618879/samplescripts.zip) and install all 30 lua scripts.

### Expected behavior
Using a lot of individual scripts shouldn't remove(?)/overwrite(?) keybinds of other scripts.

### Actual behavior
At some treshold (25-30~) scripts start to break. Included 30 sample scripts break it instantly at launch, but in my normal `mpv` usage i've had situations where everything works properly at the beginning and with time it starts breaking 'randomly' at runtime, to the point where it was a pain to figure out what suddenly caused this issue.

### Log file
[brokenscriptsLUA.txt](https://github.com/mpv-player/mpv/files/14618982/brokenscriptsLUA.txt)
[brokenscriptsJS.txt](https://github.com/mpv-player/mpv/files/14618984/brokenscriptsJS.txt)

### Sample files

[samplescripts.zip](https://github.com/mpv-player/mpv/files/14618879/samplescripts.zip)

**Comment by hooke007** [comment]
I must have seen it before. Built-in osc can be reproduced too.

**Comment by Sneakpeakcss** [comment]
> I must have seen it before. Built-in osc can be reproduced too.

Yea, i've used `uosc` as an example since it's the easiest to notice on video, in comparison to all other scripts breaking.
I didn't check previously how this behaves with build-in `osc`, but on my side it seems that it goes beyond keybinds, at best it only flashes for a split of a second on video start and then disappears permanently, so that's even worse.

The only workaround i managed to find is to obviously join all my little scripts into a single file, but that's far from perfect.

**Comment by dyphire** [comment]
I can reproduce it. A long time ago, I noticed this issue and could only choose to streamline the script to avoid it.
