### ISSUE TITLE
qt_opengl example render issue

### ISSUE THREAD

**Issue by tinybug** [mpv-player/mpv#13705]
The mpv version is: 0.37.0
The Qt version is: 5.15.2
macOS version: 13.4.1

I build this example https://github.com/mpv-player/mpv-examples/tree/master/libmpv/qt_opengl, then play video with it, and then I get this result:

The video render on the letf-bottom corner, could anyone help with this? Thanks!

<img width="520" alt="image" src="https://github.com/mpv-player/mpv/assets/3439875/7c97a69a-6c72-454b-bedc-6b51fe2644ae">

**Comment by Dudemanguy** [comment]
I'm pretty sure the example is just bugged and no one has ever bothered to fix it.

**Comment by Akemi** [comment]
just an assumption. you are using a hidpi resolution and width()/height() (https://github.com/mpv-player/mpv-examples/blob/master/libmpv/qt_opengl/mpvwidget.cpp#L78) return only a resolution that doesn't take the backing scale factor into account, eg  the rendered surface is just half of the actual surface in that case.

you probably need this https://doc.qt.io/qt-6/qwindow.html#devicePixelRatio

see the same thing within mpv
https://github.com/mpv-player/mpv/blob/474e213f528c5c9c72faabb83f75e441a212d591/osdep/mac/libmpv_helper.swift#L130-L133
https://github.com/mpv-player/mpv/blob/474e213f528c5c9c72faabb83f75e441a212d591/video/out/mac/gl_layer.swift#L166
https://github.com/mpv-player/mpv/blob/474e213f528c5c9c72faabb83f75e441a212d591/video/out/mac/gl_layer.swift#L174-L183
https://github.com/mpv-player/mpv/blob/474e213f528c5c9c72faabb83f75e441a212d591/video/out/mac/gl_layer.swift#L212-L215
