### ISSUE TITLE
Quitting removes watch later files

### ISSUE THREAD

**Issue by minyani** [mpv-player/mpv#13702]
### Important Information

Provide following Information:
- mpv version: v0.37.0
- Linux Distribution and Version: Arch Linux with kernel Linux 6.7.9-arch1-1
- Source of the mpv binary: [https://archlinux.org/packages/extra/x86_64/mpv/](https://archlinux.org/packages/extra/x86_64/mpv/)
- Window Manager and version: sway version 1.9
- GPU model, driver and version: Intel 3rd Gen Core processor Graphics Controller, kernel driver i915

### Reproduction steps

Play a video or playlist and then `Q quit-watch-later`. Play it again and it will resume at the old playback position. Then `q quit`. When it is played a third time the video/playlist starts from the beginning instead of the watch later position.

### Expected behavior

`q quit` should not affect the video's watch later position/options.

### Actual behavior

`q quit` removes the video's watch later files. Here's the watch later directory after using `Q quit-watch-later`:
```
$ ls -a .local/state/mpv/watch_later/
. .. 31A5C30CAD2AC6860B0BDBE49A62B7E6  4858DAB5B4AC16AD2B7D274698C2532A  8196A4C2E5BAED94F8657CB3E2DA2E63
```
And after using `q quit`:
```
$ ls -a .local/state/mpv/watch_later/
. ..
```

### Log file

[log_0_quit-watch-later.txt](https://github.com/mpv-player/mpv/files/14608352/log_0_quit-watch-later.txt)
[log_1_quit.txt](https://github.com/mpv-player/mpv/files/14608392/log_1_quit.txt)

**Comment by Dudemanguy** [comment]
When you play the file again on the second the time, it resumes from the old playback position and deletes the old watch later data. Quitting with `q quit` doesn't save anything of course. So it seems like everything is working? I'm not sure what you expected.

**Comment by minyani** [comment]
Hmm I see. Then is there a way to stop mpv from deleting old watch later data when playing a file? It's just inconvenient for me because I like to open a playlist I've been watching and skip around to find something, and don't want to have to seek back to where I started before quitting.

**Comment by guidocella** [comment]
You can pass `--no-resume-playback` when replaying the playlist or run `write-watch-later-config` after opening it.
