### ISSUE TITLE
libplacebo warnings in console when using custom icc profile

### ISSUE THREAD

**Issue by raziel711** [mpv-player/mpv#13701]
### Important Information

Provide following Information:
- mpv version: 0.37.0-538-g5dd2d195
- Platform and Version: Windows 10 22H2 19045.4170
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild/releases
- GPU model, driver and version: NVIDIA GeForce GTX 1650, driver version 551.76

### Reproduction steps
Load any video file using a custom icc profile: `mpv --no-config --vo=gpu-next --icc-profile-auto`

### Expected behavior
The warnings in the screenshot below should be included in the log file, but not mpv's console.
### Actual behavior
I get the following lines in the console:
![mpv_nlKzhk0Lgc](https://github.com/mpv-player/mpv/assets/75226602/1f34a62f-b7b2-4e52-8e52-d5e80b02b43a)

Assuming there is not something critically wrong with my icc profile, can these warnings be hidden from the console?  The biggest issue I have is that this same set of warnings show up in the console every time I change `--scale`, toggle a shader, or toggle debanding so it can end up generating a lot of spam in the console that could hide other warnings or errors.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/14606829/log.txt)

### Sample files
This is the icc profile that I'm using:
[icc.zip](https://github.com/mpv-player/mpv/files/14606924/icc.zip)

**Comment by haasn** [comment]
Fixed by 5c1e6da21f108a27b11fad97fd491ddee06ede3c
