### ISSUE TITLE
How to automatically play DVD or Blu-ray ISO files?

### ISSUE THREAD

**Issue by Solarunit** [mpv-player/mpv#13712]
I figured out how to play DVD or Blu-ray ISO files from the terminal using:

`mpv bd:// --bluray-device=[path-to-bluray-iso]` for Blu-ray ISO

and

`mpv dvd:// --dvd-device=[path-to-dvd-iso]` for DVD ISO

The question is how to play those iso files automatically? Like `mpv [path-to-iso]` will detect if it's DVD ISO or Blu-ray ISO and will play it.

Is there a condition I can put into mpv.conf?
Or maybe it's possible with some lua script? Maybe there is already such script?

**Comment by dyphire** [comment]
For the lua script, you can refer to the relevant implementation in the [open_dialog.lua](https://github.com/dyphire/mpv-scripts/blob/main/open_dialog.lua#L85-L90) script.

**Comment by Solarunit** [comment]
@dyphire interesting, I will check it out, thanks.
I wonder how it differentiate between dvd iso and bluray iso :thinking:

**Comment by Solarunit** [comment]
I am new to lua, how to get file path/basename in `mpv [file-path]`?
I am trying `mp.get_property(path)`

**Comment by guidocella** [comment]
`mp.get_property('filename')`

**Comment by Solarunit** [comment]
when printing `print(mp.get_property('filename'))`:

`nil property unavailable`

**Comment by guidocella** [comment]
```lua
mp.register_event('file-loaded', function()
    print(mp.get_property('filename'))
end)
```

**Comment by Solarunit** [comment]
it does't print anything for me :(

**Comment by Solarunit** [comment]
with my test lua script I can redirect dvd iso file to 

```lua
local function open_dvd(path)
    mp.set_property('dvd-device', path)
    mp.commandv('loadfile', 'dvd://')
end
```

but not for bluray iso :cry: 

```
[file] Opening file.iso
....

[cplayer] Opening failed or was aborted: file.iso
...

[cplayer] finished playback, unrecognized file format (reason 4)

```
Unlike dvd iso it can't start playback bluray iso file, so we will never get to this point in lua script:

```lua
mp.register_event('file-loaded', function()
```

**Comment by Solarunit** [comment]
I have some progress with the script. I can redirect bluray iso file to `open_bluray(path)` function too.
What is the proper way to get parent directory of some directory in lua?

Like: path = `/dir1/dir2/`

and I need to get `/dir1/` path
