### ISSUE TITLE
Device exclusivity not released when playback is paused

### ISSUE THREAD

**Issue by zhengqwe** [mpv-player/mpv#13715]
### Important Information

Provide following Information:
- mpv version
0.37.0
- Windows Version
Windows 10
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20240317/mpv-x86_64-v3-20240317-git-3afcaeb.7z
- If known which version of mpv introduced the problem
- GPU model, driver and version
- Possible screenshot or video of visual glitches

### Reproduction steps

Play any audio using`mpv --no-config --audio-exclusive=yes`and pause it, then resume it.

### Expected behavior

Release device exclusivity when paused and playback normally when resume it

### Actual behavior

Device exclusivity not released when paused, and when resume it, it playback freezes, the same as #12640. If don't pause, it playback normally.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/14627384/output.txt)

**Comment by sunpenghao** [comment]
This is expected. Once an exclusive WASAPI audio client has been initialized it retains exclusive access until its destruction. mpv's generic AO code only resets the client on pause, so the device won't be released.

**Comment by sunpenghao** [comment]
What exactly do you mean by freezing?

**Comment by sunpenghao** [comment]
Is this issue device or source specific?

**Comment by sunpenghao** [comment]
Well this is interesting.

From your log the buffer should hold 10ms of samples, and the renderer thread should be woken up every 10ms, but in your case sometimes it is woken up every 1ms:
```
......
[   0.821][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.822][t][ao/wasapi] Device delay: 9.79522e+06 ns
[   0.822][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.823][t][ao/wasapi] Device delay: 1.8707e+07 ns
[   0.824][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.824][t][ao/wasapi] Device delay: 2.77546e+07 ns
[   0.825][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.825][t][ao/wasapi] Device delay: 3.66889e+07 ns
[   0.826][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.826][t][ao/wasapi] Device delay: 4.58271e+07 ns
[   0.827][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.827][t][ao/wasapi] Device delay: 5.56685e+07 ns
[   0.828][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.828][t][ao/wasapi] Device delay: 6.48748e+07 ns
[   0.828][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.829][t][ao/wasapi] Device delay: 7.43307e+07 ns
[   0.829][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.829][t][ao/wasapi] Device delay: 8.38091e+07 ns
[   0.831][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.832][t][ao/wasapi] Device delay: 9.35474e+07 ns
[   0.833][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.833][t][ao/wasapi] Device delay: 1.02108e+08 ns
[   0.834][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   0.834][t][ao/wasapi] Device delay: 1.1145e+08 ns
......
```
And sometimes it hangs for over 70ms:
```
[   1.898][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   1.899][t][ao/wasapi] Device delay: 1.04648e+08 ns
[   1.975][t][ao/wasapi] Frame to fill: 448. Padding: 448
[   1.976][t][ao/wasapi] Device delay: 3.78895e+07 ns
```
This should lead to glitches. Are there any?

**Comment by sunpenghao** [comment]
@zhengqwe

Could you try the build in https://github.com/mpv-player/mpv/pull/13784#issuecomment-2027233829 and see if the freezing problem still persists? The patch makes it so that the stream is only stopped on pause, instead of being reset completely. This might make a difference for your particular issue.

**Comment by sunpenghao** [comment]
Could you also try this build from #13805: https://github.com/mpv-player/mpv/actions/runs/8506480306/artifacts/1374035692

I've added a `--wasapi-exclusive-buffer` option to control the buffer size used in exclusive mode. You can try setting it to `min` and see if it can fix the issue. If not, try directly specifying different sizes in microseconds (I'd start from multiples of the default or minimum device period; look into the log for `[v][ao/wasapi] Device period: default xxxx us, minimum xxxx us`).
