### ISSUE TITLE
Abnormal colors with vo=gpu-next and icc-profile-auto

### ISSUE THREAD

**Issue by happybrisk** [mpv-player/mpv#13749]
### Important Information

Provide following Information:
- mpv v0.37.0-561-g3afcaeb7
- Windows 11 23H2 10.0.22631.3296
- Source of the mpv binary
  - [sourceforge](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/mpv-x86_64-v3-20240317-git-3afcaeb.7z/download)
- If known which version of mpv introduced the problem
  - Maybe a build after v0.37.0-522-ga56d8ff1
- GPU model, driver and version
  - NVIDIA GeForce RTX 3060 Ti, 31.0.15.5176

### Reproduction steps

The custom `mpv.conf` has been removed. The following steps will produce normal colors:

`mpv.com -v --vo=gpu-next xxx` , or
`mpv.com -v --vo=gpu --icc-profile-auto=yes xxx`, or
`mpv.com -v --no-config --vo=gpu-next --icc-profile-auto=yes xxx`

Only the following step will produce unusual colors:

`mpv.com -v --vo=gpu-next --icc-profile-auto=yes xxx`

### Expected behavior

The colors of the video look fine.

![image](https://github.com/mpv-player/mpv/assets/4309688/be67a8c9-3af1-4f5d-94ce-88822887a578)

### Actual behavior

With the `vo=gpu-next` and `icc-profile-auto=yes` set, the colors of the video look unusual.

![image](https://github.com/mpv-player/mpv/assets/4309688/a188e62c-3eeb-4060-b0fa-8c22d4294619)

Note

- The behavior of the version `v0.37.0-522-ga56d8ff1` was just fine.
- When I selected an icm file other than `sRGB Color Space Profile.icm`, I got the correct colors.

### Log file

[log-v0.37.0-522-ga56d8ff1.txt](https://github.com/mpv-player/mpv/files/14725035/log-v0.37.0-522-ga56d8ff1.txt)

[log-v0.37.0-561-g3afcaeb7.txt](https://github.com/mpv-player/mpv/files/14725038/log-v0.37.0-561-g3afcaeb7.txt)

### Sample files

The behaviors are the same when playing any video, so there is no need to upload a sample file.

**Comment by orion1vi** [comment]
Should be fixed by https://github.com/haasn/libplacebo/pull/249#issuecomment-2010917057

**Comment by happybrisk** [comment]
> show stats in both cases (shift+i)

stat of version v0.37.0-561-g3afcaeb7, with flags `--vo=gpu-next --icc-profile-auto=yes`:

![image](https://github.com/mpv-player/mpv/assets/4309688/7172a2c7-26b2-4690-b48a-e9feaf9e4a8b)

stat of version v0.37.0-522-ga56d8ff1 with flags `--vo=gpu-next --icc-profile-auto=yes`:

![image](https://github.com/mpv-player/mpv/assets/4309688/5600d75b-5c5b-4b1f-8515-35da988811ac)

What I find interesting is that after adding the `--no-config` parameter the colors become normal. What exactly does it do? (I've removed the `mpv.conf`)

stat of version v0.37.0-561-g3afcaeb7, with flags `--no-config --vo=gpu-next --icc-profile-auto=yes`:

![image](https://github.com/mpv-player/mpv/assets/4309688/7dd22427-ea54-4136-8114-bc6bfc2e47a8)

**Comment by happybrisk** [comment]
> Should be fixed by [haasn/libplacebo#249](https://github.com/haasn/libplacebo/pull/249)

OK I'll try next build.

**Comment by kasper93** [comment]
I though you already testing latest build. You can find them here https://github.com/shinchiro/mpv-winbuild-cmake/releases or https://github.com/zhongfly/mpv-winbuild/releases

Feel free to reopen if this still happens, but it definitely is above fix.

**Comment by happybrisk** [comment]
I tried the build `v0.37.0-663-g9cee4414`  downloaded from [here](https://github.com/zhongfly/mpv-winbuild/releases/download/2024-03-22-9cee441/mpv-x86_64-v3-20240322-git-9cee441.7z) and it seemed everything well. Thank you very much.
