### ISSUE TITLE
Video looks a bit blurry when using vo=dmabuf-wayland compared to other options.

### ISSUE THREAD

**Issue by Drommer** [mpv-player/mpv#13745]
### Important Information

Provide following Information:
- mpv 0.37.0_627_g8c1117b2cb-1
- Arch Linux with KDE Plasma Desktop
- AUR (mpv-git)
- I don't known which version of mpv introduced the problem
- KWin 6.0.2 (without using scaling)
- Intel Graphics HD 4600 / libva-intel-driver 4.2.1

The problem is relevant for videos with a resolution smaller than the screen resolution. The effect is only noticeable when the window size is increased (up to full screen), so I assume the problem is related to scaling. 

Below are screenshots taken by a third party application in full screen mode. mpv parameters:
1. ``--no-config`` ``--vo=gpu-next`` ``--hwdec=vaapi``
2. ``--no-config`` ``--vo=dmabuf-wayland`` ``--hwdec=vaapi``

Source: H264 video with 720x400 resolution. The problem is the same for MPEG-2 from DVD regardless of color space (BT.601 / BT.709). 

P.S. Also regardless of the window size you can see that the color rendition differs a little bit.

![gpu-next](https://github.com/mpv-player/mpv/assets/36813829/3fbde37b-d256-4b95-bb93-1bc73ffbdfce)
![dmf](https://github.com/mpv-player/mpv/assets/36813829/7262671e-39e9-40b8-9458-348011a40958)
[log.txt](https://github.com/mpv-player/mpv/files/14715568/log.txt)

**Comment by CounterPillow** [comment]
This is intended. Default settings for gpu/gpu-next use high quality scaling. dmabuf-wayland just leaves scaling up to the compositor, which is the whole point of it.

If you're looking for quality, don't use dmabuf-wayland.
