### ISSUE TITLE
utils.shared_script_property_set now is nil.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [mpv-player/mpv#13754]
Is there any alternative?

### Log file

[modernf] nil
[modernf]
[modernf] stack traceback:
[modernf]       D:/E/Tools/mpv/portable_config/scripts/modernf.lua:2456: in main chunk
[modernf]       [C]: at 0x7ff71997ae30
[modernf]       [C]: at 0x7ff719979d00
[modernf] Lua error: D:/E/Tools/mpv/portable_config/scripts/modernf.lua:2417: attempt to call field 'shared_script_property_set' (a nil value)

**Comment by guidocella** [comment]
`user-data`

**Comment by christoph-heinrich** [comment]
`shared-script-properties` have been replaced by [user-data](https://mpv.io/manual/master/#command-interface-user-data)
