### ISSUE TITLE
Video screenshots gets a blue nuance or tint using vo=gpu but not vo=xv on Raspberry Pi 4

### ISSUE THREAD

**Issue by gevvan** [mpv-player/mpv#13759]
### Important Information

Running ..

mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1.11-0+deb10u1+rpt1

.. on a Raspberry Pi 4B with ancient Buster-based Raspian, hence a very old mpv build from default repositories.

Like stated, I'm aware it's a very old release and that I should probably update my Raspberry and mpv. Right now I don't feel for a full Raspian update though, and building mpv from scratch seems easier said than done, I've tried it but something in the dependency chain always beats me, so I'm depending simple pre-builds available through apt-get right now.

### Reproduction steps

Whenever I watch a video and press S to take a screenshot the output gets like this,  blue-isch. See my attached screenshot. It doesn't matter if I run mpv with --no-config or --hwdec=yes or --hwdec=no, result is still the same. Interesting, if I run --vo=xv the screenshots gets perfect, no blueish tint. But then I get a blurred OSD and stuff like that, and also mpv is warning that vo=xv is old and deprecated and really a last resort. And my default vo=gpu works a charm in all aspects EXCEPT for this little issue.

### Expected behavior
Screenshots looking like the video I'm watching.

### Actual behavior
Screenshots get's blue.

### Finally

I suspect this is a known issue that was fixed in the past, and I'm aware the main recommendation is just to update software. But since that's not really an option right now, after taking ~20 minutes writing this post, I would be much glad if someone who is aware of this issue could point me in some other workaround (with current mpv) than the vo=xv that I've discovered myself. I'm guessing it's something with the colorspace that messes the output? It doesn't matter if I use png or jpg for output, they all get blue. Are there some -- switches that I could execute mpv with to not have the blue screenshots and still use vo=gpu? Or is vo=xv kind of my only option with this ancient mpv build?

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/14734959/mpv.log)

### Sample files

![mpv-shot0004](https://github.com/mpv-player/mpv/assets/49226986/79ea56a5-c75f-434d-a255-0361656b0955)

**Comment by CounterPillow** [comment]
> mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects

Really, man?

**Comment by gevvan** [comment]
> > mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
> 
> Really, man?

Yeah like stated I'm fully aware it's an ancient release. But I'm guessing (hoping*) that this issue has been "officially discovered" some time in the past, and that there was another "workaround" than using XV for video output until an official fix was out, perhaps some --colorspace overriding stuff, I don't know? Anyways, I was hoping someone could give me a friendly advice on how to do damage control on the issue WITH this old release. If possible, that is.

**Comment by gevvan** [comment]
Unfortunately, --screenshot-sw was not introduced in mpv 0.29. I have tried both yes/no for --screenshot-tag-colorspace (since I have an intuitive feeling that this is somehow colorspace-related) but it doesn't make any difference.

**Comment by CounterPillow** [comment]
It does not look like it's colourspace related, it looks like it's misinterpreting the different planes of the YCbCr pixel format. If this goes through the download-from-gpu route instead of libswscale from decoder output (which would require archeology to determine) then it's possible that your also incredibly pitifully out of date graphics driver is what's at fault.
