### ISSUE TITLE
Is the current mpv supports RTX HDR?

### ISSUE THREAD

**Issue by AyaseMitsukasa** [mpv-player/mpv#13761]
If yes, please tell me how to configure it
If no, please tell me will it be added later and when will it be added

**Comment by CounterPillow** [comment]
Duplicate of https://github.com/mpv-player/mpv/issues/13352

**Comment by AyaseMitsukasa** [comment]
> Duplicate of #13352

I have tried inverse-tone-mapping but seems no effect at all
So is it currently not supported?

**Comment by CounterPillow** [comment]
no

**Comment by AyaseMitsukasa** [comment]
> no

Ok, thanks for the reply anyway
