### ISSUE TITLE
Please bring back the lasting status line after playing a video

### ISSUE THREAD

**Issue by Markus-N** [mpv-player/mpv#13760]
### Expected behavior of the wanted feature
A while ago, the status line (position and length of the video) was kept when playing ended or the user switched to the next/previous video in a playlist. One of the last updates (don't remember exactly which one it was) removed this as well as the blank line before the output for the next video.  
Please bring back both.  
Use case: when accidentally switching video, you still have the position where you were and can resume more easily.  

### Alternative behavior of the wanted feature
This could be optional (command line switch).  
If there is one and I just overlooked it, please enlighten me. :-)

### Log file
[mpv_output.txt](https://github.com/mpv-player/mpv/files/14735121/mpv_output.txt)

**Comment by guidocella** [comment]
It was already restored.
