### ISSUE TITLE
How to set automatic full screen during video playback-resolved

### ISSUE THREAD

**Issue by laodaoxp** [mpv-player/mpv#13771]
How to set automatic full screen during video playback
---------------------
Current settings:
No title bar
Autofit smaller=50% x50%
After opening, there is a window in the middle of the screen
-----------------------
When I want to drag a video into the window, it can automatically play full screen. How to set it. thanks

**Comment by guidocella** [comment]
```
[playing]
profile-cond=playlist_count > 0
fullscreen
```

**Comment by laodaoxp** [comment]
> ```
> [playing]
> profile-cond=playlist_count > 0
> fullscreen
> ```

This method can be used. Thank you
