### ISSUE TITLE
yt-dlp hook is not working, why?

### ISSUE THREAD

**Issue by Kreijstal** [mpv-player/mpv#13775]
### Important Information

Provide following Information:
- mpv version:  0.37.0
- Windows Version: win 10
- Source of the mpv binary: msys2/mingw repo
- If known which version of mpv introduced the problem: not known
- GPU model, driver and version: not sure intel, not a playback issue
- Possible screenshot or video of visual glitches
not a playback issue

### Reproduction steps

I can't manage to play youtube addresses from mpv even if I have yt-dlp installed, yt-dlp can download the video no problem, but I get a big error log, saying something is wrong with the hook.
if I separately download the video and then play it, it works.

### Expected behavior
Youtube playback

### Actual behavior
big error output

### Log file
One is the terminal output and the other is the file output.
[terminaoutput.txt](https://github.com/mpv-player/mpv/files/14780800/terminaoutput.txt)

[output.txt](https://github.com/mpv-player/mpv/files/14780805/output.txt)

### Sample files

any youtube video will do

**Comment by richardpl** [comment]
Probably something wrong in your configuration file. I had similar issue.

**Comment by Kreijstal** [comment]
> Probably something wrong in your configuration file. I had similar issue.

I have not configured it maybe it is the mantainer version, https://github.com/msys2/MINGW-packages/issues/19568
this is how it is built
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-mpv/PKGBUILD

**Comment by richardpl** [comment]
Dunno then, for me yt links works with latest git mpv version and without any config.

**Comment by Kreijstal** [comment]
> Dunno then, for me yt links works with latest git mpv version and without any config.

 Oh so it's just a release too old? Are you using mingw to compile it?

**Comment by richardpl** [comment]
Well I use latest ytdl script and mpv and other libs, but that is probably unrelated to this issue.

**Comment by Kreijstal** [comment]
huh, the bug is gone?

**Comment by Kreijstal** [comment]
I guess it was a new release
