### ISSUE TITLE
The cursor doesn't autohide after double clicking to enter or exit fullscreen.

### ISSUE THREAD

**Issue by LampPrinter** [mpv-player/mpv#13777]
**mpv version**

`mpv v0.37.0-668-g6a47bc8f24 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Mar 28 2024 05:53:12
libplacebo version: v6.338.2
FFmpeg version: 6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100`

**macOS Version**
Sonoma 14.4.1 

**Source of the mpv binary or bundle**
Homebrew

**If known which version of mpv introduced the problem**
No

**Possible screenshot or video of visual glitches**

https://github.com/mpv-player/mpv/assets/7559328/c9a02245-dbf7-4277-b154-df061c4961bf

### Reproduction steps
After double clicking to enter fullscreen. The cursor stops autohiding. Same happens when exiting from fullscreen. If I do a single click anywhere on video, autohide starts working again.

### Expected behavior
The cursor autohides.

### Actual behavior
It doesn't.

### Log file
With flag --msg-level=input=trace

[mpv.log](https://github.com/mpv-player/mpv/files/14782542/mpv.log)

**Comment by Akemi** [comment]
will be fixed with #13781. it's something i broke with the recent input handling refactor.
