### ISSUE TITLE
secondary-sub-delay option not found

### ISSUE THREAD

**Issue by jungkyuk** [mpv-player/mpv#13783]
### Important Information

Provide following Information:
**mpv Version**: 
mpv-0.37.0

**macOS Version**:
12.5.1

**Source of the mpv binary or bundle:**
The latest third-party build at https://laboratory.stolendata.net/~djinn/mpv_osx/

**If known which version of mpv introduced the problem**
Don't know

**Hardware**
2021 M1 Macbook Pro 14"

### Reproduction steps
Run `mpv {mediafile} --sid=1 --secondary-sid=2 --secondary-sub-delay=1` in terminal

### Expected behavior
Secondary sub should have a sub delay

### Actual behavior
I get this in the terminal: 
`Error parsing option secondary-sub-delay (option not found)`
`Setting commandline option --secondary-sub-delay=1 failed.`
`Exiting... (Fatal error)`

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/14801059/log.txt)

### Sample files
I think think this is file agnostic since the option itself doesn't exist and happens for all my files.

I'm pretty new to using the cli for mpv so I hope I'm not being stupid. I thought secondary-sub-delay was supported from the mpv docs but am I using a build that doesn't have it?

**Comment by CounterPillow** [comment]
It's not in a tagged release yet, just in git. See https://github.com/mpv-player/mpv/blob/master/DOCS/interface-changes.rst#interface-changes

**Comment by jungkyuk** [comment]
Oh, so there's no way to use the option until v0.38.0 is released?

**Comment by CounterPillow** [comment]
There is: build from git.

Otherwise, no.
