### ISSUE TITLE
ytdl-raw-options local path

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#13787]
I'm trying to make mpv locate my youtube cookies from the same folder as mpv, so not using the long path like `C:/Users/test/mpv/youtubecookies.txt`, rather use something like `~~\youtubecookies.txt`

Trying 
```
ytdl-raw-options=mark-watched=,cookies="~~\youtube.txt",playlist-end=100
```
does not work.

Is it even possible?

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/9352

**Comment by guidocella** [comment]
You can either set all options in the script or use `ytdl-raw-options-append=mark-watched` `ytdl-raw-options-append=playlist-end=100`.

**Comment by guidocella** [comment]
Actually you need to do the opposite because scripts run after parsing `mpv`.conf. Set `ytdl-raw-options=mark-watched=,playlist-end=100` in `mpv.conf` and run `mp.command('change-list ytdl-raw-options append cookies=' .. mp.command_native({'expand-path', '~~/cookies.txt'}))`

**Comment by guidocella** [comment]
`no-osd change-list`

**Comment by guidocella** [comment]
`mp.commandv('change-list', 'ytdl-raw-options', 'append', 'cookies=' .. mp.command_native({'expand-path', '~~/cookies.txt'}))`
