### ISSUE TITLE
Cannot play animated WEBP created by ffmpeg

### ISSUE THREAD

**Issue by tkzv** [mpv-player/mpv#13789]
### Important Information

Provide following Information:
- mpv version: 0.37.0
- Linux Distribution and Version: Gentoo Linux
- Source of the mpv binary: built from source with media-video/mpv-0.37.0 ebuild (latest stable)
- If known which version of mpv introduced the problem: no information
- Window Manager and version: kde-plasma/plasma-meta-5.27.11
- GPU model, driver and version: Radeon HD 6950, driver from kernel 5.15.32
- Possible screenshot or video of visual glitches: n/a

### Reproduction steps

1. Unpack the attached [Rotating_earth_(large).webp.zip](https://github.com/mpv-player/mpv/files/14807987/Rotating_earth_.large.webp.zip)
2. Try to run the animation in mpv: `mpv --no-config Rotating_earth_\(large\).webp`

The animation was converted from GIF to WEBP out of https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_(large).gif using ffmpeg with default settings: `ffmpeg -i Rotating_earth_(large).gif Rotating_earth_(large).webp`

### Expected behavior

MPV should play the animation should play like it does for similarly created WEBM or static WEBP files.

### Actual behavior

Nothing is shown. The console output is (with repeating messages skipped):
```
[ffmpeg/video] webp: skipping unsupported chunk: ANIM
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
....
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: image data not found
[ffmpeg/demuxer] webp_pipe: Could not find codec parameters for stream 0 (Video: webp, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
 (+) Video --vid=1 (webp 1.000fps)
[ffmpeg/video] webp: skipping unsupported chunk: ANIM
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
....
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: image data not found
Error while decoding frame!
Exiting... (Errors when loading file)
```

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/14807971/output.txt).

### Sample files

Animation archived to bypass GitHub limitations: [Rotating_earth_(large).webp.zip](https://github.com/mpv-player/mpv/files/14807987/Rotating_earth_.large.webp.zip)
The original image is https://upload.wikimedia.org/wikipedia/commons/2/2c/Rotating_earth_(large).gif

**Comment by tkzv** [comment]
Doesn't work for ffplay.

**Comment by guidocella** [comment]
https://trac.ffmpeg.org/ticket/4907

**Comment by richardpl** [comment]
supported in librempeg.
