### ISSUE TITLE
Korean subtitles are displayed abnormally.

### ISSUE THREAD

**Issue by CornFromHell** [mpv-player/mpv#13793]
![Figure Status Update - OpenAI Speech-to-Speech](https://github.com/mpv-player/mpv/assets/147477877/e1b4fc77-fc5a-448a-bc0c-6e9ffc911ea4)

In MPV 0.37.0, UTF8-encoded Korean subtitles are output as unreadable characters. It worked fine until 0.36.0-274 (Sep 2023), but I don't know at what point after that the problem started.

I have attached the video and subtitle files to the link below.
https://www.mediafire.com/file/eq8cuwatww4vyby/Figure_Status_Update_-_OpenAI_Speech-to-Speech_Reasoning.zip/file

Information:
- mpv version: 0.37.0.561
- Windows Version: Windows 10 Pro 64bit intel (v10 b19045)
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/
- GPU model, driver and version: NVIDIA GT 1030, v31.0.15.3623

**Comment by avih** [comment]
What is the actual issue at the screenshot? the three "X inside square" symbols? at which timestamp do you observe these?

I tried using the latest (shinchiro's) windows build, and I don't get these X symbols.

Maybe it's just your font missing some glyphs?

**Comment by llyyr** [comment]
Can't reproduce on Linux with mpv and ffmpeg build from master either. You need to provide a log file

**Comment by CornFromHell** [comment]
@avih Already checked. Even if I change the settings to a different font, the same problem occurs.
