### ISSUE TITLE
command loadfile: argument index has incompatible type

### ISSUE THREAD

**Issue by holgerlembke** [mpv-player/mpv#13806]
### Important Information

Provide following Information:
- mpv v0.37.0-709-g765a43a0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
- W10
- updated via "update.bat"

### Reproduction steps

I start mpv with 

```
C:\Program Files\mpv\mpv.exe https://mcdn.one.ard.de/ardone/hls/master.m3u8 --vid=3 --aid=auto --auto-window-resize=no --input-ipc-server=\\.\pipe\mpv-pipe --idle
```

This starts the stream fine. Later I send the following command:

```
{"command":["loadfile","https://mcdn.one.ard.de/ardone/hls/master.m3u8","replace",{"vid":"3","aid":"auto","force-window":"yes"}]}
```
That should, in my theories, just play the same stream like the command line call. But it gives me a red "command loadfile: argument index has incompatible type."

In case I remove the vid/aid/fw-stuff to 

```
{"command":["loadfile","https://mcdn.one.ard.de/ardone/hls/master.m3u8","replace"]}
```
it works fine, but of course I loose the ability to switch resolution/audio stream.

This behavior is sort of new, started with recent updates, I send this command a looong time and it worked fine before.

Any ideas?

**Comment by holgerlembke** [comment]
I get the feeling that my command line was never a valid thing and only worked because, well, no so strict checks.

Could it be?

**Comment by Sneakpeakcss** [comment]
Around a month ago syntax for [loadfile](https://mpv.io/manual/master/#command-interface-[%3Coptions%3E]]]) was changed and options moved to 4th position.

https://github.com/mpv-player/mpv/issues/13656

**Comment by holgerlembke** [comment]
I'm confused.

My options are at the fourth position. Are they incorrectly formatted?

**Comment by holgerlembke** [comment]
Ok, I switched to that solution now: send two command.

```
{"command":["loadfile","https://zdf-hls-15.akamaized.net/hls/live/2016498/de/high/master.m3u8","replace"]}
{"command": ["set_property", "vid", 5]}
```

**Comment by Sneakpeakcss** [comment]
> I'm confused.
> 
> My options are at the fourth position. Are they incorrectly formatted?

4th argument. If that command worked previously then adding `-1` after `replace` should make it function like it did before:

```
{"command":["loadfile","https://mcdn.one.ard.de/ardone/hls/master.m3u8","replace",-1,{"vid":"3","aid":"auto","force-window":"yes"}]}
```
