### ISSUE TITLE
Global Media Keys

### ISSUE THREAD

**Issue by Lc4B** [mpv-player/mpv#13813]
A while ago I switched to mpv as my main player, so now I use it for practically everything, video player, music player, streaming player and TV. On a daily/work basis I often use macros and it is counterproductive and annoying to have to interrupt them to interact with mpv (and then rearrange everything), and even in gaming there are times when you cannot switch windows to simply change songs or pause.
So I wanted to ask if global multimedia keys can be implemented, considering that many keyboards now have dedicated media keys and I consider it a very useful feature (present in many worse players) unfortunately missing in mpv.

Thanks for the attention  :)

**Comment by guidocella** [comment]
They are already implemented on Windows and macOS. On other platforms you can bind keys that control mpv via https://mpv.io/manual/master/#json-ipc

**Comment by Lc4B** [comment]
> They are already implemented on Windows and macOS. On other platforms you can bind keys that control mpv via https://mpv.io/manual/master/#json-ipc

I'm on windows, both 10 and 11, and globals don't work. I don't know if I need to set some particular parameters but I couldn't find anything in the manual

**Comment by guidocella** [comment]
It's not implemented, I thought that was the point of `--input-media-keys` but apparently it just affects the focused mpv window.
