### ISSUE TITLE
How to change the duration of auto-hide when the mouse hover progress bar loses focus in MPV?

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#13819]
### Important Information

How to change the duration of auto-hide when the mouse hover progress bar loses focus in MPV?

Provide following Information:
- mpv version 0.37 Latest Builds
- Windows Version 10

**Comment by zhouxinghong** [comment]
![image](https://github.com/mpv-player/mpv/assets/54253524/70cf6299-cb1e-4949-8d0a-7109f679c579)

**Comment by zhouxinghong** [comment]
Supplement:
How to always hide the top title bar. This place has been changed many times, and with the recent version the title bar appears again, and the previous settings are completely disabled.
![image](https://github.com/mpv-player/mpv/assets/54253524/85a6bd2f-c851-40fc-8872-17f6c30a6bb7)

**Comment by zhouxinghong** [comment]
Previously set properties are completely disabled

**Comment by zhouxinghong** [comment]
mpv version 0.37 Latest Builds
Windows Version 10

**Comment by llyyr** [comment]
https://mpv.io/manual/master/#on-screen-controller-hidetimeout

https://mpv.io/manual/master/#on-screen-controller-windowcontrols

**Comment by zhouxinghong** [comment]
I have set `hidetimeout=5000` and `windowcontrols` but it doesn't work. Can you give an example? Maybe my settings are wrong.
https://github.com/mpv-player/mpv/issues/13725

**Comment by zhouxinghong** [comment]
I have set `hidetimeout=5000` and `windowcontrols` but it doesn't work. Can you give an example? Maybe my settings are wrong.

The `windowcontrols` setting is valid in the version about a week ago, and the version built on April 4, 2024 is no longer valid.

**Comment by llyyr** [comment]
`script-opts=osc-hidetimeout=5000,osc-windowcontrols=no`

**Comment by zhouxinghong** [comment]
After using your settings, it still doesn't work. When the mouse focus moves into the player, the top title bar will be displayed immediately. In the past, the top title bar could always be hidden.

In addition, script-opts=osc-hidetimeout=5000 also does not work. When the mouse focus moves out of the player, the progress bar panel will disappear immediately without a delay of 5 seconds.

**Comment by sunpenghao** [comment]
> When the mouse focus moves into the player, the top title bar will be displayed immediately.

Are you sure you set `script-opts=osc-windowcontrols=no`?

> When the mouse focus moves out of the player, the progress bar panel will disappear immediately without a delay of 5 seconds.

This is hard-coded behavior at the moment.

**Comment by zhouxinghong** [comment]
My setup is as follows:
script-opts=osc-hidetimeout=5000
script-opts=osc-windowcontrols=no

There should be no errors with such a setup. But it doesn't work.

In addition, I hope that the progress bar can be set to delay 3 to 5 seconds before automatically hiding like other players, but currently  script-opts=osc-hidetimeout=5000  does not work.

**Comment by sunpenghao** [comment]
> script-opts=osc-hidetimeout=5000
> script-opts=osc-windowcontrols=no

`script-opts` is a [key/value list option](https://mpv.io/manual/master/#list-options), so the second `script-opts` will override the first one (i.e., only `osc-windowcontrols=no` takes effect). You need to put them in a single line: `script-opts=osc-hidetimeout=5000,osc-windowcontrols=no`.

Or you can use `script-opts-add` instead if you don't want the option to get too long:

```
script-opts-add=osc-hidetimeout=5000
script-opts-add=osc-windowcontrols=no

**Comment by zhouxinghong** [comment]
@sunpenghao Thank you very much for your careful guidance! 🎉😜I'll try it again later your way. . .

**Comment by zhouxinghong** [comment]
@sunpenghao I want to ask the teacher one more question! Is there any good audio renderer available for MPV? Due to the poor sound quality of MPV, it has always been a pain point! 😂

**Comment by sunpenghao** [comment]
On Windows mpv uses WASAPI event mode by default. There's not really any "better" audio renderer out there.

**Comment by zhouxinghong** [comment]
@sunpenghao Thank you very much teacher! 🎉😜

**Comment by zhouxinghong** [comment]
@sunpenghao Hello, teacher! I found that after enabling profile=high-quality on Windows 10 system, the image quality and clarity of MPV are still not as good as VLC. may I know what is the reason?
