### ISSUE TITLE
Beginning of video is skipped if video filter initialization fails because of hardware decoding

### ISSUE THREAD

**Issue by bergfried** [mpv-player/mpv#1381]
Running something like

```
mpv --hwdec=vdpau --vf=pp test.mp4
```

triggers a video filter initialization error in my case:

```
Image formats incompatible.
Video filter chain:
 [vd] 512x280 vdpau Autoselect/Autoselect CL=mpeg2/4/h264
 [in] 512x280 vdpau BT.601 (SD)/TV CL=mpeg2/4/h264
 [scale] ??? [a]   <---
 [pp] ???
 [out] ???
Cannot initialize video filters.
Error using hardware decoding, falling back to software decoding.
```

The error itself is _not_ the issue here. The issue is that iff this happens, the first few seconds of the video are sometimes skipped. The actual amount of time skipped depends on the video and seems to be fixed for any given video. I can even see the elapsed time jumping ahead when playback is paused and I am switching between files in the playlist.

If I remember correctly, this has already occured in 0.7.1.

**Comment by wm4** [comment]
This was probably fixed some years ago (or not).
