### ISSUE TITLE
sub-blur option has no effect on subtitles

### ISSUE THREAD

**Issue by Kruasys** [mpv-player/mpv#13820]
No matter what value I put in `sub-blur`, it has no effect on subtitles at all, `sub-border-size` set to 0. Trying to get softer looking subtitles because by default they are too sharp, not sure how exactly `sub-blur` option supposed to work, can't find much anywhere about it

Full mpv.conf:
```
sub-ass-override=force
sub-blur=5
sub-border-size=0
sub-shadow-offset=3
sub-shadow-color=0/0/0/1
```

![mpv_dihEKnwBzr](https://github.com/mpv-player/mpv/assets/16331256/3f3b7558-44a5-4328-9b35-04ad6b7672e0)

**Comment by Kruasys** [comment]
Solved using `sub-ass-style-overrides=blur=1`

**Comment by llyyr** [comment]
That's just a workaround, sub-blur should still work directly and it indeed doesn't work currently

**Comment by hooke007** [comment]
It previously would blur font without border while blur border  instead as if border siez > 0.
When it was broken?

**Comment by hooke007** [comment]
Should it follow the behav of the same tag in libass?

>Be aware that this tag blurs the edges of the text, not everything. This means that if the text has a border (set with [\bord](https://aegisub.org/docs/latest/ass_tags/#borderwidth)) the border will be blurred, but if there is no border, the main text will be blurred instead.

**Comment by llyyr** [comment]
> It has been like this since at least 0.29 from my testing.

Did you try downgrading libass? According to this issue, it worked on 0.34.1 at least https://github.com/mpv-player/mpv/issues/10784 given that you set `sub-border-size=0`

**Comment by pxeemo** [comment]
Have the same issue in mpv 0.39 

> Solved using `sub-ass-style-overrides=blur=1`

This method doesn't work out for me
