### ISSUE TITLE
add some sort of basic ivtc to mpv

### ISSUE THREAD

**Issue by gaitas13** [mpv-player/mpv#13824]
### Expected behavior of the wanted feature

it would be nice to have naive ivtc on mpv, even if is only 3:2

**Comment by CounterPillow** [comment]
Might be possible with https://ffmpeg.org/ffmpeg-filters.html#fieldmatch + decimate?

**Comment by sfan5** [comment]
also https://ffmpeg.org/ffmpeg-filters.html#pullup-1

**Comment by Enivex** [comment]
This does not work for mixed content unfortunately (Like every old sci fi show). Using `decimate:mixed=true` in mpv causes a black screen for me.

I would greatly appreciate having this built into mpv, because it would mean I could play DVD remuxes directly instead of having to reencode them first.
