### ISSUE TITLE
Can the OSD information panel provide a Chinese version? Thank you

### ISSUE THREAD

**Issue by laodaoxp** [mpv-player/mpv#13828]
Stats.lua
Can the OSD information panel provide a Chinese version? Thank you

![4K美女烤鸭赏析 mp4-00_01_22 149-0003](https://github.com/mpv-player/mpv/assets/162548755/b0ee18c8-d047-4741-b1a7-7afff3c9712f)

**Comment by sfan5** [comment]
The mpv project intentionally does not provide localization.
Feel free to make your own modifications to scripts or find someone who has already done that.

**Comment by laodaoxp** [comment]
已经解决
setting：
mpv.conf
load-stats-overlay=no   

[stats.zip](https://github.com/mpv-player/mpv/files/14913031/stats.zip)
put  stats.lua into:
\portable_config\scripts

**Comment by laodaoxp** [comment]
已经解决
setting：
mpv.conf
load-stats-overlay=no   

[stats.zip](https://github.com/mpv-player/mpv/files/14913031/stats.zip)
put  stats.lua into:
\portable_config\scripts
