### ISSUE TITLE
How can I disable the acceleration when holding the arrow keys?

### ISSUE THREAD

**Issue by aljustiet** [mpv-player/mpv#13821]
When I hold the arrow keys, it starts accelerating every minute. How can I disable it and seek 5 seconds only?

**Comment by laodaoxp** [comment]
请上传你的 input.conf

**Comment by laodaoxp** [comment]
请上传你的 input.conf
谢谢

**Comment by aljustiet** [comment]
> 请上传你的 input.conf 谢谢
mpv.conf:
```
# normal top-level option
fullscreen=yes
osd-on-seek=msg-bar

# a profile that can be enabled with --profile=big-cache
[big-cache]
cache=yes
demuxer-max-bytes=123400KiB
demuxer-readahead-secs=20

[slow]
profile=high-quality

[fast]
vo=vaapi

# using a profile again extends it
[slow]
framedrop=no
# you can also include other profiles
hr-seek-precise-normal=yes
```, 
input.conf:
```
RIGHT no-osd seek  5 exact
LEFT  no-osd seek -5 exact
```

**Comment by aljustiet** [comment]
> 请上传你的 input.conf 谢谢

input.conf:
```
RIGHT no-osd seek  5 exact
LEFT  no-osd seek -5 exact
```

**Comment by laodaoxp** [comment]
Did you use this script?
portable_config\scripts\inputevent.lua ？

Do you have the following or similar settings?
input.conf：
RIGHT           seek 5                                        #@click
RIGHT           script-message-to evafast speedup             #@press
