### ISSUE TITLE
mpv lacks support for HEVC in non-standard FLV.

### ISSUE THREAD

**Issue by delhi2050** [mpv-player/mpv#13827]
Currently, there are two standards for supporting HEVC codec in FLV container:

1. The Chinese industry standard achieves HEVC support by adding codecid = 12.

2. enhanced-rtmp is a standard submitted by VSO and officially supported by FFmpeg.

As Chinese websites mostly adopt the first standard, there is a need to add support for the FLV format based on this standard.

The current support status for the first standard is as follows:

| |codecid=12|enhanced-rtmp|
|:----|:----|:----|
|mpv|❌|✔|
|MediaInfo |✔|❌|
|FFmpeg|❌|✔|
|VLC|❌|❌|
|MKVToolNix|✔|❌|
|PotPlayer|✔|✔|

Implementation:

patching FFmpeg with 
https://github.com/yt-dlp/FFmpeg-Builds/blob/e7017535a30a321d2afa313e8e2420b2a76619a1/patches/ffmpeg/master/0001-Nonstandard-HEVC-over-FLV.patch

Test video files: 

https://github.com/delhi2050/flv-hevc-test-video

**Comment by zhongfly** [comment]
By your instructions, it is necessary to build mpv with a patched ffmpeg, but mpv does not distribute any official binaries. You may need to build mpv on your own to support non-standard FLV.

**Comment by llyyr** [comment]
> I mean to make mpv support non-standard HEVC-over-FLV through patching FFmpeg or other possible methods.

So do it? As you've been told, mpv doesn't distribute any binaries. You can compile your own binary, or try to upstream that patch.

**Comment by kasper93** [comment]
> patching FFmpeg with https://github.com/yt-dlp/FFmpeg-Builds/blob/e7017535a30a321d2afa313e8e2420b2a76619a1/patches/ffmpeg/master/0001-Nonstandard-HEVC-over-FLV.patch

Send the patch to [ffmpeg-devel@ffmpeg.org](mailto:ffmpeg-devel@ffmpeg.org) and discuss it there.

There is nothing to change/fix in mpv itself.
