### ISSUE TITLE
Cut/Split Videos and Make Image Sequences 

### ISSUE THREAD

**Issue by Jay123210599** [mpv-player/mpv#13833]
How do I cut, trim, or split videos using mpv? I also want to make image sequences out of the selected fragments. How do I do that? Are there plugins for these tasks?

**Comment by sfan5** [comment]
mpv is not a video editor. Nevertheless there may be [user scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts) that can perform these tasks.
