### ISSUE TITLE
Loop play or list play takes up double the video memory when switching

### ISSUE THREAD

**Issue by InnovatorSteve** [mpv-player/mpv#13854]
### Important Information

mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.7-0ubuntu0.1
GPU:VAAPI libva2.4 

mpv --hwdec=vaapi --vo=gpu *.mp4

Can I turn off using double video memory?
At the time of switching, it seems that the memory is applied first, and then the previous memory is released, so there will be a short time mpv takes up double the video memory, which may cause my GPU video memory to be insufficient and fall back to the soft solution, which makes me very upset.

**Comment by InnovatorSteve** [comment]
[Uploading output.txt…]()

**Comment by InnovatorSteve** [comment]
log file:https://wwk.lanzouo.com/iUBPE1ukmp7g

**Comment by sfan5** [comment]
> mpv 0.32.0

There is no support for 4 years out of date software.
