### ISSUE TITLE
keybind in `input.conf` that will run powershell script?

### ISSUE THREAD

**Issue by Obegg** [mpv-player/mpv#13858]
title may sound stupid, yes, but hold on, let me explain.
i use one of those cheap aliexpress remote keyboard and mouse kind of things that have limited buttons on them,
and i was wondering if it is possible to make it so if i click `a` (for simplicity - this is an example of a keypress) it will run a powershell script (which in it i will add a different keypress which is not present on the remote keyboard).
so basically i will press `a` on the remote keyboard, that will run a powershell script, that will send `b` keypress.
in other words - key remapping.
i am aware such solution do exist in 3rd party programs such as `powertoys`, but i am really curious if what i'm asking is possible, this will save me a lot of time and hassle with different remote keyboard which have different layouts and limited buttons so if for example i buy a new remote keyboard which have different layout i can just customize the keyboard from the `input.conf` (or userscript) file instead of 3rd party software.

edit 1:
i already have the powershell section of the userscript (if not possible using `input.conf`):
```
mp.command_native({
name = 'subprocess',
capture_stdout=true,
args = { 
	'powershell', 
	'-NoProfile',
	'-Command', 
	'$wshell = New-Object -ComObject wscript.shell; $wshell.SendKeys(\'%{TAB}\')' 
}
```
(yes, i will change `$wshell.SendKeys(\'%{TAB}\')' ` to whatever the desired key should be)
i just need to add `if keypress a` somehow...

**Comment by Hrxn** [comment]
Try this, please

`input.conf`
```
a script-message-to customkeys alt-tab
```

`customkeys.lua`
```lua
mp.register_script_message('alt-tab', function ()
    mp.command_native({
        name = 'subprocess',
        capture_stdout=true,
        args = { 
            'powershell', 
            '-NoProfile',
            '-Command', 
            '$wshell = New-Object -ComObject wscript.shell; $wshell.SendKeys(\'%{TAB}\')'
        }
    })
end)

```

**Comment by aloola18** [comment]
@Obegg that script works for me
