### ISSUE TITLE
Jump by Keyframe Next/Prev Feature

### ISSUE THREAD

**Issue by selvinjack** [mpv-player/mpv#13855]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature

I have generated keyframes using ffmpeg and want to jump to each keyframe to copy timestamps.

video example: 

https://github.com/mpv-player/mpv/assets/83247692/38c3c4b5-96f6-442e-922c-a83e257f06d0

I want to jump, keyframe by keyframe, like in LosslessCut

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/2380
