### ISSUE TITLE
how get rid of ortho, lanczos, hermite up-downscalling

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#13852]
Hi, I was trying the latest mpv release and some additional stuff in the pipeline is showing up: ortho, lanczos, hermite, I don't want anything of this. I didn't set it up like this.
How can I deactivate it?
latest 37 build (shinchiro)
![mpv](https://github.com/mpv-player/mpv/assets/139760266/d16eff9e-85ca-4f98-8205-7c62bd1c128a)

36 version
![mpv before](https://github.com/mpv-player/mpv/assets/139760266/23b69f43-cf17-433a-a41f-c0a532eae5da)

Thanks for any help :)

**Comment by CounterPillow** [comment]
`--profile=fast`

**Comment by geextahslex** [comment]
Thank you :)
