### ISSUE TITLE
video cropping filter

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#13868]
Hi, is there any cropping video functionality in mpv? I would like to set keys to crop pixels in sync left/right or in sync top/bottom. I'm not talking about apect ratio like (shift+a) I mean something more flexibel, for example if there are some bad pixel lines that you wanna cropp out. Or maybe a video frame that is distracting you. I hope this makes sense.
I remember there was something like this in vlc (croppadd).

Thank you :)

![video-and-filters-and-croppadd-filter-on-windows](https://github.com/mpv-player/mpv/assets/139760266/49bf6794-4c6f-4b94-8851-1c29ee3c4c8c)

**Comment by kasper93** [comment]
`--video-crop`

https://mpv.io/manual/master/#options-video-crop

**Comment by geextahslex** [comment]
okay nice, I'm a bit confused by all the variables. How to set this up in input.conf? ^^
