### ISSUE TITLE
Bad detection of Retina resolution with mpv on macOS

### ISSUE THREAD

**Issue by Elrohir-Culnamo** [mpv-player/mpv#13861]
Screen resolution detection is incorrect

The resolution shown in `Display` is 1920x1080 and should be 3840x2160

older intel version:

<img width="1016" alt="Capture d’écran 2024-04-11 à 18 12 19" src="https://github.com/mpv-player/mpv/assets/134109601/cb8f2918-40df-42a2-8e22-6329ee7072d9">

latest version: 

<img width="536" alt="Capture d’écran 2024-04-11 à 18 12 46" src="https://github.com/mpv-player/mpv/assets/134109601/fdbe45a8-9d44-4f28-b41d-add4493df367">

### Important Information

Provide following Information:
- mpv version a6c38b93a2182d62a8d9b9c9bc73f18a81f24bef
- macOS Version : Sonoma 14.4.1

### Reproduction steps

Open a video

### Expected behavior

The resolution shown in `Display` should be 3840x2160

### Actual behavior

The resolution shown in `Display` is 1920x1080

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/14949502/mpv.log)

**Comment by kasper93** [comment]
`--hidpi-window-scale` has be disabled by default as part of https://github.com/mpv-player/mpv/pull/13478

Use `--hidpi-window-scale=yes` to restore old behavior.

**Comment by Elrohir-Culnamo** [comment]
> Use `--hidpi-window-scale=yes` to restore old behavior.

Thanks, it works perfectly as before

**Comment by Dudemanguy** [comment]
Sure but `--hidpi-window-scale` shouldn't affect the detection of the actual display resolution though right? Unless it's some macOS thing.
