### ISSUE TITLE
Comparison of different player screens for the same video

### ISSUE THREAD

**Issue by laodaoxp** [mpv-player/mpv#13862]
The image decoded by MPV
The picture decoded by potplayer+MadVR
Please refer to the comparison pictures. On the left is the MPV player, and on the right is the potplayer
![000](https://github.com/mpv-player/mpv/assets/162548755/091c1540-0ab3-49a9-833b-cebb80938de4)

The following are the configuration files and test videos
mpv.conf：
[mpv.zip](https://github.com/mpv-player/mpv/files/14953353/mpv.zip)
test.240 - 1000.mkv
[test.240 - 1000.zip](https://github.com/mpv-player/mpv/files/14953356/test.240.-.1000.zip)

Is there a way to submit the rendering quality of the MPV renderer?

**Comment by llyyr** [comment]
Follow the issue template and see if you can reproduce the issue with `--no-config` and produce a log file if you can.

> .rw-r--r-- llyyr users  96 KB 3 days ago   mpv.conf

Nobody is going to sort through your 96KB config file to figure out what went wrong.

**Comment by netExtra** [comment]
It's basically a calibration issue. I don't know if you changed your brightness/contrast/saturation/gamma settings for Potplayer but you will need to modify similar settings for mpv.
