### ISSUE TITLE
Is it possible to OCR playing video using OCR backend like Tesseract

### ISSUE THREAD

**Issue by gunir** [mpv-player/mpv#13864]
I'm trying to make mpv OCR a video to detect subtitles and translate to another window, mostly for watching movies that I don't understand and language learning, but the issue is I can't find API to capture screen to memory, or even more important, capture region to memory (to make OCR more accurate and cost less resource, because smaller = faster ? Is there APIs like that ?

**Comment by cold-nagai** [comment]
It'd be better to translate subtitles beforehand via whisper. https://github.com/abb128/LiveCaptions Also exists.
