### ISSUE TITLE
glsl shader "#include" compatibility

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#13877]
Hi, I try to get a glsl shader working that has #include functions. I'm not sure if mpv supports that. Has someone an idea?

Is there a place where you can interact with people who know glsl shaders for mpv? as glsl shaders in general are used in other places like OpenGL 3D engines etc. and the people there are often confused about the use case in mpv (with hooks etc.)

This is the shader

```
//!HOOK MAIN
//!BIND HOOKED
//!DESC Vibrance smooth 

#include "mmax.glsl"
#include "mmin.glsl"
#include "luma.glsl"

#ifndef FNC_VIBRANCE
#define FNC_VIBRANCE
vec3 vibrance(in vec3 v, in float vi) {
    float max_v = mmax(v);
    float min_v = mmin(v);
    float sat = max_v - min_v;
    float lum = luma(v);
    return mix(vec3(lum), v, 1.0 + (vi * 1.0 - (sign(vi) * sat)));
}

vec4 vibrance(in vec4 v, in float vi) { return vec4( vibrance(v.rgb, vi), v.a); }
#endif
```

**Comment by kasper93** [comment]
You can preprocess shader files yourself. mpv/libplacebo will not provide this functionality. Shaders are passed as strings, there is no reference to filesystem.

**Comment by haasn** [comment]
Try with `#extension GL_GOOGLE_include_directive: require`. You probably also need to use absolute paths.

**Comment by geextahslex** [comment]
Is there a place where you can interact with people who know glsl shaders for mpv? as glsl shaders in general are used in other places like OpenGL 3D engines etc. and the people there are often confused about the use case in mpv (with hooks etc.)

**Comment by kasper93** [comment]
You can try https://github.com/haasn/libplacebo/discussions 😉 or #mpv or #libplacebo on irc.libera.chat. I guess here is fine too, but creating full issue for simple questions is not productive, you probably will get faster answer on IRC.

**Comment by geextahslex** [comment]
>You can preprocess shader files yourself

what does this mean? I don't understand glsl shaders

**Comment by kasper93** [comment]
You can process your files before passing them to mpv. With `gcc -E` or some python script or anything really to include  the code of other files into one.

**Comment by geextahslex** [comment]
>You can try https://github.com/haasn/libplacebo/discussions 😉 or #mpv or #libplacebo on irc.libera.chat

okay I tried irc, reddit, discord, github, khronos forum. yeah no luck with that ^^'
