### ISSUE TITLE
how to get video-crop working?

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#13875]
Hi, I tried to use video-crop but there are no results. I don't know what I'm doing wrong. I'm using `hwdec=no` and
`vo=gpu-next` if it matters.

Thank you :)

I tried this
```
video-crop=800:800
video-crop=800x800
video-crop=50x50+50+50
```

**Comment by kasper93** [comment]
> I don't know what I'm doing wrong.

We also don't know, because you didn't provide log file.

**Comment by kasper93** [comment]
Feel free to reopen with more info.

**Comment by geextahslex** [comment]
@kasper93 How do I reopen?

Here is the logfile:
[output.txt](https://github.com/mpv-player/mpv/files/14999654/output.txt)
Commandline screenshot:
![dsdsdsds](https://github.com/mpv-player/mpv/assets/139760266/1bd44a5a-176f-45f2-8327-1fe44133e892)

**Comment by kasper93** [comment]
What version of mpv you are using? Looks like older one without `video-crop` support, otherwise should work.

**Comment by kasper93** [comment]
Use v0.37.0 or newer. `video-crop` has been added between v0.36.0 and v0.37.0

**Comment by geextahslex** [comment]
Oh sorry, now I see that it works in 37. I didn't thought that crop was a new feature.
