### ISSUE TITLE
macOS-bundle Code Signing Fails if Parent Directory has a Space

### ISSUE THREAD

**Issue by sandlst** [mpv-player/mpv#13872]
### Important Information

Provide following Information:
- mpv version
e42a8d537f575cf61747e9f67c5a9e34f511cb2b
- Platform and Version
macOS Sonoma 14.4.1
- meson version
1.4.0

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases
on git master

### Reproduction steps

Code Signing steps fail while running
`meson compile -C build macos-bundle`

The bundle is still created, but crashes with a CodeSign error immediately upon opening.

If the mpv directories full path contains no spaces, the Code Signing is successful.

### Expected behavior
Expected behavior is for the bundle to be able to be Code Signed even if a parent directory has a space in it.
### Actual behavior
The bundle is created but since the Code Signing did not complete it crashes immediately after opening.
### Log file
I have attached the meson-log.txt file but after taking a peek I do not think it will be helpful for this; the initial
`meson compile -C build`
completes with no issues and provides a fully working binary.
I have attached the standard output of a good (no spaces) macos-bundle build, and a bad (parent directory has a space) one where it looks like it is trying to code sign the dylibs but the path stops at the first space so it just shows
`no such file or directory`
over and over instead.
[meson-log.txt](https://github.com/mpv-player/mpv/files/14965556/meson-log.txt)

[bad.log](https://github.com/mpv-player/mpv/files/14965558/bad.log)
[good.log](https://github.com/mpv-player/mpv/files/14965559/good.log)

Without the log file, this issue will be closed for ignoring the issue template.

**Comment by Akemi** [comment]
will be fixed by #13874.
