### ISSUE TITLE
Why no stats.lua video subtitles 

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#13885]
Please add stats.lua default to show information about subtitles

**Comment by zhongfly** [comment]
https://github.com/mpv-player/mpv/pull/13866

**Comment by MyNameIsAnujRanjan** [comment]
> There is not much to say about subtitles, I've added a section as mentioned above, but currently it is only a type of subtitle track, nothing more.

What means it is only a type of subtitle track, nothing more . Can you take inspiration likemediainfo net

**Comment by kasper93** [comment]
> Can you take inspiration likemediainfo net

What would you want from it? track-info like language / title has no place in stats.lua, as they are not shown for video or audio either. For subtitles we are left for codec and that's about it.

**Comment by MyNameIsAnujRanjan** [comment]
> Maybe consider add the subtitle font style that is currently in effect.

May be sfan will update add everything here in mpv Androidnext

**Comment by kasper93** [comment]
Fixed by: #14330
