### ISSUE TITLE
Audio stuttering on macOS since v0.37.0

### ISSUE THREAD

**Issue by NextFire** [mpv-player/mpv#13880]
Possibly related issues/PRs:
https://github.com/mpv-player/mpv/issues/13676
https://github.com/mpv-player/mpv/pull/12643#issuecomment-1774264729
https://github.com/mpv-player/mpv/issues/13348

### Important Information

Provide following Information:
- mpv version: v0.37.0-775-g9030e6a7ad
- macOS Version: 14.4.1 (23E224)
- Source of the mpv binary or bundle: binary, compiled from source
- If known which version of mpv introduced the problem: v0.37.0
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

`mpv <any file> --no-config`

### Expected behavior

No audio stuttering.

### Actual behavior

Audio stutters every 20 to 60 seconds when playing any file.

I also get these kinds of errors in the macOS console:

- Healer Girl 05 (CR)
<img width="1440" alt="Capture d’écran 2024-04-13 à 17 17 37" src="https://github.com/mpv-player/mpv/assets/20094890/f24a41af-0261-4f27-be2d-f9da85147097">

- <a href="https://kara.yuru.moe/Aqours%20-%20LIVE%20-%20Mattete%20Ai%20no%20Uta%20(VIDEO%20Love%20Live!%20Sunshine!!%20Aqours%204th%20LoveLive!%20～Sailing%20to%20the%20Sunshine～%20Day%202)/Aqours%20-%20LIVE%20-%20Mattete%20Ai%20no%20Uta%20(VIDEO%20Love%20Live!%20Sunshine!!%20Aqours%204th%20LoveLive!%20～Sailing%20to%20the%20Sunshine～%20Day%202).mp4">Aqours - LIVE - Mattete Ai no Uta (VIDEO Love Live! Sunshine!! Aqours 4th LoveLive! ～Sailing to the Sunshine～ Day 2).mp4</a>
<img width="1440" alt="Capture d’écran 2024-04-13 à 17 21 35" src="https://github.com/mpv-player/mpv/assets/20094890/684cc984-b18f-457f-a68e-2f772316d037">

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/14968649/mpv.log)

(There were stutters at 0:30 and 0:40 but nothing relevant was logged)

### Sample files

N/A

**Comment by NextFire** [comment]
Sorry for the confusion, I believe 0.37 introduced the bug as I downgraded to 0.36 and I can't reproduce the issue

**Comment by m154k1** [comment]
Con you try reverting https://github.com/mpv-player/mpv/commit/36d5b5261282dd964f80cd2bb04bb53a7c6d895b and see if that helps?

**Comment by NextFire** [comment]
I can confirm reverting this commit resolved the issue

**Comment by Dudemanguy** [comment]
Probably worth reverting before the next release. I think there are various reports of audio issues that caused on macOS. cc @Akemi.

**Comment by Akemi** [comment]
i suppose we could do that. what was the reasoning behind using/introducing `ao_read_data_nonblocking`?

**Comment by kasper93** [comment]
It was introduced to avoid locking audio thread. /CC @t-8ch

**Comment by kasper93** [comment]
huh, just use `ao_read_data` at this point...

**Comment by Akemi** [comment]
> It was introduced to avoid locking audio thread. /CC @t-8ch

so it should possibly be reinvestigated in the future?

**Comment by t-8ch** [comment]
The nonblocking variant was introduced specifically for ao_pipewire as it uses a realtime audio thread, which should not be blocked.

I extended the usage to other AOs that are capable of reporting the actually available number of samples to the audio server.

If it does not work work for those other AOs should be fine to revert it.

**Comment by t-8ch** [comment]
I would be interested however why there is only one report so far.
(There was also one similar report for ao_pipewire)

It only seems to happen for very few people.

**Comment by NextFire** [comment]
Thank you!
