### ISSUE TITLE
dither green pattern

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#13881]
Hi I use dither (`dither-depth=8 dither=fruit`) It helpfs fixing artifacts etc. but it also introduces this weird green pattern which in itself prevents from ever having any real black on screen. 
What are your thoughts on this? are you using dithering? Is there any better technique? Do you also notice this in dark scenes?

Thanks for any suggestions :)

Screenshots, boosted luminance for demonstration purpose.
 dither off
![dither off 11](https://github.com/mpv-player/mpv/assets/139760266/ea5c9c99-bdab-4008-89cd-909e02c82228)
dither on
![dither on 111](https://github.com/mpv-player/mpv/assets/139760266/13620972-c98f-451c-8623-0388e9c1408d)

**Comment by haasn** [comment]
We solved a similar problem for deband grain, which turns itself off near black to avoid exactly this noise. Probably should do the same for dithering.

**Comment by geextahslex** [comment]
If its not compromising the visual quality, this sounds good

**Comment by geextahslex** [comment]
![dither inferno](https://github.com/mpv-player/mpv/assets/139760266/dd689463-6f35-4fae-a1dc-5d33b2425fd5)
![dither apocalypse](https://github.com/mpv-player/mpv/assets/139760266/fc70c129-4e84-4a00-bd22-bfb9d182bdca)

**Comment by kasper93** [comment]
Looks correct, no? What is it 2 or 3 bits?

**Comment by geextahslex** [comment]
Source is 10 bits (4kHDR)
my TV is 8 bits
my setting is `dither-depth=8 dither=fruit`

**Comment by kasper93** [comment]
> my setting is dither-depth=8 dither=fruit

Sorry, but I don't believe you. It is not possible to produce such dither pattern targeting 8-bits.

You need to state what is your problem and provide full reproduction steps with config and all the shaders you use.

Also this might be the case of https://xyproblem.info/ so please state your issue and current state of solving that issue.

**Comment by geextahslex** [comment]
>Sorry, but I don't believe you. It is not possible to produce such dither pattern targeting 8-bits.

but haasn stated above that 

>"We solved a similar problem for deband grain, which turns itself off near black to avoid exactly this noise. Probably should do the same for dithering."

I'm not sure what you mean by that. As I mentioned above "Screenshots, boosted luminance for demonstration purpose." to make it better visible.

>state what is your problem

(as mentioned above) dithering introduces this weird green pattern in shadow/dark areas which in itself prevents from ever having any real black on screen.

>full reproduction steps

watch 4k 10bit source on 8bit sdr monitor/tv with `dither-depth=8 dither=fruit`

I checked also a SDR 4k 10bits file to avoid using tonemapping, but it also has this pattern. This is raw mpv without any external glsl shaders etc.

![dither1sdfsdf](https://github.com/mpv-player/mpv/assets/139760266/9be384e0-cf2a-4401-8688-86a2eb2c9bb4)
![dither1 wewe](https://github.com/mpv-player/mpv/assets/139760266/b6ad6f1e-377d-4cfb-82ac-1b445514a224)

I can provide a logfile etc. if that helps

**Comment by geextahslex** [comment]
![zuzuz](https://github.com/mpv-player/mpv/assets/139760266/4272b49a-9ea6-4a23-bb3b-2b017e5429a0)
![zuzuz2](https://github.com/mpv-player/mpv/assets/139760266/d5e2e7a0-ccc4-4507-a194-5f1602b6bb6d)

**Comment by geextahslex** [comment]
@kasper93 is there any update or change or is it just closed?

**Comment by kasper93** [comment]
Issues tracker is not for discussions/questions, I've opened the other issue #14319.
