### ISSUE TITLE
Error opening/initializing the selected video_out (--vo) device. 

### ISSUE THREAD

**Issue by lamyergeier** [mpv-player/mpv#13893]
### Important Information

Provide following Information:
- mpv version: 0.37
- Linux Distribution and Version Fedora 39
- Source of the mpv binary:  homebrew
- If known which version of mpv introduced the problem: 0.37
- Window Manager and version: Gnome 45
- GPU model, driver and version: Intel inbuilt GPU
- Possible screenshot or video of visual glitches

#### Installation

https://0x0.st/X-DZ.txt

```
$ mpv --version
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Nov 21 2023 18:47:46
libplacebo version: v6.338.2
FFmpeg version: 7.0
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Reproduction steps

```
mpv --no-config 01-12-02.2019-03-08.QkQapdgAa7o.1440.webm
```

```
 (+) Video --vid=1 (*) (av1 2560x1440 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
File tags:
 Comment: https://www.youtube.com/watch?v=QkQapdgAa7o
Error opening/initializing the selected video_out (--vo) device.
Video: no video
Exiting... (Errors when loading file)
```

### Log file

https://0x0.st/X-DK.txt

**Comment by CounterPillow** [comment]
Your mpv is built without X11 or Wayland support.

**Comment by lamyergeier** [comment]
Homebrew on Linux installs without X11 or Wayland support? I didn't get any error while installing with homebrew. As you can see in the 

#### Installation

[https://0x0.st/X-DZ.txt](https://0x0.st/X-DZ.txt)

---

So, is mpv with Homebrew not fully supported on Linux?

**Comment by CounterPillow** [comment]
The mpv project is not the one maintaining the distributions that ship mpv. If you choose one run by incompetent idiots, such as Homebrew, then the upstream mpv project cannot help you if you run into any issues, and does not support said distribution in any way.
