### ISSUE TITLE
Do I need an exception for mpv in DisplayCAL Profile Loader?

### ISSUE THREAD

**Issue by averagePedestrian** [mpv-player/mpv#13898]
When using DisplayCAL Profile Loader to apply the icc profile for my display, and having the --icc-profile-auto option enabled in mpv, is it necessary to configure an exception for mpv in DisplayCAL Profile Loader? If so, should I select "Disable profile loader" or "Reset video card gamma table" when setting the exception?

### Log file
[mpvlog.txt](https://github.com/mpv-player/mpv/files/14996238/mpvlog.txt)

**Comment by kasper93** [comment]
If you are using color correction in mpv, you should reset video card gamma table, which would be applied on top.
