### ISSUE TITLE
wayland: window has not border and title bar

### ISSUE THREAD

**Issue by Nikoli** [mpv-player/mpv#139]
When using with weston-1.2.0 mpv has no window borders, no title bar with filename and buttons.

**Comment by matachi** [comment]
mpv on Fedora 24 with Gnome 3.20 under Wayland still lacks a border and title bar. I don't know if anything has changed since 2014 that would make it easier to implement now?

**Comment by wm4** [comment]
> I don't know if anything has changed since 2014 that would make it easier to implement now?

No. You can use the mpv X11 backend instead.

**Comment by gnumdk** [comment]
wontfix? Ok, in two years, mpv is a dead project...

**Comment by haasn** [comment]
In two years, every compositor will be able to draw server-side decorations.

**Comment by DooMMasteR** [comment]
So far, still nothing :-P
so ~10 month left

But so far MPV is the only software, that has this issue for me.

**Comment by DooMMasteR** [comment]
yeah, but the current state on an Ubuntu 17.10 machine ist still: no decorations unless gnome-mpv is used which still has no OSD-Control-UI

**Comment by gnumdk** [comment]
You can enable OSD in gnome-mpv in settings (you can pass options to mpv), just google it.

**Comment by DooMMasteR** [comment]
but not disable the slider again :-P
it is still crippled for me with Gnome 3.26.1 compared to Xorg

**Comment by gnumdk** [comment]
BTW, Gnome on wayland is broken until Gnome 4...: slow effects, slow mouse pointer, ...

**Comment by DooMMasteR** [comment]
ahh so the maintainer of MPV might be to blame?
