### ISSUE TITLE
Horrible cracking sound.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#13914]
### Important Information

Provide following Information:
- mpv version
```
mpv v0.37.0-793-g32817198bb Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0 (v6.338.0-121-ge4e096be)
FFmpeg version: N-114843-g38c322681e
FFmpeg library versions:
   libavutil       59.15.100
   libavcodec      61.5.103
   libavformat     61.3.100
   libswscale      8.2.100
   libavfilter     10.2.101
   libswresample   5.2.100
```
- Linux Distribution and Version
Arch
- Source of the mpv binary
AUR
- If known which version of mpv introduced the problem
I don't know.
- Window Manager and version
Mutter 46.0
- GPU model, driver and version
Mesa Gallium driver 24.0.5-arch1.1 for AMD Radeon RX 6750 XT (radeonsi, navi22, LLVM 17.0.6, DRM 3.57, 6.8.6-zen1-1-zen)
- Possible screenshot or video of visual glitches

It's audio problem.

### Reproduction steps

1. Play the video.

I've tried to use `--ao=pulse`, but it doesn't help.
VLC can play it without problem.

### Expected behavior
The audio is normal.
### Actual behavior
It doesn't play correctly.
### Log file

[audio_pipewire.txt](https://github.com/mpv-player/mpv/files/15011613/audio_pipewire.txt)
[audio_pulse.txt](https://github.com/mpv-player/mpv/files/15011616/audio_pulse.txt)

Without the log file, this issue will be closed for ignoring the issue template.

In the case of a crash, please provide a backtrace.

### Sample files

https://github.com/mpv-player/mpv/assets/9532105/d75bbe00-38d3-411f-b0d3-0e797bb65ce5

Sample files needed to reproduce this issue can be attached to the issue
(preferred), or be uploaded to https://0x0.st/ or similar sites.
(Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
Thanks for sharing your porn with us

**Comment by llyyr** [comment]
Firefox has the same audio artifacts, this is most likely a FFmpeg issue. Also you could've shared just the audio track.

**Comment by laichiaheng** [comment]
> Firefox has the same audio artifacts, this is most likely a FFmpeg issue. Also you could've shared just the audio track.
> 
> edit: ffplay plays it correctly

It didn't happen on Firefox when I posted this issue, but it happens now, weird.

**Comment by po5** [comment]
SFW sample with similar audio issues, plays fine in VLC. https://0x0.st/XoHe.mkv

**Comment by richardpl** [comment]
If you extract codec copy copy into .ac3 file that SFW sample above it also plays fine with ffplay. Something is very broken with lavf/mpv mkv demuxer or file is invalid and needs parser to properly split packets from bitstream.

**Comment by kasper93** [comment]
> The file in OP seems broken. Lots of [ffmpeg/audio] aac: ChannelElement 1.0 missing warnings. The difference is how this brokenness is handled.

`--ad=libfdk_aac` plays this file as mono without issues. But it is likely broken file and if we don't have more samples that expose similar issues, I don't think it is worth putting effort fixing this random video, you can watch without audio.

> SFW sample with similar audio issues, plays fine in VLC. https://0x0.st/XoHe.mkv

This is completely different issue. mkv != mp4, aac != ac3. Please don't hijack issues, it only derails discussion and pulls attention away from the original problem. I've reported in on ffmpeg trac https://trac.ffmpeg.org/ticket/10968
