### ISSUE TITLE
Switching to an external high bitrate audio track for the first time during playback will cause the video to freeze and lag continuously

### ISSUE THREAD

**Issue by dyphire** [mpv-player/mpv#13915]
### Important Information

Provide following Information:
- mpv version: git master
- Windows Version: Win11 23H2
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild
- If known which version of mpv introduced the problem

### Reproduction steps

Try playing video files with high bitrate external audio tracks using similar configurations:
```ini
aid=1
audio-file-auto=fuzzy
audio-file-paths=Audio 5.1
```
Try to switch to external audio tracks during playback.

### Expected behavior

Switch to external audio track for normal loading and video playback.

### Actual behavior

The external audio track was not immediately loaded, and the video continued to freeze and lag until the external audio track was loaded and played.

There is a simple way to avoid this problem: execute the `frame-step` command after switching to an external audio track for the first time, and then the external audio track will immediately load and the video play normally.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/15013256/mpv.log)

### Sample files

The video and audio files are too large to upload. This is the BT download link: https://nyaa.si/view/1430458

**Comment by sunpenghao** [comment]
Having the same problem.

> execute the `frame-step` command after switching to an external audio track for the first time, and then the external audio track will immediately load and the video play normally

This doesn't work for me. I've tried frame stepping/pausing then resuming before/after switching track and none worked.

**Comment by dyphire** [comment]
> > execute the `frame-step` command after switching to an external audio track for the first time, and then the external audio track will immediately load and the video play normally
> 
> This doesn't work for me. I've tried frame stepping/pausing then resuming before/after switching track and none worked.

It works for me, but it's likely not an effective solution.
