### ISSUE TITLE
DOCS/client-api-changes.rst is difficult to read on GitHub

### ISSUE THREAD

**Issue by ovitters** [mpv-player/mpv#13923]
### Important Information

Provide following Information:
- mpv version: 0.38
- Platform and Version: n/a
- Source of the mpv binary: n/a
- If known which version of mpv introduced the problem: no idea
- GPU model, driver and version: n/a
- Possible screenshot or video of visual glitches: n/a

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

If the issue is performance-related, try to reproduce it with --no-config
--profile=fast, which is designed to work on lower-end mobile devices.
Additionally, enable hardware decoding with --hwdec=yes or the Ctrl+h shortcut.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differs from your own.

The 0.38 release notes refer to https://github.com/mpv-player/mpv/blob/v0.38.0/DOCS/client-api-changes.rst. This file is difficult to read on GitHub. The formatting should be adjusted so it is readable like DOCS/interface-changes.rst.

### Expected behavior

That https://github.com/mpv-player/mpv/blob/v0.38.0/DOCS/client-api-changes.rst is readable more or less like https://github.com/mpv-player/mpv/blob/v0.38.0/DOCS/interface-changes.rst is. There's some additional characters on interface-changes.rst to make a large part of the text quoted. I guess the same should be done for DOCS/client-api-changes.rst.

### Actual behavior

https://github.com/mpv-player/mpv/blob/v0.38.0/DOCS/client-api-changes.rst is difficult to read unless you view it "raw".

### Log file

n/a

### Sample files

n/a

**Comment by tsl0922** [comment]
add a new line after `::` like 79b15f50e31d62b50d1c20160fa7ec489d3b05e5 should do the trick.

**Comment by kasper93** [comment]
Patches welcome.
