### ISSUE TITLE
OpenGL tears in exclusive fullscreen

### ISSUE THREAD

**Issue by RossSmyth** [mpv-player/mpv#13939]
### Important Information

Provide following Information:
- mpv version

mpv v0.38.0-52-ge5d683e1

- Windows Version

Window 10.0.19045

- Source of the mpv binary

shinchiro

- If known which version of mpv introduced the problem

unknown

- GPU model, driver and version

Intel Iris Xe from i7-12800H

- Possible screenshot or video of visual glitches

Unable to

### Reproduction steps

1. Download any of these files https://github.com/mpv-player/random-stuff/tree/master/vsync
2. Play with `mpv --no-config --gpu-api=opengl FILE.mkv`
3. Fullscreen the mpv window

I tested with all of the files in that directory and they all had tearing occur.

### Expected behavior

There is no tearing

### Actual behavior

There is tearing

The tearing goes away under these circumstances:

1. Run `mpv --no-config --gpu-api=vulkan FILE.mkv`
2. Do not put the window in fullscreen
3. Click on another window (i.e. the mpv window is not the active window)

If any of those three conditions are met, tearing does not occur.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/15042681/output.txt)

### Sample files

https://github.com/mpv-player/random-stuff/tree/master/vsync

**Comment by llyyr** [comment]
Does this also happen with --vo=gpu-next?

**Comment by RossSmyth** [comment]
Yes.
`mpv --no-config  --gpu-api=opengl --vo=gpu-next FILE.mkv` results in tearing as well.

**Comment by llyyr** [comment]
Most likely a driver issue then, opengl on windows isn't encouraged. You should use d3d11 or vulkan

**Comment by RossSmyth** [comment]
Yeah I do, I was just trying to replicate another issue here and saw this instead.

**Comment by RossSmyth** [comment]
I went home and tried to see if I could repeat this on my desktop with a dedicated Nvidia GPU, and instead found an entirely different issue

**Comment by RossSmyth** [comment]
Anyways, I can safely say it is probably a driver issue because I cannot replicate this issue on my computer with an Nvidia GPU
