### ISSUE TITLE
Opening youtube videos with yt-dlp silently fails recent regression

### ISSUE THREAD

**Issue by RossSmyth** [mpv-player/mpv#13934]
### Important Information

Provide following Information:
- mpv version

```ps
> mpv -V
mpv v0.38.0-52-ge5d683e1 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 19 2024 00:13:22
libplacebo version: v7.349.0 (v6.338.0-124-gd0eb997-dirty)
FFmpeg version: N-114864-gbb9e4ff35
FFmpeg library versions:
   libavutil       59.15.100
   libavcodec      61.5.103
   libavformat     61.3.100
   libswscale      8.2.100
   libavfilter     10.2.101
   libswresample   5.2.100
```

- Windows Version

Windows 10 10.0.19045 Build 19045

- Source of the mpv binary

https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240419

- If known which version of mpv introduced the problem

Sometime in the past few days. This build:
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240414
if uneffected

- GPU model, driver and version

Nvidia 2060 Super, Driver version: 551.86

- Possible screenshot or video of visual glitches

![image](https://github.com/mpv-player/mpv/assets/18294397/2aa98410-f5ea-4092-9647-0f5a80cc379a)

### Reproduction steps

1. Attempt to watch a youtube video
2. Doesn't open

### Expected behavior

It opens, or at least has an error.

### Actual behavior

Just silently fails

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/15032802/output.txt)

### Sample files

Happens with all youtube videos I've tried. But first noticed with `https://www.youtube.com/watch?v=qQVpBJyKfdA`

# Regression

Note that this is a recent regression as the same yt-dlp executable succeeds with this build:
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240414

Here is an output log of a successful playback
[output.txt](https://github.com/mpv-player/mpv/files/15032817/output.txt)

**Comment by RossSmyth** [comment]
Oh and I forgot to mention, opening local files opens as normal

**Comment by zhongfly** [comment]
https://github.com/openssl/openssl/issues/24184
