### ISSUE TITLE
Subtitle not selected by default despite having both default and forced flags

### ISSUE THREAD

**Issue by ToadKing** [mpv-player/mpv#13944]
### Important Information

Provide following Information:
- mpv version: 0.38
- Platform and Version: Arch Linux
- Source of the mpv binary: Arch repo
- If known which version of mpv introduced the problem: Unknown
- GPU model, driver and version: Nvidia RTX 2070, 550.76

### Reproduction steps

I have a MKV file with three subtitle tracks. The first one has the "default" and "forced" MKV flags on it set. However MPV by default selects the second subtitle track automatically.

### Expected behavior

The first subtitle track with forced and default flags is selected

### Actual behavior

The second subtitle track is selected

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/15046516/output.txt)

### Sample files

https://0x0.st/XoOr.mkv

### Other info

The audio track is Japanese while the subtitle tracks are English. My OS language should be reported as English.

If I remove the "forced" flag and just have the "default" one, the correct track is selected. However MPV still shouldn't select the second track if the forced flag is set on the first.

**Comment by llyyr** [comment]
Bisected to https://github.com/mpv-player/mpv/commit/81506828141481c92652987264def1f3f9a262fc
