### ISSUE TITLE
Actual FIX for files that produces..""spdif: Unusual frame timing: ............. 40 samples/frame is not implemented. Update your FFmpeg......

### ISSUE THREAD

**Issue by adolfotregosa** [mpv-player/mpv#13943]
### Important Information

Provide following Information:
- mpv version - >  any version
- Possible screenshot

![image](https://github.com/mpv-player/mpv/assets/7437931/13e1ffbd-36c5-4650-9199-9bab78847b2a)

### Reproduction steps

mpv sample.mkv -ao=pulse -audio-spdif=truehd

### Expected behavior
No message and no audio drop

### Actual behavior
Those messages and if you let the file play audio will drop at the same time the message appears. 
[ffmpeg] spdif: Unusual frame timing: 10248 => 12042, 40 samples/frame is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.

### Sample file
https://tregosacloud.duckdns.org/s/HRWxz7oX7HCSSpD

### Now for the fix...

we first need to compile ffmpeg with this change:
Edit  spdifenc.c and comment out:

       /* sanity check */
        //if (padding_remaining < 0 || padding_remaining >= MAT_FRAME_SIZE / 2) {
        //    avpriv_request_sample(s, "Unusual frame timing: %"PRIu16" => %"PRIu16", %d samples/frame",
        //                          ctx->truehd_prev_time, input_timing, ctx->truehd_samples_per_frame);
        //    padding_remaining = 0;
       // }

now compile mpv  using the ffmpeg we compiled with that change.

This fixes two issues plaguing mpv when bitstreaming (at the very least) files with ATMOS sound. 
Audio no longer drops on that sample file and when we manually seek, audio resumes correctly. 
I have yet to see any negative side effect of my change.  

I'll leave bellow screenshot of my 0.37 fixed version.
As you can see no error (especially when I seek and audio restores correctly).
![image](https://github.com/mpv-player/mpv/assets/7437931/43e1dfae-852b-499f-8dd7-f1b5a1733243)

I have opened on ffmpeg trac the issue: 
https://trac.ffmpeg.org/ticket/10948

I'm hopping mpv will be faster to implement the fix.

**Comment by sfan5** [comment]
How do you think mpv developers can implement a "fix" into the code of ffmpeg?

**Comment by netExtra** [comment]
The original fix apparently broke Dolby causing drop outs and related issues. There is an actual fix for that by @gbooker for Plex HTPC. I don't remember if it specifically gets rid of these errors but from personal experience it fixed all my Dolby issues when playing MKV files.

**Comment by mitzsch** [comment]
Related forum post.
https://forums.plex.tv/t/dolby-truehd-passthrough-modified-mpv-build/802742

**Comment by adolfotregosa** [comment]
> How do you think mpv developers can implement a "fix" into the code of ffmpeg?

They can use their own fork of ffmpeg and compile mpv against it?

**Comment by adolfotregosa** [comment]
> Related forum post. https://forums.plex.tv/t/dolby-truehd-passthrough-modified-mpv-build/802742
> 
> https://github.com/mitzsch/FFmpeg/blob/master-3/libavformat/spdifenc.c

Different approach but mine also fixes the audio loss  when you seek. Give it a try.

**Comment by sfan5** [comment]
> They can use their own fork of ffmpeg and compile mpv against it?

mpv is released as source code. We don't choose which versions of ffmpeg people build mpv with, patched or not.

**Comment by CounterPillow** [comment]
> I'm hopping mpv will be faster to implement the fix.

Your bug report is only 2 weeks old and you didn't even bother posting a patch to the mailing list. FOSS devs aren't your slaves.

**Comment by adolfotregosa** [comment]
> > I'm hopping mpv will be faster to implement the fix.
> 
> Your bug report is only 2 weeks old and you didn't even bother posting a patch to the mailing list. FOSS devs aren't your slaves.

Whats your problem? That what unnecessary and honestly rude. I'm no dev, I have VERY basic knowledge of c++ and I have no ideia how to do what you blurped out if so I would have already done that.
Since it's common sence that myself will now be flamed by you with one million arguments about how whatever, I'll retreat myself and never report anything else hut hopefully would have ended helping some person with my findings.

Have a good day.

**Comment by kasper93** [comment]
Fixed by: https://code.ffmpeg.org/FFmpeg/FFmpeg/pulls/23542

**Comment by simpson1045** [comment]
Heads-up for anyone landing here from FFmpeg commit `2db563fac2` ("spdifenc: preserve TrueHD MAT padding across branches", fixes trac #9569/#10948): on real hardware the new MAT packer appears to trade one bug for another.

**Setup:** Windows 11, mpv shinchiro builds, WASAPI exclusive passthrough (8ch/192k HBR), NVIDIA RTX 3070 HDMI direct to a Denon AVR-X3700H. Source: TrueHD Atmos 7.1 remux of a seamless-branching UHD (Star Wars Ep. III), which contains an input_timing gap (`7528 => 9302`, 40 samples/frame).

- **mpv 0.41.0-244 / FFmpeg N-123099 (pre-commit):** AVR locks instantly ("Dolby TrueHD/Atmos"), then audio drops dead at the branch splice with `Unusual frame timing … not implemented` — the exact bug the commit fixes.
- **mpv 0.41.0-923 / FFmpeg N-126125 (post-commit):** the splice is handled gracefully (`TrueHD output_timing discontinuity … total padding 115770` at verbose), but the AVR **never achieves bitstream lock at all** — front panel reports incoming "PCM (zero)", fully silent, from the first second (long before the discontinuity).

Controls on the same new build, same flags, same AVR input: DTS-HD MA 7.1 (same 8ch HBR carrier) locks fine as DTS:X; E-AC-3 JOC locks fine as Atmos. So the AO/WASAPI path is exonerated — the difference is confined to the MAT packing after `2db563fac2`.

A 40 s TrueHD-only sample reproducing the same timing values has been uploaded to streams.videolan.org/upload/ as `spdif_truehd_mat_regression_sample.mkv` (project: ffmpeg). Happy to test patches against the hardware — the receiver gives immediate lock/no-lock feedback.

**Comment by nathanlucas** [comment]
@simpson1045 
I can't find the sample you uploaded.  Maybe it needs more time to appear in the samples somewhere.  If you have another way to share it with me I'll take a look at it.

Is this only a problem with Star Wars Ep. III or has it happened on any other movies?
Does seeking get audio back?
When I was working on the ffmpeg fix I came across many streams that were genuinely damaged by older remux tools, and the problems were resolved by recreating the remuxes using more recent tools.  If you have the original disc or backup it might be worth running it through a new version of makemkv.

There was the FFmpeg change you referenced but also shortly after two related mpv commits from https://github.com/mpv-player/mpv/pull/18241.  There's a zhongfly build that has only the FFmpeg change and not the mpv changes.  Can you try that build to rule out the mpv change?  You could test the closest neighboring builds with none or both of the changes if you have time as well

Neither change yet:
https://github.com/zhongfly/mpv-winbuild/releases/tag/2026-07-26-b27573a239
FFmpeg only, not mpv yet:
https://github.com/zhongfly/mpv-winbuild/releases/tag/2026-07-28-24c1cc52a3
Both FFmpeg and mpv changes:
https://github.com/zhongfly/mpv-winbuild/releases/tag/2026-07-29-74356c0fc6

**Comment by simpson1045** [comment]
Followed up with a proper controlled retest and I have good news: your fix works on real hardware, and my "never locks" report does not reproduce. Details below.

Same HTPC and AVR as before (RTX 3070 HDMI direct to a Denon AVR-X3700H, WASAPI exclusive). I ran a build ladder against the same 40s sample:

- 0.41.0-244 (neither change): locks as TrueHD/Atmos, audio dies at the branch splice. The original bug, reproduced exactly.
- 0.41.0-910 (24c1cc52a3, FFmpeg change only): locks, plays cleanly through the splice.
- 0.41.0-912 (74356c0fc6, FFmpeg + mpv changes): clean.
- 0.41.0-920 and current 0.41.0-1012: clean. Seeking works and audio returns immediately after a seek.

So the FFmpeg change alone fixes the splice dropout. As for the lock failure I reported: I could not reproduce it on any build in this ladder, including 0.41.0-920 from Aug 8, and the exact 0.41.0-923 build I originally tested is no longer downloadable. The DTS and E-AC-3 controls in my original test rule out a wiring or endpoint mistake on that day, so I can't fully explain it. Whatever it was, it does not affect current builds, and I'm happy to call it resolved unless it resurfaces.

On your other questions: this only ever affected Ep. III for me, which fits since it is the seamless branching title (my other TrueHD remuxes from different sources never dropped out). And to test your damaged-remux theory I bought the retail 4K disc and made a fresh rip with MakeMKV 1.18.4. The fresh rip bitstreams perfectly on current builds, but so does the old remux, so at least in my case the original file does not appear damaged.

Sample: https://cloud.simpson1045.com/s/xjLgPEzHpBipXHa

Happy to test anything else against this hardware.

**Comment by nathanlucas** [comment]
@simpson1045
I checked your sample. There's a discontinuity at 25.235s but I don't see any reason why the stream might cause a problem before that. I compared spdifenc output pre-fix and post-fix on your sample up to but not including the discontinuity and the output is identical (which is expected), so I don't think the ffmpeg change is related to the failure you saw. The stream also correctly begins with a major sync and without any seeking mpv should be behaving the same pre and post fix when the movie starts. Also tried decoding the stream with ffmpeg and no errors or warnings there either.

If it happens again, capture an mpv log on it. Hopefully there will be something there. You might try power cycling the AVR and later the rebooting the computer to see if either of those changes anything.

**Comment by simpson1045** [comment]
Thanks for digging into the sample, that matches what I found on the retest. AVR state on a day I was rewiring the HDMI chain is my best guess too. I'll grab an mpv log if it ever comes back. Appreciate the fix, it made a real difference on this setup.
