### ISSUE TITLE
"alpha" option do not work. 

### ISSUE THREAD

**Issue by musicfunfan** [mpv-player/mpv#13957]
### Important Information

Provide following Information:
- mpv version
mpv v0.38.0
- Linux Distribution and Version
archlinux
- Source of the mpv binary
archlinux main repos. 
- Window Manager and version
-hyprland 0.39.1-5
- GPU model, driver and version
rx560 AMD amd opensource driver

### Reproduction steps
I use the option alpha=yes in order to render video with alpha channel. On the older version this was working now its not working. 
I get this massage ``Error parsing option alpha (option not found)``

### Expected behavior
Video with alpha channel working. 

### Actual behavior
Video with alpha channel do not work. 

Did this option removed from the mpv on the version i have installed on my system ? 
If so what can i do to have ti back?

Thanx for your time.

**Comment by sfan5** [comment]
https://github.com/mpv-player/mpv/blob/master/DOCS/interface-changes.rst:
>    - remove `--alpha` and reintroduce `--background` option for better control
     over blending alpha components into specific background types
