### ISSUE TITLE
Setting `geometry` on runtime breaks fullscreen

### ISSUE THREAD

**Issue by dexeonify** [mpv-player/mpv#13954]
### Important Information

Provide following Information:
- mpv version
```
mpv v0.38.0-63-gb364e4a6 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 21 2024 00:06:58
libplacebo version: v7.349.0 (v6.338.0-124-gd0eb997-dirty)
FFmpeg version: N-114900-ga44c34631
FFmpeg library versions:
   libavutil       59.15.100
   libavcodec      61.5.103
   libavformat     61.3.100
   libswscale      8.2.100
   libavfilter     10.2.101
   libswresample   5.2.100
```
- Windows Version: `Windows 11 Version 23H2 (OS build 22631.3447)`
- Source of the mpv binary: [shinchiro/mpv-winbuild-cmake](https://github.com/shinchiro/mpv-winbuild-cmake/releases)
- If known which version of mpv introduced the problem: Between [20240418](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240418) and [20240419](https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240419), most likely regressed by https://github.com/mpv-player/mpv/pull/13566

### Reproduction steps
1. Run `mpv --no-config --idle --force-window` in the terminal. An idle window is sufficient to reproduce.
2. Cycle fullscreen using any methods (keybinds, double-click etc).
3. Open the console and run `set geometry 100x100` (or any other values).
4. Now try cycling fullscreen again.

### Expected behavior
Cycling fullscreen should still work after changing geometry, autofit etc on runtime.

### Actual behavior
Cycling fullscreen completely breaks. The idle logo streches to fit the window width. If the user is already in fullscreen, they can't exit out of the state, and vice versa.

### Log file
[bug.txt](https://github.com/mpv-player/mpv/files/15051251/bug.txt)

**Comment by Dudemanguy** [comment]
So the cause is spurious/extra notifications due to the group data not being cleared. Not every backend handles that (understandably). The problem is that clearing said group data breaks the notifications when the value doesn't change for some reason and I don't really understand why atm.
