### ISSUE TITLE
Support built-in command palette script/API (a searchable menu)

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#13964]
### Expected behavior of the wanted feature

I noticed there has been work done on a context menu, there is another popular UI concept that could be supported as built-in script and API, a searchable menu, it can be used for:

Bindings, playlist, chapters, profiles, audio/subtitle/video tracks, commands, properties, options, audio devices, recent files, console history and more. mpv having such features built-in would improve productivity and user-friendliness, especially for beginners, some user scripts are hard to find and difficult to install due to lack of good documentation and missing package/extension/script manager.

The UI concept is very useful and popular, used for many things in VS Code (158k GitHub stars) and fzf (59k GitHub stars).

The same or similar concept is in the start menu of Windows, Gnome and KDE, in browser address bars and popular external launchers:

alfred launcher for macOS
flow launcher for Windows
rofi and albert launcher for Linux.

mpv.net had a WPF based command palette, but the code stopped working after porting from .NET Framework to .NET 5 (Core) due to a change made by Microsoft. Some mpv.net users miss the lost functionality now.

The existing script, 500 lines of code:

https://github.com/stax76/mpv-scripts?tab=readme-ov-file#command_palette

It's based on an awesome module which has 900 lines of code, found here:

https://github.com/Seme4eg/mpv-scripts/blob/master/script-modules/extended-menu.lua

There are a couple of searchable mpv menus listed here:

https://github.com/stax76/awesome-mpv?tab=readme-ov-file#menu

**Comment by tsl0922** [comment]
The context menu may have a libass based fallback implementation in the feature, it should be possible to adapt it to behave like command palette.
