### ISSUE TITLE
track-list is incorrectly detecting the video track as an image in some videos

### ISSUE THREAD

**Issue by raziel711** [mpv-player/mpv#13975]
### Important Information

Provide following Information:
- mpv version: mpv v0.38.0-63-gb364e4a6
- Platform and Version: Windows 10 22H2
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3
- If known which version of mpv introduced the problem: the problem occurs between https://github.com/mpv-player/mpv/commit/c6ccabe5854254320b175cde4106ec40d7a30946 and https://github.com/mpv-player/mpv/commit/fe0c181b1c3a73fb9d2a423d362a47d522e78c91
- GPU model, driver and version: NVIDIA GeForce GTX 1650, driver version 552.22

I am having an issue that with some videos, `track-list/N/image` is incorrectly reporting the video track as an image starting with shinchiro's mpv v0.37.0-241-gfe0c181b build.  This isn't happening with every video so I'm including a sample video.

[sample.zip](https://github.com/mpv-player/mpv/files/15083694/sample.zip)

### Reproduction steps
Starting with the v0.37.0-241-gfe0c181b build through the current build, playing the sample video by `mpv --no-config sample.mkv` and entering `show-text ${track-list/0/image}` in the console gives:
![mpv v0 37 0-241-gfe0c181b](https://github.com/mpv-player/mpv/assets/75226602/ed36551a-73e4-4d02-8940-30d538aff3c2)

However, with the previously available build, mpv v0.37.0-229-gc6ccabe5, `show-text ${track-list/0/image}` gives the correct value:
![mpv v0 37 0-229-gc6ccabe5](https://github.com/mpv-player/mpv/assets/75226602/671300e9-d275-4af6-b26e-26df7ae2abaf)

### Expected behavior
`track-list/N/image` should be no for video tracks.

### Actual behavior
`track-list/N/image` is yes on video tracks for certain videos.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/15083518/log.txt)

**Comment by kasper93** [comment]
I have a fix for that, will push when I have time.

**Comment by christoph-heinrich** [comment]
https://github.com/tomasklaen/uosc/issues/887
