### ISSUE TITLE
Support for emoji input on Windows

### ISSUE THREAD

**Issue by soredake** [mpv-player/mpv#13971]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature
Windows 11 have this nice emoji picker which lets you easily input emojis, but, mpv does not support inputting emoji's (nothing happens when I try to input emoji in mpv while chatting using [syncplay](https://syncplay.pl/)).

![image](https://github.com/mpv-player/mpv/assets/5204968/d8ff3a51-39ab-40c7-a422-438f23e19f77)

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt,
attach it to the issue, and replace this text with a link to it.

**Comment by kasper93** [comment]
Works for me, feel free to reopen with more information what exactly is not working.
