### ISSUE TITLE
Cannot load symlinked config files in directory linked with junction

### ISSUE THREAD

**Issue by soredake** [mpv-player/mpv#13972]
### Important Information

Provide following Information:
- mpv version: mpv-git 20240421
- Windows Version: Windows 11 Pro
- Source of the mpv binary: https://downloads.sourceforge.net/project/mpv-player-windows/64bit/mpv-x86_64-20240421-git-b364e4a.7z
- GPU model, driver and version: Doesn't matter
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1) Install scoop https://scoop.sh/#/
2) `scoop bucket add extras`
3) `scoop install extras/mpv-git`
4) Register associations using `$HOME\scoop\apps\mpv-git\current\installer\mpv-install.bat`
4) Link mpv config files using symlinks to `C:\Users\<username>\scoop\apps\mpv-git\current\portable_config` (you can easily do this with [this software](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html))
5) Open any media files with mpv.
6) Your config is not used.

### Expected behavior
Config files should be loaded.

### Actual behavior
Config files are not loaded, defaults are in use.

### Log file

[mpv_symlink_junction_bug.txt](https://github.com/mpv-player/mpv/files/15080288/mpv_symlink_junction_bug.txt)

### Sample files

Sample files needed to reproduce this issue can be attached to the issue
(preferred), or be uploaded to https://0x0.st/ or similar sites.
(Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by ruihe774** [comment]
`mp_path_exists` uses `stat` to check whether the config file exists. Maybe `stat` cannot well handle junctions.

FWIW, I think symbolic links are more suitable in your use case. You can create a symbolic link using PowerShell:
```powershell
New-Item -ItemType SymbolicLink -Path .\link -Target Path\To\Target
```

**Comment by ruihe774** [comment]
I've tried junctions and cannot reproduce. mpv works fine with directory junctions.

**Comment by ruihe774** [comment]
> > I think symbolic links are more suitable in your use case
> 
> I already use symlinks, they are placed in directory linked with junction to mpv folder, and that is creating this problem, using symlinks in plain folder works fine.

I'm confused. Do you mean you made a directory junction to `C:\Users\<username>\scoop\apps\mpv-git\current\portable_config` while config files inside it are also symbolic links? So, at the first place, are the config files accessible using tools other than mpv, e.g., `cmd` or `notepad`, using the path that mpv uses?

**Comment by soredake** [comment]
> Do you mean you made a directory junction to `C:\Users\<username>\scoop\apps\mpv-git\current\portable_config`

Not me, that's how `scoop` works:

mpv-git is installed to `C:\Users\user\scoop\apps\mpv-git\current`
`C:\Users\user\scoop\apps\mpv-git\current\portable_config` is junction to `C:\Users\user\scoop\persist\mpv-git\portable_config`

>So, at the first place, are the config files accessible using tools other than mpv, e.g., cmd or notepad, using the path that mpv uses?

Yes, you are right! Symlinks and junction that I made was broken, I've now linked files to `scoop\apps\mpv-git\current\portable_config` instead of `scoop\persist\mpv-git\portable_config` and everything works fine, thank you!
