### ISSUE TITLE
The screen turns off when playing a video in a Wayland session

### ISSUE THREAD

**Issue by AlexanderShad** [mpv-player/mpv#13988]
Hello.

mpv-0.38.0

If “Reduce screen brightness” and “Screen turn off - 5 minutes” are enabled in the power settings, then when watching a video in full screen mode, the screen brightness decreases over time, and then the screen turns off.

Stand:
OS: ALT Regular Sisyphus x86_64
Kernel: 6.1.87-std-def-alt1
DE: GNOME 46.1
CPU: Intel Celeron N4020C (2) @ 2.800GHz
GPU: Intel GeminiLake [UHD Graphics 600]
Display: wayland

Earlier, at another stand
OS: ALT Regular Sisyphus x86_64
DE: GNOME 45.2
CPU: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8) @ 2.100GHz
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series
Display: wayland

I got around this problem by running mpv 0.37.0 using gnome-session-inhibit , that is:
gnome-session-inhibit mpv video.mp4

In any case, on version mpv 0.38 the problem with the screen turning off while watching in a wayland session remains.

**Comment by ruihe774** [comment]
IIRC Mutter (GNOME) has added support for `zwp_idle_inhibit_manager_v1`, and gnome-session-inhibit is not needed anymore. Not sure whether it is related with this issue.

**Comment by AlexanderShad** [comment]
Hello.

I checked again.

After 2 minutes the screen brightness decreases.
After 5 minutes the screen turns off and the system is locked.

In this case, video playback does not stop. After the system is unlocked, the video continues.

Stand:
OS: ALT Regular Sisyphus x86_64
Kernel: 6.1.87-std-def-alt1
DE: GNOME 46.1
CPU: Intel Celeron N4020C (2) @ 2.800GHz
GPU: Intel GeminiLake [UHD Graphics 600]
Display: wayland

**Comment by AlexanderShad** [comment]
Hello.

In general, as found out, the problem is reproduced only when using

vo=dmabuf-wayland

If you delete the MPV configuration file, or use

vo=gpu-next

There is no problem.

DE: GNOME 46.3.1
OS: ALT Regular Sisyphus x86_64

**Comment by AlexanderShad** [comment]
Thank you
