### ISSUE TITLE
--slang region doesn't work

### ISSUE THREAD

**Issue by Piber0** [mpv-player/mpv#13983]
### Important Information

Provide following Information:
- mpv version 0.38.0
- Windows 11 23H2
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.38.0-x86_64-v3.7z/download
- If known which version of mpv introduced the problem
- GPU model, driver and version
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

`mpv --no-config --slang=fr-FR output.mkv`

### Expected behavior
According to the [documentation](https://mpv.io/manual/stable/#options-slang), the slang option supports the region of a language, so this command should select the subtitle French from France (fr-FR) instead of French from Canada (fr-CA).
### Log file

```
Z:\>mpv --no-config --slang=fr-FR output.mkv
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=en (*) (eac3 6ch 48000Hz)
 (+) Subs  --sid=1 --slang=fr-CA (subrip)
     Subs  --sid=2 --slang=fr-FR (subrip)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:02 / 00:43:29 (0%) A-V: -0.000 Cache: 84s/150MB
```

### Sample files
The specific region of a subtitle can be created in [MKVToolNix GUI](https://mkvtoolnix.download/) (and mkvpropedit propably too).

**Comment by kasper93** [comment]
Fixed by https://github.com/mpv-player/mpv/pull/13917
