### ISSUE TITLE
wasapi-exclusive-buffer ?

### ISSUE THREAD

**Issue by NeilTohno** [mpv-player/mpv#13996]
### Important Information

Provide following Information:
- Windows Version
Windows 10 22H2
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240426

- If known which version of mpv introduced the problem
> --wasapi-exclusive-buffer=<default|min|1-2000000>
> Set buffer duration in exclusive mode (i.e., with --audio-exclusive=yes). default and min use the default and minimum device period reported by WASAPI, respectively. You can also directly specify the buffer duration in microseconds, in which case a duration shorter than the minimum device period will be rounded up to the minimum period.
> 
> The default buffer duration should provide robust playback in most cases, but reportedly on some devices there are glitches following stream resets under the default setting. In such cases, specifying a shorter duration might help.
> 
> https://mpv.io/manual/master/#audio-output-drivers-wasapi-exclusive-buffer

I set wasapi-exclusive-buffer=5 (ms), and I found that the result is 5 us, 
Thanks.

mpv.exe --ao=wasapi --audio-exclusive=yes --wasapi-exclusive-buffer=5 --log-file="Y:/mpv.log" "Y:\TT3\02.mkv"

### Log file
```
[   0.610][d][ao/wasapi] IAudioClient::GetDevicePeriod
[   0.610][v][ao/wasapi] Device period: default 10000 us, minimum 3000 us
[   0.610][v][ao/wasapi] Requested buffer duration: 5 us
[   0.610][v][ao/wasapi] Trying buffer duration 3000 us
[   0.610][d][ao/wasapi] IAudioClient::Initialize
[   0.642][d][ao/wasapi] IAudioClient::Initialize pRenderClient
[   0.642][d][ao/wasapi] IAudioClient::Initialize IAudioClient_SetEventHandle
[   0.642][d][ao/wasapi] IAudioClient::Initialize IAudioClient_GetBufferSize
[   0.642][v][ao/wasapi] Buffer frame count: 144 (3000 us)
[   0.642][v][ao/wasapi] IAudioClock::GetFrequency gave a frequency of 48000.
[   0.643][d][ao/wasapi] Activating pEndpointVolume interface
[   0.644][d][ao/wasapi] IAudioEndpointVolume::QueryHardwareSupport
[   0.644][d][ao/wasapi] Entering dispatch loop
[   0.644][d][ao/wasapi] Init wasapi done
[   0.644][v][ao/wasapi] device buffer: 144 samples.
[   0.644][v][ao/wasapi] using soft-buffer of 9600 samples.
```
[log.zip](https://github.com/mpv-player/mpv/files/15128252/log.zip)

**And, who can tell me which value is most suitable?  I prefer large buffers.**
Thank you.

**Comment by ruihe774** [comment]
"microseconds" is `us`. `ms` is "milliseconds".

**Comment by Jules-A** [comment]
Maybe worth including the unit prefix in the documentation?

**Comment by NeilTohno** [comment]
I added the following code to the config file, will this cause any problems?

```
# Audio #

ad-lavc-threads=12
ao=wasapi
audio-exclusive=yes
wasapi-exclusive-buffer=6000 #min

audio-format=float
audio-channels=stereo
audio-swresample-o=resampler=soxr,precision=33
audio-swresample-o-append=cheby=1
audio-swresample-o-append=cutoff=1.00
audio-swresample-o-append=osf=fltp

# fix bgm too loud and speech too quiet
#af=lavfi="loudnorm=I=-16:TP=-3:LRA=4"
af=lavfi="loudnorm=I=-17:TP=-1:LRA=11"
```

**Comment by ruihe774** [comment]
> I added the following code to the config file, will this cause any problems?
> 
> ```
> # Audio #
> 
> ad-lavc-threads=12
> ao=wasapi
> audio-exclusive=yes
> wasapi-exclusive-buffer=6000 #min
> 
> audio-format=float
> audio-channels=stereo
> audio-swresample-o=resampler=soxr,precision=33
> audio-swresample-o-append=cheby=1
> audio-swresample-o-append=cutoff=1.00
> audio-swresample-o-append=osf=fltp
> 
> # fix bgm too loud and speech too quiet
> #af=lavfi="loudnorm=I=-16:TP=-3:LRA=4"
> af=lavfi="loudnorm=I=-17:TP=-1:LRA=11"
> ```

It's not related to the issue; you can convert this issue to a disscussion.
