### ISSUE TITLE
Add support for Youtube Mixes

### ISSUE THREAD

**Issue by marnunez** [mpv-player/mpv#1400]
Youtube Mixes are supported in youtube-dl since [this fix](https://github.com/rg3/youtube-dl/commit/652cdaa269725dfbf9effdc18a8fd0b369100399). Mpv loads the mix link as a single video (the first one). It would be nice to have the link parsed as a playlist instead (if possible).

**Comment by FedericoCeratto** [comment]
I was able to get a playlist URL by coping it from the browser.
mpv was able to play every video in sequence. It would be nice if it could allow go browse the videos with the forward/next arrows :)

**Comment by Kagami** [comment]
@FedericoCeratto do the "<", ">" and "ENTER" keybindings work for you?
Btw I was trying to play the entire channel's videos as a playlist and was thinking about creating issue for this but then I realized it's already available in mpv. Great works, guys!

**Comment by ghprod** [comment]
Thanks @Kagami  for hint :+1:

**Comment by marnunez** [comment]
@Kagami Uhhhh it never occurred to me! Nice tip!

**Comment by sslesar** [comment]
Very simple how to watch any youtube (single video or playlists). I just downloaded MPV player and downloaded youtube-dl on the single folder. After that, I created mpv.exe shortcut and added the parameter:  --no-border --ontop. 
that should result - D:\soft\MPV\mpv.exe --no-border --ontop
Finally open that shortcut and appeared MPV player and open any youtube playlist. Then select url bar and drag it and drop into player! done. I am talking about drag and drop any selected urls .
Sorry for my bad english.

**Comment by lachs0r** [comment]
By the way: `--ytdl-raw-options=yes-playlist=` will make these URLs work without changing them. Only downside is that it doesn’t start at the right playlist entry.

**Comment by Dudemanguy** [comment]
Apparently this works if you just modify the url (didn't test).

**Comment by ipatch** [comment]
doesn't seem to work for every playlist from what i can tell...

```
https://www.youtube.com/watch?v=dOsmG-sufNc&list=RDdOsmG-sufNc
```

tried with,

```
mpv --volume=34 "https://www.youtube.com/playlist?list=RDdOsmG-sufNc"
```

**Comment by LOuroboros** [comment]
> The YouTube Website will show an error if you try to open that URL in your browser, but youtube-dl (and mpv) can still resolve it as the full playlist.

That doesn't seem to be working on my end.

I turned `https://www.youtube.com/watch?v=McOAjzart78&list=RDJsntlJZ9h1U` into `http://www.youtube.com/playlist?list=RDJsntlJZ9h1U` and it's not really working. Mpv opens with no files loaded 😕
