### ISSUE TITLE
`895f40e1` breaks `hidpi-window-scale` on wayland

### ISSUE THREAD

**Issue by huyz-git** [mpv-player/mpv#14019]
### Important Information

Provide following Information:
- mpv version: 895f40e1
- Linux Distribution and Version: Archlinux 20240429
- Source of the mpv binary: self compiled
- If known which version of mpv introduced the problem: 895f40e1
- Window Manager and version kwin_wayland 6.0.4

### Reproduction steps

Use options like `--window-scale=1`, `--hidpi-window-scale=yes` or `--hidpi-window-scale=no`, and see the initial window size.
Use `Alt+1` and see if the window size change.

### Expected behavior

On 367d02e9, it works fine. `--hidpi-window-scale=yes` or `--hidpi-window-scale=no` result different initial window size, and with `--window-scale=1` the window size is the same as the video's resolution.

### Actual behavior

On 895f40e1, when setting `--window-scale=1`, the window size is actually scaled according to my wayland scale factor.
Setting `--hidpi-window-scale=yes` or `--hidpi-window-scale=no` result the same initial window size.
However, when using `Alt+1` to set window scale to 1, it works. The window size is the same as the video's resolution.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/15150370/output.txt)

**Comment by Dudemanguy** [comment]
What's the problem exactly? `--window-scale=1` and `--hidpi-window-scale=yes` are contradictory options. One has to "win".

**Comment by Dudemanguy** [comment]
I can't reproduce.
