### ISSUE TITLE
VP9 version hdr10+ video not decoding by mpv and ffprobe giving errors

### ISSUE THREAD

**Issue by aaaatheone** [mpv-player/mpv#14012]
I have some hdr10+ sample videos, got it from youtube, both are VP9 video format and has hdr10+ dynamic metadata on it.See the mediainfo screenshot of both files
![Screenshot 2024-04-28 160049](https://github.com/mpv-player/mpv/assets/145401543/4df72743-2058-47ed-9a6f-fc9a37cd03de)
![Screenshot 2024-04-28 160149](https://github.com/mpv-player/mpv/assets/145401543/2674b6ad-6b75-4311-aa1d-bdf12cfb6f2c)

But MPV players can't decoding the hdr10+ metadata from it rather then static hdr10 only and ffprobe showing some errors when tried to read those files.screenshort
![Screenshot 2024-04-28 160556](https://github.com/mpv-player/mpv/assets/145401543/1201801f-9f13-446c-95f3-9d869462f030)

when I converting those MKVs to mp4 using ffmpeg, those dynamic metadata getting lost!!

Is there any other way available where mpv can decode them and read or do you know any other player which can support vp9 version profile 2 hdr10+

**Additional check:** I have checked those files on my tv which support hdr10+ and it can read or decode hdr10+ easily without an error

**Comment by truexfan81** [comment]
have you tried it with ffplay? i suspect it's an ffmpeg issue

**Comment by aaaatheone** [comment]
> [truexfan81](/truexfan81)



> have you tried it with ffplay? i suspect it's an ffmpeg issue

@truexfan81 
so whats the command to show the file info using ffplay, I really don't know how to use ffplay to show file info, convert or any other processing.
How do I play those vp9 version hdr10+ videos using MPV?Do i need to convert vp9 to HEVC and extract hdr10+ metadata from vp9 file and inject it to HEVC file? 
If so, how do I do that

**Comment by truexfan81** [comment]
ffplay doesn't convert it's just a player thats included in ffmpeg, launch it with the terminal and watch the terminal output and see if it's having the same issues you had with mpv, that will give some indication of where the playback problem is

**Comment by aaaatheone** [comment]
ffplay also playing with errors and skipping hdr10+ metadata and playing with hdr10 only. 
![Screenshot 2024-04-28 191650](https://github.com/mpv-player/mpv/assets/145401543/255ba9fa-8e5a-494b-af04-20e262a80d25)

I think ffmpeg and mpv both need to add vp9 (youtube)version hdr10+ support. I can't believe it was not developed before lol.

At this time I have only option to convert vp9 to HEVC and extract hdr10+ metadata from vp9 file and inject it to HEVC file but how do I do that?

**Comment by truexfan81** [comment]
mpv uses ffmpeg for it's decoding and stuff so i'd say that confirms my theory that this is an ffmpeg problem and so this ticket needs to be filed on their but tracker

**Comment by kasper93** [comment]
> I think ffmpeg and mpv both need to add vp9 (youtube)version hdr10+ support. I can't believe it was not developed before lol.

Let me close this issue lol.
