### ISSUE TITLE
Can unmaximized window size settings be supported?

### ISSUE THREAD

**Issue by flowerseacar** [mpv-player/mpv#14030]
### Important Information

Provide following Information:
- mpv version  mpv v0.38.0-70-g2e03e0305c Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 26 2024 18:51:16

- Linux Distribution and Version ubuntu22.04

I want the size of the minimized window to be the same as when maximized, but my settings don't seem to take effect. It's because mpv doesn't support it or it's a problem with ubuntu22. The reason I do this is to keep the window size, but still be able to drag the window

**Comment by Dudemanguy** [comment]
How can "the size of the minimized window to be the same as when maximized"? That doesn't make sense. Can you explain what you mean?

**Comment by Dudemanguy** [comment]
Why you just described is "unmaximize" not "minimize". Very different things.

**Comment by damentz** [comment]
@Dudemanguy this guy is a bot / spammer, he opened two tickets on my project and gave nonsense responses to my replies.  I recommend you block and report as spam.

Also note he quoted you but managed to change the phrase "What you just described" to "Why you just described", an LLM would do that if it were small parameter enough.

Examples:
 - https://github.com/damentz/liquorix-package/issues/172
 - https://github.com/damentz/liquorix-package/issues/171

**Comment by kasper93** [comment]
> Also note he quoted you but managed to change the phrase "What you just described" to "Why you just described", an LLM would do that if it were small parameter enough.

Note that the message from Dudemanguy, was edited and initially had "Why". I think it is more like translator / communication issues, not bot. But either way, I closed this ticket.
