### ISSUE TITLE
mpv use a deprecated mkv balise for lang

### ISSUE THREAD

**Issue by pokemaster974** [mpv-player/mpv#14031]
### Important Information

Provide following Information:
- mpv version : mpv v0.37.0-22-g6898d57d 
- Platform and Version : Windows 10
- Source of the mpv binary : https://sourceforge.net/projects/mpv-player-windows/files/

### Reproduction steps
I've changed a balise lang into a mkv with mkvtoolnix GUI.
2 balises are present for lang : the first one marked as deprecated, the 2nd one on the next line.
I've only changed the 2nd as the first was marked as deprecated.

After this, lang was changed to English (it was before labelled as French)
![mkvinfo](https://github.com/mpv-player/mpv/assets/28442699/ac310b79-3db1-4392-a27c-5beec4dbbcd2)

MediaInfo recognizes the track as English track
```
Audio #2
ID                                       : 3
Format                                   : AAC LC
Format/Infos                             : Advanced Audio Codec Low Complexity
Identifiant du codec                     : A_AAC-2
Durée                                    : 1 h 30 min
Débit                                    : 192 kb/s
Canal(aux)                               : 2 canaux
Agencement des canaux                    : L R
Échantillonnage                          : 48,0 kHz
Débit im/s                               : 46,875 im/s (1024 SPF)
Mode de compression                      : Avec perte
Taille du flux                           : 123 Mio (4%)
Titre                                    : Audio Originale
Langue                                   : English
Par défaut                               : Non
Mode forcé                               : Non
```

But mpv uses the deprecated lang and recognizes the track as French track :
![mpv](https://github.com/mpv-player/mpv/assets/28442699/1f30e167-6ab5-4ce3-a471-928cec5955d6)

### Expected behavior
Using the balise not labelled deprecated

### Actual behavior
Using the balise labelled deprecated to display the track lang

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/15175362/log.txt)

**Comment by kasper93** [comment]
Fixed by https://github.com/mpv-player/mpv/commit/ab3b1744b9a6c7cc33e16538e175af2b00d3c2e3 Update to v0.38.0
