### ISSUE TITLE
QOpenGLWidget is displayed in its own window since libmpv.so.2.3.0 

### ISSUE THREAD

**Issue by kanehekili** [mpv-player/mpv#14045]
### Important Information

- mpv version: 1:0.38.0-2
- Arch Linux LTS Kernel
- pacman 
- 1:0.38.0-2, 1:0.37.0-2 works flawlessly
- XFCE with compiz, tested with xfwm4 as well
- GPU: Intel with i915 driver (laptop integrated graphics)

### Reproduction steps

Create a python5 or python 6 script with an embedded OpenGL widget. An example of a subclassed window can be seen [here](https://github.com/kanehekili/VideoCut/blob/master/src/MpvPlayer.py) or download the Arch Linux version of my application from [AUR](https://aur.archlinux.org/packages/videocut)
Update:  A[ Gist using OpenGLWindow](https://gist.github.com/kanehekili/fc45d870bce76905c78da57ecff660e0) (see comment below - you need to have a png file)

### Expected behavior
The created widget is shown in its frame and window as in lib version 1:0.37.0-2

### Actual behavior
With lib version libmpv.so.2.3.0  the widget is detached and displays itself in its own window. The same happened some time ago with the non-opengl implementation when using wayland. So the opengl variant is the only way to provide a consistent behaviour across X11 and wayland.
With the aforementioned version  python crashes if using a non OPENGL widget, but works if reverted back to lib version 1:0.37.0-2

### Log file
added some logs [below-with vo=libmpv](https://github.com/mpv-player/mpv/issues/14045#issuecomment-2093819736) and [without that flag](https://github.com/mpv-player/mpv/issues/14045#issuecomment-2093811946)

**Comment by Akemi** [comment]
if you are using the render API set `vo=libmpv`.

**Comment by kanehekili** [comment]
It gives me an error - "Invalid error for mpv parameter -4"  on a "plain" QT Window and some non verbal error if using the openGL option. Since these errors do not occur when the "previous" library is loaded I assume that there is a glich. I' m using jaseg's python-mpv from github for bindings.

**Comment by sfan5** [comment]
> Setting the loglevel to debug, nothing is displayed

Set the `log-file` option to create one.

**Comment by kanehekili** [comment]
Working on a small example to test - will include the option.

**Comment by sfan5** [comment]
FWIW we have a small example here and it works fine after we fixed it to include `vo=libmpv`: https://github.com/mpv-player/mpv-examples/tree/master/libmpv/qt_opengl

**Comment by kanehekili** [comment]
Just tried it to no avail.
[Here](https://gist.github.com/kanehekili/fc45d870bce76905c78da57ecff660e0) is a test. To verify it you'll need a picture relative to the code called "icons/film-clapper.png". 
In line 34 I included "vo":"libmpv" which results in showing nothing. Remove that and you'll have at least a view of the icon.
I'll add the logfile above

**Comment by kanehekili** [comment]
this is the logfile: (didn't know you couldn't add it afterward
[py6OpenGLMPV.log](https://github.com/mpv-player/mpv/files/15205300/py6OpenGLMPV.log)
 in the description

**Comment by kanehekili** [comment]
Attached the logfile with  "vo":"libmpv". Neither video nor single picture is displayed.. 

[py6OpenGLMPV2.log](https://github.com/mpv-player/mpv/files/15205339/py6OpenGLMPV2.log)

**Comment by sfan5** [comment]
Your log (which is also incomplete) shows libmpv being used initially but switches to gpu halfway. I suspect a problem in your glue code.

**Comment by kanehekili** [comment]
Sorry about the log, but using the "log_level=debug" option seems to be the only way of getting mpv logs.
Please instruct how to improve this.
Concerning the "glue code": It works with MPV 0.37.0-2 and the associated libmpv_2.2.0.so library. I've created a [gist for the purpose](https://gist.github.com/kanehekili/fc45d870bce76905c78da57ecff660e0)...

**Comment by kanehekili** [comment]
Adding two files - one with "vo=libmpv" (where no windows or graphics is displayed)  and one without. 
[gl_vo-libmpv.txt](https://github.com/mpv-player/mpv/files/15212765/gl_vo-libmpv.txt)
[gl-without-vo.txt](https://github.com/mpv-player/mpv/files/15212766/gl-without-vo.txt)
log-level has been set to trace

**Comment by kanehekili** [comment]
Last not least a log of the same gist, using mpv 0.37 with its libmpv.so 2.2.0:
[gl037Good.txt](https://github.com/mpv-player/mpv/files/15214588/gl037Good.txt)
This works with or without the "vo=libmpv" switch

**Comment by sfan5** [comment]
> Adding two files - one with "vo=libmpv" (where no windows or graphics is displayed)

`[   0.148][e][vo] Video output lipmpv not found!`

**Comment by kanehekili** [comment]
? It seems to be no problem with the previous version. I don't mind if things change - but as downstream developer I do not have any information how to fix your changes. Besides: I've never used the "vo" switch before.

**Comment by Dudemanguy** [comment]
He's saying you misspelled `libmpv` as `lipmpv`.

**Comment by kanehekili** [comment]
Thanks for the help. It was indeed the "vo" flag in combination with the "glue code". I'm closing this issue, since it looks that in former versions the "vo=libmpv" was the default.
