### ISSUE TITLE
`--vf=scale` isn't supported after ffmpeg 95568c4

### ISSUE THREAD

**Issue by zhongfly** [mpv-player/mpv#14047]
### Important Information

Provide following Information:
- mpv version: 
v0.38.0-99-gd61d2946
- Platform and Version: windows
- Source of the mpv binary: https://github.com/zhongfly/mpv-winbuild/actions/runs/8939929069
- If known which version of mpv introduced the problem
- GPU model, driver and version: not related

mpv and ffmpeg version:
```
mpv v0.38.0-99-gd61d2946 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May  2 2024 12:10:35
libplacebo version: v7.349.0 (v6.338.0-129-g47ea18e-dirty)
FFmpeg version: N-115056-g95568c4e3
FFmpeg library versions:
   libavutil       59.16.101
   libavcodec      61.5.103
   libavformat     61.3.103
   libswscale      8.2.100
   libavfilter     10.2.101
   libswresample   5.2.100
```

### Reproduction steps

run `mpv --vf=scale=help`

mpv with https://github.com/FFmpeg/FFmpeg/commit/69b4d9736b0d0ad01c41fcae2d66eaa534b76969 is good ,but https://github.com/FFmpeg/FFmpeg/commit/95568c4e316e8f5f3252596b1f01ce1de22216b6 broken.So some commits between 69b4d97 and 95568c4 broken `--vf=scale` option

### Expected behavior

Get help info about `--vf=scale`,like:
```
Options:

 w          <string>     Output video width
 h          <string>     Output video height
 flags      <string>     Flags to pass to libswscale
 interl     <bool>       set interlacing
 size       <string>     set video size
 in_color_matrix <int>        set input YCbCr type
 out_color_matrix <int>        set output YCbCr type
......
```

### Actual behavior

```
Option vf: 'scale' isn't supported.
Error parsing option vf (option parameter could not be parsed)
Setting commandline option --vf=scale=help failed.
Exiting... (Fatal error)
```

**Comment by kasper93** [comment]
@haasn

**Comment by sfan5** [comment]
it's FFmpeg/FFmpeg@bb8044581366fe286e16b14515d873979133dbda
mpv rejects filters with more than one in-/output for use with `--vf`:
https://github.com/mpv-player/mpv/blob/a26bbbd78d2ea61d335b679649c1ba266b8d0f39/filters/f_lavfi.c#L980-L997

**Comment by sfan5** [comment]
I bet it does but isn't that misusing the flag?
```c
/**
 * The number of the filter inputs is not determined just by AVFilter.inputs.
 * The filter might add additional inputs during initialization depending on the
 * options supplied to it.
 */
```
I suppose `scale` could be changed to dynamically add the ref input if any of the relevant vars are used.

**Comment by haasn** [comment]
> The pad count serves as a minimum even if the filter has dynamic inputs/outputs, so we should reject them here.

Huh, then indeed `vf_scale` would need to be fixed to only add the second input dynamically if it's being used. Whence did you get that?

**Comment by sfan5** [comment]
Yes, that is my interpretation.

**Comment by zhongfly** [comment]
Fixed by https://github.com/FFmpeg/FFmpeg/commit/6a5b021e353655ddeb1a29f50e519f562dcae5a7
