### ISSUE TITLE
--no-video option on streaming TV also downloads the video

### ISSUE THREAD

**Issue by lodgerz** [mpv-player/mpv#14076]
hi, I would like to play only the audio of an IPTV channel (so as not to consume bandwidth), I tried with the --no-video option. It works, but from conky I notice that it downloads the video anyway, so I don't save bandwidth. how can I solve it?

```
$ mpv "https://mediapolis.rai.it/relinker/relinkerServlet.htm?cont=358025&output=16" --aid=1 --no-video
Resuming playback. This behavior can be disabled with --no-resume-playback.
     Video --vid=1 (h264 1280x720 25.000fps) (2537 kbps)
     Video --vid=2 (h264 1024x576 25.000fps) (1988 kbps)
 (+) Audio --aid=1 (aac 2ch 44100Hz) (2537 kbps)
     Audio --aid=2 (aac 2ch 44100Hz) (1988 kbps)
AO: [pulse] 44100Hz stereo 2ch float
Saving state.
Not seekable, or time unknown - not saving position.
A: 00:00:23 / 00:00:30 (78%) Cache: 6.3s/275KB
Exiting... (Quit)
```

**Comment by kasper93** [comment]
You cannot, if video and audio are muxed together in one stream. You have to download the stream and demux it. It would be possible if your IPTV provider sent audio and video separately.
