### ISSUE TITLE
MPV 0.38.0 - Building from source requires >1GB of libraries :(

### ISSUE THREAD

**Issue by aerno** [mpv-player/mpv#14078]
Dear Sfan,

I don't know where else to report this, please mark this Issue as resolved asap.

I've been a fond MPV user for many years almost since the beginning of the app. It was always small and efficient in my opinion.

I used to be on 0.33.1 on Centos 7. 

This week I've been trying to build the latest MPV 0.38.0 on Rocky 9 (which builds) and am greeted with the requirements of libplacebo and libspirv...

I've built these 2 libraries and end up with >1GB of libraries required just to build the latest MPV... Phew.

I've reverted back to version 0.33.1 even on Rocky 9 as it doesn't need libplacebo and libspirv (which were at that time built in the source I read). 

Pity. Would it be an option to have basic support for placebo functions into the MPV source ? 

For me it means as soon as compilation on Rocky fails (bcs of updates) of the 0.33.1 source its end of the line.

Thanks, Arno

**Comment by kasper93** [comment]
libplacebo is tiny library. "libspirv" (you probably mean glslang, spirv-tools or shaderc) is optional and doesn't have to be built. I don't know where you get "1GB of required libraries".

If you give us information how you build and what are the pain points, we can thing together, but except libplacebo requirement, which is tiny, there is nothing else.

> please mark this Issue as resolved asap.

No problem.

**Comment by aerno** [comment]
Correct, libplacebo is small at only 1MB. I thought glslang was also required to build mpv+libplacebo and ended up with:

Compiling glslang-14.2.0 : OK
Stripping debug [/opt/multimedia/codecs/libglslang] : ............
Stripping saved : BEFORE=1962440K AFTER=1251240K
Removing sources /tmp/abmake/libglslang

In total 1.2GB ! Its quite amazing how fast (about 4min) libglslang builds to generate >1GB of binaries.

I retried building without libglslang and it works fine too. Don't know how I ended up with glslang in first place. 

My mistake, the new mpv 0.38.0 is perfectly workable !

**Comment by aerno** [comment]
The libplacebo / spirv / glslang issue seems a bit more complicated than expected: 

mpv Messines/timelapse/20240429.mp4 
 (+) Video --vid=1 (*) (h264 1920x1080 29.996fps)
[vo/gpu/drm] VT_GETMODE failed: Inappropriate ioctl for device
[vo/gpu/drm] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu/drm] No primary DRM device could be picked!
[vo/gpu/drm] Failed to find a usable DRM primary node!
[vo/gpu/libplacebo] Failed initializing any SPIR-V compiler! Maybe libplacebo was built without support for either libshaderc or glslang?
[vo/gpu/libplacebo] Failed initializing vulkan device
[vo/gpu-next/drm] Can't handle VT release - signal already used
[vo/gpu-next/drm] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/gpu-next/drm] No primary DRM device could be picked!
[vo/gpu-next/drm] Failed to find a usable DRM primary node!
[vo/gpu-next/libplacebo] Failed initializing any SPIR-V compiler! Maybe libplacebo was built without support for either libshaderc or glslang?

It seems MPV without glslang / spirv is not usable without setting a vo device. In that sense the 1GB+ sized glslang is still required to end with a workable player.

**Comment by Dudemanguy** [comment]
That looks more like you built it without x11 and/or wayland support.

**Comment by aerno** [comment]
When I remove libplacebo from /opt, and rebuild mpv 0.33 without it, it plays perfectly:

mpv Messines/timelapse/20240429-Timelapse.mp4 
 (+) Video --vid=1 (*) (h264 1920x1080 29.996fps)
VO: [gpu] 1920x1080 yuv420p
V: 00:00:02 / 00:06:53 (1%)

Exiting... (Quit)

As soon as I have libplacebo installed and try to build 0.33 I get an 'object' error during Ninja build. Ninja build -v doesn't give me any clarity.

Compiling mpv-0.38.0 with libplacebo installed without libglslang or libspirv builds perfectly, except that the resulting binary doesn't play anything.

Other players like vlc3, mplayer, kodi 20, kodi 21 all play perfectly well using libva on my workstation having gt1030 video, so I presume the libraries are all there to do it.

When I build libglslang or libspirv I end up with >1GB of installation size. For me unrealistic.

I guess MPV achitects have chosen the route of using libglslang and libspirv via libplacebo. 

For now I will have to revert back to 0.33 without libplacebo as I already mentioned in my 'bug' report. Upgrading to latest seems impossible without libglslang or libspirv for me.

Thank you for looking into it, Arno

**Comment by philipl** [comment]
1. You should be using libshaderc rather than glslang. I see there are rocky rpms for it that might be new enough. This will get you out of the business of building any of the shader libraries yourself.
2. If you are getting a huge footprint for the build tree, that's just the build tree. You only need that space when you are building it
3. If you are building huge library binaries, you must have full debug info turned on. Turn that off.

**Comment by MoSal** [comment]
>  There might be new dependencies (like Xrender)

libxpresent was the one that tripped me.
I don't remember the week I had to use Wayland fondly (#10433).

**Comment by aerno** [comment]
When I do a test build of mpv 0.38.0 I get this output:

Compiling mpv-0.38.0 : MESON setup:
The Meson build system
Version: 1.4.0
Source dir: /tmp/abmake/new/mpv-0.38.0
Build dir: /tmp/abmake/new/mpv-0.38.0/abbuild
Build type: native build
Project name: mpv
Project version: 0.38.0
C compiler for the host machine: cc (gcc 11.4.1 "cc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2)")
C linker for the host machine: cc ld.bfd 2.35.2-42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Found pkg-config: YES (/usr/bin/pkg-config) 1.7.3
Run-time dependency libavcodec found: YES 58.134.100
Run-time dependency libavfilter found: YES 7.110.100
Run-time dependency libavformat found: YES 58.76.100
Run-time dependency libavutil found: YES 56.70.100
Run-time dependency libswresample found: YES 3.9.100
Run-time dependency libswscale found: YES 5.9.100
Run-time dependency libplacebo found: YES 7.349.0
Run-time dependency libass found: YES 0.15.2
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-sign-compare: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wno-cast-function-type: YES 
Compiler for C supports arguments -Wempty-body: YES 
Compiler for C supports arguments -Wdisabled-optimization: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wno-format-zero-length: YES 
Compiler for C supports arguments -Wno-redundant-decls: YES 
Compiler for C supports arguments -Wvla: YES 
Compiler for C supports arguments -Wno-format-truncation: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -fno-math-errno: YES 
Compiler for C supports arguments -Wformat -Werror=format-security: YES 
Compiler for C supports link arguments -Wl,-z,noexecstack: YES 
Compiler for C supports link arguments -Wl,--nxcompat,--no-seh,--dynamicbase: NO 
Run-time dependency dl found: YES
Library atomic found: YES
Compiler for C supports link arguments -rdynamic: YES 
Run-time dependency threads found: YES
Header "pthread.h" has symbol "pthread_condattr_setclock" with dependency threads: YES 
Run-time dependency appleframeworks found: NO (tried framework)
Checking for function "fork" : YES 
Checking for function "ppoll" : YES 
Library windowsapp skipped: feature uwp disabled
Checking for function "glob" : YES 
Header "sys/vt.h" has symbol "VT_GETMODE" : YES 
Checking for function "pthread_setname_np" with dependency threads: YES 
Checking for function "fstatfs" : NO 
Checking for function "fstatfs" : YES 
Checking if "vector check" compiles: YES 
Program /tmp/abmake/new/mpv-0.38.0/TOOLS/docutils-wrapper.py found: YES (/tmp/abmake/new/mpv-0.38.0/TOOLS/docutils-wrapper.py)
Program /tmp/abmake/new/mpv-0.38.0/TOOLS/file2string.py found: YES (/tmp/abmake/new/mpv-0.38.0/TOOLS/file2string.py)
Program /tmp/abmake/new/mpv-0.38.0/TOOLS/matroska.py found: YES (/tmp/abmake/new/mpv-0.38.0/TOOLS/matroska.py)
Dependency libcdio skipped: feature cdda disabled
Dependency libcdio_paranoia skipped: feature cdda disabled
Has header "linux/dvb/frontend.h" : YES 
Dependency dvdnav skipped: feature dvdnav disabled
Dependency dvdread skipped: feature dvdnav disabled
Run-time dependency iconv found: YES
Found CMake: /usr/bin/cmake (3.20.2)
Run-time dependency mujs found: NO (tried pkgconfig and cmake)
Run-time dependency lcms2 found: NO (tried pkgconfig and cmake)
Run-time dependency libarchive found: NO (tried pkgconfig and cmake)
Run-time dependency libavdevice found: YES 58.13.100
Run-time dependency libbluray found: YES 1.3.4
Library m found: YES
Library rt found: YES
Dependency lua found: NO found 5.4.0 but need: '<5.3.0' ; matched: '>=5.1.0'
Run-time dependency lua found: NO (tried pkgconfig and cmake)
Run-time dependency lua52 found: NO (tried pkgconfig and cmake)
Run-time dependency lua5.2 found: NO (tried pkgconfig and cmake)
Run-time dependency lua-5.2 found: NO (tried pkgconfig and cmake)
Run-time dependency luajit found: YES 2.1.1713773202
Run-time dependency rubberband found: NO (tried pkgconfig and cmake)
Dependency sdl2 skipped: feature sdl2 disabled
Run-time dependency uchardet found: NO (tried pkgconfig and cmake)
Run-time dependency vapoursynth found: NO (tried pkgconfig and cmake)
Run-time dependency vapoursynth-script found: NO (tried pkgconfig and cmake)
Run-time dependency zimg found: NO (tried pkgconfig and cmake)
Run-time dependency zlib found: YES 1.2.11
Run-time dependency alsa found: YES 1.2.9
Dependency appleframeworks (modules: Foundation, AudioToolbox) skipped: feature audiounit disabled
Header "AudioToolbox/AudioToolbox.h" has symbol "kAudioUnitSubType_RemoteIO" skipped: feature audiounit disabled
Run-time dependency appleframeworks found: NO (tried framework)
Run-time dependency appleframeworks found: NO (tried framework)
Run-time dependency jack found: NO (tried pkgconfig and cmake)
Dependency openal skipped: feature openal disabled
Library OpenSLES found: NO
Header "sys/soundcard.h" has symbol "SNDCTL_DSP_HALT" : NO 
Run-time dependency libpipewire-0.3 found: NO (tried pkgconfig and cmake)
Run-time dependency libpulse found: YES 15.0
Run-time dependency sndio found: NO (tried pkgconfig and cmake)
Header "audioclient.h" has symbol "IAudioClient" skipped: feature wasapi disabled
Run-time dependency caca found: NO (tried pkgconfig and cmake)
Has header "d3d9.h" skipped: feature direct3d disabled
Run-time dependency libdrm found: YES 2.4.107
Run-time dependency gbm found: YES 23.1.4
Run-time dependency libjpeg found: YES 9.4.0
Dependency shaderc skipped: feature shaderc disabled
Run-time dependency libsixel found: NO (tried pkgconfig and cmake)
Checking for function "shm_open" : YES 
Dependency spirv-cross-c-shared skipped: feature spirv-cross disabled
Run-time dependency wayland-client found: YES 1.21.0
Run-time dependency wayland-cursor found: YES 1.21.0
Run-time dependency wayland-protocols found: YES 1.31
Run-time dependency xkbcommon found: YES 1.0.3
Dependency wayland-client found: YES 1.21.0 (cached)
Has header "linux/input-event-codes.h" with dependency wayland-client: YES 
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Checking for function "memfd_create" : YES 
Run-time dependency x11 found: YES 1.7.0
Run-time dependency xscrnsaver found: YES 1.2.3
Run-time dependency xext found: YES 1.3.4
Run-time dependency xpresent found: NO (tried pkgconfig and cmake)
Run-time dependency xrandr found: YES 1.5.2
Dependency xv skipped: feature xv disabled
Library EGL skipped: feature egl-angle-lib disabled
Run-time dependency egl found: YES 1.5
Library EGL skipped: feature egl-android disabled
Run-time dependency wayland-egl found: YES 18.1.0
Dependency vulkan skipped: feature vulkan disabled
Checking for function "vkCreateDisplayPlaneSurfaceKHR" with dependency vulkan: NO 
Run-time dependency ffnvcodec found: YES 12.2.72.0
Header "OpenGLES/ES3/glext.h" has symbol "GL_RGB32F" skipped: feature ios-gl disabled
Run-time dependency libva found: YES 1.12.0
Run-time dependency libva-drm found: YES 1.12.0
Run-time dependency libva-wayland found: YES 1.12.0
Dependency libva-x11 skipped: feature vaapi-x11 disabled
Dependency libva-win32 skipped: feature vaapi-win32 disabled
Dependency vdpau skipped: feature vdpau disabled
Dependency appleframeworks (modules: CoreVideo) skipped: feature videotoolbox-pl disabled
Program xcrun skipped: feature swift-build disabled
Program rst2man rst2man.py found: NO
Program rst2html rst2html.py skipped: feature html-build disabled
Program rst2pdf skipped: feature pdf-build disabled
Configuring config.h using configuration
Message: List of enabled features: alsa build-date cplugins cuda-hwaccel cuda-interop debug dmabuf-interop-gl dmabuf-wayland drm dvbin egl egl-drm egl-wayland ffmpeg ffnvcodec gbm gl glibc-thread-name glob glob-posix gpl iconv jpeg libass libavdevice libbluray libdl libplacebo linux-fstatfs luajit memfd-create posix posix-shm ppoll pthread-condattr-setclock pulse vaapi vaapi-drm vaapi-wayland vector vt.h wayland wayland-protocols-1-27 wayland-protocols-1-31 zlib
Fetching value of define "MPV_CLIENT_API_VERSION" : (((2) << 16) | (3) | 0UL) 
Compiler for C supports link arguments -Wl,-Bsymbolic: YES 
Build targets in project: 41

mpv 0.38.0

    d3d11     : NO
    javascript: NO
    libmpv    : NO
    lua       : YES
    opengl    : YES
    vulkan    : NO
    wayland   : YES
    x11       : NO

  User defined options
    libdir    : /opt/multimedia/mpv/lib
    prefix    : /opt/multimedia/mpv

@philipl I look at the 'prefix' installation directory only for size. My build tree is in /tmp and thats a tmpfs RAMdisk for me. Its gone at first boot.

Both the installed libspirv and libglslang are amazingly equal in size, about 1.1GB. Seeing the console output of glslang hints me its building spirv inside that too. 

@MoSal It could very well be libXpresent of which I don't have the -devel RPM at the moment. I'll install it and re-run:

The Meson build system
Version: 1.4.0
Source dir: /tmp/abmake/new/mpv-0.38.0
Build dir: /tmp/abmake/new/mpv-0.38.0/abbuild
Build type: native build
Project name: mpv
Project version: 0.38.0
C compiler for the host machine: cc (gcc 11.4.1 "cc (GCC) 11.4.1 20231218 (Red Hat 11.4.1-3)")
C linker for the host machine: cc ld.bfd 2.35.2-43
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Found pkg-config: YES (/usr/bin/pkg-config) 1.7.3
Run-time dependency libavcodec found: YES 58.134.100
Run-time dependency libavfilter found: YES 7.110.100
Run-time dependency libavformat found: YES 58.76.100
Run-time dependency libavutil found: YES 56.70.100
Run-time dependency libswresample found: YES 3.9.100
Run-time dependency libswscale found: YES 5.9.100
Run-time dependency libplacebo found: YES 7.349.0
Run-time dependency libass found: YES 0.15.2
Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-sign-compare: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wno-cast-function-type: YES 
Compiler for C supports arguments -Wempty-body: YES 
Compiler for C supports arguments -Wdisabled-optimization: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wno-format-zero-length: YES 
Compiler for C supports arguments -Wno-redundant-decls: YES 
Compiler for C supports arguments -Wvla: YES 
Compiler for C supports arguments -Wno-format-truncation: YES 
Compiler for C supports arguments -Wimplicit-fallthrough: YES 
Compiler for C supports arguments -fno-math-errno: YES 
Compiler for C supports arguments -Wformat -Werror=format-security: YES 
Compiler for C supports link arguments -Wl,-z,noexecstack: YES 
Compiler for C supports link arguments -Wl,--nxcompat,--no-seh,--dynamicbase: NO 
Run-time dependency dl found: YES
Library atomic found: YES
Compiler for C supports link arguments -rdynamic: YES 
Run-time dependency threads found: YES
Header "pthread.h" has symbol "pthread_condattr_setclock" with dependency threads: YES 
Run-time dependency appleframeworks found: NO (tried framework)
Checking for function "fork" : YES 
Checking for function "ppoll" : YES 
Library windowsapp skipped: feature uwp disabled
Checking for function "glob" : YES 
Header "sys/vt.h" has symbol "VT_GETMODE" : YES 
Checking for function "pthread_setname_np" with dependency threads: YES 
Checking for function "fstatfs" : NO 
Checking for function "fstatfs" : YES 
Checking if "vector check" compiles: YES 
Program /tmp/abmake/new/mpv-0.38.0/TOOLS/docutils-wrapper.py found: YES (/tmp/abmake/new/mpv-0.38.0/TOOLS/docutils-wrapper.py)
Program /tmp/abmake/new/mpv-0.38.0/TOOLS/file2string.py found: YES (/tmp/abmake/new/mpv-0.38.0/TOOLS/file2string.py)
Program /tmp/abmake/new/mpv-0.38.0/TOOLS/matroska.py found: YES (/tmp/abmake/new/mpv-0.38.0/TOOLS/matroska.py)
Dependency libcdio skipped: feature cdda disabled
Dependency libcdio_paranoia skipped: feature cdda disabled
Has header "linux/dvb/frontend.h" : YES 
Dependency dvdnav skipped: feature dvdnav disabled
Dependency dvdread skipped: feature dvdnav disabled
Run-time dependency iconv found: YES
Found CMake: /usr/bin/cmake (3.26.5)
Run-time dependency mujs found: NO (tried pkgconfig and cmake)
Run-time dependency lcms2 found: NO (tried pkgconfig and cmake)
Run-time dependency libarchive found: NO (tried pkgconfig and cmake)
Run-time dependency libavdevice found: YES 58.13.100
Run-time dependency libbluray found: YES 1.3.4
Library m found: YES
Library rt found: YES
Dependency lua found: NO found 5.4.0 but need: '<5.3.0' ; matched: '>=5.1.0'
Run-time dependency lua found: NO (tried pkgconfig and cmake)
Run-time dependency lua52 found: NO (tried pkgconfig and cmake)
Run-time dependency lua5.2 found: NO (tried pkgconfig and cmake)
Run-time dependency lua-5.2 found: NO (tried pkgconfig and cmake)
Run-time dependency luajit found: YES 2.1.1713773202
Run-time dependency rubberband found: NO (tried pkgconfig and cmake)
Dependency sdl2 skipped: feature sdl2 disabled
Run-time dependency uchardet found: NO (tried pkgconfig and cmake)
Run-time dependency vapoursynth found: NO (tried pkgconfig and cmake)
Run-time dependency vapoursynth-script found: NO (tried pkgconfig and cmake)
Run-time dependency zimg found: NO (tried pkgconfig and cmake)
Run-time dependency zlib found: YES 1.2.11
Run-time dependency alsa found: YES 1.2.10
Dependency appleframeworks (modules: Foundation, AudioToolbox) skipped: feature audiounit disabled
Header "AudioToolbox/AudioToolbox.h" has symbol "kAudioUnitSubType_RemoteIO" skipped: feature audiounit disabled
Run-time dependency appleframeworks found: NO (tried framework)
Run-time dependency appleframeworks found: NO (tried framework)
Run-time dependency jack found: NO (tried pkgconfig and cmake)
Dependency openal skipped: feature openal disabled
Library OpenSLES found: NO
Header "sys/soundcard.h" has symbol "SNDCTL_DSP_HALT" : NO 
Run-time dependency libpipewire-0.3 found: NO (tried pkgconfig and cmake)
Run-time dependency libpulse found: YES 15.0
Run-time dependency sndio found: NO (tried pkgconfig and cmake)
Header "audioclient.h" has symbol "IAudioClient" skipped: feature wasapi disabled
Run-time dependency caca found: NO (tried pkgconfig and cmake)
Has header "d3d9.h" skipped: feature direct3d disabled
Run-time dependency libdrm found: YES 2.4.107
Run-time dependency gbm found: YES 23.3.3
Run-time dependency libjpeg found: YES 9.4.0
Dependency shaderc skipped: feature shaderc disabled
Run-time dependency libsixel found: NO (tried pkgconfig and cmake)
Checking for function "shm_open" : YES 
Dependency spirv-cross-c-shared skipped: feature spirv-cross disabled
Run-time dependency wayland-client found: YES 1.21.0
Run-time dependency wayland-cursor found: YES 1.21.0
Run-time dependency wayland-protocols found: YES 1.31
Run-time dependency xkbcommon found: YES 1.0.3
Dependency wayland-client found: YES 1.21.0 (cached)
Has header "linux/input-event-codes.h" with dependency wayland-client: YES 
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Checking for function "memfd_create" : YES 
Run-time dependency x11 found: YES 1.7.0
Run-time dependency xscrnsaver found: YES 1.2.3
Run-time dependency xext found: YES 1.3.4
Run-time dependency xpresent found: YES 1.0.0
Run-time dependency xrandr found: YES 1.5.2
Run-time dependency xv found: YES 1.0.11
Dependency GL skipped: feature gl-x11 disabled
Library EGL skipped: feature egl-angle-lib disabled
Run-time dependency egl found: YES 1.5
Library EGL skipped: feature egl-android disabled
Run-time dependency wayland-egl found: YES 18.1.0
Dependency vulkan skipped: feature vulkan disabled
Checking for function "vkCreateDisplayPlaneSurfaceKHR" with dependency vulkan: NO 
Run-time dependency ffnvcodec found: YES 12.2.72.0
Header "OpenGLES/ES3/glext.h" has symbol "GL_RGB32F" skipped: feature ios-gl disabled
Run-time dependency libva found: YES 1.12.0
Run-time dependency libva-drm found: YES 1.12.0
Run-time dependency libva-wayland found: YES 1.12.0
Run-time dependency libva-x11 found: YES 1.12.0
Dependency libva-win32 skipped: feature vaapi-win32 disabled
Run-time dependency vdpau found: YES 1.1
Dependency appleframeworks (modules: CoreVideo) skipped: feature videotoolbox-pl disabled
Program xcrun skipped: feature swift-build disabled
Program rst2man rst2man.py found: NO
Program rst2html rst2html.py skipped: feature html-build disabled
Program rst2pdf skipped: feature pdf-build disabled
Configuring config.h using configuration
Message: List of enabled features: alsa build-date cplugins cuda-hwaccel cuda-interop debug dmabuf-interop-gl dmabuf-wayland drm dvbin egl egl-drm egl-wayland egl-x11 ffmpeg ffnvcodec gbm gl glibc-thread-name glob glob-posix gpl iconv jpeg libass libavdevice libbluray libdl libplacebo linux-fstatfs luajit memfd-create posix posix-shm ppoll pthread-condattr-setclock pulse vaapi vaapi-drm vaapi-wayland vaapi-x11 vdpau vector vt.h wayland wayland-protocols-1-27 wayland-protocols-1-31 x11 xv zlib
Fetching value of define "MPV_CLIENT_API_VERSION" : (((2) << 16) | (3) | 0UL) 
Compiler for C supports link arguments -Wl,-Bsymbolic: YES 
Build targets in project: 41

mpv 0.38.0

    d3d11     : NO
    javascript: NO
    libmpv    : NO
    lua       : YES
    opengl    : YES
    vulkan    : NO
    wayland   : YES
    x11       : YES

Its indeed related to libXpresent !

Player mpv-0.38.0 test:

mpv 20240429-Timelapse.mp4
 (+) Video --vid=1 (*) (h264 1920x1080 29.996fps)
VO: [gpu] 1920x1080 yuv420p
V: 00:00:07 / 00:06:53 (2%)
Exiting... (Quit)

It plays perfectly fine! Amazing how such a little detail (11kB to be exact) can result into me installing libspirv and libglslang having >1GB of binaries and almost having to let MPV go.

Thank you all for helping ! I'm glad MPV can stay with me on Rocky 9 the next years. I've been on Centos7 for too long.
