### ISSUE TITLE
The loadfile option must be an integer: image-display-duration=inf

### ISSUE THREAD

**Issue by hanguofu** [mpv-player/mpv#14077]
### Important Information

Provide following Information:
- mpv version :  0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
- Linux Distribution and Version : Ubuntu 22.04 LTS
- Source of the mpv binary : from  third party : https://ppa.launchpadcontent.net/ubuntuhandbook1/mpv/ubuntu/pool/main/m/mpv/mpv_0.38.0-0ubuntu1~jammy_arm64.deb
- If known which version of mpv introduced the problem : not sure
- Window Manager and version : Wayland   Gnome 42.9
- GPU model, driver and version : Mali-G31 ( Panfrost )
- Possible screenshot or video of visual glitches  : not avail.
- 
### Reproduction steps

Start mpv with a video clip and input-ipc-server  feature . Namely ,  commands are sent to mpv via  unix domain socket.
During mpv running , send the following cmd. to mpv : 
{ "command": [ "loadfile", "/home/sh/idle.png", "append", "image-display-duration=inf" ] } 

### Expected behavior
mpv accept the cmd. and append the pic. to the play list.

### Actual behavior
Cmd. denied : 
[ipc_2] Read error (Connection reset by peer)
[ipc_4] The loadfile option must be an integer: image-display-duration=inf
[ipc_4] Command loadfile: argument index can't be parsed: option parameter could not be parsed.

### Log file
...
[ 329.663][v][ipc_4] Client connected
[ 329.663][e][ipc_4] The loadfile option must be an integer: image-display-duration=inf
[ 329.664][e][ipc_4] Command loadfile: argument index can't be parsed: option parameter could not be parsed.
[ 329.664][v][ipc_4] Client disconnected
[ 329.664][d][ipc_4] Exiting...

### Sample files

whatever video clip you have. The png pic. doesnot matter either , find any pic. on hand.

**Comment by guidocella** [comment]
loadfile in mpv 0.38 has a new argument so you need `{ "command": [ "loadfile", "/home/sh/idle.png", "append", 0, "image-display-duration=inf" ] }`

**Comment by hanguofu** [comment]
Thankyou , guidocella :)

**Comment by cbuosi** [comment]
> loadfile in mpv 0.38 has a new argument so you need `{ "command": [ "loadfile", "/home/sh/idle.png", "append", 0, "image-display-duration=inf" ] }`

THANKS! the official site is down. was searching for this!
