### ISSUE TITLE
Playback becomes stuck using avfoundation audio driver

### ISSUE THREAD

**Issue by low-batt** [mpv-player/mpv#14092]
### Important Information

Provide following Information:
- mpv version `master` at d6803c45183b18637e603eb1997c4ffbcc434616
- macOS Version 13.6.3
- Source of the mpv binary or bundle: local build using `mpv-build`
- If known which version of mpv introduced the problem: unknown
- Possible screenshot or video of visual glitches: N/A

### Reproduction steps

- Start playing the video below with `--ao=avfoundation`
- Click the OSC ⏯ button to pause playback
- Press the → key to move the playback position forward
- Click the OSC ⏯ button to resume playback
- Repeat until clicking the OSC ⏯ button fails to resume playback

This shows options used when reproducing the problem:
```text
low-batt@gag mpv-build (master %=)$ mpv/build/mpv --no-config  --log-file=mpv.log --ao=avfoundation --keep-open ~/Movies/Advanced\ stream\ H.264\:HEVC\:UHD\:Dolby\ Vision\:Dolby\ Digital\:Dolby\ Atmos.mp4 
 (+) Video --vid=1 (*) (hevc 3840x2160 23.976fps)
 (+) Audio --aid=1 (*) (eac3 6ch 48000Hz)
AO: [avfoundation] 48000Hz 5.1(side) 6ch float
VO: [libmpv] 3840x2160 yuv420p10
AV: 00:00:19 / 00:01:38 (20%) A-V:  0.000 Dropped: 5                    
Exiting... (Quit)
low-batt@gag mpv-build (master %=)$ 
```

### Expected behavior
Playback can be paused and resumed using the OSC ⏯ button.

### Actual behavior
Playback becomes stuck and will not resume using the OSC ⏯ button. Once playback is stuck you can click the OSC ⏯ button over and over again and playback will not resume. Changing the playback position with the button showing ⏸ clears the problem and playback resumes.

This was reported against IINA in issue https://github.com/iina/iina/issues/4921.

### Log file

At the end of the log file you can see me clicking pause/resume over and over again without the video playing. Then I change the playback position and the video starts playing:
[mpv.log](https://github.com/mpv-player/mpv/files/15255377/mpv.log)

Process sample while playback is stuck:
[Sample of mpv.txt](https://github.com/mpv-player/mpv/files/15255378/Sample.of.mpv.txt)

### Sample files

I reproduced this using the Apple example file [Advanced stream
H.264/HEVC/UHD/Dolby Vision/Dolby Digital/Dolby Atmos](https://developer.apple.com/streaming/examples/advanced-stream-dv-atmos.html).

**Comment by Akemi** [comment]
pinging @ruihe774
