### ISSUE TITLE
MPV throwing increase the analyze duration and unknown codec error 

### ISSUE THREAD

**Issue by ghost152006** [mpv-player/mpv#14105]
mpv v0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 18 2024 06:31:17
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
Linux Distro: Arch Linux with Hyprland
GPU: Nvidia 1660ti Mobile Version
For running mpv i use this command:
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia mpv video.mkv
but in some videos it throws error like given below: 

[ffmpeg/demuxer] matroska,webm: Could not find codec parameters for stream 3 (Attachment: none): unknown codec
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[ffmpeg/demuxer] matroska,webm: Could not find codec parameters for stream 4 (Attachment: none): unknown codec
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[ffmpeg/demuxer] matroska,webm: Could not find codec parameters for stream 5 (Attachment: none): unknown codec
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[ffmpeg/demuxer] matroska,webm: Could not find codec parameters for stream 6 (Attachment: none): unknown codec
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' 
(5000000) options
[ffmpeg/demuxer] matroska,webm: Could not find codec parameters for stream 7 (Attachment: none): unknown codec
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[ffmpeg/demuxer] matroska,webm: Could not find codec parameters for stream 8 (Attachment: none): unknown codec
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[ffmpeg/demuxer] matroska,webm: Could not find codec parameters for stream 9 (Attachment: none): unknown codec
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[ffmpeg/demuxer] matroska,webm: Could not find codec parameters for stream 10 (Attachment: none): unknown codec
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[ffmpeg/demuxer] matroska,webm: Could not find codec parameters for stream 11 (Attachment: none): unknown codec
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
AO: [pipewire] 44100Hz stereo 2ch floatp

but with this command:
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia mpv --no-config video.mkv 
there is no error coming.
I tried deleting my mpv.conf and trying again but the same errors come only when using --no-config option that these errors disappear

my log file is below

[output.txt](https://github.com/mpv-player/mpv/files/15271639/output.txt)

this issue doesn't happen in every media I play only certain media

**Comment by CounterPillow** [comment]
>  I tried deleting my mpv.conf and trying again but the same errors come only when using --no-config option that these errors disappear

Then it's your scripts.

**Comment by llyyr** [comment]
this is an issue with the latest release of mpv-mpris cplugin 

upgrade it to master
