### ISSUE TITLE
Sourceforge mpv downloader.

### ISSUE THREAD

**Issue by DogancanYr** [mpv-player/mpv#14116]
1) When I download the latest version from Sourceforge from the download button and run it from the bat file, it extracts the files directly to the desktop without creating any folders. 
Create folders for files before the software downloads them.

2) Change the .bat and .zip file names to “automatic downloader”. Because it is not clear that it is a download assistant.

3) .bat file and when I use the numbers on the right it gives this error, when I use the numbers on the top it does not.

Please enter valid input key.
'timeout' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .

**Comment by llyyr** [comment]
mpv doesn't distribute any binaries. Contact whoever provides the Sourceforge binaries to report issues instead

**Comment by avih** [comment]
If you downloaded from here: https://sourceforge.net/projects/mpv-player-windows

Then the build is maintained here: https://github.com/shinchiro/mpv-winbuild-cmake and that's also where you should report it.

**Comment by DogancanYr** [comment]
> If you downloaded from here: https://sourceforge.net/projects/mpv-player-windows
> 
> Then the build is maintained here: https://github.com/shinchiro/mpv-winbuild-cmake and that's also where you should report it.

Thank you, I did it before your reply.
