### ISSUE TITLE
`--no-title-bar` mode the title bar appears after toggling fullscreen and window-maximized

### ISSUE THREAD

**Issue by verygoodlee** [mpv-player/mpv#14126]
### Important Information

Provide following Information:
- mpv version
```
mpv v0.38.0-209-g38741452 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May 12 2024 00:09:14
libplacebo version: v7.349.0 (v6.338.0-130-gbf1855c-dirty)
FFmpeg version: N-115182-g0d9591841
FFmpeg library versions:
   libavutil       59.17.100
   libavcodec      61.5.103
   libavformat     61.3.103
   libswscale      8.2.100
   libavfilter     10.2.101
   libswresample   5.2.100
```
- Windows Version
```
Win11 23H2 22631.3527
```
- Source of the mpv binary
https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20240512

### Reproduction steps
- input.conf
```
f osd-msg cycle fullscreen
x osd-msg cycle window-maximized
```
- run `mpv "any.mp4" --no-title-bar --no-input-default-bindings --pause=yes --autofit-larger=50%x50% --log-file=log.txt`
- cycle fullscreen to  yes
- cycle window-maximized to  yes
- cycle fullscreen to  no

### Expected behavior
N/A

### Actual behavior
a small title bar appears.
the left right and bottom borders disappears.
the rounded window corner changes to right angle window corner.
![屏幕截图 2024-05-12 210248](https://github.com/mpv-player/mpv/assets/45035465/286a37dd-8d32-48cc-a755-957f051290db)
 
### Log file
[log.txt](https://github.com/mpv-player/mpv/files/15286350/log.txt)

### Sample files
N/A

**Comment by kasper93** [comment]
I have a fix for that on my local branch, that's why I didn't see that.

**Comment by verygoodlee** [comment]
> I have a fix for that on my local branch, that's why I didn't see that.
> 
> Fixed by #14127 you can try build from there

it works.

**Comment by llyyr** [comment]
> same title bar is missing for me, on garuda distro 

open a new issue, this one is for windows and almost definitely completely unrelated to yours.

**Comment by verygoodlee** [comment]
can also reproduce with option `--no-title-bar --window-maximized=yes --auto-window-resize=yes`.

- load two videos with different aspect ratios to the playlist, such as 16:9 and 4:3
- run `playlist-next`

`auto-window-resize`  will resize the maximized window, then small title bar appears.

I think `auto-window-resize` should not work on maximized window, just as it doesn't work on fullscreen.
