### ISSUE TITLE
utils.subprocess(t) documentation misleading regarding "first array entry"

### ISSUE THREAD

**Issue by lvml** [mpv-player/mpv#1412]
The documentation of utils.subprocess(t) says:
```
...
        args
            Array of strings. The first array entry is the executable. 
```
As a programmer, I was naturally assuming that something like
```
t = {}
t["args"] = {}
t["args"][0] = "echo"
t["args"][1] = "blabla"
```
would work fine as the parameter for utils.subprocess(t) - but it turned out that mpv uses t["args"][1] as the executable name, trying to invoke "blabla" instead of "echo". 
If that is intended, the documentation shoud be clarified.

**Comment by wm4** [comment]
In Lua, the first array entry has index 1, and teaching Lua is out of scope of the manpage.

**Comment by lvml** [comment]
Wow, didn't expect this when I read in http://www.lua.org/pil/11.1.html
```
 You can start an array at index 0, 1, or any other value:
```
I didn't read to the point where it also says:
```
However, it is customary in Lua to start arrays with index 1.
```
What a weird language ;-)

**Comment by wm4** [comment]
PIL is not really right here; there are several builtin mechanisms which basically force you to start arrays at index 1.
