### ISSUE TITLE
Please allow users to disable and hide the floating progress bar completely.

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#14129]
Please allow users to disable and hide the floating progress bar completely.
Windows 10 | 11

Please allow users to disable and hide the floating progress bar completely. Since there is already a fixed progress bar at the bottom of the mpv, the floating progress bar is practically meaningless and obscures the playback screen.

For example, potplayer , vlc will not show the floating progress bar when fast forwarding and rewinding

So it is better to allow users to disable the floating progress bar completely and hide it.

![image](https://github.com/mpv-player/mpv/assets/54253524/f119e4ef-4e88-4448-8f1c-a850c9251490)

**Comment by zhouxinghong** [comment]
Since there is already a fixed progress bar at the bottom of the mpv, the floating progress bar is practically meaningless and obscures the playback screen.

**Comment by kasper93** [comment]
I told you what to do here https://github.com/mpv-player/mpv/discussions/14122#discussioncomment-9402545

Please don't create duplicated and issues. And don't create issues at all for questions, use discussions.
