### ISSUE TITLE
Tone map V-Log to PQ HDR

### ISSUE THREAD

**Issue by AndrewKeYanzhe** [mpv-player/mpv#14120]
Before requesting a new feature make sure it hasn't been requested yet.
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

### Expected behavior of the wanted feature

The user can set MPV to interpret videos as Panasonic V-Log, and MPV does color space conversion to PQ HDR (Rec 2100). This will utilise Apple's Extended Dynamic Range feature on macOS.

With the current build and the "--vf=format=gamma=v-log:colorlevels=full:primaries=v-gamut:sig-peak=10" flag, MPV tone maps V-Log to Rec709

### Log file

Even if you think it's not necessary at first, it might help us later to find
possible issues. Make a log file made with -v -v or --log-file=output.txt,
attach it to the issue, and replace this text with a link to it.

[output.txt](https://github.com/mpv-player/mpv/files/15284487/output.txt)

**Comment by Akemi** [comment]
> This will utilise Apple's Extended Dynamic Range feature on macOS.

this is completely unrelated to you feature request btw. EDR support can already be utilised by both supported macOS backends.

also aren't you just looking for `--target-prim=` and `--target-trc=`?

**Comment by AndrewKeYanzhe** [comment]
I tested mpv again with a standard PQ HDR video, and couldn't figure out how to enable EDR. 

I am using this config:

```
autofit-larger=100%x100%

loop-file=inf
--target-prim=bt.2020
--target-trc=pq
--icc-profile-auto
--target-colorspace-hint

--vo-gpu
```

The video is still tone mapped to SDR. Movist Pro can play the same video in EDR, so the file itself has no issues.

[output.txt](https://github.com/mpv-player/mpv/files/15285851/output.txt)

Could you help me with this? Thanks!

**Comment by Akemi** [comment]
- it's `vo=gpu` (no `vo-gpu`)
- if you want to use `target-colorspace-hint` use `vo=gpu-next`
- if you intended to use libmpv, as in your log, you also have to set the appropriate `cocoa-cb-output-csp=` option manually (this is only in master for now)
- `icc-profile-auto` and the `target-*` are mutually exclusive, so don't set it
- update your mpv to the latest version

```
[   0.000][e][cplayer] Error parsing option vo-gpu (option not found)
```

**Comment by AndrewKeYanzhe** [comment]
I have updated my config as 

```
autofit-larger=100%x100%
loop-file=inf

--target-colorspace-hint

--cocoa-cb-output-csp=bt.2100-pq

vo=gpu-next

```

When I launch MPV, the "Drop files to play here" window no longer appears. When I open a file using the menu bar, MPV crashes.
[output.txt](https://github.com/mpv-player/mpv/files/15286086/output.txt)

I am using the latest build by stolendata, [mpv-0.37](https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.37.0.tar.gz)

**Comment by Akemi** [comment]
there is no crash. mpv just can't initialise a `vo`, because you are not using the latest version with all features enabled.

```
[   0.060][v][vo/gpu-next/libplacebo] Failed creating instance: VK_ERROR_INCOMPATIBLE_DRIVER
[   0.060][v][vo/gpu-next/libplacebo] Failed initializing vulkan instance
[   0.060][e][vo/gpu-next] Failed initializing any suitable GPU context!
[   0.060][f][cplayer] Error opening/initializing the VO window.
```

you can try the latest nightly build at the bottom (Artifacts) [here](https://github.com/mpv-player/mpv/actions/runs/9045978977).

**Comment by AndrewKeYanzhe** [comment]
Thanks, I used the latest nightly build and tone mapping of V-Log into EDR works now. 

The only issue now is that upon closing mpv, the "mpv quit unexpectedly" dialogue pops up. 

I am using the following flags

```
--hwdec=auto-safe

--vf=format=gamma=v-log:colorlevels=full:primaries=v-gamut:sig-peak=10

--target-colorspace-hint
--cocoa-cb-output-csp=bt.2100-pq
vo=gpu-next
```

Disabling `target-colorspace-hint` will prevent the "mpv quit unexpectedly" dialogue, but EDR no longer works.

[output.txt](https://github.com/mpv-player/mpv/files/15286858/output.txt)
[crash report.txt](https://github.com/mpv-player/mpv/files/15286859/crash.report.txt)

**Comment by Akemi** [comment]
yeah this has been reported already #12666.

if you are suing `vo=gpu-next`, `cocoa-cb-output-csp` is not needed. `target-colorspace-hint` is enough.

i am closing this one then, since the only issue now has already been reported.
