### ISSUE TITLE
screenshot-template option ignored when playing from app bundle OS X

### ISSUE THREAD

**Issue by steinuil** [mpv-player/mpv#1414]
I have the screenshot-template option set in my config file along with other options.
Since updating mpv to 0.7.2 this option is just ignored when I play files by double-clicking on them/dragging them on the app icon/using `open -a /Applications/mpv.app file.mkv`. All the other options work as intended, but the screenshots are saved to my ~/Desktop folder.

The option somehow when I play a file from the terminal so I don't really know how to show the debug messages for this issue.

Also, I haven't updated mpv in a few weeks since ffmpeg had an upstream problem and I had to fix the homebrew formula myself so the problem might have already been there in 0.7 or 0.7.1

**Comment by wm4** [comment]
I think this was recently fixed in git.

**Comment by steinuil** [comment]
Oh, I'll try installing from head.

**Comment by steinuil** [comment]
Yep, I just installed the git version to test and it works.
