### ISSUE TITLE
v0.37.0 v0.38.0 high gpu usage in win10 22h2

### ISSUE THREAD

**Issue by trump888** [mpv-player/mpv#14164]
### Other Information

- Windows version:  windows10 22H2 19045 64bit
- GPU model, driver and version: intel Iris graphics 5100
- Source of mpv: v0.37.0 v0.38.0 release
- Introduced in version:

### Reproduction Steps

mpv ..\4k\Ducks.Take.Off.2160p.QHD.CRF25.x264-CtrlHD.mkv --hwdec

### Expected Behavior

low gpu usage ~ 40% ,no frame dropped like v0.36.0

 (+) Video --vid=1 (*) (h264 3840x2160 29.970fps)
Using hardware decoding (d3d11va).
VO: [gpu] 3840x2160 d3d11[nv12]
V: 00:00:16 / 00:00:16 (100%)

### Actual Behavior

high gpu usage ~ 88% ,some frame dropped

 (+) Video --vid=1 (*) (h264 3840x2160 29.970fps)
Using hardware decoding (d3d11va).
VO: [gpu] 3840x2160 d3d11[nv12]
V: 00:00:16 / 00:00:16 (100%) Dropped: 220

### Log File

[vo/gpu/d3d11] gpu-debug disabled due to error: 应用程序请求的操作依赖于已缺失或不匹配的 SDK 组件。 (0x887a002d)

sorry

### Sample Files

magnet:?xt=urn:btih:ae6ef5aeb22ae5305f62aaf7545dd7697d1aa794&dn=2160p+Demo&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.opentrackr.org:1337/announce

Ducks.Take.Off.2160p.QHD.CRF25.x264-CtrlHD.mkv

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
`--profile=fast`
