### ISSUE TITLE
What are the units of the equalizer?

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#14162]
Provide following Information:
- mpv version 0.38
- Windows Version

What are the units of the audio equalizer?

For example are the following lines correct:
`2.9dB 2.5dB 6.9dB -1.7dB ...`
`2.9b 2.5b 6.9b -1.7b ...`
`2.9 2.5 6.9 -1.7 ...`

**Comment by richardpl** [comment]
Which equalizer?

**Comment by richardpl** [comment]
Missing context.

**Comment by zhouxinghong** [comment]
OK! This issue is no longer important, thanks for your help. I'm about to close it.
