### ISSUE TITLE
Show codec flavor in stats also in passthrough mode

### ISSUE THREAD

**Issue by mitzsch** [mpv-player/mpv#14178]
### Expected behavior of the wanted feature

With the newest mpv it shows the codec flavor in the stats, as seen here => 

![image](https://github.com/mpv-player/mpv/assets/43502191/586f46b7-94a4-4ae9-b4a7-a9bde3ac02cc)

With passthrough enabled it only shows something like this =>

![current_state](https://github.com/mpv-player/mpv/assets/43502191/695d09cc-482e-4c2d-b880-623927c654e2)

It would be awesome if instead of [spdif_dts_hd] it would also show the codec with flavor like seen above. => e.g. for TrueHD/Atmos passthrough => _TrueHD [TrueHD + Atmos]_ or _spdif_truehd [TrueHD + Atmos]_ or _libavformat/spdifenc audio pass-through decoder [TrueHD + Atmos]_

Thanks!

**Comment by kasper93** [comment]
codec profile is not accessible, this information is given by the decoder after the actual data is decoded. In passthrough mode we only have codec. I've added missing desc https://github.com/mpv-player/mpv/pull/14179
