### ISSUE TITLE
MKV x264 video plays faster than audio

### ISSUE THREAD

**Issue by dcecile** [mpv-player/mpv#1417]
It seems like there's a decoding problem with my file that's causing audio/video desynchronisation. When I play it, the video races _ahead_ of the audio (so I don't think it's that my system is too slow).

To disqualify output driver issues and config issues, I've used this command line:

    mpv --vo=null --ao=null --no-config fast_video.mkv

And mpv still runs into desynchronisation:

    *************************************************
    **** Audio/Video desynchronisation detected! ****
    *************************************************
Here's the link to the first 3 MB of the file:

https://drive.google.com/file/d/0B710_jA5wFt5SFVxMkFqbjkxM2c/view?usp=sharing

**Comment by lachs0r** [comment]
Looks like something really failed at muxing the audio track and messed up all the timestamps. I don’t know how, but they look completely wrong.

My ffmpeg command-line-fu isn’t that good so I don’t know if there’s a single command to do this in one step, but you can run this to fix the issue with that file:

```
ffmpeg -i yourfile.mkv -vn -c copy audio.aac
ffmpeg -i audio.aac -i yourfile.mkv -c copy yourfile-fixed.mkv
```

Mind the order of command line arguments.

**Comment by dcecile** [comment]
Thanks, the ffmpeg remuxing fixed my file and now it plays without any problems.

I guess this issue can be closed because the timestamps in the file are bad?

**Comment by wm4** [comment]
Yes. Although we still don't know how the timestamps got broken. Anyway, broken file; we don't need to care until many more of such files surface.
