### ISSUE TITLE
Disable Night color on KDE temporarily

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#14180]
### Expected behavior of the wanted feature

KDE has a feature called Night color which shifts the colours during night to warmer shades in order to mess less with human sleep schedule. It is a great feature, but when I want to play a video at night (I use a projector hooked up to my computer), especially at fulltime, it distorts the content, which is something I really do not want. I can of course manually disable the feaure but it would be nice if MPV could do it automatically.

KDE provides either a DBUS method

    qdbus org.kde.kglobalaccel /component/kwin org.kde.kglobalaccel.Component.invokeShortcut "Toggle Night Color"

or a command like `kde-inhibit --nightLight mpv MYVIDEO` that also disables the feature when mpv is run.

### Alternative behavior of the wanted feature

I am not sure if this should be the case only when a video plays in fullscreen. Also not sure if this should be turned on by default on KDE or not.

**Comment by Dudemanguy** [comment]
This isn't mpv's job. This is for KDE. We don't have control over whatever the compositor/window manager does. dbus won't be implemented either. Feel free to write a script or something to call the dbus command (I assume it is possible but no idea). I would also assume you could configure it to not take affect if mpv is open, but again I dunno.

**Comment by felagund** [comment]
Ok, understood.

For anybody stumbling upon this, the needed script is here: https://gist.github.com/Zharkan/5f65ff9b1da85b2a2c79b777ed9e6199

Courtesy of https://www.reddit.com/r/kde/comments/ycd8k6/comment/l4xwtql/
