### ISSUE TITLE
Make sub-back-color follow text precisely

### ISSUE THREAD

**Issue by KonoVitoDa** [mpv-player/mpv#14194]
### Expected behavior of the wanted feature

I'd like that MPV's _sub-back-color_ looked like MPC-HC's _opaque box_, where the text of a shorter line is precisely covered by the back color, without the need of the box being a perfect rectangle:
![Screenshot (188)](https://github.com/mpv-player/mpv/assets/51209382/535e5621-4b99-40a1-b32d-8193f77cfd59)

On MPV on the other hand, it currently looks like this:
![Bakemonogatari 13 - Tsubasa Cat, Part 3 mkv_snapshot_20 13 921 【MPV】【LINES】 (MTBB (Honorifics))](https://github.com/mpv-player/mpv/assets/51209382/e96c2039-b300-47d0-ae7e-b18666a28229)

The _sub-back-color_ feature is important to me because I'm visually impaired and use it to improve subtitles' readability, but the way it looks like on MPV is not the ideal I suppose.
Btw, I don't want the current behavior to be completely withdrawn, just that an option to make this behavior customizable existed (_sub-back-precise=yes_ maybe? I can't think of a better name at the moment).

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/10464
