### ISSUE TITLE
consider supporting the XDG Base Directory Specification

### ISSUE THREAD

**Issue by ledti** [mpv-player/mpv#142]
http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

Mostly minor benefits here. This would allow mpv to be more dynamic with where its configuration and related files are located. 

It's an old standard and one which both MPlayer and MPlayer2 _still_ do not follow.

**Comment by Avamander** [comment]
@wm4
Why did you reintroduce non-standard behaviour in https://github.com/mpv-player/mpv/commit/269f0e743e5634691f0c9d5b1b8a4bb68eedbbd0? 

Nobody wants their home directory filled with crap that this non-standard behaviour causes.

**Comment by Avamander** [comment]
Also reopen this issue, because it's a problem again.
