### ISSUE TITLE
Video won't show with waylandvk, segfaults with x11vk

### ISSUE THREAD

**Issue by DemonicSavage** [mpv-player/mpv#14204]
### mpv Information

```bash
mpv v0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 18 2024 06:31:17
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version: Arch Linux
- Kernel Version: 6.9.1-zen1-1-zen
- GPU Model: RX 7800 XT
- Mesa/GPU Driver Version: Mesa 24.0.7-arch1.3
- Window Manager and Version: KWin 6.0.4.1-1 
- Source mpv: Arch repos
- Introduced in version:

### Reproduction Steps

mpv --no-config --vo=gpu-next --gpu-context=x11vk [FILE] 
mpv --no-config --vo=gpu-next --gpu-context=waylandvk [FILE]

### Expected Behavior

File plays normally

### Actual Behavior

With x11vk, there is a segfault. With waylandvk, the file plays, but shows no video (or even the mpv window)

### Log File

Wayland: https://pastebin.com/rPC9VhH6
X11: https://pastebin.com/QwqZUATf

X11 segfault backtrace: https://pastebin.com/k2ipvy7r

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by DemonicSavage** [comment]
An update: After a reboot, `waylandvk` also segfaults.
New logs: https://pastebin.com/yx16r835
Backtrace: https://pastebin.com/WtCcRS5f

**Comment by llyyr** [comment]
The segfaults are in `/usr/lib/libshaderc_shared.so.1`, seems like a broken system. You also don't have debug symbols for shaderc so hard to say anything concrete

**Comment by DemonicSavage** [comment]
It does seem libshaderc was the culprit - apparently I was using a weird AUR version of it. Using the official shaderc from the [extra] repo made it work.
