### ISSUE TITLE
Idle inhibit does not work with dmabuf-wayland video output on mutter

### ISSUE THREAD

**Issue by Digitalone1** [mpv-player/mpv#14206]
### mpv Information

```bash
mpv v0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 18 2024 06:31:17
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version: `Arch Linux`
- Kernel Version: `Linux 6.8.9-arch1-2`
- GPU Model: `VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Lucienne [1002:164c] (rev c2)`
- Mesa/GPU Driver Version: `4.6 (Compatibility Profile) Mesa 24.0.7-arch1.3`
- Window Manager and Version: `mutter 46.1`

### Reproduction Steps

- Start a video with `dmabuf-wayland` video output set
- Go full screen

### Expected Behavior

The screen does not turn off when `dmabuf-wayland` is set, just like it happens with `gpu`.

### Actual Behavior

The screen turns off when no key is pressed after the amount of time specified in Gnome settings. 

Setting the `gpu` video output, the screen does not turn off.

Tried also playing on the build compiled from the latest master branch. Setting `dmabuf-wayland` video output, the screen turns off.

### Log File

[output.txt](https://github.com/mpv-player/mpv/files/15395436/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Dudemanguy** [comment]
>[   2.049][v][vo/dmabuf-wayland/wayland] Enabling idle inhibitor

Can't possibly see how this could be our bug.

**Comment by Dudemanguy** [comment]
>I guess maybe mutter gets confused by the subsurfaces or something.

**Comment by Dudemanguy** [comment]
I guess it's possible that mutter considers the solid buffer surface always occluded and you wouldn't have this issue if you put blackbars on the video.

**Comment by Digitalone1** [comment]
> I guess it's possible that mutter considers the solid buffer surface always occluded and you wouldn't have this issue if you put blackbars on the video.

Black bars? It's easier to prepend `gnome-session-inhibit`. I just wanted to report the issue. If it's a Gnome problem, okay, I'll try to report to them.

**Comment by Dudemanguy** [comment]
It might be our problem. Do you get the issue if you playback a video that has visible black bars (e.g. 4:3 video fullscreen or use `--no-keepaspect` to stretch it something) else?

**Comment by Digitalone1** [comment]
@Dudemanguy I played a 21:9 video and the screen does not turn off with dmabuf. It happens when I play a 16:9 video.

**Comment by Dudemanguy** [comment]
Could you test #14209?

**Comment by Digitalone1** [comment]
> Could you test #14209?

Yes, it's working. You can close this issue. Thanks.
