### ISSUE TITLE
how to show stats when use libmpv?

### ISSUE THREAD

**Issue by stdiodavid** [mpv-player/mpv#14216]
### mpv Information

```bash
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 17 2024 19:18:44
libplacebo version: v6.338.2
FFmpeg version: 7.0
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Important Information

- Platform version: macos
- GPU model, driver and version: m3 (i don't know how to get version :)
- Source:
- Introduced in version:

### Reproduction Steps

I want something just like that : mpv_command(mpv_handel,"show status")

### Expected Behavior

show status ( like keypress "shift + i" )

### Actual Behavior

nothing 

### Log File

noneed

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by stdiodavid** [comment]
i tried  mpv_command ( mpv_handel,["keypress","i"] ),but get [input] warn: No key binding found for key 'i'.

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/9776
