### ISSUE TITLE
Separate osd from video frame in opengl-cb?

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1421]
For now, opengl-cb sub API renders osd on video frame with given viewport resolution.
This means that the viewport for FBO should be changed whenever the size of destination changed.
The most big problem here is that resizing FBO is not cheap.
Usually, the size of original video frame is fixed by decoder(and some options) so the size of FBO also can be fixed.
The texture of FBO will be upscaled by GPU when rendered on window and this job does not requires extra overhead.
But, with this method, the osd contents are already rendered on video frame so the resolution is limited to original video frame size.
This wasn't an issue for opengl-hq vo because it always renders on the screen backbuffer.

In my previous implmentation, I changed FBO resolution with some time interval so that the FBO is resized only once after resizing window is done.
But this causes blurry or dirty unscaled image for a while even if resizing done and it's quite annoying.
Well, I have to give up enhancing for OSD because it should be rendered with window resolution without scaling at the first time, but once OSD texture is sperated from video frame, the video frame can be rendered with real resolution by real-time at least because video frame can be upscaled by GPU without resizing FBO.

So, I think the solution(or workaround) for this problem is to proivde OSD contents as a sperated texture or render callback which takes its own fbo and viewport just like video frame render function.
If someone wants same behavior with previous implementation, he or she can call osd render function with same fbo and viewport of video frame.

Also, separating OSD can give more flexibility for instance one can easily extract video frame and give some effects without modifying subtitle.

And because this assumes that video frame will be rendered with a fixed size, a function to query size hint which determines the ideal fbo size would be helpful.

**Comment by wm4** [comment]
How would you render OSD without FBO (and resizing this FBO) then?

You don't need to resize the FBO every time. It's also possible to render to a larger texture, because it will use the provided viewport only. So for example you could just stretch the FBO while resizing, and resize the actual FBO when resizing is finished.

You can pass fbo=0 to render directly to the screen. But I think you're using qml, and qml makes this hard.

Also, one main point of the opengl-cb API is that the user can use mpv's OpenGL scaler, so providing this doesn't make much sense to me.

**Comment by xylosper** [comment]
> How would you render OSD without FBO (and resizing this FBO) then?

That's about what I said ' I have to give up enhancing for OSD ' and yeah, still OSD carries same problem, but at least I want to eliminate the limitation in video frame image.

> You can pass fbo=0 to render directly to the screen. But I think you're using qml, and qml makes this hard.

yes, exactly.

> Also, one main point of the opengl-cb API is that the user can use mpv's OpenGL scaler, so providing this doesn't make much sense to me.

Oh, I totally missed that. Maybe it won't be a problem then.
Close here and I'll reopen if I have a problem. Thank you!
