### ISSUE TITLE
mpv appears to randomly terminate with EOF while paused

### ISSUE THREAD

**Issue by CounterPillow** [mpv-player/mpv#14225]
### mpv Information

```bash
mpv v0.38.0-287-ge6e0aaa6c6 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May 20 2024 00:51:49
libplacebo version: v7.349.0 (v6.338.0-130-gbf1855c7)
FFmpeg version: N-115293-gd7fdd502d6
FFmpeg library versions:
   libavutil       59.17.100
   libavcodec      61.5.104
   libavformat     61.3.103
   libswscale      8.2.100
   libavfilter     10.2.102
   libswresample   5.2.100
```

### Other Information

- Linux version: Arch Linux
- Kernel Version: `Linux archbook 6.9.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000 x86_64 GNU/Linux`
- GPU Model: AMD Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15D8]
- Mesa/GPU Driver Version: `OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.7-arch1.3
` (mesa 24.0.7, radeonsi OpenGL driver atop amdgpu kernel module (the usual))
- Window Manager and Version: kwin_wayland 6.0.4.1
- Source mpv: mpv-build
- Introduced in version: Unknown

### Reproduction Steps

1. Open a YouTube video
2. Watch it for a bit, pause it
3. Leave computer, locking the session, to go do something else

### Expected Behavior

I can keep watching my caveman video where I left off

### Actual Behavior

Sometimes, rarely, the player closes with an EOF *while it is paused and has forward cache*. Annoying to try and reproduce as it does not appear to be consistent.

When it happens, I get a:
```
[1447.119][d][cplayer] Run command: stop, flags=64, args=[flags=""]
[1447.119][v][cplayer] EOF code: 4  
```

But I didn't run any stop command, unless some script (mpris?) is trolling me. I'm away from the computer when it happens, so it's hard to tell, and this is a recent-ish behaviour which does not fit the narrative of it being caused by a script I didn't update.

### Log File

https://overviewer.org/~pillow/up/9588dcf766/mpvlog-67120.log

Try to find a `[cplayer] Set property: pause -> 0`, I dare you.

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by sfan5** [comment]
Last time someone had this issue it was mpris I think. Can you reproduce without?

**Comment by CounterPillow** [comment]
I'll try, it'll take me a few days to make sure it's really truly gone.

**Comment by CounterPillow** [comment]
Hasn't reoccurred since I've disabled the mpris plugin. Looks like the kdeconnect updated something, and now when I either do actions on my desktop or my phone it might randomly terminate mpv on my laptop. That's nice.

Sorry for the noise.
