### ISSUE TITLE
Install mpv without yt-dlp packets

### ISSUE THREAD

**Issue by Gloster10** [mpv-player/mpv#14223]
### Expected behavior of the wanted feature

Ubuntu 22.04, installation of mpv via :
`sudo apt install mpv`
but an additional option to denied a re-installation of yt-dlp.
The PATH is on ~/.local/bin, where yt-dlp will be present.

Or a hint which mpv version I can install without yt-dlp features.

**Comment by kasper93** [comment]
> A version Tag of mpv without yt-dlp to compile it would also help.

mpv does not include yt-dlp, it uses external package found on system.

It is mpv option.
`mpv --script-opts=ytdl_hook-ytdl_path="~/.local/bin/yt-dlp"`

**Comment by Gloster10** [comment]
@kasper93 , 
for me yt-dlp is a standard package, imagine all applications who need ffmpeg does it make as a dependency package,
it would be for me a mess.

**Comment by kasper93** [comment]
> for me yt-dlp is a standard package

It is. And apt-get is installing this standalone package on your system.

>imagine all applications who need ffmpeg does it make as a dependency package,
> it would be for me a mess.

I don't understand what you mean. If ffmpeg is required for a given program to run it will be a dependency that is installed by you OS package manager.

Just to reiterate what I said before, mpv doesn't bundle yt-dlp in any way.
