### ISSUE TITLE
mpv 0.37+ always exits initial fullscreen onto monitor 0 when started with `fs=yes`, even when moved to another monitor

### ISSUE THREAD

**Issue by awused** [mpv-player/mpv#14226]
### mpv Information

```bash
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: 6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100

mpv v0.38.0-344-g2fa66b850d Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May 24 2024 14:41:05
libplacebo version: v6.338.2
FFmpeg version: 6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version: Fedora 40
- Kernel Version: 6.8.x (multiple versions)
- GPU Model: 4090
- Mesa/GPU Driver Version: NVIDIA 550.78 and earlier (seems irrelevant)
- Window Manager and Version: X11 + i3 version 4.23 (2023-10-29)
- Source mpv: git head as of today, fedora repos for 0.37.0, and git@v0.36.0 for 0.36
- Introduced in version: 0.37; does not reproduce on 0.36

### Reproduction Steps

* Use multiple monitors with i3 and `mpv --no-config --fs=yes`
* Use i3 to set a specific monitor for mpv that is not screen 0 on open OR manually move mpv to another monitor while still in the initial fullscreen
* Exit fullscreen (either through mpv or through an i3 shortcut)

relevant i3 config (not necessary, can move mpv manually instead):
```
set $wsmpv "mpv"
for_window [class="mpv"] floating enable move window to workspace $wsmpv focus
workspace $wsmpv output "DP-0"
```

### Expected Behavior

When I exit fullscreen mpv should remain on the current monitor as it did before 0.37.

### Actual Behavior

When I exit fullscreen mpv jumps to monitor 0, regardless of what monitor it was actually rendering on.

Exiting fullscreen later, on non-initial fullscreens, does work as expected (start fullscreen -> move to another monitor -> exit fullscreen and mpv behaves as expected, remaining on the monitor it was moved to).

### Log File

[output.txt](https://github.com/mpv-player/mpv/files/15440318/output.txt) (from 0.37)

```
[vo/gpu/x11] Display 0 (HDMI-0): [3200, 0, 5760, 1440] @ 119.997589 FPS
[vo/gpu/x11] Display 1 (DP-0): [2560, 1440, 6400, 3600] @ 119.998907 FPS
[vo/gpu/x11] Display 2 (DP-2): [6400, 2160, 8960, 3600] @ 119.997589 FPS
[vo/gpu/x11] Display 3 (DP-4): [0, 2160, 2560, 3600] @ 119.997589 FPS
```

I was watching the video on DP-0, where it was initially opened, and then closed fullscreen through mpv (pushed `F`) and it jumped to HDMI-0.

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by awused** [comment]
Bisected to 200992f90c49fdc2d5605cf79ffaa5247fd62e3e

**Comment by Dudemanguy** [comment]
I can reproduce this behavior with the i3 config you supplied but not if I simply move the fullscreen window somewhere else. Also it happens to me with 0.36.0 so I'm not even sure we're seeing the same thing.

>setting --fs-screen

This option and `--screen` has never worked for me on i3.

**Comment by awused** [comment]
Are you only counting the initial fullscreen on mpv startup? Any subsequent fullscreens are not affected.

Setting fs-screen just changes where the mpv window goes after the _initial_ fullscreen exits, and doesn't actually override which monitor i3 places the initial fullscreen on, nor what happens after any subsequent fullscreens. I bisected the issue to a specific commit added after 0.36, and cannot reproduce the issue with 0.36, so whatever you're seeing with 0.36 is a separate issue.

**Comment by Dudemanguy** [comment]
>Are you only counting the initial fullscreen on mpv startup?

Yes of course.

>Setting fs-screen just changes where the mpv window goes after the initial fullscreen exits

It doesn't do that for me. It just does nothing.

**Comment by Dudemanguy** [comment]
I found that I get can similar behavior but only if I force i3 to use floating windows for mpv. To be clear, this is what happens for me:

- set `for_window [class="mpv"] floating enable` in i3 config
- `mpv --no-config --fs video.mkv`
- move to another workspace (`shift+meta+2`)
- exit fullscreen (`f`)
- mpv exits fullscreen back onto the screen 0 instead of screen 1

And in my case, it always seems to exit fullscreen to whatever screen 0 is (primary or not doesn't appear to matter). If I don't float mpv, then it exits fullscreen and stays in the same screen as the window. This behavior is the same before 200992f90c49fdc2d5605cf79ffaa5247fd62e3e so again, not really sure we're seeing the same thing.

But anyways, does anything change for you if you simply comment out this line?

```
diff --git a/video/out/x11_common.c b/video/out/x11_common.c
index ec74a50f56..dfaac6153e 100644
--- a/video/out/x11_common.c
+++ b/video/out/x11_common.c
@@ -1667,7 +1667,7 @@ static void vo_x11_map_window(struct vo *vo, struct mp_rect rc)
         x11->fs = 1;
         // The "saved" positions are bogus, so reset them when leaving FS again.
         x11->size_changed_during_fs = true;
-        x11->pos_changed_during_fs = true;
+//        x11->pos_changed_during_fs = true;
     }
 
     if (x11->opts->fsscreen_id != -1) {
```

**Comment by awused** [comment]
Yeah, commenting out that one line seems to fix it. Though I'm actually moving the workspace to another output with mpv in it instead of moving mpv, maybe that's the difference in what you're seeing (`bindsym Mod1+Shift+Left move workspace to output left`).

**Comment by Dudemanguy** [comment]
I think just deleting that line is OK. But I'll try to do some more testing.

**Comment by awused** [comment]
I tested out git head, it's better but the mpv window isn't centered on the monitor after exiting fullscreen. Though this is also a problem even with 0.37 and `--fs-screen`, so it's not a new regression with #14228.
