### ISSUE TITLE
suboption parser cannot parse some string like "a, b" 

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1422]
For instance, if I run
```
mpv --vo=opengl-hq:icc-profile="a, b" video.mkv
```
I get an error:
```
Error parsing option vo (option parameter could not be parsed)
Setting commandline option --vo=opengl-hq:icc-profile=a, b failed.

Exiting... (Fatal error)
```

FYI, `"a,b"`(without space after comma) does not produce error.

**Comment by wm4** [comment]
You need to quote the string. In this case, the shell will strip the quotes, so you need to quote it twice, e.g. use ``'quotes'`` for the whole string.

**Comment by wm4** [comment]
Also, it would be nice if individual suboption could just be set by API, but we're not there yet. Programs and scripts can pass string suboptions by quoting them with a length, e.g.: ``--vo=opengl-hq:icc-profile=%3%a, b``, which tells the option parser that the string passed to the icc-profile suboption takes 3 bytes.

**Comment by xylosper** [comment]
Oh, okay thank you for the instructions.
