### ISSUE TITLE
Can't Play x.com Videos Anymore

### ISSUE THREAD

**Issue by InklingGirl** [mpv-player/mpv#14233]
### mpv Information

```bash
mpv v0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: n7.0
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Other Information

- Linux version: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
- Kernel Version: Linux 6.5.0-35-generic
- GPU Model: 03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev c2)
- Mesa/GPU Driver Version: Mesa 23.3.6 - kisak-mesa PPA (LLVM 15.0.7)
- Window Manager and Version: Wayland window server w/ Mutter 42.9-0ubuntu7.1 video compositor, GNOME 42.9 desktop environment
- Source mpv: Flatpak via https://flathub.org/apps/io.mpv.Mpv
- Introduced in version: N/A

### Reproduction Steps

`mpv <INSERT_ANY_X.COM_URL>`

### Expected Behavior

For the A/V to play in an `mpv` borderless window.

### Actual Behavior

```
Video to play[ytdl_hook] ERROR: Unsupported URL: https://x.com/shitposts_mp4/status/1794247036771942564
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.
```
A/V from https://x.com/ URLS does not play, likely because `mpv`/`youtube-dl` is still expecting a https://twitter.com/ URL.

### Log File

[output.txt](https://github.com/mpv-player/mpv/files/15445751/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
> `youtube-dl`

youtube-dl is unmaintained nowadays, switch to yt-dlp

**Comment by InklingGirl** [comment]
I do use `yt-dlp`.

**Comment by llyyr** [comment]
The commit that adds support for it isn't in any release yet, you need to install the nightly or master branch. https://github.com/yt-dlp/yt-dlp/commit/4813173e4544f125d6f2afc31e600727d761b8dd

Use something like pipx to install yt-dlp, `pipx install https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz`

Either way not a mpv issue.

**Comment by InklingGirl** [comment]
> The commit that adds support for it isn't in any release yet, you need to install the nightly or master branch. [yt-dlp/yt-dlp@4813173](https://github.com/yt-dlp/yt-dlp/commit/4813173e4544f125d6f2afc31e600727d761b8dd)
> 
> Use something like pipx to install yt-dlp, `pipx install https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz`
> 
> Either way not a mpv issue.

I did do just that @llyyr but x.com videos still don't won't stream, could it be because I'm using the Flatpak version of `mpv`?

**Comment by llyyr** [comment]
> I did do just that @llyyr but x.com videos still don't won't stream, could it be because I'm using the Flatpak version of `mpv`?

mpv version shouldn't matter, is mpv using the right yt-dlp executable? You can check with `which yt-dlp` and `whereis yt-dlp`

**Comment by InklingGirl** [comment]
So would that be `mpv which yt-dlp whereis yt-dlp` or `mpv which yt-dlp` & `mpv whereis yt-dlp`?

**Comment by llyyr** [comment]
yt-dlp just tagged a new release few hours ago, so you can probably just upgrade to it normally instead of installing from master https://github.com/yt-dlp/yt-dlp/releases/tag/2024.05.26

**Comment by InklingGirl** [comment]
Did that & `mpv` still can't stream from the site, even w/ `ytdl-raw-options=cookies=Documents/cookies.txt` (& I recently regenerated my cookies file w/ all the new x.com URL login credentials, too).

**Comment by llyyr** [comment]
> Did that & `mpv` still can't stream from the site, even w/ `ytdl-raw-options=cookies=Documents/cookies.txt` (& I recently regenerated my cookies file w/ all the new x.com URL login credentials, too).

does `yt-dlp x.com/something` work? If not then it's a yt-dlp issue

**Comment by InklingGirl** [comment]
> does `yt-dlp x.com/something` work? If not then it's a yt-dlp issue

Yeah that works, I do it multiple times per day, so it is `mpv` &/or its interactions w/ `yt-dlp`.

**Comment by llyyr** [comment]
Can you regenerate the log file with updated yt-dlp? In the previous one, yt-dlp just says the url isn't supported because it wasn't at that version.

**Comment by InklingGirl** [comment]
Here you go: [output-redux.txt](https://github.com/mpv-player/mpv/files/15454774/output-redux.txt)

**Comment by InklingGirl** [comment]
I have no idea how to fix that. How should I proceed?

**Comment by llyyr** [comment]
Explicitly point mpv to the yt-dlp executable that you know for sure is updated. `--script-opts=ytdl_hook-ytdl_path=/home/christian/.local/bin/yt-dlp` or wherever it is

**Comment by InklingGirl** [comment]
> `--script-opts=ytdl_hook-ytdl_path=/home/christian/.local/bin/yt-dlp`

Is that a command I can just run on its own or appended to `mpv`?

**Comment by llyyr** [comment]
> Is that a command I can just run on its own or appended to `mpv`?

It's a mpv flag so you run it appended to mpv like `mpv --script-opts=...`, if it works then you can put it inside your mpv config file later after removing the `--`

**Comment by InklingGirl** [comment]
> if it works then you can put it inside your mpv config file later after removing the `--`

I was going to ask that next. I will try.

**Comment by InklingGirl** [comment]
This is the output:
```bash
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "/home/christian/.local/bin/yt-dlp", line 5, in <module>
[ytdl_hook]     from yt_dlp import main
[ytdl_hook] ModuleNotFoundError: No module named 'yt_dlp'
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.
Exiting... (Errors when loading file)

**Comment by InklingGirl** [comment]
Huh, I regenerated the cookies.txt file & `mpv` can stream from x.com now.
