### ISSUE TITLE
Referrer functionality is broken

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#14232]
### mpv Information

mpv v0.38.0-352-g88f20a70 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May 26 2024 00:08:49
libplacebo version: v7.349.0 (v6.338.0-133-g9e1257c-dirty)
FFmpeg version: N-115388-ge9197db4f
FFmpeg library versions:
   libavutil       59.20.100
   libavcodec      61.5.104
   libavformat     61.3.104
   libswscale      8.2.100
   libavfilter     10.2.102
   libswresample   5.2.100

### Other Information

- Windows version: 10 19044
- GPU model, driver and version: GTX 1660
- Source of mpv: https://icolo.dl.sourceforge.net/project/mpv-player-windows/64bit/mpv-x86_64-20240526-git-88f20a7.7z?viasf=1
- Introduced in version:

### Reproduction Steps

Previous versions of the referrer function were intact and could successfully play streams.
```
 mpv --no-config --referrer="https://yvgdwtamlx.sw-cdnstreamwish.com" "https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0.4&sp=500&p1=tszfjzanyeke&p2=tszfjzanyeke&asn=13335"
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0.4&sp=500&p1=tszfjzanyeke&p2=tszfjzanyeke&asn=13335.
Exiting... (Errors when loading file)
```

### Expected Behavior

Streaming media could be played successfully

### Actual Behavior

Cannot play streams successfully

### Log File

```
 mpv --no-config --referrer="https://yvgdwtamlx.sw-cdnstreamwish.com" "https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0.4&sp=500&p1=tszfjzanyeke&p2=tszfjzanyeke&asn=13335"
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0.4&sp=500&p1=tszfjzanyeke&p2=tszfjzanyeke&asn=13335.
Exiting... (Errors when loading file)
```

```
 yt-dlp --referer "https://yvgdwtamlx.sw-cdnstreamwish.com" "https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0.4&sp=500&p1=tszfjzanyeke&p2=tszfjzanyeke&asn=13335"
[generic] Extracting URL: https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1....zfjzanyeke&asn=13335
[generic] index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0: Downloading webpage
[generic] index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0: Downloading m3u8 information
[generic] index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0: Checking m3u8 live status
[info] index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0: Downloading 1 format(s): 0
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Total fragments: 1441
[download] Destination: index-f3-v1-a1 [index-f3-v1-a1.m3u8？t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0].mp4
[download]   100% of ~ 815.34MiB at  118.15KiB/s ETA 02:55:24 (frag 1/1441)
```

### Sample Files

```
mpv --no-config --referrer="https://yvgdwtamlx.sw-cdnstreamwish.com" "https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0.4&sp=500&p1=tszfjzanyeke&p2=tszfjzanyeke&asn=13335"
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0.4&sp=500&p1=tszfjzanyeke&p2=tszfjzanyeke&asn=13335.
Exiting... (Errors when loading file)
```

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
> yt-dlp --referer "https://yvgdwtamlx.sw-cdnstreamwish.com" "https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0.4&sp=500&p1=tszfjzanyeke&p2=tszfjzanyeke&asn=13335"

mpv does pass on the referer header to ffmpeg, so not our bug. This doesn't work for me even with yt-dlp

**Comment by zhouxinghong** [comment]
yt-dlp --referer "https://yvgdwtamlx.sw-cdnstreamwish.com" "https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0.4&sp=500&p1=tszfjzanyeke&p2=tszfjzanyeke&asn=13335"
[generic] Extracting URL: https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1....zfjzanyeke&asn=13335
[generic] index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0: Downloading webpage
[generic] index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0: Downloading m3u8 information
[generic] index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0: Checking m3u8 live status
[info] index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0: Downloading 1 format(s): 0
[hlsnative] Downloading m3u8 manifest
WARNING: Live HLS streams are not supported by the native downloader. If this is a livestream, please add "--downloader ffmpeg --hls-use-mpegts" to your command
[hlsnative] Total fragments: 1441
[download] Destination: index-f3-v1-a1 [index-f3-v1-a1.m3u8？t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0].mp4
[download]   100% of ~ 815.34MiB at  118.15KiB/s ETA 02:55:24 (frag 1/1441)

yt-dlp can be parsed and downloaded successfully, then it means that there is indeed an error in MPV's internal processing of the --referer "https://xxxx", which would not have occurred in previous versions of MPV.

**Comment by llyyr** [comment]
mpv is passing the referrer correctly. And I can't access the url even with a referrer.

```
$ yt-dlp --referer "https://yvgdwtamlx.sw-cdnstreamwish.com" "https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0.4&sp=500&p1=tszfjzanyeke&p2=tszfjzanyeke&asn=13335"
WARNING: Post-Processor arguments given without specifying name. The arguments will be given to all post-processors
[generic] Extracting URL: https://yvgdwtamlx.sw-cdnstreamwish.com/hls2/01/03281/4xrcbhc315g5_,n,h,x,.urlset/index-f3-v1-a1....zfjzanyeke&asn=13335
[generic] index-f3-v1-a1.m3u8?t=guh4Q3kjwKSUAGNBMU3AZpVdCDK9CTLhix3sQTHmpyY&s=1716686339&e=129600&f=16488058&srv=tszfjzanyeke&i=0: Downloading webpage
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
```

**Comment by zhouxinghong** [comment]
The link above is no longer working, please try the link below again:

**Comment by zhouxinghong** [comment]
To avoid delaying you, I'll close it for now. I will open it again when I find a valid test link. Thank you very much for your help! 👍

**Comment by llyyr** [comment]
> I will open it again when I find a valid test link

But there is no issue here, mpv is using the referrer correctly. You should check your yt-dlp config to see if you're doing something else to mitigate the 403.

You can check yourself with a toy http server and using mpv to access something from it.

When I do `mpv http://0.0.0.0:8080/image0.jpg --referrer="mpv sucks"`, I can see on my http server that the referrer is used correctly.

```
$ darkhttpd .
darkhttpd/1.14, copyright (c) 2003-2022 Emil Mikulic.
listening on: http://0.0.0.0:8080/
127.0.0.1 - - [26/May/2024:12:26:45 +0530] "GET /image0.jpg HTTP/1.1" 206 285035 "mpv sucks" "libmpv"
```

You probably more likely need to set an user agent that's not "libmpv" to not get 403'd.

**Comment by zhouxinghong** [comment]
`You probably more likely need to set an user agent that's not "libmpv" to not get 403'd.`
Thank you very much for the explanation! 👍
How do I set up a non-"libmpv" user agent? 😜

**Comment by llyyr** [comment]
https://mpv.io/manual/master/#options-user-agent

**Comment by zhouxinghong** [comment]
Can you give me an example?

**Comment by llyyr** [comment]
> Can you give an example of using the code?

`--user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"`

**Comment by zhouxinghong** [comment]
Thank you very much for your help 👍! I'll try this one later on.
