### ISSUE TITLE
Stats.lua reports VP9 video as H264 when --script-opts=ytdl_hook-all_formats=yes is passed

### ISSUE THREAD

**Issue by NotMithical** [mpv-player/mpv#14243]
### mpv Information

```bash
mpv v0.38.0-352-g88f20a70 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May 25 2024 21:05:51
libplacebo version: v7.349.0 (v6.338.0-133-g9e1257c-dirty)
FFmpeg version: N-115390-g0b2316e37
FFmpeg library versions:
   libavutil       59.20.100
   libavcodec      61.5.104
   libavformat     61.3.104
   libswscale      8.2.100
   libavfilter     10.2.102
   libswresample   5.2.100
```

### Other Information

- Windows version: 10.0.19045.4412
- GPU model, driver and version: MSI Ventus GeForce RTX 4060, Nvidia Game-ready driver version 551.86
- Source of mpv: https://github.com/zhongfly/mpv-winbuild
- Introduced in version: Unsure

### Reproduction Steps

1. Using yt-dlp `--list-formats` on a youtube link, find a format that uses the VP9 codec
2. Load the video, selecting the video track found in step 1 and passing `--script-opts=ytdl_hook-all_formats=yes`, for example: `.\mpv.exe --no-config --script-opts=ytdl_hook-all_formats=yes --vid=1 https://www.youtube.com/watch?v=oqsDQ7Zjpnc`
3. Open stats page 1 and observe the codec information in line 1 of the video section

### Expected Behavior

Stats.lua reports the currently playing video track as using VP9, as can be confirmed by yt-dlp or ffprobe if the video has been downloaded. (MPV also correctly reports it as VP9 if `--script-opts=ytdl_hook-all_formats=yes` is omitted, or if the video URL is acquired through `yt-dlp --get-url` and loaded into MPV that way)

### Actual Behavior

Stats.lua reports the codec as "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [h264]"

### Log File

[output.txt](https://github.com/mpv-player/mpv/files/15450136/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
Why do you assume that `--vid=1` is the VP9 stream? That is selected with `--ytdl-format`.

**Comment by NotMithical** [comment]
I'm not assuming. I know with that link `--vid=1` gives me the same stream as if I set `--ytdl-format` and I used the former because it was faster to type when I was repeatedly testing this. I did also skim through the log file myself and I know MPV opens the VP9 decoder for that stream.

Apologies for the confusion, let me know if it would be better for me to reproduce the log file using `--ytdl-format` instead for consistency.

**Comment by guidocella** [comment]
I see. Well I can't reproduce it as stats.lua shows VP9 for me with that command.

**Comment by NotMithical** [comment]
Thank you for checking. I've just tried that command on one of my linux machines and was unable to reproduce there as well, although a different command did give me the same result. I noticed another thing though; when I press ` to open the console, on the linux machine I tested "vp9" is shown in the stream information alongside resolution, fps, etc whereas on windows it says "null" as the codec on most of the same streams.

It didn't occur to me that that might be relevant as the console has always shown null on vp9 streams for me while the stats page issue is new.

**Comment by guidocella** [comment]
Maybe you're using different yt-dlp versions?

**Comment by NotMithical** [comment]
`yt-dlp --version` gives me 2024.05.26 on both systems. However I also ran `yt-dlp --list-formats https://www.youtube.com/watch?v=oqsDQ7Zjpnc` on both to ensure I got the same results, which it does for the most part except on windows I get more detailed codec info on the vp9 streams (e.g. `vp09.00.50.08`) while on linux it just says `vp9`.

**Comment by NotMithical** [comment]
Nothing in my system has changed but this appears to have resolved itself completely.
