### ISSUE TITLE
UI is all stretched since a recent update

### ISSUE THREAD

**Issue by RaylaLe100** [mpv-player/mpv#14249]
### mpv Information

```bash
mpv v0.38.0-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May 23 2024 10:29:03
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version: EndeavourOS
- Kernel Version: 6.9.2-arch1-1
- GPU Model: 2d:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] [1002:73ff] (rev c1)
- Mesa/GPU Driver Version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.8-arch1.1
- Introduced in version: less than a month ago
![image](https://github.com/mpv-player/mpv/assets/48224109/cff1cf08-bb8f-419d-830e-9ca7d0e41abf)

### Reproduction Steps

No reproduction steps are needed, the bug appears as-is.

### Expected Behavior

Having a normally-sized UI.

### Actual Behavior

The UI is stretched vertically (almost 2:1 I would say)

### Log File

[output.txt](https://github.com/mpv-player/mpv/files/15461766/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
`--script-opts=osc-vidscale=yes` See https://github.com/mpv-player/mpv/pull/14158 for info
