### ISSUE TITLE
vo_gpu_next/d3d11: `--d3d11-output-format=auto` selects the wrong output format

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#14242]
### mpv Information

```bash
mpv v0.38.0-344-g2fa66b85 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May 25 2024 00:09:40
libplacebo version: v7.349.0 (v6.338.0-133-g9e1257c-dirty)
FFmpeg version: N-115376-gaff24c165
FFmpeg library versions:
   libavutil       59.20.100
   libavcodec      61.5.104
   libavformat     61.3.104
   libswscale      8.2.100
   libavfilter     10.2.102
   libswresample   5.2.100
```

### Other Information

- Windows version: Windows 11 10.0.22631.3593
- GPU model, driver and version: AMD 24.5.1
- Source of mpv: shinchiro
- Introduced in version: n/a

### Reproduction Steps

```
mpv --vo=gpu-next --gpu-api=d3d11 <file>
```

### Expected Behavior

libplacebo selects rgba8 because that's the configured bit depth of the device.

### Actual Behavior

libplacebo selects rgb10_a2 instead, which results in the driver having to apply its own dithering in addition to whatever mpv is doing. `--d3d11-output-format=rgba8` has to be stated explicitly.

### Log File

[mpv.log](https://github.com/mpv-player/mpv/files/15449399/mpv.log)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
`--d3d11-output-format` options doesn't really have control over libplacebo. Only supported value is `--d3d11-output-format=rgba8` and still it is only a hint, to not use 10-bit for sdr.

I guess we can add a output depth check in libplacebo and prefer matching format.

**Comment by ruihe774** [comment]
> I also tried opengl, but opengl seems to be broken in its own way, since the log doesn't show a selected format and the stats screen just shows "fbo".

There is `[vo/gpu-next/libplacebo] (Re)creating 1920x1080x0 texture with format ...` in the log showing the selected format. `--fbo-format` has no control over the texture selection logic in libplacebo.

**Comment by ruihe774** [comment]
> This is unrelated to output format.

In OpenGL, the output format *is* the fbo format.

**Comment by lextra2** [comment]
not this sh*t again...
AMDs driver [temporal dithers](https://gpuopen-librariesandsdks.github.io/adl/group__define__dither__states.html) to what ever bit depth your display is set to in their driver UI
Having MPV output 10bit or 8bit won't matter in that case.

**Comment by Jules-A** [comment]
> not this sh*t again... AMDs driver [temporal dithers](https://gpuopen-librariesandsdks.github.io/adl/group__define__dither__states.html) (at all times) to what ever bit depth your display is set to in their driver UI Having MPV output 10bit or 8bit won't matter in that case.

Huh? I don't think it dithers if the output is already 10bit... If I don't set 10bit manually in MPV the image loses some detail compared to setting to 10bit and ordered in MPV. I assume AMD is using a speed focused algorithm and the more expensive MPV options work out better.

**Comment by lextra2** [comment]
> >  I assume AMD is using a speed focused algorithm and the more expensive MPV options work out better quality.

That would be correct.

**Comment by lextra2** [comment]
> 
> Well, the funniest thing just happened actually. Ever since AMD 24.6.1, `vulkan` has started offering the rgb10_a2 format, which gets autoselected by mpv now.

Nice. Thanks for the info!
AMD has indeed added 10 bit support for vulkan with their newest 24.6.1 WHQL drivers.

`C:\Windows\System32\vulkaninfo.exe` shows a new entry for that under `Presentable Surfaces` > `FORMAT_A2B10G10R10_UNORM_PACK32`

Too bad they didn't write that into their patch notes.
