### ISSUE TITLE
Unable to Cross-Compile Using MXE on Ubuntu 24.04

### ISSUE THREAD

**Issue by SiddaramMavinamar** [mpv-player/mpv#14259]
### Important Information

- mpv version: v0.38.0
- Platform version: Ubuntu 24.04
- Meson version: 1.3.2

### Reproduction Steps

git clone https://github.com/mxe/mxe.git
cd mxe
echo "JOBS := 4" >> settings.mk
 echo "MXE_TARGETS := x86_64-w64-mingw32.static" >> settings.mk
make gcc ffmpeg libass jpeg lua luajit
export PATH=/mxe/usr/bin:$PATH
git clone https://github.com/mpv-player/mpv.git
cd mpv
meson setup build --cross-file crossfile.txt -Dlibmpv=true

### Expected Behavior

The build process should complete successfully with all dependencies properly resolved and compiled, resulting in a functional cross-compiled version of MPV.

### Actual Behavior

The build process fails with the error indicating that the libplacebo dependency is not found. Attempts to use pkg-config and cmake to resolve this dependency have been unsuccessful.

Observed that MXE does not have a makefile for libplacebo.
Tried to link libplacebo manually but encountered the same error.

### Log File

![image](https://github.com/mpv-player/mpv/assets/142959336/b2dbe7e5-b68a-4eff-873c-37b02f4f05e1)

Observed that MXE does not have a makefile for libplacebo.
Tried to link libplacebo manually but encountered the same error.

crosstextfile.txt
[binaries]
c = 'x86_64-w64-mingw32.static-gcc'
cpp = 'x86_64-w64-mingw32.static-g++'
ar = 'x86_64-w64-mingw32.static-ar'
strip = 'x86_64-w64-mingw32.static-strip'
pkg-config = 'x86_64-w64-mingw32.static-pkg-config'
exe_wrapper = 'wine64'

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of parameters, and conditions used in "Reproduction Steps".
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.

**Comment by ruihe774** [comment]
You can clone libplacebo source and put it in `mpv/subprojects/libplacebo`. Meson can then find it.

**Comment by SiddaramMavinamar** [comment]
> You can clone libplacebo source and put it in `mpv/subprojects/libplacebo`. Meson can then find it. BTW I think you may convert this to a discussion.

I have followed this step but not helping it out we have to find the way MXE should have that file or create make file in source (this is my assumption) any suggestion would be appreciated

**Comment by kasper93** [comment]
MXE is not supported and won't be until they add libplacebo for example. Also there is zero gain to use it, Meson can do all of it better already.

**Comment by SiddaramMavinamar** [comment]
> MXE is not supported and won't be until they add libplacebo for example. Also there is zero gain to use it, Meson can do all of it better already.

Hi @kasper93 
What is the best way to build MPV with static linking on both Linux and Windows natively, applying -Dgpl = false, and producing a static mpv.exe without any dependency DLLs?

Thanks for your suggestion and help
