### ISSUE TITLE
dvb_subtitle size doesn't match video

### ISSUE THREAD

**Issue by JarekMotion** [mpv-player/mpv#1425]
I have Mpegts video (mpeg2video/ac3/dvb_subtitles) where dvb subtitles are not aligned with video:

![shot0002](https://cloud.githubusercontent.com/assets/10405857/5617630/94719194-9508-11e4-883a-87979e965fe6.jpg)

however other subtitle stream in the same video is fine:

![shot0003](https://cloud.githubusercontent.com/assets/10405857/5617631/9471c3e4-9508-11e4-9eac-34b7e268805e.jpg)

 I observed that ffmpeg see the subtitles in the same manner but one can rescale them easily. It would be nice to have it done automatically or by manual rescaling.
Cheers

tested with mpv-master/ffmpeg 2.5.1.:
build/mpv video.ts -vo vdpau -ao alsa --sid 1

**Comment by wm4** [comment]
A sample file would be great.

**Comment by JarekMotion** [comment]
Short sample. There are 8 subtitles and first four are not properly rescaled, the next four are fine
http://54.171.59.211/video/video.ts

**Comment by wm4** [comment]
It should be fixed now.

**Comment by JarekMotion** [comment]
Yes, this is it. Thank you.
