### ISSUE TITLE
Unsupported hwdec: vulkan

### ISSUE THREAD

**Issue by fastrizwaan** [mpv-player/mpv#14269]
### mpv Information

```bash
mpv v0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: n7.0.1
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Other Information

- Linux version: fedora silverblue 
- Kernel Version:
- GPU Model:
- Mesa/GPU Driver Version:
- Window Manager and Version:
- Source mpv:
- Introduced in version:

# System Details Report
---

## Report details
- **Date generated:**                              2024-06-01 07:01:15

## Hardware Information:
- **Hardware Model:**                              FUTOPIA GLOBAL Private Limited ULTIMUS ELITE
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i5-1035G4 × 8
- **Graphics:**                                    Intel® Iris® Plus Graphics (ICL GT1.5)
- **Disk Capacity:**                               512.1 GB

## Software Information:
- **Firmware Version:**                            ICL_IC525_V1.0.4
- **OS Name:**                                     Fedora Linux 40.20240527.0 (Silverblue)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.10-300.fc40.x86_64

### Reproduction Steps

https://github.com/mpv-player/mpv/issues/11739 (hwdec vulkan guide)

```
flatpak run --filesystem=host io.mpv.Mpv  --hwdec=vulkan --gpu-api=vulkan --gpu-context=waylandvk 202*.mp4
Playing: 2024_05_01_11_08_42_cut_de603f9c-9cd9-4c23-a6a8-fcc8330634c7.mp4
 (+) Video --vid=1 (*) (h264 854x480 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
Unsupported hwdec: vulkan
AO: [pipewire] 44100Hz stereo 2ch floatp

```
do I need to add remove any switches or options for hwdec=vulkan to work?
https://github.com/flathub/io.mpv.Mpv/blob/master/io.mpv.Mpv.yml

### Expected Behavior

https://github.com/mpv-player/mpv/issues/11739

### Actual Behavior

well hwdec should work with vulkan

### Log File

[output.txt](https://github.com/user-attachments/files/15519895/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by ruihe774** [comment]
https://github.com/mpv-player/mpv/discussions/13909

> - Intel
>   - You must set `ANV_VIDEO_DECODE=1` in your environment to expose video decoding

**Comment by llyyr** [comment]
> #13909
> 
> > * Intel
> >   
> >   * You must set `ANV_VIDEO_DECODE=1` in your environment to expose video decoding

It shouldn't be this, because if that was the case you'd get a warning about missing "video_queue" extension from FFmpeg, rather than unsupported hwdec argument.

**Comment by philipl** [comment]
You should be using `--vo=gpu-next` as documented in the guide.

**Comment by fastrizwaan** [comment]
tried this but got the same error `Unsupported hwdec: vulkan`

```
export ANV_VIDEO_DECODE=1; flatpak run --env=ANV_VIDEO_DECODE=1 --filesystem=host --command=mpv io.mpv.Mpv --vo=gpu-next --hwdec=vulkan --gpu-api=vulkan --gpu-context=waylandvk 2*
```

Same error:
```
Playing: 2024_05_01_11_08_42_cut_de603f9c-9cd9-4c23-a6a8-fcc8330634c7.mp4
 (+) Video --vid=1 (*) (h264 854x480 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)

Unsupported hwdec: vulkan
AO: [pipewire] 44100Hz stereo 2ch floatp
VO: [gpu-next] 854x480 yuv420p
AV: 00:00:01 / 00:00
```

**Comment by llyyr** [comment]
Can you try if a mpv binary not inside a flatpak works?

**Comment by llyyr** [comment]
The ffmpeg built inside that flatpak doesn't have vulkan hwaccel, so you need to build ffmpeg with `--enable-vulkan`

**Comment by fastrizwaan** [comment]
ffmpeg n7.0.1 fails with vulkan headers not found. but ffmpeg n6.1.1 starts the build process fails:
```

libavcodec/nvenc.c: In function ‘nvenc_setup_hevc_config’:
libavcodec/nvenc.c:1373:9: error: ‘NV_ENC_CONFIG_HEVC’ has no member named ‘pixelBitDepthMinus8’
 1373 |   hevc->pixelBitDepthMinus8 = IS_10BIT(ctx->data_pix_fmt) ? 2 : 0;
   |     ^~
libavcodec/nvenc.c: In function ‘nvenc_setup_av1_config’:
libavcodec/nvenc.c:1458:8: error: ‘NV_ENC_CONFIG_AV1’ has no member named ‘inputPixelBitDepthMinus8’
 1458 |   av1->inputPixelBitDepthMinus8 = IS_10BIT(ctx->data_pix_fmt) ? 2 : 0;
   |    ^~
libavcodec/nvenc.c:1459:8: error: ‘NV_ENC_CONFIG_AV1’ has no member named ‘pixelBitDepthMinus8’
 1459 |   av1->pixelBitDepthMinus8 = (IS_10BIT(ctx->data_pix_fmt) || ctx->highbitdepth) ? 2 : 0;
   |    ^~
CC	libavcodec/on2avcdata.o
libavcodec/nvenc.c: In function ‘nvenc_map_buffer_format’:
libavcodec/nvenc.c:1692:16: error: ‘NV_ENC_BUFFER_FORMAT_YV12_PL’ undeclared (first use in this function); did you mean ‘NV_ENC_BUFFER_FORMAT_YV12’?
 1692 |     return NV_ENC_BUFFER_FORMAT_YV12_PL;
   |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
   |        NV_ENC_BUFFER_FORMAT_YV12
libavcodec/nvenc.c:1692:16: note: each undeclared identifier is reported only once for each function it appears in
libavcodec/nvenc.c:1694:16: error: ‘NV_ENC_BUFFER_FORMAT_NV12_PL’ undeclared (first use in this function); did you mean ‘NV_ENC_BUFFER_FORMAT_NV12’?
 1694 |     return NV_ENC_BUFFER_FORMAT_NV12_PL;
   |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
   |        NV_ENC_BUFFER_FORMAT_NV12
libavcodec/nvenc.c:1700:16: error: ‘NV_ENC_BUFFER_FORMAT_YUV444_PL’ undeclared (first use in this function); did you mean ‘NV_ENC_BUFFER_FORMAT_YUV444’?
 1700 |     return NV_ENC_BUFFER_FORMAT_YUV444_PL;
   |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   |        NV_ENC_BUFFER_FORMAT_YUV444
CC	libavcodec/options.o
CC	libavcodec/opus_celt.o
make: *** [ffbuild/common.mak:81: libavcodec/nvenc.o] Error 1
make: *** Waiting for unfinished jobs....
Error: module ffmpeg: Child process exited with code 2
```
perhaps the above need patches.

I've emailed the issue to ffmpeg-user@ffmpeg.org. 

Closing as this is related to ffmpeg and no mpv.

Thanks.
