### ISSUE TITLE
Turn off subtitles automatically.

### ISSUE THREAD

**Issue by DogancanYr** [mpv-player/mpv#14274]
### Expected behavior of the wanted feature

--slang=en,eng,none
I thought the None part should completely close the subtitles.

**Comment by llyyr** [comment]
You probably want `--subs-fallback=no`

**Comment by utkuefe856-bit** [comment]
Hocam size ait herhangi bir iletisim bilgisine nasil ulasabilirim acaba?

**Comment by DogancanYr** [comment]
> Hocam size ait herhangi bir iletisim bilgisine nasil ulasabilirim acaba?

Discorda gel. DogancanYr

**Comment by utkuefe856-bit** [comment]
> > Hocam size ait herhangi bir iletisim bilgisine nasil ulasabilirim acaba?
> 
> Discorda gel. DogancanYr

Istek gonderdim hocam.
