### ISSUE TITLE
Add option for rounded corner radius on subtitle backgrounds

### ISSUE THREAD

**Issue by addisonxx** [mpv-player/mpv#14270]
I have seen this requested a few times and would like to add in another vote for this feature. I have been having to use HTML video players since I can use CSS to customize the subtitle backgrounds. I really hope MPV could add this as an option because then I could view videos in IINA, which is far better experience. It seems like such a small change, but really helps modernize the look and makes the subtitles blend in seamlessly.

**Comment by hooke007** [comment]
dup https://github.com/mpv-player/mpv/issues/11585 https://github.com/mpv-player/mpv/issues/11853
