### ISSUE TITLE
Taskbar progress indicator does not appear at the very start of video playback 

### ISSUE THREAD

**Issue by raziel711** [mpv-player/mpv#14282]
### mpv Information

```bash
mpv v0.38.0-372-g481e4984 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May 31 2024 12:18:20
libplacebo version: v7.349.0 (v6.338.0-140-g50ddb03-dirty)
FFmpeg version: N-115464-g249c66bb2
FFmpeg library versions:
   libavutil       59.20.100
   libavcodec      61.5.104
   libavformat     61.3.104
   libswscale      8.2.100
   libavfilter     10.2.102
   libswresample   5.2.100
```

### Other Information

- Windows version: Windows 10 22H2
- GPU model, driver and version: NVIDIA GeForce GTX 1650, driver version 555.85
- Source of mpv: https://github.com/zhongfly/mpv-winbuild/releases
- Introduced in version: N/A

### Reproduction Steps

When using `taskbar-progress`, the taskbar progress indicator does not appear at the very start of video playback.  For example, when using a video with a duration of 23:41 played with `mpv --no-config`, at six seconds the progress indicator is not visible on the taskbar:
![mpv_FiR97HZTgh](https://github.com/mpv-player/mpv/assets/75226602/63ddb6c6-2894-4645-bddb-8192a49fc05e)

It only appears starting at seven seconds:
![mpv_qX64fZPxRm](https://github.com/mpv-player/mpv/assets/75226602/bc8d9f00-e187-4943-9a16-492ca98e15f5)

For reference, this is at the six second mark with MPC-HC; the indicator shows up from the start of the video:
![mpc-hc64_bPmxDzaKPi](https://github.com/mpv-player/mpv/assets/75226602/a26a3401-ccbf-4831-817b-8ce078b0cba1)

I've tested videos with various lengths, and it seems like the progress indicator does not appear until the video reaches around 0.5% of the total duration.  I'm sure that behavior is probably a part of Windows itself and can't be changed; however, when mpv is paused, the indicator is visible even at the very beginning of the video.

For instance, here is an example from the same video at two seconds:
![mpv_nujMHWZMja](https://github.com/mpv-player/mpv/assets/75226602/2a04e76d-e7cd-4c4d-b68c-a18c8db307fc)

Would it be possible to make it so that the behavior for the progress indicator matches when the video is playing and when it is paused?

### Expected Behavior

The taskbar progress indicator should appear from the start of the video while it is playing.

### Actual Behavior

While the video is playing, the progress indicator does not appear on the taskbar until the video reaches ~0.5% of its total duration.  The indicator only appears before the 0.5% point if the video is paused.

### Log File

[log.txt](https://github.com/user-attachments/files/15526544/log.txt)

### Sample Files

Any sufficiently long video file should work.

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
> the progress indicator does not appear on the taskbar until the video reaches ~0.5% of its total duration.

Yes, that's correct assessment. The position send to taskbar is rounded to integer % value and 0 is interpreted as no progress, so only after 0.5% it starts showing anything. There is no reason to do that, ITaskbarList3 api takes ULONGLONG, so the progress can be more fine grained. I will update that when I have time.
