### ISSUE TITLE
dither green pattern

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#14297]
### Expected behavior of the wanted feature

a dithering solution that doesn't introduce this weird green pattern which in itself prevents from ever having any real black on screen

Screenshots, boosted luminance for demonstration purpose.
dither off
![dither off 11](https://github.com/mpv-player/mpv/assets/139760266/ea5c9c99-bdab-4008-89cd-909e02c82228)
dither on `dither-depth=8 dither=fruit`
![dither on 111](https://github.com/mpv-player/mpv/assets/139760266/13620972-c98f-451c-8623-0388e9c1408d)

**Comment by kasper93** [comment]
Duplicate of #13881
