### ISSUE TITLE
Forced window-scale bind on Meta(cmd ⌘)+0/1/2.

### ISSUE THREAD

**Issue by KOSHACHIJ** [mpv-player/mpv#14305]
### mpv Information

```bash
mpv v0.38.0-388-g9fa8101847 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jun  3 2024 00:03:49
libplacebo version: v7.349.0 (v6.338.0-133-g9e1257c8)
FFmpeg version: git-2024-05-27-01c7f68
FFmpeg library versions:
   libavutil       59.20.100
   libavcodec      61.5.104
   libavformat     61.3.104
   libswscale      8.2.100
   libavfilter     10.2.102
   libswresample   5.2.100
```

### Important Information

- Platform version: MacOS 11.7.4
- GPU model, driver and version: Intel Iris Pro 1536 MB
- Source: https://github.com/eko5624/mpv-macos-intel/releases
- Introduced in version: ?

### Reproduction Steps

mpv --no-config --no-input-builtin-bindings --no-input-default-bindings

### Expected Behavior

Possible to set own bind to any keys with input-builtin-bindings=no and input-default-bindings=no

### Actual Behavior

Ignores custom binds on input.conf, even with input-builtin-bindings=no and input-default-bindings=no.
Meta+3/4/5/etc... works fine.

### Log File

[output.txt](https://github.com/user-attachments/files/15592838/output.txt)

### Sample Files

https://github.com/mpv-player/mpv/assets/67644959/501f3b0f-2c17-4e88-a1ad-a5efce5e1e83

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Akemi** [comment]
if you want to overwrite any key bound in the menu you have to overwrite those in the macOS "[System Setting](https://support.apple.com/en-gb/guide/mac-help/mchlp2271/mac)" (this will also only work with the mpv bundle). they will always take precedence over any configured key bindings and can not be bound/configured via the input.conf.

<img width="715" alt="Screenshot 2024-06-05 at 18 55 57" src="https://github.com/mpv-player/mpv/assets/680386/dd9bdd2e-e658-434d-90f4-d11cf19ce3a1">

this is a limitation on how mpv initialises the menu bar and how it loads the options. though it might be a historical limitation by now. with the recent rewrite it might be possible to disable them completely via an option.

**Comment by Akemi** [comment]
i added an option to disable the default menu shortcuts here #14412. test builds are available on that PR in the first comment.
