### ISSUE TITLE
Stuttering video with equilized Pulseaudio sink

### ISSUE THREAD

**Issue by notargets** [mpv-player/mpv#1430]
I use Pulseaudio's built-in equilizer by having a separate sink and make programs like mplayer use it. Some info about the equalizer can be found [here] (http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Equalizer/).

However, when I try to use it with mpv 0.7.2-2 on Manjaro Linux, with the `-ao=pulse::equalized` switch, the video stutters. (The sound is fine though.)

I don't see any error messages when mpv is run from terminal.

(I use the free drivers for my AMD graphic card.)

**Comment by wm4** [comment]
Video is synchronized against audio, so if audio playback status is inconsistent, the video will stutter.

Can you test whether adding ``latency-hacks=no`` to the pulse suboptions (``--ao=pulse::equalized:latency-hacks=no``) changes anything?

**Comment by notargets** [comment]
Yes, it does the trick. The video is displayed well with that suboption. Thank you!

**Comment by wm4** [comment]
Interesting. I still don't know why this would happen, though.

The default (without ``latency-hacks=no``) is probably still required to work around older, buggy pulseaudio versions.

**Comment by wm4** [comment]
Well, I disabled this option by default. Let's wait and see if it causes problems for any users.

**Comment by wm4** [comment]
The change I made didn't have any negative consequences so far, so I guess we don't have to care about this anymore.
