### ISSUE TITLE
Slow startup during ao/wasapi initialization

### ISSUE THREAD

**Issue by cusr** [mpv-player/mpv#14314]
### mpv Information

```bash
[cplayer] Command line options: '-v'
[cplayer] mpv v0.38.0-373-gdf166c13 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Jun  2 2024 00:09:08
[cplayer] libplacebo version: v7.349.0 (v7.349.0-rc1-dirty)
[cplayer] FFmpeg version: N-115515-g00d029d5c
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       59.20.100
[cplayer]    libavcodec      61.5.104
[cplayer]    libavformat     61.3.104
[cplayer]    libswscale      8.2.100
[cplayer]    libavfilter     10.2.102
[cplayer]    libswresample   5.2.100
```

### Other Information

- Windows version: Microsoft Windows 11 Pro [Version 10.0.22631.3672]
- GPU model, driver and version: Geforce RTX 3080, 555.99
- Source of mpv: https://sourceforge.net/projects/mpv-player-windows/
- Introduced in version: Tried older version(0.32.0-515-g685bd6a5f5 2020), it's faster then the new one.

### Reproduction Steps

Opening any video files.

### Expected Behavior

Fast startup.

### Actual Behavior

Usually cost more than 10 seconds to open a video file.

### Log File

[log.txt](https://github.com/user-attachments/files/15688601/log.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by cusr** [comment]
I saw a huge gap between following logs:
[   0.724][d][ao/wasapi] Find device ''
[  11.187][v][ao/wasapi] No device specified. Selecting default.
Any idea what could possibly cause this?
Is there anyway to output more information?

**Comment by kasper93** [comment]
Fix/Remove/Update you audio device drivers. It hangs in the following call
https://github.com/mpv-player/mpv/blob/31ae111ff577deb46aa0fc80732fddae65a59b36/audio/out/ao_wasapi_utils.c#L847-L849
there is nothing mpv can do to workaround this. We had similar report about it and, it was fixed by driver update.

**Comment by cusr** [comment]
Thanks a lot for referring to #12145! That ASUS bloatware, Sonic Studio 3, is the main reason.
After uninstall it, now mpv starts very fast.
I also tried the build from #14317 before uninstalling anything, but no luck it's still slow, and stopped around wasapi.
