### ISSUE TITLE
QML example fails on Windows [was: opengl-cb could not initialize OpenGL on Windows]

### ISSUE THREAD

**Issue by ichdy** [mpv-player/mpv#1434]
try to run qml example on windows but error. here's the log

> [input] Falling back on default (hardcoded) input config
> [global] config file: 'scripts'
> [global] config file: 'lua'
> [cplayer] mpv git-0488829 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
> [cplayer]  built on 2015-01-07T03:01:17
> [cplayer] ffmpeg library versions:
> [cplayer]    libavutil       54.15.100
> [cplayer]    libavcodec      56.13.100
> [cplayer]    libavformat     56.15.102
> [cplayer]    libswscale      3.1.101
> [cplayer]    libavfilter     5.2.103
> [cplayer]    libswresample   1.1.100
> [cplayer] 
> [cplayer] Configuration: ./waf configure --enable-static --enable-libmpv-shared --prefix=/
> [cplayer] config.h:
> [cplayer] 
> [cplayer] #define DEFAULT_DVD_DEVICE "D:"
> [cplayer] #define DEFAULT_CDROM_DEVICE "D:"
> [cplayer] #define HAVE_CPLAYER 1
> [cplayer] #define HAVE_LIBMPV_SHARED 1
> [cplayer] #define HAVE_LIBMPV_STATIC 0
> [cplayer] #define HAVE_CLIENT_API_EXAMPLES 0
> [cplayer] #define HAVE_STATIC_BUILD 1
> [cplayer] #define HAVE_BUILD_DATE 1
> [cplayer] #define HAVE_OPTIMIZE 1
> [cplayer] #define HAVE_DEBUG_BUILD 1
> [cplayer] #define HAVE_LIBDL 0
> [cplayer] #define HAVE_DLOPEN 1
> [cplayer] #define HAVE_VF_DLOPEN_FILTERS 0
> [cplayer] #define HAVE_ZSH_COMP 0
> [cplayer] #define HAVE_ASM 1
> [cplayer] #define HAVE_TEST 0
> [cplayer] #define HAVE_NOEXECSTACK 1
> [cplayer] #define HAVE_LIBM 1
> [cplayer] #define HAVE_MINGW 1
> [cplayer] #define HAVE_POSIX 0
> [cplayer] #define HAVE_POSIX_OR_MINGW 1
> [cplayer] #define HAVE_WIN32_INTERNAL_PTHREADS 0
> [cplayer] #define HAVE_PTHREADS 1
> [cplayer] #define HAVE_STDATOMIC 1
> [cplayer] #define HAVE_ATOMIC_BUILTINS 0
> [cplayer] #define HAVE_SYNC_BUILTINS 0
> [cplayer] #define HAVE_ATOMICS 1
> [cplayer] #define HAVE_LIBRT 0
> [cplayer] #define HAVE_ICONV 1
> [cplayer] #define HAVE_DOS_PATHS 1
> [cplayer] #define HAVE_PRIORITY 1
> [cplayer] #define HAVE_WAIO 0
> [cplayer] #define HAVE_SYS_VIDEOIO_H 0
> [cplayer] #define HAVE_TERMIOS_H 0
> [cplayer] #define HAVE_SYS_TERMIOS_H 0
> [cplayer] #define HAVE_SHM 0
> [cplayer] #define HAVE_NANOSLEEP 0
> [cplayer] #define HAVE_POSIX_SPAWN 0
> [cplayer] #define HAVE_GLOB 0
> [cplayer] #define HAVE_GLOB_WIN32_REPLACEMENT 1
> [cplayer] #define HAVE_GLIBC_THREAD_NAME 0
> [cplayer] #define HAVE_OSX_THREAD_NAME 0
> [cplayer] #define HAVE_BSD_THREAD_NAME 0
> [cplayer] #define HAVE_NETBSD_THREAD_NAME 0
> [cplayer] #define HAVE_BSD_FSTATFS 0
> [cplayer] #define HAVE_LINUX_FSTATFS 0
> [cplayer] #define HAVE_LIBGUESS 1
> [cplayer] #define HAVE_LIBSMBCLIENT 0
> [cplayer] #define HAVE_LUA 1
> [cplayer] #define HAVE_LIBASS 1
> [cplayer] #define HAVE_LIBASS_OSD 1
> [cplayer] #define HAVE_DUMMY_OSD 0
> [cplayer] #define HAVE_ZLIB 1
> [cplayer] #define HAVE_ENCODING 1
> [cplayer] #define HAVE_JOYSTICK 0
> [cplayer] #define HAVE_LIRC 0
> [cplayer] #define HAVE_LIBBLURAY 1
> [cplayer] #define HAVE_DVDREAD 1
> [cplayer] #define HAVE_DVDNAV 1
> [cplayer] #define HAVE_CDDA 1
> [cplayer] #define HAVE_ENCA 0
> [cplayer] #define HAVE_MPG123 1
> [cplayer] #define HAVE_LADSPA 0
> [cplayer] #define HAVE_LIBBS2B 1
> [cplayer] #define HAVE_LCMS2 1
> [cplayer] #define HAVE_VAPOURSYNTH_CORE 0
> [cplayer] #define HAVE_VAPOURSYNTH 0
> [cplayer] #define HAVE_VAPOURSYNTH_LAZY 0
> [cplayer] #define HAVE_SDL2 0
> [cplayer] #define HAVE_SDL1 0
> [cplayer] #define HAVE_OSS_AUDIO_4FRONT 0
> [cplayer] #define HAVE_OSS_AUDIO_NATIVE 0
> [cplayer] #define HAVE_OSS_AUDIO_SUNAUDIO 0
> [cplayer] #define HAVE_OSS_AUDIO 0
> [cplayer] #define HAVE_RSOUND 0
> [cplayer] #define HAVE_SNDIO 0
> [cplayer] #define HAVE_PULSE 0
> [cplayer] #define HAVE_JACK 0
> [cplayer] #define HAVE_OPENAL 0
> [cplayer] #define HAVE_ALSA 0
> [cplayer] #define HAVE_COREAUDIO 0
> [cplayer] #define HAVE_DSOUND 1
> [cplayer] #define HAVE_WASAPI 1
> [cplayer] #define HAVE_COCOA 0
> [cplayer] #define HAVE_GDI 1
> [cplayer] #define HAVE_WINMM 1
> [cplayer] #define HAVE_OLE 1
> [cplayer] #define HAVE_UUID 1
> [cplayer] #define HAVE_WAYLAND 0
> [cplayer] #define HAVE_X11 0
> [cplayer] #define HAVE_XSS 0
> [cplayer] #define HAVE_XEXT 0
> [cplayer] #define HAVE_XV 0
> [cplayer] #define HAVE_XINERAMA 0
> [cplayer] #define HAVE_XRANDR 0
> [cplayer] #define HAVE_GL_COCOA 0
> [cplayer] #define HAVE_GL_X11 0
> [cplayer] #define HAVE_EGL_X11 0
> [cplayer] #define HAVE_GL_WAYLAND 0
> [cplayer] #define HAVE_GL_WIN32 1
> [cplayer] #define HAVE_GL 1
> [cplayer] #define HAVE_VDPAU 0
> [cplayer] #define HAVE_VDPAU_GL_X11 0
> [cplayer] #define HAVE_VAAPI 0
> [cplayer] #define HAVE_VAAPI_VPP 0
> [cplayer] #define HAVE_VAAPI_GLX 0
> [cplayer] #define HAVE_CACA 1
> [cplayer] #define HAVE_JPEG 1
> [cplayer] #define HAVE_DIRECT3D 1
> [cplayer] #define HAVE_LIBAV 1
> [cplayer] #define HAVE_LIBSWRESAMPLE 1
> [cplayer] #define HAVE_LIBAVRESAMPLE 0
> [cplayer] #define HAVE_RESAMPLER 1
> [cplayer] #define HAVE_AVCODEC_CHROMA_POS_API 1
> [cplayer] #define HAVE_AVCOL_SPC_BT2020 1
> [cplayer] #define HAVE_AVCODEC_VDPAU_ALLOC_CONTEXT 0
> [cplayer] #define HAVE_LIBAVFILTER 1
> [cplayer] #define HAVE_LIBAVDEVICE 1
> [cplayer] #define HAVE_AVCODEC_METADATA_UPDATE_SIDE_DATA 1
> [cplayer] #define HAVE_AVFORMAT_METADATA_UPDATE_FLAG 1
> [cplayer] #define HAVE_AVCODEC_REPLAYGAIN_SIDE_DATA 1
> [cplayer] #define HAVE_AV_DISPLAYMATRIX 1
> [cplayer] #define HAVE_AVFRAME_METADATA 1
> [cplayer] #define HAVE_AVFRAME_SKIP_SAMPLES 1
> [cplayer] #define HAVE_VAAPI_HWACCEL 0
> [cplayer] #define HAVE_VIDEODECODEACCELERATION_VDADECODER_H 0
> [cplayer] #define HAVE_VIDEO_DECODE_ACCELERATION_VDA_DECODER_H 0
> [cplayer] #define HAVE_VDA_HWACCEL 0
> [cplayer] #define HAVE_VDA_GL 0
> [cplayer] #define HAVE_VDPAU_HWACCEL 0
> [cplayer] #define HAVE_DXVA2_HWACCEL 1
> [cplayer] #define HAVE_TV 1
> [cplayer] #define HAVE_TV_V4L2 0
> [cplayer] #define HAVE_LIBV4L2 0
> [cplayer] #define HAVE_PVR 0
> [cplayer] #define HAVE_AUDIO_INPUT 0
> [cplayer] #define HAVE_DVBIN 0
> [cplayer] #define HAVE_COCOA_APPLICATION 0
> [cplayer] #define HAVE_APPLE_REMOTE 0
> [cplayer] #define HAVE_SYS_SOUNDCARD_H (HAVE_OSS_AUDIO_NATIVE || HAVE_OSS_AUDIO_4FRONT)
> [cplayer] #define HAVE_SOUNDCARD_H HAVE_OSS_AUDIO_SUNAUDIO
> [cplayer] #define CONFIGURATION "./waf configure --enable-static --enable-libmpv-shared --prefix=/"
> [cplayer] #define MPV_CONFDIR "//etc/mpv"
> [cplayer] 
> [opengl-cb] Detected desktop OpenGL 3.3.
> [opengl-cb] GL_VENDOR='ATI Technologies Inc.'
> [opengl-cb] GL_RENDERER='ATI Radeon HD 4770'
> [opengl-cb] GL_VERSION='3.3.11672 Compatibility Profile Context'
> [opengl-cb] GL_SHADING_LANGUAGE_VERSION='3.30'
> [opengl-cb] Required function 'glDrawBuffer' not found for builtin OpenGL 1.1.
> [opengl-cb] At least OpenGL 2.1 or OpenGL ES 2.0 required.
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  could not initialize OpenGL

**Comment by wm4** [comment]
The platform-specific part of OpenGL implementations usually provide a function to resolve OpenGL functions (directly linking them doesn't work for extensions, and in some cases, not even for all builtin functions). On Windows, this function is wglGetProcAddress().

Often, this function won't return function pointers for builtin functions. On Windows, this happens with builtin OpenGL 1.0 functions. In mpv, we work this around in the following way: http://git.srsfckn.biz/mpv/tree/video/out/gl_w32.c#n78 . I'm not exactly sure how Qt itself does it. There seem to be multiple codepaths depending on compile-time settings. But you can see it for example in ``QWindowsGLContext::getProcAddress`` and in ``QOpenGLFunctionsPrivate::QOpenGLFunctionsPrivate``.

Now the problem is, that Qt randomly does not include fallbacks for some functions it doesn't need, like ``glDrawBuffer``. mpv on the other hand wants this function (and some others), but Qt returns NULL for them, so mpv refuses to initialize.

Someone found the same problem, and reported it to Qt as a feature request: http://bugreports.qt-project.org/browse/QTBUG-39531 (seems to be down, so I can't check if the link is correct)

If they don't fix it, the qml example could include its own fallback handling.

**Comment by ichdy** [comment]
thank you for your explanation. using workaround just now and it worked.

        static void *get_proc_address(void *ctx, const char *name) {
            (void)ctx;
            QOpenGLContext *glctx = QOpenGLContext::currentContext();
            if (!glctx)
            return NULL;
    
            void *res = (void *)glctx->getProcAddress(QByteArray(name));
    #ifdef _WIN32
            if (!res)
            {
                HMODULE oglmod = GetModuleHandleA("opengl32.dll");
                return (void *) GetProcAddress(oglmod, name);
            }
    #endif
            return res;
        }

**Comment by wm4** [comment]
This remains a Qt issue. Qt doesn't care, but I don't either. Using the workaround should work in most situations.
