### ISSUE TITLE
Blank Video hwdec=auto

### ISSUE THREAD

**Issue by kimj76** [mpv-player/mpv#14343]
### mpv Information

```bash
mpv v0.38.0-478-g5158a3d779 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
built on Jun 12 2024 18:57:44
libplacebo version: v7.349.0 (v7.349.0-rc1-2-gbc9de9c7)
FFmpeg version: N-115732-gbdd3c6ca50
FFmpeg library versions:
libavutil       59.21.100
libavcodec      61.7.100
libavformat     61.3.104
libswscale      8.2.100
libavfilter     10.2.102
libswresample   5.2.100
```

### Other Information

- Linux version: Ubuntu 24.04
- Kernel Version: 6.7.12-1-liquorix-amd64
- GPU Model: AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M/6850M XT
- Mesa/GPU Driver Version: 4.6 (Compatibility Profile) Mesa 24.1.1 - kisak-mesa PPA
- Window Manager and Version: SDDM 0.20.0-2
- Source mpv: github
- Introduced in version: MPV had been working on a build made around  Jun 5, 2024

### Reproduction Steps

MPV with hwdec=auto in the config file the video stream does not play

MPV with --no-config the video stream plays
MPV with #hwdec=auto in the config the video stream plays

I also tried commenting out other "Video Settings" in the config file like vo=gpu-next but nothing else seems to trigger the issue.

### Expected Behavior

Video stream to play, the previous build (~7 days old) with the same config file played video without issue.

### Actual Behavior

The audio stream, subtitle steam played with blank video.

### Log File

[output.txt](https://github.com/user-attachments/files/15802301/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by zhongfly** [comment]
Have fixed by https://github.com/FFmpeg/FFmpeg/commit/0060a368b175b1cbc01800af2d3d17ca9f88970c

**Comment by kimj76** [comment]
Fresh build all working
