### ISSUE TITLE
(FR) Please provide official FlatPak for mpv

### ISSUE THREAD

**Issue by zWhdmB5T** [mpv-player/mpv#14346]
### Expected behavior of the wanted feature

Dear all,

there is a [mpv FlatPak](https://flathub.org/apps/io.mpv.Mpv) available. Unfortunately, it is not officially maintained like others (e.g. [Firefox FlatPak](https://flathub.org/apps/org.mozilla.firefox), [LibreOffice FlatPak](https://flathub.org/apps/org.libreoffice.LibreOffice) or [digiKam FlatPak](digiKam)).

I would appreciate that very much. I expect high security as well as an up-to-date release (including all used libraries and such) of an official package.

Thank you!

**Comment by hooke007** [comment]
dup countless issues

> mpv does not provide binaries for any platform

**Comment by zWhdmB5T** [comment]
> dup countless issues #6933
> 
> > mpv does not provide binaries for any platform

There is a FlatPak, indeed. But it's not officially maintained. That's what I am asking for.

**Comment by zWhdmB5T** [comment]
Because one could counter that the examples of officially maintained FlatPaks mentioned above are not _community driven_ (i.e. a single persons or just a few ones) but maintained by an organisation resp. a company, here are other examples:

- [KeePassXC](https://flathub.org/apps/org.keepassxc.KeePassXC) (community)
- [Strawberry Music Player](https://flathub.org/apps/org.strawberrymusicplayer.strawberry) (solo)
- [fre:ac](https://flathub.org/apps/org.freac.freac) (solo)
- [FSearch](https://flathub.org/apps/io.github.cboxdoerfer.FSearch) (solo)
- [Qalculate! (GTK UI)](https://flathub.org/apps/io.github.Qalculate) (solo)
- [Metadata Cleaner](https://flathub.org/apps/fr.romainvigier.MetadataCleaner) (solo)

**Comment by hooke007** [comment]
IMO The answer is clear in those issues.
