### ISSUE TITLE
Network stream failed due to unicode  character `&` in streaming urls

### ISSUE THREAD

**Issue by arghya339** [mpv-player/mpv#14356]
### mpv Information

```bash
mpv v0.38.0-476-gd2bd77ad Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jun  9 2024 00:05:18
libplacebo version: v7.349.0 (v7.349.0-rc1-2-gbc9de9c-dirty)
FFmpeg version: N-115628-g658439934
FFmpeg library versions:
   libavutil       59.21.100
   libavcodec      61.7.100
   libavformat     61.3.104
   libswscale      8.2.100
   libavfilter     10.2.102
   libswresample   5.2.100
```

### Other Information

- Windows version: 23H2
- GPU model, driver and version: AMD Radeon RX550 4GB DDR5
- Source of mpv: Sourceforge
- Introduced in version:

### Reproduction Steps

please add special character support in network streaming urls, similar to mpv android

### Expected Behavior

add special character support in network streaming urls, similar to mpv-android

### Actual Behavior

add torrent urls from yts.mx or 1377x.to to seedr.cc then open torrent folder then right click and `copy download link` then open win power shell then type mpv right click and hit enter. make sure you have add mpv extracted archive path as user environment and variables.
you can see urls with spacial character error

### Log File

At line:1 char:135
+ ... Rip.x265.10bit.AAC5.1-[YTS.MX].mp4?st=5w2UuxiAQ70siQvKOCzXLA&e=171846 ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [ ] I provided all required information including system and mpv version.
- [ ] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [ ] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [ ] I attached the full, untruncated log file.
- [ ] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
Wrap the URL in quotes.

**Comment by arghya339** [comment]
> Wrap the URL in quotes.

Sir, me try with quotes and without but same issues, please help me...

**Comment by kasper93** [comment]
Sir, kindly use the single quotes `'` around your url.

**Comment by arghya339** [comment]
> Sir, kindly use the single quotes `'` around your url.

Thank you, its works after few sec. Have a nice day
