### ISSUE TITLE
Opening a video file while one is already playing crashes mpv

### ISSUE THREAD

**Issue by Naio** [mpv-player/mpv#1438]
I'm using mpv 0.7.2 for OS X from https://github.com/mpv-player/mpv/releases.

The following issue started to occur on 0.7.0, if I remember correctly:

If you open a new video file through Finder or Spotlight while one is already playing, mpv crashes.

**Comment by wm4** [comment]
Pretty sure this is fixed in master.

**Comment by pigoz** [comment]
Yes it's fixed in master.

**Comment by Naio** [comment]
Good to hear, thanks.

**Comment by Naio** [comment]
Unfortunately this issue still persist on 0.7.3. on OS X.
