### ISSUE TITLE
The blur factor applied to the font itself

### ISSUE THREAD

**Issue by 1000Fear** [mpv-player/mpv#14391]
### Expected behavior of the wanted feature

In the current version, the only 2 options I found related to font blur is `sub-blur` and `osd-blur`, according to reference, they‘re applied to the font border. 

When the _border is 0_, `sub-blur` and `osd-blur`are applied to the font itself, that‘s good, they have an Anti-Aliasing effect, I usually set `sub-blur=0.4` and `osd-blur=0.15`, making the font looks softer.

But if the _border is not 0_, blur will be applied to the border, as described in the reference, and the Anti-Aliasing effect on the font will disappear, font looks terrible to me.

Can these two options be separated? Just like `sub-blur` `sub-border-blur` `osd-blur` `osd-border-blur`. It's a pity that _border_ and _the blurriness of the font itself_ can’t be obtained simultaneously.

**Comment by hooke007** [comment]
dup and see https://github.com/mpv-player/mpv/issues/10784
