### ISSUE TITLE
Frame dropped and icc-cache file reopened on Os X

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#1439]
Since commit f811348, every time I toggle fullscreen on or off mpv reopens the icc-cache file and drop some frames. 
Is it an expected behavior with the new icc-profile system or there's a problem somewhere?

My vo configuration:
vo=opengl-hq:icc-profile-auto:approx-gamma:icc-cache=~/.config/mpv/icc-cache

The terminal output:
$ mpv video.mkv 
[vo/opengl-hq] Opening 3D LUT cache in file '~/.config/mpv/icc-cache'.
Playing: Documents/Torrent Downloads/[Dreamless] Tantei Kageki Milky Holmes TD - 01 (1280x720 x264 AAC).mkv
[stream] Video (+) --vid=1 (h264)
[stream] Audio (+) --aid=1 --alang=jpn (*) (aac)
[stream] Subs  (+) --sid=1 (*) (ass)
Opening video filter: [vapoursynth file=~/.config/mpv/filters/deband.vpy]
AO: [coreaudio] 48000Hz stereo 2ch float
VO: [opengl-hq] 1280x720 yuv420p16
[vo/opengl-hq] Opening 3D LUT cache in file '~/.config/mpv/icc-cache'.
AV: 00:00:01 / 00:23:59 (0%) A-V:  0.000
[vo/opengl-hq] Opening 3D LUT cache in file '~/.config/mpv/icc-cache'.
AV: 00:00:02 / 00:23:59 (0%) A-V:  0.000 Dropped: 3
[vo/opengl-hq] Opening 3D LUT cache in file '~/.config/mpv/icc-cache'.
AV: 00:00:03 / 00:23:59 (0%) A-V:  0.000 Dropped: 9
[vo/opengl-hq] Opening 3D LUT cache in file '~/.config/mpv/icc-cache'.
AV: 00:00:03 / 00:23:59 (0%) A-V: -0.000 Dropped: 11
[vo/opengl-hq] Opening 3D LUT cache in file '~/.config/mpv/icc-cache'.
AV: 00:00:04 / 00:23:59 (0%) A-V:  0.000 Dropped: 13

Exiting... (Quit)
$

**Comment by wm4** [comment]
Seems like the cocoa code sends a icc update on every fullscreen toggle. Even if the icc profile doesn't change, or a separate icc profile is used.

The dropped frames are merely a consequence of the (slow) icc profile reload.

**Comment by wm4** [comment]
Implemented a fix, but it's completely untested. Please try if it works.

**Comment by AirPort** [comment]
Yes, it seems it's fixed now. Thank you very much!
