### ISSUE TITLE
--softvol-max not working on OS X

### ISSUE THREAD

**Issue by FrancescoZZ** [mpv-player/mpv#1442]
A video opened with --softvol-max=100 will sound exactly the same as one with --softvol-max=1200 with both at 100%.
This is on 10.9.5.

**Comment by hackeron** [comment]
Any solution for this? - I am also trying with --softvol-max=100 and --softvol-max=1200 on Yomemite using the latest MPV from trunk and there is no difference in volume. When I press "0" to increase volume to 100%, the volume is the same.

**Comment by FrancescoZZ** [comment]
>EDIT: I forgot to specify softvol=yes in ~/.config/mpv/mpv.conf - works after adding this line! Maybe the original poster had the same issue?

It would appear so!
Should've probably read the docs better
