### ISSUE TITLE
SwayWM causes mpv to give an aliased output.

### ISSUE THREAD

**Issue by krazyguy97** [mpv-player/mpv#14422]
### mpv Information

```bash
mpv v0.38.0-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May 23 2024 10:29:03
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version: EndeavourOS
- Kernel Version:  6.9.5-1-cachyos-sched-ext #1 SMP PREEMPT_DYNAMIC Mon, 17 Jun 2024 14:40:51 +0000 x86_64 GNU/Linux
- GPU Model: 00:02.0 VGA compatible controller [0300]: Intel Corporation Tiger Lake-LP GT2 [UHD Graphics G4] [8086:9a78] (rev 01)
- Mesa/GPU Driver Version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.1-arch1.1 
- Window Manager and Version: Sway
- Source mpv: Arch linux repos
- Introduced in version: Unknown

### Reproduction Steps

Attempt to use mpv with the --vo=dmabuf-wayland argument on a low resolution video while running Sway. (this is where it is most noticeable) The output should be aliased with nothing to fix it except switching to another vo option.

### Expected Behavior

No aliasing using dmabuf-wayland.

### Actual Behavior

dmabuf-wayland caused aliasing artifacts to appear.

### Log File

[output.txt](https://github.com/user-attachments/files/15944138/output.txt)

### Sample Files

https://github.com/mpv-player/mpv/assets/114841483/9857fb3d-d2b3-450b-b59a-ac1883866af2

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Dudemanguy** [comment]
>[   0.136][v][vo/dmabuf-wayland] Window size: 1362x218 (Borders: l=0 t=0 r=0 b=0)

Are you scaling the video to this weird size in your testing?

**Comment by krazyguy97** [comment]
> > [   0.136][v][vo/dmabuf-wayland] Window size: 1362x218 (Borders: l=0 t=0 r=0 b=0)
> 
> Are you scaling the video to this weird size in your testing?

I was doing the logging in a window, while i had other things on the screen. I can test on a 1080p display if you want me to.

**Comment by Dudemanguy** [comment]
Oh okay there's no bug then. I wasn't sure if you meant a non-scaled window. `dmabuf-wayland` uses purely compositor-side scaling. It will be low quality in most cases. Use `gpu` or `gpu-next` if you want quality.

**Comment by krazyguy97** [comment]
I understand. Thanks for clarifying.

**Comment by Dudemanguy** [comment]
In theory there is nothing stopping a compositor for using something fancier although most would not have any reason to do that. I think sway uses bilinear for non-integers if I remember right.

**Comment by krazyguy97** [comment]
labwc or basically any other compositor did not have this issue. its only sway for some reason but oh well, its fine

**Comment by CounterPillow** [comment]
Where did you hear about the dmabuf-wayland VO that made you want to use it? This isn't the first time someone complained of the intended low quality, so somewhere people are finding out about it existing without knowing what it is or does, and misinformation should be corrected at the source.

**Comment by krazyguy97** [comment]
I only used dmabuf-wayland because it resulted in lower power usage on my setup.

**Comment by Dudemanguy** [comment]
>I only used dmabuf-wayland because it resulted in lower power usage on my setup.

Well that's the intended purpose at least.

**Comment by llyyr** [comment]
Set `scale_filter linear` for the output in your sway config

**Comment by krazyguy97** [comment]
> Set `scale_filter linear` for the output in your sway config

You sir, are a lifesaver 😂😂
