### ISSUE TITLE
Show thumbnail on the official osc time bar

### ISSUE THREAD

**Issue by srk24** [mpv-player/mpv#14458]
### Expected behavior of the wanted feature
When the mouse pointer is hovering over the time bar, can see a thumbnail of that time.

There used to be a relevant issue, but are there any new changes now?
https://github.com/mpv-player/mpv/issues/6919
https://github.com/mpv-player/mpv/issues/11640

**Comment by sfan5** [comment]
> but are there any new changes now?

No, as said: The chances of anyone actually implementing this is still pretty low.
