### ISSUE TITLE
Can't start mpv because of libavcodec bump

### ISSUE THREAD

**Issue by dxrknesss** [mpv-player/mpv#14478]
### mpv Information

```bash
mpv with any flag (or without them) gives an error: 

mpv: error while loading shared libraries: libavcodec.so.60: cannot open shared object file: No such file or directory

so here's info from pacman:
Name            : mpv
Version         : 1:0.38.0-5
Architecture    : x86_64

ffmpeg version n7.0.1 Copyright (c) 2000-2024 the FFmpeg developers
built with gcc 14.1.1 (GCC) 20240522
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-frei0r --enable-gmp --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libdvdnav --enable-libdvdread --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librav1e --enable-librsvg --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpl --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-mbedtls --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-vapoursynth --enable-version3 --enable-vulkan
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
```

### Other Information

- Linux version: Arch Linux
- Kernel Version: 6.9.7-zen1-1-zen
- GPU Model: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] (rev c8) (aka Vega 11 with Ryzen 5 3400g)
- Mesa/GPU Driver Version: Mesa 24.1.2-arch1.1
- Window Manager and Version: GNOME 46.3.1 & Mutter packaged with it
- Source mpv: arch package repo
- Introduced in version: -

### Reproduction Steps

have ffmpeg updated to the last major version (7.0 onwards)
have mpv updated to the last possible version

### Expected Behavior

expected mpv to work

### Actual Behavior

but it doesn't

### Log File

not possible to do

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Rebuild mpv with the new ffmpeg

**Comment by dxrknesss** [comment]
> Rebuild mpv with the new ffmpeg

can you give me the manual at least, cause I install it as binary from my repo's package repository. don't understand the word 'rebuild' in this context.

btw, I already did these steps beforehand:
- uninstalled mpv, ffmpeg
- cleared cache from pacman
- updated system
- installed mpv, ffmpeg
and still getting this error

**Comment by llyyr** [comment]
Check if your mpv and ffmpeg are from the same repo

Looking at the commit list, https://archlinux.org/packages/extra/x86_64/mpv/ has been rebuild once after ffmpeg 7.0 update, so this shouldn't happen.

**Comment by CounterPillow** [comment]
Then either the Arch maintainer is shipping broken stuff, or you're using an ffmpeg that is not from the official Arch Linux repositories but some sussy AUR thing. It's Arch Linux's job to make sure the mpv binary they ship is actually built against the ffmpeg libraries they ship.

Either way, it's not upstream mpv's problem.

**Comment by dxrknesss** [comment]
thanks, I'll try to ask around arch repo support

**Comment by mrlectus** [comment]
> thanks, I'll try to ask around arch package repo support

Did you fix it, cause am having this issue to after updating my system

**Comment by dxrknesss** [comment]
> > thanks, I'll try to ask around arch package repo support
> 
> Did you fix it, cause am having this issue to after updating my system

yeah, I just built mpv from source code. not the best solution, but at least it works
