### ISSUE TITLE
Screenshot support for opengl-cb

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1447]
opengl-cb lacks screenshot support.
The biggest problem is that it is not possible to download texture in mpv's thread.
I cannot imagine any method to reuse the command `screenshot` and `screenshot_to_file`.

Instead, I have two ideas.
One is to add a new function to render the frame into memory.  like:
```
char *mpv_opengl_cb_copy_frame(struct mpv_opengl_cb_context *ctx, bool subtitle);
```
where `subtitle` correspons to that of `screenshot` command.
Screenshot of full window is not so useful anyway and client can make its own picture for window, so I don't think `window` option is needed.

Or, we can add the `subtitle` argument to `mpv_opengl_cb_render()` so that client can download the texture by itself if needed.

I'm not sure which one is better. Maybe there exists even better method.
Anyway, screenshot support is one of very common feature of video player and it should be there.

**Comment by wm4** [comment]
Yes... I thought about making it work for the screenshot commands. The rendering functions just needs to set a mp_image reference when it shows a new frame, and the screenshot VOCTRL would read it. Subtitles are added by the player core itself.

It's possible that keeping the reference to a frame is slightly more costly then the vo_opengl method, but I doubt that it has any impact. The screenshot code was added before mp_image was refcounted. And if you actually take screenshots, reading back the data is going to be extremely slower than keeping a reference to the original frame.

There's just one problem: hardware decoding. For this, we'd have to provide a generic way to read an memory image from a hw image reference. But this should be technically solveable.

**Comment by xylosper** [comment]
Still do I prefer downloading rendered texture because it contains all results of shader.
Otherwise, all effects by shader should be implemeted through CPU again.
I think even if command is supported, it would be nice to support rendering frame without subtitle/osd.

**Comment by wm4** [comment]
>Still do I prefer downloading rendered texture because it contains all results of shader.

vo_opengl doesn't download rendered textures either; just the original source picture.

> I think even if command is supported, it would be nice to support rendering frame without subtitle/osd.

You still can disable subs per normal command, and then render the frame into a FBO, and read it back.

> I think I cannot write the generic way to download from hw image because I cannot handle vda case.

pigoz can add it. It's not hard.

I'll probably add such a thing later or so.

**Comment by wm4** [comment]
>vo_opengl doesn't download rendered textures either; just the original source picture.

To clarify: that's what it normally does. There's an alternative screenshot mode ('window'), which just does glReadPixels on the window and thus captures the "actual" output. But it will always contain subs, unless subs were disabled in the player.

**Comment by xylosper** [comment]
> But it will always contain subs, unless subs were disabled in the player.

Oh, now I can see the consistency here. Okay, never mind the creepy opinion about mpv_opengl_cb_render().

**Comment by wm4** [comment]
This is implemented now. (Sorry about the delay.)
