### ISSUE TITLE
Progress Bar don't show up (volume, contrast, chapiters, video progression)

### ISSUE THREAD

**Issue by IniKiwi** [mpv-player/mpv#14487]
### mpv Information

```bash
![Capture d’écran du 2024-07-05 14-26-17](https://github.com/mpv-player/mpv/assets/99270745/088fb8c7-b37f-4ef2-9188-14dc01da08f4)
```

### Other Information

- Linux version: Buildroot
- Kernel Version: 6.1.24
- GPU Model: any (tested on qemu and real hardware)
- Mesa/GPU Driver Version: -
- Window Manager and Version: drm video backend
- Source mpv: buildroot 2024.05
- Introduced in version: -

### Reproduction Steps

- create a x86_64 buildroot
- install mpv, fonts, alsa, alsa-utils (alsactl init), libdrm
- do `mpv -vo (any video)`
- go foward and up/down volume
- no progressbar

### Expected Behavior

![IMG_20240705_143741](https://github.com/mpv-player/mpv/assets/99270745/361120d9-c41f-4275-bb86-1d0c5b795fde)
on debian 12 

### Actual Behavior

![image](https://github.com/mpv-player/mpv/assets/99270745/aa1440f1-5b8d-40b8-aa22-489048af83b7)
on buildroot

### Log File

[output.txt](https://github.com/user-attachments/files/16109872/output.txt)

### Sample Files

(disk image is too big)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by sfan5** [comment]
> mpv 0.35.1 

Old and unsupported.

**Comment by IniKiwi** [comment]
I should try 0.37?

**Comment by sfan5** [comment]
Yes
