### ISSUE TITLE
display thumbnail for of audio-only ytdl streams

### ISSUE THREAD

**Issue by quantenzitrone** [mpv-player/mpv#14499]
### Expected behavior of the wanted feature

```
mpv https://soundcloud.com/1odumdefect/imposter-2
```
Plays the audio, but does not display the cover art.
This is expected, because the stream that `yt-dlp` gets from soundcloud has no cover art.
However, `yt-dlp` can get the cover art links from websites with `yt-dlp --get-thumbnail <link>`.
I suggest, that when mpv detects that a ytdl stream has no video, it displays the thumbnail instead.
The resulting behaviour would be like this:
```
mpv --cover-art-file="$(yt-dlp --get-thumbnail https://soundcloud.com/1odumdefect/imposter-2 2>/dev/null)" https://soundcloud.com/1odumdefect/imposter-2
```

### Alternative behavior of the wanted feature

i create a yt-dlp wrapper that does that for me, but that would probably be very hacky

**Comment by guidocella** [comment]
`--script-opts-append=ytdl_hook-thumbnails=best`
