### ISSUE TITLE
Video incorrectly positioned with --vo=dmabuf-wayland at scales >1

### ISSUE THREAD

**Issue by mahkoh** [mpv-player/mpv#14505]
### mpv Information

```bash
mpv v0.38.0-586-gdaa6068d0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul  9 2024 15:37:37
libplacebo version: v6.338.2
FFmpeg version: n7.0.1
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

- Linux version:
- Kernel Version:
- GPU Model:
- Mesa/GPU Driver Version:
- Window Manager and Version:
- Source mpv:
- Introduced in version:

### Reproduction Steps

​

### Expected Behavior

​

### Actual Behavior

At scales >1, the video is not centered vertically. The bar at the top is much larger.

![20240709_15h43m43s_grim](https://github.com/mpv-player/mpv/assets/1882250/4268a7f9-b70b-47c9-9976-17b799173ae8)

### Log File

​

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Can't reproduce on sway, and you ignored the issue template.

**Comment by mahkoh** [comment]
It's possible that it also needs `--hwdec=vaapi` but `--vo=dmabuf-wayland` doesn't work for me otherwise in any case. Reproduces on gnome, sway, kde, etc. for me.

>you ignored the issue template.

Keep in mind that I verified this issue and reported it out of the goodness of my heart. I do not use these parameters for any actual video consumption and if it went unfixed then I would not be affected.

**Comment by Dudemanguy** [comment]
Can you provide a log file?

**Comment by mahkoh** [comment]
I'm unable to reproduce with current master. It did build master but it seems that I accidentally did not use it for testing.
