### ISSUE TITLE
Black border around volume change bar and progress bar became much too thin

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#14501]
### mpv Information

```bash
mpv v0.38.0-582-ge8e6e91c49-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul  8 2024 14:19:51
libplacebo version: v7.349.0
FFmpeg version: n7.0.1
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

- Linux version: Arch Linux
- Kernel Version: Linux archHTPC 6.9.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000 x86_64 GNU/Linux
- GPU Model: 1f:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106 [Geforce RTX 3050] [10de:2507] (rev a1)
- Mesa/GPU Driver Version:
- Window Manager and Version:
- Source mpv: self-built 
- Introduced in version: Unknown, what I'm looking to find

### Reproduction Steps

Use on a 4k window. Use --no-config and change the volume level or seek. Observe that the border around the drawn OSD is much thinner than it used to be.

### Expected Behavior

The bar should look something like: ![Untitled](https://github.com/mpv-player/mpv/assets/2280117/e29b6f1b-8367-4cbe-9613-61ee2fe19711)

### Actual Behavior

Instead it looks like:
![mpv-shot0006](https://github.com/mpv-player/mpv/assets/2280117/657863c7-c8a4-4d31-85fc-2ab86d0c2f4a)

### Log File

Not sure what log file would demonstrate this.

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
`--osd-bar-border-size`

**Comment by mlindner** [comment]
> `--osd-bar-border-size`

Yes I realize there's an option to change it. I'm asking why it changed. This is a regression.

**Comment by guidocella** [comment]
It was changed because it looks better.

**Comment by guidocella** [comment]
https://github.com/mpv-player/mpv/pull/12959
https://github.com/mpv-player/mpv/pull/12994

It looks better because the previous default was hideously thick. Most videos aren't white and even then you can still see the border just fine. Either way the option exists so you can customize it.

**Comment by mlindner** [comment]
> #12959 #12994
> 
> It looks better because the previous default was hideously thick. Most videos aren't white and even then you can still see the border just fine. Either way the option exists so you can customize it.

What was the purpose of the `float dent = MPMAX(border * 1.3, 1.6);` change?

**Comment by guidocella** [comment]
dent is the size of chapter markers and is proportional to the border. Giving them a minimum value makes them clearly visible even with a smaller border.

**Comment by hooke007** [comment]
It shouldn't be an issue here.
Post the discussion instead.
