### ISSUE TITLE
Add a feature to seek for any supported headers in a file

### ISSUE THREAD

**Issue by Damole-wer** [mpv-player/mpv#14509]
### Expected behavior of the wanted feature

Hello, I would like mpv to be able to play files that have some data before the correct file header.
Currently, if the header isn't the first data in a file, mpv will not play it.
Example: 
![A png from a Godot game ](https://github.com/mpv-player/mpv/assets/173204517/6b4aa900-1f0d-4328-90c2-4af76f0ca8ad) has `GDIM   png` before the actual `‰PNG` header. The only program I found that was able to open the image is InfranView.
So if you remove the `GDIM   png`, every program will play it without a problem:
![](https://github.com/mpv-player/mpv/assets/173204517/94215115-884a-4d45-b2b6-f174ee62c27e)
There is also
[a wave file (inside the archive)](https://github.com/user-attachments/files/16146001/archive.zip), that contains 3 wave audios, each starts with `RIFF` header. So mpv will open the first audio, but miss 2 of the rest.

I would like for 2 options to be added:
1. An option like --search-header: mpv will search the whole file for any supported headers -> stops on the first found -> plays it.
2. An option like --search-header-all: mpv will append each header found to a playlist and then plays the list ;)

That's all I wanted to ask, hope i made everything clear.
Thank you for continued support of this project!

**Comment by llyyr** [comment]
This is a feature request for ffmpeg, not mpv.

**Comment by llyyr** [comment]
> So you are saying that if it works with ffmpeg, mpv won't need any modifications?

Yep, if ffmpeg sees the file as a valid png then it will just work in mpv as well since we depend on ffmpeg (as well as the vast majority of programs you tried) to actually decode stuff for us.

> Should I delete the issue then?

Issues can't be deleted, you can close it though.
