### ISSUE TITLE
apply "audio downmix prof-cond" may cause lose v/a sync when switch to bluetooth

### ISSUE THREAD

**Issue by nanachisol** [mpv-player/mpv#14518]
### mpv Information

```bash
mpv v0.38.0-595-g91586539 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul 11 2024 12:09:50
libplacebo version: v7.349.0 (v7.349.0-dirty)
FFmpeg version: N-116228-g34b4ca869
FFmpeg library versions:
   libavcodec      61.10.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.28.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

- Windows version:10.0.22631.3880
- GPU model, driver and version:Ryzen 2700U With Vega 10,Adrenalin 24.3.1
- Source of mpv:zhongfly
- Introduced in version:n/a,may be early than https://github.com/mpv-player/mpv/commit/1a32bd3

### Reproduction Steps

1.mpv.conf inclue profile-condition like this:
```
[audio-filter]
profile-desc=When the audio channel is greater than 2, the dynamic range adjustment filter is used for dual channel equipment
profile-cond=p["audio-params/channel-count"] > 2
profile-restore=copy-equal
af-pre=@dynaudnorm:lavfi=[dynaudnorm=f=500:g=31:p=0.5:m=5:r=0.9]
```
2 play any video media file with 5.1 or 7.1 audio channel
3 switch audio output to bluetooth earpods
4 mpv lose audio for seconds then turn to normal
5 when play the media files wtih mpv --no-config,everything is fine.

### Expected Behavior

when switch to bluetooth ,we can immediately hear the sound from the bluetooth earpods

### Actual Behavior

when switch to bluetooth，mpv lose audio for seconds.

### Log File

[mpv.log](https://github.com/user-attachments/files/16191429/mpv.log)

### Sample Files

[samples](https://oshi.at/zpcZ)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Don't close issues just because nobody responded, it could still be helpful for others with the same issue.
