### ISSUE TITLE
mpv shows PipeWire warnings on the stats screen if PipeWire configuration files are missing

### ISSUE THREAD

**Issue by markozajc** [mpv-player/mpv#14517]
### mpv Information

```bash
mpv v0.37.0-632-g2a08440afb-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul 10 2024 20:44:20
libplacebo version: v6.338.2
FFmpeg version: 6.1.1-4+b4
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version: Debian testing
- Kernel Version: 6.9.7-1 (liquorix build)
- GPU Model: not a video issue, occurs even when compiled without video support
- Mesa/GPU Driver Version: ditto
- Window Manager and Version: ditto
- Source mpv: local build
- Introduced in version: v0.37, commit 2a08440afbe76548c583bd38ac9ae89300ed9d1d

Note: this issue has the same symptom as #11790, but is not fixed with `--ao=pulse` and only triggers when displaying the stats screen.

### Reproduction Steps

0. Make sure client-rt.conf is absent from the system. I don't know where libpipewire looks for it, so ideally reproduce this on a system without any pipewire components except libpipewire itself.
1. Play any media file or stream with `--ao=pulse --no-config`. I was reproducing the issue with an ogg audio file and `--no-video`
2. Press <kbd>i</kbd>  to trigger the stats screen.

### Expected Behavior

The stats screen is shown:
```
 (+) Audio --aid=1 (vorbis 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
File: audio.ogg
        Size: 6.380 MiB  Format/Protocol: ogg
        Total Cache: 57.28 KiB (1.0 sec)

Audio: Vorbis  AO: pulse
        Device: Autoselect device  AO Volume: 100% (Muted)
        Channels: 2  Format: floatp ➜ float
        Sample Rate: 48000 Hz
        Bitrate: 187 kbps
A: 00:00:01 / 00:04:37 (1%)
```

### Actual Behavior

Two pipewire warnings are printed (also mangling the terminal display) along with the stats screen:
```
 (+) Audio --aid=1 (vorbis 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
A: 00:00:03 / 00:04:37 (1%)[W][09477.196660] pw.conf      | [          conf.c: 1175 try_load_conf()] can't load config client-rt.conf: No such file or directory
[E][09477.196722] pw.conf      | [          conf.c: 1204 pw_conf_load_conf_for_context()] can't load config client-rt.conf: No such file or directory
File: audio.ogg
        Size: 6.380 MiB  Format/Protocol: ogg
        Total Cache: 57.28 KiB (1.0 sec)

Audio: Vorbis  AO: pulse
        Device: Autoselect device  AO Volume: 100% (Muted)
        Channels: 2  Format: floatp ➜ float
        Sample Rate: 48000 Hz
        Bitrate: 187 kbps
A: 00:00:01 / 00:04:37 (1%)
```

### Log File

Note: I press <kbd>i</kbd> on line 190
[output.txt](https://github.com/user-attachments/files/16169073/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
>this on a system without any pipewire components except libpipewire itself.

This isn't a valid pipewire installation according to upstream, the config files need to be installed together with libpipewire.

pipewire requires that the config files be present on the system. If client-rt.conf doesn't exist on your system, report it to your distro.

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3296#note_1963590

**Comment by markozajc** [comment]
I see. I will do that.

**Comment by markozajc** [comment]
Update for fellow Debian users: looks like this bug is already tracked as [#1038394](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038394) on the BTS. Installing `pipewire-bin` seems to be a working workaround for mpv without installing the entire PipeWire metapackage.
