### ISSUE TITLE
EIA-608 subtitles in TS not recognized

### ISSUE THREAD

**Issue by superbonaci** [mpv-player/mpv#14530]
### mpv Information

```bash
mpv --version
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 17 2024 19:18:44
libplacebo version: v7.349.0
FFmpeg version: 7.0.1
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Important Information

- Platform version:
- GPU model, driver and version:
- Source:
- Introduced in version:

### Reproduction Steps

The embedded EIA-608 subtitles in TS file are not displayed at all.

### Expected Behavior

Display them.

### Actual Behavior

No sub is displayed.

### Log File

[output.txt](https://github.com/user-attachments/files/16197884/output.txt)

### Sample Files

[600_160p.ts.zip](https://github.com/user-attachments/files/16197886/600_160p.ts.zip)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by superbonaci** [comment]
Related to this: https://github.com/mpv-player/mpv/issues/14529

**Comment by sfan5** [comment]
We don't need this twice.
