### ISSUE TITLE
Use the wayland linux-dmabuf protocol correctly for pixel formats

### ISSUE THREAD

**Issue by ikalco** [mpv-player/mpv#14544]
### Expected behavior of the wanted feature

git searches through the format_table that is sent over the protocol but it should actually be searching through it using the indicies that are sent over the tranches

only using the format_table can lead to using the wrong formats that are in the table but arent currently supported

from the protocol about tranche_formats
> This event advertises the format + modifier combinations that the compositor supports.

-----

useful resources
[the linux-dmabuf protocol](https://wayland.app/protocols/linux-dmabuf-v1)
[weston-simple-dmabuf-feedback](https://gitlab.freedesktop.org/wayland/weston/-/blob/main/clients/simple-dmabuf-feedback.c) (a reference impl, look at lines 1080 to 1176)

**Comment by Dudemanguy** [comment]
Yeah it's known the current format checking has some gaps. It's on the TODO list to make it better, but truthfully I find the protocol a bit confusing.

>tranche_formats

So to be clear on this before I actually try it, how would this differ from `format_table`? The description still says `This event advertises the format + modifier combinations that the compositor supports` so it doesn't seem like to me it would give what formats the specific device supports which is what we would actually need. I did a crude way of guessing that using DRM in #13500.

**Comment by ikalco** [comment]
so basically the format_table contains an array of formats, these can be arbitrary and compositors can put whatever formats/modifiers they want in there
the point of the tranches is to tell the client which indicies into that array are actually currently supported by the compositor

this makes the protocol flexible enough to, for example, switch from using the supported formats for an egl renderer to those for direct scanout

**Comment by Honkazel** [comment]
@Dudemanguy mpv still doesn't send scanout tranche with #14815

**Comment by Dudemanguy** [comment]
What does "send scanout tranche" mean in this context?

**Comment by Honkazel** [comment]
> What does "send scanout tranche" mean in this context?

tranche_flags i guess?
I'll ping OP for help 
@ikalco (sorry, but you know about this thing more, than me)

**Comment by ikalco** [comment]
for reference https://wayland.app/protocols/linux-dmabuf-v1

i see the confusion here, and its probably because of the naming in the protocol

the format_table is not the currently supported formats, its just an array of format/modifier pairs
the tranches index into the format_table to give supported formats for that tranche

the point of the tranches is to give the client a choice between different rendering systems in the compositor

for example the scanout flag in the tranche tells the client that if they use one of the formats in that tranche, the compositor will try to use direct scanout

**Comment by Honkazel** [comment]
> for reference https://wayland.app/protocols/linux-dmabuf-v1
> 
> i see the confusion here, and its probably because of the naming in the protocol
> 
> the format_table is not the currently supported formats, its just an array of format/modifier pairs the tranches index into the format_table to give supported formats for that tranche
> 
> the point of the tranches is to give the client a choice between different rendering systems in the compositor
> 
> for example the scanout flag in the tranche tells the client that if they use one of the formats in that tranche, the compositor will try to use direct scanout

But MPV doesn't scanout in Hyprland even with #14815 
From Hyprland logs:
> [LOG] [LinuxDMABUF] updateScanoutTranche: surface has no dmabuf_feedback

**Comment by llyyr** [comment]
> But MPV doesn't scanout in Hyprland

What does this mean? Are you referring to vo=dmabuf-wayland?

On sway with vo=gpu-next, with opengl we present DRM_FORMAT_XRGB2101010 that can be directly scanned out and with vulkan it's DRM_FORMAT_ABGR16161616 which can't.

**Comment by Honkazel** [comment]
> What does this mean? Are you referring to vo=dmabuf-wayland?

Yup

**Comment by llyyr** [comment]
> Yup

does hyprland not support nv12 direct scanout? fwiw I don't think it makes much sense to do a cpu conversion with dmabuf-wayland to please compositors, the point of the VO is that it's as low power as possible so a cpu conversion defeats the purpose.

**Comment by Honkazel** [comment]
> > Yup
> 
> does hyprland not support nv12 direct scanout? fwiw I don't think it makes much sense to do a cpu conversion with dmabuf-wayland to please compositors, the point of the VO is that it's as low power as possible so a cpu conversion defeats the purpose.

Hyprland could do NV12 DS.
> feedback: main device /dev/dri/renderD128
├─── tranche: target device /dev/dri/card1, scanout
│   ├─── format C8   (0x20203843), modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format C8   (0x20203843), modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format RGB565, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format RGB565, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format RGB565, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format XRGB8888, modifier INTEL_Yf_TILED_CCS (0x100000000000005)
│   ├─── format XRGB8888, modifier INTEL_Y_TILED_CCS (0x100000000000004)
│   ├─── format XRGB8888, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format XRGB8888, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format XRGB8888, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format XBGR8888, modifier INTEL_Yf_TILED_CCS (0x100000000000005)
│   ├─── format XBGR8888, modifier INTEL_Y_TILED_CCS (0x100000000000004)
│   ├─── format XBGR8888, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format XBGR8888, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format XBGR8888, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format ARGB8888, modifier INTEL_Yf_TILED_CCS (0x100000000000005)
│   ├─── format ARGB8888, modifier INTEL_Y_TILED_CCS (0x100000000000004)
│   ├─── format ARGB8888, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format ARGB8888, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format ARGB8888, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format ABGR8888, modifier INTEL_Yf_TILED_CCS (0x100000000000005)
│   ├─── format ABGR8888, modifier INTEL_Y_TILED_CCS (0x100000000000004)
│   ├─── format ABGR8888, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format ABGR8888, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format ABGR8888, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format XRGB2101010, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format XRGB2101010, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format XRGB2101010, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format XBGR2101010, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format XBGR2101010, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format XBGR2101010, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format XRGB16161616F, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format XRGB16161616F, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format XBGR16161616F, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format XBGR16161616F, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format YUYV, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format YUYV, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format YUYV, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format YVYU, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format YVYU, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format YVYU, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format UYVY, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format UYVY, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format UYVY, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format VYUY, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format VYUY, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format VYUY, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format NV12, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format NV12, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format NV12, modifier INTEL_X_TILED (0x100000000000001)
│   ├─── format XYUV8888, modifier INTEL_Yf_TILED (0x100000000000003)
│   ├─── format XYUV8888, modifier INTEL_Y_TILED (0x100000000000002)
│   ├─── format XYUV8888, modifier INTEL_X_TILED (0x100000000000001)

**Comment by llyyr** [comment]
> Hyprland could do NV12 DS.

Then something is fishy here because with 8 bit videos, dmabuf-wayland should output nv12 since that's what it gets from vaapi. With 10 bit hevc or av1, it should be p010.

**Comment by llyyr** [comment]
> Or other format, if it's autoconverted?

What do you mean? Can you provide logs for mpv?

**Comment by mahkoh** [comment]
Once you receive the [zwp_linux_dmabuf_feedback_v1::done](https://wayland.app/protocols/linux-dmabuf-v1#zwp_linux_dmabuf_feedback_v1:event:done) event you should proceed as follows:

For each tranch that was received in the order in which it was received: Collect all format+modifier pairs in this tranch that are supported by the rest of your stack. If any of those work for the rest of your stack, pick it. Otherwise proceed to the next tranch.

You can ignore the tranche_flag. Compositors will always send tranches in the order of preference. All formats+modifiers within a tranch have the same preference.

The `done` event WILL be sent multiple times during the lifetime of the application. Usually when the window enters or exists fullscreen. At that point you SHOULD recreate your buffers as per the algorithm above.

If you do not want to do this reallocation, then there is no point in using per-surface feedback. You can instead use the [zwp_linux_dmabuf_v1::get_default_feedback](https://wayland.app/protocols/linux-dmabuf-v1#zwp_linux_dmabuf_v1:request:get_default_feedback).

-------

Whether an application uses feedback has no direct impact on whether direct scanout works. On many systems, the format+modifier you pick or have another component pick is likely going to be able to be direct scanned out anyway. For example, my AMD cards can scan out all of the following formats with some modifiers:

- XRGB8888
- ARGB8888
- RGBA8888
- XRGB2101010
- XBGR2101010
- ARGB2101010
- ABGR2101010
- XRGB16161616
- XBGR16161616
- ARGB16161616
- ABGR16161616
- XBGR8888
- ABGR8888
- RGB565
- NV12
- P010
- XRGB16161616F
- ARGB16161616F
- XBGR16161616F
- ABGR16161616F

If a compositor supports any format at all, the burden for it to be scanned out directly is very low. Usually there is no compositor-side per-format logic involved.

>EDIT: Hyprland can do NV12 DS, but without DS it can't

If a compositor advertises a format that it cannot texture, that's a compositor bug.

**Comment by llyyr** [comment]
> [autoconvert] Converting vaapi[nv12] -> vaapi[rgb0]

I don't understand why this step is happening, please provide a log file with `--log-file=mpvsucks.log`

**Comment by Honkazel** [comment]
> > [autoconvert] Converting vaapi[nv12] -> vaapi[rgb0]
> 
> I don't understand why this step is happening, please provide a log file with `--log-file=mpvsucks.log`

[uh.txt](https://github.com/user-attachments/files/16948536/uh.txt)

**Comment by Honkazel** [comment]
> [   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'GR32(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YUV9(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YU11(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YU12(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YU16(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YU24(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YVU9(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YV11(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YV12(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YV16(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YV24(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'NV12(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'NV21(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'P010(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'P012(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'P016(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'P030(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'NV16(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'AYUV(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'XYUV(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'Y410(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'Y412(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'Y416(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YUYV(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'YVYU(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'UYVY(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'VYUY(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'Y210(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'Y212(00ffffffffffffff)'
[   0.037][d][vo/dmabuf-wayland/wayland] Compositor supports drm format: 'Y216(00ffffffffffffff)'

Yeah, i see

**Comment by llyyr** [comment]
> [   0.043][v][vo/dmabuf-wayland/vaapi] Mapped surface with format nv12; drm format 'NV12(0100000000000002)' is not supported by compositor and GPU combination.

mpv gets format nv12 with modifier I915_Y_TILED from vaapi but compositor can't direct scan out. This is probably a compositor bug.

**Comment by kasper93** [comment]
> does hyprland not support nv12 direct scanout? fwiw I don't think it makes much sense to do a cpu conversion with dmabuf-wayland to please compositors, the point of the VO is that it's as low power as possible so a cpu conversion defeats the purpose.

Yeah, CPU conversion should be avoided as fire. But we have ability to do hw->hw conversion. In this case it is not as bad. For example currently it does
```
[autoconvert] Converting vaapi[nv12] -> vaapi[rgb0]
```
which is not done on cpu. But surly if we can avoid any conversion and somehow make Hyprland support nv12 input, this would be preferable. Before PR #14815 it would just output nv12, but with wrong colors, because still it wasn't supported.

**Comment by Dudemanguy** [comment]
I believe the format selection should be correct for our purposes in the PR now. Strictly speaking, mpv would not handle a hypothetical case where a format is lost during playback (device switch I guess?) and the compositor sends a new set of events. Well, the wayland code in the PR should correctly update itself and select the new formats in this scenario so I think that covers this issue.

As for the hyprland thing, it looks like it simply doesn't advertise the drm format + modifier that is needed.

**Comment by ikalco** [comment]
the original issue is fixed, mpv seems to now use tranches correctly
so I'll close and open issue in Hyprland
