### ISSUE TITLE
mpv cannot play but PotPlayer can play the video

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#14550]
### mpv Information

```bash
mpv v0.38.0-601-gf470b63a Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul 12 2024 00:09:45
libplacebo version: v7.349.0 (v7.349.0-dirty)
FFmpeg version: N-116241-g70c6b904b
FFmpeg library versions:
   libavcodec      61.10.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.28.100
   libswresample   5.2.100
   libswscale      8.2.100

yt-dlp version
2024.07.09
```

### Other Information

- Windows version: 10
yt-dlp version
2024.07.09

### Reproduction Steps

 mpv --referrer="https://cdn3.turboviplay.com/" "https://cdn3.turboviplay.com/data1/xxxx"
[ytdl_hook] ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
[ytdl_hook] youtube-dl failed: unexpected error occurred
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
● Video  --vid=1  (png)

### Expected Behavior

mpv can play the video

### Actual Behavior

mpv cannot play but PotPlayer can play the video

### Log File

[mpv.zip](https://github.com/user-attachments/files/16233577/mpv.zip)

---

![image](https://github.com/user-attachments/assets/f1ed1ef8-2801-4922-a6aa-c62dcafc9cfb)

### Sample Files

![image](https://github.com/user-attachments/assets/0bdb9c29-4e6b-4d0f-8f6f-b5a0190858b3)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by CounterPillow** [comment]
that's not a complete log file as produced by `--log-file`.

**Comment by zhouxinghong** [comment]
How to use --log-file

**Comment by zhouxinghong** [comment]
@CounterPillow Log uploaded

**Comment by CounterPillow** [comment]
Thank you for now editing your initial response with the required information (log file). From your log file, this appears to be the same issue as #13978. Is there any particular reason why you've opened a new issue?

**Comment by zhouxinghong** [comment]
Because I don't know if you guys have fixed the issue! This issue comes up over and over again.

I didn't report the bug to you until I was sure the problem was with the mpv and not the streaming service. I hope you can fix it.

Thanks again for making mpv such a great media player.

**Comment by zhouxinghong** [comment]
What operating system are you using?
What operating system CPU are you using?
What operating system graphics card are you using?
What MPV version are you using?

**Comment by zhouxinghong** [comment]
You can really try it in the PotPlayer environment to see the player effect:

**Comment by zhouxinghong** [comment]
There is a great solution to this problem. Are you interested?

**Comment by zhouxinghong** [comment]
Hello friend! Thank you for the MPV player!
I found a solution that works:
https://code.videolan.org/videolan/vlc/-/issues/28757

**Comment by zhouxinghong** [comment]
Hello everyone!
Since the issue was previously closed so I'm reopening it and offering a solution that works:

logs 
```
 mpv --referrer='https://cdn3.turboviplay.com' 'https://cdn3.turboviplay.com/data1/H7LK7v5MU8SV1LIB5oAF/H7LK7v5MU8SV1LIB5oAF480.m3u8'
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
● Video  --vid=1  (png)
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] ...treating it as fatal error.
(Paused) V: 01:55:41 / 01:55:41 (100%) Cache: 0.0s
```
The key solution to fix the issue is as follows:
demux: adaptive: skip PNG junk when probing

**Comment by zhouxinghong** [comment]
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
● Video  --vid=1  (png)
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] ...treating it as fatal error.
(Paused) V: 01:55:41 / 01:55:41 (100%) Cache: 0.0s

Latest test link:

```
referrer=https://ryderjet.com/v/bcdzydcnzgat
https://ryderjet.com/stream/1MUALAaJW7QfSBMLLJq2GA/hjkrhuihghfvu/1779879689/39856499/index-v1-a1.m3u8
```
