### ISSUE TITLE
strange colorful line at the bottom in some videos

### ISSUE THREAD

**Issue by berndbb** [mpv-player/mpv#14559]
### mpv Information

```bash
mpv --version
mpv v0.38.0-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on May 23 2024 10:29:03
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version: NAME="Arch Linux

- Kernel Version: Linux amd64-archlinux 6.9.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 x86_64 GNU/Linux

- GPU Model:07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15dd] (rev c6)

- Mesa/GPU Driver Version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.1-arch1.1

- Window Manager and Version: xfce 4.18

- Source mpv: arch-linux repository

- Introduced in version: unknown

### Reproduction Steps

I reencoded a video using ffmpeg and the gpu for encoding.

When I play the result with mpv, I see a colorful line at the bottom of the video. Playing the file with vlc or using avidemux, I cannot see this line.

### Expected Behavior

Because this line isn't visible in the original video when playing it with mpv, I would expect it not to be there in the reencode (as it isn't seeable using vlc or avidemux playing the reencode).

The question is as first, if this is a mpv issue at all meaning: Maybe mpv shows a faulty file correctly whereas vlc and avidemux hide the faults of the video?

### Actual Behavior

> mpv --no-config test.mkv 
 (+) Video --vid=1 (*) (hevc 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (eac3 6ch 48000Hz)
AO: [pipewire] 48000Hz 5.1(side) 6ch floatp
VO: [gpu] 1920x1088 yuv420p
AV: 00:00:04 / 00:00:05 (98%) A-V:  0.000 ct: -0.051
Exiting... (End of file)

![image](https://github.com/user-attachments/assets/b442b773-c53e-450b-ade9-5172108b23e4)

### Log File

[output.txt](https://github.com/user-attachments/files/16253555/output.txt)

### Sample Files

[test-file and screenshot.zip](https://github.com/user-attachments/files/16250531/test-file.and.screenshot.zip)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
The artifacts are present even when playing the video back with ffplay, so it's most likely just a broken file.
