### ISSUE TITLE
When `demuxer-hysteresis-secs` is default value 0, `demuxer_secs==0` is `false` in lua script

### ISSUE THREAD

**Issue by zhongfly** [mpv-player/mpv#14569]
### mpv Information

```bash
mpv v0.38.0-614-g05b0b7cf Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul 16 2024 13:30:26
libplacebo version: v7.349.0 (v7.349.0-dirty)
FFmpeg version: N-116312-g635f7c0f6
FFmpeg library versions:
   libavcodec      61.10.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.28.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Important Information

- Platform version: windwos
- GPU model, driver and version: not related
- Source: zhongfly
- Introduced in version: don't know

### Reproduction Steps

1. add this lua script to mpv script folder:
```lua
local demuxer_secs = mp.get_property("demuxer-hysteresis-secs")
print(demuxer_secs)
if demuxer_secs then
	print("demuxer_secs is true")
else
	print("demuxer_secs is false")
end

if demuxer_secs==0 then
	print("demuxer_secs==0 is true")
else
	print("demuxer_secs==0 is false")
end

if demuxer_secs~=0 then
	print("demuxer_secs~=0 is true")
else
	print("demuxer_secs~=0 is false")
end

if (demuxer_secs-0)==0 then
	print("(demuxer_secs-0)==0 is true")
else
	print("(demuxer_secs-0)==0 is false")
end
```
3. run `mpv --no-config <video>`

### Expected Behavior

get `demuxer_secs==0 is true`

### Actual Behavior

[   0.025][i][test] 0.000000
[   0.025][i][test] demuxer_secs is true
[   0.025][i][test] demuxer_secs==0 is false
[   0.025][i][test] demuxer_secs~=0 is true
[   0.025][i][test] (demuxer_secs-0)==0 is true

### Log File

```
[   0.025][i][test] 0.000000
[   0.025][i][test] demuxer_secs is true
[   0.025][i][test] demuxer_secs==0 is false
[   0.025][i][test] demuxer_secs~=0 is true
[   0.025][i][test] (demuxer_secs-0)==0 is true
```

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
use `mp.get_property_native("demuxer-hysteresis-secs")`

hint: see what type your variable is with `print(type(demuxer_secs))`

**Comment by zhongfly** [comment]
Oh, I don't notice that it is a string and forget that lua does not do type conversion during comparison.
