### ISSUE TITLE
[Very important]  libmpv Vapoursynth -Dvapoursynth=enabled not work

### ISSUE THREAD

**Issue by ryou128hr** [mpv-player/mpv#14580]
### mpv Information

```bash
cplayer: mpv v0.38.0-623-ged77616f29 Copyright ﾂｩ 2000-2024 mpv/MPlayer/mplayer2 projects

[2024-07-19 17:23:11] cplayer:  built on Jul 18 2024 19:27:09

[2024-07-19 17:23:11] cplayer: libplacebo version: v7.349.0

[2024-07-19 17:23:11] cplayer: FFmpeg version: 6.1.1

[2024-07-19 17:23:11] cplayer: FFmpeg library versions:

[2024-07-19 17:23:11] cplayer:    libavcodec      60.31.102

[2024-07-19 17:23:11] cplayer:    libavdevice     60.3.100

[2024-07-19 17:23:11] cplayer:    libavfilter     9.12.100

[2024-07-19 17:23:11] cplayer:    libavformat     60.16.100

[2024-07-19 17:23:11] cplayer:    libavutil       58.29.100

[2024-07-19 17:23:11] cplayer:    libswresample   4.12.100

[2024-07-19 17:23:11] cplayer:    libswscale      7.5.100

[2024-07-19 17:23:11] cplayer:

[2024-07-19 17:23:11] cplayer: Configuration: -Dlibmpv=true -Dbuildtype=release
```

### Other Information

- Windows version:
- GPU model, driver and version:
- Source of mpv:
- Introduced in version:

### Reproduction Steps

[   2.208][d][cplayer] Run command: vf, flags=73, args=[operation="toggle", value="vapoursynth=\"~~/vs/AI4.vpy\""]
[   2.208][e][cplayer] Option vf-toggle: 'vapoursynth' isn't supported.

### Expected Behavior

[   2.208][d][cplayer] Run command: vf, flags=73, args=[operation="toggle", value="vapoursynth=\"~~/vs/AI4.vpy\""]
[   2.208][e][cplayer] Option vf-toggle: 'vapoursynth' isn't supported.

### Actual Behavior

[   2.208][d][cplayer] Run command: vf, flags=73, args=[operation="toggle", value="vapoursynth=\"~~/vs/AI4.vpy\""]
[   2.208][e][cplayer] Option vf-toggle: 'vapoursynth' isn't supported.

### Log File

[log.txt](https://github.com/user-attachments/files/16309378/log.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by CounterPillow** [comment]
> [   0.000][v][cplayer] Configuration: -Dlibmpv=true -Dbuildtype=release

You didn't build with vapoursynth.

> [Very important]

No it's not.

**Comment by ryou128hr** [comment]
How can I make

-Dvapoursynth=enabled

take effect?

**Comment by ryou128hr** [comment]
meson_options

> これは、中間子構成の一部としてビルド時に指定する必要があります。独自のmpvをコンパイルしていない場合は、その方法を学ぶ必要があります。
> 
> ただし、Issue Tracker はテクニカル サポート フォーラムではありません。これには[ディスカッション](https://github.com/mpv-player/mpv/discussions)を使用してください。


meson_options has option('vapoursynth', type: 'feature', value: 'auto', description: 'VapourSynth filter bridge').

meson setup --wipe build -Dvapoursynth=enabled

But it doesn't work.

**Comment by ryou128hr** [comment]
[main.cpp.txt](https://github.com/user-attachments/files/16309628/main.cpp.txt)

**Comment by CounterPillow** [comment]
Compiling your application that uses libmpv or somehow calls mpv otherwise with a "-Dvapoursynth=enabled" is not how this works. You need to compile mpv itself with that.

**Comment by ryou128hr** [comment]
> Compiling your application that uses libmpv or somehow calls mpv otherwise with a "-Dvapoursynth=enabled" is not how this works. You need to compile mpv itself with that.

I wrote main.cpp in VS2022.
Is this related?

**Comment by CounterPillow** [comment]
No.

I told you what the issue is.

The problem is that you do not understand as you do not actually know software development.
