### ISSUE TITLE
Bug Report: No Video Displayed When Using --start Parameter with mpv

### ISSUE THREAD

**Issue by yuchen-lea** [mpv-player/mpv#14599]
### mpv Information

```bash
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 17 2024 19:18:44
libplacebo version: v7.349.0
FFmpeg version: 7.0.1
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Other Information

- macOS version: macOS 13.6.3 (22G436)
- Source of mpv: brew

### Reproduction Steps

1. Open a terminal.
2. Execute the following command:
```
mpv "https://www.youtube.com/watch?v=vWpDs1riqbQ" --start=+130
```

### Expected Behavior

The video should start playing from the specified timestamp (2 minutes and 10 seconds) with both audio and video.

### Actual Behavior

Only audio is played, and the video is not displayed.
Execute without --start Parameter will play with both audio and video.
I'm not sure if this is related to #14091

### Log File

[output.txt](https://github.com/user-attachments/files/16386690/output.txt)

### Sample Files

<img width="743" alt="Snipaste_2024-07-26_12-55-19" src="https://github.com/user-attachments/assets/0ca9db91-8aa8-4b6f-b488-fbb6615ae987">

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by low-batt** [comment]
Did not reproduce for me using mpv built from master via [mpv-build](https://github.com/mpv-player/mpv-build) with an up to date `yt-dlp`:
```text
low-batt@gag mpv-build (master %=)$ mpv/build/mpv --no-config --start=+130 https://www.youtube.com/watch?v=vWpDs1riqbQ
● Video  --vid=1  --vlang=eng  (vp9 2560x1388 30 fps) [default]
● Audio  --aid=1  --alang=eng  (opus 2ch 48000 Hz) [default]
File tags:
 Uploader: John Kitchin
 Channel_URL: https://www.youtube.com/channel/UCQp2VLAOlvq142YN3JO3y8w
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [gpu] 2560x1388 yuv420p
AV: 00:02:20 / 00:07:41 (30%) A-V:  0.000 Cache: 6.2s/1MB    
Exiting... (Quit)
low-batt@gag mpv-build (master %=)$ yt-dlp --version
2024.07.25
```

Playback started with video at 2:10 as expected.

This test was run on a MacBook Pro with M1 chip under macOS 13.6.3.

**Comment by low-batt** [comment]
Using mpv 0.38.0 on a Mac with an older version of [yt-dlp](https://github.com/yt-dlp/yt-dlp) I was able to reproduce the behavior where no video was shown. After updating `yt-dlp` to version 2024.07.25, mpv 0.38.0 worked.

@yuchen-lea Check your version of `yt-dlp` and make sure it is up to date.

YouTube often changes their web page structure, sometimes breaking compatibility with `yt-dlp`.

**Comment by yuchen-lea** [comment]
Sorry for forgetting to check the version of yt-dlp, I found that the latest yt-dlp also works well with the older version of mpv. Thank you for your suggestion!
