### ISSUE TITLE
mpv desyncs after OS upgrade

### ISSUE THREAD

**Issue by lgbaldoni** [mpv-player/mpv#14595]
### mpv Information

```bash
mpv 0.36.0+git20230923.140d0185 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
FFmpeg version: 4.4.4
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
```

### Other Information

- Linux version: openSUSE Leap 15.6
- Kernel Version: 6.4.0-150600.23.7-default
- GPU Model: Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67DF]
- Mesa/GPU Driver Version: 4.6 (Compatibility Profile) Mesa 23.3.4
- Window Manager and Version: KDE Plasma 5.27.11/Wayland 
- Source mpv: official distro repo
- Introduced in version: I could not see the problem with 0.34 on the prior openSUSE Leap 15.5 release

### Reproduction Steps

Unsure. `hwdec = auto` and `hwdec-codecs = h264,vc1,hevc,vp8,av1,prores` or --no-audio-pitch-correction appear to have a role.
Speeding up the reproduction and then returning to 1x appear to trigger it also.

Using the stock OS-provided mpv and ffmpeg libraries from the packman repository.

I tried building current mpv against ffmpeg 7 and the problem might be gone, but there are too many variables in this.

### Expected Behavior

Normal smooth reproduction.

### Actual Behavior

`Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).`

### Log File

[output.txt](https://github.com/user-attachments/files/16379170/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
> mpv 0.36.0+git20230923.140d0185

We only provide support for the latest tagged release or newer. You can try removing `profile=high-quality` though
