### ISSUE TITLE
For cached video streams, display the video screen preview function when the mouse hovers over the progress bar

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#14619]
### Expected behavior of the wanted feature

Hello friend! 🌹.
Is it possible to add a feature that shows a preview of the video screen when the mouse hovers over the progress bar for a video stream that has been cached, like the one below:
![image](https://github.com/user-attachments/assets/90f85d45-f089-454c-8693-5da15161e417)
![image](https://github.com/user-attachments/assets/5da818a6-fd55-4f75-97aa-aa257649047e)

### Alternative behavior of the wanted feature

Hello friend! 🌹.
Is it possible to add a feature that shows a preview of the video screen when the mouse hovers over the progress bar for a video stream that has been cached, like the one below:
![image](https://github.com/user-attachments/assets/90f85d45-f089-454c-8693-5da15161e417)
![image](https://github.com/user-attachments/assets/5da818a6-fd55-4f75-97aa-aa257649047e)

**Comment by hooke007** [comment]
No
https://github.com/mpv-player/mpv/issues/14458

**Comment by da3dsoul1** [comment]
@zhouxinghong hey, can you share what osc interface are you using?
