### ISSUE TITLE
No video output with dmabuf_wayland on GTX 1080

### ISSUE THREAD

**Issue by E-Allie** [mpv-player/mpv#14627]
### mpv Information

```bash
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jan  1 1980 00:00:00
libplacebo version: v7.349.0
FFmpeg version: 6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version: NixOS 24.11 (Vicuna)
- Kernel Version: Linux 6.10.2 `#1`-NixOS SMP PREEMPT_DYNAMIC Sat Jul 27 09:40:36 UTC 2024 x86_64 GNU/Linux
- GPU Model: NVIDIA Corporation GP104BM [GeForce GTX 1080 Mobile] [10de:1be0] (rev a1)
- GPU Driver Version: NVIDIA Stable 555.58.02 and Beta 560.28.03 [closed kernel, proprietary driver]
- Mesa Version: Mesa 24.1.4
- Window Manager and Version: KDE Plasma/KWin 6.1.3
- Source mpv: OS repository/nixpkgs

On latest mpv [other versions untested], and latest stable and beta NVIDIA proprietary drivers, dmabuf-wayland fails to produce video.

### Reproduction Steps

With the hardware and software above, using dmabuf-wayland and any tested combination of gpu-api, gpu-context, and hwdec leads to no video output.

### Expected Behavior

Video Output

### Actual Behavior

No video output, with the status level error of:
status-level error of:

[hwupload] no support for this hw format
[hwupload] hardware format not supported
[autoconvert] HW-uploading to drm_prime
[hwupload] upload yuv420p -> drm_prime[yuv420p]
[hwupload] failed to upload frame
Cannot convert decoder/filter output to any format supported by the output.
Could not initialize video chain.

Possible additional context: When using other working vo's and hwdec, the output format tends to be along the lines of "cuda[nv12]", instead of drm_prime

### Log File

[output.txt](https://github.com/user-attachments/files/16475034/output.txt)

### Sample Files

Any and all videos tested yield the same result

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Dudemanguy** [comment]
dmabuf_wayland requires either vaapi or drmprime support. The latter is only relevant on SoC devices and AFAIK vaapi isn't going to work on nvidia so this is expected.

**Comment by E-Allie** [comment]
Excellent point:

When nvidia-vaapi-driver is used, the vaapi hardware decoder does work in the gpu-next context.

Attached are two additional logs, one where dmabuf_wayland fails in the presence of the vaapi driver, and the other where vaapi under gpu-next succeeds

[outputdmabuf.txt](https://github.com/user-attachments/files/16476912/outputdmabuf.txt)
[outputvaapi.txt](https://github.com/user-attachments/files/16476913/outputvaapi.txt)

**Comment by Dudemanguy** [comment]
gpu-next is using vaapi-copy which doesn't work for dmabuf-wayland because it still needs to hwupload the frame to vaapi. You can try specifying --hwdec=vaapi. I think it will fail for you.

**Comment by philipl** [comment]
`--hwdec=vaapi` will work with `--vo=gpu-next` if you use OpenGL. It does not work with Vulkan (IIRC, due to the Vulkan dmabuf import not being supported). I haven't tried with `--vo=dmabuf-wayland` but if it doesn't work it's almost certainly a driver limitation you'd need to deal with in the driver.
