### ISSUE TITLE
MPV_RENDER_PARAM_ICC_PROFILE requires use of internal bstrdup method

### ISSUE THREAD

**Issue by low-batt** [mpv-player/mpv#14633]
### mpv Information

```bash
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 17 2024 19:18:44
libplacebo version: v7.349.0
FFmpeg version: 7.0.1
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Other Information

- macOS version: macOS 13.6.3 (22G436)
- Source of mpv: brew installed
- Introduced in version: unknown

### Reproduction Steps

Write a separate libmpv client that uses the render API parameter `MPV_RENDER_PARAM_ICC_PROFILE` and has no access to mpv internal methods.

### Expected Behavior

The render API can be used without the need to access mpv methods that are not in the client and rendering API headers.

### Actual Behavior

The parameter `MPV_RENDER_PARAM_ICC_PROFILE` requires that the data pointer in the `mpv_byte_array` point to a `bstr`. I don't see a way in the client API to create a `bstr`. Did I miss something?

As can be seen in the following code from libmpv_helper.swift, internally mpv is using the internal method `bstrdup` when setting the render parameter `MPV_RENDER_PARAM_ICC_PROFILE`:
https://github.com/mpv-player/mpv/blob/5f768a688b706cf94041adf5bed7c7004af2ec5a/osdep/mac/libmpv_helper.swift#L148-L154

The `set_parameter` method expects the `data` pointer in the `mpv_byte_array` to be pointing to a `bstr`:
https://github.com/mpv-player/mpv/blob/5f768a688b706cf94041adf5bed7c7004af2ec5a/video/out/gpu/libmpv_gpu.c#L108-L110

If instead I copy the profile data a different way:
```swift
    guard let data = profile.iccProfileData else { return }
    let bytes = UnsafeMutablePointer<UInt8>.allocate(capacity: data.count)
    data.copyBytes(to: bytes, count: data.count)
    var icc = mpv_byte_array(data: UnsafeMutableRawPointer(bytes), size: data.count)
    withUnsafeMutableBytes(of: &icc) { (ptr: UnsafeMutableRawBufferPointer) in
      let params = mpv_render_param(type: MPV_RENDER_PARAM_ICC_PROFILE, data: ptr.baseAddress)
      mpv_render_context_set_parameter(mpvRenderContext, params)
    }
```

That triggers the crash shown below because `gl_lcms_set_memory_profile` attempts to free the data using`talloc_free` which correctly detects this is not a ta allocation and triggers an assert:
https://github.com/mpv-player/mpv/blob/5f768a688b706cf94041adf5bed7c7004af2ec5a/video/out/gpu/lcms.c#L123-L129

To get the client code to work using `bstrdup` I had to extract code from the `bstr.h` and `ta.h` headers and include that in my client. And change `ta.h` to make `ta_xmemdup` visible to library users and build a special version of libmpv.

### Log File

A log file is not applicable in this case as it is very clear what is happening given the code shown above.

This crash is from an experiment with a libmpv client where the data pointer in the `mpv_byte_array` did not point to a `bstr`, as discussed above.
```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x1a5348744 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1a537fc28 pthread_kill + 288
2   libsystem_c.dylib             	       0x1a528dae8 abort + 180
3   libsystem_c.dylib             	       0x1a528ce44 __assert_rtn + 272
4   libmpv.2.dylib                	       0x108ef58c4 ta_dbg_check_header + 112 (ta.c:291)
5   libmpv.2.dylib                	       0x108ef4cac get_header + 80 (ta.c:75)
6   libmpv.2.dylib                	       0x108ef518c ta_free + 24 (ta.c:238)
7   libmpv.2.dylib                	       0x108eb2020 gl_lcms_set_memory_profile + 112 (lcms.c:129)
8   libmpv.2.dylib                	       0x108ebede0 gl_video_set_icc_profile + 44 (video.c:605)
9   libmpv.2.dylib                	       0x108eb3c10 set_parameter + 132 (libmpv_gpu.c:110)
10  libmpv.2.dylib                	       0x108edc3b8 mpv_render_context_set_parameter + 60 (vo_libmpv.c:455)
11  IINA                          	       0x102f336e0 closure #1 in ViewLayer.setRenderICCProfile(_:) + 96 (ViewLayer.swift:284)
12  IINA                          	       0x102f33708 partial apply for closure #1 in ViewLayer.setRenderICCProfile(_:) + 24
13  libswiftCore.dylib            	       0x1b4185258 withUnsafeMutableBytes<A, B>(of:_:) + 64
14  libswiftCore.dylib            	       0x1b41851d4 withUnsafeMutableBytes<A, B>(of:_:) + 44
15  IINA                          	       0x102f33588 ViewLayer.setRenderICCProfile(_:) + 1568 (ViewLayer.swift:282)
16  IINA                          	       0x102f50094 VideoView.refreshEdrMode() + 1300 (VideoView.swift:437)
17  IINA                          	       0x103017d5c PlayerCore.refreshEdrMode() + 544 (PlayerCore.swift:1905)
18  IINA                          	       0x1030a91bc closure #3 in MPVController.handlePropertyChange(_:_:) + 76 (MPVController.swift:1181)
19  IINA                          	       0x102b9a614 thunk for @escaping @callee_guaranteed () -> () + 48
20  libdispatch.dylib             	       0x1a51ce874 _dispatch_call_block_and_release + 32
21  libdispatch.dylib             	       0x1a51d0400 _dispatch_client_callout + 20
22  libdispatch.dylib             	       0x1a51debf8 _dispatch_main_queue_drain + 928
23  libdispatch.dylib             	       0x1a51de848 _dispatch_main_queue_callback_4CF + 44
24  CoreFoundation                	       0x1a549fbc4 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
25  CoreFoundation                	       0x1a545d344 __CFRunLoopRun + 1992
26  CoreFoundation                	       0x1a545c428 CFRunLoopRunSpecific + 612
27  HIToolbox                     	       0x1aecb0df0 RunCurrentEventLoopInMode + 292
28  HIToolbox                     	       0x1aecb0c2c ReceiveNextEventCommon + 648
29  HIToolbox                     	       0x1aecb0984 _BlockUntilNextEventMatchingListInModeWithFilter + 76
30  AppKit                        	       0x1a8684908 _DPSNextEvent + 636
31  AppKit                        	       0x1a8683aa4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
32  AppKit                        	       0x1a8677f08 -[NSApplication run] + 464
33  AppKit                        	       0x1a864f358 NSApplicationMain + 880
34  IINA                          	       0x102dbea74 main + 12 (AppDelegate.swift:24)
35  dyld                          	       0x1a5027f28 start + 2236
```

### Sample Files

Any file will do.

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
Will be fixed by #14634
