### ISSUE TITLE
osd-back-color IGNORED

### ISSUE THREAD

**Issue by jackfrank7634** [mpv-player/mpv#14632]
### Other Information

- Windows version: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
- GPU model, driver and version:
- Source of mpv:
- Introduced in version:

### Reproduction Steps

If osd-back-color is defined, then a rectangular background is supposed to show up on the osd with the defined color/blur. osd-back-color is ignored, nothing happens, the rectangular background doesn't show up on the osd. This behavior persists since the last 3 versions.

### Expected Behavior

If osd-back-color is defined, then a rectangular background is supposed to show up on the osd with the defined color/blur

### Actual Behavior

osd-back-color is ignored, nothing happens, the rectangular background doesn't show up on the osd. This behavior persists since the last 3 versions.

### Log File

[output.txt](https://github.com/user-attachments/files/16488243/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Dudemanguy** [comment]
You need to set the corresponding `--osd-border-style` as well now. I presume you want `opaque-box`.

**Comment by jackfrank7634** [comment]
@Dudemanguy  Thanks, it worked!
