### ISSUE TITLE
Jerky video/dropped frames when playing 4k60 video with vo=dmabuf-wayland when the OSD is shown

### ISSUE THREAD

**Issue by mamarley** [mpv-player/mpv#14638]
### mpv Information

```bash
mpv 0.38.0-UNKNOWN Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0
FFmpeg version: 7.0.2-1ubuntu1
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

- Linux version: Ubuntu Oracular Oriole (development branch)
- Kernel Version: Linux mamarley-laptop 6.10.3-061003-generic #202408030619 SMP PREEMPT_DYNAMIC Sat Aug  3 06:47:12 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
- GPU Model: c1:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Phoenix1 [1002:15bf] (rev c4)
- Mesa/GPU Driver Version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.2.0~rc3-0ubuntu0~ppa0~24.10.0
- Window Manager and Version: Kwin 6.1.3
- Source mpv: https://launchpad.net/~mamarley/+archive/ubuntu/mpv-git
- Introduced in version: Unknown/not a regression

### Reproduction Steps

Play a 4k60 video (https://www.youtube.com/watch?v=LXb3EKWsInQ is a fine example) in MPV using vo=dmabuf-wayland on a system that has a >=4K screen, move the mouse to bring up the OSD, and wave the cursor back and forth over the playback progress bar.

### Expected Behavior

The video should continue to play smoothly.

### Actual Behavior

The video plays jerkily and the dropped frame counter increments rapidly.

This only happens with high-resolution 60fps video played at full resolution.  If I shrink the window to 1080p-ish size, the framedrops no longer occur.  The framedrops also do not occur with 30fps video.

### Log File

[mpv.log](https://github.com/user-attachments/files/16503856/mpv.log)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by mamarley** [comment]
mpv --version shows the git revision as UNKNOWN due to how Launchpad handles the automated builds, but the version with which I produced the log files was git25f441b740.

**Comment by llyyr** [comment]
Does this also happen with vo=gpu-next and profile=fast? dmabuf-wayland is a low-quality VO that relies on your compositor for rendering, so if it's jerky when direct scanout isn't active then it's probably on your compositor

**Comment by mamarley** [comment]
I think you're right; I did some further testing and found that it isn't just the video that is dropping frames, the compositor is dropping frames too when the OSD is updated.  (It doesn't just happen when the OSD is displayed, only when it changes.) 

If I use vo=gpu-next profile=fast, the OSD doesn't cause jerkiness and MPV doesn't report any framedrops, but the motion isn't smooth and it is definitely still dropping the occasional frame.  The CPU usage is also sky-high because this is software decoding.

If I use vo=gpu-next hwdec=vaapi, it seems to drop every other frame regardless of whether the OSD is up.  Is this worth reporting another bug?

If I use vo=gpu-next gpu-api=vulkan hwdec=vulkan, I get very few framedrops, but still some.

The only configuration that seems to get me smooth playback is vo=gpu hwdec=vaapi.

**Comment by llyyr** [comment]
> The only configuration that seems to get me smooth playback is vo=gpu hwdec=vaapi.

Because you're testing with a HDR video, gpu-next does better albeit slightly more expensive tonemapping of HDR content.`--vo=gpu-next --profile=fast --hwdec=auto-safe` should be the fastest combination of options.

**Comment by llyyr** [comment]
> which brings it inline with the power consumption for `vo=dmabuf-wayland`

dmabuf-wayland should theoretically be lower power consumption, and it is lower in practice on wlroots/sway as well. I don't know why it's the same on Kwin though.

**Comment by Dudemanguy** [comment]
Colorspaces are going to be broken on dmabuf-wayland until there's some sort of usable color management protocol.

**Comment by llyyr** [comment]
> Colorspaces are going to be broken on dmabuf-wayland until there's some sort of usable color management protocol.

That is unrelated to HDR videos looking desaturated. Even if we could communicate the colorspace to the compositor, they'd still look desaturated if your monitor wasn't HDR capable.

**Comment by Dudemanguy** [comment]
In theory, the compositor should be the one doing the tonemapping in this scenario.

**Comment by kasper93** [comment]
> In theory, the compositor should be the one doing the tonemapping in this scenario.

Until we have usable color management protocol, it is not possible. :|
