### ISSUE TITLE
Example inputs for musical pitch transposition.

### ISSUE THREAD

**Issue by paulguy** [mpv-player/mpv#14652]
### Expected behavior of the wanted feature

Considering pitch shifting has been added in https://github.com/mpv-player/mpv/commit/88885c0401c9e3adbc8dc916aab52753eb0e8f2e I think it could be useful to give an example somewhere in the documentation on adding musical pitch transposition inputs.  It's probably something someone can look up, but it'd be a super common use for this feature that it could save a lot of time.

### Alternative behavior of the wanted feature

Alternatively, I dunno if the math is complicated enough that a script would be needed.  At that point maybe it would have to be a third party external script.

### Log File

no functional issue here to show logs of

**Comment by Dudemanguy** [comment]
Not sure why this would go in the manual? Going up an octave in pitch is merely double the the frequency so `--pitch=2.0` is all you need. Assuming just the standard 12-tone western scales (which is 99.9% of relevant musical content), the difference in a semitone is multiplying by 2<sup>1/12</sup>. A full tone is 2<sup>2/12</sup> and so on. You can generate sine waves with ffmpeg and check against a tuner and the results are what I expect.

But actually thanks for mentioning this. I've just realized that I can finally solve the annoying problem of Rush's Xanadu being sped up in the studio to 452hz or something so it sounds like crap when I try to personally play along to it.

**Comment by paulguy** [comment]
I dunno, it's not _that_ obvious to someone who just might want to practice in a different key and not super familiar with the math and this is kinda the use of this for most people.  Not a super necessary "feature", just figured a nice convenience, but I don't figure it's important enough to add more default keybinds for.

**Comment by Dudemanguy** [comment]
Actually it's mentioned in the rubberband section, but the explanation is bad/non-existent imo.

**Comment by paulguy** [comment]
Oh, I missed that, whoops.
