### ISSUE TITLE
No audio when playing audio only files

### ISSUE THREAD

**Issue by viktor-grunwaldt** [mpv-player/mpv#14657]
### mpv Information

```bash
~/repos 1.9s ❱ mpv-0.38.0/mpv-0.38.0/build/mpv --version
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 10 2024 21:18:21
libplacebo version: v7.349.0
FFmpeg version: n7.0.1
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100

~/repos ❱ gcc --version
gcc (GCC) 14.2.1 20240805
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### Other Information

- Linux version: EndeavourOS
- Kernel Version: 6.10.3-zen1-2-zen x86_64 GNU/Linux
- GPU Model: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6950 XT] [1002:73a5] (rev c0)
- Mesa/GPU Driver Version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.5-arch1.1
- Window Manager and Version: KDE Plasma version 6.1.4
- Source mpv: compiled from .zip on releases
- Introduced in version: 0.38.0 (I can't check version 0.37.0 as it fails to compile: https://hastebin.com/share/qenemareqa.yaml, but previous version from arch repository didn't have this issue)

### Reproduction Steps

```
~/repos ❱ mpv-0.38.0/mpv-0.38.0/build/mpv ~/Music/KOAN\ Sound\ -\ Led\ by\ Ancient\ Light/KOAN\ Sound\ -\ Led\ by\ Ancient\ Light\ -\ 01\ Embers\ From\ Chaos.flac --no-config
```
Audio goes out via external USB DAC (XMOS Ltd iFi (by AMR) HD USB Audio)

### Expected Behavior

Audio is played.

### Actual Behavior

No audio on `.flac` `.opus` `.mp3` files (haven't tested other ones). Audio works with `.webp` `.mkv` `.mp4` files. Audio also works when playing these same files using VLC.

### Log File

[output.txt](https://github.com/user-attachments/files/16570730/output.txt)

### Sample Files

https://samplelib.com/sample-mp3.html

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by sfan5** [comment]
Have you checked the status of the pipewire audio stream with e.g. pavucontrol?

**Comment by viktor-grunwaldt** [comment]
Yes, there is no audio output. Also, I've checked whether maybe it's DAC's fault so I've tried with connected wireless headphones (Bose qc45) to my PC via bluetooth, with same result.

**Comment by llyyr** [comment]
> previous version from arch repository didn't have this issue)

I assume the last version that worked was 0.36 then? Can you try with `--ao=pulse` in that case?

**Comment by sfan5** [comment]
> Yes, there is no audio output

what does that mean?
is the stream there? is it muted? what about the volume?
can you see something in the volume meter?
can you see which output it's being played to?

**Comment by viktor-grunwaldt** [comment]
> > previous version from arch repository didn't have this issue)
> 
> I assume the last version that worked was 0.36 then? Can you try with `--ao=pulse` in that case?

No, the previous version was installed via pacman, and I assume, but don't remember exactly that I had `0.37.0-3` installed.

Using `--ao=pulse` fixes the issue.

**Comment by viktor-grunwaldt** [comment]
> > Yes, there is no audio output
> 
> what does that mean? is the stream there? is it muted? what about the volume? can you see something in the volume meter? can you see which output it's being played to?

Sorry, I'm not that technical with how audio on linux works. If by channel you mean the thing that opens up in the Playback tab in pavucontrol, then yes, it does open up, it is not muted, the VU meter does not move and is marked "silence". I can see which output it goes to - my dac.

**Comment by sfan5** [comment]
to be clear here's how it should look:
![grafik](https://github.com/user-attachments/assets/2d7dd001-796a-48d6-b4f5-85b57c1e5b7f)

if the volume bar is grayed out that means the stream is simply muted

**Comment by llyyr** [comment]
> Using `--ao=pulse` fixes the issue.

Can you try `pw-play <some audio file>` in a terminal? Also a screenshot of `pavucontrol` and `alsamixer` would be helpful to know what's exactly happening here

**Comment by viktor-grunwaldt** [comment]
Oh, I am so sorry.
It was muted inside playback.
