### ISSUE TITLE
`mpv` is (unexpectedly) maximized on GNOME and the `window-scale` option does not work

### ISSUE THREAD

**Issue by Arcohol** [mpv-player/mpv#14655]
### mpv Information

```bash
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jan  1 1980 00:00:00
libplacebo version: v7.349.0
FFmpeg version: 6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

- Linux version: `NixOS 24.11 (Vicuna)`
- Kernel Version: `Linux nixos-4800u 6.10.3 #1-NixOS SMP PREEMPT_DYNAMIC Sat Aug  3 07:01:09 UTC 2024 x86_64 GNU/Linux`
- GPU Model: `03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Renoir [Radeon Vega Series / Radeon Vega Mobile Series] [1002:1636] (rev c1)`
- Mesa/GPU Driver Version: `OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.4`
- Window Manager and Version: `GNOME 46.3.1 (Wayland) Mutter`
- Source mpv: `nixpkgs-unstable`

### Reproduction Steps

monitor setting: resolution 3840x2160, scale 200%
video: resolution 1920x1080

1. run `mpv --no-config foo.mp4`
2. run `mpv --no-config --window-scale=0.75 foo.mp4`
3. run `mpv --no-config --window-scale=1.25 foo.mp4`

### Expected Behavior

1. The window defaults to the video size (`window-scale`=1) and does NOT get maximized on start.
2. `window-scale` sets the correct window size.

That is:
1. run `mpv --no-config foo.mp4` => normal (not maximized) window, scaled to 100% video size
2. run `mpv --no-config --window-scale=0.75 foo.mp4` =>  normal (not maximized) window, scaled to 75% video size
3. run `mpv --no-config --window-scale=1.25 foo.mp4` => normal (not maximized) window, scaled to 125% video size

### Actual Behavior

1. run `mpv --no-config foo.mp4` => maximized window
2. run `mpv --no-config --window-scale=0.75 foo.mp4` =>  normal (not maximized) window, scaled to 75% video size
3. run `mpv --no-config --window-scale=1.25 foo.mp4` => maximized window, `window-scale` is not working

### Log File

`mpv --no-config --window-scale=1.25 --gpu-debug --log-file=output.txt foo.mp4`

[output.txt](https://github.com/user-attachments/files/16566947/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Arcohol** [comment]
```
[   0.367][v][vo/gpu] Resize: 2400x1350
[   0.367][v][vo/gpu] Window size: 2400x1350 (Borders: l=0 t=0 r=0 b=0)
[   0.367][v][vo/gpu] Video source: 1920x1080 (1:1)
[   0.367][v][vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 2400x1350
[   0.367][v][vo/gpu] Video scale: 1.250000/1.250000
[   0.367][v][vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[   0.367][v][vo/gpu] Video borders: l=0 t=0 r=0 b=0
[   0.367][v][vo/gpu] Reported display depth: 10
[   0.367][v][vo/gpu/wayland] Handling resize on the egl side
[   0.367][v][vo/gpu] Resize: 3840x2096
[   0.367][v][vo/gpu] Window size: 3840x2096 (Borders: l=0 t=0 r=0 b=0)
[   0.367][v][vo/gpu] Video source: 1920x1080 (1:1)
[   0.367][v][vo/gpu] Video display: (0, 0) 1920x1080 -> (57, 0) 3726x2096
[   0.367][v][vo/gpu] Video scale: 1.940625/1.940741
```
This part of the log looks suspicious, apparently an unwanted resize is called.

**Comment by llyyr** [comment]
Do you have any window rules for mpv? Try `--wayland-app-id=mpvsucks` maybe so any window rules you have aren't applied

**Comment by Arcohol** [comment]
> Do you have any window rules for mpv? Try `--wayland-app-id=mpvsucks` maybe so any window rules you have aren't applied

Not that I know of. Running `mpv --no-config --window-scale=1.25 --wayland-app-id=mpvsucks foo.mp4` produces the same behavior.

**Comment by Arcohol** [comment]
The problem seems to be resolved in the master branch.
