### ISSUE TITLE
HI! GL Extensions not supported. GL_ARB_shader_objects 

### ISSUE THREAD

**Issue by Steel-DSi** [mpv-player/mpv#14668]
### Other Information

- Windows version: 11 (Microsoft Windows [Version 10.0.22631.3958])
- GPU model, driver and version: AMD Radeon(TM) Graphics  (512 МБ) 31.0.14001.54001, NVIDIA GeForce RTX 4060 Laptop GPU  (8188 МБ) 31.0.15.5212, Dell Universal Dock D6000 9.3.3324.0; Monitor 0; Scaling windows 100%
- Source of mpv: I did not understand this parameter
- Introduced in version: 6.2.0-stable and 6.3.0

### Reproduction Steps

Try to reproduce your issue with --no-config first. If it isn't reproducible with --no-config try to find out which option or script causes your issue.
**- not help**
For decoding performance-related issues, additionally try to enable hardware decoding with --hwdec=yes or the Ctrl+h shortcut.
**- not help**

### Expected Behavior

starts → 2 seconds → blinks → 2 seconds → crashes from Task Manager

### Actual Behavior

-

### Log File

Make a log file with --gpu-debug --log-file=output.txt, which is our preferred way, and attach it to the issue.
**- no file**
If you have trouble producing a log file, you can alternatively use --gpu-debug -v -v, save the terminal output to a file, and attach it to the issue.
**- no data**
In the case of a crash, please provide a backtrace, attach the approriate .dmp file from %LOCALAPPDATA%\CrashDumps.
**- there is no current dump**

https://github.com/user-attachments/assets/6bc15ead-e87b-4a42-9c05-d21e6c92a738

![Screenshot 2024-08-13 164911](https://github.com/user-attachments/assets/f9f1b44c-8ce3-4ed5-8574-b92ba6de1a90)

[es_log.txt](https://github.com/user-attachments/files/16600281/es_log.txt)
"2024-08-13 15:46:02	ERROR	GL Extensions not supported. GL_ARB_shader_objects
2024-08-13 15:46:02	ERROR	Interrupt signal SIGSEGV received."

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
> Introduced in version: 6.2.0-stable and 6.3.0

These aren't mpv versions.

>  "2024-08-13 15:46:02 ERROR GL Extensions not supported. GL_ARB_shader_objects

mpv doesn't use this extension, and these messages also don't come from mpv.

**Comment by CounterPillow** [comment]
![winbabby](https://github.com/user-attachments/assets/0e481ba0-76cc-4c44-bb6c-023def91f4d2)

**Comment by Steel-DSi** [comment]
> ![winbabby](https://private-user-images.githubusercontent.com/308818/357448640-0e481ba0-76cc-4c44-bb6c-023def91f4d2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjAxMjQsIm5iZiI6MTcyMzU1OTgyNCwicGF0aCI6Ii8zMDg4MTgvMzU3NDQ4NjQwLTBlNDgxYmEwLTc2Y2MtNGM0NC1iYjZjLTAyM2RlZjkxZjRkMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QxNDM3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xN2RlMzdiNDgxMzFjZjgzNDJmNzVhMDdiNzY4OWFhM2NmOGNlODEwMzU0YTFjYjQzYzRjYjZlOTc4MjU4ZTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i1dKmYAYN2PCqNAXBPsWy1L-s9MG3gFLWp44tTzrWNs)

well, if there were extended logs. I would have understood something else myself. but to shamanize with a tool that is incomprehensible to me then to support)

**Comment by CounterPillow** [comment]
Our most sincere apologies for not making retrobat easier to understand for you. I'm sure mpv developers had a massive influence on this.

**Comment by Steel-DSi** [comment]
@CounterPillow @llyyr Sorry. I got the wrong topic. I am ashamed))
