### ISSUE TITLE
d3d11-output-csp in auto profile cause window flash

### ISSUE THREAD

**Issue by Norgerman** [mpv-player/mpv#14663]
### mpv Information

```bash
mpv v0.38.0-700-ge3f426aa Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 12 2024 00:07:59
libplacebo version: v7.349.0 (v7.349.0-5-g82bf46a-dirty)
FFmpeg version: N-116599-g43cde54fc
FFmpeg library versions:
   libavcodec      61.11.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.34.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

- Windows version: Microsoft Windows NT 10.0.22631.0/22631.3880
- GPU model, driver and version: Intel HD 630, 31.0.101.2127
- Source of mpv: https://github.com/shinchiro/mpv-winbuild-cmake
- Introduced in version: none.

### Reproduction Steps

use following config
```
spirv-compiler=shaderc
profile=gpu-hq
hwdec=yes
title=${filename}

vo=gpu-next
gpu-api=d3d11

[SDR]
profile-cond=get("video-params/primaries") and get("video-params/primaries") ~= "bt.2020"
profile-restore=copy
d3d11-output-csp=srgb
```
The window will flash.
But when move d3d11-output-csp outside, the window will be stable.

### Expected Behavior

Window of mpv should be stable and start playing.

### Actual Behavior

Window of mpv is flashing.

### Log File

[mpv.log](https://github.com/user-attachments/files/16579701/mpv.log)

### Sample Files

Maybe any video will cause the issue.

https://github.com/user-attachments/assets/84d63129-3682-4dcf-9246-62b6260f3056

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
It's not possible to change this option without reinitializing VO. But also, you shouldn't be setting this to anything but auto anyway

**Comment by Norgerman** [comment]
The version before such as last stable version, the version about 2-3 weeks ago, this option doesn't cause any issue. With recent version of mpv, this will make mpv keep flashing, and cannot start playing.

**Comment by zhongfly** [comment]
https://github.com/mpv-player/mpv/pull/14481

Before this merged, "d3d11-output-csp" option can't be changed at runtime.

**Comment by llyyr** [comment]
> The version before such as last stable version, the version about 2-3 weeks ago

Congrats, you've placebo'd yourself. As the above comment said, this option couldn't be changed at all during runtime before, so it did nothing at all.

**Comment by kasper93** [comment]
Well, not true if the profile is evaluated before the window is created, like in most cases.

**Comment by llyyr** [comment]
> Well, not true if the profile is evaluated before the window is created, like in most cases.

If this was true then they wouldn't have vo reinit now no?

**Comment by Norgerman** [comment]
Auto profile will be evaluated after before the window is created multi times because of some condition. Thanks.
