### ISSUE TITLE
Release manager wanted [was: Release 0.8.0]

### ISSUE THREAD

**Issue by ghedo** [mpv-player/mpv#1466]
Due to festivities and stuff, I'm kinda late on this, but I plan to release 0.8.0 this week (I haven't done any work yet though). Is there anything going on that needs waiting?

**Comment by wm4** [comment]
There are some big vo_opengl changes in preparation (smooth-motion, jinc), the opengl_cb API is still not entirely finalized, and I'm also redoing parts of the audio filter chain.

Maybe it would be better to make a 0.7.3?

**Comment by haasn** [comment]
Would this include the sigmoid scaling stuff?

It might make sense packaging all that (smooth-motion, sigmoid, jinc and possibly also some gamma changes I have planned) into a single, more major “feature release”, as that probably communicates the differences between versions better to end users.

**Comment by wm4** [comment]
>Would this include the sigmoid scaling stuff?

Yes. It was added a week ago, and excluding this feature from 0.8.0 would require additional work.

**Comment by pigoz** [comment]
Nope 0.7.3 would not include the sigmoid stuff, even though it's a 'fix' in
theory. 0.8.0 would be cut from master.

**Comment by ghedo** [comment]
Ok, so I cherry-picked a whole bunch of commits for a 0.7.3 release (see [here](https://github.com/ghedo/mpv/compare/v0.7.2...release/0.7)). It might be a good idea to verify that the OS X build still works.

**Comment by wm4** [comment]
Also, I'd pick all cocoa and coreaudio changes. Some more suggestions:

56882eaee4211ba158e82ecbd3da6c760dcc945e / 5beac919d0a2e9c7a2c103df13ee34cd2958269f
f6d7230a6fba0ab8040b1ebbdec7d3a5e2627640
d1aabb6316fd831d41da9c4b9d37048c7008e037
f0cdd673a80ff8f89b3f4c136620e398217bfccf
efd3f6f0d24a17c6c44b2bd5bdd0f42f2631ca8d
eb36bd6945bad1ddc80663f7b8d3fe95db3ca284
161bdbdb7af74396f8267a97cd8c78021ef1d0ae
98d09f735e19494d03b1d485bb2205402664bf1a
91b8a7f9943ed82b9e53178c798ce31a01174aa6
eec4b86bbc18926ca4a9d0b25c1b93a0e2924ae3
da997db09504767de63d434f0a6a6773827e670b
49d01d81e0d6c15c9a73fb8420eaabbad78dc56e
4b4d3a57bf9c793c8a938ab1cdcf4e856d5b0ca1
5a3070304fff7884d328cf1e8ac05f58b9e5bf99 (probably doesn't apply cleanly, but is somewhat important)
77a4a87e7eb822cefe07bfed5394a13e97faddbb
20f6cf3ec6996735f441cbd852e28879f0ee86de
6618e5d69ab2f1eef70769e46f4129d13bd7ff29
0fa9986a9803801fdf5e5f2286311542fd72edcf
a5832ba0194d278cb0813daf8b4af564e6848a61 / 63a414c708ea2986386639124fdfa9cdbd58e520
f2d6c8cb1cb51f05867f3c20b5c8b77213d64b80
f5b314e9e8685098badaf2bfc8f94422c0f9c4fc
44cc65e5fbb41c731e7762ee7d2396a8130e1b9d
fda44ecc923f0b5049d41bfcb785b382b0003e74
2b0fce56a225a24e9105f91fa1505d8eda8b9523
862a1b6e7eb3b16aad2d12196bd2410e996a27b1
6bb14a0d5960fd7376427036c766a20c1907e564
2ab259e6832dff38f13cdaa2a8c83b273efa8ec7
64e86b5b4ded09765a571796d1dff8cc6177d997
5f398831d2aac9f65bc3499101f529fa51eebdf7
794804725d76b489ed28cbcdb33d12d8bafa23c5

(Sorry if some were already picked by you.)

**Comment by pigoz** [comment]
20f6cf3ec69 needs to be picked only if we wanna pick the new chmap_sel fallback system

**Comment by mc4man** [comment]
I won't mind seeing this, would stop having to explain what to do. If not possible, well such is..
09c701b

**Comment by ghedo** [comment]
Ok, I picked some new commits. From the @wm4 list there were some that either didn't apply or caused the build to fail (77a4a87, eec4b86, f0cdd67, 4b4d3a5, f5b314e, 862a1b6). I did pick 5a30703 though.

I don't have much time to write the release notes right now though.

**Comment by ghedo** [comment]
Actually, 5a30703 caused build failures as well, so I removed it now.

**Comment by wm4** [comment]
> From the @wm4 list there were some that either didn't apply or caused the build to fail (77a4a87, eec4b86, f0cdd67, 4b4d3a5, f5b314e, 862a1b6). I did pick 5a30703 though.

Did you confirm whether the issues they fix exists in the release? If not, it's fine to leave them away, but only then.

>Actually, 5a30703 caused build failures as well, so I removed it now.

But it's important. Do you want users of these Intel GPUs to see garbage by default?

I'd rather have no releases at all, instead of crappy ones.

**Comment by ghedo** [comment]
I probably wasn't clear before, but the reason I didn't pick those commits was because I didn't have time to investigate the issues, and it was certainly not definitive.

In any case, it appears I have less and less time and interest to dedicate to mpv releases (it's generally a pretty boring and time consuming job, if done right), so I'd really appreciate if someone could step up and help in that (particularly writing release notes). That is, if there's anyone actually interested in releases beside me.

In the meantime, it's IMO better that I step down as the "release guy" and put a temporary hold to releases, so as to avoid doing a shoddy job ("crappy releases" as wm4 put it). I'm still interested in having official mpv releases, it's just too much work for me to handle alone.

**Comment by wm4** [comment]
>In any case, it appears I have less and less time and interest to dedicate to mpv releases (it's generally a pretty boring and time consuming job, if done right), so I'd really appreciate if someone could step up and help in that (particularly writing release notes). 

OK, so we don't have a release manager again. Yes, maintaining releases requires some work, and it's annoying. It should involve some testing too, and making sure that all bug fixes went in, and even adjusting past commits to make them apply. It's not easy. After all, I didn't want to continue doing this either.

On the other hand, I don't see much reason to care about releases. It seems they're mostly for distros, and if distros insist on such things, they should do the work themselves.

We discussed the possibility of doing weekly snapshots on IRC. These snapshots would take over the function of releases. Maybe we'll do this, if nobody else volunteers.

**Comment by haasn** [comment]
Strongly agree that releases are not worth the effort. Much more useful to maintain a decent git repository. If version numbers are used, they can just be numbered git tags.

Personally I use rolling release distros and live packages and don't see the problems with this approach.

**Comment by ghedo** [comment]
Putting my Debian maintainer hat on.

From my POV, uploading packages based on snapshot of git master every now and then is really a no brainer, and so is cherry-picking specific patches when users submit bug reports.

However, one of the most useful parts about releases is release notes. Particularly for users, it's important to see what new features or user visible changes a new version brings but it may not be possible for them to understand the git log (e.g. many changes span multiple non-consecutive commits, or just obscure messages).

The way I managed release notes so far is not very efficient: just before a new release I would scan the commits of the previous weeks and add whatever I thought was important. This not only is boring and error-prone, but it means that the entries in the changelog are written by a person who may not completely understand what a particular change does.

Many other projects however, keep a changelog in the master branch, and update it as soon as a change is committed. This scales better (the load is shared among all committers) and potentially means better entries are written because they are made by the people who understand the changes better (i.e. the ones who actually made those changes). No need to add everything of course, just the most important stuff.

In this case 99% of the work required by a new release is already done, and at that point one person may, every couple months or so, just update the header of the changelog and create a new tag in master. No need for release branches or point releases. Just snapshots of master with a nice changelog.

**Comment by wm4** [comment]
I don't like in-repo changelogs. They just keep growing, and eventually are outdated and inaccurate. But we thought about using a special marker in git commit messages (something like ``[changelog]``), which would be extracted by a script to produce a "proper" changelog.

**Comment by ghedo** [comment]
> I don't like in-repo changelogs. They just keep growing, and eventually are outdated and inaccurate

Well, the changelog can be reset after each release...

> But we thought about using a special marker in git commit messages

Yeah, that seems nice too (although it may make commit messages a bit repetitive).

**Comment by Pacoup** [comment]
If you're gonna tag master, how about simply providing the changelog as a list of commits from one tag to the next <a href="https://chromium.googlesource.com/chromium/src/+log/41.0.2272.3..41.0.2272.12?pretty=fuller&n=10000">like Google does for Chrome</a>? 

Not super pretty, but easy to maintain.

Is that possible with GitHub?

**Comment by ghedo** [comment]
> how about simply providing the changelog as a list of commits from one tag to the next

As I wrote above, this doesn't actually work. Most commits are not relevant to the users, and the ones that are more often than not have obscure messages that would require the users to know how mpv internals work to understand them. Additionally many big changes span several non-consecutive commits, while others are added and then removed before a new release is made making the git log even more confusing.

**Comment by Paviluf** [comment]
I really hope a solution can be found because for us, simple users, if there is no more release we will use an outdated MPV as the time goes on.

Ghedo, thanks to you we can enjoy MPV and maybe if devs use what wm4 propose (a special marker in git commit messages) it will simplify a lot your work and you can continue to make the releases ?

**Comment by Kovensky** [comment]
How difficult / what is the process of release management, at least as it would apply to mpv?
Most of what I have been doing lately is basically reading `git log` every few weeks and commenting way after the commit was relevant, so maybe I could turn that "skill" into something useful :)

**Comment by wm4** [comment]
Well, you could give it a try and make a 0.7.3 release...

**Comment by ghedo** [comment]
@Kovensky the release process is documented in the https://github.com/mpv-player/mpv/blob/master/DOCS/release-policy.md file (feel free to ask if you have any question).

If you want to try and do a 0.7.3 release you may want to start from my fork (https://github.com/ghedo/mpv/tree/release/0.7), it already contains a few commits (but see discussion above) and the release notes need to be written.

**Comment by Kovensky** [comment]
OK, so I tried to include as many of the suggested commits as possible (including 5a30703), and tried combing through logs since mid-december and cherry-pick anything that looked "bugfix-y" (that wasn't fixing things on, say, opengl_cb) and it `WORKSFORME` so far on OSX, but I'm getting a mysterious `../DOCS/man/lua.rst:684: (ERROR/3) Unknown target name: "details on the script initialization and lifecycle".` non-critical error (`git grep` can't find that string anywhere). Oh well.

I also picked pretty much all of the WASAPI commits, but I haven't set up a windows build system yet so I don't know if it even compiles. Wayland changes might also need testing. I pushed things to the release/0.7 branch but I might have to do some more force pushes in case there are missed commits.

Suggestions for extra commits to be included are welcome as well.

**Comment by wm4** [comment]
>but I'm getting a mysterious ../DOCS/man/lua.rst:684: (ERROR/3) Unknown target name: "details on the script initialization and lifecycle". 

The thing on line 684 is a link, which leads to nowhere. Apparently some other part of the manpage changes wasn't picked... (And yes, the rst syntax for links is awkward.)

**Comment by rossy** [comment]
> I also picked pretty much all of the WASAPI commits, but I haven't set up a windows build system yet so I don't know if it even compiles.

release/0.7 builds for me, though I didn't do much testing with it.

**Comment by Kovensky** [comment]
@wm4 yeah, indeed, I picked a commit that "fixes a link" but only because the link got renamed on a commit that I skipped (updates documentation to include newer APIs that are not in the stable release... AFAIK). Threw it away and (surprise) force-pushed ._.

**Comment by Kovensky** [comment]
Committed a RELEASE_NOTES update at 8dbdb8e; let me know if something I left out should be put in, or phrasing fixes.

If nothing else goes wrong, I'll tag it tomorrow morning (~18 hours from now).

@ghedo what is the build process for the _mac tarballs you upload?

**Comment by wm4** [comment]
Looks good to me. I didn't test it on Linux or Windows.

**Comment by pigoz** [comment]
Looks good!

**Comment by ghedo** [comment]
> what is the build process for the _mac tarballs you upload?

I don't know, I'm not the one who uploads them.

Anyway, looks good to me.

**Comment by Kovensky** [comment]
Tagged and released v0.7.3

**Comment by ghedo** [comment]
Not sure if I'm missing something, but I just pulled mpv.git and the v0.7.3 tag is not there, and if you look at the [release/0.7 branch](https://github.com/mpv-player/mpv/tree/release/0.7), the "Release 0.7.3" commit is not listed and the VERSION file is still at 0.7.2...

**Comment by wm4** [comment]
I can't find a ``v0.7.3`` tag either, although github seems to know it. It's a mystery to me... shouldn't ``git fetch origin`` retrieve it? It certainly worked when ghedo made releases. This also causes mpv-build to use 0.7.2 when using releases.

**Comment by Kovensky** [comment]
I... think I see what happened. `git push --tags` doesn't push commits + tags, but pushes _only_ tags...

**Comment by wm4** [comment]
I still wonder how you created the release with the github interface, which requires a live tag...

Anyway, all done now, thanks to everyone.
