### ISSUE TITLE
mpv fails to playback 1 channel raw PCM

### ISSUE THREAD

**Issue by guest271314** [mpv-player/mpv#14677]
### mpv Information

```bash
mpv 0.38.0
```

### Other Information

- Linux version: Ubuntu 22.04.1 LTS
- Kernel Version: Linux xubuntu 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- GPU Model:
- Mesa/GPU Driver Version:
- Window Manager and Version:
- Source mpv:
- Introduced in version:

### Reproduction Steps

Try to play raw 1 channel PCM from `stdin`

`piper.js`

```
import $ from "./dax.js";
try {
  await $`echo ${Deno.args[1]} | $HOME/.local/opt/piper/piper -q
  --length_scale 1
  --sentence_silence 0
  --model ./en_US-hfc_${Deno.args[0]}-medium.onnx --output-raw`
    .stdout(Deno.stdout.writable);
} catch (e) {
  $.logError(e.message);
  $`exit(1)`;
}
```

```
$ deno run -A piper.js male test | mpv --no-video --demuxer-rawaudio-format=s16le  --demuxer-rawaudio-rate=22050 --demuxer-rawaudio-channels=1 -
```

### Expected Behavior

`mpv` to playback the raw ` channel PCM.

This works using `aplay`

```
deno run -A piper.js male test | aplay -r 22050 -f S16_LE -t raw -
Playing raw data 'stdin' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
```

### Actual Behavior

```
$ deno run -A piper.js male test | mpv --demuxer-rawaudio-format=s16le  --demuxer-rawaudio-rate=22050 --demuxer-rawaudio-channels=1 --gpu-debug --log-file=output.txt --no-video -
[file] Reading from stdin...
Failed to recognize file format.
Exiting... (Errors when loading file)
```

### Log File

[output.txt](https://github.com/user-attachments/files/16632067/output.txt)

Looks like `mpv` is trying to load MP3 demuxer for PCM?

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by CounterPillow** [comment]
Try `--ad=pcm_s16le`

**Comment by guest271314** [comment]
Same result.

```
echo "test" | $HOME/.local/opt/piper/piper -q --length_scale 1 --sentence_silence 0 --model $HOME/localscripts/vits-web-extension/en_US-hfc_male-medium.onnx --output-raw - | mpv --demuxer-rawaudio-format=s16le  --demuxer-rawaudio-rate=22050 --demuxer-rawaudio-channels=1 --ad=pcm_s16le --gpu-debug --log-file=output.txt --no-video -
[file] Reading from stdin...
Failed to recognize file format.
Exiting... (Errors when loading file)

```

**Comment by guest271314** [comment]
Looks like `mpv` is interpreting the raw PCM stream as MP3?

```
[   1.089][d][demux] Trying demuxer: lavf (force-level: normal)
[   1.099][v][lavf] Found 'mp3' at score=1 size=2048.
[   1.100][v][lavf] Found 'mp3' at score=1 size=8192.
[   1.160][v][lavf] No format found, try lowering probescore or forcing the format.
[   1.160][d][demux] Trying demuxer: mf (force-level: normal)
[   1.160][d][demux] Trying demuxer: playlist (force-level: normal)
[   1.160][d][demux] Trying demuxer: null (force-level: normal)
[   1.160][v][demux] Trying demuxers for level=unsafe.
[   1.160][d][demux] Trying demuxer: disc (force-level: unsafe)
[   1.160][d][demux] Trying demuxer: edl (force-level: unsafe)
[   1.160][d][demux] Trying demuxer: cue (force-level: unsafe)
[   1.160][d][demux] Trying demuxer: rawaudio (force-level: unsafe)
[   1.160][d][demux] Trying demuxer: rawvideo (force-level: unsafe)
[   1.160][d][demux] Trying demuxer: mkv (force-level: unsafe)
[   1.160][d][demux] Trying demuxer: libarchive (force-level: unsafe)
[   1.160][d][file] resize stream to 262144 bytes, drop 0 bytes
[   1.161][d][demux] Trying demuxer: lavf (force-level: unsafe)
[   1.173][v][lavf] Found 'mp3' at score=1 size=2048.
[   1.174][v][lavf] Found 'mp3' at score=1 size=8192.
[   1.176][d][file] resize stream to 131072 bytes, drop 0 bytes
[   1.183][v][lavf] No format found, try lowering probescore or forcing the format.
[   1.183][d][demux] Trying demuxer: mf (force-level: unsafe)
[   1.183][d][demux] Trying demuxer: playlist (force-level: unsafe)
[   1.184][d][demux] Trying demuxer: null (force-level: unsafe)
[   1.184][v][cplayer] Opening failed or was aborted: -
[   1.184][v][cplayer] Running hook: ytdl_hook/on_load_fail
[   1.184][v][ytdl_hook] full hook
[   1.184][v][cplayer] finished playback, unrecognized file format (reason 4)
[   1.184][e][cplayer] Failed to recognize file format.
[   1.184][i][cplayer] Exiting... (Errors when loading file)
[   1.185][d][console] Exiting...
[   1.185][d][ytdl_hook] Exiting...
[   1.185][d][auto_profiles] Exiting...
[   1.187][d][cplayer] Run command: del, flags=64, args=[name="user-data/osc"]
[   1.187][d][stats] Exiting...
[   1.187][d][osc] Exiting...
```

**Comment by llyyr** [comment]
Can you try `--ad=+pcm_s16le` to force it? Also would it be possible to generate a sample file?

**Comment by guest271314** [comment]
Doesn't change anything

```
echo "test" | $HOME/.local/opt/piper/piper -q --length_scale 1 --sentence_silence 0 --model $HOME/en_US-hfc_male-medium.onnx --output-raw - | mpv --demuxer-rawaudio-format=s16le  --demuxer-rawaudio-rate=22050 --demuxer-rawaudio-channels=1 --ad=+pcm_s16le --gpu-debug --log-file=output.txt --no-video -
[file] Reading from stdin...
Failed to recognize file format.
Exiting... (Errors when loading file)

```
[output.pcm.tar.gz](https://github.com/user-attachments/files/16633643/output.pcm.tar.gz)

This works using `aplay` with the attached `output.pcm` file

```
$ aplay -r 22050 -f S16_LE -t raw output.pcm
```

**Comment by llyyr** [comment]
`--demuxer=rawaudio -demuxer-rawaudio-format=s16le --demuxer-rawaudio-rate=22050 --demuxer-rawaudio-channels=1` works. By default, rawaudio (or rawvideo) will never be used unless the user explicitly requests it

**Comment by guest271314** [comment]
@llyyr That works. 

It would be helpful to include that in conspicuous documentation and in the help entry.

**Comment by llyyr** [comment]
https://github.com/mpv-player/mpv/commit/3269bd178020c5d821e8b2d1fd807a38d63e93ce#diff-4a98544377571da9a13ef3ed52e3f8d95f83940b564634b15caad1ad7a920322R52

The change was made in 2013 when our docs weren't extensive enough and this might be the first time anyone has actually tried using those demuxers. It's probably a fine idea to add it to --demuxer=help text

**Comment by guest271314** [comment]
Should I file the PR, or are you going to? 

Something like "To play raw PCM... use `--demuxer=rawaudio --demuxer-rawaudio-format=s16le --demuxer-rawaudio-rate=<samplerate> --demuxer-rawaudio-channels=<number_of_channels>`"

?

**Comment by llyyr** [comment]
Just mentioning that rawvideo/rawaudio aren't used unless explicitly requested or forced by the user.
