### ISSUE TITLE
Slow read speeds over samba on macOS

### ISSUE THREAD

**Issue by j9ac9k** [mpv-player/mpv#14670]
### mpv Information

```bash
mpv v0.38.0-701-gacc69e082f Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 13 2024 21:41:50
libplacebo version: v7.349.0
FFmpeg version: 7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

- macOS version: 14.6.1
- Source of mpv: github clone + build
- Introduced in version: unknown

### Reproduction Steps

I get very poor network transfer speeds over a mounted samba share on macOS. 

```zsh
/usr/local/bin/mpv --no-config --profile=fast --hwdec=yes "/Volumes/videos/Reference/No Time to Die (2021).mkv"
```

The transfer rate varies by the video (which I found to be odd); but broadly is unable to keep up with playback speed:

![image](https://github.com/user-attachments/assets/02116b41-09d4-4fe2-a4ef-d01f621fdc43)

To ensure the issue isn't just the slow connection via Samba, I run `rsync` on the same file to my local disc, which I'm able to average approximately 10 MB/s.

![image](https://github.com/user-attachments/assets/156715bb-882b-4493-b39a-090e04dd8dc8)

Perhaps a note of interest: the samba server is being accessed via a site-to-site VPN, the server itself is quite some geographic distance away.  `ping` times are between 215 and 220 ms (but very consistent); and there is no measurable packet loss.

Second note of interest: when I go to play a file a second (or third, fourth...) time, I briefly get expected read/transfer speeds, but after a while, it drops off to slower speeds.

### Expected Behavior

Read speed over samba should be in the ballpark of file transfer speed from the same share.

### Actual Behavior

Read speed over samba is significantly less than file transfer speed, resulting in any kind of playback frequently stopping to recache.

### Log File

[output.txt](https://github.com/user-attachments/files/16604289/output.txt)

### Sample Files

https://www.icloud.com/iclouddrive/0e3fC_ltX-orx_bWqP1LRbO2A#Meridian%5F3840x2160%5F5994fps%5FHDR10

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Can you try setting a bigger buffer size? https://mpv.io/manual/master/#options-stream-buffer-size

**Comment by j9ac9k** [comment]
> Can you try setting a bigger buffer size? https://mpv.io/manual/master/#options-stream-buffer-size

Thanks for the fast response! Doesn't seem make a difference from what I can tell, still in a constant state of "reading" and "underrun"

```zsh
/usr/local/bin/mpv --no-config --profile=fast --hwdec=yes --gpu-debug --log-file=output.txt --stream-buffer-size=1MiB "/Volumes/videos/Reference/No Time to Die (2021).mp4"
```

![image](https://github.com/user-attachments/assets/b0e3941a-c2ff-4f80-9e89-f7059dc710ba)

[output.txt](https://github.com/user-attachments/files/16604500/output.txt)

**Comment by Akemi** [comment]
wonder if it's related to this old closed issue (https://github.com/mpv-player/mpv/issues/4434) and the stream check not working anymore for the fix (https://github.com/mpv-player/mpv/commit/f8128f6570cfee1d076811c8c2abb9e82c4834bc).

maybe the identifier [here](https://github.com/mpv-player/mpv/blob/f8128f6570cfee1d076811c8c2abb9e82c4834bc/stream/stream_file.c#L175-L186) changed?

i will try to look into this further soon.

**Comment by j9ac9k** [comment]
> wonder if it's related to this old closed issue (#4434) and the stream check not working anymore for the fix ([f8128f6](https://github.com/mpv-player/mpv/commit/f8128f6570cfee1d076811c8c2abb9e82c4834bc)).
> 
> maybe the identifier [here](https://github.com/mpv-player/mpv/blob/f8128f6570cfee1d076811c8c2abb9e82c4834bc/stream/stream_file.c#L175-L186) changed?
> 
> i will try to look into this further soon.

Happy to help.  I do have access to the samba server config, so if there are options that anyone here thinks would be beneficial to set, I'll be happy to do so.

**Comment by Akemi** [comment]
if possible, you can try to compile this simple sample program from this comment (https://github.com/mpv-player/mpv/issues/558#issuecomment-35195932), run it on the file on your mounted volume and tell me what it outputs.

**Comment by j9ac9k** [comment]
> if possible, you can try to compile this simple sample program from this comment ([#558 (comment)](https://github.com/mpv-player/mpv/issues/558#issuecomment-35195932)), run it on the file on your mounted volume and tell me what it outputs.

```
❯ ./statfs No\ Time\ to\ Die\ \(2021\).mp4
smbfs
```

**Comment by Akemi** [comment]
okay then it seems unrelated.

**Comment by kasper93** [comment]
Do you have cache enabled, how many seconds is cached when you pause? 
Could you test with `--no-config --cache=yes --cache-secs=1000 --demuxer-max-bytes=1GiB` and see if initial chunk of cache is loaded fast? Generally looks like connection is closed to smb. You can pause playback and observe how cache behave.

**Comment by j9ac9k** [comment]
I would still get speeds < 1 MB/s, usually between 300-550 KiB/s

```meson-build ❯ /usr/local/bin/mpv --no-config --cache=yes --cache-secs=1000 --demuxer-max-bytes=1GiB "/Volumes/videos/Reference/No Time to Die (2021).mp4"
● Video  --vid=1               (hevc 3832x1600 23.976 fps) [default]
● Audio  --aid=1  --alang=eng  (eac3 6ch 48000 Hz 768 kbps) [default]
● Subs   --sid=1  --slang=eng  (mov_text) [default]
○ Subs   --sid=2  --slang=eng  (mov_text) [default]
○ Subs   --sid=3  --slang=eng  (mov_text) [default]
○ Subs   --sid=4  --slang=spa  (mov_text) [default]
○ Subs   --sid=5  --slang=fra  (mov_text) [default]
○ Subs   --sid=6  --slang=kor  (mov_text) [default]
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [gpu] 3832x1596 yuv420p10
(Buffering) AV: 00:00:26 / 02:43:23 (0%) A-V:  0.000 Cache: 0.0s/192KB
Exiting... (Quit)
```

![image](https://github.com/user-attachments/assets/39ad1419-48cd-4540-981a-f9fbb6f56ddb)

(just realized I didn't save a log file, let me know if you'd like me to rerun with a log file as well).

**Comment by j9ac9k** [comment]
Just copied the same "No Time To Die" video to my local disk to test, and noticed that the cache speed was the speed that cache was being emptied, not the speed it was being filled 🤦🏻 (at least I think that's it?)  That explains a lot... but regardless, there was no buffering/caching getting in the way here:

```
/usr/local/bin/mpv --no-config --cache=yes --cache-secs=1000 --demuxer-max-bytes=1GiB "No Time to Die (2021).mp4"
```

![image](https://github.com/user-attachments/assets/92f570dd-d6b0-47dc-9d4e-30e6bf733984)

Going back to one of my reference videos on the samba share, it still pauses to buffer routinely, but when pausing the cache does fill up.

![image](https://github.com/user-attachments/assets/1bbc3cac-644e-4998-a0af-4d2bac5a1b7d)

**Comment by kasper93** [comment]
> Just copied the same "No Time To Die" video to my local disk to test, and noticed that the cache speed was the speed that cache was being emptied, not the speed it was being filled 🤦🏻 (at least I think that's it?)

It is the speed of loading the data, but when you fill the cache to the limit, the rate will be equal to the speed that the cache is emptied and new data is loaded. Essentially file bit rate speed.

> Initially the cache filled all the way up (like, instantly), and then the cache was slowly depleting during otherwise very smooth playback.

So the mpv can read the data fast. Also the 01:00 read-ahead value is an accident on your screen, I would expect it to be higher with the settings you tested. But maybe you made screenshot like that.

It is tricky to diagnose externally, because there are multiple factors, that can contribute to your issues. I don't think mpv is at fault specifically. Especially with higher cache sizes it should keep reading the data sequentially. And even if there are some hickups, it would have enough cached data to ramp up the transfer and recover.

I think macos, doesn't have strace? It would help to see how IO behaves.
Are you able to reproduce the issue on different OS?
Does rsync trasfer keep the speed all the way or it slows down?

Maybe mpv io loop is not that resilient to high latency, unreliable source, but I myself didn't see that problem before.

**Comment by kasper93** [comment]
> Is there a way I can have mpv report how fast the cache is being read in during the reading state?

This is the `Speed` value. But make sure cache size/duration is not limited, for raw read speed.

**Comment by j9ac9k** [comment]
After setting the `stream-buffer-size` to the largest possible value on my Windows machine, I'm getting file transfer speeds in line with what I would expect (14 MiB/s), I consider this issue to be resolved, I apologize for the noise, thanks for everyone's input here.

FWIW I won't be leaving the stream-buffer-size on the maximum value, but I'll keep dialing it up until things look good.

Thanks you all for making an amazing video player that can handle playing high quality streams halfway around the world!
