### ISSUE TITLE
Wish: Use "_NET_WM_DESKTOP" for "on-all-desktops"

### ISSUE THREAD

**Issue by olifre** [mpv-player/mpv#1469]
On most modern DEs on Linux, users have multiple desktops. For the "classic" watch-something-while-working situation, it is often useful to set "ontop" (already supported in mpv) and "on all desktops". 

This should work by setting _NET_WM_DESKTOP to 0xFFFFFFFF. 

As the x11_common code looks like some experience with x11 (+wayland, + windows, + more...) is needed to get this working in a good and clean way. As my dev-experience with x11 is next to nothing, I open this idea as a "wish" / Feature Request / idea. 

Of course, most DEs also offer window-property-based setting of such properties, so this is for sure not a pressing issue, but I believe it would be a useful extension.

**Comment by wm4** [comment]
The better DEs have user-visible menu entries or similar for this (as well as per-application profiles). At least IceWM does (it's old and barely maintained, but sucks less than modern WMs). There are also command line tools which can change NetWM properties. So I'm not sure if we should add an option for this.

On the other hand, we already have ontop and border options, so I'd not be terrible opposed to this.

**Comment by olifre** [comment]
> On the other hand, we already have ontop and border options, so I'd not be terrible opposed to this.

Thanks a lot, also for the quick implementation! I find this really helpful, especially when scripting something simple not having to rely on a well-configured WM (or xdotool being present) can be very useful. 

I found one issue: The `--on-all-workspaces` commandline parameter seems not to work, while setting the property after mpv is started works fine. 

I think that `vo_x11_config_vo_window` is missing a check for `opts->all_workspaces` to initially act on the value of the property (it also initially sets ontop for the window). 
But I am unsure whether `vo_x11_map_window` is the more correct place (which seems to be where noborder is initially set via the call to the x11_decoration function)...

**Comment by wm4** [comment]
Fixed.
