### ISSUE TITLE
A frozen screen appears when mpv plays for a long time

### ISSUE THREAD

**Issue by InnovatorSteve** [mpv-player/mpv#14694]
### mpv Information

```bash
mpv --version
mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
FFmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
FFmpeg version: 4.1.9-deepin6
```

### Other Information

- Linux version:PRETTY_NAME="UnionTech OS Desktop 20 Pro"
NAME="uos"
VERSION_CODENAME=eagle
- Kernel Version:Linux uos-Pl47y6feB6 4.19.0-amd64-desktop #5312 SMP Mon Nov 7 14:31:47 CST 2022 x86_64 GNU/Linux
- GPU Model:  NA
- Mesa/GPU Driver Version: OpenGL version string: 4.1
- Window Manager and Version: NA
- Source mpv: NA
- Introduced in version: screen freezes

### Reproduction Steps

The phenomena found so far:
When a video is played on the 28 VMS at the same time, the time of the phenomenon is almost the same
mpv log dmesg does not find any exception
The mpv freeze screen is closed and turned on again without exception
gdb attach mpv
Two decoder threads that should have existed were found not to exist

According to the existing phenomenon, it is suspected that the processing logic of mpv itself
Should the decoder thread not be destroyed even if there is any situation, and should there be a reminder even if it is destroyed

error:
![image](https://github.com/user-attachments/assets/b38ad9ce-bea6-45a3-9b99-1de00ef5c5b1)
normal:
![image](https://github.com/user-attachments/assets/29f485fc-d6b0-4c4c-8d5f-b7074d291f51)

I am currently using the soft solution to try to reproduce the problem, but I will not know the result until 12 hours later
I hope you can provide useful ideas or directions to help solve this problem

### Expected Behavior

Long-term playback is normal

### Actual Behavior

A frozen screen appears after a long period of playback (about 10h)

### Log File

[mpv_vm1.log](https://github.com/user-attachments/files/16657843/mpv_vm1.log)

### Sample Files

https://drive.google.com/file/d/1FHStaSBsI9-UFltSlTd1VoCF5kolhzCQ/view?usp=drive_link

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
> I hope you can provide useful ideas or directions to help solve this problem
First of all, compile mpv and ffmpeg with debug information, so we can see where thread 11/12 is waiting and for that matter backtrace of all threads can be insightful too. Also you can compile with UBSAN with unsigned overflow check enabled to see if something is not overflowing after some playback time.

Generally once you have mpv in frozen state, need to debug it and understand why it is not proceeding, narrow it down and we can start from that.

**Comment by CounterPillow** [comment]
> mpv 0.34.1 Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects

This is a 3 year out of date version. You should contact your distribution for support if you need help with it, too many things have changed since.

> [x] I tested with the latest mpv version to validate that the issue is not already fixed.

Don't check this option if you didn't do it.
