### ISSUE TITLE
since today youtube videos take 2 minutes to start with mpv+yt-dlp(nightly)

### ISSUE THREAD

**Issue by geextahslex** [mpv-player/mpv#14712]
### mpv Information

```bash
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Apr 20 2024 00:22:40
libplacebo version: v7.349.0 (v6.338.0-124-gd0eb997-dirty)
FFmpeg version: N-114897-gbba996d6c
FFmpeg library versions:
   libavutil       59.15.100
   libavcodec      61.5.103
   libavformat     61.3.100
   libswscale      8.2.100
   libavfilter     10.2.101
   libswresample   5.2.100
```

### Other Information

```text
Windows version: Windows 10 22H2 Build 19045.4170)
GPU model, driver and version: intel HD Graphics 4600, driver: 20.19.15.5171
Source of mpv: https://sourceforge.net/projects/mpv-player-windows/files/
Introduced in version: v38.0
yt-dlp: yt-dlp nightly 2024.08.19.232821
```

### Reproduction Steps

try to play youtube video with mpv+latest yt-dlp (nightly), for example: `mpv "https://www.youtube.com/watch?v=xmJUZgQ5HpQ"`
wait until video starts, see how long it takes to start playback

### Expected Behavior

video starts playback after 5-7seconds as before

### Actual Behavior

you have to wait about 2 minutes (1:50) to start the youtube video

### Log File

gpu debug
[output.txt](https://github.com/user-attachments/files/16675528/output.txt)
normal logfile
[output.txt](https://github.com/user-attachments/files/16675568/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by CounterPillow** [comment]
```
[   1.286][d][cplayer] Run command: subprocess, flags=64, args=[args="yt-dlp,--no-warnings,-J,--flat-playlist,--sub-format,ass/srt/best,--format,bestvideo+bestaudio/best,--all-subs,--no-playlist,--,https://www.youtube.com/watch?v=xmJUZgQ5HpQ", playback_only="yes", capture_size="67108864", capture_stdout="yes", capture_stderr="yes", detach="no", env="", stdin_data="", passthrough_stdin="no"]
[ 105.265][v][ytdl_hook] Found youtube-dl with path yt-dlp in PATH
[ 105.269][v][ytdl_hook] youtube-dl succeeded!
[ 105.269][d][ytdl_hook] ytdl parsing took 103.984 seconds
```

According to https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua#L964-L972 the message "Found youtube-dl with path yt-dlp in PATH" is printed after yt-dlp is executed, which means that in between mpv running the subprocess command ("exec" here) and it returning is the 104 second pause which would be within yt-dlp.

In other words, most likely not an mpv issue. Try running `yt-dlp.exe --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --all-subs --no-playlist --verbose -- https://www.youtube.com/watch?v=xmJUZgQ5HpQ` from a console and see if it also takes that long to complete. If so, it's not an mpv issue.

**Comment by geextahslex** [comment]
True story, it took also that long

**Comment by kasper93** [comment]
Closing this, because it is completely unrelated to mpv or its modules, we cannot help here.
