### ISSUE TITLE
static mpv build not working with luasocket

### ISSUE THREAD

**Issue by syehoonkim** [mpv-player/mpv#14726]
### mpv Information

```bash
mpv v0.38.0-717-g92f052c14e-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 23 2024 16:59:34
libplacebo version: v7.349.0
FFmpeg version: 44b8ea4
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

```text
- Windows version:10.0.19045.4780
- GPU model, driver and version: NVIDIA RTX A4000
- Source of mpv: this repo
- Introduced in version: my own build with Windows Clang and official prebuilt binary
```

### Reproduction Steps

Use luasocket like `local socket = require("socket.core")` with [lua51.zip](https://github.com/user-attachments/files/16725932/lua51.zip) by static mpv builds.
mpv with shared libs by msys2 works fine.

### Expected Behavior

luasocket should work fine

### Actual Behavior

mpv(.com) dies without any error message.

### Log File

[output.txt](https://github.com/user-attachments/files/16725967/output.txt)
sendust_trim.lua includese luasocket

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
External modules doesn't work with statically linked lua on Windows. External modules (`bla.dll`) are linked to lua shared library (`lua51.dll`), which must be present and the same as main program uses. Which is obviously not true when static linking. Use `-Dluajit:default_library=shared` to fix your issue.

**Comment by syehoonkim** [comment]
Thank you for your explanation!!
