### ISSUE TITLE
Pad 0:v is not connected to anything

### ISSUE THREAD

**Issue by cpiette95** [mpv-player/mpv#14761]
### mpv Information

```bash
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Nov 30 2023 14:35:43
libplacebo version: v6.338.1
FFmpeg version: 5.1.4
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
```

### Other Information

```text
- macOS version:14.5
```

### Reproduction Steps

I used this command line: 

./mpv --lavfi-complex="[0:v]scale=iw/2:ih/2[v0];[1:v]scale=iw/2:ih/2[v1];[v0][v1]hstack=inputs=2" video1.mp4 video2.mp4

### Expected Behavior

I was expecting the two videos to play simultaneously 

### Actual Behavior

I got the error "Pad 0:v is not connected to anything". Any thought about this? 

### Log File

...

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
Videos tracks are `[vid1]` and `[vid2]` not `[0:v]`.
