### ISSUE TITLE
Some files no longer playing with video

### ISSUE THREAD

**Issue by IzanagisBurden** [mpv-player/mpv#14764]
### mpv Information

```bash
mpv v0.38.0-727-g938938a9 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 27 2024 00:15:23
libplacebo version: v7.349.0 (v7.349.0-5-g82bf46a-dirty)
FFmpeg version: N-116778-g7e4784e40
FFmpeg library versions:
   libavcodec      61.11.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.34.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Important Information

```text
- Platform version: Windows 11
- GPU model, driver and version: GTX 1080ti, 552.22
- Source: shinchiro builds
- Introduced in version: mpv-x86_64-v3-20240623-git-265056f
```

### Reproduction Steps

Some older files that I have are no longer playing with video in the latest builds of mpv. These files used to play just fine on `mpv-x86_64-v3-20240609-git-d2bd77a` and older. Since `mpv-x86_64-v3-20240623-git-265056f`, there is no longer any video and the mpv window takes a while to show up. Unsure if related, but the files I have tested that no longer play are some Profile 5 DV mkv files. The log and console output both show a lot of `[ffmpeg/video] hevc: Error parsing NAL unit #1`.

### Expected Behavior

mpv to play the file with video like it used to.

### Actual Behavior

mpv takes a while to show the display window, and then only plays with audio and a black screen.

### Log File

[logfile.txt](https://github.com/user-attachments/files/16808973/logfile.txt)

### Sample Files

https://0x0.st/XvAb.mkv (100MB DV P5 test that no longer shows video past that build stated above)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Caused by https://github.com/FFmpeg/FFmpeg/commit/90fc331b0fc6f7d9c31f9e6d543102ba7fe02daf
