### ISSUE TITLE
A colour stripe on the left side of the screen.

### ISSUE THREAD

**Issue by paprykut** [mpv-player/mpv#1476]
Specs: Freshly updated Arch Linux, mpv latest git version, catalyst 14.12.

Issue: When I switch a video to a full screen mode, a left part of the screen - approx. 2-3 milimeters, does not correspond to a movie. In fact, it is a stale stripe of a different colour each time. The end result looks like the whole video has been shifted by 2-3mm into the right. There is no stripe like that when the video is started in fullscren from the beginning, however, if it is windowed and made into a full screen again, the stripe will appear.

**Comment by wm4** [comment]
Most likely an issue with the graphics driver, or, less likely, with the window manager.

Maybe you can confirm with xwininfo that the fullscreen window is correctly positioned.

**Comment by paprykut** [comment]
I have checked it with xwininfo and everything is fine. Perhaps, as I initially thought, this would be catalyst issue. Nonetheless, I have tried different versions and none worked.
