### ISSUE TITLE
hidpi-window-scale=no is ignored in plasma wayland

### ISSUE THREAD

**Issue by paulguy** [mpv-player/mpv#14779]
### mpv Information

```bash
mpv v0.38.0-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul  3 2024 05:59:22
libplacebo version: v7.349.0
FFmpeg version: n7.0.2
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Other Information

```text
- Linux version: Arch Linux
- Kernel Version: 6.10.7-arch1-1
- GPU Model: AMD Radeon RX 580
- Mesa/GPU Driver Version: Mesa 24.2.1-arch1.1
- Window Manager and Version: plasma kwin (wayland) 6.1.4-1
- Source mpv: pacman
- Introduced in version: no idea
```

### Reproduction Steps

Play any video:
mpv --no-config --log-file=log.txt <filaname>
or
mpv --no-config --hidpi-window-scale=no --log-file=log.txt <filaname>

### Expected Behavior

Video window displays at 1x video size.

### Actual Behavior

Video displays at window manager configured DPI scale.

### Log File

[log.txt](https://github.com/user-attachments/files/16830753/log.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by paulguy** [comment]
Temporary workaround, add:
Ctrl+S set autofit ${video-params/dw}x${video-params/dh}
to input.conf and just press CTRL+SHIFT+S when the video comes up.

**Comment by llyyr** [comment]
Can't reproduce on sway or weston

**Comment by paulguy** [comment]
In the log it looks like it's getting the event from the WM that it entered a display with a new DPI and just acting on it.  I'd guess just when the window is created it's entered a "new" display?  Maybe this is different from other WMs.

**Comment by paulguy** [comment]
Seems to no longer be a problem since updating to plasma 6.2?  No idea what the nature of the issue was then.
