### ISSUE TITLE
sub-back-color no longer works after updating to mpv-x86_64-20240901-git-7c672e3.7z

### ISSUE THREAD

**Issue by hengyu95** [mpv-player/mpv#14777]
### mpv Information

```bash
mpv v0.38.0-730-g7c672e33 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Aug 31 2024 00:15:54
libplacebo version: v7.349.0 (v7.349.0-9-gefb8934-dirty)
FFmpeg version: N-116820-g8a2c40162
FFmpeg library versions:
   libavcodec      61.11.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.35.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

```text
- Windows version: Microsoft Windows [Version 10.0.22631.4037]
- GPU model, driver and version: RTX 4090
- Source of mpv:  https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20240901-git-7c672e3.7z/download
```

### Reproduction Steps

Even doing mpv --no-config --sub-back-color=#AAAAAA <file> it doesn't work

### Expected Behavior

Before I upgraded setting this option gives me a colored border behind the subtitles (like YouTube CC does)

### Actual Behavior

Nothing happens regardless of how that setting is set now

### Log File

[output.txt](https://github.com/user-attachments/files/16829848/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
https://mpv.io/manual/master/#options-sub-border-style

Set `--sub-border-style=background-box`

**Comment by hengyu95** [comment]
Thanks, I'll give that a try when I get the chance. Is that a new option? I
update quite regularly and have not touched my config in a long time

**Comment by kasper93** [comment]
There were changes recently, see:
https://github.com/mpv-player/mpv/pull/14195 and [interface-changes/sub-border-style.txt](https://github.com/mpv-player/mpv/blob/afdbbac81d3082254b8fe2ae230b161ddc478380/DOCS/interface-changes/sub-border-style)

**Comment by hengyu95** [comment]
Works perfectly, thanks
