### ISSUE TITLE
~2 pixel wide transparent line at the bottom of a fullscreen window when not focused

### ISSUE THREAD

**Issue by CrashTD** [mpv-player/mpv#14773]
### mpv Information

```bash
mpv v0.38.0-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul  3 2024 05:59:22
libplacebo version: v7.349.0
FFmpeg version: n7.0.2
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Other Information

```text
- Linux version: EndeavourOS
- Kernel Version: 6.10.7-arch1-1
- GPU Model: AMD RX 7800 XT
- Mesa/GPU Driver Version: 24.2.1-arch1.1
- Window Manager and Version: KDE 6.4.1 (Wayland)
- Source mpv: Arch Repos
- Introduced in version: unknown
```

### Reproduction Steps

Play any video at fullscreen then click on a different window (on a secondary monitor) so mpv loses focus.

### Expected Behavior

Fullscreen without distracting line on the bottom 

### Actual Behavior

a ~2 pixel wide line becomes visible at the bottom where you can see part of what is behind the window (e.g. the KDE taskbar).

![grafik](https://github.com/user-attachments/assets/0ac40e54-127d-4377-a14e-20076bcb6aa2)

### Log File

[output.txt](https://github.com/user-attachments/files/16825796/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Does it happen on all three of your displays? I can't imagine how this isn't a KDE bug or a bug with your theme, mpv is drawing the same size windows as your displays

**Comment by CrashTD** [comment]
No it happens only on the middle (AOC) one. and i just noticed it happens only on highest resolution of 2560x1440 and only if KDE scaling is activated (in my case 135% to match the other displays)

it could be of course caused by KDE / wayland and a problem with the scaling algorithm or something like that. however, mpv is the only application showing this problem. it does not happen with e.g. VLC or any other fullscreen application i tested so far.

**Comment by llyyr** [comment]
Could you try with mpv built from master?

**Comment by CrashTD** [comment]
I did already yesterday. still on 0.38.0_730_g7c672e33a5-1. same behaviour.

i keep testing around a bit.

**Comment by paulguy** [comment]
Not to say that in this case it's definitely a KDE problem but but at 150% scale on X11 I get the occasional misaligned strip of pixels between a window and its edge.

**Comment by CrashTD** [comment]
Not sure when exactly it was fixed, but problem does not longer shows up in v0.39.0-24-g53f2619dbd.
