### ISSUE TITLE
text version of `overlay_add` input command

### ISSUE THREAD

**Issue by mozbugbox** [mpv-player/mpv#1477]
`show_text` does not has the flexibility to put the text over different places of the screen, e.g. the 4 corners. Therefore the show_text will interfere with the builtin OSD information.

With a `overlay_add_text` like call, we can provide some more OS system message updates while in the _fullscreen mode_, by using lua script.

**Comment by wm4** [comment]
There's already a way to make show_text interpret ASS formatting tags: http://mpv.io/manual/master/#command-interface-osd-ass-cc
Here's a reference for ASS tags: http://docs.aegisub.org/3.2/ASS_Tags/
You want ``\an`` or ``\pos``.
I'm not sure if we should/have to provide something additional to this.

**Comment by wm4** [comment]
Also I had to update the website, because the escapes were mangled.

**Comment by mozbugbox** [comment]
Thank. I did not awared that `show_text` can take ASS tags.

There were some issues I cannot figure out in my test:
* When `show_text` showed text, the builtin OSD message was turned off. e.g. at osd level 3, the playtime/duration info show on the top-left disappared during `show_text`. I'd like to see show_text not interfere with other builtin OSD info.
* I'd like to have a way to always show the text without a timeout.
* The ASS \pos(x,y) coordinate is wrong for me when I tried to put some text on bottom-right corner:

    `show_text "${osd-ass-cc/0}{\\an3}{\\pos(${dwidth},${dheight})}23:20" 10000 3`

    and the text run off the screen. If I put \\pos(100,100), I can see the text shown somewhere over the video.

**Comment by wm4** [comment]
You can *probably* use ``osc-message`` to make OSD and your own message coexist.

``\pos`` is a bit messy in this context; it probably uses some virtual resolution (like 720 vertical, and whatever fits the aspect horizontal). I have no idea how we could provide this cleanly. In any case, you don't need ``\pos``, for merely placing text in some corner, use ``\an``.

**Comment by wm4** [comment]
Maybe this can make some progress once we figure out how it should work.

**Comment by Dudemanguy** [comment]
Ancient issue but I believe this was solved by `osd-overlay` years ago.
