### ISSUE TITLE
Playing "Bad Apple!! PV" with libsixel

### ISSUE THREAD

**Issue by RealYukiSan** [mpv-player/mpv#14785]
### mpv Information

```bash
[hemlo@ASUS ~]$  mpv --version
mpv v0.38.0-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jul  3 2024 05:59:22
libplacebo version: v7.349.0
FFmpeg version: n7.0.2
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Other Information

```text
- Linux version: `Arch Linux`
- Kernel Version: `6.10.6-arch1-1`
- GPU Model: AMD Phoenix1 and NVIDIA AD106M
- Mesa/GPU Driver Version: `4.6 (Compatibility Profile) Mesa 24.1.6-arch1.1`
- Window Manager and Version: latest DWM
- Source mpv: Arch Linux repository
- Introduced in version: current used version
- Related link: Github's comment (https://github.com/mpv-player/mpv/issues/2183#issuecomment-737323328)
- xrandr information:

$ xrandr --listmonitors --listproviders
Providers: number : 2
Provider 0: id: 0x5b cap: 0xf, Source Output, Sink Output, Source Offload, Sink Offload crtcs: 4 outputs: 9 associated providers: 1 name:AMD Radeon 780M @ pci:0000:66:00.0
Provider 1: id: 0x1fd cap: 0x2, Sink Output crtcs: 4 outputs: 4 associated providers: 1 name:NVIDIA-G0
Monitors: 1
 0: +HDMI-1-0 1920/480x1080/270+0+0  HDMI-1-0
```

### Reproduction Steps

1. boot into linux
2. start dwm within Xorg server with `startx`
3. open `st -e tmux` terminal
4. disable the main/primary monitor and switch to external monitor that are connected through HDMI cable with `xrandr`
5. start mpv with `mpv --vo=sixel --no-config --gpu-debug --log-file=/tmp/output.txt ~/Music/bad_apple_pv.mp4`

### Expected Behavior

The video playing properly

### Actual Behavior

It only print `+` on the entire screen as screenshot below:
![image](https://github.com/user-attachments/assets/9671dfdb-4608-414b-96d4-1dc5693055ac)

### Log File

[output.txt](https://github.com/user-attachments/files/16843015/output.txt)

### Sample Files

I download the video from [youtube](https://www.youtube.com/watch?v=FtutLA63Cp8)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
tmux only supports sixel from 3.4 or newer, and it needs to be manually enabled during compile time. Can you try without tmux?

**Comment by RealYukiSan** [comment]
without tmux:
![image](https://github.com/user-attachments/assets/dfdae4e3-76f1-44b6-98bf-a9ed9d141a54)

**Comment by llyyr** [comment]
Actually I don't think st supports sixel either without a patch, are you using a patch? Can you try with another sixel player or another terminal that does support sixel?

**Comment by RealYukiSan** [comment]
> Actually I don't think st supports sixel either without a patch, are you using a patch?
No, I use a default st without modification.

> Can you try with another sixel player or another terminal that does support sixel?
Alright, I will try installing another terminal and give a feedback

**Comment by RealYukiSan** [comment]
Wait, do you have any recommendation for terminal app that support sixel out of the box?

**Comment by llyyr** [comment]
> EDIT: nvm, I will try alacritty first

https://github.com/alacritty/alacritty/issues/910 It doesn't support sixel. You can probably try kitty.

**Comment by RealYukiSan** [comment]
Thanks for the awesome resources! the `st` patch provided on the site actually worked with some limitations described in the gist

as a note:
I must lower the st version to apply the patch without any conflict

closing the issue as this is not related to MPV player

**Comment by barracuda156** [comment]
mlterm should support sixel.
