### ISSUE TITLE
Some .m3u8 can't be played

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#14781]
### mpv Information

Hello everyone!
Since the issue was previously closed so I'm reopening it and offering a solution that works:
https://github.com/mpv-player/mpv/issues/14550

logs 

```
 mpv --referrer='https://cdn3.turboviplay.com' 'https://cdn3.turboviplay.com/data1/H7LK7v5MU8SV1LIB5oAF/H7LK7v5MU8SV1LIB5oAF480.m3u8'
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
● Video  --vid=1  (png)
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] ...treating it as fatal error.
(Paused) V: 01:55:41 / 01:55:41 (100%) Cache: 0.0s
```

The key solution to fix the issue is as follows:
demux: adaptive: skip PNG junk when probing

### Other Information

text
Hello everyone!
Since the issue was previously closed so I'm reopening it and offering a solution that works:
https://github.com/mpv-player/mpv/issues/14550

logs 

```
 mpv --referrer='https://cdn3.turboviplay.com' 'https://cdn3.turboviplay.com/data1/H7LK7v5MU8SV1LIB5oAF/H7LK7v5MU8SV1LIB5oAF480.m3u8'
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
● Video  --vid=1  (png)
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] ...treating it as fatal error.
(Paused) V: 01:55:41 / 01:55:41 (100%) Cache: 0.0s
```

The key solution to fix the issue is as follows:
demux: adaptive: skip PNG junk when probing

### Reproduction Steps

Hello everyone!
Since the issue was previously closed so I'm reopening it and offering a solution that works:
https://github.com/mpv-player/mpv/issues/14550

logs 
```
 mpv --referrer='https://cdn3.turboviplay.com' 'https://cdn3.turboviplay.com/data1/H7LK7v5MU8SV1LIB5oAF/H7LK7v5MU8SV1LIB5oAF480.m3u8'
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
● Video  --vid=1  (png)
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] ...treating it as fatal error.
(Paused) V: 01:55:41 / 01:55:41 (100%) Cache: 0.0s
```
The key solution to fix the issue is as follows:
demux: adaptive: skip PNG junk when probing

### Expected Behavior

Hello everyone!
Since the issue was previously closed so I'm reopening it and offering a solution that works:
https://github.com/mpv-player/mpv/issues/14550

logs 
```
 mpv --referrer='https://cdn3.turboviplay.com' 'https://cdn3.turboviplay.com/data1/H7LK7v5MU8SV1LIB5oAF/H7LK7v5MU8SV1LIB5oAF480.m3u8'
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
● Video  --vid=1  (png)
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] ...treating it as fatal error.
(Paused) V: 01:55:41 / 01:55:41 (100%) Cache: 0.0s
```
The key solution to fix the issue is as follows:
demux: adaptive: skip PNG junk when probing

### Actual Behavior

Hello everyone!
Since the issue was previously closed so I'm reopening it and offering a solution that works:
https://github.com/mpv-player/mpv/issues/14550

logs 
```
 mpv --referrer='https://cdn3.turboviplay.com' 'https://cdn3.turboviplay.com/data1/H7LK7v5MU8SV1LIB5oAF/H7LK7v5MU8SV1LIB5oAF480.m3u8'
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
● Video  --vid=1  (png)
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] ...treating it as fatal error.
(Paused) V: 01:55:41 / 01:55:41 (100%) Cache: 0.0s
```
The key solution to fix the issue is as follows:
demux: adaptive: skip PNG junk when probing

### Log File

Hello everyone!
Since the issue was previously closed so I'm reopening it and offering a solution that works:
https://github.com/mpv-player/mpv/issues/14550

logs 
```
 mpv --referrer='https://cdn3.turboviplay.com' 'https://cdn3.turboviplay.com/data1/H7LK7v5MU8SV1LIB5oAF/H7LK7v5MU8SV1LIB5oAF480.m3u8'
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
● Video  --vid=1  (png)
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] ...treating it as fatal error.
(Paused) V: 01:55:41 / 01:55:41 (100%) Cache: 0.0s
```
The key solution to fix the issue is as follows:
demux: adaptive: skip PNG junk when probing

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
This is the third ticket you've opened for the same issue (#13978, #14550). What makes you think being annoying will make it more likely for people to fix your garbled HLS streams that don't follow specs?

This is already tracked at #11365

**Comment by kasper93** [comment]
> This is already tracked at https://github.com/mpv-player/mpv/issues/11365

**Comment by zhouxinghong** [comment]
[ffmpeg/demuxer] hls: Could not find codec parameters for stream 0 (Video: png, none): unspecified size
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
● Video  --vid=1  (png)
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] error reading packet: Invalid argument.
[lavf] ...treating it as fatal error.
(Paused) V: 01:55:41 / 01:55:41 (100%) Cache: 0.0s

Latest test link:

```
referrer=https://ryderjet.com/v/bcdzydcnzgat
https://ryderjet.com/stream/1MUALAaJW7QfSBMLLJq2GA/hjkrhuihghfvu/1779879689/39856499/index-v1-a1.m3u8
```
