### ISSUE TITLE
`deinterlace` fails with `hwdec` for `mpeg2video`

### ISSUE THREAD

**Issue by jiangzhenjerry** [mpv-player/mpv#14816]
### mpv Information

```bash
mpv v0.38.0-747-g0eb5e914 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep  6 2024 12:13:04
libplacebo version: v7.349.0 (v7.349.0-9-gefb8934-dirty)
FFmpeg version: N-116911-gc0666d8be
FFmpeg library versions:
   libavcodec      61.12.100
   libavdevice     61.2.100
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.36.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

```text
- Windows version: Windows 11 [10.0.27695.1000]
- GPU model, driver and version: Intel(R) Arc(TM) Graphics, Driver Version 32.0.101.5972
- Source of mpv: https://github.com/zhongfly/mpv-winbuild/releases
- Introduced in version: Not sure, but must be somewhere between `mpv-x86_64-v3-20240703-git-7c70df0.7z` (a working version from my backup) and present.
```

### Reproduction Steps

Attached later in this issue is `1.mkv`, which is a short `mpeg2video` remuxed directly from a DVD I own.

1. Use vanilla mpv without any `mpv.conf`
2. Run `mpv --deinterlace 1.mkv`. This correctly deinterlaces the video.
3. Run `mpv --deinterlace --hwdec --hwdec-codecs=all 1.mkv`. This fails to deinterlace the video.

### Expected Behavior

In Step 3 above, the video should be deinterlaced.

### Actual Behavior

In Step 3 above, the video is not deinterlaced.

### Log File

[output.txt](https://github.com/user-attachments/files/16921621/output.txt)

### Sample Files

[1.mkv.zip](https://github.com/user-attachments/files/16921624/1.mkv.zip)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by hooke007** [comment]
It's a cpu filter. Use `hwdec=auto-copy` instead.

**Comment by hooke007** [comment]
Or use d3d11vpp's deint with `d3d11va` hwdec

https://mpv.io/manual/master/#video-filters-d3d11vpp

**Comment by jiangzhenjerry** [comment]
@hooke007 Thanks for the notes. These methods work, but I'd prefer the direct decoding mode and the possibility to use `deinterlace=auto`.

**An additional finding:** I grabbed `mpv-x86_64-v3-20240703-git-7c70df0.7z` from my recent backup (which is also from zhongfly but no longer available for download), and that version works just fine. Apparently, something must have changed from July 3 to present. I edited my bug report to reflect this finding.

**Comment by sfan5** [comment]
this should in fact work automatically: https://github.com/mpv-player/mpv/blob/e169302e2de40408e4aaf5f4f74a038489765d12/filters/f_auto_filters.c#L95-L98

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/commit/67e087dcae35fa9f74a6dced588629fcdf075182 safe
https://github.com/mpv-player/mpv/commit/f44c29b223d7f0187ccf938eb1651671c8e92cf3 broken

**Comment by kasper93** [comment]
@hooke007 @jiangzhenjerry does #14822 work for you?

**Comment by jiangzhenjerry** [comment]
@kasper93 Thank you, it works for me.
