### ISSUE TITLE
Fails to load and play playlists above 10mb size

### ISSUE THREAD

**Issue by masterofobzene** [mpv-player/mpv#14823]
### mpv Information

```bash
I have huge playlists that can take up to 10mb in size (m3u).

MPV cannot play these playlists but smaller ones are played normally (up to 8 mb tested, could be more).
```

### Other Information

```text
.
```

### Reproduction Steps

.

### Expected Behavior

.

### Actual Behavior

.

### Log File

.

### Sample Files

.

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Dudemanguy** [comment]
Quickly generated a 20+ MiB m3u. It took a long time to open and is obviously slow since mpv is adding over 600,000 playlist entries internally but it worked fine.
