### ISSUE TITLE
Long lists shortened on OSD

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#1482]
Long lists shown on OSD tend to be cut short over a certain amount of rows (depending on the OSD font size). This happens e.g. with playlists or chapters' lists (here a case with a DVD rip http://a.pomf.se/dlwjmm.png): if there is no space to show the remaining elements, they simply slip under the bottom edge and they're essentially unreadable. 

One possible solution could be to force the OSD to show a certain amount of elements after the currently highlighted one (this way the unreadable elements would be on the upper side, presumably watched/listened ones instead of further tracks/chapters), but I don't know the amount of work it could actually require.

**Comment by wm4** [comment]
The basic problem is that we don't know how large the text is. We don't even know whether a certain element is completely out of the screen.

**Comment by ChrisK2** [comment]
if you use the OSC buttons for those lists (shift+click on the corresponding button), then longer lists will be drawn at smaller font size to fit some more rows on screen, but this also purely works on guessing, so it doesn't make all cases work.

**Comment by lachs0r** [comment]
Seems to be fixed with recent OSC changes.

**Comment by AirPort** [comment]
Strictly speaking the issue is not exactly solved, the OSD is still not aware of window borders, and if a list is too long it will be cut short exactly like before.
But yes, with the recent introduction of the `osc-playlist`, `osc-chapterlist` and `osc-tracklist` handlers I remapped the respective keybinds and the use case I presented in the first comment is basically gone, and since I suppose it is the most relevant one, the issue can probably be closed.
