### ISSUE TITLE
dolby AC4

### ISSUE THREAD

**Issue by ZTKSUB** [mpv-player/mpv#14826]
### Expected behavior of the wanted feature

如果可以的话,希望能加入dolbyAC4音频的解码,我用dubi杜比编码器编码出来这个AC4格式,但是我不想用杜比播放器去解码(Dolby Reference Player),因为他的UI并不是很好用
![QQ截图20240910001457](https://github.com/user-attachments/assets/02f6e260-56bc-473b-ad18-726005c9cb42)

### Sample Files

[https://1drv.ms/u/s!Ailok2smyamNa0KptHPsQtaW59g?e=MbQ7gI](url)

**Comment by ZTKSUB** [comment]
> 如果你用一些 ffmpeg fork 和 AC4 解码器构建 mpv，你可以得到 AC4，这取决于构建器。对于 shinchiro 构建，我们只考虑官方的 ffmpeg。

那,ffmpeg官方有没有开始支持AC4?

**Comment by kasper93** [comment]
https://trac.ffmpeg.org/ticket/8349
