### ISSUE TITLE
libmpv win32: 3 handles leak from registry query

### ISSUE THREAD

**Issue by wbtcpip2** [mpv-player/mpv#14835]
### mpv Information

```bash
[ 595.357][v][cplayer] mpv v0.38.0-601-gf470b63a Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
[ 595.357][v][cplayer]  built on Jul 12 2024 00:08:04
[ 595.357][v][cplayer] libplacebo version: v7.349.0 (v7.349.0-dirty)
[ 595.357][v][cplayer] FFmpeg version: N-116241-g70c6b904b
[ 595.357][v][cplayer] FFmpeg library versions:
[ 595.357][v][cplayer]    libavcodec      61.10.100
[ 595.357][v][cplayer]    libavdevice     61.2.100
[ 595.357][v][cplayer]    libavfilter     10.2.102
[ 595.357][v][cplayer]    libavformat     61.5.101
[ 595.357][v][cplayer]    libavutil       59.28.100
[ 595.357][v][cplayer]    libswresample   5.2.100
[ 595.357][v][cplayer]    libswscale      8.2.100
[ 595.358][v][cplayer] 
[ 595.358][v][cplayer] Configuration: -Ddebug=true -Db_ndebug=true -Doptimization=3 -Db_lto=true -Db_lto_mode=thin -Dlibmpv=true -Dpdf-build=enabled -Dlua=enabled -Djavascript=enabled -Dsdl2=enabled -Dlibarchive=enabled -Dlibbluray=enabled -Ddvdnav=enabled -Duchardet=enabled -Drubberband=enabled -Dlcms2=enabled -Dopenal=enabled -Dspirv-cross=enabled -Dvulkan=enabled -Dvapoursynth=enabled -Degl-angle=enabled -Dc_args=-Wno-error=int-conversion -Dprefix=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build_i686/i686-w64-mingw32 -Dlibdir=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build_i686/i686-w64-mingw32/lib -Ddefault_library=shared -Dprefer_static=True --cross-file=/__w/mpv-winbuild-cmake/mpv-winbuild-cmake/build_i686/meson_cross.txt
[ 595.358][v][cplayer] List of enabled features: build-date cplugins cuda-hwaccel cuda-interop d3d-hwaccel d3d11 d3d9-hwaccel debug direct3d dos-paths dvdnav dxgi-debug dxgi-debug-d3d11 egl-angle egl-angle-win32 ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gpl iconv javascript jpeg lcms2 libarchive libass libavdevice libbluray libplacebo luajit openal pathcch rubberband rubberband-3 sdl2 sdl2-audio sdl2-gamepad sdl2-video shaderc spirv-cross uchardet vaapi vaapi-win32 vapoursynth vector vulkan vulkan-interop wasapi win32 win32-desktop win32-executable win32-threads zimg zimg-st428 zlib
[ 595.358][v][cplayer] Built with NDEBUG.
```

### Other Information

```text
- Windows version: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
- GPU model, driver and version: NVIDIA GeForce GTX 1650 - 31.0.15.5186
- Source of mpv: https://github.com/wbtcpip2/mpv-winbuild/releases
- Introduced in version: don't know but i think it's a longtime
```

### Reproduction Steps

call:
mpv_create
mpv_initialize
MPVCommand(mpvhandle, "loadfile", videofile)
wait and
mpv_destroy

now repeat

with each new mpv instance 3 registry query are opened and never closed
Key	HKLM\SYSTEM\ControlSet001\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}	0x00000F90	0x00000001	0xFFFF88000849A610			QUERY_VALUE

the key content is here: 
[10318.zip](https://github.com/user-attachments/files/16969812/10318.zip)

the queries appears to be related to the monitor configurtaion

### Expected Behavior

the 3 reg query to be close at mpv_destroy

### Actual Behavior

the 3 reg query are not close and the handles count continue to growth 3 handles for each mpv instance.
take a look at procexp at the start of my test application:
[MPVDEBUG1.Exe.txt](https://github.com/user-attachments/files/16969849/MPVDEBUG1.Exe.txt)

and look some time later
[MPVDEBUG2.Exe.txt](https://github.com/user-attachments/files/16969856/MPVDEBUG2.Exe.txt)

dozens of query to
Key	HKLM\SYSTEM\ControlSet001\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}	0x00000484	0x00000001	0xFFFF880007513AA0			QUERY_VALUE
are leaked

is mpv quering that reg key?

i'm not sure but it seems to happen on many windows 10 systems (at least on NVIDIA GPU systems), but until now i never saw the problem on windows 11 systems

### Log File

here is the trace log from an instance of libmpv
[9040087.txt](https://github.com/user-attachments/files/16969865/9040087.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by wbtcpip2** [comment]
i can now confirm this issue only happens in windows 10 (now seen on 8 different computers with nvidia or intel gpu) 

even in my own computer if i boot win11 no problems if i boot win10 leaks

no problems with vlc on both win10 and win11

**Comment by wbtcpip2** [comment]
[  91.701][v][vo/gpu/d3d11] Queried output: \\.\DISPLAY6, 1600x900 @ 8 bits, colorspace: RGB_FULL_G22_NONE_P709 (0)

could it be this query ? it query the registry?

**Comment by kasper93** [comment]
https://learn.microsoft.com/en-us/troubleshoot/windows/win32/geticmprofile-might-leak-one-or-more-handles-on-windows10

> Microsoft has confirmed that this is a problem in the products that are listed in the "Applies to" section.
> 
> This problem is fixed in Windows 11.

Nothing we can do about it. Everything is correct on mpv side.

The leaked handle is this:
```
...
mpv.exe!update_display_info
gdi32full.dll!GetICMProfileW
gdi32full.dll!IcmUpdateLocalDCColorSpace
gdi32full.dll!GetDefaultDestinationProfile
gdi32full.dll!IcmEnumColorProfile
mscms.dll!EnumColorProfilesW
mscms.dll!InternalEnumColorProfiles
mscms.dll!GetAssociatedProfileList
mscms.dll!GetDeviceDataSize
mscms.dll!IGetDeviceDataSize
mscms.dll!OpenDisplay
KernelBase.dll!RegCreateKeyExW
KernelBase.dll!RegCreateKeyExInternalW
KernelBase.dll!LocalBaseRegCreateKey
KernelBase.dll!Wow64NtCreateKey
ntdll.dll!NtCreateKey
ntoskrnl.exe!KiSystemServiceCopyEnd
ntoskrnl.exe!NtCreateKey
ntoskrnl.exe!CmCreateKey
ntoskrnl.exe!ObOpenObjectByName
ntoskrnl.exe!ObOpenObjectByNameEx
ntoskrnl.exe!ObpCreateHandle
```
