### ISSUE TITLE
osd-border-size conflict

### ISSUE THREAD

**Issue by unknown--** [mpv-player/mpv#1484]
When altering 'osd-border-size' it seems to affect both the border of the osd-bar and the outline of the OSD text.

Would it not be better to have a separate option to increase the stroke/outline on the OSD text so that the osd-bar goes unaffected?

**Comment by wm4** [comment]
Maybe, though I'm a bit worried about the growth in the number of options.

**Comment by felagund** [comment]
Hm, what about adjusting the outline to text size? I just lowered the text size of OSD and the outline started to be too large (and so ugly), that is how I found this. osd-border-size does the trick for me, but it if adjusted automatically, that would have been even more awesome.

Not sure what the OSD bar is tough, the outline of the volume icon when I horizontal-scroll on my touchpad and change volume?
