### ISSUE TITLE
 Option to toggle hardware media keys overlay on Windows

### ISSUE THREAD

**Issue by vlnka** [mpv-player/mpv#14857]
### Expected behavior of the wanted feature

Toggle hardware media key overlay on Windows when changing system volume while MPV is playing media.

Similar to `#hardware-media-key-handling` flag in Chromium or `media.hardwaremediakeys.enabled` option in Firefox.

### Sample Files

This is what the overlay looks like - right of the volume slider:
![image](https://github.com/user-attachments/assets/2e940106-89d3-4ab7-b22c-0bb17614d558)

**Comment by kasper93** [comment]
`[--media-controls=<yes|player|no>](https://mpv.io/manual/master/#options-media-controls)`
