### ISSUE TITLE
Right Option key doesn't work on OSX

### ISSUE THREAD

**Issue by sheharyarn** [mpv-player/mpv#1487]
Just what the title says, `mpv` doesn't seem to detect my right option/alt key. There's nothing wrong with the keyboard or the key physically, it works on all other apps. And nothing is wrong with the keybinds as well, since the left option key works fine. 

Here's my keybindings for the `option` key. [Full `input.conf` here](https://github.com/sheharyarn/dotfiles/blob/master/OSX/MPV/input.conf).

```
# ...
ALT+UP      ignore
ALT+DOWN    ignore
ALT+RIGHT   no-osd seek  10 - exact
ALT+LEFT    no-osd seek -10 - exact
# ...
```

I'm on a Mid-2013 13" Macbook Air running Yosemite. I installed `mpv` using `homebrew-cask`, here's the version details:

```
~ $ mpv --version
mpv 0.7.2-git-1783e8c (C) 2000-2014 mpv/MPlayer/mplayer2 projects
 built on 2014-12-20T12:21:40
ffmpeg library versions:
   libavutil       54.15.100
   libavcodec      56.13.100
   libavformat     56.15.102
   libswscale      3.1.101
   libavfilter     5.2.103
   libavresample   2.1.0
```

**Comment by pigoz** [comment]
I think using `--no-input-right-alt-gr` might help you http://mpv.io/manual/master/#options-no-input-right-alt-gr

mpv report the right Alt as AltGr like other multiplatfom software.

**Comment by sheharyarn** [comment]
Yes, that's it! Thank you! I added this to my [`mpv.conf`](https://github.com/sheharyarn/dotfiles/blob/master/OSX/MPV/mpv.conf) to fix the issue:

```
input-right-alt-gr=no 
```
