### ISSUE TITLE
Audio device underrun when using `--af=sofalizer` in a conditional profile

### ISSUE THREAD

**Issue by noobworth** [mpv-player/mpv#14889]
### mpv Information

```bash
mpv v0.38.0-792-g21a0fa7a Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 19 2024 00:10:52
libplacebo version: v7.349.0 (v7.349.0-13-ga018ab0-dirty)
FFmpeg version: N-117072-g665bf46ac
FFmpeg library versions:
   libavcodec      61.15.100
   libavdevice     61.2.101
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.36.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

```text
- Windows version: Microsoft Windows [Version 10.0.19045.4780]
- GPU model, driver and version: NVIDIA GeForce GTX 1660 SUPER, 551.52
- Source of mpv: shinchiro
- Introduced in version: don't know
```

### Reproduction Steps

Using the following conditional profile in mpv.conf causes an audible stutter at the start of the video and `[cplayer] Audio device underrun detected.` warning to be printed in console:
```
[sofalizer]
profile-cond=p["audio-params/channel-count"] > 2
af=sofalizer="C:\Program Files\mpv\sofalizer\clubfritz\ClubFritz6.sofa"
```

However, when launching mpv using cmd from the directory where the .sofa file is located with `mpv --no-config --af=sofalizer=ClubFritz6.sofa video.mkv` there is no audio stutter and no warning is printed to console.

I've had this profile in my config for some time now and this wasn't happening before. Unfortunately, I am not sure which version introduced this problem because I haven't watched surround audio content in a while, and have updated multiple times since.

### Expected Behavior

Audio device doesn't underrun.

### Actual Behavior

Audio device underrun detected.

### Log File

Video started with the conditional profile in mpv.conf:
[profile.txt](https://github.com/user-attachments/files/17063645/profile.txt)

Video started with `mpv --no-config --af=sofalizer=ClubFritz6.sofa`:
[cmd.txt](https://github.com/user-attachments/files/17063722/cmd.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
And the problem is what? You are inserting audio filter after starting playback, it is expected that it can produce some hitch. You will not see any under runs during playback.

**Comment by noobworth** [comment]
> You are inserting an audio filter after playback has started

Does that mean that when `--af` is set from cli it's applied before playback? Because the stutter only happens when the filter is on an auto profile which I find odd. But if that's the case then it makes sense.

**Comment by kasper93** [comment]
> Does that mean that when --af is set from cli it's applied before playback?

Exactly. You can see that in the log. To get `audio-params` you need to decode or at least demux some part of audio stream, depending on the format, but inserting af later, it basically reinitialize buffers and what not. Maybe it could be somehow improved, but this is unlikely to be done in sane way probably.

`--af=sofalizer`
```
[   0.159][v][ad] Selected decoder: ac3 - ATSC A/52A (AC-3)
[   0.185][v][ffmpeg] filter: SOFA license: Creative Commons Attribution-ShareAlike 3.0 Unported License
[   0.185][v][af] User filter list:
[   0.185][v][af]   sofalizer (sofalizer.00)
[   0.185][v][cplayer] Starting playback...
[   0.185][v][af] [in] 48000Hz 5.1(side) 6ch floatp
```

profile:
```
[   0.166][v][ad] Selected decoder: ac3 - ATSC A/52A (AC-3)
[   0.166][v][af] User filter list:
[   0.166][v][af]   (empty)
[   0.166][v][cplayer] Starting playback...
[   0.166][e][ffmpeg/video] mpeg2video: ignoring pic cod ext after 0
[   0.166][d][vd] DR parameter change to 1920x1088 yuv420p align=64
[   0.166][d][vd] Allocating new (host-cached) DR image...
[   0.166][d][vd] ...failed..
[   0.166][v][vd] DR failed - disabling.
[   0.172][v][vd] Using software decoding.
[   0.172][v][vd] Decoder format: 1920x1080 yuv420p auto/auto/auto/limited/auto CL=mpeg2/4/h264 crop=1920x1080+0+0
[   0.172][v][vd] Using container aspect ratio.
[   0.172][v][vf] [in] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display CL=mpeg2/4/h264 crop=1920x1080+0+0
[   0.172][v][vf] [userdeint] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display CL=mpeg2/4/h264 crop=1920x1080+0+0
[   0.172][v][vf] [userdeint] (disabled)
[   0.172][v][vf] [autorotate] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display CL=mpeg2/4/h264 crop=1920x1080+0+0
[   0.172][v][vf] [autorotate] (disabled)
[   0.172][v][vf] [convert] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display CL=mpeg2/4/h264 crop=1920x1080+0+0
[   0.172][v][vf] [convert] (disabled)
[   0.172][v][vf] [out] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display CL=mpeg2/4/h264 crop=1920x1080+0+0
[   0.172][v][af] [in] 48000Hz 5.1(side) 6ch floatp
[   0.172][v][af] [userspeed] 48000Hz 5.1(side) 6ch floatp
[   0.172][v][af] [userspeed] (disabled)
[   0.172][v][af] [convert] 48000Hz 5.1(side) 6ch floatp
[   0.172][v][auto_profiles] Re-evaluating auto profile sofalizer
[   0.172][i][auto_profiles] Applying auto profile: sofalizer
[   0.172][v][cplayer] Setting option 'af' = 'sofalizer="C:\Program Files\mpv\sofalizer\clubfritz\ClubFritz6.sofa"' (flags = 4)
[   0.197][v][ffmpeg] filter: SOFA license: Creative Commons Attribution-ShareAlike 3.0 Unported License
[   0.197][v][af] User filter list:
[   0.197][v][af]   sofalizer (sofalizer.00)
```

**Comment by noobworth** [comment]
I see. Thank you for the explanation. If that's the case, maybe I just simply haven't noticed the stutter before, since a lot movies have the audio fade in at the start.

**Comment by kasper93** [comment]
It is not unreasonable that there is small performance regression somewhere that caused this for you. Loading profiles itself in mpv didn't change recently, but a lot other things might have. So the only way to make some sense here is to try to test some older builds and find the first not working one. Then we can think what changed.

**Comment by noobworth** [comment]
Sure, I'll try to look for the regression when I have the time.
