### ISSUE TITLE
gpu-next breaks HDR

### ISSUE THREAD

**Issue by reenvasada** [mpv-player/mpv#14882]
### mpv Information

```bash
mpv v0.38.0-771-gef19a4a0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 15 2024 00:08:43
libplacebo version: v7.349.0 (v7.349.0-10-g76bb971-dirty)
FFmpeg version: N-117040-g3f84d1d1f
FFmpeg library versions:
   libavcodec      61.13.100
   libavdevice     61.2.101
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.36.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

```text
- Windows version: Microsoft Windows NT 10.0.22631.0/22631.4169 (Windows 11)
- GPU model, driver and version: AMD Radeon RX 6800 XT, driver 24.8.1
- Source of mpv: shinchiro
```

### Reproduction Steps

Run mpv with the arguments `--no-config --vo=gpu-next --fullscreen` on my HDR video file. Visual comparison with `vo=gpu` shows that vo=gpu-next does not play HDR while vo=gpu does. I can also confirm this with the "SDR content brightness" Windows setting.

### Expected Behavior

HDR works

### Actual Behavior

HDR does not work

### Log File

I created log files with vo=gpu and vo=gpu-next. I let the file play for 5 seconds.

- [gpu.txt](https://github.com/user-attachments/files/17049217/gpu.txt)
- [gpu-next.txt](https://github.com/user-attachments/files/17049218/gpu-next.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
set `--target-colorspace-hint`

**Comment by reenvasada** [comment]
Thanks. That fixes it. Why is it not the default?

**Comment by llyyr** [comment]
> Thanks. That fixes it. Why is it not the default?

Because you don't always want HDR passthrough? If you do then you can just set it in the config.

**Comment by reenvasada** [comment]
If you have an HDR monitor and have enabled HDR in the Windows setting and are playing an HDR file then you almost always want HDR to work. (I'm not sure if there is a distinction between "HDR passthrough" and "HDR works".)

For vo=gpu the default is to enable HDR, so why is it different for vo=gpu-next? The default should be the same.

**Comment by kasper93** [comment]
> Thanks. That fixes it. Why is it not the default?
