### ISSUE TITLE
Question: View video in original resolution

### ISSUE THREAD

**Issue by sheharyarn** [mpv-player/mpv#1488]
Like VLC, is there an option to view the video in original resolution (i.e. without any scaling)? In VLC, I would usually press the <kbd>O</kbd> key on the keyboard while playing a video to scale it to the original resolution, and press it again to scale it back to the window/screen size.

![Playing Video in Original Size](https://cloud.githubusercontent.com/assets/2355108/5793609/ef23aab0-9f6b-11e4-8563-735f9fbcc228.png)

Is there a similar option or keybinding in `mpv` that lets me do this? Because... ___reasons___.

**Comment by wm4** [comment]
``cycle video-unscaled``

**Comment by sheharyarn** [comment]
Awesome! Thanks!

**Comment by zhackk** [comment]
> `cycle video-unscaled`

what does that mean?
is there a file that I can edit or is there a shortcut for that, I'm totally new to mpv.
