### ISSUE TITLE
cddb support gone?

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1489]
I cannot find a switch to build mpv with cddb support and cddb protocol is missing.
Is there a way to enable it please?

**Comment by wm4** [comment]
cdda is still there, but cddb is gone. I don't think anyone missed it ever since I removed it over 2 years ago.

**Comment by kokoko3k** [comment]
I think that someone could miss it if the userbase of mpv will raise :)
Thanks for answering.
If there is no hope, i'll close this.

**Comment by wm4** [comment]
(Forgotten.)
