### ISSUE TITLE
MPV only uses Vulkan decoding when opened through terminal

### ISSUE THREAD

**Issue by jujar** [mpv-player/mpv#14893]
### mpv Information

```bash
mpv v0.38.0-dirty Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 17 2024 09:24:25
libplacebo version: v7.349.0
FFmpeg version: n7.0.2
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Other Information

```text
- Linux version: EndeavourOS
- Kernel Version: 6.10.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 12 Sep 2024 17:21:02 +0000 x86_64 GNU/Linux
- GPU Model: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6900 XT] [1002:73bf] (rev c0)
- Mesa/GPU Driver Version: Mesa 24.2.2-arch1.1
- Window Manager and Version: Wayland 1.23.1 /KWin 6.1.5
- Source mpv: Arch package repository
- Introduced in version: N/A
```

### Reproduction Steps

Whenever I open a video from terminal, I get Vulkan video decode and amdgpu_top detects that. However, if I open the same video from my file manager GUI (Dolphin), I do not get hwdec. This is also reproduced when I launch mpv from another app, for instance Freetube.

Here's the content of mpv.conf
`gpu-api=vulkan
vo=gpu-next
hwdec=vulkan
gpu-context=waylandvk
`
So, launching from terminal seems to respect mpv.conf. Opening from GUI does not seem to do so. Is there something I can try configuration wise?

### Expected Behavior

Hwdec works when opening video files from terminal and GUI file manager

### Actual Behavior

Hwdec only works when opening videos through terminal

### Log File

Output without a file selected
[output.txt](https://github.com/user-attachments/files/17083478/output.txt)

Output with a file opened using mpv.conf parameters
[output.txt](https://github.com/user-attachments/files/17083488/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
`export RADV_PERFTEST=video_decode` isn't being propagated outside your terminal would be my guess.

Also your log files are useless because you didn't post the ones _when_ hwdec fails.

**Comment by jujar** [comment]
Thank you. I don't know how to produce a log file from the GUI. Is there a way to do that?

**Comment by llyyr** [comment]
Launch `dolphin` from the terminal where hwdec works, then launch mpv from that dolphin instance. If it works then the variable isn't propagated to dolphin when it's launched normally

**Comment by jujar** [comment]
Thank you, this indeed is the issue. Since this falls outside the scope of MPV, I'll close the issue and take my worries elsewhere.
