### ISSUE TITLE
unexpected log

### ISSUE THREAD

**Issue by Fujiwara-Chika** [mpv-player/mpv#14891]
### mpv Information

```bash
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0
FFmpeg version: 7.0.2
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Other Information

```text
- macOS version: 15.0
- Source of mpv: homebrew
- Introduced in version:
```

### Reproduction Steps

mpv --no-config anyvideo

### Expected Behavior

none

### Actual Behavior

mpv --no-config test.mp4                                                    14:53:58
 (+) Video --vid=1 (*) (h264 1920x1080 23.684fps)
VO: [gpu] 1920x1080 yuv420p
_V: 00:00:00 / 02:35:18 (0%)2024-09-20 14:54:03.745 mpv[64062:4161829] +[IMKClient subclass]: chose IMKClient_Legacy
2024-09-20 14:54:03.745 mpv[64062:4161829] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
V: 00:00:01 / 02:35:18 (0%)_
Exiting... (Quit)

### Log File

[mpv.log](https://github.com/user-attachments/files/17071161/mpv.log)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Akemi** [comment]
the error doesn't come from our code. this is an upstream problem. either apple framework or an external lib.

though a quick google search seems to indicate that it's a macOS 15 problem.
