### ISSUE TITLE
playing youtube streams via libmpv fails.

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1491]
I was struggling to make this works in a project of mine, but it doesnt.
Then i tried baka-mplayer (which uses libmpv as well) and it fails too with those log messages (the same of mine):
```
[mpv]: Run command: loadfile, flags=0, args=[https://www.youtube.com/watch?v=9vZvqNBGagw, replace, ]
[mpv]: config path: 'watch_later/DDAA9F329C60D3A10EFD51EA99B6C662' -> '(NULL)'
[mpv]: config path: 'watch_later' -> '(NULL)'
[mpv]: Playing: https://www.youtube.com/watch?v=9vZvqNBGagw
[mpv]: Running hook: ytdl_hook/on_load
[mpv]: WARNING: video doesn't have subtitles
[mpv]: failed to parse JSON data: error 
[mpv]: Run command: hook_ack, flags=0, args=[on_load]
[mpv]: Opening https://www.youtube.com/watch?v=9vZvqNBGagw
[mpv]: https: request: GET /watch?v=9vZvqNBGagw HTTP/1.1
[mpv]: User-Agent: mpv git-46a3974
[mpv]: Accept: */*
[mpv]: Range: bytes=0-
[mpv]: Connection: close
[mpv]: Host: www.youtube.com
[mpv]: Icy-MetaData: 1
[mpv]: 
[mpv]: 
[mpv]: https: header='HTTP/1.1 200 OK'
[mpv]: https: http_code=200
[mpv]: https: header='Date: Mon, 19 Jan 2015 13:49:54 GMT'
[mpv]: https: header='Server: gwiseguy/2.0'
[mpv]: https: header='Content-Type: text/html; charset=utf-8'
[mpv]: https: header='Cache-Control: no-cache'
[mpv]: https: header='Expires: Tue, 27 Apr 1971 19:44:06 EST'
[mpv]: https: header='X-Frame-Options: SAMEORIGIN'
[mpv]: https: header='X-Content-Type-Options: nosniff'
[mpv]: https: header='P3P: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=it for more info."'
[mpv]: https: header='X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube'
[mpv]: https: header='Transfer-Encoding: chunked'
[mpv]: https: header='Alternate-Protocol: 443:quic,p=0.02'
[mpv]: https: header='Set-Cookie: PREF=f1=50000000; expires=Sun, 20-Sep-2015 01:42:54 GMT; path=/; domain=.youtube.com'
[mpv]: https: header='Set-Cookie: YSC=Twjl2rCT3BI; path=/; domain=.youtube.com; HttpOnly'
[mpv]: https: header='Set-Cookie: VISITOR_INFO1_LIVE=UrsUeBhxSts; expires=Sun, 20-Sep-2015 01:42:54 GMT; path=/; domain=.youtube.com'
[mpv]: https: header='Connection: close'
[mpv]: https: header=''
[mpv]: Opened: https://www.youtube.com/watch?v=9vZvqNBGagw
[mpv]: Mime-type: 'text/html; charset=utf-8'
[mpv]: Cache size set to 25000 KiB
[mpv]: Trying demuxer: disc (force-level: normal)
[mpv]: Trying demuxer: edl (force-level: normal)
[mpv]: Trying demuxer: cue (force-level: normal)
[mpv]: Trying demuxer: rawaudio (force-level: normal)
[mpv]: Trying demuxer: rawvideo (force-level: normal)
[mpv]: Trying demuxer: tv (force-level: normal)
[mpv]: Trying demuxer: libass (force-level: normal)
[mpv]: Trying demuxer: mkv (force-level: normal)
[mpv]: Trying demuxer: lavf (force-level: normal)
[mpv]: tls: La connessione TLS non è stata terminata in modo corretto.
[mpv]: EOF reached.
[mpv]: EOF reached.
[mpv]: EOF reached.
[mpv]: No format found, try lowering probescore or forcing the format.
[mpv]: Trying demuxer: mf (force-level: normal)
[mpv]: Trying demuxer: playlist (force-level: normal)
[mpv]: Trying demuxer: subreader (force-level: normal)
[mpv]: Trying demuxer: disc (force-level: unsafe)
[mpv]: Trying demuxer: edl (force-level: unsafe)
[mpv]: Trying demuxer: cue (force-level: unsafe)
[mpv]: Trying demuxer: rawaudio (force-level: unsafe)
[mpv]: Trying demuxer: rawvideo (force-level: unsafe)
[mpv]: Trying demuxer: tv (force-level: unsafe)
[mpv]: Trying demuxer: libass (force-level: unsafe)
[mpv]: Trying demuxer: mkv (force-level: unsafe)
[mpv]: Trying demuxer: lavf (force-level: unsafe)
[mpv]: EOF reached.
[mpv]: EOF reached.
[mpv]: No format found, try lowering probescore or forcing the format.
[mpv]: Trying demuxer: mf (force-level: unsafe)
[mpv]: Trying demuxer: playlist (force-level: unsafe)
[mpv]: Trying demuxer: subreader (force-level: unsafe)
[mpv]: Failed to recognize file format.
[mpv]: 
[mpv]: Terminating cache...
[mpv]: Cache exiting...
[mpv]: AVIOContext: Statistics: 178998 bytes read, 0 seeks
```

I tried with "loadfile" and "loadlist" commands, but got the same error.
Using --slave-broken works
Using mpv by command line works.
Using socat/IPC works too.

**Comment by wm4** [comment]
It's disabled by default in libmpv, because we considered it too instrusive.

Something like this should make it work: ``mpv_set_option_string(ctx, "ytdl", "no");``

**Comment by wm4** [comment]
It's disabled by default in libmpv, because we considered it too instrusive.

Something like this should make it work: ``mpv_set_option_string(ctx, "ytdl", "yes");``

**Comment by ChrisK2** [comment]
It seems like the ytdl script was active though, it just failed to parse the JSON data for some reason.

**Comment by wm4** [comment]
Oh, you're right.

Then maybe it's locale shit.

**Comment by wm4** [comment]
@kokoko3k: can you tell us whether you set the ``LC_NUMERIC`` locale?

If you do (or more likely, the GUI framework or something else does), undo it with ``setlocale(LC_NUMERIC, "C");``, and try again.

I know that Qt like to set the locale by default and without a way to prevent it from doing that.

**Comment by xylosper** [comment]
@wm4 
Qt changes locale but only one in initialization of QCoreApplication (or it's derived class). Here's documentation:

> Locale Settings
>
> On Unix/Linux Qt is configured to use the system locale settings by default. This can cause a conflict when using POSIX functions, for instance, when converting between data types such as floats and strings, since the notation may differ between locales. To get around this problem, call the POSIX function setlocale(LC_NUMERIC,"C") right after initializing QApplication or QCoreApplication to reset the locale that is used for number formatting to "C"-locale.

**Comment by mc4man** [comment]
Just to note - baka-mplayer has no issues playing urls that use/require youtube-dl & the ytdl script
(neither does cmplayer

**Comment by xylosper** [comment]
@mc4man 
FYI, bomi(perviously known as CMPlayer) does not use `ytdl` option. Instead, CMPlayer hooks and calls youtube-dl by itself like what ytdl lua script does. And, of course, locale issue is fixed following what I mentioned.  I don't know about baka-mplayer.

**Comment by kokoko3k** [comment]
@mc4man: those logs are right from baka-mplayer ; setting LC_ALL=C makes it work.
my previous $LANG was it_IT.utf8

**Comment by wm4** [comment]
So it was locale after all. I guess I'll add a check to mpv, because this seems to happen far too often. I can't do full checking though, because locale can be changed at any time (thus break stuff at any time).
