### ISSUE TITLE
set up media reporting to os

### ISSUE THREAD

**Issue by solomoncyj** [mpv-player/mpv#14919]
### Expected behavior of the wanted feature

![image](https://github.com/user-attachments/assets/76439ca0-7102-4d33-b9df-0c4e051de16d)
report staus of media played to os and allow os widgets and key bindings to work, eg dedicated media play/pause button

**Comment by sfan5** [comment]
Install the mpv-mpris plugin if you want this.

**Comment by kasper93** [comment]
https://github.com/eNV25/mpv-mpris2
https://github.com/hoyon/mpv-mpris
