### ISSUE TITLE
Crashes on closing with HDR enabled

### ISSUE THREAD

**Issue by CarterLi** [mpv-player/mpv#14910]
### mpv Information

```bash
mpv 0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0
FFmpeg version: 7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

```text
- macOS version: macOS 15.0 (24A335)
- Source of mpv: homebrew
- Introduced in version: N/A
```

### Reproduction Steps

`mpv /path/to/hdr-video.mp4 -v --vo=gpu-next --target-colorspace-hint --no-config`

### Expected Behavior

Don't crash

### Actual Behavior

Crashed

### Log File

[output.txt](https://github.com/user-attachments/files/17109723/output.txt)

[backtrace.txt](https://github.com/user-attachments/files/17109731/backtrace.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/issues/12666
