### ISSUE TITLE
Unable to open playlist from x.com

### ISSUE THREAD

**Issue by rach-md** [mpv-player/mpv#14912]
### mpv Information

```bash
mpv 2c5928e Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 23 2024 22:34:28
libplacebo version: v7.349.0
FFmpeg version: 44b8ea4
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Important Information

```text
- Platform version: Windows 10 64bit
- GPU model, driver and version: Radeon R5
- Source: Github Action
- Introduced in version: Unknown
```

### Reproduction Steps

Play a playlist link from x.com (link in log)

### Expected Behavior

Play a video with other video added to playlist

### Actual Behavior

running from cmd produces this error
[ytdl_hook]
[ytdl_hook] stack traceback:
[ytdl_hook]     @ytdl_hook.lua:1187: in function 'on_load_hook'
[ytdl_hook]     @ytdl_hook.lua:1191: in function 'fn'
[ytdl_hook]     mp.defaults:602: in function 'handler'
[ytdl_hook]     mp.defaults:515: in function 'call_event_handlers'
[ytdl_hook]     mp.defaults:557: in function 'dispatch_events'
[ytdl_hook]     mp.defaults:508: in function <mp.defaults:507>
[ytdl_hook]     [C]: at 0x7ff74eb22d30
[ytdl_hook]     [C]: at 0x7ff74eb22360
[ytdl_hook] Lua error: @ytdl_hook.lua:1145: attempt to index local 'site' (a nil value)
client removed during hook handling
Failed to recognize file format.
Sending hook command failed. Removing hook.

### Log File

https://pastebin.com/gN5vXeXr

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Add `/photo/1` after the end of the URL. This is a yt-dlp bug, it returns the video in the tweet and also the video in the tweet that is being quoted. mpv doesn't handle multiple videos being returned from yt-dlp, and I can't imagine it being sane behavior to download unrelated videos when the user explicitly requested a specific URL.

You can reproduce with just `yt-dlp URL`, it should download both videos by default.
