### ISSUE TITLE
Please add support for multi-threads libavfilter processing

### ISSUE THREAD

**Issue by tramchamploo** [mpv-player/mpv#14923]
### Expected behavior of the wanted feature

Nowadays people like me use ffmpeg audio filter for upmixing, binauralizing and high quality resampling which in this case one core processing is not sufficient.
I believe ffmpeg already support it and enable it by default. Somehow mpv only use 1 thread for filtering.

### Alternative behavior of the wanted feature

User can specify threads for filtering or let ffmpeg do it automatically.

**Comment by richardpl** [comment]
Dunno what you complain about, command: "ffmpeg -h filter=<name_of_filter>" will list slice threading supported for audio filters.
Such filter will use multiple threads for processing each input/output channel.

Do get more useful response, provide more detailed report.

**Comment by tramchamploo** [comment]
So I checked that most audio filters have no multithread support. I use ffmpeg swr resampler with a filter size of 8192, but if I use 16384, sound has to stop every now and then. I think 16384 is pretty reasonable when dealing with 192khz audio. I tried changing alsa buffer size but no luck. Command top shows that I have used one of my core to 100% usage. Any suggestions that I can optimize this?

**Comment by richardpl** [comment]
You are on your own with swr low quality messy resampler, I wonder where you got idea to use that excessive filter size for poor performed extremely low quality and unmaintained resampler.

Get at least build with soxr enabled swr resampler engine and use that with correct filter parameters specified.

Most audio filters have no multi-threading support?

Let me reality fact-check your claim:

In librempeg there are 274 filters with multi-threading (both Audio and Video) of 508 filters. That is more than half. And I did not removed filters that are not multi-threaded but are also not doing any real CPU work (either hwaccel or metadata passthrough).

**Comment by tramchamploo** [comment]
Extremely low quality and unmaintained? I don't think so. [libswresample](https://git.ffmpeg.org/gitweb/ffmpeg.git/history/HEAD:/libswresample). As for quality, comparison[here](https://src.infinitewave.ca/) shows it's not a bad resampler. And it's not that low noise sampler are always better. You have to take ringing into consideration for hifi listening.

**Comment by richardpl** [comment]
Ask yourself why swresample have SoX resampling engine named soxr.
Libswresample is so bad that its aliasing is actually detectable by normal human hearing system.
Libswresample is not maintaned really, also its conception is strange to say at best, as it is just uglier clone of now removed libavresample from old LibAV fork days.

Last significant and fairly recent critical improvement to swresample was made by myself, the path for 16bit->16bit resampling used only 16bit precision, yikes. So I'm clearly capable, well informed and skilled to say final word about this library net gain result, in my opinion its one of the worst open source implementations of resampling, there are for certain faster resamplers out that that give better quality at same or worse parameters than libswresample.

And if you closely inspect infinitewave output for swresampler native engine resampler you will see its aliasing is very strong.
Also this have marginal importance and relevance for mpv project as aresample filter you use is not part of mpv, but part of FFmpeg project source code. PS: The goal of Librempeg project is to remove libswresample junk mess from its source code.

**Comment by richardpl** [comment]
I do not want to touch dither code of libswresample, in one occasion, with right parameters, (there is still open bug report on ffmpeg trac) it produces extremely loud artifacts to kill old speakers with ease.

phase shift setting controls if you need min phase or linear phase FIR polyphase resampler, usually linear is in mid range and minphase is smaller values with 0 being minimum.

I just tested resampling 32000Hz to 192000Hz, with no extra options it is produces aliasing after near -130dB
That is passable somehow for casual listening of 16bit audio. For anything more it is not. Of course that setting have very bad lowpass cutoff...

async / min_comp options controls stretching and squeezing to compensate for non-monotonous frame timestamps.
If you have no PTS gaps or drops or whatever you do not need this at all, its mainly for low-quality streaming and low-quality files with broken presentation timestamps.

I dunno how that options works with rest of dithering and resampling, maybe some combinations are not implemented/buggy/or not possible at all.

You can get better impulse response with some advanced settings/options to avfilter aresample filter.
But cost is big performance drop, and at such case, for faster resampling better use soxr resamping within aresample filter, it  should get better quality at same speed or even faster.

(Dunno if soxr engine works with async feature at all)

How to enable soxr resampler?
Just use "aresample=resampler=soxr"

**Comment by kasper93** [comment]
> Just use "aresample=resampler=soxr"

In mpv that would be `audio-swresample-o=resampler=soxr`

**Comment by tramchamploo** [comment]
But you cannot set phase shift with soxr.

**Comment by tramchamploo** [comment]
> > Just use "aresample=resampler=soxr"
> 
> In mpv that would be `audio-swresample-o=resampler=soxr`

Thank you. I use `af=aresample` to set it. My purpose is not to match my device's sample rate but to apply some upmixing and binauralizing so highly customiziable sampler is prefered.

**Comment by richardpl** [comment]
> But you cannot set phase shift with soxr. If your DAC has a clean impulse response, the resampler's impulse related pre-ringing becomes really audible.

Correct, that is limitation/bug of libswresample code. Feel free to send patch to FFmpeg.

PS: aasrc from librempeg is ultra min delay min-phase resampler filter, not using FIR but IIR/phasors instead.

**Comment by tramchamploo** [comment]
Since `surround` supports slice threading. Why top shows computation on a single core? 
`af-append=lavfi="surround=chl_out=5.1:angle=120:lfe_low=5:lfe_high=180:lfe_mode=sub:overlap=0.985:win_func=bharris:focus=0.2:smooth=1:win_size=65536":o="filter_threads=20,thread_type=slice"
`
if I make overlap larger, mpv shows 'Audio device underrun detected.'. I tried with different buffer size for pipewire and didn't work.

**Comment by richardpl** [comment]
Do not use larger, extreme parameters like overlap and win_size in surround filter, it is averaging too much.
The librempeg version of surround filter is more optimized for speed and quality, still need to resolve phasing issues, probably will just replace overlap-add with overlap-save, then using higher win_size would be possible without need for even higher overlap value. Smooth parameter is too big, keep it in -10dB to -20dB value range. Dunno how many threads you have, but if input is single channel than input path processing will use single thread, similarly for output path if it have 6 channels and you have 6 CPU cores it will use 6 threads. In my usage surround filter shows using all available CPU cores. On pretty old laptop old surround was 10x realtime new surround filter from Librempeg is ~30x realtime fast, on newer laptop with 8 CPU cores its also 3x faster, 100x realtime before and 300x realtime after.

So combination of extreme overlap and extreme win_size will make it very slow, near 8x on newer 8 CPU cores laptop.

PS: If you use Librempeg please use discussion there for this type of talk.

If you use ffmpeg version of surround filter, its very old, and limited and only float 32bit precise with bunch of other losses of precisions in each operation step.

Audio device underrun detected also can happen because filter is so slow that mpv have not received samples to feed to sound device in time, either because filtering is not realtime or some other task/process needs also CPU/memory/disk etc...

**Comment by tramchamploo** [comment]
Librempeg is fantastic. I'll leave a [link](https://github.com/librempeg/librempeg/issues/12) for someone interested in high quality dsp.
