### ISSUE TITLE
macOS "Game Mode" notification

### ISSUE THREAD

**Issue by myspaghetti** [mpv-player/mpv#14928]
### Expected behavior of the wanted feature

The `Info.plist` file defines the `LSApplicationCategoryType` as `public.app-category.games` which causes macOS to show a "Game Mode" notification.

Since macOS does not have an option to disable this notification (whether Game Mode is on or off) I'd prefer if mpv.app's `LSApplicationCategoryType` was `public.app-category.video` so it doesn't trigger the Game Mode notification.

### Alternative behavior of the wanted feature

Define `LSApplicationCategoryType` as `public.app-category.video` in [`mpv.app/Contents/Info.plist`](https://github.com/mpv-player/mpv/blob/d54e8c3f40934501d5fb5875defd797eff0ae57b/TOOLS/osxbundle/mpv.app/Contents/Info.plist#L136)

### Log File

mpv 2c5928e Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 23 2024 22:24:20
libplacebo version: v7.349.0
FFmpeg version: 7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100

**Comment by hooke007** [comment]
https://github.com/mpv-player/mpv/pull/13558

**Comment by Akemi** [comment]
nothing we can do about. using the video category would defy the purpose of that change. see apple's documentation:

> Game Mode optimizes your gaming experience by giving your game the highest priority access to your CPU and GPU, lowering usage for background tasks. And it doubles the Bluetooth sampling rate, which reduces input latency and audio latency for wireless accessories like game controllers and AirPods.

all things that are also beneficial to video playback.

if your problem only lies with the notification that can't be disabled, please report it to apple so we get an option for it.

**Comment by myspaghetti** [comment]
If anyone's looking for a (bad) workaround, this keybinding sort-of toggles the geometry between the video's original size and "fullscreen" on a 4K display:

`no-osd cycle-values geometry 3840x2158 ""`

Or, using percentages, which leaves a bigger gap but works for every resolution:

`no-osd cycle-values geometry 100%x99% ""`

Far from perfect but less intrusive than that toaster message, I think.

**Comment by Akemi** [comment]
maybe it would be easier to just change that node in the info.plist of the bundle, instead of working around it with a key binding.

**Comment by myspaghetti** [comment]
I'm just too lazy to [code-sign the app bundle](https://gist.github.com/rsms/929c9c2fec231f0cf843a1a746a416f5#signing-app-bundles) every time it updates and I change `Info.plist`, or compile the app bundle myself.

Thanks for mpv, it's without a doubt the best video player that exists.

**Comment by Akemi** [comment]
like i said, please start barking up the >right< tree, eg start annoying Apple about it. it's in their hand to change this.

**Comment by llyyr** [comment]
If there's no known benefits then imo it makes sense to not set it

**Comment by iamevn** [comment]
FIgured I should share my nix configs to automatically patch that plist entry in case someone else finds it useful: https://gist.github.com/iamevn/8045cfb1682249bd36b478008cbed7a8

**Comment by Akemi** [comment]
#16996 made it configurable and set the default to video, eg it will be opt-in when merged.
