### ISSUE TITLE
Regression in mpv v0.39.0: cannot play mkv files with embedded cover/thumbnail

### ISSUE THREAD

**Issue by iegubkin** [mpv-player/mpv#14924]
### mpv Information

```bash
mpv v0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 23 2024 17:46:22
libplacebo version: v7.349.0
FFmpeg version: n7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

```text
- Linux version: Arch Linux
- Kernel Version: Linux Q1900-ITX 6.10.10-arch1-1
- GPU Model: 00:02.0 VGA compatible controller [0300]: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display [8086:0f31] (rev 0e)
- Mesa/GPU Driver Version: OpenGL version string: 4.2 (Compatibility Profile) Mesa 24.2.3-arch1.1
- Window Manager and Version: Fluxbox 1.3.7
- Source mpv: https://gitlab.archlinux.org/archlinux/packaging/packages/mpv
- Introduced in version: 0.39
```

### Reproduction Steps

[BigBuckBunny test video](https://download.blender.org/demo/movies/BBB/bbb_sunflower_1080p_30fps_normal.mp4.zip)
[BBB test image converted to PNG](https://m.media-amazon.com/images/M/MV5BNmZkNWNmYTgtNmYyMy00NTM0LThiOWYtY2FmMzBiNTRhNmZiXkEyXkFqcGc@._V1_.jpg
)
[ffmpeg command used](https://ffmpeg.org/ffmpeg.html#toc-Main-options):
`ffmpeg -i "/tmp/bbb_sunflower_1080p_30fps_normal.mp4" -i BBB.png -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic out.mkv`

mpv plays video but stutters/buffers constantly. Video is not watchable.

### Expected Behavior

mkv plays this without error as it does in previous versions (0.38 tried specifically as well as current ffplay).

### Actual Behavior

I have numerous mkv video files with embedded cover art as secondary video streams (--vid=2).
None can be played successfully with v0.39.0. The stuttering/buffering makes it so the video barely plays.
mpv v0.38 (and prior versions) as well as current ffplay handle these files without error. A mp4 file generated with the same command as above plays perfectly with mpv 0.39. The same test video converted from the original mp4 to mkv without the embedded art plays without error as well. Thank you for considering this report.

### Log File

[output_mkv_failure.txt](https://github.com/user-attachments/files/17139670/output_mkv_failure.txt)

### Sample Files

[out.mkv](https://www.mediafire.com/file/nrr0i0aff16j5te/out.mkv/file)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Are you able to bisect? I can't reproduce this locally

**Comment by Dudemanguy** [comment]
Bisected to 22ed5d0d3a2e1db99f5e2d6165f0ecd013fef4d1. Specifically it's the increase in the limit (from 1000 to 100000) that causes this. Not obvious to me why that happens though.

**Comment by iegubkin** [comment]
I uploaded the completed sample file if this helps.

**Comment by Dudemanguy** [comment]
For the record, the image isn't actually properly embedded in the mkv as an attached picture. You want to use something like this instead `ffmpeg -i bbb_sunflower_1080p_30fps_normal.mp4 -attach BBB.jpg -metadata:s:t:0 mimetype=image/jpeg -c copy out.mkv`. See [here](https://github.com/mpv-player/mpv/issues/12387#issuecomment-1841488698) as well.

Of course, it is still a bug that we stall on a broken file like this. Something about the probing works not as expected.

**Comment by iegubkin** [comment]
Thank for the tip. I will definitely use this going forward. Unfortunately I have a ton of videos I now know are not up to spec. Its a little surprising that the "wrong" way is lifted directly from the ffmpeg documentation.

**Comment by Dudemanguy** [comment]
That ffmpeg in the documentation works for mp4 but not mkv. It probably should at least be clearer about that.
