### ISSUE TITLE
Filename handling on OS X: NFD used, should use NFC

### ISSUE THREAD

**Issue by zmwangx** [mpv-player/mpv#1492]
HFS+ filesystem on OS X uses Unicode NFD instead of NFC (see [Unicode Standard Annex No.15: Unicode Normalization Forms](http://unicode.org/reports/tr15/)). The encoding used by HFS+ is usually called `UTF-8-MAC`. To display filenames in this encoding correctly, it is often necessary to convert from `UTF-8-MAC` to `UTF-8` first, e.g., via `iconv -f UTF-8-MAC -t UTF-8`. Apparently `mpv` doesn't do this, so the filenames displayed in the control box are sometimes wrong, especially when Korean characters are involved. For instance, `한글.mpg` is displayed as `ᄒ.ᅡ.ᆫ.ᄀ.ᅳ.ᆯ.mpg` (I added periods between adjacent characters; otherwise the browser will assemble the NFD back into NFC, and the result will look indistinguishable.) See screenshot.

![](http://i.imgur.com/ve8bIby.png)

**Comment by wm4** [comment]
Report this to apple? I know, they won't care, but neither do I.

**Comment by zmwangx** [comment]
@wm4
> Report this to apple?

This is *not* a bug on Apple's part. It's just an annoying feature of HFS+. NFD is a well-defined encoding (see linked standard); it would be perfectly fine if everyone were using it. (Mind you, HFS+ is a very old filesystem.)

> Neither do I.

If this is your attitude toward bug reports, what else can I say?

**Comment by pigoz** [comment]
Maybe I can deal with this, I wonder if there's an API to get the filesystem's encoding.

**Comment by zmwangx** [comment]
@pigoz 
> I wonder if there's an API to get the filesystem's encoding.

I'm inclined to say no, since as far as I know, Apple itself overlooks this issue in its own software, e.g., Terminal.app. And a lot of other third party software trips on this issue, e.g., iTerm2. NFD is a really unfortunate feature of HFS+ for people like me who occasionally deal with Korean characters.

**Comment by pigoz** [comment]
Well wtf then... am I supposed to run ENCA on the filename?

**Comment by zmwangx** [comment]
@pigoz Maybe always convert from `UTF-8-MAC` to `UTF-8` on OS X? At least it doesn't hurt; if the input is NFC, the output will just remain NFC (and as said before, if the input is NFD, then it will be converted to NFC). Tested with `iconv`.

**Comment by wm4** [comment]
>This is not a bug on Apple's part. It's just an annoying feature of HFS+. NFD is a well-defined encoding (see linked standard); it would be perfectly fine if everyone were using it. 

But Apple mixes them everywhere, and also the whole rest of the world uses NFC, so I'm not sure why you'd expect consistent behavior. (Although in this case, I'd expect Harfbuzz actually being able to deal with NFD.) How would we possibly fix this? We'd have to check and possibly mutate any input, whether it's from command line, input through a pipe, file drag&drop, playlists... If you use a bad OS, you sometimes have to live with the consequences. Just like HFS+ sometimes likes to randomly corrupt the filesystem.

**Comment by zmwangx** [comment]
> How would we possibly fix this?

See my comment above. You can just do a blind transformation on OS X, if that's feasible.

**Comment by wm4** [comment]
>You can just do a blind transformation on OS X, if that's feasible.

It's not. We would have to do this at dozens of entrypoints, and even then we'd have to make sure the renormalization wouldn't corrupt data (in cases where actually NFD is needed for some reason). In many places, there is no difference between filenames and "normal" strings. Not to mention that we'd suddenly have to care about freeing the converted strings.

**Comment by zmwangx** [comment]
> It's not.
Okay, ignore this then. It's not a big deal, just looks very bad. You might want to mark this as won't fix and close it.

**Comment by zmwangx** [comment]
Hey, but wait, why do you need to do this at dozens of entrypoints? It's not a problem at the entrypoint; you just have to renormalize the string once before you print it — otherwise it can stay untouched.

**Comment by wm4** [comment]
>Hey, but wait, why do you need to do this at dozens of entrypoints? It's not a problem at the entrypoint; you just have to renormalize the string once before you print it — otherwise it can stay untouched.

As I said before, I'd expect harfbuzz to be able to deal with NFD. Either you're not using harfbuzz, or harfbuzz can't deal with NFD, or the way libass uses harfbuzz breaks with NFD.

**Comment by zmwangx** [comment]
> Either you're not using harfbuzz, or harfbuzz can't deal with NFD, or the way libass uses harfbuzz breaks with NFD.

Sorry, I'm confused. I don't think I'm using libass when I captured the screenshot.

**Comment by wm4** [comment]
> I don't think I'm using libass when I captured the screenshot.

All text on the video window is rendered by libass in mpv, including the OSD and OSC.

Also, NFD on OSX does break other things, see e.g. #1027.

**Comment by zmwangx** [comment]
> Also, NFD on OSX does break other things, see e.g. #1027.

Okay, then this is a won't fix.

**Comment by wm4** [comment]
Just tested, harfbuzz renders NFD perfectly fine.

**Comment by zmwangx** [comment]
> Just tested, harfbuzz renders NFD perfectly fine.

Is it an optional dependency?

**Comment by pigoz** [comment]
for libass it is an optional dependency, yes.

**Comment by wm4** [comment]
Without harfbuzz, libass will do naive text layouting, which excludes properly combining glyphs, which is needed with NFD (but also NFC for some languages/characters).

**Comment by zmwangx** [comment]
Problem solved after compiling with halfbuzz, thanks. Maybe it's worthwhile to note this in README (or maybe it is too obscure to deserve a place).

**Comment by wm4** [comment]
I actually updated the _README now, though I doubt anyone experiencing the same problem would catch it.
