### ISSUE TITLE
Suggestion to make scaler-resizes-only default to true

### ISSUE THREAD

**Issue by maletor** [mpv-player/mpv#1493]
Disabling the video scaling by setting the scaling method to bilinear for video output might benefit video quality when outputting source files to their native resolutions.

**Comment by haasn** [comment]
I don't think it would impact quality as much as performance. That said, it seems to be a good idea pretty much in general.

**Comment by maletor** [comment]
True, they are probably both negligible, but I think we agree, why sharpen video that isn't asking to be.

**Comment by wm4** [comment]
What is the argument for enabling this? If it's too slow, then why are you enabling a slow scaler? If your video size is always the same as window size, why are you enabling a scaler at all?

I wouldn't be opposed, but it'd be strange when enabling a filter that changes the image even if the image is not scaled (like blurring or sharpening). You can bet that enabling this option does _not_ the intuitive and expected behavior.

**Comment by Rick74crx** [comment]
Let's say I have a Full HD monitor: I would normally use a good scaler for files whose resolution is inferior to my screen's one (mostly 720p but also old SD video files), but if the source file is already 1080p I would prefer to mess with it as little as possible and save as much resources as I can. 
I think this is pretty common these days, so I too think that enabling scaler-resizes-only by default would be a good move.

**Comment by wm4** [comment]
Rejected, I think most of which could come out of this is accidentally hiding scaler bugs.

**Comment by Hrxn** [comment]
That is the question I was about to ask right now.. Good to know that the issue tracker search works. ;-)

Okay, so the source of my confusion is, as stated by the manual:

> scaler-resizes-only
Disable the scaler if the video image is not resized. In that case, bilinear is used instead whatever is set with scale. Bilinear will reproduce the source image perfectly if no scaling is performed. Enabled by default. Note that this option never affects cscale.

It says 'Enabled by default', but here in the issue it is 'rejected' and 'wontfix'.

So what is actually happening?

**Comment by wm4** [comment]
Change of opinion?

**Comment by Hrxn** [comment]
Okay, so the manual is correct and it is enabled by default, right?

That is all I wanted to know, thanks! ;-)
