### ISSUE TITLE
Weird conversion filter selected for rgb48be inputs.

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#1494]
When playing back an rgb48be file (such as a 16-bit PNG image), the inserted conversion filter (swscale) defaults to yuv444p as target format, even though rgb48le exists and makes much more sense.

Manually adding --vf=format=fmt=rgb48le fixes this quirk.

Example file: http://i.srsfckn.biz/C2.png

**Comment by wm4** [comment]
Yes, the ancient pixel format selection code in vf_scale does this. It ends up selecting the best format it knows. The simple fix is adding a preferred conversion here http://git.srsfckn.biz/mpv/tree/video/filter/vf_scale.c#n117 , the complicated fix is rewriting all this shit.

**Comment by wm4** [comment]
I chose the latter. It should work now, although it slices off the alpha component.
