### ISSUE TITLE
Windows cannot have access to that file for the following reasons:

### ISSUE THREAD

**Issue by ruben1PvP** [mpv-player/mpv#14940]
### mpv Information

```bash
I cannot open mpv, less use any of its commands
```

### Other Information

```text
- Windows version: Windows 10 Pro 22H2
- GPU model, driver and version: NVIDIA GTX 1050 Ti. Driver Version 32.0.15.6109 (according to Device Administration)
- Source of mpv: https://github.com/shinchiro/mpv-winbuild-cmake/releases (20240927) (The bug applies to any version of any build)
- Introduced in version: In a previous version that I can't check because as said previously I cannot run --version
```

### Reproduction Steps

I built a new PC and such forgot about my old one for 6 months. A month ago I had to turn it on again and move everything to a new hard drive, including the mpv build. However, when I click on mpv.exe, the cursor changes to the circle as it is loading and then stops. Nothing happens afterwards. I tried to use installer.bat but the issue persists. I tried to use mpv in a console (powershell) and nothing happens, even if it's invoked with arguments

![PS](https://github.com/user-attachments/assets/545bb1e0-282c-433a-a26c-6432180d0f25)

The only "feedback" I had was from the Event Viewer, who told me this:

![Screenshot from the Event Viewer](https://github.com/user-attachments/assets/982ff480-6941-4e35-94e2-dd5cb5e3d21c)
![Screenshot from the Second Event](https://github.com/user-attachments/assets/40585690-ae91-47d5-a07b-0428f9342906)

As I said, the mpv build is in my main hard drive. I tried moving it around to another folder. I tried running chkdsk /F as asked by the event. I tried updating my drivers. I even tried to re-install Windows (maintaining programs and files). I don't know what else to do. Am I missing a dependency? It's the only explanation I can think of.

### Expected Behavior

MPV opens.

### Actual Behavior

Nothing happens.

### Log File

I cannot use that command either

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
We can't read Spanish, and this probably isn't a mpv issue

**Comment by ruben1PvP** [comment]
> We can't read Spanish, and this probably isn't a mpv issue

Basically saying, it's saying what the title of this issue is. Do you have any idea of what it could be?

**Comment by llyyr** [comment]
> Do you have any idea of what it could be?

No, read what it says. I'd be very surprised if it wrote all that text to say "Windows cannot have access to that file" in 50x more words. Either way not a mpv issue.

**Comment by ruben1PvP** [comment]
Alright, I suppose I'm in my own then.
