### ISSUE TITLE
Inconsistent behavior about URL

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1495]
Here are two URLs which contain spaces:
```
ftp://serv.valdikss.org.ru:21/Anime/Higurashi No Naku Koro Ni/[Exiled-Destiny]_When_They_Cry_Higurashi_Ep01_(6B18F06D).mkv

http://wormtube.worms2d.info/vids/Best Games of the Season 3.mp4
```

Without percent encoding,
```
mpv "ftp://serv.valdikss.org.ru:21/Anime/Higurashi No Naku Koro Ni/[Exiled-Destiny]_When_They_Cry_Higurashi_Ep01_(6B18F06D).mkv"
```
This works, but,

```
mpv "http://wormtube.worms2d.info/vids/Best Games of the Season 3.mp4"
```
This doesn't work.

With percent encoding,
```
mpv "ftp://serv.valdikss.org.ru:21/Anime/Higurashi%20No%20Naku%20Koro%20Ni/%5BExiled-Destiny%5D_When_They_Cry_Higurashi_Ep01_(6B18F06D).mkv"
```
This doesn work this time, but,
```
mpv "http://wormtube.worms2d.info/vids/Best%20Games%20of%20the%20Season%203.mp4"
```
This works.

I can't understand what's going on here.
Maybe the difference of protocol(http and ftp)?
Anyway, Inconsistent behavior about percent encoded URLs is very unatural.

**Comment by wm4** [comment]
It's simple: http protocol does not allow spaces in URLs, but interprets percent encoding, while the ftp protocol is the opposite. (I'm quite sure about http, though I didn't check the ftp protocol.)

**Comment by wm4** [comment]
PS: I tried to change this directly in ffmpeg's http protocol once, but some cranky asshole ffmpeg dev took a shit all over it, and it developed into a big flamewar with no results.

**Comment by xylosper** [comment]
Oh, damn... Thank you. So, I have to know what protocol allows percent encoding and what doesn't. Do you happen to know such list?

**Comment by xylosper** [comment]
Oh, and do you have any plan to make it uniform in mpv side, if you think it's unnatural, too?

**Comment by ValdikSS** [comment]
@xylosper, percent encoding is used only by HTTP afaik.

@wm4, I suppose mpv should play HTTP URLs both urlencoded and not. I suppose, it's as easy as doing urldecode and again urlencode of the original URL.

**Comment by wm4** [comment]
>I suppose, it's as easy as doing urldecode and again urlencode of the original URL.

First we have to know whether an URL is http. There are many protocols that map to http, starting with https, and ending with obscure crap like mmsh.

Also, this kind of URL normalization (which is _always_ an heuristic) isn't that simple.

>Oh, and do you have any plan to make it uniform in mpv side, if you think it's unnatural, too?

Sure, I just don't know yet how exactly. A solution that handles "most" cases would probably be enough, like http/https and URLs with spaces.

**Comment by wm4** [comment]
Original ffmpeg patch & discussion:

https://ffmpeg.org/pipermail/ffmpeg-devel/2014-January/153849.html
https://ffmpeg.org/pipermail/ffmpeg-devel/2014-February/153882.html

**Comment by wm4** [comment]
> I suppose, it's as easy as doing urldecode and again urlencode of the original URL.

OK, now I remember why this doesn't work. You can't distinguish "unreserved" characters like ``/`` from escaped ones.

**Comment by wm4** [comment]
Done, I hope it doesn't break anything.

Doesn't touch handling of ftp URLs.

**Comment by xylosper** [comment]
Okay, it looks working. Thank you!

**Comment by ValdikSS** [comment]
When opening any file from FTP with mpv which contains anything that could be percent encoded, mpv won't load that. This is very annoying since KDE Dolphin (and kio I suppose) use percent encoding even with FTP.

```
% mpv 'ftp://serv.valdikss.org.ru:21/Serials/_Animated%20Series/Stripperella/01.Beauty%20and%20the%20Obese%20(part1).avi'
Playing: ftp://serv.valdikss.org.ru:21/Serials/_Animated%20Series/Stripperella/01.Beauty%20and%20the%20Obese%20(part1).avi
Failed to recognize file format.


Exiting... (Errors when loading file)
```

Could this be fixed or should I fire a bug to KDE?

**Comment by qmega** [comment]
This is the workaround I use for SFTP (I also use Dolphin):
```python
#!/usr/bin/env python

# Wrapper for mpv to decode SFTP URLs, because KDE gives them to us
# encoded but ffmpeg wants them plain.

from sys import argv
from urllib.parse import unquote
from os import execv

MPV = '/usr/bin/mpv'

execv(MPV, [MPV] + [
    unquote(url) if url.startswith('sftp://') else url for url in argv[1:]
])
```
You could replace the `sftp` with `ftp` or `url.startswith('ftp://') or url.startswith('sftp://')`.

Still might be a KDE bug, though, if (S)FTP urls aren't supposed to be encoded.

**Comment by wm4** [comment]
> if (S)FTP urls aren't supposed to be encoded.

I have no ideas whether they are. Since mpv uses URLs for a lot of things, they are generally not URL-decoded to avoid confusion. It's also not clear what the heck FFmpeg does (which implements the FTP protocol).

**Comment by ValdikSS** [comment]
ffmpeg does not unquote URL.

```
% ffplay ftp://serv.valdikss.org.ru:21/Serials/_Animated%20Series/Stripperella/01.Beauty%20and%20the%20Obese%20(part1).avi
ffplay version 2.7.1 Copyright (c) 2003-2015 the FFmpeg developers
  built with gcc 5.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-shared --enable-version3 --enable-x11grab
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
[avi @ 0x7fed30004ac0] Format avi detected only with low score of 1, misdetection possible!
ftp://serv.valdikss.org.ru:21/Serials/_Animated%20Series/Stripperella/01.Beauty%20and%20the%20Obese%20(part1).avi: Invalid data found when processing input


% ffplay 'ftp://serv.valdikss.org.ru:21/Serials/_Animated Series/Stripperella/01.Beauty and the Obese (part1).avi'
ffplay version 2.7.1 Copyright (c) 2003-2015 the FFmpeg developers
  built with gcc 5.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-shared --enable-version3 --enable-x11grab
  libavutil      54. 27.100 / 54. 27.100
  libavcodec     56. 41.100 / 56. 41.100
  libavformat    56. 36.100 / 56. 36.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 16.101 /  5. 16.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, avi, from 'ftp://serv.valdikss.org.ru:21/Serials/_Animated Series/Stripperella/01.Beauty and the Obese (part1).avi':
  Metadata:
    encoder         : VirtualDubMod 1.5.10.2 (build 2540/release)
  Duration: 00:19:53.93, start: 0.000000, bitrate: 2397 kb/s
    Stream #0:0: Video: mpeg4 (Advanced Simple Profile) (XVID / 0x44495658), yuv420p, 720x400 [SAR 1:1 DAR 9:5], 1995 kb/s, 29.97 fps, 29.97 tbr, 29.97 tbn, 29.98 tbc
    Stream #0:1: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 192 kb/s
    Stream #0:2: Audio: ac3 ([0] [0][0] / 0x2000), 48000 Hz, stereo, fltp, 192 kb/s
…
```

**Comment by konaya** [comment]
FWIW, mplayer will unquote an FTP URL.
