### ISSUE TITLE
Hardware decode not working on M1 mac for h264 10 bit 4:2:2

### ISSUE THREAD

**Issue by AndrewKeYanzhe** [mpv-player/mpv#14957]
### mpv Information

```bash
mpv c11239b Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 30 2024 09:32:31
libplacebo version: v7.349.0
FFmpeg version: 7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

```text
- macOS version:14.4.1 (23E224)
- Source of mpv:https://github.com/mpv-player/mpv/actions/runs/11103272869
- Introduced in version:
```

### Reproduction Steps

1. Play a h264 10 bit 4:2:2 from the Panasonic Lumix S5ii
2. Use the config --hwdec=videotoolbox --hwdec-codecs=all 

### Expected Behavior

MPV shift+i shows HW: videotoolbox. CPU usage is ~7%. This behaviour occurs for h265, vp9 files. 

Quicktime also plays the same h264 10 bit 422 file with 7% cpu usage.

### Actual Behavior

When playing the h264 10 bit 4:2:2 file from the Lumix S5ii, shift+i does not show HW: videotoolbox. CPU usage is ~37%
<img width="1728" alt="Screenshot 2024-10-01 at 02 19 20" src="https://github.com/user-attachments/assets/be75c4c5-c875-4277-994b-60b25f33df69">

### Log File

[mpv.log](https://github.com/user-attachments/files/17194533/mpv.log)

### Sample Files

Sample h264 10 bit 422 file from Lumix S5ii
https://drive.google.com/file/d/1L8mlk10chMrq7TSvxVoAT048TTHqvF8x/view?usp=drive_link

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Akemi** [comment]
your log is incomplete.

ffmpeg throws a lot of failed to decode errors, `ffmpeg -hwaccel videotoolbox -i P1109555.MOV -f null -`

```
...
[h264 @ 0x14df0bef0] vt decoder cb: output image buffer is null: -12909
[h264 @ 0x14df2ee50] hardware accelerator failed to decode picture
[vist#0:0/h264 @ 0x14df125a0] [dec:h264 @ 0x14df0af00] Error submitting packet to decoder: Unknown error occurred
[h264 @ 0x14df0bef0] vt decoder cb: output image buffer is null: -12909
[h264 @ 0x14df37870] hardware accelerator failed to decode picture
[vist#0:0/h264 @ 0x14df125a0] [dec:h264 @ 0x14df0af00] Error submitting packet to decoder: Unknown error occurred
[h264 @ 0x14df0bef0] vt decoder cb: output image buffer is null: -12909
[h264 @ 0x14df40290] hardware accelerator failed to decode picture
[vist#0:0/h264 @ 0x14df125a0] [dec:h264 @ 0x14df0af00] Error submitting packet to decoder: Unknown error occurred
...
```

using `--vd-lavc-software-fallback=no` (just for testing to deactivate the software fallback, which likely happens due to the errors), does force hwdec but is unwatchable due to the decoding errors (we get the same as ffmpeg).

```
...
Error while decoding frame (hardware decoding)!      
[ffmpeg/video] h264: vt decoder cb: output image buffer is null: -12909
[ffmpeg/video] h264: hardware accelerator failed to decode picture
Error while decoding frame (hardware decoding)!      
[ffmpeg/video] h264: vt decoder cb: output image buffer is null: -12909
[ffmpeg/video] h264: hardware accelerator failed to decode picture
Error while decoding frame (hardware decoding)!      
[ffmpeg/video] h264: vt decoder cb: output image buffer is null: -12909
[ffmpeg/video] h264: hardware accelerator failed to decode picture
Error while decoding frame (hardware decoding)! 
...
```

this is a ffmpeg issue, please report this to them.
