### ISSUE TITLE
enhance Active Key Bindings' filter

### ISSUE THREAD

**Issue by VimWei** [mpv-player/mpv#14966]
## Active Key Bindings's issue

`Page 4 also binds / to search for input bindings by typing part of a binding or command.`
from https://mpv.io/manual/stable/#stats  

Currently, if the filter results are too numerous to fit on a single page, there's no mechanism to browse through the remaining results.

## Improvement Suggestions:

1. **Implement a Navigation Mechanism for Filter Results**: Introduce a way to navigate through paginated filter results, potentially using modifier keys in combination with other shortcuts. For example:

- `Ctrl + Down Arrow` to move to the next page of results.
- `Ctrl + Up Arrow` to move to the previous page of results.

2. **Enable Filtering of Comments**: Allow users to filter items based on the content of their comments. This would be particularly helpful when defining keybindings in input.conf or similar configuration files. Users could add specific keywords to their comments and easily retrieve those keybindings later using the filter. For example:

- g-g seek 0 absolute-percent # vim-like
- G seek 100 absolute-percent # vim-like
- ctrl+h no-osd seek -1 exact # vim-like
- ctrl+l no-osd seek 1 exact # vim-like
- ctrl+j no-osd seek 5 exact # vim-like
- ctrl+k no-osd seek -5 exact # vim-like
- ctrl+d seek 30 # vim-like
- ctrl+u seek -30 # vim-like
- ctrl+f seek 60 # vim-like
- ctrl+b seek -60 # vim-like

Then, we can filter this by "vim-like".

**Comment by guidocella** [comment]
`g-b` has better input bindings search with fuzzy finding and keyboard navigation. I wasn't sure whether to put the comments there too.

**Comment by VimWei** [comment]
At the same time, I would like to be able to directly access a persistent Active Key Bindings page through a shortcut key. This would allow me ample time to further use features like filter to look up information.

Currently, I can only use the following definition in input.conf: ? script-binding stats/display-page-4

I wish there could be a definition similar to this: ? script-binding stats/display-page-4-toggle

The desired functionality is similar to how the uppercase 'I' key works in mpv, which toggles the persistent display of the stats page, as opposed to the lowercase 'i' key, which only shows the stats briefly.

**Comment by VimWei** [comment]
> `g-b` has better input bindings search with fuzzy finding and keyboard navigation. I wasn't sure whether to put the comments there too.

Thanks! Though 'g-b' can solve some of the issues, its overall experience is not as user-friendly as Active Key Bindings.

**Comment by guidocella** [comment]
stats.lua doesn't have page up and down bindings because we don't know how many lines fill one page as mpv doesn't use a real GUI library. The linked PR implements every other request.

**Comment by VimWei** [comment]
Thank you! 

I have tested the artifacts of the pull request, and it works perfectly. 

It not only exceeded my initial expectations (by using up/down keys and maintaining consistency with the overall experience; it also added the ESC key for convenient exit), but the response speed is also incredibly fast. 

Kudos to your excellent efforts!
