### ISSUE TITLE
Add secondary-sub-reload [<id>]

### ISSUE THREAD

**Issue by VimWei** [mpv-player/mpv#14987]
### Expected behavior of the wanted feature

There is an a.srt file (with sid 1) loaded as the primary subtitle, and a b.srt file (with sid 2) loaded as the secondary subtitle.

If you use the `sub-reload 2` command, the a.srt file would disappear, and the b.srt file would change from being the secondary subtitle to becoming the primary subtitle.

However, what you want is for the a.srt file to remain as the primary subtitle, and the b.srt file to remain as the secondary subtitle. But you are unable to achieve that.

Therefore, you wish there was a `secondary-sub-reload [<id>]` command, which would allow you to reload the secondary subtitle without affecting the primary subtitle.

**Comment by VimWei** [comment]
* write a lua script: dualsubs-reload.lua 
https://github.com/VimWei/mpv-config

**Comment by ptr7F** [comment]
Hi, I’d like to kindly follow up on this feature request.
Reloading secondary subtitles without affecting the primary one would be very useful in scenarios such as bilingual subtitle learning, where the primary subtitle must remain stable while the secondary one is frequently updated.
Could this feature be considered, maybe as `secondary-sub-reload [<id>]` or as an extension to sub-reload with an option?
