### ISSUE TITLE
Mpv does not play some channels in m3u list, it works fine in kodi and vlc

### ISSUE THREAD

**Issue by dbojan** [mpv-player/mpv#15002]
### mpv Information

```bash
mpv v0.38.0-771-gef19a4a0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 15 2024 00:08:43
libplacebo version: v7.349.0 (v7.349.0-10-g76bb971-dirty)
FFmpeg version: N-117040-g3f84d1d1f
FFmpeg library versions:
   libavcodec      61.13.100
   libavdevice     61.2.101
   libavfilter     10.2.102
   libavformat     61.5.101
   libavutil       59.36.100
   libswresample   5.2.100
   libswscale      8.2.100
```

### Other Information

```text
- Windows version: Microsoft Windows [Version 6.3.9600]
- GPU model, driver and version: Nvidia GTX 750
- Source of mpv: https://github.com/shinchiro/mpv-winbuild-cmake/releases
- Introduced in version: ?
```

### Reproduction Steps

d:\apps\mpv\mpv --no-config "mylist.m3u"

use arrows at the bottom left of the window to go through channels.

### Expected Behavior

Displaying video from the streaming channels

### Actual Behavior
3 channels are included.
2nd and the 3rd channels were skipped (not played)

The list works fine in Kodi and VLC.
Here is the relevant part of the m3u list, with second and third channel:

#EXTM3U 
...
#EXTINF:-1  tvg-id="xx" tvg-logo="https://i.imgur.com/xx.png" ,xxxx
#EXTVLCOPT:http-user-agent=Android
http://123...../index.m3u8
#EXTINF:-1 tvg-id="x" ,Name
#EXTVLCOPT:http-referrer=https://www.someadress.com
https://live.address.com/something.m3u

### Log File

[output.txt](https://github.com/user-attachments/files/17269287/output.txt)

### Sample Files

[2.zip](https://github.com/user-attachments/files/17269291/2.zip)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Works if you manually set `--referrer="https://www.tvbalkanuzivo.com" --user-agent="Android"`. 

mpv doesn't support `EXTVLCOPT` or any other home-grown m3u extensions other players might use.

**Comment by dbojan** [comment]
I cant manually set different referrer for each channel, especially on other platforms, like android.
