### ISSUE TITLE
Keys received from wtype get changed to ESC

### ISSUE THREAD

**Issue by lord-re** [mpv-player/mpv#15022]
### mpv Information

```bash
mpv v0.38.0-791-g22620af459 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0 (v7.349.0-rc1-2-gbc9de9c7-dirty)
FFmpeg version: 6.1.2
FFmpeg library versions:
   libavcodec      60.31.102
   libavdevice     60.3.100
   libavfilter     9.12.100
   libavformat     60.16.100
   libavutil       58.29.100
   libswresample   4.12.100
   libswscale      7.5.100
```

### Other Information

```text
- Linux Version : up to date Gentoo
- Window Manager and Version: sway
- Introduced in version: ?
```

### Reproduction Steps

Sending keypresses to the video window with **wtype** doesn't work. Every key is read as **Escape**.

Launch ** mpv --idle --input-test --force-window --no-config** then in another terminal **sleep 3 ; wtype -k Space** 
  - hover the terminal launching mpv : it works as expected
  - hover the video window : «[input] Key ESC is bound to:»

### Expected Behavior

It should read the Space key and so pause the player.

### Actual Behavior

It exits fullscreen as it reads Escape instead of Space.

### Log File

[mpv.log](https://github.com/user-attachments/files/17293758/mpv.log)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Bisected to https://github.com/mpv-player/mpv/commit/2274311b259b7b03e3764ab4c21d69988b70a337

**Comment by lord-re** [comment]
Thanks a lot 🫶 

That was so fast, it works perfectly !
