### ISSUE TITLE
geometry - wrong starting position

### ISSUE THREAD

**Issue by xvim64** [mpv-player/mpv#15043]
### mpv Information

```bash
https://github.com/shinchiro/mpv-winbuild-cmake/releases

mpv-x86_64-v3-20241006-git-9791c6d.7z  // introduced
~
mpv-x86_64-v3-20241010-git-e09278c.7z  // ongoing
```

### Other Information

```text
- Windows version: Windows 11 24H2

- Source of mpv: mpv-x86_64-v3-20241010-git-e09278c.7z

https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20241010/mpv-x86_64-v3-20241010-git-e09278c.7z

- Introduced in version: mpv-x86_64-v3-20241006-git-9791c6d.7z

https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20241006/mpv-x86_64-v3-20241006-git-9791c6d.7z
```

### Reproduction Steps

mpv --no-config --geometry=800x800 test.mp4

// mpv-x86_64-v3-20241005-git-493cab7.7z
Center at mpv startup
![1005](https://github.com/user-attachments/assets/c04067fd-d6a9-484c-a8a1-1980bd08acdc)

// mpv-x86_64-v3-20241006-git-9791c6d.7z ~ mpv-x86_64-v3-20241010-git-e09278c.7z
No center at mpv startup
![1010](https://github.com/user-attachments/assets/93afba54-7051-49cc-89fd-722133a313d7)

mpv --no-config --geometry=3840x2160 test.mp4

// mpv-x86_64-v3-20241006-git-9791c6d.7z ~ mpv-x86_64-v3-20241010-git-e09278c.7z
No center & outside of the screen at mpv startup
![10104k](https://github.com/user-attachments/assets/ed988007-ccbd-4404-b9c5-2133b882fe52)

### Expected Behavior

Center at startup with geometry=800x800

### Actual Behavior

No center at startup with geometry=800x800 from mpv-x86_64-v3-20241006-git-9791c6d.7z

### Log File

None

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [x] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
> change `--geometry` so that it no longer unconditionally moves the window on platforms where that is possible. Use `--force-window-position` or add `+50%+50%` to your geometry command to get the old behavior back.

See: https://github.com/mpv-player/mpv/commit/e01eab4385d8fe6a542dd9526f912e37b691f58e

**Comment by Dudemanguy** [comment]
I made sure in x11 that it would center the window on startup but not subsequent runtime changes.

**Comment by kasper93** [comment]
> I made sure in x11 that it would center the window on startup but not subsequent runtime changes.

huh, It doesn't seem consistent. Should I add also this workaround to Windows?

**Comment by Dudemanguy** [comment]
I thought that was desirable. People usually want windows to open up on the center.

**Comment by kasper93** [comment]
Ok, I will change that, I though your commit was removing centering window when using geometry on purpose.

**Comment by Dudemanguy** [comment]
It does but just not 100% of the time like it used to.

**Comment by Akemi** [comment]
> I made sure in x11 that it would center the window on startup but not subsequent runtime changes.

same for me on macOS btw.

**Comment by Lonely233233** [comment]
The best solution for now is to comment out geometry and use autofit-larger=60% alone

**Comment by xvim64** [comment]
> When opening a vertically oriented video, it's still not centered. Version number: 20241011

Opened this issues --> https://github.com/mpv-player/mpv/issues/15053
