### ISSUE TITLE
Right click to pause and play bug

### ISSUE THREAD

**Issue by jadetexy** [mpv-player/mpv#15045]
### Other Information

```text
- Windows version:
- GPU model, driver and version:
- Source of mpv:
- Introduced in version:
```

### Reproduction Steps

Please test the bug in the development team where right clicking during video playback loops between pauses. After testing multiple times, it was found that right clicking during playback cannot pause, and similarly, right clicking during pause cannot play

### Expected Behavior

Right click to pause or play

### Actual Behavior

Right clicking cannot pause or play, appearing as if double clicking twice resulted in no change in status

### Log File

Please test

### Sample Files

Please test

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by CounterPillow** [comment]
Can't reproduce the problem you describe. Since you provided no information to prove that the bug exists, I assume you are lying and made it all up.

**Comment by kasper93** [comment]
Thank you @CounterPillow for testing.
