### ISSUE TITLE
Video Display Problem on Portrait Mode Monitor (1200x1980)

### ISSUE THREAD

**Issue by CharlesMengCA** [mpv-player/mpv#15049]
### mpv Information

```bash
mpv 0.39.0-101-g3b95c00d Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on 2024-10-10 1:55 PM
libplacebo version: v7.349.0
FFmpeg version: git-2024-10-10-7bb283aa7
FFmpeg library versions:
   libavcodec      61.22.100
   libavdevice     61.4.100
   libavfilter     10.6.100
   libavformat     61.9.100
   libavutil       59.42.100
   libswresample   5.4.100
   libswscale      8.5.100
```

### Other Information

```text
- Windows version: Microsoft Windows [Version 10.0.19045.5011]
- GPU model, driver and version: NVIDIA GTX 1650 SUPER, Version 565.90
- Source of mpv: master branch
- Introduced in version: https://github.com/mpv-player/mpv/commit/e5159de8118120163689c27f5cbc1ec68c2d27c8
```

### Reproduction Steps

mpv --screen=2 "e:\161223 JSJ Belly Dance Team Lim Seong-mi-Heart of Percussion Belly Dance Performance (Jungnang Club Madang Christmas Festival Jungnang East Market).webm" --no-config

### Expected Behavior

Tile and Video display correctly like following screenshot:

![Working](https://github.com/user-attachments/assets/c839d3f9-2039-41f7-acb8-39676ac1d7da)

### Actual Behavior

The title is out of screen; has black edge on left and right sides.

![TitleMissing](https://github.com/user-attachments/assets/37ab847f-7a5a-4739-b178-0be35a192419)

### Log File

[output.txt](https://github.com/user-attachments/files/17334973/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
@CharlesMengCA: Does this work for you #15049?

**Comment by CharlesMengCA** [comment]
The fix is working. Thanks.
