### ISSUE TITLE
Unable to know if a captured stream will be playable

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1504]
With mplayer, i used to query the demuxer property, and if it returned *mpeg** i considered the stream right to be captured.
```
# mplayer -demuxer help |grep mpeg
    mpegts  29   MPEG-TS demuxer
    mpegps   2   MPEG PS demuxer (Mpeg)
   mpegpes  41   MPEG PES demuxer (Mpeg)
    mpeges   1   MPEG ES demuxer (Mpeg)
   mpeggxf  42   MPEG ES in GXF demuxer (Mpeg)
   mpeg4es  27   MPEG4 ES demuxer (Mpeg)
```
With mpv, those demuxers are gone (right?), and lavf is used instead.
Is there a way to know if capturing a stream could produce playable files in advance with mpv?

**Comment by wm4** [comment]
We could just export the file format name (as given by ffmpeg).

**Comment by wm4** [comment]
>With mpv, those demuxers are gone (right?), and lavf is used instead.

And yes to this question.

**Comment by kokoko3k** [comment]
Yes, that would be great, thank you.

And as a side note, i really appreciate the speed of the replies :+1:

**Comment by wm4** [comment]
Done; I didn't actually test my commit, can you confirm it's what you want?

**Comment by kokoko3k** [comment]
I tried with a simple mpg file and a ts one and it seems to work well, thank you.
