### ISSUE TITLE
Skip to black frame

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1507]
One user requested this feature.

In most case, black frame is inserted on transition of scene.
So, if the video lacks chapter information, skipping to next black frame would be helpful feature , for instance to skip intro.

This requires 'scanning frames' instead of 'seeking', timeout for skipping is neccesary, for instance, find black frame in next 5min pts frames.

Also, lots of video contains some kind of logo even if it's black frame, so it's meaningless to find only totally black frame in such case.
It's needed to calculate the average brightness(average of Y in PC level) and compare it to some criteria.

During skipping frames, as another feature, it will be nice to display some intermediate frames.

I'm doing this with some crippy hack in my application(inserting a dummy video filter and calculate brightness with 100 times playback speed in muted) , I think this is more easy job for decoder.

**Comment by wm4** [comment]
Uh, sounds like a complicated and crappy feature. I think a video filter could actually handle this on its own; it'd just require extra hackery for hw decoding.

**Comment by wm4** [comment]
PS: also, hw decoding could just be disabled while doing this; the problem is just switching between sw and hw.

**Comment by xylosper** [comment]
> I think a video filter could actually handle this on its own

By manipulating PTS of video frame? But still it's needed to handle audio (mute or whatever, I can see anyway to set it from video filter).

> PS: also, hw decoding could just be disabled while doing this; the problem is just switching between sw and hw.

I assumed it's still way faster to download hwdec image instead of using swdec from my experience of hwdec=vaapi-copy and hwdec=no, and this is very performance critical feature because this feature requires the best speed of decoder.

**Comment by wm4** [comment]
>By manipulating PTS of video frame? But still it's needed to handle audio (mute or whatever, I can see anyway to set it from video filter).

No. It knows when a seek happens (VFCTRL_RESET or so), and then it just needs to throw away every frame until the "seek target" is reached. The player will always sync audio to video start. (Though it could happen that the packet queue overflows if a lot of video is skipped; it doesn't decode the audio while skipping video. Also, once the seek finishes, it'll decode the audio all at once, which could cause a delay.)

**Comment by xylosper** [comment]
> it just needs to throw away every frame until the "seek target" is reached.

As a matter of fact, that was my first implemetation. and...

> The player will always sync audio to video start. (Though it could happen that the packet queue overflows if a lot of video is skipped; it doesn't decode the audio while skipping video.

maybe this is related, when I skipped many frames in vf, the filter got same PTS frame only as input and some mpeg error message is printed (I don't remember what it was, sorry).

> Also, once the seek finishes, it'll decode the audio all at once, which could cause a delay

Yes, so I muted the audio, and scanned, and enforced to seek to PTS of black frame, and unmuted.

**Comment by wm4** [comment]
For the sake of screenshots, there's now a way a filter could actually convert a hwdec image to a CPU image.

**Comment by lachs0r** [comment]
See “skiptofade” at https://github.com/mpv-player/mpv/wiki/User-Scripts
