### ISSUE TITLE
The available 32-bit file is corrupted.

### ISSUE THREAD

**Issue by ofernandofilo** [mpv-player/mpv#1509]
The available files are corrupted:
mpv-i686-latest.7z
mpv-i686-20150123.7z

Cheers

**Comment by lachs0r** [comment]
Try to use an archiver that is not more than five years out of date.

**Comment by ofernandofilo** [comment]
¬¬

I tried with WinRAR 5.10, WinRAR 5.20, 7zip 9.20 and they all said that is corrupt the file.

The same software open the 64 bit files without no trouble, but not the 32 bit version!

**Comment by lachs0r** [comment]
Well sorry about that comment then. However, I’ve only posted it after 
downloading and extracting the files myself to verify that they are not 
broken.

**Comment by ofernandofilo** [comment]
The same with PeaZip 5.5.3.

Please, if you, sir, use a different software that works with this file please inform.

--

[Window Title]
Warning

[Content]
Some input files cannot be read (may be locked, not accessible or corrupted)
The archive may require a different password for the current operation
For more details, "Report" contains the task's log, and "Console" contains the task definition as command line.

[OK]

**Comment by lachs0r** [comment]
Did you try redownloading with a different browser? The files are definitely 
fine, and the software versions you are using should work.

**Comment by ofernandofilo** [comment]
I'm sorry, apparently the problem was my Avast antivirus.

Yes, I tried several times. I used Google Chrome and Palemoon.

However, I tried with my laptop and it worked.

So I disabled Avast, downloaded again and worked on the desktop as well.

I still do not know what happened and why corrupted only the 32-bit version, but not the 64-bit version.

Finally, I noticed that when Avast is enabled, the downloaded file missing 2KB the compressed file without any error message or viruses by Avast.

http://oi60.tinypic.com/314aueg.jpg

Thank you for your attention.

**Comment by lachs0r** [comment]
Should be noted that Avast also has a false positive on the 64-bit executable. 
I don’t know why.

Just use Windows Defender and common sense tbh. Most third party AV software 
is itself really just malware.

**Comment by ofernandofilo** [comment]
I will post only the hashes of the files for those who have the same problem as me.

Thanks and cheers!

REAL FILE:
CRC32: 84A7D80B
MD5: 95D05AD13F6F86041E0E7B985832D778
SHA-1: 65AD1D5647BAE29DEBF05F0F5E9EAC1A5AD0B07E

CORRUPTED FILE:
CRC32: C19803AE
MD5: 3ABE2C57D041B365DD6A0930C3A64151
SHA-1: 48C917B34A6339C2D7AFF8B5B351B4A0C3297457
