### ISSUE TITLE
Inconsistent window controls behavior after fullscreen toggle with maximize

### ISSUE THREAD

**Issue by Samillion** [mpv-player/mpv#15093]
### mpv Information

```bash
mpv v0.39.0-113-g228f3860 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Oct 13 2024 00:08:22
libplacebo version: v7.349.0 (v7.349.0-15-g756220c-dirty)
FFmpeg version: N-117481-g02306cbfe
FFmpeg library versions:
   libavcodec      61.22.100
   libavdevice     61.4.100
   libavfilter     10.6.100
   libavformat     61.9.100
   libavutil       59.42.100
   libswresample   5.4.100
   libswscale      8.5.100
```

### Other Information

```text
- Windows version: Windowx 10 x64
- GPU model, driver and version: Nvidia GTX 660, v475.14
- Source of mpv: https://sourceforge.net/projects/mpv-player-windows/files/
- Introduced in version: Found on v0.39, not sure since when
```

### Reproduction Steps

To reproduce, do the following:
- `mpv video.mp4 --no-border --no-config`
- Maximize => Fullscreen => Unmaximize
- Maximize => Unmiximize (now requires two clicks)

### Expected Behavior

Unmaximize in one click

### Actual Behavior

Unmaximize needs two clicks.

- First click maximizes a couple of pixels
- Second click actually unmaxmizes.

### Log File

Log [output.txt](https://github.com/user-attachments/files/17369303/output.txt)

This was originally reported on my OSC fork repo, which contains more videos and logs: 
https://github.com/Samillion/ModernZ/issues/18

### Sample Files

Preview of the behavior in action:

https://github.com/user-attachments/assets/7f534238-7088-4e10-89b3-78ff293ce9ff

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Samillion** [comment]
I forgot to note that "Maximize" behavior after that stays the same, requiring two clicks to maximize.

**Comment by kasper93** [comment]
Why close this? It is valid issue.

**Comment by Samillion** [comment]
It honestly felt like a very specific scenario tiny issue. You guys already have a truckload, thought I'd lessen the burden of thought since it's not really breaking any function.

Re-opening.
