### ISSUE TITLE
The property "media-title" and "alang" seems to work wrong

### ISSUE THREAD

**Issue by 1000Fear** [mpv-player/mpv#15092]
### mpv Information

```bash
mpv v0.39.0-113-g228f3860 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Oct 13 2024 00:08:17
libplacebo version: v7.349.0 (v7.349.0-15-g756220c-dirty)
FFmpeg version: N-117481-g02306cbfe
FFmpeg library versions:
   libavcodec      61.22.100
   libavdevice     61.4.100
   libavfilter     10.6.100
   libavformat     61.9.100
   libavutil       59.42.100
   libswresample   5.4.100
   libswscale      8.5.100
```

### Other Information

```text
- Windows version: Microsoft Windows NT 10.0.19045.0/19045.4412
- GPU model: NVIDIA GTX 1080Ti 
- GPU driver and version: Studio Driver 561.09
```

### Test File Information:

> Title: TEST
> Audio 1 (Default Track)
>     Language: en
> Audio 2
>     Language: zh
> _(I think other information is not important, so I will omit it.)_
> 

I made two copies of the file: `TEST.mkv` and `1.mkv` for comparison. The hash values are the same; only the filenames are different. Here is the `mpv.conf`:

> alang=auto  
> geometry=1920x1080  
> volume=100  
> 
> [TEST]  
> profile-cond=media_title:find('TEST')  
> #profile-cond=get("metadata/by-key/title"):find('TEST')  
> alang=zh  
> geometry=960x540  
> volume=50

### Scenario 1:
When I set `profile-cond=media_title:find('TEST')`:
    Opening 1.mkv, the `geometry` and `volume` settings were applied, but `alang` was not.
      `geometry=960x540`, `volume=50`, `alang=en`
    Opening TEST.mkv, the `geometry`, `volume`, and `alang` were all applied.
      `geometry=960x540`, `volume=50`, `alang=zh`

### Scenario 2:
When I set `profile-cond=media_title:find('1')`:
    Opening 1.mkv, the `geometry`, `volume`, and `alang` were all applied.
    `geometry=960x540`, `volume=50`, `alang=zh`
    Opening TEST.mkv, none of the settings were applied.
    `geometry=1920x1080`, `volume=100`, `alang=en`

### Scenario 3:
When I set `profile-cond=get("metadata/by-key/title"):find('TEST')`:
    Both files behaved the same. The `geometry` and `volume` settings were applied, but `alang` was not.
    `geometry=960x540`, `volume=50`, `alang=en`

### Scenario 4:
When I set `profile-cond=get("metadata/by-key/title"):find('1')`:
    Both files behaved the same. None of the settings were applied.
    `geometry=1920x1080`, `volume=100`, `alang=en`

I think there is an issue with how `media-title` behaves (Scenarios 1 and 2) and with how `alang` is applied (Scenarios 1 and 3).
According to the manual, the behavior of media-title should be:

> If the currently played file has a title tag, use that. Otherwise, return the filename property.

However, in my controlled experiment, `media-title` seems to ignore the video file’s title tag (even it exists) and instead identifies and returns the filename (Scenario 2). When using `get("metadata/by-key/title")`, it correctly recognizes the title tag, but then `alang` doesn't apply (Scenario 3).
At the same time, I don’t understand why `alang` behaves differently from `geometry` and `volume`. In cases where the profile condition is met, `alang` is not applied, while the other settings are (Scenarios 1 and 3).

Here's the log files for each scenario, I get them with this command.
`mpv "E:\Replay\1.mkv" --log-file=C:\Users\1000Fear\Desktop\mpv.log`
[Scenario 1 (1.mkv).log](https://github.com/user-attachments/files/17368920/Scenario.1.1.mkv.log)
[Scenario 1 (TEST.mkv).log](https://github.com/user-attachments/files/17368921/Scenario.1.TEST.mkv.log)
[Scenario 2 (1.mkv).log](https://github.com/user-attachments/files/17368922/Scenario.2.1.mkv.log)
[Scenario 2 (TEST.mkv).log](https://github.com/user-attachments/files/17368923/Scenario.2.TEST.mkv.log)
[Scenario 3 (1.mkv).log](https://github.com/user-attachments/files/17368924/Scenario.3.1.mkv.log)
[Scenario 3 (TEST.mkv).log](https://github.com/user-attachments/files/17368925/Scenario.3.TEST.mkv.log)
[Scenario 4 (1.mkv).log](https://github.com/user-attachments/files/17368926/Scenario.4.1.mkv.log)
[Scenario 4 (TEST.mkv).log](https://github.com/user-attachments/files/17368927/Scenario.4.TEST.mkv.log)

Can you tell me if this is a bug, or is there something wrong with my configuration?
Let me know if you need any more information.

### Expected Behavior

I believe the expected behavior should be:
    Scenarios 1 and 3: `geometry`, `volume`, and `alang` should all be applied.
    Scenarios 2 and 4: None of the settings should be applied.

### Actual Behavior

see Reproduction Steps

### Log File

see Reproduction Steps

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [x] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
Scenario 1 and 3 logs show that `--alang` is indeed applied, but it needs to be set before files load and their title becomes available for it to influence track selection. `profile-cond=media_title:find('1')` is true when `media-title` initially has the same value of `filename` before being updated with the title metadata when the file loads.

**Comment by guidocella** [comment]
It needs a script unless subtitles always have the same `sid` or you inline a script in the condition like in https://github.com/christoph-heinrich/mpv-subtitle-lines.

**Comment by guidocella** [comment]
Audio tracks can already be changed after the file is loaded with the `aid` property. `--alang` only has effect before that and I don't think making it change tracks while a file is playing was ever discussed. I don't see how you would obtain a file's metadata before loading it.

**Comment by guidocella** [comment]
Files are loaded, then tracks and metadata are read, then playback starts. Also metadata can be contained in the individual streams which are decided with track selection.
