### ISSUE TITLE
No OSC/OSD with --force-window on Os X

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#1510]
The culprit seems to be commit 2858232. With audio only files and force-window, mpv works normally but it doesn't display neither OSC or OSD.
Note that  the OSC seems to be present and working although invisible: if I click where the seekbar should be, the player seeks as expected.

When in fullscreen, also, the window appears grey instead of the usual black, and in this case, unlike before, OSC is totally absent (no seeking if I click in the seekbar zone).

There are no message on the terminal window, but if you need it I'll log and post the output in verbose mode.

**Comment by wm4** [comment]
Yep, I broke that on all platforms.
