### ISSUE TITLE
(Hosting request) Create a Radicle backup and mirror to protect your development

### ISSUE THREAD

**Issue by hardBSDk** [mpv-player/mpv#15112]
### Expected behavior of the wanted feature

[Radicle](https://radicle.xyz/) is a platform for peer-to-peer Git repositories, your repository works like a torrent where anyone can be a seeder of your code.

This will increase the download speed, add a backup and protect the project from GitHub problems.

**Comment by CounterPillow** [comment]
Thanks for submitting commercial spam. However, mpv already can be mirrored by anyone as per the terms of the license, there is no need to bother the repo owners about this, and it's quite clear that you're only doing this to drive traffic to your website.

**Comment by hardBSDk** [comment]
"Commercial spam"

You said lies, I don't have a relation with Radicle.

Very educated.

**Comment by llyyr** [comment]
> You said lies, I don't have a relation with Radicle.

![image](https://github.com/user-attachments/assets/314ea3bb-53ea-4309-b293-aeac37220894)

Certainly aren't making it easy for other people to know that. The point stands, git is decentralized as it is. you can `git clone` the repo then distribute in whatever way you want.
