### ISSUE TITLE
youtube-dl: add support for audio-only option

### ISSUE THREAD

**Issue by Tratoschek** [mpv-player/mpv#1511]
Youtube seems to have the ability to download only the audio track. This saves bitrate at downloading and the resulting audio track seems to have actually a higher bitrate then the extracted one of the video.

It would be nice, if you could add the behaviour, that if you type something like:
mpv --ytdl "https://linktovideo" -vo null
that then mpv automatically uses the audio-only link. In youtube-dl this could be achieved when using the -x flag.

**Comment by wm4** [comment]
If you use --no-video, I think this should already work if you use a DASH format.

**Comment by Tratoschek** [comment]
Hmm, you are right. It takes some time to load (~10 sec than with video). I tried with bestaudio and m4a:
$ mpv 'https://www.youtube.com/watch?v=HBSgpIolBfs' --no-video --ytdl-format=bestaudio
Playing: https://www.youtube.com/watch?v=HBSgpIolBfs
[ytdl_hook] WARNING: video doesn't have subtitles
[cache] Cache is not responding - slow/stuck network connection?
[cache] Cache is not responding - slow/stuck network connection?
[cache] Cache is not responding - slow/stuck network connection?
[cache] Cache is not responding - slow/stuck network connection?
 (+) Audio --aid=1 --alang=und (*) (aac)

Is it an option, to activate it per default if the --no-video flag is set? ATM, only setting --no-video results in this:
$ mpv 'https://www.youtube.com/watch?v=HBSgpIolBfs' --no-video
[ytdl_hook] WARNING: video doesn't have subtitles
     Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)

**Comment by robin007bond** [comment]
Can this one be closed?

**Comment by wm4** [comment]
Yep.
