### ISSUE TITLE
Certain video files refuse to run on hardware decoder

### ISSUE THREAD

**Issue by forthrin** [mpv-player/mpv#15128]
### mpv Information

```bash
mpv version: git-2024-10-16-e404426-dirty
FFmpeg version: git-2024-10-05-099f88b
```

### Reproduction Steps

`$ mpv 1.mp4`

(File is only a single video frame, which is all it takes to provoke the issue.)

Possibly related to #3318 and #559.

### Expected Behavior

Hardware decoding should work.

If the file is broken:

1. What specifically is broken? Was it encoded in an incorrect way?
1. Is there any utility that can repair the file without recoding the entire video stream?

### Actual Behavior

File falls back to software decoder. (This has happened for several other files over the years.)

```txt
$ mpv 1.mp4
mpv(41676,0x1fdda7240) malloc: nano zone abandoned due to inability to reserve vm space.
* Video  --vid=1  (h264 1920x1080 25 fps) [default]
[ffmpeg/video] h264: Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.
[ffmpeg/video] h264: number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
[ffmpeg/video] h264: Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.
[ffmpeg/video] h264: number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
[ffmpeg/video] h264: number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
VO: [libmpv] 1920x1080 yuv420p
V: 00.040 / 00.040 (100%)
Exiting... (End of file)
```

### Log File

N/A

### Sample Files

https://github.com/user-attachments/assets/b5fe10d9-2200-4875-b92a-4f62daa876dc

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
Can you reproduce with `ffmpeg -hwaccel videotoolbox -i 1.mp4 -f null /dev/null`?

**Comment by Akemi** [comment]
this is an ffmpeg problem, if at all. please report it upstream.

```
akemi@Mac-Studio ~ % ffmpeg -hwaccel videotoolbox -i 378104527-b5fe10d9-2200-4875-b92a-4f62daa876dc.mp4 -f null -
ffmpeg version 7.0.2 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.3.9.4)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.0.2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
[h264 @ 0x135704ee0] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/Akemi/Downloads/378104527-b5fe10d9-2200-4875-b92a-4f62daa876dc.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.9.100
  Duration: 00:00:00.04, start: 0.040000, bitrate: 7783 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 7596 kb/s, 25 fps, 25 tbr, 16k tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> wrapped_avframe (native))
Press [q] to stop, [?] for help
[h264 @ 0x135707480] Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.
[h264 @ 0x1357102c0] number of reference frames (0+5) exceeds max (4; probably corrupt input), discarding one
Output #0, null, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf61.1.100
  Stream #0:0(und): Video: wrapped_avframe, yuv420p(tv, bt709, top coded first (swapped)), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 25 fps, 25 tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
        encoder         : Lavc61.3.100 wrapped_avframe
[out#0/null @ 0x600002a94000] video:0KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
frame=    1 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.04 bitrate=N/A speed=0.545x    
```

**Comment by forthrin** [comment]
> Can you reproduce with `ffmpeg -hwaccel videotoolbox -i 1.mp4 -f null /dev/null`?

Thanks for chipping in. Same problem. Do you have any knowledge/forensics to attach to the upstream issue?

**Comment by Akemi** [comment]
usually ffmpeg would like you to provide a test file, the ffmpeg command you used/tested with and the output of it that command. but i believe that is what their issue tracker says when trying to open an issue.

**Comment by forthrin** [comment]
Responses haven't been very friendly or helpful when posting issues earlier, so passing unless their values have changed.

**Comment by Akemi** [comment]
> Responses haven't been very friendly or helpful when posting issues earlier, so passing unless their values have changed.

sry to hear that, though i can relate. some years ago i was reporting every videotoolbox issue reported to mpv upstream. even posted fixes to their mailing list. though was mostly ignored for months or even years, or met with unfounded 'resistance'. i stopped doing this after some time. sry this was probably a bit too much rambling.

**Comment by forthrin** [comment]
No, that's reassuring to hear. When even the team lead of the best video player is ignored, the best guess is (they think, at least) they are so on top of their own project they have no interest in outside intervention.

**Comment by llyyr** [comment]
> they are so on top of their own project they have no interest in outside intervention.

Or they simply don't have the bandwidth available to provide support. (which is the case, most of the time)

**Comment by Akemi** [comment]
> ... the team lead of ...

just on a side note since i found it funny. we don't really have a team and with that any kind of lead. it's more like many independent contributions that are coordinated in one or another way (by the ones that have merge rights).

but thanks i am that highly appraised.

also what llyyr said, it also comes down to time they can and want to invest, personal interest, personal connections, other involvements, tenacity, etc. sry i probably sounded more negative than i intended to.

**Comment by forthrin** [comment]
I have a philosophy that if you're an insurmountable and irreplaceable number one at your game, you can be as eccentric and unlikable as you want. But not really. And you don't -have- to. And this mostly applies for artists (painters, composers). And if you're number two, you have to be friendly like everyone else. And this is why vanity is considered the ultimate sin.

That said, if anyone has binary knowledge of what's wrong with this file, or how to repair it without re-coding, do post here.

**Comment by philipl** [comment]
Taking the original reported error at face value, the file was encoded with too many reference frames for the hw decoder, or at least video toolbox to accept. This is a weird error to see in this day and age, but it was certainly a real kind of error in the past. If your hardware/os are sufficiently old, it might really be just what it says. If true, your only option is to reencode with a more conservative profile.

**Comment by forthrin** [comment]
System is quite new:

```
System Version: macOS 15.0.1 (24A348)
Model Identifier: MacBookAir10,1 (M1 2020)
```

So max reference frames for HW decoder is 4? Is this a limitation on the/all GPU, macOS or mpv?

`ffprobe` says `refs=1` on the original file. Seems it's not able to give the actual number.

Doing a stream copy well into the file does not help, in case it was an issue only with the start of the file.

**Comment by philipl** [comment]
It's incredibly unlikely that hardware that new has a real max ref frames of 4. But it's possible that the h.264 profile of the video is documented as limiting it to 4 and vtb is enforcing this rather than just working. There are ways to override the profile and/or ignore it but I do not remember the options for it or whether they are sufficiently exposed in mpv.

**Comment by forthrin** [comment]
> There is no limit imposed by H.264 Main Profile Level 4 on consecutive B-frames. However, it is generally recommended to limit the maximum number to around 4, as using more does not provide significant benefits.

https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/h264_refs.c#L765

```c
    if (h->long_ref_count + h->short_ref_count > FFMAX(h->ps.sps->ref_frame_count, 1)) {
        /* We have too many reference frames, probably due to corrupted stream */
        av_log(h->avctx, AV_LOG_ERROR,
               "number of reference frames (%d+%d) exceeds max (%d; probably "
               "corrupt input), discarding one\n",
               h->long_ref_count, h->short_ref_count, h->ps.sps->ref_frame_count);
```

If the stream was "corrupted", then lots more data would be wrong so the video wouldn't play in SW. And time-cutting the video would work around a local problem. So it seems like it should be possible to repair the metadata to make it HW-play.

https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/h264dec.h#L487

`short_ref_count` is supposed to be stored in the `avcC` atom. Naively tried replacing each `05` with `04` one by one by editing the binary, but that either gave `Invalid NAL unit size` or did not change the error message.

```txt
00000000: 6176 6343 014d 4028 ffe1 001b 674d 4028  avcC.M@(....gM@(
00000010: 9662 80f0 089f bc05 0808 080a 0000 0300  .b..............
00000020: 0200 0003 0065 2808 0004 6837 f3c8 0004  .....e(...h7....
00000030: 68fe 3720 0004 685f 8d48 0005 687f cc2f  h.7 ..h_.H..h../
00000040: 2000 0568 27e3 1b20 0005 682f e308 c800   ..h'.. ..h/....
00000050: 0568 3fe3 2c80 0005 6811 f8d4 8000 0000  .h?.,...h.......
00000060: 13                                       .
```

Anyone who knows the format and structs, and can do an educated analysis?
