### ISSUE TITLE
Implicit declaration of function with "add support for xx-color-management-v4" commit

### ISSUE THREAD

**Issue by samoht0** [mpv-player/mpv#15120]
### Important Information

- mpv version: master, starting with commit 187fffd0f5104352bdfdb8c968572830589fad78 
- Platform version: Fedora 40
- Meson version: 1.4.1

### Reproduction Steps

See reproducible copr install and build log, includes Meson log.

### Expected Behavior

pl_color_primaries_name
pl_color_transfer_name
functions declared.

### Actual Behavior

pl_color_primaries_name
pl_color_transfer_name
marked as implicit declaration of function, leading to build error.

Note: xx-color-management-v4.h is generated, see [21/327] of meson log.

### Log File

[edit][obsolete]

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of parameters, and conditions used in "Reproduction Steps".
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.

**Comment by llyyr** [comment]
These functions are defined in `libplacebo/colorspace.h`, but the header gets included via wayland_common.h -> video/mp_image.h -> "video/csputils.h"

I'm curious how it's missing in your build, I don't see any warnings for it

**Comment by samoht0** [comment]
colorspace.h is there, installed with libplacebo-devel-6.338.2-1.fc40.x86_64.rpm
https://koji.fedoraproject.org/koji/rpminfo?rpmID=37588011

**Comment by llyyr** [comment]
Never mind, 

>       '349': 'add pl_color_{primaries,system,transfer}_name(s)',

This is only available on the latest libplacebo release, but mpv didn't bump the minimum libplacebo version

**Comment by samoht0** [comment]
I found it:  libplacebo-6.338.2 colorspace.h doesn't include the definitions.
So, 7.349.0 needed starting with commit 187fffd0f5104352bdfdb8c968572830589fad78

**Comment by sfan5** [comment]
(keeping this open until we have sorted out the requirement formally)
