### ISSUE TITLE
dmabuf-wayland does not show a window on NVIDIA GPU

### ISSUE THREAD

**Issue by Kimiblock** [mpv-player/mpv#15127]
### mpv Information

```bash
Warning: option --load-osd-console was replaced with --load-console and might be removed in the future.
mpv v0.39.0-165-g6b695ac6e4 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Oct 18 2024 21:10:24
libplacebo version: v7.349.0
FFmpeg version: n7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

```text
- Linux version: Arch Linux
- Kernel Version: 6.11.3-arch1-1
- GPU Model: GeForce RTX 4060 Max-Q / Mobile
- Mesa/GPU Driver Version: 560.35.03
- Window Manager and Version: 6.2.1.1
- Source mpv: mpv-git devel package from `archlinuxcn` repository
- Introduced in version: unknown
```

### Reproduction Steps

```
➜  ~ mpv --no-config --vo=dmabuf-wayland '/home/kimiblock/Downloads/2024-10-11 23-19-35.mkv' 
● Video  --vid=1  (av1 1920x1200 90 fps)
● Audio  --aid=1  'Track1' (aac 2ch 48000 Hz)
[hwupload] no support for this hw format
[hwupload] hardware format not supported
[autoconvert] HW-uploading to drm_prime
[hwupload] upload yuv420p -> drm_prime[yuv420p]
[hwupload] failed to upload frame
Cannot convert decoder/filter output to any format supported by the output.
Could not initialize video chain.
Video: no video
AO: [pipewire] 48000Hz stereo 2ch floatp
A: 00:00:02 / 00:04:10 (1%)
Exiting... (Quit)
```

### Expected Behavior

Video plays correctly

### Actual Behavior

MPV does not show any window

### Log File

[output.txt](https://github.com/user-attachments/files/17442094/output.txt)

### Sample Files

https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Dudemanguy** [comment]
You need support for VAAPI which nvidia doesn't support. Or alternatively drmprime but that's not relevant outside of SoC. There's probably some vaapi emulation library or something out there, but no idea how well it works or if it's even a good idea for this use case. Nothing we can do about it.

**Comment by Kimiblock** [comment]
Does dmabuf-Wayland require VAAPI?


--
Sincerely, 
Kimiblock

**Comment by Dudemanguy** [comment]
It requires a hardware decoding driver that is capable of importing dmabufs. There are currently two that can AFAIK and both are implemented: VAAPI or drmprime. If your GPU can't do either one of those, it won't work. In reality, most people use VAAPI.

**Comment by kasper93** [comment]
> It requires a hardware decoding driver that is capable of importing dmabufs. There are currently two that can AFAIK and both are implemented: VAAPI or drmprime.

Vulkan could work too, but is not implemented.

Also correct me if I'm wrong, but the requirement of vaapi currently is limitation of mpv implementation. We could upload dmabuf directly (without vaapi context) with software decoding without issues.

> If your GPU can't do either one of those, it won't work. In reality, most people use VAAPI.

As we can see from this issue, not everyone can sue vaapi.

**Comment by Dudemanguy** [comment]
>Vulkan could work too, but is not implemented.

Can you get drm format/modifier pairs from vulkan decoding? I'm not super familiar with the API or anything, but I didn't see how you could do that so didn't think it was possible.

>We could upload/export dmabuf directly (without vaapi context) with software decoding without issues.

I guess but adding a software path doesn't make any sense with the design of the VO imo.

**Comment by kasper93** [comment]
> Can you get drm format/modifier pairs from vulkan decoding? I'm not super familiar with the API or anything, but I didn't see how you could do that so didn't think it was possible.

https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetImageDrmFormatModifierPropertiesEXT.html

There is `export_handle` option in libplacebo. See https://github.com/haasn/libplacebo/blob/9e16c86f9a37af7fb207241150c2fe7ba50e3471/src/vulkan/gpu_tex.c#L564-L598

I didn't dig into it. But looks like all the puzzle pieces are there, just not connected currently.

> I guess but adding a software path doesn't make any sense with the design of the VO imo.

Fair, although, I don't foresee it would be a lot of code to support that.
