### ISSUE TITLE
stereo3d: print osd and similar things in 3d the same way

### ISSUE THREAD

**Issue by Tratoschek** [mpv-player/mpv#1513]
mpv seems to detect the 3d flag in mkv and has the video-stereo-mode option to change the video content as someone like. Normally I use it so, that I change my (3D) TV to the according setting (e.g. sbs mode) and the TV cut the pictures and overlays them. ATM this results in very strange pictures, if you press P or so, because then one eye see the time and the other not.

It would be nice, if you print the osd and maybe the lua overlay the same way the stereo-mode dictates it.

**Comment by wm4** [comment]
Hm, I thought this was already implemented...

**Comment by wm4** [comment]
Can you post a full log with -v when playing something 3D?

**Comment by Tratoschek** [comment]
$ mpv -v some3dmovie.mkv -vo vdpau -video-stereo-mode=ab2l                                                      [cplayer] Command line: 'mpv' '-v' 'some3dmovie.mkv' '-vo' 'vdpau' '-video-stereo-mode=ab2l'
[cplayer] mpv git-29cf62d (C) 2000-2015 mpv/MPlayer/mplayer2 projects                                                  
[cplayer]  built on UNKNOWN                                                                                            
[cplayer] ffmpeg library versions:                                                                                     
[cplayer]    libavutil       54.17.100                                                                                 
[cplayer]    libavcodec      56.20.100                                                                                 
[cplayer]    libavformat     56.19.100                                                                                 
[cplayer]    libswscale      3.1.101                                                                                   
[cplayer]    libavfilter     5.8.101                                                                                   
[cplayer]    libswresample   1.1.100                                                                                   
[cplayer]                                                                                                              
[cplayer] Configuration: /var/tmp/portage/media-video/mpv-9999/work/mpv-9999/waf --prefix=/usr --libdir=/usr/lib64 --confdir=/etc/mpv --docdir=/usr/share/doc/mpv-9999 --disable-libmpv-shared --disable-libmpv-static --disable-build-date --disable-optimize --disable-debug-build --disable-pdf-build --enable-vf-dlopen-filters --enable-zsh-comp --enable-iconv --disable-libguess --disable-libsmbclient --enable-lua --enable-libass --enable-libass-osd --enable-encoding --disable-joystick --enable-lirc --enable-libbluray --enable-dvdread --enable-dvdnav --disable-cdda --enable-enca --enable-mpg123 --enable-ladspa --enable-libbs2b --enable-lcms2 --disable-vapoursynth --disable-vapoursynth-lazy --enable-libavfilter --enable-libavdevice --enable-sdl2 --disable-sdl1 --disable-oss-audio --disable-rsound --disable-pulse --enable-jack --disable-openal --enable-alsa --disable-wayland --enable-x11 --enable-xss --enable-xext --enable-xv --enable-xinerama --enable-xrandr --enable-gl-x11 --disable-egl-x11 --disable-gl-wayland --enable-gl --enable-vdpau --enable-vdpau-gl-x11 --enable-vaapi --enable-vaapi-vpp --enable-vaapi-glx --disable-caca --enable-jpeg --enable-vaapi-hwaccel --enable-vdpau-hwaccel --disable-tv --disable-tv-v4l2 --disable-libv4l2 --disable-pvr --disable-dvbin configure                       
[cplayer] config.h:                                                                                                    
[cplayer]                                                                                                              
[cplayer] #define DEFAULT_DVD_DEVICE "/dev/sr0"                                                                        
[cplayer] #define DEFAULT_CDROM_DEVICE "/dev/sr0"                                                                      
[cplayer] #define HAVE_CPLAYER 1                                                                                       
[cplayer] #define HAVE_LIBMPV_SHARED 0                                                                                 
[cplayer] #define HAVE_LIBMPV_STATIC 0                                                                                 
[cplayer] #define HAVE_CLIENT_API_EXAMPLES 0                                                                           
[cplayer] #define HAVE_STATIC_BUILD 0                                                                                  
[cplayer] #define HAVE_BUILD_DATE 0                                                                                    
[cplayer] #define HAVE_OPTIMIZE 0                                                                                      
[cplayer] #define HAVE_DEBUG_BUILD 0                                                                                   
[cplayer] #define HAVE_PDF_BUILD 0                                                                                     
[cplayer] #define HAVE_LIBDL 1                                                                                         
[cplayer] #define HAVE_DLOPEN 1                                                                                        
[cplayer] #define HAVE_VF_DLOPEN_FILTERS 1                                                                             
[cplayer] #define HAVE_ZSH_COMP 1                                                                                      
[cplayer] #define HAVE_ASM 1                                                                                           
[cplayer] #define HAVE_TEST 0                                                                                          
[cplayer] #define HAVE_NOEXECSTACK 0                                                                                   
[cplayer] #define HAVE_LIBM 1                                                                                          
[cplayer] #define HAVE_MINGW 0                                                                                         
[cplayer] #define HAVE_POSIX 1                                                                                         
[cplayer] #define HAVE_POSIX_OR_MINGW 1                                                                                
[cplayer] #define HAVE_WIN32_INTERNAL_PTHREADS 0                                                                       
[cplayer] #define HAVE_PTHREADS 1                                                                                      
[cplayer] #define HAVE_STDATOMIC 0                                                                                     
[cplayer] #define HAVE_ATOMIC_BUILTINS 1                                                                               
[cplayer] #define HAVE_SYNC_BUILTINS 0                                                                                 
[cplayer] #define HAVE_ATOMICS 1                                                                                       
[cplayer] #define HAVE_LIBRT 1                                                                                         
[cplayer] #define HAVE_ICONV 1                                                                                         
[cplayer] #define HAVE_DOS_PATHS 0                                                                                     
[cplayer] #define HAVE_WAIO 0                                                                                          
[cplayer] #define HAVE_SYS_VIDEOIO_H 0                                                                                 
[cplayer] #define HAVE_TERMIOS_H 1                                                                                     
[cplayer] #define HAVE_SYS_TERMIOS_H 0                                                                                 
[cplayer] #define HAVE_TERMIOS 1                                                                                       
[cplayer] #define HAVE_SHM 1                                                                                           
[cplayer] #define HAVE_NANOSLEEP 1                                                                                     
[cplayer] #define HAVE_POSIX_SPAWN 1                                                                                   
[cplayer] #define HAVE_GLOB 1                                                                                          
[cplayer] #define HAVE_GLOB_WIN32_REPLACEMENT 0                                                                        
[cplayer] #define HAVE_GLIBC_THREAD_NAME 1                                                                             
[cplayer] #define HAVE_OSX_THREAD_NAME 0                                                                               
[cplayer] #define HAVE_BSD_THREAD_NAME 0                                                                               
[cplayer] #define HAVE_NETBSD_THREAD_NAME 0                                                                            
[cplayer] #define HAVE_BSD_FSTATFS 0                                                                                   
[cplayer] #define HAVE_LINUX_FSTATFS 1                                                                                 
[cplayer] #define HAVE_LIBGUESS 0                                                                                      
[cplayer] #define HAVE_LIBSMBCLIENT 0                                                                                  
[cplayer] #define HAVE_LUA 1                                                                                           
[cplayer] #define HAVE_LIBASS 1                                                                                        
[cplayer] #define HAVE_LIBASS_OSD 1                                                                                    
[cplayer] #define HAVE_DUMMY_OSD 0                                                                                     
[cplayer] #define HAVE_ZLIB 1                                                                                          
[cplayer] #define HAVE_ENCODING 1                                                                                      
[cplayer] #define HAVE_JOYSTICK 0                                                                                      
[cplayer] #define HAVE_LIRC 1                                                                                          
[cplayer] #define HAVE_LIBBLURAY 1                                                                                     
[cplayer] #define HAVE_DVDREAD 1                                                                                       
[cplayer] #define HAVE_DVDNAV 1                                                                                        
[cplayer] #define HAVE_CDDA 0                                                                                          
[cplayer] #define HAVE_ENCA 1                                                                                          
[cplayer] #define HAVE_MPG123 1                                                                                        
[cplayer] #define HAVE_LADSPA 1                                                                                        
[cplayer] #define HAVE_LIBBS2B 1                                                                                       
[cplayer] #define HAVE_LCMS2 1                                                                                         
[cplayer] #define HAVE_VAPOURSYNTH_CORE 0                                                                              
[cplayer] #define HAVE_VAPOURSYNTH 0                                                                                   
[cplayer] #define HAVE_VAPOURSYNTH_LAZY 0                                                                              
[cplayer] #define HAVE_SDL2 1                                                                                          
[cplayer] #define HAVE_SDL1 0                                                                                          
[cplayer] #define HAVE_OSS_AUDIO_4FRONT 0                                                                              
[cplayer] #define HAVE_OSS_AUDIO_NATIVE 0                                                                              
[cplayer] #define HAVE_OSS_AUDIO_SUNAUDIO 0                                                                            
[cplayer] #define HAVE_OSS_AUDIO 0                                                                                     
[cplayer] #define HAVE_RSOUND 0                                                                                        
[cplayer] #define HAVE_SNDIO 0                                                                                         
[cplayer] #define HAVE_PULSE 0                                                                                         
[cplayer] #define HAVE_JACK 1                                                                                          
[cplayer] #define HAVE_OPENAL 0                                                                                        
[cplayer] #define HAVE_ALSA 1                                                                                          
[cplayer] #define HAVE_COREAUDIO 0                                                                                     
[cplayer] #define HAVE_DSOUND 0                                                                                        
[cplayer] #define HAVE_WASAPI 0                                                                                        
[cplayer] #define HAVE_COCOA 0                                                                                         
[cplayer] #define HAVE_GDI 0                                                                                           
[cplayer] #define HAVE_WINMM 0                                                                                         
[cplayer] #define HAVE_OLE 0                                                                                           
[cplayer] #define HAVE_UUID 1                                                                                          
[cplayer] #define HAVE_WAYLAND 0                                                                                       
[cplayer] #define HAVE_X11 1                                                                                           
[cplayer] #define HAVE_XSS 1                                                                                           
[cplayer] #define HAVE_XEXT 1                                                                                          
[cplayer] #define HAVE_XV 1                                                                                            
[cplayer] #define HAVE_XINERAMA 1                                                                                      
[cplayer] #define HAVE_XRANDR 1                                                                                        
[cplayer] #define HAVE_GL_COCOA 0                                                                                      
[cplayer] #define HAVE_GL_X11 1                                                                                        
[cplayer] #define HAVE_EGL_X11 0                                                                                       
[cplayer] #define HAVE_GL_WAYLAND 0                                                                                    
[cplayer] #define HAVE_GL_WIN32 0                                                                                      
[cplayer] #define HAVE_GL 1                                                                                            
[cplayer] #define HAVE_VDPAU 1                                                                                         
[cplayer] #define HAVE_VDPAU_GL_X11 1                                                                                  
[cplayer] #define HAVE_VAAPI 1                                                                                         
[cplayer] #define HAVE_VAAPI_VPP 1                                                                                     
[cplayer] #define HAVE_VAAPI_GLX 1                                                                                     
[cplayer] #define HAVE_CACA 0                                                                                          
[cplayer] #define HAVE_JPEG 1                                                                                          
[cplayer] #define HAVE_DIRECT3D 0                                                                                      
[cplayer] #define HAVE_LIBAV 1                                                                                         
[cplayer] #define HAVE_LIBSWRESAMPLE 1                                                                                 
[cplayer] #define HAVE_LIBAVRESAMPLE 0                                                                                 
[cplayer] #define HAVE_RESAMPLER 1                                                                                     
[cplayer] #define HAVE_LIBAVFILTER 1                                                                                   
[cplayer] #define HAVE_LIBAVDEVICE 1                                                                                   
[cplayer] #define HAVE_AVCODEC_CHROMA_POS_API 1                                                                        
[cplayer] #define HAVE_AVCOL_SPC_BT2020 1                                                                              
[cplayer] #define HAVE_AVCODEC_VDPAU_ALLOC_CONTEXT 1                                                                   
[cplayer] #define HAVE_AVCODEC_METADATA_UPDATE_SIDE_DATA 1                                                             
[cplayer] #define HAVE_AVFORMAT_METADATA_UPDATE_FLAG 1                                                                 
[cplayer] #define HAVE_AVCODEC_REPLAYGAIN_SIDE_DATA 1                                                                  
[cplayer] #define HAVE_AV_DISPLAYMATRIX 1                                                                              
[cplayer] #define HAVE_AVFRAME_METADATA 1                                                                              
[cplayer] #define HAVE_AVFRAME_SKIP_SAMPLES 1                                                                          
[cplayer] #define HAVE_VAAPI_HWACCEL 1                                                                                 
[cplayer] #define HAVE_VIDEODECODEACCELERATION_VDADECODER_H 0                                                          
[cplayer] #define HAVE_VIDEO_DECODE_ACCELERATION_VDA_DECODER_H 0                                                       
[cplayer] #define HAVE_VDA_HWACCEL 0                                                                                   
[cplayer] #define HAVE_VDA_GL 0                                                                                        
[cplayer] #define HAVE_VDPAU_HWACCEL 1                                                                                 
[cplayer] #define HAVE_DXVA2_HWACCEL 0                                                                                 
[cplayer] #define HAVE_TV 0                                                                                            
[cplayer] #define HAVE_TV_V4L2 0                                                                                       
[cplayer] #define HAVE_LIBV4L2 0                                                                                       
[cplayer] #define HAVE_PVR 0                                                                                           
[cplayer] #define HAVE_AUDIO_INPUT 0                                                                                   
[cplayer] #define HAVE_DVBIN 0                                                                                         
[cplayer] #define HAVE_WIN32_EXECUTABLE 0                                                                              
[cplayer] #define HAVE_COCOA_APPLICATION 0                                                                             
[cplayer] #define HAVE_APPLE_REMOTE 0                                                                                  
[cplayer] #define HAVE_SYS_SOUNDCARD_H (HAVE_OSS_AUDIO_NATIVE || HAVE_OSS_AUDIO_4FRONT)                                
[cplayer] #define HAVE_SOUNDCARD_H HAVE_OSS_AUDIO_SUNAUDIO                                                             
[cplayer] #define CONFIGURATION "/var/tmp/portage/media-video/mpv-9999/work/mpv-9999/waf --prefix=/usr --libdir=/usr/lib64 --confdir=/etc/mpv --docdir=/usr/share/doc/mpv-9999 --disable-libmpv-shared --disable-libmpv-static --disable-build-date --disable-optimize --disable-debug-build --disable-pdf-build --enable-vf-dlopen-filters --enable-zsh-comp --enable-iconv --disable-libguess --disable-libsmbclient --enable-lua --enable-libass --enable-libass-osd --enable-encoding --disable-joystick --enable-lirc --enable-libbluray --enable-dvdread --enable-dvdnav --disable-cdda --enable-enca --enable-mpg123 --enable-ladspa --enable-libbs2b --enable-lcms2 --disable-vapoursynth --disable-vapoursynth-lazy --enable-libavfilter --enable-libavdevice --enable-sdl2 --disable-sdl1 --disable-oss-audio --disable-rsound --disable-pulse --enable-jack --disable-openal --enable-alsa --disable-wayland --enable-x11 --enable-xss --enable-xext --enable-xv --enable-xinerama --enable-xrandr --enable-gl-x11 --disable-egl-x11 --disable-gl-wayland --enable-gl --enable-vdpau --enable-vdpau-gl-x11 --enable-vaapi --enable-vaapi-vpp --enable-vaapi-glx --disable-caca --enable-jpeg --enable-vaapi-hwaccel --enable-vdpau-hwaccel --disable-tv --disable-tv-v4l2 --disable-libv4l2 --disable-pvr --disable-dvbin configure"              
[cplayer] #define MPV_CONFDIR "/etc/mpv"                                                                               
[cplayer]                                                                                                              
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config path: 'encoding-profiles.conf' -> '/etc/mpv/encoding-profiles.conf'                                    
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf                                                          
[cplayer]                                                                                                              
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config file: 'config'                                                                                         
[global]     -> '/home/tratoschek/.mpv/config'                                                                              
[cplayer] Reading config file /home/tratoschek/.mpv/config                                                                  
[cplayer]                                                                                                              
[cplayer] Setting option 'ao' = 'jack' (flags = 4)                                                                     
[cplayer] Setting option 'ytdl' = '' (flags = 4)                                                                       
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config file: 'mpv.conf'                                                                                       
[cplayer] Setting option 'v' = '' (flags = 8)                                                                          
[cplayer] Setting option 'vo' = 'vdpau' (flags = 8)                                                                    
[cplayer] Setting option 'video-stereo-mode' = 'ab2l' (flags = 8)                                                      
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config file: 'input.conf'                                                                                     
[input] Falling back on default (hardcoded) input config                                                               
[input/#1] Setting up LIRC support...                                                                                  
[osc] Loading script @osc.lua...                                                                                       
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config file: 'scripts'                                                                                        
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config file: 'lua'                                                                                            
[osc] loading mp.defaults                                                                                              
[osc] loading @osc.lua                                                                                                 
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config path: 'lua-settings/osc.conf' -> '(NULL)'                                                              
[osc] lua-settings/osc.conf not found.                                                                                 
[cplayer] Done loading @osc.lua.                                                                                       
[ytdl_hook] Loading script @ytdl_hook.lua...                                                                           
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config file: 'scripts'                                                                                        
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config file: 'lua'                                                                                            
[ytdl_hook] loading mp.defaults                                                                                        
[ytdl_hook] loading @ytdl_hook.lua                                                                                     
[cplayer] Run command: hook_add, flags=0, args=[on_load, 1, 10]                                                        
[cplayer] Done loading @ytdl_hook.lua.                                                                                 
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config file: 'scripts'                                                                                        
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config file: 'lua'                                                                                            
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config path: 'watch_later/EABB21053E0D44686EF7EFC25718CE44' -> '(NULL)'                                       
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config path: 'watch_later' -> '(NULL)'                                                                        
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config path: 'watch_later/EABB21053E0D44686EF7EFC25718CE44' -> '(NULL)'                                       
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config path: 'watch_later' -> '(NULL)'                                                                        
[cplayer] Playing: some3dmovie.mkv
[cplayer] Running hook: ytdl_hook/on_load
[cplayer] Run command: hook_ack, flags=0, args=[on_load]                                                               
[file] Opened: some3dmovie.mkv                                                                                         
[cache] Cache size set to 25000 KiB                                                                                    
[demux] Trying demuxer: disc (force-level: normal)                                                                     
[demux] Trying demuxer: edl (force-level: normal)                                                                      
[demux] Trying demuxer: cue (force-level: normal)                                                                      
[demux] Trying demuxer: rawaudio (force-level: normal)                                                                 
[demux] Trying demuxer: rawvideo (force-level: normal)                                                                 
[demux] Trying demuxer: libass (force-level: normal)                                                                   
[demux] Trying demuxer: mkv (force-level: normal)                                                                      
[mkv] Found the head...                                                                                                
[mkv] + a segment...                                                                                                   
[mkv] /---- [ parsing seek head ] ---------                                                                            
[mkv] \---- [ parsing seek head ] ---------                                                                            
[mkv] |+ segment information...                                                                                        
[mkv] | + timecode scale: 1000000                                                                                      
[mkv] | + duration: 6129.867s                                                                                          
[mkv] | + segment uid b4 e1 5b 0c b5 50 9f 33 a0 59 ba 5e 9f f3 52 db                                                  
[mkv] |+ segment tracks...                                                                                             
[mkv] | + a track...                                                                                                   
[mkv] |  + Track number: 1                                                                                             
[mkv] |  + Name: 3D-T&B                                                                                                
[mkv] |  + Track type: Video                                                                                           
[mkv] |  + Video track                                                                                                 
[mkv] |   + Display width: 1920                                                                                        
[mkv] |   + Display height: 1080                                                                                       
[mkv] |   + Pixel width: 1920                                                                                          
[mkv] |   + Pixel height: 1080                                                                                         
[mkv] |   + StereoMode: ab2l                                                                                           
[mkv] |  + Codec ID: V_MPEG4/ISO/AVC                                                                                   
[mkv] |  + CodecPrivate, length 43                                                                                     
[mkv] |  + Language: chi                                                                                               
[mkv] |  + Default duration: 41.708ms ( = 23.976 fps)                                                                  
[mkv] | + a track...                                                                                                   
[mkv] |  + Track number: 2                                                                                             
[mkv] |  + Name: ~ DTS-HD MA 7.1 @ 16bit                                                                               
[mkv] |  + Track type: Audio                                                                                           
[mkv] |  + Audio track                                                                                                 
[mkv] |   + Sampling frequency: 48000.000000                                                                           
[mkv] |   + Channels: 6                                                                                                
[mkv] |  + Codec ID: A_DTS                                                                                             
[mkv] |  + Language: ger                                                                                               
[mkv] |  + Default duration: 10.667ms ( = 93.750 fps)                                                                  
[mkv] /---- [ parsing chapters ] ---------                                                                             
[mkv] New edition 0                                                                                                    
[mkv] Default edition flag: 0                                                                                          
[mkv] Chapter 0 from 00:00:00.000 to 00:00:00.000, 1 - 0:00:00                                                         
[mkv] Chapter 1 from 00:07:04.966000000 to 00:00:00.000, 2 - 0:07:04                                                   
[mkv] Chapter 2 from 00:14:23.571000000 to 00:00:00.000, 3 - 0:14:23                                                   
[mkv] Chapter 3 from 00:20:40.113000000 to 00:00:00.000, 4 - 0:20:40                                                   
[mkv] Chapter 4 from 00:26:18.493000000 to 00:00:00.000, 5 - 0:26:18                                                   
[mkv] Chapter 5 from 00:31:26.884000000 to 00:00:00.000, 6 - 0:31:26                                                   
[mkv] Chapter 6 from 00:38:13.666000000 to 00:00:00.000, 7 - 0:38:13                                                   
[mkv] Chapter 7 from 00:45:24.638000000 to 00:00:00.000, 8 - 0:45:24                                                   
[mkv] Chapter 8 from 00:50:49.629000000 to 00:00:00.000, 9 - 0:50:49                                                   
[mkv] Chapter 9 from 00:57:46.588000000 to 00:00:00.000, 10 - 0:57:46                                                  
[mkv] Chapter 10 from 01:07:05.980000000 to 00:00:00.000, 11 - 1:07:05                                                 
[mkv] Chapter 11 from 01:12:30.804000000 to 00:00:00.000, 12 - 1:12:30                                                 
[mkv] Chapter 12 from 01:16:48.437000000 to 00:00:00.000, 13 - 1:16:48                                                 
[mkv] Chapter 13 from 01:23:19.828000000 to 00:00:00.000, 14 - 1:23:19                                                 
[mkv] Chapter 14 from 01:28:59.83000000 to 00:00:00.000, 15 - 1:28:59                                                  
[mkv] Chapter 15 from 01:35:22.967000000 to 00:00:00.000, 16 - 1:35:22                                                 
[mkv] Chapter 16 from 01:42:07.871000000 to 00:00:00.000, 17 - 1:42:07                                                 
[mkv] \---- [ parsing chapters ] ---------                                                                             
[mkv] |+ found cluster                                                                                                 
[mkv] Deferring reading cues.                                                                                          
[mkv] All headers are parsed!                                                                                          
[mkv] Aspect: 1.777778                                                                                                 
[demux] Detected file format: Matroska                                                                                 
[cache] blocking for STREAM_CTRL 8                                                                                     
[cache] blocking for STREAM_CTRL 8                                                                                     
[find_subfiles] Load subtitles in .                                                                                    
[global] search dirs: /home/tratoschek/.mpv /etc/mpv                                                                        
[global] config path: 'sub/' -> '(NULL)'                                                                               
[cplayer]  (+) Video --vid=1 '3D-T&B' (h264)
[cplayer]  (+) Audio --aid=1 --alang=ger (*) '~ DTS-HD MA 7.1 @ 16bit' (dts)
[cplayer] [V] fourcc:0x31637661  size:1920x1080  fps:23.976
[vo/vdpau/x11] X11 opening display: :0                                                                                 
[vo/vdpau/x11] X11 running at 1920x1080 (":0" => local display)                                                        
[vo/vdpau/x11] Detected wm supports NetWM.                                                                             
[vo/vdpau/x11] Detected wm supports FULLSCREEN state.                                                                  
[vo/vdpau/x11] Detected wm supports ABOVE state.                                                                       
[vo/vdpau/x11] Detected wm supports BELOW state.                                                                       
[vo/vdpau/x11] Detected wm supports STAYS_ON_TOP state.                                                                
[vo/vdpau/x11] Display 0 (DisplayPort-0): [0, 0, 1920, 1080] @ 60.000000 FPS                                           
[vo/vdpau/x11] Display 1 (HDMI-0): [0, 0, 1920, 1080] @ 60.000000 FPS                                                  
[vo/vdpau] Assuming 1000.000000 FPS for framedrop.                                                                     
[vd] Codec list:                                                                                                       
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10                                                         
[vd]     lavc:h264_vdpau (h264) - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (VDPAU acceleration)                       
[vd] Opening video decoder lavc:h264                                                                                   
[vd] Detected 4 logical cores.                                                                                         
[vd] Requesting 4 threads for decoding.                                                                                
[vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]                                       
[vo/vdpau/x11] Disabling screensaver.                                                                                  
[ad] Codec list:                                                                                                       
[ad]     lavc:dca (dts) - DCA (DTS Coherent Acoustics)                                                                 
[ad] Opening audio decoder lavc:dca                                                                                    
[ad] Requesting 1 threads for decoding.                                                                                
[ad] Selected audio codec: DCA (DTS Coherent Acoustics) [lavc:dca]                                                     
[cplayer] Starting playback...                                                                                         
[af] Audio filter chain:                                                                                               
[af]   [in] 48000Hz 5.1(side) 6ch floatp                                                                               
[af]   [out] 48000Hz 5.1(side) 6ch floatp                                                                              
[af]   [ao] 48000Hz 5.1(side) 6ch floatp                                                                               
[ao] Trying preferred audio driver 'jack'                                                                              
[ao/jack] requested format: 48000 Hz, 5.1(side) channels, floatp                                                       
[ao/jack] using soft-buffer of 9600 samples.                                                                           
[cplayer] AO: [jack] 48000Hz 5.1(side) 6ch floatp
[cplayer] AO: Description: JACK audio output
[af] Audio filter chain:                                                                                               
[af]   [in] 48000Hz 5.1(side) 6ch floatp                                                                               
[af]   [out] 48000Hz 5.1(side) 6ch floatp                                                                              
[af]   [ao] 48000Hz 5.1(side) 6ch floatp                                                                               
[af] Audio filter chain:                                                                                               
[af]   [in] 48000Hz 5.1(side) 6ch floatp                                                                               
[af]   [out] 48000Hz 5.1(side) 6ch floatp                                                                              
[af]   [ao] 48000Hz 5.1(side) 6ch floatp                                                                               
[vd] VIDEO:  1920x1080  23.976 fps    0.0 kbps ( 0.0 kB/s)
[vd] VDec: vo config request - 1920 x 1080 (yuv420p)
[vd] VO Config (1920x1080->1920x1080,0x3EC)
[vf] Video filter chain:
[vf]  [vd] 1920x1080 yuv420p Autoselect/Autoselect CL=mpeg2/4/h264 stereo=ab2l/ab2l
[vf]  [in] 1920x1080 yuv420p BT.709 (HD)/TV CL=mpeg2/4/h264 stereo=ab2l/ab2l
[vf]  [out] 1920x1080 yuv420p BT.709 (HD)/TV CL=mpeg2/4/h264 stereo=ab2l/ab2l
[cplayer] VO: [vdpau] 1920x1080 yuv420p
[cplayer] VO: Description: VDPAU with X11
[vo/vdpau/x11] Current display FPS: 60.000000
[vo/vdpau] Compositing window manager detected. Assuming timing info is inaccurate.
[vo/vdpau] Window size: 1842x1036
[vo/vdpau] Video source: 1920x1080 (1920x1080)
[vo/vdpau] Video display: (0, 0) 1920x1080 -> (0, 0) 1841x1036
[vo/vdpau] Video scale: 0.958854/0.959259
[vo/vdpau] OSD borders: l=0 t=0 r=1 b=0
[vo/vdpau] Video borders: l=0 t=0 r=1 b=0
[vo/vdpau] Assuming 60.000000 FPS for framedrop.
[vo/vdpau] Recreating vdpau video mixer.
[global] search dirs: /home/tratoschek/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/tratoschek/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/tratoschek/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[global] search dirs: /home/tratoschek/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/tratoschek/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/tratoschek/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[global] search dirs: /home/tratoschek/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/tratoschek/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/tratoschek/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[statusline] AV: 00:00:02 / 01:42:09 (0%) A-V: -0.000 Cache:  2s+23571KB
[cplayer] Run command: script_binding, flags=9, args=[osc/__keybinding1]
[statusline] AV: 00:00:02 / 01:42:09 (0%) A-V:  0.000 Cache:  2s+23571KB
[vo/vdpau] Allocating a 1024x512 surface for OSD bitmaps.
[statusline] AV: 00:00:02 / 01:42:09 (0%) A-V:  0.000 Cache:  2s+23571KB
[cplayer] Run command: script_binding, flags=9, args=[osc/__keybinding1]
[statusline] AV: 00:00:04 / 01:42:09 (0%) A-V: -0.000 Cache:  2s+23024KB
[cplayer] Run command: show_progress, flags=9, args=[]
[statusline] AV: 00:00:04 / 01:42:09 (0%) A-V:  0.000 Cache:  2s+22965KB
[vo/vdpau] Allocating a 2048x128 surface for OSD bitmaps.
[vo/vdpau] Allocating a 1024x256 surface for OSD bitmaps.
[statusline] AV: 00:00:06 / 01:42:09 (0%) A-V: -0.000 Cache:  2s+22559KB
[cplayer] Run command: show_progress, flags=9, args=[]
[statusline] AV: 00:00:07 / 01:42:09 (0%) A-V: -0.000 Cache:  2s+21840KB
[cplayer] Run command: script_binding, flags=9, args=[osc/__keybinding1]
[statusline] AV: 00:00:07 / 01:42:09 (0%) A-V:  0.000 Cache:  2s+21840KB
[cplayer] Run command: script_binding, flags=9, args=[osc/__keybinding1]
[statusline] AV: 00:00:07 / 01:42:09 (0%) A-V:  0.000 Cache:  2s+21840KB
[cplayer] Run command: script_binding, flags=9, args=[osc/__keybinding1]
[cplayer] Run command: script_binding, flags=9, args=[osc/__keybinding2]
[statusline] AV: 00:00:08 / 01:42:09 (0%) A-V: -0.000 Cache:  2s+21125KB
[cplayer] Run command: quit, flags=9, args=[0]
[cplayer] EOF code: 6  
[cplayer] 
[ad] Uninit audio filters...
[ad] Uninit audio decoder.
[vd] Uninit video.
[cache] Terminating cache...
[cache] Cache exiting...
[cplayer] 
[cplayer] Exiting... (Quit)
[ytdl_hook] Exiting...
[osc] Exiting...
[vo/vdpau/x11] Enabling screensaver.
[vo/vdpau/x11] uninit ...

**Comment by wm4** [comment]
Oops, forgot about this.

This happens because of ``--vo=vdpau``. This vo does not implement duplicating the OSD. Try with opengl.

**Comment by wm4** [comment]
No feedback...
