### ISSUE TITLE
how to load the c cplugin 

### ISSUE THREAD

**Issue by jsdfhasuh** [mpv-player/mpv#15140]
### mpv Information

```bash
mpv v0.39.0-170-g37159a8e Copyright @ 2000-2024 mpv/MPlayer/mplayer2 projects
built on 0ct 20 2024 00:05:22
libplacebo version: v7.349.0 (v7.349.0-18-g9e16c86-dirty)
FFmpeg version: N-117613-g72e538112
FFmpeg library versions:
Libavcodec61.22.100
libavdevice61.4.100
libavfilter10.6.100
libavformat61.9.100
libavutil59.44.100
libswresample5.4.100
libswscale8.6.100
```

### Other Information

```text
- Windows version:
win 11
```

### Reproduction Steps

my c code：\n
![image](https://github.com/user-attachments/assets/34efcf90-5e46-434a-8f5c-702b48e9a21d)
my task.json:  \n
![image](https://github.com/user-attachments/assets/06b71c3e-1407-4194-9f47-12a000da2ecb)

### Expected Behavior

it will print the mpv version

### Actual Behavior

![image](https://github.com/user-attachments/assets/c26cba23-5121-4e8c-8a6f-b33e4c1ecd02)
can not load the c plungin

### Log File

[test]C plugin error：‘找不到指定的程序。
[test]
[test] Could not load cplugin script C:\Users\ddlo9\AppData\Roaming/mpv/scripts/test.d
[auto_profiles] Applying auto profile: ontop-playback
Resuming playback. This behavior can be disabled with --no-resume-playback.
●Video --vid=1 --vlang=en (h264 1920x1080 29.97 fps） [default]
●Audio--aid=1--alang=ja‘日语'（aac 2ch 48000 Hz）[default]
Subs--sid=1--slang=zh‘简体中文’（subrip)
O Subs--sid=22--slang=zh‘繁体中文’（subrip)
Using hardware decoding (d3d1lva).
AO:[wasapi] 44100Hz stereo 2ch float
VO:[gpu] 1920x1080 d3d11[nv12]
Saving state.
(Paused) AV:00:00:09/ 00:54:11(0%) A-V:0.000
Exiting...(Quit)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
How did you build/create `test.dll`? Could you explain what steps did you take in detail?

**Comment by jsdfhasuh** [comment]
> How did you build/create `test.dll`? Could you explain what steps did you take in detail?

cmd /c chcp 65001>nul && "C:\Program Files\mingw64\bin\gcc.exe" C:\Users\dd109\Desktop\mpv-0.39.0\mpv-0.39.0\my_scripts\test.c -DMPV_CPLUGIN_DYNAMIC_SYM -I C:\Users\dd109\Desktop\mpv-0.39.0\mpv-0.39.0\ -shared -o C:\Users\dd109\Desktop\mpv-0.39.0\mpv-0.39.0\my_scripts\test.dll

**Comment by kasper93** [comment]
Make sure all dependencies of test.dll are in PATH or the same folder. This error message means that during loading of test.dll some its dependencies were not found.

**Comment by jsdfhasuh** [comment]
> Make sure all dependencies of test.dll are in PATH or the same folder. This error message means that during loading of test.dll some its dependencies were not found.

what dependencies it need? I include the "libmpv/client.h",and it compile no error message

**Comment by jsdfhasuh** [comment]
> Make sure all dependencies of test.dll are in PATH or the same folder. This error message means that during loading of test.dll some its dependencies were not found.

same scripts。 in ubuntu it work fine。the build command is "gcc -o simple.so simple.c -I /home/jsdfhasuh/mpv-build/mpv -shared -fPIC"

**Comment by jsdfhasuh** [comment]
![image](https://github.com/user-attachments/assets/beef77c7-6fcb-4329-a11f-8ee149b228e6)

**Comment by jsdfhasuh** [comment]
![image](https://github.com/user-attachments/assets/1f3d8fe2-87b5-4397-98bc-492f12609973)
maybe the error occur in dlopen， it can not find the scripts file.

**Comment by jsdfhasuh** [comment]
> Use `llvm-readobj --needed-libs` or something similar to check for DLL dependencies.
I try use llvm-readobj --needed-libs
![image](https://github.com/user-attachments/assets/fead09e4-d586-49fb-9fbc-118489157e5f)
I get kernel32 and msvcrt from internet，and put them in the scripts folder。but same error

**Comment by kasper93** [comment]
>  I get kernel32 and msvcrt from internet，and put them in the scripts folder。but same error

Don't download random dlls from internet. Those are standard system libraries, you already have it. Run your mpv under debugger, see why your library fails to load.

Also add `MPV_EXPORT` to your `mpv_open_cplugin` function.

**Comment by jsdfhasuh** [comment]
> > I get kernel32 and msvcrt from internet，and put them in the scripts folder。but same error
> 
> Don't download random dlls from internet. Those are standard system libraries, you already have it. Run your mpv under debugger, see why your library fails to load.
> 
> Also add `MPV_EXPORT` to your `mpv_open_cplugin` function.
ok, it work
