### ISSUE TITLE
how to fix this build error

### ISSUE THREAD

**Issue by jsdfhasuh** [mpv-player/mpv#15161]
### Important Information

```text
- mpv version:0.39
- Platform version:windows
- Meson version:1.51
```

### Reproduction Steps

"I compiled and generated mpv.exe on Ubuntu 24 using MinGW-w64, following the instructions at https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md. I used the command meson setup -Ddefault_library=static -Dprefer_static=true -Dc_link_args='-static' -Dcpp_link_args='-static' --cross-file cross-file.txt build."

### Expected Behavior

get the screenshot

### Actual Behavior

[screenshot] Could not open libavcodec encoder for saving images
[screenshot] Error writing file 'C:\Users\dd109\Pictures\MPV-image/mpv-shot-0006.png'!
Error writing screenshot!

### Log File

[mpv.txt](https://github.com/user-attachments/files/17487413/mpv.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of parameters, and conditions used in "Reproduction Steps".
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.

**Comment by jsdfhasuh** [comment]
@kasper93 please give me some advice

**Comment by kasper93** [comment]
Your build is likely missing zlib needed for png encoder in ffmpeg. Post your build log. But either way it is not mpv issue.

**Comment by jsdfhasuh** [comment]
> Your build is likely missing zlib needed for png encoder in ffmpeg. Post your build log. But either way it is not mpv issue.您的构建可能缺少 ffmpeg 中 png 编码器所需的 zlib。请发布您的构建日志。但无论如何，这不是 mpv 的问题。

[meson-log.txt](https://github.com/user-attachments/files/17490648/meson-log.txt)
this is my log

**Comment by jsdfhasuh** [comment]
> Your build is likely missing zlib needed for png encoder in ffmpeg. Post your build log. But either way it is not mpv issue.您的构建可能缺少 ffmpeg 中 png 编码器所需的 zlib。请发布您的构建日志。但无论如何，这不是 mpv 的问题。

cat <<EOF > subprojects/ffmpeg.wrap
[wrap-git]
url = https://gitlab.freedesktop.org/gstreamer/meson-ports/ffmpeg.git
revision = meson-7.1
depth = 1
[provide]
libavcodec = libavcodec_dep
libavdevice = libavdevice_dep
libavfilter = libavfilter_dep
libavformat = libavformat_dep
libavutil = libavutil_dep
libswresample = libswresample_dep
libswscale = libswscale_dep
EOF

**Comment by kasper93** [comment]
> Run-time dependency zlib found: NO (tried pkgconfig, cmake and system)

If you are using meson you can do `meson wrap install zlib` from top directory and reconfigure, should detect zlib in this case.

**Comment by jsdfhasuh** [comment]
> zlib
![image](https://github.com/user-attachments/assets/57b0bc65-bb14-4b3f-b4b8-d58bb62874c0)
![image](https://github.com/user-attachments/assets/a759c87c-fd16-4331-9bf1-c3532a184346)
[Uploading meson-log.txt…]()
same error， it can not detect the zlib。

**Comment by kasper93** [comment]
Add `--force-fallback-for=zlib` to your meson command.

**Comment by kasper93** [comment]
Use `luajit`

**Comment by jsdfhasuh** [comment]
> Use `luajit`
but it compile error
[2635/2895] Compiling C object subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/libluajit-5.1.a.p/lj_err.c.obj
FAILED: subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/libluajit-5.1.a.p/lj_err.c.obj 
x86_64-w64-mingw32-gcc -Isubprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/libluajit-5.1.a.p -Isubprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src -I../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c11 -O2 -g -fno-stack-protector -fomit-frame-pointer -D_LARGEFILE_SOURCE -U_FORTIFY_SOURCE -MD -MQ subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/libluajit-5.1.a.p/lj_err.c.obj -MF subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/libluajit-5.1.a.p/lj_err.c.obj.d -o subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/libluajit-5.1.a.p/lj_err.c.obj -c ../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c: In function ‘RtlUnwindEx_FIXED’:
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:244:61: error: expected declaration specifiers before ‘asm’
  244 | VOID RtlUnwindEx_FIXED(PVOID,PVOID,PVOID,PVOID,PVOID,PVOID) asm("RtlUnwindEx");
      |                                                             ^~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:259:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
  259 | {
      | ^
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:354:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
  354 | {
      | ^
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:384:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
  384 | {
      | ^
In file included from ../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_obj.h:13,
                 from ../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:9:
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:774:1: note: in expansion of macro ‘LJ_NOINLINE’
  774 | LJ_NOINLINE void LJ_FASTCALL lj_err_throw(lua_State *L, int errcode)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:807:1: note: in expansion of macro ‘LJ_NOINLINE’
  807 | LJ_NOINLINE GCstr *lj_err_str(lua_State *L, ErrMsg em)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:813:1: note: in expansion of macro ‘LJ_NOINLINE’
  813 | LJ_NOINLINE void lj_err_mem(lua_State *L)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:835:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
  835 | {
      | ^
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:885:1: note: in expansion of macro ‘LJ_NOINLINE’
  885 | LJ_NOINLINE void LJ_FASTCALL lj_err_run(lua_State *L)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:910:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
  910 | {
      | ^
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:917:1: note: in expansion of macro ‘LJ_NOINLINE’
  917 | LJ_NOINLINE void LJ_FASTCALL lj_err_trace(lua_State *L, int errcode)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:125:25: error: expected declaration specifiers before ‘__attribute__’
  125 | #define LJ_NORET        __attribute__((noreturn))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:927:1: note: in expansion of macro ‘LJ_NORET’
  927 | LJ_NORET LJ_NOINLINE static void err_msgv(lua_State *L, ErrMsg em, ...)
      | ^~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:944:1: note: in expansion of macro ‘LJ_NOINLINE’
  944 | LJ_NOINLINE void lj_err_msg(lua_State *L, ErrMsg em)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:950:1: note: in expansion of macro ‘LJ_NOINLINE’
  950 | LJ_NOINLINE void lj_err_lex(lua_State *L, GCstr *src, const char *tok,
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:964:1: note: in expansion of macro ‘LJ_NOINLINE’
  964 | LJ_NOINLINE void lj_err_optype(lua_State *L, cTValue *o, ErrMsg opm)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:980:1: note: in expansion of macro ‘LJ_NOINLINE’
  980 | LJ_NOINLINE void lj_err_comp(lua_State *L, cTValue *o1, cTValue *o2)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:989:1: note: in expansion of macro ‘LJ_NOINLINE’
  989 | LJ_NOINLINE void lj_err_optype_call(lua_State *L, TValue *o)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1008:1: note: in expansion of macro ‘LJ_NOINLINE’
 1008 | LJ_NOINLINE void lj_err_callermsg(lua_State *L, const char *msg)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1038:1: note: in expansion of macro ‘LJ_NOINLINE’
 1038 | LJ_NOINLINE void lj_err_callerv(lua_State *L, ErrMsg em, ...)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1049:1: note: in expansion of macro ‘LJ_NOINLINE’
 1049 | LJ_NOINLINE void lj_err_caller(lua_State *L, ErrMsg em)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:125:25: error: expected declaration specifiers before ‘__attribute__’
  125 | #define LJ_NORET        __attribute__((noreturn))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1055:1: note: in expansion of macro ‘LJ_NORET’
 1055 | LJ_NORET LJ_NOINLINE static void err_argmsg(lua_State *L, int narg,
      | ^~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1070:1: note: in expansion of macro ‘LJ_NOINLINE’
 1070 | LJ_NOINLINE void lj_err_argv(lua_State *L, int narg, ErrMsg em, ...)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1081:1: note: in expansion of macro ‘LJ_NOINLINE’
 1081 | LJ_NOINLINE void lj_err_arg(lua_State *L, int narg, ErrMsg em)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1087:1: note: in expansion of macro ‘LJ_NOINLINE’
 1087 | LJ_NOINLINE void lj_err_argtype(lua_State *L, int narg, const char *xname)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_def.h:129:25: error: expected declaration specifiers before ‘__attribute__’
  129 | #define LJ_NOINLINE     __attribute__((noinline))
      |                         ^~~~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1110:1: note: in expansion of macro ‘LJ_NOINLINE’
 1110 | LJ_NOINLINE void lj_err_argt(lua_State *L, int narg, int tt)
      | ^~~~~~~~~~~
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1118:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 1118 | {
      | ^
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1126:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 1126 | {
      | ^
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1132:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 1132 | {
      | ^
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1138:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 1138 | {
      | ^
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1144:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 1144 | {
      | ^
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1151:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 1151 | {
      | ^
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:1161: error: expected ‘{’ at end of input
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c: At top level:
../subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/lj_err.c:109:14: warning: ‘err_unwind’ defined but not used [-Wunused-function]
  109 | static void *err_unwind(lua_State *L, void *stopcf, int errcode)
      |              ^~~~~~~~~~
[2637/2895] Compiling C object subprojects/LuaJIT-04dca7911ea255f37be799c18d74c305b921c1a6/src/libluajit-5.1.a.p/lj_ffrecord.c.obj

**Comment by kasper93** [comment]
Go to submodule folder of luajit and remove this line. See https://github.com/LuaJIT/LuaJIT/pull/1272
