### ISSUE TITLE
Volumes differ between ao_pulse and ao_pipewire

### ISSUE THREAD

**Issue by paulmenzel** [mpv-player/mpv#15171]
### mpv Information

```bash
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0
FFmpeg version: 7.0.2-3
FFmpeg library versions:
   libavutil       59.8.100
   libavcodec      61.3.100
   libavformat     61.1.100
   libswscale      8.1.100
   libavfilter     10.1.100
   libswresample   5.1.100
```

### Other Information

```text
- Linux version: Debian sid/unstable
- Kernel Version: Linux abreu 6.12.0-rc4-00047-gc2ee9f594da8 #19 SMP PREEMPT_DYNAMIC Tue Oct 22 11:56:37 CEST 2024 x86_64 GNU/Linux
- GPU Model: 00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 620 [8086:5916] (rev 02)
- Mesa/GPU Driver Version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.2.4-1
- Window Manager and Version: *gnome* 1:47+2
- Source mpv: Debian archive (*mpv* 0.38.0-1+b1)
- Introduced in version: unknown
```

### Reproduction Steps

*pipewire* 1.2.5-1

Play audio file with `--ao=pipewire` and `--ao=pulse`.

### Expected Behavior

The resulting volume should be the same.

### Actual Behavior

Starting with `--ao=pipewire` the resulting volume is louder compared to `--ao=pulse`.

### Log File

1.  [mpv-pulse.txt](https://github.com/user-attachments/files/17513621/mpv-pulse.txt)
2.  [mpv-pipewire.txt](https://github.com/user-attachments/files/17513622/mpv-pipewire.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Dudemanguy** [comment]
>The resulting volume should be the same.

Why would they be the same?

**Comment by llyyr** [comment]
Launch mpv once with both and use `pavucontrol` to see if you accidentally changed the server volume for mpv for either pulse or pipewire.

**Comment by paulmenzel** [comment]
> Launch mpv once with both and use `pavucontrol` to see if you accidentally changed the server volume for mpv for either pulse or pipewire.

That was it. It was set to 153 % with pipewire. Thank you very much for pinpointing the cause.

PS: That explains the distortions I had with PipeWire. After moving the slider to 100 %, the distortions with PipeWire are also gone. Awesome.

**Comment by paulmenzel** [comment]
> > The resulting volume should be the same.
> 
> Why would they be the same?

I guess you could argue both sides, but for me switching audio backends should be independent from the resulting volume, as it’s some API(?) talking to a sound server and not some (volume) profile. I guess, it’s not like this.
