### ISSUE TITLE
OSD Sub Language Select

### ISSUE THREAD

**Issue by Raidfire-SDR** [mpv-player/mpv#15176]
### Other Information

```text
- Windows version:11
- GPU model, driver and version:rx550
- Source of mpv:
- Introduced in version:
```

### Reproduction Steps

Attempt to use osd to change sub language.

### Expected Behavior

I update my mpv about once a week in the last update the default changed for the OSD sub language select, before clicking the icon with left mouse selected the next sub, right the previous, now it pops up a menu of all languages that is almost unreadable and I cannot switch off the subs now. how to return to original defaults, can someone provide the osd parameter to add to the input conf.

### Actual Behavior

unreadable menu.

### Log File

[mpvoutput.txt](https://github.com/user-attachments/files/17528215/mpvoutput.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Samillion** [comment]
For reference, to turn off subtitles in the new select menu, click on the same (active) subtitle track.

**Personal note:**
I realize sudden change can be overwhelming, but I highly recommend giving the new select menu a chance. Full mouse control, scrollable, fuzzy match typing. It is excellent in handling track lists (and audio device select).

**Comment by guidocella** [comment]
You are right that's it's unusable with the default font size. Please vote to increase it in https://github.com/mpv-player/mpv/discussions/15044

**Comment by Raidfire-SDR** [comment]
I'm colour blind, the choice of colours makes it impossible to read, it wasn't the font size (which i have manually tweaked anyway for thing like the console) it's the colours, if you want it to be accessible to all it's going to need to go monochrome, anything green or red is a big no for colour blind people unless you want to put an opaque background under the menu to increase contrast - which detracts from the original idea.

Having to get out a keyboard for fuzzy typing is a step backwards, and a con not a pro, having it on the mouse was perfect it didn't require another device, how about a separate button next to the original that opens the menu so we have the best of both worlds?

**Comment by Raidfire-SDR** [comment]
current back to old osc.conf (a note on the never flag  for the eagle eyed - that's my default, i map mouse fwd and back buttons to always and never in my input conf)

visibility=never
deadzonesize=1
sub_track_mbtn_left_command=cycle sub
sub_track_mbtn_right_command=cycle sub down
title=${media-title}
title_mbtn_left_command=show-text "${!playlist-count==1:[${playlist-pos-1}/${playlist-count}] }${media-title}"
title_mbtn_right_command=show-text ${filename}

chapter_prev_mbtn_right_command=show-text ${chapter-list} 3000
chapter_next_mbtn_right_command=show-text ${chapter-list} 3000

audio_track_mbtn_left_command=cycle audio
audio_track_mbtn_right_command=cycle audio down

**Comment by guidocella** [comment]
We're not UI designers, suggestions for different colors are welcome. The selected item color is just the color for selected tab completions that NRK suggested (it is yellow, not green or red).  I don't think we'll use monochrome by default as that would make the UI worse for everyone who is not color blind.

You don't have to use a keyboard for fuzzy typing since mouse support was just added. Adding more buttons was already rejected due to the OSC being too cluttered: https://github.com/mpv-player/mpv/issues/5067#issuecomment-341385781 https://github.com/mpv-player/mpv/issues/8065#issuecomment-688528684
Script-opts to customize the bindings have been added and you don't even have to use the menu by default since you can change tracks with the wheel.

Everyone is welcome to test PRs, we can't force more people to provide reviews if they don't give them (but apparently there was more interest in reviewing the tab width configuration lol).

**Comment by Raidfire-SDR** [comment]
MPV is great with one exception anywhere text creeps into the UI it becomes incredibly difficult to use the last think i want is a shiny apple style UI but something functional with high contrast, I don't think it's the font size as much as the wight, the text is always too thin and wiry making it hard for people with limited vision, if the text was thicker it would be more functional for the moment it's way too light to be of any use to me, mine is fixed with conf edits, i'm talking more out of the box for novice users.

**Comment by guidocella** [comment]
Are you talking about the monospace font? Try `--script-opt=console-font=sans-serif`, that's what I use. The default is monospace just to align tab completions on a grid in the console. I thought of defaulting the console to a proportional font when called for selection if no font was specified, dunno if that's wanted.

Even if you rebind the wheel using the wheel on OSC buttons should still work.

**Comment by Raidfire-SDR** [comment]
Now there's your answer...
Sans serif as default makes the new lua menu both look nice and functional! Still puttin my mouse buttons back tho ;)
