### ISSUE TITLE
youtube-dl: support default-search

### ISSUE THREAD

**Issue by Tratoschek** [mpv-player/mpv#1517]
A nice feature of youtube-dl is the search option, e.g.:
youtube-dl --default-search ytsearch nyan cat

Current supported values seems to be:
ytsearch (youtube), ytsearchdate (youtube), yvsearch (yahoo videos), gvsearch (google videos)

It would be nice, if mpv provides an option to hook this parameter to youtube-dl.

**Comment by wm4** [comment]
> if mpv provides an option to hook this parameter to youtube-dl.

I think you could get this with simply using ``--ytdl-raw-options``.

**Comment by rubyFeedback** [comment]
This came again recently on a reddit discussion thread.

I tried to copy/paste this here:

    mpv --no-video ytdl://ytsearch:"welcome tp the internet bo burnham"

Unfortunately mpv gave this error:

"No protocol handler found to open URL ytdl://ytsearch:welcome tp the internet bo burnham
The protocol is either unsupported, or was disabled at compile-time."

It's good that there is a message explaining why it failed, but now I wonder HOW to get
support for this into mpv. Could perhaps the message be a bit more verbose, 
e. g. explain WHICH particular option should be enabled during compile time? I can
recompile mpv just fine, but right now as I write this, I don't know which option it
is. I have to do another google search now ... :D

**Comment by pabloab** [comment]
This works like a charm (with some errors, though):

    mpv --quiet --no-video --ytdl-format=best "ytdl://ytsearch:\"lofi+radio\""
