### ISSUE TITLE
Cannot seek within cached data?

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1518]
I was trying to do some sort of timeshifting with a dvb card, but i noticed that even if i set a very big cache (100MB), mpv is unable to seek.
I know the devs have not dvb card, so i reproduced the issue by dumping the stream and "catting" it to mpv.

so, the followings are equivalent:
```
#mpv dvb://cielo --demuxer-lavf-analyzeduration=1 --demuxer-lavf-probesize=512000 --cache-secs=10 --cache=100000
#cat /tmp/stream.ts |mpv - --cache-secs=10 --cache=100000
```
The dumped stream is here (35MB):
http://wpage.unina.it/aorefice/sharevari/stream.ts
Of course, before i seek, i let the cache to fill, but as soon as i hit the arrow key, the stream simply restarts from the beginning.

Note that for some reason, mplayer is able to seek within the cached data in this particular case.

**Comment by wm4** [comment]
What does it say.

**Comment by olifre** [comment]
I can reproduce here, both with the uploaded file and also with a "fresh" stream. 
An interesting fact is that hr-seek (i.e. shift+down / shift+up in default bindings) works perfectly fine for both.

**Comment by olifre** [comment]
I managed to reproduce with a "normal" mpeg-ts stream, so it is likely not related to missing information from the DVB stream, but seems to affect all mpeg-ts: 
`
ffmpeg -i someinputvideo.mp4 -acodec copy -tune zerolatency -x264opts bitrate=2600:vbv-maxrate=2600:vbv-bufsize=166:nal_hrd=cbr -vcodec libx264 -f mpegts -muxrate 3200K -y output.ts
cat output.ts | mpv - --cache=100000
`
shows the same behaviour. 
Apart from that, I am out of ideas, but maybe these pointers can help to find the issue...

**Comment by kokoko3k** [comment]
good finding, at least the issue has a workaround.
I did not even know that default precise seeking was different from the hr one.
@wm4; i did not understood your comment.

**Comment by wm4** [comment]
I conclude ffmpeg's seeking code is fucked, at least if the file fits in the cache. If it doesn't fit, it's possible that the demuxer reads outside of the cache, which is not expected to work, and things will just blow up.

With hr-seek, the player will just continue decoding until the target is reached, even if the seek is completely off - so there's a slightly better chance of it working.

Anyway, closing. Unless somebody minds?

**Comment by kokoko3k** [comment]
Is ok to me.

**Comment by olifre** [comment]
Also fine for me!

**Comment by falcon03** [comment]
I do experience the same issue when playing the streams produced by my dvb-t/t2 network tuner. Is there any fix/workaround?

Seeking by using Shift+Arrows does not work for me: it's slow and the stream freezes after seeking for a while. Also Kodi/VLC don't have problem seeking within these streams, so if this is a FFMpeg bug there should be a workaround I guess.

**Comment by wm4** [comment]
Try with git master (pushed something just now) + `--demuxer-lavf-hacks=no`. This should disable some special-handling for seeking in ts.

Note that while kodi probably uses libavformat for .ts (I don't know), VLC definitely does not.
