### ISSUE TITLE
Add support for the Enhanced LRC format (A2 extension)

### ISSUE THREAD

**Issue by PureTryOut** [mpv-player/mpv#15190]
### Expected behavior of the wanted feature

MPV already supports basic LRC to have lyrics play along with a song. However it would be nice if MPV also supported the Enhanced LRC format (the A2 extension).

https://en.wikipedia.org/wiki/LRC_(file_format)#A2_extension_(Enhanced_LRC_format)

Using that extension a player like MPV can highlight each individual word when it needs to be sung, this is useful for example for karaoke.

With the format each word is wrapped around additional timestamps in the `<mm:ss.xx>` format.
Note that there will often be an "accurate timestamp" before the first word in a sentence which is useful so the lyric can be shown on screen before the first word in it is actually sung/highlighted.

### Sample Files

[Armin van Buuren & Kensington - Heading Up High.txt](https://github.com/user-attachments/files/17535048/Armin.van.Buuren.Kensington.-.Heading.Up.High.txt)

GitHub doesn't allow LRC files to be uploaded (wrong file extension) so just rename the file from `.txt` to `.lrc`.

**Comment by llyyr** [comment]
This is a feature request for ffmpeg, once ffmpeg supports it nothing needs to be done on mpv's side to support it

**Comment by groutoutlook** [comment]
hi, for anyone come from the future, after 2 years there are still nothing on `ffmpeg` with the enhanced LRC..

EDIT: anyone looking for this kind of usage should look at `.ass` instead of `.lrc`, they work, now, and instantly.
