### ISSUE TITLE
Directly playing a playlist file does not support list of files while --playlist does

### ISSUE THREAD

**Issue by pxia** [mpv-player/mpv#15193]
### mpv Information

```bash
mpv v0.39.0-244-ga670f75679 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Oct 27 2024 14:22:13
libplacebo version: v7.349.0
FFmpeg version: n7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

```text
- macOS version: 15.0.1 (24A348)
- Source of mpv: github
- Introduced in version: n/a
```

### Reproduction Steps

Create a `playlist.txt` containing a list of local files, then `mpv playlist.txt`

### Expected Behavior

playlist being played

### Actual Behavior

```
$ mpv playlist.txt
Failed to recognize file format.
Exiting... (Errors when loading file)
```

meanwhile using --playlist option

```
$ mpv --playlist=playlist.txt
[playlist] Reading plaintext playlist.
Playing: /Users/xia/Downloads/2599172973.mp4
 ● Video  --vid=1  (h264 1920x1080 60.1449 fps) [default]
 ● Audio  --aid=1  (aac 2ch 48000 Hz 129 kbps) [default]
Using hardware decoding (videotoolbox).
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [gpu-next] 1920x1080 videotoolbox[nv12]
2024-10-27 14:24:14.134 mpv[85388:11691593] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-27 14:24:14.134 mpv[85388:11691593] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
Saving state.
AV: 00:00:00 / 00:00:06 (0%) A-V:  0.000
[+-----------------------------------------------------------------------------]
Exiting... (Quit)
```

This behavior contradicts the `--playlist` option documentation unless I'm missing something, which says:

> If no format is detected, it will be treated as list of files, separated by newline characters.

> You can play playlists directly, without this option.

I think either the behavior needs to be updated or the doc needs more clarification. Thanks in advance!

### Log File

[mpvlog.txt](https://github.com/user-attachments/files/17535489/mpvlog.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
Rename it to playlist.m3u.

**Comment by Dudemanguy** [comment]
`You may need this option to load plaintext files as a playlist.`

It's working as expected.
