### ISSUE TITLE
Skip to linked timestamp does not work after youtube-dl change

### ISSUE THREAD

**Issue by SirCmpwn** [mpv-player/mpv#1519]
Previously, a link like [this](http://youtu.be/G8sspkc9-E4?t=24s) would skip to the timestamp in the link. Now it plays from the start.

**Comment by ChrisK2** [comment]
huh? This never worked.

**Comment by SirCmpwn** [comment]
Nope, it totally used to work.

**Comment by wm4** [comment]
Although it would be nice if it did.

**Comment by ChrisK2** [comment]
Certainly, but currently youtube-dl doesn't even parse that info (but they already have issues filed for this).

**Comment by SirCmpwn** [comment]
I think it's reasonable to leave parsing that up to mpv. It seems like seeking is clearly the responsibility of the player.

**Comment by wm4** [comment]
>I think it's reasonable to leave parsing that up to mpv.

No.

**Comment by SirCmpwn** [comment]
You could also *maybe* address the second bit, instead of just sounding like a prick.

>It seems like seeking is clearly the responsibility of the player.

How is an external tool supposed to be responsible for seeking during playback?

**Comment by wm4** [comment]
>How is an external tool supposed to be responsible for seeking during playback?

Magic?

The prick-free response to that is, youtube-dl should tell us by how much to seek, which is what the filed issue mentioned by Chrisk is about.

**Comment by 0xACE** [comment]
Lua script?

https://gist.github.com/Shudouken/0233126a99627be217a4

put it in `~/.mpv/scripts`

**Comment by wm4** [comment]
Depends on ytdl returning sane infos. (How hard can it be...)

**Comment by SirCmpwn** [comment]
Yeah, it should be pretty easy. I've been meaning to do it when I have a spare moment for a while now.

**Comment by wm4** [comment]
I was pretty sure there was a ytdl issue for parsing the time parameter in the URL and returning it in the JSON, but I can't find it.

**Comment by ChrisK2** [comment]
https://github.com/rg3/youtube-dl/issues/642

**Comment by jaimeMF** [comment]
In the next version of youtube-dl the star time is extracted and exposed in the `start_time` field, there's also an `end_time` field but I don't know if it's useful for mpv.

**Comment by wm4** [comment]
Nice!

**Comment by ChrisK2** [comment]
Nice indeed. Now the question is, should we also support the ``end`` parameter? It probably doesn't get used widely and may cause unexpected behaviour when the player exits in the middle of the file for no immediately apparent reason (assuming the user didn't fully inspect the URL before passing it to mpv).

**Comment by wm4** [comment]
Fixed via the PR above.
