### ISSUE TITLE
Smoothmotion: mf:// playback freezes / idles

### ISSUE THREAD

**Issue by olifre** [mpv-player/mpv#1521]
Using 
`mpv "mf://*.jpg" --mf-fps=5 -v -vo opengl-hq:smoothmotion`
playback freezes (idles) after a few pictures - unless mouse is moving over the video-window or keys are pressed (i.e. anything issueing commands). 

`mf://` Still works fine without smoothmotion.

**Comment by olifre** [comment]
Update: I found it works fine if I use
`mpv "mf://*.jpg" --mf-fps=10 -v -vo opengl-hq:smoothmotion`
My refresh is 120 Hz. Sounds like an issue with low fps vs. high refresh rate?

**Comment by wm4** [comment]
>Sounds like an issue with low fps vs. high refresh rate?

Yes. Not sure if fully fixed.

**Comment by olifre** [comment]
> Yes. Not sure if fully fixed.

At least for the examples I have at hand, it seems so... `mf://` on a 120 Hz display is probably also the worst, but still realistic case.
