### ISSUE TITLE
seekable property, always yes if there is a cache?

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1522]
It seems that mpv exports the seekable property with "yes" value everytime a cached stream is played.
While this is justified because one can actually seek within the cache, it may lead to unexpected behaviour if the user try to seek into an uncached stream point.
Actually mpv informs the user about that, you know:
```
Stream is not seekable.
Enabling seeking because stream cache is active.
```
But i'm adapting a gui frontend to mpv (was mplayer), and i don't like the idea of parsing human-readable strings, so it would be great if that info is exported, maybe with a raw property (=seekable?) or by splitting the seekable property into:
1-the old style "seekable" property
2-a new "seekable-cache" property

What do you think?

**Comment by wm4** [comment]
What do you want to do with this information? Would a property that tells you that seeking "might be broken" work too? It'd have exactly the same behavior (at least for now), but a slightly different intention.

**Comment by kokoko3k** [comment]
The use case is the following:
Say i'm playing a stream through http and the server does not allow me to freely seek within the remote file (ie: does not support resume); my gui tells the user: "go on, seek to the point you like", and the user clicks on a far point of the progress widget.
What will probably happens is that mpv somehow hangs waiting for some data to arrive to that point, leaving the user in a "limbo"
--
With mplayer backend i used to inform the user about that and allowing only relative seeks to limit the problems.

When it comes to the exported property, my opinion is that if a stream is always seekable when the cache is active, then having seekable=yes just because of that is redundant,dispensable.
So, I'd invert the logic by exporting seekable=no if the seek is only possible within the cache.

If not possible, another property that would export the information that seeking is actually broken outside the cache would come handy anyway.

thanks.

**Comment by wm4** [comment]
>When it comes to the exported property, my opinion is that if a stream is always seekable when the cache is active, then having seekable=yes just because of that is redundant,dispensable. (because is equivalent to reading the cache property, am i right?)
>So, I'd invert the logic by exporting seekable=no if the seek is only possible within the cache.

The main point of this property is actually that it reflects exactly whether the core allows seek commands to go through, and also whether the command line "UI" enables or disables seek commands. So I don't think it's wrong to export the property in this form, instead of duplicating the logic "cache => seekable" in every client.

**Comment by kokoko3k** [comment]
Got it.
Something like "seek-broken" or whatever would do the trick as well.

**Comment by wm4** [comment]
Called it ``partially-seekable``. I hope it works as intended.

**Comment by kokoko3k** [comment]
Thanks, it works fine.
