### ISSUE TITLE
[encoding] section executes twice on startup

### ISSUE THREAD

**Issue by Arcitec** [mpv-player/mpv#15224]
### mpv Information

```bash
mpv 0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: 6.1.2
FFmpeg library versions:
   libavcodec      60.31.102
   libavdevice     60.3.100
   libavfilter     9.12.100
   libavformat     60.16.100
   libavutil       58.29.100
   libswresample   4.12.100
   libswscale      7.5.100
```

### Important Information

```text
Fedora 40, built mpv manually from 0.39.0.
```

### Reproduction Steps

**~/.config/mpv/mpv.conf:**

```ini
[encoding]
script=~~/encoder-scripts/load-encoder-keybinds.lua
```

**~/.config/mpv/encoder-scripts/load-encoder-keybinds.lua:**

```lua
local mp = require("mp")
local msg = require("mp.msg")

local encoder_conf_name = "input-encoder.conf"
local encoder_conf_path = mp.find_config_file(encoder_conf_name)

if not encoder_conf_path or encoder_conf_path == encoder_conf_name then
	msg.info('Could not find "' .. encoder_conf_name .. '". Skipping.')
else
	msg.info('Loading input config: "' .. encoder_conf_path .. '".')
	mp.command_native({ "load-input-conf", encoder_conf_path })
end
```

**Start MPV with these options:**

```sh
mkfifo /tmp/mpv-enc
mpv --o=/tmp/mpv-enc --of=nut --ovc=rawvideo --oac=pcm_s16le <video file>
```

You will see this (never mind the message, the important part is "keybinds2" showing that it loaded the script twice):

```
[load_encoder_keybinds] Loading input config: "/home/johnny/.config/mpv/input-encoder.conf".
[load_encoder_keybinds2] Loading input config: "/home/johnny/.config/mpv/input-encoder.conf".
```

I have already verified that no script loads at all if I remove the `script=` config line. So it's definitely caused by the `[encoder]` section/profile executing twice.

### Expected Behavior

Encoder section should only execute once.

### Actual Behavior

Encoder config section executes twice.

### Log File

Not relevant.

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
> Log File

>Not relevant.

This is absolutely relevant, there's a lot of logging that mpv does when it comes to how profiles are processed or applied and would help single down the exact component responsible for a bug (if any).

**Comment by kasper93** [comment]
> [encoder] section/profile executing twice.

There is no guarantee that profiles are not "entered twice". Profiles are not something that is "executed", they represent a state that we enter or leave.

**Comment by Arcitec** [comment]
@llyyr Alright the log file is here:

[output.txt](https://github.com/user-attachments/files/17564522/output.txt)

It shows that the `[encoding]` profile is applied twice.

Here's my encoding profile:

```ini
[encoding]
include=~~/vr-profiles.conf
script=~~/encoder-scripts/load-encoder-keybinds.lua
```

These messages are repeated twice in the log:

```
[cplayer] Reading config file /home/johnny/.config/mpv/vr-profiles.conf
[cplayer] Setting option 'scripts-append' = '~~/encoder-scripts/load-encoder-keybinds.lua' (flags = 4)
```

@kasper93 I can see the point of letting mpv run profiles multiple times.

But is there anything I can at least do to guard myself against repeated inclusion of the same script? Can my script detect that it has already been loaded once and immediately `return/exit` so it doesn't run the code twice?

Or perhaps the `script=` setting could have a built-in guard against loading the same script code many times?

**Comment by Arcitec** [comment]
> It is fine for your script to be loaded and do nothing.

Yeah that's my goal. I am ok with the script being loaded twice. I just wondered if there's a way I can ensure that the script only does its job once?

Something like:

```lua
if mp.has_registered_something("iwashere") then
  return
end
mp.register_something("iwashere")
```

Like a guard against multiple runs.

**Comment by llyyr** [comment]
> Load your script once and do whatever you need to do based on the state on the mpv

While this is true and a potential solution, I'm slightly interested in finding out why the profile is being loaded twice in encoding mode. Inside encoding mode, your config is ignored and only options under `[encoding]` is loaded (or if you specified a profile with `--profile`). So I can't intuitively think of why it would get processed twice

> I just wondered if there's a way I can ensure that the script only does its job once?

You can use `user-data` to store "script-loaded" or something and check for that.

**Comment by kasper93** [comment]
> Yeah that's my goal. I am ok with the script being loaded twice. I just wondered if there's a way I can ensure that the script only does its job once?

Load the script once outside the profile.

**Comment by Arcitec** [comment]
> Load the script once outside the profile.

That's not possible because the mpv encoding mode ignores everything outside of `[encoding]`. It's a design choice mentioned here:

"It's also possible to define default encoding options by putting them into the section named `[encoding]`. (This behavior changed after mpv 0.3.x. In mpv 0.3.x, config options in the default section / no section were applied to encoding. This is not the case anymore.)"

From:  https://github.com/mpv-player/mpv/blob/master/DOCS/encoding.rst

---

> You can use `user-data` to store "script-loaded" or something and check for that.

Thanks, that taught me something I didn't know was possible! Unfortunately it turns out that the two scripts load in parallel, so usually they can't see each other's value and both run anyway, hehe.

```
[load_encoder_keybinds2] nil
[load_encoder_keybinds] nil
```

From this code change at the top of my script:

```lua
local mp = require 'mp'
local msg = require 'mp.msg'

local ud_key = "user-data/scripts/load-encoder-keybinds/loaded"
local prev_val = mp.get_property_native(ud_key)
msg.info(prev_val)
mp.set_property_native(ud_key, "Hello World")
```

I get "hello world" like 30% of the times.

But I see that you found the actual issue and made a pull request! Awesome! :) I can also help clarify something about it over there so I'll comment over there.
