### ISSUE TITLE
Scaling bug with anamorphic video

### ISSUE THREAD

**Issue by wiiaboo** [mpv-player/mpv#1523]
Scalers other than bilinear and bicubic_fast seem to repeat a few pixels in the middle of the video when scaling from 854x480 to 853x480.

[Screenshot](https://i.fsbn.eu/OUe.png)
[Example video](https://i.fsbn.eu/0kS.webm) (3MB)
Video produced via screen capturing `mpv --no-config --vo=opengl:scale=spline36`
mpv -V:
```mpv git-f47b14b (C) 2000-2015 mpv/MPlayer/mplayer2 projects
built on 2015-01-26T03:13:24```

**Comment by lachs0r** [comment]
Can’t reproduce, at least not with any of my samples.
Can you upload a short cut?

**Comment by wiiaboo** [comment]
The exact clip: https://i.fsbn.eu/inahogod.webm (has sound and it's ~27MB)

**Comment by lachs0r** [comment]
Yeah, looks fine here, on nvidia and a bunch of Mesa drivers
(r300g, nouveau, i915). Random GL implementation quirks? :/

**Comment by wiiaboo** [comment]
Windows 8.1 x64 and AMD 7870 with latest drivers here.

**Comment by wiiaboo** [comment]
Looks to happen there too. Also with your builds, so it's another windows-only bug, probably.

**Comment by lachs0r** [comment]
Actually I can reproduce this with my Windows builds. Guess I should update them.

**Comment by wiiaboo** [comment]
Managed to pinpoint the approximate date to between your 20150120 and 20150123 builds.

**Comment by wiiaboo** [comment]
OK, finally found the offending commit: https://github.com/mpv-player/mpv/commit/02df9886ea239a8efa578677d44ee9b5f74be422

**Comment by wm4** [comment]
@haasn

**Comment by haasn** [comment]
This is somewhat worrysome, actually. Can we confirm that it only happens on Windows?

spline36, at least in theory, only samples from exact pixel coordinates, GL_NEAREST and GL_LINEAR should produce the exact same result.

Either spline36 is broken or something is fundamentally broken on Windows. Not sure which.

**Comment by wm4** [comment]
Yes, it's quite possible that there is something fundamentally broken either in our code or on windows.

**Comment by haasn** [comment]
@wiiaboo Can you upload screenshots of -vo scale=nearest before and after the commit, respectively?

**Comment by haasn** [comment]
@wiiaboo Can you upload screenshots of scale=nearest before and after the commit, respectively?

**Comment by wm4** [comment]
Actually I'm getting it too on Linux: ``mpv inahogod.webm  --start=5.5 --pause``

It's extremely visible when switching between bilinear and defaults.

**Comment by wm4** [comment]
This probably happens only because the size of the video is not-mod-2, with 4:2:0 sub sampling. So this is probably not too critical, and only the hack for non-aligned chroma sizes is broken.

**Comment by wiiaboo** [comment]
@haasn 
`git checkout 02df988` https://i.fsbn.eu/nearest-02df988.png
`git checkout HEAD~1` https://i.fsbn.eu/nearest-f24c2e0.png
drastically different results with supposedly the same scaler.

**Comment by haasn** [comment]
This bug is present because the scaler is broken for anamorphic video, pixels are not sampled accurately. The code in gl_video_scalers dealing with the video size is suspect, perhaps the passed value is not accurate.

This is not caused by the GL_NEAREST change, but that change makes it (much) more obvious. You can look into it if you want, or I can when I get home.

**Comment by wm4** [comment]
>This bug is present because the scaler is broken for anamorphic video, pixels are not sampled accurately. 

But there is no anamorphic video anywhere.

**Comment by wiiaboo** [comment]
Yes, the video is actually YUV 420 853x480. I created it with --vf-add=scale=-2:480:noup=2.

**Comment by wm4** [comment]
Shitty cascading corner cases.

**Comment by haasn** [comment]
Oh, I see what you mean now. I was under the impression that it was related to anamorphic video, based on the initial description, but that's really just an artifact of the resulting video size being odd.
