### ISSUE TITLE
Context menu partially broken in latest mpv builds

### ISSUE THREAD

**Issue by averagePedestrian** [mpv-player/mpv#15233]
### mpv Information

```bash
mpv v0.39.0-269-g41cff490 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Oct 30 2024 12:06:16
libplacebo version: v7.349.0 (v7.349.0-19-g118d810-dirty)
FFmpeg version: N-117673-gbb57b7801
FFmpeg library versions:
   libavcodec      61.22.100
   libavdevice     61.4.100
   libavfilter     10.6.100
   libavformat     61.9.100
   libavutil       59.46.100
   libswresample   5.4.100
   libswscale      8.9.101
```

### Other Information

```text
- Windows version: Windows 10 22H2 (OS Build 19045.4894)
- GPU model, driver and version: GTX 1660Ti, v537.58 
- Source of mpv: Windows builds by zhongfly (git)
- Introduced in version:
```

### Reproduction Steps

1. Download `dyn_menu.lua` from [tsl0922/mpv-menu-plugin](https://github.com/tsl0922/mpv-menu-plugin/blob/main/src/lua/dyn_menu.lua) and place it inside `~/scripts`.
2. Download the example menu configuration file, `input.conf`, from [tsl0922/input.conf](https://gist.github.com/tsl0922/8989aa32994b0448a2652ee260348a35) and place it inside the `portable_config` directory.

### Expected Behavior

Following the merge of right-click context menu support (https://github.com/mpv-player/mpv/pull/13700), `dyn_menu.lua` alone should be enough for context menu functionality, without needing `menu.dll` or `dialog.lua` to be placed into the `~/scripts` folder 

### Actual Behavior

In the latest mpv builds (GitHub CI, shinchiro Windows build, and zhongfly):
- The context menu only partially works with the `dyn_menu.lua` script from the main branch. Right-clicking does bring up a context menu, but clicking options like `Open > Files`, which should open a file selection dialogue, does not work. This functionality seems to require all three files present in the `~~/scripts` directory, contrary to the expected behaviour.
- Additionally, using the `dyn_menu.lua` script downloaded from the GitHub releases page results in the context menu failing to display altogether.

### Log File

[output.txt](https://github.com/user-attachments/files/17591318/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
> like Open > Files, which should open a file selection dialogue

File open dialog is not implemented/supported. Only context menu is supported. Patches welcome, there is currently no plans to add this.

**Comment by averagePedestrian** [comment]
> File open dialog is not implemented/supported. Only context menu is supported. Patches welcome, there is currently no plans to add this.

Really? I distinctly remember it working when the feature was first merged. I also remember it working a couple of months back, but I can't exactly pinpoint the time frame because I haven't been watching stuff lately. Let me downgrade to older versions and see if I'm right.

**Comment by averagePedestrian** [comment]
It seems I was mistaken; the open dialogue functionality was indeed never implemented.
