### ISSUE TITLE
ChrisK's build not working

### ISSUE THREAD

**Issue by asoksevil** [mpv-player/mpv#1526]
Hey there,

Just updated to Yosemite 10.10.1 and downloaded the latest build from ChrisK from here: http://sva.wakku.to/~chris/mpv_builds/mpv_latest.zip and I found out that mpg wasn't working at all, it did not open/play any video, constantly crashing.

Does anybody know what's going on?

**Comment by Cpuroast** [comment]
Do you actually mean Mpeg-1?
I just tried the same build with an Mpeg-1 file under 10.9.5 with no issues. 
I'll try the same build at work under 10.10.1 tomorrow.
mpv_20150124155829_git-13e3573.tar.bz2 is the build I tried, for which mpv_latest is currently an alias.

**Comment by ChrisK2** [comment]
Can't reproduce with newest build (mpv_20150127053312_git-00b2611.tar.bz2). Please download the newest build and try again. Post the crash report if it crashes again.

**Comment by asoksevil** [comment]
@Cpuroast 

No, I meant mpv.

@ChrisK2 

It's fixed, it's just that it took a while to open (30-40 seconds) For next updates it would be great to display a window what mpg is doing (building fonts, etc)

**Comment by Cpuroast** [comment]
Considering mpv on OSX is now heavily restricted on which fonts get fed to fontconfig, it's cache update is near instant and it should never appear "stalled".

**Comment by ChrisK2** [comment]
Displays a message is not possible. But caching should be quite fast unless your computer really slow or you have put lots of fonts where you shouldn't have.

**Comment by asoksevil** [comment]
@cpuroast @chrisk2

I am running a 2010 MacBook Air (Intel Core 2 Duo). Thanks for the info though

**Comment by wm4** [comment]
>Displaying a message is not possible. 

Well, you _could_ hack something with cocoa (maybe even into fontconfig), but yeah, that would be the kind of hack that is very awful but still increases userfriendliness a lot.
