### ISSUE TITLE
Secondary subtitles will not automatically adapt to the primary subtitle spacing.

### ISSUE THREAD

**Issue by zhouxinghong** [mpv-player/mpv#15267]
### mpv Information

```bash
mpv v0.39.0-300-g42ff6f92 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov  3 2024 00:06:03
libplacebo version: v7.349.0 (v7.349.0-19-g118d810-dirty)
FFmpeg version: N-117698-gc325f9c61
FFmpeg library versions:
   libavcodec      61.23.100
   libavdevice     61.4.100
   libavfilter     10.6.101
   libavformat     61.9.100
   libavutil       59.46.100
   libswresample   5.4.100
   libswscale      8.9.101
```

### Other Information

```text
- Windows version: 10 19044
- GPU model, driver and version:
- Source of mpv: 
  [MPV](https://github.com/shinchiro/mpv-winbuild-cmake/releases/download/20241103/mpv-x86_64-20241103-git-42ff6f9.7z)
- Introduced in version:
```

### Reproduction Steps

1. Start playing the video;

2. Add two subtitles to the video, one as the primary subtitle and the other as the secondary subtitle;

### Expected Behavior

The secondary subtitle should be able to automatically calculate and adapt to the spacing of the primary subtitle without a huge outer space between the two subtitles.

### Actual Behavior

Secondary subtitles cannot automatically calculate and fit the spacing of primary subtitles, and a huge external space will appear between the two subtitles.

### Log File

mpv --no-config 'https://ed198uy.cloudatacdn.com/u5kjvzfb5hf3sdgge4os4yspim4o7pxiydmdn3srdfseygh74ryxgx5sepaa/itnlis26tq~oPgARJ074D?token==tjsyfjmfpskihmx=13568932'

### Sample Files

Normal external spacing:
![2024-11-06_113448](https://github.com/user-attachments/assets/da7282b6-1788-45cb-8cc9-2aa5dc4f20b9)

![image](https://github.com/user-attachments/assets/eaf83534-7387-48bf-98a0-855dbf2f30e2)
Huge external spacing:
![2024-11-06_113715](https://github.com/user-attachments/assets/739f19c9-f0eb-4cc3-8a79-83b8cf842e48)

![2024-11-06_114435](https://github.com/user-attachments/assets/3f0401e5-2323-4453-b5a4-35f5b3152c93)

![2024-11-06_114246](https://github.com/user-attachments/assets/8bd0e7bb-069e-43bb-b205-ec4db0269e20)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
> The secondary subtitle should be able to automatically calculate and adapt to the spacing of the primary subtitle without a huge outer space between the two subtitles.

Wrong, the expected behavior is secondary subs are at the top. You didn't provide a log file and your sample is an ephemeral URL from a piracy site, so it's impossible to do anything about this issue
