### ISSUE TITLE
mpv --of=rtsp | rtsp streaming way to fast

### ISSUE THREAD

**Issue by efschu** [mpv-player/mpv#15263]
### mpv Information

```bash
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: 6.1.1-3ubuntu5
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

```text
- Linux version: Ubuntu 24.04 LTS
- Kernel Version: 6.8.0-48-generic
- GPU Model: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series]
- Mesa/GPU Driver Version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.2
- Window Manager and Version: wayland 1.34-1
- Source mpv:
- Introduced in version:
```

### Reproduction Steps

I want to stream to my rtsp server by this command:
`mpv in.mkv --ovc=mpeg4 --of=rtsp --o=rtsp://192.168.0.83:8554/mystream`

in.mkv includes following stream:
`Stream #0:0(ger): Video: h264 (High), yuv420p(tv, bt470bg/unknown/unknown, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)`

which has 25fps

### Expected Behavior

Stream it to rtsp server with correct fps, in this case with 25fps

### Actual Behavior

It is streaming as fast as it can encode it, in this case with around 100fps

### Log File

[output.txt](https://github.com/user-attachments/files/17631438/output.txt)

### Sample Files

it happens with any video file

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [x] I attached the backtrace in the case of a crash.

**Comment by sfan5** [comment]
This is not a bug. Encoding does not have a "realtime" mode.
Consider using ffmpeg instead.

**Comment by efschu** [comment]
Well, ffmpeg does not support vapoursynth vpy filters like mpv does.

For now I pipe it with mpv to a named pipe and use this pipe with ffmpeg. 

But, as I saw rtsp output is included in mpv, I thought to use it directly.

Sooo, I'm a bit confused, why the rtsp option even exists, cus it will always encode way to fast?

**Comment by efschu** [comment]
The correct command I am using with working fps is:

`mpv --hwdec=yes --vf-add="realtime" --ovc=libx264 --ovcopts="preset=fast" --ovcopts="qp=18" --ovcopts="bf=0" --of=rtsp --audio-samplerate=44100 --o=rtsp://192.168.0.83:8554/mystream --vf-add="realtime" --vf=vapoursynth="script.vpy" --vf-add="realtime" --input-ipc-server=mpvsocket --framedrop=decoder+vo --idle`

I dunno why I had to add `--vf-add="realtime"` multiple times, but I have some videos where this was the only working command so far.

So no need to pipe a video around, mpv can do all what is needed.
