### ISSUE TITLE
OSD should show all available subtitle and audio tracks when clicking their buttons instead of just cycling through them

### ISSUE THREAD

**Issue by Pentaphon** [mpv-player/mpv#15275]
### Expected behavior of the wanted feature

Instead of having a button that just cycles through subtitle and audio tracks, the button should bring up a "drop up" list", or a "launcher" OSD element that shows all available tracks. This will make it much easier to get through files with lots of subtitles.  The following options are possible with a simple OSD:

Option 1: "Drop up" list

<img width="523" alt="74101196-854e3100-4b37-11ea-85fc-2fdf83f8fa35" src="https://github.com/user-attachments/assets/72d10bed-f101-44a4-9685-5145faa641bf">

Option 2:  Middle of window "Launcher" OSD element

![launcher](https://github.com/user-attachments/assets/b2f17903-ba86-41fb-9ef5-708d59b47709)

**Comment by guidocella** [comment]
That's implemented on master.

**Comment by Pentaphon** [comment]
> That's implemented on master.

When did that happen? I'm using an 11/03 build.

**Comment by guidocella** [comment]
cd2acb477c

**Comment by Pentaphon** [comment]
Thanks guidocella. Closing this now. I didn't see it since I was using osc lua from https://github.com/po5/thumbfast and it only appeared 2 weeks ago so I asked the thumbfast dev to merge his custom osc.lua with `master
`
