### ISSUE TITLE
error opening/initializing vo window

### ISSUE THREAD

**Issue by richardpl** [mpv-player/mpv#15278]
### mpv Information

```bash
mpv v0.39.0-323-g3bbc770b14 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov  9 2024 09:49:35
libplacebo version: v7.349.0 (v7.349.0-19-g118d8106)
FFmpeg version: N-118482-g19bc5f88b8
FFmpeg library versions:
   libavcodec      61.24.100
   libavdevice     61.4.100
   libavfilter     10.6.101
   libavformat     61.9.100
   libavutil       59.46.100
   libswresample   5.4.100
   libswscale      8.9.101
```

### Other Information

```text
- Linux version: Arch Linux
- Kernel Version: Linux archlinux 6.11.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000 x86_64 GNU/Linux
- GPU Model: 0000:00:02.0 VGA compatible controller [0300]: Intel Corporation Raptor Lake-S UHD Graphics [8086:a788] (rev 04)
0000:01:00.0 VGA compatible controller [0300]: NVIDIA Corporation AD106M [GeForce RTX 4070 Max-Q / Mobile] [10de:2860] (rev a1)
- Mesa/GPU Driver Version: OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.2.6-arch1.1
- Window Manager and Version: dwm-6.5
- Source of mpv: this repository
- Latest known working version: N/A
- Issue started after the following happened: N/A
```

### Reproduction Steps

simply start playing some video

### Expected Behavior

video window with pixels

### Actual Behavior

no window at all

### Log File

[output.log](https://github.com/user-attachments/files/17686810/output.log)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by sfan5** [comment]
Your mpv is built without x11 or wayland, no surprise it can't open a window.

**Comment by llyyr** [comment]
mpv is built without any gpu context besides displayvk, build with x11/wayland accordingly

**Comment by richardpl** [comment]
Thanks, it was not obvious that I also need to install libxss and enable glslang in libplacebo.
