### ISSUE TITLE
Incorrect chroma location handling with vo=gpu

### ISSUE THREAD

**Issue by emotion3459** [mpv-player/mpv#15288]
### mpv Information

```bash
mpv v0.39.0-300-g42ff6f92 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov  3 2024 00:06:03
libplacebo version: v7.349.0 (v7.349.0-19-g118d810-dirty)
FFmpeg version: N-117698-gc325f9c61
FFmpeg library versions:
   libavcodec      61.23.100
   libavdevice     61.4.100
   libavfilter     10.6.101
   libavformat     61.9.100
   libavutil       59.46.100
   libswresample   5.4.100
   libswscale      8.9.101
```

### Other Information

```text
- Windows version: Windows 11
- GPU model, driver and version: GTX 1080Ti, Driver 561.09
- Source of mpv: scoop
```

### Reproduction Steps

Use vo=gpu and open a subsampled file with top-left chroma location.

### Expected Behavior

Behavior should match gpu-next.

### Actual Behavior

Chroma is erroneously shifted downwards. [Comparison](https://slow.pics/c/sAgcrhMR)

### Log File

[output.txt](https://github.com/user-attachments/files/17690398/output.txt)

### Sample Files

[Sample](https://files.catbox.moe/2ujweb.mkv)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
Chroma offset is flipped vertically in vo_gpu. Will fix later, when I get some time.
