### ISSUE TITLE
Accessing estimated-vf-fps property in vo-vapoursynth filter

### ISSUE THREAD

**Issue by rjinvajmi** [mpv-player/mpv#15289]
### Expected behavior of the wanted feature

in vapoursynth scripts which are called via mpv, the container_fps variable is available, but it can contain bogus values (especiallly in variable frame rate videos)

In mpv, the estimated-vf-fps variable gives more accurate results, but how can this variable be accessed in vapoursynth "

Currently,a vapoursynth script gives this error for 
`
print(estimated_vf_fps) (or print(estimated-vf-fps)
`

[vapoursynth] Script evaluation failed:                                               
[vapoursynth] Python exception: name 'estimated_vf_fps' is not defined                
[vapoursynth]                                                                         
[vapoursynth] Traceback (most recent call last):                                      
[vapoursynth]   File "src\\cython\\vapoursynth.pyx", line 3124, in vapoursynth._vpy_evaluate
[vapoursynth]   File "src\\cython\\vapoursynth.pyx", line 3125, in vapoursynth._vpy_evaluate
[vapoursynth]   File "/home/ani/.mpv/rife/auto_rife.vpy", line 25, in <module>        
[vapoursynth]     print(estimated_vf_fps)                                             
[vapoursynth] NameError: name 'estimated_vf_fps' is not defined                       
[vapoursynth]                                                                         
[vapoursynth] could not init VS

may be related to https://github.com/mpv-player/mpv/issues/4133

**Comment by sfan5** [comment]
That would be a circular dependency because [`estimated-vf-fps`](https://mpv.io/manual/master/#command-interface-estimated-vf-fps) depends on what the filter chain outputs.

> Currently, script gives this error for print(estimated_vf_fps)

of course it does, because only properties documented here exist: https://mpv.io/manual/master/#video-filters-vapoursynth

**Comment by rjinvajmi** [comment]
> of course it does, because only properties documented here exist: https://mpv.io/manual/master/#video-filters-vapoursynth

thanks. Is there a way to set other mpv properties (for eg: glsl-shaders) from the vapoursynth script . i.e. if we can't read generic mpv-properties from vapoursynth, can we write to them instead?

Of course,since a vapoursynth script is "normal" pytthon code, one can always start mpv with --input-ipc-serve and then write to the unix socket in python to change mpv properties. But a pure vapoursynth way would be better.

**Comment by sfan5** [comment]
> Is there a way to set other mpv properties (for eg: glsl-shaders) from the vapoursynth script

No.
A vapoursynth script is supposed to do video filtering and not control the running mpv instance in arbitrary ways.

**Comment by CrendKing** [comment]
@rjinvajmi If the video is relatively fixed framerate, you can use the following script to pass it to the VapourSynth script:
```
mp.register_event('file-loaded', function()
    mp.add_timeout(3, function()
        local fps = mp.get_property_native('estimated-vf-fps')
        mp.set_property_native('vf', string.format('vapoursynth="%s":user-data=%.2f', 'script.vpy', fps))
    end)
end)
```
This script waits for 3 seconds for the property to be available, then pass it with the [`user-data` option](https://mpv.io/manual/master/#video-filters-user-data). You can access the whole user data string in VPY with `user_data`.

If the video is variable framerate that the FPS always changes, I'm afraid there is probably no way to send always-up-to-date value to VPY.

**Comment by kasper93** [comment]
Instead of unobserve_property, you can compare to last set value with some threshold and reinsert vf if the value changed significantly enough.

**Comment by CrendKing** [comment]
Sure, if the value doesn't change too frequently (like every second).
