### ISSUE TITLE
--sub-back-color not working

### ISSUE THREAD

**Issue by erns8** [mpv-player/mpv#15294]
### mpv Information

```bash
mpv 0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 28 2024 01:31:20
libplacebo version: v7.349.0 (v7.349.0-13-ga018ab0-dirty)
FFmpeg version: N-117212-g01c47dd23
FFmpeg library versions:
   libavcodec      61.20.100
   libavdevice     61.4.100
   libavfilter     10.5.100
   libavformat     61.8.100
   libavutil       59.40.100
   libswresample   5.4.100
   libswscale      8.4.100
```

### Other Information

```text
- Windows 11 23H2
- Source of mpv: https://sourceforge.net/projects/mpv-player-windows/files/release/mpv-0.39.0-x86_64-v3.7z/download
- GPU model, driver and version: RX 7700 XT - 24.10.1
- Latest known working version: 0.38.0
```

### Reproduction Steps

Launch (or load with --sid) .srt subtitles with --sub-back-color

### Expected Behavior

With mpv 0.38.0
`mpv output.mkv --no-config --sub-back-color=0.0/0.0/0.0/0.75 --sid=1`

![image](https://github.com/user-attachments/assets/934916f3-1158-445f-9283-fa1a3ad3fd97)

### Actual Behavior

With mpv 0.39.0 (also not working with mpv v0.39.0-325-gd66ed2d8)
`mpv output.mkv --no-config --sub-back-color=0.0/0.0/0.0/0.75 --sid=1`

![image](https://github.com/user-attachments/assets/ca7e38cc-10cc-44ee-ad58-e2bf0dbb5dfb)

### Log File

gpu-debug disabled due to error:  The application has requested an operation that depends on an absent or incompatible component of the Software Development Kit (SDK). (0x887a002d)

[output.txt](https://github.com/user-attachments/files/17694759/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by Samillion** [comment]
```
-- sub-border-style=background-box
```

https://mpv.io/manual/master/#options-sub-border-style

**Comment by mrfragger** [comment]
Ctrl+Y              cycle-values sub-border-style background-box outline-and-shadow 
Alt+Y             cycle-values sub-back-color                     "#FF000000" "#80000000" "#60000000" "#000000" #! [Subtitle Colors] > [Style] > Sub Transparency for Background

**Comment by igorbaryshev** [comment]
sub-back-color doesn't work for me in both 0.39 and 0.38, nothing happens when I set the value
