### ISSUE TITLE
Client cannot give file list for audio-file and sub-file option

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1531]
`audio-file` option is defined as:
```c
OPT_STRING_APPEND_LIST("audio-file", audio_files, M_OPT_FILE),
```
and `sub-file` is defined in similar way, and setting "options/audio-file" always sets just one file instead of appending.

I suggest changing these option to OPT_PATHLIST or, adding new options such as `audio-files` and `sub-files` whose type is OPT_PATHLIST so that client can set file list directly.

**Comment by wm4** [comment]
This was explicitly changed, so that you can pass files containing ``,`` characters to these options.

However, you should be able to set the options using MPV_FORMAT_NODE containing a MPV_FORMAT_NODE_ARRAY.

**Comment by xylosper** [comment]
Oh, I didn't know that. I'll try mpv_node. Thank you.
