### ISSUE TITLE
how to limit youtube-dl premium quality

### ISSUE THREAD

**Issue by Azirine** [mpv-player/mpv#15315]
### Expected behavior of the wanted feature

YouTube premium quality 616 is slow to load and buggy (skipping to unloaded timestamp freezes download). It is possible to skip 616? I would much prefer 248 or similar.

**Comment by CounterPillow** [comment]
`--ytdl-format` accepts the same options as yt-dlp's `-f` option, see the "FORMAT SELECTION" section in the yt-dlp manual.
