### ISSUE TITLE
Dual GPU not accelerating correctly with --vulkan-device

### ISSUE THREAD

**Issue by rijnhard** [mpv-player/mpv#15311]
### mpv Information

```bash
mpv 0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0
FFmpeg version: 7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Other Information

```text
- Linux version: Fedora Linux 41 (KDE Plasma)
- Kernel Version: 6.9.12 (also on 6.11.7)
- GPU Model:
    00:01.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Kaveri [Radeon R7 Graphics] [1002:130f]
    03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 24 [Radeon RX 6400/6500 XT/6500M] [1002:743f] (rev c7)
- Mesa/GPU Driver Version: 24.2.6
- Window Manager and Version: KWin 6.2.3-1
- Source of mpv: Fedora repo
- Latest known working version: ? 
- Issue started after the following happened: n/a
```

### Reproduction Steps

Bare with me on this, I'm trying to make best of a broken world.

I have a TV connected to Kaveri (iGPU) HDMI, because of an outstanding amdgpu bug affecting my RX 6400 (which causes the TV to frequently disconnect), this means switcheroo is active. So the idea is to use the RX 6400 (dGPU) for the video decoding because the kaveri cannot handle H265@4k.

To simplify things, I can confirm that having the dGPU connected to the TV can play 4k H265 with hdr perfectly (barring screen disconnects), with the following profile. 
```
vo=gpu-next
gpu-api=vulkan
gpu-context=waylandvk
hwdec=vaapi
```

Now after some digging I found `--vulkan-device` which returns:
```
mpv --vulkan-device=help
WARNING: radv is not a conformant Vulkan implementation, testing use only.
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Available vulkan devices:
  'AMD Radeon R7 Graphics (RADV KAVERI)' (GPU 0, PCI ID 1002:130f, UUID 00000000-0000-0000-0100-000000000000)
  'AMD Radeon RX 6400 (RADV NAVI24)' (GPU 1, PCI ID 1002:743f, UUID 00000000-0300-0000-0000-000000000000)
  'llvmpipe (LLVM 19.1.0, 256 bits)' (GPU 2, PCI ID 10005:0, UUID 6d657361-3234-2e32-2e36-000000000000)
```

Now with the HDMI connected to the kaveri and switcheroo active, and simply adding the flag specifying the RX 6400 via name or uuid, doesn't error but doesn't change results. Results are as choppy as just using the kaveri without the RX 6400 installed.

Notes:
- as a negative test I passed some garbage to `--vulkan-device` and it does indeed error.
- I'm not expecting hdr to work because it's not supported by the kaveri.

### Expected Behavior

Should offload video decoding to the dGPU even under switcheroo when requested.

### Actual Behavior

Always uses primary gpu for decoding.

### Log File

[mpv.log](https://github.com/user-attachments/files/17754083/mpv.log)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by llyyr** [comment]
You need to use `DRI_PRIME=1` for this and a new enough Mesa (24.3 or newer) https://gitlab.freedesktop.org/mesa/mesa/-/commit/ed781c74032ec3ff893bd0d60d9b88a3055476f5

**Comment by rijnhard** [comment]
I have been using DRI_PRIME but didn't include it in the ticket because it had no effect, but I didn't know about the mesa bug! Thank you soo much for sharing that, 24.3 should be out soon, so that should then solve the problem.

And thank you for explaining the difference. It's been rough getting this new gpu and not being able to use it.

**Comment by llyyr** [comment]
You can make it work right now as well if you switch to x11 session on kwin, or run mpv under xwayland with `--gpu-context=x11vk`

**Comment by kasper93** [comment]
> Yeah the mesa team AFAIK is still experimenting with the vulkan decoding on amd, so it totally fails and doesn't have the required extension.

For this you have to define `RADV_PERFTEST=video_decode` to expose extensions, if your gpu is supported.

**Comment by rijnhard** [comment]
> You can make it work right now as well if you switch to x11 session on kwin, or run mpv under xwayland with `--gpu-context=x11vk`

I mean I can, but ewww. Tbh I haven't used x11 in the last 8 years on my htpc. And it's mostly been fine :p. I'd rather just keep experimenting and logging bugs and try to be helpful to the maintainers.

But I do appreciate the workaround

**Comment by rijnhard** [comment]
> > Yeah the mesa team AFAIK is still experimenting with the vulkan decoding on amd, so it totally fails and doesn't have the required extension.
> 
> For this you have to define `RADV_PERFTEST=video_decode` to expose extensions, if your gpu is supported.

Oooooooooo it worked on the kaveri! That's kinda insane, considering it's age. (I mean playback is still choppy, but it rendered), I'll be playing with this in the future.
