### ISSUE TITLE
Missing 16:10 aspect-ratio

### ISSUE THREAD

**Issue by ahimta** [mpv-player/mpv#15324]
### Expected behavior of the wanted feature

When clicking `Ctrl+A` repeatedly never get `16:10` aspect-ratio.

I looked into two likely relevant-parts which are the following:
1. https://github.com/mpv-player/mpv/blob/70aaba71d6e3071a732069a1d222d1eb4293faf2/player/command.c#L2386
2. https://github.com/mpv-player/mpv/blob/70aaba71d6e3071a732069a1d222d1eb4293faf2/player/command.c#L3125

But both don't help-much. Seems this is more concerned with mpv-properties which probably, and for very good-reasons, has significant-levels of indirection.

Honestly such changes better done by a maintainer as it's easier than even discussing/explaining to others. Unless what's needed/decided is to resolve some indirection or simplify the design/system to make such-details more tractable.

### Alternative behavior of the wanted feature

When clicking `Ctrl+A` repeatedly and around `16:9` aspect-ratio, should get to `16:10` aspect-ratio.

**Comment by guidocella** [comment]
That's defined in https://github.com/mpv-player/mpv/blob/dd5f2069b8b3e452e7cdca017942da07b02a69ad/etc/input.conf#L148. You can rebind shift+a to cycle through any aspect you want.

**Comment by ahimta** [comment]
Thank you for thoughtfully reading my-comment and noticing the `Ctrl`
blunder and I should've made the additional-effort of simply searching for
the property-name in the project.

I'd suggest `16:10` is added as it's quite-common nowadays. I have
two-devices that use it and the rest are mostly `16:9`.

The opposite likely-applies to `4:3` as it maybe relatively-rare and just
obfuscates the others. But this maybe a separate issue.

**Comment by Akemi** [comment]
closing this, since i agree with @na-na-hi on this and the keybinding can easily be changed to fit ones needs.

**Comment by ahimta** [comment]
You're thinking of this more from a technical-perspective than an
end-user's. Think like you do when using other products/apps.

An end-user, even a programmer, would just use another-player like VLC.
Don't take users not complaining as a sign of not-caring as most would just
be non-users.

Especially as mpv has no preferences in the UI. This makes it much-more
important to have what a user-needs by-default.

Anyway I'm just speaking my-mind and I understand that you won't even reply
as your previous-reply is sufficient.

**Comment by kasper93** [comment]
You might be interested in `--keepaspect=no`.

**Comment by kasper93** [comment]
> This isn't the right-place for it and likely you'll need to review your Snap approach

mpv doesn't support Snap or any other packaging solution.

**Comment by ahimta** [comment]
It probably does-implicitly through its-documentation like in
`CONFIGURATION FILES` section.

Anyway you're more-familiar with mpv and know-better than I.

**Comment by kasper93** [comment]
I don't know anything about mpv Snap, because it is not supported. `CONFIGURATION FILES` section describes in detail how various configuration files are used and where they are located. If you have any Snap or whatever questions they should be directed to person who maintains such package.

**Comment by llyyr** [comment]
> A separate-issue but seems changing the config works only using `~/snap/mpv/current/.config/mpv/input.conf`.

All snap config files are stored in `~/snap/APP_NAME/`. There's nothing mpv can do about it. How is it mpv's problem if the user is using a horrible "sandbox" solution that's probably worse than running `sudo mpv` but doesn't even understand the quirks of the sandbox?
