### ISSUE TITLE
Do not remove support for opengl-old.

### ISSUE THREAD

**Issue by felixq** [mpv-player/mpv#1532]
The Intel motherboard with integrated chipset have really bad drivers. I have no words to express how bad they are.
I have updated drivers, version of OpenGL that support is 1.4. It does not work with opengl option.
The direct3d and direct3d_shaders options have worse performance than opengl-old option.
mpv not support directx, which is the best support with Intel drivers. This last I checked with mplayer.
Also I have other hardware that only works with opengl-old.

Intel(R) Core(TM)2 Duo CPU     E6550  @ 2.33GHz
Windows 7 64-bit build 7601 [Service Pack 1]

thank you very much

**Comment by lachs0r** [comment]
At the risk of being very unhelpful, you have several alternative options:

a) Upgrade the toasters to something with more performance per Watt.
b) Move to an OS with less terrible drivers
   (very sure it’s not as bad on Linux).
c) Use VLC, MPC-HC or MPlayer.
d) Implement a compatible video renderer that is NOT using OpenGL 1.x and
   NOT using the ancient DirectX overlay renderer (how about something 
   EVR-based?)

**Comment by wm4** [comment]
I don't think we want to add opengl-old at this point.

But I find it surprising that even ``--vo=direct3d`` is slower?

**Comment by felixq** [comment]
Not exactly slower but more often jumps for no reason and takes more to start up sometimes.
It is not the OS, is Intel which makes bad drivers. Even Firefox has blocked all Intel drivers to enable hardware acceleration. The time when I found the key to activate it was a disaster.

I have used these players, mplayer2 and I was left with mplayer with smplayer as GUI, until I discovered mpv. I really liked mpv despite I had to read me full manual.

My knowledge of c are not so high to develop myself. Maybe later.

If you can not I'll stick to the latest version that supports it, it works well anyway. And occasionally I'll try the new versions.

Thank you very much.

**Comment by steinuil** [comment]
I would also personally have problems if `opengl-old` was removed as I'm using an old Mac that only supports up to OS X 10.7.5 because of its old hardware, and `direct3d` and `xv` are not an option on OS X.

*But* apparently 10.7.5 reached its end of life in october last year, and all Macs on which the newer releases of OS X are supported perform well with the `opengl` vo.

Basically I'm saying that if `opengl-old` is removed there's no need to replace it with a faster vo on OS X, as Macs that can't run other vo are (informally) deprecated.

**Comment by pigoz** [comment]
What's wrong with vo_opengl on OS X 10.7.5? Maybe I could add a minimal vo_corevideo VO.. if that's needed for some super old GPU

**Comment by steinuil** [comment]
Nothing is wrong, it's just that macs that don't support OS X >10.7 are very slow with it. And 10.7 is done for, that's all I'm saying.

**Comment by HealingTek** [comment]
Dropping opengl-old has also left me in the bind as my main video machine is an old laptop, running Linux, with an integrated Intel GPU that's too slow to render acceptably with any other output and isn't new enough to do OpenGL 2.1.

**Comment by wm4** [comment]
It definitely won't come back. Sorry.
