### ISSUE TITLE
Can't seek still image videos

### ISSUE THREAD

**Issue by Spider-Jerusalem** [mpv-player/mpv#1533]
Here's a <a href="https://a.pomf.se/qwfvjj.webm/">webm</a> created with the following ffmpeg command:
```
     ffmpeg -i image.jpg -i audio.flac -threads $(nproc) \
    -c:v libvpx -crf 10 -qmin 5 -qmax 55 \
    -vf scale=360:-1 -sws_flags lanczos -c:a libvorbis -ac 2 \
    -b:a 128K out.webm
```
Seeking seems to be supported in firefox, but seeking in mpv restart the video, without any error output by mpv.

**Comment by wm4** [comment]
The file contains a broken index (only 1 entry, pointing to the start of the file). Using ``--index=recreate`` helps, though it strangely jumps to the start of the file when seeking back.

Report this bug to ffmpeg.

**Comment by Spider-Jerusalem** [comment]
Ok, I'll report it.

**Comment by wm4** [comment]
I take this back. Actually, the file has only 1 video frame, so this is expected.

You still can try to convince ffmpeg to mux this as coverart picture instead, though.

The issue here is that mpv considers this file video, and seeks always are snapped to video frames.

**Comment by wm4** [comment]
With git master you now should be able to seek in this file, if you enable hr-seek. (Doing a single click on the OSC seek bar also does a hr-seek.)

However, it will always decode the entire audio from start until the seek target. This is because demuxers and file formats work this way, and there isn't too much that can be done about.

**Comment by Spider-Jerusalem** [comment]
Thanks for the fast work. I indeed saw that firefox did that (having to buffer after each seek even when playing the local file).

**Comment by wm4** [comment]
Hm, this issue will probably not show any new developments, so closing.
