### ISSUE TITLE
Can't play Youtube video after update to 0.7.3

### ISSUE THREAD

**Issue by MagikBSD** [mpv-player/mpv#1534]
When I try to play YT video I get following error.

: mpv https://www.youtube.com/watch?v=-RewiM53akE
Playing: https://www.youtube.com/watch?v=-RewiM53akE
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),))
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] tls: The TLS connection was non-properly terminated.
Failed to recognize file format.

Exiting... (Errors when loading file)

Currently I've installed mpv 0.7.3 and youtube-dl 2015.01.25 on FreeBSD 10.1.
Earlier using mpv 0.7.1 and youtube-dl 2014.11.26, everything works OK.

**Comment by Skibicki** [comment]
Found it reported here. https://github.com/rg3/youtube-dl/issues/4807

**Comment by jaimeMF** [comment]
@MagikBSD could you post at https://github.com/rg3/youtube-dl/issues/4807 the output of `youtube-dl --verbose "https://www.youtube.com/watch?v=-RewiM53akE"`?

**Comment by wm4** [comment]
Upstream bug report was closed.
