### ISSUE TITLE
Some subs aren't enabled at start or with v

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#1535]
But can be turned on via the Osc
This was relayed to me from another user who didn't provide (yet) a sample though in his cli it was reported as "(dvd_subtitle)"
I looked for a similar type file online & found one. Link is to a sample of 1st. min. It contains the video, 1 audio & 1 sub stream reported as "(hdmv_pgs_subtitle)"
Obviously I don't know much about about subs but thought I'd relay
http://www.datafilehost.com/d/8c719731

**Comment by kevmitch** [comment]
In addition to toggling subtitle visibility "v", there is also the matter of selecting *which* subtitle to track to display "j"/"J" one of which is "no subitlte". Clicking the OSD is equivalent to hitting the j key. To see subtitles, you must have them both enabled and have a non-null track selected. I agree, it is kind of confusing.

**Comment by mc4man** [comment]
Ok - thanks, I missed that little bit, maybe just because or because all the other files I have that have subs always open with them enabled.
After grabbing a few other files with subs I see some open with a sub selected (enabled & visible) & some open with no sub selected.

**Comment by wm4** [comment]
I guess I could extend the message if v is toggled but no subtitle is selected.

**Comment by bhrgunatha** [comment]
I have kind of the opposite problem - every .mkv file I open (that has a subtitle track) automatically displays the first one - regardless of whether I have enabled subtitles using v or selected a track using j. This has become very annoying as lots of videos now come with subtitle tracks for hard of hearing and they are always automatically displayed and I have to use v or j to turn them off.

**Comment by wm4** [comment]
Put ``sid=no`` into your config.

>regardless of whether I have enabled subtitles using v or selected a track using j. 

When you play multiple files in a row?

**Comment by bhrgunatha** [comment]
Yes. Thanks for the suggestion. So quick too!
I tried putting `v=no` in my config file but it complained - I didn't realise it should be `sid=no`
Now it's working nicely!  .
