### ISSUE TITLE
SAMPLE_CONVOLUTION_POLAR_R syntax error when scale/cscale=ewa_lanczos on Windows

### ISSUE THREAD

**Issue by ebvjr** [mpv-player/mpv#1536]
https://gist.github.com/ebvjr/6640b4369b42a2e86994

Settings:
```javascript
#Video
vo=opengl-hq:scale=ewa_lanczos:scale-antiring=0.7:cscale=ewa_lanczos:cscale-antiring=1.0:scale-down=mitchell:srgb:debug
vf=gradfun
display-fps=60
fs

#Audio
ao=wasapi

#Screenshot
screenshot-format=png
screenshot-png-filter=0
screenshot-png-compression=4
screenshot-template=D:\\Screenshot\\mpvsnap-%tY.%tm.%td-%tHh%tMm%tSs%

#osd
lua-opts=osc-layout=bottombar
```
![opengl_error](https://cloud.githubusercontent.com/assets/9087493/5953159/fde9cb36-a7bf-11e4-83d9-f7f7509671d8.png)

**Comment by wm4** [comment]
The shader compiler seems to be rejecting the shader for no good reason. Can you provide a log with ``-v``?

**Comment by ebvjr** [comment]
mpv -v
https://gist.github.com/ebvjr/c672a4c39ccb5de03f51

**Comment by wm4** [comment]
Sorry... when playing the file.

**Comment by ebvjr** [comment]
https://gist.github.com/ebvjr/3cf8fd795ab860fb02f7

**Comment by wm4** [comment]
Thanks. Intel drivers tend to be buggy (especially on Windows). It happened before that Intel drivers rejected or miscompiled perfectly valid GLSL. In this case, I can't see what exactly it has trouble with, though. Does it happen only with the ewa filters?

**Comment by ebvjr** [comment]
Yes. all scale filters works fine except ewa_lanczos. (probably worth mentioning the driver version i'm using: 9.17.10.3517 https://downloadcenter.intel.com/Detail_Desc.aspx?DwnldID=23764&lang=eng&ProdId=3319)

**Comment by wm4** [comment]
There's now a new windows build that fixes a problem with _another_ Intel driver for _different_ hardware, but maybe worth a try.

**Comment by ebvjr** [comment]
Using mpv-x86_64-20150129 build
https://gist.github.com/ebvjr/aeb2095b570f7e42705d

Same case.

**Comment by haasn** [comment]
Since the syntax error seems to be on the line containing essentially just:

```    SAMPLE_CONVOLUTION_POLAR_R(sample_scaler0, 3, lut_1d_l, WEIGHTS0, 0.700000)```

Maybe, just maybe, it's something stupid like the name being too long?

**Comment by ebvjr** [comment]
Probably not. tried all format i know (1.mp4,1.mkv,1.wmv,1.avi) and still getting the same syntax error.

**Comment by wm4** [comment]
Also, does this only happen in fs mode? (Since that's part of the issue title.)

**Comment by ebvjr** [comment]
It happen also on cscale. (renamed the title)

**Comment by haasn** [comment]
To confirm or deny my previous guess, does this patch help at all?

```
diff --git a/video/out/gl_video.c b/video/out/gl_video.c
index 2aae1ad..9d22d74 100644
--- a/video/out/gl_video.c
+++ b/video/out/gl_video.c
@@ -823,7 +823,7 @@ static void shader_setup_scaler(char **shader, struct scaler *scaler, int pass)
         if (scaler->kernel->polar) {
             int radius = (int)scaler->kernel->radius;
             // SAMPLE_CONVOLUTION_POLAR_R(NAME, R, LUT, WEIGHTS_FN, ANTIRING)
-            APPENDF(shader, "SAMPLE_CONVOLUTION_POLAR_R(%s, %d, %s, WEIGHTS%d, %f)\n",
+            APPENDF(shader, "SAMPLE_POLAR_R(%s, %d, %s, WEIGHTS%d, %f)\n",
                     name, radius, lut_tex, unit, scaler->antiring);
 
             // Pre-compute unrolled weights matrix
diff --git a/video/out/gl_video_shaders.glsl b/video/out/gl_video_shaders.glsl
index 3bc72dd..3a41da5 100644
--- a/video/out/gl_video_shaders.glsl
+++ b/video/out/gl_video_shaders.glsl
@@ -312,7 +312,7 @@ float[6] weights6(sampler2D lookup, float f) {
         lo = min(lo, c);                                                    \
         hi = max(hi, c);                                                    \
 
-#define SAMPLE_CONVOLUTION_POLAR_R(NAME, R, LUT, WEIGHTS_FN, ANTIRING)      \
+#define SAMPLE_POLAR_R(NAME, R, LUT, WEIGHTS_FN, ANTIRING)                  \
     vec4 NAME(VIDEO_SAMPLER tex, vec2 texsize, vec2 texcoord) {             \
         vec2 pt = vec2(1.0) / texsize;                                      \
         vec2 fcoord = fract(texcoord * texsize - vec2(0.5));                \
```

Although I just realized that the reason the syntax error points at the line containing the macro is probably because the syntax error happens inside the macro expansion..

**Comment by haasn** [comment]
No feedback. Furthermore, we no longer use those macros at all.

**Comment by ebvjr** [comment]
It's still not working though.

**Comment by haasn** [comment]
Your version of mpv is outdated. Please build from latest master.

**Comment by wm4** [comment]
He probably relies on lachs0r's builds, which haven't updated yet.
