### ISSUE TITLE
2015-01-29 Win32 build crashes when displaying any osd-msg

### ISSUE THREAD

**Issue by Divetoxx** [mpv-player/mpv#1538]
http://mpv.srsfckn.biz/mpv-i686-20150129.7z 
The latest 2015-01-29 Win32 build crashes after pressing O to display default osd-msg2.
It crashes immediately after start if osd-msg1=anything is described in config file.
So it crashes when need to display any osd-msg.

**Comment by lachs0r** [comment]
Fixed, same URL.
