### ISSUE TITLE
Not Building on Mac OS 10.15.7

### ISSUE THREAD

**Issue by martinmckenna** [mpv-player/mpv#15409]
### mpv Information

```bash
Mac OS version 10.15.7
Xcode version 12.4 (this is the latest I can get with my OS)
mpv version 0.35.0
```

### Reproduction Steps

1. Install mpv with `brew install mpv` or `brew install mpv --HEAD`
2. Watch build fail

### Expected Behavior

`meson compile -C build --verbose` will build

### Actual Behavior

`meson compile -C build --verbose` won't build 

### Log File

[log.txt](https://github.com/user-attachments/files/17963623/log.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by martinmckenna** [comment]
I know it's a really old version of mac OS, but the README says the project supports mac 10.15 and I'm on the latest Xcode I'm allowed to install

**Comment by Akemi** [comment]
those are the system requirements, eg it runs on 10.15 but might not build on it (due to Apples dev tool update policy). what you are encountering is a known SDK/Xcode bug that was fixed in the next version. nothing we can do about.
