### ISSUE TITLE
Zoom keybindings on keypad not bound anymore

### ISSUE THREAD

**Issue by kaymio** [mpv-player/mpv#15416]
### mpv Information

```bash
mpv v0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov  6 2024 17:31:17
libplacebo version: v7.349.0
FFmpeg version: n7.1
FFmpeg library versions:
   libavcodec      61.19.100
   libavdevice     61.3.100
   libavfilter     10.4.100
   libavformat     61.7.100
   libavutil       59.39.100
   libswresample   5.3.100
   libswscale      8.3.100
```

### Other Information

```text
- Linux version:NAME="Manjaro Linux" PRETTY_NAME="Manjaro Linux"
- Kernel Version:  Linux XXX 6.11.10-2-MANJARO #1 SMP PREEMPT_DYNAMIC Mon, 25 Nov 2024 05:29:44 +0000 x86_64 GNU/Linux
- GPU Model: 0b:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] [1002:67df] (rev c7)
- Mesa/GPU Driver Version: driverInfo      = Mesa 24.2.7-arch1.1
- Window Manager and Version: Sway 1.10
- Source of mpv: Manjaro repos, updated today
- Latest known working version: 1:0.38.0-8
- Issue started after the following happened: Updated yesterday from 38 to 39 via Manjaro upgrade
```

### Reproduction Steps

Upgrade from 38 to 39.
Try to use Alt+KP+ to increase zoom with 38, it works
Try to use Alt+KP+ to increase zoom with 39, [input] No key binding found for key 'Alt+KP_ADD'.

### Expected Behavior

Zoom in with the Alt+KP_ADD as it did in earlier versions. The manual says Alt++ should do this, but I don't have a + on my first layer on my keyboard layout and the Alt+KP_ADD should work out of the box. As it did in the past.

### Actual Behavior

[input] No key binding found for key 'Alt+KP_ADD'.
[input] No key binding found for key 'Alt+KP_SUBTRACT'.

Which is probably related to [this change](https://github.com/mpv-player/mpv/pull/14350) in which @kasper93 says:

"Any comments on this one? I think it does not conflicts with anything, so should be safe to add, no?"

### Log File

[zoomnotworking.txt](https://github.com/user-attachments/files/17968850/zoomnotworking.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
It's related to https://github.com/mpv-player/mpv/pull/14660. You can bind `Alt+KP_ADD` to `add video-zoom 0.1` as written in the log.

**Comment by guidocella** [comment]
Yeah, probably.

**Comment by kasper93** [comment]
It has been done for volume. `*` and `/`. While `+` and `-` were left unbound. @na-na-hi do you remember why exactly this were done like that?

**Comment by kaymio** [comment]
BTW, if `*` and  `/` are on the first most upper layer to set the volume, wouldn't it be easier to put zoom on KP_ADD and KP_SUBTRACT on the first layer of the layout, so without pressing Alt. Or preferably set both?
