### ISSUE TITLE
gbr/rgb color matrix is incorrectly detected as BT.601

### ISSUE THREAD

**Issue by 0n-s** [mpv-player/mpv#15418]
### mpv Information

```bash
mpv 0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Jan  1 1980 00:00:00
libplacebo version: v7.349.0
FFmpeg version: 7.0.2
FFmpeg library versions:
   libavcodec      61.3.100
   libavdevice     61.1.100
   libavfilter     10.1.100
   libavformat     61.1.100
   libavutil       59.8.100
   libswresample   5.1.100
   libswscale      8.1.100
```

### Important Information

```text
- Platform version: NixOS unstable
- GPU model, driver and version: Mesa 24.2.2, Intel(R) UHD Graphics 620 (KBL GT2)
- Source of mpv: nixpkgs nixos-unstable
- Latest known working version: ?
- Issue started after the following happened: ?
```

### Reproduction Steps

1. Look at a frame of a video with a RGB/GBR color matrix in mpv
2. Look at the same frame in e.g. VLC

### Expected Behavior

I was expecting mpv to detect the color matrix as GBR/RGB.

### Actual Behavior

It detects the color matrix as BT.601.

### Log File

[output.txt](https://github.com/user-attachments/files/17969459/output.txt)

### Sample Files

```
https://github.com/user-attachments/assets/542fb9da-2af5-418c-a7f4-464956a8df4a
```

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
> I was expecting mpv to detect the color matrix as GBR/RGB.

Why? Video is `yuv420p10`. It's not RGB.

**Comment by 0n-s** [comment]
Color matrix is not color format.

**Comment by kasper93** [comment]
> Color matrix is not color format.

What do you mean? Color matrix for bgr/rgb is identity. Your video is yuv. What do you expect to happen? mpv sees that video is mistagged with rgb matrix, ignores that and guesses bt.601 based on the resolution of the video. This way you get correctly looking video.

**Comment by 0n-s** [comment]
First of all, it's not correct. The background is grey when the matrix is assumed to be BT.601, 'cause it's not.

& again, we're talking about RGB as a color matrix here, not as a color format, so the video being YUV or not doesn't matter. Identity is probably a better term to use here (it's what mediainfo calls it) as it avoids confusion with the RGB color format.
FFmpeg defines the identity color matrix as such (from `libavutil/csp.c`):
```
static const struct AVLumaCoefficients luma_coefficients[AVCOL_SPC_NB] = {
    ...
    [AVCOL_SPC_RGB]        = { AVR(1),      AVR(1),      AVR(1)      },
    ...
```
& it can be used with any color format just fine.

**Comment by kasper93** [comment]
> First of all, it's not correct. The background is grey when the matrix is assumed to be BT.601 (it's supposed to be pure black).

That's because video has also mistagged color levels. You can fix that with `--vf=format=colorlevels=limited`.

> & again, we're talking about RGB as a color matrix here, not as a color format, so the video being YUV or not doesn't matter. Identity is probably a better term to use here (it's what mediainfo calls it) as it avoids confusion with the RGB color format.

I don't know what to tell you. This is how your (YUV) video looks like as (RGB) converted (incorrectly) with identity matrix.

![image](https://github.com/user-attachments/assets/350f559d-df5b-4753-9feb-4bb9f7f4ae33)

> & it can be used with any color format just fine.

No, it doesn't make sense with YUV formats. ffmpeg ties color system to format. Your video is YUV, there is nothing more about it.

**Comment by 0n-s** [comment]
> That's because video has also mistagged color levels.

That is correct, my bad.

> No, it doesn't make sense with YUV formats.

Fair enough. While it does _work_ properly in e.g. `ffplay` & VLC, I will agree it does make absolutely no sense in the context of YUV.
