### ISSUE TITLE
synchronization for libmpv

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1542]
libmpv provides each set of sync and async version for command/property.
async version set is very useful for not-blocking operations, but sometimes, its utilization is restricted by absence of synchronization functionality like glFinish() in OpenGL.

Suppose 'A' is an operation which can be executed asynchronously when they're executed independently and 'B' is another operation which depends on the execution state of 'A'.
Lack of synchronization enforces me to write two set of functions sync/async for 'A' or just let me give up async version.

I think something like mpv_synchronize() or mpv_flush() will make it easier to use async set of APIs.

**Comment by wm4** [comment]
Currently, asynchronous commands are executed synchronously within the core (just that the API function returns immediately, instead of blocking for the result), so they're not much different from synchronous commands. ``mpv_command_string(ctx, "ignore");`` has exactly the same behavior as a ``mpv_flush();`` would.

**Comment by xylosper** [comment]
Ah, then, may I think any sync version function call will flush all queued commands?

**Comment by wm4** [comment]
Yep, currently.

Currently, synchronous vs. asynchronous is a bit of a mess. The core always runs commands synchronous or asynchronously, depending what it is. For example, ``seek`` or ``loadfile`` are pretty much always synchronous. The result of these commands can be seen only later. Other commands, like ``screenshot``, always block the player. If an internal mechanism is introduced to handle these things in a more consistent way, it would probably change the default behavior of such commands. Or in other words, it would require an incompatible API change (even if the C API doesn't need to be changed, fundamentally changing the commands that can be issued with the API constitutes an API change).

We still can introduce something like ``mpv_flush()`` though, if you think it's helpful.

**Comment by xylosper** [comment]
> We still can introduce something like mpv_flush() though, if you think it's helpful.

If you think this behavior might be changed, i think mpv_flush() for alias of "ignore" command will be helpful in order to ensure synchronization at mpv_flush() regardless of internal behavior of mpv.
If you won't change this in close future, I think it would be enough to mention this feature in ducumentation.

Thank you!

**Comment by wm4** [comment]
Added something... I hope it's what you expected.

**Comment by xylosper** [comment]
Thank you!
