### ISSUE TITLE
Bug with IPC property-change events on initiation

### ISSUE THREAD

**Issue by ids1024** [mpv-player/mpv#1544]
While working on a feature for a program that uses mpv or mplayer as a backend (np1/mps-youtube#191), I noticed that `property-change` events were not being sent when mpv was first started and `observe_property` called using json IPC, while it was working for another developer.  With git bisect I tracked it down to 5f0a2b5908523ff3e792cab2f59901cb761332df which makes ytdl used by default.  Adding `ytdl=no` to the configuration made it send an event on start again.

I presume that ytdl slows down the loading of mpv, and the observe_property command is run before mpv has initialized.

**Comment by wm4** [comment]
What property exactly did you observe?

Property change events don't come necessarily in order; they're batched in a specific way, so the order of change events or when they happen could change.

**Comment by ids1024** [comment]
The `volume` property.  It appears that the `observe_property` command was run before mpv was initialized, so the value was not yet defined and it did not send a change event.

I think it would make sense in this case for a change event to be send when the value of the property is defined, but I admit that it is not a bug if a change event is not guaranteed in this case.  @hrnr has fixed the issue in mps-youtube by waiting for `time-pos` to change before observing the other property.

**Comment by wm4** [comment]
> @hrnr has fixed the issue in mps-youtube by waiting for time-pos to change before observing the other property.

That's not the right fix. but I have a suspicion why it doesn't work with ytdl enabled. In short, ytdl adds a potentially long phase of waiting for something, and we need to recheck property changes after the wait is done.

**Comment by wm4** [comment]
Let me know if it's better now.

**Comment by ids1024** [comment]
Thanks, that fixes it.
