### ISSUE TITLE
problems with fs-black-out-screens

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#1545]
The recent option to black out the secondary screen on OS X stopped working on my system a week or so ago. I can't determine exactly why, but in investigating, I noticed the following:

my ~/Logs/mpv.log shows:
Error parsing option fs-black-out-screens (option not found)
/Users/username/.config/mpv/config:28: setting option fs-black-out-screens='' failed.

I've tried with mpv 0.7.1, 0.7.2, and now with 0.7.3, they all give that error. Looking farther back in the log though, 0.7.1 and (I think) 0.7.2 previously did not give the error. It seems to have started showing up on January 25, just after a crash where I had to force-quit mpv. At the time I was running OS X 10.10.1, I updated to 10.10.2 on January 28.

Oddly though, the logged error is not necessarily directly related to whether the black-out function actually works or not. I tried booting my computer with an alternate startup disk, same OS X (10.10.2) and same mpv versions, and on that system the black-out-screens function is still working. However, it also gives the same above error in the log. Changing the setting in the config file doesn't seem to affect it. The black-out function is always active on my alternate startup disk, and never active on my normal startup disk, regardless of the setting in the config file. I can't determine why it works on one startup disk and not the other.

I can't say whether the setting ever affected whether the function was enabled or not, since I added the setting to my config file as soon as it was implemented (in 0.7.1), it seemed to work, and I never tried removing it.

**Comment by pigoz** [comment]
`--fs-black-out-screens` is only available in git master. It is not included in stable releases yet. It will be included in the mpv 0.8.x releases

**Comment by sumyungguy** [comment]
Oh, that's embarrassing. I see what happened now. Won't go into the details, it's all sorted now, thanks!
