### ISSUE TITLE
Changing mpv's icon

### ISSUE THREAD

**Issue by asoksevil** [mpv-player/mpv#1546]
I'm on Mavericks (10.9.5) and I've been trying to change mpv's icon with partial success.

Using LiteIcon I am able to change it but as soon as I play any video it reverbs back to its initial icon.

I went to the resources folder and changed "icon.icns"  as well but that didn't do the trick either.

**Comment by ChrisK2** [comment]
The Icon is additionally baked into the binary so that it can be shown when mpv is launched from the command-line (you'd just get the generic Unix-file icon in the Dock otherwise). If you want to completely change it you have to swap it out before compiling.

**Comment by asoksevil** [comment]
Hi Chris,

Thank you for your fast reply.

I am using your latest released version and I am not too savvy when it comes to compiling my own mpv... so could you please walk me through on that? What exact file do I have to change?

Thanks

**Comment by ChrisK2** [comment]
You have to change ``TOOLS/osxbundle/mpv.app/Contents/Resources/icon.icns``.

**Comment by asoksevil** [comment]
Chris,

I guess you can change that only if you are compiling a new version, but what if I am already using one (yours)? These are the docs and folders I can see:

![captura de pantalla 2015-02-01 a la s 21 51 28](https://cloud.githubusercontent.com/assets/739697/5994017/af09f65e-aa5c-11e4-8410-7bc45e888771.png)

**Comment by xylosper** [comment]
He already said it's not possible.
> If you want to completely change it you have to swap it out before compiling.

**Comment by asoksevil** [comment]
I thought there was a watt before com
