### ISSUE TITLE
"on_load" hook doesn't get called by the player

### ISSUE THREAD

**Issue by Fuwiz** [mpv-player/mpv#15465]
### mpv Information

```bash
mpv v0.39.0-386-g2d813de6 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Nov 24 2024 00:04:13
libplacebo version: v7.349.0 (v7.349.0-26-g5788a82-dirty)
FFmpeg version: N-117868-gecc7d5db9
FFmpeg library versions:
   libavcodec      61.25.102
   libavdevice     61.4.100
   libavfilter     10.6.101
   libavformat     61.9.100
   libavutil       59.47.101
   libswresample   5.4.100
   libswscale      8.9.101
```

### Other Information

```text
- Windows version: Microsoft Windows [Version 10.0.19044.5131]
- GPU model, driver and version: AMD rx560, 24.9.1
- Source of mpv: latest from https://sourceforge.net/projects/mpv-player-windows/files/64bit/
- Latest known working version: 0.39.0-240 (mpv-x86_64-20241027-git-fbf8695)
- Issue started after the following happened: after mpv update.
```

### Reproduction Steps

I did with --no-config etc, no errors.
Described better here: https://github.com/sibwaf/mpv-scripts/issues/18#issuecomment-2518389519

### Expected Behavior

I have "fuzzydir" script and it should find all subs in folder with video automatically and add them.
Script here: https://github.com/sibwaf/mpv-scripts

### Actual Behavior

After mpv update it not working anymore. Creator of script says problem in (my) mpv and not in his scipt, so im here. And he told all works fine on his linux.
https://github.com/sibwaf/mpv-scripts/issues/18#issuecomment-2518613464

### Log File

[output.txt](https://github.com/user-attachments/files/18053465/output.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
Works fine for me. Could you try latest build from here https://nightly.link/mpv-player/mpv/workflows/build/master ?

**Comment by Fuwiz** [comment]
> Works fine for me. Could you try latest build from here https://nightly.link/mpv-player/mpv/workflows/build/master ?

Tried from here 2 mingw32 builds and msvc. No effect. But works on version 0.39.0-240.

**Comment by kasper93** [comment]
Could you fine first not working build from https://github.com/zhongfly/mpv-winbuild/releases ? It will be faster this way probably to figure out what has changed.

**Comment by Fuwiz** [comment]
> Could you fine first not working build from https://github.com/zhongfly/mpv-winbuild/releases ? It will be faster this way probably to figure out what has changed.

There it limit - 6 pages, i cant go further. Last worked build for me was "mpv-x86_64-20241027-git-fbf8695.7z" from https://sourceforge.net/projects/mpv-player-windows/files/64bit/
![2024-12-09 (02-50-56 712) firefox - Releases_·_zhongflympv-winbuild_—_Mozilla_Firefox](https://github.com/user-attachments/assets/a58b8123-3747-46bb-b63a-1351a2cb5651)
![2024-12-09 (02-52-21 946) firefox - mpv_player_(Windows)_-_Browse_64bit_at_SourceForge](https://github.com/user-attachments/assets/89fbe101-d995-48c2-af64-7ae4b3e55619)

**Comment by kasper93** [comment]
> There is limit - 6 pages

Sorry, I didn't realize they only store 1 month worth of builds.

> Last worked build for me was "mpv-x86_64-20241027-git-fbf8695.7z" 

So it should be somewhere in range [fbf8695..42ff6f9](https://github.com/mpv-player/mpv/compare/fbf8695...42ff6f9). I checked those commits and don't really see anything, that would explain why it stops working for you. There were some changes to scripting, but they shouldn't matter.

Could you try, to narrow it down further? I know it is trouble, but we will get better idea what's going on. Got to this link [fbf8695..42ff6f9](https://github.com/mpv-player/mpv/compare/fbf8695...42ff6f9), click on green  ✔, click on `Summary` (top left), and will will find Artifacts on the bottom.

**Comment by Fuwiz** [comment]
> > There is limit - 6 pages
> 
> Sorry, I didn't realize they only store 1 month worth of builds.
> 
> > Last worked build for me was "mpv-x86_64-20241027-git-fbf8695.7z"
> 
> So it should be somewhere in range [fbf8695..42ff6f9](https://github.com/mpv-player/mpv/compare/fbf8695...42ff6f9). I checked those commits and don't really see anything, that would explain why it stops working for you. There were some changes to scripting, but they shouldn't matter.
> 
> Could you try, to narrow it down further? I know it is trouble, but we will get better idea what's going on. Got to this link [fbf8695..42ff6f9](https://github.com/mpv-player/mpv/compare/fbf8695...42ff6f9), click on green ✔, click on `Summary` (top left), and will will find Artifacts on the bottom.

Last worked: e734f5a (e734f5ae3387fba5e2e8b8f15580108150faa3f7)
![2024-12-09 (04-08-49 575) firefox - Comparing_fbf8695 42ff6f9_·_mpv-playermpv_—_Mozi](https://github.com/user-attachments/assets/0b57e2f3-04ea-4193-bd78-15df8bee2347)

**Comment by llyyr** [comment]
Provide a log file of you actually using the script, not just launching mpv with no files or scripts.

**Comment by Fuwiz** [comment]
> Provide a log file of you actually using the script, not just launching mpv with no files or scripts.
> 
> The script isn't even in your config directory or loaded via --script, so of course it's not going to work. Nobody can help you if you don't provide this information

Script in config folder and he loaded. He just not work properly. I named logs, first 2 is just mpv logs when video playing, first - latest version, second - e734f5a. Last 2 logs created with mpv --msg-level=fuzzydir=trace path-to-video-here. First - on latest version of mpv, second - on e734f5a. On latest version subs in folder not loading, on e734f5a loading.
[mpv (latest).log](https://github.com/user-attachments/files/18054176/mpv.latest.log)
[mpv (e734f5a).log](https://github.com/user-attachments/files/18054177/mpv.e734f5a.log)
[fuzzydir (latest mpv version).txt](https://github.com/user-attachments/files/18054178/fuzzydir.latest.mpv.version.txt)
[fuzzydir (e734f5a mpv version).txt](https://github.com/user-attachments/files/18054179/fuzzydir.e734f5a.mpv.version.txt)

**Comment by llyyr** [comment]
`--load-auto-profiles=no` or `--load-auto-profiles=yes` should fix your issue for now until a better fix is pushed

**Comment by Fuwiz** [comment]
> `--load-auto-profiles=no` or `--load-auto-profiles=yes` should fix your issue for now until a better fix is pushed

Yes, this command fix problem, idk what it does, but at least all works now

**Comment by kasper93** [comment]
Could you try build from https://github.com/mpv-player/mpv/pull/15467 ? Should help in such cases.

**Comment by Fuwiz** [comment]
> Could you try build from #15467 ? Should help in such cases.

Works
