### ISSUE TITLE
Player stops when audio files with differing sample rates are played

### ISSUE THREAD

**Issue by pdball** [mpv-player/mpv#15477]
### mpv Information

```bash
mpv 0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: 6.1.1-3ubuntu5
FFmpeg library versions:
   libavcodec      60.31.102
   libavdevice     60.3.100
   libavfilter     9.12.100
   libavformat     60.16.100
   libavutil       58.29.100
   libswresample   4.12.100
   libswscale      7.5.100
```

### Other Information

```text
- Linux version:"Ubuntu 24.04.1 LTS"
- Kernel Version:Linux test-lnx 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- GPU Model:
- Mesa/GPU Driver Version:
- Window Manager and Version:
- Source of mpv:
- Latest known working version:0.32.0
- Issue started after the following happened:
```

### Reproduction Steps

./mpv --log-file=output.txt --no-config --audio-device='alsa/iec958:CARD=USB,DEV=0' s44100.flac s48000.flac 

### Expected Behavior

Playback continues when a file, with a differing sampling rate from the previous, loads.

### Actual Behavior

Audio playback stopped after the first file ended

### Log File

[output.txt](https://github.com/user-attachments/files/18068652/output.txt)

### Sample Files

`sox -n -r 44100 -c2 s44100.flac synth sin %-12 sin %-9 sin %-5 sin %-2 fade h 0.1 4 0.1`
`sox -n -r 48000 -c2 s48000.flac synth sin %-12 sin %-9 sin %-5 sin %-2 fade h 0.1 4 0.1`

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by pdball** [comment]
Note that playback continues after seeking backwards when the second file loads.

**Comment by llyyr** [comment]
Is this specific to ao=alsa? Can you try any other ao?

**Comment by pdball** [comment]
I don't use --ao.  The --audio-device='alsa/iec958:CARD=USB' is how I select the USB connected DAC.  

The .lua code I showed indicated that the input sample rate != the the setting for the output device.  

The output log hints that the output reconfiguration to accommodate the new sample rate is skipped until I force a seek back.  This worked in Debian Bullseye mpv version 0.32.0.  The next Debian release provides mpv version 0.35.1 and that is broken. So is current git code.

**Comment by Dudemanguy** [comment]
Okay I can actually reproduce if I explicitly set the audio device.

**Comment by pdball** [comment]
I can confirm that the proposed change resolves the problem in my use case.
Thank you for the speedy fix.
