### ISSUE TITLE
Black screen on restore (Windows)

### ISSUE THREAD

**Issue by flriancu** [mpv-player/mpv#1547]
This problem happens (at least) on Windows 7, with Intel HD Graphics 4000 and [Nvidia GeForce 3xx.xx](http://i.imgur.com/vXKf73c.png) driver (it persists across all updates/versions). I start a video with mpv, [it runs fine](http://i.imgur.com/i3JTUlW.png), I minimize then restore it; now the display area of the window [is black](http://i.imgur.com/SFRxkd5.png) (the audio still runs). I've tested on .avi, .mp4, 8-bit and 10-bit encoded H264, .mp3's with cover art etc, there are no exceptions.
Edit: the version of mpv is almost always the latest available for Windows, it persists across all versions.

**Comment by wm4** [comment]
With what vo?

**Comment by floriniancu** [comment]
I'm assuming it's that thing set by --vo=.....
The default is opengl; I've tested with --vo=direct3d and it works fine, minimize and all; no errors/warnings shown in the console.
On a side note, with --vo=opengl-hq it crashes as soon as I minimize (here's an [image](http://i.imgur.com/mUArsn4.png)).

**Comment by wm4** [comment]
Can you make the same screenshot, but with -v added?

**Comment by floriniancu** [comment]
There was a huge wall of text so I saved it to a text file. Here's [vo=opengl](http://pastebin.com/VCeQib65) with -v and [vo=opengl-hq](http://pastebin.com/p5AVuKYe) with -v.
I hope I got it right. For opengl, I minimized and restored the window before quitting, and for opengl-hq I minimized the window (and closed mpv when it crashed).

**Comment by wm4** [comment]
Well, I was wondering where exactly it's crashing.

**Comment by floriniancu** [comment]
Yeah, it happens on all videos when I minimize... Let me know if I you need any more info. About the black screen with opengl, it's just my two cents, but I think it has some sort of conflict with the Intel graphics.

**Comment by wm4** [comment]
For now I've suppressed the resize to 1x1 when minimizing (not sure if it fully works), which may or may not improve this. I don't know the actual cause, though.

**Comment by wm4** [comment]
Guess we can consider this fixed.

**Comment by indivisible** [comment]
The issue still persists, as of 8fff12542279960ff6e0a14f186d5c4c4d2bdfe4. Using `--vo opengl` on win7 (64 bit, Intel driver) still produces a black window after minimizing and restoring the player window. Interestingly `--vo opengl-hq` works fine.

**Comment by flriancu** [comment]
Still having the same problem on the same machine. This does not happen if the video is paused
@indivisible is your driver, by some chance, Intel HD Graphics 4000?

**Comment by indivisible** [comment]
Yes, it is.

**Comment by flriancu** [comment]
Here's an update, when running the latest build (with the default vo=opengl):
- I open the file and the video starts playing
- I minimize and restore mpv, the video is now black
- I resize the window ever so slightly and the video reappears
- I can now minimize, restore and resize mpv freely, with the video playing normally.
Here's an [output log](http://pastebin.com/mjVMws4Q); I don't know if it helps, but here's what I did: minimize, restore, resize, in this order, twice.

**Comment by flriancu** [comment]
The latest Windows build, 2015-09-23, fixed this bug (with the default opengl). The opengl-hq still crashes.

**Comment by kabigears** [comment]
This still happening with the latest build with the default opengl.

**Comment by flriancu** [comment]
@kabigears on what OS? It does not happen on my Windows 7.

**Comment by lachs0r** [comment]
ANGLE should fix this if it’s still a problem with native OpenGL.
