### ISSUE TITLE
`console.lua` Issue with vertical alignment after recent changes.

### ISSUE THREAD

**Issue by Sneakpeakcss** [mpv-player/mpv#15478]
### mpv Information

```bash
mpv v0.39.0-474-g63e6dfba Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Dec  9 2024 19:05:00
libplacebo version: v7.350.0 (v7.349.0-30-g056b852-dirty)
FFmpeg version: N-118034-gd21134313
FFmpeg library versions:
   libavcodec      61.26.100
   libavdevice     61.4.100
   libavfilter     10.6.101
   libavformat     61.9.100
   libavutil       59.49.100
   libswresample   5.4.100
   libswscale      8.12.100
```

### Other Information

```text
- Windows version: 22H2
- GPU model, driver and version: N\A
- Source of mpv: zhongfly
- Latest known working version: N\A
- Issue started after the following happened: #b71ab51
```

### Reproduction Steps

```
set osd-align-y bottom;set osd-margin-y 100;show-text '----------------------------------- position test -----------------------------------'
```

### Expected Behavior

Previously, it was possible to align OSD messages to the bottom(`osd-align-y`) and fine-tune the position with `osd-margin-y` without moving the console. While this also moves `stats.lua`, it still had enough room to float at the top and remain readable, while keeping console position intact:

https://github.com/user-attachments/assets/bb31adec-bf7a-4936-a4c9-c0b1ad8c235f

The best outcome would be to allow the messages to be aligned independently of `stats.lua`/`console.lua`, but even previous behaviour was good enough.

### Actual Behavior

Changes in https://github.com/mpv-player/mpv/commit/b71ab51996608da4a7ce862f95a4f79a8ff1b755 broke this, and don't allow adjusting the positioning of OSD messages without moving the console:

https://github.com/user-attachments/assets/96c202f3-5605-4579-b193-05dc8f6cba10

### Log File

[log.txt](https://github.com/user-attachments/files/18069576/log.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
This is not breakage, console was intentionally made to respect OSD margins for consistency, like OSD messages and stats already did. This allows equal mirrored margins as seen in https://github.com/mpv-player/mpv/pull/15342.
