### ISSUE TITLE
vf=fingerprint problem

### ISSUE THREAD

**Issue by angousana** [mpv-player/mpv#15489]
### mpv Information

```bash
mpv 0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
libplacebo version: v6.338.2
FFmpeg version: 6.1.1-3ubuntu5
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

### Other Information

```text
- Linux version: Ubuntu 24.04.1 LTS
- Kernel Version: 6.8.0-49-generic
- Source of mpv: apt
```

### Reproduction Steps

mpv --vf=fingerprint:print video.mkv

### Expected Behavior

for it to print the fingerprint to be used with skip-logo.lua 

### Actual Behavior

[fingerprint] Falling back to libswscale.
[fingerprint] unsupported video format
Disabling filter fingerprint.00 because it has failed.

### Log File

.

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by CounterPillow** [comment]
You did not attach a full log file, despite claiming in the checkboxes you did.

The problem here likely is that Ubuntu enables hwdec by default, and most video filters don't work with that. Use --hwdec=no or --hwdec=auto-copy.

Either way, can't reproduce on an up to date version (you're using an out of date version that Ubuntu ships)
