### ISSUE TITLE
OSX bundle: crash when using vapoursynth

### ISSUE THREAD

**Issue by Argon-** [mpv-player/mpv#1549]
I recently upgraded vapoursynth to R26 (using homebrew) and didn't notice it at first, because it works just fine when mpv is launched from the command line, but when I'm using the bundle every VS script (called with some `vf toggle vapoursynth` key binding) results in mpv crashing:

    Thread 6 Crashed:: mpv/playback core (OSX)
    0   org.python.python             	0x0000000114c94a45 PyImport_AddModuleObject + 24
    1   org.python.python             	0x0000000114c94b54 PyImport_AddModule + 31
    2   vapoursynth.so                	0x0000000114b7eda8 PyInit_vapoursynth + 318
    ...

Full report: https://gist.github.com/Argon-/102c67f80835f697156f

I assume the problem is the bundle generation, maybe due to the Cython change from VS R25 to R26?

**Comment by pigoz** [comment]
I actually encountered the same problem a few hours ago. I think the Cython change might be the cause, but I have not much of an idea how python + cython should be packaged (especially when a relocateable bundle which you can also move to other machines comes into play)...

**Comment by pigoz** [comment]
Anyway I can add some special case to the bundle generation and not run install name tool for links to "Python"

**Comment by Argon-** [comment]
This would help at least in my case, where I'm using the bundle for "double click to open" stuff.
Aside from that, there are OSX applications shipping with full-fledged Python frameworks and stuff, but I'm not sure if this is something desirable.

**Comment by pigoz** [comment]
I fixed the immediate problem. I'm not sure I would want to package a complete python installation with mpv. I think the time would be better spent improving our Lua-Vapoursynth bridge.
