### ISSUE TITLE
0.39 doesn't do tone mapping with vo=gpu and hwdec=*-copy

### ISSUE THREAD

**Issue by chainikdn** [mpv-player/mpv#15498]
### mpv Information

```bash
mpv 0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 28 2024 01:30:48
libplacebo version: v7.349.0 (v7.349.0-13-ga018ab0-dirty)
FFmpeg version: N-117212-g01c47dd23
FFmpeg library versions:
   libavcodec      61.20.100
   libavdevice     61.4.100
   libavfilter     10.5.100
   libavformat     61.8.100
   libavutil       59.40.100
   libswresample   5.4.100
   libswscale      8.4.100
```

### Other Information

```text
- Source of mpv: shinchiro's build
- Latest known working version: 0.38
```

### Reproduction Steps

mpv --no-config --vo=gpu --hwdec=auto-copy <some-hdr-video>

### Expected Behavior

Nice tone mapped image.

### Actual Behavior

0.38: nice tone mapped image in any vo / hwdec combination.
0.39:
--vo=gpu --hwdec=auto ---> ok
--vo=gpu --hwdec=auto-copy ---> no tone mapping, washed out colors
--vo=gpu-next --hwdec=auto-copy ---> ok

Am I missing some intended 0.39 behavior change?

Attached logs with "--vo=gpu --hwdec=auto-copy" for 0.38 and 0.39.

### Log File

[mpv-038.log](https://github.com/user-attachments/files/18117373/mpv-038.log)
[mpv-039.log](https://github.com/user-attachments/files/18117374/mpv-039.log)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by kasper93** [comment]
Try latest master version, I cannot reproduce anymore.

**Comment by chainikdn** [comment]
That one: https://github.com/mpv-player/mpv/commit/9b571a7aa711b9587e6acf68572e2003e2ddd51e
