### ISSUE TITLE
[Idea] Make mpv embeddable into a website and then allow it to play .avi files in the browser tab

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#15503]
### Expected behavior of the wanted feature

[Idea] Make mpv embeddable into a website and then allow it to play .avi files in the browser tab

I have many .mp4 files which work fine on the browser and mpv.

I have some legacy .avi files, which work fine on mpv but not on the browser. I guess one solution is to re-encoded them into .mp4 and I will probably do so in the long run. But, I was also thinking ... "wait a moment ... mpv can already handle .avi files, so why can I not play these in the browser tab too, like .mp4 files?"

I understand that this is probably a bit outside the scope of mpv, and there may be issues due to browser restrictions and what not. But I also think that it SHOULD work - I don't understand why .mp4 files can be played in the browser but .avi files can not, when .mpv can play both fine.

At any rate, this is not a good feature request that should stay open, since it is mostly an idea, but nonetheless I wanted to suggest it. I'll close the issue, as you guys have already almost 900 open issues, so it may be better to focus on the open issues. Nonetheless, perhaps someone in the future has a similar use case or idea, and who knows, perhaps in a few years this will be possible. (I guess I'll have to re-encoded the .avi files anyway, so I guess for my own use cases that may be solved eventually. Only 100 video files left to go! These originate from e. g. back to 2003 or so, give or take, or even older than that. Many of those originated from my ancient DVD collection and I am no longer using DVDs.)

**Comment by CounterPillow** [comment]
[no](https://github.com/mpv-player/mpv/issues/13575#issuecomment-1966512960)
