### ISSUE TITLE
New hooking point for playback termination

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1552]
For now, there's only one hooking point `on_load` which makes it possible to manipulate stream options.

I'm not sure this is a public command or it's only for ytdl lua script, but if it's a public one, I want to suggest another hooking point between end of playback loop and uninitialization of resources, for instance,

```c
terminate_playback:

    if (mpctx->stop_play == PT_RELOAD_DEMUXER) {
        mpctx->stop_play = KEEP_PLAYING;
        mpctx->playback_initialized = false;
        uninit_audio_chain(mpctx);
        uninit_video_chain(mpctx);
        uninit_sub_all(mpctx);
        uninit_demuxer(mpctx);
        goto goto_reopen_demuxer;
    }
>>> HERE <<<
    mp_nav_destroy(mpctx);

    if (mpctx->stop_play == KEEP_PLAYING)
        mpctx->stop_play = AT_END_OF_FILE;

    if (mpctx->stop_play != AT_END_OF_FILE)
        clear_audio_output_buffers(mpctx);

    if (mpctx->step_frames)
        opts->pause = 1;
```

For now, there's no way to figure out the core state at the end of playback, because the MPV_EVENT_FILE_END is posted after uninitialization of resources, and, even if a new event is introduced in that point, event works asynchronously and when client gets the event, maybe it's already too late to get what client want to know.

So, I think hooking which blocks the core thread is the only way to accomplish figuring out the state of end of playback such as selected track id.

**Comment by wm4** [comment]
>I'm not sure this is a public command or it's only for ytdl lua script,

A bit of both. Fragile/specific enough that it's not necessarily a guaranteed part of the API (even less so than obscure commands and properties).

> I want to suggest another hooking point between end of playback loop and uninitialization of resources, 

I'm not opposed, but note that there's no way to know the end reason at this point.

For what exactly do you need this? The track IDs for one are remembered in the track selection options.

**Comment by xylosper** [comment]
> The track IDs for one are remembered in the track selection options.

No they're not if track ID is given by `file-local-options/sid`. In that case, both of `sid` and `options/sid` return just `0` when recieving MPV_EVENT_FILE_END event.

Also, lots of properties are already invalidated in MPV_EVENT_FILE_END, e.g., `track-list`, `chapter-list`, `metadata` and so on which do not have corresponding options.

**Comment by xylosper** [comment]
Oh I missed this:
> note that there's no way to know the end reason at this point.

Totally okay. The purpose of this hooking is to know the state not why ended, although it may be better to know end reason here, too.

**Comment by wm4** [comment]
And why can't you use the ``keep-open`` option?

**Comment by wm4** [comment]
Implemented it.

**Comment by xylosper** [comment]
Thank you!!
