### ISSUE TITLE
Can't select audio or subtitles using Matroska (mkv) ordered chapters with different files

### ISSUE THREAD

**Issue by ValdikSS** [mpv-player/mpv#1553]
Hello!
I have an opening of the series with 11 audio languages and the main episode with 7 audio languages. If I use Matroska ordered chapters feature to include opening in every episode, I can't choose audio or subtitles from the opening while it's playing, but only that ones that are in the main episode file.
Works fine in VLC.

**Comment by wm4** [comment]
This is not allowed. VLC is playing a broken file; we don't need to do the same.

**Comment by ValdikSS** [comment]
Why is it broken? I just made it myself. You can have different set of audio and subtitles in every mkv file, I don't see any problem with that.

**Comment by wm4** [comment]
All tracks must be exactly the same across all linked segments, so obviously you can't add or remove tracks either.

**Comment by wm4** [comment]
Can you upload a sample that is broken in this way?

**Comment by ValdikSS** [comment]
Sure
ftp://serv.valdikss.org.ru/Serials/_Animated%20Series/W.I.T.C.H./prerel/rel/ download files op_1.mkv and chaptest-start-from-op.mkv.
It seems you're right. It works neither in potplayer nor in mpc-hc. Moreover, if the playback begins with the linked file (the first chapter with timecode 00:00:00.000 is ordered chapter), mpv uses audio and subtitle tracks from main track, while potplayer and mpc-hc use tracks from the another file, and you can't use audio tracks or subtitles which are inside the file! This could be fixed adding fake first chapter, which I did in chaptest-fixed.mkv

**Comment by wm4** [comment]
I added some warning output when the segments mismatch.

Also, I noticed that other mechanisms using the timeline code (shared with matroska) have a similar problem, e.g. what if an edl file contains multiple files with different track layouts? I might actually make it possible to select the "additional" tracks in this case. But in any case, such matroska ordered chapter files are still broken.
