### ISSUE TITLE
Matroska (mkv) linking feature doesn't work

### ISSUE THREAD

**Issue by ValdikSS** [mpv-player/mpv#1554]
Matroska (mkv) linking feature (not ordered chapters!) doesn't work. If I try to play file with linked previous or next segment, it plays just as usual file without linked segments.
Works fine in VLC.

**Comment by wm4** [comment]
What feature is this? Does it work in mpc-hc? Do you have a sample file?

**Comment by ValdikSS** [comment]
mkvmerge's --link-to-previous and --link-to-next parameters.  
Will do samples in some minutes.

**Comment by ValdikSS** [comment]
ftp://serv.valdikss.org.ru/Serials/_Animated Series/W.I.T.C.H./prerel/rel/
Download both files in a single folder and play linktest.mkv.

**Comment by wm4** [comment]
Uh, so the ``Previous segment UID`` means the player should find and load a file with that segment id, and play it before the current file?

What the fuck, just use ordered chapters if you want this.

**Comment by ValdikSS** [comment]
Works in MPC-HC and Daum PotPlayer. This is standard matroska functionality and it's designed to work with splitted (i.e. by filesize, not logically) files. This should be implemented.

**Comment by wm4** [comment]
And why don't you just use ordered chapters?

How does this crap even interact with ordered chapters?

This is all just severely retarded and dumb.

**Comment by ValdikSS** [comment]
This is not chapters. Imagine you have VOBs. You can join each VOB in each MKV file and link them like .IFO file does and it would play just as a one huge file.  
Well, I think this is not very useful thing in the every day life, too, and I use it very seldom, but this works in most players and not in mpv.

**Comment by wm4** [comment]
>This is not chapters. Imagine you have VOBs. You can join each VOB in each MKV file and link them like .IFO file does and it would play just as a one huge file.

You can still do this with ordered chapters, though I don't remember if Matroska forces you to set chapter points on the transition boundaries. If someone wants to implement this (@mathstuf?) fine, but I won't.

>Well, I think this is not very useful thing in the every day life, too, and I use it very seldom,

Aka obscure crap nobody needs.

**Comment by ValdikSS** [comment]
>You can still do this with ordered chapters, though I don't remember if Matroska forces you to set chapter points on the transition boundaries~

It is. And making chapters on every episode is pretty hard while linking files is easy.

**Comment by mathstuf** [comment]
I have scripts which generate ordered chapters for me, so linking files together this way isn't in my typical use case. I'll keep it in mind if I ever get bored though (though nested chapters, #300, is higher on my wishlist).

Looking at the spec, I see it is a property on a segment, so I also have no idea how this is meant to interact with ordered chapters (and the MKV docs are, as always, completely lacking in guidance). My guess is that when playing an ordered chapter file, ignore any `PrevUID`/`NextUID` parameters on referenced segments. Might be possible to hack it by acting as if it has ordered chapters on either side of it (but would get nasty real quick in the transitive case or if a loop is formed).

Another idea is to treat a chain of `PrevUID`/`NextUID` files as a playlist with the selected file as the current file (probably cleaner). Also probably worthy of an option to do this. Something like `--playlist=episode.mkv` might work.

Please add test data to https://github.com/mpv-player/random-stuff for this with README files explaining what is supposed to happen. Bonus points for ordered chapters thrown into the mix.

**Comment by wm4** [comment]
Currently, ``--playlist`` just opens a demuxer (forcing demux_playlist.c). Which means trying to avoid conflicts with normal mkv opening could become awkward.

Anyway, one thing I wonder about is _what_ is this feature really about? Is it like a playlist? Or like a hint what file to play next when going back or forward in the playlist? Or really linking all files and pretending it's a single file? Just what is it supposed to be?

**Comment by ValdikSS** [comment]
I'm not quite sure, but I suppose it was made for splitting one big file by filesize or length. mmg can automatically link splitted files while splitting it. I have no idea how it's really should be used.

**Comment by wm4** [comment]
Well, what does mpc-hc with Haali or lavfilters do? The original Haali code is the specification for Matroska, after all.

**Comment by ValdikSS** [comment]
mpc-hc with lavfilters handles such files as one big file, just as if it is not splitted.

**Comment by wm4** [comment]
What happens if you give it a file that has ordered chapters enabled _and_ uses --link-to-previous/--link-to-next? what happens if you give it files that are linked, but have different track layout?

**Comment by mathstuf** [comment]
All of that plus what happens if such a file is found in the middle of a playlist (e.g., `mpv foo.avi linked.mkv`)? Do you play `foo.avi` then `before-linked.mkv`?

**Comment by 00000000000001** [comment]
On the principles that the manual/deliberate should trump the automatic and that the obvious should override the hidden, ordered chapters should negate segment linking.  mkvmerge has a checkbox to automatically link segments and the complete sequence of links is going to be buried in the individual mkvs, while ordered chapters have to be manually created and they have the appearance of a full ledger of the playback, so the ordered chapters are simply more obvious and would be a manual, later addition.
If I were to link mkvs and then write ordered chapters expecting the links to work, and those links didn't work, it would be immediately obvious to me that the reason they're not working is that the ordered chapters overwrote them and that I need to write things into the chapters if I want them to work.  If, on the other hand, I accidentally linked mkvs by checking the wrong box in mkvmerge, wrote ordered chapters for one of the mkvs, and was suddenly having the player pull up a series of segments that are nowhere in the chapters I just wrote, I'd be pretty clueless as to why, and I wouldn't have anything obvious to clue me in on the reason for the unexpected result, either.

In the real world, segment linking is used in lieu of ordered chapters, so it's pretty much academic.  When an opening and ending occur at the very beginning and end of a show you can mux the episodes with links, and that's just faster than writing 25 sets of chapters with the episode lengths entered to the tenth of a second.  You never use ordered chapters along with links.
Having chapters trump links makes sense, though.

**Comment by ValdikSS** [comment]
@mathstuf, @wm4, are you still interested in my tests in 2018? Just discovered this issue that I forgot to reply.

**Comment by mathstuf** [comment]
Extra information can't hurt. This part of the Matroska spec is pretty dusty.

**Comment by ValdikSS** [comment]
04:21 music video split into 5 linked 1 minute length mkv files with mkvmergegui "link files" checkbox in splitting output section.

MPC-HC 1.7.13 with LAV Filters 0.70.2.1 handles every file as a full clip. Every split part of the file resulting in 00:04:21 video if added to the playlist.
Everything the same with external Haali media splitter and same MPC-HC (32 bit) version.

VLC has a bug. Playing any split video file after the first one causes repeats and sometimes crashes. Loading second split segment shows 05:21 in the playlist, third — 06:21, and so on.
