### ISSUE TITLE
ytdl_hook-ytdl_path does not expand-path ~~/

### ISSUE THREAD

**Issue by ahaoboy** [mpv-player/mpv#15558]
### mpv Information

```bash
mpv v0.39.0-521-g96bebf09 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Dec 21 2024 00:07:25
libplacebo version: v7.350.0 (v7.349.0-30-g056b852-dirty)
FFmpeg version: N-118098-gc90e0777d
FFmpeg library versions:
   libavcodec      61.27.101
   libavdevice     61.4.100
   libavfilter     10.6.101
   libavformat     61.9.101
   libavutil       59.51.100
   libswresample   5.4.100
   libswscale      8.12.100
```

### Other Information

```text
- Windows version: win11
- GPU model, driver and version:
- Source of mpv:
- Latest known working version:
- Issue started after the following happened:
```

### Reproduction Steps

I want to set ytdl_hook-ytdl_path to a path relative to the mpv installation directory or config directory, but it doesn't seem to work

There is the following directory structure, yt-dlp.exe is placed in the portable_config directory

```
.
├── mpv.com
├── mpv.exe
├── portable_config
│   ├── cookies.txt
│   ├── input.conf
│   ├── mpv.conf
│   └── yt-dlp.exe
└── updater.bat
```

When setting both screenshot-template and ytdl_hook-ytdl_path, only ~~/ in screenshot-template is processed correctly

```
screenshot-template="~~/MPV-%P-N%n"
script-opts=ytdl_hook-ytdl_path="~~/yt-dlp.exe"
```

log
```
[   4.416][d][cplayer] Run command: subprocess, flags=64, args=[args="~~/yt-dlp.exe,--no-warnings,-J,--flat-playlist,--sub-format,ass/srt/best,--format,bestvideo+bestaudio/best,--cookies,~~/cookies.txt,--mark-watched,--sub-langs,all,--write-srt,--no-playlist,--,https://www.youtube.com/watch?v=L949-42Pcjw", playback_only="yes", capture_size="67108864", capture_stdout="yes", capture_stderr="yes", detach="no", env="", stdin_data="", passthrough_stdin="no"]
[   4.416][v][ytdl_hook] Starting subprocess: [~~/yt-dlp.exe, --no-warnings, -J, --flat-playlist, --sub-format, ass/srt/best, --format, bestvideo+bestaudio/best, --cookies, ~~/cookies.txt, --mark-watched, --sub-langs, all, --write-srt, --no-playlist, --, https://www.youtube.com/watch?v=L949-42Pcjw]
[   4.417][e][ytdl_hook] Subprocess failed: init
[   4.417][v][ytdl_hook] youtube-dl with path ~~/yt-dlp.exe not found in PATH or not enough permissions
[   4.417][v][cplayer] Set property: user-data/mpv/ytdl/path="" -> 1
[   4.417][v][cplayer] Set property: user-data/mpv/ytdl/json-subprocess-result={"status":-3,"error_string":"init","killed_by_us":false,"stdout":"","stderr":""} -> 1
[   4.417][v][ytdl_hook] status: -3
[   4.417][v][ytdl_hook] reason: init
[   4.417][v][ytdl_hook] stdout: 
[   4.417][v][ytdl_hook] stderr: 
[   4.417][e][ytdl_hook] 
[   4.417][e][ytdl_hook] youtube-dl failed: not found or not enough permissions
```

The source code seems to use the passed string directly without using expand-path

```
    local command = {
        ytdl.path, "--no-warnings", "-J", "--flat-playlist",
        "--sub-format", "ass/srt/best"
    }

```

The cookie path may also contain ~~/

```
ytdl-raw-options=cookies=~~/cookies.txt,mark-watched=
```

### Expected Behavior

`~~/` in ytdl_hook-ytdl_path is  handled by `expand-path`

### Actual Behavior

`ytdl_hook-ytdl_path` is treated as a normal string

### Log File

[log.txt](https://github.com/user-attachments/files/18220931/log.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of files, parameters, and conditions used in "Reproduction Steps", with the addition of `--log-file=output.txt`.
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.
- [X] I attached the backtrace in the case of a crash.

**Comment by guidocella** [comment]
`ytdl_hook.lua` already calls `mp.find_config_file` on `ytdl_path` so you can just use `script-opt=ytdl_hook-ytdl_path=yt-dlp` (which is already searched by default).

**Comment by ahaoboy** [comment]
> `ytdl_hook.lua` already calls `mp.find_config_file` on `ytdl_path` so you can just use `script-opt=ytdl_hook-ytdl_path=yt-dlp` (which is already searched by default).

Thanks, I tested it and it works even without adding configuration as long as yt-dlp is placed in the portable_config directory
But the logic of cookies is a little different, I want to put cookies and yt-dlp in the portable_config directory

This will be in the mpv.exe directory instead of the portable_config directory.
```
ytdl-raw-options=cookies="cookies.txt",mark-watched=
```

Using ~~/ will give an error

```
ytdl-raw-options=cookies="~~/cookies.txt",mark-watched=
```


```
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "yt_dlp\__main__.py", line 17, in <module>
[ytdl_hook]   File "yt_dlp\__init__.py", line 1093, in main
[ytdl_hook]   File "yt_dlp\__init__.py", line 991, in _real_main
[ytdl_hook]   File "yt_dlp\YoutubeDL.py", line 990, in __exit__
[ytdl_hook]   File "yt_dlp\YoutubeDL.py", line 993, in close
[ytdl_hook]   File "yt_dlp\YoutubeDL.py", line 986, in save_cookies
[ytdl_hook]   File "yt_dlp\cookies.py", line 1317, in save
[ytdl_hook]   File "contextlib.py", line 135, in __enter__
[ytdl_hook]   File "yt_dlp\cookies.py", line 1272, in open
[ytdl_hook] FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\~/cookies.txt'
[ytdl_hook] [PYI-38012:ERROR] Failed to execute script '__main__' due to unhandled exception!
[ytdl_hook] youtube-dl failed: unexpected error occurred
AV: 00:00:01 / 03:47:00 (0%) A-V:  0.000
Failed to recognize file format.
```

**Comment by guidocella** [comment]
You can use this script

```lua
mp.set_property('ytdl-raw-options', 'cookies=' .. mp.command_native({'expand-path', '~~/cookies.txt'}))
```

or you can just use `--cookies-from-browser`.

**Comment by ahaoboy** [comment]
> or you can just use `--cookies-from-browser`.

Does not work on Windows 
```
ytdl-raw-options=cookies-from-browser=edge,mark-watched=
```
```
[ytdl_hook] ERROR: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
[ytdl_hook] ERROR: Could not copy Chrome cookie database. See  https://github.com/yt-dlp/yt-dlp/issues/7271  for more info
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.
Exiting... (Errors when loading file)
```

It seems that the simplest way is to put yt-dlp and cookies in the directory where mpv.exe is located.

**Comment by Samillion** [comment]
For `cookies`, try to set an absolute path. See my config as example: [mpv.conf/ytdl](https://github.com/Samillion/mpv-conf/blob/759bd1866d0db910f8ddd628af2283ccb9c35de3/mpv.conf#L101)
```
ytdl-raw-options=cookies="C:\Program Files\mpv\ytdl_cookies.txt"
```

Extract cookies as described in the issue with an extension such as [this one](https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc).

**Comment by ahaoboy** [comment]
> For `cookies`, try to set an absolute path. See my config as example: [mpv.conf/ytdl](https://github.com/Samillion/mpv-conf/blob/759bd1866d0db910f8ddd628af2283ccb9c35de3/mpv.conf#L101) 

Thanks, I know that using absolute paths for yt-dlp and cookies will work, but for a script developer, if all configurations and dependent programs can be placed in the portable_config directory, it will be easy for users to install and remove.

**Comment by verygoodlee** [comment]
cookies path also support environment variables.

On linux, ~~/ is usually the same directory as ~/.config/mpv/, and ~/ is equivalent to $HOME/, so you can use `ytdl-raw-options-append=cookies=$HOME/.config/mpv/cookies.txt`.

In the same way, you can use `ytdl-raw-options-append=cookies=%APPDATA%\mpv\cookies.txt` on Windows.

But portable config is more popular with users on Windows, there's no good solution for it, you can set a [MPV_HOME](https://mpv.io/manual/master/#environment-variables-mpv-home) environment variable and use `ytdl-raw-options-append=cookies=%MPV_HOME%\cookies.txt`.

**Comment by verygoodlee** [comment]
> You can use this script
> 
> ```lua
> mp.set_property('ytdl-raw-options', 'cookies=' .. mp.command_native({'expand-path', '~~/cookies.txt'}))
> ```

[change-list](https://mpv.io/manual/master/#command-interface-change-list) command is better, and there's a way to do it without adding extra scripts,
execute lua code via auto profiles, write simple lua code in `profile-cond`.
```conf
ytdl-raw-options-append=cookies=~~/cookies.txt

[expand-cookies-path]
profile-cond=ytdl_raw_options.cookies:match('^~~/') and mp.commandv('change-list', 'ytdl-raw-options', 'append', 'cookies='..mp.command_native({'expand-path', ytdl_raw_options.cookies}))
```

**Comment by ahaoboy** [comment]
> [expand-cookies-path]
> profile-cond=ytdl_raw_options.cookies:match('^~~/') and mp.commandv('change-list', 'ytdl-raw-options', 'append', 'cookies='..mp.command_native({'expand-path', ytdl_raw_options.cookies}))


Genius, this is the magic code 👍

**Comment by kasper93** [comment]
`ytdl-raw-options`, are passed as-is. Use the solution above to expand the paths/properties if needed.
