### ISSUE TITLE
cdda:// seeking broken?

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1555]
When i try to seek when playing cdda://, i get:
```
[cdda] Cannot seek forward in this stream
```
or
```
[cdda] Cannot seek backward in linear streams!
```
Skipping "chapters" (tracks) won't work as well (same messages)
using a cache:
```
[cache] Cannot seek forward in this stream
[cache] Cannot seek backward in linear streams!
```
using precise seeking doesn't make a difference.

I don't know if it may depends by the fact that i'm using cdemu and not a real CD, but mplayer seems to work without issues.

**Comment by wm4** [comment]
Just a stupid oversight. Fixed in master.

**Comment by kokoko3k** [comment]
Works fine now, thanks.
