### ISSUE TITLE
Hardcoded shared library path [/usr/lib64/libmujs.so] ?

### ISSUE THREAD

**Issue by VielLosero** [mpv-player/mpv#15566]
### Important Information

```text
- mpv version: 0.38.0
- Platform version: slackware 15.0
- Meson version: meson-0.59.4

[root@arcadia test1]# mpv --version
mpv 0.38.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Dec 24 2024 03:24:30
libplacebo version: v7.349.0
FFmpeg version: 4.4.5
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
```

### Reproduction Steps

Install mpv with "sbopkg -i  mpv" from slackbuilds on slackware 15.0
meson \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --sysconfdir=/etc \
  --mandir=/usr/man \
  -Dbuildtype=release \
  -Dmanpage-build=enabled \
  -Djavascript=disabled \
  -Dlibmpv=true \
  -Dhtml-build=enabled \
  -Dcdda=enabled \
  -Ddvdnav=enabled \
  -Ddvbin=enabled \
  $pipewire \
  $BUILD_OPTS \
  . build

### Expected Behavior

[root@arcadia test]# readelf -d usr/bin/mpv |head -20

Dynamic section at offset 0x245990 contains 70 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libass.so.9]
 0x0000000000000001 (NEEDED)             Shared library: [libavcodec.so.58]
 0x0000000000000001 (NEEDED)             Shared library: [libavfilter.so.7]
 0x0000000000000001 (NEEDED)             Shared library: [libavformat.so.58]
 0x0000000000000001 (NEEDED)             Shared library: [libavutil.so.56]
 0x0000000000000001 (NEEDED)             Shared library: [libplacebo.so.349]
 0x0000000000000001 (NEEDED)             Shared library: [libswresample.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libswscale.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libcdio_paranoia.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcdio_cdda.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcdio.so.19]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdvdnav.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libmujs.so]   <----
 0x0000000000000001 (NEEDED)             Shared library: [liblcms2.so.2]

### Actual Behavior

[root@arcadia test]# readelf -d usr/bin/mpv |head -20

Dynamic section at offset 0x245990 contains 70 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libass.so.9]
 0x0000000000000001 (NEEDED)             Shared library: [libavcodec.so.58]
 0x0000000000000001 (NEEDED)             Shared library: [libavfilter.so.7]
 0x0000000000000001 (NEEDED)             Shared library: [libavformat.so.58]
 0x0000000000000001 (NEEDED)             Shared library: [libavutil.so.56]
 0x0000000000000001 (NEEDED)             Shared library: [libplacebo.so.349]
 0x0000000000000001 (NEEDED)             Shared library: [libswresample.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libswscale.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libcdio_paranoia.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcdio_cdda.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcdio.so.19]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libdvdnav.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [/usr/lib64/libmujs.so]   <----
 0x0000000000000001 (NEEDED)             Shared library: [liblcms2.so.2]

### Log File

[sbopkg.mpv.installation.txt](https://github.com/user-attachments/files/18239543/sbopkg.mpv.installation.txt)

### I carefully read all instruction and confirm that I did the following:

- [X] I tested with the latest mpv version to validate that the issue is not already fixed.
- [X] I provided all required information including system and mpv version.
- [X] I produced the log file with the exact same set of parameters, and conditions used in "Reproduction Steps".
- [X] I produced the log file while the behaviors described in "Actual Behavior" were actively observed.
- [X] I attached the full, untruncated log file.

**Comment by sfan5** [comment]
You can see how meson links the libraries in the log:
```
[281/283] cc -o mpv [...] -Wl,--as-needed -Wl,--allow-shlib-undefined -Wl,-O1 -Wl,-z,noexecstack -rdynamic -O2 -fPIC -Wl,--start-group -ldl [...] /usr/lib64/libmujs.so [...] -Wl,--end-group
```
I can't figure out why, but this seems to be an oddity with mujs that I can reproduce on my Arch system:
```
% echo "int main() { return 0; }" >x.c
% gcc x.c -o x /usr/lib/libmujs.so 
% readelf -d x | grep \.so
 0x0000000000000001 (NEEDED)             Shared library: [/usr/lib/libmujs.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
% gcc x.c -o x /usr/lib/libavcodec.so
% readelf -d x | grep \.so           
 0x0000000000000001 (NEEDED)             Shared library: [libavcodec.so.61]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```
Either way nothing to do with mpv.

> - [x] I tested with the latest mpv version to validate that the issue is not already fixed.

That's not correct, 0.38.0 is an older version. No need to lie in your bug report.

**Comment by VielLosero** [comment]
> Either way nothing to do with mpv.
> 
>         I tested with the latest mpv version to validate that the issue is not already fixed.
> 
> That's not correct, 0.38.0 is an older version. No need to lie in your bug report.

Upss so sorry.

> [281/283] cc -o mpv [...] -Wl,--as-needed -Wl,--allow-shlib-undefined -Wl,-O1 -Wl,-z,noexecstack -rdynamic -O2 -fPIC -Wl,--start-group -ldl [...] /usr/lib64/libmujs.so [...] -Wl,--end-group

Thanks.

**Comment by qyot27** [comment]
> I can't figure out why, but this seems to be an oddity with mujs

https://git.ghostscript.com/?p=mujs.git;a=blob;f=Makefile

Line 111 is where it generates the pkgconfig file, by echoing directly out of the Makefile (rather than using a template .pc.in file like other build systems might use).  So at line 117 when it gets to the `Libs:` declaration, `echo >> $@ Libs: -L$(libdir) -lmujs` is interpreting that libdir usage rather than actually generating it the way pkg-config files generally are.  Here on Ubuntu 24.10, this is what mujs.pc looks like:
```
$ cat /usr/lib/x86_64-linux-gnu/pkgconfig/mujs.pc 
Name: mujs
Description: MuJS embeddable Javascript interpreter
Version: 1.3.3
Cflags: -I/usr/include
Libs: -L/usr/lib/x86_64-linux-gnu -lmujs
Libs.private: -lm
```

A 'normal' pkg-config file doesn't typically look like that.  It abstracts libdir and includedir away, usually as a derivative of the install prefix, and uses `${libdir}` as the reference in the Libs field (note the curly braces, rather than the parentheses as in the Makefile).  See for example fontconfig:
```
$ cat /usr/lib/x86_64-linux-gnu/pkgconfig/fontconfig.pc 
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include
sysconfdir=/etc
localstatedir=/var
PACKAGE=fontconfig
confdir=${sysconfdir}/fonts
cachedir=${localstatedir}/cache/${PACKAGE}

Name: Fontconfig
Description: Font configuration and customization library
Version: 2.15.0
Requires:  freetype2 >= 21.0.15
Requires.private:  expat
Libs: -L${libdir} -lfontconfig
Libs.private:  
Cflags: -I${includedir}
```

So if you wanted to test it, you could modify mujs.pc to use a more proper layout and see if that resolves the issue.

**Comment by sfan5** [comment]
As you can see in my example this happens when linking `libmujs.so` directly with no involvement of pkg-config at all,  so that's not it.
