### ISSUE TITLE
Adding shortcut for reloading .srt file in case of update

### ISSUE THREAD

**Issue by nicolahcm** [mpv-player/mpv#15582]
### Expected behavior of the wanted feature

I tried with the shortcut J, which switches between known subtitles file in the folder, but does not work.

Well, I am trying to add subtitles, or fix, or translate to some video. When I update the .srt file, I save it and then switching back to mpv, I would like to just press a button to reload with the updated .srt file. The button J does not do it. Switches, but keeps the old file before update. Therefore, I have everytime to drag and drop again the .srt file to the mpv player, in order to see the newly updated .srt file. It is a little uncomfortable.

I hope you can add a shortcut button, 
or even better a branch for especially those who translate, fix subtitles, etc... and would like to see in real time, after saving the .srt/.ass file. For example, by doing such that the .mpv player will check for changes in the .srt/.ass file every 1 second, or reupload it again every X time. 

I especially use MPV just for translation, fixing subtitles etc... And it would be a nice thing, I think also other people use it for the same purpose. 

Thank you very much

**Comment by guidocella** [comment]
https://mpv.io/manual/master/#command-interface-sub-reload
