### ISSUE TITLE
[Request] Option to run shaders on every display refresh as opposed to supplied video frame

### ISSUE THREAD

**Issue by BuyMyMojo** [mpv-player/mpv#15590]
### Expected behavior of the wanted feature

Some shaders like [CRT Beam Simulator](https://github.com/blurbusters/crt-beam-simulator) are needed to be rendered for display refresh in order to work and produce a good visuals.

A simple toggle in the form of a config option + cli argument to enable this behavior would be great.

It's obvious that this shouldn't be a new default functionality for performance reasons of course so an opt in setting makes the most sense.

The developer behind the shader mentioned above and the first [3:2 pulldown deinterlacing algorithm](https://web.archive.org/web/20001215064600/https://deinterlace.sourceforge.net/32Spec.htm) wrote a pretty thorough explanation on requirements in my issue [here](https://github.com/blurbusters/crt-beam-simulator/issues/6#issuecomment-2564159598)

**Comment by Dudemanguy** [comment]
If I understand correctly, you want to just draw on every hz of the monitor's display rate. This mode already exists. Any of the `--video-sync=display-*` modes will do this. You probably want `--video-sync=display-resample` in practice.

**Comment by Akemi** [comment]
not sure if this is what you are looking for but this sounds like you want `video-sync=display-resample` (or any of the `display-*` modes, https://mpv.io/manual/master/#options-video-sync) and hook your shader to OUTPUT (see `--glsl-shader` https://mpv.io/manual/master/#options-glsl-shader).

> The modes starting with display- try to output video frames completely synchronously to the display, using the detected display vertical refresh rate as a hint how fast frames will be displayed on average. These modes change video speed slightly to match the display

also see this for some more informations https://github.com/mpv-player/mpv/wiki/Video-output---shader-stage-diagram

**Comment by mdrejhon** [comment]
> These modes change video speed slightly to match the display

My CRT simulator also happens to support non-integer native:simulated Hz ratios - it's impressive how we solved a time based jitter antialiasing problem, especially when you have enough refresh rate ratio for it to perform well. . 

You can do 24fps movies via a simulated 72Hz CRT on a 240Hz OLED, it will temporally look really good in tests outside of MPV.  

It reduces display motion blur fantastically!

**Comment by mdrejhon** [comment]
Update, I have published Version 1.0.2 of Blur Busters Open Source Display Shaders Specification.

www.blurbusters.com/open-source-display#spec

MPV Player as an "Independent Software Vendor", can at their option, choose to support user plug-in refresh cycle shaders.  There's a [lot of other use cases](https://blurbusters.com/open-source-display#usecases), other than CRT simulation too, including accessibility and ergonomic features, as well as 35mm projector simulation.
