### ISSUE TITLE
cdda:// ;  property "=chapter" == "chapter" -1 ?

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1559]
when querying the chapter property and playing a cd audio, the raw property "=chapter" starts from -1
while the string property "chapter" starts at 0:

See both answers here:
```
# mpv cdda://  -ao null --input-file=/tmp/input 
[input_file] Client connected
Playing: cdda://
[cdda] Switched to track 1
 (+) Audio --aid=1 (pcm_s16le)
AO: [null] 44100Hz stereo 2ch s16
A: 00:00:02 / 01:15:17 (0%)
=chapter=-1
A: 00:00:05 / 01:15:17 (0%)
chapter=(0) of 17
A: 00:00:28 / 01:15:17 (0%)


Exiting... (Quit)
```
Is this intentional?

**Comment by wm4** [comment]
Yes. -1 is before the first chapter (which is chapter 0), and OSD formatting starts counting chapters from 1.

**Comment by kokoko3k** [comment]
Thanks, so i assume it is safe to use =chapters from -1.
