### ISSUE TITLE
--force-window behavior change [was: acc5e8f makes for unsightly 'normal' use on vids]

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#1561]
Maybe it fixes something for obscure use cases but in general looks weird now in normal use like from the context menu
Then there is a quick empty 'window', some other black 'splotch' to the side followed by actual vid window that may or may not follow geometry if set in the config.

I see youtube-dl mentioned in commit, maybe it's just me but for url's I use cli so if waiting for  a few sec's who needs an empty window, have the console already open.
Luckily atm the commit is easily reverted..

**Comment by wm4** [comment]
Well, that's the nature of it. Either you get a temporary window that shows nothing and has the "wrong" size, or you show the window only once the video size is known. Maybe the window could be shown after a timeout, but then sporadic "flicker" could happen anyway if the dummy window is created shortly before video decoding has initialized. It'd look like a race condition bug. Can't do much about this.

>Maybe it fixes something for obscure use cases but in general looks weird now in normal use like from the context menu

It's intended for the case when you pretend mpv is a GUI application, i.e. it's not used from CLI.

**Comment by wm4** [comment]
Also, here's the commit reference, github doesn't turn it into a link if it's in the issue title: acc5e8f

**Comment by Zehkul** [comment]
xfce and openbox also place the window incorrectly, worked fine in kde and enlightenment (that’s all I tested)
Even though I use Openbox, I prefer the new behavior by far. It’d be nice if the WM just did the right thing though…

Would letting hook scripts decide on the behavior of force-window be an option? Then the youtube-dl hook could just choose to show the window earlier if force-window is set. It’s not too hard however to just associate local video files with ``mpv --force-window=no`` (or the other way round for urls)

**Comment by wm4** [comment]
> It’d be nice if the WM just did the right thing though…

I wonder if there's a way to make the window manager redecide the placement on resize, but I haven't found one yet. (Might be a matter of setting more, or fewer hints.)

**Comment by mc4man** [comment]
the " pretend mpv is a GUI application" is generally from the context menu or a DnD launcher. So that obviously benefits from --force-window. I don't see that many scenarios from context or DnD that have delayed opening or delayed for more than a sec. or so. Here maybe a playlist file of url(s), in that case as a user I'm already aware that there could be a delay depending on url & or other factors. Can't see why I'd want to see an empty window.

From the context or DnD some apps use StartupNotify=true in their .desktop to give a spinning cursor till app is opened but that's not an option for mpv's .desktop that's useful.

In any event will revert for ppa use as I've never had a single complaint/comment about waiting on a window nor seen any bugs in Debian/Ubuntu regarding such.

**Comment by wm4** [comment]
Why did you close this?

**Comment by mc4man** [comment]
I thought it was a dead dog

**Comment by wm4** [comment]
I'm not sure what's the better behavior. So this issue is about discussing which one is better.

**Comment by g1400289** [comment]
It looks unsightly and messes with window placement. I would like it if there was an option to turn it off.

**Comment by wm4** [comment]
Reverted.
