### ISSUE TITLE
Toggling OSD has one step too many that does seem to do anything

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#1562]
When I toggle OSD using the key "o", when there is nothing on the screen, I have to press "o" twice to get to time played, then press it once to get to time played/total time and then press once again to clear the OSD - however, I then have to press o two times again. It seems weird. My mpv version is (from a Ubuntu PPA):

    mpv git-5e9f791 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
    built on 2015-02-04T01:00:05

Here is my input.conf:

    SHIFT+PGUP seek -60000
    PGDWN seek 600
    PGUP seek -600
    o osd 
    O show_progress
    q quit_watch_later
    Q quit
    ESC quit_watch_later
    R add sub-scale +0.1               
    T add sub-scale -0.1"""

**Comment by wm4** [comment]
The ``osd`` command cycles between 4 states:
- level 0: absolutely no OSD visible
- level 1: OSD normally visible (e.g. if you seek or issue other commands)
- level 2: time visible
- level 3: time and duration visible

Switching from 3 to 0 and 0 to 1 both don't show anything on the OSD (when switching), which might explain your confusion. You can also just use ``cycle_values`` to cycle between two states or so.

**Comment by felagund** [comment]
Oh, I see. Has that always been the case? I do not remember this in earlier versions.

What would the corresponding line in input.conf be?
Something like this:

    o cycle_values osd "?" "?" "?"

I cannot make it from here: https://raw.githubusercontent.com/mpv-player/mpv/master/etc/input.conf

**Comment by wm4** [comment]
Something like: ``o cycle_values osd-level "1" "2"``

>Has that always been the case? I do not remember this in earlier versions.

Yes. This is MPlayer-inherited behavior though the OSD messages were changed in mpv at some point (twice, because the first change was not popular).

**Comment by felagund** [comment]
Yeah, that works, thanks. However, it first shows "osd-level: 1" and actually displays the time only after a second or so. Is there a way to force it to go straight away to the time? (Like applying --osd-duration . just to this one command - I am not sure if that is possible from reading https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst )

**Comment by wm4** [comment]
Add ``no-osd`` between the key name and the command.

**Comment by felagund** [comment]
Alright, that works perfectly, thanks!
