### ISSUE TITLE
PNG rendering of transparent areas is borked sometimes.

### ISSUE THREAD

**Issue by throwaway002** [mpv-player/mpv#1565]
The renderer appears to not multiply the alpha channel.

It displays png like this:
http://a.pomf.se/bcssun.png

Source image:
http://a.pomf.se/hlcxqk.png

Renamed config file to config.old, ran with mpv %1 --loop=inf, same result. Fwiw, I only discovered this when I started to use mpv as a system-wide image previewer application. Overkill yes, but mpv's ability to apply filters to gifs and high-quality scalers is hard to beat.

**Comment by haasn** [comment]
Alpha blending is disabled by default. Enable it using the ```alpha=blend``` sub-option to -vo opengl.

**Comment by wm4** [comment]
Yes, we recently changed vo_opengl to ignore alpha, so it will show even areas that are supposed to be invisible. We did the change to fix something else. We can't change this back until ffmpeg adds API that tells is whether the alpha channel contains something useful or not.

**Comment by wm4** [comment]
(Not really "bug" in ffmpeg and libav, but they need to be extended to provide the correct info.)

**Comment by Cyberbeing** [comment]
> Yes, we recently changed vo_opengl to ignore alpha, so it will show even areas that are supposed to be invisible.

Is there is reason why alpha=yes is also broken with this image? Are you sure there isn't a bug regarding utilizing alpha channel with opengl fbo formats which should support it like rgba, rgba16, rgba16f, rgba32f? 

>We can't change this back until ffmpeg adds API that tells is whether the alpha channel contains something useful or not.

Or were you saying that alpha=yes being broken is related and actually caused by a limitation with ffmpeg?

**Comment by wm4** [comment]
See #1528.

**Comment by wm4** [comment]
FFmpeg considered the case that broke us a bug and applied a fix. So I reverted this.

Alpha support on Libav is pretty broken, so I don't care about that.
