### ISSUE TITLE
Reconnect when no data is downloaded within X seconds

### ISSUE THREAD

**Issue by m13253** [mpv-player/mpv#1566]
I use a slow Wi-Fi and sometimes drop connection while watching video over HTTP.

However MPV does not detect connection loss, and still tries to wait for the cache to fill:
```
[cache] Cache is not responding - slow/stuck network connection?
[cache] Cache keeps not responding.
```

I have to manually restart MPV to get rid of it. But it means manual seek.

I request an option to set a timeout value. When no data is downloaded within X seconds, terminate the network connection and reconnect.

Thanks.

**Comment by wm4** [comment]
Well, there is already a timeout, but it's hidden deeply within obscure mpv and ffmpeg options. I can try to add a better timeout option.

**Comment by m13253** [comment]
> Well, there is already a timeout, but it's hidden deeply within obscure mpv and ffmpeg options. I can try to add a better timeout option.

Thank you for your quick response. :smile: 

Do you mean there is already an undocumented option? Wish to improve it.

(P.S. I finally got online after 10 minutes of struggling with my Wi-Fi card)

**Comment by wm4** [comment]
>Do you mean there is already an undocumented option?

Well, it's a FFmpeg option. It's documented in FFmpeg, and there's a documented way in mpv to set such options, but the summary is that finding this option and setting it is 100% unintuitive.

I added an option for setting it directly; please report back if it works as intended!

**Comment by m13253** [comment]
Seems to work as intended.

Reconnecting works and playback resumes when network is stucked **for a short time**.

However, if the connection drops for **a long time**, MPV quits after 5 failed tries.

That may be an FFmpeg issue and I will try to get in touch with them.

Log:
```
AV: 00:00:11 / 00:24:59 (0%) A-V:  0.000 Cache:  1s+14KB
[cache] Cache is not responding - slow/stuck network connection?
(Buffering) AV: 00:00:13 / 00:24:59 (0%) A-V: -0.000 Cache:  0s+14KB
[ffmpeg] Connection lost! Attempting to reconnect (1)...
[ffmpeg] tcp: Failed to resolve hostname cc.acgvideo.com: Name or service not known
[ffmpeg] Connection lost! Attempting to reconnect (2)...
[ffmpeg] tcp: Failed to resolve hostname cc.acgvideo.com: Name or service not known
[ffmpeg] Connection lost! Attempting to reconnect (3)...
(Buffering) AV: 00:00:13 / 00:24:59 (0%) A-V: -0.000 Cache:  0s+14KB
[ffmpeg] tcp: Failed to resolve hostname cc.acgvideo.com: Name or service not known
[ffmpeg] Connection lost! Attempting to reconnect (4)...
[ffmpeg] tcp: Failed to resolve hostname cc.acgvideo.com: Name or service not known
[ffmpeg] Connection lost! Attempting to reconnect (5)...
(Buffering) AV: 00:00:13 / 00:24:59 (0%) A-V: -0.000 Cache:  0s+14KB
[ffmpeg] tcp: Failed to resolve hostname cc.acgvideo.com: Name or service not known
[file-cache] unexpected EOF
[file-cache] unexpected EOF
[file-cache] unexpected EOF
[file-cache] unexpected EOF
AV: 00:00:13 / 00:24:59 (0%) A-V: -0.000 Cache:  0s+0KB
[file-cache] unexpected EOF
Exiting... (End of file)
```

Thank you for your work! Maybe I need to fix things up at FFmpeg side.

**Comment by wm4** [comment]
The reconnecting is actually done by mpv. Currently it's limited to 5 tries with a rather small extra timeout. I'll change this too.

**Comment by wm4** [comment]
Did something. Still only 6 tries, with the last 2 tries or so waiting at most 10 seconds between the reconnect attempts.

**Comment by m13253** [comment]
Nice. Thanks.
