### ISSUE TITLE
memory leak after seek streaming video.

### ISSUE THREAD

**Issue by zhangn1985** [mpv-player/mpv#1567]
mpv version:

mpv git-edc100e (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-01-21T23:57:21
libav library versions:
   libavutil       53.3.0
   libavcodec      55.34.1
   libavformat     55.12.0
   libswscale      2.1.2
   libavresample   1.1.0

mpv config:
ao=pulse,alsa
vo=opengl-hq
cache-secs=600

OS: debian 7

reproduce step:
1, play a video via http or https, video format is not specified, video length should be longer than 1h, size should be larger than 1G.
2, seek video forward or backward
3, wait, and check memory. mpv will eat all memory.

reproducibility: 100%

**Comment by wm4** [comment]
Please make sure you're not affected by this bug: http://git.libav.org/?p=libav.git;a=commit;h=fbd6c97f9ca858140df16dd07200ea0d4bdc1a83

I'm not sure how you can check this; maybe ask your distro maintainer.

**Comment by wm4** [comment]
PS: if you have valgrind output showing the memory leak, that would be fine too.

**Comment by zhangn1985** [comment]
I will try rebuild libav with the patch, and try again.

**Comment by zhangn1985** [comment]
after rebuild mpv with libav release/10 this issue disappears
