### ISSUE TITLE
[x11] 'geometry=50%:50%' in config not working correctly

### ISSUE THREAD

**Issue by Shudouken** [mpv-player/mpv#1568]
I just re-built mpv from git and saw it now opens an empty window before loading the actual video.

The problem is that geometry=50%:50% now centers the blank window when opening a file, and then mpv proceeds to load the video without re-centering it. It still works correctly if the video is small enough to be loaded instantly.

Here's a recording to illustrate the issue
http://a.pomf.se/jzshae.webm

**Comment by wm4** [comment]
Almost the same as #1561, except recentering after resize should in theory work.

**Comment by mc4man** [comment]
Do know why it goes off of 50%:50% here with compiz but can show it developing in 2 screenshots of a screen cap.
This is the dummy window waiting on ytdl, the window is centered
![screenshot from 2015-02-07 18 06 19](https://cloud.githubusercontent.com/assets/5961561/6094346/ba99d290-aef4-11e4-978a-2c59ce7586c5.png)

This is just as mpv is opening or filling in the real vid window. A black box (no deco) has appeared offset to left & above. The new real window will fill in using the orig. dummy's right & bottom & the left &top of this new black area. So the result is the new real vid is no longer centered as it fills in using the orig. dummies right & bottom
![screenshot from 2015-02-07 18 06 54](https://cloud.githubusercontent.com/assets/5961561/6094362/6801aaa2-aef5-11e4-8ea7-15737d257842.png)

**Comment by wm4** [comment]
Reverted the --force-window change; but technically this is still a "bug" as resizing the video should recenter the window in any case.

Does ``--force-window-position`` help?
