### ISSUE TITLE
Config files are read in wrong order

### ISSUE THREAD

**Issue by Lamieur** [mpv-player/mpv#1569]
Hello,

Looks like mpv always reads files named "config" (as in: ~/.mpv/config) BEFORE files named "mpv.conf" (as in: /etc/mpv/mpv.conf and ~/.config/mpv/mpv.conf)

What this means is that my settings in ~/.mpv/config get overwritten by global settings from /etc/mpv/mpv.conf.

This, to me, breaks the assumption that search path from mp_config_dirs() is ordered by priority.

Would be much less of a problem if there was no support for ~/.mpv/config anymore, then I'd migrate to the new path immediately and not spend whole morning wondering why I can't change "vo" in the config but can on the command line :)

I'm writing this mainly so others can google this issue and save the hair pulling.

**Comment by wm4** [comment]
This happens because there is a function to search a config file with a specific name (which returns a sorted list of files), and the fallback is handled by first searching for ``mpv.config``, then ``config``. It's not expected that users mix old and new conventions.

(Though if it were up to me, I'd drop global config files completely.)

**Comment by Lamieur** [comment]
But I'm not mixing conventions (I'm your "user"), I was only hit by this because my _distro_ put "vo=opengl" in /etc/mpv/mpv.conf which I had no idea existed... (until trying to debug the problem which happened after mpv update)

If my config stopped working completely and not just some of the settings in it, I'd find the solution (which is to move config to ~/.config/mpv/mpv.conf) instantly in the man page.

If you still support old config location, then ~/.mpv/config should have higher priority than /etc/mpv/mpv.cong. Otherwise, just remove semi-support of that config name completely, problem solved :)

**Comment by wm4** [comment]
> I was only hit by this because my distro put "vo=opengl" in /etc/mpv/mpv.conf which I had no idea existed... 

Oh yeah, that's bad. Yes, the old location is still supported, as long as you don't mix conventions. Tell your distro not to do stupid things. ("vo=opengl" is even the default...)

**Comment by wm4** [comment]
Any suggestions how to fix it? Dropping either ``mpv.conf`` or ``config`` is probably not acceptable, and making the code somehow look for several config filenames at once would be a medium complication.

**Comment by wm4** [comment]
Here we go. I find dropping ``config`` regrettable, but in the long range it'll lead to less pain.
