### ISSUE TITLE
Hide Title Bar

### ISSUE THREAD

**Issue by aijcoa** [mpv-player/mpv#157]
I'm using MPV on OSX. Is it possible to hide the title bar?

Thanks.

**Comment by boscowitch** [comment]
a key command for this would be nice since by default it opens with in most systems and sometimes one wants to move the window in a corner remove and the border to save the space

**Comment by wiiaboo** [comment]
@boscowitch `Ctrl+1 cycle border` in input.conf.

**Comment by boscowitch** [comment]
Nice thx !  guess this should be added in a comment in the template git input.conf too so next time others find it too

**Comment by electrodragon** [comment]
`mpv -border=no anyTrack.mp4`

**Comment by wenmin92** [comment]
When `border=no`, the window can't resize?

**Comment by Akemi** [comment]
don't reply on such an old issue. on macOS you can resize the window no matter the border setting.

**Comment by wenmin92** [comment]
@Akemi I'm sorry for this while I am not sure is this a problem or some settings I ignore. On Windows, no border no scale, but move.
If this is a problem, I will create an issue.

**Comment by Akemi** [comment]
i don't know about windows, since i am only using macOS. you can either create an issue or ask on irc.

**Comment by wenmin92** [comment]
Thanks for your reply, I have solved this, it is a problem of mpv.net, not mpv. Sorry...
