### ISSUE TITLE
Adding a format argument to the screenshot_to_file command

### ISSUE THREAD

**Issue by steinuil** [mpv-player/mpv#1571]
Currently, when using the `screenshot_to_file` command without providing an extension in the filename argument, the file format of the output file is “arbitrary”.

Would it be possible to add an optional argument to define the format?

**Comment by wm4** [comment]
I'd start with questioning why you want to use a filename without extension?

**Comment by steinuil** [comment]
In a script I wrote I'm temporarily saving the screenshot to /tmp which is kind of a shitty hack and doesn't make it portable, I'd rather replace that with lua's built-in `io.tmpfile` or `os.tmpname` which obviously wouldn't specify the file extension.
