### ISSUE TITLE
Native fullscreen mode in OSX

### ISSUE THREAD

**Issue by VFK** [mpv-player/mpv#1572]
Maybe i've missed a discussion on this matter somewhere but what has happened with the native OS X fullscreen mode? None of the options (`--lion-fs`, `--native-fs`, etc.) are working for quite some time now. I'm on Yosemite, mpv v0.7.3 from "Releases" tab.

**Comment by pigoz** [comment]
Yes it was removed quite some time ago (between 0.6.0 and 0.7.0), because it was problematic and buggy. It was a bad idea to introduce it in mplayer2 in the first place.
