### ISSUE TITLE
Add support for playlist.

### ISSUE THREAD

**Issue by d3dx9** [mpv-player/mpv#1576]
Hi,

could you make it possible, to add items to a "playlist" like in the newest build of mplayer?

So you could use the cli like 'mpv add "link or file"'

kind regards
d3dx9

**Comment by ChrisK2** [comment]
obligatory link to https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv

**Comment by wm4** [comment]
I'm pretty sure vanilla mplayer does not do this.

**Comment by d3dx9** [comment]
@ChrisK2 - thanks, can I use this with youtube + soundcloud too?

@wm4 - yeah sorry, I misread the wrapper of nodejs for mplayer.

**Comment by ChrisK2** [comment]
Yes, should work.
