### ISSUE TITLE
Swapped colors when using vaapi acceleration with opengl video output

### ISSUE THREAD

**Issue by tngit** [mpv-player/mpv#1577]
Using --hwdec=vaapi the colors blue and red appear swapped, resulting in blue faces and similar unpleasing results. 
Trying different configurations I had the following results:

 vo | hwdec | resulting colors
-----|----------|-------------------
opengl| vaapi| wrong
opengl| no | correct
opengl| vaapi-copy| correct
vaapi| vaapi | correct

I'm using debian jessie with fglrx on an AMD E145 (contains a Radeon HD 8240). Details about installed packages are collected in the table below:

package | version
-----------|----------
mpv | 0.6.2-2
fglrx-driver| 1:14.9+ga14.201-2
xvba-va-driver| 0.8.0-9
libavcodec56|6:11.2-1
xserver-xorg| 1:7.7+7

Please let me know if you need further information.

**Comment by wm4** [comment]
I know vdpau sometimes has swapped colors (because of a hack for Flash, which "accidentally" swapped the planes). But I haven't heard about such a thing on vaapi.

Maybe it has to do with the fact that the xvba backend for vaapi has been unmaintained for years.

**Comment by wm4** [comment]
OK. Uninstall ``xvba-va-driver``. Supposedly even the closed source driver (fglrx) supports vaapi natively.

**Comment by tngit** [comment]
Removing `xvba-va-driver` removes vaapi support on my system. Mpv will fall back to unaccelerated decoding:

    libva info: VA-API version 0.36.0
    libva info: va_getDriverName() returns 0
    libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/fglrx_drv_video.so
    libva info: va_openDriver() returns -1
    [vaapi] vaInitialize(): unknown libva error
    [vo/opengl] Couldn't load hwdec driver 'vaapi'

`fglrx_drv_video.so` is part of `xvba-va-driver`. 

Do I miss anything?

Anyway, using `--vo=vaapi --hwdec=vaapi` seems to work just fine for me. So this issue is not really a problem for me. The fact that `--vo=opengl --hwdec=vaapi` swaps colors whereas `--vo=opengl --hwdec=vaapi-copy`does not, led me to think that this could be a bug with mpv. If this is a misassumption please feel free to close this issue.

**Comment by wm4** [comment]
>fglrx_drv_video.so is part of xvba-va-driver.

Maybe I was misinformed then. Sorry about that. I tried searching for it, but all I found was the unmaintained freedesktop-hosted wrapper.

Anyway, one more thing you could test: how does ``--hwdec=vaapi-copy`` behave?

**Comment by tngit** [comment]
As I wrote above: `--hwdec=vaapi-copy` does not swap colors. Did I misunderstand your question?

**Comment by wm4** [comment]
No. I overlooked that you provided this info already.

I'm not sure what else we could try. Other than writing a shader snippet that transforms the broken color back to "normal" or so.

**Comment by tngit** [comment]
Ah, ok. 

My knowledge of video codecs, video drivers and video players is extremely limited. 
If I understand you correctly, you are assuming that this is more likely a bug with vaapi or how different vaapi-libraries interact with each other than a bug with mpv itself, correct?

If this is correct, would it be possible (and a good idea) to force `--vo=vaapi` when using `--hwdec=vaapi`? Or perhaps only do this if the va-driver is `Splitted-Desktop Systems XvBA backend`, in case systems with intel's graphics cards behave differently?

If there is anything I can do to narrow the problem down, please let me know.

**Comment by wm4** [comment]
>If I understand you correctly, you are assuming that this is more likely a bug with vaapi or how different vaapi-libraries interact with each other than a bug with mpv itself, correct?

Yes.

>If this is correct, would it be possible (and a good idea) to force --vo=vaapi when using --hwdec=vaapi?

We could just disable vaapi if xvba and vo_opengl is detected. And maybe output a message how to get correct output. Redirecting the VO would be too messy, because the VO is initialized long before the video decoder. (So we can't know if vaapi is going to be used, or if it even exists on the system.)

**Comment by wm4** [comment]
Oh, and you could report this as a bug to AMD, but I wouldn't bet on any reaction.

**Comment by kevmitch** [comment]
I've never observed any thing like this on ivybridge or sanydbridge intel gpus with --vo=opengl --hwdec=vaapi, which indeed points to the amd driver being at issue.

Does amd have hwdec using the open source drivers. or is it just broken?

**Comment by wm4** [comment]
>Does amd have hwdec using the open source drivers. or is it just broken?

The opensource drivers support vdpau, and it should work. Unless it crashes, like in #1580.

**Comment by wm4** [comment]
So use ``--hwdec=vaapi-copy``. Even with Intel drivers, GLX interop is broken/shitty/slow, so this situation not surprising.
