### ISSUE TITLE
string encoding for libmpv

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1585]
I can see next description in `libmpv.h`:
```
* Warning: although the encoding is usually UTF-8, this is not always the
* case. File tags often store strings in some legacy codepage,
* and even filenames don't necessarily have to be in UTF-8 (at
* least on Linux). If you pass the strings to code that requires
* valid UTF-8, you have to sanitize it in some way.
```
So far, I've been using local 8bit encoding to hand over file name to libmpv.
Usually, local 8bit encoding is same as UTF-8 in most Linux and it worked fine.
Today, when I tried same code on windows whose local 8bit encoding is cp949, local 8bit encoding didn't work and UTF-8 worked.
This makes me confused because simple fopen() accepts only local 8bit encoding.

I can't understand what's going on here.
Does mpv handle strings as UTF-8 internally?
But the comment says filename can be non-UTF-8 and this misleads to use locale encoding.

**Comment by wm4** [comment]
> This makes me confused because simple fopen() accepts only local 8bit encoding.

On Windows, mpv uses _wfopen and similar functions to deal with unicode. It does so by converting the 8 bit strings as utf-8 to wchar_t. I agree that this might be confusing, so I'll add a notice.

**Comment by xylosper** [comment]
Let me clarify this:

* Use always utf-8 for windows
* Use local 8bit for filesystem name and utf-8 for others in Linux

May I think this is a recommended way?

**Comment by wm4** [comment]
>Use local 8bit for filesystem name and utf-8 for others in Linux

Not sure what you mean by this... anyway, the explanation in client.h should now be quite clear on this.

**Comment by xylosper** [comment]
Okay. Thank you. It helped.
