### ISSUE TITLE
[Feature request]: rescan subtitles on demand

### ISSUE THREAD

**Issue by luigino** [mpv-player/mpv#1586]
As per subject, would it be possible to implement such a function?

Regards

**Comment by ChrisK2** [comment]
what do you mean by "rescan"?

also see [sub_reload](http://mpv.io/manual/master/#command-interface-sub-reload-%5B%3Cid%3E%5D)

**Comment by wm4** [comment]
I suppose it's about finding new external subtitle files.

**Comment by luigino** [comment]
Precisely.
