### ISSUE TITLE
DXVA2: Crash on file actions

### ISSUE THREAD

**Issue by Skibicki** [mpv-player/mpv#1587]
mpv x64 and x86 lachs0r build 2015-02-13, Win 7 x64, AMD E-300 APU, AMD Catalyst 14.12
Setup: opengl or direct3d, wasapi or dsound, default options except hwdec=dxva2-copy
Crashes on: OSC Seeking (specific ordered chapter files), going forward or backward in playlist, exiting
-v output: http://pastebin.com/fcyKfv6D#

**Comment by wm4** [comment]
Looks like it crash when the decoder is uninitialized. Are you sure it crashes on normal seeking, or does it crash only when seeking in ordered chapters files? (Ordered chapters reinitialize the video decoder when segment boundaries are switched.)

**Comment by Skibicki** [comment]
I tried again and it crashed when seeking over chapter boundaries. Seeking within chapters was fine

**Comment by wm4** [comment]
Do you know if it's a regression?

**Comment by Skibicki** [comment]
Yes, a regression from the 2015-02-03 build. I'm not doing anything for a few hours so let me know if I can doing anything to help.

**Comment by wm4** [comment]
Can you tell me what commit hashes the last working and the first bad builds are? Or just paste the version statements the player prints when starting it without a file.

**Comment by Skibicki** [comment]
broken 9e14042
working 5de7f1c

**Comment by wm4** [comment]
I think this was caused by a behavior change in ffmpeg, not by a mpv change. Will fix.

**Comment by wm4** [comment]
>I think this was caused by a behavior change in ffmpeg, not by a mpv change. Will fix.

Yep, that was the reason. I asked lachs0r to make a new build.
