### ISSUE TITLE
problem with --log-file option on OS X?

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#1590]
Using the OS X  bundle version, if I add a "log-file=/xxx/yyy.log" option to the config file, a verbose log is created at that location. But the normal log at ~/Library/Logs/mpv.log is still written to with the usual terse info. Is that the expected behaviour? From the description I was expecting "log-file" to change the location of the regular log file. Also I couldn't figure out how to change the verbosity level (of either), adding "v" in the config file doesn't seem to work...

**Comment by wm4** [comment]
``But the normal log at ~/Library/Logs/mpv.log``

I don't know what that is. But apparently it's really written by ``macosx_redirect_output_to_logfile``. Pretty strange, and yes, it looks redundant.

**Comment by pigoz** [comment]
Well this is like this since mplayer1, maybe we could improve it. (All the bundle situation should be improved).
