### ISSUE TITLE
Possible to pass structures/arrays via --script-opts?

### ISSUE THREAD

**Issue by lvml** [mpv-player/mpv#1591]
I am trying to add a "blacklist"-feature to my xrandr plugin which would allow the user to blacklist certain mode/rate combinations that he knows not to work well.

But I wonder how a user could pass an array of { mode=..., rate=... } structures into my script.

When I try something like '--script-opts=xrandr-blacklist={rate=60}' then mpv complains: `Unparseable garbage at end of option value: '=60 }'`

Is there a way around this (other than asking the user to edit the script to define the blacklist there)?

**Comment by avih** [comment]
You could use `--script-opts=xrandr-blacklist=[rate=60,mode=3]` which seems to work on both bash and windows command prompt, and on both cases it passes the content between `[` and `]` as string - which you'd have to parse yourself.

I didn't try more complex content (which mpv might complain about), but passing a list of key1=value1,key2=value2,... seems to work.

**Comment by wm4** [comment]
Yeah, you can pass strings only as values, and ``[``...``]`` can quote strings. Very limited.

**Comment by lvml** [comment]
Ok, I'm using this now in https://github.com/lvml/mpv-plugin-xrandr/commit/5f187964dfa55776aa206b93ba347d1c1f6cc31b
