### ISSUE TITLE
[Ubuntu] Launcher not visible in Dash

### ISSUE THREAD

**Issue by Paradiesstaub** [mpv-player/mpv#1594]
OS: Ubuntu 15.05 64-Bit
Kernel: 3.18.0-13-generic
mpv: 0.7.3-1ubuntu1

Ubuntu uses a program called Dash to search/open applications. When searching for *mpv* no entry is shown. Starting mpv from the command-line works, but the icon displayed in the launcher has a very low resolution (~24x24px).

Executing the *mpv.desktop* start command `/usr/bin/mpv --no-terminal --force-window` in a terminal has no effect.

**Comment by wm4** [comment]
As it is, the mpv.desktop command line requires a file to be passed to it. Otherwise, it will exit immediately. Adding ``--idle`` should help; in this case mpv will keep an empty window open if nothing is played.

**Comment by mc4man** [comment]
It wouldn't show in the Dash due to NoDisplay=true in the .desktop which is proper as mentioned with current .desktop Exec=.
A launcher icon here is fine, 3 .png's are installed, it uses the 64x64 one here. 
(if you want try using full path for Icon= in mpv.desktop

Was considering using --idle in the .desktop as it could be useful though because it doesn't always return to default size (960 by 480)  after a vid is done so haven't yet. Not a big deal but returning to default would be better.

**Comment by wm4** [comment]
>because it doesn't always return to default size (960 by 480)  after a vid is done so haven't yet.

What? It certainly should...

**Comment by mc4man** [comment]
Should I start an issue ? (on size after vid finishes)
 It could possibly be a wm thing, maybe I should try another one first.. (using compiz currently

**Comment by Paradiesstaub** [comment]
Here a screenshot from the Ubuntu launcher. mpv was started using the terminal: `mpv [video file]`. The strange thing is, that the icon of the .desktop file – when looking at the .desktop file in `/usr/share/applications` – looks proper.

![mpv_icon_screenshot](https://cloud.githubusercontent.com/assets/3438182/6237931/40af65fc-b6f7-11e4-89f4-79e865c3c042.png)

Using `--idle` works as expected and should IMHO be the default. Having a video player – and such a nice on especially – which is only accessible from the command-line is suboptimal. It would make more sense to me, having a 'visible' .desktop file, and when clicked an empty player opened, hinting with a graphic + some text to drag-and-drop a file into it.

**Comment by mc4man** [comment]
Well if you think Ubuntu should use --idle in their .desktop then file a bug with Debian as mpv bugs in Launchpad are an utter  waste of time. 
mpv via the .desktop is also available thru the context menu & or l. click if set as default. A launcher icon is good for DnD based on the Mimetypes= line in the .desktop which is fairly well populated

**Comment by wm4** [comment]
Unknown status -> away with it.
