### ISSUE TITLE
Performance issue with VAAPI

### ISSUE THREAD

**Issue by ArchangeGabriel** [mpv-player/mpv#1596]
Hi there,

I’m facing trouble with mpv performances when using VAAPI, video is very laggy, dunno if there is an easy way to measure fps or profile perfs.

Using software rendering works fine, VLC using VAAPI works fine, and also, using VDPAU with VAAPI works fine (and is detected as it: `[vo/vdpau] VDPAU is most likely emulated via VA-API.`).

Also, trying vdpau with opengl vo doesn’t work, is that normal?

Error:
```
[vo/opengl] Couldn't load hwdec driver 'vdpau'
VO does not support requested hardware decoder.
```
While in man: `vdpau  requires --vo=vdpau or --vo=opengl`

**Comment by wm4** [comment]
How is it with ``--hwdec=vaapi-copy``?

**Comment by ArchangeGabriel** [comment]
It works well, except for a slightly higher CPU usage (~20% instead of ~5% when hwdec is working with vaapi or vdpau and ~60% with software rendering), which I suppose is normal, and probably what `[vaapi] Using GPU readback. This is usually inefficient.` means.

**Comment by wm4** [comment]
So when using ``--hwdec=vaapi``, does the slowness happen both with ``--vo=vaapi`` and ``--vo=opengl``? What's your system? Output of ``vainfo``?

**Comment by ArchangeGabriel** [comment]
With `vo=vaapi`, it’s a bit slow with either `hwdec=vaapi` or `vaapi-copy`. While testing, I’ve just found another weird behavior. If I run with `hwdec=vaapi-copy`, it works fine. Then, if I switch back to `hwdec=vaapi`, it works fine the first time, then become slow again.

Test cases:
1) hw=vaapi-copy, vo=opengl → OK
2) hw=vaapi, vo=opengl → OK
3) hw=vaapi, vo=opengl → Not OK

1) hw=vaapi-copy, vo=opengl → OK
2) hw=vaapi, vo=vaapi → A bit slow
3) hw=vaapi, vo=vaapi → A bit slow
3bis) hw=vaapi, vo=opengl → Not OK

1) hw=vaapi-copy, vo=opengl → OK
2) hw=vaapi-copy, vo=vaapi → A bit slow
3) hw=vaapi, vo=vaapi → A bit slow
3bis) hw=vaapi, vo=opengl → Not OK

1) hw=vaapi-copy, vo=vaapi → A bit slow
2) hw=vaapi, vo=opengl → Not OK

3bis) means either as a replacement of 3) or as 4).

So, it seems using `hwdec=vaapi` works once just after using `hwdec=vaapi-copy` with OpenGL VO for both, and VA-API VO is always quite slow.

Note, I’m not really sure of the difference between “A bit slow” and “Not OK”, I would prefer to have a quantitative way to tell that. Is there one?

I’m running an up-to-date Arch Linux install, on a Dell XPS 9530.

`vainfo`:
```
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.37 (libva 1.5.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 1.5.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
```

**Comment by wm4** [comment]
In that case, I can only blame the drivers.

**Comment by ArchangeGabriel** [comment]
So I should report against intel va?

**Comment by wm4** [comment]
Please do so. Mention that this problem occurs both with ``vaPutSurface`` (used by vo_vaap) and GLX interop (used by vo_opengl).

**Comment by wm4** [comment]
So the soltuino is ``--hwdec=vaapi-copy``, I guess. I doubt Intel gives a shit about _anything_.
