### ISSUE TITLE
Ctrl + F -- Find timecode for subtitle string

### ISSUE THREAD

**Issue by veridiam** [mpv-player/mpv#1601]
It would be really cool to be able to seek to the timecode where a certain string is found in the subtitles, the same way you can ctrl + f find a string in a webpage.

Just thought I'd throw that one up!

**Comment by wm4** [comment]
Well, this is not simple, because there is no GUI, and no way to enter text. So maybe this will never be implemented.

You still can jump between next and previous subtitles with ``ctrl+left`` and ``ctrl+right``, at least with external text subtitles.

**Comment by brayschurman** [comment]
impossible

**Comment by Dudemanguy** [comment]
Old and sounds like a feature for a script.
