### ISSUE TITLE
Dynamic Rate Control 

### ISSUE THREAD

**Issue by maimteve** [mpv-player/mpv#1603]
https://github.com/libretro/RetroArch/wiki/Getting-optimal-vsync-performance
https://github.com/libretro/libretro.github.com/raw/master/documents/ratecontrol.pdf

Does mpv have a feature like this? Would it make sense to implement?

**Comment by wm4** [comment]
Sounds like it attacks a similar problem video players have (syncing video and audio to display and soundcard).

In mpv, we have yet to do the following things:
- syncing with video fps = display fps (mostly works already)
- syncing video fps almost display fps (we should resample audio to get perfect sync)
- syncing video fps being a fraction of display fps, like 23 on 60 fps (mostly works, except can be ruined by timestamp jitter, and it's not perfect in any case)

The main problem is actually just timing frames reliably in OpenGL and in a portable way. I'm sort of stuck with this. I can look at libretro and see what tricks they employ. Thanks for pointing me towards it.

This issue doesn't really have any focus, so I'm closing it.
