### ISSUE TITLE
Option af: rubberband doesn't exist

### ISSUE THREAD

**Issue by Bergfried** [mpv-player/mpv#1606]
Running `mpv --af=rubberband=help` (this line is actually copied from the man page) results in this:

~~~~
Option af: rubberband doesn't exist.
Error parsing option af (option parameter could not be parsed)
Setting commandline option --af=rubberband=help failed.

Exiting... (Fatal error)
~~~~

`rubberband` is installed on my system.

One or two examples in the man page on how to add `rubberband` to the filter list would be nice. Is there (or will there be) a way to control how rubberband reacts to speed changes similar to `scaletempo`'s `speed=<tempo|pitch|both|none>`?

**Comment by wm4** [comment]
This just means it's not compiled in. (It uses an external library called librubberband.) I guess I can add a hint to the manpage.

The results so far were disappointing though. There are also some weird bugs that don't happen with scaletempo.

>Is there (or will there be) a way to control how rubberband reacts to speed changes similar to scaletempo's speed=<tempo|pitch|both|none>?

No. What would it be useful for?

**Comment by Bergfried** [comment]
> No. What would it be useful for?

Maybe I messed things up, sorry. What I wanted to say is that now with rubberband, there are actually two different ways to implement `--audio-pitch-correction=yes`. Maybe something like `--audio-pitch-correction=<scaletempo|rubberband|no>` would be appropriate, with `scaletempo` being the default value.

Thank you for pointing out that rubberband is just not compiled in.

**Comment by wm4** [comment]
Actually, the manpage already mentions that it uses librubberband, which implies that it's an external dependency. So I don't think it needs to be clarified additionally.

**Comment by akhenig** [comment]
I get the same error when trying to use rubberband. I installed librubberband and it still says it does not exist. Is there a flag I need to use when building mpv? Right now I'm installing mpv using homebrew.

**Comment by akhenig** [comment]
I am still unable to use rubberband. Is it possible to build with rubberband when using homebrew?

**Comment by carter-thaxton** [comment]
@akhenig Just use `brew install --with-rubberband`
