### ISSUE TITLE
interlaced scaling?

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1607]
Is the option to scale an interlaced video and still have an interlaced video gone?
My use case was to upscale sd-dvbt recordings to the native resolution of my tv so that it (temporal) deinterlaces them (cpu power is not enough to use yadif in double-frame mode.)

**Comment by wm4** [comment]
libavfilter's vf_scale can do it correctly (with newer ffmpeg, maybe needs ffmpeg git).

**Comment by kokoko3k** [comment]
ok thanks, i'll try it
