### ISSUE TITLE
Frame stuck when seeking near EOF

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#1609]
Sometimes when seeking near the end of a file, the video get stuck on a still image (the last one before the seeking), while the audio keeps going. 
This happened to me few times in the past and became obvious today when, in a mkv file with ordered chapters, I tried to seek near the bound between two chapters, the first one being in a separate file: the video got stuck for 1-2 seconds until the new segment started (again, the audio was playing fine), then the playback proceeded regularly.
Note that this never happened in my tests using exact seeking, but only with the keyframe-limited method.
Detailed log in verbose mode: https://gist.github.com/AirPort/19a296e5a03b32644391#file-gistfile1-txt

What I just described doesn't happen with every file and it may be just due to badly encoded videos, but this is not the very first time I noticed the problem, so I thought it was worth reporting.

**Comment by wm4** [comment]
It's a feature, not a bug. If you seek too far close to the end of the file, video keyframes can be completely missing. Thus it isn't possible to resume video. As a consequence, it plays audio only.

**Comment by AirPort** [comment]
>It's a feature, not a bug. If you seek too far close to the end of the file, video keyframes can be completely missing. Thus it isn't possible to resume video. As a consequence, it plays audio only.

Oh, I see. Makes sense, thank you for the explanation!
