### ISSUE TITLE
Change speed by x0.1

### ISSUE THREAD

**Issue by usingsystem8** [mpv-player/mpv#161]
If I put "]" while playing a movie, the speed will be x1.1. If I continue doing this, it will be x1.10, x1.21, x1.33, x1.46, x1.61, ...
In most of players, user can change speeds by +0.1. This mean the speed will be x1.1, x1.2, x1.3, x1.4, x1.5, ...
Please make us to change by x0.1.
Sorry, my English is difficult to understand.

**Comment by erayerdin** [comment]
If you want to use the solution of @divVerent, in case anyone wonders about where `input.conf` file is, you do not need to edit `/etc/mpv/input.conf` as @usingsystem8 has said, it is a system file.

Edit `$HOME/.config/mpv/input.conf`. You do not need sudo and it is user specific. You can create the file if it does not exist.
