### ISSUE TITLE
No JACK in 0.8.0?

### ISSUE THREAD

**Issue by Brottweiler** [mpv-player/mpv#1613]
Just updated mpv from the Archlinux repos (`0.8.0-2`), and noticed I got this
```
[ao] Audio output jack not found!
[ao] Failed to initialize audio driver 'jack'
Could not open/initialize audio device -> no sound.
```
Because I have `ao=jack` in my config. I ran `mpv --ao=help` and got 
```
Available audio outputs:
  pulse          : PulseAudio audio output
  alsa           : ALSA audio output
  oss            : OSS/ioctl audio output
  null           : Null audio output
  pcm            : RAW PCM/WAVE file writer audio output
```

So I understand that there's no JACK option. I can use `alsa` just fine, but why this? Or does it have to be compiled/build with special JACK support?

**Comment by qmega** [comment]
The official package appears to not be linked against jack anymore. My guess is it was removed by accident, because the portaudio dep was removed and that depended on jack. If you want jack back, you should probably file a bug report with Arch.

**Comment by Brottweiler** [comment]
@qmega thank you, seems like this can be closed them. :smiley:
