### ISSUE TITLE
cdda:// reports no chapters; cdda://1-99 reports exact number of chapters.

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1614]
I was trying to play an Audio CD:
```
Playing: cdda://
 (+) Audio --aid=1 (pcm_s16le)
AO: [alsa] 48000Hz stereo 2ch s16
[cdda] Switched to track 1
```
But when i try to switch to another chapter (track) it says:
```
Chapter: (unavailable)
```
so i tried:
```
# mpv cdda://1-9999 
Playing: cdda://1-9999
[cdda] Switched to track 1
 (+) Audio --aid=1 (pcm_s16le)
AO: [alsa] 48000Hz stereo 2ch s16
A: 00:00:01 / 00:59:09 (0%)
[cdda] Switched to track 2
Chapter: (3) of 15
A: 00:07:42 / 00:59:09 (13%)
[cdda] Switched to track 3
Chapter: (4) of 15
A: 00:11:35 / 00:59:09 (19%)
[cdda] Switched to track 4
Chapter: (4) of 15
(...) A: 00:11:35 / 00:59:09 (19%)
```
...as you can see now it is able to identify the number of tracks on the audio cd.

Note that this does not happens on every audio cd; sometimes mpv identifies the track numbers sometimes it does not.
i tried several combinations of --cdda-paranoia, --cdda-sector-size and  --cdda-skip without success.

mplayer works fine, instead.

**Comment by wm4** [comment]
I don't know, it works fine for me. What mpv version are you using?

**Comment by kokoko3k** [comment]
Well i just found an audio cd with that issue, but other two i tried works well.
I'm using the git from a week ago, anyway.
I could try to rip the audio-cd and stripping copyrighted audio data, it will take a while...

**Comment by wm4** [comment]
Status?

Hint: I don't care about cdda at all; if you want it improved it's up to you. If I know what's wrong I don't mind wasting some time on this.

**Comment by kokoko3k** [comment]
Sorry, i forgot to update the thread.
I wasn't able to rip the data in a way to reproduce the issue.
But the workaround exists, and that's enough to me.
