### ISSUE TITLE
sound problems

### ISSUE THREAD

**Issue by Toutatis2** [mpv-player/mpv#1616]
In linux (slackware64), with pulseaudio and alsa installed :

I have no sound when mpv-0.8.0 is compiled with pulseaudio installed, but pulseaudio is not activated.
Sound comes back if mpv-0.8.0 is compiled with option "--disalble-pulse" (alsa is then used).

mpv-0.7.3 was able to detect that pulseaudio was not activated.

**Comment by haasn** [comment]
Does the issue still happen if you're using ```ao=alsa```?

**Comment by wm4** [comment]
What does "activated" even mean?

**Comment by Toutatis2** [comment]
The issue still happens when I am using ao=alsa, with mpv compiled with pulse enabled. But it is OK when mpv is compiled with  "--disalble-pulse"

pulse "activated" means that the pulseaudio daemon is running.

**Comment by Toutatis2** [comment]
Sorry, "mpv --ao=alsa" always works....

**Comment by wm4** [comment]
I blame a distro installation problem. Even if pulse is not running, it's usually setup in a way that the daemon is started by libpulse. I don't know why mpv is failing in your case, because you provided absolutely no information.
