### ISSUE TITLE
correct/best way to restart the play with new options or "reload" the file?

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1617]
I'm trying to find the best way to apply new options to a running mpv (which is using the --input-file switch) for a gui project i'm developing.
Of course there is the possibility of starting another mpv to the same stream position, that would certainly work, but at the cost of having a black screen for a while and audio interrupted.

Another option i tried is to do:
```
echo "loadfile \"mediafile\" replace start=previoustime,option1=something,option2=somethingelse" >/tmp/input
```
...this one works as long as i don't use complex options like "scale=100:100".
If i do that, i have:
```
[input_file] Unparseable garbage at end of option value: '=100:100'
```
...the same happens by using json syntax.

So the first question is: Is that the intended behaviour, is there another syntax i can use, or is this simply a bug?

My next try was to compile a new profile on the fly (or modify an existing one) and passing it to the running instance:
```
echo "loadfile \"mediafile\" replace start=previoustime,profile=newoptionsprofile" >/tmp/input
```
...but mpv is unaware of it because the first time it was started that profile didn't existed, and if it existed, it is unaware of new content i write in it.

I know there are a lot of options and properties that can be changed runtime 
the manual ad input.rst states:
``` 
options/<name> (RW)
    Read-only access to value of option --<name>. Most options can be changed at runtime by writing to this property. Note that many options require reloading the file for changes to take effect. If there is an equivalent property, prefer setting the property instead.
```
but that would require the gui code to keep track of what property/option is changed and then decide if reloading is needed, so i think it is better, if possible, to blindly "reload" the file with the new option(s)/name 

So the final question is: how to reload the file? does the manual means stop it and start from scratch?
I'm unable to understand it by my own.

thanks.

**Comment by wm4** [comment]
>(which is using the --input-file switch) for a gui project i'm developing.

Don't use this for GUIs.

**Comment by kokoko3k** [comment]
The first thing i tried was to use the shared library, i know it would be the best way, but unfortunately gambas (the rad i'm using) isn't that good in interfacing with external libraries; so by now it is not an option for me.
So, sorry if i ask again; is it intended that when i type:
```
echo "loadfile \"mediafile\" replace vf=scale=100:100" >/tmp/input
```
mpv answers:
```
[input_file] Unparseable garbage at end of option value: '=100:100'
```
Is there some quoting/escaping i can use to make it understand what the input command is about?

**Comment by wm4** [comment]
You need to quote the option value in this case; either way, you could it just set directly as property without "reloading".

(Also just mentioning #1548 for "generic" reloading.)

**Comment by kokoko3k** [comment]
Ok, thanks for your input, i managed to make it work.
