### ISSUE TITLE
Request: apply options/sub-text-* immediately

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1622]
Currently, options/sub-text-* can be set before start playback.
Usually this is fine except one option: sub-text-margin-y.

The document mentions sub-text-margin-y as an alternative for unstyled subtitle only instead of sub-pos which also applied to ASS format.
Adjusting the position of subtitle is quite common demand and change of sub-pos is applied immediately but sub-text-margin-y isn't.

I think it would be useful if sub-text-* options are applied immediately including sub-text-margin-y.

**Comment by wm4** [comment]
Can you check whether above commit helps?

**Comment by xylosper** [comment]
Thank you!
I tested and the result is weird.
I've tried 'options/sub-text-color' and 'options/sub-text-margin-y'.
The former works during playing but latter doesn't work.

**Comment by wm4** [comment]
Did you wait until the current subtitle event disappeared? The libass cache may cause issues.

**Comment by xylosper** [comment]
Yes, also tried to seek and nothing changed.
FYI, sub-text-color was applied immediately during presenting same subtitle.

**Comment by wm4** [comment]
OK, it works only immediately if ``--no-sub-ass`` is specified. Some options, including ``--sub-text-margin-y``, are applied only if the option is set _before_ the subtitle decoder is initialized. Note that switching off subs and then switching them on again is not enough, because the subtitle decoder is actually kept alive.

Not sure yet how to fix this...

**Comment by wm4** [comment]
Made a change. It doesn't change anything for ASS subtitles, because that would overwrite the style stored in the subtitle file.

**Comment by xylosper** [comment]
Confirmed. Now it works. It would be better it was applied in real-time but maybe this is the best result. Thank you!

**Comment by wm4** [comment]
That would require an actual notification mechanism within mpv. Maybe much later, when properties and options overlap better.

**Comment by xylosper** [comment]
Okay. Btw, I have one question.
The document says about `--ass-style-override=force`:

>Try to force the font style as defined by the --sub-text-* options. Requires a modified libass, can break rendering easily. Probably more reliable than force.

What is **modified libass**, here? I've tried in Arch Linux and it just worked with distro-provided libass package. Maybe outdated description?

**Comment by wm4** [comment]
This form of style overriding has been in libass since 0.12.0 or so. It didn't work with older versions. And when the option was added, it wasn't even in any official libass. We require at least 0.12.0 now; I'll fix the wording.
