### ISSUE TITLE
Screen Capture Blocked?

### ISSUE THREAD

**Issue by ArchUser** [mpv-player/mpv#1623]
I want to use livestreamer + openbroadcaster to create highlight clips of streams but MPV is blocking window capture. Is there a way to disable this? I know I can do this with other player but I'd like to use MPV.

**Comment by wm4** [comment]
What is screen/window capture?

**Comment by ArchUser** [comment]
Recording mplayer window with software.

**Comment by wm4** [comment]
So it just reads the screen buffer? Whether this works depends on the VO and the video driver that is used. With some it works, with some it doesn't. It's not really player-specific.

**Comment by wm4** [comment]
I'll guess a bit: you use --vo=vdpau or vaapi or possibly xv; try --vo=opengl.
