### ISSUE TITLE
osd-align-x=center affects osd-bar in a strange way

### ISSUE THREAD

**Issue by Divetoxx** [mpv-player/mpv#1626]
If using new parameter osd-align-x=center the osd-bar goes left of the screen and cuts.
![2015-02-24_142820](https://cloud.githubusercontent.com/assets/1689751/6348542/a619bf98-bc31-11e4-895c-d57138e9de18.jpg)
![2015-02-24_142923](https://cloud.githubusercontent.com/assets/1689751/6348544/ab3725ce-bc31-11e4-8e2c-b43a8e14c674.jpg)
osd-bar-align-x=0 doesn't help!

**Comment by wm4** [comment]
Yes, recent regression.
