### ISSUE TITLE
Windows/opengl - resize only updates the content size after the mouse stops moving

### ISSUE THREAD

**Issue by avih** [mpv-player/mpv#1627]
While dragging the window border to resize it, the video content only resizes when the mouse stops moving (even if the LMB is still held down). The video keeps playing smoothly also when the video size doesn't match the window size.

This doesn't happen with d3d output.

It seems the offending revision is 210c83ab31dd69c7a47c4b89d3a5fce78d4bedf2 .

The previous revision ( afcbee8305e1d5c99012a6b9880b43b27b2d411a ) doesn't have this issue - the content resizes together with the window size even while the mouse moves continuously.

The offending revision ( 210c83ab31dd69c7a47c4b89d3a5fce78d4bedf2 ) doesn't build out of the box, but it does after applying the build fix from 2 revisions later - and then it indeed updates the content size during window resize only after the mouse stops moving.

**Comment by wm4** [comment]
I would have preferred the way things were done before the commit as well, but unfortunately it was a bug fix.

**Comment by avih** [comment]
I read the commit comment and noticed that it's about fixing an Intel issue (which I also use by default for mpv).

So I went ahead and tried this same revision with the AMD discrete GPU which I also have (8850m in Enduro configuration (AMD's "optimus")). And the problem goes away - the content resizes smoothly even while the mouse keep moving.

So is it an Intel driver issue?

**Comment by wm4** [comment]
>So is it an Intel driver issue?

Didn't some report a problem with nvidia too? Anyway, it's not clear how to do this correctly, but the current state seems to work everywhere.
