### ISSUE TITLE
--ass-force-style change behaviour

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1628]
I just noticed (and saw some relevant commits lately) that the behaviour of --ass-force-style is somehow changed.
maybe this one? 
https://github.com/mpv-player/mpv/commit/b629da9a40673ccd67bf7661cfdd10c8f79f6eaa

A couple of days ago, the following produced red subtitles.
```
mpv mediafile --sub-file=srtsub.srt --ass-force-style=PrimaryColour=H000000FF
```
now the same command gives me white subtitles and using sub-* options is needed instead.

Is it intended?

Thanks.

**Comment by wm4** [comment]
I'd say: yes, why not.

**Comment by kokoko3k** [comment]
Well, i don't really care myself; i just asked to know what the new logic will be so that i can adapt my mpv frontend.
But if i'd find a reason why not applying ass styles to non ass subtitles anymore would be a bad thing, first thing comes to mind is that probably there are various ass attributes not mirrored by sub-* options; so that new way of handling ass-force-style would lead to a loss of functionalities.

**Comment by wm4** [comment]
>first thing comes to mind is that probably there are various ass attributes not mirrored by sub-* options; so that new way of handling ass-force-style would lead to a loss of functionalities.

Like what?

**Comment by kokoko3k** [comment]
i'm really not that in, so the following may be more or less wrong, but here i read some attributes that probably are missing:
http://pythonhosted.org/pysubs2/api-reference.html

angle = None
    Rotation (ASS only)
borderstyle = None 
    Border style
marginl = None
    Left margin (in pixels)
marginr = None
    Right margin (in pixels)
marginv = None
    Vertical margin (in pixels)
scalex = None
    Horizontal scaling (ASS only)
scaley = None
    Vertical scaling (ASS only)
tertiarycolor = None
    Tertiary color (pysubs2.Color instance)

**Comment by wm4** [comment]
All of these, except angle, and maybe non-1:1 scaling, can be configured.

Moreover, --ass-force-style can ruin .ass subs.
