### ISSUE TITLE
OSD (position on screen) & OSC (increaseing font size)

### ISSUE THREAD

**Issue by midna-luis** [mpv-player/mpv#1631]
Any guidance on how to do the following? (thank you)
1) Make OSD & osd-playing-msg appear on top left corner of screen?
   The latest upgrade (0.8.1) makes them both appear on the bottom
   left of screen (thus, obscuring the subtitles).
2) Make OSC (on-screen-controller) font size appear much larger?

### ~/.config/mpv/mpv.conf
fullscreen=yes          #start mpv fullscreen, 720p
osd-playing-msg='${filename}'    #display filename when video loads
osd-color='#00CED1'     #Dark Turquoise
osd-duration=2000       #default 1000
no-osd-bar 

Again, thank you

**Comment by wm4** [comment]
>The latest upgrade (0.8.1) makes them both appear on the bottom
left of screen (thus, obscuring the subtitles).

This definitely shouldn't happen.

**Comment by wm4** [comment]
0.8.1 is broken. It misplaces the OSD. CC @Kovensky

**Comment by wm4** [comment]
It's ff10bd65d68883d51cad9db5066f5e0baf74be30. It removes code which was redundant in git master, but still is important with 0.8.0 as base.

**Comment by wm4** [comment]
>The latest upgrade (0.8.1) makes them both appear on the bottom
left of screen (thus, obscuring the subtitles).

This is now fixed on 0.8.2.

**Comment by midna-luis** [comment]
wm4: Thank you for taking care of so quickly. 
Cheers
