### ISSUE TITLE
Setting pulse sink doesn't work

### ISSUE THREAD

**Issue by yurivict** [mpv-player/mpv#1632]
Setting the option "-ao pulse::oss_output.dsp4" or "-ao pulse::4" is supposed to play on sink number 4, but sound still goes to sink 0.

Additionally, for some reason, 'pacmd set-default-sink 4' also doesn't affect mpv, and it always plays to sink 0.

'cat /dev/urandom | pacat -d oss_output.dsp4' does play to sink 4

Man page talks about [\<host>][:\<output sink>] for -ao pulse. It should clarify what \<output sink> means (name or id).

**Comment by wm4** [comment]
This option is simply passed to the ``dev`` parameter of this pulseaudio API function: http://freedesktop.org/software/pulseaudio/doxygen/stream_8h.html#ab9544f6677af133fbe81bf8a21eb489c

I don't know what exactly it means either.

**Comment by yurivict** [comment]
Curiously, changing sink name causes failure to initialize pulse device, but correct sink name doesn't change sink properly.

**Comment by wm4** [comment]
I can look what pacat does... tomorrow.

**Comment by wm4** [comment]
pacat does the same as mpv. It passes the sink argument to the API function I mentioned.

So I don't know why you'd get the behavior you see.

**Comment by faminebadger** [comment]
I can confirm the same behaviour:
```
$ pacmd list-sinks |egrep '(index|name):'
   index: 0
       name: <alsa_output.pci-0000_01_00.1.hdmi-surround71>
 * index: 3
       name: <alsa_output.pci-0000_08_04.0.analog-stereo>
```
So, launching mpv:
```
$ mpv -ao=pulse::alsa_output.pci-0000_08_04.0.analog-stereo test.mkv
...
cplayer: AO: [pulse] 48000Hz stereo 2ch float
```
Audio from PC speakers (correct)
```
$ mpv -ao=pulse::made_up_name test.mkv
...
        ao: Failed to initialize audio driver 'pulse'
   cplayer: Could not open/initialize audio device -> no sound.
```
No audio at all (correct)
```
$ mpv -ao=pulse::alsa_output.pci-0000_01_00.1.hdmi-surround71 test/mkv
...
cplayer: AO: [pulse] 48000Hz stereo 2ch float
```
Audio plays from PC speakers (incorrect - this should be to the amplifier's surround speakers)

Exactly the same behaviour results from using indices (0/3) instead of names. 0 & 3 both result in PC speakers, anything else fails to open.

Launching pavucontrol clearly shows that in both the first and last cases, the Xonarr soundcard is the active device, and I can move the stream to the radeon's output using pavucontrol and that works.

But it should have gone there in the first place?

**Comment by faminebadger** [comment]
> pacat does the same as mpv. It passes the sink argument to the API function I mentioned.

Just to follow up on this, I did the same experiment with pacat.

```
$ pacat -d alsa_output.pci-0000_08_04.0.analog-stereo /usr/share/sounds/alsa/Front_Left.wav
```
Sound from PC speakers (correct)
```
$ pacat -d alsa_output.pci-0000_08_04.0.analog-stereod /usr/share/sounds/alsa/Front_Left.wav
Stream error: No such entity
```
No sound (correct)
```
$ pacat -d alsa_output.pci-0000_01_00.1.hdmi-surround71 /usr/share/sounds/alsa/Front_Left.wav
```
Sound from amplifier surround speakers (correct).

So actually, it appears you're doing something different to pacat after all.

**Comment by wm4** [comment]
>So actually, it appears you're doing something different to pacat after all.

But what? This could as well be opaque PulseAudio magic, of which there is a lot.
