### ISSUE TITLE
OSC doesn't show up

### ISSUE THREAD

**Issue by nerdouille** [mpv-player/mpv#1633]
Hi, I just built latest git version (0.8.2-git-7fe9126) on debian stable using some isntructions found here https://nyxi.eu/blog/2014/01/19/compiling-mpv-in-Wheezy-2014/  and I can't see the OSC when I move the mouse, any ideas?

**Comment by wm4** [comment]
Compile with Lua enabled.

**Comment by wm4** [comment]
PS: which means you probably want to add liblua5.2-dev to the command line.

**Comment by nerdouille** [comment]
Ok thanks it works

**Comment by kevmitch** [comment]
If you're using mpv-build and are on debian, you should probably build the [debian package](https://github.com/mpv-player/mpv-build#installing-dependencies-on-debian-or-ubuntu) to ensure that things like this "just work".
