### ISSUE TITLE
OpenGL Gamma Gone Dark

### ISSUE THREAD

**Issue by dtl131** [mpv-player/mpv#1636]
https://github.com/mpv-player/mpv/commit/fbacd5de31de964f7cd562304ab1c9b4a0d76015
After the recent commit dealing with gamma, my opengl output is extremely dark and I have to turn the gamma up to 30 to get a decent picture. Using -vo vdpau is still okay.

Also, I believe there's a typo in the commit (a missing '=') at line 612 of mp_image.c
if (params->gamma = MP_CSP_TRC_AUTO)
Note: Adding the '=' and rebuilding didn't fix the issue.

I'm using Debian sid amd64, 8400GS with nouveau driver, ffmpeg 2.5.4.
If you need other details, let me know.
Thanks

**Comment by wm4** [comment]
Which vo_opengl options?

**Comment by dtl131** [comment]
I wasn't using any special paramters. Now I've tried opengl-hq and that has a reasonable appearance at default gamma. I guess I will just use opengl-hq (as I probably should be doing anyway according to manual).

**Comment by wm4** [comment]
Ah, you're right, now I get it too.

**Comment by haasn** [comment]
Culprit was an omitted check for use_linear_light in gl_video.c, which was buried by the recent refactoring of gamma. It only broke the case where linear light was *not* enabled, which I forgot to test.

Thanks for catching the single = issue (though it was unrelated here and of little importance), I can't believe I didn't get a compiler warning for that.
