### ISSUE TITLE
RTP streams don't play properly

### ISSUE THREAD

**Issue by hugo19941994** [mpv-player/mpv#1637]
If I watch an RTP stream the video has a lot of artifacts. Sound is mostly ok, but is a bit choppy at times. Happens at least in Arch and Windows 8.1

This **doesn't** happen on other players.

Console output in Windows:
```
AV: 00:00:08 A-V:  0.000 Dropped: 0/40 Cache:  0s+2KB
[ffmpeg/video] h264: Reference 8 >= 2
[ffmpeg/video] h264: error while decoding MB 2 28, bytestream 23544
AV: 00:00:08 A-V:  0.000 Dropped: 0/40 Cache:  0s+2KB
[ffmpeg/demuxer] mpegts: PES packet size mismatch
AV: 00:00:08 A-V:  0.000 Dropped: 0/40 Cache:  0s+2KB
[ffmpeg/video] h264: cabac decode of qscale diff failed at 89 37
[ffmpeg/video] h264: error while decoding MB 89 36, bytestream 84350
AV: 00:00:08 A-V:  0.000 Dropped: 0/40 Cache:  0s+2KB
[ffmpeg/audio] mp2: Header missing
Error decoding audio.
AV: 00:00:08 A-V:  0.042 ct:  0.054 Dropped: 0/40 Cache:  0s+2KB
[ffmpeg/video] h264: Reference 2 >= 2
[ffmpeg/video] h264: error while decoding MB 92 30, bytestream 56042
```
Screenshot on Windows
![capture](https://cloud.githubusercontent.com/assets/6431131/6427651/f4e3d5b6-bf86-11e4-9a6f-7ba70a800ea3.PNG)

**Comment by wm4** [comment]
Any sample URL?

The is most likely libavformat dropping packets or so.

**Comment by hugo19941994** [comment]
Hmm. This is an IPTV HD stream inside my LAN so no URL unfortunately. I can only find [this rtsp stream which works fine in mpv](http://www.wowza.com/html/mobile.html) (maybe because the bitrate is low)
I'll try to find another source.

**Comment by wm4** [comment]
Any way to reproduce the issue is welcome. Can't do much as it is.

**Comment by wm4** [comment]
In addition to the cause being unknown, this is most likely a ffmpeg issue.
