### ISSUE TITLE
Compiled .app bundles for Mac from /releases/

### ISSUE THREAD

**Issue by Naio** [mpv-player/mpv#1641]
Can we continue to get compiled .app bundles for Mac from /releases/ like in the past for those that do not have the knowledge to compile themselves?

Thank you in advance,
Naio

P.S. I know this is not really an "issue", but I didn't know where else to bring this up, sorry.

**Comment by Argon-** [comment]
Afaik these release builds were/are compiled by ChrisK3, you can still get them here: http://sva.wakku.to/~chris/mpv_builds/

**Comment by pigoz** [comment]
cc @ChrisK2

**Comment by ChrisK2** [comment]
Yeah, I'll add them once I remember and have time to.

**Comment by Naio** [comment]
Alright, thanks!
