### ISSUE TITLE
Question: Can I Disable Streaming Support At Compile Time?

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#1642]
Hi,

I only want mpv for local video play back, no online streaming.

Can I disable streaming at compile time, does mpv have a --disable-option for it?

I noticed a streaming cache that appears in the OSD, is this for online streaming? If so I'd like to be able to disable this at compile time. For now I placed in my config; ```cache=no```, but I'd like it removed form the build if possible....

Is ```./old-configure --help``` all the current mpv compile options?

thanks

**Comment by meuwe** [comment]
Please I want to know also.

thank you

**Comment by wm4** [comment]
No.

**Comment by kevmitch** [comment]
mpv will always handle direct http urls to a media file (e.g., http://xxxx.mkv) urls because this is built into ffmpeg I believe. There is no way to disable it in either package. Trying to disable this would be like trying to disable handling regular files.

If you don't --enable-gnutls/--enable-openssl in ffmpeg, then congratulations, you have disabled https:// support.

Finally if you don't have youtube-dl installed (or your version is too old), mpv will not be able to convert youtube page urls into direct links to the video file.

**Comment by meuwe** [comment]
Hello,

I did not enable --enable-gnutls/--enable-openssl in ffmpeg, then why do I have, from what I understand is a Stream Cache that appears in the OSD? ```Cache 2s + 24MB```

**Comment by kevmitch** [comment]
The stream cache stores the current section of the playing file in memory. It works independent of whether that file is on the local disk or being remotely accessed by (for example http://).
It controlled by the --cache command line option which takes the arguments "no", "auto" or a number representing the desired size in kilobytes. --cache=no will disable it completely.

--cache=auto is the default. In this mode, mpv uses some heursitics to determine whether the source file is local or from the network. If it is local, no cache is used. 

If you are seeing a cache, then you either specified a cache size like --cache=1024 or mpv thinks the file you're playing is from the network. I think this includes being accessed by nfs or cifs, etc.

**Comment by meuwe** [comment]
I did not specify a cache, I have videos associated with my file manager, so all I do is just click a video and mpv opens and plays. I also don't have anything in the mpv config for a cache.

So when opening a file as I mentioned and playing it off my hard drive, then the OSD should not be displaying this cache information?

**Comment by kevmitch** [comment]
No, there should not be cache for local files by default. Testing here with git-53867aa from 2015-02-23, I see that with --no-config it enables cache for a file on smbnetfs, and it correctly does not enable cache (i see no cache info on OSD) for a file on my local disc. What version of mpv are you using? What type of file system is the file you're playing stored on? Do you see the same behaviour if you run mpv on the command line with the --no-config parameter?

Also double check the existence/contents of 
~/.mpv/mpv.conv
~/.mpv/config
~/.config/mpv/mpv.conf
~/.config/mpv/config

**Comment by meuwe** [comment]
I play movies off of ext4 in Linux on my box, and ntfs and fat32 off of usb portable drives/sticks.

Ok I'm not seeing this if run a movie on my hard drive with ext4, and I don't see it with fat32 on my usb flash stick. I just realized I am only seeing this cache with NTFS on my portable usb hard drives.

Hmm why NTFS?

**Comment by rossy** [comment]
Well, ntfs-3g is a FUSE filesystem. check_stream_network() in stream_file.c looks like it marks every FUSE filesystem as a network one, so that could explain it.

**Comment by qmega** [comment]
Cache is indeed auto-enabled for ntfs-3g. I don't think there's a whole lot we can do about that without FUSE-specific code and a whitelist of subtypes (correct me if I'm wrong) which seems like it could get pretty dirty. Enabling cache on FUSE still seems like the right call to me, if we have to pick all or nothing, because you'd definitely want it on things like sshfs.

@meuwe If you're never going to use mpv for remote files and just want the cache disabled, what's wrong with just putting `cache=no` in your config file?

**Comment by meuwe** [comment]
Yes I have ```cache=no``` in the config, not a big deal.

I was only trying to figure out why this was happening locally.

**Comment by haasn** [comment]
And what, exactly, is wrong with having a cache?

**Comment by wm4** [comment]
>And what, exactly, is wrong with having a cache?

Maybe saving 14KB of binary code?

**Comment by meuwe** [comment]
What is the cache even for? I thought this only had to do with Streaming media?

**Comment by wm4** [comment]
It's useful in any situation the source media is very slow and has huge latency spikes.

**Comment by meuwe** [comment]
I've been looking around trying to read what it does, anywhere I can read about it?

thanks

**Comment by kevmitch** [comment]
As I explained above, the cache stores part of what is playing in memory for fastest access. This is useful if the original data source source (disk, network, etc) can have large delays (latency spikes referred to by wm4 above) or if reading in large batches significantly improves performance.

The [man page](http://mpv.io/manual/master/#cache) does a pretty good job of explaining it as well as how to fine tune it.

**Comment by meuwe** [comment]
Sorry I forgot, overlooked what you mentioned before.

Ok I'm assuming from what you've said that I should use in the config for the defaults as; ```cache=auto```

NTFS locally still uses cache, maybe this is something to change in the future.

thanks
