### ISSUE TITLE
Right click issue

### ISSUE THREAD

**Issue by Cephel** [mpv-player/mpv#1644]
Right clicking then dragging the mouse off the window and releasing the right mouse button will resume / pause the video, despite the mouse not being in focus anymore. This is inconsistent with most other GUI elements, where clicking on them, then dragging the mouse off them and releasing the mouse button will _not_ activate the element.

**Comment by wm4** [comment]
By "GUI" you mean the OSC? That's different code.

We're not checking the mouse position when dispatching normal key binds.

A minor inconsistency I can certainly live with.

**Comment by haasn** [comment]
I think he means that other GUI elements like buttons inside Gtk windows will ignore clicks if you drag the mouse off the window before releasing, not the OSC in particular.

**Comment by Cephel** [comment]
No, anywhere inside the video window, not on the OSC
