### ISSUE TITLE
smoothmotion + hwdec=vdpau

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1645]
Using vdpau api + opengl with smoothmotion leads to video stuttering on my hardware (tested with a 9800GT and a GTX750ti).
The same configuration without smoothmotion is actually smoother.

So i wonder if opengl:smoothmotion is supposed to work with vdpau decoding.
If not, maybe mpv needs some logic to disable smoothmotion when hwdecoding is used (?)

**Comment by wm4** [comment]
Works fine here. Your hw is probably too slow.

**Comment by haasn** [comment]
Smoothmotion has tighter hardware requirements than non-smoothmotion.

If it takes your setup 30ms to decode a single frame, then it would be fine without smoothmotion (1s/24Hz = 41 ms) but it wouldn't be fine with smoothmotion (1s/60 Hz = 16ms) because the timing requirement on rendering a frame is now one vsync, rather than one movie frame.

This is an implementation issue, not a fundamental issue. I'm waiting for the gl_rework redesign before fixing it properly.

**Comment by kokoko3k** [comment]
I'm not sure it depends on hardware speed, i might be wrong.
Both of my Hw setups performs the same, and now I just did a test with compositing disabled on the 9800GT which is about 1/4 the speed of my other system (gtx750ti)

* Cpu: Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz
* Gpu: 9800GT

Test #1: smoothmotion without hardware decoding:
```
mpv http://wpage.unina.it/aorefice/sharevari/tearingandsmoothness.mp4  --hwdec=no --vo=opengl:smoothmotion
```
* Video is butter smooth
* cpu use: ~20%
* gpu use: ~6%
* Video engine utilization: 0%

Test #2: smoothmotion with hardware decoding:
```
mpv http://wpage.unina.it/aorefice/sharevari/tearingandsmoothness.mp4 --hwdec=vdpau --vo=opengl:smoothmotion
```
* Video is butter smooth
* cpu use: ~6%
* gpu use: ~6%
* Video engine utilization: 14%


Test #2: No smoothmotion with hardware decoding:
```
mpv http://wpage.unina.it/aorefice/sharevari/tearingandsmoothness.mp4 --hwdec=vdpau --vo=opengl
```
* Video is less smooth than 1 but smoother than 2
* cpu use: ~4%
* gpu use: ~4%
* Video Engine Utilization: 14%

...the average load is low in all of the tests on the cpu and the gpu

**Comment by kokoko3k** [comment]
I'm not even able to spot blended frames when i use vdpau + smoothmotion.

**Comment by haasn** [comment]
There might be other issues. The current smoothmotion code is rather finnicky and depends on frames arriving within a certain timeframe (between the last blended frame and the next blended frame), if frames arrived sooner or later than that, it breaks down.

I also want to fix this, ideally after the gl rework.

**Comment by kokoko3k** [comment]
Some other infos:
i managed to test another system, it is an i3-3110M with an intel HD4000 on board.
While it confirmed my old findings (vdpau+opengl:smoothmotion not working),
i managed to try vaapi-copy+opengl and there smoothmotion worked, while it failed on vaapi+opengl

**Comment by kokoko3k** [comment]
Just tried the latest git: 0.8.2_309_g0c9c047
and it seems that the issue is gone; vdpau+opengl works really well and the cpu use is more or less the same as for vdpau+vdpau.
Great work, thanks!
