### ISSUE TITLE
waf can't find libass when I have it installed

### ISSUE THREAD

**Issue by ainstushar** [mpv-player/mpv#1649]
Hi devs,

I have been installing and updating my mpv using brew for a while. I get the latest changes by using ``--HEAD`` option in brew. Recently when I tried updating mpv, I got this error message:

````
Checking for SSA/ASS support : no ('libass >= 0.12.1' not found) 
Unable to find development files for libass, or the version found is too old. Aborting. If you really mean to compile without libass support use --disable-libass.
````

I have libass 0.12.1 installed. Running ``brew list libass`` reports:

````
/usr/local/Cellar/libass/0.12.1/include/ass/ (2 files)
/usr/local/Cellar/libass/0.12.1/lib/libass.5.dylib
/usr/local/Cellar/libass/0.12.1/lib/pkgconfig/libass.pc
/usr/local/Cellar/libass/0.12.1/lib/ (2 other files)
````

Running ``pkg-config --libs libass`` outputs:
````
-L/usr/local/Cellar/libass/0.12.1/lib -lass 
````

Am I missing something? I've made sure to update my brew formula list so it should be updated with latest changes.

Thanks for help.

**Comment by torque** [comment]
If you look at the mpv provided homebrew formula, it uses its own `libass-ct` by default. You need to `brew uninstall mpv-player/mpv/libass-ct` and `brew install --HEAD mpv-player/mpv/libass-ct` to update it because of how poorly homebrew handles HEAD builds (refuses to update them, etc).

The other option is to use the `--with-official-libass` flag when installing mpv from homebrew, but `libass-ct` offers some advantages over official libass to the casual user.

**Comment by ainstushar** [comment]
Thanks for your help. Completely forgot about updating the built in libass-ct.

Also, on a side note, do I need to update any other libraries built in with mpv? My current install line looks something like this: ``brew install --HEAD --with-bundle --with-libquvi --with-little-cms2 --with-lua --with-libbluray --with-libdvdread --with-official-libass --verbose mpv``.

**Comment by torque** [comment]
libquvi isn't used any more. It was removed in favor of youtube-dl integration. Other than that, if you're updating mpv, you may want to update ffmpeg as well.

**Comment by ainstushar** [comment]
All right. Thanks.

On Thu, Mar 5, 2015 at 1:44 AM, Upstanding Citizen <notifications@github.com
