### ISSUE TITLE
Go full screen while keeping the video aspect unchanged.

### ISSUE THREAD

**Issue by VeralianIV** [mpv-player/mpv#1650]
Is there an input/hotkey that toggle fullscreen while keeping the original aspect ratio of the video?

**Comment by wm4** [comment]
Not sure what you mean. By default, mpv always keeps the aspect ratio of the video. Which means it won't be "stretched".

**Comment by VeralianIV** [comment]
My screen resolution is a bit higher than 720p,what I want is to go fullscreen without stretching the video to the borders of my screen.and have the video surrounded by black bars.Basically I want this 
![bandicam 2015-03-06 00-00-46-589](https://cloud.githubusercontent.com/assets/11322226/6516637/fea603b2-c369-11e4-9655-c3f2c0b41c7c.png)

**Comment by wm4** [comment]
So you don't like that the video is scaled a bit to fill the screen? You can probably use ``--video-unscaled``.

**Comment by VeralianIV** [comment]
I checked the manual and found that but couldn't figure out how to use it(sorry being ignorant).

**Comment by VeralianIV** [comment]
Thanks for the help,I got it to work.
