### ISSUE TITLE
ssa subtitles not rendered - Bad timestamp

### ISSUE THREAD

**Issue by YogSottot** [mpv-player/mpv#1654]
External subtitles in "SSA"-format. When try to play, get error "Bad timestamp" and subtitles not rendered. VLC can handle this sub.

```
[libass] Bad timestamp
[libass] Bad timestamp
[sub] Subtitle filter chain: ass (ass)
[global] search dirs: /home/user/.config/mpv /home/user/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/user/.config/mpv /home/user/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[libass] Setting up fonts...
[libass] Done.
[libass] EOF reached.
[cplayer] Starting playback...
```
mpv 0.8.2, ffmpeg 2.5.4, libass 0.12.1

Example of subtitles: https://app.box.com/s/5ukh0v9vvx2xyf4vlojqohi6o5p1vdz3
Log http://pastebin.com/rLw3q8SA

**Comment by wm4** [comment]
Seems to work with ``--sub-demuxer=subreader``.

That it doesn't work with defaults is either a libass bug, or a broken file, or both. Not sure yet.

**Comment by wm4** [comment]
OK, it was both. Normally, the timestamp starts with a single ``0``, and this subtitles has two ``0``, which confused libass. But all other parsers are fine with it, so I changed it in libass git master.
