### ISSUE TITLE
Fallback screenshot directory.

### ISSUE THREAD

**Issue by 0xACE** [mpv-player/mpv#1658]
Hello.

I noticed today that when I ran mpv in a folder where I don't have WRITE access it would result in printing:

    Error opening 'shot00001.jpg' for writing!
    Error writing screenshot!

It would be nice to have the ability to set some fallback location for the screenshots.

Personally this doesn't bother me much, but I figured it's worth reporting.

To produce this problem on your pc (linux), you could try:

    cd / && mpv http://www.youtube.com/watch?v=dQw4w9WgXcQ

After that try to take a screenshot and you should get the same error

Cheers!

**Comment by wm4** [comment]
You can change the screenshot directory as a side-effect of ``--screenshot-template``. So if you want screenshots somewhere else, you can just set this option.

**Comment by 0xACE** [comment]
@wm4 
Yes, previously; I've only edited the filename, but I suppose you're right.

Personally I'll keep it so that screenshots end up in mpv's working directory...

Feel free to deal with this issue as you see fit. I just reported it just in case...

**Comment by wm4** [comment]
Idea rejected for now.
