### ISSUE TITLE
mpv doesnt respect icon setting

### ISSUE THREAD

**Issue by Fixles** [mpv-player/mpv#1662]
Hello,

I've been unable to make mpv use a different icon. I've tried modifying the .desktop file and overwritten 3 icons in hicolor icon theme. Still I have the default circle icon in lxpanel?

Running Debian 8. lxpanel 0.7.2

mpv 0.6.2 (C) 2000-2014 mpv/MPlayer/mplayer2 projects
 built on 2014-10-25T13:21:01
libav library versions:
   libavutil       54.3.0
   libavcodec      56.1.0
   libavformat     56.1.0
   libswscale      3.0.0
   libavfilter     5.0.0
   libavresample   2.1.0

Thanks.

**Comment by barajasr** [comment]
Digging through old tickets, I found this https://github.com/mpv-player/mpv/issues/1546. The advice offered was to change icon(s) before compiling; found under mpv/etc/.

**Comment by wm4** [comment]
The window icon is usually provided by the application itself, i.e. each program has to set the icon itself in C code. Correct me if I'm wrong.

**Comment by nagisa** [comment]
> each program has to set the icon itself in C code

This is the case, yes. However some DEs, such as GNOME, check window attributes (I think WM_CLASS, can’t say off the top of my head) to associate the window with a `.desktop` file, in which case it will use the icon defined in `.desktop`. Not sure about `lxpanel` and there’s most likely nothing that can be done about it.
