### ISSUE TITLE
Video remains fullscreen on forced minimize (Windows)

### ISSUE THREAD

**Issue by flriancu** [mpv-player/mpv#1663]
When mpv is in fullscreen mode and I hit Win+M (minimize all), the video remains fullscreen and keeps playing. Since all the windows (including mpv) are now minimized, the player stops responding to controls (since it's not in focus).

If I use Alt+Tab and happen to restore mpv (or press Space and bring the taskbar into view and then click mpv, on Windows 7), I can exit fullscreen or pause etc. and everything returns to functioning properly.

Cheers!
P.S. On a side note, is there a boss key? Would it work to define one in input.conf?

**Comment by wm4** [comment]
Not sure if I understand the bug description. I think not.

> P.S. On a side note, is there a boss key? Would it work to define one in input.conf?

``q``

**Comment by avih** [comment]
I can reproduce the case where borderless mpv doesn't respect minimize-all on my system. I'm guessing the full-screen mode is yet another case of borderless window and therefore is disrespectful for the same reason.

**Comment by flriancu** [comment]
Sorry for replying so late. Just to clarify, the basic steps for reproducing this bug are, for me, putting mpv in fullscreen mode and hitting Win+M.

What I mean is that the video feed somehow remains "hooked" to the display and keeps rendering on the screen. As mpv's window is now minimized, it's only natural that the video will no longer react to keys or mouse controls, and in order to fix it, you have to keep Alt+Tabbing until you make mpv the active window.

**Comment by wm4** [comment]
Happens with other OpenGL applications too. And in all cases only in fullscreen mode. Must be a Windows bug. Unless someone suggests a working workaround, I'll close as wontfix.
