### ISSUE TITLE
Remove margin for ASS subtitle

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1664]
![image](https://cloud.githubusercontent.com/assets/4363181/6544511/f3231f28-c596-11e4-86e9-14f5866601a2.png)

As you can see, the ASS subtitle is located with some bottom margin with `--sub-pos=0`.
This margin still exists even with `--sub-text-margin-y=0 --ass-force-style=force`.
Is it possible to remove margin around ASS subtitle?

**Comment by wm4** [comment]
> Is it possible to remove margin around ASS subtitle?

No, the margin is kept as stored in the subtitle file.

**Comment by xylosper** [comment]
It doesn't disappear even with `--sub-text-margin-y=0 --ass-force-style=force`.
Does this mean that this limitation comes from libass?

**Comment by wm4** [comment]
libass git added more fine grained control of overriding, but I haven't enabled overriding margin because it might destroy some subtitles.

**Comment by xylosper** [comment]
Thank you for clarifying.

**Comment by wm4** [comment]
In general, all overrides can break something, so it might possibly be a good idea to add more fine grained control over it. On the other hand, you don't improve usability by adding dozens of options... so I'm not sure how this should end.

**Comment by xylosper** [comment]
I just don't want users to use ass subs if they want to customize style because, obviously, ass subs are not supposed to be customized...
