### ISSUE TITLE
un-wid on fullscreen

### ISSUE THREAD

**Issue by haarp** [mpv-player/mpv#1671]
The most common use-case for the --wid option is probably to embed mpv into applications, such as webpages (i.e. using mozplugger). The biggest penalty for doing this is that fullscreen breaks - the page only provides a fixed size for mpv. Fullscreening mpv does nothing.

Would it be possible to un-attach mpv from a given wid when fullscreen is enabled (and re-attach when fullscreen is disabled)? This would give the best of both worlds - using mpv as the browser video player and still allow fullscreen.

Thanks :)

**Comment by wm4** [comment]
Fullscreening must be handled by the window manager, which would mean that the window must suddenly be known to the window manager. Probably not simple.

**Comment by wm4** [comment]
The complexity of this would be a bit too high. With all this fucked up X11 stuff (race conditions when reparenting and fullscreening in succession etc.) we probably couldn't hope to get this working well either. Rejected for now.
