### ISSUE TITLE
LUA OSD disappears on click

### ISSUE THREAD

**Issue by haarp** [mpv-player/mpv#1672]
The LUA GUI seems to disappear once a left-click is registered. This hurts the usability. Try using the seek buttons - you constantly have to keep jiggling the mouse to keep the buttons visible.

Wouldn't it make more sense to keep the OSD up until the cursor moves out of it (or stays still for a few seconds)?

**Comment by wm4** [comment]
This is probably because X sends a mouse leave event to the window. Your window manager is probably broken. Or maybe you're embedding in a foreign application using a gross hack that barely works? (mozplugger stuff.)

**Comment by haarp** [comment]
Oooh, indeed. This indeed only seems to happen inside mozplugger. mpv is innocent then.

**Comment by wm4** [comment]
I wonder if this could be hack-fixed. How does mozplugger embed mpv?

**Comment by haarp** [comment]
There are two ways.

One is by using the --wid option with the $window variable. From the manpage:
$window - This is the X window Mozilla has given the plugin. This can be used with applications such as MPlayer to display graphics inside the mozilla window.

The other just "swallows" the mpv window:
This  flag  tells  mozplugger that the command will open a window with the specified name and that Mozplugger will then move this window inside your browser.

--wid is the most commonly used method, but both exhibit this bug.

**Comment by haarp** [comment]
I can confirm that it's fixed. Thanks! You guys are awesome!
