### ISSUE TITLE
ebml_types.h is random and prevents reproducible builds

### ISSUE THREAD

**Issue by Nikoli** [mpv-player/mpv#1673]
Compared build dirs of mpv-0.8.2 with ```rsync -navc``` and found that ```ebml_types.h``` is different during every build. This file is include into ```demux/demux_mkv.c.13.o``` and ```demux/ebml.c.13.o```, so they are reproducible too. commit 6dd97ccf5c89db1be2312ffee3d81f74afb6d80a tells about sorting, but it actually does not work now.

I use perl-5.18.2.

**Comment by wm4** [comment]
This is because perl randomizes hash tables.

**Comment by Nikoli** [comment]
Now build is reproducible again.
