### ISSUE TITLE
Image corruption (--hwdec=vdpau) after rotating the screen on Linux. [vdpau preemption recovery]

### ISSUE THREAD

**Issue by davidsantos-br** [mpv-player/mpv#1675]
1. Start playing a video (in my case it was an H264/AAC .mp4) with `--hwdec=vdpau` (`--vo=opengl` or `--vo=vdpau`, I tested with both).
2. Pause.
3. Rotate the screen (e.g. with the command `xrandr -o right` or using NVIDIA X Server Settings, I tested with both).
   
   The video image will be corrupted*. Rotating back to the original setting (`xrandr -o normal`) won't fix it.
   
   The console shows the following messages:
   
   ```
   [vo/opengl/vdpau] Error when calling vdp_video_mixer_render: The display was pre-empted, or a fatal error occurred.
   (Paused) AV: 00:00:03 / 00:52:54 (0%) A-V:  0.000
   [vo/opengl/vdpau] Got display preemption notice! Will attempt to recover.
   (Paused) AV: 00:00:03 / 00:52:54 (0%) A-V:  0.000
   [vo/opengl/vdpau] Recovered from display preemption.
   ```
   
   Getting the mouse pointer in or out of the window (or hovering over the seek area of the floating control) litters the console with this message:
   
   ```
   [vo/opengl/vdpau] Error when calling vdp_video_mixer_render: An invalid handle value was provided.
   ```
4. Play.
   The video will stay corrupted for a few seconds, then it will go back to normal. I assume it goes back to normal when it reaches a keyframe.

If the screen is rotated without pausing the video, then the video area simply goes black (the audio keeps playing normally). Pausing/resuming doesn't fix it, neither does seeking. I didn't find a way to recover from that (i.e. I have to quit and restart mpv).

\* This is what I mean by “the video image will be corrupted”:
![screenshot from 2015-03-10 17 24 08 pixelized](https://cloud.githubusercontent.com/assets/39162/6584538/d0f6004a-c74a-11e4-89d3-faa7a31e9066.png)

**Comment by wm4** [comment]
I can reproduce this. Not sure what's going on.

**Comment by wm4** [comment]
PS: it's normal that when the driver throws away all state ("display preemption") the video is black or corrupted for a short time, but it shouldn't stay like this permanently.

**Comment by wm4** [comment]
Can you retry with latest git master? I'm not sure if it helps at all, but there was a change to this code.

**Comment by davidsantos-br** [comment]
I'm sorry, but I can't compile it. I tried several times, but it didn't work. I'm using Ubuntu Vivid. Using mpv-build it complained that `GL_RGB_422_APPLE` was undefined. I commented out that part, but then it complained that `GLX_CONTEXT_CORE_PROFILE_BIT_ARB` and `GLX_CONTEXT_PROFILE_MASK_ARB` are undefined. That's when I gave up.

**Comment by kevmitch** [comment]
> I'm sorry, but I can't compile it. I tried several times, but it didn't work. I'm using Ubuntu Vivid. 

I've just confirmed that mpv-build works on a stock vivid system. Did you use the debian package or generic method? Do you have any ppas enabled? Are you fully up to date? To get a list of possibly conflicting third party packages, you can run 

    aptitude search '?narrow(?installed, !?origin(Ubuntu))'

(you may need to install aptitude for that comand to work)

**Comment by davidsantos-br** [comment]
I was able to compile now. Same steps as yesterday, but I ran `apt-get dist-upgrade` earlier today. It's odd, because I ran it two or three days ago (i.e. one or two days before I tried to compile mpv), but apparently it made a difference because it's the only change I can think of since when I tried to do it yesterday.

**Comment by davidsantos-br** [comment]
Regarding the issue of the video area going black in an unrecoverable manner if the screen is rotated during playback, it still happens to me with `--vo=opengl --hwdec=vdpau` but not with `--vo=vdpau --hwdec=vdpau`. I don't know if it's relevant, but I'm using the video driver from the package nvidia-346 instead of nouveau.

If the video is paused when the screen is rotated, on subsequent playback both sets of options behave the same way they did before: the image gets corrupted for a few seconds but then it goes back to normal on the next keyframe (I think, it goes back to normal after a few seconds, usually when the image on the video changes substantially, like when the video cuts to another scene or camera angle). Based on wm4's comment, I take it that that much is normal for vdpau.

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
