### ISSUE TITLE
Client API: MPV_EVENT_PROPERTY_CHANGE doesn't fire when setting the property 'fullscreen' without any file loaded

### ISSUE THREAD

**Issue by jdoe0** [mpv-player/mpv#1676]
MPV_EVENT_PROPERTY_CHANGE doesn't fire when setting 'fullscreen' without any files loaded. The event fires correctly when there is at least one file loaded. The event also seems to fire correctly for other properties (eg. 'pause') even when there's no file loaded.

**Comment by wm4** [comment]
Can't reproduce.

Note that the video output is normally not initialized if no file is loaded, and then toggling fullscreen does not work. You can only set the fullscreen option. Setting options at runtime is kind of a hack though, and it doesn't trigger any notifications of any kind. This will probably be cleaned up later.

For now, I've made a change that allows setting the fullscreen _property_ even if no VO is created.
