### ISSUE TITLE
cant find the property for play/pause icon

### ISSUE THREAD

**Issue by blendi-93** [mpv-player/mpv#1677]
hi,
i'am tinkering with my mpv and want to use a custom osd-msg1 '${pause}: ${media-title}: ${time-remaining}'.
pause returns only yes/no (as in the manpage) but i'am searching for the prop to display the play/pause icon.
![mpv play icon in osd](http://i.imgur.com/6SoCx4p.png)

**Comment by wm4** [comment]
You can insert the current OSD symbol with ``${osd-sym-cc}``.

**Comment by blendi-93** [comment]
thx for help and sry for wasting ur time ;)
searched for ico or icon :D
