### ISSUE TITLE
Prefetch audio data in af?

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1678]
I'm trying to apply C++ library DynamicAudioNormalizer from http://muldersoft.com/docs/dyauno_readme.html but it requires looking ahead data about several seconds to find local gain factor.
I tried filter_out() and it works fine sometimes but also it causes out of sync of audio/video often.

vf can prefetch video frames by returing true in using needs_input().
Is it possible for af to prefetch audio data for looking ahead?
If not, can I expect it could be implemented?

**Comment by wm4** [comment]
Currently you need to set ``af->delay``. I'm also planning for changing it to use per-frame timestamps, but haven't realized this yet.

**Comment by xylosper** [comment]
I'm already doing it but still I get av desync from time to time and sometimes,  mpv prints av desync  warning message even though av is synchronized.

I wanted to make it sure whether mpv can prefetch audio data or not before debugging my code. So, from your answer it's possible if I set right value for delay?

**Comment by wm4** [comment]
The delay is in second. It sure is possible that there's a bug in the mpv code, of course, but in theory it should work. The delay must be the amount of audio that went into your filter, but wasn't output yet.

**Comment by xylosper** [comment]
Okay. Thank you for answer!
