### ISSUE TITLE
Green video with tensor scalers for cscale

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#1679]
With the latest git-master, specifying certain scalers for chroma scale make the video greenish and errors are printed on the terminal window.
I tried with several options and it seems it only happens with tensor scalers; bilinear and the ewa filters I tested are all working fine.

Here's the verbose log: https://gist.github.com/AirPort/f027db949b9f4bdf02a3

And here's the screenshot of the video output (I had to take it with the system's screen captures' program because mpv's screenshot had actually the correct colours): http://i.imgur.com/WBbC4s0.png

**Comment by haasn** [comment]
Should be fixed in 3ee9d7c416a6f61900c2c3b9ec46530906d43832.

**Comment by AirPort** [comment]
Yep, it is. Thank you!
