### ISSUE TITLE
get elapsed media file time

### ISSUE THREAD

**Issue by tberger2** [mpv-player/mpv#1682]
Hello
I'm missing the 'get_time_length' slave command to get the elapsed time of a video file played. Is there a way to obtain that information or redirect the command line output to a fifo log file?
Thank you in advance!

**Comment by wm4** [comment]
Is this a MPlayer command? This probably corresponds to the ``duration`` property. There are some other properties that return the current position etc. too.

**Comment by wm4** [comment]
Whoos, it's not ``duration``, but ``length``.

http://mpv.io/manual/master/#command-interface-length
