### ISSUE TITLE
timer.stop() does nothing, timer.kill() throws error

### ISSUE THREAD

**Issue by daikazoku** [mpv-player/mpv#1683]
I'm having problems with this simple lua script, but I'm not 100% sure if it's a bug or I just don't understand lua well enough. I'm using a windows build but I had an Os X friend try it and it gives the same results.

Expected behavior: the counter stops after 3 seconds.
Actual behavior: the counter stops after 6 seconds with an error thrown in the console.

```lua
counter = 0
timer = mp.add_periodic_timer(0.1, function() 
	mp.osd_message(counter, 0.1)
	counter = counter + 1
end) -- display an increasing number every tenth of second

mp.add_timeout(3, function() timer.stop() end) -- stop the timer after 3 seconds, does nothing

mp.add_timeout(6, function() timer.kill() end) -- kill the timer after 6 seconds, throws error
```

**Comment by wm4** [comment]
You need to use ``timer:stop()`` and ``timer:kill()``. (It can be confusing when to use ``.`` and ``:`` in Lua; usually ``:`` is used for objects, while ``.`` merely accesses a table.)

**Comment by daikazoku** [comment]
Thank you.
