### ISSUE TITLE
Only auto-connects to left channel when playing mono audio with jack

### ISSUE THREAD

**Issue by ids1024** [mpv-player/mpv#1684]
I noticed that I was only getting sound out of the left speaker when playing a file that previously worked fine, then I realized that I was using alsa and now I am using jack.  When playing mono audio, mpv only creates one jack ouput, and it only connects to the left speaker.

**Comment by wm4** [comment]
Jack has no channel layouts. Instead it requires you to map channels manually. So this is only natural that this happens, and it can by definition not be fixed.

**Comment by kevmitch** [comment]
>Jack has no channel layouts. Instead it requires you to map channels manually. 

by manually, you mean --audio-channels=2 should work in this particular instance?

**Comment by ids1024** [comment]
> by manually, you mean --audio-channels=2 should work in this particular instance?

Thanks, that does solve the issue for me.

**Comment by wm4** [comment]
Yes, or teach jack that only one connected output means mono, if that is even possible.

Also, we changed the default from --audio-channels=2 to --audio-channels=auto a while ago, which probably caused this?
