### ISSUE TITLE
8-channel playback with jack audio output on Linux

### ISSUE THREAD

**Issue by kalle-del-haye** [mpv-player/mpv#1688]
I'm using mpv with jack by using the option `ao=jack:port=jconvolver:std-channel-layout=alsa`.
But everytime playing a video with a 7.1 audio track, mpv convert the audio to 5.1. And there are 8 ports for mpv to connect to.

    [af] Audio filter chain:
    [af]   [in] 48000Hz 7.1 8ch s32
    [af]   [out] 48000Hz 7.1 8ch s32
    [af]   [ao] 48000Hz 7.1 8ch s32
    [ao] Trying preferred audio driver 'jack'
    [ao/jack] Setting option 'port' = 'jconvolver' (flags = 0)
    [ao/jack] Setting option 'std-channel-layout' = 'alsa' (flags = 0)
    [ao/jack] requested format: 48000 Hz, 7.1 channels, s32
    [ao/jack] chmap_sel #0: mono
    [ao/jack] chmap_sel #1: stereo
    [ao/jack] chmap_sel #2: 2.1
    [ao/jack] chmap_sel #3: quad
    [ao/jack] chmap_sel #4: 5.0(alsa)
    [ao/jack] chmap_sel #5: 5.1(alsa)
    [ao/jack] chmap_sel #6: 6.1
    [ao/jack] using soft-buffer of 9600 samples.
    AO: [jack] 48000Hz 5.1(alsa) 6ch floatp
    [cplayer] AO: Description: JACK audio output
    [af] Adding filter lavrresample
    [af] Audio filter chain:
    [af]   [in] 48000Hz 7.1 8ch s32
    [af]   [lavrresample] 48000Hz 5.1(alsa) 6ch floatp
    [af]   [out] 48000Hz 5.1(alsa) 6ch floatp
    [af]   [ao] 48000Hz 5.1(alsa) 6ch floatp

To me, it looks like `std-channel-layout=alsa` prevents the selection of an 8-channel map.
So, do I make some mistake or is there something wrong with mpv?

kalle

**Comment by wm4** [comment]
I hope it works now.

**Comment by kalle-del-haye** [comment]
Not really:

    [af]   [ao] 48000Hz 7.1 8ch s32
    [ao] Trying preferred audio driver 'jack'
    [ao/jack] Setting option 'port' = 'jconvolver' (flags = 0)
    [ao/jack] Setting option 'std-channel-layout' = 'alsa' (flags = 0)
    [ao/jack] requested format: 48000 Hz, 7.1 channels, s32
    [ao/jack] chmap_sel #0: mono
    [ao/jack] chmap_sel #1: stereo
    [ao/jack] chmap_sel #2: 2.1
    [ao/jack] chmap_sel #3: quad
    [ao/jack] chmap_sel #4: 5.0(alsa)
    [ao/jack] chmap_sel #5: 5.1(alsa)
    [ao/jack] chmap_sel #6: 6.1
    [ao/jack] chmap_sel #7: 7.1(alsa)
    [ao/jack] not enough ports available
    [ao] Failed to initialize audio driver 'jack'

So, the right channelmap is available - but mpv says `[ao/jack] not enough ports available`. Jack says, there are 8 input ports usable by mpv.

By the way, `msg-level=ao=debug` dosn't work for me. I have to set `msg-level=all=debug` to see the [ao] debug output.

Thanks.
kalle

**Comment by wm4** [comment]
I don't really know how jack works, but I'm pretty sure mpv tries to use ports ``out_0`` to ``out_7``. It's not something about port ``out_8`` instead of port ``out_0`` being provided, or is it?

Anyway, I added 1 more line of debug output to be sure. Maybe you can look at it again.

>By the way, msg-level=ao=debug dosn't work for me. I have to set msg-level=all=debug to see the [ao] debug output.

Works for me.

**Comment by kalle-del-haye** [comment]
OK. I have found the problem.
For 8 channel playback through jack in my situation I need 32 ports (4 x 8), **theoretically**. But only when I start jackd with 33 ports (or more) the playback is working.

    AO: [jack] 48000Hz 7.1(alsa) 8ch floatp

Not really logical - but *"C’est la vie".*

On the debug logging problem I will take a deeper look tomorrow.

Thanks for your help.
