### ISSUE TITLE
Audio skips when adding filters

### ISSUE THREAD

**Issue by bucaneer** [mpv-player/mpv#1693]
I'm trying to setup mpv as a backend for [gmusicbrowser](https://github.com/squentin/gmusicbrowser), using the JSON IPC to control it. I'm having trouble with equalizer and volume (replaygain) audio filters. Each time filter-related settings in gmusicbrowser are updated, mpv receives a command like this:
`{"command":["af","add","@EQ:equalizer=0:0:0:0:0:0:0:0:0:0"]}`
This makes mpv playback skip ahead (to next audio frame?), so moving an equalizer slider is basically like holding down a fast-forward button.

Mplayer does not have this problem - if I adjust filter settings with a slave mode command (e.g. `af_cmdline equalizer 0:0:0:0:0:0:0:0:0:0`), playback continues smoothly. I assume mpv tries to apply filters immediately, while mplayer waits for an opportunity to apply them without disruption.

Is there some way to force mplayer-like behaviour in this case?

**Comment by wm4** [comment]
>Is there some way to force mplayer-like behaviour in this case?

The difference is only that mplayer doesn't drop the audio output buffers, while mpv does. I guess this could be changed.

**Comment by wm4** [comment]
Probably better, let me know.

**Comment by bucaneer** [comment]
That resolves the issue completely, thanks.
