### ISSUE TITLE
SIMBL bundle not being injected properly

### ISSUE THREAD

**Issue by twayz** [mpv-player/mpv#1694]
Hi,

I'm not sure why but I have a couple SIMBL plugins that inject additional items in the "Window" menu bar in all my OSX applications. Both were installed using EasySIMBL However, these plugins do not work on the mpv osx application. I tried two plugins: Afloat and MenuAndDockless. They both work on pretty much every other OSX app I have except mpv. Mpv does load both bundles but nothing gets injected into the "Window" menu. I'm hoping someone has more insight into why this is happening. Here is the log file:

3/16/15 6:27:53.255 PM com.github.norio-nomura.SIMBL-Agent[497]: #EasySIMBL add runningApp <NSRunningApplication: 0x7ff5ae982130 (io.mpv - 93575)>.
3/16/15 6:27:53.380 PM com.github.norio-nomura.SIMBL-Agent[497]: #EasySIMBL runningApp <NSRunningApplication: 0x7ff5ae982130 (io.mpv - 93575)> isFinishedLaunching.
3/16/15 6:27:53.380 PM com.github.norio-nomura.SIMBL-Agent[497]: #EasySIMBL mpv started
3/16/15 6:27:53.381 PM com.github.norio-nomura.SIMBL-Agent[497]: #EasySIMBL app start notification: <NSRunningApplication: 0x7ff5ae982130 (io.mpv - 93575)>
3/16/15 6:27:53.386 PM com.github.norio-nomura.SIMBL-Agent[497]: warning: failed to get scripting definition from /usr/local/Cellar/mpv/HEAD/mpv.app; it may not be scriptable.
3/16/15 6:27:53.416 PM mpv[93575]: #EasySIMBL SIMBL loaded by path /usr/local/Cellar/mpv/HEAD/mpv.app <io.mpv>
3/16/15 6:27:53.416 PM mpv[93575]: #EasySIMBL checking bundle /Users/rob/Library/Application Support/SIMBL/Plugins/Afloat.bundle
3/16/15 6:27:53.417 PM mpv[93575]: #EasySIMBL checking target identifier *
3/16/15 6:27:53.418 PM mpv[93575]: <Afloat - DEBUG: '-[Afloat install]'>: <Afloat: 0x60800003f880> found no Window menu in NSApp <Application: 0x608000150ac0>
3/16/15 6:27:53.419 PM mpv[93575]: #EasySIMBL loaded /Users/rob/Library/Application Support/SIMBL/Plugins/Afloat.bundle
3/16/15 6:27:53.419 PM mpv[93575]: #EasySIMBL checking bundle /Users/rob/Library/Application Support/SIMBL/Plugins/MenuAndDockless.bundle
3/16/15 6:27:53.419 PM mpv[93575]: #EasySIMBL checking target identifier *
3/16/15 6:27:53.421 PM mpv[93575]: load
3/16/15 6:27:53.421 PM mpv[93575]: #EasySIMBL loaded /Users/rob/Library/Application Support/SIMBL/Plugins/MenuAndDockless.bundle
3/16/15 6:27:53.421 PM mpv[93575]: #EasySIMBL checking bundle /Users/rob/Library/Application Support/SIMBL/Plugins/SpotlightFinder.bundle
3/16/15 6:27:53.422 PM mpv[93575]: #EasySIMBL checking target identifier com.apple.Spotlight
3/16/15 6:27:53.422 PM mpv[93575]: #EasySIMBL checking bundle /Users/rob/Library/Application Support/SIMBL/Plugins/TypeStatus.bundle
3/16/15 6:27:53.423 PM mpv[93575]: #EasySIMBL checking target identifier com.apple.iChat
3/16/15 6:27:53.424 PM com.github.norio-nomura.SIMBL-Agent[497]: #EasySIMBL receiveSIMBLHasBeenLoadedNotification from io.mpv
3/16/15 6:27:53.721 PM mpv[93575]: insertMenu

Thank you!

**Comment by Argon-** [comment]
Shouldn't you contact the SIMBL people? It's not like "being able to inject code with a third party application" is supposed to be a feature of most software.

**Comment by pigoz** [comment]
Maybe it's because mpv is a nibless application? I have no idea how those plugins would work.

**Comment by wm4** [comment]
Unless someone explicitly works on this, I don't think this will ever get fixed.
