### ISSUE TITLE
[featurerequest] playlist support for osc

### ISSUE THREAD

**Issue by blendi-93** [mpv-player/mpv#1699]
can we have a interactive playlist via osc for example?

**Comment by ChrisK2** [comment]
this is quite difficult to do properly, but it's already on a "things we'll eventually do in a distant future"-list

**Comment by blendi-93** [comment]
"things we'll eventually do in a distant future"-list

thx, thats all i want :D great player btw

**Comment by sleek22** [comment]
@blendi-93 

The following is a little script I wrote in AutoIt that can move through a directory while mpv is running. It sets the F2 and F3 keys as hotkeys when mpv is running. It release them when mpv closes. AutoIt is available here:

http://fileforum.betanews.com/detail/AutoIt/968271279/1

While 1
Sleep(100)
	If ProcessExists("mpv.exe") Then mpv()
WEnd

Func mpv()
HotKeySet("{F2}","previous")
HotKeySet("{F3}","nextx")

While ProcessExists("mpv.exe")
   Sleep(100)
WEnd   

HotKeySet("{F2}")
HotKeySet("{F3}")  
EndFunc


Func previous()
   Send("q")
   Sleep(100)
   Send("{LEFT}")
   Sleep(100)
   Send("{ENTER}")
EndFunc

Func nextx()
   Send("q")
   Sleep(100)
   Send("{RIGHT}")
   Sleep(100)
   Send("{ENTER}")
EndFunc
