### ISSUE TITLE
Empty config won't display some jpg images

### ISSUE THREAD

**Issue by cmdrkotori** [mpv-player/mpv#1700]
Bascially, every now and then about (1/500-1/1000) I come across a jpeg image in my collection that mpv cannot display with an empty config.
Here's one. http://a.pomf.se/lrevgj.jpg It displays fine in browser but not in mpv.

    tux@oniichan ~/Pictures> mpv --config=no 1425608696721.jpg 
    Playing: 1425608696721.jpg
    [ffmpeg/video] mjpeg: Unhandled pixel format 0x32111100 bits:8
    [ffmpeg/demuxer] jpeg_pipe: Could not find codec parameters for stream 0 (Video: mjpeg, none(bt470bg/unknown/unknown), 1234x1000 [SAR 256:256 DAR 617:500]): unspecified pixel format
    [ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' and 'probesize' options
    [lavf] av_find_stream_info() failed
     (+) Video --vid=1 (mjpeg)
    [ffmpeg/video] mjpeg: Unhandled pixel format 0x32111100 bits:8
    Error while decoding frame!
    
    
    Exiting... (Errors when loading file)

on the other hand, when I copy my vo from my config over, it opens:

    tux@oniichan ~/Pictures> mpv --config=no '--vo=opengl-hq:swapinterval=1:dither-depth=8:scale=ewa_lanczossharp:cscale=ewa_lanczossharp:temporal-dither:scaler-resizes-only:scale-antiring=1.0:cscale-antiring=1.0:fbo-format=rgba16f:sigmoid-upscaling:sigmoid-slope=6.5:sigmoid-center=0.75:smoothmotion:background=0.5/0.5/0.5' 1424716203934.jpg 
    Warning: option smoothmotion was replaced with interpolation and might be removed in the future.
    Playing: 1424716203934.jpg
     (+) Video --vid=1 (mjpeg)
    [vo/opengl-hq] Warning: option smoothmotion was replaced with interpolation and might be removed in the future.
    VO: [opengl-hq] 1824x1026 yuv420p
    V: 00:00:00 (0%)
    
    
    Exiting... (End of file)

fwiw, this file crashes mplayer2 as well.

**Comment by lachs0r** [comment]
Works for me. `mpv -V`?

**Comment by wm4** [comment]
The image you linked works perfectly fine here with --no-config.

**Comment by cmdrkotori** [comment]
Perhaps the bug is with ffmpeg?


mpv -V says

    mpv git-c710e14 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
     built on 2015-03-16T03:22:54
    ffmpeg library versions:
       libavutil       54.20.100
       libavcodec      56.28.100
       libavformat     56.25.101
       libswscale      3.1.101
       libavfilter     5.12.100
       libswresample   1.1.100

My ffmpeg options are
--enable-libx264 --enable-libmp3lame --enable-libfdk-aac --enable-nonfree --enable-libvpx --enable-libvorbis

**Comment by wm4** [comment]
Your ffmpeg looks slightly more recent than what I was testing with, so it seems unlikely.

**Comment by cmdrkotori** [comment]
Sorry about that, I uploaded the wrong file. I was hoping to do this without using a NSFW image. http://a.pomf.se/bembli.jpg

Upon further testing, --vo actually has no effect. It seems I was looking at an adjacent image when trying to isolate the bug.

**Comment by lachs0r** [comment]
I’m using the same ffmpeg library versions for my Windows builds and they work fine. However, that mpv version points to a commit on haasn’s personal master branch (do you have a good reason to use this?). Maybe you should try building mpv master instead.

**Comment by cmdrkotori** [comment]
No, this bug has been present for over a week before I switched. I was just testing out some stuff.

**Comment by lachs0r** [comment]
This JPEG file uses 3:1:1 subsampling (wtf), which I guess is not supported by FFmpeg.

**Comment by cmdrkotori** [comment]
Seems so. I just recompiled with latest ffmpeg-master and mpv-master from here, and it is still present.

**Comment by wm4** [comment]
Definitely a ffmpeg issue. You can try reporting it to ffmpeg.

**Comment by lachs0r** [comment]
Note: You can create such files with ImageMagick: `convert image.png -sampling-factor 3:1:1 out.jpg`

**Comment by wm4** [comment]
FFmpeg fixed it in git master.
