### ISSUE TITLE
osd-font-size question

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#1703]
from the man page:
```
--osd-font-size=<size>
[..]
The actual pixel size is scaled with  the  window height: if the window height is larger or smaller than 720, the actual size of the text increases or decreases as well.
```
That seems to apply to Xv, but not to opengl.
Indeed, with a 1280x1024 screen, the following gives me larger than 50px font:
```
mpv videofile --osd-font="Liberation Sans:style=bold" --osd-font-size=50 --fs --osd-scale=1024/720 --vo=opengl
```
..while this one gives me exactly 50px font:
```
mpv videofile --osd-font="Liberation Sans:style=bold" --osd-font-size=50 --fs --osd-scale=1 --vo=opengl
```

The very same commands, but with --vo=xv produced expected results: (50px font on fullscreen with -osd-scale=1024/720 and smaller than 50px font with --osd-scale=1).

EDIT:
I forgot the question.
Is the manpage wrong? Is there a way to have consistent osd font sizes across different video output drivers?

thanks.

**Comment by wm4** [comment]
xv is special. It doesn't have OSD support, so OSD is rendered into video.

DO NOT USE XV.

**Comment by kokoko3k** [comment]
Ok,
Then what is stated on the man page is wrong (on opengl.)
with opengl what you have on the screen is exactly the font size you selected, NOT your screen height/720

**Comment by wm4** [comment]
Don't know, what without osd-scale?

**Comment by kokoko3k** [comment]
--osd-scale=1 or without osd-scale is perfectly the same.
With opengl, WYSIWYG, no need to to any math.

**Comment by wm4** [comment]
I mean how it behaves without using --osd-scale.

**Comment by kokoko3k** [comment]
It is the same

**Comment by wm4** [comment]
No, opengl behaves exactly as described in the manpage. I even tested it again.

And xv is, as I've said before, a special-case.

**Comment by d9k** [comment]
mpv options names constantly change causing errors so consult docs:

https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst

**Comment by garoto** [comment]
Most useless issue bump I've seen in all these years. Nice job.
