### ISSUE TITLE
Issue playing rtmp streamings

### ISSUE THREAD

**Issue by zecarlosalmeida** [mpv-player/mpv#1704]
Can't use attribute --network-timeout when playing rtmp addresses like:  rtmp://rtmp3.srvstm.com/13128/13128.stream
Appears the error: Failed to open rtmp://rtmp3.srvstm.com/13128/13128.stream

Thanks

**Comment by wm4** [comment]
FFmpeg doesn't allow setting the timeout for this protocol. mpv ignores the option in this case now.
