### ISSUE TITLE
Allow retrieving window-related options (geometry, autofit, etc.) when using client API

### ISSUE THREAD

**Issue by jdoe0** [mpv-player/mpv#1705]
Currently, trying to retrieve the value of window-related options such as `geometry` returns NULL even when the option is set via mpv_load_config_file() or mpv_set_option_string(). Allowing these options to be retrieved via client API would be useful as it would allow clients to easily handle these options themselves.

**Comment by wm4** [comment]
In what form do you want them back? As strings? Are you going to parse this string, and why?

**Comment by jdoe0** [comment]
>In what form do you want them back? As strings?
Yes. I think it would make sense to make it accessible via the properties `options/` and `option-info/` like the other options.
>Are you going to parse this string, and why?
Yes. Currently, my frontend accepts an mpv config file from the user and pass it to mpv. Pretty much all options work correctly except things like `autofit`. I want to be able to detect and read the value from these options so that I can move and resize the GUI accordingly.

**Comment by wm4** [comment]
I added it, but note that I think what you're doing is not only not worth the effort, but also fragile and will break as soon as we change something.
