### ISSUE TITLE
Please don't remove option vo=opengl:srgb 

### ISSUE THREAD

**Issue by cwbsw** [mpv-player/mpv#1707]
This option is useful. It can fix the color problem on my mid-2014 Macbook Pro, although I don't know the reason exactly. 

The color problem is about dynamic range. As we all know, the video file is encoded with 16-235, the TV is also 16-235, but PC display is 0-255, so conversion is needed. It looks like that my mac can't handle it correctly. If I add "vo=opengl:srgb" to my config file, I will get correct output. 

This is a .mp4 file for test. [This is download link.](https://drive.google.com/file/d/0B6Oxh3xiW-x8VFhQN1R4R3FnZUk/view?usp=sharing) Please look at bottom right corner.

The first picture is right, and the last one is wrong.
![2015-03-21 13 48 25](https://cloud.githubusercontent.com/assets/10339357/6764069/0e487414-cfd9-11e4-9a04-5e06d45de0f3.png)
![2015-03-21 13 49 10](https://cloud.githubusercontent.com/assets/10339357/6764073/21f1be30-cfd9-11e4-8981-96719a3671a7.png)

**Comment by haasn** [comment]
:srgb wasn't removed, it was deprecated in favor of :target-prim=bt709:target-trc=srgb (which should have the same result as the old :srgb flag - if not, it's a bug).

**Comment by pigoz** [comment]
Did you try `icc-profile-auto`? That's what you want to generally use on OS X..

**Comment by cwbsw** [comment]
Thank you all. Unfortunately, both ":target-prim=bt709:target-trc=srgb" and "icc-profile-auto" didn't work. I also tried "colormatrix-output-range=limited", then the output is wrong as expected, but is contrary to the second picture above, no conversion was executed. At last, I found that ":srgb" option may be not the key factor, after many experiments. 

I test the "0.7.3-git-c4e4d9c" and "git-010cf18", the former's output is right, the latter is newer and its output is wrong, but the option ":srgb" is suitable for both. Then I reviewed the two logs carefully, there are some differences between them. Is it the true reason? 

The right log:

[vo/opengl] compiling shader program 'frag_osd_libass', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] [  2] #define USE_OSD_LINEAR_CONV_BT2020 1
[vo/opengl] [  3] #define USE_OSD_SRGB 1
[vo/opengl] compiling shader program 'frag_osd_rgba', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] [  2] #define USE_OSD_LINEAR_CONV_BT2020 1
[vo/opengl] [  3] #define USE_OSD_SRGB 1
[vo/opengl] shader link log (status=1): WARNING: Output of vertex shader 'color' not read by fragment shader
[vo/opengl] 
[vo/opengl] compiling shader program 'indirect', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] [  2] #define USE_CONV CONV_PLANAR
[vo/opengl] [  3] #define USE_COLORMATRIX 1
[vo/opengl] [  4] #define USE_LINEAR_LIGHT_BT2020 1
[vo/opengl] [  5] #define SAMPLE_C(p0, p1, p2) sample_bilinear(p0, p1, p2, filter_param1_c)
[vo/opengl] [  6] #define SAMPLE_L SAMPLE_BILINEAR
[vo/opengl] [  7] #define FIXED_SCALE 1
[vo/opengl] shader link log (status=1): WARNING: Output of vertex shader 'color' not read by fragment shader
[vo/opengl] 
[vo/opengl] compiling shader program 'final', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] [  2] #define USE_SRGB 1
[vo/opengl] [  3] #define SAMPLE_L(p0, p1, p2) sample_bilinear(p0, p1, p2, filter_param1_l)
[vo/opengl] shader link log (status=1): WARNING: Output of vertex shader 'color' not read by fragment shader

The wrong log:

 [vo/opengl] compiling shader program 'frag_osd_libass', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] [  2] #define USE_OSD_LINEAR_CONV_BT1886 1
[vo/opengl] [  3] #define USE_OSD_SRGB 1
[vo/opengl] compiling shader program 'frag_osd_rgba', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] [  2] #define USE_OSD_LINEAR_CONV_BT1886 1
[vo/opengl] [  3] #define USE_OSD_SRGB 1
[vo/opengl] shader link log (status=1): WARNING: Output of vertex shader 'color' not read by fragment shader
[vo/opengl] 
[vo/opengl] compiling shader program 'indirect', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] [  2] #define USE_CONV CONV_PLANAR
[vo/opengl] [  3] #define USE_COLORMATRIX 1
[vo/opengl] [  4] #define USE_LINEAR_LIGHT_BT1886 1
[vo/opengl] [  5] #define SAMPLE_C(p0, p1, p2) sample_bilinear(p0, p1, p2, filter_param1_c)
[vo/opengl] [  6] #define SAMPLE SAMPLE_TRIVIAL
[vo/opengl] [  7] #define FIXED_SCALE 1
[vo/opengl] shader link log (status=1): WARNING: Output of vertex shader 'color' not read by fragment shader
[vo/opengl] 
[vo/opengl] compiling shader program 'final', header:
[vo/opengl] [  1] #define VIDEO_SAMPLER sampler2D
[vo/opengl] [  2] #define USE_SRGB 1
[vo/opengl] [  3] #define SAMPLE(p0, p1, p2) sample_bilinear(p0, p1, p2, filter_param1_l)
[vo/opengl] shader link log (status=1): WARNING: Output of vertex shader 'color' not read by fragment shader

**Comment by haasn** [comment]
So you're complaining about the BT.2020 -> BT.1886 change? The former was wrong. If you got output that seems “right” with it, then perhaps something else is wrong in your system.

What makes you think that one image is more correct than the other? What is your methodology, and what are your sources?

**Comment by cwbsw** [comment]
Maybe you're right, because almost all the other players on Mac OS X, like VLC, XBMC, QuickTime, do the same thing as mpv's latest build. But in my opinion, the "wrong" image is too dark, so that some details are lost in the shadows. So could I switch back to BT.2020 by editing config file?

**Comment by haasn** [comment]
No, but you can use a different ICC profile for your display, and you can also manually increase the brightness using the “brightess” and “user gamma” controls.

**Comment by cwbsw** [comment]
Thank you. I'll have a try.
