### ISSUE TITLE
MPV not using custom  subtitle styles

### ISSUE THREAD

**Issue by AbhiDGamer** [mpv-player/mpv#1708]
I am not able to get mpv to show the subtitles in desired style.It used to work in earlier versions of mpv but now it just shows only default type of subtitle.I am currently using latest mpv build (64 bit) for windows (64 bit)  available at http://mpv.srsfckn.biz/
Earlier
![earlier](https://cloud.githubusercontent.com/assets/7191374/6766135/12dea2f4-d020-11e4-97c4-89eed8355e8d.jpg)
Now
![now](https://cloud.githubusercontent.com/assets/7191374/6766136/12e4e31c-d020-11e4-87e4-455f25f43c10.png)

and it shows error like:
  Unable to update the static FcBlanks: 0xfffb
### My config file:
--vo=direct3d_shaders
--ao=dsound
--hwdec=auto
--ass-force-style="Name=Default,Fontname=comicbd,Fontsize=20,PlayResX=512,PlayResY=320,Name=Default,Fontname=Comic Sans MS,Fontsize=24,PrimaryColour=&H0000ffff,BackColour=&H00000000,OutlineColour=&H00000000,Bold=1,Italic=0,Alignment=2,BorderStyle=1,Outline=0.5,Shadow=1,MarginL=20,MarginR=24,MarginV=2"
--sub-auto=fuzzy
--osd-level=1
--osd-fractions=yes
--save-position-on-quit
--softvol=yes
--softvol-max=300
--framedrop=decoder+vo
--sub-pos=100
--sub-text-margin-y=0
--osd-margin-y=0
--ass-use-margins
--ytdl=yes
--ytdl-format=bestvideo+bestaudio
--slang=en
--cache=5000
--ass-line-spacing=1

**Comment by wm4** [comment]
these are probably not ASS subs, and ``--ass-force-style`` doesn't affect them. (This is my guess, didn't check.) Use the ``--sub-text-...`` options to customize the style instead.

**Comment by AbhiDGamer** [comment]
thanks for the suggestion. I tried it out and it worked.
#here is my new conf file:
# MPV Write your default config options here!
# Use opengl video output by default.
--vo=direct3d_shaders
--ao=dsound
--hwdec=auto
# Use quotes for text that can contain spaces:
--ass-force-style="Fontname=comicz,Fontsize=20,PlayResX=512,PlayResY=320,PrimaryColour=&H0000ffff,BackColour=&H00000000,OutlineColour=&H00000000,Bold=1,Italic=0,Alignment=2,BorderStyle=1,Outline=0.5,Shadow=1,MarginL=20,MarginR=24,MarginV=2"
--sub-auto=fuzzy
--osd-level=1
--osd-fractions=yes
--save-position-on-quit
--softvol=yes
--softvol-max=300
--framedrop=decoder+vo
--sub-pos=100
--sub-text-margin-y=0
--osd-margin-y=0
--ass-use-margins
--ytdl=yes
--ytdl-format=bestvideo+bestaudio
--slang=en
--cache=5000
--sub-ass
--sub-text-font='Comic Sans MS:style=Bold'
--sub-text-font-size=50
--sub-text-color='#FFFF00'
--sub-text-back-color='#0000ffff'
--sub-text-border-color='#00000000'
--ass-line-spacing=1
