### ISSUE TITLE
Popcorn-Time mpv crashes...

### ISSUE THREAD

**Issue by meuwe** [mpv-player/mpv#1710]
Hi,

I filed a report with Popcorn-Time but they said mpv had nothing to do with their code.

When I start a video with mpv as my external video player it crashes.

When I start Popcorn-Time from the cmd line, I do not see any output when mpv crashes, so I'm not sure how I can see what is going on causing this.

mpv crashes in their 0.3.7.2 beta and the latest version from git too...

I tried this without my ~/.mpv/config and let it run with default settings that mpv gives it, but it still crashed...

**Comment by wm4** [comment]
Well, does it print anything when it crashes? Does it crash at all, or just exist without playing a video? Can you post a log?

>mpv crashes in their 0.3.7.2 beta

We never released such a version. We did release 0.3.7... 1 year ago.

**Comment by meuwe** [comment]
Hi,

Well I'm saying crash, it just closes and stops playing and I've been messing with it and Popcorn-Time for hours and can't seem to figure why.

I run Popcorn-Time from the terminal but it doesn't show anything when mpv closes.

I said 0.3.7 ```in their`` meaning their app, hehe... :)

**Comment by wm4** [comment]
>Well I'm saying crash, it just closes and stops playing and I've been messing with it and Popcorn-Time for hours and can't seem to figure why.

Try putting ``log-file=/tmp/log.txt`` into your mpv.conf.

>I said 0.3.7 `in their meaning their app, hehe... :)

Oh, ok.

**Comment by meuwe** [comment]
ok brb :)

**Comment by meuwe** [comment]
Here's the log output;

http://dpaste.com/1H41DSQ

**Comment by wm4** [comment]
I see no crash in this log. Playback seems to initialize, and after 70 seconds you quit.

**Comment by meuwe** [comment]
It just quits on it's own...

By the way I though to play a online video you just do;

mpv URL?

So I try and nothing, it just shows me options is all...

mpv https://www.youtube.com/watch?v=9fdAt0ke9w8

**Comment by mc4man** [comment]
Here with popcorn & mpv as soon as mpv starts playback the streaming will be stopped after 1 min or so. 
Then mpv plays out whatever has already been dl'ed/cached & closes. If one was to pause mpv before the streaming is canceled then the dl'ing continues until playback is started in mpv, then again after 1 min or so it's cancelled, ect.

seen in popcorn terminal - 
[2746:0322/112718:INFO:CONSOLE(46)] ""[%cINFO%c] Loading torrent:" "color: blue;" "color: black;" "startingDownload"", source: app://host/src/app/app.js (46)
[2746:0322/112723:INFO:CONSOLE(46)] ""[%cINFO%c] Loading torrent:" "color: blue;" "color: black;" "downloading"", source: app://host/src/app/app.js (46)
[2746:0322/112759:INFO:CONSOLE(46)] ""[%cINFO%c] Loading torrent:" "color: blue;" "color: black;" "ready"", source: app://host/src/app/app.js (46)
[2746:0322/112759:INFO:CONSOLE(46)] ""[%cINFO%c] Loading torrent:" "color: blue;" "color: black;" "playingExternally"", source: app://host/src/app/app.js (46)
[2746:0322/112759:INFO:CONSOLE(46)] ""[%cINFO%c] Launching External Player: \"/usr/bin/mpv\"  http://127.0.0.1:54745/" "color: blue;" "color: black;"", source: app://host/src/app/app.js (46)
[2746:0322/112956:INFO:CONSOLE(46)] ""[%cINFO%c] Streaming cancelled" "color: blue;" "color: black;"", source: app://host/src/app/app.js (46)
[2746:0322/112956:INFO:CONSOLE(46)] ""[%cINFO%c] Preloading stoped" "color: blue;" "color: black;"", source: app://host/src/app/app.js (46)

**Comment by meuwe** [comment]
@mc4man I wonder if this is popcorn cancel the stream? Hmm

**Comment by meuwe** [comment]
I also noticed when mpv is playing a little before it closes the audio is really low and I use in my config;

ao=alsa

I tried vlc and it works ok and the audio is also really loud, not sure why audio is also so low in mpv.

Lots of hmms LOL...

**Comment by wm4** [comment]
I see:

>[  83.416][v][cplayer] Run command: quit, flags=9, args=[0]

Which means someone explicitly sends a quit command.

**Comment by meuwe** [comment]
LOL, Popcorn sent the cmd then, because I was just sitting doing nothing but watching. ;)

**Comment by meuwe** [comment]
I asked before, I can't get mpv to play a youtube video, please tell me how?

I thought it was just; ```mpv url```?

**Comment by wm4** [comment]
>LOL, Popcorn sent the cmd then, because I was just sitting doing nothing but watching. ;)

I don't know, but I doubt it. They would have to enable slave mode etc., but they probably don't even have mpv specific code.

Maybe it's because mpv receives SIGTERM or so?

**Comment by meuwe** [comment]
SIGTERM hmm...

But can you PLEASE tell me how to play a stream online, so I can test to see if it will stream ok...

thank you

**Comment by wm4** [comment]
Depends what kind of stream; the command line you tried with youtube should have worked or shown an error message (instead of the help text) - it's like mpv was called without arguments.

**Comment by meuwe** [comment]
mpv https://www.youtube.com/watch?v=9fdAt0ke9w8

mpv 0.8.3-git-4db470e (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-03-22T14:55:08
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options

**Comment by meuwe** [comment]
Won't play errrr this is 0.8.3, just spits out the help text...

**Comment by mc4man** [comment]
They only have this in src/app/lib/device/ext-player.js
'mpv': {
			type: 'mpv',
			switches: '',
			subswitch: '--sub-file='
mpv itself has no issue playing the stream, (stream started from another player, then mpv the unique local url),  nor does smplayer using mpv

**Comment by meuwe** [comment]
If this is suppose to play videos as mpv URL and it's not playing for me, maybe this is why it's crapping in Popcorn-Time?

Hmm

**Comment by mc4man** [comment]
That youtube vid is fine here so separate local? issue to you

**Comment by meuwe** [comment]
@mc4man I just comipled 0.8.3 from the mpv-build scripts, the only thing I have added to it is;
```
ffmpeg_options
--enable-libxvid 
--enable-libx264
```
And
```
mpv_options
--prefix=/usr
--confdir=/etc/mpv
--docdir=/usr/doc/mpv-0.8.3
--mandir=/usr/man
--disable-libavresample
```

Other then these 2 files everything else is standard for the scripts...

**Comment by meuwe** [comment]
AHHHH I have to put it in quotes " "

This works! :)

--> ```mpv "https://www.youtube.com/watch?v=9fdAt0ke9w8"```

**Comment by wm4** [comment]
Your shell must have dropped the URL then. (bash doesn't do this.)

**Comment by meuwe** [comment]
AHHH HA, so that's it? I'm using zsh...

**Comment by lachs0r** [comment]
On Sunday 22 March 2015 10:01:39 meuwe wrote:
> AHHH HA, so that's it? I'm using zsh...

And properly configured zsh should not do this either, or at least do nothing 
and print a glob error.

**Comment by qmega** [comment]
With setopt null_glob it would do that.

**Comment by mc4man** [comment]
Got it to work on Debian/Ubuntu by giving the mpv entry a cmd & some switches. It's possible it's just 1 of the 3 or some combo. At this point because this grunt build stuff was a pita to get  work right don't care to find out anymore. Basically just used what I do for the Exec= in mpv's .desktop
(using just -- didn't help
[27234:0322/171655:INFO:CONSOLE(46)] ""[%cINFO%c] Launching External Player: \"/usr/bin/mpv\" --no-terminal --force-window  -- http://127.0.0.1:35835/"
![screenshot from 2015-03-22 17 25 19](https://cloud.githubusercontent.com/assets/5961561/6771586/73da8eea-d0b8-11e4-9c6d-ab682751f413.png)

**Comment by meuwe** [comment]
@lachs0r ok...

@mc4man so you just used, ```--no-terminal & --force-window```?

By the way anyone have Windows to test this on?

@lachs0r ahh so you're the one making the Windows build? I'll grab the latest x64 one and see how it goes in Win7 too.

**Comment by mc4man** [comment]
Well actually 3 but no matter, tried 1 last build using just --no-terminal & that seems to do the trick, whatever that is..
.. Launching External Player: \"/usr/bin/mpv\" --no-terminal  http://127.0.0.1:49022/" ....

**Comment by meuwe** [comment]
@mc4man 

Ok I'll add that to my config and give it a try...

**Comment by wm4** [comment]
>So what does terminal=no do? From man all I can gather is that output/messages, warnings, etc, aren't sent to the terminal?

It disables terminal output and input. To only disable input ``input-terminal=no`` can be used. I'm not sure why this matters, but I suppose this popcorn thing wants input itself, and some of the input you're sending to it triggers a quit key binding.

**Comment by avih** [comment]
Could there be a case where mpv playing the file prevents popcorn-time from writing to it, and so it aborts playback once EOF is reached, and P.T. aborts writing to the file once it realizing it's not writable?

**Comment by meuwe** [comment]
So terminal=no mean as example, no playback status?

**Comment by meuwe** [comment]
Why was this closed? I don't see any mention on whether this is a mpv bug or popcorn issue?

thanks

**Comment by mc4man** [comment]
I certainly could be wrong but my perspective is - 
Popcorn has an entry in their source to use mpv as an external player & it doesn't work right, at least for linux.
So it's Popcorn's problem to get it right.
(- if they add the switch (option), then it works correctly or they could pursue whatever else makes mpv work if there is some objection to using that option.

**Comment by meuwe** [comment]
Ok Developer said this was the fix;

https://git.popcorntime.io/popcorntime/desktop/commit/6f1864cb00b0af4da062391de04206f9495c88b0

**Comment by meuwe** [comment]
So is this a Popcorntime or mpv issue?

**Comment by meuwe** [comment]
Anyone, my last question?

thanks

**Comment by wm4** [comment]
Wasn't everything said in this issue?

**Comment by meuwe** [comment]
My mistake, I wasn't looking closely enough, I see it seems to be a popcorn issue...

thank you

**Comment by Andoni199** [comment]
Hey, how can I apply those settings to my current Popcorn-Time installation? It won't let me save them through Developer Tools.
