### ISSUE TITLE
Windows build - waf does not find installed libraries

### ISSUE THREAD

**Issue by papplampe** [mpv-player/mpv#1716]
I followed all of the steps here: https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#native-compilation-with-msys2 but using the i686 version.
When running the configration step it complains about missing libraries. But according to pkg-config they are installed and using a test program I can link to them.
Here the log:

    $ ./waf configure CC=gcc.exe --prefix=/mingw32
    Setting top to                           : C:\Users\dummy\Downloads\mpv 
    Setting out to                           : C:\Users\dummy\Downloads\mpv\build 
    Checking for waf version in 1.8.4-1.9.0  : ok 
    Checking for program 'cc'                : gcc.exe 
    Checking for program 'pkg-config'        : C:\msys32\usr\bin\pkg-config.exe 
    Checking for program 'ar'                : C:\msys32\mingw32\bin\ar.exe 
    Checking for program 'perl'              : C:\msys32\usr\bin\perl.exe 
    Checking for program 'rst2man'           : not found 
    Checking for program 'rst2pdf'           : not found 
    Checking for program 'windres'           : C:\msys32\mingw32\bin\windres.exe 
    Checking for 'msvc' (C compiler)         : not found 
    Checking for 'gcc' (C compiler)          : gcc.exe 
    Detected target OS:                      : os-win32 
    Checking for compiler flags -Werror=implicit-function-declaration : yes 
    Checking for compiler flags -Wno-error=deprecated-declarations    : yes 
    Checking for compiler flags -Wno-error=unused-function            : yes 
    Checking for compiler flags -Wempty-body                          : yes 
    Checking for compiler flags -Wdisabled-optimization               : yes 
    Checking for compiler flags -Wstrict-prototypes                   : yes 
    Checking for compiler flags -Wno-format-zero-length               : yes 
    Checking for compiler flags -Werror=format-security               : yes 
    Checking for mpv CLI player                                       : yes 
    Checking for shared library                                       : disabled 
    Checking for static library                                       : disabled 
    Checking for static build                                         : disabled 
    Checking for whether to include binary compile time               : yes 
    Checking for whether to optimize                                  : yes 
    Checking for whether to compile-in debugging information          : yes 
    Checking for manpage generation                                   : no (missing RST2MAN) 
    Checking for pdf manual generation                                : disabled 
    Checking for dynamic loader                                       : no 
    Checking for dlopen                                               : yes 
    Checking for compilation of default filters for vf_dlopen         : disabled 
    Checking for zsh completion                                       : disabled 
    Checking for inline assembly (currently without effect)           : yes 
    Checking for test suite (using cmocka)                            : disabled 
    Checking for generate a clang compilation database                : disabled 
    Checking for compiler support for noexecstack                     : no 
    Checking for linker support for --nxcompat --no-seh --dynamicbase : yes 
    Checking for -lm                                                  : yes 
    Checking for MinGW                                                : yes 
    Checking for POSIX environment                                    : no 
    Checking for development environment                              : yes 
    Checking for win32                                                : yes 
    Checking for internal pthread wrapper for win32 (Vista+)          : disabled 
    Checking for POSIX threads                                        : yes 
    Checking for stdatomic.h                                          : yes 
    Checking for compiler support for __atomic built-ins              : stdatomic found 
    Checking for compiler support for __sync built-ins                : stdatomic found 
    Checking for compiler support for usable thread synchronization built-ins : yes 
    Checking for linking with -lrt                                            : no 
    Checking for iconv                                                        : yes 
    Checking for w32/dos paths                                                : yes 
    Checking for libwaio for win32                                            : no 
    Checking for termios                                                      : no 
    Checking for shm                                                          : no 
    Checking for nanosleep                                                    : yes 
    Checking for POSIX spawnp()/kill()                                        : no 
    Checking for glob()                                                       : no 
    Checking for glob() win32 replacement                                     : yes 
    Checking for fchmod()                                                     : no 
    Checking for GLIBC API for setting thread name                            : no 
    Checking for OSX API for setting thread name                              : no 
    Checking for BSD API for setting thread name                              : no 
    Checking for NetBSD API for setting thread name                           : no 
    Checking for BSD's fstatfs()                                              : no 
    Checking for Linux's fstatfs()                                            : os-linux not found 
    Checking for libguess support                                             : no ('libguess >= 1.0' not found) 
    Checking for Samba support                                                : libdl not found 
    Checking for Lua                                                          : no ('luajit >= 2.0.0' not found) 
    Checking for SSA/ASS support                                              : no ('libass >= 0.12.1' not found) 
    Unable to find development files for libass, or the version found is too old. Aborting. If you really mean to compile without libass support use --disable-libass.

And just to prove that libass is indeed installed here the output of pkg-config:

    $ pkg-config --atleast-version 0.12.1 libass && echo $?
    0

**Comment by wm4** [comment]
Did you try running:
``C:\msys32\usr\bin\pkg-config.exe --atleast-version 0.12.1 libass && echo $?``

(There could be a small chance that these are different executables.)

**Comment by rossy** [comment]
That looks like it's using a MinGW/MSVC Python. I've only had success with the MSYS version of Python. You could try invoking MSYS Python directly with ``/usr/bin/python3 waf configure CC=gcc --prefix=/mingw32``

**Comment by wm4** [comment]
Also, can you post the ``build/config.log`` file?

**Comment by papplampe** [comment]
$ where pkg-config
    C:\msys32\usr\bin\pkg-config.exe

    $ "C:\msys32\usr\bin\pkg-config.exe" --atleast-version 0.12.1 libass && echo $?
    0

**Comment by papplampe** [comment]
$ /usr/bin/python3 waf configure CC=gcc.exe --prefix=/mingw32
    Setting top to                           : /c/Users/dummy/Downloads/mpv
    Setting out to                           : /c/Users/dummy/Downloads/mpv/build
    Checking for waf version in 1.8.4-1.9.0  : ok
    Checking for program 'cc'                : gcc.exe
    Checking for program 'pkg-config'        : /usr/bin/pkg-config
    Checking for program 'ar'                : /mingw32/bin/ar
    Checking for program 'perl'              : /usr/bin/perl
    Checking for program 'rst2man'           : not found
    Checking for program 'rst2pdf'           : not found
    Checking for program 'windres'           : /mingw32/bin/windres
    Checking for 'gcc' (C compiler)          : gcc.exe
    Detected target OS:                      : os-win32
    Checking for compiler flags -Werror=implicit-function-declaration : yes
    Checking for compiler flags -Wno-error=deprecated-declarations    : yes
    Checking for compiler flags -Wno-error=unused-function            :       0 [main] python3 1260 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied
    no
    Checking for compiler flags -Wempty-body                          : yes
    Checking for compiler flags -Wdisabled-optimization               :       0 [main] python3 6060 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied
    no
    Checking for compiler flags -Wstrict-prototypes                   : yes
    Checking for compiler flags -Wno-format-zero-length               : yes
    Checking for compiler flags -Werror=format-security               : yes
    Checking for mpv CLI player                                       : yes
    Checking for shared library                                       : disabled
    Checking for static library                                       : disabled
    Checking for static build                                         : disabled
    Checking for whether to include binary compile time               : yes
    Checking for whether to optimize                                  : yes
    Checking for whether to compile-in debugging information          : yes
    Checking for manpage generation                                   : no (missing RST2MAN)
    Checking for pdf manual generation                                : disabled
    Checking for dynamic loader                                       : no
    Checking for dlopen                                               : yes
    Checking for compilation of default filters for vf_dlopen         : disabled
    Checking for zsh completion                                       : disabled
    Checking for inline assembly (currently without effect)           : yes
    Checking for test suite (using cmocka)                            : disabled
    Checking for generate a clang compilation database                : disabled
    Checking for compiler support for noexecstack                     :       0 [main] python3 5644 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied
    no
    Checking for linker support for --nxcompat --no-seh --dynamicbase : yes
    Checking for -lm                                                  : yes
    Checking for MinGW                                                : yes
    Checking for POSIX environment                                    :       0 [main] python3 2576 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied
    no
    Checking for development environment                              : yes
    Checking for win32                                                : yes
    Checking for internal pthread wrapper for win32 (Vista+)          : disabled
    Checking for POSIX threads                                        :       0 [main] python3 6068 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied
          0 [main] python3 4288 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied
          0 [main] python3 6040 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied
          0 [main] python3 4760 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied
    yes
    Checking for stdatomic.h                                          : yes
    Checking for compiler support for __atomic built-ins              : stdatomic found
    Checking for compiler support for __sync built-ins                : stdatomic found
    Checking for compiler support for usable thread synchronization built-ins : yes
    Checking for linking with -lrt                                            : no
    Checking for iconv                                                        :       0 [main] python3 5084 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied
          0 [main] python3 5516 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied
    no
    Unable to find iconv which should be part of a standard compilation environment. Aborting. If you really mean to compile without iconv support use --disable-iconv.    

And here the resulting log of that build: http://pastebin.com/trDyiFC0

Resulting log of "./waf configure CC=gcc.exe --prefix=/mingw32" (using non msys python): http://pastebin.com/d8JF5bCM

**Comment by rossy** [comment]
> ``0 [main] python3 4288 child_info_fork::abort: address space needed by 'msys-crypto-1.0.0.dll' (0xA50000) is already occupied``

This isn't good. Is MSYS2 up to date, and has it been restarted (all terminal windows closed and re-opened) since the update? If so, close everything and run ``autorebase.bat`` from the MSYS2 install directory.

**Comment by wm4** [comment]
It's all very mysterious. Can you try the official python 3 binary? Someone reported it works.

**Comment by papplampe** [comment]
running autorebase.bat after installing the msys python fixed it
