### ISSUE TITLE
FEATURE REQUEST: --term-title-msg option

### ISSUE THREAD

**Issue by roboman2444** [mpv-player/mpv#1725]
Having mpv set the title of a xterm or similar terminal would be very nice while playing media. Being able to look down at my task bar and seeing what track is currently playing, or the time would be very useful I tried to do this using escape characters by setting --term-status-msg, but it is not possible.
If this is already possible, or has already been requested, feel free to remove this.

**Comment by wm4** [comment]
>I tried to do this using escape characters by setting --term-status-msg,

It should be possible, though messing with the escapes is probably not fun.

**Comment by roboman2444** [comment]
Xterm title escapes require a null character somewhere in there, and i don't think it is possible to do it without modifying the source.

**Comment by wm4** [comment]
That's very nasty. It's basically impossible for us without changing how everything works, because all console output goes through printf.

**Comment by wm4** [comment]
Rejected; unless someone finds a way to do this without sending a 0 byte.

**Comment by vlopezj** [comment]
I use `zsh` as my shell. I managed to get the desired behaviour by adding the following hack to my `.zshrc` file:

```zsh
MPV_EXEC=/usr/bin/mpv
function mpv {
        $MPV_EXEC --term-status-msg $'\n\e]0;${filename} - mpv\a\n${?pause==yes:(Paused) }${time-pos} / ${duration} (${percent-pos}%)' $@
}
```
Screenshot:

![screenshot_20180908_171344](https://user-images.githubusercontent.com/1593773/45255750-b7c88d00-b38b-11e8-9578-1efabc03f087.png)

The `$'` … `'` syntax around the argument to `--term-status-msg` is a way of telling zsh to interpret the escape sequences (i.e. \e, \a, \n) in the string, but leave the dollar signs as they are.

I don't know if this can be generalized to other configurations; but I'll leave it here in case someone else comes across this issue.

**Comment by kanliot** [comment]
yeah, would be nice to see what song is playing.  "mpv:Dietrich Buxtehude - Song# 3"

**Comment by cbirchinger** [comment]
This is possible by adding the following to your "term-status-msg":

  \e]0;${media-title}^G

The "^G" is a \007 (BEL aka ASCII 7), which makes it a bit ugly, but while \e does turn into and ESC,
there is no way to use \007 or \a that i know of. It would be really good to allow \a or \007 and
not just \e for escape sequences in the terminal. To be clear here, "0" is ASCII 48, a normal character.

**Comment by wm4** [comment]
> There is no null byte being required to send.

My mistake.

**Comment by wm4** [comment]
@cbirchinger the --term-status-msg option specifically processes C style escapes, but it doesn't parse octal. That's why `\e` works. It does process hex escapes, so `\x07` should work. Anyway, added an option.
