### ISSUE TITLE
Commands aren't read when piped

### ISSUE THREAD

**Issue by anko** [mpv-player/mpv#1727]
Piping `mpv` into `sed` to modify its output (or just `cat`, for testing) disables keyboard commands. I wish it didn't. (Or should I not be doing that in the first place?)

I dug in a little and found [the conditional for that](https://github.com/mpv-player/mpv/blob/aa8823c2d22f9b703ba309ba23a32ed6b326fc1c/osdep/terminal-unix.c#L419-422), with the justification that it "makes mpv ... | less do the right thing". What does that mean? ([blame](https://github.com/mpv-player/mpv/blame/aa8823c2d22f9b703ba309ba23a32ed6b326fc1c/osdep/terminal-unix.c#L419-422) → @wm4)

`mplayer`'s keyboard input still works when the command is piped. (It has other issues when piped through `sed` though…)

**Comment by wm4** [comment]
>I dug in a little and found the conditional for that, with the justification that it "makes mpv ... | less do the right thing". What does that mean? (blame → @wm4)

Without it, trying to scroll up/down in less would send the input to mpv and issue e.g. seek commands.

**Comment by anko** [comment]
> trying to scroll up/down in less would send the input to mpv and issue e.g. seek commands

So when two programs read in raw mode, they *both* get sent the key events? Oh man. Sounds unfixable.

**Comment by wm4** [comment]
Actually, I think it's pretty much random who gets the input. The first key might go to the player, the second to less, and such. So is there anything we should do about this?

**Comment by anko** [comment]
Sorry for my previous vagueness. I can't see anything that mpv could do about it.

What I should really be doing is writing a wrapper that reads in raw mode and sends the resulting commands to an instance of mpv with `--input-unix-socket`, which I can then pipe. That mpv instance not reading terminal input is OK.
