### ISSUE TITLE
On Screen Controller Font Missing

### ISSUE THREAD

**Issue by asoksevil** [mpv-player/mpv#1728]
My OSC doesn't show tracks for audio, subtitles nor the title of the video currently playing:

![Imaget](http://i.imgur.com/vgZw8sq.png)

While it should be something like this:

![image](http://mpv.io/images/mpv-screenshot@2x-a5690cbb.jpg)

Any ideas? My config file has no OSC code whatsoever and it was compiled by me following this guide: https://coalgirls.wakku.to/faq/playback/compiling-mpv-on-mac-os-x

Thanks!

**Comment by wm4** [comment]
Your screenshot has no text, so the problem is probably missing fonts or a messed up fontconfig configuration (a quite common problem on OSX).

**Comment by asoksevil** [comment]
Thanks for the fast reply.

How do I fix it? Compile it again?

**Comment by Argon-** [comment]
This guide is a bit strange and looks outdated (quvi doesn't exist anymore). It installs `libass-ct` first, just to use `--with-official-libass` (that is, not `libass-ct`) right after.
Try

    brew uninstall --HEAD mpv
    brew install --HEAD mpv

and in case this does not work, try it with:

    brew uninstall --HEAD mpv
    brew uninstall --HEAD mpv-player/mpv/libass-ct
    brew install --HEAD --with-official-libass mpv

Please mind the first start-up when using a official-libass build might take quite some time while mpv appears to hang (it's recreating the font cache).

**Comment by ChrisK2** [comment]
Oh right, I should change that ...

**Comment by wm4** [comment]
?
