### ISSUE TITLE
Configure script can't find vapoursynth

### ISSUE THREAD

**Issue by Epictek** [mpv-player/mpv#1737]
./waf configure --enable-vapoursynth
```
Checking for VapourSynth filter bridge (core)                             : no ('vapoursynth >= 24' not found) 
Checking for VapourSynth filter bridge (Python)                           : vapoursynth-core not found 
You manually enabled the feature 'vapoursynth', but the autodetection check failed.
```

vspipe --version
```
VapourSynth Video Processing Library      
Copyright (c) 2012-2014 Fredrik Mellbin
Core R26
API R3.1
```

OS is Void Linux

**Comment by wm4** [comment]
Probably missing vapoursynth.pc file? vspipe is completely different, it's just a command line program that uses the vapoursynth libs.

**Comment by Epictek** [comment]
Where should that file be located? By running a find command I found it was in the folder /usr/local/lib/pkgconfig/

**Comment by Epictek** [comment]
had to add /usr/local/lib/pkgconfig/ to the PKG_CONFIG_PATH

**Comment by wm4** [comment]
This path should be included by default on virtually all distros.
