### ISSUE TITLE
volume resets after switching audio tracks

### ISSUE THREAD

**Issue by Argon-** [mpv-player/mpv#1740]
config:

    softvol-max=100
    volume=50

When I switch the audio track (`cycle audio`) in mkv files volume is set to 100%.
(I'm using softvol)

**Comment by wm4** [comment]
Can't reproduce.

**Comment by Argon-** [comment]
Probably a coreaudio thing? I can reproduce it with `--softvol-max=100 --volume=50 --no-config` but only using coreaudio. ao=pcm or ao=null work fine.

**Comment by wm4** [comment]
What about ``softvol=yes``?

**Comment by Argon-** [comment]
Fixes the problem. `softvol=auto` behaves like `softvol=no`, that is, resets the volume.
Is this a user error?

**Comment by wm4** [comment]
Probably not. Must be due to the recent pulseaudio fix. I can't get this volume restore shit ever right...

**Comment by wm4** [comment]
Please try again. If it doesn't work, make a log of the case that doesn't work with ``--msg-level=mixer=trace``.

**Comment by Argon-** [comment]
Works just as expected, the volume is retained after switching tracks, thanks!
