### ISSUE TITLE
mpv crashes when dealing with file that has ordered chapter

### ISSUE THREAD

**Issue by sikachu** [mpv-player/mpv#1741]
I'm really don't know what happen, but this file has ordered chapter. While running this file, mpv would crash at this point every time.

Here's the log from stdout and crash log https://gist.github.com/sikachu/58e3ac1f9a79404d404c

```
$ mpv --version
mpv git-8fff125 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-03-30T15:49:36
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100
```

If you need any more information for help debugging, please let me know. Thank you!

**Comment by wm4** [comment]
It appears to be crashing when reading embedded fonts. Can you try updating libass and harfbuzz? (These libraries recently had fixes on OSX, though it might be unrelated.)

**Comment by sikachu** [comment]
@wm4 apparently I no longer get a crash after I rebuilt mpv with `--with-official-libass` (which installed libsass version `0.12.1` for me). My `mpv` was built with HEAD (pigoz/libass-ct@af6c1d42c5a76a89697ecfddbba73102a28d3e1e) `libass-ct` when the crash occured.

Should I reopen this issue on `pigoz/libass-ct` instead?

/cc @pigoz

**Comment by wm4** [comment]
Yes, please. Also I'm closing this, since it's quite clearly a libass-ct issue.
