### ISSUE TITLE
Bitstream wasapi exlusive mode

### ISSUE THREAD

**Issue by evdw87** [mpv-player/mpv#1742]
On Windows, when specifying spdif as decoder, mpv should use wasapi excluvie mode by default.

**Comment by kevmitch** [comment]
We also need to make sure that all the supportable bitstream formats (particularly dtshd, truehd) actually work, and correctly (as in correct number / mapping of channels).

**Comment by wm4** [comment]
...which boils down to not touching the audio parameters if it's a passthrough format. You can use ``AF_FORMAT_IS_SPECIAL(x)`` for this.

**Comment by kevmitch** [comment]
@evdw87 could you test the above. In case you don't want to compile it, here an [mpv.exe](https://www.dropbox.com/s/bqapcfv4pabasmb/mpv.exe?dl=0). I hope 64 bit is Ok.

**Comment by kevmitch** [comment]
let me know the output with --msg-level=ao=debug

**Comment by kevmitch** [comment]
for reference, that broke existing passthrough for ac3 and dts. 

ac3 passthrough format was rejected by IsFormatSupported
dts passthrough was accepted, but the audio thread feed froze

my hypothesis is that this is a result of trying to set nBlockAlign.

**Comment by kevmitch** [comment]
ughgh, ignor all but the last of the above three. [mpv-2ccee18.exe](https://www.dropbox.com/s/0crx2hg215mr19c/mpv-2ccee18.exe?dl=0)

weird console window bug should also be fixed.

**Comment by kevmitch** [comment]
fix stupid format GUID errors. [mpv-d9609ad.exe](https://www.dropbox.com/s/zb2k530jnwsmxnz/mpv-d9609ad.exe?dl=0)
