### ISSUE TITLE
Disable audio filters for bitstream audio

### ISSUE THREAD

**Issue by evdw87** [mpv-player/mpv#1743]
When passing --rubberband to mpv it's impossible to use bitstream audio, please fix.

**Comment by wm4** [comment]
As discussed on IRC, bitstreaming is incompatible with audio filters. What you want is that mpv should silently drop filters which don't fit in. I'm not quite sure yet how to go about this.

**Comment by wm4** [comment]
Should work now. It simply drops the filter and prints a warning.
