### ISSUE TITLE
There's no way to differentiate '-' and '+-' when retrieving value of '--geometry' using client API

### ISSUE THREAD

**Issue by jdoe0** [mpv-player/mpv#1744]
For example, retrieving the value of the option 'geometry' after setting it to either '+20-20' or '+20+-20' both result in the string '0x0+20+-20' being returned. Since '-' and '+-' have different meanings, there should be a way to differentiate them in the returned string. (Perhaps the returned string should be '0x0+20++-20' for the '+20+-20' case?)

**Comment by wm4** [comment]
Sure is confusing. I hope it's better now, but there might still be a dozen of bugs there.
