### ISSUE TITLE
Feature request: always on-top on mac

### ISSUE THREAD

**Issue by WoLpH** [mpv-player/mpv#1750]
Since OS X is a bit crappy in terms of customizability it seems to be impossible to have a reliable always on-top feature, for most apps I have it working using afloat but that doesn't appear to be working for mpv.

It would be great if there would be some always on-top feature, for me it would work just fine if it's always on.

**Comment by pigoz** [comment]
Already present (see: http://mpv.io/manual/master/#options-ontop)

Can also be triggered with `Shift+t`

**Comment by WoLpH** [comment]
Thank you very much, must have used the wrong keywords when searching.

**Comment by WoLpH** [comment]
Works like a charm, thanks for the fantastic app :)
It's got everything I always loved about mplayer and loads more to make it even better.
