### ISSUE TITLE
osc-hidetimeout not compatible with per-extension profiles

### ISSUE THREAD

**Issue by dogroll** [mpv-player/mpv#1751]
[extension.webm]
script-opts=osc-hidetimeout=-1

Tried using this, doesn't work.

**Comment by wm4** [comment]
It doesn't because script options can't be updated at runtime anyway. We'd need some sort of mechanism for this.

What exactly the goal anyway with this config?

**Comment by dogroll** [comment]
I wanted the OSC/seek bar to remain open permanently only when playing certain file extensions.

**Comment by Patricol** [comment]
To give a more specific use case, I want the seek bar to always show for audio files; but not for videos.

**Comment by garoto** [comment]
Isn't exactly what avih script posted on your linked issue deals with?

**Comment by Dudemanguy** [comment]
OP's example works just fine for me. Open a new issue if this really still exists.
