### ISSUE TITLE
profile = pseudo-gui doesn't go to idle window on single file end

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#1756]
It just sits at the eof. 
Ex. - gtk-launch mpv  /home/doug/Videos/amostviolentyear-nowplaying_h1080p.mov
http://paste.ubuntu.com/10725616/

**Comment by wm4** [comment]
It's because --keep-open is also default in this mode.

**Comment by mc4man** [comment]
So then the idea here (from pseudo-gui)  is idle (window)  only on initial opening without any target file?

**Comment by mc4man** [comment]
I see in another issue that a profile entry in the local config can disable keep-open & allow idle in the (pseudo)  gui.
However I can't see where most users of the gui would want keep-open at the expense of idle or even at all.
 So for a quick test for any feedback will put up a new build with the default of keep-open to no. 
Any of the few, if any, that want keep-open can use the config to set via a [pseudo-gui] section entry.

**Comment by wm4** [comment]
So I'm thinking of changing these flags before we release (CC @Kovensky). Should I? What do you want changed? This question goes to everyone.

**Comment by mc4man** [comment]
Seems obvious - from a 'gui' perspective keep-open makes no sense, idle does. 
The prior 'gui'  and current cli behavior would be for the window to close at file end. So now from the gui users will get an empty black window at file end where there is  nothing to be done except replay/seek back or explicitly close out.
The most likely perception would be that  mpv is hanging at file end vs wow - nice new feature.

**Comment by wm4** [comment]
The participation sure wasn't high, but I killed it.

**Comment by mc4man** [comment]
For builds I provide I'll be going for the only thing that makes sense - 

    m_config_set_profile_option(cfg, ui, bstr0("idle"), bstr0("yes"));
    m_config_set_profile_option(cfg, ui, bstr0("keep-open"), bstr0("no"));
