### ISSUE TITLE
main window disappears after being unminimized

### ISSUE THREAD

**Issue by jojoman02** [mpv-player/mpv#1757]
## Steps to reproduce:

1) under OSX dock preferences enable "minimize windows into application icon"
2) start playing a video in MPV and pause it
3) enable "stay to top" SHIFT+T
4) minimize the window
5) attempt to unminimize the window by clicking the application icon.
6) watch as window unminimize and become hidden at the end of the unminimize animation

osx version 10.10.2 and 10.10.3

edit: updated with additional data to better reproduce bug

**Comment by es0phagus** [comment]
Yeah, it seems to only occur when "minimize windows into application icon" option is ticked in Dock options.

**Comment by AirPort** [comment]
Can't reproduce on my machine (MBP mid 2010, nVidia GPU) with Os X 10.10.3. Could it be a system bug solved in the last version, or maybe something related to video drivers?

**Comment by es0phagus** [comment]
Not solved, I've just updated to latest OS X

**Comment by jojoman02** [comment]
window still seems to be somewhere. if you hit F on keyboard (to fullscreen) it works... and hitting F takes it back to normal size and then it's visible.

**Comment by es0phagus** [comment]
^ that is a decent workaround but not a fix, but thanks.

**Comment by wm4** [comment]
What mpv version? Try git master.

**Comment by Argon-** [comment]
Can't reproduce it as well using 10.10.2 and current master (`e6d7e55`).
Maybe try it with `--no-config` and in case it works now try to find the problematic option in your config.

**Comment by es0phagus** [comment]
version git-8fff125. Git master?

How do I do the 'no config' thing? what do I enter into the config file exactly

**Comment by Argon-** [comment]
Where do you have your version of mpv from?

**Comment by es0phagus** [comment]
Where should I be getting the version from? I downloaded my mpv from the main site.

**Comment by jojoman02** [comment]
This version from **mpv.io** has the issue: 
> 64-bit binary (by ChrisK) [OS X 10.8+]	 http://sva.wakku.to/~chris/mpv_builds/mpv_latest.zip

I just removed mpv and reinstalled it via homebrew. Now there is **no issue**. I suppose ChrisK needs to update his build.

* Homebrew: http://brew.sh/  
* Homebrew-MPV: https://github.com/mpv-player/homebrew-mpv

**Comment by Argon-** [comment]
Funny, I just tried this version (and http://sva.wakku.to/~chris/mpv_builds/mpv_20150329202708_git-8fff125.tar.bz2 which is apparently the one es0phagus is using) and both work for me just fine.
@es0phagus if the problem still persists after upgrading to a more recent version I'd suggest you try to move your config (so mpv won't load it) and check if the problem is still there.
`--no-config` is a flag used when invoking mpv from the Terminal.

**Comment by es0phagus** [comment]
I upgraded and it still persists. Where is the config file located again? I've forgotten.

**Comment by jojoman02** [comment]
After some investigation it appears to be a bug related to the **stay on top** option, not any particular build as i've just replicated it with latest mpv from homebrew.

**Comment by es0phagus** [comment]
Yup, after I removed "ontop" from the config file the bug ceases.

**Comment by es0phagus** [comment]
Any chance of this being fixed? Still persists on El Capitan.

**Comment by jojoman02** [comment]
yep, i've noticed some apps (e.g. vox) handle on top correctly. idk how.

**Comment by Akemi** [comment]
[this](https://github.com/Akemi/mpv/commit/2355e3ef51dcc1945a9263311a3c9aaa69b3cb25) should work around this bug.

**Comment by Akemi** [comment]
okay instead of working around the bug, i found a way to [fix](https://github.com/Akemi/mpv/commit/fda4bab0afd4f18dabfe084af87bd6366414ae6c) the cause of it. this also fixes #1884. @jojoman02 since you reported both bugs can you confirm it fixes it for you too?

**Comment by es0phagus** [comment]
How do I use the code? As in where exactly do I place the fix? The mpv I have installed came built completely, unsure if that changes anything

**Comment by Akemi** [comment]
you have to build it yourself or you can try [this](https://dl.dropboxusercontent.com/u/68772824/mpv.zip).
