### ISSUE TITLE
--audio-file-auto does not load .ac3 files

### ISSUE THREAD

**Issue by oneoneleven** [mpv-player/mpv#1759]
mpv with --audio-file-auto option does not consider .ac3 file as an external.

Strangely, it begins to work if you just rename it to, for example, .mp3:
```
[find_files] Loading external files in .
[find_files] Potential external file: "The.Simpsons_S04_E17_Last.Exit.to.Springfield_EN.mp3"  Priority: 4
```

The ac3 file is in the same folder and has same name as the video file, ofc.
Also it's definitely AC-3 because lavf demuxer recognizes an AC-3 stream (even with .mp3 extension)

mpv 0.8.3, OS X 10.10

**Comment by wm4** [comment]
mpv loads such files using a whitelist of file extensions (because otherwise it'd have to open files to probe them). I added ".ac3" to the whitelist in git master.
