### ISSUE TITLE
undefined symbol: ass_set_selective_style_override_enabled

### ISSUE THREAD

**Issue by ldinc** [mpv-player/mpv#1762]
on loading video with external sub getting error: 
* mpv: symbol lookup error: mpv: undefined symbol: ass_set_selective_style_override_enabled

System: Linux linux.site 3.16.7-7-desktop #1 SMP PREEMPT Wed Dec 17 18:00:44 UTC 2014 (762f27a) x86_64 x86_64 x86_64 GNU/Linux
mpv 0.8.3 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Mar 21 2015
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100

**Comment by wm4** [comment]
libass too old. You probably compiled against recent libass headers, but you're linking to an older one at runtime.

**Comment by ldinc** [comment]
Thx, sorry for pulling this as issue!
