### ISSUE TITLE
OSS4 Playback has slight crackles

### ISSUE THREAD

**Issue by Xylemon** [mpv-player/mpv#1767]
MPV crackles when I use OSS for my sound output, but using ALSA with emulation plays fine. The cause seems to be related to this message when playing with OSS:

[ao/oss] Can't set audio device to float output.
AO: [oss] 44100Hz stereo 2ch s32

With ALSA Emulation:

[ao/alsa] Format float is not supported by hardware, trying default.
AO: [alsa] 44100Hz stereo 2ch s16

I've been reading the documentation for MPV, but I'm still not sure how to fix this issue, any help?

**Comment by Xylemon** [comment]
Setting "--aid=1" seems to have corrected the issue.

**Comment by wm4** [comment]
Maybe something about s32 support is broken, either in the OSS driver or the OSS-specific mpv code. For testing, you can try ``--audio-format=s16``.

**Comment by wm4** [comment]
Looking at the code, I can't see why s32 would fail like this.

**Comment by Xylemon** [comment]
Thank you, "--audio-format=s16" works fine. Could the issue simply be my soundcard is shite? I have simple on-board HDAudio, and it's quite difficult with OSS sometimes.

**Comment by wm4** [comment]
Although I can't test or confirm it myself, I have no reason to believe that mpv does anything wrong. So I don't know what else to try. Maybe you can ask OSS4 developers to have a look at this and to analyze the issue.

**Comment by Xylemon** [comment]
I'll have to ask and further investigate the issue, until I get a response or someone else with a real sound card can confirm this issue, feel free to close this issue. I just wish MozPlugger would respect the "--audio-format=s16" parameter since I use MPV instead of Flash for sites like YouTube.
