### ISSUE TITLE
switching device formats in exclusive mode can lead to irrecoverable audio device invalidation

### ISSUE THREAD

**Issue by kevmitch** [mpv-player/mpv#1773]
This is the last remnant of #674. Even with all the device changed event monitoring, we are still unable to gracefully handle the following corner case:

* Playing an exclusive mode pcm stream.
* Enable/Disable loudness equalization via windows device control panel
* ao_reload is requested, audio_reset is called 
* IAudioClient_Reset() returns E_HANDLE
* IAudioClient_Stop() returns AUDCLNT_E_NOT_STOPPED
* IAudioClient_Release() refuses to return so that 
* WaitForSingleObject(state->hAudioThread, INFINITE) never returns

**Comment by wm4** [comment]
>IAudioClient_Release() refuses to return so that 

That's the most ridiculous thing I've ever read. Isn't this the IUnknown method? Why would it not return? It just decreases the refcount. Seems like either Microsoft broke their own crap big time, or your drivers are somehow broken, or there's a fatal bug in the ao_wasapi code.

**Comment by kevmitch** [comment]
Doesn't Release have to deconstruct the object when the refcount hits 0?  My guess is that this final Release is calling some c++ monstrosity that could have a wait in there somewhere.

**Comment by wm4** [comment]
If such a case happens, then the wasapi internals could reasonably just create an additional (internal) reference to it, rather than preventing the user from unreffing it.
