### ISSUE TITLE
mms streaming of mms://winmedia.hartford.edu/WWUH_stream hangs on opening

### ISSUE THREAD

**Issue by jmesmon** [mpv-player/mpv#1776]
```
x@arnold ~ $ mpv mms://winmedia.hartford.edu/WWUH_stream
Playing: mms://winmedia.hartford.edu/WWUH_stream
```
[here I wait for some time then press Q]
```
Failed to open mms://winmedia.hartford.edu/WWUH_stream.


Exiting... (Quit)
x@arnold ~ $ 
```

The same stream seems to work fine with mplayer.

Version info:
```
$ mpv --version
mpv 0.8.3 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100
```

```
$ mplayer -v
MPlayer SVN-r37373 (Gentoo)-4.8.3 (C) 2000-2015 MPlayer Team
CPU vendor name: GenuineIntel  max cpuid level: 13
CPU: Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz (Family: 6, Model: 60, Stepping: 3)
extended cpuid-level: 8
extended cache-info: 16801856
Detected cache-line size is 64 bytes
CPUflags:  MMX: 1 MMX2: 1 3DNow: 0 3DNowExt: 0 SSE: 1 SSE2: 1 SSE3: 1 SSSE3: 1 SSE4: 1 SSE4.2: 1 AVX: 1
Compiled for x86 CPU with extensions: MMX MMX2 SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX CMOV
get_path('codecs.conf') -> '/home/x/.mplayer/codecs.conf'
Reading optional codecs config file /home/x/.mplayer/codecs.conf: No such file or directory
Reading optional codecs config file /etc/mplayer/codecs.conf: No such file or directory
Using built-in default codecs.conf.
init_freetype
Using MMX (with tiny bit MMX2) Optimized OnScreenDisplay
get_path('fonts') -> '/home/x/.mplayer/fonts'
```

**Comment by mc4man** [comment]
try - 
mpv rtsp://winmedia.hartford.edu/WWUH_stream

**Comment by jmesmon** [comment]
Indeed, that works. Is there a reason `mms://` doesn't just fall back to `rtsp`? Will `rtsp` always work in these cases? In anycase: sitting for a long time without doing anything isn't ideal if it can be avoided (even exiting with an error and noting that one should try rtsp would be preferable).

**Comment by mc4man** [comment]
No idea what mpv does internally, I just look at ffmpeg/ffplay. So there mms is not a supported protocol, related supported ones are mmsh, mmst, rtsp, ect
(it seems mmst would also work on your site

**Comment by mc4man** [comment]
Just to mention - 
If one was to try to open a mms in mpv thru a playlist file (context menu or mime association),  then 'nothing' would appear to happen but mpv would run in background until killed or reboot, ect. Whether that would happen with any other unsupported protocol (if any), didn't ck..

**Comment by wm4** [comment]
>Indeed, that works. Is there a reason mms:// doesn't just fall back to rtsp?

Why would it? Just use the correct protocol prefix in the first place. Also, trying to connect via mms just times out, so there's nothing that can be done about the delay.

**Comment by wm4** [comment]
> then 'nothing' would appear to happen but mpv would run in background until killed or reboot, ect. 

That's why I wanted to change the --forced-window behavior (which you complained about, so I reverted it).

**Comment by jmesmon** [comment]
@wm4 the reason I was trying to use `mms://` is that the webpage points me at it:

http://wwuh.org/index.php?q=0043-listen-online

contains a link to:

http://wwuh.org/wwuh.asx

Which points at the link mentioned in this ticket's title.

That it works in mplayer tells me there is probably some way to handle it with a slightly better user experience (unless mplayer is doing something ugly for `mms://` to work properly?

**Comment by wm4** [comment]
MPlayer has its own mms implementation (and it doesn't use rtsp - AFAIK rtsp is a completely different protocol, and I don't know why mc4man knew it'd work). It's possible that the ffmpeg mms implementation has a bug or so.

**Comment by jmesmon** [comment]
@wm4 I'd hesitate to call a piece of code that causes something to work as expected "bug" without examining it a bit.

That said: perhaps what is happening here is that mpv assumes mms is over UDP and never falls back to TCP (as some references on the internet I've read seem to imply should happen). I presume `mmst://` simply means use TCP unconditionally.

Maybe the solution here is just to have timeouts for `mms://` try `mmst` and `mmsh` in sequence after `mmsu`?

**Comment by mc4man** [comment]
My virtually non existent knowledge here would be assuming mms:// is generic > player detect the  transport layer, mmsh (http),  mmst (tcp), mmsu (udp)
As far as rtsp I thought it was the replacement for mms

**Comment by wm4** [comment]
>My virtually non existent knowledge here would be assuming mms:// is generic > player detect the transport layer, mmsh (http), mmst (tcp), mmsu (udp)

Right. I think I remember now. FFmpeg does not support automatically selecting the right protocol, and has them all separately. mpv just redirects mms to mmsh. The only other thing mpv does is redirecting http to mmsh _if_ the server serves a non-sensical playlist over http.

Actually, wikipedia says:

>As of 2012 Microsoft still recommends[1] using "mms://" as a "protocol rollover[2] URL". As part of protocol rollover a Windows Media Player version 9, 10, or 11 client opening an "mms://" URL will attempt to connect first with RTSP over UDP and if that fails it will attempt RTSP over TCP. After an RTSP attempt fails, Windows Media Player versions 9 & 10 will attempt MMS over UDP, then MMS over TCP.[3] If using Windows Media Player 11 and an RTSP attempt fails, or if using a previous version of Windows Media Player and MMS fails, a modified version of a HTTP over TCP connection will be attempted. This modified version is referred to by some third parties as MMSH,[4] and by Microsoft as MS-WMSP (Windows Media HTTP Streaming Protocol).[5] The URI scheme "mms://" has also been proposed to be used for the unrelated Multimedia Messaging Service (MMS) protocol.[6]

FFmpeg does not support this.

Wikipedia also says:

>Microsoft deprecated MMS in favor of RTSP (TCP/UDP port 554) in 2003 with the release of the Windows Media Services 9 Series, but continued to support the MMS for some time in the interest of backwards compatibility. Support for the protocol was finally dropped in Windows Media Services 2008.[1]

So I don't see any reason to even support it, unless there are a lot of mms URLs out there that use rtsp (in which case mms should redirect to rtsp).

**Comment by mc4man** [comment]
I'd just leave alone & to user to try different if mms (mmsh) doesn't work. I don't use these streams personally but a quick test of a dozen randomly chosen that can work suggests sometimes mms(h) is correct, sometimes mmst. Many mmst work also work  with rtsp & show a much cleaner console output but not always.
