### ISSUE TITLE
Feature Request - Scroll Button

### ISSUE THREAD

**Issue by es0phagus** [mpv-player/mpv#1777]
Currently, the middle scroll button on the mouse seeks the timeframe and it is very easy to do this by accident. Could it be made to control the volume instead?

**Comment by lachs0r** [comment]
You can change this behavior in `input.conf`.

**Comment by es0phagus** [comment]
Sorry, where is that located?

**Comment by avih** [comment]
> Sorry, where is that located?

http://mpv.io/manual/stable/#files


> Can I also change the player to save the file position upon closing by default?

http://mpv.io/manual/stable/#options-save-position-on-quit

**Comment by es0phagus** [comment]
Thank you.

Unfortunately, I am a complete noob to this completely. I have managed to find the /usr/local folder but it is empty. 
![screen shot 2015-04-06 at 17 29 07](https://cloud.githubusercontent.com/assets/11819257/7007508/804ced50-dc82-11e4-8078-41e4f819c58d.png)

**Comment by Argon-** [comment]
You don't need /usr/local.
https://coalgirls.wakku.to/faq/playback/compiling-mpv-on-mac-os-x See section "Configuration" for the necessary file locations. We are dealing with invisible folders (names starting with .) here. In case you are uncomfortable with the Terminal there are programs like TextWrangler which might make this easier for you (IIRC it has options to display invisible files in save/open dialogs).

You can create the necessary directory with `mkdir -p ~/.config/mpv` and the needed files with `touch ~/.config/mpv/mpv.conf ~/.config/mpv/input.conf` in Terminal. After that you can enter this directory with Finder by using the "Go to Folder" option and entering `~/.config/mpv` there. If you remember the shortcut for "Go To Folder" you can use this function in regular GUI text editor save/open dialogs too (it also features tab completion).

Now use e.g. TextEdit and edit `mpv.conf`. Add:

    save-position-on-quit
    ontop

See http://mpv.io/manual/master/#options-ontop for more other options.
`input.conf` contains key bindings. Add:

    MOUSE_BTN3 add volume 2
    MOUSE_BTN4 add volume -2

Of course you can change the value for bigger/smaller steps.
You can take a look at my slightly commented [mpv.conf](https://gist.github.com/Argon-/cd5f33329f4f1f44f9f9), maybe you discover some useful options (but better stay away from my video configuration unless you know what it means).
