### ISSUE TITLE
Question: options for fastest video decoding?

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1778]
I'm running secondary mpv client to show video preview in seek bar in my application.
The size of preview is very small (height <= 100), so **the output quality doesn't matter**.

For now, I'm applying next options:

* `hwdec=no`
* `softvol=yes`
* `mute=yes`
* `aid=no`
* `sid=no`
* `audio-file-auto=no`
* `sub-auto=no`
* `osd-level=no`
* `quiet=yes`
* `audio-pitch-correction=no`
* `ao=null`
* `pause=yes`
* `keep-open=always`
* `vd-lavc-skiploopfilter=all`

I've searched the document with 'speed'/'performance'/'fast' but I couldn't find any other options related with performance except `vd-lavc-skiploopfilter`.
However, I may have overlooked some options.

Any suggestion for fast video decoding would be helpful. Thank you.

**Comment by lachs0r** [comment]
Can’t really do it much faster for this use case. But you should probably disable hr seeking.

**Comment by xylosper** [comment]
@lachs0r 
Ah, I'm using `seek` command with `keyframes` option.
Does `hr-seek=no` still impact on perforamce in this case?

**Comment by pigoz** [comment]
You probably want to to use `audio=no` instead of `ao=null`

**Comment by xylosper** [comment]
Is aid=no different from audio=no?

**Comment by haasn** [comment]
Most of those seem redundant. I would just use ```--no-config --no-audio --no-sub --pause```.

**Comment by xylosper** [comment]
@haasn 

AFAIK, effectively --no-config is set in client API.

Is `no-audio` different from `aid=no`(and no-sub from sid=no)?
It's not possible to set --no-audio because the client API does not accept neither of audio=no nor no-audio=yes.

Also, the document says --no-audio may not work with some demuxers and recommends --ao=null in that case. That's why I added ao=null. If ao=null is redundant, maybe the document is outdated?

**Comment by kevmitch** [comment]
``vd-lavc-fast`` was mentioned on irc earlier today. ``softvol``, if anything would reduce performance because it inserts a filter, however with ``--no-audio`` already mentioned above, I imagine it has no effect.

**Comment by wm4** [comment]
> the document says --no-audio may not work with some demuxers and recommends --ao=null in that case.

This is probably outdated. MPlayer's demuxer often had a problem in this mode, and sometimes FFmpeg's demuxers break too. (The latter are bugs that should be fixed, like it happened to the flv demuxer once.)

``--no-audio`` is basically just an alias for ``--aid=no``.

**Comment by xylosper** [comment]
@kevmitch 

I've excluded `vd-lavc-fast` because the document says `Enable optimizations which do not comply with the format specification and potentially cause problems`, and I assumed that the problem contains failure of decoding/displaying video frame. Is it always safe to apply `vd-lavc-fast`?

@wm4 

Thank you for clarifying.

**Comment by wm4** [comment]
>Is it always safe to apply vd-lavc-fast?

Quite obviously it is not. It makes the decoder do non-standard things. I'm not sure, but if it's true to its description, it might be even full of security issues. Like with all ffmpeg things that are used mostly by mplayer only, they're probably also broken.

**Comment by xylosper** [comment]
@wm4 
Thank you again.

I think I got all answers I can get. Thanks to everyone who replied.

**Comment by earthwlove** [comment]
--vd-lavc-threads=1

This option gives an extremely high boost to the decode speed.
I turn on all options without this one, and It seems just this option gives the desired effect and all others seem to be placebo.
