### ISSUE TITLE
Video freezing on second monitor in OS X under fairly specific circumstances.

### ISSUE THREAD

**Issue by filchermcurr** [mpv-player/mpv#1781]
I'm not even sure how to describe this. The primary monitor has, say, a Terminal window open and expanded to fill all the available space. When the Terminal window is expanded, any video playing in fullscreen on the second monitor will freeze. The audio continues to play but the video does nothing.

If you resize the Terminal window a bit to the right, the video will resume playing on the second monitor. The attached screenshot shows the exact size a window has to be on the primary monitor before anything will play fullscreen on the second monitor. Any farther to the left and it freezes.

My mpv configuration is all defaults. Both monitors are Dell P2415Q's running on an NVidia GTX 970 (with Nvidia web driver 346.01.01f01 installed) . Running OS X 10.10.2 and mpv 36ae8a6 (but it also occurs on the stable version that Homebrew installs). 

mpv git-36ae8a6 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-04-08T01:39:13
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100

![mpv](https://cloud.githubusercontent.com/assets/11351104/7039147/ed58aafa-dd82-11e4-9047-9b7ee3c23e3d.png)

**Comment by pigoz** [comment]
This is quite odd

**Comment by filchermcurr** [comment]
I've been messing around with it to try to find something that causes it, but so far my ridiculous ideas have been unfruitful. The only concrete information I have is that it works as expected right after a reboot (or, as I discovered when I killed windowserver, a logout). I open all of my regular applications and it still works, so if there is an interaction there it doesn't occur until the applications do something later on. I haven't nailed down an exact timeframe for when it stops working.

Also, it seems to continue working if you leave a video open after rebooting. It plays back fine, but as soon as you quit and open another video, the problem surfaces and it won't play fullscreen without the mpv window having focus.

Another very minor discovery is that the window on the main monitor doesn't have to be maximized, it just has to avoid that inch or whatever of space toward the left of the monitor. So anything in that small chunk of space will interfere with playback.

Anyway, ridiculous things that don't seem to make a different in no particular order: Starting playback with the play key instead of having the window in focus, disabling transparency in Yosemite, the screen saver coming on, the screen locking, power cycling monitors, changing the retina scaling in display options, or deleting any of the mpv save states that OS X creates. Also switching the main monitor from right to left just reverses the issue.

Is there anything I can do to help diagnose the cause of this? Maybe something more concrete than my blindly bashing on things hoping for an effect?

**Comment by filchermcurr** [comment]
I think I've found a workaround. It's been working pretty consistently so far, anyway. If you launch mpv from the command line, move the video window to the second monitor, and then full screen it from the Terminal window, it will play normally (assuming you start playback from the Terminal window or using the play key on the keyboard). But if you ever focus the video window directly to control playback, once you bring something else into focus that is occupying that sliver of space on the main monitor it will freeze the video. (If it's helpful, the HUD will also freeze in whatever state of animation it's at when it loses focus. So it looks like something is just grabbing a static shot of the screen and leaving it there.)

I don't know if this gives a hint to the problem, or if it even made sense, but if anybody is experiencing similar issues it should be a good enough workaround for now.

(Also, just to make sure I'm not crazy, I tried mplayer and VLC and they both played fine. So it definitely looks like something weird going on with mpv.)

**Comment by pigoz** [comment]
This happens only with Terminal.app? No other applications? What about iTerm2?

Sorry but this is impossible for me to even attempt to reproduce (I don't have double monitor), and from your description I really have no idea where the issue is. It looks like a deadlock, but it's very strange it happens depending on interaction with other applications.

**Comment by Argon-** [comment]
I tried to reproduce it but I don't really understand which steps are the ones leading to the problem and which are fine. Also, what is
> that sliver of space on the main monitor

?

Could you provide step by step instructions?

**Comment by filchermcurr** [comment]
Sorry, I'll try to explain it more clearly.

In the screenshot above, I refer to the section of desktop that is showing as the "sliver". That's the area on the main monitor that has to remain clear for mpv to work in fullscreen on the second monitor.

So to reproduce it:
1. Open any video and drag it to the second monitor.
2. Fullscreen it on that monitor (either using F or double clicking)
3. Begin playback.
4. Alt-tab or click another window on the main display.
5. Drag any window into "the sliver".

To reproduce the workaround:
1. Open any video from the command line and drag it to the second monitor.
2. Switch back to the prompt and fullscreen it from there with the F key.
3. Begin playback from the prompt with space bar.

Here's a terrible video to complement my terrible description: https://www.youtube.com/watch?v=cUcETimpZ0s

I never noticed it before, but if you look at the second monitor when the window drags into the "sliver" you can see the video still animating in a tiny spot the size of the window that's being moved.

**Comment by pigoz** [comment]
That's the weirdest bug I have ever seen. I am not even sure if it's our fault.

**Comment by Argon-** [comment]
Just to be sure:
4+5. I click into the toolbar area of a program and drag it around? And this has nothing to do with the menu bar?
![screenshot](https://cloud.githubusercontent.com/assets/540920/7255952/e1861ff8-e84c-11e4-8065-a0c4e469b876.png)

**Comment by filchermcurr** [comment]
Right, dragging by the tool bar.

My original thought was that it was an issue with the Nvidia web drivers, which are separate from the drivers Apple ships. But when mplayer and VLC both worked in fullscreen my confidence in that theory faded a little. But not entirely!

**Comment by Argon-** [comment]
Sorry, can't reproduce this error. I'm using a ATI GPU though.
