### ISSUE TITLE
Failed to select Audio track

### ISSUE THREAD

**Issue by xswqaz** [mpv-player/mpv#1782]
Sometime Failed to select Audio track even though contains Audio track in mp4
After select audio track manually , Sounds normally

**Comment by wm4** [comment]
Log?

**Comment by xswqaz** [comment]
[ffmpeg/audio] aac: Sample rate index in program config element does not match the sample rate index configured by the container.
[ffmpeg/audio] aac: Inconsistent channel configuration.
[ffmpeg/audio] aac: get_buffer() failed
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
[ffmpeg/audio] aac: Sample rate index in program config element does not match the sample rate index configured by the container.
[ffmpeg/audio] aac: Inconsistent channel configuration.
[ffmpeg/audio] aac: get_buffer() failed
Error decoding audio.
[ffmpeg/audio] aac: Inconsistent channel configuration.
[ffmpeg/audio] aac: get_buffer() failed
Error decoding audio.
Error initializing audio.

Audio: no audio
V: 00:00:02 / 00:43:59 (0%) Cache:  2s+33164KB

**Comment by wm4** [comment]
What file format? mp4? Seems like this is either a broken file, or a ffmpeg bug or unsupported feature. Can you upload a sample file somewhere?

If it actually works when trying to select it again, then it's possible that the audio stream behaves better later into the file (but this is strange).

**Comment by xswqaz** [comment]
https://onedrive.live.com/redir?resid=9545365122224cb7%21116

**Comment by wm4** [comment]
Thanks, downloading.

**Comment by wm4** [comment]
Reported as https://trac.ffmpeg.org/ticket/4460

I tried to take a look, but I have no clue what's going on there after all.

**Comment by wm4** [comment]
PS: works with Libav.

**Comment by wm4** [comment]
Do you know how this file was created?

**Comment by mc4man** [comment]
mpv would likely play the sound of that crappy file with something like this (assuming ffmpeg used is fdkaac enabled - 
mpv --ad=lavc:libfdk_aac --audio-channels=2  
(reports 33 channels so needs to be told 2

**Comment by xswqaz** [comment]
I created mp4 from ts with option below
-acodec copy -bsf aac_adtstoasc

**Comment by wm4** [comment]
It was fixed in ffmpeg git master.

**Comment by xswqaz** [comment]
After what revision?

**Comment by wm4** [comment]
>I created mp4 from ts with option

Did the original ts play? Does it play now?

**Comment by xswqaz** [comment]
ts was no problem
I'm using homebrew ffmpeg 2.6.1 now in OSX.
I'll try it in next version

**Comment by xswqaz** [comment]
I upgraded ffmpeg 2.6.2
But, problem still exist
