### ISSUE TITLE
[Feature Request] Shortcut to loop the current file again.

### ISSUE THREAD

**Issue by johncmouser** [mpv-player/mpv#1784]
When running `mpv --shuffle *` sometimes I come across a song that I rather like and would like to hear it again after it's done playing. I believe that a capital `L` would be fit shortcut for this feature. Just press `L` and mpv will queue up the same song immediately.

I don't know if this is achievable with Lua API or not. If it is, some pointers would be nice.

Thanks,
John

**Comment by swiniopas** [comment]
```L set loop-file inf```
in your input.conf

**Comment by wm4** [comment]
@johncmouser: does this work for you?

**Comment by johncmouser** [comment]
Thanks guys that was just what I needed.

I now use `L cycle loop-file 1` in my `input.conf`. Now every time I press `L` it queues the song to play once more, then resets once the song is finished.

Thanks for the fast help. :grinning:

**Comment by hihihippp** [comment]
Current document: 
[input.conf](https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L146)
it is not:
`#L cycle-values loop "inf" "no" # toggle infinite looping(not work)`
it should be:
`L cycle_values loop-file inf no`
as @swiniopas said above.

**Comment by wm4** [comment]
?

**Comment by kevmitch** [comment]
both work for me. They should be equivalent.
