### ISSUE TITLE
show proper name on the OSD for youtube videos

### ISSUE THREAD

**Issue by r8b7xy** [mpv-player/mpv#1785]
When I play youtube videos in mpv and press "I" to show filename on the OSD, the video name which appears is just part of the url even if the title for the window matches the youtube video name.
![image](http://i.imgur.com/8YxEkud.png)

**Comment by wm4** [comment]
This can be done with ``${mediatitle}`` instead of ``${filename}``. Maybe it would be a good idea to change this.

**Comment by r8b7xy** [comment]
How to change this value?
Thanks in advance.

**Comment by r8b7xy** [comment]
I've changed line in input.conf to 'I show_text "${mediatitle}"' and now mpv shows (error) when I press 'I'.

**Comment by r8b7xy** [comment]
'I show_text "${media-title}' works like a charm. 
Thanks for your help. It should be included in man btw.
