### ISSUE TITLE
Pass-through is not working under OSX with TC Impact Twin soundcard

### ISSUE THREAD

**Issue by werdy77** [mpv-player/mpv#1790]
Trying to play an MKV video with DTS audio passed through SPDIF but MPV says it is not supported by this device:

<pre><code>[ad] Codec list:
[ad]     spdif:dts - libavformat/spdifenc audio pass-through decoder
[ad]     lavc:dca (dts) - DCA (DTS Coherent Acoustics)
[ad] Opening audio decoder spdif:dts
[ad] Selected audio codec: libavformat/spdifenc audio pass-through decoder [spdif:dts]
[cplayer] Starting playback...
[af] Audio filter chain:
[af]   [in] 48000Hz stereo 2ch spdif-dts
[af]   [out] 48000Hz stereo 2ch spdif-dts
[af]   [ao] 48000Hz stereo 2ch spdif-dts
[ao] Trying preferred audio driver 'coreaudio'
[ao] Using preferred device 'TCNearAudioEngine:0'
[ao/coreaudio] requested format: 48000 Hz, stereo channels, spdif-dts
[ao/coreaudio] detected IEC61937, redirecting to coreaudio_exclusive
[ao/coreaudio_exclusive] requested format: 48000 Hz, stereo channels, spdif-dts
[ao/coreaudio_exclusive] selected audio output device: TC Near (38)
[ao/coreaudio_exclusive] supported format: 192000.0Hz 24bit [1819304813][14][42][1][42][14] int BE S packed
[ao/coreaudio_exclusive] supported format: 176400.0Hz 24bit [1819304813][14][42][1][42][14] int BE S packed
[ao/coreaudio_exclusive] supported format: 96000.0Hz 24bit [1819304813][14][42][1][42][14] int BE S packed
[ao/coreaudio_exclusive] supported format: 88200.0Hz 24bit [1819304813][14][42][1][42][14] int BE S packed
[ao/coreaudio_exclusive] supported format: 48000.0Hz 24bit [1819304813][14][42][1][42][14] int BE S packed
[ao/coreaudio_exclusive] supported format: 44100.0Hz 24bit [1819304813][14][42][1][42][14] int BE S packed
[ao/coreaudio_exclusive] selected device doesn't support digital formats
[ao] Failed to initialize audio driver 'coreaudio'
[ao] This audio driver/device was forced with the --audio-device option.
[ao] Try unsetting it.
[cplayer] Could not open/initialize audio device -> no sound.
[ad] Uninit audio filters...
[ad] Uninit audio decoder.
[cplayer] Audio: no audio</pre></code>

The same video can be played by MplayerX (with pass-through).

I'm using [ChrisK's](http://sva.wakku.to/~chris/mpv_builds/) latest build.

<pre><code>[cplayer] mpv git-5574820 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[cplayer]  built on 2015-04-07T15:54:46</pre></code>

Why MPV think that this soundcard is not support digital output? As a fallback option it should play digital stream via the default 48000.0Hz 24bit audio channel. Please help as otherwise MPV is working great and I would like to use it as my default player. Thanks!

**Comment by wm4** [comment]
Technically, it contains this code:
```
    case 'IAC3':
    case 'iac3':
    case  kAudioFormat60958AC3:
    case  kAudioFormatAC3:
```
And the format which this device supports (``1819304813``) is not one of these.

Taking a quick look at mplayer code, it seems to do the same though.

It's possible that mplayerx was patched.

>As a fallback option it should play digital stream via the default 48000.0Hz 24bit audio channel

There's no fallback. Well, normally you shouldn't need once, so it's probably better if it fails hard if passthrough doesn't work. We're not sure.

**Comment by wm4** [comment]
Can you post a log when playing passthrough with mplayerx? Maximum verbosity, if possible.

**Comment by werdy77** [comment]
Only the audio section:

<pre><code>Forced audio codec: hwac3
Forced audio codec: hwdts
Opening audio decoder: [hwac3] AC3/DTS pass-through S/PDIF
dec_audio: Allocating 8192 bytes for input buffer.
dec_audio: Allocating 16384 + 131072 = 147456 bytes for output buffer.
hwac3: switched to DTS, 1536000 bps, 48000 Hz

ac3dts: DTS len=2012  flags=0x0  48000 Hz 1536000 bit/s
AUDIO: 48000 Hz, 2 ch, ac3le, 1536.0 kbit/100.00% (ratio: 192000->192000)
Selected audio codec: [hwdts] afm: hwac3 (DTS through S/PDIF)
Building audio filter chain for 48000Hz/2ch/ac3le -> 0Hz/0ch/??...
[libaf] Adding filter dummy 
[dummy] Was reinitialized: 48000Hz/2ch/ac3le
[dummy] Was reinitialized: 48000Hz/2ch/ac3le
Trying preferred audio driver 'coreaudio', options 'device_id=38'
AO: [coreaudio] init([48000Hz][2ch][ac3le][0])
AO: [coreaudio] got audio output device ID: 38 Name: TC Near
AO: [coreaudio] supported format: 192000.0Hz 24bit [lpcm][14][42][1][42][14] int BE S packed
AO: [coreaudio] supported format: 176400.0Hz 24bit [lpcm][14][42][1][42][14] int BE S packed
AO: [coreaudio] supported format: 96000.0Hz 24bit [lpcm][14][42][1][42][14] int BE S packed
AO: [coreaudio] supported format: 88200.0Hz 24bit [lpcm][14][42][1][42][14] int BE S packed
AO: [coreaudio] supported format: 48000.0Hz 24bit [lpcm][14][42][1][42][14] int BE S packed
AO: [coreaudio] supported format: 44100.0Hz 24bit [lpcm][14][42][1][42][14] int BE S packed
AO: [coreaudio] probe default audio output device about support for digital s/pdif output: 0
AO: [coreaudio] source: 48000.0Hz 16bit [lpcm][12][4][1][4][2] int LE S packed
AO: [coreaudio] using   375 chunks of 512 bytes (buffer len 192000 bytes)
AO: [coreaudio] 48000Hz 2ch ac3le (2 bytes per sample)
AO: Description: Darwin/Mac OS X native audio output
AO: Author: Timothy J. Wood & Dan Christiansen & Chris Roccati
Building audio filter chain for 48000Hz/2ch/ac3le -> 48000Hz/2ch/ac3le...
[dummy] Was reinitialized: 48000Hz/2ch/ac3le
[dummy] Was reinitialized: 48000Hz/2ch/ac3le</code></pre>

**Comment by pigoz** [comment]
Ok, mplayer goes on even without passthrough support advertised by the device. It looks like XBMC does a better job in identifing an additional passthrough format which incidentally matches this case:

https://github.com/xbmc/xbmc/blob/master/xbmc/cores/AudioEngine/Sinks/osx/AEDeviceEnumerationOSX.cpp#L116

**Comment by werdy77** [comment]
What would be the best solution? Using XMBC solution or add an extra switch to force passthrough?

**Comment by pigoz** [comment]
We should allow something like xbmc case with an additional switch I think. Having it as default is rather scary.

**Comment by werdy77** [comment]
I don't really see the scarcity of playing digital signal (noise) on audio channel (if the audio system is not support processing of this signal at all). The program should not think instead of the user (or be more intelligent). In worst case the user will hear this noise instead of nothing. At least he will know that the program do what he wanted.

**Comment by wm4** [comment]
Thinking of adding an extra option for this, because apparently Hackintoshes do not signal digital formats at all.

But what confuses me is that your device reports 24 bit formats only?

**Comment by Dudemanguy** [comment]
Please open a new issue if this is still a problem on 0.36.
