### ISSUE TITLE
Start at specific position in playlist

### ISSUE THREAD

**Issue by Kagami** [mpv-player/mpv#1791]
Hi. I would like to have an option to start watching playlist at a specific position.

My use case: I periodically play videos from youtube channels with mpv and after closing mpv I need to manually rewind watched videos with `playlist_next` command. Would be great to have some option like:

``` bash
$ mpv --playlist-position=10 https://youtube.com/channel/something/videos
```

I know I can save position at playlist with `Shift+Q` but I don't always remember about it and also it may be useful to start new playlist at specific position (e.g. I found some playlist with youtube's web interface and don't want to watch the first 10 videos because of their thumbnails/names). Rewinding a lot of videos is not so fast and cause some lags in case of remote video sources.

Sorry if it was already requested but I haven't found similar issue.

**Comment by ParadoxSpiral** [comment]
You can pass the playlist-start option to ytdl via the ytdl-raw-options option.

Example: 
```bash
$ mpv -ytdl-raw-options=playlist-start=64 -ytdl https://www.youtube.com/playlist?list=PL1bauNEiHIgyHtNfI-eIZDUfkNlz_TL2Z
```

**Comment by Kagami** [comment]
@ParadoxSpiral oh, thanks, I didn't know about this option (it was in git version). It works like I expected so this issue may be closed unless @wm4 thinks this option still may be useful for mpv.

Btw, little quirk with playlist-start: I can't go backward to skipped videos with `playlist_next`.

**Comment by ponyo** [comment]
It would be better if you could go fast with playlist_prev playlist_next. Why isnt there any key repeat action happening.

**Comment by wm4** [comment]
>Why isnt there any key repeat action happening.

Because then the high key repeat rate (with the low activation delay) would probably advance more than what the user intended.

**Comment by lachs0r** [comment]
A proper option (`--playlist-pos`) has been added with 602105dbdae5b35dfcd7c060349b42a990bd25a8 and later renamed to `--playlist-start` with 9e972ed7d28c33bf612452682f229fa14ef017ea.

**Comment by con-f-use** [comment]
Sorry for issue necro, but is there a keyboard shortcut inside mpv or some mechanism of selecting a video.
I'm tired of hitting enter a bunch of times and overshoot in half the cases because of latency.

**Comment by guidocella** [comment]
> Sorry for issue necro, but is there a keyboard shortcut inside mpv or some mechanism of selecting a video.

You can use a keybinding like `g script-message-to console type "set playlist-pos-1 "`
