### ISSUE TITLE
Filename Expansion — Screenshots

### ISSUE THREAD

**Issue by Yomi0** [mpv-player/mpv#1794]
If you playback a few files like this ``» mpv --profile=hw.accel --hwdec=auto ~/Downloads/\[HorribleSubs\]\ Durarara\!\!\ X2\ -\ 12\ \[720p\].mkv ~/Downloads/\[HorribleSubs\]\ Saekano\ -\ {11,12}\ \[720p\].mkv``

The screenshots will be created like this : 
\[HorribleSubs\]\ Durarara\!\!\ X2\ -\ 12\ \[720p\]_0001.jpg
\[HorribleSubs\]\ Durarara\!\!\ X2\ -\ 12\ \[720p\]_0002.jpg
\[HorribleSubs\]\ Durarara\!\!\ X2\ -\ 12\ \[720p\]_0003.jpg
\[HorribleSubs\]\ Durarara\!\!\ X2\ -\ 12\ \[720p\]_0004.jpg
\[HorribleSubs\]\ Durarara\!\!\ X2\ -\ 12\ \[720p\]_0005.jpg
\[HorribleSubs\]\ Durarara\!\!\ X2\ -\ 12\ \[720p\]_0006.jpg
\[HorribleSubs\]\ Durarara\!\!\ X2\ -\ 12\ \[720p\]_0007.jpg
\[HorribleSubs\]\ Durarara\!\!\ X2\ -\ 12\ \[720p\]_0008.jpg
\[HorribleSubs\]\ Saekano\ -\ 11\ \[720p\]_0009.jpg
\[HorribleSubs\]\ Saekano\ -\ 11\ \[720p\]_0010.jpg
\[HorribleSubs\]\ Saekano\ -\ 11\ \[720p\]_0011.jpg
\[HorribleSubs\]\ Saekano\ -\ 11\ \[720p\]_0012.jpg
\[HorribleSubs\]\ Saekano\ -\ 11\ \[720p\]_0013.jpg
\[HorribleSubs\]\ Saekano\ -\ 11\ \[720p\]_0014.jpg
\[HorribleSubs\]\ Saekano\ -\ 12\ \[720p\]_0015.jpg
\[HorribleSubs\]\ Saekano\ -\ 12\ \[720p\]_0016.jpg
\[HorribleSubs\]\ Saekano\ -\ 12\ \[720p\]_0017.jpg

Shouldn't the count start from 0000 again, since the file has changed?

**Comment by wm4** [comment]
This isn't the default screenshot template, and you didn't show your custom one, so I can't say anything.

**Comment by Yomi0** [comment]
This is my screenshot template : screenshot-template=~/Pictures/%F_%n

**Comment by Yomi0** [comment]
Ping.

**Comment by wm4** [comment]
Add ``#`` before the ``n``. The manpage says:
```
        With
        the optional # sign, mpv will use the lowest available number. For
        example, if you take three screenshots--0001, 0002, 0003--and delete
        the first two, the next two screenshots will not be 0004 and 0005, but
        0001 and 0002 again.
```
