### ISSUE TITLE
--video-stereo-mode mode does nothing

### ISSUE THREAD

**Issue by blendi-93** [mpv-player/mpv#1795]
i want to watch a video but its 3d so i used mpv --video-stereo-mode=mono but the video is still 3d.

**Comment by wm4** [comment]
Needs a sample file.

**Comment by blendi-93** [comment]
this one is 2gb, to big i think ;)

**Comment by blendi-93** [comment]
samplefile:

 https://transfer.sh/Q0uQT/sample.mkv

**Comment by wm4** [comment]
This file doesn't have any metadata that says it's 3D, so the player can't do anything magical about it. It assumes the file is mono, and can't know that this is not correct. The --video-stereo-mode option affects output, not input.

I would consider this a broken file.

You can achieve mono display with ``--vf=stereo3d:in=sbs2l:out=mono``.
