### ISSUE TITLE
Minimize Bug

### ISSUE THREAD

**Issue by es0phagus** [mpv-player/mpv#1796]
When mpv is minimized and then reopened the video no longer shows even though the app is active.

![screen shot 2015-04-11 at 20 17 08](https://cloud.githubusercontent.com/assets/11819257/7102861/3a51e436-e088-11e4-8233-06ab10fb1da1.png)

![screen shot 2015-04-11 at 20 19 03](https://cloud.githubusercontent.com/assets/11819257/7102860/3a4eef4c-e088-11e4-8f32-891e3ecd909b.png)

**Comment by es0phagus** [comment]
I just did a quick look of this forum and it is this exact bug: https://github.com/mpv-player/mpv/issues/1757 (probably should have searched first).

**Comment by wm4** [comment]
Yeah, probably a duplicate.
