### ISSUE TITLE
Key binding to enable and disable opengl smooth motion

### ISSUE THREAD

**Issue by kufii** [mpv-player/mpv#1797]
Is it possible to add a key binding to enable and disable smooth motion? if not, is this a feature that could be added?

**Comment by wm4** [comment]
Currently there's nothing, except the vo_cmdline command, which resets the parameters after ``--vo=opengl:....``.

**Comment by kufii** [comment]
and there's no way to change that flag when mpv is running?

**Comment by wm4** [comment]
No, only with vo_cmdline.

**Comment by lachs0r** [comment]
This works now.

**Comment by wiiaboo** [comment]
Example: `H      cycle-values interpolation no yes; show-text "${?=interpolation==yes:Interpolation enabled}${?=interpolation==no:Interpolation disabled}"`

**Comment by Hrxn** [comment]
I didn't test this, but I think `<key> cycle interpolation` should work as well, I assume..
