### ISSUE TITLE
MPV HTTP stream

### ISSUE THREAD

**Issue by TheChymera** [mpv-player/mpv#1799]
What is the recommended way to play a http stream with mpv?

In mplayer that would hev been, eg:

```
mplayer -nocache http://localhost:8000/mpd.mp3
```

but mpv does not have a nocache option.

**Comment by wm4** [comment]
Why do you think you need -nocache?

Just passing the URL to mpv should work.

**Comment by wm4** [comment]
Anyway, mpv understand ``--no-cache`` - this is a very consistent change in naming conventions.

You never told us the actual problem, so I'm closing this.

**Comment by TheChymera** [comment]
I was asking because I am trying to use this with gmpc and a remote mpd server broadcasting to http- Indeed it turns out simply:

```
mpv http://localhost:port/mpd.mp3
```

works. Many thanks for your help!
