### ISSUE TITLE
A property or command to retrieve screenshot data in memory

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1800]
For now, I can get screenshot data by taking screenshot using `screenshot_to_file` and read  the written file back into memory.
This is extremely inefficient because this process contains unnecessary compressing/decompressing image data from/to file.
This work is expensive enough to freeze playback for a second with high-res video.

As a client user, it would be really convenient if I can get screenshot data into memory directly.

**Comment by wm4** [comment]
Any suggestions how to achieve this? There are two problems:

1. the client API has no mechanism to retrieve bulk data
2. image data representation

**Comment by xylosper** [comment]
For 1, what about hand over pointer value of buffer through mpv_node? This requires a new format type for uintptr_t or uint64_t. Or, you can give the address in string format. For instance,
```
mpv_node_list *list = talloc_zero(NULL, mpv_node_list);
mp_image *img = talloc_steal(list, get_screenshot(...));
mpv_node node = {
    .format = MPV_FORMAT_NODE_MAP,
    .u.list = list
};

// fill node with img, for instance, pesudo code:
list["data"][i] =pointer_to_string(img->planes[i]); // or add uint64_t to format
list["stride"][i] =img->stride[i]; // or add uint64_t to format
list["width"] = img->w;
...
```
If I'm right, the image data will be freed when the node is freed.
I think this is most simple way not to change the API considerably.

For 2, I think IMGFMT_RGBA(or BGRA?) is most useful and it would be enough but if you want to take some general way, you can specify format in node, too.
If you enfoce the format as some kind of rgba type, you can omit other plane data/strides.
Eventhough the user didn't want IMGFMT_RGBA, it would be much faster to convert the format in client side than save and load image file.

**Comment by wm4** [comment]
Would it help if mpv could compress and write the screenshot asynchronously?

**Comment by xylosper** [comment]
Well, if you confine the usage to my case, that would be fine because I'll save it somewhere else eventually, but IMHO, that's another feature.
Also in that case, I think the command should allow to overwrite image file becuase it's difficult to gaurantee that a file does not exist asynchronously.

**Comment by wm4** [comment]
>I think the command should allow to overwrite image file

That's a good idea in its own right. The screenshot_to_file command always takes a full filename, so there's no reason why we should refuse to overwrite an already existing file with it.

**Comment by wm4** [comment]
I made an experimental commit in a branch: https://github.com/mpv-player/mpv/commit/6fdbb11d8f9fedbe8da9647a7c7bf63f27907749

Would this work for you? I'm not quite sure whether I like this.

**Comment by xylosper** [comment]
Finally we can use mpv_command_node :)
I've tested and it works fine here.  Thank you!

**Comment by xylosper** [comment]
```
struct mp_image *screenshot_get_rgb(struct MPContext *mpctx, int mode)
{
    struct mp_image *mpi = screenshot_get(mpctx, mode);
    struct mp_image *res = convert_image(mpi, IMGFMT_BGR0, mpctx->log);
    talloc_free(mpi);
    return res;
}
```

Here, it's allowed screenshot_get to return null pointer for failure and in that case, it will make application crashed without null pointer check.
