### ISSUE TITLE
format=colormatrix doesn't change the colormatrix property

### ISSUE THREAD

**Issue by pcordes** [mpv-player/mpv#1804]
input.conf:
```
c vf toggle format=colormatrix=bt.709; show_text ${colormatrix}
# C vf toggle format=colormatrix=bt.601
ctrl+c show_text ${colormatrix}
```

The show_text output is always whatever mpv decided to default to, based on the current file, not what the vo is actually using.

TYVM for pointing out that there's no functionality loss thanks to runtime filter toggling in the commit message for the colorspace change!  I didn't realize it was this easy to toggle filters, and how well it would work.  I used to have a cycle colormatrix forward/back bind, but all I ever used it for was toggling bt.709 on when I realize after playback started that I forgot to start mpv with bt.709.

**Comment by wm4** [comment]
>The show_text output is always whatever mpv decided to default to, based on the current file, not what the vo is actually using.

No, it just happens with a delay. The VO is reconfigured when the next video frame is displayed, which happens after all the commands are run. This was this way with the old property too. So I see no bug here.

By the way, what's the need for changing the colormatrix? Most time it should be correct.

**Comment by pcordes** [comment]
It's pretty common to see files that were downscaled from HD sources, but that don't have colorspace tags.

**Comment by pcordes** [comment]
> No, it just happens with a delay.

Ok, so that rules out my idea of using show_text to get closer to the old OSD behaviour when changing colormatrix.

However, even after a delay, using the ctrl+c keybind to just show the current colormatrix always shows the [in] format, not the current [out] format.

**Comment by wm4** [comment]
Yes, the property is before-filters. Use ``video-out-params/colormatrix``.

**Comment by pcordes** [comment]
Thanks for the help.  Sorry for the non-bug report >.<

```
c vf toggle format=colormatrix=bt.709; show_text ${video-out-params/colormatrix}
```

actually updates fast enough to display the new value after toggling, even when paused.  (on vo=opengl-hq)

**Comment by sergeevabc** [comment]
Err… I applied the solution which @pcordes was satisfied with, but am confused with the result. Pressing 'c' to change matrix -> MPV writes bt.601 in upper left corner -> pressing 'i' to get information and there… Filters: format (colormatrix=bt709). You see, the opposite, whereas I expected MPV to write what colormatrix in is use right now.

**Comment by wm4** [comment]
Combining the commands like this doesn't work because the property is only updated once a frame has passed the entire filter chain and was displayed.
