### ISSUE TITLE
scrubbing all the way to the right while paused on h.264 in mp4 shows one-past-last-frame

### ISSUE THREAD

**Issue by pcordes** [mpv-player/mpv#1807]
Ran into this while exploring https://github.com/mpv-player/mpv/issues/1805, but it's a separate issue.  Using git master (HEAD ab2a27ae01c7a739b83601db6548e4b05a8a96cf), built with git master ffmpeg (HEAD 818e8897094d044f80d05eee7a83c9f80a4334a1), Ubuntu 14.10.

 Scrubbing all the way to the right while paused gives input-dependent behaviour:
* on a .mpg: next file / exit
* ifo/dvdnav: back to menu (end-of-title behaviour)
* h.264 in SOME mp4 files shows a gray frame.  framestep-backward shows the actual last frame of the video
* h.264 in other mp4 files: shows last keyframe
* xvid in mp4: shows the last keyframe
* h.264 in mkv shows the last keyframe
* h.265 in mkv shows the last keyframe
* xvid in avi: shows the last keyframe
* wmv shows the last keyframe
* mjpeg shows the last frame (all frames are keyframes)

All tested with software-decoding, vo=opengl-hq.

So there's some weird input-dependent seek behaviour here.  Only the h.264 in .mp4 case is a definite bug, but consistency across demuxers would be nice.  Hmm, and even then, it's not reproducible on every h.264 in mp4 file.  I'll update after more testing.

The inconsistency between mpg and others is real, though.

Also nice would be a seek that never triggers EOF behaviour.  So you could just hold down fastforward to get within a GOP of EOF, without triggering mpv to exit or go to the next file.

Maybe seek_weak, or weak as an option name to seek, to use the same weak/force terminology as playlist_next.

**Comment by wm4** [comment]
Yes, all of this is demuxer dependent. libavformat doesn't even define what happens if a seek fails (which can happen in these situations).

**Comment by pcordes** [comment]
Checking my collection of mp4 files, this one-past-last-frame behaviour seems to happen only with files made by MainConcept, or something that uses that encoder.  Other h.264-in-mp4 files are fine.

ffmpeg -i output on a file that shows this one-past-last frame problem:
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'somefile.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2011-07-11 20:59:10
  Duration: 00:13:56.84, start: 0.000000, bitrate: 5158 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv), 1280x720 [SAR 1:1 DAR 16:9], 4997 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2011-07-11 20:59:13
      handler_name    : Mainconcept MP4 Video Media Handler
      encoder         : AVC Coding
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 157 kb/s (default)
    Metadata:
      creation_time   : 2011-07-11 20:59:22
      handler_name    : Mainconcept MP4 Sound Media Handler

**Comment by wm4** [comment]
Closing because I don't accept the word "scrub" for seeking.

**Comment by pcordes** [comment]
I used "scrub" because I'm talking about the use-case of using the mouse on the position slider for random access to the video.  Is that the wrong term?  If so, what is the proper term for this?
