### ISSUE TITLE
Could there be a UI when playing music?

### ISSUE THREAD

**Issue by netheril96** [mpv-player/mpv#1808]
I am on OS X and set `mpv` as default player for all media types, including video and audio. One annoyance I encounter is that the `mpv.app` playing audio does not any UI. There are no controls and no progress bar. Could this be improved?

**Comment by robin007bond** [comment]
I think this should be the default too. In the meantime, you can put:

`profile=pseudo-gui
In your mpv.conf. Is that the behavior you expected?

**Comment by netheril96** [comment]
@robin007bond 

I added that to the config file

```bash
echo 'profile=pseudo-gui' >> ~/.config/mpv/mpv.conf
```

And nothing changed.

To be clear, there is an app icon on the dock that allows me to issue keyboard commands, but that is the behavior since the last revision. What I want is to see a slider to know how much of the music is left, and be able to drag the slider, as when viewing video with mpv.

**Comment by robin007bond** [comment]
@netheril96 
Hmm, weird. It works as expected in GNU/Linux:

![mpv as music player](https://i.imgur.com/KF2EpcZ.png)

**Comment by AirPort** [comment]
The `pseudo-gui` profile is a recent addition, are you using the HEAD or the release version (0.8.3)? In the latter case `pseudo-gui` will not be recognized as an option, just add `force-window` to your config file to achieve pretty much the same outcome.

**Comment by netheril96** [comment]
@AirPort  @robin007bond 

The works as expected now after I installed the HEAD version instead of release.

**Comment by robin007bond** [comment]
Glad to hear. :+1:

**Comment by sleek22** [comment]
Put the following line in mpv.conf for a gui when playing audio. This is from the mpv manual.

--force-window

**Comment by slrslr** [comment]
It sucks when you can not stop playback or move forward in an audio!
I have looping by default so the playback never end. Not sure why i need to waste time asking at forums to get reply from someone linking me to github, where i need to apply some workaroudn via command line. It is a nonsense to hide the player.
This is one of the small things why people turn away from Linux!

**Comment by CounterPillow** [comment]
@slrslr you're commenting on an issue from 2015 that is no longer even relevant. The pseudo-gui mode is default when launched from any desktop environment, e.g. by double-clicking a file.
