### ISSUE TITLE
HLS playback stoppes if there was missing segments 

### ISSUE THREAD

**Issue by He1my** [mpv-player/mpv#1812]
MPV is behaving very poorly when working with HLS streams if a segment was not available MPV just exists playback where it should retry a couple of times for the missing segment then skip on to the next segment and continue playback

this can be easily tested using a segmented HLS video and deleting some of the segment files while the m3u8 file still have them listed, MPV should not exit playback when it can not find the segment file , it should keep moving on with the time until it finds the next segment available.
i have tested ffplay and it doesn't have this issue and behaves correctly

**Comment by wm4** [comment]
I bet this is a problem with how libavformat signals EOF, and the hacky way ffplay handles EOF. I need a good test case, otherwise I won't care.

**Comment by He1my** [comment]
you can use any HLS test file like the one here 
http://devimages.apple.com/iphone/samples/bipbop/gear2/prog_index.m3u8
download the m3u8 file along with all the 180 file segments (fileSequence0.ts to fileSequence180.ts) in that m3u8 file onto your computer, now if you play that with MPV with all the segments there it will play nicely with no issues,
to see the problem delete some of the segment files, for example delete the file  "fileSequence5.ts", then open the m3u8 file again in  MPV, it will play up until it can't find the deleted file then it will exit playback, ffplay however will not exit and will continue with a frozen image until the next segment and it will continue playing normally 

this test can be done opening the m3u8 file locally or hosting it on a webserver somewhere, this issue makes MPV virtually useless when it comes to playing online live HLS streams on a slow connection or when there is heavy network load, as most HLS streaming servers delete the segment files after a their playback time and on a slow connection that will result in a 404 not found server errors it should in this case ignore the error and skip to the next segment

**Comment by wm4** [comment]
If I download the HLS playlist and all segments, delete one segment, and play it with ffplay, it just enters an endless loop without ever resuming. (Yes, it probably resumes itself as soon as the segment actually becomes available, but this is not how it should work.)

**Comment by He1my** [comment]
yes that is right, it will get stuck in a loop unless the file becomes available it will start playing it, or if i seek after the missing segment in ffplay it will continue playing normally, MPV doesn't do that and it is unable to even seek past the missing segment, it just exists 

i now realize that this may not be the best test example for the main issue I'm reporting, the main issue is with HLS live streaming where the server deletes the segments as soon as possible, on a loaded or a slow connection MPV exists completely but ffplay will skip to the next segment if it got multiple  404 not found errors, i will need to devise a better repeatable online test for this exact scenario.
i have ran the same stream using both ffplay and mpv at the same time, ffplay will continue playing the live stream as expected, while mpv at some point exists, the output for ffplay is here http://tny.cz/4f3bf084
for  mpv  is here: http://tny.cz/0e7aabcb

as for the static segmented content in that previous test you did where ffplay loops forever, that is another related issue, i think the way it should work for this case where there are missing segments in a complete m3u8 file is to only loop looking for the file but only for the amount of seconds the missing segment contains as defined in the m3u8 file, then it should move on to the next segment and so on,
 ffplay and mpv both are not handling this case well enough (and i know it may be a rare usage case)
for example if the missing segment was "fileSequence5.ts"
#EXTINF:10," no desc"
fileSequence5.ts
then it should keep trying to request the file for 10 seconds then it should skip ahead for the next segment, not loop forever the way ffplay does and should be able to seek to other segments that does exist the way how ffplay does it now

**Comment by wm4** [comment]
ffmpeg reports correct EOF. mpv correctly follows the EOF event. ffplay doesn't actually exit on EOF. Try ``ffplay -autoexit URL``. The rough equivalent for not-``-autoexit`` in mpv is ``--keep-open``.

This is not a mpv issue, just a consequence of ffplay's weird default behavior. At best you could argue that ffmpeg should skip missing segments instead of claiming EOF. I've sent a patch to do that, whether it's accepted or not is another issue.

**Comment by wm4** [comment]
FFmpeg's HLS demuxer now skips unavailable segments in FFmpeg git master.
