### ISSUE TITLE
Remote URL takes a long time to open, possibly libass bug

### ISSUE THREAD

**Issue by hyperknot** [mpv-player/mpv#1816]
I am using mpv with --ytdl=no and I supply the video and audio stream URLs from youtube-dl -g.

The problem is that videos take a crazy amount of time to start, sometimes as much as 5 minutes. Once it started you can quit MPV, and the same command will run super quickly.

The strange thing, is that when I enabled -v, it stopped at the 
`[osd/libass] Setting up fonts...`
line.
Once it completed I could see that it later followed with `[osd/libass] Done.` line.

Isn't it possible that the super slow remote URL playback is caused because of a bug in the osd/libass part? The fonts being cached would explain why does it take less time the second time.

**Comment by lachs0r** [comment]
Yes, that’s probably just fontconfig building the cache.
Which operating system are you using and where/how did you get your mpv build?

**Comment by hyperknot** [comment]
homebrew cask install mpv
OS X 10.9.5

**Comment by selsta** [comment]
You should not use homebrew cask for mpv, it is outdated.

Instead, do `brew install --HEAD --with-official-libass mpv && brew linkapps`

**Comment by hyperknot** [comment]
I don't understand, it's installing the latest official release from Github, why would it be outdated?
https://github.com/caskroom/homebrew-cask/blob/master/Casks/mpv.rb#L6

**Comment by selsta** [comment]
0.7.3 which is outdated.

**Comment by hyperknot** [comment]
OK, I compiled it with your line (I also had to `brew reinstall ffmpeg --with-openssl` first). How can I delete the cache to see if the problem is fixed?

**Comment by wm4** [comment]
> I'll report back if I experience similar behaviour with other online videos.

That was 26 days ago... assuming the problem is solved. Make a new issue if you encounter new problems.
