### ISSUE TITLE
Incorrect mouse position after toggling fullscreen

### ISSUE THREAD

**Issue by Argon-** [mpv-player/mpv#1817]
I used a lua script to query the mouse position and it looks like whenever I toggle fullscreen the mouse position is set to the lower left corner. Moving the mouse only by a single pixel updates the position correctly. Could the mouse position be updated when going into fullscreen?

I'm asking because I gave [this user script](https://github.com/torque/mpv-progressbar) a shot. It's triggered by mouse movement in the lower part of the screen, therefore going to fullscreen triggers the script.

**Comment by wm4** [comment]
This is likely platform-specific.

**Comment by Argon-** [comment]
Ah. Tested it using OSX.
