### ISSUE TITLE
livestreamer integration

### ISSUE THREAD

**Issue by haarp** [mpv-player/mpv#1818]
This may be more of a theoretical suggestion.

Would integration (and/or simple calling) of livestreamer (http://docs.livestreamer.io/) from within mpv be feasible, akin to the way youtube-dl is used to handle video site URLs? Having livestreamer available would extend this handling to many livestreaming sites.

**Comment by wm4** [comment]
In theory it's possible, you'd just have to write a script like ytdl_hook.lua.

**Comment by selsta** [comment]
livestreamer opens mpv anyway.

`mpv->livestreamer->mpv` seems weird.

**Comment by haarp** [comment]
>livestreamer opens mpv anyway.
>mpv->livestreamer->mpv seems weird.

livestreamer basically spits out a stream on stdout, then feeds that into the player of the user's choice. All mpv would have to do is receive that stream. So it would be more like

`mpv<-livestreamer`

**Comment by selsta** [comment]
This might work: https://gist.github.com/ChrisK2/8701184fe3ea7701c9cc

**Comment by haarp** [comment]
Very interdasting! Any chance this could be merged into the main build?

**Comment by wm4** [comment]
It's up to @ChrisK2 whether he wants to merge it.

This script for one seems to enable itself only for one site...

**Comment by ChrisK2** [comment]
I'd rather not, the script pretty much duplicates the functionality of the ytdl_hook script, ideally youtube-dl should integrate support for the few sites that livestreamer can handle.

The limitation to twitch is because livestreamer can also hook into services, which youtube-dl handles just fine (or better) (like youtube.com).

**Comment by dilworks** [comment]
Why not make it an option? Say, default to youtube-dl but let the user pick which backend to use by using a commandline switch (say --stream-backend=something).

The reasoning is simple: support for streaming sites is breaking all the time given the nature of those sites, and while both tools strive to fix such support ASAP, you may find that some tool fix certain issues sooner than the other. For example right now, Ustream support on youtube-dl is kinda broken for me, while it's working just fine on a recent-ish Livestreamer build.

**Comment by selsta** [comment]
Here is an updated livestreamer hook: https://gist.github.com/selsta/cdb1e3172a87f6f028c6

mpv will default to ytdl, if `--no-ytdl` is passed it will try Livestreamer.

**Comment by dilworks** [comment]
Cool, will try later as I've just discovered that Ustream live streams aren't supported yet by youtube-dl: https://github.com/rg3/youtube-dl/issues/2226

**Comment by ChrisK2** [comment]
> Why not make it an option? Say, default to youtube-dl but let the user pick which backend to use by using a commandline switch (say --stream-backend=something).

Hm ... I'll think about something like this. Unifying both scripts would be the best option. We just need to come up with a working (and ideally smart) way to figure out wether to use youtube-dl or livestreamer.

**Comment by spaghetti2514** [comment]
I was just thinking that livestreamer integration would be awesome. Got on github to check if it had been suggested already, expecting it to have been requested and closed months ago. Awesome that it's actively being looked into.

>We just need to come up with a working (and ideally smart) way to figure out wether to use youtube-dl or livestreamer

Can we compare the output from ```youtube-dl --list-extractors``` and ```livestreamer --plugins``` to see which supports a site we're trying to access, and just pick youtube-dl if both support it?

I suppose you're trying to avoid maintaining a meta-script that tries to manually direct different sites to different scripts, but I think that might be the only option for things like youtube livestreams, which livestreamer should be used for but youtube-dl should still be used for the rest of youtube links.

**Comment by wm4** [comment]
Closing because obviously nobody cares to provide/maintain such a script.

**Comment by timofonic** [comment]
No devs interested?

**Comment by hyiltiz** [comment]
Still no one with skills who care to develop and maintain? 
Would love to watch:
https://www.ustream.tv/channel/e3uYJSDgmbz
http://www.ustream.tv/channel/live-iss-stream
