### ISSUE TITLE
Window dragging doesn’t work on OS X until the OSC has been activated at least once

### ISSUE THREAD

**Issue by vitorgalvao** [mpv-player/mpv#1819]
Window dragging from anywhere (i.e. by dragging the video being displayed as opposed to the top bar) does not work on OS X if the on-screen display hasn’t been available at least once.

So if for example the `showwindowed=no` option is set and we open a video in windowed mode, window dragging will be unavailable until the video is made fullscreen at least once. By this I mean that when opening the video it won’t work at all, but if we quickly go in and out of fullscreen, then it starts working for the duration of the video.

Reproducible both with `--script-opts=osc-showwindowed=no` and in `~/.mpv/lua-settings/osc.conf`.

If we completely disable the on-screen display in both cases (`--script-opts=osc-showwindowed=no,osc-showfullscreen=no`, or by setting both options in  `~/.mpv/lua-settings/osc.conf`), then window dragging won’t work at all.

Currently on `mpv` version `0.9.2`, installed via `homebrew` with no specified flags, from [the official repo](https://github.com/mpv-player/homebrew-mpv). OS X Yosemite `10.10.3`.

**Comment by Argon-** [comment]
Could you test with HEAD? Dragging works for me (always did). Probably try with `--no-config` too and try to identify the problematic option in case it works.

**Comment by Nyx0uf** [comment]
Same here, works perfectly (tried with my config and with --no-config)

**Comment by AirPort** [comment]
Same, it works as expected here (10.10.3, HEAD mpv).

**Comment by vitorgalvao** [comment]
Found the culprit: it’s the `showwindowed=no` option. Reproducible both with `--script-opts=showwindowed=no` and in `~/.mpv/lua-settings/osc.conf`.

**Comment by Argon-** [comment]
Interesting, but works for me even with showwindowed=no.
(However, `--script-opts=showwindowed=no --no-config` does not work. Whenever I use both flags the showwindowed is always ignored)

**Comment by vitorgalvao** [comment]
Still happens in `0.9.0`. Updated top comment to reflect that.

**Comment by vitorgalvao** [comment]
There’s a really ugly hack to work around this. Simply execute the following line.

```shell
mkdir -p "${HOME}/.mpv/scripts && echo 'function cycle_fullscreen()\n  mp.command("cycle fullscreen")\nend\n\nmp.register_event("start-file", cycle_fullscreen)\nmp.register_event("file-loaded", cycle_fullscreen)' > "${HOME}/.mpv/scripts/cycle_fullscreen_twice.lua"
```

---

What it does is create a `.mpv/scripts` directory, if it didn’t exist, in your home. It then creates a `cycle_fullscreen_twice.lua` file inside it with the contents

```lua
function cycle_fullscreen()
  mp.command("cycle fullscreen")
end

mp.register_event("start-file", cycle_fullscreen)
mp.register_event("file-loaded", cycle_fullscreen)
```

which basically just makes mpv toggle fullscreen twice when opening a file.

**Comment by vitorgalvao** [comment]
Actually, scratch that, as it causes other problems and may even hang mpv.

**Comment by wm4** [comment]
What does ``--script-opts=showwindowed=no`` actually do? Seems to do nothing here.

**Comment by vitorgalvao** [comment]
@wm4 Should be `--script-opts=osc-showwindowed=no` instead. The `osc-` prefix was left out before (not sure if I just forgot to write it or if the requirement came after the issue was opened).

**Comment by vitorgalvao** [comment]
@wm4 Actually, looking further into it, it appears the issue can be more accurately described as “window dragging doesn’t work on OS X until the OSC has been activated at least once”. I’ve updated the title and top post to reflect that.

**Comment by Akemi** [comment]
i investigated the issue and the problem is that the function [mp_input_test_dragging](https://github.com/mpv-player/mpv/blob/b6cbf74518a751e0982c2c514f16c96b5736dbad/input/input.h#L222) used in [recalcMovableByWindowBackground](https://github.com/mpv-player/mpv/blob/aceeeaf9bb7d3549c22557b8afe50838119f0b89/video/out/cocoa_common.m#L898) always returns true, when used with `--script-opts=osc-showwindowed=no`. it should return false in that case. there seems to be a mouse area active in the OSC which leads to this problem. when cycling the visibility options of the OSC `(O script_message osc-visibility cycle)` to 'never' an area seem to be properly set and the function returns the right value as expected.

so this isn't an OSX bug per se.
