### ISSUE TITLE
VDPAU hardware acceleration not working on certain files

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [mpv-player/mpv#1820]
On certain files (such as anime fansubs from [UTW] and [WhyNot] groups), hardware decoding will fail to activate.

The relevant section of the log:
````
[vd] Pixel formats supported by decoder: yuv420p10le
[vd] Pixel formats supported by decoder: yuv420p10le
[ffmpeg/video] h264: decode_slice_header error
[ffmpeg/video] h264: no frame!
[vd] Error while decoding frame!
[vd] Error using hardware decoding, falling back to software decoding.
````

Full log can be found at http://p.pomf.se/7009

My graphics card does support this codec: http://p.pomf.se/7010
````
name               level macbs width height
-------------------------------------------
…
H264_BASELINE        41  9216  2048  1152
H264_MAIN            41  9216  2048  1152
H264_HIGH            41  9216  2048  1152
…
````

Why does this happen and how can I fix it, short of re-encoding the video files?

**Comment by wm4** [comment]
These files use 10 bit. Virtually nothing can decode these on consumer hardware. If you need hardware acceleration, your only way is to re-encode them.

**Comment by wm4** [comment]
>Virtually nothing can decode these on consumer hardware.

And this is of course about GPU hardware decoding. Software decoding should be fine, but of course happens entirely on the CPU.

**Comment by wm4** [comment]
>My graphics card does support this codec: http://p.pomf.se/7010

PS: no, it doesn't. It doesn't list the Hi10P profile, which these files use.

**Comment by JamesTheAwesomeDude** [comment]
Ah, blast - I hadn't noticed that these files were Hi10..

This explains things.
