### ISSUE TITLE
Audio freezes on backward seek with external audio file

### ISSUE THREAD

**Issue by Kagami** [mpv-player/mpv#1824]
Hi. I'm really sorry if it was already answered somewere but I was trying hard to find it in bugtracker and still no luck.

I have problem with backward seek on a video files with external audio track: right after seek audio freezes for some time and continues playing only after a while. Probably it's not that bad but annoying. I haven't determined the exact format of files cause this but I believe I experience this most oftenly with aac format. Also sometimes I'm getting the same problem after switching the audio track.

Example to reproduce the problem:
```bash
$ mpv --version
mpv git-2896afa (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.22.101
   libavcodec      56.34.100
   libavformat     56.30.100
   libswscale      3.1.101
   libavfilter     5.14.100
   libswresample   1.1.100
$ youtube-dl wKFzKnEH5Vg 
[youtube] wKFzKnEH5Vg: Downloading webpage
[youtube] wKFzKnEH5Vg: Extracting video information
[youtube] wKFzKnEH5Vg: Downloading DASH manifest
[download] Destination: Seeu - Gwyiomi-wKFzKnEH5Vg.mp4
[download] 100% of 13.20MiB in 00:01
$ youtube-dl -f bestaudio wKFzKnEH5Vg
[youtube] wKFzKnEH5Vg: Downloading webpage
[youtube] wKFzKnEH5Vg: Extracting video information
[youtube] wKFzKnEH5Vg: Downloading DASH manifest
[download] Destination: Seeu - Gwyiomi-wKFzKnEH5Vg.m4a
[download] 100% of 1.29MiB in 00:00
[ffmpeg] Correcting container in "Seeu - Gwyiomi-wKFzKnEH5Vg.m4a"
$ mpv --no-config --vo=null --ao=alsa Seeu\ -\ Gwyiomi-wKFzKnEH5Vg.mp4
Playing: Seeu - Gwyiomi-wKFzKnEH5Vg.mp4
 (+) Video --vid=1 (*) (h264)
     Audio --aid=1 --alang=und (*) (aac)
 (+) Audio --aid=2 --alang=und (*) 'Seeu - Gwyiomi-wKFzKnEH5Vg.m4a' (aac) (external)
AO: [alsa] 48000Hz stereo 2ch float
VO: [null] 1280x720 yuv420p
```

Now press RIGHT, RIGHT and LEFT and audio will freeze for a second.

Files:
http://a.pomf.se/lwytsx.mp4
http://a.pomf.se/iuchgh.m4a

**Comment by wm4** [comment]
So you mean that audio results in silence, right? This is because both files essentially return a different position after seeking, so to resync them, silence is inserted. This is actually also fixed with ``--hr-seek=yes``.

**Comment by Kagami** [comment]
Yes, silence for a second. Thanks, probably I need to add this to config. This is a bit slower though...

And what about the audio track switching? It didn't get fixed with `--hr-seek`. I have one movie with ac3 external audio track where I can reproduce this, it's too big to upload though. Tell me if you need some example and I'll try to find smaller file.

```bash
$ mpv --no-config --hr-seek=yes Perepisyvaya.Betkhovena.2006.XviD.DVDRip.avi 
Playing: Perepisyvaya.Betkhovena.2006.XviD.DVDRip.avi
[ffmpeg/demuxer] ac3: Estimating duration from bitrate, this may be inaccurate
 (+) Video --vid=1 (mpeg4)
     Audio --aid=1 (ac3)
 (+) Audio --aid=2 'Perepisyvaya.Betkhovena.2006.XviD.DVDRip.ac3' (ac3) (external)
 (+) Subs  --sid=1 'Perepisyvaya.Betkhovena.2006.XviD.DVDRip.srt' (subrip) (external)
AO: [alsa] 48000Hz stereo 2ch float
VO: [opengl] 720x304 yuv420p
AV: 00:03:14 / 01:44:02 (3%) A-V:  0.000
[ffmpeg/audio] ac3: frame sync error
Error decoding audio.
AO: [alsa] 48000Hz stereo 2ch float
AV: 00:04:19 / 01:44:02 (4%) A-V:  0.000
[ffmpeg/audio] ac3: frame sync error
Error decoding audio.
AV: 00:04:21 / 01:44:02 (4%) A-V:  0.000
AO: [alsa] 48000Hz stereo 2ch float
AV: 00:04:23 / 01:44:02 (4%) A-V:  0.000
[ffmpeg/audio] ac3: exponent out-of-range
[ffmpeg/audio] ac3: error decoding the audio block
AO: [alsa] 48000Hz stereo 2ch float
[ffmpeg/audio] ac3: frame sync error
Error decoding audio.
AV: 00:04:26 / 01:44:02 (4%) A-V:  0.000
```

I'm switching the tracks with `#`, getting `frame sync error` in console and audio freezes for several seconds (sometimes even tens of seconds). I don't think it's related to this particular file because I have experienced the similar problems with a lot of files.

**Comment by wm4** [comment]
Seeking in raw ac3 files is probably not reliable. Nothing that can be done about it. Remux it to mka if you care (``mkvmerge -o out.mka in.ac3``, didn't test, but probably works).

**Comment by Kagami** [comment]
Ok, thanks.
