### ISSUE TITLE
Seeing 0/x dropped frames with webm (VP9) file

### ISSUE THREAD

**Issue by rbrito** [mpv-player/mpv#1825]
Hi.

I have a webm file that is composed of a VP9 video stream with Vorbis audio. It is 1280x720 and I'm using a Debian sid system, with mpv and ffmpeg versions as follows:

```
$ mpv --version
mpv 0.8.3 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Tue Mar 17 06:56:30 UTC 2015
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100
```

Unfortunately, when I play this file, I get the status line on the console giving me "Dropped: 0/x", with x increasing about once a second or less.

It doesn't seem to matter which video output I use (tried opengl, vaapi, xv, x11, opengl-hq, and even caca). I'm using a SandyBridge Intel notebook and the load when playing the file is very low (about 0.15) and the CPU utilization (according to htop) is circa 25%.

I don't see frames being dropped with ffplay (OK, I get only 1 right at the beginning of the file, but then, nothing else). I can provide a sample of the file, if so desired.

It was downloaded from youtube with youtube-dl (and muxed with ffmpeg).

Is there anything that I can do to fix this?

Thanks in advance,

Rogério.

**Comment by wm4** [comment]
This is because the vp9 codec has a special case that doesn't fit well into the ffmpeg API. The decoder sometimes doesn't return a new frame, which is due to another fault in the API indistinguishable from a decoder-framedrop.

There are actually no frames dropped, and ffplay simply doesn't report decoder framedropping (and doesn't need to, because it never disables it).

**Comment by wm4** [comment]
PS: to make it clear, it's a cosmetic issue with the framedrop display caused by VP9 being special, and there's no real problem.
