### ISSUE TITLE
vo_drm: support switching virtual terminals

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#1827]
Scenario:

1. On VT1, run `mpv -vo=drm video.mkv`
2. Switch to VT2

What happens:

3. Video playback continues
4. Keystrokes, however, are sent to VT2. :-1:
5. Returning to VT1 and hitting <kbd>q</kbd> stops the playback as expected.

What should happen:

3. Video playback continues, but in the background. The control over connector is returned to the OS.
4. VT2 console appears, and keystrokes are sent to VT2
5. After switching back to VT1, video shows up again.

**Comment by rr-** [comment]
Solution - we need to check current VT. `fgconsole.c` does just that and it's just 28 lines, of which the most important part is:

    int fd = getfd(NULL);
    struct vt_stat vtstat;
    if (ioctl(fd, VT_GETSTATE, &vtstat)) {
      //error...
    }
    int vt = vtstat.v_active;

So how do we know if it changed?

1. Create a thread. I don't like this idea very much. It requires locking and other boilerplate that just  obscures the code.
2. Check the VT in `draw_image()`. This won't work if the image is paused.
3. Check the VT in `control()`. According to @wm4, there will be problems with this.

**Comment by kevmitch** [comment]
I'm adding this here as it is probably related:

* console only (no xserver, wayland, etc running) 
* VT2: startx > [startx.log](http://sprunge.us/LFPh)
* switch to VT1: mpv --vo=drm file.mkv
* switch back to VT2

upon switching back to VT2 the display backlight is drastically reduced (/sys/class/backlight/intel_backlight/actual_brightness has become 0), video is still shown, and xserver crashes with 
    
    Fatal server error:
    (EE) EnterVT failed for screen 0

on stderr as seen in the above startx.log.

In the [Xorg.0.log](http://sprunge.us/hNBG), it says

    [ 63000.789] (WW) intel(0): drmSetMaster failed: Invalid argument
    [ 63000.789] (EE) intel(0): failed to set mode: Permission denied
    [ 63000.789] (EE) 
    Fatal server error:
    [ 63000.789] (EE) EnterVT failed for screen 0

In contrast, I have no problems switching back and forth between a running xserver and weston on different VTs.

**Comment by rr-** [comment]
I'm starting to think that polling `vtstat.v_active` isn't going to do any good, because after we detect it it's going to be far too late: by then, xserver will try to do whatever it needs to do (and fail).

There must be a way to hook directly to VT switching event.

**Comment by rr-** [comment]
Looks like there is a way after all!

http://asm.sourceforge.net/articles/vt.html

Gotta play with this once I get home.
