### ISSUE TITLE
strip "feature=player_embedded&" from a given URL

### ISSUE THREAD

**Issue by toralf** [mpv-player/mpv#1837]
An URLlike https://www.youtube.com/watch?feature=player_embedded&v=qJmgLqQ-uog won't work under Gentoo:

tfoerste@t44 ~ $ mpv https://www.youtube.com/watch?feature=player_embedded&v=qJmgLqQ-uog
[1] 10225
tfoerste@t44 ~ $ Playing: https://www.youtube.com/watch?feature=player_embedded
[ffmpeg] [ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
Failed to open https://www.youtube.com/watch?feature=player_embedded.

[1]+  Stopped                 mpv https://www.youtube.com/watch?feature=player_embedded
tfoerste@t44 ~ $ fg
mpv https://www.youtube.com/watch?feature=player_embedded

Exiting... (No files played)

However it is just enough to strip  "feature=player_embedded&" from it to make it working:
$> mpv https://www.youtube.com/watch?v=qJmgLqQ-uog

**Comment by wm4** [comment]
``&`` is interpreted by the shell. Quote the URL with ``"`` to prevent the shell from interpreting it.

**Comment by toralf** [comment]
*head smack* - sry for the noise
