### ISSUE TITLE
Save subtitle filepath while saving state

### ISSUE THREAD

**Issue by hashken** [mpv-player/mpv#1838]
Right now, when mpv saves state and quits, it doesn't save the the subtitle file currently being used. Would it be possible to add this feature?

**Comment by wm4** [comment]
This is a bit hairy. Can I ask what's the use-case? Normally, an external subtitle is either auto-loaded (then it doesn't need to be saved), or you add it manually.

**Comment by hashken** [comment]
This is needed only when I load the subtitle file manually. Many times I
start a movie, see for sometime and watch it later. The next time I
continue watching I have manually load the subtitle file again.

If I've loaded the subtitle file once, then it's a fair assumption that I
would want the same sub file to be used again when  I continue watching the
movie.

**Comment by Dudemanguy** [comment]
Fixed by #8960.
