### ISSUE TITLE
Consistent kernel freeze using Intel hwdec on certain video file

### ISSUE THREAD

**Issue by haarp** [mpv-player/mpv#1839]
This video: http://clanjadewolf.net/~haarp/temp/crash.mp4

Using hardware decoding on this file makes mpv freeze halfway through, followed a few seconds after by the entire system kernel (not just X). Playback with hwdec=no appears to work fine. Changing the vo does not seem to make a difference.

The problematic part complains about Non-monotonic video pts. I can also catch a glimpse of a warning before the kernel freezes:
`WARNING: invalid Slice reference frame list !!!, It is not included in DPB`

Sandy Bridge, Gentoo Linux, kernel 3.18.11-gentoo, mpv-0.8.3, xorg-server-1.16.4, xf86-video-intel-2.99.917, libva-1.3.1, libva-intel-driver-1.3.0
libva info: VA-API version 0.35.1
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_35

I suspect an Intel bug, but I'd like to get an opinion here first.

**Comment by haasn** [comment]
If it plays with ```hwdec=no``` then I'd highly suspect Intel driver's for being shitty.

**Comment by haarp** [comment]
Did some more digging. It's probably this bug: https://bugs.freedesktop.org/show_bug.cgi?id=76363

Upgrading libva-intel-driver to a version that includes the patch mentioned seems to fix it. Oh well. 

Thanks for having a look.
