### ISSUE TITLE
autoload.lua is adding "Thumbs.db" and "desktop.ini" to the playlist

### ISSUE THREAD

**Issue by sleek22** [mpv-player/mpv#1840]
autoload.lua adds "Thumbs.db" and "desktop.ini" to the playlist when they are present. These are hidden window files but will show on a folder on the desktop. The player pauses for a second and then skips to the next file.

"Thumbs.db" will be there for a folder on the desktop.
"desktop.ini" will be there for a folder on the desktop if it has been changed to show an icon. 

Can these be removed from the playlist?

**Comment by haasn** [comment]
IMO: The script should have a whitelist of extensions.

**Comment by sleek22** [comment]
I did some Google searching and was able to put together the following which seems to be working. I am not a programmer so maybe there is a simpler way to do it. The code I added starts at "-- Remove unwanted files". The first three lines are in the program for reference as to where to add the lines after.

table.sort(files, function (a, b)
return string.lower(a) < string.lower(b)
end)

-- Remove unwanted files
table.indexOf = function( t, object )
local result
 
if "table" == type( t ) then
for i=1,#t do
if object == t[i] then
result = i
break
end
end
end
 
return result
end
 

if table.indexOf(files, "Thumbs.db")  then
  table.remove(files, table.indexOf(files, "Thumbs.db"))
end
if table.indexOf(files, "desktop.ini")  then
  table.remove(files, table.indexOf(files, "desktop.ini"))
end
if table.indexOf(files, "Desktop.ini")  then
  table.remove(files, table.indexOf(files, "Desktop.ini"))
end

**Comment by rr-** [comment]
@sleek22 you might want to prefix your code with four spaces (` `` `` `` `) so it looks

    like
        this
    which

makes it more readable.

**Comment by sleek22** [comment]
I agree that allowing only certain types of files in the list would be an easier solution. It's probably a case of adding a single line that checks for common video types before allowing them to be part of the playlist.

Lua is new to me and I can't figure out where to make the changes.

**Comment by rr-** [comment]
In that case I can work on that tomorrow.

**Comment by rr-** [comment]
Should be fixed in eb62d7ec40cbe07a6177e399071809dec85ab1f3. @sleek22 please confirm if this works for you.

**Comment by sleek22** [comment]
@rr,

I tested your version out with all sorts of files and directories and it is working great so far. Thank you so much for taking the time to fix this problem.

As an aside, I was introduced to mpv player when the makers of SMPlayer allowed an option to install with mpv instead of mplayer. Running mpv player as a stand-alone, I was amazed at its speed and ability to handle high bitrate files and how fast it seeks and renders when you seek around the video. With an on-screen display and a good working playlist, plus the ability to make changes in mpv.conf, input.conf, write scripts, etc, I find that I no longer need a front-end on mpv player. It is really that good of a player.

Again, thank you for your work in fixing this problem.

**Comment by rr-** [comment]
You're welcome :+1:
