### ISSUE TITLE
(win) powermanagement | prevent hibernation

### ISSUE THREAD

**Issue by fohrums** [mpv-player/mpv#1841]
SITUATION
=

using default parameters

`
$ mpv video.mp4
`

On Windows 7 x64 I have sleep set up at 15-mins. So, is there a parameter that is specific for windows-users to prevent <i>powermanagement-hibernation</i> as <i>screensaver</i> is handled properly when using mpv.

WORKING
=

- <b>screensaver</b> is properly disabled (therefore, powering-off display is also disabled) when using mpv

PROBLEM
=

- <b>hibernation</b> is not properly handled when using mpv

NOTE
=

- mpv-20150328_win_x64
- video.mp4 has audio
- `powercfg -requests` initials <i>DISPLAY</I>: mpv; <i>SYSTEM</i>: Realtek audio

**Comment by rossy** [comment]
I'll investigate this. mpv calls SetThreadExecutionState to prevent the display from turning off, but I'm not sure if it prevents sleep as well (my computers are not configured to go to sleep automatically.)

**Comment by kevmitch** [comment]
Mine is configured to sleep, and it does not when mpv is playing. That could be my audio driver though.

**Comment by kevmitch** [comment]
C:\>powercfg -requests
    DISPLAY:
    [PROCESS] \Device\HarddiskVolume3\Program Files\mpv\mpv.exe

    SYSTEM:
    [DRIVER] USB Audio Device (USB\VID_041E&PID_30D7&MI_00\7&fc6cd99&0&0000)
    An audio stream is currently in use.
    [PROCESS] \Device\HarddiskVolume3\Program Files\Synergy\synergyc.exe
    [DRIVER] Legacy Kernel Caller

    AWAYMODE:
    None.

It appears mpv only requests the display stay awake. Not sure if that implies that the whole system should as well (although that would make sense) as [msdn](https://msdn.microsoft.com/en-us/library/windows/desktop/aa373208%28v=vs.85%29.aspx) is kind of vague on this. However for me the fact that it is playing audio makes this distinction moot.

**Comment by rossy** [comment]
Yeah, it's the same for me. mpv keeps the machine awake when audio is playing (but the screen can turn off,) and when there's video playing, the screen stays on.

**Comment by rossy** [comment]
Oh wait, I was wrong. When there's video and no audio (with --no-audio) the machine **can** go to sleep. This should probably be fixed (by adding the ES_SYSTEM_REQUIRED flag to the SetThreadExecutionState call?)

**Comment by kevmitch** [comment]
sounds reasonable.

**Comment by rossy** [comment]
@fohrums: Does that file have audio? What's the output of ``powercfg -requests`` when playing it?

**Comment by rossy** [comment]
Just merged #1843. I hope it fixes this.

**Comment by fohrums** [comment]
@rossy 

When playing the video (yes, it has audio) and do a `powercfg -requests`:
(it immediately doesn't call any <i>DISPLAY</i>, <i>SYSTEM</i>, or <i>AWAYMODE</i> when not playing the video)
```
DISPLAY:
[PROCESS] \Device\HarddiskVolume3\download\utilities\cygwin\_dependencies\mpv-x86_64-20150328\mpv.exe

SYSTEM:
[DRIVER] Realtek High Definition Audio (HDAUDIO\FUNC_01&VEN_10EC&DEV_0887&SUBSYS_10438445&REV_1003\4&3ad857fa&0&0001)
An audio stream is currently in use.

AWAYMODE:
None.
```

OTHERTHOUGHTS
=

I haven't called the `powercfg -request` command to troubleshoot the problem before. So, what i'll do is see if the problem still persists.

**Comment by fohrums** [comment]
The problem is still here :(

Is there a way for windows users to be notified of updates? 

I appreciate lachs0r's work of compiling mpv for every new release and after checking, there is a new update which is <i>mpv-20150411</i> as mine's the <i>previous version</i>. I just thought I point that out and I don't want to jump right to it if the problem isn't resolved in <i>that</i> update.

**Comment by wm4** [comment]
>mpv-20150411

This is obviously over a week old too.

>Is there a way for windows users to be notified of updates? 

I don't know, CC @lachs0r.

**Comment by fohrums** [comment]
The latest version mpv-20150411 doesn't help and the problem still persists.

**Comment by lachs0r** [comment]
New build, try again.

**Comment by fohrums** [comment]
@lachs0r [SOLVED] 
mpv-20150428 fixed the issue.

**Comment by wm4** [comment]
Nice, thanks for testing.
