### ISSUE TITLE
Unable to use ytdl-raw-options

### ISSUE THREAD

**Issue by notargets** [mpv-player/mpv#1857]
I'm using mpv 0.8.3 under Manjaro Linux and can't seem to use `--ytdl-raw-options` to watch a video that requires username/password authorization. This is what I get when I try: 

    $ mpv --ytdl-raw-options=username=<username>,password=<password> https://www.udemy.com/…
    Error parsing option ytdl-raw-options (option not found)
    Setting commandline option --ytdl-raw-options=username=<username>,password=<password> failed.

Also, I can't find `--ytdl-raw-options` in the local man page (`man mpv`) but it is there in the [online documentation](http://mpv.io/manual/master/#options-ytdl-raw-options). Has this option been removed from mpv recently or am I missing something?

**Comment by wm4** [comment]
The link is for git master; the option isn't in 0.8.3 yet. It will be in 0.9.0.
