### ISSUE TITLE
serial IR remote support

### ISSUE THREAD

**Issue by francescortiz** [mpv-player/mpv#1866]
Hi,

It seems that lirc support has been removed. Documentation says "there is no LIRC support - configure remotes as input devices instead".

The problem that I run into now is that there doesn't seem to be support for serial lirc devices working as Xorg input devices, or at least I can't find it.

Is it possible to recompile mpv with lirc support?

Thank you

**Comment by wm4** [comment]
CC @lachs0r (you seem to know about this)

>Is it possible to recompile mpv with lirc support?

No. It was removed completely.

**Comment by francescortiz** [comment]
Well, though I like mpv a lot, I am switching back to mplayer for now.

**Comment by lachs0r** [comment]
Not really sure about serial port receivers, but most devices made in the past 14 years (Windows MCE compatible) should work with evdev. Out of the box if you’re lucky and your distro ships preconfigured for that (this worked for me with openSUSE and the generic MCE receiver on a TeVii S464).

**Comment by francescortiz** [comment]
Thank you lachs0r. I will check that. What comes to my mind is, being it an input device, do you have to give focus to mpv in order for the remote to work? In other words, can you be browsing in another screen while the remote is still operational in mpv? Thanks!

**Comment by lachs0r** [comment]
Unfortunately not directly, since mpv does not handle global keyboard shortcuts by itself.

**Comment by francescortiz** [comment]
Ok, thank you.

**Comment by wm4** [comment]
I added a wiki page: https://github.com/mpv-player/mpv/wiki/IR-remotes

**Comment by deveee** [comment]
What is the reason of removing lirc support from mpv? I'm using mpv 0.8 with lirc and I don't have any issues.

I use lirc in a lot of other applications such as audacious, xbmc. I have also some other custom shortcuts, and even mouse support using irexec. The main problem is that if I want to use my IR-remote as input device, I have to totally disable lirc :(

Other thing is that evdev supports only some keys in my IR device.

**Comment by wm4** [comment]
Very unclean code, the inability to test it, and availability of supposedly better methods.

**Comment by deveee** [comment]
Maybe just leave it disabled by default? You wouldn't force people to patch it manually (or switch back to mplayer).

Another reason to use lirc is that you can control the player when it is in the background. For example you are playing the game and you can start/stop the song, change volume etc...

As I said the main reason is that it forces lirc to be totally disabled. And I can't for example configure my keyboard left/right/... arrows to simulate mouse events. Simulating mouse events on IR device works perfectly fine, but doing the same on keyboard would be strange.

**Comment by wm4** [comment]
>Maybe just leave it disabled by default?

What would that change?

>Another reason to use lirc is that you can control the player when it is in the background. For example you are playing the game and you can start/stop the song, change volume etc...

Completely orthogonal issue.

**Comment by lachs0r** [comment]
You might also want to check out evrouter.

**Comment by foobar0815** [comment]
[irxevent](http://www.lirc.org/html/irxevent.html) can help out here... 

lircrc example:

```
begin
  prog = irxevent
  button = Play
  config = Key space mpv
end

begin
  prog = irxevent
  button = Volume+
  config = Key 0 mpv
  repeat = 1
  delay = 1
end

[...]
```

for future reference this could be added to the wiki page.

**Comment by wm4** [comment]
It would be nice if you could add this to: https://github.com/mpv-player/mpv/wiki/IR-remotes

**Comment by francescortiz** [comment]
I agree with @wm4 . I created a python script to interact with the json api, but this would have been much more simple for what I do.

**Comment by chrisaljoudi** [comment]
@foobar0815 @wm4 @francescortiz I've gone ahead and edited the Wiki page to reference irxevent.

**Comment by wm4** [comment]
@ chrisaljoudi: thanks, that's awesome.
