### ISSUE TITLE
DOCS and defaults: youtube-dl default format is now bestvideo+bestaudio/best

### ISSUE THREAD

**Issue by yan12125** [mpv-player/mpv#1867]
References: 
[1] #1321
[2] rg3/youtube-dl#5447
[3] rg3/youtube-dl@feccf29c876869f44a9c983977371073b9801a51

Issue #1321 proposed to use ```bestvideo+bestaudio``` as the default format in invoking youtube-dl. Now youtube-dl's default format is bestvideo+bestaudio/best due to the proposal in [2]. As a result, either https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst should be updated to conform to the latest changes in youtube-dl, or https://github.com/mpv-player/mpv/blob/master/player/lua/ytdl_hook.lua should enforce ```best``` format when passsing arguments.

Note that such changes are not included in the latest stable release 2015.04.17 yet, but it won't be long due to youtube-dl's rapid release schedule.

**Comment by wm4** [comment]
OK, the default is now actually "best", instead of letting youtube-dl decide.

**Comment by robin007bond** [comment]
This breaks:

https://github.com/mpv-player/mpv/commit/d453600b4fe3fb7080cc41f0af11513140693eed

**Comment by jaimeMF** [comment]
In that case, you could use `-f bestaudio/best` instead.

**Comment by robin007bond** [comment]
@jaimeMF 
Thanks for the suggestion. 

I think that my commit should be reverted then, since people that don't want to waste bandwidth can use that format option instead of passing the `-x` argument.
