### ISSUE TITLE
Intel VAAPI

### ISSUE THREAD

**Issue by ArchangeGabriel** [mpv-player/mpv#1869]
Following 0.9 update, I’m having news about #1596 because of #1765.

Now, it does work with hwdec=vaapi or hwdec=vaapi-copy but only if I start in full screen and stay in this state.

If I exit fullscreen and come back to it after, playback is laggy. If I don’t start fullscreen and go fullscreen after that, playback is laggy. Note that this might have been the case before, but in 0.8.x, fullscreen was initially black, until I go out and in again (but then it was sluggy).

I’m running on i7 4702 HQ, up-to-date ArchLinux, 3200x1800 fs.

Note that VLC with hwdec works fine here.

Please ask if any info is needed.

**Comment by wm4** [comment]
Does this even happen with ``hwdec=vaapi-copy``? This is essentially the same method VLC uses.

Does it happen with software decoding? If so, it's obviously a more general problem and has nothing to do with hw decoding.

Provisionally marking this as an Intel bug.

**Comment by ArchangeGabriel** [comment]
Well. I’m a bit confuse, because while doing more tries, I’m now unable to get mpv playing fullscreen without lagging in any case… Even with software decoding or `hwdec=vaapi-copy`.

VLC still works with either software or hardware decoding (via either X11 or DRM).

**Comment by wm4** [comment]
Try with ``--vo-xv``. It's not recommended, but may help with Intel hw.

**Comment by ArchangeGabriel** [comment]
Does works fine (but with 56% CPU), but also with `--vo-xv --hwdec=vaapy` (and then only 5% CPU).

But this is not ideal, since opengl provides nice features like icc-profile support.

**Comment by wm4** [comment]
>--vo-xv --hwdec=vaapy 

Uh what? The syntax is wrong (for BOTH options), and xv can't use this type of hw decoding (it works with ``vappi-copy`` only).

**Comment by ArchangeGabriel** [comment]
Sorry, didn’t copied from terminal. Indeed, the correct setting was: `--vo=xv --hwdec=vaapi-copy`.

**Comment by wm4** [comment]
Yep, this should work. I edited my post to the correct syntax.

Do you have any subtitles in your test video? I know that subtitle and OSD rendering with xv is prohibitively slow.

**Comment by ArchangeGabriel** [comment]
Yes. They work fine.

**Comment by wm4** [comment]
And to make it clear: the subtitle slowness (and CPU usage) is mainly mpv's fault here. Other things (including mplayer and vlc) are probably a bit more efficient here. That could explain the difference.

Anyway, Xv ought to be phased out, so I don't care about this much. The real question is why opengl appears to be stuttering here.

**Comment by mc4man** [comment]
I have to say find quite the opposite, mpv on Intel almost never shows any lag or dropped frames thru a wide range of vids, some far exceeding what most users play. 
(one exception would be in recent times high rez HEVC or vp9  that have to be scaled down will drop frames with opengl-hq but fine are  with opengl

Also mpv with vaapi is more efficient than vlc, both 2.2.1 & 3.0+, about 40% or so. Though for most vids hwdec isn't really needed, maybe if playing on battery power, don't know there. 
Here the cpu is fairly close to reporter - i7-4700MQ (HD 4600) so possibly this is an Arch bug, not Intel
( all 3 of these mentioned  bugs seemed to affect Arch users..

If you want to try a fairly high bit rate avc1 with a rez close to what you're using I'll upload a clip to google drive - about 450Mb for 60 sec's. 3840x1714 vbr, plays absolutely  fine here with or without vaapi hwdec

**Comment by wm4** [comment]
> so possibly this is an Arch bug, not Intel

Probably, or a configuration mistake, or somehow due to the compositor that's in use. Either way, even assuming Intel has no bug here, it seems to make it harder than any other GPU vendor to get it working correctly.

**Comment by wm4** [comment]
In case this affected vaapi-copy only (of which I'm not fully sure after reading these posts), it might be because it mapped and copied the image non-cacheable memory without using a memcpy optimized for this. But we'll never know.
