### ISSUE TITLE
[JSON API] Strings are encoded twice

### ISSUE THREAD

**Issue by ScoreUnder** [mpv-player/mpv#1874]
>```
Playing: 東方Vocal　C83私的良曲メドレー.mp4
```

~ command line

>```
{"command":["get_property_string","media-title"]}
{"data":"\u00e6\u009d\u00b1\u00e6\u0096\u00b9Vocal\u00e3\u0080\u0080C83\u00e7\u00a7\u0081\u00e7\u009a\u0084\u00e8\u0089\u00af\u00e6\u009b\u00b2\u00e3\u0083\u00a1\u00e3\u0083\u0089\u00e3\u0083\u00ac\u00e3\u0083\u00bc.mp4","error":"success"}
```

~ json api

The JSON API is sending the string encoded as UTF-8, then with each UTF-8 byte interpreted as a codepoint (incorrect behaviour) is encoding it as JSON.

Expected output:
```
{"data":"\u6771\u65b9Vocal\u3000C83\u79c1\u7684\u826f\u66f2\u30e1\u30c9\u30ec\u30fc.mp4","error":"success"}
```

**Comment by wm4** [comment]
Not sure what's going on. Either there's a dumb bug in the json code, or the filename on your file system is not actually utf-8.

**Comment by ScoreUnder** [comment]
```
        bstr_xappend_asprintf(NULL, b, "\\u%04x", (unsigned char)cur[0]);
```
This is incorrect, it is treating chars as code points.

It looks like the methods in misc/bstr.c might help with this.

**Comment by ScoreUnder** [comment]
Right, I've made a hash of two pull requests, have a third.
