### ISSUE TITLE
Seeking with "osc-seekbarstyle=bar" inaccurate

### ISSUE THREAD

**Issue by Hakkin** [mpv-player/mpv#1876]
I'm in Windows 7 using [suhteevah's mpvhq build](https://github.com/suhteevah/mpvhq-win64/), but I've also confirmed this happens on lachs0r's builds.
[Here's an example of the seeking](https://puu.sh/hteM6/1baa942130.png), in the screenshot I clicked directly on the chapter marker, but the bar shows (and it seeked) slightly to the left.
The seeking is accurate if I seek to the middle of the bar, and then begins to drift the further to either side I go.

For me this happens even with just `script-opts=osc-seekbarstyle=bar`, but it's more obvious with my normal config, which is `script-opts=osc-vidscale=no,osc-scalefullscreen=1.5,osc-scalewindowed=1.5,osc-layout=bottombar,osc-seekbarstyle=bar,osc-minmousemove=0`

Seeking with `osc-seekbarstyle=slider` is 100% accurate as far as I can tell, so this is only a problem with the `bar` style.

**Comment by wm4** [comment]
I suspect it does use precise seeks, but the mouse coordinate calculation are off, so the seek has the wrong target.

**Comment by wm4** [comment]
CC @ChrisK2

**Comment by ChrisK2** [comment]
Confirmed, working on fix.
