### ISSUE TITLE
(win) Crash | BSOD

### ISSUE THREAD

**Issue by fohrums** [mpv-player/mpv#1883]
I don't know how to troubleshoot the problem but I can confirm it only happens when using mpv. It happens at random times with any type of video. What'll happen is my screen will go black as if my PC just did a hard reboot.

TROUBLESHOOT
=
- how do I record the event or view through logs of how the BSOD occured?

**Comment by lachs0r** [comment]
Well, driver issue. Nothing we can do about it.

Check Windows Event Log though.

**Comment by fohrums** [comment]
@lachs0r I'm using AMD-Catalyst drivers v14.12. Does this have anything to do with how CCC handles video?

http://postimg.org/image/ro6q62r0x/

**Comment by lachs0r** [comment]
Thankfully those settings cannot affect mpv. No, you just have buggy drivers. 
There are no settings you can change to fix that.

**Comment by lachs0r** [comment]
You could use --vo=direct3d_shaders, I guess, but then you lose vo_opengl’s features.

**Comment by fohrums** [comment]
@lachs0r Taking note of my AMD 7850 2GB drivers, i've decided to upgrade to the BETA version as the latest stable remained static. So far so good.

**Comment by wm4** [comment]
So a driver bug. That's probably as close to a solution we'll ever come.

**Comment by gregist** [comment]
I have experienced this bsod problem also after updated to windows 10, wrote these lines in mpv.conf and so far so good:
```
hwdec=no
vo=opengl-hq
```
