### ISSUE TITLE
doesn't switch to application when window is on another space (mac osx)

### ISSUE THREAD

**Issue by jojoman02** [mpv-player/mpv#1884]
#### Steps to Reproduce:
1. Start playing a video in mpv in a space.
2. enable **always-on-top** in mpv (SHIFT+T)
3. Switch to another space (or app in another space).
4. Attempt to switch to mpv by clicking the dock icon or via alt+tab.
5. Watch as the application becomes active* but it **doesn't** **switch** to the proper space.

#### note:
* this bug is only present when always-on-top is active 
* may be somehow related to issue #1757 

  [*]  play/pause works when hitting spacebar

**Comment by selsta** [comment]
This is probably a OS X limitation/bug. Applications that are always on-top are kinda buggy. Apart form the issue you are describing, mpv is also invisible in Mission Control when on-top is set.

VLC has the same issues.

**Comment by wm4** [comment]
Closing assuming we can't do anything about this.
