### ISSUE TITLE
Finder: Idle window appears before file loads

### ISSUE THREAD

**Issue by selsta** [mpv-player/mpv#1885]
When opening a file from the Finder, the idle window flashes for a short time before the file loads.
![Idle-window](https://cloud.githubusercontent.com/assets/7697454/7389059/e1139f22-ee6a-11e4-9c20-6cae36ae7f52.png)

**Comment by Akemi** [comment]
does this still happen?

**Comment by tewe** [comment]
I've seen it before, but not anymore.
