### ISSUE TITLE
--fs stops --screen=1 from working

### ISSUE THREAD

**Issue by ewestbrook** [mpv-player/mpv#1891]
I'm using version `0.8.3` on Gentoo.  The `--fs` and `--screen=1` options work correctly when used separately, but not together.  In mpv.conf I have:

> `screen=1`
> `fs`

When configured this way, it comes up full screen ok, but on screen 0.  Without the `fs` directive, it comes up correctly on screen 1, but not full screen.

Using these options on the command line produces the same results.

Please advise.

**Comment by wm4** [comment]
Use ``--fs-screen``.

**Comment by ewestbrook** [comment]
Thank you!  Using `--fs` and `--fs-screen=1` together does the trick.  Case closed.
