### ISSUE TITLE
LUA: Cumulative call of on_unload hook function within file-loaded event

### ISSUE THREAD

**Issue by limelime** [mpv-player/mpv#1892]
Why there is a cumulative call of **on_unload** hook within **file-loaded** event? I was expecting the **on_unload** function to call once.

Here is the code showing the issue
```lua
function on_file_loaded_init()
  mp.add_hook("on_unload", 50, function() print("CALLED at "..mp.get_time()) end)  
end
mp.register_event("file-loaded", on_file_loaded_init)
```

Assuming you are playing multiple files(e.g. `mpv *`).
Every time you press Shift+>, **on_unload** function will be called cumulatively.
For example:
1st Shift+>
   [xmpv] CALLED at 11.854861 

2nd Shift+>
   [xmpv] CALLED at 13.803323 
   [xmpv] CALLED at 13.803377 

3rd Shift+>
   [xmpv] CALLED at 19.42202 
   [xmpv] CALLED at 19.422179 
   [xmpv] CALLED at 19.422369

**Comment by wm4** [comment]
The hook is a global registration, so on every file-loaded event, you're registering a new hook.
