### ISSUE TITLE
Can't set custom font for srt subtitles

### ISSUE THREAD

**Issue by sunabozu** [mpv-player/mpv#1894]
Hello.

I'm trying to change the standard font for subtitles using config option *sub-text-font*, but it doesn't work. I tried many different fonts using their names or full paths, but whatever I do I get the same standard font on my screen.
When I run mpv from the terminal I get this warning:

> Fontconfig warning: ignoring UTF-8: not a valid region tag

Maybe it has something to do with my problem.
I'm using the latest build (though it the same for 1 year old builds as well) for OS X.

**Comment by ChrisK2** [comment]
What build? My builds? If so, did you read the notes at the top of my [builds page](http://sva.wakku.to/~chris/mpv_builds/)?

**Comment by sunabozu** [comment]
Oh thank you! I didn't know it ignores ~/Library/Fonts/
Problem solved.

**Comment by ChrisK2** [comment]
Good then.
