### ISSUE TITLE
Support compressed subtitle-files

### ISSUE THREAD

**Issue by Nudin** [mpv-player/mpv#1895]
mpv supports playing files in containers like rar, but it does not yet support giving a subtitle file in a packed container. This would be quite handy since a lot of sites (like tvsubtitles.net) provide subtitles packed in a zip-file. It would be great if you could give them just as an argument for the --sub-file option.

**Comment by wm4** [comment]
Rejected. Adding support for reading compressed zip files would be way too complicated.

**Comment by lachs0r** [comment]
This can be automated outside of mpv though. For example, you could use https://github.com/Diaoul/subliminal with a script that runs unzip or whatever if necessary.

We also have this: https://gist.github.com/selsta/ce3fb37e775dbd15c698 (linked in https://github.com/mpv-player/mpv/wiki/User-Scripts)
