### ISSUE TITLE
Video output frame dropping is not smooth with opengl

### ISSUE THREAD

**Issue by ValdikSS** [mpv-player/mpv#1897]
Hi
I have 3840×2160@44Hz external monitor. If I try to play 50 FPS video, mpv always drops 2 frames in a row with opengl video output, and the video is jerky. xv and x11 video outputs are smoother than opengl.

Is there any way to make opengl output less jerky video, as in xv?

**Comment by avih** [comment]
Not currently. The frame drop logic was modified some weeks ago to be less strict about dropping, so it ends up like you described: instead of one frame drop at a time, it now drops two frames at a time, but with longer intervals between drops.

However, since this behavior was designed to improve cases where the clip rate is very close to the screen rate, we can fall back to the previous behavior on other cases.

That being said, 50fps clip on 44hz display is quite close already, so the threshold for "close" might need to be less than 5%, which could be a bit tight IMO...

I'll see what I can do.

**Comment by ValdikSS** [comment]
Thanks.
Actually, it's much more jerky if I set 30Hz on my monitor. You can clearly see difference between jerky opengl and pretty smooth (as it could be on a 30Hz) xv.

**Comment by avih** [comment]
I'll limit this behavior only to cases where the clip and screen rates are within 5% of each other.

**Comment by avih** [comment]
However, this should not be limited to opengl. It's implemented at `vo.c` so it should apply for all types of outputs. It's the global output frame dropping logic.

**Comment by ValdikSS** [comment]
mpv thinks it doesn't drop any frames at all with xv output.

**Comment by wm4** [comment]
>mpv thinks it doesn't drop any frames at all with xv output.

What actually happens is pretty much up to the X server, I think. Here it just means that mpv sent frames to the server soon enough, and that the server had no problems consuming the frames fast enough (unless a warning occurred on the terminal, but mpv doesn't count it as framedrop).

**Comment by wm4** [comment]
@ValdikSS: does the PR above fix it for you?

**Comment by ValdikSS** [comment]
A bit better, but still far from xv.

**Comment by wm4** [comment]
Are you sure Xv isn't just faster?

**Comment by ValdikSS** [comment]
Well, yes. I'm testing with 720×576 SD video windowed, everything is smooth with opengl on 2560×1440@60Hz.

**Comment by ValdikSS** [comment]
And mpv is not as jerky at 44Hz as at 30Hz.

**Comment by avih** [comment]
The reference point should be an mpv build before f174674 (let's call it "old"). If your test case using opengl is the same with the "old" mpv builds and with this PR, then this PR works.

There could be another issue where openGL is less smooth than xv on some cases, but with the PR it should no longer drop two frames at a time with higher-than-screen-rate playback.

**Comment by ValdikSS** [comment]
I'm sorry, I thought you pushed this commit into current master and just rebuild master.
Yes, 24f0c23 fixes the issue. Thank you!

**Comment by wm4** [comment]
Thanks for testing.

**Comment by avih** [comment]
Just to make it clear, the difference between 24f0c23 which he confirmed as fixing the issue and the updated 7cefffe patch is only at the title/description.
