### ISSUE TITLE
How to disable the osc 'partially'?

### ISSUE THREAD

**Issue by leiserfg** [mpv-player/mpv#1900]
I like mpv a lot but I don't like the way the osc 'ui' look like, I wanna write somethink like neflix ui but I don't know how to disable the original osc. How can I do that?

**Comment by wm4** [comment]
``--no-osc``

**Comment by leiserfg** [comment]
Sorry, I did not give you a good explanation of what I wanted. I'm trying to write another "ui osc" in lua. For this I should disable the original, but I have no idea how to do it cleanly. Using --no-osd leave me without the ability to draw with lua, and that's what I need.

**Comment by ChrisK2** [comment]
Uhm, still not sure what you are trying to do. Do you want to add another layout?

If so, just add another function to the layout table (see [Line 725 onwards](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L725)) and then set the name of your layout in the layout option in osc.conf

**Comment by leiserfg** [comment]
I wanna write a new layout and another way to draw the seekbar, but I can't find how can I do it without recompile mpv.

**Comment by ChrisK2** [comment]
Disable the internal OSC script with ``--no-osc`` and put you modified one in the scripts folder, so that one gets loaded.
