### ISSUE TITLE
OSX: mpv hangs at startup

### ISSUE THREAD

**Issue by xeron** [mpv-player/mpv#1901]
MacBook Pro Retina Mid 2014 (SSD, 8 cores, 16GB RAM).
OS X 10.10.3.
mpv from ChrisK build: http://sva.wakku.to/~chris/mpv_builds/mpv_latest.zip

It hangs every startup. Looks like mpv rebuilds font cache every time. It uses 100% CPU for 15-20 seconds after launch and then starts to work.

May be related to #1526.

Spindump: https://gist.github.com/xeron/54a2a42fa80e82d04f22

**Comment by wm4** [comment]
>May be related to #1776.

Is this the wrong issue number, or why do you think this?

**Comment by xeron** [comment]
Yes, sorry, wrong number. #1526 is correct one.

**Comment by xeron** [comment]
I've fixed my initial post to avoid confusing other people.

**Comment by wm4** [comment]
Will be fixed hopefully forever as soon as libass merges the coretext font backend. Closing this as we can't do much about this - unless ChrisK maybe fixes the config, but I don't even know how, or if that would fix this specific issue.
