### ISSUE TITLE
Support open .part files

### ISSUE THREAD

**Issue by akanosora** [mpv-player/mpv#1902]
Partially downloaded files have the .part extension on OS X. I wonder if it is possible to have mpv open these files. I know these are partially completed files but as long as the file header is completed, mpv should be able to recognize its format and play the content. It could be quite useful for previewing partially downloaded videos.

**Comment by Argon-** [comment]
`.part` has nothing to do with the OS. You often can customize software whether to use .part of not (e.g. `--no-part` for youtube-dl).
Also, there's absolutely no problem playing these files with mpv, I did so regularly with videos which were currently being downloaded by youtube-dl?

**Comment by akanosora** [comment]
I think it is the limitation of OS X that it can only play files defined in Info.plist file. I have to add `<string>part</string>` in Info.plist to have mpv play .part files, otherwise it would just quit.
