### ISSUE TITLE
4k Probleme OSX beim starten

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#1904]
Beim starten eines 4K video mit mpv. Wird mpv fenster zu extrem rießen groß, es läuft aus rand raus. Bei anderen Playern wird es richtig angepasst.

**Comment by Argon-** [comment]
http://mpv.io/manual/master/#options-autofit-larger

**Comment by Batteriee** [comment]
Ich weiss das. Aber es sollte beim starten schon gehen und nicht selber hand an legen ;) Nervt total bei Filme schauen in 4K, musst mich immer neu bewegen.

**Comment by Argon-** [comment]
Then you are proposing `--autofit-larger=100%x100%` to be default? Not sure if this is useful. Rather start playback in fullscreen mode, it's not like you watch a 4K movie windowed anyway? And even when you do, you wouldn't use a window with 100% of your screen size.

**Comment by Batteriee** [comment]
Ja man, das beste bei 4k videos standmäßig nur die ''half size''. für mpv OSX. Denkst du jeder kann das mit der anleitung ;) es gibt auch haufen user die sowas nicht selbst können ;) Bitte update!!!

**Comment by Argon-** [comment]
Have you stopped reading after my first question mark?

**Comment by Batteriee** [comment]
Ja man. Mir ist doch nur wichtig das standardmäßig ''half size (window-scale 0.500)'' bei 4K angewendet werden, weil habe hier kein natives 4K Display. Typen mit 4K Display oder höher, dar kannst du es lassen ;)

**Comment by Batteriee** [comment]
Kommt heute noch neue build?

**Comment by CounterPillow** [comment]
Clamping the window to the screen size would give people the ability to easily scale the window by grabbing any of the corners. Just because a video is of 4K resolution doesn't mean people want to watch it at the highest possible resolution.

Worth noting is that this issue appears to be OSX specific, as I cannot reproduce it on KDE, the window automatically gets clamped to the screen size for me.

**Comment by wm4** [comment]
>on KDE, the window automatically gets clamped to the screen size for me.

Yes, we expect the window manager to do this. It's highly inconsistent on Linux, though.

**Comment by Batteriee** [comment]
Hier das meinte ich beim starten eines 4K video auf OSX. Ein richtig fettes Fenster total nervig. Habe echt keine Lust jedes mal cmd+0 (löst half size aus) zu betätigen.

![1](https://cloud.githubusercontent.com/assets/12210134/7446777/8d0822c8-f1e3-11e4-911c-4ad0af6ba62b.png)

**Comment by selsta** [comment]
> Habe echt keine Lust jedes mal cmd+0 (löst 'half size' aus) zu betätigen

Put `autofit-larger=90%x90%` in your config file like suggested above?

**Comment by Batteriee** [comment]
@selsta 
Schreibe ich zu komisch?? Mein Vorschlag war es soll standardmäßig so sein, für alle User. Nicht jeder weisst, wie man mit config Datei es verändert. Es gibt auch normale User xD

**Comment by haasn** [comment]
Solche User laden auch nicht 4K Animus runter, versuchen sie im nicht-vollbildmodus auf einem 1080p Monitor abzuspielen, und beschweren sich dann über das korrekte Resultat. ;)

**Comment by Batteriee** [comment]
@haasn 
Ich schreibe wirklich zu komisch. Es passiert automatisch beim starten eines 4K Video in den Vollbildmodus. Die einzigste Möglichkeit config Datei verändern oder mit Tastenkombination raus aus den Vollbildmodus. Aber das ich nicht mein Plan, sondern es soll bei nicht 4K Monitor schon richtig angepasst sein z.b "half size". Der Vorschlag ging eher an die normalen Usern.
Jetzt verstanden??  :):):)

**Comment by haasn** [comment]
So this happens *in fullscreen* mode as well? That sounds more of a bug to me, fullscreen mode should cover precisely the screen, no more, no less.

**Comment by Batteriee** [comment]
@haasn 
Genau ein Bug. Warum soll ich sonst hier sein xD Habe davor Bild gemacht wie es aussieht beim starten eines 4K Video mit mpv. Ergebnis ein überdimensionales mpv Vollbildfenster. Habe die config Datei nicht angerührt, somit alles auf Standard. Deswegen kam ja mein Vorschlag "half size"

**Comment by selsta** [comment]
It’s not in fullscreen mode, just because the window size is larger than the screen size. Pressing `f` will trigger fullscreen mode.

But your complain is valid, maybe `autofit-larger` could be set by default on OS X.

**Comment by Batteriee** [comment]
@selsta 
Menno! Mein schreiben zu unbekannt xD 
Ganz easy macht update für mpv OSX. Wo 4K Videos so fettes Fenster nicht standardmäßig auslösen.
Der Vorschlag soll an normalen User gehen, womit er nicht mit config Datei beschäftigen muss ;)

**Comment by Batteriee** [comment]
Ihr habt recht. Vollbildmodus ist was anders. Trotzdem meinte ich am Anfangs, das so fettes Fenster kommt, ihr habt mich total verwirrt. mpv nutzt für die Wiedergabe 4K Videos standardmäßig**autofit-larger=200%x200%**. Kein Wunder so ''big big window'' ;)

**Comment by wm4** [comment]
We speak English here.
