### ISSUE TITLE
Englisch -> German mpv OSX

### ISSUE THREAD

**Issue by Batteriee** [mpv-player/mpv#1905]
Audio Track: none = Audiospur: keine
Chapter = Kapitel
Double Size = Doppelte Größe
Half Size = Halbe Größe
Hide mpv = mpv ausblenden 
Minimize = Minimieren
Movie = Video
Normal Size = Normale Größe
Quit mpv & remember position = mpv beenden & letzter Position merken
Quit mpv = mpv beenden
Subtitle Track: none = Untertitelspur: keine
Window = Fenster
Window-scale = Fenster-Skalierung
Zoom = Zoomen

German localizing (By Batteriee)

**Comment by ChrisK2** [comment]
Thanks, but there are no plans to localise mpv.

**Comment by Batteriee** [comment]
Why?? For the future??

**Comment by rrooij** [comment]
@Batteriee 
I don't think that a program for power users like mpv needs translations. However, there are several players that use libmpv that could benefit from translations. What about taking a look at these?

**Comment by Batteriee** [comment]
OK give me site from translation project :)

**Comment by Batteriee** [comment]
Is chris a OSX/iOS developer??
