### ISSUE TITLE
Is the new default screenshot directory correct?

### ISSUE THREAD

**Issue by spaghetti2514** [mpv-player/mpv#1907]
I haven't rebuilt mpv to test this, but commit 756991bd4f78d3a241df1f4fa208d5f55ef95833 sets the screenshot directory in pseudo-gui mode to ```~desktop/```
Doesn't that imply the home directory of the user "desktop"? Shouldn't it be ```~/desktop/```?

**Comment by CounterPillow** [comment]
That doesn't even matter, since the entire screenshot-directory option does not appear to work at all for me when I try with git HEAD.

Did anyone even test this?

**Comment by spaghetti2514** [comment]
>the entire screenshot-directory option does not appear to work at all for me when I try with git HEAD

Just briefly looked at player/screenshot.c
Could be line 283
``` char *dir = ctx->mpctx->opts->screenshot_direcrory; ```
``` screenshot_direcrory ```
**``` direcrory ```**

Just for laughs, try setting the screenshot_direcrory option in your config

**Comment by CounterPillow** [comment]
Setting `screenshot_direcrory` or `screenshot-direcrory` doesn't work either, but I guess it's a good lead as to why `screenshot-direc`**`t`**`ory` doesn't work.

**Comment by spaghetti2514** [comment]
Actually, ```screenshot-directory``` should be fine.
It looks like the "direcrory" variable is at least used consistently
```c
char *screenshot_direcrory;
```
```c
OPT_STRING("screenshot-directory", screenshot_direcrory, 0),
```
```c
char *dir = ctx->mpctx->opts->screenshot_direcrory;
```
So that's probably not why the screenshot-directory option isn't working

**Comment by wm4** [comment]
The screenshot-directory option just works fine here. What is your problem?

Yes, the variable contains a typo, but the user-visible option is fine.

> Doesn't that imply the home directory of the user "desktop"? Shouldn't it be ~/desktop/?

No, because it doesn't do the same expansion as the shell.

**Comment by mc4man** [comment]
Here the default in pseudo-gui mode remains home folder
verbose shows a setting that isn't/can't be achieved? - 
[cplayer] Setting option 'screenshot-directory' = '~desktop/' (flags = 12)

Is desktop meant to be the actual "Desktop" folder or a new desktop folder?
(~ only would work here when in '  '  like in this for actual Desktop folder - 
[cplayer] Setting option 'screenshot-directory' = '~/Desktop' (flags = 12)

**Comment by wm4** [comment]
I changed the prefix.

**Comment by wm4** [comment]
>Here the default in pseudo-gui mode remains home folder

On Linux. Because there's no such thing as a standard location for it. And don'T come me with this XDG crap, it's way too roundabout and I won't bother.

**Comment by CounterPillow** [comment]
In my `.mpv/config`:
```
screenshot-directory=/home/fratti/Pictures/mpv-screens/
```

However, it still writes screenshots to /home/fratti/. The directory ~/Pictures/mpv-screens/ exists. Also, note that I do not have a `desktop`, but only a `Desktop` folder. Might contribute to the issue. 

**Side note:** A good way to get paths to user directories such as the desktop on Linux might be to use [xdg-user-dirs](https://wiki.freedesktop.org/www/Software/xdg-user-dirs/).

**Comment by wm4** [comment]
>However, it still writes screenshots to /home/fratti/. The directory ~/Pictures/mpv-screens/ exists.

Do you set any other config options, like screenshot-template?

>EDIT: Never mind, didn't refresh page and just saw that you didn't want to hear about the "XDG crap".

And this xdg-user-dirs is exactly what I meant with it. As usual, the "Linux desktop"/freedesktop has to have something that is more complicated than what windows or osx do.

**Comment by wm4** [comment]
PS: another thing that came to mind: if you start mpv from the .desktop file, you need to put the option under the ``pseudo-gui`` profile (as described here http://mpv.io/manual/master/#pseudo-gui-mode ).

**Comment by CounterPillow** [comment]
I see, my problem is that I did not put these settings in the pseudo-gui section.

**Comment by wm4** [comment]
This is a bit tricky, and users seem to hit it often. On the other hand, I'm not sure I want to introduce something like per-profile option default values, which would make the code more complex and would not have much value otherwise.

**Comment by CounterPillow** [comment]
I think the options should be processed as follows:

1. Explicit global screenshot-directory option overrides default pseudo-gui option

2. Explicit pseudo-gui option overrides global screenshot-directory option

This is, at least, what I expect, though that's just my own opinion.

**Comment by wm4** [comment]
Look at the mpv.desktop file. It adds ``--profile=pseudo-gui``. The profile can be inspected with ``--show-profile=pseudo-gui`` - the listed options are set. The config file can override these, per section. This is how it works.
