### ISSUE TITLE
Running subprocess failed: init

### ISSUE THREAD

**Issue by chaquator** [mpv-player/mpv#1908]
Happens to me when I activate the following bind I set in input.conf:
`4-d-3-d-3-d-3 show_text "4d3d3d3 Engaged." ; run "C:\\Custom Programs\\mpv\\4d3d3d.bat"`

When I run it, in the console, it says:
`Running subprocess failed: init`

Am I doing something wrong?
I'm on Windows 7

**Comment by wm4** [comment]
Possibly the Windows API doesn't support starting .bat files as executables.

**Comment by Chaquator** [comment]
In that case, I'll make this an ahk script and convert it into an exe.

**Comment by rossy** [comment]
Actually, run should work with .bat files. Windows special-cases files ending in .bat and .cmd and automatically launches the command interpreter. I just tested a similar line in my input.conf and it worked, so I'm not sure why it doesn't work in your case. I'll investigate this.

**Comment by Chaquator** [comment]
Anything I could do help?

**Comment by lachs0r** [comment]
Fixed according to https://github.com/lvml/mpv-plugin-excerpt/issues/2#issuecomment-150876653
