### ISSUE TITLE
Should audio/sub tracks (-aid/-sid options) start counting from 0 or 1?

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#191]
Currently, these start counting from 0, but the OSC (on screen controller, see issue #172) starts from 1, meaning it will show different track numbers than native mpv functionality (including the -aid/-sid options and the terminal output).

For consistency, it would be better if all of mpv follows a single convention.

So which should it be?

**Comment by wyatt8740** [comment]
Is there any way to reverse this???

It's driving me absolutely insane and breaking my scripts that I'm trying to port from mplayer.
