### ISSUE TITLE
OSX and Macbook Pro - trackpad scroll always seeks forward?

### ISSUE THREAD

**Issue by victorhooi** [mpv-player/mpv#1915]
I'm using `mpv` 0.9.1 with OSX, and a Macbook Pro.

I've noticed that no matter what I do with the trackpad (i.e. left or right, up or down), any of those motions just cause the video to seek forwards. It's very odd.

In comparison, I noticed on VLC that up/down on the trackpad (or mouse wheel, I would assume) control volume, and left/right control seeking forwards/backwards.

I did notice in the mpv manpage:

> Mouse Control
> button 3 and button 4
> Seek backward/forward 1 minute.
> button 5 and button 6
> Decrease/increase volume.

I'm not really sure if those equate to the same as VLC - but I'm guessing they shouldn't all be seeking forward.

Any ideas to figure out what's going on with `mpv` here?

**Comment by selsta** [comment]
Put these in the input.conf:
```
AXIS_UP ignore
AXIS_DOWN ignore
AXIS_LEFT ignore
AXIS_RIGHT ignore
```

**Comment by wm4** [comment]
Works just fine for me.

**Comment by victorhooi** [comment]
@selsta Hmm, that seems to disable any actions from scroll left/right/up/down on the trackpad - is that what you mean?

@wm4 Ok, that is odd - this is a fairly fresh install of OSX 10.10.4, with mpv 0.9.1 from homebrew.

Are you also on OSX with a Macbook Pro?

So you're saying that scroll left/right seeks, and scroll up/down controls volume? Do you mind sharing your input.conf and/or mpv.conf, in case that sheds any light? (I'm hoping it's just a configuration setting I need to get them to work).

**Comment by wm4** [comment]
Hm, scrolling up/down gives the expected result, but scrolling left/right is inverted. I assume for whoever added this on Linux, it was in the correct direction.

**Comment by wm4** [comment]
@victorhooi: I tested this on osx 10.10.3 on a macbook pro, yes.

The touchpad triggers the AXIS_... key bindings, at least the way it's implemented in mpv.

**Comment by selsta** [comment]
@wm4 
Left/right works like expected for me. Do you have “Scoll direction: natural” enabled?
![screen shot 2015-05-04 at 14 03 43](https://cloud.githubusercontent.com/assets/7697454/7453142/73eca59c-f266-11e4-8e8c-83da3fce7bed.png)

**Comment by wm4** [comment]
> Do you have “Scoll direction: natural” enabled?

Yes. Disabling it reverses the scroll direction on both axises.

**Comment by Cpuroast** [comment]
I use the following settings in my input.conf without "natural" scroll direction:
Works great for me, you can omit "osd-msg-bar" if you don't want to see the progress bar while seeking.

# TrackPad Normal Scroll Direction
AXIS_LEFT  osd-msg-bar seek  5
AXIS_DOWN  osd-msg-bar seek  30
AXIS_RIGHT osd-msg-bar seek -5
AXIS_UP    osd-msg-bar seek -30

**Comment by victorhooi** [comment]
Awesome stuff - thanks everybody for their tips.

This is what I ended up putting in `~/.config/mpv/input.conf` - I use "natural" scrolling in OSX:
```
AXIS_LEFT osd-msg-bar seek -5
AXIS_RIGHT osd-msg-bar seek 5
AXIS_UP add volume -5
AXIS_DOWN add volume 5
```
So left and right give me seek, and up/down give me volume adjustment (similar to VLC's default).

As an aside - I'd be curious to see if I could use the new Force Touch trackpad (https://support.apple.com/en-au/HT204352) to change seek speed, but that might be a separate ticket =).
