### ISSUE TITLE
Border around full screen window visible on other monitors, only with "fs" option

### ISSUE THREAD

**Issue by Lamieur** [mpv-player/mpv#1920]
Hi, I have "fs" option in my mpv.conf, but every time it starts in full screen mode, there's a 4 pixel border around it, visible on the display next to it. The border captures screen contents when MPV started and stays on top of programs on that screen (so I have trouble using scroll bar of a browser on the left screen :))

Pressing "f" twice to go to window mode and back to full screen fixes the problem.

Using "no-border" in the config also fixes the problem, but I prefer to have the border in window mode, just not full screen.

I thought maybe it depends on vo, so I've tried vo=vdpau, vo=opengl and vo=xv (last case ignored hwdec=vdpau). Nothing changed.

This happens whether or not I use "geometry" or "screen" setting to put it on a different screen. Whichever screen it starts on, I will see a border on the other, which disappears after double-f.

This behavior was here in 0.6/0.7, but I hoped 0.8 update will fix it. Now that 0.8.3 landed in Fedora repositories, I'm finally reporting it.

This is MATE+Marco, not compositing (probably important).

**Comment by wm4** [comment]
I'd say this is the window manager's fault. mpv doesn't attempt to remove borders when fullscreening, but it shouldn't need to do that. Fullscreening basically works by telling the window manager that the application wants to go fullscreen, and the WM takes care of resizing and positioning the window etc..

Also, the newest version is 0.9.1, not 0.8.3. But this probably doesn't change anything about this.

**Comment by Lamieur** [comment]
You're right, if I replace Marco with Openbox (openbox --replace), the border disappears. Then I do marco --replace and it re-appears as it takes control of the full-screen window. I never thought of that.

Well, it would still be sweet if it was possible to add a work-around: make it open full screen like it does when pressing "f", as that's supported correctly. But I will understand if you reject this.

**Comment by wm4** [comment]
Well, I'm not sure why initial fullscreen switching would be different from fullscreen switching at runtime, but technically we do these differently. We want initial fullscreen switching to happen atomically when the window becomes visible, and we do this by setting the ``_NET_WM_STATE_FULLSCREEN`` on the (unmapped) window manually. Runtime switching on the other hand is done by sending a ``_NET_WM_STATE`` message.

The way we handle the initial fullscreen state might not be completely standard.

Maybe you can talk to the devs of your WM?

**Comment by wm4** [comment]
I added a workaround, and hope this fixes it.

It would still be nice if mate-desktop supported atomic fullscreening, though.

**Comment by Lamieur** [comment]
I know it's late but I confirm: it actually helped! Thank you.

(There's now a new minor issue with going out of full screen but unrelated to this fix imho.)

**Comment by wm4** [comment]
Thanks for letting us know.

**Comment by haasn** [comment]
This also fixes any compatibility issues I had between mpv's fullscreen mode and xmonad. (In the past, the problem was also that xmonad ignored fullscreen state changes that happened while the window wasn't mapped)
