### ISSUE TITLE
Video equalizer 'unavailable' in vo=xv

### ISSUE THREAD

**Issue by javimixet** [mpv-player/mpv#1922]
Hi. I'm in a Lubuntu 14.04 64bit eeepc 1005p where playing a video file in mplayer with option "-vo xv" allows contrast, brightness, gamma and saturation adjustments (with 1-8 keys). Thins option in mpv "--vo=xv" shows the message "contrast=(unavailable)" when I press keys 1 or 2, and the same with brightness, gamma and saturation shortcuts.
Is this the expected behaviour? Can I do something to change it or it's not posible to use the equalizer when vo=xv?
Thanks.

**Comment by wm4** [comment]
Yes, it's expected if the hardware/driver doesn't support these controls. You can start mpv with ``--vf=eq`` to get most of them back. It will be slightly slower.

This shouldn't be any different from mplayer, though.

**Comment by javimixet** [comment]
Ok. It works with --vf=eq.
Thanks.
