### ISSUE TITLE
Every time the the osd are showed it's eating memory.

### ISSUE THREAD

**Issue by leiserfg** [mpv-player/mpv#1924]
mpv don't consume too much memory but if i move the mouse over the window the memory consumption grows up. I remove all my configurations and look at the task manager, and the memory aument around 1M each time osd are showed. I put `osc=no` on my mpv.conf and the memory becomes stable, so the problem comes  from the osd implementation.

**Comment by wm4** [comment]
Not a real leak... this is https://github.com/libass/libass/issues/53

**Comment by leiserfg** [comment]
What about using officially a previous libass until that bug are fixed?

**Comment by wm4** [comment]
>What about using officially a previous libass until that bug are fixed?

We don't even support that anymore.

**Comment by wm4** [comment]
I think there was a real drawing leak that got fixed in libass (not sure how severe). Anyway, this is a libass issue.
