### ISSUE TITLE
mkv Ordered Chapters get loaded recursively which breaks some files

### ISSUE THREAD

**Issue by ChrisK2** [mpv-player/mpv#1925]
It appears that mpv is inserting segments based on their own virtual timeline instead of the file timeline (ignoring any chapters). I was told this was a feature, however it seems to be inconsistent with Haali's way of doing things (flat linking), which causes a few files in the wild to break.

If the recursive behaviour is actually needed for some cases, I suggest to add an option for it and disable it by default.

@mathstuf I was told you may know something about this.

**Comment by mathstuf** [comment]
Do you have example files? It sounds like a bug. If a ordered chapter references another ordered chapter, I'm pretty sure you need to do it recursively to DTRT. For example, a stub mkv with a single edition which references episodes which are themselves stubs but which then put together split opening, episode, and epilogue files.

**Comment by ChrisK2** [comment]
I do, but they are a bit big.
They look like this:
We have a file for each Episode, one each for Opening and Ending and a PlayAll file.
The Episode files each link in the Opening and Ending, so far so good.

The PlayAll file is supposed to link the Opening, the MainParts of each Episode and then the Ending. However, during the MainPart chapters, the Opening (linked in by the individual Episode files) appears AGAIN (and the time taken up by the opening is missing at the end of the Chapter).

I can send you a download link to the files via eMail if necessary.

**Comment by mathstuf** [comment]
On Fri, May 08, 2015 at 06:36:59 -0700, ChrisK2 wrote:
> I do, but they are a bit big.
> They look like this:
> We have a file for each Episode, one each for Opening and Ending and a PlayAll file.
> The Episode files each link in the Opening and Ending, so far so good.
> 
> The PlayAll file is supposed to link the Opening, the MainParts of
> each Episode and then the Ending. However, during the MainPart
> chapters, the Opening (linked in by the individual Episode files)
> appears AGAIN (and the time taken up by the opening is missing at the
> end of the Chapter).

It sounds like the PlayAll either doesn't reference the right edition or
use the right time offsets.

> I can send you a download link to the files via eMail if necessary.

Extracting the metadata from the files should be sufficient. As well as
the length of each file; I don't think that's explicit in the XML.

**Comment by ChrisK2** [comment]
Here, see fileinfo.txt at the bottom for info on each file: https://gist.github.com/ChrisK2/361808ef206e44d80022

**Comment by mathstuf** [comment]
On Fri, May 08, 2015 at 07:29:09 -0700, ChrisK2 wrote:
> Here, see fileinfo.txt at the bottom for info on each file:
> https://gist.github.com/ChrisK2/361808ef206e44d80022

Thanks. It appears as though things look good file-wise. The bug in mpv
is that if a file has an edition, it is picked up even if the ordered
chapter doesn't reference it. Instead, if there is no target edition, it
should just use the video segment directly without any edition logic.

**Comment by mathstuf** [comment]
On Fri, May 08, 2015 at 10:44:31 -0400, Ben Boeckel wrote:
> Thanks. It appears as though things look good file-wise. The bug in mpv
> is that if a file has an edition, it is picked up even if the ordered
> chapter doesn't reference it. Instead, if there is no target edition, it
> should just use the video segment directly without any edition logic.

FWIW, I had never seen this in my testing because I've always made
explicit editions for everything and referenced them directly.

**Comment by wm4** [comment]
Also note that I heavily refactored this code, so it's possible that I broke it at some point.
