### ISSUE TITLE
Failing to take screenshots with VAAPI results in image corruption

### ISSUE THREAD

**Issue by oniichaNj** [mpv-player/mpv#1926]
When failing to take a screenshot (for example, being in a directory without the permissions to write it), and using hwdec=vaapi, the video that's currently being played back starts corrupting and flickering. This happens to all files, even with youtube-dl and livestreamer.

    mpv --no-config --hwdec=vaapi file.mkv

![2015-05-08-18 57 57-screenshot](https://cloud.githubusercontent.com/assets/3495385/7542951/1de825fa-f5c1-11e4-8e95-ed3a75cc0337.png)
(above screenshot taken with scrot)

Here's what it says:

    Screenshot: 'mpv-shot0001.jpg'
    Error opening 'mpv-shot0001.jpg' for writing!
    Error writing screenshot!
    AV: 00:00:06 / 00:22:35 (0%) A-V: -0.000 Cache: 10s+4096KB
    [ffmpeg/video] h264: hardware accelerator failed to decode picture
    AV: 00:00:07 / 00:22:35 (0%) A-V: -0.000 Cache: 10s+4096KB
    [ffmpeg/video] h264: hardware accelerator failed to decode picture
    AV: 00:00:00 / 00:22:35 (0%) A-V:  0.000 Cache:  9s+4096KB
    [ffmpeg/video] h264: hardware accelerator failed to decode picture
    AV: 00:00:00 / 00:22:35 (0%) A-V:  0.000 Cache:  9s+4096KB

This isn't a big issue but something's probably wrong somewhere.

**Comment by wm4** [comment]
Can't reproduce, and can't see how it would happen either.

**Comment by wm4** [comment]
Tried with both mpv 0.9.1 and mpv git with both a native intel vaapi driver and the vdpau wrapper, can't reproduce in any case.

**Comment by oniichaNj** [comment]
I can't reproduce on any other machines either. It might be worth noticing that I'm on a GMA 4500MHD and I'm using the g45-h264 branch as described [here](https://www.linuxsystems.it/2012/05/gentoo-g45-gm45-h264-vaapi-video-decoding/). I think that's probably the issue here.
