### ISSUE TITLE
Low sound on MacBook Pro Retina 2015

### ISSUE THREAD

**Issue by Symevo** [mpv-player/mpv#1928]
Could you help me with such a problem:
how can I increase volume in mpv if when playing some films (Macbook Pro Retina 2015, OS X Yosemite 10.10.3) 100% loudness is still very quiet?

**Comment by ChrisK2** [comment]
``-af=drc``

**Comment by Symevo** [comment]
I changed my PC to Mac two days ago. That's why unfortunately I don't understand what you mean. I can suppose that I have to open terminal and enter these commands. Would you be so kind to explain step by step what exactly I have to do

**Comment by rrooij** [comment]
@Symevo 
You can add `af=drc` to your mpv config file.

I don't know where it is located by default on Mac OS X. (On my system, it is in `~/.config/mpv`.)

ChrisK2 suggested using this filter as a command line option, you could use it like this:

`mpv --af=drc [your_file_to_be_played.mkv]` (without the square brackets of course)

**Comment by wm4** [comment]
Maybe this is due to downmixing. Recently we enabled normalization, which tends to make the output more silent.

**Comment by wm4** [comment]
Still unknown what the problem actually is.
