### ISSUE TITLE
OSD does not appear in screenshot

### ISSUE THREAD

**Issue by Power-Inside** [mpv-player/mpv#1929]
Maybe this isn't a feature implemented, but it would make sense to include OSD in the screenshot (like the timer).. provided that the OSD can be toggled off themselves ("O" keybind) and thus gives the flexibility to the user whether he wants a screenshot with/without OSD. (The default "S" keybind for capturing only the video screenshot thus becomes redundant)

**Comment by Zehkul** [comment]
[screenshot window](http://mpv.io/manual/master/#command-interface-[single|each-frame]])

**Comment by Power-Inside** [comment]
Oh.. sorry I didn't notice that! Thanks but aren't they command line options and how can I invoke it during playback in realtime? (like "s" keybind?)

**Comment by Power-Inside** [comment]
Thanks! I should learn to go through man pages completely. I stopped at the first block of text regarding "screenshot" while I `man mpv` and didn't bother to hit "next" to find more on it.

That being said, I think a keybind for "s" being `screenshot window` instead of the default `screenshot subtitles` could be better and IMO, it's like a "WYSIWYG" approach and gives more control to the user.
