### ISSUE TITLE
[RFC] Change the OSC default layout

### ISSUE THREAD

**Issue by wm4** [mpv-player/mpv#1931]
Here's my suggestion:
- use the `bottombar` layout
- set `deadzonesize` to 1 or close

**Comment by ChrisK2** [comment]
> use the bottombar layout

If the majority of people prefer it, fine with me. However, there need to be some alignment and design issues fixed first, e.g. the elements one the lower "bar" aren't properly aligned along a central axis and the seekbar tooltip overlays the video title in an ugly and hard to read way. Also, I probably won't maintain that layout.

>set deadzonesize to 1 or close

Yes, this improves things, however the reason for not making this the default was to make it easier for new users to "find" the OSC. Again, if no one cares about this, we can change it.

**Comment by Argon-** [comment]
Even though I personally prefer a different layout as well, I think the current default is resembling a "classic" (or rather "expected"?) video player GUI the most and is therefore fine as default (same applies for "show up on mouse move"). And wasn't this the primary purpose of the OSC anyway?

**Comment by mc4man** [comment]
Your current default deadzone is more annoying than useful. 
If 1 is too low than .75 or .8 would be vastly better  than 'everywhere'

**Comment by wiiaboo** [comment]
Would suggest also changing `minmousemove` to either 0 or 1 along with `deadzonesize=1`.

With the current default the seekbar seems to randomly disappear while you're moving and hardly shows up again unless you happen to be fast enough to move the mouse inside the osc while it's visible.

**Comment by wm4** [comment]
>Yes, this improves things, however the reason for not making this the default was to make it easier for new users to "find" the OSC. 

I don't think this would be much of a problem. Whether it's obvious (current layout), or slightly less obvious (bottombar layout) shouldn't matter too much. Especially considering further configuration of mpv is several magnitudes harder for the user anyway.

**Comment by rrooij** [comment]
I agree. The default layout now is better for HTPC, but bottombar is more suitable for a desktop in my opinion. 

bottombar should be the default, it's also more or less the standard in other players as far as I know.

**Comment by wm4** [comment]
Depends on #2093.

**Comment by ChrisK2** [comment]
Btw, if we change the layout, the manual part that explains each button also needs to be updated ... somehow.

**Comment by mc4man** [comment]
2093 is stalled or dead but changing deadzonesize to 1 is just a sec's work
