### ISSUE TITLE
Fullscreen option doesn't work right

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv#1937]
If I play a video with Fullscreen option the video start in windowed mode. 
If I press F nothing happen.
If I press again F the video switch in Fullscreen

But if I enable vf=expand=::::16/9 the Fullscreen option works normaly

I'm on Netrunner 14 x64 (Kubuntu 14.04 derivative) with nvidia 349.16 drivers and MPV 0.91

**Comment by wm4** [comment]
Added a workaround, I hope it works now.

**Comment by Paviluf** [comment]
Thank you I will try.
