### ISSUE TITLE
Crash with VapourSynth and vf=expand=::::16/9 option

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv#1938]
With some videos, at least in SD, I have this error with VapourSynth and vf=expand=::::16/9 option.

mpv: malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.

Without vf=expand=::::16/9 option the video is played.
I'm on Netrunner 14 x64 (Kubuntu 14.04 derivative) with nvidia 349.16 drivers, MPV 0.91 and VapourSynth 27

**Comment by wm4** [comment]
Can't reproduce.

**Comment by Paviluf** [comment]
OK, does MPV should be rebuild if VapourSynth is updated ?

It happen at least with this video http://trailers.apple.com/movies/paramount/wolfofwallstreet/thewolfofwallstreet-tlr2_h480p.mov

**Comment by wm4** [comment]
>It happen at least with this video http://trailers.apple.com/movies/paramount/wolfofwallstreet/thewolfofwallstreet-tlr2_h480p.mov

I don't know how to download this.

**Comment by Paviluf** [comment]
Simply click on the link, it work for me. Or maybe right click, save ?

**Comment by wm4** [comment]
No. Clicking it shows a website.

**Comment by Paviluf** [comment]
Ok I upload it here :
http://www.mediafire.com/watch/j37n75mfcjmimaj/thewolfofwallstreet-tlr2_h480p.mov

Does MPV should be rebuild if VapourSynth is updated ?

**Comment by mc4man** [comment]
to play such vids directly in mpv one would need to set a user-agent, ex
 mpv  --user-agent 'QuickTime/7.6.2 (qtver=7.6.2;os=Windows NT 5.1Service Pack 3)' <the apple-trailer url>

**Comment by wm4** [comment]
The crash happened because VapourSynth doesn't like videos cropped by uneven amounts. Now the filter fails to initialize, instead of crashing hard.

>to play such vids directly in mpv one would need to set a user-agent, ex

mpv's ytdl wrapper script already sets the user-agent suggested by youtube-dl, so I wonder why youtube-dl doesn't support downloading these trailers by setting the user-agent to something compatible.

**Comment by mc4man** [comment]
It will play from that site using the wrapper as long as one isn't that specific, ex.'s - 
only one vid avail.-
 mpv http://trailers.apple.com/trailers/ifcfilms/manglehorn/

The page from orig. here (4? vids) - 
mpv http://trailers.apple.com/trailers/paramount/thewolfofwallstreet/

**Comment by Paviluf** [comment]
> The crash happened because VapourSynth doesn't like videos cropped by uneven amounts. Now the filter fails to initialize, instead of crashing hard.
Thank you
