### ISSUE TITLE
Launch player window for pure audio

### ISSUE THREAD

**Issue by zmwangx** [mpv-player/mpv#1939]
I'm using mpv 0.9.1 on OS X, and as far as I can tell, there's no way to launch a player window for pure audio (without video stream or image attachment). Since I typically redirect mpv's stderr to `/dev/null` (I log my terminal sessions, and logs grow too fast when I allow mpv to print progress to tty), it is hard to tell where I am in the audio stream. Also, I find the OSC more helpful than mere keyboard shortcuts at times, even for pure audio playback.

Is it possible to add an option to launch player window even for pure audio (or did I miss anything)? A blank/black window should be enough, although audio visualization will be even better (`ffplay` does that).

Alternatively, is it possible to generate a video stream on the fly? I tried some `lavfi` video sources and multimedia filters, but no luck. The same filters, e.g., `color` or `showwaves`, do work on `ffplay`; maybe I'm just specifying them the wrong way for mpv.

**Comment by wm4** [comment]
``--force-window``.

Using ``av://lavfi:graph`` should work (with graph replaced by something appropriate), but I guess this is very hard to use.

mpv might get audio visualization via lavfi in the far future, although it's very low priority.

**Comment by zmwangx** [comment]
I did search "window" in the manpage, but for some unknown reason I missed the option (facepalm). Maybe because it's 3am. Sorry.
