### ISSUE TITLE
`--shuffle --loop=inf` only shuffles once

### ISSUE THREAD

**Issue by chengsun** [mpv-player/mpv#194]
Currently it shuffles the playlist once at the beginning, and loops the same shuffled order again and again.
Expected behaviour is that it re-shuffles the playlist every time the playlist is looped.

**Comment by qm3ster** [comment]
I'm sorry, but both this and #803 are solved by having a queue and a playlist.

**Comment by wm4** [comment]
I'm inclined to say that if you want such advanced behavior, either script it yourself, or use a libmpv-using app which was designed with user/playlist interaction in mind (such as mpc-qt).
