### ISSUE TITLE
Filenames with spaces not accepted when given to input pipe

### ISSUE THREAD

**Issue by hashken** [mpv-player/mpv#1940]
Mpv has the option to send input commands through a named pipe. I tried adding a subtitle file to a currently playing file using the `sub_add` input command. But, when i execute the following

    echo sub_add "Age of Dawn.srt" > input_fifo

I get the following error  

    [input] Invalid value for option sub_add: of
    [input] Valid values are:
    [input]     select
    [input]     auto
    [input]     cached
    [input] Command sub_add: argument 2 can't be parsed: option could not be parsed.
    [input] Command was defined at input_file.

**Comment by wm4** [comment]
What mpv receives is ``sub_add Age of Dawn.srt``. The shell and the echo command obviously drop the quotes.

If you do something slightly more complicated or want more robustness, I recommend using the json ipc protocol.

**Comment by wm4** [comment]
Oh, and to elaborate on the sub_add command: it's in a way pretty similar to the shell, and the filename argument needs to be 1 argument. In your example, the space between ``Age`` and ``of`` make it interpret ``of`` as second argument.

**Comment by hashken** [comment]
Yeah, that' true. I just thought there should be a way to send filenames with spaces in them

**Comment by wm4** [comment]
Yes, because this stops the shell from removing the inner quotes.
