### ISSUE TITLE
The option sub-scale is not applied when the subtitle position change

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv#1941]
With a .srt (didn't test other formats) if the subtitle position is specified the option sub-scale is not applied.
.srt sample :

1
00:00:00,100 --> 00:00:04,000
{\pos(192,216)}This is a test.
This is a test.

2
00:00:04,200 --> 00:00:07,000
- This is a test.
- This is a test.

**Comment by wm4** [comment]
Feature, not a bug.

**Comment by Paviluf** [comment]
Why ? It's not concistent, when the subtitle change position it can be a lot bigger or smaller depending on the user config.
If you want keep this feature maybe it could be interesting to add an option to always apply sub-scale ?

**Comment by wm4** [comment]
There was something with force-style.

Anyway, this request makes no sense. These subtitle scripts match positions exactly to the video, and there's no reason to break that. If you use vf_expand, don't. It's known to break this.

**Comment by Paviluf** [comment]
I understand that for you it makes no sense and I respect that. But can you try to understand that for me and probably some peoples a simple option to always have the subtitle at the same size make sense ?

It would be very kind if we can have a little option to do that.
