### ISSUE TITLE
How to build dylib into my OSX application

### ISSUE THREAD

**Issue by skydreamever** [mpv-player/mpv#1942]
I only want use mpv in my own OSX application, so I copy client.h and dylibs from mpv.app-->Contents-->MacOS, but it not work when i use client.h. What should I do?

**Comment by wm4** [comment]
If you downloaded e.g. ChrisK's mpv build, it doesn't include the library required to use mpv via client API. You need to build mpv yourself. Follow the normal compilation steps, except configure it with ``./waf --enable-libmpv-shared``.
