### ISSUE TITLE
How do I enable interpolation?What is the difference between interpolation and smoothmotion

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#1943]
like this?
mpv --vo=opengl-hq:interpolation filename
Do I need to add more commands?

what is the difference between smoothmotion and interpolation?

**Comment by ChrisK2** [comment]
https://github.com/mpv-player/mpv/wiki/Interpolation

**Comment by wm4** [comment]
> Do I need to add more commands?

No, this should be sufficient.

>what is the difference between smoothmotion and interpolation?

See wiki link posted above.
