### ISSUE TITLE
How do I set the rules for  config file?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#1946]
vo=opengl-hq:interpolation:scale=ewa_lanczossharp:icc-profile-auto

It is my setting of config file, it seems that every time I open a video would load this setting,
but I don't need the interpolation when my video is 29.97fps or 59.94fps, can I do it in the config file?

**Comment by kevmitch** [comment]
There is currently no way to do this setting aside the fact that reliably determining the *actual* frame rate is non-trivial. Stuff from a dvd for example might switch betwee 24/30 fps or have a completely variable frame rate.

I would say that you could try writing a lua script that reads the estimated-vf-fps property, but I'm not sure there's currently a way to change opengl parameters at runtime (though there is talk of it).

In any case, (someone correct me if I'm wrong, but) I'm pretty sure with the default tscale=oversample, interpolation is a no-op when the frame rate matches the refresh rate.

**Comment by wm4** [comment]
That is all correct.

**Comment by wm4** [comment]
> but I'm not sure there's currently a way to change opengl parameters at runtime

Only via vo_cmdline.
