### ISSUE TITLE
ad_spdif: Use only DTSHD if profile is HD audio

### ISSUE THREAD

**Issue by maniacgit** [mpv-player/mpv#1949]
With my new AV receiver I've the issue if a standard DTS track is played with the parameters of DTSHD (da->opts->dtshd is true in ad_spdif) then only 2 channels are used by the receiver, DTSHD plays fine.

If I play the same with dtshd disabled the standard DTS plays fine but for DTSHD the standard DTS is used (correct behaviour).

But I want to play DTSHD if available and if only standard DTS is available it should work also without changing the command line of mpv.

I think the stream->codec->profile could be used for this. In case of FF_PROFILE_DTS_HD_MA and  FF_PROFILE_DTS_HD_HRA the HD parameters should be used. For other profiles it should use the standard DTS parameters.

**Comment by wm4** [comment]
The problem is that with Matroska, we don't have the profile available. (And I think in general, the demuxer shouldn't have to provide such information.)

**Comment by maniacgit** [comment]
Do we have another possibility to get this information? I think we need it there to correctly set up the parameters.

**Comment by wm4** [comment]
Possibly it could be done by using libavcodec to parse the incoming packets in ad_spdif.c. Initialization would have to be delayed to happen on the first packet (which requires minor restructuring in ad_spdif.c).

**Comment by wm4** [comment]
These are the DTS profiles ffmpeg know (both builtin and libdadec decoders):
```
    { FF_PROFILE_DTS,         "DTS"         },
    { FF_PROFILE_DTS_ES,      "DTS-ES"      },
    { FF_PROFILE_DTS_96_24,   "DTS 96/24"   },
    { FF_PROFILE_DTS_HD_HRA,  "DTS-HD HRA"  },
    { FF_PROFILE_DTS_HD_MA,   "DTS-HD MA"   },
    { FF_PROFILE_DTS_EXPRESS, "DTS Express" },
```
Which should use the high bitrate setting?

**Comment by maniacgit** [comment]
{ FF_PROFILE_DTS_HD_HRA,  "DTS-HD HRA"  },
    { FF_PROFILE_DTS_HD_MA,   "DTS-HD MA"   },
