### ISSUE TITLE
The subtitle size change when the subtitle position change

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv#1951]
I noticed that the subtitle size change, in fullscreen, when the subtitle position change and the video ratio is not the same as the screen.

With a 16/9 screen and a 16/9 video the subtitle size seems to be consistent but with 2.35:1 video in fullscreen the subtitle size change with no reason.

I tried with an empty config file and it's the same (same sub for both video) :

![mpv-shot0001](https://cloud.githubusercontent.com/assets/2451563/7670567/2124dbf6-fcaa-11e4-9bb6-b154c35350b0.jpg)
![mpv-shot0002](https://cloud.githubusercontent.com/assets/2451563/7670569/21268b2c-fcaa-11e4-8bb3-bf1a763b899b.jpg)
![mpv-shot0003](https://cloud.githubusercontent.com/assets/2451563/7670568/21266476-fcaa-11e4-91ad-4261f440bb7d.jpg)
![mpv-shot0004](https://cloud.githubusercontent.com/assets/2451563/7670566/2124132e-fcaa-11e4-820f-dbf6497db1a5.jpg)

**Comment by Paviluf** [comment]
wm4, what infos do you need ?

**Comment by wm4** [comment]
mpv version, what kind of subtitles, etc.

I can't reproduce your findings.

**Comment by Paviluf** [comment]
- MPV built from git (last commit a4f3df5)
- No MPV config
- Netrunner 14 x64 - Nvidia 349.16
- .srt Subtitle :
```
1
00:00:00,100 --> 00:00:04,000
{\pos(192,216)}This is a test.
This is a test.

2
00:00:04,200 --> 00:00:07,000
This is a test.
This is a test. 
```

**Comment by wm4** [comment]
>{\pos(192,216)}This is a test.

Not valid srt. You're also not saying for which of these events you observe this. Anyway, it works with normal srt.

**Comment by Paviluf** [comment]
When this {\pos(192,216)} is used on a 2.35:1 video the subtitle is smaller.
The srt format don't integrate this, you are right, but it's widely used like a standard.
Maybe it can be usesul to make it works right ?

**Comment by wm4** [comment]
It does work right. End of discussion.

**Comment by wm4** [comment]
PS: where did you get this subtitle file from? I just want to know who to blame for this absurd shit. Either way, using \pos in srt will give random results and nobody who is creating this file should be surprised that different players handle it differently.

**Comment by Paviluf** [comment]
Here for exemple (the ones ending with .TAG.srt) : 
https://www.sous-titres.eu/series/download/t87ho69h5depr2x/Orphan.Black.3x04.FR.BUFGELF.zip
It's relatively spread on the web... 

> It does work right. End of discussion.
You are a fantastic developer and I really appreciate your work but you're not very open to debate ;)

**Comment by wm4** [comment]
How nice, mixed ASS and HTMl tags in srt, and the files are encoded in a 8 bit codepage too. In this case, it's simple - ignore the TAG files. The distributors of these files are complete idiots.

**Comment by Paviluf** [comment]
Ok I will stick to simple srt or ass.
Thank you

**Comment by wm4** [comment]
For your information, it _does_ work because \pos is used for explicit positioning, which is of course always within the video frame, not the screen.

And now I hope never to hear about ASS tags in SRT again.
