### ISSUE TITLE
Can't view HTTP MJPG streams

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [mpv-player/mpv#1955]
When trying to view an HTTP MJPG stream (such as produced by some web cameras), MPV doesn't work.

Both Pale Moon (a Firefox fork) and VLC Media Player can view the URLs I tested. But not MPV for some reason.

Here's a relevant sample of the log with the `-v` flag:

````
…
[lavf] Found 'mjpeg' at score=25 size=131072.
[lavf] Found 'mjpeg' at score=25 size=262144.
[lavf] Found 'mjpeg' at score=25 size=524288.
[lavf] Found 'mjpeg' at score=25 size=1048576.
[lavf] Found 'mjpeg' at score=25 size=2097152.
[lavf] Found 'mjpeg' at score=25 size=2097152.
[lavf] No format found, try lowering probescore or forcing the format.
[demux] Trying demuxer: mf (force-level: normal)
[demux] Trying demuxer: playlist (force-level: normal)
[demux] Trying demuxer: subreader (force-level: normal)
[demux] Trying demuxer: disc (force-level: unsafe)
[demux] Trying demuxer: edl (force-level: unsafe)
[demux] Trying demuxer: cue (force-level: unsafe)
[demux] Trying demuxer: rawaudio (force-level: unsafe)
[demux] Trying demuxer: rawvideo (force-level: unsafe)
[demux] Trying demuxer: tv (force-level: unsafe)
[demux] Trying demuxer: libass (force-level: unsafe)
[demux] Trying demuxer: mkv (force-level: unsafe)
[demux] Trying demuxer: rar (force-level: unsafe)
[demux] Trying demuxer: lavf (force-level: unsafe)
[lavf] Found 'mjpeg' at score=25 size=131072.
[lavf] Found 'mjpeg' at score=25 size=262144.
[lavf] Found 'mjpeg' at score=25 size=524288.
[lavf] Found 'mjpeg' at score=25 size=1048576.
[lavf] Found 'mjpeg' at score=25 size=2097152.
[lavf] Found 'mjpeg' at score=25 size=2097152.
[lavf] No format found, try lowering probescore or forcing the format.
[demux] Trying demuxer: mf (force-level: unsafe)
[demux] Trying demuxer: playlist (force-level: unsafe)
[demux] Trying demuxer: subreader (force-level: unsafe)
[cplayer] Failed to recognize file format.
…
````

Full log at http://p.pomf.se/7543

**Comment by wm4** [comment]
FFmpeg doesn't support all types of such streams. AFAIK Libav plans to add support for at least 1 type, and there are WIP patches.

**Comment by JamesTheAwesomeDude** [comment]
So this is an upstream (ffmpeg) bug which is in the process of being resolved, correct?

**Comment by wm4** [comment]
Yes/probably.

Do you have an example URL for such a stream?

**Comment by JamesTheAwesomeDude** [comment]
The one specifically which the logs I posted were acquired using is http://151cam.uoregon.edu/mjpg/video.mjpg (this can be most likely be viewed in your browser.)

**Comment by JamesTheAwesomeDude** [comment]
The latency when doing this is much increased, but `ffmpeg -i http://151cam.uoregon.edu/mjpg/video.mjpg -pix_fmt rgb24 -f rawvideo - | mpv - --quiet --demuxer=rawvideo --demuxer-rawvideo-mp-format=rgb24 --demuxer-rawvideo-w=640 --demuxer-rawvideo-h=480 --demuxer-rawvideo-size=921600` works.

So ffmpeg seems to have no problems with MJPG - I did not need to add any flags to help with the MJPG decoding. Why does MPV (0.9.1) not work by itself, then?

````
$ mpv -V
mpv 0.9.1 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-04-30T00:23:25
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100
$ ffmpeg 
ffmpeg version 2.6.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
$ 
````

**Comment by JamesTheAwesomeDude** [comment]
@wm4 Here's the output from `ffmpeg -loglevel 56 -i http://151cam.uoregon.edu/mjpg/video.mjpg -vframes 1 -f rawvideo -y /dev/null`: http://p.pomf.se/7549

FFmpeg is having 0 problems with MJPG as far as I can tell, so perhaps the `ffmpeg-bug` label is incorrect?

**Comment by wm4** [comment]
The problem here is actually that ffmpeg supports this kind of stream, but doesn't signal that it has reliably detected it. As a consequence mpv rejects it, because it could be something else than a mjpeg stream. So the label is still correct.

(While FFmpeg apparently supports this, Libav doesn't, which is why the Libav patch confused me.)

**Comment by JamesTheAwesomeDude** [comment]
What would it take to force MPV to view the stream even though FFmpeg hasn't signaled compete confidence in its format detection?

Right now, MPV just completely chokes and dies on MJPGs; would it not be a saner course of action to rely on FFmpeg's "best guess" and at least try (though possibly wrongly) to play it as MJPG?

**Comment by wm4** [comment]
With ``--demuxer-lavf-probescore=10`` or so. But it still has problems, because these streams have no timestamps, and mpv is designed to play video with timestamps. They're basically too primitive for mpv.

**Comment by JamesTheAwesomeDude** [comment]
Hmm, it seems that `--demuxer-lavf-probescore=10` works. (I have to set `--cache=no` to get the video to play properly, but that's likely a problem for a different issue.)

Since MPV needs `demuxer-lavf-probescore=10` to play MJPG files, could that behavior be baked into MPV? The current behavior - printing "Failed to recognize file format" and exiting with failure status when presented with an MJPG file/stream - seems to serve no good purpose, and it takes one simple behavior tweak to view that format correctly. (Are there even really any circumstances where lavf would wrongly identify a stream as MJPG with that low of a score in such a way that it would produce undesirable results?)

Oh, and this might be a separate issue, as well, but `vo_vdpau`, `vo_opengl`, and `vo_opengl-hq` all freak out when playing an MJPG stream, but `vo_x11` and `vo_xv` work perfectly. (Error is `[vo/opengl/vdpau] Error when calling vdp_video_mixer_render: The size of a supplied object does not match the object it is being used with.      For example, a VdpVideoMixer is configured to process VdpVideoSurface objects of a specific size.      If presented with a VdpVideoSurface of a different size, this error will be raised.`, repeated continuously.)

**Comment by wm4** [comment]
>could that behavior be baked into MPV? 

No. It's there for a reason. Why would we play random binary files as e.g. raw h264? It makes no sense. I've already said that this is a ffmpeg issue.

>Oh, and this might be a separate issue, as well, but vo_vdpau, vo_opengl, and vo_opengl-hq all freak out when playing an MJPG stream

Can't reproduce. Are you using vf_vdpaupp by any chance? (I don't want to try because of #1123.)

**Comment by JamesTheAwesomeDude** [comment]
>Are you using `vf_vdpaupp` by any chance?

Yes, I am.

I just checked, and disabling that filter fixed the video spazzing out on MJPG streams.

As for issue #1123, I'm not sure if that's the same issue since my card is a Radeon HD 4350 (AMD/ATI), I'm using the open-source (Nouveau) drivers, and I'm not experiencing any serious  problems (outside of glitchy video in MPV itself). That issue was about people with NVidia cards using the closed-source drivers, and experiencing system-wide memory corruption.

**Comment by wm4** [comment]
It's probably not - just another issue with cropped images and hardware decoding APIs.

**Comment by JamesTheAwesomeDude** [comment]
````
# ~/.config/mpv/mpv.conf

[extension.mjpg]
demuxer-lavf-probescore=10
vf-del=vdpaupp
cache=no
````

That's a (hopefully temporary) fix for MJPG streams. Adding that to the config gets them working with 0 issues (other than the obvious lack of seeking support intrinsic to the format).

**Comment by JamesTheAwesomeDude** [comment]
This issue is not resolved. MPV `0.9.2` still cannot play MJPG files. An excerpt from the log:

````
…
[demux] Trying demuxer: lavf (force-level: normal)
[lavf] Found 'mjpeg' at score=25 size=131072.
[lavf] Found 'mjpeg' at score=25 size=262144.
[lavf] Found 'mjpeg' at score=25 size=524288.
[lavf] Found 'mjpeg' at score=25 size=1048576.
[lavf] Found 'mjpeg' at score=25 size=2097152.
[lavf] Found 'mjpeg' at score=25 size=2097152.
[lavf] No format found, try lowering probescore or forcing the format.
…
[cplayer] Failed to recognize file format.
…
````

So MPV has properly identified the file - MJPG with probescore 25. MJPG files will always have probescore 25. This is the current way that MJPG files are identified. So why does MPV refuse to load this file?

**Comment by wm4** [comment]
Because

>The problem here is actually that ffmpeg supports this kind of stream, but doesn't signal that it has reliably detected it. As a consequence mpv rejects it, because it could be something else than a mjpeg stream.

**Comment by JamesTheAwesomeDude** [comment]
For MJPG streams, 25 _is_ reliable, though. An MJPG file will always have a probescore of 25. If MPV receives "mjpg with 25 confidence" from the demuxer, MPV itself can say with very high confidence that it's a valid MJPG stream.

**Comment by JamesTheAwesomeDude** [comment]
I guess the issue is this:

>mpv rejects it, because it could be something else than a mjpeg stream.

If it's identified as MJPG with a sore of 25, then the above statement ("it could be something other than a mjpeg stream") is simply untrue, and acting on the assumption that it's true is not desirable behavior.

**Comment by wm4** [comment]
That's not how the ffmpeg API works.

**Comment by JamesTheAwesomeDude** [comment]
FFmpeg returns a probescore based on the likelihood it's guessed the filetype accurately. For the most part, a higher score correlates to better reliability, EXCEPT in the case of MJPG files, which can/will never be detected with a score higher than 25. This is ffmpeg's current behavior - to always score even the most textbook MJPG streams as 25. Why, then, is this behavior not accounted for in MPV?

**Comment by wm4** [comment]
Posted a ffmpeg patch that fixes the issue with this particular stream.
