### ISSUE TITLE
Read tracks (chapters) from embedded cue sheet in audio files (FLAC)

### ISSUE THREAD

**Issue by spongbros** [mpv-player/mpv#1957]
In cases where a cue sheet has been embedded in an audio file (such as FLAC), please add support to read the tracklist from it (including track names if present) and allow switching between tracks like chapters.

**Comment by wm4** [comment]
Sample file?

**Comment by spongbros** [comment]
https://mega.nz/#!OlAVlaoR!wZ_5RohwDXy2yZIaa7QNSsBqnmpfnswpkA7DGP2eMUM

Programs such as CUETools and XLD allow cue sheets to be embedded into audio files when ripping an audio CD as a single file. If the sample file is opened in XLD, it will read the track information from the file. If it’s opened in MPC-HC on Windows, the file is opened as a single audio file with chapter markings at track breaks; the track names are read as chapter titles.
