### ISSUE TITLE
Burns one core for seeking streaming under low bandwidth

### ISSUE THREAD

**Issue by xylosper** [mpv-player/mpv#1958]
I'm not sure this is a bug or some restriction not avoidable from low bandwidth.
I've got a report that 100% CPU usage while seeking for streaming in low bandwidth environment.
I've tested with next procedure:

1. Open a YouTube URL which is long enough to prevent entire file being cached. For instance, here: https://www.youtube.com/watch?v=X-uHR_4meLQ
2. Limit bandwidth some low value. In my case, I used `wondershaper` to emulate low bandwidth:
 ```sudo wondershaper -a enp3s0 -d 100 -u 100```
3. Seek to far position where not cached in time slider.

Then, I can see that one core shows 100% usage between after seeking and before playback restarted.
Here's a figure to show how CPU usage changes:
![clip5](https://cloud.githubusercontent.com/assets/4363181/7698591/7256331e-fe4c-11e4-9ed3-a74bcc0c8b2f.png)

I used `wondershaper` because I cannot find slow connection enough to reproduce this problem.
Because only one core burns here, I guess there's a thread falling in some useless busy loop here.

Please let me know if you need any futher information for this.

**Comment by wm4** [comment]
My first fix was buggy; I just pushed another change relevant to this.

**Comment by xylosper** [comment]
Confirmed fix. Thank you!
