### ISSUE TITLE
[RFC] Unifying options and properties

### ISSUE THREAD

**Issue by wm4** [mpv-player/mpv#1960]
The plan is to remove most of the separation between options and properties. This comes from the observation that most options can be changed at runtime, either by changing a property with the same name, or by using the ``options/<name>`` property. Basically only read-only properties have no matching option.

Distinguishing them is not terribly useful anymore. If the user wants to change something, he shouldn't have to distinguish options and properties and definitely shouldn't need to know about the ``options/<name>`` one. Instead, everything is both an options and a property, and setting it causes the player to update it in the best way possible.

This basically affects everything: mpv.conf and input.conf user configurations, the client API, the JSON IPC.

There are still some conceptual problems, though. Thus this RFC.

- Some options and properties just plain conflict, because they use the same name and have different semantics. E.g. ``length`` as option controls how much of the file should be played, starting from ``--start``. The property tells you the duration of the file. Same for ``audio-format``, and probably more.
- Some options set a requested value, while their properties return the real value, e.g. ``aid``, ``sid``, ``demuxer``, ``fps``. It's not clear how to distinguish them. How do you for example read the option setting back, instead of the "real" value?
- ``aid``/``sid`` properties restrict the values that can be written to it to the current file. The options on the other hand are just a loose request. If the track requested by an option is not available, the file just uses the default track, while writing it as property would error.
- Likewise, the ``vf`` property verifies whether the filter chain succeeds to create, and rejects the newly written value if it fails. The ``vf`` option on the other hand just makes video initialization fail if it can't be used.
- Some properties are unavailable if the corresponding subsystem is not available. For example, the ``volume`` property while audio is disabled. Options on the other hand can be always changed, even if they're not going to be used.

One obvious conflict is that requested value and real value can't be separated if the options and properties are unified. Possibly the separation should be kept to some degree, but I wonder if it makes sense. The main goal here is that the user can naively set any option as property and it would just work. Using the option API could be left to those who actually need to distinguish actual and requested values.

Though I'd really want to remove the separation completely (internally too), if possible at all.

Any thoughts about this?

@xylosper: I'm mainly writing this for you, since you're probably the most important/biggest client API user.

**Comment by xylosper** [comment]
> Some options and properties just plain conflict,

Well, confliction of name will be solved simply by renaming them and deprecating old names.

> Some options set a requested value, while their properties return the real value

I think this is a normal behavior. Usually, in lots of languages/libraries/frameworks, setter function for a property can perform validating input value. If you really need to know requested value for a property, you can add another new property with `requested` suffix or prefix. Or, maybe it would be possible to add general method to keep given value for all properties.

For `aid`, `sid` and `vf, I think you can choose either one of option behavior and property behavior. Both behaviors are reasonable, I think.

Also, for, `aid` and `sid`, there's another choice for invalid value: disable that stream.

> Some properties are unavailable if the corresponding subsystem is not available. 

I think you should keep that value consistently, especially for `volume` because even there's no audio stream, there's no problem to define `volume`. It's just amplification for audio signal level and if there's no audio, you can just do nothing. I've got tons of 'unavailable property' errors which can be safely ignored.

> Though I'd really want to remove the separation completely (internally too), if possible at all.

As I said previously, I think you can unify all properties and options and add new properties only if you need seperated values.

**Comment by wm4** [comment]
>Well, confliction of name will be solved simply by renaming them and deprecating old names.

That's quite annoying in particular for the ``length`` property. Maybe I'll rename it to ``duration``, and deprecate the old name for a while.

>Also, for, aid and sid, there's another choice for invalid value: disable that stream.

So how would you set ``aid``/``sid`` if the file has not started yet? Or should it just accept all values if no file is loaded? What about the state between loadfile command and actual file loading? (This state matters for the time during the open hook is executed.)

I'd tend to say that setting a non-existing ID with ``aid`` should select the default track (i.e. the current behavior pf the ``--aid`` option). This would actually give an elegant answer to the question I'm asking above.

>I think you should keep that value consistently, especially for volume because even there's no audio stream, there's no problem to define volume. It's just amplification for audio signal level and if there's no audio, you can just do nothing.

Note that volume is quite special. The volume option has a set and unset state. If it's unset, the volume property returns whatever the system mixer has set (or if softvol is used, the value that maps to 100% volume). If the option is set, the system mixer is changed on loading. Setting the volume property only changes the mixer, but not the option. So the volume option is basically a hard override, while the volume property has simpler and more straightforward semantics.

I suppose we could trash these semantics. But then there's still the question how to distinguish between hard override, and changing the system mixer when it's available. Consider the following, assuming softvol is not used:
- file is loaded
- API user sets volume property to something
- file is unloaded (including the AO)
- the user changes the system volume through OS mixer controls
- a new file is loaded

Now what should be done after this point. Should the volume property return the system volume? Or should the loader code force the volume to the value previously set with the API?

Similar considerations have to be made for ``fps``, ``video-aspect``, ``demuxer``. For them it's actually even worse, because the only way they can work is to force the new value, while the volume property could get away with relaxed syntax.

Take ``video-aspect``. Normally, it returns the effective aspect ratio of the video. Setting it forces the aspect ratio. If you set it once, does that mean the aspect ratio of the next file is also forced? If not, how do you force the aspect ratio for all files? Maybe the API should distinguish between set and unset properties? But that also seems to be too subtle.

How would that work in a GUI? E.g. if the user selects a certain video aspect on the menu? (I think if I'd do that, I'd separate selecting the video aspect and displaying it.)

>I've got tons of 'unavailable property' errors which can be safely ignored.

This is another issue. 'unavailable property' happens in some cases when the associated subsystem is not active currently. Instead of doing this, it could just set the requested value when setting the property, and return the requested value or the last known value when getting it.

Though it might be somewhat useful in situations when the user or API user does not know whether the subsystem is active; then returning an error helps to avoid confusion about why changing a property does nothing.

**Comment by xylosper** [comment]
Maybe, there's a gap in position of view between command line based interface and graphical user interface. For instance, you would already know that there's no GUI player which disables changing volume when not playing media. It's same for other properties unless it's really impossible.

> This would actually give an elegant answer to the question I'm asking above.

Yes, maybe. It was just an idea.

>     file is loaded
    API user sets volume property to something
    file is unloaded (including the AO)
    the user changes the system volume through OS mixer controls
    a new file is loaded

If I have to disable softvol for some reason, I'll keep application's volume UNLESS the change of system volume can update application's volume in real-time which is not possible for current implementation in mpv. Most of users would complain if the volume value changed suddenly after playback started. They would think(misunderstand) that the volume changed even though they did nothing in that case.

> How would that work in a GUI? E.g. if the user selects a certain video aspect on the menu? (I think if I'd do that, I'd separate selecting the video aspect and displaying it.)

I think the selection should be kept by default. I keep every changes unless it doesn't make sense because those changes are done by user explicitly.

> This is another issue.

Yeah, I just thought it would be automatically solved if unavailable states were removed from properties.

**Comment by wm4** [comment]
>Maybe, there's a gap in position of view between command line based interface and graphical user interface. For instance, you would already know that there's no GUI player which disables changing volume when not playing media. 

I don't really agree. It's more due to the way it's implemented. (Which again could probably be fixed, but I don't have plans because I'm not looking forward to the mess.) One exception is forcing the volume on playback start, but maybe this should be a different option.

Anyway, I'm still not sure how typical things like ``demuxer`` or ``video-aspect`` should be handled. They all have in common that the user might want to force them in special situations, but normally you'd expect them to return the current state. So here's a bunch of stuff that's unsure:
- Does attempting to set the property force the value?
- Does reading the property always return the current state? What if the subsystem is inactive, e.g. what does ``video-aspect`` return while no video is loaded?
- Would reading the property and then writing the same value again change the current value into a forced setting? Even if the value that was returned was auto-detected?

**Comment by xylosper** [comment]
>    Does attempting to set the property force the value?

No. The property should be updated only if given value is valid. However, this does not mean that it should reject all set/get operations when subsystem is inactive. Lots of properties depending on subsystem still can be defined well even though the subsystem is inactive. For instance, `sub-pos` can be defined without subtitle renderer. So, basically, I think the options which can be defined without context should replace properties which cannot be manipulated when subsystem is inactive.

>    Does reading the property always return the current state? What if the subsystem is inactive, e.g. what does video-aspect return while no video is loaded?

Maybe I'm missing some point here, but I can't see any reason which prevents `video-aspect` returning set value by user while no video is loaded. If I want to know original aspect ratio of video, I'll use subproperties of `video-params/w` and `video-params/h` although I wish `video-params/aspect` wouldn't be overridden.

So, `video-params` is a property which cannot be defined without subsystem but `video-aspect` is a proeprty can be defined without subsystem.

> Would reading the property and then writing the same value again change the current value into a forced setting? Even if the value that was returned was auto-detected?

If auto detection is supported, there should be an choice to enforce auto detection. For instance, `video-aspect` already provides special value `-1` for default value in container. If a user set the `video-aspect` with a value not `-1`, it would be obvious that the user wanted to disable auto detection. I can't see any reasonable cause to recover auto detection which is disabled by user explicitly.

**Comment by wm4** [comment]
So you would strictly separate properties which request a value, and properties which return the actual value.

As currently in mpv, the ``video-aspect`` property return the actual value, but lets you override the current aspect by setting it (this also sets the option, so the next file will force the same aspect ratio).

And you would change it to always return the requested value?

What about things like ``demuxer``? Should they also have separate requested/actual properties?

**Comment by xylosper** [comment]
> So you would strictly separate properties which request a value, and properties which return the actual value.

Yes, if it's needed like `video-aspect`. But, for instance, there's no need to separate property for request and property for querying for `sub-pos`.

> this also sets the option, so the next file will force the same aspect ratio

Btw, the local option for current file will still work for unified option/property system in your plan? If it's still valid, user can set local option/property when he wants to restore default value for new playback.

> And you would change it to always return the requested value?

Yes, unless it's invalid. For instance, any negative number not -1 would be rejected in setter.

> What about things like demuxer? Should they also have separate requested/actual properties?

Yes, if you decided to fall back to auto detection when requested demuxer was not available. If you decided to terminate playback when requested demuxer was not available, I think there's no need for separation.

**Comment by wm4** [comment]
>Btw, the local option for current file will still work for unified option/property system in your plan? If it's still valid, user can set local option/property when he wants to restore default value for new playback.

What mechanism do you mean exactly?

**Comment by xylosper** [comment]
I meant `file-local-options/...`.

**Comment by wm4** [comment]
Right. This will either continue to exist, or a separate mechanism for marking an option/property as file local will be introduced.

**Comment by wm4** [comment]
I made some rather minor steps towards unification.

For example, I made the stream properties (``aid`` etc.) writable while no file is loaded. (For this one see f7ca2c83e1da067f02dcd57da5cf72a34dc5c0fc.)

**Comment by wm4** [comment]
Did another change to the hwdec properties in the spirit of unification.

**Comment by wm4** [comment]
Took longer than I hoped it'd take, but it's done now.

Some caveats remain: https://mpv.io/manual/master/#inconsistencies-between-options-and-properties
