### ISSUE TITLE
no sound - opensuse 13.2, xfce

### ISSUE THREAD

**Issue by wihedro** [mpv-player/mpv#1962]
Audio works fine with mplayer. I'm using pulse as audio driver.

Problems highlighted:

log:
Failed to initialize an audio decoder for codec 'ac3'.

verbose mode:
[ad] Codec list:
[ad] (no decoders)
[ad] Failed to initialize an audio decoder for codec 'aac'.
[ad] Uninit audio filters...
[cplayer] Audio: no audio
_______________________________________________________________________________

Here's a copy of the log:

/usr/bin/mpv --no-config --no-quiet --terminal --no-msg-color --slave-broken --no-fs --hwdec=no --sub-auto=fuzzy --vo=xv, --ao=pulse --stop-screensaver --no-input-default-bindings --input-x11-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=14680102 --monitorpixelaspect=1 --osd-scale=1 --sub-ass --embeddedfonts --ass-line-spacing=0 --sub-scale=1 --sub-text-font=Arial --sub-text-color=#ffffff --sub-text-shadow-color=#000000 --sub-text-border-color=#000000 --sub-text-border-size=2.5 --sub-text-shadow-offset=5 --sub-codepage=utf8:ISO-8859-1 --sub-pos=100 --volume=100 --cache=2048 --osd-level=0 --index=default --screenshot-template=cap_%F_%p_%02n --audio-channels=2 --af-add=scaletempo --af-add=equalizer=0:0:0:0:0:0:0:0:0:0 --softvol=yes --softvol-max=110 --ytdl=no --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-aspect}
INFO_VIDEO_FPS=${=fps}
INFO_VIDEO_BITRATE=${=video-bitrate}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_AUDIO_BITRATE=${=audio-bitrate}
INFO_AUDIO_FORMAT=${=audio-format}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-samplerate}
INFO_AUDIO_NCH=${=audio-channels}
INFO_LENGTH=${=length}
INFO_DEMUXER=${=demuxer}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
 --term-status-msg=STATUS: ${=time-pos} / ${=length:0} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} /home/wihedro/Videos/sample.mkv

--slave-broken is deprecated (see manpage).
Playing: /home/wihedro/Videos/sample.mkv
[input_file] Client connected
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 --alang=eng (*) (ac3)
 (+) Subs  --sid=1 --slang=eng (*) 'English' (subrip)
Failed to initialize an audio decoder for codec 'ac3'.
Audio: no audio
VO: [xv] 1280x720 yuv420p
[vo/xv/x11] Disabling screensaver failed.
MPV_VERSION=mpv 0.9.1
INFO_VIDEO_WIDTH=1280
INFO_VIDEO_HEIGHT=720
INFO_VIDEO_ASPECT=1.777778
INFO_VIDEO_FPS=23.976025
INFO_VIDEO_BITRATE=0
INFO_VIDEO_FORMAT=h264
INFO_VIDEO_CODEC=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
INFO_AUDIO_BITRATE=0
INFO_AUDIO_FORMAT=
INFO_AUDIO_CODEC=
INFO_AUDIO_RATE=
INFO_AUDIO_NCH=
INFO_LENGTH=60.019000
INFO_DEMUXER=mkv
INFO_TITLES=
INFO_CHAPTERS=0
INFO_TRACKS_COUNT=3
METADATA_TITLE=
METADATA_ARTIST=
METADATA_ALBUM=
METADATA_GENRE=
METADATA_DATE=
METADATA_TRACK=
METADATA_COPYRIGHT=
INFO_MEDIA_TITLE=sample.mkv
INFO_VIDEO_DSIZE=1280x720
INFO_TRACK_0: video 1 '' '' yes
INFO_TRACK_1: audio 1 'eng' '' no
INFO_TRACK_2: sub 1 'eng' 'English' yes
Failed to initialize an audio decoder for codec 'ac3'.
Audio: no audio
____________________________________________________________________________

And here's a copy of verbose mode:

wihedro@linux-4zhc:~> mpv ~/Documents/Movies/Sample.mkv -v
[cplayer] Command line options: '/home/wihedro/Documents/Movies/Sample.mkv' '-v'
[cplayer] mpv 0.9.1 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[cplayer]  built on May  7 2015
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.20.100
[cplayer]    libavcodec      56.26.100
[cplayer]    libavformat     56.25.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.11.102
[cplayer]    libswresample   1.1.100
[cplayer]
[cplayer] Configuration: ./waf configure --prefix=/usr --bindir=/usr/bin --mandir=/usr/share/man --libdir=/usr/lib64 --docdir=/usr/share/doc/packages/mpv --confdir=/etc/mpv --enable-openal --enable-cdda --enable-libmpv-shared --enable-zsh-comp --enable-manpage-build --enable-pdf-build --disable-sdl1 --disable-sdl2 --disable-build-date --disable-debug
[cplayer] List of enabled features: alsa asm atomic-builtins atomics audio-input avcodec-chroma-pos-api avframe-metadata avframe-skip-samples caca cdda cplayer dlopen drm dvbin dvdnav dvdread enca encoding fchmod gl gl-wayland gl-x11 glibc-thread-name glob iconv jack jpeg ladspa lcms2 libass libass-osd libav libavdevice libavfilter libbluray libbs2b libdl libguess libm libmpv-shared librt libsmbclient libswresample libv4l2 linux-fstatfs lua nanosleep openal optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads pulse pvr resampler shm subprocess termios tv tv-v4l2 vaapi vaapi-glx vaapi-hwaccel vaapi-vpp vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h wayland x11 xext xinerama xrandr xss xv zlib zsh-comp
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config file: 'mpv.conf|config'
[cplayer] Setting option 'v' = '' (flags = 8)
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config file: 'input.conf'
[input] Falling back on default (hardcoded) input config
[osc] Loading script @osc.lua...
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config file: 'scripts'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config file: 'lua'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'lua-settings/osc.conf' -> '(NULL)'
[osc] lua-settings/osc.conf not found.
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading script @ytdl_hook.lua...
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config file: 'scripts'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config file: 'lua'
[ytdl_hook] loading mp.defaults
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook_add, flags=0, args=[on_load, 1, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config file: 'scripts'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config file: 'lua'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'watch_later/2D29B24823457AEB312C7100B230A71A' -> '(NULL)'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'watch_later' -> '(NULL)'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'watch_later/2D29B24823457AEB312C7100B230A71A' -> '(NULL)'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'watch_later' -> '(NULL)'
[cplayer] Playing: /home/wihedro/Documents/Movies/Sample.mkv
[cplayer] Running hook: ytdl_hook/on_load
[cplayer] Run command: hook_ack, flags=0, args=[on_load]
[file] Opened: /home/wihedro/Documents/Movies/Sample.mkv
[demux] Trying demuxer: disc (force-level: normal)
[demux] Trying demuxer: edl (force-level: normal)
[demux] Trying demuxer: cue (force-level: normal)
[demux] Trying demuxer: rawaudio (force-level: normal)
[demux] Trying demuxer: rawvideo (force-level: normal)
[demux] Trying demuxer: tv (force-level: normal)
[demux] Trying demuxer: libass (force-level: normal)
[demux] Trying demuxer: mkv (force-level: normal)
[mkv] Found the head...
[mkv] + a segment...
[mkv] /---- [ parsing seek head ] ---------
[mkv] \---- [ parsing seek head ] ---------
[mkv] |+ segment information...
[mkv] | + timecode scale: 1000000
[mkv] | + duration: 7472.330s
[mkv] | + segment uid b7 f2 70 2a cd b2 9b ba a2 1a 5a ab 99 14 b0 ee
[mkv] |+ segment tracks...
[mkv] | + a track...
[mkv] |  + Track number: 1
[mkv] |  + Track type: Video
[mkv] |  + Video track
[mkv] |   + Display width: 1280
[mkv] |   + Display height: 688
[mkv] |   + Pixel width: 1280
[mkv] |   + Pixel height: 688
[mkv] |  + Codec ID: V_MPEG4/ISO/AVC
[mkv] |  + CodecPrivate, length 41
[mkv] |  + Language: und
[mkv] |  + Default flag: 0
[mkv] |  + Default duration: 41.708ms ( = 23.976 fps)
[mkv] | + a track...
[mkv] |  + Track number: 2
[mkv] |  + Track type: Audio
[mkv] |  + Audio track
[mkv] |   + Sampling frequency: 24000.000000
[mkv] |   + Output sampling frequency: 48000.000000
[mkv] |   + Channels: 2
[mkv] |  + Codec ID: A_AAC
[mkv] |  + CodecPrivate, length 7
[mkv] |  + Language: jpn
[mkv] |  + Default flag: 0
[mkv] |  + Default duration: 42.667ms ( = 23.438 fps)
[mkv] | + a track...
[mkv] |  + Track number: 3
[mkv] |  + Track type: Audio
[mkv] |  + Audio track
[mkv] |   + Sampling frequency: 24000.000000
[mkv] |   + Output sampling frequency: 48000.000000
[mkv] |   + Channels: 2
[mkv] |  + Codec ID: A_AAC
[mkv] |  + CodecPrivate, length 7
[mkv] |  + Default flag: 0
[mkv] |  + Default duration: 42.667ms ( = 23.438 fps)
[mkv] | + a track...
[mkv] |  + Track number: 4
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_TEXT/UTF8
[mkv] |  + Language: und
[mkv] |+ found cluster
[mkv] Deferring reading cues.
[mkv] All headers are parsed!
[mkv] Aspect: 1.860465
[demux] Detected file format: Matroska
[find_files] Loading external files in /home/wihedro/Documents/Movies/
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'sub/' -> '(NULL)'
[cplayer]  (+) Video --vid=1 (h264)
[cplayer]  (+) Audio --aid=1 --alang=jpn (aac)
[cplayer]      Audio --aid=2 --alang=eng (aac)
[cplayer]  (+) Subs  --sid=1 (*) (subrip)
[cplayer] File tags:
[cplayer]  Title: Spirited.Away.2001.720p.BluRay.950MB.ShAaNiG.com
[cplayer] [V] fourcc:0x31637661  size:1280x688  fps:23.976
[vo/opengl/wayland] failed to connect to a wayland server: check if a wayland compositor is running
[vo/opengl/x11] X11 opening display: :0.0
[vo/opengl/x11] X11 running at 6400x1440 (":0.0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Display 0 (DVI-I-1): [1920, 0, 4480, 1440] @ 59.950550 FPS
[vo/opengl/x11] Display 1 (HDMI-0): [0, 180, 1920, 1260] @ 60.000000 FPS
[vo/opengl/x11] Display 2 (DVI-D-0): [4480, 180, 6400, 1260] @ 60.000000 FPS
[vo/opengl/x11] Current display FPS: 59.950550
[vo/opengl] GLX chose FB config with ID 0x10d
[vo/opengl] GLX chose visual with ID 0x27
[vo/opengl] GL_VERSION='4.4.0 NVIDIA 340.76'
[vo/opengl] Detected desktop OpenGL 4.4.
[vo/opengl] GL_VENDOR='NVIDIA Corporation'
[vo/opengl] GL_RENDERER='GeForce GTX 770/PCIe/SSE2'
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='4.40 NVIDIA via Cg compiler'
[vo/opengl] OpenGL legacy compat. found.
[vo/opengl] Detected OpenGL features:
[vo/opengl]   - Framebuffers
[vo/opengl]   - VAOs
[vo/opengl]   - Float textures
[vo/opengl]   - RG textures
[vo/opengl]   - 1D textures
[vo/opengl]   - 3D textures
[vo/opengl]   - debugging extensions
[vo/opengl] 16 bit texture depth: 16.
[vo/opengl] Display depth: R=8, G=8, B=8
[vo/opengl] Assuming 59.950550 FPS for framedrop.
[vd] Container reported FPS: 23.976025
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd] Opening video decoder lavc:h264
[vd] Detected 4 logical cores.
[vd] Requesting 5 threads for decoding.
[vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
[vo/opengl/x11] Disabling screensaver.
[ad] Codec list:
[ad]     (no decoders)
[ad] Failed to initialize an audio decoder for codec 'aac'.
[ad] Uninit audio filters...
[cplayer] Audio: no audio
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[sub] Subtitle filter chain: srt (subrip) -> ass (ass-text)
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[libass] Setting up fonts...
[libass] Done.
[cplayer] Starting playback...
[vf] Video filter chain:
[vf]   [vd] 1280x688 yuv420p auto/auto CL=mpeg2/4/h264
[vf]   [in] 1280x688 yuv420p bt.709/limited CL=mpeg2/4/h264
[vf]   [out] 1280x688 yuv420p bt.709/limited CL=mpeg2/4/h264
[cplayer] VO: [opengl] 1280x688 yuv420p
[cplayer] VO: Description: Extended OpenGL Renderer
[vo/opengl] Resize: 1280x688
[vo/opengl] Window size: 1280x688
[vo/opengl] Video source: 1280x688 (1280x688)
[vo/opengl] Video display: (0, 0) 1280x688 -> (0, 0) 1280x688
[vo/opengl] Video scale: 1.000000/1.000000
[vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[vo/opengl] Video borders: l=0 t=0 r=0 b=0
[vo/opengl] Texture for plane 0: 1280x688
[vo/opengl] Texture for plane 1: 640x344
[vo/opengl] Texture for plane 2: 640x344
[vo/opengl] Reinit rendering.
[vo/opengl] recompiling a shader program:
[vo/opengl] [  1] vec4 color;
[vo/opengl] [  2] vec2 chroma = vec2(texture(texture1, texcoord1).r, texture(texture2, texcoord2).r);
[vo/opengl] [  3] color = vec4(texture(texture0, texcoord0).r, chroma, 1.0);
[vo/opengl] [  4] // color conversion
[vo/opengl] [  5] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[vo/opengl] [  6] color.a = 1.0;
[vo/opengl] [  7] // scaler pre-conversion
[vo/opengl] [  8] // main scaling
[vo/opengl] [  9] // scaler post-conversion
[vo/opengl] [ 10] // color management
[vo/opengl/x11] Disabling screensaver failed.
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'fonts' -> '(NULL)'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'subfont.ttf' -> '(NULL)'
[global] search dirs: /home/wihedro/.config/mpv /home/wihedro/.mpv /etc/mpv
[global] config path: 'fonts.conf' -> '(NULL)'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[statusline] V: 00:00:00 / 02:04:32 (0%)
[vo/opengl] recompiling a shader program:
[vo/opengl] [  1] // OSD (libass)
[vo/opengl] [  2] vec4 color = vec4(ass_color.rgb, ass_color.a * texture(osdtex, texcoord).r);
[vo/opengl] [  3] // color management

**Comment by wihedro** [comment]
second line of verbose highlight is supposed to say: '[ad] (no decoders)'

**Comment by wihedro** [comment]
[ad] no decoders

with parentheses, don't know why github deleted them.

**Comment by lachs0r** [comment]
Did you get mpv and FFmpeg from Packman? Looks like your FFmpeg build is broken.

**Comment by wihedro** [comment]
i just used the one packaged with my opensuse xfce install, but i just tried reinstalling from pacman, which did nothing.

**Comment by wihedro** [comment]
Just tried building FFmpeg, but that also did nothing.

**Comment by lachs0r** [comment]
Okay, this happens because the mpv package in Packman does not explicitly require Packman FFmpeg libraries. You need to make extra sure to install the FFmpeg libraries from the Packman repository, not the crippled one from the main repo. To avoid that problem, you should give the Packman repository a higher priority (e.g. `zypper mr -p 1 Packman`). Some repositories (like KDE:Extra) apparently also have crippled FFmpeg versions in them for whatever reason, and the package management might pick those because they have a higher build version number.

This is a problem. Packman should really make their packages depend on the correct versions.

There are all sorts of things you could have done wrong while building FFmpeg yourself (different library versions, installed to wrong prefix, used the wrong libdir, didn’t rebuild mpv with that version…). This would have worked if you had used mpv-build.

Anyway, I’ve confirmed that it works fine if the correct packages are installed, so I’m closing this.
