### ISSUE TITLE
Has current mpv version OSX libass 0.12.2?

### ISSUE THREAD

**Issue by Batteriee** [mpv-player/mpv#1963]
Yes or No?

**Comment by Argon-** [comment]
Using official libass and building from source, yes.

**Comment by Batteriee** [comment]
Ok please update. For the normal user.

**Comment by Argon-** [comment]
How?

**Comment by Batteriee** [comment]
I mean update the build from ChrisK.

**Comment by ChrisK2** [comment]
My builds are using libass master/HEAD, so it's as new as possible.
