### ISSUE TITLE
Avoid conflicts with NetBSD popcount(3)

### ISSUE THREAD

**Issue by iamleot** [mpv-player/mpv#1968]
Hello to the entire mpv community,
if I try to compile the latest stable release on NetBSD I have a build failure
due [popcount64()](http://netbsd.gw.com/cgi-bin/man-cgi?popcount+3+NetBSD-current) name conflict.

The following trivial patch will fix the issue:

 https://gist.githubusercontent.com/iamleot/07f7408dbc9ab0b09e94/raw/7945a2211e3fbda5516ca71a5df3d431154ee3df/patch-audio_chmap.c

Keep up the good work!
Ciao,
L.

**Comment by rcombs** [comment]
Why not use `av_popcount64`?

**Comment by iamleot** [comment]
Hello Rodger,

Rodger Combs writes:
> Why not use `av_popcount64`?
I did not know that! Thank you and thanks to V. Lang for the very quick
fix.


Ciao,
L.
