### ISSUE TITLE
--loop should probably default to using 'inf' if no parameters are specified.

### ISSUE THREAD

**Issue by lovelacehq** [mpv-player/mpv#1970]
Are there any good reasons/justifications for the current behavior of --loop ? I think it's reasonable for it to just assume 'inf' if no parameters are specified (as default behavior); anyone have any thoughts/disagreements/etc?

**Comment by haasn** [comment]
Strongly agree, this is something that has confused and annoyed me in the past as well.

I expect, intuitively, for [code]mpv --loop FILE[/code] to, well, loop the file. Right now it does the exact opposite.

**Comment by mc4man** [comment]
Well maybe there's some value to loop=1 though haven't seen.  Would expect it to loop once, not play once
