### ISSUE TITLE
--really-quiet cannot be negated

### ISSUE THREAD

**Issue by Cpuroast** [mpv-player/mpv#1973]
--really-quiet does not accept yes or no as a parameter contrary to --quiet which does

Invalid parameter for really-quiet flag: no
Error parsing option really-quiet (option doesn't take a parameter)

For consistency it should behave like --quiet.
So you can have: really-quiet=yes in mpv.conf and then negate it with --really-quiet=no when needed.

**Comment by wm4** [comment]
No, it can't. Use -msg-level.
