### ISSUE TITLE
Faulty integration with youtube-dl on niconico videos

### ISSUE THREAD

**Issue by AliceTertia** [mpv-player/mpv#1974]
![image](http://a.pomf.se/wuwvkl.png)
This happens with some (about half of the ones I tested) niconico videos whenever I try to play them directly through mpv using ytdl, however, if I try to download the video directly through yotube-dl, it works just fine.
I don't have flash player installed.
The youtube-dl is the same version on both of them (which is also the latest)
Pic related is on mpvhq-win64, but I get the same error when I try to play it on Linux Mint using vanilla mpv.

**Comment by AliceTertia** [comment]
![normal](http://a.pomf.se/rwtebv.png)
Pic related of it working perfectly fine with other nicovideos.

**Comment by wm4** [comment]
Are you sure about this? It even says to report this issue to youtube-dl. It fails with youtube-dl on the command line too with -J.

**Comment by wm4** [comment]
PS: in case you don't know, here's where you should report it: https://github.com/rg3/youtube-dl/issues/

**Comment by AliceTertia** [comment]
I thought about reporting it there, but since it was working with youtube-dl I thought here would be the place. Anyway, thanks.

**Comment by wm4** [comment]
>but since it was working with youtube-dl

The video in your screenshot doesn't (for me).

**Comment by qyot27** [comment]
The Megpoid video requires logging into niconico; a plain ```youtube-dl``` invocation for that video fails, but having it log in allows it to work.  Bad Apple has no log-in restriction on it, which is why that works.

Just pass ```--ytdl-raw-options="username=<username>,password=<password>"``` to mpv, substituting the actual log-in credentials.  Then it should work.
