### ISSUE TITLE
Could you add a feature, auto fill in the command when Tab is pressed.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#1977]
#for example: 
        me@mypc:~$ mpv --list-o
#then I press Tap
        me@mypc:~$ mpv --list-options

#or list the options, like this:
        me@mypc:~$ mpv --ytd
#then I press Tab 2 times
        me@mypc:~$ mpv --ytd
        --ytdl   --ytdl-format   --ytdl-raw-options

**Comment by rrooij** [comment]
Use zsh, it provides the autocompletion as far as I know.

**Comment by qmega** [comment]
For zsh, this is implemented (here, not in zsh itself) but disabled by default. Pass `--enable-zsh-comp` to the waf configure command to enable it. This is done in the Arch and Debian packages, don't know about others.

For bash, there's https://github.com/2ion/mpv-bash-completion (Author wanted to merge it, see #1021, but I guess that's on hold.)
