### ISSUE TITLE
BD Menu has no hide option

### ISSUE THREAD

**Issue by CureGecko** [mpv-player/mpv#1981]
On many blu-rays, the menu pops over the content you are watching and from there you can go to options or to the top menu which shows you more options such as special features. One issue is that once you bring up the overlay menu, there is no way to have it dismiss so you can continue where you left off. You basically have to go to the top menu to play again from the beginning or select from a chapter.

**Comment by rrooij** [comment]
Just wondering, what is the normal behavior with bluray players? Do they have an option to toggle the overlay menu?

**Comment by wm4** [comment]
Menu support was killed.
