### ISSUE TITLE
Add MPLS playback support.

### ISSUE THREAD

**Issue by CureGecko** [mpv-player/mpv#1982]
An MPLS file is a blu-ray playlist file. There are a couple of reasons for adding support.
1. A playlist may contain more than one m2ts file referenced and specify how long each should play. An example would be the Toy Story blu-ray where they have muliple languages for the credits and just place credit m2ts files automatically replacing the english one with the correct language credits.
2. Kodi media player plays the MPLS file when you choose to play a title from the index.bdmv file. This is the main reason I'm submitting this, sometimes it's easier to go to index.bdmv and select play main title than to go into the stream folder to find the correct m2ts.

Using this command https://github.com/tourettes/libbluray/blob/master/src/examples/mpls_dump.c with the options of -vlic you can see the details of a mpls file.

**Comment by wm4** [comment]
Use whatever libbluray support we have?

**Comment by CureGecko** [comment]
I would assume that would be how it would be done. If I understand correctly, you will have to go back a directory into the STREAM folder to get the M2TS file.

**Comment by truexfan81** [comment]
bump

**Comment by wiiaboo** [comment]
This was sorta implemented in 51dbb5607e19ea7f6a397f685fb5f58346b79f88.
Instead of using the .mpls file directly, you use `bd://mpls/[playlist] --bluray-device=<path to root of the bluray structure>`.

**Comment by axzxc1236** [comment]
Three years after this issue is closed, MPV still doesn't play mpls files directly.

So I created my own way to let MPV play .mpls file by default, without touching command line everytime at least.

https://github.com/axzxc1236/MPV-.desktop-file-with-mpls-support
