### ISSUE TITLE
json IPC: Sending audio_add too soon after start-file event segfaults mpv

### ISSUE THREAD

**Issue by c-14** [mpv-player/mpv#1984]
As of commit f9f2e1cc4e80a66793249651b74d83c1c8f3a8d4 sending an audio_add command via json ipc to mpv directly after receiving the start-file event from mpv causes mpv to segfault (before this commit mpv froze and didn't play the files). Adding a delay of about 0.5 seconds between receiving the start-file event and sending the audio_add command causes mpv to respond correctly and the files to play (both before and after said commit).
I have a minimal python script that can be used to reproduce the issue as well as a core from the segfault.
script: http://dl.c-14.de/mpv/segtest.py
core: http://dl.c-14.de/mpv/mpv-git-core-switch-tracks

Segfaults occur both when using local and when using remote files, the script uses remote files to make it easier to reproduce on other computers.

**Comment by wm4** [comment]
Thanks for the elaborate test case.
