### ISSUE TITLE
"Unable to update the static FcBlanks" on exit

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#1985]
On Windows 8.1 I get the error 
```
Unable to update the static FcBlanks: 0x****
```
multiple times with different codes (see [paste](http://pastebin.com/raw.php?i=kxK6rEEG)) when exiting mpv. It does not seem to affect playback in anyway though.

**Comment by wm4** [comment]
@lachs0r: Google revealed the following link, is it a problem with the fonts.conf you ship?: http://comments.gmane.org/gmane.comp.fonts.fontconfig/5495

**Comment by wm4** [comment]
@occivink: also, did you paste a mpv log into your mpv.conf or so? Because that's what it looks like. (Not the cause of the FcBlanks warnings, though.)

**Comment by occivink** [comment]
Not that I know of. That was just the output of 
```
mpv --idle --force-window -v
```
However, your previous comment made me update my fonts.conf (I must have forgotten to do that previously) which got rid of the error. Thanks.

**Comment by wm4** [comment]
Your log contains entries like ``[cplayer] C:/Program Files/mpv/mpv/mpv.conf:7: unparseable extra characters: 'libavformat     56.31.102'``, which looks like mpv.conf contains a log, on which the option parser chokes.

**Comment by occivink** [comment]
Ah I see, that was indeed a manipulation error.
