### ISSUE TITLE
Can MPV decode DTS-HD MA and DTS-HD HRA?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#1986]
As title, can MPV decode DTS-HD MA and DTS-HD HRA?

**Comment by lachs0r** [comment]
Yes, if FFmpeg has been compiled with [dcadec](https://github.com/foo86/dcadec) support.

**Comment by lachs0r** [comment]
(My Windows builds are built with dcadec in case anyone is wondering)

**Comment by kevmitch** [comment]
To futher clarify - if dcadec support is compiled in it should "just work".
You can convince yourself of this by adding ```--msg-level=ad=v``` to your command line when playing a file with dts audio. You should see something like

```
[ad] Codec list:
[ad]     lavc:libdcadec (dts) - dcadec DCA decoder
[ad]     lavc:dca (dts) - DCA (DTS Coherent Acoustics)
[ad] Opening audio decoder lavc:libdcadec
[ad] Requesting 1 threads for decoding.
[ad] Selected audio codec: dcadec DCA decoder [lavc:libdcadec]
```

**Comment by laichiaheng** [comment]
How do I install the libdcadec?
I install mpv and ffmpeg from ppa

**Comment by kevmitch** [comment]
On linux that's a good question. You could just ask whichever ppa you're using to build ffmpeg with dcadec. 

You could alternatively use [mpv-build](https://github.com/mpv-player/mpv-build) and manually build and install [dcadec](https://github.com/foo86/dcadec) into the mpv-build build_libs directory before you compile mpv and ffmpeg and then add ``--enable-libdcadec`` to the ``ffmpeg_options`` file. 

This doesn't work if you want to build the debian package however. I've found that the only way without modifying git-controlled stuff in mpv-build is to make a separate debian package for libdcadec and install it first, then build the mpv package with ``--enable-libdcadec`` in ``ffmpeg_options``. 

This would of course be a lot easier if dcadec were actually in debian. I've been wondering if there isn't something we could do to streamline the process for mpv-build.

**Comment by mc4man** [comment]
I tried  doing ppa builds using a packaged dcadec but ran into a wierd issue where i386 built fine but amd64 failed to find dcadec on it's configure. (this is a mpv with static ffmpeg build.) the build log was not informative as to cause & doing the same build locally worked so at a current loss???
anyway hacked around by including dcadec in the source, could have done more cleanly I guess. 
(- the main issue with dcadec is it doesn't configure, just a makefile so edited the makefile to 
PREFIX ?= "../build_libs"
(in this ppa https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests
ex.
[ad] Codec list:
[ad]     lavc:libdcadec (dts) - dcadec DCA decoder
[ad]     lavc:dca (dts) - DCA (DTS Coherent Acoustics)
[ad] Opening audio decoder lavc:libdcadec
[ad] Requesting 1 threads for decoding.
[ad] Selected audio codec: dcadec DCA decoder [lavc:libdcadec]

Any corrections, ect.  on method employed  or if any ideas why amd64 can't find dcadec in a launchpad build are welcome

**Comment by kevmitch** [comment]
I have a similar problem when I try to install dcadec to /usr/local/ and then try and use mpv-build. It could be that setting the PKG_CONFIG variable overrides looking in /usr/local or something.

For building right into the static binary, the dcadec makefile reads the environment variable 
PREFIX

```
$ cat scripts/dca-build 
#!/bin/sh
set -e
BUILD="$(pwd)"

cd "$BUILD"/dcadec
PREFIX="$BUILD/build_libs" make install
```

I have been successful in building and linking to a separate dcadec package on amd64. Did you make the new mpv-build pacakge build-depend on the dcadec one?

**Comment by mc4man** [comment]
No, for the moment am just including it in the mpv build source. Next update I'll try your suggested dcadec-build script vs. my edit to dcadec's makefile, seems better/more proper, so thanks for that.

As far as using a dcadec package for the mpv with static ffmpeg build will continue to look at. As mentioned it works fine here if built locally but in Launchpad, while i386 is fine,  the amd64 build fails to find dcadec in the ffmpeg configure.
When I update my personal LP  ffmpeg shared packages I'll try again & see what happens.
If curious the dcadec package source can be dl'ed from here, noting for any readers there is no intention on my part for others to use this ppa & by itself one can't as it deps on other ppa's..
https://launchpad.net/~mc3man/+archive/ubuntu/ffmpeg-tests5/+packages
(- the dcadec build there produces the binary & static libs, are you creating an .so?

**Comment by qyot27** [comment]
If you look at the entire dcadec branch network, there are a couple of nascent dev branches for CMake (https://github.com/kasper93/dcadec) and autotools (https://github.com/TimothyGu/dcadec) support, although I haven't attempted using them yet.  To be honest, I'd prefer CMake as soon as possible since that allows using Ninja (which is superior to Make on principle, and also quite often on execution and performance...even though on small projects like dcadec it'd mostly be negligible), but having both would be a good option.

So using self-rolled build scripts may not be necessary - just *git pull* from one of those two branches and then go through configuring like usual (and hope they finalize/open pull request/get merged soon so it's right there upstream).

**Comment by wm4** [comment]
Fuck CMake with a rusty rake.

**Comment by kevmitch** [comment]
> Fuck CMake with a rusty rake.
+1

Frankly, I think the current method of passing environment variables to dcadec make is perfect for such a small library. It should probably just be better documented.

**Comment by wm4** [comment]
Or it could follow autoconfig semantics... but granted, doing this with a simple build system like dcadec has is hard.

**Comment by pigoz** [comment]
for something as simple as dcadec autotools is the better choice

**Comment by mc4man** [comment]
Probably dumb ? - the orig . question was answered by 'if FFmpeg has been compiled with dcadec support.'
Is lavc:dca not also able to?
(- I no longer have a blu-ray drive & from online demos lavc:dca seems to be ok..

**Comment by kevmitch** [comment]
> Is lavc:dca not also able to?

Yes, but it is poorer quality. It only decodes the core. It can't handle extensions like lossless, high bit rate, or 7.1.
