### ISSUE TITLE
Screenshots do not include any post-processing by shaders

### ISSUE THREAD

**Issue by Soukyuu** [mpv-player/mpv#1990]
I just tried the new shader loading feature and while I got [this shader](https://github.com/haasn/gentoo-conf/blob/master/home/nand/.mpv/shaders/deband.glsl) to load, it does not show up on screenshots. I'd prefer to be able to see the final result on the screenshot, because switching between two screenshots to compare different shader settings is easier in an image viewer.

**Comment by wm4** [comment]
Map a key to ``screenshot window``, or use an external tool.

**Comment by Soukyuu** [comment]
That's even better, thanks.
