### ISSUE TITLE
there is feature: frame-by-frame like as quicktime (keyboard: right, left)?

### ISSUE THREAD

**Issue by manuelsongokuh** [mpv-player/mpv#1991]
hello

i NEED very frame-by-frame with keyboard: right and left, it's possible?

like as quicktime use frame-by-frame keyboard:right, left
VLC not supported..
does mpv can will add new feature?

**Comment by daikazoku** [comment]
You can use, by default, the keys "," and "." (see input.conf)

**Comment by wm4** [comment]
The ``,`` and ``.`` keys.

**Comment by manuelsongokuh** [comment]
ok thank YOU!! where i will change input.conf?
i'm opensuse kde4..

**Comment by manuelsongokuh** [comment]
i wish to change , and . to left, rght EASY for me keyboard, it's possible?
THANK YOUOO

**Comment by Argon-** [comment]
`.config/mpv/input.conf` or `~/.mpv/input.conf`:

    LEFT frame_step
    RIGHT frame_back_step
