### ISSUE TITLE
mpv can open direct from file iso (dvd-video)?

### ISSUE THREAD

**Issue by manuelsongokuh** [mpv-player/mpv#1993]
hello

i check search issues, not found...then
i need open from file ISO (dvd-video) created from dvdstyler but mpv can open from file iso (dvd-video) and navigator menu like as vlc?

for now vlc 2.2 not work file iso dvd-video..
and vlc 2.1 worked file iso, but nothing resolve for vlc then i wish to USE MPV, it's new for me ,and start to love MPV i never to use it and start to use it then i want to ask for file iso (dvd-video)?
thank you

**Comment by rrooij** [comment]
It works correctly here if I mount the iso and then play the mounted folder.

**Comment by manuelsongokuh** [comment]
ok but first: mount second mpv?
time is long..not FAST open.. i hope future mpv new feature: iso open with mpv without MOUNT ok?
my office has 20 peoples use fresh mpv but they dont know to use mount...this is not good...please add new feature ok?
before they used many times with vlc problem ZERO and now new problem for vlc 2.2 not work with iso...so they are blocked jobs...so i'm looking for alternative of vlc and found mpv (i never know and never to use it) now i start use mpv like as Fresh..but before i need true open iso without mount ok?
i cant teach them and they will not want to mount from terminal or natulis o dolphin...for this reason: best is: mpv opens iso direct without MOUNT ok?

i hope you to understand ok? byebye

**Comment by mc4man** [comment]
your issue(s) are more likely from dvdstyler than anything else. (maybe the same for devede)
mpv can handle dvdstyler iso's with multiple titles  somewhat directly - 
mpv dvdnav:// --dvd-device=dvd.iso or =/path/to/the.iso
( as far as vlc 2.2+ with dvdstyler iso's - if your vlc is built off of libav11 or less than it will probably work, if built off of ffmpeg 2.5 or higher probably won't work or work easily as menu will be screwed up

**Comment by manuelsongokuh** [comment]
i did test but not work terminal.. but i did say: peoples dont use never terminal and they dont know to use it because its job from windows never to use terminal this mean, they are impossible to use terminal so easy to use click and open automatic and NOT terminal.. mpv can does this feature to "direct from file iso (dvd-video)?

**Comment by manuelsongokuh** [comment]
hello
i did terminal:
mpv dvdnav:// --dvd-device=UFFICIALE-DVD-003.iso
not work MENU (navigator) but work to see movie, but nothinf menus...

if this will does resolve so i will fix in dolphin parameter:
file *.ISO and command: "mpv dvdnav:// --dvd-device"  without quote, but this is will work?

if it's complicated then i will not use mpv maybe...for period, i will looking for other alternative..
but i want know leave mpv so powerfully but i need this feature file iso direct not "TERMINAL" ok?

**Comment by rrooij** [comment]
Try `mpv dvdnav://menu` instead.

**Comment by manuelsongokuh** [comment]
hello
not work correct...(worked with mpv but not correct navigator) ..but did you try ?

**Comment by lachs0r** [comment]
mpv dvd://menu --dvd-device=file.iso

**Comment by manuelsongokuh** [comment]
![mpv-vlc](https://cloud.githubusercontent.com/assets/12126929/8280137/aff90022-18da-11e5-96e0-9e4bd8071de5.png)
hello i'm back here and reopen question..
maybe it's a bug, mpv worked as perfect for navigator! but there is missed:
-circle button
-strange rectangle opacity white..

vlc worked as perfect nothing to missed, (only not worked for version 2.2, remain problem again)
i wish to start to use mpv but i want to be fix this 2 strange..i dont know if that 2 stranged is bugs or not..

i show you dvdstyler start to design: circle button 
![mpv-vlc1](https://cloud.githubusercontent.com/assets/12126929/8280251/d1011b0a-18db-11e5-8fe0-d612106f9152.png)

**Comment by wm4** [comment]
mpv doesn't support dvd menu highlights correctly. This is unlikely to change, because it's relatively complicated, and nobody volunteered to change this.

**Comment by manuelsongokuh** [comment]
ok but it's a bug or missed feature of mpv?
not close this issue because future someone can fix or new feature ok?
i will wait and i will see this issue if will has news ok?

**Comment by wm4** [comment]
>ok but it's a bug or missed feature of mpv?

Both. Since DVD highlights cause so much complexity, we only render the highlight's bounding box with a white, translucent square.

> not close this issue because future someone can fix or new feature ok?

It's unlikely someone wants to fix this, and if, that person would be aware of the problem anyway.

I for one don't want to work on this (or DVD related things) at all.

It will likely be unimplemented forever.
