### ISSUE TITLE
Mpv ignores ass-force-style when subtitle is str

### ISSUE THREAD

**Issue by baco** [mpv-player/mpv#1994]
Although mpv uses ass subtitles as default, it is ignoring format configuration when the subtitle file is in SubRip format (str).

Before version 0.9.0 having this configuration:

    ass-force-style='FontName=Cantarell,Default.Bold=1,Default.FontSize=24,Shadow=1.5,BackColour=Black'

used to work, setting the default size and format even on srt subtitle files; now it doesn't

**Comment by wm4** [comment]
This option breaks ASS subtitles (and exists only for the purpose of breaking ASS subtitles). Use the ``--sub-text...`` options instead to configure srt subtitles.

**Comment by wm4** [comment]
PS: and if you do actually want to override ASS subtitles, use ``--ass-style-override`` (whatever mode provided by it suits you).

**Comment by baco** [comment]
Then, it would need to set the a lot more settings to make it work in both cases, ASS and SubRip; ``ass-force-style=...``, ``sub-text-font=...``, ``sub-text-bold=yes``, ``sub-text-font-size=...``, ``sub-text-shadow-offset=...`` and ``sub-text-shadow-color=...``, at least, to almost reach the same behaviour, and even then not obtaining the exact same visual result in both cases (the shadow options do not behave in the same way in ASS and SubRip).

I've tried ``ass-style-override=yes`` but it doesn't apply the style set with ``ass-force-style`` :-(

**Comment by baco** [comment]
An example of how impossible is to obtain the exact same visual result with two separate set of settings:

``ass-force-style``
![shot0001](https://cloud.githubusercontent.com/assets/102958/7869546/ced1e50c-0559-11e5-91d9-c114b79c4908.jpg)

``sub-text-*``
![shot0002](https://cloud.githubusercontent.com/assets/102958/7869554/dba7e16e-0559-11e5-9d7b-f1272cdbaf3b.jpg)

**Comment by wm4** [comment]
Might be because they use a different scale.

>I've tried ass-style-override=force but it doesn't apply the style set with ass-force-style :-(

That's something else. ``force`` applies --sub-text-... to ASS subtitles. ass-force-style is always applied (but only to ASS subtitles), unless ``ass-style-override=no`` is used.

**Comment by baco** [comment]
> Might be because they use a different scale.

Ok, I've re-scaled the shadow offset for sub-text, but the result still not the same because the algorithm is different. With ASS the shadow is like projected, tracing all black between the character and it's shadow; with sub-text-, the shadow remains separated of the corresponding character.

> That's something else. ``force`` applies --sub-text-... to ASS subtitles. ass-force-style is always applied (but only to ASS subtitles), unless ``ass-style-override=no`` is used.

The, what I would be needing is another option to ``ass-style-override`` like ``inverse-force`` that allows me to apply ``ass-force-style`` format to SubRip subtitles again :-)
