### ISSUE TITLE
Using mpv with an external GUI

### ISSUE THREAD

**Issue by curious2know** [mpv-player/mpv#1995]
Now that the option --slave-broken has once again been removed, how are we supposed to make mpv work with an external GUI such as SMplayer in Linux? Is it even possible to make use of any GUIs?

Trying to use mpv with the SMplayer GUI after this commit (e8a1d35e9c439ba8a86507e02292cc24fef0174a) simply gives the error message: 

"Error parsing option slave-broken (option not found)
Setting command line option '--slave-broken=' failed.
Exiting... (Fatal error)"

No file is played.

Curious2Know

**Comment by Argon-** [comment]
There are "real" (using the client API) front-ends/forks, e.g. http://bakamplayer.u8sand.net/ or https://bomi-player.github.io/

**Comment by wm4** [comment]
The ``--slave-broken`` option has been remove for ages, and there is a documented equivalent replacement: https://github.com/mpv-player/mpv/blob/master/DOCS/mplayer-changes.rst#slave-mode

Proper clients should use libmpv, or at least the json IPC. smplayer does several things in a way we don't like to see (and tends to thoroughly break mpv's defaults).
