### ISSUE TITLE
Consider removing TOOLS/vf_dlopen/framestep.c

### ISSUE THREAD

**Issue by Nikoli** [mpv-player/mpv#1996]
Now both ffmpeg and libav have ```select``` video filter which replaces ```framestep``` fine, ffmpeg also has ```framestep``` filter ported from mplayer, so may be it is time to remove https://github.com/mpv-player/mpv/blob/master/TOOLS/vf_dlopen/framestep.c ?
See also https://bugzilla.libav.org/show_bug.cgi?id=517

**Comment by wm4** [comment]
I'm not sure why you suddenly think it should be removed, but thanks for your opinion.

**Comment by Nikoli** [comment]
I thought ```vf_dlopen``` is mostly for filters which are not yet in both ffmpeg in libav. Recently i found that it can be replaced by ```libavfilter``` from both ffmpeg and libav, so i opened this bug.
But i guess it makes sense to keep ```framestep``` as simplest example for writing ```vf_dlopen``` filters.

**Comment by wm4** [comment]
>I thought vf_dlopen is mostly for filters which are not yet in both ffmpeg in libav.

Not really. It was meant for ad-hoc filters which can't be builtin filters for various reasons, or filters which I didn't want in mpv (like vf_telecine). Now external filters can be provided via vapoursynth, plus we support libavfilter (when vf_dlopen was added we didn't), and now vf_dlopen is pretty useless.
