### ISSUE TITLE
If I add --fullscreen or --fs, I have to double click my mouse 3 times to leave fullscreen.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2001]
OS: Linux
If I add --fullscreen or --fs, I have to double click my mouse 3 times to leave fullscreen.

**Comment by rrooij** [comment]
I can't reproduce this. Clicking twice is enough here is enough to exit fullscreen state.

Which version of mpv are you running? And which DM/WM, etc? I'm using i3wm and the latest git build

**Comment by Paviluf** [comment]
Same her, clicking twice is enough

**Comment by laichiaheng** [comment]
my mpv version is 0.9.2
window manager : Pantheon
what is DM?

**Comment by mc4man** [comment]
That seems to be what will happen on elementary_os, doesn't 'take' till 3rd attempt. Likely you'd see the same with Esc button though I gather the run command is slightly different
(  Run command: set, flags=9, args=[fullscreen, no] vs. Run command: cycle, flags=9, args=[fullscreen, (NULL)]

**Comment by wm4** [comment]
Retry with mpv git master.
