### ISSUE TITLE
[Win64] Controlling mpv with an input file not working?

### ISSUE THREAD

**Issue by sloppy9** [mpv-player/mpv#2004]
I can confirm the --input-file is being read when mpv is executed, but any commands sent after that are ignored, and being able to delete the input file would suggest it is no longer opened for reading by mpv.

Is there something I'm doing wrong or is it not possible to pipe commands to mpv in windows?

example of my usage:-
> mpv example.mp4 --input-file=input.txt
> echo quit > input.txt

**Comment by wm4** [comment]
It doesn't really work this way. The file is fully read on program start, and closed as soon as the end of the file is reached. The real usefulness of this feature is with FIFOs (pipes), which establish a communication channel between 2 processes, and mpv will keep the pipe open as long as possible (meaning you can give it commands by writing something to the FIFO).

Unfortunately, Windows is a bit different, so I don't know if this option can take named pipes. But maybe it does.

**Comment by sloppy9** [comment]
Ahh, now I feel silly! thanks for the reply.
