### ISSUE TITLE
Force subtitle size to specific size

### ISSUE THREAD

**Issue by niksy** [mpv-player/mpv#2006]
Is there an option which completely ignores `sub-scale-with-window` and `sub-scale-by-window` and uses defined value for subtitle? E.g. if I set subtitle size to 40px, I would expect it to be 40px regardless of window size.

**Comment by wm4** [comment]
No - the library we use, libass, takes such mangled values only. But if you use the right options (one of those you mentioned, I'm not perfectly sure which combination is required), it's a matter of applying a factor.
