### ISSUE TITLE
Finder randomly overlays main window

### ISSUE THREAD

**Issue by niksy** [mpv-player/mpv#2007]
In OSX, when I’m watching the video, Finder randomly pops out and overlays the whole video player. It’s manifested in a way that OSX first shows mouse cursor for 2 seconds and then just pops out current Finder window.

I thought it was something related to mouse movement, but I never touched any periperal in that period so it should be something related to software.

**Comment by wm4** [comment]
Any exact steps how to reproduce it?

**Comment by niksy** [comment]
Unfortunately no, it just shows up randomly, but I tried looking at the Console.app at the time of latest "event" and here is what I get:

```
01.06.15. 21:39:25,837 locationd[76]: Location icon should now be in state 'Active'
01.06.15. 21:39:26,296 airportd[51]: -[CWXPCConnection performScanWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergeScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:interfaceName:waitForWiFi:waitForBluetooth:token:priority:reply:]: !!! SCAN request received 0.6259 seconds after previous scan request from 76 (locationd)
01.06.15. 21:39:26,308 airportd[51]: -[CWXPCConnection performScanWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergeScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:interfaceName:waitForWiFi:waitForBluetooth:token:priority:reply:]: !!! SCAN request received 0.0121 seconds after previous scan request from 76 (locationd)
01.06.15. 21:39:27,116 Console[1056]: Failed to connect (_consoleX) outlet from (NSApplication) to (ConsoleX): missing setter or instance variable
01.06.15. 21:39:27,924 locationd[76]: Location icon should now be in state 'Inactive'
```

Maybe this is something that can help?

**Comment by niksy** [comment]
Been happening randomly in the last week, always with the same latest messages inside Console.app.

This is actually something I experienced from the first time I used mpv, but always put it to the fact that it will be somehow resolved in the next version.

**Comment by wm4** [comment]
Well, if there's no way to reproduce, I don't know how this could be solved.

Does it work if you disable mouse hiding?

**Comment by wm4** [comment]
No reaction.
