### ISSUE TITLE
mpv prints nothing to the cmd window on Windows

### ISSUE THREAD

**Issue by steinuil** [mpv-player/mpv#2008]
Since I upgraded to the latest i386 build from http://mpv.srsfckn.biz (with chocolatey), mpv doesn't print anything to the cmd window anymore. I also tried previous i386 builds up to 2015-04-11 and the result is the same.

I can still read the ouput if I redirect it to a file, but otherwise it remains silent.

I'm using mpv git-a075dfb on Windows 7 32-bit. Running mpv -v doesn't show anything weird.

**Comment by wm4** [comment]
Try using ``mpv.com`` instead of ``mpv.exe``. If you just use ``mpv`` in cmd.exe, it should use ``mpv.com``.

**Comment by steinuil** [comment]
Ah. I guess it was chocolatey's fault for linking mpv.exe instead of mpv.com to the \bin directory then.
