### ISSUE TITLE
Luasocket from LuaRocks works incorrectly inside MPV (on Linux, possible luasocket bug?)

### ISSUE THREAD

**Issue by rumkex** [mpv-player/mpv#2009]
Using MPV 0.9.2 from Ubuntu PPA, ppa:mc3man/trusty-media.

To reproduce:
* Install luasocket from rocks (**not** the apt repository, which works fine)
* Try something simple in a Lua script, like creating a socket:

        local socket = require 'socket'
        assert(socket.tcp())

* This works perfectly fine in a Lua interpreter, but fails to run inside MPV, returning an error (which seems to indicate that UNIX sockets aren't being created properly on C side of things)

What am I doing wrong? I can't even pinpoint who's at fault here.

**Comment by wm4** [comment]
Is it a Lua 5.1 vs. 5.2 difference? (mpv might be using a different liblua than the lua command line interpreter.)

**Comment by rumkex** [comment]
No, I'm using Lua 5.2 as an interpreter (cleaned out all lua 5.1 packages to be sure). Library itself is built against Lua 5.2 too.

**Comment by wm4** [comment]
In any case, there's probably no way mpv could somehow break Lua modules (except for namespace conflicts, which most likely don't happen here).

**Comment by rumkex** [comment]
It doesn't make any sense to me either, but it does look like there's something different between those two environments that causes luasocket to break.

**Comment by wm4** [comment]
Cause unknown, we can probably blame external circumstances.

**Comment by syehoonkim** [comment]
Dear,
Recently, I got this trouble.
Using the latest SourceForge's binary and luasocket, I encountered mpv being killed whenever I try to
```
socket=require("socket")
```
without any error message.
And I have found that with my own build mpv, luasocket works well.
I wonder if there is any plan to resolve this issue.
Thank you.
