### ISSUE TITLE
High Fans RPM when using –hwdec=vda

### ISSUE THREAD

**Issue by asoksevil** [mpv-player/mpv#2010]
I just realized that although CPU usage remains low (20-30% for a 1080p H264 file) fans can rev up to 4k-5k with no reason whatsoever while QuickTime seems to have the same CPU usage with no fans kicking in.

**Comment by kevmitch** [comment]
are you using opengl-hq? or even fancier vo options? These will likely do a lot more gpu work than quicktime to improve video quality, which will not show up as CPU use, but still dissipate a lot of power.

**Comment by asoksevil** [comment]
Yeah, you were absolutely right. I was using opengl-hq, as soon as I removed it fans didn´t kick off at all.
