### ISSUE TITLE
Request: input.conf option to not save on quit

### ISSUE THREAD

**Issue by vitorgalvao** [mpv-player/mpv#2011]
Perhaps an odd request, that should be made clear by the use case.

On OS X, when playing a video via the app bundle (as opposed to the CLI), it sometimes happens that I need to pause a video to do something else briefly. I then forget about it, open a new video and can see it replacing the old video in the app *losing playback position (and other details) from the first file*.

This is solved just fine with `save-position-on-quit` in `.mpv/config`. However, sometimes I *do* want to reset all playback options on my file, and this solution leaves me without an option to do so — it effectively makes `quit` and `quit_watch_later` behave the same, when set in `.mpv/input.conf`.

My request is then a `quit_dont_watch_later` (or whatever name) that would forcibly bypass `save-position-on-quit` (or `--save-position-on-quit`, if set via the command line).

---

There’s is [a workaround](https://github.com/mpv-player/mpv/issues/2011#issuecomment-108025326) for this, by using [a script](https://github.com/mpv-player/mpv/issues/2011#issuecomment-108004532), but would be nice to have this natively.

**Comment by kevmitch** [comment]
I think you want just ``quit``?

**Comment by kevmitch** [comment]
oh, ``save-position-on-quit`` overrides that

well, then don't use ``save-position-on-quit``, and instead bind different keys to ``quit`` and ``quit_watch_later``

**Comment by kevmitch** [comment]
i.e.,
```
q quit_watch_later
shift+q quit
```

**Comment by vitorgalvao** [comment]
I do have different keys for both options. The point of my post is that that does not matter, as they behave the same when `save-position-on-quit` is used. I explicitly point that out.

**Comment by vitorgalvao** [comment]
I do have different keys for both options. The point of my post is that that does not matter, as they behave the same when `save-position-on-quit` is used.

I want to use `save-position-on-quit`. Not having it makes for a worse experience and makes me lose position in some cases. I explicitly point that put as the use case.

**Comment by selsta** [comment]
```
function quit_fn()
    mp.set_property("options/save-position-on-quit", "no")
    mp.command("quit")
end

mp.add_forced_key_binding("q", "quit_dont_watch_later", quit_fn)
```

**Comment by vitorgalvao** [comment]
Thank you, @selsta. That works great.

For anyone that finds this in the future, the easiest way to get it running is to just insert that code into a `quit_dont_watch_later.lua` file inside `.mpv/scripts`.

Will leave the issue open in case any collaborator is interested in doing this natively, but naturally feel free to close if there’s no interest.
