### ISSUE TITLE
Indexing fonts to speed up launching

### ISSUE THREAD

**Issue by Adrenaline67** [mpv-player/mpv#2012]
Hi,

I'm looking for a way to index all the fonts I have installed on my windows into my fonts.conf file in order to speed up MPV's lauching (I guess I have too many fonts...). Importing every time new fonts to MPV's folder is a bit annoying, but I'll do it if I can't manage otherwise.

Thank you

**Comment by lachs0r** [comment]
There’s a line in fonts.conf that you need to uncomment to enable system fonts 
(which will make fontconfig rebuild its font cache and scan all of your system 
fonts every time you install/uninstall one, which will take forever).

However, you should never need to enable *all* system fonts, hence the default 
is to only load fonts from the fonts directory.

This is a fontconfig issue and will be fixed once libass is able to use native 
Windows fonts APIs.

**Comment by Adrenaline67** [comment]
Yes I uncommented the line, I forgot to mention it. Every time I open a video I have to wait the cache to load every font I have on my windows folder. Well, I guess I have no other choice to wait until a fix.
I will keep using MPV's folder (with commented line) until so.

Thank you for your answer !

**Comment by wm4** [comment]
This has a good chance of getting fixed in libass soon.
