### ISSUE TITLE
Blocking with MVTools

### ISSUE THREAD

**Issue by Slyneth** [mpv-player/mpv#2013]
I am using this script and seeing blockings. Do anyone know any better way of doing this?

    import vapoursynth as vs
    core = vs.get_core()
    core.std.LoadPlugin(path='/usr/local/Cellar/mvtools/HEAD/lib/libmvtools.dylib')
    
    clip = video_in
    
    src_num = int(float(container_fps) * 1e3)
    src_den = int(1e3)
    play_num = int(float(display_fps) * 1e3)
    play_den = int(1e3)

    if not (container_fps > 59):
        clip = core.std.AssumeFPS(clip, fpsnum=src_num, fpsden=src_den)
        sup  = core.mv.Super(clip, pel=2, hpad=16, vpad=16)
        bvec = core.mv.Analyse(sup, truemotion=True, blksize=16, isb=True, chroma=True, search=3)
        fvec = core.mv.Analyse(sup, truemotion=True, blksize=16, isb=False, chroma=True, search=3)
        clip = core.mv.BlockFPS(clip, sup, bvec, fvec, num=play_num, den=play_den, mode=3, thscd2=48)
    
    clip.set_output()
    
    print("Source fps", (src_num/src_den))
    print("Playback fps", (play_num/play_den))

And this is what I use for vo: 

    vo=opengl-hq:blend-subtitles:icc-profile-auto:waitvsync

**Comment by haasn** [comment]
Not an mpv issue.

**Comment by Argon-** [comment]
You are using `BlockFPS`, of course you see blocks. You can use `FlowFPS` for pixel based motion compensation (opposed to — guess what — block based motion compensation used by `BlockFPS`). However, this will be tremendously slower.

**Comment by wm4** [comment]
Not much left to say, closing.
