### ISSUE TITLE
What's the difference between JinC & ewa_lanczossharp ?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2015]
In the manual, it says that ewa_lanczossharp is jinc,
so what's the difference between them?

**Comment by Cpuroast** [comment]
ewa_lanczos is JINC, ewa_lanczossharp is a tweaked version with optimal values. It's slightly harder on the GPU than ewa_lanczos.
If your GPU is strong enough, ewa_lanczossharp is the recommended scaler, you can use it for both scale and cscale.

**Comment by laichiaheng** [comment]
But I saw jinc in the scale option when I typed " mpv --vo=opengl-hq:scale=help "

**Comment by Cpuroast** [comment]
As you can see from the manual, ewa_lanczos is simply an alias for the jinc-windowed jinc scaler.

ewa_lanczos
Elliptic weighted average Lanczos scaling. Also known as Jinc. Relatively slow, but very good quality. The radius can be controlled with scale-radius. Increasing the radius makes the filter sharper but adds more ringing.

(This filter is an alias for jinc-windowed jinc)

**Comment by laichiaheng** [comment]
![jinc](https://cloud.githubusercontent.com/assets/9532105/7952597/a390dcaa-09ea-11e5-8da9-1307305a6036.png)
So the 2 options are the same?

**Comment by Cpuroast** [comment]
close enough, but not exactly, ewa_lanczos is an alias which combines a jinc window with a jinc scaler.
ewa_lanczossharp is simply a tweaked version of ewa_lanczos.

Here are the 3 options pulled straight from the source code, as you can see they are similar but not quite the same.

{{"jinc",           3,  jinc, .resizable = true}, .polar = true},
{{"ewa_lanczos",    3,  jinc, .resizable = true}, .polar = true, .window = "jinc"},
{{"ewa_lanczossharp", 3.2383154841662362, jinc, .blur = 0.9812505644269356, .resizable = true}, .polar = true, .window = "jinc"},

**Comment by lachs0r** [comment]
To clarify: ewa_lanczos and variations thereof are jinc used as the weighting 
function and also as the windowing function for the resampling kernel.
This is equivalent to vo=opengl-hq=scale=jinc:scale-window=jinc.

So Jinc is not a typical resampling kernel by itself; it is a function, 
similar to Sinc, but for use with cylindrical filtering operations. 
mpv uses Jinc as the weighting function for EWA resampling. The ewa_* and 
haasnsoft scalers are the results of using that weighting function with 
different windowing functions.

Lanczos is Sinc-windowed Sinc, and as the EWA “equivalent” of Sinc is Jinc, 
EWA Lanczos is Jinc-windowed Jinc.

Calling that filter just Jinc is therefore incorrect, or at least confusing.

(Going to poke @haasn here just in case I got any of that wrong)
