### ISSUE TITLE
mpv gives Segentation fault at Start-up

### ISSUE THREAD

**Issue by anminosti** [mpv-player/mpv#2017]
Hej,

I've run an update on my system debian jessy with sid-libaries and afterwards i get everytime the following: 'Segmentation fault'
How can I use mpv again?

Thx Max

gdb mpv
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i586-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mpv...(no debugging symbols found)...done.

(gdb) run --no-config MP3-hi.pls 
Starting program: /usr/bin/mpv --no-config MP3-hi.pls
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/i686/cmov/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0xb4d4d788 in nettle_yarrow256_update ()
   from /usr/lib/i386-linux-gnu/libnettle.so.4

(gdb) thread apply all backtrace

Thread 1 (Thread 0xb2d2c800 (LWP 26522)):
#0  0xb4d4d788 in nettle_yarrow256_update ()
   from /usr/lib/i386-linux-gnu/libnettle.so.4
#1  0xb5aa3641 in ?? () from /usr/lib/i386-linux-gnu/libgnutls-deb0.so.28
#2  0xb5aa3804 in ?? () from /usr/lib/i386-linux-gnu/libgnutls-deb0.so.28
#3  0xb5a0c3e6 in ?? () from /usr/lib/i386-linux-gnu/libgnutls-deb0.so.28
#4  0xb59ffd6d in gnutls_global_init ()
   from /usr/lib/i386-linux-gnu/libgnutls-deb0.so.28
#5  0xb59e0534 in ?? () from /usr/lib/i386-linux-gnu/libgnutls-deb0.so.28
#6  0xb7fed86e in call_init (l=<optimized out>, argc=argc@entry=3, 
    argv=argv@entry=0xbffff584, env=env@entry=0xbffff594) at dl-init.c:78
#7  0xb7fed964 in call_init (env=0xbffff594, argv=0xbffff584, argc=3, 
    l=<optimized out>) at dl-init.c:36
#8  _dl_init (main_map=0xb7fff930, argc=3, argv=0xbffff584, env=0xbffff594)
    at dl-init.c:126
#9  0xb7fdfd3f in _dl_start_user () from /lib/ld-linux.so.2

**Comment by wm4** [comment]
It crashes in libnettle, which in turn is called by the libgnutls library constructor. This is 100% out of mpv's control, and happens even before a single line of mpv code is executed.

Report the problem to Debian.
