### ISSUE TITLE
Allow changing total/remaining time display default from osc.conf

### ISSUE THREAD

**Issue by teohhanhui** [mpv-player/mpv#2019]
Maybe something like `timeremainingstyle=remaining|total`

**Comment by ChrisK2** [comment]
Anyone else who would like to have this?

**Comment by atomnuker** [comment]
I'd like to have a milliseconds display variable exposed to the config file. Though this isn't a bad setting to have too.

**Comment by csLiKevin** [comment]
+1 I would like to have this feature.

**Comment by ChrisK2** [comment]
Implemented as of aed7c848407a472ccc63337b3bd7cef97defe8e4.
