### ISSUE TITLE
Error parsing option ytdl-raw-options (option could not be parsed)

### ISSUE THREAD

**Issue by Ram-Z** [mpv-player/mpv#2021]
Trying to pass a password containing `%` to youtube-dl fails.

```
$ mpv --ytdl-raw-options=password='%'
Invalid length 0 for 'ytdl-raw-options'
Unparseable garbage at end of option value: '%'
Error parsing option ytdl-raw-options (option could not be parsed)
Setting command line option '--ytdl-raw-options=password=%' failed.
```

Escaping the `%` with another `%` works.

```
$ mpv --ytdl-raw-options=password='%%'
```

**Comment by wm4** [comment]
Works as intended. A ``%`` at the start of a string indicates a special escaping mode, and ``%%`` produces a literal ``%`` instead.

**Comment by Ram-Z** [comment]
The `%` doesn't need to be at the beginning, it'll fail for `foo%bar` as well.
```
Unparseable garbage at end of option value: '%bar'
```

I do understand where this is coming from, but I don't get why this would be "intended" behaviour. Is there any use for the `%` escape sequence when parsing all options to mpv? The only use for it I found in the man page is for `--screenshot-template`, no other option seems to use these format specifiers. IMHO the string should just get passed as is to youtube-dl.

Anyway, this is not that important, I can easily mangle the password to escape the `%`, just wanted to let you know that the current behaviour surprised me.

**Comment by Ram-Z** [comment]
Actually, I can't escape it.

```
$ mpv --ytdl-raw-options=password='foo%%bar' 
Unparseable garbage at end of option value: '%%bar'
Error parsing option ytdl-raw-options (option could not be parsed)
Setting command line option '--ytdl-raw-options=password=foo%%bar' failed.
```

**Comment by wm4** [comment]
These rules apply: http://mpv.io/manual/master/#escaping-spaces-and-other-special-characters

**Comment by Ram-Z** [comment]
Alright... so these both work:

```
mpv --ytdl-raw-options=username="$user",password="%${#pass}%$pass" "$@"

mpv --ytdl-raw-options=username="$user",password="[$pass]" "$@"
```

Thanks
