### ISSUE TITLE
regression from 0.9.1 to 0.9.2: --sstep option

### ISSUE THREAD

**Issue by Kimik0** [mpv-player/mpv#2023]
A command line like this:
mpv --start=+<offset> --sstep=<interval> --hr-seek=yes --no-audio --untimed --vo=image:format=png:outdir=<wherever> <videofile>
gave a fixed number of png files for a given videofile, with the correct intervals between them, in v0.9.1.

In v0.9.2, the same command line, with the same parameters and videofile, a) produces about half the number of png files, b) that number is not fixed anymore; it varies between runs.

**Comment by wm4** [comment]
Can't reproduce.

**Comment by Kimik0** [comment]
I'm using the builds from here: `https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media`
In particular, these two packages:
`https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media/+files/mpv_0.9.2%7Etrusty_amd64.deb`
`https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media/+build/7370966/+files/mpv_0.9.1%7Etrusty_amd64.deb`

For a video of 24m11s length, with this command line:

`mpv --start=0:00:11.00 --sstep=22.0 --hr-seek=yes --no-audio --untimed --vo=image:format=png:outdir=/tmp/blah /tmp/testvideo.mp4`

I get this output from v0.9.1:

> Playing: /tmp/testvideo.mp4
>  (+) Video --vid=1 (*) (h264)
>      Audio --aid=1 --alang=und (*) (aac)
> [vo/image] Creating output directory '/tmp/blah'...
> Opening video filter: [pullup]
> Opening video filter: [gradfun]
> Opening video filter: [lavfi graph=pp=ac]
> VO: [image] 640x480 yuv420p
> [vo/image] Saving /tmp/blah/00000001.png
> [vo/image] Saving /tmp/blah/00000002.png
> [vo/image] Saving /tmp/blah/00000003.png
> ...
> [vo/image] Saving /tmp/blah/00000064.png
> [vo/image] Saving /tmp/blah/00000065.png
> [vo/image] Saving /tmp/blah/00000066.png
> 
> 
> Exiting... (End of file)

No matter how many times I try that, it always gives the same number of png files, 66. That's the expected number ((24m11s-11s)/22s=65.45). The images are also always the same (i.e. no timing differences)

With v0.9.2 however, I get this output:

> Playing: /tmp/testvideo.mp4
>  (+) Video --vid=1 (*) (h264)
>      Audio --aid=1 --alang=und (*) (aac)
> [vo/image] Creating output directory '/tmp/blah'...
> Opening video filter: [pullup]
> Opening video filter: [gradfun]
> Opening video filter: [lavfi graph=pp=ac]
> VO: [image] 640x480 yuv420p
> [vo/image] Saving /tmp/blah/00000001.png
> [vo/image] Saving /tmp/blah/00000002.png
> [vo/image] Saving /tmp/blah/00000003.png
> ...
> [vo/image] Saving /tmp/blah/00000034.png
> [vo/image] Saving /tmp/blah/00000035.png
> [vo/image] Saving /tmp/blah/00000036.png
> 
> 
> Exiting... (End of file)

I don't know where it got that number of 36 from, but it's certainly not the correct number. What's more, when I try that same command line several times, I get different results. Sometimes it's 36 images, sometimes 37, just now I got only 34. Even if the total number of images is the same for two runs, the images will look different here and there, implying timing differences.

I hope this helps clarify what I meant, and that you can find the bug with this info.

**Comment by avih** [comment]
The removed code was restored at b694f480fef25e9f795dff1ad614d6a163026ac6 , supposedly with this bug fixed.

Could you please confirm that the bug doesn't exist with latest master?

**Comment by Kimik0** [comment]
I have mpv installed from a .deb package (as described above). Where can I find one of 'master'?

The latest that https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests has is 0.9.2+git4.2, which still has the bug (it says "built 15 hours ago", but that may have been code from before this revert).
