### ISSUE TITLE
command line parsing issue with cache option

### ISSUE THREAD

**Issue by p-pioneer-q** [mpv-player/mpv#2026]
The "--cache" option with the syntax: "--cache value" doesn't work anymore (space is matched like an IFS), only the one field syntax: "--cache=value" now work.

MPV Version : 0.9.2-git-6beed16

**Comment by wm4** [comment]
This is expected. ``--cache`` without a value enabled the cache with default size. This is why nobody should use the old (ambiguous) syntax.
