### ISSUE TITLE
mpv indexes dvd titles starting at 0 instead of 1

### ISSUE THREAD

**Issue by postmodern** [mpv-player/mpv#2028]
Noticed that `mpv dvd://0` plays DVD Title 1 and `mpv dvd://1` plays DVD Title 2. This appears to be a regression from mplayer2. All other DVD utils index DVD titles starting at 1.

**Comment by wm4** [comment]
Not sure why I should care...

**Comment by postmodern** [comment]
@wm4 backwards compatibility and interoperability.

**Comment by orbweaver** [comment]
I agree that it would be preferable to number the titles starting from 1, not 0. I understand that programmers like to number things from 0, but literally EVERY other DVD-related software on Linux (vlc, lsdvd, mplayer etc) uses 1 as the first title. Using 0-based numbering in mpv is a potential source of confusion for users and doesn't seem to have any real benefit.

**Comment by wm4** [comment]
Feel free to write a patch. I don't feel like cleaning up the mess after several other people messed with the base index.
