### ISSUE TITLE
Subtitles - Can't get the behaviour I expect to work

### ISSUE THREAD

**Issue by maniacgit** [mpv-player/mpv#2032]
I'm using libmpv in a VDR plugin. From there the file to play is selected and the VDR OSD is rendered using the overlay from mpv.

Currently if some issues to get a sane subtitle behaviour.
I'd like to achieve the following:
- a list of preferred languages is submitted, for this I set the slang
- as default no subtitles should be visible, except the force flag is set (in Matroska in my tests, but should also works on other formats like DVD/Bluray, ...), if there are more forced subtitles the first matching language from slang should be used. For this is set sub-forced-only
- if the user hits the subtitle key on his remote, he should be able to cycle from none(or forced if available) through the different languages until he reaches none(forced) again

If I start mpv like this no subtitles are displayed, also the forced one in Matroska is ignored. I'm also not able to cycle through the available subtitles.

If I start mpv without sub-forced-only always a subtitle is displayed.

**Comment by wm4** [comment]
I'm not so sure what you mean after all. If you want subtitles not to show up without interfering with default selection mechanisms, you could just set them to invisible (``v`` key binding).

**Comment by maniacgit** [comment]
I'd like to get a behaviour like a hardware DVD player.
At least one language should be the default language for subtitles (or a list if possible). I've tried the slang parameter to set those defaults.
When starting the movie only subtitles marked as forced in the container (mkv, DVD, ...) should be active as default. If there are more than one forced subtitle in the container, the first matching language from slang should be preferred.
If I submit the "cycle sub" command I want to cycle through all available subtitles from the container. If I reach the end the forced subtitle should be displayed again (or none if there is no forced available).

**Comment by wm4** [comment]
Forced subtitles are usually not separate tracks, but just per-subtitle-event flags. The option ``--sub-forced-only`` controls this. Of course it's also possible that some files are ripped in a way that the forced subs were separated into an additional track.

**Comment by maniacgit** [comment]
Ok, good to know. I only saw this in Matroska, there you can set a forced flag to the whole subtitle also, but if doing so they are not displayed with sub-forced-only either.

But I'm still not getting an idea how to implement this with the existing parameters in a sane way while using the client api.

**Comment by kevmitch** [comment]
I just did a test with an mkv file with a single subtitle track. 

In the mkvtoolnix header editor, there are three relevant options:
"Default track' (yes/no)

> Set if that track (audio, video or subs) SHOULD be used if no language matches the user preference

"Forced Display" (yes/no)

> Set if that track MUST be used during playback. there can be many forced track for a kind (audio, video or subs). The player should select the one whose language matches the user preference or the default + forced track.

"Language" (three letter code)
> Specifies the language of the track in the Matroska languages form

I think the problem referred to is as follows:

track1 ```Language=eng``` ```Forced display=no``` ```Default track=no``` 
track2 ```Language=eng``` ```Forced display=yes``` ```Default track=no``` 

```mpv --no-config --slang=eng flie.mkv``` the file plays with track1, not track2 selected, so it appears to just ignore the ```Forced display``` flag.

**Comment by kevmitch** [comment]
> I just did a test with an mkv file with a single subtitle track. 

Correction: as stated below this, i used two subtitle tracks

**Comment by nathan-hoad** [comment]
I'm experiencing the same issue as @maniacgit. I would like to be able to specify a default language with the client API, and have mpv attempt to load that language automatically, not just for subtitles though but also for audio. The client API doesn't appear to expose anything alang/slang related though, only ID-based access methods.

The best I can think of at the moment is doing it manually outside of mpv, i.e. starting a video, getting the list of available audio/sub tracks, then selecting language based on that. Not difficult, but it would be nice if this was exposed by mpv.

@maniacgit, the third point you have about going through available subtitles, can you use the `cycle` command on the `sub` property to achieve what you're after?

**Comment by wm4** [comment]
Well, you can set the ``alang`` and ``slang`` options before loading. Maybe I'm missing something.

**Comment by nathan-hoad** [comment]
Hey, so you can! I completely missed that, thanks @wm4. I'd been looking at properties rather than options.

**Comment by maniacgit** [comment]
With the cycle option I didn't get the what I needed. Currently I still set slang and forced-subs-only. Then no subtitles are displayed at all, but the correct language is selected. I fetch the available subtitles from the client API and if the user hits the audio key on his remote a osd menu is shown where the user can select his subtitle track.
If he selected a track I switch to this track and set sub_forced_only to false and the subtitle is displayed. If the user switch the subtitle back to none currently I just set sub_forced_only to true again.

What I'm missing is the working forced flag on mkv. So if sub_forced_only is true, the forced subtitles from mkv are shown.
If this is working I think, I could extend my implementation that the track selected by mpv as default based on slang will be selected again on none in addition to set the sub_forced_only to true to get the behaviour I'm looking for.

**Comment by wm4** [comment]
>What I'm missing is the working forced flag on mkv. So if sub_forced_only is true, the forced subtitles from mkv are shown.

I'm not sure if I understand. Are you saying there's a per-track Matroska switch that requires the player to consider all subtitles in this track as forced?

Note that there is a default flag for Matroska, which doesn't have anything to do with it. It just means the track should be selected by default.

**Comment by kevmitch** [comment]
> I'm not sure if I understand. Are you saying there's a per-track Matroska switch that requires the player to consider all subtitles in this track as forced?

There is a per-track flag called "forced display". See my above post. See also [the Matroska spec](http://matroska.org/technical/specs/notes.html#Track_Flags).

**Comment by wm4** [comment]
And what should mpv do with it? We could export it to the client API.

**Comment by wm4** [comment]
>We could export it to the client API.

We do this now, and also use it for track default selection.

**Comment by maniacgit** [comment]
Fine, this should help to handle it from my code.
But it would be perfect if this also displays the subtitle while sub_forced_only is set.

**Comment by wm4** [comment]
Hm, I guess this can be closed too. Open a new issue if you don't agree.
