### ISSUE TITLE
Subtitles not shown in the window, and are cut off in full screen

### ISSUE THREAD

**Issue by yurivict** [mpv-player/mpv#2034]
The problem happens on one particular mpeg. Subtitles come from .sub file.
Second line of subtitles if cut off 50% in full screen. Also subtitles should be moved to visible area when in window.

Options --sub-text-margin-y --ass-use-margins don't help (if they are relevant).

Please tell me what information I can provide to investigate this.

mpv-0.8.3

**Comment by wm4** [comment]
I need a sample for this. Also test with git master or at least the latest release.

**Comment by yurivict** [comment]
This happens with the current trunk.

How can I extract the fragment? I have .mkv and .sub files, does mpv have the command 
line to extract from time1 to time2 with subtitles? If not, do you have the recommended way?

**Comment by wm4** [comment]
For both types of files, it should be ok just taking the first 1-10MB or so.

**Comment by yurivict** [comment]
Testcase: http://expirebox.com/download/3deb8157adc44b956aeac50c37853c24.html
Tar archive has 'run' script. Run it, immediately press 'f' and 'p', then press 'z' to Sub delay: -24,000ms, then press play again and observe the problem.

**Comment by wm4** [comment]
I'd consider this a broken file. The file is just a raw mpeg stream with DVD sub packets. There is not size and no palette (information which usually is provided by the DVD structure or by .idx files). mpv falls back to using the video as size - there's not really a better guess. In this case it goes wrong. Too bad.

You could probably create an .idx file for this (though I don't know how). Or just get a non-broken version of the file.
