### ISSUE TITLE
An issue with source-shader and vo_cmdline.

### ISSUE THREAD

**Issue by Entheogen010** [mpv-player/mpv#2035]
Hello,
I have encountered an issue when using vo_cmdline to set source-shader with opengl.

In mpv.conf I have set:
`vo=opengl:scale=ewa_lanczossharp:scale-antiring=0.5:cscale=ewa_lanczossharp:cscale-antiring=0.5:dscale=mitchell:dscale-antiring=0.5:dither=ordered:dither-depth=auto:sigmoid-upscaling:sigmoid-center=0.80:sigmoid-slope=8.0:scaler-resizes-only:fancy-downscaling:pbo:fbo-format=rgba32f:source-shader=/home/entheogen/.config/mpv/deband.glsl`

In input.conf I have set:
```
y vo_cmdline "scale=ewa_lanczossharp:scale-antiring=0.5:cscale=ewa_lanczossharp:cscale-antiring=0.5:dscale=mitchell:dscale-antiring=0.5:dither=ordered:dither-depth=auto:sigmoid-upscaling:sigmoid-center=0.80:sigmoid-slope=8.0:scaler-resizes-only:fancy-downscaling:pbo:fbo-format=rgba32f" ; show_text "Interpolation OFF"
u vo_cmdline "scale=ewa_lanczossharp:scale-antiring=0.5:cscale=ewa_lanczossharp:cscale-antiring=0.5:dscale=mitchell:dscale-antiring=0.5:dither=ordered:dither-depth=auto:sigmoid-upscaling:sigmoid-center=0.80:sigmoid-slope=8.0:scaler-resizes-only:fancy-downscaling:pbo:fbo-format=rgba32f:source-shader=/home/entheogen/.config/mpv/deband.glsl:interpolation:tscale=mitchell:tscale-antiring=0.5" ; show_text "Interpolation ON"
```

When I press `u` while watching a video, sometimes what happens in the attached picture occurs. 
If I press `y` the errors go away. If I remove the `source-shader` option from both configs, there are no errors. What can be done to solve this? Can I set an absolute path or something?

Relevant information:
OS: Ubuntu 14.04 LTS 64bit
Graphics Card/Driver: NVIDIA 670M/proprietary 331.113
mpv version: 
```
mpv git-f72028d (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-06-09T04:39:21
ffmpeg library versions:
   libavutil       54.27.100
   libavcodec      56.41.101
   libavformat     56.34.100
   libswscale      3.1.101
   libavfilter     5.16.101
   libswresample   1.2.100

```

Thanks in advance.

![2015-06-09-145320_1879x1056_scrot](https://cloud.githubusercontent.com/assets/11379351/8068340/49d0f142-0ec1-11e5-81b6-fa689d8bcc94.png)

**Comment by wm4** [comment]
Yeah, this looks reasonably serious. Probably dangling pointer.
