### ISSUE TITLE
Slow startup with embedded font

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#2038]
mpv takes a long time (~4s on my system) to start up when loading [this particular file](https://0x0.st/Vl.mkv). The file contains an embedded font (which is 5mb large) and a subtitle track using it.
Most of the time is spent on `[libass] Setting up fonts... ` which may indicate that this is not an mpv bug, though.

**Comment by wm4** [comment]
Starting mpv and playing the file takes "only" 2.5s on my old core duo 2.

The blame of course goes to fontconfig, but maybe it's even slower than necessary on your system.

**Comment by occivink** [comment]
I noticed this discussion concerning fontconfig
https://bugs.freedesktop.org/show_bug.cgi?id=64766
is the calculation of the glyph coverage the culprit in this case?
