### ISSUE TITLE
mpv coredumps when I do `mpv -vo drm --profile=pseudo-gui`

### ISSUE THREAD

**Issue by diegoviola** [mpv-player/mpv#2040]
When I do `mpv -vo drm --profile=pseudo-gui` on a TTY and I switch the tty back and forth, I get a segfault.

I'm not sure if the pseudo-gui should even work in this case?

Here's the coredumpctl output:

```
           PID: 3545 (mpv)
           UID: 1000 (diego)
           GID: 1000 (diego)
        Signal: 11 (SEGV)
     Timestamp: Thu 2015-06-11 21:01:51 BRT (2min 17s ago)
  Command Line: mpv -vo drm --profile=pseudo-gui
    Executable: /usr/bin/mpv
 Control Group: /user.slice/user-1000.slice/session-c4.scope
          Unit: session-c4.scope
         Slice: user-1000.slice
       Session: c4
     Owner UID: 1000 (diego)
       Boot ID: 18c584b8ea0243baa0e5d646cd4ac414
    Machine ID: d166c83c00674edca3c65a03df114fd3
      Hostname: myhost
      Coredump: /var/lib/systemd/coredump/core.mpv.1000.18c584b8ea0243baa0e5d646cd4ac414.3545.1434067311000000.lz4
       Message: Process 3545 (mpv) of user 1000 dumped core.
```

**Comment by wm4** [comment]
I bet the same happens when playing a video manually, and I bet this is not really mpv's fault, and I bet there is no solution to this issue.

Also, the text you pasted from systemd contains almost no useful information at all (other than it was mpv and that it was SIGSEGV). A backtrace would be more useful.

**Comment by rr-** [comment]
Should be fixed as of 8d6c22def46df77eccfd6fe61550aa59beeff28c

**Comment by diegoviola** [comment]
@rr-: Thanks. I'll try this out later today.

**Comment by diegoviola** [comment]
@rr- Thanks, I'll try this out later today.

**Comment by rr-** [comment]
What's up? :camel:

**Comment by rr-** [comment]
@diegoviola ping :crocodile:

**Comment by diegoviola** [comment]
I only get a black screen now, it doesn't segfault/coredump anymore.

**Comment by wm4** [comment]
Well, if it doesn't segfault, it's fixed, right? Closing.
