### ISSUE TITLE
[Windows] AppData\Roaming\mpv Folder Shouldn't Be Created if root\mpv Exists

### ISSUE THREAD

**Issue by Awakened0** [mpv-player/mpv#2042]
This would make mpv more portable when using the settings folder in the same folder as the exe, since it currently leaves an empty folder in Roaming whenever it's run.

**Comment by wm4** [comment]
This is not really possible, so I added something else. See linked commit above.

**Comment by Awakened0** [comment]
That sounds like it will work well. Thanks!
