### ISSUE TITLE
OpenGL not detected on OS X El Capitan

### ISSUE THREAD

**Issue by kraffslol** [mpv-player/mpv#2044]
Installing MPV with homebrew on El Capitan builds without any video outputs. After looking into it, it seems the problem is with the wscript. Specifically the `check_cocoa` function in waftools/checks/custom.py. I tried to compile the cocoa.m fragment manually using cc but to no avail. 

Seems to return an error related to the Foundation framework? I tried bypassing the check_cocoa function but about the same errors return in macosx_compat.h when trying to compile MPV.

https://developer.apple.com/library/prerelease/mac/releasenotes/MacOSX/WhatsNewInOSX/Articles/MacOSX10_11.html might be something to look into. It mentions changes to ObjC.

**Comment by selsta** [comment]
mpv compiles fine for me on 10.11 using homebrew. Did you install the XCode 7.0 beta? Also, posting the exact error you are getting would be helpful.

**Comment by kraffslol** [comment]
Using XCode 6 at the moment. I'll try Xcode 7 and see how it goes.

**Comment by kraffslol** [comment]
@selsta Followed your suggestion using Xcode 7 beta command line tools and now it seems to have compiled just fine using Homebrew. Video playback took ages to play under the first run and the application bundle segfaults at startup. Everything seems to work just fine if you run it from the terminal though.

**Comment by pigoz** [comment]
If you post a backtrace of the bundle usage, maybe we can look into it

**Comment by kraffslol** [comment]
@pigoz I don't know what to say. I tried the bundle again just now to give you the backtrace and it launches just fine. No segfaults yet. I haven't changed a thing as far as I know.

**Comment by pigoz** [comment]
@kraffslol are you running mpv git head? we had some synchronization problems in the past and I'm not sure all the fixes are in the stable release (0.9.x) yet.

**Comment by kraffslol** [comment]
Running 0.9.2 from the Brew formula at the moment. I'll try the git head too.

**Comment by kraffslol** [comment]
Git head works without issues too.

**Comment by Hazer** [comment]
Just for future reference.
I had the same issue. I got it working again after calling:

    brew cleanup

After using it, I never run into problems again.
