### ISSUE TITLE
A/B looping fails if the B point is too near the end of the file

### ISSUE THREAD

**Issue by rcombs** [mpv-player/mpv#2046]
This is spoiling my plans to support looping BFSTM files. Looks like we don't get a TICK event just at the end of the file, and if I try to use the end event instead, the file's already closing by the time the seek gets queued.

**Comment by wm4** [comment]
Are you sure this is what happens? It could be that your B point is simply outside of the file. (On the other hand, B being outside of the file could still be changed to mean looping.)

Try this branch: https://github.com/mpv-player/mpv/compare/terminate_seek

**Comment by wm4** [comment]
>It could be that your B point is simply outside of the file.

And this could apply in particular if your B point is a length, not the timestamp of the last frame. Probably.

**Comment by rcombs** [comment]
In this case, the B point is the file's duration, which will indeed be the last frame's timestamp plus its duration, not <= the last frame's timestamp. So what I want is probably for B existing, but being past the file's last timestamp, to mean looping on end.
I tried applying that patch, and also this:
```
diff --git a/player/command.c b/player/command.c
index 438879c..e187982 100644
--- a/player/command.c
+++ b/player/command.c
@@ -4910,7 +4910,7 @@ static void command_event(struct MPContext *mpctx, int event, void *arg)
         ctx->marked_pts = MP_NOPTS_VALUE;
     }
 
-    if (event == MPV_EVENT_TICK) {
+    if (event == MPV_EVENT_TICK || event == MPV_EVENT_END_FILE) {
         double now =
             mpctx->restart_complete ? mpctx->playback_pts : MP_NOPTS_VALUE;
         if (now != MP_NOPTS_VALUE && opts->ab_loop[0] != MP_NOPTS_VALUE &&
@@ -4918,7 +4918,7 @@ static void command_event(struct MPContext *mpctx, int event, void *arg)
         {
             if (ctx->prev_pts >= opts->ab_loop[0] &&
                 ctx->prev_pts < opts->ab_loop[1] &&
-                now >= opts->ab_loop[1])
+                (now >= opts->ab_loop[1] || event == MPV_EVENT_END_FILE))
             {
                 mark_seek(mpctx);
                 queue_seek(mpctx, MPSEEK_ABSOLUTE, opts->ab_loop[0],
```
And if I attach a debugger I see the `queue_seek` branch run, but I guess by the time `MPV_EVENT_END_FILE` is fired it's too late for that. Not sure where a better place for this would be.

**Comment by wm4** [comment]
Yes, too late. EOF handling is in handle_segment_switch. It sets the stop_play variable, which later in run_playloop and the central playback loop is used to determine whether it should exit. I can take a closer look tomorrow.
