### ISSUE TITLE
No sound with mpv but sound with mplayer

### ISSUE THREAD

**Issue by cyberviking** [mpv-player/mpv#2047]
here is MPV output 

Playing: Kaamelott Livre II - Tome II-FcE_tUrzPyQ.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=fre (*) (aac)
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 624x352 yuv420p
AV: 00:00:09 / 03:07:12 (0%) A-V:  0.000

Here is mplayer output

Detected file format: QuickTime / MOV (libavformat)
[lavf] stream 0: video (h264), -vid 0
[lavf] stream 1: audio (aac), -aid 0, -alang fre
Clip info:
 major_brand: mp42
 minor_version: 0
 compatible_brands: isommp42
 creation_time: 2015-04-25 14:04:09
Load subtitles in .
Failed to open VDPAU backend libvdpau_i965.so: cannot open shared object file: No such file or directory
[vdpau] Error when calling vdp_device_create_x11: 1
[ass] auto-open
Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [libavcodec]
Selected audio codec: AAC (Advanced Audio Coding) [libavcodec]
AUDIO: 44100 Hz, 2 ch, floatle, 96.0 kbit/3.40% (ratio: 12000->352800)
AO: [pulse] 44100Hz 2ch floatle (4 bytes per sample)
Starting playback...
VIDEO:  624x352  25.000 fps  369.9 kbps (46.2 kB/s)
VO: [xv] 624x352 => 624x352 Planar YV12 
A:   1.9 V:   1.9 A-V:  0.000 ct:  0.000   0/  0  0%  0%  0.3% 0 0

**Comment by lachs0r** [comment]
Is mpv muted via PulseAudio controls?

**Comment by wm4** [comment]
So, was that the reason?

**Comment by wm4** [comment]
So, was that the reason?
