### ISSUE TITLE
warnings when going fullscreen in OS X 10.11

### ISSUE THREAD

**Issue by nutinshell** [mpv-player/mpv#2048]
```
mpv git-82ff32f (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-06-16T11:17:16
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100
```

```
Playing: /Users/Jacks/Downloads/717_hd.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
AO: [coreaudio] 44100Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const: conn 0x1f6ff legacy 1
Jun 16 19:27:35  mpv[38521] <Warning>: Backtrace (at 173520):
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  0   CoreGraphics                        0x00007fff929a0dc7 CGSDisableUpdate + 199
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  1   AppKit                              0x00007fff94fc3d08 NSDisableScreenUpdates + 80
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  2   mpv                                 0x0000000101bdd292 vo_cocoa_fullscreen + 66
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  3   mpv                                 0x0000000101bdccac __vo_cocoa_config_window_block_invoke + 1228
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  4   libdispatch.dylib                   0x00007fff87976383 _dispatch_client_callout + 8
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  5   libdispatch.dylib                   0x00007fff87989506 _dispatch_barrier_sync_f_slow_invoke + 523
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  6   libdispatch.dylib                   0x00007fff87976383 _dispatch_client_callout + 8
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  7   libdispatch.dylib                   0x00007fff879878e3 _dispatch_main_queue_callback_4CF + 1677
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  8   CoreFoundation                      0x00007fff961ca6c9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  9   CoreFoundation                      0x00007fff961865a4 __CFRunLoopRun + 1908
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  10  CoreFoundation                      0x00007fff96185bc8 CFRunLoopRunSpecific + 296
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  11  HIToolbox                           0x00007fff94b02b4d RunCurrentEventLoopInMode + 235
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  12  HIToolbox                           0x00007fff94b028df ReceiveNextEventCommon + 432
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  13  HIToolbox                           0x00007fff94b02717 _BlockUntilNextEventMatchingListInModeWithFilter + 71
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  14  AppKit                              0x00007fff94e58972 _DPSNextEvent + 927
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  15  AppKit                              0x00007fff9523a234 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 324
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  16  AppKit                              0x00007fff94e4e297 -[NSApplication run] + 682
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  17  mpv                                 0x0000000101bf9f34 cocoa_main + 836
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  18  libdyld.dylib                       0x00007fff8a1bc5ad start + 1
Jun 16 19:27:35  mpv[38521] <Warning>: void CGSUpdateManager::log() const:  19  ???                                 0x0000000000000002 0x0 + 2
```

**Comment by pigoz** [comment]
Looks like a Window Server bug. I guess Apple will fix it in later developer betas.

**Comment by selsta** [comment]
I’ve been using mpv since 10.11 came out and have had no crashes yet. (Both bundle and command line)

**Comment by kraffslol** [comment]
I think I may have had the same warning messages. Just let it do it's thing for 2 minutes or so, then it should work. That's how I got it working atleast.

**Comment by pigoz** [comment]
> I’ve been using mpv since 10.11 came out and have had no crashes yet.

It's not a crash just overly verbose libraries printing warnings (probably because it's a developer's beta they compiled library code with additional log levels)

**Comment by selsta** [comment]
Sorry, the bug report title got me confused.

**Comment by pigoz** [comment]
Yeah, I fell for it too earlier. Renamed the issue.

**Comment by nutinshell** [comment]
It's not just warning messages, no playback and just a black screen, no sound no video for any media file. May be EI Capitan's bug :(

**Comment by selsta** [comment]
Use the command line tools from the XCode 7 beta and recompile mpv.

**Comment by nutinshell** [comment]
It's Xcode 7 beta compiled.

```
gcc -v
Configured with: --prefix=/Applications/Xcode-beta.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.53)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

**Comment by kraffslol** [comment]
Did you wait a few minutes at the black screen? That's what I did. Otherwise you could try recompiling ffmpeg and try again.

**Comment by Kovensky** [comment]
It's been several developer betas and this hang still happens; it also happens regardless of whether you try to fullscreen or not.

The stack trace leads to the vo_cocoa_fullscreen call inside `vo_cocoa_config_window`:

```c
        if (!s->embedded && s->window) {
            if (reset_size)
                queue_new_video_size(vo, width, height);
            vo_cocoa_fullscreen(vo);
```
This then leads to a call to `NSDisableScreenUpdates` 66 bytes into `vo_cocoa_fullscreen`, which made little sense until I realized it had inlined the call to `draw_changes_after_next_frame`.

I am not sure if the freeze happens _during_ the execution of `NSDisableScreenUpdates` or if the window manager is complained that it's been stuck on a `NSDisableScreenUpdates` that was never popped by `NSEnableScreenUpdates`, 

The only call to `NSEnableScreenUpdates` happens inside `vo_cocoa_swap_buffers`. It's possible that it's never getting called because the lack of screen updates made the VO loop stop. Alternatively, the window manager is freezing when trying to disable them, or something else is preventing the call to `NSEnableScreenUpdates`.

It's worth noting that the [only documentation I've found](https://github.com/jspiros/WindowBlur/blob/master/CGSInternal/CGSConnection.h) on `CGSDisableUpdate` (called inside `NSDisableScreenUpdates`) says that it's automatically forced to be enabled after 1 second elapses, but something is still misbehaving here. It's possible that Apple broke the forced re-enabling, and the previously working forced re-enabling was concealing a bug all along. I just don't know what it is, and can't really debug much for now.

**Comment by pigoz** [comment]
@Kovensky it would be helpful to create a simple application and see if `CGSDisableUpdate` works correctly (or maybe the api was broken by Apple). I think our usage of it is correct (we use it to avoid showing a broken window for 1 frame when going FS).

**Comment by Kovensky** [comment]
@pigoz FWIW, turning `draw_changes_after_next_frame` into a NOOP (just putting a `return;`) on top does fix the freezing. 

I also see no "broken frames" when rapidly toggling fullscreen, though there is a big white flash (fullscreen white background) right when entering fullscreen. I suppose that's the thing you want to avoid?

Not sure how I'd test if `CGSDisableUpdate`'s behavior is correct or broken.

**Comment by pigoz** [comment]
@Kovensky yes that's the thing we want to avoid. On older OSX versions you can also see through the window for one frame... which is super annoying.

**Comment by pigoz** [comment]
update: I made a test patch with disableScreenUpdatesUntilFlush but the white flash is still there.

```
diff --git a/video/out/cocoa_common.m b/video/out/cocoa_common.m
index f16f7ae..d2a16b8 100644
--- a/video/out/cocoa_common.m
+++ b/video/out/cocoa_common.m
@@ -72,8 +72,6 @@ struct vo_cocoa_state {
 
     bool embedded; // wether we are embedding in another GUI
 
-    atomic_bool waiting_frame;
-
     IOPMAssertionID power_mgmt_assertion;
     io_connect_t light_sensor;
     uint64_t last_lmuvalue;
@@ -647,13 +645,6 @@ static void vo_cocoa_resize_redraw(struct vo *vo, int width, int height)
     pthread_mutex_unlock(&s->lock);
 }
 
-static void draw_changes_after_next_frame(struct vo *vo)
-{
-    struct vo_cocoa_state *s = vo->cocoa;
-    if (atomic_compare_exchange_strong(&s->waiting_frame, &(bool){false}, true))
-        NSDisableScreenUpdates();
-}
-
 void vo_cocoa_swap_buffers(struct vo *vo)
 {
     struct vo_cocoa_state *s = vo->cocoa;
@@ -672,9 +663,6 @@ void vo_cocoa_swap_buffers(struct vo *vo)
     s->frame_h = vo->dheight;
     pthread_cond_signal(&s->wakeup);
     pthread_mutex_unlock(&s->lock);
-
-    if (atomic_compare_exchange_strong(&s->waiting_frame, &(bool){true}, false))
-        NSEnableScreenUpdates();
 }
 
 static int vo_cocoa_check_events(struct vo *vo)
@@ -703,10 +691,12 @@ static int vo_cocoa_fullscreen(struct vo *vo)
 
     vo_cocoa_update_screen_info(vo, NULL);
 
-    draw_changes_after_next_frame(vo);
     [(MpvEventsView *)s->view setFullScreen:opts->fullscreen];
 
     if ([s->view window] != s->window) {
+        [s->view setNeedsDisplay:YES];
+        // prevents the fullscreen window to show an uninitialized backing store
+        [[s->view window] disableScreenUpdatesUntilFlush];
         // cocoa implements fullscreen views by moving the view to a fullscreen
         // window. Set that window delegate to the cocoa adapter to trigger
         // calls to -windowDidResignKey: and -windowDidBecomeKey:
@@ -819,9 +809,7 @@ int vo_cocoa_control(struct vo *vo, int *events, int request, void *arg)
 @synthesize vout = _video_output;
 
 - (void)performAsyncResize:(NSSize)size {
-    struct vo_cocoa_state *s = self.vout->cocoa;
-    if (!atomic_load(&s->waiting_frame))
-        vo_cocoa_resize_redraw(self.vout, size.width, size.height);
+    vo_cocoa_resize_redraw(self.vout, size.width, size.height);
 }
 
 - (BOOL)keyboardEnabled {

**Comment by pigoz** [comment]
@Kovensky was your libass using fontconfig? I suspect our main thread is waiting for a NSEnableScreenUpdates to be triggered but the playback thread is just busy rebuilding the font cache. Could you try again with libass from git?

**Comment by torque** [comment]
For what it's worth, I just started getting this message on 10.10.5 after installing [XQuartz 2.7.8 RC1](http://xquartz.macosforge.org/trac/wiki/X112.7.8). I'm not positive that's what's causing it, but I'm fairly sure, because it's the only thing of interest I've changed on my computer recently. I wonder if El Capitan is shipping with the newer version of XQuartz. As for _why_ it would be causing this, I'm clueless.

**Comment by pigoz** [comment]
@torque Are you using libass master with no fontconfig?

**Comment by torque** [comment]
I wasn't when I made the first comment. I agree with your diagnosis that this is due to fontconfig stalling the playback thread, since the message stopped appearing once the fontconfig cache had been generated, and I haven't seen it reappear since updating to CoreText libass.

I find it curious that nobody else had reported seeing this in 10.10.

**Comment by pigoz** [comment]
Well now that coretext is used, this no longer an issue.
