### ISSUE TITLE
About file icon on OS X

### ISSUE THREAD

**Issue by hkenneth** [mpv-player/mpv#2050]
I know it is purely personal taste but I wonder if it is possible to provide a file type icon with plain white background?

**Comment by pigoz** [comment]
If someone works on the icons. We have custom icons because an awesome guy designed them for sue (we are not designers).

**Comment by wm4** [comment]
What's the state of this issue, or what is it even about?

**Comment by pigoz** [comment]
User wanted different icons.

**Comment by hkenneth** [comment]
I have created a new file type icon with white background.

https://drive.google.com/open?id=0BxjG-Ea9-dhtd3dJRm8tVkRJWGs
