### ISSUE TITLE
gtk-youtube-viewer + MPV on Powerbook G4

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#2055]
Hello,

i would like to use mpv player on my powerbook G4 with gtk-youtube-viewer.

How can i install MPV player on Osx Leopard? Will it work good as on Linux?

Thank you very much.

Richard

**Comment by ChrisK2** [comment]
It won't work at all since mpv requires at least Mac OS X 10.7.

**Comment by mrkapqa** [comment]
And with home brew? 


Von Samsung Mobile gesendet

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: ChrisK2 <notifications@github.com> </div><div>Datum:18.06.2015  09:38  (GMT+01:00) </div><div>An: mpv-player/mpv <mpv@noreply.github.com> </div><div>Cc: mrkapqa <csae2608@uibk.ac.at> </div><div>Betreff: Re: [mpv] gtk-youtube-viewer + MPV on Powerbook G4 (#2055) </div><div>
</div>It won't work at all since mpv requires at least Mac OS X 10.7.

**Comment by ChrisK2** [comment]
No. That makes no difference.

**Comment by mrkapqa** [comment]
where lies the problem? i thought i can use homebrew to install 
linux/unix apps on macintosh. why should i not be able to do so?

what is homebrew for then?

ChrisK2 wrote:

**Comment by ChrisK2** [comment]
homebrew is kist a package manager, nothing more. Not some magical thing that makes Linux applications run on OS X. It's up to each application to support OS X, an our support requires at least 10.7.

**Comment by mrkapqa** [comment]
i am going to install tigerbrew and then let you know.


with homebrew and osx 10.7+, is it possible to install mpv and  
gtk-youtube-viewer?


thanks

Zitat von ChrisK2 <notifications@github.com>:

**Comment by pigoz** [comment]
@mrkapqa the native cocoa/opengl integration will not work. mpv uses cocoa features available only on 10.7 and beyond.

You can try building with X11 support (and XQuartz), or SDL (though IIRC we don't have SDL<->OpenGL integration).

**Comment by mrkapqa** [comment]
thank you stefano; would i be able to use mplayer (graphical Version)  
instead or vlc (a bit energy-consuming on powerbook, though)?

gtk-youtube-viewer should be accessible with tigerbrew?

https://code.google.com/p/trizen/


thanks




Zitat von Stefano Pigozzi <notifications@github.com>:

**Comment by wm4** [comment]
mpv won't really work well on such old powerpc hardware if you want to decode high bitrate video.

GTK is going to be ugly on OSX.

**Comment by wm4** [comment]
Also, everything was answered.

**Comment by mrkapqa** [comment]
sorry i have an eeepc and on Linux it works very well; the powerbook  
is faster than the Intel Atom processor, thereofore i asked.


Zitat von "V. Lang" <notifications@github.com>:

**Comment by pigoz** [comment]
@mrkapqa I advise to try mpv with opengl/x11 or xv video output. If I were you though, I'd install Linux on the Powerbook.

**Comment by mrkapqa** [comment]
ciao stefano i do have linux mint ppc installed but unfortunately it is wheezy so it is a bit too much not so stable and fast maybe i install once again the debian squeeze- linux mint ppc edition and try from there . but i had problems compiliing gtk-youtube-viewer on squeeze because it come only with perl 5.10. 
other option would be lubuntu but i dont know if this works well on pwerbook. do you have any experience with linux on powerbook?
magari conosci giá quest iniziativa
http://www.powerpc-notebook.org/en/

**Comment by mrkapqa** [comment]
i tested youtube-viewer on linux with differnt options: mplayer - vlc - mpv and it seemed that mpv is most stable and fast.
