### ISSUE TITLE
MPV Youtube Streaming Error

### ISSUE THREAD

**Issue by lubuntulux** [mpv-player/mpv#2058]
I am running mpv 0.9.2 (vapoursynth enabled) from this ppa: https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth
youtube-dl via deb (youtube-dl_2015.06.04.1-1_all.deb) :https://packages.debian.org/sid/all/youtube-dl/download

When I try to stream a Youtube video  with mpv, both with or without my vapoursynth script for 60FPS interpolation, I get an error.

When I try to play something like this however, it works fine, both with and without the vapoursynth script: http://wpage.unina.it/aorefice/sharevari/tearingandsmoothness.mp4

Here the errors that exclusively occur with youtube links:
jackson@jackson:~$ mpv --vf=vapoursynth=/home/jackson/Downloads60fps.py --hwdec=no https://www.youtube.com/watch?v=Z_mf9aCHag8
Playing: https://www.youtube.com/watch?v=Z_mf9aCHag8
[ffmpeg] ?: https protocol not found, recompile with openssl or gnutls enabled.
[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
Failed to open https//r1---sn-4g57knes.googlevideo.com/videoplayback?lmt=1434341533454883&key=yt5&dur=185.411&fexp=936117%2C9407136%2C9407141%2C9407992%2C9408142%2C9408420%2C9408710%2C9409206%2C9412770%2C9412773%2C9412985%2C9413503%2C9415304%2C9415397%2C9415560%2C9416126%2C9416283%2C952626&initcwndbps=2165000&ipbits=0&mime=video%2Fmp4&nh=IgpwcjAyLmZyYTAzKgkxMjcuMC4wLjE&requiressl=yes&source=youtube&signature=627ADFD5F329FB6ADF25025F029C001A5108947A.7991EF1641E00A9A4112C6E57D0030D5AC3C02E3&hcs=yes&upn=XEsijOCEiQc&itag=22&mt=1434642035&pl=20&mv=m&ms=au&mm=31&expire=1434663769&id=o-ACkvgXZLOw6hTXU6kl1XBpKsgJeKTCoQRzwvKtVoR1tJ&ratebypass=yes&sver=3&ip=84.113.177.182&mn=sn-4g57knes&sparams=dur%2Chcs%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Cshardbypass%2Csource%2Cupn%2Cexpire&shardbypass=yes.
Exiting... (Errors when loading file)

The same happens when I don't use the vapoursynth script, hence the problem must be elsewhere:
jackson@jackson:~$ mpv https://www.youtube.com/watch?v=Z_mf9aCHag8 
Playing: https://www.youtube.com/watch?v=Z_mf9aCHag8
[ffmpeg] ?: https protocol not found, recompile with openssl or gnutls enabled.
[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
Failed to open https//r1---sn-4g57knes.googlevideo.com/videoplayback?requiressl=yes&dur=185.411&id=o-AHTuyjkfh2iy6OAy91OjLgroMvvr9BEdDjYZYwafotYn&mn=sn-4g57knes&pl=20&mm=31&source=youtube&fexp=9406128%2C9407141%2C9407535%2C9407663%2C9408142%2C9408420%2C9408710%2C9409095%2C9413503%2C9414806%2C9414916%2C9414936%2C9415304%2C9415810%2C9415972%2C9416126%2C9416573%2C952626%2C952640&ms=au&mv=m&mt=1434642151&hcs=yes&shardbypass=yes&upn=N1FSBRoSffE&itag=22&key=yt5&mime=video%2Fmp4&ip=84.113.177.182&nh=IgpwcjAyLmZyYTAzKgkxMjcuMC4wLjE&sver=3&lmt=1434341533454883&initcwndbps=2150000&sparams=dur%2Chcs%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Cshardbypass%2Csource%2Cupn%2Cexpire&signature=B93CB6FE8DDC55ABE4049B593AFAB1172D26D32F.AFE99161949293A67F7EB4856A81A0483229489F&ratebypass=yes&expire=1434663821&ipbits=0.
Exiting... (Errors when loading file)

**Comment by torque** [comment]
To quote myself from your previous issue:

>>[ffmpeg] ?: https protocol not found, recompile with openssl or gnutls enabled.

>It would behoove you to actually read the output instead of blindly flailing around.

**Comment by wm4** [comment]
Report it to the packager.

**Comment by lubuntulux** [comment]
I did, and conducted some research accordingly.

in 2014 the answer was, that it wasn't a problem caused by mpv.
"oth FFmpeg and libquvi use some SSL library. And both GnuTLS and OpenSSL have global state, which results in the error message you’re seeing. The only way around this seems to be linking libquvi with GnuTLS and FFmpeg with OpenSSL.
The other problem is that nobody seems to contribute to libquvi anymore, so the scripts are outdated and do not work that well anymore."
https://github.com/mpv-player/mpv/issues/1046

However, apart from the script for youtube-dl, no successful solutions had been offered.

**Comment by Argon-** [comment]
This is no longer a problem as libquvi doesn't exist anymore.
Your ffmpeg simply lacks any of these libraries.

**Comment by lubuntulux** [comment]
How could this be?
I downloaded ffmpeg from mc3man's ppa: https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media
All necessary packages should already be included.

**Comment by torque** [comment]
As has been mentioned, mpv stopped using libquvi a long time ago. Also, your error message is completely different from the one in the issue you linked, indicating to me that you still aren't actually reading error messages.

At this point, it should become obvious to you  that the copy of ffmpeg that mpv is using is not linked against an ssl library. If the one in the ppa is the only copy of ffmpeg you have installed, then ffmpeg from that ppa is not linked against any ssl libraries, and you need to find a different source. Do not make assumptions about what is linked against what, if you haven't actually checked. Because of license incompatibility, ffmpeg linked against openssl is non-redistributable, which means if you're going to install a binary blob, you need to find one linked against gnutls. This is absolutely not an mpv issue, and this conversation does not belong here. This is something that should be discussed with other people who use your operating system, because the solution is platform-specific.

**Comment by mc4man** [comment]
Mpv is sometimes built off of shared libav or fmpeg or a static version. In the case of the mpv you have been & currently are using it's built statically linked to ffmpeg. So it has no relationship to any  ffpmeg packages you have installed. (ie. it doesn't use
If you want https support then as mentioned contact djcj thru launchpad email or build mpv yourself.
