### ISSUE TITLE
Top 30ish pixels are semi-transparent regardless of settings.

### ISSUE THREAD

**Issue by rcurry95** [mpv-player/mpv#2059]
I'm using mpv 0.9.2 on Gentoo with all the latest x64 updates. Nothing in the output or anything seems to be wrong persay, but it is rather annoying and I'm not exactly sure what the deal is. You can see in the image that one can see the CPU monitor behind the video at the top left. Of course the transparency goes all the way across the window. It scales to the size of the window. I've tried with --noconfig and all of the -vo settings.
![2015-06-18-163638_1366x768_scrot](https://cloud.githubusercontent.com/assets/12957787/8241610/65f8fa36-15d8-11e5-839a-db73307a27c8.png)

**Comment by z0z0z** [comment]
What WM and compositor (if you're using one)?

**Comment by wm4** [comment]
What should the screenshot look like at all?

**Comment by kevmitch** [comment]
> What should the screenshot look like at all?

I think the problem is the weird hexagonal pattern directly below the title bar through which you can see the cpu monitor presumably on the desktop.

**Comment by rcurry95** [comment]
> What WM and compositor (if you're using one)?

i3 and compton.



> What should the screenshot look like at all?

Not semi-transparent at the top of the video.



> I think the problem is the weird hexagonal pattern directly below the title bar through which you can see the cpu monitor presumably on the desktop.

Indeed. The hexagonal pattern is actually just the wallpaper, but you hit the nail on the head.

**Comment by wm4** [comment]
No idea what that could be. I'm pretty sure we clear the background with opaque black, so even if we get a window with alpha pixel format, it shouldn't be transparent.

You could try ``--panscan=1``.

**Comment by rcurry95** [comment]
Nothing... I didn't think this was a usual issue since I found nothing on the webz about it. Guess I will just wait until the next update to see if that changes anything. This is what it looks like with panscan:
![2015-06-20-094341_1366x768_scrot](https://cloud.githubusercontent.com/assets/12957787/8267466/3f276f64-1731-11e5-9b7d-65f1bbf0f90d.png)

**Comment by wm4** [comment]
At this point I'd blame the compositor.

**Comment by rcurry95** [comment]
Why? It doesn't do it with any other media player... Including mplayer.

**Comment by wm4** [comment]
Try ``--vo=xv``.

**Comment by rcurry95** [comment]
No dice. It does go away when I turn off compton. I'll just deal with it because I'm not going to stop using compton.

**Comment by wm4** [comment]
Report it to compton. I'm pretty sure this is not our fault, because Xv and X11 as a whole don't even have a concept of transparency.

**Comment by HirschBerge** [comment]
For people experiencing this issue and seeing this, try changing your frame opacity. frame-opacity = 1; did the trick for me
