### ISSUE TITLE
no terminal output on osx

### ISSUE THREAD

**Issue by troex** [mpv-player/mpv#2061]
If I run mpv on osx (using `/Applications/mpv.app/Contents/MacOS/mpv`) from terminal it works but I don't have any output in terminal, even if I type `--help` or `--list-options` - nothing.

If I add `terminal=yes` to config it shows up everything (before 0.90 it didn't have this problem).

I guess it's because of `pseudo-gui` profile which mutes terminal output, but still I think it should respond in terminal to core commands. And it doesn't work correctly selecing pseudo-gui when execured without mpv.app

(I'm using latest Chris build from http://sva.wakku.to/~chris/mpv_builds/mpv_latest.zip)

**Comment by wm4** [comment]
In my opinion, it shouldn't pick up the bundle config file (which enables pseudo-gui mode) when started like this. It should only happen when being started from GUI. But I don't know enough about Cocoa etc. if this is possible. Possibly we just need another mechanism to enable pseudo-gui.

@pigoz: any ideas?

**Comment by pigoz** [comment]
Considering on newer versions of OSX the finder doesn't use a psn to start the application it could be not trivial to figure out who started the application. At the moment we use `[[NSBundle mainBundle] resourcePath]` which doesn't care where the application was started from (Finder or shell).

**Comment by troex** [comment]
Shouldn't mpv.app explicitly pass `--profile=pseudo-gui` to the bin while when executed?

Maybe another approach is to set env variable like MPV_PROFILE – but these are just ideas, it's not critical anyway, I just spent some time to get the output

**Comment by wm4** [comment]
>Shouldn't mpv.app explicitly pass --profile=pseudo-gui to the bin while when executed?

How?

**Comment by lucianmarin** [comment]
The manual says you should use --no-config when testing. Using this mpv displays the terminal output.

A mpv.conf is bundled within mpv.app which states `profile=pseudo-gui` (disables terminal output).

**Comment by wm4** [comment]
>A mpv.conf is bundled within mpv.app which states profile=pseudo-gui (disables terminal output).

Yes. That's the bundle-config, which is only loaded when mpv is started from within the bundle. But I expected this to be loaded only if started from the GUI (i.e. Finder).

**Comment by sumyungguy** [comment]
You have `bundle_started_from_finder`, which is false if an argument is given on the command line. That prevents the terminal output from being redirected to the log file. Could you also use that to tell it not to read the bundled mpv.conf file? It's not perfect because it will still happen if mpv is called from the comand line with no arguments, but maybe it's an improvement.

**Comment by wm4** [comment]
>You have bundle_started_from_finder, which is false if an argument is given on the command line. 

I think this is unreliable.

The best way to solve this might be creating a separate wrapper binary, which is used with the bundle only.
