### ISSUE TITLE
Video disappears when going full screen on 1080p external display

### ISSUE THREAD

**Issue by wzxu** [mpv-player/mpv#2062]
As the title suggests. Here's some information I've gathered trying out different combinations.

Going full screen works fine with QuickTime, and also Movist from the App Store. Works with mpv only when I set the external display to 720p. When it's 1080p, mpv window disappears going full screen with audio still playing back. Not working even in Display Mirroring mode. Not showing up in Mission Control either. Pressing F does make it reappear in windowed mode.

HDMI out on a 2015 rMBP with OS X 10.10.3. [Here's a short log](http://pastebin.com/XnnndXV6) (--msg-level=all=trace) starting from I pressed 'F' to enter full screen and quickly 'cmd-q' out of it.

**Comment by wm4** [comment]
I don't know about this. Seems impossible to fix, because it'd require your exact setup to even find out what's wrong.

**Comment by wzxu** [comment]
Yeah, from the looks of it not many other people have this issue...

Oh well. I can do some tests if you've got ideas of possible causes. Otherwise I'll just have to use Movist for playing on the TV for now.

**Comment by mrzzcn** [comment]
@wzxu I got the same problem, could you please tell me how to fix it? Thanks.

**Comment by janl** [comment]
I’m also seeing this and happy to provide debugging info if I can get any pointers no what to do :)

**Comment by Akemi** [comment]
fixed in https://github.com/mpv-player/mpv/commit/a8347eb9ba9e09177da50592fde7f3ae7261ce59
