### ISSUE TITLE
Disabling screensaver failed on Ubuntu Gnome 15.04

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv#2063]
Hello,

I have this message on Ubuntu Gnome 15.04 :

[vo/vdpau/x11] Disabling screensaver failed.

Thank you

**Comment by wm4** [comment]
Install xdg-screensaver.

**Comment by wm4** [comment]
PS: I'm surprised that Gnome or Ubuntu wouldn't have this program installed by default. Maybe you could check whether it is/was actually present? (The other thing this error message could mean that the program returned an error when running.)

**Comment by Paviluf** [comment]
It's already installed with the xdg-utils package
https://launchpad.net/ubuntu/vivid/+package/xdg-utils

**Comment by wm4** [comment]
So I guess the script returns failure. Does it actually succeed in disabling the screensaver, or does it appear during playback?

**Comment by Paviluf** [comment]
I just tried, it's a fresh install, and it succeed in disabling the screensaver.

**Comment by wm4** [comment]
Can you try this on the terminal:
```
xdg-screensaver reset ; echo $?
```
What does it print?

**Comment by Paviluf** [comment]
4

**Comment by wm4** [comment]
The manpage says this means "The action failed.".

The bad part is that even if it works, mpv actually stops calling the script, and the screensaver might kick in again later. So I guess I'll reopen this for now.

**Comment by kevmitch** [comment]
You could try running

    sh -x /usr/bin/xdg-screensaver reset 

to see where it is actually faliling

**Comment by Paviluf** [comment]
$ sh -x /usr/bin/xdg-screensaver reset 
+ check_common_commands reset
+ [ 1 -gt 0 ]
+ parm=reset
+ shift
+ [ 0 -gt 0 ]
+ [ -z  ]
+ unset XDG_UTILS_DEBUG_LEVEL
+ [ 0 -lt 1 ]
+ xdg_redirect_output= > /dev/null 2> /dev/null
+ mv+  -T ...grep \.\.\. ...

+ DEBUG 1 mv -T available
+ [ -z  ]
+ return 0
+ MV=mv -T
+ echo :0
+ sed s/:/-/g
+ screensaver_file=/tmp/xdg-screensaver-jeremy--0
+ which lockfile
+ lockfile_command=
+ which xprop
+ XPROP=/usr/bin/xprop
+ [ xreset != x ]
+ action=
+ window_id=
+ action=reset
+ detectDE
+ [ x = xtrue ]
+ [ xthis-is-deprecated != x ]
+ DE=gnome
+ + grep XScreenSaver
xscreensaver-command -version
+ gnome-screensaver-command -q
+ [ reset = resume ]
+ perform_action reset
+ result=1
+ [ reset = resume ]
+ [ reset = reset ]
+ xset+  -q
grep DPMS is Enabled
+ xset dpms force on
+ [ reset = suspend ]
+ [ reset = suspend ]
+ [ 1 -eq 0 ]
+ exit_failure_operation_failed
+ [ 0 -gt 0 ]
+ exit 4

**Comment by kevmitch** [comment]
looks like ```gnome-screensaver-command -q``` doesn't work, so it detects you DE as just 'gnome' rather than 'gnome_screensaver', but there is no handling for 'gnome' in the peform_action function, which means it's global results variable never gets set to zero for success. 

I'm pretty sure this is a bug in the script. What does 

    gnome-screensaver-command 

return?

**Comment by mc4man** [comment]
I don't use the  Ubuntu Gnome (gnome shell) release  but I don't believe it has gnome-screensaver installed by default anymore. (& possibly it wouldn't use it anyway..?

**Comment by Paviluf** [comment]
This is the output of gnome-screensaver-command :

`Le programme « gnome-screensaver-command » n'est pas encore installé. Vous pouvez l'installer en tapant :
sudo apt-get install gnome-screensaver`

It says that gnome-screensaver-command is not installed.

**Comment by ghprod** [comment]
I have this issue too .. this is my output

```
~$ sh -x /usr/bin/xdg-screensaver reset 
+ check_common_commands reset
+ [ 1 -gt 0 ]
+ parm=reset
+ shift
+ [ 0 -gt 0 ]
+ [ -z  ]
+ unset XDG_UTILS_DEBUG_LEVEL
+ [ 0 -lt 1 ]
+ xdg_redirect_output= > /dev/null 2> /dev/null
+ mv+ grep \.\.\.
 -T ... ...
+ DEBUG 1 mv -T available
+ [ -z  ]
+ return 0
+ MV=mv -T
+ sed s/:/-/g
+ echo :0
+ screensaver_file=/tmp/xdg-screensaver-hesti--0
+ which lockfile
+ lockfile_command=
+ which xprop
+ XPROP=/usr/bin/xprop
+ [ xreset != x ]
+ action=
+ window_id=
+ action=reset
+ detectDE
+ [ x = xtrue ]
+ [ xthis-is-deprecated != x ]
+ DE=gnome
+ grep XScreenSaver
+ xscreensaver-command -version
+ gnome-screensaver-command -q
+ [ reset = resume ]
+ perform_action reset
+ result=1
+ [ reset = resume ]
+ [ reset = reset ]
+ grep DPMS is Enabled
+ xset -q
+ xset dpms force on
+ [ reset = suspend ]
+ [ reset = suspend ]
+ [ 1 -eq 0 ]
+ exit_failure_operation_failed
+ [ 0 -gt 0 ]
+ exit 4

````

Need help :)

**Comment by kevmitch** [comment]
file a bug with ubunutu

**Comment by wm4** [comment]
Closing again. It's really Ubuntu's issue.

**Comment by Paviluf** [comment]
Ok I was just trying Ubuntu Gnome 15.04 and I find that I can't stand Gnome.
I'm back to Netrunner 14.1 for now.
So if anyone else have this problem you can report it to Ubuntu.

**Comment by YamashitaRen** [comment]
Doesn't seem to be an Ubuntu issue, I'm using Archlinux...
$ xdg-screensaver reset ; echo $?
4
I think I have this problem since I installed Cinnamon. I didn't had this error on Xfce or KDE.
There should be an incompatibility between xdg-screensaver and Gnome/Cinnamon or something like that...

**Comment by wm4** [comment]
More importantly, does this actually not prevent a screensaver from showing up during playback?

**Comment by YamashitaRen** [comment]
After one month of "extented" tests, I think that indeed we can say that it prevents the screensaver to show on playback.
