### ISSUE TITLE
OpenGL ES backend for non rasp-pi boards?

### ISSUE THREAD

**Issue by Tux1c** [mpv-player/mpv#2064]
Hi there,

I'm using Gentoo Linux on an Asus Transformer Prime (tf201), which is based off Tegra 3.
mpv obviously doesn't decode videos using hardware as T3 doesn't support OpenGL. I've seen the "raspberry-pi" use flag and tried setting that, but for some odd reason MPV checks if you ACTUALLY run a rasp-pi and refuses to compile when it detects otherwise, are you using some rasp video card specific code? would it be possible to get an OpenGL ES backend without the need of a rasp-pi?

**Comment by wm4** [comment]
OpenGL ES context creation is always platform dependent, even though the EGL API likes to pretend otherwise.

The raspberry pi support is hardcoded to broadcom firmware.

There's some code that should work for generic X11 via ``--vo=opengl:backend=x11egl:es`` (needs to be enabled at compile time with ``--enable-egl-x11``.

All this has nothing to do with hardware decoding. There's no code for interaction of hardware decoding with GLES (I tried on rpi, but it didn't work). I don't even know what hardware decoding APIs desktop Linux on Tegra supports.

**Comment by Tux1c** [comment]
@wm4 oh wow, thanks for the fast reply!

Thank you for clarifying, I've tried using `--vo=opengl:backend=x11egles` (I guess x11egl:es was a typo?) but it fails, I get the following error:
> [vo/opengl] Can't load OpenGL functions.
> Error opening/initializing the selected video_out (-vo) device.  

"Normal" OpenGL works (`--vo=opengl`), but very very slowly. Eh, I guess I can givup video playing on that device :)

**Comment by wm4** [comment]
>"Normal" OpenGL works (--vo=opengl), but very very slowly.

Does it use a software OpenGL implementation? Post glxinfo output too.

**Comment by Tux1c** [comment]
@wm4 
Yup, as I've mentioned before, nvidia doesn't provide any OpenGL implementation with the drivers so I use the mesa ones, or whatever.
>OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.5, 128 bits)

http://pastebin.com/0cw2ExcY

**Comment by wm4** [comment]
And the output of ``es2_info``?

**Comment by Tux1c** [comment]
es and es2 are handled by the nvidia driver
http://pastebin.com/KUiiY7Fj

**Comment by wm4** [comment]
>Thank you for clarifying, I've tried using --vo=opengl:backend=x11egles (I guess x11egl:es was a typo?) but it fails, I get the following error:

Actually no, it was not a typo. Try again, with ``-v -v -v``, and post the output.

**Comment by Tux1c** [comment]
@wm4 
when I looked through mpv's manpages it also listed x11egl and x11egles so I assumed it was a typo.  
Anyway:  
http://pastebin.com/RYJSrJVj

**Comment by wm4** [comment]
Oh right, the release is different. It was changed in git master. Then a log with ``--vo=opengl:backend=x11egles  -v -v -v`` (while trying to play a file) will probably do it.

**Comment by Tux1c** [comment]
http://pastebin.com/EHAQRGKg :)

**Comment by wm4** [comment]
Seems like nvidia's eglGetProcAddress() doesn't return pointers for builtin functions, even though the EGL 1.4 spec seems to say explicitly that it must.

**Comment by Tux1c** [comment]
Aha, so I guess I can kiss video playing with MPV on my tegra goodbye? Well, even though it kinda sucks, thank you so much for your help! I guess we can close this?

**Comment by wm4** [comment]
>Aha, so I guess I can kiss video playing with MPV on my tegra goodbye? 

I don't know yet. Do they provide vdpau?

**Comment by Tux1c** [comment]
hmmm to be honest I don't know, nor I know how to check.  
From a short google search I found this webpage http://elinux.org/Tegra/Downstream_SW/Linux4Tegra/WebBrowsers/Hardware_Accelerated_Video_Decoding which states that:
>Nvidia doesn't provide VDPAU libraries for the Tegra K1

K1 is a much more powerful and newer card than my T3, so I guess they don't? How can I check that?

**Comment by wm4** [comment]
So we would have to support yet another fucking hardware decoding API on Linux. This is ridiculous.

**Comment by Tux1c** [comment]
@wm4 
Eh, I don't think so. The number of Tegra users is very, very small. I know only 2 other people who have Linux on their TF201, and they just installed that for the fun of it. And newer Tegra chips already support OpenGL AFAIK so people might not need another way to decode stuff.

**Comment by wm4** [comment]
Decoding is different from display. I suspect the Tegra chips are too weak to handle decoding of most video on the CPU.

Anyway, if you want, I can push a branch that might make GLES output work? (You'll have to compile it yourself, of course.)

**Comment by Tux1c** [comment]
If that's not too much of an issue for you, then sure thing! I am compiling almost everything anyway :)

**Comment by wm4** [comment]
Look at the branch ``egl_test``.

Make sure the mpv binary is not linked against libGL, or it will crash due to symbol conflicts.

**Comment by Tux1c** [comment]
hmmm seems like we have 1 error less! :)
now instead of:
> [vo/opengl] Can't load OpenGL functions.
> Error opening/initializing the selected video_out (-vo) device. 

I get:
> Error opening/initializing the selected video_out (-vo) device.

Here's the output with -v -v -v (disregard the build number, I manually patched the build Gentoo provides with the commit in the `egl_test` branch):  
http://pastebin.com/vJyB967E
