### ISSUE TITLE
Youtube playback does not work

### ISSUE THREAD

**Issue by matiasw** [mpv-player/mpv#2065]
Youtube URL playback does not work with the current git master. It gives me 
```Failed to recognize file format.
Exiting... (Errors when loading file)```
It works with 0.9.2-1 from the Debian repos.

**Comment by wm4** [comment]
Did you install youtube-dl?

**Comment by matiasw** [comment]
Yes.

**Comment by wm4** [comment]
Does youtube-dl work on it? Can you post mpv output with -v?

**Comment by matiasw** [comment]
Yes, youtube-dl works, and even ytdl_hook works with the mpv from repos mentioned earlier.
Here's the output from git master: http://paste.debian.net/252703/
Output from the repo's mpv: http://paste.debian.net/252704/

**Comment by wm4** [comment]
You've compiled without Lua. Even though mpv Lua support is optional, it is needed for youtube-dl and other things.
