### ISSUE TITLE
how get stop after play video?

### ISSUE THREAD

**Issue by manuelsongokuh** [mpv-player/mpv#2068]
hello

mpv default:
play and quit

i want:
play and stop and not quit..
how?

can does show menu control (interface)?

**Comment by ChrisK2** [comment]
Add ``keep-open=yes``or ``keep-open=always``to ``mpv.conf``, see http://mpv.io/manual/master/#options-keep-open for details.

> can does show menu control (interface)?

wat

**Comment by manuelsongokuh** [comment]
sorry i'm forget to say, i dont want under terminal, like as direct open video..
possible?

for menu control, i mean: more button for details : flip, rotate, mute, but button and not keyboard..

**Comment by kevmitch** [comment]
>sorry i'm forget to say, i dont want under terminal, like as direct open video..
possible?

if you follow ChrisK2's suggestion and add the ``keep-open=yes``` to your ```mpv.conf``` file, then you won't need any special command line options.

>  for menu control, i mean: more button for details : flip, rotate, mute, but button and not keyboard.

There is only the OSC which has commonly used playback controls (play, pause skip, seek, etc), but not any of the functions you mention.

**Comment by manuelsongokuh** [comment]
ok 
thank you..but not work for me:
keep-open=yes  or  keep-open=always  in mpv.conf
...strange....sorry

**Comment by kevmitch** [comment]
what operating system are you using? where are you putting mpv.conf

On Linux, it should be at ```~/.config/mpv/mpv.conf``

**Comment by kevmitch** [comment]
On windows it should be at ```%appdata%/mpv/mpv.conf```

**Comment by manuelsongokuh** [comment]
sorry i'm forget to say what is my OS:
linux, yes i did added code in /home/user/.config/mpv/mpv.config

**Comment by kevmitch** [comment]
it is ```/home/user/.config/mpv/mpv.conf```, not ```/home/user/.config/mpv/mpv.config```

**Comment by manuelsongokuh** [comment]
sorry i'm wrong write here, that is correct:
/home/user/.config/mpv/mpv.conf

not work for me keep-open=yes

**Comment by wm4** [comment]
Closed for incomprehensible language barrier issues.

**Comment by manuelsongokuh** [comment]
why... close...? before ask me for problem "incomprehensible language barrier issues." after will close?
then i repeat :
/home/user/.config/mpv/mpv.conf
i did added : keep-open=yes
it's not work when i open file video...
then what do i will do?

**Comment by roblav96** [comment]
@wm4 There's no need to close this, there's very much useful information here :D

**Comment by manuelsongokuh** [comment]
@roblav96 +1 vote
