### ISSUE TITLE
loop infinite

### ISSUE THREAD

**Issue by manuelsongokuh** [mpv-player/mpv#2069]
hello

i need to set: loop infinite, when i open video..?
but dont want use command under terminal..
i want open video direct and play-loop infinite..
it's possible?

**Comment by ChrisK2** [comment]
Press ``L``.

**Comment by manuelsongokuh** [comment]
not work for me...
i press L , display write: "a-b loop point XXXX"
i want not A-B, but play style cycles loop infinite..

**Comment by kevmitch** [comment]
add to your input.conf 

    l cycle_values loop-file "no" "inf"

**Comment by manuelsongokuh** [comment]
ok but need to keep active ON, because start default is off..

than you all people

**Comment by kevmitch** [comment]
if you just want it always loop infinite for every file, you can add ```loop=inf``` to your ```mpv.conf```

**Comment by manuelsongokuh** [comment]
not work for me
i added 
loop=inf   in mpv.conf

**Comment by manuelsongokuh** [comment]
sorry..

**Comment by manuelsongokuh** [comment]
not worked...its a bug or...what?
