### ISSUE TITLE
Stuttering with .ogm files.

### ISSUE THREAD

**Issue by z0z0z** [mpv-player/mpv#2074]
When trying to play an .ogm file (I've tried multiple) it constantly stutters making it pretty much unwatchable, warnings in the terminal appear like this:

```
No video PTS! Making something up.
AV: 00:00:00.542 / 00:45:56.159 (0%) A-V:  0.000
No video PTS! Making something up.
AV: 00:00:00.625 / 00:45:56.159 (0%) A-V:  0.000
No video PTS! Making something up.
AV: 00:00:00.709 / 00:45:56.159 (0%) A-V:  0.000
No video PTS! Making something up.
AV: 00:00:00.917 / 00:45:56.159 (0%) A-V:  0.000
Invalid video timestamp: 0.917583 -> 0.875874
AV: 00:00:00.875 / 00:45:56.159 (0%) A-V:  0.000
No video PTS! Making something up.
```

ffprobe output of the file:

```
Duration: 00:45:56.16, start: 0.000000, bitrate: 1352 kb/s
Stream #0:0: Video: mpeg4 (DX50 / 0x30355844), yuv420p, 640x368 [SAR 1:1 DAR 40:23], 23.98 fps, 23.98 tbr, 23.98 tbn, 30k tbc
Stream #0:1(English): Audio: vorbis, 48000 Hz, stereo, fltp, 72 kb/s
Stream #0:2(English): Subtitle: text
```
ffmpeg-2.7.1
mpv-d11184a

**Comment by wm4** [comment]
Looks like a broken file. Remux with mkvmerge,. Fuck ogm.

**Comment by z0z0z** [comment]
ffmpeg gives me fatal errors when trying to remux with that, which was one thing I tried. I'm assuming the problem goes back to ffmpeg but I figured I'd see if anything could happen here. Just saying it does the same thing with every ogm file I found.

I guess I'll try mkvmerge, and give up trying to natively watch ogm files with mpv or ffmpeg-based players.

**Comment by wm4** [comment]
mkvmerge seems to be pretty good at handling ogg, so maybe it has higher chances at success than ffmpeg. ffmpeg will obviously perform on a similar level as mpv, because mpv uses the ffmpeg libraries.

**Comment by wm4** [comment]
You could also report this to ffmpeg, but I really don't care much. ogm support is just too broken overall. (mpv itself doesn't contain a single line specific to handling of ogm files.)

**Comment by z0z0z** [comment]
For anyone who finds this having trouble with the same issue, ```---no-correct-pts``` gives normal playback.

**Comment by wm4** [comment]
That's a quite brutal method and can lead to audio problems, but if it works, great.

Have you tried reporting it to ffmpeg?

**Comment by Niektory** [comment]
I'll add that this bug didn't exist in older versions, for example this version plays .ogm files without issues:
mpv git-b4f72b4 (C) 2000-2014 mpv/MPlayer/mplayer2 projects
 built on 2014-08-08T00:05:19
ffmpeg library versions:
   libavutil       52.98.100
   libavcodec      55.72.102 (runtime 55.73.101)
   libavformat     55.51.101 (runtime 55.53.100)
   libswscale      2.6.100 (runtime 2.6.101)
   libavfilter     4.11.102 (runtime 4.11.103)
   libavresample   1.3.0

**Comment by wm4** [comment]
Yeah, but its ffmpeg is also older. It's likely that this is a ffmpeg regression.

**Comment by wm4** [comment]
PS: unless you're saying that a newer mpv build linked to the same ffmpeg libs exposes the issue.
