### ISSUE TITLE
Blurry VP8/webm output with mpv

### ISSUE THREAD

**Issue by z0z0z** [mpv-player/mpv#2075]
VP8/webm video files just look blurry/low-quality compared to other players, including ffplay, vlc, and firefox's built in player. Tried with --no-config, various vo_opengl options, and vdpau output, same thing.

Pic showing difference:

https://dl4.volafile.io/get/bh1qP6sO4TioE/pic.png

Example webm file:

https://dl4.volafile.io/get/GXlVP6sO4ThIE/vid.webm

**Comment by wm4** [comment]
Your window manager probably resized the window by 1 pixel. Impossible to tell from my perspective.

**Comment by lachs0r** [comment]
This is probably the case if the `scaler-resizes-only` suboption of `vo_opengl` does not help either. Maybe log output (with `-v`) would shed some light on this.

**Comment by z0z0z** [comment]
```scaler-resizes-only``` didn't help.

It happens with openbox and gnome3, only two I tested. This may be whats happening, but just saying, doesn't happen with ffplay or vlc.

**Comment by wm4** [comment]
Does ``--keepaspect-window=no`` help?

**Comment by lachs0r** [comment]
FWIW it looks fine here without any options (using i3).

**Comment by z0z0z** [comment]
```keepaspect-window=no``` fixes it. I'm assuming you know what's wrong at this point from that.

**Comment by wm4** [comment]
>you know what's wrong at this point from that.

Yes. Your window manager. Report a bug. Actually, several people probably already did that.

**Comment by wm4** [comment]
Yes, it was already reported: #1343, last comment.

**Comment by z0z0z** [comment]
I'm not going to bother reporting it to them, nothing will come of it.

I'll still be wondering why it doesn't happen with ffplay, mplayer, VLC, or firefox even though it's just a problem with my WM.

**Comment by wm4** [comment]
>ffplay, mplayer, VLC, or firefox 

None of them actually use the aspect hint, except mplayer. I don't know why it works for you with mplayer.

**Comment by z0z0z** [comment]
This probably isn't of any help, but here's the output of mplayer.

```
Playing vid.webm.
libavformat version 56.38.102 (external)
libavformat file format detected.
[lavf] stream 0: video (vp8), -vid 0
VIDEO:  [VP80]  610x430  0bpp  60.000 fps    0.0 kbps ( 0.0 kbyte/s)
Clip info:
 encoder: Lavf56.38.102
Load subtitles in ./
==========================================================================
Opening video decoder: [ffmpeg] FFmpeg's libavcodec codec family
libavcodec version 56.45.100 (external)
Selected video codec: [ffvp8] vfm: ffmpeg (FFmpeg VP8)
==========================================================================
Audio: no sound
Starting playback...
Movie-Aspect is 1.42:1 - prescaling to correct movie aspect.
VO: [vdpau] 610x430 => 610x430 Planar YV12 
Movie-Aspect is 1.42:1 - prescaling to correct movie aspect.
VO: [vdpau] 610x430 => 610x430 Planar YV12 
```

**Comment by wm4** [comment]
xwininfo and xprop output would be useful.

**Comment by z0z0z** [comment]
xwininfo and xprop of mplayer:

http://pastebin.com/RcapCpNA
http://pastebin.com/hUprJWKb

xwininfo and xprop of mpv:

http://pastebin.com/qJDTRE2v
http://pastebin.com/bFeuVFAr

**Comment by wm4** [comment]
They set the same aspect hints. They have a differerent window gravity, no idea if that would change anything. For some reason, MPlayer still gets correctly sized by the WM.
