### ISSUE TITLE
Can’t play stream unless command-line version is in PATH

### ISSUE THREAD

**Issue by vitorgalvao** [mpv-player/mpv#2082]
I have mpv installed both as a command-line tool (`mpv`) and an OS X app bundle (`mpv.app`), under `usr/local`<sup>1</sup>. To open `mpv.app` from a terminal, `/usr/local` does not need to be in `PATH`, as OS X allows us to `open -a 'mpv' "<file_location>"`, and it will open the file with `mpv.app`.

However, playing a stream (like a youtube url) fails if `mpv` is not under `PATH`. A similar `open -a 'mpv' "<youtube_url>"` fails in that situation. This is somewhat weird when happening, for two reasons:

1. It works fine it done on a local file.
2. When I say it fails, what I mean is it actually opens `mpv.app` and sometimes even shows the window like if it were going to play, but then it just quits<sup>2</sup>.

This won’t be an issue in most cases. However, it is still frustrating when it does happen since no clue is given as to what is causing mpv to fail (seemingly crash). I’ve encountered this while trying to call mpv from an [Alfred](http://www.alfredapp.com/) Workflow (a kind of plugin), since it does not load a user’s `PATH`.

At first I thought this might be a limitation with Alfred, but VLC worked fine with the equivalent commands, for the same tasks, under the same conditions. mpv also worked well under a terminal until I specifically removed `/usr/local` from `PATH`.

Using OS X Yosemite 10.10.3 (14D136) and mpv 0.9.2 installed with homebrew.

---

<sup>1</sup> `mpv` (the cli version) is linked on `/usr/local/bin/mpv` (real location is `/usr/local/Cellar/mpv/0.9.2/bin/mpv`) and `mpv.app` (the OS X app bundle) is at `/usr/local/Cellar/mpv/0.9.2/mpv.app`.

<sup>2</sup> Logs:
```
28/06/15 17:51:44,885	CoreServicesUIAgent[58829]	unexpected message <OS_xpc_error: <error: 0x7fff7d9bfc60> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x7fff7d9bff70> { length = 18, contents = "Connection invalid" }
}>
28/06/15 17:51:44,890	com.apple.xpc.launchd[1]	(io.mpv.84948[94508]) Service exited with abnormal code: 2
```

**Comment by wm4** [comment]
If mpv is called with youtube URLs, it calls youtube-dl - simple as that. Thus youtube-dl must be in PATH for mpv.

**Comment by vitorgalvao** [comment]
So that means that if I do not have youtube-dl installed, it won’t work at all?

**Comment by vitorgalvao** [comment]
Ah, I was under the impression mpv had perhaps included youtube-dl in its code, instead of calling it as an external tool. The issue is a different one, then.

**Comment by wm4** [comment]
>Ah, I was under the impression mpv had perhaps included youtube-dl in its code, instead of calling it as an external tool. 

Since youtube-dl is written in Python, and since dealing with ever-changing multimedia sites requires intense maintenance, calling it as command line tool is pretty much the best course of action. (We used to use libquvi, but that was suddenly not maintained anymore.)

**Comment by vitorgalvao** [comment]
> calling it as command line tool is pretty much the best course of action

I agree, I see your point. Would it not be possible to warn about that when calling the app bundle over a terminal, however? No output on the terminal or on the console really makes this hard to diagnose. The command-line version prints a simple useful message.

**Comment by wm4** [comment]
We were thinking of printing error messages on the window. But for now we don't have any real plans.

I'm also wondering how we should handle log output on OSX when the bundle is used. I really have no idea.
