### ISSUE TITLE
Pan-and-scan at 90 or 270 degree rotation

### ISSUE THREAD

**Issue by ThomS8312** [mpv-player/mpv#2085]
<code>--panscan</code> still has black bars when a video is rotated at 90/270 degrees at the sides (which is actually the video's top and bottom). Can pan-and-scan be changed to account for those types of rotation too?

**Comment by wm4** [comment]
Not sure what you mean. It works for me.

**Comment by ThomS8312** [comment]
I'm not using a widescreen monitor, so common resolution videos (ie. 360p/480p/720p/1080p) have black bars at the top and bottom when at full screen.

Add to input.conf:
<code>KEY cycle_values video-rotate "90" "270" "no"</code>

- Play a 720p/1080p video (these resolutions have more prominent black bars for me).
- Press <code>f</code> for full screen.
- Press <code>e</code> to zoom in at max value 1.000, making the black bars disappear at the top and bottom while cropping the picture at the sides.
- Press <code>KEY</code> keybinding to rotate the picture 90/270 degrees.

Are black bars present at the sides of the screen when rotated this way?

**Comment by wm4** [comment]
I think what you're seeing is just an arbitrary restriction about panscan not always being able to fill the entire screen with the video frame if the image is taller than wide or so. I'm not sure yet where that comes from.

**Comment by wm4** [comment]
2e4f106ef87f3f42d88b8d76313967700437e271 probably fixes this.

**Comment by ThomS8312** [comment]
It works with 90/270 degress now, but with an issue:

- Hold down <code>e</code> until Panscan is 1.000.
- Rotate 90 or 270 degrees.
- Pan "up" "or "down" (<code>video-align-y</code>).
- Hold down <code>w</code> until Panscan is 0.000.
- Rotate to original orientation or 180 degrees.

The video will not be centered, but at 90/270 it still is.

**Comment by ThomS8312** [comment]
My mistake, it's supposed to be like that due to panning on that axis. That panned value is kept and reflected when the orientation is changed. Looks like that commit solves this issue.
