### ISSUE TITLE
Video-pan and video-align have negative 0 values

### ISSUE THREAD

**Issue by ThomS8312** [mpv-player/mpv#2087]
The value of 0 should be 0.000, but can be -0.000 instead when the <code>add</code> input command value is .05. To test this for <code>--video-pan-x</code> and <code>--video-pan-y</code>, pan to max value -3.000 and then to 0. For <code>video-align-x</code> and <code>video-align-y</code>, pan to max value 1.000 and then to 0.

Configuration for input.conf:
<code>KEY add video-pan-x +.05</code>
<code>KEY add video-pan-x -.05</code>
<code>KEY add video-pan-y +.05</code>
<code>KEY add video-pan-y -.05</code>

<code>KEY add video-align-x +.05</code>
<code>KEY add video-align-x -.05</code>
<code>KEY add video-align-y +.05</code>
<code>KEY add video-align-y -.05</code>

**Comment by rr-** [comment]
I'll fix it later today unless someone disapproves.

**Comment by ThomS8312** [comment]
Different behavior from above noted:

- Changing the value from .05  to 1.0 <b>does not</b> result in a -0.000 for <code>video-pan-x</code>,<code>video-pan-y</code> and <code>video-align-x</code>,<code>video-align-y</code>.
- Changing the value from .05 to .02 <b>does</b> result in a -0.000 when panning from max value -3.000 to 0 for <code>video-pan-x</code>,<code>video-pan-y</code> and panning from max value -1.000 to 0 for <code>video-align-x</code>,<code>video-align-y</code>.

**Comment by ThomS8312** [comment]
Tested with git and the issue persists. It's easier to get the -0.000 issue now. One simple -.05 step (-0.050) and back to 0.000 triggers it.

I get the impression that there's a deeper issue that needs to be addressed. Maybe the method used for panning is part of the problem?

**Comment by rr-** [comment]
@ThomS8312 there's no need to test further, we know what's going on and we're figuring out what is the most elegant way to resolve this issue.
