### ISSUE TITLE
mpv: relocation error: mpv: symbol av_vdpau_alloc_context, version LIBAVCODEC_56 not defined in file libavcodec.so.56 with link time reference

### ISSUE THREAD

**Issue by JesusIslam** [mpv-player/mpv#2088]
`mpv: relocation error: mpv: symbol av_vdpau_alloc_context, version LIBAVCODEC_56 not defined in file libavcodec.so.56 with link time reference`

Is the error I get when trying to run mpv. What should I do to fix this

My system is Ubuntu 15.04 x64.

**Comment by lachs0r** [comment]
That looks like mpv was built with a different version of FFmpeg than the one installed on your system. If you’ve installed mpv from a software repository, blame the packager for not getting the package dependencies right.

**Comment by JesusIslam** [comment]
Ok, I will compile it myself then

**Comment by mc4man** [comment]
More likely with such linker errors it's a user created issue...

**Comment by JesusIslam** [comment]
After manual compiling it runs fine, but missing avsynth.
