### ISSUE TITLE
Keep panning behavior consistent regardless of video orientation

### ISSUE THREAD

**Issue by ThomS8312** [mpv-player/mpv#2091]
It'd be convient if there's a way to keep the behavior of panning (<code>--video-pan-x</code>, <code>--video-pan-y</code>, <code>--video-align-x</code>, <code>--video-align-y</code>) as it is by default, despite a video's orientation.

For example, when a video is rotated by 270/180 degrees, panning "left" and "right" is reversed.

**Comment by wm4** [comment]
That's just the order of operations. Since that order is not easily changeable (as a video filter might do the rotation, while panning is handled on display), it seems unlikely that we change it. Unless someone sees a simple way to do that.

What's the use case for this at all?

**Comment by ThomS8312** [comment]
<blockquote>What's the use case for this at all?</blockquote>

I don't have one in particular. I just noticed how it makes navigation a little confusing and thought it could be improved.

I think I might have an easy way to change this, but I noticed something that needs to be corrected first. The <code>video-pan-y</code> and <code>video-align-y</code> properties have the postives and negatives reversed. Negative "y" pans up and positive "y" pans down.

**Comment by wm4** [comment]
>The video-pan-y and video-align-y properties have the postives and negatives reversed. Negative "y" pans up and positive "y" pans down.

That's just a matter of taste. The mpv coordinate system starts in the top/left corner, so this is consistent.

**Comment by ThomS8312** [comment]
<blockquote>The mpv coordinate system starts in the top/left corner, so this is consistent.</blockquote>

I see, it's like GIMP's coordinate system.

I see it to be fairly problematic that this applies to mpv because it suggests a behavioral expectation, yet denies it. It's as if I'm relearning something I've been taught was "right" is "wrong".

In GIMP, the coordinates (0,0) will match the top left corner of an image to the top left of the work area. Mpv on the other hand, <i>centers</i> the picture at (0,0). Combined with the negative and positive panning, it gives a strong impression that the x and y axes match the <a href="https://en.wikipedia.org/wiki/Cartesian_coordinate_system">Cartesian coordinate system</a>. I'm not sure if a top left coordinate system is ideal for mpv...unless there's a reason against the Cartesian coordinate system?

**Comment by ThomS8312** [comment]
Key bindings and test results:
<pre><code>Alt+LEFT add video-pan-x -.05       Pans <b>left</b>    (Negative values)
Alt+RIGHT add video-pan-x +.05      Pans <b>right</b>   (Positive values)
Alt+UP add video-pan-y +.05         Pans down    (Positive values)
Alt+DOWN add video-pan-y -.05       Pans up      (Negative values)

Ctrl+LEFT add video-align-x -.05    Pans <b>right</b>   (Negative values)
Ctrl+RIGHT add video-align-x +.05   Pans <b>left</b>    (Positive values)
Ctrl+UP add video-align-y +.05      Pans down    (Positive values)
Ctrl+DOWN add video-align-y -.05    Pans up      (Negative values)
</code></pre>

The panning direction of the video-pan-x and video-align-x properties aren't consistent,
but should be.

**Comment by ThomS8312** [comment]
UPDATE:
Proper panning means the video is moved in the opposite direction of the labeled motion. For example, panning "left" means moving the video to the right so what's at the left of the video is seen when a video is cropped at the sides. I was confused by that and made conclusions that were incorrect.

Concerns about the Cartesian coordinate system are also invalid, as mpv already pans in that way. My previous posts have been corrected (or deleted for being completely irrelevent). Test results have been changed and updated.

**Comment by ThomS8312** [comment]
Panning behaves differently between the <code>--video-rotate</code> property and the <code>rotate</code> video filter:

<pre>
correct   =  -x pans left,  +x pans right, +y pans up,   -y pans down
reversed  =  -x pans right, +x pans left,  +y pans down, -y pans up


Video property: --video-rotate=<0-360|no>
0/360  =  x-axis is correct.  y axis is correct.
90     =  x-axis is reversed. y-axis is reversed.
180    =  x-axis is <b>reversed</b>. y-axis is correct.
270    =  x-axis is reversed. y-axis is <b>correct</b>.

Video filter: rotate[=0|90|180|270]
0      =  x-axis is correct.  y axis is correct.
90     =  x-axis is reversed. y-axis is reversed.
180    =  x-axis is <b>correct</b>.  y-axis is correct.
270    =  x-axis is reversed. y-axis is <b>reversed</b>.
</pre>

I don't know why these two ways to rotate don't behave the same way since they do the same thing. Does addressing this issue fall under the "not easily changeable" category?

**Comment by wm4** [comment]
They behave differently because they are implemented differently.

This inconsistency could probably be fixed. The hard part is finding out how and why. Though I'm pretty sure you only need to flip some signs in video/out/aspect.c depending on the current rotation.

**Comment by ThomS8312** [comment]
Another issue found. The <code>video-zoom</code> property can change the panning behavior of the <code>video-align-x</code> and <code>video-align-y</code> properties. This occurs if zoomed in enough that there are no black bars visible or zoomed out enough that black completely surrounds the video:

<pre>
correct   =  -x pans left,  +x pans right, +y pans up,   -y pans down
reversed  =  -x pans right, +x pans left,  +y pans down, -y pans up
<i>*Bold text highlights differences between results.</i>


Video property: --video-rotate=<0-360|no>  (Zoomed in)
0/360  =  x-axis is correct.  y axis is reversed.
90     =  x-axis is <b>reversed</b>. y-axis is reversed.
180    =  x-axis is <b>reversed</b>. y-axis is <b>correct</b>.
270    =  x-axis is correct.  y-axis is <b>correct</b>.

Video filter: rotate[=0|90|180|270]  (Zoomed in)
0      =  x-axis is correct. y axis is reversed.
90     =  x-axis is <b>correct</b>. y-axis is reversed.
180    =  x-axis is <b>correct</b>. y-axis is <b>reversed</b>.
270    =  x-axis is correct. y-axis is <b>reversed</b>.


Video property: --video-rotate=<0-360|no>  (Zoomed out)
0/360  =  x-axis is reversed.  y axis is correct.
90     =  x-axis is reversed.  y axis is correct.
180    =  x-axis is reversed.  y axis is correct.
270    =  x-axis is reversed.  y axis is correct.

Video filter: rotate[=0|90|180|270]  (Zoomed out)
0      =  x-axis is reversed. y axis is correct.
90     =  x-axis is reversed. y axis is correct.
180    =  x-axis is reversed. y axis is correct.
270    =  x-axis is reversed. y axis is correct.


Compare these test results to the test results in my last post.
</pre>

<blockquote>This inconsistency could probably be fixed.</blockquote>

What would the behavior be when it's fixed? Because at this point, a solution for the original issue to "keep panning behavior consistent regardless of video orientation" might as well be implemented if significant changes are going to be done anyway.

**Comment by wm4** [comment]
Are you sure you're observing the correct thing, and aren't just confused about video rectangle moving vs. video itself moving?

**Comment by ThomS8312** [comment]
<blockquote>Are you sure you're observing the correct thing, and aren't just confused about video rectangle moving vs. video itself moving?</blockquote>

I'm not sure what you mean by video rectangle vs. video, but I'm looking at the direction that the panning movement takes with the <code>video-align-x</code> and <code>video-align-y</code> properties. Panning should not only move in the same direction regardless of zoom level, but also in the proper direction.

Test using these keybindings:
<pre>
Ctrl+LEFT add video-align-x -.05
Ctrl+RIGHT add video-align-x +.05
Ctrl+UP add video-align-y +.05
Ctrl+DOWN add video-align-y -.05

; add video-zoom -0.1
' add video-zoom +0.1

b set video-align-x 0 ; set video-align-y 0
n set video-zoom 0
</pre>

<i>*Press <code>b</code> and <code>n</code> to reset pan values and zoom level to 0, respectively.</i>

Follow these steps (Zooming in):
- 1. Play a video.
- 2. Press <code>'</code> to zoom in.
- 3. Press <code>Ctrl+UP</code> and <code>Ctrl+DOWN</code> and observe the movement. See how <code>Ctrl+UP</code> makes the video pan down? This <b>isn't</b> how the behavior should be; it's reversed. The video should pan up.
- 4. Press <code>Ctrl+RIGHT</code> and <code>Ctrl+LEFT</code> and observe the movement. See how <code>Ctrl+RIGHT</code> makes the video pan right? This is how the behavior should be.

Follow these steps (Zooming out):
- 1. Play a video.
- 2. Press <code>;</code> to zoom out (black surrounds all the video).
- 3. Press <code>Ctrl+UP</code> and <code>Ctrl+DOWN</code> and observe the movement. See how <code>Ctrl+UP</code> makes the video "go down" as the black at the top increases and the black at the bottom decreases? This is how the behavior should be; it's panning up.
- 4. Press <code>Ctrl+RIGHT</code> and <code>Ctrl+LEFT</code> and observe the movement. See how <code>Ctrl+RIGHT</code> makes the video "go right" as the black to the right decreases and the black at the left increases? This <b>isn't</b> how the behavior should be; it's reversed and panning left. The video should be "going left".

You can see that the above steps match the previous test results too.

**Comment by wm4** [comment]
What I'm saying is, the video rectangle always moves into the right direction, just not the video. The latter is an issue with how rotation is done in vo_opengl, which I'm permanently too tired to analyze/fix.

**Comment by ThomS8312** [comment]
The "video rectangle" is when you see the video beyond its boundaries (negative zoom value), and the "video" is when there is no zoom or zoomed in (0 or positive zoom value). Is that correct?

**Comment by wm4** [comment]
Kind of, but obviously both are present in both cases.

**Comment by wm4** [comment]
So I assume this is a problem with the vo_opengl rotation code.

**Comment by ThomS8312** [comment]
Partly. These are the issues:

1. Keep panning behavior consistent regardless of video orientation. (Rotation issue)
2. Panning is reversed with the <code>video-pan-x</code> property. (Panning issue)
3. Panning behaves differently between the <code>--video-rotate</code> property and the <code>rotate</code> video filter. (Panning/Rotation issue)
4. The <code>video-zoom</code> property can change the panning behavior of the <code>video-align-x</code> and <code>video-align-y</code> properties. (Zoom/Panning Issue)

**Comment by ThomS8312** [comment]
This post is just to add some perspective to why mpv's current behavior is an issue in this area. A good example of what mpv's behavior should follow can be observed from a typical image viewer.

In all the image viewers I have used with pan/zoom/rotate features, the behavior has been consistent among them. It is a well established standard. The original issue (keeping panning behavior consistent regardless of video orientation) is an example of behavior from this "image viewer standard", and the other issues were compared to it too.

Things like order of operations, certain panning behavior, etc. may be correct at a technical level in mpv, but not necessarily correct to the user. Usability is more important than presenting the user with technical accuracy in this case. Following the "image viewer standard" makes mpv's panning/zooming/rotating intuitive and user friendly.

**Comment by haasn** [comment]
I did a recent test of the interactions between `video-zoom`, `video-align`, `video-rotate` and `video-pan` and found them to all work consistently and as expected.

Though I've not read the entire thread, I'll assume this can be closed?

**Comment by ThomS8312** [comment]
This issue is still present in mpv. I've written a short guide to highlight the problem in a couple of examples.

Commands for input.conf:
<pre>b cycle-values video-rotate "90" "180" "270" "no"
n cycle-values video-zoom "1" "0"
Alt+LEFT add video-pan-x -.1
Alt+RIGHT add video-pan-x +.1
Alt+UP add video-pan-y +.1
Alt+DOWN add video-pan-y -.1
Ctrl+LEFT add video-align-x -.1
Ctrl+RIGHT add video-align-x +.1
Ctrl+UP add video-align-y +.1
Ctrl+DOWN add video-align-y -.1
</pre>


There are differences in panning direction in <code>panscan</code> and <code>video-zoom</code> when using <code>video-align-x/y</code> and <code>video-pan-x/y</code>. Here are steps to take to observe them:

Step 1 - Open a video with an aspect ratio that gives black bars at the top and bottom, then press <code>F</code> to enter fullscreen.
Step 2 - Press <code>E</code> until the panscan value is <code>0.500</code>.
Step 3 - Press <code>Ctrl+RIGHT</code> 3 times the <code>Ctrl+LEFT</code> 3 times. It moves in the proper direction.
Step 4 - Now press <code>Alt+LEFT</code> 3 times, then <code>Alt+RIGHT</code> 3 times. The movements are reversed this time.
Step 5 - Press <code>W</code> until panscan has a value of <code>0.000</code>.
Step 6 - Press <code>N</code> to zoom.
Step 7 - Press <code>Ctrl+UP</code> 3 times, then <code>Ctrl+DOWN</code> 3 times. The movements are reversed.
Step 8 - Press <code>Alt+UP</code> 3 times, then <code>Alt+DOWN</code> 3 times. It moves in the proper direction.

You can observe the discrepancies in panning behavior when the video is rotated at different angles too by pressing <code>B</code>. I've already done extensive testing on this in previous posts. I'm not sure if those results are still accurate after all the changes in mpv since then, but it can give an idea of the changes that occur at different rotations.

**Comment by haasn** [comment]
Works correctly for me with that test.

**Comment by ThomS8312** [comment]
To make sure we're on the same page, you mean:

Ctrl+RIGHT and Alt+RIGHT **both** scroll to the right in <code>panscan</code>?
Ctrl+LEFT and Alt+LEFT **both** scroll to the left in <code>panscan</code>?
Ctrl+UP and Alt+UP **both** scroll upwards in <code>video-zoom</code>?
Ctrl+DOWN and Alt+DOWN **both** scroll downwards in <code>video-zoom</code>?

**Comment by haasn** [comment]
What I mean is that `video-pan` always pans the video in that direction, `video-align` always aligns the video in that direction, and `video-zoom` and `panscan` don't affect this in any way.

**Comment by ThomS8312** [comment]
Looks like it's on my end then. The computer I used has old hardware, so maybe the video card doesn't have the capability to use this functionality properly. Could that be the reason?

**Comment by wm4** [comment]
Definitely not.

**Comment by Dudemanguy** [comment]
Seems to work correctly according to the thread? Feel free to reopen if not.
