### ISSUE TITLE
mpv in Windows 8.1 doesn't render subtitle correctly

### ISSUE THREAD

**Issue by knightzx** [mpv-player/mpv#2092]
mpv shows whitespaces instead of characters if the subtitle line contains " ' " character but it will render fine if that line contains another " ' " character
For example:
```
 They 'll bloom, yes they will, and they 'll bloom again until
>They                                    'll bloom again until
 there 's no missing sorrow
>there
```
EDIT: I upload the file at https://www.dropbox.com/s/16brvac2xb7wsr5/%5BCommie%5D%20Hana%20wa%20Saku%20-%20Flowers%20Will%20Bloom%20%5B8B6A9066%5D.mkv?dl=1
It happened at 1:45.

**Comment by wm4** [comment]
Maybe this will fix itself once libass has a native windows font backend.

**Comment by wiiaboo** [comment]
Could you post a sample of those subtitles? I've never had that bug.

**Comment by knightzx** [comment]
I uploaded the file.
I don't know if it's only happened with this specific file but on Linux, mpv plays the file without any problem.

**Comment by wiiaboo** [comment]
Dialogue: 5,0:03:49.85,0:03:55.95,Default,,0,0,0,,{\fad(200,200)\blur2}They{\fscx0\fsp-4} {\fscx100\fax-0.2}'{\fax0\fsp0}ll bloom, yes they will, and they{\fscx0\fsp-4} {\fscx100\fax-0.2}'{\fax0\fsp0}ll bloom again until
Dialogue: 5,0:03:55.95,0:04:02.28,Default,,0,0,0,,{\fad(200,200)\blur2}there{\fscx0\fsp-4} {\fscx100\fax-0.2}'{\fax0\fsp0}s no missing sorrow and no reason left to mourn

Problem is with the subs.

**Comment by wm4** [comment]
>The likely culprits are these tags and libass, not mpv.

Good enough for me to close this.

**Comment by wm4** [comment]
In fact it looks like this is the same bug: https://github.com/libass/libass/issues/185

**Comment by wiiaboo** [comment]
I opened it after, so it is the same bug.

**Comment by wm4** [comment]
I see, thanks.
