### ISSUE TITLE
OSC top/bottom bar layout flaws

### ISSUE THREAD

**Issue by ChrisK2** [mpv-player/mpv#2093]
stuff is not properly aligned along horizontal axes
![screen shot 2015-06-30 at 20 09 16](https://cloud.githubusercontent.com/assets/3440203/8438095/ff6ea348-1f63-11e5-87cc-a53451a4a188.png)

seekbar tool-tip may collide with file title and become hard to read
![screen shot 2015-06-30 at 20 05 47](https://cloud.githubusercontent.com/assets/3440203/8438088/f4be3e04-1f63-11e5-9460-12629a31e4a1.png)

**Comment by Morecutter** [comment]
Is this Linux UI?

**Comment by ChrisK2** [comment]
http://mpv.io/manual/master/#on-screen-controller-layout

**Comment by ItzBlitz98** [comment]
Since this is somewhat related i think an option for truncating urls and titles is needed.

![mpv_510](https://cloud.githubusercontent.com/assets/1562336/8763923/2afd8f04-2dad-11e5-90e1-e5d685ba55cd.png)

**Comment by wiiaboo** [comment]
This should make the labels aligned with each other and the buttons, at least on my osd-font:
```patch
diff --git a/player/lua/osc.lua b/player/lua/osc.lua
index 09ca0eb..924250d 100644
--- a/player/lua/osc.lua
+++ b/player/lua/osc.lua
@@ -47,12 +47,12 @@ local osc_param = { -- calculated by osc_init()
 local osc_styles = {
     bigButtons = "{\\blur0\\bord0\\1c&HFFFFFF\\3c&HFFFFFF\\fs50\\fnmpv-osd-symbols}",
     smallButtonsL = "{\\blur0\\bord0\\1c&HFFFFFF\\3c&HFFFFFF\\fs20\\fnmpv-osd-symbols}",
-    smallButtonsLlabel = "{\\fs17\\fn" .. mp.get_property("options/osd-font") .. "}",
+    smallButtonsLlabel = "{\\fs21\\fn" .. mp.get_property("options/osd-font") .. "}",
     smallButtonsR = "{\\blur0\\bord0\\1c&HFFFFFF\\3c&HFFFFFF\\fs30\\fnmpv-osd-symbols}",
     topButtons = "{\\blur0\\bord0\\1c&HFFFFFF\\3c&HFFFFFF\\fs12\\fnmpv-osd-symbols}",
 
     elementDown = "{\\1c&H999999}",
-    timecodes = "{\\blur0\\bord0\\1c&HFFFFFF\\3c&HFFFFFF\\fs20}",
+    timecodes = "{\\blur0\\bord0\\1c&HFFFFFF\\3c&HFFFFFF\\fs21}",
     vidtitle = "{\\blur0\\bord0\\1c&HFFFFFF\\3c&HFFFFFF\\fs12}",
     box = "{\\rDefault\\blur0\\bord1\\1c&H000000\\3c&HFFFFFF}",
 }
@@ -1082,7 +1082,7 @@ layouts["bottombar"] = function()
 
 
     -- Left timecode
-    geo = { x = geo.x + geo.w + padX + 100, y = geo.y, an = 9,
+    geo = { x = geo.x + geo.w + padX + 100, y = geo.y - 1, an = 9,
             w = 100, h = geo.h }
     lo = add_layout("tc_left")
     lo.geometry = geo

```

**Comment by wiiaboo** [comment]
- [ ] fix bottom/topbar when width too small to render all items properly
- [ ] fix chapter ticks with bar slider
- [ ] change default sub positioning to not be covered by osc
