### ISSUE TITLE
MPV spams console and overworks CPU when unable to display image attachments

### ISSUE THREAD

**Issue by jaxuru** [mpv-player/mpv#2094]
I've been using mpv to play audio files and display the album art, but with many of the audio files (namely any audio file downloaded from iTunes) mpv fails to read and display the image attachment. When this occurs, rather than displaying nothing, mpv spams the console with the following message until the song is over:

[ffmpeg/video] png: Invalid PNG signature (70069).
Error while decoding frame!

![screen2](https://cloud.githubusercontent.com/assets/8195503/8438089/879d0ae4-1f18-11e5-8747-575682f758d1.png)

Additionally, mpv's cpu usage shoots up to around 140%, and iTerm's usage skyrockets as well, heating the computer up quite a bit eventually:

![screen1](https://cloud.githubusercontent.com/assets/8195503/8438390/5e60a76a-1f1a-11e5-9fd7-e6971479ce21.png)

It's possible to filter out the repeated messages using --msg-level, but the out of control cpu usage persists. Additionally, when the message is filtered out, the status message (e.g. "A: 00:00:16 / 00:04:13 (6%)") in the console fails to display. The issue is replicable with --no-config and by attempting to play audio from iTunes Match or the iTunes Store.

**Comment by wm4** [comment]
Already fixed in git master.... and FFmpeg master (attachments which claim to be PNG, but are actually JPG).
