### ISSUE TITLE
[OSX] ui freeze on pause

### ISSUE THREAD

**Issue by typcn** [mpv-player/mpv#2095]
![image](https://cloud.githubusercontent.com/assets/8022103/8445035/e66e94b8-1fca-11e5-93bc-331193128790.png)

Same issue on stop or quit , sometimes cause CPU 100%

**Comment by wm4** [comment]
Useless without backtrace. Also, can not reproduce.

**Comment by typcn** [comment]
I have retried, it happened every times.

My Xcode always crash when trigger this , I found it manually.

My Program:  mpv_set_property_string(mpv,"pause","yes");
MPV : [mp_property_pause](https://github.com/mpv-player/mpv/blob/db3d36927dcc8674b32c61f7e9c0f688a278bfc4/player/command.c#L1203) -> [vo_control](https://github.com/mpv-player/mpv/blob/ff9c597fbf620bd207aaf123640233bb5f4edd7f/player/playloop.c#L76-L81) -> [mp_dispatch_run](https://github.com/mpv-player/mpv/blob/d11184a256ed709a03fa94a4e3940eed1b76d76f/video/out/vo.c#L404-L410) -> Freeze [here](https://github.com/mpv-player/mpv/blob/20bc56b22d7b1679d2cd83fec216697b8b922a09/misc/dispatch.c#L163)

**Comment by wm4** [comment]
Are you using cocoa window embedding?

**Comment by typcn** [comment]
Yes , codes here
https://github.com/typcn/bilibili-mac-client/blob/master/bilibili/PlayerView/PlayerView.mm#L333

**Comment by wm4** [comment]
And what mpv version?

**Comment by typcn** [comment]
git master

**Comment by wm4** [comment]
It seems like you make accesses to cocoa from different threads. I'm not totally sure, but I don't think Cocoa allows this at all.
