### ISSUE TITLE
Seeking backwards results in a still frame with interpolation

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#2097]
After the latest bunch of commits, seeking backwards with interpolation sometimes results in a stuck frame for a few seconds. The audio works properly and both OSC's and OSD's progress bars move forward, and after a few seconds playback resume as expected; no particular framedrop is reported.
This happens often but not everytime, only when interpolation is active and when making *exact* backwards seeks; with forwards ones and non-exact backwards seeks the issue never shows up in my tests.

There seems to be nothing of worth on the verbose terminal output regarding this, but let me know if you need the log nonetheless.
I'm using the latest git master on Os X 10.10.3.

**Comment by wm4** [comment]
What are the exact vo opengl options you use?

**Comment by AirPort** [comment]
`vo=opengl-hq:icc-profile-auto:icc-cache-dir=~~/cache:blend-subtitles:interpolation:source-shader=~~/shaders/deband.glsl`

**Comment by wm4** [comment]
Hm, yes sometimes I see it too. I can trigger it best with chapter seeks.
