### ISSUE TITLE
bitmap subtitles should use margins

### ISSUE THREAD

**Issue by Twilight** [mpv-player/mpv#2098]
i.e. while playing 16:9 video in full screen on a 4:3 monitor, or 2.39:1 video on a 16:9 monitor, it looks better if subtitle resides in the black bar under the video.

~~This is the behavior of MPC-HC~~. Could be done by the following lua script somehow, I guess you guys can do better, like lua interface can't detect screen aspect ratio.

```lua
local expanded = false
local SAR_W = 16
local SAR_H = 9

function on_fullscreen_change(n, v)
	if (v) then
		if tonumber(mp.get_property('video-aspect')) > SAR_W / SAR_H + 0.1
			and mp.get_property('sid') ~= 'no'
			and not expanded then
			mp.commandv('vf', 'add', 'expand=::::' .. SAR_W .. '/' .. SAR_H)
			expanded = true
		end
	else
		if expanded then
			mp.commandv('vf', 'del', '-1')
			expanded = false
		end
	end
end

mp.observe_property('fullscreen', 'bool', on_fullscreen_change)
```

**Comment by wm4** [comment]
Don't use vo_xv.

**Comment by Argon-** [comment]
This is done by default for non-ass subs and can be enabled for ass subs: http://mpv.io/manual/master/#options-ass-force-margins

**Comment by wm4** [comment]
Note that the default behavior was changed recently - I don't remember if it's in 0.9. But probably is.

**Comment by Twilight** [comment]
using vo opengl-hq, dvd_subtitle(idx/sub), Windows

mpv git-fccce81 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-06-28T17:11:20

how do I know if this is newer than 0.9 or not?

**Comment by wm4** [comment]
Right, it doesn't work for bitmap subs either.

Bitmap subs are explicitly positioned, and it's not even clear how they'd use the margins. No matter what you do, something would get mispositioned or stretched etc.

**Comment by Twilight** [comment]
thanks for clearing that up.

**Comment by wm4** [comment]
So what does mpc-hc do? I doubt it stretches the subtitle canvas to the screen. That would look funny if you resized the window to something very different from 16:9 or 4:3.

**Comment by Twilight** [comment]
My bad, MPC-HC doesn't do this to dvd subtitles neither, I didn't notice that, the comparison is invalid.

And I didn't notice mpv does use the margin for non-bitmap subtitles, hence the old issue title.

Sorry, I'm new to mpv.

For now I've clearly understood the situation, at least I think I have. this might cause trouble for some corner cases, but I assume rounding up to either 4:3 or 16:9(whichever is closer) would be OK for most scenarios? bitmap subtitles mainly comes from DVD or BD, AFAIK they only support those two aspect ratios, when people rip them they usually cut of the black borders which causes this misalignment.

**Comment by Twilight** [comment]
great, it seems like you skipped the "rounding up to either 4:3 or 16:9" part, but most dvd/bluray titles are 16:9 and most screens are 16:9 too these days, so good enough for me :)
