### ISSUE TITLE
playlist-defined media titles

### ISSUE THREAD

**Issue by siikamiika** [mpv-player/mpv#2100]
I'd like to use the title defined in m3u `#EXTINF` instead of the stream path when playing streams. I have a partially working solution with a lua script (https://github.com/siikamiika/scripts/blob/master/mpv%20scripts/m3u_titles.lua) but it's a bit overkill because it has to re-read the playlist in order to fetch the titles and it doesn't even work when the file extension isn't visible.

Having a property such as `playlist-title` would be cool but lua access to the raw playlist file would work as well if parsing playlist titles isn't meant to be supported.

**Comment by wm4** [comment]
Do you have a sample file?

**Comment by siikamiika** [comment]
```
#EXTM3U
#EXTINF:-1,Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG\Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG.mkv
http://localhost:8888/0/0
#EXTINF:-1,Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG\Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG.nfo
http://localhost:8888/0/1
#EXTINF:-1,Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG\Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG.srt
http://localhost:8888/0/2
#EXTINF:-1,Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG\RARBG.com.mp4
http://localhost:8888/0/3
#EXTINF:-1,Mad.Max.Fury.Road.2015.1080p.WEB-DL.DD5.1.H264-RARBG\RARBG.com.txt
http://localhost:8888/0/4
```

**Comment by siikamiika** [comment]
Thanks! I've updated the script to use `playlist/N/title`.
