### ISSUE TITLE
[Request] Bring back tscale=oversample

### ISSUE THREAD

**Issue by m45t3r** [mpv-player/mpv#2102]
Using ``interpolation`` option in the following sample: https://dl.dropboxusercontent.com/u/5701892/mpv-blur.mkv (pay attention when the camera is passing between the characters).

It used to be much more sharp when tscale was set by default to ``oversample``. Yeah, it was less fluid too, but using ``robidoux``, ``robidouxsharp`` or ``mitchell`` (the recomendation from manpage), while more fluid, it is just too blurry. The madVR with smoothmotion is more sharp too (equivalent to the old ``tscale=oversample``).

**Comment by m45t3r** [comment]
Another example: https://dl.dropboxusercontent.com/u/5701892/mpv-blur2.mkv

**Comment by wm4** [comment]
@haasn: we've talked about it. It's up to you whether you think it's worth the effort.

**Comment by haasn** [comment]
Sure, I'd be interested in implementing this. (Or maybe somebody else could take a look at it)
