### ISSUE TITLE
[Feature Request] add tab information just like baka or bomi

### ISSUE THREAD

**Issue by redhatlinux10** [mpv-player/mpv#2103]
when playing a video using [baka](http://bakamplayer.u8sand.net/) or [bomi](https://bomi-player.github.io/), hitting `tab` key will show informations about video on screen.
these informations include

0. file name
0. file title
0. file video encoding
0. whether hardware acceleration is enabled.
0. ...

this is a very useful feature imho. for example, i personally badly want informations displayed on scrren about file video encoding and whether hardware acceleration is enabled .

**Comment by haasn** [comment]
How about something like this? https://github.com/Argon-/mpv-stats

**Comment by redhatlinux10** [comment]
@haasn very nice script ! and i have a question, can this script display informations about whether hardware acceleration is enabled ?

**Comment by kevmitch** [comment]
>whether hardware acceleration is enabled ?

untested, but you could add something like something 

    append_property(s, "video", "hwdec", "HW Decoding:")

in the ```add_video``` function

**Comment by haasn** [comment]
On my end, turning on VDPAU makes it say “pixel format: vdpau” instead of “pixel format: yuv420p” or whatever. Maybe that's enough for you?

**Comment by redhatlinux10** [comment]
@kevmitch @haasn thanks for your replies. all works for me. but @kevmitch 's answer is a better one i think.

**Comment by wm4** [comment]
Note that ``hwdec`` changed its meaning recently, and you want ``hwdec-active`` in newer mpv versions.

**Comment by redhatlinux10** [comment]
i just read the script, and can not find a way to accomplish my request:
hitting `tab` will display these informations and these informations will not disappear until i hit `tab` again.
is there any solutions ?

**Comment by redhatlinux10** [comment]
it seems there is no mpv lua api to erase what i just displayed on screen via `osd_message` api.

**Comment by ntasos** [comment]
@redhatlinux10   I had the same issue as you, the solution I found is to display on osd level 2 this:
https://gist.github.com/ntasos/a2d56a5d405b89728fc9
and use tab to switch between osd level 2 / 1.
It is  messy but it works.

**Comment by kevmitch** [comment]
You could change it so that instead of displaying once, the keybinding toggles a timer that continuously redisplays for a short duration.
