### ISSUE TITLE
Audio/Video desynchronisation

### ISSUE THREAD

**Issue by t4n017** [mpv-player/mpv#2108]
Hi,
I started using mpv as an *IP TV player* and when cache drops to 0, after buffering the a/v isn't synchronized anymore. Is any way to re-sync it automatically?, or at least manually? Otherwise I have to quit and start from zero.

Given that the server where I'm streaming from isn't really stable I increased the **cache-secs** to have more chance of the server filling the cache before it gets empty.

By the way, is ok that the cache meter in KB doesn't increase?, only the one in 'secs' does.
I would like to start playing only when cache is filled but **--cache-initial** doesn't work, I guess it's because of the KB metter not working, would it be possible of a **--cache-initial-secs**?

Thanks in advance for this great player!

**Comment by wm4** [comment]
What protocol are you using?

**Comment by t4n017** [comment]
HTTP, this is the server: http://live-edge01.telecentro.net.ar

**Comment by wm4** [comment]
```
$ mpv http://live-edge01.telecentro.net.ar/
Playing: http://live-edge01.telecentro.net.ar/
Failed to recognize file format.
```

Doesn't work. This is probably not the exact URL?

Also, there are many streaming protocols that use HTTP.

**Comment by t4n017** [comment]
Sorry, here is the complete URL of one of the TV channel streamed by that server: http://live-edge01.telecentro.net.ar/live/tlfhd-720/playlist.m3u8

At this time server speed and stability is really good so I'm not having any a/v problem because cache is easily filled, and you probably won't either. But if cache gets empty, after buffering a/v get desynced.

**Comment by wm4** [comment]
OK, so it's HLS. FFmpeg's HLS support works around the mpv stream cache. Only the playlist file goes through the cache (i.e. pretty tiny and useless), while the actual media data goes through http connections opened by FFmpeg itself.

I don't know why it would desync without recovering; you could try the experimental ``drop_buffers`` command whether it helps a little.

**Comment by t4n017** [comment]
Ok, I'll try **drop_buffers** when it happens again, I need to bind it to a key no?

What about the **--cache-initial** in secs?
I'm currently using **--pause** and manually playing after cache (in seconds) is filled, but an automatic option would be great.

**Comment by wm4** [comment]
> I need to bind it to a key no?

Yes.

>What about the --cache-initial in secs?

There is no such thing. mpv pauses automatically ("Buffering") when there's an underrun. There shouldn't be a desync, at least not a huge one - maybe the HLS demuxer is actually dropping segments, though.

**Comment by t4n017** [comment]
**drop_buffers** worked, thanks!

**Comment by t4n017** [comment]
@wm4 Just found that the server also allows RTSP and it seems to work better.
But I guess RTSP doesn't allow caching, no? How can I cache the streaming at least 10 secs? I would prefer some delay rather than "stuttering" ..
