### ISSUE TITLE
vaapi output with scaling=hq errors in proportions on panscan

### ISSUE THREAD

**Issue by TiGR** [mpv-player/mpv#2109]
Here is commandline to reproduce (assumed you have intel gfx configured):

    mpv some720pvideo --hwdec=vaapi --vo=vaapi:scaling=hq --geometry=1280x640

Now, as you change pan & scan (using keys w and e), the image is not just zooms in/out proportionally, it does zoom, but also image get misplaced, or get proportions wrong. You can see it in this video:

https://www.youtube.com/watch?v=wz5ARpE1WOY

```
$ mpv --version
mpv 0.9.2 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-05-23T16:18:03
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100

$ uname -a
Linux lenovo-g570 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

**Comment by TiGR** [comment]
If you just remove `:scaling=hq` from the commandline it behaves as it should.

**Comment by wm4** [comment]
>If you just remove :scaling=hq from the commandline it behaves as it should.

Then don't use it. Sounds like a 100% driver problem.

**Comment by TiGR** [comment]
> Then don't use it.

Well, the quality it gives is much better than what can be achieved with other methods (such as `--vo=opengl:scale=spline64`) and it won't load GFX card so that it gets heated way too much (esp. when scaling 480p video to 1080p screen).

> Sounds like a 100% driver problem.

Okay, upgraded kernel to 3.19 and the behavior has changed (but still bogus): https://youtu.be/I1nEA_fA7IA

If this is not mpv bug, could you, please, point me into direction where I should report this?

**Comment by wm4** [comment]
>Well, the quality it gives is much better than what can be achieved with other methods (such as --vo=opengl:scale=spline64) 

I really doubt it.

>and it won't load GFX card so that it gets heated way too much (esp. when scaling 480p video to 1080p screen).

Sounds possible - the GPU could just use special circuity or whatever else, while we have to use portable GLSL.

>If this is not mpv bug, could you, please, point me into direction where I should report this?

If it works with hq scaling off, it must be a GPU bug, since we don't change anything about the positioning depending on panscan.

I think Intel bugs are reported on https://bugs.freedesktop.org against Mesa or vaapi or whatever it lets you select.

**Comment by wm4** [comment]
>it must be a GPU bug

Or driver bug. They probably got cropping wrong somewhere.

**Comment by TiGR** [comment]
> I really doubt it.

I was surprized too: http://imgur.com/a/LJVXz. The quality is the same or better (or in some cases much better).

**Comment by Gusar321** [comment]
I did a scaling test as well, 720x404 to 1440x810 (to fit my 1440x900 display):

opengl:scale=spline64: http://www.imagebam.com/image/9622cb420027694
opengl-hq: http://www.imagebam.com/image/04a39e420027710
vaapi:scaling=hq: http://www.imagebam.com/image/ef92fa420027739

Ignoring the offset with vaapi, I can't tell a difference between those three. Comparing the filesizes of those pngs is also interesting, opengl-hq is a bit bigger.

Regular vaapi, very noticeably blurrier: http://www.imagebam.com/image/5b8aa7420027754

And turbostat results showing power consumption: http://pastebin.ca/3048607 <- vaapi's hg scaling is basically free

**Comment by TiGR** [comment]
Well, I've created [bug report](https://bugs.freedesktop.org/show_bug.cgi?id=91241) at libva bugzilla a while ago, but it doesn't seem to get noticed. Maybe if you could, please, drop in few technical details it would speed things up? Thanks.

**Comment by wm4** [comment]
Specifically, it happens with vaPutSurface if you pass VA_FILTER_SCALING_HQ to it, and the source coordinates don't use the full image (i.e. cropping).

**Comment by wm4** [comment]
Closing, because only Intel can fix this.

**Comment by TiGR** [comment]
@wm4 I found out one very interesting thing: If i run mpv as `mpv --hw-dec=no --vo=vaapi:scaling=hq`, that is, using hq hardware scaling, but disable hardware decoding - panscan starts working pretty well. So, the error appears only if you use both hardware decoding and hq hardware scaling.

**Comment by wm4** [comment]
That's even more weird. From mpv's perspective, we use the vaapi API in exactly the same way with sw and hw decoding. (For sw decoding, hardware surfaces are created and the sw decoded image data is uploaded.)

**Comment by TiGR** [comment]
Okay, did a bit more research.If I use default or fast scaling (which seems to be the same) panscan works well, But the error is triggered not only by hq scaling, but also by nla one (these are different with nla being greatly superior on downscaling but losing a bit to hq on upscaling).

**Comment by TiGR** [comment]
Now it has became more interesting. I've found [a file](http://download.jw.org/files/media_video/6e/ivpro_E_1_r720P.mp4) that is being played as with fish-eye camera if hq scaling is enabled. [Here are screenshots of what it looks like compared to fast scaling](http://imgur.com/a/EUEgl).
