### ISSUE TITLE
Regarding the warning about ffmpeg versions

### ISSUE THREAD

**Issue by ghedo** [mpv-player/mpv#2110]
```
Warning: mpv was compiled against a different version of ffmpeg than the shared
library it is linked against. This can expose subtle ABI compatibility issues
and can lead to misbehavior and crashes.
```

Is it really needed? AFAICT ffmpeg has been fairly stable in terms of ABI in the recent releases, and every time a new ffmpeg version is uploaded to Debian the mpv package would need to be rebuilt to get rid of the message.

It's not really an important issue, but the warning can be annoying, and users might think there is something wrong even though there's a good chance that everything is ok. Maybe the version check can be changed to only check that the runtime version is not lower than the build version, or something like that.

**Comment by wm4** [comment]
Sure, have fun auditing all the code for ABI safety. In some cases, ABI safety was AFAIK explicitly ignored in mpv for Libav compatibility.

**Comment by ghedo** [comment]
> Sure, have fun auditing all the code for ABI safety

The upstream-tracker project already kinda does this, although it currently hasn't analyzed ffmpeg 2.6 and 2.7 yet http://upstream.rosalinux.ru/versions/ffmpeg.html

> In some cases, ABI safety was AFAIK explicitly ignored in mpv for Libav compatibility

The comment at https://github.com/mpv-player/mpv/blob/master/common/av_log.c#L231-235 talks about accessors that ffmpeg provides to keep ABI compatibility which are not used by mpv because libav doesn't have them, is that what you meant? I wonder if mpv could use those accessors when built against ffmpeg and provide some kind of compatibility layer when built against libav. This way the warning could be removed for ffmpeg builds, though hunting down where the accessors should be used would probably be a pain to do.

In any case Debian is going to move back to ffmpeg soonish, so it might make sense for us to use those accessors (and breaking libav compatibility) and remove the warning altogether (just thinking aloud here, even if we went this road it wouldn't really affect mpv upstream unless you wanted to drop libav compatibility as well).

**Comment by wm4** [comment]
>The upstream-tracker project already kinda does this, 

I meant mpv code.

>and provide some kind of compatibility layer when built against libav. T

We already have enough compatibility layer nonsense.
