### ISSUE TITLE
Shapes not displayed (vector graphics)

### ISSUE THREAD

**Issue by Kagurame** [mpv-player/mpv#2114]
In mpv, shapes from ass files are not displayed.

I'm using ass iclip and ass p command to create pattered lines, but the shapes are not displayed.

Here a example:
How it should look: http://img5.fotos-hochladen.net/uploads/bildschirmfotou48lj3x5yt.png
How it look using mpv: http://img5.fotos-hochladen.net/uploads/bildschirmfotovbza4wdh5t.png

ASS file (and video, raw and windows encoded example video) you can find here:
https://www.dropbox.com/sh/mqtkeuyqeqnrkkp/AAD3BouLP8D-aebIObQ-VbgPa?dl=0

Im using ubuntu 14.04 and mpv in current version for it.

**Comment by wm4** [comment]
Both vlc and mpv use libass. Your mpv/vlc builds are probably using different releases of it.

**Comment by wm4** [comment]
>Im using ubuntu 14.04 and mpv in current version for it.

And that mpv version is ancient. Please stop using it and write hate mail to Ubuntu.

**Comment by kevmitch** [comment]
> write hate mail to Ubuntu.

good luck with that, they still refuse to even fix their one line packaging mistake that breaks lua support.

**Comment by Kagurame** [comment]
Aegisub is using libass too and it display it properly. Please tell me how to update correctly to use a correct version of mpv.

**Comment by qyot27** [comment]
One of the following:
1) Rebuild the components yourself (libass-git, ffmpeg-git, mpv-git)
2) Use either mc3man's [trusty-media PPA](https://launchpad.net/~mc3man/+archive/ubuntu/trusty-media) or [djcj's vapoursynth PPA](https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth).
3) Switch to the 6-month Ubuntu release cycle and use 15.05.
