### ISSUE TITLE
An issue using VDPAUPP.

### ISSUE THREAD

**Issue by Entheogen010** [mpv-player/mpv#2115]
Hello, I have encountered an issue using VDPAUPP.

In mpv.conf, I have set:
```
vo=vdpau:output_surfaces=15:queuetime_fs=1500
vf=vdpaupp:hqscaling=1
hwdec=vdpau
```
When I try to play a video, I receive the following error: 
```
mpv: ../video/mp_image.c:244: mp_image_new_custom_ref: Assertion `!img->bufs[0]' failed.
Aborted (core dumped)
```

If I remove `vf=vdpaupp:hqscaling=1` from my config, this goes away, and the video plays just fine.

Relevant information:
OS: Ubuntu 14.04 LTS 64bit
Graphics Card/Driver: NVIDIA 670M/proprietary 331.113
mpv version:
```
mpv git-daf32e2 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Tue Jul  7 04:52:05 UTC 2015
ffmpeg library versions:
   libavutil       54.28.100
   libavcodec      56.46.101
   libavformat     56.40.100
   libswscale      3.1.101
   libavfilter     5.20.100
   libswresample   1.2.100
```

What can be done (can I do) to solve this?

**Comment by wm4** [comment]
Will fix this tomorrow.

**Comment by Entheogen010** [comment]
Thanks.
