### ISSUE TITLE
Option to choose resolution while playing m3u8?

### ISSUE THREAD

**Issue by fb39ca4** [mpv-player/mpv#2116]
I've got a URL to an m3u8 file I want to play, which contains URLs to more m3u8s for different resolutions of a video. I want to be able to choose the resolution rather than defaulting to the highest one. I can't just download the main m3u8, get the URL to the desired resolution-specific one, and pass that to mpv, because a cookie set by downloading the main m3u8 is needed when downloading the other files, otherwise the server gives a 403 error. (I am using mpv with --cookies)

**Comment by wm4** [comment]
You can use ``--hls-bitrate`` or whatever it was.

**Comment by fb39ca4** [comment]
That only seems to allow selecting the best or the worst quality. How difficult would it be to add an option to specify a numeric bitrate and select the closest one?

**Comment by wm4** [comment]
Do you have an URL that would make a good test case?

**Comment by fb39ca4** [comment]
I've been trying to play videos from daisuki.net using mpv. The URLs for the m3u8s will expire quickly, however, so you may get a 403 Forbidden if you try to go to it.

https://bngn-vh.akamaihd.net/i/43383936/35470338/smil/US/00007/188376541795236.smil/master.m3u8?hdnea=st=1436573677~exp=1436573977~acl=/*~hmac=9141b2710b62f0a51f7fc77da65014c77763b7de398e66b55c912fe3f3e2dbca

Contents of the m3u8:

    #EXTM3U
    #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=995000,RESOLUTION=640x360,CODECS="avc1.66.30, mp4a.40.2"
    https://bngn-vh.akamaihd.net/i/43383936/35470338/smil/US/00007/188376541795236.smil/index_1000000_av.m3u8?null=&id=AgBJKvDOF9Q7BUpgoFV7P%2fpBsDRuvySJtbP81ReMW%2f%2fhIaNeSwraR6NZsmsuGWHMSDBw9qeSZV7UXg%3d%3d
    #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1993000,RESOLUTION=852x480,CODECS="avc1.77.30, mp4a.40.2"
    https://bngn-vh.akamaihd.net/i/43383936/35470338/smil/US/00007/188376541795236.smil/index_2000000_av.m3u8?null=&id=AgBJKvDOF9Q7BUpgoFV7P%2fpBsDRuvySJtbP81ReMW%2f%2fhIaNeSwraR6NZsmsuGWHMSDBw9qeSZV7UXg%3d%3d
    #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=3478000,RESOLUTION=1280x720,CODECS="avc1.77.30, mp4a.40.2"
    https://bngn-vh.akamaihd.net/i/43383936/35470338/smil/US/00007/188376541795236.smil/index_4000000_av.m3u8?null=&id=AgBJKvDOF9Q7BUpgoFV7P%2fpBsDRuvySJtbP81ReMW%2f%2fhIaNeSwraR6NZsmsuGWHMSDBw9qeSZV7UXg%3d%3d
    #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=5232000,RESOLUTION=1920x1080,CODECS="avc1.640029, mp4a.40.2"
    https://bngn-vh.akamaihd.net/i/43383936/35470338/smil/US/00007/188376541795236.smil/index_6000000_av.m3u8?null=&id=AgBJKvDOF9Q7BUpgoFV7P%2fpBsDRuvySJtbP81ReMW%2f%2fhIaNeSwraR6NZsmsuGWHMSDBw9qeSZV7UXg%3d%3d

**Comment by wm4** [comment]
Well, do you have a m3u8 that's more persistent? I just want to use it for testing without having to go through extra effort.

**Comment by fb39ca4** [comment]
Sorry, I don't at the moment.

**Comment by brickleroux** [comment]
I'm also struggling with this problem. I've tried to add a keybinding for `cycle program` but this works not very reliable especially for live streams (the streams often freeze or crash). It would be great if you could add an option for choosing the quality.

For testing:
`http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8` 
or NASA live stream: 
`http://nasatv-lh.akamaihd.net/i/NASA_101@319270/master.m3u8`
