### ISSUE TITLE
Any hardware acceleration for vp9 video?

### ISSUE THREAD

**Issue by starkshaw** [mpv-player/mpv#2118]
I'm using mpv on MacBook Pro 13’ (2015, OS X 10.10.4), I found it will frame dropping significantly when I watching 4K video merged in Matroska (video: vp9, audio: aac). Then I used `--hwc=vda -vo=corevideo` in mpv.conf, I still found no difference, I use log mode then I searched this in log:

`[   0.101][v][vd] Not trying to use hardware decoding: codec vp9 is not on whitelist, or does not support hardware acceleration.`

After this it used Google VP9 as video decoder. I'm wondering if there is a way to use hardware acceleration on VP9 video?

**Comment by pigoz** [comment]
Anyway VDA on OS X only supports acceleration of H264 videos. Maybe in the future Apple will add HEVC support, but I'd say VP9 is very unlikely.

PS: `--vo=corevideo` is no longer present in mpv btw
