### ISSUE TITLE
a way to control the requested subtitles from youtube-dl

### ISSUE THREAD

**Issue by remitamine** [mpv-player/mpv#2119]
when i play video from videos(like in ted.com) that have a lot of subtitles it takes some time to get all the subtitles before playing the video.
i try to add this option to limit the languages requested by youtube-dl in the config file:
ytdl-raw-options=sub-lang="en,ar"
but it didn't work because in the ytdl_hook.lua there is this line that contain the --all-subs option:
```lua
local command = {
            ytdl.path, "--no-warnings", "-J", "--flat-playlist", "--all-subs",
            "--sub-format", subformat, "--no-playlist"
        }
```

**Comment by lachs0r** [comment]
Maybe the ytdl hook should just use the value of the `slang` option and only pass `--all-subs` if it’s unset?

**Comment by remitamine** [comment]
i think it's also good to have the option to not get the subtitles at all because some times your watching most of the videos in a language that you understand so it's just a wast of time to get the subtitles.
