### ISSUE TITLE
Which hardware acceleration is better, vaapi or vaapi-copy?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2122]
Which one should I choose?

**Comment by wm4** [comment]
I really don't know. In theory ``vaapi``, but in theory ``vaapi-copy`` could also avoid some overhead in the OpenGL interop.

**Comment by laichiaheng** [comment]
Does the interpolation work in vaapi mode?

**Comment by wm4** [comment]
If you mean vo_opengl's, yes.

**Comment by laichiaheng** [comment]
@wm4 Thanks again!
Another question, should I turn on interpolation when my video is 30 or 60 fps?

**Comment by wm4** [comment]
Whenever it looks better to you.
