### ISSUE TITLE
Ghosting when framestepping forward with interpolation

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#2127]
When framestepping forward with interpolation active, the ghost of the previous/following frame appears on screen for a split second. Framestepping backwards works as expected. 
I managed to reproduce the issue with several tscale's values, including deafult oversample.

I'm using the latest git master on Os X 10.10.4. 
My VO config: `vo=opengl-hq:blend-subtitles:icc-profile-auto:icc-cache-dir=~~/cache:source-shader=~~/shaders/deband.glsl:interpolation`

**Comment by wm4** [comment]
This is known. Ping @haasn.

**Comment by haasn** [comment]
Seems to have solved itself with the changes to the interpolation code in the meantime.
