### ISSUE TITLE
Add ReplayGain support for MKV files

### ISSUE THREAD

**Issue by Shenj** [mpv-player/mpv#2128]
MKV has REPLAYGAIN_GAIN and REPLAYGAIN_PEAK tags http://matroska.org/technical/specs/tagging/index.html#REPLAYGAIN_GAIN but MPV doesn't support it, it would be great if MPV would implement it.

**Comment by wm4** [comment]
It's likely that mpv already picks up these tags, but it depends. Do you have a sample file?

**Comment by Shenj** [comment]
From what i'm seeing on the Source there isn't actually a single reference to these 2 tags.

Eitherway here I have 3 files, one is tagged via Foobar2000, one has no tags and one is tagged via mkvtoolnix the same way Foobar2000 tags but isn't detected in Foobar2000, please note the MKA is tagged, not the audio but also when tagging the Audio and then muxing it into a MKA container it doesn't work either while the FLAC directly works.

The tagged files should playback at -30 dB but only the Flac with tags work in MPV for me.

[Original](https://drive.google.com/file/d/0B54I3wcV0tTTZmFDcGFCdW1nZkk/edit?usp=drivesdk)
[mkvtoolnix tagged](https://drive.google.com/file/d/0B54I3wcV0tTTTGpfN2E1R29YNFk/edit?usp=drivesdk)
[Foobar2000]( https://drive.google.com/file/d/0B54I3wcV0tTTdDRGUkp4cWZlWTQ/edit?usp=drivesdk)
[FLAC with tags](https://drive.google.com/file/d/0B54I3wcV0tTTazRGVnZRMzFLSFk/edit?usp=drivesdk)

I noticed though that the matroska spec wants data in a different way than the ReplayGain rec has intended which isn't a smart way of implementing other specs into the format but while REPLAYGAIN_GAIN/PEAK seem ok as MKV/MKA don't really need the original tag but REPLAYGAIN_GAIN is expected to be a Binary value according to the matroska spec but that's not MPV's fault.

MetaData | Key | Value format
----------- | ---- | ---------------
Track replay gain | REPLAYGAIN_TRACK_GAIN | [-]a.bb dB  
Peak track amplitude | REPLAYGAIN_TRACK_PEAK | .dddddd  
Album replay gain | REPLAYGAIN_ALBUM_GAIN | [-]a.bb dB  
Peak album amplitude | REPLAYGAIN_ALBUM_PEAK | c.dddddd

So MKV/MKA should actually be tagged like this for a bettery uniform formatting across implementations.

MetaData | Key | Value format
----------- | ---- | ---------------
ReplayGain | REPLAYGAIN_GAIN | [-]a.bb dB  
Peak amplitude | REPLAYGAIN_PEAK | .dddddd  

And not like this

MetaData | Key | Value format
----------- | ---- | ---------------
ReplayGain | REPLAYGAIN_GAIN | Binary 
Peak amplitude | REPLAYGAIN_PEAK | Binary

The only player i have that can actually write/detect the REPLAYGAIN_GAIN tag is Foobar2000 but it doesn't play video and seems to write a little bit different compared to mkvtoolnix.


So for the mkvtoolnix file i used the following XML to align with what should really be there, i also have the binary version but i don't know if this is really how matroska was intending it as it seems over complicating when one could use a string to achieve the same.
````
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Tags SYSTEM "matroskatags.dtd">
<Tags>
  <Tag>
    </Targets>
    <Simple>
      <Name>REPLAYGAIN_GAIN</Name>
      <String>-30 dB</String>
    </Simple>
    <Simple>
      <Name>REPLAYGAIN_PEAK</Name>
      <String>1.000000</String>
    </Simple>
  </Tag>
</Tags>
````

````
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Tags SYSTEM "matroskatags.dtd">
<Tags>
  <Tag>
    </Targets>
    <Simple>
      <Name>REPLAYGAIN_GAIN</Name>
      <Binary>LTMwIGRC</Binary>
    </Simple>
    <Simple>
      <Name>REPLAYGAIN_PEAK</Name>
      <Binary>MS4wMDAwMDA=</Binary>
    </Simple>
  </Tag>
</Tags>
````

**Comment by wm4** [comment]
Your flac in mka file has the tags in the FLAC extradata. This must be a fucking joke. Whoever thought that was a good idea belongs in prison.

**Comment by wm4** [comment]
Oh, that was WarmNoiseWithRGOnFlac.mka, while WarmNoiseFoobar2000Tagged.mka actually has Matroska tags.

**Comment by wm4** [comment]
So I just changed it to grab those tags. The reality seems to be a bit more complicated (Matroska tags can be organized in a certain way to separate track and album tags apparently), but since I don't know what this looks like, there's no support for this.

**Comment by wm4** [comment]
>The reality seems to be a bit more complicated (Matroska tags can be organized in a certain way to separate track and album tags apparently),

PS: if you want to look into it, the ``TargetTypeValue`` determines this.

**Comment by Shenj** [comment]
I will check this out once there is new build for windows with this change.

Im not really sure how useful TargetTypeValue would be for intended use case but here for example i would apply replaygain to Track 2 and one to Track 3 (maybe track 1 is video, track 2/3 are audio) and ideally MPV would understand that but if it's too hard to implement then there is probably no reason to, im not sure if the formatting is correct also i don't think there is actually any support in any player for this, foobar/vlc only understand a global tag for it.
 
````
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Tags SYSTEM "matroskatags.dtd">
<Tags>
  <Tag>
    <Targets>
      <TrackUID>2</TrackUID>
    </Targets>
    <Simple>
      <Name>REPLAYGAIN_GAIN</Name>
      <String>-30 dB</String>
    </Simple>
    <Simple>
      <Name>REPLAYGAIN_PEAK</Name>
      <String>1.000000</String>
    </Simple>
  </Tag>
  <Tag>
    <Targets>
      <TrackUID>3</TrackUID>
    </Targets>
    <Simple>
      <Name>REPLAYGAIN_GAIN</Name>
      <String>-30 dB</String>
    </Simple>
    <Simple>
      <Name>REPLAYGAIN_PEAK</Name>
      <String>1.000000</String>
    </Simple>
  </Tag>
</Tags>
````

**Comment by wm4** [comment]
This doesn't have to do with multi-track files. It's an additional concept.

mpv for one also only uses global tags for replaygain.
