### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by gsklee** [mpv-player/mpv#2130]
I'm using mpv on Mac and I can't find a way to open the preferences window of mpv. How do I open it, or does it exist at all?

(Tried to ask this question through mpv-users@googlegroups.com at first but the email no longer works.)

**Comment by wm4** [comment]
>or does it exist at all?

It doesn't exist.

>(Tried to ask this question through mpv-users@googlegroups.com at first but the email no longer works.)

We disabled it today, because it was never used much.

**Comment by gsklee** [comment]
Okay, cool.
