### ISSUE TITLE
Update the image from mpv site and update to libass 0.12.3. OSX build

### ISSUE THREAD

**Issue by Morecutter** [mpv-player/mpv#2131]
The image from the mpv website is very old. From OSX 10.9. This is not good.

And update the build for mpv OSX to libass 012.3 thx

**Comment by wm4** [comment]
What image?

**Comment by wm4** [comment]
And which build?

**Comment by Morecutter** [comment]
This image http://mpv.io/
See old window from OSX 10.9. Very terrible. Please update.


http://sva.wakku.to/~chris/mpv_builds/

**Comment by wm4** [comment]
Right, we wanted to select a new image for the website, some users posted suggestions, but then I forgot about it. Well, who cares if the screenshot is slightly outdated?

**Comment by droukd** [comment]
Love it.
:D
>ghost\boxcutter

I look around this room, and i see alot of courage.
And that gives me strength.
