### ISSUE TITLE
vdr: /usr/lib64/libmpv.so.1: undefined symbol: cmsGetContextUserData

### ISSUE THREAD

**Issue by pery69** [mpv-player/mpv#2133]
libmpv returns an error while starting vdr-mpv plugin "http://projects.vdr-developer.org/projects/plg-mpv" 

vdr: /usr/lib64/libmpv.so.1: undefined symbol: cmsGetContextUserData

VDR 2.0.6 Opensuse 13.1

**Comment by mc4man** [comment]
don't use Opensuse but i'd check what version of lcms (lcms2) is being used. symbol is in lcms2 here debian/ubuntu - 
cmsGetContextUserData@Base 2.6

**Comment by wm4** [comment]
This must be some problem with the build or the installation. Report to the vdr devs.

There's also a probability that mpv's .pc file doesn't list lcms2 correctly, but last I checked it did.

**Comment by pery69** [comment]
Thanks for the hint. I've found the solution. Just had to update lcms2 to the latest version and everything worked.
