### ISSUE TITLE
"Users Mailing List" and "Devel Mailing List" links don't work

### ISSUE THREAD

**Issue by cubuspl42** [mpv-player/mpv#2135]
The error is `There is no group named “mpv-users”.`

**Comment by wm4** [comment]
We removed these mailing lists, because they weren't very frequently used. Maybe we should have sent an announcement before deleting them, but when I remembered, it was too late.

The links are gone from the homepage. Where did we forget to remove these links?

**Comment by cubuspl42** [comment]
README.md

**Comment by wm4** [comment]
Thanks.
