### ISSUE TITLE
MPV fails to start in gnome wayland session using Archlinux

### ISSUE THREAD

**Issue by Xenphor** [mpv-player/mpv#2136]
Here is the log:

http://pastebin.com/aUjv6m1Q
short version:

    $ mpv Taylor\ Swift\ -\ Bad\ Blood\ ft.\ Kendrick\ Lamar-QcIy9NiNbmo.mkv 
    Playing: Taylor Swift - Bad Blood ft. Kendrick Lamar-QcIy9NiNbmo.mkv
     (+) Video --vid=1 (vp9)
     (+) Audio --aid=1 (*) (aac)
    wl_surface@3: error 0: Cannot commit a NULL buffer to an xdg_surface
    Using software decoding.
    [vo/opengl/wayland] error occurred on the display fd: closing file descriptor
    AO: [pulse] 44100Hz stereo 2ch float

Using vo=opengl hwdec=vaapi

**Comment by wm4** [comment]
No idea. Something strange fails at an unknown location?

> hwdec=vaapi

This won't work at all on Wayland.

**Comment by kasei-wang** [comment]
hey, try "--vo=x11".
It works on my Archlinux.

**Comment by rickysarraf** [comment]
Yes. -vo=x11 works. But is wayland as a '-vo' supported ?

**Comment by ricardomv** [comment]
I think this is fixed in 3.18.2 at least i don't have this issue anymore.

**Comment by giselher** [comment]
Can't reproduce this issue. Is there any new information?

**Comment by Manouchehri** [comment]
Using `-vo wayland` was working for me several months ago, haven't been able to reproduce this in Wayland.

**Comment by giselher** [comment]
I am closing this issue, feel free to reopen it again if it still happens.
