### ISSUE TITLE
vdpau video broken when resuming from lock screen

### ISSUE THREAD

**Issue by hrzhu** [mpv-player/mpv#2139]
It only happens when I use vdpau hwdec so I don't know it's mpv or driver's issue.
Looks like this:
![mpv](https://cloud.githubusercontent.com/assets/2360542/8666404/5d8d6f80-2a23-11e5-87bf-f1fa173de7bb.png)
There is an error message in console: `[vo/opengl-hq/vdpau] Error when calling vdp_video_surface_get_parameters: An invalid handle value was provided`. And I can't use the built-in screenshot in mpv at that time.
My DE is Xfce  4.12. By lock sreen I mean `xflock4`.  mpv config is vo=opengl-hq hwdec=auto

**Comment by hrzhu** [comment]
With vdpau vo and vdpau hwdec, the video become all black when resuming from lock screen.
error messages:
`[vo/vdpau] Error when calling vdp_presentation_queue_block_until_surface_idle: The display was pre-empted, or a fatal error occurred.`
`[vo/vdpau] Error when calling vdp_video_mixer_render: An invalid handle value was provided.`

**Comment by wm4** [comment]
This is not just "blurred", it shows a completely corrupted image.

This is normal for vdpau. The display can become "pre-empted", and then it loses all its state. Normally mpv should recover after a while, but sometimes it doesn't work.

**Comment by Akemi** [comment]
if this problem still persists, please open a new issue.
