### ISSUE TITLE
Option to load external fonts?

### ISSUE THREAD

**Issue by fb39ca4** [mpv-player/mpv#2140]
Would it be possible to load external fonts from individual font files? I have a subtitle script that was originally in an MKV with embedded fonts, but I want to use the subtitles and fonts demuxed.

**Comment by wm4** [comment]
Currently not possible.

**Comment by lachs0r** [comment]
Well, you could use a custom fonts.conf that loads an additional directory, 
but that only works if libass was built with fontconfig, and I would not 
recommend it.

You could also use e.g. Aegisub to attach the fonts to the script file itself 
if it’s ASS. Just don’t distribute such files; it’s generally frowned upon.

**Comment by fb39ca4** [comment]
I found another option - mux the subtitles and fonts into a Matroska file using mkvtoolnix.
