### ISSUE TITLE
proper shuffling of files from directory

### ISSUE THREAD

**Issue by shanky061** [mpv-player/mpv#2141]
currently when i run `mpv * --shuffle`  when current directory structure is like
```
cur_dir/
--------->dir1
             ---->song1.mp3
             ---->song2.mp3
             ---->song3.mp3
--------->dir2
             ---->song4.mp3
             ---->song5.mp3
             ---->song6.mp3
--------->song7.mp3
```
mpv shuffles song in groups like (order could be different)
* all shuffled songs from dir2 played first
* song7.mp3 played after that
* all shuffled songs from dir1 played last

I mean it kind of shuffles locally. Wouldn't it be better if mpv shuffles globally like first make list of all files in directory and then plays them randomly.

**Comment by wm4** [comment]
This is because directories are read incrementally. I don't intend to change this. Use something like ``mpv */*``, or a shell which can glob recursively.

**Comment by shanky061** [comment]
Thanks `mpv */*` worked.
