### ISSUE TITLE
mpv drops frames like crazy because of borked metadata

### ISSUE THREAD

**Issue by Q3CPMA** [mpv-player/mpv#2143]
I'm trying to watch an episode of Gamecenter CX (there must be a text encoding fuckup somewhere) with the following tags:
>File tags:
> Comment: irQ[^[LìWÆ(æ) Tvt@~R¢ãà¤Ȃɂ̃Q[oGeBuQ[Z^[CXvæ8V[YªX^[gILìے·ªt@~RȂǉ򩂵¢Q[̃GfBOðڎw·uLì̒§ívAS·܂élCR[i[u½܂ɂ¢­炱ñȃQ[Z^[vɉÁ¦AVR[i[àoê\èB¨yµ݂ɁI
> Genre: Game
> Title: Q[Z^[CX #56 utVMȗmQ[ĂсcutbVobNvv

And mpv drops a lot of frames. Using `--no-osc` solve the problem. Using `--msg-level=all=trace` gives us a lot of
>[osd/libass] Glyph 0x83 not found, selecting one more font for (sans-serif, 80, 0)
>[osd/libass] Glyph 0x81 not found, selecting one more font for (sans-serif, 80, 0)
>[osd/libass] Glyph 0x83 not found, selecting one more font for (sans-serif, 80, 0)
>[osd/libass] Glyph 0x80 not found, selecting one more font for (sans-serif, 80, 0)
>[osd/libass] Glyph 0x83 not found, selecting one more font for (sans-serif, 80, 0)
>[osd/libass] Glyph 0x83 not found, selecting one more font for (sans-serif, 80, 0)
>[osd/libass] Glyph 0x93 not found, selecting one more font for (sans-serif, 80, 0)
>[osd/libass] Glyph 0x83 not found, selecting one more font for (sans-serif, 80, 0)
>[osd/libass] Glyph 0x81 not found, selecting one more font for (sans-serif, 80, 0)

Isn't there a less performance costly way of dealing with messy metadata?

**Comment by shdown** [comment]
It's just that fontconfig searches for a glyph through all fonts installed every time. IIRC the problem is known, the same for subtitles with symbols you don't have fonts for.

**Comment by Q3CPMA** [comment]
Well, I installed japanese fonts, but it still doesn't work. There should be way to avoid having to play a video without the OSC.

**Comment by wm4** [comment]
Does this happen even if the OSC is invisible?

**Comment by shdown** [comment]
> Well, I installed japanese fonts, but it still doesn't work

The characters from your post are just random nonsense, not Japanese.

Also, I don't actually know whether the problem is in fontconfig or in libass.

**Comment by Q3CPMA** [comment]
Yeah, it happens even if the OSC is invisible.

**Comment by wm4** [comment]
>Yeah, it happens even if the OSC is invisible.

This really shouldn't happen. Can you post such a file so I can investigate this?

Other than that, it's pretty much a libass issue. I think libass will try to render the broken glyphs every frame, otherwise it wouldn't matter if fontconfig is slow here.

**Comment by Q3CPMA** [comment]
Sure, https://d.maxfile.ro/nzokpzwtfs.avi

**Comment by wm4** [comment]
I don't get dropped frame when the OSC is not visible.

**Comment by Q3CPMA** [comment]
Me neither. I must have dreamt this. Sorry.

**Comment by wm4** [comment]
Nothing mpv can do about, at least not really.

Reported to libass as: https://github.com/libass/libass/issues/186
