### ISSUE TITLE
Correcting color level mastering mastering mistakes.

### ISSUE THREAD

**Issue by kevmitch** [mpv-player/mpv#2145]
I've rented a blu ray copy of Margin Call only to find that the colorlevels seem to be off as evidenced most obviously by the grey background of the end credits:

![Margin Call screenshot](https://dl.dropboxusercontent.com/u/60598588/Margin_Call_t00.mkv.01%3A43%3A12.019.jpg)

Apparently this is a [known mastering error](http://www.avsforum.com/forum/150-blu-ray-software/1496542-blu-rays-incorrectly-encoded-rgb-pc-levels.html).

Indeed, if I take a sample of ```--vo=image:format=pgmyuv``` from throughout the film, and plot the histogram, I get the following:

![Margin Call Histogram](https://dl.dropboxusercontent.com/u/60598588/margin_call.png)

Note how the frequency of the luma drops off sharply below 29 and above 209 indicating that the image has been **doubly limited**.

Compare to It Follows, which looks correct:

![It Follows Histogram](https://dl.dropboxusercontent.com/u/60598588/it_follows.png)

So the question is, is there a way to correct for this on playback? I've tried messing around with the various permutations of ```--vf=format=colorlevels=x:outputlevel=y```, but they either have no effect, or make make the problem worse by further squeezing the range.

**Comment by kevmitch** [comment]
Ok, so I can tell my computer to output 0-255, and go into my TVs settings to lie that the incoming HDMI is 16-230, then it seems to do the trick, but the question remains if there's a way to get mpv to do this internally.

**Comment by haasn** [comment]
You can make mpv do a single round of TV->PC expansion, but not *two* rounds. (Maybe there's a way using some lavfi filter though)

Apart from that, the only way I can think of to specifically do double expansion like this would be using a pixel shader, eg. a pre-shader like this: (untested)

```
vec4 sample(sampler2D tex, vec2 pos, vec2 tex_size) {
    vec4 c = sample(tex, pos);
    return vec4((c.rgb - vec3(16.0/255)) * vec3(255.0/219), c.a);
}
```

**Comment by qyot27** [comment]
I can't tell if this is the same situation [I came across a couple years ago](http://www.animemusicvideos.org/forum/viewtopic.php?f=11&t=111837) when dealing with K-ON!!, as the AVSforum thread seems to go off on a tangent that sounds pretty similar to the cause of the issue I brought up there.

If it is the same thing I was seeing, the recommended fix was to manually specify the levels correction with the values given there, but that was for AviSynth.  I'd look to see if you can manage it with VapourSynth so the effect can be applied through mpv that way.

**Comment by wm4** [comment]
I think libavfilter's vf_lut can apply expressions on each color, and accelerates it with a LUT.

**Comment by kevmitch** [comment]
@haasn that seems to give me 

```
vo/opengl: fragment shader compile log (status=0):
vo/opengl: 0:20(11): error: no matching function for call to `sample(sampler2D, vec2)'; candidates are:
vo/opengl: 0:20(11): error:    vec4 sample(sampler2D, vec2, vec2)
vo/opengl: 
```

However, with actually knowing what I'm doing, replacing ```vec4 c = sample(tex, pos);``` with ```vec4 c = texture(tex, pos);```` seemed to do the trick. 

In any case, that's two ways of fixing it (though I didn't figure out how to use the lut yet), so I think this is solved.
