### ISSUE TITLE
"Hardware Deinterlacing" & "CoreAudio Exclusive Mode doesn't work over external DAC"

### ISSUE THREAD

**Issue by macdavis** [mpv-player/mpv#2146]
1. Just wondering whether hardware deinterlacing is supported in MPV (OS X platform)? My graphic card is Intel Iris Pro.

2. It seems CoreAudio Exclusive Mode doesn't work over my external USB DAC. It works with native audio device. No sound is produced if I use external DAC (Arce MDAC3) with a bridging device (Arce Mua1). Audio track can not be selected neither.

3. I'm really a rookie on computers. Since Metal is introduced in OS X 10.11. Is it possible to apply Metal on MPV for better performance? 

Thanks!

**Comment by wm4** [comment]
>Just wondering whether hardware deinterlacing is supported in MPV (OS X platform)? My graphic card is Intel Iris Pro.

I'm not aware of any hardware deinterlacers provided by the OSX API, although such deinterlacers exist on Linux and Windows.

>It seems CoreAudio Exclusive Mode doesn't work over my external USB DAC. It works with native audio device. No sound is produced if I use external DAC (Arce MDAC3) with a bridging device (Arce Mua1).

CoreAudio exclusive mode is pretty new in mpv, and tends to cause issues as well. Is the audio device set to 24 bit mode?

>Is it possible to apply Metal on MPV for better performance? 

No, at least not yet. Also, I doubt it has any advantages over OpenGL for mpv's use-case.
