### ISSUE TITLE
mpv RPATH problem

### ISSUE THREAD

**Issue by nerdouille** [mpv-player/mpv#2147]
Hi,

I'm building mpv on debian and I have libass in a local home directory. I've set PKG_CONFIG_PATH accordingly and mpv builds fine. However ldd shows the compiled binary can't find the libass.so.5 library even though I compiled with export RPATH=...libass/lib ?

Any tips? Thanks

EDIT: I know I can set LD_LIBRARY_PATH to ...libass/lib but I'd prefer the rpath way if possible

**Comment by wm4** [comment]
>even though I compiled with export RPATH=...libass/lib ?

Which build system interprets this? Anyway, I'm sure you can set the rpath by using CFLAGS or LDFLAGS or so.

**Comment by kevmitch** [comment]
If I'm reading [this](https://en.wikipedia.org/wiki/Rpath#The_role_of_GNU_ld) correctly, I believe the environment variable you're looking for is ```LD_RUN_PATH``` which is read by ld. Alternatively, you can add the ``` -rpath``` to LDFLAGS.

**Comment by nerdouille** [comment]
Yes I've also tried this, adding -rpath to LDFLAGS doesnt do anything. Also for exemple when I build rtorrent using PKG_CONFIG_PATH set to libtorrent's pkg-config, the produced binary is automatically linked to the proper .so file, no need to use the rpath thing. Is it intentionnally different with mpv?

**Comment by nerdouille** [comment]
Ah it works with LD_RUN_PATH thank you guys :)
