### ISSUE TITLE
Washed Colors with certains mp4

### ISSUE THREAD

**Issue by Cosmoufle** [mpv-player/mpv#2148]
Only with mpv, does I see the blacks that are grey with certain Avc I have done.
It does that with my mp4 that have those supplementary tags.

Color range                 : Full
Matrix coefficients         : SMPTE 240M

°°> It would seem that "color range full" would put to "0:255" range, but it display gray for blacks.

**Comment by kevmitch** [comment]
Well the question is are the tags accurate? What you describe will happen if you tag a file that is actually limited range as full range. If adding ```--vf=format=colorlevels=limited``` fixes it, then you need to fix the tags on the file.

**Comment by Cosmoufle** [comment]
yup, thanks, does the trick. °>°
I can't find a program that edit tags of mp4. (If you know one)
So I tried with hexedit, I can find the encoding options (options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3 etc...) but can't find those extra tags that put color range and matrix coefficients.

**Comment by ChrisK2** [comment]
The stuff you see are not actual video tags, only encoding options included for reference which have no effect on playback. The video-tags are in buried in the binary data. You can fix those with ffmpeg.

**Comment by Cosmoufle** [comment]
without reencoding the avc stream?
Searched, found a color_range option in ffmpeg, but not the full command to run.
°°> if you know or else, i'll let them as they are.

**Comment by wm4** [comment]
Can you post a sample file?

**Comment by Cosmoufle** [comment]
here ya go ^>^
https://app.box.com/s/h2hjnbpzqorkbwakxbqltm00fhs2ppyp

**Comment by wm4** [comment]
Can't see anything wrong with it. There don't seem to be any container-level tags or so which could possibly override bitstream flags (which is what I first suspected). This information:
```
Color range : Full
Matrix coefficients : SMPTE 240M
```
seems to be correct. It's of course possible that we don't handle this colorspace correctly, but I doubt it, so unless there's proof otherwise, this issue is cleared up for me.

**Comment by Cosmoufle** [comment]
Bad settings in the encoder ^^>, I just found that I have still the originals non compressed video files.
I'll have to reencode them °°>, this time I'll use avidemux that I have used for my files lastly, no problems with those.
