### ISSUE TITLE
Motion interpolation out of sync

### ISSUE THREAD

**Issue by morphological** [mpv-player/mpv#2149]
Hello1

I read about a member successfully getting 60FPS SVP like motion interpolation to work with vapoursynth and mpv https://github.com/mpv-player/mpv/issues/2057

I installed  vapoursynth, vapoursynth-extra-plugins and mpv compiled with vapoursynth from the source mentioned.  https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth

I am also using the 60FPS conversion script that was mentioned in that issue.
https://gist.github.com/ghedo/fe0d232bda81f15e838b

The interpolation works perfectly, and the video is very smooth, but after a minute or so the audio begins to get out of sync.

Whenever I scroll forward or back the video is in sync again, but after some time it gets out of sync.

I tried using additional filters and options, delaying the audio and commands like --autosync=4 --mc=0.  It all failed.

Could this be a problem with the script?

I also found an interpolation script from a member named haasn, but its not working.
The first one works with only minor interpolation noticable, but the one he say is updated, doesnt all.
https://github.com/mpv-player/mpv/issues/566

Any ideas?

**Comment by Cpuroast** [comment]
Any reason you aren't using the native interpolation support as in: "vo=opengl-hq:interpolation" instead of a custom VS script?

**Comment by Argon-** [comment]
I noticed something similar but I failed yet to reproduce it reliably.
I'm using MVTools interpolation for quite some time now, this issue is somewhat recent and only occurs rarely. My current guess is the (slight) desync happens whenever there's expensive typesetting. Couldn't pinpoint it better yet.

However, in your case it sounds more like a problem with the hardcoded assumed fps (because it happens always). The script you linked is not exactly good as it assumes the input is fixed 24fps, therefore it will fail whenever this is not the case, leading to accumulating drifts.
You are better off using the one linked here: https://github.com/mpv-player/mpv/wiki/User-Scripts (scroll down). And when this script doesn't work then make it work instead of using inferior or potentially faulty scripts.

@Cpuroast 
Because that's not the same: https://github.com/mpv-player/mpv/wiki/Interpolation

**Comment by Cpuroast** [comment]
vo=opengl:interpolation is exactly that, it's called Smoothmotion in that article. The option was simply renamed and the article was never updated.

**Comment by Argon-** [comment]
But this is about "Motion-based interpolation"...

**Comment by Cpuroast** [comment]
Ah right, fine, if you insist on using motion-based interpolation like on TVs, which is generally very expensive to compute and isn't usually great.

**Comment by morphological** [comment]
Thanks for the replies.

Argon, I tried the script you suggested and got the following outpout.
I dont know python at all, but I will try to do what I can, with your help, hopefully.

RenatoLaranja@RenatoLaranja:~$ mpv /home/guard.mkv --vf=vapoursynth=/home/RenatoLaranja/Downloads/60fps.py --framedrop=no  --hwdec=no  

Playing: /home/guard.mkv
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=ger (*) (dts)
     Audio --aid=2 --alang=eng (dts)
 (+) Subs  --sid=1 --slang=ger (*) (f) 'forced' (dvd_subtitle)
     Subs  --sid=2 --slang=ger 'complete' (dvd_subtitle)
Opening video filter: [vapoursynth file=/home/RenatoLaranja/Downloads/60fps.py]
AO: [pulse] 48000Hz 5.1(side) 6ch float
[vapoursynth] Script evaluation failed:
[vapoursynth] Python exception: expected an indented block (60fps.py, line 8)
[vapoursynth] Traceback (most recent call last):
[vapoursynth]   File "vapoursynth.pyx", line 1468, in vapoursynth.vpy_evaluateScript (src/cython/vapoursynth.c:23689)
[vapoursynth]   File "/home/RenatoLaranja/Downloads/60fps.py", line 8
[vapoursynth]     dst_fps /= 2
[vapoursynth]           ^
[vapoursynth] IndentationError: expected an indented block
[vapoursynth] 
Video filter chain:
  [vd] 1920x1080 yuv420p auto/auto CL=mpeg2/4/h264
  [in] 1920x1080 yuv420p bt.709/limited CL=mpeg2/4/h264
  [vapoursynth] 1920x1080 yuv420p bt.709/limited CL=mpeg2/4/h264   <---
  [out] ???
Cannot initialize video filters.
Could not initialize video chain.
Video: no video
A: 00:00:30 / 02:00:51 (0%)

**Comment by Argon-** [comment]
Well, I assume you copied the script somehow wrong, loosing some of the indentation.

**Comment by morphological** [comment]
You are right, sorry.

I copied the raw and it worked.
Now it at least shows me, that its out of sync in the output.

RenatoLaranja@RenatoLaranja:~$ mpv /home/guard.mkv --vf=vapoursynth=/home/RenatoLaranja/Downloads/60fps.py --framedrop=no  --hwdec=no
Playing: /home/guard.mkv
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=ger (*) (dts)
     Audio --aid=2 --alang=eng (dts)
 (+) Subs  --sid=1 --slang=ger (*) (f) 'forced' (dvd_subtitle)
     Subs  --sid=2 --slang=ger 'complete' (dvd_subtitle)
Opening video filter: [vapoursynth file=/home/RenatoLaranja/Downloads/60fps.py]
AO: [pulse] 48000Hz 5.1(side) 6ch float
Reflowing from  23.97602462  fps to  60.0  fps.
[vapoursynth] Frame requested during init! This is unsupported.
[vapoursynth] Returning black dummy frame with 0 duration.
[vapoursynth] Frame requested during init! This is unsupported.
[vapoursynth] Returning black dummy frame with 0 duration.
VO: [opengl] 1920x1080 yuv420p
AV: 00:00:05 / 02:00:51 (0%) A-V:  0.451

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:22 / 02:00:51 (0%) A-V:  2.614

**Comment by Argon-** [comment]
--framedrop=no

Problem detected. Well, now the answer is probably pretty easy: your hardware is too slow.

**Comment by morphological** [comment]
I am running an i3 and GTX 660.
I do notice the CPU being at 65 percent load, but nowhere near where it could actually impair the interpolation process.

Since I cannot use hardware decoding, is there a way to put some work on my gpu?

**Comment by Argon-** [comment]
Your CPU is insufficient for sure.
Rewriting mvtools to offload some major parts of its calculations to the GPU would make quite a few people happy. :)

**Comment by morphological** [comment]
Does the script take advantage of 4 CPU cores?

My i3 can handle the same file with SVP at an even higher load of eighty percent.

Are you sure there is no other explanation for this, considering your experiences?

I would imagine that slow hardware would be a factor, when it was actually maxed out at a hundred percent load and throttling.

**Comment by Argon-** [comment]
SVP does its calculations on GPU and mvtools/vapoursynth is not really well multithreaded.

**Comment by morphological** [comment]
What CPU are you running, if I might ask?
I feel kind of offended, that you are declaring my i3 as inadequate. lol

**Comment by Argon-** [comment]
i7 3770 and it only works because the "quality" of e.g. the analysis step in the script is performed with quality way worse then possible. ;)
As I said, a GPU implementation would certainly be a welcome addition.

**Comment by morphological** [comment]
Well I myself dont have the know how or the time, but I would certainly be prepared to fund and support such a project. That haasn guy seems to know what he is doing, all I need is a paypal ID. 
This issue is of great importance to me.

I could get a deal on an i5-4690K that I have been observing for a while and overclock it a little.
But if it turns out, that the cpu wasnt the problem, I shall be coming for you. 

And there I was thinking Linux is the platform where throwing hardware at a problem isnt the best solution.

**Comment by Argon-** [comment]
Well, as I said the whole vapoursynth/mvtool setup used here is also not scaling very well, so no guarantees on my side. ;)
Even when you get it working in real-time, there'd be still a lot of headroom left (higher quality analysis) which will certainly not work in real-time with our current hardware. A GPU implementation would really be the salvation for this stuff. Afaik haasn once looked into it, not sure how it turned out.

**Comment by morphological** [comment]
The team doesnt seem to offer much support on that specific matter and I dont see anyone else making a serious effort to attack that problem.

I will try to contact some people from the community and see if there is someone willing to do it.

I am amazed, that there arent more people demanding a gpu solution.

**Comment by Argon-** [comment]
I'm actually not sure how many people are even interested in (or do know about) it. I do like it, but plenty don't.
However, looks like there are at least some users interested in it, considering SVPs "donation drive": https://www.indiegogo.com/projects/real-time-video-frame-rate-conversion-for-pc#/story

**Comment by morphological** [comment]
lol nice find.

I will definitely contribute.
The goal for linux development is almost reached anyway, I believe it will be reached in a month.
And even if it doesnt, they will probably do it anyways, since it was very close.

**Comment by wm4** [comment]
I'm disturbed by how many people seem to want heavy artifacts and even pay for someone to create (closed sourced? vapoursynth?) plugins for this. It's a terrible world.

**Comment by haasn** [comment]
> Some of advanced Mac OS and Linux users know how to play smooth video with a combination of mpv video player and VapourSynth frame server.

I like how they name ‘mpv’ and ‘VapourSynth’, but don't mention ‘MVTools’ (the project that they illegally stole all their code from). It's almost as if they want to avoid drawing attention.

Either way, as far as the issue itself is concerned, if somebody makes a high-quality, free library for motion vector search that I can easily integrate, I would be very happy to add support for it to vo_opengl. (I've also thought about writing MV code myself from scratch, but I decided it was too much effort due to the complexity involved)

However, I will not provide any in-code support or assistance for a closed-source project.

**Comment by morphological** [comment]
Hey wmf,

I just got the i5 and tried to find the vapour script you linked, but the page mvtools is down, unfortunately. 
https://github.com/mpv-player/mpv/wiki/User-Scripts

Could you paste the script here, if you are still using it?

I will report back.
So far, with the primitive script, there is only a slight desynch, which might be negated by a simple audio delay.

**Comment by Argon-** [comment]
https://github.com/haasn/gentoo-conf/blob/nanodesu/home/nand/.mpv/filters/mvtools.vpy

Why do you insist on using no framedrop? I'd rather have a dropped frame every now and then than accumulating AV desync which is certainly not fixable with a static AV delay.
I also get framedrops: around 10-30 for ~30min of video in 720p (= 0.02% of all frames) and approx twice as much for 1080p, depending on the actual content (usually scenes with heavy typesetting lead to the drops).

**Comment by morphological** [comment]
Thanks for the link.

This script works fine in terms of av sync.
--no framedrop was not the issue, seeing as I am still using it and the audio is fine.

This primitive script was the problem.
https://gist.github.com/ghedo/fe0d232bda81f15e838b
The input is hardset to 24 FPS, that is why the desync happens.

There is one more thing, though.
Could it be that the script you linked isn't constantly active, interpolating motion?
I feel like it is only working at certain pan shots and non-intensive portions of a movie.

**Comment by Argon-** [comment]
Exactly, that's the case.
Search for `thscd2=12`. This is a threshold basically deciding whether to do motion interpolation or just regular blending.
Read more about the value here: http://avisynth.org.ru/mvtools/mvtools2.html#functions

**Comment by morphological** [comment]
Again, thank you very much for the info.
I finally understand the basic mechanisms and functions of the script.
I do want constant interpolation, though.

So basically, in order to achieve constant interpolation, one would have to increase thscd2 to a higher value. 

The documentation states, that the maximum threshold is a value of 255.
I increased it but still feel like certain scenes aren't interpolated.

The description of thscd2 rather seems to fit what I am looking for, but such an option does not occur in the script.

Is there another option I am missing, that would enable constant motion interpolation?

**Comment by haasn** [comment]
I would recommend starting off with a script like the one posted to the mpv wiki:

https://github.com/haasn/gentoo-conf/blob/nanodesu/home/nand/.mpv/filters/mvtools.vpy

(This one would have avoided your issue, since it doesn't make hard-coded assumptions about the source framerate)

**Comment by Argon-** [comment]
(he's already using your script)

> The description of thscd1 rather seems to fit what I am looking for, but such an option does not occur in the script.

Just add it the way thscd2 is used.

**Comment by morphological** [comment]
Ok, I added the thscd1 option and entered the value suggested in the documentation, which is 500. 
I did the same thing with thscd2.
Unfortunately, the script still chooses not to interpolation certain scenes.

This is what the line looks like now.
clip = core.mv.BlockFPS(clip, sup, bvec, fvec, num=dst_fps_num, den=dst_fps_den, mode=3, thscd1=500, thscd2=255)

**Comment by morphological** [comment]
I have added this, in order to individually determine the fps.
print("Source fps", (src_fps_num/src_fps_den))
print("Playback fps", (dst_fps_num/dst_fps_den))

Oddly, it outputs sixty FPS with both thscd2=12 and thscd2= 48, even though it doesn't feel like it.
Obviously, I scroll through in order to get to a constant update on the frame count update.

What do you think.

**Comment by Argon-** [comment]
Assuming you don't drop frames it *is* playing at your specified target FPS. The parameters like `thscd*` are about whether motion compensation is performed.

**Comment by morphological** [comment]
You are confusing me now.
Before, when I said that haasn`s script only seems to interpolate certain scenes, you confirmed my assumption and suggested thscd2 as the reason.

Something can't be right, since it is reporting 60FPS but I can clearly determine that at certain portions and scenes, it isn't playing at 60fps.

I have now researched every single parameter in haasn's script and even compared it to others.
Could it be, that his script actually does attempt to constantly interpolate, while simply failing to do so at times?

The structure of it is very similar to an osx guide on interpolation, which reportedly has this problem, as well.

**Comment by Argon-** [comment]
>but I can clearly determine that at certain portions and scenes, it isn't playing at 60fps.

How? Do you observe the estimated-fps?

**Comment by morphological** [comment]
I put two windows next to each other. One ran the script with hardset 60FPS interpolation, hence that is what constant interpolation must look like, and haasn's script with thscd2=12

I can clearly see, haasn's script does not interpolate in certain scenes, seeing as the image seems a bit laggy and slow, while its perfectly fluid on the other mpv instance.

Are there other options to improve smoothness, apart from thscd 1 & 2 ?

**Comment by morphological** [comment]
Ok I have figured it out.
The problem was caused by some parameter values, that are not optimal for high bitrate 1080p files.
By deleting them I presume, that the default values are used.
I also added overlap=0 to both bvec and fvec
The resulting interpolation is phenomenal, without any slowdowns or micro stutters.
Here is the new portion of the script, that I changed:
    
sup  = core.mv.Super(clip, pel=2)
    bvec = core.mv.Analyse(sup, isb=True , overlap=0)
    fvec = core.mv.Analyse(sup, isb=False, overlap=0)
    clip = core.mv.BlockFPS(clip, sup, bvec, fvec, num=dst_fps_num, den=dst_fps_den)

**Comment by morphological** [comment]
I have seen some people using --vo=opengl-hq:scale=ewa_lanczossharp with the 60FPS vapoursynth script.
Would that actually make sense?
I thought that using multiple filters is generally not recommended, but I must say, that there might be very minor improvement in overall visuals.
