### ISSUE TITLE
MPV freezes when opening multiple streams

### ISSUE THREAD

**Issue by aereaux** [mpv-player/mpv#2150]
I am trying to watch two twitch streams simultaneously (http://www.twitch.tv/srkevo4 and http://www.twitch.tv/srkevo2 in case it makes a difference) on Arch Linux.  After opening them both, one of them always freezes.  I can still quit out by pressing q, but the entire interface is frozen, even the osd.  There is no sign that anything is wrong in the terminal output, as far as I can see, and the terminal output keeps going.

If there's anything else I can provide to help diagnose the issue, let me know.

**Comment by wm4** [comment]
Does it work if you start them with ``--ao=alsa``?

**Comment by aereaux** [comment]
Yes, actually.  After a quick test, it fails to freeze at least for the minute I tested it.

**Comment by wm4** [comment]
I suspect Pulseaudio is being terribly "clever" again here. Maybe report it to Pulse upstream.

**Comment by aereaux** [comment]
Thanks for the responses.  I'm having trouble reproducing the problem, but if it happens again, I'll be sure to report it upstream.

**Comment by aereaux** [comment]
This issue is back, but --ao=alsa no longer fixes it.  Should I report it to pulseaudio, or is there something else I can try?

**Comment by wm4** [comment]
Does it work if you uninstall pulseaudio?

**Comment by aereaux** [comment]
No, it does not work.  I uninstalled pulseaudio, logged out, logged in, made sure pulseaudio was not running, and then tried it.  All but one of the windows froze again (I ran it with the --ao=alsa option if that makes any difference).

**Comment by aereaux** [comment]
I've done some more testing, and I've found that it also happens with other applications, and the problem also goes away (at least for the things I tested it with) when I change the video driver to x11 (the default is opengl, right?).  One of the applications it fails to work with is civilization V, which I believe also uses opengl extensively.
