### ISSUE TITLE
Keepalive for http streams?

### ISSUE THREAD

**Issue by m45t3r** [mpv-player/mpv#2152]
I have a habit of openning videos to watch, start doing something else and put the video in background to watch later. This works for normal videos, but while streaming, after sometime it seems that the connection is closed (probably server side), so after I resume watching and the cache finishes the video suddenly closes.

Would it be possible to implement something like keepalive pings or NOP requests so the connection doesn't close?

**Comment by wm4** [comment]
HTTP doesn't have such a thing. We try to reconnect if the TCP connection breaks.
