### ISSUE TITLE
Does it support intel quick sync?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2153]
As title, are there some ways to decode videos by the intel quick sync.

**Comment by wm4** [comment]
Why do you want it?

**Comment by laichiaheng** [comment]
@wm4 maybe more powerful?

**Comment by wm4** [comment]
No, stop listening to marketing. From what I know using hardware decoding through dxva2 and vaapi is just as good, and quicksync is mostly "needed" for hardware encoding on Windows.

**Comment by laichiaheng** [comment]
@wm4 Sometimes I see some video tearring, what might be the problem?

CPU: i5-4460 (HD4600), RAM: 4G 1333

mpv settings: 
     vo=opengl

     audio-device=alsa/default 

     sub-auto=fuzzy

     hwdec=vaapi

**Comment by Yomi0** [comment]
maybe, https://wiki.archlinux.org/index.php/Intel_graphics#Tear-free_video ?

**Comment by laichiaheng** [comment]
@Yomi0  There is no such file/folder, should I create it myself?

**Comment by Yomi0** [comment]
If ```20-intel.conf``` doesn't exist, then yes, you should create it. 
Unless there's someway the distribution you're using has a different way things should be done.

**Comment by DeadSix27** [comment]
Do add some other reasons:

QuickSync (on my iGPU) supports 4k x264, dxva2(-copy) does not on my system (AMD390x and i7 6700k)
Also I think QuickSync supports HEVC while AMD seemingly doesn't altho I never got it to work on either.

But ye, 4K x264 works fine in LAV with QuickSync but fails in dxva2 due to being 4K resolution.

And in **mpv** 1080p x264 works fine, but 4k does not either.

**Comment by wm4** [comment]
I bet dxva2 can support 4K just fine in theory. Intel's fault for having crap drivers.

I'm fairly sure you also can compile ffmpeg with quicksync and then force the quicksync decoder in mpv if you really want this.

**Comment by DeadSix27** [comment]
On that note, can you select the GPU (iGPU or Dedicated GPU) somehow (in ffmpeg or mpv)?

**Comment by wm4** [comment]
Probably via ffmpeg codec-private options, via `--vd-lavc-o=...`. Maybe the ffmpeg docs list what options are supported for qsv, and one of them is probably the device (i.e. GPU selection).

**Comment by DeadSix27** [comment]
I looked into it, hwaccel_device is the option in ffmpeg,. but not libavcodec 
`vd: AVOption 'hwaccel_device' not found.`

(E.g -hwaccel_device 0 -hwaccel/qsv dxva2 in ffmpeg)
doesn't work in mpv/libvacodec and so far I didn't find any other options.

**Comment by wm4** [comment]
That's an option of ffmpeg_qsv.c, which is part of ffmpeg CLI, not libavcodec, and which isn't used by mpv.

**Comment by wiiaboo** [comment]
That's because it's an option only found on ffmpeg.c.
Try `--vd=lavc:h264_qsv`. It won't work with 10-bit H264, btw.

**Comment by DeadSix27** [comment]
To re-phrase what I'm trying to archive, since @wm4 said this all works fine just with DXVA2,

I'm trying to find a way to tell mpv, or in the suggested case, libavcodec to use that specific GPU rather than the automatically selected one.


![image](https://cloud.githubusercontent.com/assets/1492505/20861356/526f839e-b98e-11e6-8cdb-6fa3581e328b.png)

**Comment by wiiaboo** [comment]
It depends on which one is connected to your monitor, at least for the non-copy versions.

**Comment by DeadSix27** [comment]
(well i use dxva2-copy)

**Comment by kevmitch** [comment]
For `dxva2-copy`, we call [IDirect3D9::CreateDevice](https://msdn.microsoft.com/en-us/library/windows/desktop/bb174313(v=vs.85).aspx) with D3DADAPTER_DEFAULT, which is what windows considers the "primary display adapter". We could add an option to specify the display adapter. I can take a look it this over the next week.

**Comment by wm4** [comment]
Note that ffmpeg gained some API for creating dxva2 devices, and it can even take some kind of a device string (AFAIK). We could use this. (See hwcontext.h.)
