### ISSUE TITLE
Robidoux tscale produces noticeable afterimages

### ISSUE THREAD

**Issue by gtm87x** [mpv-player/mpv#2155]
I don't know if this is somehow related to the problem described in #2127, so I'm opening this new report.

Since tscale=oversample has been reintroduced with commit 3007250, I started to see some noticeable ghosting/blackish afterimages. These are very clear during normal playback, especially in some transition or in subtitles (using blend-subtitles).
Can't say anything about other tscales because I've always used only oversample, but the latter's "old version" for sure didn't suffer from this.
Here's a sample file in which the problem shows up clearly: http://a.pomf.cat/ndkqmf.mkv
And here's some screen of the problem I've attained recording the screen during playback: http://imgur.com/a/sE1Ft
Let me know if you need any other sample/info/log.

**Comment by haasn** [comment]
Most of those screenshots just look like it's working as intended. You could try posting a playback log with ```msg-level=vo=debug``` with both the old and new versions of oversample.

That said, the one that confuses me is the one where the afterimage is “black”. I'm not sure how that could even possibly happen, given the fact that it's just blending two images together, not subtracting or anything.

**Comment by gtm87x** [comment]
>Most of those screenshots just look like it's working as intended.

I can only say it's way more noticeable than before. Here's the screen recording I made, I hope it can explain my issue more effectively than my words http://a.pomf.cat/ftyxje.mov

>You could try posting a playback log with msg-level=vo=debug with both the old and new versions of oversample.

I'll compile an old version right now and provide the logs.

>That said, the one that confuses me is the one where the afterimage is “black”

From what I have experienced before opening this issue, this often happens.

**Comment by haasn** [comment]
Ah, I don't get that *at all* on my end. But I recognize the issue, it seems like something is clearly broken with the mixing coefficients.

For example, I got results very similar to that when I had a sign error in the calculation code. You could try posting the log, that would definitely help debugging this.

**Comment by gtm87x** [comment]
Here's the log with master (git-968bd3d): https://gist.github.com/gtm87x/3e49371f4c5cee1fd9ab

Do you still need one with old oversample too?

**Comment by haasn** [comment]
That log doesn't look like ‘oversample’ is being used at all.

**Comment by gtm87x** [comment]
Actually appending :tscale=oversample to my vo line seems to fix this behaviour.
I was using the `:interpolation` flag alone, isn't it simply defaulting to oversample like it was before? From the man it seems like so.

**Comment by haasn** [comment]
Oh, I just realized the default was only changed back for ```opengl```, not ```opengl-hq```. Still, I wonder why you get such bad results with robidoux - I cannot reproduce them to the degree of severity demonstrated in your screen capture.

**Comment by gtm87x** [comment]
That could just be my GPU's fault. I'm on a five year old laptop, and the nvidia discrete card manages to work fine with opengl-hq defaults, deband shader and oversample interpolation active at the same time, but I fear everything more demanding is just beyond its capabilities.

**Comment by haasn** [comment]
So I guess the way to resolve this bug would be to make ‘oversample’ the default for opengl-hq as well, and ignore the other issue you had w.r.t tscale=robidoux? (Unless somebody else can reproduce it, or it's a regression)

**Comment by gtm87x** [comment]
I think this is best solution at the moment, yes. As I said, my issue with tscale=robidoux could be my hardware's shortcomings' fault, so if you can't reproduce it I think it's safe to just ignore it and see if someone else will report something similar in the future.
Still, if you'll need further infos or log, just let me know.

**Comment by Argon-** [comment]
Tested it out of curiosity and it happens here too. I used `opengl-hq:interpolation` with `tscale=robidoux`
Two consecutive frames from a screen recording of the interpolated playback:
![screen shot 2015-07-20 at 02 27 31](https://cloud.githubusercontent.com/assets/540920/8768604/eb0cf670-2e86-11e5-98f1-7befedea1bde.png)
![screen shot 2015-07-20 at 02 23 17](https://cloud.githubusercontent.com/assets/540920/8768599/a455cf86-2e86-11e5-9bec-e74777145a8e.png)

**Comment by Argon-** [comment]
Here's a small sequence of images: https://0x0.st/sK3.zip
Especially 826 is pretty strange imo.

**Comment by haasn** [comment]
Actually that mostly seems like it's “working as intended”, though could you provide a 60 fps recording that I can test? It should be relatively obvious whether or not it's “smooth” or completely jerky.

The negative afterimages are a natural consequence of the way this particular scaler (robidoux) works. (I wonder if clipping off the negative components of the function would improve the result)

Interesting side thought: I just realized that these negative pre-/postringing artifacts are not unlike a form of pixel overdrive, which might explain why these scalers look good on eg. my slow IPS monitors (because it's effectively adding our own form of overdrive).

Are you testing on IPS panels or TN panels? Perhaps the artifacts are just significantly more obvious on TN panels.

**Comment by Argon-** [comment]
https://0x0.st/sKg.mov
I'm not so much surprised by the existence of afterimages but more by them being black. I didn't expect this and it "feels" wrong to have something black as the result of some blending but I don't know how this algorithm works, so my "feeling" isn't meaningful anyway.
Still, the black after image suddenly appearing in 826 looks weird. 

Testing on an e-IPS (u2312hm) but I didn't really notice it while watching (I'm not using this algorithm outside of tests either, looks too blurry for me). However, according to reviews this is apparently a pretty fast panel compared to TN panels (8ms response time).

**Comment by qmega** [comment]
I'm currently using a TN panel and I see (blended) subtitles flash black when they disappear sometimes. It's significant enough that I notice it when I'm just watching normally, not looking for it (I actually use tscale=robidoux), but I don't notice it on every sub, just occasionally.

`vo=opengl-hq:scale=ewa_lanczossharp:cscale=ewa_lanczossoft:scaler-resizes-only:interpolation:tscale=robidoux:blend-subtitles=yes:gamma=0.9`

@haasn I'd be happy to try a patch for clipping off negative components or anything else you think might improve the negative afterimage issue.

**Comment by haasn** [comment]
> @haasn I'd be happy to try a patch for clipping off negative components or anything else you think might improve the negative afterimage issue.

Such a patch is almost trivial. Feel free to test.

```
diff --git a/video/out/filter_kernels.c b/video/out/filter_kernels.c
index a748ac1..065d5a1 100644
--- a/video/out/filter_kernels.c
+++ b/video/out/filter_kernels.c
@@ -257,6 +257,11 @@ static double cubic_bc(params *p, double x)
     return 0;
 }
 
+static double cubic_bc_clamp(params *p, double x)
+{
+    return fmax(cubic_bc(p, x), 0.0);
+}
+
 static double spline16(params *p, double x)
 {
     if (x < 1.0)
@@ -368,8 +373,8 @@ const struct filter_kernel mp_filter_kernels[] = {
     {{"mitchell",       2,   cubic_bc, .params = {1.0/3.0, 1.0/3.0} }},
     {{"robidoux",       2,   cubic_bc, .params = {0.3782, 0.3109} }},
     {{"robidouxsharp",  2,   cubic_bc, .params = {0.2620, 0.3690} }},
-    {{"ewa_robidoux",       2,   cubic_bc, .params = {0.3782, 0.3109}}, .polar = true},
-    {{"ewa_robidouxsharp",  2,   cubic_bc, .params = {0.2620, 0.3690}}, .polar = true},
+    {{"ewa_robidoux",       2,   cubic_bc_clamp, .params = {0.3782, 0.3109}}, .polar = true},
+    {{"ewa_robidouxsharp",  2,   cubic_bc_clamp, .params = {0.2620, 0.3690}}, .polar = true},
     // Miscellaneous filters
     {{"box",            1,   box, .resizable = true}},
     {{"nearest",        0.5, box}},
```

**Comment by qmega** [comment]
(I changed the non-ewas to cubic_bc_clamp, I assume that's what you meant? If I understand correctly (which I probably don't) ewa requires 2 dimensions, and time is only 1. At any rate, mpv won't even let me use an ewa scaler for tscale.)

That completely eliminates the black flashes for me. Interpolation still appears to be working as intended. Is there any advantage to keeping the negative output of the function?

BTW, mitchell has the same behaviour (black flashes), and cubic_bc_clamp fixes that as well. Didn't test any others.

Also, I'll be getting an IPS in the near future, so I can test with that and compare, if you think it would be any different.

**Comment by haasn** [comment]
^ there, this commit just makes it a configurable option for all tscale settings.

**Comment by qmega** [comment]
Thanks, works for me.
