### ISSUE TITLE
It's just a quesion, maybe not mpv's problem.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2159]
Can I decode it by intel HD4600 and output from my graphic card?
because HD4600 can decode 4K videos and GTX460 can't, but GTX460 has more power to render.
I did that on Windows, but don't know whether Linux can do it or not.

**Comment by kevmitch** [comment]
I understand that you want to decode on the onboard GPU and display on a discrete GPU.
On linux you should be able to use ```--hwdec=vaapi-copy --vo=opengl``` in theory. Whether that would give any performance improvement over software decoding is another thing. You'll want to profile it to see. 

I'm kind of curious exactly how ```--hwdec=vaapi``` will fail though . . . Would mpv detect that makes no sense?

**Comment by wm4** [comment]
No further reaction, so I'm closing this.
