### ISSUE TITLE
Trying to implement multiple mpv config files

### ISSUE THREAD

**Issue by morphological** [mpv-player/mpv#2160]
Hello,
I need mpv to be able to choose between multiple  mpv.conf files, with different options and properties, in order to suit various video files.

I read that in order to accomplish this, the source code must be edited.
More specifically, an if has to be added in the .conf selection portion, with as many paths as needed.

I simply failed in finding that code passage and setting it up in general.

Is there another way one could use multiple .conf files?

**Comment by wm4** [comment]
Use profiles. They can also include other config files with ``include``, so everything required should already be present.

**Comment by morphological** [comment]
Ah thank you, I wasn't even aware of that functionality.

Just one more question in that regard.
For example, one profile for mkv playback.
The following marks the beginning of the profile
[protocol.mkv]
commands  etc .....

And the end is  marked by a new [profile], correct?
Later on, the desired profile can then be used via --profile.

Also on a sidenote, I wanted to inform you about my correspondence with the SVP team regarding vapoursynth and a possible gpu solution.

I contacted some of their team members, asking whether they were gonna do it, even if the donation target won't be fully reached and if there was a possible alternative in the event of their refusal.

They said, that the gpu can already be implemented by editing some minor code and modifying the Nvidia driver. Note, that amd was not mentioned lol.

Also, they will develop for LInux, even if the target isn't reached, seeing as they already just little above a thausand shy.

**Comment by wm4** [comment]
>And the end is marked by a new [profile], correct?
>Later on, the desired profile can then be used via --profile.

Yes.

>They said, that the gpu can already be implemented by editing some minor code and modifying the Nvidia driver. 

Modifying the driver? What a nice beginning. Anyway, I don't know what SVP is planning, and considering the result will most likely be closed source, I'm not sure if I care.

**Comment by Argon-** [comment]
>And the end is marked by a new [profile], correct? ( or nothing)
Or use [default] to go back to "no-profile" mode.
