### ISSUE TITLE
ytdl defaults to limited colorlevels

### ISSUE THREAD

**Issue by paulguy** [mpv-player/mpv#2163]
Not sure what's the most correct or best option but my assumption with most streaming stuff (not sure about the details internal to Flash or HTML5) is that they expect videos to be full range and display them as such.  This problem is very noticeable with some youtube videos at least (I don't use mpv's ytdl support for much else).

Example: https://www.youtube.com/watch?v=0g_IwZu1q_M

I'm thinking maybe it would be better for youtube-dl to somehow specify the video color level to be full rather than limited.  Unfortunately, I imagine some stuff like maybe sites that show TV shows might be configured to display limited range colors so this might just end up messing those up.

**Comment by ChrisK2** [comment]
Properly encoded HD video intended for distribution should ALWAYS be limited range and also is ... most of the time. The video stream indicated wether it's full or limited range and mpv respects that flag. If it's set incorrectly there is nothing we can do except for having the user override it manually.

If we override the flag for ALL youtube videos, we'd break a LOT of correctly encoded ones. I'm afraid there's nothing we can do here.

**Comment by paulguy** [comment]
Alright, I guess i'll just tell this guy to fix it heh.

**Comment by haasn** [comment]
“Full range YUV” is not something that really makes a lot of sense either way, it's pretty arbitrary. YCbCr is designed to work with limited range colors - so if the encoder screwed that up, chances are they'll screw a lot of other things up as well.

Any real encoder would convert the full-range RGB (eg. from a screen recording) to limited range YCbCr when encoding to H.264.

**Comment by wm4** [comment]
In this case, youtube doesn't seem to tag the file at all, so we have to assume the sane default, limited color range.

**Comment by Architector4** [comment]
Stumbled upon a video with limited color range too. Funnily enough, YouTube's video player displays it as if it's a full color range video anyway...

You can also force any limited color range videos to be converted to full by setting `vf` to `scale=out_range=full`

And if you want to have a quick toggle, add this to `input.conf`:

    Ctrl+b		vf toggle "scale=out_range=full"; show-text "Toggled limited→full color range conversion"

And if you have a video that's labeled as full color range, but only uses the limited range of colors, you can forcibly expand it (with risk of blowing out colors!!) by doing the above with `scale=in_range=limited:out_range=full` filter instead.
