### ISSUE TITLE
"option-info/<name>/set-from-filedir-conf" property for Lua scripts

### ISSUE THREAD

**Issue by ElegantMonkey** [mpv-player/mpv#2165]
With it, a script like vo_battery.lua, for example, could determine if its own settings should be overridden by the ones located in the filedir conf file. There is already the "set-from-commandline" option, so it makes sense having a set-from-filedir-conf one.

**Comment by wm4** [comment]
filedir confs? Someone is using that?

**Comment by ElegantMonkey** [comment]
Well, I use it because I don't want a sharpening filter for a stream, for example. So for each show/anime I watch, I use a filedir conf.

**Comment by wm4** [comment]
I added something similar - this must be enough. I don't want to add something that's more specific.

**Comment by ElegantMonkey** [comment]
Thanks!
