### ISSUE TITLE
Add the option to append media to playback queue instead of playing media instantly

### ISSUE THREAD

**Issue by thorhop** [mpv-player/mpv#2166]
Add option for the user to add files to a playback queue when dragging and dropping files/URLs on to mpv or launching a new mpv with a command line switch which will add media to the playlist of an already running mpv process.

Right now there doesn't seem to be an option to change the default behaviour of mpv if a file/URL should be dropped on to it. Case in point: 

[input/event.c - line 23](https://github.com/mpv-player/mpv/blob/master/input/event.c#L23)

Thanks!

**Comment by kevmitch** [comment]
I second this. It would remove half the motivation for a playlist gui. Currently, all but the simplest playlists (all files in same directory) are impossible to build except from the command line.

**Comment by ChrisK2** [comment]
How about making this use a modifier key? Normal dropping replaces, dropping with Shift pressed adds?

**Comment by lachs0r** [comment]
Or, to make it a bit more intuitive, make the OSC show visual hints, e.g. so that depending on which part of the screen the files are dropped in, mpv will replace the playlist and start playing instantly, or add them to the current playlist, or something else…

I may or may not be volunteering. Does the API expose something like a drag-enter event yet?

**Comment by wm4** [comment]
>Does the API expose something like a drag-enter event yet?

No.

**Comment by ChrisK2** [comment]
now we are starting to escalate things a bit ...

**Comment by wm4** [comment]
So, what do you want?

**Comment by kevmitch** [comment]
I think it would be sufficient to interpret drags into a window already playing something as enqueue. It could be an opt-in command line / config option if there is desire to maintain the old behaviour.

**Comment by mc4man** [comment]
I would like to see an append-play command for mpv directly (to be used via DnD on  a .desktop launcher
Though admittedly that would be of limited user base useability

**Comment by wm4** [comment]
The command exists, it's just not used by the drop code. (Actually it does use it if multiple files are dropped: for each file a loadfile command is run, and only the first file wipes the previous playlist.)

**Comment by kevmitch** [comment]
Wow, that was easy

    -                (i == 0) ? "replace" : "append",
    +                (i == 0) ? "append-play" : "append",

On the other hand if this should not be the default behaviour, we need either a modifier key (+ modiified event) or an option. Opinions?

**Comment by kevmitch** [comment]
I'd be fine without any further changes than that. The drawback might be that dragging files to a playing window gives no notification that the files were added to the play list. Should there could be some sort of osd notification?

**Comment by mc4man** [comment]
above works fine here when mpv is started on a playlist or at least 2 files. So dumb ? of the month - is there anyway to have this work when mpv is opened  on a single file?
(- I guess for opening via the .desktop I could add /dev/null to the Exec= line though maybe that's a poor idea..

**Comment by kevmitch** [comment]
@mc4man I don't understand. 

Are you saying that the above doesn't work when mpv is started with  ```mpv file.mkv```? What happens then?

**Comment by mc4man** [comment]
Ok , re- checking,   if starting with a single file it does 'work' - 
[cplayer] Run command: loadfile, flags=1, args=[file:///home/doug/Videos/amostviolentyear-clip1_h1080p.mov, append-play, ]
but I have to wait until the 1st. file finishes. (no playlist arrows in Osc) or use a keyboard binding
If mpv is started with 2 files then those & any DnD files can be switched at will from those little arrows in the Osc
So I guess that was what I was looking for from a single file, ie. the Osc playlist arrows.., sorry about my confusion here.

Ot - is there anyway to stop the 'spamming'  when using -v from simple  cursor movement in window?
(-  [cplayer] Run command: ignore, flags=9, args=[]  & if exposinf Osc
[cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding2]

**Comment by kevmitch** [comment]
I see what you mean. So the OSC doesn't get updated by the drop event I guess.

Looks like once the next file is loaded the arrows appear.

There doesn't seem to be a documented event that the osc could listen to for this. ```file-loaded``` sounds like the new file has to start playing.

**Comment by kevmitch** [comment]
adding  to osc.lua

    mp.observe_property("playlist", nil, request_init)

seems to cause the arrows to appear right away.

**Comment by wm4** [comment]
So I see the following possibilities:

1. we switch to the new behavior, and the old behavior is not possible anymore
2. we make it configurable
3. something with shift modifiers deciding the behavior or so
4. somehow implement it in the OSC

I don't like 2. input.conf is not flexible enough for this (unless you have a suggestion), and I'd like to avoid another global config option. Plus, I can't imagine anyone actually bothering to find and use this setting.

We could do 3., which would be pretty simple, but also requires modifications in 4 platform backends (x11, wayland, osx, win).

Option 4 would implement it in the OSC and possibly allow fancy interactions (like visually indicating the action the drop will have), but it also sounds very complicated, and I don't volunteer to do the osc.lua part of the implementation.

**Comment by mc4man** [comment]
I like 1 but obviously a certain % would disagree & want a new DnD to start immediately. 3 seems ok, again here would prefer the modifier to be for 'old' behavior as I'd take a guess the majority would like the 'new' behavior.
(- I could do a quick test & push new behavior to one ppa & see how many complaints I get (or you get..
Right now I'd say there are 1400 or so very active users so that's not a huge sampling but could be representative

**Comment by ChrisK2** [comment]
1) will probably get some people angry "MAKE IT CONFIGURABLE!!11"

2) (global config option) or 3) sound like the best solutions to me.

4) would shut out all people who disable the OSC.

**Comment by Argon-** [comment]
3. would without doubt result in people requesting a config option to reverse the shift/no-shift behavior.

**Comment by kevmitch** [comment]
Append to playlist is now implemented on X11 and Windows when dropping with the shift key.

Leaving this open as it still needs to be implemented on MacOS and Wayland. I can probably figure out Wayland in the next day or so, but I have no way of testing on MacOS, so someone else will have to do that.

**Comment by kevmitch** [comment]
As far as I can tell Wayland suffers from the same problem as X11 in that the drag destination doesn't get any direct information about modifier keys. In contrast, this is something that Windows got dead right.

Furthermore, unlike X11 Wayland does not currently have the concept of drag and drop actions, although it looks like this is being [planned / discussed](http://lists.freedesktop.org/archives/wayland-devel/2015-June/022517.html). Therefore, I don't think it is currently possible to implement this for Wayland.

**Comment by kevmitch** [comment]
So OSX remains the only platform to do (if it's even possible there). Marking as stalled, since no one seems interested. I may one day be able to beg/borrow/steal a Mac, but no promises.

**Comment by vitorgalvao** [comment]
Just to clarify, it’s currently possible to append to the playlist with ⇧+drag-and-drop on the window on every OS but OS X.

However, it’s not possible to append to the running playlist via the CLI. Is that correct?

**Comment by wm4** [comment]
> Just to clarify, it’s currently possible to append to the playlist with ⇧+drag-and-drop on the window on every OS but OS X.

Seems so.

> However, it’s not possible to append to the running playlist via the CLI. Is that correct?

You can via Lua scripting or the JSON IPC, but there's no higher level builtin support for it with the normal "user interface".

**Comment by vitorgalvao** [comment]
> but there's no higher level builtin support for it with the normal "user interface"

Yes, that’s what I meant. Thank you for the fast reply.

**Comment by haasn** [comment]
As an end-user the way I would like to see this issue resolved is by making the drag-and-drop event a customizable keybinding, so I could decide what to do. (The path would be expanded somehow)

Not sure if that makes any sense in the mpv input frame work, but it would certainly be the most elegant way to let users decide whether to replace or append new files.

**Comment by wm4** [comment]
> As an end-user the way I would like to see this issue resolved is by making the drag-and-drop event a customizable keybinding, so I could decide what to do. (The path would be expanded somehow)

Passing the path is exactly the problem.

**Comment by Rick74crx** [comment]
@Akemi 
Since you're doing many cocoa-related things lately, there is any chance you could take a look at this long-stalled issue?

**Comment by Akemi** [comment]
that should do it.

**Comment by vitorgalvao** [comment]
@Akemi Thank you for this. Still no way to do it via CLI, is that correct?

**Comment by Akemi** [comment]
just the ways that were already mentioned i believe. i just took care of the missing cocoa part.

**Comment by vitorgalvao** [comment]
> just the ways that were already mentioned i believe.

Asking because the original request (top post) included it (emphasis added):

> when dragging and dropping files/URLs on to mpv **or launching a new mpv with a command line switch** which will add media to the playlist of an already running mpv process

But yes, as I understand it, it doesn’t do that in any OS. Was just checking.

Again, thank you for implementing it.

**Comment by Rick74crx** [comment]
Thank you very much!

**Comment by GreyAsteroid** [comment]
Alright! So I need this to be configurable 😃

Would it be best if I made a new feature request or no?

**Comment by captain** [comment]
Couldn't you just use "mpv playlist.u3m" and then "cat filename >> playlist.u3m" with things you want to append to it?  The nice thing about that is you can also "cat playlist.u3m" to SEE what's on it!  :-)
PS: This should also work on MacOS.
