### ISSUE TITLE
eof-reached is not triggered any more

### ISSUE THREAD

**Issue by HaseebYousaf** [mpv-player/mpv#2167]
the event has stopped triggering when --keep-open is enabled, probably because mpctx->audio_status is always STATUS_PLAYING.

**Comment by kevmitch** [comment]
according to the man page, ```--keep-open``` will "pause when the player would normally exit". So I think this is expected.

**Comment by wm4** [comment]
>according to the man page, --keep-open will "pause when the player would normally exit". So I think this is expected.

Technically you could say this. And in fact, I'm not sure what happens if audio is longer than video, and the code for skipping to the last video frame is skipped. In this situation, the property will probably still signal the "wrong" state.
