### ISSUE TITLE
Audio file

### ISSUE THREAD

**Issue by Vegan-us** [mpv-player/mpv#2168]
On audio file (.mp3)  the screen controller is not showing!

**Comment by wm4** [comment]
Use ``--force-window`` or ``--profile=pseudo-gui``.

**Comment by Vegan-us** [comment]
And how should I interpret that?

**Comment by wm4** [comment]
How are you running mpv?

**Comment by Vegan-us** [comment]
I have mpv as my default player so I usually click the file, open and play...

**Comment by wm4** [comment]
What operating system/distro/mpv build?

**Comment by Vegan-us** [comment]
Windows7/-/mpv-i686-20150714

**Comment by wm4** [comment]
So does it show a window when playing audio files?

**Comment by Vegan-us** [comment]
Sorry, yes it does but not the "screen controller"-  time, forwarding arrows etc..It is just a black screen. I can command volume with keyboard though!

**Comment by Vegan-us** [comment]
Sorry, yes it does but not the "screen controller"- time, forwarding arrows etc..It is just a black window. I can command volume with keyboard though!

**Comment by Vegan-us** [comment]
Sorry, yes it does but not the "screen controller"- time, forwarding arrows
etc..It is just a black window. I can command volume with keyboard though!

**Comment by wm4** [comment]
Is it showing up with normal video files?

**Comment by Vegan-us** [comment]
Yes!

**Comment by wm4** [comment]
That shouldn't happen...

**Comment by Vegan-us** [comment]
I reinstalled it again but the problem persist!

**Comment by wm4** [comment]
I guess I can try it tomorrow. How did you create the file associations?

**Comment by Vegan-us** [comment]
Thank you,

I followed this: https://github.com/rossy/mpv-install/blob/master/README.md

Thanks again for your time.

**Comment by wm4** [comment]
I tried it. I downloaded the latest 64 bit build form lachs0r's site, extracted it, double clicked mpv.exe, dragged a wav file on it, and it was playing while showing the OSC when moving the mouse over the mpv window.

**Comment by Vegan-us** [comment]
I need the 32 bit, also what is the lachs0r's site address? obviously the
version from http://mpv.srsfckn.biz/ is causing the bug...

**Comment by Vegan-us** [comment]
I've tried the older version (2015-06-28) and it is working like it
should...

**Comment by bitingsock** [comment]
I am experiencing the issue now too. version (2015-06-28) has it working.
(win 8.1x64)

**Comment by bitingsock** [comment]
Although not on my main machine...@Vegan-us does your console give an error about not supporting OpenGL 3.x?
@wm4 Would this have anything to do with it?

**Comment by wm4** [comment]
Shouldn't have to. Does it not use opengl at all on your machine? What VO does it use?

**Comment by bitingsock** [comment]
well i tried direct3d and it doesn't work either so it doesn't matter

**Comment by bitingsock** [comment]
Also I should note all osd messages are not working either. Something with ASS?

**Comment by Vegan-us** [comment]
@bitingsock  the (2015-07-26) and (2015-07-14) 32bit windows releases are showing some flaws...
No mpv icon introduction in the new open window and the screen controller is missing!

**Comment by wm4** [comment]
Sounds like a fontconfig problem then (although not everything what was said is consistent with this). Try with the latest build.

**Comment by Vegan-us** [comment]
Still the same...
