### ISSUE TITLE
Enquiry about "the last opened date" by mpv on OS X

### ISSUE THREAD

**Issue by homever** [mpv-player/mpv#2170]
I notice that when I open a .mkv file with mpv, it doesn't register the "last opened date", and thus some of my rules are not matched to be able to mark this particular mkv file as "watched".
I am asking what kinda information actually changes, so that I can modify the rules?
Or, is there any existing scripts can handle this?
Thank you.

**Comment by kevmitch** [comment]
Are you referring to unix atime (access time)? If so, then that's up to your filesystem. I think it's pretty common these days that distros specify the "relatime" or "noatime" mount option in /etc/fstab, which will basically break what it sounds like you're trying to do. You could just remove that option from your fstab and atime will work like you might expect (though at some performance penalty).

If I'm totally off the mark and you aren't talking about atime, then you'll have to be more specific about what OS and work-flow you're using.

**Comment by homever** [comment]
Forgive me for my being unprofessional as I am not doing coding.
As for my exact question, yes, it is the "atime" I was asking. 
I am on OS X. The atime is described as "the last opened date". I can't get this info if the file is accessed by mpv.

**Comment by kevmitch** [comment]
Is it working for other applications, but not mpv? 

Is there some special way an application is expected to open files on osx for this to work?

**Comment by homever** [comment]
Yes, all works well if opening with other Players, like MplayerX, Movist, or even Quick time player which actually won't open but it successfully register the “atime" to the file.
For your second question, I don't think the app need to be opened in a special way for this to work. It is supposed to work in any circumstances.

**Comment by wm4** [comment]
Are you sure this is the unix atime, and not some separate thing?

**Comment by wm4** [comment]
PS: the situation is complicated by the fact that my OSX installation crapped its pants and can't be booted anymore, so I currently can't test this myself.

**Comment by Akemi** [comment]
just some additional info. it works for me when opened with the bundle, but doesn't work when opened through terminal.

**Comment by homever** [comment]
Hi,
Thank you for the information. Even more strange, I just tested 34 movie files on my drive (opened with the bundle), only 4 of them can actually have "the last opened date" updated, and I really can't tell the difference between these 4 and the others.

**Comment by homever** [comment]
---update---
I seem to be able to identify some differences from console log.
For those failed to register "the last opened date", the console output has this error:
```
28/7/15 11:25:59.311 am CoreServicesUIAgent[290]: Error -60005 creating authorization
```
In addition, I also have this error with every opened file (irrelevant to this topic):
```
28/7/15 11:26:01.322 am CoreServicesUIAgent[290]: unexpected message <OS_xpc_error: <error: 0x103ab1c60> { count = 1, contents =
	"XPCErrorDescription" => <string: 0x103ab1f70> { length = 18, contents = "Connection invalid" }
}>
```
And some of the files have this error:
```
28/7/15 11:26:31.928 am mpv[1861]: GVA error: fail to setup QT accelerator (4)
```

**Comment by tewe** [comment]
It all works for me. Since you mention rules I assume you use Hazel, which in my experience is rather unreliable software *and* very hard to use correctly.

It'd help if you gave the output of `stat -x my.mkv` on a terminal, especially Mode and Access.

**Comment by homever** [comment]
For those have updated last opened time:
``Mode: (0644/-rw-r--r--)         Uid: (  501/Edwa)  Gid: (   20/   staff)``

For those don't have last opened time updated:
``Mode: (0600/-rw-------)         Uid: (  501/Edwa)  Gid: (   20/   staff)``

**Comment by homever** [comment]
This issue may not totally relate to mpv, but can be
