### ISSUE TITLE
Clear fullscreen flag when window size is changed

### ISSUE THREAD

**Issue by mathstuf** [mpv-player/mpv#2171]
When mpv is fullscreened then the window is resized (using Alt+RightClick), mpv still thinks it is fullscreened and toggling it will first go to the dimensions before the original fullscreen.

**Comment by wm4** [comment]
This is awfully unspecific.

**Comment by mathstuf** [comment]
- open a video in mpv (window has size A)
  - fullscreen it (`f`)
  - Alt+RightClick and drag to resize window
  - fullscreen (`f`) and mpv goes to size A rather than back to fullscreen

**Comment by wm4** [comment]
Alt+RightClick doesn't resize the window here. What OS? What window manager? etc.

**Comment by mathstuf** [comment]
Linux with XMonad. It's usually bound to that. Maybe EWMH doesn't allow it on fullscreen windows normally?

**Comment by wm4** [comment]
If xmonad logically leaves fullscreen, it must change the _NET_WM_STATE property accordingly. mpv (as of git master) will listen to that change, and unset its fullscreen flag when this happens.

**Comment by mathstuf** [comment]
Here's `xprop` output for `mpv` when it is fullscreen:

```
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3e, 0x0, 0x0, 0x0
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified location: 1440, 0
                program specified size: 1920 by 1080
                program specified minimum size: 4 by 4
                program specified minimum aspect ratio: 1920/1080
                program specified maximum aspect ratio: 1920/1080
```

and not fullscreen:

```
_NET_WM_STATE(ATOM) = 
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3e, 0x0, 0x0, 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified location: 0, 0
                program specified size: 1440 by 900
                program specified minimum size: 4 by 4
                program specified minimum aspect ratio: 1440/900
                program specified maximum aspect ratio: 1440/900
                window gravity: Center
```

**Comment by wm4** [comment]
So xmonad doesn't support ewmh fullscreen here? Then I don't know why you expect anything to work well.

**Comment by mathstuf** [comment]
Well, it works in the sense that fullscreen is toggled and everything (the behavior certainly is as expected except for this state tracking). Guess I'll just live with it (or whip up a patch).

**Comment by wm4** [comment]
For things like xmonad, mpv uses some legacy method to get into fullscreen. xmonad really should just stop being a bad WM and support EWMH. The ridiculous explanation why xmonad doesn'T is something because of Flash. (Who the fuck still uses Flash?)
