### ISSUE TITLE
OS X: Show video name (as opposed to filename) in OSD?

### ISSUE THREAD

**Issue by vitorgalvao** [mpv-player/mpv#2172]
```bash
mpv 'https://www.youtube.com/watch?v=YE7VzlLtp-4'
```

<img width="1117" alt="screen shot 2015-07-26 at 22 53 53" src="https://cloud.githubusercontent.com/assets/1699443/8896111/7f3c2958-33e9-11e5-9f60-a5b690d64e58.png">

The window title and OSC show the name of the video, while the OSD shows the stream ID. I have `i show_text "${filename}"` in my `input.conf`, so I guess there should be an alternative value instead of `${filename}` that gives us the video title. Is there?

**Comment by ChrisK2** [comment]
``media-title``

**Comment by vitorgalvao** [comment]
Thank you. More than once I had to looked around online for these values. Is there an online reference for them? Perhaps a wiki we can contribute to?

**Comment by ChrisK2** [comment]
http://mpv.io/manual/master/#property-list
