### ISSUE TITLE
 loading font from ass file not work again

### ISSUE THREAD

**Issue by realfinder** [mpv-player/mpv#2174]
hi, I am use mpv for windows

and note that 2015-07-26 and 2015-07-14 Builds can't view the fonts that attachment in ass file

2015-06-28 is ok, I am using 64 bit Builds, not know if 32 one is ok or not

**Comment by wm4** [comment]
Can you upload a .ass file which shows this well?

**Comment by wm4** [comment]
OK, got a sample from someone else.

This is not easy to fix, because the change that broke this was a fix for something else.

**Comment by realfinder** [comment]
2016-01-18 work! do you fix it or it fixed by another change?

**Comment by wm4** [comment]
No, nothing was changed.
