### ISSUE TITLE
Different panel icon setup

### ISSUE THREAD

**Issue by toZen** [mpv-player/mpv#2176]
Hi there! Thx for amaizing player! Would you be so kind to give me some advise to how to setup my own panel icons, please?
I've tried already to swap them to my own into etc/ sources directory before compiling but there is no changes unfortunately. Also was operated with no success changing icons straight in to /usr/share/icons directory. Was swipe out icon.cache and other possible caches from my system. X server been restarted at the end of all actions I've made. As result there is steel default icon appears in taskbar area of tint2 panel.  All three icons are in appropriate resolution 16x16, 32x32, 64x64.
Think so you build in icons binary file. Is it true?
So is it possible or not to change them to my owns?
Arch Linux
WM: Openbox
Tint2 panel
Thank you for respond.

**Comment by wm4** [comment]
Generally, we don't support changing the window icon, so you have to do it manually.

You need to run ``TOOLS/gen-x11-icon.sh`` before compilation. It's not part of the build process, because it requires imagemagick, and requiring imagemagick as build dependency would be overkill.

**Comment by toZen** [comment]
Thx for respond wm4! Yes it's helped my partially. The icon in panel taskbar was successfuly changed to my own but smth is gone wrong with followed convertation to binary file.
Here is screenshot:
http://itmages.com/image/view/2820348/b8fae705
Sorry to interrupting you.
