### ISSUE TITLE
When fullscreen on primary display in Windows 8.1 mpv has increased CPU usage and drops frames when changing focus

### ISSUE THREAD

**Issue by lunik1** [mpv-player/mpv#2177]
On my multi-monitor set-up mpv significantly increases CPU usage when in focus and fullscreen on whichever monitor is designated as the primary display. This behaviour is observed when using the opengl and direct3d_shaders vo drivers.

In addition, when switching focus between mpv and another window when it is fullscreen on the primary display, both monitors will briefly flash black and mpv will report dropped frames. This is not observed when mpv is minimised, or fullscreen on a secondary display.

Edit: my mistake, neither of these effects are observed when using the direct3d_shaders driver. Also, the increased CPU usage when focused only seems to happen when interpolation is enabled.

**Comment by lunik1** [comment]
I also observe the CPU behaviour on a single-monitor setup

**Comment by hethhhhh** [comment]
I can confirm this. using `-vo direct3d_shaders` doesn't solve it for me. Primary monitor is not affected. Secondary monitor is having serious lagging issues on faster moving scenes. No increased CPU usage. tested `dwmflush=yes` with `-vo opengl` no change. OS is Windows 7 x64. Interpolation off. No dropped frames reported in console (verbose is default)

**Comment by wm4** [comment]
This brings me back to wondering whether ANGLE support would help.

But currently, it wouldn't give you access to most of mpv's OpenGL features.

**Comment by lunik1** [comment]
The framedrops/black flashes may be linked to fullscreen exclusive mode as I notice similar behaviour in other players when toggling such an option.

**Comment by hethhhhh** [comment]
framedrops are gone since last build (W7x64). I'm not experiencing flashing as @lunik1

**Comment by lachs0r** [comment]
Maybe this was the OSC doing something odd? Can you test the old builds with `--no-osc` to confirm or deny this?

The black flashes only happen with some drivers (known AMD problem), and AFAIK only in multi-monitor setups. Also, they only happen with OpenGL applications.

**Comment by lunik1** [comment]
I'm still having the problems on the latest x64 build and --no-osc does not seem to make a diference.

I'm seeing the black flashes on an nvidia card/drivers.

**Comment by lachs0r** [comment]
Does this build change anything? http://tmp.srsfckn.biz/mpv_ws.exe.xz
Should at least get rid of the black flashes.

**Comment by lunik1** [comment]
That seems to fix both issues

**Comment by elemongw** [comment]
I am experiencing the exact same issue with [this](https://mpv.srsfckn.biz/mpv-x86_64-20160229.7z) build and with default configuration on Windows 7. The only difference for me is that I didn't notice any difference in cpu usage. Should I open a new bug or is it fine here?
