### ISSUE TITLE
Direct3D + DXVA - visual glitches and gpu driver crashing

### ISSUE THREAD

**Issue by Skibicki** [mpv-player/mpv#2178]
Windows 7 x64, Catalyst 15.6, Radeon 6310, mpv x64 direct3d
OK: fccce81 
Fail: 176470b and a3a453b
Video flashes green and a couple frames, may also crash. Audio plays normally. Opengl is ok.
http://pastebin.com/wLffhkT3
Note: Catalyst 15.7 breaks dxva in all players.

**Comment by wm4** [comment]
Is it possible for you to git bisect this?

**Comment by wm4** [comment]
Although I suspect it's b85321d0573ba581694d2e6be1effafee74c11d1.

**Comment by Skibicki** [comment]
I would try but I don't have anything setup to build mpv.

**Comment by wm4** [comment]
Found another thing that _might_ have caused this.
