### ISSUE TITLE
Add this PPA ppa:djcj/vapoursynth to the installation page

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv#2179]
Can you add this PPA ppa:djcj/vapoursynth (https://launchpad.net/~djcj/+archive/ubuntu/vapoursynth) to the installation page (http://mpv.io/installation/) please.

It allow to install MPV with VapourSynth compatibility on Ubuntu.

Thank you.

**Comment by kevinlekiller** [comment]
I don't think it's appropriate, that page is for mpv source / packages.

If they do that, should they then add a link to the vapoursynth package for every package manager?

**Comment by Paviluf** [comment]
You didn't understand. This PPA provide a MPV build which is compatible with VapourSynth.
It also provide a VapourSynth build but that's not the point here.

**Comment by kevinlekiller** [comment]
Ah, that makes more sense, the PPA being named the way it is lead me to the confusion. I should have looked at the contents, sorry about that.

I think your recommendation is fine then, considering one of the PPA's on that list has a bunch of non mpv packages.

**Comment by wm4** [comment]
I don't know if we should add so many PPAs - there are already 2. What do others think?

**Comment by wm4** [comment]
Also, this is the wrong repo. Website requests go to the mpv.io repo.

**Comment by Paviluf** [comment]
> I don't know if we should add so many PPAs - there are already 2. What do others think?

The avantage of this one is the compatibility with VapourSynth.

> Also, this is the wrong repo. Website requests go to the mpv.io repo.

Sorry I didn't see the other repor.

**Comment by Paviluf** [comment]
I made the request on the right repo

https://github.com/mpv-player/mpv.io/issues/28
