### ISSUE TITLE
add sub_step as a default configuration

### ISSUE THREAD

**Issue by nim4n** [mpv-player/mpv#2181]
Hi I think the sub_step configuration must be in default configuration like the previous version of mplayer as: 
`vi ~/.mpv/input.conf`
`g sub_step -1`
`y sub_step +1`

**Comment by wm4** [comment]
It has been unmapped from these keys, because you accidentally hit them way too often. And getting back to the normal subtitle delay is not simple enough.

We could map them to keys with modifiers, like ``ctrl+g`` or such.

**Comment by nim4n** [comment]
It's good.

**Comment by wm4** [comment]
What? I interpret that as you don't want any change.

**Comment by nim4n** [comment]
No, I want this change!
