### ISSUE TITLE
compile/link failure on Raspberry Pi 2 running Raspbian Wheezy with --enable-mmal

### ISSUE THREAD

**Issue by axur-delmeria** [mpv-player/mpv#2182]
I used the mpv-build git source tree, and followed the Debian instructions.

I created an ffmpeg_options file at the mpv-build top-level directory, containing only the option --enable-mmal

Compiled pretty much OK (I guess) until this part:

[242/244] Compiling video/out/gl_common.c
[243/244] Compiling stream/rar.c
[244/244] Linking build/mpv
video/out/gl_common.c.12.o:(.data.rel.ro+0x4): undefined reference to `mpgl_set_backend_rpi'
collect2: error: ld returned 1 exit status

config.log here: http://pastebin.com/RrhTVnZC

compile output from terminal (incomplete, beginning not included) : http://pastebin.com/qRwX3kNE

Any idea what's causing the issue?

**Comment by wm4** [comment]
I think your config.h and waf are out of sync. Possibly this is caused by stale config.h files somewhere in the tree. Is this an old checkout? Try with a new mpv-build checkout and starting again.

**Comment by axur-delmeria** [comment]
I pulled the source from the mpv-build git just before I started compiling, so I don't think it's an old checkout. 

I'll try deleting everything  and pull it from git again. If that doesn't work, should I use the "use-ffmpeg-master" script to pull the latest ffmpeg source, or the "use-mpv-master" script? Or both?

BTW, does mpv support ASS subtitles when using the RPi 2's hardware decoder?

**Comment by wm4** [comment]
>BTW, does mpv support ASS subtitles when using the RPi 2's hardware decoder?

Yes, but it will be too slow even for simple subtitles.

**Comment by axur-delmeria** [comment]
> Yes, but it will be too slow even for simple subtitles.
Is it due to the lack of hardware opengl and xv acceleration in the driver?

Deleted everything and pulled from mpv-build. Compile still fails. http://pastebin.com/H13k46i0

Should I switch to the mpv release branch instead of master?

**Comment by axur-delmeria** [comment]
Also, should I compile the vc4 driver first? 
There's a build-bot according to this forum: https://www.raspberrypi.org/forums/viewtopic.php?f=81&t=115350

**Comment by wm4** [comment]
Paste your ``mpv/build/c4che/_cache.py `` and ``mpv/build/config.h``.

> Is it due to the lack of hardware opengl and xv acceleration in the driver?

No, the implementation of subtitles is just somewhat inefficient, in addition to libass eating a lot of CPU in the first place.

> Should I switch to the mpv release branch instead of master? 

No.

> Also, should I compile the vc4 driver first? 

No. Just use the firmware. I doubt the new Mesa driver provides anything with video hardware decoding yet, or even if, that mpv could use it currently.
