### ISSUE TITLE
Support libsixel as a video output option

### ISSUE THREAD

**Issue by HalosGhost** [mpv-player/mpv#2183]
One of the most creative libraries I've seen recently for those of us who may not wish to use X is [``libsixel``](https://github.com/saitoha/libsixel). It allows for the output of images directly in a terminal which supports it. As mpv still supports image outputs, this would not be dramatically different.

In fact, there is already a fork of ``ffmpeg`` that supports libsixel playback, so such a thing is not beyond possibility. However, I cannot estimate how much time/work it would be to implement this feature. Rest assured, I would deeply appreciate it if it ever gets implemented!

**Comment by wm4** [comment]
There's already ``--vo=drm``.

**Comment by HalosGhost** [comment]
I would ask you to reconsider. [``dvtm``](https://github.com/martanne/dvtm) may get libsixel support, and if/when it does, window management in the console may allow for libsixel images to be displayed only in the relevant window. ``--vo=drm`` is incredibly helpful for the moment, but it obscures the whole framebuffer which makes the use of things like ``dvtm`` as window managers less functional.

This kind of support would dramatically increase the usefulness of such tools to have a functional non-X workflow.

**Comment by wm4** [comment]
Maybe if someone else writes support. I'm not interested in such toy hacks. There are already 2 proper methods to do this, X and Wayland. Why a 3rd, hacked-together one?

**Comment by HalosGhost** [comment]
I realize it's a fairly niche use-case, so I completely understand your not being too interested in writing it yourself. But there are plenty of people who do not really feel the need for a full GUI; or, in my case, wish to escape it on some machines.

As I am likely to be one of the folks trying to implement sixel in ``dvtm``, if we are successful, I will take a look at creating  a PR for this on ``mpv``.

**Comment by haasn** [comment]
> But there are plenty of people who do not really feel the need for a full GUI

Then they should accept the loss of window management and other “full GUI” things, IMO.

That, or just use a “full GUI”. Whatever that means.

**Comment by thomasberryhill** [comment]
I'd just like to say that I'd be very interested in `libsixel` support as well.

I find the idea of an X-less workflow attractive, and I was very happy to learn of the existence of [yaft](https://github.com/uobikiemukot/yaft) (which, by the way, has sixel support) and [dvtm](http://www.brain-dump.org/projects/dvtm/) (which may have sixel support in the future). These programs add several interesting features to a tty that make it act more like a full window manager.

`libsixel` support for mpv would just be icing on the cake. I understand your disinterest in implementing it, but I'm sure there are more people than just @HalosGhost and I who would be intrigued by this feature. Thanks!

**Comment by tantei3** [comment]
@HalosGhost mpv now supports sixel playback through libsixel. Do give it a try!

**Comment by yosefbernal** [comment]
Hi all. I'm quite curious to try out this output driver, but when trying to launch `mpv --vo=sixel <MyVideo>` I get: 
```
 (+) Video --vid=1 (*) (h264 1280x720 30.000fps)
[vo] Video output sixel not found!
Error opening/initializing the selected video_out (--vo) device.
Video: no video
No video or audio streams selected.


Exiting... (Errors when loading file)
``` 

Not sure why as this seems to be supported and documented [on the mpb.io manual](https://[mpv.io](https://mpv.io/manual/master/#video-output-drivers-sixel)/manual/master/#video-output-drivers-sixel). 

Any clues why this is?

**Comment by CounterPillow** [comment]
@yosefbernal make sure your mpv is up to date, and build with libsixel support. A complete `--log-file` would tell us if you've done both of these; open a new issue if you still experience problems.

**Comment by CounterPillow** [comment]
@yosefbernal assuming you're on a Debian system:

```
sudo apt-get build-dep mpv
sudo apt install libsixel libsixel-dev
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build
./rebuild -j$(nproc)
```

Then symlink the resulting `mpv-build/mpv/build/mpv` binary to some directory in your `$PATH` (e.g. `~/.local/bin`), and uninstall the distro-provided mpv. Also symlink `/usr/share/man/man1/mpv.1` to `$your-dir-here/mpv-build/mpv/build/DOCS/man/mpv.1` if you want `man mpv` to work. There's also something to be done for the .desktop file but I don't remember from the top of my head.

**Comment by pycaw** [comment]
If `--vo=sixel` is supposed to be supported by default,
on Fedora 41, why do I get with `mpv --vo=help`,

> I am not asking for an "issue resolution" just some checklist one should follow when wanting sixel support as docs don't have such a thing as far as I could find.

_note: there's no sixel_
```
Available video outputs:
  gpu              Shader-based GPU Renderer
  gpu-next         Video output based on libplacebo
  vdpau            VDPAU with X11
  wlshm            Wayland SHM video output (software scaling)
  xv               X11/Xv
  sdl              SDL 2.0 Renderer
  dmabuf-wayland   Wayland dmabuf video output
  vaapi            VA API with X11
  x11              X11 (software scaling)
  libmpv           render API for libmpv
  null             Null video output
  image            Write video frames to image files
  tct              true-color terminals
  caca             libcaca
  drm              Direct Rendering Manager (software scaling)
  kitty            Kitty terminal graphics protocol
```

Mpv version:
```
mpv 0.39.0 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
libplacebo version: v7.349.0
FFmpeg version: 7.1.1
FFmpeg library versions:
   libavcodec      61.3.100 (runtime 61.19.101)
   libavdevice     61.1.100 (runtime 61.3.100)
   libavfilter     10.1.100 (runtime 10.4.100)
   libavformat     61.1.100 (runtime 61.7.100)
   libavutil       59.8.100 (runtime 59.39.100)
   libswresample   5.1.100 (runtime 5.3.100)
   libswscale      8.1.100 (runtime 8.3.100)
```

I have `libsixel 1.10.5-2.fc41` installed and I have other tools (like timg) perfectly utilize sixel protocol in my Konsole window.

**Comment by CounterPillow** [comment]
@pycaw report it to your distribution, they likely did not enable it during the build. The mpv build system's autodetection will pick up libsixel during build if it's present, but if your distribution's packaging does not declare it as a dependency then it won't be installed during build and won't be picked up.

**Comment by pycaw** [comment]
> [@pycaw](https://github.com/pycaw) report it to your distribution, they likely did not enable it during the build. The mpv build system's autodetection will pick up libsixel during build if it's present, but if your distribution's packaging does not declare it as a dependency then it won't be installed during build and won't be picked up.

I see, thank you, will experiment with different builds.

**Comment by JustArion** [comment]
Could we get a look at this for msvc please? Scoop recently changed their mpv target to this repo but libsixel isn't enabled on msvc. Windows Terminal recently (within the last few years) got Sixel support so the capability for sixel output on Windows is there.
