### ISSUE TITLE
[Win] "Drop files to play here." not shown when using vo=direct3d_shaders

### ISSUE THREAD

**Issue by sloppy9** [mpv-player/mpv#2184]
I'm using the latest win64 build (2015-07-30). It shows up with vo=opengl, but not direct3d/direct3d_shaders.

I've only recently updated from an older version which didn't have this issue, I still have the older version (2015-06-16) on my computer and it works as expected with output set to direct3d.

**Comment by kevmitch** [comment]
duplicate/related #2168

**Comment by kevmitch** [comment]
does it work with opengl?

**Comment by sloppy9** [comment]
@keymitch
Yes, I mentioned that in my comment.

**Comment by wm4** [comment]
Does it work if you resize the window after start? Do ASS subtitles work?

**Comment by sloppy9** [comment]
@wm4
Subtitles work and I can see the OSC, just the drag and drop splash screen is missing when I launch it

**Comment by wm4** [comment]
That doesn't answer my question, though.

**Comment by sloppy9** [comment]
Mmm could you clarify? I've tried resizing the window, and ASS subtitles are working.

**Comment by wm4** [comment]
So if you start mpv without a file, a black window appears, and resizing the window doesn't make the "drop files here" message show up either?

And this is only with direct3d_shaders, but not opengl?

**Comment by sloppy9** [comment]
Correct!

**Comment by wm4** [comment]
OK, no clue why that would happen.

**Comment by sloppy9** [comment]
That makes two of us! I recently updated to Windows 10, so I thought there may be an issue with the new video/directx drivers, but as I mentioned in my first comment, an older version of mpv doesn't display this problem.

If there's any other info I can provide, or tests to run, please let me know, thanks!

**Comment by wm4** [comment]
Actually, I've found the issue. It wasn't strictly related to direct3d_shaders. Fix coming soon.

**Comment by sloppy9** [comment]
Great job, thanks a lot!
