### ISSUE TITLE
Fonts of Chinese characters spontaneously switch to different sizes and/or typefaces.

### ISSUE THREAD

**Issue by akanosora** [mpv-player/mpv#2185]
I am using the Mac version of mpv. Sometimes when I am playing MKV files with external ASS subtitles, fonts of Chinese characters change to different sizes and typefaces spontaneously. It seems to me that mpv does not obey the rules defined in the ASS file. The same file plays properly without such issue in other media players such as VLC.

mpv:
![screen shot 2015-08-02 at 1 14 13 am](https://cloud.githubusercontent.com/assets/9272721/9024993/8ec32906-38b4-11e5-84db-767c052074e3.png)

VLC:
![screen shot 2015-08-02 at 1 19 31 am](https://cloud.githubusercontent.com/assets/9272721/9024994/99fe3842-38b4-11e5-8d2a-3f47254dcf88.png)

Notice the size of the character "沉" becomes larger in mpv, while in VLC, they all appear to be the same size.

Also mpv uses different typefaces for normal and italic styles although in the ASS file, both styles are specified to use the same size of the same typeface.

mpv:
![screen shot 2015-08-02 at 1 23 19 am](https://cloud.githubusercontent.com/assets/9272721/9025005/2ea2bcfc-38b5-11e5-9768-8dbc90520067.png)

VLC:
![screen shot 2015-08-02 at 1 26 21 am](https://cloud.githubusercontent.com/assets/9272721/9025014/835460de-38b5-11e5-9678-3aba003686ce.png)

Content of the ASS file:

```
[Script Info]
ScriptType: v4.00+
Collisions: Normal
PlayResX: 1280
PlayResY: 720
Timer: 100.0000
Synch Point:
WrapStyle: 0
ScaledBorderAndShadow: no
Video Zoom: 6
Scroll Position: 0
Active Line: 0
Video Zoom Percent: 1

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Hiragino Sans GB W6,60,&H00FFFFFF,&H0000FFFF,&H17000000,&HAC000000,0,0,0,0,100,100,0,0,0,2,3,2,20,20,65,1

[Events]
Format: Layer, Start, End, Style, Actor, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:05.07,0:00:16.36,Default,NTP,0000,0000,0000,,{\fs35}{\an8}若吾起舞時 麗人亦沉醉 若吾起舞時 皓月亦鳴響\N神降合婚夜 破曉虎鶇啼 遠神惠賜
```

**Comment by typcn** [comment]
Change a complete font , eg: Heiti or Helvetica Neue

**Comment by homever** [comment]
This is irreverent  to MPV itself. Like typcn said, you may need to change another font, try 'Hiragino Sans GB'. You can also create your own fonts.conf along with other config files in mpv folder.

**Comment by wm4** [comment]
Both mpv and vlc use libass for ASS subtitles. So I don't think this has much to do with mpv.

**Comment by akanosora** [comment]
Okay, so I solved the issue by copying the particular font to `~/.local/share/fonts`. But why doesn't mpv search for fonts installed under the default font folder of OS X (aka: `/Library/Fonts`)?

**Comment by wm4** [comment]
Because then mpv might spent several minutes waiting on fontconfig to scan the fonts.

Hopefully this will be solved with the libass fonts branch, which has native OSX font lookup support.
