### ISSUE TITLE
Doesn't work on osx 10.11

### ISSUE THREAD

**Issue by gotterfield** [mpv-player/mpv#2187]
On each of the public releases..
App opens but blank (black) window appears:
no "drag file here", only a black window.
Quit doesn't work, only force quit.

I think that with the new (beta) compiler can it works

Thanks to the all crew that support this awesome
(and fastest) player.

(excuse me for my bad english)

**Comment by pigoz** [comment]
AFAIK, you have to use the new compiler or beta SDK. Hopefully it's fixed on the final release!

**Comment by wm4** [comment]
Also see #2048.
