### ISSUE TITLE
Issue with interpolation when using ewa_lanczossharp

### ISSUE THREAD

**Issue by bobbundy** [mpv-player/mpv#2198]
When using the ewa_lanczossharp scale filter, interpolation is less "smooth" almost like it isn't even there. It works fine with spline36 and looks amazingly smooth. The hardware isn't being used either.  I tried with GPU decoding and then with the CPU, the CPU was barely being used according to the system load indicator. I use Ubuntu 14.04 with the proprietary nvidia drivers. Also in the terminal there was no mention of any dropped frames.

**Comment by haasn** [comment]
Sounds like your system is too slow. Can you monitor GPU usage? (Or use a tool like apitrace etc. to monitor time spent per frame)

**Comment by bobbundy** [comment]
The interpolation seems to look "normal" again. All I did was write the config file again to test, then things looked fine. I think the order in which I wrote the options caused the problem. Anyhow thanks for the help.

**Comment by Argon-** [comment]
The option's order should be irrelevant (excluding per-file options).
