### ISSUE TITLE
Opening Blu-ray disc ISO images directly

### ISSUE THREAD

**Issue by fturco** [mpv-player/mpv#2199]
This is a feature request. I'd like to open Blu-ray disc ISO images directly, as in:

    mpv br:// -bluray-device disc.iso

But that doesn't work right now. Let me quote mpv(1):

```
bd://[title][/device] --bluray-device=PATH
              Play a Blu-Ray disc. Currently, this does not accept ISO  files.
              Instead,  you  must  mount the ISO file as filesystem, and point
              --bluray-device to the mounted directory directly.
```

**Comment by wm4** [comment]
Apparently we'd have to implement a ISO filesystem (because libbluray doesn't want to). But we don't want to do this either, so this is a WONTFIX. I wouldn't reject a patch, though.

Just mount it instead.

**Comment by lachs0r** [comment]
Also, in fact, UDF 2.50 rather than ISO9660.

Apparently libcdio supports this though. So actually a patch that implements generic disc image support through that library would be welcome.

**Comment by wm4** [comment]
libdvdread also does. But libbluray considers this the responsibility of the application using the lib.

**Comment by Kagami** [comment]
@lachs0r @wm4 seems like UDF support was added to libbluray:
https://www.mail-archive.com/libbluray-devel@videolan.org/msg01781.html

**Comment by Kagami** [comment]
It actually works just fine now, at least for me on a test BD ISO file. I think you can readjust manpage.

```
$ mpv bd:// --bluray-device=THE_MORTAL.ISO
Playing: bd://
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 --alang=jpn (pcm_bluray)
AO: [alsa] 48000Hz stereo 2ch s32
VO: [opengl-hq] 1920x1080 yuv420p
AV: 00:00:04 / 02:08:45 (0%) A-V:  0.000
```

(You need to build libbluray with `--enable-udf` for this.)
