### ISSUE TITLE
Buggy resize behavior when maximized

### ISSUE THREAD

**Issue by DerpMcDerp** [mpv-player/mpv#2202]
Whenever mpv loads a movie that has a different size than the current movie, it resizes the player window to fit the new movie size.

On MS Windows, if the player window was maximized, the size of the window will change but the window state continues to stay as maximized rather than restored (i.e. mpv changes the size of the window in the current maximized state rather than the size of the window in the restored state).

What mpv should do instead is call the `SetWindowsPlacement` function to alter the `WINDOWPLACEMENT::rcNormalPosition` member. This has the side benefit of keeping maximized windows maximized and only affecting the window size if it gets restored.

**Comment by pavelxdd** [comment]
The same issue can be reproduced without loading a new video file:

- maximize the mpv window
- apply `window-scale` (via hotkey, or any other way)

As a result, mpv will change its window size, but the maximized state will stay active.

**Comment by Akemi** [comment]
please open a new issue if this problem still persists.
