### ISSUE TITLE
Break too long lines with no spaces in OSD (or at least cut out the middle)

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#2203]
![mpv-shot0004](https://cloud.githubusercontent.com/assets/1218098/9126106/608f226c-3ca9-11e5-9bd4-9aae3e7aa951.jpg)
When browsing several subtitles with filenames that are long and do not contain spaces, the osd with the filename overflows the screen (see screenshot). The vital information (file extension) is often at the end so this is especially painful. To possible remedies:
1)Break those filenames at underscores,dashes,dots or anywhere
2)always display the beginning and the end of the filename with a few dots in the middle like this:
a_very_long_name_of_my_subtitle_file.srt would become a_very_lo..._file.srt

Workaround. One can set the OSD font to be smaller with `osd-font-size=36`. But this means nice experience is not by default.

**Comment by wm4** [comment]
Requires changes in libass.

**Comment by felagund** [comment]
I will gladly open a bug here: https://github.com/libass/libass/issues but I have no idea how I would describe it as I know nothing about the technical details.

**Comment by Akemi** [comment]
reported upstream kinda https://github.com/libass/libass/issues/348
