### ISSUE TITLE
16:10 aspect ratio.

### ISSUE THREAD

**Issue by empire1924** [mpv-player/mpv#2204]
Hi!
I would like to thank you for this product.I truly believe has the lowest cpu/memory usage than any other media player.
I'm on win 10 right now and my only issue is the aspect ratio.I checked all the scales(shift+A) but unfortunately there is no 16:10.Can you plz add 16:10 in one of the next builds?

Thanks in advance.

**Comment by ChrisK2** [comment]
Do you really have a 16:10 video with incorrectly tagged aspect ratio or do you just want to make a 16:9 video fill your 16:10 screen?

(The feature is intended to fix files with incorrectly tagged aspect ratios, not to distort a correct one.)

**Comment by avih** [comment]
But still, if you want to distort your videos also to 16:10, add this line to your `input.conf` file:
`A cycle-values video-aspect "16:9" "16:10" "4:3" "2.35:1" "-1"`

This will use shift-a to cycle also through 16:10.

**Comment by empire1924** [comment]
I just want to make a 16:9 video fill my 16:10 screen.
I checked all the scales via (shift+A) and i just didnt found this option.

**Comment by avih** [comment]
It can't fill the screen because it has a differnt aspect ratio than your screen. But you can zoom in using 'e' to fill the screen, and zoom out using 'w'. Or distort it with the `input.conf` line.

**Comment by wm4** [comment]
Put ``panscan=1`` in your config file, or use the ``w`` and ``e`` keys.

**Comment by empire1924** [comment]
Thanks for the answers/tips/info but unfortunately there is no configuration file 'mpv.conf' in the /usr/local/etc/mpv/ its just empty....wtf! lol
