### ISSUE TITLE
Resizing window does not scale video (with vo_xv) while not paused

### ISSUE THREAD

**Issue by lvml** [mpv-player/mpv#2208]
I'm experiencing a strange little bug with mpv compiled from current git head:

When I resize a (non-fullscreen) mpv window while a video is playing, often (about 8 out of 10 times) mpv does not seem to take notice of this and does not scale the video, so after enlarging the window only the upper left area of it is used, after decreasing the window size only the upper left part of the video is visible in the then-too-small window.

If I pause the replay and do the same window resizing, mpv always scales the video to the size of the window. 

The environment: linux-4.1, fvwm2, vo_xv (no hardware accelleration available on that computer).
I have not experienced this bug on two other computers running the same operating system, kernel and window manager, but using other vo's (so vo_opengl and vo_vdpau do not exhibit the symptom).

Any idea how to debug/fix this?

**Comment by wm4** [comment]
Can't reproduce. Also, xv and opengl/vdpau use the same windowing code.

**Comment by lvml** [comment]
Can you recommend some debug-log option or alike to help finding the cause?

**Comment by wm4** [comment]
You could try ``--msg-level=vo=debug`` (or trace).

**Comment by lvml** [comment]
When using --msg-level=vo=debug, the following is output when I resize the window while paused (which works fine):
```
[vo/xv] aspect(0) fitin: 970x776 monitor_par: 1.00
[vo/xv] aspect(1) wh: 970x776 (org: 720x576)
[vo/xv] aspect(2) wh: 970x776 (org: 720x576)
[vo/xv] Window size: 970x776
[vo/xv] Video source: 720x576 (720x576)
[vo/xv] Video display: (0, 0) 720x576 -> (0, 0) 970x776
[vo/xv] Video scale: 1.347222/1.347222
[vo/xv] OSD borders: l=0 t=0 r=0 b=0
[vo/xv] Video borders: l=0 t=0 r=0 b=0
[vo/xv] xv_get_eq called! (bt_709, -100)
```

When I do the same while the video plays, there is no such output - nothing is emitted on the command line, and the video is not scaled (so it seems mpv is really "just not taking notice" of the window resize).

But I noticed one more thing: Several actions that I can do on the window (not only resizing, also moving and alike) cause the following message to be emitted (but only once for each mpv run):
```
[vo/xv] X11 can't keep up! Waiting for XShm completion events...
```
Could this be some timing issue? However, the low-resolution video I replayed in the example does not really put stress on the system...

**Comment by lvml** [comment]
When using --msg-level=vo=trace, this is the output (around the time of window resizing) of the  "paused, works" and the "unpaused, does not scale" cases:

Paused:
```
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 22
[vo/xv/x11] XEvent: 12
[vo/xv/x11] XEvent: 12
[vo/xv/x11] XEvent: 28
[vo/xv] aspect(0) fitin: 934x747 monitor_par: 1.00
[vo/xv] aspect(1) wh: 934x747 (org: 720x576)
[vo/xv] aspect(2) wh: 934x747 (org: 720x576)
[vo/xv] Window size: 934x747
[vo/xv] Video source: 720x576 (720x576)
[vo/xv] Video display: (0, 0) 720x576 -> (0, 0) 934x747
[vo/xv] Video scale: 1.297222/1.296875
[vo/xv] OSD borders: l=0 t=0 r=0 b=0
[vo/xv] Video borders: l=0 t=0 r=0 b=0
[vo/xv] xv_get_eq called! (bt_709, -100)
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 2
```

Unpaused:
```
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv] X11 can't keep up! Waiting for XShm completion events...
[vo/xv/x11] XEvent: 22
[vo/xv/x11] XEvent: 12
[vo/xv/x11] XEvent: 12
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 28
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
[vo/xv/x11] XEvent: 65
```

**Comment by lvml** [comment]
I just noticed the "info-needed" tag was added - what additional information can I provide?

**Comment by wm4** [comment]
I don't know, but I have no idea what's wrong.

**Comment by lvml** [comment]
Well, since this symptom occurs only on that one system and the work-around (pause/unpause) is simple, let's put this issue to rest, for potential revival if somebody else sees a similar symptom :-)

**Comment by lachs0r** [comment]
Yeah, let’s do that.
