### ISSUE TITLE
Screenshots not always being saved at screenshot-directory

### ISSUE THREAD

**Issue by radgeRayden** [mpv-player/mpv#2215]
I'm using mpv 0.9.2 on windows, and set the screenshot-directory on my mpv.conf so they go to C:\Users\(me)\Pictures\mpv. It works more or less half of the time, but part of the screenshots are still being saved to the Desktop.

**Comment by wm4** [comment]
See #2218, which is exactly the same issue. For windows-specifics, it depends whether mpv is started from the explorer or from the terminal as mpv.com, or something like this. If it assumes it's started in a GUI context, pseudo-gui mode is enabled, and the normal defaults are overridden.
