### ISSUE TITLE
screenshot-directory ignored when mpv is launched via file launcher

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#2218]
I am not sure if this is desired, but I do not read the docs in this way:

>Store screenshots in this directory. This path is joined with the filename generated by screenshot-template. If the template filename is already absolute, the directory is ignored.

>If the directory does not exist, it is created on the first screenshot. If it is not a directory, an error is generated when trying to write a screenshot.

>This option is not set by default, and thus will write screenshots to the directory from which mpv was started. In pseudo-gui mode (see PSEUDO GUI MODE), this is set to the desktop.

I set the option in config file to point it to Desktop. When I launch mpv in terminal with `mpv /path/to/file.mp4`, it saves the screenshots to Desktop. When I click a file in Nautilus and it starts playing ,screenshots are saved to my home directory. First, the docs do not state that this is the case, and if this is desired, it does not make any sense to me. I set the option, why should it behave differently depending on the way I launch MPV? My version is `mpv git-f72028d (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-06-09`.

**Comment by mc4man** [comment]
For launching via nautilus (mpv.desktop) set the screenshot-directory= path in mpv.conf > [pseudo-gui] section

**Comment by felagund** [comment]
Ah, I see. Not that having to set this twice makes much sense to me, but could the docsplease beclearer. So
 instead:
>This option is not set by default, and thus will write screenshots to the directory from which mpv was started. In pseudo-gui mode (see PSEUDO GUI MODE), this is set to the desktop.

something like:
> Unless this option is set, the screenshot will be saved to the directory from which mpv was started. Please note that this option only takes effect when mpv is launched from the command line. When mpv is launched from the gui, the default is the home directory. See PSEUDO GUI MODE to learn how to change the default saving directory in case you launch mpv from GUI.

Please note that the docs are wrong - it defaults to my home directory, not desktop, at least on my machine.

**Comment by wm4** [comment]
Pseudo GUI mode is implemented by forcing a profile with a few option set (as documented). This is not really ideal, so better ideas are welcome.

There is no standard desktop on Linux, so we default to the home directory there. Or to be more precise, Win32 and OSX provide simple ways to get a standard location, while on Linux there is only misery so we don't bother. I guess you're on Linux (or BSD or some other unix).

**Comment by felagund** [comment]
Yep, linux.  Regarding the docs, I think this makes it clear:

>Unless this option is set, the screenshot will be saved to the directory from which mpv was started. Please note that this option only takes effect when mpv is launched from the command line. When mpv is launched from the gui, the default is the Desktop directory on OS X and Windows and Home directory on Linux. . See PSEUDO GUI MODE to for information on changing the default saving directory in case you launch mpv from GUI.

As for suggestions, just try to first read the setting of `screenshot-directory` from mpv.conf and only default to what is the default once the option is not set. Or am I missing something why this could not work like that you have to have some profile before you can read mpv.conf? Why does have to screenshot direcotry be set so early?

**Comment by wm4** [comment]
If we did this, no profile could override an already set option in the config file. Which is not the right thing.

**Comment by felagund** [comment]
Ah, I see, I had no idea profiles actually existed (by the way, in the section on profiles, I think it should be stated that ome actually uses profile by passing --profile=profilename on the command line.)

So why just not read this setting if it is not set in [pseudo-gui], then

1) no `screenshot-directory` is set anywhere, => both cmd and gui default to desktop/home on linux
2)  `screenshot-directory` is set in general options and not in any given profile (including [pseudo-gui] => always use what is set by `screenshot-directory`
3) `screenshot-directory` is set in general options and also in some profile that is invoked (including [pseudo-gui] =>use what is set for the given profile.

Sounds reasonable to me, is there some technical objection to it?

**Comment by wm4** [comment]
>2) screenshot-directory is set in general options and not in any given profile (including [pseudo-gui] => always use what is set by screenshot-directory
>3) screenshot-directory is set in general options and also in some profile that is invoked (including [pseudo-gui] =>use what is set for the given profile.

That would be awfully complicated and doesn't even make much sense.

**Comment by felagund** [comment]
Could you at least please update the docs regarding the default directoyr being $HOME on Linux (I mean, to understand what is going on, one now needs to go from `http://mpv.io/manual/master/#screenshot` in  http://mpv.io/manual/master/#screenshot to http://mpv.io/manual/master/#pseudo-gui-mode and then to http://mpv.io/manual/master/#paths which is very complicated.) 

However, I do not see what is so complicated about it

1) and 3) Is already the case, if I understand it correctly (it is just not documented clearly at all).

2) when forcing a pseudo-GUI profile, instead of taking the default ~/Desktop value, first try to read `screenshot-directory` from the config file and only then default to ~/Desktop (that seems like one if statement)
