### ISSUE TITLE
autoload.lua doesn't work as it should after its latest commit

### ISSUE THREAD

**Issue by crisalis** [mpv-player/mpv#2219]
Let's say I have a directory with 50 Matroska videos, and I open the first one of them.
If I press the 'enter' key repeatedly in order to go to the next videos loaded by autoload.lua, there will be a moment where it won't allow me to go to the next video anymore.
For some reason, at least for me, it usually only allows going to the next file either ten or five times.

Is this behaviour intentional?

The autoload.lua previous to its latest commit works properly.

**Comment by wiiaboo** [comment]
Confirmed that last commit caused it.
Trying to find a way to make both behaviors work.
Managed to make it work if you open a single file (autoload runs) and load more than one file (autoload doesn't run), but not if you load a single playlist file.

**Comment by Neffistopheles** [comment]
Would it not be desirable to just lift the max entries limit, or make it very high? So that autoload.lua just populated the entire directory.
