### ISSUE TITLE
OS X 10.11: [vo/opengl] error creating CGL context: invalid pixel format

### ISSUE THREAD

**Issue by zmwangx** [mpv-player/mpv#2221]
I get the following error when I try to play any video file (or any audio file when `--force-window`) on OS X 10.11 PB3 or PB4 (running inside VMware Fusion 7.1.2; details about my `mpv` installation can be found at the end):

```
[vo/opengl] error creating CGL context: invalid pixel format (10002)
Error opening/initializing the selected video_out (-vo) device.
```

(With default settings, `mpv` emits the error above but does not quit immediately, but there is no video — audio plays fine; with `--force-window`, `mpv` emits the error above and quits immediately.)

Here is a debug log: https://gist.github.com/zmwangx/16595b384a4e66afe9c6 generated with `mpv --no-config --force-window --msg-level=all=debug`, but I'm afraid it's not very useful.

So, has anybody encountered a similar error (it seems that [other people can run `mpv` on 10.11 just fine](https://github.com/mpv-player/mpv/issues/2048), except some warnings)? Or have an idea of what might cause the error?

In fact, some of my deps were persisted through out PB1 to PB4, so I'm not sure if some dep is at fault. I'll try to rebuild all the deps if everything else fails, but I'd rather not do that since building several dozen deps inside a VM running on a MBP is not fun.

---

My `mpv` is built from latest master via Homebrew, with the options

```
--with-libaacs --with-libbluray --with-libbs2b --with-libcaca --with-libdvdnav --with-libdvdread --with-official-libass --with-vapoursynth`
```
My `ffmpeg` is 2.7.2_1 built via Homebrew, with the options

```
--with-fdk-aac --with-ffplay --with-freetype --with-frei0r --with-libass --with-libbluray --with-libcaca --with-libquvi --with-libvidstab --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-openssl --with-opus --with-rtmpdump --with-schroedinger --with-speex --with-theora --with-tools --with-x265
```

**Comment by Cpuroast** [comment]
I suspect that the issue is caused by running inside a VM and not OSX 10.11.
Any kind of OpenGL/3D acceleration in VMs has never been great.

**Comment by zmwangx** [comment]
That's certainly possible. Could you reproduce?

**Comment by pigoz** [comment]
Looks like some OpenGL pixel format attribute required by mpv is not recognized.

Since [the OpenGL API diffs](https://developer.apple.com/library/prerelease/mac/releasenotes/General/APIDiffsMacOSX10_11/Objective-C/OpenGL.html) list no change I am assuming this is a OS X bug, or a OS X in a VM bug, or maybe some ABI breakage.
