### ISSUE TITLE
Does mpv support load .lrc lyrics?

### ISSUE THREAD

**Issue by Guanrenfu** [mpv-player/mpv#2222]
Hi everyone.
I want to load a lrc lyrics file use mpv, but I can't find that option.

So dose mpv support load .lrc lyrics?

**Comment by wm4** [comment]
It exists in ffmpeg, but is not whitelisted in mpv. Do you have a sample file?

**Comment by wm4** [comment]
Actually, I found a sample, and it works out of the box (if you compile mpv against ffmpeg and not Libav). Use it as subtitle (``--sub-file``).

**Comment by Guanrenfu** [comment]
@wm4 Hey, it's working. Thank you :)
