### ISSUE TITLE
autoload.lua freezes osc when changing video in fullscreen mode

### ISSUE THREAD

**Issue by edo44** [mpv-player/mpv#2223]
As the title said, when I'm watching a video in fullscreen and I'm trying to change the video in the playlist, the osc disappears (default osc) or it freezes (bottombar).

I have everything updated of course. Infact when I am using the 1 month old mpv version I don't have this problem.

**Comment by wm4** [comment]
Too many files?

**Comment by lachs0r** [comment]
I suppose something triggered an error condition in the OSC code. It’s changed a lot, so reopen this if you’re still able to reproduce this. Attach a log file this time.
