### ISSUE TITLE
Sub-scale-by/with-window confusingly named (and sub options in unexpected places in the docs) and buggy in one case

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#2224]
Just making a new issue out of https://github.com/mpv-player/mpv/issues/393#issuecomment-129252016 so that it does not get lost:

1)Well, first, in the man page, it would make sense to group `--sub-text-font-size=<size>` and `--sub-text-font=<pattern>`  with subtitle options, not with OSD (it took me a lot of time to find out how to set the subtitle font size, I did not expect it to find under OSD. The many more options there should be moved to subtitles section too. If somebody wants the osd and subtitles behave the same way, a swtich [new option, yay!] could be introduced like `osd-sub-keep-same` with values osd/sub/no, default not, and osd would mean corresponding options for osd would take precedence and sub would mean corresponding sub options would take precedence if both were present in the config).

2)Second, I think `sub-scale-by-window=no` should make the setting of `sub-scale-with-window` irrelevant, especially if it were renamed as per my suggestion below. This is actually a bug, because the documentation says that changing the window size with this disabled wont change the subtitle size, which is not true when the second option is enabled (docs are true when the window is resized horizontally, but sub size changes when the window is resized vertically).

3) For  `sub-scale-by-window`, I would go along something like `sub-keep-size` (or `sub-keep-size-on-window-resize` if you wanted to be eloquent). - I am not sure if there is a system to option so that "font" and "text" should be added to the options name.

For `sub-scale-with-window`, I would go for `sub-keep-vertical-proportion-to-video` or `sub-scale-with-video`, and I would switch the meaning of yes and no (no would do what yes now does). Because this is what turning this off means - the subtitles always take the same portion of the vertical space of the video regardless of its horizontal dimension. This actually might make sense for people who do not want to have the subtitles in the black margin below video but instead prefer subtitles in the video.

**Comment by Akemi** [comment]
if this issues still persists, please open a new issues for all of them.
