### ISSUE TITLE
Improve the play speed UI

### ISSUE THREAD

**Issue by DerpMcDerp** [mpv-player/mpv#2225]
- [ ] The `{ and }` and `[ and ]` keys to manipulate the play speed aren't as user friendly as they could be (e.g. to undo "{ [ [ [" you have to do "] ] ] }" in that exact order). What mpv should do instead is snap the play speed to an evenly spaced grid between each power of 2 rather than naively multiplying the playback_speed by 200% or 10%. e.g. something like:

``` C
// must be a power of 2
#define MAX_PLAY_SPEED (64.0)
// must be a power of 2
#define PLAY_SPEED_QUANTA (128)

// 1. clamps values to the range [1/MAX_PLAY_SPEED, MAX_PLAY_SPEED]
// 2. snaps values to the nearest logarithmically scaled grid point
double clamp_proportion(double value) {
    // !(a > b) is true for NaNs, (a <= b) isn't
    if (!(value > 1.0 / MAX_PLAY_SPEED))
        return 1.0 / MAX_PLAY_SPEED;
    else if (value >= MAX_PLAY_SPEED)
        return MAX_PLAY_SPEED;

/*
The following statements are only needed to handle the cases of the user using
degenerate --speed values or if they customized the keys with non-power of 2s.
They are equivalent to "return value;" otherwise.
*/

// scale it down to the unit vector
    double mag = exp2(floor(log2(value)));
    double frac = value / mag - 1.0;

// snap it to the nearest quanta point then scale back
    return mag * (1.0 + (1.0 / PLAY_SPEED_QUANTA) * round(frac * PLAY_SPEED_QUANTA));
}

double proportion_add(double value, double proportion) {
    double mag = exp2(floor(log2(value)));
    if (proportion < 0.0 && mag == value) {
        mag *= 0.5;
    }
    return value + proportion * mag;
}
```
- `]` does `playback_speed = clamp_proportion(proportion_add(playback_speed, 0.125))`. 12.5% = 1/8. This constant should be a multiple of (1 / PLAY_SPEED_QUANTA).
- `[` does `playback_speed = clamp_proportion(proportion_add(playback_speed, -0.125))`
- `{` does `playback_speed = clamp_proportion(playback_speed * 0.5)`
- `}` does `playback_speed = clamp_proportion(playback_speed * 2.0)`

It's important that the 3 constants be powers of 2 so that there is no rounding when you arbitrarily traverse it with `{ and }` or `[ and ]`.

After the above changes, the manual can say "[ and ] Decrease/increase current playback speed by about 12.5%"
- [ ] Fractional play speeds are difficult to grasp at a glance. mpv should display them as negative magnitudes instead (e.g. "-2.00x" rather than "0.50") in the OSD. This isn't as simple as `play_speed < 1 ? -1 / play_speed : play_speed`, it has to take the ratio of distances between powers of 2 for it to display symmetrically. i.e.

``` C
// converts (0, MAX_PLAY_SPEED] to [-MAX_PLAY_SPEED, MAX_PLAY_SPEED]
// for display purposes
double pretty_proportion(double value) {
    assert(value > 0);
    if (value < 1) {
        double s = exp2(-floor(log2(value)));
        value = 0.5*s*(s*value - 3.0);
    }
    return value;
}
```
- [ ] `--speed` should be altered to accept numbers in [-64, -1) or [1/64, 64] to match the above behavior. Numbers in the range [-64, -1) will automatically be converted to the range (0, 1). This is a breaking change since mpv currently lets you specify numbers in the range [0.01, 1/64) or (64, 100]. This can trivially be made non-breaking by using 128 instead of 64 though I'm skeptical of play speeds this huge (for reference mpc-hc uses to [1/8, 4] and Windows Media Player uses [1/2, 8] as the play speed bounds). Here is the conversion code to handle negative numbers that are assumed to be in the symmetric display format:

``` C
// converts [-MAX_PLAY_SPEED, MAX_PLAY_SPEED] to (0, MAX_PLAY_SPEED]
double unpretty_proportion(double value) {
    assert(value < -1 || value >= 1.0 / MAX_PLAY_SPEED);
    if (value < 0) {
        double s = exp2(-floor(log2(-value)));
        value = 0.5*s*(s*value + 3.0);
    }
    return value;
}
```

**Comment by cloph** [comment]
don't see real need for this, as you can always reset to 1.0 speed using backspace and start from there. Why is it important to exactly undo a speed-change mixing the double and 10% ones?

Also I find half speed to be displayed as 0.5 pretty straight forward. If I'd see "-2.0" I'd expect it to play in reverse with double speed. While I don't care much about the first part, as long as it results in similar speeds as multiple ] presses do now, I'm against changing slower speed to negative labels.

**Comment by DerpMcDerp** [comment]
The code for the first part makes it so that the play speeds traverse the following fixed grid (unless the user messes with custom `--speed`s) where the `{ and }` keys move the speed ±8 steps and the `[ and ]` keys move the play speed ±1 step. e.g. Pushing the `{` key on `2.25` takes it to `1.125`. Pushing the `[` key on `2.25` takes it to `2`:

```
1
	1.125
	1.25
	1.375
	1.5
	1.625
	1.75
	1.975
2
	2.25
	2.5
	2.75
	3
	3.25
	3.5
	3.75
4
	4.5
	5
	5.5
	6
	6.5
	7
	7.5
8
	9
	10
	11
	12
	13
	14
	15
16
	18
	20
	22
	24
	26
	28
	30
32
	36
	40
	44
	48
	52
	56
	60
64
```

(the fractional play speeds have a similar pattern).

> don't see real need for this, as you can always reset to 1.0 speed using backspace and start from there.

mpv effectively requires there be a key to reset the playback speed (and requires you to remember that it's bound to the backspace key) in order for you to set it back to 1.0. Having grid traversal makes the reset key a convenience rather than a necessity.

e.g. push "} [" and now try to reset it back to 1.0 without using the backspace key. If you forgot that "} [" was the key sequence and you push "[ [ [ [ [ [" to try and undo it, you end up at "1.03". It's very difficult to get back to 1.0 without remembering the exact key sequence or by pushing the backspace key.

A minor issue is that mpv doesn't use power of 2 numbers so it accumulates round-off errors.

> Also I find half speed to be displayed as 0.5 pretty straight forward. If I'd see "-2.0" I'd expect it to play in reverse with double speed.

"0.5" is a contrived fraction that is easy to understand but the fractions in general are not. e.g. it's obvious at a glance that "-7.00" means "700% slower" but it's not obvious what "0.16" means without pausing to think about it. Using negative numbers for fractional amounts have precedence elsewhere (e.g. decibels or logarithms in general).

**Comment by wm4** [comment]
I can't say I care about this at all. And I'm not convinced that this would allow us to drop the key for speed resetting, but that's the part that still makes me actually slightly interested in this.

You could try writing a patch, if it's not too intrusive.

**Comment by kevmitch** [comment]
Issue seems dead. No patch happened and no one is too excited about this idea anyway.
