### ISSUE TITLE
no seekbar on the windows builds of mpv

### ISSUE THREAD

**Issue by fishoo** [mpv-player/mpv#2228]
I am using mpv on windows xp and the OSC show up when the mouse is moved inside the player window. But there are only "skip back", "seek back", "play", "seek frwd", "skip frwd" and "full screen". No "seekbar", "time passed", "time remaining", and "title" etc.are found. I don't modify the configuration and use the default one. The mpv is downloaded from http://mpv.srsfckn.biz and the file is http://mpv.srsfckn.biz/mpv-i686-20150803.7z
![mpvyx1](https://cloud.githubusercontent.com/assets/13816097/9292162/726e999e-441b-11e5-8097-cc5131d21ed3.PNG)

**Comment by lachs0r** [comment]
This apparently only affects the 32-bit builds.
I guess there is a bug in libass’ `fonts` branch that only affects the 
fontconfig code path.

(Also, Windows XP support is going to be dropped in the foreseeable future.)

**Comment by fishoo** [comment]
I test to modify the configuration and the layout for the OSC is set to bottombar. But the bottombar is nearly disappeared and a little part of it is shown in red box in picture below.  The topbar.is similar to the bottombar.
![mpvyx22](https://cloud.githubusercontent.com/assets/13816097/9292499/14f31f24-442f-11e5-8e62-25083de88fbf.PNG)

**Comment by lachs0r** [comment]
It looks like on Windows XP, libass actually doesn’t select the fontconfig path at all. It tries to load DirectWrite, fails, but still “uses” that font provider. That’s why you’re getting that result.

Embedded fonts (like Matroska attachments) will still work, though.

**Comment by lachs0r** [comment]
Also closing this because it is a libass bug, but I’ll post here once it’s fixed.

**Comment by lachs0r** [comment]
Should work now.
