### ISSUE TITLE
How to disable multimedia keys support?

### ISSUE THREAD

**Issue by hackeron** [mpv-player/mpv#2231]
mpv currently hijacks the multimedia keys if it is running, making it impossible to go to the next track in spotify. It is good multimedia keys are supported, but is there any easy way to disable them for mpv?

**Comment by ChrisK2** [comment]
Assuming OS X: [``--input-media-keys=<yes|no>``](http://mpv.io/manual/master/#options-input-media-keys)

**Comment by hackeron** [comment]
Ah, thank you, I have been trying to get something in input.conf - that's great this feature is so easy to enable/disable, thank you, works! :)

**Comment by arbitrary-dev** [comment]
>(OS X and Windows only)

Would be nice if it'd work for Linux also.

Otherwise something like this is required:
```
$ cat ~/.config/mpv/input.conf
MUTE        ignore
VOLUME_UP   ignore
VOLUME_DOWN ignore
```

This leads to a following problem:
1. Mute volume with media key
2. Run `mpv some-video.avi`
3. Press volume toggle media key again
4. System unmutes sound, but `mpv` mutes sound
