### ISSUE TITLE
Switching 'Mute' mutes all mpv instances

### ISSUE THREAD

**Issue by teto** [mpv-player/mpv#2233]
Sometimes I start 2 videos and want to mute one of the two (because it has subtitles or I am just skipping through it to search for a specific moment). If I press M, it mutes all windows: thus one can't watch a movie while working/sorting other videos.
In case it is a feature I will back off since it's not critical but I find this behavior strange.
Version:
[cplayer] mpv 0.8.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[cplayer]  built on 2015-02-19T17:03:21

**Comment by wm4** [comment]
- you might be using pulseaudio; then not our fault, use ``--softvol=yes``
- you're using ``--softvol=yes``, then don't use it
- also your mpv build is ancient

**Comment by wm4** [comment]
Fixed a mistake in my previous post.

**Comment by teto** [comment]
It fixes it indeed sry for the trouble.
