### ISSUE TITLE
screenshot not work with videotoolbox(OS X 10.11 Public Beta 5)

### ISSUE THREAD

**Issue by cwbsw** [mpv-player/mpv#2237]
When I disable videotoolbox by `hwdec=no`, I can successfully capture screenshot. This is the error message and my environment:

    [cplayer] Error when converting image.
    [cplayer] Error writing screenshot!

    [cplayer] mpv git-da8a9ff (C) 2000-2015 mpv/MPlayer/mplayer2 projects
    [cplayer]  built on Tue Aug 18 13:54:08 CST 2015
    [cplayer] ffmpeg library versions:
    [cplayer]    libavutil       54.30.100
    [cplayer]    libavcodec      56.57.100
    [cplayer]    libavformat     56.40.101
    [cplayer]    libswscale      3.1.101
    [cplayer]    libavfilter     5.34.100
    [cplayer]    libswresample   1.2.101
    [cplayer] ffmpeg version: git-2015-08-17-21566b2
    [cplayer] Configuration: waf configure --prefix=/usr/local/Cellar/mpv/HEAD --enable-zsh-comp
    [cplayer] List of enabled features: apple-remote asm atomics av-pix-fmt-mmal av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples bsd-fstatfs build-date cocoa coreaudio cplayer debug-build dlopen dvdnav dvdread encoding fchmod gl gl-cocoa glob iconv jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libm libswresample lua nanosleep optimize osx-thread-name posix posix-or-mingw posix-spawn pthreads resampler shm stdatomic subprocess termios tv vda-default-init2 vda-gl vda-hwaccel videotoolbox-gl videotoolbox-hwaccel videotoolbox-vda-gl zlib zsh-comp

**Comment by wm4** [comment]
Does it work on older OSX versions?

**Comment by cwbsw** [comment]
I can only make sure that everything is ok on 10.10.4, and I'm not sure whether the screenshot failure is due to switch to videotoolbox or beta version's bug. Maybe it's a better choice to deal with it after Apple's official release of 10.11.
