### ISSUE TITLE
Last item of .lrc is not shown

### ISSUE THREAD

**Issue by fqj1994** [mpv-player/mpv#2244]
The last item in a .lrc is not shown.

lrc:
```
[00:00.000] 0s
[00:00.27] 0.27s
[00:00.82] 0.8s
[00:01.82] 1.8s
[00:03.82] 3.8s (but not displayed)
```

`mpv xxx.mp3 -sub xxx.lrc --no-video`

You will find the 3.8s's lyric is not shown.

If you do `mpv xxx.mp4 -sub xxx.lrc`, the 3.8s's subtitle is not shown either

A warning is displayed
`[sub/ass] Subtitle without duration or duration set to 0 at pts 3.820000, ignored`

**Comment by wm4** [comment]
Strictly speaking a ffmpeg issue. Its API can't distinguish between events that have length 0 and events with unknown length, so mpv just assumes length 0.

**Comment by wm4** [comment]
Added a hack which should handle this.
