### ISSUE TITLE
large audio desync when playing stream m3u from openwebif decoder

### ISSUE THREAD

**Issue by badpenguin** [mpv-player/mpv#2245]
I'm using mpv to open streams from the sat decoder running openwebif
its an m3u file from wich i extract an url and play mpv
the audio goes out of sync a lot, the video fall back like 4/5 seconds in the past
after just 30 seconds of playing

any suggestion about any command line parameters that can help keep the audio on sync?

**Comment by wm4** [comment]
Sample required. There could be multiple reasons why it desyncs.

**Comment by badpenguin** [comment]
how many seconds are needed?
also, best way to capture the stream? tcpdump??

**Comment by wm4** [comment]
Since this is a desync issue, I'd say at least 30 seconds?

Just give me the original stream.

**Comment by badpenguin** [comment]
its on the LAN :) i don't have a public fixed IP

/usr/bin/mpv "http://192.168.0.30:8001/1:0:1:2E0A:1A2C:FBFF:820000:0:0:0:" --force-window  --no-input-terminal --demuxer-thread=yes --demuxer-readahead-secs=12 --cache=auto --ontop  --msg-level=all=status
