### ISSUE TITLE
Snap to desktop edges (feature request)

### ISSUE THREAD

**Issue by ragemuffin** [mpv-player/mpv#2248]
Is this a feature that's being worked on or is it something that won't be available in the near future?
MPC-HC has a similar feature and it works quite well.

**Comment by wm4** [comment]
Most Linux window managers have supported this for decades. It's idiotic if applications have to implement this, but I assume windows forces you to.

Anyway, nothing I personally want to work on.

**Comment by ragemuffin** [comment]
Ah alright, that makes sense.
Thank you for the response.
