### ISSUE TITLE
UI does not merge dropped files.

### ISSUE THREAD

**Issue by kybin** [mpv-player/mpv#2249]
I set 'merge-files' argument on my mpv.conf.

So when I run 'mpv *.mp4' comand, it merge my files nicely.
But dropping files in UI does not.

Seems not supported this yet. Will it supported any time soon? :)
I tested it in windows, download program from http://mpv.srsfckn.biz/ (build 2015-08-03).

By the way, thank you for all your efforts. It's a great player.

**Comment by eintw1ck** [comment]
This seems to be fixed in the current version of mpv.
