### ISSUE TITLE
1080p MKV/MP4 stuttering on mpv

### ISSUE THREAD

**Issue by asoksevil** [mpv-player/mpv#2251]
I´ve always found weird that my MBA will lag when viewing 1080p MKV using mpv while Movist and Quick Time Player do not considering that mpv is more optimized than any other player...

Could it be that I messed up my config files? (though I only have hardware acceleration and vo:OpenGL.

[mediainfo]
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 1h 59mn
Bit rate                                 : 4 500 Kbps
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 30.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.072
Stream size                              : 3.79 GiB (95%)
Title                                    : Spy.2015.1080p.HDRip.KORSUB.x264.AAC2.0-RARBG
Writing library                          : x264 core 144 r2525M 40bb568
Encoding settings                        : cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x113 / me=umh / subme=7 / psy=1 / psy_rd=1.00:0.15 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-3 / threads=40 / lookahead_threads=8 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=abr / mbtree=1 / bitrate=4500 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 1h 59mn
Duration_LastFrame                       : 43ms
Bit rate mode                            : Constant
Bit rate                                 : 224 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 191 MiB (5%)
Title                                    : Spy.2015.1080p.HDRip.KORSUB.x264.AAC2.0-RARBG
[/mediainfo]

**Comment by wm4** [comment]
Try to disable hw decoding.

**Comment by asoksevil** [comment]
That did the trick... not for some statistics. mpv´s CPU usage was around 70% but fans didn´t really kick on (2k rpm) even if CPU temperature was 70 celsius degrees.

In comparison moist with hardware acceleration enabled, was around 40% but fans were constantly on (4,5K).

Any explanation? Is movist really more optimized than mpv? I thought hw decoding would help the CPU but it does seem to worsen it.

**Comment by wm4** [comment]
It has nothing to do with "optimization". It's probably due to the fact that ffmpeg forces synchronous vda/videotoolbox decoding, or maybe videotoolbox is using software decoding and that decoder is less efficient than ffmpeg. Hard to tell.
