### ISSUE TITLE
Is it possible to deactivate touchpad?

### ISSUE THREAD

**Issue by pprw** [mpv-player/mpv#2252]
I would like to deactivate the touchpad support of mpv (which allows to move inside a video with two fingers but also generated erratic behavior when you use keyboard when watching a video).

I didn't see any option related to the touchpad. Is there one?

**Comment by lachs0r** [comment]
Touchpads are just mice to mpv so no.

**Comment by lachs0r** [comment]
(However, you can disable seeking with the “scroll wheel” by setting MOUSE_BTN3 and MOUSE_BTN4 to `ignore` in input.conf)

**Comment by pprw** [comment]
Thanks ! fixed
