### ISSUE TITLE
Building in MSYS2 under Win64 stops at linking in waf with OSError: [Errno 7] Argument list too long

### ISSUE THREAD

**Issue by LigH-de** [mpv-player/mpv#2253]
Running the [media-autobuild_suite by jb_alvarado](https://github.com/jb-alvarado/media-autobuild_suite) to build mpv (among many other A/V tools) in an MSYS2-64b environment under Win64, building mpv stops with a Python error while linking:

```
[241/242] Linking build/mpv.exe
Waf: Leaving directory `/build/mpv-git/build'
Build failed
Traceback (most recent call last):
  File "/build/mpv-git/.waf3-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Context.py", line 155, in exec_command
    p=subprocess.Popen(cmd,**kw)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 7] Argument list too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/mpv-git/.waf3-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Task.py", line 110, in process
    ret=self.run()
  File "<string>", line 30, in f
  File "/build/mpv-git/.waf3-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Task.py", line 95, in exec_command
    return bld.exec_command(cmd,**kw)
  File "/build/mpv-git/.waf3-1.8.12-f00e5b53f6bbeab1384a38c9cc5d51f7/waflib/Context.py", line 162, in exec_command
    raise Errors.WafError('Execution failure: %s'%str(e),ex=e)
waflib.Errors.WafError: Execution failure: [Errno 7] Argument list too long
```

It looks like building via waf allows to create a log file, where the argument array (kw) would be logged as "runner_env" (in waflib/Context.py line 144); but I don't know how to enable this logging, it seems that it was not enabled, at least I did not find any log file containing the text "runner_env".

_I have no experience with Python, just try to read the code, and usually only call the batch file to let the media-autobuild_suite compile, would not even be sure how to run an encode manually in an MSYS shell..._

**Comment by wm4** [comment]
I know Windows has a shorter limit on command line args, but I'm not sure how this can be worked around, or if there already exist workarounds, or if it'd work with Cygwin, etc.

**Comment by LigH-de** [comment]
Maybe if the linker accepts a parameters file instead of a long command line (like many tools do with a parameter '@paramfile').

**Comment by jb-alvarado** [comment]
I think I had a problem what goes in that direction to (also with msys2). When I copy the last gcc command and remove all duplicate linked folder (there a around ~40 of the), and only let one of them in, for example: `-L/local32/lib -L/mingw32/lib`, gcc works fine. 
But I don't know how to fix that in waf. Maybe you can add a function to prevent adding duplicates?

**Comment by jb-alvarado** [comment]
Ok we fix it with a sed:

```
replace="LIBPATH_lib\1 = ['${LOCALDESTDIR}/lib','${MINGW_PREFIX}/lib']"
sed -r -i "s:LIBPATH_lib(ass|av(|device|filter)) = .*:$replace:g" ./build/c4che/_cache.py
```

**Comment by wiiaboo** [comment]
There's like 40 repetitions of the same -L flags that can be reduced to just one instance. That helps this issue.

**Comment by wiiaboo** [comment]
This is a Windows issue, it can't be fixed by mpv or waf unless waf moves to using option files.
