### ISSUE TITLE
Hardware decoding stopped working in OS X 10.9.5

### ISSUE THREAD

**Issue by jaimeMF** [mpv-player/mpv#2255]
After commit 6894858bf23d48f62cb28b309481cded8bcd43b4, the video is not played: it gets stuck after printing:
```
AO: [coreaudio] 44100Hz stereo 2ch floatp
```
The output with that commit is [here](https://gist.github.com/jaimeMF/66801c2ed058141c26aa#file-broken-log) and the previous is [here](https://gist.github.com/jaimeMF/66801c2ed058141c26aa#file-working-log). Please ask for more info if you need it.

**Comment by wm4** [comment]
Does it work with ``--hwdec=vda``?

**Comment by jaimeMF** [comment]
[It gets stuck at the same point](https://gist.github.com/jaimeMF/66801c2ed058141c26aa#file-with-vda-log).

I forgot to mention that on the Activity Monitor the mpv process shows a high CPU load.

**Comment by wm4** [comment]
>It gets stuck at the same point.

Doesn't look like it's stuck there?

>I forgot to mention that on the Activity Monitor the mpv process shows a high CPU load.

Can you check with a debugger what it's doing? Can you quit mpv normally, or is the process frozen?

For the record, it works for me on 10.10.4.

**Comment by wm4** [comment]
Also, I think this worked only because ``--hwdec=auto`` essentially forced VDA decoding. The commit which "broke" this gives vda and videotoolbox an equal chance, so this happens.

**Comment by jaimeMF** [comment]
>>    It gets stuck at the same point.

> Doesn't look like it's stuck there?

>>    I forgot to mention that on the Activity Monitor the mpv process shows a high CPU load.

> Can you check with a debugger what it's doing? Can you quit mpv normally, or is the process frozen?

> For the record, it works for me on 10.10.4.

I should have been more clear: the mpv app icon shows on the Dock but no window is created and the audio is not played (without `--mute`). You can quit the program by pressing `q` in the terminal, `Cmd+q` after clicking in the app icon or from the dock, it prints the following:
```
[cplayer] Run command: quit, flags=9, args=[0]
[cplayer] EOF code: 6
[ad] Uninit audio filters...
[ad] Uninit audio decoder.
[vd] Uninit video.
[cplayer]
[cplayer]
[cplayer] Exiting... (Quit)
[auto_fullscreen] Exiting...
[ytdl_hook] Exiting...
[helpers] Exiting...
[pause_when_minimize] Exiting...
[osc] Exiting...
[load_webm_audio] Exiting...
```

About using the debugger, I don't have experience with it. I run `lldb -- ./build/mpv --no-config -v --hwdec=auto --mute foo.mp4` and then on the prompt I execute `run`, what should I do then?

**Comment by wm4** [comment]
Unfortunately I don't know lldb either. A backtrace from all threads would be good.

**Comment by jaimeMF** [comment]
[Here is the backtrace from all threads](https://gist.github.com/jaimeMF/66801c2ed058141c26aa#file-threads-backtrace-log).

**Comment by wm4** [comment]
That's also strange.

What output do you get with ``-v -v -v``?

**Comment by jaimeMF** [comment]
[Here it is](https://gist.github.com/jaimeMF/66801c2ed058141c26aa#file-really-verbose-log), it keeps printing `[cplayer] video_output_image: 1` for more than the video duration until you press `q` to close it.

**Comment by Argon-** [comment]
I have exactly the same problem on 10.10.5. Same symptoms (high CPU usage) and nothing happens. Output is stuck at `vd: Using hardware decoding.` (or `vd: Pixel formats supported by decoder: vda_vld vda yuv420p` with `-v`).
The problem appears when using `--hwdec=vda` or `--hwdec=auto` and does not happen with `--hwdec=videotoolbox` but only because when I use `videotoolbox` it's falling back to sw decoding:

     vd: Requested hardware decoder not compiled.
     vd: Using software decoding.

**Comment by wm4** [comment]
> vd: Requested hardware decoder not compiled.
> vd: Using software decoding.

Try with a newer FFmpeg.

**Comment by Argon-** [comment]
Interesting, while I expected this to introduce working `videotoolbox` hwdec, it also fixed `vda`.

**Comment by wm4** [comment]
Slight chance that it's broken in FFmpeg.

**Comment by jaimeMF** [comment]
Everything works fine with ffmpeg 53bf32f, it uses `videotoolbox`.
