### ISSUE TITLE
Force reconnect for streams which can resume

### ISSUE THREAD

**Issue by paulguy** [mpv-player/mpv#2256]
Some sites can be real crap sometimes and just randomly turn slow for seemingly no real reason (youtube) and usually stopping and reconnecting will make it work, but then I need to seek and wait for it to buffer to get to where I need to be.  I was wondering if there could just be a command to force it to close the stream and reconnect and try to resume like it normally would for a timeout.

**Comment by siikamiika** [comment]
Does this work for you? Save it to something like `reconnect.lua` and put it to `~/.mpv/scripts/` (linux/osx) or `homedir\AppData\Roaming\mpv\scripts\` (windows)

```lua
local url = nil
local time = nil

function restore_position()
    mp.set_property('time-pos', time)
    mp.unregister_event(restore_position)
    print('restored position:', url, time)
end

function reconnect()
    url = mp.get_property('path')
    time = mp.get_property('time-pos')
    mp.register_event('playback-restart', restore_position)
    mp.commandv('loadfile', url)
end

mp.add_key_binding('Ctrl+r', reconnect)
```

**Comment by paulguy** [comment]
It technically works but the video has to buffer up to the point that's being seeked to.  Normally when it reconnects due to a lost connection, it just returns to the original position.

I tried changing time-pos to stream-pos and it didn't work at all.  Just got terminal spammed with 
[ffmpeg] https: HTTP error 416 Requested range not satisfiable
[ffmpeg] Seek failed

No idea how to recreate the usual reconnect logic.

**Comment by bitingsock** [comment]
Are you using youtube above 720p and 60fps? This would force you to use DASH but I heard they fixed the seeking of dash in ffmpeg recently; maybe I misheard. If it's true, you problem may already be fixed.

**Comment by paulguy** [comment]
This seems to actually work now.  I wonder how reconnecting after a socket timeout worked before though and why doing so on command is so different?

Either way, would be nice if this could be implemented as a full on feature.  Plenty of misbehaving streaming sites that give you a slow mirror on their CDN.

**Comment by wm4** [comment]
``stream-pos`` is in bytes, and I honestly don't know why it's even writable.

Closing if this is no problem anymore. (?)

**Comment by nurupo** [comment]
Since mpv resumes playback at where it was left by default, this could be reduced to a less error-prone:

```lua
function reload_current_file()
    mp.commandv('loadfile', mp.get_property('path'))
end

mp.add_key_binding('Ctrl+r', reload_current_file)
```
