### ISSUE TITLE
Title of video included in screenshot name

### ISSUE THREAD

**Issue by pazpi** [mpv-player/mpv#2258]
Like title, is it possible to add some extra text in the name of the screenshots?
For example the title of the video or the dimension of the picture, like "mpv-screenshot-TITLE.jpg"
Thank in advance!

**Comment by Argon-** [comment]
http://mpv.io/manual/master/#options-screenshot-template

**Comment by pazpi** [comment]
Perfect!
I have looked at the documentation, but I haven't read deeply enough.
Thanks
