### ISSUE TITLE
mpv and aspect ratio set to the video stream

### ISSUE THREAD

**Issue by mooooonbaby** [mpv-player/mpv#2259]
hi,

i use mpv on my linux based htpc (ubuntu). i have problems playing video with a resolution less than 1080p. 720p and to matroska muxed dvds with 720x576px are played in small windows in the middle of the screen. i start mpv with the option --fs. with --video-aspect=-1 720p-files are played well. i think the probelm with the sd video is that i've set the correct aspect ratio to the video stream but to to the container. all the other player i know use the ar from the video stream, but mpv uses the container ones. i think the problem files were created by handbrake. other encodings i've muxed manually with mkvmerge have the correct ar in container and they are played well.

how can i set mpv so that it reads out the ar from video stream and not from container? (all my video files are matroska)

moonbaby

**Comment by wm4** [comment]
>720p and to matroska muxed dvds with 720x576px are played in small windows in the middle of the screen.

Are these files encoded with black bars in them?

**Comment by mooooonbaby** [comment]
yes. but mpv works well when the ar is set correct in the container even if the files have black bars.

**Comment by wm4** [comment]
I don't understand why you want to override the aspect ratio?

**Comment by mooooonbaby** [comment]
Because they are wrong. in the video stream there is the correct ar, but the ar in container is offen wrong (5:4).

**Comment by wm4** [comment]
Do you have a sample file?

**Comment by mooooonbaby** [comment]
i have this problem with all my dvd created with handbrake - and thats a lot of films

http://www.file-upload.net/download-10874218/example--1-.mkv.html

**Comment by wm4** [comment]
I think normally, the container aspect gets priority. I've played your file with VLC too, and it's played with 5:4 aspect ratio. So I'd say your file is just plain broken. What plays it "correctly"?

Which version of handbrake did you use? Your file says it's muxed by mkvmerge, but that's probably because you used it to cut a sample.

**Comment by mooooonbaby** [comment]
kodi (former xbmc).

yes, i did the encoding with handbrake into mkv container and then i created the short sample with mkvmerge. i know i would be better to create better mkvs, but at the moment i have more than 250 filmes encoded in this way with handbrake.

**Comment by junh1024** [comment]
I think what you want is a batch script to set the AR in the container correctly.
