### ISSUE TITLE
timetotal options in osc.conf does not work?

### ISSUE THREAD

**Issue by LeoXX** [mpv-player/mpv#2262]
...
[osc] lua-settings/osc.conf:3 unknown key timetotal, ignoring 
...

cat ~/.mpv/lua-settings/osc.conf
seekbarstyle=bar
layout=bottombar
timetotal=yes

mpv --version
mpv 0.9.2-git-6beed16 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-08-29T11:23:06
ffmpeg library versions:
   libavutil       54.27.100
   libavcodec      56.41.100
   libavformat     56.36.100
   libswscale      3.1.101
   libavfilter     5.16.101
   libswresample   1.2.100

What I'm doing wrong?

**Comment by ChrisK2** [comment]
You are not using HEAD/master. This is a new feature not yet available in a release.
