### ISSUE TITLE
mpv reports missed frames while check-pattern=1-1 does not

### ISSUE THREAD

**Issue by maletor** [mpv-player/mpv#2263]
You said 

> mpv is being dumb. 

With `video-sync=display-resample` mpv will report "Missed" frames next to "Dropped" frames. I'm assuming the count there should line up if what `check-pattern=1-1`. If not, is there reason for that?

**Comment by wm4** [comment]
Because mpv uses the ideal assumed vsync time to check whether rendering the frame took too long, and if it did, it's accounted as missed frame. But as we've found out, on your systems vsync frame times are very erratic, and confuse mpv's (probably too dumb) heuristic.

**Comment by maletor** [comment]
I was able to isolate the issue to `--vo=opengl-hq:scale=ewa_lanczossharp`. With only `--vo=opengl-hq` I am able to get [vsync frame timings at consistent intervals](http://0x0.st/sCU.txt).

Is it really possible the GPU can't keep up with the extra computational effort of `ewa_lanczossharp` or is something else going on?

**Comment by wm4** [comment]
>Is it really possible the GPU can't keep up with the extra computational effort of ewa_lanczossharp or is something else going on?

Sounds possible. I just wonder why it has such an effect on vsync. I'd much rather expect it to skip a vsync completely.
