### ISSUE TITLE
Does mpv support Persian subtitle?

### ISSUE THREAD

**Issue by Daniyal-Javani** [mpv-player/mpv#2265]
Hello
When I play a Persian subtitle just show unknown characters. I also add --sub-codepage=enca but still have the same problem. In other players I select "Arabic Windows (CP1256)" or "Arabic (ISO-8859-6) as subtitle encoding, but I can't find these options in mpv.
Could you please help me?

**Comment by Daniyal-Javani** [comment]
Oops this worked for me.
--sub-codepage=utf8:cp1256 and sometimes --sub-codepage=utf8:ISO-8859-6
https://github.com/mpv-player/mpv/issues/1263

**Comment by wm4** [comment]
You can try compiling mpv git with uchardet support enabled. There's a chance it might get it right automatically.
