### ISSUE TITLE
frame_back_step (",") fails on native HLS files from twitch

### ISSUE THREAD

**Issue by andrewguertin** [mpv-player/mpv#2269]
Pressing "," to step back one frame works for me on most files, but when playing videos from Twitch that use their new HLS system, it instead jumps forward a few seconds.

Steps to reproduce:
1. youtube-dl --hls-prefer-native http://www.twitch.tv/riotgames2/v/13202525
2. Play the downloaded file
3. Step backwards one frame with ","

Expected results:
Steps back one frame

Actual results:
Steps forward several seconds

Most videos work fine. The only videos I've found that fail are Twitch's HLS videos (although I haven't tried any HLS videos from other providers).

Note that youtube-dl --hls-prefer-native downloads the video by just downloading and concatenating the file chunks from the m3u8 playlist. It does no re-encoding. Without --hls-prefer-native, the video is re-encoded and the problem does not occur.

Playing the video using mpv http://www.twitch.tv/riotgames2/v/13202525 also seems to be affected.

**Comment by wm4** [comment]
This happens because seeking is broken, which in turn is most likely a libavformat issue. Using ``--hr-seek-demuxer-offset=10`` makes it work here, but also will make it much slower in general.

**Comment by Akemi** [comment]
stale issue.
