### ISSUE TITLE
mpv no longer playing video only audio

### ISSUE THREAD

**Issue by ridethewhirlwinds** [mpv-player/mpv#2270]
This problem just started yesterday and was fine and played flawlessly prior. I am running a VM with VirtualBox 5.0.2 on Arch Linux. I am using the latest and greatest mpv 41859.gf1778d1f-1.

I have tried completely deleteing my old VM and recreating and reinstalling everything fresh on 5.0.2. And still have the same problem with the audio playing but not the video.

The only thing that's changed were updates on Arch using 'pacman -Syu'. I have also tried using all the different video outputs (mpv -vo opengl etc.) to no avail. Only caca plays but looks terrible. And I noticed using 'ffplay -i example.mp4' works fine.

My virtualbox-guest-additions is up to date with the latest version: 5.0.2-1 and my linux kernel is 4.1.6-1.

Here are 2 threads that have yielded no results in a solution for this:
https://www.reddit.com/r/archlinux/comments/3j1tbp/mpv_player_stops_playing_video_only_audio/
https://bbs.archlinux.org/viewtopic.php?id=201810

Any help be appreciated as I've already tried uninstalling the mpv package and reinstalling it.

----

This is the info I get:

Playing: example.mp4 (+) Video --vid=1 (*) (h264)

(+) Audio --aid=1 --alang=und (*) (aac)

pci id for fd 12: 80ee:beef, driver (null)

libGL error: core dri or dri2 extension not found

libGL error: failed to load driver: vboxvideo

[vo/opengl] Suspected software renderer or indirect context.

Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory

[vo/vdpau] Error when calling vdp_device_create_x11: 1

[vo/xv] No Xvideo support found.

libva info: VA-API version 0.38.0

libva info: va_getDriverName() returns 0

libva info: Trying to open /usr/lib/dri/vboxvideo_drv_video.so

libva info: va_openDriver() returns -1

[vaapi] vaInitialize(): unknown libva error

Error opening/initializing the selected video_out (-vo) device.

Video: no video

AO: [alsa] 48000Hz stereo 2ch float

A: 00:00:01 / 00:42:57 (0%)

**Comment by lachs0r** [comment]
>libGL error: core dri or dri2 extension not found
>libGL error: failed to load driver: vboxvideo
>[vo/xv] No Xvideo support found.

Your VirtualBox video driver is broken.

**Comment by ridethewhirlwinds** [comment]
I've had the exact same errors before and it played the video just fine.

See thread:
https://www.reddit.com/r/archlinux/comments/3i0ebd/trying_out_mpv_player_and_have_questions_on_some/

**Comment by lachs0r** [comment]
That’s because mpv was falling back to the legacy X11 video output,
which has been removed. If you really don’t want to fix your drivers or stop 
playing video in a VM, try vo=sdl, vo=wayland or vo=drm instead.
vo=opengl:sw might work, but don’t expect it to be fast.

**Comment by ridethewhirlwinds** [comment]
I do want to fix the vboxvideo issue, but I haven't any solutions for this.

For your suggestion, do I just create a mpv.conf file and add the lines you suggested in? 

"try vo=sdl, vo=wayland or vo=drm"

**Comment by lachs0r** [comment]
Yes.

FWIW, I just tried vo=opengl:sw with KVM (qxl graphics driver) and it wasn’t 
THAT slow, just not something I’d recommend.

Really, with the degree of graphics performance you get from VMs even if the 
guest drivers are working properly (and no PCIe VGA passthrough), all this 
seems quite pointless.

**Comment by mrkapqa** [comment]
I am having similar problem on Macmini 2.1 with Osx Lion.
MPV was installed via MacPorts and seemed to build just fine.
...but , it plays only audio, no Video.

here an example of the terminal output

Playing: Alipi Naydenov - Buon Compleanno, Maestro! (LD).mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
[vo/opengl] At least OpenGL 2.1 or OpenGL ES 2.0 required.
Error opening/initializing the selected video_out (-vo) device.
Video: no video
AO: [coreaudio] 44100Hz stereo 2ch floatp
