### ISSUE TITLE
bs2b not detected

### ISSUE THREAD

**Issue by usaradark** [mpv-player/mpv#2271]
```
F:\mpv --af=bs2b --no-config
Option af: bs2b doesn't exist.
Error parsing option af (option could not be parsed)
Setting command line option '--af=bs2b' failed.

Exiting... (Fatal error)
```
...is what I'm getting. The video does not play and I am currently using the latest 32 and 64 bit of mpv. Am I missing something, or is it a client side error?

**Comment by lachs0r** [comment]
I’m not building with `libbs2b` as it is pretty much worthless. I can add it if you really want it though.

**Comment by usaradark** [comment]
Before I ask for a build, I want to ask why it's worthless? Has it been replaced by something else?

**Comment by wiiaboo** [comment]
Makes a lot of difference for certain kind of music (jazz, mostly old recordings), but for most of audio is barely noticeable.

**Comment by usaradark** [comment]
Okay then, nevermind.

**Comment by kevmitch** [comment]
I don't know if I'd call it worthless. It's really a matter of personal taste. After trying it out a bit, I decided I personally didn't like it. It does however do what it's advertised to do. It makes it sound like it's coming from speakers when you're listening with headphones. I didn't like the way it messed with the EQ though.

**Comment by wiiaboo** [comment]
The only alternative would be lavfi=[earwax] but it's as horrible as hrtf.

**Comment by dtl131** [comment]
I'm trying to get the bs2b filter from libavfilter working, but either I don't understand the syntax or something's not working (probably the former).

```
mpv --af=lavfi=graph="bs2b=profile=jmeier" video.mkv 
Error parsing option af (option could not be parsed)
Setting command line option '--af=lavfi=graph=bs2b=profile=jmeier' failed.
```
libavfilter reports it is available:
``` ... bs2b             A->A       Bauer stereo-to-binaural filter```

**Comment by wm4** [comment]
Try ``mpv --af=lavfi=[bs2b=profile=jmeier] video.mkv`` (the shell is going to remove your ``"``)

**Comment by dtl131** [comment]
^Yes, that works. Thank you. I knew I was doing something wrong.
