### ISSUE TITLE
youtube-dl overriding duration for DASH

### ISSUE THREAD

**Issue by kevinlekiller** [mpv-player/mpv#2275]
With youtube-dl we can get the duration like this : `youtube-dl --skip-download --get-duration https://www.youtube.com/watch?v=WTK4CgYbXEQ`

Is there a property or option that can be set to override the OSD duration using the duration we got from that command (I couldn't find anything in the [manual](http://mpv.io/manual/master/), but I might have missed it)?

This would allow us to skip to a specific time easily on the OSD with DASH content.

Thanks.

**Comment by wm4** [comment]
No, and this should be fixed in ffmpeg.

**Comment by kevinlekiller** [comment]
Alright, I'll keep using best, just a shame it's limited to 720p

Thanks.

**Comment by haarp** [comment]
Sorry to barge in here. @wm4, do you happen to know any open bug reports in ffmpeg for this? I can't seem to find any, nor do I have any good phrases to search by. Thanks!

**Comment by wm4** [comment]
See: https://github.com/mpv-player/mpv/releases

**Comment by haarp** [comment]
Ooh, thanks for the hint. Upgraded to ffmpeg 2.8.3 and everything works well now. :)
