### ISSUE TITLE
LAME encoded MP3's aren't played gaplessly when encoded with --nogap

### ISSUE THREAD

**Issue by calestyo** [mpv-player/mpv#2276]
Hey.

Quite strange:
When I encode some MP3s e.g. via:
$ lame  -v -V 5 --nogap 1.wav 2.wav
and play them later with mpv:
$ mpv 1.mp3 2.mp3
Playing: 1.mp3
[ffmpeg/demuxer] mp3: Estimating duration from bitrate, this may be inaccurate
 (+) Audio --aid=1 (mp3)
AO: [pulse] 44100Hz stereo 2ch s16

It gives me the above warning about estimating the duration and there's still a slight gap between 1 and 2.

But when I encode it like this:
$ lame  -v -V 5 1.wav 2.wav
(i.e. without --nogap)
$ mpv 1.mp3 2.mp3
Playing: 1.mp3
 (+) Audio --aid=1 (mp3)
AO: [pulse] 44100Hz stereo 2ch s16

there's no warning... and it plays perfectly gapless when going from 1 to 2.

Any ideas?

**Comment by lachs0r** [comment]
While quite frankly, I cannot see why you are using MP3 *more than ten years* after it has been made obsolete by widespread AAC support in consumer electronics (and, to a lesser degree, Ogg Vorbis), I’ve tried and failed to reproduce your problem on my end.

Can you upload sample files?

**Comment by lachs0r** [comment]
Also, just in case, did you try tagging the resulting files? Detecting MP3 streams without tags is unreliable (it’s… really not a very good format), so that could be stalling things.

**Comment by calestyo** [comment]
Well, I would of course use AAC, but right now Debian has only aac-enc (at least when talking about Fraunhofer based encoders), which seems to not add any gapless information at all, that's why I've tried MP3 out of curiosity.

Tagging the files didn't help.

I'll send you a link with the test files via mails,... they shouldn't become publicly downloadable.

**Comment by lachs0r** [comment]
Okay, figured it out. Gapless encoding seems to be the default for recent versions of LAME.
If you enable verbose output (`--verbose`), you will see the line “using LAME tag”, which indicates that it writes the encoder delay info etc. to the file. If you enable `--nogap`, that ends up overriding the default. Curiously, it makes LAME omit its tag. To add that tag to the file, you also need the option `--nogaptags`, which is not mentioned in the manpage but in LAME’s `--longhelp` output.
With that, it works.

This means that there is no problem on mpv’s end since the files do not contain the tags that would enable gapless playback, as backwards as that is. Blame LAME’s lame interface and documentation.

**Comment by calestyo** [comment]
hmm I just tried that myself... you're in so far right, that it writes the LAME tag with that option... and that the other seems to be the (undocumented) default ;-)

Interestingly, the resulting files are still different... and for the one with --nogaptags and --nogap I think I still here some tiny glitch... but I really had to listen several times,.. it's not really a gap, I guess, more like a small spike...

**Comment by lachs0r** [comment]
> Interestingly, the resulting files are still different...
It likely overrides other settings. Who knows.

> and for the one with --nogaptags and --nogap I think I still here some tiny
> glitch... but I really had to listen several times,.. it's not really a gap,
> I guess, more like a small spike...

Must be placebo. I’ve looked at the audio mpv plays with an audio editor and 
it’s definitely gapless.

**Comment by calestyo** [comment]
Hmm I just did the same:
mpv --ao=pcm:file=test.wav 1.mp3 2.mp3
mpv --ao=pcm:file=test2.wav 1.mp3 2.mp3

With test.wav being the one without --nogaptags and --nogap and test2.wav being the one with:
Opened both in audacity
![screenshot from 2015-09-02 23-38-33](https://cloud.githubusercontent.com/assets/919933/9645448/fbb39f20-51cb-11e5-9094-dd0d3eb65c9a.png)
As you can where the line is shown, there was the gap between the two files, as you can see, in the 2nd mode (test2), the 2nd file is played "much" earlier... and that's what I hear what doesn't fit as is should, I guess.

**Comment by calestyo** [comment]
Oh when you try that, be sure that you mute the track which isn't playing, otherwise audacity plays both, with is obviously kinda broken.

Oh, one more thing:
I tried it with fdk-aac, there, things seem to be much worse:
mpv (and mplayer as well) give some noticable spike at the end of each file (cannot tell because of that whether they're correctly gapless or not), the ipod nano seems to not play that spike, but isn't clearly gapless in return.
Demo files on the location I've sent you before... lc, he1, he2 is probably obvious,..vbr 5 is the quality (-m 5 in fdkaac)... gap 0/2 is:
-G, --gapless-mode <n>        Encoder delay signaling for gapless playback
                                 0: iTunSMPB (default)
                                 1: ISO standard (edts + sgpd)
                                 2: Both

**Comment by calestyo** [comment]
@lachs0r have you seen my last comments? Maybe this issue needs to be opened again. I've also reported the same here: https://sourceforge.net/p/lame/bugs/453/

**Comment by calestyo** [comment]
Could someone possibly re-open this? See above, why it apparently still doesn't work in all cases.

**Comment by calestyo** [comment]
Hmm I tried a bit more and *likely* it's an issue in lame (or ffmpeg)?

When encoding the MP3s with --nogaptags --nogap 1.mp3 is actually shorter, at least when opened in audacity, then when not using --nogaptags --nogap.

**Comment by lachs0r** [comment]
Audacity’s MP3 import doesn’t work correctly.
Convert to WAV with ffmpeg beforehand.

**Comment by calestyo** [comment]
Done, but same situation... apart from that: doesn't audacity use ffmpeg for the conversion?

**Comment by ValZapod** [comment]
> doesn't audacity use ffmpeg for the conversion?

Of course not.
