### ISSUE TITLE
"video-stereo-mode" option does not accept "none"

### ISSUE THREAD

**Issue by r0polach** [mpv-player/mpv#2278]
Man pages contains hint about "none" value to video-stereo-mode option
but this value is treated as invalid by mpv 0.9.2 (Linux Mint 17.2 64bit,
mpv from PPA mc3man/trusty-media)

**Comment by r0polach** [comment]
Note: video-stereo-mode=none is good default for playing both 2D and 3D videos
on 3D-capable display. As it does not work for me now, I must workaround it by using
file-specific config files with video-stereo-mode=sbs2r, video-stereo-mode=sbs2l, etc.

**Comment by mc4man** [comment]
seen here on mpv git-061b947
Valid values are:
    no
    mono
    sbs2l
    ab2r
    ab2l
    checkr
    checkl
    irr
    irl
    icr
    icl
    arcc
    sbs2r
    agmc

**Comment by wm4** [comment]
The manpage also mentions `no`, not `none`. And it works just fine.

**Comment by r0polach** [comment]
In 0.9.2, even "no" does not work:

Invalid value for option video-stereo-mode: no
Valid values are:
    mono
    sbs2l
    ab2r
    ab2l
    checkr
    checkl
    irr
    irl
    icr
    icl
    arcc
    sbs2r
    agmc
Error parsing option video-stereo-mode (option could not be parsed)
Setting command line option '--video-stereo-mode=no' failed.

...so should I upgrade to git master? Will "no" work for me?

**Comment by r0polach** [comment]
Ok, newest 0.9.2+git22 from the PPA works for me now!, it even solves other problems!

**Comment by wm4** [comment]
Seems like 0.9.2 should have accepted ``none`` and didn't accept ``no``, but that's old history now.

**Comment by mc4man** [comment]
@r0polach 
That ppa will now be getting git master builds, generally several days after being released to the standalone ppa & some user testing. Formerly it only got 'stable releases' but they no longer happen.

**Comment by lachs0r** [comment]
Wrong!

**Comment by mc4man** [comment]
Well I guess you decided to take up releases (yet again), as of the other day It said no more.
Wasn't there a time when an upcoming release was listed as an issue?
