### ISSUE TITLE
if "--fs" used, "F" must be pressed 3 times initially to escape full-screen

### ISSUE THREAD

**Issue by r0polach** [mpv-player/mpv#2281]
When I run "mpv --fs video.mkv" I must press "f" three-times to get it from full-screen...
after that, only one "f" is sufficient to in full-screen / escape from full-screen...
When I run "mkv video.mkv" it behaves normally - only one "f" press is needed...

(Using mpv-0.9.2+git22 package prom Ubuntu PPA mc3man/trusty-media repository)

**Comment by lachs0r** [comment]
Duplicate of #2072
