### ISSUE TITLE
gapless playack issues with MP4/AAC

### ISSUE THREAD

**Issue by calestyo** [mpv-player/mpv#2284]
Hey.

Not sure whether this is a bug in mpv or not, but perhaps some expert can have a look at it:

I was encoding WAV files with libfdk-aac using the fdkaac front end to MP4/AAC.
As already mentioned in #2276, they don't playback gaplessly... now it's totally unclear whether the problem is in libfdk-aac, the frontend or mpv.

At least the ipod seem to fail with playing my test files gaplessly, so there's slight indication that mpv isn't the cause.

More details on what happens are provided here:
mstorsjo/fdk-aac#35
nu774/fdkaac#19

Any ideas? Is mpv expected to play MP4s with AAC streams gaplessly?

Thanks,
Chris.

**Comment by wm4** [comment]
First off, FFmpeg probably doesn't support gapless mp4/aac. But it could probably be added.

If FFmpeg doesn't, mpv won't play it gaplessly either.

**Comment by wm4** [comment]
PS: which means you should test with ffmpeg CLI. (Transcode to wav, look at the result.)

**Comment by mc4man** [comment]
A gapless cd ripped with libfdk-aac via fdkaac plays back here without gaps in mpv & audacious.
diff may be that it was a gapless source?

**Comment by calestyo** [comment]
@wm4 Will take some time until I can do this,... I'm just about to head into 1 month vacation.

@mc4man Well, even with my example files you have to listen quite closely to hear it...

**Comment by mc4man** [comment]
Playing the same in both audacious & mpv, aud is perfect, on a couple of track transitions mpv produces a  very short sound artifact of some sort. It's not a 'gap', just some kind of pop or something..

**Comment by calestyo** [comment]
Well call it a pop or whatever... it's not there when playing the WAV or the MP3,... and you can clearly see on the screenshots in the links mentioned above that there is some kind of distortion... :-/

**Comment by wm4** [comment]
For starters, you shouldn't use fdkaac anymore, but the ffmpeg native encoder.

**Comment by calestyo** [comment]
Last time I've checked, FDK AAC was still rated the best amongst the open encoders, and ffmpeg the worst.

Apart from that, gapless should work, regardless of which encoder has been used, at least if the encoder adds proper meta-data, which fdk aac allegedly does.

**Comment by calestyo** [comment]
An update on this with recent versions of mpv/ffmpeg:

In the following a series of test files, based on https://commons.wikimedia.org/w/index.php?title=File%3ATelemann_-_2violin_Sonata_1-1.ogg, are used.

Each filename starts with a number, where the same number indicates the files belong together.

```
00.test.wav
```
PCM WAV shortened version of the above Wikipedia Demo

```
01.split-track01.wav
01.split-track02.wav
```
00.test.wav split into two halfs (these are the actual base test files used with encoders)

```
02.split-track01.mp3
02.split-track02.mp3
```
LAME encoded versions of `01.split-track01.wav` and 0`1.split-track02.wav`

```
03.split-track01.opus
03.split-track02.opus
```
opusenc encoded versions of `01.split-track01.wav` and `01.split-track02.wav`

and so on.




**How the to base test files (`01.split-track01.wav` and `01.split-track02.wav`) were created**
The Wikipedia demo file was first decoded to PCM WAV with `opusdec`, and split in two halfs with

```
$ shnsplit 00.test.wav
enter split points:
0:05.317
shnsplit: warning: rounding 0:05.317 (offset: 937919) to nearest sector boundary (offset: 938448)
shnsplit: warning: file 2 will not be cut on a sector boundary
Splitting [test.wav] (0:15.66) --> [01.split-track01.wav] (0:05.24) : 100% OK
Splitting [test.wav] (0:15.66) --> [01.split-track02.wav] (0:10.42) : 100% OK
```

For cross checking, the resulting files were joined again:
`$ sox 01.split-track01.wav 01.split-track02.wav joined.wav`

The concatenation is binary identical to the original file:
```
$ diff 00.test.wav joined.wav 
$
```
which can also be seen (visually) in e.g. audacity or sonic-visualizer (i.e. there are no gaps or other distortions between `01.split-track01.wav` and `01.split-track02.wav`.




**What is tested?**
The split files will now be encoded with some reference encoders and played respectively decoded (to PCM WAV) again afterwards checking for the following:
- Does the "gaplass" playback even work for the plain PCM WAV?
- At playback, can any gap, crack, pop, etc. be heared between the two files (i.e. does "gapless playback" work)?
- At decoding to PCM WAV, is there any shift at the start of the 1st file respectively end of the 2nd file?
- At decoding to PCM WAV, is there any gap/shift/other distortion at the end of the 1st file and start of the 2nd file when these two are concatenated, in other words at the joining position?

Hearing tests were repeated multiple times, so the files were already in the OS cache and one should basically expect no delay at all from slow storage medium (which was anyway one of the fastest SSDs)
Unless otherwise noticed, all programs libraries were from Debian unstable.

Encoders with these options were used:

- `lame --verbose -q 0 -v -V 4 --noreplaygain --id3v2-utf16 --add-id3v2 --id3v1-only`
  LAME 64bits version 3.100
- `opusenc --vbr --bitrate 96 split-track01.wav`
  opus-tools 0.1.10
- `fdkaac -p 29 -m 4 _<gapless modes, part of the filename>_`
  0.6.3
  gapless modes:
  0      iTunSMPB
  1      ISO standard (edts and sgpd)
  2      Both
- `aac-enc -t 29 -v 4`
  0.1.6
  => may not even set any gapless information, so can possibly completely ignored
- `faac -q 100 -w`
  1.29.9.2
  => may not even set any gapless information, so can possibly completely ignored


And for playback respectively decoding:
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100 (runtime 56.22.100)
   libavcodec      58.18.100 (runtime 58.35.100)
   libavformat     58.12.100 (runtime 58.20.100)
   libswscale      5.1.100 (runtime 5.3.100)
   libavfilter     7.16.100 (runtime 7.40.101)
   libswresample   3.1.100 (runtime 3.3.100)
ffmpeg version: 4.1.1-1
```




**Results**
a) Hearing Tests
`mpv 01.split-track0*.wav`		=> OK, no gap/pop/click/etc.
`mpv 02.split-track0*.mp3`		=> OK, no gap/pop/click/etc.
`mpv 03.split-track0*.opus`	=> OK, no gap/pop/click/etc.

but all with AAC:
`mpv 04.split-track0*`
...
`mpv 08.split-track0*` 			=> BAD, clearly audible gap


b) Visible tests
For these, all the encoded files were again decoded with:
`mpv --no-video -ao=pcm`
to PCM WAV files like:
```
mpv.02.split-track01.mp3.wav
mpv.02.split-track02.mp3.wav
```
which would be the yet again decoded files used in the visual tests (with audacity/sonic-visualizer), that is e.g. `mpv.02.split-track01.mp3.wav` would have been decoded with mpv from `02.split-track01.mp3`.


For each such pair an image is attached, e.g.:
`mpv.02.mp3.wav.png`
Comparing the intersection point:
- top: the original `00.test.wav`
- middle: the joined `mpv.02.split-track01.mp3.wav` and `mpv.02.split-track02.mp3.wav` (named `mpv.02.joined.mp3.wav`)
  (joins were made with `sox 1.wav 2.wav 1-joined-with-2.wav`)
- bottom: `mpv.02.split-track01.mp3.wav` alone, serving just as reference as to where the intersection is

Opus seems to always sample at 48kHz, so in sonic visualizer there is an option that will do automatic resampling on opening, which I've enabled.

`mpv.02.mp3.wav.png`	=> OK, mostly, there might be a small distortion (red circle), but I guess nothing that anyone will be able to hear
`mpv.03.opus.wav.png`	=> OK, seems perfect

all the AAC ones:
`mpv.*.*.m4a.wav.png`	=> BAD, not only huge gaps, but it seems the as if end and start of the joined files was even like "faded out/in" (no idea whether encoder or decoder error)


The test files an images can be found at:
https://drive.google.com/drive/folders/1SIt1z3FtlYa-zMEDzF-m8jsMCe2PFsyz?usp=sharing


For me it's not obvious whether these are bugs in mpv, the AAC-encoders, or ffmpeg.
I will run the same range of tests with plain ffmpeg later and report any findings upstream (will post the link to any such tickets here)

I personally am mostly interested in Opus these days… so don't feel strongly pressed from my side to do anything about these AAC-gapless issues.
But obviously other users may want to see them fixed.

Cheers,
Chris.

**Comment by calestyo** [comment]
I just finished checking with bare ffmpeg,... gapless decoding works there for Opus and MP3 (with the later also producing that small glitch which I can however not hear, but only see in the waveform... could of course also be just some general limitation or bug in lame).

It also fails to decode any of the AACs gaplessly, however (and I used the git master HEAD ffmpeg there, while with the mpv tests an older Debian ffmpeg 4.1.1 was used)... the results are a bit different for fdkaac in the ISO gapless method (but still with a gap).

The respective ticket at upstream is at https://trac.ffmpeg.org/ticket/7828

**Comment by calestyo** [comment]
I found a set of test vector AAC files, that are ought to play back gapless (by using meta data according to MPEG standards,.. not the iTunes stuff which - of course (Apple) - does it different):
https://www2.iis.fraunhofer.de/AAC/gapless.html

(turn down your volume as these files have a pretty loud and annoying sound, IMO)

**Comment by Akemi** [comment]
upstream problem.

**Comment by ValZapod** [comment]
Fixed by chromium. https://bugs.chromium.org/p/chromium/issues/detail?id=668999

**Comment by cyberfunk** [comment]
I'm experiencing this now with latest MPV player. Unfortunately ALL of my DJ mixes are encoded in m4A AAC format so there are pops between EVERY transition when using --gapless-audio=yes setting in MPV player. If I convert the mixes to other formats like FLAC, WAV or AIFF the gaps/pops dissappear and ALL transitions are smooth as butter as with iTunes/Apple Music player. Is there any remedy for m4A gapless playback issue in MPV player?

**Comment by calestyo** [comment]
> Is there any remedy for m4A AAC gapless playback issue in MPV player?

I guess not without getting ffmpeg fixed, as mentioned above.

If you still have the originals, I'd recommend to re-encode in Opus (which is anyway better)...

**Comment by cyberfunk** [comment]
Grinding my teeth right now as I have almost 100 DJ mixes in M4a format.🤣The originals are long gone as I would have run out of hard drive space long ago if I retained the full quality AIFF mixes. Mp3 used to glitch in iTunes with gapless playback so m4a seemed like the logical move in the Apple ecosystem. What really chaps my circuits is that to my knowledge m4a is the ONLY codec to glitch with gapless and mp4. Whyyyyyyyyyyyyyyy🤣

**Comment by calestyo** [comment]
Well there's still a chance that they do fix it eventually... few month ago there was at least some activity in terms of comments on the upstream bug.

It may be possible to offer a bounty to ffmpeg developers... at least some tickets in their issue tracker are flagged like this:
https://trac.ffmpeg.org/tags/%27bounty%27

Though one should probably ask them first, how that works.

**Comment by cyberfunk** [comment]
Thanks for the tips althoug this is deeper down the rabbit hole than I expected to go. I need to hit up my metalic brother the Mandalorian to check on said bounties.🤔🤖

**Comment by ValeZAA** [comment]
Thid should be all fixed now. Remainder is removed. Eac3 is also gapless now in mp4
