### ISSUE TITLE
About the recent audio filters removal

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#2286]
I'm a bit against the following removal:
* extrastereo:
I use it to have a wider audio image when listening to speakers that are too much close each other; there are no equivalent in ffmpeg

* export: 
af_export has worked well for simple vmeters visualization within my gui, xt7-player.
could you please reconsider the removal of export filter until mpv will provide another/better way to do visualizations?

* af_ladspa bridge:
There are tons of ladspa plugins like multiband compressor (which i find very useful for music content)
For movies, i used the following since years:
-af ladspa="/usr/lib/ladspa/fast_lookahead_limiter_1913.so":fastLookaheadLimiter:[20,0,2]
...as an effective "set and forget" and light on cpu audio compressor (drc) (volnorm is not very effective and ffmpeg compband not only is more cpu hungry, but needs to know the input channels  number as a parameter)... not to mention the ladspa high quality parametric equalizers; there are also ambient equalization (in the time domain) filters you can't find elsewhere to use with mpv.
I know ladspa is a filter present in ffmpeg too, but it needs to be explicitely enabled at compile time, and it is not (at least on my distro, arch, which includes ladspa in mpv); 
Yet, mpv "wraps" other filters over ffmpeg (eg: see af_volume), and ladspa seems a much simpler, yet useful, one;
Really, why the removal? Could you please reconsider?

Anyway, i already did a request to ffmpeg packager to include ladspa in arch anyway.

Thanks you very much for your attention.

**Comment by richardpl** [comment]
compand doesnt need input channels as parameter any more, you can also use dynaudnorm. I will look at porting bunch of ladspa filters to lavfi soon.

**Comment by kokoko3k** [comment]
Doesn't compband needs the attack/decays to be the same number of channels as input audio in order to work properly? I'll check dynaudionorm whith the next ffmpeg release .
Anyway i vote for the port of fast_lookahead_limiter_1913.so from swh-plugins for an effective and light drc :)

**Comment by richardpl** [comment]
At end I picked one from calf because its lgpl.

**Comment by richardpl** [comment]
Also i ported extrastereo to lavfi.

**Comment by kokoko3k** [comment]
Thanks for your work.
Just a question, do you know why ffmpeg does not enable ladspa as default?

**Comment by lachs0r** [comment]
FFmpeg only enables the bare minimum of 3rd party libraries by default,
which does not include codecs and filters.

**Comment by kokoko3k** [comment]
I just tried to use ladspa with ffmpeg, but i've got:
```
#mpv audiofile.ogg  -af lavfi="[ladspa=file=/usr/lib/ladspa/fast_lookahead_limiter_1913.so:p=fastLookaheadLimiter:c=c0=20|c1=0|c2=2]" -v

[ffmpeg] format: Cannot select channel layout for the link between filters format and out.
[ffmpeg] format: Unknown channel layouts not supported, try specifying a channel layout using 'aformat=channel_layouts=something'.
[lavfi] Can't configure libavfilter graph.
[af] Reinitialization did not work, audio filter 'lavfi' returned error code -2
[af] Audio filter chain:
[af]   [in] 44100Hz stereo 2ch floatp
[af]   [lavfi] 0Hz empty 0ch ?? <-
[af]   [out] 0Hz empty 0ch ??
[af]   [ao] 0Hz empty 0ch ??
[af] Could not create audio filter chain.
[cplayer] Error at audio filter chain pre-init!
[ad] Uninit audio filters...
[lavfi] lavfi: create graph: 'ladspa=file=/usr/lib/ladspa/fast_lookahead_limiter_1913.so:p=fastLookaheadLimiter:c=c0=20|c1=0|c2=2'
[ffmpeg] src: tb:1/44100 samplefmt:fltp samplerate:44100 chlayout:0x3
[ffmpeg] format: auto-inserting filter 'auto-inserted resampler 0' between the filter 'Parsed_ladspa_0' and the filter 'format'
[ffmpeg] format: Cannot select channel layout for the link between filters format and out.
[ffmpeg] format: Unknown channel layouts not supported, try specifying a channel layout using 'aformat=channel_layouts=something'.
[lavfi] Can't configure libavfilter graph.
[lavfi] Can't recreate libavfilter filter after a seek reset.
```

It works this way:
```
mpv /mnt/nas.crypt/Musica/Coldplay\ -\ Mylo\ Xyloto/02-coldplay-hurts_like_heaven.ogg  -af lavfi="[ladspa=file=/usr/lib/ladspa/fast_lookahead_limiter_1913.so:p=fastLookaheadLimiter:c=c0=20|c1=0|c2=2,aformat=channel_layouts=stereo]"
```
even adding mpv's --audio-channels=<a layout> don't work.

So it seems more complicated than in the past.
Is there a way to automatically guess the output layout?

**Comment by kokoko3k** [comment]
It happens with other filters too.
...but ffplay seems to work fine with the same -af option.

**Comment by ion1** [comment]
I have used
```
af-add=ladspa=/usr/lib/ladspa/mbeq_1197.so:mbeq:[-24,-24,-24,0,0,0,0,0,0,0,0,0,0,0,0]
```
to attenuate low frequencies when my neighbors are sleeping and
```
af-add=ladspa=/usr/lib/ladspa/fast_lookahead_limiter_1913.so:fastLookaheadLimiter:[12,0,2,0]
```
as a compressor that guarantees no distortion.

I hope this functionality will remain available. Thank you.

**Comment by richardpl** [comment]
Extrastereo is now in lavfi.

**Comment by richardpl** [comment]
Added also stereowiden, and you can try volume=20dB,alimiter for alternative to fast lookahead limiter.

**Comment by kokoko3k** [comment]
0.11 released; i guess this should be closed.
