### ISSUE TITLE
Supported features on README

### ISSUE THREAD

**Issue by vit1251** [mpv-player/mpv#2292]
Hello,

I am reading announce on opennet.ru and does not have features on your player.
Now I am seraching home player for my media collection. This player must circle playing and plaing by playlist.
Another way of use is news block embedding to main playing list, let's I explain this for example I have directory breaking-news and somtimes some script in linux adding to this directory news pplayer mut playing some videos for example long video flims 5 hiour length and when wide in directory breaking-news must pause playing and start breaking news (also may remove played video from braking news directory)

I view two direction of this problem:
1. Moitoring directory (no problem);
2. Pause and continue playing (language binding Python, Rubyt and etc

Can your MPV resolv this case?

**Comment by kevmitch** [comment]
I'm not sure I understand exactly what you're describing, but the [JSON ipc protocol](http://mpv.io/manual/stable/#json-ipc) might suit your needs. It allows you to read and write JSON commands to a shared socket with mpv.

If you want something more integrated, you can always link to the libmpv c library. There are a couple [python bindings](https://github.com/mpv-player/mpv/wiki/Scripting-language-bindings) to this library if you prefer.
