### ISSUE TITLE
seeking through lavfi graphs?

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#2296]
```
mpv av://lavfi:amovie=documenti/Musica/Guns\ And\ Roses\ -\ Sweet\ Child\ Of\ Mine.mp3  -v
[..]
[cplayer] Run command: seek, flags=9, args=[5.000000, relative, unused]
[lavf] Seek failed (Invalid argument)
[ffmpeg] SWR: discarding 1000 audio samples
[statusline] A: 00:00:02
[cplayer] Run command: seek, flags=9, args=[-5.000000, relative, unused]
[ffmpeg] SWR: discarding 1000 audio samples
[lavf] Seek failed (Invalid argument)
```
I'd like to use lavfi to make use of [audio to video] filters provided by ffmpeg and make audio visualization available again (byebye af_export ) within my frontend.

**Comment by richardpl** [comment]
Why are you use av://lavfi:amovie that is insane.....

**Comment by kokoko3k** [comment]
I already wrote that:
I'd like to use lavfi to make use of [audio to video] filters provided by ffmpeg and make audio visualization available again (byebye af_export ) within my frontend.

Is there another way to use audio-to-video filters?

**Comment by wm4** [comment]
It doesn't support seeking.

**Comment by richardpl** [comment]
Currently not, even ffplay does not support them directly.
