### ISSUE TITLE
Playback problems with files encoded in 4:4:4

### ISSUE THREAD

**Issue by Cpuroast** [mpv-player/mpv#2298]
Nvidia GT 650M OSX 10.10.5

git-0eb72d7 has playback issues with files encoded in 4:4:4.
git-e1fbd3b does not.

When I playback using git-0eb72d7 without a config file, the colors go all wonky and you can't see the picture, but no errors are logged.

When I playback the same file using git-0eb72d7 using vo=opengl-hq, the colors go all wonky and you can't see the picture and you get this in the log:

[vo/opengl-hq] fragment shader source:
[vo/opengl-hq] [  1] #version 150
[vo/opengl-hq] [  2] #define RG rg
[vo/opengl-hq] [  3] #define texture1D texture
[vo/opengl-hq] [  4] #define texture3D texture
[vo/opengl-hq] [  5] out vec4 out_color;
[vo/opengl-hq] [  6] in vec2 texcoord0;
[vo/opengl-hq] [  7] in vec2 texcoord1;
[vo/opengl-hq] [  8] in vec2 texcoord2;
[vo/opengl-hq] [  9] in vec2 texcoord3;
[vo/opengl-hq] [ 10] in vec2 texcoord4;
[vo/opengl-hq] [ 11] in vec2 texcoord5;
[vo/opengl-hq] [ 12] uniform mat3 colormatrix;
[vo/opengl-hq] [ 13] uniform vec3 colormatrix_c;
[vo/opengl-hq] [ 14] uniform sampler2D texture0;
[vo/opengl-hq] [ 15] uniform vec2 texture_size0;
[vo/opengl-hq] [ 16] uniform sampler2D texture1;
[vo/opengl-hq] [ 17] uniform vec2 texture_size1;
[vo/opengl-hq] [ 18] void main() {
[vo/opengl-hq] [ 19] float luma = texture(texture0, texcoord0).r;
[vo/opengl-hq] [ 20] luma *= 64.061584;
[vo/opengl-hq] [ 21] color = vec4(luma, chroma, 1.0);
[vo/opengl-hq] [ 22] // color conversion
[vo/opengl-hq] [ 23] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[vo/opengl-hq] [ 24] color.a = 1.0;
[vo/opengl-hq] [ 25] // scaler pre-conversion
[vo/opengl-hq] [ 26] color.rgb = clamp(color.rgb, 0.0, 1.0);
[vo/opengl-hq] [ 27] color.rgb = pow(color.rgb, vec3(1.961));
[vo/opengl-hq] [ 28] // main scaling
[vo/opengl-hq] [ 29] out_color = color;
[vo/opengl-hq] [ 30] }
[vo/opengl-hq] fragment shader compile log (status=0):
[vo/opengl-hq] ERROR: 0:21: Use of undeclared identifier 'color'
[vo/opengl-hq] ERROR: 0:21: Use of undeclared identifier 'chroma'
[vo/opengl-hq] ERROR: 0:23: Use of undeclared identifier 'color'
[vo/opengl-hq] ERROR: 0:23: Use of undeclared identifier 'color'
[vo/opengl-hq] ERROR: 0:24: Use of undeclared identifier 'color'
[vo/opengl-hq] ERROR: 0:26: Use of undeclared identifier 'color'
[vo/opengl-hq] ERROR: 0:26: Use of undeclared identifier 'color'
[vo/opengl-hq] ERROR: 0:27: Use of undeclared identifier 'color'
[vo/opengl-hq] ERROR: 0:27: Use of undeclared identifier 'color'
[vo/opengl-hq] ERROR: 0:29: Use of undeclared identifier 'color'
[vo/opengl-hq]
[vo/opengl-hq] shader link log (status=0): ERROR: One or more attached shaders not successfully compiled
[vo/opengl-hq]
[vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
[vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
[vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
[vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
[vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
[vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.

**Comment by Cpuroast** [comment]
git-0eb72d7
vo=opengl-hq
![opengl-hq](https://cloud.githubusercontent.com/assets/3321892/9751637/1e8a77b4-5675-11e5-9d10-29f2ab1ece15.jpg)
git-0eb72d7
vo=opengl-hq:scale=ewa_lanczossharp:scale-antiring=0.5:cscale=ewa_lanczossharp:blend-subtitles=video:interpolation:source-shader=~~/deband.glsl
![opengl-hq-good-quality](https://cloud.githubusercontent.com/assets/3321892/9751649/3e5d352c-5675-11e5-84dc-e777aedb0d1c.jpg)
git-e1fbd3b
vo=opengl-hq:scale=ewa_lanczossharp:scale-antiring=0.5:cscale=ewa_lanczossharp:blend-subtitles=video:interpolation:source-shader=~~/deband.glsl
![opengl-hq-good-quality-older-build](https://cloud.githubusercontent.com/assets/3321892/9751665/7e9b7dd8-5675-11e5-8125-599931cb5046.jpg)

**Comment by haasn** [comment]
Found the issue, it was in this part of the diff:

```
-    if (p->image_desc.flags & MP_IMGFLAG_SUBSAMPLED && nontrivial) {
+    if (p->image_desc.flags & MP_IMGFLAG_SUBSAMPLED) {
         GLSLF("// chroma scaling\n");
         pass_sample(p, 1, &p->scaler[2], cscale, 1.0, p->image_w, p->image_h,
                     chromafix);
         GLSL(vec2 chroma = color.rg;)
-        p->use_indirect = true;
-    } else {
-        // No explicit scaling needed, either because it's trivial (ie.
-        // bilinear), or because there's no subsampling. We have to manually
-        // apply the fix to the chroma coordinates because it's not implied by
-        // pass_sample.
-        GLSL(vec4 color;)
-        gl_transform_rect(chromafix, &p->pass_tex[1].src);
-        if (p->plane_count > 2 && !merged) {
-            gl_transform_rect(chromafix, &p->pass_tex[2].src);
-            GLSL(vec2 chroma = vec2(texture(texture1, texcoord1).r,
-                                    texture(texture2, texcoord2).r);)
-        } else {
-            GLSL(vec2 chroma = texture(texture1, texcoord1).rg;)
-        }
     }
```

I'm not sure what the better option to resolve this would be:

1. reintroduce the “trivial” (no subsampling) codepath + correction logic, which I also just noticed actually decreases visual quality for 4:4:4 content with a nonzero chroma subpixel offset

2. always force the chroma scaler to run, which makes no difference for 4:2:0 but would slow down 4:4:4 content. (This would, however, improve the visual quality by using the chroma scaler to apply the subpixel offset)

I'm leaning towards 2.

**Comment by wm4** [comment]
Then do 2. There's always dumb mode for performance, and 4:4:4 is rare.

**Comment by wm4** [comment]
Actually, I just remembered that 4:4:4 never has a chroma offset (from what I remember), so that argument doesn't count.

**Comment by haasn** [comment]
Okay, then I would say the best course of action is to reintroduce a simpler version of the 4:4:4 fallback code that ignores chroma offset (and also doesn't have the nested conditional due to ‘merged’ now always being true).

Note that I have redesigned the layout of this entire function, in part to introduce debanding as a native functionality, which depends on #2260. I would prefer fixing this in the restructured version, rather than this version. Would it be possible to merge that (+ the subsequent deband PR that depends on it) instead of writing a patch for this? (You can also revert the ‘else’ branch of the diff above as-is to fix it for now)

**Comment by wm4** [comment]
This should be fixed in git master now.
