### ISSUE TITLE
Hotkey to scale the video to "Fit the screen"

### ISSUE THREAD

**Issue by homever** [mpv-player/mpv#2301]
I know how to set the initial player widow size by `autofit=100%x100%`
But, is there a way to create a hotkey in `input.conf` to achieve this?
I am on a Mac. Hope this feature can be added using "CMD+3" to "Fit the screen size", but not in full screen mode.

Thanks.

**Comment by wm4** [comment]
Use fullscreen mode?

**Comment by wm4** [comment]
Or rather, what's the problem with fullscreen mode?

**Comment by homever** [comment]
hmm, consider it a low-priority feature request :dango:

**Comment by wm4** [comment]
Well, I still don't understand the purpose. Fullscreen mode does this, as far as I understand.

**Comment by homever** [comment]
I will have to keep monitoring the servers tasking all time by getting a visual UL/DL speed on Menubar/Dock.

**Comment by bitingsock** [comment]
I think he doesn't want the video to be enveloped when fullscreen.

**Comment by wygsephi** [comment]
I was trying to find this feature, too. For me, instead of binding set window-scale 1 with command+1, I would rather bind it with something which is same as autofit=50%x50% and bind command+2 with autofit=90%x90%, or some other ratio. It could be in pixels, too. Thanks for considering to add this feature.

**Comment by chella1cm** [comment]
Try --panscan=1.0

**Comment by FichteFoll** [comment]
mpv-hc allows this using alt+4 (or alt+5) bindings, which I can be translated to `--autofit=66%x66%` and `--autofit-smaller=66%x66%` respectively.

I would love to have the ability to define commands for these "options".

**Comment by asd123cqp** [comment]
I made a script which looks like this:

```lua
function fit_to_screen()
    scale = 1440.0 / mp.get_property("width")
    mp.set_property("window-scale", scale)
end

mp.add_key_binding("meta+9", "Fit_Screen", fit_to_screen)
```

You can change "1440.0" to your screen width -- if you are using a macbook it should be the scaled resolution, not the native resolution.

Two problem remaining:

1. The screen width is hardcoded -- I can't figure out how to detect automatically. It's annoying if you sync your config over multiple devices.

2. The window position is often incorrect -- I can't figure out how to move the window with script. You'll need to move the window after resized.

Hope it helps.

**Comment by haasn** [comment]
Shouldn't the window manager be doing this? On xmonad I just hit meta+f and my current window will cover the entire display (sans the informational bar at the top).

**Comment by asd123cqp** [comment]
I am not so sure about xmonad on OSX...

**Comment by FrostedMint** [comment]
I think Cmd-Z (Window » Zoom) already does this. Testing on 10.12.1 / mpv-0.22.0, it will shrink or grow the window such that it is as large as possible without going off the edge of the screen. Or am I misunderstanding the feature request?

**Comment by asd123cqp** [comment]
@FrostedMint you are absolutely right, except that cmd+z won't work if you use the "border=no" option.

**Comment by homever** [comment]
@FrostedMint This is just brilliant 💃

**Comment by SteveJobzniak** [comment]
@asd123cqp You're right... Cmd+Z does nothing if No-border mode is used...

**Comment by SteveJobzniak** [comment]
I won't open a separate ticket about this, until I know whether this is a BUG on OS X:

`mp.set_property("geometry", "50%:50%")`

Does nothing. It's supposed to center the player. But maybe it doesn't work on ANY OS after the playback has already begun? Or is this just an OS X bug?

**Comment by wm4** [comment]
`geometry` is normally only read when the window is first shown, on all platforms.

**Comment by SteveJobzniak** [comment]
@wm4 Thanks for clarifying that it isn't a bug.

**Comment by SteveJobzniak** [comment]
@asd123cqp Here's the final code I came up with. Lets me scale the window to any bounds, automatically.

```lua
function quick_scale(targetwidth, targetheight, scalefactor)
    -- Check parameter existence.
    if (targetwidth == nil or targetheight == nil or scalefactor == nil) then
        mp.osd_message("Quick_Scale: Missing parameters")
        return nil -- abort
    end

    -- Ensure that the incoming strings are valid numbers.
    targetwidth = tonumber(targetwidth)
    targetheight = tonumber(targetheight)
    scalefactor = tonumber(scalefactor)
    if (targetwidth == nil or targetheight == nil or scalefactor == nil) then
        mp.osd_message("Quick_Scale: Non-numeric parameters")
        return nil -- abort
    end

    -- If the scale factor isn't 1 (100%), we re-calculate target size.
    if (scalefactor ~= 1) then
        targetwidth = targetwidth * scalefactor
        targetheight = targetheight * scalefactor
    end

    -- Find smallest necessary video scale that fits video area in dimensions.
    -- This only looks at video and doesn't take window borders into account!
    widthscale = targetwidth / mp.get_property("width")
    heightscale = targetheight / mp.get_property("height")
    scale = (widthscale < heightscale and widthscale or heightscale)

    -- Apply the new video scale.
    mp.set_property_number("window-scale", scale)
end

-- Bind this via input.conf. Examples:
--   To fit a video to 100% of a 1680x1050 desktop size:
--     Alt+9 script-message Quick_Scale "1680" "1050" "1"
--   To fit a video to 80% of a 1680x1050 desktop size:
--     Alt+9 script-message Quick_Scale "1680" "1050" "0.8"
--   To fit a video to a 200x200 box:
--     Alt+9 script-message Quick_Scale "200" "200" "1"
mp.register_script_message("Quick_Scale", quick_scale)
```

**Comment by SteveJobzniak** [comment]
@FichteFoll @Hrxn @homever Hey guys, I saw your thumbs up and thought I'd let you know in case you started using the script: I edited the message above to extend it with the ability to set a "maxvideoscale".

It's very useful if you want to prevent the rescaling from ever going larger than the video's natural size.

For example, one of the thing I do is: Resize the video to 80% of my 1680x1050 desktop, but never allow the video to become larger than 150% of its natural size. That prevents getting too much enlarging if the video is low resolution.

You can set the new parameter to -1 to allow unlimited enlarging, to literally fill up the requested target size even if your original video was only a postage-sized 5x5 pixels ;)

**Comment by SteveJobzniak** [comment]
I've now published this and a few other scripts on the wiki:

https://github.com/mpv-player/mpv/wiki/User-Scripts

* **[auto-keep-gui-open](https://github.com/SteveJobzniak/mpv-tools/blob/master/auto-keep-gui-open.lua)**  
  Intelligently switches mpv's "keep-open" behavior based on whether you are running in video-mode or audio-only mode.

* **[cycle-video-rotate](https://github.com/SteveJobzniak/mpv-tools/blob/master/cycle-video-rotate.lua)**  
  Allows you to perform video rotation which perfectly cycles through all 360 degrees without any glitches.

* **[quick-scale](https://github.com/SteveJobzniak/mpv-tools/blob/master/quick-scale.lua)**  
  Quickly scale the video player to a target size, with full control over target scale and max scale. Helps you effortlessly resize a video to fit on your desktop, or any other video dimensions you need!

They're all finalized and working perfectly. But if there are ever updated versions, they'll be published there too.

**Comment by asd123cqp** [comment]
@SteveJobzniak great job man! I wish geometry is modifiable via hotkey – then your script would be perfect!

**Comment by SteveJobzniak** [comment]
@asd123cqp Glad I could help.

And geometry modifiable via hotkey, is what this other ticket is about: https://github.com/mpv-player/mpv/issues/3872. Please give your votes/comments/+1 there. ;-)

**Comment by kevmitch** [comment]
sounds like this was solved with a script.

**Comment by pedoc** [comment]
@chella1cm it's work for me，many thanks

**Comment by DogancanYr** [comment]
Basic solution.
Open the mpv.conf file located at C:\Users\[Username]\AppData\Roaming\mpv\mpv.conf, add the line keepaspect=no, save the file, and restart MPV.
