### ISSUE TITLE
Handle faulty ordered chapter file

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#2308]
MPV seems failed to open a video containing faulty ordered chapter file (whether the referenced file exist or not)

chapter file:
http://pastebin.com/c64DNUqm

**Comment by ChrisK2** [comment]
The file is not faulty, just "pointless" as each linked-in segment is effectively 0 seconds long, so it produces an empty timeline. Complain to the idiot that created those chapters.

**Comment by ChrisK2** [comment]
Or just use ``--no-ordered-chapters`` to ignore the timeline those chapters try to build.

**Comment by shinchiro** [comment]
Is it good idea to treat 0 duration linked-in segment as not exist, so the
player still able to play video..Noob user will panic when mpv is not
showing up when playing such file
