### ISSUE TITLE
OSX Assertion error with recent head

### ISSUE THREAD

**Issue by maru-sama** [mpv-player/mpv#2309]
I just pulled latest HEAD and recompiled mpv. When I open a video file I get the following assertion..

Assertion failed: (n_channels >= 1 && n_channels <= 4), function find_tex_format, file ../video/out/opengl/video.c, line 463.

This is happening on OSX 10.10.5 with an ATI card, I am not really sure what's happening here.

**Comment by maru-sama** [comment]
Ok I tracked it down to the last commit f1205293a70b13f53: command: make "add <property> 0" not change the value

Reverting this commit fixes the issue

**Comment by wm4** [comment]
Probably ABI mismatch due to ffmpeg changes. Recompile ffmpeg, install it, recompile mpv.

**Comment by wm4** [comment]
Also, this commit definitely doesn't trigger it. (Saw this comment after I wrote my reply.)

**Comment by maru-sama** [comment]
Ok I close this, I completely cleaned up the mpv-build repository I use for compilation and now it works. 
It should't really make a difference since but it apparently fixed the assertion
I get a different error now though but will file this as a different issue.
