### ISSUE TITLE
Audio Became Lower In v0.10.0

### ISSUE THREAD

**Issue by Geyup** [mpv-player/mpv#2313]
I'm using Slackware 14.1 x86_64.

I have in my mpv config; ```volume=10```, and when I started any video I could always here the volume quite well, now I hear nothing.

In the 0.9x versions audio played louder, now with the release of 0.10.0 I have to raise the volume twice as much to get the same level.

Hmm what's going on here?

**Comment by AirPort** [comment]
The volume option was changed between 0.9 and 0.10: 68bbab0

**Comment by lachs0r** [comment]
Also, the scale is now cubic.

**Comment by Geyup** [comment]
@AirPort ok...

@lachs0r what do you mean?
