### ISSUE TITLE
Specify fallback font for Chinese

### ISSUE THREAD

**Issue by rsy96** [mpv-player/mpv#2315]
As a Chinese, I often play video with Chinese subtitles. These subtitles often specify fonts available only on Windows, but not on my OS X. For example,

> fontconfig: cannot find font 'SimHei', falling back to 'Verdana'
fontconfig: cannot find glyph U+4EBA in font 'SimHei', falling back to 'NanumGothic'
fontconfig: cannot find glyph U+5F39 in font 'SimHei', falling back to 'Arial Unicode MS'

The problem with this automatic fallback algorithm is that it usually picks suboptimal font, and it combines several visually different fonts to display a single language, with less than ideal result. I would like to manually specify that the font `SimHei` will always be replaced with `STHeiti` (a Chinese font readily available on OS X). Is there any way to do this?

**Comment by pigoz** [comment]
Try to update to libass' git masters, it implements font fallbacks in a more correct way that is platform specific. See https://github.com/mpv-player/homebrew-mpv

**Comment by zmwangx** [comment]
I think the best way to go is to use fontconfig aliases. This way you don't need to rely on default fallback mechanisms. See `/usr/local/share/doc/fontconfig/fontconfig-user.html` (or adapt the prefix).

**Comment by wm4** [comment]
libass git master doesn't use fontconfig on OSX anymore, so that won't work.

**Comment by zmwangx** [comment]
> libass git master doesn't use fontconfig on OSX anymore

Thanks for the info. That's kind of sad, guess I'll need to learn another way of customization. However, I believe my mpv 0.10.0 is built against latest libass git master (https://github.com/libass/libass/commit/4cd05007335dddb7805acac90eae76ad0dcbed34), yet my `sub-text-font`, which is an alias family defined in `fonts.conf`, still seem to work. How's that possible when it doesn't use `fontconfig`?

**Comment by wm4** [comment]
Either you don't actually use this function, or libass was somehow compiled without CoreText support (which should never happen by default).

**Comment by zmwangx** [comment]
> Either you don't actually use this function

Ah, guess that's the case. I tried some SubRip subtitles (and thought they were drawn with libass, but probably not?) and haven't really tried any ASS. Anyway, I won't complain when it works...

**Comment by wm4** [comment]
Sorry, typo... I meant build, not function (how does this happen?). All text subtitles are actually rendered with libass in mpv.

**Comment by zmwangx** [comment]
Turned out that although I did build libass's git master, my mpv build was linked against libass 0.12.3... Sorry.

So, maybe this is the wrong place to ask, but is there a way to force latest libass to use fontconfig? Not being able to use a fontconfig family that specifies a list of fallbacks is kind of a bummer when one uses multiple languages whose charsets are not covered by one font.

**Comment by wm4** [comment]
You can compile libass with ``--disable-coretext``. Maybe libass coretext fallback support should be improved then?

**Comment by zmwangx** [comment]
> Maybe libass coretext fallback support should be improved then?

Dunno... I think it's mainly a problem of control. With latest libass trying to render, say, a styleless SubRip subtitle in Simplified Chinese, and `sub-text-font` doesn't exist or doesn't include the right glyphs, it automatically falls back to STHeiti (what the OP wants, incidentally), which is kind of nice but definitely isn't my favorite font. With fontconfig I have full control over the list of fallbacks, but without it I don't see a way to customize to my liking.

**Comment by rsy96** [comment]
@pigoz I tried `libass-git`, but the result is the same.
@zmwangx Can you post an example config that manually specify the alias?

**Comment by zmwangx** [comment]
> Can you post an example config that manually specify the alias?

`fonts.conf`:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>SimHei</family>
    <prefer>
      <family>STHeiti</family>
    </prefer>
    <default>sans-serif</default>
  </alias>
</fontconfig>
```

Didn't test, but should probably work.

**Comment by zmwangx** [comment]
> I tried `libass-git`, but the result is the same.

Btw, are you sure you are really using `libass-git`? I made a mistake earlier, when I thought I linked against git but in fact picked up 0.12.3. Maybe worth checking: `otool -L /usr/local/bin/mpv`.

**Comment by rsy96** [comment]
@zmwangx Indeed `mpv` is not linked to `libass-git`. Weird since the installation automatically picks up `libass-git` as a requirement.

The `fonts.conf` you provided works. I am settling on this for now.

**Comment by rsy96** [comment]
It is a bit odd that `homebrew/mpv` requires `mpv-player/mpv/libass-git` yet not linked to it after installation.

**Comment by zmwangx** [comment]
`mpv-player/mpv/libass-git` is keg-only, and its path isn't explicitly included in the lib search path, so the build can't pick up `libass-git`. One temporary workaround is to unlink `libass` and force link `mpv-player/mpv/libass-git`. I'll submit a patch to `homebrew/mpv` later if I've got time to investigate.
