### ISSUE TITLE
MPV black screen & OSD Chinese characters display issues on OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by homever** [mpv-player/mpv#2316]
Just updated to 10.11 GM.
By adding`vo=opengl-hq`, the latest bundle (git-e76f503)shows black screen, but `vo=opengl` seems fine.
In addition, the OSD Chinese characters will not show up.

![mp4 - mpv 2015-09-13 11-28-46](https://cloud.githubusercontent.com/assets/3777914/9835088/bd48faf4-5a0a-11e5-9ed7-b311aaeddbb4.png)

**Comment by cwbsw** [comment]
` osd-font='Hiragino Sans GB'`
    `sub-text-font='Hiragino Sans GB'`

**Comment by bodayw** [comment]
Looks like Chinese font fallback is completely broken on OS X 10.11.

I also got report saying that the new libass doesn't recognize/fallback to some common Chinese fonts, including the new system default "PingFang", showing blocks as in the picture above, with heavy frame drops.

You can manually assign a font as a workaround, as @cwbsw suggested.

**Comment by bodayw** [comment]
With the new build Chris uploaded today, the Chinese font issue should be fixed.

I personally don't have the black screen issue suggested by OP. Unless OP still have the black screen problem, otherwise we can close this.

**Comment by homever** [comment]
@cwbsw @bodayw Things worked out again. Thanks!
