### ISSUE TITLE
MPV goes blank after minimize on Windows 10

### ISSUE THREAD

**Issue by dedoyxp** [mpv-player/mpv#2318]
![screenshot 1](https://cloud.githubusercontent.com/assets/14260647/9836999/a718e29a-5a59-11e5-89cf-36e9669c573f.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/14260647/9837000/a720acfa-5a59-11e5-8457-15dfb03d3d5a.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/14260647/9837001/a729c0ba-5a59-11e5-8d00-a9bc96298750.png)
The mpv after blank is still running without not respoding problem, the sound still playing.

I use the latest mpv
I don't know what code I must display on Windows and how, so I leave it like this.

**Comment by wm4** [comment]
Well, uh, I'd call this a driver bug. What do you have in your config file?

**Comment by lachs0r** [comment]
@dedoyxp Ping?

**Comment by dedoyxp** [comment]
![screenshot 19](https://cloud.githubusercontent.com/assets/14260647/10307064/cf25970c-6c55-11e5-8088-d781a8be331b.png)
Sorry for the late response
But I can't find the config file, is it on AppData or ProgramData?

**Comment by chella1cm** [comment]
This is an example conf file.
https://github.com/mpv-player/mpv/blob/master/etc/example.conf

You can specify a video driver there

**Comment by lachs0r** [comment]
Likely duplicate of #1547, should also be “fixed” with ANGLE.
