### ISSUE TITLE
Windows: only the first instance works

### ISSUE THREAD

**Issue by v-control** [mpv-player/mpv#2319]
I have compiled libmpv for windows using this tutorial (Example with MXE):
https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md

I also compiled libmpv for Linux.

I wrote a class using QT and QT Creator that uses libmpv to play videos.

If I run my project in Linux environment I use
        mpv_set_option_string(mpv, "vo", "vaapi");
        mpv_set_option_string(mpv, "hwdec", "vaapi");

I can create multiple instances of my class and all instances play the video as expected.

If I run my project in a Windows environment (Win 8.1 and Win 10),  I use
        mpv_set_option_string(mpv, "vo", "direct3d");
        mpv_set_option_string(mpv, "hwdec", "auto");

but only the first instance plays the video. he second instance reports

[cplayer] info: Playing: c:\users\dw\Videos\VP_Demo60_2.mp4
[cplayer] info:  (+) Video --vid=1 (*) (h264)
[cplayer] info:  (+) Audio --aid=1 --alang=eng (*) (aac)
[vo/direct3d/win32] error: unable to register window class!
[cplayer] fatal: Error opening/initializing the selected video_out (-vo) device.
[cplayer] info: Video: no video
[cplayer] info: 

Are there any compiler options I have to set when compiling for Windows?
BTW: If I build a stand alone application that uses one instance of my player class, I can execute this application multiple times and play two or more videos at the same time.So it has something to do with multiple instances of the class in the same applicaton.

**Comment by wm4** [comment]
Right, this is because the registered win32 window class is apparently global. I can fix this next week.

**Comment by v-control** [comment]
That would be very great, thank you very much in advance.

**Comment by wm4** [comment]
I didn't test the actual problem, but it should work.

**Comment by v-control** [comment]
Yes, it works. Thank you very much.
