### ISSUE TITLE
Shouldn't PBO be removed from the opengl-hq preset?

### ISSUE THREAD

**Issue by Q3CPMA** [mpv-player/mpv#2321]
Hey, after an IRC discussion where I found that the dropped frames I was getting (without any GPU nor CPU resources exhaustion) were coming from the PBO option in opengl-hq and some other guy (lasch0r, I think) said that there were problems too with the Intel driver on Windows, I wondered if this troublesome option shouldn't be removed by default. Does it bring that much to the table?

**Comment by wm4** [comment]
I don't know about this - for nvidia it can be a big help (difference between fluid playback and dropped frames). I'd like to have some more reports about improvements or disimprovements this change can bring.

**Comment by ismail** [comment]
I experience the same problem on Linux using a Nvidia card (old one NVS 300) with the latest supported 340.76 drivers. With the 0.11.0 release I am getting dropped frames with any 1080p h264 content (vdpau is enabled.) Using opengl vo instead of opengl-hq makes the problem goes away. So I am guessing its related to the PBO change.

**Comment by wm4** [comment]
>With the 0.11.0 release I am getting dropped frames with any 1080p h264 content (vdpau is enabled.) 

vdpau hw decoding doesn't even touch the PBO code path.

**Comment by ismail** [comment]
Then I guess its something else that changed in the 0.11.0 release, will
keep looking.

**Comment by wm4** [comment]
opengl-hq probably gained a few features. But opengl got slower too. (Unless you enable "dumb-mode" on it.) Possible that it just got slow enough that your GPU doesn't handle it in realtime anymore.

**Comment by ismail** [comment]
Ok in my case I reproduce dropped frames with "mpv --vo=opengl:scale=spline36:deband" so its not PBO related. I'll open a new bug.
