### ISSUE TITLE
-af volume vs --volume

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#2322]
This produces silence, as expected.
```
mpv  /home/root/documenti/Video/AC3Test.avi  -af volume=volumedb=-200  
```

This one, instead:
```
mpv  /home/root/documenti/Video/AC3Test.avi  -af volume=volumedb=-200  --volume=100
```
Sounds as -af volume was just ignored.

Not that i really have an use for this, i was just testing some audio filters and found that the behaviour is somehow inconsistent, because 100% of -200db should be still -200db, and not 0db.
Is this expected/wanted?

**Comment by wm4** [comment]
Well, what do you expect? The --volume option changes the volume on af_volume. That's how it works. Maybe you can work it around by adding a second af_volume filter, but that's also a bad idea (worse audio quality due to prcession loss).

**Comment by kokoko3k** [comment]
I repeat, it is not really an issue, but man page states:
> NOTE: This filter is not reentrant and can therefore only be enabled once for every audio stream.

**Comment by wm4** [comment]
Is this actually enforced, or just old docs? I think this non-reentrancy thing could just be dropped.

**Comment by kokoko3k** [comment]
It is not just docs:
```
# mpv /videofile.avi -af volume=volumedb=60,volume=volumedb=-60,volume=volumedb=60,volume=volumedb=60,volume=volumedb=60 -msg-level=af=v
Playing: /videofile.avi
 (+) Video --vid=1 (mpeg4)
 (+) Audio --aid=1 (mp3)
[af] Adding filter volume 
[af] Setting option 'volumedb' = '60' (flags = 0)
There can only be one instance of the filter 'volume' in each stream
[af] Removing filter volume 
Error at audio filter chain pre-init!
```

**Comment by richardpl** [comment]
use lavfi-volume it should also be faster

**Comment by wm4** [comment]
And it also doesn't clamp properly, so lavfi vf_volume is not recommended.

**Comment by kokoko3k** [comment]
I don't think i understood properly.
Is good or not to use -af lavfi="[volume=volume=10dB]"  ?

**Comment by richardpl** [comment]
Clamping is for kids, use limiter.
Also clamping works for nonfloat formats.
But seriously if you need clamping your ears gonna suffer.
