### ISSUE TITLE
[opengl-cb] Setting fullscreen property fails only when there is a file loaded

### ISSUE THREAD

**Issue by jdoe0** [mpv-player/mpv#2323]
When using opengl-cb, setting the fullscreen property fails only when there is a file is loaded. When there is no file loaded the property can be set correctly with no error. For consistency, it might be desirable to allow setting the fullscreen property when there is a file loaded as well.

**Comment by wm4** [comment]
If no video is loaded, the property code has no idea whether fullscreening will work or not. Some time ago, the fullscreen property just remained unavailable at all during idle mode. But this got us some complaints. For example, if a script wants to change the fullscreen option at runtime, it'd have to check whether video is running etc. For this reason, I decided that we don't make properties unavailable anymore in general, and instead let them switch the option vlue, which is more convenient for API and script users.
