### ISSUE TITLE
vf=gradfun causing banding under gnome/wayland

### ISSUE THREAD

**Issue by jamdox** [mpv-player/mpv#2329]
using  opengl-hq with backend=x11. Removing vf=gradfun solves banding issue with 10bit h264 video.

**Comment by richardpl** [comment]
you see banding because gradfun supports only 8bit formats.

**Comment by wm4** [comment]
gradfun supports only 8 bit input, so it will force conversion to 8 bit in software using libswscale, which will cause a mjor quality degradation (because swscale was written for speed on pentiums, not quality).

Use mpv git master with opengl-hq - it has debanding now, thanks to haasn.
