### ISSUE TITLE
Vobsub show only the first sentence

### ISSUE THREAD

**Issue by kadogo** [mpv-player/mpv#2331]
Hello,

I have something strange with some vobsub subtitle.

I play the video and I see this in my terminal.
[ffmpeg] ?: Invalid command offset

It work well with VLC or if I load my subtitle with --sub-file

My OS is Debian Jessie
FFmpeg version 2.6.4
MPV version 0.8.3
The two application are installed from http://deb-multimedia.org/

**Comment by kadogo** [comment]
Little more infos.

When I load the extract  .sub with MPV it work.
But when I tried to load the extract sub of my mkv (.mks or .idx / .sub) it do the same problem.

Mkvmerge say me that the idx will be reordered.
That is maybe the problem.

**Comment by wm4** [comment]
Please upload the non-working file somewhere.

**Comment by kadogo** [comment]
Here you are.

http://www20.zippyshare.com/v/4YWSUav7/file.html
http://www20.zippyshare.com/v/PREFgQ3A/file.html
http://www20.zippyshare.com/v/iZIvhPE3/file.html
http://www20.zippyshare.com/v/a03vtuLb/file.html

I upload the work.idx / work.sub (extract directly from the DVD).
The notwork.idx / notwork.sub are extract after muxing.

**Comment by wm4** [comment]
Can you post a mpv log when playing the non-working case?

**Comment by kadogo** [comment]
Here is what I see in my terminal.
I post a dump log too (maybe it can help).

https://zerobin.net/?8546ec84ed00b6a3#Xtp4nQtE2c6ZVx0gASuDU0dT5y18axo9ua2EgcK+w+U=
https://zerobin.net/?78d9bea3f486a401#Y3W/KDH1WkdvmATyCUX+psYrdKgTIHzLbgPbxrWvPC8=

**Comment by wm4** [comment]
Please use sprunge.us or a similar non-intrusive pastebin.

**Comment by kadogo** [comment]
Here you are:
http://sprunge.us/IRiL
http://sprunge.us/SNKK

**Comment by wm4** [comment]
(Didn't need the second one.)

I can mostly reproduce. But note that you should pass the .idx file as option, not the .sub one. For some reason, the situation is even worse with the .idx ones, though.

**Comment by kadogo** [comment]
It's strange but with the extracted idx/sub from the DVD it work only when I use the .sub file

**Comment by wm4** [comment]
I suspect the command is being run, but something else is wrong. Maybe spaces in the file path or so?

**Comment by kadogo** [comment]
To read the subtitles I'm in the directory.
To extract the subs I used h264enc, it use the next command.
/usr/bin/mencoder dvd://1 -dvd-device /dev/dvd   -sid 6 -vobsubout "out" -vobsuboutindex 6  -oac pcm -ovc copy -o /dev/null

The other subs are extracted with the same command. Exemple the arabics sub work without issues.
I can upload it if it can help.

**Comment by wm4** [comment]
Do they work if you play them directly from the DVD?

**Comment by kadogo** [comment]
I just tried it directly with the DVD on mpv and it work nice.

**Comment by wm4** [comment]
Should be fixed in ffmpeg git master.
