### ISSUE TITLE
Different OSX lua script behaviour depending on how binary is run

### ISSUE THREAD

**Issue by gradha** [mpv-player/mpv#2334]
Hi.

I'm trying to implement removal of files through lua scripting and have come up with this script:

```lua
function trash_file()
	-- mp.command("run /Users/gradha/bin/trash \"${filename}\"")
	mp.command("run /bin/cp \"${filename}\" /tmp/script.cp")
	mp.command("playlist-remove current")
end
mp.add_key_binding("meta+bs", "trash_file", trash_file)
```
The ``trash`` binary moves the specified file to the recycling bin. The version you see is commented out and instead runs the ``cp`` command to a temporary file. When I run ``mpv`` with a command line like this:

```
/Users/gradha/Applications/mpv.app/Contents/MacOS/mpv  *
```
Everything works, I get the input file removed/copied depending on the line being commented and the playlist item is removed. However if I run ``mpv`` like this:

```
open -a /Users/gradha/Applications/mpv.app *
```

The playlist entry is removed but the command doesn't seem to run. When I turn on the ``cp`` version I don't get anything at ``/tmp``, neither does the ``trash`` command run (it plays a sound) when I select that version. I don't mind running ``mpv`` through an alias to make this work, but I'm curious as to why one invocation works and the other doesn't. Thanks.

**Comment by wm4** [comment]
Maybe the paths of the filenames are different when starting with ``open``?

**Comment by gradha** [comment]
The parameters as passed on the command line should be the same, my guess is that the current directory is different. I tried to use ``utils.getcwd()`` to dump it somewhere but I don't know lua and all I got were syntax errors. Can you suggest a way to log such variables to a file? The ``open`` version doesn't seem to have stdout or any other logging features.

**Comment by gradha** [comment]
The problem was using the wrong property for expansion, using ``path`` instead of ``filename`` solves the  issue with different directories and also makes the script work when the parameters include subdirectories, which was failing with the plain ``filename`` too in all cases.
