### ISSUE TITLE
audio-file-auto doesn't detect some audio file types.

### ISSUE THREAD

**Issue by moldpiss** [mpv-player/mpv#2336]
When using audio-file-auto=all mpv correctly detects mp3 and vorbis files, however fails to detect opus and audio only webms (containing either vorbis or opus) despite mpv being able to play any of the audio files listed.

**Comment by wm4** [comment]
It goes by file extensions, because actually probing all files that are potential candidates would be inefficient. If you want some extensions added, we can do this.

**Comment by moldpiss** [comment]
If that's the case I think the .opus extension should be added if it isn't already.
