### ISSUE TITLE
Support DCP playback

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#2337]
If I am not mistaken, mpv does not suuper DCP (Digital Cinema Package). It would be nice to have support for that.

A sample (16 GB) can be downloaded from here:
https://download.blender.org/demo/movies/ToS/ToS_4k_DCP.zip

I tried to play the unzipped directory but I got this:

```
Playing: tos_version_05/
[file] This is a directory - adding to playlist.

Playing: tos_version_05/00ff6680-d307-4e7b-90c2-fe67fd222b8c_pkl.xml
Failed to recognize file format.

Playing: tos_version_05/1f4c8235-d835-42e3-87ec-ac6d701342af_cpl.xml
Failed to recognize file format.

Playing: tos_version_05/ASSETMAP.xml
Failed to recognize file format.

Playing: tos_version_05/VOLINDEX.xml
Failed to recognize file format.

Playing: tos_version_05/tos_picture.mxf
[ffmpeg/demuxer] mxf: "OPAtom" with 2 ECs - assuming OP1a
[ffmpeg/video] jpeg2000: unsupported marker 0xFF5F at pos 0x10B
[ffmpeg/video] jpeg2000: Support for 4 components is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
```

**Comment by wm4** [comment]
No idea. Ask on the ffmpeg bug tracker.

**Comment by wm4** [comment]
Actually, what are you asking about? Maybe I'm misunderstanding, and this isn't about playing back the mxf file itself?

**Comment by felagund** [comment]
Indeed. There is a bug in (at least mine version of) ffmpeg that it struggles with that type of 4k jpegs.

however, what I am asking is the ability to play DCP as is, that is video with audio (and subtitles, preferably). Something like:

``` mpv -dcp path/to/dcp/directory```

Right now, MPV just scans the directory for any files it can play but ignores the xml files that specify what is video and what is audio. More samples can be downloaded here: http://www.dcpbuilder.com/download/cinema-packages.html (like this one: http://www.dcpbuilder.com/index.php?mact=DownCnt,cntnt01,click,0&cntnt01name=BBB-BURN-IN_TST-1_S_EN-EN_INT-G_51_2K_UPG_20110712_DSPL_OV.zip&cntnt01link=uploads%252Fdownload%252Fdcp%252FBBB-BURN-IN_TST-1_S_EN-EN_INT-G_51_2K_UPG_20110712_DSPL_OV.zip&cntnt01returnid=94 - 255 MB).

**Comment by felagund** [comment]
Based on this: http://superuser.com/questions/559768/ffplay-how-to-play-together-separate-video-and-audio-files, I can play the DCP like this:

```ffmpeg -lowres 1 -ss 0 -r 24 -i 094cedc9-abf9-4e60-b947-26fae2a8b781_picture.mxf -ss 0 -i c98425dc-4b65-42b1-80f4-d8909a65bbc3_sound.mxf -ac: 2 -c:v mpeg2video -f avi - | ffplay -```

(-lowres 0 lags on my machine). I just wish mpv did this magic for me so that I would not have to use anything as complicated.

**Comment by felagund** [comment]
(also, I am not sure this is the quickest way. I somehow think a quad core i7 2,6 GHz computer should be able to play a 2k movie smoothly, but maybe I am missing something).

**Comment by wm4** [comment]
This is a truly stupid format. Just like what you expect from something "professional". So they use the overcomplicated industry-turd mxf, and because it would be too simple otherwise, they don't even mux the individual streams into a single file. Instead you have to fish them out from some xml files (?). 

So the sample file you posted I could play with:
```
mpv 094cedc9-abf9-4e60-b947-26fae2a8b781_picture.mxf --audio-file=c98425dc-4b65-42b1-80f4-d8909a65bbc3_sound.mxf
```

...except that my brand-new system is too slow to play it in realtime, because it's using jpeg2000, a truly bad choice for ANYTHING that has to do with multimedia.

What are these idiots doing?

(Sorry, couldn't miss the chance to insult the whole industry.)

**Comment by felagund** [comment]
I wholeheartadly agree, but this is the format that is actually used in about any cinema in the world (basically, if you go to see a movie shot in the last few years, you are watching a projection of this format). It would be nice to be able to test it on one's desktop.

**Comment by wm4** [comment]
It wouldn't be hard, but it requires parsing XML. XML is highly complicated and there's no good XML parsing library.

**Comment by felagund** [comment]
Actually, there is a open source (Im a not sure about the license, but VLC ships it) library for playing DCPs: http://www.cinecert.com/asdcplib/download/ 

Actually, a working support for DCP playback has been recently commited to VLC: https://trac.videolan.org/vlc/ticket/16999

As for jpeg2000, my not-so-weak system is too struggling, but there are libraries that use hardware acceleration that might actually enable realtime playback: http://apps.man.poznan.pl/trac/jpeg2k

Given this, wouldn't you reconsider? In a few years time, I hope high-edn machines will be able to play this even without using a graphics cards.

**Comment by wm4** [comment]
All that would have to go into libavcodec and libavformat.

**Comment by felagund** [comment]
Meaning that I should ask ffmpeg to include asdcplib?

**Comment by wm4** [comment]
Yes.

**Comment by haasn** [comment]
Probably easier to transcode it to FFv1 or something before watching.

**Comment by felagund** [comment]
Well, I don't want to watch it. I want to check whether the DCP is well formed (I work as a subtitler and sometimes we are asked to prepare DCP subtitles). I frequently use MPV when creating subtitles but I cannot when working on a DCP.

**Comment by haasn** [comment]
Sure, but I mean you can use the FFv1 version as a subtitle reference - the timestamps will be the same, no?

**Comment by felagund** [comment]
@haasn  Yes, they will be the same. But in practice I will be checking SRT agains some .mp4 or something. In theory, .xml DCP subtitles should be fine against a DCP version of the MP4, but one needs to check it anyway. Sometimes we are asked to deliver the whole DCP package. I can check VLC if the DCP plays (even though VLC does not cope with the subtitles yet, I filled a bug there), but I kind of prefer MPV:-). Of course, the final check must be done in an actual cinema with an actual DCP server connected to a DCP projector, but it it helpful to check everything on one's PC before.

**Comment by felagund** [comment]
Ok, issue filled with ffmpeg: https://trac.ffmpeg.org/ticket/6166#
