### ISSUE TITLE
mpv uses more cpu than does vlc

### ISSUE THREAD

**Issue by tranjeeshan** [mpv-player/mpv#2338]
mpv is a CLI based media player. It should take less CPU compared to other GUI based media player. But I found that it takes more CPU than does VLC. Any specific reason?

**Comment by wm4** [comment]
Could be any reason, down to different ffmpeg versions etc. It's hard to tell without specific information. It might also depend on the terminal emulator (e.g. we found once that weston's terminal severely degraded performance).

**Comment by wm4** [comment]
PS: in my own test, mpv used slightly less with default settings (for each player), but again, it's pretty useless and _meaningless_ comparison without context.

**Comment by tranjeeshan** [comment]
I used mpv with xfce-terminal on Debian 8 jessie 'Xfce'.

**Comment by kevinlekiller** [comment]
With hardware decoding (vaapi) and opengl-hq , on a low power (U series) i3, the CPU usage is only ~8% and GPU usage is ~25% (according to intel_gpu_top) for 1080p 24fps h.264 content, drops to 10% GPU usage with scaler-downsizes-only. I find that is very low considering the good visual quality.

I've not tested performance in VLC, so can't comment on that.

**Comment by lachs0r** [comment]
It depends on a lot of factors anyway. For example, the opengl video output 
might use more CPU time than xv with bad drivers.

**Comment by mc4man** [comment]
vlc (2.x.x) by default has hwdec set to automatic so if available/suitable it will be using it.
Direct comparisons show mpv slightly more efficient with or  without hwdec, at least with opengl or vaapi/vdpau
