### ISSUE TITLE
cpu and memory usage

### ISSUE THREAD

**Issue by simon1tan** [mpv-player/mpv#2340]
Comparing mpv to mplayer, it looks like mpv uses more cpu(18% vs 10%) and memory(2.5 vs 1.5). I thought this project removed cruft, not lower performance.

**Comment by lachs0r** [comment]
CPU usage depends on a lot of factors (e.g. the video output, which has a different default in mpv). Memory usage also does. For example, libass has a glyph cache in memory that can grow to a certain size, and is used to render the OSC.

Closing for pointless troll issue.
