### ISSUE TITLE
Asynchronous playlist entry expansion

### ISSUE THREAD

**Issue by jdoe0** [mpv-player/mpv#2342]
Playlist entries that can be expanded (eg. directories and nested playlists) are currently expanded into individual files upon playing that entry. It might be better if playlist entries are expanded even if they are not the entry being played as it would provide a more presentable playlist for client API users.

For example, consider the following directory structure:

```
foo
├── bar
│   ├── a.opus
│   └── b.opus
└── baz
    ├── c.opus
    └── d.opus
```

Opening the directory `foo` with mpv yields the following playlist:

```
a.opus
b.opus
baz
```

It might be better to asynchronously (since expanding `baz` can take a long time if it were a network mount point or an online playlist) expand `baz` while `a.opus` and `b.opus` are playing, which would yield the following playlist:

```
a.opus
b.opus
c.opus
d.opus
```

**Comment by wm4** [comment]
Seems rather unlikely that this will ever get implemented. Prefetching playlist entries? Maybe. But scraping the playlist to look for entries to expand? Unlikely.

**Comment by kevmitch** [comment]
seems to already do this now.

**Comment by wm4** [comment]
There's an option to prefetch the next playlist entry now, but there's still no async expansion.

**Comment by kevmitch** [comment]
The example provided now works as requested. I can't seem to get ${playlist} to show an unexpanded list regardless of depth or number. Are you just saying it might take a long time before playback starts now because this happens synchronously? Is asynchronous playlist expansion even on the horizon?

**Comment by wm4** [comment]
I think if a playlist entry is a directory, it's recursively opened (that is pretty synchronously, but behaves like opening a file, so the frontend and playloop is not "frozen", it simply waits until it's finished). That means if you pass multiple directories to the command line, I think only the first one is expanded.

Anyway I don't mind if this is closed. If someone really wants more, he can open a new issue.
