### ISSUE TITLE
Hwdec doesn't work on Windows 10

### ISSUE THREAD

**Issue by pavelxdd** [mpv-player/mpv#2345]
OS: Windows 10 Home x64
GPU: Nvidia GTX 650 Ti Boost

mpv --hwdec=dxva2-copy --vo=opengl video.mp4

I get this error in console:
> [dxva2] Failed to create Direct3D device
> Could not open codec.

This happens on builds 2015-09-23 and 2015-09-03
Build 2015-08-27 doesn't have this error.

Also, --vo=direct3d works fine as well, I get this error only with --vo=opengl

**Comment by pavelxdd** [comment]
After removing 
> fullscreen=yes
from mpv.conf I don't get this error anymore.

It's still a bug though.

**Comment by wm4** [comment]
Sounds hard to fix.

**Comment by pavelxdd** [comment]
I don't have this issue anymore on mpv git-9163bdc
Everything is working fine.
