### ISSUE TITLE
MPV ignores scroll wheel remapping in X11

### ISSUE THREAD

**Issue by RX14** [mpv-player/mpv#2346]
I am using linux with X11 and `mpv` seems to ignore the following mappings in my `~/.config/mpv/input.conf`:

```
AXIS_UP ignore
AXIS_DOWN ignore
AXIS_LEFT ignore
AXIS_RIGHT ignore
```

`xev` reports this when scrolling down:
```
ButtonPress event, serial 32, synthetic NO, window 0x3200001,
    root 0x31b, subw 0x0, time 12444118, (645,122), root:(647,1125),
    state 0x10, button 5, same_screen YES

ButtonRelease event, serial 32, synthetic NO, window 0x3200001,
    root 0x31b, subw 0x0, time 12444118, (645,122), root:(647,1125),
    state 0x1010, button 5, same_screen YES
```

This is getting really annoying as I accidentally scroll stuff...

**Comment by RX14** [comment]
Oops, forgot to state my version:

```
mpv 0.11.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Thu Sep 24 16:26:58 BST 2015
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8

```

**Comment by kevinlekiller** [comment]
Do you mean the mouse scroll wheel?
It's `MOUSE_BTN3` / `MOUSE_BTN4` for me.
Might depend on the device/mouse.
You can run `mpv --input-test --force-window --idle` to double check.

**Comment by RX14** [comment]
Thanks! Seems a bit strange they are different between platforms though.

**Comment by kevinlekiller** [comment]
Yeah, I have the same issue with `MOUSE_BTN7` / `MOUSE_BTN8`, on linux it's back/forward, on windows it's the scroll wheel left click / scroll wheel right click.
