### ISSUE TITLE
Pressing space cannot toggle pause/play if the current input method is in full-width mode

### ISSUE THREAD

**Issue by iawaknahc** [mpv-player/mpv#2349]
OS: Windows 10 Home 64bit

If the current input method (e.g. Cangjie, Japanese) is in full-width mode, pressing space cannot toggle pause/play.

I expect the key code should be recognized instead of the actual character being entered.

**Comment by ChrisK2** [comment]
does adding (note the leading spaces)
```
　 cycle pause
```
to your input.conf fix it?

**Comment by iawaknahc** [comment]
No.

**Comment by wm4** [comment]
What does --input-test show?

**Comment by iawaknahc** [comment]
This is the OSD message when pressing space in full-width input mode.
<img width="505" alt="full-width" src="https://cloud.githubusercontent.com/assets/6625665/10129086/e4949198-65ec-11e5-9b79-c259fde5a6bd.png">

And this is OSD message when pressing space in half-width input mode.
<img width="516" alt="half-width" src="https://cloud.githubusercontent.com/assets/6625665/10129092/e8ab4e70-65ec-11e5-8cab-78fb117413a7.png">

**Comment by Flat** [comment]
Adding
````
0x3000 cycle pause
````
to your input.conf will fix it. The full-width space is called an ideographic space and 0x3000 is the Unicode for that character.

**Comment by wm4** [comment]
Nice find. I guess we should add a key name for this.

**Comment by wm4** [comment]
The next windows build (whenever it comes) should understand ``HALF_SPACE`` as key name for this.

**Comment by Flat** [comment]
Shouldn't it be ```FULL_SPACE``` as it's a full-width character?

**Comment by wm4** [comment]
OK, I renamed it to ``IDEOGRAPHIC_SPACE``.
