### ISSUE TITLE
mpv crashes gnome shell

### ISSUE THREAD

**Issue by abc-mikey** [mpv-player/mpv#2350]
Hello, 

Running mpv in gnome shell causes gnome shell to crash when accessing the activities overlay. It happens every time with my setup. 

Name        : gnome-shell
Arch        : x86_64
Epoch       : 0
Version     : 3.16.3
Release     : 1.fc22
Size        : 9.2 M
Repo        : @System
From repo   : updates

Name        : mpv
Arch        : x86_64
Epoch       : 0
Version     : 0.9.2
Release     : 2.fc22
Size        : 1.7 M
Repo        : @System
From repo   : rpmfusion-free

As you can see I am running gnome shell 3.16. I have found a discussion of a similar sounding issue relating to gnome 3.14: https://bugzilla.gnome.org/show_bug.cgi?id=755490

The exact details don't mean much to me, I am wondering if it is something you are aware of and if there is any action you can take at you end, as they seem to imply in the discussion. Also I wonder if this is in fact the same issue that I am seeing in gnome 3.16, as in my issue mpv does not appear to crash, it is gnome shell that crashes making every window disappear. When I restart it all the windows reappear including mpv which is still running. However it restarts in an unstable state and completely crashes out.

**Comment by kevinlekiller** [comment]
Have you tried a later release of mpv? 0.9.2 is a almost half a year old.

**Comment by wm4** [comment]
Unless mpv is doing something really unusual and strange that could be avoidable, I'm afraid mpv can't do anything about this. Gnome should fix their code. If a normal user program can crash it, it's definitely their bug.

Why not use the native mpv wayland backend?

**Comment by abc-mikey** [comment]
Hi, 

I don't know enough about what the people on that bug report are saying to be able to say exactly, but it was my interpretation that they were indicating that there may be (have been) something fairly unusual about mpv's behavior. Perhaps it's worth reaching out to them for clarification.

That said I no longer think that is the issue I am seeing with my crash. I have just discovered that the crash is only happening with one file - at least that I have found so far. I'm not sure what is special about this file that is causing an issue but I am seeing that there are some issues with it's name as it contains some strange characters that xprop identifies as bad utf8 characters, so it may have something to do with them.

**Comment by wm4** [comment]
mpv will send invalid UTF-8 to the server of the file uses invalid UTF-8 (or actually, more likely, just some 8 bit encoding). But it'd still be a bug of the other software if it crashes on that.

(In theory, we could recode it to valid UTF-8 by replacing invalid codepoints with replacement characters, but what's the point?)

**Comment by abc-mikey** [comment]
Yeh, if it's the UTF8 issue then it's almost certainly a Gnome bug, but honestly I'm just guessing that that is the issue. Won't know until I've managed to reproduce it or stop it from happening. I might try changing the meta data and see if that resolves it. That would let me know if it's the title.

**Comment by abc-mikey** [comment]
I can confirm that it's the metadata that is causing the problem. Changing the title so that it doesn't have bad characters in it prevents the crashes. 

I'm not sure if you want to consider putting any checks your end that you are putting semi-sane characters in the window title. I will open a bug with gnome as well. Unfortunately I haven't been able to isolate the crash in a properly reproducible way as I can't get ffmpeg to write as broken a set of bytes as I am seeing in the file I am having issue with.

**Comment by jamdox** [comment]
monthly reminder that the wayland backend doesn't work on gnome-wayland

a lot of stuff doesn't work with 3.18, but the wayland thing has been the case for a while

**Comment by neheb** [comment]
I ran into a crash with it earlier. Interestingly enough, no crash with vo=wayland but does crash with vo=opengl.

**Comment by ricardomv** [comment]
This is fixed in 3.18.2 on a gnome-wayland session
