### ISSUE TITLE
mpv.com without console window 

### ISSUE THREAD

**Issue by gen2brain** [mpv-player/mpv#2352]
I used before mpv.exe from python subprocess and I could pass options and that worked, without console window. It looks like mpv.exe is now a GUI app and I cannot pass options anymore? It does work when I use mpv.com with same options but then console window is shown.

Can I use somehow mpv.exe or mpv.com but without opening that console window?

**Comment by wm4** [comment]
I have no idea, but this stuff was changed ages ago.

You should use libmpv to avoid such problems, too.

**Comment by gen2brain** [comment]
Can I have osc if I use libmpv to play video?

**Comment by avih** [comment]
`mpv.exe` is indeed a GUI app but otherwise it still accepts cli args and uses them correctly (just tested from `cmd.exe` windows console). `mpv.com` is used to launch it with terminal support.

What cli options are you passing which don't work?

**Comment by gen2brain** [comment]
mpv.exe --fullscreen --quiet --no-ytdl --title "Some Title" --force-media-title "Some Title" URL

This works with mpv.com , but I cannot see what is the error when mpv.exe is used.

**Comment by avih** [comment]
> mpv.exe --fullscreen --quiet --no-ytdl --title "Some Title" --force-media-title "Some Title" URL

I just tried it from windows console with my own URL and it worked. Did you try it from windows console too?

Also, you can add `--force-window=immediate`. Without it, the window (fullscreen) will appear only once mpv has enough data to start playing the video. Maybe the network is a bit slow?

**Comment by gen2brain** [comment]
Network is a bit slow, yes. Maybe it is related with how subprocess builds command from list on windows. 
Thanks for confirming mpv.exe still accepts options.

**Comment by wm4** [comment]
>Can I have osc if I use libmpv to play video?

Yes, it's just disabled by default when using libmpv.
