### ISSUE TITLE
lavfi/ladspa syntax

### ISSUE THREAD

**Issue by Bergfried** [mpv-player/mpv#2354]
Neither `man mpv` nor #2286 nor <https://ffmpeg.org/ffmpeg-filters.html#Examples-13> could tell me how to properly insert LADSPA filters in mpv 0.11. I tried virtually anything, to no avail. My last try in bash:

    $ mpv '--af=lavfi=[ladspa=/usr/lib/ladspa/mbeq_1197.so:mbeq:-4.0,-4.2,-6.6,-7.3,-6.7,-6.7,-6.8,-6.9,-7.0,-7.0,-6.8,-6.4,-5.4,-5.1,0.0]' *
    Playing: asdf.mkv
     (+) Video --vid=1 (*) (h264)
     (+) Audio --aid=1 (*) (aac)
    [ffmpeg] Parsed_ladspa_0: Invalid syntax.
    [ffmpeg] Error initializing filter 'ladspa' with args '/usr/lib/ladspa/mbeq_1197.so:mbeq:-4.0'
    [lavfi] Can't configure libavfilter graph.
    Reinitialization did not work, audio filter 'lavfi' returned error code -2
    Audio filter chain:
      [in] 48000Hz stereo 2ch floatp
      [lavfi] 0Hz empty 0ch ?? <-
      [out] 0Hz empty 0ch ??
      [ao] 0Hz empty 0ch ??
    Could not create audio filter chain.
    Error at audio filter chain pre-init!
    [ffmpeg] Parsed_ladspa_0: Invalid syntax.
    [ffmpeg] Error initializing filter 'ladspa' with args '/usr/lib/ladspa/mbeq_1197.so:mbeq:-4.0'
    [lavfi] Can't configure libavfilter graph.
    [lavfi] Can't recreate libavfilter filter after a seek reset.
    Audio: no audio
    VO: [opengl] 1280x720 yuv420p

I guess I got the syntax wrong. Any help is appreciated.

**Comment by richardpl** [comment]
Use ¦ instead ,

**Comment by Bergfried** [comment]
Thank you for the quick reply. If I replace ',' with '|' in the filter argument string, I get this:

    $ mpv '--af=lavfi=[ladspa=/usr/lib/ladspa/mbeq_1197.so:mbeq:-4.0|-4.2|-6.6|-7.3|-6.7|-6.7|-6.8|-6.9|-7.0|-7.0|-6.8|-6.4|-5.4|-5.1|0.0]' *
    Playing: asdf.mkv
     (+) Video --vid=1 (*) (h264)
     (+) Audio --aid=1 (*) (aac)
    [ffmpeg] Parsed_ladspa_0: Invalid syntax.
    [ffmpeg] Error initializing filter 'ladspa' with args '/usr/lib/ladspa/mbeq_1197.so:mbeq:-4.0|-4.2|-6.6|-7.3|-6.7|-6.7|-6.8|-6.9|-7.0|-7.0|-6.8|-6.4|-5.4|-5.1|0.0'
    [lavfi] Can't configure libavfilter graph.
    Reinitialization did not work, audio filter 'lavfi' returned error code -2
    Audio filter chain:
      [in] 48000Hz stereo 2ch floatp
      [lavfi] 0Hz empty 0ch ?? <-
      [out] 0Hz empty 0ch ??
      [ao] 0Hz empty 0ch ??
    Could not create audio filter chain.
    Error at audio filter chain pre-init!
    [ffmpeg] Parsed_ladspa_0: Invalid syntax.
    [ffmpeg] Error initializing filter 'ladspa' with args '/usr/lib/ladspa/mbeq_1197.so:mbeq:-4.0|-4.2|-6.6|-7.3|-6.7|-6.7|-6.8|-6.9|-7.0|-7.0|-6.8|-6.4|-5.4|-5.1|0.0'
    [lavfi] Can't configure libavfilter graph.
    [lavfi] Can't recreate libavfilter filter after a seek reset.
    Audio: no audio
    VO: [opengl] 1280x720 yuv420p

**Comment by richardpl** [comment]
Your ffmpeg is too old , upgrade to master or use longer syntax: c1...

**Comment by Bergfried** [comment]
Thank you, again. When I try to run mpv like

    $ mpv '--af=lavfi=[ladspa=/usr/lib/ladspa/mbeq_1197.so:mbeq:c=c0=0|c1=0|c2=0|c3=0|c4=0|c5=-70|c6=-70|c7=-70|c8=-70|c9=-70|c10=-70|c11=-70|c12=-70|c13=-70|c14=-70]' *

then I don't get any errors anymore. However, the audio output at least for mbeq is really strange, it sounds like the filter only affects the left channel but the right channel is, well, *different* (hard to describe, maybe something like an inverted version of itself instead of a properly filtered version). This also happens if I don't set any of the controls manually, i.e.

    $ mpv '--af=lavfi=[ladspa=/usr/lib/ladspa/mbeq_1197.so:mbeq]' *

results in a strange stereo channel effect when it is supposed to do nothing. Using LADSPA directly in mpv 0.10 always worked correctly for me.

ffmpeg version:

    ffmpeg library versions:
       libavutil       54.31.100
       libavcodec      56.60.100
       libavformat     56.40.101
       libswscale      3.1.101
       libavfilter     5.40.101
       libswresample   1.2.101
    ffmpeg version: 2.8

**Comment by richardpl** [comment]
Your ffmpeg version is just old. In latest one this bug have been fixed.
