### ISSUE TITLE
Why fonts will be fallen back to Helvetica by fontselect?

### ISSUE THREAD

**Issue by meritozh** [mpv-player/mpv#2356]
The version of my mpv is v0.11.0. I know libass use CoreText to find font now. But in my Mac:
![image](https://cloud.githubusercontent.com/assets/7543300/10138908/259c8646-6633-11e5-81fc-8424505d1e76.png)
I have installed those fonts follow the .ass file. Am i must install those in system font folder instead of user font folder?

**Comment by wm4** [comment]
mpv currently doesn't read fonts embedded in .ass files anymore, if that's what you mean.

**Comment by meritozh** [comment]
@wm4 What's my meaning is that i have installed all fonts which this .ass file will use by its style tag. But it seems that it will be fallen back to default font settings such as Helvetica. Why it won't select **华文楷体** or others?

**Comment by wm4** [comment]
First, update to latest libass git, and try again. I think there was a bug in the fallback code which was fixed recently.

**Comment by pigoz** [comment]
@meritozh had to tell what's going wrong. Does it work if the fonts are embedded in the mkv file? Does the font family name requested in the ass file match that of the font exactly? (coretext is a it picky with that)

**Comment by meritozh** [comment]
@pigoz i can't find a .mkv file which has embedded a font. But maybe i find the reason. If the font name in .ass file is just the name of .ttf file, CoreText can't recognize it. I must make .ass file use font name which shows in Font Book. Is there any other way to let CoreText recognize it by name of font file?

**Comment by pigoz** [comment]
Well no. The font is always matched by family name. I think this is the case even when using fontconfig.

**Comment by meritozh** [comment]
@pigoz Yes. This .ass file were created by Aegisub in Windows. Now i hava a new problem below:
![image](https://cloud.githubusercontent.com/assets/7543300/10158990/08866460-66c8-11e5-8e85-4659aaf7aa11.png)
I have tried "Kaiti SC Black" "Kaiti SC" "STKaiti" by modifing .ass file. But it doesn't work.
There had a same problem that i search in Apple Mailing List:
[Invalid amor - what does this mean?](https://lists.apple.com/archives/cocoa-dev/2015/May/msg00323.html)
