### ISSUE TITLE
Man comments regarding vaapi, opengl, mesa

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#2358]
"The vaapi mode, if used with --vo=opengl, requires Mesa 11 and most likely works with Intel GPUs only"
Seems to works fine here with mesa 10.5.x, maybe I don't understand the word mode?

**Comment by lachs0r** [comment]
I think this means `--hwdec=vaapi` with the EGL backend as opposed to forcing the GLX backend or using `--hwdec=vaapi-copy`.

**Comment by mc4man** [comment]
Here both mesa 10 & mesa 11 both work generally the same with simple config of 
-hwdec=auto -vo=opengl-hq 
the former is OpenGL backend 'x11', the later OpenGL backend 'x11egl'
So 'vaapi mode'  doesn't require mesa 11 unless it's something other than 'vaapi'

**Comment by wm4** [comment]
Different in git master.

**Comment by mc4man** [comment]
That's what I was using on both mesa's - 
~$ mpv
mpv git-7394523 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Wed Sep 30 01:15:19 UTC 2015
ffmpeg library versions:
   libavutil       55.2.100
   libavcodec      57.3.100
   libavformat     57.2.100
   libswscale      4.0.100
   libavfilter     6.8.100
   libswresample   2.0.100
ffmpeg version: N-75493-g0c7ceb1

If it's -vo=opengl then on mesa 11 it's - using VAAPI EGL interop, if using opengl-hq it's x11egl
On mesa 10 both -vo's produce the same, x11
The statement in the man implies vaapi needs mesa 11 as I see no entry or mention anywhere that differentiates  vaapi mode from vaapi.

**Comment by wm4** [comment]
I have no idea what you're trying to say.

**Comment by mc4man** [comment]
Forget it, not that important  but your man states - vaapi mode, if used with --vo=opengl, requires Mesa 11
Obviously that is either incorrect as vaapi (hwdec) & opengl (vo) work fine with mesa 10 or  "vaapi mode" is something different than vaapi (hwdec

**Comment by wm4** [comment]
I still don't get you, it's all fucking explained, and correct.
