### ISSUE TITLE
How to display only file tags while playing a stream?

### ISSUE THREAD

**Issue by octos** [mpv-player/mpv#2360]
I'd like to output the file tags (icy-title) of the streams I play, and hide everything else. Is this possible?

**Comment by wm4** [comment]
I don't think there's a way currently. You _could_ use --very-quiet, and then use a Lua script to print stuff to stdout. I'll look if there's another way to achieve this.

**Comment by octos** [comment]
@wm4 How do I use this new option?

**Comment by wm4** [comment]
You can disable most log prefixes with ``--msg-level``, and explicitly enable the new one. Check the prefixes with ``--msg-module``.

**Comment by octos** [comment]
@wm4 But how can I ḍisplay `cplayer:  icy-title:`, while hiding all other `cplayer` prefixes?

**Comment by KebabLord** [comment]
use `mpv <file> --display-tags=icy-title`
to see the available tags use `mpv <file> --display-tags=*`
