### ISSUE TITLE
no matching function for call to `mix(vec4, vec4, bvec4)'

### ISSUE THREAD

**Issue by bentley** [mpv-player/mpv#2362]
A change in 0.11.0 causes shader compilation errors when I use opengl-hq.

Platform is OpenBSD -current, amd64, with radeon drivers (Radeon HD 5450). Looks like the erroring line in question is in `pass_sample_deband()`.

    $ mpv foo.mp4
    Playing: foo.mp4
     (+) Video --vid=1 (*) (h264)
     (+) Audio --aid=1 --alang=und (*) (aac)
    [vo/opengl-hq/x11] X11 error: GLXBadFBConfig
    [vo/opengl-hq] Could not create GL3 context. Retrying with legacy context.
    [vo/opengl-hq] Disabling scaler #0 (float tex. missing).
    [vo/opengl-hq] Disabling scaler #1 (float tex. missing).
    [vo/opengl-hq] Disabling scaler #2 (float tex. missing).
    [vo/opengl-hq] Disabling linear/sigmoid scaling (GLSL version too old).
    AO: [sndio] 44100Hz stereo 2ch s16
    VO: [opengl-hq] 1280x720 yuv420p
    [vo/opengl-hq] fragment shader source:
    [vo/opengl-hq] [  1] #version 120
    [vo/opengl-hq] [  2] #define RG rg
    [vo/opengl-hq] [  3] #define texture texture2D
    [vo/opengl-hq] [  4] varying vec2 texcoord0;
    [vo/opengl-hq] [  5] varying vec2 texcoord1;
    [vo/opengl-hq] [  6] varying vec2 texcoord2;
    [vo/opengl-hq] [  7] varying vec2 texcoord3;
    [vo/opengl-hq] [  8] varying vec2 texcoord4;
    [vo/opengl-hq] [  9] varying vec2 texcoord5;
    [vo/opengl-hq] [ 10] uniform float random;
    [vo/opengl-hq] [ 11] uniform sampler2D texture1;
    [vo/opengl-hq] [ 12] uniform vec2 texture_size1;
    [vo/opengl-hq] [ 13] // header
    [vo/opengl-hq] [ 14] float mod289(float x) { return x - floor(x / 289.0) * 289.0; }
    [vo/opengl-hq] [ 15] float permute(float x) { return mod289((34.0*x + 1.0) * x); }
    [vo/opengl-hq] [ 16] float rand(float x) { return fract(x / 41.0); }
    [vo/opengl-hq] [ 17] vec4 average(sampler2D tex, vec2 pos, float range, inout float h) {float dist = rand(h) * range; h = permute(h);
    [vo/opengl-hq] [ 18] float dir = rand(h) * 6.2831853; h = permute(h);
    [vo/opengl-hq] [ 19] vec2 pt = dist / vec2(1280.000000, 720.000000);
    [vo/opengl-hq] [ 20] vec2 o = vec2(cos(dir), sin(dir));
    [vo/opengl-hq] [ 21] vec4 ref[4];
    [vo/opengl-hq] [ 22] ref[0] = texture(tex, pos + pt * vec2( o.x, o.y));
    [vo/opengl-hq] [ 23] ref[1] = texture(tex, pos + pt * vec2(-o.y, o.x));
    [vo/opengl-hq] [ 24] ref[2] = texture(tex, pos + pt * vec2(-o.x, -o.y));
    [vo/opengl-hq] [ 25] ref[3] = texture(tex, pos + pt * vec2( o.y, -o.x));
    [vo/opengl-hq] [ 26] return 1.000000 * (ref[0] + ref[1] + ref[2] + ref[3])/4.0;
    [vo/opengl-hq] [ 27] }
    [vo/opengl-hq] [ 28] 
    [vo/opengl-hq] [ 29] // body
    [vo/opengl-hq] [ 30] void main() {
    [vo/opengl-hq] [ 31] // debanding (tex 1)
    [vo/opengl-hq] [ 32] #undef tex
    [vo/opengl-hq] [ 33] #define tex texture1
    [vo/opengl-hq] [ 34] vec2 pos = texcoord1;
    [vo/opengl-hq] [ 35] vec2 size = texture_size1;
    [vo/opengl-hq] [ 36] vec2 pt = vec2(1.0) / size;
    [vo/opengl-hq] [ 37] vec3 _m = vec3(pos, random) + vec3(1.0);
    [vo/opengl-hq] [ 38] float h = permute(permute(permute(_m.x)+_m.y)+_m.z);
    [vo/opengl-hq] [ 39] vec4 color = 1.000000 * texture(tex, pos);
    [vo/opengl-hq] [ 40] vec4 avg, diff;
    [vo/opengl-hq] [ 41] avg = average(tex, pos, 8.000000, h);
    [vo/opengl-hq] [ 42] diff = abs(color - avg);
    [vo/opengl-hq] [ 43] color = mix(avg, color, greaterThan(diff, vec4(0.003906)));
    [vo/opengl-hq] [ 44] avg = average(tex, pos, 16.000000, h);
    [vo/opengl-hq] [ 45] diff = abs(color - avg);
    [vo/opengl-hq] [ 46] color = mix(avg, color, greaterThan(diff, vec4(0.001953)));
    [vo/opengl-hq] [ 47] avg = average(tex, pos, 24.000000, h);
    [vo/opengl-hq] [ 48] diff = abs(color - avg);
    [vo/opengl-hq] [ 49] color = mix(avg, color, greaterThan(diff, vec4(0.001302)));
    [vo/opengl-hq] [ 50] avg = average(tex, pos, 32.000000, h);
    [vo/opengl-hq] [ 51] diff = abs(color - avg);
    [vo/opengl-hq] [ 52] color = mix(avg, color, greaterThan(diff, vec4(0.000977)));
    [vo/opengl-hq] [ 53] vec3 noise;
    [vo/opengl-hq] [ 54] noise.x = rand(h); h = permute(h);
    [vo/opengl-hq] [ 55] noise.y = rand(h); h = permute(h);
    [vo/opengl-hq] [ 56] noise.z = rand(h); h = permute(h);
    [vo/opengl-hq] [ 57] color.xyz += 0.005859 * (noise - vec3(0.5));
    [vo/opengl-hq] [ 58] color.zw = vec2(0.0, 1.0);
    [vo/opengl-hq] [ 59] gl_FragColor = color;
    [vo/opengl-hq] [ 60] }
    [vo/opengl-hq] fragment shader compile log (status=0):
    [vo/opengl-hq] 0:43(9): error: no matching function for call to `mix(vec4, vec4, bvec4)'; candidates are:
    [vo/opengl-hq] 0:43(9): error:    float mix(float, float, float)
    [vo/opengl-hq] 0:43(9): error:    vec2 mix(vec2, vec2, float)
    [vo/opengl-hq] 0:43(9): error:    vec3 mix(vec3, vec3, float)
    [vo/opengl-hq] 0:43(9): error:    vec4 mix(vec4, vec4, float)
    [vo/opengl-hq] 0:43(9): error:    vec2 mix(vec2, vec2, vec2)
    [vo/opengl-hq] 0:43(9): error:    vec3 mix(vec3, vec3, vec3)
    [vo/opengl-hq] 0:43(9): error:    vec4 mix(vec4, vec4, vec4)
    [vo/opengl-hq] 0:46(9): error: no matching function for call to `mix(vec4, vec4, bvec4)'; candidates are:
    [vo/opengl-hq] 0:46(9): error:    float mix(float, float, float)
    [vo/opengl-hq] 0:46(9): error:    vec2 mix(vec2, vec2, float)
    [vo/opengl-hq] 0:46(9): error:    vec3 mix(vec3, vec3, float)
    [vo/opengl-hq] 0:46(9): error:    vec4 mix(vec4, vec4, float)
    [vo/opengl-hq] 0:46(9): error:    vec2 mix(vec2, vec2, vec2)
    [vo/opengl-hq] 0:46(9): error:    vec3 mix(vec3, vec3, vec3)
    [vo/opengl-hq] 0:46(9): error:    vec4 mix(vec4, vec4, vec4)
    [vo/opengl-hq] 0:49(9): error: no matching function for call to `mix(vec4, vec4, bvec4)'; candidates are:
    [vo/opengl-hq] 0:49(9): error:    float mix(float, float, float)
    [vo/opengl-hq] 0:49(9): error:    vec2 mix(vec2, vec2, float)
    [vo/opengl-hq] 0:49(9): error:    vec3 mix(vec3, vec3, float)
    [vo/opengl-hq] 0:49(9): error:    vec4 mix(vec4, vec4, float)
    [vo/opengl-hq] 0:49(9): error:    vec2 mix(vec2, vec2, vec2)
    [vo/opengl-hq] 0:49(9): error:    vec3 mix(vec3, vec3, vec3)
    [vo/opengl-hq] 0:49(9): error:    vec4 mix(vec4, vec4, vec4)
    [vo/opengl-hq] 0:52(9): error: no matching function for call to `mix(vec4, vec4, bvec4)'; candidates are:
    [vo/opengl-hq] 0:52(9): error:    float mix(float, float, float)
    [vo/opengl-hq] 0:52(9): error:    vec2 mix(vec2, vec2, float)
    [vo/opengl-hq] 0:52(9): error:    vec3 mix(vec3, vec3, float)
    [vo/opengl-hq] 0:52(9): error:    vec4 mix(vec4, vec4, float)
    [vo/opengl-hq] 0:52(9): error:    vec2 mix(vec2, vec2, vec2)
    [vo/opengl-hq] 0:52(9): error:    vec3 mix(vec3, vec3, vec3)
    [vo/opengl-hq] 0:52(9): error:    vec4 mix(vec4, vec4, vec4)
    [vo/opengl-hq] 
    [vo/opengl-hq] shader link log (status=0): error: linking with uncompiled shader
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    [vo/opengl-hq] fragment shader source:
    [vo/opengl-hq] [  1] #version 120
    [vo/opengl-hq] [  2] #define RG rg
    [vo/opengl-hq] [  3] #define texture texture2D
    [vo/opengl-hq] [  4] varying vec2 texcoord0;
    [vo/opengl-hq] [  5] varying vec2 texcoord1;
    [vo/opengl-hq] [  6] varying vec2 texcoord2;
    [vo/opengl-hq] [  7] varying vec2 texcoord3;
    [vo/opengl-hq] [  8] varying vec2 texcoord4;
    [vo/opengl-hq] [  9] varying vec2 texcoord5;
    [vo/opengl-hq] [ 10] uniform float random;
    [vo/opengl-hq] [ 11] uniform mat3 colormatrix;
    [vo/opengl-hq] [ 12] uniform vec3 colormatrix_c;
    [vo/opengl-hq] [ 13] uniform sampler2D texture0;
    [vo/opengl-hq] [ 14] uniform vec2 texture_size0;
    [vo/opengl-hq] [ 15] uniform sampler2D texture1;
    [vo/opengl-hq] [ 16] uniform vec2 texture_size1;
    [vo/opengl-hq] [ 17] // header
    [vo/opengl-hq] [ 18] float mod289(float x) { return x - floor(x / 289.0) * 289.0; }
    [vo/opengl-hq] [ 19] float permute(float x) { return mod289((34.0*x + 1.0) * x); }
    [vo/opengl-hq] [ 20] float rand(float x) { return fract(x / 41.0); }
    [vo/opengl-hq] [ 21] vec4 average(sampler2D tex, vec2 pos, float range, inout float h) {float dist = rand(h) * range; h = permute(h);
    [vo/opengl-hq] [ 22] float dir = rand(h) * 6.2831853; h = permute(h);
    [vo/opengl-hq] [ 23] vec2 pt = dist / vec2(1280.000000, 720.000000);
    [vo/opengl-hq] [ 24] vec2 o = vec2(cos(dir), sin(dir));
    [vo/opengl-hq] [ 25] vec4 ref[4];
    [vo/opengl-hq] [ 26] ref[0] = texture(tex, pos + pt * vec2( o.x, o.y));
    [vo/opengl-hq] [ 27] ref[1] = texture(tex, pos + pt * vec2(-o.y, o.x));
    [vo/opengl-hq] [ 28] ref[2] = texture(tex, pos + pt * vec2(-o.x, -o.y));
    [vo/opengl-hq] [ 29] ref[3] = texture(tex, pos + pt * vec2( o.y, -o.x));
    [vo/opengl-hq] [ 30] return 1.000000 * (ref[0] + ref[1] + ref[2] + ref[3])/4.0;
    [vo/opengl-hq] [ 31] }
    [vo/opengl-hq] [ 32] 
    [vo/opengl-hq] [ 33] // body
    [vo/opengl-hq] [ 34] void main() {
    [vo/opengl-hq] [ 35] // chroma scaling
    [vo/opengl-hq] [ 36] #undef tex
    [vo/opengl-hq] [ 37] #define tex texture1
    [vo/opengl-hq] [ 38] vec2 pos = texcoord1;
    [vo/opengl-hq] [ 39] vec2 size = texture_size1;
    [vo/opengl-hq] [ 40] vec2 pt = vec2(1.0) / size;
    [vo/opengl-hq] [ 41] vec4 color = texture(tex, pos);
    [vo/opengl-hq] [ 42] color.a = 1.0;
    [vo/opengl-hq] [ 43] vec2 chroma = color.xy;
    [vo/opengl-hq] [ 44] vec4 main;
    [vo/opengl-hq] [ 45] {
    [vo/opengl-hq] [ 46] // debanding (tex 0)
    [vo/opengl-hq] [ 47] #undef tex
    [vo/opengl-hq] [ 48] #define tex texture0
    [vo/opengl-hq] [ 49] vec2 pos = texcoord0;
    [vo/opengl-hq] [ 50] vec2 size = texture_size0;
    [vo/opengl-hq] [ 51] vec2 pt = vec2(1.0) / size;
    [vo/opengl-hq] [ 52] vec3 _m = vec3(pos, random) + vec3(1.0);
    [vo/opengl-hq] [ 53] float h = permute(permute(permute(_m.x)+_m.y)+_m.z);
    [vo/opengl-hq] [ 54] vec4 color = 1.000000 * texture(tex, pos);
    [vo/opengl-hq] [ 55] vec4 avg, diff;
    [vo/opengl-hq] [ 56] avg = average(tex, pos, 8.000000, h);
    [vo/opengl-hq] [ 57] diff = abs(color - avg);
    [vo/opengl-hq] [ 58] color = mix(avg, color, greaterThan(diff, vec4(0.003906)));
    [vo/opengl-hq] [ 59] avg = average(tex, pos, 16.000000, h);
    [vo/opengl-hq] [ 60] diff = abs(color - avg);
    [vo/opengl-hq] [ 61] color = mix(avg, color, greaterThan(diff, vec4(0.001953)));
    [vo/opengl-hq] [ 62] avg = average(tex, pos, 24.000000, h);
    [vo/opengl-hq] [ 63] diff = abs(color - avg);
    [vo/opengl-hq] [ 64] color = mix(avg, color, greaterThan(diff, vec4(0.001302)));
    [vo/opengl-hq] [ 65] avg = average(tex, pos, 32.000000, h);
    [vo/opengl-hq] [ 66] diff = abs(color - avg);
    [vo/opengl-hq] [ 67] color = mix(avg, color, greaterThan(diff, vec4(0.000977)));
    [vo/opengl-hq] [ 68] vec3 noise;
    [vo/opengl-hq] [ 69] noise.x = rand(h); h = permute(h);
    [vo/opengl-hq] [ 70] noise.y = rand(h); h = permute(h);
    [vo/opengl-hq] [ 71] noise.z = rand(h); h = permute(h);
    [vo/opengl-hq] [ 72] color.xyz += 0.005859 * (noise - vec3(0.5));
    [vo/opengl-hq] [ 73] main = color;
    [vo/opengl-hq] [ 74] }
    [vo/opengl-hq] [ 75] color = main;
    [vo/opengl-hq] [ 76] color.yz = chroma;
    [vo/opengl-hq] [ 77] // color conversion
    [vo/opengl-hq] [ 78] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
    [vo/opengl-hq] [ 79] color.a = 1.0;
    [vo/opengl-hq] [ 80] // scaler pre-conversion
    [vo/opengl-hq] [ 81] // main scaling
    [vo/opengl-hq] [ 82] gl_FragColor = color;
    [vo/opengl-hq] [ 83] }
    [vo/opengl-hq] fragment shader compile log (status=0):
    [vo/opengl-hq] 0:58(9): error: no matching function for call to `mix(vec4, vec4, bvec4)'; candidates are:
    [vo/opengl-hq] 0:58(9): error:    float mix(float, float, float)
    [vo/opengl-hq] 0:58(9): error:    vec2 mix(vec2, vec2, float)
    [vo/opengl-hq] 0:58(9): error:    vec3 mix(vec3, vec3, float)
    [vo/opengl-hq] 0:58(9): error:    vec4 mix(vec4, vec4, float)
    [vo/opengl-hq] 0:58(9): error:    vec2 mix(vec2, vec2, vec2)
    [vo/opengl-hq] 0:58(9): error:    vec3 mix(vec3, vec3, vec3)
    [vo/opengl-hq] 0:58(9): error:    vec4 mix(vec4, vec4, vec4)
    [vo/opengl-hq] 0:61(9): error: no matching function for call to `mix(vec4, vec4, bvec4)'; candidates are:
    [vo/opengl-hq] 0:61(9): error:    float mix(float, float, float)
    [vo/opengl-hq] 0:61(9): error:    vec2 mix(vec2, vec2, float)
    [vo/opengl-hq] 0:61(9): error:    vec3 mix(vec3, vec3, float)
    [vo/opengl-hq] 0:61(9): error:    vec4 mix(vec4, vec4, float)
    [vo/opengl-hq] 0:61(9): error:    vec2 mix(vec2, vec2, vec2)
    [vo/opengl-hq] 0:61(9): error:    vec3 mix(vec3, vec3, vec3)
    [vo/opengl-hq] 0:61(9): error:    vec4 mix(vec4, vec4, vec4)
    [vo/opengl-hq] 0:64(9): error: no matching function for call to `mix(vec4, vec4, bvec4)'; candidates are:
    [vo/opengl-hq] 0:64(9): error:    float mix(float, float, float)
    [vo/opengl-hq] 0:64(9): error:    vec2 mix(vec2, vec2, float)
    [vo/opengl-hq] 0:64(9): error:    vec3 mix(vec3, vec3, float)
    [vo/opengl-hq] 0:64(9): error:    vec4 mix(vec4, vec4, float)
    [vo/opengl-hq] 0:64(9): error:    vec2 mix(vec2, vec2, vec2)
    [vo/opengl-hq] 0:64(9): error:    vec3 mix(vec3, vec3, vec3)
    [vo/opengl-hq] 0:64(9): error:    vec4 mix(vec4, vec4, vec4)
    [vo/opengl-hq] 0:67(9): error: no matching function for call to `mix(vec4, vec4, bvec4)'; candidates are:
    [vo/opengl-hq] 0:67(9): error:    float mix(float, float, float)
    [vo/opengl-hq] 0:67(9): error:    vec2 mix(vec2, vec2, float)
    [vo/opengl-hq] 0:67(9): error:    vec3 mix(vec3, vec3, float)
    [vo/opengl-hq] 0:67(9): error:    vec4 mix(vec4, vec4, float)
    [vo/opengl-hq] 0:67(9): error:    vec2 mix(vec2, vec2, vec2)
    [vo/opengl-hq] 0:67(9): error:    vec3 mix(vec3, vec3, vec3)
    [vo/opengl-hq] 0:67(9): error:    vec4 mix(vec4, vec4, vec4)
    [vo/opengl-hq] 
    [vo/opengl-hq] shader link log (status=0): error: linking with uncompiled shader
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    [vo/opengl-hq] dither setup: OpenGL error INVALID_VALUE.
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    AV: 00:00:00 / 00:07:27 (0%) A-V: -0.000
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    AV: 00:00:00 / 00:07:27 (0%) A-V: -0.000
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    AV: 00:00:00 / 00:07:27 (0%) A-V:  0.000
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    AV: 00:00:00 / 00:07:27 (0%) A-V:  0.000
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    [vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
    AV: 00:00:00 / 00:07:27 (0%) A-V: -0.000
    [ao/sndio] Blocking until remaining audio is played... (sndio design bug).

**Comment by dikei** [comment]
I have this issue as well. System is
    
    OS: Archlinux
    OpenGL vendor string: Intel Open Source Technology Center
    OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
    OpenGL version string: 2.1 Mesa 11.0.1
    OpenGL shading language version string: 1.20
