### ISSUE TITLE
libGL and OpenGL Errors

### ISSUE THREAD

**Issue by raeisi** [mpv-player/mpv#2363]
I am using MPV on Banana Pro and although the drivers are installed and pass the sunxi-mali test  and eventhough the 1080p videos are playing very well I get below errors while playing

# lsmod
Module                  Size  Used by
ap6210                614858  0 
sunxi_cedar_mod        10523  0 
mali_drm                3168  1 
drm                   227888  2 mali_drm
mali                  143909  0 
disp_ump                1045  0 
ump                    55022  4 mali,disp_ump

# nano ~/.mpv/config
fs=yes
index=default
ao=alsa
stop-screensaver=yes
#heartbeat-cmd="xscreensaver-command -deactivate &"
softvol=yes
softvol-max=600
af=volume=40
volume=30
hwdec=auto
hwdec-codecs=h264,vc1,wmv3,mpeg2video,mpeg4
deinterlace=auto

# mpv --force-rgba-osd-rendering -playlist <(find "$PWD" -type f) 
......
laying: /mnt/hdclub_taiwan_lantern_festival-DWEU.mkv
[stream] Video (+) --vid=1 (h264)
[stream] Audio (+) --aid=1 --alang=eng (*) (ac3)
libGL error: MESA-LOADER: malformed or no PCI ID
libGL error: unable to load driver: mali_drm_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: mali_drm
[vo/opengl] Missing OpenGL features: [NO_SW]
[vo/opengl] Rejecting suspected software OpenGL renderer.
[vo/opengl] OpenGL context creation failed!
[VDPAU SUNXI] VE version 0x1623 opened.
Trying to use hardware decoding.
AO: [alsa] 48000Hz stereo 2ch float
VO: [vdpau] 1920x1080 => 1920x1080 vdpau
[VDPAU SUNXI] Presentation time not supported
AV: 00:00:08 / 00:08:03 (1%) A-V:  0.378 D: 8

Should I be concerned about these errors or just ignore them?

**Comment by wm4** [comment]
What's your mpv version? It looks old.

The GL errors are because it tries vo_opengl first, but that fails. You can avoid them by putting ``vo=vdpau`` into your config file. I'm not surprised that you'd get broken OpenGL on this hw, and even if it works, it'll be useless for video.
