### ISSUE TITLE
HOME variable in config file

### ISSUE THREAD

**Issue by cranes-bill** [mpv-player/mpv#2368]
Hi,
First of all - thank you for your good work and sorry for my „excellent“ :flushed: English!
Just to inform - i think **MPV** do not handling properly with `$HOME` or `~/` variables in _input.conf_ file.
For example: for quick access to see the slave commands, i set the following:```
F1 run /usr/bin/xdg-open ~/.config/mpv/mpv.slave```, but when i hit **F1**, i have got this:
```gvfs-open: ~/.config/mpv/mpv.slave: error opening location: Error when getting information for file '/home/user/~/.config/mpv/mpv.slave': No such file or directory```
If i set the full path, it works as expected, as well as i run that command from the terminal, so i think the „problem“ is somewhere in **MPV** :innocent: ...
I am using  **MPV** just from few hours ago, so sorry if i have missed something!
Regards!

__*MPV a9ed9e329c; Linux*__

**Comment by wm4** [comment]
It doesn't because the ``run`` command just passes arguments unmodified to the process that is started. You can e.g. use ``F1 run sh -c "xdg-open ~/.config/..."`` to get shell behavior.

**Comment by cranes-bill** [comment]
Thank you for the instant answer!

**Comment by torontal7** [comment]
Why is this issue closed??? This is a real mpv bug: If you define a path in mpv conf file in the form `external-file=~/.config/mpv/mpv.webp`, mpv says that the file does not exist:

`Can not open external file ~/.config/mpv/mpv.webp.`

But if give the path in the form `external-file=/home/USERNAME/.config/mpv/mpv.webp`, mpv will find the image.
