### ISSUE TITLE
Blank Screen on El Capitan

### ISSUE THREAD

**Issue by es0phagus** [mpv-player/mpv#2369]
App doesn't work at all.
<img width="960" alt="screen shot 2015-10-02 at 21 23 36" src="https://cloud.githubusercontent.com/assets/11819257/10256860/e076f5bc-694b-11e5-87b8-ef2c811dfc77.png">

**Comment by es0phagus** [comment]
Welp, unintentionally left the program running in the background for about 2 mins and the movie suddenly started playing.

**Comment by AirPort** [comment]
Have you installed it with homebrew? Is it linked against "official" libass or git version?
I had something similar when homebrew by mistake built git-master against libass-release and fontconfig started to rebuild the cache.

**Comment by es0phagus** [comment]
No, I installed it via the mpv_0.10.0_mac.tar.bz2 on the site.

**Comment by Pacoup** [comment]
Yeah, when you build with homebrew (assuming you are following this: https://coalgirls.wakku.to/faq/playback/compiling-mpv-on-mac-os-x), the font cache will be built during the whole compilation process, so you won't run into this issue.

However, if you install from the the tarball, the application will need to generate the font cache upon first play, but it has no GUI for it, so you get the behaviour you just posted about. If you looked at the processes in Monitor, you would have noticed mpv was building the font cache (well, using CPU for a while).

I believe this process repeats if you install new fonts (e.g. you just installed Photoshop along with some fonts that come with it).

**Comment by maxime-michel** [comment]
Thanks for the details @Pacoup - had the same problem and was wondering what was going on.
