### ISSUE TITLE
Does ytdl_hook really need to check version every time?

### ISSUE THREAD

**Issue by octos** [mpv-player/mpv#2370]
Playing `mpv` with the `--msg-level=all=trace` option indicates that `ytdl_hook` wastes about 0.5 seconds every time a url is played on checking `youtube-dl`'s version. This seems rather inefficient and wasteful. Wouldn't it be better to check it only on the first execution and learn from that?

**Comment by wm4** [comment]
It should be checking once every mpv invocation.

**Comment by ChrisK2** [comment]
> It should be checking once every mpv invocation.

And it does. We could try to cache the result, but sounds like a bit too much effort just to squeeze out <1 sec. Patches welcome.

**Comment by wm4** [comment]
> We could try to cache the result,

How? youtube-dl could be updated, reinstalled, etc. between invocation. (Well, technically even while mpv is running, but we assume mpv isn't running for very long.)

**Comment by octos** [comment]
Do we really need to check at all? Isn't it safe enough to assume that `youtube-dl` is not too old?

**Comment by wm4** [comment]
>Do we really need to check at all? 

We can probably drop it now. Even Debian unstable's youtube-dl isn't older than 4 months.

**Comment by octos** [comment]
Great! Simpler, shorter code is always welcome.

**Comment by ChrisK2** [comment]
> How?

Write the mtime of youtube-dl to some file and only check if it doesn't match anymore ... but there are probably a bunch of corner cases that will break this anyway.

> We can probably drop it now.

Well, as long as we are not relying on a bleeding-edge feature, or youtube-dl decides to significantly change the JSON output ... yeah, we could just drop the check entirely.
