### ISSUE TITLE
no shortcut key to enter [native] fullscreen mode under OS X

### ISSUE THREAD

**Issue by cwbsw** [mpv-player/mpv#2374]
There are two fullscreen behaviors under OS X. When pressing "k", mpv will playback in the current desktop. When clicking the fullscreen button at the upper left corner, mpv will playback in a new desktop, like other application's fullscreen mode. But no key binding could handle it.

**Comment by ChrisK2** [comment]
Uh ... the "OS X fullscreen mode" has been removed months ago and the ``k`` key is assigned to something entirely different by default. ``f`` gets you into normal fullscreen.

**Comment by cwbsw** [comment]
@ChrisK2  Sorry, I made a mistake in the first post. It is "pressing f ", instead of "pressing k".  I mean, the green button still works in the current version of mpv. Its default behavior is entering fullscreen mode, not "maximizing" the window. But no shortcut key.

**Comment by brunal** [comment]
According to [the reference](http://mpv.io/manual/master/), ⌘+f should toggle fullscreen mode.

**Comment by cwbsw** [comment]
@brunal 
When pressing ⌘+f, nothing happen.

**Comment by ChrisK2** [comment]
It should just do the same thing as ``f`` anyway. I suspect your mpv version is heavily outdated.

**Comment by cwbsw** [comment]
@ChrisK2 
No, it's 0.11.0 and OS X 10.11.

**Comment by ChrisK2** [comment]
So .. uh ... on 10.11 the green button makes mpv go full screen on a new space although mpv doesn't support this itself? Is that new?

**Comment by AirPort** [comment]
Yep, it seems like it. 
It should be new, I'm pretty sure it didn't work like this in Yosemite.

**Comment by ChrisK2** [comment]
Okay and Window -> Zoom (⌘Z) just does the old window "maximize" I guess?

**Comment by cwbsw** [comment]
@ChrisK2 
I'm not sure if it's new, because I have no older OS X and mpv versions to test. But at least under OS X 10.11 and mpv 0.11, Window -> Zoom (⌘ + z) or ⌥ + green button "maximize" the window, green button makes mpv go full screen on a new space like other native OS X applications, it also supports OS X 10.11's new feature split view. So please just bind green button to a shortcut key like ⌘ + f.

**Comment by sumyungguy** [comment]
Fyi, the standard way of doing this is to have a View menu, with a menu item Enter Full Screen, and the keyboard shortcut ^ ⌘ F (control-command-F).

Personally I find the normal f fullscreen, with its ability to black out the secondary monitor, to be much superior. I suppose they could co-exist...

**Comment by Eitot** [comment]
I came across this thread while looking for a way to use OS X' full-screen mode instead of the current implementation. On Mavericks there is no way to use it: no button in the window, no menu entry and the above-mentioned keyboard shortcuts don't work. Have I understood this correctly: this feature was intentionally removed?

**Comment by ChrisK2** [comment]
Yes, it never worked properly.

**Comment by wygsephi** [comment]
This is exactly what I have been looking for. My issue is that under the current full screen implementation, the video would be kinda laggy. It seems like it has something to do with the dock, because if I use the green button to enter the native mac full screen, the video is nice and smooth, no issue.

The difference I figure is that under the native full screen the dock won't show up no matter what, but under the current implementation, the dock will pop up if I move my mouse to the side it locates. The reason of the laggy issue could be something else, but a native full screen shortcut would be nice. Though I like the current implementation, too.

**Comment by martinotu94** [comment]
Really hoping to have a handy shortcut to enable native macOS fullscreen like "f" do for the normal fullscreen. Possible to implement?

**Comment by ear** [comment]
Being able to use macOS native full screening has the advantage of being able to use split-screen. I.e. drag another app on the space occupied by mpv and it plops on its side. You can then adjust the relative size of the split by dragging the dividing line and plop both apps out of full-screen mode by clicking on the top left corner of the icon in mission control top bar.

That said, having *both* options would be great still, not advocating for removing features here.

**Comment by sumyungguy** [comment]
@ear We already have both options. Native full screen works fine, click the green button at the top left of the window.

This issue is about getting a keyboard shortcut for it. Normally that's `^ ⌘ F` in macOS, but it doesn't work in mpv. So for now, just click the button.

**Comment by ear** [comment]
Oh cool, I had not noticed because I use mpv without any chrome, the window is prettier this way 😃 

Is it possible to add such a binding through the configuration file?

**Comment by sumyungguy** [comment]
No, it's not - that's the point of this bug report.

**Comment by kkkrinko** [comment]
I use 'no-border' because this looks so cool and the gray border doesn't match the white OS X.
But here is the problem. When the title is hidden, the green button disappears too. So I'm not able to get native fullscreen by clicking the button. A keyboard shortcut will be helpful.

**Comment by martinotu94** [comment]
Totally agree with you guys. Keyboard shortcut (and maybe configurable) for native fullscreen will be very very appreciated!

**Comment by maaya1989** [comment]
——I use 'no-border' because this looks so cool and the gray border doesn't match the white OS X.
That's exactly my problem, I don't know why it didn't just use the native OS X boarder and now I have to keep the grey boarder simply because I'd like to have the native OS X fullscreen... it's like the developers just hate OS X so much they don't want anything native...

**Comment by sumyungguy** [comment]
Not sure what you mean - on my system, I get a standard native title bar, which is grey and looks the same as every other title bar, eg. in TextEdit. There are no other borders.

It looks like it would be relatively easy to add the native fullscreen keyboard shortcut. On 10.11 El Capitan and later, all you have to do is add a "View" menu, and the OS automatically adds the "Enter Full Screen" menu item and control-command-F keyboard shortcut.

https://developer.apple.com/library/prerelease/content/releasenotes/AppKit/RN-AppKitOlderNotes/  -  search "Full Screen Menu Item"

**Comment by maaya1989** [comment]
<img width="846" alt="ss 2016-10-28 14 44 52" src="https://cloud.githubusercontent.com/assets/13052129/19807052/8dec08e8-9d1e-11e6-9900-c266ae3171c4.png">
<img width="846" alt="ss 2016-10-28 14 44 52" src="https://cloud.githubusercontent.com/assets/13052129/19807157/1a341728-9d1f-11e6-9a34-407839125b90.png">

Sorry for the late response but I think these pictures give a better idea of what we were talking about.
P1:Above, window title bar, below, fullscreen window boarder. P2:window title bar of textedit. It wasn't grey like this on El Capitan, it's a Sierra thing.

**Comment by Akemi** [comment]
fixed in https://github.com/mpv-player/mpv/commit/a8347eb9ba9e09177da50592fde7f3ae7261ce59
