### ISSUE TITLE
mpv 0.11.0 Warning for AudioComponentPluginLoader

### ISSUE THREAD

**Issue by robertgzr** [mpv-player/mpv#2375]
Everything works fine but I would like to know where it comes from...
The *CGContextErase* thing I get since I installed mpv and from what I found online it might be because of some wacom drivers but the audio warning is new.

console output:

    $ mpv --profile=ydl $(pbpaste)
    Playing: https://www.youtube.com/watch?v=JvP0TD-Cr3o
    Cache fill:  1.23% (1048576 bytes)
     (+) Video --vid=1 (*) (h264)
     (+) Audio --aid=1 --alang=und (*) (aac)
    2015-10-04 12:19:53.647 mpv[28540:4e03] 12:19:53.647 WARNING:   [mpv/playback core (OSX)]        >compload> AudioComponentPluginLoader.cpp:662: RegisterComponentsFromArray:
    AO: [coreaudio] 44100Hz stereo 2ch float
    VO: [opengl] 1280x720 yuv420p
    Oct  4 12:21:19 mbp.local mpv[28540] <Error>: The function `CGContextErase' is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.

**Comment by wm4** [comment]
>The function `CGContextErase' is obsolete and will be removed in an upcoming update. Unfortunately, this application, or a library it uses, is using this obsolete function, and is thereby contributing to an overall degradation of system performance.

mpv doesn't call this function. You must be using some plugin (maybe an audio plugin?) which causes this message. We didn't get any similar reports either.

**Comment by robertgzr** [comment]
Like I said I think that is because of some driver...

But I was asking about this warning:

    015-10-04 12:19:53.647 mpv[28540:4e03] 12:19:53.647 WARNING:   [mpv/playback core (OSX)]        >compload> AudioComponentPluginLoader.cpp:662: RegisterComponentsFromArray:
