### ISSUE TITLE
Cocoa backend overlays Dock while on top

### ISSUE THREAD

**Issue by yndi** [mpv-player/mpv#2376]
Having the Dock automatically hidden and shown along with a player window placed somewhere on the bottom of the screen with `--ontop` enabled, it makes the Dock overlaid, hence completely unusable. I personally find such behavior quite odd. Is there anyone who actually needs this? I propose we make it as in MPlayer OS X Extended.

**Comment by wm4** [comment]
Well, how about not enabling ontop then?

**Comment by yndi** [comment]
I believe, `--ontop` should mean "on top of all user windows", not "on top of all system windows" as well. I would like to use the Dock to switch applications while watching a movie on top of a browser window or a text editor one for example.

**Comment by ChrisK2** [comment]
No no no. This may be the case for you, but not everyone. If you are using multiple displays you may NOT want the dock to go over your fullscreen window whenever you focus a different application.

**Comment by yndi** [comment]
Fair enough. We should make the option look like `--ontop=<yes|no|modal>` or something like that then.

**Comment by yndi** [comment]
OK, I have just realized the idea of changing syntax for such a minor one-platform feature is definitely ugly. What if we check whether the player is running in a multi-monitor configuration instead? When yes, ontop behaves as usual. When no, NSModalPanelWindowLevel is used.

**Comment by pigoz** [comment]
Maybe we could add a `--ontop-cocoa-window-level`.. or you can run your patch locally.

**Comment by yndi** [comment]
I don't think it deserves its own option. We should think about reasons why someone might want such behavior when there is only one active display. If there is none, we should implement the above strategy. Otherwise, I will run my patch locally.
