### ISSUE TITLE
[OSX] osxbundle.py fails

### ISSUE THREAD

**Issue by maru-sama** [mpv-player/mpv#2379]
I just updated to the latest git had (and there was also a XCode update in the meantime) and suddenly the osxbundle.py command fails with the following error..

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: changing install names or rpaths can't be redone for: /Users/maru/source/cvs+svn/mpv-build/mpv/build/mpv.app/Contents/MacOS/mpv (for architecture x86_64) because larger updated load commands do not fit (the program must be relinked, and you may need to use -headerpad or -headerpad_max_install_names)

I am not sure why this happens since this used to work for years. Apparently the error message explains how to solve this but I fail to add the flags to the final link command. LDFLAGS apparently does not work

**Comment by ChrisK2** [comment]
I also had this happen very rarely, it always eventually fixed itself ...

**Comment by maru-sama** [comment]
Ok, I tried it again and instead of just calling ./waf clean I completely removed the directory. Apparently this fixed it.
