### ISSUE TITLE
Streaming drops on HD stream with false EOF

### ISSUE THREAD

**Issue by celem** [mpv-player/mpv#2385]
I am streaming video from a ONVIF IP-Camera. I can stream 640x480 without problems. However, when I stream 1024x720 the stream is visible for a few seconds but then MPV dies thinking that it has reached End Of File (EOF), but, of course there is no EOF - the feed is continuous.

BTW - I added the --untimed option thinking that it would help but it does not. Upon further research I see that it would not. I guess I need mpv to ignore what it thinks is an EOF and keep streaming until manually stopped.
## Here is my console output:

$ mpv --no-audio --untimed --title "rear porch" rtsp://guest:password@mysite.mooo.com:554/11
Playing: rtsp://guest:password@mysite.mooo.com:554/11
[lavf] Forced lavf RTSP input demuxer
[libav/demuxer] rtsp: Estimating duration from bitrate, this may be inaccurate
Detected file format: RTSP input (libavformat)
Clip info:
 title: 10
[stream] Video (+) --vid=1 (h264)
[stream] Audio     --aid=1 (pcm_alaw)
Failed to open VDPAU backend libvdpau_r600.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
Audio: no audio
No video PTS! Making something up.
VO: [opengl] 1280x720 => 1280x720 420p
V: 00:00:00 / 00:00:00 (0%)
Non-monotonic video pts: 0.081000 <= 0.211420
Jump in video pts: 0.211420 -> 0.081000
V: 00:00:00 / 00:00:00 (0%)

Exiting... (End of file)
$

**Comment by wm4** [comment]
Overlooked this. This could be a problem with ffmpeg's rtsp support, or the way mpv interacts with it. But without being able to reproduce this (hard without an URL), I don't know what's happening. Most likely ffmpeg has some timeout or so, which makes it think the connection was severed.

**Comment by celem** [comment]
Contact me (email sent separately). I'll supply a link for your testing.

**Comment by wm4** [comment]
Well, you can just send me the link.

**Comment by celem** [comment]
Here it is. This is my ONVIF IP-Camera. It usually fails after about 15 seconds.
mpv  --no-audio rtsp://vlang:Lang1234@celem.mooo.com:556/11

**Comment by wm4** [comment]
Did you intend to post this publicly?

**Comment by lachs0r** [comment]
(Also make sure your IP cameras and printers are NEVER on the same network as anything else. These devices are ripe with vulnerabilities that never get patched and WILL expose any network they’re directly connected to.)

**Comment by celem** [comment]
No. User now deleted.

**Comment by wm4** [comment]
From some simple testing, it seems to hit libavformat's internal timeout. On the other hand, raising this timeout somehow doesn't work. Will do some more testing tomorrow.

**Comment by celem** [comment]
Thanks for the update

**Comment by wm4** [comment]
Whoops, a month has passed, and I haven't felt yet like I had enough time to look at this. Maybe soon.

**Comment by celem** [comment]
Any testing planned? Should I keep your login active in the camera?

**Comment by wm4** [comment]
If I'm trying again, and it doesn't work, I'll let you know.

For now I can imagine nicer ways to spend my time than debugging this, sorry.

**Comment by SphtKr** [comment]
FWIW, I think I'm seeing the same issue on my ZModo camera, and that's strictly with ffmpeg, not mpv-player. Driving me nuts, but likely an upstream issue in your project's case.

**Comment by dottgonzo** [comment]
i had the same problem with revotech cams. After spending a lot of time to develop a lib to interact with mpv socket, then i've noticed this issues with some onvif camera used for testing. Precisely mpv 0.23 worked perfectly with dahua and ezviz models and present this issue with a revotech (randomly between some seconds to 3-4 hours, reach a signal of end of file and switch to the next item on the playlist). I've tryed with lots of mpv flags with no lucks. My solution was rewriting the lib to work with vlc. 

Feel free to ask for every kind of tests.

**Comment by dottgonzo** [comment]
after the commit i've noticed that i've never used --keep-open=always, next days i will try it

**Comment by wm4** [comment]
> Feel free to ask for every kind of tests.

Generally, anything that makes it easy to reproduce and is always available might help.

Also, try to reproduce this with ffmpeg (the CLI tool), and report back.

**Comment by tmatth** [comment]
This sounds a lot like:
https://lists.libav.org/pipermail/libav-devel/2017-November/085445.html

**Comment by wm4** [comment]
mpv forces rtsp_transport=tcp, at least now.

**Comment by Akemi** [comment]
seems like ffmpeg issue. if it still persists please open a new issue.
