### ISSUE TITLE
How do you add subtitles?

### ISSUE THREAD

**Issue by HazyChestNutz** [mpv-player/mpv#2390]
For example, I am playing movie which doesn't contain any subtitles. I downloaded an .SRT file off the internet, but how do you enable that?

**Comment by kevmitch** [comment]
either drag and drop the file onto the video window, or start the player from the command line with ```--sub-file=filename.srt```

**Comment by HazyChestNutz** [comment]
drag and drop??? That's high tech. Thank you so much. that helps alot.

**Comment by kevmitch** [comment]
I think it also works automatically if the sub file has the same name as the video file (modulo extension) and is in the same directory.
