### ISSUE TITLE
Could you please provide a simple example of how to control a mpv instance?

### ISSUE THREAD

**Issue by Harinlen** [mpv-player/mpv#2391]
I'm trying to use mpv as a backend of my music player. But unlike Phonon or bass, we have to use command to control the mpv instance. But there's nothing about the this.
Could you please provides a simple c codes or Qt codes of controlling mpv instance? Provides some simple control like play&pause, stop, change volume, reset playing data.
Thanks!

**Comment by Harinlen** [comment]
Or, it there any slave mode like mplayer for mpv? It the mpv work the same as mplayer?

**Comment by wm4** [comment]
libmpv: https://github.com/mpv-player/mpv/tree/master/DOCS/client_api_examples
pipes: https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv

**Comment by Harinlen** [comment]
Thanks.
