### ISSUE TITLE
opengl Fullscreen exclusivity causes window ordering problems

### ISSUE THREAD

**Issue by bitingsock** [mpv-player/mpv#2394]
Windows 10 x64
This has actually been a problem for me ever since I started using mpv way back.
This is not a problem when I use DirectX.
When using opengl and setting to full screen, if I [ALT+TAB] to another window a few problems arise:
1) I cannot see the [alt+tab] window
2) I cannot see the window I am switching to
3) the window I've switched to properly receives all subsequent controls until "focus" is brought back to mpv's vo

**Comment by bitingsock** [comment]
This seems to have been fixed by something recently. No longer an issue.

**Comment by wm4** [comment]
Did MS fix DWM?

**Comment by kevmitch** [comment]
Still happens for me.

**Comment by bitingsock** [comment]
I don't think it's a change in mpv. Tried with the lachs0r build I was using when I reported this and it works with that too. kevmitch: what os do you use?

**Comment by bitingsock** [comment]
I don't think it's related but my D3D vo doesn't work anymore
https://paste.ee/r/7alsG
Previous mpv builds work correctly.

**Comment by wm4** [comment]
@bitingsock: this was fixed a few days ago in git.

**Comment by kevmitch** [comment]
windows 7

**Comment by wm4** [comment]
For the record, I know this problem, and others have speculated it's a DWM bug. It's not triggered by direct3d, although maybe someone could test with d3d exclusive mode (which can't be enabled with vo_direct3d - maybe I should add an option or so).

**Comment by bitingsock** [comment]
iirc mpc-hc's implementation of d3d exclusive mode would come out of exclusive mode when you alt+tab and re-enter exlcusive mode when you returned focus; I suspect this was a work around for old DWM. The bug was present in win10, but there must have been an update to DWM (or maybe windows opengl?)

**Comment by bitingsock** [comment]
Well I looked through my windows updates and there isn't anything related to DWM or opengl. Magic I guess.
