### ISSUE TITLE
--geometry does not work in Windows 10

### ISSUE THREAD

**Issue by hkenneth** [mpv-player/mpv#2397]
The --geometry option does not work properly in Windows 10 anymore. Setting geometry = 50%:50% but the window is not centered in the screen (single monitor).

There was no such issue in the official 2015-09-03 build but appears in the 2015-09-23 build.

**Comment by wm4** [comment]
Well, what is the window positioned like then?

**Comment by akanosora** [comment]
It looks like mpv centers itself before re-sizing its window. No matter which resolution the opened video has, the left and upper boundaries of the window are always positioned at the same initial place while depending on the resolution, bottom and right boundaries may move out of the screen.

**Comment by ponyo** [comment]
Geometry has never centered itself for me. But you can add the position after the size.

Autofit centers itself but the size isnt exact.

**Comment by mc4man** [comment]
It's quite similar to what  acc5e8f caused in linux before being reverted (maybe returned in some stupid fashion?
to ck. > in mpv.conf (for vid started via context menu or file association
[pseudo-gui]
force-window=no

**Comment by mc4man** [comment]
From a proactive side (as seen in linux) the misplacement seems to come from what is achieved with the
force-window=immediate option, ie. upper l. corner remains the same from dummy to actual vid window.
