### ISSUE TITLE
Show progress[ in task]bar in windows 7 & greater

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#2399]
If possible, it would awesome to have this feature in windows build. 
The progressbar will showed how much the video currently played

**Comment by ChrisK2** [comment]
What progressbar?

**Comment by shinchiro** [comment]
I mean progress in taskbar..

**Comment by DerpMcDerp** [comment]
mpc-hc implements this feature. One noteworthy thing about its implementation is that it uses the ITaskbarList3::SetProgressState method with TBPF_PAUSED so you can tell if the movie is paused or not via the taskbar.

**Comment by lachs0r** [comment]
This shouldn’t be too hard. Guess I’ll give it a shot today.

**Comment by wm4** [comment]
Well, the hard part is somehow getting the playback state in this part of the code.
