### ISSUE TITLE
Track 1 can't be selected twice.

### ISSUE THREAD

**Issue by Daniyal-Javani** [mpv-player/mpv#2400]
When I run:
```
mpv video.mkv -sub-file persian.srt -sub-file english.srt -secondary-sid 1
```
and want Persian sub goes up and English sub goes down, got this error: Track 1 can't be selected twice. For more understating should change it to:  
```
mpv video.mkv -sub-file english.srt -sub-file persian.srt -secondary-sid 2
```
to work.
Maybe this is a bug!

**Comment by ChrisK2** [comment]
Not really a bug. The first external subfile you supply gets selected for bottom-sub and then you tell it to use it for top-sub as well.
Either add ``--sid=2`` to tell it to use the second file for bottom, or just go with your own solution.
