### ISSUE TITLE
Dolby Atmos Support

### ISSUE THREAD

**Issue by maletor** [mpv-player/mpv#2401]
I have been unable to get Dolby Atmos steams to work correctly with passthrough. There are reports that this works correctly on Kodi, so it must be possible.

Sample files can be found on [a related ffmpeg bug report](https://trac.ffmpeg.org/ticket/3960).

I have a receiver capable of Dolby Atmos and can test patches if you would like.

**Comment by kevmitch** [comment]
Which ao are you using? 

What exactly happens when you try?

**Comment by maletor** [comment]
I am using ALSA.

I can enumerate `truehd` for passthrough, but technically this is Dolby Atmos. As one might expect, setting `truehd` only sends TrueHD as evidenced by the ATMOS light not turning on.

**Comment by wm4** [comment]
>There are reports that this works correctly on Kodi, so it must be possible.

From what I can see in kodi code, their way to pack truehd into spdif is pretty similar to ffmpeg's (and we use ffmpeg's code). Could you try to capture the bytestream produced by both players? (I'm not totally sure how to do this. In mpv you can use ``--ao=pcm``.)

**Comment by maletor** [comment]
@wm4, I think we can get this to work with something like `ffmpeg -i INPUT -f alsa default`. If that's the case is there much complexity with supporting that in mpv?

This may not be working now because `--audio-spdif=help` does not list any kind of "raw" format?

**Comment by wm4** [comment]
Doesn't this command just decode to pcm?

**Comment by maletor** [comment]
You're right. It decodes, in this case, to TrueHD. There's got to be a way to stream the bits directly to the hardware, unmolested.

**Comment by maletor** [comment]
Tried `aplay -Ddefault ~/Atmos.proprietary` with no luck. The issue is ALSA thinks the sample rate must be set, which doesn't even make sense as a requirement to stream bits and certainly doesn't make sense for "object based sound",  So, I try `iecset -Ddefault audio 0` but still no luck. If one could read the Kodi code to know what it's doing that would be the most helpful to resolve

**Comment by wm4** [comment]
> which doesn't even make sense as a requirement to stream bits

Actually it does. Compressed passthrough is a hack that transfers the data pretending it's some form of pcm. This happens on all level, even the lowest.

**Comment by wm4** [comment]
Also, does this definitely work with kodi? Did you try it?

**Comment by goblin** [comment]
> evidenced by the DOLBY ATMOS light not turning on

@maletor which hardware has this light? I find it extremely hard to find; for instance, the top-end [Samsung HW-N950](https://www.samsung.com/us/televisions-home-theater/home-theater/sound-bars/hw-n950-samsung-harman-kardon-soundbar-with-dolby-atmos-hw-n950-za/) doesn't seem to have any way to distinguish between EAC3 (DD+), TrueHD, or either of these with the extra Atmos metadata.

I'm starting to think Dolby Atmos (in case of this soundbar at least) is just a marketing gimmick to mean "we'll do some signal processing on your 5.1/7.1 (E)AC3/TrueHD streams and send it out some extra tweeters on the sides of the soundbar and don't you worry about any metadata in your source".

Also, how can one distinguish between a EAC3/TrueHD and Atmos streams programatically or on the command line? mpv seems to just display `ac3` or `truehd` when playing the Amaze demo from https://thedigitaltheater.com/dolby-trailers/ (the "Lossless-ATMOS" one is described as "Dolby TrueHD 7.1 ATMOS"). Importing them in Audacity just gives you 6 or 8 regular channels. Is there a way to check if there's actually some extra metadata there (and what data that is)?

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by wm4** [comment]
Stop falling for dolby marketing scams.

**Comment by Darkwolf1515** [comment]
So does atmos work in mpv or not? I’m really confused here.

**Comment by tokyovigilante** [comment]
It does for my use (mpv build from master, correct passthrough flags set, HDMI to Denon AVR-3600H). Atmos indicator on receiver when appropriate EAC3 w/ embedded Atmos data tracks played. Some issues with sync loss on seek, although  I note @wm4 has kindly patched some of the stream-silence behaviour recently.

**Comment by bombadilio** [comment]
I can get DOLBY atmos / DTS-HD tracks to play on MPC-BE x64 but in MPV it only shows up as Dolby Surround. Is there a work around for this?

**Comment by ValZapod** [comment]
Works for me in MPC-HC including on Dolby Atmos in EAC3 music ripped from Tidal (LavFilters should be configured to bitstream EAC3). Atmos TrueHD in MAT 2.0 also works, and so is DTS (without DTS:X) and Dolby 5.1.

**Comment by ValZapod** [comment]
BTW, the key part in decoding atmos metadata in EAC3 are those Huffman tables. https://www.etsi.org/deliver/etsi_ts/103400_103499/103420/01.02.01_60/ts_103420v010201p0.zip

**Comment by kasper93** [comment]
It should work currently. If it doesn't for you please, report issue with all the necessary information to diagnose the issue.
