### ISSUE TITLE
Playback gaps during ordered chapters playback

### ISSUE THREAD

**Issue by NoMoKeTo** [mpv-player/mpv#2404]
When playing a mkv file with ordered chapters there is a noticeable gap in audio and video playback when playing non-consecutive chapters.

The cache empties completely before the seek to the next chapter. It should be preloaded to avoid this gap. Something like --merge-files, but for the automated seeking that happens during ordered chapters playback.

**Comment by wm4** [comment]
>The cache empties completely before the seek to the next chapter

That's not true. But seeking will usually flush the cache, I guess.

**Comment by NoMoKeTo** [comment]
Thanks for the response. I just checked and you are right – it happened for me because the chapter was at the end of the file. 

Still, the gap occurs regardless and is not the expected behaviour while watching a movie. In this case, the ordered chapters are used to switch between parts that are different in the theatrical and extended version and parts that are the same – the switch happens mid-scene or event mid-sentence most of the time. Is there some way to prevent this gap during playpack?

**Comment by wm4** [comment]
I recommend remuxing ordered chapters to a linear file. Ordered chapters are insane.

**Comment by NoMoKeTo** [comment]
Well, this would take much more space and is therefore not really a solution… It makes sence to use ordered chapters for this type of double content. Techniques like this also happen on DVDs and Blu-Rays, why not use them in MKV?

**Comment by wm4** [comment]
Because mkv files are not blurays?

**Comment by NoMoKeTo** [comment]
Looking at the features and techniques they support, they are not too different.

**Comment by wm4** [comment]
Quite literally apples and oranges.

**Comment by NoMoKeTo** [comment]
It's not, sorry. http://www.matroska.org/technical/menu/index.html

**Comment by wm4** [comment]
Now what the fucking hell does this dead part of the "spec" have to do with anything?

**Comment by NoMoKeTo** [comment]
It's okay, I already got your “i don't need it so it's bullshit” point. 

Hopefully, someday someone will properly implement Matroska in a mplayer fork.

**Comment by wm4** [comment]
>Hopefully, someday someone will properly implement Matroska in a mplayer fork.

Unlikely, because nobody is interested in this bullshit. I don't have motivation to improve such unneeded features either with bug reports like this. ("lol just do it like bluray")

**Comment by wm4** [comment]
Actually, it looks like there might be progress in this matter. From what media were you playing these files? Hard disk or some sort of slow network? If it's the former, it's fairly certain it's just a known problem due to the way this is implemented.

**Comment by NoMoKeTo** [comment]
It was from my Hard Disk.

**Comment by wm4** [comment]
Then it's unlikely that this is happening due to caches running out. The player just times the audio/video so that there's a gap. This is not the first report about this (thus a duplicate). I'll try to fix it somehow as soon as I find time.
