### ISSUE TITLE
input.conf run command and show its output

### ISSUE THREAD

**Issue by lightonflux** [mpv-player/mpv#2405]
In the documentation i found how to assign a key to a command and how to display text. 

E.g. by adding this line in your input.conf: 

```
 ctrl+r run "rm" "-v" "${path}" ; show_text "Deleted ${filename}"
```

For other commands it would be helpful if mpv could display the output of the command. Maybe the answer is in the documentation but i wasn't able to find it. 

Is this possible? 

A simple example: 

```
ctrl+t run "date" ; show_text DATE-OUTPUT 
```

And is it possible to specific the duration of display for show_text?

**Comment by wm4** [comment]
>Is this possible? 

Not currently. The command is run asynchronously too, so it's not clear when or how it'd show output on OSD. You're probably better off doing this in a Lua script.

**Comment by Dudemanguy** [comment]
Sounds like a job for a script as noted previously.
