### ISSUE TITLE
how can I pass locally installed ffmpeg path to waf configure?

### ISSUE THREAD

**Issue by kensully** [mpv-player/mpv#2406]
Hi 
I am on Ubuntu 14.04.3 32 bit platform.
I installed ffmpeg into non-standard path according to this  [guide!](https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu)

I also added gnutls and openssl support. 
I cloned mpv repo here and exported ffmpeg pkg conf path `export PKG_CONFIG_PATH=$HOME/ffmpeg_build/lib/pkgconfig:/usr/lib/i386-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig` and ran `./waf configure  LDFLAGS=-L"$HOME/ffmpeg_build/lib"   CFLAGS=-I"$HOME/ffmpeg_build/include"`

then I run `./waf` build but it finds system libav libraries in `/usr/lib/i386-linux-gnu/`
and linking process fails due to older library.

Is there any way to override system path in `waf configure` step?

I am amateurish programmer, I didn't find a reliable way to pass non-standard library path to compiler. I hope somebody help me here.
Regards.
Kenn

**Comment by wm4** [comment]
Setting `PKG_CONFIG_PATH` should be sufficient. If it fails at runtime, you have to use LD_LIBRARY_PATH, --enable-rpath in ffmpeg configure, or use static linking. Look how mpv-build does it.

**Comment by yurashek** [comment]
There is -R/alt/lib/path option to linker (called R-path)  ...but it looks even if I will put it into the .pc (pkg-config) file (into "Libs:" record) WAF ignore it.
