### ISSUE TITLE
How to watch 3D SBS movies with anaglyph glasses on MPV?

### ISSUE THREAD

**Issue by Daniyal-Javani** [mpv-player/mpv#2413]
Actually how can I convert SBS movies to anaglyph movies when playing?
I test --video-stereo-mode equal some options but didn't work.
And try -vf stereo3d -vo opengl-hq but it isn't wide (16:9) how can I fix it?

**Comment by wm4** [comment]
``--video-stereo-mode`` only does something when the input is fallged as 3D, which unfortunately almost no files do. But you can try ``--vf=lavfi=[stereo3d=in=sbsl:out=agmc]``. See http://ffmpeg.org/ffmpeg-all.html#stereo3d for details.
