### ISSUE TITLE
Low resolution app icon in Linux

### ISSUE THREAD

**Issue by jm2** [mpv-player/mpv#2414]
Icon itself is great, just needs to be higher resolution or svg for HiDPI displays.

![icon](https://cloud.githubusercontent.com/assets/1195033/10654158/91a0b48a-781b-11e5-8f2d-9b11a0ec0038.png)

**Comment by wm4** [comment]
We have high-res icons here: https://github.com/mpv-player/random-stuff/tree/master/icon/png_exports/icon-osx.iconset

There's no native SVG around, though e.g. #2325 made it. Perfectly duplicating the mpv icon as SVG is only possible by using SVG features which almost no SVG renderer supports properly.

**Comment by rossy** [comment]
+1. I recently installed Linux on a HiDPI laptop and it's a shame that the icons packaged with mpv only go up to 64x64, when the Windows and OS X icons go up to 256x256 and 512x512.

**Comment by evgenyz** [comment]
@jm2: You could take files from #2325 and put them in ~/.icons in order to stop straining your eyes.
@wm4: Oh, Jesus, guys! Just pack it how it is, improve later. Literally any SVG is better than 64x64 PNG on a 4K display.

**Comment by lachs0r** [comment]
1097c1416f352fe4da49391548224a057cfc870d added a 128x128 icon.
