### ISSUE TITLE
Passthrough 5.1 but MPV display "stereo 2ch"

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv#2415]
If I play a movie with 5.1 AC3 audio in passthrough, MPV send correctly the 5.1 to the amp but it display:
AO: [alsa] 48000Hz stereo 2ch spdif-ac3

I used this command to test:
```
$ mpv --no-config --audio-device='alsa/hdmi:CARD=NVidia,DEV=0' --audio-spdif=ac3,dts --audio-channels=6 /movie
```

Is it just a little text output bug or something else ?

**Comment by wm4** [comment]
This is normal and due to the way audio passthrough works. The compressed audio is output over 2 channels, but the decompressed audio will actually have 6 channels.

**Comment by Paviluf** [comment]
Perfect. Thank you !
