### ISSUE TITLE
Improve feedback of properties

### ISSUE THREAD

**Issue by ThomS8312** [mpv-player/mpv#2416]
Using the <code>show-text</code> command:

- <code>video-bitrate</code>, <code>audio-bitrate</code>, and the <code>sub-bitrate</code> properties report the value "0" instead of "(unavailable)" when those streams aren't present in played media.

- <code>audio-bitrate</code> doesn't work on DASH audio (youtube-dl) and only reports a value of "0". This might affect <code>sub-bitrate</code> too. I haven't been able to test it.

- <code>audio-params/samplerate</code> reports only the value, but not the unit along with it. The bitrate properties do this already (kbps/mbps) and including the unit "Hz" with it will provide consistency.

**Comment by wm4** [comment]
Fixed in: 955c6843b6b7a491d1707104e5fad048cd1ab72c 56fefde7e2ee0c31e9d4d39b5bd0ca8a5643ebe5

> audio-params/samplerate reports only the value, but not the unit along with it. The bitrate properties do this already (kbps/mbps) and including the unit "Hz" with it will provide consistency.

Rejected. This is hard due to the way it's implemented. Also, it's trivial to add the "Hz" on the receiver side.

**Comment by ThomS8312** [comment]
<blockquote>Also, it's trivial to add the "Hz" on the receiver side.</blockquote>

How do I achieve this? I put <code>KEY show-text ${audio-params/samplerate} Hz</code> into input.conf, but when that info is unavailable it reports "(unavailable) Hz". My goal is to have the unit show after the value when available but disappear when reported "(unavailable)".

**Comment by Argon-** [comment]
`KEY show-text ${?audio-params/samplerate:${audio-params/samplerate} Hz}`

**Comment by ThomS8312** [comment]
@Argon-
That solution isn't working for me. The screen doesn't display anything at all, unfortunately.

It looks like a variation of the <code>${?NAME:STR}</code> expansion from the Property Expansion section in the man page. It's probably not working because the <code>${audio-params/samplerate}</code> after the <code>:</code> is a subproperty expansion and replaces the part of the syntax reserved for a string. That kind of configuration isn't supported (as far as I know).

**Comment by wm4** [comment]
It works perfectly fine for me.

**Comment by ThomS8312** [comment]
I launched it from the terminal this time and it shows this error message:

<pre>
[input] The show-text option must be an integer: Hz}
[input] Command show-text: argument 2 can't be parsed: option could not be parsed.
</pre>

I copied the configuration exactly as it was posted. It's good to know it works though, but for some reason it isn't for me.

**Comment by Argon-** [comment]
You have to quote the string argument of `show-text` when there are spaces. I just modified the line you posted without testing it.
`KEY show-text "${?audio-params/samplerate:${audio-params/samplerate} Hz}"` works.

**Comment by ThomS8312** [comment]
I got it to work with the double quotes but info is reported only when it's available. Nothing is reported when the info is unavailable though, not even in the terminal.

**Comment by ThomS8312** [comment]
The "(unavailable)" message isn't displayed when playing a video with no audio. Nothing shows up at all. Does this happen to you too or is it just on my end?

**Comment by ThomS8312** [comment]
Ping?

All that's needed to test this is to put <code>KEY show-text "${?audio-params/samplerate:${audio-params/samplerate} Hz}"</code> into input.conf, then launch a video without audio using the command <code>mpv --no-audio VIDEO</code> and press KEY. If "(unavailable)" isn't shown/nothing is displayed at all, I may have another approach to this issue.

**Comment by wm4** [comment]
RTFM, seriously.

**Comment by ThomS8312** [comment]
The <code>${?NAME:STR}</code> expansion was a proposed solution to my issue, and I assumed it was similar to <code>${NAME}</code>. According to the man page, expansion will occur under the condition that the property is available. It doesn't do anything otherwise (when a property can't be retrieved). That makes <code>${?NAME:STR}</code> unsuitable because it doesn't include the "(unavailable)" feedback I want when the samplerate isn't available.

So again, how do I resolve this? I already posted what I tried. The expansion that does most of what I want is <code>${NAME}</code>, but I can't make the "Hz" text independent from the "(unavailable)" message.

**Comment by kevmitch** [comment]
KEY show_text "${?audio-params/samplerate:${audio-params/samplerate} Hz}${!audio-params/samplerate:${audio-params/samplerate}}"

alternatively 

    KEY show_text "${?audio-params/samplerate:${audio-params/samplerate} Hz}${!audio-params/samplerate:(unavailable)}"

**Comment by ThomS8312** [comment]
@kevmitch 
Works perfectly once <code>show_text</code> is changed to <code>show-text</code>. The first one is what I was trying to do. Much appreciated.

I wouldn't have been able to figure that out on my own. This is the first time I've dealt with property expansion in this way and the man page isn't helpful to me in a situation like this. There's no sample example for this kind of scenario and the nested type syntax involved is not familiar to me. I still don't quite understand the syntax yet (I'm not a coder), but when I have the time I'll study it more in depth.

The expansions you provided resolve my issue surrounding one property, but is it possible to combine multiple properties together with text between them? For example, if <code>KEY show-text ${dwidth}x${dheight}</code> could expand to simply "(unavailable)" rather than "(unavailable)x(unavailable)" when it can't be retrieved.

@Argon- 
Thanks for offering your help.

**Comment by Argon-** [comment]
You reached now a point where you actually want/need some kind of logic. Even though it would be possible to do this with simple property expansion, it will look awful.
You might want to look at Lua scripts. Although it itself is a bit more complex than simple property expansion, it will also provide you with far more possibilities.
Other than that, maybe some existing user-mode scripts provide what you search for: https://github.com/mpv-player/mpv/wiki/User-Scripts

**Comment by qmega** [comment]
Lua seems like overkill for this. In the case of `dwidth` and `dheight`, you can get away with only checking one, since they'll either both be available or both not:
`${?dwidth:${dwidth}x${dheight}}${!dwidth:(unavailable)}`

**Comment by ThomS8312** [comment]
I haven't even thought of Lua scripts. I never learned how to write them because it looks too advanced. Then again, I was able to figure out the property expansion syntax yesterday after carefully examining the solution that was posted by kevmitch. It wasn't that difficult either (all those curly brackets are what caused the confusion for me). Hopefully, learning to write Lua scripts will be the same way.

I see that that link also leads to the Lua documentation, which includes examples too. Examples are what I think the Property Expansion section of the man page lacks. If I had had something to reference, the man page would have been more useful to me. Kevmitch's post not only resolved my issue, it became the reference that helped me to understand the property expansion syntax.

<blockquote>In the case of dwidth and dheight, you can get away with only checking one, since they'll either both be available or both not:
${?dwidth:${dwidth}x${dheight}}${!dwidth:(unavailable)}</blockquote>
Seeing this posted is further confirmation that I understand property expansions now. This is similar to the solution I came up with on my own shortly after I figured out the property expansion syntax. I had <code>${!dwidth:${dwidth}}</code> for the last part instead because I prefer the "(unavailable)" to be from a failed retrieval and not manually put in.

I'm not completely satisfied with it though because I don't like how the focus is on width alone and not width/height together. But, if height were added, it will cause both to expand and show "(unavailable)" twice. It's pretty specific, and demonstrates how restrictive property expansion can become with complexities.

Are there any circumstances at all where only width or height can be determined, but not both?
