### ISSUE TITLE
Can something be done to minimize certain network stutters (log inside)?

### ISSUE THREAD

**Issue by for-coursera** [mpv-player/mpv#2419]
On a certain streams from time to time I encounter something like this:

```
[ 124.663][v][ffmpeg/demuxer] hls,applehttp: HLS request for url 'http://my_url/9133.ts', offset 0, playlist 0
[ 135.827][w][ffmpeg] http: HTTP error 500 Internal Server Error
[ 135.827][w][ffmpeg/demuxer] hls,applehttp: Failed to reload playlist 0
[ 136.751][v][ffmpeg/demuxer] hls,applehttp: HLS request for url 'http://my_url/9134.ts', offset 0, playlist 0
[ 137.270][w][lavf] error reading packet.
[ 137.270][v][lavf] EOF reached.
[ 145.024][v][ffmpeg/demuxer] hls,applehttp: HLS request for url 'http://my_url/9135.ts', offset 0, playlist 0
```

Or like this:

```
[ 585.141][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[ 589.695][v][ffmpeg/demuxer] hls,applehttp: HLS request for url 'http://my_url/9179.ts', offset 0, playlist 0
[ 590.215][w][ffmpeg] http: HTTP error 500 Internal Server Error
[ 590.215][w][ffmpeg/demuxer] hls,applehttp: Failed to open segment of playlist 0
[ 590.215][v][ffmpeg/demuxer] hls,applehttp: HLS request for url 'http://my_url/9180.ts', offset 0, playlist 0
[ 591.330][w][ffmpeg] http: HTTP error 500 Internal Server Error
[ 591.330][w][ffmpeg/demuxer] hls,applehttp: Failed to open segment of playlist 0
[ 591.993][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
```

As I understand from the log, it's the server, which is to blame, am I right? However, other streams from the same server work just fine, and the problems in question appear only with this one.

Also, is it possible to fix it somehow by increasing the cache? Or the timeout, may be?

**Comment by wm4** [comment]
If the server returns error 500 for a fragment, we can't do anything. ``--demuxer-readahead-secs=`` can increase the readahead packet queue size, which might help with HLS as long as the server doesn't return errors for fragments,

**Comment by for-coursera** [comment]
Yeah, thought so :). Also, tried `--demuxer-readahead-secs=30` before with no effect (btw, it doesn't accept values greater than 30 secs, does it?)

The strangest thing, however, is that with VLC it works like a charm...

**Comment by wm4** [comment]
>Also, tried --demuxer-readahead-secs=30 before with no effect (btw, it doesn't accept values greater than 30 secs, does it?)

I don't think it's limited.

>The strangest thing, however, is that with VLC it works like a charm...

Probably a problem with libavformat's HLS implementation. Since you didn't post an URL, we will never know, nor will it ever be possible to fix it.

**Comment by for-coursera** [comment]
> I don't think it's limited.

I've tried like 60 secs but the value displayed on the onscreen controls was always 30 at best (and it never restored to that number after it started to fall).

> Since you didn't post an URL

Well, can I contact you privately then? :) nfxjfg @ googlemail . com it is?

**Comment by wm4** [comment]
Sure.

**Comment by wm4** [comment]
I'm getting problems with vlc too. 

I see errors like:

> http access error: error: HTTP/1.1 500 Internal Server Error

and:

> httplive stream error: reloading playlist failed

Also vlc tends to blank the screen and "reinitializes" the video (including showing an OSD message).

So this is probably a problem with the server.

One thing that isn't ideal in mpv is that A/V desync happens (by the size of an segment). Not sure why.

**Comment by for-coursera** [comment]
After inspecting VLC log, I must agree with you, it indeed has same "code 500" errors, too. However, from a user side, I'd also say that those errors really haven't been that obvious (like pausing the playback, etc...)

I mean, I've tried the stream for some 15 minutes, had some 6 "code 500" errors in the VLC's log, and only had heard one pause (if any, really – it was that short and non-disturbing).

Any suggestions may be how to make that beautiful mpv to act like that? :)

**Comment by yunake** [comment]
for 50x and 40x, is it possible to make libavformat (or wherever the networking code lives) retry with a timeout? this would resolve a lot of these since they are often just a symptom of overload.

**Comment by Akemi** [comment]
please open a new issue if the problem still persists.

**Comment by emansom** [comment]
During heavy traffic on various video platforms, 500 can be encountered. It'd be useful if mpv/ffmpeg/libav can be told to retry instead of quit during such scenarios.
