### ISSUE TITLE
--sub-text-font option fails when using :style=Bold in v0.11

### ISSUE THREAD

**Issue by baco** [mpv-player/mpv#2421]
I was using the following default options:

    sub-text-font=Cantarell:style=Bold

after upgrade to v0.11 the fonts displayed in subtitles were neither Cantarell glyphs' nor bold. It felt back to the generic Sans Regular I have installed on system.

I've done some tests and I can get back the style I had using:

    sub-text-font=Cantarell
    sub-text-bold=yes

But if I use:

    sub-text-font=Cantarell:style=Regular
    sub-text-bold=yes

I get again the same bad behavior, it falls back to Sans although this time is Bold. ``:style`` in ``--sub-text-font`` is causing the font search to fail and fall back to system's default.

Cantarell is not the only font I've tested. All typefaces had the same behavior.

**Comment by wm4** [comment]
It's a libass change, the old behavior is not possible anymore.

**Comment by baco** [comment]
But that syntax is documented in mpv v0.11's manpage.

Couldn't be the support for such API implemented directly in the config parser method? Say, a middle converter function from fontconfig patterns to the necessary flags to achieve the same behavior. There aren't so many patterns for ``:style``, and the only relevant one is Bold which should add ``--sub-text-bold=yes`` to the running flags, all the others may be stripped off.

**Comment by wm4** [comment]
No, too complicated, just use the bold option.

Also, this was fixed in mpv git's manpage.
