### ISSUE TITLE
Video plays at double resolution on Retina Display (OSX)

### ISSUE THREAD

**Issue by theqat** [mpv-player/mpv#2423]
On OSX 10.11.1, 13" 2015 Macbook Pro. Only option in config file is opengl-hq

Screen resolution is 2560x1600 with Apple's trickery making it act like 1280x800. 

When I play any video, regardless of it being through youtube-dl or straight off my filesystem, the windowed resolution is doubled. Can be demonstrated by trying the same video with --video-unscaled enabled; with that option, it will display at the correct resolution but with huge black bars around it. Without that option, a 1920x1080 video plays at 3840x2160 initially.

Subsequently, when going into fullscreen mode, the player uses a very high level of resources to force the 1080p video down to fit the screen. This problem is less pronounced at 720p.

**Comment by ChrisK2** [comment]
Well uh ... works as intended. The virtual "Apple's trickery" resolution is the one that applications should behave in line with. If you don't like that you can use ``--window-scale=0.5`` to negate this. And you can use ``--autofit-larger=100%`` to avoid having windows opening larger than the screen area.

**Comment by theqat** [comment]
Fair enough. I thought it was playing up because I figured it was getting scaled without me having any scaling options enabled, but if that's how it's intended then cool.

I had played around with the scaling options and autofit but couldn't quite figure out how to get that result. So thanks a lot for that.
