### ISSUE TITLE
Port of sharpen complex 2 shader

### ISSUE THREAD

**Issue by zxx1** [mpv-player/mpv#2425]
vec4 sample(sampler2D tex, vec2 pos, vec2 tex_size) {	

	float px = 1.0/image_size[0];
	float py = 1.0/image_size[1];
	float dx = px*0.6;
	float dy = py*0.6;
	
	vec4 orig = texture(tex, pos);
	vec4 c1 = texture(tex, pos + vec2((-dx), (-dy)));
	vec4 c2 = texture(tex, pos + vec2(0, (-dy)));
	vec4 c3 = texture(tex, pos + vec2(dx, (-dy)));
	vec4 c4 = texture(tex, pos + vec2((-dx), 0));
	vec4 c5 = texture(tex, pos + vec2(dx, 0));
	vec4 c6 = texture(tex, pos + vec2((-dx), dy));
	vec4 c7 = texture(tex, pos + vec2(0, dy));
	vec4 c8 = texture(tex, pos + vec2(dx, dy));
	
	vec4 flou = (c1 + c3 + c6 + c8 + 2 * (c2 + c4 + c5 + c7) + 4 * orig) * 0.0625;
	
	vec4 corrected = 3 * orig - 2 * flou;
	
	c1 = texture(tex, pos + vec2(-px, -py));
	c2 = texture(tex, pos + vec2(  0, -py));
	c3 = texture(tex, pos + vec2( px, -py));
	c4 = texture(tex, pos + vec2(-px,   0));
	c5 = texture(tex, pos + vec2( px,   0));
	c6 = texture(tex, pos + vec2(-px,  py));
	c7 = texture(tex, pos + vec2(  0,  py));
	c8 = texture(tex, pos + vec2( px,  py));
	
	float delta1 = float((c3 + 2 * c5 + c8) - (c1 + 2 * c4 + c6));
	
	float delta2 = float((c6 + 2 * c7 + c8) - (c1 + 2 * c2 + c3));
	
	if (sqrt((delta1 * delta1) + (delta2 * delta2)) > 0.2) {
		return orig * 2 - (c1 + c2 + c3 + c4 + c5 + c6 + c7 + c8) * 0.125;
	} else {
		return corrected;
	}
}

**Comment by wm4** [comment]
1. put in a gist or so (gist.github.com)
2. add link to https://github.com/mpv-player/mpv/wiki/User-Scripts

Anyone should be able to edit the wiki.

Also, this looks suspiciously like unsharp mask, with an additional heuristic. If someone thinks thus heuristic should be added to mpv's unsharp mask filter, go ahead, but I think I'm too lazy.
