### ISSUE TITLE
mpv+ytdl takes long time to load

### ISSUE THREAD

**Issue by beew** [mpv-player/mpv#2426]
Hi, it takes a long time to load some videos using mpv with ytdl hook e,g https://www.youtube.com/watch?v=JdlHf32Dd_0

It seems that it takes a long time for buffering.  

```
mpv https://www.youtube.com/watch?v=JdlHf32Dd_0
Auto-loading profile 'vo.vaapi'
Playing: https://www.youtube.com/watch?v=JdlHf32Dd_0
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) 'DASH audio' (aac) (external)
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [vaapi] 1920x1080 vaapi
AV: 00:01:59 / 00:59:58 (3%) A-V:  0.000 Cache: 10s+73MB
```
OS is Ubuntu 15.04
This seems to happen with the latest update.
```
$ mpv --version
mpv git-c21c264 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Mon Oct 26 05:47:31 EDT 2015
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8-1~vivid
```

Thanks.

**Comment by wm4** [comment]
Use ffmpeg git master.

**Comment by ChrisK2** [comment]
Yep.

**Comment by beew** [comment]
Ok, removing mpv master and installing mpv-0.11.0 fixed it. Can't use ffmeg-master because that is going to break everything else and don't feel like compiling a local version at this point.

Thanks for the suggestion though.

**Comment by wm4** [comment]
Compiling a local version should be pretty easy with mpv-build.

**Comment by Zehkul** [comment]
Or use --ytdl-format=bestvideo[vcodec=vp9]+bestaudio/best

**Comment by beew** [comment]
zehkul,

No, no vp9, I need hardware decoding.

**Comment by beew** [comment]
wm4

I know it is not hard, but I already have two versions of ffmpeg (one system, and an old local version I don't remember what it is for. :)) Don't want to be bothered now.

**Comment by beew** [comment]
It seems that this only affects Youtube, other sites such as vimeo work just as before. Looking through the mpv change log and the suggestion to use ffmpeg master I think it is due to "removal of dash video hack"since ffmpeg now supports dash videos".

**Comment by wm4** [comment]
That's correct.

**Comment by wp9015362** [comment]
> @wm4 wrote:
>
>> @beew wrote:
>>
>> Looking through the mpv change log and the suggestion to use ffmpeg master I think it is due to the commit to "removal of dash video hack since ffmpeg now supports dash videos".
> 
> That's correct.

Could you please point to the FFmpeg commit which enabled FFmpeg to support DASH now?

Regards

**Comment by wm4** [comment]
4ab56667594842283dc5ae07f0daba2a2cb4d3af
