### ISSUE TITLE
--repeat option?

### ISSUE THREAD

**Issue by JaKXz** [mpv-player/mpv#2428]
I've looked through the docs and issues and can't find anything mentioning a `--repeat` option. It would be great for adding on to the `--playlist` option as well as individual files.

**Comment by wm4** [comment]
``--loop`` to loop the playlist, ``--loop-file`` to loop playlist entries.

**Comment by JaKXz** [comment]
Thanks.

**Comment by pavo976** [comment]
one more way:
```yml
while [ 1 ]; do mpv ./music-file.mp3; done
```

**Comment by garoto** [comment]
Winblows version:

`for /l %s in (1,1,9999) do @start "" /w mpv.exe --keep-open=no uma_delicia_vp8.webm`

**Comment by MarSoft** [comment]
@pavo976, this has a downside of not being able to stop the loop easily. Even using `Ctrl+C` you will have to press it several times to really stop the loop.

**Comment by Zocker1999NET** [comment]
Just if someone finds this issue. @wm4 answer seems outdated, currently `--loop` and `--loop-file` do the same, looping the first/current file. `--loop-playlist` was added to loop the playlist, see https://mpv.io/manual/master/#options-loop-playlist

**Comment by greatquux** [comment]
I've got a weird problem where I can't stop mpv from looping a file infinitely, even when I run "mpv --loop=no" or put "loop=no" in my ~/.config/mpv/mpv.conf file.  Also tried with --loop-file=no.  It just defaults to infinite looping, and the only way to stop it is to press L when it's playing to turn it off.  Ever heard of that before?

**Comment by wm4** [comment]
Post that file. Better yet, create a new issue.

**Comment by greatquux** [comment]
Happens on all files and files within playlists. I will create a new issue.

**Comment by greatquux** [comment]
nevermind and sorry to pollute the bug report, it's a problem with the silly mpris plugin https://github.com/hoyon/mpv-mpris i'll open up an issue with them. thanks!

**Comment by sae13** [comment]
how I can repeat one file when i listen to a playlist and like music playing

**Comment by Zocker1999NET** [comment]
@sae13 `L` is the default keyboard control for toggle loping current file.

**Comment by sae13** [comment]
thanks

‫در دوشنبه ۱۴ سپتامبر ۲۰۲۰‏، Felix Stupp‏ <notifications@github.com> نوشت:‏
> @sae13 L is the default keyboard control for toggle loping current file.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci4.googleusercontent.com/proxy/z7NajrA9eEZaMBr10gwmhPmFUT7IPBnf6dHem_JWmWyqw2MON4f4NrQ6sB_4huI1wGGdQsRuDgN4ybFL_f3ttBU5mvojWe28Q0Y5DFcIsTHZsSrIhhmQje5IRVKLBqtmBh42tamnTQyI4lVRsveW5D9UFMkCpNfIS6qiU_7vPPSvtBE6eAxQaqA9nCbTTQivP9mf6SV0oywMiwC5japuS6nvcGDJFao21XjJfZghlg=s0-d-e1-ft#https://github.com/notifications/beacon/AEDBLOTGSCLM7XXUVM3WT4DSFXCHLA5CNFSM4BS5ZC5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFE6T5YA.gif
>

-- 
به امید ایرانی آبادتر آزادتر و پیشرفته تر از امروز
بدرود

**Comment by UnixCro** [comment]
`--loop-playlist` 

I was looking for that all the time. Thanks to you all!
