### ISSUE TITLE
OS X: border cycle not implemented

### ISSUE THREAD

**Issue by ideepblue** [mpv-player/mpv#2430]
I try to set a shortcut with `cycle border` or `set border "yes"`, but it always doesn't work.

But I check documentation, the property border is RW.

So I just want to know if toggle window border could be implemented?

**Comment by paulguy** [comment]
Works for me in MATE in Linux.  I added `b cycle border` to my ~/.mpv/input.conf and hitting b works as expected.  Might help to know what OS you're using.

**Comment by Flat** [comment]
Works fine for me as well on Windows.

**Comment by wm4** [comment]
It's completely unclear whether the reporter failed to configure his input.conf correctly, or uses a window manager which doesn't handle this correctly, or if there's an actual bug.

**Comment by ideepblue** [comment]
Sorry for didn't give out details about OS and mpv.

I use Mac OS X 10.11.1, mpv 0.11.0. 

I am sure that input.conf is worked well. Because I add `b cycle fullscreen` to input.conf and hitting `b` works well. But when I set `b cycle border` to input.conf and hitting `b`, I got "Failed to increment property 'border' by 1" as below.

![image](https://cloud.githubusercontent.com/assets/462170/10861158/59f31700-7fcb-11e5-96d2-03561ec564ad.png)

**Comment by ideepblue** [comment]
Any suggestion? Is the problem of MacOSX window manager?

**Comment by wm4** [comment]
>Is the problem of MacOSX window manager?

No. It seems the OSX backend implements the ``--border`` option/config setting, but not switching it at runtime.

**Comment by ear** [comment]
Interesting tidbid: with --no-border the menu bar does not appear when you focus back to the mpv window.

**Comment by vitorgalvao** [comment]
@ideepblue I suggest changing the issue’s title to something like `OS X: border cycle not implemented` so the actual problem is described, which will make this harder to find, triage, and ultimately fix.

**Comment by SteveJobzniak** [comment]
Happens to me too, with macOS Sierra and:

```
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Nov 26 05:17:19 GMT 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.1
```

I can use "mpv --no-border" but I cannot cycle it at runtime. I see "border: yes" and "border: no" changing at runtime when I put "b cycle border" in input.conf, but the border doesn't actually change.

So yeah border switching at runtime on OS X doesn't seem to be implemented.
