### ISSUE TITLE
Little lagging when seeking first chapter

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#2431]
Dont know if this is bug. When try seek first chapter (page up), there's little lag. But after that seeking next chapters is smooth as usual

**Comment by lachs0r** [comment]
That likely depends on the file. If the chapter marks are not exactly on a key frame, mpv will use precise seeking, which can be slow.

**Comment by shinchiro** [comment]
Its not the problem with file. commit f8c57433b919d085b2674a7b3640be9beb2ab301 did not have this issue when seeking the first chapter for the same file.

Also..blank white flickered when starting to load video now

**Comment by wm4** [comment]
>Its not the problem with file. Even if a file does not have chapter, it still stuck before it said (unavailable). commit f8c5743 did not have this issue when seeking the first chapter for the same file.

Probably one of many problems with the new libass build. In fact I recommend @lachs0r to roll back for now.

>Also..blank white flickered when starting to load video now

>There's also problem with direct3d_shaders failed to initialize video in old's laptop with latest commit, while commit f8c5743 didn't have this problem

Nothing should have changed about vo_direct3d.

**Comment by shinchiro** [comment]
Actually forget about the chapter & libass because the problem is not with those..For some reason, first seek with keyboard is always a bit late. After that, future seek is fast as usual..Seeking with mouse on OSD has no problem..Not a big problem for me..Just wonder why it differs from previous build.

**Comment by shinchiro** [comment]
problem solved
