### ISSUE TITLE
Video turns black on pause, and when switching between fullscreen and windowed while paused.

### ISSUE THREAD

**Issue by txtsd** [mpv-player/mpv#2432]
This has been happening with the current HEAD.

[`mpv <file>` output](https://bpaste.net/show/c1b073c041fb)
[`mpv -v` output](https://bpaste.net/show/d479350e826f)

**Comment by wm4** [comment]
Does this happen with ``--no-config``?

**Comment by wm4** [comment]
Nevermind. It's a bug in the render logic with dumb-mode.
