### ISSUE TITLE
duplicate symbol _mp_vd_lavc_videotoolbox

### ISSUE THREAD

**Issue by Asher-** [mpv-player/mpv#2433]
Compiling on Mac OS 10.11.1:
=>  git clone https://github.com/mpv-player/mpv.git
=>  cd mpv
=>  ./bootstrap.py
=>  ./waf configure --enable-libmpv-shared
=>  ./waf build

Result:

[411/413] Linking build/mpv
duplicate symbol _mp_vd_lavc_videotoolbox in:
    video/decode/vd_lavc.c.13.o
    video/decode/videotoolbox.c.13.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Asher-** [comment]
Resolved by changing vd_lava.c:122 to:
```objective-c
  extern const struct vd_lavc_hwdec mp_vd_lavc_videotoolbox;
```
Appears to work appropriately, but someone with knowledge of the code base probably knows best.

**Comment by wm4** [comment]
Yes, that's the correct fix. Thanks.
