### ISSUE TITLE
Ignore output through direct.

### ISSUE THREAD

**Issue by c384mb** [mpv-player/mpv#2434]
0.12.0-git-5b7d0fb ignored commands --vo-defaults=direct3d_shaders, direct3d. Displays through open gl. The previous version does not ignore. Win. XP.
log -v --vo-defaults=direct3d_shaders

[   0.016][v][cplayer] Setting option 'profile' = 'pseudo-gui' (flags = 8)
[   0.016][v][cplayer] Setting option 'terminal' = 'no' (flags = 12)
[   0.016][v][cplayer] Setting option 'force-window' = 'yes' (flags = 12)
[   0.016][v][cplayer] Setting option 'idle' = 'once' (flags = 12)
[   0.016][v][cplayer] Setting option 'screenshot-directory' = '~~desktop/' (flags = 12)
[   0.019][v][global] config path: 'input.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/input.conf'
[   0.019][v][global] config path: 'input.conf' -/-> 'z:input.conf'
[   0.023][v][global] config path: 'input.conf' -/-> 'z:/mpv/input.conf'
[   0.023][v][input] Falling back on default (hardcoded) input config
[   0.024][v][osc] Loading script @osc.lua...
[   0.026][v][global] config path: 'scripts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/scripts'
[   0.026][v][global] config path: 'scripts' -/-> 'z:scripts'
[   0.026][v][global] config path: 'scripts' -/-> 'z:/mpv/scripts'
[   0.026][v][osc] loading mp.defaults
[   0.027][v][osc] loading @osc.lua
[   0.030][v][global] config path: 'lua-settings/osc.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/lua-settings/osc.conf'
[   0.030][v][global] config path: 'lua-settings/osc.conf' -/-> 'z:lua-settings/osc.conf'
[   0.030][v][global] config path: 'lua-settings/osc.conf' -/-> 'z:/mpv/lua-settings/osc.conf'
[   0.030][v][osc] lua-settings/osc.conf not found. 
[   0.033][v][cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[   0.033][v][cplayer] mouse_leave script-binding osc/__keybinding2
[   0.033][v][cplayer] , force]
[   0.034][v][cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[   0.034][v][cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[   0.034][v][cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[   0.034][v][cplayer] mouse_btn2 script-binding osc/__keybinding5
[   0.034][v][cplayer] mouse_btn0_dbl ignore
[   0.034][v][cplayer] shift+mouse_btn0_dbl ignore
[   0.034][v][cplayer] mouse_btn2_dbl ignore
[   0.034][v][cplayer] del script-binding osc/__keybinding6
[   0.034][v][cplayer] , force]
[   0.034][v][cplayer] Run command: enable-section, flags=0, args=[input, ]
[   0.035][v][cplayer] Done loading @osc.lua.
[   0.035][v][ytdl_hook] Loading script @ytdl_hook.lua...
[   0.037][v][global] config path: 'scripts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/scripts'
[   0.037][v][global] config path: 'scripts' -/-> 'z:scripts'
[   0.037][v][global] config path: 'scripts' -/-> 'z:/mpv/scripts'
[   0.037][v][ytdl_hook] loading mp.defaults
[   0.037][v][ytdl_hook] loading @ytdl_hook.lua
[   0.038][v][cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[   0.038][v][cplayer] Run command: disable-section, flags=0, args=[input]
[   0.038][v][cplayer] Done loading @ytdl_hook.lua.
[   0.039][v][global] config path: 'scripts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/scripts'
[   0.039][v][global] config path: 'scripts' -/-> 'z:scripts'
[   0.039][v][global] config path: 'scripts' -/-> 'z:/mpv/scripts'
[   0.039][v][global] config path: 'watch_later' -> 'C:\Documents and Settings\Администратор\Application Data/mpv/watch_later'
[   0.039][i][cplayer] Playing: h:\Downloads\Видео\HERO3%5Fhd1080.mkv
[   0.039][v][cplayer] Running hook: ytdl_hook/on_load
[   0.040][v][cplayer] Run command: hook-ack, flags=0, args=[on_load]
[   0.044][v][ifo] Opening h:\Downloads\Видео\HERO3%5Fhd1080.mkv
[   0.044][v][ifo/dvdnav] Opening h:\Downloads\Видео\HERO3%5Fhd1080.mkv
[   0.045][v][bdmv/bluray] Opening h:\Downloads\Видео\HERO3%5Fhd1080.mkv
[   0.045][v][file] Opening h:\Downloads\Видео\HERO3%5Fhd1080.mkv
[   0.046][v][file] Stream opened successfully.
[   0.046][v][demux] Trying demuxer: disc (force-level: normal)
[   0.047][v][demux] Trying demuxer: edl (force-level: normal)
[   0.047][v][demux] Trying demuxer: cue (force-level: normal)
[   0.047][v][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.047][v][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.047][v][demux] Trying demuxer: tv (force-level: normal)
[   0.047][v][demux] Trying demuxer: libass (force-level: normal)
[   0.047][v][demux] Trying demuxer: mkv (force-level: normal)
[   0.047][v][mkv] Found the head...
[   0.047][v][mkv] + a segment...
[   0.047][v][mkv] Parsing seek head...
[   0.047][v][mkv] |+ segment information...
[   0.047][v][mkv] | + timecode scale: 1000000
[   0.047][v][mkv] | + duration: 307.926s
[   0.047][v][mkv] | + segment uid 90 71 ae 85 cc 19 c7 c0 b0 11 38 51 5d f4 ac 70
[   0.047][v][mkv] |+ segment tracks...
[   0.047][v][mkv] | + a track...
[   0.047][v][mkv] |  + Track number: 1
[   0.047][v][mkv] |  + Track type: Video
[   0.047][v][mkv] |  + Video track
[   0.047][v][mkv] |   + Display width: 1920
[   0.047][v][mkv] |   + Display height: 1080
[   0.047][v][mkv] |   + Pixel width: 1920
[   0.047][v][mkv] |   + Pixel height: 1080
[   0.047][v][mkv] |  + Codec ID: V_MPEG4/ISO/AVC
[   0.047][v][mkv] |  + CodecPrivate, length 39
[   0.047][v][mkv] |  + Language: und
[   0.047][v][mkv] |  + Default duration: 33.367ms ( = 29.970 fps)
[   0.047][v][mkv] | + a track...
[   0.047][v][mkv] |  + Track number: 2
[   0.047][v][mkv] |  + Track type: Audio
[   0.047][v][mkv] |  + Audio track
[   0.047][v][mkv] |   + Sampling frequency: 44100.000000
[   0.047][v][mkv] |   + Channels: 2
[   0.047][v][mkv] |  + Codec ID: A_AC3
[   0.047][v][mkv] |  + Default duration: 34.830ms ( = 28.711 fps)
[   0.047][v][mkv] |+ found cluster
[   0.047][v][mkv] Deferring reading cues.
[   0.047][v][mkv] All headers are parsed!
[   0.047][v][mkv] Aspect: 1.777778
[   0.047][v][demux] Detected file format: Matroska
[   0.048][v][find_files] Loading external files in h:\Downloads\Видео\
[   0.048][v][global] config path: 'sub/' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/sub/'
[   0.048][v][global] config path: 'sub/' -/-> 'z:sub/'
[   0.048][v][global] config path: 'sub/' -/-> 'z:/mpv/sub/'
[   0.048][i][cplayer]  (+) Video --vid=1 (*) (h264)
[   0.048][i][cplayer]  (+) Audio --aid=1 --alang=eng (*) (ac3)
[   0.114][v][vo/opengl] Initializing OpenGL backend 'w32'
[   2.039][v][vo/opengl] GL_VERSION='3.0.11927 Compatibility Profile Context'
[   2.039][v][vo/opengl] Detected desktop OpenGL 3.0.
[   2.039][v][vo/opengl] GL_VENDOR='ATI Technologies Inc.'
[   2.039][v][vo/opengl] GL_RENDERER='AMD Radeon HD 7480D'
[   2.039][v][vo/opengl] GL_SHADING_LANGUAGE_VERSION='4.20'
[   2.042][v][vo/opengl] Loaded functions for 210/builtin.
[   2.042][v][vo/opengl] Loaded functions for 210/builtin.
[   2.042][v][vo/opengl] Loaded functions for 300/builtin.
[   2.042][v][vo/opengl] Loaded functions for 110/GL_EXT_unpack_subimage.
[   2.042][v][vo/opengl] Loaded functions for 300/GL_ARB_framebuffer_object.
[   2.042][v][vo/opengl] Loaded functions for 300/GL_ARB_vertex_array_object.
[   2.042][v][vo/opengl] Loaded functions for 300/GL_ARB_texture_float.
[   2.042][v][vo/opengl] Loaded functions for 300/GL_ARB_texture_rg.
[   2.042][v][vo/opengl] Loaded functions for 0/WGL_EXT_swap_control.
[   2.042][v][vo/opengl] 16 bit texture depth: 16.
[   2.042][v][vo/opengl] Display depth: R=8, G=8, B=8
[   2.042][v][vo/opengl] Testing user-set FBO format (0x805b)
[   2.042][v][vo/opengl] Create FBO: 16x16
[   2.042][v][vo/opengl/win32] display-fps: 75.000000
[   2.042][v][vo/opengl] Assuming 75.000000 FPS for framedrop.
[   2.043][v][vd] Container reported FPS: 29.970032
[   2.044][v][vd] Codec list:
[   2.044][v][vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[   2.044][v][vd] Opening video decoder lavc:h264
[   2.044][v][vd] Using software decoding.
[   2.044][v][vd] Detected 2 logical cores.
[   2.044][v][vd] Requesting 3 threads for decoding.
[   2.045][v][vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
[   2.046][v][ad] Codec list:
[   2.046][v][ad]     lavc:ac3 - ATSC A/52A (AC-3)
[   2.046][v][ad]     lavc:ac3_fixed (ac3) - ATSC A/52A (AC-3)
[   2.046][v][ad] Opening audio decoder lavc:ac3
[   2.046][v][ad] Requesting 1 threads for decoding.
[   2.046][v][ad] Selected audio codec: ATSC A/52A (AC-3) [lavc:ac3]
[   2.046][v][cplayer] Starting playback...
[   2.059][v][af] Audio filter chain:
[   2.059][v][af]   [in] 44100Hz stereo 2ch floatp
[   2.059][v][af]   [out] 44100Hz stereo 2ch floatp
[   2.060][v][af]   [ao] 44100Hz stereo 2ch floatp
[   2.060][v][ao] Trying audio driver 'wasapi'
[   2.060][v][ao/wasapi] requested format: 44100 Hz, stereo channels, floatp
[   2.119][e][ao/wasapi] Error setting up audio thread: <Unknown> (0x80040154)
[   2.123][v][ao] Trying audio driver 'dsound'
[   2.123][v][ao/dsound] requested format: 44100 Hz, stereo channels, floatp
[   2.131][v][ao/dsound] Output Devices:
[   2.256][v][ao/dsound] 0 Х𢨷 裳믢褐屠꣥𠊛   2.256][v][ao/dsound] 1 Realtek HD Audio output 
[   2.621][v][ao/dsound] DirectSound initialized
[   2.621][v][ao/dsound] Channel layouts:
[   2.621][v][ao/dsound]  - waveext
[   2.621][v][ao/dsound] result: stereo
[   2.621][v][ao/dsound] format float not supported defaulting to Signed 16-bit Little-Endian
[   2.621][v][ao/dsound] Samplerate:44100Hz Channels:2 Format:s16
[   2.621][v][ao/dsound] Buffersize:35280 bytes (200.000000 msec)
[   2.621][v][ao/dsound] primary buffer created
[   2.621][v][ao/dsound] secondary (stream)buffer created
[   2.621][v][ao/dsound] device buffer: 8704 samples.
[   2.621][v][ao/dsound] using soft-buffer of 8820 samples.
[   2.622][i][cplayer] AO: [dsound] 44100Hz stereo 2ch s16
[   2.622][v][cplayer] AO: Description: Windows DirectSound audio output
[   2.622][v][af] Adding filter lavrresample 
[   2.622][v][af] Audio filter chain:
[   2.622][v][af]   [in] 44100Hz stereo 2ch floatp
[   2.622][v][af]   [lavrresample] 44100Hz stereo 2ch s16
[   2.622][v][af]   [out] 44100Hz stereo 2ch s16
[   2.622][v][af]   [ao] 44100Hz stereo 2ch s16
[   2.646][v][vd] Using container aspect ratio.
[   2.647][v][vf] Video filter chain:
[   2.647][v][vf]   [vd] 1920x1080->0x0 yuv420p auto/auto CL=mpeg2/4/h264
[   2.647][v][vf]   [in] 1920x1080 yuv420p bt.709/limited CL=mpeg2/4/h264
[   2.647][v][vf]   [out] 1920x1080 yuv420p bt.709/limited CL=mpeg2/4/h264
[   2.647][i][cplayer] VO: [opengl] 1920x1080 yuv420p
[   2.647][v][cplayer] VO: Description: Extended OpenGL Renderer
[   2.654][v][vo/opengl/win32] requested window size larger than the screen
[   2.654][v][vo/opengl/win32] reset window bounds: 1:102:1151:669
[   2.661][v][vo/opengl/win32] move window: 5:125
[   2.661][v][vo/opengl/win32] resize window: 1143:642
[   2.661][v][vo/opengl] Resize: 1920x1080
[   2.661][v][vo/opengl] Window size: 1920x1080
[   2.661][v][vo/opengl] Video source: 1920x1080 (1920x1080)
[   2.661][v][vo/opengl] Video display: (0, 0) 1920x1080 -> (0, 0) 1920x1080
[   2.664][v][vo/opengl] Video scale: 1.000000/1.000000
[   2.664][v][vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[   2.664][v][vo/opengl] Video borders: l=0 t=0 r=0 b=0
[   2.664][v][vo/opengl] Testing user-set FBO format (0x805b)
[   2.664][v][vo/opengl] Create FBO: 16x16
[   2.664][v][vo/opengl] Texture for plane 0: 1920x1080
[   2.664][v][vo/opengl] Texture for plane 1: 960x540
[   2.664][v][vo/opengl] Texture for plane 2: 960x540
[   2.664][v][vo/opengl] Reinit rendering.
[   2.665][v][vd] set video colors output-levels=0 
[   2.670][v][vo/opengl] Resize: 1143x642
[   2.670][v][vo/opengl] Window size: 1143x642
[   2.671][v][vo/opengl] Video source: 1920x1080 (1920x1080)
[   2.671][v][vo/opengl] Video display: (0, 0) 1920x1080 -> (1, 0) 1141x642
[   2.671][v][vo/opengl] Video scale: 0.594271/0.594444
[   2.671][v][vo/opengl] OSD borders: l=1 t=0 r=1 b=0
[   2.671][v][vo/opengl] Video borders: l=1 t=0 r=1 b=0
[   2.674][v][vo/opengl] Create FBO: 960x540
[   2.675][v][vo/opengl] recompiling a shader program:
[   2.675][v][vo/opengl] [  1] // chroma merging
[   2.675][v][vo/opengl] [  2] vec4 color = vec4(texture(texture1, texcoord1).x, texture(texture2, texcoord2).x, 0.0, 1.0);
[   2.675][v][vo/opengl] [  3] color.xy *= 1.000000;
[   2.821][v][vo/opengl] Create FBO: 1920x1080
[   2.821][v][vo/opengl] recompiling a shader program:
[   2.821][v][vo/opengl] [  1] // chroma scaling
[   2.821][v][vo/opengl] [  2] #undef tex
[   2.821][v][vo/opengl] [  3] #define tex texture1
[   2.821][v][vo/opengl] [  4] vec2 pos = texcoord1;
[   2.821][v][vo/opengl] [  5] vec2 size = texture_size1;
[   2.821][v][vo/opengl] [  6] vec2 pt = vec2(1.0) / size;
[   2.821][v][vo/opengl] [  7] vec4 color = texture(tex, pos);
[   2.821][v][vo/opengl] [  8] color.a = 1.0;
[   2.821][v][vo/opengl] [  9] vec2 chroma = color.xy;
[   2.821][v][vo/opengl] [ 10] vec4 main;
[   2.821][v][vo/opengl] [ 11] {
[   2.821][v][vo/opengl] [ 12] vec4 color = texture(texture0, texcoord0);
[   2.821][v][vo/opengl] [ 13] color *= 1.000000;
[   2.821][v][vo/opengl] [ 14] main = color;
[   2.821][v][vo/opengl] [ 15] }
[   2.821][v][vo/opengl] [ 16] color = main;
[   2.821][v][vo/opengl] [ 17] color.yz = chroma;
[   2.821][v][vo/opengl] [ 18] // color conversion
[   2.822][v][vo/opengl] [ 19] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[   2.822][v][vo/opengl] [ 20] color.a = 1.0;
[   2.822][v][vo/opengl] [ 21] // scaler pre-conversion
[   2.822][v][vo/opengl] [ 22] // main scaling
[   2.873][v][vo/opengl] recompiling a shader program:
[   2.873][v][vo/opengl] [  1] #undef tex
[   2.873][v][vo/opengl] [  2] #define tex texture0
[   2.873][v][vo/opengl] [  3] vec2 pos = texcoord0;
[   2.873][v][vo/opengl] [  4] vec2 size = texture_size0;
[   2.873][v][vo/opengl] [  5] vec2 pt = vec2(1.0) / size;
[   2.873][v][vo/opengl] [  6] vec4 color = texture(tex, pos);
[   2.873][v][vo/opengl] [  7] color.a = 1.0;
[   2.873][v][vo/opengl] [  8] // scaler post-conversion
[   2.873][v][vo/opengl] [  9] // color management
[   2.881][v][global] config path: 'fonts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/fonts'
[   2.881][v][global] config path: 'fonts' -> 'z:fonts'
[   2.882][v][osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.0.6 (COMPLEX)
[   2.882][v][global] config path: 'subfont.ttf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/subfont.ttf'
[   2.883][v][global] config path: 'subfont.ttf' -/-> 'z:subfont.ttf'
[   2.883][v][global] config path: 'subfont.ttf' -/-> 'z:/mpv/subfont.ttf'
[   2.883][v][global] config path: 'fonts.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/fonts.conf'
[   2.883][v][global] config path: 'fonts.conf' -/-> 'z:fonts.conf'
[   2.883][v][global] config path: 'fonts.conf' -> 'z:/mpv/fonts.conf'
[   2.883][v][osd/libass] Setting up fonts...
[   2.884][i][osd/libass] Loading font file 'z:fonts/NotoNaskhArabic-Regular.ttf'
[   2.885][i][osd/libass] Loading font file 'z:fonts/NotoSans-Regular.ttf'
[   2.886][i][osd/libass] Loading font file 'z:fonts/NotoSansHans-Regular.otf'
[   2.902][i][osd/libass] Loading font file 'z:fonts/NotoSansJP-Regular.otf'
[   2.911][i][osd/libass] Loading font file 'z:fonts/NotoSansKR-Regular.otf'
[   2.920][i][osd/libass] Loading font file 'z:fonts/NotoSansSymbols-Regular.ttf'
[   2.938][v][osd/libass] Using font provider fontconfig
[   2.938][v][osd/libass] Done.
[   2.939][v][osd/libass] fontselect: (sans-serif, 400, 0) -> NotoSans, 0, NotoSans
[   2.943][v][vo/opengl] set SwapInterval(1)
[   2.943][v][cplayer] first video frame after restart shown
[   2.943][v][cplayer] Run command: ignore, flags=9, args=[]
[   2.945][v][vo/opengl] Create FBO: 1280x768
[   2.946][v][vo/opengl] recompiling a shader program:
[   2.946][v][vo/opengl] [  1] #undef tex
[   2.946][v][vo/opengl] [  2] #define tex texture0
[   2.946][v][vo/opengl] [  3] vec2 pos = texcoord0;
[   2.946][v][vo/opengl] [  4] vec2 size = texture_size0;
[   2.946][v][vo/opengl] [  5] vec2 pt = vec2(1.0) / size;
[   2.946][v][vo/opengl] [  6] vec4 color = texture(tex, pos);
[   2.946][v][vo/opengl] [  7] color.a = 1.0;
[   2.946][v][vo/opengl] [  8] // scaler post-conversion
[   2.954][v][vo/opengl] recompiling a shader program:
[   2.954][v][vo/opengl] [  1] vec4 color = texture(texture0, texcoord0);
[   2.954][v][vo/opengl] [  2] // color management
[   2.962][v][cplayer] playback restart complete
[   3.804][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.804][v][cplayer] Run command: enable-section, flags=0, args=[input, ]
[   3.813][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.823][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.829][v][osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
[   3.833][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.835][v][vo/opengl] recompiling a shader program:
[   3.835][v][vo/opengl] [  1] // OSD (libass)
[   3.835][v][vo/opengl] [  2] vec4 color = vec4(ass_color.rgb, ass_color.a * texture(osdtex, texcoord).r);
[   3.835][v][vo/opengl] [  3] // color management
[   3.846][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.854][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.864][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.874][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.891][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.899][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.909][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.919][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.929][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.939][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.949][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.959][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.985][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   3.995][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   4.005][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   4.025][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   4.035][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   4.045][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   4.055][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   4.157][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   4.333][v][cplayer] Run command: cycle, flags=9, args=[fullscreen, (NULL)]
[   4.415][v][vo/opengl/win32] save window bounds: 5:125:1143:642
[   4.415][v][vo/opengl/win32] reset window bounds: 0:0:1152:872
[   4.417][v][vo/opengl/win32] move window: 0:0
[   4.417][v][vo/opengl/win32] resize window: 1152:872
[   4.417][v][vo/opengl] Resize: 1152x872
[   4.417][v][vo/opengl] Window size: 1152x872
[   4.417][v][vo/opengl] Video source: 1920x1080 (1920x1080)
[   4.417][v][vo/opengl] Video display: (0, 0) 1920x1080 -> (0, 112) 1152x648
[   4.417][v][vo/opengl] Video scale: 0.600000/0.600000
[   4.417][v][vo/opengl] OSD borders: l=0 t=112 r=0 b=112
[   4.417][v][vo/opengl] Video borders: l=0 t=112 r=0 b=112
[   4.420][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.235][v][cplayer] Run command: disable-section, flags=0, args=[input]
[   5.452][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.453][v][cplayer] Run command: enable-section, flags=0, args=[input, ]
[   5.489][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.496][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.506][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.517][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.527][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.537][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.546][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.556][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.567][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.576][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.586][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.596][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.606][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.616][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.627][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.636][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.647][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.656][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.667][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   5.676][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[   6.445][v][cplayer] Run command: disable-section, flags=0, args=[input]
[  10.351][v][cplayer] Run command: cycle, flags=9, args=[fullscreen, (NULL)]
[  10.377][v][vo/opengl/win32] restore window bounds: 5:125:1143:642
[  10.377][v][vo/opengl/win32] reset window bounds: 1:102:1151:669
[  10.419][v][vo/opengl/win32] move window: 5:125
[  10.420][v][vo/opengl/win32] resize window: 1143:642
[  10.420][v][vo/opengl] Resize: 1143x642
[  10.420][v][vo/opengl] Window size: 1143x642
[  10.420][v][vo/opengl] Video source: 1920x1080 (1920x1080)
[  10.420][v][vo/opengl] Video display: (0, 0) 1920x1080 -> (1, 0) 1141x642
[  10.420][v][vo/opengl] Video scale: 0.594271/0.594444
[  10.420][v][vo/opengl] OSD borders: l=1 t=0 r=1 b=0
[  10.420][v][vo/opengl] Video borders: l=1 t=0 r=1 b=0
[  10.421][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[  10.422][v][cplayer] Run command: enable-section, flags=0, args=[input, ]
[  11.172][v][cplayer] Run command: disable-section, flags=0, args=[input]
[  11.462][w][input] No key binding found for key 'Alt+F4'.
[  11.463][v][cplayer] Run command: quit, flags=9, args=[0]
[  11.463][v][cplayer] EOF code: 6  
[  11.463][v][ad] Uninit audio filters...
[  11.463][v][ffmpeg] SWR: discarding 1000 audio samples
[  11.463][v][ad] Uninit audio decoder.
[  11.463][v][af] Removing filter lavrresample 
[  11.474][v][vd] Uninit video.
[  11.509][v][cplayer] finished playback, success (reason 3)
[  11.509][i][cplayer] 
[  11.509][i][cplayer] 
[  11.509][i][cplayer] Exiting... (Quit)
[  11.509][v][ytdl_hook] Exiting...
[  11.510][v][osc] Exiting...
[  11.512][v][ao/dsound] draining...
[  11.543][v][ao/dsound] DirectSound uninitialized
[  11.598][v][vo/opengl/win32] uninit

**Comment by wm4** [comment]
``--vo-defaults`` does not do what you think you do. Use ``--vo=direct3d`` etc.. 

I guess I'll improve the manpage.

**Comment by c384mb** [comment]
--vo=direct3d And this command ignores and displays through gl, log needed?

**Comment by wm4** [comment]
Sure.

**Comment by c384mb** [comment]
Yes. When output through opengl ignored temperature setting video driver in full screen, I use 10000 K and another sign that confirms this gl. Gl temperature setting in full screen 6500 K

**Comment by wm4** [comment]
So what's the problem here?

>I guess I'll improve the manpage.

On a second thought, I won't. ``--vo`` is documented first already.

**Comment by c384mb** [comment]
As in what? Does not work command --vo=direct3d shows video through gl. The error does not register. Don't believe?

**Comment by wm4** [comment]
No.

**Comment by c384mb** [comment]
I'm doing the right thing: create file called mpv.conf in the file put command: "--log-file=z:\log -v --vo=direct3d" put it in a folder mpv/mpv ? Start mpv.

**Comment by wm4** [comment]
Wrong syntax. User error.

**Comment by c384mb** [comment]
How correctly? Only one command: --vo=direct3d mpv runs but there is no picture and no see mpv. But mpv have in the Task Manager.

**Comment by c384mb** [comment]
Appears for one second and disappears from view but is present in tasks manager.

**Comment by kevmitch** [comment]
each option goes on one line in mpv.conf and does should not have "--" in front - that's only for command line.

**Comment by c384mb** [comment]
Last. Works as I wrote above in 0.12 and correctly with this commands (--vo=direct3d, --vo=direct3d_shaders in 0.11 from cmd or run task.
![6474637e76747](https://cloud.githubusercontent.com/assets/10123577/10859977/6bc36904-7f6b-11e5-88b6-81600226e64f.png)
![46e4te64647e77](https://cloud.githubusercontent.com/assets/10123577/10859988/8ff9f464-7f6b-11e5-93d5-a20422644455.png)

**Comment by kevmitch** [comment]
> Last. Works as I wrote above in 0.12 and correctly with this commands (--vo=direct3d, --vo=direct3d_shaders in 0.11 from cmd or run task.

I don't understand what your question is. Yes, ```--vo=direct3d``` should work from the command line. The equivalent in mpv.conf is just a line containing only ```vo=direct3d```

**Comment by c384mb** [comment]
Look: https://www.cubbyusercontent.com/pl/NewFilmM.7z/_ebe5bbc3619542faa6793350ab46e733
Password:rw53twetrw52t2w65$#@$%&^Tyuui3

**Comment by kevmitch** [comment]
> Look: https://www.cubbyusercontent.com/pl/NewFilmM.7z/_ebe5bbc3619542faa6793350ab46e733
Password:rw53twetrw52t2w65$#@$%&^Tyuui3

To sumarize, 0.11 works as expected, but with 0.12 mpv runs, but fails to produce a window. It seems like the vo is failing to initialize. 

When using the command line, you should generally run ```mpv.com```, not ```mpv.exe``` so we can actually see the terminal output. Preferably paste the output in text format somewhere like http://sprunge.us/

**Comment by c384mb** [comment]
mpv.com тhe same only works cmd mpv is not visible, but the mpv is running. Me need more info http://sprunge.us/ didn't understand. Write text that displays in the cmd? Image not show?

**Comment by kevmitch** [comment]
from IRC:

>18:01 < avih> [cplayer] VO: Description: Direct3D 9 Renderer
>18:01 < avih> [vo/direct3d/win32] reset window bounds: 592:307:736:443
>18:01 < avih> [vo/direct3d/win32] move window: 600:338
>18:01 < avih> [vo/direct3d/win32] resize window: 720:404
>18:01 < avih> [vo/direct3d] Creating window failed.
>18:02 < avih> [cplayer] Could not initialize video chain.

Are you seeing something like that?

**Comment by c384mb** [comment]
https://www.cubbyusercontent.com/pl/text.txt/_f74d988f2014490ba15833a946c34a1e

**Comment by kevmitch** [comment]
so, yes

**Comment by c384mb** [comment]
Something else from me?

**Comment by kevmitch** [comment]
no, that's all from you. This looks like a bug.
