### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [mpv-player/mpv#2435]
Would you like to add more error handling for return values from functions like the following?
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action.") ⇒ [vt_switcher_init](https://github.com/mpv-player/mpv/blob/739452361f5e1de1067ca44c0bb01e95e1c075d9/video/out/drm_common.c#L47)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [audio_in_init](https://github.com/mpv-player/mpv/blob/739452361f5e1de1067ca44c0bb01e95e1c075d9/stream/audio_in.c#L30)

**Comment by wm4** [comment]
@elfring: fixed the strdup failure case, but see the commit message.

@rr-: I think vt_switcher needs some fixes:
- maybe check sigaction return value
- if a signal is registered, unregister it on exit, or a signal will write into a random FD (!!)
- on start, check if something else already installed the signal handler, and bail out if it did
