### ISSUE TITLE
Add support to other video format to MMAL codec

### ISSUE THREAD

**Issue by Groggy** [mpv-player/mpv#2438]
From what I understand, MMAL codec only support H264 video decoding. But MMAL can decode other video formats like VC-1, MPEG-2 or MPEG-4.

This could be a huge improvement on platforms like Raspberry PI because software decoding for those formats is simply not an option.

**Comment by wm4** [comment]
MPEG-2 is supported in ffmpeg's mmal decoder. VC-1 and MPEG-4 need a license key and haven't been added yet.

**Comment by Gusar321** [comment]
Actually, it's mpeg2 that requires a license key (as does vc1), mpeg4 is free.

**Comment by wm4** [comment]
mpeg2 and vc1 was added.
