### ISSUE TITLE
Time interpolation seems not to be effective

### ISSUE THREAD

**Issue by mauromol** [mpv-player/mpv#2440]
I'm currently running mpv version git-532f05b from the Ubuntu package 2:0.12.0+git installed from the PPA at: https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests
I would really like to make the time interpolation ("smoothmotion") feature work, but whichever combination of options I try, it seems like it's not effective: my video stutters, either when reproduced in a window, or when reproduced full-screen. As a reference, I use "my own eye" and compare the same video played with other players (that do not do any time interpolation) or through an set-top box on my Sharp TV (which instead is a 100 MHz LED TV with the feature that is usually called "movie mode", "natural motion" or alike). I consider myself very sensitive to fluid motions, so I don't think it's just a wrong feeling, especially when I see the same video being very smooth on my Sharp TV.

Let's go to the facts. I'm running mpv on my system, a HP notebook with Haswell i5 CPU (using the embedded Intel graphics). It's running Linux Mint 17.2 KDE edition (based and on par with current Ubuntu 14.04). The Linux kernel I'm using is 3.19.0-30-generic #33~14.04.1-Ubuntu SMP for amd64 architecture.

My mpv config file is `~/.config/mpv/mpv.conf` and contains the following:

```
vo=opengl-hq:interpolation
hwdec=vaapi
hwdec-codecs=h264,vc1,wmv3,mpeg2video
ao=pulse
display-fps=60
swapinterval=1
sub-forced-only
keep-open
force-window
```

My KDE is configured in this way: the compositor type is OpenGL 3.1, the QT graphics system is Raster, VSync is set to "redraw the whole scene".

What I'm trying to play right now is a 23.976100 fps AVI video (Xvid codec) on my notebook display running at 60 Hz.

Please let me know if you need more information to try to understand if something can be done.

**Comment by Ricardo1991** [comment]
Quoting a madVR [guide here](http://wiki.jriver.com/index.php/MadVR_Expert_Guide#Smooth_Motion)

> Smooth Motion is not, is a frame interpolation system—it will not introduce the “soap opera effect” like you see on 120Hz+ TVs, or reduce 24p judder.
Smooth Motion is designed to display content where the source framerate does not match up to any of the refresh rates that your display supports. For example, that would be 25/50fps content on a 60Hz-only display, or 24p content on a 60Hz-only display.


MPV's smoothmotion is a copy of madVR, so that's that

**Comment by lamarpavel** [comment]
Are you sure your intel GPU is capable of rendering opengl-hq with interpolation using the mesa version of kernel 3.19? Particularly the fbo-format can cause lots of stuttering when set to float on intel GPUs and older mesa drivers.

**Comment by wm4** [comment]
We have our own explanations: https://github.com/mpv-player/mpv/wiki/Interpolation

Also, overriding display-fps will almost certainly give you slightly wrong results, don't know how much it matters though.

**Comment by mauromol** [comment]
@Ricardo1991 and @wm4 I understand that smoothmotion is not the same as motion-based interpolation, but if the final result is as non-smooth as the normal 3:2 pulldown technique, what is all about? I mean, what I would have expected is something that is somewhat middle way between the result of my TV interpolation algorithm and no interpolation... Instead, what I see is essentially no benefit at all. I already tired to remove display-fps, but I see no actual difference.

@lamarpavel Honestly, I don't know. I'm using the default (open-source) drivers for my Intel chipset (i915 driver I think). I don't even know if there's something else available (I know Intel does not provide any proprietary drivers). In case, what may I try?
I read about fbo-format, but since I'm not specifying it isn't the default rgba16 applied (which is non-float, I guess)?

**Comment by mauromol** [comment]
Couldn't my problem be related to vsync not working correctly due to the KDE compositor interfering? Is there something I can check to determine if this is the case?

**Comment by wm4** [comment]
Many things could ruin it. You should try enabling display sync (``--video-sync=display-resample`` or ``--video-sync=display-desync``). If it behaves erratic, it's safe to say mpv isn't achieving any form of locking to the monitor's refresh rate.

**Comment by mauromol** [comment]
I tried both `--video-sync=display-resample` and `--video-sync=display-desync`: how can I determine if it behaves erratic? If you mean that something clearly wrong should happen on video playback, I would say that it isn't my case, because I couldn't notice any actual difference after changing that option.

**Comment by wm4** [comment]
Make sure whether it enabled itself (might depend on the file etc.). You can see on the terminal status line. It will show additional things there. If that works, look at the A/V sync field. If it jitters around heavily by more than 0.001, there's something wrong.

**Comment by kevinlekiller** [comment]
The interpolation is too much for my system (i3-5010u, my limitation is the GPU, the TDP goes from ~0.8 to 3.5 when I enable interpolation according to turbostat and GPU usage goes from ~25% to 99% in intel_gpu_top), so I use the `--video-sync=display-resample` with a script to change the monitor refresh rate / `--speed` and get pretty good results.

The  `--video-sync=display-resample` does increase the CPU load considerably(CPU TDP goes from ~4 to ~10 watts), but it is still under the limits of the CPU.

**Comment by wm4** [comment]
>The --video-sync=display-resample does increase the CPU load considerably(CPU TDP goes from ~4 to ~10 watts), but it is still under the limits of the CPU.

That's odd. It shouldn't increase CPU not that much. It does put more load on the GPU, if the video framerate is different from the monitor's.

**Comment by kevinlekiller** [comment]
You're right, I was testing a bunch of videos so I got things mixed up, I retested, it's not a huge difference at all, I'd say it's even almost identical.

I think it's because I was testing VP9 (no hw accel) vs h264.

**Comment by wm4** [comment]
>it seems to get rid of a visible hitching that happens once in a while, which is great.

That's what it's supposed to do. It will also give interpolation better timing to work with.

**Comment by lamarpavel** [comment]
@mauromol 
>I don't even know if there's something else available (I know Intel does not provide any proprietary drivers). In case, what may I try?

The open source drivers of intel are the only ones available and they are fine in general, but they build ontop of the mesa stack, which had some major developments in the past two years, most recently the jump to OpenGL 4 with kernel 4.2. So using newer mesa drivers than those provided with kernel 3.19 could have a noticable effect on performance, depending on the implementation of mpvs filters (I haven't looked at the GLSL code, but there are more things to consider than the #version).

In general though, interpolation from 23.976 to 60 FPS is no joke, my i5 ivy bridge GPU can't handle that. You are correct about the default for fbo-format though, it's rgba16 (integer) by default.

**Comment by mauromol** [comment]
@lamarpavel 
My i5 is a Haswell one, so I think it should handle that too. In any case, I tried to change the fbo-format parameter to rgba32f and it seems to work fine (I would say even better than before, from a video quality point of view, but I can't quantify at all (maybe it's just a feeling). What I can say for sure is that neither rgb32f nor rgb16f (without "a") seem to work properly, because errors are printed in the terminal when mpv tries to set up a shader in the GPU (sorry if I use wrong terms, I'm not a gfx expert).

@wm4 
I will check the terminal status line as soon as possible, thank you. In any case, if I understand it correctly, `--video-sync=display-resample` is something I would want to keep in my "stable" config file for best video quality...

**Comment by lamarpavel** [comment]
I have the same behaviour on my intel GPU regarding textures without alpha, mpv needs to be set to rgbaX or rgbaXf.
Your haswell GPU might be a bit faster or a lot (if it is an iris) than the ivy bridge, but the drivers you have might not be optimized for the computation that interpolation is performing and the step from 23.976 to 60 is honestly quite huge. It's been some time since I wrote GLSL shaders, but based on the shader code I'd say the time interpolation requires more computation than say any shader you would find in a game from the 2004-2006 era (eg. HL2).

**Comment by kevinlekiller** [comment]
I've been testing `--video-sync=display-resample` CPU/GPU usage on more files, on some files, it makes barely any difference in CPU / GPU usage, but on some files it makes the GPU usage very high and the video jerks around.

I have to head out, but will do more tests later.

**Comment by wm4** [comment]
This is going to depend on video resolution, framerate, and bitness.

**Comment by mauromol** [comment]
@wm4 
I tested better with `--video-sync=display-resample`: my status line is something like this:
    [statusline] AV: 00:00:49 / 00:58:31 (1%) A-V:  0.010 DS: -0.00945% Cache: 10s+73MB
The A-V field fluctuates indeed. After letting the video play for some dozen seconds, it is under 0.010, but it may assume various values between 0.000 and 0.007 (it's hard to distinguish, values change rapidly). The DS field, instead, is more stable and is mostly +0.11570%, rarely changing to +0.24084%.

With `--video-sync=display-desync` the A-V value slowly grows, but if I understand the meaning of that option well, I would say it's normal... isn'it?

What do you think?

**Comment by wm4** [comment]
What driver? Fullscreen or windowed? What display FPS does it report (see ``/mpv file.mkv -v |grep FPS``)?

>With --video-sync=display-desync the A-V value slowly grows, but if I understand the meaning of that option well, I would say it's normal... isn'it?

Yes. But if ``display-resample`` fluctuates, this should fluctuate as well, or there's a different problem.

**Comment by mauromol** [comment]
Driver: opengl-hq
Fullscreen or windowed: it's the same, I see no difference when the video is played windowed or fullscreen
I'll try to better explain what I see: with `--video-sync=display-resample` the video starts with DS: +0.11570% and A-V -0.039, that the A-V (which fluctuates continuously) slowly goes down until it reaches 0.000, then the DS is changed to +0.24084% and A-V fluctuates around values within -0.008 and 0.000. When it reaches 0, the DS is changed again to +0.11570% and A-V again fluctuates between -0.008 and 0.000, then DS is changed again to +0.24084% and so on.
If I grep for "FPS" I see this:

    [vo/opengl-hq/x11] Display 0 (eDP1): [0, 0, 1366, 768] @ 60.009178 FPS
    [vo/opengl-hq/x11] Current display FPS: 60.009178
    [vo/opengl-hq] Assuming 60.009178 FPS for framedrop.
    [vd] Container reported FPS: 23.976101

These numbers seem correct to me.

With `display-desync`, the DS value still fluctuates, but the mean value instead of decreasing down to 0, to continuously slowly grows up.

**Comment by wm4** [comment]
This sounds normal. It will never get the correct speed, and will always drift. It's only a problem if it fluctuates heavily and by a large amount.

**Comment by mauromol** [comment]
So, do you think vsync is working correctly on my system? And then that the judder I see even with smoothmotion enabled is normal?

**Comment by wm4** [comment]
This is really hard to tell.

**Comment by mauromol** [comment]
In any case, I have a question, if I may ask...
The quoted madVR guide says that smoothmotion, as it is implemented, does not reduce the 24p judder. However, if I had a 24 Hz monitor and a working vsync, I would expect NOT to see judder on a 24p movie, wouldn't I? I'm not a video and graphics expert, but I remember from the old '90s those DOS demos in which things were drawn on the screen with vsync enabled and they were exceptionally fluid. So, why shouldn't be 24p video fluid on 24 Hz or on 60 Hz with smoothmition interpolation enabled?
Is this problem related to the original filmed material (that is: the source video frames are themselves already "broken")?

What I'm seeing even with smoothmotion enabled is particularly visible on the edges of an object moving fast on a uniform background (for instance, a fast camera panning of a bell tower with the sky as a background): they are not moving smoothly, but they are rather jerking and showing a tearing effect (not on the whole frame, just on the fast-moving object edges!). Is this phenomenon what you call "judder" or something related to it?

**Comment by wm4** [comment]
>they are not moving smoothly, but they are rather jerking and showing a tearing effect (not on the whole frame, just on the fast-moving object edges!). Is this phenomenon what you call "judder" or something related to it?

I'd say this sounds like interlacing related problems?

**Comment by mauromol** [comment]
I tried to enable the deinterlacer with "d" key, but nothing changes for this.
By the way, if I use `-vf=help`, the `vavpp` filter is not listed, in fact setting `--vf=vavpp=deint=bob` produces an error:

    Option vf: vavpp doesn't exist.
    Error parsing option vf (option could not be parsed)
    /home/mauro/.config/mpv/mpv.conf:19: setting option vf='vavpp=deint=bob' failed.

However, I'm using the opengl-hq driver and `--hwdec=vaapi`, so I expected this to be available... Am I doing something wrong?

**Comment by wm4** [comment]
The video could just be badly processed by whoever created it, in which case a deinterlacer wouldn't help much. Maybe you could upload a sample, or maybe a screenshot, so we can see what it looks like?

>By the way, if I use -vf=help, the vavpp filter is not listed, in fact setting --vf=vavpp=deint=bob produces an error:

You must be using an older mpv version and an older libva version. mpv git master requires a libva that always includes the VPP API.

**Comment by mauromol** [comment]
`mpv --version` yields:

    mpv git-532f05b (C) 2000-2015 mpv/MPlayer/mplayer2 projects
     built on Thu Oct 29 13:56:12 UTC 2015
    ffmpeg library versions:
       libavutil       55.5.100
       libavcodec      57.12.100
       libavformat     57.11.100
       libswscale      4.0.100
       libavfilter     6.14.101
       libswresample   2.0.100
    ffmpeg version: N-76353-g54de179

Isn't it up-to-date?

**Comment by mauromol** [comment]
Here is a sample:
https://dl.dropboxusercontent.com/u/55072601/example.mkv
Have a look at 00:00:02-00:00:04, look at the left edge of the rightmost bell tower: I see a sort of "tremor" effect on it. Or else, look at the lion head on the right edge of the rightmost bell tower, moving over the sky background.
This is just an example of what I consider a non-smooth motion of fast moving objects..

**Comment by mauromol** [comment]
Just tried an even newer mpv version (which unfortunately does not indicate the git commit), but still `--vf=help` does not list vavpp filter:

    mpv UNKNOWN (C) 2000-2015 mpv/MPlayer/mplayer2 projects
     built on Thu Nov  5 06:06:35 UTC 2015
    ffmpeg library versions:
       libavutil       55.5.100
       libavcodec      57.14.100
       libavformat     57.14.100
       libswscale      4.0.100
       libavfilter     6.14.101
       libswresample   2.0.100
    ffmpeg version: N-76467-ga8b254e

**Comment by wm4** [comment]
The video is not interlaced (but may have been deinterlaced). It also looks relatively ok to me. The resolution is a bit low. In my opinion, interpolation improves it slightly.

**Comment by mauromol** [comment]
So I understand this is the best result I can achieve with mpv. This is at least comforting that there is not something wrong with my own configuration.

By the way, now I'm using the following mpv version, but I don't have the vavpp filter yet:

    mpv git-fb19371 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
     built on Fri Nov  6 02:36:22 UTC 2015
    ffmpeg library versions:
       libavutil       55.5.100
       libavcodec      57.14.100
       libavformat     57.14.100
       libswscale      4.0.100
       libavfilter     6.14.101
       libswresample   2.0.100
    ffmpeg version: N-76467-ga8b254e

Any idea on what may be wrong?

**Comment by haasn** [comment]
For the interpolation stuff, you should upload a log with ```--msg-level=vo=debug```.

Also, you chould try using a different algorithm, e.g. ```-vo opengl-hq:interpolation:tscale=mitchell```. There are some implementation differences between them, and the default trades effectiveness for reducing the prominence of artifacts. (Which manifest in the form of what seems like “halos” around moving objects)

> However, if I had a 24 Hz monitor and a working vsync, I would expect NOT to see judder on a 24p movie, wouldn't I?

Correct.

> So, why shouldn't be 24p video fluid on 24 Hz or on 60 Hz with smoothmition interpolation enabled?

It should be. Although note that interpolation will never be comparable to a real 24 Hz device because interpolation approximates smoothness at the cost of image artifacts (due to blending multiple images together).

> they are not moving smoothly, but they are rather jerking and showing a tearing effect (not on the whole frame, just on the fast-moving object edges!). Is this phenomenon what you call "judder" or something related to it?

That's basically impossible to answer from your question alone. Try providing a screenshot of the artifacts. (Interpolation artifacts would show up on screenshots, as would interlacing artifacts - though note that mpv's internal screenshot tool does not suffice for this purpose as it always captures “perfect” frames, rather than blended/intermediate frames)

> I see a sort of "tremor" effect on it.

Tremor is a bad word because it's ambiguous. There's a strong technical distinction between ‘stutter’ and ‘judder’, as they are very different problems with different solutions. The best thing to do is to learn about the differences between the terms and figure out which one it is you're seeing.

Stutter is just the case when the framerate is low, for example only receiving one screen update every 200ms gives rise to stuttery motion. (As would viewing a dark room under a strobe light)

Judder is the specific phenomenon of the *gaps between updates* being of different lengths. For example if you alternate between 200ms and 100ms. This gives rise to an unpleasant “back and forth” motion, where the speed of the object seems to be constantly alternating.

The smoothmotion technique (tscale=oversample in mpv) only tries to eliminate judder, it completely ignores stutter. The other techniques (e.g. tscale=mitchell) do combat stutter as well, but not in a very effective way. (Formally: They don't try to identify motion vectors)

One of these days I'm going to make a 60 Hz video file that demonstrates all of these artifacts on “real” video frames..

**Comment by wm4** [comment]
>There's a strong technical distinction between ‘stutter’ and ‘judder’, as they are very different problems with different solutions. 

You can define it this way, but in normal language use they can be exchangeable, IMO.

**Comment by haasn** [comment]
The distinction is between the types of artifacts, not necessarily the words I use to describe them. I just keep my terminology consistent so others can understand what I'm saying, and what the mpv code is doing. Plus, this seems to be the technical definition of ‘judder’ already, if anything then ‘tsutter’ is a more loose term in general.

**Comment by mauromol** [comment]
@haasn 
Thanks a lot for your detailed explanation. I think what I meant by "tremor" is more similar to "stutter" rather than "judder", then. I provided a sample of the video some messages above, with the object details I'm concentrating on, maybe you can see the phenomenon yourself... Anyway, I will try to see if taking screenshots can give an idea of what I'm observing.

I know about the halo effect, I can also bear some of it in certain scenarios if the smoothness of the scene is highly improved: after all, my TV has the same problem (although I must admit that it's quite limited, they did a good job at Sharp... and I bought it around 5 years ago already!). I will try the mitchell algorithm to see how it performs on that same scene, thank you!

I will also upload a debug log for the missing filter problem.

**Comment by mauromol** [comment]
I tried the mitchell algorithm but I couldn't see any substantial difference. With spline64 and lanczos algorithms I see a lot of halo effect, while with robidoux and robidouxsharp the motion is a bit smoother but more blurried.
After some trials to take a significant screenshot with KSnapshot (most screenshots where frame-perfect), I was able to capture this one: https://dl.dropboxusercontent.com/u/55072601/Screenshot%20inerpolation.png
What do you think about it?

**Comment by mauromol** [comment]
Here is the debug output regarding the missing vavpp filter: https://dl.dropboxusercontent.com/u/55072601/mpv-debug-output.txt

**Comment by wm4** [comment]
>Here is the debug output regarding the missing vavpp filter: https://dl.dropboxusercontent.com/u/55072601/mpv-debug-output.txt

libva (aka vaapi) is simply not compiled in.

**Comment by haasn** [comment]
That screenshot demonstrates the ghosting artifacts I was talking about; which are an unavoidable side effect of frame blending.

Now the question is whether or not those trailing halos were the “tearing”​/“tremor” you were referring to, or whether that's an effect not immediately obvious on the image.

**Comment by mc4man** [comment]
@mauromol 
You can have vaapi again, due to circumstances relayed via mail didn't add libegl1-mesa-dev which  apparently is now required for vaapi.
Note that in 14.04 with default mesa 10.x you'll be best served with hwdec=auto & as far as vo= , limited choices.
If you use opengl/opengl-hq you'll get vaapi-copy which sucks as far as cpu. If you use a vo of vaapi it's good on cpu but can exhibit fullscreen tearing.
Ultimately if sticking with 14.04 then get mesa-11 at some point & build mpv yourself, likely better with gcc-5 or just go to 16.04 instead where opengl/vaapi works well with low cpu use.
(the other ppa I have will stop at 0.11+some git commits - it allows vaapi with opengl/opengl-hq & works just fine with very  cpu & no tearing

If you have an optimus card then I'd use nvidia instead, there is a workaround to tearing when implementing via nvidia-prime in a compositing env.

**Comment by mauromol** [comment]
@haasn 
That screenshot was taken with tscale=oversample, which doesn't produce much halo effect to my eyes. By "halo effect" I mean the presence of rings/halos around fast moving edges and shapes.
Instead, if I set tscale=lanczos, for instance, I see quite a lot of it.
This is a screenshot taken with tscale=lanczos which demonstrates what I mean:
https://dl.dropboxusercontent.com/u/55072601/Screenshot%20interpolation%202.png
As you can see, in this screenshot the "ghosting" effect is mainly around the edges of the foreground tower and around the shapes of the stone lion head on the right
In the first screenshot, instead, the whole scene looks "blurried".
Anyway, probably you're right to say that, although different, both screenshots are due to the same cause and probably the first screenshot does not demonstrates anything about the "stuttering" I am referring to when I say that the motion is not "smooth". After all, it's quite hard to capture this in a still frame.
For curiosity, did you try to play the above video sample? Do you see the foreground tower move smoothly from left to right? Or do you see the edges (especially the left one, but also the lion head on the right) stuttering over the background?

@mc4man 
Thanks a lot for your feedback. I look forward to testing any new build with vaapi support back. If I understand it correctly, once it is available, on my 14.04 based distro I will just be able to use hwdec=vaapi-copy with vo=opengl-hq, or else hwdec=vaapi with vo=vaapi (which is however discouraged). I will try to see if vaapi-copy is worth or not, otherwise I will fall back to software decoding. I don't think I will upgrade right now to a new distro because of this (also, Mint is currently stuck at a 14.04 base).

**Comment by mauromol** [comment]
@haasn 
Probably I'm a bit crazy :-D I took a short video with my phone while my laptop was playing that video. Here it is: https://dl.dropboxusercontent.com/u/55072601/VID_20151114_151750.mp4
Here the "stuttering" effect is probably a bit amplified by the fact I'm filming with the phone, but honestly not that much. Can you see the left edge of the moving tower how it "stutters"?

**Comment by voltmtr** [comment]
>Here it is: https://dl.dropboxusercontent.com/u/55072601/VID_20151114_151750.mp4
>Can you see the left edge of the moving tower how it "stutters"?

@mauromol That part looks way more jumpy than how it plays on my system. Maybe you can post a debug log during you play that example video to see if your interpolation queue is underrun?

Also I would try disabling KDE compositor entirely and use a simple vo config like vo=opengl:interpolation:tscale=oversample to see if it makes a difference.

**Comment by mauromol** [comment]
@voltmtr 
As I said, in the video taken with the phone the effect is amplified, but it explains what I mean by "stuttering".
I tried to disable the desktop effects and also to change the compositor to XRender (from OpenGL), but nothing appreciable changed. The only thing I noted is that if I leave effects on with XRender, I have a heavy tearing effect on the video.
Changing to just opengl driver + time interpolation doesn't make a difference for the stuttering problem.
Here is a debug output taken with opengl-hq driver, tscale=oversample, that is the setup I'm usually using. I got it with --msg-level=all=debug.
https://dl.dropboxusercontent.com/u/55072601/mpv-debug-output2.txt.zip

I'm starting to think that this may be due to a non-uniform blurring (ghosting?) effect on the fast moving edges. By "non-uniform" I mean that its extend varies from frame to frame, and hence the "tremor"/"stuttering" effect...

**Comment by kevinlekiller** [comment]
@mauromol

I found `vo=opengl:interpolation` + `video-sync=display-resample` to work good together, although not perfect.

I have better results using a script I wrote (it changes the mpv speed setting and changes the display frequency - I add a 72hz mode using xrandr on startup with `~/.xprofile`). I use `video-sync=audio` with this method because `video-sync=display-resample` introduces some kind of stutter unfortunately, I've been trying to figure out why (by messing around with tons of settings) because it should be the inverse, but with `video-sync=audio` it looks perfect to my eyes.

I'm also using KDE, with the compositor enabled, Opengl 3.1 for the backend, Glx for the interface, vsync it set to automatic.

I have `Option "AccelMethod" "sna"` and `Option "TearFree" "True"` in xorg.conf (Intel GPU).

With the above stuff I've mentioned, I get no tearing/judder.

**Comment by voltmtr** [comment]
@mauromol
>I tried to disable the desktop effects and also to change the compositor to XRender (from OpenGL), but nothing appreciable change
> Changing to just opengl driver + time interpolation doesn't make a difference for the stuttering problem.
Those rule out your iGPU being too weak. Skimming your log, I don't see anything out of ordinary  with respect to mpv interpolation in your system.

>I'm starting to think that this may be due to a non-uniform blurring (ghosting?) effect on the fast moving edges
I think the effect you see is kind of non uniform in that tower scene because how the camera moves, bottom of the tower move faster than the top causing that.

Frame blending based interpolation smoothness has its limits, for a TV like vector based motion interpolation you can try enabling vapoursynth and mvtools scripts.

**Comment by mauromol** [comment]
@kevinlekiller 
Thanks for your suggestions. Unfortunately I tried all your settings, with no luck regarding this problem. On the other hand, my embedded display does not have any refresh rate other than 60Hz, 40Hz and 56Hz (this one only in 800x600), so no exact multiple of 24... Creating a xorg.conf file and adding TearFree=true did not help either (after all, I do not have any tear effect in any case). SNA was already automatically enabled.

@voltmtr 
I think I must give up, in the sense that my setup is ok, I'm just hitting the limits of this kind of time interpolation. I would say it's better than no time interpolation at all (at least when compared with mpv itself), but I really hoped I could get a TV-like effect on Linux, but it seems like (almost?) impossible. The script-based solutions you propose are currently beyond my skills.

**Comment by kevinlekiller** [comment]
@mauromol Yeah, you need to make a mode , which your display might support since it supports 40 and 56, something like 48hz, otherwise you will still get stuttering or judder, even something like 50 will work, because the script adjusts the speed, it would make the video play 4% faster. Every display I've tried so far can do 72. You can make a mode using cvt (cvt12 if you need reduced blanking) then you use xrandr to add it.

I've tried the mvtools / vapoursynth solution but it's way too CPU intensive, and drops frames like crazy.
