### ISSUE TITLE
mpv + youtube-dl on Windows?

### ISSUE THREAD

**Issue by wp9015362** [mpv-player/mpv#2448]
Hello,

unfortunately [MPC-HC does not seem to support YouTube DASH videos](https://trac.mpc-hc.org/ticket/5498).

However, [mpv seems to support it now](https://github.com/mpv-player/mpv/commit/78caf6ae8634b9fe9589187d8febb927dce2ddeb).

But how do you use mpv with youtube-dl on Microsoft Windows?

How do you tell mpv where the youtube-dl.exe is located and such? And would FFmeog also need to be installed?

It would be really nice if someone could help out, because, if mpv could be used to play YouTube DASH videos on Windows, that would be great.

Anyone here who could help?

Regards

**Comment by wm4** [comment]
I don't quite remember. Don't lachs0r's builds have youtube-dl?

Btw. I think MPC-HC might profit from the FFmpeg fix too.

**Comment by kevmitch** [comment]
They don't include youtube-dl. Download the .exe as pointed to by the [mpv download page](http://mpv.srsfckn.biz/). Just drop it into the mpv directory. See also the links to browser plug ins so you don't have to deal with windows' crappy command line.

**Comment by wp9015362** [comment]
@kevmitch & @wm4 :

Thank you for the fast replies.

After dropping youtube-dl.exe into the mpv directory, mpv indeed is now playing YouTube videos.

But it's not playing DASH videos. It's only opening the 720p version of the video (i.e. not the 1080p/2160p nor the 60fps versions)

But according to https://github.com/mpv-player/mpv/commit/78caf6ae8634b9fe9589187d8febb927dce2ddeb it should work, shouldn't it?

Do you happen to know why it's not playing the DASH videos?

Regards

**Comment by wp9015362** [comment]
PS:

The mpv version being used is https://mpv.srsfckn.biz/mpv-x86_64-20151029.7z together with https://yt-dl.org/latest/youtube-dl.exe.

Regards

**Comment by wp9015362** [comment]
PPS:

Okay, found the answer myself:

> @lachs0r wrote in https://github.com/mpv-player/mpv/releases/tag/v0.12.0:
> 
> NOTE: This release changes the default format for youtube-dl and removes some
workarounds related to MPEG DASH support. However, the required changes to
FFmpeg code are not in any FFmpeg release yet (as of 2015-10-29), so for now,
playing DASH streams requires using FFmpeg git master. You can work around
this by using the --ytdl-format=best option.

However, to actually get the DASH videos, you seem to have to use --ytdl-format=bestvideo+bestaudio instead of --ytdl-format=best :wink:.

Anyway, since the performance is so bad (as decribed in https://github.com/mpv-player/mpv/issues/932), it's not really of any use :worried:.

Regards

**Comment by kevmitch** [comment]
better yet, don't specify ytdl-format at all. This uses the youtube-dl default of bestvideo+bestaudio/best which is subtly different / better suited, for sites other than youtube.
See the [documentation](https://github.com/rg3/youtube-dl/blob/master/README.md).

**Comment by ChrisK2** [comment]
[but only if you happen to have ffmpeg installed ...](https://github.com/rg3/youtube-dl/issues/7289)

**Comment by wp9015362** [comment]
> @kevmitch wrote:
> 
> better yet, don't specify ytdl-format at all. This uses the youtube-dl default of bestvideo+bestaudio/best 

When using https://mpv.srsfckn.biz/mpv-x86_64-20151029.7z + https://yt-dl.org/latest/youtube-dl.exe and not specifiying ytdl-format, like you are suggesting, then I am only getting YouTube standard 720p videos (i.e. no DASH videos).

But when specifying --ytdl-format=bestvideo+bestaudio, then I am getting DASH videos.

By reading [the latest release notes](https://github.com/mpv-player/mpv/releases/tag/v0.12.0), I am assuming that once FFmpeg gets bumped, this will no longer be required and I will also get DASH videos when not specifying ytdl-format?

Regards

**Comment by kevmitch** [comment]
sorry, as ChrisK2 has pointed out, due to youtube-dl weirdness, you probably do have to specify ``--ytdl-format=bestvideo+bestaudio`` on windows unless you have the ffmpeg command line tool in your path.

**Comment by wp9015362** [comment]
> @ChrisK2 wrote:
> 
> [but only if you happen to have ffmpeg installed ...](https://github.com/rg3/youtube-dl/issues/7289)

It looks like the youtube-dl developers do not even know how mpv works together with youtube-dl, see:

https://github.com/rg3/youtube-dl/issues/6642

Might make sense if you would explain it to them :wink:?

Regards

**Comment by ChrisK2** [comment]
Most of them know how it works. And if they won't do anything about it we can still work around it in our code.
