### ISSUE TITLE
Caching doesn't work with livestreamer under Windows.

### ISSUE THREAD

**Issue by zxx1** [mpv-player/mpv#2449]

**Comment by zxx1** [comment]
No cache status on the interface and player closes after 1 second after I close a command prompt window. So only 1 second cached.

**Comment by wm4** [comment]
>--demuxer-readahead-secs works.

So there's no real bug. mpv automatically enables full caches for pipes on Linux, but not on Windows. Just enable it manually with ``--cache``.

**Comment by zxx1** [comment]
Yes, it works with --cache=yes, thanks.
