### ISSUE TITLE
windows: sometimes missing mpv taskbar item if started in fullscreen

### ISSUE THREAD

**Issue by avih** [mpv-player/mpv#2451]
If mpv is executed as `mpv --fs myclip` and it starts in fullscreen, and then pressing 'f' to exit fullscreen, sometimes there's no mpv item on the taskbar.

This happens both with `--vo=opengl` and with `--vo=direct3d`, and with both VOs I've seen it both with a taskbar item and without, so it seems random and unrelated to the `vo`.

Tested on windows 8.1 64 with mpv 32.

**Comment by RosadinTV** [comment]
Yes, also it happens to me sometimes.
But if you press Alt+Tab to select MPV, the icon is displayed again.

**Comment by avih** [comment]
> But if ...

Sure, but it's still a bug.

**Comment by rossy** [comment]
I can't reproduce this bug on my Windows 8.1 machine, but I wonder if it would help to add WS_EX_APPWINDOW as an extended window style in CreateWindowExW.

**Comment by avih** [comment]
As far as I can tell, using the patch below, it still behaves the same (i.e. still random on my system):
```patch
--- a/video/out/w32_common.c
+++ b/video/out/w32_common.c
@@ -1167,7 +1167,7 @@ static void *gui_thread(void *ptr)
                                       0, 0, r.right, r.bottom,
                                       w32->parent, 0, hInstance, NULL);
     } else {
-        w32->window = CreateWindowExW(0, classname,
+        w32->window = CreateWindowExW(WS_EX_APPWINDOW, classname,
                                       classname,
                                       update_style(w32, 0),
                                       CW_USEDEFAULT, SW_HIDE, 100, 100,
```

**Comment by avih** [comment]
I just also tested with d3d. The above (still random the same) is still true for OpenGL output, but with d3d output is seems to be mostly OK. In about 20 attempts, the taskbar item didn't show only on one case, and before the patch it's roughly 50-50 if the bug happens or not.

**Comment by lachs0r** [comment]
I *guess* this also happens due to Windows’ exclusive fullscreen window heuristics.
Try this build: http://tmp.srsfckn.biz/mpv_ws.exe.xz

**Comment by lachs0r** [comment]
Actually this also depends on the window style flags, and there can be random delays before windows decides whether or not to show a taskbar entry. We’ll have to ask Raymond Chen about how exactly this works, but I suspect `WS_POPUP` can prevent the window from getting a taskbar entry if it is set early enough. If that is true, the build I just posted should also work around this, since it no longer uses that style (it removes all style flags though, so not sure how Windows will react).

If this does not help either, we can try again with `WS_EX_APPWINDOW`, and if that still does not reliably fix the problem, we can try creating a window, showing it, and only switching to fullscreen mode once it is on screen.

**Comment by rossy** [comment]
Well, this fixes the other exclusive fullscreen problem (tearing) on my PC, so it looks good.

> (it removes all style flags though, so not sure how Windows will react).

Setting window styles to 0 is the same as WS_OVERLAPPED (#define WS_OVERLAPPED 0x00000000L,) so it's totally well defined.

**Comment by avih** [comment]
> I guess this also happens due to Windows’ exclusive fullscreen window heuristics.
> Try this build: http://tmp.srsfckn.biz/mpv_ws.exe.xz

So what patch did you use here?

It doesn't fix it for me.

**Comment by pavelxdd** [comment]
This issue is always reproducible for me on Windows 8, so it probably should be reopened.

I think, the only way to solve this, as @lachs0r said, would be:
> we can try creating a window, showing it, and only switching to fullscreen mode once it is on screen.
