### ISSUE TITLE
ICY metadata doesn't get 'cached' ?

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#2453]
When i listen to a webradio and i use some cache, i can pause the stream so that the cache will fill with audio data, but meantime if the webradio transmits a new icy-title metadata, mpv will display it instantly, so that when i unpause mpv, the actual song i listen does not reflect the icy-title.
Would it be possible to cache icy metadata too?

**Comment by wm4** [comment]
No.
