### ISSUE TITLE
Compiling instruction on centos.

### ISSUE THREAD

**Issue by kybin** [mpv-player/mpv#2455]
Is there any compling instruction for centos? 

I've tried it but with no luck. (ffmpeg version is low)

I want to use mpv in my production, and we use centos unfortunately.

Or could you offer one-big-static-binary file for each release? (I want it so much!)

**Comment by lachs0r** [comment]
Use mpv-build.

**Comment by kybin** [comment]
Oh, sorry I didn't knew that. 

Unfortunately it says 

```
configure: error: Package requirements (fribidi >= 0.19.0) were not met:
No package 'fribidi' found
```

How could I fix it?
