### ISSUE TITLE
buffer cache + DSP plugins

### ISSUE THREAD

**Issue by nedz14** [mpv-player/mpv#2461]
i watch videos from sites like youtube, dailymotion in smplayer with mpv and youtube-dl.
is there a way to use winamp DSP plugins and use it as audio filter.
and how can i  incrase the buffer cache to 30mb for example.
thank you

**Comment by wm4** [comment]
> winamp DSP plugins 

No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No. No.

**Comment by daikazoku** [comment]
What about any other kind of DSP plugins (like vst or whatever the linux and mac equivalent is)? Relatively often, on twitch streams or similar online content, they fail to adjust their levels at all, and you either get your ear destroyed or you don't ear anything. Any simple compressor would solve this, and it would be nice to be able to do that.

**Comment by nedz14** [comment]
how can i incrase the buffer cache then.

**Comment by wm4** [comment]
``--af=drc`` for the simplest.

>how can i incrase the buffer cache then.

It's already at 150MB by default.

**Comment by daikazoku** [comment]
huh. Apparently I should rtfm. Thanks.
