### ISSUE TITLE
prescale=nnedi3 broken without deband option

### ISSUE THREAD

**Issue by Akemi** [mpv-player/mpv#2464]
mpv --no-config --vo=opengl:prescale=nnedi3 + window-scale=2.0
![nnedi3](https://cloud.githubusercontent.com/assets/680386/11043833/f20fea7c-871e-11e5-926a-848c855fab3a.png)

mpv --no-config --vo=opengl:prescale=nnedi3:deband + window-scale=2.0
![nnedi3-deband](https://cloud.githubusercontent.com/assets/680386/11043836/f5cbd478-871e-11e5-80ec-3bb853d886b1.png)

some problems marked
![nnedi3-marked](https://cloud.githubusercontent.com/assets/680386/11043938/5f6ca8da-871f-11e5-851e-050344d0d455.png)

a test file can be found [here](https://dl.dropboxusercontent.com/u/68772824/nnedi3.mkv), but i could reproduce it with any other file too.

without the deband option nnedi3 blurs details, introduces some horizontal lines and has localised 'blurring'-like artifacts. system is OSX 10.10.3 with nvidia's web driver 346.01.02.f04. i marked some of the problems on the third screen. let me know if you can't reproduce it and/or need some more info.

**Comment by bjin** [comment]
I guess I found the cause, will open another PR to fix it once it's verified.

**Comment by bjin** [comment]
For the record,  I'm suspecting tex_mul handling to be the cause.
