### ISSUE TITLE
How to install mpv_0.12.0_mac.tar.bz2 in MAC?

### ISSUE THREAD

**Issue by limelime** [mpv-player/mpv#2465]
How to install mpv_0.12.0_mac.tar.bz2 in MAC?
I downloaded mpv_0.12.0_mac.tar.bz2 and uncompressed it.
Then, what am I suppose to do afterward?

Please note, I'm new to MAC.

**Comment by AirPort** [comment]
Drag the uncompressed file in the Application folder.
Then set it as the default application to open the file type you want to use with mpv (e.g. mkv, ...): hit cmd+i selecting such a file, select mpv from the 'Open with' menu and then click on 'Change all'. Alternatively you can drag the file you want to open in the mpv window or on the mpv bundle you uncompressed in the first place.
