### ISSUE TITLE
I can't play videos via samba on OpenSUSE Leap 42.1 Plasma 5.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2467]
I can't play videos via samba on OpenSUSE Leap 42.1 Plasma 5, but other type of files are fine.

Here is the error message:

<pre>user@user-PC:~> mpv 'smb://user@user-laptop/laptop影片/The Brightest Part of a Shadow is in the Middle-y9c
8oZ49pFc.mkv'
Playing: smb://user@user-laptop/laptop影片/The Brightest Part of a Shadow is in the Middle-y9c8oZ49pFc.mkv
Using netbios name user-PC.
Using workgroup WORKGROUP.
[smb] Could not open from LAN: 'smb://user@user-laptop/laptop影片/The Brightest Part of a Shadow is in the
 Middle-y9c8oZ49pFc.mkv'
Failed to open smb://user@user-laptop/laptop影片/The Brightest Part of a Shadow is in the Middle-y9c8oZ49p
Fc.mkv.

Exiting... (Errors when loading file)</pre>

**Comment by wm4** [comment]
Is it because of the non-ASCII characters?

**Comment by laichiaheng** [comment]
@wm4 I can't play the video which name is in English only either.

**Comment by Cpuroast** [comment]
either the fact that your share has non-english character is causing a problem, or you haven't correctly authenticated to the server, I don't see a password prompt, which could explain why.

Have you tried mounting the same share and then playing the files from the mount, instead of using smb:// ?

**Comment by laichiaheng** [comment]
@Cpuroast How to play it from the mount?
I have tested the video of english-only character file name, it doesn't work, and other music, text are able to read.

**Comment by Cpuroast** [comment]
This is help for mpv, not general linux help.

But here's how anyways:

mkdir /mnt/folder
mount -t cifs -o user=user //server/share /mnt/folder
it then prompts for your password.

then you can simply access /mnt/folder as if it was another folder on your computer
which means you can simply do:
cd /mnt/folder
mpv somefile.mkv

The share will be mounted in /mnt/folder until you reboot.

**Comment by laichiaheng** [comment]
@Cpuroast Thanks for your tutorial, although I have given up samba, and move to NFS.
There is no problem with NFS, so the samba on OpenSUSE must have some problem, it never happened when I'm on Ubuntu.

**Comment by laichiaheng** [comment]
Somebody has found the solution, for example, my URL looks like this:
"smb://user@user-laptop/laptop影片/The Brightest Part of a Shadow is in the Middle-y9c
8oZ49pFc.mkv"

and it has to become this:
"smb://user:password@user-laptop/laptop影片/The Brightest Part of a Shadow is in the Middle-y9c
8oZ49pFc.mkv"

just add the password there, can mpv player set it without terminal?

**Comment by wm4** [comment]
No, unless libsmbclient has something for this. (But I wouldn't know.)

Closing this, since cause and solution are known now. mpv definitely won't start with showing message boxes or anything for asking for passwords. If you want something more convenient, just mount your smb share with FUSE.

**Comment by laichiaheng** [comment]
@wm4 I mean to preset it in the config file, so it can enter the password automatically.

**Comment by qmega** [comment]
If you use KWallet to store your password, you could use something like this: https://github.com/mpv-player/mpv/issues/1512#issuecomment-77504217

**Comment by laichiaheng** [comment]
@qmega KDE is just too hard to use, so I have given it up.
