### ISSUE TITLE
Add sonic as alternative to WSOLA for pitch-corrected playback at changed playbackspeed

### ISSUE THREAD

**Issue by Nudin** [mpv-player/mpv#2468]
Currently the scaletempo audio filter of mpv uses the WSOLA-algorithm. Especially for speech-content and high playback speeds the quality gets quiet bad.
I found the free library sonic ([1](https://github.com/waywardgeek/sonic)) witch claims to bee better in those cases ([2](https://github.com/waywardgeek/sonic/blob/master/doc/index.md)) and is used by espeak.

I wonder if it could be implemented as alternative to WSOLA?

**Comment by lachs0r** [comment]
What about the `rubberband` filter?

**Comment by wm4** [comment]
Before anyone event attempts to do anything, it should be confirmed whether the algorithm is good enough for general purpose uses.

**Comment by lachs0r** [comment]
Nobody seems to care.
