### ISSUE TITLE
recent drm/kms changes and Iris pro problem?

### ISSUE THREAD

**Issue by almostalive** [mpv-player/mpv#2469]
I have a desktop and laptop both running Archlinux and running the same kernel 4.1.13-ck and mesa 11.0.5 and xf86-video-intel 1:2.99.917+478+gdf72bc5-2 and using the same binary that I built using mpv-build.

The desktop has a Haswell i7-4770R CPU with Iris Pro 5200 graphics connected to a Samsung TV via HDMI. At commit: b1893d2084aa3fa83dbf098f46399101e6b21a68 vo=drm worked just fine, after that commit  I get Connector 0 is disconnected and Failed to configure KMS.
when trying either opengl:backend=drm-egl or drm. verbose shows nothing useful.

The laptop has a Broadwell i3-5010U CPU with Intel HD Graphics 5500. The drm/kms changes work just fine on it. I did a quick test of hooking up the laptop to the TV via HDMI and an old monitor via VGA, the video always displayed on the laptop screen and I couldn't figure out how to get it on the other displays. vo=drm:connector=(random number) did nothing and sadly i did not have an old build to see if it would of worked with that.

Could this be an Iris Pro Graphics problem or something else? The only other video connection I have on my desktop is Displayport but I don't have a monitor for it so I can't test if it would work with that.

@rr- if you need anymore info or something for me to test let me know.

**Comment by rr-** [comment]
Well spotted, should be fixed in the PR.

**Comment by almostalive** [comment]
Yep that fixed it. Thanks for the quick fix.
