### ISSUE TITLE
Starting videos from youtube takes an extremely long time

### ISSUE THREAD

**Issue by emoryy** [mpv-player/mpv#2471]
This started when I updated to version 1:0.12.0.
If I open a youtube video url with mpv, playing the video starts after only a couple of minutes. (Last I tried it was 3 minutes.)

I don't know if it's relevant, but if I'm not patient and press ctrl+c, this is the output I get:

```
Saving state.
[ffmpeg] Seek failed
[ffmpeg] Seek failed
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none, 1280x720, 2050 kb/s): unspecified pixel format
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' and 'probesize' options
[lavf] av_find_stream_info() failed
Failed to recognize file format.
Exiting... (Quit)
```
No other output other than the initial `Playing: [youtube url]`
If I wait until the video starts the output doesn't differ than how it would be normally.

There is no problem either when trying the same urls with youtube-dl.

I use Arch Linux, everything updated to latest.

**Comment by wm4** [comment]
Read release notes.

**Comment by emoryy** [comment]
Sorry, and thanks. I don't know how I could miss that.

**Comment by f3z0** [comment]
I'm experiencing this, is this ticket still valid? What release notes?

**Comment by adisib** [comment]
I believe the release notes referred to are the v0.13.0 release notes which say:

> NOTE: The previous release changed the default format for youtube-dl and
removed some workarounds related to MPEG DASH support. However, the required
changes to FFmpeg code (FFmpeg/FFmpeg@4ab5666)
are not in any FFmpeg release yet (as of 2015-11-10), so for now, playing DASH
streams requires using FFmpeg git master. You can work around this by using the
--ytdl-format=best option.

I don't think this is related, and I am also getting this with up to date mpv and up to date youtube-dl.

**Comment by kevmitch** [comment]
I think you need mpv to be compiled against up-to-date ffmpeg to get the fix.
