### ISSUE TITLE
Nit: docs or notes should mention that Vista or higher is now required

### ISSUE THREAD

**Issue by qyot27** [mpv-player/mpv#2473]
With https://github.com/mpv-player/mpv/commit/16cd20c46f02a052f06742329dc375a695bb6e0b, the requirement of avrt.dll (and using it inside w32_common) breaks Windows XP support.

I don't really have a dog in that race anymore, since I have a Win10 setup that I use mpv near exclusively on now, but there might be some complaints in the future and having that notice might cut down on it.  XP users could be advised to use either commit https://github.com/mpv-player/mpv/commit/8f7b12d9ae3f1034cc86cea520bbb7579b1a3a25 or v0.12.0 depending on their preference for point releases or not.

Although I don't actually know if Vista is a hard minimum now, since I'm not sure if avrt.dll was added at the same time as wasapi itself was, or if it came later...and the only machine with Vista on it that I have access to is a PITA to work with.

**Comment by lachs0r** [comment]
While I’m not really in favor of keeping this dinosaur alive, that breakage was probably not intended (should be noted that ao_wasapi still tries to load that library dynamically).
