### ISSUE TITLE
video-sync not working on windows

### ISSUE THREAD

**Issue by alabrand** [mpv-player/mpv#2474]
MPV Windows Build 2015-11-10

OS: Windows 10
CPU: 5960X
GPU: 980 Ti

With the setting video-sync=display-resample turned on, audio is not in sync with video. With it turned off, audio is in sync with video. This is contrary to what the setting should be doing, I believe. Using Argon's mpv-stats (https://github.com/Argon-/mpv-stats) the A-V starts out around -0.030 and quickly climbs up all the way to 0.500, then it goes down to 0.300 and it seems to hover in the area of 0.300 to 0.500. As soon as I disable video-sync=display-resample and restart the video (reopen it) the A-V value stays at 0.000 throughout the entirety of the video. This issue happens regardless of whether my config only has video-sync=display-resample in it or tons of other stuff. It also happens regardless of the video source. My monitor is 120Hz, if that's of any help. I'll attach a couple of screens to showcase the problem. Let me know if you need any additional information.

1080p 60fps displaysync off
![mpv battlefield4 1080p 60fps displaysync off](https://cloud.githubusercontent.com/assets/6384915/11114821/a0c34c12-8927-11e5-8755-afbd9cccd728.png)

1080p 60fps displaysync on start of the video
![mpv battlefield4 1080p 60fps displaysync on start](https://cloud.githubusercontent.com/assets/6384915/11114826/a9995eee-8927-11e5-8af3-1942dcfecd6d.png)

1080p 60fps displaysync on end of the video
![mpv battlefield4 1080p 60fps displaysync on end](https://cloud.githubusercontent.com/assets/6384915/11114854/e9548d60-8927-11e5-9c04-1f82940b48de.png)

**Comment by wm4** [comment]
Normally it should start dropping frames once it's over 80ms desync, so I can't explain this.

**Comment by alabrand** [comment]
Is there a log function in mpv that could possibly reveal the problem?

**Comment by wm4** [comment]
You could post the terminal output with ``-v`` or use ``--log-file=output.txt``.

**Comment by alabrand** [comment]
[output.txt](https://github.com/mpv-player/mpv/files/32764/output.txt)

Not that I know how to make any sense of all this but there you go. Let me know if I screwed it up.

**Comment by wm4** [comment]
Maybe you can try disabling this stats thing.

**Comment by alabrand** [comment]
Done some limited testing with live performances and a couple of movies but it seems to have solved itself by removing the script. Or rather, not using the script to be more precise. Both audio and video sync up more or less perfectly from what I can tell.

My guess is that the script is polling the stats so much that it causes a desync every time it polls. Or something like that, I don't really know.

Downside to this is that I can't leave the video running in the background and then come back to it as that desyncs the audio and video. You have to pause if you want to temporarily leave the video.

**Comment by wm4** [comment]
Yes, the script is all kinds of inefficient (querying loads of properties, creating the OSD text, rendering the text).

>Downside to this is that I can't leave the video running in the background and then come back to it as that desyncs the audio and video. You have to pause if you want to temporarily leave the video.

I don't understand this.

**Comment by alabrand** [comment]
What I mean by that is I can't have mpv running a video and browsing the internet at the same time as this will desync the audio and video. Pausing and then unpausing fixes this however. But it would be nice to see some kind of dynamic video-sync that does this automatically without having to pause.

**Comment by wm4** [comment]
?????

**Comment by alabrand** [comment]
Nevermind, don't worry about it. It's not that big of a deal anyway.

**Comment by lachs0r** [comment]
Is this just NVIDIA’s driver downclocking your GPU because it thinks mpv 
doesn’t need it? Or maybe the recent MMCSS change had the opposite effect?

**Comment by alabrand** [comment]
I can confirm that driver downclocking is not the issue. In fact, my 980 Ti is running at close to maximum boost clocks as soon as I start mpv. I have checked this with both Afterburner, Inspector and HWiNFO.

Either way, the issue was eliminated by either not using the script or removing it.

**Comment by alabrand** [comment]
BTW you can close this as solved. The solution is to not use external scripts and/or/including mpv-stats.

**Comment by wm4** [comment]
OK, I'll just assume the rendering time of the script was too long to finish within the vsync.

**Comment by wm4** [comment]
I tried the stats script myself, but it seems to be fast enough for me. So certainly it isn't gravely inefficient. My CPU and GPU are much weaker than yours too. So, cause unknown. Maybe the video options are somehow too heavy. (I've only tried with ``opengl-hq:interpolation:tscale=mitchell:deband=no``.)
