### ISSUE TITLE
ytdl: seeking makes DASH H.264 stuck

### ISSUE THREAD

**Issue by tomty89** [mpv-player/mpv#2475]
Seeking with mouse wheel / arrow keys in Youtube DASH H.264 video can make it stuck; After exiting with "q", the following errors are given:

[ffmpeg] NULL: AVC: nal size 19469
[ffmpeg] NULL: missing picture in access unit with size 3628

This does not happen for VP9 or non-DASH H.264 video. However it happens with and without DASH audio. Seeking by clicking on the OSC doesn't seem to cause trouble (it might have something to do with the ranges of the leaps though).

**Comment by wm4** [comment]
I can't confirm this. On the other hand, your FFmpeg version is new enough that it should contain the commit that made DASH work.

**Comment by kevinlekiller** [comment]
I have the same issue, I've stuck to VP9 because of it. I'll try to get some more info.

**Comment by kevinlekiller** [comment]
`mpv --no-config --load-scripts=no --ytdl ytdl-format=299+251/299+141/299+140/299+171/137+251/137+141/137+140/137+171/best --cache=auto --cache-default=16384 --hwdec=auto -v https://www.youtube.com/watch?v=lRf6u_Dvp08 | tee mpv.log`

[Log file.](https://gist.githubusercontent.com/kevinlekiller/03006dee42a96f0311e4/raw/7c3cf7fb823f5580d6efa7c631bd32dd122a3658/mpv.log)

Video: `299          mp4        1920x1080  DASH video 5685k , h264, 50fps, video only, 1.02GiB`
Audio: `140          m4a        audio only DASH audio  129k , m4a_dash container, aac  @128k (44100Hz), 30.35MiB`

Steps taken:
Video started.
Waited 13 seconds until cache is full. 
Seek 60 seconds forward.
Nothing happens, exit mpv.

**Comment by wm4** [comment]
Tried exactly the same command line (after you edited it to fix the ytdl-format part), and it worked fine.

**Comment by kevinlekiller** [comment]
If you want me to run more verbose with `--msg-level` for a certain module, let me know.

**Comment by kevinlekiller** [comment]
I set `--msg-level=ffmpeg=debug`, if I pause the video, it's fine. If I seek outside the cache, and pause the video, a bunch of lines like these are output, many times per second:

`[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: stream 0, sample 6292, dts 125840000
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: stream 0, sample 6293, dts 125860000
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: stream 0, sample 6294, dts 125880000
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: stream 0, sample 6295, dts 125900000
`

**Comment by wm4** [comment]
Enabling --msg-time might help, because then I see where it's actually stuck. Feel free to add  --msg-level=ffmpeg=debug too.

**Comment by kevinlekiller** [comment]
Will do, thanks.

**Comment by kevinlekiller** [comment]
`mpv --no-config --load-scripts=no --ytdl --ytdl-format=299+251/299+141/299+140/299+171/137+251/137+141/137+140/137+171/best --cache=auto --cache-default=16384 --hwdec=auto -v --msg-level=ffmpeg=debug --msg-time https://www.youtube.com/watch?v=lRf6u_Dvp08`

The seek was around timestamp `26307789`.

[Log.](https://gist.githubusercontent.com/kevinlekiller/e266fcac50292e0f3fa3/raw/661272ef26a1fa26d5af4e2e69c9fdf684ed503a/mpv.log)

**Comment by kevinlekiller** [comment]
It is downloading (74.125.174.53 is a google IP), a constant 25Mbit/s, http://i.imgur.com/F6UT6RU.png

**Comment by wm4** [comment]
What's your youtube-dl version? Works for me with 2015.06.04.1 and 2015.11.10.

From your log it does indeed look like mpv is just skipping over fragments.

**Comment by kevinlekiller** [comment]
`youtube-dl --version`
2015.11.13

**Comment by mc4man** [comment]
Easily reproduced here, 1080p mp4 will freeze when seeking with arrow key/scroll wheel, 720p is fine
The offending commit seems to be a135c9c (demux_mkv: fix cluster skip with duration probing

**Comment by kevinlekiller** [comment]
I tried the previous commit of a135c9cffc0be4dd980f41e424d88821ea1222c1, f891b24cb53c7690fc822beabdaa7a011e5b418b,  but still the same issue.

**Comment by wm4** [comment]
Can you maybe download the mp4 stream and upload it somewhere?

> The offending commit seems to be a135c9c (demux_mkv: fix cluster skip with duration probing 

That's impossible. The mkv demuxer is not used for mp4.

**Comment by kevinlekiller** [comment]
Here's a log with `--msg-level=all=trace` if it helps, will upload the video in a bit.

https://gist.githubusercontent.com/kevinlekiller/ff658aca2e8dbfcf09a9/raw/24353f1afb34cea61deb45d21abfe53749c0203c/mpv.log

**Comment by kevinlekiller** [comment]
I picked a [shorter youtube video](https://www.youtube.com/watch?v=igqZ77NXpyE) so it's faster to upload/download. 

The video when played locally seeks fine.

[Video download link](https://www.dropbox.com/s/rjnem2xjqojlo3r/eevBLAB%20%2318%20-%20Old%20Component%20Drawers-igqZ77NXpyE.mp4?dl=0).

**Comment by mc4man** [comment]
That's what I would think. However on that commit the freezing occurs 
when seeking 1080p h.264. On the prior commit it doesn't when the ffmpeg 
source is a bit earlier than Oct. 27. On the prior commit if I use a 
recent ffmpeg git source then it also freezes.

**Comment by tomty89** [comment]
I no longer have this issue in a new Arch Linux installation with:
youtube-dl 2015.11.10
mpv 0.13.0
ffmpeg 2.8.2

**Comment by ear** [comment]
Does anyone know if this is the same problem as when you try to seek (say, by accident) on a live twitch stream? The playback stops and the thing gets stuck.

**Comment by wm4** [comment]
>Does anyone know if this is the same problem as when you try to seek (say, by accident) on a live twitch stream? The playback stops and the thing gets stuck.

Probably not.

**Comment by tomty89** [comment]
It would be ideal that mpv wouldn't allow any forward seeking when playing a live stream though.
