### ISSUE TITLE
mpv 0.13 doesn't work on wayland on gnome 3.18 in fedora 23

### ISSUE THREAD

**Issue by radistmorse** [mpv-player/mpv#2477]
when I try to launch mpv -vo wayland I get an undecorated small window in top left corner which causes all kinds of weirdness when you try to interact with it. To cut story short - it's just unusable.
Logs: http://paste.fedoraproject.org/289582/47330295

when I try to launch mpv -vo opengl[-hq] it just doesn't work.
Logs: http://paste.fedoraproject.org/289584/73304371

On the unrelated note: my OGL version is 3.3 in core profile. Do you use compat OGL profile? why?

**Comment by radistmorse** [comment]
Is there any particular kind of info you are interested in?

**Comment by wm4** [comment]
Anything that helps. Can't see anything particularly wrong in the logs.

**Comment by radistmorse** [comment]
Yes, well, I'd like that too :)

Here's weston-info
```
[morse@morseworkbook ~]$ weston-info
interface: 'wl_drm', version: 2, name: 1
interface: 'wl_compositor', version: 3, name: 2
interface: 'wl_shm', version: 1, name: 3
	formats: XRGB8888 ARGB8888
interface: 'wl_output', version: 2, name: 4
	x: 0, y: 0,
	physical_width: 380 mm, physical_height: 210 mm,
	make: 'AUO', model: '0x159d',
	subpixel_orientation: horizontal rgb, output_transform: normal,
	mode:
		width: 1920 px, height: 1080 px, refresh: 0 Hz,
		flags: current preferred
interface: 'wl_data_device_manager', version: 2, name: 5
interface: 'xdg_shell', version: 1, name: 6
interface: 'wl_shell', version: 1, name: 7
interface: 'gtk_shell', version: 2, name: 8
interface: 'wl_subcompositor', version: 1, name: 9
interface: '_wl_pointer_gestures', version: 1, name: 10
interface: 'wl_seat', version: 4, name: 11
	name: seat0
	capabilities: pointer keyboard
	keyboard repeat rate: 33
	keyboard repeat delay: 500
```
Other that that, I'm really out of ideas. Should I take it to gnome wayland team?

**Comment by radistmorse** [comment]
I was wrong, there actually is some useful info: the problem was with the --autofit-larger option. After I removed it, the window became usable again. No decorations is drawn for the window though.

With -vo wayland the OSD behaves wrong: it starts normally, but moves one "step" down and right every redraw, until disappears out of the screen. The scaling is also not working properly (again, all kinds of weirdness) and the window placement is always on top left: when you drag and drop it, it jumps back as soon as the pointer moves (unless part of the video is outside of the screen, then it stays for some reason).

With -vo opengl the OSD is ok, and window scaling and moving both work. But the fullscreen mode doesn't center the video and doesn't fill the margins.

**Comment by paulguy** [comment]
mpv always shows up in the top left for me too, in X11.  I think that part's just normal, or maybe just coincidental.  I use MATE 2.8.

**Comment by lachs0r** [comment]
So is this still a problem?

**Comment by PhilipKigo** [comment]
i tried fedora 25 to test out wayland progress on gnome 3.22; it is amazing. However this is still an issue, therefore players like baka-mplayer, smplayer when using mpv are almost unusable.

**Comment by wm4** [comment]
@PhilipKigo this sounds completely unrelated, so make a new issue if you think it's an issue (and provide some information - don't ignore the issue template). Also, mpv 0.13 is not supported anymore.
