### ISSUE TITLE
[YTDL] Going fullscreen makes video darker

### ISSUE THREAD

**Issue by CrisBRM** [mpv-player/mpv#2478]
Not sure if this is an mpv issue, however, whenever I go fullscreen, the video becomes significantly darker. This is not the case with 2015.04.03 (the 'stable' version on the gentoo repository), only happens with 2015.11.02 and 2015.11.10 (the only 2 other versions there).

Test case: https://www.youtube.com/watch?v=q858mp9M2wQ

[mpv.conf](https://github.com/mpv-player/mpv/files/33579/mpv.txt) (had to rename to mpv.txt)

**Comment by lachs0r** [comment]
Maybe you should stop copying config files with absolutely no idea of what 
they do.

1) superxbr is bad
2) your post shaders are probably broken (also these are bad)
3) most of your options are completely superfluous or even harmful

**Comment by CrisBRM** [comment]
I should probably do away with superxbr, temporal-dither, and sigmoid upscaling (messes with the post-shaders) you're right, but that's besides the point, since I did test without superxbr as well.

Adaptive sharpen post-shader is [here](https://gist.github.com/bjin/e22e96861669e897cf65). It's pretty mild.

Regardless, ytdl-2015.04.03 works fine, and the other two do not.

**Comment by bjin** [comment]
> Note that this shader expects gamma light and requires all linear scaling options (`linear-scaling` and `sigmoid-upscaling`) turned off to work properly.

I probably should move the gist just to stop those who use this shader without reading the notes.

**Comment by CrisBRM** [comment]
@bjin I know, which is precisely how I fixed it, though I'm still puzzled as to why the problem didn't manifest itself with the old ytdl version.
