### ISSUE TITLE
[Feature Request] Add UPNP/DLNA network playback support

### ISSUE THREAD

**Issue by Cormak** [mpv-player/mpv#2479]
UPNP/DLNA has more popular lately as Xbox/PS4/Windows10/miniDLNA/[insert media server here] software and hardware and faster consumer home networks have gotten into more people's hands and with all the server options out there, mpv should support UPNP/DLNA as a means of streaming media from such sources in order to make network playback simpler for the average user as well as make it more compatible with more consumer devices.

**Comment by timofonic** [comment]
I agree. We must deal with it, UPNP/DLNA is going to stay for a long time and get used to it.

**Comment by ChrisK2** [comment]
AFAIK the "streaming" with UPNP/DLNA happens completely over HTTP, which mpv already supports perfectly fine. You just have to figure out the URL yourself, since a media browser won't be integrated into mpv any time soon.

**Comment by kevmitch** [comment]
There's djmount

**Comment by Cormak** [comment]
I know there's no media browser, but you can browse an SMB share and mpv will stream the video just fine while if you browse a DLNA share, mpv will not recognize the upnp: extension at all and the file browser will just attempt to download the file.

I just think mpv should recognize the network protocol and stream accordingly.

**Comment by laichiaheng** [comment]
please support auto password filled in for SMB, there is a bug with KDE Plasma5's samba.
If I could set it in the config file, I have no problem with playing samba videos in Plasma5.

**Comment by kensully** [comment]
I was looking for such a dlna video player, unfortunately I found no working dlna video player in Linux.

**Comment by haasn** [comment]
Is it possible to just mount such media servers via some FUSE implementation of the relevant protocols?

If so, that would take care of the problem without mpv needing any custom code at all.

**Comment by billic** [comment]
@haasn yes, it is possible (not such stable), but dlna-player have some bonuses: It can be controlled from dlna-controller, runned on another device (like android tablet).

**Comment by markg85** [comment]
I was just about to post this a feature request as well. Glad i used search, hehe.

NOTE: this is just a braindump, sharing ideas. The commands below don't work!

How i envision this would work is as follows. Streaming video/audio/both from the instance where you type "mpv" to where you want to play it should be a command like so:

mpv vo=dlna:<server>

A command like above (without the server) should output a list of dlna ips where you can stream to. So:
mpv vo=dlna

That would be the cases where you want to send your content to a dlna device.
If you want to play a video from a dlna server, a command would look like:

mpv dlna://<server>/<path>

Getting a list of dlna devices can be done through avahi (service discovery stuff) with dbus calls. You'd somehow need to filter for dlna devices though.

All we need now is someone to implement the above :)
kodi supports some dlna so the pieces for this must all exist somewhere.

**Comment by wm4** [comment]
Nope.

**Comment by chachmu** [comment]
I realize this is pretty late but if anybody is still wanting to access DLNA servers using mpv I just released a plugin that lets you browse and playback content from local DLNA servers https://github.com/chachmu/mpvDLNA

**Comment by waldhef** [comment]
> realize this is pretty late

@chachmu,
it is never too late. I just yesterday googled around how to stream UPnP/DLNA contend with MPV and luckily found this thread. I followed you link and the install instruction on your GitHub page and it works perfectly. I'm so happy, thank you very much! :+1:
