### ISSUE TITLE
 With any video files automatically closes without displaying the image.

### ISSUE THREAD

**Issue by c384mb** [mpv-player/mpv#2480]
[   0.028][v][cplayer] Command line options: '--log-file=z:\log' 'h:\Видео\video.mkv'
[   0.028][v][cplayer] mpv git-fee45c0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[   0.028][v][cplayer]  built on Tue Nov 10 19:39:16 CET 2015
[   0.028][v][cplayer] ffmpeg library versions:
[   0.028][v][cplayer]    libavutil       55.5.100
[   0.028][v][cplayer]    libavcodec      57.15.100
[   0.028][v][cplayer]    libavformat     57.14.100
[   0.028][v][cplayer]    libswscale      4.0.100
[   0.028][v][cplayer]    libavfilter     6.15.100
[   0.028][v][cplayer]    libswresample   2.0.101
[   0.028][v][cplayer] ffmpeg version: N-76584-gc2b6248
[   0.028][v][cplayer] 
[   0.028][v][cplayer] Configuration: /home/lachs0r/mingw-w64-cmake/buildroot/build32/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --disable-debug-build --enable-libmpv-shared --enable-waio --enable-lua --enable-libarchive --enable-libass --enable-libbluray --enable-dvdread --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --prefix=/home/lachs0r/mingw-w64-cmake/buildroot/build32/prefix/mingw
[   0.028][v][cplayer] List of enabled features: asm atomics av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples build-date c11-tls cplayer direct3d dlopen dos-paths dsound dvdnav dvdread dxva2-hwaccel encoding gl gl-win32 glob-win32-replacement iconv jpeg lcms2 libarchive libass libass-osd libav libavdevice libavfilter libbluray libm libmpv-shared libswresample lua mingw noexecstack optimize posix-or-mingw pthreads resampler rubberband sse4-intrinsics static-build stdatomic subprocess tv uchardet waio wasapi win32 zlib
[   0.029][v][global] config path: '' -> 'C:\Documents and Settings\Администратор\Application Data/mpv'
[   0.030][v][global] config path: 'mpv.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/mpv.conf'
[   0.030][v][global] config path: 'config' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/config'
[   0.030][v][global] config path: 'mpv.conf' -/-> 'Z:/mpv/mpv.conf'
[   0.030][v][global] config path: 'config' -/-> 'Z:/mpv/config'
[   0.031][v][global] config path: 'mpv.conf' -/-> 'Z:/mpv/mpv/mpv.conf'
[   0.031][v][global] config path: 'config' -/-> 'Z:/mpv/mpv/config'
[   0.031][v][cplayer] Setting option 'log-file' = 'z:\log' (flags = 8)
[   0.034][v][global] config path: 'input.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/input.conf'
[   0.034][v][global] config path: 'input.conf' -/-> 'Z:/mpv/input.conf'
[   0.035][v][global] config path: 'input.conf' -/-> 'Z:/mpv/mpv/input.conf'
[   0.035][v][input] Falling back on default (hardcoded) input config
[   0.036][v][osc] Loading script @osc.lua...
[   0.038][v][global] config path: 'scripts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/scripts'
[   0.038][v][global] config path: 'scripts' -/-> 'Z:/mpv/scripts'
[   0.038][v][global] config path: 'scripts' -/-> 'Z:/mpv/mpv/scripts'
[   0.043][v][osc] loading mp.defaults
[   0.043][v][osc] loading @osc.lua
[   0.046][v][global] config path: 'lua-settings/osc.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/lua-settings/osc.conf'
[   0.046][v][global] config path: 'lua-settings/osc.conf' -/-> 'Z:/mpv/lua-settings/osc.conf'
[   0.046][v][global] config path: 'lua-settings/osc.conf' -/-> 'Z:/mpv/mpv/lua-settings/osc.conf'
[   0.046][v][osc] lua-settings/osc.conf not found. 
[   0.055][v][cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[   0.055][v][cplayer] mouse_leave script-binding osc/__keybinding2
[   0.055][v][cplayer] , force]
[   0.093][v][cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[   0.093][v][cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[   0.093][v][cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[   0.093][v][cplayer] mouse_btn2 script-binding osc/__keybinding5
[   0.093][v][cplayer] mouse_btn0_dbl ignore
[   0.093][v][cplayer] shift+mouse_btn0_dbl ignore
[   0.093][v][cplayer] mouse_btn2_dbl ignore
[   0.093][v][cplayer] del script-binding osc/__keybinding6
[   0.093][v][cplayer] , force]
[   0.122][v][cplayer] Run command: enable-section, flags=0, args=[input, ]
[   0.174][v][cplayer] Run command: disable-section, flags=0, args=[input]
[   0.236][v][cplayer] Done loading @osc.lua.
[   0.236][v][ytdl_hook] Loading script @ytdl_hook.lua...
[   0.293][v][global] config path: 'scripts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/scripts'
[   0.293][v][global] config path: 'scripts' -/-> 'Z:/mpv/scripts'
[   0.298][v][global] config path: 'scripts' -/-> 'Z:/mpv/mpv/scripts'
[   0.298][v][ytdl_hook] loading mp.defaults
[   0.299][v][ytdl_hook] loading @ytdl_hook.lua
[   0.299][v][cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[   0.300][v][cplayer] Done loading @ytdl_hook.lua.
[   0.300][v][global] config path: 'scripts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/scripts'
[   0.300][v][global] config path: 'scripts' -/-> 'Z:/mpv/scripts'
[   0.300][v][global] config path: 'scripts' -/-> 'Z:/mpv/mpv/scripts'
[   0.330][v][global] config path: 'watch_later' -> 'C:\Documents and Settings\Администратор\Application Data/mpv/watch_later'
[   0.387][i][cplayer] Playing: h:\Видео\video.mkv
[   0.387][v][cplayer] Running hook: ytdl_hook/on_load
[   0.389][v][cplayer] Run command: hook-ack, flags=0, args=[on_load]
[   0.414][v][ifo] Opening h:\Видео\video.mkv
[   0.414][v][ifo/dvdnav] Opening h:\Видео\video.mkv
[   0.415][v][bdmv/bluray] Opening h:\Видео\video.mkv
[   0.416][v][file] Opening h:\Видео\video.mkv
[   0.417][v][file] Stream opened successfully.
[   0.417][v][demux] Trying demuxer: disc (force-level: normal)
[   0.418][v][demux] Trying demuxer: edl (force-level: normal)
[   0.418][v][demux] Trying demuxer: cue (force-level: normal)
[   0.418][v][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.418][v][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.418][v][demux] Trying demuxer: tv (force-level: normal)
[   0.418][v][demux] Trying demuxer: libass (force-level: normal)
[   0.418][v][demux] Trying demuxer: mkv (force-level: normal)
[   0.418][v][mkv] Found the head...
[   0.418][v][mkv] + a segment...
[   0.418][v][mkv] Parsing seek head...
[   0.418][v][mkv] |+ segment information...
[   0.418][v][mkv] | + muxing app: libebml v1.3.0 + libmatroska v1.4.1
[   0.418][v][mkv] | + writing app: mkvmerge v6.5.0 ('Isn't she lovely') built on Oct 20 2013 12:50:05
[   0.418][v][mkv] | + timecode scale: 1000000
[   0.418][v][mkv] | + duration: 307.926s
[   0.418][v][mkv] | + segment uid 90 71 ae 85 cc 19 c7 c0 b0 11 38 51 5d f4 ac 70
[   0.418][v][mkv] |+ segment tracks...
[   0.418][v][mkv] | + a track...
[   0.418][v][mkv] |  + Track number: 1
[   0.418][v][mkv] |  + Track type: Video
[   0.418][v][mkv] |  + Video track
[   0.418][v][mkv] |   + Display width: 1920
[   0.418][v][mkv] |   + Display height: 1080
[   0.418][v][mkv] |   + Pixel width: 1920
[   0.418][v][mkv] |   + Pixel height: 1080
[   0.418][v][mkv] |  + Codec ID: V_MPEG4/ISO/AVC
[   0.418][v][mkv] |  + CodecPrivate, length 39
[   0.418][v][mkv] |  + Language: und
[   0.418][v][mkv] |  + Default duration: 33.367ms ( = 29.970 fps)
[   0.418][v][mkv] | + a track...
[   0.418][v][mkv] |  + Track number: 2
[   0.418][v][mkv] |  + Track type: Audio
[   0.418][v][mkv] |  + Audio track
[   0.418][v][mkv] |   + Sampling frequency: 44100.000000
[   0.418][v][mkv] |   + Channels: 2
[   0.418][v][mkv] |  + Codec ID: A_AC3
[   0.418][v][mkv] |  + Default duration: 34.830ms ( = 28.711 fps)
[   0.418][v][mkv] |+ found
-------------------------------------------------------------------------------------------------------------------------------
[   0.015][v][cplayer] Command line options: '--vo=direct3d' '--log-file=z:\log' 'h:\Видео\video.mkv'
[   0.015][v][cplayer] mpv git-fee45c0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[   0.015][v][cplayer]  built on Tue Nov 10 19:39:16 CET 2015
[   0.015][v][cplayer] ffmpeg library versions:
[   0.015][v][cplayer]    libavutil       55.5.100
[   0.015][v][cplayer]    libavcodec      57.15.100
[   0.015][v][cplayer]    libavformat     57.14.100
[   0.015][v][cplayer]    libswscale      4.0.100
[   0.015][v][cplayer]    libavfilter     6.15.100
[   0.015][v][cplayer]    libswresample   2.0.101
[   0.015][v][cplayer] ffmpeg version: N-76584-gc2b6248
[   0.015][v][cplayer] 
[   0.015][v][cplayer] Configuration: /home/lachs0r/mingw-w64-cmake/buildroot/build32/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --disable-debug-build --enable-libmpv-shared --enable-waio --enable-lua --enable-libarchive --enable-libass --enable-libbluray --enable-dvdread --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --prefix=/home/lachs0r/mingw-w64-cmake/buildroot/build32/prefix/mingw
[   0.015][v][cplayer] List of enabled features: asm atomics av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples build-date c11-tls cplayer direct3d dlopen dos-paths dsound dvdnav dvdread dxva2-hwaccel encoding gl gl-win32 glob-win32-replacement iconv jpeg lcms2 libarchive libass libass-osd libav libavdevice libavfilter libbluray libm libmpv-shared libswresample lua mingw noexecstack optimize posix-or-mingw pthreads resampler rubberband sse4-intrinsics static-build stdatomic subprocess tv uchardet waio wasapi win32 zlib
[   0.016][v][global] config path: '' -> 'C:\Documents and Settings\Администратор\Application Data/mpv'
[   0.017][v][global] config path: 'mpv.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/mpv.conf'
[   0.017][v][global] config path: 'config' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/config'
[   0.018][v][global] config path: 'mpv.conf' -/-> 'Z:/mpv/mpv.conf'
[   0.018][v][global] config path: 'config' -/-> 'Z:/mpv/config'
[   0.018][v][global] config path: 'mpv.conf' -/-> 'Z:/mpv/mpv/mpv.conf'
[   0.018][v][global] config path: 'config' -/-> 'Z:/mpv/mpv/config'
[   0.018][v][cplayer] Setting option 'vo' = 'direct3d' (flags = 8)
[   0.019][v][cplayer] Setting option 'log-file' = 'z:\log' (flags = 8)
[   0.022][v][global] config path: 'input.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/input.conf'
[   0.022][v][global] config path: 'input.conf' -/-> 'Z:/mpv/input.conf'
[   0.022][v][global] config path: 'input.conf' -/-> 'Z:/mpv/mpv/input.conf'
[   0.022][v][input] Falling back on default (hardcoded) input config
[   0.024][v][osc] Loading script @osc.lua...
[   0.024][v][global] config path: 'scripts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/scripts'
[   0.025][v][global] config path: 'scripts' -/-> 'Z:/mpv/scripts'
[   0.025][v][global] config path: 'scripts' -/-> 'Z:/mpv/mpv/scripts'
[   0.025][v][osc] loading mp.defaults
[   0.026][v][osc] loading @osc.lua
[   0.028][v][global] config path: 'lua-settings/osc.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/lua-settings/osc.conf'
[   0.028][v][global] config path: 'lua-settings/osc.conf' -/-> 'Z:/mpv/lua-settings/osc.conf'
[   0.028][v][global] config path: 'lua-settings/osc.conf' -/-> 'Z:/mpv/mpv/lua-settings/osc.conf'
[   0.028][v][osc] lua-settings/osc.conf not found. 
[   0.029][v][cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[   0.029][v][cplayer] mouse_leave script-binding osc/__keybinding2
[   0.029][v][cplayer] , force]
[   0.029][v][cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[   0.029][v][cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[   0.029][v][cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[   0.029][v][cplayer] mouse_btn2 script-binding osc/__keybinding5
[   0.029][v][cplayer] mouse_btn0_dbl ignore
[   0.029][v][cplayer] shift+mouse_btn0_dbl ignore
[   0.029][v][cplayer] mouse_btn2_dbl ignore
[   0.029][v][cplayer] del script-binding osc/__keybinding6
[   0.029][v][cplayer] , force]
[   0.030][v][cplayer] Run command: enable-section, flags=0, args=[input, ]
[   0.031][v][cplayer] Run command: disable-section, flags=0, args=[input]
[   0.032][v][cplayer] Done loading @osc.lua.
[   0.032][v][ytdl_hook] Loading script @ytdl_hook.lua...
[   0.033][v][global] config path: 'scripts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/scripts'
[   0.034][v][global] config path: 'scripts' -/-> 'Z:/mpv/scripts'
[   0.034][v][global] config path: 'scripts' -/-> 'Z:/mpv/mpv/scripts'
[   0.034][v][ytdl_hook] loading mp.defaults
[   0.035][v][ytdl_hook] loading @ytdl_hook.lua
[   0.035][v][cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[   0.035][v][cplayer] Done loading @ytdl_hook.lua.
[   0.036][v][global] config path: 'scripts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/scripts'
[   0.036][v][global] config path: 'scripts' -/-> 'Z:/mpv/scripts'
[   0.036][v][global] config path: 'scripts' -/-> 'Z:/mpv/mpv/scripts'
[   0.037][v][global] config path: 'watch_later' -> 'C:\Documents and Settings\Администратор\Application Data/mpv/watch_later'
[   0.050][i][cplayer] Playing: h:\Видео\video.mkv
[   0.050][v][cplayer] Running hook: ytdl_hook/on_load
[   0.058][v][cplayer] Run command: hook-ack, flags=0, args=[on_load]
[   0.062][v][ifo] Opening h:\Видео\video.mkv
[   0.062][v][ifo/dvdnav] Opening h:\Видео\video.mkv
[   0.063][v][bdmv/bluray] Opening h:\Видео\video.mkv
[   0.064][v][file] Opening h:\Видео\video.mkv
[   0.065][v][file] Stream opened successfully.
[   0.065][v][demux] Trying demuxer: disc (force-level: normal)
[   0.065][v][demux] Trying demuxer: edl (force-level: normal)
[   0.065][v][demux] Trying demuxer: cue (force-level: normal)
[   0.065][v][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.065][v][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.065][v][demux] Trying demuxer: tv (force-level: normal)
[   0.065][v][demux] Trying demuxer: libass (force-level: normal)
[   0.065][v][demux] Trying demuxer: mkv (force-level: normal)
[   0.065][v][mkv] Found the head...
[   0.065][v][mkv] + a segment...
[   0.065][v][mkv] Parsing seek head...
[   0.065][v][mkv] |+ segment information...
[   0.068][v][mkv] | + muxing app: libebml v1.3.0 + libmatroska v1.4.1
[   0.068][v][mkv] | + writing app: mkvmerge v6.5.0 ('Isn't she lovely') built on Oct 20 2013 12:50:05
[   0.068][v][mkv] | + timecode scale: 1000000
[   0.068][v][mkv] | + duration: 307.926s
[   0.068][v][mkv] | + segment uid 90 71 ae 85 cc 19 c7 c0 b0 11 38 51 5d f4 ac 70
[   0.068][v][mkv] |+ segment tracks...
[   0.068][v][mkv] | + a track...
[   0.068][v][mkv] |  + Track number: 1
[   0.068][v][mkv] |  + Track type: Video
[   0.068][v][mkv] |  + Video track
[   0.068][v][mkv] |   + Display width: 1920
[   0.068][v][mkv] |   + Display height: 1080
[   0.068][v][mkv] |   + Pixel width: 1920
[   0.068][v][mkv] |   + Pixel height: 1080
[   0.068][v][mkv] |  + Codec ID: V_MPEG4/ISO/AVC
[   0.068][v][mkv] |  + CodecPrivate, length 39
[   0.068][v][mkv] |  + Language: und
[   0.068][v][mkv] |  + Default duration: 33.367ms ( = 29.970 fps)
[   0.068][v][mkv] | + a track...
[   0.068][v][mkv] |  + Track number: 2
[   0.068][v][mkv] |  + Track type: Audio
[   0.068][v][mkv] |  + Audio track
[   0.068][v][mkv] |   + Sampling frequency: 44100.000000
[   0.068][v][mkv] |   + Channels: 2
[   0.068][v][mkv] |  + Codec ID: A_AC3
[   0.068]
-------------------------------------------------------------------------------------------------------------------------------
[   0.009][v][cplayer] Command line options: '--profile=pseudo-gui' '--log-file=z:\log' 'H:\Видео\3-1080p.mp4'
[   0.009][v][cplayer] mpv git-fee45c0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[   0.009][v][cplayer]  built on Tue Nov 10 19:39:16 CET 2015
[   0.009][v][cplayer] ffmpeg library versions:
[   0.009][v][cplayer]    libavutil       55.5.100
[   0.009][v][cplayer]    libavcodec      57.15.100
[   0.009][v][cplayer]    libavformat     57.14.100
[   0.009][v][cplayer]    libswscale      4.0.100
[   0.009][v][cplayer]    libavfilter     6.15.100
[   0.009][v][cplayer]    libswresample   2.0.101
[   0.009][v][cplayer] ffmpeg version: N-76584-gc2b6248
[   0.009][v][cplayer] 
[   0.009][v][cplayer] Configuration: /home/lachs0r/mingw-w64-cmake/buildroot/build32/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --disable-debug-build --enable-libmpv-shared --enable-waio --enable-lua --enable-libarchive --enable-libass --enable-libbluray --enable-dvdread --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --prefix=/home/lachs0r/mingw-w64-cmake/buildroot/build32/prefix/mingw
[   0.009][v][cplayer] List of enabled features: asm atomics av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples build-date c11-tls cplayer direct3d dlopen dos-paths dsound dvdnav dvdread dxva2-hwaccel encoding gl gl-win32 glob-win32-replacement iconv jpeg lcms2 libarchive libass libass-osd libav libavdevice libavfilter libbluray libm libmpv-shared libswresample lua mingw noexecstack optimize posix-or-mingw pthreads resampler rubberband sse4-intrinsics static-build stdatomic subprocess tv uchardet waio wasapi win32 zlib
[   0.010][v][global] config path: '' -> 'C:\Documents and Settings\Администратор\Application Data/mpv'
[   0.010][v][global] config path: 'mpv.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/mpv.conf'
[   0.011][v][global] config path: 'config' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/config'
[   0.011][v][global] config path: 'mpv.conf' -/-> 'Z:/mpv/mpv.conf'
[   0.011][v][global] config path: 'config' -/-> 'Z:/mpv/config'
[   0.011][v][global] config path: 'mpv.conf' -/-> 'Z:/mpv/mpv/mpv.conf'
[   0.011][v][global] config path: 'config' -/-> 'Z:/mpv/mpv/config'
[   0.011][v][cplayer] Setting option 'profile' = 'pseudo-gui' (flags = 8)
[   0.011][v][cplayer] Setting option 'terminal' = 'no' (flags = 12)
[   0.011][v][cplayer] Setting option 'force-window' = 'yes' (flags = 12)
[   0.011][v][cplayer] Setting option 'idle' = 'once' (flags = 12)
[   0.011][v][cplayer] Setting option 'screenshot-directory' = '~~desktop/' (flags = 12)
[   0.011][v][cplayer] Setting option 'log-file' = 'z:\log' (flags = 8)
[   0.014][v][global] config path: 'input.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/input.conf'
[   0.014][v][global] config path: 'input.conf' -/-> 'Z:/mpv/input.conf'
[   0.014][v][global] config path: 'input.conf' -/-> 'Z:/mpv/mpv/input.conf'
[   0.014][v][input] Falling back on default (hardcoded) input config
[   0.015][v][osc] Loading script @osc.lua...
[   0.016][v][global] config path: 'scripts' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/scripts'
[   0.016][v][global] config path: 'scripts' -/-> 'Z:/mpv/scripts'
[   0.016][v][global] config path: 'scripts' -/-> 'Z:/mpv/mpv/scripts'
[   0.016][v][osc] loading mp.defaults
[   0.017][v][osc] loading @osc.lua
[   0.019][v][global] config path: 'lua-settings/osc.conf' -/-> 'C:\Documents and Settings\Администратор\Application Data/mpv/lua-settings/osc.conf'
[   0.019][v][global] config path: 'lua-settings/osc.conf' -/-> 'Z:/mpv/lua-settings/osc.conf'
[   0.019][v][global] config path: 'lua-settings/osc.conf' -/-> 'Z:/mpv/mpv/lua-settings/osc.conf'
[   0.019][v][osc] lua-settings/osc.conf not found. 
[   0.020][v][cpla
------------------------------------------------------------------------------------------------------------------------------- Previous versions of the mpv with the same video file plays.

**Comment by c384mb** [comment]
"[ 0.418][v][mkv] |+ found, [ 0.068]"  This black the text I had not write this black the text automatically shows big and the black.

**Comment by wm4** [comment]
I have no idea what you're trying to say. Does mpv crash when playing this file? If so, upload the first few MB of the file somewhere (it can be as small as you like as long as it still crashes).

**Comment by c384mb** [comment]
Look video:https://www.cubbyusercontent.com/pl/NewFilm.7z/_45f360a59e0949eba21b3135b76bfd66
Pasword:re53twt$%%ty&6y785#3***u6%3434

**Comment by c384mb** [comment]
This happens with any video file, the problem is not in video files. I checked on video files mp4, flv, mkv, ts.

**Comment by wm4** [comment]
I guess it just crashes.
