### ISSUE TITLE
Looping all files in a looping playlist

### ISSUE THREAD

**Issue by Starayo** [mpv-player/mpv#2481]
I have a playlist of files I'm launching with, say, --loop-file=5, --loop=inf, and --shuffle.

What I want is for each entry in the playlist to loop 5 times before moving to the next, and the playlist as a whole will loop when it gets to the end.

Launching with these options, the first file it loads will loop 5 times, and then all subsequent files will not loop.

Is this erroneous behaviour or just not supported?

**Comment by wm4** [comment]
The --loop-file option itself is cleared when looping ends (so it will be disabled when the next file is playing). Should be possible to disable it with ``--reset-on-next-file=loop-file``, which restores --loop-file to the value on the command line each time a new file is loaded.

**Comment by Starayo** [comment]
Awesome, that works. :)
