### ISSUE TITLE
Interlaced DV material incorrectly deinterlaced with Intel vaapi output.

### ISSUE THREAD

**Issue by mleise** [mpv-player/mpv#2482]
It appears to be primarily a field order issue although seeking is also affected: pressing [left arrow] at the start of the clip cycles between 3 different pictures instead of showing the first deinterlaced field.

I noticed this while checking out if vaapi has any advanced hw deinterlacers available that can apply to DV content. I'm still not sure if Motion Compensated Deinterlacing (MCDI) only works on formats that vaapi provides decoders for, or if it is a post processing step that works with any interlaced material. (In Kodi VAAPI deinterlacers only work when the video is decoded with VAAPI as well.)

Software:
mpv 0.9.2
libva+libva-intel-driver 1.6.1
KDE Plasma 5 with compositing

ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100

vainfo:

```
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.38 (libva 1.6.1)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 1.6.1
vainfo: Supported profile and entrypoints
```

**Comment by wm4** [comment]
I'm not sure what the supposed bug is here. Are you reporting 3 different problems at once? (Sorry, I don't get it.)

**Comment by Gusar321** [comment]
The gist of it is, advanced vaapi deinterlacers (motion adaptive and motion compensated) don't work, only bob deinterlacing does. Known issue, see last few comments of #1668

**Comment by mleise** [comment]
Yeah, I've noticed that only bob deinterlacing works correctly. Hence I opened a new bug report about the advanced ones behaving strangely. I'm not involved with mpv development and as a user I can only see that it reportedly works in Kodi with e.g. MPEG-2, but not in mpv. So I consider it a fixable bug that warrants an open report. From #1668 it looks like a bug in mpv and that you have it on radar, but the bug report is closed already.
In any case, more recent versions of intel-vaapi internally fall back to bob-deinterlacing when a previous frame reference is not given. That could be used when seeking by I-frame where it would be slow to decode the previous frame.

**Comment by wm4** [comment]
mpv should be giving it the number of future/past frames required (as indicated by vaQueryVideoProcPipelineCaps()). Of course, the first frame after playback start or seeking won't have any past frames. The last video frame won't have a future frame.

**Comment by AndyFurniss** [comment]
FWIW DV historically was bff and IME ffmpeg/things will tend to assume that's what it is or encoders will say it's bff even if it isn't.

So if you have tff in dv you will need "somehow" say so.

I don't have vaapi h/w to test but with, I have an old sample of tff in dv and to get mpv to deint properly I need to explicitly call

--vf=lavfi=[yadif=1:tff]

Unfortunately my plan A which may still  work for you doesn't work for me with s/w deint as it gets called after yadif.

--vf=lavfi=[setfield=tff]

Opening video filter: [yadif mode=field interlaced-only=yes]
Opening video filter: [lavfi graph=setfield=tff]

**Comment by wm4** [comment]
Isn't this what ``--field-dominance`` is supposed to do?

**Comment by AndyFurniss** [comment]
Ah, yes and it works - I think of that as an mplayer command and didn't think to try it.

**Comment by mleise** [comment]
I've seen field number flags in DV and a time difference between fields value that can be 0 for a layman's progressive mode. I wonder if these are usable by the presentation API. (Although this is a bit OT now, since either way the videos wont play back correctly with the OP setup.)
