### ISSUE TITLE
Font spacing sometimes fubar when running from the app bundle on OS X

### ISSUE THREAD

**Issue by steinuil** [mpv-player/mpv#2483]
Sometimes the font spacing disappears like in the screenshot below when I open the mpv bundle by itself or with a file.
![dork-soles](https://cloud.githubusercontent.com/assets/4672967/11163789/e9d8f8fa-8adc-11e5-9986-fc5dcad301c8.png)
Note that this only ever happens when running from the bundle.
I think it's related to the "Drop files to play here" screen, because when it happens while playing files, that screen appears for a split second (with 0 font spacing) before the file starts to play.
[Here are the logs from both when it happens by itself and when playing a file, and my config.](https://gist.github.com/steinuil/d094d4496aae689ce9b5)
I'm using mpv 0.13.0 on OS X 10.11. I've also seen it happen on 0.12.0 so the bug was probably introduced there.

**Comment by wm4** [comment]
libass issue. Or maybe build issue.

**Comment by franzf** [comment]
Same started happening here a couple days ago. I'm building it with the standard homebrew formula. I waited to see if the libass update (0.13.1) would change anything, but nope.

![a](https://cloud.githubusercontent.com/assets/869168/11640545/1239d14e-9d01-11e5-8c6b-f87b094e7da7.jpg)

**Comment by wm4** [comment]
Probably the same as #2564 - a homebrew build issue that happens pretty often.

**Comment by franzf** [comment]
You're right, deleting my copies of mpv and dependencies and re-installing them with homebrew fixed it.

**Comment by wm4** [comment]
Then I'm assuming these issues are all the same.
