### ISSUE TITLE
from 0.9.2 to 0.10: same settings but dropping tons of frames

### ISSUE THREAD

**Issue by Soukyuu** [mpv-player/mpv#2484]
Arch linux x64, using mpv-git. Everything was fine back on `mpv-git-0.9.2_1388_g061b947`, then I updated to `mpv-git-0.10.0_25_gfea1e09` and started getting dropped frames with these settings:

```
opengl-hq:cscale=ewa_lanczossoft:scale=ewa_lanczossharp:dscale=mitchell:interpolation:deband-grain=48:fancy-downscaling:target-prim=bt.709:cscale-antiring=0.9:deband-range=8:tscale=oversample:temporal-dither:scaler-resizes-only:deband-threshold=100:sigmoid-upscaling:scale-antiring=0.8:deband:dither-depth=auto:pbo
```

Also, vapoursynth is loaded using vf.

The same happens on any snapshot past the version above, including the current `mpv-git-0.13.0_10_g0f3dede` snapshot. Did any defaults change between 0.9 and 0.10? My settings pretty much saturate my hardware (Phenom II X4 970, nvidia 260GTX), so I'm thinking it might be that. 

I tried disabling deband, but that doesn't do anything.

I'd have reported this earlier, but I didn't have much time to watch stuff lately, and when I did my PC was under heavy load, so I attributed the stutters to that, instead.

**Comment by wm4** [comment]
First try to find out if it's caused by vapoursynth, then by which opengl settings.

**Comment by Soukyuu** [comment]
Disabling vapoursynth does solve it, but that's only because it's very heavy on resources, so any marginal increase in processing power needed by mpv pushes it over the edge. I switched between the mpv versions leaving vapoursynth fixed, and with the earlier mpv versions everything is (mostly) smooth, I got about 12 dropped frames over 25 minutes. With the newer mpv version, I get about 1-2 drops per second, and the picture is stuttering visibly.

**Comment by wm4** [comment]
That seems strange. Are you able to bisect this and find the change which caused it?

**Comment by Soukyuu** [comment]
I tried messing with opengl-hq settings and removing `scale=ewa_lanczossharp` or `cscale=ewa_lanczossoft` gets rid off the framedrop as well. Changing d/tscale has no effect. Disabling interpolation does slow down the framedrops to about 1 per 3 seconds.

I have heard of bisecting, but never did it before. I'll try going through the commits and pinpointing the one that caused it. If you have a good tutorial on bisecting, do tell.

**Comment by Soukyuu** [comment]
Well, bisect left me at the commit that integrated deband into mpv instead of using deband.glsl - which made me realize that the only reason there were no framedrops with the early version was because it was failing to parse the unknown option "deband" and didn't apply ANY of the other, valid options, including the scaling ones. 

Would it be possible to change this so that failing to parse one option would either not stop trying to parse the rest, or just stop and exit with an error message, so it's clear something has gone wrong? The way it is now, unless you're looking at the console, you won't notice some option failed to parse and will end up with the wrong conclusions.

Back to the actual issue, it used to work with ewa_lanczos for scaling, so it must be something about my system. I'm going back in snapshots at the moment to try and find one where it still works. If I won't find one, then there must be something wrong with my system on the hardware level, I guess.

**Comment by lachs0r** [comment]
Should be noted that the deband defaults were quite heavy before 0.12.0.

**Comment by lachs0r** [comment]
Also I can test this with a similar system (Phenom II 955, 9800 GT) later.

**Comment by Soukyuu** [comment]
The current issue is happening regardless of deband being on or off (sorry if I wasn't being clear about that). Once I saw the commit that supposedly caused the issue, I re-ran bisect with deband off and ended up having frame drops all over the place on my good commit - because now it parsed all the options - including (c)scale which seems to causing the drops for me at the moment.

Basically, it doesn't seem to be an mpv issue. I'm thinking some update (mesa or the nvidia drivers maybe) might have caused this.

**Comment by Soukyuu** [comment]
Oh, I've tried old versions of mvtools and vapoursynth just to be sure, and it's not it either.

**Comment by wm4** [comment]
If you use the closed source nvidia drivers, Mesa isn't involved at all.

**Comment by Soukyuu** [comment]
Well, it's not the nvidia driver either. Mine's a legacy card so there aren't any updates for it anymore. I'm kind of lost on this one atm. Which libraries does resizing in mpv make use of, if any?

**Comment by wm4** [comment]
It uses OpenGL only, which depends on the GPU and GPU driver.

**Comment by Soukyuu** [comment]
Well, then I have no idea what caused it... tried downgrading nvidia drivers, and it's still the same. A workaround I've found is to set `scale-radius=1.0`, anything >=2.0 starts producing large amounts of dropped frames, with 1.9-1.1 they get progressively fewer and 1.0 are only dropping now and then (not noticeable on playback).
