### ISSUE TITLE
Can't control the player from command line after foregrounding it from the background

### ISSUE THREAD

**Issue by riflex** [mpv-player/mpv#2485]
After starting mpv 0.13.0:
- in the background (`mpv <file.extension> &`), then foregrounding it (with `fg`)
- or suspending it (with `ctrl-z`), then restarting it (with `bg`), and then foregrounding it (with `fg`)

You'll lose control to the interactive command line, although the terminal status line remains updated.

**Comment by wm4** [comment]
Your shell probably doesn't restore the terminal state. If so, it's not our problem.
