### ISSUE TITLE
 API callback function for get frame.

### ISSUE THREAD

**Issue by Xuno** [mpv-player/mpv#2486]
Can the API have a callback function for get frame pointer of external data instead of using internal frame?
In format of FBO defined by fbo-format.

**Comment by wm4** [comment]
What would this be useful for?

**Comment by Xuno** [comment]
If I have own source of frames and want use mpv as preprocessor of frame by GL Shaders, and them render in own OpenGL context. Without use any tmp files.

**Comment by lachs0r** [comment]
This is a video player, not a shader library. If you want to use mpv’s shaders, just use mpv’s shaders.
