### ISSUE TITLE
Some x265 encoded files have some seek problems

### ISSUE THREAD

**Issue by Dantenerosas** [mpv-player/mpv#2487]
Latest Windows build. Files from here https://kat.cr/rick-and-morty-s1-complete-uncensored-1920x1080-phr0sty-t9714484.html
Some serious problems with seeking. When pressed Left\Right it seeks not 5 secs but something around 1 min. With other x265 files works fine

P.S. Sorry if hard to understand English isn't my mother tongue

**Comment by lachs0r** [comment]
Left/Right by default performs keyframe seeks. Use (slower) precise seeking (Shift+Up/Down by default) for those files.
