### ISSUE TITLE
Dropped frames and choppy video with recent build.

### ISSUE THREAD

**Issue by Entheogen010** [mpv-player/mpv#2488]
Hello, I have had no problems with stuttering video and dropped frames until today. Any video I play with `vo=opengl-hq` drops hundreds of frames. VPDAU works fine. 

The only error I see is:
```
libEGL warning: DRI2: failed to authenticate
[vo/opengl-hq] Suspected software renderer or indirect context.
```

Relevant information:
OS: Ubuntu 14.04 LTS 64bit
Graphics Card/Driver: NVIDIA 670M/proprietary 340.93
mpv version:
```
mpv git-384b13c (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Sat Nov 14 04:23:13 UTC 2015
ffmpeg library versions:
   libavutil       55.5.100
   libavcodec      57.15.100
   libavformat     57.14.100
   libswscale      4.0.100
   libavfilter     6.15.100
   libswresample   2.0.101
ffmpeg version: N-76637-gedd0c1d
```

Any ideas?

**Comment by hrzhu** [comment]
Having the same problem since I install mc3man's latest build.

**Comment by Entheogen010** [comment]
That is also the build I have installed, via his PPA.

**Comment by kevmitch** [comment]
You probably need to specify the x11 backend instead of the new default x11egl, which Nvidia is apparently crappy at.

    --vo=opengl-hq:backend=x11

**Comment by Entheogen010** [comment]
kevmitch, I tried that, same results.

**Comment by wm4** [comment]
>[vo/opengl-hq] Suspected software renderer or indirect context.

Either your drivers are broken, or this mpv build is seriously broken.

**Comment by Entheogen010** [comment]
It worked fine for almost a year up until last night when I updated, so I think I'm going to chalk up to the build. Is there any more information that I can provide that would further clarify the issue?

**Comment by wm4** [comment]
Post a full log with -v when playing something.

**Comment by hrzhu** [comment]
Switching x11 backend solves my problem. My driver is nvdia-352.

**Comment by mc4man** [comment]
I believe it's fixed now, entirely  my fault, sorry for any inconvenience. New package should be available in an hr. or so.

**Comment by hrzhu** [comment]
@mc4man could you explain a bit more, I have the same problem with mpv built by mpv-build. How do I fix this?

**Comment by mc4man** [comment]
@hrzhu 
Somehow here libgl1-mesa-dev was removed from my debian/control file. For various reasons, the least of which I'm now using nvidia gpu on this laptop, I didn't notice vaapi support was gone.
Wrongly assuming that libegl1-mesa-dev was now required for vaapi I added it as a dep even though 14.04 has mesa 10. While that allowed vaapi support it caused issues as seen here & more.
So maybe ck. your control file.
(- if the intention on mpv's part is you should use libegl1-mesa-dev on installs that are on mesa 10 then you'll only get proper playback with  limited combo's of hwdec & vo whether using Intel or Nvidia gpu's

**Comment by Entheogen010** [comment]
@mc4man, the new build fixes the problem. Thank you.

**Comment by wm4** [comment]
@mc4man: I have not the slightest clue what you're trying to say, but nvidia will work even if EGL is enabled.

**Comment by mc4man** [comment]
@wm4 
simple - If libegl1-mesa-dev is used in a build for installs that have mesa 10.x - 
Intel - 
hwdec=auto  vo=opengl or opengl-hq vaapi-copy is used (works but much higher cpu than vaapi
hwdec=vaapi vo=vaapi (works but no vsync in fullscreen
hwdec=vaapi vo=opengl or opengl-hq - software decoding

nvidia - 
hwdec=auto or vdpau vo=vdpau (works fine
If vo=opengl/opengl-hq is used with hwdec=auto then software decoding
If vo=opengl  is used with hwdec=vdpau  then software decoding
If hwdec=vdpau is used with no vo= specified then a vo of opengl is used with hwdec of vdpau
If vo=opengl-hq is used with hwdec=vdpau then complete crap as per this bug

If libegl1-mesa-dev is not included in builds for mesa 10 installs then all hwdec & opengl combos work as before.

**Comment by wm4** [comment]
Can't make sense out of your writing.

For one, hwdec does not influence the choice of the VO, and I think you might be confusing software decoding and software rendering.

**Comment by mc4man** [comment]
Pretty simple, mp.conf options for hwdec & vo followed by results. 
So for example -
"if vo=opengl-hq is used with hwdec=vdpau or auto then complete crap as per this bug"
$ mpv --no-config -hwdec=vdpau  -vo=opengl-hq   '/home/doug/Videos/amostviolentyear-clip1_h1080p.mov' 
Playing: /home/doug/Videos/amostviolentyear-clip1_h1080p.mov
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
libEGL warning: DRI2: failed to authenticate
[vo/opengl-hq] Suspected software renderer or indirect context.
VO does not support requested hardware decoder, or loading it failed.
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl-hq] 1920x816 yuv420p
AV: 00:00:02 / 00:01:00 (3%) A-V:  0.000 Dropped: 46
The exact same also occurs with -hwdec=auto  -vo=opengl-hq

"If vo=opengl is used with hwdec=auto then software decoding"
Plays ok, no dropped
$ mpv --no-config -hwdec=auto  -vo=opengl   '/home/doug/Videos/amostviolentyear-clip1_h1080p.mov' 
Playing: /home/doug/Videos/amostviolentyear-clip1_h1080p.mov
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
libEGL warning: DRI2: failed to authenticate
[vo/opengl] Suspected software renderer or indirect context.
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_32
libva info: va_openDriver() returns 0
AO: [pulse] 44100Hz stereo 2ch float
Using software decoding.
VO: [opengl] 1920x816 yuv420p
AV: 00:00:02 / 00:01:00 (3%) A-V:  0.000

"If hwdec=vdpau is used with no vo= specified then a vo of opengl is used with hwdec of vdpau"
This one actually does use hwdec with opengl unlike above
$ mpv --no-config -hwdec=auto    '/home/doug/Videos/amostviolentyear-clip1_h1080p.mov' Playing: /home/doug/Videos/amostviolentyear-clip1_h1080p.mov
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
libEGL warning: DRI2: failed to authenticate
[vo/opengl] Suspected software renderer or indirect context.
AO: [pulse] 44100Hz stereo 2ch float
[vo/opengl/x11] Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.
Using hardware decoding (vdpau).
VO: [opengl] 1920x816 vdpau
AV: 00:00:10 / 00:01:00 (17%) A-V:  0.000

Can't see any reason in use for egl when mesa is at 10 so not compiling in eliminates any user's conf from possibly getting unexpected results like in this orig. report

**Comment by hrzhu** [comment]
I can confirm what mc4man says. If I build mpv with libegl1-mesa-dev (on my system it's libegl1-mesa-dev-lts-vivid), vo=opengl hwdec=vdpau falls back to sw decoding and has frame drop. The frame drop is much more obvious if I use opengl-hq. Workaround is to use opengl:backend=x11 or simply don't build mpv with egl.

**Comment by hrzhu** [comment]
I just install Xubuntu 16.04 development branch. It seems mc3man's mpv build for xenial enables more opengl backends than the trusty build.
```
mpv --vo=opengl:backend=help
OpenGL windowing backends:
    auto (autodetect)
    wayland
    x11egl
    x11
```

In ubuntu 16.04, vo=opengl hwdec=vdpau works fine and has no frame drop although it prints some error message:
```
libEGL warning: DRI2: failed to authenticate
[vo/opengl] Could not create EGL context!
```
