### ISSUE TITLE
MPV 2015-11-10 does not work on Windows XP

### ISSUE THREAD

**Issue by PapoyBanana** [mpv-player/mpv#2489]
This application has failed to start because AVRT.dll was not found. That is the error message I get when running MPV 2015-11-10 (32 bit) on Windows XP (32 bit). Can anybody help?

![mpv 2011-11-10](https://cloud.githubusercontent.com/assets/13683419/11168738/541601f2-8bcf-11e5-86d8-4dd5c3e98f36.png)

**Comment by lachs0r** [comment]
“Accidentally” broken with 16cd20c46f02a052f06742329dc375a695bb6e0b.
I suggest using an older build for now (since you don’t seem to have any problem with using outdated software).

**Comment by PapoyBanana** [comment]
Yes I'm using the 2015-10-29 version now. Ok then.

**Comment by wm4** [comment]
We're considering entirely dropping XP support.

**Comment by haasn** [comment]
It's almost 2016.

**Comment by c384mb** [comment]
For Linux there is no new version. Not who does not upgrade to mpv in the repository Ubuntu. There are given 9 version. I couldn't  to collect mpv. Me need to collect the other programs to collect mpv on Linux, error, eror and again error. I am not interested to learn commands Linux.

**Comment by wm4** [comment]
For Linux look at: https://mpv.io/installation/

Ubuntu and Debian like packaging old software of a software and not maintaining it - so don't use their default packages.

**Comment by lachs0r** [comment]
How does your inability to use a Linux distribution have anything to do with Windows XP?

**Comment by c384mb** [comment]
I watched all of that for me there's no friendly option than Windows. There are poorly written for who never used Linux. Don't forget to foreigners more difficult + this https://translate.yandex.ru/, https://translate.google.com, https://www.bing.com/translator Choose any and all translations not exactly.

The advice to go with Windows XP in favor of Linux does not suit me. I also use Windows XP. 
Maybe I'll change Windows XP on Windows but not now. I not gamer me not need directX10-12.

Не забывайте, что Америка это не вся планета это только Америка.

**Comment by c384mb** [comment]
https://vimeo.com/136578178

**Comment by c384mb** [comment]
I know much video players and coders, decoders, they don't use links. I look mostly via the Internet.

**Comment by wm4** [comment]
Less than 5% users on lachs0r's download page. We will remove XP support.

Please consider that keeping XP support causes just as much stress to us as switching to a better OS is for you. More and more software will drop XP support. (Chrome next April.)

**Comment by SPTX** [comment]
"switching to a better OS"
Now that's quite the dishonest choice of words. I don't really care that you drop support for XP, you've done a magnificent work until now so I have no issue considering the mpv version I have as the definitive one. But don't spew propaganda in support to the latest horrors microsoft tries to force down our throats. If people are still using XP for god knows how many years and versions of windows later, there has to be better and legitimate reasons than just "being an angry nerd who doesn't like evolution".
If you were honest you would drop 32bit support altogether.

This is coming from someone who programs mainly on mac OS, debian at home, and has a partition of 7 installed for (marginal) necessity, so you can't really appeal to lack of culture or fear of the unknown.

**Comment by wm4** [comment]
Technically, newer Windows is most definitely better. If you dispute this, then just as a wasrning, I'll have to say I'll force this point down your fucking throat.

If you don't want to eat Microsoft's (or Apple's) bullshit, then Linux or BSD are your only choices. Don't complain, take some slight effort and walk the way to freedom.

>  If you were honest you would drop 32bit support altogether.

32 bit support doesn't require any extra work, other than by the one building it.

**Comment by rossy** [comment]
@SPTX I understand people rejecting Windows 8.1 and 10 because of the Windows Store and UWP shit, but was there anything wrong with Windows 7?

For the record, XP was far from perfect. My favourite XP nightmare was #1325, but there have been a number of weird XP-isms that affected mpv, like the lack of a mature threading API and the inability to spawn processes with inherited handles in a thread-safe way. Believe it or not, Vista and 7 fixed a lot of things that were absolutely broken in older Windowses. I can think of a lot of ways that 7 is a better OS than XP, but I can't think of anything I miss about XP that wasn't in 7.

**Comment by haasn** [comment]
Personally I miss Windows ME. The constant crashing and malware really made it feel like home.

Would anybody be willing to port mpv to the clearly superior ME platform?

**Comment by JohnSmith25** [comment]
>Less than 5% users on lachs0r's download page. We will remove XP support.

It's all in the numbers:
Only 1% of computer users use Linux overall.
You should drop support for GNU slash Linux.
t. Linux Mint user

**Comment by RosinSmoke** [comment]
Linux user can install mpv from repository using package manager, who would download a package with browser in their right mind?
