### ISSUE TITLE
More playlist manipulation - shuffle toggle

### ISSUE THREAD

**Issue by sljunkie** [mpv-player/mpv#2491]
Continuing #965, `playlist_shuffle` can be used to create a shortcut equivalent to `--shuffle` in the command line, for instance I have:

```
$ cat ~/.config/mpv/input.conf 
b playlist_shuffle
```

It would be better if `playlist_shuffle` was toggleable - once put on shuffle, there's no way to unshuffle the playlist in the same `mpv` instance.

**Comment by wm4** [comment]
The shuffle command literally reorders the playlist, so shuffle can not be made a toggle.

**Comment by sljunkie** [comment]
Can it be made toggeable by storing the original playlist in mpv's memory (a variable or object)?

**Comment by sljunkie** [comment]
Because the built-in command loop with L is very handy; a similar command with shuffle would be wonderful to use mpv as a music player.

For instance, mpv already support cue sheets - a very nice feature most music players do not have.

**Comment by wm4** [comment]
>Can it be made toggleable by storing the original playlist in mpv's memory (a variable or object)?

So what would happen if the playlist changes while it's in the shuffled state?

**Comment by devros42** [comment]
This would be a great addition.  Same way VLC deals with turning shuffle on and off.

**Comment by wm4** [comment]
This should probably be closed, see commit above.
