### ISSUE TITLE
[Feature Request] Always on top only when playing

### ISSUE THREAD

**Issue by Poilaucul** [mpv-player/mpv#2492]
Is it possible add an option to keep the player always on top only when a file is playing?

**Comment by AirPort** [comment]
There's a user script for that: https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/ontop-playback.lua

**Comment by avih** [comment]
Run with `--ontop`, or press T (`shift-t`) to toggle while playing.

**Comment by wiiaboo** [comment]
You can also use `MOUSE_BTN2 keypress SPACE` so it runs the same command as the one associated to "space".

**Comment by wm4** [comment]
So I'd say this is up to scripts or user configured input bindings.

**Comment by benchile55** [comment]
Thanks avih

> Run with `--ontop`, or press T (`shift-t`) to toggle while playing.

your info  worked out good !
