### ISSUE TITLE
nnedi3 upscaling does nothing.

### ISSUE THREAD

**Issue by mac1202** [mpv-player/mpv#2493]
Hi I try the new nnedi3 built in option to replace the nnedi3 vapoursynth script but i dont get the same result. I dont get any improvement like you can see with the screenshot.
Original video
![mpv](https://cloud.githubusercontent.com/assets/5730439/11183689/9d62e196-8c73-11e5-8897-9e6f303a5ec5.png)
 
mpv built in nnedi3
![mpv-nnedi](https://cloud.githubusercontent.com/assets/5730439/11183722/bd60ccec-8c73-11e5-9ee5-9d7123e45817.png)

vapoursynth nnedi3
![mpv-nnedi-vapoursynth](https://cloud.githubusercontent.com/assets/5730439/11183739/c977ba0e-8c73-11e5-9a9f-027d4fad688e.png)

here my vo option : vo=opengl-hq:deband:prescale=nnedi3:nnedi3-window=8x6
Am i doing something wrong ?

**Comment by lachs0r** [comment]
Well you do kind of need to change the window size to make it scale something.

**Comment by mac1202** [comment]
Changing the windows size doesnt help there is no improvement il video quality with the built in nnedi3. The video isnt upscaled.

**Comment by lachs0r** [comment]
I mean the player window size.

I shouldn’t have to explain this but here I go: You get a larger video with 
the Vapoursynth version because that changes the input video size. Enabling a 
prescaler in mpv does not change the underlying video source and will not 
change the displayed size either. You just need to resize the player window 
for that, for example with --window-scale=2.

**Comment by mac1202** [comment]
Even with --window-scale=2 the quality is the same with or without nnedi3 option.

**Comment by bjin** [comment]
1. post the log, nnedi3 could be disabled if opengl version is low
2. tell how you take the screenshot of mpv

**Comment by mac1202** [comment]
Here's the log : http://pastebin.com/GzmPfWDr
And screenshot was taken using the s shortcut in mpv.

**Comment by bjin** [comment]
s keybinding wont capture scaled video,  please use "screenshot window" command or somme external tool

**Comment by mac1202** [comment]
Ok changing the way i take screenshot i get better quality screenshot. But they all exactely the same. No difference in quality. Maybe  I was expecting to much after seeing this kind of Comparison screenshots : 
http://abload.de/img/mn-full55c1a.jpg
http://abload.de/img/nnedi3-fullvdfok.jpg

**Comment by rr-** [comment]
Before drawing such conclusion, please test on a wider range of sources.

**Comment by sda89ha9** [comment]
try option prescale-downscaling-threshold=0

**Comment by bjin** [comment]
> Maybe I was expecting to much after seeing this kind of Comparison screenshots : 

That's no doubt an extreme example, I suspect that it would be at least 4x upscaling and probably "bilinear" is used for comparison to produce such awful aliasing. If your only purpose is just to reduce aliasing for 4x upscaling, "superxbr" is actually a better choice than "nnedi3", but it's a horrible prescaler for other source (in >2x upscaling).

> try option prescale-downscaling-threshold=0

I believe it's unrelated.
