### ISSUE TITLE
Resolution range settings

### ISSUE THREAD

**Issue by paulguy** [mpv-player/mpv#2495]
I tried setting the NNEDI3 shader on by default which works amazingly for standard def content, but when I go to play an HD video it becomes a choppy mess.  I'm wondering if there could be made a way to accomplish this in the config file.  Maybe using the property expansion but adding <, >, <=, >= comparisons for numerical values so I can just fill in 'none' or 'nnedi3' in the config file, if such a thing even works as it is; I haven't tested that.  Alternatively, maybe using the profiles system somehow.  I know I can mess with prescale-downscaling-threshold but picking an optimal value would be tricky, and just picking 1.0 would fail in the case of fullscreening 1080p video, since that'd end up being scaled up anyway.  For the moment I have a separate profile I need to specify on the command line that specifies different VO settings to enable the NNEDI3 shader, but that's not particularly great.

**Comment by Argon-** [comment]
You might be able use something like this: https://gist.github.com/selsta/9ac023688885053d42ca
But instead setting a different VO (other than specified in your mpv.conf) when your computer is not attached to a charger you simply check the property `video-params/h` https://mpv.io/manual/master/#command-interface-video-params/h for the value you desire.

**Comment by wm4** [comment]
We _might_ get the ability to do such profiles later (or at least to make implementing a script managing such profiles easily). But right now, there's nothing, other than ``vo_cmdline`` hacks, or trying to set the ``vo`` option before the VO is created.

**Comment by bjin** [comment]
> just picking 1.0 would fail in the case of fullscreening 1080p video, since that'd end up being scaled up anyway

Sorry, I don't get you here. What's the size of your monitor? If you set `prescale-downscaling-threshold` to 1.0 and then open a 1080p video, NNEDI3 won't be used unless you own a 4k monitor (like `3840x2160`), is it the case?

**Comment by paulguy** [comment]
Yeah I have a 4K monitor,   Thanks for the responses, I'll check out that script.

**Comment by paulguy** [comment]
Weirdly, 720p videos scale up with NNEDI3 just fine with no drops but 1080p is considerably worse, down to like 3-5 FPS.  I also notice that I had to set the upload mode to shader as UBO mode was far too slow at any resolution.

**Comment by bjin** [comment]
@paulguy better open another issue to discuss the performance of NNEDI3

> Weirdly, 720p videos scale up with NNEDI3 just fine with no drops but 1080p is considerably worse, down to like 3-5 FPS.

What's your graphics card, driver version, OS? How do you measure the fps number? What's your `framedrop` `nnedi3-neurons` `nnedi3-window` setting?

**Comment by paulguy** [comment]
I figured it was some kind of nonlinearity in how the shader works or how the graphics card/driver responds to the larger texture and whatnot.

**Comment by lachs0r** [comment]
https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua
