### ISSUE TITLE
Tearing with opengl-hq and not with opengl on Gnome

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#2501]
Hello,

I'm on Fedora 22 with Gnome 3.16, MPV 0.13 and Nouveau drivers. In windowed mode I have tearing with opengl-hq and not with opengl. In fullscreen mode there is no tearing with both opengl-hq and opengl.

```
mpv --no-config --vo=opengl-hq movie.mkv
```

```
mpv --no-config --vo=opengl movie.mkv
```

Also note that when I start to play a movie in fullscreen the video is choppy during the first seconds with opengl-hq before Mutter switch to unredirect mode. It's smooth with opengl.

Do you know why and how can this be fixed ?

Thank you

**Comment by wm4** [comment]
Maybe it's too slow, or there is timing dependent behavior. Retry with git master.

**Comment by Paviluf** [comment]
It's the same with MPV git master.

**Comment by Paviluf** [comment]
Don't know if that help but on my other partition with Netrunner 14.2 (Kubuntu 14.04 derivative), MPV 0.12 and Nvidia proprietary drivers there is no tearing in windowed mode with opengl-hq.

**Comment by Paviluf** [comment]
There is dropped frames with Nouveau and Opengl-hq in windowed mode. Can it be the root of the tearing ?

**Comment by Paviluf** [comment]
There is no tearing with Nouveau and Opengl-hq in windowed mode in Plasma 5. Can it be a bug in Mutter ?

**Comment by Paviluf** [comment]
On the advice of Rui Matos, a Mutter developer, I filed a bug to Nouveau. We will see if the bug lie in Nouveau or Mutter ;)

https://bugs.freedesktop.org/show_bug.cgi?id=94964

**Comment by Paviluf** [comment]
Well I activated dri3 on nouveau and the tearing with opengl-hq with windowed mpv is gone !

**Comment by wm4** [comment]
Good enough, also the original reporter terminated his github account.
