### ISSUE TITLE
Automatically enable the unredirect mode of the compositor

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv#2502]
Hello,

Is it possible to implement the possibility to automatically enable the unredirect mode of the compositor in fullscreen with this freedesktop.org feature ?

http://cgit.freedesktop.org/xdg/xdg-specs/tree/wm-spec/wm-spec.xml#n1579

Thank you.

**Comment by wm4** [comment]
Sounds like a good idea.

**Comment by Paviluf** [comment]
It doesn't seems to work. When Mutter switch to unredirect mode there is a little glitch about 3s after the start of the video. This glitch still happen with --x11-bypass-compositor=yes.

Is there a way to properly test it ?

**Comment by wm4** [comment]
It's enabled by default. You can check with xprop whether the hint is correctly set.

**Comment by Paviluf** [comment]
xprop display this _NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 1
Is it ok ?

**Comment by wm4** [comment]
According to the docs you linked, yes.

**Comment by Paviluf** [comment]
So I guess that I have to check that with Mutter devs.

**Comment by Paviluf** [comment]
> It doesn't seems to work. 

For the record it was a Mutter bug (https://bugzilla.gnome.org/show_bug.cgi?id=758544)

**Comment by berniyh** [comment]
This caused some weird behavior in kwin (which could be a kwin bug), but tracking it down to mpv's usage of said feature and reading this and the man page I found the explanations (uh none ...) very unsatisfying.

The feature was originally brought in for games that would possibly suffer from performance issues if not bypassing the compositor.
For a video player, after reading the linked page, the man page and this issue, I still have no idea whatsoever why this might be a good idea.
Is it performance? Tearing?
I don't really see a difference in both.
The man page should definitely tell you why you might want to enable or disable the feature.

**Comment by wm4** [comment]
What's so surprising? For video players, the influence of timing can be just as critical (or maybe more) than games.

I might agree that this should be applied only in fullscreen mode though, also see #2582. On the other hand, I'd expect a WM to ignore this hint if it influences user experience negatively enough.

**Comment by berniyh** [comment]
Ok, so it's about timing. Well, mpv will tell me that it assumes timing to be inaccurate no matter if the compositor is bypassed or not. Or is that a bug on its own?

I'm also not convinced that timing is that important for a video player. For recording, sure, I get that, but for playing?
If there is a continuous desync caused by the compositor, then that sounds like a bug in the compositor.

Regarding fullscreen, that would make sense if it's the only app running on a single screen (similar to what a game would do).
But not if you have 2 (or more) screens like I do. I'm watching a video in fullscreen right now when I'm writing this text and I fully expect the compositor to do everything the same way as always.

**Comment by wm4** [comment]
>Well, mpv will tell me that it assumes timing to be inaccurate no matter if the compositor is bypassed or not. Or is that a bug on its own?

Is that the vdpau VO? It uses the _NET_WM_CM_Sx atom to check whether the compositor signals compositing. I would hope that works as expected.

> I'm also not convinced that timing is that important for a video player. 

Judder etc. is one of the main complaints related to video timing issues.

> But not if you have 2 (or more) screens like I do. I'm watching a video in fullscreen right now when I'm writing this text and I fully expect the compositor to do everything the same way as always.

I don't know what's an ideal solution. Well, ideally compositors would have no bad influence on timing.

**Comment by berniyh** [comment]
> Is that the vdpau VO? It uses the _NET_WM_CM_Sx atom to check whether the compositor signals compositing. I would hope that works as expected.
Yes, only with vdpau, afaics. xv does not complain at all.
I get the message 
> [vo/vdpau] Compositing window manager detected. Assuming timing info is inaccurate.
no matter if I set --x11-bypass-compositor to yes or no.
> I don't know what's an ideal solution. Well, ideally compositors would have no bad influence on timing.
I'm ok with this, if the manpage is improved here. 
Add something like:
If set to yes, this can lead to a (partial) loss of compositing functionality while the video is running.
If set to no, you might lose timing accuracy.

Maybe with some improved wording (you are the video experts ;)).
