### ISSUE TITLE
MPV on Windows tears in fullscreen mode, but not in windowed mode

### ISSUE THREAD

**Issue by Daktyl198** [mpv-player/mpv#2504]
System info:
Windows 10 64-bit
Latest windows release available at this time: http://mpv.srsfckn.biz/mpv-x86_64-20151110.7z
Latest Youtube-dl available right now
this video is where I noticed it: https://www.youtube.com/watch?v=B_k4Zi4dR0c
The only config I have is:
```
vo=opengl-hq:scale=ewa_lanczossharp:deband

[pseudo-gui]
idle=yes
```

The video plays tear-free while in windowed mode, even maximised, but when going fullscreen suddenly there is a TON of tearing. Going back to windowed mode fixes the tearing.

I've tried using `video-sync=display-resample` to no effect.

**Comment by lachs0r** [comment]
That’s going to be fixed in the next release, I hope. In the meantime, you can add `dwmflush=windowed` to your `opengl-hq` suboptions.

**Comment by JohnDDuncanIII** [comment]
+1. The ```dwmflush=windowed``` option works great, for now.

**Comment by man0000** [comment]
I have the same problem (W10Pro x64 10586.29). 
Horizontal lines in some scenes with mp4 local HD videos
Testing previous releases, the mpv-x86_64-20151029 one doen't suffer from the bug. It started from next one.
dwmflush=windowed doesn't solve me anything.
mpv-x86_64-201511211 still presents the bug.
THANKS...

**Comment by kevmitch** [comment]
The regression is interesting. However, you might just want to use ```vo=opengl:backend=dxinterop``` now if it works with your graphics card (make sure you have the latest drivers for Intel).

**Comment by man0000** [comment]
Sadly, it doesn't work. Play starts but I have no player visible. Only hear sound and have to close mpv.exe with Task Manager.
vo=opengl working flawless. mpv dissapears when I add vo=opengl:backend=dxinterop

mpv-x86_64-201511211 and Core i7 2600 with HD2000 and latest drivers available installed.

THANKS for the reply...

**Comment by kevmitch** [comment]
Do either ```vo=opengl:backend=dxinterop``` or ```vo=opengl:backend=angle``` work with the latest release?

**Comment by man0000** [comment]
The issue is fixed in last build.

**Comment by wm4** [comment]
With which backend?

**Comment by man0000** [comment]
I'm using vo=opengl-hq:backend=angle to avoid another issue that I reported. 
It works with or without the -hq modifier

**Comment by Daktyl198** [comment]
This issue is indeed fixed with the latest build on Windows (using either vo=opengl, opengl-hq, or even opengl-hq:backgend=dxinterop for me). I'll close this issue for now.

**Comment by man0000** [comment]
THANKS...

**Comment by radgeRayden** [comment]
I have experienced this same issue on last release.

**Comment by aspera7** [comment]
Also experiencing this issue. Latest mpv build. Windows 10 latest version. Nvidia 1060 6gb 388.43 driver version, i5 4670k. Tried various settings mentioned in the thread but to no avail (though I'm not sure whether they were applied to begin with, since mpv provides no feedback and I was unable to generate the log)

**Comment by man0000** [comment]
Hi,

I haven't seen the issue since I last reported fixed.
All I have in mpv.conf is this :

profile=gpu-hq
vo=gpu
gpu-context=auto
hwdec=auto

mpv version : 0.28.0-139-gdba143de4d.

**Comment by aspera7** [comment]
> All I have in mpv.conf is this :

>profile=gpu-hq
>vo=gpu
>gpu-context=auto
>hwdec=auto

Just tried this, no change
