### ISSUE TITLE
There is some problem with vo=opengl hwdec=vaapi in KDE Plasma 5

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2505]
System: openSUSE Leap 42.1
Desktop: KDE Plasma5

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

If I set --vo=vaapi, i5-4460 cpu usage of every core will be high.
<img src="http://i.imgur.com/azpmQRM.png">

If I set --vo=opengl --hwdec=vaapi, it will become laggy, one of the cpu core usage will be high.
<img src="http://i.imgur.com/flZAArb.png">

I have tested the hardware decoding with opengl vaapi of VLC, and it doesn't cause the problem, maybe it is mpv's bug?

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

If I set --vo=vaapi hwdec=vaapi, the cpu usage of every core will be low, is it recommended?
<img src="http://i.imgur.com/ogNBHox.png">

**Comment by kevinlekiller** [comment]
I can not reproduce.

Which mpv version are you using?

07c546b2b494a620edc98dadd5dd78a052ec6783 and 6b22b216514ee2eb784711f4539410d3b312a4fd possibly fixes these issues.

**Comment by laichiaheng** [comment]
@kevinlekiller 
mpv 0.13.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Nov 10 2015
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.2
