### ISSUE TITLE
Is there a replacement for HRTF?

### ISSUE THREAD

**Issue by qitta** [mpv-player/mpv#2507]
Hi,

I've just realized that the HRTF (head-related transfer function) audio filter has been removed in release v0.11.0. As it was a quite nice feature while watching multichannel movies with headphones, I wonder myself if there is a replacement for this audio filter? I've searched through a bunch of lavfi audio filters yesterday but unfortunately I couldn't find an equivalent replacement.

Is there a lavfi replacement filter for hrtf I've missed? 

Many thanks,
qitta

**Comment by kevinlekiller** [comment]
From what I coul find, others are using Openal:

https://github.com/mpv-player/mpv/issues/1073

https://github.com/mpv-player/mpv/issues/2494

**Comment by qitta** [comment]
Hi,

thanks for the quick response. I've just thought using openal might not be a good idea as the mpv manpage is telling me this:
~~~
       openal Experimental OpenAL audio output driver

              NOTE:
                 This  driver  is  not  very  useful. Playing multi-channel audio with it is
                 slow.
~~~
Nevertheless I've just tried mpv with openal output and hrtf seems to be working.
Are there any plans hrtf audio filter to be part of mpv again?

Many tanks,
qitta

**Comment by kevmitch** [comment]
af_hrtf was total garbage that introduced obvious artifacts. openal in contrast does a surprisingly good job. I'm thinking the man page should probably be updated to suggest this usage of openal.

**Comment by richardpl** [comment]
I ported vlc sofalizer filter to lavfi, it have high quality mode only which is sloooow. If there is interest I will add fast mode.

**Comment by 2ion** [comment]
@richardpl I've been testing your sofalizer filter recently and it's been an excellent experience. I am not sure if your comment regarding the slowness of the implementation still applies to ffmpeg 3.0.2 which is what I've been using, but I've been running this on my laptop (haswell i5-4210U CPU @ 2.7ghz max) without any noticable additional CPU load – no problems at all (I've been using ClubFritz6.sofa, which is the smallest available HRTFs). I suppose though that when using large HRTFs, the CPU load goes up.

**Comment by richardpl** [comment]
Yes, for very big files it is slower. I don't use it in real time I just encode flac and mpv pick it up as additional audio stream.

**Comment by Kabouik** [comment]
> I ported vlc sofalizer filter to lavfi, it have high quality mode only which is sloooow. If there is interest I will add fast mode.

Almost 4 years later, I don't know if you are still motivated for this @richardpl , but I would be very interested. I am trying to use sofalizer in mpv for real time (so far without success despite ffmpeg built with `--enable-libmysofa`, curious if you have any guidelines written somewhere?) but the computer I want to use will already be using 100% CPU for frame interpolation, so a fast mode for audio would be quite interesting in my case.

**Comment by richardpl** [comment]
No way, buy better machine.

**Comment by Kabouik** [comment]
Not going to happen, I just bought it. :p But this is fine if it cannot work, I just wanted to investigate if it could.

You mentioned that you would consider adding fast mode if there is interest. That was years ago and I just found this Github issue a few days ago so I have no idea if development has continued. Were there enough interest to add fast mode? In case you implemented it, how can a user decide between slow and fast modes?
