### ISSUE TITLE
Downsampling with opengl lanczos scaler gives strange result

### ISSUE THREAD

**Issue by Kagami** [mpv-player/mpv#2508]
```
$ mpv --version
mpv git-a319538 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.5.100
   libavcodec      57.14.100
   libavformat     57.14.100
   libswscale      4.0.100
   libavfilter     6.14.101
   libswresample   2.0.100
ffmpeg version: N-76461-gfd0bf45
```

**Original image**

```
$ wget https://upload.wikimedia.org/wikipedia/commons/a/ad/Air_Force_Academy_Chapel%2C_Colorado_Springs%2C_CO_04090u_original.jpg
$ convert Air_Force_Academy_Chapel,_Colorado_Springs,_CO_04090u_original.jpg -resize 2560x1440 -crop 1920x+0+0 +repage -strip orig.png
```

![orig](https://cloud.githubusercontent.com/assets/533383/11245381/8346d05e-8e23-11e5-80b2-9fb3c61bcc02.png)

**mpv sws scaler**

```
$ mpv orig.png --sws-scaler=lanczos --vf=scale=480:360 --pause
```

![sws](https://cloud.githubusercontent.com/assets/533383/11245378/7be35cec-8e23-11e5-8806-b7366ba37c83.png)

**mpv opengl scaler**

```
$ mpv orig.png --vo=opengl:scale=lanczos --geometry=480x360 --pause
```

![opengl](https://cloud.githubusercontent.com/assets/533383/11245368/72a1b264-8e23-11e5-8970-4685014e3560.png)

**ImageMagick**

```
$ convert orig.png -filter Lanczos -resize 480x360 -strip im.png
```

![im](https://cloud.githubusercontent.com/assets/533383/11245364/6d42c722-8e23-11e5-863b-2282b46816c9.png)

---

As you can see, sws and IM are almost identical, while opengl result contains a lot of artifacts.

**Comment by wm4** [comment]
Add the ``correct-downscaling`` suboption.
