### ISSUE TITLE
Windows builds include debug information?

### ISSUE THREAD

**Issue by zxx1** [mpv-player/mpv#2511]
I just made 2 builds on mingw using https://github.com/mpv-player/mpv-build. 1st build with default settings and for 2nd build I've replaced the last line in scripts/mpv-config to 
./waf configure --disable-debug-build $OPTIONS
And got smaller file size and lower CPU usage for 2nd build. 1st build had the same CPU usage and approximately the same file size as builds from https://mpv.srsfckn.biz/

**Comment by wm4** [comment]
``--disable-debug-build`` only removes ``-g`` from the compiler command. So the size will be reduced, but it should have no influence on CPU usage of the build.

**Comment by zxx1** [comment]
2-10%
You can compare by yourself
https://dropmefiles.com/Iehb6
