### ISSUE TITLE
Support GStreamer 1.6.1

### ISSUE THREAD

**Issue by HLFH** [mpv-player/mpv#2512]
Hi,

I have a DLP 3D Ready videoprojector, named Vivitek Qumi Q7. I can't watch 3D content with mpv because mpv does not support 3D interface. We should be able to manual or automatically select Side-by-Side and Top-and-Bottom 3D video mode as input and render in stereoscopic 3D as output within the mpv settings.

![no3d](https://cloud.githubusercontent.com/assets/2359059/11272476/84738e54-8ecd-11e5-8a43-17d21694fdae.png)

This is the [Daum PotPlayer](https://potplayer.daum.net/). I would prefer to use the open source solution mpv, so it needs 3D interface support.

**Comment by ChrisK2** [comment]
"3D interface" ...? What's that?

Also, did you take a look at [the manual](https://mpv.io/manual/master/#options-video-stereo-mode)?

**Comment by HLFH** [comment]
![duplicated images](https://cloud.githubusercontent.com/assets/2359059/11319328/c5bd43fe-9072-11e5-9743-e1a08d1490c1.PNG)

Yes I checked also the manual and I got two duplicated images instead of a single 3D image.

**Comment by HLFH** [comment]
GStreamer 1.6.1 supports Stereoscopic 3D and MVC. As you can see here: http://gstreamer.freedesktop.org/releases/1.6/

@wm4 Hi. Could you support GStreamer 1.6.1? ffmpeg and libav are really bad in 3D support but not gstreamer since 1.6 release. Could you support it?

**Comment by wm4** [comment]
This is getting ridiculous. Please leave.
