### ISSUE TITLE
HEVC can't be accelarated by dxva2-copy

### ISSUE THREAD

**Issue by cwbsw** [mpv-player/mpv#2516]
OS: Windows 10 64bit TH2 Build 10586
GPU: Nvidia GTX 960
```
mpv git-fee45c0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Tue Nov 10 19:26:26 CET 2015
ffmpeg version: N-76584-g5d9c3bb
[vd] Codec list:
[vd]     lavc:hevc - HEVC (High Efficiency Video Coding)
[vd] Opening video decoder lavc:hevc
[vd] Probing 'dxva2-copy'...
[vd] Trying hardware decoding.
[dxva2] Using SSE4 memcpy
[dxva2] Using VO-supplied device 00000204ae93d8a0.
[vd] Selected video codec: HEVC (High Efficiency Video Coding) [lavc:hevc]
[vd] Pixel formats supported by decoder: yuv420p
[vd] Falling back to software decoding.
[vd] Detected 4 logical cores.
[vd] Requesting 5 threads for decoding.
[vd] Using software decoding.
```

**Comment by lachs0r** [comment]
HEVC should be supported. Please note however that only Main profile is supported by hardware decoders, so check whether your file is compatible.

This sample *should* play with hardware decoding: http://trailers.divx.com/hevc/KAZU_(SUBTITLES)_4K23.98p_HEVC_10Mbits.mkv

**Comment by cwbsw** [comment]
@lachs0r 
I downloaded and tested the file you provided, it also couldn't be accelerated. The error message is similar.
```
[vd] Pixel formats supported by decoder: yuv420p
[vd] Falling back to software decoding.
```

**Comment by shinchiro** [comment]
Probably ffmpeg doesnt support dxva2 for hevc yet . How about try with my build?
ow.ly/TZLSn

the ffmpeg is patched with unofficial dxva2 for hevc. http://ow.ly/UVRVY

**Comment by lachs0r** [comment]
DXVA2 support for HEVC in FFmpeg should be upstream though, since January.

**Comment by lachs0r** [comment]
I also checked my build logs; FFmpeg configure says the DXVA2 hwaccel for HEVC 
is enabled.

**Comment by cwbsw** [comment]
Thanks. @shinchiro 's build works well with hevc main profile.

**Comment by lachs0r** [comment]
Then what the hell is FFmpeg doing?

**Comment by wm4** [comment]
Yes, such a patch for mingw might be required, because mingw can't get their shit together.

It should never crash in any situation, though.

**Comment by shinchiro** [comment]
With integrated intel driver I can play fine the Main10 (HEVC) fine with dxva2-copy. The downside, the video quality slightly worse (I can see blocking in dark area) than using software decoding. I guess dxva2 for Main10 (HEVC) still has long way to go

**Comment by wm4** [comment]
Main10 dxva is not supported by mpv. But it was erroneously decoded as Main, which of course leads to artifacts. Main10 could probably be supported, but since my test hardware does not support it (I think?), I just disabled it for now.

**Comment by zxx1** [comment]
Doesn't work for me on Linux also.
[   0.100][v][vd] Trying hardware decoding.
[   0.121][v][vd] Selected video codec: HEVC (High Efficiency Video Coding) [lavc:hevc]
[   0.121][v][vo/opengl/x11] Disabling screensaver.
[   0.121][v][vo/opengl/x11] Setting DMPS: off.
[   0.122][v][ad] Codec list:
[   0.122][v][ad]     lavc:aac - AAC (Advanced Audio Coding)
[   0.122][v][ad]     lavc:aac_fixed (aac) - AAC (Advanced Audio Coding)
[   0.122][v][ad] Opening audio decoder lavc:aac
[   0.122][v][ad] Requesting 1 threads for decoding.
[   0.143][v][ad] Selected audio codec: AAC (Advanced Audio Coding) [lavc:aac]
[   0.143][v][cplayer] Starting playback...
[   0.145][v][vd] Pixel formats supported by decoder: vdpau yuv420p
[   0.145][v][vd] Pixel formats supported by decoder: yuv420p
[   0.215][v][vd] Falling back to software decoding.
Geforce 660

**Comment by wm4** [comment]
vdpauinfo? Also don't hijack issues. Why the fuck do you think dxva has anything to do with Linux? This issue even has a ms-windows tag. Jesus Christ.

**Comment by zxx1** [comment]
So remove ms-windows tag. Jesus Christ.

**Comment by cwbsw** [comment]
So I can confirm that hevc main profile can be accelarated and main 10 profile can't now, maybe I should try to compile a build with patched ffmpeg myself. Thanks.

**Comment by kevmitch** [comment]
For the record, acf239a45c17e474dd9c266f018f1502e1e13587 introduces HEVC Main10 support.
