### ISSUE TITLE
Segmentation fault on startup

### ISSUE THREAD

**Issue by timeDev** [mpv-player/mpv#2519]
Everything works when using the version on the arch community repo. When compiled locally I get a segmentation fault.
Backtraces: https://gist.github.com/timeDev/c186c0161e8747f23efb https://gist.github.com/timeDev/5bfcc96341521dc5c455

**Comment by wm4** [comment]
ABI mismatch, blame your distro.

**Comment by timeDev** [comment]
Can you give me some pointers on how to fix it?

**Comment by wm4** [comment]
You compiled mpv with conflicting ffmpeg header files and ffmpeg library files. You also could just mpv-build.

**Comment by timeDev** [comment]
Thank you!

2015-11-22 19:45 GMT+01:00 V. Lang <notifications@github.com>:
