### ISSUE TITLE
Is there any way to configure the volume mpv starts a video file with?

### ISSUE THREAD

**Issue by danechitoaie** [mpv-player/mpv#2521]
Right now it always starts at 100% which is pretty loud sometimes.
Is there a way to configure this as a default so that it starts at 50% for example?

**Comment by ChrisK2** [comment]
[``--volume``](https://mpv.io/manual/master/#options-volume)

**Comment by danechitoaie** [comment]
Perfect. Thanks. I was looking at https://github.com/mpv-player/mpv/blob/master/etc/example.conf and didn't noticed anything about volume so I assumed it's not possble to do this form config file but adding "volume=50" to mpv.conf does the trick.

Should I maybe make a PR and add a line there with this example also?

**Comment by wm4** [comment]
The example doesn't mean to demonstrate every single option mpv has.

**Comment by danechitoaie** [comment]
Ok then.

**Comment by kevinlekiller** [comment]
I'd recommend bookmarking https://mpv.io/manual/master/

**Comment by fsevenm** [comment]
You need to go to /home/user/.config/mpv/mpv.conf
if there's no mpv.conf, just make one
then add a line
`volume=50`
the range is from 0 to 100. Choose what suits you.
