### ISSUE TITLE
Request [OS X exclusive shortcuts on Windows]

### ISSUE THREAD

**Issue by kalvinator** [mpv-player/mpv#2524]
Hi,

I would like to have some of the keybord command & control available only in OS X, also become available in the Windows version. 

Thank you.

**Comment by eintw1ck** [comment]
This seems like a really vague request. I assume there wasn't parity in keybinds between macOS and Windows once, is this still the case? Can this be closed?

**Comment by Argon-** [comment]
On OSX, mpv actually has a limited amount of "UI". It's actually only a few entries in a menu bar as this is default for all programs on OSX. I assume these are the controls he's referring to: https://github.com/mpv-player/mpv/pull/4687
These menu bar entries have unique OSX-like shortcuts assigned, for technical reasons: https://github.com/mpv-player/mpv/pull/4687#issuecomment-320435263

**Comment by Dudemanguy** [comment]
Vague and old request. I assume OSX has some special stuff but there's nothing stopping you from binding whatever keybinds in windows.
