### ISSUE TITLE
Question: Avoid AO reinit?

### ISSUE THREAD

**Issue by paulguy** [mpv-player/mpv#2525]
I'm using mpv as a part of a live streaming set up and routing it through JACK, but mpv reinitializes the AO when the file changes, cutting the connection between it and OBS.  I'm wondering if there's an option or a filter I can drop in that will avoid having the AO reinitialized when the file changes.

EDIT: The `port=` option might help with this...

**Comment by wm4** [comment]
The ``--gapless-audio=yes`` option might help with this, but generally mpv assumes it can reinit the audio device any time if it needs to.

**Comment by paulguy** [comment]
Thanks for the reply.
