### ISSUE TITLE
mp3 header missing, mpv exits when I rewind to start of file

### ISSUE THREAD

**Issue by maurinxw** [mpv-player/mpv#2526]
Good morning,
I am encountering a problem when I play a mp3 file with a "missing header".
Play starts correctly, seek forward and backward works, BUT if I reach the beginning of file, mpv exits.
The error it gives to me is about "header missing". If I repeat with a well-formed MP3 file, no errors at all.
If I keep rewinding when it reach the start of the file, mpv simply stands there, waiting for me to release the rew key, then starts playing. But it does not exit.

[mpv_output.txt](https://github.com/mpv-player/mpv/files/43647/mpv_output.txt)

This is the MP3 file used for testing:
https://www.dropbox.com/s/yb70hsl7vj6t5ul/01-S%20Wonderful.mp3?dl=0

**Comment by kevmitch** [comment]
Not seeing any problems here with that test file. Not even the "header missing" message. I'm on mpv and ffmpeg git master. Try upgrading your ffmpeg.

**Comment by maurinxw** [comment]
I have upgraded ffmpeg and it has solved.
Many thanks, I close it.
