### ISSUE TITLE
[Request] Overscan function

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#2528]
I have some analog video captures with typical artifacts around the edges, especially at the bottom. I'd like an "overscan" function that would crop them, the way it would be on a TV set.

I tried the crop filter, but it seems you have to set an absolute value for the size, eg. vf=crop=620:460. My files aren't all 640x480, so that didn't work well. I thought maybe putting in negative values would do it relative to the original size, so I could do eg. vf=crop=-20:-10:5:0 to crop 5 off the left, 15 off the right, 0 off the top, and 10 off the bottom. But that didn't work. Maybe it's a good idea?

I'd also like to control it from the keyboard. I couldn't figure out how to change the crop filter values using input.conf - is it possible?

I also tried the autocrop script and the panscan (e/w keys), but they didn't do what I want.

Thanks...

**Comment by lachs0r** [comment]
Use `--video-zoom`.

**Comment by wm4** [comment]
There are lots of ways this could be done without implementing new features in mpv. Another is using lavfi's crop filter, which allows you to use expressions including the width/height of the image. Yes, you can add/remove entire filters with the vf commands, but for fine tuned changes it'd get clunky quickly.

**Comment by sumyungguy** [comment]
@lachs0r - Thanks, but that doesn't work in full screen. For example, showing a 4:3 video on a 16:9 display, with video-zoom, the top and bottom are cropped, but the sides are not.
