### ISSUE TITLE
mpv does not display embedded album art with opengl-cb until a seek

### ISSUE THREAD

**Issue by cmdrkotori** [mpv-player/mpv#2529]
Discovered yesterday with client app, and reproduced bug with the qt_opengl example. Bug not present with mpv cli ``mpv --no-config --vo=opengl``, which displays as expected.

video of bug: 
https://a.uguu.se/bnvhqj_mpv_qtopengl_framedrop.webm

example file used:
https://a.uguu.se/whvrxb_03.%E5%85%89%E3%81%AE%E3%83%AF%E3%83%AB%E3%83%84.mp3

**Comment by wm4** [comment]
This is actually a bug in the example. ``QMetaObject::invokeMethod((MpvWidget*)ctx, "update");`` doesn't make it redraw for the first (and only) frame, and mpv prints ``[vo/opengl-cb] mpv_opengl_cb_draw() not being called or stuck.`` and drops the frame.

**Comment by cmdrkotori** [comment]
The following patches fixes this issue with the example.
https://gist.github.com/cmdrkotori/e95068bfefc51592f079

**Comment by cmdrkotori** [comment]
Ah you'll have a fix a small issue with that patch, wakeupCounter should be initialized to 20, not 40.

**Comment by wm4** [comment]
That doesn't look like a correct fix at all. 200ms is mpv's timeout to drop the frame - that's probably where it comes from. The wakeup just seems to get lost (due to Qt's weird redraw logic or so.)

**Comment by cmdrkotori** [comment]
Yeah, it's a dirty client-side fix. Perhaps returning a dropped frame when nothing is in the queue would be better. (I'll be the first to admit that I don't know much about mpv internals.)

**Comment by wm4** [comment]
Normally it does that, but not in this special case with opengl-cb. The thing that happens here is just that mpv gives up waiting after 200ms after the application doesn't seem to react at all on a redraw request.

The correct solution is making Qt always strictly react to a redraw request. (Several requests can be batched into one if they somehow come too fast, but what should _never_ happen is that a request is completely ignored.)

**Comment by cmdrkotori** [comment]
>The correct solution is making Qt always strictly react to a redraw request.

That seems to be the problem.

I just modified the example locally so that there's a timer click every 2ms and an update is only called after a flag is set, and it appears that the gui thread is blocking on something.

With 2ms timer events it gets a timer click during setup at 1448716607.326s, followed by two wakeups at 1448716607.333s, and then another timer click at 1448716607.533s whereupon update is successfully called. So, despite being woken up twice, the first paintGL call seems to occur after the vo is reinitialized instead of when it is actually needed. 

This doesn't appear to be mpv's bug to me.

**Comment by wm4** [comment]
It also seems to work fine with the QML examples.

**Comment by cmdrkotori** [comment]
I worked this example into a multi-threaded edition, and now mpv_opengl_cb_draw() is always called no matter what. However video playback appears to be completely broken, I suspect for exactly the same reason.

https://gist.github.com/cmdrkotori/cd92cd5b9322852621e7

The funny thing is I'm pretty sure the example worked about two weeks ago. In any case I don't feel like working more on this bug now.

**Comment by wm4** [comment]
I'm not sure if moving the GL context to another thread is supposed to work with QOpenGLWidget - but most likely not. Note that Qt actually does use a separate OpenGL rendering thread with QtQuick2/QML (except on some known-bad drivers/platforms).

But threads shouldn't be needed to solve this. Even the slowest computers are faster than 200ms just to get a signal across. This is really just a problem with the signaling.

**Comment by cmdrkotori** [comment]
The slider in the example fetches the mpv property "time-start" which causes a hang. Removing this fetch fixes the example.

Patch: https://gist.github.com/cmdrkotori/90ae71288f08a45cb803

**Comment by wm4** [comment]
I see, that's where the locking problem with certain opengl-cb uses actually hurts. In theory, the client API user is allowed to access the normal client API from the same thread as the one which handles opengl-cb redrawing, but this does not really entirely work in some corner cases.

Since the start time has been recently always rebased to 0 (without need for further "compensation"), no functionality is actually lost in this specific case.

**Comment by wm4** [comment]
>-    mpv_opengl_cb_draw(mpv_gl, QOpenGLContext::currentContext()->defaultFramebufferObject(), width(), -height());
>+    mpv_opengl_cb_draw(mpv_gl, defaultFramebufferObject(), width(), -height());

Isn't this the same numerical value, 0?

**Comment by cmdrkotori** [comment]
On my machine defaultFramebufferObject() returns 1, while QOpenGLContext::currentContext()->defaultFramebufferObject() returns 0. Rendering to fbo 0 produces black output, both on my machine (nvidia) and my laptop (amd mesa).

**Comment by wm4** [comment]
Then I guess QOpenGLWidget redirects its output to a FBO (sometimes?), so QOpenGLWidget::defaultFramebufferObject() returns the handle to that FBO. Not really great, because the FBO indirection will make it slightly slower (but not much on reasonable GPUs).

If this fixes an actual bug, it should be put in a separate patch.

**Comment by cmdrkotori** [comment]
>If this fixes an actual bug, it should be put in a separate patch.

Split up: https://gist.github.com/anonymous/a8c630ca09d2a127d836

**Comment by cmdrkotori** [comment]
>this does not really entirely work in some corner cases.

I observed that mp4 and mp3 would drop the first frame, while mkv did not drop the first frame. Hope that helps.

**Comment by wm4** [comment]
Pushed those patches.

>I observed that mp4 and mp3 would drop the first frame, while mkv did not drop the first frame. Hope that helps.

Hm, I wouldn't expect them to behave differently, as long as they're all cover art.
