### ISSUE TITLE
[Feature Request] Add windowed mode for raspberry pi

### ISSUE THREAD

**Issue by aworan** [mpv-player/mpv#2532]
Hi,
I use mpv with my rapsberry pi 2 under ubuntu mate.
I compile it and it works great with hardware acceleration, but it always runs in fullscreen mode.
I try to run it in windowed mode adding a lot of options in command line but it always launch in fullscreen.
Can you add an option to disable fullscreen mode and play video in a window please ?

**Comment by wm4** [comment]
It's not possible right now, and it's also not easy, because the video output API we're using (the only fast one) does not integrate with X11 or Wayland at all.

**Comment by aworan** [comment]
I understand but I think maybe you can do something (not perfect), I explain.
When I use a mpv version not compiled for my rpi (like the default mpv with ubuntu mate for rpi2), it runs in windowed mode but it not have hw acceleration.
I know the video output is X11 and it's slow but it is not bad, so I can watch videos with it (but no hd ones).
It is because it use ffmpeg x264 decoder in that case and not x264_mmal one.
So if we can have two differents mode for rpi it can be great :
* fullscreen fast mode (the actual mode for rpi)
* normal mpv with X11output and x264_mmal video decoder for x264 decoding (and maybe the mmal decoder for mpeg2 too) on x11 video output
If I use ffplay (with mmal support) on my rpi2 to decode some hd video (with x264_mmal ffmpeg decoder) the result is not bad !
What do you think about it ?

**Comment by wm4** [comment]
If ffplay works for you, then mpv with SDL output (and decoder forced to mmal) should not be worse, hopefully.

**Comment by wm4** [comment]
Also, x264 is a specific encoding software, not a format.

**Comment by Gusar321** [comment]
>  normal mpv with X11output and x264_mmal video decoder for x264 decoding (and maybe the mmal decoder for mpeg2 too) on x11 video output.

That's already possible:
mpv --vd=lavc:h264_mmal --vo=x11 somefile.mp4

**Comment by wm4** [comment]
Note that vo_x11 got to be extremely slow on a weak CPU like the RPI.

**Comment by Gusar321** [comment]
> Note that vo_x11 got to be extremely slow on a weak CPU like the RPI.

Yeah, upscaling to fullscreen will give you a slideshow instead of smooth video. But playing in an unscaled or downscaled window works quite well. Setting --sws-scaler=fast-bilinear helps a bit, at the expense of quality of course.

Because the above is not ideal, I looked into getting MMAL to play non-fullscreen. What I got is the ability to set the video size and position with --geometry and/or --autofit and then switch between fullscreen/non-fullscreen during playback. The way I implemented it is probably not the best, but it works: https://gist.github.com/Gusar321/f97f7dc6f3abbb6b55ad

**Comment by aworan** [comment]
I try :
mpv --vd=lavc:h264_mmal --vo=x11 somefile.mp4
It works but I have not hardware acceleration.
When I try :
mpv --vd=help
There is no lavc:h264_mmal in the list, so I think it use lavc:h264 instead so not hardware acceleration.
Maybe I miss some option in waf configure to have the lavc:h264_mmal in mpv ?
I build mpv from the last snapshot of ffmpeg with --enable-mmal option and have ffplay with h264_mmal working.
Any Ideas ?
Thank you :)

**Comment by wm4** [comment]
Then your mpv is probably not linked against that ffmpeg.

**Comment by aworan** [comment]
I replace the ffmpeg system default version with my mmal compiled version. So mpv is link with the good version of ffmpeg (--prefix=/usr --enabled-shared --enable-mmal ...) and do ldconfig after make install.
Any another ideas ?

**Comment by wm4** [comment]
You could just use mpv-build (after editing the scripts to enable mmal).

You can also check with ``ffmpeg -codecs`` whether mmal appears anywhere.

**Comment by aworan** [comment]
I try with mpv-build it is better I get the video decoder lavc:h264_mmal !
Now I have anothers issues, when I try --vo=x11 I have a black window for video and the error :
[vo/x11] X server image format not supported, use another VO.
Any idea of what is wrong ?

I compile to enable sdl too, it works with --vo=sdl but it is very very slow !
I suppose sdl output uses opengl to render, I see in my terminal :
[vo/sdl] Using opengl
But opengl is software rendering on raspberry pi so it's extremely slow.
I need sdl using x11 but I don't found any way to ask SDL to use X11 instead of opengl.
Is there some option to do it ?

**Comment by wm4** [comment]
> [vo/x11] X server image format not supported, use another VO.

What it says. The format the X server wants is not support by vo_x11. MPlayer's actually might support it, though.

> [vo/sdl] Using opengl

You can probably force software rendering mode without OpenGL.

But the only way to get efficient video rendering is over non-X APIs, like MMAL. Not sure if @Gusar321 is interested in upstreaming his patch, which would help slightly.

**Comment by Gusar321** [comment]
> The format the X server wants is not support by vo_x11.

Probably because the reinstated vo_x11 only has 32bit support. The RPi framebuffer is 16bit by default.

> Not sure if @Gusar321 is interested in upstreaming his patch, which would help slightly.

Not sure my patch is upstream quality material, but I've made a pull request. It's the first time I'm doing with git something other than checking out upstream code, so let's see how it goes...


@aworan: Add these two lines to /boot/config.txt and then reboot, --vo=x11 should work then:

framebuffer_depth=32
framebuffer_ignore_alpha=1
