### ISSUE TITLE
[Feature Request] Subtitles in ordered chapters don't show all the time

### ISSUE THREAD

**Issue by Zak-Adelman** [mpv-player/mpv#2533]
When there are 2 or more subtitle tracks (multiple fansub groups, with/without honorifics, original/edited) but only one track in the linked file (OP has just the single karaoke track) the subtitles are not loaded. They are if you have the same number of sub streams. Multiple copies of the same stream gets crazy sometimes.

Wanted to see if, when loading the linked file, it loads the first available when there is only a single track. I have seen this behavior in VLC, possibly others.

**Comment by wm4** [comment]
Not sure why I should bother, because such files are just PLAIN INVALID.

Linked files must all have exactly the same file header. If they do not, expect arbitrary behavior.

I don't know what you expect anyway. Select random subtitle tracks?

Just tell whoever produced this file to fix their crap.
