### ISSUE TITLE
Frame drops with vo options

### ISSUE THREAD

**Issue by mpvuser1** [mpv-player/mpv#2534]
My current config:

vo=opengl-hq:scale=ewa_lanczossharp:cscale=ewa_lanczossoft:tscale=mitchell:prescale-passes=2:prescale-downscaling-threshold=1.2:prescale=superxbr:sigmoid-upscaling:temporal-dither:deband:blend-subtitles:pbo:target-prim=bt.709:target-trc=bt.1886:gamma-auto

Whenever I try to play a video in full-screen, it drops frames when going to fullscreen and then continues periodically during playback. Enabling hardware decoding fixes this, but it does not let me change the brightness/gamma/contrast/anything else with the video. Is there any way to fix this?

**Comment by wm4** [comment]
Well, then use settings that are easier on your GPU?

Hardware decoding can change how video is rendered. For example, with vdpau the data is converted to RGB first, which would skip the chroma upscaling step in OpenGL. So this is probably the reason.
