### ISSUE TITLE
mpv-1.dll crash in Windows 10

### ISSUE THREAD

**Issue by Xuno** [mpv-player/mpv#2536]
After compiling mpv-1.dll, by msys2 in Windows 10 mpv-1.dll was used in examples projects from folder
..\msys64\home\user\mpv\DOCS\client_api_examples
qt
qt_opengl

Project complied with Qt 5.5.1, VS 2013 x64 in Windows 10.

Crash occurs when trying to run qtexample.exe

Attached images are screenshots of crash analyzed by debugger and  dependency walker..

This operation was successfully compiled and run in Windows 7.

Compiled exe in Windows 7 generates the same crash as compiled in Windows 10 when run in Windows 10.

![qtexample_win10](https://cloud.githubusercontent.com/assets/9219334/11446848/289f1d2a-94f2-11e5-89b5-5ea91c24c83c.PNG)

![qtexample_win10-dependecy-profiler](https://cloud.githubusercontent.com/assets/9219334/11446854/2c6ef042-94f2-11e5-93fb-2c4817b8a84e.PNG)

**Comment by wm4** [comment]
Seems to be happening within GnuTLS. I suggest compiling ffmpeg without GnuTLS (and use schannel instead), so mpv itself wouldn't need GnuTLS or OpenSSL at all.

**Comment by Xuno** [comment]
solution found use is  Windows Builds from https://mpv.srsfckn.biz/
Dev builds have `mpv-1.dll` that work.

**Comment by mingwandroid** [comment]
You are attempting to call into mpv-1.dll compiled with MSYS2's MinGW-w64 x86_64 GCC with a Qt 5.5.1 application compiled with VS 2013 x64? Hmm, good luck with that. Why not use Qt 5.5.1 also compiled with MSYS2's MinGW-w64 x86_64 GCC?

`pacman -S mingw-w64-x86_64-mpv mingw-w64-x86_64-qt5` should see you right (and `pacman -S mingw-w64-x86_64-qt-creator` while you're at it)

**Comment by mingwandroid** [comment]
If you move over to using entirely MSYS2 packages and the problem still happens, please open a bug at https://github.com/Alexpux/MINGW-packages/issues (and not at https://sourceforge.net/p/msys2/tickets/220/ :-))
