### ISSUE TITLE
laggy: libdcadec.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by k0377** [mpv-player/mpv#2538]
I tried to get my head about some lags with video I get recently, while watching some [macbreak weekly](http://twit.tv/mbw). The only workaround so far is to double click and go full screen or back, when the lag appears. The sound isn't lagging at all. I can't seem to get the version it is running on:

```
manu:~/ $ mpv --version                                                                                                                     [12:40:56]
mpv: error while loading shared libraries: libdcadec.so.0: cannot open shared object file: No such file or directory
```
```
manu:~/ $ pacman -Ss libdcadec                                                                                                              [12:41:01]
extra/dcadec 0.1.0-1 [installed]
    DTS Coherent Acoustics decoder with support for HD extensions
```

**Comment by ChrisK2** [comment]
This most likely has nothing to do with each other, but to fix the missing lib error, recompile ffmpeg and then mpv.

**Comment by k0377** [comment]
You're right. works again now :ok_woman:
