### ISSUE TITLE
Documentation doesn't reflect change of D --> d key

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#2540]
Many places in the docs still refer to uppercase D for deinterlace.

**Comment by wm4** [comment]
Has already been fixed in git master.

**Comment by sumyungguy** [comment]
Sorry. I was looking at https://mpv.io/manual/master/ which says it's "Git master - HTML-rendering (updated daily)" but it's not in sync with the changes from a week ago...

**Comment by wm4** [comment]
It's not updated automatically; triggered a web rebuild, which should fix it.
