### ISSUE TITLE
path property only return filename.

### ISSUE THREAD

**Issue by mac1202** [mpv-player/mpv#2541]
Hi for scripting purpose I need mpv to return the fullpath and filename of the currently played video so i use the path property. But when I check the terminal output only the filename is returned. Here is the line I use in in my input.conf : 

    k run idok-mpv ${path}
    
And the idok-mpv script I use : 

    #!/bin/sh
    killall idok 2>/dev/null
    echo "$1" #line I add to check the property given by mpv
    idok "$1"

Edit
I did more testing if I launch the video like this : 

    mpv ~/Videos/myvideo.mkv

path return the correct fullpath 
But if I do : 

    cd ~/Videos
    mpv myvideo.mkv
    
it only return the filename.
Could it be possible to make mpv know the fullpath of the video without giving it on the command line.
For example If I start the video from a filemanager.

**Comment by wm4** [comment]
It works as designed. I've adjusted the docs a bit.
