### ISSUE TITLE
gl_video struct member global is sometimes null

### ISSUE THREAD

**Issue by cmdrkotori** [mpv-player/mpv#2542]
This segfaults on line 2856 of video.c

*Introducing* temporal-interpolation to the vo-cmdline during playback will reliably introduce the fault.

![scr218](https://cloud.githubusercontent.com/assets/11322485/11460700/4816354c-973d-11e5-984b-a1baf2f176f7.png)

**Comment by wm4** [comment]
I hope this fixes it.
