### ISSUE TITLE
suboption parser gives error with single quotes

### ISSUE THREAD

**Issue by Askip** [mpv-player/mpv#2544]
For example.

Error parsing option vo (option could not be parsed)
Setting command line option '--vo=opengl:icc-profile='my profile.icc'' failed.

Exiting... (Fatal error)

**Comment by wm4** [comment]
Well, then use double quotes.

**Comment by Askip** [comment]
OK.

Then fix the documentation, maybe?

**Comment by wm4** [comment]
Yes, the documentation is wrong then. See e1d414c9922e79dfc3f00a1def679358e76ded69.

Did I miss any?

**Comment by Askip** [comment]
Thats what I was looking at.
