### ISSUE TITLE
Interpolation should imply a "video-sync=display-*" default

### ISSUE THREAD

**Issue by Cpuroast** [mpv-player/mpv#2548]
When a user enables interpolation, a  "video-sync=display-*" default should be implied instead of silently being disabled

Maybe even make "video-sync=display" correspond to a default and make interpolation imply that option.

**Comment by wm4** [comment]
Not sure if I'm fond of this idea.

**Comment by haasn** [comment]
My take: Instead of silently being disabled, it should be loudly disabled (i.e. with a warning)

The user making an inconsistent/incompatible configuration is clearly an error the user should be aware of.

**Comment by wm4** [comment]
>My take: Instead of silently being disabled, it should be loudly disabled (i.e. with a warning)

This already happens. I don't like this solution overly much either, though.

So I'm open to what most users think is best.

**Comment by Akemi** [comment]
we have a warning now.
