### ISSUE TITLE
Regression: Seeking chapters broken if there is only one chapter

### ISSUE THREAD

**Issue by codicusmaximus** [mpv-player/mpv#2550]
As the title says, seeking chapters in video files no longer works if the video file only contains one chapter no matter where the chapter is.  Not sure what version this broke in.

**Comment by wm4** [comment]
This was done so intentionally, almost a year ago: 862a1b6e7eb3b16aad2d12196bd2410e996a27b1

**Comment by codicusmaximus** [comment]
Worked properly on git-2cfc358 built on 2014-09-22T18:00:59
Does not work on git-fee45c0 built on Tue Nov 10 19:26:26 CET 2015
Also does not work on git-fccce81 built on 2015-06-28T16:57:41

**Comment by codicusmaximus** [comment]
Ah, I see, so this was intentional.  In my opinion, this was a poor change that I would like to see reverted.

For a good use case:

I have many video game play recordings where, while recording, I press a key to insert a chapter to highlight an interesting event that happens.  If the file happens to only have one of those events (there are many that only have one) the file ends up with only one chapter.  Now, there is no way for me to seek to that event directly anymore.  It makes no sense to me to completely ignore seeking to a chapter just because it is the only one.

**Comment by codicusmaximus** [comment]
It looks like something else changed in the behavior of the chapter seeking as well.  Comparing the version I was using before (git-2cfc358 built 2014-09-22) and the version i just tried (git-63a414c built 2014-12-30) that was before the change you linked here are the behaviors:

2cfc358 built 2014-09-22:
if current playback position is before the single chapter and prev chapter is pressed: go to beginning of file
if current playback position is before the single chapter and next chapter is pressed: go to the chapter
if current playback position is after the single chapter and prev chapter is pressed: go to the chapter
if current playback position is after the single chapter and next chapter is pressed: close file (because seeked to end of file)

63a414c built 2014-12-30
if current playback position is before the single chapter and prev chapter is pressed: go to beginning of file
if current playback position is before the single chapter and next chapter is pressed: go to the chapter
if current playback position is after the single chapter and prev chapter is pressed: go to the chapter
if current playback position is after the single chapter and next chapter is pressed: seek to end of file and pause video

The comment on the change you linked reads "If there's only 1 chapter, the seeking by chapter (using the chapter property) will either jump to the chapter point, or quit playback. This is as designed, but seems like a useless and annoying behavior.".  This does not seem consistent with the behavior I'm seeing in either of the above versions.  It seems that the root cause behind this change was people complaining that seeking next chapter when there is only one chapter at the beginning of the file would close the file, but that does not seem to be the case in git-63a414c.  

I propse reverting the change 862a1b6 and afterwards adding a disable/enable option for "don't seek forwards on nextchapter if already past last chapter".  Not sure of a good, concise name for this option but if I think of one I will comment it.

**Comment by codicusmaximus** [comment]
Also, as an aside, I for one like that mpv closes the file if you seek a chapter forward and it's already past the last chapter.  This allows scripts such as autoload (https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) to seek to the next file upon that happening.

**Comment by codicusmaximus** [comment]
Any thoughts?

**Comment by wm4** [comment]
My goal was pretty much to avoid an unnecessary seek (or even stopping playback) if there were "not enough" chapters in the file.

I wouldn't like adding an option to control this behavior either. Fixing the use case of a single person doesn't really warrant doing this, and if there are more users who want this, they wouldn't find the option anyway. (mpv has 500 top-level options, and more sub-option on top of that.)

**Comment by codicusmaximus** [comment]
Are you saying you think it's better to leave it the way it is than to revert the change?

**Comment by wm4** [comment]
I guess so.

**Comment by lamarpavel** [comment]
If a file provides a chapter and mpv ignores the users command to seek to that chapter, is that not a bug? I see why seeking would be ignored if the chapter is at either end of the stream, but a _valid_ chapter should not be discarded.

**Comment by codicusmaximus** [comment]
Right.  I agree with lamarpavel.  The way I see it, now it is completely impossible no matter what you do to seek to a chapter if it's the only one in the file.  This does not seem wrong to you?  Before, the behavior was consistent regardless of the number of chapters.  Now there is a special case where the media player refuses to cooperate for an arbitrary reason and no tweaking of the config will get it to comply.

You stating that a file with only one chapter that isn't at the beginning of the file is "the use case of a single user" seems completely wrong to me.  There is nothing I can find in any MKV spec that requires the first chapter to be at the beginning of the file.  Also, a single user reporting a bug (as far as I'm concerned, it's a bug) doesn't make the bug irrelevant.  It seems to me you're making the decision purely based on how many people complain about it being one way or another instead of choosing a correct, consistent, configurable option -- preferably one that can satisfy both camps.  If users are complaining about the player closing when they hit 'next chapter' if they're past the final chapter, why not just make the player not seek to end of file if they're past the last chapter and they hit next chapter (and provide an option to control whether or not it behaves that way)?  I for one like the player closing in that scenario.  It's been like that for at least 10 years now in mplayer, mplayer2, and mpv.

Finally, your reason for the commit which broke this was in my opinion pretty weak and you yourself admitted that the chapter seeking worked as designed before your change.  In your commit, you stated "This is as designed, but seems like a useless and annoying behavior.".  Well, turns out it wasn't useless behavior.  I think that's reason enough to revert that commit.

**Comment by wm4** [comment]
> This does not seem wrong to you?

No.

> It seems to me you're making the decision purely based on how many people complain about it being one way or another instead of choosing a correct, 

No, I'm making my decision based on what I find annoying and what not.

> Well, turns out it wasn't useless behavior. 

No, but it's annoying. I definitely don't want playback to end playback just because there's somehow a stray chapter.

Add an option to control this? Ridiculous, if we did this every time, mpv would have 10000 options, not "only" 1000.

**Comment by lamarpavel** [comment]
What would be the problem with checking the frame number or time code before seeking to a chapter and ignore the seek only when the chapter is at the very end of the stream?

**Comment by wm4** [comment]
No, the problem is mostly when the playback position is already past the last chapter, and you issue a seek to next chapter command. Then mpv will terminate playback and start the next file (or quit) by design.

**Comment by lamarpavel** [comment]
Oh, my mistake, sorry. Then the fix could be never to seek past the last chapter, eg. forward seeking is ignored if the current position is >= the current time code or frame number?

I really don't want to bother you too much with this, but it seems like a solvable problem where everyone could be happy (:

**Comment by wm4** [comment]
>Then the fix could be never to seek past the last chapter, eg. forward seeking is ignored if the current position is >= the current time code or frame number?

But that's a feature, and normally relatively useful if there are actually chapters in the file.

**Comment by lamarpavel** [comment]
Then a single-chapter file would be a corner case and the above skip could be wrapped in an if clause testing for number of chapters, no?
