### ISSUE TITLE
File skips when playing video with "Invalid video timestamp"

### ISSUE THREAD

**Issue by abagjo** [mpv-player/mpv#2551]
When playing a video with an invalid video timestamp, the video freezes for a fraction of a second. When I play the same file with ffplay, the video plays without skipping.

Example file
http://a.pomf.cat/yffltm.mkv

```
~ $ mpv --no-config a.mkv 
Playing: a.mkv
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 (*) (aac)
 (+) Subs  --sid=1 --slang=eng (*) (subrip)
AO: [pulse] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
[osd/libass] fontconfig: cannot find font 'sans-serif', falling back to 'DejaVu Sans'
AV: 00:00:01 / 00:00:11 (16%) A-V:  0.000
Invalid video timestamp: 1.900000 -> 1.800000
AV: 00:00:02 / 00:00:11 (17%) A-V:  0.020
fontconfig: cannot find font 'sans-serif', falling back to 'DejaVu Sans'
AV: 00:00:03 / 00:00:11 (33%) A-V:  0.000
Invalid video timestamp: 3.820000 -> 3.720000
AV: 00:00:05 / 00:00:11 (49%) A-V:  0.000
Invalid video timestamp: 5.740000 -> 5.640000
AV: 00:00:07 / 00:00:11 (66%) A-V:  0.000 ct:  0.060
Invalid video timestamp: 7.660000 -> 7.560000
AV: 00:00:09 / 00:00:11 (83%) A-V:  0.000 ct:  0.080
Invalid video timestamp: 9.580000 -> 9.480000
AV: 00:00:11 / 00:00:11 (99%) A-V:  0.000 ct:  0.100


Exiting... (End of file)
```

**Comment by wm4** [comment]
Broken file, also the video has "cuts" that are indistinguishable from skipping.

**Comment by perlop** [comment]
Hi. I have the same problem. I feel like vlc handles it better. In mpv the sound is being muted, and it becomes unwatchable, while with vlc I can watch it. Here is a file.
https://u.pomf.io/szxgft.mkv

**Comment by wm4** [comment]
What's the source of these files?

**Comment by abagjo** [comment]
It looks like they were both ripped from BBC iPlayer
http://www.bbc.co.uk/iplayer/episode/b06qnthy/qi-series-m-6-marriage-and-mating
http://www.bbc.co.uk/iplayer/episode/p0342dms/the-hunt-1-the-hardest-challenge

**Comment by wm4** [comment]
The BBC doesn't distribute mkv files, so at least remuxing must have happened.

**Comment by wm4** [comment]
I've made a change to git master, which might handle this situation slightly better.

**Comment by abagjo** [comment]
It's a big improvement. It doesn't seem quite as smooth as mplayer as the video seems to freeze slightly for a very short time (only a few frames) each time an invalid video timestamp is reported, but the skipping is gone and the audio is no longer interrupted.

**Comment by wm4** [comment]
Well, the timestamp sorting mplayer does would break other things, so this is the best it's going to get. Unless there's another method to handle such cases which I missed.

I can only recommend to fix the file or the tool that was used to create it. Or it's shit-in, shit-out.
