### ISSUE TITLE
Starting mpv from a tmux session OSX

### ISSUE THREAD

**Issue by toonn** [mpv-player/mpv#2556]
Recently I screwed up removing dependencies with homebrew that were still necessary apparently.
I reinstalled mpv from the official tap. Had to set a couple of locale variables because the defaults aren't deemed valid by a python 3 module.

Now mpv has different behaviour from what I was used to. Normally when I launch mpv from the command line a window opens and receives focus with a corresponding icon in the doc. Opening mpv multiple times this way opens multiple windows with multiple icons in the dock. This is non-standard behaviour on OS X but I actually prefer this for mpv.
This used to work from tmux session in exactly the same way. Now when I launch mpv from inside a tmux session, a window opens but the terminal retains focus. After changing focus, input is still somehow going to the terminal and ESC behaves like META so ESC then q shows up as alt+q in the mpv output, pressing ESC twice still works, btw I mapped ESC to quit because I'm used to the mplayer behaviour.
Another annoyance is that when I go fullscreen, if mpv was launched from tmux, the menu bar at the top remains visible.

I believe this change must have happened recently, at least within the last month because I semi-regularly update everything through homebrew. However I had to tap the mpv repo so I'm not sure where my last version came from, my best guess would be brew cask.

I'm running OS 10.10.5 Yosemite, this is the mpv --version output:
    mpv 0.13.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
     built on Wed Dec  2 00:21:38 CET 2015
    ffmpeg library versions:
       libavutil       54.31.100
       libavcodec      56.60.100
       libavformat     56.40.101
       libswscale      3.1.101
       libavfilter     5.40.101
       libswresample   1.2.101
    ffmpeg version: 2.8.3

**Comment by wm4** [comment]
Are you sure this behavior changed with mpv? If so, what was the last working mpv version?

**Comment by toonn** [comment]
My tmux version is 2.1 from October 18th so I think the culprit is mpv, yes.
As I said I'm not entirely sure what the last version was, 0.11.0 maybe?
Do you have a way I can easily test previous versions? I can download previous app bundles but they don't include the binary that is called from the terminal which I think is the culprit.

**Comment by toonn** [comment]
I've since rebooted and I no longer have this altered behaviour. I have no idea what caused it, so I guess this issue can be closed.

**Comment by wm4** [comment]
I'll chalk it up on OSX being terrible.
