### ISSUE TITLE
Hardware decoding issues on intel hardware with latest mpv

### ISSUE THREAD

**Issue by mgcrea** [mpv-player/mpv#2557]
We've recently lost the ability to properly decode our videos with vaapi hardware support:

```
[cplayer] mpv git-9fc74d5 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Nov 29 18:02:48 UTC 2015
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.9.100
[cplayer]    libavcodec      57.16.100
[cplayer]    libavformat     57.19.100
[cplayer]    libswscale      4.0.100
[cplayer]    libavfilter     6.17.100
[cplayer]    libswresample   2.0.101
[cplayer] ffmpeg version: N-76885-gaa42753
```

```
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     lavc:h264_vdpau (h264) - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (VDPAU acceleration)
[vd] Opening video decoder lavc:h264
[vd] Probing 'vaapi'...
[vd] Requested hardware decoder not compiled.
[vd] Using software decoding.
[vd] Detected 4 logical cores.
[vd] Requesting 5 threads for decoding.
[vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
[vo/opengl/x11] Disabling screensaver.
[cplayer] Starting playback...
[vd] Using software decoding.
```

It looks like it's failing on:

```
[vd] Requested hardware decoder not compiled.
```

However hardware acceleration seems properly setup:

```
# vainfo
error: XDG_RUNTIME_DIR not set in the environment.
libva info: VA-API version 0.37.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_37
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.37 (libva 1.5.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Broadwell - 1.5.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
```

Hardware acceleration still working fine with VLC on the same media.

Using `mpv-tests` PPA on Ubuntu 14.04.3LTS (3.19).

**Comment by wm4** [comment]
mpv requires a libva newer than what Ubuntu 14.04 has by default.

**Comment by wm4** [comment]
>libva info: VA-API version 0.37.0

Actually that's wrong. mpv only requires 0.36.0. But apparently mpv didn't get compiled with it anyway.

**Comment by mgcrea** [comment]
mpv+vaapi has been working fine for months on Ubuntu 14.04, on quite a lot of different NuC machines (previously used `ppa_mc3man_trusty_media_trusty`).

**Comment by mgcrea** [comment]
Ok. Just reverted to our previous PPA (that just got the 0.13 landed), and it's now working again. Maybe you should not advise to use the `mpv-tests` PPA if it does not support hardware acceleration.

**Comment by mc4man** [comment]
Works fine here, ie.,
$ mpv 
mpv git-9fc74d5 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 29 17:24:08 UTC 2015
ffmpeg library versions:
   libavutil       55.9.100
   libavcodec      57.16.100
   libavformat     57.19.100
   libswscale      4.0.100
   libavfilter     6.17.100
   libswresample   2.0.101
ffmpeg version: N-76885-gaa42753

$ mpv    /home/doug/Videos/amostviolentyear-clip1_h1080p.mov 
Playing: /home/doug/Videos/amostviolentyear-clip1_h1080p.mov
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [opengl-hq] 1920x816 vaapi
AV: 00:00:18 / 00:01:00 (30%) A-V:  0.000

**Comment by mc4man** [comment]
I see the issue now - 14.04 only provides VA-API version 0.35.0 so waf refused vaapi on ppa build. (libva 1.3.0  source)
Will have to provide a newer libav/intel-vaapi-driver packages to that ppa.
1.4.x would suffice though 1.6,x would maybe be better. 
Didn't want previously  to force users of that ppa to higher package versions than the next Ubuntu Release upgrades had,  but  now basically a moot point so will likely go with 1.6.x
