### ISSUE TITLE
"disable_event all" causes mpv to wait on the JSON IPC socket to be closed

### ISSUE THREAD

**Issue by redneb** [mpv-player/mpv#2558]
I am running `mpv` with `--input-unix-socket`. I noticed that when I exit `mpv` (for example by pressing `q`) then the client connected to the socket receives an EOF. On the other hand, if I disable all events by sending the `disable_event all` command, then if I press `q` to exit `mpv`, `mpv` does not exit and instead, it waits for the client to close the connection. The same thing happens when I pass a socket (created by `socketpair`) to `mpv` via the `--input-file=fd://N` option.

**Comment by redneb** [comment]
Here's how to reproduce.
**Normal behavior:**
Start  `mpv` with `mpv --input-unix-socket=/tmp/mpv-socket /some/file.mkv`. Then connect to `mpv` using `socat`: `socat readline /tmp/mpv-socket`. Then hit `q` to quit `mpv`. You will see `socat` exit too (`mpv` closes the connection).

**Unexpected behavior:**
Start  `mpv` with `mpv --input-unix-socket=/tmp/mpv-socket /some/file.mkv` (same as before). Then connect to `mpv` using `socat`: `socat readline /tmp/mpv-socket` (same as before). Now enter the following command to `socat`:   ` {"command":["disable_event","all"]}`. Then go back to `mpv` and hit `q`. `mpv` will refuse to quit. But if you type `Ctrl+D` in the `socat` terminal then `mpv` will exit.

**Comment by wm4** [comment]
Do you have a way to reproduce this without socat?

**Comment by wm4** [comment]
The cause for the deadlock was actually simpler than I thought, and I didn't bother to reproduce and test the problem (for which I'm too lazy right now).
