### ISSUE TITLE
RPI2 configure failed

### ISSUE THREAD

**Issue by soredake** [mpv-player/mpv#2559]
Checking for CACA                                                         : disabled 
Checking for DRM                                                          : yes 
Checking for JPEG support                                                 : disabled 
Checking for Direct3D support                                             : win32 not found 
Checking for Raspberry Pi support                                         : no 
You manually enabled the feature 'rpi', but the autodetection check failed.
 * ERROR: media-video/mpv-0.11.0::gentoo failed (configure phase):
 *   configure failed

**Comment by kevmitch** [comment]
build/config

**Comment by kevmitch** [comment]
sorry . . 

```build/config.log``` should have more info on what is missing.

**Comment by fenque** [comment]
http://sprunge.us/fFhX

**Comment by wm4** [comment]
That's not what we asked for. We want mpv's config.log.

Anyway, it's likely this fails because Gentoo doesn't keep the RPI firmware libs in /opt.

**Comment by fenque** [comment]
Sorry, config.log is here http://sprunge.us/aJNB

**Comment by wm4** [comment]
OK, apparently the reason is that the GL headers do not provide everything needed.

**Comment by wm4** [comment]
Ignore this. The config log is really hard to read. No idea what's going on.

**Comment by kevmitch** [comment]
Well superficially, the problem is that ```/usr/include/interface/vmcs_host/vcgencmd.h``` from the rpi headers is trying to include the file ```vchost_config.h```, but it can't find it. Is ```vchost_config.h``` anywhere on your system?

```
err: In file included from /usr/include/bcm_host.h:54:0,
                 from ../test.c:1:
/usr/include/interface/vmcs_host/vcgencmd.h:33:27: fatal error: vchost_config.h: No such file or directory
 #include "vchost_config.h"
```

**Comment by fenque** [comment]
![1449165695](https://cloud.githubusercontent.com/assets/5204968/11569111/b7b384c8-99f8-11e5-858a-3170e25517b7.png)

**Comment by kevmitch** [comment]
ok, well then I'm with wm4 - no idea. 

Shouldn't ```#include "vchost_config.h"``` look in the same directory as the file it appears in?

**Comment by aplocher** [comment]
Hello, was wondering if you guys have found a way to build mpv with support RPI2?  I'm having a similar issue, I've tried using the mpv-build repo and the standard mpv (manually built FFmpeg, etc).  Here's the config.log from my mpv-build attempt: http://pastebin.com/jKkjStn4

My vchost_config.h file is located in /opt/vc/include/interface/vmcs_host/linux/vchost_config.h

I can get it to build, but it doesn't detect RPI support and if I do "mpv --vo=help" it only lists image and null

Thanks

**Comment by wm4** [comment]
I think it's because your system doesn't have the required opengl headers.

**Comment by aplocher** [comment]
@wm4 thank you for your quick response.

I'm not sure what I could be missing.  I'm running the latest version of Raspbian (Jessie) Lite.  I was hoping to get mpv working similar to how I have mplayer working - through a framebuffer module through the console without the need for xwin (only I'm having serious probs with mplayer with certain types of network streams, hence the reason I'm looking into mpv).

I've gotten a little trigger happy trying to install packages from apt-get in an attempt to figure out what's missing.  Would you mind taking a look at these and see if you notice anything glaringly obvious that I'm missing?

List of installed apt-get packages (dpkg -l): http://pastebin.com/cPdqTiPx

Recursive dir list of /opt/vc (ls -lR /opt/vc): http://pastebin.com/Wga8bXLn

Thank you!

**Comment by wm4** [comment]
I see this failing:

> err: ../test.c:1:19: fatal error: GL/gl.h: No such file or directory

You need `/usr/include/GL/`. I think it should be in mesa-common-dev, but somehow your package list says it's installed?

**Comment by aplocher** [comment]
@wm4 Thanks again.

It turns out I needed to add the package libgles2-mesa-dev.  As soon as I did that, I got vo=rpi support working!  

I'm now setting up a fresh Raspbian Jessie Lite instance on a new SD Card (since I added tons of packages in an attempt to build this).  I'm going to document the minimum dependencies needed to build this on a fresh Rasp Lite instance.

**Comment by Coacher** [comment]
@soredake, this is possibly a downstream issue. At least on Gentoo. Please track https://bugs.gentoo.org/show_bug.cgi?id=578492.

**Comment by Coacher** [comment]
@soredake, a fix was added to mpv-9999 in Gentoo a couple of hours ago.
Please test and report back.

**Comment by soredake** [comment]
@Coacher still failing https://up1.ca/#6-D07-4UxE87sX2Srz7ONA

**Comment by Coacher** [comment]
@soredake, thanks.
Now the error is different from the one you've had initially.
New error: ```/bin/ld: cannot find -lGLESv2```.

Please re-emerge media-libs/mesa with gles2 USE enabled. This should help.

**Comment by soredake** [comment]
@Coacher now it successfully compiles, thanks.

**Comment by Coacher** [comment]
@soredake, good.
The needed changes will be available in the next release.
Until then I suggest you to stick to the live (9999) version.

**Comment by Coacher** [comment]
@soredake, I think this issue can be closed now.
