### ISSUE TITLE
Strange text output

### ISSUE THREAD

**Issue by askl56** [mpv-player/mpv#2564]
When playing an mkv file, i get this bizarre text clumping:

https://www.dropbox.com/s/hio4ion8ngc47oh/Screenshot%202015-12-05%2013.51.47.png?dl=0

**Comment by wm4** [comment]
Does this only happen with mkv files?

**Comment by askl56** [comment]
Nope, just tried with an MP4 file and got the same result.

**Comment by lachs0r** [comment]
OS? Looks like miscompiled libass and/or misconfigured fontconfig.

**Comment by askl56** [comment]
Mac os X, Macbook pro. I just installed it via Homebrew

**Comment by metril** [comment]
I had the same text/font issues. Try uninstall mpv. Uninstall libass, libass-git, and libass-ct. Do a cleanup with homebrew. Then reinstall mpv. Your issue should be fixed.

**Comment by wm4** [comment]
Yes, seems most likely a libass ABI mismatch issue, or outdated libass. I've seen this before with homebrew users.

**Comment by askl56** [comment]
Thanks, reinstalling worked.
