### ISSUE TITLE
mpv memory leak

### ISSUE THREAD

**Issue by pitrou** [mpv-player/mpv#2569]
mpv keeps growing memory when playing certain videos created by `youtube-dl`. I've uploaded a sample here: http://pitrou.net/mpv_leak.mkv . Here it leaks several kB per second of playing, as indicated by `vsz` and `rss` (and the process ends ups being killed by the OOM killer if playing for long enough).

```
$ mpv --version
mpv 0.8.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-02-19T17:03:21
libav library versions:
   libavutil       54.3.0
   libavcodec      56.1.0
   libavformat     56.1.0
   libswscale      3.0.0
   libavfilter     5.0.0
   libavresample   2.1.0
```

**Comment by wm4** [comment]
Stop using a mpv version that is 1 year old and contains known and fixed bugs (partially in Libav actually).
