### ISSUE TITLE
Codec and container compatibility chart on mpv.io website and github homepage

### ISSUE THREAD

**Issue by porg** [mpv-player/mpv#2571]
At first I want to thank you for offering that great media player!

For general information purposes I'd welcome a table or list of supported codec/container/subtitle formats. Both your website www.mpv.io and your github homepage (README.md) offer only very vague information on this without further details, which leaves the average user with uncertainty.

---
1) a) https://github.com/mpv-player/mpv/
"It supports a wide variety of video file formats, audio and video codecs, and subtitle types."
b) https://github.com/mpv-player/mpv/wiki/ and FAQ
Nothing related.
2) a) https://mpv.io/
Nothing related.
b) https://mpv.io/manual/master/ 
"It supports a wide variety of video file formats, audio and video codecs, and subtitle types"
For the generic keywords "container", "codec" or "format" or specific keywords such as "h264" or "HEVC" you find some command line arguments, but never a dedicate section of supported formats.
3) Also googling for "mpv" in conjunction with "compatibility" and similar synonyms yields no useful results.

---

Therefore I came to the conclusion that knowledge on mpv and format compatibility is known merely informally or by expert users. Maybe it is identical to it's origin project MPlayer or mplayer2. But from what I have read there seems to be no source code back-porting/syncing, so that would also be speculative.

I'd very much welcome if you'd specify the format compatibility in your documentation or link to an external resource, should that exist. Thank you very much.

**Comment by ChrisK2** [comment]
mpv (like pretty much any other "free" video player) uses ffmpeg (or libav) to decode pretty much everything, so here you go: http://ffmpeg.org/general.html#Supported-File-Formats_002c-Codecs-or-Features

Since the exact features depend on the configuration the ffmpeg lib that was used to compile mpv, we can't really make a list of supported codecs and containers for mpv.

**Comment by kevmitch** [comment]
```
mpv --demuxer=help --vd=help --ad=help --oac=help --ovc=help --of=help
```

Note that the lavf demuxer comprises most of the other container formats like mp4, avi, etc. I'm not sure of a way to get a list of those from within mpv, but you can use the ffmpeg you used to build mpv to tell you

```
ffmpeg -formats
```

**Comment by wm4** [comment]
>Note that the lavf demuxer comprises most of the other container formats like mp4, avi, etc. I'm not sure of a way to get a list of those from within mpv

This is not terribly well handled, and requires a dummy file:
```
mpv /dev/null --demuxer-lavf-format=help --demuxer=lavf
```

**Comment by porg** [comment]
@ChrisK2 : Stating that mpv supports more/less what ffmpeg or libav support and giving an appropriate link would help more than having no info at all and relying on guesswork or research what libraries mpv facilitates. Would be appreciated rather than havin nothing!
