### ISSUE TITLE
Cannot seek lavf/mpegts stream even with caching enabled

### ISSUE THREAD

**Issue by tmm1** [mpv-player/mpv#2576]
I'm trying to seek around a cached mpegts stream coming over http or rtsp, but mpv claims the stream is not seekable even with the cache enabled:

```
Playing: http://10.0.1.4:5004/auto/v745
[ffmpeg] Opening http://10.0.1.4:5004/auto/v745
[ffmpeg] Could not set AVOption tls_verify='0'
[ffmpeg] Mime-type: 'video/mpeg'
[ffmpeg] Stream opened successfully.
[cache] Cache size set to 150000 KiB (75000 KiB backbuffer)
[lavf] Found 'mpegts' at score=100 size=2048.
[demux] Detected file format: mpegts (libavformat)
[demux] Stream is not seekable.
```

If I try to seek, I get an error:

```
AV: 00:00:08 A-V:  0.000 Dropped: 3 Cache: 10s+1MB
[cplayer] Run command: seek, flags=9, args=[-5.000000, relative, unused]
Can't seek in this file.
```

I also tried with `--force-seekable=yes`, which also fails but then restarts playback from the beginning of the cache:

```
AV: 00:00:34 A-V:  0.000 Cache: 10s+1MB
[cplayer] Run command: seek, flags=9, args=[-5.000000, relative, unused]
[lavf] queuing seek to 29.426644
[lavf] execute seek (to 39163.460233 flags 9)
[ffmpeg] SWR: discarding 1000 audio samples
AV: 00:00:29 A-V:  0.000 Cache:  0s+1MB
[lavf] Seek failed (Operation not permitted)
[lavf] seek done
AV: 00:00:02 A-V:  0.000 Cache:  4s+26MB
[cplayer] first video frame after restart shown
[cplayer] playback restart complete
```

Is this the intended behavior?

**Comment by wm4** [comment]
The http connection is probably really not seekable (server supports no range requests), and/or the demuxer is really accessing data outside of the cached range?

**Comment by tmm1** [comment]
The http stream is definitely not seekable.

But I'm trying to seek within the cache. In the example above I tried to
seek back from 34s to 29s and it still failed.

**Comment by wm4** [comment]
Are you using ``--force-seekable``? If not, mpv should actually be rejecting the seek command.

It could be that the demuxer tries to seek out of range anyway.

**Comment by tmm1** [comment]
Yes, I posted examples with and without force-seekable.

Without force mode, the seek fails with "Can't seek in this file" from `mp_seek` because the demuxer is not marked as seekable. 

With force mode enabled, the seek attempts but fails with "Seek failed (Operation not permitted)" in `demux_seek_lavf`.

I know the requested seek position is not out of the cache range, because mpv ends up restarting playback from the beginning of the cache which is much earlier than my requested seek point.

It sounds like this is not the intended behavior, so I'll try to log in trace mode and see if I can narrow down what's going on.

**Comment by olifre** [comment]
Is it reproducible with `--hr-seek=yes` ? If not, this might help in the debugging.

**Comment by tmm1** [comment]
Hey, it totally works as expected with `--hr-seek=yes`!

**Comment by wm4** [comment]
It was due to keyframe seeking then. hr-seek is not the default, because decoding speed is typically too bad to make hr-seeks fast. (Though there are some ways to hr-seek by default. Clicking on the seek bar in the OSC does a hr-seek, and so do key bindings like e.g. ``Shift+Left``.)

**Comment by tmm1** [comment]
Why would keyframe seeking be failing? I'm interested in making this work without `hr-seek` and would appreciate any pointers to help work up a patch.

**Comment by wm4** [comment]
Normally, seeking back without hr-seek will of course snap to the first keyframe before the seek target - but it shouldn't print something about a failing seek. (Sorry, I guess I got confused due to your first example without ``--force-seekable``.) I can't reproduce such a case either.

It's possible that libavformat actually tried to read before the cached region or so, which made the seek fail, and then somehow ended up returning the data from the start of the cached region. (What happens on seek failures is completely undefined in libavformat, so I don't expect nice things to happen.)

Can you maybe provide a test case for this? It's easy to make a file only linearly readable, e.g. ``cat file.ts | mpv -``.
