### ISSUE TITLE
mpv/DOCS/man/options.rst lacks "VIDEO FILTERS" link target

### ISSUE THREAD

**Issue by rofl0r** [mpv-player/mpv#2581]
the doc says
```
Specify a list of video filters to apply to the video stream. See `VIDEO FILTERS`_ for details and descriptions of ...
```
however the hyperlink target is apparently not existing

**Comment by wm4** [comment]
Works here: https://mpv.io/manual/master/#options-vf

The way these links work might be a bit confusing, and also github doesn't support cross-file references in its RST renderer.

(And I didn't change anything to make it show up. I just overlooked this report until now.)
