### ISSUE TITLE
User-created lua keybindings are cleared with no-input-default-bindings option

### ISSUE THREAD

**Issue by AntonTell** [mpv-player/mpv#2584]
All user-created `mp.add_key_binding()` seem to be removed when mpv is started with the `no-input-default-bindings` option.

##### Steps to reproduce:

1. Create a .lua file in `~/.config/mpv/scripts/` with this content:  
>    function something_handler()
        print("the key was pressed")
    end
    mp.add_key_binding("x", "something", something_handler)

2. Run `mpv --no-input-default-bindings file.mkv`

3. Press `x`.

###### Expected result:

The terminal should output:  
>[script_name] the key was pressed 

###### Actual result:

The terminal outputs:  
>[input] No key binding found for key 'x'.

##### mpv -v output:

>[cplayer] Command line options: '-v'  
>[cplayer] mpv git-e3de309 (C) 2000-2015 mpv/MPlayer/mplayer2 projects  
>[cplayer]  built on Sun Oct 18 19:13:34 CEST 2015  
>[cplayer] ffmpeg library versions:  
>[cplayer]    libavutil       54.31.100  
>[cplayer]    libavcodec      56.60.100  
>[cplayer]    libavformat     56.40.101  
>[cplayer]    libswscale      3.1.101  
>[cplayer]    libavfilter     5.40.101  
>[cplayer]    libswresample   1.2.101  
>[cplayer] ffmpeg version: 2.8.3  
>[cplayer]   
>[cplayer] Configuration: ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-zsh-comp --enable-libmpv-shared  
>[cplayer] List of enabled features: alsa asm atomics audio-input av-pix-fmt-mmal av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples build-date c11-tls caca cplayer debug-build dlopen drm dvbin dvdnav dvdread egl-x11 enca encoding fchmod gl gl-wayland gl-x11 glibc-thread-name glob iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libm libmpv-shared librt libsmbclient libswresample libv4l2 linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads pulse pvr resampler shm sse4-intrinsics stdatomic subprocess termios tv tv-v4l2 vaapi vaapi-egl vaapi-glx vaapi-hwaccel vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h wayland x11 xext xinerama xrandr xss xv zlib zsh-comp  
>[global] config path: '' -> '/home/anton/.config/mpv'  
>[global] config path: 'mpv.conf' -> '/home/anton/.config/mpv/mpv.conf'  
>[global] config path: 'config' -/-> '/home/anton/.config/mpv/config'  
>[global] config path: 'mpv.conf' -/-> '/home/anton/.mpv/mpv.conf'  
>[global] config path: 'config' -/-> '/home/anton/.mpv/config'  
>[global] config path: 'mpv.conf' -/-> '/etc/mpv/mpv.conf'  
>[global] config path: 'config' -/-> '/etc/mpv/config'  
>[cplayer] Reading config file /home/anton/.config/mpv/mpv.conf  
>[cplayer] Setting option 'vo' = 'opengl-hq:scale=ewa_lanczossharp:cscale=ewa_lanczossoft:scale-antiring=0.8:cscale-antiring=0.9' (flags = 4)  
>[cplayer] Setting option 'video-sync' = 'display-resample' (flags = 4)  
>[cplayer] Setting option 'hwdec' = 'no' (flags = 4)  
>[cplayer] Setting option 'audio-channels' = '2' (flags = 4)  
>[cplayer] Setting option 'softvol' = 'yes' (flags = 4)  
>[cplayer] Setting option 'softvol-max' = '200' (flags = 4)  
>[cplayer] Setting option 'no-input-default-bindings' = '' (flags = 4)  
>[cplayer] Setting option 'keepaspect-window' = '' (flags = 4)  
>[cplayer] Setting option 'keep-open' = '' (flags = 4)  
>[cplayer] Setting option 'save-position-on-quit' = '' (flags = 4)  
>[cplayer] Setting option 'ytdl' = 'yes' (flags = 4)  
>[cplayer] Setting option 'osc' = 'no' (flags = 4)  
>[cplayer] Setting option 'slang' = 'eng,en' (flags = 4)  
>[cplayer] Setting option 'alang' = 'jpn,jp,eng,en' (flags = 4)  
>[cplayer] Setting option 'v' = '' (flags = 8)  
>[cplayer] mpv git-e3de309 (C) 2000-2015 mpv/MPlayer/mplayer2 projects  
>[cplayer]  built on Sun Oct 18 19:13:34 CEST 2015  
>[cplayer] ffmpeg library versions:  
>[cplayer]    libavutil       54.31.100  
>[cplayer]    libavcodec      56.60.100  
>[cplayer]    libavformat     56.40.101  
>[cplayer]    libswscale      3.1.101  
>[cplayer]    libavfilter     5.40.101  
>[cplayer]    libswresample   1.2.101  
>[cplayer] ffmpeg version: 2.8.3

**Comment by wm4** [comment]
That's because key bindings added this way are considered default bindings (so the user can override them without editing the script). There's also ``mp.add_forced_key_binding``, which won't mark them as default bindings.
