### ISSUE TITLE
MPV GUI Font Spacing Non-Existant

### ISSUE THREAD

**Issue by metril** [mpv-player/mpv#2585]
This is a follow-up to a previous ticket that another user had submitted and I had provided a solution for. See #2564

My solution of removing all of libass, libass-ct, libass-git, and reinstalling mpv no longer works. I am able to periodically get the GUI text to effectively overlay on itself. So, the time counter, speed counter, etc. are unreadable. This is on OX 10.11.2. MPV is installed via homebrew using the tap method and not the cask.

**Comment by franzf** [comment]
Seconding. Also happens to me. I've tried several things since, including compiling libass manually, not using homebrew, and even then the spacing gets messed up once in a while. This doesn't happen with the stable builds in Github releases at all. I think it's something to do with the build script, though admittedly I can't figure out what's going on in it.

**Comment by metril** [comment]
I want to add that this issue is very random. I can open a file multiple times in a row and see the gui messed up. I can open the file again and the gui is fine. Open the file again and the gui is messed up.

**Comment by human-bean** [comment]
Have you tried --osd-font='Helvetica Neue'?

**Comment by metril** [comment]
I just added the font to my mpv.conf file. That's the only thing in there. Right now, it looks like it's working. I'll keep testing it, but why would specifying the font possibly fix this issue?

**Comment by franzf** [comment]
Doesn't help for me. A consistent way of triggering the bug is, right after opening a file, immediately start fast forwarding. The OSD will be messed up if you press `o`.

Another thing I've noticed: The spacing is tighter on non-retina screens. I've no idea if this means anything but, the more info the better, right?

![screen shot 2015-12-13 at 16 03 50](https://cloud.githubusercontent.com/assets/869168/11769367/8a94a75c-a1b3-11e5-9c3d-8ccad55c7ee2.png)

<img width="386" alt="screen shot 2015-12-13 at 16 04 22" src="https://cloud.githubusercontent.com/assets/869168/11769371/9c1c9ab6-a1b3-11e5-9d81-29784b54da17.png">

**Comment by utterbull** [comment]
Thirding.

I also experience this problem frequently. It doesn't seem to be caused by anything in the video file itself.

**Comment by metril** [comment]
Further testing shows that stuff like the "Speed" text is messed up. Also, sometimes OSD text appears fine initially, but further appearances are messed up.

**Comment by wm4** [comment]
This could also be caused by freetype or harfbuzz ABI mismatches. Recompile and reinstall the respective packages, then libass and mpv.

**Comment by franzf** [comment]
Looks like Homebrew/homebrew#46992 is maybe related? I don't think it's a version mismatch. I've deleted my whole Homebrew /Cellar and recompiled everything, but something still isn't linking to some library properly. I have the relevant .pc files in /usr/local/lib/pkgconfig and they seem correct, fwiw.

**Comment by Nyx0uf** [comment]
I have this problem too, I recompiled everything to be sure but it changes nothing.

latest mpv, OS X 10.11.1/10.11.2

**Comment by AirPort** [comment]
I think this is an issue only with the default font picked up by mpv.
I never noticed it because I've always specified a font in my config, but I run a couple of test and I was able to reproduce this only when the `osd-font=` option was unsetted.

**Comment by human-bean** [comment]
Fast forwarding right after opening a file and then pressing `o` seems to reliably mess up the font, however it was not possible for me to reproduce the bug by opening the file, pressing `o`, fast forwarding and pressing `o` again.

The used font seems to affect the outcome as well, using Arial instead of Helvetica (Neue) works well so far.

**Comment by franzf** [comment]
I got `osd-font` to fix it for me when using `o`. (I was specifying the font name wrong). Maybe something in libass isn't reading the sans-serif fallback Helvetica.dfont metrics right?

**Comment by human-bean** [comment]
Rebuilding libass `--without-harfbuzz` could be one possible workaround, as a result this issue is not present even with previously messed up fonts.

**Comment by wm4** [comment]
So, can anyone confirm whether or not harfbuzz is the cause for this?

**Comment by franzf** [comment]
Looks like rebuilding libass without harfbuzz fixed it here too.

**Comment by peterhellberg** [comment]
I had this problem with mpv installed via homebrew, and it was indeed solved by running
`brew reinstall libass --without-harfbuzz` and then `brew reinstall mpv --with-bundle`

```
OS X El Capitan (10.11.2)
mpv/0.14.0 + libass/0.13.1
```

**Comment by pigoz** [comment]
I confirm. It happens only when libass is compiled against harfbuzz.

**Comment by metril** [comment]
Confirm that libass without harfbuzz fixes the issue.

**Comment by chyiz** [comment]
I can also confirm that reinstalling libass without harfbuzz and then reinstall mpv fixed the issue.
But like @AirPort mentioned before, this only happens when `osd-font` is unset. Actually setting it to any value would also fix this issue.

**Comment by wm4** [comment]
I still can't reproduce. Does it need a specific harfbuzz version to trigger? Which are you using? (``pkg-config --modversion harfbuzz`` - 0.9.40 here.)

**Comment by AirPort** [comment]
Here I have the latest version of harbuzz (1.1.2) and the issue steadly shows up like described in here.

**Comment by wm4** [comment]
Updated harfbuzz to 1.1.2, still no problem.

**Comment by wm4** [comment]
Now I could reproduce. I'm not sure about the circumstances, maybe I just failed to hit the specific interactions that can trigger this bug.

Here's how I can reproduce it 100% reliably:
1. start with --no-config
2. do a single seek (should show the OSD bar, but not the OSD)
3. do something to make the OSD show up

If the OSD or both OSD and bar are shown for the first time, it doesn't happen.

I'm not sure what causes this.

**Comment by wm4** [comment]
Isolated: https://github.com/libass/libass/issues/212

**Comment by danechitoaie** [comment]
Having same issue. Adding osd-font='Helvetica Neue' in mpv.conf fixed it for me.

**Comment by patrickchoi** [comment]
Solution provided by danechitoaie worked for me, added osd-font='Helvetica Neue' and the OSD is readable again.

**Comment by AirPort** [comment]
Following the libass' issue, I can confirm that with latest harfbuzz's release (1.2.1) I can't reproduce this anymore.

**Comment by wm4** [comment]
>Following the libass' issue, I can confirm that with latest harfbuzz's release (1.2.1) I can't reproduce this anymore.

Indeed, this contains the fix.
