### ISSUE TITLE
E: incorrect-fsf-address (rpmlint)

### ISSUE THREAD

**Issue by region51** [mpv-player/mpv#2586]
```
E: incorrect-fsf-address /usr/src/debug/mpv-0.14.0/stream/dvb_tune.c
```
According to http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt, the current address is:
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address

**Comment by wm4** [comment]
I really don't give a shit. If it pains you, make a PR replacing all occurrences of outdated license headers with newer ones (which use a web address, no physical addresses).
