### ISSUE TITLE
Terminal options in config file override command line while being read

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#2588]
If `--msg-level=all=v` is set on the command line, I expect to see verbose terminal output.
But if `msg-level=all=warn` is found in the config file, it gets executed and overrides the command line. Subsequent verbose messages about config file options are never printed. Verbose output returns after the config file is finished being parsed.

If `--terminal=no` is set on the command line, I expect not to see any terminal output.
But if `terminal=yes` is found in the config file, error messages about bad config file options following it are printed anyway. No further messages are seen after the config file is read.

On OS X, `terminal=no` is set in the built-in config file.
If `--terminal=yes` is set on the command line, I expect to see error messages about bad options in the user config file, as well as status messages.
But config file error messages are never printed. Normal status messages are printed after reading the config file is complete.

Mpv shouldn't alter terminal or verbosity settings while reading config file options, if they've been set on the command line.

**Comment by wm4** [comment]
That's just how it works. The config options are set first, and the command line options are set afterwards. The behavior you see is merely because a recent commit made changes to the terminal options take effect immediately.

I don't see a big problem with the new behavior.

**Comment by wm4** [comment]
> I don't see a big problem with the new behavior.

Not so sure about that. It was essentially reverted.
