### ISSUE TITLE
Command key binding for systems other than OS X

### ISSUE THREAD

**Issue by suntong** [mpv-player/mpv#2589]
The man page of my `mpv` says, 

    (The following keys are valid only on OS X.)

which includes, `command + 1` (Resize video window to its original size) and `command + 2` (Resize video window to double its original size). 

I tried every key combination under my Ubuntu, and believe they are indeed **only on OS X**. These keys are what I badly needed. I have to install `vlc` just to be able to play movies double sized. 

Such a pity (and shame). Really hope that those all `command + x` key bindings will also be available for other systems than OS X. Thanks.

**Comment by lachs0r** [comment]
Update to 0.14.0.

Also, you can customize this through `input.conf` even if you don’t have this version (the command you’re looking for is `set window-scale 2.0`).
