### ISSUE TITLE
Mpv as library has still GPL

### ISSUE THREAD

**Issue by Enerccio** [mpv-player/mpv#2591]
which means that any program using it is forced to use GPL too, which makes no sense...

**Comment by rr-** [comment]
AFAIK it's dual licensed as both GPL and LGPL, and it is done so exactly for this reason.

**Comment by pigoz** [comment]
It's still gpl. It wasn't relicensed... yet.

**Comment by wm4** [comment]
Yes, it's still GPL. But you could argue that the intent of mplayer and its slave mode was that it can be used from non-GPL hosts. But if you don't want to take the risk of a legally questionable interpretation of mplayer developer intents, it's GPL.

LGPL relicensing is something that might happen. See #2033.
