### ISSUE TITLE
Multimedia keys keycodes?

### ISSUE THREAD

**Issue by amallric** [mpv-player/mpv#2593]
Hello everyone,

I am using mpv in a fully text-based environment on Arch and everything mostly works very well, except for some issues with input. The mouse is not recognised at all, and several keys on the keyboard (mostly multimedia keys but also other keys like + on the keypad and so on) either aren't detected at all or are misinterpreted by mpv.

I read earlier issues on input and I get from it that mpv works with the keyboard at a fairly high level (i.e. not scancodes, but actual ASCII data. This is fine with me, however this cannot apply to multimedia keys which do not have an associated ASCII value. I looked a bit at the source code but as I don't have much programming skills I wasn't able to understand how mpv interacts with these multimedia keys.

Input.conf has a seemingly arbitrary list of "key names" (for lack of a better word), but how exactly does mpv recognize actuel keyboard input and bind it to these keys? Does it rely on specific keycodes, or something else?

If I knew the keycodes associated by mpv to these "key names" from input.conf, then I could remap scancodes on my own side to the needed keycodes and make the setup work. With a bit of luck I could probably even make the mouse work. Both multimedia keys and the mouse are perfectly recognized and working within my system, it's just mpv that doesn't detect them.

Thanks a lot for any help.

**Comment by kevmitch** [comment]
try running

    mpv --input-test --idle

I doubt you'll get the mouse to work in a text based environment. Maybe check out, gpm though I wouldn't get my hopes up.

**Comment by amallric** [comment]
I did run mpv --input-test --idle, of course. This is how I got the information about keys on my keyboard that are either wrongly recognized or not recognized at all by mpv.

My question pertains to how does mpv identify the said multimedia keys in the first place. It can't be the ASCII value since they don't have one, so is it the scancode? The keycode? If yes, which keycode corresponds to every particular key designation from input.conf.

I don't get hopes up for the mouse either. gpm doesn't work with mpv, which is unsurprising, but the mouse itself is recognised by the system, so my plan was to try and assign mouse input scancodes to relevant keycodes to make it work with mpv directly. But to do that I need the keycodes used by mpv.

**Comment by kevmitch** [comment]
From a cursory look it appears to be happening in ```osdep/termina-unix.c```. Note in particular ```getch2()``` in which it reads characters from stdin and compares them with entries in the global ```static const struct key_entry keys``` list. Basically, it looks like you need to somehow get your keys to generate something on stdin.

**Comment by wm4** [comment]
Yes, if I interpret your question right, it's all up to ``terminal-unix.c``. It maps console input through stdin to mpv internal key codes (which are ASCII/unicode for printable chars, and special values like e.g. ``MP_KEY_HOME`` for keys which don't map to text). ``getch2`` contains the statemachine to map terminal sequences to mpv keys.

**Comment by wm4** [comment]
PS: and we expressively don't use ncurses or termcap, because these are too much of a pain.

**Comment by amallric** [comment]
Thank you. This is quite helpful. I think I understand the system. Basically stdin is accessed with read(), then memcmp() matches the input with the sequences in the keys[] array, and if there is a match, the sequence is replaced with the mpv internal key code.

A few remarks, if you don't mind.
1) I don't quite understand the syntax of those "sequences" in the keys[] array - "\033[1~" and so on. Does it have a particular meaning (if you, could you please hint me to an explanation?)

2) The keys[] array in terminal-unix.c does not have mappings for all of the "special" keys. For instance, there are none for the multimedia keys, like MP_KEY_VOLUME_UP, MP_KEY_PLAY and so on. Those are defined in keycodes.h but I don't really see where they are used in terminal-unix.c. Does that mean that all the "special" (i.e. non-ASCII) keys are disabled in terminal mode by design?

Thanks.

**Comment by wm4** [comment]
> 1) I don't quite understand the syntax of those "sequences" in the keys[] array - "\033[1~" and so on. Does it have a particular meaning (if you, could you please hint me to an explanation?)

They are VT100 escape codes.

> 2) The keys[] array in terminal-unix.c does not have mappings for all of the "special" keys. For instance, there are none for the multimedia keys, like MP_KEY_VOLUME_UP, MP_KEY_PLAY and so on. Those are defined in keycodes.h but I don't really see where they are used in terminal-unix.c. Does that mean that all the "special" (i.e. non-ASCII) keys are disabled in terminal mode by design?

Yes. And there will not be any standard mappings for them either. Each terminal emulator or native kernel virtual terminal might do something different here.

**Comment by amallric** [comment]
Ok, I get it. I guess it makes sense that you can't have multimedia keys support, then. Well, I'll see if I can tinker a local solution by redirecting /dev/input/event into stdin and such. At least I understand now how the whole thing works - this has been bothering me since ages. Thanks a lot.

**Comment by wm4** [comment]
``/dev/input`` support might be worthwhile, but of course it's completely different from the terminal, and should be implemented separately.

**Comment by lachs0r** [comment]
Using a text-based environment and then demanding GUI features…
(Linux PTYs are horrible enough already.)
