### ISSUE TITLE
Options for maximum performance on slow machine?

### ISSUE THREAD

**Issue by octos** [mpv-player/mpv#2594]
On a 1.3 GHz Intel Core i5 with OS X El Capitan 10.11.1, mpv drops lots frames while playing 4K video. QuickTime player, on the other hand, plays them effortlessly and uses only 10-15% CPU, so it is possible. What options are there to make mpv more efficient on less powerful machines? Image quality is not a priority.

**Comment by Cpuroast** [comment]
> On a 1.3 GHz Intel Core i5 with OS X El Capitan 10.11.1, mpv drops lots frames while playing 4K video. QuickTime player, on the other hand, plays them effortlessly and uses only 10-15% CPU, so it is possible. What options are there to make mpv more efficient on less powerful machines? Image quality is not a priority.

You probably just need to use the following:

hwdec=videotoolbox

**Comment by darkbrow** [comment]
Change vo not to use deband.
'vo=opengl' or 'vo=opengl-hq:deband=no'
To solve sluggish full screen playback, add 'fs-black-out-screens' to mpv.conf.

**Comment by kevmitch** [comment]
If you are light on resources, ```vo=opengl-hq``` is probably not a good idea. Just ```vo=opengl``` 
is probably the best bet as it will enable the fewest high performance features.

See also #1778. ```vd-lavc-fast``` is probably a bad idea.

**Comment by wm4** [comment]
This was answered. Also note that El Capitan has a known performance bug in fullscreen mode.

**Comment by xanview** [comment]
Adding hwdec=videotoolbox makes an enormous difference on a Macbook Pro 13" - it goes from being unwatchable to being silky smooth. Shouldn't this be the default on Mac?
