### ISSUE TITLE
Ignore certain filetypes?

### ISSUE THREAD

**Issue by for-coursera** [mpv-player/mpv#2595]
When launched in a directory (like `mpv .`), is it possible to add a command line option to ignore certain filetypes from this directory? Something like `--ignore=jpg,gif,bmp` probably?

**Comment by Argon-** [comment]
What's the difference to explicitly use e.g. your shell's globbing/wildcard features?

**Comment by for-coursera** [comment]
Oh, thanks, TIL about `extglob`.

**Comment by azzamsa** [comment]
For anyone landing here for "excluding certain/specific files":

To exclude some file, use `$ mpv !(*.jpg|*.png)`. Remember you need to activate your `extglob` beforehand, run `shopt -s extglob`.

Credit: cloph_away @ #mpv irc.

**Comment by aeseok** [comment]
Is there any work around for windows users? I'm new to the program and don't really understand the "extglob" or "$ mpv" commands

**Comment by CogentRedTester** [comment]
If you want an alternative CLI command for windows then `mpv (Get-ChildItem -Path ./* -Exclude *.jpg,*.png).fullname` in powershell seems to work.

**Comment by 07416** [comment]
Is it possible to permanently exclude certain file extensions in the config file? 

For instance, I have currently absolutely no use for .cue since mpv initially plays an album seemingly by parsing the filenames, then *repeats* by playing the CUE.

**Comment by guidocella** [comment]
> Is it possible to permanently exclude certain file extensions in the config file?
> 
> For instance, I have currently absolutely no use for .cue since mpv initially plays an album seemingly by parsing the filenames, then _repeats_ by playing the CUE.

You can exclude them with a script:
```lua
mp.observe_property('playlist-count', 'number', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        if playlist[i].filename:match('%.cue$') then
            mp.commandv('playlist-remove', i-1)
        end
    end
end)
```

**Comment by avih** [comment]
> You can exclude them with a script ...

Are you sure this works for more than one .cue file? I think once one item is removed, all the following ones get a lower number (and the overall count becomes smaller too), but I don't think your script takes that into account - neither in the number of the playlist item it will try to remove next, nor in the overall count.

**Comment by 07416** [comment]
> > Is it possible to permanently exclude certain file extensions in the config file?
> > For instance, I have currently absolutely no use for .cue since mpv initially plays an album seemingly by parsing the filenames, then _repeats_ by playing the CUE.
> 
> You can exclude them with a script:
> 
> ```lua
> mp.observe_property('playlist-count', 'number', function ()
>     local playlist = mp.get_property_native('playlist')
>     for i = #playlist, 1, -1 do
>         if playlist[i].filename:match('%.cue$') then
>             mp.commandv('playlist-remove', i-1)
>         end
>     end
> end)
> ```

Saved as a `.lua` script in the mpv scripts directory, to anyone who doesn't know. Worked correctly after testing with one album.

After thinking further, I should disable at least image and various text files as well. Would anyone be kindly enough to show how to add several formats to the line (I don't know what separator character(s) to use:

    if playlist[i].filename:match('%.cue$') then

**Comment by guidocella** [comment]
```lua
mp.observe_property('playlist-count', 'number', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        for _, extension in pairs({'cue', 'txt', 'jpg'}) do
            if playlist[i].filename:match('%.' .. extension .. '$') then
                mp.commandv('playlist-remove', i-1)
            end
        end
    end
end)
```

**Comment by 07416** [comment]
Great, I added more formats:

```
mp.observe_property('playlist-count', 'number', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        for _, extension in pairs({'cue', 'txt', 'jpg', 'jpeg', 'gif', 'png', 'log'}) do
            if playlist[i].filename:match('%.' .. extension .. '$') then
                mp.commandv('playlist-remove', i-1)
            end
        end
    end
end)

```

**Comment by 07416** [comment]
[read [from here onwards](https://github.com/mpv-player/mpv/issues/2595#issuecomment-807379930)]

I've started using the M3U format for creating playlists — I wouldn't want to remove `.m3u` and `.m3u8` from the ignore script since all of the albums/folders I've stored which contain any M3U file will play at least twice. Is there a way to keep reading specific `.m3u8` files (the filename for the said files always is `playlist.m3u8`, if relevant)?

**Comment by guidocella** [comment]
```lua
local blacklist = {'cue', 'txt', 'jpg', 'jpeg', 'gif', 'png', 'log', 'm3u8'}

local temp = {}
for _, ext in pairs(blacklist) do
    temp[ext] = true
end
blacklist = temp

-- Observing playlist instead of playlist-count would call this 3 times
-- unnecessarily on each playlist-entry change, though it would be more correct
-- since it would exclude blacklisted files in single-file directory/playlists,
-- which don't change playlist-count, and files added by calling loadfile with
-- a blacklisted file.
mp.observe_property('playlist-count', 'native', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        if blacklist[playlist[i].filename:match('%.(%w+)$')]
           and playlist[i].filename ~= 'playlist.m3u8'
           and playlist[i].filename:match('/playlist.m3u8$') == nil then
            mp.commandv('playlist-remove', i-1)
        end
    end
end)
```

I'm also sharing this faster version by avih which doesn't call `match` for each playlist entry and each extension.

**Comment by 07416** [comment]
> ```lua
> local blacklist = {'cue', 'txt', 'jpg', 'jpeg', 'gif', 'png', 'log', 'm3u8'}
> 
> local temp = {}
> for _, ext in pairs(blacklist) do
>     temp[ext] = true
> end
> blacklist = temp
> 
> -- Observing playlist instead of playlist-count would call this 3 times
> -- unnecessarily on each playlist-entry change, though it would be more correct
> -- since it would exclude blacklisted files in single-file directory/playlists,
> -- which don't change playlist-count, and files added by calling loadfile with
> -- a blacklisted file.
> mp.observe_property('playlist-count', 'native', function ()
>     local playlist = mp.get_property_native('playlist')
>     for i = #playlist, 1, -1 do
>         if blacklist[playlist[i].filename:match('%.(%w+)$')]
>            and playlist[i].filename:match('playlist.m3u8$') == nil then
>             mp.commandv('playlist-remove', i-1)
>         end
>     end
> end)
> ```
> 
> I'm also sharing this faster version by avih which doesn't call `match` for each playlist entry and each extension.

Worth noting that the matching is case-sensitive — mislabeling the file extension in uppercase seems widespread.

**Comment by guidocella** [comment]
This is case-insensitive:

```lua
local blacklist = {'txt', 'jpg'}

local temp = {}
for _, ext in pairs(blacklist) do
    temp[ext] = true
end
blacklist = temp

mp.observe_property('playlist-count', 'native', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        if blacklist[playlist[i].filename:lower():match('%.(%w+)$')] then
            mp.commandv('playlist-remove', i-1)
        end
    end
end)
```

**Comment by 07416** [comment]
@guidocella https://github.com/mpv-player/mpv/issues/12631#issuecomment-1762706885

I attempted editing, the script now doesn't appear to exclude files. My test folder only includes the following files, mpv starts playback from the `.m3u8` file:

```
beatles.m3u8
Public_domain_music_-_Wikipedia_1-Public_domain_music-1.mkv
Public_domain_music_-_Wikipedia_2-Public_domain_music-2.mkv
```

the ignore script:

```

local blacklist = {'cue', 'txt', 'pdf', 'log', 'sfv', 'md5', 'nfo', 'm3u', 'm3u8', 'accurip', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'jxl', 'bmp', 'dib', 'part', 'url', 'html', 'htm', 'vtx', 'ffp'}
-- archive formats `'rar', 'zip', '7z',`

local temp = {}
for _, ext in pairs(blacklist) do
    temp[ext] = true
end
blacklist = temp

mp.observe_property('playlist-count', 'native', function (_, count)
    if count == 1 then
        return
    end
end)
```

**Comment by guidocella** [comment]
You removed all the code that excludes files, of course it doesn't exclude them. You need to return if playlist-count is 1 and execute the same code as before otherwise to play single excluded files.

**Comment by 07416** [comment]
Sorry for the oversight above.

This script works after limited testing:

```lua
local blacklist = {'cue', 'txt', 'pdf', 'log', 'sfv', 'md5', 'nfo', 'm3u', 'm3u8', 'accurip', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'jxl', 'bmp', 'dib', 'part', 'url', 'html', 'htm', 'vtx', 'ffp'}

local temp = {}
for _, ext in pairs(blacklist) do
    temp[ext] = true
end
blacklist = temp

mp.observe_property('playlist-count', 'native', function ()
    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        if blacklist[playlist[i].filename:lower():match('%.(%w+)$')] then
            mp.commandv('playlist-remove', i-1)
        end
    end
end)

mp.observe_property('playlist-count', 'native', function (_, count)
    if count == 1 then
        return
    end
end)
```

Please consider creating a repository for the script.

**Comment by guidocella** [comment]
```lua
local blacklist = {'txt', 'jpg'}

local temp = {}
for _, ext in pairs(blacklist) do
    temp[ext] = true
end
blacklist = temp

mp.observe_property('playlist-count', 'native', function (_, count)
    if count == 1 then
        return
    end

    local playlist = mp.get_property_native('playlist')
    for i = #playlist, 1, -1 do
        if blacklist[playlist[i].filename:lower():match('%.(%w+)$')] then
            mp.commandv('playlist-remove', i-1)
        end
    end
end)
```

This is in a repository if you prefer it: https://github.com/occivink/mpv-scripts#blacklist-extensionslua

**Comment by guidocella** [comment]
I use neither but I don't see what blacklisting extensions has to do with the UI.

**Comment by Lc4B** [comment]
> @guidocella, sorry for disturbing, I thought [blacklist-extensions.lua](https://github.com/occivink/mpv-scripts#blacklist-extensionslua) was not working. However it worked perfectly fine once I drag'n'dropped a folder with blacklisted files into mpv. At first I thought [blacklist-extensions.lua](https://github.com/occivink/mpv-scripts#blacklist-extensionslua) will work even if I start the playback of a single file and skip to the next one. Unfortunately it isn't working this way.



> Hey @ach-raf, thanks for your input. This looked promising but for some reason it doesn't work in Windows: it just clears entire the playlist and resets **mpv** to default open state once you skip to excluded filetype. I have tried it by opening `MP4` file using `Open with mpv` right-click option in File Explorer and skipping through files inside a folder with the following files:
> 
> ```
> 1.mp4
> 2.mp4
> 3.jpg
> 4.mp4
> 5.mp4
> ```
I think I understand that you are using uosc with its autoload function, so if with this function you want to avoid the jpg file jumping between the videos in the folder you could remove the images via the **uosc conf file**, deleting the extensions:
```
# Types to identify media files
image_types=
```
