### ISSUE TITLE
force-window=immediate hides mpv from the DE's status bar

### ISSUE THREAD

**Issue by Shudouken** [mpv-player/mpv#2597]
I'm not sure if this only happens in cinnamon or if other DEs have this problem as well. Here's a screenshot of what I mean.
https://0x0.st/-7l.jpg

When opening a video with `force-window=immediate` mpv will not be present in the status bar of the DE, but everything else works as it should. I can confirm that this worked without problems some weeks ago. I tried it with urls (where forcing the window makes sense) but also with local files and in both cases the status bar stays empty.

**Comment by wm4** [comment]
Can't reproduce. As far as I'm aware, the window title is actually updated. I tried running cinnamon, but it's a dumb POS that just shows "failed to load session cinnamon", and then can't exit or switch virtual terminal (I had to use sysrq+r to get out), so I'm just blaming cinnamon.

You can maybe use xprop on the window when it's not showing the title to check if the title property is set properly.
