### ISSUE TITLE
media-title for playlist items

### ISSUE THREAD

**Issue by phaer** [mpv-player/mpv#2598]
I can get the title of the current media file by using the `media-title` uri, but `playlist` seems to include file names only. I suppose that makes sense because, for example, calls to youtube-dl don't happen before a file is played so mpv does not know the title beforehand.

My feature request would be a way to get titles of all playlist items before they are played or a way to add custom data to playlists using lua.

**Comment by wm4** [comment]
>My feature request would be a way to get titles of all playlist items before they are played 

Very unlikely.

>or a way to add custom data to playlists using lua. 

Might be possible.

**Comment by lachs0r** [comment]
The latter works with `file-local-options/force-media-title` (and `ytdl_hook.lua` makes use of it).
