### ISSUE TITLE
Can´t use youtube-dl

### ISSUE THREAD

**Issue by asoksevil** [mpv-player/mpv#2601]
I am trying to use mpv for playing YouTube or Twitch videos but it just doesn´t work:

I get the following error for every single video:

[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] tls: IO Error: -9806
Failed to recognize file format.

Youtube-dl is updated, I installed it using home-brew.

I am running Mavericks 10.9.5 if it helps.

**Comment by ChrisK2** [comment]
Does youtube by itself work?

If yes, post log with ``mpv -v ...``

**Comment by wm4** [comment]
Probably some kind of certificate verification error. Most likely nothing mpv has control over.

**Comment by asoksevil** [comment]
Yes, youtube-dl works (I just tried to download a video from youtube)

log:

[cplayer] Command line options: '-v' '...'
[cplayer] mpv 0.12.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Wed Dec 16 08:29:21 GMT 2015
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.31.100
[cplayer]    libavcodec      56.60.100
[cplayer]    libavformat     56.40.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.40.101
[cplayer]    libswresample   1.2.101
[cplayer] ffmpeg version: 2.8.1
[cplayer] 
[cplayer] Configuration: waf configure --prefix=/usr/local/Cellar/mpv/0.12.0 --enable-zsh-comp
[cplayer] List of enabled features: apple-remote asm atomic-builtins atomics av-pix-fmt-mmal av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples bsd-fstatfs build-date c11-tls cocoa coreaudio cplayer debug-build dlopen encoding fchmod gl gl-cocoa glob iconv jpeg lcms2 libass libass-osd libav libavdevice libavfilter libdl libm libswresample lua nanosleep optimize osx-thread-name posix posix-or-mingw posix-spawn pthreads resampler shm subprocess termios tv videotoolbox-gl videotoolbox-hwaccel zlib zsh-comp
[global] config path: '' -> '/Users/Rui/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/Users/Rui/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/Rui/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/Users/Rui/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/Rui/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/bin/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/bin/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/config'
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -/-> '/Users/Rui/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/Users/Rui/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/bin/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/input.conf'
[input] Falling back on default (hardcoded) input config
[osc] Loading script @osc.lua...
[global] config path: 'scripts' -/-> '/Users/Rui/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/Users/Rui/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/bin/scripts'
[global] config path: 'scripts' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/scripts'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] config path: 'lua-settings/osc.conf' -/-> '/Users/Rui/.config/mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/Users/Rui/.mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/usr/local/bin/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/lua-settings/osc.conf'
[osc] lua-settings/osc.conf not found. 
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[cplayer] mouse_leave script-binding osc/__keybinding2
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[cplayer] mouse_btn2 script-binding osc/__keybinding5
[cplayer] mouse_btn0_dbl ignore
[cplayer] shift+mouse_btn0_dbl ignore
[cplayer] mouse_btn2_dbl ignore
[cplayer] del script-binding osc/__keybinding6
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[input, ]
[cplayer] Run command: disable-section, flags=0, args=[input]
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading script @ytdl_hook.lua...
[global] config path: 'scripts' -/-> '/Users/Rui/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/Users/Rui/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/bin/scripts'
[global] config path: 'scripts' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/scripts'
[ytdl_hook] loading mp.defaults
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] config path: 'scripts' -/-> '/Users/Rui/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/Users/Rui/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/bin/scripts'
[global] config path: 'scripts' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/scripts'
[global] config path: 'watch_later' -> '/Users/Rui/.config/mpv/watch_later'
[cplayer] Playing: ...
[cplayer] Running hook: ytdl_hook/on_load
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[file] Opening ...
[file] Cannot open file '...': No such file or directory
[stream] Failed to open ....
[cplayer] finished playback, loading failed (reason 4)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Errors when loading file)
[ytdl_hook] Exiting...
[osc] Exiting...

**Comment by ChrisK2** [comment]
- Your mpv version is outdated (0.14.0 is recent)
- you were supposed to replace the `...` with some URL that doesn't work.

**Comment by asoksevil** [comment]
Thanks @ChrisK2 

Apologies for the mistake I am quite new to this.

[cplayer] Command line options: '-v' 'https://www.youtube.com/watch?v=iNJdPyoqt8U'
[cplayer] mpv 0.12.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Wed Dec 16 08:29:21 GMT 2015
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.31.100
[cplayer]    libavcodec      56.60.100
[cplayer]    libavformat     56.40.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.40.101
[cplayer]    libswresample   1.2.101
[cplayer] ffmpeg version: 2.8.1
[cplayer] 
[cplayer] Configuration: waf configure --prefix=/usr/local/Cellar/mpv/0.12.0 --enable-zsh-comp
[cplayer] List of enabled features: apple-remote asm atomic-builtins atomics av-pix-fmt-mmal av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples bsd-fstatfs build-date c11-tls cocoa coreaudio cplayer debug-build dlopen encoding fchmod gl gl-cocoa glob iconv jpeg lcms2 libass libass-osd libav libavdevice libavfilter libdl libm libswresample lua nanosleep optimize osx-thread-name posix posix-or-mingw posix-spawn pthreads resampler shm subprocess termios tv videotoolbox-gl videotoolbox-hwaccel zlib zsh-comp
[global] config path: '' -> '/Users/Rui/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/Users/Rui/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/Rui/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/Users/Rui/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/Rui/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/bin/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/bin/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/config'
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -/-> '/Users/Rui/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/Users/Rui/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/bin/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/input.conf'
[input] Falling back on default (hardcoded) input config
[osc] Loading script @osc.lua...
[global] config path: 'scripts' -/-> '/Users/Rui/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/Users/Rui/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/bin/scripts'
[global] config path: 'scripts' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/scripts'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] config path: 'lua-settings/osc.conf' -/-> '/Users/Rui/.config/mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/Users/Rui/.mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/usr/local/bin/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/lua-settings/osc.conf'
[osc] lua-settings/osc.conf not found. 
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[cplayer] mouse_leave script-binding osc/__keybinding2
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[cplayer] mouse_btn2 script-binding osc/__keybinding5
[cplayer] mouse_btn0_dbl ignore
[cplayer] shift+mouse_btn0_dbl ignore
[cplayer] mouse_btn2_dbl ignore
[cplayer] del script-binding osc/__keybinding6
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[input, ]
[cplayer] Run command: disable-section, flags=0, args=[input]
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading script @ytdl_hook.lua...
[global] config path: 'scripts' -/-> '/Users/Rui/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/Users/Rui/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/bin/scripts'
[global] config path: 'scripts' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/scripts'
[ytdl_hook] loading mp.defaults
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] config path: 'scripts' -/-> '/Users/Rui/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/Users/Rui/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/bin/scripts'
[global] config path: 'scripts' -/-> '/usr/local/Cellar/mpv/0.12.0/etc/mpv/scripts'
[global] config path: 'watch_later' -> '/Users/Rui/.config/mpv/watch_later'
[cplayer] Playing: https://www.youtube.com/watch?v=iNJdPyoqt8U
[cplayer] Running hook: ytdl_hook/on_load
[global] config path: 'youtube-dl' -> '/Users/Rui/.config/mpv/youtube-dl'
[ytdl_hook] found youtube-dl at: /Users/Rui/.config/mpv/youtube-dl 
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[ffmpeg] Opening https://www.youtube.com/watch?v=iNJdPyoqt8U
[ffmpeg] Mime-type: 'text/html; charset=utf-8'
[ffmpeg] Stream opened successfully.
[cache] Cache size set to 150000 KiB (75000 KiB backbuffer)
[demux] Trying demuxer: disc (force-level: normal)
[demux] Trying demuxer: edl (force-level: normal)
[demux] Trying demuxer: cue (force-level: normal)
[demux] Trying demuxer: rawaudio (force-level: normal)
[demux] Trying demuxer: rawvideo (force-level: normal)
[demux] Trying demuxer: tv (force-level: normal)
[demux] Trying demuxer: libass (force-level: normal)
[demux] Trying demuxer: mkv (force-level: normal)
[demux] Trying demuxer: rar (force-level: normal)
[demux] Trying demuxer: lavf (force-level: normal)
[ffmpeg] tls: IO Error: -9806
[lavf] No format found, try lowering probescore or forcing the format.
[demux] Trying demuxer: mf (force-level: normal)
[demux] Trying demuxer: playlist (force-level: normal)
[demux] Trying demuxer: subreader (force-level: normal)
[demux] Trying demuxer: disc (force-level: unsafe)
[demux] Trying demuxer: edl (force-level: unsafe)
[demux] Trying demuxer: cue (force-level: unsafe)
[demux] Trying demuxer: rawaudio (force-level: unsafe)
[demux] Trying demuxer: rawvideo (force-level: unsafe)
[demux] Trying demuxer: tv (force-level: unsafe)
[demux] Trying demuxer: libass (force-level: unsafe)
[demux] Trying demuxer: mkv (force-level: unsafe)
[demux] Trying demuxer: rar (force-level: unsafe)
[demux] Trying demuxer: lavf (force-level: unsafe)
[lavf] No format found, try lowering probescore or forcing the format.
[demux] Trying demuxer: mf (force-level: unsafe)
[demux] Trying demuxer: playlist (force-level: unsafe)
[demux] Trying demuxer: subreader (force-level: unsafe)
[cache] Terminating cache...
[cache] Cache exiting...
[cplayer] finished playback, unrecognized file format (reason 4)
[cplayer] Failed to recognize file format.
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Errors when loading file)
[ytdl_hook] Exiting...
[osc] Exiting...

How can I update it? I am using mpv home-brew (brew update) but it won´t update.

**Comment by ChrisK2** [comment]
> How can I update it? I am using mpv home-brew (brew update) but it won´t update.

see https://github.com/mpv-player/homebrew-mpv

And from the log it seems like your youtube-dl really is not working. Did you make the copy in your mpv folder executable as well?

**Comment by asoksevil** [comment]
No, I don´t think so. How can I make it executable?

I just updated it to 0.14 but it isn´t working.

**Comment by asoksevil** [comment]
No, I don´t think I have. How can I?

I just update fit to 0.14 but it isn´t working.

**Comment by wm4** [comment]
So youtube-dl on command line runs? Then just run ``rm /Users/Rui/.config/mpv/youtube-dl``.

**Comment by asoksevil** [comment]
How can I do that?

It is now working!

I used mpv rm /Users/Rui/.config/mpv/youtube-dl YoutubeURL

How can I change it so it is just "mpv YouTubeURL"?

Here´s the log:

mpv rm /Users/Rui/.config/mpv/youtube-dl https://www.youtube.com/watch?v=HKVoh7ypmH0
Playing: rm
[file] Cannot open file 'rm': No such file or directory
Failed to open rm.

Playing: /Users/Rui/.config/mpv/youtube-dl
[file] Cannot open file '/Users/Rui/.config/mpv/youtube-dl': No such file or directory
Failed to open /Users/Rui/.config/mpv/youtube-dl.

Playing: https://www.youtube.com/watch?v=HKVoh7ypmH0
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) 'DASH audio' (aac) (external)
AO: [coreaudio] 44100Hz stereo 2ch floatp
VO: [opengl] 638x360 yuv420p
(Paused) AV: 00:00:33 / 00:07:50 (7%) A-V:  0.000 Dropped: 1 Cache: 10s+18MB

**Comment by asoksevil** [comment]
For some "unknown" reason it seems to be working now. I only need to type in mpv YouTubeURL and it pops.
