### ISSUE TITLE
option to use mpv one instance only 

### ISSUE THREAD

**Issue by blackarcher21** [mpv-player/mpv#2610]
I wonder if that's possible. I'm looking for this but seem can't find it on manual. sorry for additional request, but if that's possible, I hope there's a possibilty to append file(s) to playlist on that mode. thanks :)

**Comment by wm4** [comment]
You can use the umpv script.

**Comment by blackarcher21** [comment]
what is umpv script? where I can find this guide? if there's in manual, could you point me that? I would like to know that. thanks

**Comment by wm4** [comment]
https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv

**Comment by blackarcher21** [comment]
okay, thank you :)

**Comment by yoord1992** [comment]
how to use umpv script?
