### ISSUE TITLE
Wrong path example in reference manual

### ISSUE THREAD

**Issue by Hrxn** [mpv-player/mpv#2611]
In this section: https://mpv.io/manual/stable/#files-on-windows

(Both manual versions affected, actually)

Example for the path to mpv.conf there:
> C:\users\USERNAME\Application Data\mpv\mpv.conf

This is misleading, because, as stated, mpv uses %AppData%.
But the example path with %AppData% would be:
> C:\Users\USERNAME\AppData\Roaming\mpv\mpv.conf

N.B.
If you use the echo command from the manual , %AppData% gets substituted and the rest of the string is just appended, so please keep in mind that the directory %AppData%\mpv exists, but the file mpv.conf does not, you have to create it first.

Speaking of mpv.conf, I just started using mpv and I don't have a config yet, so maybe you can point me to some good example configs, primarily for Windows. That would be nice..

**Comment by garoto** [comment]
I can share my config, but bear in mind I'm no expert nor overly anal about video quality and whatnot.

http://pastebin.ca/3293209

**Comment by Hrxn** [comment]
No, that is just fine, exactly what I was looking for. Thanks!

**Comment by kevmitch** [comment]
This is the [official example file](https://raw.githubusercontent.com/mpv-player/mpv/master/etc/example.conf) which strives for sane best practices.
