### ISSUE TITLE
Add JSON IPC event for passing unhandled keyboard input throught to client

### ISSUE THREAD

**Issue by tonycpsu** [mpv-player/mpv#2612]
I've got a Python wrapper around ```mpv``` that uses the JSON IPC protocol.  In some cases, I'd like to have certain keyboard input handled by my python app even when ```mpv``` has the input focus.  The hacktacular solution would be to use ```request_log_messages``` and look for things like:

    {"event":"log-message","prefix":"input","level":"warn","text":"No key binding found for key 'k'.\u000a"}

but the docs suggest making a feature request instead, so I think I'd like to see a command, e.g. ```request_unhandled_input``` that emits something along the lines of:

    {"event":"unhandled-input","key": "k"}

and then the API client can hook into those events properly.

If this sounds like a good idea, I'm happy to take a stab at implementing it and sending a PR.

**Comment by wm4** [comment]
Hm, I could maybe define some sort of fallback command, which is invoked if nothing else is mapped. This could be used to get the equivalent result, without having to add much new mechanism.

**Comment by wm4** [comment]
I implemented something. Not sure if you can puzzle it together yourself. (I now realize this is actually much more complex than just parsing the log message.) Feel free to ask questions.

**Comment by tonycpsu** [comment]
Actually I'd say it's about the same complexity, but since the script-binding functionality is already there, it makes a lot more sense to piggyback on that rather than parsing the unhandled input log messages that could easily be changed in the future.

I didn't have any problems at all switching over to this.  Thanks!
