### ISSUE TITLE
Subtitles disappear when skipping chapters in .MKV files with ordered chapters

### ISSUE THREAD

**Issue by m45t3r** [mpv-player/mpv#2613]
When you skip a chapter in an ordered chapter Matroska file (pressing ``Page Up`` for example), the first ASS subtitle to appear after the skip does not show up. Even if you go back and play that part again, it does not show until you close the file and open again. To make the subtitle to show properly, you need to skip manually instead of using``Page Up``. The strange thing is, after the subtitle appears one time, it always shows properly, even if you close and open the file again. Maybe it is some problem related to cache or something?

I can't put a test file since I don't know any ordered chapter mkv file with ASS that is small enough to post here (nor I do know how to make a ordered chapter mkv file). However I saw this behavior in ``[Coalgirls]_Clannad_(1920x1080_Blu-Ray_FLAC)`` release, both in episodes 4 and 5. You can clearly see one character talking something and no subtitle at all after skipping a chapter (after the first subtitle it appears normally). I first thought it was missing in the translation, however after seeing this in different episodes I tried to play again and it appeared. So it is a bug.

mpv git-a0519f1, build using msys2. ``mpv --version`` output:

    mpv git-a0519f1 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
     built on Sat Dec 19 13:04:35     2015
    ffmpeg library versions:
       libavutil       54.31.100
       libavcodec      56.60.100
       libavformat     56.40.101
       libswscale      3.1.101
       libavfilter     5.40.101
       libswresample   1.2.101
    ffmpeg version: 2.8.2

**Comment by ChrisK2** [comment]
I have that release and have no idea what your problem is. The subs show up perfectly fine for me when skipping around in the chapters.

**Comment by lachs0r** [comment]
--demuxer-mkv-subtitle-preroll?

**Comment by m45t3r** [comment]
@ChrisK2 maybe it is something that ``[Coalgirls]_Clannad_(1920x1080_Blu-Ray_FLAC)`` is doing, I tested again with ``[Coalgirls]_Clannad_~After_Story~_v2_(1920x1080_Blu-Ray_FLAC)`` and it is working fine. However I can reproduce this bug in ``[Coalgirls]_Clannad_(1920x1080_Blu-Ray_FLAC)`` almost any time I open a new file, after that the bug disappears.

**Comment by m45t3r** [comment]
@lachs0r seems to work. Maybe it would be better to this option be enabled by default to ordered chapters files? Or I am saying something stupid?

**Comment by lachs0r** [comment]
At least the manpage claims that it should be enabled by default for absolute 
and hr seeks. Shouldn’t that include chapter seeks? That seems to be a bug.

**Comment by m45t3r** [comment]
@lachs0r I said too soon. This seems to be a pretty difficult bug to reproduce. It seems the chance are better if you're actually watching the episode, and do a chapter skipping to skip OP/ED for example, than just doing multiples chapter skips just to try to reproduce the bug.

Using file ``[Coalgirls]_Clannad_06_(1920x1080_Blu-Ray_FLAC)_[54AAE592].mkv``, watching the whole intro of the episode, skipping the OP as soon as it starts seems to trigger the bug reliable: the episode name, that should be the next subtitle, does not show. It should show something like the image below:

![mpv-shot0001](https://cloud.githubusercontent.com/assets/844343/11915768/e911c7a4-a69c-11e5-92f6-c7c42fcfc7c4.jpg)

If you skip the introduction and OP and go directly to the episode name screen, the subtitle shows normally.

**Comment by lachs0r** [comment]
I just noticed that msys2’s libass PKGBUILD seems to use an outdated version. 
Whether you used that or not, are you able to reproduce this bug with my 
builds (https://mpv.srsfckn.biz)?

**Comment by m45t3r** [comment]
@lachs0r same thing with these build.

Just an update. You don't even need to skip using ``Page Up``. It seems to disappear with normal seek too (using arrow keys).

**Comment by lachs0r** [comment]
Anyway, this is just how the Matroska format works, and depending on where the subtitle packet is, mpv might not see it after seeking. There’s more info here: https://mpv.io/manual/master/#options-demuxer-mkv-subtitle-preroll

You could try increasing `--demuxer-mkv-subtitle-preroll-secs`.

**Comment by m45t3r** [comment]
@lachs0r But by how much? I tried both 240 (since a OP normally is 1:30 min, 2 min seemed fine) and 600. Neither do work.

**Comment by wm4** [comment]
Same as https://github.com/libass/libass/issues/206?

**Comment by m45t3r** [comment]
@wm4 from the description of this bug, seems so. However:

```
thiag@Miku-Windows ~ % pacman -Qi mingw-w64-x86_64-libass
Name            : mingw-w64-x86_64-libass
Version         : 0.13.0-1
Description     : A portable library for SSA/ASS subtitles rendering (mingw-w64)
Architecture    : any
URL             : https://github.com/libass/libass
Licenses        : ISC
Groups          : None
Provides        : None
Depends On      : mingw-w64-x86_64-fribidi  mingw-w64-x86_64-fontconfig
                  mingw-w64-x86_64-freetype  mingw-w64-x86_64-harfbuzz
Optional Deps   : None
Required By     : mingw-w64-x86_64-ffmpeg
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 714.00 KiB
Packager        : Alexey Pavlov <alexpux@gmail.com>
Build Date      : Tue Oct 6 06:15:18 2015
Install Date    : Tue Oct 6 20:35:44 2015
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

According to one reporter, this was happening in version 0.13.1 only, however I seem to be using 0.13.0.

**Comment by wm4** [comment]
OK, then this is most likely just a broken file. You can try playing with the ``--sub-clear-on-seek`` option.

**Comment by m45t3r** [comment]
@wm4 seems to work. Thanks.

**Comment by wm4** [comment]
I think 6d9cb89 should happen to fix this as well.
