### ISSUE TITLE
Different delays when using "--secondary-sub"

### ISSUE THREAD

**Issue by TheStealthReporter** [mpv-player/mpv#2629]
The feature of showing two subtitles at once is extremely useful when watching films in two languages, because you can simultaneously have the subtitles of your native languages and the subtitles in the language you want to learn.

The problem is that often the subtitles have not the same timing (in relation to the video). When only using one subtitle you can correct this with "sub-delay", but when using two subtitles (with "secondary-sid") this value applies to both files. For example: subtitle 1 is perfectly aligned with the video, but the second subtitle is +10s compared to the video. When using "sub-delay=-10" the second subtitle is now perfect but the first is wrong.

There are be multiple solutions to this problem:

1) "inter-sub-delay"
The delay of the secondary sub is now "sub-delay + inter-sub-delay". So "sub-delay" still influences the second subtitle.

2) "secondary-sub-delay"
The value "sub-delay" does not influence the delay of the second subtitle. Instead there is an independent value called "secondary-sub-delay".

3) per-file-delays
This would be the solution I prefer. Example: in case you have you have three or more subtitles you want to cycle through (this happens sometimes to me). Subtitle 1 can be perfect, subtitle 2 could be "+10s" and subtitle 3 could be "-10s". Because the subtitle for "secondary-sid" can change, using "+10s" or "-10s" for "inter-sub-delay" or "secondary-sub-delay" won't work. It is clear that per-file-delays are needed here.

I would be happy with either of these solutions. This would really simplify playing files without having to edit and re-time the subtitle files (that destroys the formatting of subtitles in some programs).

In case there is already a way around this problem (which was unable to find)  I would be grateful if you can describe it to me.

**Comment by lachs0r** [comment]
On Tuesday 22 December 2015 07:00:22 TheStealthReporter wrote:
> I would be happy with either of these solutions This would really simplify
> playing files without having to edit and re-time the subtitle files (that
> destroys the formatting of subtitles in some programs)

FYI, Aegisub should preserve the formatting. And just shifting subtitles by a 
constant value is very easy with it, too.

**Comment by polarbearing** [comment]
implementation as a separate ```--secondary-sub-delay``` would be the preferred solution.
