### ISSUE TITLE
External audio directory specification (audio equivalent of --sub-paths)

### ISSUE THREAD

**Issue by stereolink** [mpv-player/mpv#2632]
I have seen that recently there was a change to make essentially an audio equivalent of --sub-auto (#967).

I think there should also be a setting to specify directories to look for external audio to autoload. Like how I can set `sub-paths=subs` for external subtitles, I'd like to be able to say something like `audio-file-paths=dubs` for external audio.

I cannot find something like this in the man page, please let me know if it is in fact implemented and I just missed it, otherwise I think it's an appropriate addition for making external audio seamless.

**Comment by Kagami** [comment]
Agreed. Auto-loading external audio tracks from sub-paths and make them preferred is confusing behavior IMO. I have a lot of videos for which I want to load external subs but I don't want external audio tracks (typical use-case: anime + external subs + external dub). Right now there is no solution for this except removing all external tracks/mux them into video.

**Comment by wm4** [comment]
Please test. I didn't, but I have no reason to believe that it wouldn't work.

**Comment by Kagami** [comment]
But this just makes `--audio-file-paths` almost synonym of `--sub-paths` which doesn't make much sense. I think the requested feature is about making `--sub-paths` to load **only** subtitles and `--audio-file-paths` to load **only** external audio tracks.

**Comment by wm4** [comment]
True, hopefully fixed.
