### ISSUE TITLE
sub-codepage doesn't work with enca anymore

### ISSUE THREAD

**Issue by Kagami** [mpv-player/mpv#2633]
I can't make `--sub-codepage` work with enca with latest mpv.

[test.webm](http://dump.bitcheese.net/files/ukirune/test.webm)
[test.srt](http://dump.bitcheese.net/files/yzopoju/test.srt) in cp1251

```
$ mpv --version
mpv git-940007c (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.11.100
   libavcodec      57.19.100
   libavformat     57.20.100
   libswscale      4.0.100
   libavfilter     6.21.100
   libswresample   2.0.101
ffmpeg version: N-77421-gd3dbae1
```

This one works:

```
$ mpv --no-config --sub-codepage=cp1251 test.webm
Playing: test.webm
[lavf] Using subtitle charset: cp1251
 (+) Video --vid=1 (*) (vp8)
 (+) Subs  --sid=1 'test.srt' (subrip) (external)
[vo/opengl/x11] Disabling screensaver failed (-1). Make sure the xdg-screensaver script is installed.
VO: [opengl] 640x360 yuv420p
[osd/libass] fontconfig: cannot find font 'sans-serif', falling back to 'Liberation Sans'
V: 00:00:01 / 00:00:10 (10%)
fontconfig: cannot find font 'sans-serif', falling back to 'Liberation Sans'
```

This one doesn't:

```
$ mpv --no-config --sub-codepage=enca:ru:utf8 test.webm
Playing: test.webm
 (+) Video --vid=1 (*) (vp8)
 (+) Subs  --sid=1 'test.srt' (subrip) (external)
[vo/opengl/x11] Disabling screensaver failed (-1). Make sure the xdg-screensaver script is installed.
[ffmpeg] srt: Invalid UTF-8 in decoded subtitles text; maybe missing -sub_charenc option
[sub/ass] Error decoding subtitle
VO: [opengl] 640x360 yuv420p
[osd/libass] fontconfig: cannot find font 'sans-serif', falling back to 'Liberation Sans'
V: 00:00:01 / 00:00:10 (10%)
```

`--sub-codepage=cp1251` doesn't work with another real video and sub track though, but I can't reproduce it on a simple test-case.

**Comment by lachs0r** [comment]
Enca isn’t very reliable. Try `--sub-codepage=uchardet`.

**Comment by Kagami** [comment]
Installed `uchardet` package, recompiled mpv and it works now indeed (even by default, without any language settings provided). Thanks.
I guess this is related to enca and still needs to be fixed?

**Comment by lachs0r** [comment]
That’s just enca misdetecting your file’s encoding. Not our bug.

(Also, uchardet doesn’t even have a language or fallback setting.)

**Comment by Kagami** [comment]
enca can detect this file:

```
$ enca -L ru test.srt
MS-Windows code page 1251
```

And it perfectly worked before (I think git-master checkout several weeks ago). Also, I can't make work even `uchardet` on another file, but can't reproduce it yet.

**Comment by lachs0r** [comment]
Well, in that case…

**Comment by Kagami** [comment]
Ah, I think that's because another file was in ASS format. [test.ass](http://dump.bitcheese.net/files/anefaki/test.ass) in cp1251.

```
$ enca -L ru test.ass
MS-Windows code page 1251
$ mpv --no-config --sub-codepage=cp1251 test.webm
Playing: test.webm
 (+) Video --vid=1 (*) (vp8)
 (+) Subs  --sid=1 'test.ass' (ass) (external)
[vo/opengl/x11] Disabling screensaver failed (-1). Make sure the xdg-screensaver script is installed.
VO: [opengl] 640x360 yuv420p
[osd/libass] fontconfig: cannot find font 'sans-serif', falling back to 'Liberation Sans'
V: 00:00:01 / 00:00:10 (10%)
fontconfig: cannot find font 'Arial', falling back to 'Liberation Sans'
V: 00:00:02 / 00:00:10 (20%)
```

It doesn't use `cp1251` codepage even when it's passed explicitly.

**Comment by lachs0r** [comment]
Well, yes, ASS is assumed to be always UTF-8, and everything else is just a broken file. Shoot whomever created this.

**Comment by Kagami** [comment]
Hm, you're right, I checked and all other ASS files I have are in UTF-8 indeed. I thought that it might be related at first.

**Comment by wm4** [comment]
So does it work or not?

Also, we should probably drop enca. It's officially dead, and uchardet actually sees some active development.

**Comment by Kagami** [comment]
`--sub-codepage=enca:ru:utf8` still doesn't work for `srt` subs. Can you reproduce it with my test files? It should display «тест» text but instead I see an error in console.

**Comment by wm4** [comment]
When did this break? 0.12.0 is also "broken".

Actually, I double-checked what we pass to ENCA, and it's all correct. It simply returns no result. I don't know why the enca command line utility does. Won't waste more time on this.

**Comment by Kagami** [comment]
mpv enca detection actually works with larger files (real subtitles in non-utf8), sorry for the vague report. I was just confused by seeming correlation of several issues.

**Comment by FeiWongReed** [comment]
> Well, yes, ASS is assumed to be always UTF-8, and everything else is just a broken file. Shoot whomever created this.
There is A LOT OF incorrectly encoded ASS subtitles. You definitely should pass them through codepage detection. BTW, it worked correctly until 0.14

**Comment by Koshon** [comment]
..or use small command for all .ass files in directory: enconv -x UTF-8 *.ass
as an alternative solution...

**Comment by FeiWongReed** [comment]
Its not a solution when you are seeding.

**Comment by wm4** [comment]
When you are seeding, you should seed UTF-8 files, instead of insane legacy codepage files.

**Comment by Koshon** [comment]
FeiWongReed sad
> Its not a solution when you are seeding.
But for me (and i think more others) better solution than patch something.

**Comment by FeiWongReed** [comment]
If I seeding my own torrent its ok. But what about others'?
You can't enforce all the anime girls to produce CORRECT SUBS.

**Comment by FeiWongReed** [comment]
Solution is already merged into master, so you should just wait (or use gentoo with patch in /etc/portage/patches).

**Comment by Koshon** [comment]
FeiWongReed, in this regard i agree with wm4, cuz UTF more.. unified(?). And if you look at the subtitles now, you will see that the subbers make files in utf-8.

**Comment by FeiWongReed** [comment]
Not all of them and there is a lot of many-year-old torrents with "bad" or incorrectly named subs (srt with .ass extension)

**Comment by Koshon** [comment]
FeiWongReed, i not have the example files, but enconv works with all text files

**Comment by FeiWongReed** [comment]
It works. But just imagine. I have downloaded torrent and started to seed. I don't want to make a copy and waste 10gb of space to recode 24 subtitle files. I just want to run my player and watch. And additional compatibility quirk in that player is not a shame or something bad. Its ok to have quirks just for user convenience.

**Comment by Koshon** [comment]
Ye, i think you right, especially if it is container mkv.
