### ISSUE TITLE
Video gets choppy on OS X when fullscreen and there’s network activity

### ISSUE THREAD

**Issue by vitorgalvao** [mpv-player/mpv#2636]
I’ve had this bug for a while, and I’ve deleted all my setting to be sure it wasn’t something I set.

On OS X, if someone is writing us through [Messages](https://www.apple.com/osx/apps/#messages), we get a preview `…` message, indicating the person is writing something. This is how I was able to narrow it down and be sure it happens in these situations (I’m able to reproduce reliably), but keep in mind Message doesn’t need to be open to actually receive messages (and warn you of them).

If someone is writing me a message *and* I have a video in fullscreen, playback will get choppy until the person either sends the message, of deletes it. This isn’t exclusive to Messages, though. I can also reproduce if I use [Tweetbot](http://tapbots.com/tweetbot/mac/) and I keep streaming tweets. The more there are, the longer it takes to display, and the longer the choppiness lasts.

Audio still works fine. Everything works fine if the video is not fullscreen (even the actual size of the video is bigger than the screen) and I can even get in and out of fullscreen in rapid succession and see the issue manifest.

This isn’t a streaming issue, since it happens with local videos.

Currently on `mpv` version `0.14.0`, installed via `homebrew` with no specified flags, from [the official repo](https://github.com/mpv-player/homebrew-mpv). OS X El Capitan `10.11.2`. Not sure it happened on previous OS X versions, but it definitely happened on previous `mpv` versions.

**Comment by pigoz** [comment]
Are you sure it's not related to issue #2392?

**Comment by vitorgalvao** [comment]
I’ll assume they are related until I can perform more tests. I haven’t found that issue since I was focused on network usage, but apparently it seems they may be the same. If I find they’re not, I’ll report back and reopen.

Thank you.

**Comment by pigoz** [comment]
Ok, if you can somehow isolate the issue please let us know! We are still not sure what is causing it :(
