### ISSUE TITLE
Robidoux and RobidouxSharp BC-spline parameters only have 4 digits

### ISSUE THREAD

**Issue by nrobidoux** [mpv-player/mpv#2637]
I doubt very much anyone will notice any difference arising from the truncation to four decimals of the Robidoux and RobidouxSharp BC-spline parameter values, but nonetheless I suggest that you use the exact values

```
{{"robidoux",       2,   cubic_bc, .params = {12./(19.+9.*sqrt(2.)), 113./(58.+216.*sqrt(2.))} }},
    {{"robidouxsharp",  2,   cubic_bc, .params = {6./(13.+7.*sqrt(2.)), 7./(2.+12.*sqrt(2.))} }},
    {{"ewa_robidoux",       2,   cubic_bc, .params = {12./(19.+9.*sqrt(2.)), 113./(58.+216.*sqrt(2.))}, .polar = true},
    {{"ewa_robidouxsharp",  2,   cubic_bc, .params = {6./(13.+7.*sqrt(2.)), 7./(2.+12.*sqrt(2.))}}, .polar = true},
```

in https://github.com/mpv-player/mpv/blob/master/video/out/filter_kernels.c, instead of

```
{{"robidoux",       2,   cubic_bc, .params = {0.3782, 0.3109} }},
    {{"robidouxsharp",  2,   cubic_bc, .params = {0.2620, 0.3690} }},
    {{"ewa_robidoux",       2,   cubic_bc, .params = {0.3782, 0.3109}}, .polar = true},
    {{"ewa_robidouxsharp",  2,   cubic_bc, .params = {0.2620, 0.3690}}, .polar = true},
```

Reference: http://web.cs.laurentian.ca/nrobidoux/misc/AdamTurcotteMastersThesis.pdf Sections 4.8.6.1 and 4.8.6.3 as well as numerous earlier ImageMagick Forum posts.

**Comment by wm4** [comment]
Thanks. Blindly copied your suggestion; I hope I didn't accidentally add bugs.
