### ISSUE TITLE
Trying to build mpv on Raspberry Pi 2 but fails.

### ISSUE THREAD

**Issue by Xenphor** [mpv-player/mpv#2638]
I'm using archlinux arm and want to build MPV with support for the Raspberry Pi but I'm getting errors. I know it has to do specifically with raspberry pi support because if I disable it in the configure it will build fine. Here is the log: 

http://pastebin.com/eL0X0gqU

**Comment by wm4** [comment]
Seems like vo_rpi has been broken for a while.

**Comment by Xenphor** [comment]
If I build it again I get an error about rpi.h not being found. Anyone know where I can get this?

http://pastebin.com/idLZWQbs

I installed the kernel headers but I guess it's related to opengl maybe?
