### ISSUE TITLE
The hole desktop except cursor freezes sometimes when I leave full screen.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2640]
OS: elementary OS (based on Ubuntu)
mpv version: 0.14.0 git-fc7212b ffmpeg version
ffmpeg library versions:
>libavutil       55.11.100
>libavcodec      57.18.100
>libavformat     57.20.100
>libswscale      4.0.100
>libavfilter     6.21.100
>libswresample   2.0.101

ffmpeg version: N-77406-gf6830cf
mpv.conf:
>sub-auto=fuzzy
>no-osd-bar
>vo=opengl
    hwdec=vaapi

**Comment by lachs0r** [comment]
Driver bug, we can’t do anything about this. Try without `hwdec` or with a different video output.

**Comment by mc4man** [comment]
More likely an  elementary OS bug, report here - https://bugs.launchpad.net/elementaryos/+bug/1529435
prior instance - http://elementaryos.stackexchange.com/questions/2304/what-do-i-do-when-my-screen-freezes-but-the-mouse-still-works

**Comment by laichiaheng** [comment]
They told me that it could be a "mpv player" bug.
