### ISSUE TITLE
ao=wasapi:exclusive sometimes doesn't play audio

### ISSUE THREAD

**Issue by alabrand** [mpv-player/mpv#2642]
I don't know if this is a bug or an inherent thing with ao=wasapi:exclusive but sometimes it doesn't play audio. Something I have noticed is that it tends to have an issue with multi-channel FLAC, like 5.1 for example, which is sometimes the only audio available.

What happens is that some parts of the audio will play, like background noises, but other parts of the audio will not play, like character voices.

ao=wasapi works like it should however. Is there any audible differences between ao=wasapi and ao=wasapi:exclusive?

**Comment by kevmitch** [comment]
is your output device stereo? can you post a log with --msg-level=ao=verbose? do you have a sample file?

The main advantage of ```ao=wasapi:exclusive``` is that it opens the device at the correct sampling rate rather than resampling to the shared mode sampling rate.

**Comment by kevmitch** [comment]
sorry probably better to use ```--msg-level=ao=debug``` to get more messages

**Comment by alabrand** [comment]
Does these logs work alright or should I try it again? There are two separate logs, one for Wasapi and one for Wasapi:Exclusive.

[output wasapi exclusive.txt](https://github.com/mpv-player/mpv/files/73238/output.wasapi.exclusive.txt)
[output wasapi.txt](https://github.com/mpv-player/mpv/files/73239/output.wasapi.txt)

**Comment by kevmitch** [comment]
Ok, so it's opening the device as 

    5.1(side) s16 @ 48000hz

which brings us back to my above question: is your device stereo only or does it actually support 5.1?

**Comment by kevmitch** [comment]
It looks like your shared mode is stereo. ```--audio-format=stereo``` will probably fix it. 

Either your devices doesn't actually support 5.1 and it's drivers are lying that it does, or you don't have the necessary speakers connected.

**Comment by kevmitch** [comment]
ughgh, I mean  ```--audio-channels=stereo```

**Comment by alabrand** [comment]
Ah, yes, audio-channels=stereo solves the problem.

**Comment by kevmitch** [comment]
```audio-channels=stereo``` is now the default as of 930b0d1cf6f2ffa6bf3df516e120a395e1c60342 to avoid problems like this.
