### ISSUE TITLE
decode video frames to memory 

### ISSUE THREAD

**Issue by smolleyes** [mpv-player/mpv#2643]
hi is it possible to add the possibility to decode video frames to memory thru the api to mpv ? (so without attached window) ?

thanks

**Comment by lachs0r** [comment]
Maybe you want ffms2 instead? Or, in fact, VapourSynth?

**Comment by wm4** [comment]
Not possible directly, but in theory you could set ``null`` as VO, and then use the ``screenshot-raw`` command to retrieve whatever frame is considered current.

**Comment by smolleyes** [comment]
hello

i can t find any screenshot-raw option wm4 (just builded mpv from sources)

**Comment by kevmitch** [comment]
see [the manual](https://mpv.io/manual/master/#command-interface-screenshot-raw)
