### ISSUE TITLE
Playing video with wrong speed.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2644]
I was watching a .ogv video which was recorded by recordmydesktop, and the playing speed is too fast, but it plays flawlessly on YouTube: https://youtu.be/t1NA0wqZ2SU

The message in terminal:

> [ffmpeg/demuxer] ogg: Broken file, keyframe not correctly marked.
> (+) Video --vid=1 (theora)
> (+) Audio --aid=1 (vorbis)
> libva info: VA-API version 0.38.0
> libva info: va_getDriverName() returns 0
> libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
> libva info: Found init function __vaDriverInit_0_38
> libva info: va_openDriver() returns 0
> [ffmpeg/demuxer] ogg: Broken file, keyframe not correctly marked.
> AO: [pulse] 22050Hz mono 1ch float
> [vo/opengl/x11] Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.
> Using software decoding.
> VO: [opengl] 1920x1072 yuv420p
> AV: 00:00:00 / 00:00:22 (6%) A-V:  0.000
> Invalid video timestamp: 0.266667 -> 0.500000
> AV: 00:00:00 / 00:00:22 (11%) A-V: -0.198
> Invalid video timestamp: 0.850000 -> 0.983333
> AV: 00:00:00 / 00:00:22 (11%) A-V: -0.332
> [ffmpeg/demuxer] ogg: Broken file, keyframe not correctly marked.
> AV: 00:00:01 / 00:00:22 (11%) A-V: -0.310 ct: -0.057
> Invalid video timestamp: 1.200000 -> 1.500000
> 
> Audio/Video desynchronisation detected! Possible reasons include too slow
> hardware, temporary CPU spikes, broken drivers, and broken files. Audio
> position will not match to the video (see A-V status field).
> 
> AV: 00:00:01 / 00:00:22 (12%) A-V: -0.610 ct: -0.057
> Invalid video timestamp: 1.500000 -> 2.000000
> AV: 00:00:02 / 00:00:22 (14%) A-V: -1.100 ct: -0.067
> [ffmpeg/demuxer] ogg: Broken file, keyframe not correctly marked.
> etc....

**Comment by richardpl** [comment]
Link to ogv file?

**Comment by laichiaheng** [comment]
@richardpl https://drive.google.com/open?id=0BxnS0W8xlR-QS1lRWk4tMWM5R1k

**Comment by lachs0r** [comment]
(Also, if that’s your video, use https://github.com/MaartenBaert/ssr next time. Preferably with a different container format.)

**Comment by lachs0r** [comment]
Broken file, sample 404’d.
