### ISSUE TITLE
"audio-peak-value" property

### ISSUE THREAD

**Issue by lukaszmatczak** [mpv-player/mpv#2645]
Currently, external apps must use OS-dependent API to retrieve peak value of audio stream, for example IAudioMeterInformation::GetPeakValue() on Windows. Is it possible to add property like "audio-peak-value" accessible from Lua script?

**Comment by wm4** [comment]
There might be a filter in libavfilter which can compute this value; then it should be retrieved with the ``af-metadata`` property.

**Comment by lukaszmatczak** [comment]
Sounds great. I'm waiting for this feature. Thank you for help!

**Comment by wm4** [comment]
Well, the mechanisms are already all there.

I'm not sure whether libavfilter actually has a filter which does this. I thought the ``volumedetect`` filter does, but it merely prints the stats on the terminal at deinitialization, instead of passing it through the API.

Maybe @richardpl is interested in implemented a filter that does this?

**Comment by richardpl** [comment]
If I'm not mistaken there is already filter that reports bunch of info including max and min sample value in audio, it works with floats and its name is `astats`.

**Comment by wm4** [comment]
Indeed, looks like this should work.

For some really weird reason, it requires a `metadata` suboption to be set.

**Comment by lukaszmatczak** [comment]
Works excellent. Thank you!

**Comment by dweymouth** [comment]
@lukaszmatczak this was years ago but if you happen to remember how you did this I'd love if you could share some sample code. I am trying to do the same thing to add a peak meter to my music player app that uses libmpv but I can't figure it out!

**Comment by lukaszmatczak** [comment]
@dweymouth I've used code like this:
```lua
function send_state()
    local astats = mp.get_property_native("af-metadata/level")

    if astats ~= nil then
        print(astats["lavfi.astats.Overall.Max_level"])
    end
end

mp.add_periodic_timer(0.1, send_state)
```
And then I could read the current level in the parent process from mpv's stdout.

Also, I had to add `--af=@level:lavfi="astats=metadata=1:reset=4"` to the command line options.

Please note that this code is quite old and there may be a better solution now.
