### ISSUE TITLE
Slight horizontal "flicker" in playback, possible related to graphic drivers? Debian Testing

### ISSUE THREAD

**Issue by nonaddictuser** [mpv-player/mpv#2646]
Beginner here with an issue...

When I am playing videos i am experiencing a slight "horizontal flicker" (not sure how to describe it better). It doesnt happen all the time but rather "comes and goes"... It is not "lag" due to a slow connection - i have configured the playback to use a large buffer which works fine.

Could it be that i use a bad "vo" option? Currently using "opengl"...

I have my mpv.conf file attached.

[asd.txt](https://github.com/mpv-player/mpv/files/73623/asd.txt)

Furthermore:

Running Debian Testing (currently Stretch)

**Comment by wm4** [comment]
Is it tearing?

**Comment by nonaddictuser** [comment]
@wm4 Yes! After googling, I do believe tearing is the accurate term!

**Comment by kevmitch** [comment]
What graphics device are you using? [see also](https://github.com/mpv-player/mpv/wiki/FAQ#tearing)

**Comment by nonaddictuser** [comment]
@kevmitch Thanks for the "see also"-link! I think i solved the issue by simply changing to "vo=xv:adaptor=1" instead of "vo=opengl".

Only problem now is that i have a weird blue field in the bottom of my screen... I think it has to do with my dual monitor setup.

(If it is still relevant, I have a AMD Radeon HD 8570M)

**Comment by wm4** [comment]
Well, the problem is with your graphics drivers and possibly desktop environment (compositors can add or fix tearing). mpv has little control over this. Xv is not recommended, because subtitle rendering will be slow, and video rendering tends to have quality issues (it won't provide anything better than bilinear).

**Comment by nonaddictuser** [comment]
@wm4 I see.... Actually not using a desktop environment (currently on i3wm) so i suppose then it is a graphics driver issue. Any clue where to go next?

**Comment by Q3CPMA** [comment]
I don't know how old the Debian package is, but with the radeon Xorg driver 7.6, you have the tearfree option.
