### ISSUE TITLE
Performance problems on intel hd3000

### ISSUE THREAD

**Issue by Yamakaky** [mpv-player/mpv#2650]
Since a few versions, mpv uses a lot of cpu resources when viewing 1080p videos, even with vaapi. Is it known ? I don't have measurements, it's just that the fan are always on, while before they stayed mostly off.

```
mpv 0.14
ffmpeg 2.8.4
```

config:

```
# Write your default config options here!

hwdec=vaapi
vo=opengl-hq
ao=pulse
sub-auto=fuzzy
osd-duration=3000
slang=eng
save-position-on-quit
```

**Comment by Cpuroast** [comment]
Depending on which version you were running before, opengl-hq now does debanding by default which does increase GPU usage a bit
You could try this and see if it makes a diff: vo=opengl-hq:deband=no

Besides that, not much has changed in the opengl-hq string for some time.

The other thing would be if you are viewing 1080p videos that not 8-bit, when that happens it falls back to 100% cpu decoding, as the Intel GPUs can't decoding those in hardware.
