### ISSUE TITLE
http_proxy (option not found)

### ISSUE THREAD

**Issue by Poilaucul** [mpv-player/mpv#2655]
The http_proxy option does not seem to be found on mpv 0.14.0

How do you pass proxy settings to mpv?

>[   0.004][v][cplayer] Command line options: '--log-file=output.txt'
[   0.004][v][cplayer] mpv 0.14.0-git-e1993d5 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[   0.004][v][cplayer]  built on Fri Dec 11 20:18:31 CET 2015
[   0.004][v][cplayer] ffmpeg library versions:
[   0.004][v][cplayer]    libavutil       55.10.100
[   0.004][v][cplayer]    libavcodec      57.17.100
[   0.004][v][cplayer]    libavformat     57.19.100
[   0.004][v][cplayer]    libswscale      4.0.100
[   0.004][v][cplayer]    libavfilter     6.20.100
[   0.004][v][cplayer]    libswresample   2.0.101
[   0.004][v][cplayer] ffmpeg version: N-77205-g5990ccf
[   0.004][v][cplayer] 
[   0.004][v][cplayer] Configuration: /home/lachs0r/mingw-w64-cmake/buildroot/build64/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-win32-internal-pthreads --enable-gpl3 --enable-waio --enable-lua --enable-libarchive --enable-libass --enable-libbluray --enable-dvdread --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --prefix=/home/lachs0r/mingw-w64-cmake/buildroot/build64/prefix/mingw
[   0.004][v][cplayer] List of enabled features: asm atomics av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avframe-metadata avframe-skip-samples build-date c11-tls cplayer debug-build direct3d dlopen dos-paths dsound dvdnav dvdread dxva2-hwaccel encoding gl gl-dxinterop gl-win32 glob-win32-replacement gpl3 iconv jpeg lcms2 libarchive libass libass-osd libav libavdevice libavfilter libbluray libm libmpv-shared libswresample lua mingw noexecstack optimize posix-or-mingw resampler rubberband sse4-intrinsics static-build stdatomic subprocess tv uchardet waio wasapi win32 win32-internal-pthreads zlib
[   0.005][v][global] config path: '' -> 'C:\Users\lalberi\AppData\Roaming/mpv'
[   0.005][v][global] config path: 'mpv.conf' -/-> 'C:\Users\lalberi\AppData\Roaming/mpv/mpv.conf'
[   0.005][v][global] config path: 'config' -/-> 'C:\Users\lalberi\AppData\Roaming/mpv/config'
[   0.006][v][global] config path: 'mpv.conf' -> 'C:/Program Files/MPV/mpv.conf'
[   0.006][v][global] config path: 'config' -/-> 'C:/Program Files/MPV/config'
[   0.006][v][global] config path: 'mpv.conf' -/-> 'C:/Program Files/MPV/mpv/mpv.conf'
[   0.006][v][global] config path: 'config' -/-> 'C:/Program Files/MPV/mpv/config'
[   0.006][v][cplayer] Reading config file C:/Program Files/MPV/mpv.conf
[   0.007][e][cplayer] Error parsing option http_proxy (option not found)
[   0.009][e][cplayer] C:/Program Files/MPV/mpv.conf:3: setting option http_proxy='http://172.16.1.121:9090' failed.
[   0.009][v][cplayer] Setting option 'alang' = 'jp,jpn,en,eng' (flags = 4)
[   0.009][v][cplayer] Setting option 'slang' = 'fr,en,eng' (flags = 4)
[   0.009][v][cplayer] Setting option 'cache' = 'yes' (flags = 4)
[   0.009][v][cplayer] Setting option 'cache-default' = '1024000' (flags = 4)
[   0.009][v][cplayer] Setting option 'vo' = 'opengl:scaler-resizes-only:prescale=nnedi3:scale=ewa_lanczossharp:cscale=ewa_lanczossoft:tscale=mitchell:temporal-dither:blend-subtitles:pbo:target-prim=bt.709:target-trc=bt.1886:gamma-auto:icc-profile-auto:3dlut-size=256x256x256' (flags = 4)
[   0.009][v][cplayer] Setting option 'hwdec' = 'dxva2-copy' (flags = 4)
[   0.009][v][cplayer] Setting option 'save-position-on-quit' = 'yes' (flags = 4)
[   0.009][v][cplayer] Setting option 'script-opts' = 'osc-layout=bottombar,osc-hidetimeout=3000,osc-seekbarstyle=bar,script-opts=osc-vidscale=no,osc-scalefullscreen=1.5,osc-scalewindowed=1.2' (flags = 4)
[   0.009][v][cplayer] Setting option 'no-border' = '' (flags = 4)
[   0.009][v][cplayer] Setting option 'ontop' = '' (flags = 4)
[   0.009][v][cplayer] Setting option 'screenshot-format' = 'png' (flags = 4)
[   0.009][v][cplayer] Setting option 'screenshot-png-filter' = '0' (flags = 4)
[   0.009][v][cplayer] Setting option 'screenshot-png-compression' = '4' (flags = 4)
[   0.009][v][cplayer] Setting option 'log-file' = 'output.txt' (flags = 8)
[   0.010][i][cplayer] mpv 0.14.0-git-e1993d5 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
[   0.011][i][cplayer]  built on Fri Dec 11 20:18:31 CET 2015
[   0.012][i][cplayer] ffmpeg library versions:
[   0.012][i][cplayer]    libavutil       55.10.100
[   0.013][i][cplayer]    libavcodec      57.17.100
[   0.014][i][cplayer]    libavformat     57.19.100
[   0.014][i][cplayer]    libswscale      4.0.100
[   0.022][i][cplayer]    libavfilter     6.20.100
[   0.023][i][cplayer]    libswresample   2.0.101
[   0.024][i][cplayer] ffmpeg version: N-77205-g5990ccf
[   0.025][i][cplayer] 
[   0.026][i][cplayer] Usage:   mpv [options] [url|path/]filename
[   0.026][i][cplayer] 
[   0.027][i][cplayer] Basic options:
[   0.028][i][cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[   0.029][i][cplayer]  --no-audio        do not play sound
[   0.029][i][cplayer]  --no-video        do not play video
[   0.031][i][cplayer]  --fs              fullscreen playback
[   0.033][i][cplayer]  --sub-file=<file> specify subtitle file to use
[   0.034][i][cplayer]  --playlist=<file> specify playlist file
[   0.035][i][cplayer] 
[   0.036][i][cplayer]  --list-options    list all mpv options
[   0.036][i][cplayer]

**Comment by ChrisK2** [comment]
environment variable.

``http_proxy=http://my.proxy/ mpv http://some/url``

**Comment by Poilaucul** [comment]
This should be set as a windows environment variable?

**Comment by Hrxn** [comment]
Yes.

Temporary: `set`
http://ss64.com/nt/set.html

Permanent: `setx`
http://ss64.com/nt/setx.html

**Comment by edo44** [comment]
I set `http_proxy=127.0.0.1:8118` as an environmental variable  for privoxy, but looking at the firewall it doesn't work when I open a youtube video. I just put `mpv "youtubelink"` in the terminal to load the video, maybe I'm missing some steps like restarting the OS?
