### ISSUE TITLE
Property "mute" doesn't exist for videos without audio

### ISSUE THREAD

**Issue by nezumisama** [mpv-player/mpv#2656]
I just noticed that mute doesn't exist when I play a video with no audio. Would be cool if it existed with a default so that my script doesn't have to change behaviour in such cases (e.g. mute could return false and setting be ignored).
Or at least, there needs to be a note about properties unavailable under certain circumstances in the manual.

**Comment by wm4** [comment]
Until this is changed somehow, you can probably set ``options/mute``. But be aware that there are issues with this.

**Comment by wm4** [comment]
I think this was changed. It should "work" now, with some caveats.
