### ISSUE TITLE
Fullscreen on wayland is not centering/blackening screen.

### ISSUE THREAD

**Issue by judu** [mpv-player/mpv#2657]
Hi,
I'm running mpv on an exherbo machine with wayland and the last stable Gnome-Shell on it.
Before that I was running it on the same machine, but on X11, and everything was fine.

Since I switched to wayland, the fullscreen acts weirdly: the video is pushed to the top-right corner and maximised until either the height or the width hits the other side of the screen, and then the part that is not covered by the image still displays what's behind.

Here is what it looks like when not fullscreen (note that I also have no window decoration anymore):
![mpv-nofs-screenshot](https://cloud.githubusercontent.com/assets/221365/12071587/209c2608-b0b4-11e5-86f4-b8ab7bd071ed.png)

And when in fullscreen:
![mpv-fs-screenshot](https://cloud.githubusercontent.com/assets/221365/12071589/3ef58f7c-b0b4-11e5-9486-f1788d5acb63.png)

And here is the logs when I ran mpv (I fullscreened mpv, I unfullscreened it, I moved it a bit, so it might reflect in the logs):
[mpv-log.txt](https://github.com/mpv-player/mpv/files/75975/mpv-log.txt)

I just saw that I switched to wayland almost at the same time I updated mpv to 0.14. I'm trying to build the old (0.13 version) back to check how it behaves.

In the mean time, here is my full install (w/ build) log of mpv 0.14:
[mpv-build-log.txt](https://github.com/mpv-player/mpv/files/75972/mpv-build-log.txt)

**Comment by judu** [comment]
Same deal with mpv 0.13. I'm trying the scm just in case.
I can apply any patch and try any configure options you might need.

(Oh, and happy new year!)

**Comment by wm4** [comment]
>note that I also have no window decoration anymore

That is expected. Wayland uses client-side window decorations. Neither do we want mpv to depend on a bloated toolkit just to draw the decorations, nor do we know which decorations to draw (there are going to be many wayland compositors, impossible for mpv to achieve a "native" look).

**Comment by judu** [comment]
Ok for the decoration stuff, it does not bother me at all, I just thought it might have been related :)

**Comment by bluerider** [comment]
Strangely, the video fullscreens and centers in weston.

**Comment by judu** [comment]
I confirm that.

**Comment by giselher** [comment]
mpv uses the official shell protocol `wl_shell`, which is not correctly implement in gnome. gnome heavily relies on the new but still unstalbe `xdg_shell`.

**Comment by giselher** [comment]
Fixed with:    eb6b2b6e

**Comment by bluerider** [comment]
I just compiled mpv from the master branch with https://github.com/mpv-player/mpv/commit/eb6b2b6e50e6e3d3db41190ad818d8b966750734 applied. It doesn't seem to be fixed.

**Comment by giselher** [comment]
Can you post a screenshot.

**Comment by bluerider** [comment]
![screenshot from 2016-02-07 13-26-01](https://cloud.githubusercontent.com/assets/4624935/12874275/ac7b1f7e-cd9e-11e5-8b39-59a0cf0213d2.png)

**Comment by giselher** [comment]
Status update: I have an Idea for a solution but implementing takes a bit longer then expected.

**Comment by magcius** [comment]
If you feel wl_shell is incorrectly implemented in GNOME, let us know so we can fix it.

**Comment by Weegee** [comment]
This issue still seems to exist under GNOME 3.20 and mpv 0.16.0, using vo=opengl.

mpv windowed:
![](https://puu.sh/o4qsT/975aab7ebc.png)

mpv in fullscreen:
![](https://puu.sh/o4qvc/ec6d6eb995.png)

**Comment by wm4** [comment]
This also doesn't behave right on weston. Instead of filling the screen, it takes the scales the window size to the closest screen border. At least weston seems to clear the background, though. No idea how to fix it, naively setting width=fs_width (and same for height) gives strange results.

**Comment by wm4** [comment]
Fixed via #3123.
