### ISSUE TITLE
vo=wayland hwdec=vaapi 100% cpu

### ISSUE THREAD

**Issue by tuncer** [mpv-player/mpv#2658]
vaapi is supported under native Wayland since 8aa8417aa35fd30990a1695380f22179848c6463, so I gave it a try. It worked, but it was using at least one cpu core completely. No idea what's happening, maybe inefficient copying of data. Is this expected?

package | version
-------- | --------
mpv | 0.14.0
libva | 1.6.2
wayland | 1.9.0
weston | 1.9.0

**Comment by wm4** [comment]
Post log with -v.

**Comment by tuncer** [comment]
It falls back to software decoding, but that doesn't explain how a small-res, low-bitrate recording of a video uses 100%. On a much older CPU with software-only decoding it doesn't even take 50% of one core for a high-bitrate 720p video, so I'd expect software-only decoding on a cpu (that supports libva under X (8%)) to maybe get up to 30% with hwdec=none and vo=wayland.

```
$ mpv -vo wayland video.file
...
[cplayer] Setting option 'hwdec' = 'vaapi' (flags = 4)
[cplayer] Setting option 'vo' = 'vaapi' (flags = 4)
[cplayer] Setting option 'vo' = 'wayland' (flags = 8)
[cplayer] Setting option 'v' = '' (flags = 8)
...
[vo/wayland/wayland] Seat "default" connected
[vo/wayland/wayland] output received:
[vo/wayland/wayland] 	vendor: SEC
[vo/wayland/wayland] 	model: unknown
[vo/wayland/wayland] 	w: 1366, h: 768
[vo/wayland/wayland] 	Hz: 60
[vd] Container reported FPS: 50.000000
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd] Opening video decoder lavc:h264
[vd] Probing 'vaapi'...
[vd] VO does not support requested hardware decoder, or loading it failed.
[vd] Using software decoding.
[vd] Detected 4 logical cores.
[vd] Requesting 5 threads for decoding.
...
[cplayer] VO: [wayland] 640x360 yuv420p
[cplayer] VO: Description: Wayland SHM video output
[vo/wayland] Window size: 640x360
[vo/wayland] Video source: 640x360 (640x360)
[vo/wayland] Video display: (0, 0) 640x360 -> (0, 0) 640x360
[vo/wayland] Video scale: 1.000000/1.000000
[vo/wayland] OSD borders: l=0 t=0 r=0 b=0
[vo/wayland] Video borders: l=0 t=0 r=0 b=0
...
```

Is there maybe some permission problem with Weston and libva, which doesn't exist under Xorg?

Has anyone succeeded with vo=wayland and hwdec=vaapi?

**Comment by Gusar321** [comment]
vo=wayland is a software output, like vo=x11, meaning colorspace conversion and scaling are done in software. It's not surprising that this is slow and that it doesn't work with hwdec=vaapi. Try vo=x11 in X, it should be roughly the same.

What you should be using is "--vo=opengl --hwdec=vaapi", that is what the commit you referenced implemented, vaapi/opengl interoperability under wayland. The most efficient method would be a wayland backend for vo=vaapi, this is possible but not implemented yet in mpv. But "--vo=opengl --hwdec=vaapi" should already work very well.

**Comment by tuncer** [comment]
Thanks, that works. vo=opengl is around the same overhead as Xorg with vo=opengl. I would welcome a Wayland backend for vo=vaapi.

Opened #2662, closing.
