### ISSUE TITLE
Dose *brew linkapps mpv* unuseful

### ISSUE THREAD

**Issue by TingYa** [mpv-player/mpv#2660]
I install mpv by 
`brew tap mpv-player/mpv`
`brew install mpv`
and at last i want to make it as an application in my Mac so i use `brew linkapps mpv` but it dosen't work.
Is there some solution for it ?

**Comment by pigoz** [comment]
The tap doesn't exist anymore. Update formulas (`brew update`), use `brew install mpv --with-bundle`, then `brew linkapps mpv`.

**Comment by Aisuko** [comment]
That command input to bash after `brew install mpv --with-bundle` which is `brew cask install mpv`. The fist command only install mpv player, the second one command was Movinf `mpv.app` to `Applications`.
[Link fo source](https://apple.stackexchange.com/questions/288689/installed-mpv-with-brew-but-nothing-in-applications)
