### ISSUE TITLE
nnedi3 results in bad artifacts if a crop filter is inserted during playback

### ISSUE THREAD

**Issue by quilloss** [mpv-player/mpv#2661]
Test file:
[Lenna.zip](https://github.com/mpv-player/mpv/files/76133/Lenna.zip)

Result after ```vf add crop=512:512:64:64```:
![lenna_00_00_10 359](https://cloud.githubusercontent.com/assets/8151080/12073252/5713d04a-b150-11e5-9d6b-23e0244b5300.png)

A crop filter inserted before playback is fine.

**Comment by wm4** [comment]
I suspect a FBO is not reallocated to the correct size after a reconfig, or something like this.

@bjin: any ideas?
