### ISSUE TITLE
Feature request: Wayland vo=vaapi support

### ISSUE THREAD

**Issue by tuncer** [mpv-player/mpv#2662]
vaapi supports Wayland, but this hasn't been implemented in mpv yet.

**Comment by wm4** [comment]
Hardware decoding is implemented when using vo_opengl.

**Comment by wm4** [comment]
PS: you need at least Mesa 11.

**Comment by tuncer** [comment]
What's the difference between vo=vaapi and vo=opengl?

**Comment by tuncer** [comment]
In #2658 @Gusar321 said `The most efficient method would be a wayland backend for vo=vaapi, this is possible but not implemented yet in mpv.`. That's why I opened this task.

**Comment by wm4** [comment]
vo_vaapi uses the really bad X11-specific API not even Intel cares about, and thus makes no sense to be implemented on Wayland. Maybe something could be done with vo_wayland, but I'm not interested in that.

**Comment by Gusar321** [comment]
vo_vaapi uses a fixed-function scaler, vo_opengl uses the GPU for scaling. opengl provides better quality (when using opengl-hq), but a fixed-function scaler is more efficient (use vaapi:scaling=hq for a better result, not as good as opengl-hq, but good enough for me).

vo_vaapi as currently implemented is indeed tied to X - vaPutSurface uses an x11 window as target - but it is possible to use use a wayland buffer as the target for vaPutSurface. See putsurface_wayland.c in the libva source: http://cgit.freedesktop.org/vaapi/libva/tree/test/putsurface/putsurface_wayland.c
vaGetSurfaceBufferWl seems to be the function that makes it possible. gstreamer-vaapi implements it too.

**Comment by wm4** [comment]
Yes, that might be suitable for vo_wayland, but I'm still extremely uninterested in this because 1. I dislike hardware decoding, 2. can't even use it for libmpv because it'd require extremely complex and platform specific integration between libmpv and the API users windowing code and toolkit.

Besides, I think fixed function video rendering stuff is backwards as hell. (Wayland staff still seems to believe in it though, well too bad, not my problem, now go away.)

**Comment by lkraav** [comment]
Whoever else is on a discovery road about Wayland vs hardware accelerated video on Intel, I can report that `hwdec=vaapi` makes a massive difference for CPU usage on Skylake i7. Same `mpv` video play goes from 50% usage -> 7%, measured on `htop`.

**Comment by tuncer** [comment]
I use `vo=opengl` under Wayland and it works well.

There have-been/are two issues, though:

1. There was a bug where under Weston, but not under wlc-based compositors, pausing mpv would make it use 100% cpu. I don't know if the issue was in mpv or mesa, but this seems to be fixed when using mpv from master.

2. There's an OpenGL error message on launch under Wayland (both libweston and libwlc compositors).

**Comment by wm4** [comment]
> [vo/opengl] after init_gl: OpenGL error INVALID_OPERATION, but it works and looks like it can be ignored.

We think it's a Mesa bug, but we aren't 100% certain. It's indeed safe to ignore for now.
