### ISSUE TITLE
Can we have mpv to load subtitles muxed in .mka files?

### ISSUE THREAD

**Issue by bodayw** [mpv-player/mpv#2663]
I got batch of anime release recently that the encoder decided to only include the Japanese audio in the main .mkv files and put the English audio and the subtitles in separate .mka files, for the reason that most of their audience are Chinese so they can choose not to download the additional .mka files if they don't need them. I do want the subtitles, but there is no way for me to let mpv load the subtitle track in the .mka file (the audio track works fine).

This is probably a corner case but I guess there is no harm to add this functionality?

**Comment by wm4** [comment]
It exists, use --sub-file.

**Comment by bodayw** [comment]
Thanks. Didn't know ``--sub-file`` can work like this. But...

1. In DOCS/man/option.rst, it probably should be ``--sub-file=<filename>`` instead of ``--sub-file=subtitlefile``.

2. I can only get this option to work in Terminal, with something like ``mpv ~/xyz/abc.mkv --sub-file=~/xyz/def.mka``, but if I put the option in ``mpv.conf`` it doesn't seem to work. I'm using the app bundle build for OS X.

3. Sorry if it was not clear, but what I want is to let mpv automatically detect subtitle tracks contained in external .mka files, not just audio tracks. Sure I can make it work by using ``--sub-file`` or manually extract the subtitle from the .mka files, but it would be nice to make it automatically happen, just as any other external audio and subtitle files. That being said, if there're reasons like "not actually trivial to implement" or "likely to break something else" or "sub tracks in .mka files is bad practice so we should support it by default", it's fine just leave it.

**Comment by zc62** [comment]
I wrote [a lua script](https://github.com/zc62/mpv-scripts/blob/master/autoload-sub-in-mka.lua) to make this automatic.
