### ISSUE TITLE
Unable to decode some HEVC videos by hardware decoding.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2664]
CPU: i5-4460
GPU: intel HD4600
System: elementary OS

Terminal information:
>libva info: VA-API version 0.36.0
>libva info: va_getDriverName() returns 0
>libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
>libva info: Found init function __vaDriverInit_0_36
>libva info: va_openDriver() returns 0
>AO: [pulse] 48000Hz stereo 2ch float
>[vo/vaapi/x11] Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.
>Using software decoding.
>VO: [vaapi] 3840x2160 yuv420p
>AV: 00:00:02 / 00:04:55 (0%) A-V:  0.254 Dropped: 39

Media information:
>General
Complete name                            : /home/laichiaheng/影片/4K-Changhong-Discover_the_true_Sichuan-HEVC@HD.Club.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42
File size                                : 1.65 GiB
Duration                                 : 4mn 55s
Overall bit rate mode                    : Variable
Overall bit rate                         : 47.9 Mbps
Encoded date                             : UTC 2014-12-25 12:55:49
Tagged date                              : UTC 2014-12-25 12:55:49
Writing application                      : TMPGEnc Video Mastering Works 6 Trial with Movie Plug-in Version. 6.0.0.8
Copyright                                : www.HD.Club.tw

>Video
ID                                       : 2
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L5@High
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 4mn 55s
Bit rate                                 : 47.4 Mbps
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.970 fps
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.191
Stream size                              : 1.63 GiB (99%)
Writing library                          : x265 unknown:[Windows][MSVC 1700][64 bit]
Encoding settings                        : wpp / ctu=64 / tu-intra-depth=1 / tu-inter-depth=1 / me=1 / subme=2 / merange=57 / no-rect / no-amp / max-merge=2 / temporal-mvp / no-early-skip / no-fast-cbf / rdpenalty=0 / no-tskip / tskip-fast / no-strong-intra-smoothing / no-lossless / no-cu-lossless / no-constrained-intra / no-fast-intra / open-gop / interlace=0 / keyint=250 / min-keyint=25 / scenecut=40 / rc-lookahead=20 / bframes=3 / bframe-bias=0 / b-adapt=2 / ref=5 / weightp / no-weightb / aq-mode=2 / aq-strength=1.00 / cbqpoffs=0 / crqpoffs=0 / rd=3 / psy-rd=0.00 / psy-rdoq=0.00 / signhide / lft / sao / no-sao-non-deblock / no-b-pyramid / cutree / rc=abr / bitrate=50000 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=51 / qpstep=4 / vbv-maxrate=60000 / vbv-bufsize=60000 / ipratio=1.40 / pbratio=1.30
Encoded date                             : UTC 2014-12-25 12:55:49
Tagged date                              : UTC 2014-12-25 12:55:49
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

>Audio
ID                                       : 1
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 4mn 55s
Bit rate mode                            : Variable
Bit rate                                 : 445 Kbps
Maximum bit rate                         : 576 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 15.7 MiB (1%)
Encoded date                             : UTC 2014-12-25 12:55:49
Tagged date                              : UTC 2014-12-25 12:55:49

**Comment by kevmitch** [comment]
Rerun mpv with ```--msg-level=vd=debug``` to get more information on why hwdec isn't working. 

It looks like the clip is 8bit so that shouldn't be a problem, but it may be that the particular profile is not supported by the hardware - are any other programs able to use hwdec on this clip?

It's also possible that you need a newer vaapi version than 0.36.0. I've got 0.38.0 here. 

Also according to #2631, 1a6f3c56ea6e7bf9928fc99469f8f5da4578f035 may be required for working hwdec with an old gcc version. What version of mpv are you using.

**Comment by Gusar321** [comment]
HD4600 is Haswell, there is no hardware hevc decoder on it. There's a hybrid (CPU+shaders) decoder for Windows, but not for Linux.

**Comment by laichiaheng** [comment]
@kevmitch 
I forgot to add the latest ppa

@Gusar321 
What! Doesn't intel update their driver for Linux?

**Comment by Gusar321** [comment]
@laichiaheng: I didn't check, but the Windows decoder is probably implemented in HLSL aka Direct3D. For Linux, they'd need to write a GLSL decoder, and they probably lack incentive for that. They wrote a hybrid VP9 decoder (not for Haswell though, for Broadwell and up), but only because it was sponsored by Google, likely for use in Chromebooks.

**Comment by laichiaheng** [comment]
Does the Broadwell support HEVC decoding for Linux?

**Comment by Gusar321** [comment]
> Doesn't the Broadwell support HEVC decoding for Linux?

Nope. Hybrid decoder in Windows (that even does 10bit, the Haswell hybrid decoder only does 8bit), nothing in Linux.

Braswell and Skylake have 8bit decoders (full fixed-function decoder) supported in Linux. Broxton and Kaby Lake will have 10bit decoders.

**Comment by wm4** [comment]
Yeah, pretty sure Broadwell doesn't support HEVC. On Windows, you can get hybrid decoding (appears to half the CPU usage or so), but that's it. Nothing we can do about.

**Comment by mgcrea** [comment]
@wm4 Any chance with newer Skylake processors on Linux?

**Comment by wm4** [comment]
Sure, this should work. But it won't handle 10 bit HEVC.
