### ISSUE TITLE
Video frozen with WASAPI

### ISSUE THREAD

**Issue by rossy** [mpv-player/mpv#2665]
With --ao=wasapi, the video freezes on the first frame. --ao=dsound works. Log here: https://gist.github.com/rossy/c6ded6a112a4cf368cdf

The first bad commit seems to be 5afa688. Ping @kevmitch.

**Comment by rossy** [comment]
Log with --msg-level=ao=trace: https://gist.github.com/rossy/bf606c1f011fb775fe79

**Comment by kevmitch** [comment]
does that fix it?

**Comment by rossy** [comment]
Yep, that works.
