### ISSUE TITLE
Playing H264 4K 59.94fps video with vo=opengl is laggy.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2668]
CPU: intel i5-4460
GPU: intel HD4600
System: elementary OS

Terminal information:
> (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
AO: [pulse] 48000Hz stereo 2ch float
[vo/opengl/x11] Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.
Using hardware decoding (vaapi).
VO: [opengl] 4096x2160 => 4096x2160 vaapi
AV: 00:01:31 / 00:37:59 (3%) A-V:  0.000 Dropped: 2610

Video information:
>General
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 7.85 GiB
Duration                                 : 37mn 59s
Overall bit rate mode                    : Variable
Overall bit rate                         : 29.6 Mbps
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00
Writing application                      : Lavf56.25.101

-
>Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L5.2
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 37mn 59s
Bit rate                                 : 29.4 Mbps
Width                                    : 4 096 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 1.896
Frame rate mode                          : Constant
Frame rate                               : 59.940 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.055
Stream size                              : 7.80 GiB (99%)
Writing library                          : x264 core 146 r2538 121396c
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x1:0x130 / me=hex / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=8 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=1 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=29400 / ratetol=1.0 / qcomp=0.60 / qpmin=3 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=58800 / vbv_bufsize=58800 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

-
>Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 37mn 59s
Bit rate mode                            : Variable
Bit rate                                 : 192 Kbps
Maximum bit rate                         : 58.8 Mbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 52.1 MiB (1%)
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

**Comment by wm4** [comment]
Your settings are probably too heavy?

**Comment by laichiaheng** [comment]
@wm4 
It is my setting:
>sub-auto=fuzzy
no-osd-bar
vo=opengl
hwdec=vaapi

**Comment by wm4** [comment]
Then I don't know. The CPU sounds like it's good enough to decode this in realtime.

If the problem is just because the video FPS is slightly higher than the display FPS, using ``--video-sync=display-resample`` might help (but of the problem is something else, it will make it worse).
