### ISSUE TITLE
sub-codepage stopped to work for ass subtitles

### ISSUE THREAD

**Issue by FeiWongReed** [mpv-player/mpv#2669]
Recently I have upgraded mpv from 0.11 to 0.14.

I have a lot of videos with ass subtitles encoded in cp1251. Previously I were using ```--sub-codepage=utf8:cp1251``` and everything worked fine. But for now such subtitles are rendered as trash.

For now I'm unable to override encoding even with ```--sub-codepage=cp1251```

I tried ```enca```, ```uchardet``` and ``guess`` options, even with modifiers but had no success.

mpv output sample: 
```
(+) Subs  --sid=1 'test.ass' (ssa) (external)
```

Same file converted to utf8 renders correctly.

**Comment by wm4** [comment]
>I have a lot of videos with ass subtitles encoded in cp1251.

Why? .ass is supposed to use utf-8.

**Comment by FeiWongReed** [comment]
But a lot of torrents contains incorrectly encoded files. And I can't easily recode them because I'm seeding. 

Its very common problem...

**Comment by FeiWongReed** [comment]
I think its due to problems of aegisub running on windows. Or, maybe, old aegisub versions. But its very common and its real pain in the ass when player is unable to recode.

**Comment by FeiWongReed** [comment]
Just a historic record. Patch for 0.14 looks like so:

```
--- demux/demux_lavf.c.orig	2016-01-04 14:32:51.001078480 +0000
+++ demux/demux_lavf.c	2016-01-04 14:34:00.786061366 +0000
@@ -613,8 +613,8 @@
             }
         }
 
-        if (matches_avinputformat_name(priv, "ass"))
-            sh_sub->is_utf8 = true;
+//        if (matches_avinputformat_name(priv, "ass"))
+//            sh_sub->is_utf8 = true;
 
         break;
     }
```

**Comment by Koshon** [comment]
..or use small command for all .ass files in directory: enconv -x UTF-8 *.ass
as an alternative solution...

**Comment by FeiWongReed** [comment]
Similar issue with the explanation: #2633
