### ISSUE TITLE
demux / stream file queries

### ISSUE THREAD

**Issue by sda89ha9** [mpv-player/mpv#2675]
OS: Windows 10
while playing a video, process monitor shows many QueryStandardInformationFile operations
bug or feature?
are the associated costs negligible?

process monitor logs
--demuxer=mkv: http://pastebin.com/ssTCBBDj
--demuxer=lavf : http://pastebin.com/EP9rSKMN

**Comment by wm4** [comment]
Probably harmless. We just use read() and sometimes lseek(). Microsoft's msvcrt.dll does these requests, so you have to ask them.

**Comment by rossy** [comment]
They seem to be from the stream_get_size calls in update_cache. Shouldn't be a problem. I'm fairly sure that syscall isn't expensive.

**Comment by rossy** [comment]
(Note: According to Process Monitor, these calls take an average of 5μs each on my machine. The longest call takes 24μs.)

**Comment by sda89ha9** [comment]
did some benchmarking for fun
playing video for 5 * 60 seconds
mpvinit.exe = stream_get_size moved from update_cache to demux_init_cache

file system activity
![mpvbench](https://cloud.githubusercontent.com/assets/15878392/12098013/9960c806-b31f-11e5-9de5-a75582493645.PNG)

**Comment by wm4** [comment]
Well, that seems not that insignificant.
