### ISSUE TITLE
Possible to use "real" release version for Info.plist?

### ISSUE THREAD

**Issue by timsutton** [mpv-player/mpv#2677]
`version.sh` always generates a version of the form "git-sha1" - I'd like to suggest that to better follow the guidelines of how versions can be represented in Info.plist files, that the "real" version (i.e. `0.14`) be used for the `CFBundleShortVersionString` key. The SHA-1 value could be instead used in either a separate project-specific key or the `CFBundleVersion` key, which is generally reserved to be a "machine-readable" version. `CFBundleShortVersionString` is what is used by the Finder whenever version info is displayed.

Besides the practical benefit of a user being able to more easily tell which version they have installed, there are some tools that are then better able to detect the installed versions - organizations that deploy mpv using a mass deployment or software management system, or if this project were ever to adopt Sparkle as an update framework using these version patterns make it easier for it to detect versions.

I'm not very familiar with this project (I'm a systems administrator that manages a variety of Macs in labs and studios for multimedia use), but if it's possible for `version.sh` to perhaps output the version in these different formats, perhaps the other parts of the app bundle assembly can make use of either version format wherever it's appropriate. If this is of interest I could work on a PR for this.

**Comment by pigoz** [comment]
@timsutton sure it's possible. Can we have the patchlevel also in the CFBundleShortVersionString? (i.e.: 0.14.0).

I think this should apply only when building a release tarball, is that correct? If I build from git master I should still get the SHA imho.

**Comment by pigoz** [comment]
I added the change. This will take effect next time the master branch is cut for the next release (0.15.0 – we don't do patchlevel releases anymore).

**Comment by timsutton** [comment]
Thanks! So you would create a VERSION file in the build root at the time of making a new release build?

And yes, putting the patch version number in the version string is fine.

**Comment by pigoz** [comment]
Yes, when releases are cut the release manager creates a branch and adds the VERSION file and updates the changelog.
