### ISSUE TITLE
Add gamepad support

### ISSUE THREAD

**Issue by pavelxdd** [mpv-player/mpv#2678]
mpv --input-test --force-window --idle
doesn't catch any gamepad sticks/buttons events, so I suppose it's not supported yet.
Would be useful when using Kodi + mpv as external player.

**Comment by wm4** [comment]
We don't normally add specific support for specific input devices. Instead, we expect the OS to generate proper events for it. For example, we removed LIRC and Joystick support for this reason. There are exceptions too; however, in case of gamepad none of the developers is likely to have this device, or to be interested in controlling mpv with it.

If you're on Linux, you should try to make this device generate X11 key events.

**Comment by pavelxdd** [comment]
Found a program to map gamepad keys to keyboard events on Windows.
Thanks for suggestion.
