### ISSUE TITLE
Drag and Drop DVD simply exits

### ISSUE THREAD

**Issue by redxii** [mpv-player/mpv#2681]
Windows 7 64-bit & 2015-12-11 64-bit build

I don't have any problems playing DVDs if I use the command-line or drag/dropping of other files. I tried seeing if spaces or special characters in the path were a problem but still didn't work after giving a simple name.
[mpv.txt](https://github.com/mpv-player/mpv/files/78691/mpv.txt)

**Comment by lachs0r** [comment]
Yeah, something’s wrong with libdvdread/libdvdnav on Windows. It cannot seem to open directories, period. Too bad.
