### ISSUE TITLE
How can I use SmoothMotion on Windows x64?

### ISSUE THREAD

**Issue by shavitush** [mpv-player/mpv#2682]
I recently found out that mpv-player has something called SmoothMotion which makes videos look smoother, similar to SVP; just better, and not using frame interpolations.

I tried Googling and only found Linux related results, which were to add this line to my mpv.conf file:
`vo=opengl:smoothmotion:smoothmotion-threshold=0.0`

I did so and video playback still looks really choppy, I can play the file with SVP and it looks smoother.. just with artifacts, that I heard SmoothMotion doesn't cause them.

Can anyone please assist me? Thanks :smile:

Edit: oh, can someone please label this issue as `question`? :D

**Comment by Cpuroast** [comment]
on recent version of mpv it's now:

vo=opengl:interpolation

also on very recent versions of mpv, as in 0.14 and up, you also need to use the following for interpolation to activate:

video-sync=display-* options, see:

https://mpv.io/manual/stable/#options-video-sync

**Comment by shavitush** [comment]
@Cpuroast thanks very much for the quick reply!

Is this a valid configuration?

    vo=opengl:interpolation
    video-sync=display-resample-desync

I downloaded mpv x64 from https://mpv.srsfckn.biz/ but the video still feels choppy.

**Comment by Cpuroast** [comment]
that's valid, although I don't think I'd use the desync option, I'd use either of the following ones:

display-resample
display-resample-vdrop
display-vdrop

You also have to define what choppy is.

**Comment by shavitush** [comment]
My definition for 'choppy' is that it feels as if the video play is still not smooth

**Comment by Cpuroast** [comment]
join the mpv irc channel, it will be more efficient.

https://webchat.freenode.net/
#mpv on irc.freenode.net

**Comment by shavitush** [comment]
Oh nevermind, I just switched my monitor to work at 60hz instead of 75hz and this issue solved :o

Thanks for helping!
