### ISSUE TITLE
question, maybe ass bug

### ISSUE THREAD

**Issue by latot** [mpv-player/mpv#2683]
Hi all, well i prefere first ask, i don't know if this is a mpv or libass bug, basically, i have an extern .ass, and the subtitles have 2 decimals like:

```
Dialogue: 0,0:00:08.20,0:00:09.20,white,,0000,0000,0000,,{\pos(323,335)}End
```
but if i use 3 decimals ex:
```
Dialogue: 0,0:00:08.200,0:00:09.200,white,,0000,0000,0000,,{\pos(323,335)}End
```
now seems random subtitles, only match the first time(start) but don't end correclty, with some subs only are showed 1 seg others more time.

Logs, https://gist.github.com/latot/39f7eb9f804271efeb09

Linux Gentoo 64

**Comment by wm4** [comment]
If anything, it's a ffmpeg bug. libass is not used to parse ass files anymore.

**Comment by wm4** [comment]
Turns out this actually works as designed. vsfilter (which defines the ASS format) also behaves this way. It can't be fixed.

**Comment by astiob** [comment]
To elaborate, the part after the decimal point is always measured in centiseconds, regardless of the number of figures provided. `0:00:08.200` means 8 seconds and 200 centiseconds, which is the same as 10 seconds. I’m not sure about old libass, but certainly both current libass and all versions of VSFilter behave this way.

**Comment by latot** [comment]
D:
in your experience what should be the maximun presicion i can use in subtitles?

**Comment by wm4** [comment]
You need to follow the libass syntax. If you want more precision, you probably have to use a different format, or maybe you can mux it as mkv and fudge the mkv timestamps.
