### ISSUE TITLE
osd lowercase inconsistency

### ISSUE THREAD

**Issue by pavelxdd** [mpv-player/mpv#2687]
osd-msg cycle pause - shows "pause: yes" and "pause: no"
osd-msg cycle mute - shows "Mute: yes" and "Mute: no"

Can the "pause" be changed to "Pause" for consistency?

**Comment by wm4** [comment]
No. The "mute" property has an explicit entry somewhere, which makes changes with "cycle" to the property show up on OSD by default using some custom string (which happens to be "Mute"). Adding a custom string for the "pause" property would also make changes to the property show up on the OSD by default, which is what we currently do not want.

But you can do something like ``cycle mute ; show_text "Pause: ${pause}"`` (untested, but should work)
