### ISSUE TITLE
Relicense filter_kernels.c to BSD

### ISSUE THREAD

**Issue by wm4** [mpv-player/mpv#2688]
Calling out to 3 other people who are in the commit log for the file filter_kernels.c:

@haasn 
@bjin 
@lucy

Do I get permission from you to relicense this file to LGPL and/or the new BSD license?

(The latter seems attractive because some parts of the file are already under new BSD. Would avoid having two licenses for it.)

**Comment by lucy** [comment]
I am OK with relicensing to LGPL or BSD, although the only code from me in the file is a pair of curly braces.

**Comment by bjin** [comment]
It's okay to relicense my past contributions to filter_kernels.c under terms of LGPL or BSD.

**Comment by haasn** [comment]
I'm OK with relicensing my past contributions to filter_kernels.c under terms of BSD.

Hopefully somebody “steals” it and actually uses lanczos instead of bilinear for once.

**Comment by wm4** [comment]
Thank you all.

**Comment by wm4** [comment]
I'm assuming @haasn is also ok with changing filter_kernels.h to the same license as filter_kernels.c.
