### ISSUE TITLE
mpv crashes xorg with -video-sync=display-resample when exiting or quiting fullscreen, Intel gpu

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#2698]
Seen here with an optimus laptop,  - 
Desktop: Unity 7.4.0  Distro: Ubuntu 16.04 xenial
Machine:   System: LENOVO product: 20217 v: Lenovo IdeaPad Y510P
           Mobo: LENOVO model: VIQY0Y1 v: 31900058STD
           Bios: LENOVO v: 74CN44WW(V3.05) date: 09/18/2013
CPU:       Quad core Intel Core i7-4700MQ (-HT-MCP-) speed/max: 2391/3400 MHz
Graphics:  Card-1: Intel 4th Gen Core Processor Integrated Graphics Controller
           Card-2: NVIDIA GK107M [GeForce GT 755M]
           Display Server: X.Org 1.17.3 drivers: intel (unloaded: fbdev,vesa) FAILED: nouveau
           Resolution: 1920x1080@59.91hz
           GLX Renderer: Mesa DRI Intel Haswell Mobile
           GLX Version: 3.0 Mesa 11.0.7

Does not occur when using nvidia via nvidia-prime, nor on same machine when using Mesa 10.x.x
Only occurs when exiting (file end) or quiting (q) in fullscreen, if in a window no issue.
Crash Title: Xorg crashed with SIGABRT in draw_current_msc()

Whether of any value,  no idea, Stacktrace, ect. here - 
http://paste.ubuntu.com/14442820/

**Comment by lachs0r** [comment]
And what makes you believe that this is an mpv bug rather than a driver bug?

**Comment by mc4man** [comment]
It is most likely a driver (xorg?) bug, only reported here as it may 
start affecting some mpv users.
As previously mentioned doesn't affect mesa 10.x & forgot  to add xorg 
1.17.1, affected install has 1.17.3, haven't anything atm using  newer 
xorg though may shortly.

**Comment by lachs0r** [comment]
Well the backtrace looks like Intel people screwed up something in SNA again.

**Comment by mc4man** [comment]
broke on the latest merge from debian in 16.04 (xserver-xorg-video-intel (2:2.99.917+git20151217-1~exp1) so will add to lp bug. Personally don't use intel anymore on optimus as have a hacky fix for the lack of vsync in nvidia-prime as proposed nvidia fixes aren't yet in X & maybe never in kernel..
diff from last working has a number of sna commmits - 
https://launchpadlibrarian.net/230338082/xserver-xorg-video-intel_2%3A2.99.917+git20151019-1~exp1ubuntu1_2%3A2.99.917+git20151217-1~exp1ubuntu1.diff.gz

**Comment by diegoviola** [comment]
This looks similar to this?

https://bugs.freedesktop.org/show_bug.cgi?id=93844

**Comment by lachs0r** [comment]
Use a recent kernel and the modesetting DDX (remove xserver-xorg-video-intel).

**Comment by diegoviola** [comment]
@mc4man can you provide steps to reproducing this?

Is it still an issue with xf86-video-intel git?

As @lachs0r mentioned, modesetting is a great alternative and you should use it if it solves your problems. That said, it would still be nice if you can file a bug report against xf86-video-intel if this is still a problem.

https://bugs.freedesktop.org/enter_bug.cgi?product=xorg&component=Driver/Intel

**Comment by diegoviola** [comment]
@mc4man Could you please provide the steps to reproduce this bug?

Is it still an issue with xf86-video-intel git?

As @lachs0r mentioned, modesetting is a great alternative and you should use it if it solves your problems. That said, it would still be nice if you can file a bug report against xf86-video-intel if this is still a problem.

https://bugs.freedesktop.org/enter_bug.cgi?product=xorg&component=Driver/Intel

**Comment by mc4man** [comment]
@diegoviola  - Seems no longer an issue, actually I guess since current on 16.04, i.e., 2.99.917+git20160325

**Comment by diegoviola** [comment]
@mc4man Good to know, thanks.
