### ISSUE TITLE
external subtitle

### ISSUE THREAD

**Issue by sda89ha9** [mpv-player/mpv#2700]
OS: windows 10

mpv without iconv displays no external subtitles unless --sub-codepage=utf8 is specified

sub-codepage=auto: http://pastebin.com/BcV5sBWB
sub-codepage=utf8: http://pastebin.com/g8FQKp96

**Comment by bodayw** [comment]
I have a similar issue here on OS X (likely to be the same one).

The latest OS X build (git-2a80680) won't show external ASS subtitles if it's not UTF-8 encoded (in my case they're UTF-16). They're still detected as you can see the tracks in the OSC.

Build git-de0523b still works normally.

**Comment by wm4** [comment]
Is this with or without iconv?

**Comment by bodayw** [comment]
@wm4 Sorry but I'm not familiar with this. I'm using OS X 10.11.2 and mpv builds from @ChrisK2 , though, if that helps. The description above is without ``sub-codepage=`` in mpv.conf. Set it to ``=utf8`` fixes this issue just as the OP said.

**Comment by ChrisK2** [comment]
``Checking for iconv                                                        : yes``

**Comment by wm4** [comment]
I hope I fixed this. Seemed to have to do with UTF-16 files?

**Comment by sda89ha9** [comment]
seems to work!


UTF-8 encoded:
[lavf] UTF-8 detected charset: 'utf-8'
[lavf] Using charset 'utf-8'.
[lavf] avformat_find_stream_info() finished after 144142 bytes.
[lavf] queuing seek to 0.000000
[lavf] execute seek (to 0.000000 flags 9)
[lavf] seek done

UTF-16 encoded:
[lavf] auto detected charset: 'utf-16le'
[lavf] Using charset 'utf-16le'.
[lavf] Using subtitle charset: utf-16le
[lavf] avformat_find_stream_info() finished after 288286 bytes.
[lavf] queuing seek to 0.000000
[lavf] execute seek (to 0.000000 flags 9)
[lavf] seek done
