### ISSUE TITLE
Implement a chroma-only prescale mode

### ISSUE THREAD

**Issue by oldoak1988** [mpv-player/mpv#2702]
It looks like the current behaviour of prescale is to simply double the resolution of the luma and chroma while not taking into account the dimensions of the video and the resolution of the display. This results in unneccesary computations for playback of 1080p content on a native 1080p display where only chroma upscaling is useful and where luma upscaling is quite a wasteful task.

Is it therefore possible to implement a shader based nnedi3 prescaler that only operates on chroma?

**Comment by bjin** [comment]
> This results in unneccesary computations for playback of 1080p content on a native 1080p display where only chroma upscaling is useful and where luma upscaling is quite a wasteful task.

You need to set `prescale-downscaling-threshold` to `1.5` to prevent this.

> Is it therefore possible to implement a shader based nnedi3 prescaler that only operates on chroma? 

Weights of NNEDI3 are trained with luma plane, so I really don't see a reason to use it for chroma. It's possible and relatively easy to add the support though.

**Comment by fhlfibh** [comment]
Setting `prescale-downscaling-threshold` to `1.5` (actually, to anything between 1.5 and 1.9) seems to disable NNEDI3 for 1080p video on a FHD monitor entirely, i.e. for both luma and chroma.

NNEDI3 only for chroma could work together with `cscale` option, and without excessive load for 1080p on FHD.

Not sure if I understand all that mechanics correctly, but having "NNEDI3 for chroma only" looks useful.

**Comment by lachs0r** [comment]
`prescale` has ben superseded by shader hooks.
