### ISSUE TITLE
documentation should mention that dvd subtitles can't be repositioned

### ISSUE THREAD

**Issue by archenemies** [mpv-player/mpv#2707]
I had to go to #mpv on Freenode to get help with the mpv man page. I would suggest editing it in the following way. These lines:

     r and t
            Move subtitles up/down.
                        
could say:

     r and t
            Move subtitles up/down. (text subtitles only - no DVD subtitles)

and these lines:

       --sub-use-margins
              Enables  placing  toptitles  and subtitles in black borders when
              they are available, if the subtitles are in a plain text  format
              (or ASS if --ass-style-override is set high enough).

could say:

       --sub-use-margins
              Enables  placing  toptitles  and subtitles in black borders when
              they are available, if the subtitles are in a plain text  format
              (or ASS if --ass-style-override is set high enough).

              NOTE: Won't work with DVD subtitles, which are images.

and these lines:

       --sub-pos=<0-100>
              Specify the position of subtitles on the screen.  The  value  is
              the vertical position of the subtitle in % of the screen height.

could say:

       --sub-pos=<0-100>
              Specify the position of subtitles on the screen.  The  value  is
              the vertical position of the subtitle in % of the screen height.

              NOTE:
                This option only works with text subtitles, not image-based
                subtitles (e.g. DVD subtitles).

I hope these edits make sense - I know a lot of people don't use DVDs anymore, but I think that many still do. I think it's difficult for a non-expert to understand why these key bindings and command-line options won't work for DVDs. In fact, perhaps even an expert on DVDs would assume that the image bitmap could be shifted up or down, and such a person might wonder why 'r' and 't' or --sub-pos don't produce an effect when viewing a DVD with mpv. If we amend the manual page to explain these shortcomings, it could save users from having to spend time debugging or searching on forums to find the answer.

Thank you!

**Comment by wm4** [comment]
I've added some generic text in the subtitle option section. Feel free to make a pull request for more extensive additions.

**Comment by archenemies** [comment]
Thank you.
