### ISSUE TITLE
subtitle: hang when playing kfx & very high memory usage

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#2715]
Not sure if this related with mpv's problem or libass
When playing certain kfx, mpv hangs and the memory usage shoot up to ~1.5gb in my pc. I can play the video with the ass subtitle fine in other player (mpc-be).

Here's the file:
http://a.pomf.cat/sgrfcv.mkv

**Comment by wm4** [comment]
Works perfectly fine here. Maybe you're using an old libass.

**Comment by shinchiro** [comment]
I used current git libass. Played on windows
When I read log about the sub, something caught me. Probably this the cause of my problem?

[sub/ass] Glyph bounding box too large: 41942786x41942786px
[sub/ass] Glyph bounding box too large: 41942786x41942786px

**Comment by wm4** [comment]
Certainly looks very fishy (and I don't get that). Slight chance it might be specific to the directwrite backend.

**Comment by shinchiro** [comment]
Here's another file which *completely* freeze my windows pc
http://a.pomf.cat/fersvc.mkv

**Comment by wm4** [comment]
Doesn't even drop a single frame here.

**Comment by wm4** [comment]
I can reproduce this problem on Windows with the DirectWrite and Fontconfig backends, but not on Linux.

**Comment by wm4** [comment]
Reported it as: https://github.com/libass/libass/issues/210

**Comment by shinchiro** [comment]
Does vlc also use libass to render the sub? Because these two files are playing fine in vlc

**Comment by wm4** [comment]
It does.
