### ISSUE TITLE
Substitles have scene bleed (just tested .ass subtitles)

### ISSUE THREAD

**Issue by 4re** [mpv-player/mpv#2716]
Starting from commit 04934e86dd154d1824253ba468c8f76eadc3076a subtitles randomly bleed, sometimes for up to two frames (maybe even more, but that's what I found).

As this does not happen with every line, it can take a bit to find one that does, but when you find it the bleeding is consistent.

All commits before that work OK and are consistent with Aegisub.

**Comment by wm4** [comment]
Do you have a sample?

**Comment by 4re** [comment]
The one at 0:00:12.78 bleeds in mpv.
[sample](https://www.dropbox.com/s/92vg35vo6pgpnak/sample.mkv?dl=0)

**Comment by wm4** [comment]
There is a gap between the two subtitles at this point. The earlier subtitle disappears when the scene changes. Then it takes a few frames until the next subtitle appears. mpv removes the gap by extending the previous subtitle. Works as designed, and just happens to fill the gap in the wrong direction. But usually, extending the earlier subtitle is saner. Use ``--sub-fix-timing=no`` if you don't like it.

**Comment by 4re** [comment]
OK, that's a solution for me, but the problem is that it's inconsistent with Aegisub, and most windows players, so subtitles that don't bleed anywhere bleed here. And I assure you there is no way to make that line not bleed, you can only achieve that by placing a subtitle just before starting at the first frame of the new scene, do you think that is correct? to not be able to make a subtitle not bleed?

**Comment by wm4** [comment]
>you can only achieve that by placing a subtitle just before starting at the first frame of the new scene, do you think that is correct? to not be able to make a subtitle not bleed?

Yes. Or add no gap.

I might also be willing to reconsider changing timing for ASS subtitles by default, but for now I see no reason.

**Comment by 4re** [comment]
Not always there will be a subtitle after the one that's gonna bleed, changing the default for that option would be nice.
