### ISSUE TITLE
hardware decoding did not work with opengl when fullscreen status is yes

### ISSUE THREAD

**Issue by SeaHOH** [mpv-player/mpv#2717]
win7 sp1 x64
Radeon HD6670
 mpv 0.14.0-git-e1993d5 x64

when using
```
vo=opengl
hwdec=auto
hwdec-preload=auto
```
hardware decoding works well **in window mode**.
```
[dxva2] Using fallback memcpy (slow)
Using hardware decoding (dxva2-copy).
```
hardware decoding did not work with the **next file** in list **in fullscreen mode**.
```
[dxva2] Using fallback memcpy (slow)
[dxva2] Failed to create Direct3D device
Could not open codec.
Using software decoding.
```
then, quit **back to window mode**, the hardware decoding **works again** with the **next file** in list.

when using
```
vo=direct3d_shaders
hwdec=auto
hwdec-preload=auto
```
everything is well.

**Comment by Cpuroast** [comment]
The most likely possibility is that the file that failed to use hardware decoding is not supported by the video card's decoding engine.

Compare it with the files that worked using something like Mediainfo:

https://mediaarea.net/en/MediaInfo/Download/Windows

**Comment by SeaHOH** [comment]
All tested files is supported hardware decoding,
**playing the next file in fullscreen mode** is point.

**Comment by Cpuroast** [comment]
Ok, I mis-understood, the issue, I get it now. 
Using vo=opengl and hardware decoding, the player errors out when in full screen and it switches to the next file in the playlist.
Where as when using vo=direct3d_shaders it does not.

As it says in the manual: Hardware decoding over OpenGL-interop is supported to some degree. Note that in this mode, some corner case might not be gracefully handled, and color space conversion and chroma upsampling is generally in the hand of the hardware decoder APIs.

It could be buggy or out of video date drivers. If your video card drivers are out of date, try updating them and see if it helps.

**Comment by SeaHOH** [comment]
My card is old, the drivers is out of date. I well try to update.
Thanks
But, is there anybody meet the same issue before? Even with the new drivers , cards and so on.

**Comment by shinchiro** [comment]
I didnt have that problem either using backend win or angle

**Comment by wm4** [comment]
This is a known problem. When OpenGL goes into fullscreen, some drivers enable exclusive fullscreen mode, and then no other D3D devices can be created. But existing D3D devices somehow continue to work. The hardware decoding code needs a D3D device every time decoding is reinitialized.

The `angle` and `dxinterop` backends shouldn't have this problem, but `win` can have it. vo_direct3d doesn't enter exclusive mode either.

**Comment by wm4** [comment]
PS: which means you should try with those backends.

**Comment by SeaHOH** [comment]
I have updated my card drivers, and checked the backend options. The `auto` `w32 ` and `dxinterop` could be use.
Hardware decoding works well with the `dxinterop` on fullscreen mode. But there is a nother problem: other application in ontop mode would be cover the fullscreen video. The option `es=yes` is not help.

**Comment by SeaHOH** [comment]
Out back window mode then enter fullscreen mode again, those ontop widgets could not be see even with `es=no` option. The reenter fullscreen mode must be need, this is nettlesome.
How does the `es` option working? And is there other ways to solve? I do not like to ues ontop feature when fullscreen mode is on, it is not reliable when application do not respond.

**Comment by SeaHOH** [comment]
I think out a way, use lua scripts. The hardware decoding can work without `dxinterop` backend.
```lua
mp.register_event("end-file",  function()
    local fs = mp.get_property_native("fullscreen") -- Read fullscreen status.
    mp.set_property_native("fullscreen", false) -- Set window mode.
    mp.add_timeout(0.1, function() -- Do not set a shorter time, otherwise hardware decoding may not work.
        mp.set_property_native("fullscreen", fs) -- Restore fullscreen status .
    end)
end)
```

**Comment by kevmitch** [comment]
> But there is a nother problem: other application (e.g. some useful widgets) in ontop mode would be cover the fullscreen video, just like when use vo=direct3d_shaders option. The option es=yes is not help.

If I understand you correctly, this is a feature rather than a bug. ontop is used for things like system-wide volume / brightness osd or the alt-tab switcher which are supposed to cover the video while active. An application should not put itself in such a state if it is not actually meant to be "on top" of everything else.

**Comment by SeaHOH** [comment]
When mpv using `vo=opengl:backend=win` (mine is w32) and the ontop states is off, fullscreen status is on, other ontoped application is stay over mpv, but you can not see them.
