### ISSUE TITLE
[Win10] Windows Defender is flagging mpv.exe as malware

### ISSUE THREAD

**Issue by qyot27** [mpv-player/mpv#2720]
This started happening a few hours ago, after its definitions updated.  States that mpv.exe is really a trojan (Trojan:Win32/Dorv.C!rfn) and then proceeds to remove it.

Obviously, yes, false positive, but the problem is that Windows Defender cannot be turned off in Win10 (or rather, it can temporarily, but it tells you it'll turn Defender back on again if you leave it off for too long), and despite my attempting to place mpv.exe and the directory it resides in in the exceptions list, that did absolutely nothing to stop Defender from freaking out.

Also, I have little reason to believe Microsoft would actually resolve this on their end, which aside from the heads up is why I'm reporting it here.

Windows 10 Home 32-bit, builds of mpv from Jan 1 and HEAD as of this time of writing.  At first I thought it might have to do with that HLS issue recently found in FFmpeg, but the build from tonight used the git HEAD for it too, where that issue is fixed (plus, neither of the corresponding builds of FFmpeg from Jan 1 or tonight tripped up Defender at all, only mpv.exe did).

**Comment by avih** [comment]
Can't reproduce with my own build (latest mpv master and ffmpeg master built using MXE - http://a.pomf.cat/nknztv.7z from this branch: https://github.com/avih/mpv/tree/js-duk )  on windows 7, 8.1 or 10 with latest windows defender definitions.

How do you build mpv?

**Comment by czarkoff** [comment]
@qyot27 Until the problem is solved for you, you can work it around by wrapping `mpv.exe` in 7-zip.

**Comment by lachs0r** [comment]
Do my builds trigger this as well? Years ago Avira freaked out over the 64-bit executable but not the 32-bit one. Also, does it happen if you build FFmpeg and mpv with only the bare minimum of compile-time options and 3rd party libraries enabled? If not, maybe you could figure out which one is causing the false positive?

**Comment by ismail** [comment]
@lachs0r Just tested your builds (both 32bit and 64bit) and they are fine (This is on Win10 x64, definitions as of today). Even manually scanned to be sure.

**Comment by qyot27** [comment]
@avih
https://github.com/qyot27/mpv/blob/extra-new/DOCS/crosscompile-mingw-tedious.txt

@lachs0r
It doesn't seem to.  I'll check using the minimalistic build type I use for FFMS2 and see if that's ok.  Judging from the description of the Trojan, if one of the external libs is causing it, I'd assume it'd be one of the protocol handling ones (GnuTLS is the one I'm worried about here).

**Comment by wm4** [comment]
>I'd assume it'd be one of the protocol handling ones (GnuTLS is the one I'm worried about here).

You don't need GnuTLS. FFmpeg has support for the native Windows TLS APIs.

**Comment by avih** [comment]
FWIW, my ffmpeg is built with GnuTLS 3.4.8 .

**Comment by qyot27** [comment]
Wasn't GnuTLS (or openssl) necessary at some point for RTMPE support if rtmpdump wasn't enabled?  I remember some of the RTMP(E) support in FFmpeg was improved, but I didn't know if all of the reasons for rtmpdump (or corresponding TLS library) had been eclipsed by it already.

**Comment by wiiaboo** [comment]
Not anymore. SChannel with --enable-gmp or --enable-gcrypt enables rtmp(t)e support in FFmpeg without need for librtmp.

**Comment by qyot27** [comment]
Ah, good.  Then hopefully that is what's causing it, since that'd be easily fixable.

**Comment by qyot27** [comment]
Unfortunately, even the minimal build of ffmpeg and mpv tripped it too.  I've also found other references to false positives with this supposed Trojan's signature, including one for MS Office itself.

**Comment by wm4** [comment]
>including one for MS Office itself.

Then at least there's a chance that MS fixes their crap.
