### ISSUE TITLE
[OSX] Battery life issue

### ISSUE THREAD

**Issue by Tapsibaba** [mpv-player/mpv#2725]
Hello,

I create an issue because I did researches but I could not find anything to help me.
I use mpv because I love it, it works well and I don't have issues to read video files but I've got a battery life issue. I don't know if it is related to the configuration or something else...

2.7GHz dual-core Intel Core i5
Turbo Boost up to 3.1GHz
8GB 1866MHz LPDDR3 memory
Intel Iris Graphics 6100

(This is the config of my Mac, a retina Macbook Pro 13")
I'm running OS X El Capitan 10.11.2! ;)

Mpv was compiled using the terminal and using this:
brew install --HEAD --with-bundle --with-bluray-support --with-libdvdread --with-little-cms2 --with-lua --with-bundle mpv

My config file (really simple config file):
autofit-larger=80%x80%
hwdec=videotoolbox
vo=opengl-hq

(I used to have a longer line on the vo thing but well, it is not important because it did not change the energy consumption)

I played two episodes of a TV show with those characteristics: 
Taille du fichier                        : 815 Mio
Durée                                    : 46mn 5s
Débit global moyen                       : 2 472 Kbps

Vidéo
Identifiant du codec/Suggestion          : XviD
Débit                                    : 2 300 Kbps
Largeur                                  : 1 280 pixels
Hauteur                                  : 720 pixels
Format à l'écran                         : 16/9
Images par seconde                       : 23,976 Im/s
Bibliothèque utilisée                    : XviD 64

Audio
Identifiant du codec/Suggestion          : MP3
Débit                                    : 160 Kbps
Canaux                                   : 2 canaux
Echantillonnage                          : 48,0 KHz

How I played the files:
Macbook plugged on a TV (HDMI).
The TV was displaying a 1080p signal. 
I lowered the screen brightness to the minimum.
I played the first episode, the Macbook was at 21% of battery. I reached 5% of battery after the first episode. I had to use the AC Adapter to watch the second episode. 
The average energetic impact is very very high... 216,61 after the two episodes!!
It's way higher than Safari for example. (42,57 atm)
And it's even higher than VLC...

Can someone help me to optimize my battery life using MPV? I love this soft guys, it's really a great work but I think that I may have a problem with it but as it is often the case, the problem may be between the Mac and the chair... lol

Anyways, I'm really sorry if I'm explaining my issue at the wrong place, if that's the problem please tell me where I should post it.

Thank you for reading! :)

**Comment by ChrisK2** [comment]
``vo=opengl-hq``
High Quality (``hq``) obviously comes at a price.

**Comment by pigoz** [comment]
1) Don't use `vo=opengl-hq`.
2) Watch h264 files so they can be decoded with videotoolbox (ad opposed to xvid).

**Comment by wm4** [comment]
`osc=no` and `terminal=no` might help a little bit too, but maybe not much.

**Comment by pigoz** [comment]
I assume this can be closed

**Comment by Hrxn** [comment]
Maybe also `ytdl=no`, since this is also enabled by default. But it won't change much, I'd guess..

**Comment by kevmitch** [comment]
If you want to keep some of the quality of opengl-hq, you can disable debanding, which can be pretty energy consuming compared to the other stuff.

Looks like your content is not playing at native resolution, but for such cases ```scaler-resizes-only``` should save some power with no loss in quality.

So something like 

    vo=opengl-hq:deband=no:scaler-resizes-only
