### ISSUE TITLE
-vo=drm, nouveaufb and VGA compatible controller: NVIDIA Corporation GF119 [GeForce GT 520] (rev a1)

### ISSUE THREAD

**Issue by saahriktu** [mpv-player/mpv#2728]
I got this error:
[vo/drm] Cannot set CRTC for connector 32: No such file or directory
Error opening/initializing the selected video_out (-vo) device.

In strace log:
set_robust_list(0x7f36c9f599e0, 24)     = 0
prctl(PR_SET_NAME, "mpv/vo\0\0\0\0\0\0\0\0\0\0") = 0
pipe([12, 13])                          = 0
fcntl(12, F_GETFD)                      = 0
fcntl(12, F_SETFD, FD_CLOEXEC)          = 0
fcntl(13, F_GETFD)                      = 0
fcntl(13, F_SETFD, FD_CLOEXEC)          = 0
open("/dev/tty", O_RDWR|O_CLOEXEC)      = 14
rt_sigaction(SIGUSR1, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGUSR2, NULL, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGUSR1, {0x49aad0, [], SA_RESTORER|SA_RESTART, 0x7f36cfcd8cf0}, NULL, 8) = 0
rt_sigaction(SIGUSR2, {0x49aad0, [], SA_RESTORER|SA_RESTART, 0x7f36cfcd8cf0}, NULL, 8) = 0
ioctl(14, VIDIOC_RESERVED or VT_GETMODE, 0x7f36c9f58ac0) = 0
ioctl(14, VT_SETMODE, 0x7f36c9f58ac0)   = 0
open("/dev/dri/card0", O_RDWR|O_CLOEXEC) = 15
ioctl(15, DRM_IOCTL_MODE_GETRESOURCES, 0x7f36c9f58a70) = 0
ioctl(15, DRM_IOCTL_MODE_GETRESOURCES, 0x7f36c9f58a70) = 0
ioctl(15, DRM_IOCTL_MODE_GETCONNECTOR, 0x7f36c9f58a70) = 0
ioctl(15, DRM_IOCTL_MODE_GETCONNECTOR, 0x7f36c9f58a70) = 0
ioctl(15, DRM_IOCTL_MODE_GETCONNECTOR, 0x7f36c9f58a70) = 0
ioctl(15, DRM_IOCTL_MODE_GETCONNECTOR, 0x7f36c9f58a70) = 0
ioctl(15, DRM_IOCTL_MODE_GETENCODER, 0x7f36c9f58ac0) = 0
ioctl(15, DRM_IOCTL_MODE_CREATE_DUMB, 0x7f36c9f58c40) = 0
ioctl(15, DRM_IOCTL_MODE_ADDFB, 0x7f36c9f58be0) = 0
ioctl(15, DRM_IOCTL_MODE_MAP_DUMB, 0x7f36c9f58c30) = 0
mmap(NULL, 8294400, PROT_READ|PROT_WRITE, MAP_SHARED, 15, 0x10082b000) = 0x7f36c8f70000
ioctl(15, DRM_IOCTL_MODE_CREATE_DUMB, 0x7f36c9f58c40) = 0
ioctl(15, DRM_IOCTL_MODE_ADDFB, 0x7f36c9f58be0) = 0
ioctl(15, DRM_IOCTL_MODE_MAP_DUMB, 0x7f36c9f58c30) = 0
mmap(NULL, 8294400, PROT_READ|PROT_WRITE, MAP_SHARED, 15, 0x10102b000) = 0x7f36c8787000
ioctl(15, DRM_IOCTL_GET_CAP, 0x7f36c9f58c00) = 0
ioctl(15, DRM_IOCTL_MODE_GETCRTC, 0x7f36c9f58b90) = -1 ENOENT (No such file or directory)
ioctl(15, DRM_IOCTL_MODE_SETCRTC, 0x7f36c9f58b70) = -1 ENOENT (No such file or directory)
write(1, "\33[0;31m[vo/drm] Cannot set CRTC "..., 76) = 76
write(1, "\33[0m", 4)
munmap(0x7f36c8f70000, 8294400)         = 0
ioctl(15, DRM_IOCTL_MODE_RMFB, 0x7f36c9f58bcc) = 0
ioctl(15, DRM_IOCTL_MODE_DESTROY_DUMB, 0x7f36c9f58be0) = 0
munmap(0x7f36c8787000, 8294400)         = 0
ioctl(15, DRM_IOCTL_MODE_RMFB, 0x7f36c9f58bcc) = 0
ioctl(15, DRM_IOCTL_MODE_DESTROY_DUMB, 0x7f36c9f58be0) = 0
close(15)                               = 0
rt_sigaction(SIGUSR1, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x7f36cfcd8cf0}, NULL, 8) = 0
rt_sigaction(SIGUSR2, {SIG_DFL, [], SA_RESTORER|SA_RESTART, 0x7f36cfcd8cf0}, NULL, 8) = 0
close(14)                               = 0
close(12)                               = 0
close(13)                               = 0
futex(0x7036c4, FUTEX_CMP_REQUEUE_PRIVATE, 1, 2147483647, 0x703700, 2) = 1
madvise(0x7f36c9759000, 8368128, MADV_DONTNEED) = 0
exit(0)                                 = ?
+++ exited with 0 +++

libdrm tests passed. Videocard - VGA compatible controller: NVIDIA Corporation GF119 [GeForce GT 520] (rev a1).

> cat /proc/fb
0 nouveaufb
> ls /dev/dri/
card0  controlD64  renderD128

For example result of "modeprint nouveau":
Starting test
Resources

count_connectors : 3
count_encoders   : 4
count_crtcs      : 2
count_fbs        : 0

Connector: DVI-I-1
        id             : 32
        encoder id     : 34
        conn           : connected
        size           : 530x300 (mm)
        count_modes    : 20
        count_props    : 11
        props          : 1 2 20 23 24 25 26 27 18 21 22
        count_encoders : 2
        encoders       : 33 34
Mode: "1920x1080" 1920x1080 60
Mode: "1680x1050" 1680x1050 60
Mode: "1280x1024" 1280x1024 75
Mode: "1280x1024" 1280x1024 60
Mode: "1440x900" 1440x900 60
Mode: "1280x960" 1280x960 60
Mode: "1280x720" 1280x720 60
Mode: "1024x768" 1024x768 75
Mode: "1024x768" 1024x768 70
Mode: "1024x768" 1024x768 60
Mode: "832x624" 832x624 75
Mode: "800x600" 800x600 75
Mode: "800x600" 800x600 72
Mode: "800x600" 800x600 60
Mode: "800x600" 800x600 56
Mode: "640x480" 640x480 75
Mode: "640x480" 640x480 73
Mode: "640x480" 640x480 67
Mode: "640x480" 640x480 60
Mode: "720x400" 720x400 70
Connector: HDMI-A-1
        id             : 35
        encoder id     : 0
        conn           : disconnected
        size           : 0x0 (mm)
        count_modes    : 0
        count_props    : 10
        props          : 1 2 23 24 25 26 27 18 21 22
        count_encoders : 1
        encoders       : 36
Connector: VGA-1
        id             : 37
        encoder id     : 0
        conn           : disconnected
        size           : 0x0 (mm)
        count_modes    : 0
        count_props    : 5
        props          : 1 2 26 27 18
        count_encoders : 1
        encoders       : 38

Encoder
        id     :33
        crtc_id   :0
        type   :1
        possible_crtcs  :0x3
        possible_clones :0x0
Encoder
        id     :34
        crtc_id   :29
        type   :2
        possible_crtcs  :0x3
        possible_clones :0x0
Encoder
        id     :36
        crtc_id   :0
        type   :2
        possible_crtcs  :0x3
        possible_clones :0x0
Encoder
        id     :38
        crtc_id   :0
        type   :1
        possible_crtcs  :0x3
        possible_clones :0x0

Crtc
        id             : 29
        x              : 0
        y              : 0
        width          : 1920
        height         : 1080
        mode           : 0x203533c
        gamma size     : 256
Crtc
        id             : 31
        x              : 0
        y              : 0
        width          : 0
        height         : 0
        mode           : 0x203533c
        gamma size     : 256

Ok

**Comment by wm4** [comment]
It's not support for nvidia GPUs, because the drivers don't support the API.

**Comment by wm4** [comment]
Wait a moment, you're using nouveau. I'd expect they're supporting this.

**Comment by wm4** [comment]
@rr-: ping

**Comment by rr-** [comment]
@saahriktu have you tried playing with `--connector`, `--devpath` and `--mode` options?

**Comment by saahriktu** [comment]
Yes.

**Comment by rr-** [comment]
What if you try to watch video on an auxillary screen and set the above options accordingly?

**Comment by saahriktu** [comment]
Yes, it's output video to second monitor (as connector=1), but don't works with first.

**Comment by rr-** [comment]
@saahriktu could you test if [this change](https://github.com/rr-/mpv/commit/471636a98ee5ab76bbc6b78cdc0e5719b70bc70f) fixes the problem? Thanks. (On my end it makes no difference - these values end up being the same, but this might be just a coincidence.)

**Comment by saahriktu** [comment]
Yes, it works. Problem is being solved now.

**Comment by wm4** [comment]
Fix is in master now.
