### ISSUE TITLE
[BISECT][REGRESSION] mpv --term-playing-msg='INFO_VIDEO_CODEC=${=video-codec}' results in segfault

### ISSUE THREAD

**Issue by Coacher** [mpv-player/mpv#2729]
Hello.

The problem is described in the subject. This problem also makes smplayer (15.11.0, 16.1.0) unusable with mpv, but please note that this is not smplayer-specific.

This problem is present in 0.15.0, but not in 0.14.0. Thus it is a regression.

The relevant info follows.

mpv -v: https://bpaste.net/show/5e701d29ee06
Example file: http://filebin.ca/2TuatfMZ1x4Y (source: https://www.youtube.com/watch?v=m-KdDvwrDFA&index=1&list=PLchGsFtT6nrSwPAve39lPdeKr1OWWAk5j obtained with youtube-dl -x)
git bisect log: https://bpaste.net/show/b5f46246b71c

Update: problematic commit: 4195a345a51e52337bc972aacbce0fd6e88ebb5d

**Comment by Coacher** [comment]
Error log: https://bpaste.net/show/ce50207d7636

**Comment by Coacher** [comment]
gdb stack trace with mpv built from master at the problematic commit: https://bpaste.net/show/4dcfc0fd0f82

**Comment by Coacher** [comment]
Please fix.

**Comment by wm4** [comment]
>Please fix.

What if I say no next time?

**Comment by Coacher** [comment]
> What if I say no next time?

Than you will make me and all Gentoo users unhappy because I will have to stick to some old version that works.

For now, thank you for the fix :)
