### ISSUE TITLE
Attached fonts not used with external subtitles file

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#2731]
Hi,

Since version 0.15, subtitles are not rendered with the font specified in the subtitles script if the script is external (separate ass file) and instead the default font is used. If the script is muxed in the mkv, there is no problem. 
A message like `[sub/ass] fontselect: Using default font family: (LTFinnegan Medium, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, DejaVuSans` is displayed if the subtitles are external.

**Comment by wiiaboo** [comment]
Is the font installed in your system?

**Comment by occivink** [comment]
No, but this hasn't been a problem with past versions.

**Comment by occivink** [comment]
A quick bisect indicates that this was introduced in this commit:
https://github.com/mpv-player/mpv/commit/8d4a179c144cb3e36762b2c3cef55d1d3bb9f951

**Comment by wm4** [comment]
Are you talking about .ass files with embedded fonts (base64 encoded or so), or something else?

**Comment by occivink** [comment]
No, the fonts are attached in the mkv, and referenced by the external ass. I can whip up a quick example if you want.

**Comment by occivink** [comment]
I'm not sure if that's a proper host, but here goes: 
subtitle: https://d.maxfile.ro/sddezxcopk.ass
video: https://d.maxfile.ro/tjoekqjkrz.mkv
Before that commit, `mpv tjoekqjkrz.mkv --sub-file sddezxcopk.ass` uses the font embedded in the mkv, after it uses a default font.

**Comment by wm4** [comment]
OK, I understand. I'm not interested in changing this. You can remux the fonts and the .ass file to .mks, then it should work.

**Comment by occivink** [comment]
That's a shame. I don't want to mux the subtitles because I want to be able to modify them easily. 
Is there a way to specify an additionnal directory in which mpv should look for fonts? I'd rather not pollute my system fonts with all sorts of garbage fonts.

**Comment by wiiaboo** [comment]
You can create a "fonts" directory in the conf dir or mpv's dir and put the fonts there, I think.

**Comment by occivink** [comment]
Thanks this works, but it doesn't scale if all fonts in there are loaded every time mpv. I guess the closest I can get to the previous behavior is some scripts to easily demux and remux the subtitles.
