### ISSUE TITLE
Subtitles not being read over the network

### ISSUE THREAD

**Issue by CrisBRM** [mpv-player/mpv#2732]
Steps to reproduce:
1. Access samba share normally (eg: smb://wirelessspace/OpenShare/series/the.blacklist/)
2. Open file
3. Corresponding subtitle will not load (eg: the.blacklist.s03e01.hdtv.x264-killers.mp4 and the.blacklist.s03e01.hdtv.x264-killers.srt)

It works if I copy them and play it locally.

Git version, vanilla conf for testing purposes, 4.2.8 kernel, gentoo, ffmpeg 2.8.5.

Edit: This might have to do with the fact ffmpeg was not built with the samba flag...
Edit2: Nope. Compiled ffmpeg and mpv with the proper flags and still nothing.

**Comment by lachs0r** [comment]
Mount the share (mount -t cifs etc. etc.).

**Comment by wm4** [comment]
Log?

**Comment by CrisBRM** [comment]
http://pastebin.com/raw/q5Ux853V

**Comment by wm4** [comment]
Oh, now I get it.

No, we don't do this automatically. You either have to pass the subtitle explicitly with `--sub-file`, or do what lachs0r said.

Even if we had code to list Samba dirs, we wouldn't use it, as we'd avoid doing a potentially slow operation like listing dirs over network. But if it's mounted into the filesystem, mpv's dir listing code will assume it's local.
