### ISSUE TITLE
I can't play the videos with hardware decoding when using Nouveau driver.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2734]
> (+) Video --vid=1 (wmv3)
 (+) Audio --aid=1 --alang=jpn (wmav2)
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nouveau_drv_video.so
libva info: va_openDriver() returns -1
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/nouveau_drv_video.so
libva info: va_openDriver() returns -1
VO does not support requested hardware decoder, or loading it failed.
Using software decoding.
VO: [opengl] 1920x1080 yuv420p
AO: [pulse] 48000Hz stereo 2ch float
AV: 00:00:13 / 00:09:18 (2%) A-V: -0.003 Dropped: 16

**Comment by lachs0r** [comment]
1) Use VDPAU
2) Check this site for whether your GPU is supported: http://nouveau.freedesktop.org/wiki/VideoAcceleration/

**Comment by lachs0r** [comment]
Also, WMV3 is a variant of VC-1. Make sure your decoder supports that.

**Comment by laichiaheng** [comment]
@lachs0r 
> (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
Failed to open VDPAU backend libvdpau_nouveau.so: cannot open shared object file: No such file or directory
Failed to open VDPAU backend libvdpau_nouveau.so: cannot open shared object file: No such file or directory
VO does not support requested hardware decoder, or loading it failed.
AO: [pulse] 44100Hz stereo 2ch float
Using software decoding.
VO: [opengl] 1920x1080 yuv420p
AV: 00:00:02 / 01:01:35 (0%) A-V:  0.000

It is still using software decoding.

my GPU is GT650M

**Comment by lachs0r** [comment]
How about installing the nouveau state tracker for VDPAU? Check for a package called libvdpau_nouveau or mesa-vdpau-drivers.

**Comment by laichiaheng** [comment]
@lachs0r Can't find the first one, the result of the second one is here:
>libcheese-gtk23 : 相依關係: libcogl15 (>= 1.15.8) 但它卻將不會被安裝
 libcheese7 : 相依關係: libclutter-gst-2.0-0 (>= 0.10.0) 但它卻將不會被安裝
              相依關係: gstreamer1.0-clutter 但它卻將不會被安裝
 libclutter-1.0-0 : 相依關係: libcogl-pango15 (>= 1.15.8) 但它卻將不會被安裝
                    相依關係: libcogl15 (>= 1.15.8) 但它卻將不會被安裝
 libclutter-gtk-1.0-0 : 相依關係: libcogl15 (>= 1.15.8) 但它卻將不會被安裝
 libgl1-mesa-dri-lts-vivid : 衝突: libgl1-mesa-dri

**Comment by lachs0r** [comment]
Well, sorry, but I can’t help you with your broken distro. Also, you’re going to need proprietary firmware for your GPU to support hardware decoding anyway (as mentioned on the page I linked earlier). Honestly, you’re better off just installing proprietary drivers.

**Comment by laichiaheng** [comment]
@lachs0r Which distro do you use? I'm using elementary OS which is based on Ubuntu 14.04LTS

**Comment by lachs0r** [comment]
openSUSE, but it’s not going to be a whole lot easier with that. You still need to install the firmware manually if you insist on using nouveau, as far as I know.

**Comment by laichiaheng** [comment]
@lachs0r So... you have no problem with decoding VC-1 and H264 video in openSUSE, right?

**Comment by lachs0r** [comment]
I’m not using nouveau.

**Comment by mc4man** [comment]
1. If installing mesa libs then you have to install whichever version matches, ex. 14.04.3 uses lts-vivid so, 
mesa-vdpau-drivers-lts-vivid. That .so would then be found in /usr/lib/x86_64-linux-gnu/vdpau or i386 equivalent.
You should probably install synaptic & acquaint yourself with what you have & can have
2. You have an optimus card so your purported settings should be using i965_drv_video.so. Installing the above package is likely a waste of time. (and it's not even clear that m cards are supported for nouveau hwdec
3. If you don't want to use Intel gpu hwdec then install the nvidia drivers & nvidia-prime, ect.

**Comment by laichiaheng** [comment]
@mc4man My laptop doesn't support the optimus, so there is Nvidia card only.
