### ISSUE TITLE
No windows with opengl-hq in windows 10 x64...

### ISSUE THREAD

**Issue by man0000** [mpv-player/mpv#2736]
Hi,

I don't know if I am doing something wrong. I am in Windows 10 x64 (Intel HD2000).

With vo=opengl-hq in the mpv.conf, I don't have window but mpv.exe is running in processes and have to kill it. 
With vo=opengl the window appears as expected.

Besides, if d3dcompiler_43.dll is absent from the folder, I have window and sound but not image. Changelog points that is needed for 7 or older. ¿?...

This behavior is with the last release of yesterday [0.15.0-git-2a8bbee]. With my previous one [0.12.0-git-5b7d0fb] and the same conf file, I don't have any issue.

Any idea???.

THANKS...

**Comment by Hrxn** [comment]
Uhm, d3dcompiler_43.dll? Absent from which folder?

You didn't get it with mpv. I don't have any .dll files in my folder, and I'm on Windows 10 x64 too.

Did you try to run dxdiag?

http://windows.microsoft.com/en-us/windows-10/open-and-run-dxdiagexe

**Comment by man0000** [comment]
If you download the last build of mpv [2016-01-18|64-bit] from the 'Windows builds by lachs0r' page from mpv.io [https://mpv.srsfckn.biz/], you have the dll inside the zip besides manual.pdf, mpv.com and mpv.exe.

If your zip doesn't have the dll, please tell me from where did you downloaded it.

**Comment by Hrxn** [comment]
Oh, right, new builds. Since yesterday..

I haven't updated to the latest version, I was referring to the build from 2015-12-11.

So you can rule out issues with the GPU driver?

**Comment by man0000** [comment]
With 2015-12-11 I had an issue with horizontal lines in the image when I go fullscreen so revert to the one without the issue.

I have just tried the new build and have these issues. Little I have tested. Only want to know if they were my fault or issues of the build. With my actual build, I don't suffer them.

Any help is welcome. THANKS...

**Comment by shinchiro** [comment]
Do you mean screen tearing?

Also d3dcompiler_43.dll exist for a reason. Why people want to delete it?

**Comment by man0000** [comment]
In the previous build, when in fullscreen I had horizontal lines appearing sometimes in the image, not when windowed.

I don't want to delete the dll. 
Only asked if it is necessary as it wasn't until now and the changelog says is there for Windows 7 or older.
I undestand the dll but, why I have no visible window when using opengl-hq but it appears when I use opengl. Something I'm doing wrong?.

**Comment by man0000** [comment]
Testing, the problem with opengl-hq comes from es=no.
vo=opengl:scale=spline36:cscale=spline36:dscale=mitchell:dither-depth=auto:correct-downscaling:sigmoid-upscaling:deband:es=no
 When you change this to auto or delete it, the window is visible and all works as expected.
 Something in the new build seems to affect this.

**Comment by shinchiro** [comment]
Doesn't happen to me when using opengl-hq. Post the log so the devs can see
it

**Comment by man0000** [comment]
log is for opengl                                    Player Window Visible
log-hq is for opengl-hq                           Player Window  Not Visible 
log-hq- is for opengl-hq with es=auto       Player Window Visible

[mpv.zip](https://github.com/mpv-player/mpv/files/96583/mpv.zip)

**Comment by lachs0r** [comment]
This looks like you did not install your GPU drivers properly. If you look at 
lines 169 to 179 of log-hq, you’ll see that it’s getting Microsoft’s software 
renderer (instead of Intel’s OpenGL implementation), which cannot work with 
our opengl renderer.

**Comment by man0000** [comment]
It could be if I had the same error with the previous version, no?. 
I haven't changed anything in my system and with previous versions I can use -hq and with the new one there is the issue.
Here is the same portion of the log with the previous version of mpv:

[   1.306][v][vo/opengl-hq] Initializing OpenGL backend 'w32'
[   1.323][v][vo/opengl-hq/win32] display-fps: 60.000000
[   1.323][v][vo/opengl-hq/win32] resize window: 100:100
[   1.323][v][vo/opengl-hq/win32] move window: 0:0
[   1.451][v][vo/opengl-hq] GL_VERSION='3.0.0 - Build 9.17.10.4229'
[   1.451][v][vo/opengl-hq] Detected desktop OpenGL 3.0.
[   1.451][v][vo/opengl-hq] GL_VENDOR='Intel'
[   1.451][v][vo/opengl-hq] GL_RENDERER='Intel(R) HD Graphics 2000'
[   1.451][v][vo/opengl-hq] GL_SHADING_LANGUAGE_VERSION='1.30 - Intel Build 9.17.10.4229'
[   1.451][v][vo/opengl-hq] Loaded functions for 210/builtin.
[   1.451][v][vo/opengl-hq] Loaded functions for 210/builtin.
[   1.451][v][vo/opengl-hq] Loaded functions for 300/builtin.
[   1.451][v][vo/opengl-hq] Loaded functions for 110/GL_EXT_unpack_subimage.
[   1.451][v][vo/opengl-hq] Loaded functions for 300/GL_ARB_framebuffer_object.
[   1.451][v][vo/opengl-hq] Loaded functions for 300/GL_ARB_vertex_array_object.
[   1.451][v][vo/opengl-hq] Loaded functions for 300/GL_ARB_texture_float.
[   1.451][v][vo/opengl-hq] Loaded functions for 300/GL_ARB_texture_rg.
[   1.451][v][vo/opengl-hq] Loaded functions for 0/WGL_EXT_swap_control.

It recognizes my graphics card and the last Intel version of the graphic drivers. Correct?.
Maybe I'm missing something?.

THANKS for the help...

**Comment by lachs0r** [comment]
Okay, that’s weird for sure.
Maybe ANGLE’s failure to initialize kills the Intel OpenGL renderer?

@wm4: I don’t know, maybe it’s better to explicitly disable the ANGLE backend 
for -hq instead of implicitly through es=no? Is there even a good reason to do 
so by default, considering the fact that the default set of -hq features 
appears to work fine?

**Comment by lachs0r** [comment]
@man0000: Just to be sure, could you test with backend=win as opengl-hq suboption?

**Comment by wm4** [comment]
It makes mpv use ANGLE out of the box, which is a good idea.

-hq on the other hand defaults to `auto`, which should be fine?

I haven't read everything here, but is the problem that ANGLE initializes fine, but then fails to compile a shader?

**Comment by lachs0r** [comment]
ANGLE doesn’t initialize fine because -hq sets es=no. Then mpv tries to use 
the win backend, but that fails because mysteriously it’s getting the 
Microsoft renderer.

**Comment by wm4** [comment]
So the entire problem is that the user is bothered to use ``vo=opengl-hq:es=yes`` when he wans opengl-hq + ANGLE?

**Comment by lachs0r** [comment]
The problem is that `vo=opengl-hq` fails without explanation when the ANGLE backend is compiled in. Most users don’t know (and shouldn’t have to know) what ANGLE is or does, and the automatic fallback to the plain win backend should not fail.

**Comment by Hrxn** [comment]
I guess that's what I was going to ask...

I use `vo=opengl-hq` and made some logs..
I noticed that ANGLE gets initialized, but it's not used, I assume, because directly after that I saw that win32 gets initialized..

Is that the default behavior?

**Comment by man0000** [comment]
This works as expected. So do with es=yes and es=auto
vo=opengl:scale=spline36:cscale=spline36:dscale=mitchell:dither-depth=auto:correct-downscaling:sigmoid-upscaling:deband:es=no:backend=angle

With backend=win, there's no window. Same with es=yes and es=auto
vo=opengl:scale=spline36:cscale=spline36:dscale=mitchell:dither-depth=auto:correct-downscaling:sigmoid-upscaling:deband:es=no:backend=win

**Comment by wm4** [comment]
The `es` suboption is ignored if the angle or win backends are forced, unless there's a bug.

**Comment by man0000** [comment]
Looking at the results, seems es suboption works as expected and issue goes to backend, no?...

**Comment by Hrxn** [comment]
So it's normal that with `backend=auto` two different backends appear in the log as initialized?
