### ISSUE TITLE
Build failure with vaapi enabled and ffmpeg < 2.7 due to weak VP9 guard

### ISSUE THREAD

**Issue by Coacher** [mpv-player/mpv#2737]
Hello.

VP9 support for vaapi is enabled via this guard: https://github.com/mpv-player/mpv/blob/v0.15.0/video/decode/vaapi.c#L112

However, VP9 support also requires FF_PROFILE_VP9_0 symbol, which is only available in ffmpeg >= 2.7 and libav master. Configure script states that ffmpeg-2.4 and libav-11 should be enough: https://github.com/mpv-player/mpv/blob/v0.15.0/wscript#L398

Please adjust VP9 guard, since VP9 support is not solely relies on recent libva.
Currently mpv cannot be built with vaapi support on ffmpeg < 2.7 and libav even with libva-1.6.2 due to this problem.

**Comment by Coacher** [comment]
Build log with ffmpeg-2.6.3: https://572386.bugs.gentoo.org/attachment.cgi?id=423390

**Comment by Coacher** [comment]
Downstream bug report: https://bugs.gentoo.org/show_bug.cgi?id=572386

**Comment by wm4** [comment]
There is not a single reason to prefer 2.6 oer 2.8, btw.

**Comment by Coacher** [comment]
> There is not a single reason to prefer 2.6 oer 2.8, btw.

Maybe. But this breaks build with any non-live version of libav.

Thank you for the fix.
