### ISSUE TITLE
[Win] Problem with secure connections

### ISSUE THREAD

**Issue by Matthaiks** [mpv-player/mpv#2739]
Can't play YouTube videos with this build: https://mpv.srsfckn.biz/mpv-x86_64-20160118.7z
Older builds are OK.

Error log:
[ffmpeg] https protocol not found, recompile FFmpeg with openssl, gnutls,
[ffmpeg] or securetransport enabled.
[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
[stream] Failed to open                                                               

Windows 8.1

**Comment by lachs0r** [comment]
When did you download this archive? There was a time frame of a few minutes where I had a broken build up. The current one should work.

**Comment by Matthaiks** [comment]
So I was unlucky. Redownloaded and it's working fine now. Thanks.

**Comment by lachs0r** [comment]
Sorry about this. I should have tested this more carefully before publishing the build, especially since I’ve changed so many things.
