### ISSUE TITLE
Issue with JSON parser, float values and non-english locale.

### ISSUE THREAD

**Issue by sotlampr** [mpv-player/mpv#2740]
Hello,
I discovered a bug wen using the JSON IPC on a machine with LC_NUMERIC locale flag set to a languange that uses comma for decimal mark.

The code in question is [here](https://github.com/mpv-player/mpv/blob/ea442fa047819ec2e48a3dbe8ea21959ac3d70b0/misc/json.c#L251), where the float value is converted via printf to a string according to the locale set.

I noticed the issue when using mps-youtube, you can see the [bug report](https://github.com/mps-youtube/mps-youtube/issues/415).

It seems there is already a check [here](https://github.com/mpv-player/mpv/blob/ea442fa047819ec2e48a3dbe8ea21959ac3d70b0/player/client.c#L459), but I didn't receive any helpful message.

I would like your remarks on this and any directives on how to fix this.
S.

**Comment by wm4** [comment]
We don't support setting locale. If some library does this, this library is VERY deeply broken.

**Comment by hrnr** [comment]
Sorry for commenting on closed issue. But I'm just wondering, does this also apply if we launch mpv binary via popen (or fork+exec)? Shouldn't then mpv force the locale itself? Or this is also not supported configuration and we should always set C locale before launching mpv?

Regards,
Jiri

mps-youtube/mps-youtube#415

**Comment by wm4** [comment]
exec() overwrites the program state, so no.

libcaca seems to overwrite the locale, so this has nothing to do with mpv nor mps-youtube.

Since vo_caca is at best some kind of joke, I don't care very much either.

**Comment by wm4** [comment]
Quick search shows that it really does:

https://github.com/cacalabs/libcaca/blob/203d33361ee392588bcbd42684791460bf9cd35d/caca/driver/ncurses.c#L246
https://github.com/cacalabs/libcaca/blob/203d33361ee392588bcbd42684791460bf9cd35d/caca/driver/x11.c#L109

I'd fix this by removing vo_caca, but since random people would probably not like this, I'll do nothing.

**Comment by hrnr** [comment]
Thanks for explanation. I was wondering how could locale get inherited via exec(). Now it makes sense.

Of course since it's only libcaca problem, this is not an issue.

**Comment by samhocevar** [comment]
I’m sorry but if your program crashes when the locale is set, go fix your program. Have a nice day!

**Comment by hrnr** [comment]
Well, to be fair it does not crash. It just produces invalid JSON.

**Comment by wm4** [comment]
>I’m sorry but if your program crashes when the locale is set, go fix your program. Have a nice day!

Your library changes C text processing rules for the entire process out of the blue. This is not safe. It's a good example of library-unsafe behavior which interferes with the host process. (Other examples are global mutable state that is not synchronized or affects other library users, or doing things like `exit(0)`.) Sorry, your poop library is just broken. Go fix it.

Just out of curiosity for the bizarre, I wonder what you're suggesting to "fix" this issue. Maybe set the locale temporarily to something sane? Race conditions. Use the new POSIX 2008 per-thread locale API? Slow, messy, and by far not available on every system. NIH snprintf and strtod? These are very complex functions and not a solution. Replace `,` with `.` manually? Very fragile and messy, and doesn't work with snprintf or even strtod in the general case anyway. Just change the locale back? You can't know when something else changes the locale, and it's a race condition too.

But yeah, keep claiming changing the locale is sane.
