### ISSUE TITLE
Looping gives noticeable delay with active VO

### ISSUE THREAD

**Issue by Kagami** [mpv-player/mpv#2745]
[Test file.](https://dump.bitcheese.net/files/ogutymo/tuturu.webm)

According to both `mkvinfo -v` and `ffprobe -show_frames -of compact` last video frame in this file has `PTS=3.873s` and `duration≈0.016s` and last audio frame is at `3.892s`.

Howerver, with `--loop` option enabled I can hear noticeable delay between repetitions with mpv. Everything is fine with `--no-video` but I can still hear delay with any `--vo` and `--video-sync` options values.

Replacing `vo_still_displaying(vo)` with `false` in `player/video.c` fixes the issue.

**Comment by ChrisK2** [comment]
FYI: there's ``--loop-file`` for looping a single file by seeking back to the beginning instead looping the playlist (and re-initing playback on each loop)

**Comment by Kagami** [comment]
`--loop-file` still gives the same delay as `--loop`.

**Comment by Hrxn** [comment]
Well, I didn't have anything else to do at the moment..

Testing the test file:

`--loop`  very noticeable delay, `--loop-file` no delay

I'm not exactly sure what you are hearing, but keep in mind that the transition is not perfect (no perfect loop), so audio artifacts may be possible (Is it called audio artifact, by the way?)

But I got this warning about the file:
```
Playing: tuturu.webm
 (+) Video --vid=1 (*) (vp9)
 (+) Audio --aid=1 '연애의 조건 (Love Options)' (vorbis)
File tags:
 Title: Bestie - Love Options MV
[mkv] Discarding potentially broken or useless index.
AO: [wasapi] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
AV: 00:00:00 / 00:00:03 (25%) A-V: -0.000
Saving state.


Exiting... (Quit)
```

The Korean characters are not displayed correctly inside cmd.exe, maybe that is related to that other issue here #2743 ?

Required debug information:
```
OS: Windows 10 Pro x64 15.11
MPV: 0.15.0 latest official build for Win
GPU: Latest drivers and working, etc. pp.
```

**Comment by Kagami** [comment]
[Here](https://dump.bitcheese.net/files/ucipezo/tuturu-mpv-patched.webm) is what I hear with patched `player/video.c`
[Here](https://dump.bitcheese.net/files/yfunifu/tuturu-mpv-loop-file.webm) is what I hear with `--loop-file` (same as `--loop` in my case)

**Comment by Kagami** [comment]
Well, maybe `--loop-file` gives less delay than `-loop` but it's still there. Transition in patched version is better.

**Comment by Hrxn** [comment]
Ah, I think I misunderstood..

You had me on the wrong track with 'delay'.

I hear the same as you, more or less. No delay with `--loop-file`, but the sound changes in pitch abruptly, yes. So no smooth transition, and this is clearly audible..

**Comment by Kagami** [comment]
Yes, seems like `--loop` gives delay (on pre-fixed mpv) and `--loop-file` stops playback too early. I just heard something wrong with `--loop-file` and wasn't sure what exactly it is.
