### ISSUE TITLE
pvr:// no longer supported

### ISSUE THREAD

**Issue by kinleyd** [mpv-player/mpv#2748]
On Arch Linux, starting from version 0.14 and continuing into 0.15, when I run:
$ mpv pvr:// 

 I get this error message:
No protocol handler found to open URL pvr://
The protocol is either unsupported, or was disabled at compile-time.

I'm hoping pvr support hasn't been disabled intentionally.

**Comment by AirPort** [comment]
It was: 475fe45

**Comment by kinleyd** [comment]
Thanks @AirPort - I'm complained on that commit. Hopefully @wm4 will reinstate support. :)

**Comment by kinleyd** [comment]
Looks like pvr support is done. What a pity.

**Comment by wm4** [comment]
Only 1 person who wants it back, and the only hardware which this benefits is old and special. Not a very strong case. I _could_ add it back, but then it may as well happen that it disappears soon after that again.

**Comment by kinleyd** [comment]
Sadly too true, only one hand has been raised in favour of reinserting said
code, so no, it does not sound like a strong case.

But.
Before we close the matter, allow me to present my case:

1) I'm using this outmoded technology not out of choice. The primary
problem is that I don't have an alternative. I live in Bhutan, which
unfortunately is still all analog. mpv's pvr is all that works with this
cable input. If I could use an alternative I would, and I would lower my
lonesome hand.

2) If you don't reinsert the code, I would have to do it. I like mpv as it
works for me now, and I'm willing to make that effort if I have to. I don't
know what would be involved - a fork of mpv, some work understanding which
snippets I'd have to put back and where, etc. - I'm really not sure, but I
would do it. The point being to emphasize that I really like mpv.

It would be a lot of work for me to figure it out so if it isn't too much
trouble for you to put it back, I'd really appreciate it!

3) Finally, perhaps we wouldn't need to keep pvr support for too long. I
will see what kind of alternative digital gear will work for me, and
perhaps then I would happily retire my vintage pvr cards.

So there, having pleaded my case, I do hope you will be a kind soul and
help me out!

Thanks. :)
