### ISSUE TITLE
Support sop:// protocol

### ISSUE THREAD

**Issue by rassie** [mpv-player/mpv#2751]
`sop://` protocol is used by [SopCast](http://www.sopcast.org/) to broadcast P2P television. Currently, if one wishes to view some of the channels, a Linux Sopcast client (separate download) needs to be started like this: `sp-sc sop://broker.sopcast.com:3912/$ID $PORT1 $PORT2` where `$ID` stands for a channel ID, `$PORT1` is the local data exchange port and `$PORT2` is the player port. Running `mpv http://localhost:$PORT2` plays the video stream after the client has buffered enough data.

Similar to the `ytdl` Lua hook, it seems that the middle-man could be cut: `mpv sop://broker.sopcast.com:3912/$ID` could play the stream directly, starting the Sopcast client in the background as needed.  The client produces a lot of cryptic output, which is however parsable and thus can provide needed information about buffering and progress (an open-source [Sopcast Player](https://code.google.com/p/sopcast-player/) provides this information without an apparent problem).

NB: This is probably Linux only, since Windows and MacOS X are provided with full GUI-based clients for Sopcast and therefore `sp-sc` might not be available.

**Comment by Akemi** [comment]
OSX is fine too. the app contains a `sp-sc-auth` binary.

**Comment by Akemi** [comment]
i tried to write a [sopcast hook](https://github.com/Akemi/mpv-sopcast-hook). only tested it on OSX. there is also an ugly sleep timer which waits for `sp-sc-auth` to load since i can't read the output of it. anyway maybe there is a better way to do it.

**Comment by mozbugbox** [comment]
If you read [gsopcast/iostatistics.cc](https://code.google.com/archive/p/gsopcast/) source, you can see that you can monitor sopcast caching progress by start sending `"state\ns\n"` __twice__ and then keep sending `"s"` to the tcp socket of the player port for `sp-sc-auth`.

**Comment by Akemi** [comment]
i updated the hook slightly.
