### ISSUE TITLE
Integrate SuperRes

### ISSUE THREAD

**Issue by igv** [mpv-player/mpv#2752]
Here is the source:
https://github.com/zachsaw/MPDN_Extensions/blob/master/Extensions/RenderScripts/Shiandow.SuperRes.cs
https://github.com/zachsaw/MPDN_Extensions/blob/master/Extensions/RenderScripts/SuperRes/Diff.hlsl
https://github.com/zachsaw/MPDN_Extensions/blob/master/Extensions/RenderScripts/SuperRes/SuperRes.hlsl
and a couple of functions from https://github.com/zachsaw/MPDN_Extensions/blob/master/Extensions/RenderScripts/Common/ColourProcessing.hlsl
It's a pretty simple shader, but unfortunately it can't be used as a post shader.

**Comment by igv** [comment]
glsl shader of SuperRes:
https://gist.github.com/igv/e180f2d8b999ba68f3c4
Should force linear-light

**Comment by bjin** [comment]
This isn't going to happen anytime soon. It brings a lot of complexity, and the HLSL code is licensed under LGPLv3.

**Comment by lanzorg** [comment]
Why can't it be used as post shader?
In madvr, super-res can be used in "upscaling refinements" aka "post upscaling".

**Comment by igv** [comment]
>Why can't it be used as post shader?
It can't be used as custom post shader, it requires pre-resized image and video bit depth.

**Comment by lanzorg** [comment]
Is it impossible to pre-resize the picture or change the bit depth with custom shaders?
What is wrong exactly? An opengl weakness, a mpv internal code structure fault or something else?
I really like this algorithm, I hope it will become real in mpv. ;)

**Comment by ADormant** [comment]
@bjin  @igv @lanzorg   You can use this Cg version it can be used as a post-processing shader.

https://github.com/libretro/common-shaders/tree/master/sharpen
https://github.com/libretro/common-shaders/tree/master/sharpen/shaders
https://github.com/libretro/common-shaders/tree/master/misc

**Comment by igv** [comment]
What is the difference? adaptive sharpen already has been ported and super-res is the same shader from MPDN Extensions.

**Comment by ADormant** [comment]
Adaptive-Sharpen and SuperRes are different shaders.

**Comment by igv** [comment]
I was wrong, it doesn't require video bit depth, only original image in diff shader, then the resulting texture should be passed to SuperRes shader as uniform variable.

**Comment by igv** [comment]
Updated SuperRes, added downscaler.
