### ISSUE TITLE
MPV stream titles contain garbage

### ISSUE THREAD

**Issue by markg85** [mpv-player/mpv#2754]
Hi,

I tend to play the Q-Music (dutch) radio stream quite often using the following simple command:
> mpv http://icecast-qmusic.cdp.triple-it.nl/Qmusic_nl_live_96.mp3

Apparently the stream title changes when the broadcaster is about to play a different number, so i see lines like:
File tags:
 icy-title: Sun Is Shining - AXWELL /\ INGROSSO'
A: 00:07:36 Cache: 10s+232KB
File tags:
 icy-title: Second Hand Heart - BEN HAENOW & KELLY CLARKSON'5��N�
A: 00:08:16 Cache: 10s+248KB

The first  "icy-title: Sun Is Shining - AXWELL /\ INGROSSO'" is OK.
The second "icy-title: Second Hand Heart - BEN HAENOW & KELLY CLARKSON'5��N�" contains garbage.

It doesn't bother me much, but i reported it just in case.
I'm not even sure if this issue is in mpv or in the libraries it's using. If that's the case, please do tell then i will report it against the appropriate library.

Cheers,
Mark

**Comment by wm4** [comment]
Could reproduce, and dumped the thing we get from the server as hex:

```
00000000  53 74 72 65 61 6d 54 69  74 6c 65 3d 27 41 64 76  |StreamTitle='Adv|
00000010  65 6e 74 75 72 65 20 4f  66 20 41 20 4c 69 66 65  |enture Of A Life|
00000020  74 69 6d 65 20 2d 20 43  4f 4c 44 50 4c 41 59 27  |time - COLDPLAY'|
00000030  b2 54 27 3b                                       |.T';|
```

The stuff after the `COLDPLAY` is probably garbage. Normally, the StreamTitle field is terminated with `';` - which is also the case here, except there's some garbage before it.

I think the server is just buggy.

**Comment by markg85** [comment]
Hi wm4,

Thank you for looking into this so fast!
Just curious, could you explain how you did it this fast? Just the steps to reproduce that?
I'd like to be able to do that as well.

What i would do is clone the mpv repository, look for "icy-title" and add debug output around that assuming i would have found it in the mpv repository. But i have a feeling that your take on this is much faster and prevents recompiling?

**Comment by wm4** [comment]
Recompiling takes only 4 seconds (after ffmpeg is setup, configure is run etc.). I only added some code to dump the icy string we get from libavformat into a file. Anyway, I think this is going to be a WONTFIX.

**Comment by markg85** [comment]
Ahh ok :) Thank you for the short explanation.
Closing this issue.
