### ISSUE TITLE
HLS broken with newest FFmpeg (was: Forced pauses in m3u8 style playlists)

### ISSUE THREAD

**Issue by Warblefly** [mpv-player/mpv#2755]
Thank you for reading this.

I'm using mpv git-809786d, pulled and built today. It's built against FFmpeg N-78025-g22ee0a5, also pulled and built today.

The compilation is carried out on GNU/Linux using mingw-w64 gcc 5.3.0, and the executable is being run on Windows 10, 64 bit.

In this build, there is a major stuttering problem on m3u8 style live channels.

The player halts at the end of each .ts section of the m3u8 playlist, and only then fetches the next section. Until now, sections appeared (sensibly) to be fetched in advance of needing to be played.

Here is an example.

Channels such as this:

```uri
http://wmsrtsp1.rte.ie/live/android.sdp/playlist.m3u8
```

...until now have played perfectly smoothly. But now, when watching the console messages from mpv (not using -v), it seems that each portion of the playlist is downloaded, played, and then the next portion fetched without any look-ahead.

```console
C:\Users\john_000\Videos>mpv --no-ytdl http://wmsrtsp1.rte.ie/live/android.sdp/playlist.m3u8
Playing: http://wmsrtsp1.rte.ie/live/android.sdp/playlist.m3u8

Playing: http://wmsrtsp1.rte.ie/live/android.sdp/chunklist_w747541394.m3u8

Playing: http://wmsrtsp1.rte.ie/live/android.sdp/media_w747541394_173814.ts
[ffmpeg] NULL: start time for stream 0 is not set in estimate_timings_from_pts
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
AO: [wasapi] 44100Hz stereo 2ch float
VO: [direct3d] 1024x576 yuv420p
AV: 00:00:11.960 / 00:00:12.000 (99%) A-V:  0.000 DS: 2.417/6 Cache:  0s+0KB

Playing: http://wmsrtsp1.rte.ie/live/android.sdp/media_w747541394_173815.ts

[ffmpeg] NULL: start time for stream 0 is not set in estimate_timings_from_pts
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
AV: 00:00:07.971 / 00:00:08.010 (99%) A-V:  0.000 DS: 2.417/5 Cache:  0s+0KB

Playing: http://wmsrtsp1.rte.ie/live/android.sdp/media_w747541394_173816.ts

[ffmpeg] NULL: start time for stream 0 is not set in estimate_timings_from_pts
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
AV: 00:00:04.730 / 00:00:12.010 (40%) A-V:  0.000 DS: 2.417/5 Cache:  7s+0KB
```

ffplay executed on this playlist works without stopping.

**Comment by wm4** [comment]
It seems libavformat is not recognizing it as HLS correctly? But then it shouldn't work via ffplay either.

**Comment by Warblefly** [comment]
Indeed, that's the weird thing. The playlist plays fine on ffplay. You don't think it's anything to do with these recent commits to libavformat/hls.c, do you?

https://github.com/FFmpeg/FFmpeg/commits/master/libavformat/hls.c

mpv/ffmpeg were last built before those changes were made. That build worked well.

I appreciate you looking into this. mpv is my primary player.

**Comment by wm4** [comment]
Actually I do think that something in ffmpeg git master broke HLS probing for mpv. It works if you do --demuxer=lavf.

**Comment by Warblefly** [comment]
It does! Just tried it. But if I can't break the change by using plain ffplay, how phrase my concern to the FFmpeg-Devel list? Or (as I recognise your name from that list) is it better if you mention it?

**Comment by wm4** [comment]
I already brought it up on the IRC channel.

Apparently the way it works is that the HLS demuxer checks the filename, and rejects the URL if it doesn't end in m3u8 (for whatever reasons). If no filename is set, the check is supposed to be skipped. Except that "no filename" means NULL, which makes another demuxer actually crash. So mpv passes "", which is now rejected by the HLS demuxer.

So yeah, indeed not mpv's fault.

**Comment by Warblefly** [comment]
That's really helpful! Thanks a lot — I may login there to see what the conversation is like. My C programming skills are really lower than the lowest, but watching a fix take place may teach me something.

**Comment by wm4** [comment]
To my knowledge, another recent change in ffmpeg should fix this again.

**Comment by Warblefly** [comment]
Yay :-) Just saw it on the #ffmpeg-devel channel and in the repository. Compiling it now (shared libs, but compiling mpv as well just to be sure)
