### ISSUE TITLE
Artifacts with use of scalers and/or opengl-hq

### ISSUE THREAD

**Issue by a-laptop** [mpv-player/mpv#2758]
Example: https://u.teknik.io/50rxAn.png

Specs
CPU: i5 6500
GPU: r9 390
Tested on Arch kernel 4.2.4-1, 4.3.3-3 and 4.4-4 as well as Debian kernel 3.16, 4.3. Tested with radeon (xf86-video-ati) and amdgpu (xf86-video-amdgpu) drivers.

Artifacts seem to appear when shaders are applied ontop of the opengl config, also occurs on the reccomended opengl-hq. With and without hwdec applied. No problems with opengl-hq in Windows 10 64bit and no artifacting. Have only noticed this problem within the last 2 months, can't say if it was always present or not. Tried rolling back to older kernel versions to see if it was due to the jump in kernel. This artifacting is present in both mkv, mp4 and wmv containers.

**Comment by Cpuroast** [comment]
I doubt mpv is to blame, most likely drivers or hardware related issue.

**Comment by a-laptop** [comment]
Thanks anyway mate, I'll probably just stick to the default since it's good enough and move better looking videos to windows when I feel like playing around wuth vo settings.

Rolled back to drivers, xorg and mpv  from Nov-15 and the problem persists so I might just not have noticed the artifacting.

Played around with haasnsoft and lanczos ontop of opengl rather than opengl-hq and still experienced the same problems as well.

**Comment by wm4** [comment]
Insufficient problem description.
