### ISSUE TITLE
vf=dsize not working anymore

### ISSUE THREAD

**Issue by insysadm** [mpv-player/mpv#2760]
it worked fine in:

mpv git-fee45c0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Tue Nov 10 19:26:26 CET 2015
ffmpeg library versions:
   libavutil       55.5.100
   libavcodec      57.15.100
   libavformat     57.14.100
   libswscale      4.0.100
   libavfilter     6.15.100
   libswresample   2.0.101
ffmpeg version: N-76584-g5d9c3bb

for example:

mpv --vf=dsize=640:-2 sample.mp4
Playing: sample.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
Opening video filter: [dsize w=640 h=-2]
AO: [wasapi] 44100Hz 5.1(side) 6ch float
VO: [opengl] 1280x720 => 640x360 yuv420p
AV: 00:00:02 / 00:00:10 (22%) A-V:  0.000

Exiting... (Quit)

but is not working in 

mpv 0.15.0-git-2a8bbee (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 18 14:52:12 CET 2016
ffmpeg library versions:
   libavutil       55.13.100
   libavcodec      57.22.100
   libavformat     57.21.101
   libswscale      4.0.100
   libavfilter     6.25.100
   libswresample   2.0.101
ffmpeg version: N-77911-g9cdc23e

for example:

mpv --vf=dsize=640:-2 sample.mp4
Playing: sample.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
Opening video filter: [dsize w=640 h=-2]
AO: [wasapi] 44100Hz 5.1(side) 6ch float
VO: [opengl] 1280x720 yuv420p
AV: 00:00:01 / 00:00:10 (17%) A-V:  0.000

Exiting... (Quit)

also tried it from config file, same result.

**Comment by wm4** [comment]
`dsize` can now only change the aspect ratio, not the video size directly. Use --geometry, --window-scale, or one of the --autofit... options instead.

**Comment by insysadm** [comment]
but it's in the manual

**Comment by wm4** [comment]
The manpage mentions that this changes the aspect only, for the most part.

> (window in middle of the screen 640 pixels wide)

something like `--geometry=50%:50% --autofit=640` (the first forces centering the window, the second forces the window width)
