### ISSUE TITLE
mp4 player not working

### ISSUE THREAD

**Issue by maxxgilly** [mpv-player/mpv#2764]
![1](https://cloud.githubusercontent.com/assets/16928131/12631016/406d3a12-c51d-11e5-9921-863af42055d8.jpg)

I started using mpv player with windows 7 recently and it was working fine until yesterday.  As you could see, I have set mpv player as my default player, but whenever I try to open it is showing a message as in the image.  This is even after closing all the applications.  Please find a solution as I find the mpv player as the best player I have used so far.

**Comment by rossy** [comment]
Could you post a log? Open a Command Prompt and type something like:
```
start mpv.exe F:\Interstellar* --log-file=F:\log.txt
```
Then upload log.txt to a pastebin.

**Comment by maxxgilly** [comment]
still it shows the same.
![1](https://cloud.githubusercontent.com/assets/16928131/12639604/38686a66-c573-11e5-9af9-72e57074d8a4.jpg)

**Comment by kevmitch** [comment]
> still it shows the same.

yes, but what does the log.txt say?

**Comment by maxxgilly** [comment]
[log.txt](https://github.com/mpv-player/mpv/files/108277/log.txt)

I've attached the log for you to review.  Note, I had mpv installed from the mentioned folder H:Superstars/Kam Shi.  Should I delete it?

**Comment by kevmitch** [comment]
Wonder if there's a particular configuration option that makes this trigger for you. Does

    start mpv.exe F:\Interstellar* --no-config

produce the same error?

**Comment by maxxgilly** [comment]
This is the result I get while I still have mpv installed.
![1](https://cloud.githubusercontent.com/assets/16928131/12684882/0fbb76f4-c68f-11e5-8d97-13b63ebc6412.jpg)
