### ISSUE TITLE
Opengl VDPAU hw decoding not working for 3gp/mpeg4

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#2767]
Hi!

mpv 0.15.0 on gentoo 64 bit with Nvidia GTX 660 -- VDPAU not using h/w acceleration for 3gp/mpeg4.

However, I'm not sure if it should use h/w decoding in this case. It just seems that it founds a suitable VDPAU decoder, but doesn't use it for some reason.

>$ mpv -v --profile=basic clip.3gp
...
[vd] Container reported FPS: 9.989268
[vd] Codec list:
[vd]     lavc:mpeg4 - MPEG-4 part 2
[vd]     lavc:mpeg4_vdpau (mpeg4) - MPEG-4 part 2 (VDPAU)
[vd] Opening video decoder lavc:mpeg4
[vd] Probing 'vdpau'...
[vd] Trying hardware decoding.
[vd] Selected video codec: MPEG-4 part 2 [lavc:mpeg4]
[vo/opengl/x11] Disabling screensaver.
[vo/opengl/x11] Setting DMPS: off.
[cplayer] Starting playback...
[vd] Pixel formats supported by decoder: vdpau yuv420p
[vd] Pixel formats supported by decoder: yuv420p
[vd] Falling back to software decoding.
[vd] Detected 8 logical cores.
[vd] Requesting 9 threads for decoding.
[vd] Using software decoding.
[vd] Using container aspect ratio.
[vf] Video filter chain:
[vf]   [vd] 1024x720 yuv420p auto/auto CL=mpeg2/4/h264 rot=180
[vf]   [in] 1024x720 yuv420p bt.709/limited CL=mpeg2/4/h264 rot=180
[vf]   [out] 1024x720 yuv420p bt.709/limited CL=mpeg2/4/h264 rot=180
[cplayer] VO: [opengl] 1024x720 yuv420p
...

Video mediainfo:
>General
Complete name                            : VID_20160128_161312.3gp
Format                                   : MPEG-4
Format profile                           : 3GPP Media Release 4
Codec ID                                 : 3gp4
File size                                : 12.3 MiB
Duration                                 : 26s 28ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 3 972 Kbps
Encoded date                             : UTC 2016-01-28 13:13:12
Tagged date                              : UTC 2016-01-28 13:13:12

>Video
ID                                       : 1
Format                                   : MPEG-4 Visual
Format profile                           : Main@L4
Format settings, BVOP                    : Yes
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : 20
Duration                                 : 26s 28ms
Bit rate mode                            : Constant
Bit rate                                 : 3 961 Kbps
Nominal bit rate                         : 256 Kbps
Width                                    : 1 024 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 1.422
Rotation                                 : 180°
Frame rate mode                          : Variable
Frame rate                               : 9.989 fps
Minimum frame rate                       : 9.986 fps
Maximum frame rate                       : 9.994 fps
Color space                              : YUV
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.538
Stream size                              : 12.3 MiB (100%)
Title                                    : VideoHandle
Writing library                          : MTK_ENCODER_V3
Language                                 : English
Encoded date                             : UTC 2016-01-28 13:13:12
Tagged date                              : UTC 2016-01-28 13:13:12
mdhd_Duration                            : 26028

mpv profile:
>[basic]
vo=opengl
hwdec=vdpau
hwdec-codecs=all
softvol=no

Regards,
Alex

**Comment by wm4** [comment]
vdpauinfo output?

**Comment by fhlfibh** [comment]
@wm4 

display: :0.0   screen: 0
API version: 1
Information string: NVIDIA VDPAU Driver Shared Library  355.11  Wed Aug 26 16:05:52 PDT 2015

Video surface:

name   width height types
-------------------------------------------
420     4096  4096  NV12 YV12 
422     4096  4096  UYVY YUYV 

Decoder capabilities:

name                        level macbs width height
----------------------------------------------------
MPEG1                           0 65536  4032  4048
MPEG2_SIMPLE                    3 65536  4032  4048
MPEG2_MAIN                      3 65536  4032  4048
H264_BASELINE                  41 65536  4032  4080
H264_MAIN                      41 65536  4032  4080
H264_HIGH                      41 65536  4032  4080
VC1_SIMPLE                      1  8190  2048  2048
VC1_MAIN                        2  8190  2048  2048
VC1_ADVANCED                    4  8190  2048  2048
MPEG4_PART2_SP                  3  8192  2048  2048
MPEG4_PART2_ASP                 5  8192  2048  2048
DIVX4_QMOBILE                   0  8192  2048  2048
DIVX4_MOBILE                    0  8192  2048  2048
DIVX4_HOME_THEATER              0  8192  2048  2048
DIVX4_HD_1080P                  0  8192  2048  2048
DIVX5_QMOBILE                   0  8192  2048  2048
DIVX5_MOBILE                    0  8192  2048  2048
DIVX5_HOME_THEATER              0  8192  2048  2048
DIVX5_HD_1080P                  0  8192  2048  2048
H264_CONSTRAINED_BASELINE      41 65536  4032  4080
H264_EXTENDED                  41 65536  4032  4080
H264_PROGRESSIVE_HIGH          41 65536  4032  4080
H264_CONSTRAINED_HIGH          41 65536  4032  4080
H264_HIGH_444_PREDICTIVE       41 65536  4032  4080
HEVC_MAIN                      --- not supported ---
HEVC_MAIN_10                   --- not supported ---
HEVC_MAIN_STILL                --- not supported ---
HEVC_MAIN_12                   --- not supported ---
HEVC_MAIN_444                  --- not supported ---

Output surface:

name              width height nat types
----------------------------------------------------
B8G8R8A8         16384 16384    y  Y8U8V8A8 V8U8Y8A8 A4I4 I4A4 A8I8 I8A8 
R10G10B10A2      16384 16384    y  Y8U8V8A8 V8U8Y8A8 A4I4 I4A4 A8I8 I8A8 

Bitmap surface:

name              width height
------------------------------
B8G8R8A8         16384 16384
R8G8B8A8         16384 16384
R10G10B10A2      16384 16384
B10G10R10A2      16384 16384
A8               16384 16384

Video mixer:

feature name                    sup
------------------------------------
DEINTERLACE_TEMPORAL             y
DEINTERLACE_TEMPORAL_SPATIAL     y
INVERSE_TELECINE                 y
NOISE_REDUCTION                  y
SHARPNESS                        y
LUMA_KEY                         y
HIGH QUALITY SCALING - L1        y
HIGH QUALITY SCALING - L2        -
HIGH QUALITY SCALING - L3        -
HIGH QUALITY SCALING - L4        -
HIGH QUALITY SCALING - L5        -
HIGH QUALITY SCALING - L6        -
HIGH QUALITY SCALING - L7        -
HIGH QUALITY SCALING - L8        -
HIGH QUALITY SCALING - L9        -

parameter name                  sup      min      max
-----------------------------------------------------
VIDEO_SURFACE_WIDTH              y         1     4096
VIDEO_SURFACE_HEIGHT             y         1     4096
CHROMA_TYPE                      y  
LAYERS                           y         0        4

attribute name                  sup      min      max
-----------------------------------------------------
BACKGROUND_COLOR                 y  
CSC_MATRIX                       y  
NOISE_REDUCTION_LEVEL            y      0.00     1.00
SHARPNESS_LEVEL                  y     -1.00     1.00
LUMA_KEY_MIN_LUMA                y  
LUMA_KEY_MAX_LUMA                y

**Comment by wm4** [comment]
Maybe a profile check fails. Can you upload a sample?

**Comment by fhlfibh** [comment]
@wm4 
5 secs clip cut with `ffmpeg -c:v copy` [http://sendfile.su/1198535](http://sendfile.su/1198535)

**Comment by wm4** [comment]
The file identifies itself as mpeg-4 "Main Profile", which is not even defined in the vdpau API. Not sure, but you might be out of luck.

**Comment by fhlfibh** [comment]
@wm4 
Ok, I will try to file a but at ffmpeg.org later, maybe they'll fix their API

Thanks a lot!

Alex

**Comment by wm4** [comment]
I mean the libvdpau API. I don't know if this "Main Profile" is supported by any hardware decoders at all. If not, that would explain why it's not defined in the API (because there's no need to).

**Comment by Gusar321** [comment]
The only mpeg4 hw decoder I have is the Raspberry Pi 2. And it seems it can decode that video, mpv claims "Using hardware decoding (rpi)"

Is it possible somehow to reinstate --vd-lavc-check-hw-profile=no for VDPAU? That would allow checking if the Nvidia hw decoder can handle such video.

**Comment by wm4** [comment]
>Is it possible somehow to reinstate --vd-lavc-check-hw-profile=no for VDPAU?

No. libavcodec selects the profile now, and there's no API to get this behavior. All you could do is editing vdpau_mpeg4.c in the libavcodec sources. I did that, and the video seemed to decode ok.

**Comment by fhlfibh** [comment]
Unfortunately, now I have no idea where I should file this bug to, so I close this thread for now.
Maybe later me or someone else will reopen it or will file the bug to the right place.
