### ISSUE TITLE
Support `fmps_playcount` fields when playing audio files

### ISSUE THREAD

**Issue by mruessler** [mpv-player/mpv#2769]
Right now, `mpv` does not seem to support the `fmps_playcount` ID3 field. Are there plans to implement support?

**Comment by wm4** [comment]
Where's the specification of this field?

**Comment by mruessler** [comment]
FMPS (free media player specification) specification can be found [here](https://wiki.freedesktop.org/www/Specifications/free-media-player-specs/).

**Comment by wm4** [comment]
The links there are all 404.

**Comment by mruessler** [comment]
Then I guess it does not make sense to implement it.
