### ISSUE TITLE
Subtitles with language code

### ISSUE THREAD

**Issue by for-coursera** [mpv-player/mpv#2771]
Sorry if I'm missing something but is it possible to make mpv load language code differentiated subtitles, too? Like, if there's a clip `VideoNamedFoo.avi` and a subtitles file `VideoNamedFoo.en.srt`, then mpv simply doesn't load it.

OS X 10.8.5.

**Comment by Frechdachs** [comment]
The option `--sub-auto=fuzzy` should load everything that contains the filename of the video. The default is `exact`.

**Comment by for-coursera** [comment]
Oh, I see. Thanks!

And that option can be put to `mpv.conf`, too:

    # Auto load external subtitles.
    # fuzzy: Load all subs containing media filename.
    sub-auto=fuzzy

Thus, I'm closing it now.
