### ISSUE TITLE
Mac OS X release builds [was: tar.bz2]

### ISSUE THREAD

**Issue by es0phagus** [mpv-player/mpv#2775]
The latest version (v0.15) doesn't have a tar.bz2 file to download; how can I install it? I have always just used the tar.bz2 file.

**Comment by wm4** [comment]
I guess you mean the mac builds.

**Comment by Cpuroast** [comment]
You can also use these semi-official builds from here:

http://sva.wakku.to/~chris/mpv_builds/

They are more frequent and based on git-master, although stuff can break at times, although it's pretty rare :)

**Comment by es0phagus** [comment]
@wm4 Yes, I mean the Mac builds
@Cpuroast Those don't have a changelog? And I'd prefer to have a stable release.

**Comment by wm4** [comment]
It's not like "stable" means anything. Stable releases are random git snapshots.

**Comment by bodayw** [comment]
The OS X build will only appear there on the release page if @ChrisK2 (the maintainer of the link mentioned above) makes one, and for some reason he hasn't made one for 0.15.0. More or less one year ago mpv still have a release manager who actually handpicks recent commits in the git master branch and make stable releases, which was a tedious work and in my memory there were times when those stable builds just break things as well. Now mpv releases are just cut offs from git master, happens every once in a while, as @wm4 pointed out.

So...it's actually the same person who makes all those builds, be it "stable" release or random git snapshots, and they're not really different in terms of stability now.

**Comment by chrisaljoudi** [comment]
FWIW, I'd be happy to provide OS X builds of the tagged releases to be made available on the [GitHub releases page)(https://github.com/mpv-player/mpv/releases) if @wm4 is interested.

**Comment by ChrisK2** [comment]
Oh, never got to posting here. I updated my build-system to 10.11 and am still dealing with the post-upgrade-fallout. I made a test-build and it didn't launch on 10.10 (unless started with Terminal) and crashed on 10.8 (apparently some harfbuzz incompatibility).

**Comment by cactus** [comment]
@ChrisK2 Just curious -- Any updates regarding the osx builds?

**Comment by ChrisK2** [comment]
nope.

**Comment by enerai** [comment]
@ChrisK2 If it is possible, I wish that there is an OS X build of the latest stable version, only for 10.11. Thanks a lot!

**Comment by taiyangc** [comment]
+1 for making 10.11-only builds again! Thanks.
