### ISSUE TITLE
Regressions functionality mpv-0.15.0

### ISSUE THREAD

**Issue by wasp71** [mpv-player/mpv#2783]
Hi!
In the mpv-0.15.0 don't work video filter "dsize", but in the mpv-0.14.0 work is fine!
For example:
mpv -vf=dsize=960:-2 video_file_or_stream

Part of log for mpv-0.15.0:
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (mp2)
Opening video filter: [dsize w=960 h=-2]
AO: [oss] 48000Hz stereo 2ch s16
VO: [opengl] 1920x1080 yuv420p
AV: 00:00:05 A-V: -0.000 Cache:  1s+0KB

Part of log for mpv-0.14.0:
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (mp2)
Opening video filter: [dsize w=960 h=-2]
AO: [oss] 48000Hz stereo 2ch s16
VO: [opengl] 1920x1080 => 960x540 yuv420p
AV: 00:00:03 A-V: -0.000 Cache:  1s+0KB

Please fix that!
Thanks!

P.S.
OS FeeBSD 10.2

pkg info:
mpv-0.14.0,1                   Free and open-source general-purpose video player
ffmpeg-2.8.5,1                 Realtime audio/video encoder/converter and streaming server

**Comment by AirPort** [comment]
See https://github.com/mpv-player/mpv/issues/2760

**Comment by wasp71** [comment]
Thanks, work!
But need correct man page.

**Comment by wm4** [comment]
But the manpage already mentions this? Just like I mentioned it in the referenced issue.
