### ISSUE TITLE
Can not read ~/.config/mpv/mpv.conf when I execute through shell by Command Line

### ISSUE THREAD

**Issue by raylua2566** [mpv-player/mpv#2785]
When I run from /Applications/mpv.app , it can read ~/.config/mpv/mpv.conf.
But run through cmd like :

>  mpv xxxx.mp4

It not affected by ~/.config/mpv/mpv.conf.

**Comment by ccqpein** [comment]
same to me, I even cannot load conf file in /Application/mpv.app
