### ISSUE TITLE
how to disable dvd subtitle transparency?

### ISSUE THREAD

**Issue by myskn** [mpv-player/mpv#2786]
A mkv file, it used graphical subtitle , sometimes i can't see the subs, because subtitle transparency.

**Comment by lachs0r** [comment]
There’s no way to change the appearance of bitmap-based subs like that, currently. You’ll have to fix the subtitles manually.

**Comment by myskn** [comment]
@lachs0r 
i test 3 software on a same mkv file.
mpv: subtitle transparency.
vlc: subtitle transparency, but it can disable dvd subtitle transparency.
mplayer: subtitle not transparency.
