### ISSUE TITLE
-vo wayland  -hwdec vaapi

### ISSUE THREAD

**Issue by gfvehlhg** [mpv-player/mpv#2787]
In wayland session when you output via OpenGL hardware acceleration works, but still using `-vo opengl-hq` sometimes skipped frames; and using `-vo opengl` sensitive soap the image, but without performance problems. In `-vo wayland` every frame is perfect, but it does not work hardware acceleration, and the laptop heats up and makes noise.

**Is it possible to implement hardware acceleration when outputting via wayland?**

**Comment by wm4** [comment]
It's possible to implement it, but currently there are no developers interested in doing it.

> using -vo opengl sensitive soap the image

Not sure what this means.
