### ISSUE TITLE
Return raw frame in "-vo wayland"

### ISSUE THREAD

**Issue by gfvehlhg** [mpv-player/mpv#2788]
I suppose when using `-vo wayland` a frame is converted to a format `xrgb8888`, but the wayland protocol allows returns in the format `yuv420`, for example. Will this increase the performance with this implementation?

**Comment by wm4** [comment]
Not sure what you're asking. That vo_wayland should send yuv frames to wayland?

**Comment by gfvehlhg** [comment]
Yes, now available only rgb565 and rgb8888

**Comment by giselher** [comment]
The supported frame format depends on the compositor. Which compositor supports yuv formats?

**Comment by giselher** [comment]
I checked and both weston and sway only support rgb8888.

**Comment by gfvehlhg** [comment]
@giselher Want to say that these flags do nothing?
```
$ mpv -vo wayland:help
Options:

 alpha                          Flag (default: no)
 rgb565                         Flag (default: no)

Total: 2 options
```

**Comment by giselher** [comment]
> The supported frame format depends on the compositor. Which compositor supports yuv formats?
> 
> The reference implementation of compositor weston does not fully support the wayland protocol?

It fully supports the protocol. It has a mechanism that tells you what frame formats it supports. The specs just lists all possible formats it *can* support.

**Comment by giselher** [comment]
> I checked and both weston and sway only support rgb8888.
> 
> Want to say that these flags do nothing?
> 
> $ mpv -vo wayland:help
> Options:
> 
>  alpha                          Flag (default: no)
>  rgb565                         Flag (default: no)
> 
> Total: 2 options

Yeah, it supports rgb8888, argb8888 and rgb565. But not yuv420 and other formats.
