### ISSUE TITLE
Transparent bar at top of window (i3wm)

### ISSUE THREAD

**Issue by Zekario** [mpv-player/mpv#2790]
When I use mpv, there is a small transparent bar at the top of the video. This apparently shows what is underneath the window, which is annoying. This happens on more than one video, so it isn't just in the file. I also tried a complete reinstall of mpv, to no avail. The size of the window has no effect.

What can I try that may fix it?

~~EDIT: Setting the border to 1 pixel fixed it.~~

It seems to be caused by compton, as turning it off fixes the bar. Turning frame_opacity to 1 fixes it, but I'd like to have it set to 0.7. Maybe I can do this, brb.

**Comment by wm4** [comment]
At least if using X11, most likely a WM bug? Since there's no further information or anything, I'll just assume that.
