### ISSUE TITLE
frame-back-step stops working after a few frames

### ISSUE THREAD

**Issue by zuzzurro** [mpv-player/mpv#2796]
I have tried frame-back-step (,) on multiple videos I have, and most of the times it works for some frame steps, and then video just gets "stuck". It seems a bug to me,  maybe it's just that not enough people are requesting this?

**Comment by kevmitch** [comment]
Seems to work for me all the time. Files in question are probably broken. Do you have a sample?

**Comment by Q3CPMA** [comment]
I can reproduce it on all my m2ts files. Probably due to the container.

**Comment by wm4** [comment]
Needs sample files.

Transport streams are hard to seek, and libavformat often seems to miss the seek target (?). Try `--hr-seek-demuxer-offset=5`.

**Comment by zuzzurro** [comment]
Thanks a lot for the feedback. It's my first query in the mpv project and I really appreciate the help.
 I will try the --hr-seek-demuxer-offset suggestion. On the other hand I can choose container, but I really need the functionality. What's the best container for this?

**Comment by Q3CPMA** [comment]
@wm4 [Here](a.pomf.cat/hkjrgq.m2ts). Obtained via `ffmpeg -i 00001.m2ts -ss 00:07:10.000 -t 2 -c copy out.m2ts`

**Comment by wm4** [comment]
>On the other hand I can choose container, but I really need the functionality. What's the best container for this?

mkv, mp4.

>@wm4 Here. Obtained via ffmpeg -i 00001.m2ts -ss 00:07:10.000 -t 2 -c copy out.m2ts

Yeah, effectively libavformat doesn't seek to before the seek target (even though it's told to do so), so only increasing the --hr-seek-demuxer-offset can help. Note that depending on the h264 stream and what ffmpeg does when remuxing to mkv/mp4, the same situation could happen with these formats.

Also, the sample doesn't even have decodable audio, which confuses mpv a lot.

**Comment by zuzzurro** [comment]
Guys.. with a trasnport stream h264/50 frames GOP I can use an hr-seek-demuxer-offset > 2 and stepping backwards seem to work all the time. That is fine and dandy, thanks a lot for the suggestion.
What happens, though is that the CPU usage becomes way higher, and single stepping is a bit slow.
Do you think this is reasonable or is it an indication of a BUG?
I think a spike in CPU usage is understandable, but why does it become constant in presence of a steady flow of back steps? Are we by change discarding the buffer every time??

**Comment by wm4** [comment]
Yes with hr-seek-demuxer-offset=2, each backstep will decode at least 2 seconds of video, all for 1 frame.

**Comment by zuzzurro** [comment]
So, for each backstep you decode 2 seconds of video, and then throw the result away? Wouldn't it be possible to cache the decode video for a while?

**Comment by wm4** [comment]
Possible yes, simple no.

**Comment by zuzzurro** [comment]
Would you be able to point out the code that is involved, and would need to be modified?

**Comment by All3xJ** [comment]
I fixed by uncommenting the `RIGHT seek 5` and `LEFT seek -5` lines in input.conf
and also by adding `hr-seek=yes` in mpv.conf
