### ISSUE TITLE
--screenshot-template=%tX doesn't support nanoseconds

### ISSUE THREAD

**Issue by ThomS8312** [mpv-player/mpv#2801]
Using <code>%tN</code> as a format specifier with the <code>screenshot-template</code> option won't expand to a nanoseconds value, but displays "%N" instead.

**Comment by wm4** [comment]
What makes you think this should work? As the manpage explains, this uses strftime(), and it doesn't support `%N`.

**Comment by ThomS8312** [comment]
I've never heard of strftime() before seeing it in the man page. When I read that, I thought it was code that was a part of mpv that copied <code>date</code> (you might be surprised how these things can be interrupted when it's unfamiliar). I just looked it up and saw for myself that it had its own man page and all the options for it listed.

But, is there any particular reason strftime() is used and not <code>date</code>? I've found nanoseconds to be a very reliable way to create unique filenames and it wouldn't have the drawback of playback time specifiers (<code>%wX</code>), which can expand to an "unknown" value in certain circumstances.

**Comment by wm4** [comment]
Because date is not a C function?

strftime can't format nanoseconds, because the input passed to it has at most seconds precision.

**Comment by ThomS8312** [comment]
So this is a limitation of strftime. At least I know why nanoseconds aren't an option.

Could a lua script add nanoseconds to <code>screenshot-template</code> using <code>date</code>?

**Comment by wm4** [comment]
>Could a lua script add nanoseconds to screenshot-template using date?

No, but Lua scripts can do screenshots in other ways, like with https://mpv.io/manual/master/#command-interface-screenshot-to-file or https://mpv.io/manual/master/#command-interface-screenshot-raw.

**Comment by ThomS8312** [comment]
OK, thanks. I'll look into it.
