### ISSUE TITLE
Problem with video pts with --lavfi-complex and album-art

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#2802]
I was trying to overlay an audio visualization to the album art, this way:
```
mpv '/mnt/nas.crypt/Musica/Houndmouth - Little Neon Limelight (2015)/01 - Sedona - Houndmouth.mp3'  --lavfi-complex='[aid1]asplit[ao][a1];[a1] avectorscope=m=lissajous_xy:s=256x256:r=25 [spectrum];[vid1][spectrum]overlay[vo]'
```
The audio file ha album art, and this causes the following in the terminal:
```
[..]
Invalid video timestamp: 0.000000 -> 0.000000
AV: 00:00:00 / 00:03:57 (0%) A-V:  6.528 Dropped: 5848 Cache:  0s+0KB
Invalid video timestamp: 0.000000 -> 0.000000
AV: 00:00:00 / 00:03:57 (0%) A-V:  6.528 Dropped: 5849 Cache:  0s+0KB
Invalid video timestamp: 0.000000 -> 0.000000
AV: 00:00:00 / 00:03:57 (0%) A-V:  6.528 Dropped: 5850 Cache:  0s+0KB
Invalid video timestamp: 0.000000 -> 0.000000
AV: 00:00:00 / 00:03:57 (0%) A-V:  6.528 Dropped: 5851 Cache:  0s+0KB
Invalid video timestamp: 0.000000 -> 0.000000
AV: 00:00:00 / 00:03:57 (0%) A-V:  6.528 Dropped: 5852 Cache:  0s+0KB
Invalid video timestamp: 0.000000 -> 0.000000
AV: 00:00:00 / 00:03:57 (0%) A-V:  6.528 Dropped: 5853 Cache:  0s+0KB
Invalid video timestamp: 0.000000 -> 0.000000
AV: 00:00:00 / 00:03:57 (0%) A-V:  6.528 Dropped: 5854 Cache:  0s+0KB
Invalid video timestamp: 0.000000 -> 0.000000
AV: 00:00:00 / 00:03:57 (0%) A-V:  6.528 Dropped: 5855 Cache:  0s+0KB
Invalid video timestamp: 0.000000 -> 0.000000
AV: 00:00:00 / 00:03:57 (0%) A-V:  6.528 Dropped: 5856 Cache:  0s+0KB
Invalid video timestamp: 0.000000 -> 0.000000
[..]
```
Disabling album art produces the correct result, but without any background.

The issue is the very same when i try to use a static picture as background:
```
mpv audiofile.mp3 --audio-display=no --lavfi-complex='[aid1]asplit[ao][a1]; [a1]avectorscope=m=lissajous_xy:s=256x256:r=25 [spectrum]; movie=/path/to/png/image.png,scale=256x256 [pic]; [pic][spectrum]overlay[vo]' 
```

**Comment by wm4** [comment]
Does it work if you change the order?

**Comment by kokoko3k** [comment]
Swapping the input parameters of the overlay filter make it work, but of course the visualization will be hidden by the album cover.

**Comment by wm4** [comment]
AFAIK the overlay filter uses the first input as "master", which dictates timing, so feeding only a static picture will do nothing. (Although I consider it a bug that it seems to repeat its output and always with the same pts.)

Anyway, both problems are issues in libavfilter.

**Comment by kokoko3k** [comment]
Understood.
Big and dirty workaround by using avectorscope just to have a transparent image with timestamp infos...
```
--lavfi-complex='[aid1]asplit=3[a1][a2][ao];     [a2]adrawgraph=bg=#00000000[blank]; [blank][vid1]overlay[back] ; [a1]avectorscope[sp];[back][sp]overlay[vo]
```

**Comment by richardpl** [comment]
Hmm, perhaps adding loop filter would work for this use case, it would loop single frame only so its ok and with different pts each time.

**Comment by wm4** [comment]
Doesn't sound like the right approach.

One stream is EOF; `overlay` should just use the other stream as master.

**Comment by richardpl** [comment]
I posted patch that appears to fix this, hope it doesn't break anything.

**Comment by richardpl** [comment]
Should be fixed.

**Comment by wm4** [comment]
Closing then.
