### ISSUE TITLE
keep mpv player window in front of other windows at play time.

### ISSUE THREAD

**Issue by noscripter** [mpv-player/mpv#2803]
I think it is convenient to keep the mpv play window in front of all other windows during play time, which is a standard feature too for all other movie players, so I am wondering how to enable this feature in mpv or if this feature is available.

**Comment by wm4** [comment]
--ontop

**Comment by Argon-** [comment]
You can also (de)activate it during runtime by pressing T.
https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L120

**Comment by noscripter** [comment]
Thank you so much, @Argon-  @wm4  I think this should be updated to your document.

**Comment by Argon-** [comment]
It is documented: 
https://mpv.io/manual/master/#keyboard-control
https://mpv.io/manual/master/#options-ontop

**Comment by noscripter** [comment]
@Argon-  nice, thank you.

**Comment by sephrioth** [comment]
@Argon- Is it possible to activate ontop  while playing and deactivate while paused **automatically**?

**Comment by Argon-** [comment]
https://github.com/mpv-player/mpv/wiki/User-Scripts
> ***ontop-playback***
> Disables the ontop property when pausing, and enables it again when unpausing the video, if it was disabled.

**Comment by UnixCro** [comment]
How is it possible that mpv manages that no other window can overlay it? Does it use any terminal command for the `--ontop` parameter?
