### ISSUE TITLE
Feature Request: 60 FPS Integration

### ISSUE THREAD

**Issue by Droyk** [mpv-player/mpv#2804]
You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.

So guys I heard you guys are making a new player so i thought it will be a good idea to integrate 60 fps 
means convert any any 24 or 25 fps video to 60 fps Like SVP ....thanxx for reading guys

**Comment by Cpuroast** [comment]
mpv isn't exactly new, it's been in dev for quite some time, with multiple stable releases.

There's already: https://mpv.io/manual/stable/#video-output-drivers-interpolation

Which isn't motion interpolation like SVP, but helps alot with reducing stuttering caused by mismatches in the video fps and display refresh rate (also known as judder).

**Comment by CrisBRM** [comment]
If you want that, follow this guide https://kaangenc.me/motion-interpolation-24-fps-to-60-fps-with-mpv-vapoursynth-and-mvtools.html

**Comment by Droyk** [comment]
[**@CrisBRM**](https://github.com/CrisBRM) commented on [Feb 10, 2016, 3:33 AM GMT+5:30](https://github.com/mpv-player/mpv/issues/2804#issuecomment-182097991 "2016-02-09T22:03:39Z - Replied by Github Comment Enhancer"):
> If you want that, follow this guide [https://kaangenc.me/motion-interpolation-24-fps-to-60-fps-with-mpv-vapoursynth-and-mvtools.html](https://kaangenc.me/motion-interpolation-24-fps-to-60-fps-with-mpv-vapoursynth-and-mvtools.html)

Problem is I don't any bit of coding's Pretty stupid right I know

**Comment by CrisBRM** [comment]
That doesn't require any programming skills, only that you follow the guide.

**Comment by Droyk** [comment]
[**@CrisBRM**](https://github.com/CrisBRM) commented on [Feb 10, 2016, 4:33 AM GMT+5:30](https://github.com/mpv-player/mpv/issues/2804#issuecomment-182126032 "2016-02-09T23:03:40Z - Replied by Github Comment Enhancer"):
> That doesn't require any programming skills, only that you follow the guide.

I think everything is in codings i didn't even understand what is even written

**Comment by Droyk** [comment]
[**@Cpuroast**](https://github.com/Cpuroast) commented on [Feb 10, 2016, 2:59 AM GMT+5:30](https://github.com/mpv-player/mpv/issues/2804#issuecomment-182080412 "2016-02-09T21:29:12Z - Replied by Github Comment Enhancer"):
> mpv isn't exactly new, it's been in dev for quite some time, with multiple stable releases.
> 
> There's already: [https://mpv.io/manual/stable/#video-output-drivers-interpolation](https://mpv.io/manual/stable/#video-output-drivers-interpolation)
> 
> Which isn't motion interpolation like SVP, but helps alot with reducing stuttering caused by mismatches in the video fps and display refresh rate (also known as judder).

how to play 60 fps on windows

**Comment by Argon-** [comment]
What SVP is on windows is Vapoursynth+MVTools on linux/OSX. However, it is more complex to set up and has worse performance. In most cases the performance will be so bad that you can't use it like you can use SVP. I don't know about the features SVP provides so maybe there are some differences too.

**Comment by Droyk** [comment]
[**@Argon-**](https://github.com/Argon-) commented on [Feb 10, 2016, 1:49 PM GMT+5:30](https://github.com/mpv-player/mpv/issues/2804#issuecomment-182249329 "2016-02-10T08:19:03Z - Replied by Github Comment Enhancer"):
> What SVP is on windows is Vapoursynth+MVTools on linux/OSX. However, it is more complex to set up and has worse performance. In most cases the performance will be so bad that you can't use it like you can use SVP. I don't know about the features SVP provides so maybe there are some differences too.
@Argon- so when do you think interpolation will be god enough for MPV on windows how many days or months it will take to get it done

**Comment by Argon-** [comment]
As far as I know nobody's working on improving the current situation.

**Comment by wm4** [comment]
Didn't pigoz do something into this direction?

**Comment by pigoz** [comment]
@wm4 gave up. mvtools code is incomprehensible.

**Comment by Droyk** [comment]
[**@pigoz**](https://github.com/pigoz) commented on [Feb 11, 2016, 4:03 PM GMT+5:30](https://github.com/mpv-player/mpv/issues/2804#issuecomment-182797606 "2016-02-11T10:33:48Z - Replied by Github Comment Enhancer"):
> [@wm4](https://github.com/wm4) gave up. mvtools code is incomprehensible.

So again i ask do you guys really are doing anything in this direction .....and if you are not when you are gonna do it any approx. time limit :question:

**Comment by wm4** [comment]
Try again in 10 years.

**Comment by Hrxn** [comment]
I like your optimism :smile:

**Comment by wm4** [comment]
It has nothing to do with optimism. I think this feature simply isn't coming into reality because nobody cares (enough).
