### ISSUE TITLE
Audio-codec property unavailable when using A->V lavfi-complex filters

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#2806]
See:
```
# build/mpv /mnt/nas.crypt/Musica/Coldplay\ -\ Mylo\ Xyloto/02-coldplay-hurts_like_heaven.ogg  --term-status-msg='${audio-codec}' --lavfi-complex='[aid1]asplit[ao][a1];[a1]showspectrum[vo]'
[..]
(unavailable)
[..]
# build/mpv /mnt/nas.crypt/Musica/Coldplay\ -\ Mylo\ Xyloto/02-coldplay-hurts_like_heaven.ogg  --term-status-msg='${audio-codec}' 
[..]
Vorbis [lavc:vorbis]
[..]
```

**Comment by wm4** [comment]
Most of these properties don't work, because 1. multiple decoders could be active, and 2. there's no association between the decoders and the properties.

**Comment by kokoko3k** [comment]
Did not understood completely what you mean, i'm not that "in"
Is there a user-level workaround for that?

**Comment by wm4** [comment]
No workaround.

**Comment by wm4** [comment]
At some point, I'll probably add this information to the track-list (so it's possible to handle this with multiple decoders active).

**Comment by kokoko3k** [comment]
Good to hear, thanks.

**Comment by wm4** [comment]
Added this in 0a1e926670a5563df788f9c732a93e3230d86182.
