### ISSUE TITLE
'--vaapi' configure option should allow KMS/DRM as an alternative to x11 and wayland?

### ISSUE THREAD

**Issue by Coacher** [mpv-player/mpv#2808]
Hello.

After 68366b05f283d8f12f5602c74954e2ec986b2f50 vaapi can be used with egl-drm via gbm, but '--vaapi' still requires x11 and wayland exclusively. Shouldn't '--vaapi' requirements be relaxed to account for egl-drm via gbm?

**Comment by wm4** [comment]
Does this fix it?

**Comment by Coacher** [comment]
Yes. Thank you very much.
