### ISSUE TITLE
ffmpeg showfreqs complex filter vs seeking

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#2810]
Seeking with right arrow key after starting mpv the following way is problematic, and the stream go back to the starting position.
```build/mpv /mnt/nas.crypt/Musica/BestOfBowie/CD1/01.Space.Oddity.ogg --lavfi-complex='[aid1]asplit[ao][a1];[a1]showfreqs[vo]'```
I don't know if this is due to mpv or ffmpeg, maybe richardpl will read this...

**Comment by wm4** [comment]
Doesn't happen here, retry with ffmpeg git.

**Comment by wm4** [comment]
It was probably this change: http://git.videolan.org/?p=ffmpeg.git;a=commit;h=4ab4793c155e66ce7845831a5761c2bc0d04b035

**Comment by kokoko3k** [comment]
Confirmed, thank you for pointing it out.
