### ISSUE TITLE
irxevent issue on lircrc

### ISSUE THREAD

**Issue by G500** [mpv-player/mpv#2812]
Hello
I write lircrc for mpv. when i run irxevent it say 

irxevent: bad config string "key / mpv"

my lircrc is :

begin
  prog = irxevent
  button = play-pause
  config = Key space mpv
end

begin
  prog = irxevent
  button = volup
  config = Key 0 mpv
  repeat = 1
  delay = 1
end

begin
 prog = irxevent
 button = voldown
 config = key / mpv
 repeat = 1
 delay = 1
end

only keys 0 and space work key / for volume down doesn't work. where is my mistake on lircrc file?

**Comment by chrisaljoudi** [comment]
This isn't an mpv issue. The correct `config` should be:

```
config = key slash mpv
```

[Here's a list of key names irexec accepts](https://github.com/aldebaran/lirc/blob/master/doc/irxevent.keys).

**Comment by chrisaljoudi** [comment]
@wm4 this isn't an mpv issue (and I've addressed the solution in a comment above).

Letting you know so you can label the issue as not being an mov bug (and potentially close).

**Comment by wm4** [comment]
k
