### ISSUE TITLE
add option to show osd only fullscreen

### ISSUE THREAD

**Issue by manu09** [mpv-player/mpv#2814]
My use case makes no sense to show any osd (while not beeing fullscreen):

```
on-all-workspaces=yes
geometry=25%-25-45
ontop=yes
border=no
```

Please add an option to show the OSD in fullscreen mode only.

**Comment by paulguy** [comment]
I imagine you can script that.  Look in to the stuff mpv has for observing a property.

**Comment by wm4** [comment]
OSD or OSC? Also yes, sounds like something that should be done with a script.

**Comment by lachs0r** [comment]
https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua

**Comment by wiiaboo** [comment]
And if OSC, `showwindowed=no` in `lua-settings/osc.conf`.
