### ISSUE TITLE
playback-time shows wrong value when dropping frames

### ISSUE THREAD

**Issue by zaza42** [mpv-player/mpv#2816]
I'm using mpv on a slow machine, and i've run this bug when i want to control mpv over socket.
When frames are heavily dropped, the playback-time values are the same, while the audio is played correctly without any glitches.
Here's a timestamped output of a script when playing videos:
15:33:56:717558860 n=1 playback-time: 135.568767 time-pos: 135.568767
15:33:57:004333936 n=2 playback-time: 135.835700 time-pos: 135.835700
15:33:57:193298656 n=3 playback-time: 135.835700 time-pos: 135.835700
15:33:57:327817032 n=4 playback-time: 135.835700 time-pos: 135.835700
15:33:57:450125907 n=5 playback-time: 135.835700 time-pos: 135.835700
15:33:57:641603397 n=6 playback-time: 136.236100 time-pos: 136.236100
15:33:57:881318452 n=7 playback-time: 136.236100 time-pos: 136.236100
15:33:58:091646955 n=8 playback-time: 136.236100 time-pos: 136.236100
15:33:58:298760922 n=9 playback-time: 136.236100 time-pos: 136.236100
15:33:58:430438775 n=10 playback-time: 136.236100 time-pos: 136.236100
15:33:58:549841809 n=11 playback-time: 137.003533 time-pos: 137.003533
15:33:58:660210287 n=12 playback-time: 137.003533 time-pos: 137.003533
15:33:58:796975893 n=13 playback-time: 137.003533 time-pos: 137.003533
15:33:58:930969696 n=14 playback-time: 137.003533 time-pos: 137.003533
15:33:59:088378069 n=15 playback-time: 137.003533 time-pos: 137.003533
15:33:59:230142437 n=16 playback-time: 137.971167 time-pos: 137.971167
15:33:59:351776450 n=17 playback-time: 137.971167 time-pos: 137.971167

Is it a bug, or are there any property which contains the audio playback time instead of video?

(i'm using the default video-sync=audio and framedrop=decoder+vo)

**Comment by wm4** [comment]
If both audio and video are active, the video timestamp is used as canonical playback position. It's not possible to get the audio timestamp in this case. I see no problem here.
