### ISSUE TITLE
Wayland backend doesn’t honor the configure event (regression, bisected)

### ISSUE THREAD

**Issue by linkmauve** [mpv-player/mpv#2817]
Since eb6b2b6e50e6e3d3db41190ad818d8b966750734, the Wayland backend (used by vo_opengl and vo_wayland) sends a `set_fullscreen` request in the `configure` event handler.

This prevents alt-tabbing out of mpv in Weston because it will instantly go back to fullscreen, and perhaps more importantly is wrong because a `set_fullscreen` request will trigger a `configure` event, which makes an infinite loop hogging the CPU and GPU.

**Comment by giselher** [comment]
Yeah, sorry about that, I will revert the commit as soon as I have a solution for #2657

**Comment by linkmauve** [comment]
If the issue is support for wl_shell lacking in gnome-shell, the best solution would be 1) to report them a bug about it, so they can fix it, and 2) to move to xdg_shell.
