### ISSUE TITLE
Incorrect channel layout for PCM 3.0

### ISSUE THREAD

**Issue by james-west** [mpv-player/mpv#2819]
mpv is incorrectly identifying PCM 3.0 (fl-fr-fc) as PCM 2.1 (fl-fr-lfe).  I included two samples below from a clip of a Blu-ray rip of Vicky Cristina Barcelona as well as logs when playing the sample with PCM 3.0.  vcb_pcm_3_0.mkv has a PCM 3.0 audio track, and vcb_ac3_3_0.mkv has an AC3 3.0 audio track that I transcoded from the PCM track and which mpv handles correctly.  When playing vcb_pcm_3_0.mkv, the voice-over from the center channel is not audible.  If the command line option "--af=format=s16:48000:2.1:s16:48000:3.0" is added when playing vcb_pcm_3_0.mkv, the audio is played correctly with the center channel audible.

I originally noticed the issue in Plex Media Player and was able to reproduce it in the Windows version of mpv.

I don't believe it's an issue with the source file because MediaInfo shows the channel positions for vcb_pcm_3_0.mkv as "Front: L C R" and the center channel is played correctly by MPC-HC or when transcoded to another surround format by eac3to or Plex.  Even if the source file is quirky, it should at least be possible to handle it.

I'm not sure if this is an issue with mpv itself or if an underlying library, such as FFmpeg or Libav, is used to get the channel layout.

[vcb_pcm_3_0.zip](https://github.com/mpv-player/mpv/files/129464/vcb_pcm_3_0.zip)

[vcb_ac3_3_0.zip](https://github.com/mpv-player/mpv/files/129463/vcb_ac3_3_0.zip)

[vcb_pcm_3_0.mkv.log.txt](https://github.com/mpv-player/mpv/files/129471/vcb_pcm_3_0.mkv.log.txt)

**Comment by wm4** [comment]
This file basically uses a hack: it's muxed via AVI compatibility, and sneaks in a channel layout via the WAVEFORMATEXTENSIBLE header. But it's supported by most things these days, and adding support should be pretty easy. I'll have a look tomorrow.

**Comment by wm4** [comment]
Implemented it now, via fa821de8b2b11c0c5e378342e0d56d16366cd96f. (Accidentally put wrong issue number.)
