### ISSUE TITLE
Can't open external .ass file headed with some empty lines.

### ISSUE THREAD

**Issue by seabao2k16** [mpv-player/mpv#2821]
The mpv console reports 'Can not open external file xxxxx.ass', when the subtitle file headed with some empty lines. The attach file is sample subtitle file.
[sample-ass.zip](https://github.com/mpv-player/mpv/files/129635/sample-ass.zip)

**Comment by wm4** [comment]
Should work in ffmpeg 3.0.

**Comment by yshui** [comment]
I'm seeing a similar bug.

mpv can not open ass files that start with a white space. ffmpeg version is 3.2

**Comment by wm4** [comment]
Report it to ffmpeg, with a sample file.
