### ISSUE TITLE
can't play internet radio

### ISSUE THREAD

**Issue by gthreepw00d** [mpv-player/mpv#2824]
http://livestream.rfn.ru:8080/kulturafm/mp3_64kbps
mpv 0.15
Playable with ffplay (2.6.8) or vlc 2.2.

**Comment by wm4** [comment]
Works perfectly fine here?

**Comment by gthreepw00d** [comment]
Issue is cache-initial=2000 in my config

**Comment by wm4** [comment]
Nothing changed about this.

**Comment by gthreepw00d** [comment]
Sorry, everything is ok, closing.
