### ISSUE TITLE
opengl-hq debanding doesn't work with OS X hwdec (videotoolbox)

### ISSUE THREAD

**Issue by kiririn** [mpv-player/mpv#2831]
Not sure if it's even supposed to work but examples are below. I took the screenshots with Ctrl+s.

With hwdec:
mpv \[HorribleSubs\]\ Non\ Non\ Biyori\ Repeat\ -\ 04\ \[720p\].mkv --no-config --start=14:39 --pause  --vo=opengl-hq --hwdec=auto
https://my.mixtape.moe/jmoyja.jpg

Without:
mpv \[HorribleSubs\]\ Non\ Non\ Biyori\ Repeat\ -\ 04\ \[720p\].mkv --no-config --start=14:39 --pause --vo=opengl-hq
https://my.mixtape.moe/bijans.jpg

Version: mpv git-0af5335

**Comment by wm4** [comment]
It's supposed to work.

What about `mpv file.mkv --vf=format=nv12 --vo=opengl-hq`?

**Comment by kiririn** [comment]
> What about mpv file.mkv --vf=format=nv12 --vo=opengl-hq?

That doesn't really do anything that I can see but if I add `--hwdec=auto` I get this:

Opening video filter: [format fmt=nv12]
AO: [coreaudio] 44100Hz stereo 2ch floatp
Using hardware decoding (videotoolbox).
Using conversion filter.
Image formats incompatible or invalid.
Video filter chain:
  [in] 1280x720 videotoolbox bt.709/limited CL=mpeg2/4/h264
  [scale] ??? [a]   <---
  [format] ???
  [out] ???
Falling back to software decoding.
[ffmpeg/video] h264: co located POCs unavailable
[ffmpeg/video] h264: reference picture missing during reorder
[ffmpeg/video] h264: Missing reference picture, default is 8
Using conversion filter.
VO: [opengl-hq] 1280x720 nv12

**Comment by wm4** [comment]
Anyway, post log with -v and videotoolbox.

**Comment by kiririn** [comment]
Log: http://sprunge.us/dgaQ

**Comment by wm4** [comment]
Without the vf-format please.

**Comment by kiririn** [comment]
Here: http://sprunge.us/KIVQ

**Comment by wm4** [comment]
Thanks. The output looks as expected, so I suspect a subtle issue with the use of texture rectangles. (The only thing different to the sw case.)
