### ISSUE TITLE
video sync issues playing mpegts streams

### ISSUE THREAD

**Issue by bmentink** [mpv-player/mpv#2833]
Hi,
I am having large sync issues (video lagging audio by >10 seconds) when playing a mpegts stream from mumudvb.... and very jerky video, audio ok.

Some suspect entries in the log:

**ffmpeg/demuxer: mpegts: parser not found for codec none, packets or times may be invalid.**

I have no problems playing other IPTV streams using this container:
**ffmpeg/demuxer: hls,applehttp**

The problem is only with mpegts

PS: This is on linux.

Contents of my mpv.conf is:

```
vo=vaapi
hwdec=vaapi
keepaspect=no
softvol=yes
softvol-max=1000
hwdec-codecs=all

```

**Comment by wm4** [comment]
Needs sample.

**Comment by bmentink** [comment]
Sample of what? The log or the data?

**Comment by wm4** [comment]
Data.

**Comment by bmentink** [comment]
Ok, will try and save a portion of the stream when I get home tonight .. where can I put it?

**Comment by wm4** [comment]
Anywhere you like, as long as it's accessible.

**Comment by bmentink** [comment]
Here is the 1st few seconds of play:
https://drive.google.com/file/d/0B8M0Ic6LRtOzSWtZU2U5bmVzWmM/view?usp=sharing

**Comment by bmentink** [comment]
Here is the console output for the above file:
[error.txt](https://github.com/mpv-player/mpv/files/135588/error.txt)

**Comment by wm4** [comment]
Can't see any issues when playing that sample.

**Comment by bmentink** [comment]
Did you not get any sync issues? I am surprised, I recorded that as I was playing and had lot's of issues ..... what are your comments on the console output I posted?

**Comment by wm4** [comment]
Did you try to play your own sample?

**Comment by bmentink** [comment]
No, will try that at home.

So, you havn't answered my questions on those errors ......

What version of ffmpeg are you running, mine is 2.8.6

`ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libdcadec --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-shared --enable-version3 --enable-x11grab
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
`

**Comment by wm4** [comment]
The errors just mean that the stream most likely was cut off at a certain point, not unusual for broadcast, especially on channel switching/initial playback.

**Comment by bmentink** [comment]
Please answer my question of ffmpeg version .... it will help me track this down, especially  if I know what your setup is and how it differs from mine .. 

None of the above  is helping me resolve this at the moment ..

**Comment by wm4** [comment]
git master, and I'm getting the errors too. The sample seems to be mostly in sync. I suspect there were enough errors in your stream to disrupt mpv's A/V sync, but it's not in the sample you posted.

**Comment by bmentink** [comment]
I will get you a better sample ...

**Comment by bmentink** [comment]
Hi,

I think I know what the issue is. MPV does play the video fine as long as I tell it to use vaapi as the video out and decode module. So it is a playback issue, not an mpv or ffmpeg issue.

I ran into this problem while using the IPTV.bundle in plex. For some reason, when playing the same stream in plex, the hardware accelleration vaapi options are ignored  for mpegts even though they are used for other video containers like hts,applehttp ...

Can you tell me why this could be happening (I think you are on the plex forum as well)
Hope you can help, I don't know if this is a plex issue or IPTV.bundle issue ..

**Comment by wm4** [comment]
I think the decoding errors just disable hardware decoding sometimes early on. So if you don't get errors, it keeps decoding fine. Which means hardware decoding actually has nothing to do with it.

**Comment by lachs0r** [comment]
I can’t reproduce this with my DVB-S2 hardware. What I do know however is that many home routers will start dropping packets randomly if you attempt to multicast on the LAN. Some even drop WiFi connections entirely (while the multicast source is connected via Ethernet).

I suggest trying TVHeadend as the streaming source instead. It has been working much better than mumudvb in my experience anyway.
