### ISSUE TITLE
[low-priority feature request] Add a Vulkan (vk) rendered video output

### ISSUE THREAD

**Issue by mpvOWNZ** [mpv-player/mpv#2837]
I already know this will take some time to materialize, but nevertheless it would be very interesting to see, even if for nothing else than to compare the performance, vsync timings and latency of OpenGL vs. Vulkan!

**Comment by mpvOWNZ** [comment]
Here is something interesting from the "RetroArch" developers who already have implemented Vulkan support:

> When you have ‘logging enabled’ in RetroArch, it will always report frame time deviations at application exit inside the terminal. They are much lower with Vulkan than they ever were in GL. Frame time deviations as low as 0.005% and 0.035% are pretty much expected, with GL you could only dream of such low figures.

Because of these much lower deviations and because of much better control over buffer swap management (see point 3), audio/video sync is just so much nicer.

[http://www.libretro.com/index.php/vulkan-progress-report-and-initial-impressions/](url)

**Comment by wm4** [comment]
Maybe or maybe not, but no reason to keep this open.
