### ISSUE TITLE
dxva2: failed except used with backend=dxinterop

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#2844]
Here is the sample file:
https://a.pomf.cat/cwwlxe.mkv

when tried with `--hwdec=dxva2` it failed. But using `--hwdec=dxva2-copy` works as expected
[log.txt](https://github.com/mpv-player/mpv/files/138401/log.txt)

strangely if I explicitly used `backend=dxinterop` with `hwdec=dxva2`, it works with both intel and nvidia

**Comment by wm4** [comment]
That's expected.

**Comment by wm4** [comment]
PS: how does it behave with ``--hwdec=auto``? If everything works right, it should select the best method.

**Comment by shinchiro** [comment]
nope, it still failed with `--hwdec=auto`

**Comment by wiiaboo** [comment]
`--vo=opengl=backend=win --hwdec=auto`: [failed](https://j.fsbn.eu/KTHl.txt)
`--vo=opengl=backend=dxinterop --hwdec=auto`: [failed](https://j.fsbn.eu/1cym.txt)
`--vo=opengl=backend=angle --hwdec=auto`: [failed](https://j.fsbn.eu/tv87.txt)
`--vo=opengl=backend=win --hwdec=dxva2-copy`: [success](https://j.fsbn.eu/71mW.txt)
