### ISSUE TITLE
[suggestion] screenshot-template options with Youtube Streams

### ISSUE THREAD

**Issue by marteaurouge** [mpv-player/mpv#2847]
It would be handy to have options to set a custom screenshot-template used when playing Youtube Streams using:

- the title (which is displayed on the player)
- the unique id of the video

**Comment by wm4** [comment]
Lua can use a Lua script to change the template dynamically, or even use the screenshot-file command.

The title can be accessed via property access. The video ID is a youtube-specific concept and too special.
