### ISSUE TITLE
Feature Request: Hotkey for toggling the GLSL debanding filter

### ISSUE THREAD

**Issue by CounterPillow** [mpv-player/mpv#2852]
The `opengl-hq` output enables the GLSL debanding shader by default. However, depending on the video content, this is not always what a user may wish to use.

A hotkey to toggle the debanding filter on and off would save me the trouble of having to change this setting outside of mpv all the time. In that case, I could use `opengl-hq:deband=no` and simply hit a hotkey when I feel like I need the debanding filter.

**Comment by kevmitch** [comment]
I know this isn't the greatest solution, but until the option system is made more flexible I think we're stuck with using the following ```input.conf```:

    b vo-cmdline deband
    shift+b vo-cmdline deband=no

The real problem with this is if you aren't just using vo=opengl-hq, then you have to duplicate your full vo cmdline in your ```mpv.conf``` as well as in both those bindings modulo debanding.

**Comment by Hrxn** [comment]
Just out of curiosity, could you give me an example where a user might want to disable the debanding filter? Because I can't think of any right now, in my opinion debanding is basically always an improvement, with the exception of dire performance constraints.

**Comment by kevmitch** [comment]
I haven't tested myself, but I understand it can perform badly on grainy material. But the most significant consideration for me is to reduce power usage on battery. debanding takes more wattage than all the other opengl-hq options combined.

**Comment by CounterPillow** [comment]
@Hrxn on my intel integrated GPU, performance is the main concern. intel_gpu_top shows it to affect usage into the range of over 10% from a quick test, which depending on the hardware and situation can be enough to either drop frames or have the GPU raise its clockrate, drawing more power.

Simply put: If I do not notice any banding, I do not need the debanding filter.

**Comment by Zehkul** [comment]
> Just out of curiosity, could you give me an example where a user might want to disable the debanding filter?

It’s not just about disabling it, some sources are so shitty you want to use debanding with insane settings that would needlessly destroy a ton of detail on better video files. (The new [Utawarerumono](http://i.imgur.com/iW2ebOQ.jpg) for example)

Debanding with different strengths currently makes your input.conf extremely messy, even more so if you also want to enable/disable/change things like tscale depending on the source.

**Comment by wm4** [comment]
Exposing the opengl suboptions directly and making them changeable as normal properties is still on my todo list.

**Comment by CounterPillow** [comment]
This is resolved now, since you can do it easily these days. Thanks!

**Comment by haasn** [comment]
For the record, the relevant keybinding looks like `d cycle deband`
