### ISSUE TITLE
[Windows 7 x64] Stutter on minimize/restore of any window

### ISSUE THREAD

**Issue by maniak1349** [mpv-player/mpv#2853]
When any window (not only mpv ones) got minimized/restored playback is stuttering for the duration of resizing. For example in older versions (build 2014-08-27) video was stuttering too, but audio and owerall playback progression was not.

**Comment by lachs0r** [comment]
Can you try with `--vo=opengl:backend=dxinterop`?

**Comment by maniak1349** [comment]
Tried with `--vo=opengl:backend=dxinterop` - same stutter. If it will be of any help - aero is disabled and I'm using classic windows theme.

**Comment by lachs0r** [comment]
It’s quite likely that Aero will help if you use dxinterop.

**Comment by maniak1349** [comment]
With enabled aero theme there is no stutter with and without dxinterop. Is there any chance for a fix for classic theme though?

**Comment by lachs0r** [comment]
I don’t think so. Also, newer versions of Windows always enable the compositor anyway (sarcastic reminder that Windows 7 is the new XP).

**Comment by kevmitch** [comment]
I can attest that contrary to intuition, keeping the compositor out of the equation actually makes graphics performance worse (at least on intel). It's just too ingrained in the way windows works I guess. Note that the Intel drivers turn aero on by default when you install them suggesting that they probably aren't designed to be used without.

**Comment by maniak1349** [comment]
Audio/playback stutter seems to be fixed in the latest builds. So I guess this issue can be closed.

Simplest way to get rid of video stutter seems to be to disable minimization animation in the visual effects tab of the performance options dialog. But I'm ok with the way it is now - it's not like you paying attention to the video when you shuffling your windows around anyway.

About reasons of video stutter - it seems that in classic theme whenever any window is in process of minimization/restore animation event processing for every window will be stopped for that duration. So every thread that calls `GetMessage` or `SendMessage` will stop and wait 'till the animation ends. And without event processing you cannot update the contents of the window. So there is probably no simple solution if there is one at all.
