### ISSUE TITLE
Is it possible to add new feature into mpv?

### ISSUE THREAD

**Issue by wasp71** [mpv-player/mpv#2860]
Hi all!
A very useful feature in the mpv: --title="window title"!
In the settings menu (for example, Xfce) you can link needed icon for a specific application,
something like this:

$ cat TV::1+1.desktop 
[Desktop Entry]
Name=1+1
Comment=1+1
Exec=mpv --title=1+1 -cache-initial=2000 http://tv.lan.ua/get_stream.php?id=1
Icon=/home/admin/Icons/1plus1.png
Terminal=0
Type=Application
Categories=X-TV

Is it possible to change the default icon mpv player (in the title bar)
on other icon from another location (for example, from *.desktop file)?

**Comment by wasp71** [comment]
The question remains open ...

**Comment by wm4** [comment]
I don't quite understand what you mean. The X11 window icon is provided by applications, and in mpv is hardcoded. It can't be changed without messing with the source and recompiling.

**Comment by wasp71** [comment]
If "in mpv is hardcoded", the question is closed.
Thanks.

**Comment by Hrxn** [comment]
Is there something like Resource Hacker for Linux binaries (ELF)?

Might be an option here, but I don't know anything reliable here.
