### ISSUE TITLE
Compatibility with ffmpeg 3.0

### ISSUE THREAD

**Issue by nivekuil** [mpv-player/mpv#2862]
ffmpeg 3.0 is in Arch Linux's testing repository now, and provides these newer versions of the following libraries: libavutil.so.55, libavcodec.so.57, libavformat.so.57, libswscale.so.4, libavfilter.so.6, libavdevice.so.57, and libswresample.so.2. mpv should be updated to load the newer versions.

**Comment by wm4** [comment]
Done.
