### ISSUE TITLE
2016.02.23 update - does Not play .flv files

### ISSUE THREAD

**Issue by LandisTwo** [mpv-player/mpv#2865]
Hello,
as of 2016.02.23 packman update of mpv, SMPlay will Not play .flv (flash) files saved locally. I'm using opensuse 13.2, KDE 4x and my media (smplay, mpv, gstrearmer etc) repos are from  Packman at uni-erlangen.de
There are no 'saved' or available, back version (earlier versions) in packman repo, so 'downgrading' mpv, smplayer is not easily done.
Thanks, Landis.

as per your bug reporting I tried ffplay from terminal, based on same ffmpeg libs and the .flv files play. I don't have avplay.

MPV and SMPlayer (based on mpv) does not play flv files
 - smplayer fails with Exit code 2, mpv just doesn't start.

ffplay, VLC, Kaffine and MPlayer will play the save flv files.

stacktrace: (problem is with All .flv files, Not just this sample file)
`landis@linux-e6420:~/Working01> gdb mpv
GNU gdb (GDB; openSUSE 13.2) 7.8
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...

warning: /etc/gdbinit.d/gdb-heap.py: No such file or directory
Reading symbols from mpv...(no debugging symbols found)...done.
Missing separate debuginfos, use: zypper install mpv-debuginfo-0.15.0-38.10.x86_64
(gdb) run --no-config Bangkok.flv
Starting program: /usr/bin/mpv --no-config Bangkok.flv
Got object file from memory but can't read symbols: File truncated.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffdd658700 (LWP 20098)]
[New Thread 0x7fffdce57700 (LWP 20099)]
[New Thread 0x7fffd7fff700 (LWP 20100)]
Playing: Bangkok.flv
[New Thread 0x7fffd77fe700 (LWP 20101)]
[Thread 0x7fffd77fe700 (LWP 20101) exited]
Failed to recognize file format.

Exiting... (Errors when loading file)
[Thread 0x7fffdce57700 (LWP 20099) exited]
[Thread 0x7fffdd658700 (LWP 20098) exited]
[Thread 0x7fffd7fff700 (LWP 20100) exited]
[Inferior 1 (process 20094) exited with code 02]
(gdb)
`
Landis.

**Comment by LandisTwo** [comment]
i installed from opensuse/ropos/multimedia/apps:
mpv 15.0-40.1-x86x64
and from opensuse/repos/kde-extra/
smplayer 16.1.0-10.2-86x64
instead of those offered by packman/uni/ repos.
and have the same Exit code 2 using smplayer and nothing loading using mpv
Landis.

**Comment by LandisTwo** [comment]
I downgraded mpv from http://download.opensuse.org/distribution/leap/42.1/repo/oss/suse/ to Version 0.11.0 built Sep 23 2015 ...
MPV and SMPlayer Work with this downgraded version.
Landis.
p.s. I did Not downgrade SMPlayer.

**Comment by lachs0r** [comment]
SMPlayer is not supported.

**Comment by lachs0r** [comment]
Also, make sure FFmpeg libraries also come from Packman (there’s a publishing freeze right now so that might be broken… wait for a bit or use mpv-build).

mpv does not use GStreamer.

**Comment by LandisTwo** [comment]
Hello lachs0r.
what do you mean by 'smplayer is not supported'?
you don't support smplayer (i get that, this is github for mpv)
or - that smplayer doesn't use mpv (because it Does use mpv as it's 'engine' backend)
Again, the version (15.38) from packman is what is Not working (does not play .flv).
I wasn't saying gstreamer was involved, only that i was getting most all my non-ffmpeg/mpv files from opensuse/multimedia and not packman.
My ffmpeg packages/libraries are coming from Packman.

Thanks, Landis.

**Comment by LandisTwo** [comment]
2016.04.18 - 
this is the 3rd system I've had this Exact same problem with.
Only 11.x from sucky Leap 42.1 repo will work on a fresh 13.2 install.
Just say'n
