### ISSUE TITLE
Problem mpv don't show some subtitles (SRT)

### ISSUE THREAD

**Issue by latot** [mpv-player/mpv#2869]
Hi, well the problem is seems mpv or something skip some subtitles, someones show and others not.
I don't know when this starts but before works fine.

An example log: https://gist.github.com/latot/c681482bd998236f014d
An example subtitle: [01.srt.zip](https://github.com/mpv-player/mpv/files/147182/01.srt.zip)

I use Gentoo 64

**Comment by wm4** [comment]
ffmpeg is breaking your subs. I've tried to convince ffmpeg to remove the check, but they're not willing.

**Comment by latot** [comment]
D:

well so maybe an solution can be this, at least while we wait solve via ffmpeg.

some subtitles start with this symbols: ï»¿1 if we replace it with 1 start working again.

**Comment by wm4** [comment]
By the way, you might want to try compiling with uchardet; it seems to detect this correctly.

**Comment by latot** [comment]
Hi, just finished test uchardet but sadly the problem persist D:
(tested with uchardet 0.0.1 and 0.0.5)
```
[statusline] AV: 00:01:14 / 00:41:40 (2%) A-V:  0.000
[ffmpeg] srt: Invalid UTF-8 in decoded subtitles text; maybe missing -sub_charenc option
[sub/ass] Error decoding subtitle
[statusline] AV: 00:01:16 / 00:41:40 (3%) A-V:  0.000
[ffmpeg] srt: Invalid UTF-8 in decoded subtitles text; maybe missing -sub_charenc option
[sub/ass] Error decoding subtitle
[statusline] AV: 00:01:17 / 00:41:40 (3%) A-V:  0.000
[ffmpeg] srt: Invalid UTF-8 in decoded subtitles text; maybe missing -sub_charenc option
[sub/ass] Error decoding subtitle
[statusline] AV: 00:01:19 / 00:41:40 (3%) A-V:  0.000
[ffmpeg] srt: Invalid UTF-8 in decoded subtitles text; maybe missing -sub_charenc option
[sub/ass] Error decoding subtitle
```

a little mistery, or an message bug, wy say "sub/ass" if is a srt?

**Comment by wm4** [comment]
Works for me. Do you force the --subcp option?

**Comment by latot** [comment]
no

**Comment by latot** [comment]
D:
mkvmerge add that symbols to the srt....

**Comment by wm4** [comment]
Oh wait, I thought it was an external subtitle, because the sample file you posted was.

If it's muxed in mkv, then 1. it's definitely broken, 2. it's definitely only possible to work it around by modifying ffmpeg.

**Comment by wm4** [comment]
And 3., it's a mkvmerge bug too.

**Comment by wm4** [comment]
Which mkvmerge version did this?

**Comment by latot** [comment]
well, i test now with external subs, and works, not fine but better that merged, with external change/add more wird symbols like:

![captura de pantalla de 2016-02-25 18-16-50](https://cloud.githubusercontent.com/assets/10523095/13334669/fb030a8e-dbeb-11e5-80ba-06a9efab55c0.png)

i'm using libmatroska 1.4.4 and mkvtoolnix 8.9.0, i can confirm in that version exist the bug, and probably some oldest too.

**Comment by latot** [comment]
hi, from the issue: https://github.com/mbunkus/mkvtoolnix/issues/1615#issuecomment-189002583
the behavior its correct in mkvmerge, it uses this: https://en.wikipedia.org/wiki/Byte_order_mark

so basically the problem is ffmpeg don't support BOM files (files with that weird symbols).

its posible disable BOM from mpv at least while ffmpeg can support it?
because actually we can't reproduce that subs...

**Comment by wm4** [comment]
You'll have to be clearer about expected/unexpected behavior, and maybe post sample files.

**Comment by latot** [comment]
okis, first in mkvmerge it use BOM (By Order Mark) files, that means, if you send to the input:
```
1
00:01:05,703 --> 00:01:07,038
Hola. Me llamo Heather.
```
mkvmerge should add the BOm chars to this, so the result is:
```
ï»¿1
00:01:05,703 --> 00:01:07,038
Hola. Me llamo Heather.
```
more info in the wiki link in the previus message.
that its fine

now, ffmpeg don't supports this so its breaks when it found it.

now don't have to much sense leave this problem because ffmpeg don't wanna support it, so an option should be disable BOM from mpv to can reproduce correctly the files (remove that chars).

**Comment by wm4** [comment]
ffmpeg definitely supports the BOM.

**Comment by latot** [comment]
but if support it why all this problem D:

**Comment by czarkoff** [comment]
I guess ffmpeg supports BOM only for encodings where BOM exists - UCS-2, UCS-4 and UTF-16. There is no byte order in utf-8, so U+FEFF should always interpreted as **zero-width non-breaking space** there. Inserting it into UTF-8-encoded SRT breaks the format. So this is definitely a bug in mkvmerge.

That said, @latot, this particular issue happens because you use UTF-8 locale and don't specify encoding to mkvmerge, so it assumes that your subtitle file is encoded with UTF-8. But your subtitle file is encoded in ISO-8859-1, and thus is not a valid UTF-8 byte stream. Try specifying encoding explicitly or converting file to UTF-8.

Anyway, this doesn't seem to be mpv bug.

**Comment by wm4** [comment]
What the heck are you guys talking about? FFmpeg does recognize and skip the BOM.

I'm not going to guess what the fuck is supposed to be the bug here, so either post a sample file or go away.

**Comment by latot** [comment]
[a.mkv.zip](https://github.com/mpv-player/mpv/files/148125/a.mkv.zip)

Hi here a video example with the subtitle uploaded here (black screen), there you can see and compare missed subs.

**Comment by czarkoff** [comment]
@latot: indeed, your ISO-8859-1 subrip file was muxed into Matroska file as UTF-8:
```
ddc@e325:~ $ mkvinfo tmp/a.mkv 
+ EBML head
|+ EBML version: 1
|+ EBML read version: 1
|+ EBML maximum ID length: 4
|+ EBML maximum size length: 8
|+ Doc type: matroska
|+ Doc type version: 4
|+ Doc type read version: 2
+ Segment, size 145920
|+ Seek head (subentries will be skipped)
|+ EbmlVoid (size: 4029)
|+ Segment information
| + Timecode scale: 1000000
| + Muxing application: libebml v1.3.3 + libmatroska v1.4.4
| + Writing application: mkvmerge v8.9.0 ('Father Daughter') 64bit
| + Duration: 240.000s (00:04:00.000)
| + Date: Fri Feb 26 11:53:07 2016 UTC
| + Segment UID: 0x9c 0xf4 0xe2 0x50 0x1f 0x0e 0xa5 0x27 0x7f 0x58 0xf1 0x87 0xd2 0x80 0xce 0x87
|+ Segment tracks
| + A track
|  + Track number: 1 (track ID for mkvmerge & mkvextract: 0)
|  + Track UID: 1
|  + Track type: video
|  + Lacing flag: 0
|  + MinCache: 1
|  + Codec ID: V_MPEG4/ISO/AVC
|  + CodecPrivate, length 42 (h.264 profile: High @L1.3)
|  + Default duration: 40.000ms (25.000 frames/fields per second for a video track)
|  + Language: und
|  + Video track
|   + Pixel width: 320
|   + Pixel height: 240
|   + Display width: 320
|   + Display height: 240
| + A track
|  + Track number: 2 (track ID for mkvmerge & mkvextract: 1)
|  + Track UID: 8031993931144508220
|  + Track type: subtitles
|  + Lacing flag: 0
|  + Codec ID: S_TEXT/UTF8   # Here is your problem
|  + Language: und
|+ EbmlVoid (size: 1090)
|+ Cluster
```
I extracted streams, removed "BOM", converted subrip to UTF-8 and remuxed:
```
ddc@e325:~/tmp/mpv $ mkvextract tracks a.mkv 0:video.mkv 1:subrip-garbled.srt
Extracting track 0 with the CodecID 'V_MPEG4/ISO/AVC' to the file 'video.mkv'. Container format: AVC/h.264 elementary stream
Extracting track 1 with the CodecID 'S_TEXT/UTF8' to the file 'subrip-garbled.srt'. Container format: SRT text subtitles
Progress: 100%
ddc@e325:~/tmp/mpv $ dd if=subrip-garbled.srt bs=1 skip=3 | iconv -f ISO-8859-1 > subrip.srt
251+0 records in
251+0 records out
251 bytes transferred in 0.002 secs (112708 bytes/sec)
ddc@e325:~/tmp/mpv $ mkvmerge -o a2.mkv video.mkv subrip.srt 
mkvmerge v8.8.0 ('Wind at my back') 64bit
'video.mkv': Using the demultiplexer for the format 'AVC/h.264'.
'subrip.srt': Using the demultiplexer for the format 'SRT subtitles'.
'video.mkv' track 0: Using the output module for the format 'AVC/h.264 (unframed)'.
'subrip.srt' track 0: Using the output module for the format 'text subtitles'.
The file 'a2.mkv' has been opened for writing.
'video.mkv' track 0: Extracted the aspect ratio information from the MPEG-4 layer 10 (AVC) video data and set the display dimensions to 320/240.
Progress: 100%
The cue entries (the index) are being written...
Muxing took 0 seconds.
```
The resulting file plays nicely in mpv, subs render.

Now, it is not mpv's or ffmpeg's job to fix charset issues in your subtitles. So mpv's behavior in this case is exactly right.

**Comment by latot** [comment]
okis thx the help :D

**Comment by wm4** [comment]
All mkv subtitles are forcibly UTF-8.
