### ISSUE TITLE
Backwards relative seeks on external audio files temporarily lose audio

### ISSUE THREAD

**Issue by moldpiss** [mpv-player/mpv#2870]
Video plays silently for 1-10 seconds after performing a relative backwards seek on any file with an external audio track selected. Exact backwards seeks don't produce this.

**Comment by wm4** [comment]
That's a known problem and comes from the fact that the video track seeks to an earlier position than the audio because of key-frame snapping. Use hr-seeks to work it around.

**Comment by moldpiss** [comment]
Non-hr seeks work as requested on external audio tracks. Tested build on commit 469666b75bdf336f6c263faa313d46f5684cc577.

Keep up the good work. I enjoy reading the comments you leave on your commits.
