### ISSUE TITLE
Playing realtime stream with mpv - freezing?

### ISSUE THREAD

**Issue by MikeStros** [mpv-player/mpv#2871]
Hello.
I'm trying to use mpv player instead of mplayer in my smart home project. Mpv have much more useful features and i want to say thanks to all mpv developers.

Now i'm trying to watch close-to-realtime TCP video stream with mpv. I'm using "--untimed" option to display video frames as fast as they comes to stdin (or pipe). But there is a problem - when player runs out of cache data and start to play realtime, video begins to freeze for a moment. I read mpv manual, tried different cache options, different video outputs etc... Without any improvement. 

Seems like mpv have some kind of input buffer and video freezes while it's filling. When I increase input video bitrate, freezing become smaller. At bitrate about 6 Megabit/second freezing almost gone away.

When using mplayer in same way, realtime video plays smooth without freeze.
I recorded sample video to show the problem. Bitrate of incoming stream is 500 kBit/sec

mpv https://www.youtube.com/watch?v=GYNBt8gXeQ0
mplayer https://www.youtube.com/watch?v=-s0tEMv1RS8

Please, help me to deal with this problem. May be there is some option in mpv source code which can help me to play such stream smooth?
Thank you!

**Comment by wm4** [comment]
Does ``--no-cache-pause`` help?

**Comment by MikeStros** [comment]
Just tried it. No, it does not help.

**Comment by MikeStros** [comment]
When using --cache=xx option, we can see what happens with cache:
https://www.youtube.com/watch?v=ixxHoijPeW8
Video plays when "Cache: ???+0KB" and stops when cache shows 0S and >0KB

**Comment by wm4** [comment]
Well, without a way to reproduce it...

**Comment by MikeStros** [comment]
I made simple Qt application for windows which streams short video file (test.264) on 10000 tcp port. It sends 700 bytes to socket every 10ms (about 550 kBit/sec stream). Video plays once, to repeat video you need connect to port again.

Mplayer and MPV player work the same as reading from real TCP camera stream - mplayer plays almost smooth and mpv freezes.

Here is how it looks like on my PC:
mplayer https://youtu.be/qYplGDRkCvY
mpv https://youtu.be/fzcvrF_szbg

I uploaded .rar archive with test application here http://dropmefiles.com/fKNbk
For tests windows version of netcat is needed. It's here https://eternallybored.org/misc/netcat/netcat-win32-1.11.zip

**Comment by wm4** [comment]
>I uploaded .rar archive with test application here http://dropmefiles.com/fKNbk

That's a binary executable.

**Comment by MikeStros** [comment]
> That's a binary executable.

When i press download, it's downloading my stream_test.rar file
Sent duplicate to your profile e-mail

**Comment by MikeStros** [comment]
Also shared it on Google drive https://drive.google.com/file/d/0Bx_oedf8MUK1Z1ZjODNNSi1Gems/view?usp=sharing

**Comment by wm4** [comment]
Easier test method please. I'm not going to run some Qt program.

**Comment by lachs0r** [comment]
Well, looks like we won’t get either a better test method or the source code to that program.

**Comment by rgaufman** [comment]
I'm seeing the same, a live RTSP stream freezes, my command is:

```
DISPLAY=:0 mpv --no-cache --keep-open --hwdec=vdpau --hwdec-codecs=all --vo=vdpau --cache-secs=0 --demuxer-readahead-secs=0 --no-cache-pause rtsp://127.0.0.1:10108/proxyStream
```

**Comment by thutex** [comment]
adding to these comments that i am also seeing a freeze when running 4 streams. 3 of them freeze at a random point in time, and dont come back while the last one keeps running. restarting mpv fixes all 4 for a random time
