### ISSUE TITLE
OSD only shows symbols (no progress bar etc)

### ISSUE THREAD

**Issue by bakteria1** [mpv-player/mpv#2874]
I just got a new laptop and installed mpv on it. Identical config files, and identical versions, running on the same operating system. (arch)
But I cannot get the progress bar to show at all. Same when I try and change volume.

**Comment by andreaskem** [comment]
Missing font? I see that the Arch package does not pull in ttf-font, maybe you need one?

**Comment by bakteria1** [comment]
It does, but its called noto-fonts instead. 
I've been trying to troubleshoot this since last night with the help of the irc-channel. And were all stumped. 
I have also tried to force fonts with --osd-fonts='Cantarell' but the fonts never even get called on. When I look at mpv -v during playback. Only the symbols gets called on.
This is all the OSD I get: http://imgur.com/a/atrga

**Comment by bakteria1** [comment]
It was the font. Installed ttf-dejavu and it worked right away. 
Thanks!
