### ISSUE TITLE
error when building with mxe environment

### ISSUE THREAD

**Issue by artynet** [mpv-player/mpv#2879]
i have just bumped into this error whan compiling the latest trunk :
```
../video/out/opengl/context_dxinterop.c:19:28: fatal error: versionhelpers.h: No such file or directory
 #include <versionhelpers.h>
                            ^
compilation terminated.

Waf: Leaving directory `/home/arturo/MPV/mpv/build'
Build failed
 -> task in 'objects' failed (exit status 1):
        {task 140371073332688: c context_dxinterop.c -> context_dxinterop.c.14.o}
['/home/arturo/MPV/mxe/usr/bin/x86_64-w64-mingw32.static-gcc', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-D_WIN32_WINNT=0x0601', '-DUNICODE', '-DCOBJMACROS', '-U__STRICT_ANSI__', '-municode', '-D__USE_MINGW_ANSI_STDIO=1', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-isystem', '/home/arturo/MPV/mpv/osdep/win32/include', '-I', '/home/arturo/MPV/mpv/osdep/win32/include', '-DIN_WINPTHREAD', '-mwindows', '-mconsole', '-mwindows', '-mconsole', '-mwindows', '-mwindows', '-mconsole', '-mms-bitfields', '-I/home/arturo/MPV/mpv/build', '-I/home/arturo/MPV/mpv', '-I/home/arturo/MPV/mxe/usr/x86_64-w64-mingw32.static/include', '-I/home/arturo/MPV/mxe/usr/x86_64-w64-mingw32.static/include/dvdcss', '-I/home/arturo/MPV/mxe/usr/x86_64-w64-mingw32.static/include/harfbuzz', '-I/home/arturo/MPV/mxe/usr/x86_64-w64-mingw32.static/include/cairo', '-I/home/arturo/MPV/mxe/usr/x86_64-w64-mingw32.static/include/pixman-1', '-I/home/arturo/MPV/mxe/usr/x86_64-w64-mingw32.static/include/libpng16', '-I/home/arturo/MPV/mxe/usr/x86_64-w64-mingw32.static/include/fribidi', '-I/home/arturo/MPV/mxe/usr/x86_64-w64-mingw32.static/include/glib-2.0', '-I/home/arturo/MPV/mxe/usr/x86_64-w64-mingw32.static/lib/glib-2.0/include', '-I/home/arturo/MPV/mxe/usr/x86_64-w64-mingw32.static/include/freetype2', '-DHAVE_DVDNAV=1', '-DHAVE_DVDREAD=1', '-DHAVE_LIBAV=1', '-DHAVE_LIBAVFILTER=1', '-DHAVE_CDDA=1', '-DHAVE_LIBSWRESAMPLE=1', '-DHAVE_LIBBLURAY=1', '-DHAVE_CACA=1', '-DHAVE_LIBAVDEVICE=1', '-DHAVE_LIBASS=1', '-DPCRE_STATIC', '../video/out/opengl/context_dxinterop.c', '-c', '-o', '/home/arturo/MPV/mpv/build/video/out/opengl/context_dxinterop.c.14.o']
```
I have also taken care of installing the GLEW package with :

```
make glew sdl2 sdl2_image freetype
```

but I'm getting the error anyway....the only solutio so far I have found is to configure the build disalbling the GL support with :

```
./waf configure --disable-gl
```

any hints on this ? thanks in advance.....

              Arturo

**Comment by paulguy** [comment]
There is actually a pull request for that specific problem: https://github.com/mpv-player/mpv/pull/2875

**Comment by jeeb** [comment]
This pull request is most likely not going to pass, as it would be duplicating system headers (available in Windows SDK for MSVC and mingw-w64 master). It is also used only for a single switch, which makes the usefulness of it a bit dubious (https://github.com/mpv-player/mpv/commit/3d2fb9e9a8e8f4bff3ef5b2faec8f8dc9f916dd0). So the real alternatives IMHO would be:
* Break dx interop on Vista (revert the patch adding the requirement for this header).
* Require mingw-w64 that is not yet released (a check for the header).

Until one of those things is done, people compiling with mingw-w64 may want to either update their mingw-w64 toolchain to the master branch, or just copy the header from current mingw-64 master to their toolchains (https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/include/versionhelpers.h).

**Comment by paulguy** [comment]
Well, whichever, it's at least a solution for the person with the problem here, so it can work for now.

**Comment by jeeb** [comment]
I would rather see either updating one's toolchain or grabbing the header from mingw-w64 as I linked as an actual solution :) . No need to patch mpv for it.

**Comment by artynet** [comment]
as I told here https://github.com/mpv-player/mpv/pull/2875, I have decided to build from scratch again the toolchain and rebuild. All now is working as it should. The issue can be closed, thanks.

**Comment by wm4** [comment]
Solved by updating.
