### ISSUE TITLE
How to enable smoothmotion?

### ISSUE THREAD

**Issue by hobbes78** [mpv-player/mpv#2885]
Hi all,

I’m new to `mpv`, coming from `mplayer`, and the main reason that led me to try it out was the **smoothmotion** feature. But activating it seems harder that I hoped for. I started with this command line:

    mpv file.avi

The documentation only mentions once “smoothmotion,” when describing a `scale` filter called `oversample`; however it seems it should be used with `tscale` instead; and for `tscale` to be specified, an output driver seems to need to be specified, maybe `opengl`, no?

    mpv --vo=opengl:tscale=oversample file.avi

However in the `tscale` documentation I read it requires also the `interpolation` option.

    mpv --vo=opengl:tscale=oversample:interpolation file.avi

However in the `interpolation` documentation I read it required also the `--video-sync` with one of the `display-` options, maybe `display-resample`, no?

    mpv --vo=opengl:tscale=oversample:interpolation --video-sync=display-resample file.avi

This seems to be it, but after all this recursive option enabling I’m a bit lost :/ Is this command correct? Couldn’t a simple `--smoothmotion` switch be available instead?

Thanks in advance,

André

**Comment by lamarpavel** [comment]
The option you set are correct, but you probably want to set them in the config file (~/.config/mpv/config) so you don't have to type the command line all the time.

A flag such as `--smoothmotion` might abstract too much away as there is a great difference between the various scalers (oversample is just one of many) and mpv generally does not try to hide configuration from those who want to get their feet wet. I could imagine mpv shipping with a more fleshed out default config that offers more predefined profiles that are easily switched between and that cover use cases such as yours.

**Comment by haasn** [comment]
I think an alias system (e.g. “smoothmotion” -> “interpolation+tscale+video-sync”, or “nnedi3” -> “prescale+prescale-passes+prescale-downscaling-threshold”) might do more harm than good when it comes to helping people figure out how mpv options work.

In this specific case, it would probably be easier to cut down on the number of recursive option enabling a new user has to do by explicitly documenting up-front that enabling smoothmotion requires all of these options.

**Comment by wm4** [comment]
I've considered enabling display-sync mode automatically if interpolation is enabled in vo_opengl, but then considered it'd do more harm then it helps.

You don't need to set tscale, though.

**Comment by hobbes78** [comment]
Thank you all for the feedback. If a 24fps movie is played on a 60Hz screen, I suppose the framerate smoothmotion achieves is somewhere between 24 and 60, depending on hardware being used, no? Is there a way to display the fps value? I tried `--term-playing-msg='FPS: ${fps}'` but it didn't work...

**Comment by lazeran** [comment]
`vo=opengl:interpolation
video-sync=display-resample`

Just add in your mpv.conf

**Comment by bfulop** [comment]
How about these settings for smooth motion? 

I was getting this error message with above config

```
Option vo: this option does not accept sub-options.
Sub-options for --vo and --ao were removed from mpv in release 0.23.0.
```

After going through the docs I came up with these options, what do you think?

```
vo=opengl
interpolation
video-sync=display-resample
scale=oversample
tscale=oversample
```

**Comment by TheJman494** [comment]
@bfulop 
For interpolation you just need to set tscale
Scale, dscale and, cscale are used for when you resize the video up/down.

You can also get a list of available filters with --tscale=help if you open mpv.com in a command prompt on Windows

Here's an example for your your mpv.conf
```
profile=opengl-hq
video-sync=display-resample
blend-subtitles=yes
interpolation=yes
tscale=oversample
```
And if you would like to try out a few different options in real time put this in input.conf
```
v cycle interpolation
b cycle-values tscale "oversample" "linear" "catmull_rom" "mitchell" 
```

**Comment by bfulop** [comment]
Ah thanks, the `scale=oversample` setting could explain then why I had some performance issues going full screen (on a low end Mac). 

Yesterday I was driving myself crazy testing the different settings.

What would you suggest as setting to get a really exaggerated motion blur effect (24FPS movie on a 60Hz projector)? I actually prefer motion blur to crisp movements especially on a large screen.

I tried

```
tscale-blur=1.2
tscale-wblur=1.2
tscale-radius=16
```

But still couldn't see any visible difference (testing with the 24FPS [bunny clip](https://github.com/haasn/interpolation-samples/raw/master/24fps/native.mkv?raw=true) from the interpolation [wiki page](https://github.com/haasn/interpolation-samples) )

**Comment by kevmitch** [comment]
I believe the consensus is that `catmull_rom` or `mitchell` are ideal if you don't mind some blur. `linear` is probably more blurry. `oversample` is best for crispness.

**Comment by CounterPillow** [comment]
@percheperche instead of reading old issues you should be reading the documentation and the error message it gives you.

You'll want
```
interpolation=yes
video-sync=display-resample
tscale=oversample
```
or any other tscale. Leave out the `vo` line. If you want to use the hq profile, use `profile=gpu-hq`.

**Comment by percheperche** [comment]
@CounterPillow I don't see any differences with these options...

**Comment by CounterPillow** [comment]
@percheperche have you tried other tscale options? They vary in how they look.

Also, you obviously will only see differences during playback, not while framestepping or pausing.

**Comment by Hi-Angel** [comment]
@percheperche yeah, at first I also thought it's not working. But apparently it does, it's just that the difference very small. I can tell that because if I replace the `tscale=oversample` with `tscale=mitchell`, I see movement become more blurry.
