### ISSUE TITLE
Start playing only when window is focused?

### ISSUE THREAD

**Issue by brianbuccola** [mpv-player/mpv#2889]
Hi,

I just upgraded from v0.15.0 to v0.16.0, and it seems to have broken what I would consider a feature: namely, it used to be that when I spawned mpv, the video would not start playing until I actually focused the window containing mpv. This is useful to me because I have a dedicated workspace for videos, and I like to be able to spawn mpv into that workspace from my browser workspace while I continue browsing and let the video buffer and/or until I'm ready to view it. Now, I have to switch to the workspace, manually pause the video, then switch back.

Is it possible to get this "feature" back?

Thanks,
Brian

P.S. If it matters, I'm running XMonad on Arch Linux.

**Comment by wm4** [comment]
It was a bug, not a feature. If you really want it, write a Lua script. (Not sure if everything required for it is there.)

**Comment by lamarpavel** [comment]
You can append `--pause` to the mpv invocation from your browser to achieve the same effect quickly.

**Comment by brianbuccola** [comment]
@wm4: I figured it was probably a bug, not a feature - oh well.

@lamarpavel: Thanks - that's a good idea. I actually wound up just adding `pause` to `~/.config/mpv/mpv.conf` so that it always starts on pause, because the vast majority of my video watching is in stream form anyway.
