### ISSUE TITLE
Add script-message to make the OSC show up temporarily

### ISSUE THREAD

**Issue by tberger2** [mpv-player/mpv#2891]
The 'script_message enable-osc' command in input.conf seems not to work any longer.

Is there any way to get this behaviour back?
Thx in advance

**Comment by Cpuroast** [comment]
This was replaced with:

script_message osc-visibility never
script_message osc-visibility auto

See the man page: https://github.com/mpv-player/mpv/blob/v0.16.0/DOCS/man/osc.rst

**Comment by tberger2** [comment]
I've already seen this before but is there any way to define an interval for osc visibility?

**Comment by garoto** [comment]
I guess adjusting this in osc.conf? https://mpv.io/manual/master/#on-screen-controller-hidetimeout

**Comment by tberger2** [comment]
This has no influence on key bindings.

**Comment by ChrisK2** [comment]
I guess we need a new script-message for this now ...

... will take care of this ..eventually.. ... unless someone else does ...

**Comment by kasper93** [comment]
Fixed by: https://github.com/mpv-player/mpv/pull/14358
