### ISSUE TITLE
zsh completion should only show useful protocols

### ISSUE THREAD

**Issue by WoLpH** [mpv-player/mpv#2892]
It might be hard to define which protocols are useful for everyone but there are certainly some useless protocols in the list. The `file://` protocol for example makes no sense since files are supported without the protocol.

I propose a cleanup to the list of protocols but perhaps even a (configurable?) hardcoded list of protocols.
For example, this is the output of `mpv<tab>` for me in a directory with 3 video files:

```
# mpv
---- media file
---- URL
av://         bd://         bluray://     br://         concat://     fd://         file:
ftp://        hls://        httpproxy://  lavf://       memory://     mms://        mmshttp://
null://       rtmp://       rtmps://      rtmpte://     rtp://        sftp://       tcp://
test.mkv      tls://        udp://        avdevice://   bdnav://      bluraynav://  brnav://
edl://        ffmpeg://     file://       gopher://     http://       https://      md5://
mf://         mmsh://       mmst://       rar://        rtmpe://      rtmpt://      rtmpts://
rtsp://       srtp://       test.avi      test.mp4      tv://         unix://
```

It requires quite a bit of searching and tabbing to find the files. Are there people actually using these protocols commandline without copy/pasting?

**Comment by lachs0r** [comment]
Not sure what I configured to do this but I get completions sorted by type:

```
$ mpv<tab>
somedir/                           somefile.mkv
av://         dvd://        http://       null://       smb://
avdevice://   dvdnav://     httpproxy://  rar://        srtp://
bd://         dvdread://    https://      rtmp://       tcp://
bdnav://      edl://        lavf://       rtmpe://      tls://
bluray://     fd://         md5://        rtmps://      tv://
bluraynav://  ffmpeg://     memory://     rtmpt://      udp://
br://         file:         mf://         rtmpte://     unix://
brnav://      file://       mms://        rtmpts://
cdda://       ftp://        mmsh://       rtp://
concat://     gopher://     mmshttp://    rtsp://
dvb://        hls://        mmst://       sftp://
```

**Comment by WoLpH** [comment]
That would indeed help, I can't find any relevant setting in my zshrc but I'll keep looking.
it still begs the question how many are actually useful though :)

The ones that are imho extremely useless and should be removed:

 - gopher - the precursor for http, I highly doubt it was ever used for videos
 - file - these are supported natively so ultimately useless
 - rar - as with above, just specify a rar file instead
 - concat - seems like a very specific use-case, not a native thing
 - null - this is a protocol? should it be?
 - memory - seems like something you wouldn't use from the regular command line
 - udp - raw videostreams or something? which protocol is this using?
 - tcp - same as with udp, is this ever useful to autocomplete?
 - tls - see above
 - unix - see above
 - md5 - is this a video protocol, really?

Device specific ones that appear mostly useless to me but might still have some uses. Should be a configurable option imho.

 - cdda - cd protocols
 - dvd/dvdnav/dvdread - dvd protocols
 - bd/bdnav/bluray/bluraynav - bluray protocols

That still leaves a lot of protocols which probably have no use either, and some which I've never heard of such as `mf://` and `edl://`.

**Comment by qmega** [comment]
> It requires quite a bit of searching and tabbing to find the files. Are there people actually using these protocols commandline without copy/pasting?

IIRC @ghedo said he used completion for URLs. Personally, I don't, and I have it disabled with the following in `~/.zshrc`:

    zstyle ':completion:*:complete:mpv:*' tag-order '!urls'

With that configuration, it will actually still complete URL prefixes if you type the beginning of them, but only if there are no files that match the same string. So maybe that should actually be the default, if we can do that from the script. Opinions? Does anyone else use tab completion for URLs?


> Not sure what I configured to do this but I get completions sorted by type

    zstyle ':completion:*' group-name ''

Or if you only want it for mpv:

    zstyle ':completion:*:complete:mpv:*' group-name ''


Also possibly relevant is #2273, which I kind of forgot about. I think we may run into a similar problem here of different people wanting different sets of protocols (if anyone actually uses it, that is). It is probably already possible to override it using zstyle if you care enough. If we are going to hard-code a list, I'm not going to be the one to come up with it.

@WoLpH Do you actually want to use a subset of the URLs, or were you just trying to compromise and would rather them not be completed at all?

**Comment by WoLpH** [comment]
First of all, thanks for the great response. It seems my zsh-fu is definitely lacking a bit as I should have thought of this myself.

As for disabling url completion completely, that is definitely an option for me. I do use them at times but besides `http`, `https` and `rtsp` I can't say I ever use it...

Disabling this by default would have my vote as well, I doubt that it's too useful for anyone but I can't imagine it being useful at all in it's current shape. Most of these protocols surely aren't used anymore so if anything I think there should be a protocol blacklist instead of a whitelist. That way new protocols will be included by default but obsolete ones are dropped.

**Comment by Kagami** [comment]
Agree with @WoLpH. Most of this protocols are completely useless for common users. The current state of completition almost makes "mpv \<tab\>" useless: you better type first few letters of file, instead of choosing within that huge list.

**Comment by qmega** [comment]
I'm going to look into getting the script to display URLs only if no files match when I have a little more time, hopefully tomorrow. If that doesn't work out, maybe removing it from the script completely is a good idea; doesn't seem like it's used much if at all.

For now, I'm going to try making a quick wiki page on customizing zsh completion.

**Comment by qmega** [comment]
#3030 makes my personal configuration default, so URLs won't be completed unless no files match. If anyone gets here later wanting to change it back, you can use something like this in your `~/.zshrc`:

    zstyle ':completion:*:*:mpv:*' tag-order

That just defines the relevant style but doesn't set it to anything, so the script won't override it and you'll get the default behaviour of all tags being completed at once.

I don't think we'll be able to come up with a default whitelist or blacklist that will suit everyone, and I don't want to get into another situation like we have with file extensions now. If you want your own custom list, you can probably make it happen with some combination of tag-order and ignored-patterns or something like that. If you want to do that and can't figure it out, post here and I'll see if I can.

**Comment by WoLpH** [comment]
I don't think it should be a fallback, perhaps in the order it should be but I don't see any relation between having files available and wanting to access a url.

Having a default list of supported urls should work just fine as long as there is some documentation

**Comment by qmega** [comment]
@WoLpH I'm not really sure what you're saying. I think you're saying you want URLs completed along with files, but only a subset of them. Correct me if I'm wrong.

I don't want to put that in the script by default, as I said, because everyone wants different sets of prefixes, and many people don't want any at all. However, you should be do that for yourself with `tag-order` and friends (see the man page for `zshcompsys`). I'm willing to help if you need it.

> I don't see any relation between having files available and wanting to access a url.

Right, but wanting files is almost certainly more common for most people (remember that *pasting* a URL doesn't require tab completion at all), and URLs get in the way of that, so we're trading more work in a rarer case for less work in a more common one.

**Comment by WoLpH** [comment]
I mean that the behavior should be consistent. Either always display the urls or never.
Making it depend on files in the current directory is not something I would expect.

**Comment by qmega** [comment]
Hmm, okay. I guess I can see your point, but I don't think it actually works like that in practice. The only situation in which you'd get URLs when pressing Tab without typing anything is in an empty directory, and I wouldn't expect that to happen very often. The practical effect of the new setup is that URLs generally won't show up in the list at all *unless you type the beginning of one*. That seems fairly intuitive to me. The only really weird case I can think of would be if you typed e.g. `ht<Tab>` expecting `http://` and you happened to have a file called `htsomething.mkv`. And it comes with benefits in addition to cleaning up the list, such as `mpv <Tab>` in a directory with files all sharing some prefix inserting that prefix right away (letting you immediately type an episode number, for example).

**Comment by qmega** [comment]
If you want URLs alongside files by with a blacklist, you can do this:

    zstyle ':completion:*:*:mpv:*' tag-order
    zstyle ':completion:*:*:mpv:*' ignored-patterns '(memory|md5|whatever-else)://'

I tried messing with custom tags but I couldn't easily get it to work and this does work, so it should be fine. If you wanted a whitelist instead, you would have to get the custom tags working, or approach it some other way, because if you use a negative pattern at this scope it'll ignore files as well. Maybe I'll try again later.

**Comment by WoLpH** [comment]
Fair enough, I agree with that solution.

Thanks for your efforts. It's a very big improvement!
