### ISSUE TITLE
[Question] audio: change downmix behavior, add --audio-normalize-downmix

### ISSUE THREAD

**Issue by habaneros** [mpv-player/mpv#2894]
I noticed this was added to mpv 0.16.0, but couldn't find any info on what was actually changed & what the new option does.
Tried `audio-normalize-downmix` out on a 5.1 AC3 file with my stereo setup, and all I got was that the voices were barely audible while the overall loudness seemed to have been reduced.
Is this to be expected?

**Comment by wm4** [comment]
Yes. The manpage is clear on this.
