### ISSUE TITLE
Add binding to save later without quitting

### ISSUE THREAD

**Issue by mathstuf** [mpv-player/mpv#2895]
It'd be nice to able to save the current playback state without having to quit. This would be useful is watching a flaky video stream or a file that is being downloaded (and mpv catches up to the end of the file). Or is there a better way to do this?

**Comment by paulguy** [comment]
Probably can abuse the A-B loop functionality for this.

**Comment by mathstuf** [comment]
If you only set A, that doesn't do much, IIRC. The internal tristate isn't something I'd like to work around. Plus, that ties up the A-B loop feature (which isn't necessarily exclusive here).

**Comment by paulguy** [comment]
Yeah, it's not the best but it's something that could be used for now, until a better solution is made later.  I imagine you mean a sort of video bookmarking feature?

**Comment by wm4** [comment]
https://mpv.io/manual/master/#command-interface-write-watch-later-config
https://mpv.io/manual/master/#options-keep-open

**Comment by mathstuf** [comment]
Thanks; had missed that. Is it something that would make sense as a default binding (I'm using `W`)?

**Comment by wm4** [comment]
I don't really think so. Too obscure.
