### ISSUE TITLE
Change ytdl's Default Options

### ISSUE THREAD

**Issue by asoksevil** [mpv-player/mpv#2901]
How do you change the default options for videos played through mpv?

I have added: ytdl-format=137+140

to my config file but it keeps loading the best available (4k which doesn't run properly on my 2010 MBA)

I think the best I can do is 1080p but the previous format or any other format won't work...

Thanks!

**Comment by asoksevil** [comment]
Fixed.

I had to use the global settings to overwrite it.

**Comment by garoto** [comment]
You can also use a format like this:

ytdl-format='bestvideo[ext=mp4][width<=1280][height<=720]+audio[ext=m4a]/best'

The "/best" at the end is for not breaking yt-dl for websites other than YT.
