### ISSUE TITLE
screeenshot-directory not working

### ISSUE THREAD

**Issue by carks32** [mpv-player/mpv#2902]
I'm pretty sure I'm doing something wrong with the conf file, but I don't know why it does not work. It doesn't matter where do I tell it to save the screenshots, but it just goes and saves it on the desktop.

I'm on the windows build, w7.

**Comment by kevmitch** [comment]
I believe that when not starting from the command line, you need to put this in the ```psudo-gui``` section

       [pseudo-gui]
       screenshot-directory=C:\Users\you\

**Comment by Hrxn** [comment]
Correct.

On Windows, if you start mpv via taskbar, start menu, or by opening a file in the default shell (aka Explorer), it always switches into `pseudo-gui` mode.

https://mpv.io/manual/master/#pseudo-gui-mode

**Comment by wm4** [comment]
Yes, this is very fucked up, but this is how it works.
