### ISSUE TITLE
${audio-bitrate} returns (unavailable) if playing mkv

### ISSUE THREAD

**Issue by Divetoxx** [mpv-player/mpv#2903]
Last windows build https://mpv.srsfckn.biz/mpv-i686-20160229.7z doesn't show ${audio-bitrate} if playing mkv files.
avi, mp4, ts, m2ts, mpg, wmv - all ok.
Something is broken now.

![111](https://cloud.githubusercontent.com/assets/1689751/13545299/1b7bc762-e298-11e5-9bbf-1609ce949766.jpg)

**Comment by garoto** [comment]
I guess I can confirm. The property seems to display properly with PCM and Opus audio streams from my limited testing.

http://i.imgur.com/09m1KKD.jpg
http://i.imgur.com/09m1KKD.jpg

Win7 x64.

**Comment by Hrxn** [comment]
Sorry for hijacking, but this is exactly the kind of status info display I was looking for.
Could you paste your OSD config here?

**Comment by kevmitch** [comment]
> Sorry for hijacking, but this is exactly the kind of status info display I was looking for.
Could you paste your OSD config here?

https://github.com/Argon-/mpv-stats

**Comment by Hrxn** [comment]
I actually used that one some weeks ago...

Okay, so maybe not your `mpv.conf`, but your mpv-stats conf instead? ;-)

**Comment by Divetoxx** [comment]
I have mpv.conf with this line:
osd-msg3="${time-pos}   ${duration}   ${video-format}   ${fps}   ${width}x${height}   ${video-params/pixelformat}   ${audio-codec-name}   ${audio-bitrate}   ${video-params/colormatrix}   ${video-params/colorlevels}"

**Comment by Hrxn** [comment]
Nice, thanks...

By the way, does `Shift+o` cycle through all 3 OSD levels?

**Comment by Divetoxx** [comment]
Yes, of course! Shift+o cycles through all 3 OSD levels, why not?

**Comment by Hrxn** [comment]
I can't test it myself right now, am still on the road..
