### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by Toneymoon** [mpv-player/mpv#2906]
By default mpv tries to use vo=opengl or vo=vdpau, but my system does not have hardware acceleration for both:
System:    Host: arch Kernel: 4.4.3-1-ARCH i686 (32 bit) Desktop: Xfce 4.12.3 Distro: Arch Linux
Graphics:  Card: VIA CN700/P4M800 Pro/P4M800 CE/VN800 Graphics [S3 UniChrome Pro]
           Display Server: X.Org 1.18.1 driver: openchrome Resolution: 1024x768@60.00hz
           GLX Renderer: Gallium 0.4 on llvmpipe (LLVM 3.7, 128 bits) GLX Version: 3.0 Mesa 11.1.2

mpv crashes while trying to play video without config (with the default settings):
http://dump.bitcheese.net/files/ikamesy/mpv_-v_dump.txt
http://dump.bitcheese.net/files/aroxeke/mpv_gdb_bt.txt

**Comment by wm4** [comment]
Report it to Mesa, please.
