### ISSUE TITLE
How subtitle naming should be?

### ISSUE THREAD

**Issue by vonpupp** [mpv-player/mpv#2907]
Hello,

I have an mp4 video and 5 subtitles, as follows:
    -rw-rw----+ 1 av av 119K Feb 25 08:26 'The Last Reformation - The Beginning.en.srt'
    -rw-rw----+ 1 av av 123K Feb 25 08:26 'The Last Reformation - The Beginning.es.srt'
    -rw-rw----+ 1 av av 125K Feb 25 08:26 'The Last Reformation - The Beginning.fr.srt'
    -rw-rw----+ 1 av av 121K Feb 25 08:26 'The Last Reformation - The Beginning.it.srt'
    -rw-rw----+ 1 av av 3.3G Mar  4 12:55 'The Last Reformation - The Beginning.mp4'
    -rw-rw----+ 1 av av 123K Feb 25 08:26 'The Last Reformation - The Beginning.pt_br.srt'

When I play the video file, the english subtitles are load automatically however I cannot switch over different subtitles. From what I read in the documentation it should be ``ctrl+right``, however this doesn't work. What should be the subtitles names?

The subtitles icon is the one shown on the red box? Should it show 1/5, 2/5 and so forth?

![screenshot](https://cloud.githubusercontent.com/assets/1082073/13549785/1567d934-e2ec-11e5-82f3-1872a02f2f94.png)

Thank you very much.

**Comment by SeaHOH** [comment]
You should set `--sub-auto=fuzzy`, then the subtitle can be changed.
The Manual documentation is long, but it has a good menu, very clear.

**Comment by vonpupp** [comment]
Great!

Thank you very much! This works fine as expected =). Just out of curiosity, is there any other way without this flag for the subtitles to be loaded automatically? Does this depends on the filename scheme?

**Comment by dylanaraps** [comment]
You can add `sub-auto=fuzzy` to your mpv.conf file.
