### ISSUE TITLE
Audio no longer playing after update, other files not playing at all

### ISSUE THREAD

**Issue by FranNyan** [mpv-player/mpv#2908]
Using Suse linux. The newest update doesn't play audio on mp4/mkv files and attempting to open AVIs or any other file crashes the program.  

Output when playing a file that played fine before the update was:

> Playing: /f-drive/Dload/[Over-Time] Kamen Rider Ghost - 19SD [38AF6687].mp4
>  (+) Video --vid=1 (*) (h264)
>  (+) Audio --aid=1 --alang=und (*) (aac)
> Failed to initialize an audio decoder for codec 'aac'.
> Audio: no audio
> VO: [opengl] 854x480 yuv420p
> V: 00:00:00 / 00:23:17 (0%)

Attempting to play an AVI or mp3 gives: "Failed to recognize file format."   as the error.

I've fiddled around with a bunch of audio settings, added new audio decoders, but nothing seems to be working.  Video plays fine on VLC so the system has all the decoders it needs, I assume.    Any ideas what I can do?

**Comment by wm4** [comment]
Most likely a broken build or build against a crippled ffmpeg. Get it from somewhere else.

>Video plays fine on VLC so the system has all the decoders it needs,

There's no such thing as system decoders on Linux.

**Comment by lachs0r** [comment]
Make extra sure all the FFmpeg (libavcodec etc.) packages are coming from Packman.
