### ISSUE TITLE
Wrong version in mpv.pc file

### ISSUE THREAD

**Issue by Vascom** [mpv-player/mpv#2921]
When build MPV under Linux created pkgconfig file mpv.pc with wrong version:
1.20.0 instead of 0.16.0.

**Comment by rossy** [comment]
That's probably correct. mpv versions its client API separately from the standalone program. See https://github.com/mpv-player/mpv/blob/master/DOCS/client-api-changes.rst#api-changes

**Comment by Vascom** [comment]
Hm, I am understand.
Thanks for fast reply.
