### ISSUE TITLE
regression - mpv refuses to save state of some videos

### ISSUE THREAD

**Issue by Spanguole** [mpv-player/mpv#2922]
I updated my mpv from `0.15.0` to `0.16.0` and now it refuses to save state of videos that are built up from several mkv files (i.e. an mkv file that instead of housing the whole video references other mkv files holding individual chapters).
This worked perfectly fine in `0.15.0`, but now on `0.16.0` refuses to save state with a `Not seekable - not saving state.`, making it a regression.
It appears commit https://github.com/mpv-player/mpv/commit/39ed9b7d96f553096eeb02117ff531e42c11951d is responsible for it. I reverted this commit from `0.16.0` and the regression went away – with it reverted mpv again saves and restores state of such files just fine.

**Comment by wm4** [comment]
This probably has been fixed in git if it is what I think it is.
