### ISSUE TITLE
deadzonesize=1 quit working

### ISSUE THREAD

**Issue by billschu** [mpv-player/mpv#2923]
last known working
mpv git-ad2d10a (mint-17 ppa- 2.0.15)

broken as of
mpv git-2db1b92 (mint17.2 ppa-2.0.16) 

also tried
mpv --no-config --script-opts=osc-deadzonesize=1 anyfile.mp4 with no joy

broken items behave as if deadzonesize is set to default value of 0

**Comment by AirPort** [comment]
I noticed that too for a short time a couple of days ago, it's been already solved in git with the very next commit (0cdd8ff).

**Comment by ChrisK2** [comment]
apparently already fixed.
