### ISSUE TITLE
The softvol-max option must be <= 1000.000000:

### ISSUE THREAD

**Issue by tberger2** [mpv-player/mpv#2925]
Is there any reason why?
Is it possible to increase this limit?
Maybe a patch?

Some media files are too silent played on a laptop computer.

Thank you!

**Comment by tberger2** [comment]
Found a solution for me adding -af=drc.

**Comment by kevmitch** [comment]
There's also ```--af=lavfi=dynaudnorm``` and ```--af=lavfi=acompressor```, both of which should be higher quality.
