### ISSUE TITLE
Can't get a perfect DS: value anymore

### ISSUE THREAD

**Issue by uid313** [mpv-player/mpv#2928]
Ever since upgrading to FFmpeg 3.0 and mpv 0.16.0, this is how my DS: field looks like:
- with 24 fps video -> `DS: 2.480`
- with 25 fps video -> `DS: 2.370`
- with 60 fps video -> `DS: 0.990`

I had perfect values before, on both Intel & Nvidia (Linux + 60Hz monitor), so I know for a fact that this can't be a hardware problem.
Anyone else seeing the same?

PS: I should add that this is with activated `interpolation`.

**Comment by Hrxn** [comment]
Anything else running in the background?

**Comment by uid313** [comment]
@Hrxn 
Nope, and I don't think that it's performance related, since it used to be a perfectly even number before & the numbers are just too close, so my hardware should be able to "go the last mile", so to speak.

Also, I think these numbers might be of interest:
`[vo/opengl-hq/x11] Current display FPS: 60.000000
[vo/opengl-hq] Assuming 60.000000 FPS for display sync.
[vd] Container reported FPS: 25.000000
`

`[statusline] AV: 00:00:01 / 00:00:24 (8%) A-V:  0.008 DS: 2.360/1
[cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[statusline] AV: 00:00:02 / 00:00:24 (11%) A-V:  0.007 DS: 2.377/1
[cplayer] Run command: disable-section, flags=0, args=[input]
[statusline] AV: 00:00:09 / 00:00:24 (36%) A-V:  0.000 DS: 2.400/1
[cplayer] Change display sync audio drift: 0
[cplayer] Compensation factor: 1.000054
[statusline] AV: 00:00:23 / 00:00:24 (94%) A-V: -0.005 DS: 2.400/1
[lavf] EOF reached.
[statusline] AV: 00:00:24 / 00:00:24 (99%) A-V:  0.000 DS: 2.370/1
`

**Comment by Hrxn** [comment]
Did you try a different backend?
https://mpv.io/manual/master/#video-output-drivers-backend

**Comment by uid313** [comment]
> Did you try a different backend?
I'm using `x11` on Nvidia and `x11egl` on Intel, since these are the ones recommended on Linux.

**Comment by Hrxn** [comment]
Well, I'm only running mpv on Windows currently, so it's either `win` or `dxinterop` for me.

I am not completely sure, but, AFAIK, `x11` uses GLX, and I think I read here somewhere that the newer EGL should work better.

Do you have the exact same issue with both Nvidia and Intel GPUs? That's strange..

**Comment by kevmitch** [comment]
> I am not completely sure, but, AFAIK, x11 uses GLX, and I think I read here somewhere that the newer EGL should work better.

This is true for Intel. Last I heard ```x11egl```  was not great for Nvidia.

**Comment by wm4** [comment]
Newer nvidia drivers have good EGL support, except that hardware decoding does not work.

**Comment by wm4** [comment]
?
