### ISSUE TITLE
man page rendering issue

### ISSUE THREAD

**Issue by Forcer78** [mpv-player/mpv#2930]
On OS X, the mpv man page throws grotty errors when displayed. This has been an issue for many versions, and so far only with mpv. Searching the internet for the error text actually brought up mpv as the first result: http://askubuntu.com/questions/547608/grotty-man-page-messages/547616

> ```
>    mpv - a media player
> ```
> 
> SYNOPSIS
>       mpv [options] [file|URL|PLAYLIST|-]
>       mpv [options] files
> 
> DESCRIPTION
>       mpv  is  a  media  player based on MPlayer and mplayer2. It supports a wide variety of video file >formats, audio and video codecs, and subtitle types. Special input URL types are available to read input >from a variety of sources other than disk files. Depending on platform, a
>       variety of different video and audio output methods are supported.
> 
> ```
>   Usage examples to get you started quickly can be found at the end of this man page.
> ```
> 
> INTERACTIVE C**grotty:<standard input> (<standard input>):4326: character above first line discarded
> grotty:<standard input> (<standard input>):4330: character above first line discarded
> grotty:<standard input> (<standard input>):4334: character above first line discarded**
> ONTROL

Edit: [Screenshot here.](http://i.imgur.com/x72a93g.png)

**Comment by rr-** [comment]
http://stackoverflow.com/a/38273288/2016221
