### ISSUE TITLE
Enable seeking for module music files

### ISSUE THREAD

**Issue by mrrhq** [mpv-player/mpv#2931]
Hello, now that ffmpeg already has libopenmpt support, which is what mpv uses, I'm wondering how much of the API is actually being used to enable seeking on their side. This is honestly intended to be a feature request, though some may consider it a bug.

What I want is mpv to enable seeking for module music files. (.it, .s3m, .xm, .mod).

**What happens:** When I seek using arrow keys, it always goes back to the starting position of the song.

**What is supposed to happen:** seeking properly though the song (using ffmpeg/libopenmpt's API.)

**Comment by wm4** [comment]
> Hello, now that ffmpeg already has libopenmpt support, 

Never heard of it... can't find it in the ffmpeg repo either.

**Comment by mrrhq** [comment]
Ah, sorry, it's actually libmodplug, not libopenmpt.

http://directory.fsf.org/wiki/Libmodplug

My mpd player also has it enabled. If you use mpd with a player on a Debian Sid system, and I bet other systems have this enabled, you can use an mpd client to transpose through a mod music song, even though it can miss some parts of the tracks (modifiers that change the tempo or play instruments continuously, etc...) Those are not bugs but specific implementations in libmodplug, nothing to worry about.

I just want mpv to be able to seek with those mod music files correctly.

**Comment by wm4** [comment]
The ffmpeg wrapper supports seeking, so mpv will use it: http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavformat/libmodplug.c;h=75699e89b473e551d59f91c1080e4934db007c94;hb=HEAD#l342

**Comment by kevmitch** [comment]
Seems to require hr-seek (exact) seek. This can be achived by pressing **shift** arrow, or adding to your ```~/.config/mpv/input.conf```

    RIGHT seek  5  exact
    LEFT seek -5 exact
    UP seek 60 exact
    DOWN seek -60 exact

**Comment by wm4** [comment]
Does that mean attempting to seek always goes back to the start?

**Comment by kevmitch** [comment]
Yes, non hr-seeks go back to start.

**Comment by wm4** [comment]
Then it probably doesn't provide anything better - just use hr-seeks.

**Comment by mrrhq** [comment]
While precise seeking works, if I seek while the playback is above 50% with mod files, it will just skip to the end and play the next song (or stop playing).

**Comment by wm4** [comment]
> if I seek while the playback is above 50% with mod files, it will just skip to the end and play the next song (or stop playing).

Sounds like a ffmpeg issue too.
