### ISSUE TITLE
[request] Expose `--osd-msg1-3` as RW properties

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#2934]
We can use `--osd-msg1-3` to display a message. However, it seems these can be only set from CLI and configuration files. It makes sense to support it from LUA/IPC as well.

Note that this is different from `mp.osd_message` and `mp.commandv("show-text", ...)`, which display message once for fixed period of time. The intended point of exposing `--osd-msg1-3` to LUA is to let users write persistent status bars with arbitrary logic by utilizing the option's OSD message level mechanism.

**Comment by wm4** [comment]
``options/osd-msg1`` etc.
