### ISSUE TITLE
Mpv.io 2:0.16.0+git3-trusty1hard-drive connection

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#2943]
Hello,
I love your player.
But since upgrade to new version, when I connect an extern hard-drive, it's note my file manager (nemo) open, it's mpv.
Strange, my linux is linuxmint 17.3 64bits with ppa: mc3man/mpv-test.
For the moment I use vlc but...
If I concerve mpv with vlc, it's the problem, perhaps it's liguess1.
Thank to mpv, the top movie player.

**Comment by kevmitch** [comment]
It sounds like you're saying that mpv opens when you plug in an external hard drive, whereas the expected behaviour is for your file manager to open pointing at newly connected drive.

If this is the case, then it's not mpv's fault. Your desktop environment is in charge of how to respond to events like new drives being connected.

If this is not the case, then you're going to have to clarify what the problem actually is.

**Comment by robinwood2** [comment]
Thank for your answer, sorry for my bad English, I'm french.
It's not my OS, It's just since the last upgrade, not before.
I don't change my defaut priority when I plug an hard-drive and then I remove mpv, comportement is normal.

**Comment by kevmitch** [comment]
So you're saying my interpretation of the problem is correct?

**Comment by robinwood2** [comment]
No, sorry.
It's not my OS, it's mpv withch is open when I plug an hard-drive.
This problem isn't on the past version.
If I remove mpv, when I connect hard-drive extern, it's my file manager whitch is open, normal.

**Comment by mc4man** [comment]
The last update to that trusty repo was a 100% no change rebuild, it only added git version number to cli
(for whatever reason launchpad/my rules file doesn't use version.sh as anticipated so I simply edit it in per build & occasionally forget to do that.
Can be seen in the diff - https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests/+files/mpv_2%3A0.16.0+git3~trusty_2%3A0.16.0+git3~trusty1.diff.gz

Taking a quick look at mint with nemo there is no issue unless one adds mpv.desktop as the default for inode/directory in mimeapps.list. So check yours...
(mpv does not register for inode/directory on install or update
If not that then something else you did.

**Comment by robinwood2** [comment]
The last mpv update to that trusty solved the hard-drive connect.
Thank you so much.
Mpv take me the most beautifull movie image.
The very best player.
Now I not a ghost.

**Comment by wm4** [comment]
Whatever this was about.
