### ISSUE TITLE
[request] Drag and Drop support dropping text URLs

### ISSUE THREAD

**Issue by CurtisLeeBolin** [mpv-player/mpv#2945]
I filed #2944 not realizing my problem was mpv not supporting DnD text URLs like VLC supports.

Chrome and Chromium seems to drop URLs as text.  (only tested in linux)
DnDing the URLs from the Firefox's Location bar also drops as text.
Drag and Dropping URLs from a text editor is another use case.
Any other location where the URL is text, e.g. cli.

Since DnD is a key aspect of mpv, "Drop files to play here", I hope URL text dropping support is added soon.

Thank You For Your Time.

**Comment by CrisBRM** [comment]
Just use https://addons.mozilla.org/en-us/firefox/addon/watch-with-mpv/ or https://github.com/agiz/youtube-mpv

**Comment by CurtisLeeBolin** [comment]
@CrisBRM, that does not pertain to my request for text URL DnD support.

**Comment by lachs0r** [comment]
IMO those idiotic browsers should still be fixed. KDE implements this correctly.

**Comment by CurtisLeeBolin** [comment]
@lachs0r, I am requesting URL text dropping support, not a debate about something unrelated to my request.

**Comment by lachs0r** [comment]
I’m only suggesting that you also report that to the browser vendors. This actually matters to other applications, e.g. when dropping URLs to a file browser. It’s also a bug because these browsers do implement URL dropping on other platforms.

**Comment by CurtisLeeBolin** [comment]
@lachs0r, dropping files into a file manager from chrome and chromium works fine.  MPV is the one and only program that I have experienced not working as expected.  This is a minor part of my text URL dropping request.  Dropping the URL from the location bar from any browser does NOT work with MPV.  Dropping text URL from any other program does NOT work with MPV.

I do NOT want someone to read your response and think my request is due to some other program's bug.  Please show in your responses that you are not giving a solution to my request.

**Comment by wm4** [comment]
Text URLs should be working on X11 since a few days ago.
