### ISSUE TITLE
Sign doesn't display properly in mpv

### ISSUE THREAD

**Issue by DiddyKode** [mpv-player/mpv#2948]
This is probably a very specific issue but I'm reporting it anyway.

Version: last lachs0r build (0.16.0 64bits)
OS: Windows 10

This is how a certain sign looks in mpc-be: 
![mpc_sign](https://cloud.githubusercontent.com/assets/16172196/13762282/aa3ad3e0-ea1c-11e5-95f9-a422fcaa30ae.png)

and this is how it looks in mpv:
![mpv_sign](https://cloud.githubusercontent.com/assets/16172196/13762320/e6f8e2ae-ea1c-11e5-8a06-44511569f6c3.jpg)

the .ass file in question (sorry, i couldnt think of a better host site):
[https://mega.nz/#!bIYn3JbB!Sr8vbWu3hW7C2-TuDqJ6za1vSuWlk5VYRUJ9aag6wLo](url)

As you can see in the screenshots, mpv isn't showing the rectangle that covers the original text. That rectangle is a large part of the .ass script, that's why I say that this is a specific issue (and maybe not a mpv issue)
The sign appears at 00:10:16

log:
[out.txt](https://github.com/mpv-player/mpv/files/173030/out.txt)

**Comment by Akemi** [comment]
it's missing a lowercase 'L' in the drawing parameter.

> m -2 156 712 156 712 91 -2 91
> m -2 156 **l** 712 156 712 91 -2 91

you should report that to libass though.

**Comment by lachs0r** [comment]
The drawings are invalid. This also affects a sign at 02:38.
Here’s a fixed script: https://0x0.st/KQb.ass

**Comment by DiddyKode** [comment]
Thank you both!
