### ISSUE TITLE
No way to output audio to HDMI

### ISSUE THREAD

**Issue by mauromol** [mpv-player/mpv#2950]
I'm using mpv git-d8b27ee under Linux Mint 17.3 KDE (based on Ubuntu Trusty).

Using mpv --audio-device=help shows:

    List of detected audio devices:                                                 
      'auto' (Autoselect device)                                                    
      'pulse/alsa_output.pci-0000_00_03.0.hdmi-stereo' (Audio interno Digital Stereo (HDMI))
      'pulse/alsa_output.pci-0000_00_1b.0.analog-stereo' (Audio interno Stereo analogico)
      'alsa/default' (Playback/recording through the PulseAudio sound server)
      'alsa/hdmi:CARD=HDMI,DEV=0' (HDA Intel HDMI, HDMI 0/HDMI Audio Output)
      'alsa/hdmi:CARD=HDMI,DEV=1' (HDA Intel HDMI, HDMI 1/HDMI Audio Output)
      'alsa/hdmi:CARD=HDMI,DEV=2' (HDA Intel HDMI, HDMI 2/HDMI Audio Output)
      'alsa/plughw:CARD=HDMI,DEV=3' (HDA Intel HDMI, HDMI 0/Hardware device with all software conversions)
      'alsa/plughw:CARD=HDMI,DEV=7' (HDA Intel HDMI, HDMI 1/Hardware device with all software conversions)
      'alsa/plughw:CARD=HDMI,DEV=8' (HDA Intel HDMI, HDMI 2/Hardware device with all software conversions)
      'alsa/plughw:CARD=PCH,DEV=0' (HDA Intel PCH, 92HD91BXX Analog/Hardware device with all software conversions)
      'oss' (Default (oss))
      'jack' (Default (jack))

I've also put this in input.conf:

    A cycle_values audio-device pulse/alsa_output.pci-0000_00_1b.0.analog-stereo pulse/alsa_output.pci-0000_00_03.0.hdmi-stereo

so that I can change audio device during playback.
The PulseAudio HDMI output device is working fine in KDE and in VLC, for instance, where I have no problems to switch the output audio device from the internal Analog device (uses my notebook embedded speakers) or the HDMi output device (sends audio to the TV I connect to the HDMI port).

But in mpv, even if the OSD shows it's performing the audio device cycling, the audio always goes to the internal Analog device (i.e.: I hear audio from the notebook speaker in any case).

I also tried to run:

    mpv -v --audio-device=pulse/alsa_output.pci-0000_00_03.0.hdmi-stereo /path/to/file

and audio always goes to the embedded speakers. I see no relevant output from mpv regarding this:

    [ao] Trying audio driver 'pulse'                                                
    [ao] Using preferred device 'alsa_output.pci-0000_00_03.0.hdmi-stereo'          
    [ao/pulse] requested format: 48000 Hz, stereo channels, floatp                  
    [ao/pulse] Library version: 4.0.0                                               
    [ao/pulse] Proto: 28                                                            
    [ao/pulse] Server proto: 4294967295                                             
    [ao/pulse] Channel layouts:                                                     
    [ao/pulse]  - #fl                                                               
    [ao/pulse]  - #fr                                                               
    [ao/pulse]  - #fc                                                               
    [ao/pulse]  - #lfe                                                              
    [ao/pulse]  - #bl                                                               
    [ao/pulse]  - #br                                                               
    [ao/pulse]  - #flc                                                              
    [ao/pulse]  - #frc                                                              
    [ao/pulse]  - #bc                                                               
    [ao/pulse]  - #sl                                                               
    [ao/pulse]  - #sr                                                               
    [ao/pulse]  - #tc                                                               
    [ao/pulse]  - #tfl                                                              
    [ao/pulse]  - #tfc                                                              
    [ao/pulse]  - #tfr                                                              
    [ao/pulse]  - #tbl                                                              
    [ao/pulse]  - #tbc                                                              
    [ao/pulse]  - #tbr                                                              
    [ao/pulse] result: stereo                                                       
    [ao/pulse] device buffer: 6000 samples.                                         
    [ao/pulse] using soft-buffer of 9600 samples.  

Please note I'm using the HDMI port connected to my embedded Haswell i5 CPU graphics.

**Comment by tberger2** [comment]
`mpv -ao=alsa:device=[hw:x,y]`
is working for me

to get x,y:
`aplay -l | grep HDMI`

**Comment by wm4** [comment]
It's pulseaudio being upset or something?

**Comment by mauromol** [comment]
Hi, using --ao=alsa:device=... works, but...

First of all, it's not a PulseAudio problem because, as I said, VLC works perfectly fine with the PulseAudio backend with regards to output device selection.

Also, if I use --audio-device=alsa/* (that is, I try to use the --audio-device switch instead, with any of the alsa device rather than the pulse one), it does not work either.

Finally, the mpv documentation says: "you should use the --audio-device option, instead of setting the device directly" when talking about the ability to choose the alsa device with --ao=alsa switch (by the way, I couldn't find where the [hw=x,y] syntax is explained in the reference documentation).

And, is there an equivalent way to change the PulseAudio output device with --ao=pulse:something?

**Comment by tberger2** [comment]
I've checked this 
`-audio-device=alsa/*`
which works for me...
...but that seems not to helpful for you. :-(

**Comment by msva** [comment]
I've pretty strange issue about how mpv works with PulseAudio (it means, that this problem doesn't exist in some other software).

If I try to set `--audio-device=pulse/alsa_output.pci-0000_00_03.0.hdmi-stereo-extra1`, mpv sends audio to internal speakers. Despite of "default" output device (so, even if I set HDMI as default device, mpv will play sound through internal speakers in this case (but will use HDMI if I'll not specify the `--audio-device` option). Although, my initial case was to direct the sound to HDMI on `mpv` side and don't set it as default output source).

// and since `--ao` is dropped now, I can't check if it will help like it helped some people above :-/
