### ISSUE TITLE
Changing default speakers result in crash

### ISSUE THREAD

**Issue by zehle** [mpv-player/mpv#2951]
I was watching a video-file in MPV when I noticed that my speakers wasn't set as default, resulting in no audio. I changed the default speakers in Windows to the external speakers and MPV frooze.

**Comment by kevmitch** [comment]
If this is reproducible, please provide a log produced with `log-file=log.txt`.

**Comment by Argon-** [comment]
I just recently had that on OSX: unplugged my headphones while mpv was opened (paused) in the background -> crash.
However, it only happened like 3 times so far. I don't know yet how to reliably reproduce it...
