### ISSUE TITLE
Errors when playing the YouTube live streams.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#2952]
It happens on elementary OS and openSUSE Leap.

[ffmpeg/audio] aac: element type mismatch 1 != 0
[ffmpeg/audio] aac: element type mismatch 1 != 0
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
[ffmpeg/audio] aac: element type mismatch 1 != 0
AO: [pulse] 48000Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [opengl] 256x144 vaapi
[osd/libass] fontconfig: cannot find font 'sans-serif', falling back to 'Roboto Regular'
[ffmpeg/audio] aac: element type mismatch 1 != 0
[ffmpeg/audio] aac: element type mismatch 1 != 0
[ffmpeg/audio] aac: element type mismatch 1 != 0
[ffmpeg/audio] aac: element type mismatch 1 != 0
[ffmpeg/audio] aac: element type mismatch 1 != 0
AV: 00:00:00 A-V:  0.000 Cache:  9s+0KB
[ffmpeg/audio] aac: element type mismatch 1 != 0
AV: 00:00:00 A-V:  0.000 Cache:  9s+0KB
[ffmpeg/audio] aac: element type mismatch 1 != 0
AV: 00:00:00 A-V:  0.000 Cache:  9s+0KB
[ffmpeg/audio] aac: element type mismatch 1 != 0
AV: 00:00:00 A-V:  0.000 Cache:  9s+0KB
[ffmpeg/audio] aac: element type mismatch 1 != 0
[ffmpeg/audio] aac: element type mismatch 1 != 0
AV: 00:00:00 A-V:  0.000 Cache:  9s+0KB
[ffmpeg/audio] aac: element type mismatch 1 != 0
AV: 00:00:00 A-V:  0.000 Cache:  9s+0KB
[ffmpeg/audio] aac: element type mismatch 1 != 0
[ffmpeg/audio] aac: element type mismatch 1 != 0
AV: 00:00:00 A-V:  0.000 Cache:  9s+0KB
[ffmpeg/audio] aac: element type mismatch 1 != 0
AV: 00:00:00 A-V:  0.000 Cache:  9s+0KB
[ffmpeg/audio] aac: element type mismatch 1 != 0
[ffmpeg/audio] aac: element type mismatch 1 != 0
AV: 00:00:02 A-V:  0.000 Cache:  9s+0KB

**Comment by wm4** [comment]
Just ignore them?

**Comment by laichiaheng** [comment]
@wm4 but it will become 256x144, the original resolution is 1920x1080

**Comment by kevmitch** [comment]
So your problem isn't the errors, but that the selected format is too low resolution.

This is probably youtube-dl's bizzare "if ffmpeg is in your path . . ." logic used with the default format `--ytdl-format=bestvideo+bestaudio/best`. One option is to specify 
`--ytdl-ormat=bestvideo+bestaudio`, but that may apparently break some non-youtube sites. The other option is to install ffmpeg (or avconv) so that it's in your `$PATH`.

**Comment by laichiaheng** [comment]
@kevmitch I do have ffmpeg installed.

**Comment by CrisBRM** [comment]
Can confirm.

https://www.youtube.com/watch?v=hxyiafJ7CeQ

**Comment by Hrxn** [comment]
In doubt, test it with youtube-dl. If it doesn't even work there...
Well, not an mpv issue.

**Comment by kevmitch** [comment]
> https://www.youtube.com/watch?v=hxyiafJ7CeQ

This stream no longer exists.

**Comment by sCreami** [comment]
Using an other random live stream you can see that youtube-dl fails to recognize the best format

> $ youtube-dl -F https://www.youtube.com/watch\?v\=_BMREq7yLu4
[youtube] _BMREq7yLu4: Downloading webpage
[youtube] _BMREq7yLu4: Downloading video info webpage
[youtube] _BMREq7yLu4: Extracting video information
[youtube] _BMREq7yLu4: Downloading formats manifest
[youtube] _BMREq7yLu4: Downloading MPD manifest
[info] Available formats for _BMREq7yLu4:
format code  extension  resolution note
92           mp4        240p       HLS , h264, aac  @ 48k
93           mp4        360p       HLS , h264, aac  @128k
94           mp4        480p       HLS , h264, aac  @128k
95           mp4        720p       HLS , h264, aac  @256k
96           mp4        1080p      HLS , h264, aac  @256k
91           m3u8       unknown    (best)

A quick workaround is to specify the format to mpv using the `ytdl-format` option such as
> $ mpv --ytdl-format=95 https://www.youtube.com/watch\?v\=_BMREq7yLu4

Which then, plays the stream at 720p.

**Comment by kevmitch** [comment]
Yes, this is a youtube-dl issue. You get the same low resolution stream invoking youtube-dl by itself.

    youtube-dl https://www.youtube.com/watch?v=_BMREq7yLu4

The problem seems to be that youtube-dl can't figure out the highest quality stream.
