### ISSUE TITLE
Hardware Acceleration doesn't work in drm-egl mode

### ISSUE THREAD

**Issue by kongqx** [mpv-player/mpv#2954]
I m focus on mpv in drm mode with the latest version. Referring to docs, I use the drm-egl backend for opengl VO mode. However, loading hardware decoding is always failed. 

I m wondering that is there anything wrong with my usage and does anyone test the drm-egl mode?

More information is attached below:

[cplayer] Command line options: '--vo=opengl:backend=drm-egl' '--hwdec=vaapi' '-v' '../VideoClip/Rings_2x2.mp4'
[cplayer] mpv git-0cdd8ff (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Wed Mar 16 12:49:45 CST 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.17.103
[cplayer]    libavcodec      57.24.102
[cplayer]    libavformat     57.25.100
[cplayer]    libswscale      4.0.100
[cplayer]    libavfilter     6.31.100
[cplayer]    libswresample   2.0.101
[cplayer] ffmpeg version: 3.0
[cplayer] 
[cplayer] Configuration: ./waf configure
[cplayer] List of enabled features: any-gl asm atomic-builtins atomics audio-input av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-profile-name avframe-metadata avframe-skip-samples build-date cplayer debug-build desktop-gl dlopen drm dvbin egl-drm egl-helpers egl-x11 enca encoding fchmod gbm gbm.h gl gl-x11 glibc-thread-name glob iconv libass libass-osd libav libavfilter libdl libm librt libswresample linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads resampler shm sse4-intrinsics subprocess termios tv tv-v4l2 vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-hwaccel vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 videodev vt.h x11 xext xinerama xrandr zlib
[global] config path: '' -> '/root/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/root/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/root/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/root/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/root/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/etc/mpv/config'
[cplayer] Setting option 'vo' = 'opengl:backend=drm-egl' (flags = 8)
[cplayer] Setting option 'hwdec' = 'vaapi' (flags = 8)
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -> '/root/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/root/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/etc/mpv/input.conf'
[global] user path: '/root/.config/mpv/input.conf' -> '/root/.config/mpv/input.conf'
[file] Opening /root/.config/mpv/input.conf
[file] Stream opened successfully.
[input] Parsing input config file /root/.config/mpv/input.conf
[input] Input config file /root/.config/mpv/input.conf parsed: 1 binds
[osc] Loading script @osc.lua...
[global] config path: 'scripts' -> '/root/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/root/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] config path: 'lua-settings/osc.conf' -/-> '/root/.config/mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/root/.mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/usr/local/etc/mpv/lua-settings/osc.conf'
[osc] lua-settings/osc.conf not found. 
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[cplayer] mouse_leave script-binding osc/__keybinding2
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[cplayer] mouse_btn2 script-binding osc/__keybinding5
[cplayer] mouse_btn0_dbl ignore
[cplayer] shift+mouse_btn0_dbl ignore
[cplayer] mouse_btn2_dbl ignore
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[input, ]
[cplayer] Run command: define-section, flags=0, args=[input_osc, del script-binding osc/__keybinding6
[cplayer] , default]
[cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: disable-section, flags=0, args=[input]
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading script @ytdl_hook.lua...
[global] config path: 'scripts' -> '/root/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/root/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[ytdl_hook] loading mp.defaults
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] config path: 'scripts' -> '/root/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/root/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[stats] Loading script /root/.config/mpv/scripts/stats.lua...
[global] config path: 'scripts' -> '/root/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/root/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[stats] loading mp.defaults
[global] user path: '/root/.config/mpv/scripts/stats.lua' -> '/root/.config/mpv/scripts/stats.lua'
[stats] loading file /root/.config/mpv/scripts/stats.lua
[global] config path: 'lua-settings/stats.conf' -/-> '/root/.config/mpv/lua-settings/stats.conf'
[global] config path: 'lua-settings/stats.conf' -/-> '/root/.mpv/lua-settings/stats.conf'
[global] config path: 'lua-settings/stats.conf' -/-> '/usr/local/etc/mpv/lua-settings/stats.conf'
[stats] lua-settings/stats.conf not found. 
[cplayer] Run command: define-section, flags=0, args=[input_stats, s script-binding stats/stats
[cplayer] , default]
[cplayer] Run command: enable-section, flags=0, args=[input_stats, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input_forced_stats, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_stats, allow-hide-cursor+allow-vo-dragging]
[cplayer] Done loading /root/.config/mpv/scripts/stats.lua.
[frame_info] Loading script /root/.config/mpv/scripts/frame_info.lua...
[global] config path: 'scripts' -> '/root/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/root/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[frame_info] loading mp.defaults
[global] user path: '/root/.config/mpv/scripts/frame_info.lua' -> '/root/.config/mpv/scripts/frame_info.lua'
[frame_info] loading file /root/.config/mpv/scripts/frame_info.lua
[global] config path: 'lua-settings/frame_info.conf' -/-> '/root/.config/mpv/lua-settings/frame_info.conf'
[global] config path: 'lua-settings/frame_info.conf' -/-> '/root/.mpv/lua-settings/frame_info.conf'
[global] config path: 'lua-settings/frame_info.conf' -/-> '/usr/local/etc/mpv/lua-settings/frame_info.conf'
[frame_info] lua-settings/frame_info.conf not found. 
[cplayer] Run command: define-section, flags=0, args=[input_frame_info, i script-binding frame_info/frame_info
[cplayer] , default]
[cplayer] Run command: enable-section, flags=0, args=[input_frame_info, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input_forced_frame_info, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_frame_info, allow-hide-cursor+allow-vo-dragging]
[cplayer] Done loading /root/.config/mpv/scripts/frame_info.lua.
[global] config path: 'watch_later' -> '/root/.config/mpv/watch_later'
[cplayer] Playing: ../VideoClip/Rings_2x2.mp4
[cplayer] Running hook: ytdl_hook/on_load
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[file] Opening ../VideoClip/Rings_2x2.mp4
[file] Stream opened successfully.
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[lavf] avformat_find_stream_info() finished after 86829 bytes.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[find_files] Loading external files in ../VideoClip/
[global] config path: 'sub/' -/-> '/root/.config/mpv/sub/'
[global] config path: 'sub/' -/-> '/root/.mpv/sub/'
[global] config path: 'sub/' -/-> '/usr/local/etc/mpv/sub/'
[global] config path: 'audio/' -/-> '/root/.config/mpv/audio/'
[global] config path: 'audio/' -/-> '/root/.mpv/audio/'
[global] config path: 'audio/' -/-> '/usr/local/etc/mpv/audio/'
[cplayer]  (+) Video --vid=1 (*) (h264)
[vo/opengl] Setting option 'backend' = 'drm-egl' (flags = 0)
[vo/opengl] Initializing OpenGL backend 'drm-egl'
[vo/opengl] Initializing KMS
[vo/opengl] Creating GBM device
[vo/opengl] Initializing GBM surface (1280 x 1024)
[vo/opengl] Initializing EGL
[vo/opengl] Initializing EGL surface
[vo/opengl] GL_VERSION='3.0 Mesa 10.1.3'
[vo/opengl] Detected desktop OpenGL 3.0.
[vo/opengl] GL_VENDOR='Intel Open Source Technology Center'
[vo/opengl] GL_RENDERER='Mesa DRI Intel(R) Sandybridge Desktop '
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='1.30'
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 300/builtin.
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 110/GL_EXT_unpack_subimage.
[vo/opengl] Loaded functions for 300/GL_ARB_framebuffer_object.
[vo/opengl] Loaded functions for 300/GL_ARB_vertex_array_object.
[vo/opengl] Loaded functions for 300/GL_ARB_texture_rg.
[vo/opengl] Loaded functions for 320/GL_ARB_sync.
[vo/opengl] Loaded functions for 430/GL_ARB_debug_output.
[vo/opengl] Loaded functions for 310/GL_ARB_uniform_buffer_object.
[vo/opengl] Filterable half-float textures supported.
[vo/opengl] Preparing framebuffer
[vo/opengl] swap_control extension missing.
[vo/opengl] Reported display depth: R=0, G=0, B=0
[vo/opengl] 16 bit texture depth: 16.
[vo/opengl] Testing user-set FBO format (0x805b)
[vo/opengl] Create FBO: 16x16 -> 16x16
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Loading hwdec driver 'vaapi-egl'
[vo/opengl] Loading failed.
[vo/opengl] Loading hwdec driver 'vaapi-glx'
[vo/opengl] Loading failed.
[vd] Container reported FPS: 23.976000
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd] Opening video decoder lavc:h264
[vd] Probing 'vaapi'...
[vo/opengl] Loading hwdec driver 'vaapi-egl'
[vo/opengl] Loading failed.
[vo/opengl] Loading hwdec driver 'vaapi-glx'
[vo/opengl] Loading failed.
[vd] VO does not support requested hardware decoder, or loading it failed.
[vd] Using software decoding.
[vd] Detected 4 logical cores.
[vd] Requesting 5 threads for decoding.
[vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
[cplayer] Starting playback...
[vd] Using software decoding.
[vd] Decoder format: 1920x1920 yuv420p auto/auto CL=mpeg2/4/h264
[vf] Video filter chain:
[vf]   [in] 1920x1920 yuv420p bt.709/limited CL=mpeg2/4/h264
[vf]   [out] 1920x1920 yuv420p bt.709/limited CL=mpeg2/4/h264
[cplayer] VO: [opengl] 1920x1920 yuv420p
[cplayer] VO: Description: Extended OpenGL Renderer
[vo/opengl] Resize: 1280x1024
[vo/opengl] Window size: 1280x1024
[vo/opengl] Video source: 1920x1920 (1:1)
[vo/opengl] Video display: (0, 0) 1920x1920 -> (128, 0) 1024x1024
[vo/opengl] Video scale: 0.533333/0.533333
[vo/opengl] OSD borders: l=128 t=0 r=128 b=0
[vo/opengl] Video borders: l=128 t=0 r=128 b=0
[vo/opengl] Testing user-set FBO format (0x805b)
[vo/opengl] Create FBO: 16x16 -> 16x16
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Texture for plane 0: 1920x1920
[vo/opengl] Texture for plane 1: 960x960
[vo/opengl] Texture for plane 2: 960x960
[vo/opengl] Reinit rendering.
[cplayer] set video colors output-levels=0 
[vo/opengl] recompiling a shader program:
[vo/opengl] [  1] color.x = 1.000000 * vec4(texture(texture0, texcoord0)).x;
[vo/opengl] [  2] color.y = 1.000000 * vec4(texture(texture1, texcoord1)).x;
[vo/opengl] [  3] color.z = 1.000000 * vec4(texture(texture2, texcoord2)).x;
[vo/opengl] [  4] // color conversion
[vo/opengl] [  5] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[vo/opengl] [  6] color.a = 1.0;
[vo/opengl] [  7] // color management
[global] config path: 'fonts' -/-> '/root/.config/mpv/fonts'
[global] config path: 'fonts' -/-> '/root/.mpv/fonts'
[global] config path: 'fonts' -/-> '/usr/local/etc/mpv/fonts'
[osd/libass] Shaper: FriBidi 0.19.6 (SIMPLE)
[global] config path: 'subfont.ttf' -/-> '/root/.config/mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/root/.mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/usr/local/etc/mpv/subfont.ttf'
[global] config path: 'fonts.conf' -/-> '/root/.config/mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/root/.mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/usr/local/etc/mpv/fonts.conf'
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf, 0, DejaVuSans
[cplayer] first video frame after restart shown
[cplayer] playback restart complete
[cplayer] Run command: quit, flags=9, args=[4]
[cplayer] EOF code: 6  
[vd] Uninit video.
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Quit)
[stats] Exiting...
[frame_info] Exiting...
[ytdl_hook] Exiting...
[osc] Exiting...

**Comment by wm4** [comment]
You need Mesa 11.

**Comment by kongqx** [comment]
I copy the mpv to the new PC which has Mesa 11 and got the same error. 

Should I rebuild mpv in new PC?

[cplayer] Command line options: '../VideoClip/Rings_2x2.mp4' '-v' '--hwdec=vaapi' '--vo=opengl:backend=drm-egl'
[cplayer] mpv git-0cdd8ff (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Wed Mar 16 12:49:45 CST 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.17.103
[cplayer]    libavcodec      57.24.102
[cplayer]    libavformat     57.25.100
[cplayer]    libswscale      4.0.100
[cplayer]    libavfilter     6.31.100
[cplayer]    libswresample   2.0.101
[cplayer] ffmpeg version: 3.0
[cplayer] 
[cplayer] Configuration: ./waf configure --disable-egl-x11
[cplayer] List of enabled features: any-gl asm atomic-builtins atomics audio-input av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-profile-name avframe-metadata avframe-skip-samples build-date cplayer debug-build desktop-gl dlopen drm dvbin egl-drm enca encoding fchmod gbm gbm.h gl gl-x11 glibc-thread-name glob iconv libass libass-osd libav libavfilter libdl libm librt libswresample linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads resampler shm sse4-intrinsics subprocess termios tv tv-v4l2 vaapi vaapi-drm vaapi-glx vaapi-hwaccel vaapi-x11 vdpau vdpau-gl-x11 videodev vt.h x11 xext xinerama xrandr zlib
[global] config path: '' -> '/root/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/root/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/root/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/root/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/root/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/etc/mpv/config'
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Setting option 'hwdec' = 'vaapi' (flags = 8)
[cplayer] Setting option 'vo' = 'opengl:backend=drm-egl' (flags = 8)
[global] config path: 'input.conf' -/-> '/root/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/root/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/etc/mpv/input.conf'
[input] Falling back on default (hardcoded) input config
[osc] Loading script @osc.lua...
[global] config path: 'scripts' -/-> '/root/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/root/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] config path: 'lua-settings/osc.conf' -/-> '/root/.config/mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/root/.mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/usr/local/etc/mpv/lua-settings/osc.conf'
[osc] lua-settings/osc.conf not found. 
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[cplayer] mouse_leave script-binding osc/__keybinding2
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[cplayer] mouse_btn2 script-binding osc/__keybinding5
[cplayer] mouse_btn0_dbl ignore
[cplayer] shift+mouse_btn0_dbl ignore
[cplayer] mouse_btn2_dbl ignore
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[input, ]
[cplayer] Run command: define-section, flags=0, args=[input_osc, del script-binding osc/__keybinding6
[cplayer] , default]
[cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading script @ytdl_hook.lua...
[global] config path: 'scripts' -/-> '/root/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/root/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[ytdl_hook] loading mp.defaults
[cplayer] Run command: disable-section, flags=0, args=[input]
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] config path: 'scripts' -/-> '/root/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/root/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[global] config path: 'watch_later' -> '/root/.config/mpv/watch_later'
[cplayer] Playing: ../VideoClip/Rings_2x2.mp4
[cplayer] Running hook: ytdl_hook/on_load
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[file] Opening ../VideoClip/Rings_2x2.mp4
[file] Stream opened successfully.
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[lavf] avformat_find_stream_info() finished after 86829 bytes.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[find_files] Loading external files in ../VideoClip/
[global] config path: 'sub/' -/-> '/root/.config/mpv/sub/'
[global] config path: 'sub/' -/-> '/root/.mpv/sub/'
[global] config path: 'sub/' -/-> '/usr/local/etc/mpv/sub/'
[global] config path: 'audio/' -/-> '/root/.config/mpv/audio/'
[global] config path: 'audio/' -/-> '/root/.mpv/audio/'
[global] config path: 'audio/' -/-> '/usr/local/etc/mpv/audio/'
[cplayer]  (+) Video --vid=1 (*) (h264)
[vo/opengl] Setting option 'backend' = 'drm-egl' (flags = 0)
[vo/opengl] Initializing OpenGL backend 'drm-egl'
[vo/opengl] Initializing KMS
[vo/opengl] Creating GBM device
[vo/opengl] Initializing GBM surface (1366 x 768)
[vo/opengl] Initializing EGL
[vo/opengl] Initializing EGL surface
[vo/opengl] GL_VERSION='3.0 Mesa 11.0.4'
[vo/opengl] Detected desktop OpenGL 3.0.
[vo/opengl] GL_VENDOR='Intel Open Source Technology Center'
[vo/opengl] GL_RENDERER='Mesa DRI Intel(R) Ivybridge Mobile '
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='1.30'
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 300/builtin.
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 110/GL_EXT_unpack_subimage.
[vo/opengl] Loaded functions for 300/GL_ARB_framebuffer_object.
[vo/opengl] Loaded functions for 300/GL_ARB_vertex_array_object.
[vo/opengl] Loaded functions for 300/GL_ARB_texture_rg.
[vo/opengl] Loaded functions for 320/GL_ARB_sync.
[vo/opengl] Loaded functions for 430/GL_ARB_debug_output.
[vo/opengl] Loaded functions for 310/GL_ARB_uniform_buffer_object.
[vo/opengl] Filterable half-float textures supported.
[vo/opengl] Preparing framebuffer
[vo/opengl] swap_control extension missing.
[vo/opengl] Reported display depth: R=0, G=0, B=0
[vo/opengl] 16 bit texture depth: 16.
[vo/opengl] Testing user-set FBO format (0x805b)
[vo/opengl] Create FBO: 16x16 -> 16x16
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Loading hwdec driver 'vaapi-glx'
[vo/opengl] Loading failed.
[vd] Container reported FPS: 23.976000
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd] Opening video decoder lavc:h264
[vd] Probing 'vaapi'...
[vo/opengl] Loading hwdec driver 'vaapi-glx'
[vo/opengl] Loading failed.
[vd] VO does not support requested hardware decoder, or loading it failed.
[vd] Using software decoding.
[vd] Detected 4 logical cores.
[vd] Requesting 5 threads for decoding.
[vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
[cplayer] Starting playback...
[vd] Using software decoding.
[vd] Decoder format: 1920x1920 yuv420p auto/auto CL=mpeg2/4/h264
[vf] Video filter chain:
[vf]   [in] 1920x1920 yuv420p bt.709/limited CL=mpeg2/4/h264
[vf]   [out] 1920x1920 yuv420p bt.709/limited CL=mpeg2/4/h264
[cplayer] VO: [opengl] 1920x1920 yuv420p
[cplayer] VO: Description: Extended OpenGL Renderer
[vo/opengl] Resize: 1366x768
[vo/opengl] Window size: 1366x768
[vo/opengl] Video source: 1920x1920 (1:1)
[vo/opengl] Video display: (0, 0) 1920x1920 -> (299, 0) 768x768
[vo/opengl] Video scale: 0.400000/0.400000
[vo/opengl] OSD borders: l=299 t=0 r=299 b=0
[vo/opengl] Video borders: l=299 t=0 r=299 b=0
[vo/opengl] Testing user-set FBO format (0x805b)
[vo/opengl] Create FBO: 16x16 -> 16x16
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Texture for plane 0: 1920x1920
[vo/opengl] Texture for plane 1: 960x960
[vo/opengl] Texture for plane 2: 960x960
[vo/opengl] Reinit rendering.
[cplayer] set video colors output-levels=0 
[vo/opengl] recompiling a shader program:
[vo/opengl] [  1] color.x = 1.000000 * vec4(texture(texture0, texcoord0)).x;
[vo/opengl] [  2] color.y = 1.000000 * vec4(texture(texture1, texcoord1)).x;
[vo/opengl] [  3] color.z = 1.000000 * vec4(texture(texture2, texcoord2)).x;
[vo/opengl] [  4] // color conversion
[vo/opengl] [  5] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[vo/opengl] [  6] color.a = 1.0;
[vo/opengl] [  7] // color management
[global] config path: 'fonts' -/-> '/root/.config/mpv/fonts'
[global] config path: 'fonts' -/-> '/root/.mpv/fonts'
[global] config path: 'fonts' -/-> '/usr/local/etc/mpv/fonts'
[global] config path: 'subfont.ttf' -/-> '/root/.config/mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/root/.mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/usr/local/etc/mpv/subfont.ttf'
[global] config path: 'fonts.conf' -/-> '/root/.config/mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/root/.mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/usr/local/etc/mpv/fonts.conf'
[osd/libass] Setting up fonts...
[osd/libass] Done.
[osd/libass] fontconfig: cannot find font 'sans-serif', falling back to 'Droid Sans Fallback'
[cplayer] first video frame after restart shown
[cplayer] playback restart complete
[cplayer] Run command: quit, flags=9, args=[4]
[cplayer] EOF code: 6  
[vd] Uninit video.
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Quit)
[ytdl_hook] Exiting...
[osc] Exiting...

**Comment by kevmitch** [comment]
> Should I rebuild mpv in new PC?

Yes
