### ISSUE TITLE
Have to toggle Fullscreen 3 times when flag set in config

### ISSUE THREAD

**Issue by Efinr** [mpv-player/mpv#2969]
Added the 'fullscreen' flag to the config.
MPV starts in fullscreen like it is told to, but to go into windowed mode for the first time, I have to toggle fullscreen 3 times - double clicking works, too. Replacing the first or third time with the Escape-key works, but the second does not.
I'm running it on linux (elementary OS).

**Comment by kevmitch** [comment]
Sounds a lot like #2072.

**Comment by wm4** [comment]
What window manager, what mpv version?

**Comment by Efinr** [comment]
Window manager is Gala
MPV sais it is version 'git-d8b27ee'

**Comment by wm4** [comment]
Yes, Gala is another mutter based thing, thus a duplicate.
