### ISSUE TITLE
Audio output stuck at "stereo" when using optical out (OSX)

### ISSUE THREAD

**Issue by JoRod94** [mpv-player/mpv#2975]
So my surround sound system is pretty old, so it only has optical in. I bought a optical to 3.5mm adapter for my Macbook Pro (which work since the MBP 3.5mm port works for that). Problem is, OSX doesn't allow for mpv to detect a 5.1 option (even the MIDI setup app detects digital out as strictly stereo).

VLC works for this, and outputs 5.1 audio when the file has it, so it must be possible. I've tried forcing 5.1 but it always outputs stereo.

LOG (Relevant portion):
[ad] Codec list:
[ad]     spdif:dts - libavformat/spdifenc audio pass-through decoder
[ad]     lavc:dca (dts) - DCA (DTS Coherent Acoustics)
[ad]     spdif:dts-hd (dts) - libavformat/spdifenc audio pass-through decoder
[ad] Opening audio decoder spdif:dts
[ad] Selected audio codec: libavformat/spdifenc audio pass-through decoder [spdif:dts]
[cplayer] Starting playback...
[af] Audio filter chain:
[af]   [in] 48000Hz stereo 2ch spdif-dts
[af]   [out] 48000Hz stereo 2ch spdif-dts
[af]   [ao] 48000Hz stereo 2ch spdif-dts
[ao] Trying audio driver 'coreaudio'
[ao/coreaudio] requested format: 48000 Hz, stereo channels, spdif-dts
[ao/coreaudio] redirecting to coreaudio_exclusive
[ao/coreaudio_exclusive] requested format: 48000 Hz, stereo channels, spdif-dts
[ao/coreaudio_exclusive] selected audio output device: Built-in Output (63)
[ao/coreaudio_exclusive] Using substream 0/1.
[ao/coreaudio_exclusive] our format: 48000.0Hz 16bit 3cac [12][4bpp][1fbp][4bpf][2ch] int LE S packed (spdif-ac3)
[ao/coreaudio_exclusive] -  192000.0Hz 24bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  176400.0Hz 24bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  96000.0Hz 24bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  88200.0Hz 24bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  48000.0Hz 24bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  44100.0Hz 24bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  32000.0Hz 24bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  192000.0Hz 20bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  176400.0Hz 20bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  96000.0Hz 20bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  88200.0Hz 20bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  48000.0Hz 20bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  44100.0Hz 20bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  32000.0Hz 20bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] -  192000.0Hz 16bit mcpl [12][4bpp][1fbp][4bpf][2ch] int LE S packed (s16)
[ao/coreaudio_exclusive] -  176400.0Hz 16bit mcpl [12][4bpp][1fbp][4bpf][2ch] int LE S packed (s16)
[ao/coreaudio_exclusive] -  96000.0Hz 16bit mcpl [12][4bpp][1fbp][4bpf][2ch] int LE S packed (s16)
[ao/coreaudio_exclusive] -  88200.0Hz 16bit mcpl [12][4bpp][1fbp][4bpf][2ch] int LE S packed (s16)
[ao/coreaudio_exclusive] -  48000.0Hz 16bit mcpl [12][4bpp][1fbp][4bpf][2ch] int LE S packed (s16)
[ao/coreaudio_exclusive] -  44100.0Hz 16bit mcpl [12][4bpp][1fbp][4bpf][2ch] int LE S packed (s16)
[ao/coreaudio_exclusive] -  32000.0Hz 16bit mcpl [12][4bpp][1fbp][4bpf][2ch] int LE S packed (s16)
[ao/coreaudio_exclusive] -  96000.0Hz 16bit 3cac [76][6144bpp][1536fbp][0bpf][2ch] int LE S packed (spdif-ac3)
[ao/coreaudio_exclusive] -  48000.0Hz 16bit 3cac [76][6144bpp][1536fbp][0bpf][2ch] int LE S packed (spdif-ac3)
[ao/coreaudio_exclusive] -  44100.0Hz 16bit 3cac [76][6144bpp][1536fbp][0bpf][2ch] int LE S packed (spdif-ac3)
[ao/coreaudio_exclusive] setting stream physical format: 48000.0Hz 16bit 3cac [76][6144bpp][1536fbp][0bpf][2ch] int LE S packed (spdif-ac3)
[ao/coreaudio_exclusive] format in use before switching: 44100.0Hz 24bit mcpl [4][8bpp][1fbp][8bpf][2ch] int LE S (-)
[ao/coreaudio_exclusive] actual format in use: 48000.0Hz 16bit 3cac [76][6144bpp][1536fbp][0bpf][2ch] int LE S packed (spdif-ac3)
[ao/coreaudio_exclusive] input channel layout:
[ao/coreaudio_exclusive] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio_exclusive]  - description 0: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio_exclusive]  - description 1: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio_exclusive] mp chmap: unknown2
[ao/coreaudio_exclusive] input channel layout:
[ao/coreaudio_exclusive] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio_exclusive]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio_exclusive]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio_exclusive] mp chmap: stereo
[ao/coreaudio_exclusive] Channel layouts:
[ao/coreaudio_exclusive]  - stereo
[ao/coreaudio_exclusive]  - mono
[ao/coreaudio_exclusive] result: stereo
[ao/coreaudio_exclusive] virtual format 48000.0Hz 16bit 3cac [76][6144bpp][1536fbp][0bpf][2ch] int LE S packed (spdif-ac3)
[ao/coreaudio_exclusive] Latency property cntl: 5 frames
[ao/coreaudio_exclusive] Latency property zisf: 1536 frames
[ao/coreaudio_exclusive] Latency property tfas: 96 frames
[ao/coreaudio_exclusive] base latency: 34104 microseconds
[ao/coreaudio_exclusive] using soft-buffer of 9728 samples.
[cplayer] AO: [coreaudio_exclusive] 48000Hz stereo 2ch spdif-dts
[cplayer] AO: Description: CoreAudio Exclusive Mode

**Comment by lachs0r** [comment]
S/PDIF only has enough bandwidth for an uncompressed stereo signal. To get surround sound, you must use either AC-3 or DTS. For files that already use this codec, you might need the `--audio-spdif` option; for everything else you need to use the `lavcac3enc` audio filter.

**Comment by lachs0r** [comment]
Oh, also, even though mpv shows stereo output with SPDIF passthrough, the signal will be unchanged, i.e. have as many channels as the DTS stream in your example log. You should be hearing surround sound.

**Comment by wm4** [comment]
> [cplayer] AO: [coreaudio_exclusive] 48000Hz stereo 2ch spdif-dts

It's just passing through DTS data here, so most likely 5.1. The "2ch" means nothing and is just how the spdif protocol works.

**Comment by JoRod94** [comment]
Got it working with --ad=spdif:dts, thank you.
