### ISSUE TITLE
http streaming problem

### ISSUE THREAD

**Issue by xswqaz** [mpv-player/mpv#2977]
Failed to http tcp ts streaming 
It was ok in vlc
No response after playing

`
hostname:Downloads user$ mpv --version
mpv 0.16.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Mon Feb 29 21:32:37 PST 2016
ffmpeg library versions:
   libavutil       55.17.103
   libavcodec      57.24.102
   libavformat     57.25.100
   libswscale      4.0.100
   libavfilter     6.31.100
   libswresample   2.0.101
ffmpeg version: 3.0

hostname:Downloads user$ mpv http://192.168.88.162:8080/27
Playing: http://192.168.88.162:8080/27

Exiting... (Quit)
`

**Comment by xswqaz** [comment]
I found it looking for youtube-dl 
I rename youtuebe-dl to another name and fixed

**Comment by ChrisK2** [comment]
just use `--no-ytdl` when it gets in the way.
