### ISSUE TITLE
Random segfaults with newer FFmpeg

### ISSUE THREAD

**Issue by qyot27** [mpv-player/mpv#2979]
I'm not exactly sure whether this is due to some silent API breakage that mpv needs to account for*, or whether it's solely on FFmpeg's side, but when linked against either FFmpeg's git HEAD or the release/3.0 branch, mpv starts throwing segfaults under pretty random conditions (sometimes invoking the same command several times will finally work after several segfaults, or it'll only work the first time and then segfault every time after).

*something like this was mentioned in https://github.com/FFMS/ffms2/issues/256, and it does seem that other things (like FFMS2 and x264) that link against the same build that causes trouble for mpv also causes trouble for those projects too.

About the only constant is that it happens whenever libavformat is used, since I could use the internal MKV demuxer and never have this problem, but if I tried to play back an MKV file with --demuxer lavf, then the segfaults would occur.  Likewise, short files didn't seem to trip it, or at least trip it as quickly: a 10-second segment seemed fine, a 30-second segment started throwing segfaults after one or two invocations, a 60-second segment either only worked once or exhibited the same problem as the full-length files did (these were all done with a 720p60 sample).

If I link mpv against release/2.8, the issue seems to go away and no segfaults occur.

Windows 10 Home 32bit
Atom Z3735F (Silvermont)
2GB RAM
mpv git HEAD, static
FFmpeg release/3.0 or git HEAD, static

**Comment by wm4** [comment]
Can't reproduce.

**Comment by Xuno** [comment]
This is our mpv-1.dll file based on git-042ca84 that we compiled with the following parameters for x64 Windows PC
```
$ ./waf configure CC=gcc --enable-libmpv-shared --enable-static-build --enable-gpl3 --prefix=/mingw64
```
We uploaded [mpv-1.zip] to (https://github.com/mpv-player/mpv/files/183190/mpv-1.zip)

Can we get your dll file with enabled-gpl3 for testing at our side?

**Comment by qyot27** [comment]
After a little more testing, it looks like I can make the segfaults in mpv go away if I build FFmpeg with all of its optimizations disabled.  I'll need to identify exactly whether it's the cpu march flags that do it or the other optimizations, but this now looks very much like a compilation settings issue (it's just strange it would suddenly start happening between 2.8 and 3.0/HEAD).  I'll close this issue.

**Comment by qyot27** [comment]
I believe I've figured out exactly what caused it: a commit to FFmpeg from Feb 9th that changed the optimization settings on GCC 4.9 or higher to not disable tree vectorization anymore when using [the default opt level of] -O3.  If I add -fno-tree-vectorize to FFmpeg's extra-cflags to force the old behavior, then mpv is fine.  I was using GCC 5.3.0.

In the commit message, it says that with the change, FATE still passed on x86-64; maybe it still miscompiles under 32-bit.
