### ISSUE TITLE
[Question] Any reason not to use "scale=gaussian"?

### ISSUE THREAD

**Issue by uid313** [mpv-player/mpv#2983]
I recently got my hands on a NUC with a Intel N3150 SoC.
After testing different scalers (since both `ewa_lanczos` & `haasnsoft` were too much for this chip), I mostly settled upon `bicubic_fast` & `gaussian`.
However, I noticed that `gaussian` produced a much clearer picture than the rest; after reading up a bit about this, it became clear why:
A Gaussian filter doesn't produce any ringing by design! (Was news for me...)
Therefore, no reason to activate `scale-antiring` at all.
Also, both `bicubic_fast` & `gaussian` produced no visible aliasing, but when comparing still images, `bicubic_fast` looked blurrier than `gaussian` (though I had read that it should be in fact the other way around, i.e. a gaussian filter being blurrier, since it is used to blur images, and a bicubic filter should be perceived as being sharper, thanks to excessive amounts of ringing).

So, any objection to `scale=gaussian` being used (or maybe even being the default for `opengl-hq`, since I found that `spline36` produces both visible aliasing & ringing)?

**Comment by Hrxn** [comment]
I'm not sure, if you don't have any problems with aliasing artifacts, why not?

Gaussian should add more blur, that is right, but this depends on the example or the source material, and if it works for you...

**Comment by uid313** [comment]
> Gaussian should add more blur, that is right

Interestingly, it is the other way around for me, `bicubic_fast` looks blurrier than `gaussian`!

Also, compare these images (many thanks @haasn for making these available):

https://github.com/haasn/mpvhq-upscalers/blob/master/rose/bicubic.png
https://github.com/haasn/mpvhq-upscalers/blob/master/rose/gaussian.png

https://github.com/haasn/mpvhq-upscalers/blob/master/gradients/bicubic_fast.png
https://github.com/haasn/mpvhq-upscalers/blob/master/gradients/gaussian.png

https://github.com/haasn/mpvhq-upscalers/blob/master/baby/bicubic_fast.png
https://github.com/haasn/mpvhq-upscalers/blob/master/baby/gaussian.png

To me, `bicubic_fast` looks blurrier, but produces less aliasing (with the downside of ringing).
Still, `gaussian` doesn't produce any more visible aliasing than `spline36`, so I wonder why it specifically was made the default for `opengl-hq`.

**Comment by Hrxn** [comment]
Well, based on these sample images, I'd agree with you.

I don't think the difference is that significant, but if you know what you're looking for.....

I have no idea why `spline36` is the default, I have wondered about that as well. The documentation is a bit short when it comes to the different scalers, in my opinion.
