### ISSUE TITLE
Subtitles don't get back to their original position

### ISSUE THREAD

**Issue by sCreami** [mpv-player/mpv#2984]
> mpv git-3353923 (but happens since a while)
OS X 10.9.5

When playing a video file. The subtitles may not suit my taste so I force my own ass style on them. But when I disable my custom style, they don't get back to their starting position. It happens in every file with ass style but I don't know if it's related.

Here's an example:

Starting position,
![coalgirls _fullmetal_alchemist_brotherhood_07_ 1280x720_blu-ray_flac _ 737cee6c -01](https://cloud.githubusercontent.com/assets/1769603/13961186/cb897066-f05b-11e5-899c-a6e4aecb01e8.jpg)

Forcing my style,
![coalgirls _fullmetal_alchemist_brotherhood_07_ 1280x720_blu-ray_flac _ 737cee6c -02](https://cloud.githubusercontent.com/assets/1769603/13961185/cb213fe6-f05b-11e5-88ec-6a3dce719131.jpg)

Going back to original,
![coalgirls _fullmetal_alchemist_brotherhood_07_ 1280x720_blu-ray_flac _ 737cee6c -04](https://cloud.githubusercontent.com/assets/1769603/13961187/cb8c3468-f05b-11e5-88e3-297bb7533dc8.jpg)

As you can see their new position is (_always_) lower than the starting one.
I didn't resize the window between those 3 screenshots.

**Comment by wm4** [comment]
Could be due to collision detection in libass. If so, it can't be fixed.

**Comment by sCreami** [comment]
If it can't be helped...

**Comment by wm4** [comment]
Well, I'm not sure if it's that problem, but it's very likely.
