### ISSUE TITLE
mpv has problems with DTS audio tracks

### ISSUE THREAD

**Issue by habaneros** [mpv-player/mpv#2985]
I have a .mkv file which contains two audio tracks: AC-3 & DTS.
With AC-3 I get zero dropped frames, however the same file with DTS causes massive amounts of framedrops!
At first I thought it could be my hardware (Intel Braswell), however then I found this from a Raspberry Pi user:

> mkv with 5.1 DTS-MA - OK
> BDMV (full bluray folder structure) with 7.1 DTS-MA - OK
> CPU usage on pi2 barely got up to 15%/core.

So it can't be a hardware problem...

Anyone else seen the same or have an explanation for the problem?

**Comment by wm4** [comment]
Most likely a timestamp problem. Impossible to tell without a sample.

**Comment by habaneros** [comment]
If it indeed is a timestamp problem, could the same file be played without any problems with the AC-3 track (i.e. the timestamp problem lies with only the DTS track)?

**Comment by wm4** [comment]
Yes, or with audio disabled.

**Comment by lachs0r** [comment]
Reopen if you have a sample.
