### ISSUE TITLE
Stream recording feature

### ISSUE THREAD

**Issue by strelec** [mpv-player/mpv#2988]
It could be possible to have a key reserved to stop and start recording.

Currently, it is not possible to record just pieces of the stream.

**Comment by sCreami** [comment]
I've got a trick to do this by adding this line in input.conf
`Meta+s run youtube-dl "${path}" -o ~/Desktop/%(title)s.%(ext)s; show_text "Downloading ${filename}"`
But sadly it has the issue that you need to kill the process yourself to stop the recording.

**Comment by strelec** [comment]
My guess is that would always start recording from the start of the file/stream.

**Comment by sCreami** [comment]
You can already achieve this by making a lua script using `mp.register_event("start-file", ...)` to start at playback and `utils.subprocess(t)` to run youtube-dl.

**Comment by sCreami** [comment]
> It would be good to have something like that:
   1. It starts recording when you press Ctr+R
   2. A red dot appears in the overlay gui.
   3. It stops recording when you press Ctr+R again and properly finalizes the file.

It's the job for a script. You can implement it yourself with the help at https://mpv.io/manual/master/#lua-scripting or wait for someone with enough time to write it.

**Comment by wm4** [comment]
Makes sense to want this, and people are getting tricked by --stream-capture or --stream-dump all the time (these don't do what is requested here). Other players have such features as well.

Unlikely that I'll spend time on such a feature, though.

**Comment by wm4** [comment]
By the way, it would be pretty easy to add a default script and key binding that reopens the file and encodes from it.

I'm not sure if users want "real" stream recording that doesn't require redownloading the data and which works with unseekable live streams and such.

**Comment by cranes-bill** [comment]
Hi, i'm posting here to avoid opening a new issue just for question:
Is there any way to dump live hls stream?

**Comment by wm4** [comment]
This probably works for hls?

**Comment by wm4** [comment]
Oh, lacking context here. This was actually implemented as ``--record-file``. Highly experimental.

**Comment by cranes-bill** [comment]
That just play the stream and produces an empty file. Should i append any extra flag?

**Comment by danielkza** [comment]
If anyone else is having issues with this feature, try picking a different output file extension. I was trying to record an HLS stream to an .mp4 file, which doesn't work, but wasn't easy to guess from the error message (.ts is needed instead).

**Comment by francisuk1989** [comment]
i just get
[input] No key binding found for key 'Ctrl+r'.
