### ISSUE TITLE
rtmp error: [ffmpeg] Closing connection: NetStream.Play.StreamNotFound

### ISSUE THREAD

**Issue by zaza42** [mpv-player/mpv#2992]
I've tried to watch revision livestream, but mpv failed:
$ mpv rtmp://revision.scenesat.com/live/mainhall       
Playing: rtmp://revision.scenesat.com/live/mainhall
[ffmpeg] HandShake: client signature does not match!
[ffmpeg] Closing connection: NetStream.Play.StreamNotFound
Failed to open rtmp://revision.scenesat.com/live/mainhall.

Exiting... (Errors when loading file)

With google I've found a workaround: 
$ mpv "rtmp://revision.scenesat.com/live/mainhall live=1"                    
Playing: rtmp://revision.scenesat.com/live/mainhall live=1
[ffmpeg] HandShake: client signature does not match!
[ffmpeg] rtmp server sent error
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (mp3)
File tags:
 Title: 
AO: [pulse] 44100Hz stereo 2ch s16

...and plays smoothly.

Could you add this "live=1" trick into man/docs or hardcode it?

**Comment by wiiaboo** [comment]
That "trick" only works with librtmp, so it probably won't be hardcoded.
You should probably report this to FFmpeg as well on their tracker.
