### ISSUE TITLE
Windows 10, 64-bit: requests for OpenGL return wrong version

### ISSUE THREAD

**Issue by Warblefly** [mpv-player/mpv#2995]
mpv version: latest, compiled from source almost daily.

This system has Intel G45 drivers that always return their OpenGL version as 2.1.0 to all programs and tests except mpv. Instead, mpv sees version 1.1.0. This behaviour began about three months ago, so I switched to using direct3d as my video output. However, it means I can't compare the performance of OpenGL and Direct3D. 

mpv reports as follows:

```
[vo/opengl] Initializing OpenGL backend 'win'
[vo/opengl] The OpenGL driver does not support OpenGL 3.x
[vo/opengl] GL_VERSION='1.1.0'
[vo/opengl] Detected desktop OpenGL 1.1.
[vo/opengl] GL_VENDOR='Microsoft Corporation'
[vo/opengl] GL_RENDERER='GDI Generic'
[vo/opengl] Combined OpenGL extensions string:
[vo/opengl]  GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
[vo/opengl] Loaded functions for 110/GL_EXT_unpack_subimage.
[vo/opengl] Detected suspected software renderer.
[vo/opengl] WGL_EXT_swap_control missing.
[vo/opengl] Suspected software renderer or indirect context.
[vo/opengl] At least OpenGL 2.1 or OpenGL ES 2.0 required.
[vo/opengl/win32] uninit
[cplayer] Error opening/initializing the selected video_out (-vo) device.
[lavf] packets=0, bytes=0, active=0, more=0
[cplayer] Video: no video
```

"GDI Generic" is the Microsoft-supplied opengl32.dll fallback driver. I wonder why mpv is selecting this in preference to the installed Intel driver, that all other programs pick up, and use?

Please let me know if you need any more debugging information.

**Comment by wm4** [comment]
mpv doesn't specifically "search" or "load" any drivers, it just uses the normal win32 API. So I doubt it's our bug.

**Comment by lachs0r** [comment]
This is very strange indeed, and I don’t see what we could do about it.
I suggest trying one of my builds (they use ANGLE) and considering the problem solved if that works.
