### ISSUE TITLE
[feature request] OSD verbose information like KODI

### ISSUE THREAD

**Issue by markg85** [mpv-player/mpv#3000]
Hi,

Specially when testing if some output is working (vdpau, vaapi, software encoding, framedrops, etc..) i find myself looking at the command output of mpv. While that works ok, i'd really like to have an OSD verbose mode like KODI has (see the attached image).

![codec_info](https://cloud.githubusercontent.com/assets/49061/14078857/7e48631e-f4f9-11e5-974e-eb216f4d4b59.png)

**Comment by haasn** [comment]
Try https://github.com/Argon-/mpv-stats/

**Comment by wm4** [comment]
We intentionally don't provide such a thing because there is a lot of information you could be interested in, which would result in lots of clutter. You can construct one using ``--osd-msg1`` and property expansion. mpv-stats is an extreme approach to this (which also includes more formatting).
