### ISSUE TITLE
Is there a proper way to restart playback at the end of a video?

### ISSUE THREAD

**Issue by garoto** [mpv-player/mpv#3001]
When "keep-open" is set to "yes", at end of playback, the video will pause at the last frame and stay there. What If I want to restart playing the same video again?

Currently, I have this keybinding set up that somewhat solves the problem, but the player will still be in a paused state requiring a second key press to start playing:

`BS seek 0 absolute-percent ; show_text "Seek to 0% - ${playback-time} / ${duration} (${percent-pos}%)" 2000 0`

I tried adding a "; cycle pause" to the end of that binding line, and while it works when the video indeed reached its end, it will pause the video if used while playback is still running.

Is there a better approach to accomplish this?

**Comment by haasn** [comment]
You could just `set pause no` instead of cycling through it.

**Comment by garoto** [comment]
Adding ` ; set pause no` to the BS keybinding seems to resolve my issue. Thanks a lot haasn, I'd need  years to figure that one out on my own :blush:

**Comment by mindfulsource** [comment]
I want to set `b` (for 'beginning') to do this, in this context.

But both `b seek 0 absolute-percent; set pause no` and `b seek 0 absolute-percent; cycle pause` still require the `b` to be pressed a second time to resume playback after going back to beginning.

Is there a different unpause we should use these days?

**Comment by garoto** [comment]
I believe this commit fixes the behavior you describe: https://github.com/mpv-player/mpv/commit/fcf0b80dc9dd3ed29e45451bda6315ce0c2b4729

**Comment by mindfulsource** [comment]
You're correct, I updated to the current build on macOS using `brew install --HEAD mpv` and it's all good, thank you!

**Comment by github-account1111** [comment]
I'm using the latest build and getting the behavior @mindfulsource described. No matter whether I put `set pause no` before or after seek, it doesn't unpause.

**Comment by oe-d** [comment]
You can use [my script](https://github.com/oe-d/control) to do that.

In input.conf: `Space      script-binding control/cycle-pause`

**Comment by blueray453** [comment]
> You can use [my script](https://github.com/oe-d/control) to do that.
> 
> In input.conf: `Space script-binding control/cycle-pause`

This is a great solution. How the play button can be changed to replay (reload) button (both visually and functionally) after the video is finished.
