### ISSUE TITLE
Refactor video-zoom to make it logarithmic (or make 1.0 the native value)

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#3004]
Video-zoom should be on a log scale. Currently, the “intended” way to work with video-zoom is that you should be adding or subtracting amounts from it to zoom in or out.

But this results in irregular zoom amounts, and e.g. once you zoom out enough so that it hits -1.0, the video just disappears completely, which doesn't really make a whole lot of sense (concerning the option).

In reality, I think when zooming in our out, it's more likely that the user wants to *modify* the current scale, e.g. always zooming in or out by 10% relative to what's currently being displayed.

One way of accomplishing this would be to make video-zoom a flat multiplier centered around 1.0, then you could use “multiply” to interact with it. This also has the advantage of ```--video-zoom=4``` on the command line actually giving you a 4x multiplication of the image. (Ignoring for now the fact that mpv also multiplies in the difference between the window and source size) This has the downside that some values make little sense, e.g. --video-zoom=0 or negative values. And also, the scale is “lopsided” in that zooming in makes the video-zoom value explode out to infinite, and zooming out squishes it into the space between 0 and 1.

Another way of accomplishing it would be to make video-zoom logarithmic, so that you could keep on adding or subtracting amounts all the way to infinity, to get a consistent difference every time.

I think the latter approach makes the most sense in terms of backwards compatibility and keybinding-friendliness.

**Comment by lamarpavel** [comment]
Why not two settings:

1. __zoom-add=n__ lets you zoom logarithmically, allwoing keybindings that always add/subtract 10% etc
2. __zoom-by=n__ lets you zoom by factor of n, allowing keybindings that always zoom by 2x or 0.5x etc

**Comment by haasn** [comment]
I don't think two settings are necessary here.

I thought a bit more and I do really prefer a log scale, even if only for the fact that ```--video-zoom=0.1``` will have the same behavior as now, as would any ```add video-zoom 0.1``` keybindings. (The difference being, of course, in the scaling on successive presses)

**Comment by wm4** [comment]
By the way, I don't feel like backwards compatibility is all that important here. The options operate in an awkward enough way that getting exact results with them is hard anyway, so users most likely have been using "approximate" methods, if any.

**Comment by haasn** [comment]
> I thought a bit more and I do really prefer a log scale, even if only for the fact that --video-zoom=0.1 will have the same behavior as now

Note, in the final implementation this is no longer true, because instead of going for some odd broken ratio just to preserve ``--video-zoom=0.1``'s exact semantics, I went for powers of two instead. It's similar enough for the difference to be negligible but much cleaner and more useful in the long run.
