### ISSUE TITLE
with dvdnav, seek forward sometimes goes backwards

### ISSUE THREAD

**Issue by archenemies** [mpv-player/mpv#3005]
Under DVD playback with libdvdnav, sometimes pressing the left or right arrow keys causes the movie to seek in the wrong direction.

I've experienced this problem with several DVDs. To reproduce, for example one can do something like this (with the Netflix "The Green Mile" DVD):

```
dvdbackup -M -o green-mile -i /dev/sr0
# skip ahead 3 hours and 6 minutes to credits
mpv -dvd-device green-mile/The\ Green\ Mile/ dvdnav://0 --start=03:06:00
```

Hit "O" to show OSD. Pressing the left arrow causes the displayed time to go forward rather than back. Pressing the right arrow also causes the time to go forward. Replacing "dvdnav" with "dvdread" in the command line fixes the problem.

In most of the rest of the DVD, seeking behaves correctly, but sometimes seeking backwards gets stuck at a certain point, and often the increments are not 5 seconds. With some DVDs ("My Neighbors the Yamadas") the problem seems to be more severe, to the point that seeking doesn't seem to work anywhere (as I recall).

Passing `--hr-seek=yes` fixes the direction problem at position 03:06:00, but the increments are much smaller than 5 seconds.

**Comment by wm4** [comment]
This would require proper seeking support in libdvdnav. Not our problem.

**Comment by archenemies** [comment]
Not your problem that seeking is broken? Wow!

**Comment by wm4** [comment]
It's broken in libdvdnav, so we can't do anything about it.

**Comment by archenemies** [comment]
OK... Have you informed the dvdnav people that it's broken? Have you considered switching back to dvdread as the default, which is not broken?

I'm just trying to ensure that my bug report goes somewhere, other than "into the void".

**Comment by wm4** [comment]
I think the dvdnav people have been aware about this for years, and there was a half-baked API function that sort of worked, but was not exported in a header. kodi/xbmc used this "inofficial" function. Later videolan forked the libs and effectively overtook maintainership. That should give you an overview over the chaos. If you want your bug report to be honored, report it to dvdnav (whereever they are today), and then report back here.

**Comment by archenemies** [comment]
Have you considered switching back to dvdread as the default, which is not broken?

Where should I report the dvdnav bug? I think you should do it, since reporting a bug in mpv should be as easy as reporting a bug in mpv. But if you want me to do it, at least tell me where you're pulling the current version of the library from.

**Comment by wm4** [comment]
The mpv dvdread code is unmaintained and unmaintainable code that duplicates half of dvdnav (dvdnav was basically a cleanup of it, and the proper way to do it, just with worse seeking).

**Comment by archenemies** [comment]
Why do you only answer one question per message?

**Comment by CounterPillow** [comment]
>I think you should do it, since reporting a bug in mpv should be as easy as reporting a bug in mpv.

But it's not a bug in mpv.

>Where should I report the dvdnav bug?

Try the [libdvdnav-devel mailing list](https://mailman.videolan.org/listinfo/libdvdnav-devel).

>But if you want me to do it, at least tell me where you're pulling the current version of the library from.

mpv has no official builds. Thus, wm4 isn't pulling the library from anywhere. Especially considering his dislike for all things optical media.

**Comment by archenemies** [comment]
> mpv has no official builds

I see, thank you. That helps clarify this for me.
