### ISSUE TITLE
[question/feature request?] triggers manipulating multiple instances of mpv

### ISSUE THREAD

**Issue by v1kn** [mpv-player/mpv#3007]
Having discovered the power and coolness aspect of lua scripting to extend `mpv`, I have browsed through the majority of the documentation, but haven't found commands options or properties, that would let one instance of mpv manipulate another when it starts. For example:  

When video A is playing, and subsequently video B starts, video A gets paused and minimised.  

Is it possible for `mpv` to recognize multiple instances of itself and act upon them? 
Thank You

*Disclaimer: I am not a coder*

**Comment by wm4** [comment]
`--input-ipc-server` (which lets you use json IPC), or just implement such functionality in a script.
