### ISSUE TITLE
mpv (0.16.0) doesn't play iptv stream

### ISSUE THREAD

**Issue by wasp71** [mpv-player/mpv#3010]
mpv doesn't play iptv stream with error:
> 
[ffmpeg/video] mpeg2video: Invalid frame dimensions 0x0.
Error while decoding frame!
[ffmpeg/video] mpeg2video: Invalid frame dimensions 0x0.
Error while decoding frame!
[ffmpeg/video] mpeg2video: Invalid frame dimensions 0x0.
Error while decoding frame!
[ffmpeg/video] mpeg2video: Invalid frame dimensions 0x0.
Error while decoding frame!
> 

But vlc playnig is fine!
See example: ftp://ftp.vladiom.net/pub/Tempo/IPTV/vlc_record_Football_2_160331.ts

**Comment by wm4** [comment]
It takes a while until the stream shows up.

Blame ffmpeg's shitty ts demuxer.
