### ISSUE TITLE
WTF?

### ISSUE THREAD

**Issue by zaezsh** [mpv-player/mpv#3011]
[cplayer]    libavcodec      57.24.102
[cplayer]    libavformat     57.25.100
[cplayer]    libswscale      4.0.100
[cplayer]    libavfilter     6.31.100
[cplayer]    libswresample   2.0.101
[cplayer] ffmpeg version: 3.0
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/usr --bindir=/usr/bin --mandir=/usr/share/man --libdir=/usr/lib64 --docdir=/usr/share/doc/packages/mpv --confdir=/etc/mpv --enable-openal --enable-cdda --enable-libmpv-shared --enable-zsh-comp --enable-manpage-build --disable-sdl1 --disable-sdl2 --disable-build-date --disable-debug --enable-gpl3
[cplayer] List of enabled features: alsa any-gl asm atomic-builtins atomics audio-input av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-profile-name avframe-metadata avframe-skip-samples caca cdda cplayer desktop-gl dlopen drm dvbin dvdnav dvdread enca encoding fchmod gl gl-x11 glibc-thread-name glob gpl3 iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libm libmpv-shared librt libsmbclient libswresample libv4l2 linux-fstatfs lua nanosleep openal optimize oss-audio oss-audio-native plain-gl posix posix-or-mingw posix-spawn pthreads pulse resampler shm sse4-intrinsics subprocess termios tv tv-v4l2 vaapi vaapi-glx vaapi-hwaccel vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h x11 xext xinerama xrandr xss xv zlib zsh-comp
[global] config path: '' -> '/home/jone/.config/mpv'
[global] config path: 'mpv.conf' -> '/home/jone/.config/mpv/mpv.conf'
[global] config path: 'config' -> '/home/jone/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/home/jone/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/jone/.mpv/config'
[global] config path: 'mpv.conf' -> '/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/etc/mpv/config'
[cplayer] Reading config file /etc/mpv/mpv.conf
[cplayer] Setting option 'audio-pitch-correction' = 'no' (flags = 4)
[cplayer] Reading config file /home/jone/.config/mpv/config
[cplayer] Reading config file /home/jone/.config/mpv/mpv.conf
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -> '/home/jone/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/homejone/.mpv/input.conf'
[global] config path: 'input.conf' -> '/etc/mpv/input.conf'
[global] user path: '/etc/mpv/input.conf' -> '/etc/mpv/input.conf'
[ifo] Opening /etc/mpv/input.conf
[ifo/dvdnav] Opening /etc/mpv/input.conf
[bdmv/bluray] Opening /etc/mpv/input.conf
[file] Opening /etc/mpv/input.conf
[file] Stream opened successfully.
[input] Parsing input config file /etc/mpv/input.conf
[input] Input config file /etc/mpv/input.conf parsed: 0 binds
[global] user path: '/home/jone/.config/mpv/input.conf' -> '/home/jone/.config/mpv/input.conf'
[ifo] Opening /home/jone/.config/mpv/input.conf
[ifo/dvdnav] Opening /home/jone/.config/mpv/input.conf
[bdmv/bluray] Opening /home/jone/.config/mpv/input.conf
[file] Opening /home/jone/.config/mpv/input.conf
[file] Stream opened successfully.
[input] Parsing input config file /home/jone/.config/mpv/input.conf
[input] Input config file /home/jone/.config/mpv/input.conf parsed: 6 binds
[osc] Loading script @osc.lua...
[global] config path: 'scripts' -/-> '/home/jone/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/home/jone/.mpv/scripts'
... 

wtf, are you so now do??

**Comment by lachs0r** [comment]
WTF?

**Comment by Hrxn** [comment]
That issue title...
