### ISSUE TITLE
stop-screensaver=yes breaks xautolock

### ISSUE THREAD

**Issue by TheodoreGk** [mpv-player/mpv#3012]
Running mpv with xautolock will behave as expected. However, afterwards xautolock will not respond properly:

    ~ $ xautolock -disable
    Could not locate a running xautolock.
    ~ $ ps aux | grep [x]autolock
    guest      806  0.0  0.0  20116  1096 ?        S    09:56   0:00 xautolock -time 10 -locker systemctl suspend -detectsleep -corners ---- -notify 30 -notifier notify-send -u critical -t 10000 -- 'zzz in 30"'

**Comment by wm4** [comment]
mpv merely invokes xdg-screensaver.
