### ISSUE TITLE
Can't build for GPL 3 under gentoo.

### ISSUE THREAD

**Issue by paulguy** [mpv-player/mpv#3013]
No matter what I do I can't get a GPL3 build working under gentoo. By default it's disabled.  Tried creating a local overlay version of it with the disabled changed to enabled.  Looked in the build script which indicates it's just --gpl3.  Tried that, still doesn't work.  I hate this fucking software fucking copyright bullshit..  I just want fucking NNEDI3 back.  I see it's still in the source code and enabled by HAVE_GPL3 so I dunno what's going on with this crap.

**Comment by kevmitch** [comment]
As indicated by `./waf --help`, the correct option is `--enable-gpl3`.

**Comment by 5paceToast** [comment]
On the local flags:
`--gpl3` doesn't sound right
`./waf configure --help | grep gpl3` gives out `--enable-gpl3       enable GPL3 license [disable]`, which is `--enable-gpl3` and not `--gpl3`
Can you try that? (manual build, not as a part of an overlay, at least at first)

On Gentoo:
The licensing for nnedi is vague, (see [bug 571728](https://bugs.gentoo.org/show_bug.cgi?id=571728), which is why it's been disabled (at least until upstream properly (here!) clarifies the situation). Nnedi is considered a "rather minor feature", so the chances of that being resolved downstream are rather low.

**Comment by paulguy** [comment]
I've tried both in the script.  Neither reported an error.

**Comment by fhlfibh** [comment]
@paulguy 

Gentoo guys know about the issue, as you can see from ***5paceToast***'s link above (actually, it was me who filed that bug there). MPV people have no relation to this Gentoo situation (except that initially it was their idea to make GPL3 a separate option).

To enable NNEDI in Gentoo's MPV you have to a) enable using testing branch for mpv, b) set up your own local overlay, c) create there your own ebuild file for mpv adding a "gpl3" USE flag, and d) build mpv with this new USE flag enabled.

How to enable testing versions for certain packages https://wiki.gentoo.org/wiki/ACCEPT_KEYWORDS

How to set up a local overlay https://wiki.gentoo.org/wiki/Overlay/Local_overlay

One of my local ebuilds with "gpl3" flag added http://pastebin.com/EMexBj1f
Note the following bolded changes:

Add a "gpl3" flag and enable it by default:
>IUSE="+alsa archive bluray cdda +cli doc drm dvb +dvd +egl +enca encode gbm
    +iconv jack jpeg lcms +libass libav libcaca libguess libmpv lua luajit
    openal +opengl oss pulseaudio raspberry-pi rubberband samba sdl selinux
    test uchardet v4l vaapi vdpau vf-dlopen wayland +X xinerama +xscreensaver
    xv zsh-completion ***+gpl3***"

Disable (comment out) auto-disabling GPL3:
>***\#***       --disable-gpl3      \# Unclear license info. See Gentoo bug 571728.

Add enabling GPL3 somethere:
> --disable-debug-build   # Do not add -g to CFLAGS
      ***$(use_enable gpl3)***
      $(use_enable doc html-build)

Then you have to enable "gpl3" flag in make.conf, package.use or somewhere and rebuild MPV from your local overlay.

You will have to repeat this procedure after every MPV update.
Hope, I didn't forgot anything.

**Comment by kevmitch** [comment]
For what it's worth I would generally agree the gentoo people are over-thinking this. The mpv binary is released under gpl2 (or later) unless the --enable-gpl3 flag was used, in which case it is released as gpl3. The explicit use of the flag resolves any of the "confusion".

**Comment by paulguy** [comment]
@fhlfibh  I did get it working, it was just a bit annoying and I was mostly annoyed that any of that was even necessary. I was probably making a typo or something.

Also, I was a bit drunk when I wrote this issue so sorry about the language.
