### ISSUE TITLE
vertical video is displayed improperly

### ISSUE THREAD

**Issue by i026e** [mpv-player/mpv#3015]
It seems, mpv has a problem with displaying 3gp video that was shot vertically.
Only part of video is displayed correctly, another part is smeared. Rotating video by 90/270 degrees (mpv --video-rotate 90) results in normal presentation. ffplay shows no problem in both orientations

Here is  [screenshot](https://drive.google.com/open?id=0B-0OWg1AmVe1TW44T2Y4bUpTdWc) of the problem
[Screenshot](https://drive.google.com/open?id=0B-0OWg1AmVe1TTB3MmlPRVEzenM) when video was turned by 90 degrees
[Example](https://drive.google.com/open?id=0B-0OWg1AmVe1S3NkbThzYnY1UmM) of video

**Comment by wm4** [comment]
Update to git master. Though there are still some settings which might show a broken video with rotation applied (nnedi, I think).
