### ISSUE TITLE
SMI style tags are displayed as is

### ISSUE THREAD

**Issue by trustin** [mpv-player/mpv#3017]
Built from master. Debian 7.

I'm not exactly sure since when, but MPV started to display the style tags such as `<FONT COLOR=...>` in .SMI subtitle files as is rather than stripping them away or applying styles correctly.

![image](https://cloud.githubusercontent.com/assets/173918/14230247/edc5d9b2-f989-11e5-8269-b0ad9b518aee.png)

**Comment by wm4** [comment]
Works with a sample file I have (in fact the sample file which is used by ffmpeg to test this functionality).

Can you upload a non-working .smi file?

**Comment by wm4** [comment]
Actually, before you do this, against which ffmpeg version is mpv linked?

**Comment by trustin** [comment]
```
$ ffmpeg -v
ffmpeg version N-79143-g8ff0f6a Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --prefix=/usr --enable-shared --enable-gpl --enable-libmp3lame --enable-libx264 --extra-cflags='-march=native -O3' --extra-cxxflags='-march=native -O3'
  libavutil      55. 19.100 / 55. 19.100
  libavcodec     57. 30.100 / 57. 30.100
  libavformat    57. 29.101 / 57. 29.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 40.102 /  6. 40.102
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
```

I built ffmpeg from ffmpeg master. What branch would you recommend instead?

**Comment by trustin** [comment]
As a workaround, I used this script to convert .smi to .ass:

https://gist.github.com/trustin/e06fadcbca90985b1df4dafebd9f5d25

**Comment by wm4** [comment]
ffmpeg master is fine.

Still, mpv could be possibly linked or configured against another version, so either look at the pmp log for the version, or run mpv CLI without argument.

A sample would still be appreciated. You also can check if this is a ffmpeg issue with `ffmpeg -i file.smi out.ass`.

**Comment by lachs0r** [comment]
Guess we’re not getting a sample.
