### ISSUE TITLE
Define ICC profile in config file

### ISSUE THREAD

**Issue by GerhardR01** [mpv-player/mpv#3023]
Hi all,

I'm on a Mac and if I open mpv via terminal it is possible to load an icc profile:
mpv video.mp4 --vo=opengl:scale=lanczos:icc-profile=icc_profile.icc

I'm not shure how to define it in the config file for standard use.
I tried just a line with:
icc-profile=/path/icc_profile.icc
and also the whole argument of the terminal command:
vo=opengl:scale=lanczos:icc-profile=/path/icc_profile.icc

Both didn't work. How to do it the right way?

Thanks,
Gerhard

**Comment by haasn** [comment]
The latter should work, assuming the path is correct and you are not overriding the ‘vo’ option from the command line.

**Comment by GerhardR01** [comment]
Thanks! I found the solution:
I had to create an own mpv.conf file in ~/.config/mpv/ with the settings and not using the mpv.conf in the mpv package.
