### ISSUE TITLE
Youtube playlist improvement

### ISSUE THREAD

**Issue by nwgat** [mpv-player/mpv#3024]
when you copy and paste a playlist from youtube you sometimes get current playing + playlist, yet mpv does not play the playlist it only plays current playing

`mpv https://www.youtube.com/watch?v=XjD1Zg9My_E&list=PLyIFQr1wryPIFKOVSA7NjrxUbpe8UMN3L`

if i do this, it works
`mpv https://www.youtube.com/watch?list=PLyIFQr1wryPIFKOVSA7NjrxUbpe8UMN3L`

**Comment by wiiaboo** [comment]
Duplicate of https://github.com/mpv-player/mpv/issues/2592.

**Comment by wm4** [comment]
Closing then.
