### ISSUE TITLE
Drag&drop doesn't work for PathFinder

### ISSUE THREAD

**Issue by eugenesvk** [mpv-player/mpv#3025]
When running `mpv --profile=pseudo-gui` and drag&dropping a media file from PathFinder, nothing happens, the window just closes instead of opening the file. When doing the same thing from default Finder everything is fine. Would you please fix it so that PathFinder drag&drops also work?
Thanks

OS X 10.11.4
mpv 0.16.0 (installed with Homebrew)
PathFinder 7.3.2

**Comment by wm4** [comment]
Log?

**Comment by eugenesvk** [comment]
Where is the log located?

**Comment by Akemi** [comment]
i just tested it with PathFiner 7.4.1 and it worked without problems. is it still broken for your with the newest release?

**Comment by Akemi** [comment]
since there is no reply and it worked in my tests, closing it.

**Comment by eugenesvk** [comment]
Sorry to have missed your question, you're right, it's working just fine
