### ISSUE TITLE
CD Graphics video [lavc:cdgraphics] skips forward, gets off-sync with Karaoke track

### ISSUE THREAD

**Issue by clintonthegeek** [mpv-player/mpv#3027]
When playing a .cdg file (graphic file displaying lyrics for karaoke music) and accompanying audio track the seekbar skips forward immediately to the next animation in the file instead of pausing for the appropriate duration. This results in the lyrics getting off-sync with the audio track, and mpv skipping over intros, instrumental sections, or any part of a song where the graphics should be paused.

**Comment by richardpl** [comment]
Please provide files.

**Comment by clintonthegeek** [comment]
For some reason this bugtracker won't accept my zip file upload, so here is a link:

http://s000.tinyupload.com/index.php?file_id=83442475769593346022

**Comment by wm4** [comment]
So a frame can "Freeze" for a few seconds. The playback core can't know if it's a discontinuity or not. (If there's a jump, should it wait for a few seconds? Or consider it as a discontinuity?)

**Comment by richardpl** [comment]
Packet duration?

**Comment by wm4** [comment]
@richardpl:
```
[PACKET]
codec_type=video
stream_index=0
pts=528
pts_time=1.760000
dts=528
dts_time=1.760000
duration=1
duration_time=0.003333
convergence_duration=N/A
convergence_duration_time=N/A
size=24
pos=12672
flags=_
[/PACKET]
[PACKET]
codec_type=video
stream_index=0
pts=1129
pts_time=3.763333
dts=1129
dts_time=3.763333
duration=1
duration_time=0.003333
convergence_duration=N/A
convergence_duration_time=N/A
size=24
pos=27096
flags=K
[/PACKET]
```
Completely useless, as usual.

**Comment by richardpl** [comment]
Will look is this bug in demuxer...

**Comment by wm4** [comment]
Even then, many external decoders I have to deal with will not pass through pkt_duration or even know a correct value of it, so this is not a general solution.

**Comment by wm4** [comment]
PS: also, mpv does this after filters, and filters are unlikely to pass this through.

**Comment by wm4** [comment]
I per-packet/frame discontinuity flag would be a good concept, because the demuxer knows best whether something is a timestamp reset or not. A decoder could also set it if frames are dropped/packets are invalid. But unfortunately it doesn't exist in ffmpeg, and even if it were introduced, wouldn't be consistent.

**Comment by tmm1** [comment]
@clintonthegeek can you provide a sample file so I can test it with #5792

**Comment by clintonthegeek** [comment]
[SC8322-01 - Moody Blues, The - I'm Just A Singer In A Rock And Roll Band.zip](https://github.com/mpv-player/mpv/files/2019008/SC8322-01.-.Moody.Blues.The.-.I.m.Just.A.Singer.In.A.Rock.And.Roll.Band.zip)

This file had the problem when I initially reported the bug.

**Comment by tmm1** [comment]
Interesting, I've never seen cdg before. How do you play the files together with mpv?

**Comment by clintonthegeek** [comment]
Once you open the .cdg any .mp3 (or, perhaps, other audio format?) is sideloaded as long as it shares the same filename and is in the same folder. :)
