### ISSUE TITLE
OSD not show on user interaction on Windows 10

### ISSUE THREAD

**Issue by eugenesvk** [mpv-player/mpv#3028]
I've set `osd-level=1` in my `mpv.conf` file and the OSD is never shown, even when I "interact" by pause/seek etc. with either my mouse or my keyboard. Other levels work fine (e.g. 2 shows time, 3 shows time+status)

**Comment by Hrxn** [comment]
Not sure what you mean.

Unlike OSD levels 2 and 3, 1 does not show anything by default.
You can disable OSD per input via `no-osd`, i.e. `$KEY no-osd set volume "80"`

Maybe you have `--no-osd` somewhere?

**Comment by eugenesvk** [comment]
OSD 1 should `1:	enabled (shows up only on user interaction)` So what exactly is **user interaction**?
I don't have `--no-osd` anywhere and I'm aware of the `no-osd` option for specific keybinds — that's not it.
But maybe I'm not understanding the user interaction properly. What I'd expect is whenever I seek/pause etc. with OSD 1 it would count as user interaction and show OSD text `osd-status-msg`

**Comment by Hrxn** [comment]
User interaction is any type of user input. If you play a file (CLI, GUI, doesn't matter) and then do nothing, just let the file finish, you will never see any OSD level 1 messages.

The progress bar, shown with `o` or `Shift+P` or when seeking (arrow keys, etc.) is an user interaction, for example. The same when changing image settings (number row) or volume, etc. Or when using a keybind without `no-osd`, you will see the active command in the upper left corner (with default OSD settings).

`osd-status-msg` is more or less the same as `osd-msg3` so you don't see that normally.

**Comment by eugenesvk** [comment]
> then do nothing, just let the file finish, you will never see any OSD level 1 messages.

Exactly what I expected and why I've set OSD to level 1

> Or when using a keybind without no-osd, you will see the active command in the upper left corner (with default OSD settings).

I do see it for some commands (e.g. window scale), but what I'm interested in is the `osd-status-msg`

> osd-status-msg is more or less the same as osd-msg3 so you don't see that normally.

So which user interaction should trigger it? In other players (e.g. MPC-HC) if I pause I seek left/right I see OSD message showing me current time / duration, which is very convenient and allows me to hide the status bar.
However, in mpv nothing happens when I seek — the only way for me to check out the current time / duration (which are part of my `osd-status-msg`) is to either press `O` or move mouse to show the OSC window.

In the manual 
`--osd-msg3=<string>
This is also used for the show_progress command (by default mapped to P), or in **some non-default cases when seeking.**`
That's exactly what I need, but what are those "non-default cases"?

**Comment by kevmitch** [comment]
> what are those "non-default cases"?

I believe if you have in your `input.conf` set something like
```
RIGHT osd-msg seek  1
LEFT osd-msg seek -1
```
