### ISSUE TITLE
Build master fails with --enable-zsh-comp

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#3032]
After 4561649, building mpv master with `--enable-zsh-comp` results in a failure in the last step.

> [214/214] Creating build/etc/_mpv
> Global symbol "$service" requires explicit package name at /Users/myuser/Desktop/mpv-master/TOOLS/zsh.pl line 70.
> Global symbol "$service" requires explicit package name at /Users/myuser/Desktop/mpv-master/TOOLS/zsh.pl line 70.
> Execution of /Users/myuser/Desktop/mpv-master/TOOLS/zsh.pl aborted due to compilation errors.
> 
> Waf: Leaving directory `/Users/myuser/Desktop/mpv-master/build'
> Build failed
>  -> task in '_mpv' failed (exit status 255): 
> 	{task 4571539472: _mpv  -> _mpv}
> ' "/usr/bin/perl" "/Users/myuser/Desktop/mpv-master/TOOLS/zsh.pl" "/Users/myuser/Desktop/mpv-master/build/mpv" > "etc/_mpv"

Up to 6325bdf everything works fine.
The system is Os X 10.11.4; tell me if you need more info, but every combination I've tried (system python/python3, brew/manual building) gave me the same outcome.

**Comment by ArchangeGabriel** [comment]
That’s because of https://github.com/mpv-player/mpv/commit/4561649f2d942ae12cdf7ce93d074d75d7268bb5.

**Comment by wm4** [comment]
ping @qmega

**Comment by region51** [comment]
I have this very same problem Fedora 23
```
[480/480] Creating build/etc/_mpv
14:25:45 runner ' "/usr/bin/perl" "/builddir/build/BUILD/mpv-89571312bfa76b9512b3fb17db0b58e315d60d0e/TOOLS/zsh.pl" "/builddir/build/BUILD/mpv-89571312bfa76b9512b3fb17db0b58e315d60d0e/build/mpv" > "etc/_mpv" '
Global symbol "$service" requires explicit package name (did you forget to declare "my $service"?) at /builddir/build/BUILD/mpv-89571312bfa76b9512b3fb17db0b58e315d60d0e/TOOLS/zsh.pl line 80.
Global symbol "$service" requires explicit package name (did you forget to declare "my $service"?) at /builddir/build/BUILD/mpv-89571312bfa76b9512b3fb17db0b58e315d60d0e/TOOLS/zsh.pl line 81.
Execution of /builddir/build/BUILD/mpv-89571312bfa76b9512b3fb17db0b58e315d60d0e/TOOLS/zsh.pl aborted due to compilation errors.
Waf: Leaving directory `/builddir/build/BUILD/mpv-89571312bfa76b9512b3fb17db0b58e315d60d0e/build'
Build failed
 -> task in '_mpv' failed (exit status 255): 
	{task 140449139192144: _mpv  -> _mpv}
' "/usr/bin/perl" "/builddir/build/BUILD/mpv-89571312bfa76b9512b3fb17db0b58e315d60d0e/TOOLS/zsh.pl" "/builddir/build/BUILD/mpv-89571312bfa76b9512b3fb17db0b58e315d60d0e/build/mpv" > "etc/_mpv" '
error: Bad exit status from /var/tmp/rpm-tmp.7aukf2 (%build)
```

**Comment by qmega** [comment]
I'm really sorry. I was pretty out of it yesterday. I was testing with a raw completion script and just copied my changes into the perl script. Forgot it was an interpolating heredoc. Submitted a PR to fix it.

**Comment by region51** [comment]
769213605b5bbc8d4d335ebd3eb2968ec1bde478 works for me
