### ISSUE TITLE
audio volume is always at 100% at startup

### ISSUE THREAD

**Issue by cpu82** [mpv-player/mpv#3035]
Hi,

Since mpv 0.15.0 release, audio volume is always at 100%  right after starting playback.

The culprit is in `audio/mixer.c`
```
struct mixer *mixer_init(void *talloc_ctx, struct mpv_global *global)
{
    struct mixer *mixer = talloc_ptrtype(talloc_ctx, mixer);
    *mixer = (struct mixer) {
        .log = mp_log_new(mixer, global->log, "mixer"),
        .opts = global->opts,
        .vol_l = 100,
        .vol_r = 100,
        .driver = "",
    };
    return mixer;
}
```
This quick fix solves the issue, but I'm not sure if this change was intended or not.

```
--- audio/mixer.c.orig  2016-03-29 14:12:22 UTC
+++ audio/mixer.c
@@ -57,8 +57,8 @@ struct mixer *mixer_init(void *talloc_ct
     *mixer = (struct mixer) {
         .log = mp_log_new(mixer, global->log, "mixer"),
         .opts = global->opts,
-        .vol_l = 100,
-        .vol_r = 100,
+        .vol_l = -1,
+        .vol_r = -1,
         .driver = "",
     };
     return mixer;
```

Can someone take a look at this?

Thanks

**Comment by wm4** [comment]
It is intended, see here for remarks: https://mpv.io/manual/master/#command-interface-mixer-active

This has in particular to do with the fact that mpv won't communicate with a system until an audio output is opened.

It's all a mess, but I'm not sure how this could be solved other than separating mixer controls from audio outputs, which would be annoying too.
