### ISSUE TITLE
"audio-channels" not recognized in input.conf

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#3040]
Hi,

I want to use "M" to cycle between `"--audio-channels=dl"`, `"--audio-channels=dr"` and `"--audio-channels=2.0"` so I added the following the `input.conf` file:

`M   audio-channels  cycle_values    dl dr 2.0`

but when I run `mpv`, it says:

```
[input] Command 'audio-channels' not found.
[input] Command was defined at /home/sebastien/.config/mpv/input.conf:16.
```

Can you help me ?

**Comment by kevmitch** [comment]
You have the command and property switched around. It should be

    M cycle_values audio-channels dl dr 2.0

**Comment by sebma** [comment]
Ok, 

But now mpv says on the terminal:
`The audio-channels option must be an integer: dl`
and it says on the screen of the video:
`Failed so set propersty 'audio-channels' to 'dl'`

What are the integer values for "dl", "dr" or "2.0" ?

**Comment by kevmitch** [comment]
Looking at the man page `audio-channels` isn't even a valid property . I think this is only kind of working due to the depricated `track-list/N/audio-channels`, which is a read only description of the underlying audio track anyway.

What you probably want is `audio-params/channel-count`, but this appears to also be read only. I'm not even able to set `options/audio-channels`. I'm beginning to wonder if this is even possible.

**Comment by wm4** [comment]
I don't think anything prevents setting the option? But it won't reinitialize the audio chain automatically. Though it could be achieved by e.g. switching the audio track off and on again.

**Comment by kevmitch** [comment]
M cycle_values options/audio-channels "dl" "dr" "2.0"

or even

    M set options/audio-channels "stereo"

results in the osd saying

    options/audio-channels: (error)

**Comment by wm4** [comment]
This is because _display_ of the option on the OSD fails. There is no conversion for channel layout -> string in the option code. (It'd be easy enough to add, maybe I'll do that later.)

E.,g. this works for me, even if it shows an error on OSD: ``x set options/audio-channels 5.1 ; ao-reload``

**Comment by sebma** [comment]
This does not:
`M set options/audio-channels dl`

Can you tell why ?

**Comment by sebma** [comment]
I know why, I have forgotten the `; ao-reload` :-)

**Comment by sebma** [comment]
So the correct line for what I wanted is now:

`M cycle_values options/audio-channels dl dr 2.0 ; ao-reload`

Can you fix the "display of the option on the OSD" when you have some time ?

Thanks a lot.
