### ISSUE TITLE
Pause when exiting fullscreen with only one shortcut

### ISSUE THREAD

**Issue by sohvd** [mpv-player/mpv#3041]
Hi,

I'm on Windows 7 and I would like to use ESC for pause and exit fullscreen. For now I use ESC+P, can you tell me what do I have to change in imput.conf to do this with ESC?

**Comment by Cpuroast** [comment]
All the info you needed to figure that out was in the input.conf man page:

https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst
https://mpv.io/manual/master/#general-input-command-syntax

But I'll be nice and give it to you on a silver platter.

Add the following line to your input.conf file:

ESC set fullscreen no ; cycle pause

**Comment by sohvd** [comment]
Thank you very much!

**Comment by Cpuroast** [comment]
Next time you need to tweak a keyboard binding, please refer to the links I mentioned and you should be able to figure it out.

**Comment by Cpuroast** [comment]
After testing it myself, it looks like the reverse will give you a smoother experience:

ESC cycle pause ; set fullscreen no

**Comment by sohvd** [comment]
Thanks it's even better. I use mpv for two days, I'll take the time to read the full manual, it's worth it.
