### ISSUE TITLE
0.17.0 Extra Notches in Display?

### ISSUE THREAD

**Issue by Geyup** [mpv-player/mpv#3042]
In Linux, when I want to fast forward, or go back with the mouse wheel, not sure I remember the name of the display that appears, but I noticed in 0.17.0 it has extra notches in it. I don't recall seeing it look this way in previous versions.

Please see the attached screen shot where I placed a red dot above and below these extra notches.

What does this represent, why doesn't it just appear like it use to with only one notch on top and bottom, like the ones you see further to the right?

![mpv](https://cloud.githubusercontent.com/assets/13072581/14445250/16e1a62a-003b-11e6-964a-68164562776a.jpg)

**Comment by ChrisK2** [comment]
Those are the positions of chapter markers. They come from the file you are playing. Apparently there are many chapters at those places.

**Comment by Geyup** [comment]
Ahh ok thanks...
