### ISSUE TITLE
Need help for command line to use with mpv

### ISSUE THREAD

**Issue by ManuCart** [mpv-player/mpv#3044]
Hello
Before with mplayer I used this command line
````
mf://@files.lst -mf type=jpg:fps=3 -ovc lavc -lavcopts vcodec=mjpeg -nosound -o stopmotion.avi
````
But now I have this error
````
Error parsing option mf (option not found)
Setting commandline option --mf= failed.
````

What the way to use with mpv

**Comment by ChrisK2** [comment]
[Reading manual](https://mpv.io/manual/master/#options-mf-fps).

**Comment by ManuCart** [comment]
best answer for a member, thanks a lot.
I allready reading manual but without poor sample not possible to find my solution.
Nevermind I'm returning on gui apps without learning more

**Comment by wm4** [comment]
>-ovc lavc -lavcopts vcodec=mjpeg 

Pointless/wrong.

> -nosound

Renamed to ``-no-audio``.

**Comment by ManuCart** [comment]
thanks very mutch fo wm4 but not to ChrisK2
