### ISSUE TITLE
Modernize UI for Mac OS X

### ISSUE THREAD

**Issue by dubert** [mpv-player/mpv#3048]
It would be great to see the UI updated, and match Quicktime:
- Titlebar that fades in
- Visually cleaned up control panel

This is something I would be willing to tackle, I'm just not sure where to start. Any feedback?

**Comment by wm4** [comment]
> Titlebar that fades in

Shouldn't that be handled by cocoa if it exists?

> Visually cleaned up control panel

We don't have a control panel at all. Did you get the correct project?

**Comment by dubert** [comment]
Here is a comparison between QuickTime and mpv:
![videocomparison](https://cloud.githubusercontent.com/assets/1843672/14533858/cfe3dce2-0234-11e6-9f98-8c2d616e54d5.gif)

This is what I meant by the control panel (I wasn't sure what to call it):
<img width="584" alt="screen shot 2016-04-14 at 11 29 35" src="https://cloud.githubusercontent.com/assets/1843672/14533868/dda8e584-0234-11e6-8e5d-0791121eb7e9.png">

**Comment by ChrisK2** [comment]
It's called the [On Screen Controller (OSC)](https://mpv.io/manual/master/#on-screen-controller). Here is the source code, feel free to add another layout: https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua

**Comment by wm4** [comment]
That would require mpv to crop off part of the video while the mouse pointer is inside the window. Doesn't seem like a good solution. On the other hand, there's a way to always remove borders in mpv. (Not sure if it's runtime-toggleable on OSX.)

**Comment by ChrisK2** [comment]
Yeah, you could just disable window decorations and have the OSC render the title bar.

**Comment by xhhqzxg24** [comment]
Maybe you need some shadows?
img too big  ^ω^
https://itmages.com/image/view/4153643/037e4d50

**Comment by typcn** [comment]
Titlebar transparent can be enabled with "NSFullSizeContentViewWindowMask"

But it need CALayer enabled on the window, after enable CALayer:
1. Can't use two OpenGL view in single process
2. About 2x CPU & memory usage
3. Sometime crash on drawing

**Comment by Akemi** [comment]
wonder if we could consider this solved with [iina](https://github.com/lhc70000/iina)? there are some caveats with doing this in mpv and the OSC being transparent with a backdrop blur is (nearly) impossible to do.

**Comment by pigoz** [comment]
Yeah. Now that there is a proper GUI for mpv on OS X use that if you want the player to look like QuickTime.

**Comment by muescha** [comment]
> Yeah. Now that there is a proper GUI for mpv on OS X use that if you want the player to look like QuickTime.

maybe try IINA ( https://github.com/iina/iina ) it is based on MPV
