### ISSUE TITLE
The screen freezes after I exit full screen.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#3051]
It really happens in most of the time when I exit the full screen mode.
CPU: intel i5-4460
iGPU: intel HD4600
OS: Ubuntu 14.04.3LTS
kernel: 4.2.0-35-generic
MPV: 2:0.16.0+git6~trusty
settings:
>vo=opengl
>sub-auto=fuzzy
>no-osd-bar
>video-sync=display-resample

Every time it happens, I have to go to tty1 and type "sudo service lightdm restart", lots of stuff will be lost.

**Comment by lachs0r** [comment]
GPU driver and/or compositor bug.

**Comment by marlencrabapple** [comment]
This behavior persists in 16.04. Are you guys 100% its a GPU driver bug? Intel's drivers have been bumped several versions since 14.04 and nothing has changed
