### ISSUE TITLE
Howto get properties from fifo by command line

### ISSUE THREAD

**Issue by andysendo** [mpv-player/mpv#3058]
Hi, i can set properties such as percent-pos etc. to fifo (created by mkfifo) by command line like "echo percent-pos 10 > some named pipe" and mpv daeom could response correctly. But how can i get properties from the fifo such as command line "echo get percent-pos > pipe" or something?

Thanks.

**Comment by ChrisK2** [comment]
That's not (properly) possible. You need to use the [JSON IPC API](https://mpv.io/manual/master/#json-ipc) for this.

**Comment by andysendo** [comment]
Thanks for replay. 
So mpv remove some of mplayer slave mode command such as 
get_percent_pos, 
get_percent_pos, etc. I dont know why.
I'm running self-compiled mpv 0.16 that dont have --input-ipc-server option, maybe need recompile.

**Comment by rossy** [comment]
> So mpv remove some of mplayer slave mode command such as get_percent_pos, get_property, etc. I dont know why.

MPlayer's slave mode was pretty badly designed. See [mplayer-changes.rst][1] for details. JSON IPC replaces slave mode and should hopefully be a lot better.

> I'm running self-compiled mpv 0.16 that dont have --input-ipc-server option, maybe need recompile.

Yeah, the --input-ipc-server option was recently renamed from --input-unix-socket. --input-unix-socket will work in both mpv 0.16.0 and 0.17.0 (but the name is deprecated in 0.17.0.)

[1]: https://github.com/mpv-player/mpv/blob/master/DOCS/mplayer-changes.rst#slave-mode

**Comment by wm4** [comment]
> get_percent_pos, get_property, etc. I 

All of these were replaced. get_property is a json mpv bridge command and not a mpv command itself.

**Comment by andysendo** [comment]
mpv with --input-unix-socket option works very well. 

Another question is if i start mpv window like "mpv --profile=pseudo-gui --no-video --keep-open --input-unix-socket=/tmp/mpvsocket &", then load mp3 files one by one by self-script. Aka mpv window/process will not auto quit, the script load a mp3 file to mpv then play it, wait until mpv play over, then load next mp3 file. It works fine under current Xsession. But if i switch to second Xsession, mpv will hang to load next mp3 file until switch back to current Xsession. So does mpv support this action with some options in gui mode? (mpv daemon without gui window wont have this problem)

**Comment by wm4** [comment]
See https://mpv.io/manual/master/#pseudo-gui-mode what pseudo GUI mode actually does. Looks like you have a problem with --force-window. Just don't use this profile and only add what you need.
