### ISSUE TITLE
image broken with dxva2-copy on windows

### ISSUE THREAD

**Issue by blackarcher21** [mpv-player/mpv#3059]
happens after upgrade to 0.17.0 (2016-04-11)
screenshot: http://i.imgur.com/X5Xa0FX.png
sample: https://a.pomf.cat/tbjhgl.mkv
looks good with 0.16.0 (2016-02-29)

my hardware
CPU: Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz
GPU: Intel(R) HD Graphics 3000 (driver version: 9.17.10.4229)
Windows 8.1 64-bit

**Comment by shinchiro** [comment]
working fine to me

**Comment by kevmitch** [comment]
can you post the log generated with `--log-flie=log.txt`

**Comment by kevmitch** [comment]
Sorry, that's `--log-file=log.txt`

**Comment by blackarcher21** [comment]
http://pastebin.com/FCR0KR4S

**Comment by kevmitch** [comment]
Does this fix it?
http://kevmitch.ca/mpv.ce153bd.exe

**Comment by blackarcher21** [comment]
Could you compress it to 7z then upload it again so I can get smaller size? My Internet charge per MB. Even if it just a little smaller in result, that really help me. thanks

**Comment by wm4** [comment]
https://0x0.st/ZmN.7z

**Comment by blackarcher21** [comment]
@wm4 Thanks for reupload it

@kevmitch Yes, it does. 
Here is also the log in case if you need this 
http://pastebin.com/42HQ9Zym

**Comment by kevmitch** [comment]
https://0x0.st/ZaP.7Z

**Comment by kevmitch** [comment]
oh, wait nevermind
