### ISSUE TITLE
vo=opengl with wayland = INVALID_FRAMEBUFFER_OPERATION

### ISSUE THREAD

**Issue by subsonik** [mpv-player/mpv#3061]
Hi,

When attempting to playback video using mpv 0.17 under GNOME 3.20.1/wayland, I get the following error: `[vo/opengl-hq] after rendering: OpenGL error INVALID_FRAMEBUFFER_OPERATION.`

vo=x11 works fine, as does vo=opengl:backend=x11egl. Using vo=wayland results in no errors, audio playing, but no video window being drawn.

Attached is a log file of '-v --vo=opengl'.

Thanks.

[mpv.txt](https://github.com/mpv-player/mpv/files/225337/mpv.txt)

**Comment by wm4** [comment]
There's no log attached.

**Comment by subsonik** [comment]
Oops, sorry. Attached now. :)

**Comment by wm4** [comment]
No idea what's happening here, but it seems to be wayland related.

**Comment by ZiRo-** [comment]
I encountered this bug as well. This is due the either one or both of these options:
```
[cplayer] Setting option 'geometry' = '50%:50%' (flags = 4)
[cplayer] Setting option 'autofit-larger' = '90%x90%' (flags = 4)
```

**Comment by subsonik** [comment]
Thanks @ZiRo-, it was indeed caused by the 'autofit-larger=90%x90%' line in my mpv.conf. 

However, I'm now getting this error: '[vo/opengl-hq/wayland] There is already a dnd entry point.'. 

It doesn't seem to be negatively affecting playback in any way, though.

I'm also not getting any window decorations (maybe caused by the above error), but this isn't a problem, so long as the video plays correctly, as it does.

Cheers!

**Comment by wm4** [comment]
Well that's still a bug.

**Comment by Jiehong** [comment]
Gnome 3.22 on Archlinux here.

The option `autofit` also prevents the display of anything. Removing it causes the following error to still occur:

```
[vo/opengl] retrieving framebuffer depth: OpenGL error INVALID_OPERATION.
```

Yet, videos work just fine.

Still, no borders whatsoever.

**Comment by Jiehong** [comment]
I've opened another bug report for the no-border issue: https://github.com/mpv-player/mpv/issues/4033.

**Comment by atomnuker** [comment]
Autofit works with wayland with the latest mpv git master, closing this bug

**Comment by liaowang11** [comment]
```bash
❯ mpv --version                                                                                           
mpv 0.27.0-406-g35d74e1612 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
```
Just compiled from AUR against master branch, still not working if `autofit_larger` options is defined.
