### ISSUE TITLE
Audio doesn't play until the end with 'keep-open' enabled

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#3064]
I don't know if it only applies to audio-only files, but it's especially noticeable with very short audio clips.

Let me know if you want samples, I cannot really upload the ones I have publicly.

**Comment by occivink** [comment]
Here is a [sample](b.1339.cf/djzlycx.wav). If you play it with `mpv djzlycx.wav --no-config` you can hear the full 'beep', and if you play it with `mpv djzlycx.wav --no-config --keep-open`, no sound is being played.

**Comment by wm4** [comment]
Works here.

**Comment by occivink** [comment]
Here is the [log](https://github.com/mpv-player/mpv/files/233601/log.txt) when reproducing it.

**Comment by wm4** [comment]
Does it work if you force ``--ao=alsa``? (You might have to disable pulse or so.)

**Comment by occivink** [comment]
Turns out that pulseaudio is pretty hard to disable (even with `autospawn = no`), but after doing so the file is played correctly.

**Comment by wm4** [comment]
This probably means that we don't determine playback end from pulse correctly, and then pause the stream while it's still playing.

**Comment by occivink** [comment]
Closed by #6900
