### ISSUE TITLE
typesetting issue at 4k

### ISSUE THREAD

**Issue by jonwoo** [mpv-player/mpv#3070]
- OS: Windows 10 x64
- Build: Latest srsfckn build (2016-04-11)
- File in question: [FFF] KILL la KILL - 01 [BD][720p-AAC][F95822D0].mkv (720p/1080p doesn't matter; result is identical)
- Have tried no-config.
- displays correctly in MPC-HC (out of the box or with XySubFilter+MadVR)

A black box should be drawn to cover up the original image for the localized typesetting but after a certain size well past 1080p/1440p the black box disappears (essentially the attached image is about the cutoff size). Not an issue to most people but could be an issue to those with a 4k display.

Attached is an example of the black box being drawn vs. not drawn. This is actually a favorable example because all the other examples are completely unreadable (and there's about 200 of these over the duration of KILL la KILL).

![kill](https://cloud.githubusercontent.com/assets/7465561/14695116/8f9db482-0734-11e6-8d20-34eff4ecd24f.jpg)

**Comment by haasn** [comment]
Does mpv print any warnings? It's entirely possible that some bounding box ends up so large that it can no longer be uploaded as a texture.

I've run into similar issues myself, where on a 4K display some textures will end up at absurd dimensions like 8000x9000 since the authors made them much too big for the original video.

As an easy work-around, you can use `:blend-subtitles=video` to get around the problem of having to render subs at display-size to begin with.

**Comment by jonwoo** [comment]
Alright, after setting up a log file and loading up the episode in windowed mode:

Beginning of episode: Glyph bounding box too large: 3964x2033px (8,058,812 square pixels)
End of episode: Glyph bounding box too large: 3764x2127px (8,006,028 square pixels)

The bounding boxes at the beginning and end of this episode are of different dimensions.I think it's safe to say that the bounding boxes _can_ break in when over 8 million square pixels (or at least in the Windows build of mpv).

:blend-subtitles=video is the easy work-around I needed to make this a non-issue for myself, thanks!

**Comment by wm4** [comment]
Reported as https://github.com/libass/libass/issues/220.

It's also possible that you'll run out of texture space, even if the libass restriction is lifted.

**Comment by wm4** [comment]
Could you extract the subtitle file and upload it somewhere? Might be helpful for testing.

**Comment by jonwoo** [comment]
[ass file](https://my.mixtape.moe/onjhyk.ass)

Also, thanks for forwarding the issue to the correct location.
