### ISSUE TITLE
Linked MKVs unsupported

### ISSUE THREAD

**Issue by Veicc** [mpv-player/mpv#3073]
mpv doesn't seem to support one of the standard features of of mkv, linked (not ordered!) chapters. All other major media players such as VLC support this feature. I'm just a casual anime watcher who was told to make an issue about it here, so instead of explaining, I'm going to just provide a linksto help you understand what this is about: http://mod16.org/hurfdurf/?p=8

Here's an example of the usage of linked mkvs: http://www.nyaa.se/?page=view&tid=804148

Thanks in advance!

**Comment by wm4** [comment]
Tell the encoder not to use this rarely supported feature.

**Comment by Veicc** [comment]
But it isn't rarely supported, it's a standard feature of the mkv container which is supported by VLC, MPC-HC and others. Thanks for your attention, though.

**Comment by richardpl** [comment]
Give link to such mkvs, I was unable to find them.

**Comment by wm4** [comment]
Even then it's not worth supporting, as the _files_ are rare as well. The torrent you linked has less than 500 downloads.

**Comment by Veicc** [comment]
Well, even though the files are not very common, they could be, if the feature was supported by the player many encoders tend to endorse.

richardpl, I suppose you wanted to avoid using that torrent link in my post, so here's a DDL: http://8man.s0.fi/owncloud/index.php/s/VBX02lOtOea4m8m

**Comment by animefreak2** [comment]
Testing, it seems to work in:
VLC
MPC-HC
MPDN (though that's a hilariously broken player, isn't it?)

Not supported:
MPC-BE

Anyway, my next 3 releases are all using linked mkvs, as was my last.

**Comment by haasn** [comment]
In case @Veicc is just an innocent bystander; the reason you're getting such a harsh reaction is because the mpv project has a history of being trolled by people demanding support for this feature.

So there's not a whole lot of interest for any developer to write the code necessary. If you want the feature, you'll probably have to write the code yourself.

**Comment by Veicc** [comment]
> In case @Veicc is just an innocent bystander; the reason you're getting such a harsh reaction is because the mpv project has a history of being trolled by people demanding support for this feature.

Oh wow, well, I guess this feature really is quite obscure then.

**Comment by animefreak2** [comment]
There's a reason the scene still does Xvid/AC-3 in avi.  It's for compatibility.  We in anime-land have always needed codec packs because we're a little "special", as wm4 pointed out.  MKV, Hi10p, and softsub support is all hit or miss outside known good configurations.  
If you need Windows to get CCCP working, there are some people on the forums with MSDN subscriptions handing out keys.  Just do a forum search for MSDN.

**Comment by Hrxn** [comment]
> Xvid/AC-3 in avi. 

.. And that's why we can't have nice things :laughing:

**Comment by DonCuan** [comment]
>Tell the encoder not to use this rarely supported feature.

That would usually require a time machine. If we had one, we could also tell encoders not to use video formats etc. that have since been deprecated, but alas their releases have been around for years and people still expect them to be played back on today's players. In my case, it's [EtB]'s release of Gankutsuō, which is arguably still the best rip of the show (the Blu-rays are garbage). I might have more on my disk without noticing that they used the feature, since they played just fine in the past.

Luckily, I only know of one active encoder who makes use of that feature in recent encodes.

The last versions of mplayer2 supported linked MKVs. mpv used to support them at least until 0.6.2 (I just installed the version in Debian stable to test). The functionality was there, but must have been broken at some point.

**Comment by wm4** [comment]
> Luckily, I only know of one active encoder who makes use of that feature in recent encodes.

No comment.

> The functionality was there, but must have been broken at some point.

I doubt that, but feel free to bisect.

**Comment by Al-eXs** [comment]
Segment Linking and Ordered Chapters are supported, I have a bunch of anime that uses the two features, in order to present the "complete" episode you need the Opening and Ending in the folder and the episodes will be "complete" in the timeline. I don't know what specifically is not working.

`mpv "Some Anime ep 5.mkv"
Playing: Some Anime ep 5.mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 2: ./Some Anime Ending.mkv
Match for source 1: ./Some Anime Opening.mkv`

`mpv -V
mpv 0.22.0-git-1d4273c (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 20 18:59:12 CET 2016
ffmpeg library versions:
   libavutil       55.40.100
   libavcodec      57.66.105
   libavformat     57.58.100
   libswscale      4.3.101
   libavfilter     6.67.100
   libswresample   2.4.100
ffmpeg version: N-82573-ge7aaf0e`

**Comment by DonCuan** [comment]
@Al-eXs
Linked MKVs are another Matroska feature that can be used for similar purposes like ordered chapters, but works differently.

I have to retract my statement about the particular release I mentioned though, It does in fact use ordered chapters, but is no longer recognized as such by more recent mpv versions. So that would be a different issue.

**Comment by ipatrol** [comment]
> Oh wow, well, I guess this feature really is quite obscure then.
Within the anime community it's a subject that comes up all the time. Is it that it's obscure? Or is it that no one in the mpv community wants to write it because they have an antipathy to it due to the past trolling?

**Comment by CounterPillow** [comment]
@ipatrol lol, I can confidently say that I've never come across an anime release that uses linked MKVs. They do use ordered chapters often though, which is already supported.

Either provide statistical evidence or you'll just be laughed at.

**Comment by haasn** [comment]
> Within the anime community it's a subject that comes up all the time. 

Are you sure you're not confusing this with ordered chapters? Those are used for anime all the time, and mpv supports them.

> Is it that it's obscure? Or is it that no one in the mpv community wants to write it because they have an antipathy to it due to the past trolling?

Both

**Comment by Jj0YzL5nvJ** [comment]
Linked MKVs, segment linking, external chapters, SegmentUID or whatever it be called, is supported, since "mplayer2 / ffmpeg-mt" age. But they not be handled comfortably, like in VLC / MPC-HC. Especially when are combined with editions. Example:
```
mpv --edition=1 "[NnS] Shikabane Hime Kuro.Episodio 06.[0F782868].mkv"
Playing: [NnS] Shikabane Hime Kuro.Episodio 06.[0F782868].mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 1: ./[NnS] Shikabane Hime Kuro.OP.Limpio.[DVD.H264.AC3][1660714E].mkv
Match for source 2: ./[NnS]Shikabane.Hime.Kuro.ED.Limpio.[DVD.H264.AC3][5CB5130C].mkv
     --edition=0 'Un Monstruo llamado Felicidad (Karaokes)' (*)
 (+) --edition=1 'Un Monstruo llamado Felicidad (Sin Karaokes)'
 (+) Video --vid=1 'H264' (h264 704x480 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) 'AC3' (ac3 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=spa (*) 'ASS' (ass)
AO: [pulse] 48000Hz stereo 2ch float
Using hardware decoding (vdpau).
VO: [opengl] 704x480 => 852x480 vdpau[yuv420p]
AV: 00:01:29 / 00:23:39 (6%) A-V:  0.000 Cache: 10s+73MB
Using hardware decoding (vdpau).
AV: 00:21:54 / 00:23:39 (92%) A-V:  0.000 Cache:  9s+2MB
Using hardware decoding (vdpau).
AV: 00:23:24 / 00:23:39 (98%) A-V:  0.000 Cache: 10s+637KB
Invalid audio PTS: 1404.778000 -> 1405.030000
AV: 00:23:24 / 00:23:39 (98%) A-V:  0.240 Cache:  9s+585KB
Using hardware decoding (vdpau).
AV: 00:23:39 / 00:23:39 (99%) A-V:  0.000 ct:  0.252 Cache:  0s+0KB


Exiting... (End of file)
```
Is there any way to switch editions at time of reproduction? If they are marked on the time bar, why can not I use them like any other ordered chapter?

> @ipatrol lol, I can confidently say that I've never come across an anime release that uses linked MKVs.
 They are very common in fansubs from countries with low bandwidth or with shitty ISPs. Ibero-America for example.

Samples:
```
mpv "[NF] Hen Zemi OAD 01 DVDrip [Hi10p] [C5A0A583].mkv"
Playing: [NF] Hen Zemi OAD 01 DVDrip [Hi10p] [C5A0A583].mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 2: ./[NF] Hen Zemi OAD DVDrip Ending [Hi10p] [00609373].mkv
Match for source 1: ./[NF] Hen Zemi OAD DVDrip Opening [Hi10p] [E8545CA9].mkv
 (+) Video --vid=1 (*) (h264 848x480 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=spa (*) (ass)
AO: [pulse] 48000Hz stereo 2ch float
VO: [opengl] 848x480 yuv420p10
AV: 00:26:39 / 00:26:39 (99%) A-V:  0.000 Cache:  0s+130MB


Exiting... (End of file)
```
```
mpv "[BB~NF] Kemono no Souja Erin BDrip 31 [Hi10p] [291B3CC5].mkv"
Playing: [BB~NF] Kemono no Souja Erin BDrip 31 [Hi10p] [291B3CC5].mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 2: ./[BB~NF] Kemono no Souja Erin BDrip Ending 02 [Hi10p] [47F7345A].mkv
Match for source 1: ./[BB~NF] Kemono no Souja Erin BDrip Opening 02 [Hi10p] [E82EBA72].mkv
 (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (flac 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=spa (*) (ass)
AO: [pulse] 48000Hz stereo 2ch s16
VO: [opengl] 1280x720 yuv420p10
AV: 00:24:29 / 00:24:29 (99%) A-V:  0.000 Cache:  0s+0KB


Exiting... (End of file)
```
```
mpv "[NF] Panty & Stocking with Garterbelt 06 BDrip [Hi10p] [49EE604B].mkv"
Playing: [NF] Panty & Stocking with Garterbelt 06 BDrip [Hi10p] [49EE604B].mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 2: ./[NF] Panty & Stocking with Garterbelt BDrip Ending [Hi10p] [41DD4B14].mkv
Match for source 1: ./[NF] Panty & Stocking with Garterbelt BDrip Opening [Hi10p] [340118E4].mkv
There are 0.107 seconds missing from the timeline!
 (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (flac 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=spa (*) (ass)
AO: [pulse] 48000Hz stereo 2ch s16
VO: [opengl] 1280x720 yuv420p10
AV: 00:23:40 / 00:23:41 (99%) A-V:  0.000 Cache:  0s+73MB


Exiting... (End of file)
```
```
mpv "[NF] Hajime no Ippo New Challenger 26 [27093ACA].mkv"
Playing: [NF] Hajime no Ippo New Challenger 26 [27093ACA].mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 2: ./[NF] Hajime no Ippo New Challenger [Ending] [874001B0].mkv
Match for source 1: ./[NF] Hajime no Ippo New Challenger [Opening] [D224FA43].mkv
 (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
 (+) Subs  --sid=1 (*) (ass)
AO: [pulse] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p10
AV: 00:22:49 / 00:22:49 (99%) A-V:  0.000 Cache:  0s+73MB


Exiting... (End of file)
```
```
mpv "[AU-NF] Tears to Tiara 19 [BD][FCA0D74E].mkv"
Playing: [AU-NF] Tears to Tiara 19 [BD][FCA0D74E].mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 2: ./[AU-NF] Tears to Tiara ED2 [BD][1D2D2F21].mkv
Match for source 1: ./[AU-NF] Tears to Tiara OP [BD][A1A434B4].mkv
 (+) Video --vid=1 (*) 'h264' (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) 'AAC' (aac 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=spa (*) 'ASS' (ass)
File tags:
 Title: [AU-NF] Tears to Tiara 19
AO: [pulse] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p10
AV: 00:23:45 / 00:23:45 (99%) A-V:  0.000 Cache:  0s+0KB


Exiting... (End of file)
```
```
mpv "[NF] Aa Megami-sama DVDrip 17 [DB541114].mkv"
Playing: [NF] Aa Megami-sama DVDrip 17 [DB541114].mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 2: ./[NF] Aa Megami-sama DVDrip [Ending 02] [E95DE4A6].mkv
Match for source 1: ./[NF] Aa Megami-sama DVDrip [Opening] [1D7051FA].mkv
There are 0.082 seconds missing from the timeline!
 (+) Video --vid=1 (*) (h264 848x480 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=spa (*) (ass)
AO: [pulse] 48000Hz stereo 2ch float
VO: [opengl] 848x480 yuv420p10
AV: 00:23:55 / 00:24:09 (98%) A-V:  0.000
[sub/ass] PlayResX undefined, setting to 800
AV: 00:24:09 / 00:24:09 (99%) A-V:  0.000


Exiting... (End of file)
```
```
mpv "[NF] Aa Megami-sama Sorezore no Tsubasa DVDrip 23 [ED7B8D17].mkv"
Playing: [NF] Aa Megami-sama Sorezore no Tsubasa DVDrip 23 [ED7B8D17].mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 2: ./[NF] Aa Megami-sama Sorezore no Tsubasa DVDrip [Ending 02] [8822F39B].mkv
Match for source 1: ./[NF] Aa Megami-sama Sorezore no Tsubasa DVDrip [Opening] [A0502F5F].mkv
There are 0.166 seconds missing from the timeline!
 (+) Video --vid=1 (*) (h264 848x480 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=spa (*) (ass)
AO: [pulse] 48000Hz stereo 2ch float
VO: [opengl] 848x480 yuv420p10
AV: 00:24:09 / 00:24:09 (99%) A-V:  0.000


Exiting... (End of file)
```
```
mpv "[NF] Wooser no Sonohi Gurashi 07 BDrip [A270697A].mkv"
Playing: [NF] Wooser no Sonohi Gurashi 07 BDrip [A270697A].mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 1: ./[NF] Wooser no Sonohi Gurashi BDrip [Opening] [A70E52D6].mkv
Match for source 2: ./[NF] Wooser no Sonohi Gurashi BDrip [Ending] [A24B00F5].mkv
 (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=spa (*) (ass)
AO: [pulse] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p10
AV: 00:03:49 / 00:03:49 (99%) A-V:  0.000


Exiting... (End of file)
```
```
mpv "[NF] Baccano 14 BDrip [Hi10p] [6D178032].mkv"
Playing: [NF] Baccano 14 BDrip [Hi10p] [6D178032].mkv
File uses ordered chapters, will build edit timeline.
This file references data from other sources.
Will scan other files in the same directory to find referenced sources.
Match for source 1: ./[NF] Baccano Ending BDrip [Hi10p] [B11DF610].mkv
 (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (flac 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=spa (*) (ass)
AO: [pulse] 48000Hz stereo 2ch s16
VO: [opengl] 1280x720 yuv420p10
AV: 00:27:46 / 00:27:46 (99%) A-V:  0.000 ct:  0.086 Cache:  0s+0KB


Exiting... (End of file)
```

**Comment by Argon-** [comment]
@Jj0YzL5nvJ ALL of your examples use "ordered chapters", NOT "segment linking". mpv supports ordered chapters just fine.

Both are very similar and ordered chapters are what's commonly used in anime. Ordered chapters is "mightier" than segment linking as it can be used to do the same (and more). The only advantage of segment linking is that it's easier to create but there's little difference really.

During the first requests of segment linking support several questions where asked about how it should behave in certain cases. No answers were provided though.

**Comment by wiiaboo** [comment]
In case someone wants to implement it, here's the spec on [hard linking](https://tools.ietf.org/html/draft-lhomme-cellar-matroska-02#section-21.1), [nextUID](https://tools.ietf.org/html/draft-lhomme-cellar-matroska-02#section-7.3.11), and [prevUID](https://tools.ietf.org/html/draft-lhomme-cellar-matroska-02#section-7.3.9).

From what I follow, this "hard linking" using Next/PrevUID is supposed to be created when splitting files in order for those split files to playback as if it were a single joined file.

**Comment by Jj0YzL5nvJ** [comment]
> @Jj0YzL5nvJ ALL of your examples use "ordered chapters", NOT "segment linking". mpv supports ordered chapters just fine.

They are **ordered chapters with segment linking**. A single file can have ordered chapters, think of it like a menu. And yes, mpv supports ordered chapters and ordered chapters with segment linking just fine.
Examples: http://www.ps-auxw.de/ordered/

More info:
https://coalgirls.wakku.to/faq
http://forum.doom9.org/showthread.php?t=99489
https://forums.animesuki.com/showthread.php?t=66444

The only problem is with "multi-segment linking" (multi-editions / menus), I don't see any way to switch in play time with mpv. Example:
```
General
Unique ID                                : 214788365054629740386958790729253366757 (0xA196BC01682FF3C3874F13CB4F5DABE5)
Complete name                            : [NnS] Shikabane Hime Kuro.Episodio 06.[0F782868].mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 282 MiB
Duration                                 : 20mn 39s
Overall bit rate                         : 1 910 Kbps
Encoded date                             : UTC 2010-08-13 18:22:05
Writing application                      : mkvmerge v3.4.0 ('Rapunzel') built on May 15 2010 09:38:20
Writing library                          : libebml v0.8.0 + libmatroska v0.9.0
Attachments                              : Shikabane Filco Olde Style.ttf

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 16 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 20mn 39s
Bit rate                                 : 1 424 Kbps
Width                                    : 704 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Original display aspect ratio            : 3:2
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.176
Stream size                              : 210 MiB (75%)
Title                                    : H264
Writing library                          : x264 core 95 r1592+1 03a877f
Encoding settings                        : cabac=1 / ref=16 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / fade_compensate=0.00 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=32 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=3 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / constrained_intra=0 / bframes=8 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / weightp=2 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=80 / rc=crf / mbtree=1 / crf=13.0 / qcomp=0.80 / qpmin=0 / qpmax=51 / qpstep=4 / ip_ratio=1.40 / aq=1:0.60
Language                                 : English
Default                                  : No
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Mode extension                           : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                 : A_AC3
Duration                                 : 20mn 39s
Bit rate mode                            : Constant
Bit rate                                 : 448 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                               : 31.250 fps (1536 spf)
Compression mode                         : Lossy
Stream size                              : 66.2 MiB (23%)
Title                                    : AC3
Language                                 : Japanese
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Title                                    : ASS
Language                                 : Spanish
Default                                  : Yes
Forced                                   : No

Menu #1
00:00:00.000                             : es:Opening / es:Episodio / es:Ending
00:20:24.932                             : es:Avance del siguiente episodio

Menu #2
00:00:00.000                             : es:Opening / es:Episodio / es:Ending
00:20:24.932                             : es:Avance del siguiente episodio

```

**Comment by wiiaboo** [comment]
@Jj0YzL5nvJ  [`cycle edition`](https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L143)

**Comment by Jj0YzL5nvJ** [comment]
> @Jj0YzL5nvJ cycle edition

Thanks, **mayus e** works, now I don't see any problem.
