### ISSUE TITLE
Subtitle Rendering question

### ISSUE THREAD

**Issue by phydano** [mpv-player/mpv#3074]
Hi,

I am not sure if this is a problem or I did not have a proper configuration. The issue I see is with how the subtitle rendering in MPV against VLC are different. Here are the screenshots:

https://www.dropbox.com/s/mx5oin9rc2285hn/MPV%20-%20sub%20not%20seem%20to%20blend%20well.png?dl=0
https://www.dropbox.com/s/iqywtj363fi1ac9/VLC%20-%20sub%20seem%20to%20blend%20well.png?dl=0

As you can see, the VLC one renders the subtitle that looks blended to the video (sorta blurry) where as MPV subtitle doesn't look that too blend with the video (sorta bright). Is it an issue? Or can I put something into my configuration file to have the same effect? Apologies if I posted in a wrong place, but help is appreciated :)

Also, on my Mac when I drag multiple files over to MPV, it only play one file. To play multiple files, I have to put all the files in a folder and drag that folder to MPV. Is it a bug?

**Comment by wm4** [comment]
mpv usually prefers rendering subtitles in screen space, because it gives better quality. `--vo=opengl:blend-subtitles=video` should give different behavior.

>Also, on my Mac when I drag multiple files over to MPV, it only play one file. To play multiple files, I have to put all the files in a folder and drag that folder to MPV. Is it a bug? 

I have no idea.

**Comment by phydano** [comment]
Cool thank you. I will give that a try. Also how can I create a playlist with MPV?

**Comment by wm4** [comment]
Not sure what you mean.

**Comment by phydano** [comment]
A playlist so I can play multiple files continuously. At the moment I cannot drag multiple files to mpv as it only play one file....I have to put them in a folder and drag it to mpv to have it play all the files....which is daunting. 

I tested your code and it works. Previously I have this:
`vo=opengl-hq:icc-profile-auto`
but how can I merge these two together into one line?
`vo=opengl-hq:icc-profile-auto`
`vo=opengl:blend-subtitles=video`

If I leave them as two lines, the bottom one overrides the top one....any suggestion?

**Comment by wm4** [comment]
`vo=opengl-hq:icc-profile-auto:blend-subtitles=video`

> A playlist so I can play multiple files continuously. At the moment I cannot drag multiple files to mpv as it only play one file....I have to put them in a folder and drag it to mpv to have it play all the files....which is daunting. 

I think putting a list of files into a .m3u text file should always work. Dragging multiple files at once on the mpv window should work too, though.

**Comment by phydano** [comment]
I just edited my above post a few seconds ago. Highlighting multiple files and double click them actually add all the files to the list. However, I have no luck with dragging multiple files. 

Thank you so much for the code. I will test it now.

**Comment by kevmitch** [comment]
For dragging multiple files issue, see #3076

**Comment by Hrxn** [comment]
FWIW, a playlist can also be a simple plain text file, where one line = path to file.
You can generate such a file with a simple shell script etc.

At least that works for me here..

**Comment by phydano** [comment]
While watching movies through the use of `blend-subtitle=video`, there is a bit of problem I noticed with how it being render. I noticed that around the subtitle there is some sort of bleeding (I'm not sure if this is a word to describe it, but you can see what I mean in the screenshots below...). However when look into VLC, there doesn't seem to be any sort of bleed. Is it a bug?

https://www.dropbox.com/s/xpzsoytipygj2im/vlc%20blend%20subtitle.png?dl=0
https://www.dropbox.com/s/8hqq8k32vanz5hj/mpv%20blend-subtitle%3Dvideo.png?dl=0

**Comment by wm4** [comment]
Looks like ringing caused by whatever scaler you're using, but not sure.

**Comment by phydano** [comment]
I am not using any scaler. This is a complete line: `vo=opengl-hq:icc-profile-auto:blend-subtitles=video` (which is what you gave me...)

**Comment by haasn** [comment]
This is an expected result of combining `blend-subtitles=video` with `scale=spline36` (the `opengl-hq` default).

You could try setting `scale-antiring=1`. If that doesn't help, and you **really** want to replicate VLC's results at the cost of worse quality, use `scale=bilinear` (or just use `vo=opengl` instead of `vo=opengl-hq`).

**Comment by phydano** [comment]
> You could try setting scale-antiring=1. If that doesn't help, and you really want to replicate VLC's results at the cost of worse quality, use scale=bilinear (or just use vo=opengl instead of vo=opengl-hq).

Thanks for the explanation. I don't want to sacrifice quality so I am using 'yes' instead of 'video' now.
