### ISSUE TITLE
Dragging multiple files not working

### ISSUE THREAD

**Issue by phydano** [mpv-player/mpv#3076]
Hi,

Dragging multiple files to mpv only play one file. On the other hand, highlighting all the files and double click on that allows mpv to add files to the list (i.e. now all files can be play). I am on the latest build as I just download it yesterday.

**Comment by kevmitch** [comment]
What OS?

**Comment by phydano** [comment]
MAC OSX El Capitan 10.11.4
MPV (git-1944a34)

**Comment by wm4** [comment]
Dragging multiple files should start playback of the first file, and queue the other files to the internal playlist. It doesn't play all at once, if that's what you're expecting?

**Comment by phydano** [comment]
Dragging multiple files only play the fist file, that's it. On the other hand, highlight all files and double click them, play the first file and add the rest to the queue. Also I have tested by adding mpv to a dock. Dragging multiple files and drop them to the mpv icon in dock also add files to the queue. 

Have you try drag and drop multiple files to mpv when it's open?

**Comment by wm4** [comment]
I confirmed that it works on Linux.

**Comment by phydano** [comment]
Any confirmation on Mac OS?

**Comment by Nyx0uf** [comment]
Dragging on the mpv window or application icon ? (Seems it works from the dock if I understood)

**Comment by Hrxn** [comment]
Dropping on the Dock should work as intended, while dropping on the mpv window does not, apparently (OS X).

**Comment by NaturalHarmonia** [comment]
How would this work on Windows 10?
