### ISSUE TITLE
PCM audio track popping during playback.

### ISSUE THREAD

**Issue by ztxgeol** [mpv-player/mpv#3077]
- Hi there, I'm using mpv 0.17 which is installed by Homebrew on OS X 10.9.5.
- and YES, I'm using the lastest version.
- The problem is when I playing my file(.m2ts) on mpv, It produce popping sounds EVER TIME the BGM comes to a high tone.
- Audio Track Format: PCM, 48kHz, 4616kbps.

Here's the log.
[cplayer] Command line options: '-v'
[cplayer] mpv 0.17.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Apr 19 13:05:38 CST 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.17.103
[cplayer]    libavcodec      57.24.102
[cplayer]    libavformat     57.25.100
[cplayer]    libswscale      4.0.100
[cplayer]    libavfilter     6.31.100
[cplayer]    libswresample   2.0.101
[cplayer] ffmpeg version: 3.0.1
[cplayer] 
[cplayer] Configuration: waf configure --prefix=/usr/local/Cellar/mpv/0.17.0 --enable-gpl3 --enable-zsh-comp
[cplayer] List of enabled features: any-gl apple-remote asm atomic-builtins atomics av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-profile-name avframe-metadata avframe-skip-samples bsd-fstatfs build-date c11-tls cocoa coreaudio cplayer debug-build dlopen fchmod gl gl-cocoa glob gpl3 iconv jpeg lcms2 libass libass-osd libav libavdevice libavfilter libdl libm libswresample lua nanosleep optimize osx-thread-name posix posix-or-mingw posix-spawn pthreads resampler shm subprocess termios tv videotoolbox-gl videotoolbox-hwaccel zlib zsh-comp
[global] config path: '' -> '/Users/ztxgeol/.config/mpv'
[global] config path: 'mpv.conf' -> '/Users/ztxgeol/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/ztxgeol/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/Users/ztxgeol/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/ztxgeol/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/bin/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/bin/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/Cellar/mpv/0.17.0/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/Cellar/mpv/0.17.0/etc/mpv/config'
[cplayer] Reading config file /Users/ztxgeol/.config/mpv/mpv.conf
[cplayer] Setting option 'vo' = 'opengl-hq:backend=cocoa' (flags = 4)
[cplayer] Setting option 'hwdec' = 'videotoolbox' (flags = 4)
[cplayer] Setting option 'display-fps' = '60' (flags = 4)
[cplayer] Setting option 'ao' = 'coreaudio' (flags = 4)
[cplayer] Setting option 'audio-file-auto' = 'fuzzy' (flags = 4)
[cplayer] Setting option 'ad-lavc-downmix' = 'no' (flags = 4)
[cplayer] Setting option 'audio-normalize-downmix' = 'no' (flags = 4)
[cplayer] Setting option 'geometry' = '50%:50%' (flags = 4)
[cplayer] Setting option 'autofit-larger' = '70%x70%' (flags = 4)
[cplayer] Setting option 'autofit-smaller' = '30%x30%' (flags = 4)
[cplayer] Setting option 'fs-black-out-screens' = 'yes' (flags = 4)
[cplayer] Setting option 'ontop' = 'yes' (flags = 4)
[cplayer] Setting option 'cursor-autohide' = '1800' (flags = 4)
[cplayer] Setting option 'no-osd-bar' = '' (flags = 4)
[cplayer] Setting option 'osd-bar-w' = '10' (flags = 4)
[cplayer] Setting option 'osd-bar-h' = '2' (flags = 4)
[cplayer] Setting option 'osd-border-size' = '1' (flags = 4)
[cplayer] Setting option 'osd-bar-align-x' = '1' (flags = 4)
[cplayer] Setting option 'osd-bar-align-y' = '1' (flags = 4)
[cplayer] Setting option 'osd-border-size' = '0' (flags = 4)
[cplayer] Setting option 'osd-color' = '#CCFFFFFF' (flags = 4)
[cplayer] Setting option 'osd-border-color' = '#000000' (flags = 4)
[cplayer] Setting option 'osd-duration' = '2000' (flags = 4)
[cplayer] Setting option 'osd-font' = 'ArialMT' (flags = 4)
[cplayer] Setting option 'osd-font-size' = '28' (flags = 4)
[cplayer] Setting option 'screenshot-template' = '~/Desktop/mpv-screenshot-%n' (flags = 4)
[cplayer] Setting option 'screenshot-format' = 'png' (flags = 4)
[cplayer] Setting option 'screenshot-high-bit-depth' = 'yes' (flags = 4)
[cplayer] Setting option 'screenshot-jpeg-quality' = '100' (flags = 4)
[cplayer] Setting option 'use-filedir-conf' = 'yes' (flags = 4)
[cplayer] Setting option 'no-input-default-bindings' = '' (flags = 4)
[cplayer] Setting option 'sub-auto' = 'fuzzy' (flags = 4)
[cplayer] Setting option 'sub-text-font-size' = '32' (flags = 4)
[cplayer] Setting option 'sub-text-font' = 'FZYOUH_506L' (flags = 4)
[cplayer] Setting option 'sub-text-border-size' = '0' (flags = 4)
[cplayer] Setting option 'sub-text-shadow-offset' = '1' (flags = 4)
[cplayer] Setting option 'sub-text-shadow-color' = '#000000' (flags = 4)
[cplayer] Setting option 'sub-text-margin-y' = '70' (flags = 4)
[cplayer] Setting option 'sub-codepage' = 'utf8:gb18030' (flags = 4)
[cplayer] Setting option 'ass-shaper' = 'complex' (flags = 4)
[cplayer] Setting option 'cache' = 'auto' (flags = 4)
[cplayer] Setting option 'cache-seek-min' = '1024' (flags = 4)
[cplayer] Setting option 'demuxer-readahead-secs' = '5.0' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] mpv 0.17.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Apr 19 13:05:38 CST 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.17.103
[cplayer]    libavcodec      57.24.102
[cplayer]    libavformat     57.25.100
[cplayer]    libswscale      4.0.100
[cplayer]    libavfilter     6.31.100
[cplayer]    libswresample   2.0.101
[cplayer] ffmpeg version: 3.0.1
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]

**Comment by kevmitch** [comment]
do you have a sample file where you could point to a time-stamp with the problem?

**Comment by ztxgeol** [comment]
sorry but i don't have any sample files.😓

**Comment by lachs0r** [comment]
Try `--audio-normalize-downmix=yes`.

(I think it was a really bad idea to make the default `no` by the way. Too quiet on laptop speakers by default is better than destroying them with clipping.)

**Comment by ztxgeol** [comment]
No more clippings after setting `yes` to `--audio-normalize-downmix`, thanks!
But I wonder will this option actully normalize the audio since I've heard many suggestions on not normalizing audio ?

**Comment by wm4** [comment]
>(I think it was a really bad idea to make the default no by the way. Too quiet on laptop speakers by default is better than destroying them with clipping.)

You can't just win. But for the "normal" case of typical surround movie content, not normalizing seems to be better.

**Comment by ztxgeol** [comment]
Problem solved !
Thanks for the patience !
