### ISSUE TITLE
Default Window Size

### ISSUE THREAD

**Issue by es0phagus** [mpv-player/mpv#3078]
Hey,
I have browsed through the configuration options, but I cannot seem to find the command for what I want. Basically, I want the mpv window to open by default at Half Size rather than Normal Size:

<img width="249" alt="screen shot 2016-04-23 at 14 23 16" src="https://cloud.githubusercontent.com/assets/11819257/14761649/4c77a10e-095f-11e6-9e53-20fe6ca5638b.png">

Is there a command I can input into the config file?

**Comment by twofoureight** [comment]
Have you tried [--autofit-larger](https://mpv.io/manual/master/#options-autofit-larger)?

**Comment by twofoureight** [comment]
Add `window-scale=0.5` to your config.

**Comment by es0phagus** [comment]
^ Yep, that seems to have worked. Thank you.
