### ISSUE TITLE
Screen not redrawn after unlock

### ISSUE THREAD

**Issue by tewe** [mpv-player/mpv#3079]
1. play a video full screen
2. hit pause
3. wait for the screen to lock
4. enter password to unlock

At this point mpv is still paused in the foreground, but it looks like the computer is still locked, because the screen isn't redrawn.
1. hit space bar

Video will resume playback normally.

git-2b4123f on OS X 10.11.4

**Comment by wm4** [comment]
Probably means it should be redrawn after leaving unlock, but it's not clear at all in response to which event.

Normally cocoa/GL apps don't need to redraw themselves because the compositor always keeps the window surface data around.

CC @pigoz

**Comment by Akemi** [comment]
does this still happen? even with `--no-config`?

**Comment by Akemi** [comment]
not reproducible. if it still happens drop a comment and i will reopen it.
