### ISSUE TITLE
Regexp or wildcards with option --sub-paths

### ISSUE THREAD

**Issue by feofankss** [mpv-player/mpv#308]
Please add regexp or wildcards to this option. Many directories containing subs may have different format of names. It's a problem.

**Comment by glukki** [comment]
@wm4 I really need that for subs and audio!
I'm watching a couple of series right now, and they have audio directory in completely different format: `{Lang} Sound [{author}]`, `{LANG} sound`.
I want to put just `*sound*` wildcard in my config to cover most of my cases!

Would you accept a good patch implementing that?

**Comment by DeadNews** [comment]
@glukki 
https://github.com/dya-tel/mpv-scripts#fuzzydirlua
Allows using wildcards for sub-file-paths and audio-file-paths:
`sub-file-paths=path1/**:path2/**`
`sub-file-paths=**`
