### ISSUE TITLE
Using MPV with OMX hardware decode

### ISSUE THREAD

**Issue by duyhotan2000** [mpv-player/mpv#3081]
Hello!

After some time finding a suitable player for porting to our embedded board (running an ARM64 chipset), we have chosen MPV.

However, we want to use MPV with hardware decoding. Our company provides an OMX layer for hardware decoding. So can we integrate this OMX layer to MPV?

We have investigated to integrate OMX with MPV, but we are not sure that we need to write a new decoder module (like vd_lavc.c) or just write a hardware decode module (like rpi.c)?

Thank you!

**Comment by wm4** [comment]
It would be preferred as part of libavcodec. rpi.c in mpv is just a tiny wrapper to activate the libavcodec implementation.

libavcodec already has an OMX encoder, but not decoder: https://git.libav.org/?p=libav.git;a=blob;f=libavcodec/omx.c;h=01920cbd0c6a16f49a5d7f14bfd61eceabb81b79;hb=HEAD

I've also asked a Libav dev whether he would post his WIP OMX decoder.

What hw is it?

**Comment by duyhotan2000** [comment]
It's Renesas' hardware.
We have had an OMX IL Media Component library.

If you have any information, please share with me!
Thank you so much!
