### ISSUE TITLE
Subtitles don't show for 5 seconds after Ordered Chapter

### ISSUE THREAD

**Issue by kurisubrooks** [mpv-player/mpv#3082]
Watching any .mkv file with ordered chapters with subtitles, for about 3 to 5 seconds after the ordered chapter has finished playing, the subtitles for the video won't show for that period of time. 

---
OS X 10.11 El Capitan, mpv 0.14
(Also tested on 0.15 Linux)

Searched for bugs similar to mine but all I was able to find was #2264, but I think this is unrelated.

**Comment by wm4** [comment]
Update to a later mpv release, that should fix it, I think.

**Comment by kurisubrooks** [comment]
Oh, I swore 0.15 was the latest. I'll give it a shot. Sorry for not looking into that 😕
