### ISSUE TITLE
Tools: umpv - play instead of append

### ISSUE THREAD

**Issue by zunder** [mpv-player/mpv#3083]
Preface: I did ask the question on #mpv IRC channel, could not get a solution though.

Using umpv from tools ([/TOOLS/umpv](https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv)) has the opportunity of appending videos to a running instance of mpv. I would rather have a following behaviour:

- umpv videoA.mp4 # mpv opens and videoA.mp4 starts playing
- umpv videoB.mp4 # same mpv instance is choosen and videoB.mp4 starts playing immediately

Note: in IRC channel one suggested to remove the append part in line 81:
https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv#L81
That did not work though (now videoB.mp4 did not play and did not queue in the playlist)

**Comment by wm4** [comment]
Works just fine. You probably removed the `\n` part, instead of strictly only the `append`.

**Comment by zunder** [comment]
@wm4 well, you got me. Works as expected, thanks for the follow up.
