### ISSUE TITLE
Mac Does Not Sleep

### ISSUE THREAD

**Issue by es0phagus** [mpv-player/mpv#3085]
Hey,

I have noticed for the second occasion that my mac does not sleep when mpv is running. This results in the battery draining to 0% by the time I wake up. Is it intended to be like this? I usually try to close down mpv when I'm not using it, but ever so often, I overlook it and this happens.

**Comment by wm4** [comment]
Why would you leave mpv "open"? Is it playing anything?

**Comment by Argon-** [comment]
>Is it intended to be like this?

So you would prefer your computer to enter standby while watching a movie...? Do you want users to deactivate standby every time they want to watch a movie?

**Comment by pigoz** [comment]
It's intended. If you pause it doesn't happen, as mentioned by @Argon- it;s to stop the computer from entering sleep while watching a movie.

**Comment by bitfrickler** [comment]
@pigoz: Definitely not true. It prevents my Mac from getting sleep even if it's paused.

**Comment by Argon-** [comment]
Definitely working fine on my machine  (mpv master, 10.11). Since I haven't seen similar reports, I'd assume it's a problem on your end maybe caused by some other program?

**Comment by Akemi** [comment]
can't reproduce and not enough info.
