### ISSUE TITLE
support for debugging when subtitle files fail to load. 

### ISSUE THREAD

**Issue by shirishag75** [mpv-player/mpv#3089]
Hi all, 
There are times when .ass or .sub subtitle files fail to load even though they have the same file-name as the media file.  In such instances, it doesn't tell what is wrong or why those files are not being loaded. If such a debugging method was available it would go a long way in understanding why a particular subtitle or any other feature doesn't work. I am running 0.14 under Debian and looked in list-options but without success for the same 👎 

```
[$] mpv --list-options | grep debug
                                                                                                
(null) requires an argument
```
Look forward for answers.

**Comment by wm4** [comment]
Use `-v`, then fish it out. In most cases, libavformat simply fails to detect the format properly.
