### ISSUE TITLE
RTMP support is not complete with ytdl_hook

### ISSUE THREAD

**Issue by gangsterakato** [mpv-player/mpv#3090]
Using mpv to directly playing Hitbox streams doesn't work. Example: `mpv http://www.hitbox.tv/csgobattle`.

```
$ mpv http://www.hitbox.tv/csgobattle
Playing: http://www.hitbox.tv/csgobattle
[ffmpeg] RTMP_ReadPacket, failed to read RTMP packet header
Failed to open rtmp://edge.live.hitbox.tv/live/csgobattle.
```

A `youtube-dl` developer, @yan12125, says that the RTMP support is not complete with `ytdl_hook`.

You can see the full detail here: https://github.com/rg3/youtube-dl/issues/9348

mpv 0.17.0
youtube-dl 2016.04.24
ffmpeg 2.8.6
ffprobe 2.8.6
rtmpdump 2.4

Linux Void x64 Cinnamon - Kernel version 4.5.2

**Comment by yan12125** [comment]
With some quick investigation I guess the reason is in ```ytdl_hook.lua```:
```Lua
 if not (json.play_path == nil) then
```
For this stream, there is no ```play_path``` but it's really RTMP. Maybe mpv should check the ```protocol``` field, too.

**Comment by wiiaboo** [comment]
Stream works if ffmpeg/mpv was compiled with librtmp. A bug ticket has been posted in FFmpeg. While it's not fixed, your alternatives are getting mpv compiled with FFmpeg with librtmp or using livestreamer.

**Comment by ChrisK2** [comment]
The hook should now work correctly.

**Comment by wiiaboo** [comment]
Additionally, you can add `[protocol!=rtmp]` and it'll work with hitbox HLS streams.
Ex:
`ytdl-format=(bestvideo+bestaudio/best)[protocol!=rtmp]/best`
