### ISSUE TITLE
d3d11va: mpv stopped working when failed to find a suitable decoder

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#3092]
Tested on latest git.
cli:
`mpv --vo=opengl:backend=angle --hwdec=auto input`

**Comment by kevmitch** [comment]
so what exactly is the output? by "stopped working" do you mean it actually crashes?

**Comment by shinchiro** [comment]
yes it crashed after showing '[d3d11va] Failed to find a suitable decoder' message

**Comment by kevmitch** [comment]
did it used to find a decoder on this file?

**Comment by shinchiro** [comment]
here's the log:
[log.txt](https://github.com/mpv-player/mpv/files/243458/log.txt)

My laptop didnt support hwdec for this file so I expect it fallback to software decoding but it went crashed instead
