### ISSUE TITLE
YTDL caching does not account for playback speed

### ISSUE THREAD

**Issue by alystair** [mpv-player/mpv#3095]
I tend to watch most videos at 1.2x+ speed to save time in my life... however when watching from YTDL it doesn't account for playback speed so the cache runs out pretty quickly.

**Comment by ChrisK2** [comment]
youtube-dl itself has nothing to do with caching. With which sites does this happen? YouTube? all?

**Comment by alystair** [comment]
Oh, I'm using Cruncyroll.

**Comment by alystair** [comment]
The "fix" I'm doing is simply waiting for most of the video to cache before initially playing

**Comment by ChrisK2** [comment]
I guess the streaming server CR is using in your area simply sends data out only at 1x viewing speed. So yeah, caching the most of the file beforehand would be the only solution.

A `-v` log of you starting playback might give us more insights.

**Comment by ChrisK2** [comment]
(missclick)

**Comment by alystair** [comment]
All -v does is bring back the dreaded 'Cache is not responding' error - sometimes even when the playback is paused the the cache is filling up.

**Comment by haasn** [comment]
Probably the best thing to do would be to have youtube-dl download the videos in the background (from the command line) when you aren't watching them. Then, you get around to watching them, you could just watch straight from disk and save yourself the hassle.

All in all it sounds like a network bandwidth issue, not an mpv issue. CR does most likely rate-limit their downloads (which I personally don't really understand, why not rate limit in the client instead?) to avoid “wasting” bandwidth in case somebody stops playing the video early.

**Comment by lachs0r** [comment]
Late response, but yes, at least some of CR’s CDNs have bandwidth limits in place (I think it’s exactly 16 Mbit/s with Akamai, for example).

**Comment by lachs0r** [comment]
Well, we really can’t fix slow networks.
