### ISSUE TITLE
Fullscreen needs a flag with `--hwdec=rpi` on Raspberry PI 3

### ISSUE THREAD

**Issue by mgcrea** [mpv-player/mpv#3096]
```
$ mpv --quiet --no-osc --no-border --no-window-dragging --hwdec=rpi --no-stop-screensaver --fullscreen --fs-screen=all --ontop --ao=alsa --ao=alsa:device=[hdmi] /srv/player/data/media/571b9c29-530c-4e41-aa42-050eac110004/media/apple-tv-b1-2.mp4
```

Does enable GPU decoding, however, I can still see the desktop/background ~~behind~~ around the video, any ideas? I'm using Ubuntu Mate 16.04LTS on a Raspberry PI 3.

```
$ mpv --version
mpv 0.14.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.6-1ubuntu2+rpi1~xenial1.8
```

```
$ uname -a
Linux player-655d 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l armv7l armv7l GNU/Linux
```

**Comment by wm4** [comment]
Define "behind the video"?

**Comment by mgcrea** [comment]
@wm4 Like a windowed mode (but frameless), can take a picture if you want.

**Comment by Gusar321** [comment]
The rpi vo wil not clear what's around the video by default, you have to request it:

--vo=rpi:background=yes

**Comment by mgcrea** [comment]
@Gusar321, thanks it does work!

Shouldn't it be the other way around though? clear background by default (like on any other platform), and add a specific flag to skip background clearing on the rpi? `--fullscreen` is pretty explicit about the user wish for mpv to clear the background.

**Comment by wm4** [comment]
It can reduce performance by a lot because it adds another screen-size compositing layer. Not sure how to make this work "correctly".

**Comment by mgcrea** [comment]
Out of curiosity, what would be the lightest way to add such fullscreen layer? Write a custom OpenGL / SDL app?

**Comment by wm4** [comment]
Use what was said above (`--vo=rpi:background=yes`)?

OpenGL or SDL will be slow on the RPI.
