### ISSUE TITLE
building mpv failed at linking in GCC 6.1

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#3097]
not quite sure if its related with mpv or not. I tried compiling mpv in gcc 6.1 just now. 32bit compiled without problem but compiling 64bit gives error..its 'multiple definition' error & point out to 'osdep/path-win.c'

[mpv-build-error.txt](https://github.com/mpv-player/mpv/files/243646/mpv-build-error.txt)

**Comment by wm4** [comment]
You can try this branch: https://github.com/rossy/mpv/commit/win-remove-libuuid

**Comment by shinchiro** [comment]
yeah, that fix the problem. I can compiled successfully on gcc 6.1 & gcc 5.3 (32bit and 64bit) :+1:

**Comment by rossy** [comment]
Great. I'll merge that patch then.
