### ISSUE TITLE
Hello! Who can help me solve the problem of playing LPCM track, thank you! Google Translate

### ISSUE THREAD

**Issue by caicy1991** [mpv-player/mpv#3098]
mkv package 24-bit LPCM audio track is not playing correctly, need to set up how? 
pcm_s24le
Mac OS X EI Capitan
mpv 0.17.0
Google Translation

**Comment by kevmitch** [comment]
What actually happens?

**Comment by caicy1991** [comment]
First of all, my computer is a MacBook Pro, the system is Mac OS X EI Capitan, mpv version is 0.17.0
Secondly, you can not play properly file format is mkv, video track is AVC, the audio track is LPCM
When I play .mkv files, sound is not playing correctly issued harsh noise
Specifically when playing a 16-bit LPCM (pcm_s16le) when everything is normal, there is no problem; and 24-bit LPCM (pcm_s24le) playback when problems arise
How to solve it?

**Comment by kevmitch** [comment]
It should just work. I don't have a Mac to test, but last I did it was no problem on Windows or Linux. 

If the pcm_s24le file is multi-channel, you might need to specify `--audio-normalize-downmix=yes` to prevent clipping. Otherwise, there might be a bug in mpv's coreaudio audio output driver.

**Comment by wm4** [comment]
It's easily possible that demuxing of particulat pcm in mkv files is broken, so a sample would be good.

**Comment by caicy1991** [comment]
Files from Blu-ray movie "The Prestige" Extract, which has LPCM audio track.
If I directly play .m2ts files, everything is normal
But to extract the audio track re-packaged as mkv file, mpv will not play properly, there is very harsh voice.

**Comment by richardpl** [comment]
I don't have that or any Blu-ray movie.

**Comment by haasn** [comment]
> If I directly play .m2ts files, everything is normal

Sounds like the error was introduced during conversion from .m2ts to .mkv

**Comment by wm4** [comment]
PCM in MKV is mostly a hack (what a surprise), so it's pretty possible that the demuxer does something wrong. But no sample, no fix.

**Comment by ztxgeol** [comment]
I've been suffered from this promblem, too.
Using `ao=coreaudio:exclusive` maybe helpful for you.

**Comment by 1000000002** [comment]
That's a bug in mkvtoolnix.  Fixes are in builds 01209+ of 9.1.0
https://github.com/mbunkus/mkvtoolnix/issues/1683
https://mkvtoolnix.download/windows/pre/

If you don't want to update to a prerelease, demux using eac3to.  mkvtoolnix can then mux it to mkv just fine, it just had trouble demuxing from m2ts.

I use MPC-HC so I knew the problem wasn't in the player.  You can thank me for sending in the report and sample to mosu.

**Comment by caicy1991** [comment]
Thank you @1000000002
