### ISSUE TITLE
Hello ! Mpv builds for Mac OS X

### ISSUE THREAD

**Issue by Begooder** [mpv-player/mpv#3099]
Hi everyone, 

I really love mpv and use it every day.
It is not a technical issue but there is no new mac build since February (http://sva.wakku.to/~chris/mpv_builds/).
Do you know if it is normal or is there another site like ChrisK's mpv builds ?

Unfortunately, I am not enough skilled to build it myself but I don't want go back to VLC...

Cheers and sorry for my English

**Comment by wm4** [comment]
That's up to @ChrisK2.

**Comment by Hrxn** [comment]
Any reasons for not using the Homebrew version?

**Comment by ChrisK2** [comment]
See #2775.

**Comment by Begooder** [comment]
I used Homebrew for the first time and it works well thx

But, how to update mpv with Homebrew in the future ?

**Comment by Hrxn** [comment]
1. Update Homebrew itself:
`brew update`

2. Upgrade everything with:
`brew upgrade`

Or: upgrade a specific formula with:
`brew upgrade $FORMULA`
