### ISSUE TITLE
RPI: quitting mpv while in fullscreen with the background layer results in a black screen

### ISSUE THREAD

**Issue by Gusar321** [mpv-player/mpv#3100]
Probably a fallout of the recent changes to vo_rpi. It seems the background layer does not get destroyed when mpv quits.

**Comment by wm4** [comment]
From the code it looks like it is destroyed.

**Comment by Gusar321** [comment]
Doesn't get destroyed in practice though. If I blindly type and run mpv again, the video will appear. So I blindly typed mpv --vo=rpi:layer=-12 and now only the osd/subtitles are visible, which indicates that the background layer from the previous mpv instance is still there.

**Comment by Gusar321** [comment]
I looked into this and figured it out. Some code was removed from uninit in commit 74e3d11, I added it back and voila, the background overlay is now gone on quit.
```diff
diff --git a/video/out/vo_rpi.c b/video/out/vo_rpi.c
index bbbaae9..cd37362 100644
--- a/video/out/vo_rpi.c
+++ b/video/out/vo_rpi.c
@@ -729,6 +729,9 @@ static void uninit(struct vo *vo)

     destroy_dispmanx(vo);

+    if (p->update)
+        vc_dispmanx_update_submit_sync(p->update);
+
     if (p->renderer)
         mmal_component_release(p->renderer);

```
However, is uninit the correct place for this now, or should it maybe go into destroy_dispmanx?

**Comment by wm4** [comment]
I guess it makes no difference. Can you send a git-format-patch or a PR?

**Comment by wm4** [comment]
Got fixed.
