### ISSUE TITLE
can't get back to 1.0x playing speeds with default keybinds

### ISSUE THREAD

**Issue by kerokeroloid** [mpv-player/mpv#3102]
how to reproduce:

open a movie with mpv
press ] until playing speed goes to 100x
press [ until playing speed goes close to 1x

it is now impossible to make the speed go to 1x again without closing and opening mpv again.

proposed fix: dunno lol

**Comment by wm4** [comment]
Hit backspace.

**Comment by kerokeroloid** [comment]
... wow. and I bet this doesn't even make top 10 of your worst bug reports.
