### ISSUE TITLE
mpv - nautilus focus

### ISSUE THREAD

**Issue by rcspam** [mpv-player/mpv#3103]
Hi,
When nautilus windows focus is set to follow the mouse, mpv lose the focus in full-screen, so the shortcuts influence the nautilus window under. Tested on ubuntu 14.04 and 16.04..
This is very uncomfortable.
This is a long time issue (several years) which is not happened with mplayer or mplayer2.

Thanks for this cool app
rcspam

**Comment by lachs0r** [comment]
That’s a problem of your window manager.
