### ISSUE TITLE
It drops frames when playing 1920 x 1080 HEVC 10bit video with interpolation.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#3105]
CPU: intel i5-4460
iGPU: intel HD4600
OS: Ubuntu 16.04

I can play 1920 x 808 H264 video with vaapi hardware acceleration and interpolation flawlessly, is it because that HD4600 is not strong enough to handle the HEVC 10bit codec?

**Comment by wm4** [comment]
Intel GPUs don't support HEVC hardware acceleration, so there's that.

**Comment by laichiaheng** [comment]
@wm4 Does the hardware acceleration affect the interpolation?

**Comment by mc4man** [comment]
you have Haswell (HSW) so no hwdec for hevc, period.

libva-intel-driver - 
Platform definitions:
CTG: Cantiga, Intel GMA 4500MHD (GM45)
ILK: Ironlake, Intel HD Graphics for 2010 Intel Core processor family
SNB: Sandybridge, Intel HD Graphics for 2011 Intel Core processor family
IVB: Ivybridge
HSW: Haswell
BDW: Broadwell
CHV/BSW: Cherryview/Braswell
SKL: Skylake
BXT: Broxton
KBL: Kabylake

Codecs
------

H.264   D   ILK+
H.264   E   SNB+
MPEG-2  D   CTG+
VC-1    D   SNB+
JPEG    D   IVB+
JPEG    E   CHV+/BSW+
VP8     D   BDW+
VP8     E   CHV+/BSW+
HEVC    D   CHV+/BSW+
HEVC    E   SKL+
VP9     D   BXT+
HEVC 10bit     D       BXT+
VP9 10bit      D       KBL+

**Comment by laichiaheng** [comment]
@mc4man 
Is the interpolation calculated by CPU?
Does the VAAPI hardware acceleration affect the performance of interpolation?

**Comment by kevmitch** [comment]
> Is the interpolation calculated by CPU or GPU?

GPU (via opengl)

> Does the VAAPI hardware acceleration affect the performance of interpolation?

it should not

**Comment by laichiaheng** [comment]
@kevmitch This is why I am so confused, wondering why HD4600 can't handle 23.976fps 1920x1080 resolution with interpolation.

**Comment by kevmitch** [comment]
it's not hard to tax an hd4600 with mpvs opengl options. Intel's drivers have also been getting worse for it as time goes on [91066](https://bugs.freedesktop.org/show_bug.cgi?id=91066), [93361](https://bugs.freedesktop.org/show_bug.cgi?id=93361), [93971](https://bugs.freedesktop.org/show_bug.cgi?id=93971).

Right now I'm running a kernel with the 12bpc patch reverted and and a year old xorg intel driver in the deprecated UXA mode to get acceptable results.

**Comment by kevmitch** [comment]
or wait, the above bugs are with my hd4400. My hd4600 is only running windows, so not sure actually. It's possible hd4600 doesn't even work with UXA at all. 

Still, one thing you could check is if the estimated-display-fps is actually close to the display-fps. If not, set the latter to the actual value with --display-fps.

**Comment by maletor** [comment]
@kevmitch just ditch the intel drivers and use kernel modesetting.

**Comment by Hrxn** [comment]
> Still, one thing you could check is if the estimated-display-fps is actually close to the display-fps. If not, set the latter to the actual value with --display-fps.

How close is close enough? When is it beneficial to set it with `display-fps` to 60, or 120, or 144, or whatever current displays offer
