### ISSUE TITLE
Blend-subtitle=video causes 'ring' or 'bleed' around subtitles

### ISSUE THREAD

**Issue by phydano** [mpv-player/mpv#3108]
Hi,

This is a follow up from issue [#3074](https://github.com/mpv-player/mpv/issues/3074). To recap...while watching movies through the use of `blend-subtitle=video`, there is a bit of problem I noticed with how it being render. I noticed that around the subtitle there is some sort of bleeding (I'm not sure if this is a word to describe it, but you can see what I mean in the screenshots below...). Just to compare with VLC, there doesn't seem to be any sort of bleed though. Is it a bug?

[VLC Blend Subtitle](https://www.dropbox.com/s/xpzsoytipygj2im/vlc%20blend%20subtitle.png?dl=0)
[MPV Blend Subtitle](https://www.dropbox.com/s/8hqq8k32vanz5hj/mpv%20blend-subtitle%3Dvideo.png?dl=0)

P.S: I don't use any scaler though apart from this line: `vo=opengl-hq:icc-profile-auto:blend-subtitles=video`. I am on MAC OSX Capitan.

**Comment by lachs0r** [comment]
That’s just because mpv uses a scaler with stronger ringing/sharpening properties. You can try using the `scale-antiring` sub-option, tweaking other scaler options, or picking a different scaler.

**Comment by Hrxn** [comment]
mpv screenshot looks better to me..

Yes, it has some slight ringing, but I still like it better.

**Comment by haasn** [comment]
(You could also just use a different value of `blend-subtitles`)

**Comment by phydano** [comment]
> You can try using the scale-antiring sub-option, tweaking other scaler options

Thanks. I'll play around with that option later.

> mpv screenshot looks better to me..
Yes, it has some slight ringing, but I still like it better.

Yep, MPV is better than the rest of media players I'm using on Mac (e.g. VLC, Elmedia). I was just confuse why there is the ringing but now I know why its there, XD.

> (You could also just use a different value of blend-subtitles)

I am using blend-subtitles=yes now.
