### ISSUE TITLE
Embedded DVD subtitles (IDX/SUB in MKV, VOBSUB in VOB) do not display after update to v0.17

### ISSUE THREAD

**Issue by optimiz** [mpv-player/mpv#3109]
Hello, @mpv-player is great, thank you for your hard work and diligent effort.  After updating mpv from v0.16 to v0.17, neither IDX/SUB (in MKV) nor VOBSUB (in VOB) subtitles display. I tested under both hardware (vdpau) and software decode; these particular graphic-based subtitles simply do not display.  Text-based subtitles (SRT and ASS) display correctly (before and after the update), only graphic-based subtitles do not display after the update to v0.17.  Here's the sample output from an MKV and VOB affected by this issue...

[mpv_mkv_output.txt](https://github.com/mpv-player/mpv/files/249771/mpv_mkv_output.txt)
[mpv_vob_output.txt](https://github.com/mpv-player/mpv/files/249772/mpv_vob_output.txt)

I checked the changelog to see if I missed a setting change or removal of support for these formats, but found nothing obvious. Please advise, thank you for your time.

P.S. VLC displays both graphic and text-based subtitles --on same system with the same files-- correctly.

> $ zgrep mpv /var/log/dnf.log*gz
/var/log/dnf.log-20160424.gz:Apr 19 13:24:10 DEBUG ---> Package mpv.x86_64 0.16.0-1.fc23 will be upgraded
/var/log/dnf.log-20160424.gz:Apr 19 13:24:10 DEBUG ---> Package mpv.x86_64 0.17.0-1.fc23 will be an upgrade

**Comment by wm4** [comment]
Works for me. Possibly a problem with the ancient ffmpeg version you're using.

**Comment by optimiz** [comment]
Thank you for the quick response.  Following your advice, I tested ffplay (to rule out the ffmpeg v2.8.6 libs) using the same system and files as before and it displays the subtitles from both MKV and VOB correctly.  I'll downgrade mpv back to v0.16 to work around the incompatibility.  Thanks again for the hint, it's much appreciated.

![ffplay_2016-05-05_08-03-34](https://cloud.githubusercontent.com/assets/8029862/15047816/851ab344-129b-11e6-87bf-dfdd835ec5fb.jpg)

**Comment by wm4** [comment]
What the fuck?

**Comment by Coacher** [comment]
I have the same problem on Gentoo with mpv-0.17.0 and latest mpv from git @ da0bf27.
I've done a bisect run between 0.16.0 and 0.17.0. Here's the result:
```
$ git bisect log
git bisect start
# good: [9d2980dab752280468620df49cabe7f4843f0551] Release 0.16.0
git bisect good 9d2980dab752280468620df49cabe7f4843f0551
# bad: [0536841647ef7931bffb4386d8ffbb5b2b568e8a] Release 0.17.0
git bisect bad 0536841647ef7931bffb4386d8ffbb5b2b568e8a
# good: [3353923f2906368fb4d0b1fc0927f9f8fce30cf8] vo_opengl: GLX: try to create 3.3 core profile context
git bisect good 3353923f2906368fb4d0b1fc0927f9f8fce30cf8
# good: [3984d2acca22465f8cbe7276134c1be1963af4fb] player: hide cache in status line by default again
git bisect good 3984d2acca22465f8cbe7276134c1be1963af4fb
# bad: [c0e13d54a85663ff8ac87d2910f1688978ea1f60] aspect: make video-zoom logarithmic
git bisect bad c0e13d54a85663ff8ac87d2910f1688978ea1f60
# good: [0d746522325923ff5926f3a3cd0024b679a8199f] build: fix AVCodecParameters FFmpeg API check
git bisect good 0d746522325923ff5926f3a3cd0024b679a8199f
# bad: [7089175d8d45d7c75621e56d2a3623fe02e38960] sd_lavc: use decoder-reordered PTS for PGS
git bisect bad 7089175d8d45d7c75621e56d2a3623fe02e38960
# good: [64791a08323f392ace49228b6794d442a41fd71b] ao_coreaudio_exclusive: add missing newline to log message
git bisect good 64791a08323f392ace49228b6794d442a41fd71b
# good: [eb740673b8a110f5d18879ba0080e9d3f13387d0] sd_lavc: add a comment about duration==0 handling
git bisect good eb740673b8a110f5d18879ba0080e9d3f13387d0
# first bad commit: [7089175d8d45d7c75621e56d2a3623fe02e38960] sd_lavc: use decoder-reordered PTS for PGS
```
I can confirm that if I build mpv from git @ da0bf27 with a patch that reverts 7089175, then this problem is not reproducible anymore.

My ffmpeg version is 2.8.7.

Gentoo bugreport: https://bugs.gentoo.org/show_bug.cgi?id=582384

Please fix.

**Comment by wm4** [comment]
It's because ffmpeg git and 3.x have a certain bug fix that is not in 2.8.7.

Gentoo should stop using badly maintained and unstable old ffmpeg releases.

**Comment by Coacher** [comment]
Gentoo moves towards ffmpeg-3.
Sadly many packages still fail to build against ffmpeg-3: https://bugs.gentoo.org/show_bug.cgi?id=ffmpeg-3

**Comment by Coacher** [comment]
Thank you very much for fixing this problem.

**Comment by wm4** [comment]
> Sadly many packages still fail to build against ffmpeg-3:

Your own fault for making your live harder by trying to use a single ffmpeg release for all packages.

**Comment by haasn** [comment]
> Please fix.

```
echo '<media-video/ffmpeg-4' >> /etc/portage/package.unmask
```

That will remove the stupid Gentoo mask on ffmpeg 3. I don't know why they would prefer to mask the entire ffmpeg package rather than just put it as a blocking dependency on the packages that break instead.
