### ISSUE TITLE
Can mpv show the CPU, GPU, RAM usage and frame drops information on the video?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#3110]
Can it show the CPU, GPU, RAM and frame drops information like MPC or PotPlayer?
So that we don't need to switch the window to terminal.

**Comment by kevmitch** [comment]
see [mpv-stats](https://github.com/Argon-/mpv-stats)

**Comment by laichiaheng** [comment]
Will you put this function in MPV? It is useful!

**Comment by wm4** [comment]
Probably not.
