### ISSUE TITLE
utf16?

### ISSUE THREAD

**Issue by rezad1393** [mpv-player/mpv#3112]
I recently discovered that many of my new subtitles that I download are not in utf8 encoding but in utf-16
mpv doesn't show these subtitles and I have to convert to utf8
vlc does show them but I like mpv better.
Is there a way to fix this ?

**Comment by wm4** [comment]
It normally supports utf-16 out of the box. Maybe an old ffmpeg version?

**Comment by rezad1393** [comment]
mpv on archlinux. so no I dont think so.
ffmpeg 1:3.0.2-1

**Comment by wm4** [comment]
Then either your build is broken, or you force a charset, or it hates you. I can't guess for you.

**Comment by richardpl** [comment]
Could you upload one such utf16 subtitle somewhere?

**Comment by rezad1393** [comment]
yes 

[link](https://mega.nz/#!T4VBgDiT!rlon5kTYb1D1Ewbo5mz4H8JiTEzvvB5uUo3UxCjBHHs)

**Comment by wm4** [comment]
Works here.

**Comment by ArchangeGabriel** [comment]
Works for me too on ArchLinux, with both mpv from community and mpv-light from aur.

**Comment by rezad1393** [comment]
then why it doesnt for me?

**Comment by wm4** [comment]
How should I know?

**Comment by rezad1393** [comment]
is there a debug option or verbose option so that I see what is causing this?
the subtitle that is converted to utf8 works on the same instance of mpv by switching to it but the utf16 doesnt and in terminal there are no errors or warning about that.

**Comment by wm4** [comment]
Run with -v. This is on the link that is shown when opening an issue on this repo.

**Comment by rezad1393** [comment]
sorry. you are right.
I dont see any error in the terminal output.
could this be a font problem?

**Comment by wm4** [comment]
If it works with utf-8, then absolutely not.

**Comment by lachs0r** [comment]
You were supposed to paste the `-v` output. If you can’t spot any errors, that doesn’t mean there aren’t any clues as to what’s causing the problem.
