### ISSUE TITLE
Watching a file that's saving from a stream shows double negative time remaining

### ISSUE THREAD

**Issue by joshka** [mpv-player/mpv#3114]
I'm watching a live stream that [Livestreamer](http://livestreamer.io) is saving to disk underneath mpv. For clarity, the file is continuously being appended to.

Say I start watching 30 seconds after starting Livestreamer. The time remaining starts `-00:00:30` as this is the length of the file. 30 seconds later we get to `-00:00:01` and then `--00:00:01`. Note the double negative here is because we've passed the point where the file originally ends.

I think that what probably makes more sense  is to update when the file size changes, so `-00:00:01` is always 1 second from the end of file, rather than 1 second from the end of file that existed when the file was opened.

This would be useful in particular where we hit the end of the streamed buffer and mpv pauses (i.e. I've specified `--keep-open`). Instead of the screen not updating, we'd see the remaining time increasing and showing the amount of buffered file.

**Comment by wm4** [comment]
Not worth the trouble, especially the last point.

**Comment by ChrisK2** [comment]
I'll eventually just make the OSC not show the duration when it's becoming invalid.

**Comment by johnoneil** [comment]
I'm also seeing this issue watching a recorded mpeg2ts, so it may be a bit more common than the above case.
Initial play start time begins at about 26:00:00 and time remaining counts down from (double negative)--24:21:40.
Will check a little further and see if there's something I can add.

**Comment by joshka** [comment]
I understand you don't think this feature request is worth the effort. I wonder if you could perhaps provide a quick high level overview of what would be required to make this work?

I can see that we'd need to recompute the muxer's time likely here: https://github.com/mpv-player/mpv/blob/768448305292f50c72533597c25992b70e8e42ac/demux/demux_lavf.c#L1009

**Comment by wm4** [comment]
libavformat can't update the file duration.

The double negative is probably added by osc.lua.
