### ISSUE TITLE
Support for language named subtitle files

### ISSUE THREAD

**Issue by John-Gee** [mpv-player/mpv#3115]
Hello,

I would like mpv to autoload subtitles that have the language appended to the name.

Currently, if I have:
A.mkv
A.srt
mpv will load the mkv and srt together.

But not in this case:
A.mkv
A.en.srt

Am I missing something to configure?
If not I believe it would be of great help.

Thank you!

**Comment by wiiaboo** [comment]
`--sub-auto=fuzzy` and make sure "en" is in the list of `slang`.

**Comment by John-Gee** [comment]
Awesome, thank you for the quick reply!
