### ISSUE TITLE
mpv through ssh

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#3118]
Hi,

If I run mpv (0.17) through ssh (in gnome-terminal) on a video located on a Ubuntu machine connect to my plasma TV, the X11 server on my ssh client displays the video (which is expected) but there is no audio.

The alsa driver is used.

If I run mpv through ssh (on the console: tty1) on a video located on a Ubuntu machine connect to my plasma TV, mpv says : 

Error opening/initializing the selected video_out (-vo) device.
Video: no video

But if I use "-vo null", the audio get played on the plasma TV

So I can get either the video or the audio but not both :(

Can you help ?

**Comment by VirulentVir** [comment]
why don't you use ffserver to serve the file and run mpv locally?

**Comment by lachs0r** [comment]
Or, in fact, just use sftp:// (needs FFmpeg built with libssh support)?

**Comment by lachs0r** [comment]
Also, remember setting `DISPLAY`.

**Comment by lachs0r** [comment]
I’m not even sure I understood your scenario correctly.
Do you want to:
a) Log in to a machine via SSH, then run mpv there on the display that is attached to said machine? Set the `DISPLAY` environment variable to the appropriate X11 display (e.g. `DISPLAY=:0 mpv file.mkv`).
b) Run mpv on a machine and play some remote media? In that case you just have to use pubkey ssh auth (see `ssh-copy-id`) and point mpv to a valid sftp URL, e.g. `sftp://user@host/path/to/file`

**Comment by sebma** [comment]
@lachs0r Actually I didn't even know myself, lol !

Both answers are fine for me because I wanted to do both.

I should have posted to questions.

Thanks a lot, man.
