### ISSUE TITLE
shift+pgup / shift+pgdwn don’t work with audio

### ISSUE THREAD

**Issue by ousia** [mpv-player/mpv#3121]
According to `mpv.rst`, seeking forward and backward by 10 minutes is performed when pressing _Shift+PGUP_ and _Shift+PGDWN_.

Well, I don’t know why, but this doesn’t work with latest release on Fedora 23.

Version numbers are:

```
mpv --version
mpv 0.17.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.6
```

Is this a bug or am I missing something?

Many thanks for your help.

**Comment by wm4** [comment]
Are you trying this on the terminal? Try --force-window.

**Comment by haasn** [comment]
Many terminals (rxvt at least) will interpret shift+pageup/down as “scroll the terminal up/down” instead. The application never sees it.

In general, detecting something like shift+pageup from the terminal is basically impossible either way.

**Comment by ousia** [comment]
@wm4 & @haasn,

`--force-window` works, but would it be possible to enable _PageUp_ and _PageDown_ to seek forward or backward by 10 minutes?

I guess this might make sense, since (as far as I know) audio contains no chapters.

Many thanks for your help again.

**Comment by wm4** [comment]
Just create an input.conf with the appropriate mappings: https://mpv.io/manual/master/#input-conf

**Comment by fbriere** [comment]
To anyone who ended up here after a bit of Googling (like I did): Thanks to the awesomeness of mpv, it's quite easy to create a script that will apply key bindings specifically for audio files.  That way, you can remap `Page Up/Down` to seek 10 min. for audio files, and still use them to switch chapters for video files.

Here's [my own take](https://github.com/fbriere/mpv-scripts/blob/master/scripts/audio-file-keys.lua) at this; hope it can be useful to other people as well.
