### ISSUE TITLE
(DebianWheezy-7.9 -latest MPV-Build) - Washed Out Colors in new Mpv-Build on DebianWheezy

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#3124]
Hello ,

i found out that new MPV_Build apparently breaks something in color management as the videos played .

used this "script" here

sudo aptitude install autoconf  automake  libasound2-dev libegl1-mesa-dev  libfontconfig-dev  libfreetype6-dev  libfribidi-dev libgl1-mesa-dev libgnutls-dev libtool libx11-dev libxext-dev libxinerama-dev libxrandr-dev  libxv-dev  pkg-config python  x11proto-core-dev yasm
./update
./clean
cd libass
git checkout 9a2b38e8f5957418362e86b525f72794565deedd
cd ..
./build -j2

before it used to work but something must have changed in the mpv-build git collection as i am no more able to  compile without getting distorted images afterwards.

when i play video this is the message

[vo/opengl] Could not create EGL context!

thank you all
![bildschirmfoto vom 2016-05-09 21 20 25](https://cloud.githubusercontent.com/assets/12947465/15125440/226fe42c-162d-11e6-9482-5fa6eeb41247.png)
![bildschirmfoto vom 2016-05-09 21 20 28](https://cloud.githubusercontent.com/assets/12947465/15125439/226fb7e0-162d-11e6-8806-f156785c62b7.png)
![bildschirmfoto vom 2016-05-09 21 20 38](https://cloud.githubusercontent.com/assets/12947465/15125441/22734cd4-162d-11e6-9c85-fdae36737d66.png)

**Comment by wm4** [comment]
Post mpv log with -v.

**Comment by mrkapqa** [comment]
[cplayer] Command line options: '-v'
[cplayer] mpv 0.17.0-git-0536841 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Mon May  9 20:45:13 CEST 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.17.103
[cplayer]    libavcodec      57.24.102
[cplayer]    libavformat     57.25.100
[cplayer]    libswscale      4.0.100
[cplayer]    libavfilter     6.31.100
[cplayer]    libswresample   2.0.101
[cplayer] ffmpeg version: n3.0.2
[cplayer] 
[cplayer] Configuration: ./waf configure
[cplayer] List of enabled features: alsa any-gl asm atomic-builtins atomics audio-input av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-profile-name avframe-metadata avframe-skip-samples build-date cplayer debug-build dlopen drm dvbin egl-helpers egl-x11 fchmod gl gl-x11 glibc-thread-name glob iconv libass libass-osd libav libavdevice libavfilter libdl libm librt libswresample linux-fstatfs nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads resampler shm standard-gl subprocess termios tv tv-v4l2 videodev vt.h x11 xext xinerama xrandr xv zlib
[global] config path: '' -> '/home/richie/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/home/richie/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/richie/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/home/richie/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/richie/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/etc/mpv/config'
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] mpv 0.17.0-git-0536841 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Mon May  9 20:45:13 CEST 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.17.103
[cplayer]    libavcodec      57.24.102
[cplayer]    libavformat     57.25.100
[cplayer]    libswscale      4.0.100
[cplayer]    libavfilter     6.31.100
[cplayer]    libswresample   2.0.101
[cplayer] ffmpeg version: n3.0.2
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]

**Comment by wm4** [comment]
With playback.

**Comment by mrkapqa** [comment]
richie@debian:~/Downloads$ mpv -v Pressure\ Busspipe\ -\ Crazy\ Love\ \(Official\ HD\ Video\).mp4 
[cplayer] Command line options: '-v' 'Pressure Busspipe - Crazy Love (Official HD Video).mp4'
[cplayer] mpv 0.17.0-git-0536841 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Mon May  9 20:45:13 CEST 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.17.103
[cplayer]    libavcodec      57.24.102
[cplayer]    libavformat     57.25.100
[cplayer]    libswscale      4.0.100
[cplayer]    libavfilter     6.31.100
[cplayer]    libswresample   2.0.101
[cplayer] ffmpeg version: n3.0.2
[cplayer] 
[cplayer] Configuration: ./waf configure
[cplayer] List of enabled features: alsa any-gl asm atomic-builtins atomics audio-input av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-profile-name avframe-metadata avframe-skip-samples build-date cplayer debug-build dlopen drm dvbin egl-helpers egl-x11 fchmod gl gl-x11 glibc-thread-name glob iconv libass libass-osd libav libavdevice libavfilter libdl libm librt libswresample linux-fstatfs nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads resampler shm standard-gl subprocess termios tv tv-v4l2 videodev vt.h x11 xext xinerama xrandr xv zlib
[global] config path: '' -> '/home/richie/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/home/richie/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/richie/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/home/richie/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/richie/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/etc/mpv/config'
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -/-> '/home/richie/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/home/richie/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/etc/mpv/input.conf'
[input] Falling back on default (hardcoded) input config
[global] config path: 'scripts' -/-> '/home/richie/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/home/richie/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[global] config path: 'watch_later' -> '/home/richie/.config/mpv/watch_later'
[cplayer] Playing: Pressure Busspipe - Crazy Love (Official HD Video).mp4
[file] Opening Pressure Busspipe - Crazy Love (Official HD Video).mp4
[file] Stream opened successfully.
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[lavf] avformat_find_stream_info() finished after 98304 bytes.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[find_files] Loading external files in .
[global] config path: 'sub/' -/-> '/home/richie/.config/mpv/sub/'
[global] config path: 'sub/' -/-> '/home/richie/.mpv/sub/'
[global] config path: 'sub/' -/-> '/usr/local/etc/mpv/sub/'
[global] config path: 'audio/' -/-> '/home/richie/.config/mpv/audio/'
[global] config path: 'audio/' -/-> '/home/richie/.mpv/audio/'
[global] config path: 'audio/' -/-> '/usr/local/etc/mpv/audio/'
[cplayer]  (+) Video --vid=1 (*) (h264)
[cplayer]  (+) Audio --aid=1 --alang=und (*) (aac)
[vo/opengl] Initializing OpenGL backend 'x11probe'
[vo/opengl/x11] X11 opening display: :0
[vo/opengl/x11] X11 running at 1024x768 (":0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Display 0 (LVDS-1): [0, 0, 1024, 768] @ 60.003840 FPS
[vo/opengl/x11] Current display FPS: 60.003840
[vo/opengl] GLX chose FB config with ID 0xf05e56f0
[vo/opengl] GLX chose visual with ID 0x1de
[vo/opengl] Creating OpenGL 3.3 context...
[vo/opengl] Creating OpenGL 3.2 context...
[vo/opengl] Creating OpenGL 3.1 context...
[vo/opengl] Creating OpenGL 3.0 context...
[vo/opengl] Creating OpenGL 2.1 context...
[vo/opengl] GL_VERSION='2.1 Mesa 8.0.5'
[vo/opengl] Detected desktop OpenGL 2.1.
[vo/opengl] GL_VENDOR='nouveau'
[vo/opengl] GL_RENDERER='Gallium 0.4 on NV86'
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='1.20'
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 110/GL_EXT_unpack_subimage.
[vo/opengl] Loaded functions for 300/GL_ARB_framebuffer_object.
[vo/opengl] Loaded functions for 300/GL_ARB_vertex_array_object.
[vo/opengl] Loaded functions for 300/GL_ARB_texture_rg.
[vo/opengl] Loaded functions for 320/GL_ARB_sync.
[vo/opengl] Loaded functions for 0/GLX_SGI_swap_control.
[vo/opengl] Loaded functions for 0/GLX_SGI_video_sync.
[vo/opengl] Filterable half-float textures supported.
[vo/opengl] No vdpau support found - probing more things.
[vo/opengl/x11] uninit ...
[vo/opengl] Initializing OpenGL backend 'x11egl'
[vo/opengl/x11] X11 opening display: :0
[vo/opengl/x11] X11 running at 1024x768 (":0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Display 0 (LVDS-1): [0, 0, 1024, 768] @ 60.003840 FPS
[vo/opengl/x11] Current display FPS: 60.003840
[vo/opengl] Could not create EGL context!
[vo/opengl/x11] uninit ...
[vo/opengl] Initializing OpenGL backend 'x11'
[vo/opengl/x11] X11 opening display: :0
[vo/opengl/x11] X11 running at 1024x768 (":0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Display 0 (LVDS-1): [0, 0, 1024, 768] @ 60.003840 FPS
[vo/opengl/x11] Current display FPS: 60.003840
[vo/opengl] GLX chose FB config with ID 0xf056a0a0
[vo/opengl] GLX chose visual with ID 0x1de
[vo/opengl] Creating OpenGL 3.3 context...
[vo/opengl] Creating OpenGL 3.2 context...
[vo/opengl] Creating OpenGL 3.1 context...
[vo/opengl] Creating OpenGL 3.0 context...
[vo/opengl] Creating OpenGL 2.1 context...
[vo/opengl] GL_VERSION='2.1 Mesa 8.0.5'
[vo/opengl] Detected desktop OpenGL 2.1.
[vo/opengl] GL_VENDOR='nouveau'
[vo/opengl] GL_RENDERER='Gallium 0.4 on NV86'
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='1.20'
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 210/builtin.
[vo/opengl] Loaded functions for 110/GL_EXT_unpack_subimage.
[vo/opengl] Loaded functions for 300/GL_ARB_framebuffer_object.
[vo/opengl] Loaded functions for 300/GL_ARB_vertex_array_object.
[vo/opengl] Loaded functions for 300/GL_ARB_texture_rg.
[vo/opengl] Loaded functions for 320/GL_ARB_sync.
[vo/opengl] Loaded functions for 0/GLX_SGI_swap_control.
[vo/opengl] Loaded functions for 0/GLX_SGI_video_sync.
[vo/opengl] Filterable half-float textures supported.
[vo/opengl] Reported display depth: R=8, G=8, B=8
[vo/opengl] 16 bit texture depth: 16.
[vo/opengl] Testing user-set FBO format (0x805b)
[vo/opengl] Create FBO: 16x16 -> 16x16
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Assuming 60.003840 FPS for display sync.
[vd] Container reported FPS: 25.000000
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd] Opening video decoder lavc:h264
[vd] Using software decoding.
[vd] Detected 2 logical cores.
[vd] Requesting 3 threads for decoding.
[vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
[vo/opengl/x11] Disabling screensaver.
[vo/opengl/x11] Setting DMPS: off.
[ad] Codec list:
[ad]     lavc:aac - AAC (Advanced Audio Coding)
[ad]     lavc:aac_fixed (aac) - AAC (Advanced Audio Coding)
[ad] Opening audio decoder lavc:aac
[ad] Requesting 1 threads for decoding.
[ad] Selected audio codec: AAC (Advanced Audio Coding) [lavc:aac]
[cplayer] Starting playback...
[af] Audio filter chain:
[af]   [in] 44100Hz stereo 2ch floatp
[af]   [out] 44100Hz stereo 2ch floatp
[af]   [ao] 44100Hz stereo 2ch floatp
[ao] Trying audio driver 'alsa'
[ao/alsa] requested format: 44100 Hz, stereo channels, floatp
[ao/alsa] using ALSA version: 1.0.25
[ao/alsa] opening device 'default'
[ao/alsa] trying format float
[ao/alsa] hw pausing supported: yes
[ao/alsa] buffersize: 11025 samples
[ao/alsa] period size: 689 samples
[ao/alsa] device buffer: 11024 samples.
[ao/alsa] using soft-buffer of 11024 samples.
[cplayer] AO: [alsa] 44100Hz stereo 2ch float
[cplayer] AO: Description: ALSA audio output
[af] Adding filter lavrresample 
[af] Audio filter chain:
[af]   [in] 44100Hz stereo 2ch floatp
[af]   [lavrresample] 44100Hz stereo 2ch float
[af]   [out] 44100Hz stereo 2ch float
[af]   [ao] 44100Hz stereo 2ch float
[vd] Decoder format: 1280x720 yuv420p auto/auto CL=mpeg2/4/h264
[vf] Video filter chain:
[vf]   [in] 1280x720 yuv420p bt.709/limited CL=mpeg2/4/h264
[vf]   [out] 1280x720 yuv420p bt.709/limited CL=mpeg2/4/h264
[cplayer] VO: [opengl] 1280x720 yuv420p
[cplayer] VO: Description: Extended OpenGL Renderer
[vo/opengl/x11] not waiting for MapNotify
[vo/opengl] Resize: 1022x708
[vo/opengl] Window size: 1022x708
[vo/opengl] Video source: 1280x720 (1:1)
[vo/opengl] Video display: (0, 0) 1280x720 -> (0, 67) 1022x574
[vo/opengl] Video scale: 0.798438/0.797222
[vo/opengl] OSD borders: l=0 t=67 r=0 b=67
[vo/opengl] Video borders: l=0 t=67 r=0 b=67
[vo/opengl] Testing user-set FBO format (0x805b)
[vo/opengl] Create FBO: 16x16 -> 16x16
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Texture for plane 0: 1280x720
[vo/opengl] Texture for plane 1: 640x360
[vo/opengl] Texture for plane 2: 640x360
[vo/opengl] Reinit rendering.
[cplayer] set video colors output-levels=0 
[vo/opengl] recompiling a shader program:
[vo/opengl] [  1] color.r = 1.000000 * vec4(texture(texture0, texcoord0)).r;
[vo/opengl] [  2] color.g = 1.000000 * vec4(texture(texture1, texcoord1)).r;
[vo/opengl] [  3] color.b = 1.000000 * vec4(texture(texture2, texcoord2)).r;
[vo/opengl] [  4] // color conversion
[vo/opengl] [  5] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[vo/opengl] [  6] color.a = 1.0;
[vo/opengl] [  7] // color management
[cplayer] first video frame after restart shown
[cplayer] playback restart complete
[vo/opengl] Resize: 1024x709
[vo/opengl] Window size: 1024x709
[statusline] AV: 00:00:00 / 00:03:28 (0%) A-V:  0.000
[vo/opengl] Video source: 1280x720 (1:1)
[vo/opengl] Video display: (0, 0) 1280x720 -> (0, 66) 1024x576
[vo/opengl] Video scale: 0.800000/0.800000
[vo/opengl] OSD borders: l=0 t=66 r=0 b=67
[vo/opengl] Video borders: l=0 t=66 r=0 b=67
[statusline] AV: 00:00:00 / 00:03:28 (0%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:00 / 00:03:28 (0%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:00 / 00:03:28 (0%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:00 / 00:03:28 (0%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:00 / 00:03:28 (0%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:00 / 00:03:28 (0%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:00 / 00:03:28 (0%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:37 / 00:03:28 (18%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:37 / 00:03:28 (18%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:37 / 00:03:28 (18%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:37 / 00:03:28 (18%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:37 / 00:03:28 (18%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:37 / 00:03:28 (18%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:37 / 00:03:28 (18%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:37 / 00:03:28 (18%) A-V:  0.000
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:00:37 / 00:03:28 (18%) A-V:  0.000
[cplayer] Run command:

**Comment by mrkapqa** [comment]
both machines that had problems with debian wheezy have nvidian graphic cards - one quadro 140m , the other a smaller i think

**Comment by mrkapqa** [comment]
but, on the one with quadro 140m, i sucessfully compiled mpv on debian wheezy half a year ago without any problems ... but something must have changed in the meantime :)

**Comment by mrkapqa** [comment]
[cplayer] Run command: ignore, flags=9, args=[]
[cplayer] Run command: ignore, flags=9, args=[]
[statusline] AV: 00:03:26 / 00:03:28 (99%) A-V:  0.000
[lavf] EOF reached.
[statusline] AV: 00:03:28 / 00:03:28 (99%) A-V:  0.000
[cplayer] EOF code: 1  
[ad] Uninit audio decoder.
[af] Removing filter lavrresample 
[vd] Uninit video.
[cplayer] finished playback, success (reason 0)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (End of file)
[ao/alsa] draining...
[vo/opengl/x11] Enabling screensaver.
[vo/opengl/x11] Setting DMPS: on.
[vo/opengl/x11] uninit ...

**Comment by wm4** [comment]
I see nothing unusual here, and I'm inclined to blame your drivers.

Maybe you could create an apitrace trace? (https://apitrace.github.io/)

**Comment by mrkapqa** [comment]
thank you i will try to install approriate nvidia-drivers



Am 09/05/16 um 23:16 schrieb V. Lang:

**Comment by mrkapqa** [comment]
thank you, i was able to solve it by installing correct video driver  
for my Lenovo T61
http://www.thinkwiki.org/wiki/Installing_Debian_Wheezy_on_a_ThinkPad_T61



Zitat von "V. Lang" <notifications@github.com>:

**Comment by wm4** [comment]
What driver did you use before?

**Comment by mrkapqa** [comment]
i don#t know , just installed wheezy fresh from dvd1-amd64 , and quite 
afterwards installed mpv

it used to work before withouth having to install drivers

just used his instructions that he posted on his prior website

https://nyxi.eu/compiling-mpv-on-debian.html#compiling-mpv-on-debian


but a half year ago something changed  and i could no more install mpv 
on wheezy as i was used to before.
got error - harfbuzz not installed and fontconfig error


so after asking here i got this updated helper

|sudo aptitude install autoconf automake libasound2-dev libegl1-mesa-dev 
libfontconfig-dev libfreetype6-dev libfribidi-dev libgl1-mesa-dev 
libgnutls-dev libtool libx11-dev libxext-dev libxinerama-dev 
libxrandr-dev libxv-dev pkg-config python x11proto-core-dev yasm 
./update ./clean cd libass git checkout 
9a2b38e8f5957418362e86b525f72794565deedd cd .. ./build -j2 which worked 
for installing Mpv on Wheezy , but on some machines i got this 
Color-Washed-Out issue, which apparently it must be a driver thing 
connected with this building process. will continue using Wheezy for 
some time so in case in run in trouble again, i'll let youknow. thanks |





Am 10/05/16 um 13:15 schrieb V. Lang:

**Comment by wm4** [comment]
Maybe it was using nouveau then. These drivers tend to be very unstable and incomplete, so that could explain it.
