### ISSUE TITLE
Audio Boost

### ISSUE THREAD

**Issue by zQueal** [mpv-player/mpv#3127]
Unlike many of you, I'm sure, I have a very difficult time hearing. 

I found `--volume` but it no longer seems to do what I want.

    This was changed after the mpv 0.9 release. Before that, 100 actually meant maximum volume. At the same time, the volume scale was made cubic, so the old values won't match up with the new ones anyway.

Additionally I've tried `--softvol-max=1000` but I don't hear any noticeable volume boost. Playing the same media file in any other player at `150%` boost I can hear the same audio just fine.

Anyone have any advice?

**Comment by lachs0r** [comment]
This depends on your audio output. Softvol is not used by default for audio outputs with native support for per-application volume control.

Also, you should give `--af=drc` a try.

**Comment by zQueal** [comment]
> This depends on your audio output.

It seems like I'm using wasapi.

I'm afraid all this stuff is a bit foreign to me. I tried adding `af=drc` to my `mpv.conf` but by itself it does nothing. I assume you mean to use it in tandom with a [bunch of these options](https://mpv.io/manual/stable/#audio-filters-drc[).

__EDIT:__ I have no idea what it's doing but adding `af=drc:2` to my `mpv.conf` seems to be doing something. I can hear it a little better, but I'd still like to be able to squeeze out an additional 50% or so.

**Comment by lachs0r** [comment]
Increase the target amplitude then.

**Comment by sda89ha9** [comment]
softvol has to be enabled - mpv.conf
softvol=yes
softvol-max=200
or try this
af=lavfi=[acompressor=6]

**Comment by zQueal** [comment]
Thanks for the guidance, lachs!

sda, this worked perfectly! I can hear just fine now. Thanks for all the help!
