### ISSUE TITLE
Some input options do not apply to player window (stdin/XEvent issue).

### ISSUE THREAD

**Issue by loimu** [mpv-player/mpv#3131]
Some input options do not apply to player window.
For example input.conf options below

    AXIS_UP    add volume +2
    AXIS_DOWN  add volume -2

are working only through stdin but not for player window.

Platform: Linux, X11.
Reproducible: always.

**Comment by wm4** [comment]
If you mean the mouse wheel, they are handled as buttons. The AXIS events are available on wayland and osx only.

**Comment by loimu** [comment]
It's not hard to implement this for X.

**Comment by wm4** [comment]
Feel free to do so.
