### ISSUE TITLE
Static linking ANGLE no longer work

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#3133]
previously, customize mpv to search pkg-config for ANGLE works. But now I seem cannot do it anymore

**Comment by wm4** [comment]
It's always LoadLibrary'd now.

**Comment by shinchiro** [comment]
In that commit's message, it said compatible with ANGLE linked at build-time. Am I missed something?

**Comment by wm4** [comment]
Only on the source code level. You could patch out the angle_load calls and the angle_dynamic.h includes, change the wscript back to use pkg-conf, and you'd get the old behavior.

**Comment by shinchiro** [comment]
ok got it
