### ISSUE TITLE
-shuffle fails with directories

### ISSUE THREAD

**Issue by gordallott** [mpv-player/mpv#3134]
using 0.17.0 on osx

--shuffle is supposed to play files in a random order, when you specify directories instead of files --shuffle will shuffle the order of directories but then add the files in the directories sequentially 

this means that if you have say five directories full of video files, - say you order tv shows into seasons, you can't play random episodes from the entire run, only random episodes from one season that mpv randomly chooses until the 1/24 chance that mpv selects another directory comes up

mpv should probably expand all the directories in the playlist before selecting a file to play

**Comment by wm4** [comment]
Was changed ages ago in git.

**Comment by gordallott** [comment]
Tested with latest git and this issue is still reproducable, has not been fixed behaviour is exactly the same as described in the issue.

tested with
```
⇒  mpv --version
mpv git-8ff96f0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Tue May 24 17:40:20 BST 2016
ffmpeg library versions:
   libavutil       55.17.103
   libavcodec      57.24.102
   libavformat     57.25.100
   libswscale      4.0.100
   libavfilter     6.31.100
   libswresample   2.0.101
ffmpeg version: 3.0.2
```

**Comment by wm4** [comment]
Are you passing multiple directories at the same time?

That's a WONTFIX, I'm afraid.

**Comment by wm4** [comment]
(Although I'd be open for suggestions how to fix it.)

**Comment by gordallott** [comment]
yeah multiple directories at the same time, basically `mpv --shuffle *` - sucks if it's a wontfix but I can work with the existing behaviour, thanks for the reply
