### ISSUE TITLE
Per-audio-device profiles?

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [mpv-player/mpv#3136]
There is no way to control the hardware device used with `no-softvol` on a per-`audio-device` basis.

This leaves the deprecated `ao`'s suboptions as the only way to get robust audio device settings.

For example, ideally this configuration would be valid:

````
# mpv.conf
[audio-device.alsa/front:CARD=Live]
no-softvol
ao-defaults=alsa:mixer-device=[hw:CARD=Live]:mixer-name=Front

[audio-device.alsa/rear:CARD=Live]
no-softvol
ao-defaults=alsa:ignore-chmap=:mixer-device=[hw:CARD=Live]:mixer-name=Surround

[audio-device.alsa/hw:CARD=ICH7]
no-softvol
ao-defaults=alsa:mixer-device=[hw:CARD=ICH7]:mixer-name=PCM
````

````
# input.conf
A cycle_values audio-device alsa/rear:CARD=Live alsa/front:CARD=Live alsa/hw:CARD=ICH7
````

Pressing Shift+A would cycle through the configured audio devices, and use the appropriate hardware volume controls for each one.

However, with neither `ao` nor `current-ao` being writable by `cycle_values`, even this workaround is broken:
````
A cycle_values current-ao alsa:device=[rear:CARD=Live]:ignore-chmap=:mixer-device=[hw:CARD=Live]:mixer-name=Surround alsa:device=[front:CARD=Live]:mixer-device=[hw:CARD=Live]:mixer-name=Front alsa:device=[hw:CARD=ICH7]:mixer-device=[hw:CARD=ICH7]:mixer-name=PCM
````

**Comment by wm4** [comment]
Not possible right now.

**Comment by JamesTheAwesomeDude** [comment]
Is there any way to be able to cycle bound-together sets of options? The below setup doesn't work due to `profile` not being selectable at runtime, but you see the intent

````
# mpv.conf
#ALSA hardware volume
[black-jack]
no-softvol
audio-device=alsa/rear:CARD=Live
ao-defaults=alsa:ignore-chmap=:mixer-device=[hw:CARD=Live]:mixer-name=Surround
[green-jack]
no-softvol
audio-device=alsa/front:CARD=Live
ao-defaults=alsa:mixer-device=[hw:CARD=Live]:mixer-name=Front
[integrated-audio]
audio-device=alsa/hw:CARD=ICH7
ao-defaults=alsa:mixer-device=[hw:CARD=ICH7]:mixer-name=PCM
````

````
# input.conf
A cycle-values profile black-jack green-jack integrated-audio
````

**Comment by wm4** [comment]
No.

**Comment by Hrxn** [comment]
If nothing else helps, try the old and trusted method of config switching scripts.
My usual approach of dealing with inflexible applications. ;-)

Use shell scripts to (de-)activate or set up your devices, or whatever else, and then exchange the appropriate `*.conf` files from that script, and then launch the application.

**Comment by JamesTheAwesomeDude** [comment]
@Hrxn That is an interesting idea, though I wonder if at that point it wouldn't be easier to code in proper device-switching support as a Lua plugin

**Comment by Hrxn** [comment]
Well, I personally think that automatic switching of config files and then running the app from that script is very easy, and it basically always works. Because it only relies on simple file system functionality.

But you're right about everything that depends on the app runtime, can't do anything externally here.
But you can use `vo-cmdline` to change some VO options during runtime, the manual does not mention `ao-cmdline`, but this may be a viable way to implement something like this.

**Comment by wm4** [comment]
I would question why mixer-channel has to be set in  the first place.

**Comment by JamesTheAwesomeDude** [comment]
@wm4 Because ALSA has no facility to autoselect the correct mixer name.

The only mixer controls that affect `rear:` are the EQ controls and `Surround`; `Master` and `PCM` do not affect it.

`Wave Surround` controls the amount of stereo audio sent to `hw:` which is pumped to the rear speakers.

**Comment by JamesTheAwesomeDude** [comment]
Also, this might be a separate issue, but when using hardware volume control, the percent reported by MPV seems to have no meaningful connection to the actual state of the mixer. It doesn't seem to be linked to the dB gain, and it is usually slightly different from the "percent" reported by alsamixer.

MPV reports the volume as "2%" in this situation, for some reason:

````
┌──────────────────────────── AlsaMixer v1.0.27.2 ─────────────────────────────┐
│ Card: SB Live! Value [CT4780]                        F1:  Help               │
│ Chip: Cirrus Logic CS4297A rev 4                     F2:  System information │
│ View: F3:[Playback] F4: Capture  F5: All             F6:  Select sound card  │
│ Item: Surround [dB gain: -39.60, -39.60]             Esc: Exit               │
│                                                                              │
│     ┌──┐              ┌──┐     ┌──┐     ┌──┐     ┌──┐     ┌──┐     ┌──┐      │
│     │  │              │  │     │▒▒│     │  │     │  │     │  │     │  │      │
│     │  │              │  │     │▒▒│     │  │     │  │     │  │     │  │      │
←     │  │              │  │     │▒▒│     │  │     │  │     │  │     │  │      →
←     │  │              │  │     │▒▒│     │  │     │  │     │  │     │  │      →
←     │  │              │  │     │▒▒│     │  │     │  │     │  │     │  │      →
←     │  │              │▒▒│     │▒▒│     │  │     │  │     │  │     │  │      →
←     │  │              │▒▒│     │▒▒│     │  │     │  │     │  │     │  │      →
←     │  │              │▒▒│     │▒▒│     │  │     │  │     │  │     │  │      →
←     │  │              │▒▒│     │▒▒│     │  │     │  │     │  │     │  │      →
│     │  │              │▒▒│     │▒▒│     │▒▒│     │  │     │  │     │  │      │
│     │  │              │▒▒│     │▒▒│     │▒▒│     │  │     │  │     │  │      │
│     └──┘     ┌──┐     ├──┤     └──┘     └──┘     └──┘     └──┘     └──┘      │
│              │MM│     │OO│                                                   │
│              └──┘     └──┘                                                   │
│      0               56<>56  100<>100  22<>22     0        0       0<>0      │
│   3D Contr 3D Contr   PCM     Front  <Surround> Center    LFE     Synth      │
└──────────────────────────────────────────────────────────────────────────────┘

````

Likewise, alsamixer's `51`/`-17.60dB ` is reported as "56%" by MPV.
