### ISSUE TITLE
Translate 'watch later' hashes to filepaths

### ISSUE THREAD

**Issue by jamietanna** [mpv-player/mpv#3138]
Is there any way that the hashes found in `$HOME/.config/mpv/watch_later` can be translated back into a filepath?

I have a number of entries, and it would be great if I could work out what they correspond to, so I can finish watching them.

Platform: Arch Linux x64
MPV version:

```
mpv 0.17.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Wed Apr 27 15:26:51 CEST 2016
ffmpeg library versions:
   libavutil       55.17.103
   libavcodec      57.24.102
   libavformat     57.25.100
   libswscale      4.0.100
   libavfilter     6.31.100
   libswresample   2.0.101
ffmpeg version: 3.0.2
```

**Comment by haasn** [comment]
Unless you had ``write-filename-in-watch-later-config`` enabled, there is no way. (Unless you want to do a brute force search on all the media files you have)

**Comment by jamietanna** [comment]
I did not, but thanks for letting me know about that config option. I'll enable that by default for now.
