### ISSUE TITLE
Support for playback of cached files

### ISSUE THREAD

**Issue by grepwood** [mpv-player/mpv#3140]
Hello,

I'm writing a game engine, so I can't have FILE \* with videos in them. Instead, the game engine works with .dat files that have internal structures which allow me to buffer entire files and do anything with them afterwards.

mpv is currently the only player that works for my use case. Previous players that I tried would either not work with latest FFmpeg APIs or have the SDL2 surface's refresh rate fixed, so only 25 fps videos play correctly.

I'd like to request a feature that allows to play files cached into a char pointer with a known size.

Best regards,
grep

**Comment by haasn** [comment]
How are you using mpv? As libmpv or are you running the mpv binary directly?

> I'm writing a game engine, so I can't have FILE * with videos in them.

Not strictly related but: why not? Couldn't you just split the .dat up into its constituent files?

**Comment by kevmitch** [comment]
#2630 might be of interest

**Comment by grepwood** [comment]
@haasn The .dat is proprietary. I can't modify it, but only extract relevant parts of it. I'm using a slightly modified version of the sdl example: https://gist.github.com/grepwood/05ba45b9ad535709b2159996aad2b6f6

**Comment by lachs0r** [comment]
stream_cb API.
