### ISSUE TITLE
How to change video quality on youtube?

### ISSUE THREAD

**Issue by 4815162342lost** [mpv-player/mpv#3141]
I do not understand, bad wiki. i want to change video quality. But how?

Stream (Eurovision 2016): mpv https://www.youtube.com/watch?v=no1v1-2HZ6g 

I try 
`mpv https://www.youtube.com/watch?v=no1v1-2HZ6g `
but get video on 144p.

I found `--ytdl-format=bestvideo+bestaudio` options and try it, but i get errors:
`[ytdl_hook] ERROR: requested format not available
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] tls: The TLS connection was non-properly terminated.
Failed to recognize file format.
Exiting... (Errors when loading file)`

Please, help me, how i can manage video quality? For example, i want to get 1080p videos with best audio.

**Comment by 4815162342lost** [comment]
And please, improve you wiki\FAQ. Add youtube video examples with different quality.

**Comment by 4815162342lost** [comment]
```
vodka@vodka-PC:/tmp/dist/livestreamer-1.12.2$   youtube-dl --list-formats  https://www.youtube.com/watch?v=no1v1-2HZ6g
[youtube] no1v1-2HZ6g: Downloading webpage
[youtube] no1v1-2HZ6g: Downloading video info webpage
[youtube] no1v1-2HZ6g: Extracting video information
[youtube] no1v1-2HZ6g: Downloading formats manifest
[youtube] no1v1-2HZ6g: Downloading MPD manifest
[info] Available formats for no1v1-2HZ6g:
format code  extension  resolution note
92           mp4        240p       HLS , h264, aac  @ 48k
93           mp4        360p       HLS , h264, aac  @128k
94           mp4        480p       HLS , h264, aac  @128k
95           mp4        720p       HLS , h264, aac  @256k
96           mp4        1080p      HLS , h264, aac  @256k
91           m3u8       unknown    (best)

```

**Comment by 4815162342lost** [comment]
OK, i found it:
` mpv https://www.youtube.com/watch?v=no1v1-2HZ6g --ytdl-format 96`

I am a little stupid, but you wiki too bad. man not bad, but please, improve you wiki and add more examples with --ytdl-format options on FAQ.

**Comment by wiiaboo** [comment]
That's a youtube-dl issue, not mpv's, btw. And --ytdl-format examples same, all depends on youtube-dl.
