### ISSUE TITLE
s16 audio distorted due to non-normalized downmix

### ISSUE THREAD

**Issue by foo86** [mpv-player/mpv#3142]
This [sample file](https://0x0.st/qN0.dts) sounds badly distorted after downmixing to stereo with libswresample. `--audio-normalize-downmix=yes` helps, as does `--af=lavrresample=o=[internal_sample_fmt=fltp]`. Looks like libswresample doesn't do any clipping unless doing floating point to integer conversion.

**Comment by wm4** [comment]
> Looks like libswresample doesn't do any clipping unless doing floating point to integer conversion.

Yes, I suspect that's what happens. This was actually noticed some time ago already, but the one who was supposed to test this disappeared:

https://github.com/mpv-player/mpv/commits/something

Can you test whether these 2 top commits fix it?

I think libavresample did not have this problem, but now that I'm looking at the libavresample code again, I'm not so sure.

**Comment by foo86** [comment]
> Can you test whether these 2 top commits fix it?

These work if I replace s->avrctx_out with s->avrctx, e.g.:

```
--- a/audio/filter/af_lavrresample.c
+++ b/audio/filter/af_lavrresample.c
@@ -330,7 +330,7 @@ static int configure_lavrr(struct af_instance *af, struct mp_audio *in,
         if (af_fmt_is_float(s->out_format) && af_fmt_to_bytes(s->out_format) > 4)
             sample_fmt = AV_SAMPLE_FMT_DBLP;
         MP_VERBOSE(af, "Forcing internal_sample_fmt=%d\n", sample_fmt);
-        av_opt_set_int(s->avrctx_out, "internal_sample_fmt", sample_fmt, 0);
+        av_opt_set_int(s->avrctx, "internal_sample_fmt", sample_fmt, 0);
     }
     av_opt_set_double(s->avrctx, "rematrix_maxval", normalize ? 1 : 1000, 0);
 #else
```

> I think libavresample did not have this problem, but now that I'm looking at the libavresample code again, I'm not so sure.

I didn't test with libavresample, but it seems it has proper [clipping](http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavresample/audio_mix.c;hb=HEAD#l119) in place for s16p case.

**Comment by wm4** [comment]
>These work if I replace s->avrctx_out with s->avrctx, e.g.:

Right, that seems to be an oversight. avrctx_out is supposed to use for reordering only.

**Comment by wm4** [comment]
Supposedly fixed with: http://git.videolan.org/?p=ffmpeg.git;a=blobdiff;f=libswresample/rematrix.c;h=f18c9f67db307c8066ed1c021309daaf4cd7332c;hp=932088ffb7dd442e0aa24cc0ab1fc466b1a56f6a;hb=7fe81bc4f8ba684626fa08f7bef46da3e8abe373;hpb=35c23bf67df62d8d6dbfca05e99d6d607c17f7bb

**Comment by foo86** [comment]
That doesn't make any difference when matrix is not normalized.

**Comment by wm4** [comment]
New attempt: http://git.videolan.org/?p=ffmpeg.git;a=commit;h=2f76157eb05bf63725f96167feda6b2e07501c7e

**Comment by foo86** [comment]
That fixed it. No workaround is needed in mpv, thus closing.
