### ISSUE TITLE
Will MPV have a snap package?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#3143]
If there is a snap package, we will be able to use the latest MPV on Ubuntu without adding PPA.

**Comment by wm4** [comment]
Only if someone makes one. We (the mpv developers) don't package stuff.

**Comment by mc4man** [comment]
You'll likely see it soon, up in github though likely not ready to install.
Also it may be be a bit deficient atm in it's configure though I'm sure they'll get it together at some point.

**Comment by joeky888** [comment]
Mpv is now on official flathub https://github.com/flathub/io.mpv.Mpv

```fish
$ flatpak install flathub io.mpv.Mpv
$ io.mpv.Mpv "VIDEO_LINK"
```
