### ISSUE TITLE
How to set the parameter "if" in ytdl-format?

### ISSUE THREAD

**Issue by romacode** [mpv-player/mpv#3146]
~/.mpv/config
```
ytdl-format=bestvideo[height<?1080]+bestaudio/best → video-unscaled=yes
ytdl-format=bestvideo[height=?1080]+bestaudio/best → video-unscaled=no
```

**Comment by Hrxn** [comment]
Not sure what you're trying to achieve, but you can't set something like this in `ytdl-format`, AFAIK.

**Comment by romacode** [comment]
Thanks for that added a new parameter.
`video-unscaled=downscale-big`
