### ISSUE TITLE
Symbol Lookup Error

### ISSUE THREAD

**Issue by CartridgeGen** [mpv-player/mpv#3147]
Hi! I've been compiling MPV for a while now with as always, SUCESS! Suddenly, I stomped on a video which looks like any other but infact causes MPV to crash on this line : 

mpv: symbol lookup error: /home/odroid/mpv/build/mpv: undefined symbol: ass_set_check_readorder

I've been maintaining this port on ARMHF for about 5 months now but I see there's some fixing to do.
This may be ARMHF problems that causes this, just like other problems I encountered in other programs that would normally work on a X86_X64 but acts differently on ARMHF even if the code is working. Do I have to add something like -fPIC or anything else to solve this problem?
I'm running Debian 8 on an ODROID Xu3. Compiled with SDL2, OpenAL (causses issues atm), LIBASS latest, GLES2 (Through SDL2), Disabled GL. If you need more information, don't hesitate :P

**Comment by htraki** [comment]
I had the same error message in Linux Mint Xenial. The problem was solved after upgrading libass to 0.13.2

**Comment by wm4** [comment]
Build error - you are compiling against a newer libass, but then using an older libass at runtime. Use of mpv-build is recommended.

**Comment by Goddard** [comment]
I get this error with your ppa on Ubuntu 16.04.

**Comment by CounterPillow** [comment]
@Goddard that PPA is not run by any of the core mpv developers.

**Comment by Goddard** [comment]
It is advertised on your website.  That kind of gives it an official appearance.

**Comment by Hrxn** [comment]
We probably could argue endlessly now about the possible semantics of _advertised_ in this context here.
But no, I don't think that this can be considered as "official" in any determined sense of the word.

Think of it like this, merely a starting point, guidance to give visitors the right direction.

I don't recommend to pin the devs down on this in any way - they would rather simply remove the link question, I assume.

**Comment by CartridgeGen** [comment]
I got over this problem real easy and i agree with hrxn. Its up to us to make sure our libraries match using a simple ldd command. I dont understand why this was reopened from a year ago.

**Comment by Goddard** [comment]
@Hrxn not trying to pin anyone down.  I am just saying, others, and myself included would be led to believe it is going to work if it is on your website.  If isn't the real deal PPA maybe just say this.

On the website it suggests it is the recommended method of using the player.

"Distributions usually package outdated, unmaintained, and unsupported versions of mpv. This is especially true for popular distros like Debian and Ubuntu. You are recommended to use mpv-build or 3rd party packages instead."

I am not trying to argue here.  I am saying I tried to use your software and it does not work.  That is all.

**Comment by CounterPillow** [comment]
Not exactly sure which part of "3rd party packages" made you think you should report a packaging issue in a 3rd party package to the upstream project by commenting on an old, barely related, closed and invalid issue. You're barking up the wrong tree. If you want it fixed, ask the person who runs the PPA, because there is no issue in mpv itself.

**Comment by Goddard** [comment]
Again not trying to argue, but apparently you are.

Clearly in context, it says you should use this PPA, **OR** 3rd party packages instead.

I honestly don't care.  I was just letting people know.  Reporting issues is in fact the purpose of this GitHub.  I had no indication why I was getting this error or that this PPA wasn't an official source.  I reported on this issue because that is what I found in the search engine.

Don't know why I am having to defend my self so vigorously for something so trivial.

**Comment by pink-mist** [comment]
> Clearly in context, it says you should use this PPA, **OR** 3rd party packages instead.

But it's not OR. The PPA **IS** a 3rd party package. How hard is it for you to understand this?

**Comment by CartridgeGen** [comment]
Lock the thread/issue.

**Comment by Hrxn** [comment]
@Goddard Look, I think I know where you are coming from. I get it. This whole situation is less than ideal (just the way the world works, apparently), and I understand that it is really frustrating for any potential user, starting from the official project page, believing to be doing everything in the right way, just to land in some dead end after all.

The remaining options are to find another 3d-party source for packages, or build it for yourself.

That's just how it is, different distros and their packaging systems are often a horrible mess. But that is their responsibility, and as the other comments in here already point out, you are unfortunately at the wrong place here.
