### ISSUE TITLE
linking error when build for mingw-w64 x86_64

### ISSUE THREAD

**Issue by artynet** [mpv-player/mpv#3150]
after following the usual steps for building mpv with the MXE environment, I get this error at the final linking :
```
[225/225] Linking build/mpv.exe
video/out/opengl/hwdec_dxva2gldx.c.14.o: In function `map_frame':
/home/arturo/MPV/mpv/build/../video/out/opengl/hwdec_dxva2gldx.c:185: undefined reference to `d3d9_surface_in_mp_image'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/arturo/MPV/mpv/build'
```
and then all the failed linkings are shown. any thoughts about that ?

Best, Arturo

**Comment by wm4** [comment]
Apparently you compiled without hardware decoding enabled, which caused an obscure build failure. I hopefully fixed the latter.
