### ISSUE TITLE
Add Grain

### ISSUE THREAD

**Issue by xeverse** [mpv-player/mpv#3153]
Is there a grain/noise video filter?
or how can one add some grain otherwise?

**Comment by wiiaboo** [comment]
Use higher levels of deband-grain, maybe? https://mpv.io/manual/master/#video-output-drivers-deband-grain

**Comment by haasn** [comment]
It would be relatively simple to do this with a user shader

**Comment by lachs0r** [comment]
And lavfi has a `noise` filter, too.

**Comment by xeverse** [comment]
@wiiaboo Thx. Though it has chroma too. I usually just add luma noise. But with lower values it looks as good as luma only.
@haasn How? Applying shaders that's what i was thinking at first.
@lachs0r Noise filter? Where is it? I couldn't find. https://libav.org/documentation/libavfilter.html

**Comment by haasn** [comment]
If you want to just add luma noise, you could copy/paste the PRNG that debanding uses into a custom user shader and have it apply to the LUMA and RGB textures (and add the noise to all three channels evenly).

**Comment by wiiaboo** [comment]
> @lachs0r Noise filter? Where is it? I couldn't find. https://libav.org/documentation/libavfilter.html

Only in FFmpeg. Libav is missing a lot of filters.

**Comment by haasn** [comment]
```glsl
//!HOOK LUMA
//!HOOK RGB
//!BIND HOOKED

#define STRENGTH 256

// PRNG taken from mpv's shader
float mod289(float x)  { return x - floor(x / 289.0) * 289.0; }
float permute(float x) { return mod289((34.0*x + 1.0) * x); }
float rand(float x)    { return fract(x / 41.0); }

vec4 hook()  {
    vec3 _m = vec3(HOOKED_pos, random) + vec3(1.0);
    float h = permute(permute(permute(_m.x)+_m.y)+_m.z);

    return HOOKED_tex(HOOKED_pos) + vec4(STRENGTH/4096.0 * (rand(h) - 0.5));
}
```

I wrote this, it should be what you want. (Adds grayscale noise only)

**Comment by xeverse** [comment]
@haasn vo=opengl-hq:post-shaders=~/.mpv/shader/lumanoise
`[vo/opengl-hq] fragment shader source:
[vo/opengl-hq] [  1] #version 330
[vo/opengl-hq] [  2] #define RG rg
[vo/opengl-hq] [  3] #define texture1D texture
[vo/opengl-hq] [  4] #define texture3D texture
[vo/opengl-hq] [  5] out vec4 out_color;
[vo/opengl-hq] [  6] in vec2 texcoord0;
[vo/opengl-hq] [  7] in vec2 texcoord1;
[vo/opengl-hq] [  8] in vec2 texcoord2;
[vo/opengl-hq] [  9] in vec2 texcoord3;
[vo/opengl-hq] [ 10] in vec2 texcoord4;
[vo/opengl-hq] [ 11] in vec2 texcoord5;
[vo/opengl-hq] [ 12] uniform float random;
[vo/opengl-hq] [ 13] uniform float frame;
[vo/opengl-hq] [ 14] uniform vec2 image_size;
[vo/opengl-hq] [ 15] uniform sampler2D texture0;
[vo/opengl-hq] [ 16] uniform vec2 texture_size0;
[vo/opengl-hq] [ 17] uniform vec2 pixel_size0;
[vo/opengl-hq] [ 18] #define LUT_POS(x, lut_size) mix(0.5 / (lut_size), 1.0 - 0.5 / (lut_size), (x))
[vo/opengl-hq] [ 19] // header
[vo/opengl-hq] [ 20] #define pixel_size pixel_size0
[vo/opengl-hq] [ 21] //!HOOK LUMA
[vo/opengl-hq] [ 22] //!HOOK RGB
[vo/opengl-hq] [ 23] //!BIND HOOKED
[vo/opengl-hq] [ 24] 
[vo/opengl-hq] [ 25] #define STRENGTH 256
[vo/opengl-hq] [ 26] 
[vo/opengl-hq] [ 27] // PRNG taken from mpv's shader
[vo/opengl-hq] [ 28] float mod289(float x)  { return x - floor(x / 289.0) * 289.0; }
[vo/opengl-hq] [ 29] float permute(float x) { return mod289((34.0*x + 1.0) * x); }
[vo/opengl-hq] [ 30] float rand(float x)    { return fract(x / 41.0); }
[vo/opengl-hq] [ 31] 
[vo/opengl-hq] [ 32] vec4 hook()  {
[vo/opengl-hq] [ 33]     vec3 _m = vec3(HOOKED_pos, random) + vec3(1.0);
[vo/opengl-hq] [ 34]     float h = permute(permute(permute(_m.x)+_m.y)+_m.z);
[vo/opengl-hq] [ 35] 
[vo/opengl-hq] [ 36]     return HOOKED_tex(HOOKED_pos) + vec4(STRENGTH/4096.0 * (rand(h) - 0.5));
[vo/opengl-hq] [ 37] }
[vo/opengl-hq] [ 38] // body
[vo/opengl-hq] [ 39] void main() {
[vo/opengl-hq] [ 40] vec4 color;
[vo/opengl-hq] [ 41] // custom shader
[vo/opengl-hq] [ 42] color = sample_pixel(texture0, texcoord0, texture_size0);
[vo/opengl-hq] [ 43] // scaler pre-conversion
[vo/opengl-hq] [ 44] color.rgb = clamp(color.rgb, 0.0, 1.0);
[vo/opengl-hq] [ 45] color.rgb = pow(color.rgb, vec3(1.961));
[vo/opengl-hq] [ 46] // main scaling
[vo/opengl-hq] [ 47] out_color = color;
[vo/opengl-hq] [ 48] }
[vo/opengl-hq] fragment shader compile log (status=0):
[vo/opengl-hq] 0(33) : error C1008: undefined variable "HOOKED_pos"
[vo/opengl-hq] 0(36) : error C1008: undefined variable "HOOKED_tex"
[vo/opengl-hq] 0(36) : error C1008: undefined variable "HOOKED_pos"
[vo/opengl-hq] 0(42) : error C1008: undefined variable "sample_pixel"
[vo/opengl-hq] 
[vo/opengl-hq] shader link log (status=0): Fragment info
[vo/opengl-hq] -------------
[vo/opengl-hq] 0(33) : error C1008: undefined variable "HOOKED_pos"
[vo/opengl-hq] 0(36) : error C1008: undefined variable "HOOKED_tex"
[vo/opengl-hq] 0(36) : error C1008: undefined variable "HOOKED_pos"
[vo/opengl-hq] 0(42) : error C1008: undefined variable "sample_pixel"
[vo/opengl-hq] 
[vo/opengl-hq] after rendering: OpenGL error INVALID_OPERATION.
`

**Comment by haasn** [comment]
Needs to be set as `user-shaders=`, not `post-shaders=`.

**Comment by xeverse** [comment]
>Error parsing option user-shaders (option not found)
Option vo: Error while parsing opengl-hq parameter user-shaders (~/.mpv/xeshader/haasn_lumanoise)
Error parsing option vo (option could not be parsed)
/home//.mpv/config:9: setting option vo='opengl-hq:user-shaders=~/.mpv/xeshader/haasn_lumanoise' failed.
Error parsing option user-shaders (option not found)
Option vo: Error while parsing opengl-hq parameter user-shaders (~/.mpv/xeshader/haasn_lumanoise)
Error parsing option vo (option could not be parsed)
/home//.config/mpv/mpv.conf:9: setting option vo='opengl-hq:user-shaders=~/.mpv/xeshader/haasn_lumanoise' failed.

**Comment by haasn** [comment]
> (And you need a newer version of mpv)

**Comment by xeverse** [comment]
@haasn ahh bleeding edge.. thanks anyway. i'll think about this.

**Comment by haasn** [comment]
You can port it to be used as a post-shader (pre-shader) instead, too. See the manual for details.

**Comment by xeverse** [comment]
@haasn Just tried the git version and your noise user-shader worked.

This noise is dither. Goood for vision. For visual perception. 
Essential feature i'd say for any video player.
Although i haven't research the actual algo but
the film grain and just prng noise is not exactly the same thing.

That's how i encode movies. I'd remove any grain/noise with temporal degrain.
Encode it. That way my transcodes half the size of anything else on trackers.
They use half of bitrate just for grain these release groups.
But then we need this grain back while playing back.
For righteous visual experience..

**Comment by xeverse** [comment]
Is it possbile to bind a key to quickly enable/disable such shader?

**Comment by haasn** [comment]
Sort of. You can use `vo_cmdline`, ideally in combinations with `--vo-defaults` to completely override the VO option list. You can use that to turn the user shader on or off at runtime.

(I use such a setup to turn interpolation on and off, see my configs [here](https://github.com/haasn/gentoo-conf/blob/nanodesu/home/nand/.mpv/input.conf#L48))

**Comment by xeverse** [comment]
@haasn Oh you interpolate? like svp? to 60fps?

**Comment by Hrxn** [comment]
@xeverse https://mpv.io/manual/master/#video-output-drivers-interpolation

**Comment by xeverse** [comment]
I'm not sure i'm getting hw decoding anymore when i use
vo=opengl-hq:user-shaders=~/.mpv/shader/lumanoise
instead of vo=vdpau
can i have both?

**Comment by Hrxn** [comment]
?
`vo=....`
`hwdec=vdpau`

**Comment by xeverse** [comment]
@Hrxn Now this works out.
Sometimes it does sometimes it doesn't.
Glitch in the matrix i guess.
must be all the hell broke loose or something..
