### ISSUE TITLE
how to specify 'youtube-dl' config path?

### ISSUE THREAD

**Issue by outsinre** [mpv-player/mpv#3155]
My Linux system has standard _youtube-dl_ instllation. However, I have another build in a customized path. I would like to tell _mpv_ to use my customized _youtube-dl_ instead of the default one.

Some guys suggest _creating a symlink in ~/config/mpv/youtube-dl_ pointing to my desired build. But `mpv -v` does NOT show such line as:

```
[global] config path: 'youtube-dl' -/-> '/home/jim/.config/mpv/youtube-dl'
```

**Comment by outsinre** [comment]
How to verify *mpv* is using my customized build instead of default?

**Comment by kevmitch** [comment]
You can narrow down the verbose messages with

    mpv  --msg-level=ytdl_hook=v https://www.youtube.com/watch?v=QuGu9LgbBNg

You should see a line such as 

     ytdl_hook: found youtube-dl at: /home/kevmitch/.config/mpv/youtube-dl

**Comment by outsinre** [comment]
`mpv  --msg-level=ytdl_hook=v https://www.youtube.com/watch?v=QuGu9LgbBNg`
only outputs:

```
libva info: VA-API version 0.38.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_38
libva info: va_openDriver() returns 0
```

I cannot see any information related to `ytdl_hook`.

**Comment by sergeevabc** [comment]
Issue is closed but question remains, is there a way to specify path to youtube-dl? mpv.conf var maybe.

**Comment by wm4** [comment]
PATH in your OS.
