### ISSUE TITLE
Rate-limiting ytdl

### ISSUE THREAD

**Issue by pks-t** [mpv-player/mpv#3156]
I currently have some problems with youtube-dl congesting my network link. That is when I download a video with youtube-dl, I am unable to do anything else that has to do with networking, e.g. browsing the web is painfully slow.

Youtube-dl has an option `--rate-limit`, which allows me to limit the maximum bandwith available to download the video. When I use the switch directly (e.g. `youtube-dl --rate-limit 1M <URL>`) the issue disappears, that is I can still do other things which require network access. I tried passing the option to youtube-dl via mpv by using `--ytdl-raw-options=rate-limit=1M`, but unfortunately this does not help, mpv still slows down my complete network link.

So I guess the option is not processed correctly, though I cannot tell who is responsible for this, either ytdl or mpv. But I'd guess it's mpv, as directly invoking ytdl with the option has the desired results.

**Comment by haasn** [comment]
To be honest, it would be better to solve this problem on the networking layer rather than the application layer.

One download consuming all your bandwidth should never cause interactive streams to become unusable.

**Comment by pks-t** [comment]
That's certainly true. I've tried things like QoS with fc_qodel or using other algorithms for congestion control but they didn't help. I've also noticed that only mpv/ytdl causes the issue, e.g. when downloading data at full speed via curl the issue does not occur. I'm rather clueless what ytdl does differently to cause this.
Maybe I should check back with ytdl upstream?

**Comment by haasn** [comment]
The key to solving congestion is dropping packets instead of slowing them down. Slow packets just ruin latency for everything else, since the FIFO needs to be painfully worked through when congestion happens.

Try adding a rate limiting filter + setting a much more aggressive `limit` option for your fq_codel perhaps? Also, try using “prio” to prioritize packets based on QoS tags (for outgoing traffic).

**Comment by wm4** [comment]
You could limit the mpv cache, which essentially would limit the download speed to the stream's bitrate.

**Comment by pks-t** [comment]
@haasn: yes, rate limiting solves the problem. I guess this solution would be acceptable for a stationary computer, where the link's rate is known. But on my laptop where I frequently connect to other networks I do not know the bandwith and would need to manually tweak it. I'm not that fluent with QoS, but is there anything that might help for ingress traffic that does not relay on rate limiting?

@wm4: Limiting the cache to a lower value causes the link to become responsible earlier than before, sure. I guess this solution is more acceptable than rate-limiting, I guess.

Thanks for your hints, I appreciate them and they help solving the symptoms. But in the end I don't think they solve the acutal problem. The question remains why ytdl kills my network while downloading via curl does not. But I guess I'll post the issue on the ytdl tracker, as the issue also occurs when directly invoking ytdl.

**Comment by wm4** [comment]
mpv doesn't even use youtube-dl to download media data. I don't think this issue has anything to do with mpv's or youtube-dl's networking.

**Comment by haasn** [comment]
> The question remains why ytdl kills my network while downloading via curl does not.

There's a good chance that curl sets some different QoS tags (e.g. marking it as “bulk” instead of regular traffic), although I'm pretty sure that would only affect egress.

> I'm not that fluent with QoS, but is there anything that might help for ingress traffic that does not relay on rate limiting?

I'm not that fluent with QoS either, so I have no idea how to even do ingress traffic shaping. (All of the examples I can find online deal with the scenario in which you have one router that has an upwards and an inwards link, so you can do egress limiting on the “inwards” link to limit users' downloads)

**Comment by SPDurkee** [comment]
I don't know if it's appropriate to comment on closed issues, but when searching for mpv rate limiting this appears high in the search results.

I've found an easy solution to this: curl --limit-rate 1m {URL} | mpv -

**Comment by haasn** [comment]
^ slightly better would be `mpv <(curl --limit-rate 1m URL)`, to avoid breaking stdin on the mpv process
