### ISSUE TITLE
Merge --sub-scale-by-window and --sub-scale-with-window into a single option

### ISSUE THREAD

**Issue by maniak1349** [mpv-player/mpv#3158]
`--sub-scale-by-window` and `--sub-scale-with-window` options are affecting the same thing - how resizing the window affects the size of the subtitles. Regardless of how they are or will work there always will be one combination which will not make much sense/be pretty much useless. Also options have similar yet not really self explanatory names which lead to even more confusion.

Suggestion: merge them into one option with 3 states that will cover all useful modes.
Suggested name/params: `--sub-scale-mode=<none|by-video|by-window>`

There may be a confusion about using `--sub-scale` with `--sub-scale-mode=none` - `--sub-scale` will still work in this case. So this new option probably should have a different name. If the name stays, then this case should be mentioned in the documentation.

There should probably be a minimum level of compatibility during a deprecation period of old options.

---

---

Old post:

Right now on practice `--sub-scale-by-window` and `--sub-scale-with-window` options affect subtitles size as follows:

| mode | when the video is resized | vertical margins effect |
| --- | --- | --- |
| none | font with constant size N | font is becoming _smaller_ proportionally to margin size |
| with | font with constant size N | none |
| by | font is scaled to video size | none |
| by + with | font is scaled to video size | margin is counted as part of the video size |

As you can see only 'by' mode is actually doing exactly what it should according to man. It's easy to fix the behavior of 'none' mode (it's uses video+margin height instead of just video height), but the question is how 'with' and 'by + with' modes should work.

If current 'by + with' effect is the way it should be then the only use for 'with' mode I see is to not touch font size unless the size dictated by window height is exceeding the fixed size. If it does, then replace it with new size. This way font size will remain constant with video resize (but not when margins are added) yet keeping fullscreen font size consistent. This will be even more confusing behavior than right now.

But I believe that the better solution would be to remove those weird combined behaviors altogether. Then scaling modes will work like this:

| mode | when the video is resized | vertical margins effect |
| --- | --- | --- |
| none | font with constant size N | none |
| with | font is scaled by video size | margin is counted as part of the video size |
| by | font is scaled by video size | none |

Simple and straightforward. And to eliminate the combied mode and make configuring those scaling behaviors more comprehensible I suggest to replace `--sub-scale-by-window` and `--sub-scale-with-window` with the single choice option. Something like: `--sub-scale-mode=<none|by-video|by-window>`. Not sure about the name though - it may lead to some confusions with relation to `--sub-scale` option. Any suggestions with naming?

If the above should be implemented, then I believe `--ass-scale-with-window` should be replaced too (by separate option of course) to make the syntax consistent. There is no `--ass-scale-by-window` option right now - it is on by default. That's because it can break ass layout I guess, but since `--ass-scale-with-window` can break it too, then there is no harm in allowing user to disable scaling by window as long it is staying on by default.

Also, it seems to me that those options can be implemented as commands, but the usefulness of them are questionable. The only practical use of them I see is to play with them on different samples and see what suits you best, then add necessary options to configuration file and succseefuly forget about them. So the question is - what's mpv's policy about options-commands?
- add everything that will work in runtime and will not break anything

or
- add only stuff that will make sense and will be actually useful

Also on a semirelated subject - I've noticed that sub margin usage options are doing the same thing for ass and text subtitles and have similar names in `MPOpts` (`ass_use_margins` and `ass_use_margins`) but called differently - `--ass-force-margins` and `--sub-use-margins`. The 'force' word is obviously to indicate that using margins is not a good idea with ass, but shouldn't they be both `-use-` to simplify understanding of what they do? And the explanation of usage dangers can be left for documentation.

And finally - I'm pretty sure I can fix/implement this.

**Comment by wm4** [comment]
> And finally - I'm pretty sure I can fix/implement this.

Implement what? The merging of the 2 sub-scale options? Sure, that's probably an ok idea. But there should probably be a minimum level of compatibility during a deprecation period.

Also, I still don't really get what you mean. There's too much text.

**Comment by maniak1349** [comment]
Sub scaling by-window/with-window not always working correctly. Most cases are fixable, but with the way things are now there always will be a case with weird behavior. Also two options that do the same thing in different ways and weirdly overlap in one case are confusing.

Suggestion: merge them into one option with 3 states that will cover all useful modes.
Suggested name/params: `--sub-scale-mode=<none|by-video|by-window>`

Should it be done like this or should those options be left alone?
> probably an ok idea

In that case:

1. There may be a confusion about using `--sub-scale` with `--sub-scale-mode=none`. `--sub-scale` will still work. Different name for option?
2. There is `--ass-scale-with-window`, but no `--ass-scale-by-window` right now (always on). Should it be replaced with `--ass-scale-mode` and if yes - should `none` mode be allowed for ass? (it's not now)
3. Both old and new options can be made into commands (available for hotkeys). There is little use for them, yet they will (probably) not break anything. In such cases - to add or not to add?

> Implement what? The merging of the 2 sub-scale options?

Yes, and also (3) and (4) if the answer is "yes" for them too. Sorry, maybe "implement" is too big a word for that.

> But there should probably be a minimum level of compatibility during a deprecation period.

Right, now I'm not sure I can do this.

**Comment by wm4** [comment]
> Sub scaling by-window/with-window not always working correctly.

When?

Both options set to "yes" is actually the mpv default for normal text subs (non-ASS). The intention is that the font proportionally scales with the window. It should not consider the video margins, because the video margins are also used by default for normal text subs. To repeat this, the window size is used to scale the text size, and the subs otherwise fill out the window fully. This is how it should work, and there's nothing to fix.

`--sub-scale-by-window=no` means literally that changing the window size should not change the font size. If you add `--sub-scale-with-window=no`, the font size will depend on the margins, which may or may not make sense. (But most likely a bit useless.)

Only setting `--sub-scale-with-window=no --sub-use-margins=no` is useful if you want the subtitles to be part of the video. For ASS, this mode is mandatory, but note that if you enable style override mode, the `--sub-...` options are used instead. I think that's sane.

I still don't understand what you want to change, other than merging the two options into one.

**Comment by maniak1349** [comment]
It's simultaneously options effect interpretation/comprehension issue and an actual error i believe. That's why I think that those options should be merged - it will reduce the confusion. And that's why there all that text above - because I was trying to explain what's wrong and obviously failed miserably.

Let give it one more try. There's what's going on right now:

by|with|when the video is resized|vertical margins effect
---|---|---|---
no|no|font with constant size N|font is becoming **smaller** proportionally to margin size
no|yes|font with constant size N|none
yes|no|font is scaled to video size|none
yes|yes|font is scaled to video size|margin is counted as part of the video size

From your post above I've got that you believe that by+with behavior is correct (last line of the table). As if we saying to the player **'scale subtitles with window size including the margins'**. Let's left it like that.

Second line from the bottom - `scale-by-window`. It does exactly what it says in the documentation right now **'scale subtitles with video size, ignore the margins if any'**. (The fact that video part is mentioned only in `--sub-scale-with-window` description does not really help to understand this.)

Now lets get to the first line of the table - scaling by window and video is disabled - at least this is what is said in the documentation. **'don't scale subtitles at all, ever'**. With this configuration scaling (or rather lack of it) works fine with no margins, but it makes subtitles **smaller** with margins. If it should be like that then description does not indicate that in any way.

And now to the second line scaling by video is disabled, yet scaling by window is enabled. This is most confusing option since **'scale subtitles with window size including the margins'** is already done by by+with configuration.

If it is doing the same thing, then it's fine, it just needs an addition to documentation that this option overrides `scale-by-window`. If it's doing something else (not scaling with window but scaling with margins, for example) than it's not really logical and definitely not explained anywhere.

And right now it's acting in neither of those ways. Now its doing **'don't scale subtitles at all, ever'** thing. This goes against the documentation and logic.

Sorry, wall of text again, but I can't explain it any better. I can make some screenshots, but there will be a lot of them for all cases and it will probably be even more confusing.

-------------------

(You can skip the rest if your head is already full of this stuff.)

To explain the confusion further - this is the way I assumed the options work (or at least should work) by looking into documentation only:

by|with|action
---|---|---
no|no|don't scale subtitles at all, ever
no|yes|scale subtitles with window size including the margins
yes|no|scale subtitles with video size, ignore the margins if any
yes|yes|its either **scale subtitles with window size including the margins** due to unmentioned override, or this combination is invalid and can't/shouldn't work correctly because it will scale subtitles twice

That's why in the first post I said that it's working correctly only in one case (third) and maybe in another one (fourth).

**Comment by wm4** [comment]
Sorry, your explanations are just too confusing.

Here is how it _does_ and _should_ work:

by|with|changing window height|changing vertical margins
---|---|---|---
no|no|no effect|scales the font
no|yes|no effect|no effect
yes|no|scales the font|scales the font
yes|yes|scales the font|no effect

The no/no case specifically scales the font with the video size. E.g. if you scale video 2x, each pixel will have twice the size, and the font will also have twice the size. It might be useless, but it does what it's documented to do.

There is a libass bug, which causes the subtitles to shift/crop incorrectly with large margins (see https://github.com/libass/libass/issues/218).

I also agree that the names/descriptions of these options might be confusing, and some combinations might be pointless.

So, describe in 1 or 2 sentences (and _not_ more): where is there an actual bug here?

**Comment by maniak1349** [comment]
Differences between my test and your table:
1. Effects of line 3 and line 4 are switched.
2. In case from line 1: changing window height with no vertical margins has no effect (correct), when there are vertical margins subtitles are getting smaller proportionally to margin size (incorrect?). Example:
![window](https://cloud.githubusercontent.com/assets/2755776/15455173/2e11090a-2055-11e6-8d97-dda73e0ec82d.jpg)
![fullscreen](https://cloud.githubusercontent.com/assets/2755776/15455172/2d9fe20c-2055-11e6-8bd3-ffce97ce5b1b.jpg)

**Comment by wm4** [comment]
>  1. Effects of line 3 and line 4 are switched.

Can't confirm. I just retested with `--sub-scale-by-window=no --sub-scale-with-window=yes`. The font size always stays the same, no matter how I change margins (with panscan or zoom), or the size of the window (by... resizing it).

>  2. In case from line 1: changing window height with no vertical margins has no effect (correct), when there are vertical margins subtitles are getting smaller proportionally to margin size (incorrect?).

No, both are correct. It makes more sense with `--sub-use-margins=no` (but this option shouldn't change font size in this case).

**Comment by maniak1349** [comment]
> Can't confirm. I just retested with `--sub-scale-by-window=no --sub-scale-with-window=yes`. The font size always stays the same, no matter how I change margins (with panscan or zoom), or the size of the window (by... resizing it).

` --sub-scale-by-window=yes --sub-scale-with-window=no` and ` --sub-scale-by-window=yes --sub-scale-with-window=yes` are switched. yes/no ignores margin, yes/yes scales with it. In the table it the other way around.

> No, both are correct. It makes more sense with `--sub-use-margins=no` (but this option shouldn't change font size in this case).

Alright, if you say so. I thought it was a bug because it's somewhat weird to get a smaller font with a bigger window.

**Comment by wm4** [comment]
> because it's somewhat weird to get a smaller font with a bigger window.

The option means the font size scales with the video size. Although it doesn't make too much sense in combination with the other option, which means the font won't scale with the window. So I agree the options could be merged with the nonsense combination omitted.

**Comment by maniak1349** [comment]
(Sorry to bother you again with this, but that's hopefully the end of the ride.)

> `--sub-scale-by-window=yes --sub-scale-with-window=no` and `--sub-scale-by-window=yes --sub-scale-with-window=yes` are switched. yes/no ignores margin, yes/yes scales with it. In the table it the other way around

I have thought a bit about it and double checked the documentation. And it seems to me that the way things are now is correct. The documentation clearly says that `--sub-scale-with-window=yes` "Make the subtitle font size relative to the window, instead of the video".

So there is just a typo in your table? Should it be:

by | with | changing window height | changing vertical margins
---|---|---|---
no | no | no effect | scales the font
no | yes | no effect | no effect
yes | no | scales the font | no effect
yes | yes | scales the font | scales the font

If that's the case and if we ignoring no/no behavior as we agreed, then there is actually nothing broken right now.

**Comment by wm4** [comment]
>So there is just a typo in your table? Should it be:

No.

**Comment by maniak1349** [comment]
> No.

Well then I obviously don't understand why it should work the way you say it should. I'll just leave the decision to those who does.

Updated title and first post with useful info.

**Comment by wm4** [comment]
> Well then I obviously don't understand why it should work the way you say it should. 

Are you denying how it _does_ currently work, or only how it should?

**Comment by maniak1349** [comment]
Only how it should. The way it does work right now at least agrees with the things the documentation say in my opinion. (If no/no case is ignored that is.)

**Comment by wm4** [comment]
The font size is locked to the video size in this case. If the margins get larger, the video size gets smaller, thus the font gets smaller.

> (If no/no case is ignored that is.)

wat

You keep doing this. Please express yourself clearly.

**Comment by maniak1349** [comment]
> You keep doing this. Please express yourself clearly.

That's because I'm completely confused about no/no case now. That's what you said before:
>
by|with|changing window height|changing vertical margins
---|---|---|---
no|no|no effect|scales the font

Yes, that's what's happening right now: changing the size of the window is not affecting font size, changing margin size without changing the video size makes the font smaller proportionally.

> The no/no case specifically scales the font with the video size. E.g. if you scale video 2x, each pixel will have twice the size, and the font will also have twice the size. It might be useless, but it does what it's documented to do.

This is not happening right now: video size by itself has no effect on the font size. The only thing that affects the font size is the difference between margin size and video size.

> The font size is locked to the video size in this case. If the margins get larger, the video size gets smaller, thus the font gets smaller.

Yes, that's what's happening right now.

Conclusion: either I misunderstanding the second statement or it contradicts with first and third ones.

Now to the reason why I want to ignore it and think it's weird:
There is no direct mentions in documentation of the fact that no/no acts in relation to difference between video size and video window and that the bigger the margin the smaller the font. I just can't see how I can know this regardless of how I read the documentation.

So if it's desired bahavior then it should be documented.

Let's just look from the perspective of unaware user: I've set --sub-scale-by-window and --sub-scale-with-window to NO. So now there is no size related scaling enabled and now my subtitle font wil be the same all the time.

**Comment by wm4** [comment]
> This is not happening right now: video size by itself has no effect on the font size. The only thing that affects the font size is the difference between margin size and video size.

It's about the conceptual video size. If you set `--sub-use-margins=no` (which _only_ changes the subtitle position currently), you will see that changing margins in this mode will keep the relative video size equal to video scaling. Yes, the absolute scaled or unscaled video size does not matter, which indeed is odd, but just a consequence due to how it works. (And I never claimed this combination makes too much sense.)

**Comment by maniak1349** [comment]
Wait, so "changing vertical margins" = "scales the font" in third line of your table (yes/no case) means that it scales it _down_? And as a result of the combination of these effects font retains it's size when the video stays the same and margins are changing?

**Comment by maniak1349** [comment]
It seems that I just have misread the table, it makes sense now. And yes, the options are working exactly like that right now.

**Comment by Stefan986** [comment]
This thread could have been much easier if someone actually took time to check all 4 possible combinations for these 2 ---sub-scale options. These are not the same and this is not a good idea. Having it merged would cause many weird and unexpected scaling issues. There are 4 combinations:

1. Both set to YES (merged)
`sub-scale-with-window=yes`
`sub-scale-by-window=yes`

[http://imgur.com/2kmjILL](url)


2. Both set to NO (merged)
`sub-scale-with-window=no`
`sub-scale-by-window=no`

[http://imgur.com/qBuinCK](url)


3. Set to YES and NO (not merged)
`sub-scale-with-window=yes`
`sub-scale-by-window=no`

[http://imgur.com/S0AMoB8](url)


4. Set to No and YES (not merged)
`sub-scale-with-window=no`
`sub-scale-by-window=yes`

[http://imgur.com/OMTQfon](url)

It would cause issues with snapped windows especially. On screen-shots there are 3 windows snapped to left upper corner, snapped to right edge and just floating scaled down window. mpv.exe used the same mpv.conf with these 4 possible configuration of sub-scale-by/with-windows options as described. Obviously these are different.

**Comment by Akemi** [comment]
seems like this is off the table.
