### ISSUE TITLE
GLES-only output

### ISSUE THREAD

**Issue by sardemff7** [mpv-player/mpv#3159]
Currently, having the full OpenGL installed means having GLX too, and thus X11.

Would it be possible for mpv to use only the GLES subset, so it could run nicely on a X11-free system? Maybe at least using VA-API?

**Comment by wm4** [comment]
This has nothing to do with GLES vs. full OpenGL.

You can compile without X11 and run Wayland or use `--vo=opengl:backend=egl-drm` - but only if you have a Intel GPU. (MAybe AMD works too, no idea.)
