### ISSUE TITLE
Interpolation crash with tscale=lanczos

### ISSUE THREAD

**Issue by linkmauve** [mpv-player/mpv#3160]
Here is the failed assert:
```
mpv: ../video/out/opengl/utils.c:655: find_uniform: Assertion `sc->num_uniforms < SC_UNIFORM_ENTRIES' failed.
```

**Comment by haasn** [comment]
Try again with https://github.com/mpv-player/mpv/commit/8262a4dd5296f11338b2d54190982b1e07aa1267

**Comment by linkmauve** [comment]
That fixed it, I’ll upgrade before reporting a bug the next time, sorry.
