### ISSUE TITLE
waf configure with --enable-rpi fails with error: You manually enabled the feature 'rpi', but the autodetection check failed.

### ISSUE THREAD

**Issue by hlima** [mpv-player/mpv#3163]
the configure phase is failing to recognize it is compiling in an rpi. This is apparently due to the fact the the check for lib 'EGL' is not including 'GLESv2' that is referenced by 'EGL'. this causes the link to fail with a lot of missing simbols.
I was able to get it to work changing the wscript as follows:

```
diff --git a/wscript b/wscript
index 684fdf0..c59dda5 100644
--- a/wscript
+++ b/wscript
@@ -788,7 +788,7 @@ video_output_features = [
                      lib=['mmal_core', 'mmal_util', 'mmal_vc_client', 'bcm_host']),
             # We still need all OpenGL symbols, because the vo_opengl code is
             # generic and supports anything from GLES2/OpenGL 2.1 to OpenGL 4 core.
-            check_cc(lib="EGL"),
+            check_cc(lib=["EGL","GLESv2"]),
             check_cc(lib="GLESv2"),
```

**Comment by wm4** [comment]
Doesn't that mean the `check_cc(lib="GLESv2"),` is redundant? Also, git format-patch or PR, please.

**Comment by wm4** [comment]
PS: last I checked it worked - I'm wondering if this is not accidentally picking up a wrong libEGL (maybe Mesa's instead of the RPI firmware).

**Comment by hlima** [comment]
I am using Jessie build from may 10 that I downloaded from the raspberry  site.
A find for libEGL gives me the following:
./usr/lib/arm-linux-gnueabihf/libEGL.so.1
./usr/lib/arm-linux-gnueabihf/libEGL.so.1.0.0
./opt/vc/lib/libEGL.so
./opt/vc/lib/libEGL_static.a

I think that it is picking up libEGL from /opt/vc/lib

**Comment by hlima** [comment]
after 3 years I had to compile this particular version (v0.28.0) again and figure that the problem was the check for libEGL. It requires libGLESv2 to be linked as well. I changed line 776 in wscript  o include libGLESv2 as follows:
 `check_cc(lib=["EGL","GLESv2"]),`     
and then things worked as usual
