### ISSUE TITLE
Changing window-scale via commands should keep the video centered

### ISSUE THREAD

**Issue by FichteFoll** [mpv-player/mpv#3164]
When changing the window-scale property via commands (such as `input.conf`), the window remains positioned at its top-left x and y coordinates. It would be much nicer if the window would move accordingly to make its center position static instead.
When the window would exceed a monitor's screen estate, it should then adjust its position to not exceed it, assuming there's enough space left on the other sides (while considering https://github.com/mpv-player/mpv/issues/2935).

mpc-hc has this behavior. I can record a video (or gif) if desired.

Related: https://github.com/mpv-player/mpv/issues/2397, https://github.com/mpv-player/mpv/issues/2301

(I'm on Windows 7.)

**Comment by Hrxn** [comment]
Yes, same on Windows 10.

I think this is a good idea, honoring the `geometry` setting after a `set window-scale`.

But it should be made optional, keeping the window corner fixed is also useful.

**Comment by FichteFoll** [comment]
Just a clarification: I did not mean something like honoring the geometry setting always. If the window is moved, it gets a new "center" position which it should resize around.

**Comment by c02y** [comment]
This feature request shouldn't be closed since the video is not centered after changing window-scale via shortcuts of mpv

**Comment by Akemi** [comment]
this was added for the windows backend and might have been requested for windows. so closing it was actually fine. if it doesn't work for you (on other platforms) just open an issue with all infos we ask for. at least that makes a lot more sense than commenting on a years old closed issue that everyone will just ignore.
