### ISSUE TITLE
IPC command to perform property expansion

### ISSUE THREAD

**Issue by FichteFoll** [mpv-player/mpv#3166]
I would love to have an IPC command that performs property expansion like in `show_text` but returns the result. Command name could be `expand_properties` or similar. It would accept a string as parameter and return the formatted result in the data field.

You can get basic functionality by querying each property manually with the `get_property` IPC command but that only returns the value and no actual formatting. The conditionals are also not supported and would require to be implemented as well somehow.
Exposing the already existing expansion in mpv would be much easier than trying to emulate it externally.

**Comment by FichteFoll** [comment]
Here's a hack for this that I implemented in Python by abusing the `run` command and writing an expanded argument to a file which I then read from the actual application:

https://github.com/FichteFoll/hexchat-addons/blob/66bb2c3a6afa023e4f57fa03102c261f91755c6e/mpv_np.py#L151-L196

Doesn't feel good but it works.

**Comment by wm4** [comment]
Part of the problem is that I don't even want property expansion to be part of any API.

**Comment by FichteFoll** [comment]
Any reason for that?

**Comment by wm4** [comment]
I want to change it one day, and exposing it to even more things would increase the breakage.

**Comment by wm4** [comment]
I could expose it in a tricky/subtle way via a sub-property, something like `expand/...text`, which you then could query via `get_property`. Would that work?

**Comment by FichteFoll** [comment]
I'm not sure I understand that.

Can you show me an example of expanding this property string: `${media-title} [${time-pos}${!duration==0: / ${duration}}]`?

**Comment by Dudemanguy** [comment]
`expand-text` has existed for a while now so this should be possible.

**Comment by Dudemanguy** [comment]
I take back the above. I don't think that works because IPC doesn't use command-native (someone correct me if I'm wrong again).

**Comment by FichteFoll** [comment]
No, it does indeed work for me. I completely missed that `expand-text` has been added and verified that it does indeed work as I need it to. Thanks for the heads-up.

https://github.com/FichteFoll/hexchat-addons/commit/ea51b71e266b7bc6f1e8a9f999529b5602bdb4d2
