### ISSUE TITLE
External subtitles with ordered chapters are not properly loaded and played back

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#3168]
Hi,

If you play a file that uses ordered chapters and both the main file and the 'chapters' have external subtitles file, two issues happen:
- Only the main file's subtitles are loaded and rendered
- The subtitles of the main file are not offset by the duration of the 'chapter', meaning that they will continue during the chapter and be desynced after the main file resumes.

Here is some dubious ascii art to help illustrate the issue:

```
01.mkv 01.ass
02.mkv 02.ass

  [----------------------|----------------|--------------------]
  ^                      ^                ^
01.mkv                 02.mkv          01.mkv 

   ^^^^^^^^^^^^^^^^^^^^^^
everything ok, 01.ass is loaded
  
                          ^^^^^^^^^^^^^^^^
                 02.ass is not loaded, the subtitles 
                    from 01.ass keep appearing
  
                                           ^^^^^^^^^^^^^^^^^^^^                             
                                      the rest of the 01.ass is played
                                               desynchronized
```

Thank you.

**Comment by wm4** [comment]
This is not supported. Remux the ordered chapters into a single file, or merge the subtitles into a single file. You could also create a EDL file for the subtitles and load that.

**Comment by occivink** [comment]
Alright, I was expecting something like that. As long as the issue is acknowledged I'm fine.
Thanks for the hints.
