### ISSUE TITLE
docdir being used to store .conf files? not installing to debian/tmp/etc/

### ISSUE THREAD

**Issue by ProfessorKaos64** [mpv-player/mpv#3172]
Platform= Debian 8

I have been using/mimicking packaging from Debian (I have checked the external sources at https://mpv.io/installation/ for PPAs) up until release 0.17.x here. Why would .conf files be written to the data dir? in my [log](http://sprunge.us/jKZY) of the build, I don't see any place where files are being written to etc. libdir is being picked up fine from my [debian/rules](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/mpv/debian/rules), but not /etc/mpv it seems. `destdir=debian/tmp` sets the install destination of course, but only ever /usr, and subsequently, /usr/lib and /usr/share end up there.

See [this line](https://github.com/mpv-player/mpv/blob/f0d743741235fcf4f73610c45c2684268d744183/wscript#L942)

**Comment by wm4** [comment]
They're example. mpv generally doesn't need any installed config files, except maybe the encoding profiles if you want to use them for encoding.

**Comment by ProfessorKaos64** [comment]
I'm not sure why nothing is being written to $PREFIX then for etc, when it used to. *shrugs*

**Comment by wm4** [comment]
Why should it?

**Comment by ProfessorKaos64** [comment]
No idea then why [Debian Sid's](https://packages.debian.org/sid/mpv) approach would specify in mpv.install `etc/*` when that doesn't getting written. I'll just axe it if their approach isn't valid anymore.

**Comment by wm4** [comment]
I don't know what exactly Debian does, and their mpv packages are effectively unmaintained.

> would specify in mpv.install etc/* when that doesn't get written.

Probably to force these directories to be created.

**Comment by mc4man** [comment]
The only thing installed to /etc/mpv was & still is, -  encoding-profiles.conf.

**Comment by ProfessorKaos64** [comment]
I don't get debian/tmp/etc/* at all @mc4man. Would it be safe to pull that from etc in the source root? i.e. the repository.

**Comment by mc4man** [comment]
Not sure why this matters if you are building for yourself  & myself have nothing to do with Debian or Deb-Multimedia but ck. debian/mpv.install file. Does it have on a line   - 
etc/*

**Comment by ProfessorKaos64** [comment]
Yep it has that https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/mpv/debian/mpv.install

**Comment by mc4man** [comment]
Well then get rid of the line in the mpv.install file. 
Out of curiosity, does your debian built mpv even do encoding? If not then no purpose for the file..
(your log says 'disabled', as in  ' Checking for Encoding                                                     : disabled '

**Comment by mc4man** [comment]
I believe in 0.17 'release' encoding was default disabled. So if disabled no /etc/mpv/encoding-profiles.conf so no /etc/mpv as there is nothing going in there.
