### ISSUE TITLE
If libcaca is the video output, the option --really-quiet should be added automatically.

### ISSUE THREAD

**Issue by z3ntu** [mpv-player/mpv#3173]
As I wrote in the title when you use `libcaca` for the video output, normally mpv prints the status line(s) over libcaca's output and it looks really weird. So to "prettify" the experience you get with caca, mpv should not print anything to the terminal (`--no-terminal` is bad, as you can pause the video, but can't resume afterwards (or quit mpv) and you have to kill the process).

**Comment by wm4** [comment]
I don't consider libcaca an important enough use-case to add a complex mechanism that would achieve this. In fact, I'd rather drop libcaca support.

**Comment by z3ntu** [comment]
:( Please not, libcaca is really cool to show off to other people.
