### ISSUE TITLE
How can I disable software scaler?

### ISSUE THREAD

**Issue by duyhotan2000** [mpv-player/mpv#3175]
Hello,

I want to build MPV and run it on an ARMv8 based SoC.
However, I don't need to use software scaler and want to disable it. The reason maybe it is very low performance because there is no accelerator for ARM.
Can you tell me how I can disable it?

Thank you!

**Comment by wm4** [comment]
Well, without software scaler you probably can't see anything? I suspect you're on X11 and using `--vo=x11`.

Implementing a backend for vo_opengl might help a bit.

The only way to get full performance would be using the SoC's native video API, which would probably be hard.
