### ISSUE TITLE
yet another *sshole OS software dev

### ISSUE THREAD

**Issue by negativeions** [mpv-player/mpv#3176]
That's what we need more of. More dipsh*t OS devs who don't give a sh*t about anyone except themselves and "smart people" who are into programming. The peons be damned. "We don't owe you anything, stfu". Yeah, well, wtf kind of world do we live in? Maybe I should put my career on hold, spend 5 years of my life learning programming just to write a good bloody video player with a UI that actually works and plays all formats properly in OSX. Is that it? MPC HC, now that's a team of real, normal people.

**Comment by pigoz** [comment]
There are several UI to mpv, and FYI the dipshit os dev you talk about works on Plex Media Player, which I heard is an open source GUI to mpv, which runs well on OS X and is actually primarly developed on it.

**Comment by haasn** [comment]
When it comes to making people do something for your benefit, shouting and screaming while stamping your feet is a pretty ineffective way of accomplishing that.

**Comment by divinity76** [comment]
*or hire someone to fix it :-)

**Comment by Brottweiler** [comment]
Issues in this manner should, in my opinion, be replied to by a contributor then be locked.
