### ISSUE TITLE
zoom in mpv

### ISSUE THREAD

**Issue by TheChymera** [mpv-player/mpv#3177]
How can I zoom in on a video in mpv?

I have tried the `e` and `v` keys and I get notified about the updated Panscan value - but that does nothing to my image.

**Comment by region51** [comment]
```
Alt+- add video-zoom -0.25
Alt+= add video-zoom 0.25
```

**Comment by TheChymera** [comment]
Thank you, that worked.

Why is `alt+=` recommended rather than `alt++` ?

**Comment by Hrxn** [comment]
You can change `alt+=` to anything you like..

**Comment by TheChymera** [comment]
@Hrxn I am aware, I just sa the recommendation I got, and found the same advice elsewhere on the web. I am wondering if I'm missing something obvious that might make `alt+=` the first choice in this matter rather than `alt++`.

**Comment by paulguy** [comment]
= is next to -.  + is a shifted character.

**Comment by TheChymera** [comment]
Ah, different countries, different layouts :)

**Comment by PowaBanga** [comment]
on be-latin1 keyboad, `+` and `=` are on the same key

is there a way to chang keyboard configuration ???

**Comment by Hrxn** [comment]
Yes, edit `input.conf`

**Comment by goetzc** [comment]
Once zoomed, panning can be done with these VIM-like keybinding:
```
Alt+h add video-pan-x 0.05
Alt+l add video-pan-x -0.05
Alt+k add video-pan-y 0.05
Alt+j add video-pan-y -0.05
```

**Comment by wm4** [comment]
There are default bindings now (though different ones).

**Comment by wltprgm** [comment]
In Fedora 27 mpv version 0.27.2-1.fc27 does not have these key bindings yet. man mpv does not have the key bindings like the official one as well [link](https://mpv.io/manual/master/#keyboard-control)

**Comment by Argon-** [comment]
If you take a look at the dates of wm4's post, this was 6 days ago.
Meanwhile, you are using a version of mpv more than half a year old. How would you expect this to work?

**Comment by goetzc** [comment]
@Argon-  0.27.2 was released [two months ago](https://github.com/mpv-player/mpv/releases/tag/v0.27.2).

**Comment by Argon-** [comment]
v0.27.1 as well as v0.27.2 are both v0.27.0 with changes _only_ to the ytdl_hook.

**Comment by goetzc** [comment]
So you are trying to say the new keybindings are only on master branch and not on a release version?

**Comment by Hrxn** [comment]
> So you are trying to say the new keybindings are only on master branch and not on a release version?

Yes, exactly.

**Comment by abdallahbouhannache** [comment]
how to do zoom to specific point of the video !just like pictures.

**Comment by wm4** [comment]
There might be a script for that. (I don't know which. Look at the wiki.)

**Comment by ValZapod** [comment]
Alt+Schift+ "+" for zoom +

**Comment by 07416** [comment]
from the command-line:

    --video-zoom=0.25

**Comment by All3xJ** [comment]
> Once zoomed, panning can be done with these VIM-like keybinding:
> 
> ```
> Alt+h add video-pan-x 0.05
> Alt+l add video-pan-x -0.05
> Alt+k add video-pan-y 0.05
> Alt+j add video-pan-y -0.05
> ```

actually it does not work for me. only alt+ and alt- works
