### ISSUE TITLE
segfaults with amdgpu drivers

### ISSUE THREAD

**Issue by natostanco** [mpv-player/mpv#3179]
using `hwdec=vdpau/vo=vdpau` with amdgpu drivers causes segfaults system wide, first mpv then the whole system.
here my xorg.conf: http://pastebin.com/raw/Pg57FFth

**Comment by wm4** [comment]
If it crashes the whole system, it's definitely not a mpv issue.

**Comment by natostanco** [comment]
well, vlc segaults too, but does not make the system crash so I don't know.

**Comment by wm4** [comment]
No, if a normal application can tear down your system, it's your drivers fault.

**Comment by haasn** [comment]
There's little we can do about AMD's terrible drivers.

**Comment by wm4** [comment]
(I can only suggest to report it upstream. Would be nice to have a link to the upstream bug report here.)
