### ISSUE TITLE
[question] Does subtitle encoding detection include format specific characters?

### ISSUE THREAD

**Issue by larvanitis** [mpv-player/mpv#3180]
I was having some problems with false encoding detection, while using uchardet, and I was wondering if the buffer passed to the library code for evaluation is stripped of the format (`srt` etc.) specific characters such as timing information and formatting markup (such as `<i>`).

So, would this `srt` file
```
1
00:00:12,345 --> 00:00:13,678
<i>Hello</i>
world!
```
be passed as is or would it get stripped to just
```
Hello
world!
```

I tried to find out from [`charset_conv.c`](https://github.com/mpv-player/mpv/blob/v0.17.0/misc/charset_conv.c) and [`demux_lavf.c`](https://github.com/mpv-player/mpv/blob/v0.17.0/demux/demux_lavf.c) but I don't speak C...

Thanks!

**Comment by wm4** [comment]
No, mpv essentially passes the whole subtitle file to the detector.
