### ISSUE TITLE
sigmoid-upscaling affects downscaling too

### ISSUE THREAD

**Issue by maniak1349** [mpv-player/mpv#3183]
OpenGL `sigmoid-upscaling` option affects downscaling too. Is it supposed to be that way? Neither documentation nor option name says anything about it.

**Comment by Hrxn** [comment]
Not sure, could be the color transformation being active regardless of scaling?
Does this option result in visible artifacts when downscaling? Or what exactly are you seeing?

**Comment by maniak1349** [comment]
Can't say that those are really artifacts, but something definitely happening.

There's the original 1920x1080 image:
![pseudo rick and morty s01e01 - pilot 1080p h 265 mkv-00 00 20](https://cloud.githubusercontent.com/assets/2755776/15622448/7ada8a20-2471-11e6-91f4-958f73b8cba0.jpg)

There's what I see when I use `vo=opengl` while downscaling to 1280x720:
![opengl](https://cloud.githubusercontent.com/assets/2755776/15622472/a63f084e-2471-11e6-8cd1-613654fc15fe.jpg)

And there's what I see when I use `vo=opengl:sigmoid-upscaling` while downscaling to 1280x720:
![opengl_sigmoid](https://cloud.githubusercontent.com/assets/2755776/15622487/ca21e916-2471-11e6-92d2-c9423b935103.jpg)

Especially noticeable on sharp edges - lines are getting thinner and lighter.

**Comment by Hrxn** [comment]
Okay, I see what you mean.
I am with you, downscaling should not be affected by this option, I assume.

**Comment by haasn** [comment]
From the man page:

> This also implies `linear-scaling`.

**Comment by maniak1349** [comment]
> This also implies `linear-scaling`.

Thought that this will also be applied only for upsacles.

**Comment by haasn** [comment]
No, from the description of `linear-scaling`:

> Scale in linear light.

**Comment by maniak1349** [comment]
No, I meant that I thought that `linear-scaling` implied by `sigmoid-upscaling` will only affect the upscales and not just turned on for everything.
