### ISSUE TITLE
How to set the subtitle line spacing?

### ISSUE THREAD

**Issue by utapdio** [mpv-player/mpv#3185]
I found the SSA/ASS line spacing setting below:
`--ass-line-spacing=<value>`

But I want to customize the line spacing of my `.srt` subtitle files.
How can I do? I just didn't find any solution to solve it.

thanks for your help.

**Comment by maniak1349** [comment]
It should work for .srt subs too with `--ass-style-override` set to anything but `no`. (Default is `yes`).
