### ISSUE TITLE
--ytdl-raw-options cannot handle ':'

### ISSUE THREAD

**Issue by mozbugbox** [mpv-player/mpv#3188]
When passing `--proxy` option to youtube-dl, mpv spit out:
```
mpv --ytdl-raw-options=proxy=127.0.0.1:8080 'https://www.youtube.com/whatever....'
Expected '=' and a value.
Error parsing option ytdl-raw-options (option could not be parsed)
```
It seems that the `:` in proxy like `127.0.0.1:8080` stumbles mpv

**Comment by wiiaboo** [comment]
Because `:` is used as a parameter separator. You have to [escape that](https://mpv.io/manual/master/#escaping-spaces-and-other-special-characters).

**Comment by mozbugbox** [comment]
Thanks, quoting `:` does work well.

**Comment by swiniopas** [comment]
Can options  that don't take arguments be made to work too? For example --ytdl-raw-options=reverse-playlist would be useful but breaks currently.

**Comment by mozbugbox** [comment]
you have to append an extra `=` at the end for empty value:

`--ytdl-raw-options=playlist-reverse=`

**Comment by atommixz** [comment]
not work for me (in script)
```
proxy='http://proxy.on.hyperboria.name:8118'
mpv http://twitch.tv/monstercat --ytdl-raw-options=proxy=%`expr length "$proxy"`%"$proxy"
```
