### ISSUE TITLE
mp.suspend() not working?

### ISSUE THREAD

**Issue by hany** [mpv-player/mpv#3189]
Hi there, I'm trying to implement a LUA script that will allow the player to temporarily stop/suspend before playing the next item in a playlist. I've been looking at the [`mp.suspend()`](https://mpv.io/manual/stable/#lua-scripting-mp-suspend()) function as it seems to do what I want, however it's not working. Trying to call it in a script has no effect on the player at all. Further, increasing logging output shows absolutely nothing when that function is called.

Is there something I'm missing?

**Comment by wm4** [comment]
The default Lua event loop will sill call `mp.resume_all()` before waiting, which is probably what happens in your case.

The correct wait to make playback pause is setting the pause property.

**Comment by hany** [comment]
I'm actually looking to stop playback entirely before advancing to the next item on the playlist. Is there an alternative way of doing this?
