### ISSUE TITLE
Wayland VO hangs with dispatch in preinit function

### ISSUE THREAD

**Issue by duyhotan2000** [mpv-player/mpv#3192]
Hello,

I built MPV and run it on an embedded system with Wayland.
However, it hangs forever unless I remove the **wl_display_dispatch(wl->display.display);** line in preinit function of video/out/vo_wayland.c

Is this normal and does it impact to the processing of MPV?

Thank you!

**Comment by atomnuker** [comment]
Wayland implementation just got a rewrite, so closing this bug
