### ISSUE TITLE
--osc-fractions cli option?

### ISSUE THREAD

**Issue by phenest** [mpv-player/mpv#3200]
There is an --osd-fractions cli option but this doesn't affect the OSC.

The OSD disappears after a timeout, but the OSC can be kept visible using the mouse cursor.

Can that be added?

**Comment by ChrisK2** [comment]
Click on the left timestamp.

**Comment by wiiaboo** [comment]
--script-opts=osc-timems=yes or just timems=yes in lua-settings/osc.conf should do it.

**Comment by phenest** [comment]
That's it! Thanks.
