### ISSUE TITLE
[Question] - Is there a option for "remember window size and position"

### ISSUE THREAD

**Issue by paper9oll** [mpv-player/mpv#3201]
Hi All,

This is not actually an issue but i'm not too sure where to discuss.

I would like to know whether there is an options available for setting "remember window size and position", i have looked into the documentation but some options i don't quite understand hence anyone with better understanding knows?

Thanks You

**Comment by Hrxn** [comment]
Did you try `--geometry=...` and `--autofit=..`?
Ref. manual: 
https://mpv.io/manual/master/#options-geometry
https://mpv.io/manual/master/#options-autofit

For example, `--geometry=50%:50%` always centers the window in the middle of the screen.

**Comment by paper9oll** [comment]
@Hrxn thanks you for the help. its works.

**Comment by erik55** [comment]
Please read or search the documentation. It wasn’t difficult to find the option: `--save-position-on-quit`

**Comment by jupiter104** [comment]
Would be nice if mpv remembered for each file the size and position of the window by default.

**Comment by blueray453** [comment]
I have a script that remember different states:

```
local state_file = mp.command_native({"expand-path", "~~/player-state"})
local savefile

local function load_state()
    local loadfile = io.open(state_file, "r")
    if loadfile then
        local state_data = loadfile:read("*all")
        loadfile:close()

        local volume = state_data:match("volume=(%d+%.?%d*)")
        if volume then
            mp.set_property("volume", tonumber(volume))
        end

        local sid = state_data:match("sid=(%a+)")
        if sid then
            mp.set_property("sid", sid)
        end

        local loop_file = state_data:match("loop%-file=(%a+)")
        if loop_file then
            mp.set_property("loop-file", loop_file)
        end

        local osd_width = state_data:match("osd%-width=(%d+)")
        if osd_width then
            mp.set_property("osd-width", tonumber(osd_width))
        end

        local osd_height = state_data:match("osd%-height=(%d+)")
        if osd_height then
            mp.set_property("osd-height", tonumber(osd_height))
        end
    end
end

local function save_state()
    savefile = io.open(state_file, "w+")
    savefile:write(
        "volume=" .. mp.get_property("volume") .. "\n" ..
        "sid=" .. mp.get_property("sid") .. "\n" ..
        "loop-file=" .. mp.get_property("loop-file") .. "\n" ..
        "osd-width=" .. mp.get_property("osd-width") .. "\n" ..
        "osd-height=" .. mp.get_property("osd-height") .. "\n"
    )
    savefile:close()
end

load_state()

mp.observe_property("volume", "native", function(name, value)
    save_state()
end)

mp.observe_property("sid", "native", function(name, value)
    save_state()
end)

mp.observe_property("loop-file", "native", function(name, value)
    save_state()
end)

mp.observe_property("osd-width", "native", function(name, value)
    save_state()
end)

mp.observe_property("osd-height", "native", function(name, value)
    save_state()
end)
```

The thing is `osd-width` and `osd-height` is reset to the following value every-time i restart.

```
osd-width=960
osd-height=540
```

what can be done here? And also please give me some feedback about the script if something is wrong here or can be improved.

**Comment by blueray453** [comment]
I also worked on a gnome extension https://github.com/blueray453/restore-mpv-by-blueray453

if you are using gnome then this can be useful. 

**Disclaimer:** This is neither fully tested not production ready. Pull requests welcome.
