### ISSUE TITLE
Fix or Not Fix window size of mpv in runtime

### ISSUE THREAD

**Issue by joseguille9** [mpv-player/mpv#3203]
Hi,
I´m have a problem to play videos in mpv. I´m explain it with an example.

Example:
I´m have a playlist of three files:

Myvideo1.mp4 is 320x240
Myvideo2.mp4 is 640x360
Myvideo3.mp4 is 1280x720

When playing the files the window of mpv resize to fit the width and height for each video.

I´m need a feature in mpv, a property for set key binding in input.conf file for "fix" or "not fix" the current window size of mpv in runtime.

Anyway, Thanks for this great media palyer.

**Comment by maniak1349** [comment]
Related: #2301.

**Comment by Akemi** [comment]
there was a script for it. can't find it atm.
