### ISSUE TITLE
Crash : Assertion failed: (!queue->suspend_requested)

### ISSUE THREAD

**Issue by BurhanMughal** [mpv-player/mpv#3204]
Hi there,
I am facing a crash after closing mpv, Its frequency is 1/3.

This is what I got in the console: 

Assertion failed: (!queue->suspend_requested), function queue_dtor, file ../misc/dispatch.c, line 58.

OSX : 10.11.4
XCode:7.3
iOS: 9.3.2
Let me know if you need anything else.
thanks.

**Comment by wm4** [comment]
Do you have a full backtrace?

**Comment by BurhanMughal** [comment]
Hi wm4 no it just gives this error.

**Comment by wm4** [comment]
That's not enough to determine the cause.

**Comment by Akemi** [comment]
does this still happen?

**Comment by Akemi** [comment]
nothing we can do about like this.

**Comment by EzeKees** [comment]
Keep going, I get the same error.
#7169

**Comment by wm4** [comment]
That is't the same error.
