### ISSUE TITLE
--script silently ignores inputs

### ISSUE THREAD

**Issue by Profpatsch** [mpv-player/mpv#3211]
`--script` has the awkward behaviour that it silently ignores
- files that don’t end on `.lua` (even if valid lua files)
- lua files with syntactic errors
- non-existing files

Since they are specified on the command line, `mpv` should probably exit with an error pointing to the problematic script and what happened, because the user wants the file to be loaded or she wouldn’t have specified it explicitly.

**Comment by wm4** [comment]
>files that don’t end on .lua (even if valid lua files)

OK.

>lua files with syntactic errors

>non-existing files

Can't confirm.

**Comment by Hrxn** [comment]
Why shouldn't it ignore files that don't end with `.lua`?

**Comment by Profpatsch** [comment]
@Hrxn Because the user tells it to open that script file.

**Comment by Hrxn** [comment]
Open *a* script file? Open *any* script file? If it's not a Lua script, it's completely pointless.
Or, to rephrase my question: Why shouldn't a proper Lua file have its proper file extension?

**Comment by WildPenquin** [comment]
Well... I guess you could ask why should ANY file not have it's proper file extension. IMHO relying on the ending is a windows-y way of detecting a file type. I think about the ending as a way to make it easier for the USER to quickly see what type a file is - but it is still essentially just part of the file name, as any other part. At least it should give an error message, not fail silently!

**Comment by Profpatsch** [comment]
Failing silently is *never* a good option in my opinion.

**Comment by wm4** [comment]
It's actually a feature, not a bug: 99e498611e128dd894b7d943abadaa1b9c0ead45

Also you still haven't said anything about the latter two cases not actually happening.

**Comment by Profpatsch** [comment]
malformed lua throws an error indeed:

```
[tmp] 
[tmp] stack traceback:
[tmp] 	[C]: ?
[tmp] 	[C]: ?
[tmp] Lua error: tmp.lua:741: '=' expected near 'stuff'
```

but doesn’t abort.

A nonexisting file doesn’t print anything (not even a warning).
With `-v` you can find, buried in debug output:

    [cplayer] Can't load unknown script: nonexisting

**Comment by Hrxn** [comment]
BTW, how do you know that --
> [...], because the user wants the file to be loaded or she wouldn’t have specified it explicitly.

-- the user is a 'she'?

**Comment by Profpatsch** [comment]
How do I know the user is a ‘he’? But that’s a bit off-topic I think. ;)

**Comment by Hrxn** [comment]
Then why prefer one variant over the other? I this some sort of game? I mean, I see how one could construct and argument to point out that this has been used wrong historically, but that is not an improvement.

**Comment by Profpatsch** [comment]
> Then why prefer one variant over the other?

I just use whichever one I like and what gets people thinking. Which apparently works. :p 
So no particular reason, and I really don’t see the relevance for the issue at hand.

**Comment by Hrxn** [comment]
For no reason? So just for shits and giggles? I already suspected that this seems to be a pretty pointless exercise, but I didn't thought it was *that* pointless.
And don't worry, I am thinking all the time..

**Comment by Profpatsch** [comment]
> And don't worry, I am thinking all the time..

If you did, this discussion wouldn’t happen here, but e.g. on Twitter (@Profpatsch).
