### ISSUE TITLE
Add a way to show technical information of a file or stream playing

### ISSUE THREAD

**Issue by WildPenquin** [mpv-player/mpv#3212]
Currently there is no easy way of displaying technical information for a file or stream playing, such as refresh rate, bit rate, resolution, encoding format, number of video/audio/subtitle streams etc.; the best I could find is --msg-level-all=v, and looking for the information in the huge amount of text that is output - and I'm not even sure that all information that might be usefull for the user is there.

IIRC mplayer used to have a --identify -switch - perhaps such a switch could be usefull? Or a new keyboard command to output the information?

Of course there are third party utilities that can be usefull (like mediainfo), but they can not be used for streams. That alone could make this feature usefull for mpv.

```
$ mpv --version
mpv git-026b75e (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Jun  4 16:43:54 EEST 2016
ffmpeg library versions:
   libavutil       55.17.103
   libavcodec      57.24.102
   libavformat     57.25.100
   libswscale      4.0.100
   libavfilter     6.31.100
   libswresample   2.0.101
ffmpeg version: 3.0.2
```

**Comment by Cpuroast** [comment]
See https://github.com/Argon-/mpv-stats

**Comment by Cpuroast** [comment]
You'll see that this lua script does pretty exactly what you want :)

**Comment by WildPenquin** [comment]
Thanks! It really does seem to work =)

**Comment by victoriastuart** [comment]
Now part of mpv: https://mpv.io/manual/stable/#stats
