### ISSUE TITLE
Fail to save video position on network share disconnect

### ISSUE THREAD

**Issue by ninjamode** [mpv-player/mpv#3213]
When playing a video file on a (SMB) network share, mpv just closes and fails to save to file position with `--save-position-on-quit` when the share is disconnected for whatever reason. Log says mpv thinks the end of the file has been reached, even though it's actually a network error.

I'm using mpv 0.17.0 with ffmpeg 3.0.2 on OS X 10.11.5. I am not sure whether this is a Mac or SMB specific problem. To reproduce, open a file on a Network share, disable wifi, wait for os x to disconnect the share while the video still plays. Mpv will then quit without saving the position.

```
AV: 00:17:09 / 00:23:55 (71%) A-V:  0.000 Cache:  0s+0KB


Exiting... (End of file)
fatal: Unable to read current working directory: No such file or directory 
```

I know that mpv wont save the position if it reaches the end of a file, however here there is also the additional information that the video is only 71% played available. Maybe this information can be used to determine when to save the playback position?

**Comment by wm4** [comment]
Nothing that can be done about it, but you should be able to use --keep-open to mitigate it. If not, write a custom script that takes care of it. (There's a command to write the watch later position, and it will succeed even on EOF, if it's executed before the player terminates the file.)

>however here there is also the additional information that the video is only 71% played available. Maybe this information can be used to determine when to save the playback position?

Generally not.
