### ISSUE TITLE
cache problem 

### ISSUE THREAD

**Issue by nthrev** [mpv-player/mpv#3217]
when you piped video contant to mpv with flag --cache , he can't seek right or left (cache don't work) 
For example : `openssl enc -aes-128-ofb -d -in encrypted.bin -iv a2b050be9463 -K 6ba62eb7bb2ccace -nopad|mplayer -cache 8000 - `
will work excelent 
`openssl enc -aes-128-ofb -d -in encrypted.bin -iv a2b050be9463 -K 6ba62eb7bb2ccace -nopad|mpv --cache=8000 - ` 
will not work...

**Comment by wm4** [comment]
Add `--force-seekable`.
