### ISSUE TITLE
mouse positionning "à la ffplay"

### ISSUE THREAD

**Issue by clu--** [mpv-player/mpv#3218]
Hi every one,
  i'm new to mpv and already liked the configurability while still keeping it lighter and faster than most other players (well not compared to ffply but then it was for testing and lacks many features and configurability to keep using it as a daily player.. though i did for more than a year till i found, now, mpv :-).
And then i miss a particular hability of ffplay : positioning in the timeline of the media playing by clicking with the mouse somewhere on the window/screen  showing it : then, the player jumps directly to that position in the media, that is if i clicked at 10% of the left edge of the window/screen it'd go to 10% of the media/stream.
Now, how would one get that with mpv? I did not find clues in the config files so my guess is that there ought to be either in scipts of in the code (and i'm no coder, sorry :-) .
So, any kind mind to light my little candle?
Thnaks a lot in advance for your patience
Zui
20160606

**Comment by wm4** [comment]
The OSC with its clickable seek bar doesn't cut it?

**Comment by clu--** [comment]
Thank you for your quick reply and here some of my remarks:
1. I'm more of a kbd person than a GUI one so when using the mouse i only seek *very* simple actions :
   in the case of the OSC you have to be precise on where you click to target the line and see it work
   with the more *intuitive* way i used under ffplay, i just clicked roughly on the screen to get the desired result.
   I'd even say it would be great on those tabletoidal object i see every-ware nowadays (used with careless fingers).
   Just try it (ffply on a video) for a while and see what it feels, then compare positionning with the OSC on mpv.

2. in the case of mpv, I simply deactivated in it altogether the config as i got annoyed seeing it appearing on the
   screen anytime a brise pushed the mouse-thing. And didn't find a way to avoid that behavior in the conf files.

3. now, if you can get the OSC to have similar behavior then i sure will comply :
   - non obstrusive, only visible when required (a hotkey or specific hot-mouse?)
   - still having it (transparently/non visible) covering the whole real-estate of the window (or FS) showing the media
       and yet its whole surface being click-able as to be used as the cursor to position in the media...
   then alrighty!

to everyone doubting the addictive effect, please give it a try and then if someone can figure out a way to have it
running in mpv (and i don't ask for any visual aid... well we always have OSD to ask for coordinates in case of need).

so? pleeeeease, someone?

thank you for your kind understanding and have a good day
Zui
20160607
----- V. Lang <notifications@github.com> wrote :

**Comment by qmega** [comment]
`~/.mpv/scripts/ffplay-seek.lua`:
```lua
mp.add_key_binding("MOUSE_BTN0", function()
    local width, height = mp.get_osd_size()
    local x, y = mp.get_mouse_pos()
    mp.commandv("seek", x / width * 100, "absolute-percent")
    -- Or, for hr-seek (slower):
    --mp.commandv("seek", x / width * 100, "absolute-percent+exact")
    -- If you want to see position on OSD:
    --mp.commandv("osd-msg-bar", "seek", x / width * 100, "absolute-percent")
    -- or just "osd-bar" or "osd-msg"
end)
```

**Comment by clu--** [comment]
Wow  Philip!

  not only did you answer my request in detail, but you also did show me the way of freedom via SIMPLE Lua scripts... GREAT!

  now i can learn lua further, knowing i'll have a nice playground to experiment beyond my prior expectations.

  muito obrigado
Zui
20160607

PS: and i guess now ffplay will become, like many other before, a good old memory :-)
