### ISSUE TITLE
Cannot seek in buffered audio stream

### ISSUE THREAD

**Issue by muchweb** [mpv-player/mpv#3220]
1. Open internet radio stream
2. Pause
3. Wait
4. Resume
5. Seek forward

```
A: 00:00:10 Cache: 10s+568KB
Can't seek in this file.
```

But it is still possible to fast-forward by speeding up playback.

**Comment by wm4** [comment]
`--force-seekable`

**Comment by muchweb** [comment]
Works with flag.
