### ISSUE TITLE
Can I use this software in my homemade OpenSUSE distribution?

### ISSUE THREAD

**Issue by fujita-nozomi** [mpv-player/mpv#3223]
but not GPL/LGPL is CC:BY-NC-SA 4.0 int'l
because in my homemade OpenSUSE distribution had something
"Copyrighted content"(not software just some wallpaper，Music File and made by myself musicbox software(but the music file in my musicbox software is Copyrighted content) )

i will not Commercial use my distribution
and also i hope another people don't Commercial use my distribution

(In some countries, "if you don't commercial use then is not tort" and that's why i want to using CC:BY-NC-SA 4.0 int'l)

**Comment by wm4** [comment]
mpv is under GPL 2 or later. Other than that, we're not a law firm and can't offer legal advice.
