### ISSUE TITLE
Option af: rubberband doesn't exist

### ISSUE THREAD

**Issue by akhenig** [mpv-player/mpv#3231]
When I try to run af=rubberband, it tells me that "option: af rubberband doesn't exist", although rubberband is installed. I am installing mpv with homebrew. Is there any build option that I need to use to have rubberband be compiled in?

**Comment by Cpuroast** [comment]
mpv --af=rubberband somefile.ext

**Comment by akhenig** [comment]
Yes, I am doing it through the config file. When I try to play a file, this is what I get: "Option af: rubberband doesn't exist.
Error parsing option af (option could not be parsed)
~/.config/mpv/mpv.conf:2: setting option af='rubberband' failed."

**Comment by wm4** [comment]
You need to compile with librubberband.

Probably not worth it.

**Comment by akhenig** [comment]
How do I compile with librubberband? Is there an easy way with homebrew?

**Comment by Argon-** [comment]
Add this line to your homebrew formula:

    depends_on "rubberband" => :optional

And install using `--with-rubberband`. Not tested but should work.

**Comment by akhenig** [comment]
Thanks, although I'm not satisfied with the quality of rubberband. Do you have any tips for the best scaletempo settings for speeding up? Chrome does it quite well with youtube videos for example.

**Comment by SteveJobzniak** [comment]
@akhenig Well, for what it's worth, Rubberband is the lowest evil of them all.

```bash
# Audio filter modes.
# By default, audio-pitch-correction is set to "yes", which automatically adds
# the "scaletempo" filter to change speed without affecting pitch. However,
# it leads to incredibly horrible, choppy sound. It's kind of the same sound
# as VLC's speed adjustment, and it sounds a lot better than VLC, but still
# sounds like garbage. So disable it.
audio-pitch-correction=no
# Instead, enable the Rubberband filter, with stereo-coherent phase mode.
# It has the best audio quality, but uses quite a bit of CPU if the stretch
# is very intense, and can lead to framedrops. The CPU usage goes up ~5-15%
# at all times even when this filter is at "no change". But that's ok.
# The ability to change the speed and have non-creepy audio is worth it.
# And it doesn't interfere with the ability to set rapid loop points.
# Summary:
# - VLC's speed adjustment with pitch correction: Even worse stutter than mpv.
# - Regular mpv with pitch correction: Disgusting stutter.
# - Regular mpv without pitch correction: Creepy downpitching.
# - Rubberband (in stereo mode): Slightly more CPU, but the audio stays perfect.
af=rubberband=channels=together
```

**Comment by SteveJobzniak** [comment]
@akhenig As for Rubberband's quality: It is great if you set it to stereo mode so that it preserves phase. Which is what I do above with "channels=together".

And you can listen to some demos on the official site here: http://breakfastquay.com/rubberband/examples.html

Definitely great quality.

There are a few issues with rubberband in mpv, related to slight desync between audio and video (I guess mpv doesn't properly read the rubberband library's "latency" info, or something), but how often do you slow down or speed up and by how much? For me it's rare. I just want to have the ability and not have horrible audio when it happens. So I chose Rubberband.

**Comment by wm4** [comment]
>I guess mpv doesn't properly read the rubberband library's "latency" info, or something (which it reports super accurately so it's just a matter of mpv reading it properly to fix that)).

Last I checked the library didn't have any.

**Comment by SteveJobzniak** [comment]
@wm4 Alright, I created a ticket regarding it, in case it's news to mpv: https://github.com/mpv-player/mpv/issues/3928
