### ISSUE TITLE
Transform a square video to 16:9

### ISSUE THREAD

**Issue by ManuCart** [mpv-player/mpv#3232]
Hello
How to transform a video 500x500px to 640x480px with black border

**Comment by rossy** [comment]
I'm not entirely sure what you mean, but you can modify the video aspect ratio with ``--video-aspect=4:3`` or ``--video-aspect=16:9``.

**Comment by maniak1349** [comment]
> How to transform a video 500x500px to 640x480px with black border

Sounds like `--geometry=640x480` to me.
