### ISSUE TITLE
Problem with SDL software video output

### ISSUE THREAD

**Issue by VittGam** [mpv-player/mpv#3234]
Hello,

Using mpv 0.17.0 on aarch64 (ODROID-C2 with Arch Linux ARM) and the SDL2 software renderer, I'm getting weird video output.

![screenshot at 2016-06-09 18 46 41](https://cloud.githubusercontent.com/assets/615188/15938597/19157aae-2e74-11e6-8797-fe42df2d6798.png)

ffplay (which uses SDL1) works fine.

Before you ask... The platform I'm using doesn't support OpenGL in hardware, and OpenGLES has still a lot of problems as of now and mpv doesn't even start with `--vo=opengl:backend=x11egl:es`, so I'm stuck with software rendering.

Cheers,
Vittorio

**Comment by wm4** [comment]
Are you sure this isn't just a SDL bug? Also I don't think this will be much faster than --vo=x11.

A EGL backend could be added, just needs someone who writes the code for it. (Although that would be sort of a fullscreen mode, unless x11egl operation can be fixed.)

**Comment by VittGam** [comment]
`--vo=x11` is slow and drops a lot of frames on this platform, even at 720x404... It's worse than llvmpipe-accelerated opengl!

By the way I just workarounded this bug with `--vf=format=bgra`.

So the full working command line for me is:
`SDL_RENDER_DRIVER=software mpv --vo=sdl:sw --vf=format=bgra file.mkv`

I'm not sure if I should close this bug or not. Is this bgr24 rendering problem a bug of mpv or SDL2? How could I check?

Regarding x11egl, to use OpenGLES in general on this platform one needs to use a kind-of-broken Mali-X11 driver that makes GLES sort-of working (at least the demo es2gears_x11 works) but then the rest of 2D X11 gets excruciatingly slow. I guess that the proper glue for the Mali-450 should be written into xf86-video-fbturbo to have things working properly and fast. So for now it'd be a no-go for me, and I'm happy with the now-working SDL2 software output.

What could be interesting would be a "plain" EGL/OpenGLES backend working outside X11 (eg. with the Mali-fbdev libraries; part of the method Kodi is using to be fully accelerated on this hardware); and without using the Direct Rendering Manager, which is not supported by the display driver. But at the moment I don't have time to look at it...

**Comment by divVerent** [comment]
I'll look at this tomorrow. I suspect some things, but need to look at the
screenshot more closely (with software) to be sure.

Could it be that sdl2 isn't using hardware scaling but software output?
This so looks like a typical SW renderer bug.

**Comment by VittGam** [comment]
Well, on this platform I need to use the software render backend of SDL, so it might just be a bug in the SDL software scaler.

**Comment by divVerent** [comment]
Some more things BTW:

- can you post your output of "xdpyinfo"?
- does changing your color depth to one of 16, 24, 32 bpp "fix" the issue?
- try the following things, one by one:
  SDL_RENDER_DRIVER=software mpv ...
  SDL_RENDER_DRIVER=opengles mpv ...
  SDL_RENDER_DRIVER=opengles2 mpv ...
  SDL_RENDER_OPENGL_SHADERS=0 mpv ...
  SDL_RENDER_SCALE_QUALITY=0 mpv ...
  Does any of these help? Some will not work at all, that is okay.

**Comment by divVerent** [comment]
Oh, and that changing the input pixel format helps is good to know. Will
investigate that too to see if it is a bug in mpv then.

**Comment by divVerent** [comment]
I pushed a possible fix to branch sdl2-pixelformats. Can you try?

I.e. do:

git fetch
git checkout sdl2-pixelformats

And recompile mpv.

**Comment by VittGam** [comment]
Compiling now. Will you still need the debug info if the fix works?

**Comment by wm4** [comment]
@divVerent: actually the ffmpeg/mpv version of RGBX is RGB0, so you could accept these formats too.

**Comment by VittGam** [comment]
The build fails because commit https://github.com/mpv-player/mpv/commit/3a015b9ec7186a41c91f6d0a565aea237806c8f4 removes support for "useless old" RGB formats. I'd revert that commit, since there are platforms where direct software rendering is faster than convoluted indirect software rendering through OpenGL MESA/llvmpipe software implementation...

**Comment by wm4** [comment]
What makes you think systems like this are the main target of mpv?

**Comment by VittGam** [comment]
Nothing. But I fail to see why they shouldn't be supported more or less properly just because a few lines of working code were removed because they were considered "old"...

**Comment by divVerent** [comment]
Odd, it built for me. Anyway, feel free to remove the RGB565 formats, they
don't matter much anyway.

**Comment by VittGam** [comment]
Nope, I've fixed it. Here: https://github.com/VittGam/mpv/commits/sdl2-pixelformats

**Comment by divVerent** [comment]
Oh, it was just BGR565 anyway. Even more reason to kill it.

**Comment by wm4** [comment]
>But I fail to see why they shouldn't be supported more or less properly just because a few lines of working code were removed because they were considered "old"...

Many of these formats were redundant and ill-defined. I don't mind adding one or two of those formats if it provably increases performance on some devices, but I won't add them back just because.

**Comment by wm4** [comment]
PS: I know that odoroid-c2 can play 720p in realtime with GL, so this whole thing seems quite ridiculous to me.

If you really want a small computer with good Linux software support, get a NUC instead. These ARM devices are absolutely pathetic, even if they bait buyers with "good" multimedia specs.

**Comment by divVerent** [comment]
In this case it was a mistake from me. I had RGB565 so I added BGR565 for
no real reason other than consistency and apparently must have forgotten to
test compile that change too.

In practice, I doubt much hardware uses BGR565, it is an oddball format.
Does X11 even support it?

**Comment by VittGam** [comment]
@wm4: Maybe the odroid c2 can on Ubuntu, but on Arch it doesn't work (mpv fails with an error when trying to use gles) and also when enabling the accelerated X11 driver, the rest of desktop environment (MATE!) gets excruciatingly slow. Even the terminal lags! So that's a big no-go for me, and I'm happy with software rendering.

Intel is a no-go for me, too; sorry.

Anyway, I've got a full working fix in my branch at https://github.com/VittGam/mpv/tree/sdl2-pixelformats

**Comment by wm4** [comment]
Reverting that commit is explicitly rejected.

**Comment by divVerent** [comment]
Why close? I think that revert is unrelated.

Can you try he current version of my branch? It does not revert said commit and has the compile error fixed another way. Sorry for the confusion.

**Comment by VittGam** [comment]
@divVerent sorry. I guess it'll work since it's the same as my commit except for the "deprecated" formats, and my commit is working. I'll be able to test it tomorrow though...

**Comment by divVerent** [comment]
Okay, considering this fixed then.
