### ISSUE TITLE
High CPU usage with 60 fps video on Gnome 3.20 + Wayland

### ISSUE THREAD

**Issue by ignisf** [mpv-player/mpv#3238]
Hello,

I am experiencing high CPU load when playing videos with a 60fps frame rate in Gnome 3.20 on Wayland.

Environment info: https://gist.github.com/ignisf/798cf1ac3f504137cd1b6b3f098ba6c0

Playback log: https://gist.github.com/ignisf/daf860c62f0942b519f5c6836973436c

CPU Load table:

| Video | hwdec=vaapi | Software decoding | hwdec=vaapi + xorg |
| --- | ---: | ---: | ---: |
| [30fps](http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4) | ~5% | 40-50% | ~4% |
| [60fps](http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4) | ~100% | 150-160% | ~7% |

The issue seems to be present in Weston 1.11.0, too.

**Comment by wm4** [comment]
My bet is that the x11 backend works fine? (``--vo=opengl:backend=x11``)

**Comment by wm4** [comment]
Also, can you try with mpv git master?

**Comment by ignisf** [comment]
sure, I'll try both, though I consider the first only a workaround

**Comment by ignisf** [comment]
No significant difference from the results above on mpv git-de4c74e with just `hwdec=vaapi`.

Running it with `-hwdec=vaapi -vo=opengl:backend=x11` yields a CPU use to the ordder of 50-70% BUT I noticed that VAAPI does not get initialised:

```
[vo/opengl] Setting option 'backend' = 'x11' (flags = 0)
[vo/opengl] Initializing OpenGL backend 'x11'
[vo/opengl/x11] X11 opening display: :0
[vo/opengl/x11] X11 running at 1920x1080 (":0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Display 0 (XWAYLAND0): [0, 0, 1920, 1080] @ 59.962844 FPS
[vo/opengl/x11] Current display FPS: 59.962844
[vo/opengl] GLX chose FB config with ID 0xd45911b0
[vo/opengl] GLX chose visual with ID 0x1a0
[vo/opengl] Creating OpenGL 3.3 context...
[vo/opengl] GL_VERSION='3.3 (Core Profile) Mesa 11.2.2'
[vo/opengl] Detected desktop OpenGL 3.3.
[vo/opengl] GL_VENDOR='Intel Open Source Technology Center'
[vo/opengl] GL_RENDERER='Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) '
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='3.30'
[vo/opengl] Loaded extension GLX_SGI_video_sync.
[vo/opengl] Loaded extension GL_ARB_debug_output.
[vo/opengl] swap_control extension missing.
[vo/opengl] Reported display depth: R=8, G=8, B=8
[vo/opengl] 16 bit texture depth: 16.
[vo/opengl] Testing FBO format 0x805b
[vo/opengl] Create FBO: 16x16 (16x16)
[vo/opengl] Using FBO format 0x805b.
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Loading hwdec driver 'vaapi-egl'
[vo/opengl] Loading failed.
[vo/opengl] Loading hwdec driver 'vaapi-glx'
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[vo/opengl] Loading failed.
[vo/opengl] Assuming 59.962844 FPS for display sync.
[vd] Container reported FPS: 60.000000
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd] Opening video decoder lavc:h264
[vd] Probing 'vaapi'...
[vo/opengl] Loading hwdec driver 'vaapi-egl'
[vo/opengl] Loading failed.
[vo/opengl] Loading hwdec driver 'vaapi-glx'
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
[vo/opengl] Loading failed.
[vd] VO does not support requested hardware decoder, or loading it failed.
[vd] Using software decoding.
```

**Comment by ignisf** [comment]
Could you give me some pointers how does one profile mpv to pinpoint such an issue?

**Comment by atomnuker** [comment]
Use perf
Yes, the issue is known, it has something to do with the polling in video/out/wayland_common. Hadn't had much time to fix it, linkmauve1 said he'd look into it whenever he has the time.

**Comment by ignisf** [comment]
> something to do with the polling in video/out

running `perf` points this way

**Comment by atomnuker** [comment]
Fixed in commit e11a20a8122
If someone could close this that'd be nice.

**Comment by ignisf** [comment]
Will do

**Comment by ignisf** [comment]
Can confirm 6-10% CPU usage with the 60 fps video on Wayland. :heart:

**Comment by ignisf** [comment]
With this I think MPV is the first video player that works natively on Wayland while providing VA-API decoding acceleration.
