### ISSUE TITLE
mpv not automatically switching to discrete graphics processor on El Capitan

### ISSUE THREAD

**Issue by twofoureight** [mpv-player/mpv#3242]
Playback was smoother after I manually enabled the discrete graphics processor. 

Does this happen by purpose?

**Comment by pigoz** [comment]
Yes, we support automatic graphics switching, but don't require the discrete GPU. What kind of machine do you have? Was this not a problem on Yosemite?

**Comment by twofoureight** [comment]
I have a rMBP mid 2015, Radeon R9 M370X. I never used mpv on Yosemite.

**Comment by Cpuroast** [comment]
In the past mpv did trigger a GPU switch to the discrete one, now it doesn't, in my case on my mid-2012 MBP, I simply disable automatic graphics switching in system preferences, so it never uses the Intel one.

**Comment by AirPort** [comment]
I may be wrong, but AFAIK, unless the dGPU is explicitly requested by the program, the OS apply an heurstic based on the resource requests related to the GPUs' power. The same versions of mpv and Os X used to trigger the GPU switch on my old machine, with Intel HD Graphics and nVidia 330M, but not on the new one, Iris Pro and R9 M370X (not a big problem in my case though, the Iris is able to play pretty much everything smooth with opengl-hq, antiring and an icc-profile).

**Comment by Akemi** [comment]
this isn't really a bug. it just uses the GPU that works completely. so in your case the integrated GPU. the only thing that could be added, without breaking the current behaviour, is adding an option for forcing the dedicated GPU. though i am not a too big fan of this.

**Comment by Akemi** [comment]
feel free to [test](https://github.com/Akemi/mpv/commit/5264f9bd9f0460fa85518146c15bb380db586739) above commit. `--force-dedicated-gpu` should always force the dedicated GPU. since i can't test it some feedback would be nice.
