### ISSUE TITLE
mpv causes X to misbehave

### ISSUE THREAD

**Issue by alex3kov** [mpv-player/mpv#3248]
This started happening after recent upgrade which included mpv. I'm not _entirely_ sure mpv is the root cause, but it sure looks that way - tell me what you think.  
Right after I log in X/Openbox, everything works okay. When I start playing some video with mpv, X starts to refresh screen only on mouse movement. For example, playing youtube video in Firefox displays only 1 frame, but if I move the cursor continuously video plays (not too smoothly); if I type several letters into terminal it remains empty, but when I move the cursor typed letters appear and so on. This behaviour continues even after exiting mpv, until reboot. I haven't been able to get this behaviour without running mpv.  
Here's a line in mpv logs that appears on every cursor movement (moving mouse slowly for about 5 cm on the screen makes for several dozens of lines in the log:
```
[cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
```
Software:  
Arch Linux x64  
xorg-server 1.18.3  
Openbox 3.6.1  
`mpv --version`  
[cplayer] Setting option 'version' = '' (flags = 8)
mpv 0.17.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Wed Apr 27 15:26:51 CEST 2016
ffmpeg library versions:
   libavutil       55.17.103
   libavcodec      57.24.102
   libavformat     57.25.100
   libswscale      4.0.100
   libavfilter     6.31.100
   libswresample   2.0.101
ffmpeg version: 3.0.2  
mpv config:
```
[default]
vo=opengl
alang=en,eng
slang=en,eng
aid=3
ytdl-format=18
cache=80000
log-file=/home/username/mpv.log
msg-level=all=v
```
[mpv.txt](https://github.com/mpv-player/mpv/files/313297/mpv.txt)

**Comment by haasn** [comment]
If it happens after mpv stops running it's not our bug. I'd blame your graphics drivers.

**Comment by alex3kov** [comment]
@haasn Indeed it was graphics drivers. Uninstalling xf86-video-intel and using modesetting instead solved it.
