### ISSUE TITLE
DTS and AC3 passtrought on spdif generate noise at output

### ISSUE THREAD

**Issue by damien7851** [mpv-player/mpv#3250]
I play DTS and AC3 video file on my cubietruck.
spdif passtrougth is ok with very old mpv and mplayer but with mpv 0.16 my amp emit only noise.
in log i seen that the sound is encoded 32bits float. on my old mpv i have a "?" for output it's strange.

**Comment by damien7851** [comment]
what information do you need?

**Comment by wm4** [comment]
All of it.

**Comment by kevmitch** [comment]
* log
* what os
* what version is "old"?
just for starters

**Comment by damien7851** [comment]
I made log, but I do not just give them for now.
os is debian jessie armbian build.
kernel is 3.4.112. armhf with buggy sound driver or miss-implemented.
with mpv 0.6 passtrougth is ok but where is error in log ( alsa lib) 
sound is not ok with mpv 0.16.
I think this is a new feature or enhancement that prevents operation. may be that the implementation of its mpv requires adaptation to bypass the driver's problem until this is corrected.

**Comment by damien7851** [comment]
I find the function in which the driver can switch to pass through :
it's "set_fmt" wich is a part of snd_soc_dai_ops struct a part of alsa.
but i not find how alsa call this function...

**Comment by haasn** [comment]
Since it was working in the past, you could start by figuring out which commit caused it to stop working.

**Comment by damien7851** [comment]
I think, but I have not tested this produced is the introduction of the "--audio-SPDIF".
I do not have the time or expertise to set up a cross toolchain for mpv it's too complicated.
Im able to test binaries from debian but no version between 0.6.2 and 0.14.0 version 0.16 is compiled by an member of armbian team.

**Comment by wm4** [comment]
Well, none of us even has a cubietruck device.

**Comment by damien7851** [comment]
That does not surprise me. I could test myself if it helps me put the cross toolchain up.
and I need a starting point in the code

**Comment by wm4** [comment]
All ALSA-specific code is in `audio/ou/ao_alsa.c`.

It's possible that this problem is caused by b2d058ef00513d52734c2b61e7a8be7b51fc01dd.

**Comment by damien7851** [comment]
I look at the code and there is a major change.
macro AF_FORMAT_IS_IEC61937 is replaced by af_fmt_is_spdif.
return of this function change notably the opening of sound device.
if return is true device string modify by mpv else not.

**Comment by damien7851** [comment]
log output :


[log0.16.txt](https://github.com/mpv-player/mpv/files/318866/log0.16.txt)
[log0.16_2.txt](https://github.com/mpv-player/mpv/files/318865/log0.16_2.txt)
[logok.txt](https://github.com/mpv-player/mpv/files/318867/logok.txt)

sound is ok with logok.txt

**Comment by wm4** [comment]
In the first two logs it outputs PCM via ALSA. If you don't hear anything, your audio setup or drivers are broken.

**Comment by damien7851** [comment]
I hear noise. 
driver dot not have default fall back to iec958 and i think that pcm is open as simple pcm but with dts stream.

**Comment by damien7851** [comment]
I'm not on my amp supporting the 32bit pcm.

it only supports 24bit 192khz. how i force this format?

**Comment by wm4** [comment]
By fixing the damn kernel driver.

**Comment by damien7851** [comment]
is not possible to use asound.conf?

where is aes param in code?

2016-06-17 13:50 GMT+02:00 V. Lang <notifications@github.com>:

**Comment by LennyLip** [comment]
+1 same issue (armbian on cubietruck, mpv from https://www.armbian.com/cubietruck/ with legacy kernel), 

```
$mpv
[cplayer] mpv 0.14.0 
[cplayer] Setting option 'ao' = 'alsa:device=[hw:1,0]' (flags = 4)
[cplayer] Setting option 'af-add' = 'lavcac3enc=bitrate=640' (flags = 4)
[cplayer] Setting option 'audio-spdif' = 'ac3,dts,dts-hd' (flags = 4)
```

I hear noise, when forward video. But it starts with silent.

**Comment by CounterPillow** [comment]
@LennyLip ancient mpv versions aren't supported, and this is a bug in the driver, not in mpv, so I'm not sure what you're +1ing here for.

**Comment by LennyLip** [comment]
@CounterPillow thanks, what driver a you talking for? mpd (stereo) works perfectly...
