### ISSUE TITLE
video playback glitching out with hwdec "d3d11va" and/or "auto"

### ISSUE THREAD

**Issue by dumpsters** [mpv-player/mpv#3255]
So I just updated my mpv and video playback seems to be glitching out when using d3d11va/auto, to be honest I've never used anything other than software or dxva2-copy til now.

**Platform:**
Windows 10 Enterprise Build 10586.318

**Driver:**
Radeon Crimson 16.6.1 (VGA: R7 260x)

**mpv version tested:**
latest from https://bitbucket.org/rorgoroth/mpv-for-windows/downloads (_mpv-latest-Win64.zip_) as of today/when I'm posting this

**MPC-HC version tested:**
latest from https://mpc-hc.org/downloads/ ("_v1.7.10 which was compiled from d911f14_") x64

**Two .webm files and one image showing off the problem:**
https://u.pomf.is/dazvpi.webm
https://u.pomf.is/cbejfy.webm (with stats)
![glitched d3d11va](https://cloud.githubusercontent.com/assets/12140220/16085221/b3e39f08-32f1-11e6-8055-30296d3a3eb8.png)

**Same file running on MPC-HC (unchanged configs):**
![mpc-hc](https://cloud.githubusercontent.com/assets/12140220/16085166/90f88a6c-32f1-11e6-8a56-7aad03d76d18.png)

**DXVA Checker:**
![dxva](https://cloud.githubusercontent.com/assets/12140220/16085772/948441f6-32f3-11e6-8777-05d3a1047573.png)

**hwdec options I tried and their results:**
- d3d11va -> glitched like in the examples
- d3d11va-copy -> (no glitch)
- dxva2 -> seems to work fine from what I've seen (no glitch)
- auto -> goes to d3d11va (glitched)
- auto-copy -> goes to dxva2-copy (no glitch)

**relevant mpv.conf:**

```
vo=opengl-hq:backend=angle:swapinterval=1:icc-profile="~~/monitor-profiles/SM633NW.icm":icc-contrast=0:blend-subtitles:deband:deband-grain=0:scale=ewa_lanczossharp:cscale=ewa_lanczossharp:tscale=oversample
hwdec=auto
video-sync=display-resample
framedrop=no

ontop=yes
geometry=50%:50%
autofit-larger=960x600
keep-open
no-border

ad-lavc-downmix=yes
audio-channels=mono
```

**output log from one of the video files:**
[output.txt](https://github.com/mpv-player/mpv/files/316441/output.txt)

Let me know if you need any more informations. As a side note, I would love to know how to properly use the monitor profile's constrast and how to properly downsample to mono sound.

**Comment by wm4** [comment]
I assume `--hwdec=auto-copy` works? What about a simple `--vo=opengl`?

**Comment by dumpsters** [comment]
`--hwdec=auto-copy` sets it to dxva2-copy.
What do you mean by simple `--vo-opengl`? just that without anything else in the config file or same config file but opengl instead of opengl-hq?

Also I forgot to mention in the OP that d3d11va-copy seems to work, I don't know the differences between that and d3d11va or anything but just thought I should say.
![d3d11va-copy](https://cloud.githubusercontent.com/assets/12140220/16088157/203691ba-32fc-11e6-8f47-cdce37822e80.png)

**Comment by wm4** [comment]
`d3d11va` is the mode `--hwdec=auto` selects in your case. Can you test `--no-config --vo=opengl --hwdec=d3d11va` ?

**Comment by dumpsters** [comment]
Here's how it plays with those parameters:
https://u.pomf.is/zpivjv.webm

Also I updated the "hwdec options I tried and their results" section in the OP.

**Comment by wm4** [comment]
What happens if run with `--hwdec=auto --vf=d3d11vpp:interlaced-only=no`?

**Comment by dumpsters** [comment]
https://u.pomf.is/izuiqi.webm

**Comment by wm4** [comment]
Does the branch `d3d_copy_texture` help?

**Comment by dumpsters** [comment]
Sorry but I can't compile stuff here

**Comment by dumpsters** [comment]
Using https://bitbucket.org/rorgoroth/mpv-for-windows/downloads/mpv64__d3d_copy_texture.7z

`mpv "Game.of.Thrones.S06E09.1080p.HDTV.x264-BATV.mkv" --no-config --vo=opengl-hq --hwdec=d3d11va`

```
VO does not support requested hardware decoder, or loading it failed.
AO: [wasapi] 44100Hz stereo 2ch float
Using software decoding.
```

with d3d11va-copy mpv crashes.

**Comment by wm4** [comment]
The crash is a small oversight. I fixed it and force-pushed the branch.

Not sure why the d3d11va mode doesn't work for you. It does for me.

**Comment by dumpsters** [comment]
I noticed the same glitch happening on youtube and oddshot.tv sometimes so maybe it's not an mpv issue but a driver/os one?

**Comment by vishnunaini** [comment]
I Can confirm this behaviour.

I am seeing H.264 videos glitching when --hwdec auto is passed to mpv in windows.

**Comment by rossy** [comment]
Possibly related Chrome issue (see the attached WebM): http://crbug.com/623029

It seems like Chrome are solving this by manually blacklisting AMD drivers from using external NV12 texture.

**Comment by haasn** [comment]
How about we manually blacklist AMD drivers?

**Comment by wm4** [comment]
That issue just says that they reverted the default. Looking forward to seeing how they solve it and it they find the real cause. (Surely they know how to contact the AMD driver team directly.)

**Comment by Jimmy-Z** [comment]
still true with 16.9.2 driver, very disappointed in AMD

**Comment by wm4** [comment]
To be honest I'm not sure if there could be a user error (documentation about d3d11va and threading isn't very explicit on MSDN). But if even Google chose to use a blacklist, it seems likely that their code is actually correct and AMD's drivers are broken. I'd expect that Google and AMD are in contact with each other. Also, I haven't heard of problems on other platforms (Intel/nvidia).

Is it known whether all AMD hardware is affected?

Also, did anyone try the d3d_copy_texture branch? It's aging, I can rebase it if anyone wants a newer version.

**Comment by vishnunaini** [comment]
Based on the chrome source code from https://cs.chromium.org/chromium/src/gpu/config/gpu_driver_bug_list_json.cc almost all AMD hardware i.e vendor id 0x1002 appears to be affected

`    {
      "id": 171,
      "description": "NV12 DXGI video hangs or displays incorrect colors on AMD drivers",
      "cr_bugs": [623029, 644293],
      "os": {
        "type": "win"
      },
      "vendor_id": "0x1002",
      "features": [
        "disable_dxgi_zero_copy_video",
        "disable_nv12_dxgi_video"
      ]
    },`

Firefox currently disables d3d11 on all AMD hardware and falls back to dxva2

Based on both cases it can safely be assumed all AMD hardware is effected.

I tested it on a A10 APU(Radeon 7660G) with 15.7 (15.200.1065.0) driver (Trinity)
and a HD 8670M with 16.9 driver and both cases are effected.

I will try to test it soon on Carrizo chips.

**Comment by vishnunaini** [comment]
Don't assume that Google and AMD are in contact with each other. It is likely that they only contact AMD if a workaround is not possible or requires too much effort.

**Comment by xnoreq** [comment]
With latest AMD driver (version 16.11.4) eglStreamPostD3DTextureNV12ANGLE fails.

**Comment by dumpsters** [comment]
Using:
```
AMD driver 16.11.2
hwdec=d3d11va-copy
profile=opengl-hq
opengl-backend=angle
opengl-pbo=yes
opengl-swapinterval=1
opengl-shaders="~~/scripts/adaptive-sharpen-2pass.glsl"
```

I get **[d3d11va] Failed to create Direct3D11 texture with 22 surfaces: The parameter is incorrect. (0x80070057)**

mpv log:
```
[auto_profiles] Applying profile SD
Playing: Dawn.of.the.Dead.2004.1080p.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
AO: [wasapi] 44100Hz stereo 2ch float
[d3d11va] Failed to create Direct3D11 texture with 22 surfaces: The parameter is incorrect. (0x80070057)
[auto_profiles] Applying profile HD
Using software decoding.
VO: [opengl] 1920x812 yuv420p
Resolution: 1920x812, Framerate: 23.976 Hz
```
Tried using `log-file=output.txt` but it gets stuck on "Playing: dir/filename" and a spam of `[   0.232][v][lavf] Found 'lrc' at score=5 size=17982.` (video never gets to play)


Gonna update to latest now and test again.

**Comment by wm4** [comment]
Wondering if it doesn't like D3D11_BIND_SHADER_RESOURCE...

**Comment by wm4** [comment]
> How about AMD fixes their shit?

Apparently this happened, according to: https://github.com/mpv-player/mpv/issues/3464#issuecomment-292523829

So I'm closing this. If someone still has the problem even with updated AMD drivers, please post here, or open a new issue.
