### ISSUE TITLE
Bluray menu on linux?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3258]
Hi!

Is it possible to have bluray BD-J menu working with mpv on linux?

I tried mpv-0.17.0 with libbluray-0.9.3 BD-J enabled and Icedtea-7 JVM, but couldn't get anything, except some "parser errors" in mpv's log:
`Playing: bd://
Entity: line 1: parser error : AttValue: " or ' expected
er="1">Burn After Reading</di:titleName></di:tableOfContents><di:thumbnail href=
                                                                              ^`

Regards,
Alex

**Comment by wm4** [comment]
Menu support was removed from mpv some releases ago.

Unless there's a developer who has interest in bluray menus and wants to invest effort into them, they won't come back.
