### ISSUE TITLE
Stream dump doesn't dump a raw stream

### ISSUE THREAD

**Issue by billrepay** [mpv-player/mpv#3262]
I am using mpv-0.17.0 and I am trying to record video from the webcam. Actually, I have an old netbook and I am using an USB camera to inspect a pipe, so I would like to be able to view the video and record it at the same time. I also setup wayland and mpv was the only player that worked with wayland. Works quite well too.

As this is a crappy netbook with a bit hard disk, I tried to dump the raw YUV420p stream to disk, using the --stream-dump option. This created the file but nothing appeared. I was hoping to get some video to playback, but alas nothing, just an empty file.

I checked the source and noticed that the tv data isn't going through the stream side of things but rather via the decoder side of things. Anyhow I managed to get the stream I was after by dumping the raw data entering the deocder in  video/decode/dec_video.c:
ie. 
```
     MP_STATS(d_video, "start decode video");
 
+if(fp == NULL) fp = fopen("a.dump", "wb");
+fwrite(packet->avpacket->data, 1,  packet->avpacket->size, fp);
     struct mp_image *mpi = d_video->vd_driver->decode(d_video, packet, drop_frame);

     MP_STATS(d_video, "end decode video");
```

and using ffmpeg I was able to compress this into video thus:
ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 1280x720 -r 10 -i a.dump -c:v libx265  output.mp4

I guess the issue here that you cannot dump a raw stream, but it would be nice if it was possible to dump the raw data before decoding.

**Comment by wm4** [comment]
This must be via the rtsp protocol. FFmpeg has an awful hack for this and circumvents the stream layer completely. Thus no byte is ever transferred through the stream layer, and the dump file remains empty. This can't be fixed.

Writing packets to a file is completely different, and mpv doesn't support it. Use ffmpeg CLI or something.

**Comment by yan12125** [comment]
Got here by searching RTSP and ```--stream-dump```. @wm4 Did you mean it's impossible to use mpv to dump RTSP streams to files correctly?
