### ISSUE TITLE
rescan-external-files won't find/select subtitles if media is played via. http

### ISSUE THREAD

**Issue by norpol** [mpv-player/mpv#3264]
### mpv version and platform
- Debian Stretch
- mpv 0.14 AND 0.17 (via. Debian and Debian multimedia, didn't test with latest git because command wasn't mentioned in changelogs)
### Expected behavior

If I run `rescan-external-files` I'd expect mpv to search at the current directory for new subtitle-files (`.srt`) and then adding it to the current playing file.
The bug also breaks this [subtitle script](https://gist.github.com/selsta/ce3fb37e775dbd15c698).
### Actual behavior

Command-Line Interface will give feedback that `rescan-external-files` was run, subtitle at the current folder (or any default subtitle folder, or defined sub-path) won't be selected.
### Reproduction steps

Open in one shell:
`mpv --input-ipc-server=/tmp/mpv.socket --sub-paths=/path/to/sub-files/ --sub-auto=all http://localhost/video-file.mkv`

And then in another:
`socat - UNIX-CONNECT:/tmp/mpv.socket`
and then run the command `rescan-external-files`.
### Log files

I'm not sure if it's necessary to provide the complete log-file. I think this issue is the same on any other installation and it's right now difficult for me to clear the log-file from personal details (sorry). If you really need it, I'm going to make the efforts to clear the log-file.
Here is some necessary part of the log-file:

```
[   0.005][v][cplayer] mpv 0.17.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[   0.005][v][cplayer]  built on UNKNOWN
[   0.005][v][cplayer] ffmpeg library versions:
[   0.005][v][cplayer]    libavutil       55.17.103
[   0.005][v][cplayer]    libavcodec      57.24.102
[   0.005][v][cplayer]    libavformat     57.25.100
[   0.005][v][cplayer]    libswscale      4.0.100
[   0.005][v][cplayer]    libavfilter     6.31.100
[   0.005][v][cplayer]    libswresample   2.0.101
[   0.005][v][cplayer] ffmpeg version: 3.0.2
[   0.005][v][cplayer] 
[   0.005][v][cplayer] Configuration: ./waf configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --enable-cdda --confdir=/etc/mpv --disable-build-date --enable-sdl2 --zshdir=/usr/share/zsh/vendor-completions --enable-zsh-comp --enable-gpl3 CC=ccache cc
[   0.005][v][cplayer] List of enabled features: alsa any-gl asm atomics audio-input av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-profile-name avframe-metadata avframe-skip-samples c11-tls caca cdda cplayer debug-build dlopen drm dvbin dvdnav dvdread egl-helpers egl-x11 enca fchmod gl gl-wayland gl-x11 glibc-thread-name glob gpl3 iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libguess libm librt libsmbclient libswresample libv4l2 linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads pulse resampler rubberband sdl2 shm sse4-intrinsics standard-gl stdatomic subprocess termios tv tv-v4l2 uchardet vaapi vaapi-egl vaapi-glx vaapi-hwaccel vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h wayland x11 xext xinerama xrandr xss xv zlib zsh-comp
```

Thank you!

**Comment by wm4** [comment]
This normally works relative to the file's path, and consequently it doesn't work for http URLs.

The subtitle-script should probably explicitly add those subtitles by path.

**Comment by norpol** [comment]
Thank you for your very fast reply.
Could you (or someone who can implement/maintain this) maybe add a (configuration) parameter for `rescan-external-files` to specify a scan-path or make it also scan for example the `sub-paths`?
If the behavior won't be changed, could you update the [documentation](https://mpv.io/manual/stable/#command-interface-rescan-external-files) to:
> Rescan external files at the media's file-path according to the current --sub-auto and  --audio-file auto settings. This can be used to auto-load external files after the file was loaded. This will only scan for files that are played on a local resource and not remotely (for example via. http).

**Comment by wiiaboo** [comment]
@norpol can you test with https://github.com/mpv-player/mpv/pull/4293?
