### ISSUE TITLE
Subtitles do not respect the time.

### ISSUE THREAD

**Issue by Cervoz** [mpv-player/mpv#3265]
Hi,

### Mpv version and platform
Version of 2016-04-11, Windows 7.

### Expected behavior
Respect the time subtitles.

### Actual behavior
When two subtitles are slightly spaced (like 200 milliseconds), they appear stuck without space.

### Reproduction steps
Copy/paste this in a .srt file and open with a random video. Normally a break of 200 ms should appear between the two lines, but with me (and others), this cut does not appear. No problem on other players like VLC or MPC.

```
1
00:00:00,040 --> 00:00:04,350
Si vous voulez rester en vie,

2
00:00:04,540 --> 00:00:06,770
je vous conseille de ne pas bouger.
```

### Log files

[output.txt](https://github.com/mpv-player/mpv/files/322407/output.txt)

**Comment by wm4** [comment]
Use ``--sub-fix-timing=no``. No, we won't change it. No, flickering subtitles are not something anyone wants to have.
