### ISSUE TITLE
playlist-count not updating properly when observed

### ISSUE THREAD

**Issue by 00SteinsGate00** [mpv-player/mpv#3267]
### mpv version and platform
* OS X 10.11.5
* mpv 0.17.0

### Expected behavior

I'm creating a node package to control mpv via the Json IPC protocol right now and stumbled into some bug, or at least I think it is one.

I use the `observe_property` to keep track of various properties, such as "playlist-count"

If I remove a song or add a song to the playlist, I would expect to get a *property-change* message.

### Actual behavior

I don't get any message. But when I get a "playlist-pos" *property-change* message (which I have observed as well), receive a *property-change* message for "playlist-count", too.

When I only observe "playlist-pos", a `playlist-remove` command triggers a *property-change* message. 'load file' (appending) however does not.

I checked with `get_property` that "playlist-count" was correctly updated.
 
### Reproduction steps

Open a running instance of **mpv** with more than 1 song.
```
mov /Folder/containing/more/than/one/song --input-ipc-socket=/tmp/mpv.sock
```

In another terminal open Socat
```
socat - UNIX-CONNECT:/tmp/node-mpv.sock   
```
and enter the commands to observe the property

```
{"command": ["observe_property", 1, "playlist-count"]}
{"command": ["observe_property", 2, "playlist-pos"]}
```

In a 3rd terminal send a `playlist-remove` and a `loadfile` message.

```
echo '{"command": ["playlist-remove", 2]}' | socat - /tmp/mpv.sock
echo '{"command": ["loadfile", "/some/song.mp3", "append"]}' | socat - /tmp/mpv.sock
```

### Log files

http://sprunge.us/bgAg

**Comment by wm4** [comment]
Yeah, that has to be explicitly handled in the mpv code. I suppose currently it only triggers a notification if you actually start/end playback of a file.

**Comment by wm4** [comment]
I hope it works now. I didn't actually test it.

**Comment by 00SteinsGate00** [comment]
I just tested it with the latest build and can confirm, that it is working properly as expect. Thank you very much for addressing this so quickly.
