### ISSUE TITLE
VDPAU: corruption when decoding too fast

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#3268]
### mpv version and platform

Master. Also tested v0.16 with no change. Nvidia 367.27 + Gentoo Linux 4.5.7
### Expected behavior

Frames are rendered correctly
### Actual behavior

Frames are rendered with image corruption
### Reproduction steps

`mpv --speed=20 --hwdec=vdpau FILE` or just use `mpv --hwdec=vdpau FILE` and try precise seeking
### Log files

https://0x0.st/Ty_.txt

**Comment by haasn** [comment]
`--vf=vdpaurb` fixes the `-speed 20` issue but not the precise seeking issue.

The artifacts also look distinctly different. The `-speed 20` artifacts just look like the bottom bits of the frame are melted. The precise seeking artifacts are more like spontaneous blocks appearing all over the frame.

**Comment by wm4** [comment]
I'm seeing the latter type of artifacts in all cases.

**Comment by wm4** [comment]
(364.16 here.)

**Comment by lamarpavel** [comment]
Since the update to mpv 0.18 I get artifacts with hwdec=vdpau that look like de-interlacing gone wrong, it occurs regardless of seeking or speed-up. I'm using an AMD card with mesa 11.2.2 under xorg 1.18.3 (Archlinux).
The artifacts are not visible on screenshots made with mpv.

This is what it looks like with and without vdpau, all other settings default via --no-config:
http://b.1339.cf/qoedfst.png
http://b.1339.cf/xdaebwu.png

**Comment by wm4** [comment]
That's different and looks like the reinterleaving is going wrong.

**Comment by haasn** [comment]
mpv's deinterleaving shader relies on correct GL_NEAREST behavior. Maybe your drivers are bust?

**Comment by lamarpavel** [comment]
Alright, sorry to have cluttered up this issue with something unrelated. Should I create a new one for further investigation?

**Comment by wm4** [comment]
AMD issue: #3317

**Comment by JackieKu** [comment]
Same here with [361.28, 367.27] once I upgraded my hardware from GTX 550 to GTX 950. Also it happens with both `--vo vdpau` and `--vo opengl`.

I was thinking this new hardware might be faulty, then I tried mplayer+vdpau and (mpv|mpc-hc)+dxva2 _on Windows_ and they don't have any problem.

MPV versions: 0.18.0, 0.18.1, master

**Comment by haasn** [comment]
Note: I can partially “work around” the issue by using

```
export VDPAU_TRACE=2
export VDPAU_TRACE_FILE=/dev/null
```

The fact that this helps significantly seems to indicate that the issue might be some sort of synchronization barrier gone wrong.

**Comment by lachs0r** [comment]
I can’t reproduce this anymore with a GTX 960 (driver 370.28).

**Comment by haasn** [comment]
Neither can I
