### ISSUE TITLE
[Menu] bar on fullscreen on Os x 10.11 using multiple monitor

### ISSUE THREAD

**Issue by BakaPhoenix** [mpv-player/mpv#3272]
Using the option "Displays have separate Spaces" in mission control settings while using multiple monitors will make the task bar appear while watching a video in full screen if using another window in the other screen.
I made a screenshot to show the problem:
http://i.imgur.com/j4VFwLj.png

**Comment by ChrisK2** [comment]
That's the menu bar.
Try enabling "stay on top" (Shift + t).

**Comment by Akemi** [comment]
fixed in https://github.com/mpv-player/mpv/commit/a8347eb9ba9e09177da50592fde7f3ae7261ce59
