### ISSUE TITLE
Change Screenshot Name Format, Directory, and File Type

### ISSUE THREAD

**Issue by kurisubrooks** [mpv-player/mpv#3275]
### mpv Version and Platform
`mpv`: 0.17
`platform`: OS X 10.11 El Capitan

### Request
1. Change the Screenshot output name format from `mpv-shot{int}.jpg` to `mpv-{filename}{int}.jpg` (or similar).
> This allows for easier sorting and finding of screenshots taken from within mpv. I take alot of screenshots while watching anime of nice scenes, but they all get mushed together in one directory with no way to tell what video that screenshot is from. ~~(unless you have a very, very good memory)~~

2. Move the default Save location from the Desktop to the Pictures folder, or an mpv subfolder in the Pictures folder.
> This keeps clutter off of your desktop, and in macOS Sierra, the Desktop is used for Cloud Syncing with iCloud, so this will create unnecessary files being synced to your Cloud Drive, and related Apple Devices.

3. Change format from `jpg` to `png`.
> I'd love higher resolution screenshots, I take alot of screenshots of nice scenes in videos, and i'd love that extra bump in quality.

**Comment by wiiaboo** [comment]
1. https://mpv.io/manual/master/#options-screenshot-template
2. https://mpv.io/manual/master/#options-screenshot-directory
3. https://mpv.io/manual/master/#options-screenshot-format

**Comment by kurisubrooks** [comment]
I'm using mpv through the Homebrew linked binary, is there any way to add these startup options to that whilst still being able to launch as a binary file?

**Comment by haasn** [comment]
https://mpv.io/manual/master/#configuration-files
