### ISSUE TITLE
[closed/solved] sub-paths does not seem work.

### ISSUE THREAD

**Issue by dragons4life** [mpv-player/mpv#3278]
**Windows 10**
According to the manual, `sub-paths` is supposed to load up all the subs within the folder you assign it to, correct?

so if I were to have` /video/video.mkv` play and the subs will be at `/video/subs/` it will load up the subs if I add the command `sub-paths=subs` in my mpv.conf

However it does not do that, it just loads up the video with (if it has) the subs on the .mkv container.

I am currently using sub-auto=all and it does not work with it neither (I've used every option for sub-auto)

In short, I don't think `sub-paths` is working.

Also if possible, I was thinking this could be added as a feature on MPV

Whenever you use playlist-next/prev the files do not remember the save position, it's a minor annoyance but it will be good if they did remember their playback position.

I also believe that having filter settings such as gamma=0 in your mpv.conf should automically.

Also I would like to ask for a feature request, if you can call it that.
as of right now using the input command playlist-next/prev does not save playback position, I would like for the playback position to be remembered if I skip to the next file.

**Comment by wiiaboo** [comment]
If you have `sub-paths=subs` it will look for files in `/video/`, `/video/subs/` and `~/.config/mpv/subs`. Why would it append the video filename?

**Comment by dragons4life** [comment]
Sorry yes you are correct, I meant to say `/video/subs/` instead of `/video/video.mkv/subs/`

**Comment by wiiaboo** [comment]
It should work, run mpv with `--log-file=log.txt` and upload it somewhere.

**Comment by dragons4life** [comment]
https://upload.teknik.io/TamLP.txt

**Comment by wiiaboo** [comment]
Can you  try using `;` as separators instead of `:`?

**Comment by dragons4life** [comment]
<img src='https://i.sli.mg/yYNf8H.png'/>
It worked.

**Comment by wiiaboo** [comment]
The difference is in the manual, so you can probably close this.

**Comment by dragons4life** [comment]
you are correct `Specify extra directories to search for subtitles matching the video. Multiple directories can be separated by ":" (";" on Windows)`

I am just fucking blind, mostly assumed it worked with " : ", than again so did you, kind of weird it doesn't.

thanks for your help

**Comment by Argon-** [comment]
Instead of renaming just close the issue with the button next to the "Comment" button.
