### ISSUE TITLE
Build error on 0.18.0, OSX 10.11.5, waf no such option --enable-gpl3

### ISSUE THREAD

**Issue by patrickchoi** [mpv-player/mpv#3279]
Hello,

Getting the following error when I try to compile. 

==> Cloning https://github.com/mpv-player/mpv.git
Updating /Library/Caches/Homebrew/mpv--git
==> Checking out branch master
==> Downloading https://pypi.python.org/packages/source/d/docutils/docutils-0.12
Already downloaded: /Library/Caches/Homebrew/mpv--docutils-0.12.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Ce
==> Downloading https://waf.io/waf-1.8.12
Already downloaded: /Library/Caches/Homebrew/mpv--waf-1.8.12.12
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/HEAD --enable-gpl3 --en
Last 15 lines from /Users/patrickchoi/Library/Logs/Homebrew/mpv/02.python3:
                        disable libavcodec DXVA2 and D3D11VA hwaccel
                        [autodetect]

  tv features:
    --disable-tv        disable TV interface [autodetect]
    --disable-tv-v4l2   disable Video4Linux2 TV interface [autodetect]
    --disable-libv4l2   disable libv4l2 support [autodetect]
    --disable-audio-input
                        disable audio input support [autodetect]
    --disable-dvbin     disable DVB input module [autodetect]

  standalone app:
    --disable-apple-remote
                        disable Apple Remote support [autodetect]
waf: error: no such option: --enable-gpl3

**Comment by Argon-** [comment]
The homebrew formula was not updated yet: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb#L65
Workaround: build using `--HEAD`

**Comment by lachs0r** [comment]
That option no longer has a reason to exist since NNEDI3 has been removed from the source tree.

**Comment by Argon-** [comment]
> That option no longer has a reason to exist since NNEDI3 has been removed from the source tree.

The homebrew formula was not updated yet, it installs 17 as stable and uses this flag in this case. For building git master the usage of that flag was removed from the formula a week ago.

**Comment by patrickchoi** [comment]
Thanks, removing --HEAD from the build command worked
