### ISSUE TITLE
video-zoom doesn't reset with reset-on-next-file=video-zoom and same resolution images

### ISSUE THREAD

**Issue by 0WUL** [mpv-player/mpv#3281]
### mpv version and platform
mpv git-22c76e8, ffmpeg N-80680-ga887fbb, Linux

### Reproduction steps
1) Enable reset-on-next-file=video-zoom
2) Open two or more same-resolution videos or images (e.g. both 1280x720) in a playlist
3) Zoom in or out
4) Go next/prev in playlist.

### Expected behavior
The video-zoom resets

### Actual behavior
It stays the same amount zoomed in/out (visually at least)

If I increase/decrease the zoom by any amount, or resize the mpv window at all, the zoom visually resets.

### Log files
http://pastebin.com/raw/PwetBmNG

### Other info
I tried opengl and xv video outputs, and both openbox and Gnome wayland.

video-pan-x and video-pan-y also do not visually reset under the same circumstances.

**Comment by wm4** [comment]
Thanks for reporting and sorry for the delay.
