### ISSUE TITLE
d3d11va not working?

### ISSUE THREAD

**Issue by ArchangeGabriel** [mpv-player/mpv#3285]
### mpv version and platform

2016-06-25 build from https://mpv.srsfckn.biz/.

Windows 7 64bit, fully updated. GT730.

### Reproduction steps

Run `mpv --hwdec=d3d11va somefile.mkv`.

### Expected behavior

It should work (it does with dxva2, using ANGLE too).

### Actual behavior

It doesn't work: 
```
[vd] VO does not support requested hardware decoder, or loading it failed.
[vd] Using software decoding.
```

### Log files

(Relevant) excerpt:
```
[vo/opengl] Initializing OpenGL backend 'angle'
[vo/opengl] Rendering flipped.
[vo/opengl] GL_VERSION='OpenGL ES 3.0 (ANGLE 2.1.0.fd99bfc647ae)'
[vo/opengl] Detected GLES 3.0.
[vo/opengl] GL_VENDOR='Google Inc.'
[vo/opengl] GL_RENDERER='ANGLE (NVIDIA GeForce GT 730 Direct3D11 vs_5_0 ps_5_0)'
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='OpenGL ES GLSL ES 3.00 (ANGLE 2.1.0.fd99bfc647ae)'
[vo/opengl] Loaded extension GL_EXT_texture_norm16.
[vo/opengl] Loaded extension GL_EXT_color_buffer_half_float.
[vo/opengl] Loaded extension GL_EXT_disjoint_timer_query.
[vo/opengl] Loaded extension GL_ANGLE_translated_shader_source.
[vo/opengl] swap_control extension missing.
[vo/opengl] Reported display depth: R=8, G=8, B=8
[vo/opengl] Testing FBO format 0x805b
[vo/opengl] Create FBO: 16x16 (16x16)
[vo/opengl] Using FBO format 0x805b.
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Loading hwdec driver 'd3d11-egl'
[vo/opengl] Loading failed.
[vo/opengl] Loading hwdec driver 'd3d11-egl-rgb'
[vo/opengl/d3d11-egl-rgb] D3D11 video decoding not supported on this system.
[vo/opengl] Loading failed.
[vd] Container reported FPS: 23.976025
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd] Opening video decoder lavc:h264
[vd] Probing 'd3d11va'...
[vo/opengl] Loading hwdec driver 'd3d11-egl'
[vo/opengl] Loading failed.
[vo/opengl] Loading hwdec driver 'd3d11-egl-rgb'
[vo/opengl/d3d11-egl-rgb] D3D11 video decoding not supported on this system.
[vo/opengl] Loading failed.
[vd] VO does not support requested hardware decoder, or loading it failed.
[vd] Using software decoding.
```

Am I missing something?

**Comment by wm4** [comment]
D3D11 video decoding doesn't work on Windows 7.

**Comment by avih** [comment]
> D3D11 video decoding doesn't work on Windows 7.

Sounds like this could be a useful addition to the warning message which mpv prints (when applicable).

**Comment by wm4** [comment]
Why the fuck would we bother? If users are so stupid trying to force something that doesn't work instead of using the proper mechanisms, it's up to them to figure out what they broke.

**Comment by ArchangeGabriel** [comment]
Well, I’ve tried d3d11va because from the doc, “dxva2 is not safe.” (talking of quality reduction). And found no evidence that Windows 7 was the culprit here…

**Comment by wm4** [comment]
Yes, with Windows 7 you either have to accept quality reduction, or you don't use hardware decoding with no copy back.

**Comment by ArchangeGabriel** [comment]
You mean that `d3d11va-copy` should work or that `dxva2-copy` doesn’t suffer quality reduction?

**Comment by wm4** [comment]
Latter.

**Comment by ArchangeGabriel** [comment]
OK, thanks. I should be able to live with that. Maybe you could precise this in the man. ;)

**Comment by wm4** [comment]
...and this is also VERY CLEARLY apparent from the --hwdec manpage description, which I just reread.

**Comment by ArchangeGabriel** [comment]
Indeed, dunno how I missed the last paragraph… Thanks!

So, what could be added is either an error message about the fact that Win7 doesn’t support d3d11va like @avih suggested or a mention of it in the doc (something like “Windows only” → “Windows 8+ only”, or a note below like it’s done for vaapi/Mesa 11), or even both.

**Comment by Hrxn** [comment]
Nah, don't bother.
I, for one, am already happy that Windows is supported at all ;)

**Comment by wang-bin** [comment]
Did you try d3d11 update for win7? http://download.microsoft.com/download/F/4/3/F431C6D1-D581-459E-BB01-A6AEBBB779FC/Windows6.1-KB2670838-x86.msu  or http://download.microsoft.com/download/F/4/3/F431C6D1-D581-459E-BB01-A6AEBBB779FC/Windows6.1-KB2670838-x64.msu mpv d3d11va then works perfectly on my win7 environment.

**Comment by wm4** [comment]
AFAIK d3d11va principally doesn't work with video decoding on Windows 7. It's (almost) the only reason we still have dxva2. Is this a special driver by a specific vendor, or does it work for all?

**Comment by Skibicki** [comment]
Check hardware compatibility carefully. Update KB2670838 received many complaints on support forums.

**Comment by wang-bin** [comment]
I find that mpv fails to open d3d11 decoder. But in fact d3d11 decoder is available because it works fine in my player. Tested hardware: intel HD3000, GT540M
