### ISSUE TITLE
youtube live stream buffers

### ISSUE THREAD

**Issue by Joseph65** [mpv-player/mpv#3288]
### mpv version and platform

mpv 0.14.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.6-1ubuntu2
If you're not using git master or the latest release, update.
### Reproduction steps

When i watch this live stream "https://www.youtube.com/watch?v=A8A1NVZHFtc" in mpv with
`mpv --ytdl-format 95 https://www.youtube.com/watch?v=A8A1NVZHFtc`
it buffers alot, this doesnt happen when i play it with a browser in 720p quality
the format 95 is also 720p.
### Log files

Make a log file made with -v or --log-file=output.txt, paste it to sprunge.us,
and replace this text with a link to it.

**Comment by wiiaboo** [comment]
> If you're not using git master or the latest release, update.
You should do this. It could be fixed in newer versions and the devs don't support anything beyond latest release or git master.

**Comment by Joseph65** [comment]
i did that im using now mpv 0.18.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Jun 26 12:02:37 UTC 2016 and im having the same issue do you know of any special parameter to fix the buffering

**Comment by Jj0YzL5nvJ** [comment]
The buffer problem resides in ffmpeg, not mpv.
 With your video I see this errors:
`[ffmpeg] tls: A TLS packet with unexpected length was received.`

I build my ffmpeg (3.1.1) with --enable-gnutls.
Maybe --enable-openssl fix your problem...

Example:
`./configure --prefix=/usr/local --arch=amd64 --cpu=amd64 --enable-gpl --enable-version3 --enable-shared --enable-libx264 --enable-libmp3lame --enable-openssl --disable-debug`

**Comment by sebma** [comment]
Hi,
I'm using ffmpeg v3.2 that has `--enable-gnutls` and `--enable-nonfree` from : 
```
$ $(which ffmpeg) 2>&1 | egrep -oi "openssl|--enable-gnutls|--enable-nonfree"
--enable-gnutls
--enable-nonfree
$ 
```
But I still get the `[ffmpeg] tls: A TLS packet with unexpected length was received.` warnings :( 

Do you any other suggestion ?

**Comment by Jj0YzL5nvJ** [comment]
I use this now:
```
ffmpeg version 3.2.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 20160609
  configuration: --prefix=/usr/local --arch=amd64 --cpu=amd64 --enable-gpl --enable-version3 --enable-nonfree --enable-shared --enable-libfdk-aac --enable-libmp3lame --enable-librtmp --enable-openssl --enable-opengl --enable-libpulse --enable-libass --enable-libbluray --enable-libcaca --enable-libvpx --enable-libvorbis --enable-libtheora --enable-libopus --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --disable-debug
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

The only related options are: `--enable-librtmp --enable-openssl`

@sebma, can you provide an URL example for testing?

**Comment by sebma** [comment]
Oops, the whole bunch of warning I get was not concerning live streams, sorry :)

I think I'll create another issue for that.

**Comment by wiiaboo** [comment]
Stream doesn't exist anymore and I can't tell what the original issue was. Probably shitty net or not enough cache.
