### ISSUE TITLE
Volume and seek progress are not clearly visible with osd-blur using high number

### ISSUE THREAD

**Issue by blackarcher21** [mpv-player/mpv#3290]
### mpv version and platform

mpv 0.18.0 for Windows, 64-bit version

### Reproduction steps
Using high number for osd-blur, use max regarding manual, 20.0

### Behavior
Volume and Seek progress are not clearly visible

**Comment by wm4** [comment]
Guess what, I don't care.

**Comment by haasn** [comment]
Seems to be working as intended?

**Comment by blackarcher21** [comment]
Sorry, I just don't know if it is working as intended or not. Text is still okay. Here is screenshot http://i.imgur.com/f8idEVX.jpg (using 10.0 atm).
