### ISSUE TITLE
The audio of my .wmv PORN doesn't sync.

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#3297]
It doesn't happen to VLC player.

### mpv version and platform
mpv 0.18.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Jun 26 12:02:37 UTC 2016
ffmpeg library versions:
   libavutil       55.26.100
   libavcodec      57.46.100
   libavformat     57.40.101
   libswscale      4.1.100
   libavfilter     6.46.102
   libswresample   2.1.100
ffmpeg version: N-80640-gf573acc
### Reproduction steps
Play the video.
### Expected behavior
Video and Audio are sync.
### Actual behavior
It doesn't sync if I seek forward many minutes.
### Log files
Playing: /home/user/下載/.非家庭類/"My Porn Video".wmv
 (+) Video --vid=1 (vc1)
 (+) Audio --aid=1 (wmapro)
libva info: VA-API version 0.39.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [opengl] 1920x1080 vaapi
Failed audio resync.
AV: 00:03:07 / 02:39:57 (1%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:04:09 / 02:39:57 (2%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:05:11 / 02:39:57 (3%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:20:35 / 02:39:57 (12%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:21:37 / 02:39:57 (13%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:22:37 / 02:39:57 (14%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:26:43 / 02:39:57 (16%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:27:45 / 02:39:57 (17%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:28:45 / 02:39:57 (17%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:29:47 / 02:39:57 (18%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:34:51 / 02:39:57 (21%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:38:07 / 02:39:57 (23%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:39:09 / 02:39:57 (24%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:40:11 / 02:39:57 (25%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:41:12 / 02:39:57 (25%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:42:12 / 02:39:57 (26%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:44:18 / 02:39:57 (27%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:45:18 / 02:39:57 (28%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:52:25 / 02:39:57 (32%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 01:00:35 / 02:39:57 (37%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 01:03:40 / 02:39:57 (39%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 01:04:40 / 02:39:57 (40%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 01:05:40 / 02:39:57 (41%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 01:06:42 / 02:39:57 (41%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 01:09:49 / 02:39:57 (43%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 01:10:50 / 02:39:57 (44%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 01:14:59 / 02:39:57 (46%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 01:16:04 / 02:39:57 (47%) A-V:  0.000 DS: 2.000/0
Failed audio resync.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 01:16:06 / 02:39:57 (47%) A-V: -3.813 ct: -0.277

Exiting... (Quit)
### My setting
vo=opengl
sub-auto=fuzzy
no-osd-bar
video-sync=display-resample
hwdec=vaapi
sub-text-font=noto-sans-cjk

**Comment by wm4** [comment]
Sample required. (Non-PORN sample would be preferred though.)

**Comment by JulianLai** [comment]
I only have the porn sample for .wmv files, I need some time to compress and upload the video.

**Comment by wm4** [comment]
I hope you don't mean to transcode the video? In any case, as long as the resulting file can be used to reproduce the failure, it should be fine.

**Comment by JulianLai** [comment]
No, just turn it into a .tar.xz format, and it is still so big.......
I need almost 3 hours to upload it.

**Comment by Argon-** [comment]
Can't you e.g. cut the first 10min? `ffmpeg -i input.wmv -c copy -t 00:10:00.0 output.wmv`

**Comment by JulianLai** [comment]
https://drive.google.com/open?id=0BxnS0W8xlR-QV0doR0NWR0hsRlk
Here is the 10 minutes video.

**Comment by haasn** [comment]
Plays fine here.

**Comment by JulianLai** [comment]
@haasn Because it is only a 10 minutes video, you won't see the effect by your eyes, if the video time is longer, you will see it.

**Comment by JulianLai** [comment]
Can it be fixed? Or is it ffmpeg's bug?

**Comment by JulianLai** [comment]
It seems like being fixed in version 0.18.1, thanks!

**Comment by wm4** [comment]
Can't remember anything that would have changed this (except the actual initial sync and the message it printed), but ok.
