### ISSUE TITLE
Bad performance while using interpolation

### ISSUE THREAD

**Issue by TallsFalls** [mpv-player/mpv#3298]
### mpv version and platform

mpv git-9ca1592 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
built on Wed Jun 29 10:31:38 BST 2016
ffmpeg library versions:
libavutil       55.27.100
libavcodec      57.48.101
libavformat     57.40.101
libswscale      4.1.100
libavfilter     6.46.102
libswresample   2.1.100
ffmpeg version: 3.1
### Reproduction steps

Playing video while using interpolation.
### Expected behavior

Stable performance.
### Actual behavior

The GPU seems to go on its low speed mode (135MHz core clock instead of 1110.5MHz) at some spots of the video (maybe after X playback time), and then I start to have hundreds of dropped frames. Sometimes when I replay the same part I don't have any problem and the core clock keeps running at 1110.5MHz, but after some time it goes wrong again.
I'm not sure if the low core clock speed causes the performance problem or if it's a coincidence, but both seem related. GPU load never goes over 70%, and CPU load keeps below 25%. I'm using GPU-Z to check the GPU information.
### Log files

[http://sprunge.us/ALeD](http://sprunge.us/ALeD)

**Comment by wm4** [comment]
You can probably fix this by setting the driver to maximum performance in the nvidia control panel.

The same thing happens on Linux, and I'm not sure if we can workaround it. (Short of using nvidia's control lib and forcing the setting in our code.)

**Comment by kevinlekiller** [comment]
I had dropped frames with some aggressive settings (cscale to ewa_lanczossharp for example), on Windows you can do like wm4 wrote, in manage 3d settings you add a exe profile for mpv.exe and set it to "Prefer maximum performance", on Linux I wrote [a lua script](https://raw.githubusercontent.com/kevinlekiller/mpv_scripts/master/powermizer/powermizer.lua) which sets it to max performance when mpv runs and back to adaptive when it exits.

**Comment by wm4** [comment]
Interesting. One suggestion: hook it to the property `core-idle`, then the thing can go back to low performance when paused.

**Comment by kevinlekiller** [comment]
That's a good idea, thanks!

**Comment by TallsFalls** [comment]
Thank you, I fixed my problem by setting the driver to maximum performance in the nvidia control panel.

**Comment by JulianLai** [comment]
Is the newer intel GPU able to run the interpolation?

**Comment by cwbsw** [comment]
Is it possible to do some benchmark about interpolation performantion, in order to confirm whether a machine could turn on interpolation?

**Comment by haasn** [comment]
> Is it possible to do some benchmark about interpolation performantion, in order to confirm whether a machine could turn on interpolation?

You can try it out yourself very easily: Set a keybinding like ```t show-text "${vo-performance}"``` and press it after 10 seconds or so of playback.

It's split into 3 groups. The one you're interested in for interpolation is “present time”. It should be very low with interpolation off (about 1000μs for me with 3dlut and dithering at 4K), and go up noticeably with interpolation on (goes up by ~700μs for me with `tscale=mitchell`).

**Comment by cwbsw** [comment]
@haasn Thanks, it's helpful. However, I found that the present time reached close to 16666μs with angle backend, but the value was only ~3000μs with dxinterop backend. Is it expected? There was no dropped frames, and gpu load was below 50% under the two situations. (maximum performance selected in the nvidia control panel)

By the way, what's your graphic card, powerful enouth to handle 4K display?

**Comment by igv** [comment]
This seems like happens with ANGLE only. When render timing is high (despite the fact that GPU usage is below average), video-sync=display-resample causes stuttering with ANGLE. With es=no render timing is the same, but no stuttering.

**Comment by haasn** [comment]
@cwbsw I am using a GTX 970.

It being that high with ANGLE compared to dxinterop is somewhat worrying. I personally can't stand ANGLE either way.

**Comment by rossy** [comment]
@igv Is this on Windows 8.1/10, and does the problem go away in fullscreen mode? I have this problem on my machine as well and I suspect it's because ANGLE's swapchain length is too small and it's wasting time waiting for the DWM to release the backbuffer texture.

**Comment by igv** [comment]
@rossy Win 10

> does the problem go away in fullscreen mode?

nope

**Comment by igv** [comment]
> This seems like happens with ANGLE only. When render timing is high (~15000, despite the fact that GPU usage is below average), video-sync=display-resample causes stuttering with ANGLE. With es=no render timing is the same, but no stuttering.
Only happens when hwdec is enabled (any).

**Comment by lachs0r** [comment]
Still an issue?

**Comment by TallsFalls** [comment]
Not an issue anymore, I think it was fixed a while ago. Thanks.
