### ISSUE TITLE
[feature request] exit keyboard shortcut

### ISSUE THREAD

**Issue by mattia-b89** [mpv-player/mpv#3302]
I'd like to have "CTRL+q" as keyboard shortcut for quitting application
I'm a linux user and I expect this keyboard combination

**Comment by Argon-** [comment]
Then feel free to add it...? https://mpv.io/manual/stable/#keyboard-control

**Comment by wm4** [comment]
But ctrl+q already works?

**Comment by mattia-b89** [comment]
I opened this issue in order to standardise mpv (IMHO, a common ''issue''
in the Linux world...).

Just for this reason I tagged it as ''feature request''... or I should
tagged it as ''enhancement''
On 3 Jul 2016 1:37 p.m., "V. Lang" <notifications@github.com> wrote:

Closed #3302 <https://github.com/mpv-player/mpv/issues/3302>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mpv-player/mpv/issues/3302#event-711379402>, or mute
the thread
<https://github.com/notifications/unsubscribe/AAhSt_8hzk7JCHIzjpI0v4XZYOmotQF4ks5qR57qgaJpZM4JDsMS>
.
