### ISSUE TITLE
Fetch subtitles on Windows/macOS

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3304]
Though there already are scripts to do this, it doesn't seem they were made to be used outside of a Linux environment. Or at least I have no idea on how to do it, and I couldn't find anything on Google about it. I'm using Windows for now, but I assume the same applies for macOS.

**Comment by wiiaboo** [comment]
subliminal should work fine in Windows and Mac, it's Python.
Install Python, `pip install subliminal` in prompt/terminal and you should be good to go.

**Comment by firewater2** [comment]
Damn, that seems easy. Last time I checked the things I found felt unfriendly to people who don't know about code.

I installed Python, and then subliminal.

![subliminal](https://cloud.githubusercontent.com/assets/11010067/16543842/b29abffc-40c3-11e6-8756-4ad517350273.png)

Then I used [the code](https://github.com/vayan/autosub-mpv), but I instantly get"Download failed" error after pressing 'b'.

I believe the line that isn't working for me is:

` subl = "/usr/local/bin/subliminal" -- use 'which subliminal' to find the path`

I tried writing "which subliminal" on cmd, but nothing happened. I assume it must be prefaced by something related to Python, but I don't know what that would be. I did try finding the path by searching it myself, and ended on what seems to be the path: "C:\Users\User\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\subliminal", but if I paste that into the line mentioned above, I get no response when pressing 'b', and when I change all the "\" into "/", I get the download failed error again.

**Comment by Argon-** [comment]
Just for the record: on OSX it works the same as on Linux.

**Comment by cmdrkotori** [comment]
@firewater2: 
>I tried writing "which subliminal" on cmd, but nothing happened.

The Windows equivalent is in powershell: `(Get-Command subliminal).path`.

**Comment by wm4** [comment]
This is up to script authors, and as it was mentioned, it actually seems to work already.

**Comment by firewater2** [comment]
@cmdrkotori 
Thank you very much!!! That command provided the correct path (which is one I had actually tried, minus specifying subliminal.exe), and it works super nicely.

Sorry that I didn't mark this as question. I hope it serves as a good Google result for people who wanted to do the same thing!

**Comment by Hrxn** [comment]
For the record:

There is not only Powershell, the equivalent (more or less) to `which` on Unix in `CMD` is `WHERE /?`
