### ISSUE TITLE
Open picture without --fullscreen or with --no-osc fails on ubuntu 16.04

### ISSUE THREAD

**Issue by lionep** [mpv-player/mpv#3310]
### mpv version and platform

Reproduced on mpv git-1c5fd2d and mpv 0.18.0, on ubuntu 16.04
### Reproduction steps

```
# Fails
mpv --no-osc --fullscreen sample_file.jpg
# Works fine 
mpv --fullscreen sample_file.jpg
```
### Expected behavior

The picture should render fine in fullscreen
### Actual behavior

A small part of the picture is displayed in a corner of the screen
### Log files

http://sprunge.us/TFJZ

**Comment by wm4** [comment]
Works here (but on nvidia).

Does it render correctly if you toggle FS twice after the window was created?

**Comment by lionep** [comment]
After toggling FS it displays fine.  
I'm on Intel Iris Graphics 6100, and on Intel Iris 540.

**Comment by mc4man** [comment]
Works fine here on 16.04 with Haswell (4600) & Skylake (HD520)

**Comment by lionep** [comment]
It works also fine on a Braswell Celeron, I'm testing this on a fresh install on the Iris 540.

**Comment by wm4** [comment]
Desktop environment and drivers possibly matter more than the GPU.

**Comment by lionep** [comment]
After some investigation, it happens when DRI 3 is enabled in xorg.conf

**Comment by mc4man** [comment]
Yeah, DRI 3 would do as described with slight variation on different GPU's. Also has a minor effect if not setting -fs 
With osc enabled widow opens correct but image only in top corner, fills in after 1/2 sec or so
With -no-osc then the window only fills in fully when moved
(all of above on the so called 0.18 release

**Comment by tjackson** [comment]
I've observed this bug on Intel IvyBridge for at least 2 years now, only with DRI3 enabled -- modesetting or xf86-video-intel both. LIBGL_DRI3_DISABLE=1 fixes it. It's been mentioned in passing on freedesktop.org, but didn't get any attention.

Oddly it happens with -vo opengl but not -vo vaapi.

**Comment by tjackson** [comment]
This seems to have been worked around in mpv recently, at least for me. Only tested between v0.23 (fail) and yesterday's master.
