### ISSUE TITLE
Any way to add Joystick support ?

### ISSUE THREAD

**Issue by okabekudo** [mpv-player/mpv#3320]
I miss the joystick support very much I just got it working very nicely in mplayer and I wanted to activate it in mpv and then I see in one of the changelogs that you removed it. :/ You don't have to add it again I know it caused big issues, but is there a way to add it again, like a patch file that I just could apply to my build? As said you don't have to include it again. I just would be very happy to use it.

**Comment by garoto** [comment]
I have no answer for you, but there's always AntiMicro (https://github.com/AntiMicro/antimicro).

**Comment by lachs0r** [comment]
Duplicate of #2678.
