### ISSUE TITLE
OSD slider is unintuitive near edges

### ISSUE THREAD

**Issue by DerpMcDerp** [mpv-player/mpv#3321]
Lets say you open a movie in a maximized player window and you want to watch the last couple of seconds of the movie (e.g. some movies have information that flashes for a brief time at the end and you want to be able to pause and read it). It seems like what you should be able to do is click a few pixels to the left of the right border and have it skip to there.

This doesn't work though. It seems like what mpv does is that treats the pixels about half a diamond width as synonym for the last frame of the movie.

i.e. here is how it currently works:

```
  _________________________
  | / \
  |/   \
  |\   /
  | \ /
  -------------------------
  ^--^
    \--- clicking anywhere here takes you to 0:00
```

Here is how it should work:

```
     ______________________
    /|\
   / | \
   \ | /
    \|/
     ----------------------
  ^--^
    \--- clicking anywhere here takes you to 0:00
```

i.e. just display the left and right borders of the slider to the center of the diamond rather than at the edges but keep the hit boxes as is.

**Comment by wiiaboo** [comment]
Have you tried `--script-opts=osc-seekbarstyle=bar`?

**Comment by Argon-** [comment]
That's just how this slider style is supposed to work. Imo it would look quite weird if the slider were to leave the bar like you indicated in the second ascii art.
Just select a different style to something that is more intuitive for you.

**Comment by DerpMcDerp** [comment]
The diamond could be clipped if it overflows the bar to make it look less weird.

**Comment by Argon-** [comment]
Implying a clipped diamond looks less weird ;)

**Comment by ChrisK2** [comment]
Won't be changed. Use the bar style if you like the normal behaviour.

**Comment by JamesTheAwesomeDude** [comment]
I agree. This current system makes no sense. The pointers at the top and bottom of the diamond DON'T line up with the playback position relative to the bar??

When the diamond is pointing to the 3% mark on the bar, the video's only 1% played, and when it's pointing to the 97% mark, the video's already 99% played.

This behavior would make sense if the diamond were a square (because then it would be analagous to a scrollbar), but the pointers at the top and the bottom of the diamond absolutely seem like they should be pointing to, well, the playback position!

**Comment by ChrisK2** [comment]
I agree but I don't have a good-looking solution to this, besides the bar style. If you have a suggestion on how to style this, I'm happy to listen.

**Comment by JamesTheAwesomeDude** [comment]
How about something like this?

 * The actual seek area is shown, and the diamond points refer to appropriate, intuitive positions inside of it
 * The diamond is not clipping outside of the "seek area" visually

Best of both worlds, we have the seek bar actually functioning sanely, but we don't clip the diamond.

![mpvshot-2016-09-08-00 00 00 022](https://cloud.githubusercontent.com/assets/2776014/18371892/b465120a-75fd-11e6-8efb-fd5d3405cb93.png)
