### ISSUE TITLE
Volume not set correctly

### ISSUE THREAD

**Issue by ParadoxSpiral** [mpv-player/mpv#3322]
### mpv version and platform
paradoxspiral@archer> mpv --version
mpv git-16b48a4 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Fri Jul  8 12:59:51 CEST 2016
ffmpeg library versions:
   libavutil       55.24.100
   libavcodec      57.46.100
   libavformat     57.38.100
   libswscale      4.1.100
   libavfilter     6.46.101
   libswresample   2.1.100
ffmpeg version: N-80344-g6fd4145

Linux archer 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux

### Reproduction steps
1. ```mpv --no-config --volume 30 --profile=pseudo-gui ```
2. Switch volume to see what it's at in pseudo-gui
3. Load file
4. Switch volume to see what it's at

### Expected behaviour
Volume = 30 at step 2

### Actual behaviour
Volume = 100 at step 2
Volume = 30 at step 4

### Log files
http://sprunge.us/jFEW

**Comment by wm4** [comment]
I'll
- remove the ``--softvol`` option (or rather deprecate it and make it do nothing)
- make ``--volume`` and the ``volume`` property always control softvol
- make the ``volume`` property behave as expected
- add new options/properties for hardware volume
- do the same for mute

Does this sound ok?

**Comment by ParadoxSpiral** [comment]
Thanks, sounds good to me.

**Comment by LebedevRI** [comment]
To whoever else does not like the softvol mixer, and would like to access the old behavior, thanks to #mpv channel for suggestion:

```
$ mkdir -p ~/.config/mpv && cat <<EOL >> ~/.config/mpv/input.conf
9 add ao-volume -2.0
/ add ao-volume -2.0
0 add ao-volume 2.0
* add ao-volume 2.0
EOL

```

That should rebind the usual volume keybindings back to changing the hw volume.
Until something else is removed, anyway.

**Comment by soredake** [comment]
@pigoz @haasn @kevmitch @Akemi @rossy @wiiaboo can you please re-add [this commit](https://github.com/mpv-player/mpv/commit/7621a028bf555c9ed0430501bc6eac2fa204114c) to mpv? It doesn't hurt to have an option for users that want to control pulseaudio instead of softvol.
