### ISSUE TITLE
Man-page clarification?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3323]
From the man-page at mpv.io https://mpv.io/manual/stable/#options-hwdec

> vdpau is usually safe. If deinterlacing enabled (or the vdpaupp video filter is active in general), it forces RGB conversion. The latter currently does not treat certain colorspaces like BT.2020 correctly (which is mostly a mpv-specific restriction). **If the vdpauprb retrieves image data without RGB conversion, but does not work with postprocessing.**

What does the bolded sentence mean, in simple words?

**Comment by wm4** [comment]
It means I suck at checking my writing.
