### ISSUE TITLE
Interpolation makes 60fps Videos stutter.

### ISSUE THREAD

**Issue by dragons4life** [mpv-player/mpv#3325]
### Play 60fps video

-what happens
### Interpolation turns off? no stutter when interpolation is on?

-whats not supposed to happen
### Stutter

https://i.lithi.io/70Ma.webm ( For some reason the video capture does not capture when I turn off Interpolation, and is almost at the end you can see a new line on CMD when I do, ignore the first one since that was to activate Interpolation since I was not sure if it was on or not. **0:50** )
(You can see huge stutter from **0:39**)

https://upload.teknik.io/k7xFE.txt - log
https://i.lithi.io/529W.conf - conf

**Comment by haasn** [comment]
Known issue, happens because of mpv not reliably knowing when to turn interpolation off.

You can work around it by using a higher setting of ``interpolation-threshold``, I personally use 0.01.

**Comment by dragons4life** [comment]
Yeah that's what I though, I'll try your settings to see if it fixes it a bit or just keep on manually disabling interpolation.

**Comment by wm4** [comment]
> Known issue, happens because of mpv not reliably knowing when to turn interpolation off.

So how can this be fixed?

**Comment by haasn** [comment]
interpolation-threshold is compared against `abs(disphz/vfps - 1)` where `vfps` is the speed-adjusted display FPS.

Maybe we want to be comparing against the original display FPS, and not the speed-adjusted display FPS.

**Comment by Hrxn** [comment]
The original display FPS, is that what can be set via `--display-fps=<fps>`? ([Man link](https://mpv.io/manual/master/#options-display-fps))

Because it also mentions `--video-sync=display-* ` there, so is this still relevant with `interpolation=no`?

By the way, where does this apparently pretty significant variance in speed-adjusted display FPS come from? Is that an indication for some driver issue or maybe another problem?

**Comment by JulianLai** [comment]
What does the speed-adjusted display FPS mean? Is it the video's fps?

**Comment by haasn** [comment]
@JulianLai Almost, but in the case of e.g. 23.976 Hz videos on a 60 Hz monitor, the “display-adjusted” vfps would be 24.000 Hz and not 23.976 Hz.

Btw, this issue seems to have fixed itself on my end, I no longer get any flickering even with the default value of `interpolation-threshold`.

**Comment by dragons4life** [comment]
>tscale=oversample
>interpolation
>video-sync=display-resample
https://i.lithi.io/WiFH.webm

>interpolation
>video-sync=display-resample
https://i.lithi.io/hBGi.webm

Still happens on my end

**Comment by haasn** [comment]
@dragons4life That video confuses me. Why does it still happen with interpolation off?

**Comment by dragons4life** [comment]
Testing out youtube videos and local videos, and they do seem to not have this problem (they did before iirc), so mostly it's just twitch.

https://www.youtube.com/watch?v=79ImZE0K7xc
https://www.youtube.com/watch?v=anrvBD4aTGY
https://www.youtube.com/watch?v=u-d0q-RKr5s

Maybe it's twitch? maybe it's with streamed videos in general?

@haasn were exactly? because the only thing I saw it was not so smooth frames from the camera itself (maybe), but it was never as bad as it was with interpolation.
