### ISSUE TITLE
how to boost audio in ver 0.18.1?

### ISSUE THREAD

**Issue by meritozh** [mpv-player/mpv#3330]
### mpv version and platform
ver. 0.18.1 in macOS
### question
For older version, I use
```
softvol=yes
softvol-max=200
```
but in the latest release, `softvol` has been deprecated. Now how to set to boost audio?

**Comment by wiiaboo** [comment]
The **option** is deprecated because now `softvol=yes` is the default. Just erase `softvol=yes` and change `softvol-max` to `volume-max` and you're done.

**Comment by meritozh** [comment]
thanks, @wiiaboo
