### ISSUE TITLE
ICC Profiles on OS X

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#3333]
### mpv version and platform
Built from source on 2016-07-09 at 18:11:03 with: --with-vapoursynth --with-bundle
OS X El Capitan 10.11.5

### Reproduction steps
Selection of a system-wide icc profile e.g "Color LCD Calibrated.icc", and setting icc-profile suboption to another, e.g. "Color LCD".

### Expected behavior
Same colors as setting "Color LCD.icc" for system-wide profile and using icc-profile-auto suboption.

### Actual behavior
Similar colors to using icc-profile-auto suboption with "Color LCD Calibrated.icc"

### Log files
Using icc-profile-auto : http://sprunge.us/WBff
Using custom profile : http://sprunge.us/XagA

**Comment by haasn** [comment]
The log indicates that mpv is in fact loading "Color LCD.icc", which is different (based on the has value) from the system-wide profile.

Perhaps you are confusing the ICC profile with the loaded calibration curves? Try comparing with the gamma table reset. Not sure how to do that on OS X, but on Linux it's done with `xgamma -gamma 1.0`.

**Comment by kkanungo17** [comment]
Nothing about resetting gamma tables in OS X anywhere. :(

It seems to me like OS X applies the system-wide profile correction over mpv's own.

**Comment by haasn** [comment]
OS X shouldn't be modifying the mpv window at all (i.e. no further color correction is being done), but OS X is still in charge of loading the gamma tables embedded in most ICC profiles into your video card's LUTs.

The easiest way to find out which of the two is the case is by taking a screenshot of your desktop while displaying the mpv window. If the difference is in the gamma table alone, it will not show up on a screenshot. But if the screenshot itself differs, then OS X is mangling mpv's output (which would be considered a bug.

**Comment by kkanungo17** [comment]
The same problem occurs in the desktop screenshot. With mpv using "Color LCD.icc", if it has been set as the system-wide profile, then colors are as they should be, but using "Color LCD Calibrated.icc" changes the colors to the current profile.

The screenshot, if it's any help : http://imgur.com/95asrVR

**Comment by kkanungo17** [comment]
so it's just a gamma table problem?

**Comment by haasn** [comment]
Can you upload both screenshots?

- One with `Color LCD Calibrated.icc` set as the system profile and `:icc-profile="Color LCD.icc"` set in mpv
- One with `Color LCD.icc` set as the system profile and `:icc-profile-auto` set in mpv

I ask because it's also possible that taking the screenshot itself tagged the screenshots with metadata about the ICC profile that was loaded at the time.

**Comment by kkanungo17** [comment]
System profile "Color LCD.icc" with icc-profile-auto : http://imgur.com/sCgFHZg
System profile "Color LCD Calibrated.cc" with icc-profile="Color LCD.icc" : http://imgur.com/GCrOb0J

**Comment by haasn** [comment]
The screenshots look identical to me, they're not even tagged at all.
