### ISSUE TITLE
Building pdf failed

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#3338]
### mpv version and platform
commit 588b2f4

### Reproduction steps
Compile with `--enable-pdf-build`

### Log files
[mpv-build-err.txt](https://github.com/mpv-player/mpv/files/365591/mpv-build-err.txt)

**Comment by SchweinDeBurg** [comment]
I can confirm that. Using Python 2.7 10 and the latest versions of needed packages installed from PIP.
