### ISSUE TITLE
Maximum audio volume is 130%

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#3339]
### mpv version and platform
commit 588b2f4 , win10-x64

### Reproduction steps
Pressing continously '0' key while playing video until the osd displayed `130%`

### Expected behavior
Should be `100%` when max out audio volume in mpv

### Actual behavior
Showing `130%` after max out audio volume in mpv

**Comment by lachs0r** [comment]
130% means it’s amplified. You can configure the limit with the `--softvol-max` option.

**Comment by sda89ha9** [comment]
https://github.com/mpv-player/mpv/commit/995c47da9afacfcc30d8a17d2f2a2268fbf4fdb9

**Comment by cranes-bill** [comment]
So, there is no way anymore to control system mixer from MPV, right?
I would like to bring back previous volume control behaviour. Can somebody tell me how can i do it, please!

**Comment by sda89ha9** [comment]
- system or per-application volume can still be controlled with the
  ao-volume and ao-mute properties (there are no command line options)
https://github.com/mpv-player/mpv/blob/master/DOCS/interface-changes.rst

i.e., input.conf
9 add ao-volume -2
0 add ao-volume 2

**Comment by cranes-bill** [comment]
OK, probably due to my bad English, i was not understood...
I just want the old volume control, where volume bar looks without „_delimiter_“ on 100% (see the picture) and increasing the MPV volume also increase the system volume (Pulse audio).

![capture du 2016-07-17 10-u-19](https://cloud.githubusercontent.com/assets/5161278/16899613/ed0cab96-4c12-11e6-9b88-f102b349838a.png)

**Sorry for the bad English!**

**Comment by cranes-bill** [comment]
That's what i'm talking about. This is an older MPV version:

![capture du 2016-07-17 13-u-19](https://cloud.githubusercontent.com/assets/5161278/16900173/ba59676c-4c25-11e6-9625-abff99294214.png)

It also starts with latest volume level set....
Can somebody tell me where this change have been making, please!

**Comment by w17t** [comment]
> 130% means it’s amplified. You can configure the limit with the `--softvol-max` option.

thanks, according to the [manual](https://jlk.fjfi.cvut.cz/arch/manpages/man/community/mpv/mpv.1.en) it seems to be a (deprecated) alias for `--volume-max` option

> --softvol-max is a deprecated alias and should not be used. 

the range is `100-1000` defaulting to `130` %

**Comment by CounterPillow** [comment]
almost like this is an issue from 2016 and the option has changed since then
