### ISSUE TITLE
Mpv after version 0.14 freezes when  constantly pressing Alt+Tab in Windows 10

### ISSUE THREAD

**Issue by stepshal** [mpv-player/mpv#3342]
Maybe it just for me, but after mpv version 0.14 when you open browser and mpv both in fullscreen and start pressing constantly Alt+Tab, it may work, it can do not do anything, and then freeze where you cannot do anything but reboot. In Windows 10. In 0.14 it's work just fine, without problems.

**Comment by stepshal** [comment]
And it's blinking when you Alt+Tab in 18.1, and some more visual glitches, when you go in fullscreen it grab piece of backgroung from window under it.

**Comment by sda89ha9** [comment]
gpu? --hwdec=? --vo=?

**Comment by stepshal** [comment]
@sda89ha9 Yeah, changing --vo to direct3d do the thing, opengl doesn't do it anymore, i closing issue.

**Comment by stepshal** [comment]
When i set --vo in cmd, it's working, but you add it in mpv.conf, it's stays the same.

**Comment by stepshal** [comment]
@sda89ha9 Changing --vo seems to work, thanks.
