### ISSUE TITLE
Startup error: mpv: undefined symbol: ass_set_check_readordere

### ISSUE THREAD

**Issue by Marcostux** [mpv-player/mpv#3344]
### mpv version and platform

1:0.17.0-1~xenial Ubuntu 16.04 64 bits

### Reproduction steps

I installed following these steps 

sudo add-apt-repository ppa:djcj/vapoursynth 
sudo apt-get update 
sudo apt-get install mpv

### Expected behavior

Start and normal operation

### Actual behavior

user@user:~$ mpv 
mpv: symbol lookup error: mpv: undefined symbol: ass_set_check_readorder

### Log files

Impossible to create log file, error

**Comment by lachs0r** [comment]
1) This version of mpv is outdated
2) It has been linked to a libass version that is not installed on your system (so it’s a broken package because it doesn’t have proper dependencies)

**Comment by Marcostux** [comment]
Oh sorry, this is the version with vapoursynth support recommended in Svp: [https://www.svp-team.com/wiki/SVP:Linux](url) 

What should I do?

**Comment by mc4man** [comment]
Try upgrading your libass5 package to the one from the ppa (- 0.13.2-1

**Comment by Marcostux** [comment]
> Try upgrading your libass5 package to the one from the ppa (- 0.13.2-1

It worked! thanks!!
