### ISSUE TITLE
DVD menus / Playing entire DVD from a single file

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3345]
1. Will DVD menus be supported at some point? They often include extras that don't always seem accessible in other forms.
2. Every time I'm gonna play a DVD I have to make a playlist of the VTS_XX_X files (for example, I open MPV, and then drag VTS_02_1, VTS_02_2, VTS_02_3, and VTS_02_4 into the window). This is inconvenient because I use Kodi to play videos, and I clearly cannot do any dragging in there. Instead, Kodi recognizes the "VIDEO_TS.IFO" file as the entire movie, which should be fine, but in my testings, opening said file only works (as in, the entire film is played) in 2 out of 5 DVDs I've tried. In the other 3, MPV opens and closes itself immediately. edit: VLC cannot play any of these 3 either, so it must be a problem with the files. Though it's not related with MPV, I wonder if anyone knows why these might be failing.

**Comment by paulguy** [comment]
According to the man page, it appears you can just point mpv to the base disc path, which contains the VIDEO_TS directory, either by simply providing that on the command line or using `--dvd-device=PATH` along with the dvd:// URL.

**Comment by lachs0r** [comment]
1) I’m fairly confident DVD menus will not be supported ever, unless someone steps up and writes a proper library for DVD support. libdvdread/libdvdnav are not very helpful, to say the least.
2) `dvd:///path`, `--dvd-device=path dvd://` or simply passing the DVD root directory to mpv should work. Note that 0.26.0 disables support for DVD structures by default for the same reason.

**Comment by firewater2** [comment]
Thanks for the answers guys, I'll try them when the problem occurs again! A shame about DVD support mostly in regards to preservation, but then again I suppose it must be quite a challenge to take on that issue (with relatively little reward).

**Comment by fhlfibh** [comment]
@firewater2 Afaik, Kodi 18 supports menu now (at least, BD menu, but maybe DVD menu works there too). In theory it might be possible to attach mpv to Kodi as an external player and to configure all this system so that Kodi plays menus while mpv plays an av-stream itself.
Unfortunately, at the moment personaly I have neither Kodi nor time for testing this theory...

**Comment by firewater2** [comment]
Do you really think that's possible?! Sounds really interesting... maybe some day!
