### ISSUE TITLE
Render on GPU, display on IGP ?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3346]
Hi!

If I have a CPU with IGP, a monitor attached to IGP, and a descrete GPU-- is it possible to set MPV so that it would render the picture on GPU, and then send that picture to IGP to display on attached monitor? 

Regards,
Alex

**Comment by ArchangeGabriel** [comment]
Not sure what could be done on MPV side, but depending on your setup you might already make this work with hwdec offloading.

Is this a laptop or a desktop (not sure if it matters though)? Linux or Windows? What brands are the discrete GPU and the IGP?

**Comment by haasn** [comment]
Unlikely

**Comment by ArchangeGabriel** [comment]
VDPAU offloading works. But that means Linux+nvidiaGPU. The AMD equivalent might work too.

**Comment by fhlfibh** [comment]
@ArchangeGabriel 
No, I don't mean "hardware decoding".
Optimus Hybrid driver for Nvidia+Intel is something similar to what I mean (at least, as far as I understand how it works). Let's say we have Nvidia GPU and Intel IGP, with a monitor attached to Intel. MPV decodes picture on GPU with VDPAU, reads result back to RAM, makes all other processing with GPU, and sends the final picture to IGP to display it on screen. Not sure if the above is correct, but it somehow illustrates what I'm asking about: to separate rendering from displaying.

**Comment by ArchangeGabriel** [comment]
VDPAU is hardware decoding. So for this one, it could work the Optimus way indeed. But for other things (filters outside VDPAU, processing), I don’t know.

**Comment by Jj0YzL5nvJ** [comment]
Hmm... maybe [libvdpau-va-gl](https://github.com/i-rinat/libvdpau-va-gl) can do the trick.

**Comment by fhlfibh** [comment]
Closing my old issue.
Note for future readers: as of now, mpv-0.23.0 can do somehow opposite trick -- it can decode video stream on Intel iGP with VAAPI, and send it to GPU (Nvidia in my case) for futher processing and displaying. Here on issue tracker there's a separate discussion on that, but I'm too lazy to search for the link.
