### ISSUE TITLE
Crash on exit with hwdec=d3d11va after b46eaa3

### ISSUE THREAD

**Issue by igv** [mpv-player/mpv#3348]
### mpv version and platform

mpv git-77e1e8e Win 10
### Reproduction steps

Open any h.264 video from command line with --hwdec=d3d11va option
### Expected behavior

No errors after mpv shut down
### Actual behavior

There is a message "mpv has stopped working"
### Log files

From Administrative Events:

```
Faulting application name: mpv.exe, version: 2.0.0.0, time stamp: 0x578c8c10
Faulting module name: d3d11.dll_unloaded, version: 10.0.10586.494, time stamp: 0x5775e29e
Exception code: 0xc0000005
Fault offset: 0x000000000006445b
Faulting process id: 0xd64
Faulting application start time: 0x01d1e18922b16390
Faulting application path: e:\Programs\mpv\mpv.exe
Faulting module path: d3d11.dll
```

**Comment by wm4** [comment]
Is this with HEVC on Intel? I can't reproduce with h264, but I know there are weird HEVC issues, for which I'm blaming the drivers.

**Comment by igv** [comment]
Codec doesn't matter, happens always when hardware decoding is used. nVidia 660.

**Comment by rossy** [comment]
Not sure if it's related, but I had consistent crashes on exit until I updated my drivers (from 368.39 to 368.69.) I can't remember if d3d11va was involved or not.

**Comment by igv** [comment]
I have latest driver version 368.81.
Actually not sure if it happens with every video, so here is a [sample ](http://download.openbricks.org/sample/H264/big_buck_bunny_720p_H264_AAC_25fps_3400K_short.MP4), crashes every time with it.

**Comment by igv** [comment]
Also note thar if you tun mpv not from command line it will crash silently, you won't see "mpv has stopped working" message.

**Comment by igv** [comment]
Still crashes on a fresh Windows installation with a latest drivers and mpv. There is a message "mpv has stopped working" now even if mpv wasn't started from command line.
But I will probably stop using hwdec.

**Comment by rossy** [comment]
Btw I can repro this consistently now. For some reason, the error reporting dialog doesn't show when I launch mpv normally and then close it, but a werfault.exe process will appear briefly in the task manager. When I launch mpv in a debugger, play some video with hwdec=d3d11va and close it, it will almost always crash with an EXCEPTION_ACCESS_VIOLATION.

It always happens after d3d11.dll is unloaded. When decoding with hwdec_d3d11egl, only ANGLE has a reference to d3d11.dll, so d3d11.dll is unloaded when ANGLE calls FreeLibrary. It seems like a thread owned by the Nvidia driver (nvwgf2umx.dll) tries to call functions in d3d11.dll after it's unloaded (RIP is set to an address where d3d11.dll used to be.)

I have no idea why this is happening though. If hwdec uninit happens before vo uninit, ANGLE's reference to d3d11.dll should still be alive while any hwdec-related objects are alive. That said, we might be able to fix this by calling d3d_load_dlls() in all cases, even when only ANGLE has to call into d3d11.dll directly. That way, d3d11.dll will never be unloaded.

**Comment by wm4** [comment]
Sounds good enough.

**Comment by igv** [comment]
Seems fixed.
