### ISSUE TITLE
Incorrect encoding of a glyph-symbol

### ISSUE THREAD

**Issue by rokorok** [mpv-player/mpv#3352]
I'm having some trouble with displaying a symbol tagged as {\fe2}F in .ass-file.
Here's a link to the file: https://www.dropbox.com/s/a6bld9dv7bh9g4p/s3.ass?dl=0
Should I use particular --sub-codepage for this?

### mpv version and platform
0.18.1, Windows 10
### Expected behavior
https://i.imgur.com/uuEnoBH.png
### Actual behavior
https://i.imgur.com/6jACxVB.jpg

**Comment by wm4** [comment]
`\fe2` indicates that wingdings should be used, so I guess this is a legitimate bug. But it's a libass one, not a mpv one, so I'm closing this.

> Should I use particular --sub-codepage for this?

No, the file is UTF-8. But the subs use some weird legacy tag to change the encoding just for the `F`.

**Comment by wm4** [comment]
PS: the libass bug tracker is here: https://github.com/libass/libass/issues
