### ISSUE TITLE
mpv plays videos too fast on the particular FreeBSD laptop

### ISSUE THREAD

**Issue by yurivict** [mpv-player/mpv#3353]
On the FreeBSD laptop all videos are playing too fast. Seconds counter is visibly running too fast.
https://github.com/mpv-player/mpv/issues/3351 is probably related because it happens on the same system.

Time in general runs fine on this system.
mpv doesn't use pulseaudio.
mplayer doesn't have the same problem.

### mpv version and platform
0.18.1

**Comment by wm4** [comment]
Log file missing.

**Comment by yurivict** [comment]
Sorry, log is in https://github.com/mpv-player/mpv/issues/3351 - same log.

**Comment by yurivict** [comment]
Ok, this was an older log. Later I turned off the pulseaudio, and with OSS it still plays too fast.

**Comment by wm4** [comment]
Does it happen with ``--ao=null``?

**Comment by yurivict** [comment]
When I disabled pulseaudio, I turned the port option off. But --ao=pulse is still available even without the pulseaudion option, which is weird.

With --ao=null and --ao=oss the problem is gone. So the pulseaudio is a culprit.

**Comment by wm4** [comment]
>So the pulseaudio is a culprit.

Yes, everything points towards it.

**Comment by yurivict** [comment]
It appears there is something wrong with time on FreeBSD on this machine, or with the pulse audio, not with mpv.
