### ISSUE TITLE
mpv still offers the "pulseaudio" option for --ao when pulseaudio is disabled

### ISSUE THREAD

**Issue by yurivict** [mpv-player/mpv#3355]
When PULSEAUDIO=off in the FreeeBSD port, configure says that it is disabled:
```
Checking for PulseAudio audio output                                      : disabled 
```

However, mpv still offers this option for --ao:
```
$ mpv --ao=help
Available audio outputs:
  pulse          : PulseAudio audio output
  oss            : OSS/ioctl audio output
  null           : Null audio output
  pcm            : RAW PCM/WAVE file writer audio output
```
### mpv version and platform
0.18.1

**Comment by wm4** [comment]
You're probably not using the correct mpv binary?

If mpv was built with ``--disable-pulse``, the resulting binary will most definitely not have an pulse output.

**Comment by haasn** [comment]
Can confirm that I do *not* see ao_pulse in my copy of mpv (built with `USE="-pulse"` under gentoo)
