### ISSUE TITLE
mpv fails to find subtitles in the Subtitles/ folder

### ISSUE THREAD

**Issue by yurivict** [mpv-player/mpv#3356]
mpv doesn't find subtitles in "Subtitles/" folder.

While playing the file "some-file.mkv" mpv doesn't find its subtitles which are in "Subtitles/some-file.sub" and "Subtitles/some-file.idx".

Copying files from Subtitles/\* to the same folder makes mpv find the subtitles.
### mpv version and platform

0.18.1

**Comment by garoto** [comment]
Do you have `--sub-paths` set to search for a "Subtitles" dir?

**Comment by yurivict** [comment]
I didn't set this. But I think it is best if ```--sub-paths``` will have a default that will represent the most common cases.

For example, the default could be: ```--sub-paths=ass:srt:sub:Sub:subs:Subs:subtitles:Subtitles```

**Comment by stefanos82** [comment]
OK, this option partially worked for me, but now it raises another concern: It cannot parse more than one subtitle.

Imagine you have a movie named "foo" and you have a folder with various subtitles. The only subtitle it will work would be the one that has the same name as the movie. 

If you have named the rest of your subtitles as "foo (dutch).srt", "foo (french).srt", but left English as "foo.srt", then it would see only the last (English) subtitle.

Is this behavior normal? Also, why can't I click on the default UI window and choose which subtitles to use? That would be a lot easier this way.

Cheers.

**Comment by yurivict** [comment]
I agree. mpv should show all subtitles if they are under the folder where the movie is. It should be made as easy as possible to use.

**Comment by garoto** [comment]
I guess the `--sub-auto` parameter might have something to do with it. Try `sub-auto=fuzzy` in your mpv.conf.

https://mpv.io/manual/master/#options-sub-auto

**Comment by stefanos82** [comment]
@garoto `--sub-auto=fuzzy` did not work for me at all. Actually, it had disabled all subtitles. I decided to check `--sub-auto` with `all` option and that worked perfectly.

Question: I'm on GNU / Debian; where should I find `mpv.conf`?

**Comment by lachs0r** [comment]
Actually, yes. This would be a job for a libmpv frontend or a user script, as mpv itself doesn’t use a real UI toolkit.
