### ISSUE TITLE
Add pulseaudio volume control back

### ISSUE THREAD

**Issue by medhefgo** [mpv-player/mpv#3359]
With mpv 0.18.1, hardware volume control got removed, enforcing softvol. It doesn't remember the last set volume on next start and when using pulseaudio, clients should really expose their per-application volume and not insert some own volume filter unless requested.

**Comment by ParadoxSpiral** [comment]
Hardware volume control did not get removed.
It's accessible via [ao-volume](https://mpv.io/manual/master/#command-interface-ao-volume) and [ao-mute](https://mpv.io/manual/master/#command-interface-ao-mute).

**Comment by medhefgo** [comment]
Yes, your're right. But it doesn't behave like normal volume control by showing a volume slider.

**Comment by Gusar321** [comment]
There's no slider in the 1.8.1 release, but there is in git master.

**Comment by wm4** [comment]
Here's a branch that tries to improve the situation, doesn't seem to be too popular either, though: https://github.com/mpv-player/mpv/tree/shitmess

**Comment by daniell-balabit** [comment]
For anyone bumping into this, there's a quite easy workaround to rebind the default keys to control audio volume (from https://superuser.com/questions/1158926/how-to-make-mpv-use-the-pulseaudio-volume-controls-again):
```
$ cat ~/.mpv/input.conf
0 add ao-volume 2
9 add ao-volume -2
* add ao-volume 2
/ add ao-volume -2
m cycle ao-mute
```

**Comment by levaidaniel** [comment]
For anyone bumping into this, there's a quite easy workaround to rebind the default keys to control audio volume (from https://superuser.com/questions/1158926/how-to-make-mpv-use-the-pulseaudio-volume-controls-again):
```
$ cat ~/.mpv/input.conf
0 add ao-volume 2
9 add ao-volume -2
* add ao-volume 2
/ add ao-volume -2
m cycle ao-mute
```

**Comment by soredake** [comment]
@pigoz @haasn @kevmitch @Akemi @rossy @wiiaboo can you please re-add [this commit](https://github.com/mpv-player/mpv/commit/7621a028bf555c9ed0430501bc6eac2fa204114c) to mpv? It doesn't hurt to have an option for users that want to control pulseaudio instead of softvol.

**Comment by Akemi** [comment]
please don't ping people on various issues about the same thing. also don't abuse old closed issues, open a new one. no one is gonna care about it like this.
