### ISSUE TITLE
Regression in pulseaudio handling, 0.18.1 always starts with 100% volume.

### ISSUE THREAD

**Issue by markg85** [mpv-player/mpv#3362]
Hi,

I'm using ArchLinux and tend to stay fairly updated and am using ao=pulse as sound output.
A few days ago i started noticing that when i start mpv the volume is always at 100%.

Now the regression here is that you now seem to have two mpv volume levels. There is one in "pavucontrol" (the pulseaudio volume control application), changing the volume there changes the sound output in mpv, but the "volume percentage" in mpv stays exactly where it is. The opposite is also true, if you change the volume in mpv the volume slider in pavucontrol doesn't change accordingly.

This probably also causes the bug that the volume is at 100% at startup. The correct volume is set in pavucontrol, but apparently not being received by mpv.

At first i was blaming myself since i had just been playing with pulseaudio settings (as a user), but a clean user showed the exact same issues as i just described. So i downgraded mpv to 0.18.0 to see if that would fix things, and it did. It remembers the volume just fine, resumes at the level where it was left and changing the volume in pavucontrol changes it in mpv (and the other way around).

If there is anything you want me to test to get this debugged, command outputs to give.. Just ask :)

Best regard,
Mark

**Comment by markg85** [comment]
Would you mind elaborating why this is a "wontfix"?

**Comment by wm4** [comment]
The change is noted in the changelog. I don't feel like switching it back.

**Comment by markg85** [comment]
You mean the fix for https://github.com/mpv-player/mpv/issues/3322?

If that's so, then i don't understand how this fixes anything.
The actual and expected results of that report are now the case when pulseaudio is used.

Could you elaborate a bit more and perhaps explain how i can get the behavior back that used to be there? You must admit, it's not such a weird wish to have the previous volume back when you start mpv.

Also, as it currently is done is completely counter intuitive for the user because there are in effect 2 completely independent volume controls for mpv (on in mpv itself, one in pulseaudio)

**Comment by markg85** [comment]
bump.. i hope you could comment on this. I'd like to know if i have to go the config route.

**Comment by ParadoxSpiral** [comment]
@markg85 

>Could you elaborate a bit more and perhaps explain how i can get the behavior back that used to be there? You must admit, it's not such a weird wish to have the previous volume back when you start mpv.

Use git master, and ao-volume + ao-mute for volume control.

**Comment by markg85** [comment]
Ok, fair enough.
Next question :)

I have no clue which commands i have to fill in for those fields. Do you perhaps know the ones for pulseaudio?

Also, the volume bar now apparently can go to 130%. It's fine, but i would much rather limit it to 100%. Which setting do i need to change to make 100% the max volume?

**Comment by ParadoxSpiral** [comment]
1) You set those properties like you [set any other property](https://mpv.io/manual/master/#input-conf), e.g. `9 add ao-volume -1`

2) [volume-max](https://mpv.io/manual/master/#options-softvol-max). But you won't need this if you use ao-volume + ao-mute.

**Comment by markg85** [comment]
I don't get it.

How will that property magically work with pulseaudio?

**Comment by ParadoxSpiral** [comment]
I don't know how it works, if you want to know that read the code.
But that doesn't matter, does it? It works is what's important.

**Comment by markg85** [comment]
Really, just call me stupid if it's a silly question, but how do i set hat property?
I have a .config/mpv/mpv.cong file and it contains some properties (like  ao=pulse) and that seems to work just fine.

However, if i set:
ao-volume=-1

I keep getting:
Error parsing option ao-volume (option not found)
/home/mark/.config/mpv/mpv.conf:6: setting option ao-volume='-1' failed.

I must either be missing very obvious or it isn't obvious at all...

**Comment by kevmitch** [comment]
you don't set properties in mpv.conf, you modify them with keybindings in input.conf with lines like @ParadoxSpiral showed above, i.e.,

    9 add ao-volume -1

**Comment by wm4** [comment]
And here too: https://github.com/mpv-player/mpv/wiki/FAQ#i-want-the-old-pulseaudio-volume-control-back-on-linux

**Comment by markg85** [comment]
Why did nobody nor the faq page tells **anything** about replacing the **default** volume key bindings for these new ones?

And why has this been made so extremely overly complicated?
Couldn't there just be a implicit audio detection based on ao=<alsa, pulse, bla>
Then just handle the audio out differently when it's pulse, since you seem to be desperately looking for a way to manipulate audio. I still don't see why this had to be changed at all besides cleaning up old code.

Anyhow, changing the **default** keys is done by adding this in input.conf:
/ add ao-volume -2
SHIFT+* add ao-volume 2

**Comment by ParadoxSpiral** [comment]
>Why did nobody nor the faq page tells anything about replacing the default volume key bindings for these new ones?
The change was listed in the release notes, albeit not the implications (personally I'd like it to be more explicit).

>And why has this been made so extremely overly complicated?
It's just changing keybindings, nothing too difficult. This is extensively documented.
On the other side one of the big advantages is that you now have much simpler and arguably more deterministic control over these properties which I, as a user of libmpv, greatly appreciate.

>Couldn't there just be a implicit audio detection based on ao=
There could be, but imho implicit things are bad and add complexity. Changing the keybinding really isn't that complex.

>I still don't see why this had to be changed at all besides cleaning up old code.
To fix the unexpected behaviour I reported, and give more control. But cleaning old code is reason enough, and entirely up to the maintainer to decide.

**Comment by markg85** [comment]
@ParadoxSpiral to be frank, the fix for your "unexpected behavior" will cause many more people to experience "unexpected behavior" just because your case was fixed.

I have no say in this, i don't code nor contribute to mpv.. But if it were up to me i'd have closed your issue as wontfix. Specially now that i know the implications it has.

**Comment by haasn** [comment]
@markyg85 mpv volume persisting across videos is quite honestly “unexpected behavior” in my books, especially since nothing else in mpv does this sort of thing.

**Comment by markg85** [comment]
@haasn then there is a difference of expectation. What you consider as unexpected is what i would consider as expected. And i'm willing to bet that the majority of linux users has the same expectation as me (audio should restore to previous levels).

I know of no other video player that does what you describe. All players that i know resume audio volume from last time. That is in windows, mac and linux. Why would it have to be different for mpv?

**Comment by haasn** [comment]
> I know of no other video player that does what you describe. All players that i know resume audio volume from last time. That is in windows, mac and linux. Why would it have to be different for mpv?

Because mpv is a stateless, command-line, config-file driven, keyboard controlled minimalist player core/backend and the rest aren't? The fact that it also seems to appeal to the “GUI app” crowd is more the result of a bolted-on hack (pseudo-gui mode) than anything else.

Among command line tools, implicitly sharing state across sessions is a very weird thing to do. (And I like my mpv as a command line tool, any way)

**Comment by markg85** [comment]
I am using it on the command line for playing radio stations.
Also for video, but radio more often.

In the technological age we live in i really would consider it a massive bug if an application cannot restore the volume as it was. Command line and gui. Right now MPV by default can't (or doesn't want to) and i consider that a massive bug!

You would have a point if we were still in the alsa age without pulseaudio or dmix for volume levels per application. Then the app should leave the volume alone and play at whatever the master volume is set. But thankfully technology moved on for the better. It's ok if you think differently, but do realize that the vast majority of the people likes to have it's volume restored to whatever it was.

It would be a different case if you start the app with an argument telling the volume to be 100% to start with. Then it's just your setting that should work however the setting is implemented. But that's **not** the case by default so it shouldn't happen, but somehow it is now decided that it should.

**Comment by soredake** [comment]
@pigoz @haasn @kevmitch @Akemi @rossy @wiiaboo can you please re-add [this commit](https://github.com/mpv-player/mpv/commit/7621a028bf555c9ed0430501bc6eac2fa204114c) to mpv? It doesn't hurt to have an option for users that want to control pulseaudio instead of softvol.

**Comment by Akemi** [comment]
reverting that commit is (most likely) not an option, since there was an ao rewrite and other things since then. so no i won't. i also won't because i am not on linux and can't test it.

also, there is `ao-volume`. isn't that what you want?

if not please open a proper issue which explains what you actually want and what mpv does atm which is not desired. see the issue template.
