### ISSUE TITLE
Seeking in HLS streams flushes the buffer

### ISSUE THREAD

**Issue by yash1610** [mpv-player/mpv#3365]
### Reproduction steps
Load any hls stream for example, `https://walterebert.com/playground/video/hls/sintel-trailer.m3u8` or `https://secure.twitch.tv/sovietwomble/v/79771443`and once the stream starts seek using arrow keys
### Expected behavior
Should seek within the buffer it has built-up
### Actual behavior
Flushes the buffer -> Seeks as desired -> Starts buffering from 0 even if the seek location was within the buffer it previously built-up
[Screencast of the problem](https://drive.google.com/open?id=0BzPRIOqQO-fHSmo3aHNQSmg4b1k)
### Log files
http://sprunge.us/GLKd

------------------------------------
P.S if you can solve another query regarding HLS streams, I have cache-default set at a ridiculously high amount(1500000) so that it buffers the entire video that I want to watch, but this is not honored when playing HLS streams. HLS streams only buffer to the 10s+160kb mark as can be seen in my screencast, if you can point me in the right option to use for that it'd be appreciated. Also I am sorry if I am not using the right terms to define my issue. Thank you

**Comment by wm4** [comment]
HLS streams are fully implemented within the FFmpeg demuxer, and the mpv stream cache layer is circumvented. Thus seeks always discard all data, and the cache options won't work.

Would probably be hard to fix, unless we start creating our own file cache (which would have to cache each fragment).
