### ISSUE TITLE
mesa vaapi output s/w decode I420 vs YV12 question

### ISSUE THREAD

**Issue by AndyFurniss** [mpv-player/mpv#3370]
I am looking into a mesa vaapi issue and notice that mpv when doing s/w dec + vaapi vo apparently uses fourcc YV12.

I haven't looked at mpv code, but wondered if you did this to work around a mesa bug or if you do it for intel vaapi as well?

I was planning on correcting what I think is a mesa va bug - so if it was a workaround it may need changing. Though an added issue is that some recent vaapi encode patches seem to have broken things differently anyway....

**Comment by wm4** [comment]
What is the problem?

**Comment by AndyFurniss** [comment]
AMD have recently added vaapi encode to mesa, but if supplied with I420/IYUY or YV12 the conversion to nv12 switches u and v wrongly. I was looking into why and thought I had found it, in that the code apparently switches u and v for I420/IYUV rather than YV12 and reversing this fixed the issue.

While seeing what else hit this code with some printfs I see that mpv --vo=vaapi does when using s/w decode.

I thought ffmpeg outputs I420, but see that it is being seen as YV12 in mesa code from mpv. Without my (possibly wrong) "fix" this works correctly, with my fix mpv --vo=vaapi will show wrong colours.

I wondered if mpv had at some time worked around a mesa va bug by saying I420 was YV12.

Additional complication = the new AMD code also trashes mpv --vo=vaapi in different ways, but that's a separate issue.

**Comment by wm4** [comment]
--vo=vaapi should definitely work. Encoding is completely different anyway. FFmpeg has its own mechanism for this too. Wouldn't be surprising if FFmpeg accidentally swapped the planes, because they moronically decided to use FFmpeg pixfmts (and not vaapi FourCCs) to identify the format of vaapi surfaces.

**Comment by AndyFurniss** [comment]
When I mentioned ffmpeg I only meant that the s/w decode is being done by it via mpv - and I guess that when ffmpeg is used by mpv  for s/w decode it doesn't know what vo mpv will use.

The encode swap issue is currently being tested with gstreamer.

**Comment by AndyFurniss** [comment]
With older mesa mpv works fine. So it's just a mesa regression (well two), so closing.
