### ISSUE TITLE
Subtitle position issue of a MKV file with matroska subtitle.

### ISSUE THREAD

**Issue by sarkdavidson** [mpv-player/mpv#3371]
### mpv version and platform

**mpv 0.18.1 (C)** _2000-2016 mpv/MPlayer/mplayer2 projects
 built on Tue Jul 26 14:29:11 CST 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.1_
**Platform**
**OS X El Capitan** 
If you're not using git master or the latest release, update.
### Reproduction steps

**Matroska subtitle means subtitle style is editable, not embedded as a picture or separated ass,srt subtitle files.** 
Open MKV
Using "R""T" to change subtitle position, it works
Using "U" to turn on "ASS subtitle style override" to "Force"., it works.
Using "R""T" to change subtitle position, it works.
Turn off "Ass subtitle style override"
then pressing "R" "T"
### Expected behavior

Subtitle with ass subtitle style should work.
### Actual behavior

Nothing change.
### Log files

Make a log file made with -v or --log-file=output.txt, paste it to sprunge.us,
and replace this text with a link to it.

**Comment by lachs0r** [comment]
Well that’s exactly what disabling what is now called `--sub-ass-override` (which defaults to `yes`) is supposed to do.
