### ISSUE TITLE
Need help on Lua Scripts

### ISSUE THREAD

**Issue by jaimehrubiks** [mpv-player/mpv#3374]
I am new with Lua scripting and can't make it work.
This is my script, but I think that every script fails to work:
http://pastebin.com/kkerkZLk

### mpv version and platform

mpv 0.16.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Wed Apr  6 16:42:58 CEST 2016
(might be a little old, but it was compiled with raspberry pi support)

### Reproduction steps

Put script under ~/.mpv/scripts/myscript.lua

### Expected behavior

Work

### Actual behavior

[cplayer] Can't load unknown script: /home/pi/.mpv/scripts/test.lua

**Comment by wiiaboo** [comment]
Did you compile with lua?

**Comment by jaimehrubiks** [comment]
I did not compile it myself, I thought Lua was part of the software and would be always installed. I will check that out.

**Comment by wiiaboo** [comment]
Paste output of `mpv -v`
