### ISSUE TITLE
PATCH: small typo in demux_raw.c

### ISSUE THREAD

**Issue by ewtoombs** [mpv-player/mpv#3375]
From 6b18e12c3bf948ff88eacb2e32ac54c5d8d038ce Mon Sep 17 00:00:00 2001
    From: Eric Toombs <ewtoombs@uwaterloo.ca>
    Date: Thu, 28 Jul 2016 10:36:57 -0400
    Subject: [PATCH] s16be support was missing due to small typo.
    
    ---
     demux/demux_raw.c | 2 +-
     1 file changed, 1 insertion(+), 1 deletion(-)
    
    diff --git a/demux/demux_raw.c b/demux/demux_raw.c
    index 0d7517c..e4cf596 100644
    --- a/demux/demux_raw.c
    +++ b/demux/demux_raw.c
    @@ -55,7 +55,7 @@ const struct m_sub_options demux_rawaudio_conf = {
                        ({"u8",      PCM(0, 0,  8, 0)},
                         {"s8",      PCM(1, 0,  8, 0)},
                         {"u16le",   PCM(0, 0, 16, 0)}, {"u16be",    PCM(0, 0, 16, 1)},
    -                    {"s16le",   PCM(1, 0, 16, 0)}, {"u16be",    PCM(1, 0, 16, 1)},
    +                    {"s16le",   PCM(1, 0, 16, 0)}, {"s16be",    PCM(1, 0, 16, 1)},
                         {"u24le",   PCM(0, 0, 24, 0)}, {"u24be",    PCM(0, 0, 24, 1)},
                         {"s24le",   PCM(1, 0, 24, 0)}, {"s24be",    PCM(1, 0, 24, 1)},
                         {"u32le",   PCM(0, 0, 32, 0)}, {"u32be",    PCM(0, 0, 32, 1)},
    -- 
    2.9.0

**Comment by wm4** [comment]
Merged.
