### ISSUE TITLE
Add support for cda.pl site ( via youtube-dl )

### ISSUE THREAD

**Issue by xjjx** [mpv-player/mpv#3377]
Seems that youtube-dl supports cda.pl site but for some reason mpv not.

### mpv version and platform
Linux Manjaro, mpv 0.18.1

### Reproduction steps
$ youtube-dl -F http://www.cda.pl/video/568578ea
[CDA] 568578ea: Downloading webpage
[info] Available formats for 568578ea:
format code  extension  resolution note
0            mp4        unknown 

$ mpv http://www.cda.pl/video/568578ea
ffmpeg library versions:
   libavutil       55.28.100 (runtime 55.17.103)
   libavcodec      57.48.101 (runtime 57.24.102)
   libavformat     57.41.100 (runtime 57.25.100)
   libswscale      4.1.100 (runtime 4.0.100)
   libavfilter     6.47.100 (runtime 6.31.100)
   libswresample   2.1.100 (runtime 2.0.101)
ffmpeg version: 3.0.2

mpv was compiled against a different version of FFmpeg/Libav than the shared
library it is linked against. This is most likely a broken build and could
result in misbehavior and crashes.

mpv does not support this configuration and will not run - rebuild mpv instead.

Exiting... (Fatal error)

### Expected behavior
play movie

### Actual behavior
fatal error

### Log files
I feel it's not needed.

**Comment by ChrisK2** [comment]
... read your log, your mpv is broken.
