### ISSUE TITLE
Analysis & Reassembly of SVP 4 Linux Vapoursynth Script

### ISSUE THREAD

**Issue by morphological** [mpv-player/mpv#3379]
In the past, despite my limited knowledge on the matter, I have heavily concerned myself with the addition of GPU acceleration regarding 60 FPS interpolation and vapoursynth.

Now there has been a release by the SVP team specifically targeted at Linux users, that offers full GPU support, while using a "custom" vapoursynth script, that unequivocally shares some similarities with haasn's contributions.

Which can be found here: https://www.svp-team.com/wiki/Download
Additionally required packages and an install guide: https://www.svp-team.com/wiki/SVP:Linux

They do not feature the full script outright, in order for their subpar software layer to remain relevant, however I intend to reassemble the script for exclusive and independent usage, which is going to require as much support from as many knowledgeable people as possible.
Mainly for practical reasons due to the shitty software, but also because of their notorious thievery.

There are two main scripts that are immediately accessible and visible:

[base.py](https://gist.github.com/morphological/ad0ee277441bfff8422da6f93040df25)

[generate.js](https://gist.github.com/morphological/f324debfbca1a72b7f444a7dc1cd89e6)

[override.js](https://gist.github.com/morphological/007bf636b7bcaa899f0a8cf9ec9ad8f2)

There do not seem to be any clear points of separation, whereas the critical portions of the code are missing.
The installation folder does not seem to contain any more scripts or textfiles.

I have managed to tinker around and craft a hybrid with base.py and some other scripts, which does not seem to work reliably, massively drops frames and crashes constantly.

I hope you can shed some light on this.

Regards

**Comment by haasn** [comment]
Most of the work behind SVP is hidden inside the closed-source SVPFlow2.dll (GPU-accelerated version of MVTool's MFlowFps function).

Without access to that function or an equivalent reimplementation you are not going to get very far.

**Comment by morphological** [comment]
Hence, it would be illegal to extract and distribute the code?
I imagine, that the implementation of the extracted code wouldn't just be a matter of copy and paste?

**Comment by Argon-** [comment]
Reassemble...?
When I tried this long ago you could clearly see in the terminal generated script's path they loaded and open/modify it without any problems. I don't get what's your problem here.

**Comment by morphological** [comment]
It's not that easy.
The scripts that are immediately available do not feature any relevant code regarding GPU acceleration.

And the libsvpflow1_vs64.so and libsvpflow2_vs64.so don't, as well.

Since this SVP version is specifically targeted at Linux Users, I imagined it to be easier to just extract and reuse the code/script.
Apparently, it's not just a giant vapoursynth script.

**Comment by Argon-** [comment]
What, no, of course not. 
You can consider it, from a user point of view, the same as using MVTools just that this MVTools has some code running on GPU instead of CPU. What you need/want is the source code of their MVTools modifications which are, obviously, not open. 

I don't see anything you can do other than trying to disassemble/reverse engineer their compiled lib to achieve what you want.

**Comment by morphological** [comment]
What programming language would that be in?

I thought, that instead of using/porting their MVtools implementation on Windows, they exclusively utilized it's successor Vapoursynth on Linux in order to achieve the interpolation.
Hence is why there are Vapoursynth scripts involved, which contain code that clearly has the purpose of interpolation, while the GPU acceleration portion has been intentionally removed.

Even if one were to be able to extract their code regarding GPU acceleration, how could it be used in conjunction with Vapoursynth in order to accomplish GPU accelerated interpolation through one single script?

While I could not find anything in on Linux version with regards to libsvpflow1_vs64.so and libsvpflow2_vs64.so, I have now been able to review the Windows version's SVPFlow2.dll.

Frankly, I have no idea what I am looking at, it seems like C++, which I do not understand.
And even if I did, I would not know how to put the pieces together.

**Comment by haasn** [comment]
VapourSynth is not a successor to MVTools, it's a successor to AviSynth. (I don't know why people keep thinking VapourSynth does motion interpolation, but it doesn't...)

**Comment by Argon-** [comment]
> I thought, that instead of using/porting their MVtools implementation on Windows, they exclusively utilized it's successor Vapoursynth on Linux in order to achieve the interpolation.
Hence is why there are Vapoursynth scripts involved in the Linux Version of SVP, which contain code that clearly has the purpose of interpolating, while the GPU acceleration portion has been intentionally removed.

Well, your whole assumption is totally wrong. SVP does not need Vapoursynth, it also works with avisynth but it's pretty much Windows-only.

> Even if one were to be able to extract their code regarding GPU acceleration, how could it be used in conjunction with Vapoursynth in order to accomplish GPU accelerated interpolation?

Vapoursnyth has nothing to do with it.
You have to find out what modifications they made to MVTools (GPU support) and add them to MVTools...

**Comment by morphological** [comment]
@haasn Yes, but only parts of it, I believe. I disassembled the .dll  with objdump and reinterpreted in C++ with a builder. 

@Argon- Then why is Vapoursynth a prerequisite to use SVP 4 Linux, while the install generates two separate Vapoursynth scripts that are clearly responsible for interpolation ( They even comment that in the script)?

**Comment by Argon-** [comment]
I told you where to find it and this script there IS the full VS script.

**Comment by haasn** [comment]
> Yes, but only parts of it, I believe. I disassembled the .dll with objdump and reinterpreted in C++ with a builder. 

Feeding the disassembly into a decompiler is not the same thing as having the original source, for many reasons.

**Comment by morphological** [comment]
@Argon: You suggested I observe the scripts being loaded in the terminal during operation.

Only base.py and generate.js seem to be used, the rest is accessed by the software layer, which does not appear in the terminal.

The install folder does not contain any VS scripts, apart from the two mentioned in my original post.

**Comment by Argon-** [comment]
Sorry but you are doing something wrong. I want you to look at the mpv messages when the vf vapoursynth filter is loaded, it contains the path to the generated script file. Neither mpv nor VS will at any time load base.py and of course never a JavaScript file.
The "software layer" isn't really accessing anything either. Whenever you change options it will create a new script and then load the vf with the correct path.
