### ISSUE TITLE
[BUG] mpv+vaapi+fullscreen causes screen noise when we disable compositing

### ISSUE THREAD

**Issue by gary816** [mpv-player/mpv#3380]
### mpv version and platform
mpv 0.18.1
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.1

vainfo: VA-API version: 0.39 (libva 1.7.1)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Desktop - 1.7.1

Arch Linux (Antergos Linux)

### Reproduction steps
1. Disable compositing
KDE Plasma:
System Settings -> Hardware -> Display and Monitor -> Compositor
Uncheck "Enable compositor on startup".
-> Logout/Login

2. Get a movie trailer
$ wget http://trailers.apple.com/movies/universal/thegreatwall/the-great-wall-trailer-1_h1080p.mov

3. Play it on fullscreen
$ mpv --hwdec=vaapi -vo=opengl -ao=pulse --fullscreen the-great-wall-trailer-1_h1080p.mov
Play the movie for a minute.
It causes screen noise.

Note:
"-vo=vaapi" also causes the noise.

**Comment by Gusar321** [comment]
Intel driver bug. Switch to UXA acceleration, or drop the intel driver altogether and use the modesetting driver instead. For more info, see this report at the Arch bugtracker: https://bugs.archlinux.org/task/46976

**Comment by gary816** [comment]
Thanks Gusar321,
I wrote /etc/X11/xorg.conf.d/20-intel.conf

> Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   Option      "AccelMethod"  "uxa"
EndSection

and mpv can play the movie properly. :-)
Thank you for the quick reply.
