### ISSUE TITLE
x264-r2479-dd79a61

### ISSUE THREAD

**Issue by Geyup** [mpv-player/mpv#3386]
Handbrake 0.10x uses ```x264-r2479-dd79a61``` and I wanted to know if there's any benefit to sticking to this version for mpv when compiling x264 support in mpv?

thank you

**Comment by kevmitch** [comment]
This is probably a better question to the handbrake devs as to why they use that particular version. If I were to guess though, it was simply the latest working version when they released and or created the binary. Generally I would just go with the current x264 git master. That said, this only matters at all if you are actually using mpv to encode.

**Comment by Geyup** [comment]
The question was to ask about using a version with MPV.

Compiling against x264, or xvid doesn't help for playback support?

thanks

**Comment by haasn** [comment]
Why would a video encoder help for playback?
