### ISSUE TITLE
OSD render on 4K video caused many dropped frames

### ISSUE THREAD

**Issue by duyhotan2000** [mpv-player/mpv#3389]
Hello,

I have built MPV and run successfully on an ARMv8 SoC board.
However, when running 4K videos, there are many dropped frames when the OSD is displaying. I tried to disable OSD drawing by comment the function **osd_conv_ass_to_rgba** in **render_object** in osd.c and the result is no more dropped frames.
This does not happen with FullHD video, just from QHD and above.

Any recommendation for this low performance?

Thank you!

**Comment by wm4** [comment]
Hardware too slow?

>  osd_conv_ass_to_rgba 

This is never used in the normal rendering path (except with some non-preferred VOs), and is especially slow.

**Comment by duyhotan2000** [comment]
I'm using Wayland for video out and this must be used. Anyway to overcome this?

**Comment by wm4** [comment]
If you mean ``--vo=wayland`` - this is also inherently slow (does software scaling) and is not preferred. We might even remove it. Use ``--vo=opengl``, which has a wayland backend.

**Comment by duyhotan2000** [comment]
I forgot to told you that I have ported direct memory access from decoder to Wayland and also use hardware scaling. But the hardest thing is to using the GUI, it is very slow in 4K due to this issue.

**Comment by wm4** [comment]
In that case, you should probably implement support for SUBBITMAP_LIBASS (instead of only SUBBITMAP_RGBA), which might make it faster. At least it will give you the direct output of libass, and skip the slow unoptimized C code for converting to RGBA. Or you could render the OSD at a lower resolution.

**Comment by duyhotan2000** [comment]
OK, thanks for your answer!
Just one more question regarding the `--vo=opengl`. My environment doesn't support libGL.so now, but only libEGL.so. Does MPV work with libEGL.so?

**Comment by wm4** [comment]
Yes.

**Comment by duyhotan2000** [comment]
EGL or EGL-wayland doesn't have fully support on our platform now. Do you have any other way to render OSD into a RGBA bitmap?

**Comment by wm4** [comment]
> Do you have any other way to render OSD into a RGBA bitmap?

You'll have to make one.
