### ISSUE TITLE
framedrop problem

### ISSUE THREAD

**Issue by acroobat** [mpv-player/mpv#3391]
Just switched from vlc to mpv, but unfortunately can't use it.

After some time of watching video drops appear and video starts to freeze.
With an option framedrop=no, Audio/Video desynchronisation detected! With vlc or mplayer there is no such a problem.

Graphics: Intel HD3000
System: Gentoo x64
Version of mpv: 0.18.1
Version of ffmpeg: 2.8.5
.config is empty

I tried to use with different vo=opengl, vo=vaapi, vo=xv. And tried to increase cache. No success.

**Comment by lamarpavel** [comment]
`--hwdec=vaapi` and install the intel-vaapi drivers (eg. libva-intel-driver on Archlinux).

**Comment by wm4** [comment]
Unlikely that hardware decoding is the problem. But I'm not sure what the problem is, maybe the poster should have followed the issue template.

**Comment by acroobat** [comment]
lamarpavel, doesn't help.

**Comment by acroobat** [comment]
wm4, the problem is that i can't watch video because of constant drops, details in my first post. No matter if i use software of hardware decoding.

**Comment by kevinlekiller** [comment]
Try `--vo=opengl:deband=no`

You could also try `--vo=opengl:deband=no:dumb-mode=yes`, although it says the option might be removed in the future.

**Comment by lamarpavel** [comment]
@acroobat what wm4 meant was that you skipped vital information in your report. Outline the reproduction steps to your problem, that includes what type of file you were playing, how you executed mpv and under which OS etc. And most importantly you did not provide a log: start mpv with `--log-file=output.txt, paste it to sprunge.us`.

**Comment by acroobat** [comment]
lamapavel, everything(OS, how i reproduce the problem) in my first post. I think he can not help, if he care about template rather than problem.

**Comment by acroobat** [comment]
kevinlekiller, doesn't work. Ok, problem is solved - just returned to vlc.

**Comment by lamarpavel** [comment]
@acroobat 
>And most importantly you did not provide a log: start mpv with --log-file=output.txt, paste it to sprunge.us

**Comment by acroobat** [comment]
lamarpavel, i am sorry, but i have already removed mpv from system. What i can say is there was nothing essential in the terminal output. With framedrop=vo, there were just constant drops starting from about 30-40 minutes of playing any video. With framedrop=no - Audio/Video desynchronisation detected the same after 30 minutes approximately. For me problem is solved. Thank to all.

**Comment by mpvOWNZ** [comment]
@acroobat 
Sorry to say so, but it seems that You are mentally challenged and therefore wouldn't notice a difference compared to using an inferior video player such as VLC anyway! :-1:
