### ISSUE TITLE
Desyncing when holding player window

### ISSUE THREAD

**Issue by Spode** [mpv-player/mpv#3393]
### mpv version and platform

mpv 0.18.1-git-1e00bcc built on Sun Jul 10 02:35:34 CEST 2016
from https://mpv.srsfckn.biz/

Windows 10 Anniversary Edition. Happened in earlier versions of Win10 also.

### Reproduction steps

Play any media. Click the player window to make it active/focused. Using the mouse click and hold the player window and reposition it.

### Expected behavior

Window repositioned, video and audio still in sync.

### Actual behavior

When holding the player window the video and audio freezes. The output in cmd shows framedrops and desyncing:

![4](https://cloud.githubusercontent.com/assets/595105/17420906/1a5e5896-5aa6-11e6-936a-c9d616f377fd.png)

### Log files

http://sprunge.us/ERjG

**Comment by wm4** [comment]
Must be a regression, even if not recent.

**Comment by dragons4life** [comment]
Does the video actually look like it's de-syncing afterwards? or does it play fine?

Dropped frames are normal happens to me. https://a.uguu.se/LQhwLmMoBsi5_819897577d.webm

See how the video "stops" for like a second whenever I hold down left click to move it around? at least that's my theory as to why the drops happen.

**Comment by wm4** [comment]
Can't reproduce. However, just clicking on the title bar and holding the mouse button down freezes playback for 1 second. This is due to win32 misbehavior.

**Comment by Spode** [comment]
Tried to record an [example](https://a.uguu.se/ntbsKb2L1CqG.webm). I'm clicking and holding down the mousebutton every few seconds.

**Comment by wm4** [comment]
This should help a bit. But not always.

**Comment by Spode** [comment]
Hmm.. so now I'm confused. I could've swore I had problems with desyncing (tried to make mpv my main player a month or so ago). But now I can't reproduce it. The log does give that warning that it's desynchronized but it doesn't seem to be.

**Comment by dragons4life** [comment]
It's normal happens to me on every other player I've used, I suggest you stop holding down left click for such a huge amount, the sooner you left click+move the less you'll even notice the lagg/pause, see my video at 0:17.

**Comment by wm4** [comment]
Well, uh, I consider this solved.

**Comment by Hrxn** [comment]
> [..] see my video at 0:17.

Seems to be gone..
