### ISSUE TITLE
Mpv with rsound => missing audio

### ISSUE THREAD

**Issue by aksr** [mpv-player/mpv#3394]
Version: **0.18.1**, Platform: **Arch Linux**

There is no audio if I use mpv in conjunction with rsound.
Reproduction steps:

    mpv -ao rsound:host=192.168.1.11 file.mp4

Expected behavior: *Sound should be heard.*
Actual behavior: *There is no sound.*
Log: *http://sprunge.us/eiha*

Audio is fine when I use mplayer (with rsound patch)

    mplayer-rsound -ao rsound:host=192.168.1.11 file.mp4
If you need more info, please do tell.
Best regards.

**Comment by ignisf** [comment]
> ```
> [   0.516][e][ao] Audio output rsound not found!
> [   0.516][e][ao] Failed to initialize audio driver 'rsound'
> ```

I suspect the mpv binary packaged in Arch has no rsound support. In fact, seeing how rsound is only available through AUR, I'm sure the mpv package does NOT have rsound support.

You should try to install `mpv-git` from AUR and check if rsound works out for you.

**Comment by wm4** [comment]
Yep, rsound is not compiled in.

**Comment by aksr** [comment]
**ignisf**: I thought the same about binary package, but I wasn't sure 
*especially when rsound support is not explicitly disabled inside mpv's PKGBUILD*.
I have rsound already installed (without it, *example* with mplayer wouldn't work).
Does *rsound* has to be installed before building mpv for it to be supported?
If the answer is yes, then it all makes sense.
I'll try installing mpv-git.

**Comment by wm4** [comment]
Btw. what do you want to use rsound for?

**Comment by aksr** [comment]
My speaker on my laptop is broken, so I want to send the sound of videos etc. on my main computer. :)
Also, sound is better and louder.
