### ISSUE TITLE
Question about Windows build how to keep player open if you want just to close the video

### ISSUE THREAD

**Issue by YukiSakuma** [mpv-player/mpv#3396]
### mpv version and platform

2016-07-10	|	64-bit build

I am using the windows exe file and need  to close the video currently playing while keeping the mpv player open is it possible?

**Comment by dragons4life** [comment]
You can drag and drop it? alternatively you can use https://github.com/rossy/mpv-open-file-dialog

However I do not know how to only close the video on MPV, doubt it has that "feature" as well. https://mpv.io/manual/master/ try looking on the manual if you want.

**Comment by rossy** [comment]
It's possible. You should create an input.conf and add a key binding for the ``stop`` command. Then add the following to your mpv.conf, so mpv stays open after the file is stopped:
```
[pseudo-gui]
idle
```

**Comment by paulguy** [comment]
If you're OK with opening it from a terminal, you can also switch to the 'no' video track with _ (underscore).  If you do this without a terminal, you'll just have a background mpv playing audio which you'll need to kill or wait for it to finish, or push a command to it with its JSON interface.

**Comment by Argon-** [comment]
>  If you do this without a terminal, you'll just have a background mpv playing audio

In my case I'll get a black window. Even when you don't have one, shouldn't you still be able to continue cycling video tracks?

**Comment by paulguy** [comment]
In my experience, the window just disappears and I need to hit _ in the terminal to get it back.  Maybe there's some difference there between the widnows and linux version, which I use.

**Comment by Argon-** [comment]
Yes, when you launch from a terminal. But when launching mpv by double click then the pseudo-gui profile is active.
In pseudo-gui you'll still have a window and when launching from terminal you can still continue cycling "in" the terminal. So there should be no problem.

**Comment by paulguy** [comment]
Oh, OK.  Yeah I never really load mpv using an icon so I didn't know.  Good that the simple solution works, heh.  Not sure if it'll stay with no video on the next playlist entry though.
