### ISSUE TITLE
OpenGL Error when calling mpv_opengl_cb_draw on OSX

### ISSUE THREAD

**Issue by lhc70000** [mpv-player/mpv#3397]
### mpv version and platform

```
[cplayer] mpv 0.18.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sat Jul  2 02:12:40 BST 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.28.100
[cplayer]    libavcodec      57.48.101
[cplayer]    libavformat     57.41.100
[cplayer]    libswscale      4.1.100
[cplayer]    libavfilter     6.47.100
[cplayer]    libswresample   2.1.100
[cplayer] ffmpeg version: 3.1.1
```

OSX 10.11.6, Xcode 8 beta
### Environment

I'm using mpv client API (opengl-cb) on OSX 10.11.6. To avoid blocking main thread, the video is rendered to an offscreen FBO with `mpv_opengl_cb_draw` in another thread, and is copied to view in main thread.

I occasionally added an `glGetError()` after `mpv_opengl_cb_draw`, and found that except the first several calls, **each** `mpv_opengl_cb_draw` call would cause an OpenGL Error `INVALID_OPERATION`. The error seems not to be caught by `mpv`, and there is no mpv logs indicating the error.

(When video config changes, it will catch the error saying "after creating framebuffer texture: OpenGL error INVALID_OPERATION")

( **All works pretty well so far**, the error does not affect any functionalities I used.)
### Possible problem location

After digging for a while in assembly code, I found that the error is very likely caused by

``` cpp
gl->BeginQuery(GL_TIME_ELAPSED, id);
```

in `gl_timer_start` function in [video/out/opengl/utils.c](https://github.com/mpv-player/mpv/blob/master/video/out/opengl/utils.c).

It could be confirmed by running `glGetError()` in lldb. Before executing the instruction, `glGetError()` returns `GL_NO_ERROR`, however it returns `INVALID_OPERATION` right after this instruction. In addition, I checked the `id` variable, it's a different positive integer at each time.

I am not sure whether it's caused by my (possibly) improper usage of the client API. I will continue test if needed.

**Comment by wm4** [comment]
This shouldn't be called if the GL implementation doesn't support it. Though it's also possible that this code is somehow buggy. We'll need a more complete mpv log.

**Comment by lhc70000** [comment]
Here's a complete log: [http://sprunge.us/eDiT](http://sprunge.us/eDiT)

After changing aspect ratio, it outputs "after creating framebuffer texture: OpenGL error INVALID_OPERATION.", however if add a glGetError() after `mpv_opengl_cb_draw`, it seems that the error is generated each time (and since the error is caught, no error message will be printed in log).

**Comment by wm4** [comment]
So the OpenGL version should be good enough to include all of the query/timer extensions. Do you still think `gl->BeginQuery(GL_TIME_ELAPSED, id);` causes this?

**Comment by lhc70000** [comment]
Yes, I still think the error occurs at this line.

Here's the screenshots as proof, also assembly code for `gl_timer_start`: [http://sprunge.us/jBcT](http://sprunge.us/jBcT) if you are goint to take a look:

Before
![99b65e56-d282-4bfa-8a2b-2f450d541503](https://cloud.githubusercontent.com/assets/8478049/17457914/47f84bc6-5c37-11e6-8024-c965550aa55b.png)

After
![fc0e2ed2-d13e-4a7f-93c5-38842318ce2b](https://cloud.githubusercontent.com/assets/8478049/17457920/563b70d2-5c37-11e6-9827-244658f0131c.png)

**Comment by haasn** [comment]
As far as I can tell, mpv isn't doing anything wrong here. Is it a driver bug?

**Comment by wm4** [comment]
Either we overlooked something, or it's a driver bug.

**Comment by Akemi** [comment]
is this still a problem? i believe you don't render anything to an offscreen FBO anymore right? i didn't get any errors with cocoa-cb, though i also don't draw to an offscreen FBO.

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
