### ISSUE TITLE
Fullscreen bug when using --autofit

### ISSUE THREAD

**Issue by pavelxdd** [mpv-player/mpv#3400]
### mpv version and platform

> mpv --version
mpv git-78bcbe2 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Aug  6 21:08:28 MSK 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.1

Windows 8.1 x64
NVIDIA GTX 650 Ti

### Reproduction steps
    mpv "video.mkv" --no-config --load-scripts=no --fullscreen --autofit=50% --log-file=output.txt

### Expected behavior
Videos plays stretched to fullscreen.

### Actual behavior
Video takes only 1/4 of the screen.
http://i.imgur.com/vRJn0jr.png
Without an --autofit option everything works fine.

### Log files
http://sprunge.us/IfLY

**Comment by pavelxdd** [comment]
I've just found out that this commit
https://github.com/mpv-player/mpv/commit/9f70117233c88b6cf4329c93e0d89f56f96acbac
was the last one when everything worked OK

**Comment by wm4** [comment]
Makes sense. I guess the window width/height isn't updated correctly anymore.

**Comment by wm4** [comment]
Branch above should fix it. Didn't test it, thus it's only a branch.

**Comment by pavelxdd** [comment]
I can confirm that this branch has fixed the problem for me.
