### ISSUE TITLE
Hardware encoding support?

### ISSUE THREAD

**Issue by kokowang** [mpv-player/mpv#3401]
Is there any way to enable hardware encoding on OS X for h264/h265 when using mpv to output video files? If not, would this be something that could possibly be implemented into MPV in the future? (I would just use a video encoder that's already available but I can't find any with Vapoursynth support).

**Comment by wiiaboo** [comment]
If FFmpeg was compiled with --enable-nvenc it's just another codec like the others:
```sh
$ mpv --ovc=help | grep nvenc
  --ovc=h264_nvenc   NVIDIA NVENC H.264 encoder
  --ovc=nvenc        NVIDIA NVENC H.264 encoder
  --ovc=nvenc_h264   NVIDIA NVENC H.264 encoder
  --ovc=nvenc_hevc   NVIDIA NVENC hevc encoder
  --ovc=hevc_nvenc   NVIDIA NVENC hevc encoder
```

**Comment by wm4** [comment]
Generally not, except encoders which somehow magically take in normal surfaces.
