### ISSUE TITLE
Unable to set chapter-list from lua plugin

### ISSUE THREAD

**Issue by hahiserw** [mpv-player/mpv#3402]
### mpv version and platform
mpv 0.18.0 x86_64 
GNU/Linux 4.6.4-1-ARCH

### Reproduction steps
- Create a plugin containing:
```lua
function main()
  mp.set_property_native('chapter-list', {{time = 1, title = 'a'}})
end

mp.add_hook('on_preloaded', 1, main) -- or on_load
```
- Launch any video
- Press Page Up / Page Down

### Expected behavior
Adding a chapter.

### Actual behavior
Not adding a chapter.

**Comment by wm4** [comment]
Was fixed by PR above.
