### ISSUE TITLE
title="${filename}" minus the extension

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3404]
For mpv.conf, `title="${filename}"` displays the title of the windows as "filename.extension", but I'd rather have "Locke" as the window title, rather than "Locke.mkv", as I prefer to treat media on a more "pure" level. Generally, I have a disdain for metadata when it's not needed, and personally, I don't care about what container holds my videos. The music player that I use doesn't state "Health and Efficiency.mp3" on its title, so it'd be nice to have that on MPV as well.

I know one can display the "media title", but I've found this is not often the correct title for the video.

**Comment by avih** [comment]
> I know one can display the "media title", but I've found this is not often the correct title for the video.

What do you mean by "not correct"? is it missing? or does it have an actual title which you consider incorrect? FWIW, in my experience it's working very well (doesn't mean you're wrong, just sharing my own experience with it).

Maybe, assuming that's not the case, `media-title` should fall back to the filename sans the extension (and dots replaced with spaces?) in case it's missing?

**Comment by firewater2** [comment]
I don't think I used it too much, but I remember release groups would put their [name] instead of the title of the video, or the title would include the year of the film (which I don't want to see there), or the title would be the localized name (whereas I prefer to use the original alphabet of the country it was originally released in).

Can't believe this was actually fixed though, thanks!
