### ISSUE TITLE
Apply Replaygain from tags of individual tracks in multitrack media files

### ISSUE THREAD

**Issue by WhitePeter** [mpv-player/mpv#3405]
### mpv version and platform
mpv git-367e9fb (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Tue Aug  9 17:53:19 CEST 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.51.100
   libavformat     57.46.100
   libswscale      4.1.100
   libavfilter     6.50.100
   libswresample   2.1.100
ffmpeg version: N-81307-gb3a6911

Platform: Debian GNU/Linux 8 (Jessie)

### Reproduction steps
So far I have only been able to get RG tags for individual tracks into
matroska files, so I first created an opus file, which then was analyzed
by bs1770gain.

Playing that file works:
`% mpv --af=volume=replaygain-preamp=-15:replaygain-track sample.opus`

The volume is noticably lower than the original, even more pronounced
by replaygain-preamp=-15, which is a good test, if RG actually works.

The same opus file was then merged into two .mka files, one having the
RG tags written to the track metadata section and the other to the
global tags.

```
% mediainfo sample.*.mka
General
Unique ID                                : 274713958187036931034496361643256468148 (0xCEABFBDBB7640A66C49A473B599652B4)
Complete name                            : sample.RG_global.mka
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 337 KiB
Duration                                 : 10s 0ms
Overall bit rate                         : 276 Kbps
Encoded date                             : UTC 2016-08-09 14:12:54
Writing application                      : Lavf57.46.100
Writing library                          : Lavf57.46.100
REPLAYGAIN_ALBUM_PEAK                    : 0.795689
REPLAYGAIN_ALGORITHM                     : ITU-R BS.1770
REPLAYGAIN_REFERENCE_LOUDNESS            : -23.00
REPLAYGAIN_TRACK_GAIN                    : -4.53 LU
REPLAYGAIN_TRACK_PEAK                    : 0.795689
REPLAYGAIN_TRACK_RANGE                   : -18.84 LU
REPLAYGAIN_ALBUM_GAIN                    : -4.53 LU
REPLAYGAIN_ALBUM_RANGE                   : -18.84 LU

Audio
ID                                       : 1
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 10s 0ms
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Rear: L R, LFE
Sampling rate                            : 48.0 KHz
Bit depth                                : 32 bits
Compression mode                         : Lossy
Default                                  : Yes
Forced                                   : No
DURATION                                 : 00:00:10.000000000
NUMBER_OF_FRAMES                         : 500
NUMBER_OF_BYTES                          : 340281
_STATISTICS_WRITING_APP                  : mkvmerge v9.3.1 ('Mask Machine') 64bit
_STATISTICS_WRITING_DATE_UTC             : 2016-08-09 16:12:54
_STATISTICS_TAGS                         : BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES

General
Unique ID                                : 286924962251189474636244467374216808764 (0xD7DBBCD73B4D408939F789DDFD0D893C)
Complete name                            : sample.RG_per_track.mka
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 337 KiB
Duration                                 : 10s 1ms
Overall bit rate                         : 276 Kbps
Writing application                      : Lavf57.46.100
Writing library                          : Lavf57.46.100

Audio
ID                                       : 1
Format                                   : Opus
Codec ID                                 : A_OPUS
Duration                                 : 10s 1ms
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Rear: L R, LFE
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Writing library                          : Lavf57.46.100
Default                                  : Yes
Forced                                   : No
REPLAYGAIN_ALGORITHM                     : ITU-R BS.1770
REPLAYGAIN_REFERENCE_LOUDNESS            : -23.00
REPLAYGAIN_TRACK_GAIN                    : -4.53 LU
REPLAYGAIN_TRACK_PEAK                    : 0.795689
REPLAYGAIN_TRACK_RANGE                   : -18.84 LU
REPLAYGAIN_ALBUM_GAIN                    : -4.53 LU
REPLAYGAIN_ALBUM_RANGE                   : -18.84 LU
REPLAYGAIN_ALBUM_PEAK                    : 0.795689
DURATION                                 : 00:00:10.001000000
```

Playing these two files with the above command results in the one
having the global RG tag being played at the same volume as the
original opus file and the other played back without any gain, hence
much louder:

`% mpv --af=volume=replaygain-preamp=-15:replaygain-track sample.opus sample.RG_global.mka sample.RG_per_track.mka`

sample.opus and sample.RG_global.mka play as expected.
sample.RG_per_track.mka is played wihout RG.

### Expected behavior
I think for file formats that do allow more than one audio track, the
RG tags should be read from the track tags first and only if there are
none to be found, then read the RG tags from the global tags.

### Actual behavior
Only the global RG tags are read and acted upon.

### Log files
http://sprunge.us/VfBE

Here is an archive containing above mentioned files:
https://0x0.st/BY6.zip

**Comment by wm4** [comment]
According to your mediainfo output, the gain/peak values are the same for album and track for each of your files.

**Comment by WhitePeter** [comment]
> According to your mediainfo output, the gain/peak values are the same for album and track for each of your files.

That is correct. This is because I only fed a single file to bs1770gain. There need to be at least two files with differing track gains for album gain to really matter. This was only an example. Usually I let it run over a whole album, and then album gain gets actual meaning. :)

**Comment by wm4** [comment]
If the tags are exactly the same for track/album, and the track/album mode will always give the same result. How could it possibly be different?

**Comment by WhitePeter** [comment]
> If the tags are exactly the same for track/album, and the track/album mode will always give the same result. How could it possibly be different?

I didn't say it would be different. I think there is a misunderstanding here. I explicitly instruct mpv to use the track gain, so album gain should not matter at all. It shouldn't do any harm, either. I just haven't found out yet, how to disable album gain calculation in bs1770gain.

The problem is that only RG tags that are in the global tags section actually work in mpv. The file which has the tags in the track tag section behaves as if there weren't any RG tags at all. mpv seem to ignore them.

**Comment by wm4** [comment]
So you mean the case where a single file has multiple audio tracks? But none of your sample files contain more than 1 track. I suppose you could also mean the case of file formats which distinguish per-track tags and global tags, which I could see being a problem. Needs sample files.

**Comment by WhitePeter** [comment]
> So you mean the case where a single file has multiple audio tracks?

Yes, only then it really makes a difference.

> But none of your sample files contain more than 1 track.

As I said, my example is only to demonstrate the minimum. See above, sample.RG_global.mka has the RG tags listed under "General", which I would call global, and sample.RG_per_track.mka has them under "Audio" which is a track specific section.

> I suppose you could also mean the case of file formats which distinguish per-track tags and global tags, which I could see being a problem.

Well, I think I mean both. :) Say, a film that has two audio tracks. Both will most likely have different RG values, so I want that to be reflected by the track specific RG tags. That is certainly possible with matroska. I haven't really tested with other formats as mkv is my goto format for videos.

> Needs sample files.

I tried uploading the samples for my initial report. But even though the error message suggested that zip file are among the accepted formats, my file got rejected anyway. And it was only about 1 MB in size. Can you suggest another way of sending samples. I can also make one that has two audio tracks with individual RG tags for each. 5 seconds should be enough? Then the file size should stay reasonably small

**Comment by wm4** [comment]
Just use https://0x0.st/ or something similar to upload files.

**Comment by WhitePeter** [comment]
Thank you very much. I was looking for something like that, but all I could find were those scammy looking file hosters.

Anyway, I have updated my initial post, so it now contains the files I am writing about. I am working on creating a sample, which has two audio tracks...

**Comment by wm4** [comment]
So, just sample.RG_per_track.mka doesn't work as expected, correct? I'll try to fix it tomorrow.

**Comment by WhitePeter** [comment]
Yes, that is correct. I have also created a two-track sample now:
https://0x0.st/BYD.zip

**Comment by kevinlekiller** [comment]
On a side note, the currently bs1770gain does not handle files with multiple tracks in them well, I'm working on some of those issues and fixed a couple other issues (also sent a email to the maintainer so he's aware) https://github.com/kevinlekiller/bs1770gain_fixes

**Comment by WhitePeter** [comment]
Ooops, just noticed my mistake. I accidentally transcoded the opus files to vorbis stream. This is what I actually wanted to send:
https://0x0.st/BYk.zip

I don't think it really matters, though. But, I don't want any misunderstandings. :)

**Comment by WhitePeter** [comment]
@kevinlekiller, thank you very much for that. I also noticed that bs1770gain is kind of clumsy in certain situations. What I really don't like is that it writes a whole new file to get the tags in, but I guess it is the easier way to just let ffmpeg do the heavy lifting there and not worry about different tagging formats.

I'll take it anyway, had been searching very long for a tool that can handle almost anything one throws at it and not a basket full of mp3gain, aacgain, flac/metaflac, vorbisgain and whatnot. ;)

**Comment by kevinlekiller** [comment]
@WhitePeter yeah, I wrote a script to not have bs1770gain write a new file, although I'll have to rewrite it for proper multiple track support (which is now possible with the fixes I put in), I'll keep you posted.

**Comment by WhitePeter** [comment]
@kevinlekiller, wow, that is great to hear. Looking forward to it. This is like Easter and Christmas on one day. YAY!

**Comment by kevinlekiller** [comment]
@WhitePeter Posted the script here: https://github.com/kevinlekiller/mkvrg

**Comment by WhitePeter** [comment]
@kevinlekiller, thank you very much. That was rather quick. :) I will definitely have a look.

**Comment by wm4** [comment]
So, does it work? I only tested to the extent that the replaygain tags were interpreted per-track.

**Comment by WhitePeter** [comment]
So far I have tested the last sample I provided, the one with different loudness levels for the same content. It seems to work nicely. There is a noticeable difference in volume, sounds about right for the 6 dB difference, not that I have a loudness meter in my ears, though. ;)

Also, both RG tags have an effect, since RG-preamp -15 effects both tracks, and the difference is still there, as one would expect.

I am currently evaluating @kevinlekiller's script, so I can use it on my real content. I'll keep you posted, if I find anything amiss.
But so far, I am a happy camper. Thank you very much for this. You even did it on time! I am very grateful.

**Comment by kevinlekiller** [comment]
Not working for me (per track).

With the replaygain tags in the "global" section it works:

Example file: https://0x0.st/B0F.mkv
Log of `mpv --af=volume:replaygain-track:detach --msg-level=af=debug,ao=debug,volume=debug`:  http://sprunge.us/aEMC
ffprobe of file: http://sprunge.us/aSVb

With replaygain tags in the "track" section, it does not work:

Example file: https://0x0.st/B0C.mkv
Log of `mpv --af=volume:replaygain-track:detach --msg-level=af=debug,ao=debug,volume=debug`: http://sprunge.us/LXBW
ffprobe of file: http://sprunge.us/AUIh

**Comment by wm4** [comment]
Your logs cut out the interesting parts.

**Comment by kevinlekiller** [comment]
I'll rerun with -v

**Comment by kevinlekiller** [comment]
Tags in global (works): http://sprunge.us/XRKU

Tags in tracks (does not work): http://sprunge.us/BfiS

**Comment by kevinlekiller** [comment]
With --msg-level=all=debug:

Global: http://sprunge.us/HZMW

Tracks: http://sprunge.us/CVjR

**Comment by WhitePeter** [comment]
Maybe it is the order of REPLAYGAIN_REFERENCE_LOUDNESS and REPLAYGAIN_TRACK_[GAIN|PEAK]? That is one thing that is different. In my original sample the REPLAYGAIN_REFERENCE_LOUDNESS comes first. Also, there are no *ALBUM* tags now, just FYI.

**Comment by kevinlekiller** [comment]
I'll try reordering it, I think the album gain is only useful if you have multiple songs which belong to an album and pass "--af=volume:replaygain-album", for TV/movies I think it's not important.

**Comment by WhitePeter** [comment]
I just reorderd them, seems to make no differnence.
Some more differences I noticed:
There is no ENCODER tag per track and the DURATION is also missing.

**Comment by kevinlekiller** [comment]
Here I've reordered the tags, and added the album information:

It seems @WhitePeter , the order of the tag makes a difference?

Example file: https://0x0.st/BGi.mkv
mpv log: http://sprunge.us/NPET
ffprobe: http://sprunge.us/TXHF

**Comment by wm4** [comment]
OK, it's because it has TRACK tags, but no ALBUM tags. We expect either both, or tags with neither in the name.

**Comment by kevinlekiller** [comment]
@WhitePeter I'll edit the script to add the Album tags, will mention you so you get a notification.

**Comment by WhitePeter** [comment]
@wm4, thanks for the info. Could you change that? As far as I am aware, ALBUM tags are optional and as you already pointed out, don't always make sense.

**Comment by WhitePeter** [comment]
@kevinlekiller, thanks. And also thanks for showing me, which option was hiding in plain site. :) No I know how not to calculate ALBUM tags, when they are useless. But that is only semi-related.

**Comment by WhitePeter** [comment]
@kevinlekiller, I think you should hold off on that ALBUM gain thing. Or your script needs a major rewrite. Since it operates on individual files, there is no way bs1770gain can calculate a meaningful album gain, it ould always be just a copy of \*TRACK\*.

**Comment by kevinlekiller** [comment]
For now I'm just going to copy the track info to album, so it can work with mpv.

**Comment by wm4** [comment]
Are missing album tags allowed or not? Decide.

**Comment by WhitePeter** [comment]
Definitely allowed. :)

**Comment by WhitePeter** [comment]
The default mode of bs1770gain does calculate album gain, but one can disable that by supplying the --track-gain option. I can see people going for that option, because for single files or files that are not related in an album context, it is the right thing to _not_ have ALBUM tags.

**Comment by kevinlekiller** [comment]
Thanks @wm4, your work is appreciated.

**Comment by WhitePeter** [comment]
Thank you @wm4. What @kevinlekiller said. ;)

But does this in any way interfere with users' settings? I can see a theoretical element of surprise there, when one asks for `mpv --af=volume=replaygain-album` for tracks that don't have REPLAYGAIN_ALBUM* tags, for whatever reason. In my thinking there should be a warning, so the user knows what is happening.

Say:
"No Album Replaygain tags found, using the Track tags instead."

**Comment by kevinlekiller** [comment]
Maybe you could do mpv `--af=volume=replaygain-album:replaygain-track`, which prefers album but falls back to track (not sure if this is how it works).

Some music players will use album if you're playing an album in order, and switch to track if you are playing in a random order, but I think this kind of logic is complex and not worth implementing in mpv.

**Comment by WhitePeter** [comment]
@kevinlekiller, I was just trying to anticipate future complaints/issues. Your proposal requires the user to actually set this.
I mean, on principle, the user should get what they ask for, so if there are no album RG tags, no RG should be applied, if `--af=volume=replaygain-album` was set. But in this case I think it is the more sensible thing to issue a warning and use the track RG tags, because in the majority of cases the RG tags have a negative value meaning in a playlist, there would be tracks that were too loud, if mpv did *exactly* as the user asked.
I think other players do that fallback thing, too, if there are no album RG tags. Maybe just make a note in the documentation?

**Comment by sergeevabc** [comment]
@WhitePeter, ```replaygain=album``` in mpv.conf works as intended (Album RG tag is applied with fall-back to Track RG tag if the former is not present), but some indication of volume being boosted would be appreciated (when user presses “i” to invoke on-screen stats about playback).
