### ISSUE TITLE
HTTP: IDN doesn't work

### ISSUE THREAD

**Issue by l29ah** [mpv-player/mpv#3406]
mpv git-0b144ea (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Aug  4 21:50:29 MSK 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.1

amd64 linux

‰ mpv http://буранчик.рф/juick/vn.ogg
Playing: http://буранчик.рф/juick/vn.ogg
[ffmpeg] tcp: Failed to resolve hostname %D0%B1%D1%83%D1%80%D0%B0%D0%BD%D1%87%D0%B8%D0%BA.%D1%80%D1%84: Name or service not known
Failed to open http://буранчик.рф/juick/vn.ogg.

Expected: http://буранчик.рф/juick/vn.ogg → http://xn--80abwinqu9a.xn--p1ai/juick/vn.ogg

**Comment by wm4** [comment]
FFmpeg's problem, not ours.
