### ISSUE TITLE
How can I pass an extra include (header) directory to waf when building mpv?

### ISSUE THREAD

**Issue by sofakng** [mpv-player/mpv#3407]
Is it possible to pass extra flags to GCC (-I to add another include directory for headers) when configuring MPV with WAF?

I'm pretty sure I can use environment variables but I'd rather not use that approach.

**Comment by wiiaboo** [comment]
> I'm pretty sure I can use environment variables 

Just pass them in the same command as when you run waf configure and they won't ruin the environment. That's the only way, afaict.

**Comment by sofakng** [comment]
Thanks!
