### ISSUE TITLE
Remember volume of the last played file/opened video

### ISSUE THREAD

**Issue by dragons4life** [mpv-player/mpv#3408]
It used to behave like this before volume-max was added, if you disabled soft-vol.
(you also had to have save-position-on-quit enabled)

Ever since than the feature has been "remove", however I would like to request the ability for the volume to be remember even if you have volume-max enable, if possible.

Basically, 
_Open the video > Set Volume > Open New Video2 > Volume is the same > change volume a bit > Open new video3 > Changed volume from last video remains (new video 2)_
and so on..

**Comment by haasn** [comment]
The volume still gets remembered when using `save-position-on-quit` for me.

**Comment by dragons4life** [comment]
The first one you cannot see very well, my bad.
https://a.pomf.cat/uyvfwj.webm (loud audio)

**Comment by haasn** [comment]
In your video you are only playing different videos. `save-position-on-quiet` only applies if you play the same video file again. (Try it, it should work)

**Comment by dragons4life** [comment]
I am sorry but,
<img src='http://i.imgur.com/xAaUnJf.png'/>
<img src='http://i.imgur.com/zhwCOh4.png'/>

As in, opening a new file
As in, opening a new instance of MPV

**Comment by Argon-** [comment]
So you basically want mpv to write back changes you made to your config while playing a video?

**Comment by wm4** [comment]
Fairly sure he just wants the old pulse behavior.

**Comment by dragons4life** [comment]
No, I am asking if you could implemented with the new pulse behavior (volume-max), I don't care if you add the old behavior or do it with the new one, preferably why not use the new one.

This is how it used to work, an old build from Sourceforge 2 months ago.
https://a.pomf.cat/isguaw.webm

(https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20160701-git-c57304a.7z/download)


**------------------------------------------------------------------------------------------------------**
Also, I believe this is a "bug" with audio not really significant, but would like to know if this is normal.
Playing short files like game hitsounds, don't play correctly. 

https://a.pomf.cat/yldqaf.webm
https://a.pomf.cat/qgkcln.webm

I don't really care about this, but it seems like a bug.

I am using the default audio settings.

1. https://upload.teknik.io/XCAq6.txt
2. https://upload.teknik.io/TyuBO.txt

**Comment by wm4** [comment]
I guess it will stay this way.

I've made a FAQ entry for this: https://github.com/mpv-player/mpv/wiki/FAQ#i-want-the-old-pulseaudio-volume-control-back-on-linux

**Comment by haasn** [comment]
FWIW, mpv intentionally does not have a “remember the last value of this setting across program starts” functionality, with the sole exception of `watch_later` which applies only to specific videos.

There are decent reasons for this, but no matter how decent a reason is, some people will expect things to work weirdly. To those people, I suggest writing a user script that will serve as some form of general-purpose “state persistence” framework to which you can add options like volume but also others, to persist those options across player instances.
