### ISSUE TITLE
mpv hangs while playing full screen video with H/W acceleration 

### ISSUE THREAD

**Issue by FalconBsp** [mpv-player/mpv#3409]
### mpv version and platform

Issue observed with - mpv 0.18  and master also  ( which comes default with Ubuntu 16.04)
Ni issue with - mpv 0.4.2 ( which comes default with Ubuntu 14.04.2)

If you're not using git master or the latest release, update.
### Reproduction steps

mpv --hwdec=vdpau -vo vdpau  "Vidoe filename"
### Expected behavior

Video should play without any hang.
### Actual behavior

Some times when we start mpv .. few frames displayed and later mpv hangs. No Vidoe playes. We have to kill mpv.
### Log files

[Blank_screen_Issue.zip](https://github.com/mpv-player/mpv/files/410428/Blank_screen_Issue.zip)

Make a log file made with -v or --log-file=output.txt, paste it to sprunge.us,
and replace this text with a link to it.

Do not bother reporting a bug if you do not provide the required information.

**Comment by haasn** [comment]
Does it happen with `--hwdec=vdpau --vo=opengl`?

**Comment by FalconBsp** [comment]
Yes.

Mpv –hwdec=vdpau –vo=opengl –fullscreen  “Any Video file”

Thanks,

**Comment by marukuru** [comment]
No hanging, but stuttering playback here with `--hwdec=vaapi --vo=opengl --fulscreen` and `--hwdec=vaapi --fulscreen` since 1.8.0/1.8.1 (can't tell, because I jumped to 1.8.1 from 1.7.*)

> mpv 0.18.1-git-1e00bcc (C) 2000-2016 mpv/MPlayer/mplayer2 projects
> built on Fri Aug  5 23:53:46 CEST 2016
>ffmpeg library versions:
>   libavutil       55.28.100
>   libavcodec      57.51.100
>   libavformat     57.46.100
>   libswscale      4.1.100
>   libavfilter     6.49.100
>   libswresample   2.1.100
>ffmpeg version: N-81284-g82e53b3

**Comment by wm4** [comment]
When it hangs, attach gdb (run `pidof mpv` to get mpv's pid, then `attach 123` with 123 replaced by your pid), run the gdb command `thread apply all backtrace`, and post the output.

**Comment by FalconBsp** [comment]
Already attached trace log while raising the issue.

Attaching same again.

**Comment by wm4** [comment]
```Thread 5 (Thread 0x7fe433fff700 (LWP 22733)):
#0  0x00007fe457c84e8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fe44df0bc62 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fe44df0d617 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fe44df0d721 in xcb_wait_for_reply () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#4  0x00007fe43291e0f2 in vl_dri2_get_flush_reply (scrn=0x7fe4382a7c70) at ../../../../../SOURCES/mesa/src/gallium/auxiliary/vl/vl_winsys_dri.c:110
#5  0x00007fe43291e45b in vl_dri2_screen_texture_from_drawable (vscreen=0x7fe4382a7c70, drawable=0x1400002) at ../../../../../SOURCES/mesa/src/gallium/auxiliary/vl/vl_winsys_dri.c:194
#6  0x00007fe43291c4e1 in vlVdpPresentationQueueDisplay (presentation_queue=<optimized out>, surface=10, clip_width=1920, clip_height=1080, earliest_presentation_time=8082972685000)
    at ../../../../../../SOURCES/mesa/src/gallium/state_trackers/vdpau/presentation.c:234
```

```
Thread 1 (Thread 0x7fe45fed9980 (LWP 22717)):
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007fe45c8e3dfd in __GI___pthread_mutex_lock (mutex=mutex@entry=0x7fe4382a7858) at ../nptl/pthread_mutex_lock.c:80
#2  0x00007fe43291dc78 in mtx_lock (mtx=0x7fe4382a7858) at ../../../../../../SOURCES/mesa/include/c11/threads_posix.h:196
#3  vlVdpVideoSurfaceCreate (device=<optimized out>, chroma_type=0, width=3840, height=2160, surface=0x7fe438287f30) at ../../../../../../SOURCES/mesa/src/gallium/state_trackers/vdpau/surface.c:81
#4  0x000056440d77fa61 in ?? ()
#5  0x000056440d783a9f in ?? ()
#6  0x000056440d7827f7 in ?? ()
#7  0x00007fe45e874a9f in ?? () from /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
#8  0x00007fe45e79e60e in ?? () from /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
#9  0x00007fe45e53e72c in ?? () from /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
#10 0x00007fe45e542f79 in ?? () from /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
#11 0x00007fe45e4f0491 in ?? () from /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
#12 0x00007fe45e876686 in avcodec_decode_video2 () from /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56
```

Looks like some sort of deadlock in the driver.

**Comment by FalconBsp** [comment]
If we use older MPV version (0.4 ) , this issue is not reproducible.

**Comment by wm4** [comment]
Then please use git bisect to find what causes this issue by bisecting between mpv 0.4 and git master.
