### ISSUE TITLE
Is it possible to set the A-B loop points according to the lyric files automatically?

### ISSUE THREAD

**Issue by Edenharder** [mpv-player/mpv#3410]
### mpv version and platform

mpv 0.17.0
### Expected behavior

Set the A-B loop points according to the lyric files automatically
### Actual behavior

even cannot set multiple a,b points.

**Comment by wm4** [comment]
No, that would have to be added as a feature.

**Comment by wm4** [comment]
>even cannot set multiple a,b points.

Also what would be the point of that? Obviously playback would get "stuck" at the first loop point.

**Comment by Edenharder** [comment]
Multiple a,b points means
```
a1,b1,a2,b2...
```
where `a1,b1` is a loop while `a2,b2` is another loop. And we should have three shortcuts, one for playing in one loop only, one for switching to next loop and the other one for switch to previous loop.

**Comment by shmerl** [comment]
You can probably use [EDL](https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst) files for that.

**Comment by shmerl** [comment]
Was there some new option added for that?

**Comment by Dudemanguy** [comment]
Woops, didn't comment, but yeah EDL seems to cover this. Alternatively one could possibly use a script.

**Comment by shmerl** [comment]
It's such an obscure way to do it though, that it's almost impossible to discover unless you already know about it.

May be it's worth adding an example on using some kind of `mpv --loop "edl://audio.opus,15,10;audio.opus,30,25"` trick to the man page?

**Comment by Dudemanguy** [comment]
Sure, feel free to open a PR for it.
