### ISSUE TITLE
mpv doesn't detect desktop standard opengl support under mingw-w64 (wrong header?)

### ISSUE THREAD

**Issue by sofakng** [mpv-player/mpv#3411]
It looks like the configure script checks for the GL_RGB32F symbol inside gl.h to determine if 'Desktop Standard OpenGL' is supported, but this symbol exists in glext.h and not gl.h under mingw-w64.

Should this be changed to check for another symbol (ie. GL_RGB) instead?  I've modified this and everything compiles correctly.

If this sounds good I can create a pull request but I'm not sure if I am correct.

Thanks!

**Comment by wm4** [comment]
I think the error is in the mingw header files, or maybe your header files are just too old. GL_RGB32F is a core symbol in later OpenGL versions. In Mesa, gl.h actually simply includes glext.h.

**Comment by wiiaboo** [comment]
Apparently [they're still not in GL/gl.h](https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/5fd86940-28d6-9c85-2449-ec059a23c857%40gmail.com/#msg35272676) on Windows.

**Comment by wm4** [comment]
That doesn't matter, because

>In Mesa, gl.h actually simply includes glext.h.

All what matters is whether the symbol is available. While I'm not totally sure, it seems strange that you have to include glext.h just to get a builtin core symbol.

**Comment by wm4** [comment]
PS

> If this sounds good I can create a pull request but I'm not sure if I am correct.

If it can be done in a non-offensive way, that would probably be fine, since we include glext.h in our actual code anyway.

**Comment by sofakng** [comment]
How about my original suggestion of checking for GL_RGB instead of GL_RGB32F in the autoconf?  I think that would fix the issue on all platforms?

**Comment by wm4** [comment]
No, that would be wrong. Then we would accept old opengl headers, and fail during actual compilation.
