### ISSUE TITLE
Embedded Closed Captions (EIA-608) do not Display for Appropriate Duration

### ISSUE THREAD

**Issue by optimiz** [mpv-player/mpv#3413]
Hello, thank you for mpv, it's very useful and I appreciate all the hard work put into it.  Under mpv v.16, v.17, and v.18, "pop-on" type embedded closed captions (EIA-608) in mpeg streams display too quickly -- when stepping frame-by-frame, closed captions display for as little as a single frame, which is unreadable at 24fps.  I tested numerous mpeg streams from different publishers across roughly two decades of production with similar result.

A "single frame" closed captioned example (displays for ~33ms) from a 24fps video...

`$ ls *00h00m45.7*.png`
>2016-08-11-00h00m45.712-sample.png
2016-08-11-00h00m45.762-sample.png
2016-08-11-00h00m45.795-sample.png

`$ gm montage -geometry +0+0 -tile 3x1 *00h00m45.7*.png -resize 1024x single_frame_example.jpg`
![single_frame_example](https://cloud.githubusercontent.com/assets/8029862/17613094/71ad5788-600e-11e6-9070-66221736fe08.jpg)

A "six frame" closed-captioned example (displays for ~233ms) from the same 24fps video...

`$ ls *00h02m0*png`
>2016-08-11-00h02m04.757-sample.png
2016-08-11-00h02m04.808-sample.png
2016-08-11-00h02m04.841-sample.png
2016-08-11-00h02m04.891-sample.png
2016-08-11-00h02m04.924-sample.png
2016-08-11-00h02m04.974-sample.png
2016-08-11-00h02m05.008-sample.png
2016-08-11-00h02m05.041-sample.png

`$ gm montage -geometry +0+0 -tile 4x2 *00h02m0*.png -resize 1024x six_frame_example.jpg`
![six_frame_example](https://cloud.githubusercontent.com/assets/8029862/17613145/e3a381f0-600e-11e6-8c7d-a24873a2b9d2.jpg)

The expected behavior is for "pop-on" closed captions to display long enough to be read, or, worst-case, until the next caption is displayed.  Alternatively, a display duration within an established presentation rate (145 wpm) recommended for the deaf and hard of hearing, as presented in the [Caption Speed and Viewer Comprehension of Television Programs](http://eric.ed.gov/?id=ED434446) study would be wonderful.

Please advise, thank you.

`$ mediainfo sample.m2v`
>General
Complete name                            : sample.m2v
Format                                   : MPEG Video
Format version                           : Version 2
File size                                : 305 MiB
Overall bit rate mode                    : Variable

>Video
Format                                   : MPEG Video
Format version                           : Version 2
Format profile                           : Main@Main
Format settings, BVOP                    : Yes
Format settings, Matrix                  : Custom
Format settings, GOP                     : Variable
Bit rate mode                            : Variable
Maximum bit rate                         : 9 800 kb/s
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 23.976 (24000/1001) FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Scan order                               : 2:3 Pulldown
Compression mode                         : Lossy
Time code of first frame                 : 00:59:59:00
Color primaries                          : BT.601 NTSC
Transfer characteristics                 : BT.601
Matrix coefficients                      : BT.601

>Text
ID                                       : CC3
Format                                   : EIA-608
Bit rate mode                            : Constant
Stream size                              : 0.00 Byte (0%)

`$ mpv -v sample.m2v`
[output.txt](https://github.com/mpv-player/mpv/files/414692/output.txt)

P.S. - If it's helpful, [U.S. Title 47 Code of Federal Regulations 15.119](https://www.gpo.gov/fdsys/pkg/CFR-2010-title47-vol1/pdf/CFR-2010-title47-vol1-sec15-119.pdf
) covers the different CC display types and expected display duration for United States broadcasters.

**Comment by wm4** [comment]
It's a ffmpeg API issue. You need to use the latest ffmpeg release (or even git), or it won't work.

**Comment by optimiz** [comment]
Understood.  Thanks for the quick response.  As a alternative, is there currently a way to configure mpv to output the embedded CC (line-21) signal so a CC-capable TV can decode and display the captions directly? Basically similar to the way PCM/AC3/DTS direct-audio output/bypass via HDMI currently works?

**Comment by wm4** [comment]
No, that is not possible, and would require major effort. It's not comparable to AC3 passthrough.

**Comment by optimiz** [comment]
Understood.  I had to ask in case I had overlooked something simple.  Thank you for your time and guidance, it's much appreciated.
