### ISSUE TITLE
When using the --speed option, the elapsed and remaining time don't correspond

### ISSUE THREAD

**Issue by Lurchwart** [mpv-player/mpv#3415]
### mpv version and platform
mpv version 0.18.1
Arch Linux with Kernel Linux 4.7.0-1-ck SMP PREEMPT x86_64 GNU/Linux
### Reproduction steps
mpv --speed 2 "example video file"
### Expected behavior
Video plays with 2x speed.
Expected behavior 1: Remaining time is half the runtime of the original video, elapsed time and remaining time both run in real time.
Expected behavior 2: Remaining time is the runtime of the original video, elapsed time and remaining time both run in double real time.
### Actual behavior
Video plays with 2x speed.
Remaining time is half the runtime of the original video.
Remaining time runs in realtime, elapsed time runs in 2x realtime.
### Log files
http://sprunge.us/gYRJ

**Comment by Lurchwart** [comment]
Just thought about it and it's actually quite helpful to have the two different times.
I will leave this open though and let the devs decide.

**Comment by wm4** [comment]
The ``playtime-remaining`` property explicitly scales the remaining file time by playback speed, which seems to be what you want.

Regarding elapsed time, "no". You could write a Lua script that starts a timer during playback or so that measures the time wasted watching.
