### ISSUE TITLE
MPV 0.18.1 crashes sometimes when sending a "loadfile" command through a unix socket

### ISSUE THREAD

**Issue by 00SteinsGate00** [mpv-player/mpv#3416]
### mpv version and platform

MPV-Version: 0.18.1

Platform: OS X 10.11.5
### Reproduction steps

I am writing a program that communicates with mpv over a unix socket. My program manages its own playlist and whenever it gets the "idle" event, it loads the next file, using the "loadfile" command. Obviously this happens rather fast and I was not able to reproduce it by hand using for example the `socat` command.

I'm sorry I can't give a precise description how to reproduce this problem.
### Expected behavior

Mpv player is loading the new file
### Actual behavior

MPV crashes, my program tries to restart it. Works some times, some times it does not. Thus the unix socket refuses the connection. Often it takes like 5 seconds until my program could restart a new mpv instance.

This only happens some times. Sometimes every 3rd time, sometimes every 2nd and sometimes overtime. When I change back to mpv version 0.17.0 it works perfectly, no issue there. As soon as I go to 0.18.1 the problem comes back.
### Log files

http://sprunge.us/Vegb

**Comment by wm4** [comment]
Does it happen on CLI too? Needs a backtrace of some sort.

**Comment by 00SteinsGate00** [comment]
Well changing my program from IPC to command line input would be a huge amount of work.
I have made a small input.conf and tested stopping and immediately playing a file several times, it nothing unexpected happened. I'm aware that my fingers are a lot slower then the computer.

I could try to write some sort of script, but that requires to learn the IPC protocol first. If it helps I could try to take the time to write some sort of script.

**Comment by paulguy** [comment]
I've actually started writing a similar program yesterday, and haven't run in to this problem.  Kind of an odd coincidence...

I've only been testing with 1 video though, so maybe it depends on what video.
```
$ mpv --version
mpv git-2b1656b (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Fri Jun 10 14:07:45 EDT 2016
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.7
```

I'm using python's json.dumps() to convert this object `{"command": ["loadfile", "/home/paul/Greta - Fathom-Yrt4-cHdOLU.mkv"]}` to a string and send it to mpv using this line `s.send((json.dumps(obj) + "\n").encode('utf-8'))` where s is the socket.

This is on Linux, by the way.

**Comment by 00SteinsGate00** [comment]
It only ever occurred with the combination of the "idle" event and the "loadfile". When a file is loaded for the first time it always works.

My program consists of a Meteor project and it uses a nodeJS package to control mpv, which was written by me, too. I was looking for the error in my two programs for hours and then I remembered, that it worked in the beginning, so why not try version 0.17.0 again. And then it all worked again. Of course I could only test it empirically.

**Comment by wm4** [comment]
Also try with git master.

**Comment by wm4** [comment]
And also, if you have the capacity, testing with git bisect since 0.17.0 to find the bug would help.

**Comment by 00SteinsGate00** [comment]
I tried it with the latest master branch and was not able to reproduce the error. So it seems to be fixed again.

Thank you for taking the time.
