### ISSUE TITLE
You manually enabled the feature 'sndio', but the autodetection check faile

### ISSUE THREAD

**Issue by ProfessorKaos64** [mpv-player/mpv#3419]
### mpv version and platform

Building 0.18.1 on Debian Jessie.

### Reproduction steps

Building with the steps defined here: https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/mpv/debian/rules. I have [libroar-dev](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=contents&keywords=sndio.h) installed, which provides sndio.h, but it is not found. The lib ends up here, is the path being searched? Can I manually include it somehow?

```
find / -name "sndio.h"
/usr/include/sndio.h
```

### Expected behavior

waf detects sndio.

### Actual behavior

This error is thrown

```
/tmp/buildd/mpv-0.18.1+git+bsos1/build/.conf_check_037cc2ae18422de0bc3c7645cce8ffcd/testbuild/test.c.1.o']
no 
You manually enabled the feature 'sndio', but the autodetection check failed.
debian/rules:7: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 1
make[1]: Leaving directory '/tmp/buildd/mpv-0.18.1+git+bsos1'
debian/rules:4: recipe for target 'binary' failed
make: *** [binary] Error 2
```

### Log files

Full build log: http://sprunge.us/TXgL

### Sample files

Full build files and build script:

https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/mpv

**Comment by wm4** [comment]
libroar is probably different from the real stdio. Your log is useless and doesn't indicate why the mpv waf check fails. I recommend disabling sndio on Linux as it has absolutely no purpose even in theory.
