### ISSUE TITLE
[Feature request] video-unscaled... with downscaling?

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#3423]
### mpv version and platform

    mpv git-814dacd (C) 2000-2016 mpv/MPlayer/mplayer2 projects built on Tue Aug 16 10:00:45 CEST 2016
    Linux tornado 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux

### Description

I'm using mpv as image viewer for quite some time and have always wanted to see images the way `video-unscaled` shows them, with one caveat: if the image is too big, fit it in the window.

I've tried to emulate it with [LUA](https://github.com/rr-/dotfiles/blob/b8ef36445fb4ab2598c1159906990fbf516e2dfc/mod-mpv/config/images/fancy_zoom.lua) but it sucked - I could see the images flicker zoom during navigation, and have continued to use [my rejected hack](https://github.com/mpv-player/mpv/pull/2936) to work around it. Turns out my patch caused flickering of its own, just another kind, which only became apparent on a slower machine. I decided to drop this idea altogether, and settled for images being upscaled to the window size.

It wasn't until recently till I learned about `video-unscaled`, which looks like almost a perfect fit for what I want to achieve. I wonder if it would be possible for mpv to include similar option that downscales too big videos?

Thanks.

**Comment by soredake** [comment]
Thanks, that's exactly what I wanted https://github.com/haasn/gentoo-conf/issues/3

**Comment by rr-** [comment]
Implemented in ed644b0d3373f8ac1b3bf2ef8f797e1d1d8a775d
