### ISSUE TITLE
Man page info about video-unscaled side effects seem to be false

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#3424]
### mpv version and platform

    mpv git-814dacd (C) 2000-2016 mpv/MPlayer/mplayer2 projects built on Tue Aug 16 10:00:45 CEST 2016
    Linux tornado 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux

### Reproduction steps

The man pages contain information about `video-zoom` not working while `video-unscaled` is active:

>`--video-unscaled`
>
>Disable  scaling  of  the video. If the window is larger than the video, black bars are added. Other‐
>wise, the video is cropped. The video still can be influenced by the other `--video-`... options.  (But
>not all; for example `--video-zoom` does nothing if this option is enabled.)
>
>The  video  and  monitor  aspects aspect will be ignored. Aspect correction would require scaling the
>video in the X or Y direction, but this option disables scaling, disabling all aspect correction.

This seems to be false - `video-zoom` works fine on my end with `video-unscaled=yes`, for both static images and actual videos. (I toggle `video-unscaled` from within `input.conf` but I don't think it's relevant.)

**Comment by wm4** [comment]
> (But not all; for example --video-zoom does nothing if this option is enabled.)

This isn't in the current version of the manpage?

**Comment by rr-** [comment]
...`waf` hasn't refreshed the manpages due to missing `rst2man`. I missed it. Sorry for the trouble.
