### ISSUE TITLE
osc-scalewindowed and osc-scalefullscreen are unreliable/glitchy

### ISSUE THREAD

**Issue by dardoor** [mpv-player/mpv#3429]
### mpv version and platform
mpv 0.19.0-git-ef2d6ed, Windows

### Reproduction steps
0. --script-opts=osc-scalewindowed=2,osc-scalefullscreen=1 in mpv.conf
1. open a video windowed
2. go fullscreen
3. go back to windowed (exit fullscreen)

### Expected behavior
It scales 2x when windowed and 1x when full screen.

### Actual behavior
It scales correctly the first time (when opening a file windowed), but later it mostly reverts to default scaling when windowed. Also when full screen it often scales incorrectly (2x).

It's not a big deal for me, because I eventually switched to osc-vidscale=no, but anyway.

**Comment by wm4** [comment]
So what does "later" mean? When you resize the window manually?

**Comment by dardoor** [comment]
Ah, sorry. I meant when I go fullscreen and back several times (pressing F, for example).

**Comment by dragons4life** [comment]
This is happening to me with the Sourceforge builds (haven't check the official builds, but I did compiled it myself and updated it to the last version and it worked fine)
https://sourceforge.net/projects/mpv-player-windows/

https://i.lithi.io/2DA2h.webm - sourceforge
https://i.lithi.io/ESmD.webm - compiled with mingw(it happens here once when I go fullscreen)
https://i.lithi.io/6tlkv.txt - log.txt (sourcefoge)
https://i.lithi.io/7tyj.conf - mpv.conf
