### ISSUE TITLE
core dump when reading a .ogv file

### ISSUE THREAD

**Issue by lartaud** [mpv-player/mpv#3441]
When I try to play the .ogv file I got from wikipedia, I get a core dump.
The file _can_ be played using MPlayer SVN-r37857; xine v0.99.9-[DEBUG] or VLC version 2.2.4 Weatherwax (2.2.3-37-g888b7e89).

### mpv version and platform
mpv 0.19.0 (Arch Linux x86_64)

### Reproduction steps
wget "https://upload.wikimedia.org/wikipedia/commons/a/a6/Use_of_a_coffee_press.ogv"
mpv Use_of_a_coffee_press.ogv

### Log files
http://sprunge.us/iCQe

### Sample files
I uploaded the file on 0X0.st just in case...
https://0x0.st/Mm-.ogv

**Comment by wm4** [comment]
Known/fixed in master.
