### ISSUE TITLE
Show version/put version info into "Properties-Details" tab in Windows 

### ISSUE THREAD

**Issue by bsto** [mpv-player/mpv#3443]
How do I find out the current release version of an MPV.exe program?

Normally when (Windows) users right click (in Windows Explorer) on the mpv.exe file then select "Properties" context menu entry and then goto to the "Details" tab the version should be listed there.

In mpv.exe its always 2.0.0.0 which is nonsense.

Please provide release version info at this usual place.

Thank you
Ben

**Comment by rossy** [comment]
You can find out mpv's version with the command line interface. Open a command prompt and type ``mpv --version``

The version info in the properties tab is bogus because of a bug in the build script. I want to fix it, but it's low priority.
