### ISSUE TITLE
sid=no and no-sub have no effect in config file

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#3447]
### mpv version and platform

tested with mpv 0.19.0 and 0.14.0 on OS X

### Reproduction steps

Enter either `sid=no` or `no-sub` in the mpv config file.
Play an mkv file with embedded subtitle track.

### Expected behavior

No subtitle track will be selected or displayed. UI overlay should show eg. `-/1`

### Actual behavior

The subtitle track is selected and displayed. UI shows `1/1`.

However, setting --sid=no or --no-sub on the command line gives the expected behavior. Also, setting `sub-visibility=no` in the config file supresses the subtitles. But then one must remember the keyboard command to show them if desired, as it's not possible to turn them on with the UI overlay.

**Comment by wm4** [comment]
Works for me. Also no log, I'm just going to close this.

**Comment by sumyungguy** [comment]
My fault, my conf file was misconfigured. Thanks for checking, sorry to waste your time...
