### ISSUE TITLE
windows opengl exclusive fullscreen

### ISSUE THREAD

**Issue by sda89ha9** [mpv-player/mpv#3449]
windows 10 AU, mpv git, amd radeon
with vo=opengl:backend=win, vsync-jitter is bad if dwm is bypassed (i.e. fullscreen)
[non exclusive fullscreen hack](http://pastebin.com/raw/hpcMJBQS); not sure why this works, found the solution [here](http://stackoverflow.com/questions/30293074/opengl-tearing-with-fullscreen-native-resolution)

comparison between exclusive fullscreen vs non exclusive fullscreen
**exclusive**
--fullscreen --video-sync=display-resample --vo=opengl-hq:dwmflush=auto (SwapInterval 1)
vsync-jitter **0.924**
--fullscreen --video-sync=display-resample --vo=opengl-hq:dwmflush=no (SwapInterval 1)
vsync-jitter **0.924**
--fullscreen --video-sync=display-resample --vo=opengl-hq:dwmflush=yes (SwapInterval 0 / causes tearing)
vsync-jitter **0.002**

**non exclusive**
--fullscreen --video-sync=display-resample --vo=opengl-hq:dwmflush=auto (SwapInterval 0)
vsync-jitter **0.002**
--fullscreen --video-sync=display-resample --vo=opengl-hq:dwmflush=no (SwapInterval 1)
vsync-jitter **0.002**
--fullscreen --video-sync=display-resample --vo=opengl-hq:dwmflush=yes (SwapInterval 0)
vsync-jitter **0.002**

while dwm is active, dwmflush or swapinterval both give identical vsync-jitter

**Comment by Frechdachs** [comment]
Try adding `glfinish` to the opengl options. That's the only way I achieved really low vsync-jitter on Windows 7 with a Radeon HD 7870.

>not sure why this works

Because the AMD driver on Windows automatically switches to fullscreen exclusive mode if the gl window has exactly the size of the monitor.
