### ISSUE TITLE
Segmentation fault when playing ogv file

### ISSUE THREAD

**Issue by miltondts** [mpv-player/mpv#3452]
### mpv version and platform
mpv 0.19.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Mon Aug 15 16:24:03 CEST 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.2

Linux 4.7.1-1-ARCH SMP PREEMPT Wed Aug 17 08:13:35 CEST 2016 x86_64 GNU/Linux

### Reproduction steps
open it
### Expected behavior
Plays the video file (like ffplay)
### Actual behavior
crash with Segmentation fault
### Log files
[mpv -v](http://pastebin.com/uaxQjnm7)
[gdb mpv](http://pastebin.com/5kBbjpj2)

### Sample files
[Download](http://ia802701.us.archive.org/33/items/MIT3_091SCF10/MIT3-091SCF10Exam_2_Prob_5b_300k.ogv)

**Comment by wm4** [comment]
Was already reported at least 3 times.

**Comment by miltondts** [comment]
Would you mind point me to the issues you mention? I tried to find it before posting but without luck.
