### ISSUE TITLE
Get current playback time 

### ISSUE THREAD

**Issue by Kota-Kun** [mpv-player/mpv#3453]
Hello!
How to get the total time of the video file, as well as current position with help from objective c from a running program?
I can get the name of the open file, but what about the rest do not know.

**Comment by SlainTrue** [comment]
+
I was also interested.

**Comment by paulguy** [comment]
I'm using the duration and time-pos properties in a program I'm writing, though I'm just using the input-ipc-server thing.

**Comment by wm4** [comment]
See https://mpv.io/manual/master/#command-interface
