### ISSUE TITLE
Vapoursynth & Multicore Support

### ISSUE THREAD

**Issue by morphological** [mpv-player/mpv#3454]
Hi there!

I am currently using a script contributed by haasn, with small adjustments to achieve constant interpolation and it works like a charm.
[mvtools.vpy](https://github.com/morphological/gentoo-conf/blob/nanodesu/home/nand/.mpv/filters/mvtools.vpy)

My i7 4690K at 4.6GHZ handles 1080p mkvs at about 60% - 69% load.

A friend of mine has recently lent me his X99 workstation with an i7 5960X, an 8 core CPU.
I have noticed that only two or sometimes three cores are heavily being used when playing an mkv with motion interpolation and the aforementioned script, while the rest remains untouched.

Since I am not allowed to overclock it, those individual cores are clocked at 3.2GHZ - 3.5GHZ with boost, which is seemingly insufficient.

It's quite frustrating to see that chip struggling with this.

Is there something I can do to enable or at least improve multi core support?
I am planning on getting the AMD Zen Summit Ridge chip next year and wouldn't want to resort to the i5.

**Comment by haasn** [comment]
Have you seen the `concurrent-frames` option to `vf_vapoursynth`?

**Comment by morphological** [comment]
I can't say that I have,  could you elaborate?

I have however checked the documentation based on your suggestion and found the following:

> num_threads¶
The number of concurrent threads used by the core. Can be set to change the number. Setting to a value less than one makes it default to the number of hardware threads.

You don't seem to have used that parameter in your script, hence I presume that the default value is being used?

**Comment by haasn** [comment]
@morphological see https://mpv.io/manual/master/#video-filters-vapoursynth

**Comment by morphological** [comment]
Thanks, it states that by default the option is set to the amount of logical cores detected, which implies that more than 4 cores my be leveraged.
Is this function itself also enabled by default?

**Comment by morphological** [comment]
Would that be the correct way of implementing it?
There are still only 2 - 3 cores used, unfortunately. 
 
mpv --vf=vapoursynth=mvtools.vpy  --buffered-frames=8 concurrent-frames=8

**Comment by morphological** [comment]
@haasn

Would that be the correct way of implementing it?
There are still only 2 - 3 cores used, unfortunately. 
 
mpv --vf=vapoursynth=mvtools.vpy  --buffered-frames=8 concurrent-frames=8

**Comment by wm4** [comment]
> mpv --vf=vapoursynth=mvtools.vpy --buffered-frames=8 --concurrent-frames=8

Wrong syntax, `mpv --vf=vapoursynth=mvtools.vpy:buffered-frames=8:concurrent-frames=8`. Tuning these parameters is probably the best you can do. mvtools is known to be slow.
