### ISSUE TITLE
YTDL: Huge memory usage per subtitle

### ISSUE THREAD

**Issue by popelmaus** [mpv-player/mpv#3456]
When playing a youtube video with mpv it needs about 80MB (private bytes) for a 4KB subtitle. This gets problematic when playing a video with lots of subtitles. For example most of pewdiepie's videos (like this one "https://www.youtube.com/watch?v=LZ0rGTsdfwk") have almost 40 subtitles and therefore generate over 3GB of Ram usage.
I tried using "ytdl-raw-options=sub-lang=en": The high Ram usage doesnt occur anymore and the video is loading about 3 times faster; but no subtitles, not even the english one, are loaded.

Maybe the long loading time only comes from downloading all the different subtitles and the 3GB of Ram are just reserved and arent actually used but its still a strange behaviour. And if this doesnt get fixed it would be really nice to limit the amount of subtitles that get loaded e.g. with "ytdl-raw-options=sub-lang=..."

BTW: Why is there no parameter to set ytdl's path?

(I used the latest youtube-dl and mpv.srsfckn.biz builds for windows with --no-config)

**Comment by wiiaboo** [comment]
You need to add "write-sub=" to ytdl-raw-options (ex: `ytdl-raw-options=sub-lang=en,write-sub=`) for ytdl to get the subs.
The RAM usage is probably libass?

> BTW: Why is there no parameter to set ytdl's path?

You don't need youtube-dl.exe in path, you place it in the same dir as mpv.exe or mpv's conf dir.

**Comment by wm4** [comment]
I can't confirm such an excessive memory usage. But it starts a cache thread for each file and keeps the http connection open, which doesn't seem ideal.

**Comment by popelmaus** [comment]
Its no real memory usage, probably just memory fragmentation.
If i start the video 3 times it "uses" 9GB of RAM which i dont have. And the "working set" is only 125MB per video.

**Comment by wm4** [comment]
I think most of this is caused by the cache creating a 75MB backbuffer for each subtitle file (which obviously doesn't make too much sense).

**Comment by wm4** [comment]
This should significantly reduce resource usage of those subtitle tracks.
