### ISSUE TITLE
windows WGL doublebuffer

### ISSUE THREAD

**Issue by sda89ha9** [mpv-player/mpv#3458]
windows 10, amd radeon
with doublebuffer removed ([patch](http://pastebin.com/raw/45Dcat9V)), i noticed some improvements:
non-exclusive fullscreen mode
smoother window / fullscreen transition
less vsync-jitter due to dwmflush always working
(very) slightly less memory usage

fullscreen mode
```
doublebuffer
[vo/opengl] upload time: last 17399us avg 4514us peak 17534us
[vo/opengl] render time: last 2021us avg 1711us peak 2025us
[vo/opengl] present time: last 314us avg 251us peak 318us
vsync-jitter: 0.426

doublebuffer removed
[vo/opengl] upload time: last 2696us avg 1523us peak 2758us
[vo/opengl] render time: last 1713us avg 1718us peak 2028us
[vo/opengl] present time: last 307us avg 249us peak 314us
vsync-jitter: 0.003
```
window mode
```
doublebuffer
[vo/opengl] upload time: last 2578us avg 1496us peak 2607us
[vo/opengl] render time: last 1633us avg 1639us peak 1966us
[vo/opengl] present time: last 137us avg 113us peak 139us
vsync-jitter: 0.002

doublebuffer removed
[vo/opengl] upload time: last 2609us avg 1516us peak 2768us
[vo/opengl] render time: last 1554us avg 1638us peak 1975us
[vo/opengl] present time: last 136us avg 112us peak 138us
vsync-jitter: 0.002
```

**Comment by rossy** [comment]
Yeah, disabling double buffering seems to prevent exclusive fullscreen mode. I think all the other improvements stem from that, rather than anything to do with double buffering itself (especially since the DWM makes everything double-buffered anyway.) If we were going to add another method of disabling exclusive fullscreen, I'd prefer to just make the window 1px larger than the screen size (as in #3449.)

Do dxinterop or angle work for you? They were added because it was so difficult to get WGL to behave well.

**Comment by wm4** [comment]
Also, does removing the `gl->Flush` call instead help?

**Comment by sda89ha9** [comment]
fullscreen vsync-jitter:
dxinterop 0.001
glFinish 0.002
non-exclusive 0.002
angle 0.162
normal 0.588
glFlush removed 0.588

dxinterop and angle work fine
also, no backend or option is bad enough to cause dropped, mistimed or delayed frames

**Comment by wm4** [comment]
Well, 0.588 is quite extreme. Angle is the default these days, though.

**Comment by sda89ha9** [comment]
>  Yeah, disabling double buffering seems to prevent exclusive fullscreen mode. I think all the other improvements stem from that, rather than anything to do with double buffering itself

true

so i guess there are 3 ways to prevent exclusive fullscreen mode for WGL
make window larger than screen size
set WS_BORDER and HWND_TOPMOST
disable double buffering

**Comment by wm4** [comment]
So what's the final conclusion?

**Comment by sda89ha9** [comment]
personally, i decided for exlusive fullscreen and glfinish
