### ISSUE TITLE
Put subtitles just under movie

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#346]
I ma not sure if this can be accomplished already but I have not found a way. I have a widescreen laptop (16:10. I use

    vf=expand=:::0:16/10:

To put the image on top of the screen. With 2.35:1 films, this results in a huge black streak in the lower half of the screen. The subtitles get loaded to the gottom of the screen. I would like them to load under the bottom (with some margin given by `--sub-text-margin-y`) of the film. I cannot do it now with `sub-pos` because the aspect ratios of different films differ and so the value of `sub-pos` would have to differ too.

Now, I could make a script that would get a resolution of the film and computed that value, but that would be kind of ugly. Much better if mpv allowed this somehow. As far as I know, it has all the information it needs - i.e. the size of my screen and the aspect ratio of the film.

This is mainly valid for full-screen use. I will open an issue about different options for fullscreen as an separate issue and reference it.

**Comment by hethhhhh** [comment]
neither `--ass-use-margins`; `--sub-text-margin-y`; r,t or `--sub-pos` (with or without `--no-ass`) works for me.
The only thing I could achieve was to get subtitles first row to appear on top of the movie, and second row to appear on top of the black bottom band with -vf expand=1680:1050
```

mpv git-59d44ec win64
ffmpeg library versions:
   libavutil       54.30.100
   libavcodec      56.57.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.32.100
   libswresample   1.2.101
ffmpeg version: N-74264-gfb21d32
```

**Comment by wm4** [comment]
``--sub-use-margins`` for non-ass text subtitles, ``--stretch-image-subs-to-screen`` for image subtitles. Enjoy your ugly and broken subtitles.

**Comment by Det87** [comment]
@wm4 weirdo response.

**Comment by felagund** [comment]
Looking back at it, I must agree that the original issue never get resolved.

**Comment by wm4** [comment]
> Yeah, that is a bit of a problem. libass (the subtitle renderer) can't do this kind of top alignment.

What I said 5 years ago is still true.

**Comment by Det87** [comment]
> > Yeah, that is a bit of a problem. libass (the subtitle renderer) can't do this kind of top alignment.
> 
> What I said 5 years ago is still true.

Enjoy your ugly and true statement, bro.

**Comment by wm4** [comment]
Always these entitled dumb fuck users...

**Comment by Det87** [comment]
> Always these entitled dumb fuck users...

I guess it's all matter of perspective lol.

Peace.

**Comment by wm4** [comment]
> ugly and broken subtitles

But that's what you get when using -vf=expand (in mplayer or when it still existed in mpv).

Anyway, enough of this.
