### ISSUE TITLE
d3d11va issue

### ISSUE THREAD

**Issue by cwbsw** [mpv-player/mpv#3464]
### mpv version and platform

mpv 0.20, Win10x64, 14393.82
### Reproduction steps

playing any H.264 files via d3d11va, other formats not tested. If I take screenshot by pressing "i", then the result is correct, so I take screenshot by Win10's screenshot tool.
### Expected behavior

playing correctly
### Actual behavior

![1](https://cloud.githubusercontent.com/assets/10339357/18032779/90170740-6d43-11e6-86f0-7ce8f4271cbb.png)
### Log files

http://sprunge.us/cXFI
### Sample files

not needed

**Comment by wm4** [comment]
Yes, that's most likely an issue with AMD drivers. The d3d_copy_texture branch fixes this, but may reduce efficiency with nvidia/Intel GPUs.

Still, this issue has come up amazingly rarely. Either there are not many mpv/AMD users who enable hwdec, or it happens only sometimes.

**Comment by li23jin** [comment]
google translate
ar problem and has long 
mpv 0.20, Win10x64, 14393.10 
amd hd 7850 Crimson-16.8.2-RC4 (tried different drivers)
![sample](https://cloud.githubusercontent.com/assets/21295874/18036392/519ab17e-6d7a-11e6-8c6d-d6b5c29930b2.png)

**Comment by dumpsters** [comment]
I think I have the same problem as seen on #3255 and d3d_copy_texture branch didn't fix it for me, I think the issue is with AMD drivers but I really have no idea.

**Comment by wm4** [comment]
The vlc developer who maintains d3d11 decoding in vlc said this is a known AMD driver bug (with texture arrays), and that they fixed it, but that there is no new driver release with the fix yet.

**Comment by cwbsw** [comment]
It seems that this AMD driver bug has been fixed. 

Windows 10 15063.13 
Crimson Relive 17.4.1
mpv 0.24
Radeon RX480

**Comment by wm4** [comment]
Can you post a mpv log so I can confirm?

> Crimson Relive 17.4.1

Is this the driver?

**Comment by cwbsw** [comment]
Yes, 17.4.1 is the latest non-WHQL AMD driver. 

http://sprunge.us/eESi

**Comment by wm4** [comment]
Yep that looks good. I'm glad this issue resolved itself. Thanks for testing.
