### ISSUE TITLE
[Feature request] Keyboard shortcut additions and documentation

### ISSUE THREAD

**Issue by carado** [mpv-player/mpv#3465]
### mpv version and platform

mpv 0.20.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Aug 27 12:41:39 CEST 2016

### Description

As it is, mpv has a ";" shortcut which reloads the current file. However, I’ve been missing such a shortcut for a long time because it’s not documented in the man page, and I only discovered it accidentally. By the way, a “reload file at current position” would be extremely appreciated.

Also, as indicated by the manual page, left-clicking and respectively shift+left-clicking on the current title of the media seem to be the only way to show the playlist position and respectively playlist content. Keyboard shortcuts would be a great improvement towards making mpv fully keyboard-usable.

**Comment by wiiaboo** [comment]
> Also, as indicated by the manual page, left-clicking and respectively shift+left-clicking on the current title of the media seem to be the only way to show the playlist position and respectively playlist content.

`<key> show-text "${playlist}"` in your input.conf

**Comment by dragons4life** [comment]
>As it is, mpv has a ";" shortcut which reloads the current file. However, I’ve been missing such a shortcut for a long time because it’s not documented in the man page, and I only discovered it accidentally. By the way, a “reload file at current position” would be extremely appreciated.
`` Shift+ESC run mpv ${path}; quit_watch_later  #restart the player with the same file at the same time
#Useful for whenever you are editing your .conf files ``

Something like that?

**Comment by carado** [comment]
> Something like that?

Oh, yeah, that seems to do the job. I’m sure keeping the full playlist isnt’t that hard, with `--playlist-pos=${playlist-pos}` and all.
Showing the playlist and playlist position can be bound to keys, indeed.

All that’s left is documenting ";" then. Sorry about my lack  of knowledge for the rest.

**Comment by wm4** [comment]
";" isn't mapped by default.

**Comment by carado** [comment]
Oh, right, sorry, got confused with my settings it seems.
