### ISSUE TITLE
Suggestion: Playlist - An actual usable list

### ISSUE THREAD

**Issue by Sethox** [mpv-player/mpv#3466]
As the title suggest I want to suggest to implement a better way to manage a playlist or queued videos.
As it is right now, it is manageable, but if the user can manage a list MPV would be fully set "_easy-to-use-package_". Regardless, this is just a suggestion and thank you for your time reading this.

**Comment by wm4** [comment]
Sorry, but your suggestion is way too unspecific to be useful. And even if it were, someone would have to implement it.
