### ISSUE TITLE
Read file from memory

### ISSUE THREAD

**Issue by eikoni** [mpv-player/mpv#3468]
Hi,

I need to read data from memory (option : memory:// or hex://), but i can't :

`mpv hex://FFD8FFE000104A46494600010101004800480000FFDB00430001010101010101010101010101010101010101010101010101010101010101010101010102020101020101010202020202020202020102020202020202020202FFC0000B08000E000E01011100FFC4001500010100000000000000000000000000000008FFC40032100000030406050D00000000000000000009161715181927000506142839252636374604070813233845484967698796FFDA0008010100003F009EF060E61E9005A8407CFA2749D47D3F5AEFEAD7DA6A9FB25409F3984CB3CC20337F177BF2D51F4DE2E0AD446CBBA7980D993FB3E566CE25BC5D444FB0607952C5FF002805AAFD17798B9FA3BA3654472AEF01E1E7F666EB2569738BA813E13E49D4B9962FF553285FC5DF99592A2EE8BF548BB95E86A9B0555EB1FA3FF233DEA0580EDC857EB47AC768CC7A2FFFD9`

In string way, it's possible or not  ?

Thanks for help.

**Comment by wm4** [comment]
I don't know what you want.

**Comment by eikoni** [comment]
Can it possible to leave an exemple with "memory:// or hex://" function? i need to load data (image, video, audio) only from memory, not from an url file. I dont know if is possible here. Thanks.

**Comment by wm4** [comment]
Yes, feel free to use those? There's also the stream_cb API.

**Comment by eikoni** [comment]
Ok, how we can use those ?... Please leave an exmple, it will help. Thanks.

**Comment by wm4** [comment]
https://github.com/mpv-player/mpv-examples/blob/master/libmpv/streamcb/simple-streamcb.c

**Comment by eikoni** [comment]
Thank you for the C code, but i will try to explain again my problem :
In my app i have a function : **loadFile** -> here we can launch mpv from a file. Great it work. MPV find the local file.
I have an other function : **loadFromMemory** -> here it can send binary data from a video file (i can convert to hex too, if needed),
but MPV do anything with the command line : mpv.com hex://some_data_in_hex_format
May be is not possible, or i miss some command line arguments ?
Thanks a lot for your help.
