### ISSUE TITLE
The D3D11 device was removed: 0x887A0006

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#3469]
### mpv version and platform
git-a05f20e - Win10-x64

Not sure if related or not, but I got this error (specifically, DXGI_ERROR_DEVICE_HUNG)

```
[statusline] AV: 00:03:40 / 00:04:29 (81%) A-V:  0.000 Dropped: 5
err: testDeviceLost(2563): The D3D11 device was removed: 0x887A0006
[statusline] AV: 00:03:40 / 00:04:29 (81%) A-V:  0.000 Dropped: 11
[statusline] AV: 00:03:40 / 00:04:29 (82%) A-V:  0.000 Dropped: 11
```

Also, the error didn't writen into log files instead only showed on command prompt only.

### Expected behavior
Play video&audio smoothly.

### Actual behavior
Video stop playing but audio still playing

### Log files
[log.txt](https://github.com/mpv-player/mpv/files/442761/log.txt)

**Comment by wm4** [comment]
D3D can "die" this way, and the API user is expected to restore it and recreate all state. The API user in this case is actually ANGLE, not mpv. I'm not sure what ANGLE's policy on this is.

When exactly does this happen?

**Comment by shinchiro** [comment]
Well, that's is my guess. It happen randomly with any video files recently.

Probably some ANGLE's commit within (1month?) introduced this.

**Comment by wm4** [comment]
Possibly 9c721c64170b6698bbc68b407d780d25b2f7133c?

**Comment by wm4** [comment]
By the way, the message you pointed is also printed by ANGLE (directly to stderr or stdout).

It's also possibly that your GPU driver recently just started to die randomly.

**Comment by shinchiro** [comment]
I dont get any of this error today even though I dont do anything. I'm going to blame my driver for this
