### ISSUE TITLE
Audio crackles after repeated seeking

### ISSUE THREAD

**Issue by mahkoh** [mpv-player/mpv#3470]
### mpv version and platform

```
~$ mpv --version
mpv 0.19.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Mon Aug 15 16:24:03 CEST 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.2
```

On arch. This is nothing new.

### Reproduction steps

Play any video. Once the video reaches the end use a trackpad to "scroll back" / seek back to the start. (Results may vary when a lower precision seeking method such as a scroll wheel or up/down arrows are used.) Repeat this often as necessary.

### Expected behavior

The audio quality stays the same.

### Actual behavior

The audio starts to crackle. Restarting the player fixes this problem.

### Log files

https://gist.github.com/anonymous/3bb8e8e1bc82ea340506c71685e17452

The following lines sometimes appear in red during seeking:

```
[ffmpeg/video] h264: mmco: unref short failure
[ffmpeg/video] h264: mmco: unref short failure
```

**Comment by wm4** [comment]
Does disabling and enabling audio with `#` help?

**Comment by mahkoh** [comment]
No. I've realized that this is caused by the software volume control. Changing the volume is bound to left-right scrolling and even a small change to 106% can cause noticeable crackling. Setting `--volume-max` to 100 fixes the problem.
