### ISSUE TITLE
Create screenshot directory if it doesn't exist

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3471]
Currently if the screenshot directory doesn't exist, a message is displayed notifying the error, but I personally set no-osd for the screenshot keymap because it's just unnecessary to have it 99% of the time, so I never get to see the message. Because of this, one time after I renamed some folders, I missed the message and ended up "losing" a lot of screenshots that I (didn't) took while watching some videos.

I think it may be useful if the directory is created if it doesn't exist. FRAPS does this.

**Comment by wm4** [comment]
``--screenshot-directory`` does this already.

**Comment by firewater2** [comment]
Neat! I must have missed that one when I made the .conf file...

I'm not sure why I had to add [pseudo-gui] to it though (I don't have it enabled).

**Comment by wm4** [comment]
pseudo-gui is automatically enabled depending on how you start mpv.
