### ISSUE TITLE
Show audio format in audio OSD line

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3473]
Hi!

Currently audio OSD line (i.e. the one when cycling audio tracks with '#' key) doesn't show track's format (i.e. AC-3,  DTS, etc).

Is it possible to add it there?

**Comment by Cpuroast** [comment]
probably not,

but you can easily remap the keys in input.conf and have it display whatever you want:

https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst

This is the default key mapping
https://github.com/mpv-player/mpv/blob/master/etc/input.conf

You can simply create an empty input.conf and add the mapping overrides you want.

**Comment by fhlfibh** [comment]
@Cpuroast 
I'm quite happy with '#' key for now.
The problem is when I press it, the OSD line shows something like:
`Audio: (5) eng (track description)`
I'd like it to show something like:
`Audio: (5) eng DTS (track description)`

**Comment by Cpuroast** [comment]
That's what I was talking about, you can override the display so it shows the current display and add the audio format.

All that can be done using a custom input.conf mapping

**Comment by Cpuroast** [comment]
Example: 

If you put this in your input.conf file:

SHARP cycle audio ; show-text "Audio: ${aid} ${audio-codec-name}"

You'll get something very close to what you want, with a few changes on what properties are displayed, you could get exactly the display you want.

All the properties available for display are on this page:

https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst

**Comment by fhlfibh** [comment]
@Cpuroast i'll try that, thanks.
