### ISSUE TITLE
jump next line feature

### ISSUE THREAD

**Issue by behroozramezani** [mpv-player/mpv#3474]
Hello 
Why mpv dosen't support shortkey for jump next line subtitle and previous line? this is good feature.
other players like smplayer support it. Does add this feature to mpv?

**Comment by wm4** [comment]
You have to bind the `sub-seek` command in your input.conf.

**Comment by wm4** [comment]
And actually the manual says it's already bound to `Ctrl+LEFT and Ctrl+RIGHT`.

**Comment by behroozramezani** [comment]
Thanks
