### ISSUE TITLE
Add new feature "open as full-screen window"

### ISSUE THREAD

**Issue by OtoriTakeo** [mpv-player/mpv#3475]
MPV 0.20.0 on OS X 10.11.6
### Request

Add a new flag/feature to open mpv as full-screen window in OS X. In contrary to the current full-screen flag '--fs', it should enforce a full-screen window and not an full-screen 'overlay'. I suggest something like '--fs-app' or '--fs-window'. 
By opening mpv in full-screen windowed mode, it would allow the user to still use the desktop, without the need of disabling full-screen (overlay) and thus result in more harmonic experience within OS X. 
Furthermore I believe it could result in 'out of the box' compatibility with the in macOS 10.12 newly introduced 'Picture in Picture' feature. Although I don't have tested nor further info on it yet.

Suggested Lables: osx (only) / feature request / low priority

**Comment by Akemi** [comment]
isn't that what `--no-native-fs`? if not, you need to explain this a bit further.
