### ISSUE TITLE
[Windows] "frame-step" ignores "input-ar-rate" settings

### ISSUE THREAD

**Issue by garoto** [mpv-player/mpv#3476]
Not sure if a bug or a container/codec limitation, but reporting it anyway. Tried with many combinations of containers/codecs: .AVI+XviD, .AVI+h264, .MKV+h264, .MP4+h264, .MPG+MPEG-2.

### mpv version and platform
Windows 8.1 [Microsoft Windows [Version 6.3.9600]]

>mpv --version
>    cplayer: mpv 0.20.0-git-c226bc7 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
>    cplayer:  built on Fri Aug 26 19:57:46 CEST 2016
>    cplayer: ffmpeg library versions:
>    cplayer:    libavutil       55.29.100
>    cplayer:    libavcodec      57.54.100
>    cplayer:    libavformat     57.48.100
>    cplayer:    libswscale      4.1.100
>    cplayer:    libavfilter     6.56.100
>    cplayer:    libswresample   2.1.100
>    cplayer: ffmpeg version: N-81464-g5686748

### Reproduction steps
mpv --input-ar-rate=1 `<video.file>`

### Expected behavior
Holding the `frame-step` key bind should advance frames respecting `input-ar-rate` settings, like `frame-back-step` does.

### Actual behavior
Holding the `frame-step` key, `input-ar-rate` is ignored and video plays at its default rate.

### Log files
http://sprunge.us/GXRG

### Sample files
n/a

**Comment by wm4** [comment]
frame-step literally unpauses video playback for a frame, so it can't work like this. All you'd get is continuous playback, which it already does (until you release the key - at least on the VO window).
