### ISSUE TITLE
Named Pipe return messages not clearing after being retrieved?

### ISSUE THREAD

**Issue by smarrocco** [mpv-player/mpv#3478]
mpv 0.19.0-git-ef2d6ed

I am using mpv on Windows 10 in a vb.net 2012 Framework 4.5 application, embedded as a player (with the -wid option) successfully. Using named pipes I am able to send/receive commands & return info.

After I've sent a command to the named pipe for mpv and it has responded, my returned information seems to be odd. An example: After I've created an instance of MPV with a media file, created a pipe, and paused MPV playback....

I send 'pause' to MPV via the named pipe. I receive back
{"event":"unpause"}
{"event":"pause"}

I send another 'pause'. I receive back
{"event":"unpause"}
{"event":"pause"}
{"event":"unpause"}
{"event":"pause"}

I send another 'pause'. I receive back
{"event":"unpause"}
{"event":"pause"}
{"event":"unpause"}
{"event":"pause"}
{"event":"unpause"}
{"event":"pause"}

It seems as though the event messages that are being returned are accumulating and not being cleared after being retrieved....? Commands seem to be executed properly by MPV, only the return messages seem amiss. 

The reading of the returned messages is being done with a simple streamreader that does a ReadLine() until the Pipe's stream is empty, one line at a time.

**Comment by smarrocco** [comment]
Thank you for the sample. I'm having some trouble porting the sample C# to vb.net, but your example seems to indicate that my code is somehow re-sending the same commands multiple time, perhaps not flushing after the sending of a command. I will look into it. Is there perhaps a vb.net version of the sample you sent? I've been looking at the c# API examples, but there doesn't seem to be much documentation on it, prerequisites, etc.

**Comment by rossy** [comment]
Ah, sorry about that. It's been a while since I've written any VB.NET, so I decided to stick with what I know and write that test program in C#. I don't think I could port it to VB.NET either, but if you have VB.NET code that can reproduce the bug, I could probably read it. It might be that your code is sending commands multiple times (or reading responses more than once,) but I'm not totally ready to rule out a bug on mpv's side.

That said, if you're porting your program to libmpv, that's probably the best option.

**Comment by smarrocco** [comment]
I appreciate the offer, but I've done as you suggested and moved away from named pipes and am attempting using the API. Some of the core functionality for setting/getting properties and sending commands in the examples helped me get it running quickly. The biggest issue I'm having right now is that there are no examples of using events, and some of the commands (Load, for example) are asynchronous and there doesn't seem to be a method of checking a property for something like "File loaded/file loading" statuses. Do you know of any existing event examples for dotnet and the api?
