### ISSUE TITLE
Maximize window on startup

### ISSUE THREAD

**Issue by guivieiras** [mpv-player/mpv#3481]
Am I missing something or there is no such command/script for this? Sorry if I'm asking in the wrong place, but i didn't found a "Question" forum or something.

**Comment by wm4** [comment]
Doesn't exist, technically possible.

**Comment by UserNaem** [comment]
Yes, it's possible with https://github.com/kevinlekiller/mpv_scripts/tree/master/maximize

**Comment by Dudemanguy** [comment]
There's `--window-maximized`.
