### ISSUE TITLE
[Windows] When starting mpv with --pause and --start, taskbar progress isn't shown.

### ISSUE THREAD

**Issue by pavelxdd** [mpv-player/mpv#3482]
### mpv version and platform
> mpv --version
mpv git-453fea8 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Fri Sep  2 02:10:04 MSK 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.3

### Reproduction steps
Start the mpv with --pause and --start,
for example `mpv *.mkv --start=5:00 --pause`

### Expected behavior
Taskbar progress should be visible and have a color of paused state.

### Actual behavior
Taskbar progress will only be rendered after starting the playback.

### Log files
http://sprunge.us/MeWS

**Comment by wm4** [comment]
This likely fixes it, but I didn't test it myself.

**Comment by pavelxdd** [comment]
I launched the video a few times, and taskbar was rendered correctly only on ~2 times out of 10.
Seems like it's not fixed.

**Comment by wm4** [comment]
Could reproduce on a real windows, fixed locally.

**Comment by wm4** [comment]
Pushed the fix a while ago.

**Comment by pavelxdd** [comment]
Yes, it's fixed now. Thank you!
