### ISSUE TITLE
Parameter --zones in mpv-player

### ISSUE THREAD

**Issue by NewUserLinux** [mpv-player/mpv#3483]
Hi!. 

How to use the parameter "--zones frame start,frame end,crf/frame start,frame end,crf/..." for encoding with MPV? I want to know the syntax, please.

**Comment by wm4** [comment]
It doesn't have such a parameter.

**Comment by NewUserLinux** [comment]
Using "-x264-params" is no posible?

**Comment by wm4** [comment]
In that case it's be somehow passed to ``--ovcopts``, but don't ask me how.

**Comment by NewUserLinux** [comment]
Ok, thanks.
