### ISSUE TITLE
fallback to angle-es2 when using profile=opengl-hq

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#3485]
### mpv version and platform
c92450d - Win10-x64

### Reproduction steps
For some reason, when you use new `profile=opengl-hq` option, the default backend which is `angle` will fallback to `angle-es2`. But if you explicitly type `opengl-backend=angle` , this will solve the issue.

**Comment by wm4** [comment]
I think it was the "opengl-es=no" flag.

**Comment by Hrxn** [comment]
> new `profile=opengl-hq`

What new profile is this? Not yet documented?

And what is the default for this backend? If you don't set `es=..`, GLES gets used?
