### ISSUE TITLE
Will mpv support vaapi while playing with SVP (Smooth Video Project)?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#3486]
### mpv version and platform
 UTC 2016
ffmpeg library versions:
   libavutil       55.29.100
   libavcodec      57.54.101
   libavformat     57.48.101
   libswscale      4.1.100
   libavfilter     6.58.100
   libswresample   2.1.100
ffmpeg version: 3.0.git

Will it support vaapi while playing with SVP?

**Comment by wm4** [comment]
Unless vapoursynth somehow gained vaapi support, no. vaapi-copy probably works.

**Comment by JulianLai** [comment]
But the developer of vapoursynth says that there is no incompatibility between VapourSynth and vaapi.
