### ISSUE TITLE
Scaler-resizes-only is not default in opengl-hq anymore

### ISSUE THREAD

**Issue by gtm87x** [mpv-player/mpv#3487]
The `scaler-resizes-only` suboption used to be enabled by default in vo=opengl-hq, but it isn't anymore in the opengl-hq profile after commit 849480d0c9d5ef76bd3296034b2ad5019fb9c21d. Was that an oversight like 0c2c059826df1f0463c5cf741d717c6315b4317e or a deliberate change?

**Comment by wm4** [comment]
As far as I can see, it's still the default, even for plain vo_opengl.
