### ISSUE TITLE
Is it possible to support remembering last play point when reopen a video?

### ISSUE THREAD

**Issue by ray6080** [mpv-player/mpv#3491]
I on using Mac version of mpv, and I'm used to play from where I left when reopen a video. So I don't see any support, is it possible to add this as a new feature? And I'm willing to try coding on it.

**Comment by wiiaboo** [comment]
Use Shift+q to exit video if usin default bindings.

**Comment by ray6080** [comment]
Thank u. I missed it. Sorry.
