### ISSUE TITLE
Changing default screenshot directory

### ISSUE THREAD

**Issue by amnesiac-kid** [mpv-player/mpv#3492]
mpv git-bc97d60 

Is there a way to change the default screenshot directory? I am using Ubuntu 16.04 LTS. 
The screenshots get saved in the default home directory, which is problematic if you use Nautilus as a file browser. Nautilus has problems displaying directories with many images inside and adds a lot of loading time while opening them. And the home directory is not really the place you want to be clogged up with images and loading times. 

I always move my screenshots after some time into my screenshot directory, but I have to use multiple folders inside, because every time I move the screenshots, the numeration of the files in the home directory resets, so I have a lot of duplicate names. For a temporary solution, is there a way to make the file numeration not reset when moving the screenshots to a new directory?

**Comment by wm4** [comment]
I think you want this: https://mpv.io/manual/master/#options-screenshot-directory

You might have to put it under a pseudo-gui section, depending of how you start the player.

**Comment by tch1121** [comment]
How to save to $pwd?
```
[builtin-pseudo-gui]
screenshot-directory=.
or
[builtin-pseudo-gui]
screenshot-directory=$pwd
```
