### ISSUE TITLE
[question|help]how to use CrystallHD

### ISSUE THREAD

**Issue by zhangn1985** [mpv-player/mpv#3493]
hi,
I have one CrystalHD card (BCM70015), and installed driver from: https://github.com/dbason/crystalhd

and I can find logs:
```
[ 1338.322581] Loading crystalhd v3.10.0
[ 1338.322628] crystalhd 0000:04:00.0: Starting Device:0x1615
```
but when using mpv play H264 movie, i get the log:

```
Not trying to use hardware decoding: codec h264 is not on whitelist, or does not support hardware acceleration.
```
but when using vlc, i get:

```
Running DIL (3.22.0) Version
DtsDeviceOpen: Opening HW in mode 0
Scaling command param 0x0,ctx_scal:0x0
[00007f5b68c9e8c8] crystalhd decoder: Opened CrystalHD hardware with success
```
but black screen.

so, my question is
could mpv use CrystalHD for hwdecoding, if yes how?

**Comment by wm4** [comment]
Might be possible with ``--vd=lavc:h264_crystalhd``, if FFmpeg has it compiled it. But from what I know even the author of the FFmpeg wrapper has abandoned it, so you're up on your own.

**Comment by philipl** [comment]
(I'm that author).

I haven't verified it myself, but --vd=lavc:h264_crystalhd should work. I don't have easy access to the hardware anymore.

**Comment by zhangn1985** [comment]
think you!!
