### ISSUE TITLE
Outdated doc

### ISSUE THREAD

**Issue by Rick74crx** [mpv-player/mpv#3497]
Several bits of the doc still suggest the use of the deprecated suboption system, e.g. the usage's and the profiles' examples or the hwdec part. Also, the auto profiles' part doesn't say that ao's and vo's ones are deprecated.
I'm not skilled enough with git to make a PR, but I thought I should let you know.

**Comment by wm4** [comment]
That's all in flux. Can you point out the places that need updating?

**Comment by Rick74crx** [comment]
Sure:
'Escaping spaces and other special characters' under 'Usage' (DOCS/man/mpv.rst) contains almost exclusively examples with the old system, same with the 'Profile' section (same file). vo.rst and ao.rst both does at the beginning, and options.rst shows the deprecated vo=opengl:backend suboption in the hwdec section and under the field-dominance option description. Last one I noticed is in the ao=null description.

**Comment by wm4** [comment]
Let me know if there are any other leftovers.
