### ISSUE TITLE
Any examples of dotnet using mpv1.dll/api events?

### ISSUE THREAD

**Issue by smarrocco** [mpv-player/mpv#3498]
I am using the mpv1.dll/api in a vb.net 2012 app to play back media files. I have used the csharp sample to achieve switching from named pipes to the api, however I can find no examples/samples of using events. The existing csharp sample code seems to return immediately after beginning to load a media file, and subsequent get properties return incorrect data until the file load is completed, appearing to be an asynchronous load.

Are there any examples of this for dotnet, or is there a complete wrapper for managed code?

Or alternatively, is there a property to check from a loop that will tell me when a file load has completed?

**Comment by rossy** [comment]
Yeah, files are always loaded asynchronously. I'm not aware of any .NET examples or wrappers that can wait for events. The easiest way to do it would be to spin up a thread and call mpv_wait_event() in a loop, though that will still require writing your own P/Invoke struct definitions for all the events libmpv can generate.

**Comment by smarrocco** [comment]
Never having done that, I might have to find a simpler alternative until I can make time to explore that option. It might be a nice feature addition to have a "Status" property added that can be checked for file status (None, Loading, Loaded, timeout, etc). That could be useful even for the json/named pipe usage as well as the api.
