### ISSUE TITLE
Display multiple subtitles 

### ISSUE THREAD

**Issue by yshui** [mpv-player/mpv#350]
It sometimes makes sense to display multiple subtitles at the same time. Like displaying commentary subtitle or storyboard alongside the normal subtitle

**Comment by realyukii** [comment]
Is there a way to enable secondary subtitle from mpv's console (`backtick`)?

EDIT:
The g-S keybinding only work on Linux, to load secondary subtitle on Windows, I use `set secondary-sid <sid>` from mpv's console.

**Comment by guidocella** [comment]
The `g-S` keybinding selects secondary subtitles.
