### ISSUE TITLE
Add option to always display OSC for audio-only?

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [mpv-player/mpv#3500]
There needs to be an option to always display the onscreen controller when no video track is loaded.

(And, possibly, an option to always display the onscreen controller if the video track is merely cover art.)
### mpv version and platform

2:0.19.0~trusty @ mpv-tests PPA

Mint 17.3 x64
### Reproduction steps
- Play music files
### Expected behavior

The OSC should stick around, or else it should be possible to configure it to do so.
### Actual behavior

The OSC hides itself when the mouse is not present, and there is no way to override this behavior on the basis of video track presence.

**Comment by avih** [comment]
You can set the OSC visibility as three different modes: `always`, `auto` (on mouse move) and `never` using:
- Pressing the DEL key to cycle those.
- Send a script message, e.g. at `input.conf`: `a script-message osc-visibility never`.
- Using a command line or config value such as `--script-opts=osc-visibility=always`.

You'd need a relatively recent (two-three months) version of mpv for those.

**Comment by JamesTheAwesomeDude** [comment]
Aha, thanks for telling me about the DEL key for that. That's definitely a suitable workaround.

**Comment by avih** [comment]
> The only thing remaining now is whether this can be automatically done for files which do not contain video (and, optionally, for files whose only video track is cover art.) And at that point, it's basically only a matter of convenience.

Not out of the box, but it should be possible with a small lua script.

**Comment by AirPort** [comment]
I "wrote" a [script](https://gist.github.com/AirPort/694d919b16246bc3130c8cc302415a89) a couple of weeks ago pretty much for the same user case. I use it with `audio-display=no` (I don't like cover art visualization too much), and if it detects no video it sends the `osc-visibility=always` message and it prints the audio file's metadata in the player's window.
I'm by no means a developer so it's really, really rough, probably not too much efficient and there are a couple of corner cases in mixed playlists which make it behave not so well, but I use it on a daily basis and it does its job, and maybe an actual dev can get something decent out of it.

**Comment by wolftune** [comment]
+1 on this, would love it to be a built-in default

**Comment by avih** [comment]
For reference, this is the section from @AirPort 's script which does "always OSC if only audio".

Save this as `audio-osc.lua` and put it at the `scripts` dir inside mpv config dir:
```lua
mp.register_event("file-loaded", function()
    if mp.get_property_osd("video") == "no" then
        mp.commandv("script-message", "osc-visibility", "always", "no-osd")
        -- remove the next line if you want to keep the osd bar when no video
        mp.commandv("set", "options/osd-bar", "no")
    end
end)
```

**Comment by ubone** [comment]
I was trying to do this with profiles in mpv.conf but it doesn't work.
`--script-opts=osc-visibility=always` works in mpv.conf but only outside of the profiles.
```
# mpv.conf
[extension.gif]
loop-file=inf
[extension.webm]
loop-file=inf
[extension.mp2]
script-opts=osc-visibility=always
stop-screensaver=no
[extension.mp3]
script-opts=osc-visibility=always
stop-screensaver=no
[extension.mp4a]
script-opts=osc-visibility=always
stop-screensaver=no
[extension.ogg]
script-opts=osc-visibility=always
stop-screensaver=no
[extension.opus]
script-opts=osc-visibility=always
stop-screensaver=no
[extension.flac]
script-opts=osc-visibility=always
stop-screensaver=no
[extension.wav]
script-opts=osc-visibility=always
stop-screensaver=no
[extension.wma]
script-opts=osc-visibility=always
stop-screensaver=no
```
output with mpv.conf https://gist.github.com/f3585c8136b1a13f2170239d09f677e0

output with `--no-config` and `--script-opts=osc-visibility=always`
https://gist.github.com/65deba6e3e05fb2ed8b86b59e08764d4

**Comment by avih** [comment]
@ubone please open a new issue. Unless you have a reason to believe otherwise, this seems unrelated to this feature request.

**Comment by Akemi** [comment]
should be done via a script which also already exists.

**Comment by grolongo** [comment]
old thread but if you stumble onto this you can also do the simpler:  
```conf
[extension.mp3]
script-opts=osc-visibility=always
```
in your mpv.conf file

**Comment by rieje** [comment]
@grolongo This is more general purpose and handles OP's requirement of also appling to coverart:

    [audio]
    profile-cond=not vid and not vo_configured or p["current-tracks/video/albumart"]
    script-opts-add=osc-visibility=always

**Comment by guidocella** [comment]
`vo-configured` is true when you play audio with `--force-window` and no video track:

```
[audio]
profile-cond=not vid and vo_configured or p["current-tracks/video/albumart"]
script-opts-add=osc-visibility=always
```
