### ISSUE TITLE
Something's not right in ao_rsound.c

### ISSUE THREAD

**Issue by OrdinaryMagician** [mpv-player/mpv#3501]
### Reproduction steps

Compile.

### Expected behavior

It compiles.

### Actual behavior

It doesn't compile.

```
In file included from ../audio/out/ao_rsound.c:31:0:
../audio/out/ao_rsound.c:162:13: error: request for member 'deprecation_message' in something not a structure or union
             .deprecation_message = "request --audio-device support on issue tracker"),
             ^
/home/marisa/.cache/pacaur/mpv-build-git/src/mpv/options/m_option.h:551:32: note: in definition of macro 'OPT_GENERAL'
     {.name = optname, .flags = flagv,                                   \
                                ^~~~~
../audio/out/ao_rsound.c:161:9: note: in expansion of macro 'OPT_STRING'
         OPT_STRING("port", port, 0
         ^~~~~~~~~~

```

### Log files

N/A

### Sample files

N/A

**Comment by wm4** [comment]
This probably fixes it, though I didn't try it myself.

**Comment by OrdinaryMagician** [comment]
It did.

**Comment by wm4** [comment]
Thanks. Are you actually using rsound, or was it just automatically enabled because it was on your system?

**Comment by OrdinaryMagician** [comment]
Possibly the latter. I haven't checked what the AUR package enables.

**Comment by qmega** [comment]
If you're using the mpv-git AUR package, it doesn't explicitly enable anything other than the shared library and zsh completion. mpv's build enables whatever it finds automatically and the package picks up whatever dependencies are linked against. If rsound were to be removed or default-disabled in mpv, the package would stop using it next time you built it. I think you'd have to use --ao=rsound to actually use it, so if you don't know you are then you're probably not.

**Comment by OrdinaryMagician** [comment]
Oh well, I do have rsound installed and it's listed as a dependency of mpv-build-git so...

**Comment by wm4** [comment]
I've only asked because I never met anyone who actually used it. (As in, really used it, not just built it.)
