### ISSUE TITLE
Single frame audio playback possible?

### ISSUE THREAD

**Issue by smarrocco** [mpv-player/mpv#3502]
Is there a method of allowing audio playback during "frame-back-step" and "frame-step" operations, i.e. hearing a single frame's audio playback as you step through it?

**Comment by wm4** [comment]
This is already done for frame-step. frame-step literally plays video and audio for exactly 1 video frame. But the audio output you use might "flush" the audio when pausing, which means you'd hear nothing. For frame-back-step we'd have to reverse audio somehow, so no.
