### ISSUE TITLE
Shift+MOUSE_BTN3 acts as Shift+MOUSE_BTN4

### ISSUE THREAD

**Issue by iiiGerardoiii** [mpv-player/mpv#3506]
### mpv version and platform

0.20.0 on macOS 10.12 Beta (16A313a)
### Reproduction steps
- Add this on `input.conf`:

```
Shift+MOUSE_BTN3    seek 5
Shift+MOUSE_BTN4    seek -5
```
- Then, scroll up with the mouse wheel while holding Shift.
### Expected behavior

video should seek forward 5 seconds
### Actual behavior

video seeks backward 5 seconds
### Note

Alt+MOUSE_BTN3 works fine, same with Meta+MOUSE_BTN3.

**Comment by wm4** [comment]
Works on Linux, so this must be an issue with the OSX code.

**Comment by Akemi** [comment]
should be fixed with the above [change](https://github.com/Akemi/mpv/commit/4d4a95bb304a3d177e07b4dd713f70065d436b0b). let me know if that worked for you, otherwise i will merge it tomorrow.
