### ISSUE TITLE
opengl-hq distorts colors for some video files

### ISSUE THREAD

**Issue by avi9526** [mpv-player/mpv#3517]
### mpv version and platform

ArchLinux, problem persist with repository version:

> mpv 0.20.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
>  built on Sat Aug 27 12:41:39 CEST 2016
> ffmpeg library versions:
>    libavutil       55.28.100
>    libavcodec      57.48.101
>    libavformat     57.41.100
>    libswscale      4.1.100
>    libavfilter     6.47.100
>    libswresample   2.1.100
> ffmpeg version: 3.1.3

and with aur version https://aur.archlinux.org/packages/mpv-git/

> mpv git-343f5ca (C) 2000-2016 mpv/MPlayer/mplayer2 projects
>  built on Mon Sep 12 20:08:33 EEST 2016
> ffmpeg library versions:
>    libavutil       55.28.100
>    libavcodec      57.48.101
>    libavformat     57.41.100
>    libswscale      4.1.100
>    libavfilter     6.47.100
>    libswresample   2.1.100
> ffmpeg version: 3.1.3
### Reproduction steps

Open this file https://0x0.st/SSy.mp4 (ask if upload to other storage)
with console command:
`mpv "Overwatch 09.10.2016 - 12.56.54.09.DVR.mp4"`
or
`mpv --profile=opengl-hq "Overwatch 09.10.2016 - 12.56.54.09.DVR.mp4"`
or use smplayer with opengl(-hq) as output driver
### Actual behavior and Expected behavior

Compare this two images, left (bad colors) is with `--profile=opengl-hq`, right (good colors) is with --vo=vdpau
http://imgur.com/IBvg2hb
### Log files

http://pastebin.com/raw/w5MbHpAJ

**Comment by haasn** [comment]
Do you have a reference image for comparison? Or how do you know the one on the left is wrong?

**Comment by avi9526** [comment]
1) I have played that game, it look more like right one
2) Open using:
vlc, mplayer, windows player, basically any other player that I have and is not mpv with opengl

**Comment by qmega** [comment]
The video is tagged with BT.601 but should be BT.709. Using `--vf=format=colormatrix=bt.709:primaries=bt.709` makes it look right. (I've also played the game and the BT.709 result is more accurate.)

**Comment by haasn** [comment]
Can confirm what @qmega said, looking at the file it seems to have some pretty messed up tags.

```
Color range                              : Limited
Color primaries                          : BT.601 NTSC
Transfer characteristics                 : BT.470 System M
Matrix coefficients                      : BT.601
```

If this is the output of a screen capture than it should most likely be tagged as BT.709/sRGB for the colorspace, and the matrix coefficients should be set to whatever the encoder used while encoding.

> 1) I have played that game, it look more like right one

As far as we know, all this indicates is that the file might be broken or mistagged. (Which indeed seems to be the case here)

> 2) Open using:
vlc, mplayer, windows player, basically any other player that I have and is not mpv with opengl
> 3) When I was last time checking my eyes I was not colourblind

Neither of these are valid points

**Comment by sda89ha9** [comment]
--vf=format=primaries=bt.709, result is comparable to mpc-hc

**Comment by haasn** [comment]
@wm4 Btw, shouldn't vo_vdpau also use the BT.601 matrix if tagged like that? vo_vdpau uses BT.709 always on my end on this clip, that seems like a bug to me.

**Comment by avi9526** [comment]
> Neither of these are valid points
sorry, getting salty after playing that game

It looks like you are right, the problem is with original software, which seems to be known issue for 2 years now https://forums.geforce.com/default/topic/789194/shadowplay-recording-the-wrong-colours/?offset=1

**Comment by wm4** [comment]
So does f7471b7ff48540a4184fb095e23b2c50d9720375 fix this?

**Comment by haasn** [comment]
@wm4 My guess is that it should at least make the issue smaller to the point where it's no longer as obvious :p
