### ISSUE TITLE
Make interface not scale with window resizing

### ISSUE THREAD

**Issue by strelec** [mpv-player/mpv#3518]
It is really annoying when playing high-resolution video and you resize it to something smaller and the interface becomes so small it is barely visible.

My assumption is that, even without having it, 4k monitors might have this problem in a much greater extent.

Could the interface be fixed, independent on the window size?

**Comment by haasn** [comment]
See `--osd-scale-by-window`.

**Comment by wm4** [comment]
I suspect he means the OSC, which that option doesn't affect.

**Comment by strelec** [comment]
I mean this interface:

http://imgur.com/a/2yN7E

**Comment by dragons4life** [comment]
https://mpv.io/manual/master/#command-line-syntax

**Comment by wm4** [comment]
> I mean this interface:

Yes that's the OSC. It has its own options described in the manual. Not sure if what you want is covered.

**Comment by strelec** [comment]
It is not covered. Take a look at the interface below, I cannot read it.

Again: Interface should not resize with window.

http://imgur.com/a/fx4Mz

**Comment by wm4** [comment]
I'm fairly sure there's something.

**Comment by avih** [comment]
> It is not covered. Take a look at the interface below, I cannot read it.

Try this: `script-opts=osc-layout=bottombar,osc-vidscale=no`

**Comment by strelec** [comment]
Thanks.

Maybe consider making this a default.
