### ISSUE TITLE
many snow dots on screen

### ISSUE THREAD

**Issue by outsinre** [mpv-player/mpv#3521]
### mpv version and platform

mpv git-26b6d74; Thinkpad Linux x86_64; Intel integrated graphics.
### Reproduction steps

`mpv https://0x0.st/SSy.mp4`

or download the video locally and

`mpv SSy.mp4`
### Expected behavior

normal playing
### Actual behavior

The playing has many dots, sometimes even the whole video screen. This happens usually for HD videos i.e. 1080p.

http://imgur.com/a/FYyhp and https://imgur.com/a/mKXCp
### Log files

log: https://gist.github.com/anonymous/51403fdee24b2cf718731c0cf6c0734d

mpv.conf: https://gist.github.com/c2e04e41d4c7607557eff2dee625d193
### Sample files

https://0x0.st/SSy.mp4

**Comment by wm4** [comment]
Try with --on-config, also missing log.

**Comment by outsinre** [comment]
@wm4 Many thanks. I have updated my issue.

I have tried your suggestion with `--no-config`. The dots are gone but the console ouput:

```
mpv --log-file=no-config.txt --no-config SSy.mp4 
Playing: SSy.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
AO: [alsa] 48000Hz stereo 2ch float
VO: [opengl] 1728x1080 yuv420p
[osd/libass] fontconfig: cannot find font 'sans-serif', falling back to 'Arimo'
AV: 00:00:02 / 00:00:18 (15%) A-V:  0.491 Dropped: 109

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:18 / 00:00:18 (99%) A-V:  0.000 Dropped: 511
```

log: https://gist.github.com/520e9bebf840ca23ff69b17c238dad2e

**Comment by lachs0r** [comment]
Looks like a VAAPI problem.

**Comment by outsinre** [comment]
@lachs0r Thanks. I have updated the VAAPI library and the dots are gone.
