### ISSUE TITLE
DLNA question

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#3522]
I have known that mpv won't support for DLNA playback, but does anybody knows if there is any app which can browse the files from DLNA server and let mpv player to play it?

**Comment by wiiaboo** [comment]
https://en.wikipedia.org/wiki/List_of_UPnP_AV_media_servers_and_clients#UPnP_AV_clients

**Comment by laichiaheng** [comment]
@wiiaboo djmount seems to be a good option, thanks!

**Comment by laichiaheng** [comment]
@wiiaboo Oh! No! djmount seems to be outdated, the bugs will never be fixed.
 Most of them are DLNA server, is there any good DLNA client without video player such as KODI or Plex

**Comment by wiiaboo** [comment]
https://github.com/chilicuil/learn/blob/master/sh/tools/simple-dlna-browser
Try this.

**Comment by chachmu** [comment]
I realize this is pretty late but if anybody is still wanting to access DLNA servers using mpv I just released a plugin that lets you browse and playback content from local DLNA servers https://github.com/chachmu/mpvDLNA
