### ISSUE TITLE
mpv tv:// crashes on ubuntu xenial

### ISSUE THREAD

**Issue by mbNavy** [mpv-player/mpv#3523]
### mpv version and platform

mpv git-343f5ca linux ubuntu LTS 16.04.01 xenial, using supported cx23885 based video capture card(MPX-885).

using video card driver that comes as part of v4l2 module...

### Reproduction steps
run:
    mpv tv://

### Expected behavior
see window with video displayed...
### Actual behavior
mpv immediately crashes with a segv fault
### Log files
[mpvCrash.txt](https://github.com/mpv-player/mpv/files/470759/mpvCrash.txt)

**Comment by wm4** [comment]
Could you make a new backtrace without debug infos stripped? (It's not stripped by default, so it must be something you've been doing.) Also, a valgrind log might be helpful too.

**Comment by mbNavy** [comment]
i was hoping there would be symbol information when i ran gdb, so as to give me a hint at what is happening...

i downloaded the deb package from the ppa... ran dpkg -i to install it and its dependencies... if i should do this in a different way, let me know. as far as i know, i didn't do anything that would strip it.

is there some other way for me to get a version to try that has symbols? try an older version maybe?

this system is not on the internet so doing anything is painful.

**Comment by lachs0r** [comment]
I can check with my ancient CX25878 (Fusion 878A) card later if necessary, but last time I used it (a year ago), it was working fine with mpv.

**Comment by mc4man** [comment]
I would suggest build locally or use repo version as a ddeb package is created there. Not too sure that (ddeb) can happen in a ppa env.

**Comment by mbNavy** [comment]
sorry i don't have resources to help track this down further. i think it should be closed.
