### ISSUE TITLE
Interpolation ineffective in wayland backend

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#3524]
### mpv version and platform

intel graphics, mpv 0.20.0
### Reproduction steps

using the samples from here: https://github.com/haasn/interpolation-samples
and the command
`mpv --no-config --vo=opengl:interpolation:tscale=linear:backend=wayland --video-sync=display-resample native.mkv --log-file=output.txt`
### Expected behavior

The video is interpolated much like in x11
### Actual behavior

Everything is choppy
### Log files

http://sprunge.us/bXPE

**Comment by wm4** [comment]
Does it work with `--display-fps=60`?

**Comment by occivink** [comment]
Not really, the playback is even choppier. However, through stats.lua I can see that the estimated `display-fps` is in the range 60-100 depending on the video.
My monitor has a 60hz refresh rate.

**Comment by occivink** [comment]
Not really, the playback is even choppier. However, through stats.lua I can see that the estimated `display-fps` is in the range 60-100 depending on the video.
My monitor has a 60hz refresh rate.

edit: this only applies to wayland, in drm-egl it seems like specifying the display-fps fixes the issue.

**Comment by wm4** [comment]
While I'm not sure about the display fps reporting, the vsync behavior should have been fixed in mpv's wayland code before 0.20.0 already. CC @atomnuker.

**Comment by occivink** [comment]
What about automatic display-fps detection in drm-egl, is that not possible?

**Comment by wm4** [comment]
It's probably very possible. CC @rr-

**Comment by rr-** [comment]
@wm4 let's say I've obtained FPS for the monitor/card (not sure how to do that yet); what would be the best place to notify mpv to update its `display-fps`?

**Comment by wm4** [comment]
You need to implement VOCTRL_GET_DISPLAY_FPS and return it there.

**Comment by rr-** [comment]
Thanks

**Comment by atomnuker** [comment]
Damn it, waylandgl_swap_buffers() doesn't block and does nothing which makes sense.
vo_wayland_wait_events() seems to be thrown in for good measure with an until argument of 0 which doesn't make it block at all, and vo_wayland_request_frame() doesn't seem to wait for a callback.
I'll have time to look for a way to fix it tomorrow.

**Comment by RealJohnGalt** [comment]
Are you sure that your refresh rate is 60.0hz and not something like 59.951hz? weston-info might report the rounded value depending on the compositor you're using and if you're on an older weston (so use xrandr in X and not wayland to get correct refresh). NOTE: gnome wayland 3.22 just regressed for this, kde plasma should still report the correct value on recent weston.

My monitor's 59.951, so needed to set display-fps=59.951 in mpv.conf which fixes the stutter on older weston or new gnome.

**Comment by occivink** [comment]
My monitor's refresh rate is indeed 59.95hz (as reported by xrandr), but using that number for display-fps doesn't change anything in wayland. I tried in weston and sway and both compositors are affected.

**Comment by RealJohnGalt** [comment]
I never noticed before, but @occivink is right that interpolation doesn't work correctly on wayland even with the above commit (though that does fix the stutter without display-fps in certain situations).

I recommend testing by setting opengl-backend=x11 while in a xwayland capable wayland compositor to notice the difference.

**Comment by rr-** [comment]
>even with above commit

It was for DRM and not Wayland though

**Comment by kevmitch** [comment]
This is fixed in a743fef837bcab206b1e576db7e7a64b02890449. That change is controversial, but as is, it fixes this bug.
