### ISSUE TITLE
Keep-open feature request

### ISSUE THREAD

**Issue by dragons4life** [mpv-player/mpv#3525]
Anyway you guys can implement a keep-open that plays the next video whenever you drop it on the player, even if you've paused playback?

**Comment by Cpuroast** [comment]
Huh?

You mean, you open file 1, pause it, then drop file 2, and it resumes playback instead of staying paused?

**Comment by Cpuroast** [comment]
If that's the case, then it already exists:

https://mpv.io/manual/stable/#options-reset-on-next-file

so in your case you'd want:

--reset-on-next-file=pause Reset pause mode when switching to the next file.

Please keep in mind "https://mpv.io/manual" for future reference :)

**Comment by dragons4life** [comment]
Yeah, that seemed to do it, thanks.
