### ISSUE TITLE
mpv can't play web-video on http://www.bilibili.com/ ubuntu16.04

### ISSUE THREAD

**Issue by p1020119** [mpv-player/mpv#3526]
use  the newest  version, and i am typing on the terminal 

~$ mpv http://www.bilibili.com/video/av6260204/
Playing: http://www.bilibili.com/video/av6260204/
[ytdl_hook] Got empty playlist, nothing to play. 
Failed to recognize file format.

is it  a bug ? and  how can i fix it

**Comment by haasn** [comment]
Works for me. Try updating youtube-dl

**Comment by p1020119** [comment]
there is the log 

~$ mpv -v
[cplayer] Command line options: '-v'
[cplayer] mpv git-343f5ca (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Mon Sep 12 15:19:57 UTC 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.29.100
[cplayer]    libavcodec      57.55.101
[cplayer]    libavformat     57.48.103
[cplayer]    libswscale      4.1.100
[cplayer]    libavfilter     6.61.100
[cplayer]    libswresample   2.1.100
[cplayer] ffmpeg version: N-81635-gbc7066f
[cplayer] 
[cplayer] Configuration: ./waf configure --enable-pdf-build --prefix=/usr --confdir=/etc/mpv
[cplayer] List of enabled features: alsa any-gl asm atomics audio-input av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-has-codecpar avcodec-new-codec-api avcodec-profile-name avframe-metadata avframe-skip-samples avutil-has-hwcontext avutil-hdr avutil-mastering-metadata build-date c11-tls cdda cplayer debug-build dlopen drm dvbin dvdnav dvdread egl-drm egl-helpers egl-x11 encoding fchmod gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob gnuc iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libguess libm librt libsmbclient libswresample libv4l2 linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads pulse resampler rubberband shm sse4-intrinsics standard-gl stdatomic subprocess termios tv tv-v4l2 uchardet vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-hwaccel vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h wayland x11 xext xinerama xrandr xss xv zlib
[global] config path: '' -> '/home/newone/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/home/newone/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/newone/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/home/newone/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/newone/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/etc/mpv/config'
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] mpv git-343f5ca (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Mon Sep 12 15:19:57 UTC 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.29.100
[cplayer]    libavcodec      57.55.101
[cplayer]    libavformat     57.48.103
[cplayer]    libswscale      4.1.100
[cplayer]    libavfilter     6.61.100
[cplayer]    libswresample   2.1.100
[cplayer] ffmpeg version: N-81635-gbc7066f
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<pat>         print options which match the given shell pattern
[cplayer]

**Comment by haasn** [comment]
The log is useless if you aren't actually playing the file. But try `youtube-dl --version`.

**Comment by p1020119** [comment]
youtube-dl just a down software, and i just wanna paly the web-video,no save the video

**Comment by lamarpavel** [comment]
mpv is using youtube-dl to receive the stream.

**Comment by p1020119** [comment]
and there  is something change in mpv , and it cant loading the video can u give me the comfige?

**Comment by mc4man** [comment]
You need to not use the package version of youtube-dl, it's too old. Get rid of it & see here, self explanatory - 
http://rg3.github.io/youtube-dl/download.html
Then you will be ok as long as you keep it updated, at least monthly if not more often
