### ISSUE TITLE
Default to ao-volume on Windows?

### ISSUE THREAD

**Issue by TheRyuu** [mpv-player/mpv#3529]
WASAPI is a constant across all supported Windows versions so the behavior will be consistent.  It's also consistent with how other Windows applications handle volume control.  It has the added benefit of remembering the set volume between mpv instances.

This would effectively change how volume control on Windows worked prior to defaulting to softvol (except using keybindings this time).  IMO it makes more sense to use the ao-volume control at least on Windows where there's consistent behavior (where you also know you'll have application specific volume control).

It was discussed at the time of the softvol change that changing how the default keybindings work could be an option.  I don't know if it could be done on other systems but it seems to make sense to use ao-volume on Windows.

**Comment by wm4** [comment]
My main problem is that mpv would have two disconnected values for the system volume: one stored in the options/properties (at times when no audio output is active), and one in the system, that can change asynchronously. Unless we always keep the mixer open (and listen to its notifications), there's no reasonable way to synchronize them. Here's a branch that tries to deal with an alternative approach to some extend: https://github.com/mpv-player/mpv/commit/7621a028bf555c9ed0430501bc6eac2fa204114c

Another reason to dislike ao-volume is that it uses a different (and unknown) scale than internal volume control.

**Comment by wm4** [comment]
PS: the problem is roughly the same as with PulseAudio.

**Comment by TheRyuu** [comment]
> Here's a branch that tries to deal with an alternative approach to some extend: 7621a02

Makes sense.

> Another reason to dislike ao-volume is that it uses a different (and unknown) scale than internal volume control.

Is this really an issue though?  Why should we care how the system scales if it's consistent with all other applications on that system?

**Comment by kevmitch** [comment]
We've pretty much settled on softvol for everyone. The option to use the system mixer is still there for those who care.
