### ISSUE TITLE
Looking to hire someone for new feature additions....

### ISSUE THREAD

**Issue by smarrocco** [mpv-player/mpv#3532]
I am looking to hire someone to write and contribute a few features/enhancements to the mpv project code. An example of this would be the ability to read smpte timecode and adding that support into the api. If you are interested please let me know that I can communicate to you the requests in more detail.

If there is a more appropriate place for posting this request, please let me know.

**Comment by wm4** [comment]
You should probably update the issue title to something more eye-catching.

**Comment by smarrocco** [comment]
Thanks for the suggestion.

**Comment by lachs0r** [comment]
This isn’t more eye-catching at all. GitHub is not a platform for job offers. If you want people to care, try creating separate issues for the specific features you want implemented (as detailed as possible), and offer a bounty for each of them.
