### ISSUE TITLE
OSC delayed/unresponsive with latest builds

### ISSUE THREAD

**Issue by wrielxc** [mpv-player/mpv#3535]
### mpv version and platform

mpv git-cf5c3fc; Windows 7 64-bit; GTX 1060
Same commit; Windows 7 64-bit, Intel HD 3000 (integrated graphics)

### Reproduction steps

Play any video and mess with the OSC (turn on stats.lua, adjust volume with keybinds)

### Expected behavior

The OSC updates relatively quickly.

### Actual behavior

With git-cf5c3fc, the OSC redraws much less frequently and lags behind keyboard input substantially.
This was not a problem with git-0435120 or earlier (not sure which commit had the regression).

### Log files

git-cf5c3fc: https://gist.github.com/wrielxc/9d7c7ac7c3109f8e846e324c0b9032a7
git-0435120: https://gist.github.com/wrielxc/69ddbc9be8678d115fe3711e1b638efd
mpv.conf: https://gist.github.com/anonymous/c05da8d85680bbc2ce8983daeb547a51

### Sample files

git-cf5c3fc: https://0x0.st/Swk.mp4
git-0435120: https://0x0.st/Swn.mp4
Original file: https://0x0.st/Sw5.mp4

**Comment by wm4** [comment]
Not sure if I can see on those videos what's wrong...

**Comment by quilloss** [comment]
I think it might be due to 9c9cf125ad71aeff7fe6979b7b5d1f44f2d1a6ac. This only happens with the option `--blend-subtitle=yes`. Not sure if related but c47ae06ed80e9493d92924282b417536669ec3d0 throws a runtime exception in `misc/dispatch.c` when I toggle the stats display.

**Comment by wm4** [comment]
>I think it might be due to 9c9cf12. This only happens with the option --blend-subtitle=yes. 

Huh? Can't reproduce anyway.

>Not sure if related but c47ae06 throws a runtime exception in misc/dispatch.c when I toggle the stats display.

Yeah, already fixed locally.

**Comment by wm4** [comment]
Actually I think I can reproduce, but with OSD, not the OSC.
