### ISSUE TITLE
6 channels audio + "lavfi ladspa" + lavcac3enc guess produces stereo output

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#3543]
### mpv version and platform

0.20.0
### Reproduction steps

Have a spdif ac3 decoder
play a stream that way:

```
 mpv --ao=alsa:device=spdif --af-add=scaletempo=speed=tempo,lavfi="[ladspa=file=/usr/lib/ladspa/fast_lookahead_limiter_1913.so:p=fastLookaheadLimiter:c='c0=15|c1=0|c2=2',aformat=channel_layouts=6c]",lavcac3enc=tospdif=yes:bitrate=640:minch=3  documenti/videotest/AC3Test.avi  --vo=null --msg-level=af=debug
```
### Expected behavior

Have a dolby encoded stream 
### Actual behavior

Just a stereo pcm stream is produced
### Log files

http://pastebin.com/nGQPG6Zy
### Sample files

Any multichannel audio.

Note that forcing "aformat=channel_layouts=6c" : 

```
mpv --ao=alsa:device=spdif --af-add=scaletempo=speed=tempo,lavfi="[ladspa=file=/usr/lib/ladspa/fast_lookahead_limiter_1913.so:p=fastLookaheadLimiter:c='c0=15|c1=0|c2=2',aformat=channel_layouts=6c]",lavcac3enc=tospdif=yes:bitrate=640:minch=3  documenti/videotest/AC3Test.avi  --vo=null --msg-level=af=debug
```

will make it work:
http://pastebin.com/4Cyck6FD

Also, other wrapped filters (via lavfi) doesn't need that.

I'm not sure who to blame for that, mpv,ffmpeg,ladspa,fastlookahead limiter?

**Comment by wm4** [comment]
Seems more like a problem with lavfi's ladpsa filter than anything else. CC @richardpl

**Comment by kokoko3k** [comment]
Ok, i just noticed that when adding  channel_layouts=6c, and so  the output stream is dolby encoded, it is downmixed to 2 channels first, then upmixed to 6, then encoded.
So there is no real gain.
I'll try to experiment more.

**Comment by richardpl** [comment]
fast lookahead limiter supports only 2 input to 2 output channels:

`ffmpeg -i AC3Test.avi -af "ladspa=/usr/lib/ladspa/fast_lookahead_limiter_1913.so" -f null -`
`[Parsed_ladspa_0 @ 0x247a300] The '/usr/lib/ladspa/fast_lookahead_limiter_1913.so' library contains the following plugins:`
`[Parsed_ladspa_0 @ 0x247a300] I = Input Channels`
`[Parsed_ladspa_0 @ 0x247a300] O = Output Channels`
`[Parsed_ladspa_0 @ 0x247a300] I:O Plugin                    Description`
`[Parsed_ladspa_0 @ 0x247a300] `
`[Parsed_ladspa_0 @ 0x247a300] 2:2 fastLookaheadLimiter      Fast Lookahead limiter`

**Comment by richardpl** [comment]
You could try asc=1 for alimiter filter

**Comment by kokoko3k** [comment]
FastLookahead limiter used to work with 6 channels before "native" af ladspa was removed by mpv; i can't say why, nor "how", not a big deal as long as there are alternatives.
Thanks for the hint on asc, it does work, but it is a bit weird.
First, not having right now a 5.1 spdif decoder to test, i needed to simulate it; i've done it and reproduced the uissue by the following command; warning, it is extreme:
```
mpv documenti/Video/AC3Test.avi -af lavfi=[alimiter=64:1:1:5:1000,aformat=channel_layouts=6c] --msg-level=af=debug
```
As expected, the sound is full of statics on center and rear channels.

-BUT!-
```
mpv documenti/Video/AC3Test.avi -af lavfi=[alimiter=64:1:1:5:1000:asc=1:asc_level=0,aformat=channel_layouts=6c] --msg-level=af=debug
```

Will work (THANKS), but it is weird that just activating asc (asc=1), and then disabling his effects (asc_level=0) does the trick (!?)

**Comment by lachs0r** [comment]
Well, the issue here seems to have been that lavfi does not automatically use multiple LADSPA filter instances if there are more input channels than available filter inputs, and you would have to set up the graph explicitly. So it’s probably better to use lavfi’s built-in filters if possible.

The *real* solution, of course, is to upgrade from that stinking S/PDIF setup.
