### ISSUE TITLE
how to pan video after zooming in

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3546]
mpv git-b1893d2 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  8 16:37:08 UTC 2015
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.7

i have asked the question about zoom in https://github.com/mpv-player/mpv/issues/3542

how to pan the video when i zoom in

**Comment by wm4** [comment]
I use
```
ctrl+left add video-pan-x 0.1
ctrl+right add video-pan-x -0.1
ctrl+up add video-pan-y 0.1
ctrl+down add video-pan-y -0.1
```
