### ISSUE TITLE
Implement adaptive track switching for HLS/DASH

### ISSUE THREAD

**Issue by baco** [mpv-player/mpv#3548]
Mpv Player could be aware of all the video and audio tracks that come provided via Youtube-dl (like when using `-F` to obtain all formats) in order to be able to cycle through them using `_` or `#` respectively. Honoring `--ytdl-format=` value, of course, but being able to switch video/audio live.

**Comment by wiiaboo** [comment]
Can be easily done with audio tracks, but for the video tracks it needs an additional `video-add` command implemented by mpv.

**Comment by wm4** [comment]
Let me know if you're actually going to use it - then I can add it.

**Comment by baco** [comment]
Of course I will use it! My laptop not always connects to the fastest networks and I need to use lighter video sizes in those cases. Using the appropriate Mpv shortcut is easier than, quitting Mpv, run ``youtube-dl -F`` (because not all the providers use the same format codes) and finally await a new HTTP re-connection with the required size.

Even further, I can not control the command line of Mpv when using it with addons such as: https://addons.mozilla.org/en-US/firefox/addon/watch-with-mpv/

**Comment by wiiaboo** [comment]
Why not setup a different profile for lower qualities and running mpv with it when using shittier net?
```
ytdl-format=(bestvideo[vcodec=vp9]+bestaudio[acodec=opus]/bestvideo+bestaudio/1080p/Source/best)[protocol!=http_dash_segments][tbr<?5000]

[low]
profile-desc=ytdl low format
ytdl-format=(bestvideo[vcodec=vp9]+bestaudio[acodec=opus]/bestvideo+bestaudio/360p/Low/best)[protocol!=http_dash_segments][tbr<?1000]
```

Also, if using firefox, use [Open With]. It allows different arguments:
![image](https://i.fsbn.eu/H1Fi.png)

[Open With]: https://addons.mozilla.org/en-US/firefox/addon/open-with/

**Comment by paulguy** [comment]
If this was exposed somehow, it could be combined with a script to determine poor buffering conditions and switch to lower ones if it gets bad or go to higher ones if it gets better.  Having to try different video formats manually as your connection varies just sounds like a hassle, and could result in having to seek to where you left off if your internet just decided to get bad or more bandwidth is being used elsewhere, then you'd be stuck with poor quality regardless of if your connection got any better.

**Comment by wiiaboo** [comment]
Sounds like you need a browser HTML5 player. There's probably no rate-aware non-browser player that dynamically chooses different streams.

**Comment by wiiaboo** [comment]
Youtube-DL does give mpv a HLS url if you use `--ytdl-format meta`. That will give mpv a m3u8 with various bitrates available and will do what you basically want:
`mpv --ytdl-format meta https://www.twitch.tv/tsm_bjergsen`:
![image](https://i.fsbn.eu/4Ao0.jpg)

**Comment by baybal** [comment]
@wm4 

> Let me know if you're actually going to use it - then I can add it.

Yes, I need it. I was exploring the issue myself, and noticed this bug now.

Wanted to add support by myself, but you are probably ahead of me now?

**Comment by wm4** [comment]
I implemented the track switching idea. This has to be enabled explicitly (see recent commits) and does not do any adaptive (or even smooth) switching. It also breaks stream recording. That's probably as far as I'll go for now.

If anyone wants actually adaptive switching (as in something that computes bitrate and then automatically switches seamlessly without interruption), open a new issue. Pretty unlikely that I'll continue working on this, seems like a waste of time.
