### ISSUE TITLE
How to use javascript / nodejs /electron to send keyboard signal to repalce OSC

### ISSUE THREAD

**Issue by kscorpio** [mpv-player/mpv#3557]
I want to use mpv to cover on a electron app, and use js node js to control mpv pause/ volume ...  .... 

how to release it  to replace OSC (ON SCREEN CONTROLLER) ?

**Comment by kevmitch** [comment]
Give the ```--no-osc``` option to prevent the existing osc from running. Use [JSON IPC](https://mpv.io/manual/master/#json-ipc) or [libmpv](https://github.com/mpv-player/mpv-examples/tree/master/libmpv) to control mpv in response to your own GUI.

**Comment by kscorpio** [comment]
$mpv 111.mp4 --no-osc --input-ipc-server=/tmp/mpvsocket                                                                                                                                        
Error parsing option input-ipc-server (option not found)
Setting command line option '--input-ipc-server=/tmp/mpvsocket' failed.

**Comment by kscorpio** [comment]
─$mpv --version                                                                                                                                                                       1 ↵
mpv 0.13.0-git-a33a44c (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on Mon Dec  7 18:52:35 CST 2015
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: n2.8.3

**Comment by kscorpio** [comment]
it s ok  
use  --input-unix-socket 

i use mpv in orangepi,  version is 0.13 . it this ok?

**Comment by kscorpio** [comment]
Terminal 1
mpv 111.mp4 --no-osc --input-unix-socket=/home/orangepi/mpvsocket

-------------------------------------------------------------------------------------------------------
Terminal 2

$echo '{ "command": ["set_property", "pause", true] }' >/home/orangepi/mpvsocket                                                                                                    ---
zsh: no such device or address: /home/orangepi/mpvsocket

**Comment by 00SteinsGate00** [comment]
Not sure if this is still relevant, but you could use my NodeJs package [Node-MPV](https://github.com/00SteinsGate00/Node-MPV) for that, as it does exactly that.
