### ISSUE TITLE
relocation error

### ISSUE THREAD

**Issue by walidsa3d** [mpv-player/mpv#3561]
**mpv 0.19.0**
**ubuntu 14.04**

After installing mpv from repositories, I keep getting this error every time I try to launch it:

> mpv: relocation error: /usr/lib/x86_64-linux-gnu/librubberband.so.2: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

**Comment by jcowgill** [comment]
`GLIBCXX_3.4.21` is GCC 5, but Ubuntu 14.04 is built against GCC 4.8. My guess is that you have a copy of `librubberband.so.2` built for the wrong Ubuntu version (probably 16.04). I doubt there's an mpv bug here.
