### ISSUE TITLE
how to build mpv in armv7 like orangepi 

### ISSUE THREAD

**Issue by kscorpio** [mpv-player/mpv#3564]
i use mpv embedded in a electron app,  and want to use node js to control mpv instead of OSC
(see #3557 ) 

but now i just have a lubutun mirror  with mpv 0.13 , i test json ipc has many errors #3557 

so i planned to build a newest version , 
  1 how to build mpv in armv7 like orangepi 
  2 can it release hardware-decoding

**Comment by wm4** [comment]
> 1 how to build mpv in armv7 like orangepi 

No idea. Should be the same as all other Linux platforms?

>  2 can it release hardware-decoding

Probably not supported.

**Comment by kscorpio** [comment]
but there is a lubuntu image  which has release mpv  hardware-decoding

**Comment by kscorpio** [comment]
please re-open this issue, it han not solve anything

**Comment by wm4** [comment]
>but there is a lubuntu image which has release mpv hardware-decoding

Really? How do you know that?

**Comment by wm4** [comment]
Looks like it might work with this, but I can't tell for sure: http://linux-sunxi.org/Cedrus/libvdpau-sunxi

I recommend you do your own googling.
