### ISSUE TITLE
How to change window background picture? [or: Add option to disable OSC idle message]

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3565]
Hi!

When mpv starts like `mpv --idle --force-window=yes`, it shows a background picture with mpv logo and "Drag file here" line. Is it possible to set some other background to be shown there?

**Comment by wm4** [comment]
Not possible.

**Comment by ChrisK2** [comment]
It's not a background picture, those are ASS subtitles that are shown by the OSC. If you want something else (that can be drawn with ASS) be shown there, you have to modify [the OSC script](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L1947-L1968) and load it separately.

**Comment by Argon-** [comment]
You could use this to create the necessary subtitles: https://github.com/lyger/Aegisub_automation_scripts#Image2ASS
Brace for a lot, a lot of text.

**Comment by ChrisK2** [comment]
^ this is absolutely not recommended though.

**Comment by fhlfibh** [comment]
@ChrisK2 what exactly is not recommended?
@Argon- it's not that much about images, actually.
The problem is that if logo and "Drop files to play here" stay still on PDP or OLED screen -- those will catch static/image retention/burn-out very shortly, I'm afraid... Having a dark solid color background would be better in such situations.

**Comment by wm4** [comment]
Clearly, we need an OSC screensaver. Bouncing mpv logo?

**Comment by fhlfibh** [comment]
@wm4 yes, quite well, as for me.
Actually, as I see it, anything seems Ok as long as it moves from time to time, and is not of very high contrast.

**Comment by ChrisK2** [comment]
> @ChrisK2 what exactly is not recommended?

Using the Image2ASS script

Anyway, so an option to disable the idle message would be completely sufficient for you?

**Comment by fhlfibh** [comment]
@ChrisK2 yes, to disable the idle picture completely looks Ok as well.

**Comment by fhlfibh** [comment]
I close this issue because current build 0.24.0 has no background picture in `force-window` mode, that seems quite Ok.
