### ISSUE TITLE
Changing the "PSEUDO GUI" windows size with --geometry messes up aspect ratio.

### ISSUE THREAD

**Issue by dragons4life** [mpv-player/mpv#3566]
### Reproduction steps

geometry=750x421 (16:9 AR)
### Expected behavior

No black bars, aspect ratio to fix itself?
### Sample files

https://i.lithi.io/bArog.webm _(audio warning)_

Now to my understanding of looking trough the manual it seems to me that --geometry is the only way to change the window/pseudo gui

https://mpv.io/manual/master/#options-force-window

Guess this is kinda of a feature request, I've tried using autocrop but it doesn't crop/remove the black bars that the windows size causes.

**Comment by wiiaboo** [comment]
You're looking for --autofit, then. --geometry doesn't respect aspect ratio.

**Comment by dragons4life** [comment]
Thanks

**Comment by dragons4life** [comment]
After trying out autofit, it does in fact work, but it only changes the window size if you open a video with mpv, so if you for example open the mpv window first to drag a video or url from youtube/twitch the window size will not be the one you specified on autofit.

https://i.lithi.io/Kqg8W.webm

**Comment by wiiaboo** [comment]
Then you want both geometry and autofit. How is mpv supposed to know the aspect ratio of something you haven't given it yet?

**Comment by dragons4life** [comment]
No I just want to change the "forwindow" size without messing up the aspect ratio of the files I drag in or open with the open file dialog script.

**Comment by Akemi** [comment]
if this problem still persists, please open a new issue.
