### ISSUE TITLE
Fullscreen --vo=vaapi disables compositor and flickers in kde5

### ISSUE THREAD

**Issue by TiGR** [mpv-player/mpv#3574]
### mpv version and platform

Kubuntu 16.04.1 64 bit, i5 2450M, integrated graphics only used, mpv 0.20

```
$ mpv --version
mpv git-343f5ca (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Mon Sep 12 15:19:57 UTC 2016
ffmpeg library versions:
   libavutil       55.29.100
   libavcodec      57.55.101
   libavformat     57.48.103
   libswscale      4.1.100
   libavfilter     6.61.100
   libswresample   2.1.100
ffmpeg version: N-81635-gbc7066f

$ cat /usr/share/X11/xorg.conf.d/20-intel.conf
Section "Device"
   Identifier  "Intel Graphics"
   Driver      "intel"
   #Option      "AccelMethod"  "sna"
   Option      "TearFree"    "true"
   Option      "Vsync"       "false"
   Option      "DRI"    "3"
EndSection
```

If I run it without TearFree there is very noticeable tearing.

Option "suspend compositor for full screen windows" in Compositor settings is disabled.
### Reproduction steps

```
mpv --fs --hwdec=vaapi --vo=vaapi some.video.file.mp4
```
### Expected behavior

Just play in fullscreen as it used to before upgrade to 16.04.1/mpv 0.20
### Actual behavior
1. Plasma desktop effects get turned off. Like, I have desktop cube effect, and it stops working and it is impossible to turn it back on until any mpv instance is in fullscreen.
2. Video flickers (some previous frames randomly appear for an instance) so bad it is unwatchable.

`--vo=opengl` fixes flickering, but not disabling desktop effects. I had none of these issues on 14.04/kde4
### Log files

http://sprunge.us/JLHR

**Comment by TiGR** [comment]
And once you leave fullscreen both compositor starts working and flickering is gone.

**Comment by wm4** [comment]
You can try `--x11-bypass-compositor=no`. Other than that, vo_vaapi is unsupported.

**Comment by TiGR** [comment]
This option fixes both issues, thanks. Any reason to have it enabled by default?

As regards to vaapi - is there any particular reason to not support vaapi? It provides really good scaling quality for free (when [compared to opengl hq scaling, for instance](https://github.com/mpv-player/mpv/issues/2109#issuecomment-118848932)).

**Comment by mc4man** [comment]
You cold read thru these 'issues', maybe they'll make sense, maybe not. (does yes=yes or yes=no in regards to unredirect, ect.
https://github.com/mpv-player/mpv/issues/2582
https://github.com/mpv-player/mpv/issues/2502
At least here it appears that by default 
in window mode - x11-bypass-compositor=no ??
i.e. _NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 0
in fullscreen - x11-bypass-compositor=yes ??
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 1

**Comment by wm4** [comment]
> Any reason to have it enabled by default?

Yes - it actually helps with some things. I'd consider this either a KDE compositor, or Intel driver bug then.
