### ISSUE TITLE
Error parsing option load-scripts (option could not be parsed)

### ISSUE THREAD

**Issue by NewUserLinux** [mpv-player/mpv#3583]
Yesterday I updated mpv in lubuntu 14.04.05 and now present this problem for encoding:

"Error parsing option load-scripts (option could not be parsed)"

It's a bug?

**Comment by mc4man** [comment]
Could be related to the newish  etc/builtin.conf file, error not seen before it was included.
[encoding]
.....
load-scripts=no
Doesn't seem to have any negative effect here

**Comment by mc4man** [comment]
well actually don't see this  in git-cf5c3fc  but do in git-9959622 > today's master,  all of which use some version of builtin.conf

**Comment by wm4** [comment]
>It's a bug? 

How should I know? You completely ignored the issue template. I can't guess. Closing as invalid.
