### ISSUE TITLE
mp.get_property - how to get the file extension

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3584]
I want to the get the extension of file being played. how to get it

**Comment by wm4** [comment]
Get the `path` property, then extract the extension yourself.

**Comment by wiiaboo** [comment]
Here's an example in lua: https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua#L33

**Comment by wm4** [comment]
Though it's probably better to get the basename first (remove everything before the last `/`).
