### ISSUE TITLE
os.execute takes quite few seconds to execute ffmpeg

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3585]
I am trying to execute ffmpeg command inside os.execute. But it takes quite a few seconds and till that time i cant move ahead on mpv. so how to push that to background

**Comment by wiiaboo** [comment]
https://mpv.io/manual/master/#lua-scripting-utils-subprocess(t)

**Comment by sant527** [comment]
utils.subprocess_detached("ffmpeg ...") Will that work.
