### ISSUE TITLE
Better handle subtitle files with several texts per timestamps

### ISSUE THREAD

**Issue by Jehan** [mpv-player/mpv#3587]
### mpv version and platform

I am using git mpv (git-08432fc).
### Reproduction steps

It is very common to find non-English subtitle files with both English and text in another language. Typically the subtitle was created by someone who translated it from the English subtitle. It seems that the "usage" here is to keep the English text at the end of the file. So a SMI file for instance would have:

> &lt;SYNC Start=5905>Some text in Korean (for instance)
> […]
> &lt;SYNC Start=5905>The same text but in English.

Unfortunately it seems that mpv would display the last seen text for a given timestamp, which goes against the usage I seem to have encountered until now. That forces me to edit each and every subtitle I use to remove the English part. Very boring.

Could mpv behavior be revisited? Basically the first text for a timestamp should have precedence. Well at least this is my experience, mostly with Korean subtitles.

**Comment by wm4** [comment]
That's really completely up to ffmpeg. Do you have a sample file?

**Comment by Jehan** [comment]
Attached a home-made sample file (SMI subtitle, with .txt extension to be able to upload on github) of the kind of subtitles I often find on the web:
[sample-several-langs.txt](https://github.com/mpv-player/mpv/files/495680/sample-several-langs.txt)
I also sent you an email.

As you can see inside, there is some Korean and some English on the same file, and the Korean is first. As you can test, mpv would display the English (the later overrides, I guess) when 2 subtitles are on the same timestamp.

Now I have no idea if only the Korean community does this like that but that's very common to find these kind of files. I assume that maybe common video players on Windows would therefore process these subtitles differently and would not override with last seen text for a timestamp (I can't test though).

**Comment by wm4** [comment]
Yeah, looks like FFmpeg could export these as separate subtitle streams. You'll need to find something in FFmpeg who wants to implement this, or do it yourself.

I think you can publicly provide a single such "dual language" SMI subtitle to make implementing this easier, without having to fear consequences.

>Now I have no idea if only the Korean community does this like that but that's very common to find these kind of files.

The only SMI files I've ever seen were Korean.

**Comment by Jehan** [comment]
Oh I didn't realize that this is not even about usage, but having several language in a single file is actually even in the format spec.
Here is the feature request (which has already been existing for 3 years) on ffmpeg: https://trac.ffmpeg.org/ticket/3118

**Comment by wm4** [comment]
Yes, apparently I encouraged that person to open a FFmpeg issue.

**Comment by Jehan** [comment]
Ok I have submitted a patch, which is a first step to better support of SAMI. I see you have commit rights on ffmpeg too, so I hope I can get some reviewing soon. ;-)
