### ISSUE TITLE
Unable to send video to separate X screen :0.1

### ISSUE THREAD

**Issue by airbete** [mpv-player/mpv#3592]
### mpv version and platform

mpv-0.20.0-2.fc24.x86_64
Fedora 24

### Reproduction steps

mpv --screen N video_file.mpg

### Expected behavior

Video output is sent to an external monitor

### Actual behavior

Video is always sent to primary monitor, no matter the value of N

### Log files

http://sprunge.us/VIKD

### Notes

In my setup, I have to seperate (no Xinerama) X screens: :0.0 and :0.1. I am trying to have the GUI on :0.0 and the video on :0.1. With mplayer it is as easy as issuing the following command from a command line window on :0.0
mplayer -display :0.1 video_file.mpg
No matter the value on N in the mpv option --screen N, the video is always sent to screen :0.0. I have tried playing with --geometry, but I had no succes either.

**Comment by wm4** [comment]
`DISPLAY=:0.1 mpv ...`

**Comment by airbete** [comment]
Right! The problem is I want to use mpv from within smplayer and have the smaplyer gui on :0.0. With mplayer, I just have to add the extra option "-display :0.1" and it works. With mpv I haven't find a way yet.

**Comment by wm4** [comment]
Not our problem.

**Comment by qmega** [comment]
You could use a wrapper script that exports `DISPLAY` and execs mpv, and have smpayer call that instead of mpv.

**Comment by airbete** [comment]
Thanks for the suggestion. I've already tried this approach but I didn't find a way to make it work, probably because I don't fully grasp the interaction between smplayer and mpv. If I copy and paste the command smplayer is issuing on a command line, my script does work.

**Comment by qmega** [comment]
Then maybe smplayer isn't going through a shell and your command expects it to? Are you just putting `DISPLAY=...` at the front of your command? If you are, smplayer might be trying to find a command called `DISPLAY=...`, and understandably failing. Have you tried making an actual script, marking it executable, and putting its full path into smplayer? Or, you could use as your command `env DISPLAY=... mpv ...` so you still have an actual command without relying on the shell.

I've never used smplayer, so I don't know how it runs processes, but that's the only thing I think of given what you've said.
