### ISSUE TITLE
mpv - nextfile.lua - when shifting to next the window position changes to top bottom randomly

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3599]
I am using nextfile.lua.

I open a file in a directory with many mp4 files. When i do SHift+Up, it loads the next video but it shift the window randomly to bottom or top and sideways etc.

I want to view all the videos with a fixed height of 600 and autoift the width as per aspect ratio and all the videos to be placed in the center of the desktop when i change from one video to another

**Comment by lachs0r** [comment]
`--geometry=x600+50%+50%`
