### ISSUE TITLE
SHOUTcast streams don't show current artist/title (ICY metadata)

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#36]
This is because libavformat doesn't support this functionality. MPlayer/mplayer2 can show the metadata, because they still use the old HTTP implementation, while mpv switched to ffmpeg's (i.e. libavformat). The old implementation is still available in mpv as mp_http://...

ffmpeg bug report: https://ffmpeg.org/trac/ffmpeg/ticket/716

**Comment by wm4** [comment]
>I consider this Won't Fix on Libav.

Actually Libav has this too now. (Not sure which version, maybe the latest release.)
