### ISSUE TITLE
Video filters are forcing SW decoding on RPi

### ISSUE THREAD

**Issue by Maigre** [mpv-player/mpv#3604]
Hi,
i may have missed something but i can't use some particular video filters on RPi.
The HW decoding is working fine with MMAL: 

```
Using hardware decoding (rpi).
VO: [opengl] 1920x1080 mmal
[vo/opengl] Using HW-overlay mode. No GL filtering is performed on the video!
```

but when i apply --vf=flip or --vf=mirror
i obtain:

```
Using hardware decoding (rpi).
Using conversion filter.
Image formats incompatible or invalid.
Video filter chain:
  [in] 1920x1080 mmal bt.709/limited CL=mpeg2/4/h264
  [scale] ??? [a]   <---
  [flip] "flip.00" ???
  [out] ???
Falling back to software decoding.
[ffmpeg/video] h264: co located POCs unavailable
```

The video is played but is of course slow since it falled back to software decoding.

Any idea ? Tell me if you need more info ..
Thanks !

**Comment by wm4** [comment]
That always happens with hardware decoders. Unfortunately you can't apply those transformations with hardware decoding (the hardware probably would, but we provide no access to that). ``--video-rotate`` should work at least.

I've added a ``--hwdec=rpi-copy`` mode, which allows easily using hardware decoding with software-readback for filtering. Will be slower, though.
