### ISSUE TITLE
San Francisco font no longer recognized after upgrade to macOS Sierra

### ISSUE THREAD

**Issue by hghtmes** [mpv-player/mpv#3605]
### mpv version and platform
mpv 0.20.0  on macOS Sierra

As described, I was using San Francisco as my OSD and subtitle font for the past year but since my upgrade to macOS Sierra last week both fonts have defaulted to something different. I've tried using other fonts like Helvetica Neue and they work fine, this just seems specific to San Francisco 

### Log files
http://sprunge.us/CMPP

**Comment by rcombs** [comment]
You'll want to use "SF UI Display", not "SF UI Display Regular".

**Comment by hghtmes** [comment]
Thanks, that solved it
