### ISSUE TITLE
Feature Request: 10bit display/rendering on Mac

### ISSUE THREAD

**Issue by csdesigns** [mpv-player/mpv#3607]
mpv git-52fea2f 
Mac OS X 10.11.6
iMac 5K Late 2015 4GHz 32GB RAM AMD M395X

It would be great if mpv could support 10bit rendering for 10bit sources. While mpv has no issues decoding 10bit sources, the actual rendering is done in 8bit. Apple added support for 10bit rendering in a few 1st-party apps (Preview, FCPX, etc) with El Capitan. However, the only 'player' on the mac which I have found that supports true 10bit rendering is ffplay. Unfortunately, ffplay's HEVC decoder is very sub-optimal in terms of performance, especially compared to the excellent performance of mpv. 

[ffplay 3.1.3 HEVC Main10 decode screenshot](http://imgur.com/JLiGpIv)
[mpv git-52fea2f HEVC Main10 decode screenshot](http://imgur.com/BAKZS7x)
[HEVC Main10 source](https://www.dropbox.com/s/26olt9xqn3a9f5l/ColorRamps-grey-10bit.265?dl=0)

Best Regards,
CS

**Comment by wm4** [comment]
- ffplay is _always_ restricted to 8 bit rendering, and it's not possible to get more
- ffplay and mpv use exactly the same decoder

**Comment by haasn** [comment]
- mpv will use 10-bit surfaces and output where supported by OpenGL automatically (works on my end)
- mpv can deband artifacts like these either way

**Comment by csdesigns** [comment]
> • ffplay and mpv use exactly the same decoder

This was my understanding as well, however the rendering of the same source looks _completely_ different between mpv and ffplay – see the images I linked above as an example

> ffplay is _always_ restricted to 8 bit rendering, and it's not possible to get more

If ffplay is only rendering the 10bit HEVC source in 8bit (i.e. dithered), it is certainly doing a much better job of it by default than I have found from **any** other player. I think the frame caps and source I linked to above prove that. Even on my Late 2013 MacBook Pro 15", which does not support 10bit color on its internal display (unlike the Late 2015 iMac 5K), the rendering of the HEVC 10bit source is far superior to mpv's output (though it is not as good as on the iMac's display as I can see some slight banding on the MacBook's 8bit color display)

> mpv can deband+dither artifacts like these either way

Could you please provide example cli usage? I have looked through the mpv options but haven't found anything regarding this (at least not anything that was easily searchable with the keywords 'deband' or 'dither'). I very well could just be missing it in the documentation however

>mpv will use 10-bit surfaces and output where supported by OpenGL automatically (works on my end)

Are you on mac, Windows, or Linux? Is the output you see on your end from mpv with the sample source .265 stream different than the frame grabs I provided in the links above?

Thank you very much both for your assistance and looking into this.

**Comment by Argon-** [comment]
Huh, searching the manual for "deband" and "dither" should yield the options with exactly these names. In your case just use --vo=opengl --profile=opengl-hq as this will activate both.

**Comment by fhlfibh** [comment]
@haasn 
> mpv will use 10-bit surfaces and output where supported by OpenGL automatically

BTW, can it use and output 12-bit, when a monitor can accept such?

**Comment by wm4** [comment]
Whether mpv tries to output 10 bit to the screen could be determined from the mpv log. (But yeah, let's be a "clever" user and ignore the github issue template!)

**Comment by csdesigns** [comment]
> But yeah, let's be a "clever" user and ignore the github issue template!

nothing "clever" in my attempt to get some support; if I thought I was clever enough to figure this out myself, I wouldn't have come here asking for help or a feature request... anyway, sorry for not posting this sooner, but here are the [logs](https://www.dropbox.com/s/uvy2qjxrseaq968/logs.zip?dl=0)

**Comment by csdesigns** [comment]
> Huh, searching the manual for "deband" and "dither" will yield the options with exactly these names...
https://mpv.io/manual/master/#options-deband
https://mpv.io/manual/master/#options-dither-depth
In your case just use --vo=opengl --profile=opengl-hq as this will activate both.

Yep, my fault. I was only searching the inline mpv options available in the --list-options output. **Thanks for the suggestion!** I will test this on Monday when I can get back on the iMac.

**Comment by wm4** [comment]
Reports mpvlog-Main10-iMac.txt says:
```
Reported display depth: R=0, G=0, B=0
```
...which means it'll default to dithering to 8 bits, AFAIK.

And mpvlog-Main10-MBP.txt says:
```
Reported display depth: R=8, G=8, B=8
```
Even though they're both on OSX, I guess the drivers are pretty different.

**Comment by wm4** [comment]
I also tested your sample, and I think ffplay is smoother than plain mpv because it uses libswscale to convert to 8 bit, which dithers by default. (Maybe we should enable dither by default if the source depth is higher than the target depth.)

**Comment by Argon-** [comment]
Random info: my hackintosh using AMD and external displays (<= 8bit) and 13" MBP with Intel iGPU both report `Reported display depth: R=0, G=0, B=0` as well.

> I was only searching the inline mpv options available in the --list-options output

    → mpv --list-options | egrep 'deband|dither'
     --deband                         Flag (default: no)
     --deband-grain                   Float (0 to 4096) (default: 48.000000)
     --deband-iterations              Integer (1 to 16) (default: 1)
     --deband-range                   Float (1 to 64) (default: 16.000000)
     --deband-threshold               Float (0 to 4096) (default: 64.000000)
     --dither                         Choices: fruit ordered no (default: fruit)
     --dither-depth                   Choices: no auto (or an integer) (-1 to 16) (default: no)
     --dither-size-fruit              Integer (2 to 8) (default: 6)
     --temporal-dither                Flag (default: no)
     --temporal-dither-period         Integer (1 to 128) (default: 1)

**Comment by csdesigns** [comment]
> I was only searching the inline mpv options available in the --list-options output

On my build (built using Homebrew), mpv --list-options jumps straight:

```
 --cursor-autohide-fs-only        Flag (default: no)
 --deinterlace 
```

But I should have used man mpv – my bad

**Comment by csdesigns** [comment]
> In your case just use --vo=opengl --profile=opengl-hq as this will activate both.

I have tried this on my MBP, but the displayed result isn't much (if any different). I would hope to be able to achieve at least similar quality to ffplay.

> I also tested your sample, and I think ffplay is smoother than plain mpv because it uses libswscale to convert to 8 bit, which dithers by default.

I have tried a bunch of the additional deband/dithering options but not seeing much difference, if at all, in rendering quality (extreme cli example following):

`mpv /Downloads/ColorRamps-grey-10bit.265 --vo=opengl profile=opengl-hq deband deband-grain=4096 deband-range=64 deband-iterations=16 deband-threshold=4096 dither-depth=8 dither-size-fruit=8 temporal-dither --log-file mpv-Main10log-MBP-OpenGL.txt`

Log file for this [here](https://www.dropbox.com/s/bkpgtw3wxy9ti56/mpv-Main10log-MBP-OpenGL.txt?dl=0)

**Comment by Argon-** [comment]
Um, you forgot `--` for most options. Also, your mpv might be too old for the `--profile=opengl-hq` option. The same is possible in your version but it used a different configuration syntax for this.
As you used brew to install, just uninstall mpv and install again using `--HEAD`.

There's also absolutely no reason to change all the deband parameters (yet). Install the latest mpv and then try 

    mpv --vo=opengl --profile=opengl-hq --log-file=mpv-Main10log-MBP-OpenGL.txt <your file>

**Comment by csdesigns** [comment]
Ok thx. I'm up to date on the iMac but possibly (probably) not on the MBP. When I tried to use the -- options on the build on my MBP, I received errors. Will update mpv/brew and retest. Thanks again!

**Comment by csdesigns** [comment]
> You should update your brew first though, as you can't even get your version (0.19) with brew anymore.

Updated brew and mpv. Can now use the aforementioned options without error. Resulting display output is now even better than ffplay's. So I am changing the title of this thread and closing the ticket. I will open a new ticket for true 10 bit display. Thanks to everyone for your help!
