### ISSUE TITLE
osd show system time 

### ISSUE THREAD

**Issue by jinlich** [mpv-player/mpv#3608]
mpv-version 0.20.0-git-c226bc7 win8.1

osd show system time 
How to write？
--osd-status-msg=${？？？？？}

**Comment by lachs0r** [comment]
mpv is a video player, not a clock.

But you could write a Lua script that does this.

**Comment by jinlich** [comment]
thanks

**Comment by akFace** [comment]
mpv.conf
```
osd-level = 3
osd-status-msg = ${clock}
```

**Comment by guidocella** [comment]
`--osd-msg1=${clock}` will show it always.
