### ISSUE TITLE
render 10 bit video as native 10 bit

### ISSUE THREAD

**Issue by csdesigns** [mpv-player/mpv#3613]
There currently are no easily available 'true' 10 bit video players on the mac. Every player which supports 10 bit decoding renders the video in 8 bit. macOS has supported native 10 bit rendering in some apps since El Capitan, though even Quicktime still doesn't support 10 bit rendering. Would be great to see this added at some point as Apple doesn't seem to be in a hurry to do so and it is highly doubtful Apple will ever support most of the formats mpv does.

**Comment by haasn** [comment]
mpv will render natively at 10-bit if your OpenGL implementation supports it. It work fine for me on nvidia.

**Comment by Hrxn** [comment]
How can I test (reliably) if this works properly on Windows?

**Comment by rossy** [comment]
@Hrxn well, for backend=win and backend=angle, I don't think it will work without modification. Both backends unconditionally try to create an 8-bit backbuffer:
https://github.com/mpv-player/mpv/blob/788929e/video/out/opengl/context_w32.c#L66
https://github.com/mpv-player/mpv/blob/3751065/video/out/opengl/context_angle.c#L68

backend=dxinterop _might_ work, since it tries to let Windows select a preferred backbuffer format, but in practice, I think it always selects format 22 (D3DFMT_X8R8G8B8.)

As mentioned in #3607, you can check for a line starting with ``Reported display depth: `` in mpv's verbose output to determine what display depth mpv thinks it's rendering to. Also, with dxinterop, check for a line like ``DX_interop backbuffer format:`` to see which D3D9 format it has selected for the backbuffer.

**Comment by wm4** [comment]
EGL_RED_SIZE indicates a _minimum_ size, and the default sorting order is that EGL configs with larger sizes will be preferred. So I think this should work, if ANGLE supports it at all.

**Comment by rossy** [comment]
Ah sorry, I didn't realise that. I wonder what ChoosePixelFormat/WGL does then.

**Comment by qmega** [comment]
> mpv will render natively at 10-bit if your OpenGL implementation supports it. It work fine for me on nvidia+linux.

Do you have a Quadro GPU or something? Or is there some trick? I have a GTX 980 Ti and Asus PB279Q, both of which ostensibly support 10-bit color, and I'm running over DisplayPort 1.2. My driver will only let me do 8-bit.

**Comment by fhlfibh** [comment]
> >mpv will render natively at 10-bit if your OpenGL implementation supports it. It work fine for me on nvidia+linux.

>Do you have a Quadro GPU or something? Or is there some trick?

I second this question.

**Comment by haasn** [comment]
> Do you have a Quadro GPU or something? Or is there some trick? 

You have to set Xorg to render in 10-bit mode. Open your xorg.conf and find the sections that say `Depth 24` / `DefaultDepth 24`. Change both to 30, save the file and restart Xorg.

After that, `glxinfo` should list only 10-bit formats and mpv should be capable of native 10-bit output

**Comment by qmega** [comment]
Wow, I can't believe it was that easy. Thank you!

Though I guess it's not *quite* that easy, because it seems to break Kwin's compositing, for starters... But at least mpv seems to know what it's doing.

**Comment by haasn** [comment]
I forgot to mention, it will break absolutely everything. Good filter for shit software, though.

**Comment by fhlfibh** [comment]
@haasn Thanks a lot!
BTW, was it you in this [nvidia's forum thread] (https://devtalk.nvidia.com/default/topic/771081/linux/30-bit-depth-with-linux-driver-does-not-produce-30-bit-output-on-monitor/post/4844206/#4844206) ?

**Comment by haasn** [comment]
> BTW, was it you in this nvidia's forum thread ? 

Yes

> Is it correct, that even with xorg.conf nvidia's GTX driver will dither 10 bits to 8 for HDMI/DVI output?

Seems so.

**Comment by Hrxn** [comment]
Well, I think `backend=angle` doesn't seem to work..

```
[vo/opengl-hq] EGL extensions: EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_stream_producer_d3d_texture_nv12 
[vo/opengl-hq] Rendering flipped.
[vo/opengl-hq] Using DirectComposition.
[vo/opengl-hq] GL_VERSION='OpenGL ES 3.0 (ANGLE 2.1.0.856c497e4798)'
[vo/opengl-hq] Detected GLES 3.0.
[vo/opengl-hq] GL_VENDOR='Google Inc.'
[vo/opengl-hq] GL_RENDERER='ANGLE (NVIDIA GeForce GTX 680 Direct3D11 vs_5_0 ps_5_0)'
[vo/opengl-hq] GL_SHADING_LANGUAGE_VERSION='OpenGL ES GLSL ES 3.00 (ANGLE 2.1.0.856c497e4798)'
[vo/opengl-hq] Combined OpenGL extensions string:
[vo/opengl-hq]  GL_OES_element_index_uint GL_OES_packed_depth_stencil GL_OES_get_program_binary GL_OES_rgb8_rgba8 GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_NV_pixel_buffer_object GL_OES_mapbuffer GL_EXT_map_buffer_range GL_EXT_color_buffer_half_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_float GL_OES_texture_float_linear GL_EXT_texture_rg GL_EXT_texture_compression_dxt1 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_OES_compressed_ETC1_RGB8_texture GL_EXT_sRGB GL_ANGLE_depth_texture GL_OES_depth32 GL_EXT_texture_storage GL_OES_texture_npot GL_EXT_draw_buffers GL_EXT_texture_filter_anisotropic GL_EXT_occlusion_query_boolean GL_NV_fence GL_EXT_disjoint_timer_query GL_EXT_robustness GL_EXT_blend_minmax GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_pack_reverse_row_order GL_OES_standard_derivatives GL_EXT_shader_texture_lod GL_EXT_frag_depth GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_EXT_discard_framebuffer GL_EXT_debug_marker GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_image_external_essl3 GL_NV_EGL_stream_consumer_external GL_EXT_unpack_subimage GL_NV_pack_subimage GL_EXT_color_buffer_float GL_OES_vertex_array_object GL_KHR_debug GL_ANGLE_lossy_etc_decode GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_sync_query GL_CHROMIUM_copy_texture GL_EXT_texture_norm16 
[vo/opengl-hq] Loaded extension GL_EXT_texture_norm16.
[vo/opengl-hq] Loaded extension GL_EXT_color_buffer_half_float.
[vo/opengl-hq] Loaded extension GL_EXT_disjoint_timer_query.
[vo/opengl-hq] Loaded extension GL_ANGLE_translated_shader_source.
[vo/opengl-hq] swap_control extension missing.
[vo/opengl-hq] Reported display depth: R=8, G=8, B=8
[vo/opengl-hq] Testing FBO format 0x805b
[vo/opengl-hq] Create FBO: 16x16 (16x16)
[vo/opengl-hq] Using FBO format 0x805b.
[vo/opengl-hq] Querying ICC profile...
[vo/opengl-hq/win32] display-fps: 119.982000
```

mpv -V
```
C:\Users\Hrxn>mpv -V
mpv 0.20.0-git-c226bc7 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Fri Aug 26 19:57:46 CEST 2016
ffmpeg library versions:
   libavutil       55.29.100
   libavcodec      57.54.100
   libavformat     57.48.100
   libswscale      4.1.100
   libavfilter     6.56.100
   libswresample   2.1.100
ffmpeg version: N-81464-g5686748
```

**Comment by Hrxn** [comment]
No cigar with `backend=dxinterop` either, it seems..
```
[vo/opengl-hq] GL_VERSION='4.5.0 NVIDIA 372.90'
[vo/opengl-hq] Detected desktop OpenGL 4.5.
[vo/opengl-hq] GL_VENDOR='NVIDIA Corporation'
[vo/opengl-hq] GL_RENDERER='GeForce GTX 680/PCIe/SSE2'
[vo/opengl-hq] GL_SHADING_LANGUAGE_VERSION='4.50 NVIDIA'
[vo/opengl-hq] Combined OpenGL extensions string:
[vo/opengl-hq] WGL_ARB_buffer_region WGL_ARB_create_context WGL_ARB_create_context_profile WGL_ARB_create_context_robustness WGL_ARB_context_flush_control WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_multisample WGL_ARB_pbuffer WGL_ARB_pixel_format WGL_ARB_pixel_format_float WGL_ARB_render_texture WGL_ATI_pixel_format_float WGL_EXT_create_context_es_profile WGL_EXT_create_context_es2_profile WGL_EXT_extensions_string WGL_EXT_framebuffer_sRGB WGL_EXT_pixel_format_packed_float WGL_EXT_swap_control WGL_EXT_swap_control_tear WGL_NVX_DX_interop WGL_NV_DX_interop WGL_NV_DX_interop2 WGL_NV_copy_image WGL_NV_delay_before_swap WGL_NV_float_buffer WGL_NV_multisample_coverage WGL_NV_render_depth_texture WGL_NV_render_texture_rectangle  GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_sparse_buffer GL_ARB_sparse_texture GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_draw_buffers GL_ATI_texture_float GL_ATI_texture_mirror_once GL_S3_s3tc GL_EXT_texture_env_add GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_Cg_shader GL_EXT_depth_bounds_test GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXTX_framebuffer_mixed_formats GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_shader_objects GL_EXT_separate_specular_color GL_EXT_shader_image_load_store GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_latc GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback2 GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_EXT_window_rectangles GL_EXT_import_sync_object GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KTX_buffer_region GL_NV_alpha_to_coverage_dither_control GL_NV_bindless_multi_draw_indirect GL_NV_bindless_multi_draw_indirect_count GL_NV_bindless_texture GL_NV_blend_equation_advanced GL_NV_blend_square GL_NV_command_list GL_NV_compute_program5 GL_NV_conditional_render GL_NV_copy_depth_to_color GL_NV_copy_image GL_NV_depth_buffer_float GL_NV_depth_clamp GL_NV_draw_texture GL_NV_draw_vulkan_image GL_NV_ES1_1_compatibility GL_NV_ES3_1_compatibility GL_NV_explicit_multisample GL_NV_fence GL_NV_float_buffer GL_NV_fog_distance GL_NV_fragment_program GL_NV_fragment_program_option GL_NV_fragment_program2 GL_NV_framebuffer_multisample_coverage GL_NV_geometry_shader4 GL_NV_gpu_program4 GL_NV_internalformat_sample_query GL_NV_gpu_program4_1 GL_NV_gpu_program5 GL_NV_gpu_program5_mem_extended GL_NV_gpu_program_fp64 GL_NV_gpu_shader5 GL_NV_half_float GL_NV_light_max_exponent GL_NV_multisample_coverage GL_NV_multisample_filter_hint GL_NV_occlusion_query GL_NV_packed_depth_stencil GL_NV_parameter_buffer_object GL_NV_parameter_buffer_object2 GL_NV_path_rendering GL_NV_pixel_data_range GL_NV_point_sprite GL_NV_primitive_restart GL_NV_register_combiners GL_NV_register_combiners2 GL_NV_shader_atomic_counters GL_NV_shader_atomic_float GL_NV_shader_buffer_load GL_NV_shader_storage_buffer_object GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_compression_vtc GL_NV_texture_env_combine4 GL_NV_texture_multisample GL_NV_texture_rectangle GL_NV_texture_shader GL_NV_texture_shader2 GL_NV_texture_shader3 GL_NV_transform_feedback GL_NV_transform_feedback2 GL_NV_uniform_buffer_unified_memory GL_NV_vertex_array_range GL_NV_vertex_array_range2 GL_NV_vertex_attrib_integer_64bit GL_NV_vertex_buffer_unified_memory GL_NV_vertex_program GL_NV_vertex_program1_1 GL_NV_vertex_program2 GL_NV_vertex_program2_option GL_NV_vertex_program3 GL_NVX_conditional_render GL_NVX_gpu_memory_info GL_NVX_multigpu_info GL_NVX_nvenc_interop GL_NV_shader_thread_group GL_NV_shader_thread_shuffle GL_KHR_blend_equation_advanced GL_SGIS_generate_mipmap GL_SGIS_texture_lod GL_SGIX_depth_texture GL_SGIX_shadow GL_SUN_slice_accum GL_WIN_swap_hint WGL_EXT_swap_control
[vo/opengl-hq] Loaded extension WGL_EXT_swap_control.
[vo/opengl-hq] Loaded extension WGL_NV_DX_interop.
[vo/opengl-hq] DX_interop backbuffer size: 1x1
[vo/opengl-hq] DX_interop backbuffer format: 22
[vo/opengl-hq] DX_interop backbuffer size: 1x1
[vo/opengl-hq] DX_interop backbuffer format: 22
[vo/opengl-hq] Direct3D device reset
[vo/opengl-hq] 16 bit texture depth: 16.
[vo/opengl-hq] Reported display depth: R=8, G=8, B=8
[vo/opengl-hq] Testing FBO format 0x805b
[vo/opengl-hq] Create FBO: 16x16 (16x16)
[vo/opengl-hq] Using FBO format 0x805b.
[vo/opengl-hq] Querying ICC profile...
[vo/opengl-hq/win32] display-fps: 119.982000
```

**Comment by Hrxn** [comment]
WAIT... I first need the correct media file, right?

**Comment by wm4** [comment]
>WAIT... I first need the correct media file, right?

No.

**Comment by Hrxn** [comment]
So, no matter the file, if it works it would be 8 bits per component to 10 bit conversion + dithering?

**Comment by csdesigns** [comment]
Sorry for the possibly obtuse question, but I am a bit confused given a comment made by **wm4** 
in thread #3607...
> ffplay is always restricted to 8 bit rendering, and it's not possible to get more 

So when I run the following:
`mpv --vo=opengl --profile=opengl-hq --log-file=mpv-Main10log-MBP-OpenGL.txt /Desktop/ColorRamps-grey-10bit.265`

I receive the following in the log:
> [   0.051][v][vo/opengl] Initializing OpenGL backend 'cocoa'
[   0.094][v][vo/opengl] GL_VERSION='4.1 ATI-1.42.15'
[   0.094][v][vo/opengl] Detected desktop OpenGL 4.1.
[   0.094][v][vo/opengl] GL_VENDOR='ATI Technologies Inc.'
[   0.094][v][vo/opengl] GL_RENDERER='AMD Radeon R9 M395X OpenGL Engine'
[   0.094][v][vo/opengl] GL_SHADING_LANGUAGE_VERSION='4.10'
[   0.097][v][vo/opengl] Loaded extension GL_APPLE_rgb_422.
[   0.098][v][vo/opengl] 16 bit texture depth: 16.
[   0.098][v][vo/opengl] Reported display depth: R=0, G=0, B=0
[   0.098][v][vo/opengl] Testing FBO format 0x805b
[   0.098][v][vo/opengl] Create FBO: 16x16 (16x16)
[   0.098][v][vo/opengl] Using FBO format 0x805b.

- Is **R=0, G=0, B=0** mpv's way of reporting 10 bit, since for 8 bit displays it reports **R=8, G=8, B=8**, or is this something else altogether? 
- **haasn**, since you have reported that 10 bit rendering is working for you with nvidia + linux, could please enter what your log reports?
- If **R=0, G=0, B=0** is indeed native 10 bit, does that therefore mean my [HEVC Main10 file](https://www.dropbox.com/s/26olt9xqn3a9f5l/ColorRamps-grey-10bit.265?dl=0) is being rendered as true 10 bit? If so, then that is most excellent!

Thanks once again for everyone's assistance!!

**Comment by fhlfibh** [comment]
@haasn 
> Seems so. You can check in the nvidia-settings control panel, under the dithering options.

With GTX 660 when `Color depth` in `xorg.conf` is set to 30 bits, with the above [HEVC Main10 file](https://www.dropbox.com/s/26olt9xqn3a9f5l/ColorRamps-grey-10bit.265?dl=0) mpv says like:
> [vo/opengl] Reported display depth: R=10, G=10, B=10
...
[vd] Decoder format: 1920x1080 yuv420p10 auto/limited CL=unknown
[vf] Video filter chain:
[vf]   [in] 1920x1080 yuv420p10 bt.709/limited CL=unknown
[vf]   [out] 1920x1080 yuv420p10 bt.709/limited CL=unknown

Does it mean that "10-bit output" in X and mpv works?

With a 8-bit monitor on DVI, Nvidia-Settings has _Dithering: Auto/Enabled/Disabled_, and if enabled it has _Depth: Auto/8 bit/6 bit_ options. With 370.28 driver, when dithering is disabled, I can see clear banding with the above file. When dithering is enabled, banding seems much less, if any. What could it mean? With dithering disabled, the driver outputs 10 bit even through DVI, to a non-10-bit monitor?

**Comment by csdesigns** [comment]
Including [full log](https://www.dropbox.com/s/354jarzf12afvpf/mpv-Main10log-iMac-OpenGL.txt?dl=0) from previous example posted

**Comment by AndyFurniss** [comment]
FWIW if your source is 10 bit yuv then you should still gain over 8 bit yuv when it's converted to 8 bit RGB because you can't represent anywhere near all RGB colors in the same bit depth yuv, plus there's normally a scale involved for video vs pc levels.

http://www.poynton.com/PDFs/Merging_RGB_and_422.pdf

**Comment by haasn** [comment]
> Is R=0, G=0, B=0 mpv's way of reporting 10 bit

No. I think that means “unknown” which makes mpv fall back to 8 bit.

> haasn, since you have reported that 10 bit rendering is working for you with nvidia + linux, could please enter what your log reports?

Same as @fhlfibh 

> What could it mean? With dithering disabled, the driver outputs 10 bit even through DVI, to a non-10-bit monitor?

With dithering disabled in the driver, it most likely just clips (rounds) to 8 bit depth, hence causing the visible banding that you can see.

By using `Depth 30` and nvidia's 10->8 dithering you are just moving the dithering from mpv's vo_opengl to nvidia's driver, which gains you basically nothing but causes lots of programs to break.

Also, what do the `Auto` options select for you when you have `Depth 30` set? On a 10-bit monitor, they would select `Depth: None` and `Dithering: Disabled`, on an 8-bit monitor they would select `Depth: 8` and `Dithering: Enabled`.

**Comment by Kagami** [comment]
>I forgot to mention, it will break absolutely everything

@haasn, could you please explain, what did you mean by that? Graphical programs will work unstable/won't work at all, or something like that?

**Comment by haasn** [comment]
> Graphical programs will work unstable/won't work at all, or something like that?

google chrome looks like this, for example :p 

![chrome](https://0x0.st/Mmr.png)

**Comment by aufkrawall** [comment]
With Windows 10 Creator's Update, it's possible to use 10 bit output also in borderless windowed mode (at least with DX11 and likely also 12).
Is that somehow beneficial for currently available backends of mpv? Does gpu-api=vulkan have the same limitation as gpu-api=opengl with gpu-context=win?

Btw: Xorg 1.20 is scheduled for January and is planned to have improvements for 10 bit.

**Comment by Schlammsuhler** [comment]
Also OSX HighSierra brings a 10bit desktop environment with Metal2: https://developer.apple.com/videos/play/wwdc2017/601/
Right now the reported display depth is -1 but i hope once the new api gets adopted it will work out of the box

**Comment by Argon-** [comment]
@Schlammsuhler regarding Metal see https://github.com/mpv-player/mpv/issues/4856

**Comment by aufkrawall** [comment]
Xorg 1.20 got delayed, but at least Deep Color support is now definitely mainlined:
https://www.phoronix.com/scan.php?page=news_item&px=Deep-Color-GLAMOR-Modesetting

**Comment by Akemi** [comment]
i have a branch [here](https://github.com/Akemi/mpv/commits/cocoa-cb_10bit) that updated cocoa-cb to support "Deep Color", eg 10bit. it has some dumb limitations that come from Apple, like only supporting 16bit float formats but no 10bit int ones. though more about that if i ever open a PR. you should probably use it with `fbo-format=rgba16`, or any similar fbo format. look for a line like `[libmpv_render] Dither to 16.` with `-v`, usually it says `8`.

on 8bit setup this is still quite pointless and might even degrade the quality slightly due to Apples dithering. though i didn't find a way to confirm 10bit compatibility by the system. feel free to test if you actually have a 10bit ready macOS system, i don't have one and can't test.
