### ISSUE TITLE
How to suppress VAAPI info messages?

### ISSUE THREAD

**Issue by nick-s-b** [mpv-player/mpv#3614]
Hi all,
My setup:
**mpv version and platform**
`mpv git-343f5ca` on `Linux 4.4.0-38-generic` and `libavutil 55.29.100; libavcodec      57.55.101`

My biggest annoyance are VAAPI info messages that show up whenever I play a video from the command line.  See the output sample below...

I've tried `--quiet` , `--really-quiet` , and  `--no-terminal` and no matter what I do, I get these annoying livba info messages. What do I need to do to get rid of them?

Thanks!

```
libva info: VA-API version 0.39.2
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
libva info: VA-API version 0.39.2
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
libva info: VA-API version 0.39.2
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
```

**Comment by wm4** [comment]
libva prints them directly to stdout or stderr. We have no way of preventing this.

**Comment by lachs0r** [comment]
https://bugs.freedesktop.org/show_bug.cgi?id=73340

**Comment by tmpsa** [comment]
It appears to being fixed. :-)
https://bugs.freedesktop.org/show_bug.cgi?id=73340
https://bugs.freedesktop.org/show_bug.cgi?id=89432

**Comment by wm4** [comment]
Yeah, and mpv implements it.

**Comment by tmpsa** [comment]
No, mpv still outputs those pesky lines. This issue should therefore be re-opened.

To reproduce, configure mpv (or mpvlib) with
```
   vo = opengl
   opengl-backend=drm
   hwdec=vaapi
```
You see, the fix in libva does not fully solve the problem; its _default_ behaviour is _still_ to output messages to stdout/stderr. It's _only_ after the user (in this case mpv/mpvlib) calls the new functions
```
   vaSetErrorCallback(NULL);
   vaSetInfoCallback(NULL); 
```
that libva shuts up.

(I hope that I have understood it all correctly.)

A library should _never_ output anything on stdout/stderr.
Please implement the fix in mpv and mpvlib by using these calls.

**Comment by wm4** [comment]
> Please implement the fix in mpv and mpvlib by using these calls.

But it is?

**Comment by tmpsa** [comment]
Unfortunately, it does not seem so. (Also, the latest mpvlib has the same problem).
```
fl@S3-prototype:~/test-mpvlib$ mpv --version
mpv git-51fd8f6 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Fri Dec  9 03:51:07 UTC 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.2

fl@S3-prototype:~/test-mpvlib$ mpv --really-quiet test2.mp4
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
fl@S3-prototype:~/test-mpvlib$
```

**Comment by ArchangeGabriel** [comment]
@tmpsa Isn’t your build of mpv simply too old?

**Comment by tmpsa** [comment]
Is there a newer one? Where?
Also: the problem remains in libmpv, too. I extracted a really fresh copy from the .deb package at
https://launchpad.net/~mc3man/+archive/ubuntu/tests3/+packages

**Comment by ArchangeGabriel** [comment]
@tmpsa: Yes, in this very same git repo, that’s the principle. Latest commit is 1 hour ago. Your build is 1 month old, not sure where it’s from but if it’s yours you should build from latest git master to check whether this is fixed.

The link you gave is not even up-to-date regarding releases: current is 0.23 (https://github.com/mpv-player/mpv/releases/tag/v0.23.0), while it provides 0.22.

**Comment by ArchangeGabriel** [comment]
@tmpsa I understood your issue. `mpv - 2:0.23.0+git~xenial` doesn’t have anything in its version that would trigger update on your side I think (not .deb/Ubuntu expert though). So you don’t get update of your -git version.

**Comment by ArchangeGabriel** [comment]
In the code: https://github.com/mpv-player/mpv/search?utf8=%E2%9C%93&q=vaSetErrorCallback

**Comment by ArchangeGabriel** [comment]
And the commit: https://github.com/mpv-player/mpv/commit/2ce55238938163da8ecd302fe7c9d08e7b0b4174

**Comment by mc4man** [comment]
Re: mpv, I don't see this as working with libva/intel-vaapi-driver - 1.8.0 (0.40.0)
 Ex.  
using mpv git-fb6481e
$ mpv --no-config --hwdec=vaapi --vo=opengl  '/home/doug/Videos/amostviolentyear-nowplaying_h1080p.mkv' 
Playing: /home/doug/Videos/amostviolentyear-nowplaying_h1080p.mkv
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 (*) (mp3)
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
AO: [pulse] 44100Hz stereo 2ch s16
Using hardware decoding (vaapi).
VO: [opengl] 1920x816 vaapi
AV: 00:00:04 / 00:00:31 (12%) A-V:  0.000

So is this only to work with 0.39.4 + next commit?

@tmpsa 
The version of libmpv you have would not have this, nor would the version of libva typically available.
As far as libmpv I'll not update past 0.22 until deciding whether to provide newer shared ffmpeg libs or just go with statically linking ffmpeg to a shared object which feels wrong but I guess could work.
So maybe build your own mpv/libmpv if need be but there is also the issue of libva version..

**Comment by Vrihub** [comment]
FYI, this is still happening and quite annoying on my Debian 10 (Buster) system.

mpv 0.29.1
ffmpeg library versions:
   libavutil       56.14.100 (runtime 56.22.100)
   libavcodec      58.18.100 (runtime 58.35.100)
   libavformat     58.12.100 (runtime 58.20.100)
   libswscale      5.1.100 (runtime 5.3.100)
   libavfilter     7.16.100 (runtime 7.40.101)
   libswresample   3.1.100 (runtime 3.3.100)
ffmpeg version: 4.1.4-1~deb10u1

**Comment by CounterPillow** [comment]
Update your vaapi then, it works fine here.

**Comment by Vrihub** [comment]
> Update your vaapi then, it works fine here.

Thanks! I've upgraded `libva2`, `libva-x11-2` etc from version 2.4.0 to the upstream latest 2.5.0 (packages from Debian testing), but I still get the annoying messages.

    libva info: VA-API version 1.5.0
    libva info: va_getDriverName() returns 0
    libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
    libva info: Found init function __vaDriverInit_1_4
    libva info: va_openDriver() returns 0

Also the `i965-va-driver` package is at the latest available version.
Any ideas?

**Comment by Vrihub** [comment]
Uhm, I forgot to mention that actually the bug happens when I use `mpv --vo=vdpau`.

The bug **does not** happen when I run `mpv --vo=vaapi`, but playback is slow as hell, which I wouldn't expect, since I have an intel chipset:
`VGA compatible controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 35)`

OTOH, running `mpv --vo=vdpau` gets me the annoying libva messages, but decent playback speed, despite mpv telling me:
`[vo/vdpau] VDPAU is most likely emulated via VA-API.`
`[vo/vdpau] This is inefficient. Use --vo=gpu instead.`

Oh, and BTW, if I use `--vo=gpu`, the playback is terribly slow; it has become so slow since I've upgraded mpv from 0.23 (Debian Stretch) to 0.29.1 (Debian Buster); that's the reason I've been testing alternative `--vo=` options, but I guess this is an entirely different bug...

**Comment by Vrihub** [comment]
> Oh, and BTW, if I use `--vo=gpu`, the playback is terribly slow; it has become so slow since I've upgraded mpv from 0.23 (Debian Stretch) to 0.29.1 (Debian Buster); that's the reason I've been testing alternative `--vo=` options, but I guess this is an entirely different bug...

Ok, I now found out that if I add `--hwdec=auto` (or `--hwdec=auto`), `--vo=gpu` is again fast as it was in 0.23, so that did the trick for me!

**Comment by CounterPillow** [comment]
>Ok, I now found out that if I add --hwdec=auto (or --hwdec=vaapi), --vo=gpu is again fast as it was in 0.23, so that did the trick for me!

Try setting `vd-lavc-dr=no`. There are a few rare Intel GPUs on which direct rendering is a lot slower, and between those two versions you stated, direct rendering was made the default (as it is usually faster for everyone else). This should allow you to use `vo=gpu` even without hardware decoding.

As for the vaapi messages, those probably come from the vdpau-vaapi emulation layer you were using, i.e. were not within the hands of mpv at all but from whatever library provided your vdpau implementation.
