### ISSUE TITLE
Cannot start mpv after 8.0 cuda update.

### ISSUE THREAD

**Issue by Toqozz** [mpv-player/mpv#3618]
### mpv version and platform

 mpv 1:0.20.0-1 on 4.7.5-1-ARCH
### Reproduction steps
- install cuda 8.0
- launch mpv
- `mpv: error while loading shared libraries: libnppi.so.7.5: cannot open shared object file: No such file or directory`
### Expected behavior

Any of mpv's functions to work.
### Actual behavior

None of them work.
### Log files

I cannot include a log file because I cannot open mpv at all with cuda updated.

**Comment by paulguy** [comment]
Tried reinstalling mpv?  Might need to make sure it's actually recompiled so it builds against the new library.  If it's from the main Arch repo it might just be a binary install but an AUR install should be from source and should rebuild against the new version.

**Comment by Toqozz** [comment]
I've tried reinstalling the binary from repos but you're probably right about the recompiling, thanks.  I should report to arch repos instead!

**Comment by philipl** [comment]
It means your ffmpeg was built with cuda support against 7.5 and then cuda was upgraded. Ffmpeg needs to be rebuilt. mpv itself doesn't use libnppi.
