### ISSUE TITLE
Subtitle font setting overrides the embedded font.

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#3619]
In some cases, the subtitle font setting overrides the ASS embedded font when playing the entire episode with ordered chapters, but works fine if only the OP is played.
### mpv version and platform

macOS Sierra
mpv git-026ccca
### Reproduction steps

Playing some ordered chapters(OP, ED etc.) with embedded font ASS subtitles. 
### Expected behavior

Embedded fonts are used to display the subs.
### Actual behavior

Subtitle font setting is overrides the ASS embedded font, but playing the OP alone has no problems.
### Log files

http://sprunge.us/jjKR - Playing the total episode.
http://sprunge.us/HWXB - Playing OP alone.

**Comment by lachs0r** [comment]
Can’t reproduce with any of the releases I have.
