### ISSUE TITLE
It seems all the black pixels have been replace by blue pixels, since update to macOS Sierra.

### ISSUE THREAD

**Issue by matrix-42** [mpv-player/mpv#3626]
All the black pixels have been replace by blue pixels, include the osc bar itself.
Same as #3578 
### mpv version and platform

[cplayer] mpv 0.20.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Sep 20 20:17:33 PDT 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.28.100
[cplayer]    libavcodec      57.48.101
[cplayer]    libavformat     57.41.100
[cplayer]    libswscale      4.1.100
[cplayer]    libavfilter     6.47.100
[cplayer]    libswresample   2.1.100
[cplayer] ffmpeg version: 3.1.4

rMBP:
macOS Sierra
2.4 GHz Intel Core i5
Intel Iris 1536 MB
### Reproduction steps

normally open a video
### Actual behavior

<img width="1280" alt="screen shot 2016-10-04 at 6 31 11 pm" src="https://cloud.githubusercontent.com/assets/7775348/19098571/128dd636-8a63-11e6-9a7b-73a5a5c0fafc.png">

with warnings:

```
[vo/opengl-hq] ICC profile detected contrast very high (>100000), falling back to contrast 1000 for sanity. Set the icc-contrast option to silence this warning.
[vo/opengl-hq] ICC profile detected contrast very high (>100000), falling back to contrast 1000 for sanity. Set the icc-contrast option to silence this warning.
AV: 00:01:09 / 00:01:49 (63%) A-V: -0.000 Cache: 10s+4MB

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).
```
### Log files

http://sprunge.us/KKIO
### Sample files

https://www.youtube.com/watch?v=1xo3af_6_Jk

**Comment by matrix-42** [comment]
When I delete `3dlut-size=256x256x256` in line
`opengl-hq:icc-profile-auto:3dlut-size=256x256x256:blend-subtitles=yes`  in mpv.conf 
problem solved.

But I still don't know why.

**Comment by haasn** [comment]
Does it go away if you use 64x256x256 or 256x64x256?

**Comment by matrix-42** [comment]
@haasn 
I just checked, no such problem using 64x256x256 or 256x64x256. 
When using 128x256x256 or 256x128x256 or 256x256x128 problem appears.
You have any idea?

**Comment by haasn** [comment]
OpenGL texture size limits perhaps?

**Comment by chenxi6623** [comment]
Same problem.
I changed the
`local hqvo = "opengl-hq:icc-profile-auto:3dlut-size=256x256x256:blend-subtitles=yes"`inscripts/vo_battery.lua to`local hqvo = "opengl-hq:icc-profile-auto:3dlut-size=256x256x64:blend-subtitles=yes`,like you said, and the blue pixels turn into black. 
But I don't know why.

**Comment by Akemi** [comment]
please open a new issue if this problem still persists.
