### ISSUE TITLE
cycle-values window scale

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3632]
I am using the following in my input.conf

`F4 cycle_values window-scale 1 1.5 2.0 2.25 2.5 2.75 3.0`

the problem i am facing is that it remembers the last scale when i pressed F4

I mean inbetween i pressed any other key and come back and press F4 it does not start from scale 1. It continues from the previous scale i pressed using F4

How to reset it to scale 1 and then start over again progressively.

What i did: I assigned F3 to window-scale 0.5

So i press F3 then F4 then it should start from scale 1. Instead it starts sometimes from 2 (where it was left last time)

**Comment by Hrxn** [comment]
Well, this is intentional, I'd say..

But you can use this: `cycle <property> [up|down]`, i.e. use <kbd> F4</kbd> to cycle up and <kbd>F3</kbd> to cycle down.

**Comment by wiiaboo** [comment]
You can use static values, like
```
alt+1 set window-scale 0.5
alt+2 set window-scale 1
alt+3 set window-scale 2
```
or add values:
```
alt+1 add window-scale -0.25
alt+2 add window-scale +0.25
```
Those make both more sense than what you seem to be trying to do.

**Comment by sant527** [comment]
How to use `cycle <property> [up|down] `

I tried `F7 cycle window-scale up` and `F6 cycle window-scale down`

they look working, but  i want to cycle at 0.25 window-scale so how to mention that. Now it increases in +1

**Comment by wiiaboo** [comment]
```
alt+1 add window-scale -0.25
alt+2 add window-scale +0.25
```
This does exactly what you want.

**Comment by Hrxn** [comment]
Yeah, apparently the value can't be changed with [cycle property](https://mpv.io/manual/master/#command-interface-cycle-<property>-[up|down]).

But you could also try [cycle_values](https://mpv.io/manual/master/#command-interface-cycle-values) with *!reverse*, i.e. like this `cycle-values ["!reverse"] <property> "<value1>" "<value2>" ...`

Or if you really just want to use steps by 0.25, use `add window-scale <x>`
The benefit of `cycle_values` is that you can use smaller increments around factor 1.0...

Or what I am currently using:
```
Ctrl+1 set window-scale 0.25
Ctrl+2 set window-scale 0.5
Ctrl+3 set window-scale 0.75
Ctrl+4 set window-scale 0.8
Ctrl+5 set window-scale 1.0
Ctrl+6 set window-scale 1.25
Ctrl+7 set window-scale 1.5
Ctrl+8 set window-scale 1.75
Ctrl+9 set window-scale 2.0
Ctrl+0 set window-scale 2.25
```
