### ISSUE TITLE
resume play from the point i closed

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3633]
I am playing a video file and viewed till certain time. After i close how to resume it back to that same position.

Other than pressig Q. I mean if i close with mouse the window

**Comment by wiiaboo** [comment]
[--save-position-on-quit](https://mpv.io/manual/master/#options-save-position-on-quit)

**Comment by briatte** [comment]
Dear @wiiaboo 

Adding `CLOSE_WIN quit-watch-later` to input.conf does not work here (mpv 0.29.0 on macOS).

Is there any other way to enable 'resume playback at last position' by default, please?

**Comment by Akemi** [comment]
> [--save-position-on-quit](https://mpv.io/manual/master/#options-save-position-on-quit)

he already said how.

**Comment by briatte** [comment]
@Akemi Sure, but how do I add this to input.conf, please?

**Comment by CounterPillow** [comment]
you add it to mpv.conf, not input.conf. It's not an input keybinding.

**Comment by briatte** [comment]
@CounterPillow Thank you. The Mac version of `mpv` does not create [`mpv.conf`](https://github.com/mpv-player/mpv/blob/master/etc/mpv.conf) by default, so I did not know it existed.

Problem solved, thanks all.

**Comment by Argon-** [comment]
No version of mpv on any system creates any kind of config file (neither mpv.conf nor input.conf or the others) by itself. If such a thing happened for you then it was by whomever packaged or installed mpv for you.
