### ISSUE TITLE
2D Playback of 3D content, incorrect pixel format

### ISSUE THREAD

**Issue by susnux** [mpv-player/mpv#3634]
Using mpv 0.20.0 on openSUSE Linux

If I want to watch e.g. a 3D matroska file (stereomode 3 (Left above right eye)) it gets played incorrectly.
So mpv inserts its automatic stereo3d to mono filter which works, but then it uses the height of the full file (2160 pixel) so the movie get stretched (1920x2160 instead of 1920x1080).

If I set the video height in the matroska file to 1080 (only one eye) then 2d works but 3d does not.

mpv playback output:
```Opening video filter: [stereo3d in=auto out=mono]
VO: [opengl] 1920x1080 => 1920x2160 yuv420p

``````

my config:
```vo=opengl:interpolation:
video-sync=display-resample
audio-channels=2.1
volume=100
volume-max=100
``````

**Comment by wiiaboo** [comment]
Can you print the output of mediainfo?

**Comment by susnux** [comment]
Mediainfo:

> Format                                   : Matroska
> Format version                           : Version 4 / Version 2
> File size                                : 7.00 GiB
> Duration                                 : 1h 34mn
> Overall bit rate mode                    : Variable
> Overall bit rate                         : 10.6 Mbps
> Encoded date                             : UTC 2016-07-29 11:02:51
> Writing application                      : mkvmerge v9.3.1 ('Mask Machine') 64bit
> Writing library                          : libebml v1.3.3 + libmatroska v1.4.5
> 
> Video
> ID                                       : 1
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : High@L5.2
> MultiView_Count                          : 2
> MultiView_Layout                         : Top-Bottom (left eye first)
> Format settings, CABAC                   : Yes
> Format settings, ReFrames                : 16 frames
> Codec ID                                 : V_MPEG4/ISO/AVC
> Duration                                 : 1h 34mn
> Width                                    : 1 920 pixels
> Height                                   : 2 160 pixels
> Display aspect ratio                     : 0.889
> Frame rate mode                          : Constant
> Frame rate                               : 23.976 fps
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Progressive
> Writing library                          : x264 core 148
> Encoding settings                        : cabac=1 / ref=16 / deblock=1:1:1 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=10 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=19.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:0.60
> Default                                  : Yes
> Forced                                   : No

```mkvmerge -F json --identify```:

> "codec": "MPEG-4p10/AVC/h.264",
>       "id": 0,
>       "properties": {
>         "codec_id": "V_MPEG4/ISO/AVC",
>         "codec_private_length": 44,
>         "default_duration": 41708333,
>         "default_track": true,
>         "display_dimensions": "1920x2160",
>         "enabled_track": true,
>         "forced_track": false,
>         "language": "und",
>         "minimum_timestamp": 0,
>         "number": 1,
>         "packetizer": "mpeg4_p10_video",
>         "pixel_dimensions": "1920x2160",
>         "stereo_mode": 3,
>         "uid": 1
>       },
>       "type": "video"

**Comment by wiiaboo** [comment]
Try changing display_dimensions to 1920x1080 then.

**Comment by susnux** [comment]
Then 2D works but 3D will fail (both images are scaled to 1080p height instead of 2205px (frame packing).
So in that case maybe mpv (is it mpv or libav back-end? other) should not scale the output in 3d case.

**Comment by wiiaboo** [comment]
That's probably because mpv assumes it's ab2l, so you need `--video-stereo-mode=no --vf stereo3d=ab2l:abl` for it to maintain the full vertical resolution.

**Comment by susnux** [comment]
What works is using ```--video-unscaled=yes```

**Comment by wm4** [comment]
So what's the nature of the bug? mkv demuxer error? Somehwere else?

**Comment by susnux** [comment]
Ok so the bug is not 2d playback, if I use a standard conforming mkv file it works like it should.
The problem is 3d playback. So if I disable automatic 3d to 2d converting it should be played back without any scaling.
With the latest mpv release I have to add this to get the correct result:

`--video-unscaled=yes --video-aspect=0 --video-zoom=0`

Because even if stereo-mode is set to no mpv scales the video if it would play back only one eye.

This is not a problem when using other stereo-mode settings (e.g. `irr`) but there is no option for full Above-Below (ffmpeg's `abl` and `abr`) only half above below (`ab2r` and `ab2l`).

Maybe add some code to support `abl` and `abr` and optionally `hdmi` (ffmpeg supports that but mpv complains `Invalid value for option video-stereo-mode`).
Or to disable scaling if stereo-mode is set to `no`.

**Comment by susnux** [comment]
https://github.com/mpv-player/mpv/issues/1161 seems to be related to the missing formats for full AB(R/L).

**Comment by Akemi** [comment]
if this problem still persists, please open a new issue.
