### ISSUE TITLE
Playlist display text issue when using OSC

### ISSUE THREAD

**Issue by Hrxn** [mpv-player/mpv#3635]
### mpv version and platform
```
C:\Users\Hrxn>mpv -V
mpv 0.20.0-git-c226bc7 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Fri Aug 26 19:57:46 CEST 2016
ffmpeg library versions:
   libavutil       55.29.100
   libavcodec      57.54.100
   libavformat     57.48.100
   libswscale      4.1.100
   libavfilter     6.56.100
   libswresample   2.1.100
ffmpeg version: N-81464-g5686748
```
Windows 10 x64 (tested on two systems)

### Reproduction steps

Show the playlist by using Shift+<kbd>Left-Click</kbd> on either the *playlist next* or *playlist prev* button on the [OSC interface](https://mpv.io/manual/master/#the-interface), compare to playlist display when using something like this: `Ctrl+p show-text ${playlist}` (in your input.conf).

### Expected behavior
![mpv-showtext](https://cloud.githubusercontent.com/assets/12064918/19201882/124c3e00-8cd0-11e6-8f0d-40f904f7e8d0.png)

### Actual behavior
![mpv-borked](https://cloud.githubusercontent.com/assets/12064918/19201885/1837a6ce-8cd0-11e6-855b-f353b55c020b.png)

### Additional note:

According to https://mpv.io/manual/master/#the-interface, a left-click on the *title* button (or maybe rather area) should result in
> show playlist position and length and full title

These files had no title, so I see the filename instead, the playlist position (like this: `[x/y]`), but no length?!

**Comment by ChrisK2** [comment]
> These files had no title, so I see the filename instead, the playlist position (like this: [x/y]), but no length?!

x = position in playlist, y= length of playlist

I can reproduce the other issue, but need to investigate the cause first.

**Comment by wiiaboo** [comment]
It's probably been there since https://github.com/mpv-player/mpv/commit/05c398fb6c3a48c6a72b6b0706ea0156c46b146d .

**Comment by Hrxn** [comment]
> x = position in playlist, y= length of playlist

Ah, the length of the playlist, I see.. 😄 

Another question: Has this playlist message a property name, so that it can be used with a keybind, without the OSC?

**Comment by wiiaboo** [comment]
[playlist/count or playlist-count](https://mpv.io/manual/master/#command-interface-playlist/count), so `show-text ${playlist-count}`

**Comment by Hrxn** [comment]
Okay, thanks.

To resemble the full message, I use now something like this: 
`show-text "[${playlist-pos-1}/${playlist-count}] : ${filename} (${media-title}) (${duration})"`

BTW, if you use the property `playlist/N/filename`, for example, how do you use expansion there? I.e. replace N with current playlist position. Or is that not possible?

**Comment by wiiaboo** [comment]
Never tried. Probably too much for property expansion, more meant for scripting.

**Comment by Hrxn** [comment]
Something blocking the merge? Or just forgot? 😄

**Comment by wiiaboo** [comment]
An OK from @wm4 and/or @ChrisK2.

**Comment by wm4** [comment]
I don't really get it, but ok.

**Comment by Hrxn** [comment]
Just tried it with 0.21.0, issue doesn't seem to appear anymore.

(With new default, `osc-layout=bottombar`, did not explicitly test with `osc-layout=box` (or anything else), but the OSC elements/functions should be the same)

No merge mentioned here so far.
Maybe another commit, merged somewhere else, secret commit log? I don't know.. 😉 
Anyway, I guess this can be closed..

**Comment by wiiaboo** [comment]
Yeah, forgot about this.
