### ISSUE TITLE
libmpv static crashes on windows (Lua)

### ISSUE THREAD

**Issue by gen2brain** [mpv-player/mpv#3637]
Hello,

I am trying to use libmpv statically built in my app. It works in Linux, but on Windows it crashes. I managed to get some info from windbg:
```
*** ERROR: Symbol file could not be found.  Defaulted to export symbols for a.out.exe - 
a_out!luaopen_package+0x15744:
01dd6424 891490          mov     dword ptr [eax+edx*4],edx ds:002b:00000000=????????
0:016> k
ChildEBP RetAddr  
WARNING: Stack unwind information not available. Following frames may be wrong.
404cf848 01dc91b8 a_out!luaopen_package+0x15744
404cf8f0 776633b5 a_out!luaopen_package+0x84d8
404cfa50 01c948e7 ntdll!RtlpAllocateHeap+0xe68
404cfa78 01c4c08e a_out+0x18948e7
404cfa80 77662b65 a_out+0x184c08e
404cfab0 01c948e7 ntdll!RtlFreeHeap+0x142
404cfad8 01c4d1b8 a_out+0x18948e7
404cfae8 76dd98da a_out+0x184d1b8
404cfb3c 6eccd952 msvcrt!free+0xec
404cfbd0 00000000 d3d9!CD3DDDIDX10::Clear+0x43
```

libmpv and app are built on Linux, with i686-w64-mingw32 toolchain. I tried to compile with lua5.1, lua5.2 and luajit, no difference. If I disable osc then it works, but I need osc.

Here is a verbose log output:
https://gist.github.com/gen2brain/c991e6dba4c4fb3ea68b5e85bc23b483

Do you have any idea what I am missing? 

Thanks,
Milan

**Comment by wm4** [comment]
Are there possibly multiple libluas linked?

**Comment by gen2brain** [comment]
I don't think it is possible. Before I try with other version I always clean headers, library and pkgconfig file, and always have only one version available. I think compiler will also complain about multiple definition in that case, but I will check everything again to be sure. Library does have that symbol, I checked with nm:
```
# i686-w64-mingw32-gcc-nm -g /usr/i686-w64-mingw32/usr/lib/liblua.a | grep luaopen_package
00000fa0 T _luaopen_package
                U _luaopen_package
```

**Comment by gen2brain** [comment]
I will just use mpv.exe binary on Windows. I tried also with shared libmpv and it also crashes. I failed to compile it so it asks for lua.dll though, no matter how lib is named (liblua.dll.a, ,liblua.dll, lua.dll etc.) linker can't find shared lib.  If I ever try again and have something new to show I will reopen this issue.

Thanks

**Comment by lachs0r** [comment]
Does it work with the libmpv builds on https://mpv.srsfckn.biz (grab the dev archive)?

**Comment by gen2brain** [comment]
Yes, it does work with those builds :) Thanks. Are they also built on Linux, with cmake scripts that are available?
