### ISSUE TITLE
OS X 10.12 not adapter

### ISSUE THREAD

**Issue by WM520** [mpv-player/mpv#3638]
when my mac system is OS X 10.12 , this app remind me that we do not provide support for this pre-release version. You may encounter build failures or other breakages. I help you can fix this bug in the future

**Comment by Cpuroast** [comment]
10.12 is fully supported by mpv, I've used 0.20 on 10.12 without any differences compared to 10.11.  

I've used our semi-official builds for OSX listed here:
https://mpv.io/installation/

**Comment by WM520** [comment]
OK, I get it
