### ISSUE TITLE
--stream-capture not capturing another stream

### ISSUE THREAD

**Issue by malimM** [mpv-player/mpv#3639]
### mpv version and platform

mpv-git-44044.gb5357e8-1; Manjaro(Arch)

### Reproduction steps

I have videos set to open with --stream-capture=/home/user/Videos/<filename> argument but once a stream is captured and I open another(not at the same time), then it won't capture. I suspect it's because of the naming scheme since the new versions of mpv don't overwrite but neither does it append.

### Expected behavior

Append file to directory.

### Actual behavior

File doesn't capture(append) to directory if a file with the same name already exists.

###

I have a somewhat similar query, how do I make mpv name the file according to the captured stream name, this would solve the problem of it not appending.

**Comment by wm4** [comment]
Nope, writre a shell script or something.

**Comment by malimM** [comment]
@wm4 May I ask which part? Setting the captured stream name to the stream name or capturing another stream when there already is one?

**Comment by wm4** [comment]
Both. The stream-capture feature is garbage anyway.
