### ISSUE TITLE
Display 'Time elapsed / Total time' with a keybind

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3640]
On _input.conf_ I have `no-osd cycle_values osd-level 3 1` assigned to a key. It displays the progress of the current video as:

`[Status Icon] XX:XX:XX / YY:YY:YY (ZZ%)`

I'm very obsessive with certain things, and it irks me that it has an icon and a percentage field, because I don't need them and they make the / character appear off-center. I tried looking for a way to simply display the XX:XX:XX / YY:YY:YY part, but I couldn't find an answer.

**Comment by Hrxn** [comment]
`KEY show-text "${playback-time} / ${duration}"`
or
`KEY show-text '${playback-time} / ${duration}'`
or
`${time-pos} instead of ${playback-time}`

**Comment by skeletonhands** [comment]
`osd-msg3='${playback-time} / ${duration}'`

**Comment by firewater2** [comment]
Thanks guys! It worked.
