### ISSUE TITLE
how to jump by keyframes.

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3642]
I have a video which is concatination of multiple videos. So to jump to each part easily i prefer to jump by key frames. 

In MPV how to jump by key frames using keyboard shortcut

**Comment by wiiaboo** [comment]
[seek command](https://mpv.io/manual/master/#command-interface-[relative|absolute|absolute-percent|relative-percent|exact|keyframes])
```
LEFT seek -0.1 keyframes
RIGHT seek +0.1 keyframes
```

**Comment by sant527** [comment]
why 0.1

**Comment by Cpuroast** [comment]
You obviously didn't realize that unless you are using the --hr-seek option or: using an "exact" seek input.conf mapping, mpv does fast keyframe seeks by default.

**Comment by wm4** [comment]
Using something like 0.01 would probbaly work better. But there's no native feature for this. Also, concatenating videos with cat (instead of rewriting headers and timestamps by remuxing) is almost guaranteed to cause some sort of problem.
