### ISSUE TITLE
what is the use of --hr-seek=

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3643]
what is the use of --hr-seek=

can i anyone give example, how it makes some difference in seeking

**Comment by Argon-** [comment]
https://mpv.io/manual/master/#options-hr-seek
> Select when to use precise seeks that are not limited to keyframes. Such seeks require decoding video from the previous keyframe up to the target position and so can take some time depending on decoding performance. For some video formats, precise seeks are disabled. This option selects the default choice to use for seeks; it is possible to explicitly override that default in the definition of key bindings and in input commands.

**Comment by sant527** [comment]
I wanted to know the meaning with any example

**Comment by Hrxn** [comment]
high resolution seek.,.

**Comment by Cpuroast** [comment]
If you use hr-seek=yes(or always) it overrides the default mpv behavior, which is to do a fast keyframe seek and instead will do a slow exact seek.
