### ISSUE TITLE
new arbitrary video rotate filter

### ISSUE THREAD

**Issue by bothie** [mpv-player/mpv#3647]
### mpv 0.20.0

The new video-rotate feature - cool thing.

1) Should get documented in the man page thou, still stating:

Rotate  the video clockwise, in degrees. Currently supports 90° steps only.  [...]

2) Even cooler would be: Support negative degree (i.e. -10 should equal 350),

3) and 357.5 (and other fractions) should be possible too.

4) the new rotate is lossless in the sense, that it doesn't crop anything away, creating black triangles. Another optional flag would be cool to allow the filter to drop content such that no black triangles need to be added. Like --video-rotate=350:crop would crop parts away leaving no black triangles, not specifying :crop could yield current behavior.

And there is one issue: I seem not to be able to control the order of the rotate filter and the crop filter. -vf rotate is still limited to 90 degree steps (not sure, if this is the same filter) and reordering --video-rotate and -vf crop on the command line doesn't help.

**Comment by haasn** [comment]
re: video-rotate I wanted to make it so that the option/property would allow arbitrary inputs and the code that handles it would perform the necessary modulo 360. This would allow e.g. “add video-rotate 90” to work the way you'd expect it to. Any counter-arguments?

**Comment by wm4** [comment]
--video-rotate=123 already works.

**Comment by haasn** [comment]
@wm4 Yes, this issue was raised after arbitrary rotation was enabled.

**Comment by Dudemanguy** [comment]
`video-rotate` allows for 0-359 rotation so I think this feature request is fulfilled by now.
