### ISSUE TITLE
OS X 10.12 Folder Playlist Issue

### ISSUE THREAD

**Issue by jadorno** [mpv-player/mpv#3649]
### mpv version and platform

mpv 0.20.0 on OS X 10.12

### Reproduction steps

mpv ~/Music

### Expected behavior

Iterate Recursively to locate music 

### Actual behavior

Outputs: "This is a directory - adding to playlist." (as expected, and then nothing happens)

### Log files

(From Verbose Output)

[cplayer] Playing: OST/
[cplayer] Running hook: ytdl_hook/on_load
[osd/libass] Using font provider coretext
[osd/libass] Done.
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[file] Opening OST/
[file] This is a directory - adding to playlist.
[file] Stream opened successfully.
[demux] Trying demuxers for level=normal.

### Sample files

Not Required

**Comment by wm4** [comment]
Seems like a duplicate of another bug, but I don't remember which.

Does this happen with the final OSX Sierra version?

**Comment by jadorno** [comment]
Yes, the pre-release beta OSX Sierra concluded a few weeks ago and is now available to the public.
