### ISSUE TITLE
move "watch_later" folder to $XDG_CACHE_HOME/mpv/

### ISSUE THREAD

**Issue by excelwang** [mpv-player/mpv#3650]
The current "watch_later " folder is underlying .config/mpv/, which is very inconvenient for managing  mpv configuration files using git or cloud drive.

It is much reasonable to place "watch_later" folder under $XDG_CACHE_HOME/mpv/. $XDG_CACHE_HOME is typically set to $HOME/.cache in unix-like systems.

**Comment by Argon-** [comment]
Side note: `~/.config/mpv/watch_later` is even used when your (working) config, scripts and all this stuff are in `~/.mpv`.

**Comment by haasn** [comment]
It should be `$XDG_DATA_HOME` (i.e. `~/.local/share/mpv/watch_later`), not `$XDG_CACHE_HOME`.

**Comment by qmega** [comment]
In git master there's an option --watch-later-directory. And yeah, it should definitely go it data, not cache. So you could put in your comfig file:

    watch-later-directory=~/.local/share/mpv/watch_later

or wherever you want it.

IMO it would have been better for the option to be for data dir in general, and then watch_later could have gone in it, but also scripts could store data there or any future persistent-data feature. Then it could have even defaulted to $XDG_

**Comment by wm4** [comment]
You can change it with ``--watch-later-directory``.
