### ISSUE TITLE
 Mpv cannot read radio stream if no file is provided ( ERROR: Unsupported URL )

### ISSUE THREAD

**Issue by jstuyck** [mpv-player/mpv#3651]
### mpv version and platform

   cplayer: mpv 0.20.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
   cplayer:  built on Thu Sep 29 16:53:41 BST 2016
   cplayer: ffmpeg library versions:
   cplayer:    libavutil       55.28.100
   cplayer:    libavcodec      57.48.101
   cplayer:    libavformat     57.41.100
   cplayer:    libswscale      4.1.100
   cplayer:    libavfilter     6.47.100
   cplayer:    libswresample   2.1.100
   cplayer: ffmpeg version: 3.1.4

### Reproduction steps

$ mpv http://85.21.79.31:7128/

### Expected behavior

Playing music.

### Actual behavior

Error Failed to recognize file format.

### Log files

http://pastebin.com/VvFiyw8x

### Sample files

Radio Steam.

**Comment by avih** [comment]
> Reproduction steps
> 
> $ mpv http://85.21.79.31:7128/
> Expected behavior
> 
> Playing music.

FWIW, it plays music for me with mpv/ffmpeg only slightly newer than yours.

**Comment by jstuyck** [comment]
I'm using the version from Brew, gonna try to compile master to check.

**Comment by jstuyck** [comment]
Ok, With new version it did not work as well, 
So I removed my configuration file and it's working now.
I'm going to check the configuration file.

**Comment by jstuyck** [comment]
OK it seems to happen when the user-agent is spoofed, so I don't think it's a bug but the destination server that does not like that 😄 

`[protocol.http]
user-agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0'`

**Comment by jstuyck** [comment]
A last test, in fact when the user-agent is spoofed (as it was for me), the shoutcast server return a webpage that describes the stream, the same as if your where browsing the url (normal behavious) not the stream by itself.

**Comment by wiiaboo** [comment]
That's not a bug, it's a feature in Shoutcast/Icecast servers.

**Comment by wm4** [comment]
This is why mpv doesn't use a browser-like user agent by default.
