### ISSUE TITLE
mpv cannot be built without internet connection

### ISSUE THREAD

**Issue by rofl0r** [mpv-player/mpv#3652]
### mpv version and platform

https://github.com/mpv-player/mpv/archive/v0.20.0.tar.gz
### Reproduction steps

turn off internet and run
./waf configure
./waf -v build
./waf install --destdir=foo
### Expected behavior

mpv builds and installs.
### Actual behavior

waf wants to upgrade itself from internet and refuses to build without it.
### Log files

```
Downloading https://waf.io/waf-1.8.12...
Download failed.
Downloading http://www.freehackers.org/~tnagy/release/waf-1.8.12...
Download failed.
Could not download waf-1.8.12.
```

**Comment by fhlfibh** [comment]
AFAIK, it's expected:

> The mpv build system uses waf but we don't store it in your source tree. The script './bootstrap.py' will download the latest version of waf that was tested with the build system.
https://github.com/mpv-player/mpv

**Comment by rofl0r** [comment]
that may be expected by the developers, but quite unexpected by the users!
i suspect it would be a nice idea to make a proper release tarball with the included waf sources instead of relying on the poor github tags (see also https://github.com/sabotage-linux/sabotage/wiki/Why-github-downloads-suck )

**Comment by wm4** [comment]
This is either a releaser issue (CC @lachs0r), or an issue of replacing waf with something else.

**Comment by haasn** [comment]
If I understand the issue correctly, the `waf` command itself tries contacting the internet to check for new versions?

If so, adding the `waf` command to the release tarballs is unlikely to solve this particular issue. (But if it's not done already, it definitely should be)

**Comment by mc4man** [comment]
If waf is already in the source at required version then it does not try to upgrade here, just goes along it's merry way.
With no internet - 
$ ./waf configure
Setting top to                           : /home/doug/Desktop/mpv-static/new52/mpv/mpv 
Setting out to                           : /home/doug/Desktop/mpv-static/new52/mpv/mpv/build 
Checking for waf version in 1.8.4-1.9.0  : ok 

I thought the non issue here was that waf isn't included in the source. But if one can acquire mpv source(s) then they should be able to aquire waf which they only need to do once (re-use it) until version req. changes

**Comment by rofl0r** [comment]
@mc4man : so your recommendation is that the user that wants to be able to build mpv offline stores both the mpv tarball and the corresponding waf sources, and then at build time manually merges them together ?

**Comment by mc4man** [comment]
Not suggesting anything. Simply pointing out that the waf file that is acquired thru ./bootstrap.py can be reused for quite some time. (the one I got 10 months ago is still ok.
It's just a single file, not a source.
If they want to start inc. it in the mpv source fine but it's no big deal to get it once per the version requirement lifetime even if one is internet hobbled.

**Comment by rofl0r** [comment]
@lachs0r : can we get a statement from you as well, now that you've released 0.21.0 ?

**Comment by rofl0r** [comment]
ping

**Comment by lachs0r** [comment]
Grab waf yourself.
