### ISSUE TITLE
This basically a stupid question but I really want to ask what is a fullform of MPV?

### ISSUE THREAD

**Issue by Droyk** [mpv-player/mpv#3658]

**Comment by haasn** [comment]
I don't understand your question. Could you re-phrase it?

**Comment by Droyk** [comment]
Well okay I want to know what does MPV stands for? what is the full meaning of MPV?

**Comment by fhlfibh** [comment]
@haasn, OP thinks _mpv_ is an abbreviation.

**Comment by Droyk** [comment]
@fhlfibh Ohh so MPV is not an abbreviation I totally thought that it is an abbreviation.

**Comment by lamarpavel** [comment]
Well there is mplayer and mplayer2, since mp3 and mp4 are already taken in this context, it's mp5, but written as roman numeral v.

... or maybe not, I really just made this up.

**Comment by Droyk** [comment]
that's really stupid you know

**Comment by lamarpavel** [comment]
Well, you said it's `basically a stupid question`. So I guess that's okay then (:

**Comment by Droyk** [comment]
Lol

**Comment by wm4** [comment]
Some say it's for Mpv Plays Video, but they're wrong.
