### ISSUE TITLE
INFO: Nvidia VDPAU codec support by card

### ISSUE THREAD

**Issue by tsoernes** [mpv-player/mpv#3661]
Even though the Nvidia VDPAU library support most codecs your card might not. 
Each card has a feature classification (http://us.download.nvidia.com/XFree86/Linux-x86_64/364.19/README/supportedchips.html) with different capabilities (https://en.wikipedia.org/wiki/VDPAU#Nvidia_VDPAU_Feature_Sets)

**Comment by lachs0r** [comment]
TL;DR: Just run `vdpauinfo` to find out which features are supported by your GPU.
