### ISSUE TITLE
[RFE] Support color space conversion for v4l2

### ISSUE THREAD

**Issue by mathstuf** [mpv-player/mpv#3662]
The `colorspace`, `ycbcr_enc`, `quantization`, and `xfer_func` fields in `v4l2_pix_format` are not used. These are required to get proper color for v4l2 streams. Not quite sure where such logic should go exactly.

Note: I'm not all that interested in this feature personally (I think; my webcam seems to have bigger issues than colorspace…), but for anyone who is interested, this is what is needed.

**Comment by haasn** [comment]
I don't really understand what the requirements are here

**Comment by wm4** [comment]
I suppose this means pushing through the colorspace metadata from v4l through the layers to the mpv video chain.

**Comment by lachs0r** [comment]
This is now pretty much up to FFmpeg if you use `av://v4l2:/dev/videoX`.
