### ISSUE TITLE
(libavcodec) vdpau-hwaccel breaks on ffmpeg commit "ffmpeg: use new decode API"

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#3664]
### mpv version and platform

mpv git-b5357e8 linux (ubuntu 16.04
### Reproduction steps

build latest mpv using ffmpeg at or after git-8f6f2322285fc14f8f16377db50355864019a757
### Expected behavior

vdpau-hwaccel would be enabled
### Actual behavior

It's disabled in waf configure, ex.
Checking for libavcodec VDPAU hwaccel                                : no 
### Log files

Current ffmpeg git-2016-10-14-d790e48
waf config log
 (- libavcodec VDPAU hwaccel starts line 2257 (line numbers in browser avail by appending url 
http://sprunge.us/SCiP
# 's http://sprunge.us/SCiP?%3Clang%3E

Complete build log (package) ffmpeg config starts line 392,  mpv waf  config starts line 4420
http://sprunge.us/UOCi
# 's http://sprunge.us/UOCi?%3Clang%3E

logs from build using ffmpeg commit in question are pretty much the same, one warning was removed by later ffmpeg commit - 
src/libavutil/hwcontext_vdpau.c: In function ‘vdpau_device_create’:
 src/libavutil/hwcontext_vdpau.c:447:0: warning: "GET_CALLBACK" redefined
  #define GET_CALLBACK(id, result)

This is on an optimus machine using nvidia drivers, full mpv -v log file available if needed though nothing unexpected with  -hwdec=vdpau -vo=vdpau as vdpau-hwaccel was not compiled in 
(- using -hwdec=yes  ends up using vaapi-copy which I don't know what to make of & not really relevant to the issue

**Comment by mc4man** [comment]
What also shows is while there were 2 commits to ffmpeg concerning this it still does come up no - 
Checking for libavcodec decode/encode API                            : no

**Comment by wm4** [comment]
Important part:
```/home/doug/Desktop/mpv/new/mpv-0.20.0+git4~xenial/build_libs/lib/libavutil.a(hwcontext_vdpau.o): In function `vdpau_device_create':
/home/doug/Desktop/mpv/new/mpv-0.20.0+git4~xenial/ffmpeg_build/src/libavutil/hwcontext_vdpau.c:432: undefined reference to `XOpenDisplay'```

Definitely a ffmpeg bug. Their pkg-config file for libavutil doesn't add the X11 libs, which libavutil needs now.

**Comment by wm4** [comment]
Is this with a static ffmpeg?

**Comment by mc4man** [comment]
Yes, static.
( Also tried with libav git, same result

**Comment by wm4** [comment]
Libav has the same bug, of course.

**Comment by wm4** [comment]
I tried with mpv-build, and it works for me. It detects both the vaapi and ffmpeg hwaccels.

**Comment by mc4man** [comment]
Just tried mpv-build here, same result - 
Checking for libavcodec VDPAU hwaccel : no
So maybe a local issue?,  though it seemed this report was related,  though not much info supplied & 'solved' by just using ffmpeg-release instead
https://github.com/mpv-player/mpv/issues/3657

**Comment by mc4man** [comment]
If I relax the check in wscript, (check_headers), then support is enabled & vdpau hwdec works fine in practice. 
But in general I wouldn't do that as I'd assume it's structured the current way for good reason.

**Comment by mc4man** [comment]
Well with current mpv & ffmpeg sources done with a static ffmpeg there are 4 unexpected waf config fails - 
Checking for libavcodec avcodec_enum_to_chroma_pos API
Checking for libavcodec avcodec_profile_name()
Checking for libavcodec decode/encode API
Checking for libavcodec VDPAU hwaccel

With same mpv & the ffmpeg source done as shared all 4 pass

All use a waf check_statement so at least **here** either wscript is correct & they shouldn't be enabled or the check_statements as is can't succeed with a static ffmpeg, i.e. wscript is at fault

Allowing them to be enabled with static ffmpeg,   mpv builds & runs fine.

**Comment by slr** [comment]
> Just tried mpv-build here, same result -
Checking for libavcodec VDPAU hwaccel : no

same here.

**Comment by wm4** [comment]
To Mikus Grinsbergs, this is a ffmpeg bug. We can't do anything about it. Also we don't have control over 3rd party builds, nor do we care about it.

**Comment by mc4man** [comment]
closing as some of the failed are no longer checked with req of 3.2.2, as far as vdpau-hwaccel not an issue with shared & the configure fall on static nonsense is easily worked around.
