### ISSUE TITLE
watch_later restoring of non-fullscreen after window resize broken

### ISSUE THREAD

**Issue by globau** [mpv-player/mpv#3665]
mpv 0.20.0, macOS 10.12 (from stolendata.net)

**STR**
1. enable `save-position-on-quit` and `fullscreen` in `mpv.conf`
2. open any video
3. switch to windowed mode
4. resize the window to a smaller size (eg. half size)
5. quit playback
6. reopen the same video

**Expected**
- video restored to identical state

**Actual**
- window is sized larger than the video, resulting in large black borders
  <img width="1186" alt="screenshot 2016-10-15 11 30 39" src="https://cloud.githubusercontent.com/assets/872825/19407128/1c4a6980-92cb-11e6-8afd-9410a0edcd19.png">
- resizing this window doesn't resolve the issue
  <img width="551" alt="screenshot 2016-10-15 11 31 13" src="https://cloud.githubusercontent.com/assets/872825/19407129/234b4790-92cb-11e6-9f71-cc0863bc51d0.png">
- the video looks correct when fullscreen

**Comment by wm4** [comment]
Can't reproduce on Linux. Must be some sort of resizing error when starting in windowed mode on OSX.

**Comment by sandlst** [comment]
If I have a playlist with differently sized videos this behavior also occurs, but only when using the native OS X fullscreen mode; when I enter fullscreen mode by double clicking the video, there is no black space even when the new video loaded is a different size.

**Comment by wm4** [comment]
So that's actually a completely different bug.

**Comment by Akemi** [comment]
i just tested it with git master and couldn't reproduce it on OSX, neither with a normal nor a HiDPI resolution. can you reproduce it with only `save-position-on-quit` and `fullscreen` in your config or do you have other option in there?

**Comment by globau** [comment]
i can no longer reproduce this with mpv 0.21.0
