### ISSUE TITLE
Feature request--start from the beginning if play is pressed...

### ISSUE THREAD

**Issue by CrisBRM** [mpv-player/mpv#3666]
... when keep-open is set to yes and the playlist consists of a single file.

**Comment by kevmitch** [comment]
I assume you're referring to the OSC play button. @wiiaboo is this something that we do or do not want. If the later, this should be closed. I suppose there would have to be some logic to determine that we are paused at the end of the file to decide whether the play button has this special meaning. Seems a bit weird, though might be useful / intuitive.

The original wording of #5394 sounds like it is also requesting this, even though the user then +1ed being told to `loop-file`, which I believe makes `keep-open` redundant.

**Comment by wm4** [comment]
Or the user can add a key binding that seeks to 0 (and maybe unpauses).

**Comment by wiiaboo** [comment]
Yeah, restarting might not always mean "seek to 0 + unpause". It can depend on --start/resumed from watch-later, the format, in the case of ended livestreams it might break stuff since the segments might not exist anymore...

**Comment by thebombzen** [comment]
Seeking to `0` and unpausing for a seekable stream should work provided that `--rebase-start-time=yes` is set (which it is by default). Quit-Watch-Later just sets the `--start` option before loading the file, and you can already seek to zero if `--start` is set (`--loop-file` does exactly this). For a nonseekable stream you should not expect seeking to zero to work. It's possible reloading the file (the way `--loop-playlist` works) could work for a livestream but then it would respect the `--start` option and you could get issues there.

**Comment by Akemi** [comment]
duplicate #6291.
