### ISSUE TITLE
hardware dec breaks cropping

### ISSUE THREAD

**Issue by horusra** [mpv-player/mpv#3667]
cropping only works with software decoder

Please see this for info:
https://github.com/aidanholm/mpv-easycrop/issues/5

the scripts:
https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua
https://github.com/aidanholm/mpv-easycrop/blob/master/easycrop.lua

**Comment by wiiaboo** [comment]
> Most video filters will not work with hardware decoding as they are primarily implemented on the CPU. Some exceptions are vdpaupp, vdpaurb and vavpp. See VIDEO FILTERS for more details.

From [the manual on --hwdec](https://mpv.io/manual/master/#options-hwdec)

If you want working filters, you need to change hwdec to `auto-copy` or disable it.

**Comment by aidanholm** [comment]
Perhaps it'd be more user-friendly to raise an error when trying to add a crop filter (and possibly others) while using hwdec with a non-copy-back mode?

**Comment by wm4** [comment]
You still can crop the bottom/right border, just not the top/left ones. The reason is that FFmpeg doesn't support the appropriate metadata.
