### ISSUE TITLE
Youtube Opening with MPV doesn't work, youtube-dl download does

### ISSUE THREAD

**Issue by horusra** [mpv-player/mpv#3672]
![image](https://cloud.githubusercontent.com/assets/17074394/19418014/9d834fda-93bb-11e6-9aba-fb6228d2fec6.png)

Not sure I understand this error. it seems to happen only with some links, but the weird thing is, downloading it to disk with youtube-dl works just fine.

**Comment by wiiaboo** [comment]
Duplicate of https://github.com/mpv-player/mpv/issues/3388.
