### ISSUE TITLE
Ignore certain subtitle languages

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3674]
Often, videos include subtitles in all sort of languages, but I can only read English, so I don't have any need for seeing them.

Even if they just appear for one second while cycling subs, it's a small, visual annoyance, and also a functional one in the cases were none of the subtitles bundled are in English, and I have to download random ones and try them all - it's rather inconvenient to have to cycle [rus], [jap], [spa], [eng], [eng]

**Comment by lamarpavel** [comment]
Take a look at the settings `--slang=en` and `--sub-forced-only` as well as `--sub-auto=all`, in combination they could simply always select the subs you want automatically without any need for interaction. If that does not cover all cases you want, could you please give a use case where you want to search through subs even though english was selected by default?

**Comment by lasers** [comment]
This is what I came here to look for. It is a small annoyance for me too. Is it possible not to load all subtitles in the mpv? For one, it feels like a long minute to retrieve a video from YouTube along with unwanted 106 subtitles that never will be used. 

I only wanted a video and just `slang=en,eng,English`.

Some use cases where I want to search through subs even although English was selected by default...would be to check if it's a native English subtitle or an automatic translation subtitle, to see if it's really only an (English) option, and to check alternatives like en-GB. Most of the videos is likely to be coming from YouTube.

Also, a question... Do `slang=en,eng,English` cover en-GB too? I think having `slang=English,eng,en` first load some other language although I wanted to make sure mpv selects a native English file first before automatic translation... I'm not sure how to do that.

**Comment by firewater2** [comment]
Right, so sometimes movies come with subtitles for the commentary track, and that would be a case were two (en) subtitles are present, so even with `--slang=en` I would still have to rotate between foreign languages to reach the (en) with the commentary. A similar case - the variance of SDH (en) and standard (en), in which case I would have to rotate too, and perhaps they're side to side so it's no major concern, but other times the SDH is (en) and the standard one is (un) -for undefined, or unknown, iirc-, so in that case I would have to scroll through foreign languages to reach one from the other.

It's also a matter of visual noise, too. I don't like seeing foreign alphabets, since I can't read them.

**Comment by 07416** [comment]
Is there now an option to completely exclude specific subtitle languages? As an example use case, I default to English but may switch to my native language depending how "prose-like" the dialogue is. Additionally many can't read anything with non-Latin alphabet.

**Comment by stax76** [comment]
I worked on a script addressing this issue:

https://github.com/stax76/mpv-scripts/blob/9d21be1ee8b275092bb98c7d1ac069bc9386be13/misc.lua#L35

https://github.com/stax76/mpv-scripts/commit/9d21be1ee8b275092bb98c7d1ac069bc9386be13

https://github.com/stax76/mpv-scripts/blob/main/misc.lua

Another script that might be helpful:

https://github.com/dyphire/mpv-scripts/blob/main/track-list.lua

**Comment by KonoVitoDa** [comment]
@stax76 any way to also ignore *Forced* subtitle tracks?
