### ISSUE TITLE
osc only displays on hover

### ISSUE THREAD

**Issue by plexigras** [mpv-player/mpv#3675]
### Expected behavior

display osc if mouse move over window.
https://mpv.io/manual/master/#on-screen-controller-osc-visibility

### Actual behavior

only displays if mouse move over osc.

### mpv version and platform

git [0a81fe1](https://github.com/mpv-player/mpv/commit/0a81fe1cf9e62c26ebda1c209b3b69467991b252) / Arch Linux

**Comment by wiiaboo** [comment]
That's from the deadzonesize change in https://github.com/mpv-player/mpv/commit/8bb57c038799da39e72491888d0fc19beb493d62 which I forgot to mention in the commit log. If you change it back to 1 that's the old behavior.

**Comment by plexigras** [comment]
its [8bb57c0L217](https://github.com/mpv-player/mpv/commit/8bb57c038799da39e72491888d0fc19beb493d62#diff-67b9f869265c619e35ceb771102055a7L217) to be exact
https://mpv.io/manual/master/#on-screen-controller-deadzonesize

either changing the docs to include a mention of ``deadzonesize`` or setting the ``deadzonesize`` to ``0`` by default might stop further confusion.

**Comment by wiiaboo** [comment]
Sorry, what do you mean by including a mention of `deadzonesize`? Isn't that what the text in the link explains?

**Comment by plexigras** [comment]
i mean mentioning ``deadzonesize`` at the ``layout`` option.
something like ``auto (on mouse move outside of deadzone)``
https://mpv.io/manual/master/#on-screen-controller-osc-visibility

just so people know where to look at when they want the behavior to be like it used to be
