### ISSUE TITLE
Fullscreen incorrect when next video in playlist is different size (OS X native fullscreen)

### ISSUE THREAD

**Issue by sandlst** [mpv-player/mpv#3677]
### MPV Version

mpv git-912d668 (built on Mon Oct 17)
### System

OS X Sierra
Intel Iris Pro / AMD Radeon R9 M370X
### Reproduction steps

Load a playlist of two or more with differing video sizes (tested with first video 640x480, second video 1280x720)
### Expected behavior

When the second video is loaded, if we already are in fullscreen that video will be full screen as well.
### Actual behavior

Video is normal size in the middle of the screen with black bars filling the empty space around the video (actual window is still fullscreen).
### Notes

This behavior only happens with the Native OS X fullscreen mode (clicking the green button to make the video go full screen).  When double clicking to make the video go fullscreen the next video's fullscreen mode displays correctly.  This behavior is the same for both hardware and software decoding.
### Log file

I've made 2 log files; the first one is from me starting on the smaller video, going to the larger video, then un-maximizing the window and finally re-maximizing it to where it looks correct(OS X Native fullscreen).

The second log is made the same way as above except the mpv Fullscreen mode is used by double clicking the video window when it first comes up.

It's hard for me to make sense of the log files because it looks like there is a lot more "resizing" going on than what was actually going on, but I did notice in the first log file there is a point where it resizes the window to 2560x1440; I assume this happens when the playlist loads the second (1280x720) file.  In the second log file the window is always resized to 2880x1800 after the first resizing to 2880x1800 (the correct fullscreen resolution) and never gets resized to 2560x1440.

[OS X native fullscreen log](http://sprunge.us/GRCj)
[MPV fullscreen log](http://sprunge.us/VheL)

**Comment by Akemi** [comment]
does it work with the [new native fs](https://github.com/mpv-player/mpv/commit/a8347eb9ba9e09177da50592fde7f3ae7261ce59)?

**Comment by sandlst** [comment]
Yes, it works perfect now! Thanks for your hard work! 👍
