### ISSUE TITLE
mpv randomly appears big or small, right or left desktop on wayland

### ISSUE THREAD

**Issue by fthiery** [mpv-player/mpv#3679]
### mpv version and platform

Using Arch Linux with gnome 3.22 (which enabled wayland)

$ mpv --version
mpv 0.20.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Aug 27 12:41:39 CEST 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.4

[cplayer] Configuration: ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-encoding --enable-libmpv-shared --enable-zsh-comp
[cplayer] List of enabled features: alsa any-gl asm atomics audio-input av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-has-codecpar avcodec-new-codec-api avcodec-profile-name avframe-metadata avframe-skip-samples avutil-has-hwcontext avutil-hdr avutil-mastering-metadata build-date c11-tls caca cdda cplayer debug-build dlopen drm dvbin dvdnav dvdread egl-drm egl-helpers egl-x11 enca encoding fchmod gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libm libmpv-shared librt libsmbclient libswresample libv4l2 linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native plain-gl posix posix-or-mingw posix-spawn pthreads pulse resampler rubberband shm sse4-intrinsics standard-gl stdatomic subprocess termios tv tv-v4l2 vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-hwaccel vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h wayland x11 xext xinerama xrandr xss xv zlib zsh-comp

### Reproduction steps

Open the same video repeatedly (run, quit)

$ mpv bbb-1920-1080-30.mp4

### Expected behavior

Video should be displayed in native size (xorg behaviour)

### Actual behavior

Randomly (most of the time), video displays either tiny or with native size
Video appars on left desktop (tiny) then flashing big then moved to the right (tiny)
Sometimes video stays on the other desktop

### Log file

tiny.txt : case where video appears tiny
big.txt: case where video appears big

[big.txt](https://github.com/mpv-player/mpv/files/538259/big.txt)
[tiny.txt](https://github.com/mpv-player/mpv/files/538260/tiny.txt)

![big](https://cloud.githubusercontent.com/assets/87642/19510347/220d1ba4-95e3-11e6-89b3-a47cf682c4cc.png)
![tiny](https://cloud.githubusercontent.com/assets/87642/19510346/2209fa78-95e3-11e6-9781-69c6b984ff72.png)

**Comment by atomnuker** [comment]
This got fixed in cb2cb540f, which was committed 4 days after your mpv was compiled. So update your mpv somehow.
If you want to know what happens, Mutter asks us to resize to 0x0 pixels for some reason, which I think stands for "choose your own size", but the resize code has an arbitrary limit of 150x150 pixels minimum size.
