### ISSUE TITLE
mp3 with subs

### ISSUE THREAD

**Issue by vnckppl** [mpv-player/mpv#3684]
I was looking into the possibility to play mp3 files with lyrics in .srt format. 

When I load an .srt file to play with an .mp3 file it does not show the subtitles. When I load the same subtitle with a movie file mpv does show the subtitle. Is there a way to force the subtitle to show when playing .mp3 files?

**Comment by wm4** [comment]
Currently not, unless you use some sort of fake video.

**Comment by rrooij** [comment]
You can do: 

`mpv --force-window --sub-file=[your_sub_file] [your_audio_file]`

It works here.

**Comment by wm4** [comment]
As far as I know, it doesn't work - it doesn't update correctly.

**Comment by rrooij** [comment]
I did the following:

1. Downloaded a creative commons licensed mp3 example: http://sampleswap.org/mp3/artist/5101/Peppy--The-Firing-Squad_YMXB-160.mp3
2. Saved the example SRT https://www.matroska.org/technical/specs/subtitles/srt.html
3. Played the mp3 with force-window and used the saved sub file. It updates those two sentences correctly, as far as I can see.

This is by using an older version: 0.8.3

**Comment by wm4** [comment]
>This is by using an older version: 0.8.3

So try a not-old version.

**Comment by vnckppl** [comment]
Can confirm that unfortunately this is not working for me.

mpv installed via homebrew on osx:

mpv 0.21.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Oct 20 03:54:44 BST 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.4

**Comment by rrooij** [comment]
Same problem with latest git master.

**Comment by wm4** [comment]
It's possible that older versions used the legacy OSD subtitle renderer path, which got removed.

**Comment by vnckppl** [comment]
Any chance it will be reincorporated?

**Comment by zhangn1985** [comment]
I think you can try: https://github.com/PedroHLC/osdlyrics
