### ISSUE TITLE
Request: a consistent way to get possible values for an option

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#3702]
I don't think this is already implemented, so what i am asking is a way to print all available possible values an option would accept in a consistent way so that it could be parsed without risks of breakage.
This would lead to better autocompletion features for shells or, biased, more complete frontends.

Right now, several options like vo,ao,vf,af,vd provides a "formatted" output like:
```
#mpv --ao=help
head
value : description
[..]
value : description
```
others acts different, 
eg: stereo-mode=help (documented in man page) answers like an error:
```
Invalid value for option video-stereo-mode: help
Valid values are:
    no
    mono
```
undocumented usually acts the same way (eg: mpv --framedrop=help)

Is that feasible without too much effort? Even a one-shot dump for all of the options would do the trick, eg: mpv --list-options=values

**Comment by wm4** [comment]
You can use the `option-info/<name>` property. Because option parsing is complex, this is not always fully complete.

**Comment by kokoko3k** [comment]
thanks
