### ISSUE TITLE
How to get icy-title using JSON IPC?

### ISSUE THREAD

**Issue by alezost** [mpv-player/mpv#3705]
Hello, this is not a bug report, just a question (sorry if it is
documented, I couldn't find the answer).

How can I get `icy-title` tag from a stream using JSON IPC?  I mean when
I use `get_property` on `metadata` property I get various icy things
(icy-name, icy-genre, etc.), but `icy-title` is not among them.

Thanks.

**Comment by wm4** [comment]
If `icy-title` is available at all, it should be in the metadata property.

**Comment by alezost** [comment]
I'm very sorry, I see it now! 

I could sware it wasn't there yesterday, but, well, my bad :blush:
Sorry for bothering.
