### ISSUE TITLE
Seeking precision problems on web video

### ISSUE THREAD

**Issue by ResponSySS** [mpv-player/mpv#3706]
### mpv version and platform

`uname -a`

> Linux [...] 4.8.2-1-ARCH #1 SMP PREEMPT Mon Oct 17 08:11:46 CEST 2016 x86_64 GNU/Linux

`mpv --version`

> mpv 0.21.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
>  built on Thu Oct 20 08:19:09 CEST 2016
> ffmpeg library versions:
>    libavutil       55.28.100
>    libavcodec      57.48.101
>    libavformat     57.41.100
>    libswscale      4.1.100
>    libavfilter     6.47.100
>    libswresample   2.1.100
> ffmpeg version: 3.1.4
### Reproduction steps

`mpv "http://www.rts.ch/archives/tv/information/temps-present/3471760-la-loge-p2-et-licio-gelli.html"`
- play a few seconds
- pauses
- (a) rewind back to 00:00 using ← or ↓
- undo pause
- (b) seek through using ↑ or →
### Expected behavior

(a) rewind back to the first frame of the video, paused
(b) seek to 5s (→) or 1min (↑) later
### Actual behavior

(a) seek to about 30s later
(b) seek to 8s or plus (→) or 1m 1s or plus (↑) later
### Log file

http://sprunge.us/RfTM

**Comment by wiiaboo** [comment]
Not absolutely sure but you want exact behavior while using relative seeks. Can't have both.
Either use [`seek [secs] exact`](https://mpv.io/manual/master/#command-interface-[relative|absolute|absolute-percent|relative-percent|exact|keyframes]) or [--hr-seek=yes](https://mpv.io/manual/master/#options-hr-seek) to always have slow but exact seeks.

**Comment by wm4** [comment]
The (a) behavior is broken. It can never get back to the start for some reason. Must be either a ffmpeg HLS issue, or a broken stream (I see `[ffmpeg] NULL: non-existing PPS 0 referenced` errors all over the place).

**Comment by ResponSySS** [comment]
I should have added: the (a) and (b) behaviours perfectly work on the downloaded video (`youtube-dl "http://www.rts.ch/archives/tv/information/temps-present/3471760-la-loge-p2-et-licio-gelli.html"`).

**Comment by wiiaboo** [comment]
That works because youtube-dl remuxes the files after downloading them.

**Comment by GAumala** [comment]
I have this issue when streaming crunchyroll videos using the `--start` flag. If I do something like `--start=00:00:19` it starts later like at 00:00:30 . seeking to a particular timestamp with a mouse click has the same problem. However `--start=+0` does start at the beginning.

I guess a quick hack would be to use start positions that are about 30 seconds earlier...

**Comment by Akemi** [comment]
stale issue.
