### ISSUE TITLE
Non-transparent sub-shadow

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3712]
(Perhaps I'm missing something, but I don't think this is possible to do right now)

I have my subtitles without borders, and a slight shadow offset. It looks fantastic, but sometimes there isn't enough contrast to make the text out, so I'd love to be able to have a jet black, non-transparent, shadow, in order to resolve this issue (imagine it like rendering the subtitle a second time).

And yeah, I could just add a border, but that defeats the purpose of styling. It's a completely different feeling having even a 1px border.

**Comment by haasn** [comment]
It would take a bit of work, but it might be possible to expose subtitles as a hookable texture to the `opengl-shaders` subsystem. With that in place, it would be possible for you to run arbitrary shaders on their contents (e.g. overlaying them on top of a blurred, darkened version of them).

That should solve your use case, no? One design consideration would be whether to make the ‘subtitle’ texture the size of the entire video texture, or whether to constraint it to the size of the the actual subtitles. The latter would make something like blurring significantly more efficient, but it also wouldn't allow you to extend the blur past the edge of this texture (so it would get `cut off`), unless some other mechanism is added to allow users to resize a texture without scaling.

**Comment by lachs0r** [comment]
Uh, you can simply [adjust the shadow color](https://mpv.io/manual/master/#options-sub-shadow-color). It includes an alpha value.

Of course this isn’t going to help with bitmap-based subtitles (Blu-ray, DVD, DVB etc.) but for anything else it should work. Also needs [--sub-ass-style-override](https://mpv.io/manual/master/#options-sub-ass-style-override) for ASS subtitles.

**Comment by firewater2** [comment]
Oh boy, yes, sorry haasn, I may not have made it too clear. I didn't know about an alpha value.

`Ctrl+3 no-osd cycle_values options/sub-text-font "Arial" "Arial"; no-osd cycle_values options/sub-text-border-size "0" "0"; no-osd cycle_values options/sub-text-color "#dadada" "#dadada"; no-osd cycle_values options/sub-text-shadow-offset "5" "5" ; no-osd cycle_values options/osd-font "Arial" "Arial" ; no-osd cycle_values options/osd-color "#dadada" "#dadada" ; no-osd cycle_values options/osd-border-size "0" "0"; no-osd cycle_values options/osd-shadow-offset "5" "5" ; no-osd cycle_values options/ass-style-override "force" "force" ; cycle_values options/sub-shadow-color "1.0/0.0/0.0" "#FF0000"`

This isn't working for me, however. I must be doing something very silly, but the sub-shadow-color property is not recognized.

**Comment by lachs0r** [comment]
That just means your version of mpv is older than the current release (these options got renamed recently). Also, since you’re not cycling through a list of values, you could use `set` instead, and in recent mpv, the `options/` prefix is no longer necessary.
