### ISSUE TITLE
mpv on macOS should always set devicePixelRatio to 1

### ISSUE THREAD

**Issue by steve3d** [mpv-player/mpv#3716]
### macOS Sierra 10.12.0 and mpv 0.20 & 0.21

first of all, thanks for make such a good player. I'm using mpv under mac, and I have 4K screen, under mac, the player automatically use retina display for ui and video, this means if I'm playing a 720p video, mpv would render its default size as twice size of 720p, which is 2560x1440 pixels on screen, which is acceptable, but if I'm playing a 1080p video, the mpv window actually takes the whole screen of my 4K screen, and of course, if I play a 4K video, the default video size only shows 1/4 of video on my 4K screen, this seems too wired. which means I have to use 1/2 size of video to play a 4K video on my 4K screen.

So I think under mac, mpv should always set  devicePixelRatio to 1 for the player window, so no matter user use a retina monitor or a normal monitor, the video would always rendered as 1:1 pixel to screen.

I hope I've made myself clear, mpv should always set devicePixelRatio to 1 no matter the how the dpi scale settings.

**Comment by wm4** [comment]
Feature, not a bug.

CC @pigoz

**Comment by pigoz** [comment]
Yes, this is the intended behaviour, and afaik pretty much all video players behave like this (VLC, Apple's own QuickTime).

That said if someone contributes a patch to make this configurable we will review it and most likely accept it.

**Comment by lachs0r** [comment]
Also, you can avoid the 4K situation by using the [--autofit-larger option](https://mpv.io/manual/master/#options-autofit-larger).

**Comment by steve3d** [comment]
But windows don't have this problem, under windows, mpv always use native dpi without scaling.

**Comment by Akemi** [comment]
@steve3d i dunno why you expect macOS to work the same way as windows. this is not a problem this is just how macOS sizing works, using backing scale factor dependent [points](https://developer.apple.com/library/content/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Explained/Explained.html) instead of pixels for sizes and measurements. 

anyway here is an option to circumvent the default macOS behaviour. i wasn't really sure how to name it and if i did the option handling properly. i will open a PR if this is fine.

**Comment by steve3d** [comment]
@pigoz, maybe that's why quicktime has stopped development over 2 years. haha

**Comment by bodayw** [comment]
Well...Just saw the new commit today, but adding ``window-scale=0.5`` in the config file should do the trick, right? I see no point adding a particular option just for this.

**Comment by Akemi** [comment]
no read the my second comment on PR #3725. short answer, that would make the window half the size on none-HiDPI resolutions too.

**Comment by bodayw** [comment]
Ah I see. So this will be useful for somebody using multiple screens with different DPI settings, e.g. a HiDPI MacBook with an external normal DPI display.

**Comment by Akemi** [comment]
kinda. it's just for those who consistently want the window to open in the pixel size and not in points, using as little scaling as possible from mpv.

**Comment by galaxy001** [comment]
If I set window-scale=21/32 for 13" or window-scale=2/3 for 15" when using maximum resolution, will mpv render the video in a pixel-to-pixel way ?

Or will mpv just resize down the video and then the Mac OS resize up back the video ?

**Comment by Akemi** [comment]
MacOS doesn't resize the video. if you use the hidpi flag the window will be rendered in the scale you set pixel-by-pixel. without the flag it will it will use points, eg the window has double the pixel size of what you set, but mpv still does the resizing. 

the only thing that can happen is that MacOS ill resize the whole desktop depending on your scale settings in your system preferences.

**Comment by bodayw** [comment]
Seems there is still kind of a cosmetic issue with the current implementation: on my retina MBP, mpv 0.22.0 with ``--no-hidpi-window-scale``, the window created is always positioned on the bottom left part of the screen, instead of in the middle.

**Comment by Akemi** [comment]
yep, i planned to take care of that with issue #3867.

**Comment by MacDragon** [comment]
Hmm, is there any combination of options that would preserve the 'GUI' controlbar at 'full' display scaling size, but default the video to pixel scaling to display?, as on a '1920x1200' scaled display on a 15" macbook the controls get a bit tiny after setting no-hidpi-window-scale! but I do dislike having to resize down every time open a video, I always prefer them to be pixel patched rather than 'display' matched.

**Comment by Akemi** [comment]
you just want the OSC to be bigger? create a `lua-settings/osc.conf` in the mpv config directory and add following settings. one is for scaling the OSC in windowed and one in fullscreen. default is 1.0, 2.0 should be what you want. though you can change it to any other value you like.

```
scalewindowed=2.0
scalefullscreen=2.0
```

**Comment by MacDragon** [comment]
Ah, yes, thanks! That seems to do the job nicely on laptop display at least.

I presume if I run it on an external non hidpi screen it might now look too big as a result? though admittedly most of time that might happen will be on a tv, and being big there shouldn't hurt anyway.

**Comment by Akemi** [comment]
it doesn't appear bigger if the visual window size is the same.
