### ISSUE TITLE
Correct escaping of : in IPC

### ISSUE THREAD

**Issue by FDMX2** [mpv-player/mpv#3717]
### mpv 0.21

I remotely control mpv via JSON IPC and want open videos with external audio tracks.
When starting mpv the first time with
`mpv --audio-file=http://127.0.0.1:1/ "http://127.0.0.1:2/"`
everything works as expected.

With JSON IPC i want to use the same command like:
`{"command" : ["loadfile" , "http://127.0.0.1:2", "replace", "audio-file=http://127.0.0.1:1"] }`
which is not working because of the `:` chars in the audio-file option. The only output from mpv is:
`[ipc_0] Command loadfile: argument 3 can't be parsed: option could not be parsed.`
 Audiofiles which can be addressed without `:` work fine this way.

Other options like `title` show the same behavior if the value contains a `:` char.
Escaping with %n% as supposed in [Escaping spaces and other special characters](https://mpv.io/manual/master/#escaping-spaces-and-other-special-characters) does not help here. 

So how to correctly escape `:` here ?

**Comment by Idlusen** [comment]
Try `"audio-file=\"http://127.0.0.1:1\""` for argument 3?

**Comment by FDMX2** [comment]
Ok, my bad, i just tried it with inner ' '.

Thanks, your suggestion works perfectly.
