### ISSUE TITLE
--window-size broken when using per-file markers

### ISSUE THREAD

**Issue by Bergfried** [mpv-player/mpv#3724]
The `--window-size` option does not work properly with `--{` and `--}` anymore. Only the very first encounter of `--window-scale` will be accepted but applied to *all* files, regardless of whether they are enclosed by the same per-file markers or not. Any subsequent encounter of `--window-scale` while playing will result in an

    Error parsing option window-scale (option could not be parsed)

and will be rejected. Even `--loop` with only one file will do that as soon as the file is being played more than once. Examples:

    mpv '--{' --window-scale=0.5 somefile '--}' '--{' --window-scale=0.25 otherfile '--}'
    mpv --loop '--{' --window-scale=0.5 somefile '--}'

Using mpv 0.21.

**Comment by wm4** [comment]
This happens because at the time of setting the second option there is a window, but no video size known, so it's rejected.

**Comment by Bergfried** [comment]
Thank you very much.
