### ISSUE TITLE
OSC too squashed by default for portrait videos

### ISSUE THREAD

**Issue by sammoth** [mpv-player/mpv#3728]
The new OSC doesn't seem to scale down gracefully for portrait videos, regardless of the `vidscale` setting. In particular the text overlaps and the seekbar is hidden. The text in the previous OSC became unreadable in this situation but the controls were all still usable.

![2016-10-26-11 30 31 420746873](https://cloud.githubusercontent.com/assets/3324352/19722754/13e2d57c-9b70-11e6-8062-9ad532e1d56f.png)

**Comment by wiiaboo** [comment]
Fixed in 993466fc30e5a1a257778ccff283a8e31812206f
