### ISSUE TITLE
New pseudo-GUI not intuitively usable, doesn't scale

### ISSUE THREAD

**Issue by kaymio** [mpv-player/mpv#3730]
### mpv version and platform
mpv 1:0.21.0-1 on Arch Linux AMD64

### Reproduction steps
New "pseudo" gui doesn't scale to full visibility or functionality, not in full screen 1920x1200 and not in vertically 50:50 split screen, nor any other configuration

### Expected behavior
Being able to see the full content of the info as well as being able to use the functions given bij the pseudo-gui in most usual window alignments (like 25% per corner, 50% screen split vertically or horizontally)

### Actual behavior
![bildschirmfoto vom 2016-10-26 19-48-17](https://cloud.githubusercontent.com/assets/22966929/19738155/9b553428-9bb6-11e6-8cb5-d0df62fecd87.png)
![bildschirmfoto vom 2016-10-26 19-58-33](https://cloud.githubusercontent.com/assets/22966929/19738156/9b57169e-9bb6-11e6-9782-3f629f36ceb2.png)

### Wanted behavior

Be able to scale the fonts of the pseudo-gui in the ~/.config/mpv/mpv.conf or an extra conf file.

### Log file

[cplayer] Command line options: '-v' 'https://www.youtube.com/watch?v=loryKeOPKto'
[cplayer] mpv 0.21.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Thu Oct 20 08:19:09 CEST 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.28.100
[cplayer]    libavcodec      57.48.101
[cplayer]    libavformat     57.41.100
[cplayer]    libswscale      4.1.100
[cplayer]    libavfilter     6.47.100
[cplayer]    libswresample   2.1.100
[cplayer] ffmpeg version: 3.1.4
[cplayer]
[cplayer] Configuration: ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-encoding --enable-libmpv-shared --enable-zsh-comp
[cplayer] List of enabled features: alsa any-gl asm atomics audio-input av-avpacket-int64-duration av-new-pixdesc av-pix-fmt-mmal av-subtitle-nopict av-version-info avcodec-chroma-pos-api avcodec-has-codecpar avcodec-new-codec-api avcodec-
profile-name avframe-metadata avframe-skip-samples avutil-has-hwcontext avutil-hdr avutil-mastering-metadata build-date c11-tls caca cdda cplayer debug-build dlopen drm dvbin dvdnav dvdread egl-drm egl-helpers egl-x11 enca encoding fchmod
gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob gnuc iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libbluray libdl libm libmpv-shared librt libsmbclient libswresample libv4l2 linux-fstatfs lua nanosleep optimi
ze oss-audio oss-audio-native plain-gl posix posix-or-mingw posix-spawn pthreads pulse resampler rubberband shm sse4-intrinsics standard-gl stdatomic subprocess termios tv tv-v4l2 vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-hwaccel vaapi-way
land vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h wayland x11 xext xinerama xrandr xss xv zlib zsh-comp
[global] config path: '' -> '/home/psilo/.config/mpv'
[global] config path: 'mpv.conf' -> '/home/psilo/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/psilo/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/home/psilo/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/psilo/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/etc/mpv/config'
[cplayer] Reading config file /home/psilo/.config/mpv/mpv.conf
[cplayer] Setting option 'keep-open' = 'yes' (flags = 4)
[cplayer] Setting option 'hwdec' = 'auto' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -> '/home/psilo/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/home/psilo/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/etc/mpv/input.conf'
[global] user path: '/home/psilo/.config/mpv/input.conf' -> '/home/psilo/.config/mpv/input.conf'
[ifo] Opening /home/psilo/.config/mpv/input.conf
[ifo/dvdnav] Opening /home/psilo/.config/mpv/input.conf
[bdmv/bluray] Opening /home/psilo/.config/mpv/input.conf
[file] Opening /home/psilo/.config/mpv/input.conf
[file] Stream opened successfully.
[input] Parsing input config file /home/psilo/.config/mpv/input.conf
[input] Input config file /home/psilo/.config/mpv/input.conf parsed: 4 binds
[osc] Loading script @osc.lua...
[global] config path: 'scripts' -/-> '/home/psilo/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/home/psilo/.mpv/scripts'
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] config path: 'lua-settings/osc.conf' -/-> '/home/psilo/.config/mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/home/psilo/.mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/etc/mpv/lua-settings/osc.conf'
[osc] lua-settings/osc.conf not found.
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[cplayer] mouse_leave script-binding osc/__keybinding2
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[cplayer] mouse_btn2 script-binding osc/__keybinding5
[cplayer] mouse_btn0_dbl ignore
[cplayer] shift+mouse_btn0_dbl ignore
[cplayer] mouse_btn2_dbl ignore
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[input, ]
[cplayer] Run command: define-section, flags=0, args=[input_osc, del script-binding osc/__keybinding6
[cplayer] , default]
[cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading script @ytdl_hook.lua...
[global] config path: 'scripts' -/-> '/home/psilo/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/home/psilo/.mpv/scripts'
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'
[ytdl_hook] loading mp.defaults
[cplayer] Run command: disable-section, flags=0, args=[input]
[global] config path: 'fonts' -/-> '/home/psilo/.config/mpv/fonts'
[global] config path: 'fonts' -/-> '/home/psilo/.mpv/fonts'
[global] config path: 'fonts' -/-> '/etc/mpv/fonts'
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.3.2 (COMPLEX)
[global] config path: 'subfont.ttf' -/-> '/home/psilo/.config/mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/home/psilo/.mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/etc/mpv/subfont.ttf'
[global] config path: 'fonts.conf' -/-> '/home/psilo/.config/mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/home/psilo/.mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/etc/mpv/fonts.conf'
[osd/libass] Setting up fonts...
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[cplayer] Run command: hook-add, flags=0, args=[on_preloaded, 2, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] config path: 'scripts' -/-> '/home/psilo/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/home/psilo/.mpv/scripts'
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'
[global] config path: 'watch_later' -> '/home/psilo/.config/mpv/watch_later'
[cplayer] Playing: https://www.youtube.com/watch?v=loryKeOPKto
[cplayer] Running hook: ytdl_hook/on_load
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[global] config path: 'youtube-dl' -/-> '/home/psilo/.config/mpv/youtube-dl'
[global] config path: 'youtube-dl' -/-> '/home/psilo/.mpv/youtube-dl'
[global] config path: 'youtube-dl' -/-> '/etc/mpv/youtube-dl'
[ytdl_hook] youtube-dl succeeded!
[cplayer] Run command: audio-add, flags=0, args=[https://r10---sn-5hne6ne6.googlevideo.com/videoplayback?id=968af229e38f2ada&itag=251&source=youtube&requiressl=yes&nh=IgpwcjA0LmFtczE1KgkxMjcuMC4wLjE&mn=sn-5hne6ne6&initcwndbps=547500&pl=24&
ms=au&mv=m&mm=31&ratebypass=yes&mime=audio/webm&gir=yes&clen=22404185&lmt=1472865358274525&dur=1425.141&signature=6E17CFEA3FFB02B4275C425C3C654BCF27E7FC8A.3535DFAD3AC1267C9799077D8A740AAE71361115&key=dg_yt0&upn=pxpTiBO3L-M&mt=1477504655&ip
=213.152.161.181&ipbits=0&expire=1477526414&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,mn,initcwndbps,pl,ms,mv,mm,ratebypass,mime,gir,clen,lmt,dur, select, DASH audio, ]
[ffmpeg] Opening https://r10---sn-5hne6ne6.googlevideo.com/videoplayback?id=968af229e38f2ada&itag=251&source=youtube&requiressl=yes&nh=IgpwcjA0LmFtczE1KgkxMjcuMC4wLjE&mn=sn-5hne6ne6&initcwndbps=547500&pl=24&ms=au&mv=m&mm=31&ratebypass=yes&
mime=audio/webm&gir=yes&clen=22404185&lmt=1472865358274525&dur=1425.141&signature=6E17CFEA3FFB02B4275C425C3C654BCF27E7FC8A.3535DFAD3AC1267C9799077D8A740AAE71361115&key=dg_yt0&upn=pxpTiBO3L-M&mt=1477504655&ip=213.152.161.181&ipbits=0&expire
=1477526414&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,mn,initcwndbps,pl,ms,mv,mm,ratebypass,mime,gir,clen,lmt,dur
[ffmpeg] Mime-type: 'audio/webm'
[ffmpeg] Stream opened successfully.
[cache] no backbuffer needed
[cache] Cache size set to 21911 KiB (32 KiB backbuffer)
[demux] Trying demuxers for level=normal.
[mkv] Found the head...
[mkv] + a segment...
[mkv] Parsing seek head...
[mkv] |+ segment information...
[mkv] | + muxing app: google
[mkv] | + writing app: google
[mkv] | + timecode scale: 1000000
[mkv] | + duration: 1425.141s
[mkv] |+ segment tracks...
[mkv] | + a track...
[mkv] |  + Track number: 1
[mkv] |  + Track type: Audio
[mkv] |  + Audio track
[mkv] |   + Sampling frequency: 48000.000000
[mkv] |   + Channels: 2
[mkv] |  + Codec ID: A_OPUS
[mkv] |  + CodecPrivate, length 19
[mkv] Parsing cues...
[mkv] |+ found cluster
[mkv] All headers are parsed!
[demux] Detected file format: Matroska
[cache] blocking for STREAM_CTRL 6
[cplayer] Set property: stream-open-filename="https://r10---sn-5hne6ne6.googlevideo.com/videoplayback?id=968af229e38f2ada&itag=136&source=youtube&requiressl=yes&nh=IgpwcjA0LmFtczE1KgkxMjcuMC4wLjE&mn=sn-5hne6ne6&initcwndbps=547500&pl=24&ms=
au&mv=m&mm=31&ratebypass=yes&mime=video/mp4&gir=yes&clen=240447222&lmt=1472851291438865&dur=1425.133&signature=34B5592750135955A4E74004E2E7BFA032F0F635.3DC3C7F89E0F477F06006F4300F86E7CF561EFC8&key=dg_yt0&upn=pxpTiBO3L-M&mt=1477504655&ip=21
3.152.161.181&ipbits=0&expire=1477526414&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,mn,initcwndbps,pl,ms,mv,mm,ratebypass,mime,gir,clen,lmt,dur" -> 1
[cplayer] Set property: file-local-options/force-media-title="Keynote: Beyond Measure: The True Power and Skill of Collaboration by Dr. Margaret Heffernan" -> 1
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[ffmpeg] Opening https://r10---sn-5hne6ne6.googlevideo.com/videoplayback?id=968af229e38f2ada&itag=136&source=youtube&requiressl=yes&nh=IgpwcjA0LmFtczE1KgkxMjcuMC4wLjE&mn=sn-5hne6ne6&initcwndbps=547500&pl=24&ms=au&mv=m&mm=31&ratebypass=yes&
mime=video/mp4&gir=yes&clen=240447222&lmt=1472851291438865&dur=1425.133&signature=34B5592750135955A4E74004E2E7BFA032F0F635.3DC3C7F89E0F477F06006F4300F86E7CF561EFC8&key=dg_yt0&upn=pxpTiBO3L-M&mt=1477504655&ip=213.152.161.181&ipbits=0&expire
=1477526414&sparams=ip,ipbits,expire,id,itag,source,requiressl,nh,mn,initcwndbps,pl,ms,mv,mm,ratebypass,mime,gir,clen,lmt,dur
[ffmpeg] Mime-type: 'video/mp4'
[ffmpeg] Stream opened successfully.
[cache] Cache size set to 150000 KiB (75000 KiB backbuffer)
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[lavf] avformat_find_stream_info() finished after 106710 bytes.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[cache] blocking for STREAM_CTRL 6
[global] config path: 'sub/' -/-> '/home/psilo/.config/mpv/sub/'
[global] config path: 'sub/' -/-> '/home/psilo/.mpv/sub/'
[global] config path: 'sub/' -/-> '/etc/mpv/sub/'
[global] config path: 'audio/' -/-> '/home/psilo/.config/mpv/audio/'
[global] config path: 'audio/' -/-> '/home/psilo/.mpv/audio/'
[global] config path: 'audio/' -/-> '/etc/mpv/audio/'
[cplayer] Running hook: ytdl_hook/on_preloaded
[cplayer] Run command: hook-ack, flags=0, args=[on_preloaded]
[cplayer]  (+) Video --vid=1 (*) (h264)
[cplayer]  (+) Audio --aid=1 --alang=eng (*) 'DASH audio' (opus) (external)
[vo/opengl] Initializing OpenGL backend 'wayland'
[vo/opengl/wayland] failed to connect to a wayland server: check if a wayland compositor is running
[vo/opengl] Initializing OpenGL backend 'x11probe'
[vo/opengl/x11] X11 opening display: :0
[vo/opengl/x11] X11 running at 1920x1200 (":0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Display 0 (DP-1): [0, 0, 1920, 1200] @ 59.950171 FPS
[vo/opengl/x11] Current display FPS: 59.950171
[vo/opengl] GLX chose FB config with ID 0xa846cb90
[vo/opengl] GLX chose visual with ID 0x27
[vo/opengl] Creating OpenGL 3.3 context...
[vo/opengl] GL_VERSION='3.3.0 NVIDIA 370.28'
[vo/opengl] Detected desktop OpenGL 3.3.
[vo/opengl] GL_VENDOR='NVIDIA Corporation'
[vo/opengl] GL_RENDERER='GeForce GTX 660/PCIe/SSE2'
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='3.30 NVIDIA via Cg compiler'
[vo/opengl] Loaded extension GLX_SGI_swap_control.
[vo/opengl] Loaded extension GLX_SGI_video_sync.
[vo/opengl] Loaded extension GL_NV_vdpau_interop.
[vo/opengl] Loaded extension GL_ARB_debug_output.
[vo/opengl] 16 bit texture depth: 16.
[vo/opengl] Reported display depth: R=8, G=8, B=8
[vo/opengl] Testing FBO format 0x805b
[vo/opengl] Create FBO: 16x16 (16x16)
[vo/opengl] Using FBO format 0x805b.
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Loading hwdec driver 'vaapi-egl'
[vo/opengl] Loading failed.
[vo/opengl] Loading hwdec driver 'vaapi-glx'
[vo/opengl/vaapi-glx] Not using this by default.
[vo/opengl] Loading failed.
[vo/opengl] Loading hwdec driver 'vdpau-glx'
[vo/opengl] Assuming 59.950171 FPS for display sync.
[vd] Container reported FPS: 30.000000
[vd] Codec list:
[vd]     lavc:h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd] Opening video decoder lavc:h264
[vd] Probing 'vdpau'...
[vd] Trying hardware decoding.
[vd] Selected video codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [lavc:h264]
[ad] Codec list:
[ad]     lavc:opus - Opus
[ad]     lavc:libopus (opus) - libopus Opus
[ad] Opening audio decoder lavc:opus
[ad] Requesting 1 threads for decoding.
[ad] Selected audio codec: Opus [lavc:opus]
[cplayer] Starting playback...
[vo/opengl/x11] Disabling screensaver.
[af] Audio filter chain:
[af]   [in] 48000Hz stereo 2ch floatp
[af]   [out] 48000Hz stereo 2ch floatp
[af]   [ao] 48000Hz stereo 2ch floatp
[ao] Trying audio driver 'pulse'
[ao/pulse] requested format: 48000 Hz, stereo channels, floatp
[ao/pulse] Library version: 9.0.0
[ao/pulse] Proto: 31
[ao/pulse] Server proto: 4294967295
[ao/pulse] Channel layouts:
[ao/pulse]  - #fl
[ao/pulse]  - #fr
[ao/pulse]  - #fc
[ao/pulse]  - #lfe
[ao/pulse]  - #bl
[ao/pulse]  - #br
[ao/pulse]  - #flc
[ao/pulse]  - #frc
[ao/pulse]  - #bc
[ao/pulse]  - #sl
[ao/pulse]  - #sr
[ao/pulse]  - #tc
[ao/pulse]  - #tfl
[ao/pulse]  - #tfc
[ao/pulse]  - #tfr
[ao/pulse]  - #tbl
[ao/pulse]  - #tbc
[ao/pulse]  - #tbr
[ao/pulse] result: stereo
[ao/pulse] device buffer: 6000 samples.
[ao/pulse] using soft-buffer of 9600 samples.
[cplayer] AO: [pulse] 48000Hz stereo 2ch float
[cplayer] AO: Description: PulseAudio audio output
[af] Adding filter lavrresample
[af] Audio filter chain:
[af]   [in] 48000Hz stereo 2ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch float [a]
[af]   [out] 48000Hz stereo 2ch float
[af]   [ao] 48000Hz stereo 2ch float
[vd] Pixel formats supported by decoder: vdpau vaapi_vld yuv420p
[vd] Codec profile: Main (0x4d)
[vo/opengl/x11] Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.
[vd] Using hardware decoding (vdpau).
[vd] Decoder format: 1280x720 vdpau[nv12] bt.709/limited CL=mpeg2/4/h264
[vf] Video filter chain:
[vf]   [in] 1280x720 vdpau[nv12] bt.709/limited CL=mpeg2/4/h264
[vf]   [out] 1280x720 vdpau[nv12] bt.709/limited CL=mpeg2/4/h264
[cplayer] VO: [opengl] 1280x720 vdpau
[cplayer] VO: Description: Extended OpenGL Renderer
[vo/opengl/x11] not waiting for MapNotify
[vo/opengl] Resize: 1280x720
[vo/opengl] Window size: 1280x720
[vo/opengl] Video source: 1280x720 (1:1)
[vo/opengl] Video display: (0, 0) 1280x720 -> (0, 0) 1280x720
[vo/opengl] Video scale: 1.000000/1.000000
[vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[vo/opengl] Video borders: l=0 t=0 r=0 b=0
[vo/opengl] Testing FBO format 0x805b
[vo/opengl] Create FBO: 16x16 (16x16)
[vo/opengl] Using FBO format 0x805b.
[vo/opengl] No advanced processing required. Enabling dumb mode.
[cplayer] set video colors output-levels=0
[vo/opengl] Create FBO: 1280x720 (1280x720)
[vo/opengl] recompiling a shader program:
[vo/opengl] [  1] color = fract(gl_FragCoord.y / 2) < 0.5
[vo/opengl] [  2]       ? texture(texture0, texcoord0)
[vo/opengl] [  3]       : texture(texture1, texcoord1);
[vo/opengl] Create FBO: 640x360 (640x360)
[vo/opengl] recompiling a shader program:
[vo/opengl] [  1] color.r = 1.000000 * vec4(texture(texture0, texcoord0)).r;
[vo/opengl] [  2] color.gb = 1.000000 * vec4(texture(texture1, texcoord1)).rg;
[vo/opengl] [  3] // color conversion
[vo/opengl] [  4] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[vo/opengl] [  5] color.a = 1.0;
[vo/opengl] [  6] // color mapping
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, DejaVuSans
[cplayer] first video frame after restart shown
[cplayer] starting audio playback
[cplayer] playback restart complete
[statusline] AV: 00:00:05 / 00:23:45 (0%) A-V:  0.000 Cache: 10s+13MB
[vo/opengl] Resize: 959x1150
[vo/opengl] Window size: 959x1150
[vo/opengl] Video source: 1280x720 (1:1)
[vo/opengl] Video display: (0, 0) 1280x720 -> (0, 305) 959x539
[vo/opengl] Video scale: 0.749219/0.748611
[vo/opengl] OSD borders: l=0 t=305 r=0 b=306
[vo/opengl] Video borders: l=0 t=305 r=0 b=306
[statusline] AV: 00:00:07 / 00:23:45 (0%) A-V:  0.000 Cache: 10s+17MB
[cplayer] Run command: sub-seek, flags=8, args=[1]
[statusline] AV: 00:00:07 / 00:23:45 (0%) A-V:  0.000 Cache: 10s+18MB
[cache] EOF reached.
[statusline] AV: 00:00:22 / 00:23:45 (1%) A-V:  0.000 Cache: 10s+51MB
[cplayer] Run command: sub-seek, flags=8, args=[-1]
[statusline] AV: 00:00:34 / 00:23:45 (2%) A-V:  0.000 Cache: 10s+73MB
[cplayer] Run command: quit, flags=9, args=[4]
[cplayer] EOF code: 6
[ad] Uninit audio decoder.
[af] Removing filter lavrresample
[vd] Uninit video.
[cache] Terminating cache...
[cache] Cache exiting...
[cache] Terminating cache...
[cache] Cache exiting...
[vo/opengl/x11] Enabling screensaver.
[cplayer] finished playback, success (reason 3)
[cplayer]
[cplayer]
[cplayer] Exiting... (Quit)
[ytdl_hook] Exiting...
[osc] Exiting...
[ao/pulse] draining...
[vo/opengl] flushing shader cache
[vo/opengl/x11] uninit ...

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wiiaboo** [comment]
Duplicate of https://github.com/mpv-player/mpv/issues/3728.
