### ISSUE TITLE
Moving the OSD with an input

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3734]
How would I go about doing this? The function to set its position is there, but I need a way to update it live. Something like

`Ctrl+O set osd-margin-x "-1"`

so it moves 1 unit to the right (or left, not sure) every time I press Ctrl+O.

**Comment by garoto** [comment]
This maybe?

`Ctrl+o 		add osd-margin-x +1
Ctrl+i 		set osd-margin-x -1`

**Comment by firewater2** [comment]
YES! Thanks.

**Comment by garoto** [comment]
Glad I could help. You may close this issue now btw :)

**Comment by firewater2** [comment]
Oh, I always thought it needed to be closed by someone with higher powers or something, thanks for that too!
