### ISSUE TITLE
seekbar [with OSC slimbox layout]

### ISSUE THREAD

**Issue by sh3rry** [mpv-player/mpv#3737]
with style of the seekbar --> bar (fill)
White strip  is  out of the progress bar range when using layout  ”slimbox“ ,sometimes looks ugly。

**Comment by sh3rry** [comment]
possible use rounded corners

**Comment by sh3rry** [comment]
![image](https://cloud.githubusercontent.com/assets/9400373/19758170/75d74846-9c59-11e6-853f-29927edb3fae.png)

**Comment by wiiaboo** [comment]
@ChrisK2 I assume rounded corners for the seekbar are still expensive? (can't remember where I read this)

**Comment by sh3rry** [comment]
isn't a bad idea, either  :)

**Comment by sh3rry** [comment]
@wiiaboo | isn't a bad idea, either

**Comment by skeletonhands** [comment]
How about just remove the rounded corners? Make it something like this instead: 
![image](https://cloud.githubusercontent.com/assets/22690608/19789081/6ed317b2-9cb5-11e6-860a-a243de58552d.png)

**Comment by wiiaboo** [comment]
I'd prefer something like https://github.com/mpv-player/mpv/issues/2365 with slimbox.

**Comment by firewater2** [comment]
I'm gonna jump on this and ask if it's possible to remove the chapter markets from the bar?

**Comment by ChrisK2** [comment]
> I assume rounded corners for the seekbar are still expensive to render?

Yes. And will always be, at least with the current way the OSC works.

> So a likely fix in time for 0.21.1 would be ...

No no, don't touch this. This layout should only be used together with ``seekbarstyle=slider``. If you make those changes you'll ruin the look of ``slider`` (unless the changes only apply when using ``bar``.

> I'm gonna jump on this and ask if it's possible to remove the chapter markets from the bar?

No.
