### ISSUE TITLE
 dxva2 issue on windows 7

### ISSUE THREAD

**Issue by kopineko** [mpv-player/mpv#3738]
### mpv version and platform
```
mpv 0.21.0-git-e6b85c9 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Oct 20 02:56:27 CEST 2016
ffmpeg library versions:
   libavutil       55.32.100
   libavcodec      57.63.103
   libavformat     57.52.100
   libswscale      4.1.100
   libavfilter     6.64.100
   libswresample   2.2.100
ffmpeg version: N-82050-gd3b352c
```
Windows7x64 Service Pack 1
### Reproduction steps
Playing any H.264 files via dxva2 or dxva2-copy, other formats not tested.
### Expected behavior
Playing correctly.
### Actual behavior
![mpv-shot0133](https://cloud.githubusercontent.com/assets/272386/19767993/ec63be6c-9c6e-11e6-9dd1-6195fd916d6b.jpg)
### Log file
http://pastebin.com/uLjy9PUa
### Sample files
Not needed.

**Comment by lachs0r** [comment]
Does this work with other players (make sure they really are using DXVA2)?
I’m pretty sure this is just Intel screwing up.

**Comment by shinchiro** [comment]
not really intel bug but with current ffmpeg git it was built

**Comment by lachs0r** [comment]
You mean it was fixed in FFmpeg? Is it [this commit](https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/8bd38ec5bde1d2691d6385975a2bad61538188bf)?

**Comment by shinchiro** [comment]
Probably as I dont have this issue when I built on 23rd

**Comment by lachs0r** [comment]
@kopineko does [this build](https://0x0.st/e4W.7z) fix it for you?

**Comment by kopineko** [comment]
@lachs0r 
Yes, now everything is working fine.
Thanks.

**Comment by lachs0r** [comment]
Okay, then the next release will contain this fix.
