### ISSUE TITLE
Crash Without (Obvious) Error On a Particular File

### ISSUE THREAD

**Issue by dasime** [mpv-player/mpv#3740]
MPV doesn't seem to be able to open the attached file. This file works fine in MPC-HC (CCCP 2015-10-18).

### mpv version and platform

Windows 7 64-bit

mpv-x86_64-20150302 (mpv 0.16.0-git-8eaef74)
mpv-x86_64-20161020 (mpv 0.21.0-git-e6b85c9)
(both lachs0r's builds)

### Reproduction steps

Attempt to play the sample file.

### Expected behaviour

The video should play (hurr).

#### mpv-x86_64-20150302
When launched from cmd.exe it opens the MPV window for about 10 seconds before popping up with a blank _Microsoft Visual C++ Runtime Library_ window.
When MPV is launched in pseudo GUI mode and the file is dragged onto the window MPV waits for about 10 seconds before popping up with a _Microsoft Visual C++ Runtime Library_ window that says:

>This application has requested the Runtime to terminate it in an unusual way.
>Please contact the application's support team for more information.

#### mpv-x86_64-20161020
When launched from cmd.exe the MPV window does not appear.
When launched in pseudo GUI mode and the file is dragged onto the window MPV waits for about 10 seconds and quits without saying anything.

For both releases the memory MPV is consuming steadily climbs to ~1.2 GB before the MPV process ends.

### Log file

It appears MPV gets in a loop and the log is 32 MB so I've uploaded it here:

https://0x0.st/eyB.txt

### Sample files

I clipped the file with mkvmerge to a 15 MB sample. This sample seems to reproduce the issue in the same way and also plays fine in MPC-HC (CCCP 2015-10-18).

https://0x0.st/eyM.mkv

**Comment by sda89ha9** [comment]
try --demuxer=lavf or --no-ordered-chapters

**Comment by dasime** [comment]
I can confirm both of those flags mean MPV successfully plays this file. However, both of them just disable ordered-chapters so they're not very practical to set globally. I've just tested on a few differently muxed MKV files with OCs and OCs otherwise work fine in MPV without these options.

**Comment by wm4** [comment]
Sample file doesn't "crash" or freeze with git master.

**Comment by dasime** [comment]
What an incredible coincidence! This issue has existed for at least a year and by the time I get effected by it it gets fixed in master three days earlier in 3a78eef and 18681a7.

My seven day old build just wasn't quite new enough, haha.
