### ISSUE TITLE
Set playback speed to 100%

### ISSUE THREAD

**Issue by JonnyTech** [mpv-player/mpv#3741]
There are keyboard shortcuts to increase and decrease the playback speed but not to reset it back to normal ie 100% (VLC uses the equal sign "=" as default). Is this an easy request to implement?

**Comment by AirPort** [comment]
Backspace does already that by default AFAIK.

**Comment by wiiaboo** [comment]
https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L69
BS stands for backspace.
