### ISSUE TITLE
[feature request] Make subtitles background to look like the youtube's one.

### ISSUE THREAD

**Issue by githubuser135** [mpv-player/mpv#3743]
# From this:

![b](https://cloud.githubusercontent.com/assets/22780789/19813108/987ae314-9d38-11e6-96ab-57b31c087767.png)
# To this:

![a](https://cloud.githubusercontent.com/assets/22780789/19813121/9ce9e6de-9d38-11e6-9d66-96ce5b25958a.PNG)

**Comment by garoto** [comment]
Check these manual entries:

https://mpv.io/manual/master/#options-sub-color
https://mpv.io/manual/master/#options-sub-back-color
