### ISSUE TITLE
RadeonHD GPU eventually stalls with vdpau on mesa's radeonsi

### ISSUE THREAD

**Issue by John-Gee** [mpv-player/mpv#3745]
I originally thought the issue came from something new in the graphic stack, but after bisecting mesa and using old kernels, I still had the issue so I tried bisecting mpv instead and the issue went away.
It might still be a problem in the graphic stack though so please join us in the fdo bug at:
https://bugs.freedesktop.org/show_bug.cgi?id=98271
### mpv version and platform

Platform: Linux x86_64
mpv version: started at commit 6b22b216514ee2eb784711f4539410d3b312a4fd onwards latest release (1.0.21).
### Reproduction steps

The issue seems to happen when I quickly go back and forth (up and down arrows) while watching a video using -hwdec vdpau either with -vo opengl(hq) or -vo vdpau, I haven't seen it using -vo xv.

script used to bisect: https://gist.github.com/John-Gee/85d61999c73bab5b3c723a5141ea20d3
### Expected behavior

Video seeking for hours with nothing wrong happening.
### Actual behavior

The screen will eventually freeze, then go dark, then the computer freezes.

If I wait for mpv's OSD to disappear before pressing an arrow again, I don't seem to get the issue, but that may just be because then I do less seeking.
### Log file

https://gist.github.com/John-Gee/eb30fc6b0a9f5931989a591d02543741
### Sample files

I've been using mkv files with x264 videos, not sure if it matters though, but I guess it should be a video codec supported by my GPU decoder (RadeonHD 280X).

**Comment by haasn** [comment]
Shouldn't this be a mesa bug report?

**Comment by John-Gee** [comment]
Well, like you I would think the fix should come from mesa, but I don't know enough to say, so I thought it'd be better to have devs from both sides discussing it, similarly to the AA bug happening in mesa as well (https://bugs.freedesktop.org/show_bug.cgi?id=97988). I linked my mesa bug report at the top of this one.

Thank you!

**Comment by paulguy** [comment]
If it's hanging up computers, it's a kernel bug.  I would say it's not a userland process's responsibility to avoid locking up someone's computer,, especially when other drivers work just fine without doing so.
