### ISSUE TITLE
mpv crashes on latest git master

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#3748]
### mpv version and platform

mpv HEAD-90b968a_1, macOS Sierra 10.12.1
### Reproduction steps

Play a video from the command line.
### Expected behavior

Video plays normally.
### Actual behavior

mpv crashes, saying symbol _gliCreateContextWithShared not found.
### Log file

The log file ends just before the error message : http://sprunge.us/STbG
The actual error message : 

dyld: lazy symbol binding failed: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

dyld: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

[1]    81430 abort      mpv  --log-file=output.txt

**Comment by wm4** [comment]
This is probably a broken build or a driver issue? Anyway, certainly not a mpv issue.

**Comment by kkanungo17** [comment]
Forgot to mention this, but selecting mpv as default player and opening a file works fine. The problem is only in the command line.

**Comment by kevmitch** [comment]
> Forgot to mention this, but selecting mpv as default player and opening a file works fine. The problem is only in the command line.

Are you sure you're selecting the same git master version to associate with files?

**Comment by kkanungo17** [comment]
Yup, tried removing mpv completely and rebuild it, and set associations again. Same bug happens.

**Comment by CaledoniaProject** [comment]
Same issue, just recompiled mpv and ffmpeg, any ideas?

**Comment by lachs0r** [comment]
This appears to be a linking problem. Workaround:
```
export DYLD_INSERT_LIBRARIES='/System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine'
```

I have no idea about macOS. Could our build system be at fault or is it Homebrew?
