### ISSUE TITLE
New on screen controls a regression from previous design

### ISSUE THREAD

**Issue by jm2** [mpv-player/mpv#3749]
### mpv version and platform
mpv 1:0.21.0-1 Linux

The new tiny on screen controls / interface at the bottom of the window is a regression from the rounded floating rectangle controls of previous versions. The new one is smaller and more cluttered, looks worse IMO, and is harder to use at a distance on a TV. Please consider improvements to your new design.

**Comment by wiiaboo** [comment]
https://github.com/mpv-player/mpv/wiki/FAQ#i-want-the-old-osc-back
