### ISSUE TITLE
[Feature request] Subtitle SDH filter

### ISSUE THREAD

**Issue by tsoernes** [mpv-player/mpv#3750]
It would be nice to filter out the Subtitles for the Deaf or Hard-of-hearing non-dialog information, such as (in bold):

> **MAN:** Hello
> **[Raining]**
> **(THUNDER)**

It should be relatively simple to achieve rather good (though maybe not perfect) with a couple of regex rules.

**Comment by wiiaboo** [comment]
What regex rules would that be that doesn't remove more than necessary and/or only works with English? Why not just use non-SDH subtitles?

**Comment by tsoernes** [comment]
This should work fine for all languages: [Regexr](http://regexr.com/3ehul)

Often, SDH are the only included subtitles and downloading non-SDH subtitles are a hassle, especially considering that they are seldom marked as such. 

This won't remove song lyrics, which is fine by me.

**Comment by garoto** [comment]
What about a Lua script invoking an external `sed` instance on the currently loaded .srt and then reloading the sub via `sub-reload`? Just something that crossed my mind (don't really know much about coding stuff).

**Comment by tsoernes** [comment]
Well, I don't think `sed` is bundled with Windows or MPV, only with MinGW or Cygwin. After looking at Lua   the programming language might be enough in itself to do the filtering. If anyone could set up a Lua script for loading the subtitle and whatever else that's necessary for it to work as a plugin, I'd be happy to program and test the actual subtitle filtering rules.

**Comment by wiiaboo** [comment]
You could grab the filename using [track-list/N/external-filename](https://mpv.io/manual/master/#command-interface-track-list/n/external-filename), read and regex it and use `sub-add memory://<filtered sub file>` to replace the selected external file, or save it and `sub-add` the new file.

**Comment by lachs0r** [comment]
`--sub-filter-sdh`.
