### ISSUE TITLE
switching between fullscreen/non-fullscreen on a RPi does not work correctly with vo_opengl

### ISSUE THREAD

**Issue by Gusar321** [mpv-player/mpv#3751]
I just compiled mpv git-b0ef3dd on a Raspberry Pi 2 to test the new vo_opengl with hw-overlay support that's meant to replace vo_rpi. It seems to work, until you press 'f'. The behavior is screwy in a different way depending on how you start playback, I'll describe the two cases bellow. In both cases it appears that the size and position of the overlays is not properly updated.
### Reproduction steps

case 1: start playing a video, press 'f' to leave fullscreen
case 2: start playing a video with --no-fs, press 'f' to enter fullscreen
### Expected behavior

case 1: video goes from fullscreen to its original size and is displayed at the center of the screen, the OSD shrinks down to match the video
case 2: video goes from its original size to fullscreen, likewise for the OSD 
### Actual behavior

case 1: video remains the same size as it was in fullscreen and moves to a seemingly random position to the left of the screen, most of the video is off-screen; the OSD also moves to some random position and does not change its size
case 2: the top half of the screen goes black, video disappears; the OSD moves to the bottom left of the screen and remains at the original video size instead of going fullscreen

**Comment by Akemi** [comment]
stale issue.
