### ISSUE TITLE
Erratic visibility behavior with OSC and images

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#3752]
### mpv version and platform

git master (the issue is not related to the recent changes, I actually started noticing it a while ago)
macOS Sierra 10.12.1
### Reproduction steps

Open one/some image/s with `--image-display-duration=inf`.
### Expected behavior

I'm not exactly sure. I think that the OSC should probably be deactivated with still images, but it at least behaving "normally" (as in hiding the OSC after a while like it happens with a video file) would also be fine.
### Actual behavior

If the mouse moves on the mpv's window after opening an image via double click, the OSC appears and the only way to make it disappear is to cycle the visibility mode with del; if more than one image is opened, the OSC perma-visibilty is inherited by all the following ones. 
If the image is opened via command line, the OSC doesn't show up at all, but if there are more than one consecutive images in the playlist, moving forward triggers the "issue".
If an image follows a video in a playlist, the OSC is always on on the image.

**Comment by kevmitch** [comment]
If find it will go away when flipping to the next image if the mouse is not in the "activation region" (sorry if this is the wrong jargon word). I imagine it's probably because the osc relies hevaily on the `tick` event which doesn't actually fire on still images because no new frames are being drawn. Might therefore be hard to fix.

**Comment by wm4** [comment]
>I imagine it's probably because the osc relies hevaily on the tick event which doesn't actually fire on still images because no new frames are being drawn. 

Seems correct. The OSC shouldn't really do this and instead e.g. use a timer or be fully event-based.

**Comment by wiiaboo** [comment]
> The OSC shouldn't really do this and instead e.g. use a timer or be fully event-based.

Proper implementation of https://github.com/mpv-player/mpv/issues/2891 depends on this too.

**Comment by shabahengam** [comment]
Is there any progress?
I have this problem on wayland.if I pause a file with double click(``MOUSE_BTN0_DBL cycle pause``) and trigger OSC, then OSC will shows up everytime mouse move into the window even if its deadzone.the workaround is play/pause file with ``SPACE`` or go to fullscreen mode and get back to windowed mode.

**Comment by wm4** [comment]
Does this still happen on master? There were a bunch of changes to OSC event handling.

**Comment by wm4** [comment]
Just tested, the original issue seems to be fixed. Open new issue if there are still problems, or possibly wayland specific bugs.

**Comment by shabahengam** [comment]
yes,compiled from git-master 055a490
[log.txt](https://github.com/mpv-player/mpv/files/4512249/log.txt)
