### ISSUE TITLE
OSC crashes after recent changes to osc.lua

### ISSUE THREAD

**Issue by pavelxdd** [mpv-player/mpv#3755]
### mpv version and platform
Win10 x64
````
mpv git-eedda59 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Mon Oct 31 22:27:12 MSK 2016
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.4
````

### Reproduction steps
I use a custom osc layout which used to work for me for months until recent changes to osc.lua.
My layout: [mpv-osc.patch](http://sprunge.us/DFXh)
To reproduce an issue all that has to be done is to move a mouse over an osc.

### Expected behavior
OSC works fine just as before.

### Actual behavior
The moment I move a mouse cursor over the osc, it crashes with the following messages in console:
````
[osc] stack traceback:
[osc]   @osc.lua:627: in function 'render_elements'
[osc]   @osc.lua:2062: in function 'render'
[osc]   @osc.lua:2195: in function 'tick'
[osc]   @osc.lua:2146: in function 'process_event'
[osc]   @osc.lua:2269: in function 'cb'
[osc]   mp.defaults:101: in function 'fn'
[osc]   mp.defaults:60: in function 'handler'
[osc]   mp.defaults:339: in function 'handler'
[osc]   mp.defaults:448: in function 'call_event_handlers'
[osc]   mp.defaults:485: in function 'dispatch_events'
[osc]   mp.defaults:441: in function <mp.defaults:440>
[osc]   [C]: at 0x0046d070
[osc]   [C]: at 0x0046c660
[osc] Lua error: mp.assdraw:31: attempt to concatenate local 's' (a nil value)
````

### Log file
http://sprunge.us/KRaf

**Comment by wiiaboo** [comment]
Isn't that something wrong with your additions, though?

**Comment by pavelxdd** [comment]
Maybe, but they worked fine for a long time like that, and as you can see osc.lua crashes outside of my code.
My layout is just a slightly modified default bottombar.

**Comment by wm4** [comment]
If the crahs is caused by your patch, it's obviously your patch's fault.

**Comment by wiiaboo** [comment]
I can try to look why it crashes, but it's only with your layout, so I'd say you need to see what was changed in osc.lua that might've broken your code.

**Comment by pavelxdd** [comment]
I suppose that's really something missing in my code, which needs to be modified according to recent changes to osc.lua, but I hoped you guys could point me in the right direction, since it's you who modified osc.lua recently and you better know the code of osc.lua. Thanks, @wiiaboo

**Comment by wiiaboo** [comment]
Well, that was easy. You forgot to change the tooltip's style from timePos to timePosBar.

**Comment by pavelxdd** [comment]
Thanks a lot!
