### ISSUE TITLE
[Feature request] MacOS Sierra "Picture in Picture" implementation

### ISSUE THREAD

**Issue by sashimiman** [mpv-player/mpv#3756]
### mpv version and platform

 mpv-0.21.0 on MacOS Sierra 10.12.1

MacOS Sierra's new "Picture in Picture" feature is a convenient way to enable a video to play in a (small) sizeable window (presumably this specific mode takes care of the border-type) which hovers always-on-top over regular app windows, but, also, much more interesting, also over native-fullscreen apps (which maximizes a window to a dedicated virtual desktop).

For reference : https://developer.apple.com/library/content/documentation/WindowsViews/Conceptual/AdoptingMultitaskingOniPad/QuickStartForPictureInPicture.html

Example : vimeo.com 's html5 player + safari running in MacOS sierra already supports this neat feature.

thanks in advance

**Comment by Akemi** [comment]
this is the same as #3612 right?

**Comment by sashimiman** [comment]
actually yes it seems so. Does the reference apple dev webpage i point to helps or is it still a closed API and safari/itunes only ?

**Comment by Akemi** [comment]
i think it can be done, see the link in the last comment of the other issue.

**Comment by sashimiman** [comment]
Ok, i'll suggest the apple dev webpage i mentioned earlier as a comment to the issue previously opened. Thanks Akemi for pointing this out.
