### ISSUE TITLE
"up" event for MOUSE_BTN0 press is fired when cursor is moved

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#3757]
### mpv version and platform

mpv 0.21.0, arch linux 64 bit.

### Reproduction steps

with the following lua script:
```
function handler(table)
    for k, v in pairs(table) 
        print(k, v)
    end
end
mp.add_key_binding("MOUSE_BTN0", "whatever1", handler, {complex=true})
mp.add_key_binding("MOUSE_BTN2", "whatever2", handler, {complex=true})
```
and when launching mpv like so:
`mpv --no-config --script script.lua file`

### Expected behavior

The "up" event for MOUSE_BTN0 is fired when the mouse button is actually released, and moving the mouse has no effect on this event.

### Actual behavior

The "up" event for MOUSE_BTN0 is fired as soon as the mouse is moved, even if the button is still pressed.

The "up" event for MOUSE_BTN2 is fired appropriately when the mouse is released, moving the mouse has no effect. 

### Log file

http://sprunge.us/VJGi

**Comment by haasn** [comment]
Confirming the same thing happens for me (xmonad)

**Comment by wm4** [comment]
This happens because this action drags the mpv window.

**Comment by occivink** [comment]
Okay, how can I disable that dragging thing? It doesn't look like it's defined through input.conf.
