### ISSUE TITLE
"cache-used" property returns zero (until there is more cached data than --cache-secs asks for)

### ISSUE THREAD

**Issue by lvml** [mpv-player/mpv#3760]
### mpv version and platform

git master as of today.

### Reproduction steps

Use the https://github.com/lvml/mpv-plugin-streamcache extension I wrote

### Expected behavior

mp.get_property("cache-used") returning the actual number of kb data cached, as the manual describes

### Actual behavior

mp.get_property("cache-used") returning zero until the cache contains as much data as asked for by the "--cache-secs" option, then only the surplus number of kb data cached exceeding the so-many-seconds buffer is reported

### Log file
```
[streamcache] cache-used = 0 cache-size = 75000 cache_percent = 0 
[streamcache] cache_used=0 (< low), new_speed=0.98 
A: 00:00:07 x0.98 Cache:  6s+0KB
```
In the above output (which is extended from the published version of streamcache.lua) you see that 6 seconds worth of data are cached - yet "cache-used" still reports zero (and so does the "cache" property, here printed as "cache_percent").

### Sample files

To reproduce, play any live stream, such as e.g. this shoutcast radio channel: 'http://5.39.71.159:8193/stream'

**Comment by wm4** [comment]
Some streams, like Twitch, use HLS, which doesn't use the byte stream cache (because FFmpeg). Others, like shoutcast, allow only very little readahead, which means the demuxer cache will consume the entire byte cache, so it really has 0 bytes cached most time.

**Comment by lvml** [comment]
> Others, like shoutcast, allow only very little readahead, which means the demuxer cache will consume
> the entire byte cache, so it really has 0 bytes cached most time.

Streams like shoutcast are exactly what my "streamcache" extension was aimed at,
which slows replay a little to accumulate some cached data.

The only reason this does no longer work is that "cache-used" does no longer
give a hint as to how many bytes are buffered in the demuxer. Since mpv displays
the number of seconds buffered in its terminal output, this vital information
must still be there somehow - its just not accessible to the extension.

Would it be possible to provide some property returning this "amount of
data residing with the demuxer"? - then my extension could just add this
to the "real cache" fill as reported by "cache-used", and thus work again.

It would really be sad if I had to discard the extension as "no longer workable
with current mpv".

**Comment by wm4** [comment]
`cache-used` never showed what's buffered in the demuxer, only the stream cache. The demuxer cache measures its cache size in seconds and you can query it with `demuxer-cache-duration`. You can also disable (or effectively disable) the demuxer cache, but that would probably ruin HLS performance.

**Comment by lvml** [comment]
I have now adapted https://github.com/lvml/mpv-plugin-streamcache to deal with the strange situation that the "cache-used" property will only report back the amount of kiloBytes cached in addition to the (potentially large amount of) data cached on behalf of the "--cache-secs=N" option.
