### ISSUE TITLE
force-media-title doesn't seem to work

### ISSUE THREAD

**Issue by nmoorthy1** [mpv-player/mpv#3761]
I am on the latest Windows build available here (2016-10-20 as of posting): https://mpv.srsfckn.biz/

When setting force-media-title in my mpv.config file as
`force-media-title='${filename}'`

The result is this: 
https://imgur.com/a/4xDot

Obviously, even more complicated strings like this:
`force-media-title='${filename} - ${playback-time} / ${duration} ${?percent-pos:(${percent-pos}%)${?chapter: - Chapter: ${chapter}}${!vo-drop-frame-count==0: - Dropped frames: ${vo-drop-frame-count}'`

Also do not work as can be seen here: https://imgur.com/a/8IkxN

If I just use title and remove force-media-title, the string is processed correctly, but only changes the window title.
`title='${filename} - ${playback-time} / ${duration} ${?percent-pos:(${percent-pos}%)${?chapter: - Chapter: ${chapter}}${!vo-drop-frame-count==0: - Dropped frames: ${vo-drop-frame-count}'`

Makes this:
https://imgur.com/a/izpBH

Ultimately, my goal is to change the title in the OSD, but for some reason it is not evaluating my string correctly.

**Comment by lachs0r** [comment]
Supporting expansion in `media-title` is not an option. Assume, for example, that a “malicious” file contains a string which results in parameter expansion. And even if we were to add a special case for the `--force-media-title` option alone, e.g. ytdl.lua would have to take special care to escape things properly (in **Lua** of all things) for the same reason, as it uses this feature.

Hence, maybe you want to write a script that gets the properties and then sets `force-media-title`?

**Comment by nmoorthy1** [comment]
Okay I created a [Lua](https://github.com/nmoorthy1/mpv_change_osd_media_title) script which does what I want.
