### ISSUE TITLE
mpv continues playing after EOF when the chapter metadata is faulty

### ISSUE THREAD

**Issue by knightzx** [mpv-player/mpv#3762]
### mpv version and platform

mpv 0.21.0-git-e6b85c9 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Oct 20 02:56:27 CEST 2016
ffmpeg library versions:
   libavutil       55.32.100
   libavcodec      57.63.103
   libavformat     57.52.100
   libswscale      4.1.100
   libavfilter     6.64.100
   libswresample   2.2.100
ffmpeg version: N-82050-gd3b352c

### Reproduction steps

Open files with the chapter start after the video stream ends

### Expected behavior

The media file is faulty but i think mpv should shut down after the video stream ends

### Actual behavior

mpv just shows the last frame and does nothing till the end of the chapter

### Log file

http://sprunge.us/VejJ 

### Sample files

https://0x0.st/ehX.mkv

**Comment by lachs0r** [comment]
Isn’t this how Matroska editions are supposed to work?

**Comment by knightzx** [comment]
So this is how it's supposed to work. Thanks. We can close this then

**Comment by lachs0r** [comment]
I didn’t mean that as a rhetorical question, but I guess that an edition’s total duration is independent from the stream’s duration when it has an explicit end timestamp, whether it’s before or after the end of all streams. I have no idea if this is even specified anywhere, or whether it should only apply to editions with ordered chapters. There’s also this special case of e.g. subtitle streams that are longer than both audio and video streams. Usually, mpv shouldn’t stick around for the subtitle track, but this is a way to enforce it, however stupid it is. It can also be used as a workaround for the fact that the duration of the last frame is (AFAIK) undefined in Matroska and most other formats.

**Comment by knightzx** [comment]
I'm not familiar with Matroska specification, but as an end user, I expect that mpv would end when the audio and video streams end. Well, I haven't seen those special cases before, but if there are, maybe we could keep this behavior and/or add an option to disable it.

**Comment by lachs0r** [comment]
Upon closer inspection, it looks like this actually happens because the audio track is that long. Should have checked that first.

**Comment by knightzx** [comment]
Oh, you are right! Sorry for that.
Thanks for your support.
