### ISSUE TITLE
Blue video/screen when playing a video with hwdec over a local network

### ISSUE THREAD

**Issue by valdotdev** [mpv-player/mpv#3764]
### mpv version and platform
OS: macOS 10.12.1
Device: 13" rMBP late 2013

mpv git-3f5b41d (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Wed Nov  2 23:38:09 PHT 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.100
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2

### Reproduction steps

Play a video file then try to seek (either by arrow keys or mouse) over a SMB network. So the file is actually on my Win10 PC and mpv is installed on my Mac. Playing local video files on my machine works fine.

### Expected behavior

The video plays fine and seeks normally.

### Actual behavior

No video, only blue screen. Has audio though. I noticed that when I disable either "video-sync=display-resample" or "interpolation", the video automatically starts with a blue screen when opened. When enabled though, it only shows the blue screen when I try to seek, then errors keep popping up in terminal. It seems to be a problem with opengl and/or hwdec (not sure) since everything works fine if I totally disable them all.

### Log file

http://sprunge.us/CgVB?bash

### Sample files
Seems like any video file that supports hwdec on Mac.

**Comment by philipl** [comment]
Same behaviour on linux when using hwdec (vdpau or cuda). Does not happen with software decoding.

**Comment by philipl** [comment]
It's from change 17733bd5b84a7bb8caf497aa9ea35efd657e967a. If you revert that, it should (appear) to work correctly again.

**Comment by valdotdev** [comment]
@philipl thanks for the response! I'm actually a little new to this. Just started using mpv a few months back. How can I revert to a specific commit using Homebrew?

**Comment by philipl** [comment]
Well, you need to be building from source yourself to make changes, including reverting a commit.

**Comment by valdotdev** [comment]
Ok got it I'll do that. Thanks! Hopefully there's a fix soon.

**Comment by ERYuyNIrbNKrsc** [comment]
on linux only when the video paused I get a blue screen
[mpv log](http://pastebin.com/raw/GMzidi5J)
using hwdec vaapi

**Comment by almostalive** [comment]
I get a similar problem on linux with youtube videos as well. With interpolation enabled the video will turn blue when paused. Though for me disabling interpolation the problem goes away.

http://sprunge.us/PTdh

**Comment by Warblefly** [comment]
Same problem on Windows 10 with hardware decoding enabled and interpolation running. Reverting to 17733bd cures it. Hardware is Intel HD530 graphics, i7 Skylake processor.

**Comment by sfan5** [comment]
Same problem here w/ Intel i5 and NVIDIA GTX 950, only happens with enabled hwdec. Reverting 17733bd5b84a7bb8caf497aa9ea35efd657e967a fixes it too.

http://sprunge.us/eMOY

**Comment by Jj0YzL5nvJ** [comment]
I can only reproduce this bug under certain conditions and only with vo=opengl + hwdec=vdpau. Advancing/skipping the video, or causing/experiencing multiple frame drops.

Xubuntu 16.04.1 LTS x86_64
```
mpv git-7c9f326 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Nov  5 00:45:20 MST 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.100
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2
```
```
  GL_VERSION:  3.0 Mesa 13.1.0-devel - padoka PPA
  GL_VENDOR:   X.Org
  GL_RENDERER: Gallium 0.4 on AMD JUNIPER (DRM 2.43.0 / 4.4.0-47-generic, LLVM 4.0.0)
```

**Comment by haasn** [comment]
@Jj0YzL5nvJ Your version of mpv is too old to include the fix.

**Comment by Jj0YzL5nvJ** [comment]
Okay, recompiled to ca17587 and tested. It's fixed... thx

**Comment by valdotdev** [comment]
So far so good on mine. Thanks for the fix!
