### ISSUE TITLE
vdpau-copy?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3765]
Hi!

Manpage says about `vdpau-copy` option that it works _Linux with some GPUs only_.
I have a GTX 660 and a Quadro 600 and a Skylake iGP -- and all have `vdpau`, but lack `vdpau-copy` (let alone Quadro's strangely terrible performance in general). 
What might be these _some GPUs_?
Or maybe I should enable some option somewhere in mpv or ffmpeg, libva, etc?

**Comment by lachs0r** [comment]
The `hwdec=vdpau-copy` option should exist if mpv is new enough and both FFmpeg and mpv have been built with VDPAU support (which is done by default). It should work with all NVIDIA GPUs that support hardware decoding if you are using the proprietary drivers, but it’s a mixed bag with AMD. libva has nothing to do with this, but make sure libva-vdpau-driver is NOT installed.

**Comment by fhlfibh** [comment]
Thanks!
