### ISSUE TITLE
Playback of m3u from Enigma2 platform

### ISSUE THREAD

**Issue by scerazy** [mpv-player/mpv#3768]
### mpv version and platform
Latest from https://laboratory.stolendata.net/~djinn/mpv_osx/
If you're not using git master or the latest release, update.

### Reproduction steps
Enigma2 (Linux Satellite reciever) m3u with content

#EXTM3U 
#EXTVLCOPT--http-reconnect=true 
http://192.168.50.7:8001/1:0:1:C1D:1E78:71:820000:0:0:0:

### Expected behavior
Video/audio should play
### Log file
There is NONE created
As soon as m3u is dropped on the mvp window, it closed & that is the end of it

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files
One needs to have access to Enigma2 receiver to stream it from there, so nothing to upload

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wm4** [comment]
Run mpv on the CLI to get a log.
