### ISSUE TITLE
MacOS little bugs and improvements

### ISSUE THREAD

**Issue by eiphen** [mpv-player/mpv#3775]
mpv 0.21 / macOS 10.11.6

Maybe macOS only related:
-flickering squares / watermarks when fullscreen (classic mode) and HDMI output.
-sound freezes when maxi/minimizing window and moving the window for the first time.
-video is low framerate during window resizing
Global:
-would be nice to be able resizing the window the size we want (no locked ratio) when playing sound files.
-would be nice to have a advanced and interactive playlist interface (clickable with dragndrop support).

**Comment by wiiaboo** [comment]
The last one: [use a GUI](https://github.com/mpv-player/mpv/wiki/Applications-using-mpv)

**Comment by eiphen** [comment]
Thanks for the feedback wiiaboo. It's good to feel the project community is so much alive.

-Concerning the window ratio, I was more thinking about default behaviors, making it disabled for sound playing only (and for video it is nice the have the aspect ratio kept locked).

-For the playlist, I asked for that because, I see there is already a playlist display integrated into the hub, a few more possibilties of that existing playlist display would make the experience complete without the need of any third party GUI.

Best

**Comment by Argon-** [comment]
It would be bad having it default for audio as you usually see your cover art there.

**Comment by lachs0r** [comment]
Please open one issue for each problem, each after checking if a similar issue already exists on the tracker.
