### ISSUE TITLE
Build with SDL fails on powerpc64 w/ altivec

### ISSUE THREAD

**Issue by sambltc** [mpv-player/mpv#3776]
### mpv version and platform

0.21

### Reproduction steps
Normal build from source:
./waf configure
./waf build

### Expected behavior
Successful build.

### Actual behavior
Build fails with:

../audio/out/ao_sdl.c: In function ‘init’:
../audio/out/ao_sdl.c:177:18: error: incompatible types when assigning to type ‘__vector __bool int’ from type ‘int’
     priv->paused = 1;
                  ^
The error is due to the altivec include files (pulled in via SDL.h) adding a #define for "bool", which changes it's type (to a vector type) to one incompatible with 1, 0 or boolean tests.

Perhaps a reasonable fix is to change the definition of priv's paused field to "int", or to move the inclusion of SDL.h until after the struct definition (for struct priv)?
(Either option fixes the issue for me.)

**Comment by wm4** [comment]
Tell the SDL devs to fix their dumb crap?
