### ISSUE TITLE
vapoursynth 35 - Mavericks

### ISSUE THREAD

**Issue by asoksevil** [mpv-player/mpv#3778]
### mpv version and platform
mpv 0.20, OS X 10.9.5
If you're not using git master or the latest release, update.

### Reproduction steps

upgrade to 0.21

brew update && brew upgrade

### Expected behavior

It does not upgrade your build if you have vapoursynth since it requires El Cap or newer.

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by Argon-** [comment]
Wrong issue tracker imo. Go here: https://github.com/Homebrew/homebrew-core/issues

**Comment by lachs0r** [comment]
Yep, not our problem.
