### ISSUE TITLE
Fullscreen + Gnome 3 notification = Windows Crazy

### ISSUE THREAD

**Issue by latot** [mpv-player/mpv#3779]
mpv git-7c9f326 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
Gentoo 64

### Reproduction steps
Open a video in fullscreen, go to other app, wait a gnome notification, like usb plugged/unplugged or similar.

### Expected behavior
Don't show the video in top of windows when gnome send a notification

### Actual behavior
When you do the reproduction steps the screen will show the video, and it will start intercalating the windows depending the position of cursor in reference of the video and the notification...

Thx. Cya.

**Comment by lachs0r** [comment]
Sorry, but that’s a GNOME or possibly driver bug—nothing we could do anything about. mpv doesn’t control what the window manager does in that scenario.

**Comment by latot** [comment]
D: what info do you recommend me pass to gnome3 for this issue?

Thx!
