### ISSUE TITLE
Playlist option to cut to black?

### ISSUE THREAD

**Issue by brontosaurusrex** [mpv-player/mpv#3784]
Is it possible to cut to black on the end of current file (instead of freezing last frame), so black is shown until new file on playlist is loaded/ready for playback? If not I'd like to see that.

**Comment by wm4** [comment]
You can use ``--idle=yes --force-window`` and remove ``--keep-open``. This will close the file immediately and play the next one - if there's no next one, it will just show a black window. Unfortunately the window will also be resized.
