### ISSUE TITLE
Is there a command that one could bind in input.conf that would delete the currently playing video?

### ISSUE THREAD

**Issue by krompus** [mpv-player/mpv#3787]

**Comment by haasn** [comment]
You can do it with the `run` command

**Comment by pavelxdd** [comment]
I use this command to delete to trash on linux:
````
Ctrl+DEL run "gvfs-trash" "${path}"; stop
````

**Comment by krompus** [comment]
Sweet; thanks, guys!

**Comment by krompus** [comment]
I've successfully implemented `ctrl+Del run "trash-put" "${path}"; stop` for use with [trash-cli](https://github.com/andreafrancia/trash-cli/).
