### ISSUE TITLE
Changing hwdec auto-copy->no->auto-copy during playback results in crash

### ISSUE THREAD

**Issue by pavelxdd** [mpv-player/mpv#3788]
### mpv version and platform
Arch x64, NVIDIA proprietary driver, vdpau hwdec
````
mpv git-fc1017c (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Nov 10 05:18:28 MSK 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.100
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2
````

### Reproduction steps
Start a video with hardware acceleration:
`mpv a.mkv --no-config --hwdec=auto-copy`
Change hwdec to "no" during playback (via hotkey or lua script)
`F3 cycle-values hwdec no auto-copy`
Change hwdec back to auto-copy.

### Expected behavior
mpv shouldn't crash on changing hwdec.

### Actual behavior
mpv crashes with the message in console:
````
mpv: ../video/decode/vdpau.c:148: probe_copy: Assertion `!ctx->hwdec_priv' failed.
Aborted (core dumped)
````

If start the video with hwdec=no and change in to auto-copy during playback it won't crash. It crashes only after hwdec->no-hwdec->hwdec.
Also auto (without -copy)->no->auto doesn't crash mpv. So it only happens with auto-copy.

I tried both opengl-backends x11 and x11egl, it doesn't matter which of them I use, mpv always crashes.

### Log file
It's the full log: [log.txt](http://sprunge.us/LeSU)

**Comment by haasn** [comment]
Does this patch help?

```diff
diff --git a/video/decode/vdpau.c b/video/decode/vdpau.c
index a86f5d1..8a1ef96 100644
--- a/video/decode/vdpau.c
+++ b/video/decode/vdpau.c
@@ -87,6 +87,7 @@ static void uninit(struct lavc_ctx *ctx)
     }
 
     talloc_free(p);
+    ctx->hwdec_priv = NULL;
 
     if (ctx->avctx)
         av_freep(&ctx->avctx->hwaccel_context);
```

**Comment by pavelxdd** [comment]
@haasn, yes - it doesn't crash anymore and changes hwdec correctly.
