### ISSUE TITLE
Screenshot template annoyances

### ISSUE THREAD

**Issue by vampiricwulf** [mpv-player/mpv#3790]
So the example is given for %{filename} being equivalent to %f, but I want to be able to use it with playback hours, which has no explained value I'd need to type in the %{} to work.
I think a list of property names would help, or instead just let us use the syntax already mentioned so we can do things like %{%wH:} Where it'd display the hours if the %wH > 0 and nothing if otherwise.
And potentially an if-then-else would be more preferable, as it could allow for custom formatting rather than just checking for the existence of a format: %{%wH?'%wH.':''}.

**Comment by vampiricwulf** [comment]
Nevermind, I found it way deep in the manual, however, I do not see anything specific to playback hours, however it looks like I can rig something maybe.

**Comment by vampiricwulf** [comment]
Yep, nope. There's no way to do math on time-pos so comparisons for hours is impossible currently.

**Comment by wiiaboo** [comment]
That's probably overkill for a simple templating system. You should use a lua script instead.

**Comment by vampiricwulf** [comment]
I disagree, but w.e. I'd rather %wH only show if there's actually something to show, as not every video I'm going to watch is going to even touch an hour.
A template system should be sophisticated as it only needs to be made once. It's kinda the purpose of having templates at all.

**Comment by wiiaboo** [comment]
It's as sophisticated as it needs to be for use with the osd. Extra processing is simple enough to do with a lua script and you can use either script-messsage or script-binding to communicate with said script.

**Comment by Dudemanguy** [comment]
Sounds like a job for a script.
