### ISSUE TITLE
mpv's normal stdout interferes with vo_tct and occasionally interrupts its ANSI terminal escape codes

### ISSUE THREAD

**Issue by guineawheek** [mpv-player/mpv#3791]
This phenomenon is pretty much observable in any video file, which leads to random garbage thrown around the margins of the video and half-finished escape codes and entire glitched lines.

Would it be possible to get them to cooperate more?

**Comment by avih** [comment]
It's probably possible, but would require some effort to coordinate the two unrelated contents displaying to the same terminal. As a workaround, you can disable the normal stdout with `--quiet` or `--really-quiet`.

**Comment by guineawheek** [comment]
Makes sense. Just tested `--quiet` and `--really-quiet`; they seem to be a valid workaround for right now

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
