### ISSUE TITLE
How to create shortcut toggle key change speed to 1 or 6

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3797]
I saw two shortcuts for speed variation:

       [ and ]
              Decrease/increase current playback speed by 10%.

       { and }
              Halve/double current playback speed.

But what i am looking: toggle keyboard shortcut to change speed from 1  to 6.

**Comment by wiiaboo** [comment]
`key [cycle-values](https://mpv.io/manual/master/#command-interface-cycle-values) speed 6 1`
