### ISSUE TITLE
Add s16le to available audio-format options

### ISSUE THREAD

**Issue by tgurr** [mpv-player/mpv#3798]
### mpv version and platform
mpv 0.21.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Mon Oct 31 15:52:26 CET 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.100
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2

Linux 64bit

### Reproduction steps
With MPlayer it's possible to output in s16le raw format, e.g.:

`mplayer http://wms-15.streamsrus.com:11630 -novideo -channels 2 -srate 48000 -af format=s16le -ao pcm:file=/tmp/snapfifo`

I tried to achieve the same with mpv:

`mpv localtestfile.mp3 --no-audio-display --audio-channels=stereo --audio-samplerate=48000 --audio-format=s16le --ao-pcm-file=/tmp/snapfifo`

but mpv doesn't seem to offer s16le as an --audio-format option:

```
mpv --audio-format=help
Available formats: u8 s16 s24 s32 float double u8p s16p s32p floatp doublep spdif-aac spdif-ac3 spdif-dts spdif-dtshd spdif-eac3 spdif-mp3 spdif-truehd
```

With plain FFmpeg it works fine though:
`ffmpeg -y -i localtestfile.mp3 -f u16le -acodec pcm_s16le -ac 2 -ar 48000 -vn /tmp/snapfifo`

**Comment by wm4** [comment]
Use `s16`?

**Comment by wm4** [comment]
Also `--ao-pcm-file=/tmp/snapfifo` does nothing, unless you add `--ao=pcm`.

**Comment by tgurr** [comment]
@wm4 Thanks for the help, it works fine like this!
