### ISSUE TITLE
Feature request: retrieving available video/audio output backends via libmpv

### ISSUE THREAD

**Issue by sagara-** [mpv-player/mpv#3799]
As far as I can tell, there doesn't seem to be a way to get the available video or audio outputs (to be used via --vo/--ao) via libmpv. The mpv application itself checks for the special help vo/ao value and prints them out, but there doesn't seem to be a way to get the list via the client interface (unless I missed something obvious). A quick glance through property-list didn't reveal anything either.

**Comment by wm4** [comment]
``decoder-list``. Doesn't tell you the media type though.

**Comment by sagara-** [comment]
decoder-list is for decoders, not output backends; I originally wrote "decoder" in the issue but changed it right after submitting to outputs since I realized I was using the wrong term. I'm basicly looking for the what the output of `mpv --vo=help` and --ao=help would give you, not individual codecs.

**Comment by wm4** [comment]
There's nothing yet.

**Comment by sagara-** [comment]
This is available via option-list/vo/choices, so closing this feature request.
