### ISSUE TITLE
wscript: MinGW check returns no with clang on Windows

### ISSUE THREAD

**Issue by pavelxdd** [mpv-player/mpv#3800]
The current check for MinGW in wscript works only with GCC.
The only way to compile mpv with clang is to always return true in this check:
````
{
        'name': 'mingw',
        'desc': 'MinGW',
        'deps': [ 'os-win32' ],
        #'func': check_statement('stddef.h', 'int x = __MINGW32__;'
        #                                    'int y = __MINGW64_VERSION_MAJOR'),
        'func': check_true,
        'default': 'enable',
    }
````

Also, there are a lot of warnings about 'format' attribute during compiling:
````
 warning: 'format' attribute argument not supported: gnu_printf [-Wignored-attributes]
    PRINTF_ATTRIBUTE(3, 0);
    ^
````

**Comment by wm4** [comment]
Then it's probably not mingw?

The gnu_printf thing is needed on mingw because mingw is stupid and uses msvcrt semantics by default?

**Comment by avih** [comment]
> The gnu_printf thing is needed on mingw because mingw is stupid and uses msvcrt semantics by default?

I believe it could also be enabled like so before including `stdio.h`:

```C
// mingw - support more formats in *printf which the ms crt doesn't support. This adds
// a small bulk of ansi formatting support to the exe and makes sure it always works.
#define __USE_MINGW_ANSI_STDIO 1

#include <stdio.h>
```

**Comment by wm4** [comment]
We do that.

**Comment by pavelxdd** [comment]
What else could it be if not MinGW?
I use MSYS2 and it compiles ok if I disable the MinGW check.

**Comment by wm4** [comment]
Well, I can't guess what is going wrong.

**Comment by rossy** [comment]
I think this happens because it's using /mingw64/lib/clang/3.9.0/include/stddef.h for the check, which doesn't include \_mingw.h. It can be fixed by replacing ``check_statement('stddef.h'`` with ``check_statement('stdlib.h'``, since stdlib.h is a mingw-w64 header and it _does_ include \_mingw.h.

Disabling gnu_printf on Clang fixes some of the warning spam, but not all of it. I think there are a number of things that need to be fixed in order to properly support mingw-w64/Clang.

**Comment by wm4** [comment]
So does clang actually support mingw-w64? And how is it different from gcc?

**Comment by rossy** [comment]
Yeah, Clang is supposed to run on mingw-w64. On MSYS2, it identifies itself with this triplet:
```
$ /mingw64/bin/clang -dumpmachine
x86_64-w64-windows-gnu
```

mingw-w64 also gets a mention in their user manual (http://clang.llvm.org/docs/UsersManual.html#mingw-w64), but the MSYS2 build needs a lot of patches (https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-clang). I think they are trying to upstream some of them.
