### ISSUE TITLE
MPV does not show itself up in battery menu in Plasma 5

### ISSUE THREAD

**Issue by dolohow** [mpv-player/mpv#3801]
### mpv version and platform
0.21.0 - Linux

### Reproduction steps
1. Play video
2. Go to battery plasmoid in Plasma 5

### Expected behavior
See a message about preventing battery saving like vlc:
![image](https://cloud.githubusercontent.com/assets/1408564/20345328/fb98f6e4-abf6-11e6-9e74-d86f5be1fbf3.png)

Translation: VLC media player currently prevents power saving: Playing few media files.

### Actual behavior
Nothing is showing

**Comment by wm4** [comment]
KDE's problem, not ours. mpv doesn't do anything explicit to disable "power saving" (whatever that is) either.

**Comment by lachs0r** [comment]
mpv does this by using either `xdg-screensaver` or the XScreensaver extension, both of which work with KDE. There are no plans to support any special snowflake dbus protocols.
