### ISSUE TITLE
[Question] Is it possible to stream a YouTube video and dump it to disk at the same time?

### ISSUE THREAD

**Issue by garoto** [mpv-player/mpv#3802]
Using the same socket connection that is.

**Comment by wiiaboo** [comment]
If it's not a DASH url, you can download it using Youtube-DL and watch the file with mpv while it's being downloaded. Otherwise, no.

**Comment by garoto** [comment]
"not DASH" currently means anything better than 720p@30FPS (a.k.a the 'best' in yt-dl lingo) right?

**Comment by wiiaboo** [comment]
Right. Because those have separate video and audio and are occasionally segmented, so they're not as easy or possible to watch while downloading.

**Comment by wm4** [comment]
The general answer is "no".
