### ISSUE TITLE
loop bouncing feature-request

### ISSUE THREAD

**Issue by pussinboot** [mpv-player/mpv#3805]
would it be possible to add a second type of looping?
not sure if it would be implemented as an extra toggle for loop type on top of the existing ab-loop option or another command entirely
current looping is start at position a, once reach position b go back to a
loop bouncing is start at position a, play forwards, once reach position b, play backwards, once reach position a, play forwards, etc

i know this could be done with a lua script, but i am unsure of how to call lua scripts via json-ipc and having a separate ipc on top just for the lua script would be silly.

**Comment by haasn** [comment]
There is no support for backwards playback in mpv, currently. It would be difficult as hell, too.

**Comment by pussinboot** [comment]
ah okay, thank you. i should've realized.
that explains why stepping backwards 1 frame is more often than not slower than stepping forwards 1 frame : )
it probably doesn't make sense to add backwards playback only for uncompressed video codecs where this is not the case.

**Comment by Darxus** [comment]
Can this be re-opened, since, as the previous comment mentions, backwards playback is now supported?

**Comment by megan0n** [comment]
bump

**Comment by guidocella** [comment]
```lua
local loop_a
local loop_b

local function bouncing_loop(_, time_pos)
    if time_pos and (time_pos < loop_a or time_pos > loop_b) then
        mp.command('no-osd cycle play-dir')
    end
end

mp.add_key_binding(';', 'bouncing-loop', function ()
    if loop_a == nil then
        loop_a = mp.get_property_native('time-pos')
    elseif loop_b == nil then
        loop_b = mp.get_property_native('time-pos')
        mp.observe_property('time-pos', 'native', bouncing_loop)
    else
        mp.unobserve_property(bouncing_loop)
        mp.set_property('play-dir', 'forward')
        loop_a = nil
        loop_b = nil
    end
end)
```

This can be used by pressing ; or sending `script-message bouncing-loop` through the IPC.

**Comment by megan0n** [comment]
@guidocella Works well on loops >=1000ms. Any loop <1000ms bounces only on the last 2 frames.

**Comment by megan0n** [comment]
> ```lua
> local loop_a
> local loop_b
> 
> local function bouncing_loop(_, time_pos)
>     if time_pos and (time_pos < loop_a or time_pos > loop_b) then
>         mp.command('no-osd cycle play-dir')
>     end
> end
> 
> mp.add_key_binding(';', 'bouncing-loop', function ()
>     if loop_a == nil then
>         loop_a = mp.get_property_native('time-pos')
>     elseif loop_b == nil then
>         loop_b = mp.get_property_native('time-pos')
>         mp.observe_property('time-pos', 'native', bouncing_loop)
>     else
>         mp.unobserve_property(bouncing_loop)
>         mp.set_property('play-dir', 'forward')
>         loop_a = nil
>         loop_b = nil
>     end
> end)
> ```
> 
> This can be used by pressing ; or sending `script-message bouncing-loop` through the IPC.

Works well on loops >=1000ms. Loops <1000ms only bounces around the last 1-2 frames.

**Comment by afixisin** [comment]
> Works well on loops >=1000ms. Loops <1000ms only bounces around the last 1-2 frames.

That happens when the player overshoots the loop boundaries, then gets stuck reversing again and again before it can ever get back inside the boundaries. A fix is here, here is a fix!
It has one more change, too. Now you can pick an A time that is later than the B time. The loop will start at the earlier mark and end at the later mark.
Thanks for the script @guidocella, it is helpful.
```
local loop_a
local loop_b
local dir
local tmp_a

local function bouncing_loop(_, time_pos)
    if time_pos then
        dir = mp.get_property('play-dir')
        if dir == 'forward' and (time_pos > loop_b) then
            mp.commandv('cycle', 'play-dir')
        elseif dir == 'backward' and (time_pos < loop_a) then
            mp.commandv('cycle', 'play-dir')
        end
    end
end

mp.add_key_binding(';', 'bouncing-loop', function ()
    if loop_a == nil then
        loop_a = mp.get_property_native('time-pos')
    elseif loop_b == nil then
        loop_b = mp.get_property_native('time-pos')
        if (loop_a > loop_b) then
            tmp_a = loop_a
            loop_a = loop_b
            loop_b = tmp_a
        end
        mp.observe_property('time-pos', 'native', bouncing_loop)
    else
        mp.unobserve_property(bouncing_loop)
        mp.set_property('play-dir', 'forward')
        loop_a = nil
        loop_b = nil
    end
end)
```
