### ISSUE TITLE
Different behavior from CLI and GUI when watching Youtube

### ISSUE THREAD

**Issue by kaymio** [mpv-player/mpv#3813]
### mpv version and platform
1:0.21.0-2 on ArchLinux 4.8.8-2 with Cinnamon 3.2.1-4

### Reproduction steps
- Starting YT video from console and clip it to a side or corner.
- Drag'n'drop from browser into a window that is started via an icon and clipped afterwards to one side of the screen and filling one half or quarter of the screen. Either left/right or top/bottom. The mpv instance must be started with an icon on the GUI (Cinnamon in my case)

(Don't know whether clipping is the right word. I mean attaching "magnetically" to one side or corner of the screen by dragging the window till it snaps into place)

### Expected behavior
Always use the best quality video from YT

### Actual behavior
Starting from CLI results in expected behavior. When the mpv is started via the CLI and clipped afterwards results in the right behavior, even when done before playing the first video.

Starting from GUI via drag'n'drop in a clipped mpv instance results in lower quality video (720p or even 480p) while 1080p or 2160p are available. The instance must be clipped before playing the first video.

### Log file
Trying to add `mpv --profile=pseudo-gui -- %U --log-file=~/mpvloggit.txt ` to the starter icon results in not being able to close the edit section in cinnamon. So I can't provide a log file. Maybe you have mor insight in how to provide this.

### Sample files

https://www.youtube.com/watch?v=C-5uCjFhzrY

**Comment by wm4** [comment]
Either there are two different mpv installations, or the window didn't resize for some reason. Impossible to tell without logs.

**Comment by kaymio** [comment]
Being Arch, I can tell there is only one installation. If you tell me how to properly add the --log-file= argument to the starter, I might be able to provide the log. Could it be that mpv is checking under certain circumstances how much resolution it got available and then requesting the "fitting" quality?

**Comment by wm4** [comment]
Try adding it to mpv.conf.

**Comment by kaymio** [comment]
Adding `log-file=~/mpvgitlog.txt` or `--log-file=~/mpvgitlog.txt` doesn't result in output. There is no documentation on adding the log-file in mpv.conf.

My journal tells me this:
`Nov 18 13:33:40 xfarch zeitgeist-fts[1626]: Unable to get info on application://cinnamon-custom-launcher-5.desktop`

**Comment by kaymio** [comment]
Sorry, my fault. Here is the log-file and it seems it's a resizing problem.
[mpvgitlog.txt](https://github.com/mpv-player/mpv/files/600008/mpvgitlog.txt)

**Comment by lachs0r** [comment]
That log file shows it playing a 1080p video. Cinnamon uses Muffin though, which is based on an old version of Mutter and appears to be buggy with the aspect ratio hint. Try with `--no-keepaspect-window`.
