### ISSUE TITLE
not respecting the cache-size property

### ISSUE THREAD

**Issue by bitingsock** [mpv-player/mpv#3815]
### mpv version and platform
shinchiro - sourceforge built 13Nov2016 //Win10x64

### Reproduction steps
with "cache-default=1000" written to mpv.conf, attempt to play certain youtube video eg. https://www.youtube.com/watch?v=8hUOKjy-9-o
OR
while already watching a video and with
c cycle_values cache-size 5000 1000000; show_text ${cache-size}
in input.conf attempt to cycle the cache-size

### Expected behavior
mpv respects the cache-size property

### Actual behavior
mpv only respects the property if it is first set arbitrarily large then reduced again

### Log file
http://pastebin.com/1HxGJbeM
as we can see on lines 52&53 the cache option is being parsed but the next mention of cache in line 254 is setting it to default 75000

### Sample files
this file exhibits the problem:
https://www.youtube.com/watch?v=8hUOKjy-9-o

this one however works as expected:
https://www.youtube.com/watch?v=eVKY7nBTZGg
log: http://pastebin.com/9qH5n0XH
note: the second example also shows the default cache value being reset but it ends up respecting the option anyway...somehow.

**Comment by wiiaboo** [comment]
`[   3.067][v][cache] Cache size set to 76000 KiB (75000 KiB backbuffer)`
You didn't set `cache-backbuffer`. The default for that is 75000 KB too.

**Comment by bitingsock** [comment]
@wiiaboo This is fine since the backbuffer doesn't download in advance. The problem is even if the video is paused the cache continues to fill; but most noteworthy, only for certain videos.

**Comment by wiiaboo** [comment]
If I set both cache-default=1000 and cache-backbuffer=1000 (and cache-secs=1), both those links never go beyond "1 sec + 9xx KB" of cache for me.

**Comment by bitingsock** [comment]
I should note some work arounds:
1) a lua function registered to file-loaded to set the cache-size to 100000 then immediately back to 1000
2) pressing the keybind 3(three) times in a row to achieve something similar

**Comment by bitingsock** [comment]
@wiiaboo that indeed makes it work for me as well. did you notice if without that option whether the other options were respected or not?

**Comment by bitingsock** [comment]
--cache-backbuffer says "the reserved amount will not be used for readahead, and instead preserves already read data to enable fast seeking back."
but for some videos it seems this behavior is failing.

**Comment by wm4** [comment]
Keep in mind that if the file/stream is smaller than forward-buffer and back-buffer combined, it will just use the entire buffer to cache the whole file.

**Comment by bitingsock** [comment]
This may be the explanation I'm looking for. However, like I said, setting cache-size to be large and then small again makes it behave properly. I assume this is because it is also resetting the backbuffer?

**Comment by bitingsock** [comment]
> if the file/stream is smaller than forward-buffer and back-buffer combined, it will just use the entire buffer to cache

I'd like it if mpv didn't use that behavior. I like having a large backbuffer available without downloading what I may not be watching.

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
