### ISSUE TITLE
Adding tags and metadata

### ISSUE THREAD

**Issue by waxfingers** [mpv-player/mpv#3816]
The following is an idea/suggestion/concept... not a request =)

Background: I'm a video editor (osx) and mpv's the tool I find more resoucefull and use and cherish the most; even started trimming footage with it. I totally understand (and appretiate) that mpv's development it's not meant to be focused on a GUI and that (also as its consequence) it's incredibly
configurable. Which brings me to the metadata and tags.

**I would love to be able to write metadata and tags to the clips while I'm reviewing them.** I imagine this is something rather complicated to do - know absolutelly nothing about code - and I also can see how somekind of prompt for text and its implications could go against the minimal GUI dev philosophy.

But even if someone writes a lua script where assigned to different keyboard shortcuts one can write and change beforehand which metadata and which tags would be embedded into each clip that would do it =)

Thank you for all the great great work

**Comment by wm4** [comment]
Seems unlikely that someone does this for non-encoding mode. FFmpeg can't even write metadata without fully remuxing a file. So someone making a Lua script that maybe invokes an external GUI tag editor would be your only hope.
