### ISSUE TITLE
image scrolling with panscan

### ISSUE THREAD

**Issue by tyngdekraften** [mpv-player/mpv#3818]
### mpv version and platform

mpv master with build scripts on gnu userland

### Reproduction steps

mpv --panscan=1 --pause foo.png

### Expected behavior

beeing able to use mpv as an image viewer by scrolling with some keybinding

### Actual behavior

panscan is able to zoom to fit to width or height but it is not possible to scroll

### Sample files

typical picture you would want to zoom and scroll using mpv
foo.png 
![foo.png](https://cloud.githubusercontent.com/assets/20988975/20457055/2c069640-ae83-11e6-9c44-a60258568ebe.png)

**Comment by wiiaboo** [comment]
Add to input.conf
```
KP1     add video-rotate -90
KP2     add video-pan-y -0.01
KP3     add video-rotate +90
KP4     add video-pan-x +0.01
KP5     set video-pan-x 0; set video-pan-y 0; set video-zoom 0
KP6     add video-pan-x -0.01
KP7     add video-zoom -0.01
KP8     add video-pan-y +0.01
KP9     add video-zoom +0.01
```
