### ISSUE TITLE
crashes in osc.lua

### ISSUE THREAD

**Issue by sammoth** [mpv-player/mpv#3819]
I had the following two crashes in osc.lua. They seemingly occurred randomly and the OSC stopped appearing each time until restarting mpv:

[osc] 
[osc] stack traceback:
[osc] 	@osc.lua:2007: in function 'process_event'
[osc] 	@osc.lua:2162: in function 'cb'
[osc] 	mp.defaults:107: in function 'fn'
[osc] 	mp.defaults:60: in function 'handler'
[osc] 	mp.defaults:339: in function 'handler'
[osc] 	mp.defaults:448: in function 'call_event_handlers'
[osc] 	mp.defaults:485: in function 'dispatch_events'
[osc] 	mp.defaults:441: in function <mp.defaults:440>
[osc] 	[C]: in ?
[osc] 	[C]: in ?
[osc] Lua error: @osc.lua:2007: attempt to index field 'eventresponder' (a nil value)

[osc] 
[osc] stack traceback:
[osc] 	@osc.lua:677: in function 'limited_list'
[osc] 	@osc.lua:685: in function 'get_playlist'
[osc] 	@osc.lua:1496: in function '?'
[osc] 	@osc.lua:2010: in function 'process_event'
[osc] 	@osc.lua:2162: in function 'cb'
[osc] 	mp.defaults:107: in function 'fn'
[osc] 	mp.defaults:60: in function 'handler'
[osc] 	mp.defaults:339: in function 'handler'
[osc] 	mp.defaults:448: in function 'call_event_handlers'
[osc] 	mp.defaults:485: in function 'dispatch_events'
[osc] 	mp.defaults:441: in function <mp.defaults:440>
[osc] 	[C]: in ?
[osc] 	[C]: in ?
[osc] Lua error: @osc.lua:677: attempt to index local 'item' (a nil value)

mpv 0.21.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Oct 30 17:49:09 CET 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.100
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2

**Comment by wm4** [comment]
Fixed in git master a very long time ago.
