### ISSUE TITLE
mpv unable to handle non-standard SRT subtitle

### ISSUE THREAD

**Issue by hrimfaxi** [mpv-player/mpv#3820]
### Version
mpv 0.21.0 commit bb48f095320da6e0a71bc18729b8324924dd9bdb

If an SRT has its first sequence number missing, then mpv is unable to handle it.
Or if an SRT somehow marks start time as "0:00.000", then mpv is unable to handle it too.

### Reproduction steps
Play attachment subtitle file with an video.

### Expected behavior
mplayer can play this srt without problem.

### Actual behavior
mpv reports a misleading error:
Can not open external file Great.Rift.EP01.Fire.2010.720p.BluRay.x264.srt.
It should indicate the subtitle is corrupted instead.

### Log file
http://pastebin.com/64DaPLrs

### Sample files

A non-standard srt example: 
[Great.Rift.EP01.Fire.2010.720p.BluRay.x264.zip](https://github.com/mpv-player/mpv/files/601976/Great.Rift.EP01.Fire.2010.720p.BluRay.x264.zip)

**Comment by wm4** [comment]
We unfortunately use the ffmpeg SRT parser, so report this to FFmpeg. Not sure why this issue is open since 2016.
