### ISSUE TITLE
MPV crashes when I go fullscreen on my main monitor but not the secondary.

### ISSUE THREAD

**Issue by zouhair** [mpv-player/mpv#3823]
### mpv version and platform
mpv-x86_64-20161119-git-bb48f09 on Windows 10 Pro 1511

### My setup

I use an Asus laptop with a AMD A10 APU/HD 7730

I have a secondary monitor linked to my laptop

Laptop resolution: 1366x768
Monitor plugged: 1920x1080

### Reproduction steps

I have set my plugged monitor as my main display

### Expected behavior

Going fullscreen on both  monitor without crashing

### Actual behavior

When I go fullscreen (be it opening streams, local videos or just MPV alone) on my main monitor (be it the plugged in or the laptop one) MPV crashes.

If I change the main monitor back to the laptop it won't crash on the plugged one and vice versa. Whatever monitor is the main MPV cannot go fullscreen on it without crashing

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/602548/output.txt)

**Comment by shinchiro** [comment]
Try put `opengl-dcomposition=no` into mpv.conf

In my case, mpv always crash when switching to secondary graphic (nvidia) when opengl-dcomposition is enabled.

**Comment by zouhair** [comment]
This solved the problem, thank you.
