### ISSUE TITLE
Force subtitles into two lines

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3825]
Any interest on this? I really hope there is. Three lines drives me crazy, it just looks goddamn awful, and almost every single time I see it it's in cases were it's completely uncalled for.

**Comment by wiiaboo** [comment]
What does mpv have to do with shitty subtitles styles?
Check all these options: https://mpv.io/manual/master/#options-sub-font

**Comment by firewater2** [comment]
What does it have to do? Nothing, but it could fix them, right? I mean, why not? 

I don't see any option there that would achieve this. This is not about subs in which the font is too big so it gets split, it about subs that even if you render them at 10px will come out with 3, or even 4 nasty lines.

Some of these come with the Blu-Rays, even. It's not just some random subtitle downloaded from some site, they're the official release - and they suck.

**Comment by wm4** [comment]
Blurays use image subtitles (PGS). mpv certainly doesn't line-break them.

Do you have an example text subtitle that gets broken into 3 lines?

**Comment by firewater2** [comment]
Ooooh, right then.

So[ thi](
https://mega.nz/#!2AdxUYIB!qUeaAoTnwUxBDHpnxu4p1Q8vM5vzwIf3zkNdMlFvOfs
)s is one were there are many instances of unecessary three lines.

**Comment by wiiaboo** [comment]
That's forced newlines, in that case. Blame whoever made those subs.

**Comment by firewater2** [comment]
Right, so what I'm hoping for is a setting that forces these into two lines, much like how MPV can override the way anime subtitles come styled with colors/font/signs/etc.

**Comment by lachs0r** [comment]
Nope. Edit the file (using Aegisub or a text editor of your choice) and remove the newlines.

**Comment by firewater2** [comment]
I'd rather just get a new subtitle. Anyhow, I thought it was an useful idea.
