### ISSUE TITLE
mpv video filters not working

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3827]
I am trying the below:

mpv --vf "scale='min(320,iw)':min'(240,ih)':force_original_aspect_ratio=decrease,pad=320:240:(ow-iw)/2:(oh-ih)/2,setsar=1:1,setdar=4:3"  input

it says:

Error parsing option vf (option could not be parsed)
Setting command line option '--vf=scale='min(320,iw)':min'(240,ih)':force_original_aspect_ratio=decrease,pad=320:240:(ow-iw)/2:(oh-ih)/2,setsar=1:1,setdar=4:3' failed.

whereas the below command works 

 ffmpeg -i "input.mp4" -codec:v libx264 -crf 20 -vf "scale='min(320,iw)':min'(240,ih)':force_original_aspect_ratio=decrease,pad=320:240:(ow-iw)/2:(oh-ih)/2,setsar=1:1,setdar=4:3" -c:a copy 19_4.flv

**Comment by sda89ha9** [comment]
[lavfi](https://github.com/mpv-player/mpv/blob/master/DOCS/man/vf.rst#video-filters) filter

--vf lavfi=[scale='min(320,iw)':min'(240,ih)':force_original_aspect_ratio=decrease,pad=320:240:(ow-iw)/2:(oh-ih)/2,setsar=1:1,setdar=4:3]

**Comment by wm4** [comment]
Thanks for answering the question.

**Comment by sant527** [comment]
`mpv --vf="lavfi=[scale='min(320,iw)':min'(240,ih)':force_original_aspect_ratio=decrease,pad=320:240:(ow-iw)/2:(oh-ih)/2,setsar=1:1,setdar=4:3]" *.mp4`

worked for me. Now all the videos fit in one box
