### ISSUE TITLE
MPV display windows title gibberish.

### ISSUE THREAD

**Issue by phling1009** [mpv-player/mpv#3831]
![Uploading Screen Shot 2016-11-23 at 20.46.26.png…]()
I just encounter some problem when I use MPV to player movies , some of movies' mediatitle(Chinese characters) cannot be recognise correctly,but the filename  displayer is ok, I  just have interested in MPV,I am not good at programming,I had try several ways to solve the problem, put " title = "${filename} "  or  " force-media-title="${filename}" "in mpv.conf,but it only display the string I don't want,I need to display the filename instead,I find the original code ".wintitle = "${?media-title:${media-title}}${!media-title:No file} - mpv"," in mpv-master/options/options.c, could have a way to modify files such as mpv.conf so that display filename nor media-title, Maybe changing the Text encoding  would solve the problem,I am just intested in MPV ,I need some one to help me,thanks a lot.

**Comment by wm4** [comment]
mpv assumes that tags are in UTF-8, which is not always the case.

**Comment by phling1009** [comment]
Is there  have a simple way t  recognise other code text?

**Comment by phling1009** [comment]
I find a way to fix it ,may be is not the best way:title='${filename}',force-media-title=' '.

**Comment by wm4** [comment]
Knowing whether your file really has this problem would be helpful.

Maybe I'll implement tag charset detection and conversion one day.

**Comment by phling1009** [comment]
Thanks a lot.
