### ISSUE TITLE
please restore --no-fixed-vo option, or improve aspect behaviour when switching to next video

### ISSUE THREAD

**Issue by losttiger** [mpv-player/mpv#3836]
### mpv version and platform

mpv git-ad2d10a (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Mar  3 23:56:10 UTC 2016
Linux mint based on ubuntu 12.04

### Reproduction steps

play multiple video files in one "playlist" with different aspect ratios

### Expected behavior

- while playing each video, keep window aspect ratio as video aspect ratio when resizing
- when switching to next video of playlist, adjust window aspect ratio to aspect ratio of next video

Just keeping the optimal window aspect ratio for the currently played video 
would be desirable.

### Actual behavior

with --no-keepaspect-window
- when switching to the next video, the window aspect is correctly adjusted to the new video aspect, but
- when resizing the window, the window aspect is not locked to the video aspect, but black bars are added, and one has to try manually to readjust the window geometry in two dimensions to match again roughly the video aspect

with --keepaspect-window
- while playing a video, the window is correctly resized and keeps the video aspect ratio, but
- when switching to the next video in playlist, the window sticks to the wrong aspect of the last video, black bars are added, and the aspect is locked to this non-matching aspect

### Remark

Just keeping the optimal window aspect ratio for the currently played video 
would be desirable since it uses screen space optimally and is most comfortabe.

This is default in vlc, and also has been always been implemented like that in
all previous versions of mlayer/mplayer2

Best, Peter

**Comment by wm4** [comment]
> Just keeping the optimal window aspect ratio for the currently played video
would be desirable since it uses screen space optimally and is most comfortabe.

That's th current mpv default behavior as well.

**Comment by losttiger** [comment]
Really? With which exact setting? 
I am getting the two different non-desired behaviours, depending on the keepaspect-window switch, which I described in detail above.
Each is in itself in some way consistent, but only matches either part from what is desired.
Have you tried?

**Comment by AirPort** [comment]
On my end it works exactly like you describe in _Expected behavior_ by default.
I'm admittedly on a different platform altogether, but maybe it's more of a problem with the WM then?

**Comment by Hrxn** [comment]
> mpv git-ad2d10a (C) 2000-2016 mpv/MPlayer/mplayer2 projects
built on Thu Mar 3 23:56:10 UTC 2016

?

**Comment by losttiger** [comment]
why "?"
actual default install for my platform (ubuntu ppa) according to
https://mpv.io/installation/
output from mpv -v

with all other players (multiple versions of mplayer, mplayer2 or vlc) my WMs have the indicated behaviour

**Comment by Hrxn** [comment]
This one? https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests

**Comment by mc4man** [comment]
There is nothing in that ppa for 12.04, never was, will never be.

**Comment by losttiger** [comment]
sudo add-apt-repository ppa:mc3man/mpv-tests
sudo apt-get update
sudo apt-get install mpv

except for the no-window-geometry-adjusting when jumping to the next video in a playlist (and some annoyances, since directory-diving cannot be optionally disabled at the moment) mpv works very fine on this platform and is for the rest my favorite player.

I am not sure, if it is a distro, or distro-version problem, because the other players adjust the geometry correctly when jumping to the next file or window-resizing with the mouse.

I tried different config settings. 
It would be helpful to know which setting are used, that geometry scaling is handled optimally as well for mouse-resizing and for geometry change in a playlist.
especially the setting of the "keepaspect-window" would be interesting. On either setting, I am getting one of the two disadvantages described abaove.

**Comment by mc4man** [comment]
"mpv git-ad2d10a (C) 2000-2016 mpv/MPlayer/mplayer2 projects
built on Thu Mar 3 23:56:10 UTC 2016
Linux mint based on ubuntu 12.04"

If all that is true then one last time - it didn't come from the mpv-tests ppa & there is nothing there for you. 
A "mpv git-ad2d10a" package for *12.04* was produced last year in the smplayer ppa & that's likely what you are using or you acquired somewhere else. In any event your issue is probably local or local to mint 13 whatever & you're using an outdated mpv, outdated Os,  ect.

**Comment by losttiger** [comment]
complete new install,  completely new Version of mpv

Problem stays the same.

Now on Linux Mint 18 (Ubuntu 16.04)
mpv git-17d6ba7 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Fri Dec 23 14:24:11 UTC 2016

with default options: Window scales correctly acording to current video aspect, but:
when going to next video in playlist, the window aspect is kept from first video, which generally is not the same in every video in playlist.

same behavior with different window managers.
mplayer/mplayer2 adjust aspect correctly.

(when setting "no-keepaspect-window" the window adjusts to the aspect of the next video in list, but window resizing does not keep the actual video aspect any more - like described far above)

**Comment by lachs0r** [comment]
Works for me. Always worked. Not sure which WMs you’ve tried, but they’re probably quite buggy. It wouldn’t be the first time the aspect ratio hint is causing problems (openbox and mutter-based WMs are notorious for this). And Ubuntu 16.04 is very old by now, try on something recent and reopen if it’s still an issue.
