### ISSUE TITLE
[GUIDE] Linux+nvidia proprietary driver, how to avoid stuttering on multihead

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#3839]
This is not properly a bug report, but an advice/guide; take it as you wish, maybe this could go into wiki?

On my dual-head setup, i've always had stuttering problems with high opengl vsync jitter values (xv was fine)
I tried a lot of things, including disabling and chhanging compositors, using various video-sync methods without success.
Vsync jitter is probably entirely a driver issue; i noticed that even if my two monitors shares the very same refresh rate (75,002 - same model), as soon as something is updated on the screen, the measured vsync jitter value jumps to high values (even 0.4)
Now i finally managed to workaround it by completely disable any vsync logic in mpv and kwin and rely on nvidia's forcefullcompositionpipeline feature.
So i disabled tearing prevention in kwin, selected opengl video output in kwin and set --opengl-swapinterval=0 and it did!

No more stuttering.

I use the following scripts to enable/disable/switch nvidia's "tearfree" feature.
https://bbs.archlinux.org/viewtopic.php?pid=1671572#p1671572

**Comment by CounterPillow** [comment]
>Vsync jitter is probably entirely a driver issue

Have you reported this in the nvidia devtalk Linux forum? The nvidia devs who work on Linux actually seem to read it, and might take a look at the problem.

**Comment by lachs0r** [comment]
Setting PowerMizer to performance mode will probably also mitigate this issue. Seems like NVIDIA’s heuristic is broken. To work around this, you can use a script to call `nvidia-settings` at the `video-reconfig` and `shutdown` events.

**Comment by lachs0r** [comment]
Actually, newer driver versions will always run your GPU in full power mode if the desktop resolution is high enough because on-demand switching will cause the spikes in vsync jitter that you are observing. NVIDIA has done this for older GPUs in the past, and seems to have updated that heuristic for newer models recently. Hence, I consider this “fixed”.
