### ISSUE TITLE
abysmal performance with 4k video and EWA chroma scaler

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#3840]
mpv x64 2016-11-20 by lachs0r / mpv-x86_64-20161119-git-bb48f09 by shinchiro
Windows 10 x64

Performance is very bad for 4k video (downscaled to 1440p) when using "--cscale=ewa_lanczossharp", I have close to 100% GPU usage and mpv drops lots of frames.
GPU is a GTX 1070, it should be able to handle it easily (even 60fps).
What's interesting: When I use lachs0rs build and delete libEGL.dll from the mpv folder, performance is normal. With shinchiro's builld, the performance is bad too and there are no external dlls.
No problems with madVR and similar settings.

My commandline e.g. looks like this:
"--vo=opengl --profile=opengl-hq --cscale=ewa_lanczossharp --cscale-antiring=1 --dscale=lanczos --dscale-antiring=1 --scale=ewa_lanczossharp --scale-antiring=1 --interpolation --video-sync=display-resample"

Logfile:
http://sprunge.us/cDZV 

Happens with both 30fps and 60fps 4k video.

**Comment by wiiaboo** [comment]
--opengl-backend=dxinterop

**Comment by wm4** [comment]
The default with EGL DLLs deleted is --opengl-backend=win (which uses native OpenGL) and otherwise --opengl-backend=angle (which emulates OpenGL via Direct3D).

Not sure why D3D apparently exhibits shit performance.

**Comment by wiiaboo** [comment]
Frame timings have a lot higher present and slightly higher upload values with backend=angle than win and dxinterop:
--profile=opengl-hq: [dxinterop](https://i.fsbn.eu/9kzG.png) [win](https://i.fsbn.eu/VfY6.png) [angle](https://i.fsbn.eu/DUPZ.png)
without opengl-hq: [dxinterop](https://i.fsbn.eu/Umal.png) [win](https://i.fsbn.eu/lS9p.png) [angle](https://i.fsbn.eu/nGyv.png)

My opengl-hq:
```ini
[opengl-hq]
scale=haasnsoft
scale-radius=3
cscale=ewa_lanczos
blend-subtitles
interpolation
deband-iterations=2
deband-grain=64
deband-range=8
interpolation-threshold=0.02
temporal-dither
opengl-pbo
icc-contrast=730
target-brightness=120
icc-profile-auto=no
icc-cache-dir=~~/mpv-icc
opengl-backend=dxinterop
video-sync=display-resample
```

**Comment by aufkrawall** [comment]
Thx a lot, guys. --opengl-backend=dxinterop does the trick.
--opengl-backend=win prevents the SMPlayer overlay from working in fullscreen.

**Comment by Hrxn** [comment]
Interesting..
BTW, does `dxinterop` still use Direct3D 9Ex for presentation? As mentioned in the [manual](https://mpv.io/manual/master/#options-opengl-backend).

**Comment by wm4** [comment]
Yes, because Intel doesn't support d3d11 interop.

**Comment by rossy** [comment]
@Hrxn Also D3D11 doesn't support flip-mode present in Windows 7 because the DWM in 7 is still written with D3D 9Ex. Because of this, the Intel thing and the fact that D3D is only used for presentation, not rendering, I don't think there's much point in porting dxinterop to D3D11.

Though it is possible. There is a WIP port here: https://github.com/rossy/mpv/tree/gl-dxinterop2 Not noticeably different from D3D 9Ex interop as far as i can tell.

**Comment by aufkrawall** [comment]
I noticed that opengl-backend=win also introduces some minor stuttering which is not there with dxinterop.
Interpolation doesn't seem to work with D3D renderer.

**Comment by sda89ha9** [comment]
try opengl-glfinish or use ewa_lanczos instead ewa_lanczossharp

**Comment by sda89ha9** [comment]
you could try disable doublebuffering
which could improve things with backend=win
so that  SMPlayer overlay would work in fullscreen and less jitter

powershell code
run in directory of lachsor build mpv-x86_64-20161120
```
#https://mpv.srsfckn.biz/mpv-x86_64-20161120.7z
#PFD_DOUBLEBUFFER patch
#0x24 disable PFD_DOUBLEBUFFER, 0x25 enable PFD_DOUBLEBUFFER (DEFAULT)
$i = 0x24
$a = [io.file]::Open("mpv.exe", "Open", "ReadWrite")
if ($a) {
    $a.Position = 0xA426C
    if ($a.ReadByte() -eq 0x34) {
        $a.WriteByte($i)
        "patched"
    } else {
        "wrong mpv build"
    }
    $a.Close()
}
```

**Comment by aufkrawall** [comment]
I don't get a picture with the patched exe. glfinish leads to bad performance.

Is there anything bad about dxinterop? Seems to be working totally fine here, unlike all other options.

**Comment by wiiaboo** [comment]
It doesn't work with Intel GPUs. Other than that, it's as good or better than win backend.

**Comment by wm4** [comment]
It does work with Intel GPUs, but needs newer drivers - which are apparently not available for _all_ Intel GPUs. Relatively recent Intel GPU + new drivers should work. The problem is that it still works on older GPUs/drivers, but will crash on resizes due to a driver bug. This also means we can't enable it by default.

**Comment by aufkrawall** [comment]
Maybe just blacklist Intel or even old Intel GPUs for it?

I don't really understand the problem in general. Why is sharing the frame to DWM such a problem? I'm not aware that OpenGL games in windowed mode would have performance issues.

**Comment by wm4** [comment]
We don't blacklist individual drivers/GPUs anywhere. Testing and verifying such blacklist entries would be impossible for us.

**Comment by aufkrawall** [comment]
Ok. But probably the documentation should tell users what's the issue? :)

**Comment by lachs0r** [comment]
So it’s an ANGLE issue.

**Comment by aufkrawall** [comment]
Looks like this was a driver bug which got fixed with Nvidia 384 series.
