### ISSUE TITLE
target-trc and gamma 2.4 question

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3843]
Hi,

My TV has gamma set to 2.4, while `--target-trc` option has `gamma1.8`, `gamma2.2` and `gamma2.8` values (other values are not relevant here, afaik).

Which `gamma` should I use for `target-trc`? Or it's better don't mess with this at all?

Regards,

**Comment by fhlfibh** [comment]
I found that `bt.1886` is roughly 2.4, and my TV is set to 2.2 _de-facto_.
So I close this question, because it doesn't interest anyone, anyway.

**Comment by haasn** [comment]
The big difference between bt.1886 and gamma 2.2/2.4 is how the black point is handled. You should set it to whatever your TV is actually calibrated to, which is probably BT.1886.

**Comment by fhlfibh** [comment]
@**haasn**
Unfortunately, I still can't say for sure what my TV is actually calibrated to... TV menu setting shows 2.4, while calibration report shows gamma fluctuating around 2.2 on the grayscale ramp (or at least it's how I understand all that). Actually BT.1886 is not mentioned anywhere...
