### ISSUE TITLE
lua: How to format OSD message?

### ISSUE THREAD

**Issue by limelime** [mpv-player/mpv#3844]
### mpv version and platform

mpv 0.8.3 on Debian Jessie

### Reproduction steps
I'm trying to use lua to format OSD message. But doesn't work.
I was using the following code:
```lua
  local osd_text="{\\u1} underline {\\u0}"
  mp.osd_message(osd_text, 10)
```

### Expected behavior
The word ' underline' should be underlined.
### Actual behavior
It displayed on the screen:
```
{\u1} underline {\u0}
```

**Comment by wiiaboo** [comment]
You need [this](https://mpv.io/manual/master/#command-interface-osd-ass-cc) before any ASS tags.

**Comment by limelime** [comment]
@wiiaboo
I tried multiple variations but in vain. Can you please provide a simple example that is working.

```lua
# Tried the following variations:
local osd_text="${osd-ass-cc/1}{\\u1} underline {\\u0}"
local osd_text="${osd-ass-cc/1}{\u1} underline {\u0}" -- error
local osd_text="${osd-ass-cc/0}{\\u1} underline {\\u0}"
local osd_text="${osd-ass-cc/0}{\u1} underline {\u0}" -- error

mp.osd_message(osd_text, 10)
```

**Comment by occivink** [comment]
You need something like
```
local osd_text = mp.get_property("osd-ass-cc/0") .. "{\\u1} underline {\\u0}" .. mp.get_property("osd-ass-cc/1")
mp.osd_message(osd_text, 10)
```

**Comment by limelime** [comment]
@occivink 
Thx, it worked.
