### ISSUE TITLE
Very loud click when resuming playback on mkv files.

### ISSUE THREAD

**Issue by themusicalduck** [mpv-player/mpv#3848]
### mpv version and platform
mpv --version
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Nov 26 20:40:21 CET 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.1

Up to date Arch linux install. I use a USB soundcard, Presonus Audiobox (with USB power saving options disabled).
I use Pulseaudio and Gnome.

### Reproduction steps
Play a video file. Pause the video. Resume playback after a couple of minutes.
I *think* it only happens on mkv files, but the majority of video files I have are mkv and I can't test many files of other types.
The files use aac audio and h264 video.

### Expected behavior

Normal resume of playback.

### Actual behavior
There is a very loud click/short crunch sound before playback resumes.
It's loud to the point of being painful on the ears.
It doesn't happen every time, but happens more often than not.

### Log file

http://ks361234.kimsufi.com/s/mpv.log

### Sample files
Any mkv file will do the job (it happens almost every time I play one).

I did notice the report further down about this occurring on low frequency content, but this happens with content of any type.

**Comment by lachs0r** [comment]
Pretty sure this is a hardware problem.

**Comment by themusicalduck** [comment]
It could be. I forgot to note that it doesn't happen on other playback software and it doesn't happen on other operating systems (using mpv on OSX and Windows).

**Comment by lachs0r** [comment]
Might just be a coincidence. Maybe the other applications don’t cause PulseAudio to close the ALSA device.
