### ISSUE TITLE
Many dropped frames with 4k content on Skylake CPU

### ISSUE THREAD

**Issue by v-control** [mpv-player/mpv#3849]
### mpv version and platform
mpv git-3203d60
Xubuntu 16.10 x64
Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz

### Reproduction steps
I tried to play several 4k videos (h264 and h265, mkv and mp4) and always get many dropped frames. The processor usage is about 20% during playback, and there is no warning that my hardware is to slow. However, mpv drops many frames and report this.

I think my system should be capable playing 4k videos. Hope you can help me, thanks in advance. 

### Log file
https://drive.google.com/file/d/0B0Tx_d4frJGSeWFPbmtWaWJiVW8/view?usp=sharing

VAINFO:
libva info: VA-API version 0.39.2
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.39 (libva 1.7.1)
vainfo: Driver version: Intel i965 driver for Intel(R) Skylake - 1.7.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice

### Sample files
https://drive.google.com/open?id=0B0Tx_d4frJGSQVJ0dlhPXzdubGM

**Comment by wm4** [comment]
This indicates decoding is fast enough, but rendering is slow.

For the love of god, please don't post files on google drive. It's the most ridiculously inconvenient file hoster I've ever encountered.

**Comment by haasn** [comment]
https://0x0.st/LzR.mp4 mirror of the file in question

**Comment by v-control** [comment]
oops, sorry for that. 
I do not want to annoy you, but do you have any suggestion how to improve rendering? As far as I understand I have opengl capable hardware and software installed.

**Comment by barolo** [comment]
@v-control It's about gpu, the integrated one is not strong enough, use full-screen with compositing disabled, and disable any enhancements . You might try using never graphic graphic stack (mesa & co. )

**Comment by CounterPillow** [comment]
you can run `intel_gpu_top` to see whether any parts of your GPU are at their limit. I'm guessing the i3-6100 is not equipped with a powerful enough GPU. If that's the case, then as barolo suggested, disabling the opengl-hq profile is probably the best choice.

**Comment by v-control** [comment]
Thank you for your answers. I have done some testing and this are the results:

**1.**
Zotac ZBox Intel i3 6100U with 520 GPU, 2x4GB DDR3 1600 RAM modules and Xubuntu 16.10:
Disabeling compositing and use Fullscreen Mode helps. If I play the movie as loop, the first turn is without dropped frames, but then, at the second turn, I have dropped frames. If I loop the file using an EDL list I have less dropped frames.

**2.**
HP ProDesk, Intel i3 6100T with 530 GPU and 1 x 4 GB DDR4 2133 and Windows 10:
Many dropped frames in window and fullscreen mode.
**BUT:** If I add a second 4 GB DDR4 2133 RAM module playback is smooth. I think that is because the GPU can use dual channel RAM in this case. 

It would be interesting for me to know what is the minimum hardware/software combination that is needed for smooth 4k HEVC playback. Has anyone experience with AMD APU's?

**Comment by barolo** [comment]
@v-control AFAIK Skylake uses hybrid decode for HEVC 10 bit, and it's not efficient enough for 4K content from what I've seen.
Kabylake should be fine though.

**Comment by v-control** [comment]
I'm aware of that. But all I wrote above is the same for 4k h264 files, and as far as I know my h265 file was 8 bit.
However, I found someone who has a Gigabyte Brix with i3-7100U CPU, and he allowes me to test on his system. I'm looking forward to do so.

**Comment by ddelapaz** [comment]
I have an i3-6100 @ 3.70Ghz, Asus z170-a, Corsair 16GB DDR4 (2x8GB), Windows 10 Pro 64bit... I tested sample 4K movie and a full movie, both play back but cpu is always close to 99% and at times the content slows down, i can tell drop in frames. The weird thing is, youtube 4K appears to play pretty much flawless most of the time with a couple jumps here and there... What causes this?

**Comment by v-control** [comment]
have you used --vo opengl --hwdec=dxva2? An maybe --opengl-backend=angle?

**Comment by wm4** [comment]
Windows and Linux have completely different graphics layer, and the bugs are likely not related (unless it's about the inherent performance of the chip). Don't hijack issues.

**Comment by lachs0r** [comment]
Just not enough bandwidth on those Intel GPUs.
