### ISSUE TITLE
Low image quality of snapshot taken from webcam

### ISSUE THREAD

**Issue by rightaway** [mpv-player/mpv#3850]
I can take a snapshot from the webcam using `mpv tv:// --tv-driver=v4l2 --tv-device=/dev/video0`, but the image is quite small (640x480) and grainy (despite JPEG quality of 90) even though the webcam is 720p capable. How to take high quality snapshots using the webcam from mpv?

**Comment by lachs0r** [comment]
Use `--tv-width`/`--tv-height`.
