### ISSUE TITLE
Prevent GDM from locking 

### ISSUE THREAD

**Issue by masterkorp** [mpv-player/mpv#3851]
I would like to prevent gnome from locking when wacthing videos on mpv.

### mpv version and platform
Using ArchLinux
-> % mpv --version
Warning: option --heartbeat-cmd is deprecated and might be removed in the future (use Lua scripting instead).
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Nov 26 20:40:21 CET 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.1

### Reproduction steps
Play a video file for more than the Gnome 3 standard lockup time.

### Expected behavior
Should now not lock

### Actual behavior
The screen locks

When I used xscreensaver + awesome wm, the  i would have the following command in the system.

heartbeat-cmd="xscreensaver-command -deactivate >&- 2>&- &"

Can I adpat this to GDM? Also, I would like to do this with a Lua script is possible.

**Comment by wm4** [comment]
xdg-screensaver (which is used by default) is supposed to do this.

Report this upstream.

**Comment by masterkorp** [comment]
Hello @wm4 , I do not see a process called xdg-screensaver running when I do`ps aux`.
I know this question might be a bit offtopic, but how can I check that is xdg-screensaver that is running?

**Comment by wm4** [comment]
It's a script. It's supposed to inhibit screensavers (and other stuff) on multiple desktop environments. We use this script instead of the dbus APIs that some DEs provide, because dbus would be an unacceptable complication.

**Comment by masterkorp** [comment]
So can you explain me how do you call this script? I am running an Arch Linux installation, I recently switched between AwesomeWM to Gnome 3, so I may be missing some packages.

**Comment by masterkorp** [comment]
I did found the binary.
```
-> % pacman -Ql | grep xdg-screensaver
xdg-utils /usr/bin/xdg-screensaver
xdg-utils /usr/share/man/man1/xdg-screensaver.1.gz
```

**Comment by wm4** [comment]
We call ``xdg-screensaver reset`` all 10 seconds.

**Comment by wm4** [comment]
Did you try whether this works? If it doesn't, also try calling xdg-screensaver with suspend/resume and a valid window ID. I think that one is a total shitshow, but it wouldn't actually be too hard to support.
