### ISSUE TITLE
mpv in fullscreen mode always spawns on the first monitor

### ISSUE THREAD

**Issue by Hund** [mpv-player/mpv#3852]
### mpv version and platform

* Arch Linux
* mpv 0.22 (I also tried mpv-git from AUR)

### Reproduction steps

Open any video file with mpv and the flag `--fullscreen`.

### Expected behavior

Expected behaviour is for mpv to spawn on the active monitor in fullscreen.

### Actual behavior

Actual behaviour is that mpv always spawns on the first monitor (DVI-D-0) and it then focuses whatever workspace is active on the first monitor. 

(I'm using a triple monitor setup with the window manager i3)

### Log file

http://pastebin.com/LCGbwBMs

**Comment by smarrocco** [comment]
I can add to this issue the following:
No combination of --screen, --fs-screen, or --fullscreen seems to be able to launch mpv on a monitor other than the primary monitor at startup.

MPV can be launched at an absolute location with --geometry, but this assumes you know the overall location of the non-primary monitors.

**Comment by GUiHKX** [comment]
(Sorry for necro bumping)

I can't reproduce @Hund's behavior as of version 0.28.0, but I still can reproduce @smarrocco's. ([I reported it here](https://github.com/mpv-player/mpv/issues/4442)), so I'm wondering if you're still having this issue with the last version... If you do, and assuming you're still using Linux, try the following command and see if mpv spawns in full screen mode on your second display:

`mpv --no-config --player-operation-mode=pseudo-gui --fs --screen=1 --fs-screen=1`

If that works (it should), try it again but without the `--screen=1` switch (that shouldn't work).

If it all went as I expected, and if you are able to manually patch and compile mpv, you can test [this small patch I made to fix this](https://github.com/mpv-player/mpv/issues/4442#issuecomment-358900892) and then see if you can spawn mpv in your second display with this command:

`mpv --no-config --player-operation-mode=pseudo-gui --fs --fs-screen=1`

Thank you.

**Comment by Hund** [comment]
I forgot about this. It seems to only be an issue when launching videos via Newsboat and it doesn't happen for all videos. And it's not random either, if I open the same video 10 times, it will either just open on the first or just the third monitor. But pretty much all videos will open on the first which is the wrong monitor.

Using `mpv --no-config --player-operation-mode=pseudo-gui --fs --screen=1 --fs-screen=1` has no effect what so ever. I tried different values than `1` as well.

**Comment by GUiHKX** [comment]
Do you still use i3 as window manager? [mpv docs states](https://mpv.io/manual/master/#options-fs-screen):

```
This option does works properly only with window managers which understand the EWMH _NET_WM_FULLSCREEN_MONITORS hint.
```

Unfortunately, i3 doesn't support that:

https://github.com/i3/i3/issues/2116#issuecomment-164923412

**Comment by wm4** [comment]
Not having that hint while EMWH fullscreen is used would require a rather awkward hack, where mpv would need to move the window after (or before?) it has fullscreened. Doesn't sound like a good idea.

**Comment by Hund** [comment]
@GUiHKX: I do, that's sucks.

**Comment by martin3000** [comment]
This bug is very old and not yet fixed...

**Comment by wm4** [comment]
Well it's not our bug.

**Comment by rjc3rd** [comment]
I know this is an old thread, but it was the second link in my google search for how to make MPV open fullscreen on second monitor. 

In the mpv.conf file you simply add...
fs=yes
fs-screen=1

This way it can open fullscreen on my 4K tv monitor from simply double clicking the video file.
