### ISSUE TITLE
Feature request, opengl-medium or similar quality improvement over opengl. Opengl-hq too resource heavy

### ISSUE THREAD

**Issue by okhs** [mpv-player/mpv#3853]
Hello!

profile=opengl-hq is too demanding for my laptop's igpu. Profile opengl is too light for it. Could there be a medium preset (if we think opengl is low and opengl-hq is high)?

Or what kind of settings could I try to improve the current opengl profile?

**Comment by wm4** [comment]
CC @haasn

**Comment by wiiaboo** [comment]
Try `deband=no`.

**Comment by okhs** [comment]
"Try deband=no."

Opengl-hq still too demanding.

**Comment by Argon-** [comment]
I'd say `deband=no` and `cscale=bilinear` (based on `opengl-hq`) but not sure if that warrants its own profile.

**Comment by sda89ha9** [comment]
are you using video-sync= options andor interpolation?

**Comment by haasn** [comment]
I don't know what parts of `opengl-hq` I'd give up, but I'd probably start by giving up `deband`, followed by `cscale`. If that's still too slow, you might as well stick to `opengl`, because apart from this and `scale` there's honestly not much else that `opengl-hq` enables.

**Comment by lachs0r** [comment]
Why do we need to add a preset specifically tuned to *your* laptop? This is bullshit.
