### ISSUE TITLE
macOS notifications make cursor visible for indefinite amount of time

### ISSUE THREAD

**Issue by Hamuko** [mpv-player/mpv#3856]
### mpv version and platform

mpv git-ec74a79, macOS 10.12.1.

### Reproduction steps

1. Play video, full screen or windowed.
2. Have a notification pop up on the screen during playback.

You can use `sleep 10; terminal-notifier -message Test` for easier testing if you have terminal-notifier installed.

### Expected behavior

The cursor stays hidden or at very least hides itself after the notification goes away.

### Actual behavior

The cursor stays on screen until mouse is moved or mouse buttons are pressed.

---

I'm not sure if there's something on my system that causes this to happen since I haven't seen any reports by other users, but I am able to reproduce it on two of my computers. I'm also not sure if mpv can actually do something to fix this in case it's just shitty behaviour by macOS.

`--no-config` and `--no-osc` don't seem to help. Using `--cursor-autohide=always` results in the mouse not hiding itself even after you move the mouse or click on mouse button 1.

**Comment by noctulescent** [comment]
I'm having the same issue, using mpv-0.23.0 on macOS 10.12.2.

The cursor reappears and stay on screen when the notification pops up AND when that notification goes away after a few seconds.

**Comment by Akemi** [comment]
closed via https://github.com/mpv-player/mpv/commit/9ac05a575ce6cffa679c79b6539a798a2d41efde.
