### ISSUE TITLE
"opengl-pbo=yes" as default for --profile=opengl-hq?

### ISSUE THREAD

**Issue by mpvOWNZ** [mpv-player/mpv#3858]
I still remember the time when this was turned on by @wm4 and then disabled again.
But since then a number of improvements have been committed, so maybe it's worth giving this another shot?
BTW, even on Linux + Intel with the DDX & activated SNA I get zero problems! (Gen7 'HD 4000')

**Comment by wm4** [comment]
The default was switched around multiple times because it performed better/worse depending on drivers, so no.

**Comment by mpvOWNZ** [comment]
@wm4 
I understand Your concerns, but that was a long time ago. And since 4K videos are starting to get ever more prevalent, having mpv play them smoothly with --profile=opengl-hq by default would be a plus for new users who didn't read the manual first. (I know, shame on them!)

https://lists.freedesktop.org/archives/mesa-dev/2014-March/055350.html

> This case gets huge performance gains by using
GPU BLIT directly to PBO rather than GPU BLIT to temporary texture followed
by memcpy.
No regressions on Piglit tests  with Intel driver.
Performance gain (1280 x 800 FBO, Ivybridge):
glGetTexImage + glMapBufferRange  with patch 1.45 msec
glGetTexImage + glMapBufferRange without patch 4.68 msec

And that was in 2014!
Drivers on all platforms should be much more mature by now, so giving this option at least another chance would only be fair (especially for new and/or ignorant users).

**Comment by lachs0r** [comment]
> Drivers on all platforms should be much more mature by now
AhahahahaHAHAHAHAHAHA.

**Comment by wm4** [comment]
Last time I disabled pbos by default because "too many  problems" was in december 2015.

Yes, pbos are faster in some situations, but we don't know when. Unless we start with driver whitelists.

**Comment by haasn** [comment]
Can we reinvigorate discussion about this in light of https://github.com/mpv-player/mpv/commit/dead206873c1840a21adf789b9e4b5d167012b19 ?

If the issue was related to the map/memcpy/unmap cycle, this could in theory remove that and make the PBO case faster for all drivers. Would love to hear from anybody who had issues with `--opengl-pbo=yes` if this commit makes it better.

**Comment by AirPort** [comment]
Actually the opposite, it seems that the new PBO code took a heavy toll on performances on my system. 
It's not particularly noticeable in audio-sync mode, but display-resample is basically unusable now together with opengl-pbo in fullscreen (vsync-jitter skyrockets, lot of missed, delayed and dropped frames), on both intel and AMD GPUs.
I'll investigate better tomorrow, let me know if I can provide you useful stats.

**Comment by Akemi** [comment]
seems like this is off the table.

**Comment by wm4** [comment]
Actually --vd-lavc-dr is now the default, which is an even more extreme version of the old pbo setting.
