### ISSUE TITLE
Foldered DVD/Blu-ray have problems seeking

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#3859]
Seeking is weird with these. It produces problems with playback, and sometimes with image. [Here ](https://mega.nz/#!bM1lGTTK!SjkcEyMd1t1mv9gubRzIN-nvA-grPlhWoSoRQyckb8Y)is a video displaying the three possible outcomes I've found.

**Case 1**

This is what happens with 99.9% of DVDs, and some Blu-rays, that I've tried: with a small value (0.8), seeking forwards gets stuck, and seeking backwards either gets stuck, or goes forward. Seeking with a high value (35) works fine.

**Case 2**

Seeks backwards fine, but gets stuck on forward with a low value. Also, the video is screwed during and shortly after seeking, plus sometimes there's a problem in which after seeking, the video plays super fast and desynchronises itself with the audio (not seen on the recording I did).

**Case 3**

Opening from VIDEO_TS - Works perfectly up to a certain point, From this point on, I can no longer advance by seeking forward because it goes back to a this specific point every time I attempt (the frame it goes back to varies depending if I use the high or low value). The only way for the video to advance is just letting it play. If I let it advance a bit, and then seek (high) forward one time, it has another point of return, but I still cannot seek forward. If I let it advance, and then seek forward many times, it goes back to the original point of return.

Opening from VTS_01_0 - Almost everything works properly. The only exception is that seeking backwards with no-osd needs to be done constantly, otherwise it gets stuck.

**Comment by lachs0r** [comment]
Do people ever read the issue template?

**Comment by firewater2** [comment]
There's only one other issue listed with this problem, it's not very detailed, and is from 2 years ago. Thought it'd be worth a shot to mention it again after all this time.

**Comment by lachs0r** [comment]
The issue template you see in the input box when creating a new issue. Which you have ignored.

Also, this sounds like the usual MPEG-TS/libdvdread/libdvdnav horrors, and I can’t even reproduce them with the discs I’ve authored myself (which are all I have at the moment). Try HR seeking. You can put this in `mpv.conf`:
```
[protocol.dvd]
hr-seek=always
```

**Comment by RX14** [comment]
For others finding this issue, `--hr-seek-demuxer-offset` seems to be the right knob to tweak in addition to `--hr-seek` to get back arrow to reliably seek backwards. I have to set it to 5 to get my dvd to find a keyframe in some places.
