### ISSUE TITLE
comfirm mpv is compiled using ffmpeg and not Libav

### ISSUE THREAD

**Issue by LandisTwo** [mpv-player/mpv#3860]
### mpv version and platform
mpv 0.22.0 built on Nov 20 2016
installed from Packman for OpenSuSE 13.2
If you're not using git master or the latest release, update.

### Reproduction steps
mpv docs say to use ffmpeg and Not Libav as some options are not available with libav.

# mpv --version
`mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Nov 20 2016
ffmpeg library versions:
   libavutil       55.17.103
   libavcodec      57.24.102
   libavformat     57.25.100
   libswscale      4.0.100
   libavfilter     6.31.100
   libswresample   2.0.101
ffmpeg version: 3.0.4`

### Expected behavior
I would think that there would be no 'libav' files if mpv were using ffmpeg and Not Libav.

### Actual behavior
How can I verify this binary from Packman repo is using ffmpeg and not libav
I'd build it myself, but There are SO many other files (gstreamer, ffmpeg libraries, codecs etc) that I'd rather not. I've installed mpv, smplayer Many times on OpenSuSE over the years on Many systems that I know the littlest file, library version can cause many problems. I'd like to stick to the binary.
### Log file

Thankyou for producing mpv... It & it's predecessor mplayer have made using Linux over the past many years, much nicer. Thanks. Landis.

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wiiaboo** [comment]
libav* are the libraries' names. They were named that way before the libav fork.

**Comment by haasn** [comment]
> How can I verify this binary from Packman repo is using ffmpeg and not libav

The definitive way would be to check `ldd $(which mpv) | grep libavcodec`, then look up that filename in your package manager's installed packages, e.g.

```
λ equery b /usr/lib64/libavcodec.so.57
 * Searching for /usr/lib64/libavcodec.so.57 ... 
media-video/ffmpeg-9999 (/usr/lib64/libavcodec.so.57 -> libavcodec.so.57.66.103)
media-video/ffmpeg-9999 (/usr/lib64/libavcodec.so.57.66.103)
```

**Comment by wm4** [comment]
That's not very definitive. Just look at the micro version numbers - if they're below 100, they're Libav.

**Comment by lachs0r** [comment]
You could:
1. Check [PMBS](https://pmbs.links2linux.de/package/view_file/Essentials/ffmpeg-3.1/ffmpeg-3.1.spec?expand=1)
2. Grab the source RPM
3. Ask on the Packman mailing list
4. Look at mpv’s version output (it actually prints “libav” instead of “ffmpeg” if it looks like it’s built with Libav library versions)

**Comment by LandisTwo** [comment]
**haasn** - thanks I'll look.
mine looks like this:
`libavcodec.so.57 => /usr/lib64/libavcodec.so.57 (0x00007f24e4dab000)`

**wm4** - so, Libav (big L) are the libraries mpv docs say limit options, right.
Where libavxxxx (small L) are ffmpeg files and should have micro version above 100?  like mine: libavutils 55.17.103 or libavcodec 57.24.102,, **103** and **102** being above 100, so NOT Libav (big L), yes?

Thanks.
Landis.

**Comment by LandisTwo** [comment]
**lachs0r**
if I do ffmpeg -version mine looks like this... presumably Libav libraires, yes?
`libavutil      55. 34.100 / 55. 17.103
libavcodec     57. 64.101 / 57. 24.102
libavformat    57. 56.100 / 57. 25.100
libavdevice    57.  1.100 / 57.  0.101
libavfilter     6. 65.100 /  6. 31.100
libavresample   3.  1.  0 /  3.  0.  0
libswscale      4.  2.100 /  4.  0.100
libswresample   2.  3.100 /  2.  0.101
libpostproc    54.  1.100 / 54.  0.100
landis@linux-e6420:~> mpv -version
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Nov 20 2016
ffmpeg library versions:
   libavutil       55.17.103
   libavcodec      57.24.102
   libavformat     57.25.100
   libswscale      4.0.100
   libavfilter     6.31.100
   libswresample   2.0.101
ffmpeg version: 3.0.4`

What 'options' am i missing if my binary is compiled using Libav instead of ffmpeg? I haven't come across anything I want to do, that I have not been able to do. 

I see you're on irc.. I'll ask there. Thanks.
Landis.

**Comment by LandisTwo** [comment]
guys - it's not really that important to me. 
mpv works now and i don't produce video, so as long as it plays i'm good.

I was having an issue where mpv would crash, but only after movie/video was paused for a long time, then resumed and the log kept saying the shared version of ffmpeg is not the same version mpv was compiled against.

Well, that is almost Always going to be the case. Many apps, especially something like youtube-dl which is updated almost daily will stop working if the ffmpeg version becomes 'too old' and ffmpeg needs to be updated.
Eventually I'll be right back at ffmpeg is not the same ver mpv was compiled with... right.

So, it's working at the moment, but I haven't tried youtube-dl to see if ffmpeg version is 'ok with it'.

Thanks for your time, maybe i'll see you on irc.
Landis.

**Comment by lachs0r** [comment]
> Well, that is almost Always going to be the case.

It really shouldn’t be. That is a packaging problem.
