### ISSUE TITLE
0.22.0 don't support ffmpeg-3.2.1

### ISSUE THREAD

**Issue by ilgrad** [mpv-player/mpv#3861]
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.100 (runtime 57.64.101)
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.1

mpv was compiled against a different version of FFmpeg/Libav than the shared
library it is linked against. This is most likely a broken build and could
result in misbehavior and crashes.

mpv does not support this configuration and will not run - rebuild mpv instead.

Exiting... (Fatal error)

**Comment by wiiaboo** [comment]
Have you tried reading what it says? mpv doesn't support running with a different version of FFmpeg than the one it was compiled with. It's not an issue, it's a feature.

**Comment by lachs0r** [comment]
It supports FFmpeg 3.2.1 just fine. You just need to actually build mpv with the same library version that is installed on your system though.

**Comment by ilgrad** [comment]
sorry, apparently I have not written there
