### ISSUE TITLE
mpv crashes on quit (Segmentation fault: 11) MBP 2016

### ISSUE THREAD

**Issue by SimonAth** [mpv-player/mpv#3864]
### mpv version and platform

/usr/local/Cellar/mpv/HEAD-ec74a79_1 (66 files, 38.6M) *
  Built from source on 2016-12-02 at 14:17:56 with: --with-bundle --with-libdvdread
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb

Mac OSX Sierra on a 2016 MacBook Pro with Radeon Pro 460

### Reproduction steps

Quit the program (using q or cmd+c) whilst playing a video in fullscreen

### Expected behavior

Program closes quietly.

### Actual behavior

Program closes with Segmentation fault: 11, and throws an error "mpv quit unexpectedly"

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us/YagA

OSX problem details and system configuration
http://sprunge.us/JgTV

### Sample files

same issue on any file when played in mpv's fullscreen mode.
(mpv is fine when not in fullscreen, or in OSX native fullscreen mode.)

**Comment by Akemi** [comment]
my PR #3873 will most likely fix this issue. would be nice if you could confirm it.

**Comment by SimonAth** [comment]
Yes, #3873 fixes this issue. 
Cheers

**Comment by Akemi** [comment]
fixed in https://github.com/mpv-player/mpv/commit/a8347eb9ba9e09177da50592fde7f3ae7261ce59
