### ISSUE TITLE
OS X: Quit keycommand conflicts with system-wide OS X command

### ISSUE THREAD

**Issue by SteveJobzniak** [mpv-player/mpv#3865]
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Nov 26 05:17:19 GMT 2016

macOS Sierra.

Problem: mpv's main menu has an option "Quit mpv & remember playback position", bound to Shift+Command+Q.

Well, that's a system-wide OS X shortcut to "Log out and quit all applications". Mpv cannot use that! ;-P

The bug is here:
https://github.com/mpv-player/mpv/blob/master/osdep/macosx_application.m#L124

`keyEquivalent: @"Q"`

Perhaps Ctrl+Command+Q instead? That one isn't used by anything on macOS itself.

**Comment by CounterPillow** [comment]
Isn't quit & remember playback position just Shift+q, like on all other platforms?

**Comment by SteveJobzniak** [comment]
It is that _too_. But the OS X app wrapper also has some menu items of its own, and one of those is bound to the same as the global "Log out" menu command in OS X haha, which means that you actually get logged out if you try the shortcut that the mpv app bundle wrapper suggests.

![screen shot 2016-12-04 at 04 14 52](https://cloud.githubusercontent.com/assets/22373193/20863794/446af860-b9d8-11e6-9407-f8a6bd94b918.png)

**Comment by SteveJobzniak** [comment]
A few options:

- Delete the "Quit mpv & remember position" shortcut, since unlike the others it isn't required for "OS X glue" (common shortcut support like Cmd+Q and Cmd+H).
- Set it to something like Ctrl+Cmd+Q, which isn't reserved by the macOS desktop.
- Set it to Shift+Q so that it matches the actual default mpv shortcut. But then you run the downside of binding something without the Cmd (meta) character, which would annoy users who want to rebind Q and Shift+Q to something less dangerous than "instant quit without confirmation".

My vote goes for deleting or Ctrl+Cmd+Q.

**Comment by Nyx0uf** [comment]
I aldo think it should be removed from the menu.

**Comment by avih** [comment]
> My vote goes for deleting or Ctrl+Cmd+Q.

Leaving it in place while just changing the shortcut would have been better IMO. Quit and watch later is a major functionality of mpv, and assuming a menu is useful, this specific option rightly belongs there.

**Comment by SteveJobzniak** [comment]
@avih Those menus are mainly minimal OSX glue things to make standard app shortcuts like Cmd+Q work as intended etc.

There are lots of major mpv functionalities that don't have menu items. Like going into fullscreen mode, for one thing! People with mpv learn shortcuts (like Shift-Q and F) or they won't get very far.
