### ISSUE TITLE
OS X: Geometry coordinates are inverted

### ISSUE THREAD

**Issue by SteveJobzniak** [mpv-player/mpv#3867]
--geometry=0:0 places the window in the bottom left.

--geometry=100%:100% places the window in the top right. (According to the mpv manual that's supposed to be "Places the window at the bottom right corner of the screen.")

Seems like the OS X desktop uses a different coordinate space, and that translation code is needed for mpv on OS X.

**Comment by SteveJobzniak** [comment]
@pigoz @wm4 @frau @rcombs @rr- @czarkoff @Bilalh @Nyx0uf 

Pinging everyone who was listed as a contributor on `macosx_application.m`. This OSX layer bug is frustrating. It looks to me like X coordinates work as intended, but that Y coordinates are inverted.

**Comment by SteveJobzniak** [comment]
I found information that helps:
http://stackoverflow.com/questions/21751105/mac-os-x-convert-between-nsview-coordinates-and-global-screen-coordinates

> Mac OS uses different coordinate systems in various places. Views can define if they have an upwards or downwards pointing y-axis (`isFlipped`). A window's origin is expressed in "screen coordinates" with an upwards y-axis. Screens are arranged using the global coordinate system with y pointing down.
> 
> It's better not to try to do the conversion of all the coordinate spaces yourself but let the responsible objects do the job:
> 
>     NSView *yellowView; // your view that contains the point with the yellow arrow.
>     NSPoint yellowPoint = { 100, 100 };
> 
>     NSPoint pointInWindow = [yellowView convertPoint:yellowPoint toView:nil];
>     NSPoint pointOnScreen = [[yellowView window] convertRectToScreen:(CGRect){.origin=pointInWindow}];
> 
>     NSWindow *newWindow = [[NSWindow alloc] initWithContentRect:(CGRect){ pointOnScreen, {32, 32}} styleMask: ...];

So, it seems like what mpv for OSX may need is a simple "isFlipped" flag somewhere... To invert the Y-axis. Then the app won't have to translate coordinates. The OS will understand told that 0,0 == top left.

**Comment by Nyx0uf** [comment]
On macOS coordinates (0, 0) = bottom, left by default, in contrary of iOS which is top, left. Don't know for other platforms.

It is indeed possible to change this behaviour by overriding the `-(BOOL)isFlipped` method in an `UIView` subclass.

**Comment by SteveJobzniak** [comment]
@Nyx0uf Good to hear that it's fixable. So all someone has to do is create a subclass of UIView, override isFlipped, and assign that subclass as the view for the mpv window?

And no I cannot do it. I've never programmed for OSX before.

**Comment by sCreami** [comment]
I also realised --no-hidpi-window-scale mess up with --geometry. --geometry=100%:100% doesn't place the window on the top right has expected.

**Comment by Akemi** [comment]
we actually already use [isFlipped](https://github.com/mpv-player/mpv/blob/f1436658647aceb7ea58e595439fa6dd5c2cdb97/video/out/cocoa/events_view.m#L104). i will have a look at it since i am working on the new fullscreen anyway.

**Comment by SteveJobzniak** [comment]
@Akemi <3

**Comment by Akemi** [comment]
that #3962 should do it. feel free to test.

**Comment by SteveJobzniak** [comment]
@Akemi Thank you so much for being brilliant and being such a kind person, and helping improve the Mac side of mpv. I love you.

It's impossible to build a different branch using the homebrew install method, but I built the regular application manually to help test.

Test environment: MacBook Pro 2010. Single screen. Non-retina display (1680x1050).

All tests were done with `./mpv --force-window --idle --geometry=<X>:<Y>` for normal positions, and `./mpv --force-window --idle --geometry=[+-]<X>[+-]<Y>` for negative positions.

I compared it to the coordinate space used by macOS, and the offsets matched PERFECTLY. If I told macOS to move a window to -20, -20, and told mpv to start at -20-20, they were both identical. I tried all four corners.

You have done a perfect job. The only things I cannot test are:

- Multiple screens (how does the coordinate space survive that? macOS itself uses one huge rectangle to cover all screens but I see that you're using some other method to do a per-screen offset)
- Retina displays.

Anyway, looking forward to your merge. This issue is finally fixed. <3 I love you.

**Comment by Akemi** [comment]
since you can pass the desired screen of the window on creation you can use screen relative coordinates.

**Comment by SteveJobzniak** [comment]
@Akemi I see that the code uses `s->current_screen` from the Cocoa state. So it seems multi-screen should work. I just haven't tried it.

I also haven't tried changing `hidpi-window-scale` (I haven't specified a value for it, so it's at whatever the default is). And I cannot try retina.

But as far as what I could test: Non-retina with a single screen, works _perfectly_.

**Comment by AirPort** [comment]
I didn't notice any problem with a retina display either.
