### ISSUE TITLE
Submission: cycle_video_rotate.lua

### ISSUE THREAD

**Issue by SteveJobzniak** [mpv-player/mpv#3869]
I noticed that you have an internal repository of scripts. I also noticed that you've had questions from users about how to rotate a video.

**Method 1: Add/Subtract**

```
Alt+LEFT add video-rotate -90
Alt+RIGHT add video-rotate 90
```

Result: 0..90..180..270..359 (this is where all hell breaks loose; the video is now unevenly rotated).
Verdict: Garbage method.

**Method 2: Cycle a set of pre-determined values.**

```
Alt+LEFT cycle-values "!reverse" video-rotate "90" "180" "270" "0"
Alt+RIGHT cycle-values video-rotate "90" "180" "270" "0"
```

Result: Always even rotation. But if your first action on a video is to rotate left, your next rotation will be "0" (the default rotation for a video), so you actually have to press left _twice_ to get it to rotate left.
Verdict: Almost good... so close, but not good enough for a project the quality of mpv.

**Method 3: My "Cycle_Video_Rotate" script.**

~/.config/mpv/scripts/cycle_video_rotate.lua: **(Edit: See updated version of this script [below](https://github.com/mpv-player/mpv/issues/3869#issuecomment-264729190))**

```lua
function cycle_video_rotate(direction)
	-- Calculate what the next rotation value should be.
	newrotate = mp.get_property_number("video-rotate")
	if direction == "clockwise" then
		newrotate = newrotate + 90
	else
		newrotate = newrotate - 90
	end
	-- Wrap value to correct range (0 (aka 360) to 359).
	if newrotate >= 360 then
		newrotate = newrotate - 360
	elseif newrotate < 0 then
		newrotate = newrotate + 360
	end
	-- Change rotation and tell the user.
	mp.set_property_number("video-rotate", newrotate)
	mp.osd_message("Rotate: " .. newrotate)
end

mp.register_script_message("Cycle_Video_Rotate", cycle_video_rotate)
```

~/.config/mpv/input.conf

```
# Rotate video in 90 degree increments.
Alt+LEFT script-message Cycle_Video_Rotate "counter-clockwise"
Alt+RIGHT script-message Cycle_Video_Rotate "clockwise"
```

Result: Works instantly in any direction without needing multiple keypresses. Always aware of and basing itself on the current rotation value, thus never "jumping" to an unexpected rotation. Always uses even 90-degree increments as long as the users themselves haven't applied any uneven rotation before calling this function (in that case, it fully preserves their offset and does the 90 degree rotation on top of that).
Verdict: Get this included into mpv! ;-) It's so much slicker.

Take care!

**Comment by wm4** [comment]
You have a point, but we usually don't add scripts to the repo anymore.

Also I think the reverse mode of property cycling should probably be improved.

**Comment by fhlfibh** [comment]
@SteveJobzniak maybe https://github.com/mpv-player/mpv/wiki/User-Scripts ?

Also I'd imagine something like
`# direction is 1 or -1
signed int direction, newrotate
newrotate=newrotate+90*direction
if (newrotate<0 OR newrotate=>360) then newrotate=newrotate-360*direction
`
Didn't test it myself, sorry...

**Comment by haasn** [comment]
Personally I would find it more intuitive and less prone to edge cases like these if the “cycle” logic simply worked by finding the current value in the list and picking the next one.

That's how I implemented `:set --cycle` in qutebrowser and I have not run into any surprising behavior there.

**Comment by SteveJobzniak** [comment]
@haasn But that would break existing code and bindings that rely on cycle going from left to right, instead of having the cycle guess that we're somewhere else.

@fhlfibh There's no such thing as a "signed" or "int" in Lua, but yeah I could definitely use tricks like that to shorten the code, at the expense of readability. I haven't coded Lua in about 6 years so I struggled a bit to remember how the language works. I'm more of a C guy.

@wm4 Perhaps cycle could have an optional "assume we're currently at index X" initialization parameter.

Alt+LEFT cycle-values "!reverse" "index0" video-rotate "0" "90" "180" "270"
Alt+RIGHT cycle-values "index0" video-rotate "0" "90" "180" "270"

That would initialize the cycle as if we're already at index 0 (the first entry). So cycling forward would go to "90". Cycling backward would go to "270". And that parameter, it would assume we aren't anywhere and would in the cycling list (current behavior) and would pick "0" if going right or "270" if going left.

Adding the feature this way wouldn't break any old scripts.

Do you think there would be a value to adding such a "assume we're at index X" feature to cycling, beyond the fact that it would allow mpv to natively do video rotation cycling more nicely?

**Comment by wm4** [comment]
@haasn there's currently no way to test for equality of 2 values. We could convert the current value to a string and then compare them, but that would work badly for floats.

**Comment by SteveJobzniak** [comment]
**Updated version of ~/.config/mpv/scripts/cycle_video_rotate.lua to reduce code repetition:**

```lua
function cycle_video_rotate(direction)
	-- Calculate what the next rotation value should be.
	newrotate = mp.get_property_number("video-rotate")
	newrotate = newrotate + (direction == "clockwise" and 90 or -90)
	-- Wrap value to correct range (0 (aka 360) to 359).
	if (newrotate < 0 or newrotate >= 360) then
		newrotate = newrotate + (newrotate < 0 and 360 or -360)
	end
	-- Change rotation and tell the user.
	mp.set_property_number("video-rotate", newrotate)
	mp.osd_message("Rotate: " .. newrotate)
end

-- Bind this via input.conf, ie. "Alt+r script-message Cycle_Video_Rotate":
mp.add_key_binding(nil, "Cycle_Video_Rotate", cycle_video_rotate)
```

Feel free to either bundle this, or improve "cycle". Not sure what's best to be honest. I haven't seen any other cycle-able values that would benefit from being able to set the start-index.

**Comment by haasn** [comment]
Incidentally, this is how I rotate with my image.lua:

```
-- Rotates the video while maintaining 0 <= prop < 360
function rotate_video(amt)
    local rot = mp.get_property_number("video-rotate")
    rot = (rot + amt) % 360
    mp.set_property_number("video-rotate", rot)
end

mp.add_key_binding(nil, "rotate-video", rotate_video)
```

and in input.conf
```
CTRL+RIGHT script-message rotate-video 90
CTRL+LEFT script-message rotate-video -90
CTRL+DOWN no-osd set video-rotate 0
```

**Comment by SteveJobzniak** [comment]
@haasn That's even better, with its ability to do uneven rotation if the user wants that. Great work.

Well, there are now plenty of ideas how mpv could have better built-in rotation out of the box:

1. Add an "indexX" property to cycle which tells it which index to assume we're starting at, to avoid the need to rotate twice to get it to rotate.
2. Bundle a script that's some kind of cleaned up and merged version of haasn and my code.
3. Or create a new built-in function which basically does the same thing as the scripts: Letting you rotate left/right by a certain amount, and wrapping around properly when needed.

Either way, users surely would appreciate a way to rotate videos effortlessly in mpv. :-)

**Comment by SteveJobzniak** [comment]
I've now published this and a few other scripts on the wiki:

https://github.com/mpv-player/mpv/wiki/User-Scripts

* **[auto-keep-gui-open](https://github.com/SteveJobzniak/mpv-tools/blob/master/auto-keep-gui-open.lua)**  
  Intelligently switches mpv's "keep-open" behavior based on whether you are running in video-mode or audio-only mode.

* **[cycle-video-rotate](https://github.com/SteveJobzniak/mpv-tools/blob/master/cycle-video-rotate.lua)**  
  Allows you to perform video rotation which perfectly cycles through all 360 degrees without any glitches.

* **[quick-scale](https://github.com/SteveJobzniak/mpv-tools/blob/master/quick-scale.lua)**  
  Quickly scale the video player to a target size, with full control over target scale and max scale. Helps you effortlessly resize a video to fit on your desktop, or any other video dimensions you need!
