### ISSUE TITLE
How to pass proxy option to youtube-dl?

### ISSUE THREAD

**Issue by blue2018** [mpv-player/mpv#3870]
I'm on Windows 10, When I used the following command to pass --proxy option to youtube-dl, mpv spit out.

mpv --ytdl-raw-options=proxy=[127.0.0.1:1080] "https://www.youtube.com/watch?v=......"

It indicated that the link could not be opened, but I successfully downloaded videos on youtube through this proxy with youtube-dl.
Could you tell me what's wrong with this command? And the correct command is ??
Thank you very much!

**Comment by CounterPillow** [comment]
As far as I know, the proxy option only specifies which proxy youtube-dl fetches the youtube metadata through, from which it then parses the download URLs; the actual video data is downloaded by FFmpeg, not youtube-dl, in mpv's case.

To specify FFmpeg's proxy, try using the `http_proxy` environment variable.

**Comment by haasn** [comment]
Doesn't HTTP_PROXY work?

**Comment by blue2018** [comment]
Oh, yes, http_proxy works well, my problem is solved.
Thanks all guys for your help very much!^_^
