### ISSUE TITLE
[Suggestion] Improve hwdec and opengl-backend probing

### ISSUE THREAD

**Issue by pavelxdd** [mpv-player/mpv#3875]
Can the following way of setting hwdec and opengl-backend be supported? (A list of possible values with priority from first to last, so it's like `auto` value but with an order specified by the user)
````
hwdec=d3d11va,dxva2-copy
````
so when d3d11va fails mpv will try to use dxva2 instead of falling back to software decoding.

And:
````
opengl-backend=angle,dxinterop
````
so mpv will try to use dxinterop if angle fails.
Currently mpv falls back to direct3d vo (!), shouldn't it fall back to opengl win backend at least?

**Comment by wm4** [comment]
> hwdec=d3d11va,dxva2-copy

That's already the default with auto.

> opengl-backend=angle,dxinterop

I don't want to make the probing logic more complicated.

**Comment by pavelxdd** [comment]
> That's already the default with auto.
Probably only for angle? d3d11va (or d3d11va-copy) has never been auto selected for me, mpv always tries to use dxva2 for me.

> I don't want to make the probing logic more complicated.
I see. Can you at least make mpv not to use direct3d vo if angle fails?

**Comment by wm4** [comment]
> Probably only for angle? 

It only works with angle. dxinterop uses d3d9. dxva2-copy is preferred over d3d11va-copy, because it's faster (d3d11va essentially forces 2 copies due to its design).

**Comment by pavelxdd** [comment]
Well, ok. Please consider my second suggestion about direct3d, it doesn't make sense for mpv to use it, when there is a specific instruction vo=opengl in the config.

**Comment by wm4** [comment]
With `vo=opengl` it should fail instead of using vo_direct3d.

In all other situations, you need to make a conscious decision to use dxinterop anyway, because some buggy Intel drivers will just crash the program if you try to resize the window.
