### ISSUE TITLE
At least OpenGL 2.1 required?

### ISSUE THREAD

**Issue by tyngdekraften** [mpv-player/mpv#3876]
mpv master on GNU userland with OpenGL 1.3 support
### Reproduction steps
mpv --vo=opengl
### Expected behavior
works as mplayer -vo gl works
### Actual behavior
[vo/opengl] At least OpenGL 2.1 or OpenGL ES 2.0 required.
### Log file
[log.txt](https://github.com/mpv-player/mpv/files/631847/log.txt)

**Comment by CounterPillow** [comment]
>with OpenGL 1.3 support

Are you running this on a toaster?

**Comment by lachs0r** [comment]
We don’t support GPUs from 2001 and never will.
