### ISSUE TITLE
Add #EXTMPVOPT:  (M3U)

### ISSUE THREAD

**Issue by cipactli** [mpv-player/mpv#3877]
I was playing around with --sub-paths but could not get it working with http streams while it works fine when playing local files.

```
#EXTM3U
#EXTINF:0, Some Title
#EXTMPVOPT:sub-file=/path/to/subtitle.srt
http://someurl.mp4

```

Having this would be cool when generating playlists.

**Comment by wm4** [comment]
Too unsafe.

**Comment by cipactli** [comment]
i dont understand how its unsafe ?
Playing http stream with local subtitle is unsafe, or the m3u feature is unsafe ? Please elaborate..

VLC supports this as well, but im a major fan of mpv, and i really want to use mpv for this.
How to play local subtitle file with http stream in mpv?

thanks

**Comment by wm4** [comment]
Reading local options from a m3u stream is unsafe.

Just use the --sub-file option on the command line.

**Comment by cipactli** [comment]
Okay, I didnt knew that. I will read on this subject, thank you.

I am using --sub-file command, but when playing playlist like m3u i have troubles using the --sub-paths command, even though i rename the local subtitles to match the file name of the http stream from my server.

Is there another way of making this work?

thank you for your time
