### ISSUE TITLE
Allow ytdl to retry connections

### ISSUE THREAD

**Issue by FichteFoll** [mpv-player/mpv#3879]
Youtube-dl sometimes fails to connect to Youtube's data streams (apparently due to their servers being unstable https://github.com/rg3/youtube-dl/issues/11332#issuecomment-264638456) and mpv just goes along with what it has. It would be better if it allowed ytdl to attempt a reconnect so that you don't have to restart mpv entirely when audio is missing.

(Maybe also reduce the timeout? Idk if it's configurable, but for me, either a connection is made within 1s or not within the given 20s.)

### Reproduction steps

Try to play any youtube video via ytdl in mpv.

### Expected behavior

The video plays (with sound).

### Actual behavior

Sometimes audio is missing. Sometimes nothing is found and mpv just closes. Sometimes it works.

### Log file

The following log files were all created for the same video during a span of two minutes on 2016-12-01, in this order.

[mpv_35fBK7kCTgU_1_no_audio.txt](https://github.com/mpv-player/mpv/files/636791/mpv_35fBK7kCTgU_1_no_audio.txt)
[mpv_35fBK7kCTgU_2.txt](https://github.com/mpv-player/mpv/files/636794/mpv_35fBK7kCTgU_2.txt)
[mpv_35fBK7kCTgU_3_no_audio2.txt](https://github.com/mpv-player/mpv/files/636792/mpv_35fBK7kCTgU_3_no_audio2.txt)
[mpv_35fBK7kCTgU_4_fail_both.txt](https://github.com/mpv-player/mpv/files/636793/mpv_35fBK7kCTgU_4_fail_both.txt)
[mpv_35fBK7kCTgU_5.txt](https://github.com/mpv-player/mpv/files/636795/mpv_35fBK7kCTgU_5.txt)

### Sample files

Logs were created with https://www.youtube.com/watch?v=35fBK7kCTgU, but it happens with pretty much every video.

**Comment by wiiaboo** [comment]
Not a fix, but you can add `<key> loadfile "${path}"` to your input.conf to reopen a certain url.

**Comment by FichteFoll** [comment]
Thanks for the tip, @wiiaboo, I've been using that for the past two weeks. Unfortunately, it is still *very* annoying because mpv just closes when ytdl doesn't provide any streams and reloading when playing a video in a playlist causes mpv to reload *just that video* and the playlist is lost.

Because nobody knows why I'm having such connectivity issues with youtube's servers and I don't have much faith in my ISP figuring out the issue, I'll go back to watching in browser now.

**Comment by FichteFoll** [comment]
I just want to mention that apparently disabling ipv6 had an *immensely positive* effect on my particular issue. I did this by disabling it in my network config but later found out that youtube-dl also has a `-4` option, so I'll use that in the future.

Finally I can use mpv for youtube again.

**Comment by wiiaboo** [comment]
I think the recent network changes already implement delayed retrying already.
