### ISSUE TITLE
Can't make slideshow using -mf-fps 0.25 on Windows

### ISSUE THREAD

**Issue by tmpsa** [mpv-player/mpv#3880]
### mpv version and platform

mpv 0.22.0-git-1d4273c (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 20 18:59:12 CET 2016

Mpv for Windows,
mpv-x86_64-20161204-git-796b48b

### Reproduction steps

'mpv -vo drm --mf-fps 0.25 foo.jpg bar.jpg'

mpv.conf contains:

quiet
no-audio
no-sub-auto
video-rotate=90

### Expected behavior

I can successfully make a slide show on Linux with 'mpv -vo drm --mf-fps 0.25 foo.jpg bar.jpg', which shows both images during 4 seconds each. (That's 0.25 frames per second).

### Actual behavior

But on Windows the images are shown only briefly, presumably just as long as it takes for mpv to reload next image.

This looks like a bug in the Windows port. I have reported it here:
https://github.com/shinchiro/mpv-winbuild-cmake/issues/12#event-885251620
But it was closed there with the statement that it should be reported here, instead.

### Log file

http://lab.facilitylabs.com/tmp/mpv-log.txt

**Comment by wm4** [comment]
This changed. Either use mf://, or `--image-display-duration=4`.

**Comment by tmpsa** [comment]
Thanks! FYI:
This works: mpv -vo drm --image-display-duration=4 foo.jpg bar.jpg
This does not work: mpv -vo drm mf-fps 0.25 mf://foo.jpg mf://bar.jpg

I presume that the change is made recently. Any information about when it will be generally available in Ubuntu 16.04.1 LTS?

**Comment by lachs0r** [comment]
Never. Ubuntu 16.04 LTS will not update mpv.

**Comment by tmpsa** [comment]
Makes sense. So I should use a slightly older Windows build to be compatible over the two platforms, then. Any information when --image-display-duration was introduced? In other words, which Windows build should I look for?

**Comment by lachs0r** [comment]
Or you could just build mpv on Linux yourself (use mpv-build, it makes this rather easy) and carry on.
