### ISSUE TITLE
mpv leaves DPMS disabled when a live stream ends

### ISSUE THREAD

**Issue by LoneFox78** [mpv-player/mpv#3881]
### mpv version and platform
 0.22.0 on linux x86_64
### Reproduction steps
Watch a live stream (with livestreamer or streamlink) when the stream ends.
### Expected behavior
DPMS should be restored to the state it was before starting mpv.
### Actual behavior
DPMS is left disabled.

**Comment by wm4** [comment]
Can't reproduce.

**Comment by LoneFox78** [comment]
You didn't even try, as it is 100% reproducible. Based on this and your response to my other bug report, looks like it is time to start looking for a replacement for mpv, one with more honest and competent developers... :(

That said, this turned out to be a misfeature of streamlink. It is using SIGKILL to close the player, so no cleanup can happen.

**Comment by wm4** [comment]
Yes, I did try, just not with streamlink. I don't care whether you use mpv or not. How about fuck you.
