### ISSUE TITLE
Subtitles stop working after first 32kB

### ISSUE THREAD

**Issue by LoneFox78** [mpv-player/mpv#3882]
### mpv version and platform
0.22.0 on linux x86_64 with libav 11.8 or 12, same behavior in both versions.
Windows version of mpv works properly, I suspect it may be libav vs. ffmpeg compatibility problem.
### Reproduction steps
Play any video with srt subtitle file that is larger than 32kB. I don't know if it affects other subtitle formats too.
### Expected behavior
Subtitles working as they should. You know what that means...
### Actual behavior
Subtitles stop displaying after first 32kB exactly, often in the middle of a word.

**Comment by wm4** [comment]
Subtitles under Libav are not supported. Use FFmpeg.

**Comment by Beep6581** [comment]
What does "Subtitles under Libav are not supported" mean?

**Comment by CounterPillow** [comment]
Subtitles aren't supported if you build with Libav instea of FFmpeg.

**Comment by CounterPillow** [comment]
>For many "Use FFmpeg" is not an option (distro ships only one or the other)

then don't use the turd your distro ships but use [mpv-build](https://github.com/mpv-player/mpv-build)

**Comment by Beep6581** [comment]
It's evident there are some strong emotions here, but you're not being clear on what the problem is. Failing at `0x8000` looks like a signed short int bug. Are you saying this bug lies in libav? Or is libav's API incompatible with mpv? Or what? Let's be constructive.

**Comment by wm4** [comment]
Not really strong emotions, just emphasizing that we won't fix it or try to debug it. Libav's subtitle support is just too behind and there's no reason for us to care about it. Your distro argument also doesn't work. So either you analyze/fix the bug yourself, or just use ffmpeg.

**Comment by LoneFox78** [comment]
Here is a kludge around it. This makes the initial buffer larger, so that the subtitle file completely fits in it, and there is no need to ever fetch more. You need to patch both mpv and libav. It has potential of breaking other programs (anything that hardcodes this buffer size needs a similar patch), but I have used it for several months without any problems.

	diff -bur mpv-0.23.0-orig/demux/demux_lavf.c mpv-0.23.0/demux/demux_lavf.c
	--- mpv-0.23.0-orig/demux/demux_lavf.c  2016-12-25 15:12:38.000000000 +0200
	+++ mpv-0.23.0/demux/demux_lavf.c       2017-01-14 13:47:44.000000000 +0200
	@@ -56,7 +56,7 @@
	 
	 // Should correspond to IO_BUFFER_SIZE in libavformat/aviobuf.c (not public)
	 // libavformat (almost) always reads data in blocks of this size.
	-#define BIO_BUFFER_SIZE 32768
	+#define BIO_BUFFER_SIZE 131072
	 
	 #define OPT_BASE_STRUCT struct demux_lavf_opts
	 struct demux_lavf_opts {

---

	diff -bur libav-12-orig/libavformat/aviobuf.c libav-12/libavformat/aviobuf.c
	--- libav-12-orig/libavformat/aviobuf.c 2016-10-17 00:10:02.000000000 +0300
	+++ libav-12/libavformat/aviobuf.c      2017-01-14 13:47:34.000000000 +0200
	@@ -31,7 +31,7 @@
	 #include "url.h"
	 #include <stdarg.h>
	 
	-#define IO_BUFFER_SIZE 32768
	+#define IO_BUFFER_SIZE 131072
	 
	 /**
	  * Do seeks within this distance ahead of the current buffer by skipping
