### ISSUE TITLE
mpv filters: rotate videos as per metadata but fit in the size mentioned as per -vf filters

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3884]
I am using the following commad to use filters in the mpv and its working.

`mpv --vf="lavfi=[scale='min(320,iw)':min'(240,ih)':force_original_aspect_ratio=decrease,pad=320:240:(ow-iw)/2:(oh-ih)/2,setsar=1:1,setdar=4:3]" *.mp4`

I want to see all the videos in the 320x240 size screen and add padding accordingly

But videos having metadata of rotate=90 are showing as 240x320. 

I dont mind video being rotated, but i want it to be shown in the 320x240 box rather than 240x320 box

Whereas ffmpeg does as per i wanted. 

I have a bunch of files (with some having metadat of rotate=90)

I tried:

```
        for i in *.mp4
        do
        ffmpeg -i $i -codec:v libx264 -crf 20 -vf "scale='min(320,iw)':min'(240,ih)':force_original_aspect_ratio=decrease,pad=320:240:(ow-iw)/2:(oh-ih)/2,setsar=1:1,setdar=4:3" -c:a copy resize_$i
         done
```

Now all the videos are of size 320x240 and the videos with rotate=90 in metadata also got fit in the 320x240 and rotated to 90

where as in the mpv the the metadata rotate=90 is rotating 320x240 itself and shows as 240x320.

I tried to use 

--video-rotate=no:

`mpv --vf="lavfi=[scale='min(320,iw)':min'(240,ih)':force_original_aspect_ratio=decrease,pad=320:240:(ow-iw)/2:(oh-ih)/2,setsar=1:1,setdar=4:3]" --video-rotate=no *.mp4`

video fits in 320x240 but vidoes with rotate=90 are shown flat (horizontal)

**Comment by wm4** [comment]
I have no idea wtf these lavfi command lines do.

**Comment by sant527** [comment]
How to watch a bunch of videos in the same window size. Padding will be added to keep the aspect ratio same.

**Comment by wm4** [comment]
Use --geometry?
