### ISSUE TITLE
Disable debanding on 10-bit videos.

### ISSUE THREAD

**Issue by kkanungo17** [mpv-player/mpv#3889]
### mpv version and platform ###

Is there a way to disable debanding on 10-bit videos?

**Comment by wm4** [comment]
No. But you could hack together something using https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua

In general I don't think this is needed, though. 10 bit files can have banding too, and the deband filters is very light in its defaults.

**Comment by lachs0r** [comment]
Well, maybe not *very* light, but if you reduce the threshold to something like 48, it should be quite okay for just about anything.

**Comment by kkanungo17** [comment]
Debanding just gets a little too much for my toaster to handle on 10-bit 1080p files, so I was looking for a way to automate it.

Does reducing the threshold reduce cpu usage?

**Comment by haasn** [comment]
> Does reducing the threshold reduce cpu usage?

No, but decreasing the range and/or number of iterations can slightly improve it. It's also the GPU load you're concerned with, not the CPU load.

**Comment by kkanungo17** [comment]
I can't get the script to work with the video-params/plane-depth property.

**Comment by kkanungo17** [comment]
Never mind, I got it to work.
