### ISSUE TITLE
I am getting a new second hand laptop: what is the minimum OpenGL for full opengl-hq profile support? 

### ISSUE THREAD

**Issue by okhs** [mpv-player/mpv#3892]
Is OpenGL 3.3 support enough from the display adapter and display adapter driver, or do I need OpenGL 4.5? 
Thanks

**Comment by wm4** [comment]
OpenGL 3.0 is currently enough.

**Comment by wm4** [comment]
PS: the OpenGL version doesn't matter too much - what does is the pixel fillrate and memory transfer speed.
