### ISSUE TITLE
Arabic Subtitle

### ISSUE THREAD

**Issue by ShevoPramide** [mpv-player/mpv#3893]
when i tried to load an arabic subtitle it shows only strange language not arabic. 
![image](https://cloud.githubusercontent.com/assets/23216006/21074776/ea80b6be-bf09-11e6-86b8-d1ca994dc7db.png)

**Comment by wiiaboo** [comment]
Samples, mpv log, etc. Read what was in the issue template.

**Comment by CounterPillow** [comment]
This is most likely a problem with your subtitle file having the wrong text encoding.

**Comment by lachs0r** [comment]
1) Make sure your subtitles are UTF-8
2) If that is too much effort, make sure mpv is compiled with uchardet support
3) If uchardet fails to detect the encoding, manually specify it using `--sub-codepage`
