### ISSUE TITLE
Parsing failure (comma in filename?) with loadfile/external-file in IPC.

### ISSUE THREAD

**Issue by woodruffw** [mpv-player/mpv#3898]
Came across this while writing a program that controls an mpv session:

### mpv version and platform

```
[cplayer] mpv git-51fd8f6 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri Dec  9 03:51:07 UTC 2016
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.34.100
[cplayer]    libavcodec      57.64.101
[cplayer]    libavformat     57.56.100
[cplayer]    libswscale      4.2.100
[cplayer]    libavfilter     6.65.100
[cplayer]    libswresample   2.3.100
[cplayer] ffmpeg version: 3.2.2
```

### Reproduction steps

Start mpv with an IPC socket (`--input-ipc-server`), and attempt to issue a `loadfile` command with an `external-file` argument that has a comma in it.

Example:

```
{
   "command":[
      "loadfile",
      "/home/william/music/Tyler, The Creator/Wolf/16. Treehome95 (feat. Erykah Badu & Coco Owino).flac",
      "append-play",
      "external-file=/home/william/music/Tyler, The Creator/Wolf/Cover.jpg"
   ]
}
```

This yields the following error:

```
[ipc_0] Expected '=' and a value.
[ipc_0] Command loadfile: argument 3 can't be parsed: option could not be parsed.
```

This error does *not* occur when issued as an argument on the command line (i.e., `--external-file`).

### Expected behavior

`mpv` should load the given file and use `external-file` as cover art (I know this isn't what it's strictly meant for, but it works in the general case).

### Actual behavior

`mpv` spits out the error message above and ignores the `loadfile` command.

### Log file

http://hastebin.com/raw/oyodivugat

### Sample files

Can't share music for copyright reasons, but you should be able to replicate this with any path containing a comma passed to `external-file`.

**Comment by woodruffw** [comment]
Realized that enclosing the `external-file` argument in quotes resolves the problem. Assuming it was human error, not an actual parser error and closing this.

**Comment by wm4** [comment]
It's because the last argument is actually a `,` separated list of options.

Also, jpg files are interpreted as 1-frame video, and adding that as video track can have weird consequences (like doing a non-precise seek backwards will always seek back to position 0).
