### ISSUE TITLE
-loop flag is undocumented or unexpectedly supported

### ISSUE THREAD

**Issue by syphoxy** [mpv-player/mpv#3899]
### mpv version and platform

```
% mpv --version
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.5
```

```
% rpm -q mpv    
mpv-0.22.0-1.fc24.x86_64
```

### Reproduction steps

```
% mpv -loop FILES
```

this is apparently equivalent to `--loop=inf` but undocumented in the man page. found this out when I accidentally ran `mpv -loop inf FILES` and saw an error message about an non-existent file named `inf`.

I'm honestly willing and interested in creating the pull request for this myself but I'm not sure if this feature is unexpectedly supported or where to add it to. just looking to start a discussion on the direction to take on this inconsistency. thanks!

### Expected behavior

the command should either error about an invalid command or the man page should document the flag.

### Actual behavior

man page has no reference of `-loop` flag.

```
% PAGER=cat man mpv 2>/dev/null | grep -F -- -loop
       l      Set/clear A-B loop points. See ab-loop command for details.
       --loop=<N|inf|force|no>
       --loop-file=<N|inf|no>
              Loop a single file N times. inf means forever, no means normal playback. For compatibility, --loop-file and --loop-file=yes are also accepted, and are the same as --loop-file=inf.
              The difference to --loop is that this doesn't loop the playlist, just the file itself. If the playlist contains only a single file, the difference between the two option is that this option performs a seek on loop, instead of reloading the file.
       --ab-loop-a=<time>, --ab-loop-b=<time>
              The loop-points can be adjusted at runtime with the corresponding properties. See also ab-loop command.
              Do  not  terminate when playing or seeking beyond the end of the file, and there is not next file to be played (and --loop is not used).  Instead, pause the player. When trying to seek beyond end of the file, the player will attempt to seek to the last
       ab-loop
              Cycle through A-B loop states. The first command will set the A point (the ab-loop-a property); the second the B point, and the third will clear both points.
```

### Log file

No log necessary.

### Sample files

No sample files necessary.

**Comment by haasn** [comment]
This is very much intended behavior. First of all, “-loop” and “--loop” are essentially the same thing in the mpv parser.

The underlying “issue” here is that `--loop` without an argument is treated as `--loop=inf` by default, because I thought it was the obvious thing to do. `mpv --loop A B C` should loop A, B, C to me.

The unfortunate downside of `--loop inf X` being ambiguous between `--loop=inf X` and `--loop=<default> inf X` is a limitation of the parsing system iirc. It would be nice if `--loop <valid argument for loop> foo` would be treated as `--loop=foo` instead of as a bare `--loop`, but I don't think making that the case is very easy.

**Comment by mc4man** [comment]
The *current* man is a little ambiguous in that it says for --loop=  "Loops playback N times. A value of 1 plays it one time (default),"   Maybe that implies the default of 1 play when there is no --loop* option at all?
However when  --loop=  is presented without any value it seems to be *yes* which is the same as inf & the same as seen with just plan --loop or -loop

**Comment by wm4** [comment]
Just don't use the legacy option syntax. I made that explicit in the general option syntax part of the manpage (probably again).

> It would be nice if --loop <valid argument for loop> foo would be treated as --loop=foo instead of as a bare --loop

MPlayer had the capability to do this (and probably needs it because it has only what I call "legacy" syntax). I found it too complex and ditched it.
