### ISSUE TITLE
Combined mouse key bindings (MOUSE_BTNx-...) work wrongly: commands defined for the first buttons are triggered when you press the rest for the first time (while holding the first ones)

### ISSUE THREAD

**Issue by przemoc** [mpv-player/mpv#390]
Combined mouse buttons unexpectedly trigger commands defined for the first buttons when you press the rest for the first time (while holding the first ones).

---

Set following `input.conf`:

```
## MOUSE_BTN0 = left button
## MOUSE_BTN1 = middle button
## MOUSE_BTN2 = right button
# MOUSE_BTN2 cycle pause # builtin
MOUSE_BTN2-MOUSE_BTN0 seek -5 relative exact
MOUSE_BTN2-MOUSE_BTN1 seek  5 relative exact
MOUSE_BTN2-MOUSE_BTN0-MOUSE_BTN1 print_text test
```

Perform following scenario using mouse:
1. Press right button and release it.
2. Press right button.
3. Press middle button.
4. Release middle button.
5. Release right button.
6. Press right button.
7. Press left button.
8. Press middle button.
9. Release middle button.
10. Release left button.
11. Release right button.
12. Press right button.
13. Press middle button.
14. Press left button.
15. Release left button.
16. Release middle button.
17. Release right button.

What happens and what should happen:

After 1 playing is paused - ok.

After 2 nothing happens - ok.
After 3 playing is _resumed_ - wrong, nothing should happen now!
After 4 video is sought 5 second forward - ok.
(Repeating 3-4 doesn't cycle pause property again.)
After 5 nothing happens - ok.

After 6 nothing happens - ok.
After 7 video is _paused_ - wrong, nothing should happen now!.
After 8 video is sought 5 seconds backward - wrong, nothing should happen now!
After 9 "test" is printed to stdout - ok.
(Repeating 8-9 doesn't seek video 5 seconds backward again.)
After 10 nothing happens - ok.
After 11 nothing happens - ok.

After 12 nothing happens - ok.
After 13 playing is _resumed_ - wrong, nothing should happen now!
After 14 video is sought 5 second forward - wrong, nothing should happen now!
After 15 nothing happens - wrong, there should be `[input] No bind found for key 'MOUSE_BTN2-MOUSE_BTN1-MOUSE_BTN0'.` message.
(Repeating 14-15 doesn't seek video 5 seconds forward again.)
After 16 nothing happens - ok.
(Repeating 13-16 does seek video 5 seconds forward, which is obviously wrong.)
After 17 nothing happens - ok.

---

Tested on `mpv` git-b18f02d built using `debuild` on `mpv-build` (`
waf-plus-kill-submodules` branch, yesterday bleeding-edge versions) in up-to-date debian wheezy amd64.

---

P.S. _Why am I using combined key bindings?_
When you watch shows using mpv on TV, you may have wireless mouse, but lack such keyboard, and then you're enforced to use combined key bindings.

**Comment by MaurizioB** [comment]
Maybe I'm getting this wrong, but it looks like the behavior now is that, once the command is completed, it "resets" the still pressed down button. For example, I used right click + scroll wheel to set the volume (weird, I know), this works for the first scroll "click", but at the second one the right click is ignored, so I have to release and press right click again.
Is this expected? I understand that this is a unusual and, maybe, trivial case. I'd just like to understand if it can be "corrected" or it's not expected to work like that anymore because of the new input modes.

**Comment by wm4** [comment]
This was changed a bunch of times, and I don't myself anymore what is expected and how it should work. Yes, it could be that all keys are released when 1 key is released (except for modifiers like shift).

**Comment by GribanovIvan** [comment]
If you are looking how to bind mouse buttons, what valve named mouse4 and mouse5 - try MOUSE_BTN8 and MOUSE_BTN7, yes, 8 and 7, strange, but worked for me.

**Comment by CasualPlayer96** [comment]
> If you are looking how to bind mouse buttons, what valve named mouse4 and mouse5 - try MOUSE_BTN8 and MOUSE_BTN7, yes, 8 and 7, strange, but worked for me.

Ah thanks, you saved me.
