### ISSUE TITLE
How to output 48khz audio when using sofalizer?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#3903]
### mpv version and platform

```
mpv git-51fd8f6 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Fri Dec  9 03:51:07 UTC 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.2

```

It always show me 44100hz in the terminal, how to output 48khz audio when using sofalizer?

**Comment by richardpl** [comment]
Depends on SOFA file you use what is accepted sample rate it use for input.
you can add another filter after sofalizer:

`-af sofalizer=....,aresample=48000`

**Comment by JulianLai** [comment]
@richardpl Their voice become so funny after I set it to 96000

**Comment by richardpl** [comment]
Dolby Atmos have nothing to do with HRTFs, its different way of representing/reproducing/storing sounds.
I don't have equipment to test it....

**Comment by kevmitch** [comment]
> By the way, why does DTS-HDMA sounds better than Dolby Atmos with Sofalizer?

Softalizer requires the audio to be decoded first. Last I checked, it is not possible to decode Dolby Atmos in software. So what's going into softalizer is probably some degraded fallback,

**Comment by JulianLai** [comment]
@kevmitch The Dolby Atmos is really noisy, but the DTS-HDMA is clear, so strange.

**Comment by ChrisK2** [comment]
> Dolby Atmos have nothing to do with HRTFs, its different way of representing/reproducing/storing sounds.

In their sheer brilliance, Dolby invented a HRTF system and ALSO named that "Atmos". (The game Overwatch features this and I think there are also a few Blu-rays out there with a 2.0 Atmos track)

**Comment by lachs0r** [comment]
I think this has been answered (depends on the SOFA file).
