### ISSUE TITLE
Cannot use Mali GLES driver for playback

### ISSUE THREAD

**Issue by Icenowy** [mpv-player/mpv#3905]
### mpv version and platform

Linux/ARM 4.9 with Mali patches

MPV latest git

### Reproduction steps

Use the Mali GLES blob from NextThingCo, and kernel side from Maxime Ripard.

(The mali blob version is r6p0, and glmark2-es2 runs without problem, so does other GLES2 programs)

### Expected behavior

Playback with Mali GLES.

### Actual behavior

Failure.

### Log file

https://pastebin.anthonos.org/view/7bd8e52f

**Comment by Icenowy** [comment]
Sorry, the log file is not full...

Please read this:

https://pastebin.anthonos.org/view/93af6a30

**Comment by wm4** [comment]
No backend compiled. Unless someone explicitly makes it work for whatever device you have (maybe by adapting context_mali_fbdev.c) it's unlikely that it will be supported out of the box. But fortunately the performance would most likely be crap anyway, so nothing can be done.

**Comment by wm4** [comment]
Btw. also could be done by adding a dlopen fallback for eglGetProcAddress. But again, vendor specific.

**Comment by Icenowy** [comment]
It's a generic X11 EGL&GLES DRM device, not a FBDEV GLES device, so I don't think it's platform-specified.
(NextThingCo didn't even provide a FBDEV-based or DRM-based blob, only the X11-based one)
I said that glmark2-es2 works properly (this is a X11-based program).
And all programs that uses OpenGL ES2 with X11 and compiled with Mesa can switched to thie Mali blob easily with library replacment.
@wm4

**Comment by wm4** [comment]
The mpv x11 backend doesn't work here, because the driver doesn't provide a certain EGL extension we've been relying on, so further hackery would be required (like a fallback to dlopen).

But performance would be crap anyway.

**Comment by paulreimer** [comment]
Forgive my ignorance about this GPU (I have the same board and also want to use `mpv` for OpenGL shader purposes), but why would performance be crap -- is this mainly a hardware issue (e.g. no acceleration), or a software/driver issue (e.g. not optimized or something is not supported... yet)?

**Comment by wm4** [comment]
@paulreimer these boards have really bad OpenGL shader performance, so you can usually not use them for video. If a vendor advertises video support (1080p realtime, 4K realtime etc.) they mean their proprietary video API and hardware, which has nothing to do with OpenGL.

Even if a board has pretty good performance, it'll usually not be as fast as the vendor's fixed function video code.

In addition, these vendors typically don't support sampling decoded video from shaders (like you can do with VAAPI or D3D11VA), and even if they do, it involves forced RGB conversion before the shader sees the data.

**Comment by paulreimer** [comment]
Thanks @wm4 that does help! I'm starting down a rabbit hole here but I hope to emerge soon with a HW accelerated VAAPI driver for this board (https://github.com/linux-sunxi/libvdpau-sunxi), which uses `mpv` to verify (and this specific board was apparently verified as per https://bbs.nextthing.co/t/corrupt-picture-with-h264-encode-in-hardware-using-cedar-ve/14612):
```
mpv --vo=vdpau --hwdec=vdpau --hwdec-codecs=all test.mov
```

My HW-accelerated video knowledge is limited (just started this morning!), but my C++/GLSL knowledge is decent, does access to VAAPI help in the case of getting OpenGL filtering/shaders working on this board with `mpv`? My needs are a basic box blur effect, and/or static color blending, for example.

**Comment by wm4** [comment]
VAAPI isn't VDPAU. Also, while VDPAU (and VAAPI) on Linux usually enable you to video frames  as OpenGL textures, I'm fairly sure sunxi doesn't do that.

**Comment by paulreimer** [comment]
Gotcha. Is there a single-board-computer for this purpose that is recommended or closest to working at this time? RPi3, Odroid C2, etc?

**Comment by wm4** [comment]
The Odroid C2 GPU is relatively powerful and enough for rendering 1080p per shader (but not 4K), but supports only GLESv2 from what I remember. Crap.

Maybe a NUC?
