### ISSUE TITLE
Nvidia VDPAU and MPV: Is this Nvidia.com page for MPlayer applicable to MPV too?

### ISSUE THREAD

**Issue by timofonic** [mpv-player/mpv#3907]
Hello.

Is this applicable to MPV too? It would be interesting to make Nvidia know MPV exists too. Tons of people still mention MPlayer, despite MPV is a lot better :D 

https://devtalk.nvidia.com/default/topic/523241/linux/if-you-have-a-problem-with-vdpau-and-or-mplayer-vdpau-please-read-this-first/

**Comment by wm4** [comment]
No, most of it applies to mplayer only. This page was made in the early days, when mplayer was the only thing to support vdpau on Linux.
