### ISSUE TITLE
How to format OSD text in Lua scripts?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3913]
Hi,

Is it possible to format (i.e. to color, bold, italic, etc.) certain word(s) in OSD text?

E.g. how to make `mp.osd_message("This word is red.")` to draw the word _red_ in red color?

Afaik, there should be escape codes for this, but I can't find anything about it in man pages...

Regards,
Alex

**Comment by paulguy** [comment]
I think this might do what you want: https://mpv.io/manual/stable/#command-interface-osd-ass-cc

**Comment by fhlfibh** [comment]
@paulguy Seems like that's it, thanks!

**Comment by Argon-** [comment]
This is exactly what you want/need. I'm pretty much using it in each of my scripts, some also coloring text red. 
Wht did you try so far?

**Comment by fhlfibh** [comment]
@Argon- 
So far I tried `mp.osd_message("This is ${osd-ass-cc/0}{\b1}bold text", 10)`, plus its combinations I could think of.

**Comment by Argon-** [comment]
Let me quote the manual:
> ${osd-ass-cc/0} **disables** escaping ASS sequences

**Comment by fhlfibh** [comment]
@Argon- there's no need to quote me the manual. I tried osd-ass-cc/1 and the hell of other combinations too -- the result was pretty much the same.
If you say your scripts work correctly with these escape codes -- i will try to figure something out of them.

**Comment by Argon-** [comment]
Oh, you are using a lua script, but `${osd-ass-cc/1}` is a property. You need to get it first: `mp.get_property_osd("osd-ass-cc/1")`
When activated you can use all ASS sequences (these are _not_ properties, you can just use them).
Working example:

     local ass_start = mp.get_property_osd("osd-ass-cc/0")
     local ass_stop = mp.get_property_osd("osd-ass-cc/1")
     mp.osd_message(ass_start .. "{\\1c&H0000FF&}text" .. ass_stop)

**Comment by fhlfibh** [comment]
@Argon- 
This way it finally works, thanks!
