### ISSUE TITLE
`[` command (decrease playback speed) skips back playback position

### ISSUE THREAD

**Issue by NoNoNo** [mpv-player/mpv#3916]
### mpv version and platform

mpv 0.22.0 on macOS 10.12.1

### Reproduction steps

1. `mpv --no-config --speed=2 SOMEVIDEO.mp4`
2. (Wait a few seconds)
3. Press `[` to decrease playback speed

### Expected behavior

* Playback speed decreases and playback positions stays

### Actual behavior

* Playback speed decreases, but playback positions skips back a few seconds

### Log file

Relevant part:

````
[cplayer] first video frame after restart shown
[cplayer] starting audio playback
[cplayer] playback restart complete
[statusline] AV: 00:00:15 / 00:26:00(0%) x2.00 A-V:  0.000 Dropped: 153
[cplayer] Run command: multiply, flags=9, args=[speed, 0.909100]
[cplayer] Set property: speed -> 1
[statusline] AV: 00:00:15 / 00:26:00 (0%) x1.82 A-V:  0.000 Dropped: 153
[cplayer] Run command: seek, flags=9, args=[-5.000000, relative, unused]
[lavf] queuing seek to 10.640000
[lavf] execute seek (to 10.640000 flags 8)
[lavf] seek done
[statusline] AV: 00:00:10 / 00:26:00 (0%) x1.82 A-V:  0.000
````

Thanks & greetings!

**Comment by lachs0r** [comment]
Can’t reproduce.
