### ISSUE TITLE
Playback speed degrades audio impulses

### ISSUE THREAD

**Issue by NoNoNo** [mpv-player/mpv#3917]
### mpv version and platform

mpv 0.22.0 on macOS 10.12.1

### Reproduction steps

1. `mpv --no-config --speed=1.6 'https://www.youtube.com/watch?v=ucZl6vQ_8Uo'`

### Expected behavior

* Every beat sounds the same

### Actual behavior

* Beats differ in sound

Thanks & greetings!

**Comment by kevmitch** [comment]
This is the fault of the `scaletempo` audio filter which is inserted by default with non-unity speeds (I'm not sure why). There is no problem with `audio-pitch-correction=no`.

**Comment by lachs0r** [comment]
(`--af=rubberband` could slightly improve this, but it comes with its own kind of artifacts.)

**Comment by ale-rinaldi** [comment]
Really late to the party, but for someone like me coming here for the same issue I can confirm that @lachs0r solution (`--af=rubberband`) is much more pleasant to hear.  

It does actually have other kinds of artifacts, but it's actually impossible to change speed and not pitch without some kind of artifacts.  

The builtin solution gives back some clearly audible glitches, while Rubberband just causes some phase shift that is quite acceptable.

Thanks for sharing this!

**Comment by ale-rinaldi** [comment]
Additional note:
if the rubberband artifacts are not acceptable for you, you can try playing with scaletempo stride amount. I got a pleasant result with: `mpv --af=scaletempo=stride=30`

**Comment by wm4** [comment]
I'm open for better scaletempo default values.

**Comment by ale-rinaldi** [comment]
Great to hear! So, I'll play with them a little more and let you know what I'll come up with.  
For now I'm quite happy with `--af=scaletempo=stride=30:search=20`

**Comment by ale-rinaldi** [comment]
FYI I'm working on a script to align a source stream with a timecode in ICY metadata between multiple different PCs. To achieve this I constantly change speed, so I'm looking for a setting that doesn't produce weird results in this situation.
