### ISSUE TITLE
Seeking is borked with bink video

### ISSUE THREAD

**Issue by mzso** [mpv-player/mpv#3918]
Hi!

Seeking is pretty unreliable with these videos. If I seek via mouse it sometimes succeeds, sometimes fails and goes back to the start of the video. Hotkey seeking on the other hand never works, the video always starts playing from the beginning.
I get a lot of "Invalid audio PTS: 1.567347 -> 0.827211" type warnings, and a few "Audio/Video desynchronisation detected! [...]" warnings while seeking.

Note: I noticed that I can seek suck videos with a dshow player using LAV filters. Which is also based on libavcodec/ffmpeg. (To the best of my knowledge). So I wonder why is this.

**Comment by wm4** [comment]
Bink is a reverse-engineered codec, so the implementation in ffmpeg is probably not the best.

**Comment by wm4** [comment]
I also should say this:

> I get a lot of "Invalid audio PTS: 1.567347 -> 0.827211" type warnings

means the codec most likely doesn't flush correctly, and returns old frames from before the seek or such.

**Comment by mzso** [comment]
[**@wm4**](https://github.com/wm4) commented on [2016. dec. 18. 15:52 CET](https://github.com/mpv-player/mpv/issues/3918#issuecomment-267825469 "2016-12-18T14:52:33Z - Replied by Github Reply Comments"):
> Bink is a reverse-engineered codec, so the implementation in ffmpeg is probably not the best.

I see. So you suggest means that LAV has some enhancements on it'd end?

**Comment by Hrxn** [comment]
> description:	ffmpeg with custom patches for LAV Filters

https://git.1f0.de/gitweb?p=ffmpeg.git;a=summary

**Comment by wm4** [comment]
> So you suggest means that LAV has some enhancements on it's end?

I doubt it.

**Comment by mzso** [comment]
[**@wm4**](https://github.com/wm4) commented on [2016. dec. 18. 16:17 CET](https://github.com/mpv-player/mpv/issues/3918#issuecomment-267826955 "2016-12-18T15:17:55Z - Replied by Github Reply Comments"):
> > So you suggest means that LAV has some enhancements on it's end?
> 
> I doubt it.

It, for a fact works a lot better for bink files. So I don't know what else would explain it.

**Comment by richardpl** [comment]
Can you provide file so I could reproduce and possible fix the issue if it actually exist?

**Comment by wm4** [comment]
> It, for a fact works a lot better for bink files. So I don't know what else would explain it.

Could be another reason. It could use some dshow bink decoder, or recreate the decoder context on each seek. I doubt that the developer is spending any time to fix a shitty and obscure codec like Bink.

**Comment by mzso** [comment]
[**@wm4**](https://github.com/wm4) commented on [2016. dec. 18. 16:28 CET](https://github.com/mpv-player/mpv/issues/3918#issuecomment-267827448 "2016-12-18T15:28:00Z - Replied by Github Reply Comments"):
> > It, for a fact works a lot better for bink files. So I don't know what else would explain it.
> 
> Could be another reason. It could use some dshow bink decoder, or recreate the decoder context on each seek. I doubt that the developer is spending any time to fix a shitty and obscure codec like Bink.

Speaking of... Can't mpv do such workarounds? 


[**@richardpl**](https://github.com/richardpl) commented on [2016. dec. 18. 16:22 CET](https://github.com/mpv-player/mpv/issues/3918#issuecomment-267827144 "2016-12-18T15:22:07Z - Replied by Github Reply Comments"):
> Can you provide file so I could reproduce and possible fix the issue if it actually exist?

Yes. Here it is: https://drive.google.com/open?id=0ByfdfPvnoDuzOVpWQTZ1Ym1aOWs
(Though it's likely proprietary)

**Comment by wm4** [comment]
> Can't mpv do such workarounds?

Could, but won't.

**Comment by mzso** [comment]
[**@wm4**](https://github.com/wm4) commented on [2016. dec. 18. 17:04 CET](https://github.com/mpv-player/mpv/issues/3918#issuecomment-267829440 "2016-12-18T16:04:43Z - Replied by Github Reply Comments"):
> > Can't mpv do such workarounds?
> 
> Could, but won't.

So what's the reason for this?

**Comment by Hrxn** [comment]
^ Not investing in platform specific features such as hooking into dshow on Windows?

**Comment by mzso** [comment]
[**@Hrxn**](https://github.com/Hrxn) commented on [2016. dec. 18. 17:35 CET](https://github.com/mpv-player/mpv/issues/3918#issuecomment-267831113 "2016-12-18T16:35:29Z - Replied by Github Reply Comments"):
> ^ Not investing in only platform specific features such as hooking into dshow on Windows?

It wasn't about hooking into dshow: "recreate the decoder context on each seek"

**Comment by richardpl** [comment]
bink as format doesn't hold audio timestamps anywhere in packets...

**Comment by mzso** [comment]
[**@richardpl**](https://github.com/richardpl) commented on [2016. dec. 18. 17:57 CET](https://github.com/mpv-player/mpv/issues/3918#issuecomment-267832407 "2016-12-18T16:57:17Z - Replied by Github Reply Comments"):
> bink as format doesn't hold audio timestamps anywhere in packets...

If you meant this for me I don't know what you're getting at. :)

So, did you look at the sample I uploaded?

**Comment by richardpl** [comment]
I did, but I do other things also but for money you know...

**Comment by mzso** [comment]
[**@richardpl**](https://github.com/richardpl) commented on [2016. dec. 18. 18:13 CET](https://github.com/mpv-player/mpv/issues/3918#issuecomment-267833364 "2016-12-18T17:13:20Z - Replied by Github Reply Comments"):
> I did, but I do other things also but for money you know...

It wasn't meant as nagging. Just to verify that you didn't miss that comment/upload.

**Comment by lachs0r** [comment]
Only HR seeking works with Bink. That also explains why it would work with LAV. Anyway, file an FFmpeg bug if you watch so many video game cutscenes you absolutely need this to work. Or bother us (in a separate feature request, because it does not concernt a specific video format) to make the OSC honor `--hr-seek=always` and set that in a profile called `[extension.bik]`.

**Comment by mzso** [comment]
[**@lachs0r**](https://github.com/lachs0r) commented on [2017. júl. 22. 05:31 CEST](https://github.com/mpv-player/mpv/issues/3918#issuecomment-317150983 "2017-07-22T03:31:56Z - Replied by Github Reply Comments"):
> Only HR seeking works with Bink. That also explains why it would work with LAV. Anyway, file an FFmpeg bug if you watch so many video game cutscenes you absolutely need this to work. Or bother us (in a separate feature request, because it does not concernt a specific video format) to make the OSC honor `--hr-seek=always` and set that in a profile called `[extension.bik]`.

I see. Thanks for the explanation. I actually  prefer --hr-seek=always by default. And been using ut since I found that option.
Though I didn't notice it not working with the seekbar. I sort of can seek with it in a bik file, but sometimes it jumps to the start. Meanwhile hotkey seeking always jumps to the start when I attempt a seek with hr-seek disabled.
