### ISSUE TITLE
seeking within specific files breaks audio

### ISSUE THREAD

**Issue by Alloyed** [mpv-player/mpv#3920]
### mpv version and platform

Arch Linux, using OS package
```
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sat Nov 26 20:40:21 CET 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.2
```
### Reproduction steps

This consistently seems to happen to files recorded from OBS-studio 0.16.6-1, when the mkv format is used. Examples attached below.
It's very possible that OBS is spitting out malformed files, but the same files work in VLC and totem so I figured I'd start here.

1. Play video
2. seek to any point

### Expected behavior
audio playback

### Actual behavior
no audio playback

### Log file

https://alloyed.me/shared/log.txt

### Sample files

https://alloyed.me/shared/2016-12-18_16-42-05.mkv
https://alloyed.me/shared/2016-12-18_16-37-59.mkv

**Comment by SteveJobzniak** [comment]
@Alloyed According to the commit, https://github.com/mpv-player/mpv/commit/3b5777d86a62b9975c4c0fd224140e494db66ada - this is a bug in FFmpeg. It isn't marking audio packets as keyframes, or something like that. If you have time, please report the bug upstream so it gets fixed there _too_. ;-)
