### ISSUE TITLE
(Feature request) Playback position on subtitle search.

### ISSUE THREAD

**Issue by dragomang87** [mpv-player/mpv#3921]
Similar to:
https://github.com/mpv-player/mpv/issues/1171
but much simpler to implement.

Feature: Given an audio/video with subtitles, go to the position given by a pattern match on the subtitle.

Example:
You are playing Empire Strikes Back and press crtl+f, type "i am you father"+Enter
and voilá, the scene pops up.

**Comment by kevmitch** [comment]
This sounds like something that should be an external program or lua script if possible. It would require scanning the whole file in sequence which is not something likely to be done in the mpv core. It would be easier with an external subtitle file.

**Comment by dragomang87** [comment]
Already supporting external subtitles or even just specifically srt subs would be fantastic. 
Srt's have all the precise timestamps saved in plain, it just looks like a shame not to take advantage of that.

**Comment by kelciour** [comment]
Recently I wrote script that can be used in your situation. Here it is - [https://github.com/kelciour/playphrase](https://github.com/kelciour/playphrase).   
It's not exactly what you want but it can be used to
> go to the position given by a pattern match on the subtitle.

ps. I accidentally came across this issue when I've finished writing the script and was trying to fix some bugs. May be it will be helpful.

**Comment by kelciour** [comment]
> You are playing Empire Strikes Back and press crtl+f, type "i am you father"+Enter and voilá, the scene pops up.

If you're still interested I wrote a simple experimental [search.lua](https://github.com/kelciour/mpv-scripts/blob/master/search.lua) script that works almost exactly like that. Except that the current version of the script uses `script-message` command via [repl.lua](https://github.com/rossy/mpv-repl) script for user input instead of `ctrl+f` and it relies on the external *.srt subtitles.

**Comment by kelciour** [comment]
I've updated it and now it supports `ctrl+f`.

**Comment by kevmitch** [comment]
Feel free to add search.lua to https://github.com/mpv-player/mpv/wiki/User-Scripts. Closing because as stated initially, this will likely always be a user-script affair and not part of mpv itself.
