### ISSUE TITLE
Is there any possible to make MPV support smb by using this: https://github.com/videolabs/libdsm?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#3922]
### mpv version and platform

```
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Dec 15 21:04:53 UTC 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.68.100
   libavformat     57.60.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: 3.2.git
```
Will MPV support smb by using this: https://github.com/videolabs/libdsm?

**Comment by Argon-** [comment]
Question is why? Can't you just mount the target?

**Comment by wiiaboo** [comment]
FFmpeg supports libsmb on non-windows and in Windows you can just `mpv \\SERVER\share\file.mp4`. Why do you need this?

**Comment by JulianLai** [comment]
@Argon- Because the movie library and its interface is really good.

**Comment by wiiaboo** [comment]
Like I said, mpv already supports smb, so why this lib specifically?
