### ISSUE TITLE
Current mpv master does not compile with libav master due to libavdevice version requirement.

### ISSUE THREAD

**Issue by meridion** [mpv-player/mpv#3923]
The current mpv master https://github.com/mpv-player/mpv/commit/e57037dc952def5c2b2d2be7535052f94dfb9294 does not compile against the current libav master due to the fact that libav master curently provides libavdevice version 56.1.0 and mpv requires 57.0.0

See: https://git.libav.org/?p=libav.git;a=blob;f=libavdevice/version.h;h=a5297320daa76a706bd395c4263b6d57c7511fdb;hb=HEAD for libavdevice version

However, changing the version back down to 56.1.0 in wscript makes mpv compile fine and also run without problems. It therefore seems the version requirement of 57.0.0 might not be necessary, at least when using libav as a back-end.

**Comment by wm4** [comment]
libavdevice is not required, and according to our CI instance, both libav git and release work: https://travis-ci.org/mpv-player/mpv

**Comment by meridion** [comment]
Yes, but your CI instance is not compiling with libavdevice support.

Out of curiosity, what functionality of mpv would be impaired by missing libavdevice support? Wouldn't this hinder V4L? I mean, if it's not causing a noticeable loss of function I would understand disregarding the issue; but I know too little of libav's and mpv's innards to be able to judge that.

**Comment by wm4** [comment]
Absolutely nothing unless you're explicitly using av:// or avdevice://.

**Comment by meridion** [comment]
Hmm.. alright, that is good to know. The impact might indeed be not that large then. I was debugging why the build of mpv-9999 on Gentoo failed and stumbled upon this. I'll take this up with the maintainers.

Would be nice if this issue gets fixed eventually, especially since mpv seems to compile fine with the lower version setting, although obviously eventually libav will probably also version bump up, after which the detection will not be an issue.

In any case, thanks for the info.

**Comment by wm4** [comment]
The required libavdevice version could probably be lowered to make it get picked up, but I'm not sure why bother at all. (Libav is basically unsupported by mpv, except it still sort of compiles and many things work.)

**Comment by lachs0r** [comment]
Just use FFmpeg.
