### ISSUE TITLE
mpv does not display SRT subs after subtitle file offset 0x7fff has been passed using libav as back-end

### ISSUE THREAD

**Issue by meridion** [mpv-player/mpv#3925]
### Platform
Gentoo, x86_64, libav

### Version
Starting between 0.18.0-r1 and 0.22.0 till present.

### The issue
Somewhere between mpv version 0.18.0-r1 and 0.22.0 a change was introduced that causes mpv built against libav to no longer display subs loaded from an SRT file past the file pointer boundary of 0x7ffff.

This bug is precise to the point that a subtitle line will be displayed incompletely if part of its text lies across the 0x7fff file offset. Rewinding shows the previous subs just fine, it's as if the file is internally truncated to not exceed 0x8000 bytes.

However when using an older version of mpv, e.g. 0.18.0-r1 the subtitles show just fine. Similarly when using a version of mpv built against ffmpeg the subtitles work regardless of mpv version.

This issue persists in the current master of mpv.

Different versions of libav have been tested including libav-git and libav-11.8.

### Reproduction steps
play a video file using a recent version of mpv built againt libav:
mpv [video-file] --sub-file [srt-file]

using a sufficiently long .srt file and video. Fast forward to the point in the video where the subtitles are past the 0x7fff offset and observe they will no longer show.

### Expected behavior
The subtitles display fine throughout the whole video

### Actual behavior
Subtitles cut short after 0x7fff file boundary is crossed.

### Sample files
For ease of debugging I have pasted a suficiently long subtitle file, which  cuts off mid sentence around 41:50. (the issue was tested with multiple SRT files to verify, both ascii and unicode character sets)

The file: http://sprunge.us/bOZF

**Comment by wm4** [comment]
Subtitles are not supported at all with Libav. I'm not sure why it even works (for the beginning of the file) as you claim it does.

**Comment by meridion** [comment]
Ah, I had the impression the mpv project was still actively supporting both libav and ffmpeg back-ends. I was in the process of preparing another bug report regarding Matroska embedded DVD subtitles with libav, should I let that be then?

With regard to non-working subtiles, at least Matroska embedded ASS subtitles still work without any quirks with the latest version of mpv/libav.

Furthermore mpv-0.9.2-r1 still compiles fine against recent libav versions and has no issues whatsoever for me, which at the very least gives me the impression the subtitle bugs aren't due to libav.

**Comment by wm4** [comment]
mpv 0.9 still had some compatibility code. Although I'm not exactly sure why it still appears to work, except only for low offsets.

You should be using ffmpeg. There's no reason to use Libav at all, except for Libav development (which is important too because it gets merged into ffmpeg). Consider Libav as some sort of cleaner development branch of ffmpeg, that lacks some things such as improved subtitle handling.

**Comment by meridion** [comment]
At the time I switched to libav because of better coding practices, a stabler API, and the removal of a lot of cruft, and hopefully that meant less vulnerabilities also.

I've just did some researching and read this post: https://github.com/haasn/mpvhq-old/wiki/FFmpeg-versus-Libav which even happens to link your bug report to libav regarding subtitle demuxers: https://bugzilla.libav.org/show_bug.cgi?id=419

I guess considering all this, and the fact FFmpeg has been merging lots of libav's clean-up work, I can understand your stance. I'll consider switching back again.

**Comment by meridion** [comment]
I have bisected the bug and traced it back to this commit: bc97d60542b353141bedeee985f9e5bd68b9f076

This commit had to do with among others fixing the subtitle memory footprint as reported in https://github.com/mpv-player/mpv/issues/3456

I did the bisecting against libav-11.8

For your viewing pleasure I have attached the follow:
- The git bisect log
- 2 frame renders, one by the last working version, one by the broken version.

Since the commit diff doesn't seem that big I hope this provides you with enough information to establish the cause.
![mpv-git-4121016689-good](https://cloud.githubusercontent.com/assets/532055/21390991/d318dd5c-c789-11e6-97a6-c41fd4d23600.jpg)
![mpv-git-bc97d60542-bad](https://cloud.githubusercontent.com/assets/532055/21390998/d83725dc-c789-11e6-87d5-7db930455be7.jpg)
[subitle_bug_bisect.txt](https://github.com/mpv-player/mpv/files/666431/subitle_bug_bisect.txt)

**Comment by wm4** [comment]
> I have bisected the bug and traced it back to this commit: bc97d60

Indeed, unlike ffmpeg, libav's srt demuxer does not read everything at once when opening the file.

**Comment by lachs0r** [comment]
https://github.com/mpv-player/mpv/blob/master/README.md#ffmpeg-vs-libav
Not like we didn’t warn you.
