### ISSUE TITLE
I can't feel any difference by changing the radius of the SOFAlizer

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#3926]
### mpv version and platform

```
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Dec 15 21:04:53 UTC 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.68.100
   libavformat     57.60.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: 3.2.git
```
No matter how I set the value of radius to 2 or 3, I can't feel any difference, they still sound like the same distance.

**Comment by lachs0r** [comment]
Working as intended. This HRTF-based filter does not simulate your living room, so you don’t get reverberation and extreme speaker crosstalk as distance is increased.

Also, this is in FFmpeg (libavfilter), so report it there if you still think this is wrong.
