### ISSUE TITLE
[FEATURE] Listen to v4l2 events launched to userspace

### ISSUE THREAD

**Issue by joabreu** [mpv-player/mpv#3929]
Hi All,

First let me say that I do not know if this is the best place to post this but I could not find any reference to a mailing list or similar so that I can expose this. Sorry if I am posting in the wrong place.

So, recently I have been doing HDMI compliance using a V4L2 media driver and mpv as official player. One of the compliance requests is that the player must be continuously reproducing video, and reconfigure itself when there is a video format change (change in H/Vsize, audio rate, color depth, ...) without user interaction of any kind.

V4L2 offers to userspace an API so that events launched from drivers can be caught and processed. I found out that mpv does not use this API so I did a simple wrapper application that listens to the events launched from my driver and launches/quits mpv accordingly to these events. This causes mpv to reconfigure the pipeline and indeed user interaction is no longer needed when there is a video format change :)

Notice that V4L2 already offers a few number of events, which include format change, so there is no "custom" API (actually there is but its for another thing). So, this is all standard linux kernel features.

What I would like to ask is what is the effort to add this to mpv? By "this" I mean automatic reconfiguration of the video pipeline for tv:// devices when there is a video format change. Also, it would be nice if for example mpv quitted automatically when the video stream ended (this is also available in standard API).

Looking forward to your comments!

Best regards,
Jose Miguel Abreu

**Comment by Akemi** [comment]
if you are still interested, please open a new issue.
