### ISSUE TITLE
Manually specifying language/name for external audio track

### ISSUE THREAD

**Issue by d3adc0d3** [mpv-player/mpv#3932]
I'm writing some script that uses MPV and loads external audio files (a lot).

And I need an option to specify name and language for each track, as example:
`$ mpv file --audio-track=file.ac3 --audio-track-lang=english --audio-track-title=Dubbing`

I even can write a patch which will include that functionality if names of arguments is ok and nobody is against this.

**Comment by wiiaboo** [comment]
That's probably not functionality needed for the command line. Use what's already available:
[`track-list/N/title`](https://mpv.io/manual/master/#command-interface-track-list/n/title) and [`track-list/N/lang`](https://mpv.io/manual/master/#command-interface-track-list/n/lang).

**Comment by d3adc0d3** [comment]
I still need this, and mpv already has a lot of command line options that is better to leave for plugins/extensions/scripts, there is no reason to disallow to set some options from command line.

**Comment by wm4** [comment]
Very unlikely to happen, although the same can be achieved with the sub-add command.

**Comment by d3adc0d3** [comment]
@wm4: oh thanks, {sub,audio}-add really good command, but its still impossible to use it from command line. Still thanks for recommending this command.
