### ISSUE TITLE
Changing back and forth the sound output

### ISSUE THREAD

**Issue by bracuphoth** [mpv-player/mpv#3933]
I use the headphones [device1] on my comp. But when a bluetooth loudspeaker [device2] is on, I want it to default to that. And I do not want any sound output on the comp speakers [device3]. The loudspeaker is on only when needed, the system does the connection by itself, and it would be nice to get it even in mid play.

It was quite an adventure. So I finally got it that comma does not work to enumerate audio devices and mpv shows an error about wrong character. The key is to enumerate with `audio-device=` all the devices used and not the others. But it is counter intuitive. As the least important should be first for fallback. Now mpv.conf has
audio-device=device1
audio-device=device2

Which works Ok if the speaker is on when mpv is starting. If I switch to the headphones, all I have to do is switch off bluetooth or the speaker. But how can I convince mpv output to the loudspeaker when I turn it back on?

**Comment by kevmitch** [comment]
Provided your OS / sound backend supports ao-hotplug, you can observe the `audio-device-list` property and set the `audio-device` property accordingly when it changes. See [audio-hotplug-test.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/audio-hotplug-test.lua) and [ao-null-reload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/ao-null-reload.lua)
