### ISSUE TITLE
Runaway memory leak in long-running audio-only mpv process

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#3934]
### mpv version and platform

```
mpv git-e57037dc9 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Mon Dec 19 20:23:19 CET 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.68.100
   libavformat     57.61.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: N-82881-g99af260d0b
```

### Reproduction steps
1. ```mpv 'https://www.youtube.com/watch?v=xISO9UFz-QY&index=12&list=PLEFn_PVNSM6iXzMjwj9p4O_fJ7lruPKaQ'```

### Expected behavior

It only uses as much RAM as I have configured (cache-default)

### Actual behavior

It uses runaway amounts of RAM. I routinely wake up to this process having gotten killed by the OOM killer:

```
[  +0.000002] Out of memory: Kill process 27186 (mpv) score 894 or sacrifice child
[  +0.000066] Killed process 27186 (mpv) total-vm:46523748kB, anon-rss:29786036kB, file-rss:13132kB, shmem-rss:128kB
[  +1.686555] oom_reaper: reaped process 27186 (mpv), now anon-rss:0kB, file-rss:0kB, shmem-rss:128kB
```

### Log file

Nothing special. Here are a few minutes of playback. https://0x0.st/9xa.txt

Here is an example `htop` screenshot after running for half an hour or so:
![htop](https://0x0.st/9xB.png)

### Configuration

Including all relevant options, for completeness' sake. I have not yet tried reproducing the issue with `--no-config`.

```
cache=auto
cache-default=2000000
cache-backbuffer=1000000
cache-initial=1000
cache-seek-min=2000
ytdl=yes
ao=pulse
volume=70
volume-max=100
audio-pitch-correction=no
audio-normalize-downmix=yes
slang=eng,en,enUS,en-US
alang=jpn,jp,eng,en,enUS,en-US
ytdl-raw-options=sub-lang="en,eng,enUS,en-US",write-sub=
term-playing-msg='Resolution: ${width}x${height}, Framerate: ${container-fps} Hz'
mute=no
force-window=no
no-video
ytdl-format=bestaudio/best
af=lavfi=[loudnorm=I=-25:TP=-1.5:LRA=1]
volume=100
audio-device='pulse/alsa_output.usb-Blue_Microphones_Yeti_Stereo_Microphone_REV8-00.analog-stereo'
```

**Comment by haasn** [comment]
With just `--no-config --ytdl-format=bestaudio`, it seems like RAM also slowly grows over time, but not as quickly. (It started at res 110M and is now at res 144M)

**Comment by haasn** [comment]
In the process of bisecting the options. Using just the --cache= stuff, I'm currently sitting at 680 MB, which seems pretty constant. (That's the size of the entire downloaded file, so it doesn't surprise me)

**Comment by wm4** [comment]
Better just use valgrind?

**Comment by haasn** [comment]
It seems like just `--af=lavfi='[loudnorm=I=-25:TP=-1.5:LRA=1]'` is enough to trigger the runaway memory leak. Maybe this is a regression in libavfilter?

**Comment by haasn** [comment]
Valgrind log: https://0x0.st/9x9.txt

**Comment by wm4** [comment]
Run valgrind with --leak-check=full. For some bullshit reason it won't actually dump the leaked memory locations without it.

**Comment by haasn** [comment]
https://0x0.st/9xp.txt

**Comment by haasn** [comment]
FWIW, with the `--af=lavfi` line omitted, I get `0 bytes lost` by that output.

**Comment by haasn** [comment]
With `--af=lavi=[volume=0.5]` instead of loudnorm, I also get 0 bytes.

Here is a comparison of the filter list:

`--af=lavfi=volume`:
```
[af] Audio filter chain:
[af]   [in] 48000Hz stereo 2ch floatp
[af]   [lavfi] 48000Hz stereo 2ch floatp
[af]   [volume] "softvol" 48000Hz stereo 2ch floatp
[af]   [lavrresample] 48000Hz stereo 2ch float [a]
[af]   [out] 48000Hz stereo 2ch float
[af]   [ao] 48000Hz stereo 2ch float
```
(the extra `[volume]` is because I'm running with `--mute`)

`--af=lavfi=loudnorm`:
```
[af] Audio filter chain:
[af]   [in] 48000Hz stereo 2ch floatp
[af]   [lavfi] 192000Hz stereo 2ch double
[af]   [lavrresample] 192000Hz stereo 2ch float [a]
[af]   [volume] "softvol" 192000Hz stereo 2ch float
[af]   [lavrresample] 192000Hz stereo 2ch s16 [a]
[af]   [out] 192000Hz stereo 2ch s16
[af]   [ao] 192000Hz stereo 2ch s16
```

**Comment by wm4** [comment]
Does the same leak happen if you use ffplay with the filter?

>I'm not quite sure why it does an extra resample to s16 here?

Not sure what you mean.

**Comment by haasn** [comment]
Seems to be fixed in ffmpeg master.

> Not sure what you mean.

The output of the volume filter is ‘float’, which ao_pulse is capable of accepting (see the first example); yet it gets resamplied to s19 by lavrresample instead. Why is that the case? Can ao_pulse only handle float at 48 kHz but not at 192 kHz or something?

**Comment by wm4** [comment]
No idea. Pulse doesn't force us to take any specific format combination. Maybe it's because that lavfi filter outputs double, which ao_pulse doesn't support, and then falls back to s16 instead of float because its fallback is simplistic and doesn't use af_get_best_sample_formats to select it.

**Comment by haasn** [comment]
It goes from double to float for the softvol filter, and the output is float (not double) at that point.

**Comment by wm4** [comment]
> It goes from double to float for the softvol filter, and the output is float (not double) at that point.

The softvol filter is actually inserted only after the audio output is created.
