### ISSUE TITLE
Opening file fullscreen still shows top bar of GNOME.

### ISSUE THREAD

**Issue by Devices** [mpv-player/mpv#3935]
### mpv version and platform
0.22.0 from rpmfusion of Korora 25 GNOME (wayland). Think of Korora like fedora, but with rpmfusion installed by default.
Using the AMD open source drivers if it matters.

### Reproduction steps
Start a video with either the options "fullscreen=yes" in the config file or --fullscreen.

### Expected behavior
The video starts in fullscreen.

### Actual behavior
The top bar of GNOME is still active.
![mpvfull](https://cloud.githubusercontent.com/assets/1288343/21434771/8388e99c-c876-11e6-92b5-f5ede7e6e0f8.png)

### Log file
https://izumi.tv/f/output.txt

### Sample files
Happens to every file.

I'm sorry if this is not mpv's bug, I don't know for sure where to report this.

**Comment by atomnuker** [comment]
The same issue happens with the wayland-zxdg6 experimental WIP branch I have as well as with the Weston demo clients, hinting it's a problem with either gnome-shell or mutter. I wouldn't be surprised if something broke with the wl_shell interface as well.

I've submitted a bug report to the gnome people (https://bugzilla.gnome.org/show_bug.cgi?id=776428), you can check on the status there. For now I'm marking this as not our bug and closing the issue.

**Comment by Devices** [comment]
Thanks mate. According to `mutter --version` I'm using mutter 3.22.2.
