### ISSUE TITLE
video-rotate glitches with certain files

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#3942]
### mpv version and platform

```
mpv git-321dd794c (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 25 18:09:20 CET 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.70.100
   libavformat     57.61.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: N-82927-gc6c888e996
```

### Reproduction steps

1. Open the affected file with `mpv`
2. Set `video-rotate` to `90` or `270` (other angles are unaffected)
3. Observe the chroma layer being scaled in weird way

### Sample files

Input file:

![1477800399729](https://cloud.githubusercontent.com/assets/1045476/21472199/df7aafca-cacd-11e6-9bf7-6f8140d2d621.jpg)

Glitch in action:

![20161225_181136_azp](https://cloud.githubusercontent.com/assets/1045476/21472203/f2d90396-cacd-11e6-8024-b8f5c96c8a18.png)

**Comment by garoto** [comment]
Sample file needed. Coudn't reproduce on Windows using `opengl-backend=dxinterop` with `hwdec=auto-copy` and with  `--hwdec=cuda-copy`.

Using latest lach0r's build:

`mpv 0.23.0-git-10a005d (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 25 15:01:44 CET 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.70.100
   libavformat     57.61.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: N-82928-g77856a8`

**Comment by lachs0r** [comment]
I guess this is another case of lavfi being too damn stupid to handle 4:2:2.

**Comment by wm4** [comment]
Probably goes away if you add at least `scale=lanczos` or so.

**Comment by lachs0r** [comment]
No it doesn’t.

**Comment by haasn** [comment]
Let me guess, the file is 4:2:2 or something weird? vo_opengl has had known rotation bugs with 4:2:2 files for a while.

**Comment by rr-** [comment]
>    Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 1400x934, 25 tbr, 25 tbn, 25 tbc

Seems so

**Comment by wm4** [comment]
I got it the wrong way around: it works in dumb-mode, but it's broken in normal mode. Fixed by above PR.
