### ISSUE TITLE
macOS Touch Bar Support

### ISSUE THREAD

**Issue by beschoenen** [mpv-player/mpv#3943]
Are you guys planning on adding support for the touch bar featured in the new MacBooks?

**Comment by CounterPillow** [comment]
issue #2679 might be somewhat related, though I'm not sure what you imagine under "Touch Bar Support", since that can include anything from simply media keys to stuff like video moodbar.

What might be neat is an OSC for the touch bar.

**Comment by beschoenen** [comment]
Well, a scrub bar would be nice, also notifying macOS that something's playing, cause the play/pause buttons doesn't change when you watch something with mpv.

**Comment by beschoenen** [comment]
Current Touch Bar
<img width="1085" alt="touch bar shot 2016-12-26 at 18 48 14" src="https://cloud.githubusercontent.com/assets/1887585/21484979/06e88c0c-cb9c-11e6-9116-e99d9dbded48.png">
(The play button does work, but it doesn't change its icon)

Maybe add something like iTunes (With the scrub bar)
<img width="1085" alt="touch bar shot 2016-12-26 at 18 50 44" src="https://cloud.githubusercontent.com/assets/1887585/21484994/3a46668c-cb9c-11e6-842c-1428b283d79b.png">

**Comment by wm4** [comment]
AFAIK @rcombs made some experiments into this direction, but I don't remember much.

**Comment by rcombs** [comment]
There's a bit of awkwardness when running from CLI without an associated application bundle. I've got a radar in about it.

**Comment by beschoenen** [comment]
@rcombs Any update on this?

**Comment by Akemi** [comment]
i added simple Touch Bar support in [my branch](https://github.com/Akemi/mpv/commit/47fd9ea235aac67436acd411f743ca324e0c4166) (alternative a [build](https://dl.dropboxusercontent.com/u/68772824/mpv-touchbar.zip)). functionality should be complete. visuals can probably be improved. code still needs proper cleaning up. the seek bar itunes and quicktime uses, seems to be a none public widgets that needs to be recreated. this should also not be confused with MediaPlayer support. the 'equaliser' icon you can touch when the program is not focused to get the controls of itunes and quicktime seems to be a feature only available in the private part of the MediaPlayer (MediaRemote) framework. so we won't see that feature any time soon.

how it looks like atm. feel free to test and giving feedback.
![screen shot 2017-02-27 at 04 43 26](https://cloud.githubusercontent.com/assets/680386/23348086/6e2dfadc-fca7-11e6-911f-0a3aaa88bae2.png)
![screen shot 2017-02-27 at 04 43 13](https://cloud.githubusercontent.com/assets/680386/23348087/6e94f750-fca7-11e6-9a70-1ed0ac6681dc.png)

**Comment by rcombs** [comment]
Most of the `MediaPlayer` functionality is available through the `MPRemoteCommandCenter` framework; only a few things need to be loaded out of the private framework, and none of them are necessary for applications with built-in touch bar support. See my hack job: https://gist.github.com/a2fa5f2fd11560ea11295ec9f294d87f

**Comment by Akemi** [comment]
indeed what i said is wrong. the 'equaliser' icon appears even without the usage of the private framework. i just fucked up when testing it, forgot to start it from the Bundle and not CLI.

**Comment by beschoenen** [comment]
These guys got a scrub bar working. Might be a project to look at.

https://github.com/xzzz9097/Muse

**Comment by Argon-** [comment]
IINA is not a fork but a front-end, wrapping a GUI around mpv. When you desire GUI-like functionality then that's what you should use.

**Comment by Pavel-Guseynov** [comment]
For some reason mpv touch bar support is disabled in official builds.
You can enable it by compiling mpv by your own:
`brew install mpv --HEAD --with-bundle`

**Comment by Akemi** [comment]
there is still a second part for the touch bar support that could be implemented. apparently via the MPRemoteCommandCenter. i have an experimental implementation for that, and still need to test if everything works. we could also probably get rid of the apple remote support via "HIDRemote".

but i guess we don't need to keep this issue open for that.

**Comment by mlindner** [comment]
@Akemi Maybe reopen this given the person who closed it is gone?
