### ISSUE TITLE
Certain JPEG images get super stretched

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#3945]
### mpv version and platform

```
mpv git-321dd794c (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 25 18:09:20 CET 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.70.100
   libavformat     57.61.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: N-82927-gc6c888e996
```

### Reproduction steps

1. Open affected image file with mpv
2. Observe how the image gets stretched

I think the files themselves are broken:

- >Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 621x830 [SAR 300:1 DAR 18630:83], 25 tbr, 25 tbn, 25 tbc
- >Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 72:1 DAR 72:1], 25 tbr, 25 tbn, 25 tbc

Nonetheless I've encountered many such files in the wild already so I figured it's a good idea to report it here.

### Sample files

>![1245559995755](https://cloud.githubusercontent.com/assets/1045476/21472568/03f83ada-cae1-11e6-8a99-61609104adbf.jpg)
>![1478144441823](https://cloud.githubusercontent.com/assets/1045476/21472569/03f9d264-cae1-11e6-9acb-ed4f39ec9f1c.jpg)

And here's how it's actually rendered:

![20161225_203542_jxa](https://cloud.githubusercontent.com/assets/1045476/21472581/b7fdd774-cae1-11e6-80cc-5a4f3d903938.png)

**Comment by rr-** [comment]
(Of course, if I set `--video-aspect=no`, it works as expected.)

**Comment by wm4** [comment]
It's because ffmpeg interprets the DPI X/Y fields as aspect ration. Nothing else does this. Some files have nonsense in those fields, which results in what you see.

**Comment by haasn** [comment]
I have also encountered files in the wild where the DPI fields were required for the correct aspect ratio.

**Comment by rr-** [comment]
@haasn anamorphic screencaps?

**Comment by haasn** [comment]
@rr- I can't find any examples off-hand, at the moment, but I've come across them while browsing through the boorus.

**Comment by rr-** [comment]
I checked 257066 test JPG images and here are the results:

**4 files**: the AR is correct
**105 files**: the AR is incorrect (in 2 cases FFMPEG correctly discards the AR as invalid)
**20 files**: can't tell whether the AR is correct or not
**32 files**: no visual difference (AR is close to square)

Subject file name     | AR          | Is the AR good?
--------------------- | ----------- | ------------
32/1478317415502.jpg  | 1281:1280   | can't tell
33/1478714911916.jpg  | 72:1        | no
33/1478749289800.jpg  | 144:1       | no
33/1478750252305.jpg  | 26:20       | yes
42/1418178746603.jpg  | 4:3         | no
43/1418511122689.jpg  | 72:1        | no
44/1418680581593.jpg  | 72:1        | no
44/1418696686140.jpg  | 72:1        | no
47/1419298658185.jpg  | 71:1        | no
47/1419380274939.jpg  | 4:3         | no
47/1419381285155.jpg  | 4:3         | no
47/1419381872542.jpg  | 4:3         | no
50/1419902617030.jpg  | 102:108     | can't tell
51/1420159156169.jpg  | 29:22       | no
51/1420166055887.jpg  | 118:1       | no
52/1420395964524.jpg  | 4:3         | no
53/1420596614504.jpg  | 72:1        | no
54/1420857162705.jpg  | 100:1       | no
55/1420941140008.jpg  | 4:3         | no
55/1420941863600.jpg  | 600:1       | no
57/1421458997536.jpg  | 72:1        | no
67/1423101655843.jpg  | 72:73       | no difference
68/1423188763450.jpg  | 404:405     | no difference
69/1423433264212.jpg  | 8:9         | can't tell
72/1423789198554.jpg  | 4:3         | no
73/1423879881901.jpg  | 200:1       | no
73/1423964758131.jpg  | 4:3         | no
75/1424224907673.jpg  | 610:314     | no
80/1424744733370.jpg  | 4:3         | no
84/1425348781507.jpg  | 43:27       | no
86/1425694608235.jpg  | 299:300     | no difference
92/1426557181774.jpg  | 102:108     | can't tell
93/1426727906717.jpg  | 4:3         | no
98/1427493777376.jpg  | 4:3         | no
99/1427503982215.jpg  | 71:1        | no
99/1427584137754.jpg  | 33:26       | no
102/1428021873039.jpg | 8:9         | can't tell
103/1428108170017.jpg | 72:1        | no
103/1428108175084.jpg | 72:1        | no
103/1428108179074.jpg | 96:1        | no
103/1428108184822.jpg | 72:1        | no
103/1428108194904.jpg | 72:1        | no
103/1428108199918.jpg | 72:1        | no
105/1428433148153.jpg | 102:108     | can't tell
106/1428535926799.jpg | 4:3         | no
109/1429407475292.jpg | 4:3         | no
111/1429661928592.jpg | 102:108     | can't tell
111/1429751457050.jpg | 72:300      | no
113/1430785901244.jpg | 1:300       | no
117/1431301268386.jpg | 4:3         | no
117/1431308601299.jpg | 102:108     | can't tell
118/1431386835031.jpg | 102:108     | can't tell
122/1432053420780.jpg | 102:108     | can't tell
123/1432347294928.jpg | 404:405     | no difference
125/1432484631810.jpg | 131:132     | can't tell
125/1432599539952.jpg | 72:1        | no
126/1432673950912.jpg | 8:9         | can't tell
128/1433268548959.jpg | 102:108     | can't tell
129/1433461055718.jpg | 350:1       | no
129/1433465290543.jpg | 102:108     | can't tell
131/1433787455817.jpg | 29:22       | no
132/1433809412690.jpg | 404:405     | no difference
132/1433813084481.jpg | 100:1       | no
134/1434158067504.jpg | 72:1        | no
138/1434762864150.jpg | 40:39       | no difference
139/1434849546193.jpg | 43:27       | no
140/1435019542781.jpg | 26:20       | no
140/1435019648433.jpg | 72:1        | no
141/1435105344008.jpg | 404:405     | no difference
143/1436074713341.jpg | 33:26       | no
146/1438047633282.jpg | 500:330     | no
146/1438047873402.jpg | 299:1       | no
146/1438049282644.jpg | 4:3         | no
151/1438916173457.jpg | 28:137      | no
153/1439434998754.jpg | 2200:1647   | yes
157/1440033460810.jpg | 72:1        | no
158/1440371408029.jpg | 43127:43200 | no difference
159/1440447266436.jpg | 404:405     | no difference
160/1440626532898.jpg | 96:1        | no
160/1440635579749.jpg | 96:1        | no
160/1440635634388.jpg | 96:1        | no
160/1440643092551.jpg | 72:1        | no
161/1440730302096.jpg | 72:1        | no
166/1441854659208.jpg | 102:81      | no
174/1443409641828.jpg | 20:15       | no
175/1443581743546.jpg | 31440:23752 | no
178/1444186900240.jpg | 404:405     | no difference
180/1444619365601.jpg | 239:240     | no difference
183/1445051078915.jpg | 26:20       | no
186/1445656068050.jpg | 4:3         | no
189/1446253493470.jpg | 4:3         | no
194/1447113799846.jpg | 72:1        | no
194/1447115191390.jpg | 72:1        | no
194/1447127002018.jpg | 404:405     | no difference
199/1450020450188.jpg | 550:549     | no difference
200/1450065301175.jpg | 1:72        | no
204/1450916577766.jpg | 330:329     | no difference
210/1451704269933.jpg | 4:3         | no
213/1451793972106.jpg | 1:72        | no
214/1451785195005.jpg | 1281:1280   | no difference
215/1451701939628.jpg | 4:3         | no
219/1453694138992.jpg | 72:1        | no
221/1452915550747.jpg | 404:405     | no difference
223/1453692037061.jpg | 72:1        | no
232/1455162405304.jpg | 8:9         | can't tell
236/1455507342146.jpg | 404:405     | no difference
237/1455854061166.jpg | 71:72       | no difference
239/1456020802896.jpg | 32:27       | no
241/1456369535319.jpg | 8:9         | can't tell
246/1456539330059.jpg | 4:3         | no
247/1456882803386.jpg | 26:20       | no
254/1456630566293.jpg | 32:27       | no
256/1457830082110.jpg | 4:3         | no
257/1459304268761.jpg | 350:1       | no
260/1459132021642.jpg | 102:108     | can't tell
262/1457754221184.jpg | 4:3         | no
265/1459220695227.jpg | 10807:10800 | no difference
265/1459824255206.jpg | 120:119     | no difference
265/1460516415875.jpg | 404:405     | no difference
266/1460602980829.jpg | 150:1       | no
267/1459898767414.jpg | 1:52432     | no (ffmpeg detects it as invalid)
268/1461121387980.jpg | 100:1       | no
269/1460684818160.jpg | 4:3         | no
270/1460425116216.jpg | 72:1        | no
272/1460421295127.jpg | 102:81      | no
273/1459895486860.jpg | 40:39       | no difference
275/1461203059848.jpg | 404:405     | no difference
276/1461378047930.jpg | 72:1        | no
278/1461635106764.jpg | 32:27       | no
278/1461690130332.jpg | 72:1        | no
279/1461894785818.jpg | 4:3         | no
280/1462416166278.jpg | 404:405     | no difference
288/1462925501953.jpg | 102:108     | can't tell
289/1463625650538.jpg | 26:20       | yes
290/1463675004610.jpg | 96:1        | no
292/1463271190656.jpg | 57:60       | no
293/1463675020588.jpg | 96:1        | no
299/1465438920866.jpg | 72:1        | no
301/1465009164191.jpg | 4:3         | no
307/1466218692899.jpg | 71:554      | no
314/1465778852619.jpg | 404:405     | no difference
315/1468282528542.jpg | 910:909     | no difference
320/1467253242826.jpg | 404:405     | no difference
326/1468722658015.jpg | 26:20       | no
328/1470363910730.jpg | 721:720     | no difference
328/1470625192639.jpg | 96:72       | no
331/1469588216692.jpg | 900:899     | no difference
332/1469241224497.jpg | 404:405     | no difference
334/1469849576870.jpg | 4:3         | no
339/1468716501985.jpg | 350:1       | no
341/1470453091400.jpg | 4:3         | no
342/1471574364226.jpg | 72:1        | no
347/1471834888226.jpg | 404:405     | no difference
349/1471991087393.jpg | 404:405     | no difference
352/1479943387008.jpg | 72:1        | no
357/1480735679127.jpg | 102:108     | can't tell
357/1480822570407.jpg | 2200:1647   | yes
359/1481080277397.jpg | 762:1       | no (ffmpeg detects it as invalid)
359/1481154737314.jpg | 81:103      | can't tell
361/1481427363467.jpg | 72:1        | no
361/1481564224671.jpg | 26:20       | no

**Comment by rr-** [comment]
I also analyzed some PNG images:

**40002 files**: the AR is equal to 1
**13 files**: the AR is not 1, out of which:

- **10 files**: the AR is incorrect
- **3 files**: can't tell whether the AR is correct or not

Subject file name     | AR        | Is the AR good?
--------------------- | --------- | ---
34/1478837280759.png  | 32:27     | no
45/1418928677226.png  | 8:9       | no
93/1426724670340.png  | 4016:4331 | can't tell
120/1431649238454.png | 160:179   | can't tell
132/1433811469605.png | 4:3       | no
141/1435108460562.png | 32:27     | no
209/1451361344914.png | 853:720   | no
215/1452563732828.png | 853:720   | no
216/1452571514957.png | 853:720   | no
225/1453752885343.png | 4094:4173 | can't tell
231/1454464435075.png | 32:27     | no
323/1468379182684.png | 853:720   | no

Additionally all of 10478 test GIF images (some of which are animated, some not) have AR set to 1 (I don't think GIF can provide such metadata anyway).

**Comment by richardpl** [comment]
GIF does provide it,  in very limited manner.

**Comment by wm4** [comment]
I haven't seen any other program than ffmpeg that interprets the DPI fields as aspect ratio. Pretty annoying anti-feature.

**Comment by haasn** [comment]
@rr- How did you check your images in bulk? I could run it against my corpus of 3263763 files.

**Comment by rr-** [comment]
@haasn 

```python
#!/bin/python3
import re
import sys
import glob
from subprocess import run, PIPE
from progress.bar import Bar
from multiprocessing import Pool


def f(file):
    out = run(['ffprobe', file], stdout=PIPE, stderr=PIPE).stderr
    match = re.search(rb'SAR (\d+):(\d+)', out)
    if match:
        a = int(match.group(1))
        b = int(match.group(2))
        if a != b:
            return '%s %d %d' % (file, a, b)
    return None


with open(sys.argv[1], 'w') as handle:
    print('Collecting files...')
    files = glob.glob('**/*.gif', recursive=True)
    print('Got %d files' % len(files))
    print('Analyzing...')

    bar = Bar('Working', max=len(files))
    pool = Pool(12)
    for i, result in enumerate(pool.imap_unordered(f, files)):
        bar.next()
        if result:
            print(result, file=handle, flush=True)
    bar.finish()
```

I didn't optimize it any further. It took a while to finish, but the speed bottleneck comes from the IO rather than spawning the processes.

**Comment by haasn** [comment]
@rr- I've run the script against all of my files and, after analyzing a few thousand, have come to the conclusion that all examples of files where the aspect ratio was required were actually .**webm**s, not jpg/png.

I could not find an example of a jpg/png where the DPI field was helpful rather than destructive. Almost all files containing aspect ratio information ended up stupidly stretched, and the ones that were still identifiable at all were either warped/distorted or had no difference.

Based on this I'm going to exclude aspect ratio information explicitly for image files.

**Comment by Akemi** [comment]
stale. if it still persists please report it to ffmpeg.
