### ISSUE TITLE
(Feature Request) New option to select downscaling or upscaling for anamorphic video aspect ratio correction

### ISSUE THREAD

**Issue by nRoof** [mpv-player/mpv#3948]
mpv 0.23.0, Arch Linux x86_64, KDE Plasma 5.8.4

Currently, if the video uses non-square pixels (e.g. anamorphic DVD), and when it's opened in windowed mode, then the frame is automatically upscaled in one of the dimensions to correct the aspect ratio. 

For example, if the source video stream says the frame is 720x480 with aspect ratio 4:3, then mpv resizes the video frame to be 720x540. So the height got resized from 480 pixels to 540.

This causes some blurring, if the video is watched in the opened window with its initial size. Especially when the selected upscaling filter doesn't apply much sharpening (like bicubic).

What I'm requesting is to be able to set an option to do a downscaling in this case, to match the shortest side of the video frame. That is, as in example, to resize the frame to 640x480, so that the width of 720 pixels got downscaled to 640.

This will allow not to loose the sharpness, especially for interlaced video when the high quality downscaling filter is used.

I couldn't find such an option in the documentation. Currently I'm using this lua script as a workaround: [https://0x0.st/pNu.lua](https://0x0.st/pNu.lua)

### Reproduction steps
1. Open the sample file from the link below in mpv (with the requested option set to downscale, but it seems unavailable at the moment).
2. Verify the dimensions of the video frame.

### Expected behavior
640x480, the frame is shrinked horizontally to correct the aspect ratio.

### Actual behavior
Requested option seems to be unavailable at the moment, so dimensions are 720x540, and the frame is stretched vertically to correct the aspect ratio.

### Sample files
Short sample of anamorphic video: [https://0x0.st/pNM.mpg](https://0x0.st/pNM.mpg)

**Comment by wm4** [comment]
I don't really want an option for this and I think upscaling is always preferable here.
