### ISSUE TITLE
(Documentation Request) Windows cli output

### ISSUE THREAD

**Issue by cruzzer** [mpv-player/mpv#3949]
mpv 0.23.0-git-10a005d, Windows x64, 

Currently mpv.exe does not produce any console output on windows, which was unexpected. As mentioned [here](https://github.com/mpv-player/mpv/issues/3086#issuecomment-215054773) by maniak1349, the mpv.com binary should be used.

I was unable to find an explanation (before I found the above comment) to this behavior in the mpv's [faq](https://github.com/mpv-player/mpv/wiki/FAQ), [wiki](https://github.com/mpv-player/mpv/wiki), master [manual](https://mpv.io/manual/master/) and manual.pdf.

Maybe this could be mentioned in a more prominent location like the "Terminal" or "Teminal Status Line" section in the manual. E.g.: Note: One Windows "mpv.exe" has its console output deactivated, please use "mpv.com" instead.

If devs agree, let know where you would like this inserted and I can make a pull request.

### Reproduction steps

- mpv.exe --help -> no console output
- mpv.exe --terminal --help -> no console output
- mpv.exe --player-operation-mode=cplayer -> no console output

**Comment by rr-** [comment]
This is Windows limitation. Basically if you want your application to create any GUI window, you can no longer see its output in `cmd.exe`, but IIRC it can still be piped to files etc.

Not sure if this is true for new Windows versions too...

This indeed is kind of esoteric knowledge and it's a good idea to explain it somewhere.

**Comment by lachs0r** [comment]
https://github.com/mpv-player/mpv/wiki/FAQ#On_Windows_why_does_mpvexe_not_attach_to_the_console_and_what_does_mpvcom_do

Does this help?

**Comment by cruzzer** [comment]
Great. Thank you also for the comprehensive explenation @lachs0r .
