### ISSUE TITLE
A-V desync because of too slow hardware?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3953]
Hi,

I have mpv-0.22.0 on Linux box with Intel G3900 and GTX 1060 3Gb, video goes from GTX to TV, with `display-desync` option, and audio goes from Intel (i.e. MB's) HDMI to soundbar, with `audio-spdif=truehd, dts-hd`.  When playing videos, I see A-V desync slowly growing, and sooner (with high-bitrate video and/or hd audio) or later a framedrop occurs, which is very noticeable. snd_hda_intel suggests increasing _bdl_pos_adj_ (tried that), and mpv complains about _cpu spikes or hardware being too slow_.

Are G3900 and GTX1060 really too slow for my case? 

Regards,
Alex

**Comment by wm4** [comment]
display-desync causing av desync is by design, and it's documented and all kinds of obvious. The desync message names all kinds of things that could have gone wrong, not sure why you single out the CPU spikes one.

**Comment by fhlfibh** [comment]
@wm4 I will try `display-resample` then, thanks!
Though can't understand how it's supposed to work with pass-through, since pass-through doesn't involve any resampling, afaik.

**Comment by wm4** [comment]
> Though can't understand how it's supposed to work with pass-through, since pass-through doesn't involve any resampling, afaik.

It doesn't. It will revert to default audio timing. You can try `display-adrop` though, which attempts to discard audio frames to achieve sync.

**Comment by fhlfibh** [comment]
Nope, still dropped, delayed and mistimed frames with `display-adrop`, regardless of pass-through or not.
`display-resample` seems to work better for me.
Maybe something is wrong with snd_hda_intel... I will try GPU HDMI outputs later.
Thanks!

**Comment by haasn** [comment]
So `display-resample` with passthrough disabled works for you?

**Comment by fhlfibh** [comment]
@haasn Seems like it works better, than 'display-adrop', but i'd like to make more tests. Also disabling passthrough doesn't look like a solution, because ffmpeg seems to drop decoding dts-hd and true-hd (but i need more tests of this too)...

**Comment by wm4** [comment]
I know some files with DTS or TrueHD have corrupted timestamps.

**Comment by fhlfibh** [comment]
@wm4 Quite possible, but i dont know how to check their correctness...
