### ISSUE TITLE
usb audio device doesnt appear in list of audio devices

### ISSUE THREAD

**Issue by NapoleonWils0n** [mpv-player/mpv#3955]
### mpv version and platform

mpv 0.23.0
arch linux

If you're not using git master or the latest release, update.

### Reproduction steps

usb audio device doesnt appear in list of audio devices using:

```
mpv --audio-device=help
```

* outputs

```
List of detected audio devices:
  'auto' (Autoselect device)
  'alsa' (Default (alsa))
  'alsa/hdmi:CARD=PCH,DEV=0' (HDA Intel PCH, HDMI 0/HDMI Audio Output)
  'alsa/hdmi:CARD=PCH,DEV=1' (HDA Intel PCH, HDMI 1/HDMI Audio Output)
  'alsa/hdmi:CARD=PCH,DEV=2' (HDA Intel PCH, HDMI 2/HDMI Audio Output)
  'jack' (Default (jack))
```

* this is the output of aplay -l

```
**** List of PLAYBACK Hardware Devices ****
card 0: PCH [HDA Intel PCH], device 0: CS4206 Analog [CS4206 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: PCH [HDA Intel PCH], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: M192kHz [Musical Fidelity V-Link 192kHz], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

* in versions of mpv before 0.23.0 release this is the code i used in my ~/.config/mpv/mpv.conf

```
ao=alsa:resample=yes:device=[plughw:1,0]
```

* i can play audio through the internal speakers using this in my ~/.config/mpv/mpv.conf

```
audio-device=alsa
```

i have tried changing the order of the alsa cards using /etc/modprobe.d/alsa-base.conf
but the audio still comes out of the internal speakers and not the usb audio device

### Expected behavior

audio should play through the usb audio device

### Actual behavior

cant find the usb audio device with mpv --audio-device=help
and cant figure out what the new syntax should be to select the external usb audio device

cheers
by the way like the github issue with sections to fill in

have to look at how you set that up so i can add the same sort of thing for my github issues

https://github.com/NapoleonWils0n/kodi-playercorefactory

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by fhlfibh** [comment]
@NapoleonWils0n 
You might try `audio-device=alsa/plughw:1,0` like example here https://mpv.io/manual/stable/#options-audio-device
Didn't test it myself, though

**Comment by NapoleonWils0n** [comment]
HI Mate

Cheers, i must have missed that
ill give it a go

**Comment by NapoleonWils0n** [comment]
Hi Mate

That works like a charm
Thanks a million
