### ISSUE TITLE
Quitting in fullscreen switches you to first Space

### ISSUE THREAD

**Issue by ChrisK2** [mpv-player/mpv#3957]
### Reproduction steps

I have three spaces, I switch to Space 3, start playing a video, go into fullscreen, quit mpv while in fullscreen, now I am on Space 1 instead of 3.

Note: This does not happen when just toggling FS, only when quitting.

### Expected behavior

Stay on Space 3.

### Actual behavior

Switches to Space 1.

**Comment by sosia** [comment]
I noticed that too, but it happens to me not only with mpv: every single app I have tested, both Apple's and non-Apple's ones, behaves like that. 
Maybe there's a workaround, but it seems that's more of an Apple's bug or the "intended" behaviour of the native fs API.

**Comment by GilesJo** [comment]
I'm missing "Version 0.22". 
Now, inorder to play fullscreen, it have to go to a new space(in macOS). That means I cann't deal other things with press "command +tab" when watching video. Maybe, we could have a config to switch modes of fullsceen.

**Comment by Akemi** [comment]
see comments [here](https://github.com/mpv-player/mpv/commit/a8347eb9ba9e09177da50592fde7f3ae7261ce59) and comments on #3944.

would be nice if you wouldn't post unrelated problems on issues.
