### ISSUE TITLE
Switching paused video to fullscreen with opengl video output results in corrupted output

### ISSUE THREAD

**Issue by moosotc** [mpv-player/mpv#3958]
### mpv version and platform
mpv git-35716b53d (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Dec 29 03:27:16 MSK 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.2
Linux linmac2 4.9.0-malc #9 SMP PREEMPT Wed Dec 14 17:06:33 MSK 2016 x86_64 GNU/Linux

If you're not using git master or the latest release, update.

### Reproduction steps
mpv --demuxer=rawvideo /dev/zero & xdotool search --sync mpv sleep 1 key space key f

### Expected behavior
green screen

### Actual behavior
black screen with a green rectangle in top left corener

********************
Only happens with opengl video output. vaapi,xv,x11 or opengl with enabled debanding behave correctly.

**Comment by wm4** [comment]
Can't reproduce.

**Comment by moosotc** [comment]
"V. Lang" <notifications@github.com> writes:

> Can't reproduce.

Let's see.

glxinfo | grep 'renderer string'
OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile

Perhaps this thing only affects i915. Given with LIBGL_ALWAYS_SOFTWARE
set to 1 the issue is not reproducible here either.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Another data point - only happens with intel driver, but with modesetting (where this doesn't happen) tearing becomes a problem.

**Comment by CounterPillow** [comment]
>only happens with intel driver

The Intel DDX is notoriously buggy; I recommend ditching it for modesetting. I don't get any tearing myself on modesetting, so I don't know what that's all about. I'm on Haswell too, and my xorg.conf is something like:

```
Section "Device"
        Identifier "intel"
        Driver "modesetting"
        Option "DRI" "3"
EndSection
```

**Comment by moosotc** [comment]
@CounterPillow thank you will try a bit later
So far I've tried modesetting + compton and can easily reproduce the issue with.
mpv -vo opengl --demuxer=rawvideo /dev/zero & xdotool search --sync mpv sleep 1 key o key space key f

**Comment by moosotc** [comment]
Another piece of information the issue is not present when i3bar is hidden and easily reproducible otherwise, biazarre...

**Comment by moosotc** [comment]
bar {
        hidden_state show
}
is the culprit with the above in place the bug is reproducible with `hidden_state' set to `hide' it is not

**Comment by moosotc** [comment]
Simpler reproducer
mpv /dev/zero --demuxer rawvideo --pause & xdotool search --sync --class mpv key f

i3bar visibility makes no difference, `--vo vaapi' alleviates the issue as does `--profile opengl-hq'

**Comment by lachs0r** [comment]
Are you using compton with `--backend=glx`?

**Comment by moosotc** [comment]
Martin Herkt <notifications@github.com> writes:

> Are you using compton with `--backend=glx`?

Yes.

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
Martin Herkt <notifications@github.com> writes:

> Are you using compton with `--backend=glx`?

Worth noting that the issue is independent of compton, given that after
`pkill compton' and making sure it's no longer running the problem
persists.

(Also compton is there only to work-around mpv/opengl tearing issues)

-- 
mailto:moosotc@gmail.com

**Comment by lachs0r** [comment]
Can’t reproduce on Haswell HD4400.

**Comment by moosotc** [comment]
Following reproduces the issue for me:
mpv --demuxer=rawvideo /dev/zero & xdotool search --sync -class mpv sleep 1 key space f

mpv 0.29.0-61-g2b0b9bb6a1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Oct  9 08:15:56 MSK 2018
ffmpeg library versions:
   libavutil       56.19.101
   libavcodec      58.32.100
   libavformat     58.18.104
   libswscale      5.2.100
   libavfilter     7.33.100
   libswresample   3.2.100
ffmpeg version: N-92142-ge10fe34e7c

The configuration for ffmpeg and mpv are done with
https://github.com/moosotc/snippets/blob/master/bin/configure/ffmpeg
and
https://github.com/moosotc/snippets/blob/master/bin/configure/mpv
respectively

**Comment by moosotc** [comment]
The issue is apparently less deterministic that one would have hoped. Manually toggling fullscreen with a paused video doesn't always lead to the "corrupted" output, yet most often it does...
