### ISSUE TITLE
mpv - how to show file size in the OSD

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3959]
When i view OSD (with time) how to view the file size also

**Comment by garoto** [comment]
`--osd-msg3="${osd-sym-cc} ${playback-time} ${?duration:/ ${duration}} ${?percent-pos:(${percent-pos}%)} Size: ${?file-size:${file-size}}"`

**Comment by Hrxn** [comment]
Do you still need `${osd-sym-cc}` when using `osd-msg3`?

**Comment by garoto** [comment]
Hmm, just tested it, and I guess yes, it is needed once you override osd-msg3, but maybe I'm missing something (quite possible).
