### ISSUE TITLE
I get an error on every startup for  v0.23.0

### ISSUE THREAD

**Issue by mzso** [mpv-player/mpv#3963]
```
[socket]
[socket] stack traceback:
[socket]        [C]: in function 'require'
[socket]        C:/totalcmd/plugins/mplayer/scripts/socket.lua:12: in main chunk
[socket]        [C]: at 0x00e0f700
[socket]        [C]: at 0x00e0eb90
[socket] Lua error: error loading module 'socket.core' from file '.\socket\core.dll':
[socket]        %1: nem Win32 alkalmaz?s.
[socket]
[mime]
[mime] stack traceback:
[mime]  [C]: in function 'require'
[mime]  C:/totalcmd/plugins/mplayer/scripts/mime.lua:12: in main chunk
[mime]  [C]: at 0x00e0f700
[mime]  [C]: at 0x00e0eb90
[mime] Lua error: error loading module 'mime.core' from file '.\mime\core.dll':
[mime]  %1: nem Win32 alkalmaz?s.
[mime]
```
The errors seem to appear with every video, every time.
The localized error would be something like: "%1:  not a Win32 application"

**Comment by kevmitch** [comment]
What is this `mime.lua` script you're using? That's what's causing the problem.

**Comment by mzso** [comment]
[**@kevmitch**](https://github.com/kevmitch) commented on [2017. jan. 1. 21:51 CET](https://github.com/mpv-player/mpv/issues/3963#issuecomment-269919094 "2017-01-01T20:51:29Z - Replied by Github Reply Comments"):
> What is this `mime.lua` script you're using? That's what's causing the problem.

I'm not using anything. I Don't know what lua is. If it's there it was included in mpv at least at somepoint.

**Comment by mzso** [comment]
[**@kevmitch**](https://github.com/kevmitch) commented on [2017. jan. 1. 21:51 CET](https://github.com/mpv-player/mpv/issues/3963#issuecomment-269919094 "2017-01-01T20:51:29Z - Replied by Github Reply Comments"):
> What is this `mime.lua` script you're using? That's what's causing the problem.

So I looked at package files I found these stuff (.\mime, .\socket\ folder) it in mpv-x86_64-20140630.7z So I guess it remained since then. I have no clue where the .\scripts folder came from there's only a .\libquvi-scripts folder in this package
Why it's loaded and causing trouble now is a mystery to me.

So I guess I can remove these stuff?

**Comment by kevmitch** [comment]
yeah, it looks like these are all things form older releases. I wasn't fully aware of their existence or purpose, but the latest `mpv-x86_64-20161225.7z` doesn't have any of them. Just `mpv.exe`, `mpv.com`, `d3dcompiler_43.dll` and `manual.pdf`.

Other stuff that you did not specifically put there should probably be removed. Definitely libquvi-scripts should be axed since mpv no longer supports quvi.

**Comment by mzso** [comment]
[**@kevmitch**](https://github.com/kevmitch) commented on [2017. jan. 3. 06:54 CET](https://github.com/mpv-player/mpv/issues/3963#issuecomment-270055478 "2017-01-03T05:54:30Z - Replied by Github Reply Comments"):
> yeah, it looks like these are all things from older releases. I wasn't fully aware of their existence or purpose, but the latest `mpv-x86_64-20161225.7z` doesn't have any of them. Just `mpv.exe`, `mpv.com`, `d3dcompiler_43.dll` and `manual.pdf`.
> 
> Other stuff that you did not specifically put there should probably be removed. Definitely libquvi-scripts should be axed since mpv no longer supports quvi.

Does the "fonts" directory also serve no purpose anymore? Or is it just that no fonts are provided in the package?

**Comment by garoto** [comment]
Windows builds don't use fontconfig anymore. You can safely remove the "fonts" dir and all its contents if you're using any build from 2016.
