### ISSUE TITLE
.config/mpv/ is empty...?

### ISSUE THREAD

**Issue by manuelsongokuh** [mpv-player/mpv#3965]
i install new mpv, but there is not the file mpv.config in ./config/mpv/   
this is a bug?

**Comment by wiiaboo** [comment]
No, you're supposed to create it yourself if you want to change anything.

**Comment by manuelsongokuh** [comment]
how i will create file default?
is there the file ready to use?

**Comment by ChrisK2** [comment]
https://mpv.io/manual/master/#configuration-files

**Comment by garoto** [comment]
And if I may add: https://github.com/mpv-player/mpv/blob/master/etc/mpv.conf

**Comment by manuelsongokuh** [comment]
thank you!!!!
