### ISSUE TITLE
playback info for mpv: is it it possible?

### ISSUE THREAD

**Issue by manuelsongokuh** [mpv-player/mpv#3966]
hi
i want to ask you, if is possible add new feature:
information from video playback info (size, bitrate, codec video, codec audio, pixel size, etc, etc?

if active playback info will be add list inside video, background black 50% to opacity on video..
this is cool idea..or not good idea?

**Comment by wiiaboo** [comment]
Already done: https://github.com/Argon-/mpv-stats/

**Comment by manuelsongokuh** [comment]
ok,WOW thank you!!


I suggest you: add background balc with 50 opacity, because if video color white so i cant read the information..right?

**Comment by ChrisK2** [comment]
You can configure pretty much everything: https://github.com/Argon-/mpv-stats/#customization
