### ISSUE TITLE
Self-referential playlists cause infinite loop

### ISSUE THREAD

**Issue by andOlga** [mpv-player/mpv#3967]
### mpv version and platform

0.23.0-git-10a005d, Win32

### Reproduction steps

Create a playlist file that refers to itself by name:
`echo playlist.m3u > playlist.m3u`
Then, open it in MPV.

### Expected behavior
An error message of some sort.

### Actual behavior
MPV keeps adding the playlist file over and over, resulting in ever-increasing memory usage. It doesn't seem to stop. The actual player window doesn't ever show up, so MPV has to be killed via task manager if this problem manifests.

**Comment by wm4** [comment]
That's normal. If loading takes forever it'll sit around forever. mpv is designed to be started from command line, and there you should be able to exit it gracefully with ctrl+c. For "GUI" use --force-window=immediate might help. If you use ``--playlist`` only killing will help though.

Not sure if the particular issue here (recursive playlists) can be solved nicely.
