### ISSUE TITLE
Closed Captioning (EIA-608) does not display 

### ISSUE THREAD

**Issue by g4jc** [mpv-player/mpv#3968]
### mpv version and platform
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 25 19:20:18 UTC 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.2
GNU/Linux

### Reproduction steps
1) Insert DVD, view log.
VO: [opengl] 720x480 => 853x480 yuv420p
 (+) Video --vid=1 (mpeg2video)
 (+) Audio --aid=1 --alang=en (ac3)
     Audio --aid=2 --alang=fr (ac3)
     Subs  --sid=1 --slang=en (dvd_subtitle)
     Subs  --sid=2 --slang=es (dvd_subtitle)
     Subs  --sid=3 --slang=fr (dvd_subtitle)
     Subs  --sid=4 --slang=fr (dvd_subtitle)
     Subs  --sid=5 (eia_608)
2) attempt to run: mpv --sid=5 dvd://

### Expected behavior
Closed captions should display

### Actual behavior
No close captions display, burned-in dvd_subtitle do display but are not the same as subtitles and occasionally are not as accurate as CC.

### Log file
https://dpaste.de/ra8s/raw

### Sample files
Any NTSC DVD will do.

Or this sample file:
http://samples.ffmpeg.org/sub/subcc/ClosedCaptions/Starship_Troopers.vob

**Comment by g4jc** [comment]
If anyone works on this feature (much appreciated!), I'd also like to get some API hooks. e.g. trigger events on keywords from the text stream. This would allow for some very cool plugin development.

**Comment by ChrisK2** [comment]
Well, the sample actually works for me (track 3, you have to wait till the dialog for mpv to realize there is a CC track):

![mpv_screenshot_0001](https://cloud.githubusercontent.com/assets/3440203/21576582/adf9f908-cf35-11e6-9029-2a20d83b5eac.jpg)

**Comment by wm4** [comment]
FFmpeg has a way to determine presence of closed captions in the demuxer layer, but it's only available by using deprecated API.
Thus WONTFIX.

**Comment by g4jc** [comment]
It appears that it was previously working in mplayer using --subcc. This is especially important for individuals with hearing problems since the subtitles on the DVD are not always in sync, whereas CC always is.

If the API has been depreciated, would you mind pointing out which one it is so that I can take this upstream?

Thank you.

**Comment by wm4** [comment]
It appears you can call av_codec_get_codec_properties on AVStream.codec, and if FF_CODEC_PROPERTY_CLOSED_CAPTIONS is set, the stream has closed captions. But AVStream.codec is deprecated.

**Comment by jdenson12** [comment]
This fixes it for me:

```
diff -up mpv-0.23.0/sub/lavc_conv.c.timebase mpv-0.23.0/sub/lavc_conv.c
--- mpv-0.23.0/sub/lavc_conv.c.timebase	2017-02-10 16:52:29.818480488 +0000
+++ mpv-0.23.0/sub/lavc_conv.c	2017-02-10 16:53:45.747232175 +0000
@@ -91,6 +91,7 @@ struct lavc_conv *lavc_conv_create(struc
     av_dict_free(&opts);
     // Documented as "set by libavcodec", but there is no other way
     avctx->time_base = (AVRational) {1, 1000};
+    av_codec_set_pkt_timebase(avctx, (AVRational) {1, 1000});
     priv->avctx = avctx;
     priv->extradata = talloc_strndup(priv, avctx->subtitle_header,
                                      avctx->subtitle_header_size);

```

mpv is decoding cc through ffmpeg using realtime mode, and deep within the ffmpeg code it's trying access the timebase through AVCodecContext.pkt_timebase but nothing has set that. Without this it can't set the pts used for decoding subtitles in realtime mode which causes that to fail. The relevant lines where it's trying to access this in ffmpeg are in libavcodec/utils.c (currently line 2692):

```
            if (avctx->pkt_timebase.num && avpkt->pts != AV_NOPTS_VALUE)
                sub->pts = av_rescale_q(avpkt->pts,
                                        avctx->pkt_timebase, AV_TIME_BASE_Q);
```


The patch I've posted above works for me but needs some extra work really - the line above where it's setting AVCodecContext.time_base still seems to be needed and possibly shouldn't anymore; I don't think ffmpeg needs it anymore but maybe other parts of mpv are relying on it. I haven't looked into it yet.

It possibly also needs some ifdefs around it for API versions - av_codec_set_pkt_timebase was introduced a while ago by the looks of things but I don't know how far back mpv is trying to support.

I can prepare a PR as is or do you want to do some extra work on this?

**Comment by g4jc** [comment]
Thank you for preparing a patch. 
@wm4 would you consider re-opening this bug and seeing if the above patch could work, or recommend more changes?

**Comment by wm4** [comment]
Seems like 4d33b622ce51e702f011b8e30d7b80b15e938439 fixed this already.
