### ISSUE TITLE
long name.

### ISSUE THREAD

**Issue by c384mb** [mpv-player/mpv#3969]
[name.zip](https://github.com/mpv-player/mpv/files/679486/name.zip)

**Comment by g4jc** [comment]
This is literally one of the worst bug reports I've seen. Requires dev to download a suspicious zip and then open a png. In any case here the file is...

https://cloud.githubusercontent.com/assets/1471617/21576208/066c0a02-cf1f-11e6-89b8-b6bc28815059.png

OP seems to be reporting the fact that titles do not appear correctly if the filename is too long.

**Comment by ChrisK2** [comment]
Not possible to properly fix.

**Comment by c384mb** [comment]
I wanted to place in 7z, minus Lin... It is such way that not all see (the bots index the image).
