### ISSUE TITLE
how i add config: rotate with press key: R..?

### ISSUE THREAD

**Issue by manuelsongokuh** [mpv-player/mpv#3970]
hi

i want to use MPV always and VLC go to RIP..
so i want to press key r for rotate 90 or 180 in file mpv.config how?

**Comment by wm4** [comment]
Not sure why you'd need this, but I do it by putting `ctrl+r cycle-values video-rotate 0 90 180 270` into input.conf.

**Comment by manuelsongokuh** [comment]
thank you i need this TOO because my friends used record video from smart-phone there is video vertical and video horizontal, or video flip horizontal because friends used record video smart-phone flipped, so i think to use rotate ok?

**Comment by manuelsongokuh** [comment]
thank you!

**Comment by WanderingKnight** [comment]
Thanks wm4.. amazing

**Comment by Frioo** [comment]
Thanks @wm4 your script is very useful!

**Comment by mariojuniorjp** [comment]
> Not sure why you'd need this, but I do it by putting `ctrl+r cycle-values video-rotate 0 90 180 270` into input.conf.

Thank you very much! Works like a charm! :D

**Comment by manuelsongokuh** [comment]
hi, i need other fix: when i press ctrl-r or r (180 degree) , but keep always after close mpv and reopen video keep 180 degree , if i do again press ctrl-r or r change to 270 and close mpv and reopn mpv keep 270..that is possible fix it..? how..?

thank you
