### ISSUE TITLE
Can the autospeed script be built in by default?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#3971]
### mpv version and platform

mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Dec 15 21:04:53 UTC 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.68.100
   libavformat     57.60.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: 3.2.git

https://github.com/kevinlekiller/mpv_scripts/tree/master/autospeed/
It is easy to use and needs lesser resource than interpolation, maybe it should be built in by default?

**Comment by fhlfibh** [comment]
There's no need to "build" Lua scripts. You need mpv built with lua (or luajit) support enabled.
https://mpv.io/manual/stable/#lua-scripting

**Comment by JulianLai** [comment]
@fhlfibh I mean, it should be the basic function of MPV player, then we don't have to find those script and download them.

**Comment by fhlfibh** [comment]
@JulianLai 
Ah, I see... Then, the scrip's author (or you, if he doesn't mind) might mention them here https://github.com/mpv-player/mpv/wiki/User-Scripts
I mean, building this script into mpv by default may cause problems for users who don't need it. Contrariwise, everyone who needs it, will be able to find it on the above wiki page. Maybe, that wiki page should be mentioned in documentation.
Anyway, in this case it's devs to decide.

**Comment by Hrxn** [comment]
Not a good idea...

**Comment by JulianLai** [comment]
By the way, I don't know how to use the 'xrandr' and 'fpsadjust' script in the user-scripts wiki page, nothing happens when I place them into "~/.config/mpv/scripts"

**Comment by fhlfibh** [comment]
'Xrandr' switches monitor refresh rate to the most sutable for a given fps. 'Fpsadjust' adjusts fps to given refresh rate, and is obsolete, afaik. Both produce no OSD output. Details can be found in their gits. Also Mpv's wiki has pages about interpolation and syncronization. 'Xrandr' script works pretty well, i use it myself.

**Comment by kevinlekiller** [comment]
I didn't add them to the wiki because they are more for personal use and xrandr / fpsadjust were already in the wiki.

**Comment by JulianLai** [comment]
But it doesn't switch the monitor refresh rate after I put the script in "~/.config/mpv/scripts/"

**Comment by fhlfibh** [comment]
@JulianLai Then you should open an issue in 'Xrandr' script's git, with attaching mpv log and everything. And even if you insist to discuss it here -- i dont think much can be done without logs.

**Comment by lachs0r** [comment]
Do your monitors actually have useful refresh rates in their EDID mode list? Many display devices only support 50/60 Hz according to EDID, so xrandr can’t do much. Other than that, `--video-sync=display-resample` tries to sync as nicely as possible by adjusting speed (see also `--video-sync-max-video-change` and `--video-sync-max-audio-change`).
