### ISSUE TITLE
Fail to add the vapoursynth's nnedi3 script.

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#3972]
### mpv version and platform
```
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Dec 15 21:04:53 UTC 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.68.100
   libavformat     57.60.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: 3.2.git
```

Here is the message:
`[vapoursynth] Python exception: There is no function named nnedi3_rpow2`

**Comment by fhlfibh** [comment]
Do you need vapoursynth's nnedi3? It never worked well, afaik. There's nnedi3 made of custom shaders, the link can be found in mpv's wiki.

**Comment by Hrxn** [comment]
Which one do you mean exactly?
