### ISSUE TITLE
show-text ${fps} always report 0.000 after mpv 0.23.0

### ISSUE THREAD

**Issue by bodayw** [mpv-player/mpv#3975]
### mpv version and platform

mpv 0.23.0, macOS 10.12.2

### Reproduction steps

``i show-text ${fps}`` in input.conf, and press ``i`` while playing a video file

### Expected behavior

the number of fps of current video should be displayed on the OSD, e.g. 23.976

### Actual behavior

seems always report 0.000

**Comment by haasn** [comment]
It was renamed to `container-fps`

**Comment by bodayw** [comment]
Oh, I see...Thanks.
