### ISSUE TITLE
Subtitle text disappears when moved to the top of the window if margins exist

### ISSUE THREAD

**Issue by MoSal** [mpv-player/mpv#3977]
### mpv version and platform

Latest master (b14fc38590097117bd2eb2b71cf1a2f8b736f778)
libass 0.13.4
Gnu/Linux x86_64

### Reproduction steps
Move sub text to the top with `sub-pos` ([Screencap](https://archive.org/download/unsorted_files/x2.mkv)).

### Expected behavior
Text should not disappear.

### Actual behavior
It starts to disappear at some point.

----

I think this is a margin handling bug in `libass`.  `--sub-align-y=top` works correctly.

[This workaround](https://gist.github.com/anonymous/701d82c9f216832cae2c8badb9022445) obviously works. But I'm not sure my analysis is correct. That's why this is not a pull request.

**Comment by wm4** [comment]
I have no idea. I suspect it requires someone to dig deep in the libass sources to find out what exactly is going on and what is wrong.

For one, negative margins are needed if the video gets cropped.

Might be related to https://github.com/libass/libass/issues/218

**Comment by MoSal** [comment]
Just  to be clear:
* The subtitles come from a simple `.srt` file.
* The margins are positive (24/10 video, 16/9 display).

I'm assuming the bug is easy to reproduce.

**Comment by wiiaboo** [comment]
Couldn't reproduce with `--blend-subtitles=yes`, just `no` (default).

**Comment by Akemi** [comment]
most likely reported upstream also stale.
