### ISSUE TITLE
Incorrect audio track preselected for separated audio and video files when opened with IPC

### ISSUE THREAD

**Issue by FDMX2** [mpv-player/mpv#3980]
### mpv version and platform
mpv 0.23.0-git-10a005d (C) 2000-2016 mpv/MPlayer/mplayer2 projects
built on Sun Dec 25 15:01:48 CET 2016
ffmpeg library versions:
libavutil       55.43.100
libavcodec      57.70.100
libavformat     57.61.100
libswscale      4.3.101
libavfilter     6.68.100
libswresample   2.4.100

on windows 7

### Reproduction steps
Start mpv.com with seperate audio and video (video has no sound track) file like:
`mpv.com --input-ipc-server="MPVPipe" --no-config --log-file="log.txt" --audio-file="a_audio.webm" "a.webm"`

Connect via IPC with named pipes (for example with this programe: [NamedPipeTest](https://github.com/FDMX2/NamedPipeTest) and load another movie with seperated video and audio file like this:
`{"command":["loadfile","b.webm","replace","audio-file=\"b_audio.webm\""]}`

### Expected behavior
After execution of the IPC command, the video of 'b.webm' should be played together with the audio of 'b_audio.webm' and only one audio track (the one from 'b_audio.webm') should be available.

### Actual behavior
After execution the video of  'b.webm' is played correctly, but the sound still comes from 'a_audio.webm'. Now two audio tracks are available: the old one from 'a_audio.webm', which is preselected, and the correct one from 'b_audio.webm'.

### Log file
[log file ](http://sprunge.us/hNaI )

### Sample files
No special files necessary, same behavior occurs with all tested external audio files like mp3 and mp4.
The webm example comes from youtube videos with separated audio and video file.

**Comment by wiiaboo** [comment]
Maybe `audio-file` can't be used in those options. Use `audio-add` command instead.

**Comment by FDMX2** [comment]
I tried doing this:
1. start mpv with the same command as above: `mpv.com --input-ipc-server="MPVPipe" --no-config --log-file="log.txt" --audio-file="a_audio.webm" "a.webm"`
  => plays as it should with video and sound
2. via IPC executing following command: `{"command":["audio-remove","1"]}`
   => as expected the audio track is removed and only the video plays along
3. via IPC: `{"command":["loadfile","b.webm","replace"]}`
   => video b.webm plays correctly, but the audio track a_audio.webm plays along (instead of being removed!)
4. via IPC: `{"command":["audio-add","b_audio.webm"]}`
   => video b.webm plays correctly, with the correct audio track b_audio.webm, but now the two audio tracks are available

So the second track is not removed between loadings, which should not be the default behavior i guess.


'Removing' audio tracks via IPC after loading is possible, but becomes complicated, if files with external and internal audio are mixed.

**Comment by wiiaboo** [comment]
That's probably because --audio-file is a global option. Either switch to using `audio-add` to add a_audio.webm or try using [`--{`/`--}`](https://mpv.io/manual/master/#per-file-options) to make sure --audio-file=a_audio.webm is only used with a.webm.

**Comment by FDMX2** [comment]
ok, with the --{ --} modifier like:
`mpv.com --input-ipc-server="MPVPipe" --no-config --log-file="log.txt" --{ --audio-file="a_audio.webm" "a.webm" --}`

it works just like i want it to function!

Thx for the quick help!
