### ISSUE TITLE
How to make external subtitles text (like stored in .srt) selectable?

### ISSUE THREAD

**Issue by Edenharder** [mpv-player/mpv#3982]
### mpv version and platform

MPV: 2.3.0, OS: Mac

### Reproduction steps

Select some text in the subtitle when play the video with external subtitle file.

### Expected behavior

the subtitle could be selected, copied and so on.

### Actual behavior

the subtitle cannot be selected

**Comment by lachs0r** [comment]
You mean using the mouse cursor to select text in the subtitles that are displayed on screen? Not going to happen. Use a subtitle editor like Aegisub or a simple text editor.

**Comment by Edenharder** [comment]
@lachs0r yes. Why "Not going to happen"? Is it difficult?

**Comment by lachs0r** [comment]
Yes. Subtitle rendering goes through libass, which does not and will not provide any interface to make this possible. The ASS format which is used internally also has some advanced features which would make reliable text selection pretty much impossible. It’s a very niche use case, not worth the trouble.

**Comment by oltodosel** [comment]
Not exactly what you are looking for, but it won't be hard tweaking it to your needs. 
https://github.com/oltodosel/interSubs
