### ISSUE TITLE
How to set correct color levels?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#3983]
Hi,

Could anyone comment correctness of this Kodi's wiki page http://kodi.wiki/view/Video_levels_and_color_space ?
Is mpv's `--video-output-levels` the right option to get the effects described there?

Regards,
Alex

**Comment by bodayw** [comment]
That wiki page looks correct in general. And yes, ``video-output-levels`` correspond to the first step illustrated there.
