### ISSUE TITLE
Possible to freeze on last frame (using libmpv)?

### ISSUE THREAD

**Issue by tmpsa** [mpv-player/mpv#3984]
### mpv version and platform
latest
If you're not using git master or the latest release, update.

### Reproduction steps
loadfile foo.mp4, loadfile bar.mp4
### Expected behavior
keep showing last frame of foo.mp4 until my program has issued 'loadfile bar.mp4'
### Actual behavior
There's a time gap (of ca 1/2 second), where the background is shown
### Sample files

I have written a program that shows videos and images using libmpv.so / mpv.dll .
My program:
1. gives the command 'loadfile foo.mp4'
2. waits until the event MPV_EVENT_IDLE
3. gives the command 'loadfile bar.mp4'
I need seamless viewing of the videos (can also be images), so that the background is not seen.
But in my case there's a short time gap, when the background is visible.
Is it possible to configure libmpv so that it keeps the last frame on screen forever, or until the next loadfile command? That would be most useful. I have tries various combinations of the settings keep-open and idle, without success. If it can't be done, please add such functionality.

**Comment by lachs0r** [comment]
Are you sure it’s the background and the first/last frame of your video files are not black?

**Comment by wm4** [comment]
Also for such things just append the next file to the playlist.

**Comment by tmpsa** [comment]
Yep, I'm sure. And I don't think a playlist will help; you see, my program should determine what to show each time, there's no pre-ordered list.

**Comment by tmpsa** [comment]
Is there *any* way to make libmpv keep showing the last frame/image forever (or until a new 'loadfile foo.mp4' command is issued)?

**Comment by wm4** [comment]
Either set keep-open, or use a playlist (you don't need to use the full playlist functionality; just append the next file to the playlist a second before the current file ends).

**Comment by tmpsa** [comment]
Setting keep-open works, but then my program needs to know when the video/image has ended.
So it loops with mpv_event_wait. It seems that MPV_EVENT_PAUSE is returned when the video/image has ended. So then it makes the next loadfile bar.p4. But it does not play!

Here's a log of the events; first number is the time in ms, the second is the time diff.
If I just play one file, that works. But with two (or more) only the first is shown; libmpv sort of skips the others.

C:\Projects\FpClient\dist\test-mpv>java -jar test-mpv.jar test2.mp4 test2.mp4
--- Main: show test2.mp4 ---
   141  141 idle
   150    9 start-file
   151    1 log-message       [info] <cplayer>: Playing: test2.mp4
   159    8 tracks-changed
   159    0 metadata-update
   160    1 log-message       [info] <cplayer>:  (+) Video --vid=1 (*) (h264)
   200   40 file-loaded
   224   24 log-message       [info] <vf>: Opening video filter: [rotate angle=auto]
   227    3 video-reconfig
   232    5 log-message       [info] <cplayer>: VO: [direct3d] 1920x1080 yuv420p
   237    5 video-reconfig
   249   12 playback-restart
  6371 6122 pause
--- Main: show test2.mp4 ---
  6390   19 video-reconfig
  6391    1 tracks-changed
  6398    7 end-file
  6399    1 start-file
  6400    1 log-message       [info] <cplayer>:
  6401    1 log-message       [info] <cplayer>: Playing: test2.mp4
  6420   19 tracks-changed
  6421    1 metadata-update
  6422    1 log-message       [info] <cplayer>:  (+) Video --vid=1 (*) (h264)
  6423    1 file-loaded
  6423    0 pause
--- Main: done ---

**Comment by wm4** [comment]
> But it does not play!

Then just unpause it?

In theory you could watch the ``eof-reached`` property to determine whether keep-open mode has paused because the end of the file was reached.

But you won't be able to achieve anything close to "gapless" playback this way.

**Comment by tmpsa** [comment]
Ok, when mpv_wait_event gets MPV_EVENT_PAUSE I'll try to do the commend 'loadfile' of the following video clip, and then 'unpause'. But I can't figure out the command for unpause. Maybe I'm looking in the wrong place. Wouldn't that be documented in
https://mpv.io/manual/stable/#list-of-input-commands ?

**Comment by tmpsa** [comment]
I have also tried another approach. This one is withtout the configuration 'keep-open=yes', and starts over when MPV_EVENT_END_FILE is received.  For each file to be played I do the commands:

playlist-clear
loadfile video1.mp4
loadfile background.jpg append

Then, when I get MPV_EVENT_END_FILE (indicating that video.mp4 is finished and background.jpg starts), I start over again with the same commands:

playlist-clear
loadfile video2.mp4
loadfile background.jpg append

This should, as I understand it:
1. continue to play background.jpg (playlist-clear should "Clear the playlist, except the currently played file")
2.  "Stop playback of the current file, and play the new file immediately."
3. Add background.jpg to the new playlist

But it only plays video1.mp4. 

C:\Projects\FpClient\dist\test-mpv>java -jar test-mpv.jar test1.mp4 test2.mp4
--- Main: show test1.mp4 ---
   137  137 idle
   144    7 start-file
   145    1 log-message       [info] <cplayer>: Playing: test1.mp4
   149    4 tracks-changed
   150    1 tracks-changed
   150    0 metadata-update
   151    1 log-message       [info] <cplayer>:  (+) Video --vid=1 (*) (h264)
   153    2 log-message       [info] <cplayer>:  (+) Audio --aid=1 --alang=eng (*) (aac)
   191   38 audio-reconfig
   191    0 file-loaded
   192    1 log-message       [error] <lavf>: Edit lists are not correctly supported (FFmpeg issue).
   212   20 log-message       [info] <cplayer>: AO: [wasapi] 48000Hz stereo 2ch float
   213    1 audio-reconfig
   213    0 audio-reconfig
   228   15 log-message       [info] <vf>: Opening video filter: [rotate angle=auto]
   234    6 video-reconfig
   235    1 log-message       [info] <cplayer>: VO: [direct3d] 1360x768 yuv420p
   238    3 video-reconfig
   246    8 playback-restart
  5093 4847 audio-reconfig
  5107   14 video-reconfig
  5137   30 tracks-changed
  5137    0 end-file
--- Main: show test2.mp4 ---
  5139    2 start-file
  5139    0 tracks-changed
  5140    1 end-file
--- Main: done ---

I believe that there's a bug in mpvlib.

**Comment by wm4** [comment]
> But it only plays video1.mp4.

No, it also plays "test2.mp4", but immediately exits, for unknown reasons. Some of the log messages that I'd expect are also missing.

> But I can't figure out the command for unpause.

There is none. It's a property. Which in turn is an option that you can change at runtime.

**Comment by tmpsa** [comment]
YES! That did it! So, with configuration keep-open=yes and the sequence
mpv_command(ctx, "loadfile", filepath);
mpv_set_property_string("pause", "no");
executed after mpv_wait_event() returns MPV_EVENT_PAUSE
I get a seamless play, with 100 ms pause, which is quite acceptable, since the last frame is shown during that time. I can also at any time interrupt the ongoing show with another video/image).

Many thanks!

mpv rocks!

(I still suspect there's a bug in mpvlib manifested with the other approach, and will be happy to provide further assistance in finding it!)

**Comment by tmpsa** [comment]
On the subject of bugs and missing log messages: as can be seen in the various logs above, there are log events without any message. Probably not good.

**Comment by wm4** [comment]
There's at least 1 empty log message after a file has finished playing, that's normal.

Anyway, this can be closed.
