### ISSUE TITLE
each frame that shows the OSD prints [osd/libass] [0x7fa9f40ec8e0]: Warning: no style named 'Default' found

### ISSUE THREAD

**Issue by mtmkls** [mpv-player/mpv#3985]
### mpv version and platform
Debian Unstable:
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.2-1
libass5:amd64                                 0.13.5-1
### Reproduction steps
Start playing a video and move the mouse cursor in the bottom half of the mpv window.
### Expected behavior
No message spam on console.
### Actual behavior
Every time the OSD is drawn the above warning is printed.
### log file
$ mpv --msg-level=osd/libass=trace something.mkv
[osd/libass] Raster: FreeType 2.6.3
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.2.7 (COMPLEX)
[osd/libass] Initialized
[osd/libass] Setting up fonts...
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) 'English (AC3)' (ac3)
 (+) Subs  --sid=1 --slang=eng (*) (ass)
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
AO: [pulse] 48000Hz 5.1(side) 6ch float
VO: [opengl] 1920x1080 yuv420p
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf, 0, DejaVuSans
AV: 00:00:00 / 00:01:00 (1%) A-V:  0.000
[osd/libass] [0x7f43f03d7410]: Warning: no style named 'Default' found
[osd/libass] Parsed drawing with 5 points and 1 contours
[osd/libass] Parsed drawing with 5 points and 1 contours
[osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
[osd/libass] Parsed drawing with 12 points and 3 contours
AV: 00:00:00 / 00:01:00 (1%) A-V:  0.000
[osd/libass] [0x7f43f03d7410]: Warning: no style named 'Default' found
[osd/libass] Parsed drawing with 12 points and 3 contours
AV: 00:00:00 / 00:01:00 (1%) A-V:  0.000

**Comment by lachs0r** [comment]
Blame Debian for not rebuilding mpv after updating libass.

**Comment by mtmkls** [comment]
Ok. I assume that mpv segfaulting in libass when jumping to chapter or exiting are the same issue as this one.
