### ISSUE TITLE
libmpv fails on Windows with OpenGL, shows only blue surface

### ISSUE THREAD

**Issue by tmpsa** [mpv-player/mpv#3986]
### mpv version and platform
latest, on Windows
If you're not using git master or the latest release, update.

### Reproduction steps
A program using libmpv that shows videos and images.

### Expected behavior
Show video or image

### Actual behavior
Shows blue color

### Log file
[This is the events caught by my program]:
Other:  start-file
Log:    info: [cplayer] Playing: test0.jpg
Other:  tracks-changed
Other:  metadata-update
Log:    info: [cplayer]  (+) Video --vid=1 (mjpeg)
Other:  file-loaded
Other:  video-reconfig
Log:    info: [cplayer] VO: [opengl] 500x625 yuv420p
Other:  video-reconfig
Log:    error: [vo/opengl] shader link log (status=0): D3D compiler module not found.
Log:    error: [vo/opengl]
Other:  playback-restart
Log:    error: [vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
Log:    error: [vo/opengl] after rendering: OpenGL error OUT_OF_MEMORY.
Other:  video-reconfig
Other:  tracks-changed
Endfile:0
Log:    info: [cplayer]
Other:  video-reconfig

The vanilla mpv program works fine on Windows with vo=opengl or vo=direct3d. But my own program, that uses libmpv, only works with vo=direct3d. With vo=opengl I only get an empty bluish surface, and the errors logged above appears. Is this a bug in libmpv?

**Comment by lachs0r** [comment]
You need d3dcompiler_43.dll.
