### ISSUE TITLE
mpv how to show the osd-status-msg while launching

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#3987]
I want the osd-status-msg to be viewed when i start the video. what options i have to add to the mpv command.

Also later if i want i can turn it off using "shift+o"

osd-status-msg=${osd-sym-cc} ${playback-time} ${?duration:/ ${duration}} ${?percent-pos:(${percent-pos}%)} Size: ${?file-size:${file-size}}

**Comment by ChrisK2** [comment]
https://mpv.io/manual/master/#options-osd-level
