### ISSUE TITLE
(libmpv) mpv_set_property_string returns an error but still works when used before mpv_initialize

### ISSUE THREAD

**Issue by gunnarmarten** [mpv-player/mpv#3988]
### mpv version and platform

mpv HEAD-43386a7
ffmpeg 3.2.2
OSX 10.11.6

### Reproduction steps

I'm using libmpv with opengl-cb in my opengl application. I recently updated to the newest API changes and changed the `mpv_set_option_string` to `mpv_set_property_string` for all my options. Some of them are set before the `mpv_initialize`. Like enabling the `config` option and set a `config_dir`. I had a check for the return code and after updating the code it always returned an error although the `config_dir` is actually set. 

To reproduce:
Use the sdl example from https://github.com/mpv-player/mpv-examples.git

add
```
int rc = mpv_set_property_string(mpv, "config", "yes");
printf("rc %s\n", mpv_error_string(rc));
```
just before the `mpv_initialize` call.

Build and run.

### Expected behavior

Should set the property and return success

### Actual behavior

returns error code -11 which is "error accessing property"

### Log file

none

### Sample files

any file

**Comment by wm4** [comment]
The return value was incorrect, should work now.

**Comment by gunnarmarten** [comment]
cool yes works now. Thanks for the quick fix.
