### ISSUE TITLE
Display Edition title with OSD when cycling

### ISSUE THREAD

**Issue by Ghosthree3** [mpv-player/mpv#3990]
Pretty much what the title says. Any chance you could add a feature so that when cycling editions (default keybind 'E cycle edition') the title of the edition is displayed for 2 seconds or so using the OSD. Right now the only way (that I have found) to really check is using the repl.lua script and it's not very pleasant.

**Comment by wiiaboo** [comment]
There's no way to do it for a single edition, but using `edition-list` prints a list of all editions with titles:
```nginx
e      cycle edition; show-text "Editions:\n${edition-list}"
E      cycle edition down; show-text "Editions:\n${edition-list}"
```

**Comment by Ghosthree3** [comment]
That's actually pretty much perfect, except that it shows an arrow pointing at the edition that was just IN use rather than the one that is now in use (not sure why since it occurs after the cycle...).

I experimented with cycle edition down by the way and it behaves strangely, seems to just cycle down from edition >0 towards 0 until it reaches 0 and then it just keeps selecting it. Doesn't bother me since I'm fine with the cycle edition behaviour.
