### ISSUE TITLE
YouTube problems.

### ISSUE THREAD

**Issue by DebugReport** [mpv-player/mpv#3998]
### mpv version and platform

mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 25 19:20:18 UTC 2016
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.2
Arch Linux laptop 4.9.0-1-ARCH #1 SMP PREEMPT Thu Dec 22 13:21:10 CET 2016 x86_64 GNU/Linux

### Reproduction steps
mpv -v https://youtu.be/xPFRUM_oDKA --start 00:14:00

### Log file

https://gist.github.com/DebugReport/3dc6e8b6e90d34b02a59c75c709e8aec

[cache] Cache is not responding - slow/stuck network connection?
But my network not slow...
![speedof me_17-01-07](https://cloud.githubusercontent.com/assets/23472035/21744390/4f370834-d50c-11e6-8021-b2eb6b45170a.png)

**Comment by DebugReport** [comment]
I can't reproduce it today. Maybe it's temporary problem...

**Comment by lachs0r** [comment]
It most likely is. There are many factors deciding the speed at which you can stream YouTube, such as your ISP’s peering. For example, Vodafone in Germany (which also encompasses Kabel Deutschland) is known for heavy oversubscription and constant problems with certain CDNs like Cloudflare.

**Comment by garoto** [comment]
That's one of the scenarios where a cheap VPS acting as a proxy comes in handy.
