### ISSUE TITLE
Allow negative values for the speed option to reverse playback

### ISSUE THREAD

**Issue by saagarjha** [mpv-player/mpv#4000]
### mpv version and platform

mpv 0.23.0, macOS 10.12.3 (16D17a)

### Reproduction steps

`mpv foo.mp4 --start=50% --speed=-2`

### Expected behavior

mpv launches, starts the video and 50%, and plays the video in reverse at 2x speed.

### Actual behavior

mpv fails to launch with the following error:

```
The speed option is out of range: -2
Error parsing option speed (parameter is outside values allowed for option)
Setting command line option '--speed=-2' failed.
```

### Log file

N/A

### Sample files

N/A

**Comment by wiiaboo** [comment]
Inter-frame codecs (most in use today) don't work well with reverse playback.

This is probably a wontfix, c.f. https://github.com/mpv-player/mpv/issues/3805

**Comment by saagarjha** [comment]
Is there no way to provide rudimentary support for this by skipping to individual frames (in reverse order)? It's fine if it doesn't run at 60 FPS.

**Comment by wm4** [comment]
You can get a similar effect by keeping the `,` key (for frame backstep) pressed. Of course it's very slow.

Real backwards playback would be a nice thing, but definitely not easy to add. You could try a gstreamer player, since gstreamer has support for true backwards playback - I've never seen it in action anywhere, though.

**Comment by TeoColuccio** [comment]
Has there been any significant update?

**Comment by CounterPillow** [comment]
@TeoColuccio you can use `--play-dir=-` now.

**Comment by CounterPillow** [comment]
I'm not sure what you mean by "normal mode"

**Comment by varenc** [comment]
Could `play-dir` get a keybinding in the default input.conf? I've seen several long time mpv users suddenly just discover this amazing functionality. (though I do wish its interface was a negative speed, but I digress)
