### ISSUE TITLE
YouTuve livestream on Windows: buffer runs empty, playback stalls

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4004]
### mpv version and platform
0.23 Windows 10 x64

### Reproduction steps
When I watch a livestream on YT, the buffer runs empty and playback stalls due to this.
This doesn't happen on Linux. However, on Linux there are lots of ffmpeg warnings that TLS connection had been terminated unexpectedly. Just want to mention it. Not a big deal since playback seems to be fine, unlike on Windows.
Using latest Windows youtube-dl version from here (2017.01.08):
https://rg3.github.io/youtube-dl/

### Expected behavior
YouTube livestream playback shouldn't stall on Windows.

### Actual behavior
It stalls, you can't watch livestreams like this.

### Log file
http://sprunge.us/RDEQ

**Comment by wm4** [comment]
If it stalls after not even a minute, it might actually be debugable. Example URL?

**Comment by aufkrawall** [comment]
https://www.youtube.com/watch?v=z371JVsNNjY

**Comment by aufkrawall** [comment]
This issue still exists with mpv 0.24 and latest youtube-dl.
Sometimes it can also stall on Linux, bit it usually does this right away and not after minutes of playing. It sometimes helps then to retry playing the YT url several times.

**Comment by aufkrawall** [comment]
It doesn't seem related only to YT, also with HLS live streaming seems less stable on Windows than on Linux (e.g. zdf.de).

**Comment by aufkrawall** [comment]
I'm still having this issue with livestreams in general on Windows with mpv.
For example with this livestream:
https://zdf1112-lh.akamaihd.net/i/de12_v1@392882/master.m3u8?
Buffer runs empty after a few minutes. VLC Player works.

Would it make sense to attach a log for this again with a recent mpv build?
This bug really kills one of mpv's main fields of application on Windows. :(

**Comment by aufkrawall** [comment]
Not an mpv issue, see #4805
