### ISSUE TITLE
suggestion for color LUT in shaders

### ISSUE THREAD

**Issue by brunogm0** [mpv-player/mpv#4005]
http://opencolorio.org/FAQ.html

OpenColorIO is released as version 1.0 and has been in development since 2003. OCIO represents the culmination of years of production experience earned on such films as SpiderMan 2 (2004), Surf’s Up (2007), Cloudy with a Chance of Meatballs (2009), Alice in Wonderland (2010), and many more. OpenColorIO is natively supported in commercial applications like Katana, Mari, Silhouette FX, and others coming soon.

LICENSE? New BSD.
You are welcome to include the OpenColorIO in commercial, or open source applications

**Comment by haasn** [comment]
I have no idea what this issue is supposed to be about.
