### ISSUE TITLE
mpv drops frames trying to render ass subtitles.

### ISSUE THREAD

**Issue by bitingsock** [mpv-player/mpv#4006]
### mpv version and platform
https://mpv.srsfckn.biz/mpv-x86_64-20161225.7z
Win10x64

### Reproduction steps
Play sample file.
### Expected behavior
Plays smooth.
### Actual behavior
mpv drops frames trying to render these subtitles.
### Log file
http://pastebin.com/bH6femax
### Sample files
http://0x0.st/fMq.mkv

**Comment by lachs0r** [comment]
Can’t reproduce.

**Comment by bitingsock** [comment]
I suppose I should elaborate: specifically when they subtitles overlaying the road sign are moving is when it drops frames for me.

**Comment by wiiaboo** [comment]
Can't reproduce either.

**Comment by bitingsock** [comment]
I've concluded this line of my options is what is causing the problem:
sub-ass-force-style=Outline=1.5

**Comment by phydano** [comment]
I don't get any frame dropped either....but good on you since you found out what causing it :)
