### ISSUE TITLE
Why is there so many VO after I change my RAM to 8G 1600 dual channel?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#4007]
### mpv version and platform

```
mpv 0.22.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Thu Dec 15 21:04:53 UTC 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.68.100
   libavformat     57.60.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: 3.2.git
```
There was no such problem when I used 4G 1333 RAM with single channel.
![2017-01-09 12 24 30](https://cloud.githubusercontent.com/assets/20014762/21757309/aa198540-d667-11e6-9111-2a082cf64e65.png)

Here is my config file:
```
vo=opengl 
sub-auto=fuzzy
hwdec=auto
sub-font="AR PL UKai TW"
sub-border-size=1.5
stretch-image-subs-to-screen=yes
fs
af=lavfi=[sofalizer=sofa=/home/laichiaheng/.config/mpv/ClubFritz4.sofa:gain=13:speakers=FL 22.5|FR 337.5|BL 150|BR 210:type=freq]
sub-use-margins=no
sub-bold=yes
sub-shadow-offset=1.0
sub-shadow-color=000000
audio-device=alsa/plughw:CARD=PCH,DEV=0
script-opts=autospeed-xrandr=true,autospeed-osd=true,autospeed-spause=2,autospeed-speed=true,autospeed-estfps=true
```
My hardware:
```
CPU: i5-4460
GPU: intel iGPU HD4600
RAM: 4G 1600*2
```

It doesn't happen to the video with 1920X1080 or 3840X2160 resolution, but happens to something like  1920X808

**Comment by Hrxn** [comment]
(Obligatory comment about issue tracker not being a support forum etc.)

**Comment by JulianLai** [comment]
It is solved after I change the `type=freq` of sofilizer to `type=time`, but I still don't understand what happens..

**Comment by fhlfibh** [comment]
@Hrxn Unfortunately, there's no support forum for mpv at all, so we're forced to use this issue tracker (or irc channel, but it's less convenient) as one...

@JulianLai These frame-drops are hardly related to RAM. Mightbe, they occur because of AV synchronization.

**Comment by richardpl** [comment]
type=time should use even more CPU power than type=freq for no audible gain.

Perhaps it is because your CPU clock is in adaptive mode?

**Comment by Hrxn** [comment]
IRC is less convenient?

#mpv @ freenode, all you need to know. Any IRC-capable client will do, including Web IRC.
Freenode even has its own Web IRC: https://webchat.freenode.net/

Just ask and wait...

**Comment by lachs0r** [comment]
Note: stats.lua can cause frame drops.

**Comment by JulianLai** [comment]
@lachs0r But there is no frame drops showing on the OSD after I set the type=freq to type=time

**Comment by lachs0r** [comment]
Did it ever occur to you that there may be multiple factors contributing to 
loss of A/V sync?

**Comment by JulianLai** [comment]
@lachs0r 
This is my new setting:
```
vo=opengl
profile=opengl-hq
cscale=lanczos
cscale-antiring=0.7
icc-profile-auto  
icc-contrast=1000
sub-auto=fuzzy
hwdec=auto
sub-font="AR PL UKai TW"
sub-border-size=1.5
stretch-image-subs-to-screen=yes
fs
af=lavfi=[sofalizer=sofa=/home/laichiaheng/.config/mpv/ClubFritz4.sofa:gain=13:speakers=FL 22.5|FR 337.5|BL 150|BR 210:type=time]
sub-use-margins=no
sub-bold=yes
sub-shadow-offset=1.0
sub-shadow-color=000000
audio-device=alsa/plughw:CARD=PCH,DEV=0
script-opts=autospeed-xrandr=true,autospeed-osd=true,autospeed-spause=2,autospeed-speed=true,autospeed-estfps=true
```
As long as I change the type to freq, it drop frames, if I change it back, it plays flawlessly except some frame drops at the beginning. I have no idea what may cause the problem, I only know that everything happens after I change my memory from 4G 1333 to (4G 1600)*2

**Comment by lachs0r** [comment]
HD4600 is your problem. It barely manages opengl-hq at 1920x1080 due to low 
fill rate. Get a better GPU if you want to use these settings.

**Comment by wm4** [comment]
> @Hrxn Unfortunately, there's no support forum for mpv at all, so we're forced to use this issue tracker (or irc channel, but it's less convenient) as one...

Occasional questions are ok, but don't turn this into a forum.
