### ISSUE TITLE
Failing to Build on MacPro 1.1 running Snow Leopard

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#4009]
### mpv version and platform
mpv-build latest , MacPro 1.1 Intel , GT 7300 256 MB, Snow Leopard 10.6.8
If you're not using git master or the latest release, update.

### Reproduction steps

jur-ris-mac-pro-2:mpv-build juri$ ./rebuild -j4
+ git pull --rebase
Current branch master is up to date.
+ do_clone_all
+ do_clone ffmpeg https://github.com/FFmpeg/FFmpeg.git
+ set -ex
+ test -e ffmpeg
+ git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
Cloning into 'ffmpeg'...
remote: Counting objects: 495171, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 495171 (delta 2), reused 0 (delta 0), pack-reused 495162
Receiving objects: 100% (495171/495171), 174.76 MiB | 896.00 KiB/s, done.
Resolving deltas: 100% (383735/383735), done.
Checking out files: 100% (6286/6286), done.
+ cd ffmpeg
+ git remote set-url origin https://github.com/FFmpeg/FFmpeg.git
+ git fetch
+ do_clone fribidi http://anongit.freedesktop.org/git/fribidi/fribidi.git
+ set -ex
+ test -e fribidi
+ git clone http://anongit.freedesktop.org/git/fribidi/fribidi.git fribidi
Cloning into 'fribidi'...
remote: Counting objects: 1511, done.
remote: Compressing objects: 100% (394/394), done.
remote: Total 1511 (delta 1154), reused 1412 (delta 1099)
Receiving objects: 100% (1511/1511), 2.22 MiB | 475.00 KiB/s, done.
Resolving deltas: 100% (1154/1154), done.
+ cd fribidi
+ git remote set-url origin http://anongit.freedesktop.org/git/fribidi/fribidi.git
+ git fetch
+ do_clone libass https://github.com/libass/libass.git
+ set -ex
+ test -e libass
+ git clone https://github.com/libass/libass.git libass
Cloning into 'libass'...
remote: Counting objects: 6481, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 6481 (delta 0), reused 0 (delta 0), pack-reused 6473
Receiving objects: 100% (6481/6481), 2.21 MiB | 915.00 KiB/s, done.
Resolving deltas: 100% (4310/4310), done.
+ cd libass
+ git remote set-url origin https://github.com/libass/libass.git
+ git fetch
+ do_clone mpv https://github.com/mpv-player/mpv.git
+ set -ex
+ test -e mpv
+ git clone https://github.com/mpv-player/mpv.git mpv
Cloning into 'mpv'...
remote: Counting objects: 257701, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 257701 (delta 10), reused 0 (delta 0), pack-reused 257666
Receiving objects: 100% (257701/257701), 75.65 MiB | 1.53 MiB/s, done.
Resolving deltas: 100% (202580/202580), done.
+ cd mpv
+ git remote set-url origin https://github.com/mpv-player/mpv.git
+ git fetch
+ do_gitmaster ffmpeg n
+ set -ex
+ cd ffmpeg
+ git checkout --detach origin/master
HEAD is now at cd09e3b349... x86inc: Avoid using eax/rax for storing the stack pointer
+ git remote prune origin
+ do_releasetag fribidi ''
+ cd fribidi
++ git tag
++ grep -v rc
++ grep -v dev
++ tail -n 1
++ versort_with_prefix ''
++ sed -n -e 's/^\([0-9]\)/\1/p'
++ sed -e 's/^//'
++ sort -n -t . -k 1,1 -k 2,2 -k 3,3 -k 4,4
+ version=0.19.7
+ git checkout --detach refs/tags/0.19.7
HEAD is now at 1a6935c... 0.19.7
+ do_gitmaster libass
+ set -ex
+ cd libass
+ git checkout --detach origin/master
HEAD is now at 3b08a1d... Bump ABI version and release 0.13.6
+ git remote prune origin
+ do_gitmaster mpv v
+ set -ex
+ cd mpv
+ git checkout --detach origin/master
HEAD is now at 9c5cbbf5d... vo_drm: remove 2 redundant include statements
+ git remote prune origin
+ do_update_debian_versions
+ scripts/debian-update-versions
date: illegal option -- R
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
+ do_bootstrap
+ scripts/mpv-bootstrap
Traceback (most recent call last):
  File "./bootstrap.py", line 28, in <module>
    print("Downloading {}...".format(WAFURL))
ValueError: zero length field name in format

**Comment by lachs0r** [comment]
Holy shit upgrade your system already.
