### ISSUE TITLE
VO drops with 25Hz video on 25Hz display

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4010]
Hi,
### mpv version and platform
[cplayer] mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.34.100
[cplayer]    libavcodec      57.64.101
[cplayer]    libavformat     57.56.100
[cplayer]    libswscale      4.2.100
[cplayer]    libavfilter     6.65.100
[cplayer]    libswresample   2.3.100
[cplayer] ffmpeg version: 3.2.2
### Reproduction steps
Switch monitor to video's rate (25Hz) and play the sample file.
### Expected behavior
Smooth playback, no frame drops.
### Actual behavior
Slightly choppy playback, VO drops nearly every other second, vsync-jitter is 10 times higher than normally (all monitored with `stats.lua` script).
### Log file
The (cleaned a bit) log http://sprunge.us/WiEN
Screenshot https://0x0.st/f1Z.png
mpv config http://sprunge.us/EZPG

### Sample files
1 min sample (74M) https://0x0.st/f1N.ts

I previously tried other 25Hz videos, but didn't notice such frame-drops then (but I suspect they were progressive, not interlaced).
When I play the same sample on a 60Hz PC monitor -- there's no frame drops, even with `stats.lua` on screen.

**Comment by fhlfibh** [comment]
Closing the issue.
It looks too hardware-specific, anyway. And in practice, the video is still watchable, after all.
Anyone interested is free to leave a comment, though.

**Comment by Hrxn** [comment]
Probably.. switching to non-standard display refresh rates (i.e. not 60 Hz for typical LCDs), can lead to some problems, depending on GPU, GPU driver and the specific display or display electronic.

You can try to test other applications with 25 Hz, or try full-screen exclusive mode (on Windows), for example. You didn't state your OS or the display in question.
