### ISSUE TITLE
Add Windows mpv to scoop

### ISSUE THREAD

**Issue by RenatoUtsch** [mpv-player/mpv#4011]
Hello,

It would be really nice to add mpv to scoop:
https://github.com/lukesampson/scoop

It's one of the softwares I'm missing the most from there. I'm sure a lot of people would benefit. It also doesn't look like it's going to be very difficult, mpv's Windows builds are well suited to it.

**Comment by lachs0r** [comment]
So you’re asking us to maintain a third-party project instead of creating an issue on their tracker?
