### ISSUE TITLE
High CPU usage - HEVC

### ISSUE THREAD

**Issue by kokowang** [mpv-player/mpv#4012]
MPV 0.22 maxes out my MBPr 2015 when playing 1080p 60fps HEVC video.
Not sure if this is expected behavior; I understand that HEVC may be expensive to decode but using up 4 cores/hyperthreads to decode 1080p?

VLC can decode the same video at under 15% cpu usage. I know VLC is very different from MPV but surely there must be a way to reduce MPV's resource usage to decode H265 right? HEVC is only about 45% more expensive to decode than h264 on Ubuntu, it feels kinda odd that MPV would use 3x more than h264 (h264 software decoder uses 30% cpu for 1080p 60fps, HEVC maxes out and drops frames).

**Comment by Cpuroast** [comment]
I wouldn't be surprised if there's something else at work here.
Start by upgrading to the latest version, currently 0.23.
Are you running stock mpv config, or did you add quality enhancing configuration?

**Comment by kokowang** [comment]
I'm using stock config for video. Subtitles settings were changed but subtitles were not turned on during test.
I just tried 0.23. It plays without framedrops now, although still using ~70% CPU...

**Comment by Cpuroast** [comment]
HEVC decoding is still quite young and quite a bit more complex to decode than H.264.
It will improve over time. H.264 was in a very similar state when it was introduced, CPUs were older and too slow and decoding was barely optimized.

**Comment by Cpuroast** [comment]
and you are sure you didn't add any other options to config except sub tweaks?

Actually very fancy SSA subs, commonly used for anime, sometimes goes berserk and drives CPU usage up the wall regardless of if H.264 or H.265 is used.

**Comment by kokowang** [comment]
Like I said. Subs are not turned on. Any configs shouldn't affect it at all. Sub rendering also shouldn't be dependent on the video codec/decoder used.

**Comment by Cpuroast** [comment]
I never said it was dependant on codec and yeah if the same subs behave on top of h.264 they should behave on top of h.265.

**Comment by Cpuroast** [comment]
On the contrary, mpv is one of the most efficient players out there.

**Comment by kokowang** [comment]
Really? I use also use Quicktime and VLC, both of which has lower resource usage for every video I've tested.

**Comment by Cpuroast** [comment]
Yeah lots of macOS improvements went it as of late.

I assume you are using macOS 10.12? If not lots of the testing is mostly only being done on the current version, so I would suggest upgrading.

**Comment by wm4** [comment]
For h264, Quicktime and VLC might use hardware decoding by default. But fairly sure at least VLC doesn't for HEVC, and the hw might also be too old for that.

**Comment by haasn** [comment]
Does VLC have its own HEVC decoder or does it use libavcodec's?

**Comment by Akemi** [comment]
just wondering do you use the [HEVC patches](https://github.com/haasn/gentoo-conf/tree/fe7de3a7436c6b1c7e6f80c2fda313f207aa3bca/etc/portage/patches/media-video/ffmpeg) @haasn and some other people use that improve HEVC decoding in ffmpeg? if not you could try them.

**Comment by ohjames** [comment]
Since mpv 0.29 CPU usage is constantly at 150%+ on linux, even when decoding h264 720p videos.
