### ISSUE TITLE
Configuration 'opengl-backend' not available in mpvlib?

### ISSUE THREAD

**Issue by tmpsa** [mpv-player/mpv#4013]
### mpv version and platform
mpvlib, latest version
No X11, video should be played directly

### Reproduction steps
in mpv.conf:
vo=opengl
opengl-backend=drm

### Expected behavior
Play video, with hardware acceleration
### Actual behavior
Log messages (level 'error', prefix 'cplayer');
 "Error parsing option opengl-backend (option could not be parsed)"
"mpv.conf:11: setting option opengl-backend='drm' failed."

My program uses mpvlib to play video on an Ubuntu system.

If I play a video using mpv, configured thus:
vo=opengl
vo-backend=drm
the video plays nicely, with only 50% CPU, indicating that hardware acceleration is used.

But if I play the same video using my own program, using mpvlib, that configuration is not accepted.
It gets the abovementioned error log message, and fails.

With the configuration
vo=drm
the video plays nicely, but with 100% CPU, indicating that no hardware acceleration is used.

What is wrong here? Shouldn't mpvlib accept the same configuration as mpv?
How do I set up the configuration so that mpvlib works like mpv in this regard?

**Comment by wm4** [comment]
> vo-backend=drm

That option doesn't exist.  `opengl-backend=drm` is correct. Your libmpv is probably not compiled with DRM/GBM support enabled. Keep in mind that mpv doesn't use the libmpv binary (or the other way around).

**Comment by tmpsa** [comment]
Oh! I thought they were related. Thanks for setting me straight!
