### ISSUE TITLE
[Question] Should I still use [protocol!=http_dash_segments] in my ytdl-format config line?

### ISSUE THREAD

**Issue by garoto** [mpv-player/mpv#4015]
I still have this line in my config and everything seems to be working nicely, but I'm not sure what has happened in code since @wiiaboo posted this workaround. In what state are we (users) now?

Using latest build by lachs0r on Windows 8.1.

**Comment by wiiaboo** [comment]
Still the same, only ytdl_hook adds that by default.

**Comment by garoto** [comment]
Alright, thanks for the answer.
