### ISSUE TITLE
MPV not using 2084/PQ tone mapper on QuickTime files with PQ NCLC Color Tag

### ISSUE THREAD

**Issue by digitaltvguy** [mpv-player/mpv#4017]
### mpv version and platform
0.23.0_2

### Reproduction steps
Open QuickTime Movie that has NCLC color tags 9-16-9 (2020-PQ-2020).  
View file

### Expected behavior
Movie should be tone-mapped to view with a PQ transfer function.
MPV should use embedded index values to turn on HDR tone mapping (similar to the HEVC functionality.

### Actual behavior
No HDR tone mapping occurs

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wm4** [comment]
You shouldn't skip those last 2 steps in the issue template.

Is there any indication that ffmpeg itself reads those tags?

**Comment by lachs0r** [comment]
Looks very much like OP doesn’t care anymore.

**Comment by digitaltvguy** [comment]
..looks like mpv will only write colr atoms.  I can't find a way to read it.

Here's how you write it.

ffmpeg -i <HEVC input movie> -color_primaries bt2020 -colorspace bt2020_ncl -color_trc smpte2084 -movflags +write_colr -strict experimental -vcodec prores_ks -profile:v 4444 -pix_fmt yuva444p10le -an <Output Movie Path>.mov.

**Comment by EsmeraldaQuintero** [comment]
Do you known how to do the same but for prores_aw?

**Comment by EsmeraldaQuintero** [comment]
> ..looks like mpv will only write colr atoms. I can't find a way to read it.
> 
> Here's how you write it.
> 
> ffmpeg -i -color_primaries bt2020 -colorspace bt2020_ncl -color_trc smpte2084 -movflags +write_colr -strict experimental -vcodec prores_ks -profile:v 4444 -pix_fmt yuva444p10le -an .mov.

Do you known how to do the same but for prores_aw?
