### ISSUE TITLE
mpv open the video using another decoder

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#4018]
I am using mpv:

I have a mp4 file with the following codec details:

```
ffmpeg -i input.mp4

    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x534 [SAR 801:800 DAR 12:5], 899 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 140 kb/s (default)
```

Now i am trying to open the same file decoding in the lavc:rawvideo codec. I want to decode because i found in raw files its easy to navigate frames back and forth smoothly using keyboard shortcuts like "." and ","

so i tried:

`mpv --vd=lavc:rawvideo "input.mp4"`

but i dont think it decoded it into rawvideo.

I looking something similar to when i open a file in avidemux, it decodes the file and opens. then the file becomes very smooth to navigate

mp4 files navigation is by key frames. not so good in single frames

**Comment by wiiaboo** [comment]
That doesn't work that way.

Reencode the file into an intra-frame codec and you'll have the fast seeking you want.

**Comment by sant527** [comment]
reencoding will take away space. How is avidemux is doing it.

**Comment by wiiaboo** [comment]
No idea. Maybe a frame cache? H.264 can be intra-only, just reencode to the same bitrate with `--keyint 1`.
