### ISSUE TITLE
mpv step forward is fast but step back is slow

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#4019]
in mpv keyboard shortcuts:

```
.      Step forward. Pressing once will pause, every consecutive press will play one frame and then go into pause mode again.
,        Step backward. Pressing once will pause, every consecutive press will play one frame in reverse and then go into pause mode again.
```

Step forward is faster but step backward is slow. Because i am using some lua scripts to trim video.

how to make both work easily.

If i re encode the video to mjpeg format then it its vert smooth

**Comment by lachs0r** [comment]
That’s because MJPEG is an intra-only codec. Most common video codecs (H.264 etc.) can only be decoded efficiently in forward direction. Without keeping all frames since the last keyframe in memory (which is an indefinite number), you cannot framestep backward smoothly.

**Comment by wm4** [comment]
mpv could probably bother to cache some frames, but in general this can't be fixed.

**Comment by stibinator** [comment]
Playing back prores (all I-frame) shows the same behaviour.

**Comment by wm4** [comment]
Because it doesn't special-case it. It will still seek somewhat before the frame, and then decode/skip all frames until the target. If behavior of other demuxers/codecs weren't potentially so broken, this could actually be made pretty fast.

**Comment by stibinator** [comment]
Djvview has the option of caching decoded frames in memory, is this possible with mpv? Maybe with a user specifiable RAM cache, like djvview? I use mpv for previewing renders and so on, the ability to smoothly play backwards would be really useful.

http://djv.sourceforge.net/

**Comment by wm4** [comment]
In theory yes. But there are other issues like demuxer state, audio playback, and filtering, which make this more complicated. I don't really have time to work on such things.

**Comment by wm4** [comment]
Anyone who needs this can also just try very small precise seeks. These don't guarantee as much that the frame steps back correctly, but it should still work pretty well.

Something like:
```
<key> seek -0.05 exact
```
in input.conf. The seek distance should be larger than a frame duration, but smaller than two.

**Comment by TheSneakySniper** [comment]
`--demuxer-seekable-cache=yes --cache=yes --demuxer-max-back-bytes=10000M --hr-seek=yes --demuxer-cache-wait=yes`

**Comment by kanehekili** [comment]
In addition to the tip above I could seek precisely in mts streams using the --hr-seek-deumuxer-offset=1.5 option solved it.

**Comment by metavolution** [comment]
wow u dev guys r0ck ~ what u write here and in man page !! 

with play-dir hack, and tuning the demuxer options, 
got it to work with 4K HEVC smooth backwards playback, 
video synced with reverse audio, with cpu or gpu decode : -)

best video player feature ever ; -)

+ + +

cache=yes
demuxer-readahead-secs=60
demuxer-seekable-cache=yes
demuxer-max-bytes=1000MiB
video-reversal-buffer=500MiB
audio-reversal-buffer=200MiB
demuxer-max-back-bytes=700MiB
hwdec-extra-frames=2000
hr-seek=yes
demuxer-cache-wait=yes
#demuxer-backward-playback-step=<seconds>

+ + +

got hints what might be nonsensical in the above config?

thx 4 all the code

**Comment by notevenaperson** [comment]
> `--demuxer-seekable-cache=yes --cache=yes --demuxer-max-back-bytes=10000M --hr-seek=yes --demuxer-cache-wait=yes`

I don't know why this has so many positive reactions, doesn't look like it did anything. Doesn't mpv use a cache already? Increasing the cache size doesn't do anything. Depending on the video, stepping back `,` continues to take on second or more, yet stepping forwards is instant. `seek -0.05 exact` is just as slow too. These configurations don't change that mpv still does what @/Mia-0 said at the start of the thread, mpv has to decode forwards since the last keyframe to find the frame just one frame ago.

I would prefer if mpv could have a small cache of previous frames.

**Comment by metavolution** [comment]
with the options i mentioned, it works for me on most video files to go any direction one frame. there is even a hotkey for playing backwards. and that works instantly u can go back and forth in video in any playback speed. if its 4k and x265 one needs a GPU that supports that decoding. in my simple setup mpv can play most video files any speed and any direction. even with reverse sound and pretty instant no delay. hook up a usb playstation controller to controll it, and it is the coolest media player ever. have to experiment with tuning these options to your system though ;)

**Comment by notevenaperson** [comment]
> with the options i mentioned, it works for me on most video files to go any direction one frame. there is even a hotkey for playing backwards. and that works instantly u can go back and forth in video in any playback speed.

Those sets of options don't do anything for me. This might depend on the video codec and mpv configuration. I will test with a sample video and report back. Meanwhile I came up with a funny hack:
```
, cycle-values play-dir - +
. frame-step               
```

**Comment by notevenaperson** [comment]
> I will test with a sample video and report back.

Well, can you frame-back-step *smoothly* in this [Big Buck Bunny h264](http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4)? I can't. (default config or default config + cache options purported to work in this thread)

**Comment by metavolution** [comment]
well after u mentioned it, ur right, reverse playback works, but single step one frame back somehow is slow. especially on 4k content. on 1080p however most files it works near same speed as frame forward.

its interesting, maybe in reverse paly-dir mode, it uses a larger cache, while in single step operation, does not access this buffer or something.

**Comment by lucas-deangelis** [comment]
> Meanwhile I came up with a funny hack:
> ```
> , cycle-values play-dir - +
> . frame-step  
>```

That's a great hack, it works like a charm, thanks! However, I think the `. frame-step` might be unnecessary? I've tried with and without it and there's no difference, I'm not sure I understand why it's used here.

**Comment by notevenaperson** [comment]
> > Meanwhile I came up with a funny hack:
> > ```
> > , cycle-values play-dir - +
> > . frame-step  
> > ```
> 
> That's a great hack, it works like a charm, thanks! However, I think the `. frame-step` might be unnecessary? I've tried with and without it and there's no difference, I'm not sure I understand why it's used here.

Yeah `. frame-step` is the default already, I just included it in the example of stepping backwards and forwards to tell you "this is how you move".

**Comment by richardpl** [comment]
play-dir - need to cache frames in memory, and changing direction of play probably kills previous state.

**Comment by nucspl** [comment]
sorry to necro this but i got really annoyed by the slow `,` backstepping that i decided to make a script to "fix" it

<details>
<summary>backstep.lua</summary>

```
-- backstep.lua
--
-- Faster frame-back-step for mpv

local mp = require('mp')

function change_direction(direction)
	if mp.get_property('play-direction') ~= direction then
		mp.command('cycle play-direction')
		osd_message = string.format('P: %s', direction:gsub('^%l', string.upper))
		mp.osd_message(osd_message)
	end
end

function frame_step(event, direction)
	change_direction(direction)
	if event.event == 'down' or event.event == 'repeat' then
		mp.command('frame-step')
	elseif event.event == 'up' then -- counters imprecision of 'repeat'
		mp.set_property('pause', 'yes')
	end
end

mp.add_key_binding(nil, 'frame-forestep', function(event)
	frame_step(event, 'forward')
end, {complex = true})

mp.add_key_binding(nil, 'frame-backstep', function(event)
	frame_step(event, 'backward')
end, {complex = true})

mp.add_key_binding(nil, 'fore-play', function(event)
	change_direction('forward')
	mp.command('cycle pause')
end)
```

</details>

<details>
<summary>input.conf changes</summary>

```
# backstep.lua - frame stepping
, script_binding frame-backstep
. script_binding frame-forestep

# backstep.lua - pause cycling
MBTN_RIGHT script_binding fore-play
p script_binding fore-play
SPACE script_binding fore-play
PLAY script_binding fore-play
PAUSE script_binding fore-play
PLAYPAUSE script_binding fore-play
```

</details>

there's just a few issues:
- prolonged or too much playback on `play-direction backward` can sometimes cause reversal frame queue overflow
    - i've read that increasing `video-reversal-buffer` or `demuxer-max-back-bytes` helps but it can still occur every now and then
- it's prone to audio-video desync
- it takes two inputs to properly begin stepping frames after changing `play-direction` (i never understood why) but it's better than waiting 20 seconds just to go back 5 frames
    - in case you want to observe this, add a line to your `osd-status-msg` to display video frame count like so

https://github.com/user-attachments/assets/34d7e9c8-012c-4662-a130-0c8f2db6ff61

despite the small problems, it's more than enough for my use case, i hope this helps(:

**Comment by geextahslex** [comment]
@nucspl Hi, the solution for me is to not use the scripts forward seeking and just leave it at default, and only keybind the backward seeking to the script. This way you don't have to press the key twice.
Awesome script, thank you :)

mpv seek
```
. frame-step
#, frame-back-step
```

script seek
```
, script_binding frame-backstep
#. script_binding frame-forestep
```

**Comment by netExtra** [comment]
> @nucspl Hi, the solution for me is to not use the scripts forward seeking and just leave it at default, and only keybind the backward seeking to the script. This way you don't have to press the key twice. Awesome script, thank you :)
> 
> mpv seek
> 
> ```
> . frame-step
> #, frame-back-step
> ```
> 
> script seek
> 
> ```
> , script_binding frame-backstep
> #. script_binding frame-forestep
> ```

> sorry to necro this but i got really annoyed by the slow `,` backstepping that i made a script to "fix" it
> 
> backstep.lua
> input.conf changes
> there's just a few issues:
> 
> * prolonged or too much playback on `play-direction backward` can sometimes cause reversal frame queue overflow
>   
>   * i've read that increasing `video-reversal-buffer` or `demuxer-max-back-bytes` helps but it can still occur every now and then
> * it's prone to audio-video desync
> * it takes two inputs to properly begin stepping frames after changing `play-direction` (i never understood why) but it's better than waiting 20 seconds just to go back 5 frames
>   
>   * in case you want to observe this, add a line to your `osd-status-msg` to display video frame count like so:
> 
>  nvenc_h264_1080p_Q25.mp4 
> despite the small problems, it's more than enough for my use case, i hope this helps(:

I used to use a script then reverted to using the mpv input file and like others have said, I only customized the backward seeking only. I will try your script and see what how well it works in comparison. Well worth the necro if it works :)

**Comment by geextahslex** [comment]
@netExtra what do you mean by playdir?

**Comment by netExtra** [comment]
> @netExtra what do you mean by playdir?

--play-direction=<forward|+|backward|->
Control the playback direction (default: forward). Setting backward will attempt to play the file in reverse direction, with decreasing playback time. If this is set on playback starts, playback will start from the end of the file. If this is changed at during playback, a hr-seek will be issued to change the direction.

It then goes on to explain why backward playback will usually be slow and always be problematic.

**Comment by LonelyFarts** [comment]
I find this to be nice. Then you can still step back 1 frame if you need to. 
/ cycle-values play-dir - +
. frame-step      

One thing I wouldn't mind would be if MPV would use as many resources as it needs. My computer is barely jogging while MPV is lagging.
