### ISSUE TITLE
How to log framedrops?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4020]
Hi,

Is it possible to log frame-drops (i.e. to mark them in `--log-file=` file?

Regards,
Alex

**Comment by wm4** [comment]
No.

**Comment by fhlfibh** [comment]
Pity...

BTW, is it possible _not_ to log OSD messages made with `mp.osd_message`?

**Comment by wm4** [comment]
Also no.

What's logging framedrops supposed to be good for?

**Comment by fhlfibh** [comment]
With logging frame-drops can be watched with `watch tail` over ssh.
At the moment I have to watch them with OSD, e.g. with `stats.lua` (which in turn pollutes the log quite a bit).

**Comment by lachs0r** [comment]
That doesn’t really answer the question.

**Comment by fhlfibh** [comment]
@lachs0r What exactly doesn't answer? I can't invent anything else besides creating a lua script (at the moment, at least).

**Comment by garoto** [comment]
`tail -f mpvlog | grep "dropped"` ?

**Comment by fhlfibh** [comment]
@garoto Dropping frames is not indicated in the log at all, as far as I could understand from the above. If it were -- my problem's been solved.

**Comment by garoto** [comment]
Oh didn't know that, my bad then.

**Comment by haasn** [comment]
You can get a log of performance-related stats and events, including dropped frames, using ``--dump-stats``

**Comment by fhlfibh** [comment]
@haasn Will try that, thanks!
