### ISSUE TITLE
Weird horizontal lines on video when in full screen

### ISSUE THREAD

**Issue by prahulkgp** [mpv-player/mpv#4021]
### mpv version and platform
https://mpv.srsfckn.biz/mpv-x86_64-20161225.7z on Windows 10 64 bit.
my mpv config https://www.hastebin.com/raw/ahumefequm

Often when I play videos in full screen or when i play native resolution videos without full screen by auto hiding the task bar, horizontal lines like http://i.imgur.com/3GXpkAc.png appear when i move my cursor to the bottom for osd to appear, and on the video too.
I had to take a photo instead of the screenshot and I explained it below.
What is weird is that when I use s to take a screenshot, the screenshot doesn't contain those lines. And when playing any video, in the player itself, once I see those lines and I go back from full screen to normal, those lines disappear.
If I pause the video when I see these lines, after a second or two, they disappear.
I tried removing the config and playing a video but the issue still persists.

**Comment by lachs0r** [comment]
Hardware defect.
