### ISSUE TITLE
On Windows, "include" declaration in mpv.conf generates infinite recursion and console error msg

### ISSUE THREAD

**Issue by garoto** [mpv-player/mpv#4024]
### mpv version and platform
```
Windows 8.1

mpv 0.23.0-git-10a005d (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 25 15:01:44 CET 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.70.100
   libavformat     57.61.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: N-82928-g77856a8
```

### Reproduction steps
Having something like an `include=~~/oldies.conf` entrie in `mpv.conf` will generate the following console error message as the 1st output:
```
> mpv I:\Recordings\OBS\January_2017\11-Jan-2017_18h35m.mp4
**Maximum 'include' nesting depth exceeded.
Error parsing option include (option could not be parsed)**
Playing: I:\Recordings\OBS\January_2017\11-Jan-2017_18h35m.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=und (*) (aac)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
oldies.conf loaded
AV: 00:00:02 / 00:01:43 (2%) A-V:  0.000
```
Abeit the error output, the additional .conf file will be read and parsed successfully, as the line `oldies.conf loaded` above shows. 

There will be **NO** error message if I remove the `mpv.conf` include entrie and add it as a CLI parameter: `mpv --include=~~/oldies.conf I:\Recordings\OBS\January_2017\11-Jan-2017_18h35m.mp4`

I tested with `include=~~/oldies.conf` and `include=C:/Users/username/AppData/Roaming\mpv\oldies.conf` and both syntaxes generates the error.
 
### Expected behavior
No error message if everything goes fine I guess.

### Actual behavior
Infinite loop reading `include` declaration generates console error message as explained above.

### Log file
http://sprunge.us/ThCW

### Sample files
mpv.conf: http://sprunge.us/IYFI
oldies.conf: http://sprunge.us/DbOF

**Comment by garoto** [comment]
Why don't the config parser trigger the bug when `--include` is passed as a command line argument?

**Comment by wm4** [comment]
Complicated reasons.

**Comment by garoto** [comment]
Well, that settles it :D
