### ISSUE TITLE
osd not visible if ipc commands used

### ISSUE THREAD

**Issue by zerkalica** [mpv-player/mpv#4025]
### mpv version and platform

platform: armhf (bananapi)

repository ports.ubuntu.com / zesty

mpv --version:
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects

### Reproduction steps

OSD not visible:

```bash
mpv --input-ipc-server=/tmp/mpv.socket some_video.mkv
echo '{ "command": [ "seek", "+1" ] }' | socat - /tmp/mpv.socket
```

### Expected behavior

osd seek bar visible aftter executing this ipc command.
Any changes via commands trigger osd like changes via keypress:

OSD visible:

```bash
mpv --input-ipc-server=/tmp/mpv.socket some_video.mkv
echo '{ "command": [ "keypress", "right" ] }' | socat - /tmp/mpv.socket
```

### Actual behavior

osd not visible if we exec command

### Log file

https://gist.github.com/zerkalica/e483b6292a5d9f6e2553db4adca641f7

---

Some functionality (like osd popup) in mpv and user lua-scripts (most of all) binds only to hotkeys. But command can be invoked directly from ipc.

Using ``` '{ "command": [ "keypress", "right" ] }' ``` instead of ``` '{ "command": [ "seek", "+1" ] }' ``` is bad workaround. What if hotkey changed?

IMHO, stop using add_key_binding, add_forced_key_binding in lua scripts and deprecate it. Using keybindings directly in lua scripts is bad idea. Lua scripts must provide commands. Keybindings in input.conf binds this commands to hotkeys. Separate commands and hotkeys configuration.

**Comment by wm4** [comment]
It's on purpose, although I'm not sure where the hell it's documented. You can override the osd behavior with those prefixes: https://mpv.io/manual/master/#input-command-prefixes

**Comment by zerkalica** [comment]
Ok, command
```
{ "command": [ "osd-msg-bar", "seek", "1" ] }
```
works.

How to change default behaviour ?

In https://mpv.io/manual/master/#input-command-prefixes

```
osd-auto (default)
Use the default behavior for this command.
```

What does it mean "default behavior" ?

**Comment by wm4** [comment]
These commands are meant for use as API, so the default is always forced to not use OSD.
