### ISSUE TITLE
Variables doesn't expand in show-text command

### ISSUE THREAD

**Issue by zerkalica** [mpv-player/mpv#4026]
### mpv version and platform

platform: armhf (bananapi)

repository ports.ubuntu.com / zesty

mpv --version:
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects

### Reproduction steps

Substitutions doesn't work

```bash
mpv --input-ipc-server=/tmp/mpv.socket some_video.mkv
echo '{ "command": ["show-text", "${filename}" ] }' | socat - /tmp/mpv.socket
```

### Expected behavior

osd shows: some_video.mkv

Workaround as text:

```bash
mpv --input-ipc-server=/tmp/mpv.socket some_video.mkv
echo 'show-text "${filename}"' | socat - /tmp/mpv.socket
```

### Actual behavior

osd shows: ${filename}

### Log file

https://gist.github.com/zerkalica/e483b6292a5d9f6e2553db4adca641f7

**Comment by wm4** [comment]
``expand-properties`` prefix, same deal as with OSD.

**Comment by zerkalica** [comment]
May be change docs? It's not a default.

```
expand-properties (default)
All string arguments are expanded as described in Property Expansion.
```

Probably, default for command is raw

```
raw
Do not expand properties in string arguments. (Like "${property-name}".)
```

**Comment by frankschierle** [comment]
I have the same problem and I still don't get it, sorry,

How do I change the following line, to get the property value expanded?

`echo { "command": ["show-text", "${playback-time}"] } >\\.\pipe\mpvsocket`

**Comment by teleshoes** [comment]
> I have the same problem and I still don't get it, sorry,
> 
> How do I change the following line, to get the property value expanded?
> 
> `echo { "command": ["show-text", "${playback-time}"] } >\\.\pipe\mpvsocket`


ancient thread, but for the next person looking for the quick answer:
`echo { "command": ["expand-properties", "show-text", "${playback-time}"] } >\\.\pipe\mpvsocket`
