### ISSUE TITLE
show-text in force-window for mp3 does not hides after timeout

### ISSUE THREAD

**Issue by zerkalica** [mpv-player/mpv#4027]
### mpv version and platform

platform: armhf (bananapi)

repository ports.ubuntu.com / zesty

mpv --version:
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects

### Reproduction steps

```bash
mpv --input-ipc-server=/tmp/mpv.socket --idle --force-window=yes some.mp3 &
sleep 5
echo '{ "command": [ "show-text", "test1" ] }' | socat - /tmp/mpv.socket
sleep 2
echo '{ "command": [ "show-text", "test2" ] }' | socat - /tmp/mpv.socket
sleep 2
echo '{ "command": [ "show-text", "test3" ] }' | socat - /tmp/mpv.socket
```

### Expected behavior

- test1 popups on 0.5 sec
- test1 hides
- test2 popups on 0.5 sec
- test2 hides
- test3 popups on 0.5 sec 

### Actual behavior

- test1 popups on 0.5 sec
- test1 hides
- test2 popups on 0.5 sec
- test2 stay visible (BUG)
- test3 popups on top of test2 and stay visible too

I just try to use mpv as audio player and show current track.

### Log file

https://gist.github.com/zerkalica/e483b6292a5d9f6e2553db4adca641f7

UPD:

Bug only if --vo=vdpau used, for opengl works fine.

**Comment by wm4** [comment]
> Bug only if --vo=vdpau used, for opengl works fine.

Probably a driver bug. Works on nvidia.

**Comment by lachs0r** [comment]
Driver bug. The sunxi VDPAU implementation is rudimentary, work in progress.
