### ISSUE TITLE
Possible race condition in stream/tvi_v4l2.c ?

### ISSUE THREAD

**Issue by joabreu** [mpv-player/mpv#4028]
Hi,

I am using git master version of mpv (built using mpv-build) and I think I found a possible race condition in tv:// stream.

When capturing from an HDMI RX equipment, in 4k@60Hz mode I'm seeing errors of invalid timestamp. The timestamp value indicates that a "frame from the past" was received ("Invalid video timestamp: x -> y"; y < x). Digging through the mpv v4l2 code I found, in line 1542 of file stream/tvi_v4l2.c, an earlier release to the video mutex, even that video variables are changed after this release (especially video_cnt variable). If I change the mutex release after line 1571 I stop getting invalid video timestamp errors.

Can you confirm if this is a bug? Notice that probably this only happens in 4k video modes, which require a large cpu, data bandwidth, ... So the frame processing is slower which can trigger the race condition.

Best regards,
Jose Miguel Abreu

**Comment by wm4** [comment]
Unknown. The v4l TV code is more or less unmaintained. Are you interested in fixing it?

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.

**Comment by wm4** [comment]
It can't persist because the code was removed. Using libavformat through av:// is now recommended.
