### ISSUE TITLE
No package in CentOS in _any_ repo

### ISSUE THREAD

**Issue by smacz42** [mpv-player/mpv#4032]
### mpv version and platform

If you're not using git master or the latest release, update.

### Reproduction steps

yum install mpv

no package mpv available

### Expected behavior

mpv to be in the repos of ONE OF THE FOLLOWING:

* official centOS
* rpmfusion
* epel

### Actual behavior

No package whatsoever

### Log file

N/A

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wm4** [comment]
Distro packages are not our problems, and we even removed links to them from mpv.io.

Using mpv-build is recommended.
