### ISSUE TITLE
DTS passthrough is broken on mpv 23.0

### ISSUE THREAD

**Issue by danilovsergei** [mpv-player/mpv#4039]
After update from 0.22 to mpv 0.23  spdif passthrough of dolby/dts/ac3 does not work anymore.
My configuration is I have laptop connected via spdif to av receiver.
Execution of mpv with command below provides passthrough of original dolby/dts/ac3 stream.
mpv "RocknRolla.2008.1080p.BluRay.DTS.x264.Rus-DON.mkv" --ad=spdif:ac3,spdif:dts

But since update the same command provides just simple stereo to receiver.
Downgrade to 0.22 fixes this behaviour.
Behavior reproduced on absolutely all video files I have.

There is a link to sample video.Sample video: https://goo.gl/FthRDW
Also there are logs in attach for working 0.22 and broken 0.23
[mpv_22.log.txt](https://github.com/mpv-player/mpv/files/706258/mpv_22.log.txt)
[mpv_23.log.txt](https://github.com/mpv-player/mpv/files/706259/mpv_23.log.txt)

My system:
Gentoo 64bit
MPV use flags: X alsa bluray cdda cli dvb dvd enca encode iconv jack jpeg lcms libass lua luajit opengl pulseaudio samba uchardet v4l vaapi vdpau xinerama xscreensaver xv (-aqua) -archive (-coreaudio) -doc -drm -egl -gbm -libav -libcaca -libguess -libmpv -openal -oss (-raspberry-pi) -rubberband -sdl (-selinux) {-test} -tools -vf-dlopen -wayland -zsh-completion

**Comment by fhlfibh** [comment]
You might want to try `mpv --audio-spdif=ac3,dts" as here https://mpv.io/manual/stable/#options-audio-spdif

**Comment by wm4** [comment]
It's not from what I can tell.
