### ISSUE TITLE
Codec profile: unknown (0xffffff9d) with CUDA

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4040]
### mpv version and platform
[cplayer] mpv git-ddaab33 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sat Jan 14 18:04:25 MSK 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.43.100
[cplayer]    libavcodec      57.72.100
[cplayer]    libavformat     57.62.100
[cplayer]    libswscale      4.3.101
[cplayer]    libavfilter     6.69.100
[cplayer]    libswresample   2.4.100
[cplayer] ffmpeg version: N-83104-g9354049

### Reproduction steps
Play a file with `vo=opengl hwdec=cuda`

### Actual behavior
There's `[vd] Codec profile: unknown (0xffffff9d)` in the log.

### Log file
http://sprunge.us/KbKR

### Sample files
http://jell.yfish.us/media/jellyfish-3-mbps-hd-h264.mkv

This `Codec profile: unknown` doesn't happen with `hwdec=cuda-copy`.
Also in gentoo's bugzilla https://bugs.gentoo.org/show_bug.cgi?id=603974

Not sure if it's a bug or not, because video seems to play normally anyway.

Regards,
Alex

**Comment by haasn** [comment]
Works for me on a GTX 970. Maybe the GTX 660 is too old to support H.264?

**Comment by fhlfibh** [comment]
@haasn No idea... But it defenitely has h.264 hw decoding with VDPAU, with no problems so far, afaik.

**Comment by wm4** [comment]
It's probably FF_PROFILE_RESERVED, because the cuda decode wrapper doesn't set the profile. There is no problem.
