### ISSUE TITLE
build: automagic SSE support

### ISSUE THREAD

**Issue by Coacher** [mpv-player/mpv#4041]
Hello.

Currently mpv autodetects whether the required SSE bits are available on build host and depending on this compiles the SSE code. This automagic behaviour leads to mismatches when build and host systems have different SSE support.

Please make SSE support controllable via configure option.

**Comment by rossy** [comment]
I don't think this should cause a problem. As far as I understand it, the build script checks whether SSE4 intrinsics are supported by the compiler, but they are only used if the SSE4 support is detected on the host at runtime.

**Comment by wm4** [comment]
There is no problem.

**Comment by haasn** [comment]
Note: Even if the code is valid, some build systems care about reproducable builds (i.e. same code = same binary), so being able to override all auto-detection is pretty important for them.

That said, wouldn't e.g. specifying `-march` on your command line disable support for SSE4 or whatever in the compiler? Would mpv detect this?

**Comment by ArchangeGabriel** [comment]
@haasn Reproducible build means same compiling tool chain, so this wouldn’t be an issue either here.
