### ISSUE TITLE
Using native OS X fullscreen, mpv is shifted a bit to the bottom going out of the screen

### ISSUE THREAD

**Issue by Porkepix** [mpv-player/mpv#4044]
### mpv version and platform

mpv latest build from master a few hours ago, on OS X Mavericks

### Reproduction steps

Launch a video from terminal, here tested with youtube videos through youtube-dl or with local files.

### Expected behavior

Full screen should be correctly aligned

### Actual behavior

Fullscreen isn't aligned: at the top of the screen, there is an unused grey space, probably having the size of the menubar, and at the bottom half of the osd goes out of the screen because of that shift. See screenshot for clearer understanding.

### Log file
Logs: http://paste.leloop.org/?a7d1790043cfebab#hv4ny7tgwXd7BcyGL5oHE4htzeZPN61ag2QuNiHflUI=

### Screenshot

https://lut.im/cdIoHbhBvi/4LLci6uxTrVmeSQK.png

**Comment by Akemi** [comment]
if i remember correctly this was an issue on 10.9 and the native fullscreen, which was fixed with newer OS x versions. no not our bug.

**Comment by Porkepix** [comment]
Well, if this is an OS X issue, then why is mpv the only affected software?

Didn't noticed that anywhere else, and this is especially more frustrating that before the shift to native full screen instead of the previous one, there were no issues like that.

**Comment by Akemi** [comment]
i merged the fix into master.

**Comment by nkanaev** [comment]
@Akemi, issue still exists.

### mpv version and platform

v0.27.0 on OS X Mavericks

### reproduction steps

* enter full screen mode (native)
* enter mission control (multiple desktop listing)
* switch back to mpv


Not sure if it helps, but VLC seems to have resolved the issue [here](https://github.com/videolan/vlc/blob/43f4b269311df662da74f51a640aea88f48c1876/modules/gui/macosx/Windows.m#L170-L192)

**Comment by Argon-** [comment]
Honesty though, this is a bug in OSX. Your link shows it's possible to work around it but is it worth it adding yet another workaround...

**Comment by nkanaev** [comment]
yes, i'm aware that it's osx bug. however, i thought that if vlc could fix it, folks at mpv could do the same (given that you've already added a workaround to partially fix it).

**Comment by Akemi** [comment]
it wasn't really a workaround, we actually did something wrong. so it was just a fix. i could attempt to fix it but i have no way of testing it. i would do it in one of my OSX VMs but opengl doesn't work there and it crashes on window creation.

**Comment by nkanaev** [comment]
@Akemi i'd be glad to assist in testing. you could send me a binary for testing purposes at nkanaev [at] live [dot] com.

**Comment by Akemi** [comment]
sry, i am not going to do that. it's just too much work.
