### ISSUE TITLE
Issue with pause and opengl

### ISSUE THREAD

**Issue by moosotc** [mpv-player/mpv#4047]
### mpv version and platform
mpv git-64041f963 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Tue Jan 17 08:40:07 MSK 2017
ffmpeg library versions:
   libavutil       55.34.100
   libavcodec      57.64.101
   libavformat     57.56.100
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.2

### Reproduction steps
mpv /dev/zero --demuxer rawvideo --pause

### Expected behavior
Uniform green window

### Actual behavior
Black with green rectangle in upper left corner

### Log file
http://sprunge.us/KQci

**Comment by moosotc** [comment]
Almost the same issue with:
LIBGL_ALWAYS_SOFTWARE=1 mpv /dev/zero --demuxer rawvideo --pause
so the thing can't be blamed on the intel driver alone

**Comment by moosotc** [comment]
`LIBGL_DRI3_DISABLE=1 mpv ...' - fixes it

**Comment by mc4man** [comment]
You would see the same if opening an image file (--keep-open) & having DRI 3 enabled. Only the top left corner of the image would appear until the Osc is exposed, then the image fills in.
Generally thru xserver-xorg-core 1.18.x DRI 2 is the default, in 1.19.x DRI 3 is.

Doesn't seem to affect vid playback or if so it's just for a very brief moment when opening.
If desired one can set back to DRI 2 in  a /usr/share/X11/xorg.conf.d/20-intel.conf file.

**Comment by occivink** [comment]
I've also experience this. What are the consequences of disabling DRI3?

**Comment by occivink** [comment]
If you have high tolerance for ugly hacks you can also add this to your scripts
```
function clear(name, value)
    if value > 0 then
        mp.set_osd_ass(0, 0, "")
        mp.unobserve_property(clear)
    end
end
mp.observe_property("osd-width", "number", clear)
```
which works on my end. Maybe there is a better property to signal that the window is visible too.

**Comment by moosotc** [comment]
Sadly I have no idea how to use/where to put this snippet

**Comment by Hrxn** [comment]
`--script=<filename>`
> Load a Lua script. You can load multiple scripts by separating them with commas (,).

Or the scripts subdir of the mpv profile directory, e.g. ~/.config/mpv/scripts

**Comment by moosotc** [comment]
H R X N <notifications@github.com> writes:

> `--script=<filename>`
>> Load a Lua script. You can load multiple scripts by separating them
> with commas (,).
>
> Or the scripts subdir of the mpv profile directory, e.g. ~/.config/mpv/scripts

Thank you!

-- 
mailto:moosotc@gmail.com

**Comment by moosotc** [comment]
It appears that my hack tolerance is extremely high, so I've settled on the following

`function clear(name, value)
   if value > 0 then
      mp.osd_message (" ", 0.001)
    end
end
mp.observe_property("osd-width", "number", clear)`
