### ISSUE TITLE
volume resets to 100%

### ISSUE THREAD

**Issue by jungle-boogie** [mpv-player/mpv#4048]
### mpv version and platform

>mpv -V
mpv 0.23.0-git-10a005d (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 25 15:01:44 CET 2016
ffmpeg library versions:
   libavutil       55.43.100
   libavcodec      57.70.100
   libavformat     57.61.100
   libswscale      4.3.101
   libavfilter     6.68.100
   libswresample   2.4.100
ffmpeg version: N-82928-g77856a8

### Reproduction steps

0. Play video/audio file
1. Take note of the volume level. E.g., 100%
2. Lower volume by pressing 9 until you get the output to 90%
3. Play next video/audio file
4. Observe the volume changed to 100%

Note, it is not necessary to listen to the entire clip before proceeding to the next step.

### Expected behavior

It's expected the volume of the second and subsequent video/audio files would remain at 90%.

### Actual behavior

Volume on subsequent videos resets to 100%

### Log file

Playing video1: https://www.pastiebin.com/587eb7b40c3cb
Playing video2: https://www.pastiebin.com/587eb7e27dcd0

### Sample files

video1: https://www.youtube.com/watch?v=rrFpX4Rj_2U
video2: https://www.youtube.com/watch?v=QHGOO73Gxg4

**Comment by wiiaboo** [comment]
[This was changed back in 0.18.1 already](https://github.com/mpv-player/mpv/wiki/FAQ#I_want_the_old_PulseAudio_volume_control_back_on_Linux). "Pulseaudio" here means wasapi in Windows.
