### ISSUE TITLE
really tiny issue

### ISSUE THREAD

**Issue by sbxn14** [mpv-player/mpv#4049]
I want to watch a few movies but when I normally watch them they get black border bars on the top and bottom if its a widescreen movie. in mpv they are colored like the movie itself. I Really dislike this. how do I make them black? I cant find it naywhere

**Comment by garoto** [comment]
Weird, that's certainly not how it's supposed to be. Hardware issue?

**Comment by sbxn14** [comment]
oh im sorry I was in a rush :P.

and I found it it's SVP's doing.

**Comment by garoto** [comment]
Great, you may close this issue then.
