### ISSUE TITLE
mpv on sailfish os (jolla linux phone with wayland)

### ISSUE THREAD

**Issue by paolomi** [mpv-player/mpv#4050]
I've compiled mpv on a jolla phone with sailfish os(*) but all videos fail to play:
wl_registry@2: error 0: invalid version for global wl_seat (11): have 2, wanted 4
Segmentation fault                                                                                                            

(*) https://sailfishos.org     (2.0.5.6 is the latest version)
I've compiled mpv with the script "build"

[nemo@Sailfish ~]$ pkcon search name wayland |grep -i installed
Installed    libhybris-sbj-libwayland-egl-0.0.0.50-10.15.1.jolla.armv7hl
Installed    maliit-framework-wayland-0.99.1-1.14.1.armv7hl
Installed    maliit-framework-wayland-inputcontext-0.99.1-1.14.1.armv7hl
Installed    qt5-qtwayland-wayland_egl-5.4.0+git32-1.45.1.armv7hl
Installed    wayland-1.6.0+git1-1.4.1.armv7hl

[nemo@Sailfish ~]$ mpv -v -vo wayland Videos/dado.mp4 
[cplayer] Command line options: '-v' '-vo' 'wayland' 'Videos/dado.mp4'
[cplayer] mpv git-397705b (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Jan 15 13:19:12 UTC 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.43.100
[cplayer]    libavcodec      57.72.100
[cplayer]    libavformat     57.62.100
[cplayer]    libswscale      4.3.101
[cplayer]    libavfilter     6.69.100
[cplayer]    libswresample   2.4.100
[cplayer] ffmpeg version: N-83119-g0ba0187
[cplayer] 
[cplayer] Configuration: ./waf configure
[cplayer] List of enabled features: asm atomic-builtins atomics audio-input avcodec-chroma-pos-api avframe-metadata avframe-skip-samples avutil-mastering-metadata build-date cplayer cuda-hwaccel debug-build dlopen dvbin dvdread egl-helpers encoding fchmod gcc-tls gl gl-wayland glibc-thread-name glob gnuc iconv libass libass-osd libav libavdevice libavfilter libdl libm librt libswresample linux-fstatfs nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads pulse resampler shm subprocess termios tv tv-v4l2 videodev vt.h wayland zlib
[global] config path: '' -> '/home/nemo/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/home/nemo/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/nemo/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/home/nemo/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/nemo/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/etc/mpv/config'
[cplayer] Setting option 'v' = '' (flags = 8)
[cplayer] Setting option 'vo' = 'wayland' (flags = 8)
[global] config path: 'input.conf' -/-> '/home/nemo/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/home/nemo/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/etc/mpv/input.conf'
[global] config path: 'scripts' -/-> '/home/nemo/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/home/nemo/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[global] config path: 'watch_later' -> '/home/nemo/.config/mpv/watch_later'
[cplayer] Playing: Videos/dado.mp4
[ifo] Opening Videos/dado.mp4
[file] Opening Videos/dado.mp4
[file] Stream opened successfully.
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[ffmpeg/video] h264: Reinit context to 400x320, pix_fmt: yuv420p
[lavf] avformat_find_stream_info() finished after 131072 bytes.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[find_files] Loading external files in Videos/
[global] config path: 'sub/' -/-> '/home/nemo/.config/mpv/sub/'
[global] config path: 'sub/' -/-> '/home/nemo/.mpv/sub/'
[global] config path: 'sub/' -/-> '/usr/local/etc/mpv/sub/'
[global] config path: 'audio/' -/-> '/home/nemo/.config/mpv/audio/'
[global] config path: 'audio/' -/-> '/home/nemo/.mpv/audio/'                                                                  
[global] config path: 'audio/' -/-> '/usr/local/etc/mpv/audio/'                                                               
[cplayer]  (+) Video --vid=1 (*) (h264)                                                                                       
[cplayer]  (+) Audio --aid=1 --alang=ita (*) (aac)
[display-tags] File tags:
[display-tags]  Title: 10153914932207610
wl_registry@2: error 0: invalid version for global wl_seat (11): have 2, wanted 4
[vo/wayland/wayland] output received:
[vo/wayland/wayland]    vendor: (null)                                                                                        
[vo/wayland/wayland]    model: (null)                                                                                         
[vo/wayland/wayland]    w: 0, h: 0                                                                                            
[vo/wayland/wayland]    scale: 1                                                                                              
[vo/wayland/wayland]    Hz: 0.000000                                                                                          
Segmentation fault                  

[nemo@Sailfish ~]$ mpv -v -vo opengl Videos/dado.mp4 
[cplayer] Command line options: '-v' '-vo' 'opengl' 'Videos/dado.mp4'
[cplayer] mpv git-397705b (C) 2000-2017 mpv/MPlayer/mplayer2 projects                                                         
[cplayer]  built on Sun Jan 15 13:19:12 UTC 2017                                                                              
[cplayer] ffmpeg library versions:                                                                                            
[cplayer]    libavutil       55.43.100                                                                                        
[cplayer]    libavcodec      57.72.100                                                                                        
[cplayer]    libavformat     57.62.100                                                                                        
[cplayer]    libswscale      4.3.101                                                                                          
[cplayer]    libavfilter     6.69.100                                                                                         
[cplayer]    libswresample   2.4.100                                                                                          
[cplayer] ffmpeg version: N-83119-g0ba0187                                                                                    
[cplayer]                                                                                                                     
[cplayer] Configuration: ./waf configure                                                                                      
[cplayer] List of enabled features: asm atomic-builtins atomics audio-input avcodec-chroma-pos-api avframe-metadata avframe-skip-samples avutil-mastering-metadata build-date cplayer cuda-hwaccel debug-build dlopen dvbin dvdread egl-helpers encoding fchmod gcc-tls gl gl-wayland glibc-thread-name glob gnuc iconv libass libass-osd libav libavdevice libavfilter libdl libm librt libswresample linux-fstatfs nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads pulse resampler shm subprocess termios tv tv-v4l2 videodev vt.h wayland zlib                                                             
[global] config path: '' -> '/home/nemo/.config/mpv'                                                                          
[global] config path: 'mpv.conf' -/-> '/home/nemo/.config/mpv/mpv.conf'                                                       
[global] config path: 'config' -/-> '/home/nemo/.config/mpv/config'                                                           
[global] config path: 'mpv.conf' -/-> '/home/nemo/.mpv/mpv.conf'                                                              
[global] config path: 'config' -/-> '/home/nemo/.mpv/config'                                                                  
[global] config path: 'mpv.conf' -/-> '/usr/local/etc/mpv/mpv.conf'                                                           
[global] config path: 'config' -/-> '/usr/local/etc/mpv/config'                                                               
[cplayer] Setting option 'v' = '' (flags = 8)                                                                                 
[cplayer] Setting option 'vo' = 'opengl' (flags = 8)                                                                          
[global] config path: 'input.conf' -/-> '/home/nemo/.config/mpv/input.conf'                                                   
[global] config path: 'input.conf' -/-> '/home/nemo/.mpv/input.conf'                                                          
[global] config path: 'input.conf' -/-> '/usr/local/etc/mpv/input.conf'                                                       
[global] config path: 'scripts' -/-> '/home/nemo/.config/mpv/scripts'                                                         
[global] config path: 'scripts' -/-> '/home/nemo/.mpv/scripts'                                                                
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'                                                             
[global] config path: 'watch_later' -> '/home/nemo/.config/mpv/watch_later'                                                   
[cplayer] Playing: Videos/dado.mp4                                                                                            
[ifo] Opening Videos/dado.mp4
[file] Opening Videos/dado.mp4                                                                                                
[file] Stream opened successfully.                                                                                            
[demux] Trying demuxers for level=normal.                                                                                     
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.                                                                
[ffmpeg/video] h264: Reinit context to 400x320, pix_fmt: yuv420p                                                              
[lavf] avformat_find_stream_info() finished after 131072 bytes.                                                               
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)                                                           
[find_files] Loading external files in Videos/                                                                                
[global] config path: 'sub/' -/-> '/home/nemo/.config/mpv/sub/'                                                               
[global] config path: 'sub/' -/-> '/home/nemo/.mpv/sub/'                                                                      
[global] config path: 'sub/' -/-> '/usr/local/etc/mpv/sub/'                                                                   
[global] config path: 'audio/' -/-> '/home/nemo/.config/mpv/audio/'                                                           
[global] config path: 'audio/' -/-> '/home/nemo/.mpv/audio/'                                                                  
[global] config path: 'audio/' -/-> '/usr/local/etc/mpv/audio/'                                                               
[cplayer]  (+) Video --vid=1 (*) (h264)                                                                                       
[cplayer]  (+) Audio --aid=1 --alang=ita (*) (aac)
[display-tags] File tags:
[display-tags]  Title: 10153914932207610
[vo/opengl] Initializing OpenGL backend 'wayland'
wl_registry@2: error 0: invalid version for global wl_seat (11): have 2, wanted 4                                             
[vo/opengl/wayland] output received:
[vo/opengl/wayland]     vendor: (null)                                                                                        
[vo/opengl/wayland]     model: (null)                                                                                         
[vo/opengl/wayland]     w: 0, h: 0                                                                                            
[vo/opengl/wayland]     scale: 1                                                                                              
[vo/opengl/wayland]     Hz: 0.000000                                                                                          
[vo/opengl/wayland] EGL_VERSION=1.4 Android META-EGL                                                                          
[vo/opengl/wayland] EGL_VENDOR=Android                                                                                        
[vo/opengl/wayland] EGL_CLIENT_APIS=OpenGL_ES                                                                                 
[vo/opengl/wayland] Trying to create Desktop OpenGL context.                                                                  
[vo/opengl/wayland] Could not bind API!                                                                                       
[vo/opengl/wayland] Trying to create GLES 3.x context.                                                                        
[vo/opengl/wayland] Could not choose EGLConfig!                                                                               
[vo/opengl/wayland] Trying to create GLES 2.0 context.                                                                        
Segmentation fault

**Comment by lachs0r** [comment]
I’ve got that phone too. And even the tablet. Both fail because 1) I think there’s a problem with the wayland library version and 2) the Android graphics drivers that are used on those two devices are fucking GARBAGE (yes, proprietary Intel drivers on the tablet). Doesn’t even expose modern GLES.

Sorry, can’t fix this on our side.

**Comment by lachs0r** [comment]
In theory, there shouldn’t be a problem with mpv running on Sailfish, though. Can’t be helped with those drivers.

**Comment by paolomi** [comment]
many thanks for the explanation! :) :+1:   I'll wait a new device with open drivers! ;-)
