### ISSUE TITLE
Cross-compiling for Windows with shared libx264 fails

### ISSUE THREAD

**Issue by qyot27** [mpv-player/mpv#4052]
Having rebuilt my entire toolchain under GCC 6.3 and MinGW-w64 5.0.1, I wanted to experiment with having FFmpeg link to a shared libx264 so that I could swap between 8bit and 10bit versions of the lib at will.

When I try to build mpv against that FFmpeg, though, it fails at link time, complaining it can't find libx264:
```
[227/229] Linking build/mpv.com
[229/229] Linking build/mpv.exe
/usr/bin/../lib/gcc/i686-w64-mingw32/6.3.0/../../../../i686-w64-mingw32/bin/ld: cannot find -lx264
/usr/bin/../lib/gcc/i686-w64-mingw32/6.3.0/../../../../i686-w64-mingw32/bin/ld: cannot find -lx264
/usr/bin/../lib/gcc/i686-w64-mingw32/6.3.0/../../../../i686-w64-mingw32/bin/ld: cannot find -lx264
collect2: error: ld returned 1 exit status
```

It is there when pkg-config queries x264:
```
[mpv:$] PKG_CONFIG_PATH=/usr/i686-w64-mingw32/lib/pkgconfig pkg-config --cflags --libs x264
-I/usr/i686-w64-mingw32/include -L/usr/i686-w64-mingw32/lib -lx264  
[mpv:$] 
```

And it's included in the avcodec query:
```
[mpv:$] PKG_CONFIG_PATH=$HOME/ffmpeg_build/32bit/lib/pkgconfig pkg-config --cflags --libs libavcodec
-I/home/qyot27/ffmpeg_build/32bit/include -L/home/qyot27/ffmpeg_build/32bit/lib -lavcodec -lavicap32 -lstrmiids -lshlwapi -L/usr/i686-w64-mingw32/lib -lcdio_paranoia -lcdio_cdda -lcdio -lsecur32 -lSDL2main -lSDL2 -mwindows -Wl,--no-undefined -ldinput8 -ldxguid -ldxerr8 -lwinmm -limm32 -loleaut32 -lversion -luuid -static-libgcc -mconsole -lopengl32 -lOpenAL32 -lole32 -lzimg -lxvidcore -lxavs -lx265 -lx265_main10 -lx265_main12 -luser32 -lkernel32 -lmingw32 -lmoldname -lmingwex -lmsvcrt -lx264 -lwebpmux -lwebp -lwavpack -lvpx -lvorbisenc -lvorbis -lvo-amrwbenc -lvidstab -ltwolame -ltheoraenc -ltheoradec -logg -lspeex -lsnappy -lshine -lschroedinger-1.0 -lpthread -lorc-0.4 -lopus -lopenjp2 -DOPJ_STATIC -lopencore-amrwb -lopencore-amrnb -lnut -lmp3lame -lmodplug -lilbc -lgsm -lgme -lstdc++ -lcaca -lbluray -lxml2 -lgdi32 -lass -liconv -lfontconfig -lexpat -lfribidi -lfreetype -lpng16 -lgnutls -lws2_32 -lcrypt32 -lhogweed -lnettle -lgmp -llzma -lbz2 -lz -pthread -lpsapi -ladvapi32 -lshell32 -lswresample -lsoxr  -lavutil -lm  
[mpv:$] 
```

It's there in /usr/i686-w64-mingw32/lib as its shared form:
```
[mpv:$] ls /usr/i686-w64-mingw32/lib | grep x264
libx264.dll.a
[mpv:$] 
```

If I rerun the link command manually, removing all the references to -lx264 in the static portions and shift it to the end after -Bdynamic is used, *then* it links and the mpv.exe will complain if it can't find the x264 DLL...but after trying several other ways to make it recognize this when configuring waf, I'm at a loss.

Is this a problem with the wscript, with waf in general, with my compilation settings?  Shouldn't the build system detect that even if most of the other libs are static, that x264 is shared and should be linked that way?  Is it an issue with how FFmpeg writes its pkg-config files (since I'd assume if x264 was declared as -Wl,-Bdynamic -lx264 in libavcodec.pc, it'd work)?

**Comment by kwkam** [comment]
Just tried cross-compiling latest mpv with shared libraries under GCC 6.3.0/MinGW 6.3.0 and everything were built successfully. There were some issues but none of them is related to x264 or FFmpeg. One issue with waf is it cannot detect libraries which do not use pkgconfig (for example, iconv) and were installed in custom location (for example, `$HOME/build`), but it could be solved by
`DEST_OS=win32 TARGET=x86_64-w64-mingw32 LDFLAGS="-L$HOME/build/lib" ./waf configure ...`
or if you have set LIBRARY_PATH `LDFLAGS="-L$LIBRARY_PATH"`

**Comment by qyot27** [comment]
And how is that at all relevant to the issue here?  The problem has nothing to do with libs that don't use pkg-config, and x264 was installed to a system directory.

It has to do with the order of a mixture of static and shared libs (read: [all static except libx264, libaacs/libbdplus, and the usual dependencies on Win32 API libs](https://github.com/qyot27/mpv/blob/extra-new/DOCS/crosscompile-mingw-tedious.txt)) populated by pkg-config into the linker list and not putting shared libs under the -Bdynamic flag, *despite* pkg-config being correct when querying the libs.  Attempts to override LDFLAGS or LIBS do jack to solve that, because x264 is still being pumped into the linker list multiple times under the static portions and *that* is where it's causing a failure to link.

Not that it could continue to matter for the reason I was building libx264 as shared in the first place, since [this](https://github.com/kodabb/x264/commits/bitdepth) was posted to the x264-devel mailing list the morning I ran into this problem, but since this link order issue could potentially affect any shared lib, it's worth investigating regardless.
