### ISSUE TITLE
Use mpv for cutting up videos

### ISSUE THREAD

**Issue by phikal** [mpv-player/mpv#4054]
I wanted to suggest a feature, with which `mpv` could be used to cut videos up. 

Usually, I'd so it with `ffmepg`, like this [this](https://superuser.com/questions/138331/using-ffmpeg-to-cut-up-video):

    ffmpeg -i input.wmv -ss 00:00:30.0 -c copy -t 00:00:10.0 output.wmv

The problem is, that I always have to calculate how long the file would have to be (for `-t`), and since I already use `mpv` for finding out when to start and end the video, I thought one could add a feature, to do this automatically. 

I'd imagine, this could be done, by, e.g. pressing `a` to set the beginning of the video, and then `c` to cut from the point set with `a` until now. Then the video could be cut (which wouldn't take long, if one only copies) into a separate file, just like with screenshots. One could now debate, whether the point in time when `a` was set gets forgotten after cutting the video, or if it's remembered, what happens if `a` specifies a moment after `c`, etc.

(In case this feature already exists, I apologize for suggesting it, but I couldn't find anything about it in the official documentation)

**Comment by wiiaboo** [comment]
There's already a few user scripts to do that:
https://gist.github.com/Zehkul/25ea7ae77b30af959be0
https://github.com/lvml/mpv-plugin-excerpt
https://github.com/Kagami/mpv_slicing
https://github.com/wiiaboo/mpv-scripts/blob/master/excerpt.lua

**Comment by phikal** [comment]
Oh, my bad then.

**Comment by occivink** [comment]
Guess I'll also plug [my script](https://github.com/occivink/mpv-scripts#encodelua) which can also preserve some of the currently applied filters (crop in particular).

**Comment by Fullmetalchemist** [comment]
Thanks a lot for the scripts.
