### ISSUE TITLE
Subtitles are not loading

### ISSUE THREAD

**Issue by gericom-hummer** [mpv-player/mpv#4055]
Hi there, 
I wanna report a bug, that compiling mpv with all commits since 2017-01-20 /mpv git-73858bb0cc/, it is impossible to load subtitles. the last good version is the one with the commits up to 2017-01-19 /mpv git-8cbb2b5e9a/
System: Manjaro Linux and with Arch linux is the same
Here is the output from the terminal:
mpv ~/Downloads/SOME-MOVIE/MOVIE-TITLE.avi/mkv/mp4 
Playing: ~/Downloads/SOME-MOVIE/MOVIE-TITLE.avi/mkv/mp4 

 (+) Video --vid=1 (mpeg4)
 (+) Audio --aid=1 (ac3)
AO: [pulse] 48000Hz 5.1(side) 6ch float
VO: [opengl] 720x304 yuv420p
AV: 00:00:05 / 01:56:23 (0%) A-V:  0.000
[lavf] This syntax for the --sub-codepage option was deprecated and has been removed.
[lavf] Using subtitle charset: 
[ffmpeg] srt: Invalid UTF-8 in decoded subtitles text; maybe missing -sub_charenc option
[sub/ass] Error decoding subtitle
[ffmpeg] srt: Invalid UTF-8 in decoded subtitles text; maybe missing -sub_charenc option
[sub/ass] Error decoding subtitle
[ffmpeg] srt: Invalid UTF-8 in decoded subtitles text; maybe missing -sub_charenc option
[sub/ass] Error decoding subtitle

**Comment by gericom-hummer** [comment]
and this is the output with mpv git from 2017-01-19 /mpv git-8cbb2b5e9a/
mpv ~/Downloads/SOME-MOVIE/MOVIE-TITLE.avi/mkv/mp4
Playing: ~/Downloads/SOME-MOVIE/MOVIE-TITLE.avi/mkv/mp4
 (+) Video --vid=1 (mpeg4)
 (+) Audio --aid=1 (ac3)
AO: [pulse] 48000Hz 5.1(side) 6ch float
VO: [opengl] 720x304 yuv420p
AV: 00:00:03 / 01:56:23 (0%) A-V:  0.000
[lavf] This syntax for the --sub-codepage option is deprecated.
[lavf] Using subtitle charset: cp1251
Track added:
 (+) Video --vid=1 (mpeg4)
 (+) Audio --aid=1 (ac3)
 (+) Subs  --sid=1 'SOME-SUBTITLES.srt' (subrip) (external)
AV: 00:00:12 / 01:56:23 (0%) A-V:  0.000

**Comment by wiiaboo** [comment]
Did you try reading what was in the issue before you deleted everything? It asked for a log and sample.

**Comment by gericom-hummer** [comment]
I can't understand what you mean. I didn't delete anything.

**Comment by gericom-hummer** [comment]
This is the output from the terminal

**Comment by lachs0r** [comment]
You could try reading what the log output says and update your use of the [`--sub-codepage`](https://mpv.io/manual/master/#options-sub-codepage) option.

**Comment by gericom-hummer** [comment]
thanks @lachs0r , i have removed the sub-codepage=utf8:cp1251 from the conf file and now it is working perfect.
