### ISSUE TITLE
cue command case sensitivity

### ISSUE THREAD

**Issue by holomorph** [mpv-player/mpv#4057]
The CDRWIN manual states that cue commands (`PERFORMER`, `TITLE`, `FILE`, etc.) are case insensitive.  Other places like hydrogenaudio don't say anything about case.  I'm aware cue sheets are silly things, but I'm wondering if mpv would treat cue commands case insensitively--or if a patch to that effect is welcome--as I happened upon a cue file where the only "problem" was `Performer` instead of `PERFORMER`.

At first sight, it looks to me that only `bstr_startswith` → `bstr_case_startswith` in `demux/cue.c (read_cmd)` is needed.

**Comment by wm4** [comment]
Sample of such a file?

**Comment by holomorph** [comment]
Here you go https://0x0.st/OpK.cue
