### ISSUE TITLE
Saving default settings in OS X 

### ISSUE THREAD

**Issue by tooobe** [mpv-player/mpv#4061]
Any chance of changing default settings in mpv-player in OSX? (for example save settings/current media playtime on quit per default instead of SHIFT+Q, saving windows size & location, always on top etc)

**Comment by Cpuroast** [comment]
Feel free to add this to your input.conf to change it yourself.

q quit-watch-later

**Comment by tooobe** [comment]
I meant saving it as default settings so I don't have to press Q but can quit the application normally and still resume playback where I quit.

**Comment by Cpuroast** [comment]
Then add this to your mpv.conf:

save-position-on-quit=yes

**Comment by tooobe** [comment]
Great thank you will try. Any config command to make it always on top by default?

**Comment by Cpuroast** [comment]
All the options are documented in: 

https://mpv.io/manual/

**Comment by Cpuroast** [comment]
ontop=yes
:)

**Comment by tooobe** [comment]
Aha thanks got it, thought those were just the default mapped keys :)

**Comment by tooobe** [comment]
Got it working. Thanks a million. :)
