### ISSUE TITLE
Wayland: No Window Border

### ISSUE THREAD

**Issue by CurtisLeeBolin** [mpv-player/mpv#4062]
### mpv version and platform
mpv 0.23.0
gnome 3.22.2
wayland 1.12.0
Arch Linux

### Reproduction steps
Open mpv.desktop (mpv --player-operation-mode=pseudo-gui)
I also tried adding the `--border` argument.

### Expected behavior
I expected a window border.

### Actual behavior
No window border.

### Log file
http://sprunge.us/UfFa

**Comment by atomnuker** [comment]
Duplicate of #139.

**Comment by wm4** [comment]
I encourage reporting this as a bug to gnome instead.
