### ISSUE TITLE
loop pauses between runs

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [mpv-player/mpv#4066]
### Reproduction steps
mpv --loop=inf 1.mp4

### Expected behavior
Seamless playback : i.e first frame displayed after last frame (at same framerate).

### Actual behavior
There is about a 1sec pause before the first frame is shown again.

### Sample files
I can provide one if necessary

**Comment by wiiaboo** [comment]
With --loop you're looping the playlist. Use --loopfile.

**Comment by Matthias-Fauconneau** [comment]
Same issue with loop-file :
mpv --loop-file=inf 1.mp4

**Comment by wm4** [comment]
Amazing how you still manage to miss the point of the issue template.

**Comment by Matthias-Fauconneau** [comment]
Sorry, what are you missing ?

**Comment by garoto** [comment]
Version and Platform at the very least I presume.

**Comment by wiiaboo** [comment]
And a log and sample. No pauses here with loop-file.

**Comment by garoto** [comment]
Seamless here too as far as I can detect (Windows; lachs0r latest build)

**Comment by Matthias-Fauconneau** [comment]
Sorry, I assumed it would always happen.
mpv 0.23.0 on Linux/X.
[log.txt](https://github.com/mpv-player/mpv/files/730197/log.txt)

I synthesized some test files I can publicly share, and did some further testing.
They are encoded with libavformat/x265 RGB lossless.
A.mp4 is not seamless, it seems to vary a bit, might depend on the system load (currently high).
Also it is quite large.
https://www.dropbox.com/s/5dz2zpu1k2yzxjp/A.mp4?dl=0

B.mp4 is seamless, and much smaller, but still astonishingly large with respect to the clip complexity.
https://www.dropbox.com/s/rdqt32rcni3tgvm/B.mp4?dl=0

**Comment by paulguy** [comment]
I've looped GIFs in mpv before by specifying --vf on the command line to skip probing.  Although I guess the --vf behavior has changed so i dunno if it totally ends up skipping probing anymore.  Might be worth a try.  Any sort of hold up between starting a video and displaying the first frame will cause a pause so if you can determine where it's getting held up and seeing if you can reduce that like explicitly specifying format conversion or choosing a specific hwdec or disabling it altogether so it can skip that probing step can potentially reduce the time between opening a video and displaying the first frame.  There's also a demuxer precache option but i don't know if that's in release mpv yet.  That can probably help a bit.

**Comment by wm4** [comment]
Looks pretty seamless to me.

It says

> [cplayer] using demuxer frame duration for last frame

Which is about 63ms. It certainly shouldn't take 1 second.

Maybe make a log with --msg-time added, which could give us more information.
