### ISSUE TITLE
Hardware decoding using opengl-cb without copying back to system ram

### ISSUE THREAD

**Issue by evan-omnivor** [mpv-player/mpv#4068]
### mpv version and platform

git master on ubuntu 16.10

### Expected behavior

We want to be able to decode a video on the graphics card and then read the frames of that video through an OpenGL FBO without copying through system ram. opengl-cb seems to be a great solution, but cuda hardware decoding using the opengl-cb VO does not seem to be supported. Cuda-copy is supported, but this will copy the frames back to ram before being used as an FBO in opengl. Can you confirm that opengl-cb does not support hardware decoding without copying back to ram? If so, is this something that will be supported in the future?

**Comment by wm4** [comment]
You need to set the ``hwdec-preload`` option (renamed to ``opengl-hwdec-interop`` in git master). You could set it to ``auto``, but currently this will make it load vdpau support. So set it to ``cuda`` - it should work then (except with ANGLE on Windows).

**Comment by evan-omnivor** [comment]
Thanks!

**Comment by wm4** [comment]
Also you need ffmpeg git master for cuda + mpv git master. (The way cuda is used was changed in both ffmpeg and mpv, and the old methods are incompatible to the new ones on each side.)
