### ISSUE TITLE
Artifacts when playing HEVC 10 bit HDR with cuda-copy

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4074]
### mpv version and platform
```
[cplayer] mpv git-9c90c90 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri Jan 27 19:49:26 MSK 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.45.100
[cplayer]    libavcodec      57.75.100
[cplayer]    libavformat     57.65.100
[cplayer]    libswscale      4.3.101
[cplayer]    libavfilter     6.71.100
[cplayer]    libswresample   2.4.100
[cplayer] ffmpeg version: N-83258-gd1df72a
````

### Reproduction steps
Play _Exodus_ (or _Life of Pi_) HEVC 10-bit HDR sample with `vo=opengl hwdec=cuda-copy` (see more below)

### Expected behavior
No artefacts

### Actual behavior
Artefacts as on the screenshots. The artifacts occur at the same moments on every playback.

### Log file
Log file http://sprunge.us/IFcf
MPV settings http://sprunge.us/ShWM

### Sample files
_Exodus_ sample http://files.hdrsamples.com/downloads/hdr/Exodus_UHD_HDR_Exodus_draft.mp4
_Life of Pi_ http://files.hdrsamples.com/downloads/hdr/Life_of_%20Pi_draft_Ultra-HD_HDR.mp4
Screenshots 1) https://0x0.st/O7j.png 2) https://0x0.st/O7e.png 3) https://0x0.st/O72.png

Actually, in my system I have a 30-bit display (i.e. `Depth 30` in xorg.conf), and video goes to a FHD TV with tone-mapping, over active DP-HDMI converter, so it might be tricky to reproduce the issue... CPU G3900 can't play the sample without `hwdec`, and with `hwdec` its load about 20%+20%.
I didn't yet tested other decoders and outputs...
Personally I suspect that it might be a `display-resample` issue, or something is wrong with the samples themselves.

Regards,
Alex

PS. I understand that the issue looks somehow stupid, and doesn't much practical...

**Comment by haasn** [comment]
Both play fine for me with software decoding and display-resample, but I haven't tested 10-bit playback yet.

**Comment by fhlfibh** [comment]
@haasn Thanks for testing!

I tried with `display-sync=audio`, and with "normal" HDMI output (i.e. without DP converter) -- the artifacts still present in their previous places. Strange...

**Comment by wm4** [comment]
What about `hwdec=cuda`? Do these show up when doing a screenshot with `s` in mpv?

**Comment by fhlfibh** [comment]
@wm4 
There're same artifacts (i.e. at the same timings same places) with `hwdec=cuda` too, and with `display-desync` as well, regardless if i make screenshots or not.

**Comment by wm4** [comment]
I'd assume it's a driver bug, then.

**Comment by fhlfibh** [comment]
@wm4 quite may be. Unfortunately, I didn't notice anything strange in `dmesg`, and don't know how to make sure... Have to wait for a new nvidia's driver revision then.
