### ISSUE TITLE
Imply protocol in URLs

### ISSUE THREAD

**Issue by bobbybee** [mpv-player/mpv#4077]
I apologize if this is duplicate feature request.

When copying URLs from a search engine, frequently URLs omit the protocol, leading to typos of the form:

    $ mpv youtube.com/watch?v=xyz123

whereas mpv requires the more verbose, arguably more correct form:

    $ mpv https://youtube.com/watch?v=xyz123

Can these be simply aliased?

**Comment by wiiaboo** [comment]
What if there's a folder called `youtube.com` and you want to open file `watch?v=xuz123`?

**Comment by bobbybee** [comment]
Ah, right, I knew there must have been something I was missing :-)

Still, that seems like a corner-case. If it's feature creep, I understand, I'll hack around with bash a bit 'till I get something that works, hehe. Else, though, is there harm of introducing it as an opt-in configuration option?

**Comment by wiiaboo** [comment]
http/https links are already slow enough to open while youtube-dl tries to parse them. Removing the check for http/https/ytdl prefixes on ytdl_hook would slow down *every* load considerably just so people  not using those prefixes (you corner-case) can be satisfied.  Does that seem reasonable to you?

**Comment by bobbybee** [comment]
Fair enough. Thank you for your time :smile:

**Comment by wm4** [comment]
In theory you could put another hook in front of ytdl_hook.lua (or just edit that), which checks a whitelist of URLs or so.

But this is really just browser bullshit. There's no way to know whether a given name refers to a file, or a HTTP resource, or even something different like FTP. We can't do much about browsers being full of shit and making our lives harder.
