### ISSUE TITLE
Changing volume when speed is adjusted on --audio-pitch-correction=no resets the playback speed to normal

### ISSUE THREAD

**Issue by tyzoid** [mpv-player/mpv#4078]
### mpv version and platform

    $ mpv --version
    mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
     built on Sun Jan  8 00:53:48 CET 2017
    ffmpeg library versions:
       libavutil       55.34.100
       libavcodec      57.64.101
       libavformat     57.56.100
       libswscale      4.2.100
       libavfilter     6.65.100
       libswresample   2.3.100
    ffmpeg version: 3.2.2
    $ uname -a
    Linux Tyler-Arch 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

### Reproduction steps
 1. Play a song with mpv, using the audio-pitch-correction flag set to no
 2. Adjust the speed+pitch down by one click of the `[` key.
Adjust the speed+pitch, up or down, using the `[` or `]` keys, so that the song is playing at other than 1x speed/pitch.
 3. Adjust the volume down with the `9` key.
 4. Press the `[` key to lower the pitch again.

### Expected behavior
The volume of the song changes, but the pitch and speed adjustment stays the same.

### Actual behavior
The song reverts playback to 1x speed.  

Observations:
 * The software still keeps track of the prior speed adjustment, as .91x is still displayed after adjusting the volume
* Both `[` and `]` will cause this behavior
* Both `9` and `0` will cause this behaviour
* This behavior seems to be irrespective of audio format, I tested it on ogg vorbis, m4a, and mp3 files with the same result.
* This behavior seems to be irrespective of file length. This was tested on both 5min long songs, as well as one song over an hour in length, tested at the start and end of both songs.

### Log file
http://pastie.org/10993114
https://web.archive.org/web/20170127232526/http://pastie.org/pastes/10993114/text

**Comment by wm4** [comment]
Can't reproduce.

**Comment by lachs0r** [comment]
Me neither.
