### ISSUE TITLE
OSC playlist randomly changes size when clicking 'pl prev'/'pl next' buttons in OSC with '--force-window=yes'

### ISSUE THREAD

**Issue by Coacher** [mpv-player/mpv#4081]
Hello.

### mpv version and platform
Reproducible with mpv-0.2{1,2,3}.0 or mpv-git @ 9c90c902c11f557577f22e72a3a2db0034c511d8 on Gentoo amd64.

### Reproduction steps
1. Open playlist with several files and make sure the video window is opened.
2. Click 'pl prev'/'pl next' buttons in OSC in the video window.

### Expected behavior
Playback switches to the previous/next file and the displayed OSD has normal size.

### Actual behavior
Playback switches to the previous/next file and the displayed OSD changes size from normal to huge at random.

### Log file
mpv 0.23.0 logfile: http://sprunge.us/RiHS
mpv-git logile: http://sprunge.us/XKAZ
ffmpeg -f x11grab output: https://0x0.st/VoU.mp4

Please fix.

**Comment by Coacher** [comment]
Not reproducible when there is actual video.

**Comment by mc4man** [comment]
If scalefullscreen= & scaleforcedwindow= are the same value then you'd likely get consistent results, after that the results could be quite unexpected.
i'd think typically users would have scalefullscreen a lower value than scaleforcedwindow which produces poor results at times depending on values used.
The most unexpected is a high scalefullscreen  with a low scaleforcedwindow which makes the playlist smaller the higher scalefullscreen goes and or the lower scaleforcedwindow goes.

Can't see why for audio only thru the pseudo-gui  one would want to go fullscreen..

**Comment by Coacher** [comment]
@mc4man, this issue isn't about consistency, but about weird scaling glitches. See demo video in OP.

**Comment by mc4man** [comment]
As I said, (at least here), if those 2 scale values are equal or if 
scalefullscreen is higher than scaleforcedwindow than there aren't any 
'glitches', i.e. the behavior is consistent. Maybe different in your 
environment or you didn't try.

Is this useful behavior?, likely not.

**Comment by Coacher** [comment]
@mc4man, I misunderstood your first comment.
Indeed, if I set `scalewindowed`, `scalefullscreen`, `scaleforcedwindow` to 1, then these glitches no longer happen. Default values cause these glitches though.

It would be nice to have non-problematic default values or fix the underlying bug.
