### ISSUE TITLE
(libmpv) incorrect execution order of options in a mpv_command and a following mpv_set_property

### ISSUE THREAD

**Issue by gunnarmarten** [mpv-player/mpv#4089]
### mpv version and platform
mpv HEAD-c522d0d
ffmpeg 3.2.2
OSX 10.12.3

### Reproduction steps
I'm using libmpv with opengl-cb in my opengl application. I have a wrapper around the libmpv. A common use case is that a user opens a video file and then calls play.
I recently added an autoplay option which defaults to "no".

This results in this code which is executed subsequently:

open:
```
char autoplay_str[16];
snprintf(autoplay_str, 16, "pause=%s", autoplay == 0 ? "yes" : "no");
const char *cmd[] = {"loadfile", path, "replace", autoplay_str, NULL};
mpv_command(mpv, cmd);
```

play:
```
mpv_set_property_string(mpv, "pause", "no");
```

To reproduce:
Use the sdl example from https://github.com/mpv-player/mpv-examples.git

replace the loadfile command with: 

```
const char *cmd[] = {"loadfile", argv[1], "replace", "pause=yes", NULL};
mpv_command(mpv, cmd);
mpv_set_property_string(mpv, "pause", "no");
```

### Expected behavior

Video starts playing.

### Actual behavior

Video is paused.
If I use `mpv_command_async` and `mpv_set_property_async` the behavior is flaky, sometimes it plays the video sometimes it is paused.

### Log file

You can see, 'set property pause = false' is executed before setting option 'pause' = 'yes'
Log file was generated with msg-level="all=v" in the sdl client example:

http://sprunge.us/eWDD

### Sample files

any video file

**Comment by wm4** [comment]
"loadfile" is basically async - it directs playback to be stopped immediately, but it can take a while until it closes the current file and opens the next one. If you want to avoid this, you'll have to check for one of the events. (Per-file options are applied on loading.)

**Comment by gunnarmarten** [comment]
ok, thanks for the explanation, that makes sense.
