### ISSUE TITLE
With --hwdec= not specified cuda-copy is used over cuda

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#4091]
### mpv version and platform

git-e017c24 ubuntu 16.04

### Reproduction steps
play any cuda supported  video without specifying a hwdec=
### Expected behavior
use cuda
### Actual behavior
uses cuda-copy
### Log file
Log with --hwdec=
http://sprunge.us/FaTZ

Log with --hwdec=cuda for comparison
http://sprunge.us/hjjN

If this is a local issue then no matter, will close. Otherwise would be curious as to why it probes cuda & continues on to cuda-copy which is then used.

**Comment by wm4** [comment]
What it really should do is using vdpau. I suspect it doesn't because your ffmpeg is possibly not compiled with vdpau support.

**Comment by mc4man** [comment]
Well as mentioned quite some time ago, #3664,  the wscript check_statement for vdpau-hwaccel always fails here with a static ffmpeg. (- any launchpad mpv build using static ffmpeg shows the same fail.
 So in this case didn't edit wscript to allow/enable to see if just having cuda support was a suitable replacement.
(- cuda does work here quite well 
There is also a claim about mem leak here - #3931, I can't substantiate it though the times he said it *didn't* happen *may* have corresponded to the time or two I forgot to edit wscript. To that end I provided a build to check that though no response as of yet on that.
So if overriding the check_statement is a poor idea I'd rather not do such though in that case, (no vdpau-hwaccel) cuda over cuda-copy when appropriate would seem better.

**Comment by aufkrawall** [comment]
Did you try opengl-backend=x11 with vdpau? vdpau doesn't work here with x11egl while cuda does.
