### ISSUE TITLE
audio/audio.h: No such file or directory

### ISSUE THREAD

**Issue by ShalokShalom** [mpv-player/mpv#4094]
### mpv version and platform

0.23.0

### Reproduction steps

build bomi from here: https://github.com/d-s-x/bomi/tree/develop

### Expected behavior

build runs fine

### Actual behavior

audio/audiobuffer.hpp:5:25: fatal error: audio/audio.h: No such file or directory

(its my goal to bring Bomi in sync with the current mpv release, it use(d) a 2 year version)

**Comment by Kagami** [comment]
ping @d-s-x

**Comment by d-s-x** [comment]
> (its my goal to bring Bomi in sync with the current mpv release, it use(d) a 2 year version)

That's exactly what I'm currently working on (or at least I'm giving a try)
But I'm not managed to merge even mpv 0.10.0 yet (latest bomi is shipped with something in between 0.9.0 and 0.10.0)
Please be patient.

**Comment by ShalokShalom** [comment]
Of course, thanks a lot..
