### ISSUE TITLE
open previous playlist (files/url)

### ISSUE THREAD

**Issue by ww7** [mpv-player/mpv#4097]
it's good point to have ability resume previous playback. 
- command for scripting and key binding. 
- with option how much last session to store. 
- store not last played file, but playlist. 
- command just go back step by step in history and cycled.

**Comment by kevmitch** [comment]
Already [implemented](https://mpv.io/manual/stable/#command-interface-quit-watch-later). It should work for playlists. There is no concept of browsable "history" as there would be privacy concerns.

**Comment by ww7** [comment]
Save position on quit is not the same what suggested. 

Example: open mpv, then keypress "r" (reopen) - mpv open previous saved opened source. Keypress "r" once more - open second previous source. 

It's optionally, who need privacy, not enable this feature in config.

**Comment by sergeevabc** [comment]
Bedtime, I close MPC-HC, the next evening I open the player and just click “Play” to continue without recalling the exact location of a video file. Please, re-open the issue and implement such thing in MPV.
