### ISSUE TITLE
opening folder

### ISSUE THREAD

**Issue by ww7** [mpv-player/mpv#4098]
missing feature to open folder and optionnaly recursively

### mpv version and platform

mpv 0.23.0, macos, windows

### Reproduction steps

drag'n'drop folder to mpv icon and mpv window

### Expected behavior

open files from folder

### Actual behavior

not open

**Comment by kevmitch** [comment]
You need to fill out the issue template. There is not enough information here. This feature is already implemented except in Windows, which I assume is the OS you are reporting this for?

**Comment by Akemi** [comment]
works here as expected. please provide a log.

**Comment by Akemi** [comment]
since there is no reply i consider this solved.
