### ISSUE TITLE
Window Scale not working

### ISSUE THREAD

**Issue by AshtonCoop** [mpv-player/mpv#4104]
Using Mac OS Sierra. Open some mkv files and the window size is way much larger than screen size. The mkv files are originally videos shot by my iPhone and later I converted them into mkv.

added window-scale=0.5 in the conf file, not working.

I searched online for sometime, did not find the answers. Also searched in the forum, did not find answers. It seems that adding window-scale=0.5 should solve the problem.

Part of the configurations:

no-border                               # no window title bar
msg-module                              # prepend module name to log messages
msg-color                               # color log messages on terminal
term-osd-bar                            # display a progress bar on the terminal
use-filedir-conf                        # look for additional config files in the directory of the opened file
pause                                   # no autoplay
keep-open                               # keep the player open when a file's end is reached
#autofit-larger=100%x95%                 # resize window in case it's larger than W%xH% of the screen
deinterlace=auto                        # 'auto' does not imply interlacing-detection
cursor-autohide-fs-only                 # don't autohide the cursor in window mode, only fullscreen
input-media-keys=no                     # enable/disable OSX media keys
cursor-autohide=1000                    # autohide the curser after 1s
window-scale=0.5                        # scale window size

**Comment by wm4** [comment]
Why did you ignore the issue template?

**Comment by Akemi** [comment]
with that info i can't help you at least provide a log. i am also interested in screen resolution, HiDPI resolution and video resolution.

but if i had to guess it's probably `hidpi-window-scale=no` what you want. new MBPs have a res of 2880x1800, iPhones take video in up to 4k. on HiDPI resolutions they would be displayed in a 8k which is way more than the display resolution (and window-scale=0.5 won't help), even 4k is bigger than the display res.

**Comment by Argon-** [comment]
For me it sounds like AshtonCoop expects `window-scale` to be relative to his display. However, the appropriate option for that (`autofit-larger`) is deliberately commented out..

**Comment by Cpuroast** [comment]
Yup, something like: autofit-larger=75% is probably his best bet for huge videos.

**Comment by Akemi** [comment]
since no reply i consider this solved.
