### ISSUE TITLE
.cue unable to play filenames with certain characters

### ISSUE THREAD

**Issue by bitingsock** [mpv-player/mpv#4105]
### mpv version and platform

https://mpv.srsfckn.biz/mpv-x86_64-20161225.7z
Win10x64
### Reproduction steps
Have a file with such characters in it:
    à.flac
Make a .cue file next to it with, for example:
FILE "à.flac" FLAC
  TRACK 01 AUDIO
    ISRC FU:189800011
    INDEX 01 00:00:00

### Expected behavior
mpv plays the file indicated
### Actual behavior
[file] Cannot open file 'D:\New folder\à.flac': No such file or directory
### Log file
http://pastebin.com/fnF6Me8n

--
I should note that command prompt shows a strange character in place of the "à"
http://0x0.st/Wzg.png

**Comment by wm4** [comment]
The file is probably in a legacy codepage instead of UTF-8. mpv supports ASCII or UTF-8 .cue files only.

You should be able to work around this by either editing/converting the .cue file, or renaming the audio file to the .cue file (with different extension).

**Comment by bitingsock** [comment]
Changing the encoding fixed it.
