### ISSUE TITLE
Can't open MPV player.

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#4106]
### mpv version and platform
elementary OS
0.23.0-1~xenial
### Reproduction steps
open MPV player
### Expected behavior
it opens.
### Actual behavior
It won't open
### Error message
mpv: error while loading shared libraries: libass.so.5: cannot open shared object file: No such file or directory

**Comment by wiiaboo** [comment]
You either removed libass or forgot to recompile mpv after compiling a new libass.

**Comment by JulianLai** [comment]
You're right, it's djcj's problem.

**Comment by JulianLai** [comment]
Why does it say that some binary packages for this source are not yet published in the repository in the repository?

**Comment by thob** [comment]
@JulianLai could you resolve the issue?
