### ISSUE TITLE
High CPU/GPU load with 4K HDR mp4 and cuda-copy

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4109]
### mpv version and platform
```
[cplayer] mpv git-f1c9032 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Wed Feb  1 22:07:30 MSK 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.45.100
[cplayer]    libavcodec      57.75.100
[cplayer]    libavformat     57.65.100
[cplayer]    libswscale      4.3.101
[cplayer]    libavfilter     6.71.100
[cplayer]    libswresample   2.4.100
[cplayer] ffmpeg version: N-83258-gd1df72a
```
### Reproduction steps
Play the sample video with `hwdec=cuda-copy` and mpv settings mentioned in attach
### Expected behavior
Smooth playback
### Actual behavior
Framedrops, G3900 CPU load ~90%, GTX 1060 GPU load ~80%
### Log file
Log http://sprunge.us/GBbb
Settings http://sprunge.us/XEcO
### Sample files
Sample (450M) http://demo-uhd3d.com/files/uhd4k/LG_Colors-of-Journey-HDR.mp4 

There's less problem with `hwdec=cuda` -- CPU load ~20%, GPU load ~80%, not much framedrops.

Also it seems that there's no such problems with `.ts` files, both with `cuda` and `cuda-copy`(sample 1Gb http://demo-uhd3d.com/files/uhd4k/Samsung_HDR_Wonderland.ts).

It looks like CUDA have difficulty to decode `.mp4` format for some reason...

**Comment by lachs0r** [comment]
FWIW the high GPU load is caused by `cscale=ewa_lanczos`. You might want to turn that down a little using [auto-profiles.lua](https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua).

**Comment by fhlfibh** [comment]
@lachs0r Yes, `ewa_lanczos` is quite heavy.
But the problem is that I have the same `cscale=ewa_lanczos` with both `cuda`, and `cuda-copy`, and `mp4`, and `ts` -- and all four produce rather different load. 
With `cuda-copy`+`mp4` specifically the load is extremely high -- and I can't understand if it's normal or not...

**Comment by aufkrawall** [comment]
I can confirm with different videos that cuda-copy has a higher reported gpu load than cuda.

**Comment by philipl** [comment]
Why are you using cuda-copy - by definition it's doing extra work copying frames from the GPU to system memory and then back again. For 4K, frames are *big*, and you will take a measurable CPU hit doing those copies.

That's why interop is important and you shouldn't use cuda-copy unless you have to.

**Comment by aufkrawall** [comment]
I think some people prefer the -copy modes for VapourSynth or better deinterlacing.
If I recall it right, it doesn't really make a difference for performance whether you choose DXVA2 or DXVA2-copyback on Windows. So if copyback works well, it shouldn't be a problem (even not with just PCIe 2.0). However, cuda probably is a blackbox for developers.
On Windows, DXVA2 without copyback has worse quality with Nvidia drivers, btw.

**Comment by philipl** [comment]
The CPU difference between mp4 and ts might be due to differences in stream packing. ts will be annex-b and mp4 is whatever mp4 is. The hardware probably only accepts one and the cuvid parser probably has to do extra work to convert implicitly.

**Comment by philipl** [comment]
Oh, and your 'mp4' sample is actually a ts file with the wrong extension.

**Comment by fhlfibh** [comment]
@philipl 

> Why are you using cuda-copy
That's why interop is important and you shouldn't use cuda-copy unless you have to.

I use CUDA because my system has no other way to decode 10-bit HEVC. I use `-copy` because of reasons described here https://mpv.io/manual/stable/#options-hwdec 
Not sure what you mean by _interop_, sorry.
Of course, I can lower settings, and then it will play just fine probably. But I would like _not_ to lower settings...

"mp4" sample says in the log `[ffmpeg] AVBSFContext: The input looks like it is Annex B already`. "ts" sample says the same, as I remember, I can check it later. Also will check what if I simply rename "mp4" sample to "ts".

**Comment by philipl** [comment]
Yes. The fps is the reason for the difference. 4K frames  are big and 60fps means you are trying to push a lot of them. This is a significant CPU burden and your system simply can't handle the copying. You should use the 'cuda' hwdec and you'll have to live without whichever filters you're trying to use.

**Comment by fhlfibh** [comment]
@philipl ok, thanks. But I think I'd better upgrade my CPU, was thinking of that for some time, anyway. Just don't know yet if AVX support makes any difference for mpv/ffmpeg/etc. or not...

And might that issue https://github.com/mpv-player/mpv/issues/4074 be also related with CPU's weakness

**Comment by aufkrawall** [comment]
It's extremely unlikely that too slow CPU can lead to visual corruption.
The corruption in the linked ticket is likely related to HDR video or other colormatrix than BT.709, which could be a driver bug.

**Comment by philipl** [comment]
@fhlfibh: why are you using cuda-copy? Your settings and logs do not indicate you are trying to use any filters or that you are not using the opengl vo, and those are the only reason someone might want to use use cuda-copy.

**Comment by fhlfibh** [comment]
@philipl i'm using precisely vo=opengl

**Comment by philipl** [comment]
Like I said, there's no reason for you to use cuda-copy instead of cuda. All it's doing is increasing your CPU usage. There's no benefit.

**Comment by fhlfibh** [comment]
@philipl I use -copy simply because the man page says that it guarantees no quality loss compared to sw decoding. At the moment i'm not much interested in filters other than mentioned in my mpv config.

**Comment by philipl** [comment]
There is absolutely no quality difference between the two, and the man page does not claim there is.

**Comment by fhlfibh** [comment]
@philipl Better then, thanks.  I will try "cuda" no-copy tomorrow. The man page says not about "cuda-copy" specifically, it says about copy modes in general.

**Comment by fhlfibh** [comment]
Tried the "bad" sample with `hwdec=cuda`. Playback is (nealy) flawless, didn't notice any visual differences from `cuda-copy`, CPU load ~25%, GPU ~80% (though _stats.lua_ reports GTX 1060 GPU rendering seems to be on the edge even then).

I close this issue because it's definitely not an mpv's bug.
Thanks to all and **philipl** especially.

**Comment by aufkrawall** [comment]
I did some test under Windows and it definitely seems to to be normal that not just CPU load, but also GPU load increases with copyback modes.
