### ISSUE TITLE
sub-back-color padding/spacing support?

### ISSUE THREAD

**Issue by slashbeast** [mpv-player/mpv#4110]
I tried to search for such feature but it seems it's not implemented.

It would be cool to have a possibility to set some distance for sub-back-color, right now the background ends on the edge of the plaintext subtitles which does not looks too good. Kind of css's padding property for blocks thing would be great, or maybe there's something like that already and I just failed to find it in the manual?

**Comment by Argon-** [comment]
You should be able to do this with `sub-border-size`, right?

**Comment by slashbeast** [comment]
Not quite. if I go with for example sub-border-size=10, the background stays in place but the border of subtitles goes outside of the background

**Comment by ChrisK2** [comment]
This might have to be implemented in libass first.

**Comment by wm4** [comment]
A similar request is here https://github.com/libass/libass/issues/268#issuecomment-280921943

**Comment by slashbeast** [comment]
Even when running with `sub-ass=no`?

**Comment by ChrisK2** [comment]
All text rendering in mpv (including the OSD and OSC) are rendered using libass.

**Comment by wiiaboo** [comment]
Implemented in https://github.com/libass/libass/commit/a7807b03b0d1f25f448c14e88e0d8aa6ef4d0961.

Use [`--sub-shadow-offset`](https://mpv.io/manual/master/#options-sub-shadow-offset).
