### ISSUE TITLE
With CUDA hwdec mpv shows other video's frames

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4115]
### mpv version and platform
64-bit Linux with Nvidia's prop driver
```
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.45.100
   libavcodec      57.75.100
   libavformat     57.65.100
   libswscale      4.3.101
   libavfilter     6.71.100
   libswresample   2.4.100
ffmpeg version: N-83258-gd1df72a
```
### Reproduction steps
With mpv settings as below, play a clip (I used the Ugly one below, but it doesn't matter).
Then play the Bad clip.
Then play the Good clip.
Then play the Ugly clip again.
### Expected behavior
Normal playback
### Actual behavior
When playing the Bad after the Ugly -- first several seconds mpv shows corrupted frames from that _previous_ the Ugly clip -- screenshot https://0x0.st/WTJ.png
The same is with the Ugly played second time -- it will show frames from the Good.
And only the Good doesn't have such issue.
### Log file
Log file http://sprunge.us/eVjC
MPV settings http://sprunge.us/RfeR
### Sample files
The Good (1G) http://demo-uhd3d.com/files/uhd4k/Samsung_HDR_Wonderland.ts
The Bad (112M) https://0x0.st/WTy.mkv
The Ugly (325M) https://drive.google.com/open?id=0B8S2ER8znpF6RDZOUWFkdmpKU1k

This behavior seems to be specific for `hwdec=cuda` and these very the Bad and the Ugly clips (at least, I didn't find any other clips with such issue).
There's no such problem when using SW decoding.
Looks like something is wrong with those two clips' encoding, that triggers an issue mpv's CUDA decoder. But honestly, I have no idea...

Regards,
Alex

**Comment by haasn** [comment]
Is it specific to HEVC clips or have you been able to reproduce it with H.264 as well? Asking because I can't reproduce it on my end since I don't have a HEVC decoder in my GPU.

**Comment by fhlfibh** [comment]
@haasn Never seen such an issue with h.264 so far... But I don't use CUDA hwdec long enough yet. I came around these strange clips because I was interested in 4K HEVC with CUDA specifically (since there's no other way to get HEVC HW dec on Linux until recently, and none with Nvidia even now, afaik).

Shortly I will try more tests, with h.264.

**Comment by philipl** [comment]
So, what's happening here is primarily that the 'bad' sample is bad, as far as the hardware decoder is concerned. It seems to play back with the software decoder which probably implies this is some spec related thing where the hardware doesn't support it or interprets it in some way that's different from the encoder.

Anyway, that's got nothing to do with your recycled frames.

The nvidia GPU memory management, like most operating systems for system memory, does not clear out memory when it is freed, so if you allocate a buffer and don't initialize it to anything, you'll see what what there before. And that is what is happening here. You play one clip, so the frames are in the GPU's memory, and then you try to play the bad clip, which fails to actually decode any frames, to the playback buffers have whatever was in GPU memory before, which is probably the last video you played. If you try harder, you can probably get it to show you your desktop or images from the last game you played.

I can't tag or close tickets, but this is one is a hardware/driver limitation and nothing to do with mpv.

**Comment by fhlfibh** [comment]
@philipl thanks
I have some general idea about how memory allocation works.
But why it happens with some clips, and doesn't happen with others?
You said _the 'bad' sample is bad, as far as the hardware decoder is concerned_ and _then you try to play the bad clip, which fails to actually decode any frames_ -- so the question rather is what exactly is bad in those clips, and why hw decoder fails to decode their frames, and what where must be fixed.
I didn't mean it's an mpv's bug. But I run into it with mpv, so I started from here. Besides, I don't know where else I could file this issue... FFMPEG? Nvidia's devtalk?

**Comment by philipl** [comment]
The BAD clip starts playing normally at 10 seconds in, so presumably when the second GOP starts (I'm assuming you cut the clip on a keyframe here). So whatever the hardware is unhappy with is related to the first GOP and probably the first i frame specifically.

If you have access to windows, you should try playing it back through dxva - same hardware, different driver, and see if it does the same thing. You can even try cuda on windows, but I'd expect that to product identical results.

It's very unlikely to have anything to do with ffmpeg - we handle things very simply, using the cuvid parser and decoder together. I guess that means it could be a parser limitation, rather than anything to do with the hardware itself. But that's hard to prove - wiring the decoder into the general parsing infrastructure is a lot of tedious code to write.

Can try bringing it up on devtalk but I don't know how useful a response you'll get. For cuvid, it's mostly just me replying to questions

**Comment by fhlfibh** [comment]
@philipl I cut the Bad clip from the very beginning `ffmpeg -i input -to 00:00:XX -c:v copy -copyts output`. The Good and the Ugly are originals from the internets.
I have Win in VirtualBox only, will ask someone to test the clip for me on Win, but hardly with same hardware (i.e. GTX Pascal). From talks on forums I could understand that it plays Ok on Win with MadVR and on Nvidia Shield with Kodi.

**Comment by philipl** [comment]
For what it's worth, your trace shows that the parser is not stalling - it returns frames and we pass them to the decoder from the beginning, so the garbage frames are coming out of the decoder. Conceivably, that still doesn't exclude the parser as the source of the problems. It might be setting inaccurate frame metadata, resulting in the decoder producing garbage.

**Comment by philipl** [comment]
Oh, and finally, let's keep in mind that nvidia doesn't officially support 10bit decoding yet - I just happened to work out how to turn it on. This might be an example of why they don't think it's ready to go yet.

**Comment by fhlfibh** [comment]
Interesting, I thought it was Nvidia who added 10-bit support in their new SDK... But it feels they're not going to implement full support of "feature set F" (or how they call 4K HEVC 10/12-bit HW decoding) in any way any time soon. So your CUDA hack is the only way to have it on Nvidia under Linux, afaik (didn't try VAAPI with Intel's Kaby-Lake and AMD's Polaris AMDGPU Pro)

Anyway, at the moment my reasoning is that CUDA parser/decoder does can play at least _some_ 10-bit HEVC clips (visually) correctly -- e.g. the Good clip or the samples from this issue https://github.com/mpv-player/mpv/issues/4109 
So, even if it's not possible to change anything in parser/decoder -- it's possible (theoretically, at least) to re-encode a bad video so that the decoder will love it. Only the neccessary re-encoding parameters/settings are not clear to me now.
I will try ffmpeg with hw cuvid support shortly, maybe it will show anything interesting.

**Comment by wm4** [comment]
vaapi on kabylake should work, if you have bleeding edge versions of everything.

vdpau is looking dead.

**Comment by philipl** [comment]
@fhlfibh: nvidia have committed to official 10/12bit support in a future SDK release, so it's just that we aren't there yet.

* "HEVC/VP9 10/12 bit decoding SW support coming in Video Codec SDK 8.0"

**Comment by fhlfibh** [comment]
**philipl** Hmm, I thought we're with SDK 8 right now... On Nvidia's site it's available for download, and in my system I have `nvidia-cuda-sdk-8.0.44-r1` ready to install. Anyway, it's good if Nvidia will add 10/12-bit support officially at last.

I managed to re-encode the Bad clip somehow so that now it doesn't show garbage from the buffer anymore. Now it has only a couple of seconds of square artifacts in the beginning.
The offender seems to be the `repeat-headers` option of libx265 which the clip-maker used for encoding. I took ffmpeg's settings from mediainfo, changed `repeat-headers` to `no-repeat-headers` -- and playback became a little better.
But honestly, `no-repeat-headers` was rather an _un-educated guess_.  I'm not sure, that my re-encoding didn't degrade clip's quality (and HDR, and other stuff). Besides, some little visual artefacts still present...

**Comment by philipl** [comment]
Video SDK is separate: https://developer.nvidia.com/nvidia-video-codec-sdk

Currently 7.1

You certainly don't want to re-encode. Given that it's the first 10 seconds and just the producer logo, I'd just ignore it and play the file as it is.

**Comment by fhlfibh** [comment]
No, I certainly don't want to re-encode. But I'd like to know what is wrong there, especially because the issue seems to be not limited by the first 10 seconds and those two clips only.
But it's rather difficult to get somehow clear picture at the moment, as far as I understand... Maybe it's worth waiting for Nvidia's new SDK.
I close this issue for now.
Will add, if I find anything interesting.
Thanks!
