### ISSUE TITLE
the frequent use of fast-forward key will cause the keyboard failure

### ISSUE THREAD

**Issue by avalonzz** [mpv-player/mpv#4116]
### macOS 10.12.3

Full-screen mode, the frequent use of fast-forward key will cause the keyboard failure. The keys do not be responded, either Apple Internal Keyboard or Bluetooth Keyboard.

**Comment by truexfan81** [comment]
sounds like you are hitting the keys too hard  ijs

**Comment by Akemi** [comment]
you could at least fill out the issue template completely. 

does the keyboard fail system-wide or is mpv not responding to key presses? how can i reproduce this? are you repeatedly hitting an arrow key or are you just holding it?

as of now i can't reproduce this.
