### ISSUE TITLE
Customize saved properties for --resume-playback

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#4126]
# Problem
The `--resume-playback` feature is very useful for remembering your last position in a file, but I don't like that it remembers if you were in fullscreen or not. I always want my video files to start in a window. I've tried putting `fullscreen=no` in my `mpv.conf`, but it didn't fix it. I assume the resume config takes precedence.

Some way of ignoring properties or changing [the (currently hardcoded) list of properties that are saved to the resume config](https://github.com/mpv-player/mpv/blob/abbc8fc84a99a739e2566e4f7e022b3c1bdde1f3/player/configfiles.c#L216-L254) would solve my issue. 

# Possible solutions

The solution could be a negative setting that would ignore some properties when loading from a resume config: `mpv --resume-playback-properties-ignore=fullscreen`. This will require special parsing of the resume configs, instead of just the normal [`try_load_config`](https://github.com/mpv-player/mpv/blob/abbc8fc84a99a739e2566e4f7e022b3c1bdde1f3/player/configfiles.c#L84-L91).

Another solution is to create a `resume-playback-properties-save` property that allows you to fully customize the saved properties. I could then just use the default list, but with `fullscreen` removed: `mpv --resume-playback-properties-save=osd-level,speed,options/edition,pause,volume,mute,audio-delay,ontop,border,` ...etc. This is a bit unwieldy as there's ~30 properties saved by default. A significant downside with this approach is that older resume configs can still force fullscreen.

Maybe both solutions have their use? They could both be implemented. Either way, I'm also open to other ideas on how to solve this, or if I just missed an existing feature that could solve my problem.

**Comment by iamCristYe** [comment]
Agree. This should be working with --save-position-on-quit as well.

**Comment by iamCristYe** [comment]
Agree. This should be working with --save-position-on-quit as well.

**Comment by iamCristYe** [comment]
Agree. This should be working with `--save-position-on-quit `as well.
