### ISSUE TITLE
Does MPV support RTSP streaming?

### ISSUE THREAD

**Issue by huozhidiewu** [mpv-player/mpv#4127]
Does MPV play RTSP streams?

**Comment by CounterPillow** [comment]
[Apparently, yes](https://mpv.io/manual/master/#options-rtsp-transport)

**Comment by ChrisK2** [comment]
Apparently solved then.

**Comment by huozhidiewu** [comment]
But when I play RTSP stream, the following error message appears.
mpv rtsp://192.168.2.3:8554/1.h264                                      ✘
Playing: rtsp://192.168.2.3:8554/1.h264
[ffmpeg/demuxer] rtsp: method SETUP failed: 461 Client error
[lavf] avformat_open_input() failed
Failed to recognize file format.

**Comment by CounterPillow** [comment]
>[ffmpeg/demuxer] rtsp: method SETUP failed: 461 Client error

seems to be either an ffmpeg issue or a problem with your RTSP server. What version of ffmpeg are you using?

**Comment by huozhidiewu** [comment]
thanks for your reply!
this is ffmpeg version:
mpv -version
mpv 0.14.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.10-0ubuntu0.16.04.1

**Comment by CounterPillow** [comment]
>mpv 0.14.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects

outdated versions of mpv are not supported. If you have problems with Ubuntu's ancient mpv version, report it to Ubuntu.

**Comment by Classsic** [comment]
I think you have to install livemedia-utils (in debian), before install mpv, in this package you have openRtsp, require by mpv for read rtsp source.

**Comment by wiiaboo** [comment]
You're probably mistaking some other player with mpv. Neither FFmpeg nor mpv depend on external libs for rtsp, afaict.

**Comment by francisuk1989** [comment]
If you have Ubuntu or Ubuntu based distros you can add **one** of the following PPA
https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests
https://launchpad.net/%7Edjcj/+archive/ubuntu/vapoursynth

for FFMPEG v3 i use this PPA https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-3
at the time of posting this, i have the following

ffmpeg version 3.4.1-1~16.04.york0 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 20160609

**Comment by rubyFeedback** [comment]
Could the documentation show a clear example for how to get it to work? I am having difficulties with a C200 camera right now.

**Comment by mikerossiter** [comment]
> Could the documentation show a clear example for how to get it to work? I am having difficulties with a C200 camera right now.

I recently got mine to work with this command:
`mpv rtsp://<username>:<password>@<ip-address>:554/stream1`
The port 554 may need opening. This is mostly copied from the TP-link website so this won't work for other cameras necessarily. I didn't need to install any external libraries or anything. You may need to set the username and password in advanced settings on the Tapo app first. I assume this will be the case for other makes and models.
