### ISSUE TITLE
Resizing windowed instance without black bars

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#4128]
So sometimes I have an always-on-top windowed MPV instance running, just floating there while I do other things, and I find myself constantly resizing it so it adapts to the different windows I'm working with below it (so that MPV doesn't get in the way of a text and similar). When I do this, I see no use for having black bars on the sides and the top or bottom of the video. They're just a waste of space on windowed mode, unless maybe you want to activate subtitles and don't have enough space? But personally I'd rather have the subtitle floating over the video in such case. It's also annoying that every time I resize the window I gotta adjust it so there aren't any black bars around it, since they look bad and occupy screen space. So ideally there'd be an option on mpv.conf that'd make it so resizing the windowed window would only augment/decrease since in numbers relative to the aspect ratio of the video. I guess it'd be like how on Photoshop you can hold shift while resizing so that elements are resized respecting the height/width.

I know it's an odd request, but I believe it'd benefit everyone since I really see no point on having these black gaps on windowed mode.

**Comment by kevmitch** [comment]
This is already how it works by default? What window manager are you using?

**Comment by firewater2** [comment]
Oh my god, you're right. I use an AHK script that gives Linux-like movement/adjusting functions, so that I can drag any window by pressing ALT and left click, and I can resize them with ALT and right click. If I do this, it works as I described on my post. If I drag them by the borders of the windows, it works normally. However, I also run TrueTransparency, a program that changes the borders of windows, and if it's active (which it always is, since it's part of the custom skin I'm running) the dragging them by the border doesn't work.

So this should be closed then, though I'd appreciate if there was any way to "force" this behaviour no matter how I resize or if I use a program that skins with the borders.
