### ISSUE TITLE
Keyboard shortcut to shuffle

### ISSUE THREAD

**Issue by cossio** [mpv-player/mpv#4130]
Can we have a keyboard shortcut to shuffle the playlist (after mpv has started)?

Currently shuffling is only possible when mpv starts, through the argument `--shuffle`.

I think this is better than https://github.com/mpv-player/mpv/issues/803, which proposed that the shuffle be turned on or off. Instead, I propose to shuffle irreversibly.

**Comment by wm4** [comment]
There's a `playlist-shuffle` command, which you can map.

**Comment by cossio** [comment]
@wm4 how?

**Comment by AntonTell** [comment]
In `input.conf` add this line:

`KEY playlist-shuffle`

Change `KEY` to whatever key you to bind it to, like `k` or `alt+s`.

**Comment by cossio** [comment]
@AntonTell where is `input.conf` located?

**Comment by Flat** [comment]
https://mpv.io/manual/master/#files

**Comment by realyukii** [comment]
just wondering, is there a way to print a status through command (`) to determine if current mode is shuffle/random or sequential?

**Comment by zluo01** [comment]
> just wondering, is there a way to print a status through command (`) to determine if current mode is shuffle/random or sequential?

Hi wonder if you find a solution for your problem ?

**Comment by realyukii** [comment]
Hi @zluo01 

unfortunately, nope

**Comment by realyukii** [comment]
if I remember correctly, mpv on Windows, have shuffle icon that can tell you the state of shuffle, on linux, however, it get randomized each time you shuffle with `playlist-shuffle` instead of toggle the state
