### ISSUE TITLE
add property to retrieve FPS value just after the video decoder

### ISSUE THREAD

**Issue by chainikdn** [mpv-player/mpv#4133]
Right now all we have is:
- container-fps - "can easily contain bogus values", and yes, it's so for many video, e.g. anime
- estimated-vf-fps - "FPS of the video filter chain output"

Consider anime with variable FPS value and vapoursynth vf containing
`core.std.AssumeFPS(some-value)`

container-fps = [bogus-value]
estimated-vf-fps = [some-value]

There's no way now we could catch the moment of the actual video FPS change.

**Comment by Dudemanguy** [comment]
I'm not sure I really understand the request but you should be able to observe the `estimated-vf-fps` property for any changes and do whatever you want from there. Feel free to reopen if that does not fit your use case.
