### ISSUE TITLE
video-output-levels=limited dithers 10 bit to 8?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4138]
### mpv version and platform
64-bit Linux with Nvidia's prop driver
```
mpv git-6ac3d77 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Feb 11 15:38:46 MSK 2017
ffmpeg library versions:
   libavutil       55.46.100
   libavcodec      57.75.100
   libavformat     57.66.101
   libswscale      4.3.101
   libavfilter     6.73.100
   libswresample   2.4.100
ffmpeg version: N-83431-ga6cee50
```
### Reproduction steps
Play the sample file below, with `video-output-levels=limited` (my settings http://sprunge.us/NWBj).
### Expected behavior
Visible banding should be seen in "8-bit" square (screenshot https://0x0.st/4cv.png)
### Actual behavior
No banding, the squares are more or less equal.
### Sample files
S&M 10-bit Quantization test from http://www.avsforum.com/forum/139-display-calibration/2269338-10-bit-gradient-test-patterns.html

In my system I have a 30-bit Xorg and Nvidia's 1060 with DP connection, Nvidia driver's dithering is disabled. Color level is set to `Full` in driver, and `Limited` in TV (as per this FAQ http://kodi.wiki/view/Video_levels_and_color_space)
With mpv's `video-output-levels=limited` it shows no problem with black and white clipping (flashing bars), but doesn't pass the above S&M test (i.e. shows no banding for "8 bit").
With mpv's `video-output-levels=full` it has problem with b&w clipping, but passes the above S&M test.
With everything (driver, mpv, TV) set to `full` there's no problem with both clipping and the test.

Actually, all above might well be the result of my messing around color levels and has nothing to do with dithering, bits, etc...
But at the moment I suspect that `video-output-levels` does dither somehow.

Regards,
Alex

**Comment by wiiaboo** [comment]
Try `--deband=no`.

**Comment by fhlfibh** [comment]
@wiiaboo Can you please check what color levels you have set in driver, TV and mpv?

**Comment by wiiaboo** [comment]
I'm not using a TV and I don't set `video-output-levels`, so `auto`.

**Comment by haasn** [comment]
Remind me why you want banding?

**Comment by fhlfibh** [comment]
@wiiaboo `video-output-levels=auto` equals to `video-output-levels=full`, as the man page says. So it seems you basically have everything (i.e. mpv, gpu and monitor) set to `full`.
Yes, if I set my system in similar way -- I see banding too, just like you do.
The issue will be if you set your GPU to `full`, your monitor to `Limited` (if it supports this), and mpv to `limited` too.
Why this very set is required -- I took it from this FAQ http://kodi.wiki/view/Video_levels_and_color_space (but I don't know if its information is correct or not; some people here told me that it's "correct in general").

@haasn This S&M test is intended to test if a video setup correctly supports 10-bit output. If there's banding in "8-bit" square -- it means the setup can distinguish 8 bit from 10, and can output 8 as 8 and 10 as 10. If there's no banding -- it means the setup can't output 8 as 8 and 10 as 10. At least, this is how I understand it.

**Comment by wm4** [comment]
Depending on the mpv GL backend, you might have to specify the bit depth manually to get 10 bit output (and even then it's not guaranteed).

**Comment by fhlfibh** [comment]
@wm4 How can I specify that? Mine is `x11probe`, afaik.

**Comment by fhlfibh** [comment]
@haasn 
> Also, I would recommend setting the TV to full range RGB mode, and mpv to the same.

These settings corresponds to what that FAQ calls under 2.3-1 _Full,Full,Full -- Both Desktop & Video Content will look correct but video content is also scaled during the Y'CbCr --> RGB color space transformation. BtB & WtW are clipped so calibration will be more difficult_. Are they wrong there, or this _scaled during color space transformation_ simply doesn't matter in real life?

But yes, setting all to Full would solve this "banding" issue.

**Comment by haasn** [comment]
I don't know why you'd need out-of-range colors to be able to accurately calibrate a device? As far as I can tell, spec-conforming signals must be within this range one way or the other.

**Comment by fhlfibh** [comment]
I'm not talking about calibration, actually. What concerns me in the mentioned sentence is that with such settings _"video content"_ gets _"scaled"_ during _"color space transformation"_ (though I'm not sure what _"scaled"_ means in this particular case). However, with such "all full" settings I can't see anything visually strange on screen.

But again, what I'd like to find out in this issue is whether setting mpv's color level (i.e. `video-output-level=limited`) affects its output's color depth (i.e. dithers 10 to 8). Personally I see like it does -- and it shouldn't (but I might be quite wrong here, of course).

**Comment by haasn** [comment]
The color level has nothing to do with the color depth

**Comment by Hrxn** [comment]
To Color depth or to bit depth, that is the question...

**Comment by fhlfibh** [comment]
I tried to make some more tests, but still couldn't find what's wrong (or right). Actually, after my tests now I don't even understand if I really see 10 bits, leaving that mess of color levels alone...
Maybe later when such content and hardware becomes more common around, it all becomes more clear. For now I close this issue.
