### ISSUE TITLE
Start menu pops above full-screen player in multi-monitor setup when active on another screen

### ISSUE THREAD

**Issue by alystair** [mpv-player/mpv#4140]
### mpv version and platform
2017-02-12, Windows 7 64bit

### Reproduction steps

1. Open video, make full screen.
2. Click around on anything on another screen.

### Expected behavior
Start menu should remain hidden

### Actual behavior
Start menu pops above video

### Log file
Not applicable

### Sample files
Not applicable

**Comment by kevmitch** [comment]
Log file is applicable so we can know what opengl backend you're using. In any case, there have been a lot of changes on this front, so it would be interesting to know if this is reporducible in the new `gpu-api=d3d11`.

**Comment by alystair** [comment]
Still happening in latest Windows build. I've attached the [log.txt](https://github.com/mpv-player/mpv/files/1918314/log.txt) file. I've removed all instances of "[d][lavf] reading packet for sub" and subtitle bits since they are not relevant and flooded the log file.

**Comment by Dudemanguy** [comment]
Shouldn't happen if you use `--d3d11-exclusive-fs`.
