### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by Saphyel** [mpv-player/mpv#4145]
### mpv version and platform
Latest from the mpv-test repo for zesty?

### Reproduction steps
Use zesty version of ubuntu try to install using the repo 

### Expected behavior
Install mpv

### Actual behavior
Unmet dependencies, if this helps ubuntu zesty is using this one: http://packages.ubuntu.com/zesty/libx265-dev

### Log file
The following packages have unmet dependencies.
 mpv : Depends: libx265-95 (>= 2.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by lachs0r** [comment]
We are not responsible for broken distro repositories.
