### ISSUE TITLE
Persistent GUI Overlay When Playing on Second Display in Fullscreen

### ISSUE THREAD

**Issue by wynnsyt** [mpv-player/mpv#4147]
### mpv version and platform
mpv 0.24.0
macOS 10.12.3

### Reproduction steps
Using the default settings, enter fullscreen mode while playing, then click anywhere on another display.

### Expected behavior
Nothing should happen.

### Actual behavior
This spawns a persistent GUI overlay (progress bar, title, etc.) and it doesn't hide unless mpv regains focus.

**Comment by Akemi** [comment]
will be fixed with #4136. i still need to fix another bug though.

**Comment by wynnsyt** [comment]
Much appreciated.

**Comment by Akemi** [comment]
closed via https://github.com/mpv-player/mpv/commit/9ac05a575ce6cffa679c79b6539a798a2d41efde.
