### ISSUE TITLE
window-scale property not updated when switched to full screen

### ISSUE THREAD

**Issue by kraml** [mpv-player/mpv#4148]
### mpv version and platform
Windows x64 build by shinchiro, version 20170211

If you're not using git master or the latest release, update.

### Reproduction steps
1. Start MPV in normal window mode, get the window-scale property.
2. Press f to switch to full screen mode, get the window-scale property again.

### Expected behavior
In full screen mode, the window-scale property should be updated to reflect the window size, which happens to be the same size of the screen.

### Actual behavior
The window-scale property keeps the same as in normal window mode. It only changes when manually change the window size but not to full screen, such as dragging the window border.

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wm4** [comment]
window-scale is supposed to affect the windowed size only, so this is by design.

**Comment by kraml** [comment]
So is there anyway to get window size in full screen mode?

**Comment by wm4** [comment]
Probably not.

**Comment by wiiaboo** [comment]
You could use [osd-width/osd-height](https://mpv.io/manual/master/#command-interface-osd-height); just don't trust it too much(?)

**Comment by kraml** [comment]
Thank you! os-width/height works for me.
