### ISSUE TITLE
HLS doesn't work with basic auth

### ISSUE THREAD

**Issue by tapir** [mpv-player/mpv#4151]
### mpv version and platform
0.24.0-1 Arch 64bit

### Reproduction steps
Try to stream https://cosku:cb951303@fs.borealis.rocks/bbb.mp4/index.m3u8

### Expected behavior
Plays

### Actual behavior
Doesn't play

### Log file
No need for a log file. The issue is index.m3u8 contains URLs to other segment files but those segment files dont have the user:pass@ for basic auth to succeed so you get 401 unauthorized.

MX Player for android is the only player I could find that does this correctly. If the HLS url contains user and pass, it automatically adds it to segment URLS.

**Comment by ChrisK2** [comment]
Probably a ffmpeg issue?

**Comment by tapir** [comment]
Yeap ffmpeg issue
