### ISSUE TITLE
Allow chaining of --start, --end/--length to play multiple intervals

### ISSUE THREAD

**Issue by shmerl** [mpv-player/mpv#4153]
Is it possible to allow chaining playback control commands that change time position? For example let's say you have a 1 minute file. 

Doing something like: `mpv --start 00:15 --length 10 --start 00:30 --end 00:55 <file>` could play 2 intervals: [00:15 - 00:25] and [00:30 - 00:55].

Currently they don't chain, but last commands override all previous ones.

**Comment by ChrisK2** [comment]
Use [EDL](https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst).

**Comment by shmerl** [comment]
Thanks. This works (let's say the file is `audio.opus`)

    cat <( printf "# mpv EDL v0\naudio.opus,15,10\naudio.opus,30,25" ) | mpv -

But this doesn't:

   mpv <( printf "# mpv EDL v0\naudio.opus,15,10\naudio.opus,30,25" )

May be it's because pipes are handled differently?

**Comment by shmerl** [comment]
Hm, this works, but input is disabled, since it's reading from stidin:

    mpv - < <( printf "# mpv EDL v0\naudio.opus,15,10\naudio.opus,30,25" )

Adding --input-terminal doesn't override the disabling behavior:

    mpv --input-terminal - < <( printf "# mpv EDL v0\naudio.opus,15,10\naudio.opus,30,25" )

Is that supposed to be so, or it's a bug?

**Comment by wiiaboo** [comment]
mpv "edl://audio.opus,15,10;audio.opus,30,25" works too.

**Comment by shmerl** [comment]
@wiiaboo: That worked perfectly, thanks!
