### ISSUE TITLE
User-agent is not set for all requests

### ISSUE THREAD

**Issue by jberkel** [mpv-player/mpv#4155]
### mpv version and platform

```
mpv 0.24.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
built on Sun Feb 12 01:43:25 GMT 2017
```

### Reproduction steps

```
$ mpv --user-agent 'Foo' --http-header-fields='Header: Value' http://foo.com/playlist.m3u8
```

(see log file header)

### Expected behavior

User agent is set for all requests

### Actual behavior

User-agent is set correctly in the first few requests, later ones use the default of "Lavf/57.56.101"

### Log file

https://gist.github.com/jberkel/e44b9e9d87199be935270023808b434b

Note [line 72](https://gist.github.com/jberkel/e44b9e9d87199be935270023808b434b#file-gistfile1-txt-L72):

```
[ffmpeg] User-Agent: Lavf/57.56.101
```

### Workaround

Explicitly specify user-agent field in headers:

```
--http-header-fields='User-Agent: Foo'
```

**Comment by wm4** [comment]
Use --user-agent?

**Comment by wm4** [comment]
Actually you do. I thought you were using --http-header-fields. No idea what that part in your post is about then.

**Comment by wm4** [comment]
Looks like this is with HLS, and the options are not passed down correctly. Since you cut the log, I can't tell which ffmpeg version you used either (and whether it's already fixed), so whatever.

**Comment by jberkel** [comment]
This was with ffmpeg 3.2.4.  I also tried the head version, same result.

```
mpv git-ea297c5 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Feb 16 10:41:03 CET 2017
ffmpeg library versions:
   libavutil       55.47.100
   libavcodec      57.80.100
   libavformat     57.66.102
   libswscale      4.3.101
   libavfilter     6.73.100
   libswresample   2.4.100
ffmpeg version: git-2017-02-16-ad1d0a1
```

Will see if I can report the bug over at the ffmpeg project then.

**Comment by wm4** [comment]
Looking at this further, I guess it's possible that the HLS demuxer doesn't care what we set on on the HTTP input, and wants the options "extra". Can you try this patch: http://sprunge.us/UHFP

**Comment by jberkel** [comment]
Same result w/ the patch. Here's a more complete log if it helps:
https://gist.github.com/jberkel/332f6d6ac66ebdac934880e38d6c9e83

**Comment by wm4** [comment]
Yeah, then seems like libavformat is just ignoring these options. There'd be more confidence in this if there were an open call that succeeds, because then we'd know whether the provided options were actually consumed.

The patch I've mentioned might be required anyway.

**Comment by jberkel** [comment]
@wm4 I debugged this a bit further and it seems to be an issue of using `user-agent` and `user_agent`:

https://github.com/mpv-player/mpv/blob/master/stream/stream_lavf.c#L205
https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/hls.c#L1626

The ffmpeg code does not find the correct value and just uses the default user agent. Not sure where the right place to fix this is.

**Comment by wm4** [comment]
Apparently user-agent is deprecated and one should use user_agent. Does it work if you change that in mpv?

**Comment by jberkel** [comment]
I tried two things:
* changed `stream_lavf.c` to
```c
av_dict_set(dict, "user-agent", opts->useragent, 0);
```
* changed `hls.c` to
```c
update_options(&c->user_agent, "user_agent", u);
```

both worked. that's what I meant with "not sure where to fix this". if `user-agent` is deprecated then the fix would have to be in `hls.c`, no?

**Comment by wm4** [comment]
Yes. Technically, both stream_lavf.c and hls.c need to be changed.

**Comment by wm4** [comment]
Sorry, I must be blind. stream_lavf.c uses the correct value, so only hls.c needs to be changed.

**Comment by jberkel** [comment]
follow-up: http://ffmpeg.org/pipermail/ffmpeg-devel/2017-February/207296.html

**Comment by wm4** [comment]
Thanks. Is the mpv patch I posted needed?

**Comment by jberkel** [comment]
No, it's not needed.
