### ISSUE TITLE
mpv always spawns on workspace 4

### ISSUE THREAD

**Issue by mankoell** [mpv-player/mpv#4156]
### mpv version and platform

```
mpv 0.14.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.31.100
   libavcodec      56.60.100
   libavformat     56.40.101
   libswscale      3.1.101
   libavfilter     5.40.101
   libswresample   1.2.101
ffmpeg version: 2.8.11-0ubuntu0.16.04.1
```

### Reproduction steps

Using Xfce with 4 workspaces, open any video file with mpv and my config:

```
save-position-on-quit=yes
on-all-workspaces=yes
geometry=25%-25-45
vo=opengl-hq
ontop=yes
border=no
```

### Expected behavior

Open on the same workspace I'm currently at but also show it on all workspaces as I set `on-all-workspaces=yes` in my config above.

### Actual behavior

mpv will always spawn on workspace 4, no matter where I am

### Log file

http://paste.ubuntu.com/24006281/

**Comment by wm4** [comment]
>mpv 0.14.0

Update and retry.

**Comment by mankoell** [comment]
Still the same issue
```
mpv git-ea297c5 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed Feb 15 22:51:26 UTC 2017
ffmpeg library versions:
   libavutil       55.47.100
   libavcodec      57.80.100
   libavformat     57.66.102
   libswscale      4.3.101
   libavfilter     6.73.100
   libswresample   2.4.100
ffmpeg version: git-2017-02-15-ee4aa38
```

**Comment by v1kn** [comment]
@wm4 
Can we reopen this issue as it still persists?
Or should I open a new one?
Regardless of the distro, and with the newest mpv 0.25.
Also the title should be ranamed to : spawns on the last workspace.

**Comment by wm4** [comment]
Sure, make a new one.
