### ISSUE TITLE
Broken output for some H.265 video on hardware decoding

### ISSUE THREAD

**Issue by medhefgo** [mpv-player/mpv#4160]
Some H.265 encoded files are rendered wrongly when using hardware decoding.

Test file: https://0x0.st/4yX.mkv

Playing this file using this command
`mpv --no-config --keep-open=yes --hwdec=auto test.mkv`
it is rendered like this: https://0x0.st/4yc.png
Without hwdec, it is rendered like this: https://0x0.st/4ya.jpg

Running on up-to-date Arch Linux using proprietary NVidia drivers on a GTX 960.
mpv -v:
`mpv 0.24.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 12 12:54:08 CET 2017
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4`

If I play this file using vlc, I get this error; falling back to software rendering:
[00007f7e580eb2d8] vdpau_avcodec generic error: unsupported codec 1211250229 or profile 1

**Comment by wm4** [comment]
It's a well-known driver bug, and nvidia is unlikely to fix it. We should probably blacklist hevc with vdpau.

**Comment by medhefgo** [comment]
Does vlc just blacklist this or is mpv ignoring some error that signals it's unsupported?

**Comment by wm4** [comment]
I haven't checked, but I guess vlc just doesn't have it on a whitelist or something? It's unlikely that mpv ignores an error of any kind, because most or all of the codec handling is in ffmpeg these days.

You could try ``--hwdec=cuda``.

**Comment by medhefgo** [comment]
If I use cuda or vdpau-copy it uses software decodig (according to hwdec-current property). vdpau-copy gives these errors:
```
[ffmpeg] AVHWFramesContext: The linesize 1920 cannot be represented as uint32
Could not copy back hardware decoded frame.
Error while decoding frame!
```

**Comment by fhlfibh** [comment]
@medhefgo I tested your sample with GTX 1060 and `hwdec=cuda` https://0x0.st/4yj.png
Don't know why 'cuda' doesn't work for you, maybe Arche's build doesn't have it, or it needs another ffmpeg's version, or something...
From my personal experience, many ffmpeg-made HEVC videos have issues with HW decoding.

**Comment by wm4** [comment]
That's a ffmpeg bug. Use a stable version (that means ffmpeg git master instead of a release).

**Comment by wm4** [comment]
Maybe the ffmpeg version is slightly too old to handle cuda, or the cuda libs are not installed (normally the driver is installed with them).

The "ffmpeg bug" referred to the vdpau-copy failure, btw.

**Comment by medhefgo** [comment]
Yes, it seems arch doesn't have a cuda enabled build. A custom build works fine with correct output, though. vdpau-copy works too now but renders incorrectly like vdpau.
