### ISSUE TITLE
pseudo-dash support fails: lavf not able to detect format (minor issue)

### ISSUE THREAD

**Issue by joke-junkie** [mpv-player/mpv#4162]
Latest git master built with libav-12 produces a following verbose output when playing some videos on youtube (I can test with more and provide if necessary):

`mpv ... -ytdl-format 137+140`

[demux] Trying demuxers for level=normal.
[cache] EOF reached.
[lavf] Found 'mp3' at score=1 size=16384.
[lavf] Found 'mp3' at score=1 size=32768.
[lavf] Found 'mp3' at score=1 size=65536.
[lavf] No format found, try lowering probescore or forcing the format.
[demux] Trying demuxers for level=unsafe.
[lavf] Found 'mp3' at score=1 size=16384.
[lavf] Found 'mp3' at score=1 size=32768.
[lavf] Found 'mp3' at score=1 size=65536.
[lavf] No format found, try lowering probescore or forcing the format.
[cache] Terminating cache...
[cache] Cache exiting...
[timeline] failed to load segment
[timeline] EOF reached.
[lavf] No format found, try lowering probescore or forcing the format.
[demux] Trying demuxers for level=unsafe.
[lavf] Found 'mp3' at score=1 size=4096.
[lavf] Found 'mp3' at score=1 size=8192.
[lavf] Found 'mp3' at score=1 size=16384.
[lavf] Found 'mp3' at score=1 size=32768.
[lavf] Found 'mp3' at score=1 size=65536.
[lavf] Found 'mp3' at score=1 size=262144.
[lavf] Found 'mp3' at score=1 size=524288.
[lavf] Found 'mp3' at score=1 size=1048576.
[lavf] No format found, try lowering probescore or forcing the format.
[cache] Terminating cache...
[cache] Cache exiting...
[timeline] failed to load segment
[timeline] EOF reached.

This can be solved (at least for me) by forcing lavf format, i.e `mpv ... --demuxer-lavf-format=mp4 -ytdl-format 137+140` works fine. Forcing mp4 always is not a good idea though.

What can be done about this? I would like mpv to automatically pickup the format and give it to libav if necessary.

**Comment by atomnuker** [comment]
> What can be done about this? I would like mpv to automatically pickup the format and give it to libav if necessary.

Yeah, don't use libav.

**Comment by wiiaboo** [comment]
Without the URL we can't test whether it works with FFmpeg. I doubt wm4 tested the feature with Libav and I didn't either, so it could be that.

You could check if youtube-dl works by itself by using the same format and `--prefer-avconv`. If it manages to merge the segments and formats fine, it's possible to make it work with Libav. If youtube-dl also fails, issue a bug in Libav's tracker.

**Comment by joke-junkie** [comment]
@wiiaboo 
OK, I will make a separate build with FFmpeg and check it later.
youtube-dl works fine, and it _works_ with Libav when you force the format, see above.
Thank you.

P.S: I'm kinda new to this. Isn't demuxer supposed to demux a multiplexed stream into separate streams? Why is it involved when we have 2 separate streams from youtube already?

**Comment by wiiaboo** [comment]
Depends on whether it's using DASH segments or not. Separate streams should work fine. The URL would be useful. Or a log file with -v, like the issue template asked for.

**Comment by joke-junkie** [comment]
@wiiaboo 
I was trying to find more such videos. Apparently they should be quite long and quite new to trigger the issue.

Here's one:
https://www.youtube.com/watch?v=tKimemoRseg

**Comment by wiiaboo** [comment]
Yeah, that one's using DASH segments and it works fine with FFmpeg.

**Comment by joke-junkie** [comment]
@wiiaboo 
OK, thank you.
I will close the issue now then.

**Comment by wiiaboo** [comment]
If you prefer using Libav for some reason, you can add `[protocol!=http_dash_segments]` at the end of your ytdl-format to blacklist them and fallback to single file formats. Ex: `--ytdl-format=(bestvideo+bestaudio)[protocol!=http_dash_segments]/best`

**Comment by joke-junkie** [comment]
@wiiaboo 
I just wonder what's so different about lavf of FFmpeg now.

**Comment by wiiaboo** [comment]
FFmpeg merges everything from Libav, but Libav very very rarely cherry-picks from FFmpeg, so feature-wise they're a world apart. For user-centric applications you're better off just using FFmpeg libs.
