### ISSUE TITLE
cycle_values for multiple screens?

### ISSUE THREAD

**Issue by manolouy** [mpv-player/mpv#4164]
Hi
mpv 0.24.0-git-0f1afc6ba
Win7 64bits

Is it possible to set in input.conf cycle_values to move between multiple screens? (one screen at a time, like a "cycle_values audio-device")
I have 2 screens: 1 HDMI, 2 DVI

I did not find the command in the mpv options and I do not know if this is possible
Thanks in advance

current input.conf:
A cycle_values audio-device wasapi/{ca77d963-48b3-4143-952f-e3a127da2ddb} wasapi/{ffb00174-8b00-4cf2-ad3d-b1ebf45cf0b8}

current mpv.conf:
--screen=1
--fs-screen=1
--fs
--audio-device=wasapi/{ca77d963-48b3-4143-952f-e3a127da2ddb}

**Comment by bitingsock** [comment]
Why not just use your os keybinds? In windows this is Win+Shift+Left or Right

**Comment by manolouy** [comment]
Then it is not possible with mpv command?

**Comment by Dudemanguy** [comment]
Ancient but `cycle-values` will work with screen and any other property. Now whether or not it actually does anything depends on the OS/windowing backend but that's a separate topic.
