### ISSUE TITLE
It possible to add black border to OSC?

### ISSUE THREAD

**Issue by ERYuyNIrbNKrsc** [mpv-player/mpv#4166]
It possible to add black border to OSC?

for example numbers on a progressbar.
![screenshot_170219_1549](https://cloud.githubusercontent.com/assets/20888468/23103142/bfc2f350-f6be-11e6-803a-8daa48b17b89.png)

**Comment by wiiaboo** [comment]
What do you mean? There's a border already in that screenshot.

**Comment by wiiaboo** [comment]
If you mean a border to the seekbar, no, the bottombar and topbar layouts don't have a border in the seekbar.

**Comment by ERYuyNIrbNKrsc** [comment]
"play" "skip back" "skip frwd" and the rest are just white.

if you set boxalpha=255
![screenshot_170219_1747](https://cloud.githubusercontent.com/assets/20888468/23103885/8e7a0a4c-f6cb-11e6-8358-7a4705ed671c.png)

On Screen Controller on light scenes almost not visible

osd possible to set "--osd-border-color=<color>"
for OSC can do the same?

**Comment by wiiaboo** [comment]
Don't set boxalpha to 255 then?

@ChrisK2 any opinion on adding further options for this?

**Comment by ChrisK2** [comment]
Against.

**Comment by wiiaboo** [comment]
Guess it's decided then, I'm also against.
