### ISSUE TITLE
Flickering black boxes while playing

### ISSUE THREAD

**Issue by sCreami** [mpv-player/mpv#4167]
### mpv version and platform
git master
macOS 10.12.3 with discrete GPU
### Reproduction steps
Everytime
### Expected behavior
Smooth rendering
### Actual behavior
Flickering black boxes
### Log file
[http://sprunge.us/cDQF](http://sprunge.us/cDQF)
### Explanation with an image
![untitled-1](https://cloud.githubusercontent.com/assets/1769603/23104411/b6ecdd72-f6cd-11e6-9008-8324c54f5c40.gif)

When another window fly over the video, it generates flickering black boxes. It also happens when resizing the window, going fullscreen include.
I guess I should cc @Akemi for this.

**Comment by Argon-** [comment]
Can you try `--opengl-pbo=no`?

**Comment by sCreami** [comment]
I tried and it didn't help.

**Comment by Argon-** [comment]
Just to be sure: my first answer was `--opengl-pbo=no` which was unfortunately wrong. I changed it to `--opengl-pbo` but you might have seen the old version.

I had the same problem, `--opengl-pbo` fixed it for me.

**Comment by sCreami** [comment]
Oh yes that fixed it! 💯💯💯
I saw your first message indeed. Thank you for sharing your knowledge.

**Comment by Akemi** [comment]
if you want to keep track of the issue you can watch issue #3746 which is related to #2392 and the double buffering issue.
