### ISSUE TITLE
Put --vd / --ad codecs selection features back

### ISSUE THREAD

**Issue by aworan** [mpv-player/mpv#4169]
Hi,
I need the vd option or maybe something like for my rapsberry pi.
The new kernel versions of rpi provide an experimental kms gl driver and a experimental **fake kms gl driver**.
The last one is very interresting because it provide opengl video output and access to vc4 to hardware video decoding.
So with version 0.23 of mpv I compile it with some tricks because maybe I am smart :)
./waf configure --prefix=/usr --disable-rpi
So I build mpv without rpi support because all I want is to use h264_mmal codec and opengl output.
So after I play my videos with mpv -vd=h264_mmal video.mkv and it work very well (both windowed or fullscreen mode) in 720p Videos and very few framedrops with 1080p on my raspberry pi 3.
So I need some option to set video decoder codec in next versions.
But maybe the best is if I have some option in configure to use h264_mmal codec instead of h264 (and the same for the another accelerated video codecs in rpi mpeg2, mpeg4, vc1).
What do you think about it ?
Thanks & congratulations for your work !

**Comment by ktb83** [comment]
I have to agree. I'm using Raspbian Stretch on a Raspberry Pi 3 B with the 4.9.20-v7+ kernel and the vc4-fkms-v3d overlay. 

It didn't seem necessary to use --disable-rpi when configuring mpv, but I did test it with and without Raspberry Pi support. After building FFmpeg with MMAL support (and not necessary, but OMX support too) and then building mpv, simply calling mpv with --vo=opengl --vd=h264_mmal works pretty well for me with version 0.23.0. CPU usage does appear to be improved when mpv is configured with --disable-rpi, but it seems to be even lower when it's configured without --disable-rpi (Raspberry Pi support is enabled, but I still used opengl video output).

This seems like the best current option for a video player with OSD controls when using the vc4-fkms-v3d overlay. I've been using mpv like this as an external player for Kodi 18 (generic "linux" build, not "rbpi" build). Thanks, mpv devs!

**Comment by wm4** [comment]
Normally you don't need to use --vd (not even for hw decoding), and normal use of --vd isn't deprecated.

So I don't see an issue here - closing.
