### ISSUE TITLE
mpv crashes when going fullscreen 64bits or 32bits on Windows 10 pro

### ISSUE THREAD

**Issue by zouhair** [mpv-player/mpv#4170]
### mpv version and platform

"mpv-x86_64-20170219-git-e69b69add" and "mpv-i686-20170219-git-e69b69add"

OS:   Windows 10 pro
CPU: AMD A10-4600M APU
GPU: AMD Radeon HD 7660G + HD 7700M Dual Graphics

### Reproduction steps

Going fullscreen by double clicking inside the window or by hitting F

### Expected behavior

It's expected to go fullscreen without crashing

The old version mpv-i686-20170205-git-50991fac8 works perfectly

### Actual behavior

Opens files with no problems and plays with no problems as long as it is not fullscreen.

The moment I hit F to go fullscreen the player crashes and gives a segfault error.

### Log file

http://sprunge.us/PTOf

### Sample files

Gdb session: http://sprunge.us/fSJU

**Comment by lachs0r** [comment]
Well, it looks like it’s crashing in driver code. Try with a different opengl backend (e.g. `--opengl-backend=dxinterop` or `--opengl-backend=win`). Most likely not our bug.

**Comment by zouhair** [comment]
Thanks a lot, --opengl-backend=win worked perfectly.

**Comment by rossy** [comment]
I've heard of ANGLE crashing in fullscreen on AMD drivers before, but I haven't had a chance to investigate it. Could you try the default backend with ``--angle-egl-windowing`` as well? Also, it would be great if you could post a log from the old (working) mpv version.

Also, do other programs work in fullscreen? The default Windows 10 Films & TV app, for example?

**Comment by wm4** [comment]
That's still a problem that probably deserves investigation. ANGLE should cause less problems than the `win` backend.

**Comment by zouhair** [comment]
Here is a output.txt from mpv-i686-20170205-git-50991fac8 which works perfectly: http://sprunge.us/JFEI

Hmm, weird tried gbd session with the good version and it crashes when going fullscreen, doesn't crash when run outside gdb though: http://sprunge.us/UKGh

All other players work perfectly but the one you specified that I never used.

"Movies & TV"actually plays the video but crashes when going fullscreen.

My GPU driver is version 15.301.1901.0 can't go any newer as my GPU count as legacy :(

**Comment by rossy** [comment]
Thanks for testing!

> "Movies & TV"actually plays the video but crashes when going fullscreen.

At least we're not alone. The Movies & TV app should use a similar method of presentation to mpv (flip-model present,) so it's interesting that it's affected too. If AMD won't fix this for "legacy" GPUs, I wonder if we should blacklist them from using flip-model present.

Also TIL the "Movies & TV" app has a different name in different regions (which is kind of confusing):

> Movies & TV (Canada and the US), or Films & TV (UK, Australia, and New Zealand)

**Comment by zouhair** [comment]
Thank you for helping and thanks all of you for the great work.

And I doubt AMD will ever fix it.

**Comment by wm4** [comment]
Seems unfortunate. Funny how AMD's drivers are shit even on Windows.

**Comment by shinchiro** [comment]
@zouhair I saw you set `opengl-dcomposition=no` in the 'working' build. Does it crashed in fullscreen when using `opengl-dcomposition=yes` in that build?

**Comment by zouhair** [comment]
No, I have a monitor plugged to my laptop and I use that secondary monitor as my main monitor,

When I go fullscreen on that monitor MPV crashes, if I switch the main monitor to the laptop one everything works great be it fullscreen on the laptop or the plugged monitor.

Here is my [issue](https://github.com/mpv-player/mpv/issues/3823).

**Comment by zouhair** [comment]
Holy moly now I have another strange bug.

Here goes: 

1st video file opens, I can go fullscreen and back, no problem.

2nd video file is opened in another instance, this second one play great until I go fullscreen, the sound keeps playing but the picture stay frozen and stay frozen until I ALt-Tab and close the 1st video. At which moment 2nd video start working properly.

Godamit

**Comment by 239** [comment]
On my W10-64 / Intel i3-2310M / Intel HD 3000 / AMD HD 6770M system I got this:

- **default conf**: crash when going fullscreen / smooth playback and almost no microstuttering
- **opengl-backend=win**: no crash / more microstuttering
- **opengl-backend=dxinterop**: BSOD (atikmdag.sys)
- **opengl-dcomposition=no/yes**: crash
- **opengl-es=no**: no crash / more microstuttering
- **angle-egl-windowing**: no crash / some microstuttering

So for me the last option would be the best workaround but I'll stay on the previous build (20161225) for now since it doesn't crash at all.
