### ISSUE TITLE
Override vobsub

### ISSUE THREAD

**Issue by akyag** [mpv-player/mpv#4171]
How to override style of vobsub that has been embedded in an mkv file? Following are my subtitle related settings from conf 

> sub-ass-style-override=strip
> no-embeddedfonts
> sub-font="Proxima Nova"
> sub-font-size=38
> sub-color="#FFFFFFFF"
> sub-border-color="#FF262626"
> sub-border-size=3.2
> sub-shadow-offset=1
> sub-shadow-color="#33000000"
> sub-spacing=0.5

I am using 

> Name        : mpv
> Arch        : x86_64
> Version     : 0.23.0
> Release     : 2.fc25

**Comment by lachs0r** [comment]
You can’t. These subtitles use pictures, not text.

**Comment by rofrol** [comment]
This may help if the subtitles are inside mkv, a not as pictures https://superuser.com/questions/766890/increasing-size-of-subtitle-that-s-softly-embedded-within-mkv
