### ISSUE TITLE
Override color on colored subtitles

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#4173]
Any way to do this on .srt subtitles? I know it's doable on ass ones, but my settings aren't working for this one. It changes the style, but the color persists.

On input.conf

`Ctrl+1 no-osd cycle_values sub-text-font "Helvetica" "Helvetica" "Helvetica" "Helvetica Bold"; no-osd cycle_values sub-text-border-size "1" "1" "0" "1"; no-osd cycle_values sub-text-color "#dadada" "#dadada" "#dadada" "#dadada"; no-osd cycle_values sub-shadow-color "0.0/0.0/0.0/0.0" "0.0/0.0/0.0/0.3" "0.0/0.0/0.0/1" "0.0/0.0/0.0/0.0" ; no-osd cycle_values sub-text-shadow-offset "0" "2" "3" "0"; no-osd cycle_values osd-font "Helvetica" "Helvetica" "Helvetica" "Helvetica Bold" ; no-osd cycle_values osd-color "#dadada" "#dadada" "#dadada" "#dadada"; no-osd cycle_values osd-shadow-color "0.0/0.0/0.0/0.0" "0.0/0.0/0.0/0.3" "0.0/0.0/0.0/1" "0.0/0.0/0.0/0.0" ; no-osd cycle_values osd-border-size "1" "1" "0" "1" ; no-osd cycle_values osd-shadow-offset "0" "2" "3" "0" ; no-osd cycle_values ass-style-override "force" "force" "force" "force"`

edit: hot damn, I got a .srt subtitle in fucking COMIC SANS now... someone save me from this

**Comment by Feuermurmel** [comment]
Have you tried setting `sub-ass-style-override` to `force`? Did the trick for me.

    sub-ass-style-override = force

**Comment by firewater2** [comment]
You know, I have `ass-style-override` on input.conf and mpv.conf, but not `sub-ass-style-verride`. I wonder why I took that part out... anyway, thanks for responding. I hope this fixes it, but much inconveniently for testing purposes, I didn't save any subtitle with this problem and haven't come across one in a while.

**Comment by madaramost** [comment]
you make a mistake at color code it should be : `sub-text-color="#dadada"` not `sub-text-color "#dadada` make sure you add = character

**Comment by anticitizen4** [comment]
@madaramost `--sub-text-*` got replaced with `--sub-*` and `--sub-ass-*`. It works though, for now.
[source](https://mpv.io/manual/master/#subtitles)

**Comment by Hrxn** [comment]
@firewater2 , others, if it works, please consider closing the issue.

**Comment by firewater2** [comment]
No idea if it works, I haven't come across one of these in a while. Closing it until it happens again though,
