### ISSUE TITLE
[Feature request] Cropped Screenshot

### ISSUE THREAD

**Issue by LeonCheung** [mpv-player/mpv#4179]
Hi devs, may I ask for a feature request on supporting pre-crop screenshots?

I asked this because sometimes I only want to capture a fixed area of the screen (such as hard-coded subs, on screen PPTs, etc), normally it appears I have to crop them later to make them ready to use. So I think it would be neat to crop it while the screenshot is being taken. Is it possible or better solution? Thanks a lot!

**Comment by LeonCheung** [comment]
Oh, PS, another little idea just sparking in my head. Is it also possible to make sequenced screenshots all by a single click or something? I mean, for example, for a  5 mins video, it will automatically take per screenshot, say, every 1 mins, so that we got totally got 5 images in a flash (with/without timestamps on), which can be used as previews for others.  FYI. Thanks. :)

**Comment by ChrisK2** [comment]
Out of scope for the mpv core, but you can probably write a script to do this, there are already various similar ones: https://github.com/mpv-player/mpv/wiki/User-Scripts
