### ISSUE TITLE
Italics and quotation marks in subtitles

### ISSUE THREAD

**Issue by copywrong** [mpv-player/mpv#4182]
Quotation marks in subtitles should appear italicized like all the other punctuation marks.

**Comment by wiiaboo** [comment]
Use a different font, then.

**Comment by copywrong** [comment]
Then why not change the default font to one that italicizes quotes automatically?

**Comment by lachs0r** [comment]
The default one is a non-specific “sans-serif,” which tells your system to pick one. I’m rather sure this is a problem with your subtitle files rather than the fonts. So fix those.

**Comment by copywrong** [comment]
@lachs0r after changing sub-font to arial, the quotes became italicized, so it's not a problem with my subs.

**Comment by wiiaboo** [comment]
That probably means the font your subtitles are using don't have quotes. Either way, it's a font problem, at most a libass issue.
