### ISSUE TITLE
Seek position flickers between keyframes when dragging OSC on short videos

### ISSUE THREAD

**Issue by jrodatus** [mpv-player/mpv#4183]
### mpv version and platform

mpv git master
macOS 10.11.6

### Reproduction steps

1. Open an mp4 video less than 10 minutes in length with HD dimensions.

2. Slowly drag the OSC seek bar between any 2 adjacent key frames.

### Expected behavior

When dragging the seek bar on short videos, the seek bar and video position should consistently display the key frame for the active GOP at the seeked time.

It should not flicker 'randomly' between adjacent keyframes.

### Actual behavior

The seek bar and video position oscillate between the previous and the next key frame (bounding the seeked time). This oscillation cycles for each 1-pixel cursor movement between the corresponding slider positions.

### Example demo

![osc_drag](https://cloud.githubusercontent.com/assets/13192123/23292127/7484c98e-fa2b-11e6-82e0-c1b9ac9e47b1.gif)

### Log file

http://sprunge.us/CcQY

### Why this is an issue (imo)

1. It's visually jarring, e.g. in a presentation or demo.

2) It's difficult for the user to stop at a specific keyframe, since every 1-pixel mouse movement jumps away from it. (The gif is slowed down, does not show how fast it occurs.)

### Sample file

https://0x0.st/JPP.mp4

### Edit

I'm guessing this might be an ffmpeg seek API issue, not mpv. Feel free to close if that's the case.

As a workaround I changed "keyframes" to "exact" at this line:
https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L1740

But that's not a solution, as it can make seeking slower / laggy.

**Comment by jrodatus** [comment]
I'm guessing this might be an ffmpeg seek API issue, not mpv. Feel free close if that's the case.

As a workaround I just changed "keyframes" to "exact" at this line:
https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L1740

But that's not a good solution, as it can make seeking slower / laggy.

**Comment by wiiaboo** [comment]
This is an "intended feature". Seeking with mouse dragging uses fast keyframe seeking, not hr-seek like single click seeks. You're not supposed to be using it for precise seeks.

**Comment by jrodatus** [comment]
Are you saying the flickering back and forth is intended?

I agree, it is an intended feature that mouse dragging should use fast keyframe seeking.

That is not an issue. That is a 100% intended feature.

The issue is that video position flickers rapidly between adjacent keyframes, for each 1 pixel moved by the mouse, so that the user _cannot_ seek to a keyframe without difficulty.

**"The position should consistently display the key frame for the active GOP at the seeked time."**

^^ The above statement is consistent with keyframe seeking. I see my edit may have confused the issue, sorry.

**Comment by wiiaboo** [comment]
It basically flickers between the closest keyframe from where your pointer is. If you're about in the middle between keyframes it'll flicker between one or the other.

**Comment by jrodatus** [comment]
"if you're about in the middle"

^ That's not quite accurate.
On Mac it's flickering for _every_ pixel across the _entire_ span of the 2 keyframe times.

The user should not have to play "catch-the-keyframe" with their mouse.

It is practically a **_random_** behavior, from the user's perspective.

Clear violation of the principle of least astonishment:
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

The behavior of least astonishment would be to seek to the keyframe for the current GOP - [group of pictures](https://en.wikipedia.org/wiki/Group_of_pictures)
...not jump/leap 'randomly' between keyframes.

_No other_ media player, that I've _ever_ used, has this unpredictable behavior. I'm not bashing mpv. I love mpv. That's why I'd like to find / work on a solution, and why I reported this.

Didn't expect pushback :p

**Comment by wiiaboo** [comment]
I agree it's buggy behavior, but you'd get the same if you spammed `seek 50%` too, I think. So, not really a bug in the OSC but in how mpv/ffmpeg deals with these kind of seeks being spammed. I can be wrong.

**Comment by jrodatus** [comment]
Thanks for the validation (I mean that sincerely).

Yes, spamming `seek 50 absolute-percent keyframes` does the same thing.

I'll look into this more and follow-up, nntr

**Comment by ChrisK2** [comment]
It is certainly ugly, but also only an issue with rather short files. The longer the file is the less noticeable it becomes.

**Comment by jrodatus** [comment]
@ChrisK2, some people like their cat videos.

This is seems to be fixed by exclusively using `SEEK_BACKWARD` for seek type `MPSEEK_FACTOR`.

i.e. change:
https://github.com/mpv-player/mpv/blob/master/demux/demux.c#L1448
to `demux_flags = SEEK_BACKWARD;`

This causes a %-seek "keyframes" to always seek to the keyframe _prior to the seek time_, i.e. to the keyframe for the active GOP. That is, imo, the expected behavior of a seek bar. It also eliminates the ugly oscillation.

This seems to work fine with "exact"/hrseek as well, since (if I'm reading it right) that just works by dropping frames forward.

An edge case is when a keyframes seek factor computes to _EXACTLY_ a keyframe PTS, in which case the previous keyframe will be seeked-to. I'm not sure if adding a minor forward offset to correct this would be considered a hack, or not. But considering that a %-seek is not _typically_ intended as an exact seek operation, this case could be overlooked imo.

I might be missing something here, as I'm not familiar with mpv source.

**Comment by jrodatus** [comment]
@ChrisK2 (and anyone else who got email) the source link I gave was wrong, fixed.

**Comment by wm4** [comment]
The line you pointed out is probably nonsense. Is the behavior fixed if you change it?

**Comment by jrodatus** [comment]
Yes, it is fixed if I change it! That's what I meant to say.

And I haven't observed any side-effects, besides the edge case I mentioned.

**Comment by jrodatus** [comment]
FYI, since the source file has changed, if you guys ever want to fix it, the source line is now 287.

i.e.:
https://github.com/mpv-player/mpv/blob/master/player/playloop.c#L287
should be `demux_flags = SEEK_BACKWARD;`

It'd be a shame if this is a won't-fix. Would it be bad etiquette for me to do a pull-request for this as an outsider?

**Comment by wiiaboo** [comment]
Go for it.
