### ISSUE TITLE
[Windows] Video filtering is failing for me with "hwdec=auto" & "opengl-backend=angle"

### ISSUE THREAD

**Issue by garoto** [mpv-player/mpv#4185]
### mpv version and platform
~~~
OS Name:                   Microsoft Windows Embedded 8.1 Industry Enterprise
OS Version:                6.3.9600 N/A Build 9600
~~~
~~~
mpv 0.24.0-git-0f1afc6ba (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 12 03:08:50 CET 2017
ffmpeg library versions:
   libavutil       55.46.100
   libavcodec      57.78.100
   libavformat     57.66.102
   libswscale      4.3.101
   libavfilter     6.73.100
   libswresample   2.4.100
ffmpeg version: N-83487-gfe6e9df054
~~~

nVidia 970 with drivers "372.70 - [ r372_69-2 ]"
### Reproduction steps
Play any video file with `hwdec=auto` and `opengl-backend=angle` and add a simple video filter like `--vf=mirror` or a lavfi one like `--vf=lavfi="vflip"`

### Expected behavior
Video filter is applied together with working HW decode.

### Actual behavior
Hardware decode will fail and fall back to software decoding.

### Log file
http://sprunge.us/hYgR

### Sample files
n/a
---

This new angle backend rossy cooked is awesome btw: GPU usage is excellent (as in minimal); perfectly smooth transitions when switching to FS and back; resizing a video window will no longer generate a "lag" with regards to the actual video frame; etc. It behaves exactly like `dxinterop` does, so yeah, major kudos!

**Comment by wiiaboo** [comment]
You can't use filtering  with --hwdec=auto, you need to use the *-copy ones (--hwdec=auto-copy).

**Comment by garoto** [comment]
Damn, was this the program behavior for all this time?

**Comment by wiiaboo** [comment]
Yes. Filters are run in the CPU. If you're not using the -copy modes the video is not copied from the GPU, so the CPU can't run filters on it.

**Comment by garoto** [comment]
No wonder I never noticed this behavior: was using `dxva2-copy` & `dxinterop` all this time till rossy dropped his new angle code and I decided to mess around. Should I close this then?

**Comment by wiiaboo** [comment]
Yes. It's right in the manual.

**Comment by garoto** [comment]
I feel kinda silly now, and I have two more potential "bugs" to report regarding the new `angle` backend; I guess I'll need to troubleshoot more and document shit from now on...
