### ISSUE TITLE
ALSA return code being incorrectly checked

### ISSUE THREAD

**Issue by dw-vsn** [mpv-player/mpv#4188]
### mpv version and platform

Git master HEAD 2b6ac866c066a5422dc641c2ba9aa3af495a45c7

### Reproduction steps

Code Review

### Expected behavior

Check the correct ALSA return value

### Actual behavior

Check the wrong ALSA return value

### Log file

In audio/out/ao_alsa.c starting on line 1123 there is this code:

```
        unsigned short revents;
        snd_pcm_poll_descriptors_revents(p->alsa, fds, num_fds, &revents);
        CHECK_ALSA_ERROR("cannot read poll events");
```

The results of `snd_pcm_poll_descriptors_revents` is not being stored in the `err` variable, so the macro is not checking the correct return value. I believe it should be:

```
        unsigned short revents;
        err = snd_pcm_poll_descriptors_revents(p->alsa, fds, num_fds, &revents);
        CHECK_ALSA_ERROR("cannot read poll events");
```

**Comment by wm4** [comment]
That's probably right.
