### ISSUE TITLE
ALSA endless looping on device error

### ISSUE THREAD

**Issue by dw-vsn** [mpv-player/mpv#4189]
### mpv version and platform

Git master HEAD 2b6ac86

### Reproduction steps

Play a video with audio track on a CherryTrail device using the latest Intel LPE driver. Turn off display with DPMS, turn back on with DPMS. MPV is hung.

I know this is bleeding edge code and unrealistic for you to reproduce, but I think it exercises a failure in the ALSA error handling code that can be reproduced artificially.

### Expected behavior

MPV either stops playing audio, or exists with an error.

### Actual behavior

MPV hangs in endless loop. In ALSA `audio_wait`, `snd_pcm_poll_descriptors_revents` returns 0xC for revents, which means `POLLERR` is set, so it returns -1, but `playthread` in audio/out/play.c, but doesn't stop audio playback, instead it keeps running the code in the section marked `Fallback to guessing.`

It is not a deadlock, `playthread` just keeps calling `audio_wait` endlessly.

### Log file

I have one with my own logging in it, but I doubt that is interesting. Let me know if you would like a -v -v -v one (but I don't think it has anything interesting regarding ALSA errors).

### Sample files

Every media file with audio and video seems to cause this issue on this particular platform.

Here is a quote from Takashi Iwai, the kernel developer working on this driver and ALSA:

> Yes, this is an unavoidable issue for LPE HDMI audio.
> The audio driver is notified from the graphics driver at each time the
> mode change or DPMS on/off, then it has to turn off the whole audio
> functionality.  The other HDMI audio systems like Intel Haswell or
> later has an individual audio codec and it "works" even without the
> graphics connection.  But LPE audio is accessing directly the graphics
> register, the behavior is different, more strict.
> 
> Currently the audio driver notifies the underrun when the monitor
> disconnection is notified (e.g. mode changes, DPMS off, monitor off,
> etc).  The sound server (e.g. PA) should notice it and switch to
> another sink appropriately.  It's an issue to be solved by the
> user-space side.

**Comment by wm4** [comment]
Does this branch help https://git.io/vyL1e ? If not, logfile please.

**Comment by dw-vsn** [comment]
Yes, it appears to. Audio is lost and does not come back when display is turned back on via DPMS, but that is fine, at least MPV does not hang.

Thanks for the quick response.

**Comment by wm4** [comment]
OK, pushed that to master. In theory you could write a Lua script to automatically change audio devices if the device comes back etc. (Well, actually you can't, because alsa has no hotplug, but you could do that on other systems.)

**Comment by wm4** [comment]
Had to modify the above change in bc04acf3a76eb579ad0012286ac3bfeadaa07cc0.
