### ISSUE TITLE
Terminal input is ignored when playing stdin

### ISSUE THREAD

**Issue by hxka** [mpv-player/mpv#4190]
### mpv version and platform

mpv git-6028244160 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon Feb 27 22:36:29 MSK 2017

Platform is Linux

### Reproduction steps

`mpv --vo=null - < some-streamable-file`

(--vo=null is to keep mpv from creating a window which would be able to receive input)

### Expected behavior

Controls (e.g. space, p, q, etc) work

### Actual behavior

Any input is ignored

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/804838/output.txt)

(I ran mpv, tried pressing some keys, closed it with ^C)

**Comment by CounterPillow** [comment]
If you use stdin to stream data into mpv, you obviously cannot use stdin to send keyboard input to mpv at the same time.

Either use the window, or have a look at the JSON IPC, if you need to read from stdin while also controlling the player somehow.

**Comment by ion1** [comment]
FWIW, `foo | less` has keyboard control. If stdout is a TTY (isatty(3)), I think it will be a read/write device.

**Comment by ChrisK2** [comment]
> Either use the window, or have a look at the JSON IPC, if you need to read from stdin while also controlling the player somehow.

Or use a FIFO to pipe the steam to mpv as "file".

**Comment by hxka** [comment]
> If you use stdin to stream data into mpv, you obviously cannot use stdin to send keyboard input to mpv at the same time.

The fact that mpv expects input from stdin instead of tty when being run from a terminal (what you seem to suggest is happening) is exactly the problem.

**Comment by hxka** [comment]
> Or use a FIFO to pipe the steam to mpv as "file".

There's a cleaner workaround which doesn't require creating temporary files.
`mpv /proc/self/fd/3 3<some-streamable-file`

Or, using pipes:

`some-command | mpv /proc/self/fd/3 3<&0 0</dev/tty`

That's still a pretty clumsy way of doing that. If I had to do that every time I wanted to pipe something to less, I'd `cut` my veins.

**Comment by ChrisK2** [comment]
Does ``--input-file=/dev/tty`` work? If so, just put it in your config and you should be good.

**Comment by wm4** [comment]
It probably won't read terminal input from this option.

**Comment by qmega** [comment]
zsh and I think bash will do the fd dance for you with `mpv <(some-command)`

**Comment by SirCmpwn** [comment]
By default it makes sense to open /dev/tty instead of expecting stdin to provide user input.
