### ISSUE TITLE
mpv fullscreen playback on Plasma 5 Wayland

### ISSUE THREAD

**Issue by miku84** [mpv-player/mpv#4191]
### mpv version and platform:  	
mpv: 1:0.24.0-1
Manjaro, KF 5.31, Plasma 5.9.2
vaapi+opengl

### Reproduction steps
Login to Plasma 5 Wayland
Open a video
Try to use fullscreen

### Expected behavior
Fullscreen is working correctly

### Actual behavior
Fullscreen is not working correctly

### Log file
I can provide when needed

**Comment by atomnuker** [comment]
>Actual behavior
>
>Fullscreen is not working correctly

Its probably a kwin bug. Works fine in Weston and Gnome. Though I'm surprised mpv doesn't crash under Kwin's horrid wayland support.

Anyway, provide actual information on how its broken and I might reopen this. Log file would be useful too.

**Comment by miku84** [comment]
[Uploading mpv.zip…]()

Attached screnshot & log generated with Smplayer/mpv output.

**Comment by JulianLai** [comment]
mpv doesn't work correctly under wayland in Gnome with --vo=wayland, and I can't close the window either.

**Comment by atomnuker** [comment]
Yes, vo_wayland is buggy and needs fixing. Use opengl with a wayland backend.
