### ISSUE TITLE
Cache does not fill up for some ytdl_hook streams

### ISSUE THREAD

**Issue by medhefgo** [mpv-player/mpv#4192]
Cache does not fill up for some ytdl_hook streams

For some streams the cache never fills beyond 10s, even though the network connection (and sever) would easily allow for the 75MB default cache size to fill up. This seems to be regardless of cache-size setting. Note that --cache-secs is honored and will fill the cache beyond the 10s, but the +MB part does not fill (except for a few KB).

Some sample streams:
http://roosterteeth.com/episode/rwby-volume-4-volume-4-episode-12-l0h5ds
https://www.zdf.de/politik/frontal-21/frontal-21-vom-14-februar-2017-100.html

It seems that this only happens for hls streams.

**Comment by wiiaboo** [comment]
Nothing to do with ytdl_hook, it's a limitation of FFmpeg's hls demuxer.

**Comment by medhefgo** [comment]
Well, that's obvious. Maybe mpv could try a workaround by increasing cache-secs accordingly when using hls?

**Comment by weedy** [comment]
This used to work though.

**Comment by CounterPillow** [comment]
the cleanest fix would be for someone to either fix FFmpeg's HLS implementation, or have mpv ship its own HLS implementation. The current FFmpeg HLS support is fairly wonky; one example of this is that it also opens a new HTTP connection for each segment, if I remember correctly.

@weedy you'll have to tell people with what FFmpeg version and mpv version it "used to work", otherwise people can't verify your claim.

**Comment by weedy** [comment]
I wonder if its just yt-dl. I don't think things have been broken since mid feb for me.
I'll try rolling back versions.

     Wed Jan 11 00:36:21 2017 >>> media-video/ffmpeg-3.2.2-r1
     Tue Feb 21 21:51:36 2017 >>> media-video/ffmpeg-3.2.4
     Sun Mar  5 06:54:33 2017 >>> media-video/ffmpeg-3.2.4

     Wed Jan 11 00:41:47 2017 >>> media-video/mpv-0.23.0
     Tue Feb 21 21:55:10 2017 >>> media-video/mpv-0.24.0
     Sun Mar  5 06:57:15 2017 >>> media-video/mpv-0.24.0

     Tue Feb 21 21:25:31 2017 >>> net-misc/youtube-dl-2017.02.17
     Tue Feb 28 22:48:57 2017 >>> net-misc/youtube-dl-2017.02.22
     Sun Mar  5 06:45:34 2017 >>> net-misc/youtube-dl-2017.03.02

**Comment by CounterPillow** [comment]
mpv only uses youtube-dl to get the URLs, all the downloading/HLS stuff is left up to FFmpeg. You should also try with --no-config to make sure no change in your configuration triggered this.

**Comment by wiiaboo** [comment]
This should be fixed with the recent demuxer-cache changes.
