### ISSUE TITLE
gnome-mpv has performance issues when using client-side decorations

### ISSUE THREAD

**Issue by rhendric** [mpv-player/mpv#4197]
Please see gnome-mpv/gnome-mpv#232, which has relevant steps to reproduce. gnome-mpv claims it's an mpv bug.

My versions:
```
mpv 0.24.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon Feb 27 23:54:54 EST 2017
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4

GNOME MPV 0.11
```

**Comment by wm4** [comment]
They use --wid, which probably causes all kinds of inefficiencies.

The only way out is probably using the opengl-cb API.

I first thought it was on wayland, but sounds like plain X11. Well, whatever, probably still bad, depending on compositor.

**Comment by rhendric** [comment]
The comments in opengl_cb.h are a little forbidding:
`Warning: this API is not stable yet.`
`In general, using the "wid" option is recommended over the OpenGL API, because it's simpler and more flexible on the mpv side.`
Is this outdated advice?

**Comment by wm4** [comment]
Yes, removing it.
