### ISSUE TITLE
Feature Request: ARM ppa

### ISSUE THREAD

**Issue by mgcrea** [mpv-player/mpv#4199]
I'm currently testing an RPI3 with 16.04 (mate flavor), would love to use an up-to-date mpv version but it looks like the most recent available is `v0.14.0`:

```bash
# apt-cache policy mpv
mpv:
  Installed: 0.14.0-1build1+rpi1~xenial1.3
  Candidate: 0.14.0-1build1+rpi1~xenial1.3
  Version table:
 *** 0.14.0-1build1+rpi1~xenial1.3 990
        990 http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu xenial/main armhf Packages
        100 /var/lib/dpkg/status
     0.14.0-1build1 500
        500 http://ports.ubuntu.com xenial/universe armhf Packages
```

I haven't found anything regarding ARM installation in the docs,

Any chance we have or could have an official ARM ppa (like mc3man)

**Comment by wm4** [comment]
We don't do official builds.

**Comment by CounterPillow** [comment]
As wm4 said, mpv doesn't have official builds. However, that doesn't stop you from building a fresh version yourself.

Try using [mpv-build](https://github.com/mpv-player/mpv-build) to compile an up-to-date mpv with an up-to-date ffmpeg.

Alternatively, use a rolling release distribution, such as [Arch Linux ARM](https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-3), which doesn't ship ancient buggy software under the guise of stability.
