### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by DmitryHetman** [mpv-player/mpv#4202]
It's not clear is opengl supported under wayland? Or only GLES2.

**Comment by CounterPillow** [comment]
I've just looked at [the code that I believe is the one that handles this](https://github.com/mpv-player/mpv/blob/061b752217d15d41496ca6e4777835fcd945e237/video/out/opengl/egl_helpers.c#L177), and it seems like it attempt to use desktop OpenGL at least.
