### ISSUE TITLE
[Question] Can 'scale' and/or 'cscale' have any effect on 'tscale'?

### ISSUE THREAD

**Issue by mpvian** [mpv-player/mpv#4206]
I'm asking because up until recently I was using the default of `opengl-hq (spline36)` & also the default for `interpolation (mitchell)`, but decided to try out `gaussian` for both `scale & cscale` since I read that it's the only scaler that doesn't cause any ringing artifacts by design.
Ever since doing so I have the impression that the picture became noticably clearer, even though `gaussian` should be worse at actually upscaling lower resolution videos.
Therefore my question if the clearer picture came to be because of the non-existent ringing and whether those ringing artifacts of all the other scalers are negativly affecting the `tscale` option?

For any explanation I would be most grateful!

**Comment by wm4** [comment]
No, the options do exactly what they're documented to do. Although they interact with each others of course, because they both affect the final image in some way.
