### ISSUE TITLE
incompatible bytecode error on lua script

### ISSUE THREAD

**Issue by WhidbeyFog** [mpv-player/mpv#4208]
### mpv version and platform
mpv v0.24.0+70-git-2b6ac866c  Windows

### Reproduction steps
Put linked lua file in mpv folder and run mpv.exe. Check log for error.

### Expected behavior
script works.

### Actual behavior
In log file: Lua error: ........FirstLuaScript-5-1.lua: cannot load incompatible bytecode

### Log file: zip includes problem compiled lua file.
https://drive.google.com/file/d/0B1ui2z3CBZ8RSHZxc3NiR19HVVk/view?usp=sharing

### Sample file is in the zip file.

I'm getting started on writing my first lua script for mpv. Getting incompatible bytecode error.
Script was compiled with lua 5.1.5.

**Comment by wiiaboo** [comment]
That doesn't look like a lua script.

**Comment by lachs0r** [comment]
Mine and shinchiro’s mpv builds use luajit rather than vanilla lua. Maybe that’s incompatible.

**Comment by WhidbeyFog** [comment]
This is where I got the lua compiler: luac5.1.exe.
https://sourceforge.net/projects/luabinaries/files/5.1.5/Tools%20Executables/
lua-5.1.5_Win32_bin.zip

**Comment by wiiaboo** [comment]
Why not just load the script instead of compiling it?

**Comment by WhidbeyFog** [comment]
An earlier post here stated that lua file needs to be compiled. Might have been bogus.
I'll do some experiments.

**Comment by WhidbeyFog** [comment]
Ran with the text file instead of the compiled file.
Can't load unknown script: C:\.......AppData\Roaming/mpv/scripts/FirstLua.lua.txt

Here's the text file - it's from the mpv docs. Do I need to put a header line at the top?
function on_pause_change(name, value)
    if value == true then
        mp.set_property("fullscreen", "yes")
    end
end
mp.observe_property("pause", "bool", on_pause_change)

**Comment by wiiaboo** [comment]
Remove the ".txt", it's just ".lua".

**Comment by WhidbeyFog** [comment]
Works now without the .txt.  No error and it goes full screen on pause like the code says.
Thanks guys!
