### ISSUE TITLE
opengl-cb doesn't respect --force-window

### ISSUE THREAD

**Issue by jdoe0** [mpv-player/mpv#4212]
When using opengl-cb, the VO doesn't get configured unless a file is playing and a video track is present. This makes it impossible to display OSD messages when idling or playing an audio file. `--force-window` solves this issue for other VOs, but has no effect with opengl-cb.

mpv git-2912210da

**Comment by wm4** [comment]
It's not handled in any different way...

**Comment by jdoe0** [comment]
I've created a test case for this. If you run the test case without a parameter, it will initialize mpv without loading a file. If you try pressing `O` or other keys that display OSD texts, you will find that nothing is shown in the window. If you run the test case again with a video file as a parameter and do the same thing, OSD texts will be displayed as usual.

[test.zip](https://github.com/mpv-player/mpv/files/830219/test.zip)

**Comment by wm4** [comment]
If I set terminal=yes, it says:
```[vo/opengl-cb] No context set.
Error opening/initializing the VO window.
```

**Comment by jdoe0** [comment]
I have revised the code to fix the error, and I'm now able to see OSD even without audio tracks, so the problem is actually in my code. Sorry about that.
