### ISSUE TITLE
Vapoursynth R36 and mpv-git on Win64 initializing fails

### ISSUE THREAD

**Issue by DeadSix27** [mpv-player/mpv#4214]
mpv version https://github.com/mpv-player/mpv/commit/076116a0e5f00232f1b8dad2ab76926667b63adf
xcompiled for win64

initializing SVP VS script fails with following log:
```
[   0.727][v][cplayer] Run command: vf, flags=0, args=[add, vapoursynth=[C:\Users\*\AppData\Roaming\SVP4\scripts\9970a63c.py]:4:17]
[   0.743][i][vf] Opening video filter: [vapoursynth file=C:\Users\*\AppData\Roaming\SVP4\scripts\9970a63c.py buffered-frames=4 concurrent-frames=17]
[   0.743][v][vapoursynth] Setting option 'file' = 'C:\Users\*\AppData\Roaming\SVP4\scripts\9970a63c.py' (flags = 0)
[   0.744][v][vapoursynth] Setting option 'buffered-frames' = '4' (flags = 0)
[   0.744][v][vapoursynth] Setting option 'concurrent-frames' = '17' (flags = 0)
[   0.752][f][vapoursynth] Could not initialize VapourSynth scripting.
[   0.752][e][vf] Creating filter 'vapoursynth' failed.
[   0.752][v][vf] Video filter chain:
[   0.752][v][vf]   [in] 1920x1080 nv12 bt.709/bt.709/bt.1886/limited CL=unknown
[   0.752][v][vf]   [out] 1920x1080 nv12 bt.709/bt.709/bt.1886/limited CL=unknown
```
It's compiled against python 3.5.3-amd64 and vapoursynth r36-amd64.

Configure line: `DEST_OS=win32 TARGET=x86_64-w64-mingw32 ./waf configure --enable-libarchive --enable-sdl2 --enable-libmpv-shared`

**Oddly enough using R35 dlls  and pyd on the same mpv binary works**. 
Is there a way I can further debug this and get more information than "Could not initialize VapourSynth scripting." ? Or does anyone have a clue?

**Comment by wm4** [comment]
This simply means calling `vsscript_init()` failed. This is the very first VS-specific call. Not anything we can do about it. I suspect your python install is broken. Does vspipe work?

You could try to use the mpv-specific Lua VS backend, although that's very primitive and was hacked together without regards to sanity.

**Comment by DeadSix27** [comment]
@wm4 not sure what caused it, I recompiled everything from scratch, double checked my python and vapoursynth deps and now it works.. (i used the exactly same procedure..) maybe I missed something:

anyway thanks for your time.

**Comment by wm4** [comment]
Here's how you'd manually debug this:
- find the vsscript_init() implementing (somewhere in vapoursynth)
- sprinkle printf calls over it
- find out where it exits with an error

Or report this on the VS bug tracker.

**Comment by DeadSix27** [comment]
@wm4 thanks again, If I encounter the issue again ill know where to debug at least.
