### ISSUE TITLE
No audio playback

### ISSUE THREAD

**Issue by naghus** [mpv-player/mpv#4216]
NOTE: after the first post was closed I tried updating mpv and nothing changed.

### mpv version and platform
mpv git-ea297c5 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed Feb 15 22:51:26 UTC 2017
ffmpeg library versions:
   libavutil       55.47.100
   libavcodec      57.80.100
   libavformat     57.66.102
   libswscale      4.3.101
   libavfilter     6.73.100
   libswresample   2.4.100
ffmpeg version: git-2017-02-15-ee4aa38

Ubuntu 16.04

### Reproduction steps
Try opening any video or audio file in any format.
(tested with .avi, .mkv, mp4 and .mp3)

### Expected behavior
I expect to hear something.

### Actual behavior
Neither videos files nor audio files reproduce any audio.
Every other source of audio (e.g. firefox) works.

### Log file

http://pastebin.com/SxAv6P9v

**Comment by wm4** [comment]
Unmute the video.

**Comment by naghus** [comment]
The video isn't muted

**Comment by CounterPillow** [comment]
Is the playback happening on the right pulseaudio device? Check e.g. in `pavucontrol`.

**Comment by naghus** [comment]
Using pavucontrol, it seems that mpv redirects the audio to the hdmi port, altough it's disconnected.
I'll try attaching my laptop to the tv and then remove the connection.

**Comment by CounterPillow** [comment]
You should be able to just set it to play back on your main audio output, and it will stick. I believe which output device an application chooses is set my pulseaudio itself.

**Comment by naghus** [comment]
I wasn't able to redirect the audio to the main output, but connecting the latop to the tv and disconnecting worked for me. Thank you for your help.

**Comment by CounterPillow** [comment]
If you click on the device listed next to the application in the Playback tab of pavucontrol, you should get a drop-down showing you the available audio devices, for a laptop usually a built-in analog one and HDMI. Clicking on one will switch the application over to using that output device. I believe Ubuntu also has its own little UI thing for switching all playback streams to one device or another.

**Comment by wm4** [comment]
```
<CounterPillow> I guess that issue can be closed then.
```
k

**Comment by ManUsia5** [comment]
> Unmute the video.

Thank you :u
