### ISSUE TITLE
Mpv Build (Powerpc / Debian Wheezy) - video output blurry

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#4217]
### mpv version and platform

MPV Build - Powermac G5 - Debian Wheezy (Powerpc)

If you're not using git master or the latest release, update.

### Reproduction steps

MPV Build

sudo aptitude install autoconf  automake  libasound2-dev libegl1-mesa-dev  libfontconfig-dev  libfreetype6-dev  libfribidi-dev libgl1-mesa-dev libgnutls-dev libtool libx11-dev libxext-dev libxinerama-dev libxrandr-dev  libxv-dev  pkg-config python  x11proto-core-dev yasm
./update
./clean
cd libass
git checkout 9a2b38e8f5957418362e86b525f72794565deedd
cd ..
./build -

### Actual behavior

when i play video , the video frame is with lines, like blurred out.

The Graphic card should be capable (GTX7800 256 MB), also i have installed a kernel with 3D accelleration 
i hope it be active

OpenGL renderer string: Gallium 0.4 on NV47

### Log file

make: Leaving directory `/home/rich/Programme/mpv-build/ffmpeg_build'
Using mpv options:
Setting top to                           : /home/rich/Programme/mpv-build/mpv 
Setting out to                           : /home/rich/Programme/mpv-build/mpv/build 
Checking for waf version in 1.8.4-2.0.0  : ok 
Checking for program 'cc'                : /usr/bin/cc 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for program 'ar'                : /usr/bin/ar 
Checking for program 'rst2html'          : not found 
Checking for program 'rst2man'           : not found 
Checking for program 'rst2pdf'           : not found 
Checking for program 'windres'           : not found 
Checking for program 'perl'              : /usr/bin/perl 
Checking for 'gcc' (C compiler)          : /usr/bin/cc 
Detected target OS:                      : os-linux 
Checking for compiler flags -Werror=implicit-function-declaration : yes 
Checking for compiler flags -Wno-error=deprecated-declarations    : yes 
Checking for compiler flags -Wno-error=unused-function            : yes 
Checking for compiler flags -Wempty-body                          : yes 
Checking for compiler flags -Wdisabled-optimization               : yes 
Checking for compiler flags -Wstrict-prototypes                   : yes 
Checking for compiler flags -Wno-format-zero-length               : yes 
Checking for compiler flags -Werror=format-security               : yes 
Checking for compiler flags -Wno-redundant-decls                  : yes 
Checking for mpv CLI player                                       : yes 
Checking for shared library                                       : disabled 
Checking for static library                                       : disabled 
Checking for static build                                         : disabled 
Checking for whether to include binary compile time               : yes 
Checking for whether to optimize                                  : yes 
Checking for whether to compile-in debugging information          : yes 
Checking for manpage generation                                   : no (missing RST2MAN) 
Checking for html manual generation                               : disabled 
Checking for pdf manual generation                                : disabled 
Checking for dynamic loader                                       : yes 
Checking for C plugins                                            : disabled 
Checking for dlopen                                               : yes 
Checking for compilation of default filters for vf_dlopen         : disabled 
Checking for zsh completion                                       : disabled 
Checking for inline assembly (currently without effect)           : yes 
Checking for test suite (using cmocka)                            : disabled 
Checking for generate a clang compilation database                : disabled 
Checking for compiler support for noexecstack                     : yes 
Checking for linker support for --nxcompat --no-seh --dynamicbase : no 
Checking for -lm                                                  : yes 
Checking for MinGW                                                : os-win32 not found 
Checking for POSIX environment                                    : yes 
Checking for development environment                              : yes 
Checking for win32                                                : not found any of os-win32, os-cygwin 
Checking for internal pthread wrapper for win32 (Vista+)          : win32 not found 
Checking for POSIX threads                                        : yes 
Checking for GNU C extensions                                     : yes 
Checking for stdatomic.h                                          : no 
Checking for stdatomic.h support or slow emulation                : yes 
Checking for C11 TLS support                                      : no 
Checking for GCC TLS support                                      : yes 
Checking for linking with -lrt                                    : yes 
Checking for iconv                                                : yes 
Checking for w32/dos paths                                        : not found any of os-win32, os-cygwin 
Checking for termios                                              : yes 
Checking for shm                                                  : yes 
Checking for nanosleep                                            : yes 
Checking for POSIX spawnp()/kill()                                : yes 
Checking for posix_spawnp() or MinGW                              : yes 
Checking for glob()                                               : yes 
Checking for glob() win32 replacement                             : not found any of os-win32, os-cygwin 
Checking for fchmod()                                             : yes 
Checking for vt.h                                                 : yes 
Checking for gbm.h                                                : no 
Checking for GLIBC API for setting thread name                    : yes 
Checking for OSX API for setting thread name                      : glibc-thread-name found 
Checking for BSD API for setting thread name                      : glibc-thread-name found 
Checking for NetBSD API for setting thread name                   : glibc-thread-name found 
Checking for BSD's fstatfs()                                      : no 
Checking for Linux's fstatfs()                                    : yes 
Checking for Samba support                                        : no ('smbclient' not found) 
Checking for Lua                                                  : no ('luajit >= 2.0.0' not found) 
Checking for SSA/ASS support                                      : yes 
Checking for libass OSD support                                   : yes 
Checking for dummy OSD support                                    : libass-osd found 
Checking for zlib                                                 : yes 
Checking for Encoding                                             : yes 
Checking for Bluray support                                       : no ('libbluray >= 0.3.0' not found) 
Checking for dvdread support                                      : no ('dvdread >= 4.1.0' not found) 
Checking for dvdnav support                                       : dvdread not found 
Checking for cdda support (libcdio)                               : no ('libcdio_paranoia' not found) 
Checking for uchardet support                                     : no ('uchardet' not found) 
Checking for librubberband support                                : no ('rubberband >= 1.8.0' not found) 
Checking for LCMS2 support                                        : no ('lcms2 >= 2.6' not found) 
Checking for VapourSynth filter bridge (Python)                   : no ('vapoursynth >= 24 vapoursynth-script >= 23' not found) 
Checking for VapourSynth filter bridge (Lazy Lua)                 : lua not found 
Checking for VapourSynth filter bridge (core)                     : not found any of vapoursynth-lazy, vapoursynth 
Checking for libarchive wrapper for reading zip files and more    : disabled 
Checking for SDL2                                                 : disabled 
Checking for SDL (1.x)                                            : disabled 
Checking for OSS (implementation from opensound.com)              : no 
Checking for OSS (platform-specific OSS implementation)           : yes 
Checking for OSS (emulation on top of SunAudio)                   : oss-audio-native found 
Checking for OSS audio output                                     : yes 
Checking for RSound audio output                                  : no 
Checking for sndio audio input/output                             : disabled 
Checking for PulseAudio audio output                              : no ('libpulse >= 1.0' not found) 
Checking for JACK audio output                                    : no ('jack' not found) 
Checking for OpenAL audio output                                  : disabled 
Checking for OpenSL ES audio output                               : no 
Checking for ALSA audio output                                    : yes 
Checking for CoreAudio audio output                               : no 
Checking for AudioUnit output for iOS                             : no 
Checking for WASAPI audio output                                  : win32 not found 
Checking for Cocoa                                                : no 
Checking for DRM                                                  : yes 
Checking for GBM                                                  : gbm.h not found 
Checking for Wayland                                              : no ('wayland-client >= 1.6.0 wayland-cursor >= 1.6.0 xkbcommon >= 0.3.0' not found) 
Checking for X11                                                  : yes 
Checking for Xss screensaver extensions                           : no ('xscrnsaver' not found) 
Checking for X extensions                                         : yes 
Checking for Xv video output                                      : yes 
Checking for Xinerama                                             : yes 
Checking for Xrandr                                               : yes 
Checking for OpenGL Cocoa Backend                                 : cocoa not found 
Checking for OpenGL X11 Backend                                   : yes 
Checking for OpenGL X11 EGL Backend                               : yes 
Checking for OpenGL DRM EGL Backend                               : gbm not found 
Checking for OpenGL Wayland Backend                               : wayland not found 
Checking for OpenGL Win32 Backend                                 : win32 not found 
Checking for OpenGL/DirectX Interop Backend                       : gl-win32 not found 
Checking for OpenGL Win32 ANGLE Backend                           : not found any of os-win32, os-cygwin 
Checking for OpenGL Win32 ANGLE Library                           : egl-angle not found 
Checking for VDPAU acceleration                                   : no ('vdpau >= 0.2' not found) 
Checking for VDPAU with OpenGL/X11                                : vdpau not found 
Checking for VAAPI acceleration                                   : no ('libva >= 0.36.0' not found) 
Checking for VAAPI (X11 support)                                  : vaapi not found 
Checking for VAAPI (Wayland support)                              : gl-wayland, vaapi not found 
Checking for VAAPI (DRM/EGL support)                              : vaapi, egl-drm not found 
Checking for VAAPI GLX                                            : vaapi-x11 not found 
Checking for VAAPI EGL on X11                                     : vaapi-x11 not found 
Checking for VAAPI EGL                                            : not found any of vaapi-wayland, vaapi-x-egl 
Checking for CACA                                                 : no ('caca >= 0.99.beta18' not found) 
Checking for JPEG support                                         : no 
Checking for Direct3D support                                     : win32 not found 
Checking for Android support                                      : no 
Checking for Raspberry Pi support                                 : no ('bcm_host' not found) 
Checking for Desktop standard OpenGL support                      : yes 
Checking for Android OpenGL ES support                            : android not found 
Checking for iOS OpenGL ES support                                : no 
Checking for Any OpenGL (ES) support                              : yes 
Checking for OpenGL without platform-specific code (e.g. for libmpv) : not found any of libmpv-shared, libmpv-static 
Checking for MALI via Linux fbdev                                    : no 
Checking for OpenGL video outputs                                    : yes 
Checking for EGL helper functions                                    : yes 
Checking for FFmpeg/Libav present                                    : yes 
Checking for libav* is FFmpeg                                        : yes 
Checking for libav* is Libav                                         : no 
Checking for Libav/FFmpeg library versions                           : yes 
Checking for libavdevice                                             : yes 
Checking for libavutil GPU memcpy for hardware decoding              : no 
Checking for libavcodec VAAPI hwaccel                                : vaapi not found 
Checking for libavcodec VAAPI hwaccel (new)                          : vaapi-hwaccel not found 
Checking for libavcodec VAAPI hwaccel (old)                          : vaapi-hwaccel not found 
Checking for libavcodec videotoolbox hwaccel                         : no 
Checking for Videotoolbox with OpenGL                                : videotoolbox-hwaccel, gl-cocoa not found 
Checking for libavcodec VDPAU hwaccel                                : vdpau not found 
Checking for DXVA2 and D3D11VA hwaccel                               : win32 not found 
Checking for CUDA hwaccel                                            : yes 
Checking for GCC SSE4 intrinsics for GPU memcpy                      : not found any of d3d-hwaccel, vaapi-hwaccel-old 
Checking for TV interface                                            : yes 
Checking for videoio.h                                               : no 
Checking for videodev2.h                                             : yes 
Checking for Video4Linux2 TV interface                               : yes 
Checking for libv4l2 support                                         : no ('libv4l2' not found) 
Checking for audio input support                                     : yes 
Checking for DVB input module                                        : yes 
Checking for w32 executable                                          : not found any of os-win32, os-cygwin 
Checking for Apple Remote support                                    : cocoa not found 
Writing configuration header:                                        : config.h 
'configure' finished successfully (8.994s)
Waf: Entering directory `/home/rich/Programme/mpv-build/mpv/build'
[  1/217] Compiling version.sh
Waf: Leaving directory `/home/rich/Programme/mpv-build/mpv/build'
'build' finished successfully (1.503s)
Waf: Entering directory `/home/rich/Programme/mpv-build/mpv/build'
[  1/229] Compiling version.sh
[217/229] Linking build/mpv
+ install /usr/local/share/doc/mpv/mpv.conf (from etc/mpv.conf)
+ install /usr/local/share/doc/mpv/input.conf (from etc/input.conf)
+ install /usr/local/share/doc/mpv/mplayer-input.conf (from etc/mplayer-input.conf)
+ install /usr/local/share/doc/mpv/restore-old-bindings.conf (from etc/restore-old-bindings.conf)
+ install /usr/local/share/applications/mpv.desktop (from etc/mpv.desktop)
+ install /usr/local/etc/mpv/encoding-profiles.conf (from etc/encoding-profiles.conf)
+ install /usr/local/share/icons/hicolor/16x16/apps/mpv.png (from etc/mpv-icon-8bit-16x16.png)
+ install /usr/local/share/icons/hicolor/32x32/apps/mpv.png (from etc/mpv-icon-8bit-32x32.png)
+ install /usr/local/share/icons/hicolor/64x64/apps/mpv.png (from etc/mpv-icon-8bit-64x64.png)
+ install /usr/local/share/icons/hicolor/scalable/apps/mpv.svg (from etc/mpv-gradient.svg)
+ install /usr/local/share/icons/hicolor/symbolic/apps/mpv-symbolic.svg (from etc/mpv-symbolic.svg)
+ install /usr/local/bin/mpv (from build/mpv)
Waf: Leaving directory `/home/rich/Programme/mpv-build/mpv/build'
'install' finished successfully (3.752s

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

rich@debian:~$ mpv -v Jah\ Bouks\ -\ Angola\ \[Official\ Video\ 2013\]-kGTpmVf3CHU.mp4 
[cplayer] Command line options: '-v' 'Jah Bouks - Angola [Official Video 2013]-kGTpmVf3CHU.mp4'
[cplayer] mpv git-076116a (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri Mar 10 17:17:10 UTC 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.48.100
[cplayer]    libavcodec      57.82.102
[cplayer]    libavformat     57.66.104
[cplayer]    libswscale      4.3.101
[cplayer]    libavfilter     6.74.100
[cplayer]    libswresample   2.4.100
[cplayer] ffmpeg version: N-83795-g195784e
[cplayer] 
[cplayer] Configuration: ./waf configure
[cplayer] List of enabled features: alsa any-gl asm atomics audio-input build-date cplayer cuda-hwaccel debug-build dlopen drm dvbin egl-helpers egl-x11 encoding fchmod gcc-tls gl gl-x11 glibc-thread-name glob gnuc iconv is_ffmpeg libass libass-osd libav libavcodec libavdevice libdl libm librt linux-fstatfs nanosleep optimize oss-audio oss-audio-native posix posix-or-mingw posix-spawn pthreads shm standard-gl subprocess termios tv tv-v4l2 videodev vt.h x11 xext xinerama xrandr xv zlib
[global] config path: '' -> '/home/rich/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/home/rich/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/rich/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/home/rich/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/rich/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/etc/mpv/config'
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -/-> '/home/rich/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/home/rich/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/etc/mpv/input.conf'
[global] config path: 'scripts' -/-> '/home/rich/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/home/rich/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[global] config path: 'watch_later' -> '/home/rich/.config/mpv/watch_later'
[cplayer] Playing: Jah Bouks - Angola [Official Video 2013]-kGTpmVf3CHU.mp4
[file] Opening Jah Bouks - Angola [Official Video 2013]-kGTpmVf3CHU.mp4
[file] Stream opened successfully.
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[cplayer] Opening done: Jah Bouks - Angola [Official Video 2013]-kGTpmVf3CHU.mp4
[find_files] Loading external files in .
[global] config path: 'sub/' -/-> '/home/rich/.config/mpv/sub/'
[global] config path: 'sub/' -/-> '/home/rich/.mpv/sub/'
[global] config path: 'sub/' -/-> '/usr/local/etc/mpv/sub/'
[global] config path: 'audio/' -/-> '/home/rich/.config/mpv/audio/'
[global] config path: 'audio/' -/-> '/home/rich/.mpv/audio/'
[global] config path: 'audio/' -/-> '/usr/local/etc/mpv/audio/'
[cplayer]  (+) Video --vid=1 (*) (h264)
[cplayer]  (+) Audio --aid=1 --alang=und (*) (aac)
[vo/opengl] Initializing OpenGL backend 'x11probe'
[vo/opengl/x11] X11 opening display: :0
[vo/opengl/x11] X11 running at 1280x1024 (":0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Display 0 (DVI-I-2): [0, 0, 1280, 1024] @ 60.019740 FPS
[vo/opengl/x11] Current display FPS: 60.019740
[vo/opengl] GLX chose FB config with ID 0xc1
[vo/opengl] GLX chose visual with ID 0x14f
[vo/opengl] Creating OpenGL 3.3 context...
[vo/opengl] Creating OpenGL 3.2 context...
[vo/opengl] Creating OpenGL 3.1 context...
[vo/opengl] Creating OpenGL 3.0 context...
[vo/opengl] Creating OpenGL 2.1 context...
[vo/opengl] GL_VERSION='2.1 Mesa 8.0.5'
[vo/opengl] Detected desktop OpenGL 2.1.
[vo/opengl] GL_VENDOR='nouveau'
[vo/opengl] GL_RENDERER='Gallium 0.4 on NV47'
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='1.20'
[vo/opengl] Loaded extension GL_ARB_map_buffer_range.
[vo/opengl] Loaded extension GL_ARB_framebuffer_object.
[vo/opengl] Loaded extension GL_ARB_vertex_array_object.
[vo/opengl] Loaded extension GL_ARB_texture_rg.
[vo/opengl] Loaded extension GL_ARB_sync.
[vo/opengl] Loaded extension GLX_SGI_swap_control.
[vo/opengl] Loaded extension GLX_SGI_video_sync.
[vo/opengl] No vdpau support found - probing more things.
[vo/opengl/x11] uninit ...
[vo/opengl] Initializing OpenGL backend 'x11egl'
[vo/opengl/x11] X11 opening display: :0
[vo/opengl/x11] X11 running at 1280x1024 (":0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Display 0 (DVI-I-2): [0, 0, 1280, 1024] @ 60.019740 FPS
[vo/opengl/x11] Current display FPS: 60.019740
[vo/opengl] EGL_VERSION=1.4 (Gallium)
[vo/opengl] EGL_VENDOR=Mesa Project
[vo/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES OpenGL_ES2 OpenVG 
[vo/opengl] Trying to create Desktop OpenGL context.
[vo/opengl] chose visual 0x14f
[vo/opengl] GL_VERSION='2.1 Mesa 8.0.5'
[vo/opengl] Detected desktop OpenGL 2.1.
[vo/opengl] GL_VENDOR='nouveau'
[vo/opengl] GL_RENDERER='Gallium 0.4 on NV47'
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='1.20'
[vo/opengl] Loaded extension GL_ARB_map_buffer_range.
[vo/opengl] Loaded extension GL_ARB_framebuffer_object.
[vo/opengl] Loaded extension GL_ARB_vertex_array_object.
[vo/opengl] Loaded extension GL_ARB_texture_rg.
[vo/opengl] Loaded extension GL_ARB_sync.
[vo/opengl] swap_control extension missing.
[vo/opengl] 16 bit texture depth: 8.
[vo/opengl] Reported display depth: R=8, G=8, B=8
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Assuming 60.019740 FPS for display sync.
[vd] Container reported FPS: 29.970030
[vd] Codec list:
[vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd] Opening video decoder h264
[vd] Using software decoding.
[vd] Detected 4 logical cores.
[vd] Requesting 5 threads for decoding.
[vd] Selected video codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[ad] Codec list:
[ad]     aac - AAC (Advanced Audio Coding)
[ad]     aac_fixed (aac) - AAC (Advanced Audio Coding)
[ad] Opening audio decoder aac
[ad] Requesting 1 threads for decoding.
[ad] Selected audio codec: aac (AAC (Advanced Audio Coding))
[cplayer] Starting playback...
[vo/opengl/x11] Disabling screensaver.
[vo/opengl/x11] Setting DMPS: off.
[ffmpeg/video] h264: Reinit context to 1280x720, pix_fmt: yuv420p
[af] Audio filter chain:
[af]   [in] 44100Hz stereo 2ch floatp
[af]   [out] 44100Hz stereo 2ch floatp
[af]   [ao] 44100Hz stereo 2ch floatp
[ao] Trying audio driver 'alsa'
[ao/alsa] requested format: 44100 Hz, stereo channels, floatp
[ao/alsa] using ALSA version: 1.0.25
[ao/alsa] opening device 'default'
[ao/alsa] trying format float
[ao/alsa] Going to set final HW params:
[ao/alsa] ---
[ao/alsa] ACCESS:  RW_INTERLEAVED
[ao/alsa] FORMAT:  FLOAT_BE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: 32
[ao/alsa] FRAME_BITS: 64
[ao/alsa] CHANNELS: 2
[ao/alsa] RATE: 44100
[ao/alsa] PERIOD_TIME: (15623 15647)
[ao/alsa] PERIOD_SIZE: (689 690)
[ao/alsa] PERIOD_BYTES: (5512 5513)
[ao/alsa] PERIODS: 16
[ao/alsa] BUFFER_TIME: 250000
[ao/alsa] BUFFER_SIZE: 11025
[ao/alsa] BUFFER_BYTES: 88200
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] hw pausing supported: yes
[ao/alsa] buffersize: 11025 samples
[ao/alsa] period size: 689 samples
[ao/alsa] device buffer: 11025 samples.
[ao/alsa] using soft-buffer of 11025 samples.
[cplayer] AO: [alsa] 44100Hz stereo 2ch float
[cplayer] AO: Description: ALSA audio output
[af] Adding filter lavrresample 
[af] Audio filter chain:
[af]   [in] 44100Hz stereo 2ch floatp
[af]   [lavrresample] 44100Hz stereo 2ch float [a]
[af]   [out] 44100Hz stereo 2ch float
[af]   [ao] 44100Hz stereo 2ch float
[vd] Decoder format: 1280x720 yuv420p bt.709/bt.709/bt.1886/limited CL=mpeg2/4/h264
[vf] Video filter chain:
[vf]   [in] 1280x720 yuv420p bt.709/bt.709/bt.1886/limited CL=mpeg2/4/h264
[vf]   [out] 1280x720 yuv420p bt.709/bt.709/bt.1886/limited CL=mpeg2/4/h264
[cplayer] VO: [opengl] 1280x720 yuv420p
[cplayer] VO: Description: Extended OpenGL Renderer
[vo/opengl/x11] not waiting for MapNotify
[vo/opengl] Resize: 1278x720
[vo/opengl] Window size: 1278x720
[vo/opengl] Video source: 1280x720 (1:1)
[vo/opengl] Video display: (0, 0) 1280x720 -> (0, 1) 1278x718
[vo/opengl] Video scale: 0.998437/0.997222
[vo/opengl] OSD borders: l=0 t=1 r=0 b=1
[vo/opengl] Video borders: l=0 t=1 r=0 b=1
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Texture for plane 0: 1280x720
[vo/opengl] Texture for plane 1: 640x360
[vo/opengl] Texture for plane 2: 640x360
[cplayer] set video colors output-levels=0 
[vo/opengl] recompiling a shader program:
[vo/opengl] [  1] color.r = 1.000000 * vec4(texture(texture0, texcoord0)).r;
[vo/opengl] [  2] color.g = 1.000000 * vec4(texture(texture1, texcoord1)).r;
[vo/opengl] [  3] color.b = 1.000000 * vec4(texture(texture2, texcoord2)).r;
[vo/opengl] [  4] // color conversion
[vo/opengl] [  5] color = color.rgba;
[vo/opengl] [  6] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[vo/opengl] [  7] color.a = 1.0;
[vo/opengl] [  8] // color mapping
[cplayer] first video frame after restart shown
[cplayer] starting audio playback
[cplayer] playback restart complete
[vo/opengl] Resize: 1278x719
[vo/opengl] Window size: 1278x719
[vo/opengl] Video source: 1280x720 (1:1)
[vo/opengl] Video display: (0, 0) 1280x720 -> (0, 0) 1278x719
[vo/opengl] Video scale: 0.998437/0.998611
[vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[vo/opengl] Video borders: l=0 t=0 r=0 b=0
[statusline] AV: 00:00:15 / 00:04:09 (6%) A-V:  0.001
[cplayer] Run command: quit, flags=9, args=[0]
[cplayer] EOF code: 6  
[ad] Uninit audio decoder.
[af] Removing filter lavrresample 
[vd] Uninit video.
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Quit)
[ao/alsa] draining...
[vo/opengl/x11] Enabling screensaver.
[vo/opengl/x11] Setting DMPS: on.
[vo/opengl] flushing shader cache
[vo/opengl/x11] uninit ...
![bildschirmfoto vom 2017-03-10 18 12 38](https://cloud.githubusercontent.com/assets/12947465/23807839/2d894d3a-05bf-11e7-8a0a-29f844acfff1.png)

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wm4** [comment]
I'm fairly sure this is a GPU driver issue.

Is there a reason your screenshot looks so blue?

**Comment by CounterPillow** [comment]
This issue (and your [blue colour](https://wiki.ubuntu.com/PowerPCKnownIssues#A14.04_Trusty_Tahr)) might be caused by your very old Mesa version (8.0.5 from October 2012). Mesa is the FOSS implementation of OpenGL that open drivers such as Intel's i965 or nouveau rely on.

PowerPC is a big-endian system, and since a lot of code is written and tested on x86, some drivers and applications may make implicit assumptions about using little-endian, which can introduce bugs like you see when said code is run on big-endian platforms. The scaling and rendering of the video in mpv is done by OpenGL shaders in this case, and in my experience platform-specific bugs in OpenGL shaders are often triggered by driver/OpenGL implementation bugs.

Since version 8.0.5, Mesa did not only receive improvements such as potential OpenGL 3.1 support for your hardware, but has also received bug fixes for big-endian systems. It may resolve your blurriness issue.

**Comment by mrkapqa** [comment]
thank you very much for your quick help - 
can i just update mesa withouth need to update to jessie ? it happened to me lately that whenever i install jessie directly on powermac it would not boot, i think there is problem with installer on powerpc (at least i must have problems with yaboot when dealing with 2 hardddrives).
so as far as possible i'd like to stay put atm; 

it found this post (but it is concerning jessie)

Ah, if you want newer GL drivers you need to upgrade libgl1-mesa-dri and libgl1-mesa-glx (which should upgrade the other required packages): apt-get -t jessie-backports install libgl1-mesa-{dri,glx}

so could i just add the jessie-backports to my wheezy-sources-list and install the newer mesa?

i found when i update to jessie that the blurring thing is actually gone, but then i had other problems.

thanks

**Comment by CounterPillow** [comment]
>i found when i update to jessie that the blurring thing is actually gone

so this confirms it's a driver/mesa issue.

>so could i just add the jessie-backports to my wheezy-sources-list and install the newer mesa?

I'm not very familiar with Debian, but I don't think you can just add repositories like that from a newer release to an older one. You'd have to ask a Debian-focused community if you want help with upgrading/fixing your Debian system.

**Comment by kevmitch** [comment]
> so could i just add the jessie-backports to my wheezy-sources-list and install the newer mesa?

No. jessie-backports is backports **to** jessie from testing so is not binary compatible with wheezy. If wheezy-backports solves your problem, you should use that instead. Alternatively, you can try adding a deb-src (not deb) for jesse to sources.list and rebuild the package yourself (apt-get source libgl1-mesa-dri, dpkg-buildpackage -uc -us)

**Comment by mrkapqa** [comment]
thank you so much for your help,
i have an imac g5 and wheezy runs really so much better than jessie on it. 
could i also do this deb-src with kodi which is available in my preferred version 16.1 on jessie-backports whilst staying on wheezy? i tried to compile it several times on powerpc, but it always failed on me at sometime.

**Comment by wm4** [comment]
So, np mpv problem confirmed, closing.
