### ISSUE TITLE
Option to change the title of file shown by OSC to file name?

### ISSUE THREAD

**Issue by rieje** [mpv-player/mpv#4221]
The OSC always shows the title of the video, but I want it to show the file name instead. I must always manually check the file name via right-clicking the title or `SHIFT + I`, but even then it only shows the file name briefly. I don't want the title of the video to be shown at all, because that means I need to properly tag the titles of all videos, whereas it's far more practical to name the file names to something more sensible.

I have searched everywhere in the [documentation](https://mpv.io/manual/master/) but haven't found such an option.

P.S. Setting `seek 3` and `seek -3` or whatever value only seems to work for a few videos--is this a bug? I never had this problem on VLC so I don't think it is file-dependent.

**Comment by ChrisK2** [comment]
Uuuh ... I guess we could make the title toggle-able to switch between file-name and file-title and have a config option to set what is displayed initially, similarly to the timestamps.
