### ISSUE TITLE
macOS:  Being able to change system-volume with Apple Remote.

### ISSUE THREAD

**Issue by Lord-Kamina** [mpv-player/mpv#4226]
### mpv version
 - Any on macOS.

### Reproduction steps
 - Press volume up/down on Apple Remote.
### Expected behavior
 - System volume is changed.
### Actual behavior
 - mpv changes its internal volume. And, If the appropriate buttons are remapped to "ignore" in input.conf, then nothing happens.

I understand if you don't want to make changes in the default config, but it'd be great to at least be able to configure the app so we can change the system volume.

**Comment by Akemi** [comment]
there are probably only two ways to handle this. either change `kHIDRemoteModeExclusiveAuto` to `kHIDRemoteModeShared` or programatically changing the system volume if that is possible.

**Comment by zohozer** [comment]
I'm using my Apple remote all day long to change the master volume of my MacBookPro. To make this working you will need to download "BetterTouchTool" and configure there the buttons as you wish. Personally I assigned SHORT press of Vol UP/DOWN to change the MPV internal volume and LONG press of Vol UP/DOWN to change the master volume of my MAC. You can assign a lot more actions to your remote as you need. I think this is the best option for MAC users.

**Comment by hector** [comment]
I have been able to change the volume with no problems with mac versions prior to High Sierra (OSX  10.13), but with High Sierra all buttons work except up/down for volume.
It seems Apple might have changed the mapping of those buttons. I copy the links I have found about the issue:

https://discussions.apple.com/thread/8106033
https://forums.plex.tv/discussion/289570/mac-mini-osx-updated-to-high-sierra-and-remote-problem

The second link contains references on how other open source projects (Kodi, openPHT) have solved it.

I have also checked that VLC was having this problem and now it is working fine, but I cannot confirm if it is something VLC has solved or something that Apple changed on the last OSX 10.13.4 update. Anyway, the problem persists for MPV on OSX 10.13.4.

**Comment by Akemi** [comment]
@hector i don't think mpv was ever able to change the system volume on macOS. if you didn't rebind your input keys it's just the internal mpv volume you are changing.

the buttons that don't work anymore on 10.13 is a completely different issue and you should open a new one for that.

**Comment by hector** [comment]
Thanks @Akemi. I actually meant the internal mpv volume, as you suggested. Besides, I don't mpv should change the system volume, at least by default. All other media players I know of don't do that.

**Comment by Akemi** [comment]
since apple remote has been scrapped by both Apple and us.
