### ISSUE TITLE
stream_cb and invoke libmpv APIs in a different instance

### ISSUE THREAD

**Issue by siriux** [mpv-player/mpv#4227]
I want to use multiple mpv instances, some for reading and one for writing. The idea is that I'll create a custom stream reading from some instances (using opengl_cb), and I would use it with stream_cb on the writing instance to write it to an output.

But I've seen this note about stream_cb, and I'm not sure if it applies, because I would be invoking the apis of a different instance (the reader instances), while the custom callbacks are registered on the writer instance of mpv.

> * Note that your custom callbacks must not invoke libmpv APIs as that would
> * cause a deadlock.

Is this safe to do? If so, the note could be modified to reflect this possibility.

PS: I don't know if there is a better way to provide user created frames as an input than stream_cb. So maybe this is irrelevant.

**Comment by wm4** [comment]
> Is this safe to do?

Yes.

>  I don't know if there is a better way to provide user created frames as an input than stream_cb.

What kind of frames? Probably no.
