### ISSUE TITLE
pcm_cb for audio equivalent of opengl_cb

### ISSUE THREAD

**Issue by siriux** [mpv-player/mpv#4228]
As I couldn't find a way to get the audio output from the player, as I do with the video using opengl_cb, I propose a new audio output called pcm_cb that allows to receive the audio in a callback.

If there is already an alternative way to do this, please let me know.

**Comment by wm4** [comment]
Currently there's no way to do this. At best you could force one of the existing AOs to write to "your" sink.

What's this for?

**Comment by siriux** [comment]
Thanks. The idea was to use it for video editing, but I think I'll use something else.

**Comment by wm4** [comment]
If you don't want this feature anymore, please close the issue.
