### ISSUE TITLE
add a lyrics displayer

### ISSUE THREAD

**Issue by Droyk** [mpv-player/mpv#4229]
Good morning guys,

I just found out about mpv kinda like it and saw there no functionality for lyrics I love to read lyrics when I am hearing music so plz add it and if you can plz add all the type of functionalities that mini lyrics have http://www.crintsoft.com/MiniLyrics.htm

3 functionalities I want the most 

- always on top feature, so you can see the lyrics on top of anything.
- automatically search the lyrics on the net
- floating lyrics (what this feature does is let the lyrics float on top of everything and doesn't interact with user mouse clicks that's a really handy feature.)

**Comment by ChrisK2** [comment]
It probably makes more sense to get MiniLyrics to use mpv as player than integrating all that highly special-case and out-of-scope-of-a-video-player-functionality into mpv.

also:

> always on top feature, so you can see the lyrics on top of anything.

already possible, see "stay on top"

> automatically search the lyrics on the net

Out of scope for the mpv core, write a lua-script for that.

**Comment by Droyk** [comment]
>It probably makes more sense to get MiniLyrics to use mpv as player than integrating all that highly special-case and out-of-scope-of-a-video-player-functionality into mpv.

you are completely right but the main problem is minilyrics already stop developing so there no chance that they will ever start developing again just for mpv that's the reason I said to add these features.

**Comment by Boot-Error** [comment]
Is this issue still relevant? We 

> > It probably makes more sense to get MiniLyrics to use mpv as player than integrating all that highly special-case and out-of-scope-of-a-video-player-functionality into mpv.
> 
> you are completely right but the main problem is minilyrics already stop developing so there no chance that they will ever start developing again just for mpv that's the reason I said to add these features.

We can use the APIs provided by MusixMatch to fetch lyrics with timestamp and display in MPV.

And if it was ever to fetch timestamp lyrics, one could translate into a subtitle file and feed it to the GUI, showing the lyrics. This sounds useful!

**Comment by guidocella** [comment]
A synchronized lyrics downloader is now in the wiki's user scripts.
