### ISSUE TITLE
Feature request: Third state after video ending

### ISSUE THREAD

**Issue by kaymio** [mpv-player/mpv#4230]
Hi,
mpv has been my daily driver for years. Especially for watching youtube and other video portals. Mostly using drag and drop, it confronts me with a little but ever present problem.

As far as I know, either the player exits after the video has ended or it wil be kept open with the following section in the mpv.conf

`# Do not close the window on exit.

keep-open=yes`

So each time I drag and drop a link into the mpv player I've to do it just before the previous video has ended or have to right click in the player after the link has been inserted in the stopped player.

This behavior is not present when at first starting mpv. Then the logo is visible and the added link plays right away. 
Now the feature request: Could the player go back to the state it has been in at the first start, instead of doing a hard stop after ending a video? So each added new link is playing right away, without having to unpause it.

**Comment by AirPort** [comment]
You're probably searching for `idle=yes`.

**Comment by kaymio** [comment]
Thanks, that's just what I wanted. After disabling the keep-open=yes and adding idle=yes it does what I just requested. Thx again. I'll close this issue.
