### ISSUE TITLE
screenshot-to-file not accepting variables

### ISSUE THREAD

**Issue by nonamethanks** [mpv-player/mpv#4233]
### mpv version and platform
Latest in https://www.archlinux.org/packages/community/i686/mpv/

### Reproduction steps
If my "input.conf" file contains the line `w screenshot-to-file "/home/nonamethanks/tools/stitching/screenshot_%F.png" video` which I'd like to use for when I need to save some pictures to a separate folder that is monitored by various scripts, the "%F" string or whatever other variable in its place is interpreted as two literal and separate characters rather than as a variable, while the mpv.conf options such as "screenshot-template" instead work as intended.

### Expected behavior
The %F variable should be interpreted as the name of the file. The screenshot filename should be be "screenshot_originalfilenamehere.png".

### Actual behavior
The screenshot created has filename "screenshot_%F.png"
The "%F" is interpreted literally and not as a variable. Same goes for %n, %P, etc. This makes the screenshot-to-file option useless as the screenshots keep overwriting each other.

### Log file
https://puu.sh/uHxY5/8a691034e0.txt
Relative lines:
```
[   0.960][v][cplayer] Run command: screenshot-to-file, flags=9, args=[/home/nonamethanks/tools/stitching/screenshot%F%P%n.png, video]
[   0.960][i][cplayer] Screenshot: '/home/nonamethanks/tools/stitching/screenshot%F%P%n.png'
```

**Comment by wm4** [comment]
Unfortunately the whole point of the `screenshot-to-file` command is that it doesn't expand any of such variables. You can either set the screenshot-template to it and use the normal screenshot command, or explicitly provide your own filename. You could for example script it with Lua.
