### ISSUE TITLE
dvdread:// doesn't correctly detect audio/subtitles in some cases

### ISSUE THREAD

**Issue by qrwyeui** [mpv-player/mpv#4235]
On some discs, mpv dvdread:// doesn't detect the presence of DVD subtitles.  Presumably, the same is true of audio, although I haven't noticed any discs where that is the case.

The issue is that when scanning for subtitles, it looks at the metadata for the wrong PGC - it uses the VTS-relative title number instead of the PGC number.  (Of course, the two are most often equal, but they don't have to be.)  For example, on the disc I'm looking at:

- I'm trying to play the seventh title on the disc (what mpv refers to as dvdread://6).  That happens to be the third title in the second VTS:

   tt_srpt->title[6].title_set_nr = 2
   tt_srpt->title[6].vts_ttn = 3

- It corresponds to the eighth PGC within that VTS:

   vts_ptt_srpt->title[2].ptt[0].pgcn = 8

- That PGC includes two audio tracks and one subtitle track:

   vts_pgcit->pgci_srp[7].pgc->audio_control[0] = 0x8000
   vts_pgcit->pgci_srp[7].pgc->audio_control[1] = 0x8100
   vts_pgcit->pgci_srp[7].pgc->audio_control[2...7] = 0
   vts_pgcit->pgci_srp[7].pgc->subp_control[0] = 0x80000000
   vts_pgcit->pgci_srp[7].pgc->subp_control[1...31] = 0

- Meanwhile, the *third* PGC in that VTS happens to contain the
  same two audio tracks and no subtitles:

   vts_pgcit->pgci_srp[2].pgc->audio_control[0] = 0x8000
   vts_pgcit->pgci_srp[2].pgc->audio_control[1] = 0x8100
   vts_pgcit->pgci_srp[2].pgc->audio_control[2...7] = 0
   vts_pgcit->pgci_srp[2].pgc->subp_control[0...31] = 0

The effect is that 'mpv dvdread://6' correctly plays the eighth PGC in the second VTS, but does not allow me to turn on subtitles, either via the command line or by pressing 'j'.

This is due to the following in stream_dvd.c:

   pgc = vts_file->vts_pgcit ? vts_file->vts_pgcit->pgci_srp[ttn].pgc : NULL;

Here, AFAICT, 'ttn' should instead be 'pgc_id-1' (as defined later in the same function.)

Of course, this isn't perfect - it still might fail to detect audio/subtitles in a title that contains *multiple* PGCs.  However, scanning the first PGC in the title was obviously the intent here, and makes more sense than scanning some other unrelated PGC. :)

The bug is an old one; mplayer also does not detect the subtitles in this case.  However, mplayer, unlike mpv, allows me to *enable* subtitles even though it doesn't detect them.

**Comment by wm4** [comment]
Use dvdnav via dvd://.

**Comment by qrwyeui** [comment]
LOL, I was kinda half expecting that.  Please fix #3005, then we'll talk. :)

**Comment by wm4** [comment]
>Please fix #3005, 

That's not our bug either.

You want DVD? You get DVD. Which means terrible quality and terrible behavior, apparently. You don't want that? Rip the DVD.

**Comment by qrwyeui** [comment]
Not everybody has the time or the disk space (or for that matter, the expertise) to do that.  Otherwise, we wouldn't be talking about this.

Whatever.  I've identified a problem, I've explained in detail why the existing code is incorrect, and I've provided the fix, which is trivial.  You can do what you like with it.

**Comment by wm4** [comment]
> Not everybody has the time

To much time has been wasted on DVD playback.

>  or the disk space

Are you joking? Making a transparent encode with x264 will result in a fraction of the space needed for a DVD.

> You can do what you like with it.

I absolutely don't care. I tried to remove the DVD code 2 times from this project, but it turned out to be simpler to just ignore all DVD bug reports instead of dealing with users who want DVD support back. Anyway, if you want any change applied, make a PR.

**Comment by tobiasjakobi** [comment]
I just wanted to express my thanks to qrwyeui for fixing this bug. Also I don't understand where this hating of optical media comes from. It's like, every time this comes up, wm4 throws a fit and then changes some default options to punish users.

**Comment by wm4** [comment]
Because they're complex, terribly implemented, and effectively unmaintained (not only in mpv).

If someone wants to overtake maintainership, they can be enabled by default again.
