### ISSUE TITLE
libmpv opengl-cb limits the framerate of the host opengl application to the framerate of the movie

### ISSUE THREAD

**Issue by gunnarmarten** [mpv-player/mpv#4237]
### mpv version and platform

MacOS Sierra 10.12.3
mpv: git-636675e
ffmpeg: 3.2.4

### Reproduction steps

I'm using libmpv with opengl-cb in my opengl application. The application normally runs at 60 fps. But when I play a movie the framerate drops to the fps of the movie.
I'm using the opengl-cb api like in the sdl example. I call `mpv_opengl_cb_draw` in my render loop to get the frame rendered into an fbo for further usage.
I tried adding `mpv_opengl_cb_report_flip` but the behavior was the same.
I experimented with some options. I tested with `video-sync=desync` but without any change.

To reproduce you can use the sdl example from https://github.com/mpv-player/mpv-examples.git
and add a timer around the call `mpv_opengl_cb_draw` to see the the different durations it takes when playing 60 fps (the method takes around 16 ms) or 30 fps (the method takes around 33 ms) movies.

### Expected behavior

The host applications framerate should not be affected by the movies fps. 

### Actual behavior

The framerate drops to the fps of the movie.

### Log file

I can only provide you with a logfile of the sdl example where you can see the timing but I don't think this will have some value.

### Sample files

any video file with 60fps or 30fps or 25fps to see the different timings

**Comment by wm4** [comment]
In audio timing mode, the draw call may block up to 50ms - it will first draw the frame, then sleep, then return. This is supposed to improve timing/performance. It means if the video has >=20 fps, the framerate will be limited to it.

There'll probably be a better solution in the mid-range, but for now you can only work it around.

One possibility would be to not call the draw call until 50ms later. Probably not too reliable, but could work.

Another is enabling display-sync mode, which will disable waiting, and which will make the API ask you draw a new frame every frame. You need to set the video-sync and display-fps properties for this to work.

**Comment by gunnarmarten** [comment]
I tested with enabled display-sync mode and indeed my host application now runs at 60 fps. In the logs I occasionally see "adjusting display FPS to a value closer to..." and a bit later "switching back to assuming display fps = 60.002 Hz".
I think it shows up during some heavier transitions when the framerate drops under 60 fps.

**Comment by wm4** [comment]
That's possible - it's also possible that it keeps switching between two very close values (which should probably be fixed).

**Comment by Boscop** [comment]
Any update on this? :)

**Comment by wm4** [comment]
Update on what exactly?

**Comment by gunnarmarten** [comment]
Just saw commit 0b23264 of the pull request #5635.
That sounds like the feature I was waiting for. I will test that soon.
So instead of enabling display-sync mode and set the `display-fps`, is setting the `video-timing-offset` to 0 the better solution? Or has this new option other drawbacks?

Maybe we should reference this issue then.

**Comment by Akemi** [comment]
fixed.

**Comment by wm4** [comment]
You should preferably use the render API + MPV_RENDER_PARAM_BLOCK_FOR_TARGET_TIME, which allows to do some of the timing yourself.
