### ISSUE TITLE
"Close" currently loaded media file

### ISSUE THREAD

**Issue by smarrocco** [mpv-player/mpv#4240]
I'm using mpv via vb.net as an embedded player and using commands such as
DoMpvCommand("loadfile",...
to load and display media files.

Is there a similiar command for "closing" an already loaded file? I'd like to restore the player to the same state it was in before the file was loaded (blank), preferably without having to load a blank media file, throw away the current instance of the player or some such workaround. Possible?

**Comment by wm4** [comment]
`stop`

Keep in mind that it's async.
