### ISSUE TITLE
no ('libass >= 0.12.1' not found)

### ISSUE THREAD

**Issue by plexigras** [mpv-player/mpv#4245]
### mpv version and platform

git master

If you're not using git master or the latest release, update.

### Reproduction steps

```
pacaur -S mpv-git
```

### Expected behavior

install git master

### Actual behavior

```
Checking for SSA/ASS support                                      : no ('libass >= 0.12.1' not found) 
Unable to find development files for libass, or the version found is too old. Aborting. If you really mean to compile without libass support use --disable-libass.
```

### Libass is installed

```
$ pacman -Qi libass

Repository      : extra
Name            : libass
Version         : 0.13.4-1
Description     : A portable library for SSA/ASS subtitles rendering
Architecture    : x86_64
URL             : https://github.com/libass/libass/
Licenses        : BSD
Groups          : None
Provides        : libass.so=5-64
Depends On      : fribidi  fontconfig
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 88.38 KiB
Installed Size  : 262.00 KiB
Packager        : Maxime Gauduin <alucryd@archlinux.org>
Build Date      : Sun 09 Oct 2016 08:23:55 PM CEST
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

**Comment by CounterPillow** [comment]
You're confusing libsass with libass.

**Comment by plexigras** [comment]
ohh thanks @CounterPillow maybe updateing libass which i have installed(v0.13.4-1) will fix this

**Comment by CounterPillow** [comment]
0.13.4 is new enough. If there is an issue, it's on your end, because I'm successfully using the mpv-git AUR package right now.

**Comment by rossy** [comment]
FWIW libass is the first pkg-config package that mpv's configure script tries to look for, so if it doesn't work, it could indicate a problem with pkg-config.

**Comment by plexigras** [comment]
ok thats good to know.

you got any ideas what i could be doing wrong or how to fix this?

**Comment by plexigras** [comment]
@rossy i thought it might be something with that since i somehow messed stuff up with pkg-config
 
but its not that `/usr/lib/pkgconfig/libass.pc` is missing its definitely there and it contains

```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libass
Description: LibASS is an SSA/ASS subtitles rendering library
Version: 0.13.4
Requires: 
Requires.private: harfbuzz >= 0.9.5, fontconfig >= 2.10.92, fribidi >= 0.19.0, freetype2 >= 9.10.3
Libs: -L${libdir} -lass 
Libs.private: -lm
Cflags: -I${includedir}
```

**Comment by rossy** [comment]
What's the result of ``pkg-config libass --libs``?

Also a pastebin of build/config.log could help narrow this issue down.

**Comment by plexigras** [comment]
it dosen't return mutch
```
$ pkg-config libass --libs

-lass
```

**Comment by rossy** [comment]
That looks correct. What about mpv's ``build/config.log``?

**Comment by plexigras** [comment]
#### build/config.log

https://gist.github.com/27ceb7cd8a7a229a1106e732fad69745

**Comment by plexigras** [comment]
@rossy thanks looking at build/config.log fixed it
