### ISSUE TITLE
OSX - full-screen mode - "fake" mode disapeared?

### ISSUE THREAD

**Issue by zohozer** [mpv-player/mpv#4253]
### mpv version and platform
mpv version 2017-Feb-12 21:41 downloaded from https://laboratory.stolendata.net/~djinn/mpv_osx/

OSX 10.11.6

### Reproduction steps

When I'm opening a file in full-screen mode, MPV enters into the Native full-screen mode of OSX, which I don't want, but instead of this I need to open in full-screen fake mode or how it is called. I had this option before into older build, but for some reason seems that mode has been replaced and I can't find any option to switch the FS behavior back to the "Fake" mode.

Please help to restore the old "Fake" full-screen mode for OSX.

**Comment by Akemi** [comment]
at least take a minute and try to use the the search of the issue tracker. #4014
