### ISSUE TITLE
mpv stopped working

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#4254]
### mpv version and platform
076116a0e - Win10-x64

### Expected behavior
Plays video

### Actual behavior
mpv stopped working

### Log file
```
[sub/ass] Failed to process glyph outline!
```
seem like libass's rendering bug I guess. Switch off the sub does not make mpv hang.

### Sample files
https://0x0.st/ttL.mkv

**Comment by wm4** [comment]
Well, it keeps working here...

**Comment by shinchiro** [comment]
extracting sub and remux it again works though. Not sure why this happen

**Comment by shinchiro** [comment]
Looks like it's not always the case. This time with different file, mpv stopped working on 3:20 minutes.
File: https://openload.co/f/VUUWMWBYs2o/file_390388_%28f66f1497%29.7z 
Log: https://0x0.st/thU.7z

What already do:

- Playing on Win10 - NOT Work
- Playing with other Win10 pc - NOT Work
- Compile libass with fontconfig instead of DirectWrite - NOT Work
- Playing on Linux - Work
- Playing on Linux with mpv.exe under Wine - Work
- Mux the sub+fonts with other video & play - Work

**Comment by shinchiro** [comment]
Oh well, seems it already fixed somewhere else
