### ISSUE TITLE
Directory-specific mpv.conf applied to subdirectories.

### ISSUE THREAD

**Issue by ntasos** [mpv-player/mpv#4256]
I would like files in a specific directory, including subdirectories, to use different options.
Right now this is only possible by placing a mpv.conf next to every single file.
Maybe a profile that uses path as a parameter would be more convenient.

**Comment by wm4** [comment]
I don't think this will happen. You could easily implement something very similar with a Lua script (or even autoprofiles.lua).

**Comment by ntasos** [comment]
So what should I set in "profile-desc" using autoprofiles.lua ?

**Comment by Hrxn** [comment]
What about `--use-filedir-conf`? Should enable directory-specific configuration files, doesn't it?

**Comment by ntasos** [comment]
> What about --use-filedir-conf? Should enable directory-specific configuration files, doesn't it?

I already use this option but what I want is to have a mpv.conf inside  _/home/user/videos_   and  files inside  _/home/user/videos/othervideos_  to also use this conf.

Using autoprofiles.lua with profile-desc=cond:p.path>"/home/user/videos" does exactly what I want.
Thanks for the help.

**Comment by Hrxn** [comment]
`apply-profile` from within the .conf of a sub-dir?

**Comment by wm4** [comment]
> profile-desc=cond:p.path>"/home/user/videos"

It doesn't sound like it would do anything useful. You probably want to use some sort of startswith string function (which Lua doesn't define, but should be easy to write yourself, or see e.g.: http://stackoverflow.com/questions/22831701/lua-read-beginning-of-a-string

**Comment by ntasos** [comment]
It seems my approach with autoprofiles.lua had trouble when playing files from command-line without the full path.
So I created a Lua script as wm4 instructed. Here it is if anyone is interested:
[https://gist.github.com/ntasos/d2fc69ad456177a968a1bc1964de422c#file-directory_options-lua](url)

**Comment by wm4** [comment]
There's an utils.join_path helper function which could slightly simplify your patch.

**Comment by ntasos** [comment]
> There's an utils.join_path helper function which could slightly simplify your patch.

Quite useful, thanks.
It still leaves me with problem when playing files one directory up(or more):
`mpv ../../something/video.mkv`
But it's working good enough for now.
