### ISSUE TITLE
Request: Sequential (relatively synchronous) command list for a single input key

### ISSUE THREAD

**Issue by AndydeCleyre** [mpv-player/mpv#4258]
`0.24.0`, Arch Linux

My case is subtitle fetching. This requires first fetching the subs, then applying them. The best possible solution is to press one key, and then another:

```
S run "subberthehut" "-nfs" "${path}"
R rescan_external_files reselect
```

But it would be nice to have something similar to:

```
S run "subberthehut" "-nfs" "${path}"; rescan_external_files reselect
```

except making sure not to run the second command before the first one finishes.

The above one-liner will "work" if you tap the key twice; first time downloads and then rescans too early, second time starts downloading again and immediately rescans, picking up the first-downloaded file just before it's overwritten).

**Comment by wm4** [comment]
They're already sequential, just that `run` doesn't wait for the process to terminate.

But I think you'd be better off using a lua script anyway (there are a bunch for subtitle downloading linked on the wiki).
