### ISSUE TITLE
Can't build mpv with 'opengl' and 'vdpau' without 'x'

### ISSUE THREAD

**Issue by DmitryHetman** [mpv-player/mpv#4261]
### mpv version and platform
Lastest, Gentoo GNU/Linux.
If you're not using git master or the latest release, update.

### Reproduction steps
emerge -av mpv
### Expected behavior
Build and install mpv without X support ( on wayland)
### Actual behavior
Opengl have X in dependency
### Log file

Make a log file made with -v o
![wayland-screenshot](https://cloud.githubusercontent.com/assets/18743742/24165702/05e8bc9a-0e69-11e7-918c-29b2884d79b5.png)
r --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by CounterPillow** [comment]
vdpau only works on X11 afaik

complain about it to nvidia

**Comment by DmitryHetman** [comment]
How about opengl?

**Comment by CounterPillow** [comment]
OpenGL should work fine on wayland, if emerge doesn't let you build it that way then that's a Gentoo issue, not an mpv issue.

**Comment by DmitryHetman** [comment]
I'll try to change ebuild and see if it works.

**Comment by wm4** [comment]
I assume this worked.
