### ISSUE TITLE
Freezes when playing 144FPS video (on 144Hz monitor)

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#4263]
### mpv version and platform
0.24.0-git-0f1afc6ba, Windows 7 SP1
### Reproduction steps
Download and extract the sample video (98.7MB)
Run cmd
mpv --log-file=output.txt [MMD艦これ]時雨でGirls　144FPS-sm26578448.mp4
### Expected behavior
Smooth playback.
### Actual behavior
Sometimes drops frames (not always in the same timecodes), CPU usage spikes from ~25-35% to 100% and the entire OS stops reacting (mouse doesn't move either) for about 1.5-3 seconds. Cmd states the amount of dropped frames.
### Log file
http://pastebin.com/shjYDMGx
### Sample files
https://u.nya.is/bpxaux.zip
https://aww.moe/qiad8o.mp4
https://u.nya.is/xyxsfl.mp4

**Comment by wm4** [comment]
No idea what could cause this.

Trying to download the file leads to server error 500.

**Comment by UserNaem** [comment]
I uploaded another sample to other file hosting services.
Try using a browser, some of these file hosting services seem to require captcha for some reason.

**Comment by wm4** [comment]
Sample works well here. It really seems to be 144fps.

**Comment by UserNaem** [comment]
> works well here

Well that doesn't help me much. Should I try enabling DXVA2 to avoid potential stutter due to weak CPU? VLC seems to play the video fine with DXVA2 enabled.

**Comment by wm4** [comment]
You say that your PC freezes, which doesn't have anything to do with performance at all. (Unless the Windows scheduler is unexpectedly bad...)

**Comment by UserNaem** [comment]
Added this to mpv.conf:
vo=opengl
opengl-backend=angle
hwdec=auto
CPU usage dropped to ~2.5-6% average, but freezes are still happening randomly.
VLC and MPC-HC both seem to work fine with DXVA and without DXVA, so it's unlikely to be an issue with hardware or OS.

**Comment by wm4** [comment]
Maybe try `video-sync=display-resample`. No idea if this will work better or worse.

**Comment by UserNaem** [comment]
Now it often hangs somewhere between 00:00:500 and 00:02, then hangs again once or twice in the next 10-15 seconds, then doesn't seem to hang anymore.

**Comment by Hrxn** [comment]
And other players don't freeze at all? Absolutely nothing?

Very unusual. Like if OpenGL is semi-broken, if this can be achieved at all.
Other OpenGL applications  to test?

**Comment by wm4** [comment]
He isn't using OpenGL.

**Comment by Jj0YzL5nvJ** [comment]
I have a VG248QE.

[mpv git-55834d70e OpenGL](http://sprunge.us/XifR), CPU usage: 28-45% and drops=5

[mpv git-a993a871e OpenGL](http://sprunge.us/Qjhc), CPU usage: 29-46% and drops=6

[mpv git-a993a871e OpenGL+VDPAU](http://sprunge.us/eKKi),  CPU usage: 7-9% and many drops...
```
AV: 00:00:04 / 00:01:31 (4%) A-V:  0.500 Dropped: 572
AV: 00:01:31 / 00:01:31 (99%) A-V:  0.000 Dropped: 12191
```

[mpv git-a993a871e VDPAU only](http://sprunge.us/XeUN),  CPU usage: 7-9% and many drops...?
```
AV: 00:00:04 / 00:01:31 (4%) A-V:  0.497
AV: 00:01:31 / 00:01:31 (99%) A-V:  0.000
```

The conclusion is... I need a new PC T.T

**Comment by Jj0YzL5nvJ** [comment]
No freezes for me, only insane frame drops with VDPAU. But that is a hardware limitation (UVD 2.2).

The shader cache of NVIDIA drivers can cause many weird errors in certain emulators, such as ePSXe OpenGL plugins.
@UserNaem, try disabling the shader cache just for testing.

**Comment by Hrxn** [comment]
I doubt that OP will get very far with VDPAU on Windows..

**Comment by Hrxn** [comment]
> He isn't using OpenGL.

Yes, but ANGLE? So maybe something on the translation side?

**Comment by Jj0YzL5nvJ** [comment]
Naturally I can't test DXVA, so I used an "equivalent".
I think is shader cache fault.

**Comment by UserNaem** [comment]
How to disable shader cache? I searched in mpv's manual, couldn't find anything about it, only disable shaders entirely.
Tried this:
```
vo=opengl
opengl-backend=angle
hwdec=dxva2
vo-direct3d-disable-shaders
```
Doesn't seem to affect the frequency and severity of freezes.

I also tried enabling G-Sync and noticed something weird.
When G-Sync is enabled for both windowed and fullscreen applications, mpv almost doesn't freeze at all during 144fps video playback as long as its window is active. If I switch to any other window it freezes "as normal" and may freeze immediately upon switching off the mpv window.
Normally I have G-Sync set to fullscreen only because some applications don't work well with it.

**Comment by Jj0YzL5nvJ** [comment]
Disable shader cache in NVIDIA control panel, not in mpv.

**Comment by UserNaem** [comment]
Found it, but it doesn't seem to affect anything.

**Comment by Jj0YzL5nvJ** [comment]
So that was not it...

Try with:
`--no-config --no-border --vo=direct3d --hwdec=no`
and:
`--no-config --no-border --vo=opengl --hwdec=no`

**Comment by UserNaem** [comment]
> `--no-config --no-border --vo=direct3d --hwdec=no`

Near perfect, drops 1 frame every several seconds, no noticeable lags. Could this be because the videos' framerates are 144.001 FPS?

> `--no-config --no-border --vo=opengl --hwdec=no`

Freezes for 20+ frames every several seconds, occasionally freezes for 100+ frames.

It looks like using vo=direct3d solved the problem. Thanks a lot.

**Comment by wm4** [comment]
vo_direct3d will be removed.

Try to experiment with the ANGLE swapchain parameters instead.

**Comment by UserNaem** [comment]
```
hwdec=dxva2-copy
vo=opengl
opengl-backend=angle
angle-egl-windowing=yes
angle-renderer=d3d11
```

This seems to work, ~10-15% average CPU usage, sometimes dropping single frames like with vo=direct3d. But why would you want to remove direct3d?

**Comment by wm4** [comment]
It's probably dependent on the exact swapchain parameters. Maybe @rossy has ideas on this.

> But why would you want to remove direct3d?

Because it's lots of complex code for a not very good API (D3D9 - D3D11 is available everywhere on Windows now). With ANGLE, it's also completely redundant to vo_opengl.
