### ISSUE TITLE
Why my input.conf is not working?

### ISSUE THREAD

**Issue by frellzy12** [mpv-player/mpv#4267]
I want to control my volume with my mouse wheel so I created a txt file on my mpv folder named input.conf e the code to do this but is not working... anyone can help me?

![3243214213](https://cloud.githubusercontent.com/assets/26638669/24275571/1512dfe6-100f-11e7-8a6f-4fba51031228.PNG)

**Comment by rossy** [comment]
It looks like that file has a hidden .txt extension, so the real file name is input.conf.txt. mpv won't load this file. To make a real .conf file, go to Save As in Notepad and select "All Files (*.*)" from the dropdown before saving.

**Comment by frellzy12** [comment]
That was it, thanks mate
