### ISSUE TITLE
[osd/libass] PlayResX undefined, setting to XXX

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#4268]
### mpv version and platform
git-c345680 

### Reproduction steps
run from cli, always on 2nd line.
Is this info so useful that have to see all the time?
(- recently all the libva crap was removed, now something else..

**Comment by wm4** [comment]
It's probably a broken script, so a warning is deserved. We can't tell more from the info you provided.

**Comment by wiiaboo** [comment]
This is actually from the OSC, but I can't tell what commit caused it, but it's fixed in #4103.
