### ISSUE TITLE
mpv icon blurred under KDE Large Icons Task Switcher

### ISSUE THREAD

**Issue by xuzhao9** [mpv-player/mpv#4270]
### mpv version and platform
MPV 0.24.0-4.1
openSUSE Tumbleweed
If you're not using git master or the latest release, update.

### Reproduction steps

1. Set KDE task switcher theme to Large Icons
2. Open mpv 
3. Press Alt-tab to call out task switcher

### Expected behavior

Clear MPV application icon

### Actual behavior

Blurred MPV application icon
See screenshot: http://imgur.com/a/pqSFd

### Sample files

I think the problem is TOOLS/gen-x11-icon.sh file only packs 64x64 sized icons. The Large Icons task switcher requires at least 128x128 icon to avoid blurring.

**Comment by wm4** [comment]
> I think the problem is TOOLS/gen-x11-icon.sh file only packs 64x64 sized icons. The Large Icons task switcher requires at least 128x128 icon to avoid blurring.

Yes. We try to avoid adding huge files to git, and 128x128 would probably inflate it somewhat. So we probably won't add it. Maybe find out if there's a way to provide a svg file to KDE?

**Comment by xuzhao9** [comment]
@wm4 There is a mpv.svg file in hicolor/scalable/apps/mpv.svg. It seems KDE will always use the X11 window icon provided by the application, so I cannot make KDE use the svg file as icon. Is it possible to let MPV use the svg file as X11 window icon by default?

**Comment by wm4** [comment]
The protocol used for that supports bitmaps only.

**Comment by xuzhao9** [comment]
@wm4 Applications like emacs support an option of --no-bitmap-icon(http://www.gnu.org/software/emacs/manual/html_node/emacs/Icons-X.html), it helps me get rid of similar problem for emacs.

**Comment by xuzhao9** [comment]
@wm4 Also, may I ask what bitmap icon file mpv is using in X11? I tried remove the 32x32 icon png file and replace it with 128x128 one, but it does not work.

**Comment by wm4** [comment]
Custom, see TOOLS/gen-x11-icon.sh.

**Comment by rossy** [comment]
> Yes. We try to avoid adding huge files to git, and 128x128 would probably inflate it somewhat. So we probably won't add it.

I don't think this is a huge problem, at least not compared to what's required for Windows and macOS. mpv's git repository already has two 128x128 PNGs: one in each macOS .icns file. It also has four 512x512 PNGs and five 256x256 PNGs if you count the .icns and .ico files. Combined, the .icns and .ico files weigh 1.26 MB, but the X11 files (mpv-icon-8bit-*.png and x11_icon.bin) only weigh 16.6 KB.

If you set a resolution-independent image as the window icon in [Qt 5][1], it generates 16x16, 32x32, 64x64 and 128x128 icons, so maybe mpv should also use this list of sizes. Naively, I'd expect this to add about 40 KB to the repo (four times the size of the 64x64 icon, times two,) but GZip compression might make this better?

[1]: https://github.com/qt/qtbase/blob/4b62d7ba9e0e/src/plugins/platforms/xcb/qxcbwindow.cpp#L1514-L1517

**Comment by wm4** [comment]
Adding a 128x128 would be acceptable (would add 70KB without the PNG), but what if someone wants 256x256 and 512x512 icons in X11? This leads to nothing...

**Comment by CounterPillow** [comment]
Suggestion: Include only up to 128px resolution icons, and have higher resolution ones be generated by an optional build dependency which rasterises a vector file into the higher resolution icons.

This way, people who don't want to have more build time dependencies don't need them for mpv to work, but people who want higher res icons can get them easily without the mpv git repo having to contain any "large" files.

**Comment by wm4** [comment]
No, this is about avoiding more code too. Otherwise you could just add libavformat/libavcodec use to the X11 code to parse and use the Window .ico files.

**Comment by rossy** [comment]
> Adding a 128x128 would be acceptable (would add 70KB without the PNG), but what if someone wants 256x256 and 512x512 icons in X11? This leads to nothing...

To be fair, according to git-blame, that list of sizes (128x128, 64x64, 32x32 and 16x16) has been in Qt since Qt 5.0 (2012,) so it's probably stable. I'd hope if DEs want bigger icons, they'd try the ones in /usr/share/icons instead.

Also, even if x11_icon.bin gained 256x256 and 512x512 icons, it still wouldn't be as bloated as icon.icns, which has two of each (retina and non-retina) and separate ICC profiles for each PNG icon.

**Comment by xuzhao9** [comment]
I have created a pull request to fix this problem. Could you guys help review it? @rossy

**Comment by lachs0r** [comment]
A 128x128 icon was merged.
