### ISSUE TITLE
Possible to dynamically append new segments while playing?

### ISSUE THREAD

**Issue by FDMX2** [mpv-player/mpv#4278]
With [edl files](https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst) it is possible to play a list of segments as they were one single file (it is possible to jump around in the timeline).

Is it possible to dynamically append new segments, while this edl file plays via [IPC](https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst) ?

The behavior I want to achieve is the like the one of the HLS [event type](https://developer.apple.com/library/content/referencelibrary/GettingStarted/AboutHTTPLiveStreaming/about/about.html):

"Event playlists maintain the references to older media while gaining new references. This process results in an expanding media playlist. This type of playlist allows the players to navigate freely (backward and forward) from the beginning of the program."

**Comment by wm4** [comment]
Currently it's not possible, but in theory something along this could e implemented.

Why not use ffmpeg's HLS demuxer though?

**Comment by FDMX2** [comment]
What i have is a server providing media segments. I don't care where these segments (HLS stream, MPD stream, pipe, whatever ... ) come from and want to be able to play them with mpv with correct timeline.
EDL files are a solution, as long as the segment and the overall length is known. 
Thus it's not possible to use growing streams, with yet unknown length.

I tested your hint by doing the following:
I setup a minimal http server, serving an hls stream of type event. This way mpv handles the stream like it would handle any other hls event stream. 

The stream is played correctly and stops at the end of the event, but mpv acts like it would play an endless stream (no possibility to jump in the timeline).

Does mpv internally support this behavior (a growing timeline ) at all, or is it ffmpeg handling the stream like a pure livestream?

If mpv does not provide this feature yet, can you give me a hint where to start in order to create it?

**Comment by wm4** [comment]
> The stream is played correctly and stops at the end of the event, but mpv acts like it would play an endless stream (no possibility to jump in the timeline).

Does normal seeking work? If it has no duration, it won't show a usable seek bar on the OSC obviously. FFmpeg doesn't support updating duration mid-stream either. Playing new segments or seeking into them should still work to the degree possible.

> Does mpv internally support this behavior (a growing timeline ) at all,

For EDL? Currently not. In theory, implementing it wouldn't be so hard.

**Comment by wm4** [comment]
> If mpv does not provide this feature yet, can you give me a hint where to start in order to create it?

The implementation is in demuxer_timeline.c, with the parser being in demux_edl.c. This would somehow involve appending a new `struct segment` (or otherwise manipulating it, maybe updating the whole list?). There are some weird details with memory management involved.

I think you'd be much better off with some existing streaming protocol (like HLS or just appending .ts fragments into a unix pipe).

**Comment by FDMX2** [comment]
As I said the playing of new segments works, but seeking is not possible.

I will stick with the approach described with the minimal hls server serving an event type list which keeps growing. Once the Event (and with it the segment list) ends, I create and open a hls vod file, containing all the previous segments, with which seeking works. By keeping track of the current playtime the transition works good enough for my purpose.

Thanks for the support!
