### ISSUE TITLE
How to play HDR videos on a SDR screen?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#4285]
Do I have to setup something, or just play it?

### mpv version and platform

mpv git-aae0833fc6 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Mar 25 13:03:09 CST 2017
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4

**Comment by wiiaboo** [comment]
Just play it.

**Comment by Hrxn** [comment]
Yes, you can just play it, but you won't see "real" HDR. Only with a display capable of HDR.

**Comment by haasn** [comment]
(What happened to just trying it and seeing if it works?)

**Comment by wm4** [comment]
With HDR, nobody knows whether the result looks correct. This means an expert has to be consulted.

**Comment by JulianLai** [comment]
＠haasn It looks so dark.

**Comment by wiiaboo** [comment]
Try different values of [--target-brightness](https://mpv.io/manual/master/#options-target-brightness) and the next two options. There's no correct way of display HDR on SDR.

**Comment by JulianLai** [comment]
@wiiaboo The graphic looks brighter, but the subtitle still looks so dim.

**Comment by wiiaboo** [comment]
If this is an image-based subtitle format (DVD or BD), there's nothing you can do about it, other than OCR'ing them.

**Comment by wm4** [comment]
Do you have a sample for HDR + image subtitles?

**Comment by JulianLai** [comment]
@wiiaboo @wm4 Yes, it is the image-based subtitle, after I change it to the SRT format, the problem is solved. Thanks!

**Comment by wiiaboo** [comment]
Apparently if you use `blend-subtitles=yes` or `blend-subtitles=video` it'll use the same hdr-tone-mapping as the video, so that could make them brighter too.

**Comment by fhlfibh** [comment]
**JulianLai**

> Which target brightness do you guys prefer? 100 looks much better for me.

AFAIK, it's not a question of _prefer_. Every TV has its own peak brightness that can be measured with special tools (a colorimeter or something). That is if you want a "correct" tone-mapping.
Also it's possible to find some "average" brightness for some models in reviews, etc.
Otherwise you can set any target brightness you feel better with.

**Comment by haasn** [comment]
I guess image-based subtitles should probably be treated the same way as the OSD, and not like part of the video (unlike e.g. ASS subtitles)

**Comment by JulianLai** [comment]
By the way, can't I set the target-brightness with vaapi?
