### ISSUE TITLE
YUV limited 16-240 

### ISSUE THREAD

**Issue by age1988** [mpv-player/mpv#4288]
It seems in the code that mpv don't care about chroma limited range max value is 240 for tv->pc conversion
`  
        yuvlim =  { 16*s, 235*s, 16*s, 128*s },
        yuvfull = {  0*s, 255*s,  1*s, 128*s },  // 1 for symmetry around 128
  
 ...

    double ymul = (rgblev.max - rgblev.min) / (yuvlev.ymax - yuvlev.ymin);
    double cmul = (rgblev.max - rgblev.min) / (yuvlev.cmid - yuvlev.cmin) / 2;

    // Contrast scales the output value range (gain)
    ymul *= params->contrast;
    cmul *= params->contrast;

    for (int i = 0; i < 3; i++) {
        m->m[i][0] *= ymul;
        m->m[i][1] *= cmul;
        m->m[i][2] *= cmul;
        // Set c so that Y=umin,UV=cmid maps to RGB=min (black to black),
        // also add brightness offset (black lift)
        m->c[i] = rgblev.min - m->m[i][0] * yuvlev.ymin
                  - (m->m[i][1] + m->m[i][2]) * yuvlev.cmid
                  + params->brightness;
    }
}`

For y channel there aren't any issue but
I think this formula applied to uv channels maybe could be slighty better  :  ((x-128)/224)*255+128
Where 224=240-16 and pure grey 128  stay grey

Or maybe this gives  exactly the same result?

**Comment by haasn** [comment]
I don't see the issue. `yuvlim` sets the chroma range to 16-240, with 128 being the midpoint (neutral).

**Comment by fhlfibh** [comment]
Sorry for offtopic, but does mpv respect 10-bit limited range (95-685 AFAIK)?

**Comment by haasn** [comment]
mpv uses a scaling coefficient of:

```
double s = mp_get_csp_mul(colorspace, params->input_bits, params->texture_bits) / 255;
```

Where mp_get_csp_mul, for YUV, returns:
```
return (1LL << input_bits) / ((1LL << texture_bits) - 1.) * 255 / 256;
```

So assuming input_bits = texture_bits = 10, this would translate to:

```
s = 1024/1023 * (255 / 256) / 255
s = 1024/1023 / 256
```

Since the values are `16*s`, `128*s` and (by combination) `240*s`, and the maximum texture range is 1023 (corresponding to a value of 1.0), this translates to a result of:

```
min: 16 * 1024/256 = 64
mid: 128 * 1024/256 = 512
max: 240 * 1024/256 = 960
```

64-960 is the range quoted in the specs. I'm not sure where you got 95-685 from.

**Comment by fhlfibh** [comment]
95-685 are from google, I don't remember the specs numbers by heart. Anyway, my question was rather about logic "in general". Some time ago I tried to figure it out from the code, but failed. Thanks for the explanation!

**Comment by age1988** [comment]
Thanks for the reply.
That formula i've posted it is not so good.
This is probably the most precise formula
y = ((x-16)/219)*255
cb,cr = if (x>=128) then ((x - 128) / (240 - 128))  * (255 - 128) + 128  else ((x - 16) / (128 - 16)) * (128 )  

16 is perfectly mapped to 0
128 is perfectly mapped to 128
240 is perfectly mapped to 255

I've done a glsl for testing it

[tvpcHQ.zip](https://github.com/mpv-player/mpv/files/887833/tvpcHQ.zip)
