### ISSUE TITLE
hwdec-current property does not get updated when changing hwdec

### ISSUE THREAD

**Issue by romaincointepas** [mpv-player/mpv#4289]
### mpv version and platform

- Both 0.24 and master (`c68be80a63f100d1a55d8be7273c89734d6abeeb`)
- macOS Sierra 10.12.4

### Reproduction steps

Using the client API:
- observe `hwdec-current`
- init mpv with `--opengl-hwdec-interop=auto` and`--hwdec=auto`
- play a video
- I do get `hwdec-current` changed to `videotoolbox-copy` when playback starts
- a few seconds later, set `--hwdec=no` (can confirm it switched back to software decoding)

### Expected behavior

Receive a change in `hwdec-current` (should become `no`)

### Actual behavior

Not receiving any changes for `hwdec-current`.

---

Also, after doing `--hwdec=no`, switching back to `--hwdec=auto` again does switch back to videotoolbox (can confirm hardware decoding), but `hwdec-current` never changes.

**Comment by wm4** [comment]
Above commit should fix most of this.

**Comment by romaincointepas** [comment]
@wm4 Thanks!
