### ISSUE TITLE
mpv-git configure doesn't detect dvdnav library

### ISSUE THREAD

**Issue by simonbcn** [mpv-player/mpv#4290]
Arch Linux

I'm trying to compile mpv with dvd support (`--enable-dvdnav`) but it doesn't detect:
```
...
Checking for dvdread support                                      : disabled 
Checking for dvdnav support                                       : dvdread not found 
You manually enabled the feature 'dvdnav', but the autodetection check failed.
```

With `--enable-dvdread` compiles but it doesn't recognize the `dvd://` protocol:
```
$ mpv dvd:// --dvd-device="/dunehd/dvd1"
Playing: dvd://
No protocol handler found to open URL dvd://
The protocol is either unsupported, or was disabled at compile-time.
```

Both libraries are installed:
```
libdvdnav 5.0.3-1
libdvdread 5.0.4-1
```

**Comment by wiiaboo** [comment]
Add `--enable-dvdread`, it's disabled by default.

**Comment by simonbcn** [comment]
@wiiaboo, please re-read my comment (_I have edited it_).

**Comment by wm4** [comment]
You need to enable dvdread too to get dvdnav. If that doesn't work, post build/config.log.

**Comment by simonbcn** [comment]
ok, I got it but I don't understand this configuration: 
`mpv` doesn't compile with `dvdnav` alone, it needs `dvdread`   
and   
`mpv` compiles with `dvdread` alone but it is useless to read dvd.

Why not put a single option that is something like `--enable-dvd` and it detects both libraries?
