### ISSUE TITLE
How to catch keystrokes (e.g. Ctrl+C) in libmpv? 

### ISSUE THREAD

**Issue by tmpsa** [mpv-player/mpv#4291]
My apologies if this is the wrong forum, or the question is trivial.
As it is now, the console (on a non-X linux system) is completely locked out when libmpv runs.
Is it possible to set up libmpv (preferably with calls to the API) so that certain keystrokes (such as Ctrl+C) on the console are detected, resulting in some kind of callback?

**Comment by wm4** [comment]
Using the opengl-cb API for rendering is preferred, and that one doesn't create a window or take over any input.

Other than that, the only way is to disable input (if it's possible, depends on the OS), or use ``script-message-to`` to get a client message when a key is hit (this works with non-scripts like libmpv's mpv_handle too).

**Comment by tmpsa** [comment]
Sorry, I don't quite understand the answer. I'm using the API defined in mpv\lib\include\client.h, not any opengl-cb API.
I presume that you mean calling mpv_command(ctx, "script-message-to <something>")
but I can't figure out what that <something> then should be to trap e.g. Ctrl+C.
The manual isn't clear on this.  An example would be much appreciated.

**Comment by wm4** [comment]
Provide an input.conf that has such a binding.

**Comment by wm4** [comment]
Also there are general examples here https://github.com/mpv-player/mpv-examples/tree/master/libmpv
