### ISSUE TITLE
How to imitate efficiently MPC-HC default sub font?

### ISSUE THREAD

**Issue by Heimdallx** [mpv-player/mpv#4298]
Hi,

Sorry to borrow but I'm so used to MPC, I can't stop to change my mpv.conf file to find a similar Arial font, unfortunately I can't find the same border and shadow depth, could someone help me with that?

In MPC, I use the default Arial Bold 18, "Outline" border style with 2 as "Width" value and 3 as "Shadow" value. I have no idea what it's equivalent in mpv.

**Comment by kkanungo17** [comment]
sub-font='Arial Bold'
sub-font-size=18
sub-border-size=2
sub-shadow-offset=3

Add these lines to mpv.conf.

**Comment by Heimdallx** [comment]
http://imgbox.com/4Eksa3IX
http://imgbox.com/C40FZxDV

Thanks for your help, first pic is mpv, second is MPC-HC.
I will do some work to make it right, do you know how I can have the same kind of shadow, it seems to be the most difficult thing to copy.

**Comment by wiiaboo** [comment]
There's no sure way to make them exactly the same, last time I tried. MPC-HC and mpv use different subtitle renderers with also different font renderers.

**Comment by kkanungo17** [comment]
Try decreasing the shadow offset, increase font size and border size, and set sub-shadow-color=#00000000. I think we can make a close approximation, if not an exact match.

**Comment by Heimdallx** [comment]
Thanks again, I have an approximation, the Arial font is a little bit tighter, the shadow lighter but it will do the job! This is what I did if someone is interested: 
sub-font=Arial Bold
sub-font-size=42
sub-border-size=2
sub-shadow-offset=3
sub-shadow-color="#33000000"
sub-text-margin-y=36
sub-text-color="#ffffffff"
