### ISSUE TITLE
Add support to use only one instance of mpv

### ISSUE THREAD

**Issue by gperezmz** [mpv-player/mpv#43]
Maybe I'm just lacking of reading comprehension, but I can't see a way to achieve this on the man page. Is it possible to make an _option_ to use the same mpv instance to play files? Instead of having to close one first and then open another one.

I know you can achieve this with an input file and `loadfile PATH` but...

**Comment by MavropaliasG** [comment]
Wow what? I am so surprised this is not implemented? How??

**Comment by wm4** [comment]
Because the main developer of this software thinks the concept is excruciatingly stupid.

**Comment by MavropaliasG** [comment]
It clearly isn't @wm4 , in fact this would be the expected behavior of a video player. Why not even allow it as a configuration for people who don't think it's excruciatingly stupid?

**Comment by haasn** [comment]
> It clearly isn't @wm4 , in fact this would be the expected behavior of a video player. Why not even allow it as a configuration for people who don't think it's excruciatingly stupid?

I'm assuming you didn't read the thread and find the script that @wm4 went to the trouble of authoring, testing and publishing for this exact use case? Does that not cover your use case?

(FWIW I also think this sort of "detect other running instances and send commands to them" is extremely unexpected and stupid, borderline nonsensical behavior for a command line program. At best I could be convinced to only enable it in `pseudo-gui` mode)

**Comment by wm4** [comment]
Even for GUI programs, this kind of behavior is inconvenient and annoying. Why the hell would you not start a new program when I ask for a new program?

**Comment by fahri314** [comment]
## Single Instance

`mpv/scripts/single_instance.lua`

- Windows:

```lua
local mp = require 'mp'
local utils = require 'mp.utils'

function close_other_instances()
    local current_pid = utils.getpid()

    local process_list = utils.subprocess({
        args = { "tasklist", "/FI", "IMAGENAME eq mpv.exe" },
        cancellable = false
    })

    if process_list.status == 0 then
        for line in process_list.stdout:gmatch("[^\r\n]+") do
            local pid = line:match("mpv%.exe%s+%d+")
            if pid then
                pid = tonumber(pid:match("%d+"))
                if pid and pid ~= current_pid then
                    utils.subprocess({
                        args = { "taskkill", "/PID", tostring(pid), "/F" },
                        cancellable = false
                    })
                end
            end
        end
    end
end

mp.register_event("start-file", close_other_instances)
```

- Linux:

```lua
local mp = require 'mp'
local utils = require 'mp.utils'

function close_other_instances()
    local current_pid = utils.getpid()

    local process_list = utils.subprocess({
        args = { "pgrep", "-x", "mpv" },
        cancellable = false
    })

    if process_list.status == 0 then
        for pid in process_list.stdout:gmatch("%d+") do
            pid = tonumber(pid)
            if pid and pid ~= current_pid then
                utils.subprocess({
                    args = { "kill", tostring(pid) },
                    cancellable = false
                })
            end
        end
    end
end

mp.register_event("start-file", close_other_instances)
```

**Comment by Digita1Menace** [comment]
> Even for GUI programs, this kind of behavior is inconvenient and annoying. Why the hell would you not start a new program when I ask for a new program?

Because many programmers are stupified by the obvious.

**Comment by Digita1Menace** [comment]
> Because the main developer of this software thinks the concept is excruciatingly stupid.

WOW... is it that same ass clown who made VLC? That dude is PURE TRASH. People begged that fuktard to allow VLC to simply open up the next file in a directory FOR YEARS ans the maggot refused to impliment it.

**Comment by Digita1Menace** [comment]
> ## Single Instance
> 
> `mpv/scripts/single_instance.lua`
I'm going to have to try this because Mpv.Net [which allows 1 instance] has a couple annoying broken features as well.
Thanks.

**Comment by llyyr** [comment]
> WOW... is it that same ass clown who made VLC? That dude is PURE TRASH. People begged that fuktard to allow VLC to simply open up the next file in a directory FOR YEARS ans the maggot refused to impliment it.

If you pay me a billion dollars I'll implement this feature in mpv and VLC.

**Comment by Digita1Menace** [comment]
> > WOW... is it that same ass clown who made VLC? That dude is PURE TRASH. People begged that fuktard to allow VLC to simply open up the next file in a directory FOR YEARS ans the maggot refused to impliment it.
> 
> If you pay me a billion dollars I'll implement this feature in mpv and VLC.

LOL, yo couldn't pay me a billion to ever touch that POS player [shit LC] again..
