### ISSUE TITLE
Audio/Video desync if --start and --vf=<filter> is used if filter changes framerate

### ISSUE THREAD

**Issue by kokowang** [mpv-player/mpv#4300]
Version: Latest (HEAD) and Latest (Release 0.24) MacOS Sierra 10.12
In Terminal: mpv <videofile> --vf=vapoursynth=<frameinterpolationfilter> --start=1:00 -o file.mp4 
Video is ahead of audio, the further into the video that --start is specified, the worse the desync is; the rate seems to be about 1 second per 3 minutes. (If I do --start=1:00:00, the audio will be behind by about 20 seconds)
This happens with MVTools, SVPFlow, SVPFlow2, etc...

Audio desync does not worsen as video plays. Desync seems to be only effected by the value after --start, and remains about the same desync throughout the video.
There is no issue if --start is not specified.
There also is no issue if --vf does not change framerate.

**Comment by chainikdn** [comment]
usually 'hr-seek-framedrop=no' fixes audio desync

**Comment by wm4** [comment]
Are you sure the scripts preserve the timestamps properly? They'd have to set the frame durations in a way there's no drift after output.

**Comment by kokowang** [comment]
thanks. hr-seek-framedrop=no seems to have fixed it.

**Comment by wm4** [comment]
That is not the solution. Can I get a log or a sample file?

**Comment by kokowang** [comment]
I don't have mpv 0.24 installed on my laptop ATM. Desktop still has desync with 0.24
[log.txt](https://github.com/mpv-player/mpv/files/902955/log.txt)

**Comment by kokowang** [comment]
Here's another:
[test2.mp4.zip](https://github.com/mpv-player/mpv/files/903013/test2.mp4.zip)
[log.txt](https://github.com/mpv-player/mpv/files/903014/log.txt)

**Comment by wm4** [comment]
That test video is out of sync even when playing normally? I don't get it.

**Comment by wm4** [comment]
I guess you ran mpv in encoding mode, and that's the _output_. I want the source. But if it's a normal youtube encode, there's probably no particular problem anyway.

I assume the source script requires constant framerate input, and can't deal with PTS skips, which is what hr-seek framedrop does (to speed up seeking). So I guess `hr-seek-framedrop=no` is actually the right "solution" to work around the problem with the script.
