### ISSUE TITLE
[vo/opengl] retrieving framebuffer depth: OpenGL error INVALID_ENUM

### ISSUE THREAD

**Issue by diogo-gomes** [mpv-player/mpv#4304]
### mpv 0.24.0 @ Manjaro

When I play an youtube video throw GTK Youtube Viewer I get this error message:
`[vo/opengl] retrieving framebuffer depth: OpenGL error INVALID_ENUM.`

_The video works fine._

### Log file
[vo/opengl] Suspected software renderer or indirect context.
[vo/opengl] retrieving framebuffer depth: OpenGL error INVALID_ENUM.
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p

**Comment by CounterPillow** [comment]
According to @wm4 in [this issue comment](https://github.com/mpv-player/mpv/issues/4087#issuecomment-276033134)

>`[vo/opengl] retrieving framebuffer depth: OpenGL error INVALID_ENUM.`
>Ignore that part. It's harmless and always happens with Mesa. We don't know if it's their bug or our bug.

**Comment by wm4** [comment]
Yes, as the quote said, it's not sure whose bug it is. I should probably report it to Mesa and see what they say. The effect is that the mpv renderer will assume your display depth is 8, and dither to that depth.

> [vo/opengl] Suspected software renderer or indirect context.

That's a bit worse, but definitely doesn't have to do with mpv, but your drivers, and probably means you're using GL software rasterization.

**Comment by wm4** [comment]
What Mesa version are you using?

**Comment by diogo-gomes** [comment]
@wm4 
I'm using mesa  17.0.2-2.

**Comment by wm4** [comment]
Reported here, let's see what Mesa says: https://bugs.freedesktop.org/show_bug.cgi?id=100609

**Comment by montvid** [comment]
I got the same using the new ubuntu 18 lts with mesa hwdec=vaapi vo=opengl

> OpenGL version string: 3.0 Mesa 18.0.0-rc5

> [vo/opengl] retrieving framebuffer depth: OpenGL error INVALID_OPERATION.

**Comment by CounterPillow** [comment]
>vo=opengl

try reproducing with a git version of mpv, not the outdated one Ubuntu ships

**Comment by wm4** [comment]
It's even more weird that this was apparently explicitly fixed in 2010 (before we even used it), and they have a regression test to ensure it keeps working: https://bugs.freedesktop.org/show_bug.cgi?id=28551

Maybe I'm missing something.

**Comment by Russell-Jones** [comment]
@CounterPillow I've done this using mpv-build. I see the following
```
./mpv/build/mpv --hwdec=vaapi --vo=gpu somefile.mp4
 (+) Video --vid=1 (*) (h264 1280x720 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[vaapi] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
 (+) Video --vid=1 (*) (h264 1280x720 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
     Subs  --sid=1 (*) (eia_608)
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1280x720 yuv420p
AV: 00:00:19 / 00:02:18 (13%) A-V:  0.031 DS: 2.000/5
```
Context for the error from using `--msg-level=all=trace`
```
...
[vd] Opening decoder h264
[vd] Looking at hwdec h264-vaapi...
[vo/gpu] Loading hwdec driver 'vaapi-egl'
[vo/gpu/vaapi-egl] using VAAPI EGL interop
[vo/gpu/vaapi-egl] Trying to open a x11 VA display...
[vo/gpu/vaapi-egl/vaapi] libva: VA-API version 1.1.0
[vo/gpu/vaapi-egl/vaapi] libva: va_getDriverName() returns -1
[vo/gpu/vaapi-egl/vaapi] libva: User requested driver 'i965'
[vo/gpu/vaapi-egl/vaapi] libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
[vo/gpu/vaapi-egl/vaapi] libva: Found init function __vaDriverInit_1_1
[vaapi] libva: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[vo/gpu/vaapi-egl/vaapi] libva: va_openDriver() returns -1
[vo/gpu] Loading failed.
[vo/gpu] Loading hwdec driver 'drmprime-drm'
[vo/gpu/drmprime-drm] Failed to retrieve DRM fd from native display.
[vo/gpu] Loading failed.
...
```
The build doesn't seem to have any Wayland support. I've the following installed.
```
$ dpkg -l | grep wayland | sed -E 's/^[^ ]+ +([^ ]+) .+/\1/g'
freerdp2-wayland
kwayland-data
kwayland-integration:amd64
libglfw3-wayland:amd64
libkf5waylandclient5:amd64
libqt5waylandclient5:amd64
libqt5waylandcompositor5:amd64
libuwac0-0:amd64
libva-wayland2:amd64
libwayland-bin
libwayland-client0:amd64
libwayland-client0:i386
libwayland-cursor0:amd64
libwayland-cursor0:i386
libwayland-dev:amd64
libwayland-egl1:amd64
libwayland-egl1:i386
libwayland-egl1-mesa:amd64
libwayland-egl1-mesa:i386
libwayland-server0:amd64
libwayland-server0:i386
qtwayland5:amd64
qtwayland5-dev-tools
qtwayland5-doc
wayland-protocols
xwayland-hwe-18.04
```
I've added `libwayland-egl-backend-dev:amd64` and am retrying the configure/build.
