### ISSUE TITLE
macOS's brightness/volume OSD flickers while playing 10bit MKV file in fullscreen

### ISSUE THREAD

**Issue by nguyenhimself** [mpv-player/mpv#4306]
### mpv version and platform

mpv: stable 0.24.0
macOS Sierra 10.12.4

### Reproduction steps

1. Play a 10bit MKV file in fullscreen.
2. Change brightness or volume with MacBook's top-row buttons.
3. The brightness or volume OSD (which is transparent) fades in and fades out.

### Expected behavior

After reflecting changes, the brightness or volume OSD should fade out smoothly.

### Actual behavior

The brightness or volume OSD flickers while fading out.

### Log file

- [My log file.](https://www.dropbox.com/s/xcwq8ez1fszx60n/output.txt?dl=0)

### Sample files

- [A recording of the bug.](https://www.dropbox.com/s/604cvtrvzca695s/Record%20-%2010bit.mp4?dl=1\0)
- [A sample 10bit MKV file to reproduce this bug.](https://www.dropbox.com/s/2v0xyy624if8cgo/Sample%20-%2010bit.mp4?dl=1)

**Comment by Akemi** [comment]
probably duplicate of #3746. try with `--opengl-pbo=yes`.

**Comment by nguyenhimself** [comment]
Oh that was it. Thanks. I didn't search the issues carefully enough.
