### ISSUE TITLE
MPV Player skips live iptv .ts feeds in a matter of seconds

### ISSUE THREAD

**Issue by inglesuniversal** [mpv-player/mpv#4307]
### mpv version and platform

your latest release for Mac is giving me an issue that players like VLC or even kodi standard tv player cause.... 

If you're not using git master or the latest release, update.

### Reproduction steps

What happens is that once I drag and drop the m3u file with a list of IPTV channels listed with .TS at the end, the player DOES work and looks beautiful on my MacBook Air, however, about 20 seconds of playtime and the streams cuts and goes and grabs the next IPTV channel from the playlist.

Can you fix this issue... Kodi is way too confusing to manage something so simple, I am looking for a better software just mainly for IPTV (.ts) and (.m3u8) links
### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by Akemi** [comment]
closing for now since a lot changed in that department. we can reopen this if the problem still persists.
