### ISSUE TITLE
with --fs option, mpv should directly go fullscreen

### ISSUE THREAD

**Issue by m5d** [mpv-player/mpv#431]
I think that if --fs option (or the corresponding config entry) is specified, mpv should not first create a smaller window before going to fullscreen. I guess in X11, this can be achieved by changing the _x_,_y_, _height_ and _width_ values which are passed to `vo_x11_config_vo_window` in x11_common.c

**Comment by MostAwesomeDude** [comment]
Trivially reproducible with recent Awesome and mpv.

Note to the next person trying to solve this: I read through Awesome's atom-handling code and didn't see any obvious reason why this problem happens. I thus would suspect that the next likely culprit is Awesome's window-layout code, but I don't have the energy to do that right now.

I also read mpv's atom-handling code and didn't see any obvious wrongness, and I'm not sure where I'd search more on mpv's side.
