### ISSUE TITLE
Possible problem between mpc-qt and libmpv

### ISSUE THREAD

**Issue by luigino** [mpv-player/mpv#4311]
Using mpv 0.24 built against ffmpeg 3.2 on openSUSE_Leap_42.2 x86_64.

Built [mpc-qt](https://github.com/cmdrkotori/mpc-qt) a Qt front-end for libmpv.

When the app is idle, that is without any media playing (even paused), the CPU
usage skyrockets. The mpc-author is of the opinion this could be caused by a [bug
in libmpv](https://github.com/cmdrkotori/mpc-qt/issues/75).

I don't quite understand the problem, but see attached valgrind log.

[mpc-valgrind_full_024.zip](https://github.com/mpv-player/mpv/files/911469/mpc-valgrind_full_024.zip)

**Comment by wm4** [comment]
I can't reproduce this problem either, but I don't have pulseaudio.

The valgrind logs are useless.

Run mpc-qt under a debugger, and when the high CPU usage occurs, drop into the debugger with ctrl+c and see where you end up.

**Comment by luigino** [comment]
It looks like I end up [here](https://github.com/cmdrkotori/mpc-qt/blob/master/main.cpp#L39)  :grimacing:
[mpc-qt_gdb.zip](https://github.com/mpv-player/mpv/files/912674/mpc-qt_gdb.zip)

**Comment by wm4** [comment]
Run  `thread apply all backtrace` and resume again, then repeat - do that a bunch of times.

Please stop uploading single files as .zip.

**Comment by luigino** [comment]
> Run thread apply all backtrace and resume again, then repeat - do that a bunch of times.

Done and done.
[mpc-qt_gdb_threadall.log.txt](https://github.com/mpv-player/mpv/files/912969/mpc-qt_gdb_threadall.log.txt)

**Comment by wm4** [comment]
If you set a breakpoint on `ao_hotplug_get_device_list`, does it get constantly called again?

**Comment by luigino** [comment]
> If you set a breakpoint on ao_hotplug_get_device_list, does it get constantly called again?

It does look like: 
[mpc-qt_gdb_break_log.txt](https://github.com/mpv-player/mpv/files/913012/mpc-qt_gdb_break_log.txt)

**Comment by wm4** [comment]
Try running: `mpv --idle --script=TOOLS/lua/observe-all.lua`

Does it use CPU? Does it spam stuff (after the initial property dump)?

**Comment by luigino** [comment]
>Try running: mpv --idle --script=TOOLS/lua/observe-all.lua
> Does it use CPU?

Yes:
![mpv-observe-all lua](https://cloud.githubusercontent.com/assets/1450716/24909544/9c321f78-1ec4-11e7-8ba5-4a88f6a51047.jpg)

> Does it spam stuff (after the initial property dump)

Not that I could see.
[mpv-observe_all.lua.txt](https://github.com/mpv-player/mpv/files/913190/mpv-observe_all.lua.txt)

**Comment by wm4** [comment]
Not sure what your screenshot is supposed to show.

**Comment by luigino** [comment]
> Not sure what your screenshot is supposed to show.

CPU% for mpv and pulseaudio and possibly something else you'd want to know. I took it for completeness, if necessary.

**Comment by wm4** [comment]
So does mpv constantly use 1% CPU? Does pulseaudio stop using CPU if you quit mpv? etc.

Also, try again with mpc-qt, see if setting a breakpoint on `ao_hotplug_eventao_hotplug_event` makes the debugger stop on it very often, and if so, post a backtrace.

**Comment by luigino** [comment]
> So does mpv constantly use 1% CPU? Does pulseaudio stop using CPU if you quit mpv? etc.

More like > 80%. And yes, pulseaudio goes down to ~0% when I quit mpv launched with that script.

> Also, try again with mpc-qt, see if setting a breakpoint on ao_hotplug_eventao_hotplug_event makes the debugger stop on it very often, and if so, post a backtrace.

```
> gdb mpc-qt
(gdb) break ao_hotplug_eventao_hotplug_event
Function "ao_hotplug_eventao_hotplug_event" not defined.                                                              
Make breakpoint pending on future shared library load? (y or [n]) y                                                   
Breakpoint 1 (ao_hotplug_eventao_hotplug_event) pending.                                                              
(gdb) run                                                                                                             
Starting program: /usr/bin/mpc-qt                                                                                     
[Thread debugging using libthread_db enabled]                                                                         
Using host libthread_db library "/lib64/libthread_db.so.1".                                                           
[New Thread 0x7fffcdb88700 (LWP 14433)]                                                                               
[New Thread 0x7fffc2b9c700 (LWP 14434)]                                                                               
[New Thread 0x7fffb9601700 (LWP 14435)]                                                                               
```
It never stops.

**Comment by wm4** [comment]
> It never stops.

Is that because it can't set breakpoints on libmpv-internal functions or so?

**Comment by luigino** [comment]
> Is that because it can't set breakpoints on libmpv-internal functions or so?

No, that's because I was actually writing the function name twice as per previous comment :tired_face:

[mpc-qt-gdb_ao_hotplug_event.txt](https://github.com/mpv-player/mpv/files/913387/mpc-qt-gdb_ao_hotplug_event.txt)

**Comment by wm4** [comment]
So did the standalone `mpv` run eat significant amounts of CPU time or not?

Does the same (`ao_hotplug_eventao_hotplug_event` being called often) happen in the standalone instance?

**Comment by luigino** [comment]
> So did the standalone mpv run eat significant amounts of CPU time or not?

As per linked screenshot, when launched with that .lua script, it did. Otherwise no.

> Does the same (ao_hotplug_eventao_hotplug_event being called often) happen in the standalone instance?

Only with `mpv --idle --script=TOOLS/lua/observe-all.lua`, otherwise never. See attached log:
[mpv-gdb_ao_hotplug_event.txt](https://github.com/mpv-player/mpv/files/913556/mpv-gdb_ao_hotplug_event.txt)

**Comment by wm4** [comment]
Still don't know what's wrong. Try this patch for starters, run it with that lua script: http://sprunge.us/iHCA

**Comment by luigino** [comment]
There you are:
[mpv-024-patched-observe_all.lua.txt](https://github.com/mpv-player/mpv/files/913801/mpv-024-patched-observe_all.lua.txt)

**Comment by wm4** [comment]
So, it looks to me as if PulseAudio is spamming "new device" events. mpv reacts by updating the device list.

Try this patch: http://sprunge.us/aXBK

**Comment by luigino** [comment]
No change.

**Comment by wm4** [comment]
So I'd say PulseAudio is spamming us with device notifications, and it happens even when we don't even retrieve the device list (i.e. we merely have the event list subscribed). I can't exclude that there's a bug in ao_pulse.c, but at least the rest of the player seems to be fine here.

One "strange" thing is that it seems to spend most of the CPU time listing _ALSA_ devices, but that's because device listing includes devices from all backends, not just ALSA, and relists all devices if Pulse sends a notification.

**Comment by wm4** [comment]
One last patch to test: http://sprunge.us/DCAA (behavior shouldn't change, gives more output)

**Comment by luigino** [comment]
[mpv-024-3rdpatch_observe-all_lua.txt](https://github.com/mpv-player/mpv/files/914174/mpv-024-3rdpatch_observe-all_lua.txt)

**Comment by wm4** [comment]
OK, I'd say report it as a Pulse bug. We're getting constant callbacks from `pa_context_set_subscribe_callback`.

Might be worth testing with all audio outputs disabled at compile time (or in ao.c) to see whether getting the device list triggers it.

**Comment by luigino** [comment]
> OK, I'd say report it as a Pulse bug. We're getting constant callbacks from pa_context_set_subscribe_callback.

I wonder if it's some quirk related to the openSUSE pulseaudio (I've just tried its experimental 10.0 package with no change), either in the form of a patch or a default configuration.

On the other hand, I've confronted the installed package list with a person in the mpc-qt bug thread who has no problems, not even with the observe-all.lua script and the only differences are in Qt, KDE and xorg/Mesa.

> Might be worth testing with all audio outputs disabled at compile time (or in ao.c) to see whether getting the device list triggers it.

Thing is I already build in a VM on OBS which I doubt has any audio output enabled.
In case you wanted to see the build log, it's [here](https://github.com/mpv-player/mpv/files/914264/mpv-024_3rdpatch_buildlog.txt).

Will also check the differences with the other person's build.

**Comment by wm4** [comment]
I have no idea what that log is, but I see that it builds at least ao_alsa.

**Comment by luigino** [comment]
For some reason the PA event swamping problem (and consequent CPU% consumption) disappeared after removing the --enable-openal switch from the build.

How are the two things related?

**Comment by wm4** [comment]
I don't know. Go find out?

**Comment by luigino** [comment]
It's confusing. If I build mpv against openal and then set the latter to use alsa, there is no problem.
But if I have openal use pulse and build mpv against alsa and not pulseaudio, there is no event storm either.

I tried having a look at how mpv talks to openal and how openal talks to pulse, but I'm afraid it's beyond me.

**Comment by luigino** [comment]
openal people tentatively recommend the [attached patch](https://github.com/mpv-player/mpv/files/917246/mpv-pulse_mask.patch.txt), which seems to solve the problem for me.

**Comment by luigino** [comment]
With https://github.com/mpv-player/mpv/commit/f34de634501f0fd95ac6ea26b3ed643183222165 the problem seems to have disappeared.
