### ISSUE TITLE
Current time is wrong (offset of total time)

### ISSUE THREAD

**Issue by lightonflux** [mpv-player/mpv#4314]
### mpv version and platform
Debian 9 (testing)

mpv 0.24.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4-1

### Reproduction steps

Play mp4 (m4a) with broken duration information.

### Expected behavior

Display actual duration and play length.

E.g. VLC displays the right play time but hints an error at the terminal:

    Warning: data is not aligned! This can lead to a speedloss

[Probably related](https://superuser.com/questions/728795/new-ffmpeg-swscaler-0xa314080-warning-data-is-not-aligned-this-can-lead#799987)

### Actual behavior

mpv starts counting at the total play time then counts onwards. So if a file is 1h long second 1 is displayed as 60:01 not 00:01.

![bildschirmfoto von 2017-04-11 20-21-52](https://cloud.githubusercontent.com/assets/1377943/24924332/b753c966-1ef4-11e7-99b8-472b084eeddf.png)

### Log file
Log: https://paste.ubuntu.com/24362357/

**Comment by wiiaboo** [comment]
An actual sample file would probably be useful.

**Comment by lightonflux** [comment]
Still uploading. I have veeeery slow upstream speed.

**Comment by wm4** [comment]
`--demuxer-lavf-probe-info=yes` probably "fixes" it. If so, I'd call it a FFmpeg bug.

**Comment by lightonflux** [comment]
[Link](https://0x0.st/wGd.m4a)

>       --demuxer-lavf-probe-info=yes
Tried the option but it is not recognised. (By both `mpv` and `ffmpeg`).
