### ISSUE TITLE
Crash when opening a file.

### ISSUE THREAD

**Issue by DeadSix27** [mpv-player/mpv#4315]
Version: https://github.com/mpv-player/mpv/commit/7497b633e9ffbc48cda46215b2d5b1194a3b3a5f (Compiled with GCC 6.3.0 mingw)
OS: Win8.1 64bit 
Crashes when opening a video file, I guess it has something to do with:

https://github.com/mpv-player/mpv/commit/7497b633e9ffbc48cda46215b2d5b1194a3b3a5f.diff

in the newest commit since the one right before that works fine.
(Not sure if this is a obvious issue.)
The log doesn't output anything out of the ordinary, if you still want it tell me.
(I don't exactly know how to use gdb or VS to debug the build, if you need that I'd need some instructions.)

**Comment by Warblefly** [comment]
Same for me on Windows 10 64 bit, compiled with GCC 6.3.1 mingw. Crash is error 0xc0000374 in RtlNonEmptyDirectoryReparsePointAllowed() in ntdll.dll

I have not yet had a chance to test this commit-by-commit and am not by the computer right now to send the full trace. Will do so in the morning.

**Comment by wm4** [comment]
Can't reproduce. Is anything specific needed?

**Comment by Warblefly** [comment]
I confirm on my Windows 10 Insider Build 16170 that the error occurs at 7497b63. Building from the master tree immediately before this commit runs perfectly.

On the faulty build, it is possible to start mpv with the `mpv --idle` command; but as soon as a file is dropped onto the opened player window, the crash happens.

Here is the gdb backtrace, as far as it gets:
```
#0  0x00007ffaab6d5c1f in ntdll!RtlIsNonEmptyDirectoryReparsePointAllowed () from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ffaab6dc2fa in ntdll!RtlpNtSetValueKey () from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ffaab685012 in ntdll!RtlIsPartialPlaceholderFileInfo () from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007ffaab698e4c in ntdll!memset () from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x00007ffaaaf6998c in msvcrt!free () from C:\WINDOWS\System32\msvcrt.dll
#5  0x0000000000c9cc55 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by wm4** [comment]
Staring at the code again, it was pretty obvious. But I didn't test this again.

**Comment by Warblefly** [comment]
I'm building it now.

**Comment by Warblefly** [comment]
Problem is cured on my system. Thank you for fixing this!

**Comment by DeadSix27** [comment]
@wm4 Fixed for me too, thanks.
