### ISSUE TITLE
Please make GPU device for hardware accelerated decode selectable

### ISSUE THREAD

**Issue by cwbsw** [mpv-player/mpv#4320]
Most people have two GPUs, a Intel integrated GPU, and a AMD/NVIDIA discrete GPU. The decoding capacity of them are different. For example, the latest AMD Polaris GPUs don't support VP9 codec, and GTX 970/980 don't support HEVC codec. If mpv could support integrated GPU decoding, users would have more choices, especially useful for those who have both latest Kabylake CPU and old discrete GPU.

**Comment by fhlfibh** [comment]
For Intel IGP and old Nvidia GPU you might want to use `--vaapi-copy`

**Comment by cwbsw** [comment]
However, `vaapi-copy` is just Linux only. I think it should be possible to support Intel integrated GPU by `d3d11va-copy` on Windows 10.

**Comment by DmitryHetman** [comment]
Why support malware?

**Comment by Hrxn** [comment]
What malware?
Sure this is the right issue?

**Comment by JulianLai** [comment]
@fhlfibh Does vaapi-copy work for AMD GPU?

**Comment by fhlfibh** [comment]
> @fhlfibh Does vaapi-copy work for AMD GPU?

I never had an ATI/AMD card, so I don't know for sure.
Afaik, it should work, in theory (but may be somehow tricky to set up in practice).

**Comment by gavin--** [comment]
You said most people have two GPUs.  Where did you get this information?  I doubt this is a fact.

**Comment by Hrxn** [comment]
I think it's meant like internal GPU (like Intel Core CPUs, etc.) plus dedicated GPU, connected via PCI(e).

**Comment by ArchangeGabriel** [comment]
Yes, but I, for one, have never seen any numbers about how spread are those setup. There still a lot of laptops with Intel only. And I think they’re still some Intel procs without GPU. Not sure about AMD world.
