### ISSUE TITLE
A/V Desync on seek via OSC but not via arrow keys? (mpvpipe)

### ISSUE THREAD

**Issue by DeadSix27** [mpv-player/mpv#4321]
### mpv version and platform
Version: https://github.com/mpv-player/mpv/commit/3709ce6718bed8a113d141cdf5e8198f22f3c5f7
Platform: Windows 8.1 64-bit

## tl;dr
Skipping via the OSC produces a a/v desync when playing a video with SVP+vapoursynth+mpv
Skipping via arrow keys does not.
The fact it does desync the audio and video via keys made me wonder whether its an issue inside mpv and not svp but I am still unsure, either way, I reported it now.

Subtitles are still in sync with the audio too (which I  assume is because only the video goes through the processing)

### Reproduction steps and actual behavior
1. Install SVP4,
2. put Python 3.6-embeddable into the mpv folder.

3. Have the default config beside these options:
```
vo=opengl
opengl-pbo
hwdec=dxva2-copy
input-ipc-server=mpvpipe
log-file=output.txt
```
4.  Open any x264 encoded video in a mkv container, use the **OSC** to skip to like 2/3 of the file.
5. Experience an a/v delay/off sync.

### Actual behavior

Produce no delay.

### Log files
Skipping via OSC: https://gist.github.com/DeadSix27/0671d9c73c144b93d6c053e1c71e6d69
Skipping via Arrow Keys: https://gist.github.com/DeadSix27/7f626f4118a4ee823099abe38f22f86a

**Comment by wm4** [comment]
One uses precise seeking, another one doesn't. SVP apparently can't deal with skipped frames, which hints a lot of more is wrong with that filter.

**Comment by wm4** [comment]
Also probably duplicate of #4300.

**Comment by DeadSix27** [comment]
@wm4 thanks for looking into it more, I couldn't see a related issue on my searches (i wish it would search the content too, not just title)
