### ISSUE TITLE
Taking screenshots may make subtitles corrupt

### ISSUE THREAD

**Issue by nagisa** [mpv-player/mpv#4325]
### mpv version and platform

```
mpv git-bba08e38ff (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Apr 16 17:01:43 EEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3
```

### Reproduction steps

Watch an anime with AlphaSubstation subtitles. Take a screenshot.

### Expected behavior

Screenshot is made and subtitles are shown correctly afterwards.

### Actual behavior

Goes from 
![screenshot from 2017-04-17 12 24 26](https://cloud.githubusercontent.com/assets/679122/25085123/37853994-2369-11e7-9fd1-bb90ebe4227f.jpg)

to

![screenshot from 2017-04-17 12-26-32](https://cloud.githubusercontent.com/assets/679122/25085129/3bb10a48-2369-11e7-839e-22ed75a387e0.png)

The extra screenshots made later on with mpv still look correct, despite the incorrect rendering on the screen.

### Log file

http://sprunge.us/jJUK

### Sample files

This is reproducible with 15th episode of Little Witch Academia from Asenshi, though I have been able to reproduce the same behaviour in a multiple cases for at least 3 months now.

https://0x0.st/xj-.mkv is a piece that I cut out with ffmpeg which can reproduce it. Interestingly it does not reproduce without the included custom font streams.

**Comment by shinchiro** [comment]
I got same file. Taking screenshot with subtitle work correctly on windows though

**Comment by nguyenhimself** [comment]
Works fine for me with the latest stable release [(v0.24.0 0f1afc6)](https://github.com/mpv-player/mpv/commit/0f1afc6ba2a088cf890a5cf7949ed6711b94a766).

[Sample screenshot.](https://cloud.githubusercontent.com/assets/482270/25096510/b2c8f918-23ca-11e7-8cfa-e5ef468268dd.jpg)

Maybe give it a try with another build?

**Comment by wm4** [comment]
Seems like this happens with vo_vaapi only.

**Comment by nagisa** [comment]
@wm4 indeed. Switching to any other `vo` works fine.
