### ISSUE TITLE
Vulkan renderer support.

### ISSUE THREAD

**Issue by DmitryHetman** [mpv-player/mpv#4327]
### mpv version and platform

If you're not using git master or the latest release, update.

### Reproduction steps
mpv hello.webm
### Expected behavior
play with vulkan api
### Actual behavior
OpenGL is used for drawing
### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by Hrxn** [comment]
Questionable definition of *"Expected  behavior"*..

**Comment by wm4** [comment]
That sure is a weird bug report. If this is supposed to be a feature request: there's some stalled work in progress, so maybe or maybe not.
