### ISSUE TITLE
Need to get coordinates of mouse click

### ISSUE THREAD

**Issue by WhidbeyFog** [mpv-player/mpv#4328]
### mpv version and platform
mpv-x86_**64**-20170415-git-3709ce671.7z    Windows 10 

### Reproduction steps
Start mpv player and click the left button of the mouse within the bounds of the video frame
### Expected(Desired) behavior
**Lua logs mouse coordinates**

Lua script logs these two statements:
print("the left mouse button was clicked")
print("mouse_table argument: " .. table.concat(mouse_table, ";")) // Desire first arg is table with mouse coordinates

**Excerpt from FirstLua script:**
function mouse_click_handler(mouse_table)
    print("the left mouse button was clicked")
    print("mouse_table argument: " .. table.concat(mouse_table, ";"))   
end
mp.add_key_binding("MOUSE_BTN0", "left_mouse_button", mouse_click_handler)

<**From manual:** Some events have associated data. This is put into a Lua table and passed as argument to fn. The Lua table by default contains a name field, which is a string containing the event name. If the event has an error associated, the error field is set to a string describing the error, on success it's not set.> I realize it says "Some events", but was hoping this would work on mouse events._

### Actual behavior
**No mouse coordinates provided in the callback**
First statement is logged.
Second statement - **was hoping for mouse coordinates but the argument was nil--> Lua Error**

13:55:26.301 [FirstLua] **the left mouse button was clicked** 
13:55:26.301 (Paused) V: 00:00:05 Cache: ???+36KB
13:55:26.301 [FirstLua] 
13:55:26.301 [FirstLua] stack traceback:
13:55:26.301 [FirstLua] 	C:\Users\whidbey\AppData\Roaming/mpv/scripts/FirstLua.lua:91: in function 'fn'
13:55:26.301 [FirstLua] 	mp.defaults:200: in function 'fn'
13:55:26.301 [FirstLua] 	mp.defaults:60: in function 'handler'
13:55:26.301 [FirstLua] 	mp.defaults:339: in function 'handler'
13:55:26.301 [FirstLua] 	mp.defaults:458: in function 'call_event_handlers'
13:55:26.301 [FirstLua] 	mp.defaults:495: in function 'dispatch_events'
13:55:26.301 [FirstLua] 	mp.defaults:451: in function <mp.defaults:450>
13:55:26.301 [FirstLua] 	[C]: at 0x0116f710
13:55:26.301 [FirstLua] 	[C]: at 0x0116ed10
13:55:26.301 [FirstLua] **Lua error: C:\Users\whidbey\AppData\Roaming/mpv/scripts/FirstLua.lua:91: bad argument #1 to 'concat' (table expected, got nil)**
13:55:26.375 (Paused) V: 00:00:05 Cache: ???+36KB

### Log file
https://drive.google.com/open?id=0B1ui2z3CBZ8RV2dNNEVqaVlXUG8

**Comment by wm4** [comment]
There's an undocumented `mp.get_mouse_pos` function. osc.lua uses it. Whether there will be a standard way to get this - I don't know.
