### ISSUE TITLE
Interpret any plaintext file with an unrecognizable format as M3U

### ISSUE THREAD

**Issue by Larivact** [mpv-player/mpv#4330]
I like to bookmark online videos by saving their URL in a `.url` file. When I open them with VLC, VLC interprets them as M3U and plays them, MPV however fails to play them.

When I'd save the URLs as `.m3u` MPV would play them but I prefer the `.url` extension since it's more descriptive, the files all contain only a single URL.

**Comment by wm4** [comment]
Proof that vlc does what you request mpv should do? Because I very extremely doubt that.

**Comment by Larivact** [comment]
Well I am on Linux and `vlc 2.2.4` behaves so for me. How about you try it yourself?
>Because I very extremely doubt that.

Why?

**Comment by CounterPillow** [comment]
Can't you just use `mpv --playlist=file.url`?

**Comment by Larivact** [comment]
@CounterPillow that works but it doesn't allow me to

* drag an URL file on the MPV pseudo-gui
* drag an URL file on the MPV launcher

which would be nice since I have URL files associated with my web browser.

**Comment by mc4man** [comment]
Then just add 1 line to the top of  your .url file & use File= on url line
[playlist]
Ex.
[playlist]
File=https://youtu.be/_70M4lkLKPk

**Comment by wm4** [comment]
What we could do is treating .url as playlist file by extension, but only if .url files are actually a thing.

**Comment by Larivact** [comment]
This isn't about .url files. When you tell a program to open a file, the program should do its best to open the file and not just fail because it doesn't recognize the file extension.

**Comment by CounterPillow** [comment]
>This isn't about .url files.

So in other words, they're not a thing then.

Can't you just write a .desktop file for your `.url` files that executes mpv with `--playlist=`? Changing the fallback meaning of all plain-text files to something that suits exactly your needs seems like a bad idea.

**Comment by Larivact** [comment]
I get that you're declined to fix an esoteric issue that won't affect 99.99% of your users.
While this posed an UX issue for me I now moved to a keyboard-driven workflow and with ranger's rifle 
defining a new extension `ext vid = mpv --playlist="$@"` was trivial.

I appreciate your responsiveness.
