### ISSUE TITLE
How to download subtitles?

### ISSUE THREAD

**Issue by kodekrendel** [mpv-player/mpv#4332]
Hi. 
Any chance that mpv has a similar option/plugin like VLC, which has build-in plugin to download subtitles?

It literally makes life MUCH easier. After a 2 years of using VLC I am use to it. This is literally single option that I miss in mpv.

**Comment by wiiaboo** [comment]
https://github.com/mpv-player/mpv/wiki/User-Scripts
Look for 'subliminal', there's at least three scripts using it and at least one other using other backend.

**Comment by kodekrendel** [comment]
@wiiaboo can you please point me to manual how to use User Scripts? I can't find it.

**Comment by wiiaboo** [comment]
https://mpv.io/manual/master/#lua-scripting
