### ISSUE TITLE
mpv have video speed and audio speed different

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#4335]
In mpv i know how to slow the speed of the video. but at this time i want the audio to be playing normally. Its ok if it does  not sync with the video.

**Comment by wiiaboo** [comment]
https://mpv.io/manual/master/#options-fps and https://mpv.io/manual/master/#options-no-correct-pts.
Or --vf=lavfi=[[setpts](https://ffmpeg.org/ffmpeg-filters.html#setpts)=2*PTS] to play twice as slow.
