### ISSUE TITLE
Certain desktop animations break/freeze while in fullscreen exclusive mode using win backend

### ISSUE THREAD

**Issue by Hakkin** [mpv-player/mpv#4337]
### mpv version and platform
mpv v0.24.0+234-git-3709ce671
Windows 7

### Reproduction steps
For me, this happens every time by entering fullscreen using opengl-backend=win

### Expected behavior
Desktop animations should behave normally

### Actual behavior
Various desktop animations "freeze" when mpv is running in fullscreen exclusive mode, the ones I've noticed are when minimizing/maximizing a window (the animation where it "glides" from the taskbar freezes mid-animation), and when you hold your mouse over a preview thumbnail in the taskbar, all the windows go transparent to bring focus to the window you're hovering over (aero peek), this animation also freezes, all windows will be stuck transparent until you exit or unfullscreen mpv.

### Log file
http://sprunge.us/ReNM
This log was made using --no-config to rule out it being anything specific in my config triggering this.

### Example
https://0x0.st/xtt.mkv
(The dropped frames mpv shows are simply because I'm recording the desktop which causes performance issues.)
This shows the animation "freezing" when I begin playback and minimize the window, during playback I can (seemingly) no longer interact with the frozen window, minimizing and maximizing the window just makes the frozen animation appear and disappear, when I quit mpv the animation resumes from where it froze and I can interact with the window again.

My CPU is an i5-4590 and my graphics card is a Radeon RX 480 4GB, all drivers are up to date.

I believe this is an mpv bug because other programs I've used that use exclusive fullscreen mode don't do this.

**Comment by wm4** [comment]
I believe this is an interaction between the Windows compositor and the GL driver. They are not well integrated, so these things happen - usually to all fullscreen GL applications. Nothing we can do about.

You can use the angle or dxinterop backends. Both use d3d for windowing interaction and thus shouldn't have the problem.

**Comment by Hakkin** [comment]
As I noted at the bottom, this doesn't happen in other programs that use fullscreen exclusive mode as far as I've seen, this only happens while using mpv.
Bother angle and dxinterop have performance issues for me, which I believe are related to the windows compositor (performance is okay on primary monitor, bad performance on any non-primary monitor), but that is probably for a separate issue.

**Comment by wm4** [comment]
I don't know what these "other programs" actually do, so I can't say anything about it.

**Comment by Hakkin** [comment]
If you want an example, I believe Dolphin (the emulator) uses fullscreen exclusive mode, and it doesn't have the same problems as mpv.

**Comment by wm4** [comment]
Does it use OpenGL windowing?

**Comment by Hakkin** [comment]
I believe so, I have the backend set to "OpenGL" in the graphics settings.
