### ISSUE TITLE
Maximize window doesn't work

### ISSUE THREAD

**Issue by behroozramezani** [mpv-player/mpv#4339]
When I maximize mpv window it doesn't fill screen. other application is ok in kde.
mpv version 
``
Version         : 1:0.24.0-3
``
Arch
Kde 5.9
![mpv-issue](https://cloud.githubusercontent.com/assets/17659342/25243918/feb35f26-2613-11e7-8aa6-b65b2f1c7a4e.png)
#

**Comment by wiiaboo** [comment]
Maximized window is not the same as fullscreen. You press 'f' or double-click with left mouse to fullscreen.

**Comment by behroozramezani** [comment]
> Maximized window is not the same as fullscreen. You press 'f' or double-click with left mouse to fullscreen
I know that . but Maximized window doesn't fill screen.

**Comment by wiiaboo** [comment]
Try with [`--no-keepaspect-window`](https://mpv.io/manual/master/#options-no-keepaspect-window).
In windows it's ignored, but it might work there.

**Comment by BlondfootInnawoods** [comment]
Doesn't work.
