### ISSUE TITLE
Switching to fullscreen only works once in Wayland

### ISSUE THREAD

**Issue by Eitilt** [mpv-player/mpv#4343]
### mpv version and platform

mpv 0.18.0 on Gentoo (desktop 13.0, kernel 4.9.16)
All enabled use flags: alsa, cdda, cli, dvd, egl, enca, encode, iconv, jpeg, lcms, libass, lua, opengl, wayland

Of note, all X support is disabled in favor of Wayland, but (according to other issues on here) the opengl-hq VO is used instead.

### Reproduction steps

Play any video, then hit `f` three times.

### Expected behavior

The video switches to full screen, back to windowed/actual size, and then to full screen once again.

### Actual behavior

The first two switches are performed as expected, but the third (and every other succeeding switch) leaves the video at a size best described as "thumbnail". In other words, everything works the first time a video is made full screen, but every time after that it goes tiny instead.

### Log file

http://sprunge.us/QBiO (error occurs starting at 12.647)

**Comment by wm4** [comment]
>mpv 0.18.0

Too old.
