### ISSUE TITLE
[ffmpeg] Impossible to convert between the formats supported by the filter 'mpv_src_vid2' and the filter 'auto_scaler_0'

### ISSUE THREAD

**Issue by ArchangeGabriel** [mpv-player/mpv#4345]
### mpv version and platform

ArchLinux, 0.24.0

### Reproduction steps

Run `mpv vid1.mkv --external-file=vid2.mkv --lavfi-complex='[vid1] [vid2] hstack [vo]'`

### Expected behavior

Video playing side-by-side in a mpv window.

### Actual behavior

```
[ffmpeg] Impossible to convert between the formats supported by the filter 'mpv_src_vid1' and the filter 'auto_scaler_0'
failed to configure the filter graph
```

### Log file

https://www.zerobin.net/?11b1256a17eba1ab#27OZEmH6zV5w869a85mNs0BvNfFSPEZFuX8cIUOBcJI=

**Comment by wm4** [comment]
I suspect you're using hw decoding. The paste thing said it requires JS, so I didn't look.

**Comment by ArchangeGabriel** [comment]
Hum sorry about the paste thing. Will mind this for the next time. And you were right, for some reason the vaapi-copy arg of my command disappeared for some reason. Sorry for the noise.
