### ISSUE TITLE
Playing webm audio file does not show time 

### ISSUE THREAD

**Issue by rieje** [mpv-player/mpv#4346]
I downloaded an audio file with a .webm extension. When I play it with mpv <file>.webm, it plays the audio without a GUI (which is fine, not needed), and the input controls work. However, it doesn't show [current timestamp]:[total audio length], which is crucial to have some sort of context of where I am on when listening to content (I would like to know how much time until the content is over, etc.). 

I'm on the latest version of mpv on Arch Linux.

**Comment by wm4** [comment]
Issue template ignored.
