### ISSUE TITLE
mpv silently falls back to software decoding

### ISSUE THREAD

**Issue by ArchangeGabriel** [mpv-player/mpv#4347]
### mpv version and platform

ArchLinux, 0.24.0

### Reproduction steps

Try to play a video for which hwdec is not supported.

### Expected behavior

`Using software decoding` appears in terminal output.

### Actual behavior

Nothing appears.

**Comment by wiiaboo** [comment]
https://github.com/mpv-player/mpv/commit/ddaab3349b2826acd6ca1fa82b5f1d7d5944cd72

**Comment by wiiaboo** [comment]
Basically, it confused most people about hwdec falling back to software decoding, so it's unlikely to be reverted.

**Comment by ArchangeGabriel** [comment]
So, the idea is to check wether `using hwdec` is printed and else this means software decoding is used? Because falling back to software decoding in this case was an issue with me encoding in H264 10bit which is not supported by VAAPI.

**Comment by ArchangeGabriel** [comment]
I’m fine with that, as long as I can tell wether hwdec is working by looking at the normal console output.

**Comment by wiiaboo** [comment]
10-bit H.264 isn't supported anywhere in hardware, basically,
You can check that "Using hardware decoding" shows up. If not, it's using software decoding.
Or use `--term-playing-msg="${hwdec-current==no:Using software decoding.}"` if you really really want that message to show up.

**Comment by ArchangeGabriel** [comment]
Thank you very much! Final thing: can I have this printed in yellow just as `[vo/opengl/x11] XOpenIM() failed. Unicode input will not work.` is? That would be perfect. :)

**Comment by wiiaboo** [comment]
No idea, depends on your terminal, afaik.

**Comment by ArchangeGabriel** [comment]
OK, I thought this would be some marking (like error/warning) in the message coming from mpv and then indeed my terminal rendering it this way, so that adding the same marking to this message would work. But that’s OK if you don’t know how I can do that, I’ll definitively live without it. :)

**Comment by ArchangeGabriel** [comment]
@wiiaboo Hum, it seems to print the message even with hardware decoding working… Is that expected? Hardware decoding seems still on, so…
