### ISSUE TITLE
Ignoring keys not working on Wayland

### ISSUE THREAD

**Issue by tsoernes** [mpv-player/mpv#4348]
### mpv version and platform
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.28.100
   libavcodec      57.48.101
   libavformat     57.41.100
   libswscale      4.1.100
   libavfilter     6.47.100
   libswresample   2.1.100
ffmpeg version: 3.1.7

Fedora 25 Gnome **Wayland** x64

(Have tried building from source with mpv-build, which yields "Unable to find OpenGL header files for video output.")

### Reproduction steps
Set input.conf to
```
AXIS_UP ignore
AXIS_DOWN ignore
MOUSE_BTN3 ignore
MOUSE_BTN4 ignore
AXIS_UP    add volume 2
AXIS_DOWN  add volume -2
```
### Expected behavior
Scrolling adjusts volume
### Actual behavior
Scrolling adjusts volume AND seeks
### Extras
mpv --input-test --idle --force-window confirms that AXIX_UP and DOWN is bound to SEEK.

**Comment by tsoernes** [comment]
Confirmed also a problem with: 
[torstein@localhost ~]$ mpv --version
mpv git-591d99a (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Apr 22 13:57:19 CEST 2017
ffmpeg library versions:
   libavutil       55.61.100
   libavcodec      57.93.100
   libavformat     57.72.101
   libswscale      4.7.101
   libavfilter     6.85.100
   libswresample   2.8.100
ffmpeg version: N-85601-g4925537
![screenshot from 2017-04-22 14-37-19](https://cloud.githubusercontent.com/assets/6782404/25304527/4567dfb8-2769-11e7-8965-29d8dab16075.png)

**Comment by tsoernes** [comment]
Adding --no-input-default-bindings as command line arg or no-input-default-bindings in mpv.conf does not work either. Default bindings are still used.

**Comment by DeadSix27** [comment]
I'm on windows, short question related to this, is the new proper way to bind mouse wheel up down to commands, using AXIS_UP and DOWN, prior to rossys commits it was MOUSE_BTN3,4, which do not work anymore now.

**Comment by atomnuker** [comment]
Works fine with the latest mpv git master, closing bug
