### ISSUE TITLE
forcedetect colorlevels setting

### ISSUE THREAD

**Issue by unic0rn** [mpv-player/mpv#4350]
can we please get forcedetect for colorlevels setting in format filter, in addition to auto/limited/full?

as it is, auto falls back to the one tagged or limited if there's none, at least as i understand it. the thing is, there are files that aren't properly tagged, and for some content (anime) it isn't always obvious.

in such case, -vf format=:::forcedetect should start with limited and check the luma range in use for every frame for the first... 10 seconds? (preferably configurable) during playback, switching to full in case limited range is exceeded and stopping the checks at that point.

i suppose it could be incompatible with things like hardware-based decoding and it would increase the cpu usage slightly in the detection phase, but for some broken files/streams (like from Funimation) it's the only way to avoid guessing if what you're seeing is the right thing or not.

**Comment by haasn** [comment]
For such obscure cases don't you think it would be easier to just make a keybinding to toggle the file's value range? That's my standard practice for mistagged files, and it works better than any auto-detection is ever going to.

**Comment by unic0rn** [comment]
no.

whole file certainly uses a single range, that's for sure - and autodetection will detect full range without problems, given enough frames.

it's not a matter of changing the range on the fly, it's a matter of deciding which range to use for given file, because for such obscure cases it isn't always clear. hitting a key to toggle it one way or another a couple of times during a video, trying to figure out which option is the correct one (and it really isn't always clear) instead of focusing on watching it, isn't fun at all.

http://i.imgur.com/nFz8Py7.jpg
http://i.imgur.com/8PpgQVv.jpg
http://i.imgur.com/c3KmDMt.jpg
http://i.imgur.com/pGzAezP.jpg
http://i.imgur.com/j5JmTcu.jpg
http://i.imgur.com/l9cNYZX.jpg
http://i.imgur.com/qPLy3MD.jpg
http://i.imgur.com/ReOozoz.jpg
http://i.imgur.com/RwtyGVg.jpg
http://i.imgur.com/BDYudAI.jpg
http://i.imgur.com/tgLMYwH.jpg
http://i.imgur.com/JrGQRaz.jpg
http://i.imgur.com/pueukIY.jpg
http://i.imgur.com/G6bQpGA.jpg
