### ISSUE TITLE
latest ('git+https://github.com/mpv-player/mpv'         'find-deps.py') doesnt support rpi

### ISSUE THREAD

**Issue by enricoT** [mpv-player/mpv#4352]
### mpv version and platform
mpv-git-0.24.0.r263.g611426d162-1-armv7h.pkg.tar.xz generated from aur 2017-04-20 raspberry pi 3 b the latest release of the day from
source=('git+https://github.com/mpv-player/mpv'
        'find-deps.py')
from configure:
Checking for Raspberry Pi support                                 : no ('bcm_host' not found)

### Reproduction steps
running mpv:
mpv --vo=rpi videoh264.omx.mkv
### Expected behavior
Playing: videoh264.omx.mkv
[cache] Failed to allocate cache buffer.
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 (*) (ac3)
 (+) Subs  --sid=1 --slang=en (*) 'videoh264.omx.idx' (dvd_subtitle) (external)
AO: [alsa] 48000Hz stereo 2ch float
Using hardware decoding (rpi).
VO: [rpi] 720x576 => 1024x576 mmal
[osd/libass] PlayResX undefined, setting to 960
(Paused) AV: 00:00:04 / 02:10:19 (0%) A-V:  0.000

### Actual behavior
Playing: videoh264.omx.mkv
[cache] Failed to allocate cache buffer.
 (+) Video --vid=1 (*) (h264 720x576 25.000fps)
 (+) Audio --aid=1 (*) (ac3 6ch 48000Hz)
 (+) Subs  --sid=1 --slang=en (*) 'videoh264.omx.idx' (dvd_subtitle) (external)
[vo] Video output rpi not found!
Error opening/initializing the selected video_out (--vo) device.
Video: no video

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by Akemi** [comment]
please open a new issue if this problem still persists.
