### ISSUE TITLE
how to i only skip 5 seconds upon pressing right key rather than a minute ( or more ) of video ?

### ISSUE THREAD

**Issue by jpca999** [mpv-player/mpv#4353]
### mpv version and platform

If you're not using git master or the latest release, update.

### Reproduction steps
happens all the time. all the versoins. 
### Expected behavior
ability to change the skip length 
### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wiiaboo** [comment]
https://mpv.io/manual/master/#input-conf

**Comment by CounterPillow** [comment]
Also be aware that the default seek behaviour is to seek with keyframe-accuracy for fast seeking purposes, so if your keyframes are ridiculously far spaces apart, I think you only get to seek to those. Check the manual to see how you can switch it to do a precise seek.
