### ISSUE TITLE
Cannot pass argument to mpv 0.25.0 using "open -a mpv --args" anymore

### ISSUE THREAD

**Issue by gbstan** [mpv-player/mpv#4354]
### mpv version and platform
mpv: 0.25.0
platform: macOS Sierra 10.12.4
If you're not using git master or the latest release, update.

### Reproduction steps
Open a terminal
Type:
open -a mpv --args --vid=no https://www.youtube.com/watch?v=aatr_2MstrI

### Expected behavior
In previous versions of mpv, this allowed to open mpv without video, i.e. just download and play the audio.
This now prevents scripting (in particular with Alfred) to use mpv for direct audio playback

### Actual behavior
Since the upgrade to mpv 0.25.0, mpv does not recognise the arguments passed to it through "open -a mpv --args ..." anymore and thus does not play the audio as expected

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by gbstan** [comment]
Solved!

Changing the order of the arguments solved the issue:

open -a mpv name_of_file --args --vid=no

This can now be closed!

**Comment by Akemi** [comment]
use the mpv binary directly instead of open?

**Comment by gbstan** [comment]
Unfortunately, there is a good reason to use "open":
  

  
Using "open -a mpv "youtube_video_link_here"   --args --vid=no" in a bash script allows to launch the mpv GUI to only play the audio, which is needed to have access to next, previous, forward, backward, etc. even when playing audio only.   
  
  
  
  
 This worked before in previous versions of mpv.
  
  
  
 It doesn't work anymore as:
  
 open -a mpv "youtube_video_link_here"   --args --vid=no
  
  
  
seems to open mpv and play the YouTube video instead of only downloading and playing the audio, which is the expected behaviour.
  

  
So it seems that for some reason "-args --vid=no" is not passed correctly any more from open to mpv. Again, this was working yesterday on mpv 0.24.   
  
  
  
Sent from my phone.
  

  
  
  
  
  

  
  
>

**Comment by Akemi** [comment]
there is no need to repeat yourself again. i know it doesn't work anymore because i 'removed' that feature because of simplification of one commit. i deemed the case of opening mpv via "open" as useless since you can just use the mpv binary in the bundle directly.

so the only reason you use 'open' is because you always want the GUI? just use `mpv --player-operation-mode=pseudo-gui` and you get the same behaviour.

**Comment by gbstan** [comment]
Super! This works!

Many thanks for your prompt and very useful response.

This can now be marked as resolved!

**Comment by vitorgalvao** [comment]
> This can now be marked as resolved!

@gbstan You have to power to close the issue yourself (you can close issues you opened).
