### ISSUE TITLE
Problem with some long YouTube videos

### ISSUE THREAD

**Issue by xesarni** [mpv-player/mpv#4355]
mpv 0.25.0
youtube-dl 2017.04.17
Windows 8.1 x64

Long videos from this [channel](https://www.youtube.com/user/TheMexicanRunnerSRL/featured) cannot be played.

Example:
> mpv --msg-level=ytdl_hook=debug -v[ytdl_hook] failed to parse JSON data: error
> [cplayer] Run command: hook-ack, flags=0, args=[on_load]
> [ffmpeg] Opening https://www.youtube.com/watch?v=o5CqbYGLs7w
> [ffmpeg] Mime-type: 'text/html; charset=utf-8'
> [ffmpeg] Stream opened successfully.
> [cache] Cache size set to 150000 KiB (75000 KiB backbuffer)
> [demux] Trying demuxers for level=normal.
> [cache] EOF reached.
> [lavf] No format found, try lowering probescore or forcing the format.
> [demux] Trying demuxers for level=unsafe.
> [lavf] No format found, try lowering probescore or forcing the format.
> [cache] Terminating cache...
> [cache] Cache exiting...
> [cplayer] Opening failed or was aborted: https://www.youtube.com/watch?v=o5CqbYGLs7w
> [cplayer] finished playback, unrecognized file format (reason 4)
> [cplayer] Failed to recognize file format.
> [cplayer]
> [cplayer]
> [cplayer] Exiting... (Errors when loading file)
> [osc] Exiting...
> [ytdl_hook] Exiting... https://www.youtube.com/watch?v=o5CqbYGLs7w

Other videos:
https://www.youtube.com/watch?v=XmL19DOP_Ls
https://www.youtube.com/watch?v=_oahMdI1T78 + more.

**Comment by ChrisK2** [comment]
Uh yeah, the JSON output from youtube-dl with
```
youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --no-playlist --format bestvideo+bestaudio/best --all-subs -- https://www.youtube.com/watch?v=o5CqbYGLs7w
```

is 29 MB large because it contains URLs to ALL fragments ... which blows up mpv's JSON parser.

For those videos ``--ytdl-raw-options=youtube-skip-dash-manifest=`` seems to do it as a workaround for now.

**Comment by xesarni** [comment]
Thanks for the workaround!

**Comment by Earnestly** [comment]
This is starting to appear on more and more long videos, such as https://www.youtube.com/watch?v=1JylxvHvdtA.  I've found that configuring this workaround necessary for now.
