### ISSUE TITLE
Is gtf or cvt better to create a 48hz modeline?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#4356]
The gtf gives me the exact refresh rate that I need.
```
$ gtf 1920 1080 47.952

  # 1920x1080 @ 47.95 Hz (GTF) hsync: 53.23 kHz; pclk: 135.41 MHz
  Modeline "1920x1080_47.95"  135.41  1920 2032 2232 2544  1080 1081 1084 1110  -HSync +Vsync
```
Lots of people say that cvt is more advanced, however it can't create the real 47.952Hz.
```
$ cvt 1920 1080 47.952
# 1920x1080 47.89 Hz (CVT) hsync: 53.30 kHz; pclk: 134.75 MHz
Modeline "1920x1080_47.95"  134.75  1920 2024 2224 2528  1080 1083 1088 1113 -hsync +vsync
```

So...which one is exactly better??

**Comment by haasn** [comment]
What does this have to do with mpv?

**Comment by lachs0r** [comment]
Neither is better than the other. Pick whatever works for your display. However, most LCDs use/require timings that are not compliant with either GTF or CVT (lower pixel clocks, which works due to digital display technology).
For example, I use the equivalent of this with mine (in practice it’s a modified EDID):
`"1920x1080x71.93" 160.04 1920 1924 1956 1992 1080 1083 1087 1117`

**Comment by JulianLai** [comment]
@lachs0r How do you get these numbers?

**Comment by qmega** [comment]
You could try [cvt12](https://github.com/kevinlekiller/cvt_modeline_calculator_12) ([AUR package](https://aur.archlinux.org/packages/cvt12-git/)). Its `-b` option uses extra reduced blanking that can produce any refresh rate. Your example would be `cvt12 1920 1080 47.952 -b` which gives:
```
# 1920x1080 @ 47.952 Hz Reduced Blank (CVT) field rate 47.952 Hz; hsync: 53.418 kHz; pclk: 111.11 MHz
Modeline "1920x1080_47.95_rb"  111.11  1920 1968 2000 2080  1080 1103 1108 1114 +hsync -vsync
```

**Comment by lachs0r** [comment]
@JulianLai late reply but I loaded the monitor’s dumped EDID in wxEDID to poke the numbers on the DTD Constructor tab until I got the rate I wanted with a low enough pixel clock. LCDs don’t care about the timing formula or front/back porch etc. so you can pretty much run them at anything that falls within their horizontal/vertical refresh rate range.
