### ISSUE TITLE
Typo in wiki?

### ISSUE THREAD

**Issue by magicgoose** [mpv-player/mpv#4358]
if "api" is one of the video file extensions then I guess it should be "avi" instead
https://github.com/mpv-player/mpv/wiki/FAQ/_compare/e8d5dd39fdaf2ced38366a6f8908719352d19a58...577d2a9dccddde93a9cfaad31fe0f3a2ef5f54d9
BTW, I'm not sure why I have write access to the wiki…

**Comment by wiiaboo** [comment]
Everyone can edit the wiki.
