### ISSUE TITLE
Include property name in JSON IPC response

### ISSUE THREAD

**Issue by vilhalmer** [mpv-player/mpv#4359]
When subscribing to property changes via the IPC socket, each change sends an object that contains the name of the property that changed, so you can differentiate.

    {event: "property-change", name: "metadata", data: "…" }

However, when explicitly requesting a property, the resulting object contains only:

    {data: "…", error: "success"}

While including the name is unnecessary when working with the socket in a pure request-response way, things get a little more complex when doing both requests and subscriptions. I propose adding the `name` key to these responses as well, so that the same code path in the client can be used to process objects generated by either mechanism. This would prevent the client from having to maintain state to remember which property it requested last and route it appropriately. It would also make it much easier to request multiple properties, as you wouldn't have to wait for the response between each to be able to differentiate them.

**Comment by wiiaboo** [comment]
There's `request_id`, isn't that more or less what you want?

**Comment by vilhalmer** [comment]
It is indeed! My apologies, I had totally overlooked that in the docs.
