### ISSUE TITLE
Make mpv aware of Windows taskbar

### ISSUE THREAD

**Issue by wiiaboo** [mpv-player/mpv#4363]
More exactly, make the default autofit and window-scale changing behavior use the monitor's work area, instead of the whole monitor resolution.

Usecase 1: opening video larger than work area with no --autofit options and default --window-scale=1
- actual behavior: taskbar covers the bottom part of the video and/or OSC if layout=bottombar

Usecase 2: changing window-scale to larger values
- expected: fit within the work area, even if the window was moved to be covered by the taskbar
- actual: mpv ignores the taskbar and gets bottom part covered

Usecase 3: --autofit-larger=50%x50%
- expected: scale down window to fit to 50%x50% of work area
- actual: scales down window to fit to 50%x50% of monitor

Usecase 4: move window so that it gets covered by the taskbar and/or goes beyond the monitor (other than the window title, which should always be visible)
- expected and actual: ignores taskbar

Usecase 5: resize window with window-scale should behave differently if close to an edge of the screen.
- expected: if close to top-right edge, it should scale to the bottom-left so the window doesn't go beyond the screen
- actual: resize is always centered, even if close to the top edge, hiding the window title.

**Comment by shinchiro** [comment]
@rossy Does using `SPI_GETWORKAREA` with [SystemParametersInfo](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724947(v=vs.85).aspx) API will help to get the available screen size without the taskbar?

**Comment by rossy** [comment]
Yep, that would work, but only for the primary monitor. You can also use [GetMonitorInfo][1] and ``MONITORINFO::rcWork`` to get the work area of any monitor, in case there are secondary taskbars on other monitors.

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/dd144901.aspx

**Comment by pavelxdd** [comment]
Hello. I'd like to work on implementing these usecases, but I have one thing to comment on:

> Usecase 5
expected: if close to top-right edge, it should scale to the bottom-left so the window doesn't go beyond the screen

I don't think this is what is expected. I'd say the top-right corner of the window should stay where it was, and the bottom-left should be adjusted. For example if the window is snapped to the top-right corner, it will stay snapped to it after changing the window-scale.

**Comment by wiiaboo** [comment]
That's exactly what I mean with that usecase, yes.
