### ISSUE TITLE
Rethinking how filter/setting state is retained/discarded between videos when playing a playlist

### ISSUE THREAD

**Issue by epitron** [mpv-player/mpv#4365]
_(NB: I'm not using the bug template because this is more of a discussion for how to improve the usability of the playlist feature)_

### Background

I sometimes like to play music videos on shuffle in mpv. The video files are a bit of a mess -- varying quality, messed up aspect ratios, black bars that need to be cropped, etc. (I often need to adjust the settings for them.)

Unfortunately, mpv handles settings differently when in playlist mode than when playing one file at a time -- sometimes, if you change the settings for one video, mpv will apply them to all subsequent videos also.

#### Some Examples:

* Changing the aspect ratio will affect the next video in the list
* Cropping a video (with an autocrop script) will affect the next video in the list
* If a video has a "saved position" which is set to the very end of the video, when it comes up in the playlist, mpv will just freeze on the last frame of that video and wait until you rewind or skip to the next video (in this scenario, I'd like it to totally ignore the saved position)

### Possible Solution:

This is a tricky problem to solve because it depends highly on user preferences.

Ideally, when playing a playlist, I'd like it to retain the fullscreen and volume settings between videos, to ignore any saved positions, and for mpv to remember the video filter/aspect ratio settings I'd set previously (in playlist mode, or regular mode).

One solution would be to let the user configure which settings mpv remembers/ignores in playlist mode and regular mode. (eg: `--playlist-mode-setting-persistence=+fullscreen,+aspect,-saved_position,-vf`)

If I'm overestimating the variability of people's preferences, this would be a bit overkill of a solution. Maybe the defaults just need to be changed.

Thoughts?

**Comment by epitron** [comment]
Update: I just found an option that's roughly what I described:  `--reset-on-next-file=<all|option1,option2,...>`

It doesn't look like it solves the saved-position problem, but it should help!

**Comment by Hrxn** [comment]
I think it's a good idea to use playback settings on a per file basis.

Not sure what would be the best way to implement it, though.

There already is Quit-and-Save-position, so it could be done like this. On user input only, nothing automatic.

**Comment by Dudemanguy** [comment]
#8960 would fix the inability to customize watch_later data and close this (found another one heh).

**Comment by guidocella** [comment]
I think that what he's asking is already fixed by using `--no-resume-playback` with playlists.

**Comment by Dudemanguy** [comment]
Well fixed by something anyway.
