### ISSUE TITLE
Cannot get dwidth / dheight properties on MPV_EVENT_FILE_LOADED event

### ISSUE THREAD

**Issue by HarukaMa** [mpv-player/mpv#4367]
### mpv version and platform

0.25 on macOS, bundled in IINA

### Description

I'm a collaborator of IINA project, and when we get `MPV_EVENT_FILE_LOADED` event we would try to set window size to match the video size. But at this point, we could not immediately get data of `dwidth` and `dheight` properties; they both returns 0. A short time after this event, however, those properties would return normal values. We would have to use `width` and `height`, unfortunately this would yield wrong results on videos with anamorphic pixels (such as 16:9 DVD videos, 720x576 -> 1024x576).

### Reproduction steps

Try to read `dwidth` property when `MPV_EVENT_FILE_LOADED` event is received.

### Expected behavior

mpv returns correct data specified in video stream.

### Actual behavior

Sometimes mpv returns 0 for the property.

### Log file

I think log file in this case is not related?

### Sample files

With any file presumably (although only anamorphic ones are affected)

**Comment by wm4** [comment]
In general, these properties are available only once the first video frame has been decoding and is displayed (or about to display). `MPV_EVENT_FILE_LOADED` is fired before that, so trying to read `dwidth` etc. will result in a race condition.

You could instead wait for the `MPV_EVENT_VIDEO_RECONFIG` event. Or better (but equivalent), observe the `video-out-params` property, read it as mpv_node, and get the `dw`/`dh` fields (they're the same as the `dwdith`/`dheight` properties). Keep in mind that property observation fires an event only if the full value actually changes.

If you want to have "frame perfect" resizing of the video window, it's going to be more complicated.
