### ISSUE TITLE
How to use options or commands?

### ISSUE THREAD

**Issue by kodekrendel** [mpv-player/mpv#4368]
Hello aliens.

I need to shuffle my playlist. How to do this impossible task?
I see --shuffle and shuffle-playlist. But I have no idea how to use it, because Documentation is written on alien language.

I don't need to edit .conf files, since I want to shuffle one friggin time, and not edit files for that task everytime. I found only that solution in Google. Google have no idea how to use mpv with  --shuffle and shuffle-playlist. Since Google is for humans, and mpv is not :smile:

**Comment by wiiaboo** [comment]
`[playlist-shuffle command](https://mpv.io/manual/master/#command-interface-playlist-shuffle)`. Just assign it to some key and it'll probably do what you want.

**Comment by kodekrendel** [comment]
@wiiaboo damn, that was easy :+1: Now I feel stupid.
