### ISSUE TITLE
[question/issue(?)] about the "eq" video filter removal.

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#4370]
### mpv version and platform
0.25

Since the video filter deprecation, including the "eq" video filter, i wonder what will happens when the "eq filter" will be really dropped and a video equalization will be requested by the user when using an output video driver that doesn't support it.

By now, the man page still states:
```
(The  following  keys  are  valid  only  when  using  a  video  output  that supports the corresponding adjustment, or the software equalizer
       (--vf=eq).)
```
and, partially unrelated:

```
                 --vf=sub,eq
                        Moves  sub  rendering  before  the  eq filter. This will put both subtitle colors and video under the influence of the video
                        equalizer settings.

```

Thanks.

**Comment by wm4** [comment]
The key bindings / properties will simply stop working for those VOs.

The manpage will be cleaned up once the deprecation is finished (or feel free to make a PR).
