### ISSUE TITLE
Unable to play RAW video in the yuv444p format

### ISSUE THREAD

**Issue by magiruuvelvet** [mpv-player/mpv#4372]
### mpv version and platform

git 150c988e88 Linux
```
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3
```

### Reproduction steps

1. (just for quick reproduction, I actually have native yuv444p videos) Convert any video to RAW into the yuv444p format. `ffmpeg -i input -c:v rawvideo -pix_fmt yuv444p output.yuv`

2. mpv's rawvideo demuxer can't seem to play rawvideos in the yuv444p format because it requires FourCC values, unlike ffmpeg which uses yuv444p, yuv422p, yuv420p and so on. `ffplay` has no issues playing the video (`ffplay -video_size WxH -framerate FPS -pixel_format yuv444p video.yuv`). I also have no issues playing yuv420p raw videos in mpv, because the FourCC is `I420` and it works just fine. But I can't figure out the FourCC of yuv444p. I tried `I444`, `Y444` and also `444P` and bunch of similar phrases, but mpv rejects them all.

### Expected behavior

That mpv plays back the yuv444p video as ffplay does.

### Actual behavior

```
mpv --demuxer rawvideo --demuxer-rawvideo-w 1920 --demuxer-rawvideo-h 1080 --demuxer-rawvideo-format yuv444p --demuxer-rawvideo-fps 23.98 output.yuv
Option demuxer-rawvideo-format: invalid FourCC: 'yuv444p'

mpv --demuxer rawvideo --demuxer-rawvideo-w 1920 --demuxer-rawvideo-h 1080 --demuxer-rawvideo-format I444 --demuxer-rawvideo-fps 23.98 output.yuv
Playing: output.yuv
[rawvideo] rawvideo: img size not specified and unknown format!
```

Again, yuv420p (`I420`) works just fine.

### Log file

Log (`I444`): https://hastebin.com/ohewijareb.md
Log (`yuv444p`): https://hastebin.com/iqepakuhus.md

### Sample files

see Reproduction steps 1.)

### Side notes

I'm wondering if mpv actually supports YUV 4:4:4. Playing yuv444p from H.264 or H.265 encoded frames works, but most likely the native decoders are used there. Teach me if I'm wrong ;)

**Comment by wm4** [comment]
`--demuxer-rawvideo-mp-format` (equivalent to those ffmpeg `-pixel_format` options) probably works. Or you could use the ffmpeg raw video demuxer directly, although that would require using `--vd-lavc-o` to pass through all the parameters.

**Comment by magiruuvelvet** [comment]
Using `--demuxer-rawvideo-mp-format` works great and I can use my prefered format names without remembering new ones. I somehow missed that in the documentation.

Thanks

**Comment by wm4** [comment]
mpv uses FFmpeg's raw video decoder. mpv's own raw video demuxer supports only a few FourCCs "automatically", but in general all FourCCs should work as long as you specify a frame size with `--demuxer-rawvideo-size`. According to libavcodec/raw.c, there's actually a 444 FourCC, whether it's official or not.
