### ISSUE TITLE
using --on-all-workspaces spawns mpv only on the last workspace

### ISSUE THREAD

**Issue by v1kn** [mpv-player/mpv#4373]
### mpv version and platform

Ubuntu 16.04 - 17.04
Xfce DE
mpv 0.25 built on 2017.04.23

### Reproduction steps

1. create multiple workspaces (tested only on Xfce DE)
2. run `mpv` with `--on-all-workspaces`

### Expected behavior

the player is visible on all workspaces

### Actual behavior

the player appears only on the last created workspace

### Log file

[pastebin log](https://pastebin.com/zbLxW1gB)

### Summary of DEs

Xfce => on last workspace
MATE => on first workspace
GNOME => on first workspace
Plasma 5 => works

**Comment by wm4** [comment]
I'd tend towards claiming that this is a xfce bug. Apparently we set _NET_WM_DESKTOP to 0xFFFFFFFF, which seems to be the same xfwm does internally.

**Comment by mc4man** [comment]
Maybe an Ubuntu bug, whatever, but that option has never had any effect here with compiz.
(- though I guess one could use a window rule to make mpv sticky

**Comment by CounterPillow** [comment]
`mpv --idle --force-window --on-all-workspaces` works as expected with kwin on Plasma 5.9.5, so it's definitely not an mpv bug.

**Comment by v1kn** [comment]
@wm4 
This may indeed be a matter of window manager. However, I just now performed a quick test with MATE marco wm (virtualbox, ubuntu mate 17.04, mpv 0.24), and in this setup, `mpv` shows up only on the first workspace, despite them being 4 by default.

So it seems `--on-all-workspaces` behaves differently with each window manager.
While not strictly a bug in `mpv`, maybe this option can be enhanced in a DE/WM-agnostic way?

**Comment by wm4** [comment]
> maybe this option can be enhanced in a DE/WM-agnostic way?

There's probably no standard for this.

**Comment by sfan5** [comment]
@mc4man 

Definitely not an Ubuntu bug, can reproduce this with Arch+XFCE too.
Window always appears on the last workspace.

**Comment by mc4man** [comment]
Checked with metacity & the option works there. That would be the only WM here that it does...

**Comment by v1kn** [comment]
I can confirm @CounterPillow 's findings, virtualbox test on KDE Neon shows that under KWin the option works.

However, another test with Ubuntu Gnome 17.04 -- mpv spawns only on the first workspace
