### ISSUE TITLE
sub-back-padding

### ISSUE THREAD

**Issue by itmitica** [mpv-player/mpv#4374]
I'd like to have some padding around subtitles, when sub-back-color is defined. Right now, the back box has no padding. I'd like the back box around the sub text enlarged, something like in the image below. Is this possible?

Thanks.

![screenshot from 2017-04-26 22-03-45](https://cloud.githubusercontent.com/assets/1570477/25452063/ecda4aea-2acc-11e7-8fe8-f4bf685118d3.png)

**Comment by wiiaboo** [comment]
This should a be a feature request to libass, which doesn't have a way of changing the size of the opaque box.

**Comment by itmitica** [comment]
Just to be clear, my request is not about subtitles in ASS format, it's about normal text subtitles. The screenshot attached is of a movie file and a corresponding srt subtitle file. The settings I use in the `mpv.conf` file are these:
```
sub-color=0.0/0.0/0.0/0.75
sub-back-color=1.0/1.0/1.0/0.75
```

**Comment by wiiaboo** [comment]
mpv uses libass to render all text subtitles. Make a feature request in libass to add a way of changing BorderStyle: 4 box size or, like BorderStyle: 3, make it changeable with border-size.

**Comment by itmitica** [comment]
OK, thanks.

**Comment by kelciour** [comment]
It seems this issue can be closed as it is similar to this one - https://github.com/mpv-player/mpv/issues/4110
