### ISSUE TITLE
option to diplay window when playing audio tracks

### ISSUE THREAD

**Issue by mpvfeatures** [mpv-player/mpv#4375]
This is a feature request, if just haven't found the parameter to do this, please just close this issue with a hint

### Expected behavior
When mpv is skipping from a video to an audio file with the default "--fixed-vo", it should keep the X-Window open, so i can still use the mouse/keybord to control it.

### Actual behavior
The window disappears and I can't even skip the audio track to get to the next video.

Personally I actually always run mpv as a background process, so there is no way to control it via the console. Others still have to switch tho the workspace and xterm to control it again.

### Proposed solution
1..an option --window with a default of --window=video and --windoe=always will keep a window with black content open so that osd, inputs and controls can still be used when playing an audio track.
2. an option --omit with default --omit=none and possible values of --omit=audio --omit=video --omit=image --omit=text, And when loading a file, it will be skipped if it is that type (just like mplayer skipped all audio files when -nosound was uesd). this would also be a nice thing for those that use `mpv A.Movie-2017/*` and don't want the A.Movie-2017/a.movie.nfo file to be shown,

Either option would solve my problem, but i think both are a good idea.

**Comment by wiiaboo** [comment]
`--force-window`?

**Comment by mpvfeatures** [comment]
read the manpage for 3 hours missed that option, but that was when i was frustrated that the -nosound did not work and audio files where not skipped with --mute or --volume=0
but --forece-window definitely solves my issue.
thx
