### ISSUE TITLE
reset values when file changes

### ISSUE THREAD

**Issue by mpvfeatures** [mpv-player/mpv#4376]
This is a feature request, please close the issue if:
- it is already possible, i just did not find the option
- it is much more complicated to realize than expected
- no one but me is interested in this feature

### mpv version and platform
0.24.0

### Reproduction steps
i added the following to my input.conf file:
```
W osd-bar add video-aspect -0.1
E osd-bar add video-aspect 0.1
```

### Expected behavior
Normaly playing the next video the video-aspect is changed to that of the new video.

### Actual behavior
When having pressed W or E that canged asspect-ratio is applied to all videos that play later.

### Why this is NOT a bug
I know that keeping a changed value and only resetting unchanged values is a feature. And that behavior should stay that way

### Possible workaround:
I could write a lua script setting video-aspect to the aspect of the current video that is triggered everytime the played file changes.

### Proposed solutions
1. It might be possible to apply a default reset to all properties that are initially loaded from the file-information. Thereby values like "volume", "brightness" ... would stay the same across videos, but "frames-per-second" ,"aspect" ... would also be reset when the video changes,
2. keep 1. as default, but add some configuration to it (this might get complicated)
3. and this is my favorite, because it solves the problem where it originated from, and it adds a whole lot of more possibilities:
 - add events as possible "keys" to the input.cont
 - add a "reset" command, that will put a property to the original value (the command-line or config-file or playback-file value) just like it is set when mpv ist started.

this way I could just write:
```
W osd-bar add video-aspect -0.1
E osd-bar add video-aspect 0.1
file-loaded reset video-aspect
```

and others may write stuff in the input.conf like:
= reset volume
file-loaded osd_show_property_text "${filename}"

Again I know that that can be done with Lua already, but it still would be a great feature to have a "reset" command in the input.conf.

**Comment by wiiaboo** [comment]
[`--reset-on-next-file=video-aspect`](https://mpv.io/manual/master/#options-reset-on-next-file)?

**Comment by mpvfeatures** [comment]
thx, it is a valid solution i did not know bout, still think the feature of having it in the input,conf to be trigged by a key or event is worth considering.

**Comment by wiiaboo** [comment]
It is already triggered by an event. More than that and you use lua scripting to hook to whatever event you need for your specific usecase. input.conf is for keys only.

**Comment by mpvfeatures** [comment]
valid point, what about putting those in an event.conf?
As a feature for people not skilled enough to write a Lua script (those might actually exist).

And lets not forget that the main feature request was about a "reset" command, witch imho would go well the whole set/add/multiply... commands, just so it can be used in the input.conf via keypress.
