### ISSUE TITLE
No response irregularly when quitting

### ISSUE THREAD

**Issue by ztxgeol** [mpv-player/mpv#4378]
### mpv version and platform
mpv 0.25.0 (Latest Release)
macOS 10.12.4 (16E195)

### Reproduction steps
Hard to Reproduce since there is no law.
### Expected behavior
Quit normally whether by hitting the red button on window or cmd+q.
### Actual behavior
Sometimes no response when quitting.
### Log file

http://sprunge.us/KbNS (This is the No Responsing one)

**Comment by Akemi** [comment]
i never saw this so the chances of me fixing it is nearly zero. is there no error report/backtrace?

**Comment by ztxgeol** [comment]
Here's normal one: [http://sprunge.us/RMXA](url)

**Comment by lazeran** [comment]
I had the same issue before and it started after I rebuilt mpv with version 0.24->0.25 (forgotten build numbers). Issue resolved after build b5b3aad.
