### ISSUE TITLE
Support --opengl-backend=backend1,backend2

### ISSUE THREAD

**Issue by Hummer12007** [mpv-player/mpv#4382]
It's no longer possible to have mpv working adequately (opengl backend and stuff) under BOTH Wayland and X11.
Due to the very unfortunate https://github.com/mpv-player/mpv/commit/bba08e38ff9842c4edf9da6a1d54066a01acd982 it no longer even tries to use wayland, if it can use X11. As a consequence, to actually use wayland backend, one has to specify `--opengl-backend=wayland` in the config. As a result, vo:opengl doesn't even try to use anything else under X11, so it fails miserably and mpv falls back to some legacy crap like xv, or whatever is available. Either the commit has to be reverted, or a way to specify multiple opengl backends (sorted by priority) has to be implemented (e.g. --opengl-backend=wayland,x11egl with obvious behavior).

**Comment by wm4** [comment]
Rejected.

**Comment by SirCmpwn** [comment]
This seems like a pretty good fix to the problem. No one loses. What's your problem, @wm4!

**Comment by Hummer12007** [comment]
Then how would you suggest to have mpv use the wayland backend under wayland and x11 backend under x11? Apart from stupid shit like creating an alias.

**Comment by haasn** [comment]
> Then how would you suggest to have mpv use the wayland backend under wayland and x11 backend under x11?

That's what auto-detection / probing is for, i.e. the `auto` setting.

**Comment by Hummer12007** [comment]
@haasn the mentioned commit "broke" the behavior: mpv no longer uses the wayland backend under wayland when Xwayland is available.

**Comment by haasn** [comment]
@Hummer12007 Ignore the wayland vs xwayland issue completely for the moment and focus merely on the question of whether or not `--opengl-backend` should support multiple options.

This doesn't make sense in isolation, because `auto` exists for picking the best backend in any situation; and I can't think of a strong use case for the list-style option. If you want to set an explicit backend, you can already do that.

**Comment by Hummer12007** [comment]
X11 backend is not the best backend in wayland situation. If I set the `wayland` backend, opengl won't work under X11 at all.

**Comment by haasn** [comment]
If you're using X11 then why are you setting the `wayland` backend?

**Comment by Hummer12007** [comment]
I'm occasionally using X11.

**Comment by SirCmpwn** [comment]
Lots of people find themselves switching between the two when their needs are better served by one or the other.

**Comment by haasn** [comment]
Perhaps bba08e3 could instead make the “--wayland” compile-time option default to off; that way it won't bother users except those who explicitly enable it, and presumably understand the drawbacks involved.
