### ISSUE TITLE
how can I use mpv to decode video ?

### ISSUE THREAD

**Issue by geraldzhang** [mpv-player/mpv#4386]
I want develop a mac app ,that can play VR video , how can I display the video frames myself use openGL?

**Comment by wm4** [comment]
You can let mpv render video into a framebuffer of your choice. Here's an example: https://github.com/mpv-player/mpv-examples/blob/master/libmpv/cocoa-openglcb/cocoa-openglcb.m

But mpv controls the video timing etc.
