### ISSUE TITLE
specifyable offset for image subtitles

### ISSUE THREAD

**Issue by hethhhhh** [mpv-player/mpv#4387]
### mpv version and platform
```
win64; mpv 0.25.0 built on Sun Apr 23 03:06:36 CEST 2017
ffmpeg version: N-85608-gbe1430a531
```

MKV files with PGS (bitmap subtitles) render on top of video, instead of the black area below
using --stretch-image-subs-to-screen works halfway, since the subs often go over the movie halfway.
so something like --image-subs-offset-x --image-subs-offset-y will be wonderful. 
also --image-subs-ratio would be great for too big/small subs
I know they are ugly and crap to work with, but most source is in that format, and many people don't convert them to text, when packing. Thank you for working on this.

**Comment by paulguy** [comment]
`--sub-pos` seems to be what you want.

**Comment by garoto** [comment]
Both binded to `t` and `r` by default.

**Comment by wiiaboo** [comment]
`sub-pos` doesn't affect bitmap subtitles.

**Comment by lachs0r** [comment]
Overlap with #1802
