### ISSUE TITLE
Change OSC Backcolor

### ISSUE THREAD

**Issue by RosadinTV** [mpv-player/mpv#4388]
Hi, is there any way to change the background color of the OSC?
I know the alpha value can be changed using --script-opts=osc-boxalpha=80 for example.
But what I would like to do is change the RGB value, to give it different colors (red, orange, pink, etc.)
Thanks.

**Comment by bitingsock** [comment]
If you disable the integral OSC (--no-osc) and put the external one in your scripts folder: https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua
you can change line 74 which contains styling for the backcolor. Currently, the part that reads "1c&H000000" is the hexcolor for the backdrop. Changing this to 1c&H0000FF for example would make it full red.

**Comment by ChrisK2** [comment]
We do not intend to make this configurable so if you really need to change the color, please use the method described above.

**Comment by RosadinTV** [comment]
@bitingsock Thank you very much, this is exactly what I was looking for.

**Comment by mxkrsv** [comment]
It's really trivial to make it user adjustable and I see no drawbacks of doing so. Any real arguments?

**Comment by UNIVPM-S1079707** [comment]
> It's really trivial to make it user adjustable and I see no drawbacks of doing so. Any real arguments?

It took me longer to figure out that I wasn't getting log messages because I disabled them in the config than to actually implement this.

#13948
