### ISSUE TITLE
External audio in .mka file with the same name doesn't played

### ISSUE THREAD

**Issue by Divetoxx** [mpv-player/mpv#4389]
Hello!
I am using new build for Windows 32 bit 2017-04-23.
If playing .mkv video the player doesn't recognize and doesn't play external audio which is stored in the .mka file with the same name and is placed in the same folder.
Previous windows build 2017-02-12 does play it.

Log: http://splushka.com/mpv_2017-04-23_windows.txt

**Comment by wiiaboo** [comment]
> ## Changed
> - options: change --audio-file-auto default to not to load any files
