### ISSUE TITLE
External audio files

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#4390]
Is this still a thing? I'm pretty sure this worked up until I updated mpv to the latest version, and now it just doesn't get recognized. It probably works through command line, but I'm talking about a more UX-friendly method - having an audio file and a video file on the same folder, with the same name, and then opening the video and get the external audio to show up when changing tracks. I tried with different video/audio combinations - nothing shows up other than internal audio.

**Comment by CounterPillow** [comment]
See #4389 and read the changelogs.
