### ISSUE TITLE
Make OSC font size adjustable

### ISSUE THREAD

**Issue by sleek22** [mpv-player/mpv#4392]
It's great having the new title feature in the OSC but with the large font and a long title, information is cut off on the right side.

I have it such that the OSC displays the title, file size, bitrate, aspect ratio, and volume. A smaller font size would allow even more file information without it being cut off.

I am using the Windows version of mpv.

**Comment by ChrisK2** [comment]
No. See #4388.

**Comment by sleek22** [comment]
If I go the route of disabling the OSC and using osc.lua, is it possible to change the font size there? If so, what would be the line that I would change or insert there?

**Comment by ChrisK2** [comment]
https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L73

``\\fs12`` sets the font size.

**Comment by sleek22** [comment]
vidtitleBar = "{\\blur0\\bord0\\1c&HFFFFFF\\3c&HFFFFFF\\fs18\\q2}",

It was actually a few lines down on line 80 as above. I changed to a lower fs value and it is working great.

Thank you so much for the help.
