### ISSUE TITLE
JSON IPC and multiple external-file

### ISSUE THREAD

**Issue by maiorfi-at-innovactive** [mpv-player/mpv#4394]
It seems that this subject has been already discussed here and there, but I did not spot yet how to properly format json ipc message related to multiple external-file options.

I would like to use lavfi-complex property in order to get a 2x2 tiling with a loadfile command and 3 external-file items.

Thanks!

**Comment by wm4** [comment]
You have to set this as a mpv_node with the format set to MPV_FORMAT_NODE_ARRAY. Each array item would be a string with the filename of an external file.

It's not possible to set this as a simple string, because filenames could contain `,` (or any other separator that could be used).

**Comment by maiorfi-at-innovactive** [comment]
Sorry for reiterating on this, but I'm still wondering whether it is possible (and, in that case, how) express a mpv_node with MPV_FORMAT_NODE_ARRAY using JSON-IPC notation.

Thanks.

**Comment by wm4** [comment]
sure, if you use json IPC, it should accept a json array of strings.

**Comment by maiorfi-at-innovactive** [comment]
Actually I thought I could, but I tried with following two ways, without success (here you can find request command and reply event):

```json
{ "command": ["set_property", "external-file", ["file1","file2"] ] }
{"error":"invalid parameter"}
{ "command": ["set_property", "external-file", "file1", "file2" ] }
{"error":"invalid parameter"}
```

**Comment by wm4** [comment]
That should have worked, but didn't because it restricted nesting so that passing the file array was not possible. I fixed it now.

**Comment by maiorfi-at-innovactive** [comment]
Great, thanks!
