### ISSUE TITLE
change seek / jump time span when using keys arrow-right / left

### ISSUE THREAD

**Issue by drorbemet** [mpv-player/mpv#4396]
I dindn't find a description on configuring the default seek time spans when using modifier-arrow-keys on an instance of mpv with a gui-window.
### mpv version and platform
I am using mpv 0.24.0 on linux with gnome-desktop currently.

### Reproduction steps
Use (shift)-arrow-right / arrow-left to jump backward / forward.

### Expected behavior
I would like to jump / seek exactly 3 seconds using (shift)-arrow-left/right.

I get this behaviour using command line tools:
echo '{ "command": ["seek", "-3", "relative", "exact"] }' | socat - /tmp/mpvsocket

A configuration entry in some mpv config file like
~/.config/mpv/mpv.conf

### Actual behavior
The default behaviour known to me is a jump by approximately 5 to 6 seconds which is to much or using shift 1 second which is to small for my use case.

**Comment by wiiaboo** [comment]
https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L47-L57

Just change yours to have different values?

**Comment by drorbemet** [comment]
Ok mpv has a config file. I didn't had one untill now. Thanks for the link on the input.conf template.

**Comment by LeonCheung** [comment]
Thanks guys, you all saved me so much work!

**Comment by Josehkn** [comment]
Thanks!

**Comment by EsmaeilSaleh** [comment]
Thanks

**Comment by srezasm** [comment]
I added the following lines at the end of the mpv.conf

```
RIGHT seek  5
LEFT  seek -5
```

and it works, but every time I open a video from the command line, it prints the following error:

```
/home/user/.config/mpv/mpv.conf:10: unparseable extra characters: 'seek  5'
/home/user/.config/mpv/mpv.conf:11: unparseable extra characters: 'seek -5'
```

**Comment by Hrxn** [comment]
Keybinds belong in `input.conf` and not in `mpv.conf`.

**Comment by clot27** [comment]
For those still not working, try adding `exact` after assigning seek duration, like:
```
RIGHT 5 exact
LEFT 5 exact
```

**Comment by All3xJ** [comment]
> For those still not working, try adding `exact` after assigning seek duration, like:
> 
> ```
> RIGHT 5 exact
> LEFT -5 exact
> ```

of course he meant
```
RIGHT seek 5 exact
LEFT seek -5 exact
```
