### ISSUE TITLE
Can't search with GUI on very long videos

### ISSUE THREAD

**Issue by tsoernes** [mpv-player/mpv#4397]
mpv git-591d99a (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Apr 22 13:57:19 CEST 2017
ffmpeg library versions:
   libavutil       55.61.100
   libavcodec      57.93.100
   libavformat     57.72.101
   libswscale      4.7.101
   libavfilter     6.85.100
   libswresample   2.8.100
ffmpeg version: N-85601-g4925537
![screenshot from 2017-05-03 21-34-35](https://cloud.githubusercontent.com/assets/6782404/25678009/8d035522-3048-11e7-9c9b-b6f296cb3605.png)

**Comment by wiiaboo** [comment]
Thanks for not following the issue template. We will be sure to fix your issue prompty with absolutely no information.

**Comment by wiiaboo** [comment]
This video is probably https://www.twitch.tv/videos/138401861, but it works fine on my side. No double-negative or weird timestamps.

**Comment by CounterPillow** [comment]
I get a double negative, just jump to the "end" of the video, which is not the actual end; it plays past it and goes in the negative for time remaining. It's a problem with HLS and estimating the length of it, if I remember correctly.

```
mpv 0.25.0-26-gde225e3a6a (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed May  3 09:41:32 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3
```

So, the real issue is that video lengths with HLS are broken.

**Comment by tsoernes** [comment]
So take this video for example: https://www.twitch.tv/videos/138383659?t=3h49m38s
There's about 5 minutes left of the video when you start. Press right arrow in order to jump a couple of seconds ahead.  The timestamps get all messed up, the video starts playing from the beginning. The seek bar shows the correct time, but it's no longer possible to jump.
