### ISSUE TITLE
skipping unknown ALSA channel map: FL FR FC LFE SL SR SL SR

### ISSUE THREAD

**Issue by xswqaz** [mpv-player/mpv#4399]
### mpv version and platform

mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Apr 23 12:26:53 CEST 2017

### Reproduction steps

I added on the fly ac3 encode to mpv.conf

af=scaletempo,lavcac3enc 
audio-device=alsa/iec958:CARD=Device,DEV=0  # audio device which has spdif

### Expected behavior

ac3 5.1ch output was expected

### Actual behavior

Failed to encode ac3? (not ac3 but s16)

### Log file

[af] Adding filter lavrresample 
[af] Audio filter chain:
[af]   [in] 48000Hz 5.1 6ch floatp
[af]   [lavrresample] 48000Hz 5.1 6ch float [a]
[af]   [scaletempo] 48000Hz 5.1 6ch float
[af]   [volume] "softvol" 48000Hz 5.1 6ch float
[af]   [out] 48000Hz 5.1 6ch float
[af]   [ao] 48000Hz 5.1 6ch float
[ao] Trying audio driver 'alsa'
[ao] Using preferred device 'iec958:CARD=Device,DEV=0'
[ao/alsa] requested format: 48000 Hz, 5.1 channels, float
[ao/alsa] using ALSA version: 1.1.3
[ao/alsa] opening device 'iec958:CARD=Device,DEV=0'
[ao/alsa] trying format float
[ao/alsa] trying format double
[ao/alsa] trying format s32
[ao/alsa] trying format s24
[ao/alsa] trying format s16
[ao/alsa] skipping unknown ALSA channel map: FL FR FC LFE SL SR SL SR
[ao/alsa] Disabling multichannel output.
[ao/alsa] Channel layouts:
[ao/alsa]  - stereo
[ao/alsa]  - 3.1
[ao/alsa]  - 5.1(side)
[ao/alsa] result: stereo
[ao/alsa] Going to set final HW params:
[ao/alsa] ---
[ao/alsa] ACCESS:  RW_INTERLEAVED
[ao/alsa] FORMAT:  S16_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: 16
[ao/alsa] FRAME_BITS: 32
[ao/alsa] CHANNELS: 2
[ao/alsa] RATE: 48000
[ao/alsa] PERIOD_TIME: 15625
[ao/alsa] PERIOD_SIZE: 750
[ao/alsa] PERIOD_BYTES: 3000
[ao/alsa] PERIODS: 16
[ao/alsa] BUFFER_TIME: 250000
[ao/alsa] BUFFER_SIZE: 12000
[ao/alsa] BUFFER_BYTES: 48000
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] channel map reported by ALSA: FL FR
[ao/alsa] which we understand as: stereo
[ao/alsa] which is what we requested.
[ao/alsa] hw pausing supported: yes
[ao/alsa] buffersize: 12000 samples
[ao/alsa] period size: 750 samples
[ao/alsa] device buffer: 12000 samples.
[ao/alsa] using soft-buffer of 12000 samples.
[cplayer] AO: [alsa] 48000Hz stereo 2ch s16

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wm4** [comment]
The ac3 conversion filter is somehow not active, but due to the log being cut off I can't see why.

**Comment by xswqaz** [comment]
I found this log. But why removing filter?

[cplayer] first video frame after restart shown
[af] Adding filter scaletempo 
[af] Adding filter lavcac3enc 
[af] Adding filter lavrresample 
[af] Removing filter lavcac3enc

**Comment by wm4** [comment]
I won't guess.

No information -> no bug.
