### ISSUE TITLE
Timed text subtitle/dfxp playback support

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#4401]
I am on 0.25 and I cannot play timed text subtitles as used by Netflix, they use the dfxp extension. The player says "Can not open external file bug.dfxp" (there should be "cannot" instead of "can not" by the way). I include a sample file below.

### Sample files
[bug.dfxp.zip](https://github.com/mpv-player/mpv/files/976347/bug.dfxp.zip)

**Comment by wiiaboo** [comment]
That's a feature request for FFmpeg/Libav, not mpv.

**Comment by felagund** [comment]
I see. The corresponding bug reports seem to be https://trac.ffmpeg.org/ticket/4859 and https://trac.videolan.org/vlc/ticket/14974 for VLC.

**Comment by wm4** [comment]
Yes, that has to be implemented in ffmpeg. Though not sure if there's anyone interested in doing it.
