### ISSUE TITLE
xinerama and screensaver disable options

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4404]
Hi,

It seems, that Xinerama and xscreensaver support is now hardcoded, that is they can't be disabled at configure time?

https://bugs.gentoo.org/show_bug.cgi?id=617516

Is it possible to have xinerama's and screensaver's disable options back?

Regards,
Alex

**Comment by CounterPillow** [comment]
See https://github.com/mpv-player/mpv/commit/927afa311d4a89b022305508acbf4e7325fe3928

**Comment by wm4** [comment]
No.

**Comment by fhlfibh** [comment]
That way it looks more as an attempt to fix something that isn't broken...
Don't know about others, but in my system mpv worked happily without xinerama, xv, or xscreensaver (even though it was compiled from source every other week).

**Comment by wm4** [comment]
These libs are tiny. Stop annoying us with shit that doesn't matter at all.
