### ISSUE TITLE
Option --linear-scaling not found

### ISSUE THREAD

**Issue by Gooberpatrol66** [mpv-player/mpv#4405]
mpv Rock*.mp4 --linear-scaling

Error parsing option linear-scaling (option not found)
Setting command line option '--linear-scaling=' failed.

Exiting... (Fatal error)

**Comment by wiiaboo** [comment]
What's the version? Respect the issue template, please.

**Comment by Gooberpatrol66** [comment]
It's the most recent version. The template says to use the most recent version before reporting bugs.

**Comment by wiiaboo** [comment]
"Recent version" doesn't say absolutely nothing useful.

**Comment by wm4** [comment]
The issue template also says to post a log.

**Comment by wm4** [comment]
@CounterPillow said he wants to give you tech support, so whatever.

**Comment by CounterPillow** [comment]
According to a quick google search of your username, you appear to be using Ubuntu judging by your AskUbuntu account.

The version of mpv shipped in Ubuntu's repositories is **not** the most recent version. Ubuntu is a distribution with a "stable" release cycle, which means they ship outdated software.

The "most recent" sentence in the issue template is to tell you to not report bugs with your distro's ancient mpv versions.

**Comment by Gooberpatrol66** [comment]
I'm actually using Gentoo now.

It turns out there was a disconnect between what was installed and what portage was telling me was keyworded so...yeah.
