### ISSUE TITLE
Windows failure (v0.25.0)

### ISSUE THREAD

**Issue by SeaHOH** [mpv-player/mpv#4406]
### mpv version and platform
mpv: 0.25.0 / Windows build 2017-04-23 64-bit
platform: Windows 7 sp1 x64
CPU: AMD A6 / Llano
~GPU: AMD Radeon HD 6530D~  **There is a mistake**
GPU: AMD Radeon HD 6670

### Actual behavior
In mpv 0.24.0, everything is OK. This happens in mpv 0.25.0.
Sometimes, when I fullscreen or close the mpv windows, the OS is down,  resulting in I must reboot my PC.

### Log file
Sorry,  there is no logs. I do not know what happend.

### Sample files

**Comment by wm4** [comment]
Post logs with -v or --log-file=log.txt with mpv 0.24.0 and 0.25.0 (both of them).

**Comment by Hrxn** [comment]
Other applications that utilize significant GPU resources in any way run without issues?

**Comment by SeaHOH** [comment]
@wm4 
It is not happens everytime, and OS is down when happend, so I can not get logs.
I have used `hwdec=dxva2-copy`, then I will test without any hwdec, the result will reported here in few days.

@Hrxn 
No problem.

**Comment by avih** [comment]
Try also adding to your config file: `angle-egl-windowing=yes` - https://mpv.io/manual/master/#options-angle-egl-windowing

It can sometimes help cases similar to yours, which probably happen due to buggy GPU drivers.

**Comment by SeaHOH** [comment]
@avih 
This not work for me, my config is `opengl-es=no` and `opengl-backend=win`, not use `angle`.

**Comment by wm4** [comment]
Oh, you're saying such an important fact only now?

This is exactly the reason why we want people to post logs. The issue template is here for a reason.

If your next post doesn't come with a log, I'll just lock the issue. We're developers, not tech support for stupid people.

**Comment by lachs0r** [comment]
@SeaHOH 
If your OS crashes, that’s a driver bug. You can still try to get logs by using the `--log-file` option, but they’re probably going to be incomplete if the crash happens before they’re written to disk.

**Comment by SeaHOH** [comment]
Of course the log was incompleted. If you need it, I will try to get it.

@wm4 Do not call me stupid, I do not like it.

**Comment by SeaHOH** [comment]
Of course the log was incompleted. If you need it, I will try to get it.

@wm4 Do not call me stupid, I do not like it.

**Comment by SeaHOH** [comment]
Sorry, I think about that the write operation is not safe for my disk when OS crashes, I have give up to get a log.

I will still report the result of config is `hwdec=no` here in few days later.

**Comment by SeaHOH** [comment]
I have set the log file to a flash memory disk. So, I got it.

[mpv.log.txt](https://github.com/mpv-player/mpv/files/981724/mpv.log.txt)
This time, the OS does not crashed, but does not responding for some seconds when fullscreen.

**Comment by avih** [comment]
Please post the full log, from the beginning, as it includes important configuration info.

**Comment by SeaHOH** [comment]
The log file is too long, this is the beginning.
[mpv.log-b.txt](https://github.com/mpv-player/mpv/files/981785/mpv.log-b.txt)

**Comment by avih** [comment]
> this is the beginning.

It's not.

**Comment by SeaHOH** [comment]
Why??

**Comment by avih** [comment]
Because it's missing the start where it states the mpv version, config files, config options, etc. Like this:

```
[   0.008][v][cplayer] Command line options: '--idle' '--log-file=my.log'
[   0.008][v][cplayer] mpv 0.25.0-103-gb0d5a38 (master-e2b9551 +JS) (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[   0.008][v][cplayer]  built on Sat May  6 03:33:05 IDT 2017
[   0.008][v][cplayer] ffmpeg library versions:
[   0.008][v][cplayer]    libavutil       55.61.100
[   0.008][v][cplayer]    libavcodec      57.94.101
[   0.008][v][cplayer]    libavformat     57.72.101
[   0.008][v][cplayer]    libswscale      4.7.101
[   0.008][v][cplayer]    libavfilter     6.88.100
[   0.008][v][cplayer]    libswresample   2.8.100
[   0.008][v][cplayer] ffmpeg version: git-859cc5c [built 2017-05-06]
[   0.008][v][cplayer]
[   0.008][v][cplayer] Configuration: ./waf configure --enable-static-build --disable-debug --disable-caca --lua=luajit --enable-libarchive --enable-encoding
[   0.008][v][cplayer] List of enabled features: asm atomics avutil-imgcpy-uc build-date c11-tls cplayer cuda-hwaccel d3d-hwaccel direct3d dlopen dos-paths egl-angle egl-helpers encoding gcc-tls gl gl-dxinterop gl-win32 glob-win32-replacement gnuc iconv is_ffmpeg javascript jpeg lcms2 libarchive libass libass-osd libav libavcodec libavdevice libbluray libm lua luajit mingw noexecstack optimize posix-or-mingw sse4-intrinsics static-build stdatomic subprocess tv uchardet wasapi win32 win32-internal-pthreads zlib
[   0.010][v][cplayer] Reading config file C:\Users\<user>\AppData\Roaming/mpv/mpv.conf
[   0.010][v][cplayer] Setting option 'priority' = 'abovenormal' (flags = 4)
[   0.010][v][cplayer] Setting option 'osd-duration' = '3000' (flags = 4)
[   0.010][v][cplayer] Setting option 'autofit-larger' = '90%x90%' (flags = 4)
[   0.010][v][cplayer] Setting option 'script-opts' = 'osc-boxmaxchars=100,osc-hidetimeout=1000,osc-deadzonesize=0,osc-layout=box,osc-seekbarstyle=bar,osc-vidscale=no,osc-scalewindowed=2,osc-scalefullscreen=2,osc-title=${+osd-playing-msg}' (flags = 4)
[   0.010][v][cplayer] Setting option 'force-window' = 'immediate' (flags = 4)
[   0.010][v][cplayer] Setting option 'ytdl-format' = 'bestvideo[fps=60][height<=1080]+bestaudio/bestvideo[height<=1080]+bestaudio/best' (flags = 4)
[   0.010][v][cplayer] Setting option 'ytdl-raw-options' = 'write-auto-sub=,sub-lang=en,write-sub=' (flags = 4)
[   0.010][v][cplayer] Setting option 'hwdec' = 'auto' (flags = 4)
[   0.010][v][cplayer] Setting option 'vo' = 'opengl' (flags = 4)
[   0.010][v][cplayer] Setting option 'correct-downscaling' = '' (flags = 4)
[   0.010][v][cplayer] Setting option 'dscale' = 'mitchell' (flags = 4)
[   0.010][v][cplayer] Setting option 'angle-egl-windowing' = 'yes' (flags = 4)
[   0.010][v][cplayer] Setting option 'sub-pos' = '70' (flags = 4)
[   0.010][v][cplayer] Setting option 'sub-use-margins' = 'no' (flags = 4)
...
```

etc etc.

**Comment by SeaHOH** [comment]
I just put `log-file=my.log` in mpv.conf, it is must run in command line?

**Comment by avih** [comment]
> it is must run in command line?

No. It's OK in `mpv.conf`.

But this log is still missing the start. Either it's corrupted only at the start, or something in your startup (batch file? lua script?) messes with it. Both are very weird.

**Comment by avih** [comment]
> But this log is still missing the start

Apologies. Apparently it shows the mpv version and build options only when setting a log file from command line.

The log is probably enough. Sorry again.

**Comment by SeaHOH** [comment]
[fulllog.txt](https://github.com/mpv-player/mpv/files/981828/fulllog.txt)
OK, I got it by use '--msg-level=all=trace --log-file=S:\log.txt' in command line.
But it is not the same issues.

**Comment by SeaHOH** [comment]
@wm4 @lachs0r @avih 
It seems work well without hardware decoding, no crashed or slow down happend.

**Comment by lachs0r** [comment]
Well, we’ve learned nothing from that. This is most certainly a driver bug we can’t do anything about anyway. Try not to use hwdec then.

**Comment by SeaHOH** [comment]
Maybe you are right, the type of the card is too old. Thanks to check this issues.
