### ISSUE TITLE
CUDA decoding and stuff with Nvida's SDK 8

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4409]
Hi,

Afaik, Nvidia recently released their Codec SDK 8 https://developer.nvidia.com/nvidia-video-codec-sdk
Can you please fix CUDA (or maybe VDPAU) hevc decoding that wanted that SDK-8, as far as i remember.

Regards,
Alex

**Comment by fhlfibh** [comment]
There were already issues with templates on the topic, that were not solved nevertheless. 
E.g. https://github.com/mpv-player/mpv/issues/4115 or https://github.com/mpv-player/mpv/issues/4074 of myself.

Anyway, it's rather a "feature request".

**Comment by wm4** [comment]
These issues were closed.

From this issue, it's not known whether it's a bug report (about what?) or a feature request (about what?) or something else. Are we supposed to guess? I'd rather not, so bye.
