### ISSUE TITLE
observe_property doesn't work with JSON IPC

### ISSUE THREAD

**Issue by freijon** [mpv-player/mpv#4410]
### mpv version and platform

using: Arch Linux 64-bit
tried with: mpv-git from the AUR

### Reproduction steps

Register the obervation of a property with the command:
`echo '{ "command": ["observe_property", 999, "pause"] }' | socat - /tmp/mpvsocket`
result:
`{"error":"success"}`

### Expected behavior

As soon as the property changes (in this case when I pause the player) I would expect this event:
`{ "event": "property-change", "id": 999, "data": true, "name": "pause" }`

### Actual behavior

No event is shown

### Log file

[Output logfile](https://gist.github.com/freijon/6b7f2a6401fe818e4551ef76abe4040e)

**Comment by wiiaboo** [comment]
Did you try with `--no-config`?

**Comment by freijon** [comment]
Just tried it with --no-config. Same behavior.
Yes, by AUR I mean the Arch User Repository. mpv-git installs the git master version. I also tested it with the official Arch package for mpv (mpv 0.25)

**Comment by wiiaboo** [comment]
AUR isn't a platform. It's a repository for building scripts which you can use anywhere, not just Archlinux.

**Comment by freijon** [comment]
I updated the issue description to clarify the platform

**Comment by wm4** [comment]
You would expect this event where? Property notifications are per client, so if you disconnect the client (like a single socat invocation will do), the property notification will be deleted with the client.

**Comment by freijon** [comment]
I'm writing a client which connects to the socket and reads it's output. But you can do the same with socat if you don't provide a stdin. Just use:
 `
socat - /tmp/mpvsocket
`. 
It will stay connected and show the events. Except for the observed property.

**Comment by freijon** [comment]
That would explain the behavior. I'll close the issue and reopen it in case it still doesn't work with the client I'm writing. I used socat for fast debugging/testing purposes but never tested it with my client. Thanks!
