### ISSUE TITLE
Regression : cuda - Could not open codec

### ISSUE THREAD

**Issue by pat357** [mpv-player/mpv#4411]
### mpv version and platform
mpv 0.25.0-44-ge2b955121 + every version from git I got after 2017-05-06.
My build from 2017-05-03 is the latest version I have without the issue. The next build I made was 2017-05-06 is affected (has the issue), just like all my later builds.
I suspect this issue has something to do with this update :  5757db844a449ed6a1e0fadb2bd62bae6852c78a
( = cuda: add new way to set cuda context on cuvid codecs ) dated 2017-05-05

Platform : Win7sp1 64bit / GTX680 with drivers v378.78 (GTX680 = only 8bit on HW decoding)

### Reproduction steps
Media I've tested are normal progressive H264 YUV420P8 containers (mp4,mkv,mov,..).
Download MPV from https://sourceforge.net/projects/mpv-player-windows/files and take build 20170506-git-e2b9551(x64) or build from current git.
```
mpv --no-config --vo opengl --hwdec=cuda --opengl-backend=dxinterop --video-sync=display-resample "k:\film\Battlefield_3_Fault_Line_Full_Trailer.mov" 

Playing: k:\film\Battlefield_3_Fault_Line_Full_Trailer.mov
 (+) Video --vid=1 (*) (h264 1920x1080 60.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
Could not open codec. <-------------------------|
AO: [wasapi] 48000Hz stereo 2ch float
VO: [opengl] 1920x1080 yuv420p
AV: 00:00:09 / 00:12:07 (1%) A-V:  0.000 DS: 1.000/0
```
### Expected behaviour
Player uses **CUDA  (h264_cuvid) for decoding** the h264 stream, just like all builds before 2017-05-03 (I used x64 build).
Unaffected, but older build from lachs0r : https://mpv.srsfckn.biz/ and pick the one dd. 20170423.
```
Playing: k:\film\Battlefield_3_Fault_Line_Full_Trailer.mov
 (+) Video --vid=1 (*) (h264 1920x1080 60.000fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
AO: [wasapi] 48000Hz stereo 2ch float
Using hardware decoding (cuda).  <-------------------------|
VO: [opengl] 1920x1080 cuda[nv12]
AV: 00:00:06 / 00:12:07 (0%) A-V:  0.000
```

### Actual behaviour
Actual behaviour changed somewhere between 2017-05-03 and 2017-05-06.
For builds (from git, of course) from 2017-05-06 and *all* later versions  : player gives an error "**could not open codec.**" and falls back to **software decoding**.
The build from 2017-05-03 and all earlier versions have no problem using Cuda/h264_cuvid decoding using the same command and the same files.

### Log file
http://sprunge.us/eNAF 

### Sample files
Happens with every h264 file I've tried.

**Comment by pavelxdd** [comment]
Same issue here on Windows 10 / GTX 1080 Ti

**Comment by garoto** [comment]
Is your ffmpeg up-to-date?

**Comment by pat357** [comment]
Yes, before compiling MPV, I always compile ffmpeg straight from git !

**Comment by pat357** [comment]
I was able to narrow down the cause of this problem to commit https://github.com/mpv-player/mpv/commit/5757db844a449ed6a1e0fadb2bd62bae6852c78a .
I checked out to commit before above (one commit earlier) and after recompiling ffmpeg to latest Git, the compiled MPV was 100% OK.
Did the same for commit https://github.com/mpv-player/mpv/commit/5757db844a449ed6a1e0fadb2bd62bae6852c78a and the problem was there.
Now I'm 100% sure that this commit is causing this issue.

**hwdec=cuda** didn't work with later versions (**could not find codec**) but **hwdec = cuda-copy** does work !! I find this strange because **both use the **same** underlying ffmpeg h264_cuvid** !!

If I compare the logs from hwdec=cuda  vs  hwdec=cuda-copy.
1. hwdec=cuda-copy (working)
```
[   0.249][v][vo/opengl] No advanced processing required. Enabling dumb mode.
[   0.249][v][vo/opengl/win32] DPI detected from the old API: 101
[   0.249][v][vo/opengl/win32] display-fps: 60.000000
[   0.257][v][vo/opengl/win32] color-profile: C:\Windows\system32\spool\drivers\color\CalibratedDisplayProfile-5.icc
[   0.257][v][vo/opengl] Assuming 60.000000 FPS for display sync.
[   0.257][v][vd] Container reported FPS: 60.000000
[   0.257][v][vd] Codec list:
[   0.257][v][vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[   0.257][v][vd]     h264_qsv (h264) - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (Intel Quick Sync Video acceleration)
[   0.257][v][vd]     libopenh264 (h264) - OpenH264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[   0.258][v][vd]     h264_cuvid (h264) - Nvidia CUVID H264 decoder
[   0.258][v][vd] Opening video decoder h264
[   0.258][v][vd] Probing 'cuda-copy'...
[   0.258][v][vd] Trying hardware decoding.
[   0.258][v][vd] Using underlying hw-decoder 'h264_cuvid'
[   0.358][v][ffmpeg/video] h264_cuvid: CUVID capabilities for h264_cuvid:
[   0.358][v][ffmpeg/video] h264_cuvid: 8 bit: supported: 1, min_width: 48, max_width: 4096, min_height: 16, max_height: 4096
[   0.358][v][ffmpeg/video] h264_cuvid: 10 bit: supported: 0, min_width: 0, max_width: 0, min_height: 0, max_height: 0
[   0.358][v][ffmpeg/video] h264_cuvid: 12 bit: supported: 0, min_width: 0, max_width: 0, min_height: 0, max_height: 0
[   0.358][v][vd] Selected video codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
```

2. hwdec=cuda (not working)
```
[   0.239][v][vo/opengl] No advanced processing required. Enabling dumb mode.
[   0.239][v][vo/opengl] Loading hwdec driver 'cuda'
[   0.331][v][vo/opengl/win32] DPI detected from the old API: 101
[   0.331][v][vo/opengl/win32] display-fps: 60.000000
[   0.338][v][vo/opengl/win32] color-profile: C:\Windows\system32\spool\drivers\color\CalibratedDisplayProfile-5.icc
[   0.338][v][vo/opengl] Assuming 60.000000 FPS for display sync.
[   0.339][v][vd] Container reported FPS: 60.000000
[   0.339][v][vd] Codec list:
[   0.339][v][vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[   0.339][v][vd]     h264_qsv (h264) - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (Intel Quick Sync Video acceleration)
[   0.339][v][vd]     libopenh264 (h264) - OpenH264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[   0.339][v][vd]     h264_cuvid (h264) - Nvidia CUVID H264 decoder
[   0.339][v][vd] Opening video decoder h264
[   0.339][v][vd] Probing 'cuda'...
[   0.339][v][vd] Trying hardware decoding.
[   0.339][v][vd] Using underlying hw-decoder 'h264_cuvid'
[   0.339][e][vd] Could not open codec.
[   0.339][v][vd] Falling back to software decoding.
[   0.339][v][vd] Detected 12 logical cores.
[   0.339][v][vd] Requesting 13 threads for decoding.
[   0.340][v][vd] Selected video codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)

**Comment by garoto** [comment]
[**@pat357**](https://github.com/pat357) commented on [May 18, 2017, 3:56 PM GMT-3](https://github.com/mpv-player/mpv/issues/4411#issuecomment-302509634 "2017-05-18T18:56:34Z - Replied by Github Reply Comments"):
> Yes, before compiling MPV, I always compile ffmpeg straight from git !

Are you the shinchiro dude that puts out those git builds on sf.net?

**Comment by monarc99** [comment]
i have similar problems on linux, but i think my nvidia drivers (375) too old, because commit comment from https://github.com/FFmpeg/FFmpeg/commit/17f63d98e679e88a64f96e4aefba57b12ca29a0c 

compat/cuda: update cuvid/nvdec headers to Video Codec SDK 8.0.14
This raises the required minimum NVIDIA display driver versions:
NVIDIA Linux display driver 378.13 or newer
NVIDIA Windows display driver 378.66 or newer

at the moment i wait for new stable drivers.

**Comment by pat357** [comment]
No, I'm not shinchiro. 
I was also testing the versions available on sf.net, that's all.

**Comment by pat357** [comment]
Hmm.... My drivers are 378.78 and I still have the issue : cuda-copy is ok but for cuda I get "**Could not open codec**".
If additional info is required/wanted (besides the one already here), just ask.

**Comment by jane1969** [comment]
Hi,
I face the same problem. I use mpv on a laptop (W8.1) with nvidia gpu to show outside diving videos at high resolution, colors and rate (for slowdown purpose), and I can no longer make it work since last version. It returns the error "could not open codec" with both avc and hevc encoded videos.
On the workstation I use to encode videos, I can reckon on software decoding, but not on the laptop. I tried several combinations of settings but none runs properly. Curiously, cuda-copy still works, but with 60 fps videos, it is very laggy. I tried again with former version, and except for cuda decoding working fine, other options acted the same. The only setting that could play 60 fps hi-res video was dxva2, but when the laptop is plugged on an external monitor with 10-bit capability, colours remain washed whatever other setting I use on the renderer.
I believe that the trouble cannot come from my computer nor driver as 0.25 has no problem.
I hope mpv still gets support and has not been abandoned, as I really enjoyed it with smplayer for its simplicity and low requirements. For now, I remain on previous versions, but it would be a pity to miss new features on next ones because of this.
Maybe I am doing something wrong and a solution already exists ?
Thanks.

**Comment by fhlfibh** [comment]
@jane1969 https://github.com/mpv-player/mpv/issues/4742

**Comment by wm4** [comment]
Well, if someone wants to add the configure test that enables the new ffmpeg code for this on Windows, I wouldn't mind. Otherwise just wait until we drop support for older ffmpeg versions.

**Comment by jane1969** [comment]
I do apologize, I did not intent to wake up a former conflict (people can be so passionate !), I should have read closed issues also before posting.
So I will just wait (I am just unable to perform that "configure test" you talk about). Anyway, 0.25 gives me full satisfaction.
Thanks.

**Comment by Akemi** [comment]
most likely fixed. if not please open a new issue.
