### ISSUE TITLE
panscan no longer working on OS X Yosemite

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#4412]
### mpv version and platform
Problem occurs with mpv version 0.23.0 or later on OS X 10.10.5 Yosemite.
Not a problem with 0.22.0 or earlier on Yosemite.
Not a problem with any mpv version on 10.12.4 Sierra.
Not tested on other versions of OS X.

### Reproduction steps
Playing eg. a 640x480 video file containing a letterboxed 16:9 image, on a 1080p monitor.
Press the 'f' key to go fullscreen, then press the 'e' key repeatedly to set panscan=1.0

### Expected behavior
The video will "zoom in" until the left and right sides touch the sides of the screen. Black bars from the letterboxing will disappear off the top and bottom of the screen.

### Actual behavior
The OSD indicates that the panscan value is increasing, but nothing happens to the image.

### Log file
Log of mpv 0.25.0 on OS X 10.10.5 (fail):
http://sprunge.us/OICB
Log of mpv 0.22.0 on OS X 10.10.5 (success):
http://sprunge.us/TATR
Log of mpv 0.25.0 on macOS 10.12.4 (success):
http://sprunge.us/cXUD

**Comment by Akemi** [comment]
for whatever reason it resizes (reports) the fullscreen window to 1440x1080 instead of staying at 1920x1080. i don't have a 10.10 system so i can't really test it.

**Comment by sumyungguy** [comment]
Another observation, after I set panscan=1.0 on the command line. When I go to full screen, at first the image is expanded to fill the width as I expect. But about one second later, it resizes down again, all on its own.

Even when going full screen without panscan, there's always a small glitch about one second later. I guess it's something to do with the transition into a new space, as the delay seems to correspond to the same amount of time as the animation for that.

**Comment by Akemi** [comment]
10.10 is too old to make a specific fix for that version, since the bug doesn't exist on newer versions anymore.
