### ISSUE TITLE
Can't seek after pause in udp stream

### ISSUE THREAD

**Issue by lionep** [mpv-player/mpv#4413]
### mpv version and platform

Reproduced on linux : mpv 0.25.0 (ubuntu 16.04 and on Mac OS Sierra)

### Reproduction steps

- Play a video (tested with udp multicast stream) with options --force-seekable=yes, --no-cache-pause
- Pause the video for 10 seconds with spacebar
- Play the video with spacebar
- Press > to seek

### Expected behavior

- Seeking if cache is seconds is more than 5, else return to live play

### Actual behavior

- Nothing happens, no seek is done.

### Log file

http://sprunge.us/WfDY

### Sample files

Sample stream comes from this kind of hardware : 
https://www.tbsdtv.com/products/tbs2603-hd-hdmi-video-encoder.html

Is there any option to apply or command to send to return to the live stream ?  
This stream is played on several PC on the same network, the stream server is also on the same network, and after some times, some PC are desynchronizing.
At this time, the best options are : `---no-audio --video-sync=desync --no-initial-audio-sync --no-cache --untimed` to desynchronize the less possible. But I lose audio and audio sync with this solution.

**Comment by wm4** [comment]
libavformat returns a failure code for whatever reasons:
```
[  13.465][v][lavf] Seek failed (Operation not permitted)
```
Not sure why that happens.

You could try the `drop-buffers` command.

**Comment by Akemi** [comment]
no reply. also a lot changes since 0.25, if the problem still persists we can reopen this.
