### ISSUE TITLE
Built-In GUI not scaling with the window

### ISSUE THREAD

**Issue by hhiru** [mpv-player/mpv#4417]
### Sample files

![mpv_too_small](https://cloud.githubusercontent.com/assets/11262717/25965650/dfcc840e-3688-11e7-8761-b7dd1dc5e364.png)

**Comment by wiiaboo** [comment]
Create [`lua-settings\osc.conf`](https://mpv.io/manual/master/#configuration) inside your mpv's configuration directory and add [`vidscale=no`](https://mpv.io/manual/master/#on-screen-controller-vidscale) to it.

**Comment by hhiru** [comment]
So I added that string to this file `C:\Users\hiru\AppData\Roaming\mpv\lua-settings\osc.conf` but nothing happens.

**Comment by wiiaboo** [comment]
> It'll probably still look small because all layouts have a minimum size in order to work properly.

Try with layout=slimbox or just use a proper GUI.

**Comment by hhiru** [comment]
I'll use the slimbox config since I use the keyboard instead of the visual gui most of the time. thanks for the help :)
