### ISSUE TITLE
record-file broken with some hls streams

### ISSUE THREAD

**Issue by eked** [mpv-player/mpv#4419]
### mpv version and platform
mpv 0.25.0 on Linux
### Reproduction steps
`mpv --record-file=test.ts -- https://twitch.tv/monstercat`
(or any other twitch.tv stream if this one goes down)
### Expected behavior
Stream gets recorded to `test.ts`.
### Actual behavior
No recording and an empty file is created.
Release 0.24 worked.
I tracked it down to 6f8c953 and setting `--demuxer-lavf-probe-info=yes` is a workaround.
### Log file
[link](https://clitxt.com/t/5a3-1494580059.txt)
pertinent parts:

    [ffmpeg] mpegts: dimensions not set
    [recorder] Write header failed.
    Disabling stream recording.
### Sample files
n/a

**Comment by wm4** [comment]
Why was this closed? It's probably still a valid bug.

**Comment by eked** [comment]
I thought 4e663566dda9fea8cbff8e58f65e91863cbf42a4 fixed this.
