### ISSUE TITLE
Option to prevent window opening for audio tracks

### ISSUE THREAD

**Issue by olivergondza** [mpv-player/mpv#4426]
### mpv version and platform

`Linux arch 4.4.31-1-lts #1 SMP Thu Nov 10 18:01:16 CET 2016 x86_64 GNU/Linux`
```
mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon May  8 20:03:32 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3
```

### Reproduction steps

Play a directory of audio files where some of them have a cover-art embedded in the file (ID3 tags in mp3 IIUC).

### Actual behavior

mpv keeps popping windows up as soon as it hit a track with an image to show and hide it again once the track ends. Closing the window would stop the playback so it needs to be dismissed carefully ...

### Expected behavior

Since I have not required window to be created, I expect the mpv to keep playing in the terminal. I tried `--force-window=no` but to no avail as it does exactly what the name imply - does not force it. I browsed the man page and have not found a switch that would prevent any window to be created while plying audio tracks.

mpv is a huge improvement over mplayer but this is one of the reasons I still use it on occasion.

**Comment by wm4** [comment]
`--no-audio-display` (it literally says that on the terminal), or `--no-video`.

`--force-window` only matters in cases where absolutely nothing (i.e. not even coverart) is available for video.

**Comment by olivergondza** [comment]
Thanks, both `--no-audio-display` or `--audio-display=no` does what I am looking for! The former does not seem to be on the man page (deprecated?) so I stick with the latter.

**Comment by wm4** [comment]
The ``--no-` is another way to with the other option. It works in general with options that accept choices and include a "no" choice.

**Comment by Tucanix** [comment]
For others who happen to have the same issue as me:

I had issues trying to disable the window on audio playback. It works on one machine but not the other. The machine it doesn't work on has a few scripts and `visualizer.lua` forced the window to stay open. I would suggest that scripts would not be able to overwrite terminal flags like --no-video.

`--no-config` Worked to solve this issue for me.

**Comment by guttermonk** [comment]
When I set `audio-display=no`, the player still opens up. I tried setting `speed=1.5` just to make sure mpv is finding my config, and can confirm playback speed does change. So `audio-display` should be working.

According to the man page, setting `audio-display=no` should "Disable display of video entirely when playing audio files." It doesn't mention anything about keeping the "window" from opening up. Just to be painfully thorough, can anyone confirm that `audio-display=no` should keep the window from opening?

Running nixos 24.11 at the moment, btw.

**Comment by guidocella** [comment]
`--force-window` determines whether a window is spawned. It is `no` by default.

**Comment by guttermonk** [comment]
I have `force-window=no` in my config. Is that correct for what I'm trying to achieve?

**Comment by guidocella** [comment]
It's not needed since it's the default. Are you starting mpv from the terminal?

**Comment by guttermonk** [comment]
No, I'd like to be able to open audio files from my file manager, yazi, without it opening a player window.

I am able to play audio files from terminal without it opening a player window though. It would be nice if the `force-window=no` flag also applied to the file manager.

**Comment by eclairevoyant** [comment]
That sounds like your file manager is calling mpv in such a way that it doesn't read the config; that doesn't seem like an mpv issue.

**Comment by guttermonk** [comment]
@eclairevoyant you were right. Thank you for the suggestion.

For some reason yazi was defaulting to using the `--force-window` flag. The solution was to create this custom config ~/.config/yazi/yazi.toml
```
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
linemode    = "size"
show_hidden = false
sort_by     = "natural"

[preview]
tab_size   = 2
max_width  = 1000
max_height = 1000

[opener]
play = [
	{ run = 'mpv "$@"' },
]

[open]
rules = [
	{ name = "*/", use = [ "open", "edit", "reveal" ] },

	{ mime = "text/*",  use = [ "edit", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "video/*", use = [ "play", "reveal" ] },
	{ mime = "audio/*", use = [ "play", "reveal" ] },
	{ mime = "inode/x-empty", use = [ "edit", "reveal" ] },

	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },

	{ mime = "application/zip",             use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/gzip",            use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-tar",           use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-bzip",          use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-bzip2",         use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal", "archive" ] },
	{ mime = "application/x-rar",           use = [ "extract", "reveal", "archive" ] },

	{ name = "*", use = [ "open", "reveal" ] },
]

[plugin]
prepend_previewers = [
	{ mime = "audio/*", run = "exifaudio" },
]
```

**Comment by CarterSnich** [comment]
Debian 12, mpv 0.35.1. `--no-audio-display` didn't work when playing a YTM playlist. Had to use `--force-window=no`
