### ISSUE TITLE
Play two audio streams simultaniously?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4428]
Hi,

Is it possible to play two (or more) audio streams from a video file simultaneously (provided that alsa have different outputs for it). E.g. what if I want to play a movie audio in some language to speakers, and in another language -- to headphones.

**Comment by lachs0r** [comment]
No.

**Comment by azzamsa** [comment]
@kkkrackpot I play multiple audio files this way. I don't know if this suit with your purpose. (for different output; speaker & headpone. I don't know about that)

``` bash
(mpv beach.mp3 --loop-file &);mpv birds.mp3 --loop-file
```

This way you can play multiple song at once. with volume control missing (you have to adjust the volume manually from your sound mixer)

**Comment by wm4** [comment]
Can be done with --lavfi-complex.

**Comment by richardpl** [comment]
And with amix filter...
