### ISSUE TITLE
Another problem with vdpau after Mesa update...

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [mpv-player/mpv#4433]
### mpv version and platform

Xubuntu 16.04.2 LTS
r600g:
```
  GL_VERSION:  3.0 Mesa 17.2.0-devel - padoka PPA
  GL_VENDOR:   X.Org
  GL_RENDERER: Gallium 0.4 on AMD JUNIPER (DRM 2.43.0 / 4.4.0-78-generic, LLVM 5.0.0)
```

```
mpv 0.25.0-9-g18703b55d (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Tue Apr 25 11:25:52 MDT 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3
```

```
mpv 0.25.0-78-g3a7b4df4b (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed May 17 08:58:06 MDT 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.1
```

### Reproduction steps

Play a video using "the magic combination": `--vo=opengl --hwdec=vdpau`

### Expected behavior

Play the video and watch its content, music, etc.

### Actual behavior

mpv takes the last thing that was in the background and does not show or do anything else (not even CPU activity).
I have to close Terminal to close mpv...

### Log file

http://sprunge.us/MgKH
http://sprunge.us/WUJP

### Sample files

`--ytdl-format=137+171 https://www.youtube.com/watch?v=-NHG1-wlUh4`

### Notes

mpv works fine with:
```
--vo=opengl --hwdec=no
--vo=opengl --hwdec=vdpau-copy
--vo=vdpau --hwdec=no
--vo=vdpau --hwdec=vdpau
--vo=vdpau --hwdec=vdpau-copy
```

Example:
http://sprunge.us/jBUW

**Comment by wm4** [comment]
You might need to report this to Mesa instead. But I'm not sure what is actually going on.

**Comment by Jj0YzL5nvJ** [comment]
This bug was fixed here: https://bugs.freedesktop.org/show_bug.cgi?id=101254
But after, two other bugs not related to VDPAU appear. After a new Mesa update this day, everything is working properly again, at least for me.
