### ISSUE TITLE
Reload the video at the same time it's currently on

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#4435]
The situation is that my external drive occasionally disconnects, stopping the video, and making me have to manually close it, go to the folder, open it again, change audio streams, etc. I'm looking for a line to add to input.conf that will reload the video and keep it were it currently is.

I know it's possible because I asked this a long time ago and someone offered a solution, but I just can't find the post were I did it.

**Comment by CounterPillow** [comment]
personally I use

```
yourkeyhere write-watch-later-config; loadfile "${path}"
```

**Comment by firewater2** [comment]
Yes, this! Thanks much.
