### ISSUE TITLE
Cache always showing under seekbar 

### ISSUE THREAD

**Issue by hhiru** [mpv-player/mpv#4436]
### mpv version and platform
mpv 0.25.0

### Reproduction steps
Play a video

### Expected behavior
It should not show cache usage by default

### Actual behavior
It shows cache usage under the seekbar without a config enabled

### Log file

https://pastebin.com/yJGQd3Df

![image](https://cloud.githubusercontent.com/assets/11262717/26217520/fe3a7ef8-3c07-11e7-9c9a-5f195f218ddc.png)

**Comment by wiiaboo** [comment]
That's a feature request, not a bug.

What config do you mean? There's always cache enabled for non-local files, unless you turned it off.

**Comment by hhiru** [comment]
Files are saved on my drive, how's that non-local? Also this happens with no config files too

**Comment by wiiaboo** [comment]
You didn't specify the files path in the log files, so I can't know for sure why it's still using cache.

**Comment by hhiru** [comment]
Files are stored on a mounted drive in /mnt/ Does this matter?

**Comment by AirPort** [comment]
Is the drive formatted in NTFS or in any other filesystem mounted via FUSE by any chance?

**Comment by hhiru** [comment]
It is indeed a NTFS drive (shared with a Windows partition)

**Comment by AirPort** [comment]
Then AFAIK the cache behaviour is correct: https://github.com/mpv-player/mpv/issues/2367#issuecomment-144987171

**Comment by hhiru** [comment]
So in order to prevent mpv from interpret my files as network files I should make a partition ext4 linux-friendly so that files are actually considered local files?

**Comment by AirPort** [comment]
You can just put a `mpv.conf` file with `no-cache` in the video directory on that drive.

**Comment by hhiru** [comment]
Can't I just use the no-cache in the main mpv folder since I do not stream files?

**Comment by wiiaboo** [comment]
Sure.
