### ISSUE TITLE
[feature request] Time interval of seeking via mouse-wheel scrolling should vary depending on cursor position.

### ISSUE THREAD

**Issue by rieje** [mpv-player/mpv#4437]
Currently, you can set a single time interval (for example 5 seconds) that a single notch of mouse-scrolling up/down will skip ahead/behind. When you seek a video, you usually want to get an accurate context of the progression of the video, so seeking 5 seconds ahead/behind in a 15 second video is much different (in this case, not very useful--you likely want a lesser interval) than seeking 5 seconds ahead/behind in a 3 hour movie (also probably not useful--you probably want a greater interval). 

How about having two or more time intervals, each triggered depending on your mouse cursor's vertical position on the screen? For example, mouse-scrolling at the bottom portion of the video seeks the video with an interval of 3 seconds, mouse-scrolling at the middle portion with an interval of 10 seconds, and mouse-scrolling at the top portion of the video with an interval of 1 minute. Then, mouse-wheel scrolling is useful regardless of the length of the video. 

I don't think feature is niche at all and the implementation I've described came from the idea that there are already some input settings whose behavior depends on the actions done at different areas of window of the video. I see no downsides and I believe VLC has a similar feature where the seek interval changes depending on whether you mouse-scroll at the screen (slower) or at the seek bar area (faster, depending on how close you are to the seek bar).

**Comment by lachs0r** [comment]
You can also seek to a relative percentage of the file/stream (`seek relative-percent`).

**Comment by avih** [comment]
> How about having two or more time intervals ...

You can have up to 9 with the zones script: https://github.com/wiiaboo/mpv-scripts/blob/master/zones.lua
