### ISSUE TITLE
gapless disabled with -af

### ISSUE THREAD

**Issue by richardpl** [mpv-player/mpv#4438]
MPV doesn't handle gapless playback with -af filters.

**Comment by wm4** [comment]
Needs some proof? Most likely a problem with draining or so, but I won't go all the way trying to reproduce it myself somehow.

**Comment by richardpl** [comment]
I hear click at transition, without -af it works fine.
By proof you mean short encoded sample?

**Comment by wm4** [comment]
Command line, source sample, and output sample of what you get would be ideal.
