### ISSUE TITLE
Random play of tracks

### ISSUE THREAD

**Issue by mrkaban** [mpv-player/mpv#4440]
Hello, I liked the player, and especially the list of supported formats. Is it planned to create a window with a list of tracks? As well as random playback of tracks from the list? A similar function is in Windows Media Player.

**Comment by CounterPillow** [comment]
mpv's OSC is minimalistic on purpose, if you want a fully-feature GUI player you might want to look into [GUI frontends using libmpv](https://github.com/mpv-player/mpv/wiki/Applications-using-mpv#gui-frontends).

**Comment by Argon-** [comment]
mpv can display tracks and https://mpv.io/manual/master/#options-shuffle them as well.

**Comment by mrkaban** [comment]
Thank you! I later read about it.
