### ISSUE TITLE
"--fs-screen=1" spawns mpv on primary monitor in windowed mode

### ISSUE THREAD

**Issue by guihkx** [mpv-player/mpv#4442]
### mpv version and platform

```
mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon May  8 20:03:32 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.1
```
```
Arch Linux 64-bit
Desktop Environment: XFCE 4.12
Window Manager: Xfwm4 4.12.4
Xorg: 1.19.3
NVIDIA 381.22 (proprietary drivers)
Primary monitor resolution: 1920x1080 (120Hz)
Secondary monitor resolution: 1360x768 (60Hz)
Linux version 4.9.28-1-lts (builduser@andyrtr) (gcc version 6.3.1 20170306 (GCC) ) #1 SMP Sun May 14 18:07:38 CEST 2017
```

### Reproduction steps

Try to launch mpv on secondary monitor by running: `mpv --player-operation-mode=pseudo-gui --fs-screen=1`

### Expected behavior

mpv spawns in full screen mode on secondary monitor.

### Actual behavior

mpv spawns in windowed mode on primary monitor. However, if you run: `mpv --player-operation-mode=pseudo-gui --screen=1`, then mpv will actually spawn on secondary monitor, but in windowed mode. I've tried adding `--fs` but that makes mpv spawn on primary monitor again. If it's not obvious enough, yes I did try that with an actual video... Oh, I've also tried `--fs-screen=2`, but nada.

### Log file

https://gist.githubusercontent.com/GUiHKX/b0e72186a260e0787e9f2d35f2d3faa3/raw/ded8291d340a9cfa4530b91db74dbfef7dc131f5/mpv.txt

**Comment by alfrix** [comment]
you are missing --fs in the command try:
`mpv --player-operation-mode=pseudo-gui --fs --fs-screen=1`

**Comment by GUiHKX** [comment]
It didn't work for me as well... mpv gets spawned in full screen mode on primary monitor.

**Comment by thebombzen** [comment]
Is this still a problem in mpv 0.28.0?

**Comment by GUiHKX** [comment]
Arch Linux is still on 0.27.0 so I haven't be able to test it yet, but as soon as they package version 0.28.0 I'l l let you know.

**Comment by thebombzen** [comment]
You can also try building mpv from git master if you'd like to test it sooner.

**Comment by GUiHKX** [comment]
Okay, so I just did that and mpv still spawns in full-screen on first monitor.

[LOG.TXT](https://gist.github.com/GUiHKX/845519b957e57c7bc91f3be73cb04a93/raw/2c263f330af932f89ad93246d1e3c21fbfd03526/LOG.TXT)

My monitor setup is still the same by the way:

![screenshot_2018-01-14_00-34-45](https://user-images.githubusercontent.com/626206/34912226-d953b7b2-f8c2-11e7-8079-834e78d47327.png)

The secondary screen is not 72" though, it's actually a 32" TV with a resolution of `1360x768`. I also have mpv installed on Windows and doing that works as expected.

**Comment by GUiHKX** [comment]
If I try to run in windowed mode, like this: `mpv --player-operation-mode=pseudo-gui --screen=2`

mpv successfully spawns on the secondary monitor.

**Comment by GUiHKX** [comment]
I've recently switched from XFCE to KDE Plasma, but unfortunately I'm still getting the same behavior in mpv v0.28.0.

Since I also use mpv on this Windows partition I have in dual boot with Arch, I thought it could be useful to compare the output of both environments. [The monitor setup is *exactly* the same](https://i.imgur.com/h5nNOIq.png), but **on Windows, spawning mpv on secondary monitor in full screen actually works**. On a side note, I find it odd that apparently I'm the only one experiencing this issue on Linux... (or am I?)

Here are the log files for `$ mpv --no-config --player-operation-mode=pseudo-gui --fs --fs-screen=1`:

* [Arch Linux](https://github.com/mpv-player/mpv/files/1643163/mpv-arch.txt)
* [Windows 10](https://github.com/mpv-player/mpv/files/1643164/mpv-windows10.txt)

**Comment by GUiHKX** [comment]
Oh my...

So I was trying different combinations of mpv switches on Linux, then I simply added `--screen=1` to previous commands and it worked (on both v0.27.0 and v0.28.0, btw):

`$ mpv --screen=1 --fs --fs-screen=1 video.mp4`

So, apparently, if I only use `--fs-screen=1` on Windows, it works since it automatically implies `--screen=1` as well. I'm not sure if this is a bug or if I'm just dumb, so I'll leave it up to you guys. :laughing: 

Feel free to close this since it's been solved now.

**Comment by Hrxn** [comment]
NB: The opener can close issues as well..

**Comment by GUiHKX** [comment]
I'm aware of that, I'm just not sure if this behavior should be fixed since the same command produces different results on both Windows and Linux.

**Comment by thebombzen** [comment]
So, in summary:
`mpv --fs --fs-screen=1` spawns mpv in fullscreen on monitor 0.
`mpv --screen=1 --fs --fs-screen=1` spawns mpv in fullscreen on monitor 1.
The above only occurs on your Arch Linux boot. On your Windows boot, `--fs-screen=1` seems to imply `--screen=1`.

If what you're reporting is true, this is a bug. I have a second monitor that I can unearth to do some testing, seeing as I also have a dual boot Arch Linux / Windows computer.

**Comment by wm4** [comment]
Does the WM support _NET_WM_FULLSCREEN_MONITORS? That's what mpv uses to set fs-screen. There are a ton of nasty details though. For example, mpv assumes the screen number goes by the Xinerama API, and nothing specifies what the _NET_WM hint uses. (At least from my hazy memory, didn't check again.)

**Comment by GUiHKX** [comment]
@thebombzen Yes, that's exactly it. I've just re-installed XFCE to try this again; and mpv behaves like it does on KDE, only spawning in full screen on monitor 1 when I use these three switches together: `--screen=1 --fs --fs-screen=1`.

@wm4 I just did a quick search on their code, so I'm pretty sure both [xfwm4 (XFCE's wm)](https://github.com/xfce-mirror/xfwm4/blob/ef33ff7b2666ffc320700592fc7d4a300d5a8163/src/display.c#L121) and [KWin (KDE's wm)](https://github.com/KDE/kwin/blob/ff3b741ad8f020c5031933ef0b0bb6f77c8d7248/COMPLIANCE#L151) do support `_NET_WM_FULLSCREEN_MONITORS`.

**Comment by kevmitch** [comment]
I can confirm direct to full screen on secondary display requires `--screen=1` in addition to `--fs-screen=1` on openbox.

**Comment by GUiHKX** [comment]
I'm not much of a C programmer myself but this fixed it for me:

```diff
diff --git a/video/out/x11_common.c b/video/out/x11_common.c
index 5f2c658a9c..498c2d95e8 100644
--- a/video/out/x11_common.c
+++ b/video/out/x11_common.c
@@ -1211,6 +1211,7 @@ static void vo_x11_sizehint(struct vo *vo, struct mp_rect rc, bool override_pos)
     bool force_pos = opts->geometry.xy_valid ||     // explicitly forced by user
                      opts->force_window_position || // resize -> reset position
                      opts->screen_id >= 0 ||        // force onto screen area
+                     opts->fsscreen_id >= 0 ||      // same as above 
                      x11->parent ||                 // force to fill parent
                      override_pos;                  // for fullscreen and such
```

**Comment by GUiHKX** [comment]
Care to give an example? Here are my tests:

* `$ mpv --player-operation-mode=pseudo-gui` (spawns in windowed mode on `screen 0`)
* `$ mpv --player-operation-mode=pseudo-gui --screen=0` (spawns in windowed mode on `screen 0`)
* `$ mpv --player-operation-mode=pseudo-gui --screen=1` (spawns in windowed mode on `screen 1`)
* `$ mpv --player-operation-mode=pseudo-gui --fs --fs-screen=0` (spawns in full screen mode on `screen 0`)
* `$ mpv --player-operation-mode=pseudo-gui --fs --fs-screen=1` (spawns in full screen mode on `screen 1`)

**Comment by guihkx** [comment]
I'm using GNOME 3.36.4 instead of XFCE now, and `mpv --player-operation-mode=pseudo-gui --fs --fs-screen=1` actually places the mpv window on my secondary screen, which is great!

However, doing the same on KDE Plasma 5.19.2 didn't work.

**Comment by Dudemanguy** [comment]
FYI, since you're using wayland using only `--screen` will not work because the protocol doesn't support clients picking an output (it does support `--fs-screen` though). I did ask a while ago to add this to `xdg-shell` but none of the core wayland devs were particularly receptive so probably just don't expect that to happen.

If it doesn't work in Plasma's wayland session, it would be a compositor limitation. I would expect it to work in Xorg of course, but I've never actually tested it.

**Comment by guihkx** [comment]
Oops, I should've mentioned that I'm on X11 in both GNOME and Plasma, since I'm using the NVIDIA's proprietary driver, which is pretty bad on Wayland at the moment.

**Comment by Dudemanguy** [comment]
Huh well I guess Plasma xorg is worse than I thought.

**Comment by benyaminl** [comment]
So this still a problem on windows then?

**Comment by sohanglal** [comment]
`mpv . --screen=0` works for me

**Comment by benyaminl** [comment]
> `mpv . --screen=0 --fs` works for me

Seems I get it now, so when you are using laptop, whether you change your primary window, the first screen still will be the laptop, and it will still shown on screen 0, as mpv start from zero. Hmm... sad. 
but thanks

**Comment by Dudemanguy** [comment]
`mpv --fs --fs-screen=1` should work on X11 as of f7151932df4b239a8ee724117103cc15635987c5.
