### ISSUE TITLE
Jack audio and rear/center mismapped channels

### ISSUE THREAD

**Issue by Tele42** [mpv-player/mpv#4444]
Good day,

I use Smplayer/mpv on Gentoo with JACK audio and have recently been saddened by finding the [removed --jack-std-channel-layout=alsa](https://github.com/mpv-player/mpv/commit/a7f51f8fd48df7f04f47b515180338f8b9b78fed) option as I can not find any other solution in order to get a sane layout by default (fl, fr, rl, rr, ctr, sub, sl, sr) so I have to remap the jack connections after I have started playback. Please re-add the alsa layout as a non-default or let me know if there is another method to setup the channel mapping without having to remove the option for stereo playback.

**Comment by wm4** [comment]
That change was implemented over a year ago...

Anyway, Jack has no concept of channel layouts, so it's up to you. If you really want to do it in mpv, you can probably do it with `--af=pan` or `--af=channels`. These filters are deprecated though. You could just use an audio API that has proper support for multichannel too, like pulse or alsa.

**Comment by Tele42** [comment]
I previously attempted to use`--af=channels=8:[0-0,1-1,2-4,3-5,4-2,5-3,6-6,7-7]` or `--af=channels=6:[0-0,1-1,2-4,3-5,4-2,5-3]` as a workaround for this issue, but is an unacceptable solution because the filter errors out with `[channels] Invalid routing in pair nr. 2.` when the media file is stereo. Due to this I am not able to set and forget the workaround in smplayer. If the filter picked up null inputs when it's fed less channels than mapped, then it would work for me.

If I were to use pulse or alsa at this time, it would be via an alsa loopback devices and a bridge or pulseaudio which feeds into JACK and does not have direct access to the sound card. Both are more mangled than than directly using JACK.

**Comment by wm4** [comment]
Surely you can do something within Jack to fix the order.

**Comment by Tele42** [comment]
The short version is no, if there is a solution for this in jack, I have not found it.

If I point jack to a channel remapping in alsa, then all existing surround sound applications become wrong. I could workaround some of them, but not all of them.

If qjackctl's patchbay allowed me to give a persistent channel mapping, that would also solve the problem, but it does not have that level of control.
