### ISSUE TITLE
I am using the mplayer version [1.3.0.0] on windows server 2013.I want to play the locally saved audio file using mplayer.In normal scenerios the time difference between commnad given and playing of audio is less then *1 sec* which is good . But the problem is when ever I restart my PC or start PC after shutting it down , the time taken by the mplayer to play the file is around *6 secs*. This also happens if we keep Computer on standby mode for around 5-6 Hrs.In brief "The mplayer takes more time to launch for the first time after reboot OR being on the standby mode for more then 5-6 Hrs.By adding the mplayer to automatically launch during startup will solve first issue but the problem for the Standby scenerio will still persist. So I was looking for any solution through configuration settings in Mplayer or any other settings options available in mplayer that can solve this issue to happen. Please share with me if there is any possible way through which this issue can be eliminated ..Thanks alott!

### ISSUE THREAD

**Issue by ravibhanushali** [mpv-player/mpv#4448]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Step 1 : Reboot the Windows PC. Open poweshell and type following command "Measure-Command {start "Mplayer.exePath"}...........This command returns the time taken for the Mplayer.exe to launch...Note the time in secs.
Step 2 : Now without restarting , again go to Powershell and type the command given above ... Note the execution time... I would less then a sec...
Step 3 : let the PC be on Standby mode  (i.e Dont use mplayer for that time)for 6 Hrs and again follow the procedure in step2.. Note down the execution time ...The time will be same as the execution time in 1st step...
Step 4 : Again follow procedure in STEP2 and note down the execution time...
### Expected behavior
The execution time of the mplayer should be around 1 sec, even after rebooting PC or keeping the PC in standby mode(i.e Dont use mplayer for that time)for 5-6 hrs .
### Actual behavior
The launch time of the mplayer after PC reboot or keeping the PC in standby mode(i.e Dont use mplayer for that time)........ is around 5-6 secs.
### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by rossy** [comment]
This issue tracker is for mpv, not MPlayer. If you think this is an MPlayer issue, please report it to them:
https://mplayerhq.hu/DOCS/HTML/en/bugreports.html

I'm not totally sure it's an issue though. Generally, I'd expect a program to take longer to start after the system is rebooted or spends a long time idle, since the libraries it requires might not be resident in RAM and must be loaded off disk. There might also be a few startup tasks running in the background.

Also, please keep issue titles short! I think you might have written text in the title that you intended to put in the message body.
