### ISSUE TITLE
Artifacts with CUDA HW decoding

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4454]
Hi,

When using `hwdec=cuda` I see strange artefacts: bluish silhouettes/outlines/shades around moving objects. It resembles "motion blur", but I doubt it is in the case. I can hardly describe it, so I filmed it from TV screen (clip below).
These things are not seen on still objects, as well as they can't be caught with an ordinary screenshot (i.e. with `s`)
There's no (or much less, at least) such problem with `hwdec=vdpau-copy`.
I believe it all started with new Nvidia's SDK 8,  and related commints to ffmpeg's git (but I'm not sure).
Probably I should ask @philipl to have a look too.

### mpv version and platform
```
64-bit Gentoo with 4.9.16 kernel
Nvidia's proprietary driver 381.22
mpv 0.25.0-80-g37f057197 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri May 19 20:46:55 MSK 2017
ffmpeg library versions:
   libavutil       55.63.100
   libavcodec      57.96.101
   libavformat     57.72.101
   libswscale      4.7.101
   libavfilter     6.90.100
   libswresample   2.8.100
ffmpeg version: N-86172-g162414cefe
```
### Reproduction steps
Play any(?) video with `hwdec=cuda` 

### Expected behavior
No strange artefacts.

### Actual behavior
Strange artefacts.

### Log file
Logs don't show any problem.

### Sample files
Original video https://0x0.st/E9J.mkv
Video clip showing artifacts https://0x0.st/E9e.MOV -- I made it with a camera from TV screen
Screenshot showing artifacts https://0x0.st/E9j.png -- the indicated things are clearly seen on screen, it's not a camera bug or something.

**Comment by CounterPillow** [comment]
It kind of looks like one of the chroma planes is one or more frames behind for some reason.

**Comment by aufkrawall** [comment]
Can't confirm this with 0.25 or latest git on either Windows nor Linux.
GPU, settings?

**Comment by fhlfibh** [comment]
Settings http://sprunge.us/ODjS
Log of the original video from above http://sprunge.us/ZOQU

**Comment by aufkrawall** [comment]
Well, I'd try to find out if there is a faulty specific setting.
I don't see why opengl-pbo should be used, performance should be optimal with cuda anyway.
Dunno about opengl-fbo-format=rgba32f, image quality voodoo?

**Comment by philipl** [comment]
Yeah. Works fine here. I'd start with a stripped down settings file and then build it back up.

**Comment by fhlfibh** [comment]
The issue was because of `cscale` option.
In the above config http://sprunge.us/ODjS I disabled all processing settings below `vo=opengl`
Then I started enabling them one by one.
The artifacts appeared when I enabled `cscale=ewa_lanczossharp`
Then I enabled all options back except `cscale=ewa_lanczossharp` -- no issues.
Then I enabled `cscale=ewa_lanczos` -- the problem appeared again.
Then I enabled `cscale=spline36` -- again no issues.
So as far as I can understand, CUDA doesn't like Ewa-Lanczos chroma upscaling (or vice-versa)...

**Comment by wm4** [comment]
Maybe it's an issue with trying to access a previous' frame's mapped texture or so. If so, it could happen with vdpau or d3d11va too...

**Comment by aufkrawall** [comment]
I'm using cscale=ewa_lanczossharp with cuda myself without issues.
My config: http://sprunge.us/UhBC

**Comment by fhlfibh** [comment]
@aufkrawall 
I tried your config (modified it a little to suit my system) -- no problem.
However, if I comment out everything except `cscale=ewa_lanczossharp` http://sprunge.us/KXUU -- the problem is still here...

**Comment by aufkrawall** [comment]
I tried git ffmpeg + git mpv with deband off and cuda decoding enabled and still couldn't encounter the artifacts.

**Comment by fhlfibh** [comment]
@aufkrawall what driver's version you have?

**Comment by aufkrawall** [comment]
381.22 on 4.11.

**Comment by fhlfibh** [comment]
@aufkrawall and what monitor/TV model you use?

**Comment by aufkrawall** [comment]
I'm using a PC monitor with 2560x1440 75Hz via DL-DVI.

Can you capture the artifacts with a screen video recording (e.g. with OBS)?

**Comment by fhlfibh** [comment]
@aufkrawall It was somehow tricky, but I managed to make a screencast with `recordmydesktop --full-shots --fps 50 --display :0 --no-sound --overwrite --no-frame` -- https://0x0.st/IOt.ogv

To sum it all up somehow:
I have two PCs, their software and hardware are fairly the same. Particularly, they have identical OS, Nvidia drivers, X-server, ffmpeg and mpv.
I don't see artifacts on GTX660 connected via DVI to FHD Benq GW2250HM.
I do see artifacts on GTX1080 connected via HDMI (or DP-HDMI) to FHD Panasonic VT60.
But both are Ok with `vdpau-copy`.

**Comment by aufkrawall** [comment]
I unfortunately can't test with different displays. I'm on a Pascal GPU too (1070).

**Comment by haasn** [comment]
My best guess is that it's a problem with `texture_size/pixel_size`.

If my theory is correct, then adding this an `--opengl-shader` should fix the problem:

```glsl
//!HOOK CHROMA
//!BIND HOOKED
//!DESC fix chroma size

vec4 hook()
{
    return HOOKED_tex(HOOKED_pos);
}
```

**Comment by fhlfibh** [comment]
@haasn I will sure test it, but only tomorrow evening.

**Comment by fhlfibh** [comment]
The issue seems gone now.
I "blame" https://github.com/mpv-player/mpv/commit/b2fb3f1340ed7ceb9b3fc8ba4ddec107e3a41a13 for it.
Closing the issue, because it seems hardly debuggable, anyway.

**Comment by wm4** [comment]
Seems unlikely. Should have affected dumb mode only.

**Comment by haasn** [comment]
Extremely unlikely b2fb3f1 has anything to do with it.

**Comment by fhlfibh** [comment]
Yes, quite may be. But I have no other alternatives. Maybe rebuilding mpv down the commits tree could locate the exact reason -- but I don't know if there's now any sense doing it? In any case, at the moment the issue seems gone, I checked it with the same sample video from above.

**Comment by wm4** [comment]
Most likely it was a driver thing.

**Comment by aufkrawall** [comment]
Corruption with rec2020 hdr hevc 10 bit video is still there.

**Comment by haasn** [comment]
@aufkrawall Open a new issue with screenshots/log/etc

**Comment by aufkrawall** [comment]
LAV Filters shows the same problem, so it must be a driver bug.

**Comment by haasn** [comment]
Then don't, I guess

**Comment by aufkrawall** [comment]
Good news: The artifacts with cuda + HEVC 10 bit HDR are gone with 387 driver.

**Comment by fhlfibh** [comment]
Contrariwise, for me 387 they are back again with 387...
