### ISSUE TITLE
[equalizer] This filter is deprecated. Use 'anequalizer' or 'firequalizer' instead.

### ISSUE THREAD

**Issue by slashbeast** [mpv-player/mpv#4455]
Hello.

I started seeing that equalizer is deprecated, and that I should use either anequalizer or firequalizer, but man still have information about equalizer and nothing about how to use 'anequalizer' or 'firequalizer'. Perhaps the man page could use update.

**Comment by wiiaboo** [comment]
They're FFmpeg filters, so you go to the FFmpeg documentation: [anequalizer](https://ffmpeg.org/ffmpeg-filters.html#anequalizer) and [firequalizer](https://ffmpeg.org/ffmpeg-filters.html#firequalizer).
