### ISSUE TITLE
[Feature request] Time for on-screen display (OCD)

### ISSUE THREAD

**Issue by rieje** [mpv-player/mpv#4456]
I looked at the options and it seems the on-screen display can either have:

* just the seek bar (with no other information), visible when seeking (default)
* persistent time elapsed shown, along with the seek bar
* persistent time elapsed and the total length of the video, along with a % completed and along with the seek bar

I want the information of the third option but not be persistent--only when I seek. I don't think this is currently possible after taking a look at the docs. So, nothing should shown on the video, but when I seek, I want to see more than just a seek bar (the default)--I want to see the third option provides. I just don't want this to be persistent.

Such a configuration is not currently possible on mpv, is it?

**Comment by Cpuroast** [comment]
Use the "input.conf" config file.

Example: 

RIGHT osd-msg-bar seek  5
DOWN  osd-msg-bar seek  30
LEFT  osd-msg-bar seek -5
UP    osd-msg-bar seek -30

AXIS_LEFT  osd-msg-bar seek  5
AXIS_DOWN  osd-msg-bar seek  30
AXIS_RIGHT osd-msg-bar seek -5
AXIS_UP    osd-msg-bar seek -30

**Comment by rieje** [comment]
This works nicely, thank you.

**Comment by rieje** [comment]
@Cpuroast Thanks, that works nicely. I don't suppose I can move the position of the time text information on the top somewhere else (like bottom or next to the osd bar), right? I know I can move the osd bar's position, but I would like to move the time text on the bottom or center because I want all information displayed by mpv to be in one area (bottom or close to it).

**Comment by Cpuroast** [comment]
Look at the OSD options:

https://mpv.io/manual/stable/#osd

It's all there :)
