### ISSUE TITLE
no OSC in non-x env (tty) using --vo=drm

### ISSUE THREAD

**Issue by nycko123** [mpv-player/mpv#4459]
### mpv version and platform
Mpv 1:0.25.0-3
Arch Linux 4.11.2-1-ARCH
### Reproduction steps
I've noticed an issue, which might be specifically connected to mpv and drm.
So the issue is as it's stated in the topic. Video files (local or streams) are played ok with proper OSC (o-key, 9- 0-keys), unless they're piped to other programs. This is only noticable using drm in tty's, no issue exists in xserver.

### xserver
1. `mpv --hwdec=auto testfile.mp4` gives
`Playing: Wideo/testfile.mp4
 (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
Using hardware decoding (vaapi).
VO: [vaapi] 1280x720 vaapi[nv12]
AO: [pulse] 44100Hz stereo 2ch float
AV: 00:00:05 / 00:03:09 (3%) A-V:  0.000`
OSC pops up
2. with piping
`cat testfile.mp4 | mpv --hwdec=auto -` gives
`Playing: - [file] Reading from stdin... (+) Video --vid=1 (*) (h264 1280x720 23.976fps) (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz) Using hardware decoding (vaapi). VO: [vaapi] 1280x720 vaapi[nv12] AO: [pulse] 44100Hz stereo 2ch float AV: 00:00:06 / 00:03:09 (3%) A-V: 0.000 Cache: 9s+37MB`
OSC pops up
### tty (non-x env)
1. `mpv --vo=drm --hwdec=auto testfile.mp4` 
gives the same output as in xserver, OSC works
2. with piping
`cat testfile.mp4 | mpv --vo=drm --hwdec=auto -` 
gives the same output as in xserver, except **there is no OSC**
I've tried to pass couple of arguments to the player, with no luck:
`cat testfile.mp4 | mpv --vo=drm --hwdec=auto --player-operation-mode=cplayer -` 
`cat testfile.mp4 | mpv --vo=drm --hwdec=auto --force-window -`
`cat testfile.mp4 | mpv --vo=drm --hwdec=auto --force-window --player-operation-mode=cplayer -`

**Comment by thebombzen** [comment]
I can get the OSC show just fine with `--vo=drm` on my Arch Linux laptop. 

It's worth mentioning that Getty doesn't respond to mouse input so the OSC will not show if you move the mouse. If you set a keybind to show the OSC then it should render properly. Can you try this and report back?

**Comment by Akemi** [comment]
if this issue still persist please open a new issue.
