### ISSUE TITLE
Exiting mpv during Full Screen Mode leaves OS on a new or empty Workspace/Desktop

### ISSUE THREAD

**Issue by adityaravishankar** [mpv-player/mpv#4461]
Basically, quitting while in Full Screen leaves elementary OS on a different empty workspace from the one where mpv was started.

This seems like it might be similar to #4400 (except that this one is for Linux) .. I believe mpv might be quitting before the full screen sliding animation has time to end, so the player remains in the empty workspace that it created for full screen mode.

### mpv version and platform
mpv 0.25.0-b7d0dfa (C) 2000-2017 mpv/MPlayer/mplayer2 projects
OS: elementary OS 0.4.1 Loki

### Reproduction steps
1. Open any video, and switch to full screen mode (using the F key)
2. While video is playing, quit mpv (Using the Q key)

### Expected behavior
OS returns to the original desktop/workspace that mpv was opened from

### Actual behavior
MPV stays behind on a fresh/empty workspace (that was used for fullscreen), instead of returning to the original work space.

### Log file

Skipping log file for now. Will upload if necessary. This bug seems pretty easy to reproduce.

**Comment by pink-mist** [comment]
This doesn't happen for me. Sounds more like an issue with whatever windowmanager or desktop environment you're using.

**Comment by adityaravishankar** [comment]
Definitely could be the desktop environment... elementary OS is still a little rough around the edges... 

I think I should move this bug to eOS instead, since I was able to recreate the problem with VLC as well.
