### ISSUE TITLE
hwdec fails on all interlaced and / or MPEG-2 content

### ISSUE THREAD

**Issue by csdesigns** [mpv-player/mpv#4462]
I am unable to get mpv to successfully use hardware decoding on Mac OS X 10.11.6 for anything but H.264 progressive content. MPEG-2 interlaced, MPEG-2 progressive, and H.264 interlaced content attempts to use the videotoolbox hwdec option, however they all fall back to sw decoding. 

This is an issue on my Early 2009 Mac mini and Late 2008 MacBook Pro, both of which I would like to use with Plex's DVR feature (as a good bit of the content I record via Plex is ATSC MPEG-2 interlaced). I can edit the mpv.conf file to play back H.264 progressive content with videotoolbox as the hwdec (mpv by default, on these systems at least, will use sw decoding for all content otherwise):
```
vo=opengl
hwdec=videotoolbox
```

For interlaced content, I need to have the decoder perform a deinterlace to avoid the ugly combing of 1080i on playback. In order to best do so, I also need to add a line in mpv.conf to use frame-based yadif deinterlace mode rather than the default field-based:
```
vf=yadif=frame:yes
``` 
While I know that field-based deinterlacing is preferable to frame-based, there are two key issues here precluding me from using this:

1. These systems apparently aren't powerful enough to do a proper field-based deinterlace in real-time, as I am seeing many dropped frames; switching to frame-based yadif resolves this and playback is 100% smooth
2. The vast majority of the content I am recording was originally film-based anyway, so a frame-based deinterlacer is going to be more than sufficient for playing back this type of content without introducing any undo additional judder

If I edit the mpv.conf file to support frame-based deinterlacing, this provides smooth and clean playback of interlaced content using the sw decoder. However, in doing so, it also breaks hw decode of H.264 progressive content (complains of not being able to configure the **libavfilter** graph). {It does seem that if I use 'hwdec=videotoolbox-copy' that hw decoding is still functional, but I guess the attempt to apply yadif on top of this is way too much as the playback is by far the worst in terms of frames played per second.} 

I have found most MPEG-2 content to be ok with sw decode only. However, I do have H.264 content that certainly performs much better using videotoolbox, so finding a singular solution that works well decoding sourced MPEG-2 progressive, MPEG-2 interlaced, and H.264 progressive content would be ideal.
 
Therefore, guess I have a number of questions:
1. Is mpv / videotoolbox supposed to support MPEG-2 hw decode?
2. Is mpv / videotoolbox supposed to support interlaced decode and deinterlacing of content?
3. Is it possible to create a single edited mpv.conf file such that certain parameters only apply to certain input formats within the same file? i.e., interlaced (and / or MPEG-2) input content has certain filters specified, and progressive (and / or H.264)  input content has a different set of filters specified, all within a single mpv.conf file? This way I could specify how I want MPEG-2 video to be treated, and what to do with H.264 from one conf file. I know there is the 'hwdec-codecs=' option, but as far as I can tell, this is an all-or-nothing sort of thing _<= meaning I can't specify this multiple times within a single conf file._

Oddly enough, I never used to have these issues with the older Plex Home Theater app. I think that player by default would do a frame-based deinterlace, and use videotoolbox for H.264, so performance was always quite good on these systems. But the interface and UI is so much improved with Plex Media Player that the older app is a pain to even look at and use these days.

The current version of mpv installed is: 0.25.0-92-gbc3365b

Sample source files and logs can be found [here](https://www.dropbox.com/sh/wqinwcotblu9g2m/AACurZycDaDijfUyTsz9R8Kda?dl=0).

Thanks for any assistance anyone can provide.

**Comment by wm4** [comment]
As far as I know, Apple doesn't support MPEG-2 at all, and H264 interlaced is also not really supported.

The filter error is because yadif does not support hardware decoding. On platforms other than OSX, mpv can insert the correct deinterlacing filter (depending on the hwdec mode) with `deinterlace=yes`. But on OSX, Apple does not provide any working hardware deinterlacing API, so you can only use `hwdec=videotoolbox-copy` and use yadif (that might be too slow, especially on such old hardware).

With newer hardware you could probably get good support by running Linux or Windows 10, but I'm not going to make promises for such old hardware.

**Comment by csdesigns** [comment]
Thanks for the information. Understood on the limitations of OS X. And as you and I both previously alluded to, hwdec=videotoolbox-copy does indeed maintain the hw decode for H.264 interlaced, but these systems are not able to keep up for R/T playback.
