### ISSUE TITLE
[feature request] open multiple files as separate instances

### ISSUE THREAD

**Issue by rieje** [mpv-player/mpv#4463]
Often I would like  to open multiple videos side-by-side to compare their quality. If I open these files via the command like `mpv file1 file2`, file1 gets opened by file2 gets queued to a playlist. Is there a way to open the videos separately and at the same time via the command line? I can run the command to open each file separately, but that's not ideal (and for scripting purposes).

I checked the documentation using the terms "playlist" and "queue" to see if there's an option to disable queuing the videos or adding it to a playlist but there doesn't seem to be any.

**Comment by wiiaboo** [comment]
`mpv file1 & mpv file2`?
