### ISSUE TITLE
[Feature request] Support multiple conf files, add codec specific params within conf, or edit default decode behavior

### ISSUE THREAD

**Issue by csdesigns** [mpv-player/mpv#4464]
Inline with an issue I have run into and described in detail in post #4462 , since there is a limitation in that OS X doesn't support hw deinterlacing, a convenient solution would be to have the ability to set specific parameters within the mpv.conf file explicitly per codec. The primary formats I am dealing with are MPEG-2 progressive, MPEG-2 interlaced, and H.264 progressive. For MPEG-2, sw decoding is generally ok on my systems. But H.264 does benefit from having the ability to use hw decode in most instances. So rather than the mpv.conf only being capable of general parameters, if I could write a specific set of lines for MPEG-2 and a specific set for H.264, that would be ideal.

Something akin to the following I think would be beneficial:
```
codec=h264
hwdec=videotoolbox
deinterlace=no

codec=mpeg2video
hwdec=no
vf=yadif=frame:yes
```
Alternative option would be to add a parameter to mpv.conf that can set the fallback behavior. Right now, if hw decode is enabled initially, but a filter is called further down that conflicts, this will immediately force mpv to default to sw decode. Being to control mpv's behavior regarding this would also be convenient. In the example I refer to above, if I could tell mpv to always fallback to hw decode whenever hw decode is compatible with the raw source, it would therefore ignore the yadif commands whenever H.264 video is sourced and hw decode would remain.

**Comment by garoto** [comment]
Give this auto-profiles Lua script a try: https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua

**Comment by csdesigns** [comment]
> Give this auto-profiles Lua script a try: https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua

Thanks! That should do it!! 😃

**Comment by csdesigns** [comment]
Would you have a tip on how to get mpv to react based off of **codec** input in the profile? I've been able to make this mostly work based off of format (container/muxer) type and frame rate, but can't find documentation or examples on how to specify based on codec type (ie h264 or mpeg2video). Thanks!

**Comment by garoto** [comment]
[${video-format}](https://mpv.io/manual/master/#command-interface-video-format) property expansion.

Like these two examples:

```
[mpeg2video]
	profile-desc=cond:p.video_format=="mpeg2video"
	term-playing-msg="profile mpeg2video loaded (${video-format})"
	hwdec=no
	hr-seek=yes

[h264]
	profile-desc=cond:p.video_format=="h264"
	term-playing-msg="profile h264 loaded (${video-format})"
	hwdec=auto-copy
	hr-seek=no
```
