### ISSUE TITLE
Many "[ffmpeg] tls: IO Error: -9806" warnings

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#4468]
### mpv version and platform
```
$ mpv --version
mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Apr 23 01:38:53 BST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3
$  sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195
```

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
`$ mpv --log-file=output.txt https://www.youtube.com/watch?v=mdErJp_R1_g`
### Expected behavior
No "[ffmpeg] tls: IO Error: -9806" warnings and therefore a quicker start of the video
### Actual behavior
Many "[ffmpeg] tls: IO Error: -9806" warnings : 
`$ grep ffmpeg.*tls:.IO.Error:.-9806 output.txt`
### Log file

[output.txt](http://sprunge.us/RdFN)

**Comment by sebma** [comment]
This issue seems to be fixed on mpv v0.26+ffmpeg v7:3.3.3.

**Comment by evolutionxbox** [comment]
This issue is still present on mpv v0.27.1+ffmpeg v3.4.2

**Comment by jsit** [comment]
I also have this issue. This is when trying to stream a live YouTube video. Example:

`mpv --vid=no https://www.youtube.com/watch?v=Ga3maNZ0x0w`

It only buffers 4 seconds at a time, plays those 4 seconds, then stops and has to buffer again apparently.

The output looks something like this:

```
Playing: https://www.youtube.com/watch?v=Ga3maNZ0x0w
     Video --vid=1 (h264 1920x1080 60.000fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
AO: [coreaudio] 48000Hz stereo 2ch floatp
(Buffering) A: 00:00:04 / 00:00:00 Cache:  0s+2MB
[ffmpeg] tls: IO Error: -9806
(Buffering) A: 00:00:09 / 00:00:00 Cache:  0s+2MB
[ffmpeg] tls: IO Error: -9806
(Buffering) A: 00:00:14 / 00:00:00 Cache:  0s+2MB
[ffmpeg] tls: IO Error: -9806
A: 00:00:14 / 00:00:00 Cache:  4s+2MB
[ffmpeg] tls: IO Error: -9806
```

Full logfile: https://paste.ee/p/zueYV

I am on:
mpv 0.27.2
ffmpeg version 3.4.2

**Comment by wm4** [comment]
Well we don't care about old versions of anything.

**Comment by jsit** [comment]
Wow I was incredulous but I just installed mpv 0.28.2 and it now works fine 👍

**Comment by Akemi** [comment]
fixed.
