### ISSUE TITLE
Cross compilation terminology is off

### ISSUE THREAD

**Issue by Ericson2314** [mpv-player/mpv#4472]
Inherited from mplayer it seems like, your cross compilation terminology is off. The target platform is only relevent for compilers, or other tools which work with machine code potentially different than the one they run on. For all programs, host is the one it runs on, and build is the one it's built on.

Thus, `HOST`, not `TARGET`, is the environment variable you want here. Any other references to "target" should likewise be changed.

### mpv version and platform

Git master

### Reproduction steps

Read code block in https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md 

### Expected behavior

```
DEST_OS=win32 HOST=i686-w64-mingw32 ./waf configure
```

### Actual behavior

```
DEST_OS=win32 TARGET=i686-w64-mingw32 ./waf configure
```

**Comment by wiiaboo** [comment]
This isn't autoconf. TARGET is correct.

**Comment by Ericson2314** [comment]
Err I didn't mean to imply you were using Autoconf or the documentation does not match the implementation. The terminology was created by Autoconf, and using `TARGET` to mean something else, it's a bit of a footgun for distro packagers supporting cross compilation.

**Comment by wiiaboo** [comment]
I doubt @wm4 would be fine with a rename that just breaks existing scripts using it to pre-append the CHOST to cross-compiling tools.
If a rename would go through I'd suggest using CROSS_PREFIX instead.

**Comment by wm4** [comment]
Isn't this up to waf?

**Comment by Ericson2314** [comment]
@wm4 I would have feared that, but by @wiiaboo's quote of https://github.com/mpv-player/mpv/blob/master/wscript#L951 it looks like it actually isn't.

**Comment by Ericson2314** [comment]
I would

1. Continue to support `TARGET` for now but add a deprecation warning

2. Add a `--host` flag, which is pretty standard for these things.

**Comment by CounterPillow** [comment]
Could `HOST` just be made an alias of sorts for `TARGET` (or the other way around)? That way existing scripts don't get broken, and there's no conflict between the two anyway since mpv is not a compiler.

**Comment by wiiaboo** [comment]
@Ericson2314 Calling it standard doesn't really work since it's a different build system that doesn't come with built-in support for such things, thus why it's done in mpv's wscript.

I'd go with respecting both TARGET and HOST. They're just convenience anyway. The waf way of doing this would be setting CC/PKG_CONFIG/AR/WINDRES with the proper name.
