### ISSUE TITLE
Auto OSC Visibility stays shown when not covering video.

### ISSUE THREAD

**Issue by Chilledpeperami** [mpv-player/mpv#4474]
This is a feature request, I often watch videos on one half of the screen, this means that the OSC does not cover up any part of the video and hence has no disadvantage is being shown all the time.

A screenshot showing how the left video is with the OSC visibility set to always and the right one showing the OSC visibility set to auto.
![screenshot from 2017-06-01 11-58-22](https://cloud.githubusercontent.com/assets/19192677/26674806/e7bf75ce-46c1-11e7-9028-e3e584cad2f8.png)

**Comment by avih** [comment]
If I understand correctly, you want to always show the OSC if it doesn't cover any part of the video?

I'm not sure it's a good idea. Some people prefer to not see the OSC even if there's room to fit it without covering the video. There are also different OSC layouts and sizes, and each of them covers a different area of the screen. Also, video can be zommed in and zoom out and other manipulations. Making your request work for all cases is a lot of work for not much gain, IMO.

Your request sounds perfect for a lua script: if the relation between the video aspect ratio to the window aspect ratio fits whatever you like, set osc visibility mode to always. If you never zoom the video or use different OSC layouts, then it doesn't have to take them into account.

Also, you can just press DEL to set the OSC to be always visible.

**Comment by afritsch** [comment]
According to the manual, you can configure this behaviour.
https://mpv.io/manual/master/#on-screen-controller-visibility
You can try this, but I did not test it.
lua-settings/osc.conf
`
visibility=always
`

**Comment by avih** [comment]
> this key is not mentioned in the manual BTW

Sure it is. at the "Key Bindings" section of "Using the OSC" (just above "Configuration").

**Comment by Chilledpeperami** [comment]
Yes I know I can set it to always but then it also covers up a part of the video if the window and video aspect ratios are right.

What I mean is when the visibility is set to auto, the auto hide algorithim would know if the OSC wouldn't cover up the video, and show it always, since it will not cover up part of the video.

**Comment by wiiaboo** [comment]
Too troublesome. I'd point you to use a proper libmpv-using GUI instead with actual GUI elements.

**Comment by Dudemanguy** [comment]
This sounds like something that should be implemented in a script. You can use the `osd-dimensions` property to get the exact margins of the video and determine what you want to do from there.
