### ISSUE TITLE
VDPAU decoding or rendering allocates zero-length DRM buffer

### ISSUE THREAD

**Issue by bbarenblat** [mpv-player/mpv#4479]
### mpv version and platform

```
$ mpv --version
mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.5-1
```

I’m on Debian 9 (stretch) with a GeForce GTX 760 (NVE4/GK104/Kepler with VP5 decoding engine). I’m driving my card with Nouveau from Linux 4.11.0, and I’ve installed the proprietary firmware from version 325.15 of Nvidia’s driver, which Nouveau [needs for acceleration](https://nouveau.freedesktop.org/wiki/VideoAcceleration).

### Reproduction steps

`mpv --hwdec=vdpau --vo=vdpau video.mkv`

### Expected behavior

My kernel log doesn’t show anything unusual – maybe some notifications about firmware being direct-loaded.

### Actual behavior

Nouveau dumps hundreds of lines reading

```
nouveau 0000:00:0a.0: DRM: skipped size 0000000000000000
```

to my kernel log.

I believe this is a bug in mpv rather than in Mesa or Nouveau because playing the video with mplayer – `mplayer -vc ffh264vdpau -vo vdpau video.mkv` – prints no error messages.

### Log file

http://sprunge.us/CAWC

**Comment by wm4** [comment]
The vdpau code in mpv doesn't create DRM buffers (or any other kind of buffers), so it can't be mpv.
