### ISSUE TITLE
Screen tearing in multimonitor setup on Ubuntu

### ISSUE THREAD

**Issue by petran79** [mpv-player/mpv#4481]
I use latest MPV version in Ubuntu 16.04 with latest Nvidia drivers (381)

I use 2 monitors. A Gsync Asus ROG 34" set as primary and an LG W2361V set as secondary.
When I open a video file on Asus monitor I get screen tearing in full screen mode. No such problem if I drag the file to the LG monitor.

If I set the Asus monitor as primary and disable LG monitor, tearing problem disappears and videos play fine on fullscreen on Asus. Problem also disappears if I switch primary and secondary monitors. LG primary and Asus secondary. Even when I switch a second time to the initial configuration after that and make Asus primary monitor again, there is no tearing on the Asus monitor. 

Yet if I log out and enter again, tearing appears on Asus like the first time.

here are the settings in mpv config file

# MPV config

# Every possible settings are explained here:
# https://github.com/mpv-player/mpv/tree/master/DOCS/man

##################
# VIDEO
##################
# Video output
vo=opengl-hq

# Video filters
#vf=
vo=opengl:scale=ewa_lanczossharp:cscale=ewa_lanczos:dscale=mitchell:tscale=catmull_rom:scale-radius=3:scaler-resizes-only:tscale-clamp:dither-depth=8:deband:swapinterval=1:correct-downscaling:interpolation:prescale-passes=2:prescale-downscaling-threshold=1.6:post-shaders="~~/shaders/finesharp.glsl,~~/shaders/deband.glsl,~~/shaders/krig.glsl,~~/shaders/superres.glsl"
video-sync=display-resample
hwdec=no
framedrop=vo
# Start in fullscreen
# fullscreen

# Activate autosync
autosync=30

# Skip some frames to maintain A/V sync on slow systems
framedrop=vo

# Force starting with centered window
geometry=50%:50%

# Keep the player window on top of all other windows.
ontop=yes

# Disable screensaver
stop-screensaver=yes

# Enable hardware decoding if available.
#hwdec=auto

# Screenshot format
screenshot-format=png

##################
# AUDIO
##################
# Audio driver
ao=alsa

# Output channels (stereo)
audio-channels=2
af=format=channels=2

# Set volume to 100%
volume=100
volume-max=600

# Disable softvol usage
#softvol=no

# 130% amplification
softvol-max=130

##################
# SUBTITLES
##################
# Subtitle position to 93% of the screen
# sub-pos=93

# Subtitle font size
# sub-text-font-size=44

# Subtitle size
#sub-scale=1.2

# Thin border ASS subtitles
#ass-force-style=Outline=1

# Make the subtitle font size relative to the window, instead of the video
#sub-scale-with-window=yes

# Whether to scale subtitles with the window size (default: yes). 
# If this is disabled, changing the window size won't change the subtitle font size.
#sub-scale-by-window=no

# Change subtitle encoding. For Arabic subtitles use 'cp1256'.
# If the file seems to be valid UTF-8, prefer UTF-8.
#sub-codepage=utf8

**Comment by haasn** [comment]
You could try playing around with `__GL_SYNC_DISPLAY_DEVICE`.

**Comment by lachs0r** [comment]
I’m actually having some trouble with the driver ignoring `__GL_SYNC_DISPLAY_DEVICE`, probably since the switch to GLVND. I don’t know when exactly it stopped working because all three of my main displays operate with the same timings (modified EDID) and I only noticed it one day when trying to use my projector

In any case, this is a driver issue.
