### ISSUE TITLE
X/Y scaling of subtitles

### ISSUE THREAD

**Issue by MegaPramuk** [mpv-player/mpv#4483]
I'm not sure what exactly to call this but here goes.
Back when I was on Windows and used MPC-HC, there was an option to scale soft subtitles in both axis individually, e.g. one could set the X-axis scale of the subtitles to 800% while the Y-axis is scaled to 200%. That was great because of my second monitor being in a very wide resolution (3840x240@120) so I could just leave the resolution at that when I wanted to watch some old videos. Now I'm on GNU/Linux and mpv doesn't provide such option and those that scale the subtitles completely don't exactly help. 
I'm using ``--no-keepaspect`` to override the video's aspect ratio and stretch the video to fill my monitor.
``--sub-scale-with-window`` and ``--sub-scale-by-window`` don't do anything at all (just as their -ass- counterparts) and ``--sub-scale``, while it does enlarge the subtitles, they are still not comfortable to read (they're kinda squashed together and might cover the video if there's too much of a scale).
[Here's](https://my.mixtape.moe/ztejbr.jpg) Magic Knight Rayearth as an example. The first image being ``--sub-scale-with-window=yes``, second is ``--sub-scale-by-window=yes`` and third is ``--sub-scale=2.5``. You can imagine how squashed the letters are when the image is squashed into 4:3.

**Comment by MegaPramuk** [comment]
I forgot to mention, I've compiled master (fdd75f90a) to test this.

**Comment by rossy** [comment]
Yeah, mpv should probably do this when --monitorpixelaspect is set, but for some reason it doesn't, which is odd because the OSC is scaled. Another problem is that ``--monitorpixelaspect`` treats large values like ``1:12`` as out-of-range.

As a workaround, you could try ``--vf=sub``

**Comment by wiiaboo** [comment]
Probably needs a different --blend-subtitles value.

**Comment by MegaPramuk** [comment]
Using ``--vf=sub`` did the trick. Thanks!
Didn't know that video filters could also subs.

**Comment by wm4** [comment]
(That filter is going to be removed, and the behavior you see is actually sort of a bug.)
