### ISSUE TITLE
Question: MP4 smooth streaming ???

### ISSUE THREAD

**Issue by Sami32** [mpv-player/mpv#4486]
I apologize if i bother anyone here, but after hours of searches and tests, i struggle to find a way to make _**MEncoder**_ produce MP4 smooth streaming compliant (like _FFmpeg_ with `-movflags +faststart`.

I tried to play with `vglobal=1:aglobal=1` and `global_header`, but i wasn't able to put them in the same command line.  `-ovc x264` is used to be able to conform to MPEG4 AVC part 10.

Do that even possible ?
Any help will be greatly appreciated !

Thank you.

**EDIT**: Here an example of my command line:
```logtalk
mencoder.exe −cache 8192 −cache−min 4 -ss 0 dvd://1 -dvd-device <source file> -msglevel statusline=2 -vf scale=640:-10,expand=640:480,harddup -lavdopts threads=1 -ovc x264 -sws 9 -x264encopts preset=ultrafast:profile=baseline:bitrate=700:global_header:threads=auto:slow_firstpass -oac faac -faacopts mpeg=4:tns:object=2:raw:br=96 -of lavf -lavfopts format=mp4 -ofps 25 -nofontconfig -nosub -noautosub -af lavcresample=48000:srate=48000:channels=2 −alang fr,en,und
```

**Comment by wiiaboo** [comment]
This isn't the mplayer bug tracker.

**Comment by Sami32** [comment]
It's not a bug, it's a question.

Though i can understand if you don't know how to do that as well.

**Comment by wiiaboo** [comment]
This isn't a forum or user support channel for mplayer/mencoder either.
