### ISSUE TITLE
[Feature Req] .ugoira support

### ISSUE THREAD

**Issue by Bl4Cc4t** [mpv-player/mpv#4487]
Hey :)
I would love to see support for .ugoira files (i. e. created via [Nandaka/PixivUtil2](https://github.com/Nandaka/PixivUtil2/))!
At least I couldn’t find anything regarding these on here, so here I go.
Essentially, these are ordinary .zips with moving information in a .js file.
A workaround would also be nice.

Relating: [Nandaka/PixivUtil2/issues/69](https://github.com/Nandaka/PixivUtil2/issues/69)

**Comment by wm4** [comment]
Is there a sample?

But from the sound of it, this could be the worst video "format" I've ever encountered.

**Comment by wiiaboo** [comment]
Can't you just export it to a normal format like APNG, GIF or WebM with the same exact PixivUtil2?

**Comment by Bl4Cc4t** [comment]
@wm4 @wiiaboo Just checked, you can export it to GIF and APNG.
While GIF is obviously not an option (because of massive quality loss), APNG does a bit better.
The downsides are mainly the long time it takes to convert and the big size. It’s sometimes even bigger than the GIF (not in this comparison). 

Here a comparison (ugoira with 150 frames):
<img width="278" alt="bildschirmfoto 2017-06-07 um 3 09 53" src="https://user-images.githubusercontent.com/6740726/26880042-7c488ce6-4b93-11e7-9c01-71c5cd1b64ea.png">
Time-wise, the GIF took `1:06` to convert, the APNG `10:50` (and my computer is not that bad).
[Here’s a link to these.](https://u.nya.is/azxvyr.zip)

I know this may sound a bit childish, [but this honeyview player](https://www.bandisoft.com/honeyview) can play .ugoira as well (at least that’s what Nandaka claims). So I’d assume, it’s not impossible to do :)

**Comment by wiiaboo** [comment]
Not impossible, but that's an image viewer, mpv is not. Adding a pseudo-format only used by a single utility to export a pseudo-format only used by one site seems like the most niche usecase you can find.

**Comment by wiiaboo** [comment]
You could find a way to script this to the edl protocol if only that .js/.json information was outside the zip.
Otherwise, it'd need to be a specific demuxer inside FFmpeg/mpv specific to this pseudo-format.

**Comment by wiiaboo** [comment]
The link to the samples doesn't work, btw.

**Comment by marcan** [comment]
Honestly, you might be better off writing a remuxer that just converts it to some container with MJPEG and VFR support.

(disclaimer: I designed the original ugoira format)

**Comment by wm4** [comment]
Or just use mf:// if the delay values are all the same.

The source images are probably either png or jpg - png can go into APNG, jpg could go into mkv as mjpeg.

**Comment by marcan** [comment]
The images inside the zip are always PNG or JPEG.

Very specific implementations aside, does mpv support playback within a zip archive? That could be generically useful perhaps (not just ugoira, e.g. Android boot animations, or just slideshows in a zip). Not sure if implementation-wise it would be easy to add though.

**Comment by wm4** [comment]
mpv with libarchive can open zip files - it basically treats them as playlists, with special mangled archive paths as entries. But it can't use it for mf:// or --merge-files, so you can make it only treat them as separate images. EDL doesn't work with it either, due to questionable "security" mechanisms.

**Comment by wm4** [comment]
(Using EDL/--merge-files wouldn't be so great anyway, because it keeps all files open, including various buffers, which would result in quite a lot of bloat.)

**Comment by Bl4Cc4t** [comment]
That’s a nice script you found, @wiiaboo! From what I can see, it even uses the embedded json data.
**So, to sum it up:** the best way to view these animations is probably by remuxing them into a .mkv.
I also agree that this seems to be a very niche format and that it’s mainly build for online viewing.


But that support for .zips is given is also a nice thing to note, even if I’m unable to install `libarchive` (it gives me some strange error).
On a side note, I’d suggest putting a list with all formats mpv currently supports (with build flags if necessary) somewhere in the manual (I even searched for `zip` before I opened this issue).

Thanks for the help everyone!

**Comment by wm4** [comment]
What does the script do if the source files are png?

**Comment by wiiaboo** [comment]
Probably fail, but it could be adapted to use mp4 for png instead, according to @marcan.

**Comment by wm4** [comment]
Well, in theory, you can use png in mkv via VfW muxing. Very evil. (Reminder: VfW muxing is AVI compatibility in mkv.)

**Comment by wiiaboo** [comment]
At least with the two links I tried ([one](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=44524589) and [two](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=63272000), the delays are all uniform, so you could just download the zip will all the images and open the zip in mpv with `--loop --image-display-duration=<delay/1000>` and it'd work normally.

**Comment by wm4** [comment]
I tried muxing a mkv with png. FFmpeg actually refuses to remux apng to mkv, but png works (which means you'd need to write an awkward ffconcat file to put in multiple png files). mpv's demuxer eats this, and vlc seems to work too. Didn't actually try multiple frames.
