### ISSUE TITLE
any option for ffmpeg's protocol_whitelist

### ISSUE THREAD

**Issue by zhangn1985** [mpv-player/mpv#4488]
when playing  local m3u8 files, 
mpv will log:
```
[ffmpeg] http: Protocol not on whitelist 'file,crypto'!
[ffmpeg/demuxer] hls,applehttp: Failed to open segment of playlist 0
[ffmpeg] http: Protocol not on whitelist 'file,crypto'!
[ffmpeg/demuxer] hls,applehttp: Failed to open segment of playlist 0
[ffmpeg] http: Protocol not on whitelist 'file,crypto'!
```

after search ffmpeg support `-protocol_whitelist` option.

`ffmpeg -protocol_whitelist file,tcp,http -i test.M3U8 -c copy test.ts`

does mpv support something like that?
[tmpq63zvoks.m3u8.zip](https://github.com/mpv-player/mpv/files/1056627/tmpq63zvoks.m3u8.zip)

**Comment by wiiaboo** [comment]
[`--demuxer-lavf-o`](https://mpv.io/manual/master/#options-demuxer-lavf-o), probably.

**Comment by zhangn1985** [comment]
same as https://github.com/mpv-player/mpv/issues/2937
