### ISSUE TITLE
Go full scring without scaling the video

### ISSUE THREAD

**Issue by AlexCzar** [mpv-player/mpv#4489]
I googled around but couldn't find a way to go full screen without scaling the video. Preferrably via hotkey. E.g. `f` to go full screen `Alt+1` (doesn't matter, just an example) to set scale to original video size.
Why? Sometimes I prefer to view unscaled videos, but don't want the stuff behind the player to distract me. Ideally in such cases I'd open mpv full screen, have video in original size vertically and horizontally centered framed by black bars.

**Comment by haasn** [comment]
`--video-unscaled`?

**Comment by AlexCzar** [comment]
@haasn Awesome! Thanks! Don't know how have I missed it.
