### ISSUE TITLE
[question] Why is --enable-cplugins not enabled by default?

### ISSUE THREAD

**Issue by majewsky** [mpv-player/mpv#4491]
As of mpv 0.25.0, C plugin support must be enabled explicitly by setting `--enable-cplugins` at build time. What's the reason for this? I'm asking because I'd like to ask my distribution to ship mpv with plugin support enabled, but want to check first whether that's a safe thing for them to do.

**Comment by wm4** [comment]
Not much. Mostly just being careful. I enabled it by default for now, but if there are any problems I might revert it.

**Comment by majewsky** [comment]
Awesome, thanks! When do you plan your next release? If it's still some time, it's not a problem at all. But if you're planning on doing a release soon anyway, I will not annoy my packager about this.

**Comment by wm4** [comment]
Typically every 2-3 months, depends on @lachs0r.

**Comment by majewsky** [comment]
Got it. Thanks for the quick responses.

**Comment by Safari77** [comment]
11c7775b2c broke `waf build` on Fedora 25 x86_64 (bisected).
Using waf-1.9.12.

```
Waf: Leaving directory `/wrk/safari/cvs/mpv/build'
Build failed
Traceback (most recent call last):
  File "/usr/share/waf/waflib/Task.py", line 144, in process
    ret=self.run()
  File "/usr/share/waf/waflib/extras/syms.py", line 23, in run
    re_nm=re.compile(r'T\s+('+self.generator.export_symbols_regex+r')\b')
AttributeError: 'task_gen' object has no attribute 'export_symbols_regex'
```

**Comment by CounterPillow** [comment]
@Safari77 highly doubt that's the fault of that commit, but rather, you updating waf.

You should use the waf version that is specified in mpv, as different versions are incompatible with each other.

**Comment by Safari77** [comment]
I missed that waf 1.9.8 requirement.
