### ISSUE TITLE
Cannot seek on some hls streams that had been streamed live

### ISSUE THREAD

**Issue by danburd** [mpv-player/mpv#4492]
### mpv version and platform

Windows 10 64-bit 0.25.0

### Reproduction steps

mpv.exe https://intel-f.akamaihd.net/i/intel060717_1@76456/master.m3u8

### Expected behavior

The stream would load and there would be 00:00:00 on the left side of the seek bar and 02:54:47 would be on the right side of the seek bar (or whatever the precise length of the stream is). Also it would be possible to click inside the seek bar to view a different part of the stream.

### Actual behavior

26:19:20 is on the left side of the seek bar and --23:24:33 is on the right. Clicking the seek bar does not change your location within the stream, so the user cannot navigate to a different part of the stream.

### Log file

http://sprunge.us/SFYB

### Sample files

N/A

**Comment by wm4** [comment]
https://github.com/mpv-player/mpv/wiki/FAQ#Why_does_the_cache_not_work_for_Twitch_HLS_sites_and_some_youtube_links

**Comment by wm4** [comment]
(Also I might implement a packet cache that survives seeking, which could probably be used for this.)

**Comment by danburd** [comment]
Ok. If it's a know issue that's not going anywhere then feel free to close it as such. I didn't know if it was widely known.

**Comment by Akemi** [comment]
if this is still an issue, please open a new issue.
