### ISSUE TITLE
Caching disabled for some youtube-dl videos

### ISSUE THREAD

**Issue by desbma** [mpv-player/mpv#4495]
### mpv version and platform

MPV from Arch Linux repo: https://www.archlinux.org/packages/community/x86_64/mpv/

    $ mpv -V
    mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
     built on Mon May  8 20:03:32 CEST 2017
    ffmpeg library versions:
       libavutil       55.58.100
       libavcodec      57.89.100
       libavformat     57.71.100
       libswscale      4.6.100
       libavfilter     6.82.100
       libswresample   2.7.100
    ffmpeg version: 3.3.1

### Reproduction steps

Command that should play a video with caching enabled, but does not:
`$ mpv 'https://www.youtube.com/watch?v=9fffrIqzw8g'`

Similar commands that work as expected:
* With another video:
`$ mpv 'https://www.youtube.com/watch?v=9fffrIqzw8g'`

* By forcing another youtube-dl format:
`$ mpv --ytdl-format=best 'https://www.youtube.com/watch?v=9fffrIqzw8g'`

### Expected behavior

Caching should  be available for youtube-dl streams, for all videos.

### Actual behavior

Caching is not available for the first command, for no apparent reason.

### Log file

https://www.dropbox.com/s/mxjwg6o5ahlde6p/mpv.log?dl=0

**Comment by wiiaboo** [comment]
[FAQ answers your frequently asked question](https://github.com/mpv-player/mpv/wiki/FAQ#Why_does_the_cache_not_work_for_Twitch_HLS_sites_and_some_youtube_links).

**Comment by desbma** [comment]
Indeed.
I searched the issues but missed the FAQ, sorry.
