### ISSUE TITLE
AV synchronization lost on some lavfi audio filters when changing playback speed.

### ISSUE THREAD

**Issue by tsjnachos117** [mpv-player/mpv#4496]
I'm running mpv version 0.25.0-git-cc69650 on Ubuntu 16.04 (x64 version).

This can be reproduced like so: load mpv with an lavfi audio filter, press either <kbd>[</kbd> or <kbd>]</kbd> to change the playback speed, and just like that, audio/visual de-synchronization will likely occur. How much de-sychronization you experience depends largely on which filters you use. For example, acompressor only de-sychronizes by a few milli-seconds (an amount so small, it isn't really a problem), while dynaudnorm causes the audio to skip about 13.5 seconds ahead of the video (that's a problem). In my experience, this happens with all videos, regardless of the resolution, container, frame rate, etc. (I haven't tested this with audio-only files). Video can be instantly re-sycronized by fast forwarding or rewinding.

Also, I do have a custom ~/.mpv/config file, I don't think the contents of said file are relevant, since the issue persists even if I use the --no-config option.

PS: [Here, have a log file](https://github.com/mpv-player/mpv/files/1062622/output.txt) :smile:

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
