### ISSUE TITLE
Can't play https content

### ISSUE THREAD

**Issue by futuro** [mpv-player/mpv#450]
When attempting to play web content from an https address mpv fails with the following message
```
$ mpv https://soundcloud.com/howtodestroyangels/ice-age-the-soft-moon-remix
Playing: https://soundcloud.com/howtodestroyangels/ice-age-the-soft-moon-remix
[ffmpeg] tls: An unexpected TLS packet was received.
Failed to open https://soundcloud.com/howtodestroyangels/ice-age-the-soft-moon-remix.
```

This does not happen with the following url:
https://www.youtube.com/watch?v=BYvAARH5z2k

-F

**Comment by wm4** [comment]
We don't use libquvi anymore. So the craptastic unsafe behavior of all these SSL libs shouldn't be tripped up anymore, simply because there's only 1 user of these libs in the process.
