### ISSUE TITLE
"Invalid play entry" for dvd://title/dir if dir name contains dash

### ISSUE THREAD

**Issue by arvidjaar** [mpv-player/mpv#4502]
### mpv version and platform

Ubuntu 16.04, 2:0.25.0+git4~xenial from mc3man repository

### Reproduction steps
Try to play explicit title from  directory with dash in name, like `dir-1`

### Expected behavior
Video is played

### Actual behavior
Parsing failure:

```
$ mpv dvd://1/dir-1/
Invalid play entry dvd://1/dir-1/
```

**Comment by mc4man** [comment]
Probably because support for dvd's (and audio cd's) wasn't enabled & hasn't for a couple of months.
I guess it (dvd) could be enabled next time, doesn't matter to me one way or the other.
(- audio cd's in mpv is a waste of time & won't be returned.

**Comment by mc4man** [comment]
you could close this as it was an invalid report to start with & I re-enabled dvd support for the 0.05% of users that would want it.
And wtf dvd://1/dir-1/ is I won't know..
