### ISSUE TITLE
Play video without sound

### ISSUE THREAD

**Issue by exxfzc** [mpv-player/mpv#4507]
macos 10.12,mpv 0.25

Last login: Sat Jun 10 22:03:26 on ttys000
zilingdeMacBook-Pro:~ ziling$ http://v.youku.com/v_show/id_XNTE3ODIxMjQ=.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.2
[1] 1778
-bash: http://v.youku.com/v_show/id_XNTE3ODIxMjQ=.html?spm=a2h0k.8191407.0.0: No such file or directory
zilingdeMacBook-Pro:~ ziling$ mpv http://v.youku.com/v_show/id_XNTE3ODIxMjQ=.html?spm=a2h0k.8191407.0.0&from=s1.8-1-1.2
[2] 1785
[1]   Exit 127                http://v.youku.com/v_show/id_XNTE3ODIxMjQ=.html?spm=a2h0k.8191407.0.0
zilingdeMacBook-Pro:~ ziling$ Resuming playback. This behavior can be disabled with --no-resume-playback.
Loading config '/Users/ziling/.config/mpv/watch_later/280E44D0459B8AE48F29A468B7F57361'
Playing: http://v.youku.com/v_show/id_XNTE3ODIxMjQ=.html?spm=a2h0k.8191407.0.0
[markfinished] Not have tag 1 nil 
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
[drc] libavfilter filter 'drc' not found!
Couldn't create or open audio filter 'drc'
Error at audio filter chain pre-init!
Audio: no audio
failed to init videotoolbox decoder: Hardware doesn't support accelerated decoding for this stream or Videotoolbox decoder is not available at the moment (another application is using it). (-78)
VO: [opengl] 512x288 yuv420p
[ffmpeg] NULL: missing picture in access unit with size 2760

**Comment by CounterPillow** [comment]
```
[drc] libavfilter filter 'drc' not found!
Couldn't create or open audio filter 'drc'
Error at audio filter chain pre-init!
```

there's your problem. Remove drc from your config.
