### ISSUE TITLE
mediainfo<>mpv id mapping? source data

### ISSUE THREAD

**Issue by Selur** [mpv-player/mpv#4509]
since:
`mpv "f:\TestClips&Co\MPEG-4 H.264\multivideo.m2ts" --aid=no --sid=no --vid=no --msg-level=all=status`
doesn't give me much data about the audio, video, subtitle streams:
```
     Video --vid=1 (h264 720x480 23.976fps)
     Video --vid=2 (h264 1920x1080 23.976fps)
     Audio --aid=1 (dts 6ch 48000Hz)
     Audio --aid=2 (dts 6ch 48000Hz)
     Audio --aid=3 (ac3 6ch 48000Hz)
     Audio --aid=4 (ac3 6ch 48000Hz)
     Audio --aid=5 (ac3 6ch 48000Hz)
     Subs  --sid=1 (hdmv_pgs_subtitle)
     Subs  --sid=2 (hdmv_pgs_subtitle)
     Subs  --sid=3 (hdmv_pgs_subtitle)
     Subs  --sid=4 (hdmv_pgs_subtitle)
     Subs  --sid=5 (hdmv_pgs_subtitle)
     Subs  --sid=6 (hdmv_pgs_subtitle)
     Subs  --sid=7 (hdmv_pgs_subtitle)
     Subs  --sid=8 (hdmv_pgs_subtitle)
```
I would like to map the data I get from mediainfo using:
`mediainfo --full "f:\TestClips&Co\MPEG-4 H.264\multivideo.m2ts"`
to the data I got from mpv.

So I got a few questions:

Can I rely on that mpv and mediainfo always use the same audio/video/subtitle order?
Thus that mpvs vid=1 always matches to 'Video #1'? (analog for audio, subtitle)

Also is there a way to get more data about each track?

**Comment by wiiaboo** [comment]
> Can I rely on that mpv and mediainfo always use the same audio/video/subtitle order?

No. Mediainfo doesn't use FFmpeg/Libav as backend like mpv, so you're not absolutely guaranteed to get the same information from both.

> Also is there a way to get more data about each track?

[mpv_identify.sh](https://github.com/mpv-player/mpv/blob/master/TOOLS/mpv_identify.sh)?

**Comment by Selur** [comment]
> mpv_identify.sh?
might be useful on Linux, but not on Windows,...

**Comment by wiiaboo** [comment]
I meant it as an example of what kind of information you can get from mpv and how you'd get it.
You can port it to whatever language runs on Windows or add it to a compiled program.

**Comment by Selur** [comment]
Okay. Got any documentation about what properties can be checked?
Or are:

`filename
        path
        stream-start
        stream-end
        stream-length
        demuxer
        length
        chapters
        editions
        titles
        duration
        audio
        audio-bitrate
        audio-codec
        audio-codec-name
        video
        angle
        video-bitrate
        video-codec
        video-format
        video-aspect
        fps
        width
        height
        dwidth
        dheight
        sub` all the available properties?

**Comment by wiiaboo** [comment]
https://mpv.io/manual/master/#property-list

**Comment by Selur** [comment]
thanks.
