### ISSUE TITLE
What is the relationship/difference between mpv and MPlayer-1.3.0?

### ISSUE THREAD

**Issue by shevegen** [mpv-player/mpv#4510]
[FAQ Addition]: Could there be a new entry added to the FAQ of this project? In particular my question, and perhaps that of some other people, is - what is the relationship/difference between mpv and MPlayer-1.3.0 e.g.? Is the latter obsolete or why should mpv be used and such? Does not need to be a long entry, just perhaps a short comment - I read about mpv first on the original mplayer homepage by Compn.

Thank you for considering and apologies for putting the issue in the title. :D

**Comment by CounterPillow** [comment]
The README already links to an [incomplete and now unmaintained list of changes](https://github.com/mpv-player/mpv/blob/master/DOCS/mplayer-changes.rst). The list of changes has become so big, it's unreasonable to keep maintaining this and mpv should be seen as an entirely new player.

In short: mpv is alive and throws out old broken code, mplayer is dead and clings onto old broken code like a hoarder.

One important change is that mpv, unlike mplayer, does not copy ffmpeg code into its codebase internally and update it once in a blue moon, but actually properly uses ffmpeg.

**Comment by wiiaboo** [comment]
mpv stopped merging changes from mplayer a long time ago, so other than the existing documentation already mentioned there's no way of knowing the actual differences between the two players.

**Comment by wm4** [comment]
Added this: https://github.com/mpv-player/mpv/wiki/FAQ#How_is_mpv_related_to_MPlayer

The short form is "mpv is not MPlayer".
