### ISSUE TITLE
Ability to jump in playlist

### ISSUE THREAD

**Issue by adeshkp** [mpv-player/mpv#4514]
There should be an option/command to jump entries in a playlist. This can help when viewing a long playlist from start and you do not save the position at the playlist. Although `--playlist-start` can help in these situations, it would be better to have commands for interactive control to improve experience.

I tried following in `input.conf` and obviously it does not work:
`shift+enter set playlist-pos ${=playlist-pos}+10`

I get following error with mpv 0.24.0
_The playlist-pos option must be an integer: 0+10_
_Failed to set property 'playlist-pos' to '0+10'_

**Comment by wiiaboo** [comment]
That's because input.conf doesn't do math. Do it in a lua script and it'll work fine.

**Comment by jdoe0** [comment]
This works for me: `shift+enter add playlist-pos 10`

**Comment by adeshkp** [comment]
Thanks jdoe0! That did the trick.

**Comment by wiiaboo** [comment]
I'd forgotten about that basic command :V

**Comment by SteveJobzniak** [comment]
@adeshkp @jdoe0 In addition to the built-in command above, you may want to try out my [Leapfrog](https://github.com/SteveJobzniak/mpv-tools) mpv script instead. Its advantage is that it provides nice on-screen feedback about the jump.
