### ISSUE TITLE
Waf script '1.9.8' and library '1.8.12' do not match

### ISSUE THREAD

**Issue by mtdeguzis** [mpv-player/mpv#4515]
### mpv version and platform

Platform: Linux
OS: Debian Jessie

### Reproduction steps

Clone latest release

Run (`--libdir` can be omitted for testing)
```

        python ./waf -v configure                                       \
                        --prefix=/usr                                   \
                        --libdir=/usr/lib/$(DEB_HOST_MULTIARCH)         \
                        --confdir=/etc/mpv                              \
                        --zshdir=/usr/share/zsh/vendor-completions      \
                        --enable-cdda                                   \
                        --enable-sdl2                                   \
                        --enable-sndio                                  \
                        --enable-zsh-comp                               \
                        --enable-libmpv-shared                          \
                        --disable-build-date
```

### Expected behavior

Configure stage completes

### Actual behavior

Error:
```

make[1]: Entering directory '/build/mpv-0.25.0+git+bsos1'
test -s ./waf && python ./waf -v distclean || true
Waf script '1.9.8' and library '1.8.12' do not match (directory '/build/mpv-0.25.0+git+bsos1')
find . -name "*.pyc" -delete
make[1]: Leaving directory '/build/mpv-0.25.0+git+bsos1'
   dh_clean
 debian/rules build
dh build
   dh_testdir
   dh_update_autotools_config
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/build/mpv-0.25.0+git+bsos1'
python bootstrap.py
Waf script '1.9.8' and library '1.8.12' do not match (directory '/build/mpv-0.25.0+git+bsos1')
Traceback (most recent call last):
  File "bootstrap.py", line 14, in <module>
    wafver = subprocess.check_output([sys.executable, './waf', '--version']).decode()
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', './waf', '--version']' returned non-zero exit status 1
debian/rules:7: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 1
make[1]: Leaving directory '/build/mpv-0.25.0+git+bsos1'
debian/rules:4: recipe for target 'build' failed
```

### Log file

Log file:  http://sprunge.us/XUbP

**Comment by jcowgill** [comment]
I assume this is based on the Debian mpv package? Debian has a `03_waf.patch` which manually patches in waf so that it doesn't need to download it from the internet during the build (and for other long complex reasons...). You will need to update that patch for waf 1.9.8 or just remove it if you don't care about this stuff.

In any case this is not an upstream bug.

**Comment by mtdeguzis** [comment]
Ah... I am using a that patch, sorry about that. Just needs updated.

**Comment by CounterPillow** [comment]
Since you appear to be trying to build a more recent version on Debian, you may also run into issues where your distribution's ffmpeg/Libav version is too old. Consider trying [mpv-build](https://github.com/mpv-player/mpv-build), which will link in a recent version of ffmpeg.

**Comment by mtdeguzis** [comment]
I have ffmpeg 2.8 ported form Ubuntu (enabled some extras needed for packages like Kodi). I am working on getting that up to 3.2.2 for the latest mpv. If not, I will stick to 22 (I think that was the cutoff) until Valve can bump SteamOS to Debian Stretch as a base.

**Comment by CounterPillow** [comment]
Considering there are API differences between 2.8 and 3.x, the way to go is definitely to use mpv-build then, so that you do not break Debian repo software on your system that depends on ffmpeg 2.8.

**Comment by mtdeguzis** [comment]
I was planning on building 3.x to my testing repo, then rebuilding the handful packages that rely on ffmpeg components as a dependency. If I don’t I and going to stick with version 22 here as noted above. Thank you for the pointer though.

Thank you,

----------------------------------------------------------------------------------------------------------------------------
Michael DeGuzis | Systems Engineer | CDIS-IT. | Geisinger Health System
mtdeguzis@geisinger.edu<mailto:mtdeguzis@geisinger.edu> | Office 570-214-3765 | Mail code 30-71
100 N. Academy Ave  Danville, PA  17822-3071 | www.geisinger.org<http://www.geisinger.org/>
