### ISSUE TITLE
How is it possible to display properties in OSD with JSON API?

### ISSUE THREAD

**Issue by alezost** [mpv-player/mpv#4517]
Hello, sorry if it's something obvious and documented, but I couldn't find an answer.

### mpv version and platform

mpv 0.25.0 on Arch Linux

### Reproduction steps

1. The following command:
```
echo 'show-text "speed: ${speed}"' | socat - /tmp/mpv-socket
```
displays `speed: 1.00` as expected

2. The following command:

```
echo '{"command":["show-text","speed: ${speed}"]}' | socat - /tmp/mpv-socket
```

displays `speed: ${speed}`. 

Is it intended? and if so,  may I ask, what is the correct way to display speed and other properties in OSD using JSON API?

Thanks.

**Comment by alezost** [comment]
Also a related question, if you don't mind:

```
echo show-progress | socat - /tmp/mpv-socket
```

works as expected, and this:

```
echo '{"command":["show-progress"]}' | socat - /tmp/mpv-socket
```

doesn't display anything.

**Comment by wm4** [comment]
You need to add one of the osd prefixes to enable the OSD for the command. It's disabled by default.

Probably confusing, maybe I'll change the defaults for OSD commands specifically.

**Comment by alezost** [comment]
Sorry, but it is still confusing :smile:

Could you please explain what `osd prefixes` are, and how to enable them?

**Comment by wiiaboo** [comment]
@alezost https://mpv.io/manual/master/#command-interface-osd-auto

**Comment by alezost** [comment]
Thanks, @wiiaboo, but even after reading that, I don't understand what to do :-(

`Input Command Prefixes` section begins with:

    These prefixes are placed between key name and the actual command.

but I can't grasp where this "between" should be placed in the following
command:

```
echo '{"command": ["show-progress"]}' | socat - /tmp/mpv-socket
```

Could you please show me JSON command that shows progress OSD?

Also the manual says:

    All of the osd prefixes are still overridden by the global --osd-level settings.

But when I run mpv with `--osd-level=1`, JSON commands still don't display properties in OSD.

**Comment by wiiaboo** [comment]
```
echo '{"command": ["osd-auto", "show-progress"]}' | socat - /tmp/mpv-socket
```
probably.

**Comment by alezost** [comment]
@wiiaboo, this doesn't work for me.  Did you actually check it?

**Comment by wiiaboo** [comment]
No, I don't have socat. But i tried with an alternative and `show-text` doesn't work either, with any prefix.

**Comment by garoto** [comment]
I believe you need an `expand-properties` call for actually be able to expand properties. On my Windows (8.1), this works:

`echo {"command": ["expand-properties", "show-text", "${audio-codec}"]} >\\.\pipe\mpv-socket`

And the `echo {"command": ["osd-auto", "show-progress"]}>\\.\pipe\mpv-socket` shown above works too.

**Comment by alezost** [comment]
@wiiaboo, @garoto Thanks! Apparently I failed to check the commands properly.  Now I see both your variants work :blush:

@wm4, I believe it would be good to enable these OSD prefixes for JSON API by default.

I'm closing this issue, thanks for the help!
