### ISSUE TITLE
[vo/opengl] dither setup: OpenGL error INVALID_ENUM

### ISSUE THREAD

**Issue by alfrix** [mpv-player/mpv#4519]
This error started to show up since version 25, however mpv seems to work regardless of this issue.

Win10 15063
Nvidia 9600gt (driver 342.01)
Mpv 0.25 

```
Playing: .\1-Black Clipping.mp4
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
[vo/opengl] High bit depth FBOs unsupported. Enabling dumb mode.
[vo/opengl] Most extended features will be disabled.
VO: [opengl] 1920x1080 yuv420p
[vo/opengl] dither setup: OpenGL error INVALID_ENUM.
MPV_VERSION=mpv 0.25.0
V: 00:00:00 / 00:05:00 (0%) DS: 3.560/1
Exiting... (Quit)
```
Git version
```
Playing:
 .\1-Black Clipping.mp4
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
[vo/opengl] High bit depth FBOs unsupported. Enabling dumb mode.
[vo/opengl] Most extended features will be disabled.
VO: [opengl] 1920x1080 yuv420p
[vo/opengl] dither setup: OpenGL error INVALID_ENUM.
MPV_VERSION=mpv 0.25.0-117-g4e12baf3d
V: 00:00:01 / 00:05:00 (0%) DS: 3.548/6
Exiting... (Quit)
```
### Reproduction steps
play any video

**### Expected behavior
No errors like in 24**
```
Playing: .\1-Black Clipping.mp4
 (+) Video --vid=1 (*) (h264)
[vo/opengl] High bit depth FBOs unsupported. Enabling dumb mode.
[vo/opengl] Most extended features will be disabled.
VO: [opengl] 1920x1080 yuv420p
MPV_VERSION=mpv 0.24.0-git-0f1afc6ba
V: 00:00:01 / 00:05:00 (0%) DS: 3.543/2
Exiting... (Quit)
```

**Comment by Hrxn** [comment]
I think that's the real problem here:
> [vo/opengl] High bit depth FBOs unsupported. Enabling dumb mode.

**Comment by haasn** [comment]
Regardless of high bit FBOs being supported or not, mpv should not normally be throwing OpenGL errors, and this sounds like a regression. But without a log it's impossible to say anything else.

**Comment by alfrix** [comment]
Full log https://pastebin.com/Zvd8384H

**Comment by haasn** [comment]
Hmm, don't see anything particular that seems out of place. Does `--dither=no` help?

**Comment by alfrix** [comment]
> Does --dither=no help?

yes, no errors in that case

dither=8 also causes the error

**Comment by lachs0r** [comment]
Could be a problem with ANGLE. Try with my builds, and if that doesn’t work, a different `--opengl-backend`.

**Comment by alfrix** [comment]
> Could be a problem with ANGLE

Yes it is, because it doesn't happen with --opengl-backend=win or --opengl-backend=dxinterop 

> Try with my builds

The first short log it´s from your build (MPV_VERSION=mpv 0.25.0)

**Comment by Hrxn** [comment]
What happens if you try `ffplay`? Does this work without any issues?

**Comment by haasn** [comment]
> What happens if you try ffplay? Does this work without any issues?

Don't see how that's relevant at all. We essentially already know the problem has something to do with the texture format being chosen to upload the dither texture. I doubt `ffplay` is relevant at all.

**Comment by wm4** [comment]
ffplay uses SDL's YUV overlay feature for video, so you get "whatever" (literally). So, very not relevant.

**Comment by Hrxn** [comment]
Yeah, but the GPU is rather old, and so is the driver. If mpv switches to OpenGL dumb mode, it could indicate that something is not working properly, or not supported at all.
If you try to run `ffplay` on an somewhat old system, you should get a similar OpenGL error message, and it probably doesn't work at all because it doesn't have mpv's fallback mechanism.

**Comment by alfrix** [comment]
I don't see how ffplay is relevant but here you go https://pastebin.com/jGTX1b6r

**Comment by quilloss** [comment]
https://github.com/mpv-player/mpv/blob/master/video/out/opengl/video.c#L2196-L2199
Missing else?

**Comment by wm4** [comment]
Actually if the else branch happens, it should error out or so.

But no idea why the else branch would happen in the first place. It could happen only with old GLES versions.

**Comment by Hrxn** [comment]
Okay no error with ffplay, then scratch that.
mpv shouldn't be in OpenGL dumb mode, but it somehow is.
But I think it's something specific to your config still..

**Comment by quilloss** [comment]
>It could happen only with old GLES versions.

I thought GLES 2.0 doesn't support 16 bit textures.

**Comment by alfrix** [comment]
The OpenGL support of the 9600gt https://pastebin.com/V650b0wM

**Comment by haasn** [comment]
> mpv shouldn't be in OpenGL dumb mode, but it somehow is

I don't get why you're so hung up about dumb mode. Dumb mode literally exists to make sure mpv works properly on environments like this. Entering dumb mode on hardware where nothing else is supported is *not* a bug, but erroring during dither texture creation certainly is.

**Comment by wm4** [comment]
Dumb mode doesn't even disable dithering.

Anyway, the real issue is that GLES 3.0 context creation seems to fail. It shouldn't fail, because his ANGLE is new and I suppose he uses nvidia d3d11 drivers.

The dithering thing is a bug (it should either fallback to a working dithering method, or disable it), but the real problem is that something is going wrong with ANGLE.

**Comment by alfrix** [comment]
> Anyway, the real issue is that GLES 3.0 context creation seems to fail.

I believe that this card doesn´t support GLES 3.0 since that would require OGL 4.3

i was sure that this bug appeared on 0.25, but after looking at f8861f681f5b18ebb it may be older

**Comment by Hrxn** [comment]
> Dumb mode doesn't even disable dithering.

Was just going to ask since when, but okay he already found it: https://github.com/mpv-player/mpv/commit/f8861f681f5b18ebb9c32cb6e4909766f92b9263, Mar 20 2017.

> I believe that this card doesn´t support GLES 3.0 since that would require OGL 4.3

That's the real question. Maybe it's somehow trying to run something between GLES 2 and GLES 3, heh.

**Comment by rossy** [comment]
Yeah, IIRC ANGLE only supports GLES 3.x on Direct3D feature level 10_1 and up. If that log is correct, the card only supports up to 10_0, so creating a GLES 2.0 context should be correct.

**Comment by wm4** [comment]
> Yeah, IIRC ANGLE only supports GLES 3.x on Direct3D feature level 10_1 and up. If that log is correct, the card only supports up to 10_0, so creating a GLES 2.0 context should be correct.

That's a shame, given the HW can do everything we actually need. The Windows situation still sucks, I guess.
