### ISSUE TITLE
option to use stereo jack output even with mono audio files

### ISSUE THREAD

**Issue by wolftune** [mpv-player/mpv#4524]
### mpv version and platform

I'm on 0.25 and KDE Neon but should be a universal issue

### Reproduction steps

Use the ao=jack and open a mono audio file

### Expected behavior

connection of the single mpv output to both top two output channels for the audio interface

### Actual behavior

connection to only one output means only one side of stereo speakers or headphones get used

### Sample files

https://0x0.st/lPD.ogg

**Comment by wm4** [comment]
ao_jack does exactly what it's told to do: output mono. What Jack does with it is your problem. You can probably force the way ao_jack outputs with --audio-channels=2 or with specific audio filters, but beyond that, we can't fix Jack.

**Comment by wolftune** [comment]
@wm4 thanks! To my surprise, audio-channels=2 worked! I didn't see that in the jack section of the manual where I was looking, but I thought it would create 2 channels but still output on only 1 (so, my assumption was the correct approach was to have only 1 channel but connect to 2 jack output channels, which would indeed work)… but that argument just did it! The audio outputs on both of the 2 channels. Cheers!
