### ISSUE TITLE
man page incomplete sentence: In earlier mpv versions

### ISSUE THREAD

**Issue by jcowgill** [mpv-player/mpv#4525]
Forwarded from https://bugs.debian.org/864908

`DOCS/man/options.rst` contains this:

```rst
``--audio-spdif=<codecs>``
    List of codecs for which compressed audio passthrough should be used. This
    works for both classic S/PDIF and HDMI.

    Possible codecs are ``ac3``, ``dts``, ``dts-hd``. Multiple codecs can be
    specified by separating them with ``,``. ``dts`` refers to low bitrate DTS
    core, while ``dts-hd`` refers to DTS MA (receiver and OS support varies).
    If both ``dts`` and ``dts-hd`` are specified, it behaves equivalent to
    specifying ``dts-hd`` only.

    In earlier mpv versions

    .. admonition:: Warning

        There is not much reason to use this. HDMI supports uncompressed
        multichannel PCM, and mpv supports lossless DTS-HD decoding via
        FFmpeg's new DCA decoder (based on libdcadec).
```

The "In earlier mpv versions" line doesn't make any sense and looks incomplete to me.

**Comment by wm4** [comment]
That was probably me not finishing the sentence, but I have no idea what I wanted to write.

**Comment by downthomas** [comment]
Maybe something about how all codecs in the spdif family were possible in earlier versions?
Here's the commit where you changed it originally: [c560f6ff0ab9aec70e53a268e2ff388a85ec3ca0](https://github.com/mpv-player/mpv/commit/c560f6ff0ab9aec70e53a268e2ff388a85ec3ca0).
