### ISSUE TITLE
Blu-ray multi angle support

### ISSUE THREAD

**Issue by Selur** [mpv-player/mpv#4528]
Since I can't find anything inside the manual I guess mpv doesn't support multi-angle Blu-ray discs.
Would be nice if either someone can point me on how to select the angle of Blu-ray input or if support for this could be added. (Haven't checked, but since FFplay support it, libbluray should too,..)

**Comment by wiiaboo** [comment]
Try with --dvd-angle or setting the property `angle`.

**Comment by Selur** [comment]
--dvd-angle for blu-ray? okay, will try tomorrow,..
