### ISSUE TITLE
Failed to build master branch

### ISSUE THREAD

**Issue by SchweinDeBurg** [mpv-player/mpv#4529]
### mpv 0bac1a52e8a5e60359dc010551a36ab7940ed552,  Linux (CentOS 6.9 32-bit)

```
[242/246] Compiling build/osdep/main-fn-unix.c.16.o
Waf: Leaving directory `/home/elijah/rpmbuild/BUILD/mpv-0.25.0-git/build'
Build failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/waf-1.9.12/waflib/Task.py", line 145, in process
    ret=self.run()
  File "/usr/lib/python2.7/waf-1.9.12/waflib/extras/syms.py", line 24, in run
    re_nm=re.compile(r'T\s+('+self.generator.export_symbols_regex+r')\b')
AttributeError: 'task_gen' object has no attribute 'export_symbols_regex'
```

**Comment by lachs0r** [comment]
If this is an older clone, make sure to clean the build directory and re-run waf configure first.

**Comment by SchweinDeBurg** [comment]
No, it was result of the rpmbuild inside the clean directory.

**Comment by lachs0r** [comment]
Try using the waf version that is pulled by mpv’s bootstrap.py script (1.9.8).

**Comment by SchweinDeBurg** [comment]
Just tried... unfortunately, result is the same...

**Comment by SchweinDeBurg** [comment]
Hm-m-m... looks very strange... Using https://waf.io/waf-1.9.12 I just successfully built mpv. But the same version of waf used from installed RPM package produces the above error. Anyway, this issue should be closed. :-)
