### ISSUE TITLE
Python 2 -> 3

### ISSUE THREAD

**Issue by tenplus1** [mpv-player/mpv#4531]
is it possible to build mpv against python3 so we can finally remove python2 from distros.

**Comment by Argon-** [comment]
Huh? homebrew (OSX package manager) is using python3 to build mpv for a long time (except for building the manual because of some strange PATH stuff with docutils).

**Comment by CounterPillow** [comment]
What do you mean, "build against"?

Afaik the only thing that uses python is the waf build system, and waf is fine with both python 2 and python 3, as long as you don't mix the two.

**Comment by wm4** [comment]
mpv is not built against Python (except maybe indirectly via vapoursynth, which requires Python 3). waf should work with both Python versions.

**Comment by in-in** [comment]
But it still forces you to download Python2 on Ubuntu 18.04
If you need the latest version from this PPA `ppa:mc3man/mpv-tests`

![18061201](https://user-images.githubusercontent.com/8797432/41272373-7fe74560-6e1d-11e8-872b-cbbc0697cc32.png)

**Comment by j605** [comment]
So build it yourself or report it to the PPA author. What does an error in packaging  have to do with this issue?

**Comment by in-in** [comment]
The problem was with recommended packages
This `--no-install-recommends` option omits the installation of Python2
`sudo apt install --no-install-recommends mpv`
