### ISSUE TITLE
Place screenshots on a folder with the video title

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#4532]
Would this be possible? Something like

`screenshot-directory="C:/Users/George/Video Screenshots/$video_name$/"`

**Comment by haasn** [comment]
The directory can be part of the `screenshot-template` option.

**Comment by firewater2** [comment]
How would I do that? I tried `"%F/"%F %P"` but no dice.

Just to be clear, the result I want is:

Taking a screenshot for "Star Wars" video = "C:/Users/George/Video Screenshots/Star Wars/Star Wars 00_01_54.989.jpeg"
Taking a screenshot for "Manchester by the Sea" video = "C:/Users/George/Video Screenshots/Manchester by the Sea/Manchester by the Sea 00_01_54.989.jpeg"

**Comment by otommod** [comment]
It has to do with the fact the directory does not exists and mpv won't try to create it.

**Comment by firewater2** [comment]
Yeah, that's what I'm asking - if there is a way it can create it like that for each file, but I guess not, so all I can do is request it.

**Comment by otommod** [comment]
You can do it with a Lua script, such as
```lua
mp.register_event("file-loaded", function()
    local dirname = mp.get_property("filename/no-ext")
    mp.set_property("options/screenshot-directory", dirname)
end)
```

This will make sure that the `screenshot-directory` option is always set to the name of the current file (without the extension).

**Comment by firewater2** [comment]
Nice!!! Thanks!! Any chance it could create the folder on the path specified on `screenshot-directory`? Right now it's making it on the same folder as the video. I tried, but I don't know .lua nor much coding so it didn't work.

**Comment by otommod** [comment]
Try this
```lua
local utils = require("mp.utils")
local basedir = mp.get_property("options/screenshot-directory")
mp.register_event("file-loaded", function()
    local filedir = mp.get_property("filename/no-ext")
    local dir = utils.join_path(basedir, filedir)
    mp.set_property("options/screenshot-directory", dir)
end)
```

**Comment by firewater2** [comment]
Certified hacker stuff right here, thanks so much!!

**Comment by idlinnes** [comment]
screenshot-template='%F/%F-%n-%p'
