### ISSUE TITLE
Load files in an already running mpv instance

### ISSUE THREAD

**Issue by adeshkp** [mpv-player/mpv#4534]
### mpv 0.24.0

I'm not able to able to find a way to load a file in an already running mpv instance. I tried simple-loader.lua, but when I press Alt+Enter it makes mpv exit. Also script starts with "/tmp" directory.

I also found "loadfile" command in documentation but not sure how to make that work with a keybinding and an arbitrary file path. So, please suggest how this can be done.

**Comment by wiiaboo** [comment]
In input.conf add:
`<key> loadfile "${path}"`

**Comment by lachs0r** [comment]
See also `TOOLS/umpv` in the source tree.

**Comment by fhlfibh** [comment]
@adeshkp Personally, I don't quite understand what exactly you want to achieve, but that's how `simple-loader.lua` works:
That script is a kind of OSD, i.e. on screen it shows a list of files in a given dir and let you move up and down the list selecting the file you want, and then let you load that selected file into mpv for playback.
For that, mpv must already be in _running_ (actually, idle) state, i.e. you should start it something like `mpv --idle --force-window=yes --fullscreen --script=/simple-loader.lua --script-opts=top-dir=/path/to/your/top-level-dir`
When you select a file from list (its filename gets yellow) and press `Alt-Enter` -- the script loads that file into mpv (i.e. starts playback). When you press `Alt-Enter` during active playback -- nothing should happen (in theory). When you press `Alt-End` during active playback -- playback stops and you're back to the file list to select a new file. Also the script has an option `--top-dir` to change default /tmp to anything you want.

**Comment by adeshkp** [comment]
@fhlfibh Thanks for the response! Maybe I was not using the script properly. /tmp didn't have any video files, so it might have caused the player to exit.

Anyway I have solved my problem. Now I'm using `loadfile` command through JSON IPC with my custom shell script to handle JSON fiddling.
