### ISSUE TITLE
License change and functions dropped.

### ISSUE THREAD

**Issue by qwerty007** [mpv-player/mpv#4536]
Shouldn't at least the man page be updated? It still says I can use 'I' to show filename on the OSD, but it doesn't work anymore and I get
`[input] No key binding found for key 'I'.`
in the terminal.
It's the result of
https://github.com/mpv-player/mpv/commit/2e84934be7d419da91c2bc0682d71087439d66ad
referring to
https://github.com/mpv-player/mpv/commit/116ca0c768219b10eeee1f68b5b0365916d4b4e0

**Comment by thebombzen** [comment]
Closed by #4537. Should it be closed?

**Comment by wm4** [comment]
Yes. You can put "Closes #4536" into the commit message next time.
