### ISSUE TITLE
Option to automatically play YouTube related video ("Up next" or "Autoplay")

### ISSUE THREAD

**Issue by Lesik** [mpv-player/mpv#4538]
Hey,

mpv's YouTube support is already amazing.
However, one nifty feature that I really miss when not using YouTube's web UI is that it plays suggested videos, that is other songs by the same artist, or in the same genre. With this feature, one never has to select a new song to listen to, the algorithm selects a fitting one for you automatically. That way, I often find new artists on the internet that I did not know before, a pleasant side effect.

It would be amazing for mpv to support this. The related video could be scraped out of the HTML, and then added to the mpv playlist, for example.

**Comment by wiiaboo** [comment]
Ask Youtube-DL, but probably not. Use some Youtube-specific app if you want Youtube features.

**Comment by haasn** [comment]
While this would almost surely fit into the scope of youtube-dl, perhaps the simplest way you could accomplish this is with a user script that automatically appends the “recommended” video to the playlist.

**Comment by cvzi** [comment]
I changed one of the existing scripts to do this, here is the result: 
https://github.com/cvzi/mpv-youtube-upnext
It appends the top video "Up next" from the right side of the website to the playlist. It relies on the website HTML so time will tell if it's stable.

**Comment by Dudemanguy** [comment]
Seems like a script to do this exists now and certainly not a feature that belongs in mpv itself.
