### ISSUE TITLE
mpv refuses to load YT vids in playlists if ytdl.lua produces edl:// URLs

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#4541]
### mpv version and platform

mpv 0.25.0-197-gf001b47cb8 on Arch Linux x86_64

### Reproduction steps

`mpv --no-config -v <(printf "#EXTM3U\n%s\n" 'https://www.youtube.com/watch?v=wpD9BKRlfuw')`

### Expected behavior

mpv plays the sole video in the playlist

### Actual behavior

it doesn't

### Log file

just an excerpt since the URLs are huge and this should be easy to reproduce
<pre>
[timeline] Total duration: 228.252000
[timeline] Durations and offsets are non-authoritative.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (timeline segments)
[cplayer] Set property: stream-open-filename="edl://!mp4_dash,init=%604%https://r8---sn-4g57knle.googlevideo.com/{{ ... }},length=3.879;" -> 1
[cplayer] Set property: file-local-options/force-media-title="LIA - New World (Omega Force Mix x) Nightcore" -> 1
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[stream] 
[stream] Refusing to load potentially unsafe URL from a playlist.
[stream] Use --playlist=file or the --load-unsafe-playlists option to load it anyway.
[stream] 
[cplayer] Opening failed or was aborted: edl://!mp4_dash,init=%604%https://r8---sn-4g57knle.googlevideo.com/{{ ... }},length=3.879;
[cplayer] finished playback, loading failed (reason 4)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Some errors happened)
</pre>

**Comment by sfan5** [comment]
That makes it work, but that's not the point.
The playlist <b>I am</b> passing to mpv does not contain an unsafe URL, the unsafe URL is generated by an implementation detail so I would expect mpv (although technically correct) not to warn me about this.

**Comment by haasn** [comment]
How is mpv to know whether you typed the contents of the m3u manually or not? As far as mpv is seeing it, it's just an m3u, and m3us containing URLs are potentially dangerous.

**Comment by sfan5** [comment]
http(s) URLs in m3us are not generally considered dangerous by mpv, it works just fine with other videos.
Try e.g.: `mpv --no-config -v <(printf "#EXTM3U\n%s\n" 'https://www.youtube.com/watch?v=7upPDw232O8')`

**Comment by haasn** [comment]
That's because `https` is considered a safe protocol. The documentation of `--load-unsafe-playlists` says so.

**Comment by wiiaboo** [comment]
Can't reproduce this here, even without `--load-unsafe-playlists`.

**Comment by sfan5** [comment]
now works if you have the native DASH demuxer (86004909acf543d1f890b9debc763a67dcadc800)
