### ISSUE TITLE
ffmpeg - compiling nightly vs release 3.3.2

### ISSUE THREAD

**Issue by therealkitman** [mpv-player/mpv#4542]
Hi,

In compiling mpv 0.25.0-182-g856fb767f against a nightly release of ffmpeg (git master) the `./waf configure` step fails that it can't find libavcodec. The compiled nightly ffmpeg binary works ok.

If I compile using ffmpeg release 3.3.2 (with ffmpeg compiled the same way and locations as the nightly), mpv finds all the files, compiles and runs ok.

So my question is really, does mpv have issues with ffmpeg's nightly snapshots or should I always use ffmpeg's releases eg 3.2 or 3.3 etc?

Thanks,
Chris.

**Comment by lachs0r** [comment]
I guess 0.25.0 is getting a little too old… Will fix that soon.

Meanwhile, you could also just use mpv master.

**Comment by therealkitman** [comment]
I thought I was using master? I used git clone `https://github.com/mpv-player/mpv.git` to get the source.

**Comment by wiiaboo** [comment]
mpv should usually build with any relatively recent release and git master.

We need the build/config.log from you to check if this is a user issue or an actual issue in mpv.

**Comment by therealkitman** [comment]
Hi, not sure here. lachs0r says he will fix something but I was using master branch of mpv.
I will created a new test area and get git master of mpv again and the overnight snapshot of ffmpeg (not a release) and see if I can recreate the issue.

**Comment by wiiaboo** [comment]
The issue he said would fix is the lack of a new release, as he misread that you were trying to build from 0.25.

**Comment by lachs0r** [comment]
Yeah, sorry. I can’t reproduce your issue either. You didn’t say how you installed FFmpeg either, and you didn’t post `build/config.log`.

**Comment by therealkitman** [comment]
Ok, I have git cloned a new nightly build of ffmpeg and the master of mpv. I compiled them in a fresh location. Oddly mpv compiles ok. I can only assume that PERHAPS the older nightly of ffmpeg had an issue. Or I did something repeatly wrong in the original build but I am loathed to know what.

I think I might close this one until I get a repeatable issue next time. Sorry for the false flag.

Chris.

```
ffmpeg version N-86691-gc8853568b1 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.8 (SUSE Linux)
  configuration: --prefix=/home/chris/ffmpeg_build2 --pkg-config-flags=--static --extra-cflags=-I/home/chris/ffmpeg_build/include --extra-ldflags='-L/home/chris/ffmpeg_build/lib -L/home/chris/ffmpeg_build/lib64' --bindir=/home/chris/bin2 --enable-openssl --enable-static --disable-shared --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree
  libavutil      55. 67.100 / 55. 67.100
  libavcodec     57.100.103 / 57.100.103
  libavformat    57. 75.100 / 57. 75.100
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 94.100 /  6. 94.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

```
chris@linux-c4x2:~/bin2> ./mpv 
Passing multiple arguments to ofopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing multiple arguments to ofopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
mpv 0.25.0-301-g41b3b11669 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon Jul  3 14:22:19 AWST 2017
ffmpeg library versions:
   libavutil       55.67.100
   libavcodec      57.100.103
   libavformat     57.75.100
   libswscale      4.7.101
   libavfilter     6.94.100
   libswresample   2.8.100
ffmpeg version: N-86691-gc8853568b1

```
