### ISSUE TITLE
"stay on top" option not working on wayland ?? only for me ??

### ISSUE THREAD

**Issue by narutowindy** [mpv-player/mpv#4543]
### mpv version and platform
 mpv 0.25.0 ,Arch 64bit official repo

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wm4** [comment]
Wayland doesn't provide anything that would allow an application to do this, thus it's not implemented. Maybe using the mpv X11 backend helps.
