### ISSUE TITLE
Choppy playback with Videotoolbox decoding

### ISSUE THREAD

**Issue by macdavis** [mpv-player/mpv#4544]
### mpv version and platform
mpv git f8cc184
MacOS 10.12.5 (16F73)

### Reproduction steps
Play the attached video with `-no-config -hwdec=videotoolbox`

### Actual behavior
![mpv-shot0001](https://user-images.githubusercontent.com/7761079/27507140-964612b8-590c-11e7-9500-b3621f89e94c.jpg)

### Log file
[videotoolbox_error.log](http://sprunge.us/gBNE)

### Sample files
[sample.m2ts](https://0x0.st/UmY.m2ts)

**Comment by wm4** [comment]
Most likely either a ffmpeg or apple issue.

**Comment by wm4** [comment]
Also, the sample link is 404.

**Comment by macdavis** [comment]
@wm4 Thanks for reminding. The sample link should be working now.

**Comment by wm4** [comment]
The sample works on Linux with hw decoding without problems, so the file is probably fine.

**Comment by Cpuroast** [comment]
File plays fine on macOS using software decoding, but I can confirm I experience the same issue with hardware decoding on Intel HD4000 or GT650M, Apple issue.

**Comment by macdavis** [comment]
@Cpuroast @wm4 
I converted to m4v with `ffmpeg -i /UmY.m4v -vcodec copy -acodec copy output.m4v `. This m4v can be correctly decoded.

**Comment by macdavis** [comment]
@Cpuroast @wm4 
I converted to m4v with `ffmpeg -i /UmY.m2ts -vcodec copy -acodec copy output.m4v`. This m4v can be correctly decoded.

**Comment by downthomas** [comment]
It looks like it is a videotoolbox issue with MBAFF in Mpeg2video:
[https://trac.ffmpeg.org/ticket/5272](https://trac.ffmpeg.org/ticket/5272)
