### ISSUE TITLE
audio-channels=downmix results in mono 1ch

### ISSUE THREAD

**Issue by macdavis** [mpv-player/mpv#4545]
### mpv version and platform
mpv git f8cc184
MacOS 10.12.5 (16F73)
### Reproduction steps
Play the sample file with `-no-config -ad-lavc-downmix=yes -audio-channels=downmix `
### Expected behavior
The log should say `AO: [coreaudio] 48000Hz stereo 2ch floatp`
### Actual behavior
`AO: [coreaudio] 48000Hz mono 1ch floatp`
However, the actual sound you listen to seems to be stereo.

> [i][cplayer]  (+) Audio --aid=1 (ac3 6ch 48000Hz)
[v][ad] Codec list:
[v][ad]     ac3 - ATSC A/52A (AC-3)
[v][ad]     ac3_fixed (ac3) - ATSC A/52A (AC-3)
[v][ad]     ac3_at (ac3) - ac3 (AudioToolbox)
[v][ad] Opening audio decoder ac3
[v][ad] Requesting 1 threads for decoding.
[v][ad] Selected audio codec: ac3 (ATSC A/52A (AC-3))
[v][cplayer] Starting playback...
[v][af] Adding filter lavrresample 
[v][lavrresample] Remix: 5.1(side) -> downmix
[v][af] Audio filter chain:
[v][af]   [in] 48000Hz 5.1(side) 6ch floatp
[v][af]   [lavrresample] 48000Hz downmix 2ch floatp [a]
[v][af]   [out] 48000Hz downmix 2ch floatp
[v][af]   [ao] 48000Hz downmix 2ch floatp
[v][ao] Trying audio driver 'coreaudio'
[v][ao/coreaudio] requested format: 48000 Hz, downmix channels, floatp
[v][ao/coreaudio] selected audio output device: Built-in Output (46)
[v][ao/coreaudio] input channel layout:
[v][ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[v][ao/coreaudio]  - description 0: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[v][ao/coreaudio]  - description 1: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[v][ao/coreaudio] mp chmap: unknown2
[v][ao/coreaudio] input channel layout:
[v][ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[v][ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[v][ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[v][ao/coreaudio] mp chmap: stereo
[v][ao/coreaudio] Channel layouts:
[v][ao/coreaudio]  - stereo
[v][ao/coreaudio]  - mono
[v][ao/coreaudio] result: mono
[v][ao/coreaudio] Latency property cntl: 399 frames
[v][ao/coreaudio] Latency property zisf: 512 frames
[v][ao/coreaudio] Latency property tfas: 93 frames
[v][ao/coreaudio] audiounit latency [us]: 354
[v][ao/coreaudio] device latency [us]: 20916
[v][ao/coreaudio] using soft-buffer of 9600 samples.
[i][cplayer] AO: [coreaudio] 48000Hz mono 1ch floatp
[v][cplayer] AO: Description: CoreAudio AudioUnit
[v][af] Removing filter lavrresample 
[v][af] Adding filter lavrresample 
[v][lavrresample] Remix: 5.1(side) -> mono
[v][af] Audio filter chain:
[v][af]   [in] 48000Hz 5.1(side) 6ch floatp
[v][af]   [lavrresample] 48000Hz mono 1ch floatp [a]
[v][af]   [out] 48000Hz mono 1ch floatp
[v][af]   [ao] 48000Hz mono 1ch floatp
[v][cplayer] starting audio playback
### Log file
[downmix.log](http://sprunge.us/fUYc)

### Sample files
[surround_test.ac3](https://0x0.st/Um0.ac3)

**Comment by wm4** [comment]
I assume there's no real reason why you picked "downmix".
