### ISSUE TITLE
seeking causes other pulseaudio clients to playback faster

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#4546]
[relevant pulseaudio bug report](https://bugs.freedesktop.org/show_bug.cgi?id=98906)

### mpv version and platform

```
mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon May  8 20:03:32 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.2
```

### Reproduction steps

This bug only occurs when I configure pulseaudio to remap my outputs, here are the relevant parts:
`~/.config/pulse/daemon.conf`:
```
default-sample-channels = 4
default-channel-map = front-left,front-right,rear-left,rear-right
```
`~/.config/pulse/default.pa`:
```
load-module module-remap-sink sink_name=speakers remix=no master=alsa_output.pci-0000_00_1f.3.analog-surround-40 channels=2 master_channel_map=rear-left,rear-right channel_map=front-left,front-right
load-module module-remap-sink sink_name=headphones remix=no master=alsa_output.pci-0000_00_1f.3.analog-surround-40 channels=2 master_channel_map=front-left,front-right channel_map=front-left,front-right
```

Whenever seeking in mpv (e.g. by simply holding \<right\>), all other pulse clients (including other mpv instances) on the same output (headphones or speakers) start playing back faster by about 1.5x

Note that this bug only occurs when the seeking mpv instance plays video files, audio-only files do not cause this.

I've tested whether seeking in other programs (firefox, vlc, cmus, ffplay) affected pulse clients in the same manner and they do not.

### Log file

[seeking mpv instance](http://sprunge.us/UTTK)

[faster playback mpv instance](http://sprunge.us/eEHi)

**Comment by wm4** [comment]
This is clearly a pulseaudio bug?
