### ISSUE TITLE
af=drc=1 removed from v0.25, what is the alternative option?

### ISSUE THREAD

**Issue by andysendo** [mpv-player/mpv#4547]
af=drc=1 in mpv.conf makes playing movies actors talking sounds bigger.
v0.25 seems not support drc anymore, enable it cause no drc filter erros, and no sound output, disable drc playing movies actors talking sound small.

so what is the alternative option in mpv.conf?

**Comment by CounterPillow** [comment]
From interface-changes.rst:

>   - --af=drc is gone (you can use e.g. lavfi/acompressor instead)

**Comment by sda89ha9** [comment]
af=lavfi=[acompressor=3]
or
af=lavfi=dynaudnorm

https://ffmpeg.org/ffmpeg-filters.html#acompressor
https://ffmpeg.org/ffmpeg-filters.html#dynaudnorm

**Comment by andysendo** [comment]
af=lavfi=[acompressor=3]  works,  af=lavfi=dynaudnorm does not.
could configure input.conf about increase/decrease acompressor value?

**Comment by sda89ha9** [comment]
there is this, https://github.com/medhefgo/mpv-acompressor

**Comment by andysendo** [comment]
i've read https://github.com/medhefgo/mpv-acompressor, default keybind F1~F4 not working, try to configure as 'F1 set acompressor update-param ratio 1.0' failed, so i give up.

anyway the main question is resolved, thank guys.
