### ISSUE TITLE
How to create two mpv players on Android

### ISSUE THREAD

**Issue by wtiandong** [mpv-player/mpv#4548]
Hi all,
We are working on play two different videos side by side at the same time on Android. How ever, on Android, there can only be two GLSurfaceView. Could someone give us some suggestions? 

Thanks!
BR

**Comment by wm4** [comment]
Well, you could render to a FBO. Which will probably be slow. In the future, there might be support to render to a sub-rectangle of a framebuffer as well, but it's not here yet.

**Comment by wtiandong** [comment]
hi all，
we solve this problem. We use Android TextureView to render video. Android allow multiple texture views
