### ISSUE TITLE
mpv0.25 vaapi hardware decoding by intel-g45-h264 driver don't work

### ISSUE THREAD

**Issue by andysendo** [mpv-player/mpv#4549]
mpv0.23 vaapi hardware decoding by intel-g45-h264 driver works, with some warn info. such as:

libva info: va_openDriver() returns 0
[ffmpeg/video] h264: Using deprecated struct vaapi_context in decode.

but still hardware decodiing, cpu load is low.

mpv0.25 vaapi hardware decoding do not work anymore, with error info:
libva info: va_openDriver() returns 0
[ffmpeg/video] h264: Hardware does not offer any usable surface formats.

i compile mpv with the same ffmpeg / libav release, so maybe mpv0.25 made some change? how to fixed?

**Comment by andysendo** [comment]
just Closed? means no need to fix?

**Comment by CounterPillow** [comment]
it was closed because you ignored the issue template.

**Comment by andysendo** [comment]
what was that? where is it?
