### ISSUE TITLE
--show-profile enc-<whatever> or newer show-profile=enc<whatever> doesn't return results

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#4551]
### mpv version and platform
mpv 0.25.0-7bfeb8b Ubuntu/Debian

### Reproduction steps
Run (for reporting version but latest should show same with new command)
mpv --show-profile enc-to-hp-slate-7 
### Expected behavior
returns profile details
### Actual behavior
returns Unknown profile 'enc-to-hp-slate-7'.
### Log file
https://0x0.st/U4V.log
If I add -o - to end of command then profile info is returned as in this log,
https://0x0.st/U4W.log

Seems to not look for encoding-profiles.conf unless -o - is specified somewhere in command
(- whether in /etc/mpv or ~/.config/mpv

**Comment by wiiaboo** [comment]
Yes, because encoding profiles are hidden unless you use -o.

**Comment by mc4man** [comment]
Ok, what brought this to mind was the latest commit, i.e.
 You can view the exact options a profile sets by
-#   mpv -show-profile enc-to-hp-slate-7
+#   mpv --show-profile=enc-to-hp-slate-7

**Comment by wm4** [comment]
It used to work, especially with `-o -`, but this actually got broken.
