### ISSUE TITLE
ao pulse failed.

### ISSUE THREAD

**Issue by zhangn1985** [mpv-player/mpv#4552]
### mpv version and platform

mpv 0.25.0-236-gd8ad8ae01 (C) 2000-2017 mpv/MPlayer/mplayer2 projects

debian 9

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

play any video/audio with ao=pulse

### Expected behavior

play normal

### Actual behavior

Assertion 'value' failed at pulse/proplist.c:81, function pa_proplist_sets(). Aborting.

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

[output.txt](https://github.com/mpv-player/mpv/files/1101402/output.txt)

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

NOTE: play with ao=alsa works fine.

**Comment by wm4** [comment]
That sounds like an internal error, so please report this to pulseaudio.

**Comment by zhangn1985** [comment]
if I reset to 7b84a3b04e01a25400ebef98cab6de5141dfee33 , mpv works fine with ao=pulse.

**Comment by zhangn1985** [comment]
72ef74dab5244753c9bc6f33687aa60a2886c53b  good
037c37519b305bb5d5ea0379122d62ba356cc103 bad

**Comment by zhangn1985** [comment]
it very strange, it require rebuild ao_pulse.c , after rebuild this file, the issue is gone..

**Comment by zhangn1985** [comment]
i think this maybe:

add    ` int period_size; ` before `char *client_name;` in `struct ao`

and ao_pulse.o is not recompiled, and  `struct ao` is still old.

when mpv is running, ao_pulse.o will convert new  `struct ao` to old, leads to  `char *client_name;` NULL pointer, and `pa_proplist_sets()` assert failed @ https://github.com/mpv-player/mpv/blob/master/audio/out/ao_pulse.c#L428

question here is why `waf` not re-compile ao_pulse.c when it dependence internal.h is changed?

**Comment by wm4** [comment]
Normally waf does this, and I've never seen it not do that.

**Comment by zhangn1985** [comment]
```
zhangn1985@zhang-debian:~/source/mpv$ git reset 72ef74dab5244753c9bc6f33687aa60a2886c53b --hard
HEAD 现在位于 72ef74dab encoding-profiles: remove useless noformat vf from enc-v-h264
zhangn1985@zhang-debian:~/source/mpv$ ./waf
Waf: Entering directory `/home/zhangn1985/source/mpv/build'
[  1/224] Compiling version.sh
[ 36/224] Compiling audio/out/ao.c
[ 37/224] Compiling audio/out/ao_alsa.c
[ 39/224] Compiling audio/out/ao_jack.c
[171/224] Compiling audio/out/ao_lavc.c
[217/224] Compiling audio/out/ao_null.c
[218/224] Compiling audio/out/ao_oss.c
[219/224] Compiling audio/out/ao_pcm.c
[220/224] Compiling audio/out/pull.c
[221/224] Compiling audio/out/push.c
[222/224] Compiling common/version.c
[223/224] Compiling options/options.c
[224/224] Linking build/mpv
Waf: Leaving directory `/home/zhangn1985/source/mpv/build'
'build' finished successfully (3.606s)
zhangn1985@zhang-debian:~/source/mpv$ git pull
更新 72ef74dab..d8ad8ae01
Fast-forward
 DOCS/interface-changes.rst |  2 +-
 audio/out/ao.c             |  7 +++++++
 audio/out/ao_alsa.c        |  1 +
 audio/out/ao_lavc.c        |  4 +++-
 audio/out/ao_null.c        |  2 ++
 audio/out/ao_openal.c      |  1 +
 audio/out/ao_oss.c         |  3 ++-
 audio/out/ao_sndio.c       |  2 ++
 audio/out/internal.h       |  8 ++++++++
 audio/out/push.c           | 15 +++++++++++++--
 etc/encoding-profiles.conf | 10 +++++-----
 options/options.c          |  2 +-
 12 files changed, 46 insertions(+), 11 deletions(-)
zhangn1985@zhang-debian:~/source/mpv$ ./waf
Waf: Entering directory `/home/zhangn1985/source/mpv/build'
[  1/224] Compiling version.sh
[ 36/224] Compiling audio/out/ao.c
[ 37/224] Compiling audio/out/ao_alsa.c
[ 39/224] Compiling audio/out/ao_jack.c
[139/224] Compiling audio/out/ao_lavc.c
[217/224] Compiling audio/out/ao_null.c
[218/224] Compiling audio/out/ao_oss.c
[219/224] Compiling audio/out/ao_pcm.c
[220/224] Compiling audio/out/pull.c
[221/224] Compiling audio/out/push.c
[222/224] Compiling common/version.c
[223/224] Compiling options/options.c
[224/224] Linking build/mpv
Waf: Leaving directory `/home/zhangn1985/source/mpv/build'
'build' finished successfully (3.631s)
zhangn1985@zhang-debian:~/source/mpv$ 
```

ao_pulse is not rebuilt..

**Comment by wm4** [comment]
Very odd... `ao_pulse.c` simply does `#include "internal.h"`, like all other AOs.
