### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#4553]
### mpv version and platform
mpv-build , latest, debian wheezy i386, lenovo laptop t400
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
git mpv-build
cd mpv-build
./update
./clean
./build -j2
sudo ./build install

### Expected behavior
build fine

### Actual behavior
Using mpv options:
Setting top to                           : /home/rich/Programme/mpv-build/mpv 
Setting out to                           : /home/rich/Programme/mpv-build/mpv/build 
Checking for waf version in 1.8.4-2.0.0  : ok 
Checking for program 'cc'                : /usr/bin/cc 
Checking for program 'pkg-config'        : /usr/bin/pkg-config 
Checking for program 'ar'                : /usr/bin/ar 
Checking for program 'rst2html'          : not found 
Checking for program 'rst2man'           : not found 
Checking for program 'rst2pdf'           : not found 
Checking for program 'windres'           : not found 
Checking for program 'perl'              : /usr/bin/perl 
Checking for 'gcc' (C compiler)          : /usr/bin/cc 
Detected target OS:                      : os-linux 
Checking for compiler flags -Werror=implicit-function-declaration : yes 
Checking for compiler flags -Wno-error=deprecated-declarations    : yes 
Checking for compiler flags -Wno-error=unused-function            : yes 
Checking for compiler flags -Wempty-body                          : yes 
Checking for compiler flags -Wdisabled-optimization               : yes 
Checking for compiler flags -Wstrict-prototypes                   : yes 
Checking for compiler flags -Wno-format-zero-length               : yes 
Checking for compiler flags -Werror=format-security               : yes 
Checking for compiler flags -Wno-redundant-decls                  : yes 
Checking for mpv CLI player                                       : yes 
Checking for shared library                                       : disabled 
Checking for static library                                       : disabled 
Checking for static build                                         : disabled 
Checking for whether to include binary compile time               : yes 
Checking for whether to optimize                                  : yes 
Checking for whether to compile-in debugging information          : yes 
Checking for manpage generation                                   : no (missing RST2MAN) 
Checking for html manual generation                               : disabled 
Checking for pdf manual generation                                : disabled 
Checking for dynamic loader                                       : yes 
Checking for C plugins                                            : yes 
Checking for dlopen                                               : yes 
Checking for zsh completion                                       : disabled 
Checking for inline assembly (currently without effect)           : yes 
Checking for test suite (using cmocka)                            : disabled 
Checking for generate a clang compilation database                : disabled 
Checking for compiler support for noexecstack                     : yes 
Checking for linker support for --nxcompat --no-seh --dynamicbase : no 
Checking for -lm                                                  : yes 
Checking for MinGW                                                : os-win32 not found 
Checking for POSIX environment                                    : yes 
Checking for development environment                              : yes 
Checking for win32                                                : not found any of os-win32, os-cygwin 
Checking for internal pthread wrapper for win32 (Vista+)          : win32 not found 
Checking for POSIX threads                                        : yes 
Checking for GNU C extensions                                     : yes 
Checking for stdatomic.h                                          : no 
Checking for stdatomic.h support or slow emulation                : yes 
Checking for linking with -lrt                                    : yes 
Checking for iconv                                                : yes 
Checking for w32/dos paths                                        : not found any of os-win32, os-cygwin 
Checking for termios                                              : yes 
Checking for shm                                                  : yes 
Checking for nanosleep                                            : yes 
Checking for POSIX spawnp()/kill()                                : yes 
Checking for posix_spawnp() or MinGW                              : yes 
Checking for glob()                                               : yes 
Checking for glob() win32 replacement                             : not found any of os-win32, os-cygwin 
Checking for fchmod()                                             : yes 
Checking for vt.h                                                 : yes 
Checking for gbm.h                                                : no 
Checking for GLIBC API for setting thread name                    : yes 
Checking for OSX API for setting thread name                      : glibc-thread-name found 
Checking for BSD API for setting thread name                      : glibc-thread-name found 
Checking for BSD's fstatfs()                                      : no 
Checking for Linux's fstatfs()                                    : yes 
Checking for Samba support (makes mpv GPLv3)                      : disabled 
Checking for Lua                                                  : no ('luajit >= 2.0.0' not found) 
Checking for Javascript (MuJS backend)                            : no ('mujs >= 1.0.0' not found) 
Checking for SSA/ASS support                                      : yes 
Checking for libass OSD support                                   : yes 
Checking for dummy OSD support                                    : libass-osd found 
Checking for zlib                                                 : yes 
Checking for Encoding                                             : yes 
Checking for Bluray support                                       : no ('libbluray >= 0.3.0' not found) 
Checking for dvdread support                                      : disabled 
Checking for dvdnav support                                       : disabled 
Checking for DVD/IFO support                                      : not found any of dvdnav, dvdread 
Checking for cdda support (libcdio)                               : disabled 
Checking for uchardet support                                     : no ('uchardet' not found) 
Checking for librubberband support                                : no ('rubberband >= 1.8.0' not found) 
Checking for LCMS2 support                                        : no ('lcms2 >= 2.6' not found) 
Checking for VapourSynth filter bridge (Python)                   : no ('vapoursynth >= 24 vapoursynth-script >= 23' not found) 
Checking for VapourSynth filter bridge (Lazy Lua)                 : lua not found 
Checking for VapourSynth filter bridge (core)                     : not found any of vapoursynth-lazy, vapoursynth 
Checking for libarchive wrapper for reading zip files and more    : disabled 
Checking for SDL2                                                 : disabled 
Checking for SDL (1.x)                                            : disabled 
Checking for OSS                                                  : yes 
Checking for RSound audio output                                  : no 
Checking for sndio audio input/output                             : disabled 
Checking for PulseAudio audio output                              : yes 
Checking for JACK audio output                                    : no ('jack' not found) 
Checking for OpenAL audio output                                  : disabled 
Checking for OpenSL ES audio output                               : no 
Checking for ALSA audio output                                    : yes 
Checking for CoreAudio audio output                               : no 
Checking for AudioUnit output for iOS                             : no 
Checking for WASAPI audio output                                  : win32 not found 
Checking for Cocoa                                                : no 
Checking for DRM                                                  : yes 
Checking for GBM                                                  : gbm.h not found 
Checking for Wayland                                              : no ('wayland-client >= 1.6.0 wayland-cursor >= 1.6.0 xkbcommon >= 0.3.0' not found) 
Checking for X11                                                  : yes 
Checking for Xv video output                                      : yes 
Checking for OpenGL Cocoa Backend                                 : cocoa not found 
Checking for OpenGL X11 Backend                                   : yes 
Checking for OpenGL X11 EGL Backend                               : yes 
Checking for OpenGL DRM EGL Backend                               : gbm not found 
Checking for OpenGL Wayland Backend                               : wayland not found 
Checking for OpenGL Win32 Backend                                 : win32 not found 
Checking for OpenGL/DirectX Interop Backend                       : gl-win32 not found 
Checking for OpenGL Win32 ANGLE Backend                           : not found any of os-win32, os-cygwin 
Checking for OpenGL Win32 ANGLE Library                           : egl-angle not found 
Checking for VDPAU acceleration                                   : yes 
Checking for VDPAU with OpenGL/X11                                : yes 
Checking for VAAPI acceleration                                   : no ('libva >= 0.36.0' not found) 
Checking for VAAPI (X11 support)                                  : vaapi not found 
Checking for VAAPI (Wayland support)                              : gl-wayland, vaapi not found 
Checking for VAAPI (DRM/EGL support)                              : vaapi, egl-drm not found 
Checking for VAAPI GLX                                            : vaapi-x11 not found 
Checking for VAAPI EGL on X11                                     : vaapi-x11 not found 
Checking for VAAPI EGL                                            : not found any of vaapi-wayland, vaapi-x-egl 
Checking for CACA                                                 : yes 
Checking for JPEG support                                         : yes 
Checking for Direct3D support                                     : win32 not found 
Checking for Android support                                      : no 
Checking for Raspberry Pi support                                 : no ('bcm_host' not found) 
Checking for iOS OpenGL ES hardware decoding interop support      : no 
Checking for OpenGL without platform-specific code (e.g. for libmpv) : not found any of libmpv-shared, libmpv-static 
Checking for MALI via Linux fbdev                                    : no 
Checking for OpenGL video outputs                                    : yes 
Checking for EGL helper functions                                    : yes 
Checking for FFmpeg/Libav present                                    : yes 
Checking for libav* is FFmpeg                                        : yes 
Checking for libav* is Libav                                         : no 
Checking for Libav/FFmpeg library versions                           : yes 
Checking for libavdevice                                             : yes 
Checking for libavutil GPU memcpy for hardware decoding              : yes 
Checking for libavutil content light level struct                    : yes 
Checking for libavcodec VAAPI hwaccel (FFmpeg 3.3 API)               : vaapi not found 
Checking for libavcodec videotoolbox hwaccel (new API)               : gl-cocoa not found 
Checking for libavcodec videotoolbox hwaccel (old API)               : gl-cocoa not found 
Checking for libavcodec videotoolbox hwaccel                         : not found any of videotoolbox-hwaccel-old, videotoolbox-hwaccel-new 
Checking for Videotoolbox with OpenGL                                : videotoolbox-hwaccel, gl-cocoa not found 
Checking for libavcodec VDPAU hwaccel (FFmpeg 3.3 API)               : yes 
Checking for DXVA2 and D3D11VA hwaccel                               : win32 not found 
Checking for DXVA2 and D3D11VA hwaccel (new API)                     : no 
Checking for CUDA hwaccel                                            : yes 
Checking for GCC SSE4 intrinsics for GPU memcpy                      : not found any of d3d-hwaccel 
Checking for TV interface                                            : disabled 
Checking for videoio.h                                               : tv not found 
Checking for videodev2.h                                             : tv not found 
Checking for Video4Linux2 TV interface                               : not found any of sys_videoio_h, videodev 
Checking for libv4l2 support                                         : tv-v4l2 not found 
Checking for audio input support                                     : not found any of tv-v4l2 
Checking for DVB input module                                        : disabled 
Checking for w32 executable                                          : not found any of os-win32, os-cygwin 
Checking for Apple Remote support                                    : cocoa not found 
Checking for macOS Touch Bar support                                 : cocoa not found 
Writing configuration header:                                        : config.h 
'configure' finished successfully (10.511s)
Waf: Entering directory `/home/rich/Programme/mpv-build/mpv/build'
[  1/218] Compiling version.sh
[218/218] Linking build/mpv
/home/rich/Programme/mpv-build/build_libs/lib/libavcodec.a(crystalhd.o): In function `flush':
crystalhd.c:(.text+0x21): undefined reference to `DtsFlushInput'
/home/rich/Programme/mpv-build/build_libs/lib/libavcodec.a(crystalhd.o): In function `receive_frame':
crystalhd.c:(.text+0x96): undefined reference to `DtsProcOutputNoCopy'
crystalhd.c:(.text+0x411): undefined reference to `DtsGetDriverStatus'
crystalhd.c:(.text+0x68d): undefined reference to `DtsReleaseOutputBuffs'
/home/rich/Programme/mpv-build/build_libs/lib/libavcodec.a(crystalhd.o): In function `crystalhd_receive_frame':
crystalhd.c:(.text+0xba3): undefined reference to `DtsTxFreeSize'
crystalhd.c:(.text+0xcc0): undefined reference to `DtsProcInput'
crystalhd.c:(.text+0xd0a): undefined reference to `DtsGetDriverStatus'
/home/rich/Programme/mpv-build/build_libs/lib/libavcodec.a(crystalhd.o): In function `uninit':
crystalhd.c:(.text.unlikely+0x13): undefined reference to `DtsStopDecoder'
crystalhd.c:(.text.unlikely+0x1b): undefined reference to `DtsCloseDecoder'
crystalhd.c:(.text.unlikely+0x23): undefined reference to `DtsDeviceClose'
/home/rich/Programme/mpv-build/build_libs/lib/libavcodec.a(crystalhd.o): In function `init':
crystalhd.c:(.text.unlikely+0x150): undefined reference to `DtsDeviceOpen'
crystalhd.c:(.text.unlikely+0x184): undefined reference to `DtsCrystalHDVersion'
crystalhd.c:(.text.unlikely+0x1ec): undefined reference to `DtsSetInputFormat'
crystalhd.c:(.text.unlikely+0x220): undefined reference to `DtsOpenDecoder'
crystalhd.c:(.text.unlikely+0x254): undefined reference to `DtsSetColorSpace'
crystalhd.c:(.text.unlikely+0x27d): undefined reference to `DtsStartDecoder'
crystalhd.c:(.text.unlikely+0x2a6): undefined reference to `DtsStartCapture'
/home/rich/Programme/mpv-build/build_libs/lib/libavformat.a(matroskadec.o): In function `matroska_decode_buffer.isra.10':
matroskadec.c:(.text+0xc4c): undefined reference to `BZ2_bzDecompressInit'
matroskadec.c:(.text+0xc9b): undefined reference to `BZ2_bzDecompress'
matroskadec.c:(.text+0xcb9): undefined reference to `BZ2_bzDecompressEnd'
matroskadec.c:(.text+0xefa): undefined reference to `BZ2_bzDecompressEnd'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/rich/Programme/mpv-build/mpv/build'
Build failed

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wm4** [comment]
I don't know, but it's a ffmpeg error, so report it to ffmpeg.
