### ISSUE TITLE
The video is playing. How do I load the subtitle file?

### ISSUE THREAD

**Issue by zyb920** [mpv-player/mpv#4557]
The video is playing. 
How do I load the subtitle file?

**Comment by lachs0r** [comment]
1) Use `--sub-file`
2) Drag and drop subtitles to the video window
3) Use the same name for the subtitle file as for the video file
4) Use `--sub-auto=fuzzy` or `--sub-auto=all`

Also, this is not a support forum and you have ignored the issue template. I’ll let it slide though.
