### ISSUE TITLE
use libmpv,  --sub-file faild

### ISSUE THREAD

**Issue by zyb920** [mpv-player/mpv#4558]
use libmpv,

For example, I'm play  AAA.mp4 file, 
const char *args[] = {"loadfile", "D:/video/AAA.mp4", NULL};
mpv_command_async(mpv, 0, args);

playing more minutes, 

and then loading b.srt subtitle file.
mpv_set_option_string(mpv, "sub-file", "E:/subtitle/b.srt"); Caption display failed。

But the 2 API together will be successful..........

**Comment by zyb920** [comment]
mpv_set_option_string(mpv, "sub-file", "E:/subtitle/b.srt"); Caption display failed。

**Comment by wm4** [comment]
You need to set the `sub-file` option before the `loadfile` command, or as part of it, or use the `sub-add` command to load it during playback.
