### ISSUE TITLE
h264 decoding error

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#4559]
### mpv version and platform
7b84a3b04e - Win10-x64

### Reproduction steps
Play video normally

### Expected behavior
Ugly green blocking. Purely decoding the file in ffmpeg also throw same errors. For some reason, VLC can play it fine. FFMS2 can decode it properly.

### Actual behavior
Play video normally

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/1110903/log.txt)

### Sample files
https://0x0.st/0rJ.mkv

**Comment by wiiaboo** [comment]
```
λ mpv --no-config https://0x0.st/0rJ.mkv
Playing: https://0x0.st/0rJ.mkv
[mkv] SeekHead position beyond end of file - incomplete file?
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (opus 2ch 48000Hz)
AO: [wasapi] 48000Hz stereo 2ch float
[ffmpeg/video] h264: SEI type 5 size 7112 truncated at 136
VO: [opengl] 1920x1080 yuv444p10
AV: 00:00:00 / 00:23:41 (0%) A-V:  0.000 Cache: 10s+3MB
[ffmpeg/video] h264: top block unavailable for requested intra mode -1
[ffmpeg/video] h264: error while decoding MB 2 0, bytestream 248848
AV: 00:00:00 / 00:23:41 (0%) A-V:  0.000 Cache: 10s+3MB
[ffmpeg/video] h264: top block unavailable for requested intra mode -1
[ffmpeg/video] h264: error while decoding MB 34 0, bytestream 37317
AV: 00:00:00 / 00:23:41 (0%) A-V:  0.000 Cache: 10s+3MB
[ffmpeg/video] h264: Reference 3 >= 3
[ffmpeg/video] h264: error while decoding MB 72 1, bytestream 46043
[ffmpeg/video] h264: Cannot use next picture in error concealment
(Paused) AV: 00:00:01 / 00:23:41 (0%) A-V:  0.000 Cache: 10s+2MB
```
![img](https://i.fsbn.eu/99gf.png)

Seems to play fine in MPC-HC with latest LAVFilters release.

**Comment by wiiaboo** [comment]
Seems to be a regression in FFmpeg since at least 718f8a01dfa301b2d21eefcd61bdd1988953d0aa (commit used by LAVFilters 0.7 and tested with mpv as working).

**Comment by wm4** [comment]
Any chance you could bisect?

**Comment by wiiaboo** [comment]
Could take a few hours as I'll probably need to reconfigure in every step.

**Comment by wiiaboo** [comment]
```
15:16:49 nevcairiel@| if you have a file that was encoded with old x264, then strip its SEI and then complain that it doesnt decode right ... then your file is just broken :)
15:17:14 nevcairiel@| because old x264 produced broken files
15:17:40        BBB@| I was going to say, was this file generated with old x264 but not signaled as such?
```
Broken video encoded with older version of x264 but since SEI was stripped FFmpeg can't detect it. Either tell the authors to stop stripping the SEI or use a newer x264.

**Comment by bctvigil** [comment]
This was a regression introduced in ffmpeg with 840b41b2a643fc8f0617c0370125a19c02c6b586

**Comment by wm4** [comment]
There's a workaround for the playback resume failure with those files. All other cases can be handled with `--vd-lavc-assume-old-x264`.
