### ISSUE TITLE
mpv cannot support some online videos like which are in Google Drive to fast forward or backward

### ISSUE THREAD

**Issue by lioliy** [mpv-player/mpv#4561]
mpv cannot support some online videos like which are in Google Drive direct link (https://doc-0k-b8-docs.googleusercontent.com/balalalalalal) to fast forward or backward.

These files have a feature : I download the video in many browser it can't check the file size

![196EDF44-086B-4B50-B880-D6492587B927.png](https://ooo.0o0.ooo/2017/06/30/5956258220bdf.png)

In mpv,It will download full part of the file which I want to fast forward or backward.
So it will buffering long time ,I test the same video in vlc even mxplayer and there is no problem.
In the meantime, it will also says with a warning

> [mkv]  SeekHead position beyond end of file - incomplete file?

seeking is almost not working. I suspect that mpv is not correctly handling the cache for this type of media

I use the newest version of mpv.

Please fix this issue.

**Comment by wm4** [comment]
That's Google's fault not ours. They save the files without range support, so mpv can't seek. Their Google drive service is fucking terrible anyway.

You could force seeking and use a large cache in an attempt to work this around.

**Comment by Hrxn** [comment]
> Their Google drive service is fucking terrible anyway.

Uh... okay, what would you recommend instead?

**Comment by lioliy** [comment]
I try to set a large cache in mpv.But didnot work
How to force to seek in mpv?
Have anyway to solve the problem?
