### ISSUE TITLE
How to un-apply --opengl-shaders ?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4562]
Hi,

Is it possible to _un-apply_ (or clear?) custom user shaders (i.e. to pass something like `--opengl-shaders=no`) ?

Regards,
Alex

**Comment by wiiaboo** [comment]
Something to do this has just been committed: https://github.com/mpv-player/mpv/commit/91583fccac85880ad2199f50463c095560791d56
Use `--opengl-shader-clr`.

**Comment by fhlfibh** [comment]
Will try that, thanks!

**Comment by fhlfibh** [comment]
Nope, `opengl-shader-clr` doesn't work, for me, at least.

I have two profiles in `config` file:
```
[FHD profile]
hwdec=vdpau-copy
opengl-shader="~/.config/mpv/shaders/nnedi3-nns64-win8x4-chroma.hook"

[UHD profile]
hwdec=cuda
opengl-shader-clr
```
[My script](https://github.com/fhlfibh/height-profiles/blob/master/height-profiles.lua) loads one or another depending on video height.
If I play a FHD clip, and then a UHD clip -- mpv applies NNEDI shader for both.

**Comment by wm4** [comment]
It changes again. Now you need opengl-shaders-clr.

**Comment by fhlfibh** [comment]
@wm4 And `opengl-shaders=/...` to load shaders?

**Comment by wm4** [comment]
Probably best to use multiple `opengl-shader` options. `opengl-shaders` now requires separation by `:` or `;` (depending on OS) - not sure if that actually breaks backwards compat.
