### ISSUE TITLE
Seeking in flic files fails

### ISSUE THREAD

**Issue by DominusExult** [mpv-player/mpv#4564]
### mpv version and platform

OS X 10.12.5
MPV 0.25.0 

### Reproduction steps
- Open a flic file (*.flc)
- try to seek in the time line

### Expected behavior

- moving playback to the chosen time frame

### Actual behavior

- crash

### Log file

Unfortunately the prebuilt app seems to ignore the --logfile arg, probably due to the wrapper it uses in the app.

### Sample files

https://www.dropbox.com/s/tb599e6ebv17quc/01castle.flc.zip?dl=0

**Comment by wm4** [comment]
Can't reproduce.

**Comment by wm4** [comment]
(Although it's true that you can't even seek to the start of the file.)

**Comment by CounterPillow** [comment]
it doesn't crash for me, it just closes the player because

```
[lavf] Seek failed (Operation not permitted)
[lavf] seek done
[lavf] EOF reached.
```

**Comment by DominusExult** [comment]
Yes, sorry, ut wasn't clear to me whether it crashes or closes.
So, it closes the player when you try to seek

**Comment by CounterPillow** [comment]
The demuxer/decoder is apparently from 2003, and unless someone really feels like investing time into fixing a format extremely few people will ever feel the need to decode, I recommend just losslessly transcoding the files that you care about instead of trying to play them directly, e.g. with

```
ffmpeg -i 01castle.flc -c:v ffv1 castletranscode.mkv
```

which will give you a (lossless) ffv1-inside-mkv file.

**Comment by DominusExult** [comment]
I *can* view and seek with quicktime 7, I just noticed that seeking doesn't work with IINA and thus MPV and wanted to notify of this.
Transcoding is not an option because I need it in flic format for another project.

**Comment by richardpl** [comment]
Flic format is crap format, and it does not support seeking.

**Comment by DominusExult** [comment]
At least with Quicktime you *can* seek. The format is basically like gif. All still pictures and the header gives you the amount of pictures and at what speed those pictures should be played. http://steve.hollasch.net/cgindex/formats/fli.html
Seeking shouldn't be that difficult if you keep track of the frames.

Calling it crap doesn't help. It exists and in very very few circumstances people might have legit reasons to use it.

In this case it might be best to either cut support alltogether or NOT allow seeking or handle the failure of seeking more gracefully.

**Comment by richardpl** [comment]
Why would I keep track of frames, non-crap formats do not need to keep track of frames.

**Comment by haasn** [comment]
@DominusExult mpv outsources seeking to FFmpeg. Seems like the right place to ask for support for this format would be there.

**Comment by wm4** [comment]
Except that @richardpl is a stuck up ffmpeg developer who adds support for "crap" formats all the time.

**Comment by DominusExult** [comment]
It's an ancient animation format. Awesome for its time and still very simple.

I don't know if I have more desire for crapalicous comments. I just wanted to report that there is something wrong in seeking flics is handled. I couldn't care less about discussing whether the format is crap or not.

**Comment by wiiaboo** [comment]
Either way, it's a FFmpeg issue, so discussing it here doesn't really do much.

**Comment by richardpl** [comment]
Posted patch to fix this.

**Comment by Hrxn** [comment]
When will it be merged?

**Comment by richardpl** [comment]
In couple of days max, then wait for couple of days for nightly build of mpv to get it.
