### ISSUE TITLE
Delay while using a somagic device

### ISSUE THREAD

**Issue by Astreos** [mpv-player/mpv#4565]
Hello !

I want to display the video stream from a somagic USB device in mpv, but there is about 1s of delay. However, everything is okay when I use mplayer...

### mpv version and platform
mpv 0.23.0 on Fedora 25

### Reproduction steps
--> mpv command :
somagic-capture | mpv --demuxer=rawvideo --demuxer-rawvideo-fps=25 --demuxer-rawvideo-w=720 --demuxer-rawvideo-h=576 --demuxer-rawvideo-mp-format=uyvy422 -
--> mplayer command :
somagic-capture | mplayer -demuxer rawvideo -rawvideo "pal:format=uyvy:fps=25" -vf yadif -vo gl -

### Expected behavior
mpv should display the somagic stream without delay.

### Actual behavior
mpv displays the somagic stream with about 1s of delay.

### Log file
https://gist.github.com/Astreos/c71277dc6d737bbd2780dca81bd6aa03

Thank you in advance for all your work, and for the help you will provide !

Best regards,
Astreos

**Comment by wm4** [comment]
You can try --cache=no --demuxer-thread=no

**Comment by Astreos** [comment]
Hi !

Thank you for your fast answer, it is working much better now ! Maybe I still have some delay in comparison to mplayer, but it is not significant, so I'll keep testing...

Best regards,
Astreos
