### ISSUE TITLE
MPV play dolby, dts audio ect?

### ISSUE THREAD

**Issue by Obi-Shinobi** [mpv-player/mpv#4567]
I have only the most basic MPV player and have zero code skill and can't figure out how to get my PC with MPV player to tell my receiver its in dolby, dts ect. Kodi can do it but kodi is way more than I want. I love how lite MPV is and the response is amazing.

sorry for the noob

**Comment by CounterPillow** [comment]
The `--audio-spdif` option can be used to specify for which codecs mpv should do passthrough, [see the manual for more information](https://mpv.io/manual/master/#options-audio-spdif).

Please note though that this is a bugtracker and not a support forum.

**Comment by Obi-Shinobi** [comment]
My bad, where can i find the support forum because none of that seems to work.

**Comment by CounterPillow** [comment]
there is none
