### ISSUE TITLE
[ao/also] "Audio device returned broken buffer state" error

### ISSUE THREAD

**Issue by c-14** [mpv-player/mpv#4568]
### mpv version and platform

mpv git master 41b3b116695bcad3fdb3129b133e2a97d9a76847
gentoo linux

### Reproduction steps
* play an audio file (any audio file should do, reproduced with various mp3 and flac files as well as dts)

### Expected behavior
* mpv plays the audio file correctly without printing errors to the console

### Actual behavior
* mpv prints "[e][ao/alsa] Audio device returned broken buffer state (sent 960 samples, got 480 samples, 480 period)!" but plays the file correctly

### Log file
http://sprunge.us/XTaZ

### Additional Information
This doesn't seem to occur when I use an audio device directly but only when I use a "route" device
relevant alsa config: http://sprunge.us/iNdM

I did try debugging on my own for a bit and I think the issue is in the value of data.samples in audio/out/push.c:ao_play_data initialized via mp_audio_buffer_peek because if I clamp the value using MPMIN(data.samples, ao->period_size); on line 304 I get rid of all the errors except for the first one where it returns 16 samples.

**Comment by lachs0r** [comment]
Looking at that config, this behavior is about what I’d expect. Both PCM’s you’re routing to probably use different buffer/period sizes. Make sure they’re the same.

**Comment by wm4** [comment]
That means snd_pcm_status_get_avail() return a certain buffer space, but snd_pcm_write*() isn't taking all the input. That is unexpected. This case will just stop working once I make more changes and don't allow the AO to partially reject data.

**Comment by c-14** [comment]
I've managed to get rid of the error by wrapping one of the slaves of the route in a dmix interface.
Is this the intended method of resolving the issue?
new portion of the asoundrc:
`pcm.pchmix {
	type dmix
	ipc_key 1024
	slave {
		pcm "pch"
		buffer_size 8192
	}
}
`

**Comment by wm4** [comment]
No. But we'll probably never find out whether this is a bug or not, because ALSA is a fucking mess and doesn't even have a bug tracker. I'll just keep breaking the users shit and advocate switching to Pulse as a counter measures.

**Comment by lachs0r** [comment]
I assume the multi PCM just runs the slaves with whatever buffer config they have by default, and the API then just reports something random to us. At least that sounds like something ALSA would do.

FWIW: You probably didn’t have to wrap it in dmix. Setting identical buffer/period sizes for both slaves should do the trick. Just guessing though.
