### ISSUE TITLE
CUDA decoding produces garbage lines

### ISSUE THREAD

**Issue by LaserEyess** [mpv-player/mpv#4571]
### mpv version and platform

OS: GNU/Linux 64bit
GPU: Nvidia GTX 960 
Driver Version: 381.22

mpv version
```
mpv --version
mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon May  8 20:03:32 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.2
```
ffmpeg version
```
ffmpeg -version
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
built with gcc 7.1.1 (GCC) 20170516
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-shared --enable-version3
libavutil      55. 58.100 / 55. 58.100
libavcodec     57. 89.100 / 57. 89.100
libavformat    57. 71.100 / 57. 71.100
libavdevice    57.  6.100 / 57.  6.100
libavfilter     6. 82.100 /  6. 82.100
libavresample   3.  5.  0 /  3.  5.  0
libswscale      4.  6.100 /  4.  6.100
libswresample   2.  7.100 /  2.  7.100
libpostproc    54.  5.100 / 54.  5.100
```

### Reproduction steps

play video with 
`mpv --no-config --hwdec=cuda` 

### Expected behavior

normal playback

### Actual behavior

garbage lines on the bottom of the screen, does not happen with SW decoding or VDPAU
![](https://0x0.st/0Oi.png)
### Log file
http://sprunge.us/jXbj

### Sample files

https://0x0.st/0Oz.mkv

This is the only video file I have experienced this with. My guess is either there's something wrong with the encoding settings making it not a 'clean' h264 file, or that ffmpeg is mishandling CUDA somehow. I don't understand why VDPAU would work but CUDA would not, so I don't really think it's drivers. But I know very little about writing drivers or decoders so I am probably wrong.

**Comment by mc4man** [comment]
Yeah, cuda here seems to produce a line at bottom with xxxx:534. 
xxxx:532 or xxxx:536 are ok, as is pretty much anything else., just xxxx:534. 
 Why?, no clue

**Comment by LaserEyess** [comment]
I vaguely remember some hardware decoders having issues with certain aspect ratios, but I can't find any information about it, and all I can find about CUDA decoding is that it supports h264 "up to 4096x4096" on my GPU.

**Comment by fhlfibh** [comment]
CUDA decoding is somehow buggy.
https://github.com/mpv-player/mpv/issues/4074

**Comment by heelsleeh** [comment]
same issue .here is my solution
video card: geforce 770
old ENV (with issue)
OS: Centos 7 x86_64
mpv:  mpv-0.27.0
ffmpeg: ffmpeg-3.4
nvidia driver: NVIDIA-Linux-x86_64-384.98.run
video-codec-sdk: Video_Codec_SDK_8.0.14.zip

current ENV( OK)
video card: geforce 770
OS: Centos 7 x86_64
mpv:  mpv-0.27.0
ffmpeg: ffmpeg-3.3.5
nvidia driver: NVIDIA-Linux-x86_64-375.66.run
video-codec-sdk: Video_Codec_SDK_7.1.9

mpv config with cuda works fine
mpv --hwdec=cuda --vo=opengl test.mp4

**Comment by wm4** [comment]
Try `--hwdec=nvdec` with git master.

**Comment by LaserEyess** [comment]
```
mpv 0.27.0-394-g871a8a316a (C) 2000-2017 mpv/MPlayer/mplayer2 projects                          
 built on Sat Nov 11 10:09:04 EST 2017                                                          
ffmpeg library versions:                                                                        
   libavutil       56.0.100                                                                     
   libavcodec      58.2.100                                                                     
   libavformat     58.2.100                                                                     
   libswscale      5.0.101                                                                      
   libavfilter     7.0.101                                                                      
   libswresample   3.0.101                                                                      
ffmpeg version: N-88710-gaeed5ecdb3                                                             
```

I can confirm that it's fixed.
