### ISSUE TITLE
vdpau-copy with higher Vsync-jitter than pure CPU decoding, is it normal?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#4572]
### mpv version and platform

```
CPU: intel core i5-4460
GPU: AMD RX460
mpv 0.25.0-305-g5df3576856 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Tue Jul  4 11:46:01 CST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.2
```

### Reproduction steps
Playing video with vdpau-copy hardware acceleration and CPU decoding.
### Expected behavior
vdpau-copy is better than pure CPU decoding.
### Actual behavior
It gets higher Vsync-jitter with vdpau-copy.

**Comment by lachs0r** [comment]
Yes this is normal. And your assumption that hardware decoding is in any way automatically better than software decoding is wrong. On a modern desktop, it has no advantages, and about the same power draw (I’ve measured this). Also, this is not a support forum.
