### ISSUE TITLE
The new mpv-git isn't compatible with SVP4

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#4574]
@qmega 
It doesn't work as usual, but SVP4 works fine with mpv-vapoursynth
It shows me these message when I try to build mpv-git in pamac:
```
The requested URL returned error: 504
The requested URL returned error: 502 
```

**Comment by wiiaboo** [comment]
Why is this a mpv issue?

**Comment by JulianLai** [comment]
@wiiaboo It seems to be caused by this issue: https://github.com/mpv-player/mpv/commit/300f6a334498059f28ec63406112348c7e00fa64
Is there any possible way to solve it?
