### ISSUE TITLE
Mpv fails to show video when another multimedia app is running

### ISSUE THREAD

**Issue by mzso** [mpv-player/mpv#4578]
Hi!

I started noticing this recently. (Though it doesn't mean it's a recent issue)

Usually my progDVB is running and I'm trying to preview a video with MPV.  Audio plays but no video. I see some desynchronization warning with a dropped frames counter going up constantly:

`Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).`

Sometimes after several long seconds the video finally appears. I usually don't have the patience to wait half a minute or more. Particularly because I mainly use MPV to quickly check out files, do to it's fast startup. (In normal circumstances.)

I never experienced an issue like this with any other video player.

**Comment by mzso** [comment]
@wiiaboo 
Well, you didn't waste time ignoring an issue.

**Comment by CounterPillow** [comment]
@mzso you've ignored the issue template and provided no useful information to even begin debugging this. You are not in any position to be snarky here.

**Comment by mzso** [comment]
[**@CounterPillow**](https://github.com/CounterPillow) commented on [2017. júl. 6. 11:10 CEST](https://github.com/mpv-player/mpv/issues/4578#issuecomment-313340928 "2017-07-06T09:10:41Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) you've ignored the issue template and provided no useful information to even begin debugging this. You are not in any position to be snarky here.

I provided every information I have...

**Comment by wm4** [comment]
Why is reading so hard? The issue template only requires you to *read* it and to fill out the missing parts.

Please don't waste our time. Getting help is a privilege, not a right.
