### ISSUE TITLE
mpv not able to play encrypted-mp4 (cenc-aes-ctr)

### ISSUE THREAD

**Issue by sschnug** [mpv-player/mpv#4579]
Hi, new mpv-user here evaluating the player for some project of mine.

**I'm having trouble playing encrypted-mp4 with mpv. Is there anything wrong (usage or misinterpretation of functionality) or is this a bug?**

## Example

Let's assume we got a sample-video: ```SampleVideo_1280x720_1mb.mp4``` (actual video does not matter).

#### 1:
```ffplay SampleVideo_1280x720_1mb.mp4```
    -> OK
#### 2:
```mpv SampleVideo_1280x720_1mb.mp4```
    -> OK

### Encrypt

Let's encrypt it using ffmpeg and cenc-aes-ctr:

#### 3:
```ffmpeg -i SampleVideo_1280x720_1mb.mp4 -vcodec copy -acodec copy -encryption_scheme cenc-aes-ctr -encryption_key 76a6c65c5ea762046bd749a2e632ccbb -encryption_kid a7e61c373e219033c21091fa607bf3b8  SampleVideo_1280x720_1mb_encrypted.mp4```

#### 4:
```ffplay SampleVideo_1280x720_1mb_encrypted.mp4 -decryption_key 76a6c65c5ea762046bd749a2e632ccbb```
    -> OK

#### 5: shinchiro build
```mpv --demuxer-lavf-cryptokey=76a6c65c5ea762046bd749a2e632ccbb SampleVideo_1280x720_1mb_encrypted.mp4```
```mpv --demuxer-lavf-cryptokey=76A6C65C5EA762046BD749A2E632CCBB SampleVideo_1280x720_1mb_encrypted.mp4``` (just to be sure)
    -> No -> looks it's beeing interpreted as unencrypted-stream or decryption is broken
    -> tons of bitstream errors

#### 6: lachs0r build
```mpv --demuxer-lavf-cryptokey=76a6c65c5ea762046bd749a2e632ccbb SampleVideo_1280x720_1mb_encrypted.mp4```
```mpv --demuxer-lavf-cryptokey=76A6C65C5EA762046BD749A2E632CCBB SampleVideo_1280x720_1mb_encrypted.mp4``` (just to be sure)
    -> No -> looks it's beeing interpreted as unencrypted-stream or decryption is broken
    -> tons of bitstream errors

## Version info
Everything tested on windows:

- ffmpeg version N-86691-gc885356 Copyright (c) 2000-2017 the FFmpeg developers
  - zeranoe windows build
- ffplay version N-86691-gc885356 Copyright (c) 2003-2017 the FFmpeg developers
  - zeranoe windows build
- mpv 0.25.0-289-g69289aec6c (C) 2000-2017 mpv/MPlayer/mplayer2 projects 
  - Windows build by shinchiro
- mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
  - Windows build lachs0r

**Edit:**
- same behaviour on Linux (ubuntu 16.04 LTS) using:
  - ```mpv 0.25.0-7bfeb8b-amended (C) 2000-2017 mpv/MPlayer/mplayer2 projects built on Sun Jun 25 04:29:14 UTC 2017``` installed through (non-Vapoursynth-PPA)

## Log-file
[log @ gist](https://gist.github.com/sschnug/1a63770779f8e6df3935d669d5eacc79)

## Remarks
Checking ```ffplay --help``` and searching for crypto-stuff, there are various entries and maybe this is the core of these problems.

Entries:

- **1:** AVFormatContext AVOptions:
  -   cryptokey         <binary>     .D...... decryption key
- **2:** crypto AVOptions:
  -   decryption_key    <binary>     .D...... AES decryption key
- **3:** mov,mp4,m4a,3gp,3g2,mj2 AVOptions:
  -   decryption_key    <binary>     .D...... The media decryption key (hex)

I suppose my ```ffplay```-command is using case 3, while ```mpv``` is using case 1. As the command i used for mpv is the only one i can imagine (only crypto-related) it's the only thing i tried.

I'm not that familiar with ffmpeg/ffplay (at this module-level), but i can imagine, that internally *AVFormat* and *AVOptions* are treated very differently.

**Comment by richardpl** [comment]
Because you first need to read mpv manual to figure how to correctly set ffmpeg avoptions.

**Comment by sschnug** [comment]
Fair enough. I can understand the frustration with lazy users, but for us it's not quite as simple as for you developers. So while i'm thankful for the hint, you could have also add a one-liner to show me what to do.

Nonetheless: 

Working (and maybe correct usage):

    mpv --demuxer-lavf-o=decryption_key=76a6c65c5ea762046bd749a2e632ccbb SampleVideo_1280x720_1mb_encrypted.mp4

**Comment by wm4** [comment]
Actually this option exists: https://mpv.io/manual/master/#options-demuxer-lavf-cryptokey

It's from ancient MPlayer times, and apparently it doesn't work.

**Comment by wiiaboo** [comment]
@wm4 might as well remove it, to prevent confusion.

**Comment by sschnug** [comment]
Thanks for the follow-up remarks!

**Comment by wm4** [comment]
Actually replaced it with different code.

**Comment by haasn** [comment]
So what's this about multiple options? `cryptokey` and `decryption_key`? Maybe we should set both?

**Comment by wm4** [comment]
Actually I think only `cryptokey` works. I used the option named @sschnug claimed to use though.

**Comment by sschnug** [comment]
I can't follow your discussion, but the source of my usage of ```decryption_kes``` (opposed to ```cryptokey```) comes from this old commit to ffmpeg [here](https://lists.ffmpeg.org/pipermail/ffmpeg-cvslog/2015-December/096951.html).

**Comment by wm4** [comment]
Oh, so it's a private mp4 option. Better to remove the mpv option then.

**Comment by wm4** [comment]
And it's gone.
