### ISSUE TITLE
Get watched position even file is skipped.

### ISSUE THREAD

**Issue by super94i** [mpv-player/mpv#4581]
Is there a way to get real-time watched time or progress from MPV? 
I know there "--save-position-on-quit", but it says in the docs "This does not happen if playback of a file is stopped in any other way than quitting", so if someone skips the file by mistake, he has to manually reach the point where he skipped "by mistake".

Thank you.

**Comment by haasn** [comment]
What I do in such cases is just look at the last playback time mpv showed on the terminal. When switching files, it preserves the status line of the previous file.

**Comment by CounterPillow** [comment]
You could also change your playlist entry skip bind to do a `write-watch-later-config` before switching to the next file.

**Comment by super94i** [comment]
Hey, Could you please delete this issue? I would really appreciate it!

**Comment by Akemi** [comment]
no it can't. also don't change the bloody title and content it can still be helpful for other when searching.
