### ISSUE TITLE
Noisy audio like broken audio

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#4582]
### mpv version and platform
8c0162e - Win10-x64

### Reproduction steps
Play audio

### Expected behavior
Normal audio

### Actual behavior
Noticed noisy audio like broken radio in beginning of file. 

### Log file
8c0162e log
[log.txt](https://github.com/mpv-player/mpv/files/1132731/log.txt)

69289ae log (works correctly)
[log.txt](https://github.com/mpv-player/mpv/files/1132732/log.txt)

I guess it should played as float, not stereo u8

### Sample files
https://0x0.st/GsT.opus

**Comment by kevmitch** [comment]
I think I've got a fix for this, but I'm not in windows at the moment to test. I'll post it shortly.

**Comment by shinchiro** [comment]
Yeah, that PR fixed it
