### ISSUE TITLE
Not fill out even with fullscreen option

### ISSUE THREAD

**Issue by xswqaz** [mpv-player/mpv#4585]
### mpv version and platform

0.25.0 Linux

### Reproduction steps

I'm using 1280x1028 resolution with 1920x1280 monitor for refresh rate 75Hz
But When I play with fullscreen option, mpv only play partial screen ( vertical expand needed )

### Expected behavior

Fill out screen

### Actual behavior

Not fill out screen ( needs to be expand vertical )

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by xswqaz** [comment]
I resolved by keepaspect=no

**Comment by lachs0r** [comment]
You could also use pan-and-scan to zoom while preserving aspect ratio.
With default keybinds, just press e, or use panscan=1 in your config.
