### ISSUE TITLE
man page: information about DXVA2 quality degradation not comprehensive enough

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4588]
### mpv version and platform

any version on Windows

### Reproduction steps

Compare color gradients or samples where chroma blur can easily be spotted

### Expected behavior

The man page should state that using DXVA2 will introduce additional banding and chroma blur compared to software decoding (or copyback modes), at least on Nvidia (can't test AMD & Intel).

### Actual behavior

There is just some information about wrong RGB conversion (which may be really old and not accurate anymore?).

### Sample files

http://www3.zippyshare.com/v/Bp7m54o3/file.html
With these samples, you can easily spot that banding gets worse (leave deband disabled) and chroma looks clearly blurrier compared to software decoding on Nvidia.

**Comment by kevmitch** [comment]
Not sure about the state then, but now it all seems pretty clearly described under "Quality reduction with hardware decoding": https://mpv.io/manual/master/#options-hwdec
