### ISSUE TITLE
sub-scale=1 doesn't work in ~/.mpv/config

### ISSUE THREAD

**Issue by shirishag75** [mpv-player/mpv#4589]
### mpv 0.25.0 on Debian testing/buster

I am running mpv on Debian testing/buster hence running mpv 0.25.0 . I have put the following options in ~/.mpv/config and tried to source it and got the following error - 

```
$] cat config                                                                                                                     
     1  # Write your default config options here!
     2  alang=eng,en,english
     3  slang=en,eng,english
     4  sub-scale=1
```

while sourcing it I get the following error - 

```
[$] source ~/.mpv/config                                                                                                           
/home/shirish/.mpv/config:4: command not found: sub-scale=1
```
The above should have worked, shouldn't it /

**Comment by wiiaboo** [comment]
Why are you trying to source it?
