### ISSUE TITLE
Mpv library with parameters for videoboard does not release memory

### ISSUE THREAD

**Issue by kapulkin** [mpv-player/mpv#4594]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Call subsequently C API methods
mpv_initialize()
mpv_set_option_string("keep-open", "always")
mpv_set_option("wid", 4)
mpv_set_option_string("hwdec", "yes")
mpv_command("loadfile", file)
mpv_command("set", "vd", "lavc:h264_cuvid")
mpv_command("set", "vo", "opengl")
mpv_terminate_destroy()

### Expected behavior

After loading library, film and then terminating it memory consuming should not changed essentially.

### Actual behavior

After loading library, film memory consumption grows and after terminating does not come back.

**Comment by kevmitch** [comment]
observe the issue template. need log, os, gpu, etc. Though this is almost certainly a driver bug since any memory mpv is actually responsible for should be freed on exit.
