### ISSUE TITLE
How to toggle on-screen-display with a hotkey?

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#4597]
### mpv version and platform

mpv 0.25.0, Windows 7 SP1

### Reproduction steps
I tried these bindings in mpv.conf:
c script-message osd-level cycle
c script-message osc-visibility cycle
c osd-level cycle
None of them prevented display of on-screen messages (i.e. playback progress when pressing O)

I was able to hide the on-screen controls, but messages such as volume change could only be hidden with  --no-osc (or no-osc in mpv.conf), but that'd require restarting the player. Is there a way to toggle the display of on-screen messages with a keybind without having to edit mpv.conf?

**Comment by wiiaboo** [comment]
First off, you're mixing OSC and OSD. Which one do you want to hide?

**Comment by UserNaem** [comment]
Preferably both with one hotkey. I was able to make a hotkey that toggles the display of on-screen-controls, but the on-screen-display messages still appear and the only way of hiding them I found was --no-osc.

**Comment by wiiaboo** [comment]
OSC isn't [toggleable like that](https://mpv.io/manual/master/#on-screen-controller-osc-visibility). And it doesn't have any relation whatsoever to osd-level, so I doubt that you managed to influence something in OSD with `--no-osc`. Look into using a simple script like [this](https://github.com/mpv-player/mpv/issues/4513#issuecomment-308363894).

**Comment by UserNaem** [comment]
Argh. I probably should have asked before wasting a hour trying to make it work like that. Thanks.

**Comment by avatar70t** [comment]
#/ no-osd cycle-values osd-level 3 1
