### ISSUE TITLE
window size on Windows not optimal by default when downscaling

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4598]
### mpv version and platform
0.25 Windows & Linux

### Reproduction steps
When you open a video that is bigger than the display's resolution (e.g. 4k video on 1440p screen), mpv's window on Windows doesn't get maximized and is too big for this state. This leads to the title bar being partially cut and parts of the video are drawn beneath the task bar.

### Expected behavior
On Linux (KDE Plasma), mpv's window by default gets maximized when the video size is bigger than the display's, so that no parts of the window are cut or burried below the task bar.
The same should happen on Windows by default, the current behavior is very inconvenient. And even when the window isn't maximized, it should never be "too big".

**Comment by wiiaboo** [comment]
Already sort of requested in another issue: https://github.com/mpv-player/mpv/issues/4363
