### ISSUE TITLE
mpv sftp://***  segmentation fault 

### ISSUE THREAD

**Issue by AlbertDu** [mpv-player/mpv#4600]
## info 
latest mpv version
osx and installed through brew

## log
mpv sftp://dzy@10.137.62.181:9688/home/dzy/1.avi -v

[cplayer] Command line options: 'sftp://dzy@10.137.62.181:9688/home/dzy/1.avi' '-v'
[cplayer] mpv c5dfd66 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Jul 11 20:56:48 CST 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.58.100
[cplayer]    libavcodec      57.89.100
[cplayer]    libavformat     57.71.100
[cplayer]    libswscale      4.6.100
[cplayer]    libavfilter     6.82.100
[cplayer]    libswresample   2.7.100
[cplayer] ffmpeg version: 3.3.2
[cplayer] 
[cplayer] Configuration: waf configure --prefix=/usr/local/Cellar/mpv/HEAD-c5dfd66 --enable-zsh-comp --enable-libmpv-shared --enable-html-build --confdir=/usr/local/etc/mpv --datadir=/usr/local/Cellar/mpv/HEAD-c5dfd66/share/mpv --mandir=/usr/local/Cellar/mpv/HEAD-c5dfd66/share/man --docdir=/usr/local/Cellar/mpv/HEAD-c5dfd66/share/doc/mpv --zshdir=/usr/local/Cellar/mpv/HEAD-c5dfd66/share/zsh/site-functions --enable-libarchive --enable-libbluray --enable-dvdnav --enable-dvdread --enable-pulse
[cplayer] List of enabled features: 52 apple-remote asm atomics avutil-imgcpy-uc bsd-fstatfs build-date caca cocoa coreaudio cplayer cplugins cuda-hwaccel debug-build dvdnav dvdread dvdread-common encoding fchmod gl gl-cocoa gl-x11 gnuc iconv is_ffmpeg jack jpeg lcms2 libarchive libass libass-osd libav libavcodec libavdevice libbluray libdl libm libmpv-shared lua macos-touchbar nanosleep optimize osx-thread-name plain-gl posix posix-or-mingw posix-spawn pthreads pulse rubberband shm stdatomic termios uchardet videotoolbox-gl videotoolbox-hwaccel videotoolbox-hwaccel-old x11 xv zlib zsh-comp
[global] config path: '' -> '/Users/du/.config/mpv'
[global] config path: 'encoding-profiles.conf' -/-> '/Users/du/.config/mpv/encoding-profiles.conf'
[global] config path: 'encoding-profiles.conf' -/-> '/Users/du/.mpv/encoding-profiles.conf'
[global] config path: 'encoding-profiles.conf' -/-> '/usr/local/bin/encoding-profiles.conf'
[global] config path: 'encoding-profiles.conf' -> '/usr/local/etc/mpv/encoding-profiles.conf'
[cplayer] Reading config file /usr/local/etc/mpv/encoding-profiles.conf
[global] config path: 'mpv.conf' -/-> '/Users/du/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/du/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/Users/du/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/Users/du/.mpv/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/bin/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/bin/config'
[global] config path: 'mpv.conf' -/-> '/usr/local/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/usr/local/etc/mpv/config'
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -/-> '/Users/du/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/Users/du/.mpv/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/bin/input.conf'
[global] config path: 'input.conf' -/-> '/usr/local/etc/mpv/input.conf'
[osc] Loading lua script @osc.lua...
[global] config path: 'scripts' -/-> '/Users/du/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/Users/du/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/bin/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] config path: 'lua-settings/osc.conf' -/-> '/Users/du/.config/mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/Users/du/.mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/usr/local/bin/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/usr/local/etc/mpv/lua-settings/osc.conf'
[osc] lua-settings/osc.conf not found. 
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[cplayer] mouse_leave script-binding osc/__keybinding2
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[cplayer] mouse_btn2 script-binding osc/__keybinding5
[cplayer] mouse_btn3 script-binding osc/__keybinding6
[cplayer] mouse_btn4 script-binding osc/__keybinding7
[cplayer] axis_up script-binding osc/__keybinding8
[cplayer] axis_down script-binding osc/__keybinding9
[cplayer] mouse_btn0_dbl ignore
[cplayer] shift+mouse_btn0_dbl ignore
[cplayer] mouse_btn2_dbl ignore
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[input, ]
[cplayer] Run command: define-section, flags=0, args=[input_osc, del script-binding osc/__keybinding10
[cplayer] , default]
[cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading lua script @ytdl_hook.lua...
[global] config path: 'scripts' -/-> '/Users/du/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/Users/du/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/bin/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[ytdl_hook] loading mp.defaults
[cplayer] Run command: disable-section, flags=0, args=[input]
[global] config path: 'fonts' -/-> '/Users/du/.config/mpv/fonts'
[global] config path: 'fonts' -/-> '/Users/du/.mpv/fonts'
[global] config path: 'fonts' -/-> '/usr/local/bin/fonts'
[global] config path: 'fonts' -/-> '/usr/local/etc/mpv/fonts'
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.4.6 (COMPLEX)
[global] config path: 'subfont.ttf' -/-> '/Users/du/.config/mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/Users/du/.mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/usr/local/bin/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/usr/local/etc/mpv/subfont.ttf'
[global] config path: 'fonts.conf' -/-> '/Users/du/.config/mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/Users/du/.mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/usr/local/bin/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/usr/local/etc/mpv/fonts.conf'
[osd/libass] Setting up fonts...
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[cplayer] Run command: hook-add, flags=0, args=[on_preloaded, 2, 10]
[cplayer] Done loading @ytdl_hook.lua.
[osd/libass] Using font provider coretext
[osd/libass] Done.
[global] config path: 'scripts' -/-> '/Users/du/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/Users/du/.mpv/scripts'
[global] config path: 'scripts' -/-> '/usr/local/bin/scripts'
[global] config path: 'scripts' -/-> '/usr/local/etc/mpv/scripts'
[global] config path: 'watch_later' -> '/Users/du/.config/mpv/watch_later'
[cplayer] Playing: sftp://dzy@10.137.62.181:9688/home/dzy/1.avi
[cplayer] Running hook: ytdl_hook/on_load
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[ffmpeg] Opening sftp://dzy@10.137.62.181:9688/home/dzy/1.avi
[1]    8250 segmentation fault  mpv sftp://dzy@10.137.62.181:9688/home/dzy/1.avi -v

### 1
brew info mpv
mpv: stable 0.25.0 (bottled), HEAD
Media player based on MPlayer and mplayer2
https://mpv.io
/usr/local/Cellar/mpv/HEAD-c5dfd66 (98 files, 56.1MB) *
  Built from source on 2017-07-11 at 20:57:26 with: --with-jack --with-libarchive --with-libbluray --with-libcaca --with-libdvdnav --with-libdvdread --with-pulseaudio --with-rubberband --with-uchardet --with-x11 --with-bundle
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb
==> Dependencies
Build: pkg-config ✔
Required: libass ✔, ffmpeg ✔
Recommended: jpeg ✔, little-cms2 ✔, lua ✔, youtube-dl ✔
Optional: jack ✔, libaacs ✘, libarchive ✔, libbluray ✔, libcaca ✔, libdvdnav ✔, libdvdread ✔, pulseaudio ✔, rubberband ✔, uchardet ✔, vapoursynth ✘
==> Requirements
Build: python3 ✔
Required: macOS >= 10.8 ✔
Optional: x11 ✔

### 2 

➜  ~ brew info ffmpeg
ffmpeg: stable 3.3.2 (bottled), HEAD
Play, record, convert, and stream audio and video
https://ffmpeg.org/
/usr/local/Cellar/ffmpeg/3.3.2 (243 files, 52.0MB) *
  Built from source on 2017-07-11 at 15:43:08 with: --with-libass --with-libssh --with-openssl --with-libvorbis --with-libvpx
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ffmpeg.rb
==> Dependencies
Build: pkg-config ✔, texi2html ✔, yasm ✔
Recommended: lame ✔, x264 ✔, xvid ✔
Optional: chromaprint ✘, fdk-aac ✘, fontconfig ✔, freetype ✔, frei0r ✘, game-music-emu ✘, libass ✔, libbluray ✔, libbs2b ✘, libcaca ✔, libgsm ✘, libmodplug ✘, libsoxr ✔, libssh ✔, libvidstab ✘, libvorbis ✔, libvpx ✔, opencore-amr ✘, openh264 ✘, openjpeg ✘, openssl ✔, opus ✘, rtmpdump ✘, rubberband ✔, schroedinger ✘, sdl2 ✘, snappy ✘, speex ✘, tesseract ✘, theora ✘, two-lame ✘, wavpack ✘, webp ✘, x265 ✘, xz ✔, zeromq ✘, zimg ✘

**Comment by wiiaboo** [comment]
Try opening the same link with ffmpeg/ffprobe/ffplay.

**Comment by AlbertDu** [comment]
how to open it in ffmpeg?

**Comment by wiiaboo** [comment]
Same way as with mpv, with a `-i` before the input URL/filename.

**Comment by AlbertDu** [comment]
➜  ~ ffmpeg -i  sftp://dzy@10.137.62.181:9688//home/dzy/1.avi 
ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libass --enable-libmp3lame --enable-libssh --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libxvid --enable-opencl --enable-openssl --disable-lzma --enable-nonfree --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
[1]    8744 segmentation fault  ffmpeg -i sftp://dzy@10.137.62.181:9688//home/dzy/1.avi

**Comment by wiiaboo** [comment]
Then it's not mpv issue. Open an issue in trac.ffmpeg.org.

**Comment by AlbertDu** [comment]
Is there any alternative way to open the sftp server file through mpv?

**Comment by wiiaboo** [comment]
Sure. Download the file and then open it locally.

**Comment by AlbertDu** [comment]
I would like to open the remote file in the online way, could you please give me some suggestions?

**Comment by wiiaboo** [comment]
This isn't a user support forum.

Open the issue in FFmpeg's bug tracker and it'll eventually be fixed, if it is a real issue.

**Comment by wm4** [comment]
Just use fuse or a web server?

**Comment by haasn** [comment]
You can also use `sshfs`.

**Comment by AlbertDu** [comment]
thanks a lot!

**Comment by wiiaboo** [comment]
If you use FFmpeg git master the issue is [probably fixed already](https://trac.ffmpeg.org/ticket/6413).

**Comment by lachs0r** [comment]
If it really is that same bug, just use pubkey auth. You should use pubkey auth anyway.
