### ISSUE TITLE
mpv won't execute frame-step or frame-back-step command after video reachs eof

### ISSUE THREAD

**Issue by wtiandong** [mpv-player/mpv#4602]
Hi all,
I notice that when mpv reaches the EOF of a video, it won't execute frame-step or frame-back-step command. But I hope when mpv reaches EOF, it can still respond to frame-back-step. I notice that when reaches EOF, mpv will uninit audio decoder, uninit video, and finish playback with reason 0 (success). Is there any method to make mpv keep the video and can respond to the command after reaches EOF?

**Comment by wtiandong** [comment]
Hi all,
I know how to solve this. Just mpv_set_option_string(mpv, "keep-open", "always"); to keep the file open.

**Comment by wm4** [comment]
Seems like you answered your own question?
