### ISSUE TITLE
ffmpeg: tls: Creating security context failed (0x80090302)

### ISSUE THREAD

**Issue by nexional** [mpv-player/mpv#4605]
### mpv version and platform
mpv-x86_64-20170708-git-7c1db05.7z, Windows 7 Professional 64 bit

### Reproduction steps
Open any video stream link using command line -
mpv [streaming-file-link]
e.g. 
mpv -v -v -v --log-file=log.txt "https://server.ferrante.me/shared/index.php?dir=iTunes/Home%20Videos/&file=35017Ferrante.m4v"

### Expected behavior
It's supposed to open the stream.

### Actual behavior
Fails with error -
ffmpeg: tls: Creating security context failed (0x80090302)
(I can play the movie directly in the browser but mpv fails to load it giving the "tls" error)
Also tried mpv with --no-config option but still the same error.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/1144181/log.txt)

### Sample files
attached mpv.conf file as well in zip form -
[mpv.zip](https://github.com/mpv-player/mpv/files/1144184/mpv.zip)

**Comment by mc4man** [comment]
use a better url
mpv --ytdl=no https://server.ferrante.me/shared/iTunes/Home%20Videos/35017Ferrante.m4v

**Comment by nexional** [comment]
Same error with "--ytdl=no" as well :(

/cygdrive/c> mpv --ytdl=no https://server.ferrante.me/shared/iTunes/Home%20Videos/35017Ferrante.m4v
   cplayer: Auto-loading profile 'protocol.https'
   cplayer: Playing: https://server.ferrante.me/shared/iTunes/Home%20Videos/35017Ferrante.m4v
    ffmpeg: tls: Creating security context failed (0x80090302)
    stream: Failed to open https://server.ferrante.me/shared/iTunes/Home%20Videos/35017Ferrante.m4v.
   cplayer:
   cplayer:
   cplayer: Exiting... (Errors when loading file)

**Comment by wiiaboo** [comment]
FFmpeg can't read it either, nor curl, so it seems like an issue with the server.

**Comment by CounterPillow** [comment]
@nexional Your server's certificate chain appears to be incomplete, according to the [Qualys SSL test](https://www.ssllabs.com/ssltest/analyze.html?d=server.ferrante.me)

**Comment by nexional** [comment]
I can open the media on browser. Is there a way to bypass certificate problem?

**Comment by CounterPillow** [comment]
you can use `--tls-verify=no` to bypass certificate verification, but the real solution here is to fix your server's certificate chain.

**Comment by mc4man** [comment]
Plsys back just fine here
mpv --ytdl=no https://server.ferrante.me/shared/iTunes/Home%20Videos/35017Ferrante.m4v 
Auto-loading profile 'protocol.https'
Playing: https://server.ferrante.me/shared/iTunes/Home%20Videos/35017Ferrante.m4v
 (+) Video --vid=1 (*) (h264 594x480 29.963fps)
 (+) Audio --aid=1 --alang=und (*) (aac 2ch 48000Hz)
     Audio --aid=2 --alang=und (ac3 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [opengl] 594x480 => 594x540 vaapi[nv12]
AV: 00:00:26 / 00:04:37 (9%) A-V:  0.000 Cache:  9s+39MB

**Comment by wiiaboo** [comment]
Plays fine here too now.

**Comment by CounterPillow** [comment]
Since it plays fine for @mc4man, could it be that this is a case of a certificate in the chain not yet being in our trust stores or something, but in the private trust stores of web browsers?

**Comment by mc4man** [comment]
If I were you I'd be thinking about wtf you're doing rather than an apparent inability to truncate a url to suit mpv (or likely any other player.
I don't know what country you're in but if US then probably a bad idea to advertise a wide open server of content for anyone to play (and a frickin dl button to boot 

Anyway if url is for ex.
https://server.ferrante.me/shared/index.php?dir=iTunes/Movies/300/&file=300%20%281080p%20HD%29.m4v
Then truncate to 
https://server.ferrante.me/shared/iTunes/Movies/300/300%20%281080p%20HD%29.m4v

(- all ytdl=no does is not waste time & needless warnings, ect.

**Comment by nexional** [comment]
Thanks guys but I still am not able to play with individual options or any combination of --tls-verify=no, --ytdl=no, --no-config.

@mc4man I don't own the server :). Just stumbled upon for some free content. It was working fine so far but suddenly started getting "tls" errors.

**Comment by mc4man** [comment]
Assumed it was yours based on 1st vid, i.e. home photos from the 50's
Have you actually tried removing `index.php?dir=`  and `&file=` from any of those server urls? 

https://server.ferrante.me/shared/iTunes/Home%20Videos/35017Ferrante.m4v

**Comment by nexional** [comment]
yeah, no luck :(

**Comment by wiiaboo** [comment]
Still works fine here. Whatever it is doesn't seem to be mpv's fault, but probably something wrong with your system's certificates.

**Comment by nexional** [comment]
Anything I can do to clear my system certificates?

**Comment by wiiaboo** [comment]
Try browsing it with IE or Edge and see if there's any error.

**Comment by nexional** [comment]
I can play the movie directly on any browser (chrome/IE) like I mentioned in original post. Somehow mpv fails to load it.

**Comment by nexional** [comment]
Anything on this problem. Is there a way to ignore the certificate error/chain?

**Comment by CounterPillow** [comment]
@nexional 
>you can use `--tls-verify=no` to bypass certificate verification

werks 4 me

**Comment by nexional** [comment]
Apparently it started working again with the latest build of either MPV (mpv-x86_64-20170722-git-2378acc.7z) or youtube-dl (2017.07.23). Don't even need the flag. I have to add, it's probably something done at the server end to fix the certificate chaining. Nonetheless I hope it doesn't break again. Fingers crossed :). BTW thanks guys for all your inputs.
