### ISSUE TITLE
Since v0.24, mpv fails to detect blu-ray subtitle language

### ISSUE THREAD

**Issue by macdavis** [mpv-player/mpv#4611]
### mpv version and platform
mpv (v0.24) and later, MacOS 10.12.5 (16F73)

### Reproduction steps
Download this sample [MVC 3D ISO Sample #2 with 3D Subtitles](https://drive.google.com/file/d/0BwxFVkl63-lEM2xjQndxV3ZzaVE/view?usp=sharing) and play it.

### Actual behavior
In 0.24, subtitle language can't be detected while in 0.23, it can be.
### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
[0.24.log](http://sprunge.us/HVXZ)
[0.23.log](http://sprunge.us/HeDR)
### Sample files
[MVC 3D ISO Sample #2 with 3D Subtitles](https://drive.google.com/file/d/0BwxFVkl63-lEM2xjQndxV3ZzaVE/view?usp=sharing)

**Comment by macdavis** [comment]
This problem still occurs in the latest git version. Sorry if I didn't make myself clear.

**Comment by wm4** [comment]
Do they use different libbluray versions?

**Comment by macdavis** [comment]
@wm4 
All mpv tests are under the same version of libbluray.
With libbluray 0.9.0: mpv 0.23 - ok,  mpv 0.24 - not working, mpv git(8e20ef4) - not working;
With libbluray 1.0.1: mpv 0.23 - ok,  mpv 0.24 - not working, mpv git(8e20ef4) - not working.

**Comment by wm4** [comment]
Can you bisect mpv git?

**Comment by macdavis** [comment]
@wm4 
I tried to locate it manually. It seems this bug was introduced in commit [fb9a32977d6abf4c83a92d993af58e393819c062](https://github.com/mpv-player/mpv/commit/fb9a32977d6abf4c83a92d993af58e393819c062)

Commit [e13a62fc346867450cd41d02cffbdaf477a3fec4](https://github.com/mpv-player/mpv/commit/e13a62fc346867450cd41d02cffbdaf477a3fec4) is the last version that works fine.
