### ISSUE TITLE
Is there a way to manually choose the MPV cache folder?

### ISSUE THREAD

**Issue by super94i** [mpv-player/mpv#4612]
Hello,

I don't much space in the main C:\ drive, I'm using special config where I set the cache to be 500+ MB per video. This means that amount will be saved in the C:\ Drive.

I'm using MPV on windows, installed. With this config: https://github.com/Argon-/mpv-config/blob/master/mpv.conf with some modifications.

I have another drive where an enough space is available, and this is where I want to save the cache of MPV "If possible".

Thanks!

*before someone asks, yes I know %appData%, is the place where it's stored. Even though I finished streaming what I watching. The 800 MB that was deducted from C:\ is still missing somewhere. Thanks.

**Comment by wm4** [comment]
Your config doesn't store any cache on the disk - only in RAM.

**Comment by super94i** [comment]
Alright, can I do download and stream? 
To avoid filling up my RAM?

**Comment by CounterPillow** [comment]
https://mpv.io/manual/master/#options-cache-file

**Comment by super94i** [comment]
@CounterPillow  That's Great! It works really well!

Quick question, can MPV pickup the latest cache saved, then continue caching what's after? So you wont need to re-fill the RAM to what's already saved in the ram?

Thanks!

**Comment by CounterPillow** [comment]
The manual for that option says

>you can't use an existing cache file to resume playback of a stream. (Technically, mpv wouldn't even know which blocks in the file are valid and which not.)

so in other words, no.

**Comment by super94i** [comment]
Alright. Thanks everyone.

**Comment by super94i** [comment]
Hey, Could you please delete this issue? I would really appreciate it!

**Comment by Akemi** [comment]
really...
