### ISSUE TITLE
Contradiction on information about release policy

### ISSUE THREAD

**Issue by lekeke** [mpv-player/mpv#4621]
The [README](https://github.com/mpv-player/mpv#release-cycle) states a new version of mpv is released every other month.

The [release-policy](https://github.com/mpv-player/mpv/blob/master/DOCS/release-policy.md#release-policy) states a new version of mpv is released every month and sometimes twice a month.

That's a contradiction.

Also there's been no release since April, so in the end neither one is being followed.

**Comment by fhlfibh** [comment]
@lekeke The release periods are not fixed that hard long then, afaik. Actually it seems depend on the devs' mood or something. In any case, you can clone and compile the latest version, even daily.

**Comment by Hrxn** [comment]
Why open another issue? 
There already is #4620

**Comment by lekeke** [comment]
@fhlfibh In any case it's better to make that clear, no? Someone reading the docs will be confused because it says one thing in the README and another thing in the release-policy.

@Hrxn That was not an issue, that was a pull request. And it was rejected because of commit guidelines and also because it was more of a joke on my part.
So here I opened a proper issue for discussion.

**Comment by Hrxn** [comment]
You're right, but I still think it could've been discussed there..
