### ISSUE TITLE
--sub-auto doesn't load external smi subtitle files

### ISSUE THREAD

**Issue by paseu** [mpv-player/mpv#4626]
### mpv version and platform
mpv version
mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Tue Jul 18 23:18:06 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.2

platform
4.11.9-1-ARCH

### Reproduction steps
mpv file.mkv(or avi) --sub-auto=all(or fuzzy,exact) --sub-file-paths=sub:subs:/path/to/subtitle/directory 

### Expected behavior
load external smi subtitle files (smi and srt files tested)

### Actual behavior
it doesn't load smi subtitle files(it loads srt files)
mpv v0.25.0 works well with same files

### Log file
http://sprunge.us/gAJH
### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)[](url)

**Comment by AirPort** [comment]
It seems that .smi has been dropped from subs extensions in 5bfbe6d due to potential license issues.

**Comment by paseu** [comment]
@AirPort thank you for the answer.
