### ISSUE TITLE
Playing multi-volume RAR archive results in segmentation fault

### ISSUE THREAD

**Issue by copywrong** [mpv-player/mpv#4635]
### mpv version and platform
v0.26.0 on Arch Linux x86_64
### Reproduction steps
Play a RAR file (.rar or .part01) part of a multi-volume sequence
### Expected behavior
Play video within multi-volume without segmentation fault
### Actual behavior
Complains about "missing" file in multi-volume sequence and segfaults
### Log file
https://pastebin.com/Ukk4Dc0u (.rar)
https://pastebin.com/t2kHRQ9A (.part01)

**Comment by wiiaboo** [comment]
libarchive bug, most likely.

**Comment by lachs0r** [comment]
(Those backtraces are pretty much useless without debug symbols installed.)

**Comment by garoto** [comment]
Multi-volume RARs cause a crash if they contain a "Recovery Record" of any ammount. Has been like this since the switch to libarchive IIRC. Crashing only occurs if a seek is performed, otherwise they open and play fine as far as I was able to test.

**Comment by garoto** [comment]
Btw, the error msg `[file] Cannot open file '<filename>r??': No such file or directory` isn't direclty related to "the multi-part with recovery record" mpv crash. This mgs will display even for files that play flawlessly from beggining to end.

**Comment by copywrong** [comment]
@wiiaboo Using that gives the following message:
> Failed to recognize file format.

.

**Comment by copywrong** [comment]
@lachs0r What package should I install to enable "debug symbols"?

**Comment by copywrong** [comment]
@garoto Playback was fine until pacman
> [ALPM]  upgraded mpv (1:0.25.0-1 -> 1:0.25.0-2)

**Comment by lachs0r** [comment]
As far as I know, you need to rebuild packages if you want debug symbols on Arch. See https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces

That distro is fucking retarded.

**Comment by garoto** [comment]
[**@copywrong**](https://github.com/copywrong) commented on [Jul 19, 2017, 5:56 PM GMT-3](https://github.com/mpv-player/mpv/issues/4635#issuecomment-316514656 "2017-07-19T20:56:07Z - Replied by Github Reply Comments"):
> [@garoto](https://github.com/garoto) Playback was fine until pacman upgrade:
> 
> > [ALPM]  upgraded mpv (1:0.25.0-1 -&gt; 1:0.25.0-2)

Forgot to say that I'm on Windows. @lachs0r is the old rar demuxer still present in the code and can it be made avaible perhaps? That'd settle it with me without bothering the libarchive guys.

**Comment by copywrong** [comment]
I don't know about you, but for me the issue is gone with mpv 0.28.2 and libarchive 3.3.2.
