### ISSUE TITLE
A few minutes playback MPV 0.26.0 kernel panic

### ISSUE THREAD

**Issue by misiekkb** [mpv-player/mpv#4637]
### mpv version and platform

0.26.0 on MBP late 2011 with OSX 10.11.6

### Reproduction steps

After update to 0.26.0 mpv playing a movie a few minutes. After a x minutes I get kernel panic.

### Expected behavior

On 0.25 working correct.

### Actual behaviour

Doesn't work on 0.26.0.

### Log file

I get in system log information "Graphics kernel error: 0x00000002"

**Comment by Akemi** [comment]
if possible try it on 10.12.5. it's most likely a driver bug.

**Comment by misiekkb** [comment]
Thanks for answer. Maybe time to upgrade system.
When I active GPU mpv working good, no kernel panic.

I get a lot of dropped on 0.26.0, no matter source video. This is my config https://pastebin.com/zcGVsauN

This config is the best for my mac on 0.25.0, but on 0.26.0 a lot of dropped a few thousands on movie. What is wrong?

**Comment by Akemi** [comment]
might be related to #4615.

**Comment by sCreami** [comment]
I suffered from an identical issue. I even made the Apple After Sales replace the motherboard but it didn't help because I kept the same hard drive. This issues (if it's the same as mine) comes from the OS after an upgrade. To fix it, use your Time Machine backup to reinstall MacOS. Don't worry about losing your personal files, the reinstallation keeps them. Only the OS related files are replaced.

**Comment by misiekkb** [comment]
I still this same problem on 10.13 and mpv 0.27.0, error "Graphics kernel error: 0x00000002" for a few minutes playing. Mpv 0.26.0 and 0.27.0 have problem with HD3000?

**Comment by haasn** [comment]
> Graphics kernel error: 0x00000002

Complain to apple

**Comment by misiekkb** [comment]
But on 0.25.0 everything is correct. On 0.27.0 if I turn on hwdec not crashed, but a lot of artefacts on screen and problem with color.

**Comment by CounterPillow** [comment]
that's still apple's fault. Userspace applications should not be able to crash the kernel, period.

**Comment by misiekkb** [comment]
To close this post. 0.28 fixing problems.
