### ISSUE TITLE
Request: Set video transparency when running under opengl using --alpha (0->255) option [as per OMXplayer --alpha option on Raspberry Pi]

### ISSUE THREAD

**Issue by raspi-user** [mpv-player/mpv#4638]
_'OMXPlayer: An accelerated command line media player - Raspberry https://www.raspberrypi.org/documentation/raspbian/applications/omxplayer.md
omxplayer --win 0,0,640,480 /opt/vc/src/hello_pi/hello_video/test.h264 ... instead of the default --alpha Set video transparency (0..255)_'

I don't think this option is currently available? Any suggestions for a possible workaround using shaders etc?

Thanks

**Comment by wm4** [comment]
--vo=rpi has an option, AFAIK.
