### ISSUE TITLE
[Request] Hotkey to record stream/video

### ISSUE THREAD

**Issue by pascaldulieu** [mpv-player/mpv#4639]
Would it be possible to implement something so a hotkey can be set to start and stop a recording and then output it using the screenshot-template and screenshot-directory to a location.

It would allow anyone to capture a small clip from a show or film and save it as a webm or other format and then post it where they would like quickly without the hassle of finding a program to do exactly that or editing the media to create the clip

**Comment by wiiaboo** [comment]
There's a few scripts doing just that in the [wiki](https://github.com/mpv-player/mpv/wiki/User-Scripts).
