### ISSUE TITLE
0.26.0 regression: errors when play audio(ao/oss)

### ISSUE THREAD

**Issue by cglogic** [mpv-player/mpv#4642]
### mpv version and platform
mpv 0.26.0 on FreeBSD

### Reproduction steps
Play any file with audio.

### Expected behavior
Play audio without errors in terminal, mpv 0.25.0 work well.

### Actual behavior
Continuous errors:
`[ao/oss] Audio device returned broken buffer state (sent 64 samples, got 0 samples, 8 period)!`

### Log file
[Log](http://sprunge.us/PFCP)

**Comment by scfarley** [comment]
I am also experiencing this except I see "4 period".

**Comment by iamleot** [comment]
@wm4 , I can confirm that this regression existed also on NetBSD and 8c82555 fixes it!

Thank you very much for the quick fix!

**Comment by scfarley** [comment]
Yes, thank you!

**Comment by cglogic** [comment]
Commit [8c82555](https://github.com/mpv-player/mpv/commit/8c82555e41a6a9edb677756cfe89f28a2918be2a) eliminates problem, thanks!
