### ISSUE TITLE
mpv not play this Multimedia file

### ISSUE THREAD

**Issue by zyb920** [mpv-player/mpv#4643]
I have a Multimedia file，mpv  is not play。
other player can  play， 
I want to send this multimedia file to you. I don't know how to send it。

This is the information that is viewed using MediaInfo：

General
Complete name                            : F:\play_source\1\featherhead.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 10.7 MiB
Duration                                 : 11mn 25s
Overall bit rate                         : 131 Kbps
Movie name                               : featherhead
Writing application                      : Lavf54.46.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Baseline@L3
Format settings, CABAC                   : No
Format settings, ReFrames                : 6 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 120ms
Bit rate                                 : 424 Kbps
Width                                    : 1 066 pixels
Height                                   : 800 pixels
Display aspect ratio                     : 4:3
Original display aspect ratio            : 4:3
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.020
Stream size                              : 6.21 KiB (0%)

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 11mn 25s
Bit rate mode                            : Constant
Bit rate                                 : 129 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 KHz
Compression mode                         : Lossy
Stream size                              : 10.6 MiB (99%)

**Comment by rossy** [comment]
A log from mpv would probably be more useful than MediaInfo output (please read the issue template.)

If you want to upload the file, try https://0x0.st/ or https://mixtape.moe/

**Comment by lachs0r** [comment]
Well, apparently OP doesn’t care.

**Comment by zyb920** [comment]
I uploaded this file through https://mixtape.moe/

**Comment by lachs0r** [comment]
Broken file. Has 3 video frames at a rate of 25 FPS, so of course it ends before you hear anything. Playing with `--no-video` works.
