### ISSUE TITLE
Apple’s OpenAL implementation is useless; mpv should prefer openal-soft

### ISSUE THREAD

**Issue by lachs0r** [mpv-player/mpv#4645]
https://github.com/mpv-player/mpv/commit/af6126adbe61fb2b6cc780025246d33df93072e6 introduced support for building with Apple’s OpenAL implementation, which however is horrible. If present, mpv should always prefer openal-soft.

See also #3763.

**Comment by timofonic** [comment]
@lachs0r I heard that from a Mac user too. Unrelated, I also got amazed macOS only goes up to OpenGL 4.1.

**Comment by haasn** [comment]
I'm amazed macOS even manages to boot on Apple hardware.
