### ISSUE TITLE
mpv does not play audio cd on linux

### ISSUE THREAD

**Issue by glaubersm** [mpv-player/mpv#4646]
### mpv version and platform
0.26, Arch linux

### Reproduction steps
insert audio cd, open terminal, run "mpv /dev/sr0"
### Expected behavior
mpv plays audio cd
### Actual behavior
mpv does not play audio cd

### Log file

https://0x0.st/DeZ.txt

**Comment by Cpuroast** [comment]
As far as I know that's in the 0.25 changelog:

"Support for some optical media functionality (DVD/CD) is now disabled by default."

I assume this applies to cd audio.

**Comment by lachs0r** [comment]
`av://libcdio:/dev/sr0` could still work however. I never tried (got rid of my last CDs a few weeks ago).

**Comment by glaubersm** [comment]
lachs0r your command does not work.

**Comment by lachs0r** [comment]
Well, that’s unfortunate. You need to rebuild with `--enable-cdda` then.

**Comment by mc4man** [comment]
Why anyone would use mpv for audio cd's is a mystery but seeing as though you have ccda enabled it may have been something like - 
mpv cdda://
or 
mpv --force-window cdda://

**Comment by lachs0r** [comment]
Oh, I missed that. Yeah. You might have to use the cdda protocol explicitly.

**Comment by glaubersm** [comment]
I use smplayer with mpv backend to play audio cds.
mpv cdda:// works.
