### ISSUE TITLE
crash on deinterlace video

### ISSUE THREAD

**Issue by ERYuyNIrbNKrsc** [mpv-player/mpv#4652]
### mpv version and platform

mpv 0.26.0-21-g38b367c03 
Kubuntu 17.10 x86_64

### Reproduction steps

play interlaced video (although it is possible with any video) --> press "d" --> crash

### Log file

http://sprunge.us/bBgZ

backtrace
http://sprunge.us/HUgQ

**Comment by mc4man** [comment]
It would be this commit that's caused vavpp to crash mpv
https://github.com/mpv-player/mpv/commit/0ce3dce03aaea3e777ebf68504d5afb3f5e3f9e1

**Comment by haasn** [comment]
Unfortunately, @wm4 is currently on vacation, and I think he's the only one who fully understands this change or how to best fix the issue.

**Comment by ERYuyNIrbNKrsc** [comment]
I just temporarily turned off the "vaapi"

**Comment by nagisa** [comment]
Having the same without deinterlacing. I think in my case it happens because of 10-bit colour space in the source, but not sure. Not using deinterlacing though.

**Comment by Gusar321** [comment]
@nagisa are you using --vo=vaapi? That in combination with software decoding will crash.

**Comment by nagisa** [comment]
Yes.

**Comment by mc4man** [comment]
Just in the outside chance this has slipped thru the cracks thought I'd bump it.
