### ISSUE TITLE
Subtitles not showing with compute polar filter

### ISSUE THREAD

**Issue by quilloss** [mpv-player/mpv#4657]
### mpv version and platform

mpv 6c06e7e
Windows 10

### Reproduction steps
View subtitled video with ```--scale=ewa_lanczos --blend-subtitles=yes```.
Ensure the video is scaled so that the ```ewa_lanczos``` filter is taking effect.
### Expected behavior
Subtitle is visible.
### Actual behavior
Subtitle is not visible.

I think this is due to this ```bool skip_fbo = flags & FBOTEX_COMPUTE;``` in [fbotex_change](https://github.com/mpv-player/mpv/blob/master/video/out/opengl/utils.c#L333). Removing that condition allows subtitles to be displayed.

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by haasn** [comment]
Ah, makes sense. We still need an FBO if we're going to be writing to the same image from a *different* shader. Fair enough, I'll just delete the skip_fbo logic. Worst case is that we'll allocate an FBO we don't actually use, big deal.
