### ISSUE TITLE
Crach when the video filter VAVPP is enabled

### ISSUE THREAD

**Issue by cranes-bill** [mpv-player/mpv#4660]
### mpv version and platform
mpv (f2809e1)
Linux

### Reproduction steps
Just play some video.

### Expected behavior
To play video

### Actual behavior
Crashes with the following output:
```
Opening video filter: [vavpp]
Using hardware decoding (vaapi).
mpv: ../video/mp_image_pool.c:174: mp_image_pool_add: Assertion `mp_image_is_writeable(new)' failed.
Abandon (core dumped)
```

**Comment by mc4man** [comment]
Same as https://github.com/mpv-player/mpv/issues/4652
