### ISSUE TITLE
[Question/Request] Minimizing via script / script events supporting ipc

### ISSUE THREAD

**Issue by FDMX2** [mpv-player/mpv#4661]
I want to create a lua script providing a minimize, close and fullscreen button on the upper right window of mpv, if started without borders or in fullscreen mode.
Fullscreen and close buttons work as expected by toggling the fullscreen property and using the _quit_ command. But i struggle with implementing the minimizing functionality.
I have two questions about this:

- is there a property or command to minimize the window (the property "window-minimized" cannot be set) within lua scripting environment?
- if not, how can i create an event inside the script in a way that an ipc client can subscribe to it? This way the ipc client can minimize mpv.

If none of the above works a request either minimizing functionality out of the box or a way to create custom events working together with ipc.

**Comment by paulguy** [comment]
Can wmctrl be used within lua?

**Comment by FDMX2** [comment]
System commands can be called, so this would work at least with Linux. 
But on the one hand this would limit the solution to Linux and on the other hand it would require another program although i already use mpv wrapped up in another one connected via ipc. Thus a way to create events within a script that can be observed via ipc would be sufficient for me.

**Comment by FDMX2** [comment]
I was not able to invoke an event or create a new one inside a lua script in a way that it could be reached throughout an IPC connection.
In order to make it work anyway i abused an already existing property (in my case the `status-msg` property) and observed it via IPC.

**Comment by Dudemanguy** [comment]
>I want to create a lua script providing a minimize, close and fullscreen button on the upper right window of mpv, if started without borders

Old but this is actually what happens by default now in the OSC. If you always want the buttons to be visible in fullscreen, use an auto-profile or something.
