### ISSUE TITLE
Compute shader uses too much shared memory

### ISSUE THREAD

**Issue by quilloss** [mpv-player/mpv#4668]
### mpv version and platform

9875f14
Windows 10

### Reproduction steps
Downscale using a compute shader.
### Expected behavior
No errors.
### Actual behavior
Blue screen with the following error.
```error C5041: cannot locate suitable resource to bind variable "in2". Possibly large array.```

```--window-scale=0.2972``` consumes 50544 bytes. My gpu only has 49152 bytes of shared memory. The minimum possible amount is 32768 bytes.

The program should limit the use of compute shared memory or fallback to fragment shader scaling for such downscaling ratio.

**Comment by haasn** [comment]
Yeah, I had suspected as much; which is why I originally hard-coded the maximum radius at 16. But it seems that was not strict enough.

I've changed it to compute the exact requirements.
