### ISSUE TITLE
"mp_image_pool: disallow adding read only frames" breaks vavpp

### ISSUE THREAD

**Issue by philipl** [mpv-player/mpv#4670]
### mpv version and platform
git master, linux

### Reproduction steps

Use hwdec=vaapi with vf=vavpp

I tried with h.264 and mpeg2 and with interlaced/progressive with and without using the deinterlacer. All with identical results.

I also did git bisect to narrow it down to this specific change (although the error made it pretty obvious)

### Expected behavior

Video plays

### Actual behavior

```
mpv: ../video/mp_image_pool.c:174: mp_image_pool_add: Assertion `mp_image_is_writeable(new)' failed.
Aborted (core dumped)
```

### Log file

http://sprunge.us/OgEQ

### Sample files

Any file, it seems, but log is generated using `burosch1.mpg`

**Comment by haasn** [comment]
Duplicate of #4652.
