### ISSUE TITLE
[Question]  how to reduce width of video without the height increasing

### ISSUE THREAD

**Issue by pennyscan** [mpv-player/mpv#4671]
Windows Build:   mpv-x86_64-20170718

Any mp4 video and using     vf add dsize= ...     in input.conf

I have spent over 20 hours trying to solve this simple problem, and every dsize combination I can think of.

Any help would be very appreciated.

**Comment by garoto** [comment]
Not sure if I understand what you're trying to do, but maybe one of these two:

`--no-keepaspect-window` or `--no-keepaspect`

**Comment by pennyscan** [comment]
thanks for reply.
I have tried those options before, but I'll try again now

this is behaviour I need, shown here using MPC or Pot player

https://youtu.be/YnobYs_dVR8

**Comment by pennyscan** [comment]
yes, same problem, height increase, not width decrease

input.conf is this...
1 vf add dsize=640:360
2 vf add dsize=600:360
3 vf add dsize=560:360


run mpv --no-keepaspect --start=+%seek_time% --keep-open=yes --no-border --cursor-autohide=always --osc=no --osd-level=0 "%inputfile%"

**Comment by pennyscan** [comment]
Thanks garoto, you helped solve again.

I just needed to add --geometry and use your --no-keepaspect-window option

it all works great now
many thanks
