### ISSUE TITLE
[Question] how to queue (enqueue) media

### ISSUE THREAD

**Issue by pennyscan** [mpv-player/mpv#4674]
windows 10

run mpv  song1.mp3                 this will play song1.mp3

run --append song2.mp3       is something like this possible ?

A method to play song2 after song1 finished

I cannot find solution in the mpv manual

**Comment by avih** [comment]
You could drag and drop another file onto the mpv window while you hold down the Shift key - which will add it to the current playlist. I'm not sure if it's at the manual.

**Comment by wiiaboo** [comment]
Shift+drag the new files to an already open mpv or run the initial one with `--input-ipc-server=\\.\pipe\mpvsocket` and then `echo loadfile song2.mp3 append-play > \\.\pipe\mpvsocket`.

**Comment by haasn** [comment]
Rather than `--input-ipc-server` you could also use the simpler `--input-file` if all you care about is sending commands

**Comment by pennyscan** [comment]
thankyou for the solution.

**Comment by pennyscan** [comment]
echo loadfile song2.mp3 append-play > \\.\pipe\mpvsocket

Yes this works great for simple filenames but not longer filenames with spaces or others chars.

Is there a way to make this work with a filename like  "My song àéÿ  £¥ƒ€.mp3"

**Comment by garoto** [comment]
See my comment [here](https://github.com/mpv-player/mpv/issues/4695#issuecomment-319412003).

**Comment by mossaybo** [comment]
### **Linux:** 
(needs xclip to be installed)
add the following to ~/.config/mpv/input.conf
`Ctrl+c run "/bin/bash" "-c" "echo ${sub-text} | xclip -selection clipboard"`
