### ISSUE TITLE
How do I disable the OSD message that shows up when I press next/prev button?

### ISSUE THREAD

**Issue by fdemolisher** [mpv-player/mpv#4675]
When I press next/prev playlist or chapter button on the OSC, an OSD message shows up and sometimes overlap with other OSD messages like so:
![sallysubs hanayamata - 07 bd 720p aac 155f9177 mkv_0001_ 00_00_03 461](https://user-images.githubusercontent.com/30496130/28666832-2fb299d0-72f3-11e7-8f8f-fccc29daec0b.jpg)

![sallysubs hanayamata - 07 bd 720p aac 155f9177 mkv_0003_ 00_10_47 937](https://user-images.githubusercontent.com/30496130/28666715-c9c5f09a-72f2-11e7-9c54-c0e7e05777f7.jpg)

What do I do to disable this? Tried --osd-level=0 but it disabled the other OSD instead.

**Comment by Keith94** [comment]
I'm wondering about this as well. Often times the text takes up too much space on the screen. It would be nice to adjust the duration on screen and/or font size of these specific messages.

**Comment by butterw** [comment]
So, does Anyone Know how to disable playlist OSD without disabling OSD ?

**Comment by Jonta** [comment]
@butterw This thread: https://bbs.archlinux.org/viewtopic.php?id=213642

Points to
`--no-osd-bar`
and
`--osd-bar`
in the man-page

> Disable display of the OSD bar. This will make some things (like
seeking) use OSD text messages instead of the bar.

> You  can  configure  this  on  a per-command basis in input.conf
using osd- prefixes, see Input command prefixes. If you want  to
disable the OSD completely, use --osd-level=0.

**Comment by garoto** [comment]
This behavior is hardcoded in `osc.lua` and cannot be changed with the current avaiable options.

**Comment by adamburgess** [comment]
Does this issue need to be closed? It would be nice to have an option to disable the chapter list OSD. Having the ticks in the bottom bar is usually sufficient. I would like to disable it as so many named chapters are filled with spoilers...

**Comment by avih** [comment]
> Does this issue need to be closed?

I closed it accidentally, but now it should really be closed, as #9515 was just merged.

**Comment by adamburgess** [comment]
@avih this is awesome, thanks for taking the time :)
