### ISSUE TITLE
Add a V4L2 mem2mem hwdec

### ISSUE THREAD

**Issue by linkmauve** [mpv-player/mpv#4677]
### mpv version and platform
0.26.0-40-g81851febc4, on Linux on ARM.

### Reproduction steps
- Have a random ARM board.
- Want to play a video on it.
- Start it in mpv, with hwdec=auto since you heard it’s useful.

### Expected behavior
The video plays fine.

### Actual behavior
Your CPU is way too slow since you are on a terrible ARM board, so swdec can’t keep up with whatever huge video file you gave it.

ffmpeg now [got a m2m driver](https://ffmpeg.org/pipermail/ffmpeg-devel/2017-July/214067.html), which could be used as a copy hwdec by mpv.  It is the de-facto API for video decoding in Linux, and is implemented for many SoCs so it shouldn’t be very hard to find supported hardware for testing.

### Log file
N/A

### Sample files
Any hard enough to decode file.

**Comment by wm4** [comment]
Patches welcome.

I know someone wants to add support for a device that requires a custom decoder lib, but outputs mem fds, and rendering can be done via DRM. So the rendering part could handle both.

**Comment by sfan5** [comment]
taken care of by #10496
