### ISSUE TITLE
mpv does not find vaapi as selected video output

### ISSUE THREAD

**Issue by saski4711** [mpv-player/mpv#4682]
current mpv git does not find vaapi when selected as output

command used: ./mpv -v --vo=vaapi --ao=alsa --hwdec=auto 

[vo] Video output vaapi not found!
[cplayer] Error opening/initializing the selected video_out (--vo) device.
[cplayer] Video: no video                                                                                           

./mpv -vo=help shows:

Available video outputs:
  opengl         : Extended OpenGL Renderer
  null           : Null video output
  image          : Write video frames to image files
  tct            : true-color terminals
  drm            : Direct Rendering Manager

so no vaapi detedted apparently. configure log however inicates that vaapi is being detected: 
Checking for VAAPI acceleration                                   : yes
Checking for VAAPI (X11 support)                                  : x11 not found
Checking for VAAPI (Wayland support)                              : gl-wayland not found
Checking for VAAPI (DRM/EGL support)                              : yes
Checking for VAAPI GLX                                            : gl-x11, vaapi-x11 not found
Checking for VAAPI EGL on X11                                     : vaapi-x11, egl-x11 not found
Checking for VAAPI EGL                                            : not found any of vaapi-wayland, vaapi-x-egl

foll log: https://pastebin.com/Gnw8XhnY

vainfo shows:
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib64/va/drivers/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.40 (libva )
vainfo: Driver version: Intel i965 driver for Intel(R) Kabylake - 1.8.4.pre1 (glk-alpha-81-g7f50a13)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointEncSlice
      VAProfileVP9Profile2            : VAEntrypointVLD

mpv log -v: https://pastebin.com/Ze9k3HNF

What am I doing wrong?

**Comment by CounterPillow** [comment]
You didn't build with X11 support since you don't have X11 development headers installed, so it can only do VAAPI through DRM/EGL, not on X11 or Wayland.

fwiw, you shouldn't be using vo_vaapi anyway, but opengl.

**Comment by saski4711** [comment]
Well x11 is installed allright. A closer look at config.log brought the answer:

Checking for X11
['/usr/bin/pkg-config', 'x11 >= 1.0.0', 'xscrnsaver >= 1.0.0', 'xext >= 1.0.0', 'xinerama >= 1.0.0', 'xrandr >= 1.2.0', '--libs', '--cflags', 'x11', 'xscrnsaver', 'xext', 'xinerama', 'xrandr']
err: Package xscrnsaver was not found in the pkg-config search path.
Perhaps you should add the directory containing `xscrnsaver.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xscrnsaver' found
Package xscrnsaver was not found in the pkg-config search path.
Perhaps you should add the directory containing `xscrnsaver.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xscrnsaver' found

Is this xscrnsaver **really** a necessary dependency to get X11 output? 
Anyway, mpv plays vaapi just fine after the missing lib is being installed.

**Comment by CounterPillow** [comment]
https://github.com/mpv-player/mpv/blob/1097c1416f352fe4da49391548224a057cfc870d/video/out/x11_common.c#L1915

may be legacy code, but it is used.
