### ISSUE TITLE
DXVA2 and D3D11VA don't work for VP9 10 bit on a GT 1030

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4683]
### mpv version and platform
0.26.0 Windows

### Reproduction steps
Set up config for DXVA2/D3D11VA and play VP9 10 bit video.
(I tried both opengl-backend=dxinterop and angle, also hwdec copy modes.)

### Expected behavior
mpv should use hardware decoding on a GTX 1030 (it does work with LAV Filters or the Windows 10 video app).

### Actual behavior
It uses software decoding.

### Log file
I can't provide further information since I don't have access to the GT 1030 anymore.
But I suppose it's better to report it anyway than to keep it unmentioned.

### Sample files
Download a VP9 10 bit video from YouTube using youtube-dl:
https://www.youtube.com/watch?v=tO01J-M3g0U
It's likely not correctly flagged as HDR, but that shouldn't matter for decoding.

**Comment by wm4** [comment]
No log -> can't act on it.
