### ISSUE TITLE
[Question] Help with Scaling

### ISSUE THREAD

**Issue by pennyscan** [mpv-player/mpv#4684]
I've replaced MPC and Pot Player with mpv in a windows app. 
Everything is working great except one problem I can't resolve after much effort.

the ability to reduce or enlarge the width of the video by a % (or by pixel amount) with a key

I've tried dsize, geometry, scaling, lua scripts (cannot write width or dwidth) ffmpeg filters, --no-keepaspect-window etc.

if anyone can solve this problem I'm happy to paypal €50 toward their time

here is an example of required behaviour with MPC player https://youtu.be/YnobYs_dVR8

Keith

**Comment by avih** [comment]
Something like this at your `input.conf` ?

```
ctrl+e add aspect 0.1
ctrl+w add aspect -0.1
```

**Comment by pennyscan** [comment]
Thank you so much for your help, that seems to work perfectly. 
I'll test a bit more tomorrow, but please send me an email address I can credit paypal you as promised

thanks again

**Comment by avih** [comment]
You're welcome. Please donate it to a good cause of your choice.

**Comment by pennyscan** [comment]
Thanks,

I hope this foundation to help cure ageing is acceptable..

Here is receipt.

Best regards
Keith hoyes


[image1.JPG]





On 29 Jul 2017, at 12:14 pm, avih <notifications@github.com<mailto:notifications@github.com>> wrote:


You're welcome. Please donate it to a good cause of your choice.

**Comment by pennyscan** [comment]
this is my current input.conf for windows which works really well..

1 run "cmd.exe" "/d" "/c" "echo ${playback-time} / ${duration}|clip"    #time and duration to clipboard
2 add aspect -0.01      # thinner video
3 add aspect 0.01          # wider video
4 add window-scale -0.1    # decrease video size
5 add window-scale 0.1     # increase video size 
6 multiply speed 0.96      # slow video player 5%
7 multiply speed 0.99	   # slow music player 1%
