### ISSUE TITLE
Interpolation has no effect when enabled

### ISSUE THREAD

**Issue by chrisyue** [mpv-player/mpv#4686]
### mpv --version

it's on MacOS Sierra 10.12.5

```
mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Tue Jul 18 21:38:06 BST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.2
```

### Reproduction steps

```
mpv --interpolation --video-sync=display-resample <video-path>
```

also I tried `--tscale` option with values like `mitchell`, `triangle`,

### Expected behavior

the video played should be smoother.

### Actual behavior

the video played looks the same as no `--interpolation`

### Log file

http://sprunge.us/AGjT

### Sample Video

http://www.dvdloc8.com/clip.php?movieid=12167&clipid=1

**Comment by haasn** [comment]
Try going through https://github.com/haasn/interpolation-samples

**Comment by chrisyue** [comment]
@haasn thanks for the sample.

and I tried the big bunny sample https://github.com/haasn/interpolation-samples/raw/master/20fps/native.mkv?raw=true, still I can't tell a difference when use a interpolation or not

**Comment by haasn** [comment]
So even with interpolation enabled, that 20 fps native clip doesn't look like the “20 fps + interpolation” sample?

**Comment by chrisyue** [comment]
@haasn OK, I got what you mean. 

There is no "20 fps + interpolation" sample, however, I've compared "24 fps + linear" sample, it's the same as 24 fps native + interpolation + tscale=linear, so it's actually has some effects with interpolation feature. Maybe it's too hard to "interpolation" a 20 fps video, so I can't tell a difference about interpolation used on the 20 fps sample.

and it's strange that interpolation has unnoticable effect on video I downloaded, which is 30fps. I think I will try more video to confirm this issue

**Comment by garoto** [comment]
I recorded my screen while playing the `20fpsnative.mkv` sample with and without `interpolation` and the difference for me is quite jarring between the two modes.

https://0x0.st/kM8.mp4 (~21MB)

**Comment by Hrxn** [comment]
Uh, what kind of special version of Windows is that?

**Comment by garoto** [comment]
It's just 8.1 with shell 'enhancements' I guess.

**Comment by Hrxn** [comment]
Is that ConEmu, the terminal app?

**Comment by garoto** [comment]
No, that's ConsoleZ (/cbucher/console/), Clink and ansicon.

**Comment by chrisyue** [comment]
I had misunderstanding of the `--interpolation` option, this issue could be closed.
