### ISSUE TITLE
Subtitles not shown on last frame in encoding mode

### ISSUE THREAD

**Issue by lachs0r** [mpv-player/mpv#4689]
### mpv version and platform

mpv 0.26.0-52-g37b7b32d61 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.2

### Reproduction steps

Encode a video with subtitles on the last frame.

### Expected behavior

Subtitles are visible on last frame.

### Actual behavior

Subtitles disappear on last frame.

### Log file

Not relevant.

### Sample files

https://0x0.st/kce.mkv

`mpv kce.mkv --oautofps -o test.avi`

**Comment by lachs0r** [comment]
Update: Subtitles on the last frame may actually be completely random. Timestamp problem?

**Comment by wm4** [comment]
Can't reproduce anyway.
