### ISSUE TITLE
flicker with video-sync=display-vdrop

### ISSUE THREAD

**Issue by jaccc** [mpv-player/mpv#4690]
### mpv version and platform
0.26.0, Gentoo

### Reproduction steps
video-sync=display-vdrop
interpolation
set display to 59.94 Hz
play 59.94 fps video

### Expected behavior
no flicker
### Actual behavior
flicker every few seconds
### Log file

[vo/opengl] Initializing OpenGL backend 'x11probe'
[vo/opengl/x11] X11 opening display: :0.0
[vo/opengl/x11] X11 running at 1920x1080 (":0.0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Display 0 (HDMI1): [0, 0, 1920, 1080] @ 59.939394 FPS
[vo/opengl/x11] Current display FPS: 59.939394
[vo/opengl] GLX chose FB config with ID 0x95
[vo/opengl] GLX chose visual with ID 0xc2
[vo/opengl] Creating OpenGL 4.0 context...
[vo/opengl/x11] X11 error: GLXBadFBConfig
[vo/opengl/x11] Type: 0, display: 0x3c31403f990, resourceid: 13c, serial: 3c
[vo/opengl/x11] Error code: b0, request code: 9a, minor code: 22
[vo/opengl] Creating OpenGL 3.3 context...
[vo/opengl] GL_VERSION='3.3 (Core Profile) Mesa 17.1.5'
[vo/opengl] Detected desktop OpenGL 3.3.
[vo/opengl] GL_VENDOR='Intel Open Source Technology Center'
[vo/opengl] GL_RENDERER='Mesa DRI Intel(R) Sandybridge Desktop '
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='3.30'
[vo/opengl] Loaded extension GL_ARB_get_program_binary.
[vo/opengl] Loaded extension GLX_SGI_swap_control.
[vo/opengl] Loaded extension GLX_SGI_video_sync.
[vo/opengl] Loaded extension GL_ARB_debug_output.
[vo/opengl] No vdpau support found - probing more things.
[vo/opengl/x11] uninit ...
[vo/opengl] Initializing OpenGL backend 'x11egl'
[vo/opengl/x11] X11 opening display: :0.0
[vo/opengl/x11] X11 running at 1920x1080 (":0.0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Display 0 (HDMI1): [0, 0, 1920, 1080] @ 59.939394 FPS
[vo/opengl/x11] Current display FPS: 59.939394
[vo/opengl] EGL_VERSION=1.4 (DRI2)
[vo/opengl] EGL_VENDOR=Mesa Project
[vo/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES 
[vo/opengl] Trying to create Desktop OpenGL context.
[vo/opengl] chose visual 0x20
[vo/opengl] GL_VERSION='3.3 (Core Profile) Mesa 17.1.5'
[vo/opengl] Detected desktop OpenGL 3.3.
[vo/opengl] GL_VENDOR='Intel Open Source Technology Center'
[vo/opengl] GL_RENDERER='Mesa DRI Intel(R) Sandybridge Desktop '
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='3.30'
[vo/opengl] Loaded extension GL_ARB_get_program_binary.
[vo/opengl] Loaded extension GL_ARB_debug_output.
[vo/opengl] swap_control extension missing.
[vo/opengl] 16 bit texture depth: 16.
[vo/opengl] Testing FBO format 0x805b
[vo/opengl] Create FBO: 16x16 (16x16)
[vo/opengl] Using FBO format 0x805b.
[vo/opengl] Assuming 59.939394 FPS for display sync.
[vd] Container reported FPS: 29.970030
[vd] Codec list:
[vd]     mpeg2video - MPEG-2 video
[vd]     mpegvideo (mpeg2video) - MPEG-1 video
[vd]     mpeg2_cuvid (mpeg2video) - Nvidia CUVID MPEG2VIDEO decoder
[vd] Opening video decoder mpeg2video
[vd] Using software decoding.
[vd] Detected 2 logical cores.
[vd] Requesting 3 threads for decoding.
[vd] Selected video codec: mpeg2video (MPEG-2 video)
[vf] Opening video filter: [yadif]
[yadif] This filter will be replaced by using libavfilter option syntax directly. Parts of the old syntax will stop working, and some defaults may change.
[yadif] Using libavfilter for 'yadif'

**Comment by jaccc** [comment]
It looks like display frequency is slightly below 59.94 Hz. I can try different Modeline if it exists.

Section "Monitor"
        Identifier   "HDMI1"
        Modeline "1920x1080_59"  148.35  1920 2008 2052 2200  1080 1084 1089 1125 +hsync +vsync
        Option "PreferredMode" "1920x1080_59"
EndSection

It looks like mpv is using DRI2 instead DRI3 despite DRI3 seems to enabled.
LIBGL_DEBUG=verbose glxinfo
libGL: Using DRI3 for screen 0

**Comment by jaccc** [comment]
log
[mpv.txt](https://github.com/mpv-player/mpv/files/1188335/mpv.txt)

no change with --opengl-backend=x11

triple buffering is disabled in xorg.conf
Option "TripleBuffer" "false"

**Comment by jaccc** [comment]
found workaround for flicker: interpolation-threshold=0.2
Interpolation can be disabled for 59.94 fps video. 

There is desync despite almost same frequency with interpolation and video-sync=display-vdrop
There is warning with interpolation and without video-sync=display-vdrop:
[vo/opengl] Interpolation now requires enabling display-sync mode.
[vo/opengl] E.g.: --video-sync=display-resample
audio resampling is unacceptable because of distortion

**Comment by kevmitch** [comment]
Does resampling also have this problem? I'm not actually able to reproduce it. What distortion is there when resampling? or are you referring to the audio just not being lossless?

I do recall having issues with interpolation when the output refresh rate was close to the input frame rate, but like I said, no longer see issues even with `--interpolation-threshold=-1`

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
