### ISSUE TITLE
No OSC/OSD/subtitles on FreeBSD with various hardware. With Windows all fine.

### ISSUE THREAD

**Issue by schmied** [mpv-player/mpv#4692]
### mpv version and platform

mpv 0.26.0

ffmpeg library versions:
 libavutil       55.58.100
 libavcodec      57.89.100
 libavformat     57.71.100
 libswscale      4.6.100
 libavfilter     6.82.100
 libswresample   2.7.100
 ffmpeg version: 3.3.2

OS and packages compiled with clang.

On Desktop:
Haswell CPU
GeForce GTX 750 TI
FreeBSD 12.0-CURRENT amd64

On Laptop:
Sandybridge Mobile CPU
On CPU HD Graphics
FreeBSD 12.0-CURRENT amd64

Behaviour observed several weeks, also with mpv version 0.25

If mpv installed as binary package instead of built from source, OSC/OSD is also not displayed.

Running mpv on both computers with Windows all behaviour is as expected.

### Reproduction steps

Play video. Trigger OSC/OSD by moving mouse or seek forward.

### Expected behavior

Display OSC and OSD.

### Actual behavior

OSC and OSD not displayed. However, I can click at the bottom (invisible OSC) and change playing position.

### Log file

Laptop configure log
https://pastebin.com/raw/Pwcviwpc

On Desktop PC configure log should be the same, there are exactly the same packages installed.

**Comment by wiiaboo** [comment]
mpv log-file would probably be useful too.

**Comment by schmied** [comment]
https://pastebin.com/raw/Pwcviwpc

Are these 'run command: expand-text' logs normal?

Thanks!

**Comment by schmied** [comment]
BTW, I also tested with --no-config, but same result not displaying OSC/OSD.

**Comment by schmied** [comment]
I forgot to mention that the OSC seems to be there, but not being displayed. I can click on the 'invisible' OSC and change the plaing position.

**Comment by sCreami** [comment]
Try to reconfigure with luajit instead of lua52fbsd.

**Comment by schmied** [comment]
Just compiled with luajit and verified luajit in the mpv log. No OSC/OSD display with luajit as well. I think I tried this a few weeks ago and it did not help.

**Comment by wiiaboo** [comment]
Do regular subtitles show up?

**Comment by schmied** [comment]
No.
Perhaps it is a bug on the FreeBSD side? They frequently change some graphics stuff to keep track of newer APIs mostly from the linux world.

**Comment by sCreami** [comment]
I may also be an issue with libass or fontconfig.

**Comment by schmied** [comment]
I have a very strict fonts.conf, only allowing Helvetica and Terminal. But all my other applications work.

**Comment by schmied** [comment]
[   0.070][v][osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.4.6 (COMPLEX)
[   0.070][v][osd/libass] Setting up fonts...
[   0.075][v][osd/libass] Using font provider fontconfig
[   0.075][v][osd/libass] Done.
[   4.186][v][osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.4.6 (COMPLEX)
[   4.186][v][osd/libass] Setting up fonts...
[   4.190][v][osd/libass] Using font provider fontconfig
[   4.190][v][osd/libass] Done.

**Comment by sCreami** [comment]
You'd seen the font selected after that. What is printed? Mine looks like this.
````
[   4.231][v][osd/libass] Setting up fonts...
[   4.233][v][osd/libass] Using font provider coretext
[   4.233][v][osd/libass] Done.
[   4.235][v][osd/libass] fontselect: (Open Sans Semibold, 400, 0) -> /Users/alex/Library/Fonts/OpenSans-Semibold.ttf, -1, OpenSans-Semibold
[   4.235][v][osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
````

**Comment by schmied** [comment]
No. I did a 'grep ass' and 'grep font' on my log. I also copied my fonts.conf to ~/.config/mpv/ and did a 'fc-cache -v -r -f', but all without success.

**Comment by sCreami** [comment]
Try to whitelist mpv-osd-symbols-Regular

**Comment by schmied** [comment]
With an empty fonts.conf now everything is displayed, but my fonts look ugly now. So I have to play around with my fonts.conf a bit.

Thank you very much!

BTW I cannot find any installed mpv font on the system.

**Comment by schmied** [comment]
Is it possible that mpv cannot render bitmap fonts?

**Comment by wiiaboo** [comment]
mpv-osd-symbols is a built-in font to render the OSC/OSD symbols, but just that. It doesn't have regular glyphs. Can you use a less strict fonts.conf just for mpv?

**Comment by schmied** [comment]
Arghh, I forgot I can shadow the fonts.conf in .config/mpv/
I copied my original fonts.conf (which force all non-mono fonts to Helvetica) to the mpv directory and replaced Helvetica with DejaVu. Now it works fine and the rest of my applications look like before again.
It seems that mpv or libass or whatever cannot handle bitmap fonts.

Thank you very much again, much appreciated!

**Comment by schmied** [comment]
FYI: If forcing everything to an outline font the OSC is a bit fucked up, but OSC/OSD/subtitles are rendered. If forcing to a bitmap font, nothing gets displayed.

**Comment by wiiaboo** [comment]
Open an issue about bitmap fonts in libass repo then. This issue is not mpv's.
