### ISSUE TITLE
[Request] Hotkey to copy currently displayed subtitles text to clipboard

### ISSUE THREAD

**Issue by hsyong** [mpv-player/mpv#4695]
Is it possible to add a feature (hotkey) to copy the subtitles to clipboard? It would be good for language learners to be able to copy/paste the text to dictionary software or Google Translate.

Thanks!

**Comment by Argon-** [comment]
Via input.conf:
1. OSX: https://github.com/mpv-player/mpv/issues/4653#issuecomment-317411382
2. Windows: https://github.com/mpv-player/mpv/issues/4653#issuecomment-317514725
3. Linux: none posted but should work like OSX with another binary instead of `pbcopy`

Lua code that can cover all systems (needs adjustments): https://github.com/mpv-player/mpv/issues/4653#issuecomment-317411567

**Comment by hsyong** [comment]
First of all, I'm not really a programmer, just a user. But I managed to get it to somehow work by following the example you posted  (thank you!). **It works for English subtitles files. But when I use Japanese subtitles, only "???????" is copied to clipboard.**

---------------------------------
**My lua file, same location as input.conf (inside C:\mpv\portable_config\ ) :**
local function set_clipboard(text)
local res = utils.subprocess({ args = {
'powershell', '-NoProfile', '-Command', string.format([[& {
Trap {
Write-Error -ErrorRecord $_
Exit 1
}
Add-Type -AssemblyName PresentationCore
[System.Windows.Clipboard]::SetText('%s')
}]], text)
} })
end

**Added this to my input.conf:**
Ctrl+x run "cmd.exe" "/d" "/c" "echo ${sub-text}|clip"
--------------------------------

Can it be made to work with texts of other language besides English?

My system: Windows 7 with latest version of MPV.

Thanks!!

**Comment by hsyong** [comment]
Please ignore the previous comment. Seems no need for lua script. I just need to add this line to input.conf:
Ctrl+x run "cmd.exe" "/d" "/c" "echo ${sub-text}|clip"

**But it works only for English subtitles. If I'm using Japanese subtitles, only a series of question marks are copied to clipboard.**

Can it be made to work with texts of other language besides English?

My system: Windows 7 with latest version of MPV.

Thanks!!

**Comment by Argon-** [comment]
Most likely some encoding problem. I'm sure there's a solution but I don't use Windows, can't help you.

**Comment by garoto** [comment]
I did some search and it can be fixed by changing `cmd.exe` codepage to `Unicode` with `chcp 65001` command. That input.conf binding should then read:

```
Ctrl+x run "cmd.exe" "/d" "/c" "@chcp 65001 & @echo ${sub-text}|clip"
```
Seems to work as advertised with japanese chars in my limited testing.

Be aware tho, that the above `run` line won't work with a multi-line sub, because the `CRLF` at the line break, the command line will be split in two:
```
"cmd.exe" /d /c "@chcp 65001 & @echo é o trabalho de antigos humanos
que desenhavam…|clip"
```

Coudn't figure out a workaround.

**Comment by hsyong** [comment]
Just tested and still shows ?????? on my Win 7 laptop.

Anyway, after looking at the posted links/samples above for a couple of days I tried a different method and managed to create a script that seems to work. I created my own lua file and placed it in the scripts folder (C:\mpv\portable_config\scripts\getsub.lua).

This is the complete code in the lua script file with hotkey to send current subtitles to clipboard. Tested and seems to work well with Japanese and English subs:
----------------------------------------
utils = require 'mp.utils'

local function set_clipboard()
    local res = utils.subprocess({ args = {
        'powershell', '-NoProfile', '-Command', string.format([[& {
            Trap {
                Write-Error -ErrorRecord $_
                Exit 1
            }
            Add-Type -AssemblyName PresentationCore
            [System.Windows.Clipboard]::SetText('%s')
        }]], mp.get_property("sub-text"))
    } })
end

mp.add_key_binding("Ctrl+x", "set_clipboard", set_clipboard)

---------------------

Requires Powershell 3.0 (default in WIn 8 and Win 10). Win 7 user possibly need to update from Powershell 2.0.

**PS: As I'm not really a programmer I'd appreciate if someone/anyone can just look at the code and see if anything is inappropriate. Thanks!**

**Comment by haasn** [comment]
@hsyong Seems like it would break on subtitle lines that contain a `'` character.

**Comment by hsyong** [comment]
@haasn Yes, you are right. I have been wondering for a few days why it won't work sometimes (nothing seems to be copied to clipboard even when there is subtitle on the screen).

Now you have mention it, any lines with the character ' will not be copied.

**Other than this little issu, MPV seems to be working fine. Will it cause any problem to the functioning of MPV?
Do you know the cause/explanation or solution to this?**

Thank you!

**Comment by hsyong** [comment]
@haasn  I searched the web and found a replace function and all I can think of is to just replace ' with nothing (delete). Adding an escape backslash doesn't work.

Removing the ' is not pretty but it works for me. Any better idea?
-------------------------------------------------------------
utils = require 'mp.utils'

local function set_clipboard()
	**local subtext = mp.get_property("sub-text")
	subtext = string.gsub(subtext, "'", "")**
	
    local res = utils.subprocess({ args = {
        'powershell', '-NoProfile', '-Command', string.format([[& {
            Trap {
                Write-Error -ErrorRecord $_
                Exit 1
            }
            Add-Type -AssemblyName PresentationCore
            [System.Windows.Clipboard]::SetText('%s')
        }]], subtext)
    } })
end

mp.add_key_binding("Ctrl+x", "set_clipboard", set_clipboard)
-------------------------------------------------------------

**Comment by garoto** [comment]
What about double quotes around the `%s` argument? e.g. `SetText("%s")`

**Comment by hsyong** [comment]
@garoto Interesting, now it works with subtitles with ' character but doesn't work with subtitles text with " character. Thank you.

**Comment by garoto** [comment]
Hah, bummer :|

**Comment by hsyong** [comment]
@garoto So now I use your method and also replace double-quote with single-quote in the subtitles. Still not good but looks better than removing the ' character.

*******************
utils = require 'mp.utils'

local function set_clipboard()
	**local subtext = string.gsub(mp.get_property("sub-text"), "\"", "'")**
	
    local res = utils.subprocess({ args = {
        'powershell', '-NoProfile', '-Command', string.format([[& {
            Trap {
                Write-Error -ErrorRecord $_
                Exit 1
            }
            Add-Type -AssemblyName PresentationCore
            [System.Windows.Clipboard]::SetText("%s")
        }]], subtext)
    } })
end

mp.add_key_binding("Ctrl+x", "set_clipboard", set_clipboard)

*******************

**Comment by archenemies** [comment]
For Linux:

    $ tail -n 1 ~/.mpv/input.conf
    Ctrl+x run "/bin/sh" "-c" "echo ${sub-text} | xsel -b"

**Comment by mossaybo** [comment]
### **Linux:** 
(needs xclip to be installed)
add the following to ~/.config/mpv/input.conf
`Ctrl+c run "/bin/bash" "-c" "echo ${sub-text} | xclip -selection clipboard"`

**Comment by fxmarty** [comment]
@mossaybo Thank you. However this solution does not work for subtitles on several lines (clipboard is empty), do you have an idea how to deal with them?

**Comment by varenc** [comment]
### Security Warning
For most of these subtitle->clipboard commands, be wary that it's possible for some malicious subtitles to execute arbitrary code if you're not escaping everything perfectly.  That's a pretty unlikely scenario of course.

Now that that's out of the way... on macOS, this command bound to "⌥+s" works well for me:
`Meta+s run "/bin/sh" "-c" "echo '${sub-text}' | tr '\n' ' ' | pbcopy"; show-text "Subtitle copied"`

This works for multiline subs and the `tr` util replaces line breaks with just a single space. 


But since I don't escape quotes, a malicious subtitle could inject arbitrary code.  Here's an example of a malicious srt file:
```
1
00:00:01,000 --> 05:00:00,000
Normal subtitle...{\an7}{\fs1} muahah' > /dev/null; touch /tmp/h4x0red; /usr/bin/say 'you are hacked like its 2002';#
```

If I ran my copy subs command after loading that subtitle, it'll then lead to arbitrary code execution. In this case creating a /tmp/h4x0red file and on macOS, speaking a message aloud with the `say` command.  And as a user, you'll probably only see "Normal subtitle..."  on screen since the ASS formatting tags set the malicious text to a near invisible font size 1. Someone could append that malicious snippet after every subtitle on a genuine .srt file, and you might not even see the malicious snippet appear on screen. 

Forunatenly I don't think this attack vector is really on anyone's radar...yet! 🙃

**Comment by GunGunGun** [comment]
@varenc One more reason for built-in clipboard util func +1
I think we need this feature because using xclip/powershell to copy is incredibly slow, hacky, and buggy, unsafety.

**Comment by varenc** [comment]
Agreed!  No idea what built in pasteboard support would entail though.  I'm naively hopeful that behavior is similar enough between platforms that it'd be simple to support this.  Especially if the scope was just limited to copying text into the pasteboard.

**Comment by garoto** [comment]
Chances of a multiplatform clipboard command being implemented in the nearby future:  zero.

**Comment by JayXT** [comment]
> ### **Linux:**
> 
> (needs xclip to be installed) add the following to ~/.config/mpv/input.conf `Ctrl+c run "/bin/bash" "-c" "echo ${sub-text} | xclip -selection clipboard"`
> 
> Edit: **USE THIS CODE INSTEAD** it will work for multi lines subs `Ctrl+c run "/bin/bash" "-c" "echo \"${sub-text}\" | xclip -selection clipboard"`

It looks like this might have some issues on Wayland. At least, I didn't work in my case (Debian 12 GNOME).

**Comment by guidocella** [comment]
On Wayland you install `wl-clipboard` and bind `run wl-copy -- ${sub-text}`.

**Comment by JayXT** [comment]
@guidocella, I've tried both `y run wl-copy -- ${sub-text}` and `y run "/bin/bash" "-c" "wl-copy -- $sub-text"`, but both didn't work for some reason.

**Comment by guidocella** [comment]
Did you install wl-copy?

**Comment by JayXT** [comment]
@guidocella , yes, more specifically, I've installed wl-clipboard and ensured that variations of wl-copy command work when used in terminal.

**Comment by guidocella** [comment]
Does y log any error in the \` console, or by starting mpv from the terminal?

**Comment by JayXT** [comment]
@guidocella , in this case each time I press "y" the following log message is written:
`(Paused) AV: 00:01:11 / 00:24:20 (5%) A-V: 0.000`

**Comment by JayXT** [comment]
@na-na-hi , @guidocella, I've decided to to tackle the problem from a different standpoint and started to investigate various scripts created by community. Especially useful one is the following: https://github.com/rofe33/mpv-copyStuff/blob/master/copyStuff.lua.

Based on its analysis I've created a simplified version only for subtitle copying. Here how it looks like:

```
require 'mp'
require 'mp.msg'

-- Copy Currently Displayed Subtitle
local function copySubtitle()
    local subtitle = string.format("%s", mp.get_property_osd("sub-text"))

    if subtitle == "" then
        mp.osd_message("There are no displayed subtitles to copy.")
        return
    end

   local pipe = io.popen("wl-copy", "w")
   pipe:write(subtitle)
   pipe:close()
   mp.osd_message("The displayed subtitle is copied to clipboard.")
   
end

-- Key-Bindings
mp.add_key_binding("y", "copySubtitle", copySubtitle)
```

It's enough to disable mapping for "y" in your input conf (if there is such mapping), put the script into mpv's scripts directory and then start/restart the application. 

It worked fine in GNOME as well, so I hope the solution will help others and save some precious time.

**Comment by FedirVolkov** [comment]
> ```
> Ctrl+x run "cmd.exe" "/d" "/c" "@chcp 65001 & @echo ${sub-text}|clip"
> ```

Hello. Is it possible to trigger this comand by clicking on that subtitle line instead of keyboard hotkey? I'm using Windows tablet, mainly with touchscreen input.
