### ISSUE TITLE
mpv stuck playing files on bluetooth headset

### ISSUE THREAD

**Issue by easy-easy** [mpv-player/mpv#4697]
### mpv version and platform

mpv 0.26.0, archlinux

### Reproduction steps

I use an bluetooth-headset using [bluez-alsa](https://github.com/Arkq/bluez-alsa) because I do not use pulseaudio. On some mp3-files mpv is stuck on playing. It startet but does not play anything. This is reproductible. Here is my .asoundrc:

pcm.sndcard {
	type hw
	card PCH
}

pcm.!default {
  type plug
  slave.pcm {
    @func getenv
    vars [ ALSAPCM ]
    default "pcm.dmix" #cm.smix" #pcm.smix is a dmix/dsnoop full duplex pcm plugged to the main hardware card.
  }
  hint {
    show on
    description "Default ALSA Output"
  }
}

pcm.bths {
  type bluealsa
  interface "hci0"
  device "20:16:03:17:2D:31"
  profile "a2dp"
  delay 10000
}

command for mpv:

ALSAPCM=bths mpv --no-config ppap.mp3
Playing: ppap.mp3
 (+) Audio --aid=1 (mp3 2ch 48000Hz)
AO: [alsa] 48000Hz stereo 2ch s16

here mpv looks like hang in a loop or waiting on something, occurs every time with this file. mplayer has no problem to play it:

ALSAPCM=bths mplayer ppap.mp3 
MPlayer SVN-r37916 (C) 2000-2017 MPlayer Team
225 audio & 460 video codecs
do_connect: could not connect to socket
connect: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing ppap.mp3.
libavformat version 57.71.100 (external)
Mismatching header version 57.56.101
Audio only file format detected.
Load subtitles in ./
==========================================================================
Opening audio decoder: [mpg123] MPEG 1.0/2.0/2.5 layers I, II, III
AUDIO: 48000 Hz, 2 ch, s16le, 192.0 kbit/12.50% (ratio: 24000->192000)
Selected audio codec: [mpg123] afm: mpg123 (MPEG 1.0/2.0/2.5 layers I, II, III)
==========================================================================
[AO OSS] audio_setup: Can't open audio device /dev/dsp: No such file or directory
AO: [alsa] 48000Hz 2ch s16le (2 bytes per sample)
Video: no video
Starting playback...
A:  28.3 (28.2) of 154.0 (02:34.0)  0.5% 

I can provide the mp3 if needed.

### Expected behavior

playing the file

### Actual behavior

stuck after started.

### Log file

https://pastebin.com/w3A3j6zq

### Sample files

https://0x0.st/kQl.mp3

**Comment by lachs0r** [comment]
That sounds terribly unreliable given libasound’s inability to even cope with disappearing devices at runtime. I’m afraid Bluetooth is one of those areas where PulseAudio is actually much better than ALSA (both on the sending and the receiving end). Might be working with MPlayer and other applications by pure chance.

Also, it’s hard to test without access to such BT hardware.

Maybe wrap the BT device in a dmix PCM? Should give mpv more stable buffering to work with.

**Comment by lachs0r** [comment]
I’ve thought about this for a while and I’ve come to the conclusion that trying to work around the issues with this plugin is not worth it. I have very good reasons to use ALSA and avoid PulseAudio like the plague myself (despite libasound being such a clusterfuck), but when it comes to Bluetooth audio, I consider PA the only working solution on Linux.

I also have no way to debug this, and I’m not sure if any other mpv developer has the time and hardware to do so. So don’t hold your breath, this isn’t likely to get fixed anytime soon.

**Comment by easy-easy** [comment]
Well, that's sad to hear, but I understand you. Just wondered why it works with mplayer and not with mpv.. This is btw. stuck on the most mp3 files and streams the case.. As long as mplayer works, no problem. ;) Thanks for mpv anyway. Great peace of software.

Regards, easy.

**Comment by lachs0r** [comment]
Someone else has been looking into this for a bit (don’t know if he’s come to any meaningful conclusion yet) but it’s definitely a bug in libasound and/or that bluez pcm module and he’s been able to reproduce it with aplay. Closing.

(Note that mpv makes use of some newer APIs compared to MPlayer, which explains the difference in behavior.)
