### ISSUE TITLE
[Question] loadfile .. append-play

### ISSUE THREAD

**Issue by pennyscan** [mpv-player/mpv#4700]
windows 10

is there a way to make....
echo loadfile song.mp3 append-play > \.\pipe\mpvsocket

work with filenames like...

song × ÷ ≠ ≥ ≈ π.mp3

**Comment by pennyscan** [comment]
I've tried normal double quotes i.e "filename.mp3"  but mpv did not respond

**Comment by wm4** [comment]
Use json and something that correctly converts strings to json literals.
