### ISSUE TITLE
Can fonts be portable in windows？

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#4701]
### mpv version and platform

mpv 0.26.0 windows 64bits build from
https://mpv.srsfckn.biz/

Can mpv use --sub-font= or --osd-font=
to specify a file subfont.ttf which put in the directory of mpv?

I want the mpv can portable so i want to the subfont.ttf don't need to install
but can put together with mpv and i can use command or mpv.conf to specify the font.

I use mplayer before from
http://oss.netfarm.it/mplayer/

and it's can put a subfont.ttf to dir "mplayer" to tell mplayer use the font.

**Comment by lachs0r** [comment]
By default, mpv will check these directories for subfont.ttf (this also shows up in `-v` output):

`%APPDATA%\mpv\subfont.ttf`
`<mpv directory>\subfont.ttf`
`<mpv directory>\mpv\subfont.ttf`

**Comment by kesdoputr** [comment]
sorry, i put a subfont.ttf into my mpv directory

but it seems not work,may i add some option or command?

2017-08-01 19:06 GMT+08:00 Martin Herkt <notifications@github.com>:

**Comment by kesdoputr** [comment]
ok i know,put subfont.ttf in fonts directory and usd --osd-font

to specify font name is work,thx for your reply.

2017-08-01 20:15 GMT+08:00 kesdoputr wang <kesdoputr@gmail.com>:
