### ISSUE TITLE
mpv not play this Multimedia file。

### ISSUE THREAD

**Issue by zyb920** [mpv-player/mpv#4704]
Original address( the problem closed )：
https://github.com/mpv-player/mpv/issues/4643#issuecomment-319577067

I have a Multimedia file，mpv is not play。
other player can play，
I want to send this multimedia file to you. I don't know how to send it。

I uploaded this file through https://mixtape.moe/

Page information：
Help Fund Us — We depend on donations to pay for servers. To donate, go to our Donate page.
mixtape.moe
Mixtape.moe
Drop Your Fire, Fam
Upload and share any file up to 100MB

4618 files uploaded today
Select or drop your file(s)
record from mic

featherhead.mp4  my.mixtape.moe/wdmlly.mp4
Done!

Blog Terms Privacy Report Transparency Tools

click my.mixtape.moe/wdmlly.mp4   join https://track5.mixtape.moe/wdmlly.mp4

I don't know  this  file  has  been uploaded successfully.

**Comment by lachs0r** [comment]
I’ve reopened the original issue.
