### ISSUE TITLE
[Question] play, pause and unpause

### ISSUE THREAD

**Issue by pennyscan** [mpv-player/mpv#4705]
With video, I can trick the player into pause mode  and play mode using the . Key (frame step)

. = pause
Space = play

So I always know The true play state without guessing mpv pause/play cycle

But this does not work with mp3 files (no frame)

Is there any command that can force play (unpause) or force pause

**Comment by wiiaboo** [comment]
```
<somekey> set pause no
<otherkey> set pause yes
```

**Comment by pennyscan** [comment]
Thank you, I'll need to read the manual more carefully.
