### ISSUE TITLE
Add opportunity to compile mpv without xscrnsaver

### ISSUE THREAD

**Issue by teod0r** [mpv-player/mpv#4706]
Can't compile mpv without xscrnsaver! I don't need any screensavers!

**Comment by fhlfibh** [comment]
https://github.com/mpv-player/mpv/issues/4404

**Comment by mc4man** [comment]
what makes you think xscrnsaver,h (libxss*) has anything to do with whether screensavers are installed/used or not?

**Comment by haasn** [comment]
@mc4man he's probably some arch linux user who thinks saving 10 kB is going to keep his system free from “bloat”

**Comment by timofonic** [comment]
@haasn I'm an Arch Linux user and I don't think that way.

What would be quite extreme is an Alpine Linux desktop user :D
