### ISSUE TITLE
Problems about geometry and no keyframe

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#4707]
### mpv version and platform

mpv 0.26.0 windows 64bits build from
https://mpv.srsfckn.biz/

### Reproduction steps
I set geometry=50%:50% in mpv.conf，and play a playlist with two file
which file01.mp4 is 320x240,file02.mp4 is 720x480
when i use windows mode i switch from two files the window is on the center of screen
but when i play file like below:
1.play file01,mp4 in fullscreen mode
2.switch to file02.mp4
3.back to window mode
4.now the window is not on the center of screen

### Expected behavior
When i back from fullscreen to window,it should be still on the center of screen.

### Actual behavior
If files have same resolution it's all ok.But when files have different resolution,when i back from
fullscreen to window,the window's position is base on the first window's top-left corner

And i have another question,i play a file and mpv can't play and give a message below:
**[ffmpeg/video]  warning: first frame is no keyframe**
And i can use mplayer to play the same file.
I find in man page to see if there is a option to skip but not found.
The sample file is below:
https://srv07.bitsend.jp/download/6ca421a1460ad631d7c48749f193b263.html

**Comment by wm4** [comment]
Not sure, but I think --force-window-position does what you want. Depends on whether your window manager cooperates.

**Comment by kesdoputr** [comment]
I have try to use force-window-position but no use.
When i play diffrent resolution video in window mode,it's work.
But when i change to fullscreen,swtich video and back to windo mode
The window is not in center like i set in mpv.conf geometry=50%:50%.

And how can i solve the second problem?I think the video sample have some problem
but i can play it with mplayer,can mpv skip the error and play it?
