### ISSUE TITLE
mpv master breaks when using RAVU

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#4708]
### mpv version and platform

The first bad commit is 53188a14b

### Reproduction steps

Use mpv with `--opengl-shader=`[ravu-r3.hook](https://github.com/bjin/mpv-prescalers/blob/master/ravu-r3.hook).

### Expected behavior

RAVU shader gets applied, as before.

### Actual behavior

```[vo/opengl] Unrecognized FORMAT description: 'f'!```

### Log file

https://0x0.st/kYl.txt

### Sample files

https://0x0.st/kYU.hook

Any file triggers the issue.

**Comment by wm4** [comment]
The fix breaks all existing user shaders with custom textures, even those that still worked. The "FORMAT" line needs to be adjusted, and "COMPONENTS" goes away.

CC @bjin @igv
