### ISSUE TITLE
mpv-git @ 56742ec - [vo/opengl] after rendering: OpenGL error INVALID_OPERATION.

### ISSUE THREAD

**Issue by Coacher** [mpv-player/mpv#4717]
### mpv version and platform

mpv 56742ec-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Aug  5 18:47:08 MSK 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.3

OS Gentoo amd64.

### Reproduction steps

Play this video: http://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_surround.avi

### Expected behavior

Video is played without any warnings/errors.

### Actual behavior

Video is played, but there is `[vo/opengl] after rendering: OpenGL error INVALID_OPERATION` message.

### Log file

https://paste.pound-python.org/show/V2Fu26OnEWFR7A6LRv0R/

### Additional info

This error doesn't happen with 0389852.

**Comment by haasn** [comment]
Can you post another log using `--opengl-debug` as well?

**Comment by Coacher** [comment]
https://paste.pound-python.org/show/V3ez2evAQOWK71gVl1sE/

**Comment by bjin** [comment]
I noticed the same error, setup is `Mesa 17.1.5` with `Intel HD 4000`, Linux.
First bad commit is 333cae74ef0fa62e0355e85d21f0f41ced3963e7
This message seems to be printed after every new shader is compiled/generated, but nothing suspicious in log even with `msg-level=vo=trace --opengl-debug`.

**Comment by haasn** [comment]
Is it possible you could capture an `apitrace` and upload it (or a log)?

**Comment by bjin** [comment]
apitrace for last good commit: https://0x0.st/dXy.trace
first bad commit: https://0x0.st/dXt.trace
mpv invoked with `--pause` and then quit

**Comment by bjin** [comment]
Not sure why only the setup gl calls are captured even with `--verbose`, here is trace file captured with `egl` backend.
first bad: https://0x0.st/dXY.trace
last good: https://0x0.st/dX3.trace

**Comment by haasn** [comment]
I noticed the presence of these two calls in the `bad` trace:

```
+glGetProgramiv(program = 13, pname = GL_PROGRAM_BINARY_LENGTH, params = &0)
+glGetProgramBinary(program = 13, bufSize = 0, length = &0, binaryFormat = &GL_ZERO, binary = 0x7f2c90b10ba4)
```

Maybe that has something to do with it? Is it possible that you could replay the trace and figure out exactly which instruction triggers the error?

**Comment by bjin** [comment]
I'm not able to replay the trace file either, which seems to require OpenGL 4.4.

The diff immediately before we get `GL_INVALID_OPERATION` is like.  Is it something about the order of `glUseProgram` and `glEndQuery`?

~~~
glBindFramebuffer(GL_FRAMEBUFFER, 0)                            glBindFramebuffer(GL_FRAMEBUFFER, 0)
                                                           >    glEndQuery(GL_TIME_ELAPSED)
                                                           >    glUseProgram(0)
glActiveTexture(GL_TEXTURE1)                                    glActiveTexture(GL_TEXTURE1)
glBindTexture(GL_TEXTURE_2D, 0)                                 glBindTexture(GL_TEXTURE_2D, 0)
glActiveTexture(GL_TEXTURE2)                                    glActiveTexture(GL_TEXTURE2)
glBindTexture(GL_TEXTURE_2D, 0)                                 glBindTexture(GL_TEXTURE_2D, 0)
glActiveTexture(GL_TEXTURE0)                                    glActiveTexture(GL_TEXTURE0)
glUseProgram(0)                                            <
glEndQuery(GL_TIME_ELAPSED)                                <
glGetError() = GL_INVALID_OPERATION                        <
~~~

**Comment by haasn** [comment]
Well the problem with glGetError is that it just reports an error in the entire previous block since the last glGetError (or in this case, since the beginning of the program, apparently). That's why replaying the trace would be so useful - since it basically does glGetError after every single call. I mean you could try and disable GL_TIME_ELAPSED queries but I doubt it would make any difference.

You could also try inserting more `debug_check_gl` calls, one after each line, to try and narrow it down more.

**Comment by bjin** [comment]
Added a few calls, the `GetProgramBinary` [call](https://github.com/mpv-player/mpv/blob/333cae74ef0fa62e0355e85d21f0f41ced3963e7/video/out/opengl/ra_gl.c#L642) in `ra_gl.c` triggered the error.

**Comment by haasn** [comment]
I just saw that bufSize = 0, which seems to violate API usage.

**Comment by haasn** [comment]
Huh, actually I get INVALID_USAGE errors when running through apitrace as well, but only through apitrace:

```
[vo/opengl] GL: GL_INVALID_OPERATION error generated. <program> binary is too large to fit into <bufSize>
[vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
```

**Comment by CounterPillow** [comment]
@haasn you might want to replace all glGetError calls (which force a sync between GPU and CPU, which can kill performance) with the OpenGL debug log callback functionality, which also allows you to [scope messages](https://www.khronos.org/opengl/wiki/Debug_Output#Scoping_messages) so you roughly know which area they came from.

**Comment by haasn** [comment]
> EDIT: oh lol it's OpenGL 4.3+ so I guess you can't make this the default, thanks Apple.

Well to be honest, we can still break non-essential features on Apple. Debug callbacks are not essential.

**Comment by haasn** [comment]
We could also probably just get rid of OSD timestamp queries altogether and require non-reentrant usage of ra_timer. I just sort of wanted to keep them there because I know there are test clips trying to display stupidly large OSD textures (in particular on 4K monitors) which can take quite a noticeably amount of time to upload and render. So getting rid of them would represent a downgrade in functionality.

**Comment by wm4** [comment]
> Huh, actually I get INVALID_USAGE errors when running through apitrace as well, but only through apitrace:

We now always retrieve the shader binary, if the extension is present. It's a consequence of our overly generic ra interface. We could probably fix it later, if we really care.

Anyway, the error seems that GL_PROGRAM_BINARY_LENGTH returns 0, and we still try to read the program anyway.

The manpages seem to indicate that this is allowed only if compilation failed though?

> When a progam's GL_LINK_STATUS is GL_FALSE, its program binary length is zero. 

Anyway, made a potential fix to git master.

**Comment by Coacher** [comment]
0b10a07 fixes the issue for me. Thanks.

**Comment by Akemi** [comment]
same here on macOS.

**Comment by pc00per** [comment]
I'm getting the same issue on nvdec.

**Comment by CounterPillow** [comment]
@pc00per  no you're not, this issue is from 2017 and has been fixed. Open a new issue
