### ISSUE TITLE
How to reload config file?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4718]
Hi,

Is there any key-binding command to reload the `config` file when mpv is running in idle state?

Regards,
Alex

**Comment by wiiaboo** [comment]
No. You have to restart mpv.

**Comment by fhlfibh** [comment]
It's a pity...

**Comment by wm4** [comment]
Well, libmpv can load a config file at runtime, so in theory it would be possible. But since you can't reset the _old_ values to before the file was loaded, it would be pretty useless/confusing anyway.

**Comment by vanbang9710** [comment]
Maybe a [keybind to call a cmd.exe](https://www.reddit.com/r/mpv/comments/vc2mvc/restart_mpv_with_keybinding/) is the solution

**Comment by KonoVitoDa** [comment]
> Maybe a [keybind to call a cmd.exe](https://www.reddit.com/r/mpv/comments/vc2mvc/restart_mpv_with_keybinding/) is the solution

It is, but how to make it also work with images and links? With this command the images are open with the default image viewer, and the links on the browser.
