### ISSUE TITLE
Stretched image when blitting from p->output_fbo

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#4719]
### mpv version and platform

333cae74ef is the first bad commit.

### Reproduction steps

1. `mpv --no-config --video-sync=display-resample --blend-subtitles=yes` on a <60 Hz file; or some other way of forcing the use of p->output_fbo
2. Switch between fullscreen and back, or resize the video some other way

### Expected behavior

Renders as before

### Actual behavior

Image drawn into p->output_fbo is weird/stretched (wrong aspect ratio); parts are left over from before, etc.

### Log file

https://0x0.st/doJ.txt

### Notes

1. Removing use of `FBOTEX_FUZZY` works around the problem
2. Removing use of `p->output_fbo` works around the problem
3. This patch seems to solve the problem

```c
diff --git a/video/out/opengl/osd.c b/video/out/opengl/osd.c
index a656451c2e..b80892169e 100644
--- a/video/out/opengl/osd.c
+++ b/video/out/opengl/osd.c
@@ -309,7 +309,7 @@ void mpgl_osd_draw_finish(struct mpgl_osd *ctx, int vp_w, int vp_h, int index,
     const int *factors = &blend_factors[part->format][0];
     gl_sc_blend(sc, factors[0], factors[1], factors[2], factors[3]);
 
-    gl_sc_dispatch_draw(sc, target, part->vertices, part->num_vertices);
+    gl_sc_dispatch_draw(sc, vp_w, vp_h, target, part->vertices, part->num_vertices);
 }
 
 static void set_res(struct mpgl_osd *ctx, struct mp_osd_res res, int stereo_mode)
diff --git a/video/out/opengl/shader_cache.c b/video/out/opengl/shader_cache.c
index 68d9d4cab2..772e7bc8b5 100644
--- a/video/out/opengl/shader_cache.c
+++ b/video/out/opengl/shader_cache.c
@@ -717,6 +717,7 @@ static void gl_sc_generate(struct gl_shader_cache *sc, enum ra_renderpass_type t
 }
 
 struct mp_pass_perf gl_sc_dispatch_draw(struct gl_shader_cache *sc,
+                                        int vp_w, int vp_h,
                                         struct ra_tex *target,
                                         void *ptr, size_t num)
 {
@@ -728,7 +729,7 @@ struct mp_pass_perf gl_sc_dispatch_draw(struct gl_shader_cache *sc,
 
     timer = sc->current_shader->timer;
 
-    struct mp_rect full_rc = {0, 0, target->params.w, target->params.h};
+    struct mp_rect vp = {0, 0, vp_w, abs(vp_h)};
 
     struct ra_renderpass_run_params run = {
         .pass = sc->current_shader->pass,
@@ -737,8 +738,8 @@ struct mp_pass_perf gl_sc_dispatch_draw(struct gl_shader_cache *sc,
         .target = target,
         .vertex_data = ptr,
         .vertex_count = num,
-        .viewport = full_rc,
-        .scissors = full_rc,
+        .viewport = vp,
+        .scissors = vp,
     };
 
     timer_pool_start(timer);
diff --git a/video/out/opengl/shader_cache.h b/video/out/opengl/shader_cache.h
index c4fcefc391..bcdf8d87e8 100644
--- a/video/out/opengl/shader_cache.h
+++ b/video/out/opengl/shader_cache.h
@@ -46,6 +46,7 @@ void gl_sc_blend(struct gl_shader_cache *sc,
                  enum ra_blend blend_dst_alpha);
 void gl_sc_enable_extension(struct gl_shader_cache *sc, char *name);
 struct mp_pass_perf gl_sc_dispatch_draw(struct gl_shader_cache *sc,
+                                        int vp_w, int vp_h,
                                         struct ra_tex *target,
                                         void *ptr, size_t num);
 struct mp_pass_perf gl_sc_dispatch_compute(struct gl_shader_cache *sc,
diff --git a/video/out/opengl/video.c b/video/out/opengl/video.c
index b3922f50d1..7aca8ca4ff 100644
--- a/video/out/opengl/video.c
+++ b/video/out/opengl/video.c
@@ -1197,7 +1197,7 @@ static struct mp_pass_perf render_pass_quad(struct gl_video *p, int vp_w, int vp
     va[4] = va[2];
     va[5] = va[1];
 
-    return gl_sc_dispatch_draw(p->sc, target, va, 6);
+    return gl_sc_dispatch_draw(p->sc, vp_w, vp_h, target, va, 6);
 }
 
 static void finish_pass_direct(struct gl_video *p, struct ra_tex *target,
```

I have no idea if this is the proper/correct fix, though - especially since `finish_pass_fbo` seems to pass the real FBO size (not the “logical” FBO size) as the vp_w/vp_h to finish_pass_direct, which makes no sense to me. Maybe I'm missing something else.

**Comment by haasn** [comment]
Also what strikes me as odd is that FUZZY textures work fine for the other draw passes, it just breaks on the final output pass (for some reason). Even the `interpolation` pass works correctly.

**Comment by haasn** [comment]
Also I was thinking that instead of this complicated raytracing business, we could instead generate a real polygonal model of a 3D sphere and map it to the right texture coordinates using equirectangular projection, then use a “traditional” camera projection matrix to map this into the plan. (Maybe we could use a geometry shader for this? :p)

At least that could be a starting point; optimizing away the actual geometry could be done as a separate step, but that would rely on figuring out how to “reverse” this calculation.

**Comment by wm4** [comment]
Normally the viewport should match the size of the underlying textures (so our vertex coordinates map to pixels). Strange.

**Comment by wm4** [comment]
Fairly sure it's because pass_draw_to_screen() assumes the fbo is always the framebuffer and uses p->vp_w/h for the size.

**Comment by haasn** [comment]
> Normally the viewport should match the size of the underlying textures (so our vertex coordinates map to pixels). Strange.

No, the problem is the FUZZY texture - which make the *real* texture size larger than the *logical* texture size. So the code computing the viewpoint needs to know about the logical fbotex size.
