### ISSUE TITLE
Add support for nicovideo danmaku “subtitles”

### ISSUE THREAD

**Issue by linkmauve** [mpv-player/mpv#4722]
### mpv version and platform
master, revision 2b83f7e391ab68b23602e89b97ebc07ca09d8e7c.

### Reproduction steps
`mpv http://embed.nicovideo.jp/watch/sm10215922`

### Expected behavior
All of the [danmaku](http://danmaku.weebly.com/) should be played.

### Actual behavior
Only the video and audio are played.

### Log file
N/A

### Sample files
N/A

**Comment by wiiaboo** [comment]
Out-of-scope.
https://github.com/abyssonym/danmaku-play
https://github.com/m13253/danmaku2ass

**Comment by wiiaboo** [comment]
Also, duplicate of https://github.com/mpv-player/mpv/issues/1974.

**Comment by linkmauve** [comment]
Doesn’t seem to be a duplicate of this one, nicovideo videos otherwise work.

**Comment by wiiaboo** [comment]
> Doesn’t seem to be a duplicate of this one, nicovideo videos otherwise work.

I guess.

> Maybe it should be implemented in youtube-dl to avoid yet another dependency?

Go ahead. I don't see any issues or requests about it.
