### ISSUE TITLE
build instructions for iOS ?

### ISSUE THREAD

**Issue by skrew** [mpv-player/mpv#4723]
Hi,

It's look like this (very nice) project are iOS compliant.

I try to build on a mac with xCode installed but i got some logs like:

```
Checking for AudioUnit output for iOS                             : no 
Checking for iOS OpenGL ES hardware decoding interop support      : no 
```

Any chance to get a wiki or some tips to build libmpv for iOS ?

Thanks.

**Comment by Argon-** [comment]
Do you have the latest version? https://github.com/mpv-player/mpv/pull/4685

**Comment by skrew** [comment]
Yes, the last version (from git clone).

Playing a bit, i can pass the configure and build, but the iOS objective-c sample don't works:
`libmpv does not have the opengl-cb sub-API.`

configure give me:
```
Checking for libavcodec videotoolbox hwaccel (new API)               : no 
Checking for libavcodec videotoolbox hwaccel (old API)               : no 
Checking for libavcodec videotoolbox hwaccel                         : not found any of videotoolbox-hwaccel-old, videotoolbox-hwaccel-new 
Checking for Videotoolbox with OpenGL                                : videotoolbox-hwaccel, gl-cocoa not found 
```

The problem (i think) is waf get local (macos) ffmpeg build (via `pkg-config`) and i don't know how to force using my cross-compiled version.
-I / -L has not effect.

**Comment by skrew** [comment]
Some steps, but still not success...

```
Checking for libavcodec videotoolbox hwaccel (new API)               : no 
Checking for libavcodec videotoolbox hwaccel (old API)               : yes 
Checking for libavcodec videotoolbox hwaccel                         : yes 
Checking for Videotoolbox with OpenGL                                : gl-cocoa not found 
```

Now, in the obj-c sample, `mpv_get_sub_api`check pass but in 
`mpv_opengl_cb_init_gl` : `gl init has failed.`

**Comment by skrew** [comment]
It's me, again...

All works fine but building for simulator don't works.

When i use -arch=arm64 it works, but with arch=x86_64 i got `Unable to find either POSIX or MinGW-w64 environment, or compiler does not work.`

**Comment by coreyjv** [comment]
@skrew -- I'd like to do something similar but instead of build for iOS I'd like to build for tvOS. Would you happen to have instructions / commands you used to build this on iOS?

Thanks!

**Comment by arekf** [comment]
@byMohamedali I was recently using this fork and was able to build successfully, you may want to try it:
https://github.com/qoli/mpv-ios-scripts

**Comment by byMohamedali** [comment]
Thank you i try that now 😄
