### ISSUE TITLE
Want to start mpv in a default window size and position

### ISSUE THREAD

**Issue by c769214** [mpv-player/mpv#4724]
### mpv version 0.23

I would like to startup mpv in a default windows size (regardless of the media resolution) and a fixed position (eg: 0,0 or 123,400) 

Any method to achieve this?

Thanks a lot ! 

Using Ubuntu 14.04 Linux version

**Comment by rossy** [comment]
Check out the [--geometry][1] option.

[1]: https://mpv.io/manual/master/#options-geometry
