### ISSUE TITLE
Fullscreen/OSD glitches (on Windows)

### ISSUE THREAD

**Issue by xnoreq** [mpv-player/mpv#4732]
### mpv version and platform
mpv 0.26.0

### Reproduction steps
With `opengl-backend=dxinterop`
`hwdec=dxva2-copy`
or with `hwdec=d3d11va-copy`
`opengl-backend=angle`

Switching to/from fullscreen causes some annoying **flickering** during the transition (only with dxinterop/dxva2-copy). 
Additionally, if I open a video (on the main monitor), drag it to the second monitor and go in and out of fullscreen mode, part of the desktop **wallpaper** is left in a **corrupted** state showing parts of the video frame before leaving fullscreen mode.

Also, for example with the following config:
`vf-add="@saturate1:!lavfi=[eq=saturation=1.4843]"`
`vf-add="@saturate2:!lavfi=[eq=saturation=1.2127]"`

and the following input.conf:
`n vf toggle @saturate1`

Pressing n a few times and switching to/from fullscreen mode results in the following **glitch**:

![grafik](https://user-images.githubusercontent.com/4028859/29046592-7110252c-7bc8-11e7-9a4c-f1a981030468.png)

![grafik](https://user-images.githubusercontent.com/4028859/29046626-9951042a-7bc8-11e7-85ac-11db4b9f2a53.png)

In fullscreen:
![grafik](https://user-images.githubusercontent.com/4028859/29046641-a3b0d256-7bc8-11e7-829e-e40a00120b2a.png)

**Comment by garoto** [comment]
inb4 "Log file missing"

**Comment by xnoreq** [comment]
`opengl-pbo` seems to be the cause of  the OSD graphical glitch on my system. Without it, I cannot reproduce OSD corruption as shown above.

**Comment by garoto** [comment]
Oh, I can relate: `opengl-pbo` caused the OSD to become stuck when doing some simple `vf` operations, but it happened in sw mode for me, never in `dxva2-copy` with `dxinterop` (but I might be misremembering).

**Comment by xnoreq** [comment]
Disabling `opengl-pbo` also seems to eliminate the flickering when switching to/from fullscreen with `dxinterop`/`dxva2-copy`.

So that only leaves the wallpaper corruption on the second monitor after leaving fullscreen.

**Comment by garoto** [comment]
Yep, `opengl-pbo` and scaling the OSD leaves rendering artifacts behind. Tried only with sw decode. I made a video showing the glitch, just in case: https://0x0.st/d19.mp4

Log: http://sprunge.us/GCUb

**Comment by wm4** [comment]
I think I could reproduce some problems (inconsistently) with ANGLE + --opengl-pbo, but they're probably ANGLE bugs.
