### ISSUE TITLE
Crazy memory leaks

### ISSUE THREAD

**Issue by xnoreq** [mpv-player/mpv#4735]
### mpv version and platform
mpv 0.26.0

### Reproduction steps
```
hwdec=d3d11va-copy
opengl-backend=angle
hwdec-codecs=all
```

Add a bunch of videos to mpv. Mash the key bound to `playlist-next`.

### Expected behavior
Bounded memory usage. Playing a ~5000 kbps bitrate full hd video I measure about 80 MB private working set.
I don't see a reason why memory usage should increase beyond that, especially when switching to lower bitrate videos.
![grafik](https://user-images.githubusercontent.com/4028859/29051208-3ac5fafa-7be1-11e7-955c-9cd864597510.png)

### Actual behavior
Memory usage grows **until the system runs out of memory and mpv crashes or is killed.**

After roughly 30 times playlist-next:
![grafik](https://user-images.githubusercontent.com/4028859/29051251-750935d8-7be1-11e7-9b18-6a1e384ef277.png)

More detailed process stats also showing leaking handles:
Before:
![grafik](https://user-images.githubusercontent.com/4028859/29051281-b1fe8b5a-7be1-11e7-82ba-6d7270c82649.png)

After roughly 30 skips:
![grafik](https://user-images.githubusercontent.com/4028859/29051293-ce590b7c-7be1-11e7-9895-1682739923eb.png)

**Comment by xnoreq** [comment]
Further details:
A detailed look at the handles shows:
- what seems to be graphics driver DirectX cache File & Section & Event handles leaking,
- lots of threads leaking
- the rest are countless unnamed Event & Mutant (mutex, semaphore) type handles leaking

**Comment by wm4** [comment]
Can't reproduce. Missing log file.

**Comment by haasn** [comment]
Does setting ``hwdec=no`` fix it?

**Comment by xnoreq** [comment]
@haasn I'm not seeing leaks as reported above with `hwdec=none` or `hwdec-codecs=none`.

**Comment by haasn** [comment]
Sounds like the solution is to stop using `hwdec`.

**Comment by xnoreq** [comment]
Or switch to another player that uses the same libav/ffmpeg hardware acceleration but doesn't leak at all.
Thanks and good luck.

**Comment by wm4** [comment]
Or you could just ignore the troll and post a log file.

**Comment by wm4** [comment]
Found it - the trick was that you really need multiple files to make it show up, and that the new d3d hwaccel code must be used.

**Comment by OneB1t** [comment]
i have same issue is there any solution for this problem other than hwacel off?
Even after de6d3f8 it is still broken :-/

Also it looks like leak differs between different GPU architectures (it is leaking much less on my intel 630 based system than on AMD R290X system.)

**Comment by CounterPillow** [comment]
Open a new issue instead of replying to a closed 3 year old issue.

**Comment by OneB1t** [comment]
Why when this is probably still relevant? (it is probably issue with mpv.dll itself, but maybe there is something we can do from wrapper code in order to correctly dispose all modules related to hwdec)

**Comment by avih** [comment]
It was reported for D3D11, and at least some leak was fixed at the D3D11 as a result of this report, and for 3 years there were no reports of leaks, so even if it is the same issue (which I think is unlikely), you should open a new issue with proper logs and evidence of the leak.

**Comment by OneB1t** [comment]
I put it here as i have same symptoms as xnoreq it works fine without hwdec and it is broken with both d3d11va and dxva2
For me it looks like mpv-1.dll is not unloading display driver libraries on dispose when hwdec is used

this is how it steadily eats memory with each new media loaded (im reloading complete mpv.dispose() is called between each play)
![image](https://user-images.githubusercontent.com/320479/104334326-7d8acf80-54f2-11eb-8cdd-35fc59c5e1aa.png)

when hwdec=off this memory leak is not occuring

here is trace log for this problem but as im using c# mpv wrapper (Mpv.NET) im not sure if log will be useful. There is nothing about dispose of loaded modules
https://0bin.net/paste/YPupCNHd#+6+sl2XZagkFfaYoPeiQ08pQbC2gnvaaluvmx2L+Y96

**Comment by avih** [comment]
It doesn't look like a leak to me, certainly not anywhere near the OP issue and report. Please open a new issue, with log, and better evidence. It's the last time I'm requesting it, and any further comments you post here will not get any response.

**Comment by avih** [comment]
Also, if you use mpv.net then report it to mpv.net. If you report it here for mpv then use mpv itself.

**Comment by OneB1t** [comment]
Does not really matter what wrapper is used as this is not issue of wrapper itself (as with hwdec off it works perfectly fine) wrapper correctly calls "MpvTerminateDestroy TerminateDestroy"

![image](https://user-images.githubusercontent.com/320479/104360803-e7ff3800-5511-11eb-8750-73227de601c3.png)
This is how leak looks like on AMD card with video reload every 5 sec (it is much worse than on intel)

**Comment by CounterPillow** [comment]
# OPEN A NEW ISSUE EVERYONE ELSE WHO COMMENTED ON THE ORIGINAL ONE DOESN'T NEED TO RECEIVE NOTIFICATIONS FOR YOUR COMMENTS

**Comment by OneB1t** [comment]
Maybe that is the reason why i want to reuse this issue ;)

**Comment by Akemi** [comment]
here we go. comments are locked.
