### ISSUE TITLE
Out of memory errors for big images and opengl-hq

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#4737]
### mpv version and platform

```
mpv 0.26.0-121-g12cafdc868 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Tue Aug  8 07:28:25 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.2
```

### Reproduction steps

1. Try to open https://0x0.st/dSD.jpg with `mpv --no-config --loop=yes --profile=opengl-hq`
2. Observe high memory usage

(Each of the options provided by that profile seems to introduce at least additional 1 GB compared with plain `opengl`, with `--deband=yes` taking the crown causing 2.5 GB memory usage alone)

### Expected behavior

The decoder tries to eat less memory and renders the image in one way or another

*or*

I am rightfully told to upgrade my RAM or switch to a less demanding profile :-) still it's an issue that's good to be tracked I think.

### Actual behavior

My machine freezes and I have to pray OOM killer rescues it.

### Log file

Just empirical evidence with `htop`

### Sample files

https://0x0.st/dSD.jpg

**Comment by haasn** [comment]
Seems to work fine here, consuming about 300 MB of RAM. It hovers around that value every time it loops, but it certainly does not balloon or consume gigabytes and gigabytes.

Does `--vo=null` solve your problem? For me it reduces the RAM consumption by about 200 MB but otherwise the behavior is identical.

**Comment by rr-** [comment]
With `--vo=null` the high memory consumption goes away.

Logs from a session during which it consumes lots of memory: https://0x0.st/dQT.txt
Intel GPU
Arch Linux

**Comment by haasn** [comment]
Does `--opengl-pbo` change anything? What about `--vd-lavc-dr=yes`?

**Comment by quilloss** [comment]
For me on Windows

No PBO:
Private Bytes: 2.82 GB
Working Set: 225 MB
GPU Dedicated Memory: 2.77 GB

PBO:
Private Bytes: 3.15 GB
Working Set: 426 MB
GPU Dedicated Memory: 2.65 GB

mpv takes a while to open a second instance of the file but the system does not seem to suffer any performance loss.

**Comment by rr-** [comment]
Fiddling with both of the suggested options doesn't reduce the consumption under 2 GB.
Is it possible to get to know who allocates that memory with `valgrind` or `cat /proc/something`?

**Comment by AndyFurniss** [comment]
Seemingly uses ram indirectly for me with amd GPU as it uses more vram than I have (=2gig) so the over spill is  GTT 1 to 2 gig depending whether I am full screen or scrolling through windowed view.
 
![mpv-hud-jpg](https://user-images.githubusercontent.com/7150195/29999218-da6baa04-9037-11e7-8eb3-11b77ab70acc.png)

**Comment by Akemi** [comment]
if this is still an issue, please open a new issue.
