### ISSUE TITLE
wmctrl moving issue with mpv

### ISSUE THREAD

**Issue by qoxxxx** [mpv-player/mpv#4739]
### mpv version and platform
0.26.0 on Ubuntu 16.04

### Reproduction steps
`wmctrl -r mpv -e 0,500,500,-1,-1`

### Expected behavior
Top left of mpv's window moved to 500,500

### Actual behavior
Center of mpv's window moved to 500,500

As per wmctrl's manpage: `x,y is the position of the top left corner of the window`
Not sure if it's a wmctrl issue or mpv, but I could observe that behaviour with mpv only.

**Comment by mc4man** [comment]
Likely because mpv does
"Program supplied window gravity: CenterGravity"
(- not sure your command is of much use to begin with..

**Comment by qoxxxx** [comment]
Right, `wmctrl -r mpv -e 1,500,500,-1,-1` is working fine. Never paid attention to the gravity option. 
[A gravity of 0 indicates that the Window Manager should use the gravity specified in WM_SIZE_HINTS.win_gravity](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html)
I guess every other app I encountered used NorthWest.

It's of use to me when used with `:ACTIVE:` to move and/or resize windows using keybindings.
