### ISSUE TITLE
a434892 breaks playback completely on cocoa

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#4740]
### mpv version and platform

git master
macOS 10.12.6

### Reproduction steps

Play any video

### Expected behavior

Video plays

### Actual behavior

mpv gets stuck at inizializing cocoa backend. The culprit seems to be here: https://github.com/mpv-player/mpv/commit/a434892208559232d108b512f9ed30527e646d9d#diff-1bff8c3f4ffe3f9bd5971727ab23fcd7

Moving the `( "osdep/main-fn-cocoa.c",               "cocoa" ),` check back above `( "osdep/main-fn-unix.c",                "posix" ),` seems to fix it, but I have no idea if in turn it breaks something else.

### Log file
https://0x0.st/d1O.txt

**Comment by wm4** [comment]
Fixed by 2ad7978. Regression by #4634.
