### ISSUE TITLE
0.26.0 regression: CUDA doesn't work anymore on Windows

### ISSUE THREAD

**Issue by AgnMout** [mpv-player/mpv#4741]
Reopening of issue #4630 closed without valid reason.

mpv version and platform

0.26.0 on Windows
Reproduction steps

With 0.26.0, cuda hardware decoding doesn't work anymore on Windows, it uses CPU decoding instead. Codec doesn't seem to matter, happens with both VP9 and H.264. cuda-copy still works.
Only Windows is affected, it still works on Linux.
Expected behavior

It should work like with 0.25, reverting to this version makes it work again.
Actual behavior

It doesn't work with 0.26.

**Comment by AgnMout** [comment]
Locked conversation: always wondered how so bright people could be at the same time so childish.
Or maybe because you know your arguments are invalid:
- use software decoding: with UHD HEVC 10 bit, well, everybody does not own a 12 cores
- use D3D11VA: the only available backend is angle, with bad behaviour with 10 bit videos
- use DXVA2: well known quality degradations already with nvidia and intel
Do not bother locking this conversation, I will not post anymore, it is just useless.

**Comment by wm4** [comment]
> same time so childish.

Funny coming from you, who spammed github issues with the explicit intent of seeing who gives up first.
