### ISSUE TITLE
0.26.0 regression: CUDA doesn't work anymore on Windows

### ISSUE THREAD

**Issue by AgnMout** [mpv-player/mpv#4742]
Reopening of issues #4630 and #4741 closed twice without valid reason (mere caprice, who will get tired first ?)

mpv version and platform

0.26.0 on Windows
Reproduction steps

With 0.26.0, cuda hardware decoding doesn't work anymore on Windows, it uses CPU decoding instead. Codec doesn't seem to matter, happens with both VP9 and H.264. cuda-copy still works.
Only Windows is affected, it still works on Linux.
Expected behavior

It should work like with 0.25, reverting to this version makes it work again.
Actual behavior

It doesn't work with 0.26.

**Comment by wiiaboo** [comment]
Opening duplicates issues will not get your issue fixed any faster.

**Comment by wiiaboo** [comment]
The fact that `hwdec=cuda` worked in Windows before was pure coincidence. Using `hwdec=dxva2` or `hwdec=d3d11va` is basically equivalent to it (different APIs but ultimately same result/hardware), so there's close to no reason to fix it.

**Comment by AgnMout** [comment]
Quality differences, cuda filters such as deinterlacing, right color conversion (0-255)...
https://wiki.mikejung.biz/MPC-HC_Video_Decoder_Comparison
"Pure coincidence": one day, someone wrote some code without any precise goal, just for killing time, and then realized that, by magic, it added a new feature ?
Shall stick to MPC-HC.

**Comment by CounterPillow** [comment]
mpv works on more platforms than windows, cuda hwdec was added for Linux because vdpau is awful. If you're after quality, you should be using software decoding anyway.

Since you're not providing any logs to even begin debugging this, I don't think anyone will mind losing you as a user.

**Comment by wm4** [comment]
CUDA offers 0 improvements over D3D11VA, which mpv supports. It's merely the nvidia specific API that exposes the same features as D3D11VA. I guess it's useful for use with native OpenGL and if you don't want to use a -copy mode.

In any case, please stop using mpv, if it means we don't have to deal with people like you.
