### ISSUE TITLE
`dynaudnorm` lavfi filter causes audio/video desync at high playback speed

### ISSUE THREAD

**Issue by mateon1** [mpv-player/mpv#4743]
### mpv version and platform
mpv 0.26.0/ffmpeg 3.3.2 on Linux (NixOS)

### Reproduction steps
1. Play any video with the commandline option --af=lavfi=dynaudnorm
2. Note that audio and video are synced
3. Seek to the beginning, and play the video in double speed with `}`
4. Notice that now audio comes before the proper point in the video

### Expected behavior
Video and audio stay in perfect sync

### Actual behavior
Audio desyncs, and now comes before the appropriate moment in the video, the A-V indicator stays at 0.000 rather than notifying that a desync happened.

### Log file
https://ipfs.io/ipfs/QmVXx6S2E46mN6CLYRzSrmkrJ7Hcdd1FVZ1gKWGJHEFt8r/mpv-log.txt

### Sample files
N/A, seems to happen on any file (tested 1080p and 720p video from youtube, both downloaded locally and with a `ytdl://` URI)

**Comment by kevmitch** [comment]
I can reproduce this here. There are known issues with `dynaudionorm` stemming from the fact that it requires a long lookahead buffer. The workaround is ot use `--lavfi-complex='[aid1] dynaudnorm [ao]'`.

**Comment by kevmitch** [comment]
Significantly improved with #5401, though still not perfect.

**Comment by Dudemanguy** [comment]
Seems fine to me + really old so closing. Feel free to open a new issue if my perception is just bad (wouldn't be the first time).
