### ISSUE TITLE
No errors on invalid files via IPC

### ISSUE THREAD

**Issue by bcdev-com** [mpv-player/mpv#4750]
### mpv version and platform

Windows, 32bit, lachs0r's build from 2017-07-18

### Reproduction steps

Controlling MPV via JSON IPC.  Fairly complete implementation running smoothly, except for getting any sort of error back when attempting to load a corrupt file.

Sending commands like:
    {"command":["loadfile", "foo.mp4", "replace"], "request_id":"loadfile"}
where foo.mp4 is a zero byte file.

### Expected behavior
Would expect to get something like:
  {"error":"some error code", "request_id":"loadfile", "data":"some error message"}

### Actual behavior
Instead receive:
  {"error":"success", "request_id":"loadfile", "data":null}
exactly the same as when loading a valid file.  The console does show:
  Playing: foo.mp4
  Failed to recognize file format.

### Log file

The two lines above are all that are logged.  I am also observing changes to the 'path' property, and it changes briefly to the invalid file, and then to null.

I'm treating that null path as the error indicator for now, but surely an actual message should be sent back in some fashion.

Thanks,
-Blake

**Comment by wm4** [comment]
`loadfile` is mostly asynchronous. mpv will accept commands even _while_ the file is loaded, so it can't be made synchronous (maybe in a distant feature when we reorganize all commands). But even then it could be that i fails to decode any data right after successfully loading (reading all file headers etc.). Your best bet is to listen for the MPV_EVENT_END_FILE event. If you get MPV_EVENT_PLAYBACK_RESTART, it's a pretty good bet that at least _some_ data is being played.

**Comment by bcdev-com** [comment]
Thanks, both for the information and the speed of the response.

I'm not concerned about the getting anything synchronously - I'm already handling all the successful events from loading a file asynchronously when they arrive.   

What I'm confused about is there doesn't ever seem to be any event or property change that gives the sort of "Failed to recognize file format" error that's printed on the console over the IPC channel?  The docs suggest I should get an {"event":"end-file", "reason":"error", "error": "Failed to recognize file format."}, but I don't.  I just get an {"event": "end-file"} with no reason code at all.  Is that expected?

**Comment by wm4** [comment]
Seems to be missing.

**Comment by bcdev-com** [comment]
Does that make this a documentation bug, or worth re-opening as something that will be fixed in in the future?

**Comment by wm4** [comment]
Both. I think it should be implemented. Please open an issue.
