### ISSUE TITLE
Leaving fullscreen doesn't properly maximize mpv window again if taskbar is docked to Right or Left

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#4753]
### mpv version and platform

0.26.0, Windows 7 SP1

### Reproduction steps
Go to "Taskbar and Start Menu Properties" and set your Windows taskbar location on screen to Left or Right (won't reproduce if set to Bottom or Top).
Run mpv.
Maximize the mpv window.
Go to fullscreen mode.
Exit fullscreen mode.
### Expected behavior
The window should return to maximized state, covering all available area.
### Actual behavior
The window is "maximized" (can't be maximized, but can be restored), but its position doesn't cover all available area anymore. Here's a screenshot:
![image](https://user-images.githubusercontent.com/21028464/29240271-1dc072e4-7f7b-11e7-8b69-363f0c0ddb7c.png)

### Log file

https://pastebin.com/z6qewecF

**Comment by wiiaboo** [comment]
Probably related to https://github.com/mpv-player/mpv/issues/4363.
