### ISSUE TITLE
custom time OSD

### ISSUE THREAD

**Issue by b4zz4** [mpv-player/mpv#4759]
![2017-08-14-023410_640x360_scrot](https://user-images.githubusercontent.com/643833/29259415-3f7b0a88-8099-11e7-9d1a-7fd4a0e5ca25.png)

I wish to have the time in hours, minutes, second and frames of way to be able to use it for edition of videos. example: **hh:mm:ss:ff**

**Comment by wiiaboo** [comment]
mpv is not a NLE. You won't get precise frames unless you're using an intra video codec, most likely: [`estimated-frame-number`](https://mpv.io/manual/master/#command-interface-estimated-frame-number)

**Comment by b4zz4** [comment]
thanks. I do not attain to do that drawtext run like effect of ffmpeg. But it is a good start :+1:

**Comment by b4zz4** [comment]
`melt video.mkv -attach dynamictext:#timecode# bgcolour=0x000000DD fgcolour=0xFFFFFFFF valign=bottom halign=center outline=10`

**Comment by wiiaboo** [comment]
Yes?

**Comment by Keith94** [comment]
@wiiaboo How to get your OSC/progress bar style?

**Comment by wiiaboo** [comment]
I pasted it right above the screenshot.

**Comment by Keith94** [comment]
Yeah, thanks for the link. Did you use anything extra besides `seekbarstyle=knob`?

**Comment by wiiaboo** [comment]
boxalpha=125 and timetotal=yes

**Comment by b4zz4** [comment]
In ffplay can see it work. But in my mpv says this:

```
[ffmpeg] No such filter: 'drawtext'
[lavfi] Can't configure libavfilter graph.
Video filter chain:
  [in] 1600x900 yuv420p bt.709/bt.709/bt.1886/limited SP=1.000000 CL=mpeg2/4/h264
  [lavfi] "lavfi.00" 1600x900 yuv420p bt.709/bt.709/bt.1886/limited SP=1.000000 CL=mpeg2/4/h264   <---
  [out] ???
Cannot initialize video filters.
Could not initialize video chain.

```

**Comment by wm4** [comment]
What's even the goal here? Obviously the OSD renders the time. The frame number can't be known exactly for aforementioned reasons.

**Comment by wiiaboo** [comment]
@b4zz4 That error seems pretty explanatory. Your ffmpeg/mpv is missing drawtext filter.

@wm4 hh:mm:ss:ff timestamps, I assume. Maybe a simple lua script could be used to convert from milliseconds to frames. Long as you don't expect the timecode to be exactly accurate.
