### ISSUE TITLE
xdg-screensaver should use suspend/resume instead of reset

### ISSUE THREAD

**Issue by Hello71** [mpv-player/mpv#4763]
related to #4752, but making new bug to remove +1s.

the Right Way(TM) seems to be to use `xdg-screensaver suspend WindowID` and `xdg-screensaver resume WindowID`. this slightly decreases CPU usage but more importantly conveniently works around the b0rked `xdg-screensaver reset` freedesktop behavior (https://bugs.freedesktop.org/show_bug.cgi?id=102124#c3).

**Comment by wm4** [comment]
Wouldn't it be better to fix xdg-screensaver? I can look at providing a `WindowID`. Do any protocol users actually check whether this is a real X window? Can the root window be used?

**Comment by Hello71** [comment]
based on a cursory review of the source, the gnome one automatically stops when the wid closes.

**Comment by Hello71** [comment]
hahaha so it turns out that `xdg-screensaver suspend` *also* doesn't work on KDE because their stupid implementation automatically uninhibits when the sending service is unregistered making it unusable with `dbus-send` ahahahaha kmn

**Comment by CounterPillow** [comment]
@Hello71 more like powerdevil follows the spec whereas xdg-screensaver doesn't.

Now we'll wait for the two parties to bikeshed over a solution for years.

**Comment by Hello71** [comment]
https://bugs.kde.org/show_bug.cgi?id=383575
