### ISSUE TITLE
Add support for HTSP protocol (TVHeadend)

### ISSUE THREAD

**Issue by skrew** [mpv-player/mpv#4764]
Hi,

HTSP protocol provide streams separately. (see [muxpkt](https://tvheadend.org/projects/tvheadend/wiki/Htsp))

With MPV you can add audio-track via `audio-add` but only for local file.

It would be great, via `streamcb`, to be able to add video / audio tracks.

Kodi handle this stream (see the plugin, [pvr](https://github.com/kodi-pvr/pvr.hts)), any chance to have libmpv handling multiple streams ?

**Comment by wm4** [comment]
New protocols should generally go into ffmpeg.

> It would be great, via streamcb, to be able to add video / audio tracks.

There's no reason why this wouldn't work for stream-cb.

**Comment by skrew** [comment]
Because stream-cb only handle one stream/container (who contains all audio/video/Subtitles tracks).
But in case of HTSP protocol, all tracks come separately.

So when i have 1 video track, 2 audio tracks, 2 subtitles tracks, how i merge all into 1 stream for mpv_stream_cb_info->read_fn ?

**Comment by wm4** [comment]
You can open multiple stream_cb URLs, that are all independent. The API supports this.

**Comment by skrew** [comment]
How i can open multiple streams ? with multiple mpv instances ?

Because, as i read in the header file:

```
If a custom stream with the same name is already registered, then the MPV_ERROR_INVALID_PARAMETER error is returned.
```

```
mpvCheckErr(mpv_stream_cb_add_ro(MPVHandler.shared.mpv, "htspchannel", mutableRawPointerOf(obj: MediaSettings.shared.getFileHandlerHTSP()), htsp_channel_open_fn))
MPVHandler.shared.command(.loadfile, args: ["htspchannel://..."])
```

I can register only one instance of htspchannel uri, and only one "open file" at the same time.

**Comment by skrew** [comment]
Little update... Using 2 `mpv_stream_cb_add_ro`(one for video, one for audio) and an mpv instance with loadfile and audio-add works, but A/V are desynchronised (it's not a surprise !)

That's why htsp protocol give those informations with packets:

```
subscriptionId     u32   required   Subscription ID.
frametype          u32   required   Type of frame as ASCII value: 'I', 'P', 'B'
stream             u32   required   Stream index. Corresponds to the streams reported in the subscriptionStart message.
dts                s64   optional   Decode Time Stamp in µs.
pts                s64   optional   Presentation Time Stamp in µs.
duration           u32   required   Duration of frame in µs.
payload            bin   required   Actual frame data.
```

I don't think it's usable with libmpv (i'm don't sure we can set low level stuffs like setting packet->dts) and i'm still surprised that kodi can handle very specific protocol like this via a simple plugin...

Tell me if i'm wrong.

**Comment by wm4** [comment]
Yeah, seems like that kodi plugin implements it as a demuxer. mpv doesn't (and probably won't) provide support for external demuxers. Trying to handle this protocol as separate streams won't really work, because that will apparently drop the timestamps in the main protocol. I recommend implementing this in libavformat (I wonder if @richardpl is interested). This shouldn't be that hard. Another approach would be remuxing to some other protocol on the fly before feeding the data to mpv, but that sounds like a bad solution.
