### ISSUE TITLE
¿How to incorporate options per file into a playlist?

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#4765]
Mpv x64 release 13/08/2017. Windows 10 x64 bits
Hello good afternoon.
First I want to congratulate the whole team that develops MPV, sincerely it is the best player that I know.
I have a question, which I hope you can answer.
I use MPV through the command line, I usually play back many files at the same time, (through the command line or with a playlist), I want to know how I have to write to the playlist Of the command line different options per file.
For example:
I have a list of files and I want the first one to have a group of options that apply only to it and not globally, the same with the second, with the third, and so on.
I do not know how to configure the options per file.
I read in the manual that I have to write the syntax
Mpv --a file1.mkv --b - \ - - file2.mkv --d file3.mkv --e - \} file4.mkv --f

But it does not work, I clarify that I'm on Windows 10 64 bit.
Can you really use options per file through a playlist?
I have no idea how to use it, thank you very much in advance and apologize for my level of English, I'm from Argentina!

**Comment by wiiaboo** [comment]
Yes, it does work. That's not the right syntax at all. Just enclose the file-only options between `--{` and `--}`.

**Comment by wiiaboo** [comment]
`--a` and `--b` are examples of options, they're not real options. The `--\{` in the examples are for some shells that need `{` escaped. I don't think cmd.exe needs them, so:
`mpv --exampleoption file1.mkv --{ --anotherexampleoption file2.mkv --}`
In this example with example options, the option `--anotherexampleoption` would only be active for file2.mkv, but `--exampleoption` is active for both.

**Comment by EzeKees** [comment]
Thank you very much! I tried it and it works perfect!
Many thanks!!
