### ISSUE TITLE
Minimize OSC spam in the logfile

### ISSUE THREAD

**Issue by garoto** [mpv-player/mpv#4771]
I've recently changed the way I invoke mpv on my Windows box to always generate a log file with the `--log-file` command line parameter. Problem is, OSC script messages polute and make the resulting log grow unnecessarily large with redundant stuff like:
```
[  17.531][v][cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding1]
[  17.531][v][cplayer] Run command: expand-text, flags=0, args=[${filename}]
```
And so on and so forth.

Can these messages be moved to another level not logged by the usual verbosity level used by --log-file? Or is there something wrong with lacsh0r's build I'm using?

Example log file: http://sprunge.us/efZC

**Comment by wiiaboo** [comment]
> Or is there something wrong with lacsh0r's build I'm using?

No, there's really that many commands being run. For the sake of allowing dynamic titles it has to expand-text on every frame. the script-binding command is run for every pixel you move your mouse.

**Comment by garoto** [comment]
Appreciate your explanation on how it works. But do you think those can be moved to their own dedicated `msg-module` perhaps or, maybe, change the `cplayer` log module to switch the verbosity level of scripts to debug? I really wish those OSC msg were not present when navigating log files.

**Comment by wiiaboo** [comment]
FWIW, I also think it's way too spammy even for verbose. Maybe some prefix to make commands a bit more silent.
@wm4?

**Comment by garoto** [comment]
@wm4 thoughts?

**Comment by wm4** [comment]
Yes, at least the expand messages should be filtered.
