### ISSUE TITLE
Too high GPU load with opengl-hwdec-interop=d3d11-egl

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4774]
### mpv version and platform
mpv 0.26.0-166-g16e0a39482
ffmpeg git-2017-08-16-16efcfe4

### Reproduction steps
When I play a demanding video with demanding settings, --opengl-hwdec-interop=d3d11-egl (which is selected by default for hwdec=d3d11va) kills my GPU performance (tools report very high GPU usage like ~90%).

### Expected behavior
d3d11va-egl + angle should show similar performance like e.g. dxva2 + dxinterop (which shows ~45% GPU usage).

### Actual behavior
It's much more demanding and framedrops occur, while dxva2 + dxinterop performance is fine.
d3d11-egl-rgb is also fine regarding performance, but it shows banding problems with 8 bit content.

### Log file
Log for d3d11-egl:
http://sprunge.us/BEej

**Comment by garoto** [comment]
But at which P-state? If the GPU is staying at a low performance mode like P8 or similar, then isn't it a trade of?

**Comment by aufkrawall** [comment]
It's not related to pstates, the GPU (GTX 1070 on Windows 10 with driver 385.28) runs with full clock of 2GHz and is consuming a lot of power.

**Comment by shinchiro** [comment]
What is last working build? Probably a regression

**Comment by rossy** [comment]
Which Windows version? Are you sure the performance regression is related to hwdec? There's no perf difference between this build and the last one with software decoding?

**Comment by aufkrawall** [comment]
Software decoding is always fine here, I'm on Windows 10 Creators Update. It also happens with old mpv versions like 0.21.

**Comment by kevmitch** [comment]
This seems kind of expected. The GPU will be doing more work with d3d11va. With dxva2 (and presumably d3d11va-rgb - which I guess is new) the GPU drivers do a quick and dirty colour conversion with speed the only objective, whereas d3d11va gives mpv the original yuv planes. mpv then does the colour conversion with much more emphasis on quality and correctness. Also, if you have anything fancy for `cscale`, it will be a noop with dxva2 wheras with d3d11va, it will have full effect. That would actually be the first setting I'd try to cut back to see if your GPU can keep up. It's also not too surprising that hwdec uses more GPU than non-hwdec where the CPU does more of the work.

**Comment by aufkrawall** [comment]
Hardware decoding shouldn't really put a lot of additional load on the GPU since it's using fixed function units for decoding.
dxva2-copy + dxinterop works fine in terms of both performance and quality (I'm not reporting the issue to get something fixed for myself, just hope it will help for future d3d11va support improvements). The same applies to cuda and vdpau on Linux. Actually, the reported GPU load with zero copy modes is even lower than with copy modes.

**Comment by rossy** [comment]
> It also happens with old mpv versions like 0.21.

Ah, my mistake. I misread the bug and assumed you were talking about a regression between different versions of mpv, rather than a difference between dxinterop and angle.

**Comment by aufkrawall** [comment]
One mystery less:
The high GPU load occurs when anisotrpic filtering is forced via the graphics driver. 

Now if we could only use Angle without any banding. :(

**Comment by Hrxn** [comment]
> Actually, the reported GPU load with zero copy modes is even lower than with copy modes.

Uh, well, isn't that expected?

**Comment by aufkrawall** [comment]
Closing because it's not a mpv/ANGLE bug.
