### ISSUE TITLE
youtube titles in playlist (osd)

### ISSUE THREAD

**Issue by brontosaurusrex** [mpv-player/mpv#4780]
### mpv version and platform
```
mpv 0.26.0-179-g01058b16f9 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Aug 18 15:49:57 CEST 2017
ffmpeg library versions:
   libavutil       55.74.100
   libavcodec      57.102.100
   libavformat     57.76.100
   libswscale      4.7.102
   libavfilter     6.99.100
   libswresample   2.8.100
ffmpeg version: N-87004-gcadab5a2a7

os = Debian 9
```
### Reproduction steps
Shift+drag youtube videos (not youtube playlists) to mpv window and see playlist in osd. 
In input.conf I have 'F3 script-message osc-playlist 5' to see the playlist.

### Expected behavior
The actual titles would show, same as if loading 'youtube.com/watch?list=somelist' type of links.

### Actual behavior
watch?v=xy shows.

### Log file
<http://paste.debian.net/plain/981977>

### p.s.
Possibly related: If this is 'youtube-dl is not telling me type of thing': Even with single video playing from youtube and it is already in full playback it will still show 'watch?v=xy' instead of title.

**Comment by necronoise** [comment]
"Your requested paste entry '981977' could not be found"
I dont know if we have the same issue, but I want to my script show the titles when I play any music or playlist, to do that you can press shift+i.

mpv ytdl://ytsearch:'gorgoroth' --no-video
Playing: ytdl://ytsearch:gorgoroth

Playing: ytdl://73Za2PVVDcI
 (+) Audio --aid=1 --alang=eng (*) (vorbis 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
(Paused) A: 00:00:04 / 00:04:04 (1%) Cache: 24s+944KB

shift+i

mpv ytdl://ytsearch:'gorgoroth' --no-video
Playing: ytdl://ytsearch:gorgoroth
File: ytsearch:gorgoroth

Playing: ytdl://73Za2PVVDcI
File: 73Za2PVVDcI
	Title: Gorgoroth - Sign of an Open Eye (w / Lyrics ) 1080HD
 (+) Audio --aid=1 --alang=eng (*) (vorbis 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
File: 73Za2PVVDcI
	Title: Gorgoroth - Sign of an Open Eye (w / Lyrics ) 1080HD
	Cache: 0 +2.156 sec 26.599 KiB/s
	Size: 3.844 MiB

Audio: vorbis (Vorbis)
	Sample Rate: 44100 Hz
	Channels: 2
	Bitrate: 128 kbps
A: 00:00:02 / 00:04:04 (0%) Cache:  2s+98KB

**Comment by Dudemanguy** [comment]
Tried it on a random youtube playlist and it worked for me so I'll assume it has been fixed.

**Comment by garrett-hopper** [comment]
@Dudemanguy, I believe the intent of this issue is for that same behavior that occurs when you play an entire playlist also occur when videos are queued one by one. As far as I can tell, that has not been resolved. (Perhaps the issue title should be updated to reflect the actual feature request.)

**Comment by Dudemanguy** [comment]
Oops you're right, I misunderstood.
