### ISSUE TITLE
tearing when seeking when using hwdec on windows

### ISSUE THREAD

**Issue by Jimmy-Z** [mpv-player/mpv#4782]
### mpv version and platform
windows builds by lachs0r, tested with 20160625(oldest available on https://mpv.srsfckn.biz/) and most recent 0.26

### Reproduction steps
Seek with any file with hwdec enabled, dxva2 or d3d11va.

no such tearing appears with dxva2-copy or d3d11va-copy.

It only tears when seeking, no tearing after seeking, so hardly noticeable, not really a big deal, but I found out just recently when using vaapi on ubuntu, no such tearing appears, same computer with Intel HD graphics, made me a bit curious.

**Comment by garoto** [comment]
Can't say I've noticed anything resembling frames tearing (as in video-game-with-vsync-disabled tearing). But I'm using an nvidia GPU. That said, you should probably produce a log at least.

**Comment by Jimmy-Z** [comment]
Sorry, I though that was easy to reproduce, since I've seen it on both my desktop(AMD) and laptop(Intel).

[issue4782intel.zip](https://github.com/mpv-player/mpv/files/1236122/issue4782intel.zip)
While producing this log file I noticed `profile=opengl-hq` has to be there.

**Comment by Jimmy-Z** [comment]
[issue4782amd.zip](https://github.com/mpv-player/mpv/files/1236143/issue4782amd.zip)
For AMD `profile=opengl-hq` is not needed. and the tearing is more obvious than Intel.

**Comment by Jimmy-Z** [comment]
I don't know when but it seems to have been fixed, haven't noticed any tearing for a while.
