### ISSUE TITLE
mpv messes with desktop environment in fullscreen

### ISSUE THREAD

**Issue by tsoernes** [mpv-player/mpv#4786]
### mpv version and platform

mpv 0.26.0-9-g2378acc3b3 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Jul 22 19:50:49 CEST 2017
ffmpeg library versions:
   libavutil       55.68.100
   libavcodec      57.102.100
   libavformat     57.76.100
   libswscale      4.7.101
   libavfilter     6.95.100
   libswresample   2.8.100
ffmpeg version: N-86834-gd24a82d2e2

Fedora 26 Kde Xorg, Nvidia proprietary drivers
### Reproduction steps
When I go into full screen, all desktop environment widgets like the taskbar and system clock
 (i.e. the default kde tray clock) reverts to some previous time, like a couple of days a go (it varies), then stops. 

When I quit fullscreen, the DE reverts back to current time and works as normal. No errors from mpv. Also happens when idling mpv without config in fullscreen.

**Comment by lachs0r** [comment]
Sounds more like a potential graphics driver bug. What happens if you interact with the KDE clock?

**Comment by tsoernes** [comment]
You were right. Had nothing to do with twitch or playing links.

The whole desktop environment reverts back to some previous time. The taskbar shows which programs were opened at that time. It is caused by entering full screen and reverts back to normal when full screen is exited. I'm unable to interact with the desktop environment (on the other screens) when in full screen.

**Comment by lachs0r** [comment]
So this is either a KWin bug (see also compositor settings under systemsettings5 → Display and Monitor) or another NVIDIA driver regression.
