### ISSUE TITLE
(Request) User Script youtube format change

### ISSUE THREAD

**Issue by Joseph65** [mpv-player/mpv#4787]
When i play a youtube video with mpv it chooses bestvideo+bestaudio formats
what im requesting is that i can change format from 1080p to 720p or 480p
with a lua user script, since not all pc can handle 4k playback.
enabling with a shortcut or osc.

**Comment by haasn** [comment]
You can set this yourself using `ytdl-format`.

**Comment by haasn** [comment]
An example:

```
ytdl-format=bestvideo[height<=1080]+bestaudio/best
```
