### ISSUE TITLE
Integrated GPU causes sub-par video (sample included)

### ISSUE THREAD

**Issue by ballo** [mpv-player/mpv#4788]
### mpv version and platform
mpv Version: mpv-0.26.0 (according to where I downloaded it since the Mac version inexplicably lacks both a version string in the info.plist nor does it have an 'About' window) 

OS version: 10.10.5

Late 2011 MacBook 17" w/Intel HD 3000 & AMD Radeon HD 6750M

### Reproduction steps

Download and play this mkv using gfxCardStatus to switch GPU:

https://drive.google.com/uc?id=0BwxFVkl63-lETTVtaVV0LUVRZ1k&export=download

https://drive.google.com/file/d/0BwxFVkl63-lETTVtaVV0LUVRZ1k/view

On my machine it's evident even in windowed mode, although in times past it was more apparent in full screen (although I'm not certain if this is the same issue)

### Expected behavior

The integrated GPU ought to provide smooth playback

### Actual behavior

Only the discrete GPU provides smooth playback. The integrated GPU pulses between smooth and dithering which is obvious when looking at the scrolling white lines in the video.

### Log file

Integrated:
https://pastebin.com/JnpgSZj4
Discrete:
https://pastebin.com/TepfAAi6

### Sample files

https://drive.google.com/uc?id=0BwxFVkl63-lETTVtaVV0LUVRZ1k&export=download

**Comment by Akemi** [comment]
first of all update your mpv version. no idea where you got it from but it's definitely not 0.26 since it's 1 1/2 years old from January 2016 https://github.com/mpv-player/mpv/commit/aaafbfc. it says so in your log "mpv git-aaafbfc (C) 2000-2016".

you can get a recent mpv versions [here](https://laboratory.stolendata.net/~djinn/mpv_osx/). those definitely are tagged properly. they have a version string in the plist file. also on the most recent version there is also an About menu (e0a2d152163977fdc2a48ac1bd4144614a1e6f25).

try with 0.26 and 0.25 at least, since 0.26 has some problems on macOS.

**Comment by ballo** [comment]
If you do an internet search for mpv mac install the first link is:

https://mpv.io/installation/

The link for OS X builds is:

https://laboratory.stolendata.net/~djinn/mpv_osx/

I downloaded the latest one. Fair enough?

**Comment by ballo** [comment]
and yes, it's very hard to keep track which mpv versions I have (yes, I have multiple because they all have different bugs) because they all report the version as "git-aaafbfc" whatever that means, and they all lack a Get Info menu item.

**Comment by Akemi** [comment]
that is the site i linked to, so yes.
if you are implying that you used the latest version on there, then you didn't. the latest version is tagged as "mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects" and that isn't the version you provided a log from.

**Comment by ballo** [comment]
So this version:

https://laboratory.stolendata.net/%7Edjinn/mpv_osx/mpv-latest.tar.gz

is 100 times MORE choppy. Unwatchable

**Comment by Akemi** [comment]
> try with 0.26 and 0.25 at least, since 0.26 has some problems on macOS.

see what i said.

**Comment by Akemi** [comment]
also try with `--opengl-early-flush=no`, `--opengl-pbo=yes` and the combinations of both.

**Comment by Akemi** [comment]
> yes, it's very hard to keep track which mpv versions I have because they all report the version as "git-aaafbfc" whatever that means

it really isn't. no they don't if you get the releases.

> (yes, I have multiple because they all have different bugs)

use a more recent version than one that is 1 1/2 years old and you probably get less bugs. otherwise you should report them or no one can fix them.

> and they all lack a Get Info menu item.

like i said

> also on the most recent version there is also an About menu (e0a2d15).

**Comment by ballo** [comment]
Old MPV:
windowed Intel GPU: blurry
windowed AMD GPU: good
full screen Intel GPU: blurry
full screen AMD GPU: good

0.25.0:
windowed Intel GPU: blurry
windowed AMD GPU: blurry
full screen Intel GPU: worse
full screen AMD GPU: worse

Definitely a step backwards

**Comment by ballo** [comment]
Bugs are besides the point if the video is garbage, no?

And no, 0.25.0 has no about menu. It also hid the quit & save location menu for some reason (you guys are more minimalist than Jobs)

**Comment by Akemi** [comment]
apparently bugs are not besides the point since you've got a problem about them here.

because 0.25 is not the latest version. don't make me repeat myself over and over again.

could you just stay on topic and stop complaining about things that have already been fixed or been taken care of (#4687). i am still waiting for you to do what i told you.

**Comment by ballo** [comment]
(ugh, one of the GPU switches while mpv was running caused the system to freeze and I had to reboot)

I did all combos of windowed/full screen and intel/amd for --opengl-early-flush=no/--opengl-pbo=yes --opengl-early-flush=no and --opengl-pbo=yes.

None are as good as the OLD version using AMD. Intel w/full screen is unwatchable and is a lot worse than any other combo. The flags don't appear to do squat.

**Comment by ballo** [comment]
Just to be extra thorough I tested with another video with and without --opengl-early-flush=no --opengl-pbo=yes:

windowed Intel GPU: watchable
windowed AMD GPU: watchable
full screen Intel GPU: unwatchable
full screen AMD GPU: watchable

**Comment by Akemi** [comment]
also try `--video-sync=display-resample` in combinations with the other options. for now with the 0.25 version.

i am also interested in the mpv status line when you start mov via command line `AV: 00:00:33 / 00:23:57 (2%) A-V:  0.001 DS: 2.500/1 Dropped: 1`. especially what DS: and Dropped: says after a bit of playback.

**Comment by ballo** [comment]
I'm trying to find a good royalty free sample video which makes this evident but I'm turning up empty so far. Sports would be best but most sample videos are filming simple objects or 3D geek crap. It's very frustrating.

--video-sync=display-resample makes my sports video unwatchable in windowed mode and even worse in full screen. 2x worse at least.

**Comment by ballo** [comment]
OK, I found one:

http://s1.demo-world.eu/hd_trailers.php?file=panasonic_2012_edmonton_indy-DWEU.mkv

This clearly shows the differences between, for example, Intel 3000 in windowed vs full screen (as well as other more subtle differences).

**Comment by Akemi** [comment]
the video doesn't really matter, since i can't reproduce what you are seeing or we are not on the same page what exactly your issue is with being "blurry" and "dithering".

**Comment by ballo** [comment]
Is there a way to log if frames are being dropped?

**Comment by Akemi** [comment]
see what i said

> i am also interested in the mpv status line when you start mpv via command line AV: 00:00:33 / 00:23:57 (2%) A-V: 0.001 DS: 2.500/1 Dropped: 1. especially what DS: and Dropped: says after a bit of playback.

there is also [stats.lua](https://github.com/Argon-/mpv-stats) that is quite helpful.

did you only test `--video-sync=display-resample` or in combination with the other options?

**Comment by ballo** [comment]
Also, this line doesn't work:

./mpv AV: 00:00:33 / 00:23:57 (2%) A-V: 0.001 DS: 2.500/1 Dropped: 1

I tried in zsh, bash, and sh. With zsh mpv will attempt to play the root directory, and sh reports:

sh: syntax error near unexpected token `('

I don't see a man file to see what you're trying to do here.

**Comment by ballo** [comment]
When I tested --video-sync=display-resample it was without any other flags

**Comment by Akemi** [comment]
i didn't say you should use it as a command line option. i meant for you to look at the mpv status line when starting mpv via command line and paste the result here after a bit of playback.

you only get a man if you build mpv yourself not via the bundle. we have a manual on our [page](https://mpv.io/manual/master/).

like i said you should test `--video-sync=display-resample` with the other flags i mentioned. especially with `--opengl-early-flush=no` since it helps with 60fps video, the first one you posted.

please post a log file with at least `--video-sync=display-resample --opengl-early-flush=no` and the 60fps file from the initial post.

**Comment by ballo** [comment]
I didn't know what you meant by status line. It isn't visible when I'm viewing videos in full screen.

When running a portion of the 60FPS with all the flags and windowed mode it runs very slowly:
AV: 00:00:12 / 00:10:05 (2%) A-V:  0.000 DS: 1.000/83 Dropped: 17

It runs a little faster full screen.

With the AMD both windowed and full screen appear to run full speed. It's difficult to know exactly because there is no FPS indicated. 

When running the 30fps video (the latter one I posted) I got this warning for the Intel 3000 HD:

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

and loads of dropped frames. 

No problem with AMD. It plays, perceptively speaking, perfectly. 

In every case there are a dozen odd dropped frames but I attribute that to losing frames during the startup process. At least with the discrete GPU I don't appear to lose frames after this initial period. With the integrated GPU it happens continuously (with those flags). 

I also ran it with no flags and with the FPS video the integrated GPU is constantly dropping frames as well. It doesn't run slow, but the frames are dropping at a rate of 30/sec. (307 frames in roughly 10 seconds). Windowed mode with the video running in the background behind the dock and iTerm window. With the discrete AMD the same test netted 326 dropped frames. 

Same two tests with the 30 FPS video netted 229 dropped frames (really horrible) for integrated and only 6 dropped frames for discrete.

**Comment by ballo** [comment]
I tried running a command like this to automate the process and enforce some standard but it doesn't display the status line:

./mpv  ~/Downloads/new7/panasonic_2012_edmonton_indy-DWEU.mkv.download/panasonic_2012_edmonton_indy-DWEU.mkv  & sleep 10 ; killall mpv

If I pipe the output to a file it displays the status momentarily, then it disappears.

**Comment by Akemi** [comment]
try the git master with the newly introduced [cocoa-cb](https://github.com/mpv-player/mpv/commit/c5e4538bc4b63f02bf89f62aa25a37b9eb0c0316) backend for opengl-cb.
