### ISSUE TITLE
Title bar color - macOS dark theme

### ISSUE THREAD

**Issue by ear** [mpv-player/mpv#4789]
I have a small feature request. I have noticed that other mac software has been implementing custom title bars: it is possible to make it dark to match the dark menu bar and dock.

Examples are editors like [Atom](https://github.com/atom-material/atom-material-ui/issues/334) and [Sublime Text](https://www.sublimetext.com/docs/3/themes.html#elements-windows); music players like Spotify; terminals like [iTerm](https://gitlab.com/gnachman/iterm2/issues/4080); and there's probably more out there.

I say let's have an option for mpv also to make a dark title bar that matches!

Thank you for taking the time to read this.

**Comment by Argon-** [comment]
I say use `--no-border` because who needs a title bar on a video anyway.

**Comment by ear** [comment]
`--no-border` used to make the menu bar unresponsive/broken so I had stopped using it, thanks for reminding me! That's definitely good. I'd be still nice to have a title bar that matches other apps and the macOS dark theme though 😎

**Comment by Akemi** [comment]
i was thinking about changing the border/title so it is similar to QuickTime, eg within the video frame and automatically fading out and/or make it an option to the `--border` option. wonder if this is a wanted change/addition. this would also make the no border option a bit more consistent with 'style guidelines', eg a proper shadow and rounded corners.

though it will have some complications especially with the OSC top bar.

**Comment by nathan** [comment]
[NSWindow](https://developer.apple.com/documentation/appkit/nswindow?language=objc) supports [NSAppearanceCustomization](https://developer.apple.com/documentation/appkit/nsappearancecustomization?language=objc), so you can send <code>[*window* [setAppearance:](https://developer.apple.com/documentation/appkit/nsappearancecustomization/1533925-appearance?language=objc) [[NSAppearance](https://developer.apple.com/documentation/appkit/nsappearance?language=objc) [appearanceNamed:](https://developer.apple.com/documentation/appkit/nsappearance/1529612-appearancenamed?language=objc)[NSAppearanceNameVibrantDark](https://developer.apple.com/documentation/appkit/nsappearancenamevibrantdark?language=objc)]]</code> and get a window that looks like this:

<img width="584" alt="screen shot 2017-09-12 at 10 11 46" src="https://user-images.githubusercontent.com/1578238/30330353-dbd9da24-97a2-11e7-9a35-13519a78f452.png">

If you also send <code>[*window* [setBackgroundColor:](https://developer.apple.com/documentation/appkit/nswindow/1419751-backgroundcolor?language=objc)[[NSColor](https://developer.apple.com/documentation/appkit/nscolor?language=objc) [blackColor](https://developer.apple.com/documentation/appkit/nscolor/1527194-blackcolor?language=objc)]]</code> you can make the titlebar actually black:

<img width="652" alt="screen shot 2017-09-12 at 10 12 00" src="https://user-images.githubusercontent.com/1578238/30330437-176cc236-97a3-11e7-8f60-144335ed5d63.png">

To detect dark mode, you can use <code>[[[NSUserDefaults](https://developer.apple.com/documentation/foundation/nsuserdefaults?language=objc) [standardUserDefaults](https://developer.apple.com/documentation/foundation/nsuserdefaults/1416603-standarduserdefaults?language=objc)] [stringForKey:](https://developer.apple.com/documentation/foundation/nsuserdefaults/1416700-stringforkey?language=objc)@"AppleInterfaceStyle"]</code>, which returns `@"Dark"` iff the user has enabled the dark menu bar/dock. However, Apple [recommends](https://developer.apple.com/macos/human-interface-guidelines/windows-and-views/panels/#huds) that apps always use the dark-on-light color scheme / components (regardless of user preferences) if they are media-centric.

**Comment by nathan** [comment]
> i can't really see where Apple recommends what you said, at least not what you linked since that is about HUDs.

HUDs use the dark appearance/material. Combined with [the following](https://developer.apple.com/macos/human-interface-guidelines/visual-design/translucency/#appearance-and-materials):

> Don’t combine a light appearance with a dark material, or vice versa.

This implies the rest of the user interface should too.

**Comment by Akemi** [comment]
that still doesn't say that media centric Apps should use dark appearance, just that dark and light shouldn't be mixed. or do i misunderstand something?

**Comment by nathan** [comment]
Apple recommends that you use HUDs for media-centric apps:

> HUDs are designed to complement apps that focus on highly visual content or that provide an immersive experience, such as a full-screen slide show. For example, QuickTime Player uses a HUD to display inspector information without obstructing too much of the user’s content.

> In general, a HUD should only be used in the following scenarios:
> 
> - In a media-oriented app that focuses on movies, photos, or slides.
> - In an immersive app with a dark interface.
> - …

HUDs use a dark appearance. Apple also recommends that you don't mix dark and light appearances. Ergo the rest of the app should probably use a dark interface too.

Also, all of Apple's video-centric apps—QuickTime Player, iMovie, FaceTime—use a dark interface.

**Comment by Akemi** [comment]
we don't use HUDs in mpv or rather there is 'no need' to use HUDs since we only really have a video view. we also don't mix anything, so there is no reason to force a dark theme. if this is changed it should definitely be user changeable in one or another way. i also don't see it as a recommendation but rather as a "should only be used in following cases ... but doesn't need to be used". it's up to the dev what to do.

i would consider Preview (opens slides, Photos, etc) for example also a media oriented App and it uses a light theme with a light HUD-like Panel (Inspector).

**Comment by nathan** [comment]
It definitely should be user-settable. The default should probably be dark, though, once it's implemented (especially since the OSC uses a dark theme too).

**Comment by Akemi** [comment]
i would propose/suggest an option with three to five choices (if the variants make a difference) <auto|light|dark(|mediumLight|ultraDark)>, auto being the default. auto is using the system preferences. if dark is preferred i would also be fine with dark being the default.

**Comment by ear** [comment]
Sublime supports straight giving it [the colors](http://www.sublimetext.com/docs/3/themes.html#elements-windows) maybe that's what you want too?

**Comment by Akemi** [comment]
just a heads up #5520.
