### ISSUE TITLE
HEVC 10bit hardware decoding: [vd] Codec profile: unknown (0xffffff9d)

### ISSUE THREAD

**Issue by nshtg** [mpv-player/mpv#4790]
### Reproduction steps

Try playing the sample file using `hwdec=auto` and `hwdec=cuda-copy` (`cuda` fails for other reasons).

### Expected behavior

Should play the HEVC 10bit 2160p file using hwec.

### Actual behavior

Falls back to software decoder for anything except `cuda-copy`.
I suspect the error `[vd] Codec profile: unknown (0xffffff9d)`.

This does not happen for all HEVC Main10 encoded files, only for some.

### Log file

I enabled the trace debug level and let it run the 1s example video.

- `hwdec=auto`, falls back to sw-decoding: https://git.io/v5fvq
- `hwdec=cuda-copy`, works using hw-decoding: https://git.io/v5fv0

### Sample files

I created a small sample file (1s => 857kb) from the beginning of an effected mkv:

https://mega.nz/#!vlUSiILa!UZrfmxJAicbyXAJCC1UHCM50K0T4WZvryi_2ynTpGJQ

**Comment by fhlfibh** [comment]
@nshtg https://github.com/mpv-player/mpv/issues/4040

**Comment by nshtg** [comment]
@fhlfibh 
Any idea why it might fail? Could you reproduce the error using the sample file?

I suspected that error, because when its working (cuda-copy) that error is missing.

**Comment by fhlfibh** [comment]
@nshtg MPV's current CUDA doesn't work on Win at the moment. There were several issues about it recently. 
On my Lin system the sample plays Ok with `hwdec=cuda`

**Comment by nshtg** [comment]
@fhlfibh
I know that cuda is currently broken, thats not my problem.

Auto is loading d3d11va and thats what triggers the error from the issue.

**Comment by wm4** [comment]
I'd rule this either a broken file, or ffmpeg bug.

**Comment by nshtg** [comment]
@wm4 
@fhlfibh 
I looked back through old versions, and v0.25.0 plays the file perfectly fine, and reads the correct profile:

> mpv 0.25.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Apr 23 03:06:36 CEST 2017
ffmpeg library versions:
   libavutil       55.61.100
   libavcodec      57.93.100
   libavformat     57.72.101
   libswscale      4.7.101
   libavfilter     6.86.100
   libswresample   2.8.100
ffmpeg version: N-85608-gbe1430a531

> [vd] Codec profile: Main 10 (0x2)
[d3d11va] {86695f12-340e-4f04-9fd3-9253dd327460} MPEG2and1_VLD  NV12
[d3d11va] {ee27417f-5e28-4e65-beea-1d26b508adc9} MPEG2_VLD  NV12
[d3d11va] {6f3ec719-3735-42cc-8063-65cc3cb36616} <unknown>  NV12
[d3d11va] {1b81bea4-a0c7-11d3-b984-00c04f2e73c5} VC1_D2010  NV12
[d3d11va] {1b81bea3-a0c7-11d3-b984-00c04f2e73c5} VC1_D  NV12
[d3d11va] {32fcfe3f-de46-4a49-861b-ac71110649d5} <unknown>  NV12
[d3d11va] {d79be8da-0cf1-4c81-b82a-69a4e236f43d} <unknown>  NV12
[d3d11va] {f9aaccbb-c2b6-4cfc-8779-5707b1760552} <unknown>  NV12
[d3d11va] {1b81be68-a0c7-11d3-b984-00c04f2e73c5} H264_E  NV12
[d3d11va] {5b11d51b-2f4c-4452-bcc3-09f2a1160cc0} HEVC_VLD_Main  NV12
[d3d11va] {107af0e0-ef1a-4d19-aba8-67a163073d13} HEVC_VLD_Main10  NV12 P010
[d3d11va] {20bb8b0a-97aa-4571-8e99-64e60606c1a6} <unknown>  NV12 P010
[d3d11va] {15df9b21-06c4-47f1-841e-a67c97d7f312} <unknown>  NV12
[d3d11va] {efd64d74-c9e8-41d7-a5e9-e9b0e39fa319} <unknown>  NV12
[d3d11va] {ed418a9f-010d-4eda-9ae3-9a65358d8d2e} <unknown>  NV12
[d3d11va] {9947ec6f-689b-11dc-a320-0019dbbc4184} <unknown>  NV12
[d3d11va] {33fcfe41-de46-4a49-861b-ac71110649d5} <unknown>  NV12
[d3d11va] {463707f8-a1d0-4585-876d-83aa6d60b89e} VP9_VLD_Profile0  NV12
[d3d11va] {a4c749ef-6ecf-48aa-8448-50a7a1165ff7} <unknown>  NV12 P010
[d3d11va] {dda19dc7-93b5-49f5-a9b3-2bda28a2ce6e} <unknown>  NV12 P010
[d3d11va] {6affd11e-1d96-42b1-a215-93a31f09a53d} <unknown>  NV12
[d3d11va] {914c84a3-4078-4fa9-984c-e2f262cb5c9c} <unknown>  NV12
[vd] Selecting {107af0e0-ef1a-4d19-aba8-67a163073d13} HEVC_VLD_Main10 104
[vd] Requesting pixfmt 'd3d11va_vld' from decoder.
[vd] Using hardware decoding (d3d11va).

Somewhere along the way to v0.26.0 the parsing got damaged. I guess "broken file" is less likely (it worked before, gets parsed correctly in MediaInfo and similar programs).

I noticed setting `--vd-lavc-check-hw-profile=no` enables hwdec using d3d11, so I guess the unknown profile error is indeed the reason why mpv falls back to software rendering.

**Comment by nshtg** [comment]
I also checked using ffprobe, ffmpeg lib decodes the file fine and recognizes the Main10 codec profile, so this seems like a mpv problem.

**Comment by wm4** [comment]
@nshtg no, this is all up to ffmpeg. ffprobe probably gets it "correctly" because of idiotic things which I won't acknowledge or implement in mpv.

**Comment by fhlfibh** [comment]
@nshtg Missed `hwdec=auto` from your description, sorry...
Anyway, on Lin it goes with hw decoding even with `[vd] Codec profile: unknown (0xffffff9d)`
Unfortunately, I can't say any thing more, I don't know much about hwdec things on Win...

**Comment by timofonic** [comment]
@wm4  @nshtg  @fhlfibh 
If there's need of testers. I'm going to install Windows Server 2016 x64 on my "workstation". I can install Windows 10 x64 too for testing purposes.

I have a Nvidia Optimus setup:
- Laptop model: MSI GE62 2QD Apache Pro
- CPU: Intel Core i7 5700HQ @ 2.7GHz
- RAM: 8GB (considering to upgrade, official BIOS limits by 16Gb but...)
- iGPU: Intel HD Graphics 5600
- dGPU: Nvidia GeForce GTX 960M

**Comment by Akemi** [comment]
stale issue.
