### ISSUE TITLE
Logitech M600 horizontal Scroll issue

### ISSUE THREAD

**Issue by man0000** [mpv-player/mpv#4792]
Hi,

I have just realized the horizontal scroll in my (2) Logitech M600 mice does not work with the last release
[mpv-x86_64-20170718] but it works with the previous [mpv-x86_64-20170423].

I have tested the 2 mice in 2 different PCs and Windows 10 Pro/Home versions with the same results.
Vertical scroll has no issue.

With my Logitech T630/Logitech T650 there are no problem at all vertically or horizontally.

Anything I am missing?.

THANKS...

**Comment by lachs0r** [comment]
Scroll wheel inputs are now called WHEEL_UP/DOWN/LEFT/RIGHT in input.conf. You’ll have to fix that.
