### ISSUE TITLE
Change downscaler based on resolution

### ISSUE THREAD

**Issue by z0z0z** [mpv-player/mpv#4793]
If the video resolution is 1080p or lower, I want to use dscale=mitchell

If the video resolution is bigger than 1080p, e.g. 4K, I want to use dscale=bilinear, because mpv is ass on my computer trying to dscale 4K video with demanding downscaling algorithms.

Is there anyway to make mpv choose the downscaling algo dynamically based on the video's resolution?

**Comment by wiiaboo** [comment]
[auto-profiles.lua](https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua)

**Comment by z0z0z** [comment]
@wilaboo 
Could you, gib example of how I would use this to do what I want

**Comment by wiiaboo** [comment]
Read the script's instructions. It has examples too. Or wait for someone else.

**Comment by z0z0z** [comment]
@wilaboo 
[res2big]
profile-desc=resolution>1080p
dscale=bilinear

Why doesn't this work?

**Comment by wiiaboo** [comment]
Because there's no property called resolution, most likely.

**Comment by z0z0z** [comment]
@wilaboo
How do I find the property that defines video resolution?

**Comment by garoto** [comment]
This is pretty much lifted from Argon's mpv.conf (https://github.com/Argon-/mpv-config/blob/master/mpv.conf#L119)

```
profile-desc=cond:get("height", math.huge) < 1080
dscale=mitchell
```

**Comment by haasn** [comment]
Downscaling peformance shouldn't depend on the size of the source texture. I suspect the real reason you're getting bad performance is because the `cscale` is still trying to upscale the chroma texture to 4K, even though your display is smaller than that.

I suspect the better long-term fix would be to downscale luma to chroma instead in these cases.

**Comment by fhlfibh** [comment]
@haasn 

> I suspect the better long-term fix would be to downscale luma to chroma instead in these cases.

Does it imply that at the moment when downscaling 4K to FHD it first upscales chroma to 4K and then downscales RGB back to FHD? If it's the case, downscaling 4K luma to chroma (especially if chroma is originally of FHD size) looks better indeed...

@z0z0z You can try my script if you want https://github.com/fhlfibh/height-profiles/blob/master/height-profiles.lua
It's not so feature-rich as `auto-profiles.lua`, but much simplier.
In `mpv.conf` create two profiles named `UHD profile` and `FHD profile`, and put where what you want.

**Comment by haasn** [comment]
> Does it imply that at the moment when downscaling 4K to FHD it first upscales chroma to 4K and then downscales RGB back to FHD? If it's the case, downscaling 4K luma to chroma (especially if chroma is originally of FHD size) looks better indeed...

Correct.

**Comment by CrisBRM** [comment]
@haasn Does this behaviour constitute a regression or just something that needs to be fixed? 
![screenshot from 2017-08-23 00-12-59](https://user-images.githubusercontent.com/9098352/29591716-1f24b576-8798-11e7-9670-d7e2bd5109b6.png)
![screenshot from 2017-08-23 00-14-57](https://user-images.githubusercontent.com/9098352/29591717-1f400ab0-8798-11e7-9368-a7a5e2778cf0.png)

Then again, I do have this profile active:
```
[native]
profile-desc=cond:get('width',0) >= 1920
opengl-shader="~~/shaders/crossbilateral.glsl"
```

**Comment by haasn** [comment]
I'm not entirely sure what you mean. The bad performance? Does it go away if you use an older mpv version?

**Comment by CrisBRM** [comment]
@haasn The upscaling of the chroma plane to the original resolution of the video (in this case, 2560x1080) before downscaling to 1080p. Has it always worked this way?

**Comment by haasn** [comment]
> Has it always worked this way?

Yes.

**Comment by Argon-** [comment]
@z0z0z https://mpv.io/manual/master/#property-list
The expressions are just Lua code.
