### ISSUE TITLE
Issue with Gopro videos and vaapi

### ISSUE THREAD

**Issue by nhabongo** [mpv-player/mpv#4794]
Hi,

I am having a problem when try to hw accelerate videos made with my GoPro 4 camera. The player always fallaback to software rendering. It seems to be a problem with the pixel format (yuvj420p). 

VLC can handle these videos just fine using the vaapi (very little cpu usage).

Here`s an example:
OS:
      arch linux 4.12.8-2-ARCH #1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 GNU/Linux
mpv: 
      mpv 0.26.0-207-gb62150bd6b (C) 2000-2017 mpv/MPlayer/mplayer2 projects
      built on Wed Aug 23 09:30:37 -03 2017
      ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.3

video track properties (ffmpeg -i):
    Duration: 00:01:08.33, start: 0.000000, bitrate: 60107 kb/s
    Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 59959 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)

mpv log (mpv -v): 
[cplayer] Reading config file /etc/mpv/mpv.conf
[cplayer] Setting option 'hwdec' = 'vaapi' (flags = 4)
[cplayer] Setting option 'hwdec-codecs' = 'all' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[ffmpeg] AVHWDeviceContext: Matched "Intel i965 driver for Intel(R) Broadwell - 1.8.3" as known driver "Intel i965 (Quick Sync)".
[vo/opengl/vaapi-egl] using VAAPI EGL interop
[vo/opengl/vaapi-egl] Supported formats:
[vo/opengl/vaapi-egl]  nv12
[vo/opengl/vaapi-egl]  p010
[vo/opengl] Reported display depth: 8
[vo/opengl] Assuming 59.981809 FPS for display sync.
[vd] Container reported FPS: 29.970030
[vd] Codec list:
[vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     h264_cuvid (h264) - Nvidia CUVID H264 decoder
[vd] Opening video decoder h264
[vd] Probing 'vaapi'...
[vd] Trying hardware decoding.
[vd] Selected video codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[ad] Codec list:
[ad]     aac - AAC (Advanced Audio Coding)
[ad]     aac_fixed (aac) - AAC (Advanced Audio Coding)
[ad] Opening audio decoder aac
[ad] Requesting 1 threads for decoding.
[ad] Selected audio codec: aac (AAC (Advanced Audio Coding))
[cplayer] Starting playback...
[vd] Pixel formats supported by decoder: vdpau vaapi_vld yuvj420p
[vd] Codec profile: High (0x64)
[vd] Unsupported hw decoding format: yuv420p
[vd] Requesting pixfmt 'yuvj420p' from decoder.
[ffmpeg/video] h264: Reinit context to 3840x2160, pix_fmt: yuvj420p
[vd] Falling back to software decoding. 

Any ideias ?

Tks.

**Comment by wm4** [comment]
Seems like this is another retarded ffmpeg thing that has to be worked around in mpv.

Do you have a sample file?

**Comment by nhabongo** [comment]
Sure. Here you go: https://0x0.st/5s7.mp4
