### ISSUE TITLE
libmpv: is the OSC available when embedding the video window?

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#4795]
I'm building a libmpv based player with C# for Windows and wonder if the OSC is available when embedding the video window?

**Comment by wm4** [comment]
Yes, but the osc is disabled by default with libmpv.

**Comment by stax76** [comment]
I wasn't able to show it, is it implemented in one of the examples? So far I could only get the C# working but without OSC. IIRC I tried osc=yes but it wasn't sufficient, might it have something to do with handling of mouse move events?

**Comment by wm4** [comment]
Yes, you need to be sure it gets mouse events, somehow.

**Comment by stax76** [comment]
You mean I must capture mouse events and send it to libmpv? Maybe you can point me to related mpv code so I can figure it out from studying the related code.

**Comment by stax76** [comment]
Maybe I should try a text search for wm_mouse*

**Comment by wm4** [comment]
That depends on a lot of things, all which you don't provide here. This is also not a support forum.

**Comment by stax76** [comment]
Ok, understandable, thanks.

**Comment by stax76** [comment]
I'm stuck here, client.h mentions 'mouse' only two times but not as part of the api but only in some descriptions.

There is a mouse command described here:

https://mpv.io/manual/master/#command-interface-mouse-%3Cx%3E-%3Cy%3E-[%3Cbutton%3E-[single|double]]

but it seem to deal with clicks only but for the osc I assume mouse move would be needed.

in the c# example I tried following:

```
        private void buttonPlay_Click(object sender, EventArgs e)
        {
            if (_mpvHandle != IntPtr.Zero)
                _mpvTerminateDestroy(_mpvHandle);

            LoadMpvDynamic();
            if (_libMpvDll == IntPtr.Zero)
                return;

            _mpvHandle = _mpvCreate.Invoke();
            if (_mpvHandle == IntPtr.Zero)
                return;

            _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("input-default-bindings"), GetUtf8Bytes("yes"));
            _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("input-vo-keyboard"), GetUtf8Bytes("yes"));
            _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("osc"), GetUtf8Bytes("yes"));

            _mpvInitialize.Invoke(_mpvHandle);
            _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("keep-open"), GetUtf8Bytes("always"));

            _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("input-default-bindings"), GetUtf8Bytes("yes"));
            _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("input-vo-keyboard"), GetUtf8Bytes("yes"));
            _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("osc"), GetUtf8Bytes("yes"));

            int mpvFormatInt64 = 4;
            var windowId = pictureBox1.Handle.ToInt64();
            this.ActiveControl = pictureBox1;
            _mpvSetOption(_mpvHandle, GetUtf8Bytes("wid"), mpvFormatInt64, ref windowId);
            DoMpvCommand("loadfile", textBoxVideoSampleFileName.Text);
        }
```
unfortunately it didn't help

in the source code I searched for wm_mouse* and found a function called mp_input_set_mouse_pos but it didn't give be any clues how to reach it from the api.

I do not know what the abbreviation vo stands for.

Maybe it's simply not possible, I mean most people who do embedd will probably code there own UI but it's quite much work and the built in osc is totally fine.

**Comment by wm4** [comment]
Then maybe the win32 window mpv creates doesn't receive any mouse input.

For mouse moves: ` If <button> is omitted, only the position will be updated.`

**Comment by stax76** [comment]
I'll try it tonight. Danke :-)

**Comment by stax76** [comment]
According to spy++ the mpv window is not getting any messages, I think it's due to how winforms work, I'll have to refresh and improve my winforms and winapi knowledge.

**Comment by stax76** [comment]
I can make it show as long as the mouse moves but the moment it stops moving it disappears, has anybody a idea for possible reasons? In the code below I add a message filter where I should rather overwrite WndProc but that's unrelated.

```
        private void buttonPlay_Click(object sender, EventArgs e)
        {
            if (_mpvHandle != IntPtr.Zero)
                _mpvTerminateDestroy(_mpvHandle);

            LoadMpvDynamic();
            if (_libMpvDll == IntPtr.Zero)
                return;

            _mpvHandle = _mpvCreate.Invoke();
            if (_mpvHandle == IntPtr.Zero)
                return;

            _mpvInitialize.Invoke(_mpvHandle);
            _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("osc"), GetUtf8Bytes("yes"));
            _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("osd-duration"), GetUtf8Bytes("3000"));
            _mpvSetOptionString(_mpvHandle, GetUtf8Bytes("keep-open"), GetUtf8Bytes("always"));
            int mpvFormatInt64 = 4;
            var windowId = pictureBox1.Handle.ToInt64();
            _mpvSetOption(_mpvHandle, GetUtf8Bytes("wid"), mpvFormatInt64, ref windowId);
            DoMpvCommand("loadfile", @"D:\Temp\StaxRip\doku.mkv");
            Thread.Sleep(1000);
            mpvHwnd = FindWindowEx(pictureBox1.Handle, IntPtr.Zero, "mpv", null);
            picBoxHwnd = pictureBox1.Handle;
            Application.AddMessageFilter(new TestMessageFilter());
        }

        [DllImport("user32.dll", CharSet = CharSet.Auto)]
        public static extern string SendMessage(IntPtr hWnd, int msg, IntPtr wParam, IntPtr lParam);

        public static IntPtr picBoxHwnd;
        public static IntPtr mpvHwnd;

        [SecurityPermission(SecurityAction.LinkDemand, Flags = SecurityPermissionFlag.UnmanagedCode)]
        public class TestMessageFilter : IMessageFilter
        {
            public bool PreFilterMessage(ref Message m)
            {
                if (m.HWnd == picBoxHwnd)
                {
                    SendMessage(mpvHwnd, m.Msg, m.WParam, m.LParam);
                    return true;
                }
                return false;
            }
        }

        [DllImport("user32.dll", CharSet = CharSet.Unicode)]
        static extern IntPtr FindWindowEx(IntPtr parentHandle, IntPtr childAfter, string lclassName, string windowTitle);
```

**Comment by wiiaboo** [comment]
https://mpv.io/manual/master/#options-cursor-autohide ?

**Comment by stax76** [comment]
I found something, in mpv the the mpv window gets messages like so:

<003247> 0000000000110498 P WM_MOUSEMOVE fwKeys:0000 xPos:812 yPos:249
<003248> 0000000000110498 S WM_NCHITTEST xPos:891 yPos:702
<003249> 0000000000110498 R WM_NCHITTEST nHittest:HTCLIENT
<003250> 0000000000110498 S WM_SETCURSOR hwnd:00110498 nHittest:HTCLIENT wMouseMsg:WM_MOUSEMOVE
<003251> 0000000000110498 R WM_SETCURSOR fHaltProcessing:False
<003252> 0000000000110498 P WM_MOUSEMOVE fwKeys:0000 xPos:799 yPos:249
<003253> 0000000000110498 S WM_NCHITTEST xPos:867 yPos:702
<003254> 0000000000110498 R WM_NCHITTEST nHittest:HTCLIENT
<003255> 0000000000110498 S WM_SETCURSOR hwnd:00110498 nHittest:HTCLIENT wMouseMsg:WM_MOUSEMOVE
<003256> 0000000000110498 R WM_SETCURSOR fHaltProcessing:False
<003257> 0000000000110498 P WM_MOUSEMOVE fwKeys:0000 xPos:775 yPos:249
<003258> 0000000000110498 S WM_NCHITTEST xPos:846 yPos:693
<003259> 0000000000110498 R WM_NCHITTEST nHittest:HTCLIENT

in the c# player the mpv window get these:

<064256> 0000000000090658 S WM_MOUSEMOVE fwKeys:0000 xPos:1082 yPos:412
<064257> 0000000000090658 R WM_MOUSEMOVE
<064258> 0000000000090658 P WM_MOUSELEAVE
<064259> 0000000000090658 S WM_PAINT hdc:00000000
<064260> 0000000000090658 R WM_PAINT
<064261> 0000000000090658 S WM_PAINT hdc:00000000
<064262> 0000000000090658 R WM_PAINT
<064263> 0000000000090658 S WM_PAINT hdc:00000000
<064264> 0000000000090658 R WM_PAINT
<064265> 0000000000090658 S WM_PAINT hdc:00000000
<064266> 0000000000090658 R WM_PAINT
<064267> 0000000000090658 S WM_PAINT hdc:00000000
<064268> 0000000000090658 R WM_PAINT
<064269> 0000000000090658 S WM_MOUSEMOVE fwKeys:0000 xPos:1086 yPos:402
<064270> 0000000000090658 R WM_MOUSEMOVE
<064271> 0000000000090658 P WM_MOUSELEAVE
<064272> 0000000000090658 S WM_PAINT hdc:00000000
<064273> 0000000000090658 R WM_PAINT
<064274> 0000000000090658 S WM_PAINT hdc:00000000
<064275> 0000000000090658 R WM_PAINT
<064276> 0000000000090658 S WM_PAINT hdc:00000000
<064277> 0000000000090658 R WM_PAINT
<064278> 0000000000090658 S WM_PAINT hdc:00000000
<064279> 0000000000090658 R WM_PAINT
<064280> 0000000000090658 S WM_PAINT hdc:00000000
<064281> 0000000000090658 R WM_PAINT
<064282> 0000000000090658 S WM_PAINT hdc:00000000
<064283> 0000000000090658 R WM_PAINT
<064284> 0000000000090658 S WM_MOUSEMOVE fwKeys:0000 xPos:1089 yPos:389
<064285> 0000000000090658 R WM_MOUSEMOVE
<064286> 0000000000090658 P WM_MOUSELEAVE

Instead of sending the messages with SendMessage I will try the mpv mouse command.

**Comment by stax76** [comment]
I can also try to prevent messages being sent to the parent picture box, that might as well fix it.

**Comment by wm4** [comment]
That entirely depends on how win32 propagate messages, and how WinForms uses win32.

**Comment by stax76** [comment]
I think winforms is somehow similar than mfc using wm_reflect, each control has it's own wndproc, generally I'm rather clueless about the whole topic, I didn't find much info about how exactly winforms work and if this wasn't bad enough I've not programmed pure win32. It's gonna take some time until I have everything working how I want it.

**Comment by stax76** [comment]
Using the mpv mouse command fixes it but I cannot get single click working, I verified the code gets executed and the coordinates should be ok (osc appears as soon as I enter the below half).

```
using System.Windows.Forms;

namespace mpvnet
{
    public partial class MainForm : Form
    {
        public MainForm()
        {
            InitializeComponent();
            Program.Form = this;
            mpv.Init(Handle);
        }

        protected override void OnMouseMove(MouseEventArgs e)
        {
            base.OnMouseMove(e);
            mpv.CommandString($"mouse {e.X} {e.Y}");
        }

        protected override void OnMouseClick(MouseEventArgs e)
        {
            mpv.CommandString($"mouse {e.X} {e.Y} MOUSE_BTN0 single");
            mpv.CommandString($"mouse {e.X} {e.Y} 0 single");
            mpv.CommandString($"mouse {e.X} {e.Y} MOUSE_BTN1 single");
            mpv.CommandString($"mouse {e.X} {e.Y} 1 single");

            mpv.Command("mouse", e.X.ToString(), e.Y.ToString(), "0");
            mpv.Command("mouse", e.X.ToString(), e.Y.ToString(), "1");
            mpv.Command("mouse", e.X.ToString(), e.Y.ToString(), "MOUSE_BTN0");
            mpv.Command("mouse", e.X.ToString(), e.Y.ToString(), "MOUSE_BTN1");

            base.OnMouseClick(e);
        }
    }
}
```

**Comment by rossy** [comment]
Yeah, mpv disables the video window in ``--wid`` mode, which means it won't get any keyboard or mouse input:
https://github.com/mpv-player/mpv/blob/037c7a927928/video/out/w32_common.c#L1421-L1422

This is kind of on purpose, so programs embedding the mpv window can handle the mouse input themselves for things like context menus. It's possible we could make this behaviour optional, but it might be better to just use the ``mouse`` command.

> Using the mpv mouse command fixes it but I cannot get single click working, I verified the code gets executed and the coordinates should be ok (osc appears as soon as I enter the below half). None of the playback controls of the osc is reacting.

Hmm, I wonder if this is because OSC buttons are activated on mouse-up. I don't think the ``mouse`` command can generate mouse-up events. It should probably be improved.

**Comment by stax76** [comment]
I tried with SendMessage and it works but it gets sent repeatedly in a loop for unknown reasons. There is a .NET class called NativeWindow I can try next.

```
        protected override void WndProc(ref Message m)
        {
            if (m.Msg == 0x0201 || // WM_LBUTTONDOWN
                m.Msg == 0x0202 || // WM_LBUTTONUP
                m.Msg == 0x0100)   // WM_KEYDOWN
            {
                Native.SendMessage(mpv.MpvWindowHandle, m.Msg, m.WParam, m.LParam);
            }

            base.WndProc(ref m);
        }
```

**Comment by stax76** [comment]
I have everything working now. :-) Keys were sent repeatedly because I've sent only WM_KEYDOWN and not WM_KEYUP.
