### ISSUE TITLE
Forward seek snaps to next keyframe instead of nearest keyframe

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#4796]
### mpv version and platform

0.26.0, Windows 7 SP1

### Reproduction steps
Get or make a video with a keyframe interval of 10 seconds (uploaded to sample files)
To make: `ffmpeg -i input.mkv -c:v libx264 -preset ultrafast -r 30 -g 300 output.mp4`
Open the video with mpv. (this will start its playback)
Seek forward with mouse wheel up.
### Expected behavior
Seek forward by 10 seconds.
### Actual behavior
Seek forward by 20 seconds (to the next keyframe)
### Sample files
**(might be very loud)** https://qt.vidyagam.es/Oi1w9dC.mp4

**Comment by wiiaboo** [comment]
Makes more sense than seeking forward and ending up in a previous keyframe?

**Comment by garoto** [comment]
Hmm, I thought this is what `hr-seek` was about (not trying to be snarky).

**Comment by wiiaboo** [comment]
`hr-seek` does exact seeks, which might slow.

**Comment by garoto** [comment]
Yeah, I realize now what your 1st reply was about and the OP issue.

**Comment by UserNaem** [comment]
I guess I can't blame the player for this unusual behavior on poor encodes, but still, I wish there was an option to snap to nearest keyframe on seeking.

**Comment by wiiaboo** [comment]
That really wouldn't make much sense anyway. If you're at 1, seek forward to 3 and the next keyframe is only at 10, you'd want to go back to 0?

**Comment by UserNaem** [comment]
Fair enough, I guess I should use precise seeking instead.
