### ISSUE TITLE
Menu Bar improvements: Missing items and shortcuts

### ISSUE THREAD

**Issue by baskerville** [mpv-player/mpv#4797]
The following standard shortcut is missing: *Hide Others* (bound to *⌥⌘H*).

**Comment by Akemi** [comment]
there are even more "Standard menu items" and their shortcuts missing. like "Show All", CMD+P for "Print", all the different Find ones, etc.

that being said, feel free to discuss what should be added and what doesn't make sense.

**Comment by guoyf** [comment]
"About" is necessary, I think.

**Comment by Akemi** [comment]
> "About" is necessary, I think.

it's already there.

**Comment by guoyf** [comment]
Really? But I just can't find it. I'm using the build by stolendata.

**Comment by Hrxn** [comment]
Changes are not in the release version yet, I think..

**Comment by Akemi** [comment]
see PR #4687, with some screenshots.

**Comment by Akemi** [comment]
added by 0d964471b81f3b136c29f4bd659796f47fb49892.
