### ISSUE TITLE
Hard-Coded Window Icon

### ISSUE THREAD

**Issue by NoSuck** [mpv-player/mpv#4800]
Thank you for the most useful video player around.

### mpv version and platform

mpv 0.26.0
Linux 4.12.8-1-ARCH #1 SMP PREEMPT Thu Aug 17 08:37:20 CEST 2017 x86_64 GNU/Linux

### Reproduction steps

Open any video with mpv.

### Expected behavior

I expect mpv's window to have `$HOME/.icons/$THEME/$RESOLUTION/apps/mpv.png` or `/usr/share/icons/$THEME/$RESOLUTION/apps/mpv.png` as its icon.

### Actual behavior

The window instead uses a hard-coded icon apparently included from `video/out/x11_icon_*.inc`.  Perhaps #2414 is related?

**Comment by rossy** [comment]
> I expect mpv's window to have ``$HOME/.icons/$THEME/$RESOLUTION/apps/mpv.png`` or ``/usr/share/icons/$THEME/$RESOLUTION/apps/mpv.png`` as its icon.

Note that getting the correct icon is much more complicated than this. The icon theme can be in any XDG data directory, and all bets are off with regards to the subdirectories. Some themes have the size first, eg. ``16x16/apps``, and others have the "category" first eg. ``apps/16``. The only way to know where to look is to parse the XDG index.theme file and implement the full [icon lookup algorithm][1].

Qt and GTK applications get this XDG icon spec parsing "for free" from the framework, but a raw X11 application like mpv must do it all manually. It's possible, but complicated.

[1]: https://standards.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup

**Comment by wm4** [comment]
Yes, we're unlikely to implement this complexity.

**Comment by NoSuck** [comment]
> Qt and GTK applications get this XDG icon spec parsing "for free" from the framework, but a raw X11 application like mpv must do it all manually. It's possible, but complicated.

How about compromising with an mpv.conf/command-line setting?  Users could specify an icon path, and mpv would use that:

	window-icon=/usr/share/icons/whatever.png

Anything is better than hard-coded.
