### ISSUE TITLE
Buffering stalling for livestreams

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4805]
### mpv version and platform
mpv 0.26
Windows 10 x64 Creators Update
(I once reported this for YouTube livestreams, but it probably won't hurt to have a case without youtube-dl in between)

### Reproduction steps
Open this livestream with mpv:
https://zdf1314-lh.akamaihd.net/i/de14_v1@392878/master.m3u8

### Expected behavior
Playback should be stable.

### Actual behavior
Playback stalls after a short period because buffer runs empty and doesn't get refilled.
VLC Player plays the stream without buffering issues.

### Log file
http://sprunge.us/hCIK

**Comment by aufkrawall** [comment]
Ok, I just realized that mpv also uses youtube-dl for HLS.
However, buffering/playback doesn't seem to stall when players are fed via pipes by youtube-dl. Have to confirm this further though.

**Comment by wiiaboo** [comment]
Problem is FFmpeg's handling of HLS. Piping it from livestreamer/streamlink is recommended instead.

**Comment by timofonic** [comment]
@wiiaboo Are there a script to automate it? :D

It's [StreamLink](https://streamlink.github.io/). [Livestreamer](http://livestreamer.io) got abandoned and forked to Streamlink, don't remember it ;)

There's an [API Guide](https://streamlink.github.io/api_guide.html#api-guide) too!

**Comment by wiiaboo** [comment]
No script that I know of. Just open livestreams with streamlink. There's no easy way to distinguish videos from livestreams in youtube.

**Comment by wm4** [comment]
Does anyone know whether the better performance is due to reusing the HTTP connection for segments?

**Comment by aufkrawall** [comment]
I think there is something very broken with ffmpeg on Windows in general. Also when I use youtube-dl or Livestreamer to feed mpv or any other player, there are always buffering issues.
I definitely don't encounter them on Linux. On Linux even YouTube livestreams work without problems, while they usually stop buffering enough instantly or shortly after start of playback on Windows.
(Of course livestreams in general work on that Windows system, like in the web browser or it seems also VLC).

So probably not mpv's fault at all, but still a real annoyance. 
How are the chances that it ever will get fixed? Somehow bring it to ffmpeg developers attention?

**Comment by wiiaboo** [comment]
If it's Windows-only, it could be from using SChannel instead of GnuTLS or OpenSSL. Try mpv built with either of those and see if there are still buffering issues.

From my own experience SChannel has worked fine.

**Comment by aufkrawall** [comment]
I only once crosscompiled mpv for Windows on Linux. Maybe I get to it at some point, but I'd really appreciate it if someone with a ready build environment could do this.

**Comment by wiiaboo** [comment]
https://i.fsbn.eu/mpv-schannel.7z
https://i.fsbn.eu/mpv-libressl-lgpl.7z
https://i.fsbn.eu/mpv-gnutls.7z
here you go

**Comment by wm4** [comment]
Another theory: Linux, or some TLS libs, are simply faster at establishing a new HTTPS connection.

**Comment by aufkrawall** [comment]
Thanks a lot, wiiaboo!
Unfortunately, it doesn't seem to make a difference whether I choose SChannel, GnuTLS or OpenSSL. :(

**Comment by aufkrawall** [comment]
Good news:
The issue seems to be entirely caused by the program cFosSpeed which offers traffic shaping at network driver level.
As soon as I uninstall it, buffering of livestreams on Windows works as well as on Linux. At least I could watch hours of YT and other HLS without any buffering issues over the past few days, while the issue instantly reappeared after I installed cFosSpeed again.
So not an mpv issue, I'm closing this ticket, and #4004 as well.
