### ISSUE TITLE
Something analog to mplayers 'change_rectangle <val1> <val2>' through ipc?

### ISSUE THREAD

**Issue by Selur** [mpv-player/mpv#4808]
Is there something analog to mplayers 

> change_rectangle <val1> <val2>
    Change the position of the rectangle filter rectangle.
        <val1>
            Must be one of the following:
                0 = width
                1 = height
                2 = x position
                3 = y position
        <val2>
            If <val1> is 0 or 1:
                Integer amount to add/subtract from the width/height.
                Positive values add to width/height and negative values
                subtract from it.
            If <val1> is 2 or 3:
                Relative integer amount by which to move the upper left
                rectangle corner. Positive values move the rectangle
                right/down and negative values move the rectangle left/up.

which can be used through mpvs ipc interface?

**Comment by lachs0r** [comment]
Not that I know of. You can try getting FFmpeg folks to add command support to the drawbox filter in lavfi, though. With that, you could use filter labels and `vf-command`.

**Comment by Selur** [comment]
As far as I know, lavfi does support drawbox, so I'll look into that. :)
Thanks!
