### ISSUE TITLE
Allow the user to pick video quality for YouTube links

### ISSUE THREAD

**Issue by Fuuzetsu** [mpv-player/mpv#481]
Currently it seems that `mpv <youtubelink>` will play the best quality video. In cases where I'm on a netbook with a small screen and 1024x768, there really is no need for it to choke on 1080p videos. It'd be great to be able to choose the quality. 
Currently I end up having to use youtube-dl wrapper script which is a shame considering mpv has YouTube support.

I'm unsure whether this should just be merged under #287.

**Comment by wm4** [comment]
All of this is obsolete. We stopped using quvi. We now use youtube-dl, and you can pass the quality setting to ``--ytdl-format``. What parameter this takes is up to youtube-dl's ``--format`` parameter.
