### ISSUE TITLE
Make secondary subtitle configurable after running

### ISSUE THREAD

**Issue by lllllllllllllllllllllllllllllllllllllll** [mpv-player/mpv#4810]
Currently, we can only add secondary subtitle by the command line argument `--secondary-sid`. Please add input commands like `sub-secondary-add`, `sub-secondary-remove`.

Moreover, for the time being, it is not possible to change some essential properties of the secondary subtitle, e.g. the position of the subtitle on the screen, delay of the subtitle. Please make it as flexible as the primary subtitle.

**Comment by wm4** [comment]
`secondary-sid` is available at runtime in the same form as on the command line, and `sub-add` etc. works orthogonally.
