### ISSUE TITLE
MPV no --option to adjust OSD for 3D SBS

### ISSUE THREAD

**Issue by mac010** [mpv-player/mpv#4811]
### mpv version and platform

All / all platforms (in my case 0.26 on Fedora 26)

### Reproduction steps

1. Use MPV as a media player on a media PC connected to a 3DTV.
2. Play a 3D video file with MPV.
3. Switch TV into 3D mode (always SBS afaik)

### Expected behavior

MPV having an --option to duplicate the OSD and mouse pointer over both sides of the screen for 3D playback.

### Actual behavior

The OSD overlays as is which create a pretty trippy effect, and renders the buttons useless.

**Comment by wm4** [comment]
Already exists in some form.

**Comment by mac010** [comment]
Hi wm4, thanks for the awesome player! erm just wondering what the --option is then, i have searched the man for "osd" and "3d" and don't see anything?

**Comment by wm4** [comment]
You probably have to flag the video as 3D with -vf format (some suboption of it), and then possibly prevent it from "downmixing" it to mono with --video-stereo or whatever it was.

**Comment by mac010** [comment]
Adjusted my play script, thank you =)

**Comment by avih** [comment]
> Adjusted my play script, thank you =)

You could share your settings in case others need similar help.

**Comment by mac010** [comment]
Hi, yeah sure.

I use this line for 3D videos if I need to swap L/R frame to match my TV's 3D mode (as my TV's function to do this doesn't seem to work):
mpv --vf=format=stereo-out=sbs2l,stereo3d=sbsl:sbsr --video-stereo-mode=no
I use this line for 3D videos that start on a frame that matches my TV:
mpv --vf=format=stereo-out=sbs2l

The --vf=format=stereo-out=sbs2l is great for the UI, but subtitle playback while overlaid correctly is stretched/large and the --sub-font-size option doesn't seem to work.

Is it possible to have the --vf=format=stereo-out ignore the subtitles? I much prefer the subs created with sub3dtool, as these can have 3d depth and whatever font/size you want, but these are already sbs format so playback with --vf=format=stereo-out=sbs2l results in side by side subs.

**Comment by wm4** [comment]
Well, I could remove OSD/subtitle duplication entirely, if it's not useful.

**Comment by mac010** [comment]
Hmm I'd be happy, but I wouldn't ask in case others use it successfully, maybe an on/off param/switch?
