### ISSUE TITLE
OSD re-appears upon focusing a different window, if the mouse escaped from below

### ISSUE THREAD

**Issue by ear** [mpv-player/mpv#4812]
### mpv version and platform

mpv v0.26.0 - OS X El Capitan 10.11.6

### Reproduction steps

* Open a Video
* Hover over the bottom part of the window with the mouse so that the OSD pops up
* Click on a window under it—actually under, as in, vertically down from it
* While moving the mouse away from the mpv window, the OSD correctly disappears
* When the focus goes to the window clicked, the OSD *reappears*

### Expected behavior

The OSD should not re-appear.

### Actual behavior

The OSD re-appears for no reason.

For it to disappear one has to hover the mouse anywhere on top of the mpv window and then move it away. mpv does not need to be re-focused for the OSD to disappear for good: just moving the mouse over and away works.

### Log file

Do I need to make one of those?

### Sample files

I'm playing a youtube video with it so I guess you can do the same. I ran it with the following command line:

```
open -n -a mpv --args "--ytdl-format=247+251" https://www.youtube.com/watch?v=wlxcafXlfs4
```

### Screenshots

I thought I'd show you what happens, visually, too:

1. mpv window focused, mouse inside the window, hovering over the bottom part where the OSD screen appears
![1-over](https://user-images.githubusercontent.com/2104122/29795113-252b08a0-8c4b-11e7-9d00-4e75d5e3ae7d.jpg)
1. if the mouse exits from the mpv window from any of these marked zones (the red strips) the OSD disappears, BUT…
![3-hot](https://user-images.githubusercontent.com/2104122/29795121-2b6c8450-8c4b-11e7-87be-0673b50be8ec.jpg)
1. as soon as one clicks on another window, mpv is unfocused and blink! the OSD appears again on the mpv window:
![2-under](https://user-images.githubusercontent.com/2104122/29795118-28a536f4-8c4b-11e7-8eec-3e88bfe64f4f.jpg)

If one exits the window from any other side (the top, and the left and right parts that are not part of the OSD) the OSD does _not_ come up again, correctly.

Thank you for taking the time to read this bug report.

**Comment by Akemi** [comment]
it doesn't do that here. are you sure you are using 0.26? since `open -n -a mpv --args "--ytdl-format=247+251" https://www.youtube.com/watch?v=wlxcafXlfs4` that invocation shouldn't work anymore. at least it won't open a youtube video like this, since arguments are being discarded like this in mpv's case.

**Comment by Akemi** [comment]
0.26 should also have have a toggle fullscreen and volume button on the OSC, which is missing from your screenshot.

**Comment by ear** [comment]
Thank you for the incredibly fast response.

You are right, turns out my `open` command was opening an older version. Argh.

Good news: the bug is not there on the REAL new version.
Bad news: I can't pass arguments down to ytdl anymore? Do you have any suggestions about that?

**Comment by Akemi** [comment]
put it into your mpv.conf file in `~/.config/mpv `or use the mpv binary directly in the bundle `mpv.app/Contents/MacOS/mpv`

**Comment by ear** [comment]
OK `/Applications/mpv.app/Contents/MacOS/mpv --ytdl-raw-options="format=247+251" https://www.youtube.com/watch?v=wlxcafXlfs4` does seem to work. I need it on a per-video basis, can't set it globally.

Unfortunate `open -n -a mpv --args` does not seem to work though. Do you happen to know why that is?

**Comment by Akemi** [comment]
yes because `mpv-wrapper.sh` discards those arguments before launching mpv.

**Comment by ear** [comment]
You're right!

```
$ cat mpv-wrapper.sh
#!/bin/bash -l
export MPVBUNDLE="true"
$SHELL -c "$(dirname "$0")/mpv --player-operation-mode=pseudo-gui $*"

$ open -n -a mpv --args '--ytdl-raw-options="format=247+251"' https://www.youtube.com/watch?v=wlxcafXlfs4
```

This works 😄 

Thanks again for the help @Akemi. Much appreciated!

**Comment by Akemi** [comment]
alternatively you could put `/Applications/mpv.app/Contents/MacOS/` into your path or symlink `/Applications/mpv.app/Contents/MacOS/mpv` into `/usr/local/bin`. then you could launch mpv just via `mpv`.

what you did might break the bundle in other cases though.

**Comment by ear** [comment]
Yeah. I will have to do that I think. Maybe write it in my own wrapper (say in `~/.bin/mpv`) so that I also don't get the console output, just like one gets from the bundled wrapper.

**Comment by Akemi** [comment]
`mpv --ytdl-raw-options="format=247+251 https://www.youtube.com/watch?v=wlxcafXlfs4 > /dev/null 2>&1 &`, a bit less convenient.
