### ISSUE TITLE
Simple rounding output depth

### ISSUE THREAD

**Issue by age1988** [mpv-player/mpv#4815]
Hi!
Is it possible to add as a feature request to choose the output bitdepth like 8 or 10 bit  but with no dither and simple rounding ?
I found is visually better if mpv does  this last step because some gpus with their own algorithm could degrade a bit the quality of the output
Thanks :-)

**Comment by haasn** [comment]
Huh? How would an implementation get rounding wrong? Screenshot? And what's to say they won't round your output either?

**Comment by aufkrawall** [comment]
I think the manpage and default setting are a bit misleading here.
There is no dithering done by the GPU driver, so either you let mpv do it or get banding. My vote would really be to enable dithering to 8 bit by default.

**Comment by age1988** [comment]
if dither is disabled the output should be the same with or without this custom shader

//!HOOK OUTPUT
//!BIND HOOKED


vec4 hook() {
    vec4 c = HOOKED_tex(HOOKED_pos);
    c = ((round(c *255.0))/255.0);
    return c;
}


I admit probably this shader is not correct :-) but I see some small difference, without this shader the output is a little more washed out.
It's even possibile there's something wrong just about my monitor or my pc
