### ISSUE TITLE
mpv doesn't load opengl-shader when not run via cmd.exe unless full path is specified

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4817]
### mpv version and platform
mpv build by shinchiro 2017-08-26 x64
Windows 10 x64 Creators Update

### Reproduction steps
In my mpv config, I got
opengl-shaders="antiring.hook"
The shader is placed in mpv.exe main directory.
I open video files via cmd.exe (mpv.exe path/video.mkv) and Windows Explorer.

### Expected behavior
It shouldn't make a difference for the shader to get loaded either if mpv opens a video file via cmd.exe or Windows Explorer.

### Actual behavior
There is a difference: The shader doesn't get loaded when mpv is run via Windows Explorer, but it does get loaded when run via cmd.exe.
However: It also gets loaded when run via Windows Explorer when I point to the shader in mpv.conf with its full absolute path (e.g. opengl-shaders="C:\Users\USER\AppData\Local\mpv\antiring.hook").

### Log file
Well, I guess it's obvious even without log? Of course I will post it if you still want it.

Oh, and btw: It would be really great if it wasn't necessary to load an external shader for antiringing with EWA scalers.

**Comment by avih** [comment]
> Well, I guess it's obvious even without log? Of course I will post it if you still want it.

Post it. While the symptom is obvious, the reason might not be, and the log could help.

**Comment by lachs0r** [comment]
You need to use `~~/antiring.hook` to specify a path relative to one of mpv’s configuration directories.

**Comment by garoto** [comment]
Good to know prefixing `~~` to file locations in mpv.conf will also search in `mpv.exe` base directory as well.

**Comment by haasn** [comment]
https://mpv.io/manual/master/#files-on-windows

**Comment by garoto** [comment]
```
Config files located in the same directory as mpv.exe are loaded with lower priority. 
```

I guess this is it then.
