### ISSUE TITLE
mpv is scaled on hidpi wayland

### ISSUE THREAD

**Issue by kaueraal** [mpv-player/mpv#4821]
### mpv version and platform

mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.3

on Fedora 26 amd64 using wayland/gnome3

with config

```
hwdec=vaapi
framedrop=decoder+vo
vo=opengl
opengl-backend=wayland
scale=spline36
dscale=mitchell
dither-depth=auto
correct-downscaling
cache=yes
alang=jp,jpn,en,eng,de,ger,deu
slang=en,eng,de,deu,ger
osd-duration=2000
sub-bold=yes
sub-margin-y=40
sub-font-size=45
sub-font="Droid Sans"
```

### Reproduction steps

Run mpv with video output on a hidpi screen with wayland/gnome 3 with enabled scaling.

### Expected behavior

The scaling of the video is solely done by mpv. Probably the same scaling should be applied by mpv with the configured algorithm and the fonts rendered proportionally larger. 

### Actual behavior

mpv is scaled by wayland/gnome 3, as it does not advertises itself as hidpi-compatible.

**Comment by kaueraal** [comment]
This is done correctly, mpv solely reports wrong values.

**Comment by wm4** [comment]
What does it report wrongly?

**Comment by kaueraal** [comment]
I just wanted to link it, see https://github.com/mpv-player/mpv/issues/4822 .
