### ISSUE TITLE
wrongly reported vo-dimensions on hidpi-screen

### ISSUE THREAD

**Issue by kaueraal** [mpv-player/mpv#4822]
### mpv version and platform

mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
built on UNKNOWN
ffmpeg library versions:
libavutil 55.58.100
libavcodec 57.89.100
libavformat 57.71.100
libswscale 4.6.100
libavfilter 6.82.100
libswresample 2.7.100
ffmpeg version: 3.3.3

on Fedora 26 amd64 using wayland/gnome 3

### Reproduction steps

Run mpv with video output on a hidpi screen with wayland/gnome 3 with enabled scaling.

### Expected behavior

mpv reports that it scales the output and not gnome 3/wayland.

### Actual behavior

mpv outputs (at first) only the non-scaled resolution like
```VO: [opengl] 1280x720 vaapi[nv12]```

When run with `-v` it outputs the real resolution and scale it uses later:
```[vo/opengl/wayland] resizing 1280x720 -> 1280x720
[vo/opengl] Resize: 2560x1440
[vo/opengl] Window size: 2560x1440
[vo/opengl] Video source: 1280x720 (1:1)
[vo/opengl] Video display: (0, 0) 1280x720 -> (0, 0) 2560x1440
[vo/opengl] Video scale: 2.000000/2.000000
```

First I assumed that the output is scaled by wayland, see #4821 .

**Comment by wm4** [comment]
No, this line always shows the source video size.

The values shown with -v are the pixel sizes, so if you started the player fullscreened, 2560x1440 should be the native resolution of your screen. (If not, the wayland compositor must be scaling it.)

**Comment by kaueraal** [comment]
Still, I do not think that it should. The video out is not a this resolution. Otherwise the size can get removed there, as it is already listed a few lines above in the video content with
```
(+) Video --vid=1 (*) (h264 1280x720 23.976fps)
```
