### ISSUE TITLE
easier auto profiles needed

### ISSUE THREAD

**Issue by truexfan81** [mpv-player/mpv#4824]
Mpv needs an auto profile feature that can be used without having to know how to code.  Current method is just too complicated/confusing.

**Comment by Hrxn** [comment]
> [..] having to know how to code.

Not really..

**Comment by truexfan81** [comment]
"Not really.."  Ok i want to have 2 profiles, 1 for 50+fps videos, and one for everything else, how do i configure that? I tried everything i could think of yesterday, all i got for my effort was a headache.

**Comment by Argon-** [comment]
`profile-dec=cond:p.container_fps > 50`

You don't have to know anything about programming. You need to know about the properties that exist (see here: https://mpv.io/manual/master/#property-list) how you can access them (**3** ways are illustrated in auto-profiles.lua) and what `=, <, >` are.

**Comment by truexfan81** [comment]
i tried using container-fps, i guess i just can't figure out the syntax, i just kept telling me 
[auto_profiles] Profile 'other' condition: [string "profile other condition"]:1: unexpected symbol near '?'
[auto_profiles] Profile '50/60p' condition: [string "profile 50/60p condition"]:1: unexpected symbol near '?'

this was when trying to use profile-dec=cond:p.container_fps >= 50
and profile-dec=cond:p.container_fps <= 49 for the other profile  maybe it got confused by having both > and =?

**Comment by Argon-** [comment]
Post your profile + condition please.

**Comment by truexfan81** [comment]
am in the process of recreating them now, after i got frustrated with it yesterday i deleted them and went back to manually changing settings.

**Comment by Argon-** [comment]
You deleted the profiles but kept the printed error message?

**Comment by truexfan81** [comment]
i never closed the ps window, anyway i tried it again with the condition you provided and got a different error.   http://pastebin.centos.org/207021/50436369/

**Comment by Argon-** [comment]
My bad, it's `profile-desc`.

**Comment by truexfan81** [comment]
which puts it back to the previous error

**Comment by Hrxn** [comment]
Try it like this:

```
profile-desc=cond:get('container-fps',0) >= 50
profile-desc=cond:get('container-fps',0) < 50
```

To set a default value..

I don't know if `estimated-vf-fps` works as a property, but `container-fps` does not work for "broken" files in a reliable way...

**Comment by truexfan81** [comment]
"but container-fps does not work for "broken" files in a reliable way..." i actually have an example of that, when playing this https://www.youtube.com/watch?v=p-j14U1PYMY  it does not load either profile.

**Comment by Argon-** [comment]
Nothing works reliably for a broken file. A different way of auto-profiles is not going to change the reliability of properties. 
These things have nothing to do with each other.

**Comment by Doofussy2** [comment]
I'm sorry to dig this up, but I'm having no luck getting my profile(s) to work.
@Argon- would you be so kind as to help me out?

My goal is to have a profile for 4k media to be played with a specific hwdec. I've tried variations of this;

[width]
profile-desc=cond:p.width>3500,height>1000
hwdec=nvdec-copy

I've also tried using video-codec for hevc, but I just can't get it to work. Is it possible to do this, or am I doing something wrong?

**Comment by Argon-** [comment]
It's ```p.width>3500 and p.height>1000```

**Comment by Doofussy2** [comment]
Thanks @Argon- but that doesn't work, either. I think there's something else going on, here. I see this in the log

[   0.011][f][auto_profiles] Lua error: D:/mpv/portable_config/scripts/auto-profiles.lua:143: '=' expected near '2018'
[   0.011][v][auto_profiles] Exiting...

**Comment by Argon-** [comment]
Nice but without knowing what profile-desc triggered this I can't help you

**Comment by Argon-** [comment]
Did you test if the profile gets applied? For easy testing I'd recommend you use something like `dither-depth=1`.
For me this works. Moreover, the looking at the timestamp of your log line this shouldn't be a problem evaluation your rule, that's a syntax error in the `auto-profiles.lua` script. Did you modify it?

**Comment by Doofussy2** [comment]
I have tried 'get', and/with a range of permutations. I can get nothing to work.

I was mentioning the video-codec because I would prefer to use that instead of the width, height. But can't get that to work, either. I tried (and other permutations of);

[4k]
profile-desc=cond:get('video-codec')=hevc
hwdec=nvdec-copy

[4k]
profile-desc=cond:p.video-codec=hevc
hwdec=nvdec-copy

This is the script I'm using;
[auto-profiles.lua.txt](https://github.com/mpv-player/mpv/files/2364720/auto-profiles.lua.txt)

https://github.com/wiiaboo/mpv-scripts/blob/master/auto-profiles.lua

I did remove the part with the explanation. Should I leave that i?

Thanks again @Argon-

**Comment by Doofussy2** [comment]
You mean lines 191 and 192?

-- re-evaluate all profiles immediately
on_idle()

So delete them?

**Comment by Doofussy2** [comment]
Thanks @garoto. That is working, I appreciate the help.

**Comment by Doofussy2** [comment]
@garoto thank you so much. I can now use that to implement profiles. Sweet! It works for interlaced content, too. I'm so grateful.

**Comment by Argon-** [comment]
HEVC has nothing to do with 4K though? I can have 4K with other codecs as well?

**Comment by Doofussy2** [comment]
What this is truly about, is fixing the deinterlacing problem. I have a lot of mixed content that I watch, including Live TV. There is a lot interlaced content, so I need deinterlacing. deinterlacing=yes, doesn't work well. It causes so many problems. Dropped frames with 720p Live TV, and plays havoc with 4k HDR content. So I've been trying to find a solution. Having tried the deinterlacing profile (given to me by someone else on here) and it didn't work, I thought I'd try a video-codec profile. And through trying to make it work, I found myself, here. And you guys have helped me a lot. So now I can, and have finally make the deinterlacing profile, work. And it works, great!

[Interlaced]
profile-desc=cond:p["video-frame-info/interlaced"]
vf=lavfi=yadif

Now it only get's enabled when interlaced content is detected, and leaves everything else alone. This is fantastic!

And now I've also learned how to make correct profiles. So I'm very very happy!

I did report my issue, but a solution wasn't presented. So I've been on a mission.
https://github.com/mpv-player/mpv/issues/5927

**Comment by garoto** [comment]
Why didn't you mention this was about interlaced content to begin with?

**Comment by Doofussy2** [comment]
Perhaps I should have, but my posting in this thread was more related to not being able to make any profile, work. But since you ask. Having tried to get the deinterlacing working prior, and failing, I was operating under the incorrect understanding that it didn't work at all. And I was looking for a workaround that would get me close enough to a solution. As my main issue was with mpeg2video, and HEVC 4k HDR media, I figured if I could use the video-codec profile, that would give me what I wanted. You showed me how to use that profile, correctly, and I wondered if it would work with the interlaced, profile. So I tried it. It works, and you have shown me the error of my ways :)

Sorry to have bothered you guys, but thank you again.

**Comment by garoto** [comment]
`profile-desc=cond:p["audio-codec-name"]=="mp3"`

Use single or double quotes around strings when doing comparisons.

**Comment by Doofussy2** [comment]
I tried that, too. Same result.

**Comment by garoto** [comment]
You tried **audio-codec-name** and it didn't work?

**Comment by Doofussy2** [comment]
Yeah, and as I said, this happens with multiple different profiles.

**Comment by garoto** [comment]
In this case, I have no clue. The profile condition I posted works for me.

**Comment by Doofussy2** [comment]
So if you use that profile for only mp3, set ac3 encoding minimum channel to 2, and play any audio codec other than mp3 that isn't being bitstreamed, it doesn't enable the profile and doesn't convert to AC3?

**Comment by garoto** [comment]
[Yes.](https://0x0.st/zse5.jpg)

**Comment by Doofussy2** [comment]
Ok, I'm assuming you used the script I posted, so that means my mpv build has an anomaly. I'll test other builds, and see what happens. Thanks garoto.

**Comment by garoto** [comment]
> No, I have the same issue almost all my profiles, videos too. Not just ac3enc. I was quite clear about that.

Upload all your relevant `.conf` files. And a run with `--log-file=output.log` might be important as well.

**Comment by Doofussy2** [comment]
I can generate a log and post it, later. I'll also post all of my profiles. Thanks for the help.

**Comment by Doofussy2** [comment]
> `profile-desc=cond:p["audio-codec-name"]=="mp3"`

Well, my apologies. I re-tried that, and it did indeed, work. I think that when I originally tested it, I was using multiple codecs, and not using the correct syntax. To that point, how do I add multiple codecs? Comma separation breaks the profile. Or do I need to make another profile?

**Comment by garoto** [comment]
> To that point, how do I add multiple codecs? Comma separation breaks the profile. Or do I need to make another profile?

```
profile-desc=cond:p["audio-codec-name"]=="mp3" or p["audio-codec-name"]=="aac"
```

**Comment by Doofussy2** [comment]
Thanks, that makes sense. I'll adjust it, later.

**Comment by garoto** [comment]
In case you don't know, one can _quickly_ test which and how properties really expand by adding the following line to `mpv.conf`:
```
input-ipc-server=mpv-socket
```
and then from a `cmd.exe` prompt:
```
echo show-text ${file-format} 10000 >\\.\pipe\mpv-socket
```

Replacing `${file-format}` with the desired property and where `10000` is the osd timeout in ms.

**Comment by Doofussy2** [comment]
Thank you. I'll keep that in mind for the future.
