### ISSUE TITLE
DVD playback not working properly

### ISSUE THREAD

**Issue by SharkMachine** [mpv-player/mpv#4826]
### mpv version and platform

Version: 1:0.26.0-1~xenial2 (Ubuntu 16.04)

### Reproduction steps

Try to play a DVD (region 1)

```
mpv /dev/sr0
```

### Expected behavior

It plays correctly

### Actual behavior

It doesn't

![alt text](http://sharkma.ecxol.net/beautifulll.png "NICE")

This is what it should look like:

![alt text](http://sharkma.ecxol.net/beautifulll_real.png "NICE2")

### Log file

http://sharkma.ecxol.net/mpvlog

### Sample files

Can't share a DVD

**Comment by mc4man** [comment]
Wrong command to play dvd, read the man (there probably are other commands not immediately listed as well
It's a moot point for you as the build you're using didn't enable dvdread/dvdnav anyway..

**Comment by SharkMachine** [comment]
I think it's quite clear that this is not an issue then.

**Comment by SharkMachine** [comment]
After building it with dvdread & dvdnav myself and using the correct command, it works. Thanks for guiding me to the right direction.

It's a shame there's no DVD menu support though.
