### ISSUE TITLE
MPV windows does not play utf-8 links.

### ISSUE THREAD

**Issue by super94i** [mpv-player/mpv#4829]
I'm trying to create a batch file that plays a URL.

Sample url: https://username:P_a$$word@localhost/library/Movies/%e0%b2%b2%e0%b3%82%e0%b2%b8%e0%b2%bf%e0%b2%af%e0%b2%be%20(2013)/Lucia%20(2013).mkv

it shows on cmd as:
C:\Users\Folder>mpv https://username:P_a$$word@localhost/library/Movies/b2e082b2e0bfb2e0be0(2013)/Lucia0(2013).mkv
   cplayer: Playing: https://username:P_a$$word@localhost/library/Movies/b2e082b2e0bfb2e0be0(2013)/Lucia0(2013).mkv
 ytdl_hook: ERROR: Unable to download webpage: nonnumeric port: 'P_a$$word@localhost' (caused by InvalidURL("nonnumeric port: 'P_a$$word@localhost'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 ytdl_hook: youtube-dl failed, trying to play URL directly ...
    ffmpeg: https: HTTP error 404 Not Found
    stream: Failed to open https://username:P_a$$word@localhost/library/Movies/b2e082b2e0bfb2e0be0(2013)/Lucia0(2013).mkv.
   cplayer:
   cplayer:
   cplayer: Exiting... (Errors when loading file)

contents of the bat file:
CHCP 65001
mpv https://username:P_a$$word@localhost/library/Movies/%e0%b2%b2%e0%b3%82%e0%b2%b8%e0%b2%bf%e0%b2%af%e0%b2%be%20(2013)/Lucia%20(2013).mkv
Pause

I'm using the latest windows 64 build from: https://mpv.srsfckn.biz/

**Comment by wiiaboo** [comment]
Try with `--no-ytdl`.

**Comment by super94i** [comment]
@wiiaboo 

   cplayer: Playing: https://username:P_a$$word@localhost/library/Movies/b2e082b2e0bfb2e0be0(2013)/Lucia0(2013).mkv
    ffmpeg: https: HTTP error 404 Not Found
    stream: Failed to open https://username:P_a$$word@localhost/library/Movies/b2e082b2e0bfb2e0be0(2013)/Lucia0(2013).mkv.
   cplayer:
   cplayer:
   cplayer: Exiting... (Errors when loading file)
----------------
it's trying to access folder: Movies/b2e082b2e0bfb2e0be0(2013)/Lucia0(2013).mkv
when actually it should be: Movies/%e0%b2%b2%e0%b3%82%e0%b2%b8%e0%b2%bf%e0%b2%af%e0%b2%be%20(2013)/Lucia%20(2013).mkv

**Comment by wiiaboo** [comment]
Well, that's your problem then. You need to at least quote-surround the URL. `%` is a special character in cmd.exe, so you need to escape it. Nothing to do with mpv.

**Comment by super94i** [comment]
@wiiaboo in the bat file, the link is quoted. https://i.imgur.com/KwZWmlq.png

yet when I run the cmd, that happens..

**Comment by wiiaboo** [comment]
Wrong quotes.

**Comment by super94i** [comment]
even the double quotes don't work, I've tried it.

**Comment by wiiaboo** [comment]
Use a proper terminal then that's not cmd.exe, probably.

**Comment by super94i** [comment]
To be fair, when I paste the link manually to different cmd, the link plays fine. But when I run that link from a bat, it does not work.

**Comment by wiiaboo** [comment]
Unrelated to mpv then. You need to find some other way other than using .bats to feed those url-encoded paths.

**Comment by garoto** [comment]
Percent signs in programs args in batch files needs a secondary `%`, just like it's in a `for` loop. Like:
```
https://username:P_a$$word@localhost/library/Movies/%%e0%%b2%%b2%%e0%%b3%%82%%e0%%b2%%b8%%e0%%b2%%bf%%e0%%b2%%af%%e0%%b2%%be%%20(2013)/Lucia%%20(2013).mkv
```

Microsoft quality software right there.

**Comment by super94i** [comment]
Hey, Could you please delete this issue? I would really appreciate it!
