### ISSUE TITLE
jump between playlist keeping current position

### ISSUE THREAD

**Issue by manolouy** [mpv-player/mpv#4830]
mpv-x86_64-20170718
win7 64

Hello, how do I do to keep the current position of each list individually?
I use a shortcut to switch between lists, ex:
1 loadlist "1.m3u"
2 loadlist "2.m3u"

I could not find a command to do this

**Comment by haasn** [comment]
Does `write-watch-later-config ; load playlist.m3u` help? In theory, mpv can restore the playlist index when using the “watch later” feature.

**Comment by manolouy** [comment]
Thanks for answering
I can not make it work
when switching between lists, start from the beginning again
can you show me an example conf file?

**Comment by Akemi** [comment]
this can most likely be archived with a script.
