### ISSUE TITLE
Taking screenshot doesn't work in dxinterop

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#4831]
### mpv version and platform
 
449d9725c9 - Win10-x64

### Reproduction steps

Taking screenshot with ``Ctrl-s``. Run with  `mpv --no-config --opengl-backend=dxinterop`
Got black screenshot instead. The log said `INVALID_OPERATION` occured

Doesnt happen with ANGLE backend.

### Expected behavior

Get a picture

### Actual behavior

As stated above.

### Log file

https://0x0.st/RM9.txt

**Comment by Artoriuz** [comment]
Just to add, on the same build (449d972) it works here with dxinterop if I don't --no-config.

**Comment by shinchiro** [comment]
Tested again with my other Nvidia gpu with GL 4.5, it works well (fixed #4832). Probably there is something wrong with older GL 3?

**Comment by rossy** [comment]
This might be because we map the framebuffer with WGL_ACCESS_WRITE_DISCARD_NV. It would depend on whether the driver actually makes use of this hint and makes the framebuffer write-only. I'll look into this.

**Comment by rossy** [comment]
Closing since mpv no longer reads from the frontbuffer to take window screenshots (so this should work now.)
