### ISSUE TITLE
OSD/OSC's text leftover in black border

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#4832]
### mpv version and platform

449d972 - Win10-x64

### Reproduction steps

1. Play a video which has different aspect ratio than monitor. In this case, opened 4:3 video
2. Run with `mpv --no-config --opengl-backend=dxinterop`
3. Go to fullscreen mode
4. Make osd/osc appear with seeking or hovering
5. Got leftover text in black border after they disappeared

![image](https://user-images.githubusercontent.com/9623615/30020657-376c23b8-9197-11e7-933b-a8ef3e8f6716.png)

(I need to switch to windowed mode to clean the 'text')

Doesn't happen with ANGLE backend

### Log file

https://0x0.st/RMy.txt

**Comment by Akemi** [comment]
is this still an issue with all the recent changes we have? please open a new issue if it is the case.
