### ISSUE TITLE
Youtube-dl integration broken for DASH streams in 0.26

### ISSUE THREAD

**Issue by mateon1** [mpv-player/mpv#4836]
### mpv version and platform
0.26.0, NixOS

### Reproduction steps
Try to open any Youtube link with mpv
For example: `mpv https://youtube.com/watch?v=7-2hLCIaT4k`

### Expected behavior
mpv plays the Youtube video

### Actual behavior
mpv integration fails during ytdl_hook.lua

### Log file

Full log: https://ipfs.io/ipfs/QmaEBQ8MmSgDa3H9EVrsXBMpdsZ71K3G2pAJESEZQgRcgT/mpvlog.txt

Relevant lines:
```lua
[ytdl_hook] stack traceback:
[ytdl_hook] 	[C]: in function 'len'
[ytdl_hook] 	@ytdl_hook.lua:71: in function 'edl_escape'
[ytdl_hook] 	@ytdl_hook.lua:139: in function 'edl_track_joined'
[ytdl_hook] 	@ytdl_hook.lua:171: in function 'add_single_video'
[ytdl_hook] 	@ytdl_hook.lua:454: in function 'fn'
[ytdl_hook] 	mp.defaults:518: in function 'handler'
[ytdl_hook] 	mp.defaults:339: in function 'handler'
[ytdl_hook] 	mp.defaults:458: in function 'call_event_handlers'
[ytdl_hook] 	mp.defaults:495: in function 'dispatch_events'
[ytdl_hook] 	mp.defaults:451: in function <mp.defaults:450>
[ytdl_hook] 	[C]: ?
[ytdl_hook] 	[C]: ?
[ytdl_hook] Lua error: @ytdl_hook.lua:71: bad argument #1 to 'len' (string expected, got nil)
```

### Sample files
N/A

**Comment by AirPort** [comment]
Known issue: https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058
