### ISSUE TITLE
Map frame by frame step forward/backward to mouse wheel

### ISSUE THREAD

**Issue by student-sx** [mpv-player/mpv#4838]
Can stepping forward and backward one frame (bound to . and ,) be mapped to the mousewheel, i.e. after the video is paused, scrolling in one direction moves frame by frame forward and scrolling into the other direction moves backward frame by frame.

**Comment by haasn** [comment]
Yes

**Comment by student-sx** [comment]
How can I do this?

**Comment by haasn** [comment]
input.conf

**Comment by garoto** [comment]
```
AXIS_UP frame-step
AXIS_DOWN frame-back-step
```

**Comment by coz** [comment]
Where the heck is the input.conf???

**Comment by kasper93** [comment]
> Where the heck is the input.conf???

See https://mpv.io/manual/master/#files
