### ISSUE TITLE
mpv sometimes displays wrong (green) color

### ISSUE THREAD

**Issue by mfcc64** [mpv-player/mpv#4840]
### mpv version and platform
`mpv 0.26.0-237-g5771f7abf4 (C) 2000-2017 mpv/MPlayer/mplayer2 projects`
`built on Wed Sep  6 07:03:12 WIB 2017`
`ffmpeg library versions:`
`libavutil       55.74.100`
`libavcodec      57.104.101`
`libavformat     57.81.100`
`libswscale      4.7.103`
`libavfilter     6.101.100`
`libswresample   2.8.100`
`ffmpeg version: N-87185-ge6e58de03d`
`[vo/opengl] GL_VERSION='4.5 (Core Profile) Mesa 17.1.4'`
`[vo/opengl] GL_VENDOR='Intel Open Source Technology Center'`
`[vo/opengl] GL_RENDERER='Mesa DRI Intel(R) Haswell Mobile '`
`[vo/opengl] GL_SHADING_LANGUAGE_VERSION='4.50'`

Probably, regression since 1d47473a7bb49663c197efa9a6ff8d836a9c1693
### Reproduction steps
`build/mpv video.mp4 --msg-level=vo=v --no-config --dscale=mitchell`

### Expected behavior
Color is displayed correctly.

### Actual behavior
Sometimes, wrong (green) color is displayed.

**Comment by haasn** [comment]
This matches a similar weird issue I once saw with `vo=vulkan`; but I've also been unable to reproduce it consistently..

Maybe this is a bug in the UBO code? (I wonder if we should try explicitly clearing the unused byte ranges in the UBO)

**Comment by haasn** [comment]
How reliably can you reproduce the issue?

**Comment by mfcc64** [comment]
> How reliably can you reproduce the issue?

Inconsistent.
Result of trials: 7 errors on 100 playbacks.

**Comment by mfcc64** [comment]
Without --dscale , --scale, --cscale, I cannot reproduce the error (I try more than 200 times). Probably, because of different shader.

**Comment by haasn** [comment]
Did https://github.com/mpv-player/mpv/commit/0fe4a492c431610dc69b66eb4397707bda178b99 fix the issue?

**Comment by mfcc64** [comment]
It fixed the issue (I try more than 200 times without errors).
Thank's.
