### ISSUE TITLE
Permission denied when opening DVD on Windows

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#4841]
### mpv version and platform

0.26.0
Windows 8.

### Reproduction steps

On a folder with a video_ts folder:
`mpv "...\video_ts"`

### Expected behavior

Opens the video in its entirety.

### Actual behavior

Does not open anything - "permission denied".

### Log

[output.txt](https://github.com/mpv-player/mpv/files/1279645/output.txt)

---

Solutions referenced [here](https://github.com/mpv-player/mpv/issues/4711) don't work for me:

1. Use "mpv *" - Same error. 
2. Autoplaylist - Haven't tried it but I'm guessing this isn't intended to open DVD video_ts folders.
3. .reg script - Doesn't work for me (probably an error regarding my mpv.exe directory), and wouldn't use it either since I run videos from Kodi and need some way to open the folders from there (ie. associating a .lnk to the folder with a .bat script).

---

Normally there's always one .ifo file within video_ts that opens the video entirely, but I've found some cases were none of the files do this, and instead I'm stuck with either individually opening 20 min. segments of the film, or nothing at all (cause I can't open it fully like this).

**Comment by lachs0r** [comment]
Please don’t ignore the issue template.

**Comment by firewater2** [comment]
Sorry but it's a bad day and there's a bunch of stuff I don't know how to do, such as the MPV version, or how to obtain the log file. I'll update this comment with those soon...

**Comment by haasn** [comment]
cc @rossy I believe I've seen this a couple of times. Apparently mpv can't open directories on windows for some reason?
