### ISSUE TITLE
Short audio files don't finish playing

### ISSUE THREAD

**Issue by veridiam** [mpv-player/mpv#4842]
### mpv version and platform
0.26 Linux and Windows

### Reproduction steps
Play any audio file less than 1 second in duration

### Expected behavior
Audio file should play fully before the player exits

### Actual behavior
Player exits before audio is fully finished playing

**Comment by lachs0r** [comment]
Works for me. Don’t omit the log file.

**Comment by veridiam** [comment]
https://pastebin.com/raw/JAR3b52K

audio file is 0.206s long
tested the same file in foobar2000, which plays the file in its entirety

**Comment by Akemi** [comment]
if this issue still persists please open a new issue with all the info we ask for.
