### ISSUE TITLE
mpv outputs an error when using cookies.txt

### ISSUE THREAD

**Issue by winneon** [mpv-player/mpv#4848]
### mpv version and platform

```
$ mpv --version
mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Jul 20 13:13:36 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.3
```

```
$ uname -a
Linux dankisk-arch 4.12.8-2-ARCH #1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 GNU/Linux
```

### Reproduction steps

Generate a `cookies.txt` that has a session cookie with your favourite tool. A session cookie generally has `0` as its expiration date. Afterwards, try to access a private video or a video behind a paywall using the cookie that you just generated.

The command I use is:

```
$ mpv --cookies --cookies-file=cookies.txt --ytdl-raw-options=cookies=cookies.txt "https://www.youtube.com/watch?v=P4y91gLok8o"
```

### Expected behavior

The video is loaded into mpv and starts playing.

### Actual behavior

The session cookie in the `cookies.txt` file you just generated has magically disappeared, and mpv outputs an error:

```
$ mpv --cookies --cookies-file=cookies.txt --ytdl-raw-options=cookies=cookies.txt "https://www.youtube.com/watch?v=P4y91gLok8o"                                 
Playing: https://www.youtube.com/watch?v=P4y91gLok8o
[ytdl_hook] 
[ytdl_hook] stack traceback:
[ytdl_hook] 	[C]: in function 'len'
[ytdl_hook] 	@ytdl_hook.lua:71: in function 'edl_escape'
[ytdl_hook] 	@ytdl_hook.lua:139: in function 'edl_track_joined'
[ytdl_hook] 	@ytdl_hook.lua:171: in function 'add_single_video'
[ytdl_hook] 	@ytdl_hook.lua:454: in function 'fn'
[ytdl_hook] 	mp.defaults:518: in function 'handler'
[ytdl_hook] 	mp.defaults:339: in function 'handler'
[ytdl_hook] 	mp.defaults:458: in function 'call_event_handlers'
[ytdl_hook] 	mp.defaults:495: in function 'dispatch_events'
[ytdl_hook] 	mp.defaults:451: in function <mp.defaults:450>
[ytdl_hook] 	[C]: in ?
[ytdl_hook] 	[C]: in ?
[ytdl_hook] Lua error: @ytdl_hook.lua:71: bad argument #1 to 'len' (string expected, got nil)
[ffmpeg] tls: The TLS connection was non-properly terminated.
Failed to recognize file format.


Exiting... (Errors when loading file)
```

### Log file

Sprunge: http://sprunge.us/XVBP
Pastebin: https://pastebin.com/raw/W6Y0s6qV

### Sample files

If you have no video to test with, upload [this sample video](http://0x0.st/RD0.mp4) to YouTube and set the video to private.

If http://0x0.st/ is not working, [here is a Dropbox mirror](https://www.dropbox.com/s/3grj3c4fbo7k64i/2scary.mp4?dl=1).

**Comment by wiiaboo** [comment]
About the youtube-dl issue: duplicate of https://github.com/mpv-player/mpv/issues/4728. See https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058 for a workaround.

No idea about the cookies-file stuff.

**Comment by winneon** [comment]
This seems to solve the issue of mpv not being able to load a private issue. However, I am concerned still because now ffmpeg is spamming `tls: The TLS connection was non-properly terminated.` in the terminal. The video is playing though and there doesn't seem to be seeking issues, so I'm not sure why the error is being emitted.

**Comment by wiiaboo** [comment]
That's a known issue with FFmpeg doing unproper TLS connections. Search the
issue tracker in mpv for a better explanation, probably.

**Comment by winneon** [comment]
Ah, that makes sense then. Thank you for the help! I really appreciate it!
