### ISSUE TITLE
[question] need help for portable config usage on Windows

### ISSUE THREAD

**Issue by blackarcher21** [mpv-player/mpv#4849]
### mpv version and platform

mpv 0.26.0-237-g5771f7abf4 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Sep  8 18:18:26 UTC 2017
ffmpeg library versions:
   libavutil       55.74.100
   libavcodec      57.105.100
   libavformat     57.81.100
   libswscale      4.7.103
   libavfilter     6.103.100
   libswresample   2.8.100
ffmpeg version: git-2017-09-08-8043d8eb

I have mpv directory D:/Programs/mpv along with config files
Here are my question:
1. How to access mpv's directory? I want all screenshots saved into subdirectory "screenshots"
2. Is mpv support windows variable, like %USERPROFILE% so it can access Documents/Pictures?
3. Is it possible to make watch_later created also in this folder without full address in the config? How to do that?

I have been looking for this but couldn't find them in manual.
Regards. Thanks :)

**Comment by wiiaboo** [comment]
1. ~~/screenshots probably works. If not, it could probably be implemented
2. No. mpv doesn't retrieve all environment variables or expand them, just the ones it uses.
3. Search the manual, there's an option just for that. Something with 'watch-later' in the name.

**Comment by blackarcher21** [comment]
1. yes, it works like that. thank you
2. okay, got it.
3. yes, I know there are option for watch later, but I'm looking for solution like no.1. I tried with watch-later-directory="~~/watch_later", as example, I want it located in D:/Programs/mpv/watch_later but doesn't work. Did I do it wrong for this?

**Comment by wiiaboo** [comment]
Ah, no, you can't set watch_later to a different directory.

**Comment by Hrxn** [comment]
What about [--config-dir](https://mpv.io/manual/master/#options-config-dir)?

**Comment by blackarcher21** [comment]
if I use full path, for example
watch-later-directory="D:/Programs/mpv/watch_later", its correctly located at D:/Programs/mpv/watch_later

using config-dir doesn't go with the purpose I guess.

**Comment by wiiaboo** [comment]
Oh, you can actually change the watch-later directory. Didn't know.
You can either change config-dir and it should be under <config-dir>/watch_later or change watch-later-directory to a completely different directory.

You can also, on Windows at least, create a portable_config directory/file which will make mpv consider the dir the main config dir instead of %APPDATA%/mpv, I think. https://mpv.io/manual/master/#files-on-windows

**Comment by blackarcher21** [comment]
okay, thank you
