### ISSUE TITLE
[Feature Request] Keep window aspect ratio proportional to video AR

### ISSUE THREAD

**Issue by simonbru** [mpv-player/mpv#4850]
When resizing the window, *gnome-mpv* maintains the video aspect ratio by adding vertical or horizontal black bars. *mpv* behaves differently, the window always keeps the same shape to avoid wasting space.

Here are videos of the resizing behavior of [gnome-mpv](https://0x0.st/R7Q.mp4) and [mpv](https://0x0.st/R7S.mp4) to make it more clear.

I like to have a video playing in a corner of the screen, and it is easier to find the perfect window size with mpv thanks to the way it resizes. However I don't know how difficult it is to implement, or if it could cause issues with some window managers.
Maybe this could be implemented as a distinct feature triggered by a button or keyboard shortcut ? Similarly to the alt+1,2,3 shortcuts, but it would compute the window/video size based on the mouse cursor position ?

**Comment by haasn** [comment]
You want mpv to implement a feature that mpv implements? Huh? Was this supposed to be a gnome-mpv feature request?

**Comment by simonbru** [comment]
Wow pretty dumb mistake of my part. :p
I went on the mpv repo to see how the resizing behavior was implemented and mixed up the tabs.

My apologies for the noise!
