### ISSUE TITLE
Querying the vo perf data makes the player crash

### ISSUE THREAD

**Issue by AirPort** [mpv-player/mpv#4853]
### mpv version and platform

macOS 10.12.6
git master

### Reproduction steps

Query the vo perf data using stats.lua or `show-text "${vo-passes}"`

### Expected behavior

vo perf data shows up.

### Actual behavior

The player crashes (11013 bus error). 
I bisected it and the first bad commit seems to be 1da5324.

### Log file
lldb log: https://0x0.st/7K3.txt
mpv log: https://0x0.st/7Kx.txt

**Comment by Argon-** [comment]
Yeah this is known. I could also test this on multiple different machines, however, all of them running OSX (10.11). I really hope this is not a fuckup of OSX again... 
Have some work to do right now but hope I can debug this later this day.

**Comment by Argon-** [comment]
@haasn Found the problem:
https://github.com/mpv-player/mpv/blob/71c25df5e66154e6b8b72ebc0f8ef5ae0c40d7f6/video/out/vo.h#L146
256 is apparently to high, for whatever reason. Maximum my machine can take is 249

**Comment by AirPort** [comment]
Even stranger: timers by themselves seems to work actually, since using verbose output (-v -v) I can see them in the terminal.
It's trying to show them in the OSD with show_text or the script that causes the crash, apparently.

**Comment by Akemi** [comment]
this might be relevant, i can access `vo-passes` with c/swift via `mpv_get_property` without problems on macOS. it only crashes when accessing via `mp.get_property_native -> script_get_property_native`, which also uses `mpv_get_property`. is it possible that this is some lua related restriction?

**Comment by haasn** [comment]
So there's a size limit to how much data you can pass in the VOCTRL return struct, or something? As a crude hack, does dynamically tallocating the array instead of having ot part of the struct fix it at all?

**Comment by haasn** [comment]
Also this seems like a compiler bug, so try upgrading GCC etc.

**Comment by haasn** [comment]
Is it possible that 512 kB is just too big for the stack to begin with? I assume this patch helps?

```diff
diff --git a/player/command.c b/player/command.c
index 87709e119c..1147eab14e 100644
--- a/player/command.c
+++ b/player/command.c
@@ -2913,19 +2913,21 @@ static int mp_property_vo_passes(void *ctx, struct m_property *prop,
         return M_PROPERTY_OK;
     }
 
-    struct voctrl_performance_data data = {0};
-    if (vo_control(mpctx->video_out, VOCTRL_PERFORMANCE_DATA, &data) <= 0)
-        return M_PROPERTY_UNAVAILABLE;
+    int ret = M_PROPERTY_UNAVAILABLE;
+    struct voctrl_performance_data *data = talloc_ptrtype(NULL, data);
+    if (vo_control(mpctx->video_out, VOCTRL_PERFORMANCE_DATA, data) <= 0)
+        goto out;
 
     switch (action) {
     case M_PROPERTY_PRINT: {
         char *res = NULL;
         res = talloc_asprintf_append(res, "fresh:\n");
-        res = asprint_perf(res, &data.fresh);
+        res = asprint_perf(res, &data->fresh);
         res = talloc_asprintf_append(res, "\nredraw:\n");
-        res = asprint_perf(res, &data.redraw);
+        res = asprint_perf(res, &data->redraw);
         *(char **)arg = res;
-        return M_PROPERTY_OK;
+        ret = M_PROPERTY_OK;
+        goto out;
     }
 
     case M_PROPERTY_GET: {
@@ -2933,14 +2935,19 @@ static int mp_property_vo_passes(void *ctx, struct m_property *prop,
         node_init(&node, MPV_FORMAT_NODE_MAP, NULL);
         struct mpv_node *fresh = node_map_add(&node, "fresh", MPV_FORMAT_NODE_ARRAY);
         struct mpv_node *redraw = node_map_add(&node, "redraw", MPV_FORMAT_NODE_ARRAY);
-        get_frame_perf(fresh, &data.fresh);
-        get_frame_perf(redraw, &data.redraw);
+        get_frame_perf(fresh, &data->fresh);
+        get_frame_perf(redraw, &data->redraw);
         *(struct mpv_node *)arg = node;
-        return M_PROPERTY_OK;
+        ret = M_PROPERTY_OK;
+        goto out;
     }
     }
 
-    return M_PROPERTY_NOT_IMPLEMENTED;
+    ret = M_PROPERTY_NOT_IMPLEMENTED;
+
+out:
+    talloc_free(data);
+    return ret;
 }
 
 static int mp_property_vo(void *ctx, struct m_property *p, int action, void *arg)
diff --git a/video/out/opengl/video.h b/video/out/opengl/video.h
index e20af90643..d163bc8405 100644
--- a/video/out/opengl/video.h
+++ b/video/out/opengl/video.h
@@ -27,6 +27,7 @@
 #include "shader_cache.h"
 #include "video/csputils.h"
 #include "video/out/filter_kernels.h"
+#include "video/out/vo.h"
 
 // Assume we have this many texture units for sourcing additional passes.
 // The actual texture unit assignment is dynamic.
@@ -164,7 +165,6 @@ void gl_video_resize(struct gl_video *p,
                      struct mp_rect *src, struct mp_rect *dst,
                      struct mp_osd_res *osd);
 void gl_video_set_fb_depth(struct gl_video *p, int fb_depth);
-struct voctrl_performance_data;
 void gl_video_perfdata(struct gl_video *p, struct voctrl_performance_data *out);
 void gl_video_set_clear_color(struct gl_video *p, struct m_color color);
 void gl_video_set_osd_pts(struct gl_video *p, double pts);
```

**Comment by haasn** [comment]
Also, 512 kB is way too large for the stack anyway, so I've just changed this (in master) and also reduced the size to 256 kB.

Goes to show what effects increasing the size of a struct can have - code somewhere else might still be assuming it's small.

I assume this issue can be closed now.

**Comment by Argon-** [comment]
Yes, your last patch does indeed fix the issue and latest master (with your commit) works as well. Thanks!

Tried to use different compilers and increase stacksize but I couldn't make waf cooperate. Simply changing the compiler with `CC` makes it no longer detecting cocoa/opengl.
I like makefiles.

**Comment by AirPort** [comment]
Yep, everything works fine now. Thank you very much!
