### ISSUE TITLE
Will mpv ever scrap opengl for metal?

### ISSUE THREAD

**Issue by negativeions** [mpv-player/mpv#4856]
Isn't metal supposed to be this new great thing? Is there an advantage to using metal over OGL? Metal 2 is coming out soon...

**Comment by Akemi** [comment]
nope. yes. yes.

**Comment by Argon-** [comment]
Metal is only "great" because Apple doesn't implement recent versions of OpenGL or cross-platform standards like Vulcan at all. Their supported OpenGL version is nearly a decade old afaik.

**Comment by haasn** [comment]
I can't think of any advantages metal would have over vulkan; except that Apple gets to dictate and monopolize it. (And as I'm sure all developers are aware, that's the best thing that could possibly happen to a standard)

**Comment by Hrxn** [comment]
> Isn't metal supposed to be this new great thing?

Yes.
> Is there an advantage to using metal over OGL?

Yes.
> Metal 2 is coming out soon...

Yes.

How do you say? Pull requests welcome. ®™

A little side note, don't take it for granted because I just heard it from some Random Internet Comment: Metal is supposedly pretty easy to pick up and get something going, so that may be something at least..
On the other hand, maybe Apple will decide to hop onto the Vulkan bandwagon soon-ish.

**Comment by Argon-** [comment]
>  On the other hand, maybe Apple will decide to hop onto the Vulkan bandwagon soon-ish.

No. Seriously, this will not happen unless they officially kill Metal and this won't happen either. On OSX, we are stuck without Vulkan and with shitty/old OpenGL till the end of days.

**Comment by AirPort** [comment]
Pretty much, unless some kind of compatibility layer/API shows up, and after all I think it's going to happen in some form sooner or later (AFAIK there already is a commercial implementation of Vulkan for macOS/iOS built upon Metal, and I think I also remember Khronos talking about a multi-platform portability API for Vulkan-Metal-DirectX).

**Comment by haasn** [comment]
> Metal is supposedly pretty easy to pick up and get something going

If you can find a working GLSL->MSL compiler

**Comment by Hrxn** [comment]
Don't ask me, I was just reiterating.
But is MSL really that much of a difference compared to other shader programming languages?
Not that I can't really judge here, but it doesn't seem to make any sense, from the onset, to stray from the known path, so to say..

**Comment by haasn** [comment]
> Not that I can't really judge here, but it doesn't seem to make any sense, from the onset, to stray from the known path, so to say..

Nothing apple does makes sense.

**Comment by Hrxn** [comment]
They made a lot of sense in the past, not so sure about the Tim Cook era though, guess I agree now..

**Comment by negativeions** [comment]
well, it makes porting from iOS to macOS easier and deving for apple platforms more uniform I guess.

**Comment by CounterPillow** [comment]
>well, it makes porting from iOS to macOS easier and deving for apple platforms more uniform I guess

Except not really, because newer versions of OpenGL ES are so similar to desktop OpenGL that all you need to port things is a handful of ifdefs.

Metal is just a political move to try and control the graphics API on their system all by themselves.

**Comment by negativeions** [comment]
wtf was I talking about? You're right... however, it's not surprising since typically Apple is more about getting the most out of crappier hardware so they want something specific for themselves.

**Comment by haasn** [comment]
> Except not really, because newer versions of OpenGL ES are so similar to desktop OpenGL

Especially when you don't actually support any desktop OpenGL features that go beyond the scope of GLES.

**Comment by Argon-** [comment]
@haasn 
> If you can find a working GLSL->MSL compiler

Combine glslang with [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross) which can "Convert SPIR-V to readable, usable and efficient Metal Shading Language" x)

**Comment by wm4** [comment]
I don't mind improving iOS/OSX support, but Apple really doesn't make it easy. I have no idea why they adhered to the OpenGL standard so long, but now do something completely different. MSL in particular seems like quite a pain, because you pretty much need a modified C++ compiler for it. Only morons could come up with that one, but I guess they think this is for free because they can just import a LLVM clusterfuck.

**Comment by negativeions** [comment]
A modified C++ compiler? You mean C++14?

**Comment by wm4** [comment]
The Metal shader language is some modern version of C++, plus extensions and restrictions to make it possible to compile it to shaders at all.
