### ISSUE TITLE
video-unscaled option

### ISSUE THREAD

**Issue by makanbaks0** [mpv-player/mpv#4859]
can I make script if video height below 768p mpv uses `--video-unscaled=yes`, or maybe add this to input.conf (if i press ~ `video unscaled=yes`)?
thx

**Comment by CounterPillow** [comment]
you can with [auto-profiles](https://github.com/wm4/mpv-scripts/blob/master/auto-profiles.lua)

**Comment by makanbaks0** [comment]
@CounterPillow thank you
