### ISSUE TITLE
Video broken with some settings combinations

### ISSUE THREAD

**Issue by adisib** [mpv-player/mpv#4860]
### mpv version and platform

v0.27.0, Windows x64 build by lachs0r. Running on Windows 10 x64, AMD GPU.
Edit: Should note that this isn't a problem on the previous version of mpv, only this new release, in case it wasn't clear.

### Reproduction steps

Using AMD hardware, play any video with a blank config with --opengl-backend=win added. This can also be reproduced with other setting combinations, such as --opengl-backend=dxinterop as the backend, though enabling PBOs fixes it, and adding --cscale=ewa_robidoux ontop of the PBOs causes it to break again.

### Actual behavior

Video shows a solid color instead of any video (one video was white, one was pink). Audio seems to play fine. Console spams error messages.

### Log file

Params used:
`--no-config --opengl-backend=win --opengl-debug --log-file=log.txt --frames=1`

Log file:
https://pastebin.com/QPLcYun8

Console errors:
`[vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
[vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
[vo/opengl] after rendering: OpenGL error INVALID_OPERATION.
`

Please ask if you require any additional information.

**Comment by aufkrawall** [comment]
Can't confirm with Nvidia. Maybe try some older drivers?

**Comment by haasn** [comment]
You could also try either bisecting or trying to debug the GL callstream to figure out which exact command triggers it.

**Comment by evdw87** [comment]
I have similar problems with dxinterop. I also have an AMD GPU. PBO is the main issue. Scaling causes extended issues. I did some tests...

My screen resolution is: 1920x1080

video @ 1920x1080
-----

fails (solid white output):
--opengl-backend=dxinterop

works:
--opengl-backend=dxinterop
--opengl-pbo=yes

fails (solid blue output):
--opengl-backend=dxinterop
--opengl-pbo=yes
--cscale=ewa_robidoux

fails (solid white output):
--opengl-backend=dxinterop
--opengl-pbo=yes
--scale=ewa_robidoux

fails (pink video output):
--opengl-backend=dxinterop
--opengl-pbo=yes
--cscale=triangle

fails (solid white output):
--opengl-backend=dxinterop
--opengl-pbo=yes
--scale=triangle

works:
--opengl-backend=dxinterop
--opengl-pbo=yes
--cscale=nearest

works:
--opengl-backend=dxinterop
--opengl-pbo=yes
--scale=nearest


video @ 1280x720
-----

fails (solid white output):
--opengl-backend=dxinterop

works:
--opengl-backend=dxinterop
--opengl-pbo=yes

fails (solid blue output):
--opengl-backend=dxinterop
--opengl-pbo=yes
--cscale=ewa_robidoux

works:
--opengl-backend=dxinterop
--opengl-pbo=yes
--scale=ewa_robidoux

works:
--opengl-backend=dxinterop
--opengl-pbo=yes
--cscale=triangle

works:
--opengl-backend=dxinterop
--opengl-pbo=yes
--scale=triangle

works:
--opengl-backend=dxinterop
--opengl-pbo=yes
--cscale=nearest

works:
--opengl-backend=dxinterop
--opengl-pbo=yes
--scale=nearest

**Comment by adisib** [comment]
I can confirm that for me it also breaks with dxinterop as the backend, but works when PBOs are added as an addition, while failing again if cscale=ewa_robidoux is added on top. I'll update the issue description to reflect that it is an issue with some settings combinations rather than specifically with win as the backend.

**Comment by wm4** [comment]
dxinterop is basically obsolete. We now have a native d3d11 backend. Closing, also because the last reply was an eternity ago.
