### ISSUE TITLE
Streaming RTSP with MPV over long periods of time [info needed]

### ISSUE THREAD

**Issue by Silverbeard00** [mpv-player/mpv#4862]
Apparently, if I stream 5 IP cameras over RTSP with MPV after about 6 hours the entire computer freezes (kernel panic).   Are there any options I can use with MPV to prevent this from happening?  It's not taxing my CPU that hard (~30% total cpu usage) and the cameras are directly connected with a gigabit switch.

I'm at a loss to understand why this is happening.

**Comment by lachs0r** [comment]
No, there are no options in mpv to prevent
1) driver bugs
2) faulty RAM
3) faulty PSU
from potentially crashing your system.
