### ISSUE TITLE
[proposal] different HDR conversion settings by default

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4863]
Current default settings look very overbrightened and flat when playing HDR video, at least with videos that don't have broken HDR metadata like nits=1 (an example for such a flawed video would be e.g. the Sony 4k HDR Camp demo).

For video with proper HDR meta data (like e.g. LG OLED Chess), I find the following values much better suited:
tone-mapping=reinhard
tone-mapping-param=0.2
tone-mapping-desaturate=3.5

I can provide screenshots, download links etc., but it's really obvious if you try a bit around.
tone-mapping-desaturate is a matter of taste to some extent. However, the value of 2.0 will bleach green leaves a lot in forest scenes which aren't oversaturated.

hdr-compute-peak unfortunately can lead to banding, this can be observed with the settings above in the aforementioned LG OLED Chess demo.

**Comment by haasn** [comment]
I think your settings produce images that are way darker than they should be.

If anything, what you could try doing is finding more examples of clips that have been independently graded (by mastering technicians) for both HDR and SDR. And especially try and avoid “demo clips”, but try finding actual content. (e.g. a movie that was mastered for both HDR and SDR).

A few 1-frame clips of such a movie would certainly help more when it comes to figuring out what kind of tone mapping curve is the best default.

**Comment by aufkrawall** [comment]
I'll look out for real content, but I think e.g. popular YouTube material like "The Redwoods" with naturalistic colors might already be a good testcase:
ftp://helpedia.com/pub/multimedia/testvideos/The%20Redwoods%204k%2024fps%20(VP9%20Profile%202%20HDR).mkv

I think it's reasonable to assume that viewers usually want a contrast rich result for HDR content. That imho justifies some minor clipping for dark areas over dull/overbrightened images.

**Comment by haasn** [comment]
The “The Redwoods” test clip looks fine to me with default settings. “hable” seems too dark.

**Comment by fhlfibh** [comment]
IMO, a good wike page about HDR and its options would be more useful than messing with default figures.

**Comment by aufkrawall** [comment]
And what would that wiki entry consist of?
There is already stuff on the manpage and there are only few options.

**Comment by aufkrawall** [comment]
The banding with hdr-compute-peak was also related to this issue:
https://github.com/mpv-player/mpv/issues/4976

I think what would lead to better results would also be a different hue preservation. madVR's "HQ hue preservation" e.g. helps to prevent orange from turning into reddish etc.
mpv's desaturate could imho also be harsher towards very intense red and blue and maybe less towards green.

**Comment by aufkrawall** [comment]
Btw: hdr-compute-peak doesn't work with Vulkan and D3D11 because it can't find compute shader.

**Comment by haasn** [comment]
Works for me (vulkan)

**Comment by aufkrawall** [comment]
It does work with
gpu-api=vulkan
hdr-compute-peak

But as soon as I add even just cscale=bicubic, mpv renders only a solid blue window and there are lots of errors:
https://pastebin.com/bbYFhbxN

**Comment by haasn** [comment]
Turns out that was a bug; I've fixed it in libplacebo. Should be trivial to backport if you care this much about hdr-compute-peak (I had assumed nobody would)

**Comment by aufkrawall** [comment]
It helps to restore more detail in highlights, so yeah. Would be good if it was working. :)

**Comment by haasn** [comment]
It doesn't really make a difference with the default `tone-mapping=mobius`, does it?

**Comment by aufkrawall** [comment]
It even seems to achieve the opposite of what I'd call desired, highlights look even brighter. :(
Well, I didn't test it extensively in mpv, but in madVR there is the same feature and I found it useful there.

**Comment by haasn** [comment]
> It even seems to achieve the opposite of what I'd call desired, highlights look even brighter. :(

Well that's sort of the point; it can accurately detect and use the full dynamic range.

**Comment by aufkrawall** [comment]
New desaturation is nice, e.g. blue skies look less cartoony. Of course the old default value of 2.0 is way off. I personally like something around 0.14.

**Comment by aufkrawall** [comment]
Is it to be expected that it's pretty much impossible to decrease brightness with mobius? Even with tone-mapping-param=0.01 it's still really (too) bright.
With reinhard, the param setting has a much stronger effect.
--hdr-compute-peak can also suddenly dim brightness, that happens after the first seconds of the "Chasing the Light" clip of Samsung when using reinhard.
http://4kmedia.org/samsung-chasing-light-4k-demo/

**Comment by haasn** [comment]
Yeah that's pretty much expected. Even with the parameter set to 0.00, that just means it'll be equal to stock reinhard.

**Comment by aufkrawall** [comment]
Thanks for your recent HDR improvements.

I noticed some nasty behavior in general of desaturate (not related to current changes): When decreasing its value, the image shows some smeared or blocky artifacts.

1.0:
https://abload.de/img/1yzsyl.png

0.1:
https://abload.de/img/0.126s8u.png

tone-mapping=reinhard
tone-mapping-param=0.25
tone-mapping-desaturate=0.1/1.0
hdr-compute-peak=yes

madVR also got a new option recently to change the settings for diffuse white, which can help to fight the oversaturated colors.
Like I described back in fall, this is especially a problem with some blue and red tones:
https://abload.de/img/blue83shy.png
https://abload.de/img/redzjsdt.png
https://abload.de/img/red2rps3n.png

When increasing desaturate to fight this, other bright parts with not so saturated colors can look quite pale compared to the rest of the image:
https://abload.de/img/pale1qcs2f.png
https://abload.de/img/pale2jkseb.png
https://abload.de/img/pale3p0sig.png
https://abload.de/img/pale4wlsdf.png

(tone-mapping-desaturate=0.5)

**Comment by aufkrawall** [comment]
Is hdr-compute-peak=yes expected to have such a huge impact on color conversion? It looks quite fantastic in videos where it doesn't have problems, colors mostly neither look to saturated or too pale.
But in some videos it noticeably changes brightness a lot, or some scenes get way too dark, even without visible logo (e.g. LG chess sample).
There also seems to be some kind of shader compile issue. When shader cache yet isn't populated yet, there are sometimes strong blocky artifacts (on both Nvidia and AMD, OGL and D3D11).

**Comment by Akemi** [comment]
the proposal wasn't accepted till now so i doubt we will get anything out of it now.
