### ISSUE TITLE
Crashes playing VP9 videos with hwdec=dxva2-copy

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#4870]
**UPD**: most likely a duplicate of #4865.

### mpv version and platform
0.27.0, Windows 7 SP1
### Reproduction steps
(You'll probably need a video card that supports hardware VP9 decoding)
mpv --no-config --v --log-file=log.txt --hwdec=dxva2-copy C:\g0R3X.webm
### Expected behavior
Playback.
### Actual behavior
"mpv has stopped working" crash message.
### Log file
https://pastebin.com/81B5KwNE
### Sample files
https://a.safe.moe/g0R3X.webm

**Comment by wm4** [comment]
I assume this is fixed with a recent ffmpeg.

**Comment by UserNaem** [comment]
(Do I look like a developer? I don't even know git, let alone be able to not screw up trying to compile anything.)
I'll have to wait for a build.
