### ISSUE TITLE
sub-font is changing the font size of the ASS-subtitle

### ISSUE THREAD

**Issue by Sbks** [mpv-player/mpv#4872]
sub-font disabled
[image](https://images.imgbox.com/9e/69/n2Pht2p9_o.png)

--sub-font='Any font'
[image](https://images.imgbox.com/5c/c2/Ngss2KEi_o.png)

sample file
[dl](https://mega.nz/#!yh9H2AzD!UI2LK8tj4wEzOZJ8WpNmsZs5KFL4gCICglNLwurZfxk)

> [The --sub-font option (and many other style related --sub- options) are ignored when ASS-subtitles are rendered, unless the --no-sub-ass option is specified.](https://mpv.io/manual/master/#options-sub-font)

**Comment by Akemi** [comment]
if thiss issue still persists, please open a new issue.
