### ISSUE TITLE
opengl-backend=dxinterop broken with shader

### ISSUE THREAD

**Issue by eXmendiC** [mpv-player/mpv#4874]
mpv version: v0.27.0
"opengl-backend=dxinterop" doesn't work together with shaders (like nnedi3).
It worked fine with v0.26.0 (see the comparison above).

I tried using "opengl-backend=angle" and that works. So I think the issue is with "dxinterop" and not the shader itself.
With v0.26.0 I had the issue that "win" and "angle" showed me a green screen instead of the video, but that seems fixed with mpv v0.27.0.
I just want to report that issue here, there is no reason for me to still use dxinterop when angle works.

Log file:
https://pastebin.com/yqtXz9xE

Comparison:
https://diff.pics/RlVgdCTYxINX/1

**Comment by haasn** [comment]
What does “doesn't work” mean?

**Comment by aufkrawall** [comment]
Judging by the result, he probably means that NNEDI3 isn't used and mpv falls back to some internal scaler.

**Comment by haasn** [comment]
In that case, can you upload another log with `--msg-level=vo=debug`?

**Comment by eXmendiC** [comment]
Here: https://pastebin.com/LrLNKx2V

**Comment by haasn** [comment]
That doesn't help me; --msg-level only applies to stdout, not to --log-file

@wm4 pls fix

**Comment by Dudemanguy** [comment]
Ancient one. Please open a new issue if this still exists.
