### ISSUE TITLE
Taking screenshot failed

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#4875]
### mpv version and platform
mpv: 0.27.0 64bit from https://mpv.srsfckn.biz/
platform: windows 7 SP1 64bit
### Reproduction steps
1. I use mpv --no-config to play a mp4 video to use only default hotkeys.
2. I press Ctrl+s try to take a screenshot.
(default should be **Ctrl+s async screenshot window**)
3.I get a error message Taking screenshot failed(picture below)
but only Ctrl+s can't work , **s　S　Alt+s** works.

http://i.imgur.com/Pucv0En.jpg

How should i do?I need to capture screenshot with osd or other message sometimes.

**Comment by kesdoputr** [comment]
When i change vo from opengl(default) to direct3d 
It seems all ok.

**Comment by Hrxn** [comment]
Driver issue, most likely..
