### ISSUE TITLE
ytdl_hook: add chapters by parsing video's description, no longer working

### ISSUE THREAD

**Issue by CrisBRM** [mpv-player/mpv#4876]
https://github.com/mpv-player/mpv/pull/3593
Test: https://www.youtube.com/watch?v=YGmACxoYDjE
git master, ffmpeg git master, etc.

**Comment by wiiaboo** [comment]
Going to need logs with `--msg-level=ytdl_hook=debug`.
And maybe pastebin of output of `youtube-dl -J <url>`. Last time I tried it was broken with some videos.

**Comment by Jj0YzL5nvJ** [comment]
Works for me: http://sprunge.us/WPIa
```
youtube-dl --version
2017.09.11
```

**Comment by CrisBRM** [comment]
@j605 Yup. Updating youtube-dl fixed it.
