### ISSUE TITLE
Deinterlacing not working on RPI raspbian stretch

### ISSUE THREAD

**Issue by denz2** [mpv-player/mpv#4879]
[mpv.txt](https://github.com/mpv-player/mpv/files/1308796/mpv.txt)
### mpv version and platform
mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Sep  2 10:58:40 AWST 2017
ffmpeg library versions:
   libavutil       55.74.100
   libavcodec      57.104.101
   libavformat     57.80.100
   libswscale      4.7.103
   libavfilter     6.101.100
   libswresample   2.8.100
ffmpeg version: N-87155-g0e995eac20

I tried 0.27 but doesnt work on the pi sound but no video.

When I play any video it is not deinterlacing the video so it is not watchable. I have a sample file and the log file 

https://1drv.ms/v/s!Ap2CKhsbDnkA4EBEJl19A12wMP4q

**Comment by Gusar321** [comment]
Deinterlacing on the RPi is not implemented in mpv yet. So this issue could serve as a feature request. MMAL supports a few different deinterlacing methods, would be nice if mpv added support from them.

I too noticed that there's no video with version 0.27 when using --vo=opengl, but --vo=rpi should work.

**Comment by denz2** [comment]
Thank you for that with --vo=rpi I have video.
