### ISSUE TITLE
[enhancement] Make pseudo gui show network loading progress inside seekbar on youtube-dl videos

### ISSUE THREAD

**Issue by lynxlynx** [mpv-player/mpv#4881]
mpv is great tool and I love it's tight integration with famous youtube-dl script - the first open source player which does the right thing by offering video downloading job to third party program which deals with often changing api of third party services.
As title says, it would be great to make it's pseudo gui show a network loading progress of youtube-dl handled video just like most browser video player widgets do.
I looked into osc.lua but I can't find where to start. I have rather bad lua experience.

**Comment by avih** [comment]
mpv only uses youtube-dl to grab the _clip_ URL (e.g. from a youtube _page_ URL), but doesn't use youtube-dl to do actual video downloads.

Nevertheless, some "Analyzing URL ..." indication while youtube-dl tries to fetch and parse the URL could be useful indeed.

@wiiaboo ?

**Comment by lynxlynx** [comment]
Even better then, since mpv knows how much is fetched, can it "draw" the progress then?

**Comment by avih** [comment]
Progress of what? Assuming your bandwidth to the video URL is reasonable, mpv launches youtube-dl to "translate" the URL to a stream URL (this typically takes 1-2 seconds, which mpv can't track for progress), and then does very minimal prefetch before starting the playback (another 1-2 seconds typically).

**Comment by lynxlynx** [comment]
Ok I did not digged into how mpv does fetching the stream.
When I watch a YouTube video, I see the "Cache:" line in right side of pseudo gui, which updates number of fetched stream megabytes so far and stops when it's done. And since mpv knows total length of fetched video, I thought it will be good to display this loading progress inside seekbar as a bar of another shadow color instead of number of megabytes.

**Comment by haasn** [comment]
torque's mpv-progressbar does this. Keep in mind it can only ever be a crude estimation, based on the current bitrate. You can't know how “long” a section of already-downloaded video is until you decode it, which mpv doesn't do until it needs to play it.

**Comment by lynxlynx** [comment]
Thanks @haasn for suggestion! I'd looked into it now and it seems to be working. I will use it.
