### ISSUE TITLE
mpv crashes with 4k 60fps VP9 and d3d11va

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#4882]
### mpv version and platform
0.27 Windows 10

### Reproduction steps
Open a 4k 60fps VP9 video with d3d11va.

### Expected behavior
It should play.

### Actual behavior
mpv crashes.
Happens with angle + d3d11va and d3d11va-copy. Doesn't hapen without hwdec.

### Log file
http://sprunge.us/VhMR

**Comment by haasn** [comment]
Can you produce a backtrace? Does it happen with `ffplay`? (not sure if you can get ffplay to use hwdec)

**Comment by aufkrawall** [comment]
ffplay --help doesn't seem to offer hardware decoding options, or I'm missing it.
How to produce a backtrace?

**Comment by wm4** [comment]
Does it happen with any other format/framerate/resolution combination? Does it work with dxva2? d3d11va-copy?

**Comment by aufkrawall** [comment]
It seems to happen with VP9 videos in general, independent of video properties (well, I only got YT material), opengl-backend and selected hardware decoder.
Thus I suppose this a duplicate of this:
https://github.com/mpv-player/mpv/issues/4870

**Comment by wm4** [comment]
There was a ffmpeg fix that might have to do with this.

**Comment by aufkrawall** [comment]
Yes, fixed with recent git build.
