### ISSUE TITLE
[Documentation] Main Readme - please consider adding an example via ./waf how to use prefix

### ISSUE THREAD

**Issue by shevegen** [mpv-player/mpv#4893]
Hello mpv team,

A few days ago I managed to compile mpv from source (latest .zip checkout from the github site here, via the download button).

All went fine; I am using mpv. (I use both mplayer and mpv by the way; also I think it's nice because mpv had a few improvements already which I think mplayer could use in the user interface, but I digress).

The readme currently shows how to compile things via waf:

    ./bootstrap.py
    ./waf configure
    ./waf
    ./waf install

I know the GNU autoconfigure tools very well; and cmake too. In GNU configure we can use --prefix=/location; in cmake we can use, for example, -DCMAKE_INSTALL_PREFIX=/usr.

I have had barely any exposure with waf, and so I was wondering whether mpv could have an example? I think without option, mpv was installed into /usr/local/ prefix. I'd like to easily use /usr prefix or some other directory too, if that would be possible. So my question is:

- Do you folks think it would be useful if an example could be added to the main readme, showing how to use another prefix via waf?

I could probably google but I think that perhaps a few others may also want to know, so I thought it may be good to file an issue request. Please do feel free to close this issue at any moment in time, anyway!

PS: I also recently read the entry in the documentation explaining the differences between mpv and mplayers. Thanks to whoever added it! I have been using mplayer since ... 13 years or so and I am still happy, so I thought I would not like mpv because it may be completely different. But after trying mpv for some days so far, I think that the differences are not that huge. Both video players are nice IMO. Mplayer could be a little bit more active though, it seems as if mpv has more active development going on (but I can't say for sure).

**Comment by lachs0r** [comment]
Not sure how you’ve been able to use MPlayer for 13 years, made yourself familiar with other build systems and know about the concept of install prefixes… yet you couldn’t figure out how to pass `--prefix` or `--help` to waf.
