### ISSUE TITLE
Cannot open Youtube using libmpv - C#

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#4898]
Hi, I really love MPV. I can not believe how functional (and fast) this player is. Only have one problem, I can not play videos (or streamings) from youtube. I saw that you have to activate the option "mpv_set_option_string(handle, "ytdl", "yes")" (from this ) but it does not seem to work. This is my code:

 _mpvSetOption(_mpvHandle, GetUtf8Bytes("wid"), 4, Panel1.Handle.ToInt64())
_mpvSetOptionString(_mpvHandle, GetUtf8Bytes("keep-open"), GetUtf8Bytes("always"))
_mpvSetOptionString(_mpvHandle, GetUtf8Bytes("video-aspect"), GetUtf8Bytes("4:3"))

DoMPVCommand("loadfile", "https://www.youtube.com/watch?v=IjGdi7z_B4U")

  Public Sub DoMPVCommand(ParamArray args As String())
       Dim byteArrayPointers As IntPtr()
       Dim mainPtr = AllocateUtf8IntPtrArrayWithSentinel(args, byteArrayPointers)
       _mpvCommand(_mpvHandle, mainPtr)
       For Each ptr In byteArrayPointers
           Marshal.FreeHGlobal(ptr)
       Next
       Marshal.FreeHGlobal(mainPtr)
   End Sub

All other code is same to the libmpv example in C#
I can play everything correctly, except youtube videos
Thanks in advance.

**Comment by wm4** [comment]
Make sure you set the `ytdl` option correctly. Also add `log-file=out.txt` and upload `out.txt` after trying it.

**Comment by EzeKees** [comment]
Thanks, here I leave the log when I open a Youtube url:

DoMPVCommand("loadfile", "https://www.youtube.com/watch?v=IjGdi7z_B4U")

[   0.013][v][cplayer] mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[   0.013][v][cplayer]  built on Wed Sep 13 04:17:50 CEST 2017
[   0.013][v][cplayer] ffmpeg library versions:
[   0.013][v][cplayer]    libavutil       55.74.100
[   0.013][v][cplayer]    libavcodec      57.105.100
[   0.013][v][cplayer]    libavformat     57.82.100
[   0.013][v][cplayer]    libswscale      4.7.103
[   0.013][v][cplayer]    libavfilter     6.105.100
[   0.013][v][cplayer]    libswresample   2.8.100
[   0.013][v][cplayer] ffmpeg version: N-87286-g6ce4a635ed
[   0.013][v][cplayer] 
[   0.013][v][cplayer] Configuration: /home/lachs0r/mingw-w64-cmake/buildroot/build32/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-encoding --enable-egl-angle-lib --enable-lua --enable-javascript --enable-libarchive --enable-libass --enable-libbluray --enable-dvdread --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --prefix=/home/lachs0r/mingw-w64-cmake/buildroot/build32/prefix/mingw
[   0.013][v][cplayer] List of enabled features: asm atomics avutil-content-light-level avutil-icc-profile avutil-imgcpy-uc avutil-spherical build-date cplayer cuda-hwaccel d3d-hwaccel d3d-hwaccel-new d3d9-hwaccel debug-build direct3d dos-paths dvdnav dvdread dvdread-common egl-angle egl-angle-lib egl-angle-win32 egl-helpers encoding gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gnuc iconv is_ffmpeg javascript jpeg lcms2 libarchive libass libass-osd libav libavcodec libavdevice libbluray libm libmpv-shared lua luajit mingw noexecstack optimize plain-gl posix-or-mingw rubberband static-build stdatomic uchardet wasapi win32-desktop win32-internal-pthreads win32-pipes zlib
[   0.013][v][cplayer] Setting option 'log-file' = "C:\u005cTVi Plus\u005cSistema\u005cBinarios\u005cTViPlus95.VPM.log" (flags = 64) -> 0
[   0.013][v][cplayer] Setting option 'keep-open' = "always" (flags = 64) -> 0
[   0.014][v][cplayer] Setting option 'video-aspect' = "No" (flags = 64) -> -3
[   0.014][v][ytdl_hook] Loading lua script @ytdl_hook.lua...
[   0.015][v][ytdl_hook] loading mp.defaults
[   0.015][v][ytdl_hook] loading @ytdl_hook.lua
[   0.015][v][ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[   0.015][v][cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[   0.016][v][cplayer] Run command: hook-add, flags=0, args=[on_preloaded, 2, 10]
[   0.016][v][cplayer] Done loading @ytdl_hook.lua.
[   0.016][v][cplayer] Setting option 'ytdl' = "yes" (flags = 64) -> 0
[   0.017][v][cplayer] Setting option 'panscan' = "1.0" (flags = 64) -> 0
[   0.018][v][cplayer] Setting option 'deinterlace' = "yes" (flags = 64) -> 0
[   0.019][v][cplayer] Setting option 'brightness' = "0" (flags = 64) -> 0
[   0.020][v][cplayer] Setting option 'contrast' = "0" (flags = 64) -> 0
[   0.022][v][cplayer] Setting option 'saturation' = "0" (flags = 64) -> 0
[   0.023][v][cplayer] Setting option 'gamma' = "0" (flags = 64) -> 0
[   0.025][v][cplayer] Setting option 'hue' = "0" (flags = 64) -> 0
[   0.026][v][cplayer] Run command: loadfile, flags=0, args=[https://www.youtube.com/watch?v=ks_Rch6MrDY, replace, ]
[   0.026][i][cplayer] Playing: https://www.youtube.com/watch?v=ks_Rch6MrDY
[   0.026][v][cplayer] Running hook: ytdl_hook/on_load
[   0.026][v][cplayer] Set property: pause="no" -> 1
[   0.026][w][ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[   0.026][v][cplayer] Run command: hook-ack, flags=0, args=[on_load]
[   0.027][v][ffmpeg] Opening https://www.youtube.com/watch?v=ks_Rch6MrDY
[   0.205][v][ffmpeg] Mime-type: 'text/html; charset=utf-8'
[   0.205][v][ffmpeg] Stream opened successfully.
[   0.206][v][cache] Cache size set to 150000 KiB (75000 KiB backbuffer)
[   0.206][v][demux] Trying demuxers for level=normal.
[   0.880][v][cache] EOF reached.
[   0.920][v][lavf] No format found, try lowering probescore or forcing the format.
[   0.921][v][demux] Trying demuxers for level=unsafe.
[   0.948][v][lavf] No format found, try lowering probescore or forcing the format.
[   0.948][v][cache] Terminating cache...
[   0.948][v][cache] Cache exiting...
[   0.949][v][cplayer] Opening failed or was aborted: https://www.youtube.com/watch?v=ks_Rch6MrDY
[   0.949][v][cplayer] finished playback, unrecognized file format (reason 4)
[   0.949][e][cplayer] Failed to recognize file format.
[   0.949][i][cplayer] 

Do you know that you can fail? Thank you very much

**Comment by EzeKees** [comment]
I have solved it, I needed to put the YoutubeDl executable along with the mpv dll, I thought I had done it already, but no. Thank you very much too
