### ISSUE TITLE
Feature request: bundle mpv with the HTML manual

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#4899]
The bundled PDF manual requires having a PDF reader, and it is a pain to navigate. The HTML manual has better performance, search and navigation, and can be read on any device with any web browser, but it's only available with an active Internet connection because it's not bundled with the builds. It can be saved manually, but probably no one is going to think about it before they need it.

Also, there is no apparent way to get a HTML manual for non-latest versions of mpv, which can be bad if a user is stuck with an old version for any reason, such as using Windows XP.

**Comment by Hrxn** [comment]
You can open the PDF manual with every somewhat modern browser, just sayin'.

**Comment by mc4man** [comment]
There is no bundled pdf so if wanting an html version configure it in or ask whoever doing the build you're using to consider adding.

**Comment by Hrxn** [comment]
lachs0r's build for Windows comes with a PDF manual, as far as I know..

**Comment by negativeions** [comment]
you can open pdf's in any browser. Dunno about windows but the preview app in macOS can open pdf's natively.

**Comment by Argon-** [comment]
Well great, then we can at least read about all the features our outdated and buggy graphics drivers don't support.

**Comment by UserNaem** [comment]
I'm not here to make an OS debate, the PDF manual is worse in every imaginable way and the HTML manual is only available online and only for latest versions.

**Comment by haasn** [comment]
mpv doesn't distribute official packages, so this is outside of our control. If you build mpv from source you can choose whether or not to build and install the HTML/PDF manuals.

**Comment by Hrxn** [comment]
> Dunno about windows [..]

Windows ships with the Edge browser, displays PDFs just fine. And is actually associated with .pdf files out of the box.

**Comment by negativeions** [comment]
@UserNaem how is this anything but a trivial issue if you can easily open it without any issues? You're just crying about spilled milk on principle. It works. So who cares.

**Comment by UserNaem** [comment]
PDF lags and the document is a pain to navigate.

**Comment by Argon-** [comment]
As haasn already said, you are talking to the wrong people. mpv supports building a HTML manual (https://github.com/mpv-player/mpv/blob/master/wscript#L85) when building. When your distribution of mpv does not contain this HTML manual, then it's the fault of whoever compiled it for you. When you compiled it yourself, then it's your fault for not enabling the HTML manual.

Nobody is "bundling" anything here. This project only releases source code. Please complain to the person compiling mpv for you.

**Comment by qyot27** [comment]
>PDF lags and the document is a pain to navigate.

So use a PDF reader that displays the navigation index and doesn't guzzle resources: it's not hard to find them. \*[cough](https://www.sumatrapdfreader.org/free-pdf-reader.html)\*

**Comment by Argon-** [comment]
(The default reader on OSX can already do that, you just have to use it)

**Comment by qyot27** [comment]
[The OP uses Windows 7, though.](https://github.com/mpv-player/mpv/issues/4896#issuecomment-330684120)

**Comment by Argon-** [comment]
Oh, mistook him with a another guy posting here

**Comment by wm4** [comment]
What's even the problem? On https://mpv.io/manual/ there are links for both HTML and PDF versions of the current release.

**Comment by UserNaem** [comment]
They require the user to be online to view them, and they're only for the latest versions. Which is probably not a problem for most users and use cases, but can be bad if a non-latest version is being used. Also, the PDF manual is inconvenient to read.
