### ISSUE TITLE
Re: yet again vaapi bfa9b62

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#4904]
### mpv version and platform
latest master, 52789d6

### Reproduction steps
Play any video with hwdec unspecified, i.e. hwdec=, hwdec=yes 
### Expected behavior
get proper supported hwdec
### Actual behavior
Fails here on the probing, similar to https://github.com/mpv-player/mpv/issues/4865
### Log file
http://sprunge.us/IejD

Additionally, lightly off-topic, -  the commit in question says - 
        # Use GPU-accelerated video output by default.
           vo=gpu
Is it the intention to default to hwdec now?

**Comment by mc4man** [comment]
On the other hand with nvidia drivers no issue.
mpv --no-config --hwdec=  /home/doug/Videos/amostviolentyear-clip1_h1080p.mov 
Playing: /home/doug/Videos/amostviolentyear-clip1_h1080p.mov
 (+) Video --vid=1 (*) (h264 1920x816 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vdpau).
VO: [gpu] 1920x816 vdpau[yuv420p]
AV: 00:00:01 / 00:01:00 (2%) A-V:  0.000

**Comment by mc4man** [comment]
While I thought it was from the vo=gpu stuff it seems it was this commit
https://github.com/mpv-player/mpv/commit/bfa9b628589068acdbb04d97f86051063e82fd94

**Comment by wm4** [comment]
This was my editor not reloading the file correctly.
