### ISSUE TITLE
Enforce eac3 to ac3 conversion is specified in the configuration

### ISSUE THREAD

**Issue by edhelas** [mpv-player/mpv#4909]
### mpv version and platform

mpv 0.26.0 (C) 2000-2017 from Debian Testing repositories

### Reproduction steps

```
audio-channels=2
audio-spdif=ac3,dts
af=scaletempo,lavcac3enc=yes:auto:3
```

Launch a video containing a `eac3` soundtrack.

### Expected behavior

Because `eac3` is not put in audio-spdif, MPV should ask lavcac3enc to encode it in `ac3` and then output it in SPDIF

### Actual behavior

The `eac3` soundtrack is actually downmixed to stereo.

### Log file
```
Playing: file.mkv
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (eac3 6ch 48000Hz)
     Subs  --sid=1 --slang=eng (subrip)
AO: [pulse] 48000Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [opengl] 1920x1080 vaapi[nv12]
AV: 00:00:02 / 00:48:01 (0%) A-V:  0.000

Exiting... (Quit)
```
Having this feature could be really useful for people like me that have an amplifier that doesn't supports eac3 but only ac3.

**Comment by wm4** [comment]
`audio-channels=2` will force codec downmix. Remove it and it should work.

**Comment by ggogel** [comment]
This issue is long closed but I'm facing the same problem. With or without audio-channels=2. Shouldn't make any different though, because AC3 is technically a surround format encoded in a stereo signal.

**Comment by ggogel** [comment]
I finally got it working with these settings
```
audio-spdif=ac3
af=lavcac3enc=yes:640:3
```
The audio channels shouldn't make any difference though, because AC3 is technically a surround format encoded in a stereo signal. I think the issue was caused by the `auto` bitrate.
