### ISSUE TITLE
[Documentation] Cross-mentioning of smplayer?

### ISSUE THREAD

**Issue by shevegen** [mpv-player/mpv#4910]
Hello again mpv-devs,

Today I was modifying some of my old ruby scripts that have had mplayer hardcoded as main audio/video player. I replaced that with an environment variable which I toggle between mplayer and mpv (right now mostly mpv but I keep mplayer around, for several reasons). Then I suddenly wondered whether smplayer supports mpv, so I looked - and indeed, smplayer does support mpv!

It links in from at the very least here:

http://smplayer.sourceforge.net/en/mpv

Now to my question:

- Do you think that the documentation could also mention smplayer? Smplayer was putting a nice wrapper over mplayer and I used to use smplayer a lot (I mostly used mplayer on the commandline though, so smplayer was not that useful to me).

I am not affiliated with smplayer in any way, by the way. I just thought that it may be fair to also mention smplayer at mpv, aka cross-mention/links. It could be a new file perhaps or just a mention on the main readme. Anyway, please do feel free to close this here at any moment in time, thanks!

**Comment by wiiaboo** [comment]
It's mentioned in the same place as other mpv GUIs: https://github.com/mpv-player/mpv/wiki/Applications-using-mpv

mpv's manual concerns only mpv itself.

**Comment by garoto** [comment]
A+ for effort and fancy words.
