### ISSUE TITLE
Mute and unmute are not instant

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#4911]
### mpv version and platform

0.27.0-45-gf3ec494613, Windows 7 SP1

### Reproduction steps
Start playback of any video or audio file.
Pause.
Mute.
Unpause.
### Expected behavior
Volume muted instantly.
### Actual behavior
Audio plays for a split second before it's muted. Un-muting is similarly non-instant.

**Comment by lachs0r** [comment]
That’s because mpv does not use the system volume control, which means the latency depends on mpv’s and Windows’ playback buffer size. There were way too many issues with system volume control, so it got removed.

You can (partially) restore this behavior by changing your keybinds in input.conf to control ao-volume and ao-mute instead. See also #3322.

**Comment by dippyhippy** [comment]
This behaviour is also exhibited on my system, I was looking through the issue tracker and came across this. Do I need to submit a fresh issue?

Linux laptop 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u1 (2017-06-18) x86_64 GNU/Linux
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.4-2+b1

As stated in the original issue, if you mute a video when paused the mute effect doesn't take place until after the video has been resumed. This also occurs when reducing or increasing the volume.

**Comment by CounterPillow** [comment]
>Do I need to submit a fresh issue?

no, because it's something mpv can't fix since it's a shortcoming of the underlying system, which can be both Linux and Windows.

**Comment by dippyhippy** [comment]
@CounterPillow Not sure I understand your logic there, the commonality is surely mpv. This doesn't happen on, say, vlc; or any other media player I use. Can you please elaborate on what shortcomings you are referring to?

**Comment by dippyhippy** [comment]
There was an existing solution -> https://github.com/mpv-player/mpv/issues/3322

**Comment by CounterPillow** [comment]
@dippyhippy see lachs0r's comment as to why ao-volume no longer is the default.
