### ISSUE TITLE
--target-gamut option is not documented

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#4913]
Hi,

There's a sentence in `--gamut-warning` description in the man:

> ... it's a good idea to combine this with --tone-mapping=clip  and use --target-gamut to set the gamut to simulate.

However, `--target-gamut` itself is not documented, and it's not even clear if it can be used alone, without `--gamut-warning`.

Regards,
Alex

**Comment by haasn** [comment]
Oh, it should be `--target-prim`, not `--target-gamut`.

**Comment by fhlfibh** [comment]
UPD. The same goes for `--gpu-gamma`:

> --blend-subtitles=<yes|video|no>
Blend subtitles directly onto upscaled video frames, before interpolation and/or color management (default: no). Enabling this causes subtitles to be affected by --icc-profile, --target-prim, --target-trc, --interpolation, --gpu-gamma and --post-shader.

**Comment by kevmitch** [comment]
052ae5393a2282b7eeb2e824a526bc89bf01bf1f
