### ISSUE TITLE
Freezing with high FPS videos (on Windows 7)

### ISSUE THREAD

**Issue by dardoor** [mpv-player/mpv#4921]
**edited** with more info

### mpv version and platform

v.0.27.0, but it started with with v0.24.0. Windows 7 64bit.

### Reproduction steps

1. Open a high fps (I tried with 75+) video on Windows 7, with Flux or similar software (SunsetScreen) running.
2. Observe the playback or move the mouse pointer anywhere.

### Expected behavior

Normal playback, no freezing. Like in v0.23.0 and earlier.

### Actual behavior

The whole screen freezes twice for a second or so. The higher the FPS of the video, the sooner it starts freezing.

### Sample files

[high fps test.zip](https://github.com/mpv-player/mpv/files/1327651/high.fps.test.zip)
These files are Lagarith, but it happens with H.264 as well.
The 100fps causes freezing already within the first second or two, the 75fps one later.

The issue is probably related to [#4846](https://github.com/mpv-player/mpv/issues/4846). But this time it doesn't require a still image or moving the mouse pointer over the progress bar. And just like there, this does not happen on Windows 10.

**Comment by EzeKees** [comment]
tested on windows 8.1 without any problem. Did you change the video output? ("vo = opengl")

**Comment by dardoor** [comment]
No, but I tried that now and no change.

But I think I finally found what's causing it: **Flux (f.lux)**. Or to be more precise, a combination of Flux and Windows 7, because I have Flux on W10 and it's fine.
As soon as I exit Flux it doesn't freeze anymore (just disabling it isn't enough).

Mind you, with older (v.0.23) versions of mpv freezing doesn't happen with Flux on either.
So it's a combination of the three: new mpv, Flux and Windows 7.

**Comment by EzeKees** [comment]
Evidently has something to do with video drivers. Tried to update them?
From my own experience I say that if you have a modern machine, windows 7 "magically" spoil the drivers (mainly video). Before Win 8 and Windows 10 came out, I never had a problem, afterwards yes.

**Comment by dardoor** [comment]
Yeah, I tried updating the drivers. Didn't help.
But what did help is setting **vo=direct3d**.

**Comment by UserNaem** [comment]
I had the same issue (#4263) before, and now that you mention it, I do also have f.lux installed and running. This is what solved it for me:
```
hwdec=dxva2-copy
vo=opengl
opengl-backend=angle
angle-egl-windowing=yes
angle-renderer=d3d11
```

**Comment by dardoor** [comment]
Yeah, that works too. I see that you have an Nvidia card, so that kinda eliminates the driver vendor cause, because I reproduced this on two PCs with an ATI/AMD.

So the problematic combination is just: mpv 0.24.0+, Windows 7 and f.lux (or similar).

**Comment by Akemi** [comment]
if this is still an issue, please open a new issue.
