### ISSUE TITLE
.mpv config => run mpv in mute mode

### ISSUE THREAD

**Issue by prankousky** [mpv-player/mpv#4923]
Hi,

this is not really an issue per se, so I am not including all the version info, hope that is okay.

Is tere some line I can include in my .mpv file to set mpv to mute whenever it starts? i know i could just press "m" to mute, but i'd rather have it on mute **unless** i need to actually hear sound when using it... 

thanks in advance :)

**Comment by selsta** [comment]
You could try `mute`.

**Comment by prankousky** [comment]
Thank you :) Worked just fine.
