### ISSUE TITLE
Cannot switch to new video while mpv is running 

### ISSUE THREAD

**Issue by wynnsyt** [mpv-player/mpv#4926]
### mpv version and platform

mpv 0.26.0 and 0.27.0
macOS 10.13

### Reproduction steps

Double-click a video to play it. Then double-click another video.

### Expected behavior

mpv stops current video and plays the new one. 

### Actual behavior

A second mpv icon shows up in the dock and is not responsive. 

It can be killed normally by force quit, but only when the first mpv is running. If I quit the first instance, then the new icon remains in the dock although no process of mpv is running at all. In this state I cannot play any video by double-click any longer. 

Restoring from this requires killing WindowServer, or reboot.

### Log file

Nothing shows up in ~/Library/Logs/mpv.log, or system logs.

**Comment by AirPort** [comment]
This is probably some sort of system wide behavioural change with High Sierra.
I can reproduce it to some extent, although in my case it's not unresponsive, the system just opens a second instance of the bundle and it plays the new video, instead of overriding the already opened one.

**Comment by Akemi** [comment]
i bet it's the wrapper again. if this really broke and can't be fixed we need to remove it. related #4866.

for testing, you can delete this `mpv.app/Contents/MacOS/mpv-wrapper.sh` file in the bundle and change `mpv-wrapper.sh` to just `mpv` [here](https://github.com/mpv-player/mpv/blob/a5b97104cff358beebdb7ed1e96f7ab441295afa/TOOLS/osxbundle/mpv.app/Contents/Info.plist#L176) in the `mpv.app/Contents/Info.plist`. after that you probably need to rebuild the App cache (forgot the terminal command for that) or just rename the mpv bundle temporarily. `mpv` to `mpv2` should work.

**Comment by wynnsyt** [comment]
@AirPort 
I only ran into this immediately after upgrading to 10.13, so I suspect it is caused by the OS too.

@Akemi 
I tried removing the wrapper and editing the plist, after which mpv won't launch at all. Do you mind explain what you mean by "rebuild the app cache", because renaming the app bundle didn't help?

**Comment by VivaLosDoyers** [comment]
@Akemi removing `mpv-wrapper.sh`, changing `Info.plist`, and renaming the app is not sufficient. When you try to launch the app, it immediately exits.

**Comment by Akemi** [comment]
@wynnsyt  you can try `touch PATH/TO/mpv` or `killall -u "$USER" cfprefsd` (i believe that was the process), but seems like there is another issue (maybe the psn one).

i try to look into it tomorrow. i wasn't home today.

**Comment by doggles** [comment]
My issue is mostly related, so figure I'd add it on here.

macOS 10.13, 2016 15" MacBook Pro, mpv 0.27.0

Expected behavior the same: while first video is playing, double-clicking a second video from Finder will stop the first video and play the second video in the same instance.

Actual behavior: Difference in my situation is that while the second video _does_ play successfully in a new instance, while the first video continues playing, this is not how the app has ever behaved for me on macOS when built with the `--with-bundle` flag.

**Comment by Akemi** [comment]
for a quick test does any of the earlier releases work? if you could test 0.24, 0.25 and 0.26, pls.

**Comment by doggles** [comment]
Hey @Akemi, just tested from 0.21 through 0.26, same result for each. More High Sierra curveballs

**Comment by Akemi** [comment]
'great' news. then it probably will take a bit longer till i can fix this, need to update one of my machines first.

**Comment by Akemi** [comment]
i just tested it myself and 0.24 works for me as intended. any version after that, which uses the wrapper, has the problems mentioned here. @doggles if you have problems with <=0.24 too, that might be a different issue.

**Comment by wynnsyt** [comment]
Just downloaded 0.24 and sure enough it works.

**Comment by doggles** [comment]
@Akemi think I was up too late; meant to say 0.24 through 0.26, which would still be wrong since I just looked at my downloads and realized I grabbed 0.26 and 0.25 twice. :l echoing the other users here: issue isn't present in 0.24

**Comment by Akemi** [comment]
k thx for (re)testing. if i don't find another way to handle this the wrapper needs to go. basically a5b97104cff358beebdb7ed1e96f7ab441295afa needs to be reverted and some other ways need to be found for the things the wrapper fixed.

**Comment by Akemi** [comment]
it would be nice if you could test #4936.

**Comment by doggles** [comment]
Works on my end
