### ISSUE TITLE
2-Finger scrubbing is now Volumne, how to revert to Timeline scrubbing?

### ISSUE THREAD

**Issue by warhost** [mpv-player/mpv#4932]
### mpv version and platform

0.27.0 from https://laboratory.stolendata.net/~djinn/mpv_osx/

### Reproduction steps

Play a video, use 2 fingers on touchpad and scrub left or right.

### Expected behavior

The timeline should move.

### Actual behavior

The volume changes.

Any idea how to revert that to the old function, which I liked much more?

**Comment by CounterPillow** [comment]
You can set `AXIS_UP` and `AXIS_DOWN` in input.conf to seek, I believe it is those binds. Might also be `MOUSE_BTN3` and `MOUSE_BTN4`, but I think that was platform-specific in previous versions or something.
