### ISSUE TITLE
Seeking backwards (by seek -1 exact) is slower then seeking forwards

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#4935]
If I hold pressed a button associated with action `seek 1 exact`, mpv plays the video in default speed. when I do that in reverse (`seek -1 exact`), the playback is tow or three times slower. Is there a reason that is and could that be fixed? I would think that if I have already played the video, the images should be stored in cache and the playback should be fast enough, no?

I tried puttin this:

    [cache]
    cache=yes
    cache-default=5400000
    cache-backbuffer=4900000

into my config file but that does not seem to have made a difference.

**Comment by CounterPillow** [comment]
The reason is that non-intra codecs require you to decode from the last gop onwards, which means that backseeking requires decoding more frames than seeking forward.

**Comment by felagund** [comment]
But should not be the frames stored in cache when I have played the video just a second before? I have 16 GB of RAM so I do not mind having a 2GB cache of decoded frames - that shold be enough for a few seconds of playback both ways, no?

**Comment by wm4** [comment]
The code for exact seeking backwards and forwards is not different at all. They do exactly the same thing, doing an absolute seek to the target position.

**Comment by CounterPillow** [comment]
>But should not be the frames stored in cache when I have played the video just a second before?
in coded format, not decoded.

**Comment by felagund** [comment]
> in coded format, not decoded.

I see. So this would be a new feature to store them coded, right? Would it actually speed things up? One FullHD frame has what, 6MB of data? So that is 150 MB per second with 25 FPS? So a 2 GB RAM cache could hold about 13 seconds of video? That would be actually enough for my needs.

I am not sure how hard it would be to implement but it would be a useful feature for me.

**Comment by wm4** [comment]
The problem is that even if you can simply cache the decoded frames, you can't do that with all the other playback state, like the demuxer, audio, subtitles, or the frames that follow after the cached ones.

**Comment by kevmitch** [comment]
back in my day we didn't even have frame backstep
