### ISSUE TITLE
Option icc-profile-auto not working on macOS

### ISSUE THREAD

**Issue by ePirat** [mpv-player/mpv#4938]
### mpv version and platform
* macOS 10.13 (17A365)
* mpv git master (052ae53)
* ffmpeg version: git-2017-09-29-3df437c

### Reproduction steps
Start mpv with the `--icc-profile-auto=yes` argument:

```
mpv -v --icc-profile-auto=yes --pause path/to/file.jpg
```

### Expected behavior
mpv should use my default ICC color profile for the current screen.

### Actual behavior
mpv is not using the default ICC color profile for the current screen.

Looking at [vo_gpu.c:144](https://github.com/mpv-player/mpv/blob/HEAD/video/out/vo_gpu.c#L144) it seems like my log should contain a `Querying ICC profile...` line, that is only the case if I specify a path to an ICC profile though (`--icc-profile`), not when only `--icc-profile-auto` is set.

### Log file
http://sprunge.us/HKXc

**Comment by Akemi** [comment]
indeed that doesn't work. it starts working here when i add `--sigmoid-upscaling=yes` for example. is it the same for you? @haasn  might be interested in looking at this.

**Comment by ePirat** [comment]
Indeed, adding `--sigmoid-upscaling=yes` makes `--icc-profile-auto=yes` work as expected.

**Comment by haasn** [comment]
Does this diff fix it?

```diff
diff --git a/video/out/gpu/video.c b/video/out/gpu/video.c
index 8f56380789..563b3d89bf 100644
--- a/video/out/gpu/video.c
+++ b/video/out/gpu/video.c
@@ -3388,9 +3388,9 @@ static void check_gl_features(struct gl_video *p)
         } else if (p->opts.dumb_mode <= 0) {
             MP_WARN(p, "High bit depth FBOs unsupported. Enabling dumb mode.\n"
                        "Most extended features will be disabled.\n");
+            p->use_lut_3d = false;
         }
         p->dumb_mode = true;
-        p->use_lut_3d = false;
         // Most things don't work, so whitelist all options that still work.
         p->opts = (struct gl_video_opts){
             .gamma = p->opts.gamma,

```

**Comment by ePirat** [comment]
No

**Comment by haasn** [comment]
Hmm. Anyway, what seems to be happening is that `gl_lcms_has_profile` returns false in `reinit_from_options`, so it thinks it's not using a 3DLUT and therefore voluntarily switches into dumb mode.

What's weird is that preventing the voluntary dumb mode switch causes it to work. Can you post a log with `--gpu-dumb-mode=no`?

**Comment by haasn** [comment]
Also cc @wm4 3DLUTs work in dumb mode just fine, like the other color management options. So this logic should be changed anyway; I'm just not sure why my fix doesn't seem to do so.

**Comment by ePirat** [comment]
@haasn Sure, should I use the version with or without the patch?

**Comment by haasn** [comment]
Okay, I can reproduce the issue locally.

**Comment by haasn** [comment]
This patch should fix it. cc @wm4 not sure if this is the best way of doing things?

```diff
commit 5dce3b7f8e6624e77384166a0fd75942d9592069
Author: Niklas Haas <git@haasn.xyz>
Date:   Sat Sep 30 16:25:20 2017 +0200

    vo_gpu: enable 3DLUTs in dumb mode
    
    Unless FBOs are unsupported, this works. In particular, it's required to
    get ICC profiles working in voluntary dumb mode. So instead of
    blanket-disabling it, only disable it in the !have_fbo false case.

diff --git a/video/out/gpu/video.c b/video/out/gpu/video.c
index 8f56380789..63dd5586c8 100644
--- a/video/out/gpu/video.c
+++ b/video/out/gpu/video.c
@@ -3390,7 +3390,6 @@ static void check_gl_features(struct gl_video *p)
                        "Most extended features will be disabled.\n");
         }
         p->dumb_mode = true;
-        p->use_lut_3d = false;
         // Most things don't work, so whitelist all options that still work.
         p->opts = (struct gl_video_opts){
             .gamma = p->opts.gamma,
@@ -3411,9 +3410,12 @@ static void check_gl_features(struct gl_video *p)
             .tone_mapping_param = p->opts.tone_mapping_param,
             .tone_mapping_desat = p->opts.tone_mapping_desat,
             .early_flush = p->opts.early_flush,
+            .icc_opts = p->opts.icc_opts,
         };
         for (int n = 0; n < SCALER_COUNT; n++)
             p->opts.scaler[n] = gl_video_opts_def.scaler[n];
+        if (!have_fbo)
+            p->use_lut_3d = false;
         return;
     }
     p->dumb_mode = false;
```

**Comment by wm4** [comment]
I thought you said ICC works in dumb mode?

Patch probably ok, not sure about icc_opts life time issues.

**Comment by haasn** [comment]
@wm4 I was unsure about the lifetime issues too, but when you consider that this function does the exact equivalent of setting all of the unused options to `NULL`, it would have been a bug in the current code to just delete it randomly like that.

> I thought you said ICC works in dumb mode?

I thought so too, but it's only the non-ICC options that still worked (tone mapping etc.)

**Comment by ePirat** [comment]
@haasn Just tested it and the new patch fixes it.
