### ISSUE TITLE
mpv is green when playing audio-only files.

### ISSUE THREAD

**Issue by blah1** [mpv-player/mpv#4939]
### mpv version and platform
Regression in mpv 0.26.0-157-g63b1031ca2
mpv 0.26.0-156-g817bb2bbbe is unaffected.
Bug persists in latest mpv-git: mpv 0.27.0-84-g052ae5393a

### Reproduction steps
Open a media file that has no image, thumbnail, or video to display, using --profile=pseudo-gui. 
No bugs noticed when opening a video, or audio file with a cover image.

### Expected behavior
mpv opens a black window with pseudo-gui working properly.

### Actual behavior
mpv opens a green window with black bars outside the default aspect ratio, but pseudo-gui works properly.

### Log file
mpv 0.26.0-157 (bugged): https://ptpb.pw/U670.txt
mpv 0.26.0-156 (working): https://ptpb.pw/Gidq.txt
mpv 0.27.0-84 (bugged): https://ptpb.pw/JXeF.txt
I used the same file for consistency, but it occurs on other files, uncluding .flac, .m4a, and .ogg

### Screenshots
mpv 0.26.0-157 (bugged): https://ptpb.pw/i61Q.png
mpv 0.26.0-156 (working): https://ptpb.pw/twl0.png

### Notes
The black bars are a non-issue, to be expected from i3 forcing a window into a strange resolution.
The bug is not reproducable on my newer laptop; both run ArchLinux and i3wm. This laptop that I have issues on has an Intel Atom CPU N470 with an Intel Atom D4xx/D5xx/N4xx/N5xx Integrated Graphics Controller, and uses xf86-video-intel for graphics drivers. (Modesetting drivers do not run because it is too old to run GLAMOR, apparently.)
I already read the system requirements "mpv is not intended to be used with bad GPUs." but I figured this might be an exception because it is a regression.

**Comment by haasn** [comment]
It's not immediately clear to me why 63b1031ca2 causes the regression, but I'd like to point out that the result (#008700) *exactly* matches the color you get when you decode #000000 as YUV instead of RGB.

**Comment by blah1** [comment]
Using --vo=x11 fixes the green background for audio files for me. 0.26.0-157 Log: https://ptpb.pw/JsrL.txt
It does not change the green bar at the bottom in bug #4940 though. Log: https://ptpb.pw/kqJz.txt
It also lags the video a lot more, so it wouldn't be a real fix anyway.
I'm guessing that the underlying cause for both issues is still the same though, so I'd still call them duplicates for now.

**Comment by blah1** [comment]
Both bugs seem to be fixed as of https://github.com/mpv-player/mpv/commit/b12b92822182fddd2fc3d5116d505371ac72719e.
Closing.
