### ISSUE TITLE
green borders instead of black borders in mpv 0.27 when using expand video filter

### ISSUE THREAD

**Issue by xdilemite** [mpv-player/mpv#4940]
mpv 0.27 windows

using
-vf=expand=0:-50:0:0:

black border in mpv version 0.26

green instead of black borders in mpv version 0.27

**Comment by blah1** [comment]
Possibly related to the issue I opened a couple minutes ago. https://github.com/mpv-player/mpv/issues/4939
Your issue also affects both of my laptops, not just my old one.
Confirming on Archlinux, i3wm, mpv-git 0.27.0-84, Intel Atom graphics. Log: https://ptpb.pw/Gmmb.txt
And Archlinux, i3wm, mpv 0.27 stable, Intel i7 graphics. Log: https://ptpb.pw/wzZy.txt

Just did a regression test again, works on 0.26.0-156: https://ptpb.pw/2rww.txt
broken on 0.26.0-157: https://ptpb.pw/LYGU.txt
Confirmed same bug.

**Comment by blah1** [comment]
Confirming on non-Intel hardware: Archlinux, i3wm, Radeon RX 470, mpv 0.27.0 stable also has the bug: https://ptpb.pw/8BQ3.txt

**Comment by haasn** [comment]
Closing this in favor of #4939.
