### ISSUE TITLE
pause-when-minimize.lua makes mpv freeze on quit on macOS

### ISSUE THREAD

**Issue by anonmonogatari** [mpv-player/mpv#4942]
### mpv version and platform
/usr/local/Cellar/mpv/HEAD-77547d7
macOS 10.12.6

### Reproduction steps
Press q to quit.

### Expected behavior
mpv quits normally.

### Actual behavior
Mpv randomly freezes upon pressed "q". 

### Log file
Cannot produce log file when it freezes.

### Sample files
[mpv.conf](http://sprunge.us/Ofih)

I actually tried everything to solve this problem. 

- Recompiled with every possible config.
- Deleted mpv.conf
- Deleted all user scripts (solved the problem, then installed back one by one to find the faulty one)

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
