### ISSUE TITLE
mpv hwdec doesn't correctly display color of yuvj420p video

### ISSUE THREAD

**Issue by tellowkrinkle** [mpv-player/mpv#4946]
### mpv version and platform
```
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Sep 17 23:49:00 BST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.4
```
OS: macOS High Sierra 10.13（17A365）

### Reproduction steps

1. Make sure mpv is using the hardware decoder
2. Generate a white video with the command `ffmpeg -f lavfi -i color=white:640x480:d=3 -pix_fmt yuvj420p output.mp4`
3. Open `output.mp4` with mpv
4. Open `output.mp4` with either QuickTime or VLC (for comparison)

### Expected behavior

Both QT/VLC and mpv are completely white

### Actual behavior

mpv is considerably darker than QT/VLC, specifically 235/235/235 instead of 255/255/255

### Log file

http://sprunge.us/LbgL

### Sample files

(This is the output of the above ffmpeg command, so its use isn't required)
https://0x0.st/FZA.mp4

**Comment by wm4** [comment]
Does it look correct without hwdec?

**Comment by tellowkrinkle** [comment]
It does look correct without hwdec.
I'm using a 2014 MacBook Pro with an I7-4980HQ if it helps

**Comment by wm4** [comment]
I suspect videotoolbox itself resamples the data to limited range. Can you try whether the result is correct with `--vf=format:colorlevels=limited`?

I think this is because we use `kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange`. For full range video, we should use `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange`. mpv itself doesn't make the range a property of the pixel format, so this is messy.

**Comment by tellowkrinkle** [comment]
Yep, it works properly with `--vf=format:colorlevels=limited`

**Comment by wm4** [comment]
I tried `kCVPixelFormatType_420YpCbCr8BiPlanarFullRange`, but it doesn't change anything. Piece of shit Apple APIs.

**Comment by wm4** [comment]
(I can't find anything else that would make the Apple decoder to stop behaving like this, and it'd be unwise to adjust the color levels metadata from the hwaccel. So this is probably indeed a WONTFIX, at least from my side.)
