### ISSUE TITLE
Going to next file in playlist toggles fullscreen when it is set as extension specific

### ISSUE THREAD

**Issue by anticitizen4** [mpv-player/mpv#4947]
### mpv version and platform

0.27, MacOS 10.11.6

### Reproduction steps

I have this in config:
```
[extension.mkv]
fullscreen=yes
```

### Expected behavior

All mkv files should go fullscreen both by opening a single file and by changing file through playlist.

### Actual behavior

Going to the next file in playlist causes fullscreen to be toggled (every next file switches fullscreen state).

**Comment by wm4** [comment]
That's as designed. Use a Lua script to circumvent.
