### ISSUE TITLE
Turning off video in YouTube playback with webm/opus won't allow jumping forward unless hr-seek is enabled

### ISSUE THREAD

**Issue by wolftune** [mpv-player/mpv#4955]
### mpv version and platform

Ubuntu 2:0.27.0~xenial1 

### Reproduction steps

* run `mpv https://www.youtube.com/somevideocode`
* hit `_` to remove the video and be audio-only back in terminal
* hit forward arrow key

### Expected behavior

Jump forward in track

### Actual behavior

Jumps to previous 10-second mark already played (i.e. goes from 0:05 seconds to 0:00 or from 1:23 to 1:20) and can only keep jumping back to that same spot.

With the video enabled, everything is normal, forward jumping works

`hr-seek=yes` solves this.

### Log file

https://pastebin.com/FgEH25AQ

**Comment by mc4man** [comment]
Likely because your getting their webm with opus audio. If you force them to serve you up aac(m4a) then what you want would work fine. 
May be other ways, I dunno..

**Comment by wolftune** [comment]
@mc4man why would webm/opus matter? I don't have this problem when using opus audio files locally. I'm actually not immediately finding or knowing how to get a full webm/opus file locally (I'm sure I could with enough time and effort) in order to test that specific case. But the fact that I can do this with the very same thing as long as the video is *shown* but not with the video hidden seems quite unrelated to codec.

**Comment by mc4man** [comment]
Well I don't know the tech side of any of this, others certainly do.
All I'm trying to tell you what you are doing won't work as you're doing. Maybe it's because it ends up as a mkv.
If you were to do something like this in mpv.conf or on cli (then with --) it would work
```
ytdl-format="bestvideo[width<=4096][height<=2304]+bestaudio[ext=m4a]/best[ext=mp4]/best"

```
you could lower those values if you wish to 1920 1080 or whatever

**Comment by wolftune** [comment]
Okay, that's quite surprising to me, but you're right that it works. Why, I have no idea, that seems like a real bug.

**Comment by wolftune** [comment]
Wow, this is so weird. Tried lots of things. https://github.com/rg3/youtube-dl/issues/6018 was relevant for the frustrating fact that youtube-dl seems to refuse to let `prefer-free-formats` actually prefer free formats when they aren't the highest quality. I prefer free formats and wanted to figure out if there was a way to operate okay with them, but I don't understand the format commands enough to write one to try all the variations.

It certainly appears that the bug this issue is about appears whenever the format is webm / opus or related.

**Comment by wolftune** [comment]
Note: although the jump fails, I can fast-forward with shift-right-arrow, except that I can't do that in my terminal because that reserves shift-arrow for moving between terminal tabs! But it works if I open a GUI version of mpv.

Is there any way to change the input to mpv so that (A) I swap the non-shift arrow function and shift-arrow (I want to make the 1-sec the default) and (B) change from shift-arrow to something else like Alt-arrow?

**Comment by haasn** [comment]
I think the concrete formulation of this bug is that mpv uses keyframe seeks even when the video track is disabled, where it should be using exact seeks. (Keyframe seeking for audio is basically nonsensical)

**Comment by garoto** [comment]
I could reproduce the behavior with these two command lines about 15~20m ago:

`mpv --ytdl-format="248+251" "https://www.youtube.com/watch?v=gtZ7OVoI2nc"`
`mpv --ytdl-format="248+251" "https://www.youtube.com/watch?v=lmEAzxIfeDo"`

(248 is VP9 1080p video and 251 is Opus audio)

Now, they both seek just fine when disabling the video track OR appending `--no-video` to the CLI parameters. Kinda confused now; google content shenanigans perhaps?

**Comment by wolftune** [comment]
when I use `--no-video` it works overall. The glitch happens when I start with video and then hit `_` to remove the video track

**Comment by wolftune** [comment]
Oh, `hr-seek=yes` seems to have solved it entirely!

**Comment by garoto** [comment]
Yeah, was about to post something similar. @haasn nailed it I guess. Adding `hr-seek=yes` to the CLI arguments seems to fix it.

**Comment by garoto** [comment]
@wolftune you can close this issue by the way.

**Comment by wolftune** [comment]
@garoto shouldn't the underlying issue be fixed though? (i.e. not using frames if playing audio-only) or was it fixed?

**Comment by garoto** [comment]
Oh yeah, you are correct, my bad.

**Comment by wiiaboo** [comment]
Can you still reproduce this with 0.28 or git master?

**Comment by wolftune** [comment]
So far, no. I removed the hr-seek item in my config, tried a few things. Seems fixed!
