### ISSUE TITLE
[Not sure if bug] Raw "audio-delay" property returns negative -0.000000

### ISSUE THREAD

**Issue by garoto** [mpv-player/mpv#4959]
### mpv version and platform
Windows 8.1 + lachs0r's latest build.
```
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed Sep 13 04:18:08 CEST 2017
ffmpeg library versions:
   libavutil       55.74.100
   libavcodec      57.105.100
   libavformat     57.82.100
   libswscale      4.7.103
   libavfilter     6.105.100
   libswresample   2.8.100
ffmpeg version: N-87286-g6ce4a635ed
```
### Reproduction steps
Run mpv with the following command line:

`mpv --no-config --osd-msg1="Audio Delay RAW value: ${=audio-delay}\n${!=audio-delay==0.000000: This line should not be shown if the raw audio-delay value is 0.000000 (${=audio-delay})}" <media-file>`

Now decrement `audio-delay` by pressing the default keybind: <kbd>CTRL</kbd>+<kbd>-</kbd> a couple of times till is shows a negative value.
Now press the increment `audio-delay` default keybind <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>=</kbd> untill it reaches `0.000000` again and observe how the conditional expansion is not respected.

### Expected behavior
Raw `${audio-delay}` property should not return negative zero value when its value is simply zero.

### Actual behavior
`${audio-delay}` will display negative 0, making `{!=audio-delay==0.000000: test}` fail after decrementing past below zero and back.

---
This is obviously a minor issue from a end-user pov, since one can easily workaround it by simply using `${!audio-delay==0 ms:[...]}` instead, but I thought I should report about it in any case.

Edit: added screenshot fwiw ![screenshot-0596-05-10-2017](https://user-images.githubusercontent.com/11768175/31259717-3e017778-aa1f-11e7-974b-73362a09546f.png)

**Comment by lachs0r** [comment]
That’s just floating point error (value actually isn’t exactly 0).
