### ISSUE TITLE
no config file found

### ISSUE THREAD

**Issue by negativeions** [mpv-player/mpv#4960]
mpv 0.27
macOS 10.12.6

Everytime I press cmd-, I get a message saying "no config file found".... is this normal? Are there no GUI preferences? Where do I get these config files?

**Comment by Hrxn** [comment]
https://mpv.io/manual/master/#configuration-files

**Comment by negativeions** [comment]
mpv.conf is not in the configuration directory. On macOS, the folder was empty.

**Comment by negativeions** [comment]
and it's empty.

**Comment by Hrxn** [comment]
Yes, correct. Always the same principle (i.e. other programs as well): The application tries to read those files, but they don't exist in the first place, so no settings get used and the program runs in default mode. You have to create those files for yourself, any simple text editor should work.

**Comment by lachs0r** [comment]
To summarize: Yes, this is normal. No, there are no GUI preferences. You write those config files yourself. Create a file called mpv.conf in one of mpv’s configuration directories and enter any options you wish to change from their defaults.
