### ISSUE TITLE
lavfi-complex, movie filter and Windows absolute paths

### ISSUE THREAD

**Issue by AxelTerizaki** [mpv-player/mpv#4962]
mpv fails to load if you use Windows absolute paths (C:/somethingsomething) in the lavfi-complex parameter.

### mpv version and platform

Tested on 0.25 and 0.27

### Reproduction steps

1. Make a small picture, like a QRCode in a directory like C:\test
2. Launch mpv with the following command 👍 
```
mpv path/to/video.mp4 --lavfi-complex="movie=C:/test/qrcode.png[logo]; [logo][vid1]scale2ref=150:150[logo1][base];[base][logo1] overlay=20:20[vo]"
```

### Expected behavior

mpv should play the video with the picture on top of it, in the upper left corner

### Actual behavior

Refuses to start up.

### Log file

The displayed message is 
```
[   0.027][e][ffmpeg] AVFilterGraph: Error initializing filter 'movie' with args 'd:/perso/karaokemugen-app/app/temp/qrcode.png'
[   0.027][f][cplayer] parsing the filter graph failed
```

See the attached log file for more details : 
[log.txt](https://github.com/mpv-player/mpv/files/1362630/log.txt)

### Sample files

Just to make it easier, here's the qrcode in question : 
![qrcode](https://user-images.githubusercontent.com/4531597/31277452-51044e9a-aaa1-11e7-9943-414cb124fc2d.png)

Note that it fails no matter the image/video combination

### Notes

I ran several tests and it works perfectly if you don't put a `:` character in the path. For example :
```
mpv path/to/video.mp4 --lavfi-complex="movie=test/qrcode.png[logo]; [logo][vid1]scale2ref=150:150[logo1][base];[base][logo1] overlay=20:20[vo]"
```
This works perfectly and displays the qrcode as long as you launch mpv from the directory below the `test` one.

Judging from the log file, it might be a problem with ffmpeg more than mpv, but I'm not too sure if mpv can't do something about it...

I tested using `\` instead of `/` -> failure

I tested trying to escape `:` with `\`, fails as well.

Does anyone have any ideas ? (apart from the obvious "don't use Windows" but my app relying on mpv is  multiplatform so... :)

**Comment by lachs0r** [comment]
That’s not going to fix this issue, but I’d recommend using libmpv and starting out with one of the QML examples at https://github.com/mpv-player/mpv-examples/tree/master/libmpv. I once made a schedule thing for video screenings that displayed an animated countdown with a generated QR code before each video, and would overlay a logo while playing those videos. That was all done in QML, no lavfi involved. Only had to write maybe half a dozen lines of C++. You should definitely give it a try, it’s very easy.

**Comment by AxelTerizaki** [comment]
My problem is my app is using nodejs, so I don't have access to libmpv with it, but I use the mpv command interface via sockets.

Unless there is a way to overlay stuff during runtime which I'm unaware of... (that would be ideal, because right now I have to know the dimensions of the image / video I'm playing in order to scale the QRCode accordingly)

**Comment by garoto** [comment]
Escaped single quotation marks works for me:

`mpv path/to/video.mp4 --lavfi-complex="movie=\'C:/test/qrcode.png\'[logo]; [logo][vid1]scale2ref=150:150[logo1][base];[base][logo1] overlay=20:20[vo]"`


Escaped backslashes (`\'C:\\test\\qrcode.png\'`) also appear to work as expected.

**Comment by AxelTerizaki** [comment]
That indeed solves my issue, thank you.

I might post a feature suggestion to be able to do this kind of stuff via the command interface, but for now I'll live with setting it before runtime on the commandline.

Thanks again !

**Comment by marnunez** [comment]
Hi! How about filenames with spaces?

`C:\mpv\mpv.exe "0053~aa~Walking 02_tvc1.avi" --lavfi-complex="movie=\'0053~aa~Walking\ 02_tvc1.avi\'[in1];movie=\'0053~aa~Walking\ 02_tvc2.avi\'[in2];[in1][in2]hstack[vo]"`

I tried escaping and double escaping the spaces with no avail. Any ideas?
