### ISSUE TITLE
mpv mis-identifies paletted RGB in mp_image_params_guess_csp

### ISSUE THREAD

**Issue by haasn** [mpv-player/mpv#4965]
### mpv version and platform

`0.27.0-101-g10dd120ba-dirty`

### Reproduction steps

1. `mpv https://0x0.st/F0D.png`

### Expected behavior

mpv infers gamma=sRGB, since it's an RGB file.

### Actual behavior

mpv infers gamma=BT.1886 and then sticks with this choice throughout the filter chain:

```
[vd] Decoder format: 1920x1080 [0:1] pal8 auto/auto/auto/full CL=unknown (auto 0.000000/0.000000/0.000000)
[vf] Video filter chain:
[vf]   [in] 1920x1080 pal8 bt.709/bt.709/bt.1886/full SP=1.000000 CL=unknown
[vf]   [scale] 1920x1080 argb rgb/bt.709/bt.1886/full SP=1.000000 CL=unknown [a]
[vf]   [out] 1920x1080 argb rgb/bt.709/bt.1886/full SP=1.000000 CL=unknown
```

Since the decoder just exports "auto" for everything, the first source for the bt.1886 choice must be `*_guess_csp`, which probably picks BT.1886 because it takes the `YUV/other` branch.

### Log file

https://0x0.st/F0k.log

### Sample files

https://0x0.st/F0D.png

### Notes

I'm not sure what the best way to work around this is. Maybe we could figure out a way to only guess the colorspace *after* the filter chain? Or maybe we should treat "pal8" as also being RGB, because the *contents* of the palette are RGB in this case? (How would you even detect that?)

**Comment by haasn** [comment]
Alternatively, it might be the case that the correct way to work around this is to have the PNG decoder in libavcodec export sRGB tagging for untagged PNGs (and perhaps infer the best choice from the tagged gAMA/cHRM otherwise?).

cc @atomnuker thoughts?

**Comment by wm4** [comment]
It's just part of our general logic - we might want to change it. For now I've fixed this particular issue.
