### ISSUE TITLE
macOS 10.13 High Sierra Verifying issue

### ISSUE THREAD

**Issue by shengyang998** [mpv-player/mpv#4966]
System and mpv version:

macOS:  10.13
mpv:  0.27.0 (OS X builds by stolendata) [checkout here](https://laboratory.stolendata.net/~djinn/mpv_osx/)

The large files(1gb up), got the issue that have to Verifying every time when open the videos.

see also here:
https://forums.macrumors.com/threads/“verifying”-upon-opening-every-file.2065395/

My currently workaround is: 
using shell command 
```shell
mpv [path_to_file]
```
 to open the file.

**Comment by AirPort** [comment]
As it shows in the thread you linked it's a system wide issue, mpv has no means to control or work around it.

(`sudo xattr -rd com.apple.quarantine *` in the user directory solved the problem permanently here).
