### ISSUE TITLE
Hotkey to show filename in OSD

### ISSUE THREAD

**Issue by Ambrevar** [mpv-player/mpv#4967]
I believe `I` used to display the filename on screen.  It seems that this binding is gone in recent versions.  Any explanation for this?  What was the command bound to `I`?

**Comment by Argon-** [comment]
I'm just guessing but maybe `I show-text "${filename}"`.
Self-plug: once this is merged, it will also show the filename with `i`: https://github.com/mpv-player/mpv/pull/4918

**Comment by wiiaboo** [comment]
https://github.com/mpv-player/mpv/commit/2e84934be7d419da91c2bc0682d71087439d66ad#diff-0aa4c1e9a9d3f1da17a742c557f34361

**Comment by charmparticle** [comment]
@Ambrevar just add this to your ~/.config/mpv/input.conf:

    show-text "${filename}"

et voila.
