### ISSUE TITLE
crash with sample file

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#4970]
Hi,

with a recent build I get a crash with one of my samples, it was fine with a older build.

I'm on Win 10 x64 using hwdec=yes with GTX 1060

https://www.dropbox.com/sh/m8ys30m5cjug07a/AAAWXN_7rMxhCK7p5aTxNs51a?dl=0

**Comment by lachs0r** [comment]
Could you be any less specific?

**Comment by stax76** [comment]
yes I'm lazy but should be sufficient to reproduce

**Comment by lachs0r** [comment]
Okay, give me a second, I’m gonna get my crystal ball and some hardware to reproduce this with.

**Comment by stax76** [comment]
http://sprunge.us/MEKf

**Comment by lachs0r** [comment]
Much better. Now someone might be able to actually figure out what’s going on.

**Comment by haasn** [comment]
Does it still crash with `--hwdec=no`?

**Comment by stax76** [comment]
With mpv.conf hwdec=no it doesn't crash.

I just tested some other VP9 files, all crash so problem is VC9 specific.

**Comment by Akemi** [comment]
please open a new issue if this still persists.
