### ISSUE TITLE
Taking screenshots does not work with win/vulkan

### ISSUE THREAD

**Issue by wrielxc** [mpv-player/mpv#4972]
### mpv version and platform
https://github.com/mpv-player/mpv/commit/9c806bc299b25210d96a8cc9b2acf3b08d2d7936, Windows 7 64 bit

### Reproduction steps
Taking a screenshot with `Ctrl+S` and `mpv --no-config --gpu-api=vulkan --gpu-context=win` results in
`Taking screenshot failed.` being recorded in the log. It works fine with `--gpu-api=opengl`

In both cases the video plays fine both on full-screen and windowed.

### Expected behavior
A screenshot being saved.

### Actual behavior
No screenshot being saved.

### Log file
https://0x0.st/Csl.txt

`msg-level=all=trace`
https://0x0.st/Csd.txt

### Sample files
Every file I've tried has this issue.

**Comment by atomnuker** [comment]
Its a known issue, it would take a lot of work and would probably reduce performance and increase memory if implemented. IMO the correct way to solve this would be to just have the backends themselves do the output for both opengl and vulkan.

**Comment by haasn** [comment]
To be more specific, this limitation only applies to `screenshot window`, not the regular screenshot stuff.

It's actually not as bad as @atomnuker makes it out to be, but the screenshot mechanism would have to be fundamentally extend support for rendering-to-textures and adding a `ra_tex_download` (into a TEX_UPLOAD buffer, I guess?).

However, I most likely won't get around to it until libplacebo.

**Comment by Akemi** [comment]
i believe this works now with the new backend.
