### ISSUE TITLE
Keyboard shortcut modifier Ctrl+Alt+Shift stopped working as of 0.27.0

### ISSUE THREAD

**Issue by johnlee1st** [mpv-player/mpv#4973]
### mpv version and platform

The 0.27.0 binary available on [https://mpv.srsfckn.biz/](https://mpv.srsfckn.biz/), running on Windows 7 x-64

### Reproduction steps

1. Add the following in input.conf:
`Ctrl+Alt+Shift+p set pause yes`

2. Press the keyboard shortcut combination while a video is being played back.

### Expected behavior

The player is supposed to be paused, which worked prior to the latest release, 0.27.0.
In contrast, the following still does work:
`Ctrl+Alt+p set pause yes`

### Actual behavior

Running mpv with the "--input-test" option reveals that the player apparently fails to detect the modifier combination altogether.

### Log file

FWIW, Ctrl+Alt+Shift+p left no trace in the log file, while Ctrl+Alt+p did and worked.

[https://pastebin.com/ty4bTsHu](https://pastebin.com/ty4bTsHu)

**Comment by thebombzen** [comment]
Did you try using `Ctrl+Alt+P` rather than `Ctrl+Alt+Shift+p`? mpv uses `P` instead of `Shift+p`

**Comment by johnlee1st** [comment]
thebombzen, of course I did. Same results.

**Comment by garoto** [comment]
Weird, seems to be working fine for me on 8.1

**Comment by haasn** [comment]
Works for me on Linux/X11

**Comment by rossy** [comment]
Do you have the video window or the console window selected when you enter this keystroke? I can get ``Ctrl+Alt+P`` to show up with ``--input-test`` when I press ``Ctrl+Alt+Shift+p`` while the video window is active, but I can't get it to work while the console window is active. It doesn't work in the console window with 0.26.0 either.

**Comment by johnlee1st** [comment]
rossy, I don't even use the console window on a regular basis, as I usually run `mpv.exe`.  It makes no difference for me which window I have selected even when I run `mpv.com`.

**Comment by garoto** [comment]
Try running mpv.com via a cmd window with `--msg-level=input=debug` as argument. It should properly identify the ctrl+alt+P keybinf in the console window, like below:
```
input: key code=0x600004e 'Ctrl+Alt+N' down
input: key 'Ctrl+Alt+N' -> 'cycle pause' in 'default'
```

**Comment by Dudemanguy** [comment]
Very old. May or may not still exist. Please open a new issue if it does.
