### ISSUE TITLE
ICC and sRGB with unprofiled material

### ISSUE THREAD

**Issue by Popkultur** [mpv-player/mpv#4975]
### Reproduction steps
use wide gamut display

### Expected behavior
movies without profile information should be treated like sRGB

### Actual behavior
sRGB is displayed wrong

Description: mpv should have the possibility to make at least sRGB the standard profile for media without profile information. So providing a icc profile for a wide gamut display it should then treat colors of unprofiled material like sRGB and this should lead to the correct display of unprofiled material on a wide gamut display. Probably with an option --unprofiled-sRGB or the like.

**Comment by haasn** [comment]
I don't understand the issue, and the lack of a log or test file doesn't help. Also, mpv 0.22 is pretty old.

**Comment by Popkultur** [comment]
okay, I also seem to not understand color management for movies, further reading:
http://www.oyranos.org/2012/06/movie-luts-inside-icc-profiles/

So I need to switch my display to sRGB for movie playback so far. I don't know how to technically solve the problem.
