### ISSUE TITLE
Movies with Alpha are displayed Premultiplied with black

### ISSUE THREAD

**Issue by NNois** [mpv-player/mpv#4983]
Hi, we have issues with transparent videos withe well know premul/unpremult stuff
I've put some demo files together at the bottom

what_we_should_see
![what_we_should_see](https://user-images.githubusercontent.com/2362053/31540734-b8c92260-b00c-11e7-8582-3553dfcd4f0b.png)

what we actually see in mpv
![what_we_see_in_mpv_171013](https://user-images.githubusercontent.com/2362053/31540756-c864c7e2-b00c-11e7-9bac-d163ac7b95fd.png)

why ? because the decoder multiply the rvb channel with the alpha channel, then display it so you end up with a premultiplied image "bug"

If source is premultiplied with black
the rvb is
![checkalpha_ qtrle_premultiplied_rvb_screenshot png](https://user-images.githubusercontent.com/2362053/31541072-cb2785a4-b00d-11e7-9575-2ec46fe4dcc6.png)
the alpha is
![alpha_channel](https://user-images.githubusercontent.com/2362053/31541083-d494b440-b00d-11e7-834f-f1b7764f1ee1.png)

If source is unpremultiplied
the rvb is
![rvb_channel](https://user-images.githubusercontent.com/2362053/31541100-e174234e-b00d-11e7-9094-98b57c20ecf4.png)
the alpha is
![alpha_channel](https://user-images.githubusercontent.com/2362053/31541106-e7224fb4-b00d-11e7-9195-73634d7dc6a2.png)

So what mpv should do is
if premultiplied -> unpremultiply before compositing it to the checker grid
if unpremultiplied -> do nothing and comp it to the checker grid

This is tricky stuff but for example quicktime file with a codec compatible with an alpha channel do contain some bit about the source mode if it's a premult on or not. Some image file format too implies it, for example pngs file are always unpremultiplied.

Maybe a first step for MPV should be to do nothing, so at least unpremultiplied stuff are ok to play without bug 

PS: maybe you need more media format like a prores4444 file ? please let me know

### Sample files
https://drive.google.com/drive/folders/0B1K5Lo1-_y9QTXNNYWFNYzFwZkE?usp=sharing

**Comment by wm4** [comment]
FFmpeg thinks all alpha is unpremultiplied.

Do you know whether the alpha mode is defined for mov? Is there a flag in the file headers?

**Comment by NNois** [comment]
Hi,
FFmpeg is right I think ;-) So at least we should display correctly unpremultiplied movies in MPV. Please find an unpremultiplied movie in the files previously linked.

Yes there is some sort of alpha mode flag in the header because Graphics Apps like Adobe After effect switch to the right mode with mov files. But I don't know where to look exactly but ffmprobe don't see any differences between the two mov files provided...

**Comment by wm4** [comment]
Not sure if it's correct now.

With boxdumper I can't see any difference between the premultiplied and unpremultiplied files, except creation_time and modification_time.

**Comment by NNois** [comment]
I can confirm it's fixed ;-)
