### ISSUE TITLE
Broken MKV error message when using authorized IANA MIME types for font attachments.

### ISSUE THREAD

**Issue by jspaces** [mpv-player/mpv#4992]
### mpv version and platform
Latest master git version 6d534138ed compiled as of today October 14, 2017.
Archlinux fully patched as of today October 14, 2017.

### Reproduction steps
Play MKV video where MIME type for attached fonts is **application/font-sfnt**, **font/ttf** or **font/oft**.

### Expected behavior
Play MKV video without listing MIME type is not correct when using any of the default authorized [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml#font) ttf or otf MIME type definitions.

### Actual behavior
When the video is played with the MKV file has the TrueType or OpenType fonts listed as application/font-sfnt, font/ttf or font/oft the following message occurs:
MIME type application/font-sfnt (or font/ttf or font/oft). Assuming this is a broken Matroska file, which was muxed without setting a correct font MIME type.

### Notes
Please note that this MIME type was put in place in [2016.](http://www.iana.org/assignments/media-types/application/font-sfnt) IANA also has added font/ttf and font/oft as font mime types this [year ](https://tools.ietf.org/html/rfc8081) thus these MIME types should also be acceptable without the error message that the MIME type are not being set correctly. The video plays fine without issue when the MIME type error messages appear when the file is loaded. No other error message(s) appear when playing the file.

### Details
I ran Mkvtoolnix v17.0.0 to package the MKV video after editing the ASS script file to change the fonts and edit some lines. When the new fonts are added, Mkvtoolnix lists the attachments as application/font-sfnt, I can easily change the mime type to font/ttf or font/otf since it is also defined in /etc/mime.type file. The **unofficial** MIME type **application/x-truetype-font** was not even listed as an option until I created at local user mime type definition for it. 

### Media information file showing mime types of attachments.
[video-info.txt](https://github.com/mpv-player/mpv/files/1384997/video-info.txt)

**Comment by wm4** [comment]
Which are the mime types that should be added?

**Comment by jspaces** [comment]
Sorry for the late reply. I have been extremely busy with work relate stuff.
I believe that all 3 should be added.
The "application/font-sfnt" at this time appears to be the default which was added in 2016.
The "font/ttf" and "font/oft" look like they will be the default in the near future since they were just added this year.

**Comment by dali99** [comment]
application/font-sfnt is deprecated and replaced by font/sfnt

* font/ttf
* font/otf

should definetly be added

* font/sfnt
* font/collection
* font/woff
* font/woff2

are also valid font types in [RFC8081](https://tools.ietf.org/html/rfc8081)

The only outlier  that I'm aware of then is 

* font-tdpfr

Which I don't know if is in mpv already.

The popularily used but unofficial, or deprecated mime types

* application/font-sfnt
* application/x-truetype-font
* application/application/x-font-opentype
* application/vnd.ms-opentype

Don't have to be added probably (should still load and play), but if they're there, warning on use might be an idea.

**Comment by thebombzen** [comment]
See #5229

**Comment by thebombzen** [comment]
Fixed in f3d2f4c6c2a57a03daa824db2eb7a544ce56f81a
