### ISSUE TITLE
opengl-cb: video freezes, audio works

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#4993]
I am making this issue to track down a bug I'm struggling with for more than a month.

### mpv version and platform

```
mpv 0.27.0-236-g6d534138ed (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Oct 14 19:26:58 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.4
```

- `Linux tornado 4.12.10-1-ARCH #1 SMP PREEMPT Wed Aug 30 12:18:42 CEST 2017 x86_64 GNU/Linux`
- Nvidia GTX 970 with proprietary drivers
- bspwm
- `compton --backend glx --vsync opengl --paint-on-overlay`

### Reproduction steps

Very hard to tell. I'm not even sure if it's mpv's problem, might be my program, pympv, Qt, etc.

1. I am writing a PyQT application that uses https://github.com/marcan/pympv to talk with libmpv.
   The code is almost direct translation of mpv-examples to Python:

    Rendering - https://github.com/rr-/bubblesub/blob/master/bubblesub/ui/mpv.py
    Update callback - https://github.com/rr-/bubblesub/blob/master/bubblesub/api/video.py#L132-L155

3. Weird stuff I am doing that might matter:

   - I play parts of video from point A to point B.
     I do that by seeking to point A and setting and `--end` to point B which tricks mpv into thinking it has reached EOF. I prevent mpv from closing the file when it reaches `--end` by setting `--keep-open`.
     I can play many lines with the above kludge before the video gets stuck.
   - I am almost sure the video sometimes froze without any window operations, right before my eyes, so I don't think it's a window manager's fault.

### Expected behavior

Video frames get redrawn.

### Actual behavior

At some random point in time (into 1-60 minutes of working with my program), the video stops updating. It's no longer redrawed on the Qt widget, which keeps displaying the last frame it received. I can minimize the window, then maximize it and that stuck frame is properly rerendered. Changes to properties such as playback position are no longer reported smoothly, instead, they're "chopped" (I believe this is because of https://github.com/mpv-player/mpv/blob/master/video/out/vo_opengl_cb.c#L393). **Audio works**.

I managed to reproduce this situation while running the whole thing in gdb. Demuxer and audio threads are okay, since audio keeps playing, I can normally seek etc. The video thread seems to work correctly too, it executes the update callback in `opengl-cb` and everything. From what I can tell at very least, there's no simple deadlock in the sense that some thread is stuck waiting forever for some mutex.

### Log file

Enabling debug messages seems to make the issue go away (!) or at least greatly decreases chances of reproducing it.

### Sample files

Irrelevant, seems to happen with every video.

**Comment by rr-** [comment]
These functions get called as expected even in such "stuck" state:

`def swapped(self):`
`def maybe_update(self):`

This function gets no longer called:

`def paintGL(self):`

**Comment by nxnev** [comment]
Same issue here. In my experience, it gets fixed when I stop compton but I know that's not a real solution. Related issue: chjj/compton#494

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
