### ISSUE TITLE
Green video output with hwdec=cuda after screenlock

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#4994]
### mpv version and platform

mpv 0.27 on Gentoo Linux

### Reproduction steps

1. Play video file with `--hwdec=cuda`
2. Lock and unlock the screen

### Expected behavior

Video playback should not be affected

### Actual behavior

mpv shows a full green screen and does not recover. Only solution is to restart mpv.
Audio playback continues normally.

### Log file

http://sprunge.us/GYFA 

### Sample files

Not required.

**Comment by philipl** [comment]
Which screen lock? gnome-shell?

I tried that here and it played correctly after locking and unlocking.

On the other hand, suspend/resume with a movie playing or paused leads to a complete mess, as the GPU loses state. cuvid doesn't appear to have any sort of preemption callback so we don't know what's happened and what to do (in the way that the vdpau preemption callback does).

@BtbN Do you have any ideas about handling preemption?

**Comment by BtbN** [comment]
I'm not aware of there being any callbacks like that, no.

**Comment by aufkrawall** [comment]
I don't experience such an issue with Plasma.

**Comment by BtbN** [comment]
It highly depends on how aggressive the screenlock is. If it turns off the GPU it will most likely loose all state and is in need of a decoding-restart.

**Comment by aufkrawall** [comment]
I guess it wouldn't be very smart to disable the NV GPU device for lockscreen/standby because NV GPUs can't turn themselves off (at least not in regular non-mobile PCs).
Proprietary NV driver btw. screws X rendering after standby for me with Plasma. I get corruption and need to restart the shell. Probably a problem with Qt, doesn't happen with open source drivers.

**Comment by Q9II** [comment]
I'm using light-locker with the proprietary drivers.

**Comment by philipl** [comment]
For me, testing with the libplacebo branch, I get a segfault inside the nvidia library doing vkCmdPipelineBarrier() on a vt switch. Basically, without a preemption callback, this can never work properly. It's a strange gap in their API.

**Comment by aufkrawall** [comment]
I remember I was having "stuck/frozen picture" issues with nvdec also when switching Plasma's virtual desktops on Xorg mpv OGL. Never had this with vaapi.

**Comment by Akemi** [comment]
if the issues still persists please open a new issue with all the info we ask for.
