### ISSUE TITLE
Desync A/V, need framedrop on slow system

### ISSUE THREAD

**Issue by skrew** [mpv-player/mpv#4995]
### mpv version and platform
MPV Head, iPad A7, iOS 11

### Reproduction steps
Play an HEVC video on iPad mini 2, which are too slow to handle the codec

### Expected behavior
Drop video frames to maintain A/V sync'ed

### Actual behavior
A/V are desynchronised immediately

### Log file
```
[cplayer] warn: 
[cplayer] warn: Audio/Video desynchronisation detected! Possible reasons include too slow
[cplayer] warn: hardware, temporary CPU spikes, broken drivers, and broken files. Audio
[cplayer] warn: position will not match to the video (see A-V status field).
[cplayer] warn: 
```

Tested with many options, and all values available to options, like:

```
check_error(mpv_set_option_string(mpv, "video-sync", "display-resample"));
check_error(mpv_set_option_string(mpv, "framedrop", "decoder"));
check_error(mpv_set_option_string(mpv, "vd-lavc-skipframe", "all"));
```

Thanks.

**Comment by wm4** [comment]
It does that normally, but at some point video decoding can be slow enough that even heavy frame dropping can't make it keep up with audio.

**Comment by skrew** [comment]
Ok, it does by default, or i have to let my 3 options in place ? (Even if this don't works on this case, this can be useful in some others conditions)

**Comment by ZSwitch** [comment]
@skrew how did you build successfully for iOS?
 I configured it like this:
export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/:$PATH"
export SDKPATH="$(xcodebuild -sdk iphoneos -version Path)"
export CFLAGS="-isysroot $SDKPATH -arch arm64 -mios-version-min=8.0.0 -fembed-bitcode"
export LDFLAGS="-isysroot $SDKPATH -arch arm64 -Wl,-ios_version_min,8.0.0 -lbz2"
 ./waf configure --disable-cplayer --disable-lcms2 --disable-lua --enable-libmpv-static --enable-ios-gl --enable-gl
./waf build

and error occurred...

**Comment by skrew** [comment]
@ZSwitch don't use my ticket for your problem.
Search on issues, i had found there.
If you still have problem, open a new ticket and i will help if needed.

**Comment by lachs0r** [comment]
What wm4 said. And defaults should be fine.
