### ISSUE TITLE
Question - Can mpv feed HDR converted to SDR to x264 encoder

### ISSUE THREAD

**Issue by tyeeman** [mpv-player/mpv#4997]
I playback HDR with mpc just fine while viewing on my SDR monitor. Now I want to feed that video to x264 encoder. I read mpv can encode, I tried it recently with an SDR fed to x264 and it works fine. So I need the command line to do the HDR to SDR to encoder.

Tried this command line, 
```
mpv.com "movie.mkv" --ofps=24000/1001 --ovc=libx264 --ovcopts-add=profile=high,crf=21,preset=slow,tune=film,level=4.1 --oac=aac --oacopts-add=b=256k --hdr-tone-mapping=reinhard --target-prim=bt.709 --target-brightness=120 --o r:\1\encode.mkv
```
but I get the muted colors HDR signal being encoded.

**Comment by haasn** [comment]
No, mpv's HDR->SDR conversion lives entirely in the GPU video output module.

You're probably looking for something like zimg instead?

**Comment by tyeeman** [comment]
Thanks I'll check it out.

**Comment by aluo-x** [comment]
I understand this issue is closed, but it is a feature I am interested in as well. @haasn

**Comment by thebombzen** [comment]
You can already do this using libavfilter. `--vf=lavfi="zscale=transfer=linear,format=gbrpf32le,tonemap=reinhard,zscale=transfer=bt709,format=yuv420p"` or appropriate equivalent should work if the input has its HDR colorspace tagged.

**Comment by tyeeman** [comment]
Just tried it and got this - 
```
Error parsing option zscale (option not found)
Option vf: Error while parsing lavfi parameter zscale (transfer)
Error parsing option vf (option parameter could not be parsed)
Setting commandline option --vf=lavfi=zscale=transfer=linear,format=gbrpf32le,tonemap=reinhard,zscal
e=transfer=bt709,format=yuv420p failed.
```

**Comment by lachs0r** [comment]
FFmpeg needs to be compiled with --enable-libzimg.

**Comment by tyeeman** [comment]
Ah Ha! and your the compiler! I believe I got my windows version from your site.

**Comment by thebombzen** [comment]
Actually the issue here is you didn't quote it. Your quotes were unhelpfully removed by your shell. You need probably actually need to type `--vf=lavfi='"zscale=transfer=linear,format=gbrpf32le,tonemap=reinhard,zscale=transfer=bt709,format=yuv420p"'`

**Comment by tyeeman** [comment]
Just tried it, get this - 
```
Error parsing option vf (option parameter could not be parsed)
Setting commandline option --vf=lavfi='zscale=transfer=linear,zscale=transfer=bt709,format=gbrpf32le
,tonemap=reinhard,format=yuv420p' failed.

Exiting... (Fatal error)

```

**Comment by thebombzen** [comment]
I'm not even sure what to say to someone who cannot copy and paste.

**Comment by winneon** [comment]
@thebombzen You are being very rude for no real reason. On Windows using the default cmd.exe shell, if you copy and paste the single-quoted then double-quoted code block your provided into the shell, the shell will remove the double quotes.

**Comment by thebombzen** [comment]
That doesn't change the fact that they didn't copy and paste.
I wrote: `zscale=transfer=linear,format=gbrpf32le,tonemap=reinhard,zscale=transfer=bt709,format=yuv420p`
The error message contains this, however:
`zscale=transfer=linear,zscale=transfer=bt709,format=gbrpf32le,tonemap=reinhard,format=yuv420p`
The second filter will not work.
