### ISSUE TITLE
Ass subtitle isn't displayed correctly

### ISSUE THREAD

**Issue by xingcoo** [mpv-player/mpv#4998]
### mpv version and platform
- macOS 10.12.6
- mpv 0.27.0
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
The screenshot is from The.Big.Bang.Theory.S11E03 1:13 using subtitle [The.Big.Bang.Theory.S11E03.720p.HDTV.X264-DIMENSION.简体&英文.ass](http://www.zimuzu.tv/subtitle/53724)
### Expected behavior
[https://imgur.com/a/Vf2SC](https://imgur.com/a/Vf2SC)
### Actual behavior
[https://imgur.com/a/r89nI](https://imgur.com/a/r89nI)
### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)

**Comment by wm4** [comment]
Report to libass. Also make sure you actually provide all information that's asked.
