### ISSUE TITLE
Built failed for iOS

### ISSUE THREAD

**Issue by ZSwitch** [mpv-player/mpv#5000]
### mpv version and platform
MPV Head, build for iOS in macOS High Sierra 10.13

### Reproduction steps

At first, I configured some environment like:
export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/:$PATH"
export SDKPATH="$(xcodebuild -sdk iphoneos -version Path)"
export CFLAGS="-isysroot $SDKPATH -arch arm64 -mios-version-min=9.0.0 -fembed-bitcode"
export LDFLAGS="-isysroot $SDKPATH -arch arm64 -Wl,-ios_version_min,9.0.0 -lbz2"

Then, ./waf configure --disable-cplayer --disable-lcms2 --disable-lua --enable-libmpv-static --enable-ios-gl --enable-gl

Finally, ./waf build ,and error occurred.

### Expected behavior
built success and generated static library.
### Actual behavior
building failed
### Log file

Waf: Leaving directory `/Users/admin-5/mpv_git/mpv/build'
Build failed
 -> task in 'mpv' failed with exit status 1: 
	{task 4542008048: c hwdec_ios.m -> hwdec_ios.m.19.o}
['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk', '-arch', 'arm64', '-mios-version-min=8.0.0', '-fembed-bitcode', '-D_ISOC99_SOURCE', '-D_GNU_SOURCE', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64', '-D_LARGEFILE64_SOURCE', '-std=c99', '-Wall', '-O2', '-g', '-Werror=implicit-function-declaration', '-Wno-error=deprecated-declarations', '-Wno-error=unused-function', '-Wempty-body', '-Wdisabled-optimization', '-Wstrict-prototypes', '-Wno-format-zero-length', '-Werror=format-security', '-Wno-redundant-decls', '-Wvla', '-Wno-logical-op-parentheses', '-fcolor-diagnostics', '-Wno-tautological-compare', '-Wno-tautological-constant-out-of-range-compare', '-Wall', '-Wundef', '-Wmissing-prototypes', '-Wshadow', '-Wno-switch', '-Wparentheses', '-Wpointer-arith', '-Wno-pointer-sign', '-Wno-unused-result', '-pthread', '-I.', '-I..', '-I/usr/local/Cellar/ffmpeg/3.3.2/include', '-I/usr/local/Cellar/libass/0.13.7/include', '-I/usr/local/Cellar/harfbuzz/1.4.6_1/include/harfbuzz', '-I/usr/local/Cellar/graphite2/1.3.10/include', '-I/usr/local/include', '-I/usr/local/include/freetype2', '-I/usr/local/Cellar/fribidi/0.19.7_1/include/fribidi', '-I/usr/local/Cellar/glib/2.52.3/include/glib-2.0', '-I/usr/local/Cellar/glib/2.52.3/lib/glib-2.0/include', '-I/usr/local/opt/gettext/include', '-I/usr/local/Cellar/pcre/8.41/include', '-I/usr/local/opt/freetype/include/freetype2', '../video/out/opengl/hwdec_ios.m', '-c', '-o/Users/admin-5/mpv_git/mpv/build/video/out/opengl/hwdec_ios.m.19.o']

![image](https://user-images.githubusercontent.com/16774273/31657065-13be3cd0-b2f3-11e7-89a5-885bfc52eb7a.png)

**Comment by wm4** [comment]
The actual error message seems to be missing.

**Comment by ZSwitch** [comment]
@wm4   oh...forgive my fault.
../video/out/opengl/hwdec_ios.m:76:53: error: use of undeclared identifier 'AV_HWDEVICE_TYPE_VIDEOTOOLBOX'; did you mean 'AV_HWDEVICE_TYPE_VDPAU'?
    av_hwdevice_ctx_create(&p->hwctx.av_device_ref, AV_HWDEVICE_TYPE_VIDEOTOOLBOX,
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                    AV_HWDEVICE_TYPE_VDPAU
/usr/local/Cellar/ffmpeg/3.3.2/include/libavutil/hwcontext.h:28:5: note: 'AV_HWDEVICE_TYPE_VDPAU' declared here
    AV_HWDEVICE_TYPE_VDPAU,
    ^
1 error generated.

**Comment by wm4** [comment]
Seems like you need to build with a newer ffmpeg version (and the mpv configure script lacks a check for this).

**Comment by skrew** [comment]
I confirm, you need the git (head) version of ffmpeg.
If you want to use the current release version of ffmpeg (3.3.4), you need an older version of MPV. (2-3 weeks older, before the old api support have been removed)

**Comment by ZSwitch** [comment]
@skrew thank you!!!
