### ISSUE TITLE
choppy playback with cuda deinterlacing

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#5001]
### mpv version and platform
mpv 0.27.0-253-gc7824f7c9d ffmpeg N-87874-g15b86d3b4a
tested on Linux

### Reproduction steps
Play an interlaced video file with a config like this:
hwdec=cuda
vd-lavc-o=deint=adaptive

### Expected behavior
Deinterlacing shouldn't lead to choppy playback, vdpau deinterlacing works.

### Actual behavior
cuda deinterlacing ruins playback and there are errors like
"Invalid video timestamp: 4.480000 -> 3.480000"

### Log file
https://pastebin.com/x87LLSXh

### Sample files
http://www101.zippyshare.com/v/SNtWXqHm/file.html

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
