### ISSUE TITLE
CLI for retrieving current position

### ISSUE THREAD

**Issue by yakir12** [mpv-player/mpv#5002]
I'm sorry to open an issue for something I suspect I just missed in the docs/issues (I have tried to look for a solution extensively though).
 
If `mpv` is playing some file, how do you query the current position of that file, *while it's playing*, from the terminal? Is there a way to probe that specific process? Or are there CLI options that tell `mpv` to save the position every second to some file (that I can periodically read from)? 

Thanks in advance!

**Comment by garoto** [comment]
https://mpv.io/manual/master/#json-ipc

**Comment by yakir12** [comment]
Brilliant! Thank you..!
