### ISSUE TITLE
Application Not Responding

### ISSUE THREAD

**Issue by 5t3f4n** [mpv-player/mpv#5004]
### mpv version and platform
mpv 0.27.0 (stolendata build)
macOS High Sierra 10.13 (17A405)

### Reproduction steps
Try to open file associated with mpv.app

### Expected behavior
File opens in mpv

### Actual behavior
>You can't open the application "mpv.app" because it is not responding.
<img width="420" alt="mpv" src="https://user-images.githubusercontent.com/11399326/31675182-29f1fdae-b364-11e7-95d2-03250a399b80.png">

It's impossible to quit from either Dock or using the killall command, and it doesn't show in Activty Monitor at all, but it remains in Dock in a non-responsive state.
<img width="220" alt="dock" src="https://user-images.githubusercontent.com/11399326/31675192-32341fce-b364-11e7-9fbb-78892029ef83.png">

It is still possible to run and use mpv normally by running `/Applications/mpv.app/Contents/MacOS/mpv`
No log file because don't know how to get it (if possible) from an already hanged GUI instance launched from Finder. Only solution I've found so far to rid of the unresponsive app from Dock is to log out and back in.

**Comment by Akemi** [comment]
fixed with 77021cf6fe6a1813b832c8927c288e958b6f6845. it's only in master, it will be in the next release.

**Comment by Shafley** [comment]
I have the same problem.
I can't force quit mpv, and it always stay in Dock, can't log out, can't find pid, can't restart Mac
I'm desperate. :sob:

**Comment by Akemi** [comment]
you have to get a build from master, the fix is in no release yet.
