### ISSUE TITLE
Problem with WAV to WAV conversion

### ISSUE THREAD

**Issue by ibrshv** [mpv-player/mpv#5009]
### mpv version and platform
```
mpv 0.27.0-amended (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Sep 14 07:49:49 UTC 2017
ffmpeg library versions:
   libavutil       55.74.100
   libavcodec      57.105.100
   libavformat     57.82.100
   libswscale      4.7.103
   libavfilter     6.105.100
   libswresample   2.8.100
ffmpeg version: git-2017-09-12-6ce4a63
```
### Reproduction steps
```
mpv in.wav -o out.wav
mpv in.wav --of=u8 -o out_u8.wav
mpv in.wav --of=s8 -o out_s8.wav
mpv in.wav --of=u16le -o out_u16le.wav
mpv in.wav --of=s16le -o out_s16le.wav
```
### Expected behavior
I wanted to convert over 100k wav files with '--speed=0.4 --af=scaletempo=stride=10:overlap=0.8'. But I noticed that file size become very large. Testing one of the file shows that mpv increase number of bits, length and bitrate. From 8 bits, 0:00.638 sec., 88 kb/s to 16 bits, 0:01.49 sec., 176 kb/s. Is it possible to get identical out.wav from my in.wav, so then I can just to add my filter settings? 

### Actual behavior
```
 7043 in.wav
32846 out.wav
16384 out_u8.wav
16384 out_s8.wav
32768 out_u16le.wav
32758 out_s16le.wav
```
```
Input #0, wav, from 'in.wav':
  Duration: 00:00:00.63, bitrate: 88 kb/s
    Stream #0:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 11025 Hz, 1 channels, u8, 88 kb/s

Input #0, wav, from 'out.wav':
  Metadata:
    encoder         : Lavf57.82.100
  Duration: 00:00:01.49, bitrate: 176 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 11025 Hz, 1 channels, s16, 176 kb/s

out_u8.wav: Invalid data found when processing input

out_s8.wav: Invalid data found when processing input

out_u16le.wav: Invalid data found when processing input

out_s16le.wav: Invalid data found when processing input
```
### Log file
http://sprunge.us/TTJi default
http://sprunge.us/dELd u8
http://sprunge.us/GjNX s16le

### Sample files
https://0x0.st/CCb.wav

**Comment by wm4** [comment]
`--of` forces the output file format, so it writes raw u8 etc. without a wav header. Force the audio codec instead (-oac I think?), which should work.

**Comment by ibrshv** [comment]
I convert with `mpv in.wav --oac=pcm_u8 -v -o test.wav` and got 8 bit 88 kb/s, but length is incorrect. http://sprunge.us/dYfg
Original:
```
Input #0, wav, from 'in.wav':
  Duration: 00:00:00.63, bitrate: 88 kb/s
    Stream #0:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 11025 Hz, 1 channels, u8, 88 kb/s
```
Result:
```
Input #0, wav, from 'test.wav':
  Metadata:
    encoder         : Lavf57.82.100
  Duration: 00:00:01.49, bitrate: 88 kb/s
    Stream #0:0: Audio: pcm_u8 ([1][0][0][0] / 0x0001), 11025 Hz, 1 channels, u8, 88 kb/s
```

**Comment by kevmitch** [comment]
The length thing is a real bug that I have noticed for a while. The provided file is 6999 samples long. The first 6999 samples of the output are identical, but there are 9385 additional samples of silence added onto the end. `ffmpeg -i in.wav out.wav` conversely results in output identical to the input.

**Comment by wm4** [comment]
Is the displayed time correct during playback?

**Comment by kevmitch** [comment]
The status line stays at `00:00:00 / 00:00:00` for the duration of playback. It's probably no coincidence that the output file is 16384 samples and the log says

```[ao/lavc] device buffer: 16384 samples.```

**Comment by Dudemanguy** [comment]
Was not able to reproduce the length bug with the given steps so I will assume this was fixed.
