### ISSUE TITLE
How to compile in debug mode for Windows

### ISSUE THREAD

**Issue by dohisev** [mpv-player/mpv#5010]
I'm following the tutorial [https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md](https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md) but I can't figure it out how to compile the debug and release versions of `libmpv`.

**Comment by rossy** [comment]
Those instructions should give you a DLL with debug symbols. If you want a release build, try running ``waf configure`` with the ``--disable-debug-build`` flag. You can also strip debug symbols (to make a release build) with the [strip][1] command.

If you're debugging with Visual Studio, this might not be too helpful though. mingw-w64 GCC generates debug info in a different format to Visual C++, so from Visual Studio's perspective, it will look like mpv-1.dll has no debug info. There's no easy solution to this, but you might be able to use [rainers/cv2pdb][2] to generate a .pdb that Visual Studio can understand.

[1]: https://sourceware.org/binutils/docs-2.29/binutils/strip.html
[2]: https://github.com/rainers/cv2pdb

**Comment by dohisev** [comment]
Thank you for your answer, I have no idea why but when I compile from the source and try to compile anything using libmpv it compiles without any problem, but when I run the application it just crashes and exit. It does work however using the compiled versions from [https://mpv.srsfckn.biz/](https://mpv.srsfckn.biz/).
