### ISSUE TITLE
Broken Video picture from .ts file

### ISSUE THREAD

**Issue by osxdoc** [mpv-player/mpv#5014]
### mpv version and platform
macOS: 10.13
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Oct 15 20:26:47 BST 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4

### Reproduction steps
.ts video files from ZDF/ZDFinfo/ZDF_neo from my sat receiver using mpv for playback.

### Actual behavior
Most green broken picture with channels streamed/downloaded from my Sat receiver (VU+ solo 4k).
This only happens with channels from german Television ZDF/ZDFinfo/ZDF_neo (VLC and mpv 0.25 works fine)

### Sample files
https://cl.ly/0u323m1m3X2S/zdfinfo.ts

**Comment by wm4** [comment]
Sample file works for me.

**Comment by osxdoc** [comment]
Ok, now I have deleted my .config/mpv folder and it works now.

**Comment by wm4** [comment]
In that case a log would have been useful (which the issue template actually asks for).

**Comment by osxdoc** [comment]
That was the output log.
https://cl.ly/220D1J0U2x1G/output.txt
