### ISSUE TITLE
Monitor turns off under KDE Plasma Wayland session during video playback

### ISSUE THREAD

**Issue by glaubersm** [mpv-player/mpv#5015]
### mpv version and platform
mpv 1:0.27.0-1, Arch linux

### Reproduction steps
play any video under KDE Plasma Wayland session
wait your system reaches the monitor power management timeout

### Expected behavior
monitor keeps turned on

### Actual behavior
monitor turns off when the power management timeout is reached

**Comment by atomnuker** [comment]
Ask kwin to support the idle-inhibit-unstable-v1 protocol.

**Comment by dyskette** [comment]
Another user here, same thing in GNOME right? And by protocol, you mean this:

https://cgit.freedesktop.org/wayland/wayland-protocols/tree/unstable/idle-inhibit

**Comment by atomnuker** [comment]
Yes

**Comment by glaubersm** [comment]
I'm testing kde plasma 5.12 beta with mpv 0.27 on Arch Linux,
kde plasma 5.12 beta has idle-inhibit-unstable-v1 protocol support
https://bugs.kde.org/show_bug.cgi?id=385956
but the problem described in this report is still happening.
