### ISSUE TITLE
Compilation fails with libva-2.0.0.pre3

### ISSUE THREAD

**Issue by ERYuyNIrbNKrsc** [mpv-player/mpv#5016]
### mpv version and platform

mpv 0.27.0-256-gd9e3bad500 

Kubuntu 17.10 amd64

### Reproduction steps
install libva-2.0.0.pre3 and build

### Log file

http://sprunge.us/eCJj

**Comment by joebonrichie** [comment]
Still a problem with libva 2.0.0 

Culprit commit seems to be [here](https://github.com/01org/libva/commit/cb1f254ec65954ff7585f40df4b38337c462b14c#diff-d6b123c0fc6770f152e98618cccc23f1)

**Comment by wm4** [comment]
Disabled in git master for now.
