### ISSUE TITLE
mpv hangs when the flac audio reaches to the end, or Seeking backward / forward

### ISSUE THREAD

**Issue by ERYuyNIrbNKrsc** [mpv-player/mpv#5017]
### mpv version and platform

mpv 0.27.0-259-g13fb166d87
Kubuntu 17.10 amd64

### Reproduction steps

build mpv with latest ffmpeg https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/858db4b01fa2b55ee55056c033054ca54ac9b0fd

### Expected behavior

playing flac audio

### Actual behavior

hang on the end, and when seeking backward / forward

### Log file

http://sprunge.us/AEHC

### Sample files

any flac files...
https://0x0.st/srAo.flac

**Comment by wm4** [comment]
Works for me.

**Comment by myfreeer** [comment]
Reproduced on windows x64, mpv `0.27.0-262-g044af63d98`, ffmpeg `git-2017-10-21-a5fd8aa4`, not reproduced on windows x64, mpv `0.27.0-262-g044af63d98`, ffmpeg `n3.4`.
Seems an upstream issue.

**Comment by tjackson** [comment]
I can reproduce this on PNGs too.

**Comment by kevmitch** [comment]
dup of #5026 which is fixed
