### ISSUE TITLE
latest mpv cannot play youtube videos with https capable ffmpeg

### ISSUE THREAD

**Issue by TCH68k** [mpv-player/mpv#5020]
I've just build FFMPEG 3.4 with the following config options: --enable-gnutls --enable-libass --enable-opengl

When i tell "ffmpeg -protocols" it enlists https among them.

When i try to view a youtube video with the old mpv 0.8.3 from the Debian repo, it works flawlessly.

But when i try to view it with mpv 0.27.0, then it tells me the following:

root@Csabi:~# /usr/local/bin/mpv https://www.youtube.com/watch?v=s9xl7covihg
Playing: https://www.youtube.com/watch?v=s9xl7covihg
[ffmpeg] https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
Failed to open https://r6---sn-qpbpu8-c0qe.googlevideo.com/videoplayback?ei=lE_qWei-PJXIVv2UsYgN&initcwndbps=1415000&dur=5994.161&expire=1508549621&ipbits=0&mime=audio%2Fwebm&id=o-AEnkb3otvSItDYbxyAwQnAc5MxsjXD_2ABgD1A2rueFZ&pl=24&mm=31&mn=sn-qpbpu8-c0qe&ms=au&mt=1508527955&gir=yes&ip=94.21.161.30&requiressl=yes&mv=m&signature=59908484B7F2AFEECE67B12E43386015D070A9FA.88DA4D5CF3364E439CCFC75EA1DD28D6D8296486&beids=%5B9466592%5D&keepalive=yes&itag=251&key=yt6&lmt=1506545129334888&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&clen=113497509&ratebypass=yes.
Can not open external file https://r6---sn-qpbpu8-c0qe.googlevideo.com/videoplayback?ei=lE_qWei-PJXIVv2UsYgN&initcwndbps=1415000&dur=5994.161&expire=1508549621&ipbits=0&mime=audio%2Fwebm&id=o-AEnkb3otvSItDYbxyAwQnAc5MxsjXD_2ABgD1A2rueFZ&pl=24&mm=31&mn=sn-qpbpu8-c0qe&ms=au&mt=1508527955&gir=yes&ip=94.21.161.30&requiressl=yes&mv=m&signature=59908484B7F2AFEECE67B12E43386015D070A9FA.88DA4D5CF3364E439CCFC75EA1DD28D6D8296486&beids=%5B9466592%5D&keepalive=yes&itag=251&key=yt6&lmt=1506545129334888&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&source=youtube&clen=113497509&ratebypass=yes.
[ffmpeg] https protocol not found, recompile FFmpeg with openssl, gnutls or securetransport enabled.
[ffmpeg] Protocol not found. Make sure ffmpeg/Libav is compiled with networking support.
Failed to open https://r6---sn-qpbpu8-c0qe.googlevideo.com/videoplayback?ei=lE_qWei-PJXIVv2UsYgN&initcwndbps=1415000&dur=5994.133&expire=1508549621&ipbits=0&mime=video%2Fwebm&id=o-AEnkb3otvSItDYbxyAwQnAc5MxsjXD_2ABgD1A2rueFZ&pl=24&mm=31&mn=sn-qpbpu8-c0qe&ms=au&mt=1508527955&gir=yes&ip=94.21.161.30&requiressl=yes&mv=m&signature=692E520C903CEFFD24F7D7D008932561C0A5C36F.5EEA14DDFBB1FBB2DEFDDA06FF96AB98C0CCFEBA&beids=%5B9466592%5D&keepalive=yes&itag=247&key=yt6&lmt=1506559335447126&sparams=aitags%2Cclen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&clen=897802115&ratebypass=yes.

Exiting... (Errors when loading file)

**Comment by kevmitch** [comment]
Are you sure that mpv was compiled against the gnutls enabed ffmpeg? I'd recommend using [mpv-build](https://github.com/mpv-player/mpv-build) to be sure.

**Comment by TCH68k** [comment]
It was. However, since then, this somehow solved itself. I did not change anything, but now opening the mentioned YT link with mpv is working.
