### ISSUE TITLE
Error on loading vapoursynth filter

### ISSUE THREAD

**Issue by pulgalipe** [mpv-player/mpv#5023]
macOS: 10.12.6
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Oct 22 01:38:38 -02 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100

Error log: https://hastebin.com/bulecavice.md

mpv compiled with brew using the command: 

`brew install mpv --with-bundle --with-libaacs --with-libarchive --with-libbluray --with-libdvdnav --with-libdvdread --with-uchardet --with-vapoursynth `

I just open an movie on mpv with this line on my config file:

`vf=vapoursynth=/Users/pulgalipe/.config/mpv/vapoursynth/f3kdb.vpy`

f3kdb is already compiled/installed using the `waf` commands from  their own repo.

`f3kdb.vpy` script content:

```python
import vapoursynth as vs
core = vs.get_core()
clip = video_in
clip = core.std.Trim(clip, first=0, length=500000)
clip = core.f3kdb.Deband(clip, output_depth=16, dynamic_grain=True, grainy=16, grainc=16)
clip.set_output()
```

**Comment by Argon-** [comment]
Installing f3kdb is not enough, you have to make it available to vaporsynth (there's an autoload directory) or explicitly load it in the script (from a path). 

Btw f3kdb should be in homebrew
