### ISSUE TITLE
OSC support for vo_rpi using SDL input

### ISSUE THREAD

**Issue by ksharindam** [mpv-player/mpv#5025]
So many thanks to mpv developers for supporting raspberry pi video output.  
vo_rpi solved huge problems playing videos on raspberry pi.  
But the only problem is, it does not support OSC because OMX IL can not be integrated with x11 and mouse input can not be received.  
I think this problem can be solved by creating a (fullscreen) SDL window only to get mouse input, then create the video overlay (vo_rpi) to display the video. Then show the OSC according to the mouse movement.  
Many games use this method on raspberry pi.  

If it is possible, please add this feature.

**Comment by wm4** [comment]
It's probably more likely that someone would add low level mouse input (which could also be used by vo_drm), but generally just unlikely.

**Comment by ksharindam** [comment]
Ok, low level input (like ncurses).would be better.

**Comment by Dudemanguy** [comment]
Old one, but I think the OSC should work on vo_rpi. The code looks like it supports it at least. Feel free to reopen if this is not the case.
