### ISSUE TITLE
Question: How to go forward or backward, album-wise?

### ISSUE THREAD

**Issue by stefanos82** [mpv-player/mpv#5028]
```bash
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.4-2
```

I know that with `>` and `<` can go backward and forward respectively in a playlist.

How to do the same for albums? I have a huge playlist that consists of 10 albums and I would like to skip certain albums with some key.

Is there something in official documentation that already does this and I cannot see it?

Cheers.

**Comment by wiiaboo** [comment]
Nope, mpv isn't a music player. Unless you're using single-file albums with cue/chapters there's no logical way to split albums.

**Comment by stefanos82** [comment]
That's too bad :disappointed: I use it as my media player of choice and I would love to have such option.

**Comment by Hrxn** [comment]
AFAIK, [mpc-qt](https://github.com/cmdrkotori/mpc-qt) supports out-of-order playback/queuing, maybe see if that fits your desired use case, or look how it's done there, don't know, maybe it helps.

**Comment by stefanos82** [comment]
@Hrxn I could use smplayer as my front-end and mpv as my back-end, but that's not what I want to accomplish.

Anyway, I thought to ask to see whether I missed a hot-key somewhere inside the official docs.

Cheers.

**Comment by haasn** [comment]
You could probably use horrible hacks like concatenating each directory into a single virtual timeline; but either way it's going to be an ugly mess
