### ISSUE TITLE
Unhide cursor when switching Spaces on OSX

### ISSUE THREAD

**Issue by rcombs** [mpv-player/mpv#503]
Not sure how one would go about detecting that, but it'd be convenient to unhide the cursor if the user switches workspaces.

**Comment by rcombs** [comment]
https://gist.github.com/23b8961385de9bcca76a here have a patch

**Comment by wm4** [comment]
@pigoz: opinion?

It looks like the right way to do it to me.

**Comment by rcombs** [comment]
I stole the method from WebKit, and I'd imagine those guys know what they're doing.

**Comment by pigoz** [comment]
@rcombs nice. If that works we should merge that. Can you autorelease the blankImage and remove it from the vo_cocoa_state struct?

**Comment by rcombs** [comment]
Released manually; an autorelease pool seemed like overkill (but I don't know that much about Obj-C): https://gist.github.com/03395b1cb8c3f0717873

**Comment by pigoz** [comment]
LGTM can you open a PR or send me a patch (with `git format-patch`)?
