### ISSUE TITLE
Manual resume of last playback position

### ISSUE THREAD

**Issue by sayuru** [mpv-player/mpv#5034]
Requesting an option to always play files from the beginning with the ability to manually resume last playback position (preferably with a keyboard shortcut).

**Comment by Dudemanguy** [comment]
This isn't really simple or pretty but it could be done with a script. You could launch the file with the `--no-resume-playback` option. That option prevents the watch_later file from being used and deleted. Then, you could hash the file name and compare it with the name of the watch-later data (I think mpv uses md5 if I remember right). You could also use the `write-filename-in-watch-later-config` option to make finding it easier. Anyways, then the file could be parsed for the value of start (it's always just `start=<value>`) and finally you could write whatever that value is to `time-pos` to resume the playback position. Bind that script to a keybind and it would be a "manual" resume. You can cleanup/delete the `watch_later` at the same time if you need to.

Anyways as far as adding this feature to mpv itself, it's not really feasible with the way the `watch_later` stuff works. Basically, they are just mini config files that mpv reads on startup and then applies them as options just like your normal config file. Trying to add some conditional ignoring to specifically `start` in only `watch_later` files while storing whatever that `start` value is plus adding some keybind to do a seek for would be much, much uglier than the script I described above. It would also be far too complicated for a rather niche feature. I think the script is your best bet here.
