### ISSUE TITLE
Streaming mp3s fail

### ISSUE THREAD

**Issue by J-Reis** [mpv-player/mpv#5035]
### mpv version and platform
Debian Stable (9.2)
mpv installed from repo
```
mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.8-1~deb9u1
```
### Reproduction steps
Initiate play of steaming mp3 via m3u file, wait 1-10min for audio to stop playing.
### Expected behavior
As far as I know, mpv should be able to play this kind of stream without interruption under normal network conditions.
### Actual behavior
Audio stops after a variable period of time. log shows "Cache is not responding - slow/stuck network connection?". Network in use is a fairly standard home setup and performs normally for other tasks. In this particular case, [the web player](http://news.stlpublicradio.org/#stream/0) for the same stream works fine.
### Log file

http://sprunge.us/AHUh

### Sample files
[kwmu.m3u](http://kwmu-sc.streamguys.com/kwmu1.m3u) available from http://www.kwmu.org/listen.php

[wpr-ideas-mp3-64.m3u](https://wpr-ice.streamguys1.com/wpr-ideas-mp3-64.m3u) available from https://www.wpr.org/listen-live

**Comment by CounterPillow** [comment]
Works just fine here, been listening to http://kwmu-sc.streamguys.com/kwmu1.m3u for over 10 minutes now.
```
$ mpv --version
mpv 0.27.0-270-g0358cca39e (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon Oct 23 11:32:08 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.4
```

Update your mpv and ffmpeg, your mpv version is almost a year old.

**Comment by J-Reis** [comment]
Fair enough, I'm new to "participating" by reporting bugs. I suppose I should take this up with the Debian maintainers since this is the version packaged for Stable.

Thanks for the following up!
