### ISSUE TITLE
mms:// weirdness (cannot play and/or dump the stream)

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#5038]
### mpv version and platform
mpv 0.27.0-74-g791b9c4024 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Sep 28 16:32:28 CEST 2017
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.4

### Reproduction steps
``` mpv mms://192.132.34.181/streamUnina```
### Expected behavior
To play the stream.

### Actual behavior
```koko@Gozer# mpv mms://192.132.34.181/streamUnina 
Playing: mms://192.132.34.181/streamUnina
[ffmpeg] http: HTTP error 404 Not Found
Failed to open mms://192.132.34.181/streamUnina.
```
The following works instead:
```mpv rtsp://192.132.34.181/streamUnina```
But the stream should be mms (this is what the "source" website says).

Indeed, mplayer and vlc work:
```mplayer mms://192.132.34.181/streamUnina
[..]
Connecting to server 192.132.34.181[192.132.34.181]: 1755...
Connected
[..]
```

...Other than that, mpv is unable to dump the stream via rtsp, and, via rtsp, even mplayer fails to dump.

```
koko@Gozer# mpv rtsp://192.132.34.181/streamUnina --stream-dump=/tmp/stream.dump 
Playing: rtsp://192.132.34.181/streamUnina
Exiting... (End of file)
```

### Log file
Failed to play via mms:
http://sprunge.us/UhTU
Failed to dump stream via rtsp (mpv rtsp://192.132.34.181/streamUnina --stream-dump=/tmp/stream.dump -v):
http://sprunge.us/NdNB

**Comment by wm4** [comment]
Find out how it works and I can implement it.

**Comment by kokoko3k** [comment]
I'm not sure i understood correctly.
If you you are referring to the mms protocol per se, the documentation is here:
https://msdn.microsoft.com/en-us/library/cc234711.aspx

But i really don't care to play mms, if rtsp works (this is the case), i'd like to dump the stream via mpv instead (be it rtsp or mms).

**Comment by wm4** [comment]
I care about any of this even less than you.

**Comment by mc4man** [comment]
isn't this the same mms nonsense from way back, i.e., for mpv you specify the transport layer & or in this case mms = rtsp
https://github.com/mpv-player/mpv/issues/1776
In other words no real bug here..

**Comment by Dudemanguy** [comment]
Looking at this briefly, the solution seems to be to use `rtsp` instead especially since Microsoft deprecated this ages ago.
