### ISSUE TITLE
vp9 10bit hardware decoding doesn't work with GT 1030

### ISSUE THREAD

**Issue by sdsucks** [mpv-player/mpv#5044]
### mpv version and platform
mpv 0.27.0/win10x64/nvidia driver version 388.00

### Expected behavior
smooth hardware decoding

### Actual behavior
software decoder is used

### Log file
https://pastebin.com/EqM8ZWBb

### Sample files
https://www.youtube.com/watch?v=tO01J-M3g0U
youtube-dl.exe -f 337

vp9 8bit hardware decoding has no problem

**Comment by aufkrawall** [comment]
Thx for reporting this with a logfile. I briefly had access to a 1030 and reported this too, but hadn't had time to create a log.
Does it also still occur with a recent git build?
https://sourceforge.net/projects/mpv-player-windows/files/

**Comment by sdsucks** [comment]
Yes, I am using lastest verion on sf.net.

**Comment by wm4** [comment]
FFmpeg has no support for vp9 10 bit on DXVA2/D3D11VA.

**Comment by sdsucks** [comment]
Does it mean there's nothing mpv devs can do about this?

**Comment by aufkrawall** [comment]
At least LAV Filters do support it.

**Comment by wm4** [comment]
Then go away and use LAV filters?

**Comment by garoto** [comment]
Don't Nevcairiel have his own ffmpeg tree with custom patches?

**Comment by shinchiro** [comment]
> Don't Nevcairiel have his own ffmpeg tree with custom patches?

Probably this one
https://git.1f0.de/gitweb?p=ffmpeg.git;a=commit;h=43717fb1d1f58c43054845b7625161430cb4809e;js=1

**Comment by aufkrawall** [comment]
Nevcairiel has submitted his patches upstream, this can be closed.
