### ISSUE TITLE
--fs-screen=all does not use both screens

### ISSUE THREAD

**Issue by darkbasic** [mpv-player/mpv#5046]
### mpv version and platform

```
$ mpv --version
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Oct 20 21:00:00 CEST 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4
```

Arch Linux with Plasma 5.11 and X11

### Reproduction steps

mpv <file> --fs-screen=all --fs

### Expected behavior

Full screen mode uses both screens.

### Actual behavior

Just the current screen is used.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/1421663/mpv.log)

**Comment by Akemi** [comment]
if this can still be reproduced please open a new issue.
