### ISSUE TITLE
Vulkan-rev2 often crashes on startup (while it sometimes works)

### ISSUE THREAD

**Issue by Artoriuz** [mpv-player/mpv#5049]
I'm not entirely sure I should be posting this here since vulkan-rev2 isn't even merged, but I suppose it's more visible here. 

### mpv version and platform

[Latest available build with vulkan-rev2 and ra_d3d11 from shinchiro's sourceforge (20171028-git-3413fe4-rebase-branch-vulkan-rev2+ra-d3d)](https://sourceforge.net/projects/mpv-player-windows/files/experimental/mpv-x86_64-20171028-git-3413fe4-rebase-branch-vulkan-rev2%2Bra-d3d.7z/download)
Windows 10 x64 16299.19 (1709)
Graphics card is an AMD RX470 (Polaris 10) 

### Reproduction steps

Opening any random file with --gpu-api=vulkan will sometimes work perfectly and sometimes just crash on startup. I don't really know what causes the issue or how to always make it crash, it really seems to be absolutely random. 

### Expected behavior

Like in vulkan-rev1, very early builds of vulkan-rev2, or any other ra, it should always work. Since it works perfectly fine on rev1 and used to work perfectly fine on rev2 too months ago (pardon me, but I don't know in which build it started to crash), it was reasonable to suppose that it isn't an issue that is caused by a bug in the driver, but I can't confirm whether it works or not across different operating systems and different vendors.  

### Actual behavior

mpv randomly crashes sometimes, randomly works sometimes. 

### Log file

https://pastebin.com/avihCjq7

### Sample files

Well, since it apparently happens with any file, including a sample file would be pointless in my point of view, I made a quick 30s video to demonstrate that without changing anything, just trying it over and over will make mpv eventually work even if it was previously crashing. (Or make it crash even it if was previously working). 

https://youtu.be/98PbWYIIH7U

**Comment by shinchiro** [comment]
Crash report will be meaningful with stack trace. Grab [debug symbols](https://sourceforge.net/projects/mpv-player-windows/files/experimental/debug/). Read how to setup the debugger there

**Comment by Artoriuz** [comment]
Not sure if I did this correctly
https://pastebin.com/wiyt78fB

**Comment by haasn** [comment]
Thanks, that stack trace helped fix the issue. It's a miracle it ever worked at all.

**Comment by Artoriuz** [comment]
I don't think I'll find myself time to setup a build environment, so I'll most likely only report back whenever there's a new build built by shinchiro.

**Comment by shinchiro** [comment]
Well, I just compiled a new build with recent changes of both branches. You can test it

**Comment by Artoriuz** [comment]
Yeah I should've checked before writing that, checked just now and it seems to be working perfectly. No crashes anymore. Thanks a lot =)

**Comment by haasn** [comment]
Does it work with --async-compute now as well? (And if so, does that improve performance?)

**Comment by Artoriuz** [comment]
@haasn Running with --vulkan-async-compute seems to work, or at least mpv doesn't throw any obvious errors at me. Performance is the same though. 
Since I don't really know whether it's working (and not giving a performance boost) or just not working at all, a log:
https://pastebin.com/WNk6Dd1m

**Comment by haasn** [comment]
@Artoriuz try also adding `--vulkan-queue-count=3`. That + async compute does some interesting things on this type of hardware.

**Comment by Artoriuz** [comment]
Well, it still doesn't seem to make any meaningful difference. But I think I can say the framerates are more stable (higher minimums and lower maximums) with --vulkan-async-compute and --vulkan-queue-count=3.
