### ISSUE TITLE
[question] new lua events to help with subtitle  plugins

### ISSUE THREAD

**Issue by teto** [mpv-player/mpv#5051]
I am learning a new language and I thought I could hack around subtitles to highlight unusual words/stop playing on hard ones/translate only hard ones etc. There are tools to duplicate a track into another language so that any player can display 2 languages at the same time so that's not a problem.
My idea was to tap into mpv events through lua: 
https://github.com/mpv-player/mpv/blob/master/DOCS/man/lua.rst
and have the lua plugin communicate with some external process to analyze the sentence.

Would adding "new_sentence" / "new_subtitle" events be ok upstream ?
Out of curiosity, would it be easy to rewrite the subtitle on the fly ?

**Comment by avih** [comment]
Not sure why this wasn't answered till now, but one could observe the `sub-text` property to get notified whenever the subtitle changes (including starting and ending).
