### ISSUE TITLE
--enable-ffmpeg-upstream fails to compile with upstream ffmpeg git master

### ISSUE THREAD

**Issue by dbermond** [mpv-player/mpv#5066]
mpv git master fails to compile with the brandly new option --enable-ffmpeg-upstream:
```
Checking for FFmpeg/Libav present                                    : yes 
Checking for libav* is FFmpeg mpv modified version                   : no 
Checking for libav* is upstream FFmpeg (unsupported)                 : yes 
Checking for libav* is Libav                                         : no 
Checking for Libav/FFmpeg library versions                           : no ('libavutil >= 56.0.100 libavcodec >= 58.2.100 libavformat >= 58.0.102 libswscale >= 5.0.101 libavfilter >= 7.0.101 libswresample >= 3.0.100' not found) 
Unable to find development files for some of the required FFmpeg/Libav libraries. You need git master. For FFmpeg, the mpv fork, that might contain additional fixes and features is required. It is available on https://github.com/mpv-player/ffmpeg-mpv Aborting.
```

`config.log`:
```
--------------------------------------------------------------------
Checking for Libav/FFmpeg library versions
['/usr/bin/pkg-config', 'libavutil >= 56.0.100', 'libavcodec >= 58.2.100', 'libavformat >= 58.0.102', 'libswscale >= 5.0.101', 'libavfilter >= 7.0.101', 'libswresample >= 3.0.100', '--libs', '--cflags', 'libavutil', 'libavcodec', 'libavformat', 'libswscale', 'libavfilter', 'libswresample']
err: Requested 'libavcodec >= 58.2.100' but version of libavcodec is 58.1.100

from /storage/linux/abs/mpv-full-git/src/mpv-full-git: The configuration failed
no ('libavutil >= 56.0.100 libavcodec >= 58.2.100 libavformat >= 58.0.102 libswscale >= 5.0.101 libavfilter >= 7.0.101 libswresample >= 3.0.100' not found)
```

It seems the minimum required versions needs to be lowered in order to allow compilation with upstream ffmpeg.

For example: currently, upstream ffmpeg git master libavcodec is at 58.1.100, but the minimum required version at [wscript](https://github.com/mpv-player/mpv/blob/a7a1ae0b3d60cdaab0774fcb08de33fa6b12848b/wscript#L429-L434) is 58.2.100. This 58.2.100 minimum requirement matches only ffmpeg-mpv.

Using mpv git master and ffmpeg (upstream) git master.

**Comment by CounterPillow** [comment]
That's because upstream ffmpeg is lacking some hwaccel API changes that wm4 submitted patches for. It should work again once ffmpeg merges them.

**Comment by orbea** [comment]
Are those the patches that were rejected for being an "ugly hack"?

http://ffmpeg.org/pipermail/ffmpeg-devel/2017-October/217312.html

**Comment by CounterPillow** [comment]
@orbea I thought you were going to use mplayer instead. Shoo

**Comment by orbea** [comment]
I don't recall making that claim, but if I did I obviously was either not clear enough or wrong. I am stuck in a place where I have to use both MPlayer and mpv because neither works well enough to be used solely. Mpv this is more of a deliberate choice while MPlayer I suspect its mostly legacy. However MPlayer doesn't repeatedly go out of its way to break my use cases so I may be forced to use that only in the future...

Its also still a valid question. Are we waiting for the patches to be merged or are they still rejected for being "Dirty hacks"?

**Comment by CounterPillow** [comment]
>Its also still a valid question. Are we waiting for the patches to be merged or are they still rejected for being "Dirty hacks"?

They're not "rejected", they're rejected in the form they took there based on michaelni's veto. That being said, they've been rewritten already, and have been submitted again, with slightly different semantics.

I recommend following ffmpeg-devel for ffmpeg news, instead of bugging the mpv issue tracker passive-aggressively.

**Comment by orbea** [comment]
Can someone link the specific ffmpeg mailing list posts concerning this? I have had difficulty finding them. It does seem mpv will now build against the lastest ffmpeg-snapshots. Is this something that will last or will it continue to be a game of cat and mouse? Can distros expect to be able to support mpv with stable ffmpeg releases without patching mpv?

Also, there was nothing passive about it. It was a clear and upfront criticism about incompatible changes being forced on users for no reason other than a single developer's personal spite.

**Comment by richardpl** [comment]
Just switch to ffmpv.

**Comment by garoto** [comment]
Don't bother, orbea has some sort of agenda with mpv's ffmpeg fork.

**Comment by avih** [comment]
It's a valid concern. No need to be toxic about it.
