### ISSUE TITLE
feature request: add loop and random button in ui

### ISSUE THREAD

**Issue by dikasetyaprayogi** [mpv-player/mpv#5067]
### mpv version and platform
1:0.27.0-2 arch linux

### Expected behavior
in future releases it would be very nice to have loop and random play button toggle in mpv. a nice loop button suggestion would be like 3 mode cycle in every toggle including: no loop, loop current and loop all

### Reason and Logic
this feature is generally intended for use in playing music videos where user are generaly like to loop it, play a collection of music videos, or make play at random order. also an user who prefer playing audio files with mpv where this loop/random thing is a common use would be very beneficted

### Sample files
example mockups:
![screenshot from 2017-11-02 16-56-57](https://user-images.githubusercontent.com/33314785/32321514-f318e2b0-bff3-11e7-94f6-53477c0b737e.png)

thank you very much for your attention and sorry if my english bad :)

**Comment by haasn** [comment]
You can easily add keybindings for this. I don't see a need to clutter up the already way-too-cluttered OSC with this obscure feature.

**Comment by Sojens** [comment]
i don't like that this got removed as "this would make it cluttered". i love mpv, great video player, but this feature being absent is annoying, as it is something i regularly need to use. there is even free space for it. why can't it be added as an option you enable in config, or something?
