### ISSUE TITLE
feature request: asign a loop key in middle mouse button

### ISSUE THREAD

**Issue by dikasetyaprayogi** [mpv-player/mpv#5068]
### mpv version and platform
1:0.27.0-2 arch linux

### common cause
im really like mpv concept of putting play/pause control in right mouse click by default, its really convinient and helpful for quick play/pause. but i see the middle mouse it just had no key asigned by default so it would it be nice to make this button also have a useful fuction than  blank.
i see mpv have a loop control but must asigned first in mpv config, would it be more convinient if this useful feature asigned by default?

### Expected behavior
in future release it would be nice to assign a loop control by default in middle mouse click

thank you for your attention and sorry if my engliz is bad :)

**Comment by haasn** [comment]
Seems weird and unnecessary. mpv already has a default loop keybinding (ctrl+l); not sure why duplicating this to the middle mouse button would be beneficial or required?

Plus, middle mouse = loop doesn't strike me as particularly common or logical. If anything, I'd expect middle click to quit. (Compare e.g. middle click in browsers and other tabbed GUIs)
