### ISSUE TITLE
mpv blue screen, on latest build, with ITU-R Recommendation BT.2020

### ISSUE THREAD

**Issue by 99issues** [mpv-player/mpv#5069]
### mpv version and platform
mpv 0.27.0-328-g4617a53496-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Tue Oct 31 15:54:07 UTC 2017
ffmpeg library versions:
   libavutil       56.0.100
   libavcodec      58.2.100
   libavformat     58.0.102
   libswscale      5.0.101
   libavfilter     7.0.101
   libswresample   3.0.100
ffmpeg version: N-88322-g1ab3b7f64a-1

### Reproduction steps
mpv -vo gpu --ytdl-format='bestvideo+bestaudio/best' https://www.youtube.com/watch?v=hsbM2c6-9Wg

### Expected behavior
Video, audio, and OSD

### Actual behavior
Blue screen, no OSD, audio only

### Log file
http://sprunge.us/UWUR

video card: intel
video driver: xserver-xorg-video-intel
OS: debian sid (unstable)

**Comment by wm4** [comment]
Log missing. (Can anyone write a bot for his?)

**Comment by 99issues** [comment]
Log URL added.

**Comment by haasn** [comment]
> OpenGL 2.1

Jesus that's old. Anyway, this could probably be fixed by changing it to “if (sig > j) { sig *= ... }”.

**Comment by 99issues** [comment]
Thank you for looking into this. Is there any way to fallback to a different video output driver or possible renderer option(s) whenever viewing a video using this color space?

My knowledge regarding this issue is limited but, willing to learn. Besides learning GLSL, what else should be learned to be able to support legacy systems using OpenGL 2.1 / GLSL 120 for this situation?

**Comment by haasn** [comment]
Well, one thing you could do is force the target primaries/trc to be the same as the file by using `--target-prim=bt.2020 --target-trc=pq`. That should make it look identical to what it would look like if this function did not exist to begin with. But it will not look very good.

Actually, in this case there's an easier work-around: If you use a different tone mapping function (e.g. `--tone-mapping=hable`), it should work even on GLSL 120.

**Comment by 99issues** [comment]
Forcing the target primaries and trc did not work, same blue screen:
```
[vo/gpu] Disabling scaler #3 mitchell (GLSL version too old).
[vo/gpu] Disabling color management (GLSL version too old).
```

Using `--tone-mapping=hable` was able to display. Thank you for work-around!
