### ISSUE TITLE
Input.conf broken?

### ISSUE THREAD

**Issue by pribibinakk** [mpv-player/mpv#5072]
mpv version  0.27.0  OSX Mavericks 10.9.5

Hello, i have a strange behaviour. Just edited input.conf (I'm completely new to MPV) and set my arrow keys (UP,DOWN) for "add volume 2" and "add volume -2", it works as expected but only for a while... after i was not able to set up anything, it seems mpv somehow ignore input.conf? Even if i delete input.conf (to reset bindings to hardcoded mpv presets) my UP,DOWN keys doesn't do huge seeking steps as before. They do nothing, if i create new input.conf and try  to set up anything ( example ESC quit) it ignores everything and i`m not able to set up anything and my arrow keys still doesn't do any function even if input.conf file is not present.

Is there any way to reset mpv to defaults or make input.conf properly working?

**Comment by Akemi** [comment]
pls don't ignore the issue template. a log would be helpful.

**Comment by pribibinakk** [comment]
Ok, sorry for that nooby question i would attach the log file, but where can I get it? From Console or via Terminal? Not experienced in this, for me to remap keybindings is enough... :-) So if you explain me how i create log file for you, it helps me too much. Than you

**Comment by Akemi** [comment]
it was described in the issue template you ignored. either start mpv via terminal and `-v` or with `--log-file=output.txt` that saves a log to specified location.

**Comment by kevmitch** [comment]
This is likely mpv not reading the `input.conf` the OP though it was. We'd really need a log to say for sure, but OP is MIA for over a month. Reopen if a log is provided.
