### ISSUE TITLE
Adjust subtitle timing separately for secondary and primary tracks

### ISSUE THREAD

**Issue by ddevault** [mpv-player/mpv#5074]

**Comment by timofonic** [comment]
@SirCmpwn Would you please like to elaborate on it a bit more? I'm curious to understand what you mean about exactly :)

**Comment by SirCmpwn** [comment]
If you speficy a secondary subtitle track (with --secondary-sid), you can play two subtitle tracks at once. I would like to adjust the subtitle delay for each track separately.

**Comment by CounterPillow** [comment]
Duplicate of #2629
