### ISSUE TITLE
Configure mpv to save videos streamed with yt-dl hook script

### ISSUE THREAD

**Issue by Mark-Weston** [mpv-player/mpv#5075]
Hello, I would like to store the videos I watch from youtube to `~/Videos/`. How would I go about doing it with mpv?
It would be perfect if mpv could start a daemon that would continue downloading the video even after the mpv itself has closed. Is that possible?

**Comment by ChrisK2** [comment]
This is not easily possible through configuration. The easiest thing would be adding a hook script (similar to the ytdl_hook.lua script) to download the video separately with youtube-dl. But this would mean the video would be downloaded twice, once from mpv to play it and once from youtube-dl to download it.

**Comment by garoto** [comment]
With the [Unix equivalent](https://mpv.io/manual/master/#json-ipc) of this line as part of a shell script to generate a unique filename perhaps?

`echo {"command": ["set_property", "record-file", "youtube-$DATE-$TIME.mkv"]}>\\.\pipe\mpv-socket`

Then invoke the script with a keybind set to [run](https://mpv.io/manual/master/#command-interface-run-%22command%22-%22arg1%22-%22arg2%22-) the shell script from `input.conf`.

Or alternatively like ChrisK2 mention, download the file again with `youtube-dl` directly via keybind in `input.conf`:

`CTRL+D		run "cmd.exe" "/s" "/d" "/c" "chdir /d I:\\ && youtube-dl ${path}"`

**Comment by Mark-Weston** [comment]
Thanks for your suggestions, but I found that this little convenience was not worth the hassle (for me, personally) and I ended up just using youtube-dl and mpv separately, for their own purposes (downloading and streaming).
