### ISSUE TITLE
Scaling subtitles causes video to stutter

### ISSUE THREAD

**Issue by 0x24D** [mpv-player/mpv#5077]
### mpv version and platform
OS: Debian testing
MPV: 0.27.0

### Reproduction steps
1. Set sub-scale option in mpv.conf e.g. subscale=75
2. Select video to play in mpv via file manager
3. Drag and drop .srt file into mpv
4. Play video where subtitles should be displayed

### Expected behavior
Video plays fine and subtitles are displayed with specified scaling.
The video works correctly with the --no-config option so it has to do with the sub-scale option, I have nothing else in my mpv.conf
I used to have my subtitles scaled and the videos played fine, but I cannot remember if the sub-scale option was used at that time or if it was another subtitle scaling option.

### Actual behavior
Video starts stuttering whenever subtitles are to be displayed, the subtitles are also not displayed.

### Log file
http://sprunge.us/LQiV

**Comment by 0x24D** [comment]
Setting the subtitle size using sub-font-size instead of setting the scaling allows the video/subtitles to act as expected.

**Comment by lachs0r** [comment]
Well, scaling the subtitles by a factor of 75 is going to make playback slow. If you wanted 75%, you should use --sub-scale=0.75.
