### ISSUE TITLE
Replaygain inconsistent normalization

### ISSUE THREAD

**Issue by hdante** [mpv-player/mpv#5078]
### mpv version and platform
mpv 0.27.0-2
Arch Linux amd64

### Reproduction steps
    $ bs1770gain --apply 1 source.opus -o normalized
    $ bs1770gain --track-tags source.opus -o r128
    $ bs1770gain --track-tags --replaygain source.opus -o replaygain
    $ mpv --replaygain=track normalized/source.flac  # ok
    $ mpv --replaygain=track r128/source.opus # ok
    $ mpv --replaygain=track replaygain/source.opus # wrong, too loud

### Expected behavior
Replaygain working uniformly with all modes. (but warning, bs1770gain tags might be non standard)

### Actual behavior

File replaygain/source.opus too loud.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/1443606/log.txt)

### Sample files
Reference audio comes from:
https://www.youtube.com/watch?v=Hy8kmNEo1i8

**Comment by Dudemanguy** [comment]
Oh this one just seems like it's because r128 wasn't supported at the time. It now exists since #10117, so I'll close it as solved.
