### ISSUE TITLE
Missing support for R128_TRACK_GAIN

### ISSUE THREAD

**Issue by hdante** [mpv-player/mpv#5079]
### mpv version and platform
mpv 0.7.0-2
arch linux amd64

### Reproduction steps
    $ opustags -s 'R128_TRACK_GAIN=-5000' source.opus -o low.opus
    $ mpv source.opus 
    $ mpv --replaygain=track low.opus  # wrong, same volume as source.opus

### Expected behavior
low.opus should have been played at a lower volume

### Actual behavior
source.opus and low.opus have the same volume

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/1443657/log.txt)

### Sample files
Reference audio: https://www.youtube.com/watch?v=Hy8kmNEo1i8

**Comment by rsmaior** [comment]
Are you sure you are under mpv 0.7.0-2? It was released in the end of 2014...

Anyway, I'm with mpv 0.27.0 and have the same results as you (Antergos Linux amd64).

**Comment by garoto** [comment]
Log says 0.27.0, so a typo I presume.

**Comment by Jochem-W** [comment]
This still seems to be an issue in the latest version of mpv, 0.32.0.
I've encoded the same song to both FLAC and opus and according to metaflac and opusinfo, both of my songs have gain tags, but when playing them both using mpv with replaygain set to album, the gain only gets applied for the flac file.

[metaflac.log](https://github.com/mpv-player/mpv/files/4858567/metaflac.log)
[opusinfo.log](https://github.com/mpv-player/mpv/files/4858570/opusinfo.log)
[mpv-flac.log](https://github.com/mpv-player/mpv/files/4858568/mpv-flac.log)
[mpv-opus.log](https://github.com/mpv-player/mpv/files/4858569/mpv-opus.log)

**Comment by saltzify** [comment]
A friend of mine doesn't have a Github account, but says that this patch should fix the issue so I'm posting it here for review.

https://dpaste.com/88KJV2X9A

**Comment by hdante** [comment]
I don't believe the track gain and the album gains are interdependent, so the conditions shouldn't be nested.

**Comment by Dudemanguy** [comment]
Fixed by #5079.

**Comment by thebombzen** [comment]
Fixed by #10117 but yes.
