### ISSUE TITLE
option to change non video background color

### ISSUE THREAD

**Issue by itsjoshpark** [mpv-player/mpv#508]
When you use mpv with `keepaspect` and `wid`, it can show black bars on the sides of the video (the non video part, usually black), which is fine.
Is it possible to change that color so as to integrate it visually with my frontend?

**Comment by UlfR** [comment]
it would be great to have such feature

**Comment by wm4** [comment]
There's actually https://mpv.io/manual/master/#options-background

But it works only for some VOs.

**Comment by UlfR** [comment]
Thanks! It works for opengl, it is enough for me.

**Comment by Tatsh** [comment]
I use this option when testing cropping.
