### ISSUE TITLE
No video playing when not linked against libxss

### ISSUE THREAD

**Issue by Flow-It** [mpv-player/mpv#5082]
### mpv version and platform
0.27.0, Linux

### Reproduction steps
compile mpv on a system where libxss is not installed

### Expected behavior
videos are playing

### Actual behavior
videos are not playing

### Log file
$ mpv --vo=opengl sample.mp4 
Playing: sample.mp4
 (+) Video --vid=1 (*) (h264 320x240 15.000fps)
 (+) Audio --aid=1 --alang=und (*) (aac 6ch 48000Hz)
[vo/opengl] VT_GETMODE failed: Inappropriate ioctl for device
[vo/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
i965_dri.so does not support the 0xffffffff PCI ID.
[vo/opengl] Failed to get EGL display.
[vo/opengl] Failed to setup EGL.
[vo/opengl] 'drm-egl' is deprecated, use 'drm' instead.
[vo/opengl] Can't handle VT release - signal already used
[vo/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
i965_dri.so does not support the 0xffffffff PCI ID.
[vo/opengl] Failed to get EGL display.
[vo/opengl] Failed to setup EGL.
Error opening/initializing the selected video_out (--vo) device.
Video: no video

Exiting... (Errors when loading file)

**Comment by CounterPillow** [comment]
That's because you compiled without X11 support altogether.

**Comment by Flow-It** [comment]
Ok, explicitly enabling x11 output pulls in the neccessary dependencies. I should have paid more attention to the configure output.
