### ISSUE TITLE
not responding after opened .ass file

### ISSUE THREAD

**Issue by 1900forever** [mpv-player/mpv#5084]
I accidentally opened a .ass file, which is a subtitle file type, associated with a .mp4 file. MPV did not response and I could not quite it from dock, and I cannot find mpv process in Activity Monitor either. Meanwhile, no video file could be open by mpv (no response), I have to log out an log in.

**Comment by richardpl** [comment]
MPV Version? ASS file? etc...

**Comment by Akemi** [comment]
most likely this #4926 problem which is fixed in git master.

thx for ignoring the issue template and making me guess everything.

**Comment by 1900forever** [comment]
My bad...
