### ISSUE TITLE
Feedback not given and last issue closed with zero thought.

### ISSUE THREAD

**Issue by tdiguy** [mpv-player/mpv#5087]
platform is windows 10
( terrible feedback / lack of specific feedback from last issue re-creating issue )
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

Reproduction steps

Laptop with discrete and integrated gpu unable to play video's
in my case it is a asus ROG laptop with a ibm graphics card and a nvidia geforce gtx 960m

Expected behavior

nothing happens and no log is generated

Actual behavior

Log file

none is being generated.
Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by rossy** [comment]
I added some comments to your original issue.
