### ISSUE TITLE
any chance of metal support in the future for macOS?

### ISSUE THREAD

**Issue by jerkstore369** [mpv-player/mpv#5088]
as the title..

**Comment by haasn** [comment]
If somebody wants to implement it..

**Comment by timofonic** [comment]
@jerkstore369 Do you want to implement it?

**Comment by jerkstore369** [comment]
I'm not a programmer, sorry. I just like to occasionally read up on solutions for fixes of apps that I use and suggest things based on user experience once in a while. For some reason I find reading about it kind of interesting even though I don't understand it really.

**Comment by beingalink** [comment]
RetroArch seems to have implemented a metal video driver: <https://www.libretro.com/index.php/retroarch-metal-video-driver-for-modern-macos/>. Would this be applicable to mpv, too?

<https://github.com/libretro/RetroArch>

**Comment by Akemi** [comment]
i gave up on the idea of doing metal directly and i am going the way of using moltenVK, which leverages metal too. see #5571.

**Comment by abrasivemurk** [comment]
> i gave up on the idea of doing metal directly and i am going the way of using moltenVK, which leverages metal too. see #5571.

Why did you gave up on doing Metal directly?

**Comment by Akemi** [comment]
because i am too dumb for it.

**Comment by wm4** [comment]
While in theory, creating an internal backend might be relatively simple, the main problem would be the shaders. Metal favors offline shader builds, and they don't use GLSL. Dealing with that could be vfery messy. MoltenVK takes care of these issues.

**Comment by tmm1** [comment]
There is now also an ANGLE wrapper for Metal: https://github.com/kakashidinho/metalangle

**Comment by wm4** [comment]
Is this different from Google's project? They were working on it too, in upstream ANGLE.

**Comment by tmm1** [comment]
Looks like the same thing. This is the developer's fork with pieces that have not been upstreamed yet, and other pieces which likely will never be (such as a replacement wrapper for GLKit). https://github.com/kakashidinho/metalangle#differences-between-metalangle-and-googles-angle
