### ISSUE TITLE
[ytdl_hook] youtube-dl failed

### ISSUE THREAD

**Issue by tp78903** [mpv-player/mpv#5089]
### mpv version and platform

Windows 10
mpv-x86_64-20170913
youtube-dl 2017.11.06

### Reproduction steps

`mpv https://www.youtube.com/watch?v=UlwaXLsvcXY` in command prompt

### Expected behavior
Video plays in mpv correctly

### Actual behavior
Video fails to play

### Log file

https://pastebin.com/5ZsHSkm7

**Comment by garoto** [comment]
You need to drop `youtube-dl.exe` somewhere in your PATH, or at the same dir where `mpv.exe` is located.

**Comment by tp78903** [comment]
@garoto Hi, I have done that already but it still doesn't work. Any ideas?

![explorer_2017-11-08_04-59-03](https://user-images.githubusercontent.com/32758295/32550369-aaa2fafa-c441-11e7-8e83-95f109ccbd6e.png)

**Comment by garoto** [comment]
Ugh, not sure. Is this your 1st time using mpv+youtube-dl or it suddenly broke? Does it work for other YT videos? What about other video hosts like vimeo.com or dailymotion.com?

I'm using the same mpv and ytdl versions, but on Win 8.1 and it works for me. Are you behind some sort of country-wide firewall like in China?

**Comment by tp78903** [comment]
mpv+youtube-dl used to work fine on my previous Win 8 machine. I tried earlier youtube-dl versions but still nothing.

I tried other sites like Twitch or Dailymotion and they are all broken for me..

I'm not using a firewall like that.. only Windows Defender. I'm not sure what it could be.

Thanks for trying to help me @garoto

**Comment by qyot27** [comment]
https://github.com/mpv-player/mpv/issues/4728#issuecomment-320725058

**Comment by tp78903** [comment]
Found the solution, it was caused by missing Visual C++ redist:
https://github.com/rg3/youtube-dl#the-exe-throws-an-error-due-to-missing-msvcr100dll

My bad and sorry for the trouble!
