### ISSUE TITLE
How to prevent the mpv window from changing its size on file change?

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#5091]
### mpv version and platform
0.27.0, Windows 7 SP1

I looked and searched through the manual to see if there's any options to force a specific window size regardless of input video(s), but it keeps setting itself to the video's size on every file\URL change. Am I missing something?

**Comment by wm4** [comment]
You can force the window size with `--geometry=WxH`, but there's no way to just keep the initial window size yet.

**Comment by Hrxn** [comment]
What if you use `--geometry=..` (like above) in conjunction with `--reset-on-next-file=geometry`?

**Comment by wm4** [comment]
That resets only the option value, which does not reflect changes to the window. So it won't do anything.

**Comment by garoto** [comment]
mpv certainly is in need of some usability love.

**Comment by anonish** [comment]
I use
[code]
geometry=..
no-keepaspect-window
[/code]

**Comment by Hrxn** [comment]
Okay, but what about the aspect ratio inside the window then?
