### ISSUE TITLE
mouse wheel not working

### ISSUE THREAD

**Issue by Inginn** [mpv-player/mpv#5092]
### Expected behavior
WHEELUP working or
MOUSE_BTN4 working or
WHEELDOWN working or
MOUSE_BTN3 working 

### Actual behavior
mouse wheel stops working if AXIS is ignored, this used to only work for trackpads but now works for scrollweel to, took ages to find out.

tldr
AXIS_UP    ignore   = mouse wheel not bound

this is both a bug report and a note for others in the same trouble.

**Comment by lachs0r** [comment]
The AXIS and WHEEL events were merged in 7897f79217af1e04e6e65bd72e938058e84c451a.

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
