### ISSUE TITLE
New d3d11 backend incompatible with video filters

### ISSUE THREAD

**Issue by miosenpai** [mpv-player/mpv#5094]
### mpv version and platform
```
mpv 0.27.0-371-gbd4ec8e (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed Nov  8 18:31:34 STD 2017
ffmpeg library versions:
   libavutil       56.0.100
   libavcodec      58.2.100
   libavformat     58.0.102
   libswscale      5.0.101
   libavfilter     7.0.101
   libswresample   3.0.101
ffmpeg version: git-2017-11-07-3e0a87c
```
### Reproduction steps
Enable hwdec=d3d11va, vo=gpu, gpu-context=d3d11 and a video filter such as vf=scale=1280:720. Similar behavior can also be triggered by the following VapourSynth script taken from the manual.
```
import vapoursynth as vs
core = vs.get_core()
core.std.AddBorders(video_in, 10, 10, 20, 20).set_output()
```
### Expected behavior
Player to continue using the d3d11 backend.
### Actual behavior
Player reverts to software decoding.
### Log file
vf=scale=1280:720 - https://pastebin.com/YW82c0mT
vapoursynth - https://pastebin.com/3DQ8ikan

**Comment by wm4** [comment]
This has nothing to do with the backend. Direct hw decoding is always incompatible to video filters which want to work on CPU memory. Use a `-copy` hwdec mode.
