### ISSUE TITLE
Hardware encoded HEVC on latest Mac through FFmpeg fails (video toolbox)

### ISSUE THREAD

**Issue by AlexisMay** [mpv-player/mpv#5095]
Platform : macOS 10.13
Adding a hwenc requires an annoying number of small changes to some FFmpeg files, but main logic is in libavcodec/videotoolboxenc.c

I was trying to use -c:v hevc_videotoolbox on my Kaby Lake Mac. Any suggestions to make it work out of the box?

**Comment by tmm1** [comment]
What does this have to do with mpv? Does mpv let you encode video?
