### ISSUE TITLE
--videotoolbox-format=no disables hardware acceleration on new Macs

### ISSUE THREAD

**Issue by Forcer78** [mpv-player/mpv#5096]
This exact configuration used to work as expected on a Haswell Mac, but appears to break on Kaby Lake.

Somewhat related, I was hoping the Kaby Lake Mac supported HEVC and VP9 in hardware, but it looks like that isn't exposed?

### mpv version and platform

```
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Nov  3 21:55:07 EDT 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4
```

Latest Homebrew version on macOS 10.12.6.

### Reproduction steps

Play an H.264 file with `--hwdec=auto` and `--videotoolbox-format=no`.

### Expected behavior

Hardware-accelerated output with decoder-chosen pixel format.

### Actual behavior

mpv/ffmpeg falls back to software decoding.

### Log file

`--no-config`: http://sprunge.us/dLOS
\+ `--hwdec=auto`: http://sprunge.us/EcDD
\+ `--videotoolbox-format=no`: http://sprunge.us/OVVF
```
[   0.077][v][vd] Unsupported hw decoding format: yuv420p
```

### Sample files

Taken from another issue: https://0x0.st/FZA.mp4

**Comment by wm4** [comment]
Not sure why you think you need `--videotoolbox-format`. This changed again in mpv git master, where this particular thing should work again (actually the option has been deprecated and replaced by a more general one). The `no` choice actually doesn't do anymore what it used to do, but it never did anything too useful anyway.
