### ISSUE TITLE
How to specify the quality of a live YouTube broadcast

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5098]
Libmpv 13 sep (last version) 

Good morning, I would like to know how I have to write on the command line to specify the playback quality of a live YouTube broadcast.
For example, whenever I play this link
https://youtu.be/0tek2aa8hAQ
Always play it at 720p
How can I select the playback quality?
Does it differ in something that is a live video and not a common YouTube video?
Thank you very much!

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/1460675/log.txt)

### Sample files
https://youtu.be/0tek2aa8hAQ

**Comment by CounterPillow** [comment]
you can set `ytdl-format` to a format you wish to use, e.g. `ytdl-format=[height<=360]` would select the highest quality stream below a height of 360.

**Comment by EzeKees** [comment]
Thank you very much!

**Comment by garoto** [comment]
https://github.com/rg3/youtube-dl/blob/master/README.md#format-selection

**Comment by EzeKees** [comment]
Yes, thank you very much, but from the link that you sent me, I still do not know how to designate the commands in mpv, I do not know the syntax. (I'm in Windows 8)

**Comment by garoto** [comment]
What's your resolution goal?

In the command prompt, to play the first video stream with height less than 720px:

`mpv --ytdl-format="[height<720]" https://youtu.be/0tek2aa8hAQ`

Or just add `ytdl-format="[height<720]/best"` to your `mpv.conf`.

**Comment by EzeKees** [comment]
Thank you very much!
I got a lot of doubts, congratulations to all for this great software
