### ISSUE TITLE
Cyan-like color with Vulkan after updating Intel driver

### ISSUE THREAD

**Issue by YuriMachine** [mpv-player/mpv#5099]
### mpv 0.27.0-349-gd46c9c2e62-dirty Windows 10 x64

I've already tried using different gpu-context

### Expected behavior
https://abload.de/img/immagine0bjrt.png
### Actual behavior
https://abload.de/img/immagine2z5k0o.png
### Log file

https://pastebin.com/QRyeh93d

**Comment by shinchiro** [comment]
Try removing `hwdec=auto` from your mpv.conf

**Comment by YuriMachine** [comment]
It's the same even with a mpv.conf like this:
```
profile=gpu-hq
gpu-api=vulkan
gpu-context=winvk
spirv-compiler=shaderc
```
The only thing I noticed is that if I remove profile=gpu-hq the screen turns white instaed of cyan

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
