### ISSUE TITLE
Colons in screenshot-template=%p

### ISSUE THREAD

**Issue by tewe** [mpv-player/mpv#51]
OS X allows colons in file names, but the file manager displays them as slashes for historical reasons. They're generally not a good idea.

The man page says %p uses the OSD format, but I couldn't find a way to change it.

How about individual percent sequences for play time?

**Comment by hejops** [comment]
Colons are no longer accepted on my linux machine, probably as a result of some update I'm not fully aware of.

**Comment by tewe** [comment]
"Colons not accepted" is a bit vague. You're using %p and getting an error? You put `:` in a template and it doesn't show up in `ls`?

**Comment by hejops** [comment]
Yes, I'm using %p, and mpv simply returns the following:
```
Error opening '00:00:00.png' for writing!
Error writing screenshot!
```

**Comment by tewe** [comment]
That seems to be `fopen` failing. Which is separate from configuring a template without colons, so please create a new issue. Including the following information will help.

What is the current directory? Do you have the right permissions on it? What kind of file system is it on?

**Comment by hejops** [comment]
My apologies, I realised I was performing the action on an NTFS filesystem (although a few weeks ago I could do it just fine; not an mpv issue then). Nonetheless I still think the default setting should be something that's usable in all use cases.

**Comment by eugenesvk** [comment]
You could replace regular colons with this Modifier Letter Colon https://unicode-table.com/en/A789/ to avoid the old filesystem bugs and maintain the nicely separated times you're used to everywhere else
: → ꞉
