### ISSUE TITLE
5.1 surround not set right and being downmixed to 3.1 

### ISSUE THREAD

**Issue by bacon-cheeseburger** [mpv-player/mpv#5101]
### mpv version and platform
debian testing linux, kernel 4.13.12, audio output via HDMI connected to surround receiver
mpv compiled from git (0.27.0-393-git+8e50dc1)
ffmpeg-mpv compiled from git (3.5-dev-914-git+aeed5ec)

### Reproduction steps
DISPLAY=:0.0 mpv --ao=alsa --audio-device=default --audio-channels=6 --no-cache --no-config --demuxer=lavf --fullscreen --input-file=/dev/stdin --input-terminal=no --osd-duration=2000 -v --vo=gpu --hwdec=auto "/test/samples/51.surround.aac.mp4"

### Expected behavior
5.1 surround sound is expected.

### Actual behavior
The 5.1 audio is being downmixed to 3.1. Using the --alsa-ignore-chmap doesn't help. The log shows LR/RR being reported as UNKNOWN.

### Log file
http://paste.debian.net/995111/

### Sample files
https://0x0.st/siiT.mp4

**Comment by lachs0r** [comment]
Try --audio-channels=5.1 (or whatever your setup is).
Also, on most distros, the “default” device is stereo-only by default. You’ll 
have to fix that up manually. For example:
https://github.com/mpv-player/mpv/wiki/ALSA:-Surround-Sound-and-Upmixing

(You’ll have to adapt that to your setup of course)

**Comment by lachs0r** [comment]
Actually, just paste your .asoundrc or whatever you use to configure your 
channel layout.

**Comment by bacon-cheeseburger** [comment]
Thanks for your reply. Here's my ~/.asoundrc:
~$ cat ~/.asoundrc
pcm.!default "hdmi:NVidia,1"
~$

Unfortunately I just noticed that didn't work right anymore so I'm not sure at what point the problem arouse. In case this is helpful, here's the eld info as well:

~$ cat /proc/asound/card1/eld#0.1
monitor_present         1
eld_valid               1
monitor_name            SONY AVAMP

connection_type         HDMI
eld_version             [0x2] CEA-861D or below
edid_version            [0x3] CEA-861-B, C or D
manufacture_id          0xd94d
product_id              0xf02
port_id                 0x200
support_hdcp            0
support_ai              0
audio_sync_delay        0
speakers                [0x5f] FL/FR LFE FC RL/RR RC RLC/RRC
sad_count               12
sad0_coding_type        [0xc] MLP (Dolby TrueHD)
sad0_channels           2
sad0_rates              [0x1ec0] 44100 48000 88200 96000 176400 192000
sad1_coding_type        [0xc] MLP (Dolby TrueHD)
sad1_channels           6
sad1_rates              [0x1ec0] 44100 48000 88200 96000 176400 192000
sad2_coding_type        [0xc] MLP (Dolby TrueHD)
sad2_channels           8
sad2_rates              [0x6c0] 44100 48000 88200 96000
sad3_coding_type        [0xb] DTS-HD
sad3_channels           2
sad3_rates              [0x1ec0] 44100 48000 88200 96000 176400 192000
sad4_coding_type        [0xb] DTS-HD
sad4_channels           6
sad4_rates              [0x1ec0] 44100 48000 88200 96000 176400 192000
sad5_coding_type        [0xb] DTS-HD
sad5_channels           8
sad5_rates              [0x6c0] 44100 48000 88200 96000
sad6_coding_type        [0x1] LPCM
sad6_channels           2
sad6_rates              [0x1ee0] 32000 44100 48000 88200 96000 176400 192000
sad6_bits               [0xe0000] 16 20 24
sad7_coding_type        [0x1] LPCM
sad7_channels           6
sad7_rates              [0x1ee0] 32000 44100 48000 88200 96000 176400 192000
sad7_bits               [0xe0000] 16 20 24
sad8_coding_type        [0x1] LPCM
sad8_channels           8
sad8_rates              [0x1ee0] 32000 44100 48000 88200 96000 176400 192000
sad8_bits               [0xe0000] 16 20 24
sad9_coding_type        [0x2] AC-3
sad9_channels           6
sad9_rates              [0xe0] 32000 44100 48000
sad9_max_bitrate        680000
sad10_coding_type       [0x7] DTS
sad10_channels          6
sad10_rates             [0x6e0] 32000 44100 48000 88200 96000
sad10_max_bitrate       1536000
sad11_coding_type       [0xa] E-AC-3/DD+ (Dolby Digital Plus)
sad11_channels          8
sad11_rates             [0xc0] 44100 48000

**Comment by bacon-cheeseburger** [comment]
I just did a check with speaker-test and got the following results. Although 4 & 5 are shown as "Unknown", they correctly played as 4 "Front Center" and 5 "Subwoofer".

~$ speaker-test -c 6 -t wav

speaker-test 1.1.3

Playback device is default
Stream parameters are 48000Hz, S16_LE, 6 channels
WAV file(s)
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 64 to 5440
Period size range from 32 to 2720
Using max buffer size 5440
Periods = 4
was set period_size = 1088
was set buffer_size = 5440
 0 - Front Left
 1 - Front Right
 3 - Rear Right
 2 - Rear Left
 4 - Unknown
 5 - Unknown
Time per period = 8.526012

**Comment by bacon-cheeseburger** [comment]
Turns out this is a problem with drivers. Sorry MPV!
