### ISSUE TITLE
mpv should never try to resume streams

### ISSUE THREAD

**Issue by vimeitor** [mpv-player/mpv#5102]
mpv 0.27

Hi. I'm not completely sure what classifies as stream and what does not, but opening a stream like Twitch should never try to resume a previous session. Currently, it takes about 30s for a stream to load on my pc unless I pass the _--no-resume-playback_ because of that. Granted, I have _save-position-on-quit=yes_ on my config, but it shouldn't affect it regardless.

**Comment by dragons4life** [comment]
Add this to mpv.conf at the bottom, applies to everything you are playing from the web.

[protocol.http]
no-resume-playback
[protocol.https]
profile=protocol.http
[protocol.ytdl]
profile=protocol.http

**Comment by vimeitor** [comment]
Thank you very much for your answer. Works flawlessly. I will close the issue, but feel free to reopen it if needed.
