### ISSUE TITLE
Initial transients of audio files are mangled on first few playbacks

### ISSUE THREAD

**Issue by ottworks** [mpv-player/mpv#5103]
### mpv version and platform
Windows 10
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed Sep 13 04:18:08 CEST 2017
ffmpeg library versions:
   libavutil       55.74.100
   libavcodec      57.105.100
   libavformat     57.82.100
   libswscale      4.7.103
   libavfilter     6.105.100
   libswresample   2.8.100
ffmpeg version: N-87286-g6ce4a635ed

### Reproduction steps
1. Play a file with a sharp initial transient (such as a single drum hit).
### Expected behavior
The transient plays correctly and is heard correctly.
### Actual behavior
The transient is lost on initial playback, but is audible when restarting playback after a few times.
### Log file
https://pastebin.com/raw/jucq2ENP
### Sample files
Here is a video of the issue: https://my.mixtape.moe/lljnsd.mp4
Here is the audio file in question: https://my.mixtape.moe/jfnxze.wav

**Comment by kevmitch** [comment]
possibly related to #4842

**Comment by Dudemanguy** [comment]
The audio API was completely rewritten since this issue, so things are completely different now internally. Please make a new issue if the problem still exists.
