### ISSUE TITLE
Linking error with mingw

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#5106]
### mpv version and platform

Commit 9b5d062

### Expected behavior

Compile as usual

### Actual behavior

Failed at linking with lots of undefined reference pointed to libavformat. The Travis build also got similar errors

### Log file

[error log](https://0x0.st/siNx.log)
[build log](https://0x0.st/siN3.log)

**Comment by wm4** [comment]
Probably something that ffmpeg broke. Does it work with upstream ffmpeg? If not I could revert it for now.

**Comment by kwkam** [comment]
I got similar error messages (those undefined symbols) and then I checked the file `mpv/build/c4che/_cache.py` , and noticed that the ld flags for ffmpeg is strange.
Just modified `ffmpeg/configure` and mpv.exe is linked successfully.
```
diff --git a/configure b/configure
index c6fb344929..6db8e02ad6 100755
--- a/configure
+++ b/configure
@@ -7011,7 +7011,7 @@ EOF

 for lib in $LIBRARY_LIST; do
     lib_deps="$(eval echo \$${lib}_deps)"
-    echo ${lib}_deps=\"$lib_deps\" >> ffbuild/config.sh
+    echo ${lib}_deps=\"$lib_deps\" >> $TMPH
 done

 cp_if_changed $TMPH ffbuild/config.sh
```

**Comment by jamrial** [comment]
pkg-config file creation was broken by a recent libav commit that was merged to ffmpeg, but should be now fixed in both projects.

**Comment by shinchiro** [comment]
Yeah, no more linker errors with ffmpeg git. Thanks for the help
