### ISSUE TITLE
Feature request: support .url (internet shortcut) files

### ISSUE THREAD

**Issue by UserNaem** [mpv-player/mpv#5107]
I wanted to associate web shortcuts with mpv, but that didn't go so well, mpv tried to play the shortcut.

**Comment by wm4** [comment]
Link to technical spec?

**Comment by UserNaem** [comment]
MSDN article: https://msdn.microsoft.com/en-us/library/windows/desktop/bb776784(v=vs.85).aspx

Internet shortcuts are technically INI files that should contain the following:
```
 [InternetShortcut]
 URL=http://example.com
```
They might contain other metadata, but that's safe to ignore.

**Comment by UserNaem** [comment]
(Tl;dr: a .url file has syntax similar to INI files and should contain one URL, like this)
```
[InternetShortcut]
URL=http://example.com
```
