### ISSUE TITLE
Video freezes briefly when entering fullscreen

### ISSUE THREAD

**Issue by dreness** [mpv-player/mpv#5110]
### mpv version and platform
```
mpv 0.27.0-349-gd46c9c2e62-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Nov  4 08:50:51 UTC 2017
ffmpeg library versions:
   libavutil       56.0.100
   libavcodec      58.2.100
   libavformat     58.0.102
   libswscale      5.0.101
   libavfilter     7.0.101
   libswresample   3.0.101
ffmpeg version: git-2017-11-04-9d0b42bce
```
win10/64bit

### Reproduction steps
This problem can happen with most any clip. Let's use some stuff generated by ffmpeg:
```
ffmpeg -f lavfi -i "testsrc=duration=10:size=2560x1440:rate=60" \
-f lavfi -i "aevalsrc=sin(880*2*PI*sin(t/5)*t):d=10:s=4000" \
-c:a pcm_s16le -codec:v libx264 output.mkv
```
Here's a copy of that file: [output.mkv](https://youbeill.in/scrap/mpv/output.mkv)

In pursuit of consistent timing between the good vs bad repro case, how about a small lua script that engages fullscreen at the 5 second mark:

```
local function goFS()
        mp.set_property('fullscreen', 'yes')
end

mp.add_timeout(5,goFS)
```
Now we'll run mpv with default settings targeting the file generated by ffmpeg. Also write a stats / log file, load the above lua script, and disable the OSD. I threw in gpu-debug at no extra charge.
```
mpv.com --no-config --dump-stats=mpv-stats-bad.txt --log-file=mpv-log-bad.txt \
--no-osc --script=fs.lua --gpu-debug=yes output.mkv
```
... and again for the 'good' repro case, where I employ the crafty workaround of moving the mouse just before the 5s mark.
```
mpv.com --no-config --dump-stats=mpv-stats-good.txt --log-file=mpv-log-good.txt \
--no-osc --script=fs.lua --gpu-debug=yes output.mkv
```

### Expected behavior
In both cases, there should be no video hitch when fullscreen engages.

### Actual behavior
In the bad case, where there's no mouse movement, video hitches fairly badly (usually around 1 second) when entering fullscreen.

### Logs and stats
For each case (bad and good), I've provided logs and stats files, as well as a PNG of the graph generated by [stats-conv.py](https://github.com/mpv-player/mpv/blob/master/TOOLS/stats-conv.py) from the stats file.
#### Bad case
- [mpv-log-bad.txt](https://youbeill.in/scrap/mpv/mpv-log-bad.txt)
- [mpv-stats-bad.txt](https://youbeill.in/scrap/mpv/mpv-stats-bad.txt)
![alt text](https://youbeill.in/scrap/mpv/bad.png "Bad stats graph")

#### Good case
- [mpv-log-good.txt](https://youbeill.in/scrap/mpv/mpv-log-good.txt)
- [mpv-stats-good.txt](https://youbeill.in/scrap/mpv/mpv-stats-good.txt)
![alt text](https://youbeill.in/scrap/mpv/good.png "Good stats graph")

### Notes
- I've experimented with many different vo / gpu-api settings; it doesn't seem to affect this problem
- If I disable mouse input completely with ```--input-cursor=no```, the workaround stops working
- ```cursor-autohide``` doesn't seem to make a difference
- the audio is *usually* not affected, but sometimes it hitches with the video
- thanks for your work on this project, it's pretty rad :)

**Comment by ArchangeGabriel** [comment]
I’m seeing the reverse behaviour, i.e. freezing when leaving full screen, but I think I know why: compositing behaviour. I have no compositing for full screen windows, but do for windowed ones. So this is likely compositing flipping on/off in my case that produces this.

Not sure if that could be your case too, but I would start by checking that. ;)

**Comment by Hrxn** [comment]
What do you mean? Did you manually set some custom options for compositing in Windows? Via some 3rd-party tool or something?

**Comment by aufkrawall** [comment]
For Windows 8, you can turn off compositing only via hacks, and for Windows 10 not at all.
It also shouldn't be necessary because DWM does work fine and mpv runs in borderless fullscreen instead of exclusive fullscreen, which allows instant switching.
For Windows 7, DWM can still be disabled in compatibility options. Windows 7 DWM is old DX9 crap, so it might help.
You can also try gpu-shader-cache-dir=~~/shader-cache to perhaps mitigate the problem.

With Windows 10, D3D11 and cached shaders switching should be instant.

**Comment by Hrxn** [comment]
Yea, that's why I was a bit baffled by this..

**Comment by stax76** [comment]
Is your Windows 10 Version 1709?

**Comment by ArchangeGabriel** [comment]
@Hrxn I’m not on Windows. My compositor is kwin. I was just saying that something similar could be at play, I don’t know how Windows works.

**Comment by aufkrawall** [comment]
Disable turning off of compositor in fullscreen.
I think KWin behavior has recently changed to flicker when turning off compositing. It can also stutter after reenabling it.

**Comment by garoto** [comment]
[**@ArchangeGabriel**](https://github.com/ArchangeGabriel) commented on [Nov 14, 2017, 1:40 PM GMT-2](https://github.com/mpv-player/mpv/issues/5110#issuecomment-344298597 "2017-11-14T15:40:14Z - Replied by Github Reply Comments"):
> [@Hrxn](https://github.com/hrxn) I’m not on Windows. My compositor is kwin. I was just saying that something similar could be at play, I don’t know how Windows works.

You could have said that as the 1st statement of your 1st reply to this Windows specific issue. Or better yet, open your own issue.

**Comment by dreness** [comment]
This is a little embarrassing, but... this no longer reproduces on my machine. The only intentional change between then and now was an upgrade of [Afterburner](https://www.guru3d.com/files-details/msi-afterburner-beta-download.html) to the latest version, which included a re-installation of [RTSS](http://www.guru3d.com/files-details/rtss-rivatuner-statistics-server-download.html) version 7 (which I was already running). I use these only for monitoring and screen recording, not overclocking.

Hmm... it's possible I also changed the "application detection level" in RTSS - I'll experiment more when I get home.

**Comment by Hrxn** [comment]
That's good to hear. A little remark on this issue here: Reproduction could be a bit difficult for us other users, because you use some pretty specific Windows built without stating on how or where to obtain it. I don't know, but I wouldn't be surprised if only a handful of people on this planet actually use or have this specific version right now, if at all. So, the easiest way would probably be to upload the binaries somewhere?

**Comment by ArchangeGabriel** [comment]
@garoto Sorry, I was just saying that compositing might be the issue. I know my WM is at fault here, that’s why I did not open an issue against mpv for this, and I did not expect people would try to help me since I know exactly why it happens.

**Comment by dreness** [comment]
I've been watching like a hawk, and this problem has never reoccured.

@Hrxn - I believe I got the mpv binary I use on my Windows machine from https://mpv.srsfckn.biz

Closing this since I can no longer repro.
