### ISSUE TITLE
Segmentation Fault when using mpv with SVP

### ISSUE THREAD

**Issue by valdotdev** [mpv-player/mpv#5116]
### mpv version and platform

mpv `--HEAD --with-vapoursynth` | macOS 10.13.1

_Built with homebrew and modified the ffmpeg formula to get the source from ffmpeg-mpv_

### Reproduction steps

1. Open SVP
2. Open a video file with the recommended command options per their [website](https://www.svp-team.com/wiki/SVP:Mac)
```
input-ipc-server=/tmp/mpvsocket
hwdec-codecs=all
hwdec=auto-copy
opengl-early-flush=no
hr-seek-framedrop=no
```

### Expected behavior

mpv and SVP works fine

### Actual behavior

mpv crashes even with `--no-config`

I know that mpv doesn't natively/properly support SVP but prior to High Sierra everything seemed to work fine. Ultimately, I'm not sure if the problem is with mpv or SVP. Since it was working prior to the OS update I just thought it was worth reporting anyway. Doesn't also work with the latest stable release but did in Sierra.

### Log file

Output with `-v` ran in `gdb`

http://sprunge.us/ZiIC

### Sample files

Tested with a bunch of mkv and mp4 files

**Comment by Argon-** [comment]
Can you either compile with debug symbols and redo and/or upload the crash report from OSX (with resolves a few more symbols than what you posted)?

**Comment by valdotdev** [comment]
Here's the crash report after trying again (outside gdb) http://sprunge.us/hZPO

Unfortunately I'm not very familiar (nor much experience) on how to compile with debug symbols with these types of applications. Do you have any references I can use If the above still won't suffice? Thanks.

**Comment by Argon-** [comment]
Well it's crashing in SVP for once. Apparently when it attempts to draw some on-screen stuff (`SmoothFpsCore::drawOSD`). Can you deactivate this overlay and try again?
As for why this happens: no idea. I'm just guessing.

Is the only difference really 10.13 and not maybe ffmpeg-mpv? Do older mpv versions work on 10.13?

**Comment by valdotdev** [comment]
Test results using mpv stable with different ffmpeg versions:

-  SVP + mpv v0.27.0 + ffmpeg 3.4 + OSD on = **crash**
-  SVP + mpv v0.27.0 + ffmpeg 3.4 + OSD off = OK
-  SVP + mpv v0.27.0 + ffmpeg master + OSD on = **crash**
-  SVP + mpv v0.27.0 + ffmpeg master + OSD off = OK
-  SVP + mpv v0.27.0 + ffmpeg-mpv + OSD on = **crash**
-  SVP + mpv v0.27.0 + ffmpeg-mpv + OSD off = OK

So basically crashing occurs regardless of ffmpeg version. In which...I'm not sure what's happening at this point. My only guess is it's something to do with macOS?

**Comment by Akemi** [comment]
only the SVP devs can tell you what exactly happens. it's more likely a problem in SVP itself, since it doesn't crash in a system lib. anyway you should report that to them.

**Comment by valdotdev** [comment]
@Akemi Thanks. Reported to them some hours ago.
