### ISSUE TITLE
[ffmpeg] Invalid return value 0 for stream protocol

### ISSUE THREAD

**Issue by Brottweiler** [mpv-player/mpv#5118]
### mpv version and platform

```sh
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Nov  3 14:10:56 CET 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4
```

- Archlinux
- `Linux noname 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux`

### Reproduction steps
`mpv https://go.twitch.tv/monstercat --no-vid --volume=0 --no-config`

### Expected behavior
Output looking like this

```sh
Playing: https://go.twitch.tv/monstercat
 (+) Audio --aid=1 (aac 2ch 48000Hz)
AO: [pulse] 48000Hz stereo 2ch float
A: 00:00:01 / 00:00:00 Cache:  3s+6KB
```

### Actual behavior
Output spammed with `[ffmpeg] Invalid return value 0 for stream protocol`

### Log file
https://gist.github.com/cd701ca0a07eacb2957642110736f8b8

### Sample files

Play any twitch stream or youtube video with mpv.

------

This might not be an issue of mpv, but ffmpeg, but I think you know better than me, this didn't use to happen but started happening recently for some reason.

**Comment by tmm1** [comment]
This is due to a change in ffmpeg 3.4

You can either switch to an older version of ffmpeg, or compile a newer version of mpv.

**Comment by Brottweiler** [comment]
@tmm1 Ah, so upgrading mpv will solve this? Either by compiling it or wait for an update? Good to know.

**Comment by jamrial** [comment]
@tmm1 No, it's not a change in ffmpeg 3.4. The avio change is only officially available on git master, but for some reason the Arch ffmpeg maintainer backported it to their ffmpeg 3.4 package, as well as the mpv commit that adapted to it into their mpv 0.27 package.

Why? I don't know.

**Comment by wolkenschieber** [comment]
Is the Arch maintainer aware of this issue?

**Comment by CounterPillow** [comment]
@wolkenschieber you should probably ask the arch maintainer that, and not here.
