### ISSUE TITLE
OSC (bottombar) isn't visible/working on Wayland backend || The MPV window is unfocused and can be fixed only by clicking on top

### ISSUE THREAD

**Issue by paulcarroty** [mpv-player/mpv#5120]
### mpv version and platform

mpv 0.27, SUSE Tumbeweed

### Reproduction steps

1. Enable OpenGL and Wayland backend via `vo=opengl` and `opengl-backend=wayland`

### Expected behavior

* Move mouse/touchpad to bottombar and he is visible
* MPV window is stable and focused 

### Actual behavior

* no bottombar
* The MPV window will hide when you click or move cursor.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/1476420/log.txt)

### Sample files

`mpv --vo=opengl --opengl-backend=wayland --hwdec=vaapi  --log-file=/tmp/log.txt https://www.youtube.com/watch?v=E4FY894HyF8`

**Comment by lachs0r** [comment]
Fixed in master.
