### ISSUE TITLE
Stuck at buffering with youtube's live video

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#5121]
### mpv version and platform
41243e7c4f - Win10-x64

### Reproduction steps
Open any youtube's live video. Run mpv without user's config, `--no-config`

### Expected behavior
Play smoothly

### Actual behavior
Loaded video for a few seconds and stuck at buffering for eternity. Already used latest youtube-dl

### Log file
[log-file](https://0x0.st/s-Xs.txt)

**Comment by wm4** [comment]
When I tried it before, it worked fine (and used HLS).

When I try to open it know, it uses EDL (ytdl.lua using generic segmented support via youtube-dl), and not the pseudo-DASH EDL. So this can't work well. It always freezes when opening segment 2.

**Comment by shinchiro** [comment]
Is there any workaround for this (for now)

**Comment by aufkrawall** [comment]
Is it to be expected that only the Windows build is affected by this, but not Linux?
Because that's the case for me.

**Comment by shinchiro** [comment]
The schannel lib was the fault. Using libressl or openssl fixed it

**Comment by aufkrawall** [comment]
Seems lachs0r's 0.28 build uses schannel since it shows the same problem.
