### ISSUE TITLE
URLs with known multimedia formats shouldn't call hooks like ytdl-hooks

### ISSUE THREAD

**Issue by Porkepix** [mpv-player/mpv#5125]
### mpv version and platform

mbp :: ~ » mpv --version
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Nov 16 17:35:12 CET 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4

OS: macOS 10.9

### Reproduction steps

Besides mpv, having youtube-dl installed on the computer.
Call mpv on a url with known multimedia extensions, let's say a .mp3 or .m3u

### Expected behavior

URLs ending with a known multimedia format shouldn't call the ytdl-hook and play it immediately.

### Actual behavior

Due to another problem (known and independent, this issue just highlight the reported issue), I could notice that the ytdl-hook was called even if the url is ending with nown multimedia formats

Examples:
```
» mpv https://direct.franceinfo.fr/live/franceinfo-midfi.mp3

Playing: https://direct.franceinfo.fr/live/franceinfo-midfi.mp3
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno 54] Connection reset by peer> (caused by URLError(error(54, 'Connection reset by peer'),))
[ytdl_hook] youtube-dl failed, trying to play URL directly ...
```
```
» mpv http://listen.moe/stream.m3u
Playing: http://listen.moe/stream.m3u
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
[ytdl_hook] youtube-dl failed, trying to play URL directly ...

Playing: https://listen.moe/vorbis
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
[ytdl_hook] youtube-dl failed, trying to play URL directly ...
```
Yet again, SSL errors are another issue (and I know why those are here: system's python is too old and changing PATH for a more recent one make it disappear), but this made me able to see it was calling the hook while I think it could be done without.

PS: But while it's mentionned here, if you think those SSL issues should have a workaround or be reported for older pythons, please tell me but I guess this is affecting too old ones for that?

**Comment by shinchiro** [comment]
> mpv http://listen.moe/stream.m3u
This works fine here on windows build

**Comment by SirCmpwn** [comment]
That's actually somewhat concerning if it works without hitting youtube-dl. This is by design imo. We'd have to reach out with an HTTP HEAD request to grab the Content-Type to know what it actually is, we definitely shouldn't infer it from the URL.

**Comment by lachs0r** [comment]
Exactly. And it would be pointless for us to do so because youtube-dl already does that work for us. We always call the ytdl hook because that is the easiest way to determine whether a given URL is supported by youtube-dl. In fact, there’s no way to do this without running youtube-dl, for instance due to its generic extractor. And we can’t just look at the URL pattern and assume it won’t need youtube-dl either—see Dropbox for example.

I don’t think we need a workaround for systems where Python is installed with a broken SSL library. Just fix that or use --no-ytdl there.
