### ISSUE TITLE
Some streams can present "invalid audio PTS" issues

### ISSUE THREAD

**Issue by Porkepix** [mpv-player/mpv#5126]
### mpv version and platform

mbp :: ~ » mpv --version
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Nov 16 17:35:12 CET 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4

OS: macOS 10.9

### Reproduction steps

Run mpv on some streams having the issue

### Expected behavior

It shouldn't present any errors

### Actual behavior

Between every track on the stream, player is printing error lines like the following one:

`Invalid audio PTS: 256.587755 -> -0.002902`

The right part of the arrow is always the same.

### Additional notes

When this happens, display is like the following:
```
A: 00:03:27 / 00:00:00 Cache:  0s+31KB
Invalid audio PTS: 207.535601 -> -0.002902
A: 00:01:01 / 00:00:00 Cache:  3s+0KB
```
So, total time is missing, but the line before the error one seems to show the total time as current time and after the error it shows the correct playing time.

This could also be a server-side problem from the streaming service, but my knowledges on the topic are a bit low to judge about that.

**Comment by kevmitch** [comment]
probably broken file. need logs and sample.

**Comment by Porkepix** [comment]
@kevmitch My bad, I was sure I did gave the URL but it seems I failed and it was not in the opening post. Sorry about that forgetting.

Problem does reproduce on every track change on this stream URL: `http://listen.moe/stream.m3u`on several computers. So I think instead of a sample you can easily reproduce it by playing it.
Same goes for logs as you probably would get more accurate ones than me, but if yu really want mine, I'm not sure where can I find how to get those.

**Comment by wm4** [comment]
This is an ogg stream which includes timestamps that reset on track change. So this is as expected. Would probably be nicer if ffmpeg reported this somehow.
