### ISSUE TITLE
any chance to be able to live switch between audio channels? 

### ISSUE THREAD

**Issue by zmartell** [mpv-player/mpv#5129]
I am looking to be able to switch between audio channels. I have found a way to switch between individual audio tracks but i have videos where certain audio is on the left speaker, and other audio is on the right speaker and need to cycle/select between the two.

**Comment by Idlusen** [comment]
Searching for "channel" in the manual, you find the simple --balance option, however deprecated (as mpv will tell you when you using it) in favor of the lavfi pan filter.
Thus you could have in you input.conf
`[ set af lavfi="pan=1c|c0=c0"`
`] set af lavfi="pan=1c|c0=c1"`
or, same effect with --balance:
`[ set balance -1`
`] set balance 1`
These previous commands map the left or right channel to both speakers. To only mute one speaker:
`[ set af lavfi="pan=stereo|c0=c0"`
`] set af lavfi="pan=stereo|c1=c1"`

**Comment by wm4** [comment]
Both balance and pan have been removed from git master. Now don't need the `lavfi=` thing anymore, because `pan` uses the lavfi filter directly.

**Comment by kevmitch** [comment]
This is the kind of "special" feature that is best suited for a script. Take a look at [acompressor.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/acompressor.lua) for an example of how to add key bindings to modify filters on the fly.
