### ISSUE TITLE
regression: D3D11VA not working anymore for VC-1 (progressive and interlaced)

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#5131]
### mpv version and platform
mpv 0.27.0-407-gcd6f964b56-dirty
Windows 10 AU x64

### Reproduction steps
Set up a config like this:
hwdec=d3d11va
gpu-api=opengl
gpu-context=angle

...and play either VC-1 progressive or deinterlaced.
(edit: I wrote "VP9" instead of "VC-1", sorry for the confusion)

### Expected behavior
It should use D3D11VA hardware decoding like with latest stable build 0.27.

### Actual behavior
On both Nvidia and Intel, mpv-git refuses to use D3D11VA for both progressive and interlaced VC-1.
Doesn't matter if angle or native D3D11 renderer is chosen. DXVA2 oddly works.

### Log file
https://pastebin.com/SfZXE62v

### Sample files
Not tied to a specific sample, but in case you quickly want VC-1 progressive and interlaced samples to reproduce:
http://www64.zippyshare.com/v/2qYkaVZb/file.html

**Comment by thebombzen** [comment]
Is this still a problem in 0.28.0?

**Comment by aufkrawall** [comment]
Yes, still only DXVA2 works with this codec.

**Comment by wiiaboo** [comment]
Seems to be a FFmpeg bug though. `ffmpeg -hwaccel d3d11va -i <vc1> -f null -` doesn't work either.

**Comment by aufkrawall** [comment]
Got fixed in ffmpeg.
