### ISSUE TITLE
Feature request: autoload subtitle tracks in mka files when opening a mkv file with --audio-file-auto and --sub-auto

### ISSUE THREAD

**Issue by zc62** [mpv-player/mpv#5132]
Although mka is designed to have audio only in Matroska standard, there do exist many mka files containing not only audio tracks, but also subtitle tracks. As mentioned in issue #2663, mpv is able to load mka files as external subtitle files via the --sub-file option, however, I think it is probably more natural to let the --sub-auto option automatically handle mka files. This will be great for people who mainly use the pseudo-gui version of this software.

**Comment by zc62** [comment]
I made up a [script](https://github.com/zc62/mpv-scripts/blob/master/autoload-sub-in-mka.lua) to work on this feature.

**Comment by kevmitch** [comment]
In this and the previous bug, I never saw a sample file. I just made an mka by stripping out the video from a DVD rip in mkvtoolnix and the subtitlles just worked. Or is this something about trying to be clever about which subtitle to select? Is the script sufficient? How does mpv handle mka differently than mkv and why?

**Comment by zc62** [comment]
@kevmitch 
OK I didn't make it clear. I know when a single mka file is opened by mpv, all audio and subtitle tracks in this mka file are loaded properly. The problem occurs when the mka file is loaded by `--audio-file-auto` option. You can try keep that mka file you had, leave only the video track in the mkv file and open the mkv file with `--audio-file-auto=fuzzy` and `--sub-auto=fuzzy`. My observation is that audio tracks in the mka file are loaded correctly but no subtitle tracks can be seen.

The script is not perefect, because the order of lua script execution and external-file loading in mpv cannot be predicted. My script manually adds these mka files as sub-files. For some unknown reasons, if my script is executed before mpv loading the mka file as audio-files (driven by `audio-file-auto`), the mka file won't be loaded as audio-files anymore. Then in my script I add them back. If my script is executed later, then everything is okay. So one will observe inconsistent audio track orderings between different runs. Sometimes correct (same ordering as without my script) but sometimes wrong.

**Comment by kevmitch** [comment]
Does hooking `file-loaded` instead of `start-file` work any better? 

It looks like mpv will fuzzy load an .mka file as audio and an .mks file as subtitles but not the other way around. So the "solution" would be to try and fuzzy load any similarly named .mkX as audio and / or subtitles. Could that have surprising consequences?

**Comment by zc62** [comment]
Yes `file-loaded` works better. Thanks.

There are still minor bugs (depending on which flag I am using when execute `sub-add`). I think the `auto` flag is the one closest to correct, because at least it won't break `sid=no` (subtitle auto-load, but no auto-selection). But in this case even `sid` equals some language codes, nothing will be auto-selected when we only have subtitles from the mka file. Other two flags (`select` and `cached`), works in the previous case, but they do not work well when there are other external subtitle files. Subtitles in the mka file will be given the highest priority, even when `slang` should select another external sub-file.

I think fuzzy every mkX and load them as audio and sub-files should work, and may be easy to implement. But maybe it can be more efficient? I saw the demuxer could correctly show all of the tracks in the mka file when it is pulled by `--audio-file-auto`. Will it be more straightforward to add the subtitle tracks to track-list at that time, if they fulfill the `--sub-auto` requirement? `slang` and `sid` auto-selection take place afterwards, so that the auto-selection should work perfectly.

**Comment by wm4** [comment]
I think what you want is that it loads all streams from autoloaded files?

Could be done by removing the `filter` argument from `mp_add_external_file()` and everything it calls.

**Comment by zc62** [comment]
Yes, exactly.

**Comment by wm4** [comment]
See #5192.

**Comment by zc62** [comment]
Tested. It works!
