### ISSUE TITLE
Lua mp.get_property broken here

### ISSUE THREAD

**Issue by Q3CPMA** [mpv-player/mpv#5134]
### mpv version and platform
OS: Gentoo
Version: "0.27.0.2017.10.27" (also tested with 0.27)
I tested with both lua and luajit (just in case).
(I'm actually thinking that this may be a Gentoo bug, since it's too big to be from mpv)

### Reproduction steps
I'm trying to use use this lua script:
```
> cat .config/mpv/scripts/redshift_toggle.lua
-- Toggle redshift when opening/closing mpv

local prop = {"vid", "video", "video-format", "track-list/count",
    "current-vo","current-ao","vo-configured"}
for i=1, #prop
do
    mp.msg.log("info", prop[i] .. " = " .. mp.get_property(prop[i], "nil"))
end

-- if mp.get_property("vo-configured") == "yes"
-- then
--  os.execute("pkill -x -USR1 redshift")
--
--  mp.register_event("shutdown",
--      function(event) os.execute("pkill -x -USR1 redshift") end)
-- end
```

```
> mpv --no-config --script=.config/mpv/scripts/redshift_toggle.lua video.mkv 2>&1 | grep -F redshift_toggle
[redshift_toggle] vid = auto
[redshift_toggle] video = auto
[redshift_toggle] video-format = nil
[redshift_toggle] track-list/count = 0
[redshift_toggle] current-vo = nil
[redshift_toggle] current-ao = nil
[redshift_toggle] vo-configured = no
> mpv --no-config --script=.config/mpv/scripts/redshift_toggle.lua music.flac 2>&1 | grep -F redshift_toggle
[redshift_toggle] vid = auto
[redshift_toggle] video = auto
[redshift_toggle] video-format = nil
[redshift_toggle] track-list/count = 0
[redshift_toggle] current-vo = nil
[redshift_toggle] current-ao = nil
[redshift_toggle] vo-configured = no
```

### Expected behavior

"Proper" properties. At least `vo-configured` returning yes when there's some video.

### Actual behavior

See steps.

### Log file

Video: https://files.catbox.moe/vcgc3s.log
Music: https://files.catbox.moe/i2bz4m.log

### Sample files

Works with any file with and without a video track.

**Comment by Q3CPMA** [comment]
False alarm. I wrongly thought that scripts started after the vo configuration. It might still be a good idea in the lua doc to say that the `file-loaded` event happens before vo config (so you shoukld use `video` instead of `vo-configured` to know if there's a window).

**Comment by Argon-** [comment]
Plenty of properties are asynchronous so it's wrong to assume any order as guaranteed in the first place. 
For me, vo-configured works as a "does a window exist" indicator. The video property is definitely not sufficient to indicate this.

**Comment by avih** [comment]
> Plenty of properties are asynchronous

Properties are fully synchronous. Don't spread FUD.

**Comment by Argon-** [comment]
You are refering to the retrieval of properties, I'm not. 
I'm trying to say you cannot define an order like "file-loaded event will always happen before x" and assume it will hold true. There's only a very limited amount of x in this special case and there might be none in others.

**Comment by avih** [comment]
To be more clear:
- all the get_property* and set_property* functions are fully synchronous and happen right away.
- All messages from the core to the client (i.e. the script in this case) are a-synchronous and go through the client's queue.
- All messages arrive to the client in the exact order they were sent.
- Messages include events, key presses, script messages, and also messages for property observers.

So a function which registers to be notified when a property value changes will indeed be called a bit later than when it actually changed, and also depends on how many events are queued before it (though I still haven't encountered a reasonable use case where the queue depth is non negligible).

It is true that you cannot control order of things which the core player manages, but other than this, property access is with get/set is always synchronous, and events which the core sent don't arrive in random order to the client but rather exactly at the order they were sent in.

**Comment by Argon-** [comment]
Yes but, again, we are not taking about the retrieval of properties (or are we?) but rather the "order of things" withing the player.

**Comment by avih** [comment]
The only thing I said was that "Plenty of properties are asynchronous" is, at the very least, a very misleading statement. Nothing else, nothing more.
