### ISSUE TITLE
Manual doesn't clarify if --icc-profile-auto is safe to use under WMs with colour management

### ISSUE THREAD

**Issue by v-fox** [mpv-player/mpv#5136]
[Gentoo says](https://wiki.gentoo.org/wiki/Color_management#mpv) that mpv doesn't inform WM's about its colour space even when it's doing colour management which may lead to double conversion and spoiled results. Because of that I keep that option disabled while using kwin under Linux. But is it really true ? And is disabling it any better than not in such case ? Manual should clarify, I think.

**Comment by haasn** [comment]
Have you tried testing it? I don't use a compositor that does color management so I'm afraid I can't offer much advice.

**Comment by v-fox** [comment]
I'm not sure what would be good visual for testing. My display is A-MVA+-based BenQ GW2270 with slight (like 5-7%) shift from sRGB and 3000 contrast, ICC profile is made by ArgyllCMS/displaycal from which mpv doesn't seem to get contrast and complains. I'm not sure how double conversion glitch would even look like.

But for a developer it should be easy to find out if this "will not tag the surface appropriately" claim is true, at least.

**Comment by haasn** [comment]
You can try using a fictional ICC profile like one that swaps the R/G/B channels, or an extremely wide gamut one like ProPhotoRGB. Those types of profiles should make double vs single application pretty obvious to discern visually.

> But for a developer it should be easy to find out if this "will not tag the surface appropriately" claim is true, at least.

I have no idea what “surface” means in this context

**Comment by v-fox** [comment]
> You can try using a fictional ICC profile like one that swaps the R/G/B channels, or an extremely wide gamut one like ProPhotoRGB. Those types of profiles should make double vs single application pretty obvious to discern visually.

Surprisingly for me, I had ProPhotoRGB and SwappedRedAndGreen installed. The second one is more obvious, so I tried setting it up as screen's profile in kwin's settings. Then I tried mpv with `--icc-profile-auto` and with `--icc-profile-auto --icc-profile=/usr/share/color/icc/colord/SwappedRedAndGreen.icc`. Results seem to be the same for both cases, and equal to when screen's profile is correct. Only difference is in case of SwappedRedAndGreen as screen's profile then mpv gives out swapped colours with `--icc-profile-auto` alone, which is exactly what's expected.

If there were double conversion then putting SwappedRedAndGreen for screen and into mpv would result in non-swapped picture, right ? That didn't happen. So, I guess, everything is fine.

> I have no idea what “surface” means in this context

As far as you know, mpv's colour correction is complete, right, no reason to worry ?
Then you can safely add "can be used with colour-correcting WM's" or something to `--icc-profile-auto`'s description to get rid of ambiguity.
And I think I will add it by default now.

**Comment by haasn** [comment]
> If there were double conversion then putting SwappedRedAndGreen for screen and into mpv would result in non-swapped picture, right ? That didn't happen. So, I guess, everything is fine.

Yes. I don't understand your other comments though. Didn't you say that it was equal to when the screen's profile is correct? And you seemed to contradict yourself about what happens with `---icc-profile-auto`.

**Comment by v-fox** [comment]
> Yes. I don't understand your other comments though. Didn't you say that it was equal to when the screen's profile is correct? And you seemed to contradict yourself about what happens with ---icc-profile-auto.

I meant "equal" in a sense that colours were swapped in all cases but one: when correct profile used for screen and `--icc-profile-auto` alone is used in mpv. It didn't seem to matter if incorrect profile is used alone on screen, alone in mpv or in both. Not counting mpv's correction being completely disabled, I didn't try that as it doesn't matter.

**Comment by haasn** [comment]
> Not counting mpv's correction being completely disabled, I didn't try that as it doesn't matter.

That would actually be an interesting test. If you set the swapped RGB profile in your compositor, and disable mpv's color management, are the colors swapped or not?

If they aren't, then the compositor is clearly not applying color management to mpv in the first place.

**Comment by v-fox** [comment]
> That would actually be an interesting test. If you set the swapped RGB profile in your compositor, and disable mpv's color management, are the colors swapped or not?
> 
> If they aren't, then the compositor is clearly not applying color management to mpv in the first place.

Indeed. In that case (`--icc-profile-auto=no`) colours are NOT swapped.
But is compositor supposed to ignore apps that don't announce their profiles or treat them as sRGB ? I know that KDE apps do have correction with kwin but I'm not sure if that's what they do themselves or if it's kwin at work. I reopened Firefox after changing colour profile. Googled up [this page](https://forums.adobe.com/thread/1183489) and [it says "red" where's green and "green" where's red](https://forums.adobe.com/servlet/JiveServlet/showImage/2-5201265-315432/png-color-profile-test.png), Adobe logo became green. Meaning it does work for FF which supposed to have colour correction. But then again, it probably works just like mpv.

**Comment by haasn** [comment]
Well it would be news to me that any compositor applies color management to begin with. (Actually I think OS X does this in some circumstances?)

**Comment by v-fox** [comment]
> Well it would be news to me that any compositor applies color management to begin with. (Actually I think OS X does this in some circumstances?)

To be honest, it's kind of ambiguous. In KDE4 there were a clear option for kwin's CC. It's still shown in documentation [like that](https://userbase.kde.org/Color_Management/en#How_to_enable_color_correction_in_KDE). But then it used Oyranos and now, with 5, it's colord with built-in KDE's own configuration menu. kwin doesn't have that option listed explicitly but I think I saw somewhere that it's enabled when OpenGL 3.1 (highest of XRender, OpenGL 2.0 and 3.1 options) is selected as kwin's backend. There was whole song and dance when they've added it and now - only mystery.

**Comment by Akemi** [comment]
> Well it would be news to me that any compositor applies color management to begin with. (Actually I think OS X does this in some circumstances?)

one can for example attach a colorspace (Profile) to a CAOpenGLLayer to tag the drawn content and as far as i understood it will convert it to the displays color space. in case of both being the same or nil it is a noop.

**Comment by v-fox** [comment]
> one can for example attach a colorspace (Profile) to a CAOpenGLLayer to tag the drawn content and as far as i understood it will convert it to the displays color space. in case of both being the same or nil it is a noop.

I just though: doesn't that mean that mpv should always expose colour profile (source one, if there is no target) even if it isn't doing conversion itself ?

**Comment by haasn** [comment]
> I just though: doesn't that mean that mpv should always expose colour profile (source one, if there is no target) even if it isn't doing conversion itself ?

Sure
