### ISSUE TITLE
[libmpv]: When call mpv_opengl_cb_uninit_gl, all clients became black window 

### ISSUE THREAD

**Issue by CodeEagle** [mpv-player/mpv#5137]
### 1.25.0

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Sample files

Using libmpv to create cocoa OSX application, multiple clients create from `mpv_create`, and has it's own handler from `mpv_get_sub_api`.

When close a window, then call `mpv_opengl_cb_uninit_gl`, all other window become black window

**Comment by CodeEagle** [comment]
Logic in macOS app`IINA` is keep all referees of create mpv instance and clear it when `IINA` terminate. question is why can not manager each mpv OpenGL callback independent?

**Comment by Dudemanguy** [comment]
This API was deprecated and recently removed completely.
