### ISSUE TITLE
The SUP font size is too small when using blend-subtitles=yes with 1920x800 resolution in fullscreen

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5138]
Is there any way to make `stretch-image-subs-to-screen` work with `blend-subtitles`?
@dragons4life 
Video resolution: 1920x800
The SUP font size is too small with `blend-subtitles`:
![deepin _20171125155507](https://user-images.githubusercontent.com/20014762/33228546-06ad35da-d1f9-11e7-94a7-d2bf6587ca14.png)

The font size is normal with `stretch-image-subs-to-screen` and without `blend-subtitles`:
![deepin _20171125155706](https://user-images.githubusercontent.com/20014762/33228566-549d1e04-d1f9-11e7-81e7-acc3801d6e4c.png)
### mpv version and platform
```
mpv 0.27.0-396-g007cd24c2b (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 12 12:13:07 CST 2017
ffmpeg library versions:
   libavutil       56.0.100
   libavcodec      58.2.100
   libavformat     58.2.100
   libswscale      5.0.101
   libavfilter     7.0.101
   libswresample   3.0.101
ffmpeg version: N-88710-gaeed5ecdb3
```
### Reproduction steps
blend-subtitles=yes
### Expected behavior
The SUP subtitle font size is bigger
### Actual behavior
It is small

**Comment by dragons4life** [comment]
I suggest you post some pictures as examples

**Comment by JulianLai** [comment]
ideal font size:

![deepin _20171123212247](https://user-images.githubusercontent.com/20014762/33174811-7faa78c8-d094-11e7-8155-b91bec50681b.png)
blend-subtitles:
![deepin _20171123212207](https://user-images.githubusercontent.com/20014762/33174837-91897c92-d094-11e7-968c-3cdcf455bb60.png)

**Comment by JulianLai** [comment]
@dragons4life The sub-font-size won't work with sup when using blend-subtitles
![deepin _20171125155507](https://user-images.githubusercontent.com/20014762/33228546-06ad35da-d1f9-11e7-94a7-d2bf6587ca14.png)

**Comment by zc62** [comment]
I think it is not:

> The font size is normal with `stretch-image-subs-to-screen` and without `blend-subtitles`

but:
The font size is abnormally large with `stretch-image-subs-to-screen` and normal with `blend-subtitles`.

You are using a SUP subtitle designed for 1920x1080 resolution. It should work as it is intended to be with a 1920x1080 video. But when you force it to work with a 1920x800 video, it must shrink to fit the 800 vertical resolution. `blend-subtitles` is working fine, as it is designed to. `stretch-image-subs-to-screen` actually displays the subtitle incorrectly. It just looks "correct" in this very special case.

I would suggest you either modify the SUP subtitle to fit 1920x800 resolution or add the black bars back to your video to make it 1920x1080.

**Comment by kevmitch** [comment]
> I would suggest you either modify the SUP subtitle to fit 1920x800 resolution 

This is probably the best solution. I recently used [BDSup2Sub](https://github.com/mjuhasz/BDSup2Sub) for exactly this.

**Comment by lachs0r** [comment]
Note: There is https://github.com/amichaelt/BDSup2SubPlusPlus

**Comment by lachs0r** [comment]
In any case, this is working as intended, since this is cropped video. Of course blending the subtitles intended for a larger frame size with a cropped video will end up downscaling them.
