### ISSUE TITLE
glsl-shaders option not documented?

### ISSUE THREAD

**Issue by fhlfibh** [mpv-player/mpv#5142]
Hi,

As far as I remember, man page had some explanations about `glsl-shaders` option (about `-append`, `-clr`, etc). 
Now I can't find anything of it in DOCS files.
Is it gone? Did `shaders` options change again?

Regards,
Alex

**Comment by CrisBRM** [comment]
What are you talking about? https://mpv.io/manual/master/

**Comment by fhlfibh** [comment]
https://mpv.io/manual/master/
https://github.com/mpv-player/mpv/tree/master/DOCS

**Comment by CrisBRM** [comment]
Yeah? They're all there.

**Comment by fhlfibh** [comment]
Yup, found it in mpv.rst
