### ISSUE TITLE
mpv crashes on panscan 0.100 in fullscreen mode

### ISSUE THREAD

**Issue by TiGR** [mpv-player/mpv#5150]
### mpv version and platform

```
$ mpv -V
mpv git-2017-11-19-4569f39 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Tue Nov 21 00:26:19 UTC 2017
ffmpeg library versions:
   libavutil       56.0.100
   libavcodec      58.4.102
   libavformat     58.2.100
   libswscale      5.0.101
   libavfilter     7.1.100
   libswresample   3.0.101
ffmpeg version: ffmpeg-mpv-git-2017-11-19-37e0c9f
$ cat /etc/os-release
NAME="KDE neon LTS"
VERSION="5.8"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon LTS User Edition 5.8"
VERSION_ID="16.04"
HOME_URL="http://neon.kde.org/"
SUPPORT_URL="http://neon.kde.org/"
BUG_REPORT_URL="http://bugs.kde.org/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

### Reproduction steps

1. Playing 1424×1080 video on 1920×1080 screen in fullscreen mode ([this](https://rutracker.org/forum/viewtopic.php?t=4964798) one).
2. Press `e` to increase panscan.

### Expected behavior

Increase panscan, continue playback zoomed.

### Actual behavior

mpv crashes.

If you increase panscan past 0.1 to, say, 0.2 in windowed (not fullscreen) mode then you can go to fullscreen and it won't crash. You can then continue increasing it without any problems. But if you reduce it back to 0.1 it crashes.

### Log file

https://pastebin.com/Yk3U6erj

### Sample files

See above (there is magnet link also).

**Comment by TiGR** [comment]
BTW, log misses the error message that mpv spits out on crash:

    mpv: i965_post_processing.c:2740: pp_nv12_avs_initialize: Assertion `out_w <= out_wpitch && out_h <= out_hpitch' failed.

**Comment by wm4** [comment]
Why are you using this garbage VO?

**Comment by wm4** [comment]
Can you answer the question? The VO is pretty bad because it's limited by Intel's bad API, which is not just bad, but obviously also buggy and semi-unmaintained (I'm pretty sure this bug is Intel's). It's legacy API, and I'm thinking of removing this VO entirely. There shouldn't even be a need for it.

**Comment by TiGR** [comment]
Well, it is supposed to be native way to display video, using hardware acceleration for video rendering (that includes "free" high quality video scaler). The difference is really noticeable: you either view video in complete silence or you hear your computer's cooling system. And it also affects battery life. Most of time it works ok. Also, i've never had crashes like this before for years using mpv.

So, for me it is not garbage at all.

**Comment by thebombzen** [comment]
You should instead use OpenGL (or Vulkan) and enable VAAPI hardware decoding using the `--hwdec` options. The OpenGL video renderer does everything on the GPU, and if you use `--hwdec=vaapi` it'll hardware-decode directly to a GPU texture. This is what you're looking for.

There's a reason the documentation recommends against this VO.

**Comment by TiGR** [comment]
I was comparing video outputs only, when hardware decoder was used in both cases. See [this comment](https://github.com/mpv-player/mpv/issues/2109#issuecomment-118848932).

**Comment by wm4** [comment]
Well, the only way to get this functionality back is via wayland (using yuv surface support). Not sure if anyone is interested in implementing it. I'll probably let vo_vaapi.c bitrot some more, but eventually it'll go away.
