### ISSUE TITLE
Cursor doesn't autohide when going full screen, if pointer is outside video window.

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#5151]
### mpv version and platform
mpv 0.25.0 to 0.27.0
macOS 10.12.6

### Reproduction steps
Case 1:
1. With mpv 0.25.0 or later, not using any scripts or mpv.conf options, double-click on a video file to open it.
2. Move the mouse pointer cursor outside of the video window so that it remains visible.
3. Press `f` to go fullscreen.

Case 2:
1. With mpv 0.25.0 or later, put `fs` in the mpv.conf file, and put autodeint.lua in scripts folder.
2. Move the window containing the video file so that its icon is outside where the non-fullscreen video window would be.
3. Double-click the file to open it.

### Expected behavior
As in 0.24.0, the cursor should automatically hide when entering fullscreen.

### Actual behavior
Cursor remains visible.
Using `no-native-fs` makes no difference.
Rapidly pressing `f` repeatedly will sometimes hide the cursor, maybe related to the cursor-autohide timeout value.

### Log file

Case 1: http://sprunge.us/jiWD
Case 2: http://sprunge.us/cQBT
Case 2 (without autodeint.lua installed, works ok): http://sprunge.us/RhQa

**Comment by Akemi** [comment]
i fixed case 1 in #4833 just now. case 2 is not present in #4833.

**Comment by Akemi** [comment]
fixed via c5e4538bc4b63f02bf89f62aa25a37b9eb0c0316.
