### ISSUE TITLE
[macOS] OSD doesn't autohide after exiting native fullscreen and moving cursor out of window.

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#5152]
### mpv version and platform
mpv 0.27.0
macOS 10.12.6

### Reproduction steps
1.  Without using any scripts or mpv.conf options, double-click on a video file to open it.
2. Press `f` to enter fullscreen.
2. Move the mouse pointer to the center of the screen.
3. Press `f` to exit fullscreen again.
4. Move the mouse pointer out of the video window, downwards through the bottom of the window, so that it passes through the OSD.

### Expected behavior
When the mouse pointer leaves the window, the OSD should auto-hide.

### Actual behavior
The OSD remains visible.
If `no-native-fs` is added to mpv.conf, the OSD auto-hides as expected.

### Log file
http://sprunge.us/MIMi

**Comment by Akemi** [comment]
i can reproduce. the bug is not present in #4833.

**Comment by Akemi** [comment]
fixed via c5e4538bc4b63f02bf89f62aa25a37b9eb0c0316.
