### ISSUE TITLE
Crash on opening 2nd movie, macOS

### ISSUE THREAD

**Issue by dm5n** [mpv-player/mpv#5153]
### Reproduction steps

> Open a movie file and play > pause and minimise the window

> Open Finder select another movie and play with mpv

### Expected behavior

Selected movie should play and minimised movie should stay minimised or close 

### Actual behavior

2nd mpv icon appears, bounces in dock then stops. Force Quit doesn't quit the app.

**Comment by Akemi** [comment]
has already been fixed. duplicate of #4926 and many more.
