### ISSUE TITLE
Taking a screenshot with OSD displayed

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#5154]
I would like to take a screenshot with OSD displayed (so that the timecode is visible). I tried searching through the docs but that does not seem possible. Would it be possible to add it? If it is possible, how can one enable it? There do not seem to be any suitable options here: https://mpv.io/manual/stable/#screenshot

**Comment by garoto** [comment]
It's `ctrl+s` by default. But in any case in input.conf:

<keybind> async screenshot window

**Comment by felagund** [comment]
Ah, I see, was taking into the wrong part of documentation.

**Comment by garoto** [comment]
Yeah, it's in section named "List of Input Commands" under "Command Interface".
