### ISSUE TITLE
The color is different with vaapi

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5157]
Look at the skin color
default:
![default](https://user-images.githubusercontent.com/20014762/33357773-5980cd54-d4ff-11e7-88c4-90c08bdf6ffb.png)
vaapi (strange):
![ravu with vaapi](https://user-images.githubusercontent.com/20014762/33357775-59ed86ba-d4ff-11e7-836e-032b4365d243.png)

### mpv version and platform
```
mpv 0.27.0-396-g007cd24c2b (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 12 12:13:07 CST 2017
ffmpeg library versions:
   libavutil       56.0.100
   libavcodec      58.2.100
   libavformat     58.2.100
   libswscale      5.0.101
   libavfilter     7.0.101
   libswresample   3.0.101
ffmpeg version: N-88710-gaeed5ecdb3
```
### Reproduction steps
Play video
### Expected behavior
Same color with vaapi-copy and no hwdec
### Actual behavior
color is different
### Log file
[mpv.log.zip](https://github.com/mpv-player/mpv/files/1512522/mpv-ravu.log.zip)

**Comment by lachs0r** [comment]
This is explained in the “Quality reduction with hardware decoding” note in the manual: https://mpv.io/manual/master/#options-hwdec

Nothing we can do about that. That’s just how these APIs work.
