### ISSUE TITLE
frame drops for the 4K HEVC HDR video with vaapi-copy and cpu decoding, but smooth with vaapi

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5160]
### mpv version and platform
```
mpv 0.27.0-396-g007cd24c2b (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 12 12:13:07 CST 2017
ffmpeg library versions:
   libavutil       56.0.100
   libavcodec      58.2.100
   libavformat     58.2.100
   libswscale      5.0.101
   libavfilter     7.0.101
   libswresample   3.0.101
ffmpeg version: N-88710-gaeed5ecdb3
```
### Reproduction steps
play 4K HEVC 10bit HDR video
### Expected behavior
smooth
### Actual behavior
not smooth
### Log file
[HDR.log.zip](https://github.com/mpv-player/mpv/files/1512728/HDR.log.zip)

**Comment by thebombzen** [comment]
It sounds like your system probably is too slow to CPU decode HEVC or copy it to/from the GPU with `-copy` in realtime. This doesn't sound like a bug.

**Comment by JulianLai** [comment]
@thebombzen What CPU do we need to play 4K HDR video smoothly?

**Comment by JulianLai** [comment]
@thebombzen @lachs0r the frame timings is low, but still lots of frame drops
![deepin _20171213223123](https://user-images.githubusercontent.com/20014762/33943888-5fb943a2-e055-11e7-807f-7798854e79c0.png)

**Comment by lachs0r** [comment]
Those frame timings are too high for smooth 60 fps.
