### ISSUE TITLE
Chroma is displayed one pixel down from where it should be in a png screenshot

### ISSUE THREAD

**Issue by YaLTeR** [mpv-player/mpv#5162]
### mpv version and platform

```
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Nov  3 14:10:56 CET 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4
```

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Source files: [RGB](https://my.mixtape.moe/xaerdr.mp4), [YUV444P](https://my.mixtape.moe/ercswh.mp4).

Open RGB and YUV444P and take png screenshots. Look at the bottom left corner. You'll see [this](http://screenshotcomparison.com/comparison/125056).

Now, `ffmpeg -i yuv444p.mp4 444.png` and compare with that. You'll see [this](http://screenshotcomparison.com/comparison/125058).

As you can see, mpv seems to display chroma one pixel down from where it should be.

### Expected behavior
Chroma being where it should be.

### Actual behavior
Chroma is one pixel down.

### Log file
http://sprunge.us/Cdfd

### Sample files
Source files: [RGB](https://my.mixtape.moe/xaerdr.mp4), [YUV444P](https://my.mixtape.moe/ercswh.mp4).

**Comment by haasn** [comment]
Seems to work for me

**Comment by YaLTeR** [comment]
Huh. After a couple of tests, seems to only show up on the png screenshot (taken with the `s` button), and not on the actual playback (if I screenshot it with some screenshot tool).

**Comment by haasn** [comment]
When you take a regular screenshot (with ‘s’ or ‘S’), it doesn't go through the mpv renderer, but through **libswscale**, which is a known piece of shit. Sounds like swscale can't handle 4:4:4 chroma offsets correctly or something.

**Comment by wm4** [comment]
That's correct. Suggestions welcome.

**Comment by YaLTeR** [comment]
I have no idea about mpv's structure, but perhaps it's possible to go through the mpv renderer and then `glReadPixels`/do something similar for the screenshot?

**Comment by thebombzen** [comment]
You can already hit `Ctrl+s` to take a screenshot from mpv's renderer. 

Either way, could this potentially be fixed with the `sws_flags` named `full_chroma_int`?

**Comment by haasn** [comment]
> Also if it's a bug in swscale then how does ffmpeg -i yuv444p.mp4 444.png work correctly?

If that works correctly, then it's possible that there's an issue with the way metadata is passed between ffmpeg and mpv and back. Like, maybe the chroma metadata gets dropped somewhere.

**Comment by Akemi** [comment]
stale issue. also we have screenshots rendered on the gpu now.
