### ISSUE TITLE
It hangs when opening second MPV instance on macOS

### ISSUE THREAD

**Issue by aitt** [mpv-player/mpv#5163]
### mpv version and platform

mpv: 0.27.0
https://mpv.io/
/usr/local/Caskroom/mpv/0.27.0 (64B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/mpv.rb

### Reproduction steps
1. Play movie-1 by click it
2. When movie-1 is playing, click movie-2, there will open a 2nd instance of MPV
3. The 2nd instance keeps hang, not play anything, cannot be closed, cannot be force closed, no response
4. It even cause the OS cannot reboot unless power recycle the machine

### Expected behavior
1. Should not hang at least
2. Ideally there should be no 2nd instance, the expected behavior should be closing movie-1 and loading movie-2 and play it

### Log file
It's very easy to reproduce

**Comment by AirPort** [comment]
Known issue, already fixed in git master: https://github.com/mpv-player/mpv/issues/4926

**Comment by aitt** [comment]
Thank you for your response.
I didn't realize there's a similar issue opened already, which's been fixed back at Oct 3.
BTW, mpv in brew cask has not yet been updated since Sep 23.

**Comment by Akemi** [comment]
we are not responsible for brew. they probably didn't update it yet because there hasn't been a new release since then, so there is 'nothing' to update.

**Comment by aitt** [comment]
Thank you.
How can I get the latest mpv on macOS?
Pull the code from GitHub, and build it?

**Comment by thebombzen** [comment]
Well that would be one way. Another way would be to download it prebuilt from [https://mpv.io/installation/](https://mpv.io/installation/).

**Comment by aitt** [comment]
Thank you,  @thebombzen .
I installed the Homebrew one.
Do you know why it doesn't generate a link under /Applications?
That means I cannot associate media files with mpv thus cannot play a movie by just clicking it, the only way is to start mpv from command line.

**Comment by Akemi** [comment]
the homebrew one is also only 0.27, you would need to install it withe the `--HEAD`
 option, though that might fail currently because of other reasons. also if you want an app bundle wich is also linked to you Application folder you have to install it with the `--with-bundle` option.
