### ISSUE TITLE
(feature) Option to scale the window based on % of the screen size instead of video

### ISSUE THREAD

**Issue by 1ll3g4l** [mpv-player/mpv#5167]

**Comment by kevmitch** [comment]
[`--autofit=50%`](https://mpv.io/manual/stable/#options-autofit)

**Comment by 1ll3g4l** [comment]
@kevmitch Can't be bind-able, at least on windows 10.

**Comment by Argon-** [comment]
Yes, similar to the geometry option, they only work on startup and can't be changed during runtime (well, you can change them but nothing happens)

**Comment by 1ll3g4l** [comment]
@kevmitch @Argon- Can this issue be re-opened or not? @Argon- this also happens on linux/osx for you?
