### ISSUE TITLE
Vsync-Jitter increases a lot when loading subtitles with both vaapi-copy and vd-lavc-dr are enabled

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5169]
### mpv version and platform
```
mpv 0.27.0-446-g643a1fc7de-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.3.100
   libavcodec      58.6.102
   libavformat     58.2.103
   libswscale      5.0.101
   libavfilter     7.5.100
   libswresample   3.0.101
ffmpeg version: N-89366-g65b5fcfbe2
```
### Reproduction steps
`--hwdec=vaapi-copy`
`--vd-lavc-dr=yes`
### Expected behavior
low vsync-jitter all the time
### Actual behavior
vsync-jitter goes up frequently
### Log file
[(vaapi-copy)+(vd-lavc-dr).log.zip](https://github.com/mpv-player/mpv/files/1523407/vaapi-copy.vd-lavc-dr.log.zip)
[mpv.conf.zip](https://github.com/mpv-player/mpv/files/1523422/mpv.conf.zip)

**Comment by lachs0r** [comment]
Why do you keep reporting vaapi driver issues to us?
