### ISSUE TITLE
There is no option to enable vaapi for AMDGPU

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5170]
It seems like mpv doesn't support the vaapi-glx anymore?
Shouldn't the vaapi work with vaapi-egl?
libva: 2.0.0-2
libva-mesa-driver: 17.2.6-1
### mpv version and platform
```
mpv 0.27.0-446-g643a1fc7de-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.3.100
   libavcodec      58.6.102
   libavformat     58.2.103
   libswscale      5.0.101
   libavfilter     7.5.100
   libswresample   3.0.101
ffmpeg version: N-89366-g65b5fcfbe2
```
### Reproduction steps
`--gpu-hwdec-interop=auto`
`--hwdec=vaapi`
### Expected behavior
vaapi enabled
### Actual behavior
```
[vo/gpu/drmprime-drm] Could not get drm interop info.
VO does not support requested hardware decoder, or loading it failed.
```
### Log file
[NoVaapiForAMDGPU.log.zip](https://github.com/mpv-player/mpv/files/1523526/NoVaapiForAMDGPU.log.zip)

**Comment by lachs0r** [comment]
vaapi-glx was dropped in commit c4372675189e2834bb39fb77fa0e214affcbdb36. vaapi-egl requires the EGL opengl backend. Looks like vo_gpu autoprobes glx first, so this is an inaccuracy in the manual.

Whether or not this works then depends on your drivers.

**Comment by wm4** [comment]
It only tries to use GLX if the GL context reports vdpau interop support. This will have to be worked around somehow once AMD supports vaapi-egl.

**Comment by JulianLai** [comment]
It is so unbelievable that how bad the AMD driver is.

**Comment by JulianLai** [comment]
They have sent a patch to libva, but it isn't included in libva2.0
