### ISSUE TITLE
Twitch issue

### ISSUE THREAD

**Issue by rend3r** [mpv-player/mpv#5172]
### mpv version and platform
mpv 0.27.0-407-gcd6f964b56-dirty (shinchiro)
built on Sun Nov 19 10:44:29 UTC 2017
ffmpeg library versions:
    libavutil       56.0.100
    libavcodec      58.4.103
    libavformat     58.2.100
    libswscale      5.0.101
    libavfilter     7.1.100
    libswresample   3.0.101
ffmpeg version: git-2017-11-18-936a4c04b
Windows 7 SP1 x64

### Reproduction steps
mpv https://www.twitch.tv/videos/205742060

Sometimes stream is played, sometimes does not
```
Playing: https://www.twitch.tv/videos/205742060
[cplayer] Running hook: ytdl_hook/on_load
[global] config path: 'youtube-dl' -/-> 'C:\Users\denis\AppData\Roaming/mpv/youtube-dl'
[global] config path: 'youtube-dl' -/-> 'D:/Program Files/MPV/youtube-dl'
[global] config path: 'youtube-dl' -/-> 'D:/Program Files/MPV/mpv/youtube-dl'
[ytdl_hook] youtube-dl succeeded!
[cplayer] Set property: file-local-options/user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)" -
> 1
[cplayer] Set property: stream-open-filename="https://fastly.vod.hls.ttvnw.net/50ddcfa4de8ea19c929c_quakechampions_26865506048_74776429
9/chunked/index-dvr.m3u8" -> 1
[cplayer] Set property: file-local-options/force-media-title="Day 1 - Quake Champions Invitational at DreamHack Winter 2017" -> 1
[ytdl_hook] adding subtitle [rechat]
[cplayer] Run command: sub-add, flags=0, args=[https://rechat.twitch.tv/rechat-messages?video_id=v205742060&start=1512116308, auto, jso
n, rechat]
[ffmpeg] Opening https://rechat.twitch.tv/rechat-messages?video_id=v205742060&start=1512116308
[ffmpeg] tcp: Failed to resolve hostname rechat.twitch.tv: No address associated with hostname
Failed to open https://rechat.twitch.tv/rechat-messages?video_id=v205742060&start=1512116308.
Can not open external file https://rechat.twitch.tv/rechat-messages?video_id=v205742060&start=1512116308.
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[ffmpeg] Opening https://fastly.vod.hls.ttvnw.net/50ddcfa4de8ea19c929c_quakechampions_26865506048_747764299/chunked/index-dvr.m3u8
[ffmpeg] tls: Creating security context failed (0x80090302)
Failed to open https://fastly.vod.hls.ttvnw.net/50ddcfa4de8ea19c929c_quakechampions_26865506048_747764299/chunked/index-dvr.m3u8.
[cplayer] Opening failed or was aborted: https://fastly.vod.hls.ttvnw.net/50ddcfa4de8ea19c929c_quakechampions_26865506048_747764299/chu
nked/index-dvr.m3u8
[cplayer] finished playback, loading failed (reason 4)
```

But mostly hanging after this step:
```
Playing: https://www.twitch.tv/videos/205742060
[cplayer] Running hook: ytdl_hook/on_load
[global] config path: 'youtube-dl' -/-> 'C:\Users\denis\AppData\Roaming/mpv/youtube-dl'
[global] config path: 'youtube-dl' -/-> 'D:/Program Files/MPV/youtube-dl'
[global] config path: 'youtube-dl' -/-> 'D:/Program Files/MPV/mpv/youtube-dl'
[ytdl_hook] youtube-dl succeeded!
[cplayer] Set property: file-local-options/user-agent="Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20150101 Firefox/47.0 (Chrome)" -
> 1
[cplayer] Set property: stream-open-filename="https://vod034-ttvnw.akamaized.net/50ddcfa4de8ea19c929c_quakechampions_26865506048_747764
299/chunked/index-dvr.m3u8" -> 1
[cplayer] Set property: file-local-options/force-media-title="Day 1 - Quake Champions Invitational at DreamHack Winter 2017" -> 1
[ytdl_hook] adding subtitle [rechat]
[cplayer] Run command: sub-add, flags=0, args=[https://rechat.twitch.tv/rechat-messages?start=1512116308&video_id=v205742060, auto, jso
n, rechat]
[ffmpeg] Opening https://rechat.twitch.tv/rechat-messages?start=1512116308&video_id=v205742060
[ffmpeg] tcp: Failed to resolve hostname rechat.twitch.tv: No address associated with hostname
Failed to open https://rechat.twitch.tv/rechat-messages?start=1512116308&video_id=v205742060.
Can not open external file https://rechat.twitch.tv/rechat-messages?start=1512116308&video_id=v205742060.
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[ffmpeg] Opening https://vod034-ttvnw.akamaized.net/50ddcfa4de8ea19c929c_quakechampions_26865506048_747764299/chunked/index-dvr.m3u8
[ffmpeg] Mime-type: 'application/x-mpegURL'
[ffmpeg] Stream opened successfully.
[cache] Cache size set to 150000 KiB (75000 KiB backbuffer)
[demux] Trying demuxers for level=normal.
[lavf] Found 'hls,applehttp' at score=100 size=2048.
```
[mpv.log](https://github.com/mpv-player/mpv/files/1524616/mpv.log)

### mpv.conf, input.conf
[mpv.conf.log](https://github.com/mpv-player/mpv/files/1524610/mpv.conf.log)
[input.conf.log](https://github.com/mpv-player/mpv/files/1524611/input.conf.log)

**Comment by sfan5** [comment]
Sounds like something is wrong with TLS.
Which TLS library do shinchiro's builds use?

**Comment by shinchiro** [comment]
It's using schannel. Found out the hang because of schannel as it works fine with libressl. Weird enough as it always works fine with schannel before.

@rend3r You can download my latest today's build, built with libressl, which fixed this issue

**Comment by aufkrawall** [comment]
Noob question: Why not use GnuTLS or OpenSSL like in the build script for Linux?

**Comment by shinchiro** [comment]
Because of library's size. Gnutls depends on libgcrypt+gcrypt-error. Openssl is a big fatty. Compared to these two, libressl is a bit smaller than Openssl and doesn't depend on another libs

**Comment by rend3r** [comment]
@shinchiro Ok, the issue is eliminated.

Another rare issue happens to me - twitch play is suddenly stopping after while. The only sign is empty cache.

> (Paused) AV: 05:25:50 / 10:18:47 (52%) A-V:  0.000 Cache: 120s+101KB

And then cache goes to 0 sec and does not filling anymore until stream restart. I will provide more information with
`--msg-level=all=error,ffmpeg=trace,demux=trace,cache=trace,lavf=trace,vd=trace,ad=trace,ytdl_hook=trace`

**Comment by garoto** [comment]
Is the TCP socket still in a ESTABLISHED state when that happens?

**Comment by rend3r** [comment]
@garoto I'm not sure and now after your post I start thinking that socket is closed due PPPoE session reconnection. I will check with portmon if I could reproduce the hang.

**Comment by rend3r** [comment]
This log is not for the issue I've already mensioned but related to it
[twitch.zip](https://github.com/mpv-player/mpv/files/1537080/twitch.zip)
Before this line
`[  91.951][v][ffmpeg/demuxer] hls,applehttp: HLS request for url 'https://fastly.vod.hls.ttvnw.net/50ddcfa4de8ea19c929c_quakechampions_26865506048_747764299/chunked/3031.ts', offset 0, playlist 0`
I've just opened the stream, seeked over and paused it until cache filled to 120sec. After that, I've disconnected PPPoE connection and mpv tries got the chuncks until
`[ 105.920][e][ffmpeg] tcp: Failed to resolve hostname fastly.vod.hls.ttvnw.net: No address associated with hostname`
and gave up. At this moment cache filled for ~100 secs. I wait for 20 sec cache and bring PPPoE connection on. mpv spent this last 20 secs and closed the video windows. The previous described issue does not lead to windows closing - mpv hangs with last video frame until ctrl+C.

**Comment by rend3r** [comment]
Ok, I reproduce https://github.com/mpv-player/mpv/issues/5172#issuecomment-349759337
Cutted log [twitch2_trim.zip](https://github.com/mpv-player/mpv/files/1537714/twitch2_trim.zip)
symptoms:
empty cache
Video window is not closing. Playback is stoped.
Several (3 in my case) socket with CLOSE WAIT status.

**Comment by thebombzen** [comment]
Is this still an issue in mpv 0.28.0?

**Comment by kevmitch** [comment]
Note the above is with `--no-tls-verify`. It works with and with out `--tls-verify` on the [2017-12-29 shinchiro build](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20171229-git-d9ca235.7z/download) from around the same time. Maybe @lachs0r should just ditch schannel.

**Comment by Hrxn** [comment]
I think we had this discussion before, and I believe his response was something along the lines of, "rather fix any issues with SChannel first"..

**Comment by Traneptora** [comment]
What about now, is it still an issue?
