### ISSUE TITLE
Build error in Debian Buster when configured with --disable-gl

### ISSUE THREAD

**Issue by MrLeylo** [mpv-player/mpv#5174]
### mpv version and platform

mpv 0.27.0-9bbf8a

built on Sat Dec 3 11:39:00 CET 2017

### Reproduction steps

- Clone repo
- sudo ./waf configure --disable-gl
- sudo ./waf build

### Expected behavior

Build without issues

### Actual behavior

Error (status=1)

#### No verbose

[  1/194] Compiling version.sh
[194/194] Linking build/mpv
video/out/opengl/hwdec_drmprime_drm.c.19.o: In function `overlay_frame':
/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/../video/out/opengl/hwdec_drmprime_drm.c:117: undefined reference to `ra_gl_get'
/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/../video/out/opengl/hwdec_drmprime_drm.c:129: undefined reference to `mpgl_get_native_display'
/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/../video/out/opengl/hwdec_drmprime_drm.c:140: undefined reference to `mpgl_get_native_display'
video/out/opengl/hwdec_drmprime_drm.c.19.o: In function `init':
/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/../video/out/opengl/hwdec_drmprime_drm.c:215: undefined reference to `ra_gl_get'
/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/../video/out/opengl/hwdec_drmprime_drm.c:218: undefined reference to `mpgl_get_native_display'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)

#### Verbose

Waf: Entering directory `/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build'
[  1/194] Compiling version.sh
11:55:19 runner ' sh ../version.sh --cwd="/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv" --versionh="version.h" '
[194/194] Linking build/mpv
11:55:19 runner ['/usr/bin/cc', '-rdynamic', '-pthread', '-pthread', '-Wl,-z,noexecstack', '-pthread', '-pthread', '-pthread', '-pthread', '-rdynamic', '-pthread', '-pthread', '-pthread', '-Wl,-version-script', '-Wl,mpv.def', 'osdep/main-fn-unix.c.20.o', 'audio/aconverter.c.19.o', 'audio/audio.c.19.o', 'audio/audio_buffer.c.19.o', 'audio/chmap.c.19.o', 'audio/chmap_sel.c.19.o', 'audio/fmt-conversion.c.19.o', 'audio/format.c.19.o', 'audio/aframe.c.19.o', 'audio/decode/ad_lavc.c.19.o', 'audio/decode/ad_spdif.c.19.o', 'audio/decode/dec_audio.c.19.o', 'audio/filter/af.c.19.o', 'audio/filter/af_format.c.19.o', 'audio/filter/af_lavcac3enc.c.19.o', 'audio/filter/af_lavfi.c.19.o', 'audio/filter/af_lavrresample.c.19.o', 'audio/filter/af_scaletempo.c.19.o', 'audio/filter/tools.c.19.o', 'audio/out/ao.c.19.o', 'audio/out/ao_lavc.c.19.o', 'audio/out/ao_null.c.19.o', 'audio/out/ao_oss.c.19.o', 'audio/out/ao_pcm.c.19.o', 'audio/out/pull.c.19.o', 'audio/out/push.c.19.o', 'common/av_common.c.19.o', 'common/av_log.c.19.o', 'common/codecs.c.19.o', 'common/encode_lavc.c.19.o', 'common/common.c.19.o', 'common/tags.c.19.o', 'common/msg.c.19.o', 'common/playlist.c.19.o', 'common/recorder.c.19.o', 'common/version.c.19.o', 'demux/codec_tags.c.19.o', 'demux/cue.c.19.o', 'demux/demux.c.19.o', 'demux/demux_cue.c.19.o', 'demux/demux_disc.c.19.o', 'demux/demux_edl.c.19.o', 'demux/demux_lavf.c.19.o', 'demux/demux_mf.c.19.o', 'demux/demux_mkv.c.19.o', 'demux/demux_mkv_timeline.c.19.o', 'demux/demux_null.c.19.o', 'demux/demux_playlist.c.19.o', 'demux/demux_raw.c.19.o', 'demux/demux_rar.c.19.o', 'demux/demux_timeline.c.19.o', 'demux/ebml.c.19.o', 'demux/packet.c.19.o', 'demux/timeline.c.19.o', 'input/cmd_list.c.19.o', 'input/cmd_parse.c.19.o', 'input/event.c.19.o', 'input/input.c.19.o', 'input/ipc.c.19.o', 'input/ipc-unix.c.19.o', 'input/keycodes.c.19.o', 'misc/bstr.c.19.o', 'misc/charset_conv.c.19.o', 'misc/dispatch.c.19.o', 'misc/json.c.19.o', 'misc/node.c.19.o', 'misc/ring.c.19.o', 'misc/rendezvous.c.19.o', 'misc/thread_pool.c.19.o', 'options/m_config.c.19.o', 'options/m_option.c.19.o', 'options/m_property.c.19.o', 'options/options.c.19.o', 'options/parse_commandline.c.19.o', 'options/parse_configfile.c.19.o', 'options/path.c.19.o', 'player/audio.c.19.o', 'player/client.c.19.o', 'player/command.c.19.o', 'player/configfiles.c.19.o', 'player/external_files.c.19.o', 'player/loadfile.c.19.o', 'player/main.c.19.o', 'player/misc.c.19.o', 'player/lavfi.c.19.o', 'player/javascript.c.19.o', 'player/osd.c.19.o', 'player/playloop.c.19.o', 'player/screenshot.c.19.o', 'player/scripting.c.19.o', 'player/sub.c.19.o', 'player/video.c.19.o', 'stream/cache.c.19.o', 'stream/cache_file.c.19.o', 'stream/cookies.c.19.o', 'stream/rar.c.19.o', 'stream/stream.c.19.o', 'stream/stream_avdevice.c.19.o', 'stream/stream_edl.c.19.o', 'stream/stream_file.c.19.o', 'stream/stream_cb.c.19.o', 'stream/stream_lavf.c.19.o', 'stream/stream_memory.c.19.o', 'stream/stream_mf.c.19.o', 'stream/stream_null.c.19.o', 'stream/stream_rar.c.19.o', 'sub/ass_mp.c.19.o', 'sub/dec_sub.c.19.o', 'sub/draw_bmp.c.19.o', 'sub/img_convert.c.19.o', 'sub/lavc_conv.c.19.o', 'sub/osd.c.19.o', 'sub/osd_libass.c.19.o', 'sub/sd_ass.c.19.o', 'sub/sd_lavc.c.19.o', 'sub/filter_sdh.c.19.o', 'video/csputils.c.19.o', 'video/fmt-conversion.c.19.o', 'video/image_loader.c.19.o', 'video/image_writer.c.19.o', 'video/img_format.c.19.o', 'video/hwdec.c.19.o', 'video/mp_image.c.19.o', 'video/mp_image_pool.c.19.o', 'video/sws_utils.c.19.o', 'video/decode/dec_video.c.19.o', 'video/decode/vd_lavc.c.19.o', 'video/filter/refqueue.c.19.o', 'video/filter/vf.c.19.o', 'video/filter/vf_buffer.c.19.o', 'video/filter/vf_convert.c.19.o', 'video/filter/vf_format.c.19.o', 'video/filter/vf_lavfi.c.19.o', 'video/filter/vf_sub.c.19.o', 'video/out/aspect.c.19.o', 'video/out/bitmap_packer.c.19.o', 'video/out/dither.c.19.o', 'video/out/filter_kernels.c.19.o', 'video/out/gpu/context.c.19.o', 'video/out/gpu/hwdec.c.19.o', 'video/out/gpu/lcms.c.19.o', 'video/out/gpu/osd.c.19.o', 'video/out/gpu/ra.c.19.o', 'video/out/gpu/spirv.c.19.o', 'video/out/gpu/shader_cache.c.19.o', 'video/out/gpu/user_shaders.c.19.o', 'video/out/gpu/utils.c.19.o', 'video/out/gpu/video.c.19.o', 'video/out/gpu/video_shaders.c.19.o', 'video/out/opengl/hwdec_drmprime_drm.c.19.o', 'video/out/vo.c.19.o', 'video/out/vo_drm.c.19.o', 'video/out/vo_image.c.19.o', 'video/out/vo_lavc.c.19.o', 'video/out/vo_null.c.19.o', 'video/out/vo_gpu.c.19.o', 'video/out/vo_tct.c.19.o', 'video/out/win_state.c.19.o', 'video/out/drm_atomic.c.19.o', 'video/out/drm_common.c.19.o', 'video/out/drm_prime.c.19.o', 'osdep/terminal-unix.c.19.o', 'osdep/io.c.19.o', 'osdep/timer.c.19.o', 'osdep/timer-linux.c.19.o', 'osdep/threads.c.19.o', 'osdep/semaphore_osx.c.19.o', 'osdep/subprocess.c.19.o', 'osdep/subprocess-posix.c.19.o', 'osdep/path-unix.c.19.o', 'ta/ta.c.19.o', 'ta/ta_talloc.c.19.o', 'ta/ta_utils.c.19.o', '-o/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/mpv', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L/usr/local/lib', '-lavcodec', '-lm', '-lz', '-ldl', '-lswresample', '-lm', '-lavutil', '-lm', '-ldl', '-lrt', '-ldrm', '-lm', '-ldl', '-lavdevice', '-lm', '-lxcb', '-lxcb-shm', '-lxcb-shape', '-lxcb-xfixes', '-lavfilter', '-lm', '-ldl', '-lswscale', '-lm', '-lavformat', '-lm', '-lz', '-lavcodec', '-lm', '-lz', '-ldl', '-lswresample', '-lm', '-lavutil', '-lm', '-ldl', '-lavfilter', '-lm', '-ldl', '-lswscale', '-lm', '-lavformat', '-lm', '-lz', '-lavcodec', '-lm', '-lz', '-ldl', '-lswresample', '-lm', '-lavutil', '-lm', '-ldl', '-lz', '-lmujs', '-lass']
video/out/opengl/hwdec_drmprime_drm.c.19.o: In function `overlay_frame':
/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/../video/out/opengl/hwdec_drmprime_drm.c:117: undefined reference to `ra_gl_get'
/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/../video/out/opengl/hwdec_drmprime_drm.c:129: undefined reference to `mpgl_get_native_display'
/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/../video/out/opengl/hwdec_drmprime_drm.c:140: undefined reference to `mpgl_get_native_display'
video/out/opengl/hwdec_drmprime_drm.c.19.o: In function `init':
/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/../video/out/opengl/hwdec_drmprime_drm.c:215: undefined reference to `ra_gl_get'
/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/../video/out/opengl/hwdec_drmprime_drm.c:218: undefined reference to `mpgl_get_native_display'
collect2: error: ld returned 1 exit status

Waf: Leaving directory `/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build'
Build failed
 -> task in 'mpv' failed with exit status 1: 
	{task 140135029230240: cprogram main-fn-unix.c.20.o,aconverter.c.19.o,audio.c.19.o,audio_buffer.c.19.o,chmap.c.19.o,chmap_sel.c.19.o,fmt-conversion.c.19.o,format.c.19.o,aframe.c.19.o,ad_lavc.c.19.o,ad_spdif.c.19.o,dec_audio.c.19.o,af.c.19.o,af_format.c.19.o,af_lavcac3enc.c.19.o,af_lavfi.c.19.o,af_lavrresample.c.19.o,af_scaletempo.c.19.o,tools.c.19.o,ao.c.19.o,ao_lavc.c.19.o,ao_null.c.19.o,ao_oss.c.19.o,ao_pcm.c.19.o,pull.c.19.o,push.c.19.o,av_common.c.19.o,av_log.c.19.o,codecs.c.19.o,encode_lavc.c.19.o,common.c.19.o,tags.c.19.o,msg.c.19.o,playlist.c.19.o,recorder.c.19.o,version.c.19.o,codec_tags.c.19.o,cue.c.19.o,demux.c.19.o,demux_cue.c.19.o,demux_disc.c.19.o,demux_edl.c.19.o,demux_lavf.c.19.o,demux_mf.c.19.o,demux_mkv.c.19.o,demux_mkv_timeline.c.19.o,demux_null.c.19.o,demux_playlist.c.19.o,demux_raw.c.19.o,demux_rar.c.19.o,demux_timeline.c.19.o,ebml.c.19.o,packet.c.19.o,timeline.c.19.o,cmd_list.c.19.o,cmd_parse.c.19.o,event.c.19.o,input.c.19.o,ipc.c.19.o,ipc-unix.c.19.o,keycodes.c.19.o,bstr.c.19.o,charset_conv.c.19.o,dispatch.c.19.o,json.c.19.o,node.c.19.o,ring.c.19.o,rendezvous.c.19.o,thread_pool.c.19.o,m_config.c.19.o,m_option.c.19.o,m_property.c.19.o,options.c.19.o,parse_commandline.c.19.o,parse_configfile.c.19.o,path.c.19.o,audio.c.19.o,client.c.19.o,command.c.19.o,configfiles.c.19.o,external_files.c.19.o,loadfile.c.19.o,main.c.19.o,misc.c.19.o,lavfi.c.19.o,javascript.c.19.o,osd.c.19.o,playloop.c.19.o,screenshot.c.19.o,scripting.c.19.o,sub.c.19.o,video.c.19.o,cache.c.19.o,cache_file.c.19.o,cookies.c.19.o,rar.c.19.o,stream.c.19.o,stream_avdevice.c.19.o,stream_edl.c.19.o,stream_file.c.19.o,stream_cb.c.19.o,stream_lavf.c.19.o,stream_memory.c.19.o,stream_mf.c.19.o,stream_null.c.19.o,stream_rar.c.19.o,ass_mp.c.19.o,dec_sub.c.19.o,draw_bmp.c.19.o,img_convert.c.19.o,lavc_conv.c.19.o,osd.c.19.o,osd_libass.c.19.o,sd_ass.c.19.o,sd_lavc.c.19.o,filter_sdh.c.19.o,csputils.c.19.o,fmt-conversion.c.19.o,image_loader.c.19.o,image_writer.c.19.o,img_format.c.19.o,hwdec.c.19.o,mp_image.c.19.o,mp_image_pool.c.19.o,sws_utils.c.19.o,dec_video.c.19.o,vd_lavc.c.19.o,refqueue.c.19.o,vf.c.19.o,vf_buffer.c.19.o,vf_convert.c.19.o,vf_format.c.19.o,vf_lavfi.c.19.o,vf_sub.c.19.o,aspect.c.19.o,bitmap_packer.c.19.o,dither.c.19.o,filter_kernels.c.19.o,context.c.19.o,hwdec.c.19.o,lcms.c.19.o,osd.c.19.o,ra.c.19.o,spirv.c.19.o,shader_cache.c.19.o,user_shaders.c.19.o,utils.c.19.o,video.c.19.o,video_shaders.c.19.o,hwdec_drmprime_drm.c.19.o,vo.c.19.o,vo_drm.c.19.o,vo_image.c.19.o,vo_lavc.c.19.o,vo_null.c.19.o,vo_gpu.c.19.o,vo_tct.c.19.o,win_state.c.19.o,drm_atomic.c.19.o,drm_common.c.19.o,drm_prime.c.19.o,terminal-unix.c.19.o,io.c.19.o,timer.c.19.o,timer-linux.c.19.o,threads.c.19.o,semaphore_osx.c.19.o,subprocess.c.19.o,subprocess-posix.c.19.o,path-unix.c.19.o,ta.c.19.o,ta_talloc.c.19.o,ta_utils.c.19.o -> mpv}
['/usr/bin/cc', '-rdynamic', '-pthread', '-pthread', '-Wl,-z,noexecstack', '-pthread', '-pthread', '-pthread', '-pthread', '-rdynamic', '-pthread', '-pthread', '-pthread', '-Wl,-version-script', '-Wl,mpv.def', 'osdep/main-fn-unix.c.20.o', 'audio/aconverter.c.19.o', 'audio/audio.c.19.o', 'audio/audio_buffer.c.19.o', 'audio/chmap.c.19.o', 'audio/chmap_sel.c.19.o', 'audio/fmt-conversion.c.19.o', 'audio/format.c.19.o', 'audio/aframe.c.19.o', 'audio/decode/ad_lavc.c.19.o', 'audio/decode/ad_spdif.c.19.o', 'audio/decode/dec_audio.c.19.o', 'audio/filter/af.c.19.o', 'audio/filter/af_format.c.19.o', 'audio/filter/af_lavcac3enc.c.19.o', 'audio/filter/af_lavfi.c.19.o', 'audio/filter/af_lavrresample.c.19.o', 'audio/filter/af_scaletempo.c.19.o', 'audio/filter/tools.c.19.o', 'audio/out/ao.c.19.o', 'audio/out/ao_lavc.c.19.o', 'audio/out/ao_null.c.19.o', 'audio/out/ao_oss.c.19.o', 'audio/out/ao_pcm.c.19.o', 'audio/out/pull.c.19.o', 'audio/out/push.c.19.o', 'common/av_common.c.19.o', 'common/av_log.c.19.o', 'common/codecs.c.19.o', 'common/encode_lavc.c.19.o', 'common/common.c.19.o', 'common/tags.c.19.o', 'common/msg.c.19.o', 'common/playlist.c.19.o', 'common/recorder.c.19.o', 'common/version.c.19.o', 'demux/codec_tags.c.19.o', 'demux/cue.c.19.o', 'demux/demux.c.19.o', 'demux/demux_cue.c.19.o', 'demux/demux_disc.c.19.o', 'demux/demux_edl.c.19.o', 'demux/demux_lavf.c.19.o', 'demux/demux_mf.c.19.o', 'demux/demux_mkv.c.19.o', 'demux/demux_mkv_timeline.c.19.o', 'demux/demux_null.c.19.o', 'demux/demux_playlist.c.19.o', 'demux/demux_raw.c.19.o', 'demux/demux_rar.c.19.o', 'demux/demux_timeline.c.19.o', 'demux/ebml.c.19.o', 'demux/packet.c.19.o', 'demux/timeline.c.19.o', 'input/cmd_list.c.19.o', 'input/cmd_parse.c.19.o', 'input/event.c.19.o', 'input/input.c.19.o', 'input/ipc.c.19.o', 'input/ipc-unix.c.19.o', 'input/keycodes.c.19.o', 'misc/bstr.c.19.o', 'misc/charset_conv.c.19.o', 'misc/dispatch.c.19.o', 'misc/json.c.19.o', 'misc/node.c.19.o', 'misc/ring.c.19.o', 'misc/rendezvous.c.19.o', 'misc/thread_pool.c.19.o', 'options/m_config.c.19.o', 'options/m_option.c.19.o', 'options/m_property.c.19.o', 'options/options.c.19.o', 'options/parse_commandline.c.19.o', 'options/parse_configfile.c.19.o', 'options/path.c.19.o', 'player/audio.c.19.o', 'player/client.c.19.o', 'player/command.c.19.o', 'player/configfiles.c.19.o', 'player/external_files.c.19.o', 'player/loadfile.c.19.o', 'player/main.c.19.o', 'player/misc.c.19.o', 'player/lavfi.c.19.o', 'player/javascript.c.19.o', 'player/osd.c.19.o', 'player/playloop.c.19.o', 'player/screenshot.c.19.o', 'player/scripting.c.19.o', 'player/sub.c.19.o', 'player/video.c.19.o', 'stream/cache.c.19.o', 'stream/cache_file.c.19.o', 'stream/cookies.c.19.o', 'stream/rar.c.19.o', 'stream/stream.c.19.o', 'stream/stream_avdevice.c.19.o', 'stream/stream_edl.c.19.o', 'stream/stream_file.c.19.o', 'stream/stream_cb.c.19.o', 'stream/stream_lavf.c.19.o', 'stream/stream_memory.c.19.o', 'stream/stream_mf.c.19.o', 'stream/stream_null.c.19.o', 'stream/stream_rar.c.19.o', 'sub/ass_mp.c.19.o', 'sub/dec_sub.c.19.o', 'sub/draw_bmp.c.19.o', 'sub/img_convert.c.19.o', 'sub/lavc_conv.c.19.o', 'sub/osd.c.19.o', 'sub/osd_libass.c.19.o', 'sub/sd_ass.c.19.o', 'sub/sd_lavc.c.19.o', 'sub/filter_sdh.c.19.o', 'video/csputils.c.19.o', 'video/fmt-conversion.c.19.o', 'video/image_loader.c.19.o', 'video/image_writer.c.19.o', 'video/img_format.c.19.o', 'video/hwdec.c.19.o', 'video/mp_image.c.19.o', 'video/mp_image_pool.c.19.o', 'video/sws_utils.c.19.o', 'video/decode/dec_video.c.19.o', 'video/decode/vd_lavc.c.19.o', 'video/filter/refqueue.c.19.o', 'video/filter/vf.c.19.o', 'video/filter/vf_buffer.c.19.o', 'video/filter/vf_convert.c.19.o', 'video/filter/vf_format.c.19.o', 'video/filter/vf_lavfi.c.19.o', 'video/filter/vf_sub.c.19.o', 'video/out/aspect.c.19.o', 'video/out/bitmap_packer.c.19.o', 'video/out/dither.c.19.o', 'video/out/filter_kernels.c.19.o', 'video/out/gpu/context.c.19.o', 'video/out/gpu/hwdec.c.19.o', 'video/out/gpu/lcms.c.19.o', 'video/out/gpu/osd.c.19.o', 'video/out/gpu/ra.c.19.o', 'video/out/gpu/spirv.c.19.o', 'video/out/gpu/shader_cache.c.19.o', 'video/out/gpu/user_shaders.c.19.o', 'video/out/gpu/utils.c.19.o', 'video/out/gpu/video.c.19.o', 'video/out/gpu/video_shaders.c.19.o', 'video/out/opengl/hwdec_drmprime_drm.c.19.o', 'video/out/vo.c.19.o', 'video/out/vo_drm.c.19.o', 'video/out/vo_image.c.19.o', 'video/out/vo_lavc.c.19.o', 'video/out/vo_null.c.19.o', 'video/out/vo_gpu.c.19.o', 'video/out/vo_tct.c.19.o', 'video/out/win_state.c.19.o', 'video/out/drm_atomic.c.19.o', 'video/out/drm_common.c.19.o', 'video/out/drm_prime.c.19.o', 'osdep/terminal-unix.c.19.o', 'osdep/io.c.19.o', 'osdep/timer.c.19.o', 'osdep/timer-linux.c.19.o', 'osdep/threads.c.19.o', 'osdep/semaphore_osx.c.19.o', 'osdep/subprocess.c.19.o', 'osdep/subprocess-posix.c.19.o', 'osdep/path-unix.c.19.o', 'ta/ta.c.19.o', 'ta/ta_talloc.c.19.o', 'ta/ta_utils.c.19.o', '-o/home/leylo/LIFE_ULTIMATE/Repos/Others/mpv/build/mpv', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L/usr/local/lib', '-lavcodec', '-lm', '-lz', '-ldl', '-lswresample', '-lm', '-lavutil', '-lm', '-ldl', '-lrt', '-ldrm', '-lm', '-ldl', '-lavdevice', '-lm', '-lxcb', '-lxcb-shm', '-lxcb-shape', '-lxcb-xfixes', '-lavfilter', '-lm', '-ldl', '-lswscale', '-lm', '-lavformat', '-lm', '-lz', '-lavcodec', '-lm', '-lz', '-ldl', '-lswresample', '-lm', '-lavutil', '-lm', '-ldl', '-lavfilter', '-lm', '-ldl', '-lswscale', '-lm', '-lavformat', '-lm', '-lz', '-lavcodec', '-lm', '-lz', '-ldl', '-lswresample', '-lm', '-lavutil', '-lm', '-ldl', '-lz', '-lmujs', '-lass']

**Comment by kevmitch** [comment]
Works here in a fresh sid chroot when checking out v0.27.0. Does running `./waf clean` first help?

**Comment by kevmitch** [comment]
reopen if it persists
