### ISSUE TITLE
Do we see the average frame timing or peak frame timing to know whether it drop frames or not?

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5185]
![deepin _20171206144524](https://user-images.githubusercontent.com/20014762/33648339-5913586a-da94-11e7-94cc-6199a45896b3.png)
As you can see, it is a 30fps video, the average frame timing is 27.336ms, the peak frame timing is 41.688ms, if the video is playing without frame drops, should the frame timing be below 33.333ms? If so, which one should I look? Average? Or peak?
### mpv version and platform
```
mpv 0.27.0-495-g0433162f7f-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.5.100
   libavcodec      58.6.102
   libavformat     58.2.103
   libswscale      5.0.101
   libavfilter     7.6.100
   libswresample   3.0.101
ffmpeg version: N-89398-gc8bd2c7d09
```
### Reproduction steps
Shift+i to desplay the frame timing
### Expected behavior
See the frame timing
### Actual behavior
See the frame timing

**Comment by haasn** [comment]
Average. Peak timings usually get smoothed out by the graphics driver's built-in latency. Normally, you'd instead look for mistimed or delayed frames.
