### ISSUE TITLE
Video is not smooth while the value of decoder frame drops and output frame drops display as 0

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5186]
### mpv version and platform
```
mpv 0.27.0-495-g0433162f7f-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.5.100
   libavcodec      58.6.102
   libavformat     58.2.103
   libswscale      5.0.101
   libavfilter     7.6.100
   libswresample   3.0.101
ffmpeg version: N-89398-gc8bd2c7d09
```
### Reproduction steps
Shift+i to display the stats
### Expected behavior
If the value of the Dropped Frames display as 0, there is no frame drops
### Actual behavior
I can see the video is moving not smoothly, althoug the value is remain 0
### Log file
[NoFrameDrops.log.zip](https://github.com/mpv-player/mpv/files/1534327/NoFrameDrops.log.zip)

**Comment by lachs0r** [comment]
Need stats output (https://mpv.io/manual/master/#options-dump-stats). Probably a driver issue though.
