### ISSUE TITLE
FFmpeg ABI compatibility - possibility to use/compile mpv trying to not check for ffmpeg compatibility?

### ISSUE THREAD

**Issue by shevegen** [mpv-player/mpv#5187]
Hello mpv team,

First I'd like to thank you people for mpv, it's great. While I also use mplayer, it would be correct to say that I use mpv a lot more. If we look at e. g. projects such as smplayer, who can handle both mpv and mplayer, then I am most likely not the only one who has noticed mplayer-versus-mpv (and the mplayer team appears to be friendly to mpv, e. g. Compn linking to mpv and pointing out the licence change some time ago). Anyway, enough for the off-topic but I did want to mention **mplayer**.

In particular because ... I may be wrong but I think that I could use mplayer even if I upgraded to another ffmpeg version, **without** having to recompile mplayer. Perhaps just minor... but if I recall correctly, mplayer either did not mind, or it gave out some warning such as "ffmpeg version incompatibility" or "libav version incompatibility". I don't know the exact error BUT I am almost 100% sure that mplayer still tried to play fine.

With mpv, I think there is a hard and abrupt stop, leaving no way to play multimedia files with a different ffmpeg version than the one it was compiled for. I can understand this to some extent, I guess it makes the life of the mpv team also easier. And I should also note that for me personally it is not a big deal, I use a set of ruby scripts to compile/re-compile, so it is not a big deal. But sometimes I forget to do until I e. g. need mpv ... for example, I had a ruby script that works as my "wecker" (german for an alarm clock). It's not a perfect system because I do break stuff and then sometimes mplayer or ffmpeg (or nowadays, mpv) may not work. I also have to admit that I can also fix the "forgetting to compile", since I used scripts, I could add a simple hook to also trigger a recompile of mpv whenever I compile ffmpeg. Still, I thought to mention it because ... this is mostly due to convenience for me, and perhaps also (hopefully) for other people.

- Would it be possible to let mpv try hard to play something, even with another ffmpeg version, if it were possible? The default could be to remain the way how mpv works, but a compile-time switch could be used perhaps, something like --ignore-ffmpeg-compatibility or so... or --be-compatible-to-ffmpeg=[yes/no].

That way perhaps mpv could try hard to make use of ffmpeg and only if the ABI would be too incompatible, would mpv also fail to play stuff. Perhaps for major version changes, this is not possible, but for minor version changes, perhaps?

Anyway, I am not sure how adamant the mpv team is in regards to the ABI compatibility, so feel free to close this issue at any time. I just wanted to mention it before I go option B, which is to add a hook to my scripts that whenever I compile a new version of ffmpeg, I'll also compile mpv.

Thanks for reading!

For anyone else who may read this, here is a copy/paste of the current main README entry for the ffmpeg ABI compatibility:

----

FFmpeg ABI compatibility

"mpv does not support linking against FFmpeg versions it was not built with, even if the linked version is supposedly ABI-compatible with the version it was compiled against. Expect malfunctions, crashes, and security issues if you do it anyway.

The reason for not supporting this is because it creates far too much complexity with little to no benefit, coupled with absurd and unusable FFmpeg API artifacts.

Newer mpv versions will refuse to start if runtime and compile time FFmpeg library versions mismatch."

**Comment by CounterPillow** [comment]
>In particular because ... I may be wrong but I think that I could use mplayer even if I upgraded to another ffmpeg version, without having to recompile mplayer. Perhaps just minor... but if I recall correctly, mplayer either did not mind, or it gave out some warning such as "ffmpeg version incompatibility" or "libav version incompatibility". I don't know the exact error BUT I am almost 100% sure that mplayer still tried to play fine.

Because mplayer contains an internal copy of the ffmpeg source tree.

Supporting multiple ABI versions would be an absolute nightmare and pretty much impossible. Fix your package management instead; if ffmpeg's ABI changes, all packages that depend on it need to be rebuilt.

**Comment by kevmitch** [comment]
Use [mpv-build](https://github.com/mpv-player/mpv-build) to produce an mpv binary statically linked to its own ffmpeg that remains constant even when you upgrade your system ffmpeg. Running anyway with ABI incompatibility will lead to inexplicable behavior and unnecessary issues opened here.

**Comment by jeeb** [comment]
In the very theory as long as the ABI hasn't changed mpv might run but you'll have to be on your toes for any accidental ABI breaks not marked with a major version bump. They don't happen often, but it's a possible occurrence. Debian patches out the version check, which is a valid alternative as they tend to do some sort of checking on if same API version libraries actually work or not. See [`debian/patches/06_ffmpeg-abi.patch`](https://anonscm.debian.org/cgit/pkg-multimedia/mpv.git/tree/debian/patches/06_ffmpeg-abi.patch).

Same mpv build running through multiple FFmpeg ABI versions is just insanity, though. Since as long as that was done correctly (not an accidental ABI break) the libraries would have different major API versions (and thus file names). So that just won't work.
