### ISSUE TITLE
OSC don't display

### ISSUE THREAD

**Issue by IAMJ** [mpv-player/mpv#5189]
### mpv version and platform
mpv version: 0.27.0 （git master compiled today）
OS: macOS 10.13.1

### Expected behavior
![0](https://user-images.githubusercontent.com/2928760/33706908-968b2ba0-db70-11e7-97dd-d6f0ee51324d.png)

### Actual behavior
![1](https://user-images.githubusercontent.com/2928760/33706915-9f68d952-db70-11e7-9db5-59ebaca15c1b.png)

### Sample files

**Comment by kevmitch** [comment]
Log needed. You're probably missing lua. Go back and recompile making sure that during ./waf configure you see 

    Checking for Lua : yes (version found: XXXX)

**Comment by IAMJ** [comment]
@kevmitch 
Thanks.
log file:  http://sprunge.us/VLiX

I reinstalled it via homebrew

mpv: stable 0.27.0 (bottled), HEAD
/usr/local/Cellar/mpv/0.27.0_2 (57 files, 33.7MB) *
  Built from source on 2017-12-07 at 17:19:04 with: --with-bundle
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb

**Comment by kevmitch** [comment]
Yes, lua is missing. I don't really know home brew, but that script says lua is "recommended" suggesting it will build without it if you don't have it installed or specify it or something.

**Comment by lachs0r** [comment]
You need to build with Lua 5.1, 5.2 or LuaJIT.

**Comment by IAMJ** [comment]
@lachs0r 
Thanks, let me try

**Comment by IAMJ** [comment]
@lachs0r 
build with Lua 5.2，OSC is back! Thanks

**Comment by iovis9** [comment]
Hey @IAMJ, I have Lua 5.3.4 and it didn't come back. How did you reinstall it with Lua? The `--with-lua` option is ignored and brew says I have Lua installed.

**Comment by IAMJ** [comment]
@iovis9 
I did not install via hromebrew, compiled by [mpv-build](https://github.com/mpv-player/mpv-build)

**Comment by kevmitch** [comment]
@iovis9 lua 5.3 is not supported. You need lua5.1, lua 5.2 or luajit, see #5202

**Comment by avih** [comment]
> lua 5.3 is not supported. You need lua5.1, lua 5.2 or luajit, see #5202

#5205

**Comment by iovis9** [comment]
Ohhh, I had no idea Lua 5.3 was that different, sorry! Thanks for taking the time to point to the issue.
