### ISSUE TITLE
Feature in stats.lua: Display audio track bit-depth

### ISSUE THREAD

**Issue by zc62** [mpv-player/mpv#5190]
Currently stats does not show the bit-depth:
![mpv_audio_info](https://user-images.githubusercontent.com/17048823/33706412-12de4184-db02-11e7-92f1-29cad0df7eaa.png)
It should be available for example, in Matroska, or ao can tell.
![bit-depth](https://user-images.githubusercontent.com/17048823/33707337-0cc945ca-db05-11e7-9334-3142b7c4e3d8.png)

**Comment by kevmitch** [comment]
We could add `audio-params/format` but this will do weird things like print `s32p` for 24 bit dts-hd or `floatp` for aac. We can't distinguish between 24 and 32 bits.

**Comment by zc62** [comment]
OK. What about 24 bit in other codecs? Is there any way to tell if the audio format detected is correct for sure or not? If so, maybe it can be printed as `s32p (uncertain)`.

**Comment by Argon-** [comment]
Is it really that relevant...? mpv is not a music player after all.
Note that I'm not really against such an addition itself but you have to consider that the stats script is currently (with DS and all this stuff) quite close to the maximum numbers of lines it can display (with current font size).
To display such an information at least on the same line as another one is pretty much mandatory.

**Comment by zc62** [comment]
I just thought people who really wants to see the sample rate, channel and bitrate information may also be interested in the bit depth.

Some other players display them in just one line, since each piece of information is quite short. We can save space by doing so. By removing "Sample Rate", "Channels" and so on we can make it even shorter. For example, in PotPlayer (windows software):
![potplayer](https://user-images.githubusercontent.com/17048823/33730876-554cc958-db4f-11e7-9c07-2b86ae290d02.png)

I think it would be really nice if the re-sampled rate and depth can also be shown. For example, if I use `--audio-samplerate=96000` and `--audio-format=s32`, the log (omitted many lines) shows:
```bash
[   3.248][v][ao/wasapi] Trying stereo s32 (32/32 bits) @ 96000hz (exclusive) -> unsupported
[   3.249][v][ao/wasapi] Trying stereo s32 (24/24 bits) @ 48000hz (exclusive) -> ok
[   3.249][v][ao/wasapi] Trying stereo s32 (24/24 bits) @ 96000hz (exclusive) -> ok
[   3.255][v][ao/wasapi] Accepted as stereo s32 @ 96000hz -> stereo s32 (24/24 bits) @ 96000hz (exclusive)
```
or maybe I need to open a new issue for this...

**Comment by kevmitch** [comment]
> mpv is not a music player after all.

Why not? Anyway it doesn't matter if you're listening to music or the audio channel to a corporate training video, the bit depth is a piece of information of equal relevance to the sample rate. 

> OK. What about 24 bit in other codecs?

This is not specific to any codec. ffmpeg's api always provides 24 bit audio in 32 bit integers with 0 lsb. As far as I know there isn't a way to know whether it's doing this or providing real 32 bit audio. Someone correct me if I'm wrong on that.

The only place mpv even knows about the existence of 24 bit audio is in the audio output and this is specific to each output and based on hardware capabilities, and only indirectly on the input stream. You've pointed out some wasapi log messges containing information that only wasapi knows about and certainly doesn't publish to any properties. ALSA on the other hand, doesn't do anything at all for 24 bit output. It just provides 32 bits to the driver which truncates to 24 outside of mpv's knowledge or control if that's all the hardware supports.

**Comment by haasn** [comment]
We can certainly compress the display of most of these stats in general; like compressing the entire sample spec into one line. (Channel count, format, rate, etc.)

**Comment by fhlfibh** [comment]
Also it would be good to have tags of current audio-stream displayed too.
e.g.  audio-streams in movies often have language tags and title/comment tags

**Comment by kevmitch** [comment]
> Also it would be good to have tags of current audio-stream displayed too.

Sounds like  #5191. I'm not sure if it's stats.lua's job to display content descriptions. It's aimed at more technical information.

I think audio could take two lines: `file` for input format from the file and `output` for the format that mpv produces to whatever audio API it's using. This reduces the current length by one and offers more information.

**Comment by fhlfibh** [comment]
@kevmitch Yes, the first image in that issue illustrates what I'm talking about: look at two FLAC streams there, both with identical tech data and JPN lang tag -- and different names. In my case I sometimes have a dozen streams like this for a single video.

I don't know if it's a technical information or not, I can only say that it's more convenient to have as much info as possible about what is currently being played and how mapped to a single button.

**Comment by zc62** [comment]
Personally I prefer to leave audio track name to "Available Audio Tracks" as I showed in that issue, since the name matters mostly when you switch between different audio tracks. I think stats may look tidy that we mainly show technical information not available elsewhere (except in the log), and keep other information at the place they belong to.

**Comment by Argon-** [comment]
>I don't know if it's a technical information or not

I agree with @zc62 here, you already get these information from `tracklist`/`osc-tracklist` and they are displayed when cycling through audio streams.

**Comment by zc62** [comment]
Probably I should close this because of #5827
