### ISSUE TITLE
Feature: when available, show track "Name" and "Properties"

### ISSUE THREAD

**Issue by zc62** [mpv-player/mpv#5191]
Currently mpv shows track name properly for built-in audio and subtitle tracks. However, for external files, only the filename can be seen. I understand it is important to keep the filename there, but I think we can easily abbreviate the filename when `--audio-file-auto=fuzzy` or `exact` and `--sub-auto=fuzzy` or `exact`, and try to shorten them in other cases, so that we can make some room for "Name" and "Properties".

Some pics for illustration:
Mkvtoolnix: above red line: mkv; below: mka.
![mkvtoolnix_example2](https://user-images.githubusercontent.com/17048823/33707832-c0e0cd48-db06-11e7-9b76-2b18c324e60b.png)
For tracks inside the mkv file: name yes, properties no.
For external files: name no, properties no.
![audio](https://user-images.githubusercontent.com/17048823/33707843-c760c560-db06-11e7-9e58-41c03d750747.png)
![sub](https://user-images.githubusercontent.com/17048823/33707852-cb755472-db06-11e7-976b-c4e1b70a54aa.png)

The "Name" and "Properties" info may also help with issue #5133

**Comment by Dudemanguy** [comment]
I think #6228 fixed this (feel free to reopen if I'm wrong).
