### ISSUE TITLE
Change "Use /dev/tty instead of stdin for terminal input" makes input invisible after qutting

### ISSUE THREAD

**Issue by philipl** [mpv-player/mpv#5195]
### mpv version and platform

8977fe5ed9d73dd56441d5071a0c2732636e7be3
Ubuntu 17.10
gnome-terminal

### Reproduction steps
Run mpv
Quit

### Expected behavior
Can type in terminal and see text

### Actual behavior
Can type in terminal and cannot see text
Need to 'reset' to return input visibility to normal

**Comment by TheAMM** [comment]
Seconding (on an older 14.04 laptop), gnome-terminal, bash.

**Comment by wm4** [comment]
In addition, this appears to eat 100% CPU on the terminal thread. Basically the change is completely broken. Nice.

**Comment by kwkam** [comment]
```diff
diff --git a/osdep/terminal-unix.c b/osdep/terminal-unix.c
index c7309fbf50..df27e34068 100644
--- a/osdep/terminal-unix.c
+++ b/osdep/terminal-unix.c
@@ -253,7 +253,7 @@ read_more:  /* need more bytes */

 static volatile int getch2_active  = 0;
 static volatile int getch2_enabled = 0;
-static bool read_terminal;
+static volatile bool read_terminal;

 static void enable_kx(bool enable)
 {
@@ -463,6 +462,7 @@ void terminal_uninit(void)
     setsigaction(SIGTTIN, SIG_DFL, 0, false);
     setsigaction(SIGTTOU, SIG_DFL, 0, false);

+    read_terminal = false;
     do_deactivate_getch2();

     if (input_ctx) {
@@ -474,7 +474,6 @@ void terminal_uninit(void)
     }

     getch2_enabled = 0;
-    read_terminal = false;
 }

 bool terminal_in_background(void)
@@ -502,6 +501,4 @@ void terminal_init(void)
     setsigaction(SIGTSTP, stop_sighandler, SA_RESETHAND, false);
     setsigaction(SIGTTIN, SIG_IGN, 0, true);
     setsigaction(SIGTTOU, SIG_IGN, 0, true);
-
-    getch2_poll();
 }
diff --git a/player/main.c b/player/main.c
index 2a3b6c62ea..a2b57fce10 100644
--- a/player/main.c
+++ b/player/main.c
@@ -133,7 +133,7 @@ void mp_update_logging(struct MPContext *mpctx, bool preinit)
     if (mp_msg_has_log_file(mpctx->global) && !had_log_file)
         mp_print_version(mpctx->log, false); // for log-file=... in config files

-    if (enabled && !preinit && mpctx->opts->consolecontrols)
+    if (enabled && preinit && mpctx->opts->consolecontrols)
         terminal_setup_getch(mpctx->input);
 }

```
At least fixed the terminal

**Comment by richardpl** [comment]
@wm4 what terminal emulator is that?

**Comment by SirCmpwn** [comment]
Can reproduce high CPU usage, but cannot reproduce terminal issues in gnome-terminal.

**Comment by SirCmpwn** [comment]
GNOME Terminal 3.26.2 Using VTE version 0.50.2 +GNUTLS

**Comment by SirCmpwn** [comment]
Can you test if this patch fixes the issue?

https://github.com/mpv-player/mpv/pull/5202

**Comment by philipl** [comment]
I can't reproduce the invisible input after the select() timeout fix. If I revert that fix, no visible input. If I apply that fix, visible input.

**Comment by SirCmpwn** [comment]
I don't understand what you mean.

**Comment by philipl** [comment]
I mean that the bug I reported, of not being able to see input after qutting is not reproducible for me since you pushed the fix for the high cpu usage (the select() timeout fix).

**Comment by SirCmpwn** [comment]
It is a race condition after all, so I imagine the first patch just made it harder to hit, and the second patch solves it. To make this more apparent and reproducable, try adding `sleep(1)` at the start of the loop in `terminal_thread`, then testing it with and without #5202 applied.
