### ISSUE TITLE
osd-sym-cc does not get reproducibly updated with more complex strings for osd-msg1/2/3

### ISSUE THREAD

**Issue by mjk-gh** [mpv-player/mpv#5207]
### mpv version and platform
mpv 0.27.0 (more precise: mpv 1:0.27.0-dmo3)
OS: Debian GNU/Linux (amd64) testing

### Reproduction steps
- Create minimalistic ~/.mpv/config with long string for osd-msg1 that contains a lot of $... terms:
-------------- snip ---------------
osd-msg1="${osd-sym-cc}${?loop-file==yes:.}${?loop-playlist==inf::} ${playback-time} / ${duration}   (${percent-pos}%)   [${width}x${height}@${container-fps} fps ${speed}] ---- ${filename} [${file-size}]\n${__bookmark.bookmarklist:}\na: ${aid} [${audio-delay}] @ ${osd-ass-cc/0}{\\\\i1}{\\\\1c&H00ffff&}${volume}{\\\\1c&Hffffff&}{\\\\i0}${osd-ass-cc/1}${osd-sym-cc}${?loop-file==yes:.}${?loop-playlist==inf::} ${playback-time} / ${duration}   (${percent-pos}%)   [${width}x${height}@${container-fps} fps ${speed}] ---- ${filename} [${file-size}]\n${__bookmark.bookmarklist:}\na: ${aid} [${audio-delay}] @ ${osd-ass-cc/0}{\\\\i1}{\\\\1c&H00ffff&}${volume}{\\\\1c&Hffffff&}{\\\\i0}${osd-ass-cc/1}${osd-sym-cc}${?loop-file==yes:.}${?loop-playlist==inf::} ${playback-time} / ${duration}   (${percent-pos}%)   [${width}x${height}@${container-fps} fps ${speed}] ---- ${filename} [${file-size}]\n${__bookmark.bookmarklist:}\na: ${aid} [${audio-delay}] @ ${osd-ass-cc/0}{\\\\i1}{\\\\1c&H00ffff&}${volume}{\\\\1c&Hffffff&}{\\\\i0}${osd-ass-cc/1}${osd-sym-cc}${?loop-file==yes:.}${?loop-playlist==inf::} ${playback-time} / ${duration}   (${percent-pos}%)   [${width}x${height}@${container-fps} fps ${speed}] ---- ${filename} [${file-size}]\n${__bookmark.bookmarklist:}\na: ${aid} [${audio-delay}] @ ${osd-ass-cc/0}{\\\\i1}{\\\\1c&H00ffff&}${volume}{\\\\1c&Hffffff&}{\\\\i0}${osd-ass-cc/1}"
-------------- snip ---------------
- `mpv --no-config --include ~/.mpv/config foobarbaz.mp4`
- Toggle pause state (using space bar) a few times and sometimes see osd-sym-cc showing a play symbol when in pause state.

Further notes:
- If the string contains only "`${osd-sym-cc} ${playback-time} XXXXXXXX[...]XXXXXX`" so that it is as long as the example string given above, the bug does not occur.
- Tested with osd-msg1, osd-msg2, osd-msg3.
- With my setup (3.3 GHz AMD multicore with GeForce GTX 750 Ti), bug is reproducible within a few seconds of playing around with the space bar.
- The bug occurs with both `vo=opengl` and `vo=x11`, as well as `--no-audio`.
- On occurrence of this bug (and directly afterwards), the value for "Dropped:", that is printed in the console status line, does not change.

### Expected behavior
osd-sym-cc reproducibly shows the play/pause symbol for the appropriate playback state.

### Actual behavior
osd-sym-cc only reproducibly shows the play symbol for the play state, but for the pause state, it often shows the play symbol instead of the pause symbol.

### Log file
https://pastebin.com/dcif91UA
Switched about 6-7 times between play and pause. Bug occurs with first and with last pause.

### Sample files
Tested with various videos from youtube, e.g. https://www.youtube.com/watch?v=3Cw9YFLDZeo

**Comment by Dudemanguy** [comment]
This should have been fixed by 296d40dc6f38401085d005bb4627f8afff46b041. osd-msg1/2/3 and long strings has nothing to do with it. It happened with any osd rendering.
