### ISSUE TITLE
mp.utils.getpid

### ISSUE THREAD

**Issue by SteveJobzniak** [mpv-player/mpv#5208]
This is a proposal for a new util function.

## Use case:

Scripts can launch external processes. Being able to tell that external process which mpv PID we're calling from (such as `os.execute("something " .. mp.utils.getpid())`) would allow that subprocess to differentiate the correct calling process if multiple mpv binaries are running.

In some cases, such as if we're calling an external C binary, we could of course just write that C binary to say "get the PID of the parent process". But in other cases, we don't have that luxury. For example, Apple's AppleScript has many great features for controlling app windows (via the Accessibility API) based on their process ID, but has no way of getting the calling process ID.

## Implementation:

- Bind to `getpid()` POSIX call on Mac and Linux (http://www.manpages.info/macosx/getpid.2.html).
- Alternative on Mac (but same result as `getpid()`): https://developer.apple.com/documentation/foundation/nsprocessinfo
- Bind to `GetCurrentProcessId()` on Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/ms683180(v=vs.85).aspx

**Comment by TheAMM** [comment]
I pronounce my interest for this feature.
Being able to differentiate between unique mpv processes can help a lot with scripts that to filesystem access or something related to it, not to mention allowing external control over the process through the scripts.

**Comment by SteveJobzniak** [comment]
It seems like there are 2 proposed uses for it so far:

- MacOS specific: Having the PID lets you tell AppleScript to do window management of mpv's player window. Its window management commands require a PID of what process to control, and the exact PID is even more important for finding the exact player instance when there are multiple ones.
- General (and this is the most interesting use case for me, now that I've heard about it): Having the PID lets you launch any external, detached process (`mp.utils.subprocess_detached({args:['somescript.py', mp.utils.getpid()]})`) and safely giving that script the ability to check if the launching parent PID is still alive. So even if mpv crashes or is force-killed, the subprocess, regardless of language, has a way of checking if the parent PID is still alive. Otherwise the subprocess would sit there in the background forever as an orphan.

There are surely even more uses for this.

**Comment by pink-mist** [comment]
External programs tend to have access to the parent pid without needing it passed in. For example in bash scripts there's the ```$PPID``` variable.

**Comment by Akemi** [comment]
> MacOS specific: Having the PID lets you tell AppleScript to do window management of mpv's player window. Its window management commands require a PID of what process to control, and the exact PID is even more important for finding the exact player instance when there are multiple ones.

it would probably be better if we would just add a possibility to react to geomerty and autofit property changes within mpv instead, eg. using our voctrl event api? if it was already rejected my bad for bringing it up again. i for my part wouldn't be against it.

**Comment by avih** [comment]
> react to geomerty and autofit property changes within mpv

This is definitely something I'd consider useful, but find it hard to estimate how complex it could become and if the complexity would be worth it.

**Comment by kevmitch** [comment]
#4218

**Comment by Akemi** [comment]
oh yeah we still have #3872 open.

**Comment by kevmitch** [comment]
> oh yeah we still have #3872 open.

this is what I meant

**Comment by SteveJobzniak** [comment]
@Akemi Hi again man, long time no see! Your continued work on the OS X GUI is incredible. Thanks.

Regarding #3872: I have answered with some info regarding that, which emerged on IRC today.
