### ISSUE TITLE
Issue #4792 persists after update

### ISSUE THREAD

**Issue by man0000** [mpv-player/mpv#5214]
Hi,

I have changed the Scroll wheel inputs WHEEL_UP/DOWN/LEFT/RIGHT in input.conf but, the horizontal scroll in the Logitech M600 still makes nothing.

With T630 and T650 all works as expected as before.

THANKS...

**Comment by thebombzen** [comment]
WHEEL_LEFT and WHEEL_RIGHT work as expected on my Logitech M510.

Try running `mpv --idle --force-window --input-test` and see if mpv displays the WHEEL_LEFT and WHEEL_RIGHT inputs when you click them. If not, it's probably an issue with your mouse drivers and you might need to install the Logitech mouse software to get those buttons to work.

**Comment by man0000** [comment]
Hi,

MANY THANKS for the  instruction test.
Seems like now in Logitech M600, swipe left/right are read as buttons and not as wheel.
Test returned MBTN_BACK/MBTN_FORWARD instead of WHEEL_LEFT/RIGHT.
Now configured an all works as expected.

MANY THANKS...
