### ISSUE TITLE
Vsync-Jitter becomes high frequently with linux4.15-rc3 dc enabled.

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5218]
![deepin _20171211162125](https://user-images.githubusercontent.com/20014762/33821802-3603c652-de90-11e7-8086-e29e98dcfc4a.png)

### mpv version and platform
```
mpv 0.27.0-520-gfd4e756e9c-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.5.100
   libavcodec      58.6.103
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.7.100
   libswresample   3.0.101
ffmpeg version: N-89463-gc7a5e80f56
```
```
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Baffin [Radeon RX 460/560D / Pro 450/455/460/560]
           Display Server: x11 (X.Org 1.19.5 ) driver: amdgpu Resolution: 1920x1080@60.00hz
           OpenGL: renderer: AMD Radeon RX 460 Graphics (POLARIS11 / DRM 3.23.0 / 4.15.0-rc3-mainline, LLVM 6.0.0)
           version: 4.5 Mesa 17.4.0-devel (git-4c7af87fb9)
```
### Reproduction steps
play movies and see the stats
### Expected behavior
stable vsync-jitter
### Actual behavior
vsync-jitter goes hight frequently
### Log file
[VsyncWithAMDGPU-DC.log.zip](https://github.com/mpv-player/mpv/files/1547028/VsyncWithAMDGPU-DC.log.zip)

**Comment by kevmitch** [comment]
Sounds similar to #3792, though that's with Intel.

**Comment by JulianLai** [comment]
@kevmitch How to dump the stats?
What more information do I need to offer here to make the problem easier to be solved?

**Comment by lachs0r** [comment]
Jitter of 0.06 is still pretty okay though.

**Comment by JulianLai** [comment]
@lachs0r It's like this `0.06 -> 0.06 -> ...-> 0.75 -> 0.80 -> 0.06 -> ..` and so on
I also need to enable `opengl-waitvsync`, otherwise, it will be always higher than 0.100

**Comment by JulianLai** [comment]
@lachs0r Is there any way to solve the power management problem?

**Comment by lachs0r** [comment]
0.1 is still okay. People are using mpv with higher jitter than that. It’s generally much worse on other platforms. And there is no problem with power management, that’s just a side effect of what it does (it’s also just an assumption on my part—maybe it doesn’t have anything to do with this).

I’m closing this because there doesn’t seem to be an actual problem (and if there is, it’s not mpv’s).
