### ISSUE TITLE
Automatically loop small files

### ISSUE THREAD

**Issue by tp78903** [mpv-player/mpv#5222]
Is there any script or setting that can automatically loop a file if it's under X seconds of duration?

For example, open a <5s file => sets loop current file to yes => open a >5s file => turns loop off

Thank you.

**Comment by zc62** [comment]
I wrote it just now: [autoloop.lua](https://github.com/zc62/mpv-scripts/blob/master/autoloop.lua)

**Comment by kevmitch** [comment]
script seems like the best solution for this rather special problem.

**Comment by tp78903** [comment]
@zc62 Thanks for the script, works like a charm. I've added it to the wiki.
