### ISSUE TITLE
Playback of 60 fps file is much too fast with video-sync=display-resample

### ISSUE THREAD

**Issue by e00E** [mpv-player/mpv#5228]
### mpv version and platform
Windows 10
60hz monitor
```
mpv 0.27.0-509-g3723e611fc-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Dec  9 12:06:44 UTC 2017
ffmpeg library versions:
   libavutil       56.5.100
   libavcodec      58.6.103
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.7.100
   libswresample   3.0.101
ffmpeg version: git-2017-12-08-713f9c5b5
```
### Reproduction steps

Download and play https://github.com/haasn/interpolation-samples/raw/master/60.000.mkv with mpv and set `video-sync=display-resample`.

### Expected behavior
Playback happens at normal speed.

### Actual behavior
Video and mpv's reported playback position move a lot faster than normal (roughly 10 times faster). Cpu usage is much higher.

Happens windowed and full screen. When entering fullscreen speed is normal for maybe a second then speeds up.

Also happens with `--display-fps=60`.
### Log file
http://sprunge.us/dcPf
This line might be interesting
```[   0.060][v][vd] Container reported FPS: 60.000004```
since it should be exactly 60fps and mpv reports while playing
```(+) Video --vid=1 (*) (h264 1920x1080 60.000fps)```

**Comment by haasn** [comment]
This bug is most likely caused by non-blocking swap calls. Display sync relies on the swapchain blocking after every present.

Since it seems like you're using ra_d3d11, ping @rossy 
```
[   0.018][v][vo/gpu/d3d11] Initializing GPU context 'd3d11'
[   0.043][v][vo/gpu/d3d11] Using Direct3D 11 feature level 12_1
[   0.043][v][vo/gpu/d3d11] Device Name: NVIDIA GeForce GTX 970
[   0.043][v][vo/gpu/d3d11] Device ID: 10de:13c2 (rev a1)
[   0.043][v][vo/gpu/d3d11] Subsystem ID: 3842:2974
[   0.043][v][vo/gpu/d3d11] LUID: 000000000000ac38
[   0.043][v][vo/gpu/d3d11] Initializing SPIR-V compiler 'shaderc'
[   0.043][v][vo/gpu/d3d11] Using Direct3D 11.1 runtime
[   0.043][v][vo/gpu/d3d11] Maximum Texture2D size: 16384x16384
[   0.044][v][vo/gpu/d3d11] D3DCompiler version: 10.0.16299.15
[   0.056][v][vo/gpu/d3d11] Using DXGI 1.2+
[   0.056][v][vo/gpu/d3d11] Using flip-model presentation
```

**Comment by e00E** [comment]
I tried a file with 23.976fps and `--no-audio` and indeed experienced the same problem.

**Comment by e00E** [comment]
I tried both files with `gpu-context=winvk` and the problem went away.

**Comment by rossy** [comment]
This is strange because --gpu-context=d3d11 should have blocking swap calls as well. Is this a multi-monitor system and is the 60Hz display your primary monitor? Also, is VSync forced off (or triple-buffering forced on) in the NVIDIA control panel?

**Comment by e00E** [comment]
Ah that was a good guess. I had set `Vertical sync` to `Fast` in the nvidia control panel which is as nvidia describes it from the application's point of view like no vsync while still not incurring tearing.
When I set it to Use the 3D application setting` then the problem goes away.

I do not know if mpv can do any better when the user forces this setting, so from my perspective we can close this bug.

**Comment by e00E** [comment]
It would be nice if mpv could output a warning if this situation is detected though.

**Comment by rossy** [comment]
Yeah, I don't think there's anything mpv can do to override that setting if it's forced by the drivers. Glad it's fixed though. I'm not a fan of those driver settings for this reason. It would be alright if they forced every _video game_ to disable VSync, but if VSync is disabled system-wide, it affects everything that uses 3D acceleration (though apparently Vulkan isn't affected?)

> It would be nice if mpv could output a warning if this situation is detected though.

Like @haasn said, mpv should detect this situation for files with audio, automatically disable display-sync and print a "Audio/Video desynchronisation detected!" warning. It might also be possible for us to detect that specific setting with NVAPI.

**Comment by aufkrawall** [comment]
I once reported a problem which in the end was caused by forcing anisotropic filtering when using ANGLE.
It's surely best practice to create a driver profile for mpv.exe and leave everything to application controlled for it.
