### ISSUE TITLE
fbdev video output support? Play video through GPIO display

### ISSUE THREAD

**Issue by CZyMfnIPC** [mpv-player/mpv#5231]
### mpv version and platform

Raspberry pi - Raspbian stretch

### Reproduction steps

I have a small LCD connected to the RPi through the GPIO pins. I am trying to play video on the console. 

### Expected behavior

On Jessie, I use mplayer2 and SDL to output to /dev/fb1 with this command:
SDL_VIDEODRIVER=fbcon SDL_FBDEV=/dev/fb1 mplayer -nolirc -vo sdl -fixed-vo file.mpg

### Actual behavior

On Stretch, I am now trying to use mpv with a similar command, but I cannot get it to display on my LCD:
SDL_VIDEODRIVER=fbcon SDL_FBDEV=/dev/fb1 mpv -vo=sdl file.mpg

### Log file

[vo/sdl] SDL_Init failed
[cplayer] Error opening/initializing the selected video_out (-vo) device.

I see that there is no official fbdev support, and it looks like mpv is using SDL2 which seems to not support framebuffer output. Do I have any way to output to my display? Or do I need to stick with the old mplayer2?

I found this gist patch in my searching: https://gist.github.com/uobikiemukot/ccb5e1fd71e43f3adec6

Has anyone tried it? Any plans to roll it into the official release? How would I go about trying it myself? 

Thanks!

**Comment by thebombzen** [comment]
Try using `--vo=gpu --gpu-api=opengl --gpu-context=mali-fbdev` (or if you're using an older version, try `--vo=opengl --gpu-context=mali-fbdev`.

**Comment by CZyMfnIPC** [comment]
Stretch is version 0.23.0, it seems neither --gpu-api nor --gpu-context is recognized. I see that inital mali-fbdev support was added in 0.21.0, so I just need to find the right syntax to try it out.

**Comment by CZyMfnIPC** [comment]
It looks like it might be `--vo=opengl --opengl-backend=mali-fbdev`?
however, that also has an error parsing opengl-backend...

**Comment by CounterPillow** [comment]
Use a newer version of mpv.

**Comment by CZyMfnIPC** [comment]
I was trying to update to the newest, however ran into issues. Looks like I need to try again. I will post a new issue for help to get it installed, then return here with my results for getting it running in fbdev

**Comment by thebombzen** [comment]
Alternatively you can join IRC and ask in the freenode channel `#mpv` if you'd like realtime help. It's much more effective than opening an issue because you cannot figure something out, seeing as issues are mostly to report defects in MPV rather than trying to get stuff to work on your end. (Opening up issues to ask questions rather than report a problem is the sort of thing that annoys developers, for future reference.)

**Comment by xantoz** [comment]
Can you get the LCD working using tinydrm instead of fbdev? tinydrm is a new set of drivers in the linux kernel meant to replace usage of fbdev for precisely small LCD screens connected over GPIO (usually SPI buses, IIRC it doesn't support any displays over I2C yet).

If you manage to get that working you could try either `--vo=drm` or `--vo=opengl --opengl-context=drm`.

Disclaimer: Just an alternative idea. I haven't yet tested tinydrm, or even less, mpv on top of tinydrm.

**Comment by CZyMfnIPC** [comment]
My first step now is to get an updated version of mpv installed so I can have access to these new options. trying to get help on the IRC channel, but they are having a hard time debugging. It is failing to ./build with issues linking against MMAL.

**Comment by kevmitch** [comment]
reopen if the recommended options don't work in the latest release.

**Comment by CZyMfnIPC** [comment]
I finally got mpv built from master, but when I try --vo=gpu --gpu-api=opengl --gpu-context=mali-fbdev it says "Error parsing option gpu-context (option parameter could not be parsed)
Setting commandline option --gpu-context=mali-fbdev failed."

without gpu-context it runs, but does not show on my fbdev screen.

**Comment by haasn** [comment]
And was your mpv built with `mali-fbdev` support? Try `./waf configure --enable-mali-fbdev`

**Comment by CZyMfnIPC** [comment]
if it is not enabled by default with mpv-build, then I did not.. I will try that, thanks!

**Comment by haasn** [comment]
It's enabled by default if development headers for mali fbdev support are found.

**Comment by CZyMfnIPC** [comment]
@haasn with mali-fbdev enabled, I get this error during config: You manually enabled the feature 'mali-fbdev', but the autodetection check failed.

http://0x0.st/sqo6.log

Any ideas?
Thanks!

**Comment by kevmitch** [comment]
Can't find `EGL/fbdev_window.h`. You need to install whatever provides that, or `CFLAGS=-I/wherever/that/is`

**Comment by wm4** [comment]
I'm fairly sure the header is MALI specific and won't work with anything else anyway.

The classic fbdev is a backwards API that is being phased out from drivers, and I don't think there are any plans to support it. Ask the devs to add support for DRM, which is the modern alternative for fbdev, and which mpv mostly supports.
