### ISSUE TITLE
No hardware decode for HEVC yuv422p10le

### ISSUE THREAD

**Issue by sameer** [mpv-player/mpv#5232]
Not sure if this is an mpv, ffmpeg, etc. or an actual hardware limitation issue, because I can play other pixel formats like p10e fine.

### mpv version and platform

mpv 0.27.0-534-g522bfe5be1 (C) 2000-2017 mpv/MPlayer/mplayer2 projects

### Reproduction steps

Play a video with yuv422p10le pixel format and --vd=hvec_qsv.

### Expected behavior

Plays the video with Intel QuickSync hardware decode.

### Actual behavior

Fails saying hevc_qsv does not support the pixel format.

### Log file

http://0x0.st/sXa7.txt

### Sample files

http://0x0.st/sXaF.mp4

**Comment by thebombzen** [comment]
There are currently no hardware decoders that support pixel subsampling other than 4:2:0. This is a limitation of your hardware (and everyone else's hardware, too).

**Comment by sameer** [comment]
I was afraid this was the case. I'm looking into transcoding to yuv420p with ffmpeg, looks like I'll be installing a bunch of packages.

Thanks
