### ISSUE TITLE
4K HEVC frame drops with 60~85% cpu usage.

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5233]
There is no frame drops with playing 4K AVC 59.94fps video, but it happens to 4K HEVC.

Here is the GPU and CPU usage when playing 4K HEVC HDR video:
![deepin _20171214144519](https://user-images.githubusercontent.com/20014762/33979712-95f4e526-e0e0-11e7-94fb-2c3b176cff09.png)
Low frame timings:
![deepin _20171214150907](https://user-images.githubusercontent.com/20014762/33979755-c49424dc-e0e0-11e7-8610-385d474854a8.png)

It seems like the GPU can play 4K 59.94fps video without problem, CPU can decode the HEVC with acceptable usage, then why does it still drop frames?
### mpv version and platform
```
mpv 0.27.0-520-gfd4e756e9c-dirty (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.5.100
   libavcodec      58.6.103
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.7.100
   libswresample   3.0.101
ffmpeg version: N-89463-gc7a5e80f56
```
### Reproduction steps
play 4K HEVC
### Expected behavior
smooth
### Actual behavior
stutter
### Log file
[HEVC4K.log.zip](https://github.com/mpv-player/mpv/files/1558186/HEVC4K.log.zip)

**Comment by thebombzen** [comment]
>CPU can decode the HEVC with acceptable usage

No, it can't.

**Comment by JulianLai** [comment]
@thebombzen But there is no frame drops with 60~80% cpu usage for the 4K AVC 59.94fps video, shouldn't it be OK for the HEVC 4K 59.94fps, too?

**Comment by thebombzen** [comment]
HEVC requires more CPU to decode than AVC. A lot more. This is not a surprise.

**Comment by JulianLai** [comment]
@thebombzen Shouldn't the CPU usage be much higher if it needs more resources? The highest usage is only 85%

**Comment by JulianLai** [comment]
@thebombzen It seems like the vaapi zero copy hardware decoding is the only solution?

**Comment by thebombzen** [comment]
Yes, that's something I told you 11 days ago. It was true then, it's true now, and if you open another issue about it, it'll still be true then too.

**Comment by JulianLai** [comment]
@thebombzen I see, thanks.
It will need to wait for the libva 2.1 to be released, otherwise, there is no zero copy mode of vaapi for AMDGPU

**Comment by JulianLai** [comment]
@thebombzen I was wrong, HEVC 4K plays smoothly, it only happens to HDR

**Comment by aufkrawall** [comment]
Are you using a CPU with enabled hyperthreading? If yes: More than 50% total CPU load often means that there is 100% load on each of the physical cores available, which probably means for decoding that the load is too high to fill queues timely.
I also observed that when the load is much too high, CPU load even breaks down.

**Comment by JulianLai** [comment]
@aufkrawall No, i5-4460 doesn't have the hyperthreading.
I also notice that the CPU usage will go to 100% if I enable `vd-lavc-dr` and `vd-lavc-threads=32`, and the few seconds at the begining of the video will also be smooth.

**Comment by giaur500** [comment]
My Ryzen CPU has 12 cores. No matter hat I seet, I am getting huge frame drops when trying to play hevc file with no more than 10% cpu usage - so, alwyas 1 cpu core used.

Tested on hevc 8k/30 cps and 4k/120 fps. I'm pretty sure playback could be fine on all 12 cores.

**Comment by thebombzen** [comment]
Stop retro-bumping four-year-old invalid issues.
