### ISSUE TITLE
Regression: failure to take screenshot with hwdec=vaapi

### ISSUE THREAD

**Issue by kevmitch** [mpv-player/mpv#5240]
### mpv version and platform

mpv 0.27.0-534-g522bfe5be1
ffmpeg 2d131fc31
libva1 1.8.3-1
Intel Ivy Bridge 

### Reproduction steps

`mpv <file> --hwdec=vaapi`
press `s` for screen shot 

### Expected behavior

png screenshot taken

### Actual behavior
```
[ffmpeg] AVHWFramesContext: Failed to read image from surface 0x400002b: 16 (surface is in use).
Taking screenshot failed.
```
### Log file
[log](http://sprunge.us/EdPd)

### Bisect

first bad commit 522bfe5be1 (vo_gpu: don't re-render hwdec frames when repeating frames)

**Comment by jeeb** [comment]
I guess you mean 5261d1b099edf16712582790085f4d369438dfe5 for the bad commit.

**Comment by kevmitch** [comment]
> I guess you mean 5261d1b for the bad commit.

ugh, yes

**Comment by grantwwu** [comment]
I have also observed this bug.

**Comment by wm4** [comment]
Not sure why this happens, when it apparently never happened with our old vaapi code. I don't think we try to access the image while it's written to, but surely it can happen while it's read from (like being used as reference frame during decoding, or when being displayed via GL). But surely, doing read accesses while it's used for other read accesses, it should work.

@fhvwy any ideas or comments?

Do we need some nonsense like staging surfaces, and could the libavutil code do this?
