### ISSUE TITLE
Display cache status on `o` presses too

### ISSUE THREAD

**Issue by linkmauve** [mpv-player/mpv#5247]
### mpv version and platform
74c6e7ba1d on ArchLinux.

### Reproduction steps
Press o while a video is playing.

### Expected behavior
The caching information that is currently displayed when moving the pointer to display the OSC should be displayed there too.

### Actual behavior
It isn’t.

### Log file
N/A.

### Sample files
Any.

**Comment by Argon-** [comment]
Is there a reason why it should?

You can do this, locally, yourself, by changing `osd-status-msg`, e.g. `osd-status-msg='${time-pos} / ${duration}\n${cache}'`

**Comment by kevmitch** [comment]
If I remember correctly, this used to be the case, but it was removed probably because this information is on the OSC. As @Argon- said, if you really like it, you can set it yourself.
