### ISSUE TITLE
Where do I go to find instructions on how to build MPV for iOS? (iPhone 8)

### ISSUE THREAD

**Issue by TheSneakySniper** [mpv-player/mpv#5264]
The title, basically.

I have not that much experience in swift (but i am good at googling around!), and was wondering if there was an in depth tutorial on how to build mpv for iOS.

Thanks!

**Comment by tmm1** [comment]
See mpv-examples repo

**Comment by Ahmedbutt** [comment]
@tmm1 I have seen examples repo but didnt find anything useful. Can you give more information regording that how could we get mpv static library for iOS project?
