### ISSUE TITLE
[Lua] Adding a timer prevents idle functions from triggering 

### ISSUE THREAD

**Issue by occivink** [mpv-player/mpv#5266]
### mpv version and platform
```
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Dec 15 18:31:42 CET 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.1
```

### Reproduction steps

Save this snippet 
```
mp.add_forced_key_binding("mouse_move", "test", function() end)
mp.register_idle(function() print("idle") end)
-- comment the next line to see the difference in behaviour
mp.add_periodic_timer(0.5, function() print("period") end)
```
as script.lua and run `mpv --no-config --script script.lua --idle --force-window`.

### Expected behavior

"period" is printed every 0.5s, and "idle" is printed after every "period" and every time the mouse moves

### Actual behavior

Only "period" gets printed, the idle function is never triggered.

**Comment by wm4** [comment]
As I've said earlier, this is probably a bug in the common Lua helper code, maybe in this function: https://github.com/mpv-player/mpv/blob/master/player/lua/defaults.lua#L468

**Comment by avih** [comment]
Is there a valid real-world use case for register_idle? as a repeating registration after every idle (current supposed behavior) or maybe for one-shot which fires only at the next (possibly current) idle?

**Comment by occivink** [comment]
@avih I use it in one [script](https://github.com/occivink/mpv-scripts/blob/master/drag-to-pan.lua) (see line 99, 112 and 116). Since `mouse_move` or mouse scrolling get called **very** quickly it allows me to batch these events and only set the properties once.

**Comment by wm4** [comment]
It's very useful to wait for all state changes and property notifications to finish, too.

**Comment by avih** [comment]
> "period" is printed every 0.5s, and "idle" is printed after every "period" and every time the mouse moves

It should definitely fire after mouse move events (and I confirm it doesn't), but I'm not sure if it's supposed to fire after timers - the docs are not clear about it, but I'd think it shouldn't.

**Comment by avih** [comment]
> but I'm not sure if it's supposed to fire after timers

After clarification - it's supposed to fire just before the script goes to sleep, which typically also happens after due timers are fired.

So your expectation is correct. Sorry for the noise.
