### ISSUE TITLE
Feature request: Position video with the middle of the video being the starting point.

### ISSUE THREAD

**Issue by installgentooRMS** [mpv-player/mpv#5267]
From manual:

>x and y set the window position, measured in pixels from the top-left corner of the screen to the top-left corner of the image being displayed.

I can't use this because videos all have different dimensions which will cause the videos to overlap the desktop or appear way too off-center. 

What I want is the ability to set all videos to start from an xy coordinate, not have the top-left of the video being the starting point, rather the center, and then have them scale (if they're too big) so they don't overlap the Windows taskbar.

**Comment by wiiaboo** [comment]
Maybe https://github.com/mpv-player/mpv/pull/5257 will fix that last one.

**Comment by pavelxdd** [comment]
@wiiaboo no it won't. This PR doesn't change the way position coordinates are treated.

**Comment by Akemi** [comment]
if this is still an issue, please open a new issue.
