### ISSUE TITLE
mpv doesn't render on second screen when launched with `--fs --fs-screen=all`

### ISSUE THREAD

**Issue by pavelxdd** [mpv-player/mpv#5268]
### mpv version and platform

0.27.0 (it can be reproduced on git master as well)
Windows 10

### Reproduction steps

Start mpv with `mpv --player-operation-mode=pseudo-gui --no-config --fs --fs-screen=all`
or `mpv --force-window --idle --no-config --fs --fs-screen=all`

### Expected behavior

The mpv logo (or video, if you provided mpv with a filename) rendered in the middle of the virtual screen, one part on the left screen and the other part on the right screen.

### Actual behavior

The image is rendered only on the one screen (cropped), and the other screen is completely black.
If leave fullscreen and switch back, the image is displayed fine on both screens.
What is strange, if I take a screenshot with mpv or Print Screen, the mpv logo is there, as if it was rendered on the second screen too.

I started mpv this way ~30 times, and most of the times the mpv renders on the secondary screen, while the primary is black. There were a few times (3-4), when mpv rendered on primary screen and the secondary was black. And there was one time when the image was rendered on both screens like it should. So it is completely random.

### Log file

https://0x0.st/s8Nm.log
debug log: https://0x0.st/s8Np.log

**Comment by wm4** [comment]
Could depend on the swap chain and GPU API.

**Comment by pavelxdd** [comment]
I can't reproduce it with `--vo=direct3d` by the way.

**Comment by Akemi** [comment]
please open a new issue if this still persists.
