### ISSUE TITLE
Visual bug during playback of specific movie

### ISSUE THREAD

**Issue by erasmux** [mpv-player/mpv#5271]
### mpv version and platform

mpv-x86_64-20171216-git-e1ac0c1 on Windows 7 SP1 64bit

I traced the bug to the mpv-x86_64-20171113-git-41243e7 release (meaning on this release and newer ones the bug still occurs but if I go back to mpv-x86_64-20171104-git-d46c9c2 or older the bug does not occur).

### Reproduction steps

Play the [mpv_bug.mkv](
https://mega.nz/#!FHxm2KIS!Y5LaHNheS9F6e31ujGBOF8vJAOzAhtowi7q1HhtKgDE
) with mpv and at 00:00:13 there is a visual bug (see [screenshoot1](http://image.ibb.co/f41QLR/mpv_shot0001.jpg) and [screenshoot2](http://image.ibb.co/dnSzfR/mpv_shot0002.jpg)).

### Expected behavior

No visual bug.

### Actual behavior

Visual bug.

### Log file

Here is the log of the 20171216 version (which exhibits the bug):
https://pastebin.com/LcEeQpvM
(notice it has "Corrupt file detected" @ 12.303)

Here is the log of the 20171104 version (which works fine):
https://pastebin.com/RAifhtdf
(notice it has no errors like newer versions have)

### Sample files

https://mega.nz/#!FHxm2KIS!Y5LaHNheS9F6e31ujGBOF8vJAOzAhtowi7q1HhtKgDE

**Comment by wm4** [comment]
Yep, it was a real bug, the PR should fix it.

**Comment by erasmux** [comment]
Thanks!
