### ISSUE TITLE
Mess video output with r600 vdpau hw decode enabled

### ISSUE THREAD

**Issue by andysendo** [mpv-player/mpv#5273]
### mpv version and platform
mpv 0.23/0.27 (installed from repo and self-compiled),  debian9 stable repo.
Mobile firegl v5700 / intel GMA4500, open soure video driver.
Boot with standalone radeon card (disable intel card from bios ) or dual video card (use dri_prime=1) 

firegl v5700 Decoder capabilities by vdpauinfo:
MPEG2_SIMPLE                    3  9216  2048  1152
MPEG2_MAIN                      3  9216  2048  1152
H264_BASELINE                  41  9216  2048  1152
H264_MAIN                      41  9216  2048  1152
H264_HIGH                      41  9216  2048  1152
VC1_SIMPLE                      1  9216  2048  1152
VC1_MAIN                        2  9216  2048  1152
VC1_ADVANCED                    4  9216  2048  1152

### Reproduction steps
play a h264 encoding movie (whatever 720p/1080p) , with option:
1) --hwdec=auto  --vo=opengl  (actually vdpau-copy enabled)
2) --hwdec=vdpau --vo=vdpau
almost same result.

### Actual behavior
hw decoding is enabled, cpu load <8%. video output is completely mess, like this:
![1](https://user-images.githubusercontent.com/17525832/34319753-c523a8dc-e824-11e7-91b8-5fe1271cb549.png)

### Log file
VDPAU_DRIVER=r600 mpv test.mkv -hwdec=vdpau -vo=vdpau -v
[log.txt](https://github.com/mpv-player/mpv/files/1584132/log.txt)

### Plus
i also tried mplayer+vdpau, got same result. so i am not sure it is mpv bug, maybe there is some option to fix it?

**Comment by Jj0YzL5nvJ** [comment]
Similar to https://github.com/mpv-player/mpv/issues/3714, but isn't the same.

Very likely a bug on Mesa, can you provide a glxinfo output?
Or at least something like this:
glxgears -info
```
GL_RENDERER   = Gallium 0.4 on AMD JUNIPER (DRM 2.43.0 / 4.4.0-104-generic, LLVM 4.0.0)
GL_VERSION    = 3.0 Mesa 17.0.7
GL_VENDOR     = X.Org
```

**Comment by andysendo** [comment]
glxgears -info

GL_RENDERER   = Gallium 0.4 on AMD RV635 (DRM 2.49.0 / 4.9.0-4-amd64, LLVM 3.9.1)
GL_VERSION    = 3.0 Mesa 13.0.6
GL_VENDOR     = X.Org
GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_multisample GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_ATI_meminfo GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_vertex_attrib_binding GL_KHR_debug GL_AMD_pinned_memory GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_NVX_gpu_memory_info GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_EXT_polygon_offset_clamp GL_KHR_context_flush_control GL_MESA_shader_integer_functions

**Comment by Jj0YzL5nvJ** [comment]
Mesa 13.0.0-rc1 and Mesa 13.1.0-devel were problematic on ATI/AMD with certain versions of LLVM. I don't know the details. https://github.com/mpv-player/mpv/issues/3714#issuecomment-259687313
 Me recommendation is downgrade or upgrade your Mesa packages... Debian Stable doesn't help much there, I think.

 By the way, avoid install libvdpau-va-gl. VA-API is very broken on Mesa. I don't know if that the reason you are forcing `VDPAU_DRIVER=r600`.

**Comment by andysendo** [comment]
unlucky upgrade to debian testing repo mpv+vdpau playback still the same error.
va-vdpau also same error and i do not use it,
VDPAU_DRIVER=r600 is for dri_prime, boot with only radeon card not need it.

**Comment by Jj0YzL5nvJ** [comment]
Test with [mpv-build](https://github.com/mpv-player/mpv-build)... and add `--no-config` to your trials. It is not necessary to install, execute it directly.

Examples:
```
./mpv --no-config --vo=gpu --hwdec=vdpau test-file.mp4
./mpv --no-config --vo=gpu --hwdec=vdpau --ytdl-format=137+171 https://youtu.be/-NHG1-wlUh4
```

**Comment by lachs0r** [comment]
Driver/hardware problem.
