### ISSUE TITLE
mpv can not display some fonts correctly

### ISSUE THREAD

**Issue by RichieChow** [mpv-player/mpv#5279]
I found mpv could not display some fonts correctly, such as ＤＦ明朝体W5 and FG平成明朝体W7. The text will output as spaces or some strange characters.
But these can be display correctly by mpc-be with XySubFilter.

Look at the japanese characters on the top.
mpv
![dymy ank-raws 01 bdrip 1920x1080 hevc-yuv420p10 flac -001](https://user-images.githubusercontent.com/34783557/34327064-e78b1eec-e8f5-11e7-90e7-fc70343bd025.png)

mpc-be
![dymy ank-raws 01 bdrip 1920x1080 hevc-yuv420p10 flac mkv_snapshot_01 11_ 2017 12 24_21 53 34](https://user-images.githubusercontent.com/34783557/34327049-90ed1a54-e8f5-11e7-94e1-e912b0bdad11.jpg)

mpv
![liuyun vcb-s ank-raws chihayafuru 01 hi10p_1080p x264_flac -001](https://user-images.githubusercontent.com/34783557/34327067-1273fe44-e8f6-11e7-9693-b50f271bc8e3.png)

mpc-be
![liuyun vcb-s ank-raws chihayafuru 01 hi10p_1080p x264_flac mkv_snapshot_21 43_ 2017 12 24_21 54 54](https://user-images.githubusercontent.com/34783557/34327078-4062a4cc-e8f6-11e7-942a-33cc4c0c601e.jpg)

```
   sub/ass: Glyph 0x53F7 not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x53F7 not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x3092 not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x3092 not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x307F not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x307F not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x53D6 not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x53D6 not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x308B not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x308B not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x6F5C not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x6F5C not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x3080 not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x3080 not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x6697 not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x6697 not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x53F7 not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x53F7 not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x3092 not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x3092 not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x307F not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x307F not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x53D6 not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x53D6 not found in font for (ＤＦ明朝体W5, 700, 0)
   sub/ass: Glyph 0x308B not found, broken font? Trying all charmaps
   sub/ass: Glyph 0x308B not found in font for (ＤＦ明朝体W5, 700, 0)
   .....
```

**Comment by dragons4life** [comment]
Do you know how to extract the fonts from the .mkv? I suggest you upload them

**Comment by RichieChow** [comment]
[fonts.zip](https://github.com/mpv-player/mpv/files/1584904/fonts.zip)

**Comment by JulianLai** [comment]
姦

**Comment by RichieChow** [comment]
sometimes characters are displayed as blocks
mpv
![liuyun vcb-s hanasaku iroha 02 hi10p_1080p bdrip x264_flac -001](https://user-images.githubusercontent.com/34783557/34451272-37784d8e-ed5c-11e7-9de4-879c48f07e93.png)
mpc-be
![liuyun vcb-s hanasaku iroha 02 hi10p_1080p bdrip x264_flac mkv_snapshot_00 02_ 2017 12 30_12 15 40](https://user-images.githubusercontent.com/34783557/34451279-3f46e5d4-ed5c-11e7-8a4d-fd645d0b2ee1.png)

and subs will be displayed out of the screen
mpv
![liuyun vcb-s hanasaku iroha 02 hi10p_1080p bdrip x264_flac -002](https://user-images.githubusercontent.com/34783557/34451283-6cf89202-ed5c-11e7-9306-29d19ff51b25.png)
mpc-be
![liuyun vcb-s hanasaku iroha 02 hi10p_1080p bdrip x264_flac mkv_snapshot_00 21_ 2017 12 30_12 16 30](https://user-images.githubusercontent.com/34783557/34451285-782ab236-ed5c-11e7-833c-1abcd95a437c.png)
[HGRHAMSJ.zip](https://github.com/mpv-player/mpv/files/1594162/HGRHAMSJ.zip)

**Comment by Tsubajashi** [comment]
Do you still have that issue? currently fighting with ass-subs myself.

**Comment by zc62** [comment]
Is this issue still present or not? If so, have you tried to report to libass? https://github.com/libass/libass/issues

**Comment by Akemi** [comment]
ignored issue template and most like reported upstream.
