### ISSUE TITLE
how to set balance in 0.28.0? and one more question

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#5285]
### mpv version and platform
Newest 0.28.0 on https://mpv.srsfckn.biz/ 
X64 ver on windows 7sp1x64
### Reproduction steps
Before i have a setting in input.conf that 
( add balance -0.1
) add balance 0.1
But when i update to 0.28.0 it says **Option balance not found**
Is balance change name?I have some old video have only right or left sound 
so i need this option to change balance.

And one more question,if now i have multiple mpv window,example i have three play window
one is on my hard disk,another two is on youtube and twitch,is there a command or hotkey
to switch between only these three mpv windows?

**Comment by wiiaboo** [comment]
> ### Deprecated
>  -  deprecate "balance" option/property (no replacement)

It's been deprecated for months. Replacement is [audio-balance.lua](https://github.com/wiiaboo/mpv-scripts/blob/master/audio-balance.lua).

> And one more question,if now i have multiple mpv window,example i have three play window
one is on my hard disk,another two is on youtube and twitch,is there a command or hotkey
to switch between only these three mpv windows?

No, there's no main mpv process to manage that.

**Comment by kesdoputr** [comment]
Ok i see,i will try to use audio-balance.lua,thx for your reply.
