### ISSUE TITLE
Feature request: add "read input at native frame rate" option in encoding mode

### ISSUE THREAD

**Issue by chainikdn** [mpv-player/mpv#5292]
> -re (input)
> Read input at native frame rate. <...> By default ffmpeg attempts to read the input(s) as fast as possible. This option will slow down the reading of the input(s) to the native frame rate of the input(s). It is useful for real-time output (e.g. live streaming).

**Comment by TheAMM** [comment]
I remember I saw mention of this on the IRC and I've used ffmpeg's `-re` once or twice, but can you remind me what was the use-case with mpv?

**Comment by wiiaboo** [comment]
Also livestreaming, I'd guess. It's the only usecase where it'd be useful.

**Comment by chainikdn** [comment]
the same reason - "It is useful for real-time output (e.g. live streaming)."

**Comment by lachs0r** [comment]
Try --vf=realtime.

**Comment by TheAMM** [comment]
I was asking more along the way of "in what use case would you use mpv to livestream instead of ffmpeg", but sure.

**Comment by chainikdn** [comment]
to add a Vapoursynth filter, for example
ffmpeg can't do this

**Comment by wiiaboo** [comment]
Or livestreaming with proper hardcoded subtitles.

**Comment by lachs0r** [comment]
I consider this solved with the filters I have mentioned. These also have an advantage over the `-re` option: They can be inserted anywhere in the filter chain (which could change the frame/sample rate at any point).
