### ISSUE TITLE
mpv Interface Font

### ISSUE THREAD

**Issue by vermaden** [mpv-player/mpv#5299]
### mpv version and platform
% mpv --version
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Dec 14 17:28:09 UTC 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100

% uname -a
FreeBSD t420s.local 11.1-RELEASE-p4 FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

### Question

Hi, how to change INTERFACE font in mpv? (not subtitles/osd).

Regards.

**Comment by j605** [comment]
What other interface exists other than osd/osc? Setting serif and sans-serif properly in `fontconfig` should help.

**Comment by vermaden** [comment]
The --osd-font options is the on I was looking for.

I just thought that OSD is for the texts that are not subtitles that appear ABOVE the bar on the bottom.

You may of course close this issue as resolved.

Thank You.

**Comment by wiiaboo** [comment]
You can close it too, since you opened it.

**Comment by vermaden** [comment]
Right ;)

I am just used to FreeBSD BUG 'system' where I do not have rights to close the issue.
