### ISSUE TITLE
Segfault on Raspberry Pi

### ISSUE THREAD

**Issue by deltabeard** [mpv-player/mpv#5301]
### mpv version and platform

mpv: 0.28.0
ffmpeg: latest snapshot
Compiled with Buildroot, using a uclibc-ng toolchain for the Raspberry Pi 3.

### Reproduction steps

Play a h264 encoded video file on the Raspberry Pi 3. (Audio files not affected)

### Expected behavior

Not to segfault.

### Actual behavior

Segfaults when playing a video file. Prints out "SEGV".

### Log file

[gdb log file including backtrace](http://sprunge.us/DKQc)
[mpv output](http://sprunge.us/KHhR)
[mpv log file](http://sprunge.us/QUAe)

**Comment by wm4** [comment]
None of those sprunge links work.

**Comment by CounterPillow** [comment]
Sprunge seems to be down right now, but I looked at the backtrace when it was still up and it seemed like [hwdec_devs here was NULL](https://github.com/mpv-player/mpv/blob/master/video/decode/vd_lavc.c#L456).

**Comment by wm4** [comment]
I guess that could cause it.
