### ISSUE TITLE
x11 window wont init on raspi

### ISSUE THREAD

**Issue by bmoren** [mpv-player/mpv#5308]
### Raspberry Pi  mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.9-1~deb9u1

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
mpv --vo=opengl wc_1.mp4

### Expected behavior
play the video file

### Actual behavior
Error opening/initializing the selected video_out (--vo) device.

### Log file
pi@raspberrypi:~ $ mpv --vo=opengl wc_1.mp4
Playing: wc_1.mp4
 (+) Video --vid=1 (*) (h264)
 (+) Audio --aid=1 --alang=eng (*) (aac)
[vo/opengl/wayland] failed to connect to a wayland server: check if a wayland compositor is running
[vo/opengl/x11] couldn't open the X11 display ()!
[vo/opengl/x11] couldn't open the X11 display ()!
[vo/opengl/x11] couldn't open the X11 display ()!
[vo/opengl] VT_GETMODE failed: Inappropriate ioctl for device
[vo/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/opengl] Cannot open card "0": No such file or directory.
[vo/opengl] Failed to create KMS.
[vo/opengl] 'drm-egl' is deprecated, use 'drm' instead.
[vo/opengl] Can't handle VT release - signal already used
[vo/opengl] Failed to set up VT switcher. Terminal switching will be unavailable.
[vo/opengl] Cannot open card "0": No such file or directory.
[vo/opengl] Failed to create KMS.
Error opening/initializing the selected video_out (--vo) device.
Video: no video

Exiting... (Errors when loading file)

### Sample files
https://www.dropbox.com/s/pcrx5she5j8opyl/wc_1.mp4?dl=0

**Comment by CounterPillow** [comment]
>mpv 0.23.0 (C) 2000-2016

This is one year out of date.

Are you even running an X server or a wayland compositor?

**Comment by bmoren** [comment]
ok, i guess apt-get install is not going to work here ;)
