### ISSUE TITLE
window size

### ISSUE THREAD

**Issue by vendforce** [mpv-player/mpv#5310]
### mpv version and platform

OS : arch
DE: kde plasma
MPV VERSION: 1:0.27.0-5

I've tried googling it and I cant find the answer thats why I'm here !!!!!

When I open mpv its not fitting my window why doesnt it find the correct window size for the screen its running on and open .. when I click the maximise button it gets smaller, so it opens maximised but still doesnt fit my window , how do I make mpv open like a normal application maximise and minimise where maximise fits the whole screen and I'm not talking about -fs fullscreen

**Comment by kevmitch** [comment]
`--autofit=50%`
