### ISSUE TITLE
[lavf] Cannot seek in this file.

### ISSUE THREAD

**Issue by marste** [mpv-player/mpv#5313]
mpv 0.28.0 Windows x64

There is a problem with listening to some streaming radios.
Using mplayer.exe works regularly.

Example:

C:\Program Files\mpv>mpv http://sj128.hnux.com
Playing: http://sj128.hnux.com
EDL: source file 'http://sj128.hnux.com/live?type=http&nocache=377897' has unknown duration.
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
[lavf] Cannot seek in this file.
AO: [wasapi] 48000Hz stereo 2ch float
A: 00:00:00 / 00:00:01 (73%) Cache:  0s

Exiting... (End of file)

**Comment by wiiaboo** [comment]
Try with `--no-ytdl`.

**Comment by marste** [comment]
Perfect!
