### ISSUE TITLE
MPV crashing when using --video-sync=display resample on switchable(Optimus) graphics system

### ISSUE THREAD

**Issue by dnmTX** [mpv-player/mpv#5320]
### mpv version and platform
mpv-x86_64-20171229-git-d9ca235 (latest build by shinchiro)
Windows 10(x64) 1607 LTSB

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Streaming .mkv (tv show or movie) with --video-sync=display-resample

### Expected behavior
To PLAY

### Actual behavior
Player crashing shortly after
Start happening after updating the Nvidia driver to the latest(388.71).Most likely it's a driver/Optimus issue.Without VSync all works as suppose to.@rossy advised to open new issue so here i am.Would appreciate any help on this matter.Thank you
If it's any help i'm using RAM Drive so the MPV cache file is there(in TEMP folder),the "shader-cache" folder is also there and usually whatever movie i download is playing from there as well.
### Log file
Uploaded (see Sample files)

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files
[log.txt](https://github.com/mpv-player/mpv/files/1594261/log.txt)

**Comment by shinchiro** [comment]
> Player crashing shortly after

If it's crash case, I suggest you to get [debug-symbol](https://sourceforge.net/projects/mpv-player-windows/files/debug-symbol/) for that binary. Follow the steps to setup debugger and post that crash dump. That's more useful to the dev

**Comment by rossy** [comment]
@dnmTX Thanks for the log and the crash dump. We might be able to fix the crash in mpv, though the root cause seems to be a lost device error, which we can't recover from yet, and probably indicates a driver bug.

**Comment by dnmTX** [comment]
Thank you @rossy ,anything you can do is appreciated.Most likely it's a driver bug as you said,recently i start seeing same happening with my Chromium browser and when i plug my headphones(GPU is fine just the d3d11 crashing,sometimes recovers,sometime not.Also i saw that you made some progress with the "switchable graphics" and i hope that you guys not gonna abandon that project,would really like to have that option present in the near feature.Take care friend.

**Comment by dnmTX** [comment]
[system32.dll-vsync-gpu-hq.txt](https://github.com/mpv-player/mpv/files/1605346/system32.dll-vsync-gpu-hq.txt)
@rossy !!!!! I hope you still checking on my post here but i thing i found what is causing the crashes.It's the d3dcompiler_43.dll that came with the build.By removing it from the MPV folder i was able to use --video-sync=display-resample with d3d11 without experiencing any crashes(even with profile=gpu-hq no problems)Then i compared the versions on the one that that came with the build and the one in my system32 folder and they are different:
MPV- 10.0.16299.15
System32- 9.29.952.3111
Then i copied the one from system32 and replaced it with the original one in MPV folder and the result is the same,vsync is working,no crashes.I'm uploading two log files,one without the compiler and one with the one from system32.(there is already one with the original in my first post anyway) to compare it.
My question is,do i really need that d3dcompiler_43.dll to be present in the MPV folder case by the look of it even without it it's fine,but with the original one the player is crashing when using vsync?
Will wait for response.Thank you.
[no.dll-vsync-gpu-hq.txt](https://github.com/mpv-player/mpv/files/1605344/no.dll-vsync-gpu-hq.txt)

**Comment by dnmTX** [comment]
@rossy i test it with the latest build and i can confirm that there is no errors and the player didn't crash on me yet so i'll close this issue.Thank you for fixing it.
I still can't use --video-sync=display-resample.With it the player doesn't crash anymore but after certain time i'm ending up with black screen and sound only,without it is working fine.Just FYI.

**Comment by rossy** [comment]
Ah, thanks for testing. Glad it doesn't crash anymore.

> I still can't use --video-sync=display-resample.With it the player doesn't crash anymore but after certain time i'm ending up with black screen and sound only,without it is working fine.Just FYI.

I forgot to mention, ``--d3d11-flip=no`` sometimes fixes problems like this. Some drivers are buggy with flip-model present, especially on systems with switchable graphics.

**Comment by dnmTX** [comment]
@rossy "--d3d11-flip=no" crashing the player with "lost device" error right away,but.....(there is one big BUT this time)....i just checked the NVIDIA forum's feedback on the latest driver(388.71) and many experiencing the same error( "rendering device lost"...."DXGI_ERROR_DEVICE_REMOVED" to name a few),and most of the complaints are from laptop users so i'm certain now that this is a driver/Windows 10 related bug and has nothing to do with the player(Chromium is also affected from the same bug).So i'll just wait for the next driver to see if NVIDIA will resolve those issues,no need to bother you further with something that it turns out not really player related .Just another FYI :-)
