### ISSUE TITLE
VOCTRL_PERFORMANCE_DATA possible undefined behaviour and race conditions

### ISSUE THREAD

**Issue by Akemi** [mpv-player/mpv#5322]
can happen on the latest git master. @wm4 [noticed](https://github.com/mpv-player/mpv/pull/4833#discussion_r159027989) that current implementation of VOCTRL_PERFORMANCE_DATA and the voctrl_performance_data function is faulty since VOCTRL is not thread safe. this can lead to undefined behaviour and race conditions.

i can't provide any reproduction steps or the rest for the usual issue template, since i can't reproduce anything and for now it's only a theoretical issue.

**Comment by wm4** [comment]
This is specifically about `mp_frame_perf.desc`, which appears to be set to memory that's not only dynamically allocated, but could get reallocated during rendering.

**Comment by wm4** [comment]
Also, as long as memory pointed to by `desc` actually doesn't get clobbered, this might have been OK for `vo_gpu`, but it won't work for `opengl-cb` because that one has more complicated asynchronous behavior.

**Comment by kasper93** [comment]
This is actually fixed by 9fd4ae9529f749010cfd26e58ad2a7141f63b609
