### ISSUE TITLE
mpv does not automatically detect UHD bluray filesystem structure

### ISSUE THREAD

**Issue by kkkrackpot** [mpv-player/mpv#5325]
Hi,

Is it possible to make auto-playback for UHD structure, similar to that of BD structure?

With BD structure (i.e. ripped disk: BDMV, STREAM, etc), when launched like `mpv /path/to/bd-structure-on-disc`, mpv looks for the biggest `.ts` file in STREAM dir and starts playing it back automatically.

With UHD structure it currently does nothing.

AFAIK `libbluray-1.0.2` already has some support for UHD.

PS. It's simply kinda annoying to navigate through structure dirs with an IR remote, and to find the right `0000x.ts` among dozens.
  
UPD. Currently UHD playback works as `mpv bd:// --bluray-device=/path/to/structure`

**Comment by wiiaboo** [comment]
What's the directory structure of a UHDBD? For simple BD, mpv checks for `MovieObject.bdmv` or `BDMV/MovieObject.bdmv`.

**Comment by kkkrackpot** [comment]
@wiiaboo It's similar to BD, but not identical -- unfortunately, that's all that I can tell...
Here is the output of `ls -lahR` over a sample of UHD structure http://sprunge.us/jHJd
