### ISSUE TITLE
Checking for Libav/FFmpeg library versions?

### ISSUE THREAD

**Issue by Geyup** [mpv-player/mpv#5327]
I'm compiling 0.28.0 in Slackware 14.2 x64 using the mpv-build scripts, being compiled from a slackware .build script...

I downloaded the updated mpv-build scripts dated Dec 6th that were just added in, but I'm still having problems, I am getting this at the terminal;

 no ('libavutil >= 56.6.100 libavcodec >= 58.7.100 libavformat >= 58.0.102 libswscale >= 5.0.101 libavfilter >= 7.0.101 libswresample >= 3.0.100' not found) 
Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.

0.27.0 compiled just fine, and I forgot is it also using libav as well as ffmpeg?

Maybe the mpv-build scripts need fixing, I would assume they pull in everything needed?

I forgot, for 0.27.0 I had it pulling from git for the ```release versions```, am I suppose to now grab the ```ffmpeg-master``` for mpv now?

#./use-mpv-master
./use-mpv-release
#./use-ffmpeg-master
./use-ffmpeg-release

Hmm

**Comment by CounterPillow** [comment]
0.28 needs ffmpeg-master for now until ffmpeg makes another release.

**Comment by Geyup** [comment]
Ok I was just thinking that...

Thanks

**Comment by Geyup** [comment]
Hey maybe you need a ```Buckwheat Pillow``` to sleep better!

They're great!

Cheers
