### ISSUE TITLE
0.28.0 Doesn't Play & No Messages From A Terminal...

### ISSUE THREAD

**Issue by Geyup** [mpv-player/mpv#5328]
I compiled 0.28.0 from source on Slackware 14.2 x64 using the mpv-build scripts, combined into a Slackware build script.

I use SpaceFM file manger and I have videos assigned to play from mpv if I click on them in the file manager. Nothing happens when I click to play a video.

Next I ran mpv from a termial with no options like the below example and nothing happend and no mesages/errors from the terminal;

```mpv /path/to/video/video.mp4```

Here's the output of mpv;

```$>mpv```

mpv 0.28.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sat Dec 30
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.8.100
   libswresample   3.0.101
ffmpeg version: N-89660-g97b89432e4

How can I debug this to figure out why this is not playing?

Hmm, well this is the first time I've ever compiled mpv against the ffmpeg master git, instead of the release version, and before, this, I've used mpv since it came out and it's never crapped till now... :(

Below is how the build script looks;

PRGNAM=mpv
VERSION=${VERSION:-0.28.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_foo}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/foo}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
tar xvf $CWD/$PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION
chown -R root:root .
find . \
\( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
  -o -perm 511 \) -exec chmod 755 {} \; -o \
 \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;

#./use-mpv-master
./use-mpv-release
./use-ffmpeg-master
#./use-ffmpeg-release

./rebuild -j4

cd $TMP/$PRGNAM-$VERSION/$PRGNAM
./waf install --destdir=$PKG

mkdir -p $PKG/usr/man
mv $PKG/usr/share/man/man1 $PKG/usr/man

rm -rf $PKG/usr/share/man

if [ -e $PKG/usr/man ]; then
    find $PKG/usr/man -type f -exec gzip -9 {} \;
    for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
fi

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cp -a \
   Copyright \
  $PKG/usr/doc/$PRGNAM-$VERSION
  
cp $TMP/$PRGNAM-$VERSION/mpv/DOCS/{encoding.rst,tech-overview.txt} $PKG/usr/doc/$PRGNAM-$VERSION

cat $CWD/README.md > $PKG/usr/doc/$PRGNAM-$VERSION/README.md
cat $CWD/README.mpv > $PKG/usr/doc/$PRGNAM-$VERSION/README.mpv
cat $CWD/README.slack > $PKG/usr/doc/$PRGNAM-$VERSION/README.slack

mv $PKG/etc/mpv/encoding-profiles.conf $PKG/usr/doc/$PRGNAM-$VERSION/encoding-profiles.conf
rm -rf $PKG/etc

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}

**Comment by Geyup** [comment]
I tried compiling mpv from master instead of release and it didn't help, still won't play...

Hmm odd

**Comment by kevmitch** [comment]
Well `vo=vdpau` basically invalidates most of the subsequent options as they only apply to the default `vo=gpu` (in most cases this is the same as the old `vo=opengl`). Also `opengl-hq` is depricated in favour of `gpu-hq` now.

**Comment by Geyup** [comment]
Are you saying to use ```vo=gpu-hq```? Because I don't have those options,  ```mpv --vo=help``` doesn't show this option.

In 0.27.0 this use to be my old config, can you please recommend to me what I use now?

vo=opengl-hq
hwdec=vdpau
geometry=50%x50%+50%+50%
ao=alsa
volume=50
terminal=no

**Comment by CounterPillow** [comment]
`profile=gpu-hq`

vo=opengl-hq has been deprecated for a while now, which terminal output in 0.27 or earlier versions would've told you

>No Messages From A Terminal...

That's because you set `terminal=no`.

**Comment by Geyup** [comment]
THANKS

**Comment by Geyup** [comment]
I forgot to ask, for an nvidia gpu, just video watching, are these good settings?

vo=gpu
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
hwdec=vdpau
geometry=50%x50%+50%+50%
ao=pulse
volume=50
cache=auto

Thanks

**Comment by lachs0r** [comment]
If you remove hwdec=vdpau or replace it with hwdec=auto (or auto-copy) then 
yes. Otherwise using -hq settings is pointless as the hwdec API might do its 
own shitty conversion/scaling. If you can, and quality/non-glitched playback 
is your priority, go without hwdec.

**Comment by Geyup** [comment]
Thanks ```hwdec=auto``` it is... :)
