### ISSUE TITLE
No vaapi-copy for VP9 with mesa-git, ffmpeg-git and mpv-build-git

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5329]
GPU: AMD RX460

FFmpeg 3.0 has supported VP9 VA-API acceleration:
https://www.phoronix.com/scan.php?page=news_item&px=FFmpeg-3.0-Released

### mpv version and platform
```
mpv 0.28.0-45-gff506c1e49 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.8.100
   libswresample   3.0.101
ffmpeg version: N-89660-g97b89432e4
```
### Reproduction steps
hwdec=vaapi-copy
### Expected behavior
vaapi-copy
### Actual behavior
software decoding
### Log file
[mpv.log.zip](https://github.com/mpv-player/mpv/files/1595077/mpv.log.zip)
### Sample files
Any videos which are downloaded from YouTube

**Comment by kevmitch** [comment]
Why is this a new issue and not part of #5305?

**Comment by Gusar321** [comment]
There's no VP9 decoder on your graphic card. A simple vainfo could have told you that.

**Comment by JulianLai** [comment]
@kevmitch Because in #5305 I'm talking about the vaapi zero copy video decoding, here is the vaapi-copy acceleration, vaapi-copy works for my RX460

@Gusar321 What! It's the problem of libva again! Why do they lack so many things?

**Comment by Gusar321** [comment]
No, the problem isn't libva. It's exactly as I said, there is no VP9 decoder on your card. libva can't magically add what isn't there.

**Comment by JulianLai** [comment]
@Gusar321 But here says it has the hardware implementation: https://en.wikipedia.org/wiki/VP9

**Comment by Gusar321** [comment]
In Windows there's a hybrid (CPU+shaders) decoder, but hybrid decoders are a lot of effort for little gain, so they're generally not available in Linux. Linux supports fixed-function decoders, but there's no AMD hardware currently (not even Vega) with a fixed-function VP9 decoder.

**Comment by aufkrawall** [comment]
Raven Ridge supposedly has native VP9 decoding, probably even 10 bit.
But this hasn't been confirmed anywhere afaik, I start believing once I see it.
