### ISSUE TITLE
[Feature Request] Option to copy screenshot to clipboard, instead of/in addition to saving to file

### ISSUE THREAD

**Issue by enchained** [mpv-player/mpv#5330]
In the modern days of messengers it is really useful to have this feature, and you can just paste the screenshot somewhere, instead of looking for a file it was saved to.

Specifically I want this cause of Plex Media Player OSD which has no way to hide for screenshot taking, so I rarely use it on my laptop, and can't recommend PMP to friends cause of that.

So, in hopes I could bind a PMP keyboard input to an mpv command, I wish there was a command for something like that.

**Comment by thebombzen** [comment]
You can already do this if you do a bit of work yourself. You can use a custom Lua script and a custom keybind to call it (or rebind `s`) to screenshot to some png file, and then run a command that copies that file into the clipboard.

**Comment by enchained** [comment]
Thanks, I'll try that. But from what I've heard, mpv scripting is disabled for Plex Media Player, and even if I replace it with normal libmpv, it will probably be overwritten on every update. That makes it even harder to share with my friends, so I thought I could propose it as a core feature.

**Comment by zc62** [comment]
Why don't you require this feature from Plex? If something can be done via a user script, but the player using mpv disabled scripting, shouldn't that player be complained about?

**Comment by zc62** [comment]
[Here is the script.](https://github.com/zc62/mpv-scripts/blob/master/screenshot-to-clipboard.js)

**Comment by enchained** [comment]
Thank you very much! I believe some people already requested OSD-free screenshots from Plex, and were directed to config input binding to mpv features instead. And then I found out mvp in PMP can only save to file. I'll try to request that feature from Plex again, or at least an option to support scripting or this specific script.

**Comment by kevmitch** [comment]
It's now up to PMP to enable scripting or implement this feature in their own interface. For the time being, this is unlikely to be integrated into the mpv core.

**Comment by kohane27** [comment]
If anyone is looking for a Linux version, here's [clipshot.lua](https://github.com/ObserverOfTime/mpv-scripts/blob/master/clipshot.lua)

**Comment by promid** [comment]
Is there any script for MAC OS?

**Comment by enchained** [comment]
@promid You can try [clipshot.lua](https://github.com/ObserverOfTime/mpv-scripts/blob/master/clipshot.lua) mentioned above, from its code it looks like it's cross-platform.

**Comment by redoC-A2k** [comment]
In case clipshot.lua not working on your system , change the target from "image/jpeg" to "image/png"

https://stackoverflow.com/questions/59385093/copying-a-non-png-image-to-the-x-clipboard

**Comment by jamesWalker55** [comment]
Here's a script for Windows that uses the [clipboard](https://github.com/Slackadays/Clipboard) utility:

https://gist.github.com/jamesWalker55/68398be4f29f537dee37668e5cb9fd70

In your `input.conf`, add something like:

```
Ctrl+c script-binding screenshot-to-clipboard
```
