### ISSUE TITLE
Build Instructions for tvOS

### ISSUE THREAD

**Issue by coreyjv** [mpv-player/mpv#5331]
I’d like to use this as a base for a custom tvOS based player. I don’t have a lot of experience building products like this from source. Would it be possible to have someone create a more detailed set of instructions for different build environments?

Thanks for your time!

**Comment by coreyjv** [comment]
Would it be possible to get an update on this item please? Thanks!

**Comment by CounterPillow** [comment]
Have you made any effort to figure it out yourself so far? You're the person using whatever tvOS is, after all.

**Comment by coreyjv** [comment]
I have not as this is a bit out of my comfort zone. If it's something that the maintainers won't provide or don't have time for I'd rather have them be upfront about it.

**Comment by Argon-** [comment]
Apparently nobody here as ever used tvOS so you are ahead of experience anyway. It's probably faster for you to figure it out, considering you also need/want to embed it into an own video player for the same OS.

**Comment by coreyjv** [comment]
If I had to guess the build instructions are nearly identical to iOS. I see a sample for iOS in the repo so I presume someone has built it for iOS in the past. Would anyone have any information they could share regarding that?

**Comment by wm4** [comment]
I think @tmm1 built for iOS once. But I wouldn't expect anyone can give you detailed steps or so, and the build result would be a libmpv binary only, which you'd have to know how to use.

**Comment by tmm1** [comment]
See https://github.com/mpv-player/mpv/pull/3682#issue-184049753

**Comment by JLehman17** [comment]
Trying to build for tvOS fails right now because of a check for `fork()` in the wscript.
https://github.com/mpv-player/mpv/blob/master/wscript#L155

In the tvOS headers fork is defined
`pid_t	 fork(void) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;`

so running `./waf configure` gives the error
```
Checking for development environment                              : posix not found
Unable to find either POSIX or MinGW-w64 environment, or compiler does not work.
```
It's an easy thing to fix when building but I thought it should be known.

**Comment by Akemi** [comment]
@JLehman17 would you mind sending an PR?
