### ISSUE TITLE
how to incorporate lua scripts in libmpv

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5336]
### mpv version and platform
MPV 0.28 by lachs0r
Windows 8.1

I would like to know how to incorporate lua scrips in Libmpv
I have to create a folder called "scripts" in the directory where the "mpv-.dll" dll is, just as I do not understand much how to incorporate a custom configuration file in libmpv. Can somebody help me? Thank you very much!

**Comment by Jj0YzL5nvJ** [comment]
Put the "scripts" folder inside your "%APPDATA%\mpv\" route.

**Comment by EzeKees** [comment]
Perfect, thank you very much !!!

**Comment by wm4** [comment]
https://github.com/mpv-player/mpv/blob/master/libmpv/client.h#L387
