### ISSUE TITLE
--loop=inf does not work as expected

### ISSUE THREAD

**Issue by hutou** [mpv-player/mpv#5337]
### mpv version and platform

$ mpv
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Fri Dec 15 18:31:42 CET 2017
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.1

$ uname -a
Linux xps15al 4.14.9-1-ARCH #1 SMP PREEMPT Tue Dec 26 00:18:37 UTC 2017 x86_64 GNU/Linux

### Reproduction steps
Using --start [time], --end [time] and --loop=inf options shows the issue, as in the following command line :
$ mpv --no-audio --start 10:00.000 --end 10:05.000 --loop=inf "test.avi"

### Expected behavior

--loop=inf should cause mpv to play indefinitely the start/end time sequence. This was effectively the case in previous version (before june 2017, approximatively)

### Actual behavior
After playing the sequence, mpv restart at time 00:00:00 instead of --start [time]

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/1597111/mpv.log)

### Sample files

Any avi file shows the issue

**Comment by haasn** [comment]
You want `mpv --ab-loop-a=10:00 --ab-loop-b=10:05`

**Comment by thebombzen** [comment]
Funny that you mention this. There was a bit of discussion among the developers recently on exactly how these options should interact, and the conclusion was that `--loop=inf` should start from the beginning of the file even if `--start` is set. 

What you're looking for is the ab-loop feature. You can set `--ab-loop-a=10:00` and `--ab-loopb-b=10:05`, which will cause it to seek to `10:00` when it reaches `10:05`. However, `--start` is used in place of `--ab-loop-a` if it's not found, so to do what you're looking to do, you can run:
```
mpv --no-audio --start=10:00.000 --ab-loop-b=10:05.000 "test.avi"
```

**Comment by hutou** [comment]
I could get it to work properly only when using both `--start` and `--ab-loop-a` options (and `ab-loop-b`, of course), as in :

`mpv --no-audio --start=10:00.000 --ab-loop-a=10:00.000  --ab-loop-b=10:05.000 "test.avi"`

Using `ab-loop-a` and `ab-loop-b` only doesn't work : mpv start at 0:00:00
Using `--start` and `--ab-loop-b` only neither works : mpv **re**start at 0:00:00

Problem solved, anyway.
Thanks

**Comment by thebombzen** [comment]
It should as of mpv 0.28.0. Try again with the last git master or the latest release.

**Comment by thebombzen** [comment]
Specifically, it should work that way as of ff7e2946103ce35da702e57e03012c29215017d2. If it doesn't, that's a bug.

**Comment by thebombzen** [comment]
Well, the problem appears solved for you and you won't report back about a potential bug. If you have any more problems then open a new issue.
