### ISSUE TITLE
Phantom Subtitle Track

### ISSUE THREAD

**Issue by JacksonEdmonds** [mpv-player/mpv#5341]
Running current shinchiro Windows build (20171229)

I have a handful of specific files for which, when opened, mpv informs me that there is a subtitle track where there should not be one. If I switch to the subtitle track it doesn't appear to have any content, and, moreover, it is not visible in other media players (mplayer, vlc), nor seen by the likes of ffmpeg or mkvmerge. The "phantom" subtitle track persists through reencoding.
While there may be something amiss with the files I'm trying to play back, given this issue appears to be limited to mpv I thought it may be a program specific bug.
I've attached a sample of the original file, a reencoded version of that sample and the log file.

original: https://mega.nz/#!rRkQWKYZ!U2OMJsnfkIorb3Z1NJCU30mMH0bk9ZZuo-XCWqRRvrs
reencode: https://mega.nz/#!HUtVgATa!pgS05H1KzTPmCA98Z3KlmV-ASiLk7zz1dLFVefCskK8
log: https://mega.nz/#!bFtAHJKS!DvlyDzluGw7BAPq6Ak9nrlRVhgSz4_BEeTuX0MNBOus

Thanks for any assistance.

**Comment by kevmitch** [comment]
Links don't work. Please use https://0x0.st/ and / or http://sprunge.us/

**Comment by JacksonEdmonds** [comment]
Apparently github breaks a link if you use <ctrl+k> to "add a link".
Added links without wrapping in code. Should now work.

**Comment by wiiaboo** [comment]
Other players don't detect it because they don't support eia_608 closed captions. This isn't an issue.
