### ISSUE TITLE
Can mpv use the amdvlk? There is a warning for RADV

### ISSUE THREAD

**Issue by JulianLai** [mpv-player/mpv#5344]
### mpv version and platform
```
mpv 0.28.0-45-gff506c1e49 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.8.100
   libswresample   3.0.101
ffmpeg version: N-89660-g97b89432e4
```
### Reproduction steps
gpu-api=vulkan
### Expected behavior
No Warning
### Actual behavior
WARNING: radv is not a conformant vulkan implementation, testing use only.
### Log file
[vulkan.log.zip](https://github.com/mpv-player/mpv/files/1600627/vulkan.log.zip)

**Comment by zc62** [comment]
I don't think this warning is produced by mpv. It is from the graphic card driver you installed. According to the log, `gpu-api=vulkan` runs normally. (Why do you expect there should be no warning in the first place)
