### ISSUE TITLE
mpv fails at jpeg EXIF orientation

### ISSUE THREAD

**Issue by SteveJobzniak** [mpv-player/mpv#5350]
### mpv version and platform

git 0e311fc (21 days ago)

### Reproduction steps

- Clone this repository for a complete suite of EXIF test images: https://github.com/recurser/exif-orientation-examples
- Play all of those images in mpv.

### Expected behavior

- All images should look identical (rotation and flipping-wise), because they contain EXIF orientation data to tell the viewer how to display the pixels.

### Actual behavior

- mpv does not read the EXIF `orientation` flag, so all images are displayed as raw pixel data which leads to crazy rotation and flipping issues.

### Why?

If you try viewing these images in any other image viewer, they'll all display them correctly (all in the same orientation). Mpv on the other hand fails to display them correctly.

This is a major issue when using mpv as an image viewer, because most images these days (from digital cameras and phones) use EXIF orientation to tell the viewer how to display the image.

Trying to use mpv as an image viewer currently leads to a sad experience where images are rotated and flipped into crazy angles, rather than being displayed correctly. ;-)

What's necessary: An EXIF reader, which checks the orientation and applies the rotation/flipping described in the EXIF `orientation` value.

**Comment by SteveJobzniak** [comment]
Okay here's more info:

4 years ago, ffmpeg added EXIF metadata reading:
http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=bb4e1b4cf910af0de2bc884c75544603c40010cc

But they didn't (according to wm4 and my tests) hook it up to ffmpeg's internal rotation/flipping code.

As a result, you can try this: `ffmpeg -i Landscape_2.jpg test.png` and the output will be incorrect (flipped rather than natural orientation).

So this seems to be ffmpeg's fault.

**Comment by SteveJobzniak** [comment]
This 3 year old ticket seems related:

https://trac.ffmpeg.org/ticket/4149

And here's a very old ticket where they say that ffmpeg is supposed to autorotate by default:

https://trac.ffmpeg.org/ticket/515

**Comment by SteveJobzniak** [comment]
Okay this is now confirmed to be an upstream ffmpeg issue.

They added EXIF reading 4 years ago.

They added autorotation for videos 3 years ago (which is on by default).

It's just a small matter of adding autorotation for JPEGs too. I'll report it to their tracker as soon as `trac.ffmpeg.org` comes back to life (it's giving database timeout errors at signup)...

**Comment by SteveJobzniak** [comment]
Alright, the upstream ticket is now here:

https://trac.ffmpeg.org/ticket/6945#ticket

It seems like a very trivial fix since all the code for EXIF + vflip/hflip/rotate is already in ffmpeg. But I would definitely just screw it up since I don't know their codebase.

As for mpv: What do you think? Should it implement some "if ffmpeg < some future fixed version, manually read the metadata via API and apply the vflip/hflip/rotate filters"? Currently, mpv is really bad as an image viewer (try the test files in post 1 and you'll see). Perhaps it's worth fixing retroactively regardless of ffmpeg version, at least if it's trivial to read the metadata, check for `orientation`, and apply the vflip/hflip/rotate filters.

**Comment by thebombzen** [comment]
FWIW, `mpv` does respect orientation tags in mp4 videos.

**Comment by SteveJobzniak** [comment]
@thebombzen Is that due to mpv's conscious choice, though? Or is it auto-handled by ffmpeg? Because ffmpeg [has auto-orientating code for videos](http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=f5b26fbc2f564831b337f1de9faaaf6753a03871) (which turns the video straight by inserting some vflip/hflip/rotate filters automatically), but doesn't have that for jpeg files.

If mpv has special-cased mp4 files to fix orientation then it would be a good idea to fix JPGs too. Because it seems like ffmpeg are okay with putting this on the backburner and fixing JPG decoding in 3-7 years or so (look at the ticket I opened; it's priority "wish" aka "[desirable to have but no urgency](https://github.com/mpv-player/ffmpeg-mpv/blob/master/doc/issue_tracker.txt)").

**Comment by thebombzen** [comment]
I just did some testing, and FFmpeg also respects the rotation metadata tags for MP4 video files, but does not respect the rotation EXIF tags for JPEG images. You'd have to take this up with FFmpeg to deal with that.

**Comment by SteveJobzniak** [comment]
@thebombzen Yes, it's an ffmpeg bug. Sadly it's on the backburner (one of the lowest priority tickets), so I guess mpv/ffmpeg is going to need a few years to be unbroken. I'd love to delve deep into ffmpeg's code and fix this bug myself if I had time. Some people say "I have no time" and lie about it. I _literally_ have no time though. Well, I guess the upshot of that is that since I don't have time for the computer (at all), I won't have time to use mpv at all and therefore won't be annoyed anymore at all the badly decoded/misrotated JPGs. ^_^
