### ISSUE TITLE
[Feature Request] add support for you-get

### ISSUE THREAD

**Issue by hiberabyss** [mpv-player/mpv#5351]
[you-get](https://github.com/soimort/you-get) is a similar tool like youtube-dl, could it also be supported by mpv with option like `--ytdl-raw-options`?

Thanks!

**Comment by wm4** [comment]
Does it have any advantages over youtube-dl?

**Comment by wiiaboo** [comment]
Anything over youtube-dl besides supporting less sites (no Twitch support, for one)?

**Comment by Hrxn** [comment]
Yeah, less sites maybe, but different sites. Mainly support for lots of video portals from Asia..

**Comment by wiiaboo** [comment]
And broken json output:
```
It seems that your ffmpeg is a nightly build.
Please switch to the latest stable if merging failed.
{...
```

**Comment by hiberabyss** [comment]
`you-get` has better support for some Chinese video website.

**Comment by wiiaboo** [comment]
It'd need to be another script anyway, since its json has absolutely nothing to do with youtube-dl's, no format selection, basically almost no features found in youtube-dl other than the urls themselves.

**Comment by wm4** [comment]
Such a script could be added if:
1. you-get can return the media URL (plus anything needed to access it - youtube-dl returns a JSON that includes HTTP referrer and cookies)
2. Someone actually writes the mpv lua script

Though I honestly wonder why the author started this, instead of adding support for those extra sites to youtube-dl.

**Comment by Argon-** [comment]
It's even written in the same language, the heck. He really should have added extractors to youtube-dl.

Maybe you can pipe its output into mpv, although that might not work in some cases (depends on the kind of stream).

**Comment by Hrxn** [comment]
Maybe because you-get is intended to be more than just for videos, e.g. it can download pictures from Instagram, Tumblr, etc. Although only single items, per link, as far as I know.

**Comment by Argon-** [comment]
Well youtube-dl supports these sites as well. I'm sure you could add images as some kind of dummy format into the existing extractors.
