### ISSUE TITLE
Weird artifacts with d3d11

### ISSUE THREAD

**Issue by rld243** [mpv-player/mpv#5353]
### mpv version and platform

Windows 10 Fall Creators Update (Build 16299)
Nvidia GTX 960 (388.71)

mpv 0.28.0-74-ga9a4d6349a Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Thu Jan  4 16:47:13 UTC 2018
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.10.100
   libswresample   3.0.101
ffmpeg version: N-89690-g18fbfd7bf8

### Reproduction steps

Open any file with --no-config --gpu-api=d3d11 --scale=ewa_lanczossharp and go fullscreen

### Expected behavior

Video should work fine

### Actual behavior

Have some weird artifacts
Examples:
https://0x0.st/sPnr.png
https://0x0.st/sPns.png
Doesn't happen without --scale=ewa_lanczossharp or with --gpu-api=opengl

### Log file

http://0x0.st/sPnK.txt

### Sample files

Happens with any video (at least with any *.mkv I have)

**Comment by dnmTX** [comment]
Same here when using ewa_lanczos with d3d11,after awhile start having black screen with sound only(.mkv file).Uploading log file as well for better troubleshooting.
P.S. No problems with spline36 also same GPU driver as OP
[log.txt](https://github.com/mpv-player/mpv/files/1604260/log.txt)

**Comment by zc62** [comment]
Strange. I do observe these artifacts (though not as serious as you observed) with shinchiro's build (20180104). But when I was trying my own build, artifacts were gone.
Logs: 
[sourceforge_010418.log](https://github.com/mpv-player/mpv/files/1605133/sourceforge_010418.log)
[my_build.log](https://github.com/mpv-player/mpv/files/1605134/my_build.log)
Windows 7, GTX970 388.71

**Comment by shinchiro** [comment]
This my guess. Probably this is another spirv-cross bug yet? Too bad mpv doesn't print spirv-cross git version

**Comment by zc62** [comment]
I was using google/shaderc@98ab88b and rossy/crossc@ad956db

**Comment by rossy** [comment]
I get this as well. It seems to be a change in how barriers are emitted by glslang, which is exposing SPIRV-Cross's limited support for SPIR-V barriers. Working on a fix now.

**Comment by rossy** [comment]
This should be fixed in SPIRV-Cross git master.

**Comment by dnmTX** [comment]
Thank you @rossy  for taking care of this.Much appreciated.
