### ISSUE TITLE
cannot seem to make livestreamer works with hls parameters

### ISSUE THREAD

**Issue by jwallet** [mpv-player/mpv#5356]
more like a question...

### mpv version and platform
Windows builds by shinchiro, windows 10 x64 bits, mpv-x86_64-20171216-git-e1ac0c1.7z, 2017-12-16
cannot get the lastest release because mpv cannot run a m3u8 file without crashing, this was the lastest version to work properly. I have no idea what version this archive is, there is not even a txt file about that.

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
LiveStreamer and StreamLink used to work properly with all mpv version since they forked with MPlayer2, the lastest version above is the last one that does not crash while using `--player-passthrough=hls`, but that's not my issue.

I'm wondering what arguments (--) i need to make hls live edges to work, so i can open a m3u8 stream at the current time that i want like vlc and mpc do. With livestreamer if i set `--hls-live-edge=1800` it will take my current live stream but will start 2hours from now. This way i can make the live stream available from start for everyone. and also if i use this parameter to be 5 minutes behind the live stream, and adds a nice buffer and the stream stop lagging.

[image of hls parameters (livestreamer)](https://user-images.githubusercontent.com/23088305/34621838-b4aa8e5a-f218-11e7-802c-a75c24fd875d.png)

### Expected behavior
- be able to start a Live stream from the beginning (like a PVR)
### Actual behavior
- it ignores those parameters, but VLC and MPC do this kind of things, however not better than MPV that can seek into a Live HLS stream, the only player able to do that.

 [Livestreamer code about hls - live_edge](https://github.com/chrippa/livestreamer/blob/ab80dbd6560f6f9835865b2fc9f9c6015aee5658/src/livestreamer/stream/hls.py)
```python
          if self.playlist_sequence < 0:
            if self.playlist_end is None:
                edge_index = -(min(len(sequences), max(int(self.live_edge), 1)))
                edge_sequence = sequences[edge_index]
                self.playlist_sequence = edge_sequence.num
            else:
                self.playlist_sequence = first_sequence.num
```

**Comment by wiiaboo** [comment]
Works fine here with `--player-passthrough=hls --hls-live-edge=1800`, but I don't understand what's the problem. You want it to playing after 1800 segments have passed?

**Comment by jwallet** [comment]
yes, cause live stream are always at the last segment, so going back of XXXX (ex: 1800, 60*60*12) will set the stream to the first segment, so someone could decide to follow the live stream, or watch it from anywhere he wants, like the replay (5/10/30/from the start) on a PVR. so if it does that on your side, it might be and error in my code. thanks for trying it on your side
