### ISSUE TITLE
Custom pause after playing a file

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5358]
MPV 0.28  by lachs0r
Good afternoon, I would like the developers of this wonderful player to add a feature, which would be the following:

I tell MPV to play 5 video files one behind the other
I would like, for example, when video 3 ends, MPV pauses to be configured by the user. For example: "After video 3, pause for 5 minutes and then automatically continue playback automatically."
It would serve a lot for libmpv.
Thank you very much!
PS: I looked in Issues if someone ever requested this feature but I did not find anything.

**Comment by TheAMM** [comment]
This is something solved with a script. Someone was already working on a custom playlist script to pause images for specific durations.

**Comment by EzeKees** [comment]
@TheAMM 
Hello, thank you very much for answering, but what script do you refer to? To a .lua?

**Comment by EzeKees** [comment]
@TheAMM 
If you mean the Leapfrog script
It's not what I'm looking for.
I do not know if it was understood well in the previous message, I'm from Argentina and I use the google translator to write.
I want that I can configure in a video that after the same one finishes reproducing, MPV pauses for a predetermined time and that after that time passes, the reproduction continues normally.
I see it as a useful option for LIBMPV

**Comment by TheAMM** [comment]
Not that one.
I don't use `libmpv` myself, but isn't that solvable by the software that embeds it? In the normal mpv, it's solvable by a lua script by forcing keep-open and then keeping track of time.
