### ISSUE TITLE
Archive.org playlists with youtube-dl

### ISSUE THREAD

**Issue by fresm** [mpv-player/mpv#5364]
### mpv version and platform

mpv 0.28.0-80-g1eec7d2315 @ Linux

### Reproduction steps

`mpv -v http://archive.org/details/78_please-pass-the-biscuits-pappy-i-like-mountain-music_w.-lee-odaniel-and-his-hil_gbia0008674a`

throws multiple "[stream] Failed to open" errors, but finally starts to play after several unsuccessful tries.

`youtube-dl http://archive.org/details/78_please-pass-the-biscuits-pappy-i-like-mountain-music_w.-lee-odaniel-and-his-hil_gbia0008674a` works much better

### Log
[pastebin](https://pastebin.com/tX8wDnCv)

**Comment by wm4** [comment]
This is because our ytdl script builds an EDL, which opens every item before starting playback. I don't get any opening errors though.

The only error comes from the mp3 used as EDL items apparently having a broken id3v2 tag.
