### ISSUE TITLE
mpv fails to build due to unresolved dependency

### ISSUE THREAD

**Issue by Dummweilbaum** [mpv-player/mpv#5367]
Latest mpv version from GitHub, Arch Linux Kernel 4.14.12-1

### Reproduction steps
Execute makepkg on PKGBUILD with latest Ffmpeg from git installed (but not ffmpeg-mpv, since it apparently was deprecated)
### Expected behavior
mpv is compiled
### Actual behavior
build fails with error "failed to install dependency 'ffmpeg-mpv'"

**Comment by lachs0r** [comment]
Complain to the package maintainer.
