### ISSUE TITLE
Confusion with mpv + ffmpeg 3.4.1 trying to compile - it fails early - could perhaps the waf configure script check for ffmpeg version in a more fine-tuned manner?

### ISSUE THREAD

**Issue by shevegen** [mpv-player/mpv#5370]
I just finished compiling ffmpeg 3.4.1 into the /usr/ prefix successfully without error:

INSTALL libavutil/xtea.h
INSTALL libavutil/tea.h
INSTALL libavutil/lzo.h
INSTALL libavutil/avconfig.h
INSTALL libavutil/ffversion.h
INSTALL libavutil/libavutil.pc
/Depot/Temp/ffmpeg-3.4.1/

Now I try the latest mpv github snapshot. I got it via the download button, where
I get a .zip file. I extracted it, did "py bootstrap" and then "./waf configure".

This gets me this:

Checking for OpenGL Win32 ANGLE Backend                           : egl-angle not found 
Checking for VDPAU acceleration                                   : yes 
Checking for VDPAU with OpenGL/X11                                : yes 
Checking for VAAPI acceleration                                   : yes 
Checking for VAAPI (X11 support)                                  : yes 
Checking for VAAPI (Wayland support)                              : yes 
Checking for VAAPI (DRM/EGL support)                              : yes 
Checking for VAAPI GLX                                            : yes 
Checking for VAAPI EGL on X11                                     : yes 
Checking for VAAPI EGL                                            : yes 
Checking for CACA                                                 : yes 
Checking for JPEG support                                         : yes 
Checking for Direct3D support                                     : win32-desktop not found 
Checking for libshaderc SPIR-V compiler (shared library)          : no 
Checking for libshaderc SPIR-V compiler (static library)          : no 
Checking for libshaderc SPIR-V compiler                           : shaderc-shared not found 
Checking for libcrossc SPIR-V translator                          : no ('crossc' not found) 
Checking for Direct3D 11 video output                             : win32-desktop not found 
Checking for Raspberry Pi support                                 : no 
Checking for iOS OpenGL ES hardware decoding interop support      : no 
Checking for OpenGL without platform-specific code (e.g. for libmpv) : libmpv-shared not found 
Checking for MALI via Linux fbdev                                    : no 
Checking for OpenGL context support                                  : yes 
Checking for Vulkan context support                                  : no ('vulkan' not found) 
Checking for EGL helper functions                                    : yes 
Checking for FFmpeg/Libav present                                    : yes 
Checking for libav* is FFmpeg                                        : no 
Checking for libav* is Libav                                         : no 
Checking for Libav/FFmpeg library versions                           : ffmpeg not found 
Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.

Unfortunately this ends here.

The error message does not tell me anything, I am sorry. The message "Git master is
recommended" does not tell me anything either. I assume that mpv suggest to me
to ... use ffmpeg git master? But why? 3.4.1 is very recent...

I also can not do anything with this error message. It tells me that it could not find
ffmpeg. What does it really mean? ffmpeg is there. All it of. I just compiled it from
source using the tarball URL http://ffmpeg.org/releases/ffmpeg-3.4.1.tar.xz.

I did not use any configure switches to fmpeg this time.

I then had an idea and removed all of libav* in /usr/lib/, then re-ran the waf
configure line after doing "make install" again at the extracted directory
where ffmpeg is (so "make install" should just copy the already compiled
files).

The error I got this time is different:

Checking for libav* is FFmpeg                                        : yes 
Checking for libav* is Libav                                         : no 
Checking for Libav/FFmpeg library versions                           : no ('libavutil >= 56.6.100 libavcodec >= 58.7.100 libavformat >= 58.0.102 libswscale >= 5.0.101 libavfilter >= 7.0.101 libswresample >= 3.0.100' not found) 
Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.

So the script notices that libav* is ffmpeg. But it still seems to notice
some stray older versions. Ok. I guess I am beginning to understand
that I can remove all old files, then it should work. But it was confusing
to me anyway.

My suggestion here is to let wav either detect this - OR specify which
version it wants to have or expects. The second error message is
more useful to me; the first one I would not have obtained if I would not
have removed some of the old files (with this strange check or libav*
which is, by the way, a bit weird - what if a user has several ffmpeg
versions? I understand that they should ideally use only one, but
I wonder about that blunt libav* check rather than a more fine-tuned
variant).

Sorry if this is a bit showing my impatience, I stayed up too long and
my wake-up script makes use of mpv right now, and I managed to
break it elsewhere by removing an old version of "libva", which made
me have to recompile mpv ....   :P

**Comment by CounterPillow** [comment]
>I assume that mpv suggest to me to ... use ffmpeg git master? But why? 3.4.1 is very recent...

because mpv 0.28 and beyond rely on newer ffmpeg API, which ffmpeg 3.4.1 does not include, and mpv will not support several API versions of ffmpeg.
