### ISSUE TITLE
How progressbar is updated when total duration of file is not known?

### ISSUE THREAD

**Issue by antonsviridenko** [mpv-player/mpv#5374]
I'm just curious,
for example, mpv is playing .mkv file which was interrupted while recording, so total duration is not written to MKV header, but anyway mpv somehow more or less accurately updates progressbar while playing,
can someone tell how it accomplishes that or place in code  where update happens?

**Comment by lachs0r** [comment]
It generates an index on the fly if possible (as is likely the case with your mkv file), otherwise falls back to raw stream position.
