### ISSUE TITLE
[input] Command cycle-values has trailing unused arguments: ' 1'.

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#5375]
### mpv version and platform
mpv 2:0.26.0+git1~trusty1 on Ubuntu 14.04.5 LTS

### Reproduction steps
A value before the last value in `window-scale` in `~/.config/mpv/input.conf` : 
BEFORE : 
$ grep "^[^#].*window-scale" .config/mpv/input.conf
Ctrl+d	cycle_values window-scale 0.75 1 1.5 2 2.5 3 3.5 4 1
AFTER : 
$ grep "^[^#].*window-scale" .config/mpv/input.conf
Ctrl+d	cycle_values window-scale 0.75 1 1.5 2 2.5 3 3.5 4 4.5 1

### Expected behavior
The new value is taken into account
### Actual behavior
[input] Command cycle-values has trailing unused arguments: ' 1'.
[input] Command was defined at /home/sebastien/.config/mpv/input.conf:12.
### Log file

LOG : [output.txt](http://paste.ubuntu.com/26355283/)

### Sample files

It is a keyboard shortcut definition issue, therefore it occurs every time when playing any file or URL you want.

**Comment by wm4** [comment]
This is because the command exceeds the internal static limit of command arguments.
