### ISSUE TITLE
Differences in config between Linux and Windows

### ISSUE THREAD

**Issue by Gfurst** [mpv-player/mpv#5376]
### mpv version and platform

I'm using both latest version from the official Arch repo, and the latest build from the suggested Windows downloads

### Expected behavior

I would expect them to behave somewhat equally, there are however some minor differences that caught my attention, specifically, there is visual cue for the cache at the bar, and the option cache-secs for windows is actually much higher and works for twitch streams, the cache is also represented by sec/size instead of secs+size.

I would expect them to be somewhat the same since Arch has a pretty recent version, unless of course there is big difference in build options for the said windows release.

**Comment by lachs0r** [comment]
Windows builds are 0.28.0 or newer. Arch packages 0.27.0, so that is not “pretty recent” enough.

**Comment by Gfurst** [comment]
ah that explains it, weird though, even the AUR pre-builds are versioned in 0.27, so I thought no way it had that much difference. Thanks
