### ISSUE TITLE
--af=pan... results in missing audio

### ISSUE THREAD

**Issue by mnn** [mpv-player/mpv#5379]
### mpv version and platform

0.28.0 Linux (Kubuntu 16.04 LTS)

### Reproduction steps

Run with `--af=pan=6:[1,0,0,0,0,0,0,1,0,0,0,0,1,1,1,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,1]`

### Expected behavior

Sound is mixed between channels as described by the vector.

### Actual behavior

No audio is present, not even silence - application is not in volume controls at all.

### Log file

https://gist.github.com/mnn/c12cf23643c9a448ca6c4341d8e271fc

### Sample files

Bug manifests on all tested files.

**Comment by sfan5** [comment]
looks like your filter syntax is wrong
<pre>
[pan] AVOption '@1' not found.
[pan] Can't configure libavfilter graph.
[af] Reinitialization did not work, audio filter 'lavfi-bridge' returned error code -2
[af] Could not create audio filter chain.
[cplayer] Error at audio filter chain pre-init!
</pre>

**Comment by mnn** [comment]
It was working fine in previous version (it does downgrade from 5.1 channels to 2.1). I failed to find documentation for this filter, I'll look again.

**Comment by CounterPillow** [comment]
Check here: https://ffmpeg.org/ffmpeg-filters.html#pan-1

**Comment by mnn** [comment]
I only found https://github.com/mpv-player/mpv/blob/master/DOCS/man/af.rst, but `pan` is missing.

> Check here: https://ffmpeg.org/ffmpeg-filters.html#pan-1

I am confused, how can I use this with mpv?

**Comment by CounterPillow** [comment]
With `--af=pan=etcetc`

mpv automatically bridges lavfilters.

**Comment by mnn** [comment]
Oh, thank you, I'll give it a try :).

**Comment by wm4** [comment]
The internal `pan` filter was removed, and it'll use libavfilter's now, which has different syntax.

**Comment by mnn** [comment]
For others facing similar problem, here's my solution (it converts 5.1 to 3.1):

    '--af=pan="5.1|FC=FC|FL=FL+0.5*FC+0.7*SL|FR=FR+0.5*FC+0.7*SR|LFE=0.5*LFE"'

The apostrophes are important. If you are using SMPlayer then you have to put it in audio filters field *without* apostrophes and `--af=`.

**Comment by zrhoffman** [comment]
Broke for me in Arch Linux a couple of days ago (I assume because the [ffmpeg package](https://www.archlinux.org/packages/extra/x86_64/ffmpeg/) was updated from `1:3.4-4` to `1:4.0-2` on 2018-05-13).

My filter (`af=pan=1:[0.5,0.5]`) used to take stereo input, mix it to mono, then copy it to the left and right channels.

It resulted in the following terminal output:

```
x@x:~ [0]$ mpv 'https://youtu.be/xxxxxxxxxxx
Playing: https://youtu.be/xxxxxxxxxxx
 (+) Video --vid=1 (*) (vp9 1920x1080 24.000fps)
 (+) Audio --aid=1 --alang=eng (*) 'DASH audio' (opus 2ch 48000Hz) (external)
[pan] AVOption '@1' not found.
[pan] Can't configure libavfilter graph.
Reinitialization did not work, audio filter 'lavfi-bridge' returned error code -2
Audio filter chain:
  [in] 48000Hz stereo 2ch floatp
  [pan (lavfi)] 0Hz empty 0ch ?? <-
  [out] 0Hz empty 0ch ??
  [ao] 0Hz empty 0ch ??
Could not create audio filter chain.
Error at audio filter chain pre-init!
Audio: no audio
VO: [gpu] 1920x1080 yuv420p
V: 00:00:00 / 00:03:15 (0%) Cache: 25s+1MB


Exiting... (Quit)
```

It turns out that replacing the filter with `audio-channels=1` makes it work the same way.
