### ISSUE TITLE
No sound when PCM encoded audio

### ISSUE THREAD

**Issue by xAubert** [mpv-player/mpv#5381]
### mpv version and platform

mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100

downloaded from CentOS7 repo

### Actual behavior

I get no sound when playing some video file. (see log)
Looks like the problem come from the pcm audio codec since I have sound on other videos using aac.

### Log file

mpv -v testFile.mov 
[cplayer] Command line options: '-v' 'testFile.mov'
[cplayer] mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       54.20.100
[cplayer]    libavcodec      56.26.100
[cplayer]    libavformat     56.25.101
[cplayer]    libswscale      3.1.101
[cplayer]    libavfilter     5.11.102
[cplayer]    libswresample   1.1.100
[cplayer] 
[cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --bindir=/usr/bin --libdir=/usr/lib64 --mandir=/usr/share/man --docdir=/usr/share/doc/mpv --confdir=/etc/mpv --disable-build-date --enable-libmpv-shared --enable-sdl2 --enable-encoding
[cplayer] List of enabled features: alsa any-gl asm atomic-builtins atomics audio-input avcodec-chroma-pos-api avframe-metadata avframe-skip-samples cdda cplayer debug-build dlopen drm dvbin dvdnav dvdread egl-drm egl-helpers egl-x11 encoding fchmod gbm gbm.h gcc-tls gl gl-x11 glibc-thread-name glob gnuc iconv jack jpeg lcms2 libass libass-osd libav libavdevice libavfilter libdl libm libmpv-shared librt libsmbclient libswresample libv4l2 linux-fstatfs lua nanosleep optimize oss-audio oss-audio-native plain-gl posix posix-or-mingw posix-spawn pthreads pulse resampler rubberband sdl2 shm standard-gl subprocess termios tv tv-v4l2 uchardet vdpau vdpau-gl-x11 vdpau-hwaccel videodev vt.h x11 xext xinerama xrandr xss xv zlib
[global] config path: '' -> '/home/x.aubert/.config/mpv'
[global] config path: 'mpv.conf' -/-> '/home/x.aubert/.config/mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/x.aubert/.config/mpv/config'
[global] config path: 'mpv.conf' -/-> '/home/x.aubert/.mpv/mpv.conf'
[global] config path: 'config' -/-> '/home/x.aubert/.mpv/config'
[global] config path: 'mpv.conf' -> '/etc/mpv/mpv.conf'
[global] config path: 'config' -/-> '/etc/mpv/config'
[cplayer] Reading config file /etc/mpv/mpv.conf
[cplayer] Setting option 'keep-open' = '' (flags = 4)
[cplayer] Setting option 'screenshot-format' = 'png' (flags = 4)
[cplayer] Setting option 'screenshot-png-compression' = '8' (flags = 4)
[cplayer] Setting option 'screenshot-template' = '~/Desktop/%F (%P) %n' (flags = 4)
[cplayer] Setting option 'loop-file' = 'inf' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[global] config path: 'input.conf' -/-> '/home/x.aubert/.config/mpv/input.conf'
[global] config path: 'input.conf' -/-> '/home/x.aubert/.mpv/input.conf'
[global] config path: 'input.conf' -> '/etc/mpv/input.conf'
[global] user path: '/etc/mpv/input.conf' -> '/etc/mpv/input.conf'
[ifo] Opening /etc/mpv/input.conf
[ifo/dvdnav] Opening /etc/mpv/input.conf
[file] Opening /etc/mpv/input.conf
[file] Stream opened successfully.
[input] Parsing input config file /etc/mpv/input.conf
[input] Input config file /etc/mpv/input.conf parsed: 2 binds
[osc] Loading script @osc.lua...
[global] config path: 'scripts' -/-> '/home/x.aubert/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/home/x.aubert/.mpv/scripts'
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'
[osc] loading mp.defaults
[osc] loading @osc.lua
[global] config path: 'lua-settings/osc.conf' -/-> '/home/x.aubert/.config/mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/home/x.aubert/.mpv/lua-settings/osc.conf'
[global] config path: 'lua-settings/osc.conf' -/-> '/etc/mpv/lua-settings/osc.conf'
[osc] lua-settings/osc.conf not found. 
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1
[cplayer] mouse_leave script-binding osc/__keybinding2
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3
[cplayer] shift+mouse_btn0 script-binding osc/__keybinding4
[cplayer] mouse_btn2 script-binding osc/__keybinding5
[cplayer] mouse_btn0_dbl ignore
[cplayer] shift+mouse_btn0_dbl ignore
[cplayer] mouse_btn2_dbl ignore
[cplayer] , force]
[cplayer] Run command: enable-section, flags=0, args=[input, ]
[cplayer] Run command: define-section, flags=0, args=[input_osc, del script-binding osc/__keybinding6
[cplayer] , default]
[cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]
[cplayer] Done loading @osc.lua.
[ytdl_hook] Loading script @ytdl_hook.lua...
[global] config path: 'scripts' -/-> '/home/x.aubert/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/home/x.aubert/.mpv/scripts'
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'
[ytdl_hook] loading mp.defaults
[cplayer] Run command: disable-section, flags=0, args=[input]
[global] config path: 'fonts' -/-> '/home/x.aubert/.config/mpv/fonts'
[global] config path: 'fonts' -/-> '/home/x.aubert/.mpv/fonts'
[global] config path: 'fonts' -/-> '/etc/mpv/fonts'
[osd/libass] Shaper: FriBidi 0.19.4 (SIMPLE) HarfBuzz-ng 1.3.2 (COMPLEX)
[global] config path: 'subfont.ttf' -/-> '/home/x.aubert/.config/mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/home/x.aubert/.mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/etc/mpv/subfont.ttf'
[global] config path: 'fonts.conf' -/-> '/home/x.aubert/.config/mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/home/x.aubert/.mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/etc/mpv/fonts.conf'
[osd/libass] Setting up fonts...
[ytdl_hook] loading @ytdl_hook.lua
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[cplayer] Run command: hook-add, flags=0, args=[on_preloaded, 2, 10]
[cplayer] Done loading @ytdl_hook.lua.
[global] config path: 'scripts' -/-> '/home/x.aubert/.config/mpv/scripts'
[global] config path: 'scripts' -/-> '/home/x.aubert/.mpv/scripts'
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'
[global] config path: 'watch_later' -> '/home/x.aubert/.config/mpv/watch_later'
[cplayer] Playing: testFile.mov
[cplayer] Running hook: ytdl_hook/on_load
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Run command: hook-ack, flags=0, args=[on_load]
[ifo] Opening testFile.mov
[ifo/dvdnav] Opening testFile.mov
[file] Opening testFile.mov
[file] Stream opened successfully.
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[lavf] avformat_find_stream_info() finished after 7662356 bytes.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[find_files] Loading external files in .
[global] config path: 'sub/' -/-> '/home/x.aubert/.config/mpv/sub/'
[global] config path: 'sub/' -/-> '/home/x.aubert/.mpv/sub/'
[global] config path: 'sub/' -/-> '/etc/mpv/sub/'
[global] config path: 'audio/' -/-> '/home/x.aubert/.config/mpv/audio/'
[global] config path: 'audio/' -/-> '/home/x.aubert/.mpv/audio/'
[global] config path: 'audio/' -/-> '/etc/mpv/audio/'
[cplayer] Running hook: ytdl_hook/on_preloaded
[cplayer] Run command: hook-ack, flags=0, args=[on_preloaded]
[cplayer]  (+) Video --vid=1 (*) (png)
[cplayer]  (+) Audio --aid=1 --alang=eng (*) (pcm_s16be)
[vo/opengl] Initializing OpenGL backend 'x11probe'
[vo/opengl/x11] X11 opening display: :0.0
[vo/opengl/x11] X11 running at 3840x1080 (":0.0" => local display)
[vo/opengl/x11] Detected wm supports NetWM.
[vo/opengl/x11] Detected wm supports FULLSCREEN state.
[vo/opengl/x11] Detected wm supports ABOVE state.
[vo/opengl/x11] Detected wm supports BELOW state.
[vo/opengl/x11] Display 0 (DP-4): [0, 0, 1920, 1080] @ 60.000000 FPS
[vo/opengl/x11] Display 1 (DP-6): [1920, 0, 3840, 1080] @ 60.000000 FPS
[vo/opengl/x11] Current display FPS: 60.000000
[vo/opengl] GLX chose FB config with ID 0xac29fd30
[vo/opengl] GLX chose visual with ID 0x27
[vo/opengl] Creating OpenGL 3.3 context...
[vo/opengl] GL_VERSION='3.3.0 NVIDIA 384.59'
[vo/opengl] Detected desktop OpenGL 3.3.
[vo/opengl] GL_VENDOR='NVIDIA Corporation'
[vo/opengl] GL_RENDERER='Quadro M4000/PCIe/SSE2'
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='3.30 NVIDIA via Cg compiler'
[vo/opengl] Loaded extension GLX_SGI_swap_control.
[vo/opengl] Loaded extension GLX_SGI_video_sync.
[vo/opengl] Loaded extension GL_NV_vdpau_interop.
[vo/opengl] Loaded extension GL_ARB_debug_output.
[vo/opengl] 16 bit texture depth: 16.
[vo/opengl] Reported display depth: R=8, G=8, B=8
[vo/opengl] Testing FBO format 0x805b
[vo/opengl] Create FBO: 16x16 (16x16)
[vo/opengl] Using FBO format 0x805b.
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Assuming 60.000000 FPS for display sync.
[vd] Container reported FPS: 25.000000
[vd] Codec list:
[vd]     png - PNG (Portable Network Graphics) image
[vd] Opening video decoder png
[vd] Not trying to use hardware decoding: codec png is not on whitelist, or does not support hardware acceleration.
[vd] Using software decoding.
[vd] Detected 12 logical cores.
[vd] Requesting 13 threads for decoding.
[vd] Selected video codec: png (PNG (Portable Network Graphics) image)
[ad] Codec list:
[ad]     pcm_s16be - PCM signed 16-bit big-endian
[ad] Opening audio decoder pcm_s16be
[ad] Requesting 1 threads for decoding.
[ad] Selected audio codec: pcm_s16be (PCM signed 16-bit big-endian)
[cplayer] Starting playback...
[vo/opengl/x11] Disabling screensaver.
[vo/opengl/x11] Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.
[vd] Decoder format: 1253x763 [0:1] rgba auto/auto/auto/auto CL=unknown
[vf] Video filter chain:
[vf]   [in] 1253x763 rgba rgb/bt.709/srgb/full CL=unknown
[vf]   [out] 1253x763 rgba rgb/bt.709/srgb/full CL=unknown
[cplayer] VO: [opengl] 1253x763 rgba
[cplayer] VO: Description: Extended OpenGL Renderer
[vo/opengl/x11] not waiting for MapNotify
[vo/opengl] Resize: 1253x763
[vo/opengl] Window size: 1253x763
[vo/opengl] Video source: 1253x763 (1:1)
[vo/opengl] Video display: (0, 0) 1253x763 -> (0, 0) 1253x763
[vo/opengl] Video scale: 1.000000/1.000000
[vo/opengl] OSD borders: l=0 t=0 r=0 b=0
[vo/opengl] Video borders: l=0 t=0 r=0 b=0
[vo/opengl] Testing FBO format 0x805b
[vo/opengl] Create FBO: 16x16 (16x16)
[vo/opengl] Using FBO format 0x805b.
[vo/opengl] No advanced processing required. Enabling dumb mode.
[vo/opengl] Texture for plane 0: 1253x763
[cplayer] set video colors output-levels=0 
[vo/opengl] recompiling a shader program:
[vo/opengl] [  1] color.rgba = 1.000000 * vec4(texture(texture0, texcoord0)).rgba;
[vo/opengl] [  2] // color conversion
[vo/opengl] [  3] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;
[vo/opengl] [  4] color = vec4(color.rgb * color.a, color.a);
[vo/opengl] [  5] // color mapping
[vo/opengl] [  6] // transparency checkerboard
[vo/opengl] [  7] bvec2 tile = lessThan(fract(gl_FragCoord.xy / 32.0), vec2(0.5));
[vo/opengl] [  8] vec3 background = vec3(tile.x == tile.y ? 1.0 : 0.75);
[vo/opengl] [  9] color.rgb = mix(background, color.rgb, color.a);
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/dejavu/DejaVuSans.ttf, 0, DejaVuSans
[cplayer] first video frame after restart shown
[lavf] Too many packets in the demuxer packet queues:
[lavf]   video/0: 110 packets, 421426940 bytes
[lavf]   audio/1: 0 packets, 0 bytes
[cplayer] playback restart complete
[statusline] AV: 00:00:00 / 00:00:05 (8%) A-V:  0.000
[cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding2]
[statusline] AV: 00:00:00 / 00:00:05 (12%) A-V:  0.000
[cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding2]
[statusline] AV: 00:00:00 / 00:00:05 (16%) A-V:  0.000
[lavf] EOF reached.
[statusline] AV: 00:00:01 / 00:00:05 (22%) A-V:  0.000
[cplayer] Run command: script-binding, flags=9, args=[osc/__keybinding2]
[statusline] AV: 00:00:02 / 00:00:05 (35%) A-V:  0.000
[cplayer] Run command: quit, flags=9, args=[0]
[cplayer] EOF code: 6  
[ad] Uninit audio decoder.
[vd] Uninit video.
[vo/opengl/x11] Enabling screensaver.
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Quit)
[ytdl_hook] Exiting...
[osc] Exiting...
[vo/opengl] flushing shader cache
[vo/opengl/x11] uninit ...

**Comment by CounterPillow** [comment]
>mpv 0.23.0 (C) 2000-2016

You're over a year out of date, try to use an up-to-date mpv with an up-to-date ffmpeg and see if you can still reproduce.

**Comment by xAubert** [comment]
solved after building with repo version. thx
