### ISSUE TITLE
Libmpv random error?

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5384]
### MPV 0.28 
Windows 8.1
### Reproduction steps
With c # I tell libmpv to play several files with their respective parameters, randomly, sometimes libmpv does not apply the commands correctly. (For example, it does not select a stream correctly)
It will be because I have to have activated the "--reset-on-next-file" option.
Thank you very much for your help and congratulations for this fabulous player!

**Comment by thebombzen** [comment]
It would be much more helpful to the developers if you were to say what you mean by "does not apply the commands correctly" or what those "respective parameters" are or what any of this has to do with `--reset-on-next-file`. You haven't provided enough information to diagnose the problem.

**Comment by EzeKees** [comment]
Thank you very much, I'm wrong version (0.27 to 0.28)
And updating the last one solved the problem, apart it was also an error of my code c #.
Please delete or close the issue. Thanks again
