### ISSUE TITLE
Independent rotate values for images and videos

### ISSUE THREAD

**Issue by danboid** [mpv-player/mpv#5385]
### mpv version and platform

0.26.0
Ubuntu 17.10

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Set a video-rotate value in mpv.conf, other than 0 (or 360)

### Expected behavior

I only want video files to get rotated when I am playing mixed image/video playlists, not image files too. It would be nice if images could use a separate rotate setting to videos.

### Actual behavior

All image files get rotated by the given amount as well as rotatable video files. Most of my home vids need to be rotated 90 degrees so I have that set as the default but the images don't require rotation. That leads nicely onto my next issue (feature request).

**Comment by wiiaboo** [comment]
Why not just fix your videos to have the correct metadata?

**Comment by zc62** [comment]
In your `mpv.conf`:
```
video-rotate=90
[extension.png]
video-rotate=0
[extension.jpg]
profile=extension.png
[extension.jpeg]
profile=extension.png
```
Add more extensions if you have.

**Comment by kevmitch** [comment]
This is just too "special" a case. If this is needed, it should be scripted or you should use something similar to what @zc62 describes. mpv doesn't see videos and images as different (other than `--image-display-duration`, which only distinguishes at the end of file based on whether only one frame was displayed). 

> Why not just fix your videos to have the correct metadata?

Doesn't this require re-encoding?

**Comment by danboid** [comment]
Following zc62's examples above, I have got mpv playlists working better for me using the following mpv.conf:

```
fs=yes
[extension.mp4]
video-rotate=90
```

This config works quite well as most, but not all, of my mp4 files need to be rotated 90 degrees. I then have a custom key to rotate back those MP4s that get incorrectly autorotated,

It seems the proper fix would be a script. All it would need to do is check to see if video has a greater vertical dimension than the current mpv display does and if it does, rotate it 90 degrees before playing. Does such a script already exist?
