### ISSUE TITLE
Allow hiding of cache display in OSC, possibly by default.

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#5390]
### mpv version and platform
mpv 0.28.0
macOS 12

### Reproduction steps
Since version 0.28.0, a cache display is added to the ~~OSD~~ OSC. This display is very "busy", flickering, and distracting. It's especially so, if you use "box" layout, where it's right in the center of the screen. Also, at least for me, it doesn't seem to be particularly useful information during normal operation, unless there's some problem that needs troubleshooting - I've never had the need to monitor the cache in this way.

### Expected behavior
The cache display in the ~~OSD~~ OSC should be optional, and probably off by default.

### Actual behavior
Distracting and (for me) pointless cache display is always on, can't find any way to remove it.

**Comment by kevmitch** [comment]
For the record it sounds like you're referring to the OSC (On screen controller), not the OSD, which is the plain text that's usually printed in the upper right hand corner.

**Comment by wiiaboo** [comment]
It's shown in the seekbar more subtly (and it's optional) and the numbers are also in stats.lua, so I agree this could be removed or made hidden by default.

**Comment by avih** [comment]
> It's shown in the seekbar more subtly

Not too useful in a live stream (where arguably prefetch size is important) after more than few mins of playback, because the few seconds of prefetch indication at the seekbar become too small to be meaningful IMO.

I do agree though that the erratic rate at which the numbers change is a bit meh, but I don't yet have a paradigm to make it both useful in various use cases and also not erratic to look at.

**Comment by Argon-** [comment]
Maybe only show it for streams?

**Comment by avih** [comment]
> Maybe only show it for streams?

It's already not shown for local files, so this depends on your definition of "stream". Do you consider a youtube page a "stream"? or only a live stream as "stream"?

**Comment by Argon-** [comment]
Huh? OSC shows cache for me for local files.

**Comment by wiiaboo** [comment]
Only if you have forced cache.

**Comment by wiiaboo** [comment]
I'd either make it:
1. only show demuxer-cache-duration
2. refresh at most every 0.25s to 1s (https://0x0.st/sNjt.txt)
3. as is but disableable

**Comment by pmargeti34** [comment]
It seems cache=auto 'forces' cache for local files, at least on mpv 0.27. Setting cache=no removes cache display for local files but not for streaming files.

**Comment by wiiaboo** [comment]
That's outdated. 0.28 or git master already fixed that.

**Comment by pmargeti34** [comment]
Good to know, I'll be happy to update once ffmpeg 3.5 is out.

**Comment by sumyungguy** [comment]
I see it on local files on my hard drive, mkv, mp4, even if I set cache=no.

**Comment by wiiaboo** [comment]
@sumyungguy it's in git master.

**Comment by sumyungguy** [comment]
I'm not able to compile git master at the moment. I'm using 0.28.0 Mac build from stolendata.

I'll have to wait for version 0.29.0 then?

**Comment by avih** [comment]
> I'll have to wait for version 0.29.0 then?

Yes. Either someone builds it for you or you build it for yourself. And that's off topic.

**Comment by sumyungguy** [comment]
I put `demuxer-thread=no` in mpv.conf, now I have a calm "Cache: 0" display. Good enough for now... I don't watch streams anyway.

**Comment by frozenpandaman** [comment]
Thanks for the fix (or good enough for me at least), @sumyungguy!
