### ISSUE TITLE
Is it possible to remove empty audio track programatically? 

### ISSUE THREAD

**Issue by zmartell** [mpv-player/mpv#5396]
### mpv version and platform
0.28.0  linux

Is it possible to remove the empty audio track implemented by mpv? I am utilising cycleProperty audio. It goes from no sound, to track 1, to track 2 to no sound. 

The actual video file does not contain such empty track. 

Perhaps something can input into input.conf or mpv.conf using audio-remove but I cannot seem to get it working?

**Comment by wiiaboo** [comment]
What do you mean by empty track, `--aid=no`?

**Comment by zmartell** [comment]
Sorry, 

When I play a video in mpv that has one or more audio tracks. For example if I have a 2 audio tracks video file, the GUI has a "change audio" cycle button. it goes 0/2 1/2 2/2.. 0/2 being no audio, 1/2 being track 1 of video file, and 2/2 being track 2 of video file. 

How do I get rid of that "0/2" no audio track. Therefore just leaving the 1/2 (track 1) and 2/2 (track 2)? Ideally in some programatic/config file manner as I don't have a mouse or keyboard in my use case.  

It doesn't seem related to any bug or version in particular. It seems by design, but it causes a problem in my particular use-case.

**Comment by thebombzen** [comment]
You could do this with the lua scripting system. Write your own function that cycles the audio track and then cycles it again if there's no audio (check for infinite loops tho). Then bind the function to your own keybind (or to `#`, the default keybind).

**Comment by wiiaboo** [comment]
Yeah, special use-cases are normally fixed/implemented with scripts.

**Comment by zmartell** [comment]
I do not have a keyboard in my scenario. Is there a way to map a Lua script to a json ipc command and not a key binding?

Am I better off making a mpv fork that ignores such empty audio track?

**Comment by wiiaboo** [comment]
> I do not have a keyboard in my scenario. Is there a way to map a Lua script to a json ipc command and not a key binding?

[`script-message` et al](https://mpv.io/manual/master/#command-interface-script-message)

**Comment by KonoVitoDa** [comment]
https://github.com/viniciusbm/mpv-cycle-through-existing
