### ISSUE TITLE
gpu video out causes segfault on RPi

### ISSUE THREAD

**Issue by deltabeard** [mpv-player/mpv#5398]
### mpv version and platform

Git master (a5f53da229f0f3f5b7e248c47061a67f6d61d81e)
Raspberry Pi 3 - Raspbian

### Reproduction steps

Use the gpu output driver `--vo=gpu` on the Raspberry Pi without using VC4.

### Expected behavior

To work like the `--vo=rpi` option does.

### Actual behavior

Segmentation fault occurs before the video starts.

### Log file

[mpv log](http://sprunge.us/eJPh)
[gdb log and backtrace](http://sprunge.us/YKBU)

Mirror:
[gdb.txt](https://github.com/mpv-player/mpv/files/1629254/gdb.txt)
[outgpu.txt](https://github.com/mpv-player/mpv/files/1629255/outgpu.txt)

### Sample files

Any h264 encoded video.

**Comment by haasn** [comment]
Does this diff fix it?

```
diff --git a/video/out/opengl/context_rpi.c b/video/out/opengl/context_rpi.c
index 8b447d0bfc..17a646bb04 100644
--- a/video/out/opengl/context_rpi.c
+++ b/video/out/opengl/context_rpi.c
@@ -233,9 +233,6 @@ static bool rpi_init(struct ra_ctx *ctx)
     if (!mpegl_create_context(ctx, p->egl_display, &p->egl_context, &p->egl_config))
         goto fail;
 
-    if (recreate_dispmanx(ctx) < 0)
-        goto fail;
-
     mpegl_load_functions(&p->gl, ctx->log);
 
     struct ra_gl_ctx_params params = {
@@ -247,6 +244,9 @@ static bool rpi_init(struct ra_ctx *ctx)
     if (!ra_gl_ctx_init(ctx, &p->gl, params))
         goto fail;
 
+    if (recreate_dispmanx(ctx) < 0)
+        goto fail;
+
     return true;
 
 fail:
```

I'm not entirely sure in which order these initialization calls need to happen in terms of the RPi APIs; but the current code seems to have cyclic dependencies.

If this doesn't work, the other way of breaking the cyclic dependency would be to check if the swapchain has been initialized already in `recreate_dispmanx`, and if not, skip the resize event - and then send it a second time from `rpi_init`.

**Comment by deltabeard** [comment]
The segmentation fault no longer occurs. However a different error now occurs `glGetString(GL_VERSION) returned NULL`. I'm using the Raspberry Pi [userland](https://github.com/raspberrypi/userland), not the vc4 mesa driver.
[mpv_gpu2.log](https://github.com/mpv-player/mpv/files/1629611/mpv_gpu2.log)

If this bug is not related, I can open a new issue.

**Comment by haasn** [comment]
@deltabeard That's unfortunate. I guess this works, then?

```diff
diff --git a/video/out/opengl/context_rpi.c b/video/out/opengl/context_rpi.c
index 8b447d0bfc..e00c65f02c 100644
--- a/video/out/opengl/context_rpi.c
+++ b/video/out/opengl/context_rpi.c
@@ -198,7 +198,9 @@ static bool recreate_dispmanx(struct ra_ctx *ctx)
 
     ctx->vo->dwidth = p->w;
     ctx->vo->dheight = p->h;
-    ra_gl_ctx_resize(ctx->swapchain, p->w, p->h, 0);
+
+    if (ctx->swapchain)
+        ra_gl_ctx_resize(ctx->swapchain, p->w, p->h, 0);
 
     ctx->vo->want_redraw = true;
 
@@ -247,6 +249,7 @@ static bool rpi_init(struct ra_ctx *ctx)
     if (!ra_gl_ctx_init(ctx, &p->gl, params))
         goto fail;
 
+    ra_gl_ctx_resize(ctx->swapchain, ctx->vo->dwidth, ctx->vo->dheight, 0);
     return true;
 
 fail:
```

**Comment by deltabeard** [comment]
Same error: `glGetString(GL_VERSION) returned NULL.`
[log](https://github.com/mpv-player/mpv/files/1629644/gpu_err3.txt)

Are you sure this is related to the original segfault I had?

**Comment by wm4** [comment]
glGetString returning NULL typically happens if no GL context is set when calling it.

**Comment by deltabeard** [comment]
Okay I no longer get the glGetString error. The video starts playing, but the video itself cannot be seen. The subtitles and the OSD can only be seen.
[log](https://github.com/mpv-player/mpv/files/1629660/gpu_issue4.txt)
![img_20180114_184656](https://user-images.githubusercontent.com/3747104/34919443-ffd21926-f95b-11e7-92c4-03da65346710.jpg)

**Comment by wm4** [comment]
Don't know. You can try playing with the layer options and see if the video layer is just hidden behind the console. The RPI is a hack.

**Comment by haasn** [comment]
@deltabeard Do you know if that specific issue is a regression? Can you test mpv 0.27?

**Comment by deltabeard** [comment]
I've just tested mpv 0.27. The `opengl` output driver does the same thing - no video is displayed on the screen, only the subtitles. The rpi video output driver does not have this issue on either version.

I'm not sure how to change the layer of the video with the `gpu` driver. I tried `--rpi-layer` (which appears to be for rpi vo only) and that didn't work.

**Comment by haasn** [comment]
Okay, then it's unrelated to this specific issue. I'll submit a PR

**Comment by deltabeard** [comment]
Thanks. I'll open a new issue.
