### ISSUE TITLE
BPC mismatch with newer mesa

### ISSUE THREAD

**Issue by ManDay** [mpv-player/mpv#5400]
This is mpv-0.26.0 but I'm fairly sure, unless someone reported this already, it went unnoticed in master. As of [this commit](https://cgit.freedesktop.org/mesa/mesa/commit/?id=9e63cbacb6bc10b4426fc2af4989fbdc86ec4167) in mesa, when playing with `--opengl-backend=drm --vo=opengl` on TTY, the image rendered in an unrecognizeable way the colors are treated.

**Comment by Dudemanguy** [comment]
Very old issue and drm works fine as far as I'm aware. Please open a new issue if this is still an issue.
