### ISSUE TITLE
0.28 via Homebrew?

### ISSUE THREAD

**Issue by FatherOfAlways** [mpv-player/mpv#5402]
Is it possible to install v0.28 via Homebrew and if so, how?

I'm sorry for this noob question, but I don't know much about the command line and `brew install mpv` (currently) only installs v0.27.

**Comment by sfan5** [comment]
Tell the brew maintainers that you want a new version.

Supposedly `brew install mpv --HEAD` works but you somehow need a recent ffmpeg.

**Comment by AirPort** [comment]
0.28.0 in homebrew is on hold until FFmpeg cut a new stable version, required for the newest mpv to work. In the meantime, if you don't wish to wait, you can grab a precompiled binary here: https://laboratory.stolendata.net/~djinn/mpv_osx/, or you can install the latest development version of FFmpeg and mpv with brew using
```
brew install --HEAD ffmpeg
brew install --HEAD mpv
```

**Comment by avih** [comment]
[mpv-build](https://github.com/mpv-player/mpv-build) might also work which will build mpv git master and fffmpeg git master and link them statically.

**Comment by AirPort** [comment]
mpv-build works really well (I use it), but it might be a hassle if you don't want to work too much with the terminal: you have to manually call the bundle-making script by yourself after the build, and you may have to export a couple of pkg-config flags for dependencies that aren't linked to /usr/local/ (openssl above all).

**Comment by FatherOfAlways** [comment]
Thanks for your suggestions, AirPort. I think I'll use the build from the "stolendata" link then switch back to Homebrew once the mpv is updated there.
