### ISSUE TITLE
Playback lags when adjusting volume for the first time

### ISSUE THREAD

**Issue by ewasion** [mpv-player/mpv#5406]
### mpv version and platform
v0.28.0 on Windows 10

### Reproduction steps
Open a file
Adjust the volume (not mute)

### Expected behavior
Volume is adjusted instantly

### Actual behavior
The video pauses for a bit before the volume is adjusted
Only the first volume change is affected

### Log file
http://ix.io/FbZ

### Sample files
Happens on any file,

**Comment by wiiaboo** [comment]
Can you try with `--no-config`?

**Comment by haasn** [comment]
Does the same slow down happen if you press some other key (e.g. `P`) to bring up the OSD first?

I usually find that initializing the OSD for the first time is what causes the microstutter on my end. A good work-around could be forcing libass to be internally initialized by rendering a dummy OSD frame off-screen before playback starts.

**Comment by wiiaboo** [comment]
I wouldn't consider 15 seconds a microstutter.

**Comment by dnmTX** [comment]
@wiiaboo try "--ad-lavc-threads=0" ,i've notice slight improvement using it overall(fyi i don't experiencing 15 sec. microstutter).I've notice that some audio codecs require more the one thread to be initialized.The default is 1,after changing it i can see it's requesting 9 threads.Try it,might help.

**Comment by dnmTX** [comment]
Which part is so confusing for you?

**Comment by wiiaboo** [comment]
The part where I'm not the one with an issue.

**Comment by dnmTX** [comment]
Sorry,my mistake

**Comment by ewasion** [comment]
Same problem with `--no-config`, `--ad-lavc-threads=0` and rendering the OSD before adjusting the volume.
The stutter lasts for less than a second on some files, a few seconds on others.

**Comment by haasn** [comment]
> and rendering the OSD before adjusting the volume.

Can you clarify: Do you have the same hang when viewing the OSD in general for the first time, or do you have the same hang when adjusting volume for the first time regardless of whether or not the OSD was displayed previously?

**Comment by ewasion** [comment]
Sorry for being unclear, there is no stutter when viewing the OSD for the first time. Viewing it doesn't prevent the stutter from happening.

**Comment by myfreeer** [comment]
Would `--volume=95` workaround that?

**Comment by wm4** [comment]
mpv 0.28 doesn't even insert a volume filter, so the first volume change is as much work as the Nth as far as audio processing is concerned.
