### ISSUE TITLE
Too much rewind (seeking).

### ISSUE THREAD

**Issue by SemperPeritus** [mpv-player/mpv#5408]
Sorry for poor English.

### mpv version and platform
2017-12-25 build from https://mpv.srsfckn.biz/
My config: https://github.com/SemperPeritus/mpv-config

### Reproduction steps
Left and right arrows key pressing.

### Expected behavior
Seek for 1 second.

### Actual behavior
Pretty often (but not always) seek for several seconds (about up to 5-6 for 2 clicks). It seems that with two clicks it always seek much more that 2 seconds.

### Log file
http://sprunge.us/dPhS

**Comment by wiiaboo** [comment]
Use `--hr-seek`.
