### ISSUE TITLE
screenshot-template doesn't create new directories

### ISSUE THREAD

**Issue by radgeRayden** [mpv-player/mpv#5414]
If I use `screenshot-directory=~/Pictures/mpv/xyz` and there's no `xyz`, it creates the `xyz` directory. However, if I do it through `screenshot-template`, I get an error on writing screenshot. The reason I need this to work is because I want to have screenshots saved in dynamically named directories, eg. `~/Pictures/mpv/%tB-%tY/%F-%p%n`, which wouldn't expand on `screenshot-directory`.

**Comment by CounterPillow** [comment]
It should do that, I've fixed that in a recent-ish PR. What mpv version are you using? Please do not ignore the issue template.

**Comment by radgeRayden** [comment]
Oops I'm sorry. I'm on 0.27. Will wait for update then.

**Comment by CounterPillow** [comment]
>and I suppose it should have the fix then.

no. The time it was built does not mean it has all commits up to that point in the build. If it says 0.27, it has all commits in it up to the 0.27 tag, which means it lacks mine.
