### ISSUE TITLE
Wrong chapter detection with youtube-dl on youtube when two timestamps are on the same line in the description

### ISSUE THREAD

**Issue by linkmauve** [mpv-player/mpv#5415]
### mpv version and platform
0192eeb09 (master as of Wed Jan 17) on ArchLinux amd64.

### Reproduction steps
Open the sample file, see that no chapter gets created at 18:20 nor 20:12, and same near the end of the file.

### Expected behavior
A chapter would be created for every timestamp included in the description.

### Actual behavior
Some are skipped.

### Log file
Doesn’t contain any information about that.

### Sample files
https://youtu.be/22L5FCNPkrA

**Comment by wiiaboo** [comment]
Youtube-dl is the one doing the chapters for youtube at list. So it's an issue for youtube-dl to handle.
