### ISSUE TITLE
stepping frame backwards is very slow

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#5417]
I have mpv installed on Archlinux

$ mpv --version
Warning: option --softvol is deprecated and might be removed in the future (softvol is always active, and behaves as if --softvol=yes is always set).
Warning: option --softvol-max was replaced with --volume-max and might be removed in the future.
mpv 0.24.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 12 12:54:08 CET 2017
ffmpeg library versions:
   libavutil       55.34.101
   libavcodec      57.64.101
   libavformat     57.56.101
   libswscale      4.2.100
   libavfilter     6.65.100
   libswresample   2.3.100
ffmpeg version: 3.2.4

I have video with 24fps.

I am trying the following shortcuts:

```
. Step forward. Pressing once will pause, every consecutive press will play one frame and then go into pause mode again.
, Step backward. Pressing once will pause, every consecutive press will play one frame in reverse and then go into pause mode again.
```

Step Forward works smoothly but stepping backward works very slaggy.

**Comment by wiiaboo** [comment]
https://github.com/mpv-player/mpv/issues/4019

**Comment by sant527** [comment]
I found an alternate solution mentioned in #4019

@stibinator
Djvview has the option of caching decoded frames in memory, is this possible with mpv? Maybe with a user specifiable RAM cache, like djvview? I use mpv for previewing renders and so on, the ability to smoothly play backwards would be really useful.

http://djv.sourceforge.net/

**Comment by CounterPillow** [comment]
The problem isn't just caching the frames in memory, but the entire player state, which cannot simply be rewound. There is a lot more to playing back video than just decoding and presenting the frames.
