### ISSUE TITLE
[hwdec_d3d11va] No hardware acceleration with H264

### ISSUE THREAD

**Issue by dnmTX** [mpv-player/mpv#5420]
### mpv version and platform
mpv-x86_64-20180120-git-dba143d (latest build by shinchiro)
Windows 10 x64  LTSB 1607

### Reproduction steps
Playing any h264 file with --vo=gpu --gpu-context=d3d11 --hwdec=d3d11va

### Expected behavior
To be hardware accelerated by my eGPU(NVIDIA) as the previous build(s) did

### Actual behavior
THIS:
0.584][v][vd] Opening video decoder h264
[   0.584][v][vd] Looking at hwdec h264-d3d11va...
[   0.584][v][vo/gpu] Loading hwdec driver 'cuda-nvdec'
[   0.584][v][vo/gpu] Loading failed.
[   0.584][v][vd] Could not create device.
[   0.584][v][vd] Using software decoding.

I know that you guys did some changes but didn't expect to cut all(or at least most of it)  codec support from d3d11. What is the point to have  good GPU if you can't even use it to watch some videos?
What i see so far is that the VSync Jitter increased from 0.007(full screen) to 0.070 and there is much more pressure on the CPU.Bring back the codec support PLEASE !!!!!!

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/1648593/log.txt)

**Comment by shinchiro** [comment]
This appear to be a bug in `wscript` where disabling angle also disable d3d11va

**Comment by dnmTX** [comment]
@shinchiro is there a some workaround for this cause looks like this will not going to be fixed soon.I still don't see any response from the devs  here.

**Comment by kevmitch** [comment]
It's been discussed on IRC. The windows hwdec wscript deps are currently a mess. The workaround for now is to compile with angle.

**Comment by dnmTX** [comment]
Got it.Thanks for the update @kevmitch

**Comment by dnmTX** [comment]
Looks like the bug has been fixed so i'm closing this to reduce the ticket clutter.
@shinchiro whenever you can for the new build(no pressure :-) )

**Comment by kevmitch** [comment]
Well, technically, that hasn't been merged yet. It will be in the next hour or so.
