### ISSUE TITLE
MPV using  NVIDIA GPU GK20A-CPUTK1 CRASH ARM-(Linux-ARCHLINUX-Ver- 3.10.18)

### ISSUE THREAD

**Issue by aperfeito** [mpv-player/mpv#5425]
### mpv version and platform
Linux alarm 3.10.18-24-ARCH #1 SMP Wed Nov 29 16:27:21 PST 2017 armv7l GNU/Linux
ChromeBook HP 14 G3 Tegra Tk1 GPU GK20A

[aperfeito@alarm Downloads]$ mpv -v
****NvRmMemInit failed****
Error: Can't open /dev/nvhost-ctrl
[cplayer] Command line options: '-v'
[cplayer] mpv 0.28.0-139-gdba143de4d Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri Jan 19 13:47:15 PST 2018
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.7.100
[cplayer]    libavcodec      58.9.100
[cplayer]    libavformat     58.5.100
[cplayer]    libswscale      5.0.101
[cplayer]    libavfilter     7.11.101
[cplayer]    libswresample   3.0.101
[cplayer] ffmpeg version: N-89830-g0afa171f25
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/usr --disable-android --disable-win32-internal-pthreads --disable-egl-angle --disable-egl-angle-lib --disable-egl-angle-win32 --disable-gl-win32 --disable-mali-fbdev --disable-vaapi --disable-vaapi-x11 --disable-vaapi-wayland --disable-vaapi-drm --disable-vaapi-glx --disable-vaapi-x-egl --disable-caca --disable-rpi --disable-ios-gl --disable-vulkan --disable-d3d9-hwaccel --disable-d3d-hwaccel --disable-vdpau --disable-vdpau-gl-x11 --disable-gl-dxinterop --disable-gl-dxinterop-d3d9 --disable-gl-cocoa --disable-vapoursynth-lazy --disable-vapoursynth --disable-lua
[cplayer] List of enabled features: alsa asm atomics build-date cplayer cplugins cuda-hwaccel debug-build drm drmprime egl-drm egl-helpers egl-x11 encoding fchmod ffmpeg gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm librt linux-fstatfs optimize oss-audio posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse stdatomic vt.h wayland wayland-protocols x11 xv zlib
[cplayer] Reading config file /usr/etc/mpv/encoding-profiles.conf
[cplayer] mpv 0.28.0-139-gdba143de4d Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri Jan 19 13:47:15 PST 2018
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.7.100
[cplayer]    libavcodec      58.9.100
[cplayer]    libavformat     58.5.100
[cplayer]    libswscale      5.0.101
[cplayer]    libavfilter     7.11.101
[cplayer]    libswresample   3.0.101
[cplayer] ffmpeg version: N-89830-g0afa171f25
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer] 
### Reproduction steps
 mpv --playlist diarioaula.m3u
### Expected behavior
Playing: /home/aperfeito/Downloads/VideoAula/Jesus Declares He Is the Messiah (960p_24fps_H264-128kbit_AAC).mp4
 (+) Video --vid=1 (*) (h264 1920x960 23.976fps)
 (+) Audio --aid=1 --alang=und (*) (aac 2ch 44100Hz)
File tags:
 Artist: Mormon Channel
 Comment: https://www.youtube.com/watch?v=h9M2mprzCF8
 Title: Jesus Declares He Is the Messiah
shared memfd open() failed: Function not implemented
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1920x960 yuv420p
AV: 00:00:00 / 00:03:25 (0%) A-V:  0.000

### Actual behavior
****NvRmMemInit failed****
Error: Can't open /dev/nvhost-ctrl
Playing: /home/aperfeito/Downloads/VideoAula/Jesus Declares He Is the Messiah (960p_24fps_H264-128kbit_AAC).mp4
 (+) Video --vid=1 (*) (h264 1920x960 23.976fps)
 (+) Audio --aid=1 --alang=und (*) (aac 2ch 44100Hz)
File tags:
 Artist: Mormon Channel
 Comment: https://www.youtube.com/watch?v=h9M2mprzCF8
 Title: Jesus Declares He Is the Messiah
[vo/gpu/x11] X11 error: BadValue (integer parameter out of range for operation)
[vo/gpu/x11] Type: 0, display: 0xae62e800, resourceid: 0, serial: 70
[vo/gpu/x11] Error code: 2, request code: 9a, minor code: 3
[vo/gpu] Could not create GLX context!
[vo/gpu/x11] X11 error: BadValue (integer parameter out of range for operation)
[vo/gpu/x11] Type: 0, display: 0xae62e2d0, resourceid: 0, serial: 70
[vo/gpu/x11] Error code: 2, request code: 9a, minor code: 3
[vo/gpu] Could not create GLX context!

### Log file
Make a log file made with -v or --log-file=output.txt, paste it to
 similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

https://pastebin.com/T3bmj7Si
### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wm4** [comment]
You most likely do not have capable graphics drivers installed.

**Comment by aperfeito** [comment]
Its Not..... Open GL version 4.4 TK1 GK20A Nvidia very good GPU.

The Problem its Solved Knockdown (Its About Permitions) LINUX !!! All works fine 

Playing: /home/aperfeito/Downloads/VideoAula/Jesus Declares He Is the Messiah (960p_24fps_H264-128kbit_AAC).mp4
 (+) Video --vid=1 (*) (h264 1920x960 23.976fps)
 (+) Audio --aid=1 --alang=und (*) (aac 2ch 44100Hz)
File tags:
 Artist: Mormon Channel
 Comment: https://www.youtube.com/watch?v=h9M2mprzCF8
 Title: Jesus Declares He Is the Messiah
shared memfd open() failed: Function not implemented
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1920x960 yuv420p
AV: 00:00:02 / 00:03:25 (1%) A-V:  0.000


Exiting... (Quit)
LIKE A CHARM !!!!
