### ISSUE TITLE
Black screen when playing mkv with multiple tracks

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5428]
### Reproduction steps
In a playlist, I add several videos with their respective settings, one of them is an MKV that has two audio tracks and two video tracks. I set so that MPV plays the audio and video track n ° 2 and plays only the audio track 1, the video does not play it (it is black).
![mpv](https://user-images.githubusercontent.com/25028878/35192213-64bdf3a4-fe6c-11e7-8ae1-358d6b42f7d4.png)

### Log file

[TViPlus95.VPM.log](https://github.com/mpv-player/mpv/files/1649615/TViPlus95.VPM.log)

### Sample files

[](http://tviplus.com/Ejemplo%20m%C3%BAltiples%20streams.mkv)

**Comment by EzeKees** [comment]
also sometimes generates this error:
[ 606.748][f][cplayer] No video or audio streams selected.
[ 606.748][v][cplayer] finished playback, no audio or video data played (reason 4)

**Comment by wiiaboo** [comment]
Do another log with only `--no-config` and the options needed to reproduce this issue.
