### ISSUE TITLE
[question] How can I disable all keyboard and mouse input ?

### ISSUE THREAD

**Issue by XXMo2Miku** [mpv-player/mpv#5430]
How can I disable all keyboard and mouse input ?
I used "--no-input-default-bindings", but mouse wheel, keyboard "q", "esc" still work...

**Comment by sfan5** [comment]
mpv version?
`--no-input-default-bindings` produces the desired effect here

**Comment by wiiaboo** [comment]
`--no-config` too, to ignore input.conf.

**Comment by XXMo2Miku** [comment]
@wiiaboo Thanks !!

**Comment by bac0n** [comment]
I use [this](https://gist.github.com/bac0n/25ea01521dae76b209f6814738a8b198) script to set everything to ignore with exceptions. Pay attention to the paths at the end of the script.
