### ISSUE TITLE
overlay not updated when the player is paused

### ISSUE THREAD

**Issue by sgerwk** [mpv-player/mpv#5431]
### mpv version and platform

mpv: git master
platform: linux x86

### Reproduction steps

curl -O http://sgerwk.altervista.org/overlayupdate.c
gcc -o overlayupdate overlayupdate.c -lrt -lmpv
overlayupdate somefile.png

the image is shown with no overlay on it

### Expected behavior

a 200x200 box of random colors should be seen at coordinates 200,10
it should change to solid green after two seconds
disappear after other two

### Actual behavior

the box does not show at all

a workaround to this is to execute a show_text command, even with 0 duration,
right after every overlay_add or overlay_remove

this is done by the testing program with argument -t:

overlayupdate -t somefile.png

### Log file

http://sgerwk.altervista.org/output.txt

**Comment by wm4** [comment]
Fix is in a PR; the test program was useful.
