### ISSUE TITLE
mpv displays only a blue surface window (Windows 10)

### ISSUE THREAD

**Issue by felipe19930** [mpv-player/mpv#5436]
### mpv version and platform

mpv 0.28.0-139-gdba143de4d
Windows 10 64-bit

### Reproduction steps

1. Download the latest "shinchiro" build from [here](https://sourceforge.net/projects/mpv-player-windows/files/64bit/).
2. Extract it to any folder.
3. Run `installer/configure-opengl-hq.bat`.
4. Open `mpv.exe` and drop any video to it.

### Expected behavior
Video to be actually reproduced...

### Actual behavior
mpv displays a window with a blue surface only.

### Log file

[mpv.txt](https://github.com/mpv-player/mpv/files/1652922/mpv.txt)

**Comment by shinchiro** [comment]
Since it failed in D3DCompile, try rename `d3dcompiler_43.dll` inside the mpv folder to something else like `d3dcompiler_43.old.dll`

**Comment by felipe19930** [comment]
No change as well:

[mpv.txt](https://github.com/mpv-player/mpv/files/1657964/mpv.txt)

It's the same error apparently: `D3DCompile failed: Erro não especificado (0x80004005)` ("Unspecified error", or something similar), here's how mpv looks:

![sem titulo](https://user-images.githubusercontent.com/35700659/35306388-730bd0a6-0084-11e8-8c95-5fde0e7582c7.png)

**Comment by wiiaboo** [comment]
Have you tried installing some GPU drivers?

**Comment by felipe19930** [comment]
Yes, and I already have the latest version... But don't get me wrong, it's a very old [Dell computer](https://www.cnet.com/g00/products/dell-inspiron-531-tower-athlon-64-x2-3800-plus-2-ghz-2-gb-250-gb-lcd-19/specs/?i10c.encReferrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS5ici8%3D&i10c.ua=1). 

Nonetheless, I've tried a bunch of different builds because I was sure mpv used to work just fine with `profile=opengl-hq`. So this is the result:

* The last working build ([from shinchiro](https://sourceforge.net/projects/mpv-player-windows/files/64bit/)) is `mpv-x86_64-20171014-git-47b1390.7z`, which runs mpv 0.27. [Here's the log file of it](https://github.com/mpv-player/mpv/files/1662210/last-working-build.txt).
* The problematic build is the very next one, `mpv-x86_64-20171113-git-41243e7.7z`, which **still runs** mpv 0.27.

Let me know if you need something else.

**Comment by wiiaboo** [comment]
> NVIDIA GeForce 6150SE nForce 430

This doesn't look like a good GPU to use gpu-hq/opengl-hq on.

**Comment by felipe19930** [comment]
Yeah I know that's not a good GPU at all, but at the same time I've never had any issues with mpv before while using `opengl-hq`. But meh, whatever.

**Comment by wm4** [comment]
@rossy might be interested in this.

**Comment by shinchiro** [comment]
> The last working build mpv-x86_64-20171014-git-47b1390.7z

It still using `angle` so probably the new default backend `d3d11` gave problem to you. Also looking back at the first log, `d3d11` doesnt print the gpu's name so it cannot be right (I think)

```
[   0.059][v][vo/gpu/d3d11] Initializing GPU context 'd3d11'
[   0.091][v][vo/gpu/d3d11] Using Direct3D 11 feature level 9_3
[   0.091][v][vo/gpu/d3d11] Device Name: Software Adapter
[   0.091][v][vo/gpu/d3d11] Device ID: 0000:0000 (rev 00)
[   0.091][v][vo/gpu/d3d11] Subsystem ID: 0000:0000
[   0.091][v][vo/gpu/d3d11] LUID: 000000000000530b
[   0.092][v][vo/gpu/d3d11] Initializing SPIR-V compiler 'shaderc'
[   0.092][v][vo/gpu/d3d11] Using Direct3D 11.1 runtime
[   0.092][v][vo/gpu/d3d11] Maximum Texture2D size: 4096x4096
[   0.096][v][vo/gpu/d3d11] D3DCompiler version: 10.0.15063.675
[   0.126][v][vo/gpu/d3d11] Using DXGI 1.2+
[   0.126][v][vo/gpu/d3d11] Using flip-model presentation
```

**Comment by rossy** [comment]
Yep, this is an ra_d3d11 bug.

@felipe19930 It looks like opengl-hq wasn't working for you before. In your old log, mpv prints the following lines:

```
[ 0.119][w][vo/gpu] High bit depth FBOs unsupported. Enabling dumb mode.
[ 0.119][w][vo/gpu] Most extended features will be disabled.
```

So most (all?) opengl-hq features were automatically disabled due to old hardware.

This bug is because mpv switched from ANGLE to a native Direct3D 11 renderer. The new renderer should actually have better support for old hardware, but it doesn't support dithering due to the old shader model (4_0_level_9_3.) mpv is supposed to automatically disable dithering for old hardware like this, but for some reason it isn't doing it.

In the meantime, you should be able to fix this with``dither=no``, though hardware this old is probably not fast enough for gpu-hq, so you might have to set ``deband=no`` as well, or disable gpu-hq entirely.

@shinchiro Yeah, mpv doesn't print the proper adapter name for 9_3 hardware because the adapter is emulated by the D3D11 runtime. I'm not sure how ANGLE gets the real adapter name.

**Comment by felipe19930** [comment]
Oh you guys are totally right, it's not even worth trying opengl-hq / gpu-hq. I tried playing a random 1080p video with `profile=opengl-hq` and it was unwatchable, stuttering too much. Then I deleted everything and went with vanilla options (mpv 0.28) and it rendered with no issues at all... So if there's a bug I don't even it's worth trying to fix it because I'm not going back lol

**Comment by avih** [comment]
> So if there's a bug I don't even think it's worth trying to fix

It's worth fixing because it's a bug, and because it can manifest for other users too.

**Comment by felipe19930** [comment]
Makes sense. 

Well, good luck with that. And thanks for helping as well!

**Comment by felipe19930** [comment]
Hey, just confirming that those commits do fix this issue when using `profile=gpu-hq` (although I won't be using it anymore in this crap PC). Thank you.
