### ISSUE TITLE
vo=drm with force-window crashes when playing an mp3 after a png

### ISSUE THREAD

**Issue by sgerwk** [mpv-player/mpv#5438]
### mpv version and platform

github master
lnux

### Reproduction steps

mpv --vo=drm --force-window file.png file.mp3

### Expected behavior

show the png file for about 1 sec, then play the mp3 file

### Actual behavior

crashes instead of playing the mp3 file, with error:

mpv: ../video/mp_image.c:527: mp_image_crop: Assertion `x1 <= img->w && y1 <= img->h' failed.

### Log file

http://sgerwk.altervista.org/output-png-mp3.txt

**Comment by wm4** [comment]
Do you have a backtrace?

**Comment by sgerwk** [comment]
sure:

#0  0xb7fdaae1 in __kernel_vsyscall ()
#1  0xb5c74dc0 in __libc_signal_restore_set (set=0xb34fbd00)
    at ../sysdeps/unix/sysv/linux/nptl-signals.h:79
#2  __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xb5c76287 in __GI_abort () at abort.c:89
#4  0xb5c6da17 in __assert_fail_base (
    fmt=0xb5da96ac "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x80131b52 "x1 <= img->w && y1 <= img->h",
    file=0x80131a82 "../video/mp_image.c", line=528,
    function=0x80131cf0 <__PRETTY_FUNCTION__.9048> "mp_image_crop")
    at assert.c:92
#5  0xb5c6da9b in __GI___assert_fail (
    assertion=0x80131b52 "x1 <= img->w && y1 <= img->h",
    file=0x80131a82 "../video/mp_image.c", line=528,
    function=0x80131cf0 <__PRETTY_FUNCTION__.9048> "mp_image_crop")
    at assert.c:101
#6  0x800af9b6 in mp_image_crop (img=0xb34fc03c, x0=0, y0=0, x1=960, y1=480)
    at ../video/mp_image.c:528
#7  0x800afa45 in mp_image_crop_rc (img=0xb34fc03c, rc=...)
    at ../video/mp_image.c:541
#8  0x800e1a16 in draw_image (vo=0x802028c8, mpi=0xb371e488)
    at ../video/out/vo_drm.c:322
#9  0x800e1f8c in control (vo=0x802028c8, request=9, arg=0x0)
    at ../video/out/vo_drm.c:463
#10 0x800e0fe5 in do_redraw (vo=0x802028c8) at ../video/out/vo.c:945
#11 vo_thread (ptr=0x802028c8) at ../video/out/vo.c:1050
#12 0xb5e0927a in start_thread (arg=0xb34fcb40) at pthread_create.c:333
#13 0xb5d30b56 in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:110

**Comment by sgerwk** [comment]
Addition: this seems to happen only if the image is smaller than the force-window size (640x480).

**Comment by sgerwk** [comment]
Fixed by 733bcc03f62009e8cf27c95df1c7d643724df108
