### ISSUE TITLE
Build instructions for iOS

### ISSUE THREAD

**Issue by zrait** [mpv-player/mpv#5439]
### mpv version and platform
HEAD, ffmpeg-git HEAD, High Sierra 10.13.2, iOS 11
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Built ffmpeg-git using https://github.com/kewlbear/FFmpeg-iOS-build-script
The objective would be to build libmpv.a for iPhone simulator use and for iPhone device use

However, I am unable to get past ./waf configure. I've tried setting the following environment variables

CC=xcrun --sdk iphonesimulator clang
LD=xcrun --sdk iphonesimulator ld

or

CC=xcrun --sdk iphoneos clang
LD=xcrun --sdk iphoneos ld

Could someone who has successfully built mpv static libraries for iOS and then linked against them to get the example in mpv-examples to work please outline exactly the parameters used to build libmpv and ffmpeg for iOS?

**Comment by tmm1** [comment]
See https://github.com/mpv-player/mpv/pull/3682#issue-184049753
