### ISSUE TITLE
Playback speed (--speed), vaapi-copy and --lavfi-complex

### ISSUE THREAD

**Issue by ArchangeGabriel** [mpv-player/mpv#5448]
### mpv version and platform

0.27, ArchLinux (0.28 is waiting for ffmpeg upgrade)

### Reproduction steps

Try to play two videos side by side with with `lavfi-complex`, changing playback speed and using `vaapy-copy` as hwdec (since no-copy one cannot work with `lavfi-complex`), as following for instance:
```
mpv --hwdec=vaapi-copy --speed=10 <video1.mkv> --external-file=<video2.mkv> --lavfi-complex='[vid1] [vid2] hstack [vo]'
```

### Expected behavior

Both videos are played side-by-side with a play back speed of x10.

### Actual behavior

Videos are played at their normal speed. Using `--hwdec=no` works, and `--hwdec=vaapi-copy --speed=10` works when used on a single video.

### Log file

https://paste.xinu.at/3hdsr/

**Comment by wm4** [comment]
Works here. Maybe your hardware is just too slow.

**Comment by Akemi** [comment]
if the issue still persists, please open a new issue.
