### ISSUE TITLE
not playing ftp file

### ISSUE THREAD

**Issue by nodern** [mpv-player/mpv#5449]
### mpv version and platform
mpv-x86_64-20171021-git-044af63 on Windows 10 and Windows 7(both 64 bit)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Until the release before 20171021-git-044af63 worked fine with playing ftp file but, from that release, it doesn't play. (20180126-git-f8263e8 that is the most latest one also doesn't work.)

### Expected behavior
playing video

### Actual behavior
mpv.exe not showing after typing "mpv ftp://something@something.mkv" on the cmd. Also CPU keeps loading constantly almost 50%(when I tried with working version, CPU loads was much less) with mpv.exe on the process but, not showing the program. Only I can see mpv.exe on the process. I used shinchiro's builds. Also with lachs0r's builds don't work after specific release.

### Log file
https://www.datafilehost.com/d/fd620305
There are 3 files.
One is for local file play working, another is ftp file play working and the other is ftp file play not working.

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wiiaboo** [comment]
You forgot to censor credentials on the "normal" log, btw.

**Comment by nodern** [comment]
I changed it. Thank you.

**Comment by nodern** [comment]
Playing twitch stream using mpv with youtube-dl is okay, but FTP is not.

**Comment by garoto** [comment]
Disable the cache with `--cache=no` and it should start working again.

**Comment by nodern** [comment]
@garoto WOW! If works. Thank you!

**Comment by bpsib** [comment]
> Disable the cache with `--cache=no` and it should start working again.
> 
> Might also wanna add `--demuxer-seekable-cache=yes --demuxer-readahead-secs=<number of seconds> --demuxer-thread=yes` in there to have some demuxer(?) cache with seek capabilities.

I tried doing this on a TV recording (.ts file) but still just hangs and never plays. Why isn't it working for me?
