### ISSUE TITLE
Screenshots look terrible compared to original video

### ISSUE THREAD

**Issue by schmidtdominik** [mpv-player/mpv#5450]
### mpv version and platform

mpv git-2017-10-14-b299a3f (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Tue Oct 17 01:30:07 UTC 2017
ffmpeg library versions:
   libavutil       55.79.100
   libavcodec      57.108.100
   libavformat     57.84.100
   libswscale      4.9.100
   libavfilter     6.108.100
   libswresample   2.10.100
ffmpeg version: git-2017-10-14-0655810

### Reproduction steps
I took a screenshot from 3840x1600px mkv movie but the resulting png (jpg too) file looks totally different than the movie. (much darker, much less saturated colors, greenish tint)

Edit: I just noticed that when I launch it with `--vo=xv` it displays the movie in exactly the same (darker) colors as in the screenshots. 

### Expected behavior

![How it should look](https://user-images.githubusercontent.com/8918572/35462835-11a357be-02ee-11e8-84f6-3485bb2ca26b.jpg)

### Actual behavior

![The screenshot](https://user-images.githubusercontent.com/8918572/35462836-11c5a3be-02ee-11e8-93b2-35f6fb3026a3.jpg)

I took this version from the internet since I was unable to take a good screenshot (obviously) but the movie itself actually has even stronger colors than this version.

**Comment by schmidtdominik** [comment]
I turns out when I take screenshots with Ctrl+S instead of S it works as expected. So I'm guessing that the mpv renderer take into accounts color profiles or something while `libswscale` does not.

Shouldn't the mpv renderer be the default one for screenshots?

**Comment by wiiaboo** [comment]
Since there's no sample provided, I'll assume you're watching a HDR video and watching that on a SDR monitor. Look into mpv's HDR-related options or just google what happens to HDR when playing in a non-HDR monitor.

**Comment by schmidtdominik** [comment]
@wiiaboo 
Here's a sample: https://0x0.st/sbrQ.mkv
Pretty sure it's HDR, thanks for quick reply!

**Comment by wiiaboo** [comment]
That doesn't include the part in the screenshots.

**Comment by haasn** [comment]
@wiiaboo Yep, but it's sufficient to demonstrate that the clip is indeed HDR, which explains this issue fully.

There was the suggestion of possibly switching from libswscale to zimg, which does fully support HDR.
