### ISSUE TITLE
get/set --start & --end args from lua

### ISSUE THREAD

**Issue by hxss** [mpv-player/mpv#5454]
### mpv version and platform

```
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Jan 11 21:01:30 CET 2018
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.1
```

### Reproduction steps

I'm run mpv with this params:
```
mpv --\{ "file1.mp4" --start=+6 --end=00:10 --\} --\{ "file2.mp4" --start=+20 --end=00:25 --\} --loop-file=inf
```

### Expected behavior

I want to read this --start & --end values for each file. Also I want to set this for other files(not a-b-loop).
How I can do this?

**Comment by wiiaboo** [comment]
Get is implemented in git master, set isn't yet.

**Comment by hxss** [comment]
So for set I can use only a-b-loop? I was try `mp.set_property("[start/end]")` - looks like this props applies for all files in playlist.

**Comment by wiiaboo** [comment]
For individual files you'd use `file-local-options/start`.

**Comment by hxss** [comment]
`file-local-options/start` resets to null with loop-file command(`file-local-options/stop` continues to work, [like --start/end](https://github.com/mpv-player/mpv/pull/5306)) and after switching to the next file(--start/end saves its states after switching files).

I think we need only one argument, for example --start/end, which will save the state with any parameters of the loop (file or playlist) and will be available in Lua scripts for get/set. Now only a-b-loop works as it should. But a-b is not suitable for playlists(I want to write plugin like [Clipper in VLC](https://addons.videolan.org/p/1154005/)).

**Comment by wm4** [comment]
@wiiaboo set should also work if a string is used.

**Comment by hxss** [comment]
[loadfile](https://mpv.io/manual/master/#command-interface-[replace|append|append-play) should understand start/end options.

**Comment by hxss** [comment]
So, do you plan to add this feature?

**Comment by Dudemanguy** [comment]
I am not sure I understand the exact feature request. However if you only want to apply the `start` and `end` options to one file, you can also simply use the `reset-on-next-file` option which will undo any options you have set on the next file. You can then just set the `start` and `end` options again after the new file loads to what you desire. If that is not sufficient, feel free to reopen.
