### ISSUE TITLE
playlist item UID

### ISSUE THREAD

**Issue by hxss** [mpv-player/mpv#5457]
### mpv version and platform
```
mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Thu Jan 11 21:01:30 CET 2018
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.1
```

### Reproduction steps

I'm trying to write plugin for making playlist with clips. Because of I [can't set start/end](https://github.com/mpv-player/mpv/issues/5454) options for playlist items, I'm looking for unique identifier that will remain unchanged after stop playing item or after changing items order in playlist. All options/* is global and sets for every playlist item. All file-local-options/* losts them values after item stop.

I'm not found option that satisfies me. Is it exist?

P.S.: playlist item != file. In playlist can be several items linked to one file with different options.
`--\{ "file1.mp4" --start=+6 --end=+10 --\} --\{ "file1.mp4" --start=+20 --end=+25 --\}`

**Comment by wm4** [comment]
> Because of I can't set start/end options for playlist items, 

But you can.

> I'm looking for unique identifier that will remain unchanged after stop playing item or after changing items order in playlist.

Sounds like a reasonable request. How exactly would you expect that to work?

> All options/* is global and sets for every playlist item. All file-local-options/* losts them values after item stop.

What does that have to do with this feature request? Also file-local-options are obviously designed to work like this.

**Comment by hxss** [comment]
@wm4 
> But you can.

How I can do this from Lua script? For example I open m3u playlist that contain 3 videos. How I can set different start/end options for every file in current playlist so that each time these files will played, these values will used? See [#5454](https://github.com/mpv-player/mpv/issues/5454#issuecomment-360990800)

>What does that have to do with this feature request? Also file-local-options are obviously designed to work like this.

That was just a description of the current situation and problems that do not allow me to realize my task. Now we have only global options or only temporary.

>Sounds like a reasonable request. How exactly would you expect that to work?

1. On adding any item in playlist, it must be assigned a unique constant
2. Constant must be unique for every item in playlist(not for file, file can be presented several times in playlist)
3. Constant must be readable in Lua extension.

The introduction of the constant will solve not only the problem with start/end time. The constant can be used in Lua scripts to install any unique options for playlist items currently inaccessible.

**Comment by wm4** [comment]
> How I can do this from Lua script? For example I open m3u playlist that contain 3 videos. How I can set different start/end options for every file in current playlist

If you don't populate the playlist (like with `loadfile` or if you generate the playlist yourself) then you currently can't, that's right. But not sure how the feature request is supposed to help with this problem.

**Comment by hxss** [comment]
>But not sure how the feature request is supposed to help with this problem.

If I will can identifier every item at `start-file` event then I will can to set temporary `file-local-options/start` for this item. Yes - workaround, but when I was writing this issue, I just wanted to know if this UID already exist.

**Comment by wm4** [comment]
So why don't you just use the playlist index or filename? What would an UID possibly help with?
I really don't understand what you're trying to do.

**Comment by hxss** [comment]
Items in playlist may be shuffled so playlist index would changed for item. In 1 playlist may be several copies of 1 file with different start/end times.

**Comment by wiiaboo** [comment]
Sounds like EDL would be what you want then.

**Comment by hxss** [comment]
@wiiaboo EDL is cool. Didn't know about this format. But this is not what I want. With EDL I can't control all file duration, I can't seek before start point or disable end point and re-set it in new place(if I will want to change start/end).

**Comment by wm4** [comment]
I still don't get what you want.

What would probably be possible to implement is write access to the "playlist" property, and include per-playlist options in it, and/or support for UIDs (without UIDs you'd have to wipe the playlist and stop playback when setting a playlist, because no other way to reassociate the new playlist with old playlist entries, but not sure how this would be implemented).

**Comment by hxss** [comment]
Hello guys! I'm interested in this UID again :)
Can you please add it?
Maybe it will be just a timestamp in ms of moment when the playlist item was added. Something, that will help me to differ one playlist item from other. (playlist item != file, playlist pos isn't unique because of playlist can be shuffled).

**Comment by hedgehog90** [comment]
This would be a great feature to have.

**Comment by wm4** [comment]
Something like this was implemented recently.

**Comment by hedgehog90** [comment]
I couldn't find anything on the site documentation. I'd assume items in the playlist property would have a new field named 'uid'.
Could you point me in the right direction, please?

**Comment by wm4** [comment]
https://mpv.io/manual/master/#command-interface-playlist/n/id
It appears in a bunch of other places.
