### ISSUE TITLE
Feature Request: Command to hide mpv from taskbar.

### ISSUE THREAD

**Issue by acely** [mpv-player/mpv#5461]
Say I'm using mpv as a video playback component in my project, and I only want it showing a video-output window, no window border, no key event. (Because I only want to control it through JsonIPC, not user) But it still remains in the taskbar, which gives user chance to close it.

So I wonder if we can tell mpv:
(For windows)Not to show up in taskbar. Like a dialog but not window.
(For mac)Not to show menus and app-name maybe.

**Comment by EzeKees** [comment]
You did not try to do it with libmpv?

**Comment by acely** [comment]
No I didn't, because I'm using it in a Java program(called Arctime, a subtitle tool).
And in java it's hard to embed a native video surface to AWT/SWING GUI framework.

Any better suggestion will be much appreciated.

**Comment by EzeKees** [comment]
Ok, I told you nothing more, but that help I can not give you. I hope you have luck, greetings.

**Comment by Akemi** [comment]
for macOS, if you build mpv yourself, you can just change this [line](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa_common.m#L396) to either use [NSApplicationActivationPolicyAccessory](https://developer.apple.com/documentation/appkit/nsapplicationactivationpolicy/nsapplicationactivationpolicyaccessory?language=objc) or [NSApplicationActivationPolicyProhibited](https://developer.apple.com/documentation/appkit/nsapplicationactivationpolicy/nsapplicationactivationpolicyprohibited?language=objc).

as a new feature this might be a bit obscure? though it wouldn't be a big problem for the macOS part.

**Comment by acely** [comment]
Thanks for the reply, but I'm not familiar with compiling/building, so it would be nice if mpv support this feature directly.
And this issue is mainly focused in the windows taskbar thing.

**Comment by wm4** [comment]
You can use window embedding (`--wid=windowid`, with windowid being a numeric HWND).

**Comment by acely** [comment]
@wm4 I'll try that

**Comment by acely** [comment]
@wm4 Wow, the `--win=windowid` option helped a lot, and made it possible to embed mpv into my java GUI, thanks a lot!

**Comment by Akemi** [comment]
i assume this can be closed now.

**Comment by acely** [comment]
@Akemi Yes, thanks.
