### ISSUE TITLE
Load subtitles after video already playing

### ISSUE THREAD

**Issue by rightaway** [mpv-player/mpv#5464]
It should be possible to add a subtitle file after the video is already playing. For example, enter some command in mpv that lets you choose a file path. Right now if I download a subtitle file, I need to name it the same as the video file, then close mpv and reopen it for it to be automatically loaded but I'd like to specify a path so mpv can load the subtitles while already playing.

**Comment by lachs0r** [comment]
Drag and drop the file on the mpv window.

**Comment by rightaway** [comment]
I've now read https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst#general-input-command-syntax, but how can I enter the sub-add input command directly into the UI?

**Comment by lachs0r** [comment]
https://github.com/rossy/mpv-repl
