### ISSUE TITLE
Feature request: sub-step +1 and sub-step -1 keys y and g repectively like smplayer

### ISSUE THREAD

**Issue by fastrizwaan** [mpv-player/mpv#5466]
### mpv version and platform
mpv 0.27.0 Linux 64bit

Could we please have y,g for sub-step +1, sub-step -1 for in input.conf; smplayer uses y and g keys. 
This is especially useful when subtitles are not properly synced. thank you

cat ~/.config/mpv/input.conf
y sub-step +1		# immediately display next subtitle
g sub-step -1		# immediately display previous subtitle

**Comment by kevmitch** [comment]
From the [manual](https://mpv.io/manual/stable/#keyboard-control)

```
Ctrl+LEFT and Ctrl+RIGHT
```

**Comment by kevmitch** [comment]
my bad, these are `sub-seek`, not `sub-step`. added to the never ending meta issue.
