### ISSUE TITLE
spam at syslog like  gnome-session: AV: 00:00:40 / 00:00:44 (91%) A-V

### ISSUE THREAD

**Issue by mariarti** [mpv-player/mpv#5469]
### Ubuntu 16.04 x64

$ mpv -v
[cplayer] Command line options: '-v'
[cplayer] mpv 0.28.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Mon Jan 22 22:45:14 UTC 2018

### Reproduction steps
mpv rtsp://192.168.0.1:666/33

### Expected behavior
no spam at syslog like
Jan 31 18:14:10 gnome-session[1816]: AV: 00:00:40 / 00:00:44 (91%) A-V:  0.000 Cache:  3s+436KB

### Actual behavior
spam at syslog like
Jan 31 18:14:10 gnome-session[1816]: AV: 00:00:40 / 00:00:44 (91%) A-V:  0.000 Cache:  3s+436KB

actually could terminate it with 
>/dev/null 2>&1

but from 
Startup Applications added don't work this trick.

**Comment by lachs0r** [comment]
Use the provided .desktop file, or open files with `--player-operation-mode=pseudo-gui`.
And blame GNOME for the syslog spam.
