### ISSUE TITLE
mpv freezes completely after inserting Vapoursynth filter 

### ISSUE THREAD

**Issue by chainikdn** [mpv-player/mpv#5470]
Like the title said.
Right now can only test it with SVP - it freezes even with frame interpolation disabled so the script doesn't change nether frame size nor frame rate.

### mpv version and platform

latest commit from Jan 30, 2018
previous version (Jan 27) works

### Log file

[   5.977][d][user_filter_wrapper] Setting option 'file' = 'C:\Users\chain\AppData\Roaming\SVP4\scripts\d1a75caf.py' (flags = 0)
[   5.977][d][user_filter_wrapper] Setting option 'buffered-frames' = '4' (flags = 0)
[   5.977][d][user_filter_wrapper] Setting option 'concurrent-frames' = '15' (flags = 0)
[   5.977][d][global] user path: 'C:\Users\chain\AppData\Roaming\SVP4\scripts\d1a75caf.py' -> 'C:\Users\chain\AppData\Roaming\SVP4\scripts\d1a75caf.py'
[   5.977][v][vapoursynth] using 15 concurrent requests.
[   6.039][v][vf] User filter list:
[   6.039][v][vf]   vapoursynth (vapoursynth.00)
[   6.042][i][autoconvert] Converting nv12 -> yuv420p
[   6.042][d][ffmpeg] SwScaler: reducing / aligning filtersize 1 -> 4
[   6.042][d][ffmpeg] SwScaler: reducing / aligning filtersize 1 -> 4
[   6.042][d][ffmpeg] SwScaler: reducing / aligning filtersize 1 -> 1
[   6.042][d][ffmpeg] SwScaler: reducing / aligning filtersize 1 -> 1
[   6.042][v][ffmpeg] swscaler: bicubic scaler, from nv12 to yuv420p using MMXEXT
[   6.042][d][ffmpeg] swscaler: 1024x576 -> 1024x576
[   6.043][v][ffmpeg] swscaler: using unscaled nv12 -> yuv420p special converter
[   6.044][d][vapoursynth] initializing...
[   6.077][d][vapoursynth] initialized.

and that's all

**Comment by Argon-** [comment]
Can't verify this, still works here on OSX (recompiled mpv a few minutes ago).
However, something did change. `container_fps` is suddenly `0.0` for me. This was different a few minutes ago with a ~2 weeks old version of mpv. `display_fps` still works.

**Comment by chainikdn** [comment]
Any script causes the freeze.
```
import vapoursynth as vs
core = vs.get_core()
video_in.set_output()
```

I'm on Windows, build using shinchiro scripts. The only difference between two builds is using
`GIT_TAG` 2a0f9fc1588d8bda51a6340197c54285f3f62755
(the last commit id on 27 Jan, which works) vs git-master (freezes)

**Comment by chainikdn** [comment]
ba769c8  - still freezes

**Comment by wm4** [comment]
Can't reproduce.

**Comment by chainikdn** [comment]
This's what I can see: 
There's only one call of vf_vapoursynth_process() which does VS initialization, buffers first frame and requests frames from VS. Then it returns and _never_ called again. infiltGetFrame() waits forever on 'wakeup' as there no 2nd frame buffered.

**Comment by wm4** [comment]
Still can't reproduce, but qhat you say could happen. Does this help? https://0x0.st/sbRu.diff

**Comment by chainikdn** [comment]
Nope. There's only one frame available at the first and only vf_vapoursynth_process() call.

**Comment by chainikdn** [comment]
The 2nd call is waiting on 'p->lock' mutex.

**Comment by wm4** [comment]
That's how it works. It should request a new frame on the second iteration, which will fail, but make the filters before filter new frames, and call vf_vapoursynth again.

What second call?

**Comment by chainikdn** [comment]
2nd vf_vapoursynth_process() call, which supposed to buffer more input frames, is locked by mutex.

**Comment by wm4** [comment]
That made me look again, and I spotted some dumb nonsense ("what the fuck was I thinking"). Try this: https://0x0.st/sbRv.diff

**Comment by chainikdn** [comment]
this works ;)

**Comment by wm4** [comment]
Can you check whether it still works when removing the while/break change? I think there's actually some code that forces it to feed more data if the VS filter needs it.

**Comment by chainikdn** [comment]
still works

**Comment by wm4** [comment]
Thanks for testing, fix PRed.

**Comment by ArcAngelRyse** [comment]
The filter I'm trying to get working is realtime motioninterpolation.vpy and I have mvtools downloaded not installed I don't know how to honestly...? and a compiled mpv build with vapoursynth everything seems like its good except the filter fails on an attempt to enable it and if attempted to enable it again locks up mpv. 

This is most likely not an issue with mpv but i am looking for assistance to get this working on windows 10.
