### ISSUE TITLE
brief corruption with VP9 + D3D11VA on format incapable GPU

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#5473]
### mpv version and platform
mpv 0.28.0-189-g7f3c7100d5 (media autobuild suite), Windows 10 x64 CU2

### Reproduction steps
Try to play a VP9 video with D3D11VA on a GPU which is not capable of VP9 hardware decoding.
Result in the very beginning of playback:
https://abload.de/img/mpvk8s2s.png

### Expected behavior
It should fall back to software decoding without further issues.

### Actual behavior
It falls back to software decoding but some frames are distorted during the first second.
When disabling hw decoding in the config, there is no corruption. This issue likely has been introduced just recently (detaching it from angle for building?).

### Log file
https://pastebin.com/VYxXNm51

### Sample files
https://youtu.be/aqz-KE-bpKQ

**Comment by GUiHKX** [comment]
I'm having the same issue on Arch Linux; [more details here](https://github.com/mpv-player/mpv/issues/5489).

**Comment by kevmitch** [comment]
Fixed by #5490
