### ISSUE TITLE
cache values not respected on homebrew's installed version on os x

### ISSUE THREAD

**Issue by arooni** [mpv-player/mpv#5475]
### mpv version and platform
I]  ~  brew info mpv
mpv: stable 0.27.0 (bottled), HEAD
Media player based on MPlayer and mplayer2
https://mpv.io
/usr/local/Cellar/mpv/0.24.0 (27 files, 6.4MB)
  Poured from bottle on 2017-02-13 at 13:09:42
/usr/local/Cellar/mpv/0.27.0_1 (27 files, 8.1MB)
  Poured from bottle on 2017-11-10 at 21:44:44
/usr/local/Cellar/mpv/0.27.0_2 (27 files, 7.8MB)
  Poured from bottle on 2017-12-06 at 17:18:46
/usr/local/Cellar/mpv/0.27.0_3 (28 files, 8.1MB)
  Poured from bottle on 2017-12-24 at 13:02:53                                                                                                                                                                                       [0/260]
/usr/local/Cellar/mpv/0.27.0_5 (28 files, 8.6MB) *
  Poured from bottle on 2018-01-11 at 13:56:11
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mpv.rb
==> Dependencies
Build: pkg-config ✔, python3 ✔
Required: libass ✔, ffmpeg ✔, lua@5.1 ✔
Recommended: jpeg ✔, little-cms2 ✔, mujs ✔, youtube-dl ✔
Optional: jack ✘, libaacs ✘, libarchive ✘, libbluray ✘, libcaca ✘, libdvdnav ✘, libdvdread ✘, pulseaudio ✘, rubberband ✘, uchardet ✘, vapoursynth ✘
==> Requirements
Required: macOS >= 10.8 ✔
Optional: x11 ✔
==> Options
--with-bundle
        Enable compilation of the .app bundle.
--with-jack
        Build with jack support
--with-libaacs
        Build with libaacs support
--with-libarchive
        Build with libarchive support
--with-libbluray
        Build with libbluray support
--with-libcaca
        Build with libcaca support
--with-libdvdnav
        Build with libdvdnav support
--with-libdvdread
        Build with libdvdread support
--with-pulseaudio
        Build with pulseaudio support
--with-rubberband
        Build with rubberband support
--with-uchardet
        Build with uchardet support
--with-vapoursynth
        Build with vapoursynth support
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Use this config file; 
```
# cache settings
user-agent="Mozilla/5.0"

#
# Use 8MB input cache by default. The cache is enabled for network streams only.
cache-default=8192
#
# Use 8MB input cache for everything, even local files.
cache=8192
#
# If a seek is issued, and the target is 1024KB past the cached range, then
# keep reading until the seek target is hit, instead of doing a real seek.
#cache-seek-min=1024
#
# Disable the behavior that the player will pause if the cache goes below a
# certain fill size.
#cache-pause=no
#
# Read ahead about 5 seconds of audio and video packets.
demuxer-thread=yes
demuxer-readahead-secs=10.0
```
### Expected behavior
respect the cache values

### Actual behavior

[I]  ✘  ~/.c/mpv  mpv 'https://www.youtube.com/watch?v=AQBh9soLSkI' --vid=no --demuxer-thread=yes --demuxer-readahead-secs=200 --cache=4096
Option fmt: unknown format name: '444p'
Error parsing option fmt (option parameter could not be parsed)
Option vf-add: Error while parsing noformat parameter fmt (444p)
Error parsing option vf-add (option parameter could not be parsed)
/usr/local/etc/mpv/encoding-profiles.conf:72: setting option vf-add='noformat=444p,noformat=444p9,noformat=444p10,noformat=422p,noformat=422p9,noformat=422p10' failed.
Passing multiple arguments to ofopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing multiple arguments to ofopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing more than 1 argument to vf-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing more than 1 argument to vf-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing multiple arguments to ovcopts-add is deprecated!
Passing more than 1 argument to vf-add is deprecated!
Passing more than 1 argument to vf-add is deprecated!
Passing more than 1 argument to vf-add is deprecated!
Playing: https://www.youtube.com/watch?v=AQBh9soLSkI
     Video --vid=1 (h264 1280x720 30.000fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
AO: [coreaudio] 48000Hz stereo 2ch floatp
(Buffering) A: 00:00:04 / 00:00:00 Cache:  0s+2MB
[ffmpeg] tls: IO Error: -9806
(Buffering) A: 00:00:09 / 00:00:00 Cache:  0s+2MB
[ffmpeg] tls: IO Error: -9806
(Buffering) A: 00:00:14 / 00:00:00 Cache:  0s+2MB
[ffmpeg] tls: IO Error: -9806
(Buffering) A: 00:00:19 / 00:00:00 Cache:  0s+2MB
[ffmpeg] tls: IO Error: -9806
(Buffering) A: 00:00:24 / 00:00:00 Cache:  0s+2MB
[ffmpeg] tls: IO Error: -9806
(Buffering) A: 00:00:24 / 00:00:00 Cache:  4s+2MB
[ffmpeg] tls: IO Error: -9806
(Buffering) A: 00:00:34 / 00:00:00 Cache:  0s+2MB
[ffmpeg] tls: IO Error: -9806
(Buffering) A: 00:00:34 / 00:00:00 Cache:  4s+2MB
[ffmpeg] tls: IO Error: -9806
(Buffering) A: 00:00:34 / 00:00:00 Cache:  9s+2MB
[input] No key binding found for key 'k'.
(Buffering) A: 00:00:34 / 00:00:00 Cache:  9s+2MB
[input] No key binding found for key 'k'.
(Buffering) A: 00:00:34 / 00:00:00 Cache:  9s+2MB
Track switched:
     Video --vid=1 (h264 1280x720 30.000fps)
 (+) Audio --aid=1 (aac 2ch 48000Hz)
Subtitle VSFilter aspect compat: no
(Buffering) A: 00:00:34 / 00:00:00 Cache:  9s+2MB
[input] No key binding found for key 'k'.
Subtitle VSFilter aspect compat: no
(Buffering) A: 00:00:34 / 00:00:00 Cache:  9s+2MB
[input] No key binding found for key 'k'.
Subtitle VSFilter aspect compat: no
(Buffering) A: 00:00:34 / 00:00:00 Cache:  9s+2MB
[input] No key binding found for key 'k'.
[input] No key binding found for key 'k'.
[input] No key binding found for key 'k'.
Subtitle VSFilter aspect compat: no
(Buffering) A: 00:00:34 / 00:00:00 Cache:  9s+2MB
[input] No key binding found for key 'k'.

(Buffering) A: 00:00:34 / 00:00:00 Cache:  9s+2MB

# ie. still showing a 2MB cache

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
http://sprunge.us or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wiiaboo** [comment]
Try to build at least 0.28 or preferably git master. It might be an already resolved issue.
