### ISSUE TITLE
[Feature Request] Functionality of mplayer's -fs-border-bottom and -fs-border-top

### ISSUE THREAD

**Issue by T-jw** [mpv-player/mpv#5479]
### mpv version and platform
Running on manjaro.
`mpv -V`
`mpv 0.27.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects`
` built on Fri Dec 15 18:41:29 CET 2017`
`ffmpeg library versions:`
`   libavutil       55.78.100`
`   libavcodec      57.107.100`
`   libavformat     57.83.100`
`   libswscale      4.8.100`
`   libavfilter     6.107.100`
`   libswresample   2.9.100`
`ffmpeg version: 3.4.1`

### Reproduction steps
`mpv --fs-border-bottom=600 ./path/to/file.mp4`

### Expected behavior
In fullscreen mode, the video has a 600px black bar added to the bottom of the video, in effect, moving the video up by 600px.

### Actual behavior
`Error parsing option fs-border-bottom (option not found)`
`Setting commandline option --fs-border-bottom=600 failed.`

`Exiting... (Fatal error)`

**Comment by lachs0r** [comment]
[--video-align-y](https://mpv.io/manual/master/#options-video-align-y), [--video-pan-y](https://mpv.io/manual/master/#options-video-pan-y)
