### ISSUE TITLE
Problem audio and video sync

### ISSUE THREAD

**Issue by paolocomis** [mpv-player/mpv#5480]
Hello everyone, I use mpv from the terminal and I'm quite satisfied. But I'm not finding any solution to my problem. I launch the command: 

mpv video.mp4 - - audiophile audio.mp3 

NB: the video lasts 15 seconds, the audio 20 seconds.

The execution is done perfectly, but when the video ends, mpv does not close until the audio ends. How can I solve? Thanks in advance

**Comment by paolocomis** [comment]
The correct command is:

mpv video.mp4 --audio-file audio.mp3

**Comment by wm4** [comment]
mpv continues plays until the longest stream ends. So it doesn't look like there's a big here. You can use ``--end=15`` to make it stop playback at 15 seconds. (If you want that done automatically, you'd have to write a script.)

**Comment by paolocomis** [comment]
I thank you for the answer. So to make automatic closing of mpv when the video stream ends you suggest to create a script?

Do you mean a script that first calculates the duration of the variable video and then uses for example --end=$videoduration ?

**Comment by zc62** [comment]
@paolocomis  I think this is what you need:
```lua
mp.register_event("file-loaded", function(name, value)
    local video_end = mp.get_property_number("duration")
    mp.commandv("set", "end", video_end)
end)
```
Save this to a file with `.lua` extension and place it in `~/.config/mpv/scripts/` or `%APPDATA%/mpv/scripts/` if in Windows.

**Comment by paolocomis** [comment]
Thank you so much, you solved a huge problem;)
