### ISSUE TITLE
The timeline of the SUP subtitle does not match the video.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#5485]
The subtitle is fine for the MPC-BE player on Windows, but not for the MPV player on Linux.
### mpv version and platform
mpv 0.28.0-215-g59f9547fb5 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.7.100
   libswscale      5.0.101
   libavfilter     7.11.101
   libswresample   3.0.101
ffmpeg version: N-89951-g3caecf7ce8
### Reproduction steps
Play video with SUP subtitle.
### Expected behavior
The timeline is match.
### Actual behavior
It's not.
### Log file
[timeline.log.zip](https://github.com/mpv-player/mpv/files/1692414/timeline.log.zip)

**Comment by wm4** [comment]
That's not enough information to even guess what's your problem.

**Comment by zc62** [comment]
Sub desync? I remember I had similar issues before, but MPC-BE didn't work well either.

**Comment by huangjun604** [comment]
Meet the same issue since 0.28.0 I believe or earlier (I tested 0.27.0 and it works well). The SUP will skip the blank in the front and play the first sentence directly, which lead to the timeline desync.

**Comment by mxalbert1996** [comment]
This problem still exists. When mpv loads SUP subtitles from external file, it will always show the first sentence at 00:00:00 (the very beginning of the video) so all the sentences after that will not be correctly shown. However there is no problem with internal PGS subtitles (I muxed the video and the SUP file with MKVToolNix and the problem went away).

**Comment by laichiaheng** [comment]
@mxalbert1996 It's so inconvenient if I'm running out of disk space
@wm4 It still exists in 0.29.1

**Comment by zc62** [comment]
@huangjun604 Thanks for the info that v0.27.0 works while v0.28.0 doesn't. I bisected between these two tags today and found 520fc7403621156676b1ca183aed4911bf6c47b5 triggers the bug.
