### ISSUE TITLE
Support video filter 'expand' 

### ISSUE THREAD

**Issue by xdilemite** [mpv-player/mpv#5486]
mpv version0. 28 and windows 
Please  may i know  why video filter, 'expand' was dropped in mpv 0.28 release. I find it very useful in placing subtitle in black borders  and customising the video display. Is there an alternative to this vf expand.  Please if non bring it back.  Thanks

**Comment by xdilemite** [comment]
Using this option in mpv.conf vf=expand=0:-50:0:0:,  with video-aspect=1.94 in mpv previous versions before 0.28  is missed.  Please  reintroduce vf expand filter in mpv version 0.28. Thanks

**Comment by lachs0r** [comment]
This isn’t MPlayer. You don’t have to do it in such a roundabout way.

See manual for relevant options: [--sub-ass-force-margins](https://mpv.io/manual/master/#options-sub-ass-force-margins), [--sub-use-margins](https://mpv.io/manual/master/#options-sub-use-margins), [--stretch-image-subs-to-screen](https://mpv.io/manual/master/#options-stretch-image-subs-to-screen).

Of course, these only work if you’re *not* using the `xv` video output (which you shouldn’t be using anyway).

If none of these options do what you want, you can use the [pad](https://ffmpeg.org/ffmpeg-filters.html#pad-1) video filter instead.

**Comment by wiiaboo** [comment]
Examples of `pad` usage:
```
Ctrl+w vf toggle pad=x=-1:y=-1:aspect=16/9
Ctrl+f vf toggle pad=x=-1:y=-1:aspect=4/3
```
