### ISSUE TITLE
Unable to find development files for some of the required FFmpeg/Libav libraries.

### ISSUE THREAD

**Issue by greencopper** [mpv-player/mpv#5493]
Using git master.

Doing:

```
echo --enable-mmal >> ffmpeg_options
./use-mpv-release
./use-ffmpeg-release
./update
./rebuild -j4
```

Result:

```
Checking for Libav/FFmpeg library versions                           : ffmpeg not found 
Unable to find development files for some of the required FFmpeg/Libav libraries. Git master is recommended.
```

This seems to be a repeated problem for people as the net is filled with issue reports and other postings.

Is it not possible to get this fixed once and for all?

```
ffmpeg:
ffmpeg version N-89955-g118e1b0b33 Copyright (c) 2000-2018 the FFmpeg developers
```

**Comment by kevmitch** [comment]
You aren't using git master, you're explicitly using releases of both ffmpeg and mpv. That doesn't currently work. You need ffmpeg git master for the latest release as well as git master of mpv. It will be fixed "once and for all" once ffmpeg makes a new release.

**Comment by tg-m** [comment]
@kevmitch That's quite funny, new release (3.4.2) of the FFmpeg was on Feb, 11th, yet still I had to figure out what's wrong. I'm not complaining, I get software for free. But the message could be more explicit. Something like: "Go and compile FFmpeg from the master branch!" or something similar.

Also there's a problem with setting-up a run path (or RUN_PATH or RPATH? -- I don't remember) in mpv's binary -- I have to launch mpv with LD_LIBRARY_PATH set to the place where the libass.so is. ;)

Yes, I know, I could've install it into /usr/local and have no problems.

**Comment by Hrxn** [comment]
?

Current FFmpeg release is 4.0.1

**Comment by tg-m** [comment]
@Hrxn Indeed... I somehow missed that and used tag n3.4.2. Should've looked at the branches not tags. Thanks!
