### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by IamCarbonMan** [mpv-player/mpv#5494]
I've been trying to find a way to get mpv to show an image file when paused for a given  amount of time (say 1 minute). I use a long-running mpv instance with the `--wid 0` option to play videos and music in the background while I work, but since MPV is drawing onto the root window I can't have a desktop wallpaper without killing mpv and starting it again later when I want to watch something again. It would be nice to have either a commandline option like "--splash-screen" or a Lua function that can display an image over the current screen (without having to skip to an image inserted into the playlist and later seek back to the video that was playing).

**Comment by wiiaboo** [comment]
If it's a relatively simple splash you could do it like the OSC does: https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L2210-L2237

**Comment by IamCarbonMan** [comment]
My hope was that it would be possible to support any image file that mpv can display.

**Comment by wiiaboo** [comment]
That's been requested before, iirc, and not accepted, so it's unlikely it'll get accepted this time too.

**Comment by wiiaboo** [comment]
See https://github.com/mpv-player/mpv/issues/3565

**Comment by Dudemanguy** [comment]
As noted in the older issue, any arbitrary image is not really possible. The best you can do is something like what the OSC does.
