### ISSUE TITLE
Mouse actions on OSC (improvement ideas)

### ISSUE THREAD

**Issue by Stefan986** [mpv-player/mpv#5496]
As for now it is implemented as mouse wheel action on volume icon for volume control on OSC, and left/right mouse button on audio and subtitles icons, but there is room for improvement.

Preferably these should be configurable in input.conf something like this (I would use these myself)

**OSC_SUB** for subtitles icon
**OSC_AUDIO** for audio track icon
**OSC_VOL** for volume icon
**OSC_FS** for (fulls)creen icon
**OSC_SEEK** for seekbar

OSC_SUB AXIS_UP add sub-delay 0.1
OSC_SUB AXIS_DOWN add sub-delay -0.1
OSC_SUB MOUSE_BTN2 cycle-values sub-size "0.850" "0.900" "0.950" "**1.000**" "1.050" "1.100" "1.150"

if sub-size is set in mpv.conf other than **1.000** it could cycle from set subtitle size something like
"-0.150" "-0.100" "-0.050" >"sub-size set in mpv.conf"> "+0.050" "+0.100" "+0.150"

OSC_AUDIO AXIS_UP add audio-delay 0.05
OSC_AUDIO AXIS_DOWN add audio-delay -0.05

OSC_VOL MOUSE_BTN2 cycle dynamic_range_compression (from LUA script e.g.)

OSC_SEEK AXIS_UP seek 10
OSC_SEEK AXIS_DOWN seek -10
*useful if AXIS_UP and AXIS_DOWN is already bind to something other than seek

OSC_FS AXIS_UP add video-zoom 0.05
OSC_FS AXIS_DOWN zoom add video-zoom -0.05
OSC_FS MOUSE_BTN2 cycle-values video-aspect "16:9" "16:10" "4:3" "1.85:1" "2.21:1" "2.35:1" "2.39:1" "5:4" "-1"

Combining right click MOUSE_BTN2+AXIS_UP/AXIS_DOWN would make space for even more combinations for controlling actions with mouse only, just not trigger MOUSE_BTN2 action when released after combining it with scroll wheel. It is true the MOUSE_BTN0 has no action assigned, but it is more natural in hand if MOUSE_BTN2 is pressed with middle finger and AXIS scrolled with index finger than the other way around. Or even HOLD_DRAG for subtitle position on OSC_SUB or video pan on OSC_FS, a lot of ideas comes to mind. Scroll mouse button click is not implemented at all, one more action can be assigned to it (AXIS_BTN). Making height of OSC adjustable in mpv.conf would make this even easier if seekbar and icons were a little higher/bigger.

If you think what is use case, I'd rather use this with tiny PC connected to my TV as a media centre (and controlling it with mouse from 12 feet away) than having wireless keyboard sitting on my living room desk all the time. Not enough space for popcorn :)

**Comment by wiiaboo** [comment]
https://github.com/wiiaboo/mpv-scripts/blob/master/zones.lua ?

**Comment by Stefan986** [comment]
I am aware of zones lua script, but what I am suggesting is native support for that and I believe it is way more intuitive having icons on OSC as "zones". I thought it would be rather simple implementation since it is already possible (scrolling on volume icon and clicking on all of them).

Things like that being user configurable would be fantastic.

**Comment by wiiaboo** [comment]
It's not simple at all. The OSC isn't a GUI on which the elements can be assigned inputs like that.
Nor do I feel the need to add that much configurability to something already so brittle, but that's my opinion.

**Comment by Dudemanguy** [comment]
Probably safe to reject this. The OSC is extraordinarily complicated already as is so something like this won't be a part of mpv's defaults anytime soon.
