### ISSUE TITLE
Wrong dimensions when using \pos tag with show-text

### ISSUE THREAD

**Issue by Keyreach** [mpv-player/mpv#5497]
### mpv version and platform

0.14.0, Linux, armv7l

### Steps to reproduce

`show-text "${osd-ass-cc/0}{\\pos(1900, 1000)}${osd-ass-cc/1}Text"`

### Actual behavior

Coordinates that are applying with ASS {\pos} tag seems to be not related both to video size and real screen size. Right-most coordinate is about 500 and bottom-most is about 300 on 1920x1080 screen for any video

**Comment by sfan5** [comment]
> 0.14.0

0.14.0 was released over 2 years ago, you should update.

**Comment by wiiaboo** [comment]
Also, it has to do with the default OSD resolution, which is not the same as your screen's. iirc, it's based on 720px high and width depends on the window aspect ratio.
