### ISSUE TITLE
waf build --verbose only builds with 1 job

### ISSUE THREAD

**Issue by c-14** [mpv-player/mpv#5502]
### Reproduction steps

./waf configure && ./waf build --jobs=8 --verbose

(Doesn't have to be 8 jobs, any number >1 will do, the larger the number the easier it is to notice the effect)

### Expected behavior

waf builds mpv with 8 jobs

### Actual behavior

waf builds mpv with 1 job

### Extra Information

The issue is caused by commit b8b3163b859ab01cb5b2254e6c78fd63208d2f66,  and in particular by c_preproc.go_absolute=True
Removing that line causes the build to function as expected again
I don't know why this is happening and why it's only happening with --verbose, I just thought I'd mention it because it's been bothering me for a while

Note that waf will still spawn the number of jobs you request, it just won't use them to compile anything

**Comment by Dudemanguy** [comment]
The `--jobs` argument works for me on current master. No clue when this was fixed but feel free to reopen if the issue really does still exist.
