### ISSUE TITLE
change audio/video/sub track at runtime via IPC

### ISSUE THREAD

**Issue by themihai** [mpv-player/mpv#5503]
I'm trying to change the audio/video/subtitle track (by id) at runtime but I see no way to do it via IPC. It looks pretty trivial using command line[ arguments/options](https://mpv.io/manual/master/#track-selection)  (`--aid `,` --sid`, `--vid`) but I can't find any property to do it at runtime/playback time using IPC. 

The closest property I could find is [track-list](https://mpv.io/manual/master/#command-interface-track-list)   but this seems to be read only.

**Comment by wiiaboo** [comment]
```json
{"command": ["set_property", "sid", 3]}
```
Works fine here.
