### ISSUE TITLE
Couldn't update mpv without jack dependency 

### ISSUE THREAD

**Issue by xMikasa** [mpv-player/mpv#5508]
### mpv version and platform
mpv 0.27.0_6
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
updating mpv to .27.0_6 without jack dependency installed get the following error

[459/465] Linking build/libmpv.dylib
[460/465] Linking build/mpv
+ install /usr/local/Cellar/mpv/0.27.0_6/lib/libmpv.1.25.0.dylib (from build/libmpv.dylib)
+ install /usr/local/Cellar/mpv/0.27.0_6/bin/mpv (from build/mpv)
[463/465] Compiling TOOLS/zsh.pl
[464/465] Symlinking build/libmpv.dylib
dyld: Library not loaded: /usr/local/opt/jack/lib/libjack.0.dylib
  Referenced from: /usr/local/opt/ffmpeg/lib/libavcodec.57.dylib
  Reason: image not found
Couldn't find any options at /private/tmp/mpv-20180210-76169-dn5rtr/mpv-0.27.0/TOOLS/zsh.pl line 30.

Waf: Leaving directory `/private/tmp/mpv-20180210-76169-dn5rtr/mpv-0.27.0/build'
Build failed
 -> task in '_mpv' failed with exit status 255 (run with -v to display more information)

READ THIS: https://docs.brew.sh/Troubleshooting.html

### Expected behavior
Proper update
### Actual behavior
error message

If jack is not a dependency why was it necessary for me to install it before updating mpv. after it mpv updated normally

**Comment by CounterPillow** [comment]
That is a packaging issue, not mpv's problem as far as I can tell. Jack is an optional dependency in mpv, and unless your distro forces you to use it, you won't need it.

**Comment by wiiaboo** [comment]
It was an autodetected lib in FFmpeg 3.4.x, so if you built FFmpeg with JACK installed, mpv will also depend on it.

**Comment by ilovezfs** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/23957.
