### ISSUE TITLE
just blank blue picture with HDR content and D3D11

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#5509]
### mpv version and platform
mpv 0.28.0-227-gb01623e0d2
Win 10 x64

### Reproduction steps
Play HDR video with D3D11.

### Expected behavior
It should work like with Vulkan and OpenGL.

### Actual behavior
It just shows a blue picture.

### Log file
https://pastebin.com/8354Ejfd

### Sample files
any HDR video should do

**Comment by kevmitch** [comment]
Should be fixed by https://github.com/mpv-player/mpv/commit/4e7f4f10cef15d29f9e5093eff84e9e8168caf89
