### ISSUE TITLE
fullscreen is not working properly if the user is already in a fullscreen app.

### ISSUE THREAD

**Issue by themihai** [mpv-player/mpv#5514]
### mpv version and platform
OSX High Sierra
 built on Wed Jan  3 19:29:29 CET 2018
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.8.100
   libswresample   3.0.101
ffmpeg version: git-2018-01-02-57d0c24

### Reproduction steps
1. Start mpv with  --input-ipc-server=/tmp/mpvsocket --idle options.
2. Start a fullscreen application (i.e. Chrome in fullscreen)
3. Send command to mpv to load a new video file/url (using an external mechanism) through  the ipc socket
4. Set fullscreen property to fullscreen (via the ipc socket)
### Expected behavior
The mpv player steal the focus and should be displayed in fullscreen streaming the video.
### Actual behavior
mpv is launched in a small window without borders, mainly within the main window. This doesn't happen all the time. Sometimes it is displayed correctly in a new fullscreen window/space.
### Log file
In the session below(from logs) I opened and closed a files/streams for about 2 - 3 times successfully (mpv was opened properly in fullscreen mode). On the last file/stream it loaded in a small borderless window (see the image attached) instead of proper fullscreen.

https://www.dropbox.com/s/2b42c24mk69fte3/output.txt?dl=0
![Screenshot](https://i.imgur.com/fGCHvXW.jpg)

**Comment by Akemi** [comment]
is step 3 required? i just do:
1. `mpv --input-ipc-server=/tmp/mpvsocket --pause FILE`
2. fullscreen terminal
3. fullscreen terminal > `echo '{ "command": ["set_property", "fullscreen", true] }' | socat - /tmp/mpvsocket`

that works properly for me

**Comment by themihai** [comment]
Ok.. so I kinda reproduced the "bug".
Open Terminal in fullscreen. Open two tabs in it.
1. In one tab: `mpv http://vm2.dashif.org/dash/vod/testpic_2s/multi_subs.mpd  --input-ipc-server=/tmp/mpvsocket --pause --idle`
2. Then immediately  in the second tab `echo '{ "command": ["set_property", "fullscreen", true] }' | socat - /tmp/mpvsocket`
Result:
  Instead to be displayed in fullscreen the video is displayed in a window without title bar and without buttons (which I believe shows that it tried to go in fullscreen otherwise it would have the top bar controls(close, minimise, fullscreen buttons). 

I hope your internet is not working too fast because this might depend on the internet speed.  I believe that if you set the fullscreen property before the movie is actually starting playing(i.e. it's still downloading it) you get this behaviour. This may be due the fact the window may not be large enough to go in fullscreen before the video is playing(this is just speculation from my side) so you endup with that naked tiny window.

**Comment by Akemi** [comment]
i recently completed my work on the new [cocoa-cb backend](https://github.com/mpv-player/mpv/commit/c5e4538bc4b63f02bf89f62aa25a37b9eb0c0316) for opengl-cb and deprecated the old cocoa backend. it would be nice if you could test with git master and `--vo=opengl-cb` instead.

**Comment by themihai** [comment]
The bug is still present. First time I've tried it went into fullscreen, second and 3rd time I've got a small window, so the bug is not always reproductible  now. The change now is that the small window has top buttons (close, minimise, fullscreen). 

```
$ mpv --version
mpv 0.28.0-289-g13b90bc Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Mon Feb 19 11:44:41 EET 2018
ffmpeg library versions:
   libavutil       56.7.101
   libavcodec      58.11.101
   libavformat     58.9.100
   libswscale      5.0.101
   libavfilter     7.12.100
   libswresample   3.0.101
ffmpeg version: git-2018-02-17-d2fc244

```

Steps to reproduce it:
1. Open terminal in fullscreen
2. Open two tabs:
 - in one  tab : 
 `  $ mpv http://vm2.dashif.org/dash/vod/testpic_2s/multi_subs.mpd --input-ipc-server=/tmp/mpvsocket --pause --idle --vo=opengl-cb
`
 - in another tab(this should be executed immediately after first tab, timing seems to be important)
` echo '{ "command": ["set_property", "fullscreen", true] }' | socat - /tmp/mpvsocket`

**Comment by Akemi** [comment]
i couldn't reproduce this so far. only thing i noticed is that the old cocoa backend sometimes didn't want to go fs (though without titlebar glitches) but cocoa-cb always worked.

though what can happen is that the system prevents the fullscreen and consequential the [windowDidFailToEnterFullScreen](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa-cb/window.swift#L180) is triggered, which should recover the windowed state. if that happens i wouldn't consider it a bug.

does it work if you delay setting the fullscreen property by a few ms?

**Comment by themihai** [comment]
If I delay the fullscreen command a bit I get better results but it still fails sometimes.
 Even if I try to start the player directly in fullscreen with ``--fs``  it has failure rates. 
   I've made a screencast with the `--fs` option. It fails to go fullscreen for several times and then it starts going into fullscreen then again starts failing.

https://www.youtube.com/edit?o=U&video_id=teWwS1wbKI4


``mpv http://vm2.dashif.org/dash/vod/testpic_2s/multi_subs.mpd --input-ipc-server=/tmp/mpvsocket --pause --idle --vo=opengl-cb --fs``

**Comment by themihai** [comment]
I've updated to HEAD and used ``--vo=libmpv`` and now I have greater success rate. I will update this issue when I get some conclusive results.

**Comment by Akemi** [comment]
yeah i changed how starting with `--fs` behaves slightly. though this shouldn't change the behaviour when changing fs via property.

i tried it around 50 times now, and i could reproduce it once.

**Comment by mirkoschubert** [comment]
I recently got it as well... I have the latest version of mpv (0.28.2). When I open a video with `mpv --fs file.mp4` in iTerm2 in full screen mode, it beeps and mpv won't open in full screen. As soon as I leave the full screen in iTerm2 and start it again, everything works perfectly fine. One time I got it working correctly out of... maybe 30 times.

**Comment by Akemi** [comment]
the latest version is master. 0.28.2 is just the latest release which uses a now deprecated backend that was replaced by cocoa-cb. beeping implies that there was a problem with entering fullscreen that came from the system and it refused to enter fs. in that case mpv rightfully falls back to being windowed.

there is a PR (#5753) open that might fix that problem, though i can't confirm it for certain because of reproducibility on my end.

**Comment by Akemi** [comment]
should be retested with git master. let me know if the issue still persists.
