### ISSUE TITLE
There is a black line beneath the subtitle if sub-blur is enabled

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#5515]
![deepin _20180212231232](https://user-images.githubusercontent.com/9532105/36104767-d6eb9222-104d-11e8-9e76-77b53cb6e31b.png)

### mpv version and platform

mpv 0.28.0-223-g5997248505 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.7.100
   libswscale      5.0.101
   libavfilter     7.11.101
   libswresample   3.0.101
ffmpeg version: N-89955-g118e1b0b33

### Reproduction steps
--sub-blur=10
--stretch-image-subs-to-screen
--sub-use-margins=no
--sub-font="Noto Sans CJK TC Medium"
### Expected behavior
The blur effect only surrounds the subtitle.
### Actual behavior
If the subtitle is on the 2nd line, the line will appear.
### Log file
https://mega.nz/#!KVgESSKD!d-bGnDO97mu9yslwu1tH5uhCjjxd2ItLoh1JWBm4aiU

**Comment by wiiaboo** [comment]
Why not just use --sub-background?

**Comment by laichiaheng** [comment]
@wiiaboo I didn't see it in the manual.

**Comment by wiiaboo** [comment]
[--sub-back-color](https://mpv.io/manual/master/#options-sub-back-color), I mean.

**Comment by laichiaheng** [comment]
--sub-blur looks more comfortable for my eyes.
--sub-back-color is too ugly
![deepin _20180213212227](https://user-images.githubusercontent.com/9532105/36151893-0cd10398-1104-11e8-98b6-dda9282f4118.png)

**Comment by wiiaboo** [comment]
You can use transparency on sub-back-color too, but apparently sub-blur doesn't work on it.
Anyway, this is a libass issue, most likely, so you should open an issue [there](https://github.com/libass/libass/issues) instead.

**Comment by laichiaheng** [comment]
OK, thanks.
