### ISSUE TITLE
How install 0.28 Homebrew?

### ISSUE THREAD

**Issue by misiekkb** [mpv-player/mpv#5519]
How to install version 0.28 with homebrew? Because when I any upgrade repositories with homebrew I always problem with mpv, when I compile 0.28. On homebrew default is version 0.27.1 I heve problem with this version with graphic card on 0.28 everything is OK.

**Comment by Akemi** [comment]
that's a homebrew issue. they will update their formula when ffmpeg releases a new release. alternative you can use https://laboratory.stolendata.net/~djinn/mpv_osx/.

**Comment by Argon-** [comment]
You need `HEAD` ffmpeg for mpv >= 0.28:

    brew install --HEAD ffmpeg
    brew install --HEAD mpv

**Comment by misiekkb** [comment]
Akemi please help me with this. I try with compile, update formula but still I have problem with install mpv 0.28, because 
"Checking for FFmpeg/Libav present                                    : no ('libavcodec' not found) 
FFmpeg/Libav development files not found."

I downloaded ffmpeg with correct:
 libavutil >= 56.6.100
libavcodec >= 58.7.100
libavformat >= 58.0.102
libswscale >= 5.0.101
libavfilter >= 7.0.101
libswresample >= 3.0.100

but this is binary.

**Comment by kevmitch** [comment]
What's binary? That's a compilation error. you shouldn't need to compile the stolendata build. If you are compiling, do what @Argon-  said. You need ffmpeg HEAD.

**Comment by misiekkb** [comment]
Now I use stolen data build, but I prefer compile yourself.

I try ffmpeg head like @Argon wrote, but this way installing old library like libavcodec 57 not 58, mpv 0.28 must have libavcodec 58 and etc.
