### ISSUE TITLE
mpv simple spliter mp4  js

### ISSUE THREAD

**Issue by wagic520** [mpv-player/mpv#5523]
var precut=""
var nextcut=""
function something_handler() {
   
    mp.utils.write_file('file://'+mp.utils.split_path(mp.get_property('path'))[0]+'cut.py', "import subprocess \nsubprocess.Popen('ffmpeg -hide_banner -ss "+precut +" -y -i "+'"'+"'+(r'"+mp.get_property('path')+"')+'"+'"'+" -t "+nextcut +"  -c:a copy -c:v copy "+'"'+"'+(r'"+mp.get_property('path')+"')+'"+'02.mp4"'+"'"+")")

}

function  endthing_handler(){
    nextcut=    mp.get_property("playback-time")
   
}
function delthing_handler(){
  
    precut=    mp.get_property("playback-time")

}

mp.add_key_binding("c", "something", something_handler)
mp.add_key_binding("x", "endthing", endthing_handler)
mp.add_key_binding("z", "delthing", delthing_handler)

**Comment by wagic520** [comment]
make python script ,use ffmpeg splite 
this share

**Comment by wiiaboo** [comment]
This isn't the place to share scripts. It's in that wiki link.

**Comment by wagic520** [comment]
How add to wiki.

**Comment by wiiaboo** [comment]
Put it in a [gist](https://gist.github.com/) and then do like the others: https://github.com/mpv-player/mpv/wiki/User-Scripts/_compare/f09d6adf50863d23744cc79e32b766b32ecc0802...8be3f510d0cdc69e9644fd167d6076eb7dbac324

**Comment by wiiaboo** [comment]
And don't remove other people's scripts. [Edit the page](https://github.com/mpv-player/mpv/wiki/User-Scripts/_edit) and add your own _like_ other people do.
