### ISSUE TITLE
rubberband audio filter sound problem

### ISSUE THREAD

**Issue by HybridDog** [mpv-player/mpv#5524]
### mpv version and platform

mpv 0.26.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.4-2

I'm using mpv 0.26.0-3ubuntu1 (according to apt show) on lubuntu 17.10

### Reproduction steps

Open a video with mpv --af=rubberband, e.g. `$ mpv somevideo.mp4 --af=rubberband`,
then press } to double the playback speed,
after that press backspace to reset the playback speed (to 1.0).

### Expected behavior

It should sound the same as how it sounds without the --af=rubberband command line parameter.

### Actual behavior

The sound is strange, l don't know if "metallic" is the right word for this.
Using rubberband is supposed to result in higher audio quality when the playback speed is changed. The scaletempo filter is disabled automatically when enabling rubberband, isn't it?

### Log file

Here're the audio filter messages:
```
[af] Adding filter rubberband 
[af] Audio filter chain:
[af]   [in] 32000Hz mono 1ch floatp
[af]   [rubberband] 32000Hz mono 1ch floatp
[af]   [out] 32000Hz mono 1ch floatp
[af]   [ao] 32000Hz mono 1ch floatp
[af] Adding filter lavrresample 
[af] Audio filter chain:
[af]   [in] 32000Hz mono 1ch floatp
[af]   [rubberband] 32000Hz mono 1ch floatp
[af]   [lavrresample] 32000Hz mono 1ch float [a]
[af]   [out] 32000Hz mono 1ch float
[af]   [ao] 32000Hz mono 1ch float
```

**Comment by wm4** [comment]
Known problem with librubberband.

**Comment by HybridDog** [comment]
Is that related?
https://github.com/mpv-player/mpv/issues/3928

**Comment by Akemi** [comment]
upstream problem, stale issue.

**Comment by eugenedm** [comment]
Why can't nobody fix it? This issue has been around for longer than 3 years.... Can somebody program something better?

**Comment by wm4** [comment]
Surely that's possible. We could introduce a new filter that fixes all problems, but someone would have to write it. Maybe even the old scaletempo filter would be fine if tuned correctly. Feel free to make a patch.
