### ISSUE TITLE
updater.bat returns "cannot index into a null array" Error

### ISSUE THREAD

**Issue by ArcAngelRyse** [mpv-player/mpv#5526]
### mpv version and platform

Latest git build (shinchiro)

### Reproduction steps

Running updater.bat as admin or not fails, just returns this error "cannot index into a null array".

### Expected behavior

Updates mpv and youtube-dl.exe

### Actual behavior

Not Working

### Log file

To be honest I don't know to make log files in situations like these.

### Sample files
well I was going to use mega.nz but thats also a cloud storage and since its says no cloud storage so and I tried that option suggested. Im new to it, completely.

### Extra

I updated it myself, using the git build for Shinchiro but it kinda sucks without the updater. I'm on the retail version of windows 10 pro - Build 16299 - it worked at one point but then stopped suddenly. Latest build didn't fix it either so it's still an issue for me at least. I haven't changed any settings relating to mpv or anything that could stop it from working properly at least I don't think I did.

**Comment by Hrxn** [comment]
Technically, not an issue with mpv...

**Comment by wiiaboo** [comment]
Wrong repo https://github.com/shinchiro/mpv-winbuild-cmake
