### ISSUE TITLE
video is frozen after fs animation

### ISSUE THREAD

**Issue by anticitizen4** [mpv-player/mpv#5527]
### mpv version and platform

git master, OS X 10.11.6

### Reproduction steps

Play any video file.

### Expected behavior

Picture should change.

### Actual behavior

Picture changes only when going in and out of fullscreen. The picture is the last frame of fullscreen change animation. That includes osc interface and info messages. After animation completes mpv responds to commands but the frame persists, no amount of mouse movements bring osc up. Audio is unaffected. Tried with my own settings, --no-config and also without settings folder, same result.

### Log file

https://bpaste.net/raw/15f9758283c5

**Comment by Akemi** [comment]
seems like [CVDisplayLinkSetOutputHandler](https://developer.apple.com/documentation/corevideo/1456927-cvdisplaylinksetoutputhandler) is [broken](http://www.openradar.me/26640780) on 10.11 and it was just introduced with that OS version. great work Apple, especially for not fixing it after 6 iterations of 10.11.

**Comment by Akemi** [comment]
should be fixed with #5529.
