### ISSUE TITLE
opengl-cb errors on macOS when switching windows while in fullscreen

### ISSUE THREAD

**Issue by valdotdev** [mpv-player/mpv#5530]
### mpv version and platform

```
mpv 0.28.0-279-g6751b5b Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Wed Feb 14 22:12:02 +08 2018
ffmpeg library versions:
   libavutil       56.7.101
   libavcodec      58.11.101
   libavformat     58.9.100
   libswscale      5.0.101
   libavfilter     7.12.100
   libswresample   3.0.101
ffmpeg version: N-45485-g474194a8d
```

`macOS High Sierra 10.13.3`

### Reproduction steps
1. Terminal using opengl-cb and hardware decoding in **FULLSCREEN**.
I did: `mpv --no-config --vo=opengl-cb --hwdec=auto -fs <video file.mkv>`
2. While in fullscreen, switch back to another window. In my case, I switched to my terminal window.

### Expected behavior
Normal/no errors.

### Actual behavior
Non-stop errors:
> [opengl-cb/videotoolbox] error creating IOSurface texture for plane 0: invalid context (0)
> [opengl-cb] Mapping hardware decoded surface failed.

### Log file

http://ix.io/J5M

### Sample files

I used anime episodes from HorribleSubs ;)

**Comment by Akemi** [comment]
it does not happen windowed and switching a space?

**Comment by valdotdev** [comment]
It doesn't. Only when in fullscreen then switch via cmd+tab

**Comment by Akemi** [comment]
does this help?
```
diff --git a/video/out/cocoa-cb/video_layer.swift b/video/out/cocoa-cb/video_layer.swift
index 05f0894..ed259d0 100644
--- a/video/out/cocoa-cb/video_layer.swift
+++ b/video/out/cocoa-cb/video_layer.swift
@@ -198,6 +198,7 @@ class VideoLayer: CAOpenGLLayer {
             if !cocoaCB.window.occlusionState.contains(.visible) &&
                 neededFlips > 1 && canDrawOffScreen
             {
+                CGLSetCurrentContext(cglContext!)
                 draw(cglContext!)
                 display()
             } else {
```

**Comment by valdotdev** [comment]
Sorry, it doesn't.

**Comment by Akemi** [comment]
just to make sure that i am not suspecting the wrong part of the code. does this fix the error?
diff --git a/video/out/cocoa-cb/video_layer.swift b/video/out/cocoa-cb/video_layer.swift
index 05f0894..5d6b760 100644
```
--- a/video/out/cocoa-cb/video_layer.swift
+++ b/video/out/cocoa-cb/video_layer.swift
@@ -198,7 +198,7 @@ class VideoLayer: CAOpenGLLayer {
             if !cocoaCB.window.occlusionState.contains(.visible) &&
                 neededFlips > 1 && canDrawOffScreen
             {
-                draw(cglContext!)
+                //draw(cglContext!)
                 display()
             } else {
                 display()
```

**Comment by valdotdev** [comment]
Still doesn't. I guess it's the wrong part?

**Comment by Akemi** [comment]
yeah then this code is the wrong part. though now it will be hard to find the problem because that's the only part where i do something 'fancy', or rather uncommon, with the context otherwise it's completely handled behind the scenes by the CAOpenGLLayer and out of my reach.

**Comment by valdotdev** [comment]
That's too bad. Does it happen on your end as well? I tried it on my other old rMBP and it does the same. Still waiting for my bro's from the repair shop so I could test it there as well. But i'm guessing the same thing will show up. 

I could just ignore it though since I don't notice any visual or performance degradations but seeing the terminal messed up is a sore eye.

**Comment by Akemi** [comment]
sadly i can't test it since either my MBP (mid 2010) is too old for hwdec or something else is up. it always errors in ffmpeg on init.

**Comment by Akemi** [comment]
i just had @avih, on irc, test both patches and they fixed the issue for him. @valdotdev are you sure you applied the patches properly and tested the right binary? if yes something is different on your setup and/or it might be a difference in something system library related.

**Comment by valdotdev** [comment]
I've been changing the code in the source file and compile/build again. And yes, I'm using the correct binary afaik. How do you set up yours? Weird...maybe I _am_ doing it wrong...

**Comment by Akemi** [comment]
i got hwdec to work now too on my test system, i could reproduce the issue and the patches fix the issue for me too.

**Comment by valdotdev** [comment]
I try again when I get home. After looking around my system config earlier things are pretty messed up even if I explicitly call the correct binary it won't actually use it. I'll let you know later.

**Comment by valdotdev** [comment]
Just got back. Did some major cleanup and yeah both patches seems to fix it. I feel so stupid now!

**Comment by Akemi** [comment]
that's great. i will open a PR when i am done fixing another issue.

**Comment by valdotdev** [comment]
Awesome. Thanks a lot!
