### ISSUE TITLE
Raspberry Pi DRM Failed to create KMS

### ISSUE THREAD

**Issue by sameer** [mpv-player/mpv#5533]
### mpv version and platform

mpv v0.27.7 on Raspberry Pi 3 ARMv7l

### Reproduction steps

Attempt to play any video without X or Wayland in the CLI `mpv --vo=drm --hwdec=rpi file.mp4`

### Expected behavior

The video should play

### Actual behavior

The video does not play

### Log file

[log](http://0x0.st/sTBU.log)

### Sample files

Not needed, any h264 video will do.

**Comment by wm4** [comment]
Not a mpv problem.

**Comment by sameer** [comment]
Any idea what's causing it?

**Comment by sameer** [comment]
Omxplayer seems to work fine

**Comment by wm4** [comment]
Apparently the kernel doesn't support DRM for you. I'm not sure why you expect the command line to work at all. Even if DRM worked, --hwdec=rpi would fail.

**Comment by sameer** [comment]
The kernel is the rpi official kernel. There's no reason it should fail.
Could it be because rpi bumped the kernel to 4.14?

**Comment by wm4** [comment]
omxplayer doesn't use DRM?

**Comment by wm4** [comment]
I wasted about 5 minutes of my precious, unpaid life by typing up this: https://github.com/mpv-player/mpv/wiki/FAQ#Video_on_RPI_doesnt_work_or_is_too_slow

**Comment by sameer** [comment]
Thanks Vincent, sorry for the confusion.

**Comment by wm4** [comment]
Feel free to enhance the FAQ if you found a solution. The main problem is that it's too hard to build, and also often distros don't bother doing that.

**Comment by sameer** [comment]
I managed to get it to work the first time I installed it on Raspbian, but now I have no clue how I did it...
I'll try to build through ArchlinuxArm and let you know if I figure it out.

**Comment by Gusar321** [comment]
Arch makes this quite easy, there are ffmpeg-mmal and mpv-rpi packages in AUR.

**Comment by sameer** [comment]
Yup, I saw those. I haven't gotten around to building mpv-rpi but I started ffmpeg-mmal.
It's hard to believe how old some of the repos on Raspbian are.
