### ISSUE TITLE
Libmpv: EOF code: 3 randomly

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5539]
### Reproduction steps
Through my application on vb net I tell libmpv to play a series of videos as a playlist with the "keep-open" parameter
### Expected behavior
That reproduces all the files correctly
### Actual behavior
With a certain video, it sometimes shows the first frame and automatically plays the next video in the playlist, and returns the result EOF code: 3
The strange thing about this is that it happens randomly, sometimes it reproduces it well, and sometimes it generates that error.
### Log file
[log.log](https://github.com/mpv-player/mpv/files/1731000/log.log)
### Sample files
https://mega.nz/#!rkRi0YyB!-0RvVz7F2uUJP5KbtK3Nr8MqN3KsuQVJvu_d4JE-kI8

Excuse me for my English level, I am writing from Argentina.

**Comment by wm4** [comment]
Can't reproduce any problem. In your log I see only:
```
[1084.966][d][cplayer] Run command: loadfile, flags=0, args=[C:\TVi Plus\Cliente\Videos\Ley de Medios\EP.mp4, replace, ]
[1084.966][v][cplayer] EOF code: 3  
...
[1084.969][v][cplayer] finished playback, success (reason 2)
```
That EOF code 3 is something that happens because you ran loadfile with `replace`, and the "reason 2" (MPV_END_FILE_REASON_STOP in the client API) is done for the same reason.

**Comment by Akemi** [comment]
if the problem still persists please open a new issue.
