### ISSUE TITLE
(Double-)HTML in YouTube subtitles

### ISSUE THREAD

**Issue by DrMcCoy** [mpv-player/mpv#5541]
Subtitles in YouTube videos seem to contain some limited HTML. I've seen `<i>` for italics and also `&amp;` instead of an actual `&`.

Both examples can be found in this video: https://www.youtube.com/watch?v=gq4av949-3Y.
The `&amp;` is at 00:00:34.088, and the italics tag is at 01:27:46.124.

However, looking at the .vtt file downloaded by youtube-dl, the `&amp;` is an `&amp;amp;`, while the `<i>` is an `&lt;i&gt;`, i.e. the HTML tags and entities are HTML-entity'd themselves.

I'm not sure if that's what YouTube spits out, or if that's maybe a youtube-dl bug, or if this should be fixed-up by mpv, or anything. Feel free to close this issue if you think it's not your problem, of course.

**Comment by wiiaboo** [comment]
That seems like double HTML encoding, so it's an issue with the subtitles.
It's broken in youtube too:
![image](https://i.fsbn.eu/fP87.png)
