### ISSUE TITLE
No video playback with gpu-context=x11vk

### ISSUE THREAD

**Issue by Dummweilbaum** [mpv-player/mpv#5543]
mpv version 0.28.0_285_g0dbad9503f-1, ffmpeg version 3.5.r90067.g310d56e86f-1 on Arch-Linux Kernel 0.28.0_285_g0dbad9503f-1-ck

### Reproduction steps
Play video file (all formats)
### Expected behavior
Mpv starts video playback
### Actual behavior
Mpv exits with "[vo/gpu] Failed initializing any suitable GPU context!" on gpu-context=x11vk or plays back teared and stuttering video while reporting "[vo/gpu/opengl] GLX not found." when running with no-config.

**Comment by CounterPillow** [comment]
Full log with `--log-file` please.

**Comment by Dummweilbaum** [comment]
My first comment has been rendered irrellevant since now mpv doesn't even recognize common file formats like mp4 or mkv
Logfile: https://0x0.st/sT3K.txt

**Comment by CounterPillow** [comment]
That's not exactly helpful when you don't provide the sample video file.

**Comment by Dummweilbaum** [comment]
I can reproduce this issue with literally any mkv or mp4 file.

**Comment by CounterPillow** [comment]
Which issue? The one where you can't create a Vulkan GPU context, for which you didn't provide a full log, or the one where you fail to play back "1.mkv", for which you provided a log?

Because I cannot reproduce the latter.

**Comment by Dummweilbaum** [comment]
The latter occurs with any file of mentioned formats, I could reproduce the former with a stream, logs are https://0x0.st/sTg8.txt for x11vk and https://0x0.st/https://0x0.st/sTgP.txt with --no-config for reference.

**Comment by CounterPillow** [comment]
Your Vulkan implementation is missing one of the following two vulkan extensions:

```
VK_KHR_surface
VK_KHR_xlib_surface
```

This likely is because it's broken in some way. If you've recently updated mesa, try rebooting the system.

>or plays back teared and stuttering video while reporting "[vo/gpu/opengl] GLX not found." when running with no-config.

Because it's falling back to the shitty x11 VO, because your OpenGL implementation appears to be completely broken.

I suggest you attempt to fix your graphics acceleration.

**Comment by Dummweilbaum** [comment]
I'm already using the latest mesa release, even after installing vulkan-radeon, recompiling mpv from git and rebooting the issues persist, https://0x0.st/sTgS.txt with x11vk, https://0x0.st/sTgQ.txt with --no-config

**Comment by CounterPillow** [comment]
What's the output of `glxinfo`?

**Comment by Dummweilbaum** [comment]
`[user@archlinux ~]$ glxinfo`
`name of display: :0`
`Error: couldn't find RGB GLX visual or fbconfig`

**Comment by CounterPillow** [comment]
Looks like your graphics driver is broken, so this is not an issue in mpv.

**Comment by kevmitch** [comment]
Yeah, something is messed up with your system completely independent of mpv Here are the first few google hits for this error on archlinux. Basically, take a look in your /var/log/Xorg.0.log.

https://bbs.archlinux.org/viewtopic.php?id=135562
https://www.linuxquestions.org/questions/slackware-14/couldn%27t-find-rgb-glx-visual-or-fbconfig-4175600898/
