### ISSUE TITLE
[opengl-cb] "OpenGL error INVALID_FRAMEBUFFER_OPERATION"

### ISSUE THREAD

**Issue by valdotdev** [mpv-player/mpv#5546]
### mpv version and platform

`macOS High Sierra 10.13.3 on a late 2013 13" rMBP (Intel Iris Graphics)`
```
mpv 13b90bc Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 18 23:46:04 +08 2018
ffmpeg library versions:
   libavutil       56.7.101
   libavcodec      58.11.101
   libavformat     58.9.100
   libswscale      5.0.101
   libavfilter     7.12.100
   libswresample   3.0.101
ffmpeg version: git-2018-02-15-8a8d0b3
```

### Reproduction steps
1. `mpv --no-config --vo=opengl-cb --hwdec=auto -fs <video_file>` **- should be in fullscreen**
2. Seek with either mouse click or the left/right arrow keys
### Expected behavior
No errors
### Actual behavior
Plays fine but "`[opengl-cb] after creating texture: OpenGL error INVALID_FRAMEBUFFER_OPERATION.`" error after seeking
### Log file
http://ix.io/M48
### Sample files
I downloaded the [Infinity War Big Game Spot trailer](https://www.youtube.com/watch?v=pVxOVlm_lE8) via `youtube-dl` for testing. But any video will do, I guess.

**Comment by Akemi** [comment]
dies [this](https://github.com/Akemi/mpv/commit/9124ca7881c8bc1a66bc1dce8882f0a43c32b460) fix it?

**Comment by valdotdev** [comment]
I'll test it out once I get home. :+1:

**Comment by valdotdev** [comment]
@Akemi Yep, it fixed it!
