### ISSUE TITLE
--sub-ass-force-style/--sub-ass-override=force doesn't affect inline style

### ISSUE THREAD

**Issue by Jimmy-Z** [mpv-player/mpv#5547]
0.28 Windows 10

Example:
`Dialogue: 0,0:00:00.00,1:00:00.00,Default,,0,0,0,,{\fn'Times New Roman'}test sub`

Only `no-ass` can change the font in this situation.

And yes there're stupid ass files that has inline style in each and every line.

**Comment by wiiaboo** [comment]
Use 'strip' then: https://mpv.io/manual/master/#options-sub-ass-override

**Comment by Jimmy-Z** [comment]
It will strip everything, I want to replace the font only, your suggestion will affect positioning and stuff.
