### ISSUE TITLE
Decoding errors when playing rtp streams with low framerates

### ISSUE THREAD

**Issue by gunnarmarten** [mpv-player/mpv#5550]
### mpv version and platform

macOS Sierra 10.12.6 
 
mpv 0.28.0-289-g13b90bc Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
ffmpeg library versions:
 libavutil       56.7.101
 libavcodec      58.11.101
 libavformat     58.9.100
 libswscale      5.0.101
 libavfilter     7.12.100
 libswresample   3.0.101
ffmpeg version: N-45682-gacdea9e7c

### Reproduction steps

Create a rtp stream with a custom framerate (3 fps for example). Other framerates behave quiet similar (<25 fps).  Playing a stream with 30fps is fine.

`gst-launch-1.0 -v videotestsrc ! video/x-raw,width=640,height=480 ! videorate ! video/x-raw,framerate=3/1 ! x264enc sliced-threads=true tune=zerolatency speed-preset=1 ! rtph264pay ! udpsink host=127.0.0.1 port=5004`

Play the stream using a sdp file:
rather simple sdp file: http://sprunge.us/HLHh

`mpv --no-config --log-file=output.txt test.sdp`

I tried disabling caching but the behaviour is the same:
`mpv --no-config --log-file=output.txt --demuxer-seekable-cache=no --cache=no test.sdp`

### Expected behavior

Plays the stream with the given framerate.
VLC plays it fine.
ffplay plays it fine:
`ffplay -loglevel debug -i -protocol_whitelist rtp,file,udp test.sdp`

### Actual behavior

Decoding breaks after a few seconds with decoding errors, artefacts and choppy playback

### Log file

http://sprunge.us/bWdW

### Sample files

See reproduction steps above

**Comment by wm4** [comment]
Does `--rtsp-transport=lavf` help?

**Comment by gunnarmarten** [comment]
No, same behavior.
(wanted to upload the logfile but sprunge isn't working right now). But the log looks the same as without `--rtsp-transport=lavf`

**Comment by wm4** [comment]
I can't currently install gstreamer because Debian broke everything for me. So I can't reproduce this now.

**Comment by gunnarmarten** [comment]
Hey, I tried rebuild this issue with ffmpeg as streaming source. It behaves quite similar although ffplay stream playback is not always flawless anymore...

You can try this ffmpeg line to create the stream:
`
ffmpeg -r 3 -i </path/to/movie> -preset ultrafast -an -vcodec libx264 -tune zerolatency -b 900k -f rtp rtp://127.0.0.1:5004
`
or this for a test video src:

`ffmpeg -r 3 -f lavfi -i testsrc -s 640x480 -pix_fmt yuv420p -preset ultrafast -an -vcodec libx264 -tune zerolatency -b 900k -f rtp rtp://127.0.0.1:5004`

I had issues both with vlc and ffplay when using the testsrc. But a real movie src worked for both (First ffmpeg cmdline). Don't know why.

For mpv playback the behavior is like with the gstreamer src:

Playback breaks after a few seconds for both ffmpeg stream examples and then playback stop completely.
Logfile: https://pastebin.com/FQiZMYYK

And I did a test with a regular framerate of 30 fps and mpv playback breaks there too:
`ffmpeg -r 30 -f lavfi -i testsrc -s 640x480 -pix_fmt yuv420p -preset ultrafast -an -vcodec libx264 -tune zerolatency -b 900k -f rtp rtp://127.0.0.1:5004
`

mpv Logfile: https://pastebin.com/NTVz9HCX

**Comment by wm4** [comment]
The sdp file isn't available.

**Comment by gunnarmarten** [comment]
sdpfile: https://pastebin.com/rktnDzbD

or you can use the sdp which ffmpeg outputs when starting rtp streaming, it makes no difference.

**Comment by wm4** [comment]
Right... I tried this one, and used the sdp generated by it:

>ffmpeg -r 30 -f lavfi -i testsrc -s 640x480 -pix_fmt yuv420p -preset ultrafast -an -vcodec libx264 -tune zerolatency -b 900k -f rtp rtp://127.0.0.1:5004

mpv seems to work well, until it reaches maximum prefetch (as configured by stream and demuxer caches). ffplay just buffers infinitely (probably will eventually run out of memory in very unnice ways). I believe this is because it specifically enables infinite buffers for protocols like rtp and sdp. vlc just craps up without making much progress, printing messages like
```
[00007fefb4c17b30] avcodec decoder error: more than 5 seconds of late video -> dropping frame (computer too slow ?)
```

This command:
```
ffmpeg -r 3 -i </path/to/movie> -preset ultrafast -an -vcodec libx264 -tune zerolatency -b 900k -f rtp rtp://127.0.0.1:5004
```

Didn't work well in any of mpv/vlc/ffplay. In mpv/ffplay it drops packets and doesn't get to play it properly. vlc behaves as above.

So I can't reproduce anything mpv does specifically wrong.

**Comment by gunnarmarten** [comment]
I tested more and more, maybe ffmpeg is not the most reliable streaming src, my test results seemed flaky...
But anyway, your comment about stream and demuxer cache got me thinking, I tried earlier disabling the cache but now I got the feeling mpv isn't using a cache at all. So I added `--cache=yes` to my mpv cmd line and voila mpv plays flawlessly, even my initial gstreamer stream with low framerate.
I should have thought about that earlier...

So I think the main issue is, playing a stream via sdp file does not enable the cache.
Should that be a default for sdp file-types?

**Comment by wm4** [comment]
Detecting whether some FFmpeg thing (avio stream or demuxer) works over network isn't easy. But we have a large amount of per-format hacks for libavformat anyway, so I added it to my random PR.

**Comment by wm4** [comment]
To clarify, it enables cache and disables seeking (outside of cached regions).

**Comment by gunnarmarten** [comment]
Just tested your commit 1420013 and I can confirm the cache is now enabled and the playback of the stream works well.
Thanks for looking into that.

**Comment by gunnarmarten** [comment]
Closing this, since #5580 got merged
