### ISSUE TITLE
Per-File Options bugs

### ISSUE THREAD

**Issue by arsonoff** [mpv-player/mpv#5552]
### mpv version and platform

mpv 0.28.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.5.100
   libswscale      5.0.101
   libavfilter     7.11.101
   libswresample   3.0.101
ffmpeg version: git-snapshot-20180116-RPMFusion

### Reproduction steps

test.mp4 - file with black bands
command line: `cat testX | xargs mpv -v --playlist-start=Y`

1) test1:
```
--\{ "test.mp4" --panscan=1 --\}
--\{ "test.mp4" --panscan=0.5 --\}
--\{ "test.mp4" --panscan=0 --\}
```
At forced switching (keys "<" and ">") on the following/previous position of the playlist, 
the option "panscan" does not change (occasionally switches, but for what reason I did not understand).
If playing of the position of the playlist comes to an end upon termination of time, 
then switching of the option "panscan" happens correctly.
Tried with different VO backends, does not influence.

0.25.0 - there is no bug
0.26.0 - there is no bug
0.27.0 - bug
0.28.2 - bug

2) test2:
```
--\{ "test.mp4" --vo=x11 --\}
--\{ "test.mp4" --vo=sdl --\}
--\{ "test.mp4" --vo=vaapi --\}
--\{ "test.mp4" --vo=opengl --\}
```
The first VO backend is always used. Does not depend on the mpv version (0.25-0.28).

3) When using per-file options, at the end of time of reproduction there is the image distortion. 
It seems that action of options comes to an end earlier, than reproduction comes to an end. 
The image changes in sizes, and also there are other artifacts (depending on options).

Whether mpv supports any formats of playlists in which it would be possible to set options for each position, but not to use "cat|xargs"?

**Comment by wm4** [comment]
> test1

Can't reproduce (I only tried a normal command line instead of using xargs, but that should not change anything).

> test2

Runtime changes to VO are not supported. You can do it manually by disabling and reenabling video (so the VO gets recreated manually).

> 3

Could be race condition with resetting the options and destroying the VO, but I don't consider that a bug. This particular would be rather hard to work around, because the VO is strictly destroyed after the playlist entry is finished, otherwise changing between files would destroy and recreate the window. But you could possibly use a Lua script and the hook API to force it otherwise.

**Comment by arsonoff** [comment]
>1
> Cannot reproduce 

Ah, to see effect of panscan, still there has to be an option of the sizes of a window (--geometry or --fs) and aspect-ratio of the video and the screen should be different. 

For example: https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4,
```
mpv --geometry 320x160 --{ sintel_trailer-480p.mp4 --panscan 1 --} --{ sintel_trailer-480p.mp4 --panscan 0.5 --} --{ sintel_trailer-480p.mp4 --panscan 0 --}
```
0.25, 0.26 or at normal reproduction (without switching tracks):
[![scrot.jpg](https://s10.postimg.org/9vcxhlg5l/scrot.jpg)](https://postimg.org/image/f6ru2b285/)

0.27, 0.28 with switching tracks - are black bands as on the first screenshot (sometimes switches and gets stuck on another)

>2
> You can do it manually by disabling and reenabling video

Close/open mpv or execute the command from IPC pipe?

>3
> but I do not consider that a bug

Can do it not an bug,  but looks not ace (the image twitches).

**Comment by wm4** [comment]
> Ah, to see effect of panscan, still there has to be an option of the sizes of a window (--geometry or --fs) and aspect-ratio of the video and the screen should be different.

Yes, I tried that.

> Close/open mpv or execute the command from IPC pipe?

You can set the "vid" property to "no" and then back to "1".

**Comment by arsonoff** [comment]
>1
Cannot reproduce

Tested on two different computers. On both intel-built-in GPU (baytrail, skylake).
Versions of libraries identical (ffmpeg-3.5-0.1.20180116git.el7.centos.x86_64, libva-2.0.0-1.el7.centos.x86_64 ...), I change only mpv (0.25-0.27 build with a patch for libva2), any option --vo.

Reproducibility - 100% ... I do not know what else to report.

Also:
mpv-0.25.0/ffmpeg-3.3.2/libva-1.8.2 -- there is no bug.
mpv-0.27/ffmpeg-3.4.1/libva-2.0.0 -- bug.

**Comment by wm4** [comment]
Works with mpv 0.27.2 and git master. I didn't try with the vaapi POS though.

If you're using vaapi then thanks for wasting our time and not posting a log or exact steps.

**Comment by arsonoff** [comment]
0.28.2:
https://pastebin.com/40sZkNcp --vo=gpu, switched ~2 times from 10
https://pastebin.com/uafkbqq1 --vo=vaapi, switched ~2 times from 10
https://pastebin.com/VU5rGsT0 --vo=x11, switched ~3 times from 10

sintel_trailer-480p.mp4 is the good file, on other files 1 times from 20-30

**Comment by arsonoff** [comment]
0.26.0 (working):
https://pastebin.com/jiLuLMgg --vo=opengl
https://pastebin.com/Ey7Bipan --vo=vaapi
https://pastebin.com/pjhML63P --vo=x11

**Comment by wm4** [comment]
Why are you reporting this with different VOs?

**Comment by arsonoff** [comment]
Without the reason. Just for completeness.

**Comment by wm4** [comment]
Well of course that's a giant waste of time because now I also tried with those VOs.

Can't reproduce.

**Comment by arsonoff** [comment]
I apologize. 
But first it seemed to me that at different VO's bug is shown in different degree. 
But after three days of tests this degree did not manage to be set, but doubts remained ;)

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
