### ISSUE TITLE
x11/mpv reports 1916x1076 instead of 1920x1080

### ISSUE THREAD

**Issue by sylware** [mpv-player/mpv#5553]
gnu/linux, recent git linux/x11/GL/ffmpeg stack, fvwm window manager.
Playing 1920x1080 vids (vp9/opus) from youtube, fullscreen reports 1916x1076 vid size instead of 1920x1080.
(mplayer is ok). Resizing has a few pixels/lines off too. gpu vo, but I tried xv vo too.
(mpv 5d6fb5267d9ddc85e6084665ab6b20a06d214bbc)

**Comment by Argon-** [comment]
Why did you ignore the issue template?

**Comment by sylware** [comment]
Never mind. Did switch back to mplayer which has a mailing list. I'll switch to  mpv maybe later in the future (for vulkan based acceleration).
