### ISSUE TITLE
How to set image overlay/watermark during runtime?

### ISSUE THREAD

**Issue by acely** [mpv-player/mpv#5559]
I'm using mpv with JsonIPC.

The case is, I want to add overlay(or watermark) to the video while user clicks a button. The overlay is a PNG file, and resizes with the video.

**What I've tried(but not work well)**
1. The "overlay-add" command. This command can indeed add a raw image to the player, but it's used for OSD, so the overlay always keeps it's dimension, it does not resize with the video.
2. The "overlay" video filter. This filter can only be set once the player is launched, and not able to change while playback.

So I wonder if there is a better way to add watermark to the player?
Just imaging these in my mind: `watermark-set "<file>"` and `watermark-remove` and `watermark-reload`

**Comment by wiiaboo** [comment]
Maybe https://ffmpeg.org/ffmpeg-filters.html#overlay-1

**Comment by wm4** [comment]
Video filters can be changed at runtime. Use the `vf` command (there are multiple sub commands which allow you to "edit" the filter list).

**Comment by acely** [comment]
@wiiaboo Doing this via script will also work for me.

**Comment by acely** [comment]
@wm4 I'll be thankful if you can provide some examples.
I'm a little bit confused with the `vf` command😂

**Comment by saml** [comment]
@acely  how did you apply `overlay` filter at start up?

This worked for me:
```
mpv --external-file a.jpg b.mp4 --lavfi-complex "[vid1][vid2]overlay[vo]"
```

But I cannot do the same with `--vf` option:
```
mpv --external-file a.jpg b.mp4 '--vf=@myoverlay:lavfi="[vid1][vid2]overlay[vo]"'
[lavfi] exactly 2 pads required
[user_filter_wrapper] Creating filter 'lavfi' failed.
```

If you used `--vf` option, then it's a matter of using `vf-command` command:
```lua
local mouseX, _ = mp.get_mouse_pos();
mp.commandv('vf-command', 'myoverlay', 'x', mouseX)
```

**Comment by saml** [comment]
@acely you may do the following:

```bash
mpv video.webm '--vf=@foo:lavfi="movie=image.png[img]; [vid1][img]overlay=x=-10000[vo]"'
```

And you can send command to the `lavfi` filter labelled `foo` via lua script or by defining `~/.config/mpv/input.conf`. For simplicity, I used input.conf:
```
mbtn_left vf-command foo x 0
```

When left mouse button is clicked, the overlaid image will show up.  

Explanation: Initially the image is overlaid at x=-10000. So, it's invisible. On mouse click, filter command called `x` is sent to the filter labelled `foo`. The filter is actually a lavfi filter graph. So, `x` command will be sent to all filters in the graph: `movie` and `overlay`. `overlay` filter knows how to handle `x` command and it sets the image's x coordinate to 0, showing the image. 

Things worthy to mention:

1. You cannot send filter command to `--lavfi-complex`. `vf-command` only searches filters in `--vf`: https://github.com/mpv-player/mpv/blob/4a0fcdfbd84d9b93dd9b4cee457b7c1894fbb124/filters/f_output_chain.c#L427 (`p->user_filters` are `--vf`).
1. `--vf` expects single input (one input pin, one output pin: https://github.com/mpv-player/mpv/blob/4a0fcdfbd84d9b93dd9b4cee457b7c1894fbb124/filters/f_lavfi.c#L844 ). You cannot start a filter that takes two inputs, such as `overlay` filter.
    Because of these constraints, I used `movie` filter to specify external file (image.png), instead of `--external-file`. By pushing `overlay` filter after `movie` filter, I could use `--vf` instead of `--lavfi-complex` so that I can send filter commands.
1. Filter commands are sent to `all` filters inside lavfi filter (graph): https://github.com/mpv-player/mpv/blob/4a0fcdfbd84d9b93dd9b4cee457b7c1894fbb124/filters/f_lavfi.c#L777   You cannot send a command to a specific filter inside the graph.

**Comment by acely** [comment]
@saml Thanks so much for providing these valuable informations! I'll have a try and tell the result.

**Comment by slawomir0211** [comment]
@acely and what's result?

**Comment by acely** [comment]
The result is, by setting the `lavfi-complex` property works for me.
The code is:
`sendMsg(String.format("set lavfi-complex \"%s\"", "movie='"+filename+"'[pwm]; [vid1][pwm]overlay[vo]"));`

But the problem is, how to remove this overlay?
`sendMsg("set lavfi-complex \"null\"");` doesn't work,
`sendMsg("set lavfi-complex \"\"");` doesn't work.

ps: I use `sendMsg(String msg)` to send data to mpv via JsonIPC.

**Comment by acely** [comment]
And also, the `vf set|add|toggle|del|clr "filter1=params,filter2,..."` works as well.
The code is:
`sendMsg(String.format("vf set lavfi=\"%s\"", "movie='"+filename+"'[pwm],[vid1][pwm]overlay[vo]"));`

Note that between filters, `,` is used. This is different from `;[space]` in `lavfi-complex`.

And `sendMsg("vf clr \"\"");` can be used to remove the overlay.

**Comment by paulfertser** [comment]
>           You cannot send a command to a specific filter inside the graph.

For those who find this ticket few years later via a search engine, this missing feature was added in https://github.com/mpv-player/mpv/commit/d32f1aac3ffd2e7b766773446c4510a2cad397fb and became part of 0.37.0 release. Now you can use the last optional `vf-command` argument to specify the target, optionally including the id part (e.g. to distinguish between two overlays).
