### ISSUE TITLE
How to play/stream remote Blu-ray disc files ?

### ISSUE THREAD

**Issue by themihai** [mpv-player/mpv#5560]
I have several  Blu-ray disc files stored online (i.e. on Google Drive). Would be possible to stream them  somehow without to download them locally first ? e.g.
`bd://first  --bluray-device=http://example.com/BDMV/index.bdmv  http://example.com/BDMV/PLAYLIST/0001.mpls   http://example.com/BDMV/STREAM/00001.m2ts ...`

**Comment by wiiaboo** [comment]
Unless you mount it as a local filesystem, I'd guess that isn't possible.

**Comment by themihai** [comment]
yeah... that's what I'm doing now but it's not working great. I spawn a webdav sever which wraps the actual http requests/files and then mount the webdav wrapper using a webdav-FUSE driver. The issue is that there are many point of failures and it proves hard to make it work smoothly.

**Comment by themihai** [comment]
Do you think a patch would be acceptable and doable to allow passing all the files along with hints of the actual file paths so that the player can recreate the directory structure in memory and stream the files over http? 
```

bd:// --bluray-device-http= file=http://x.com/file1  hint=BDMV/index.bdmv \
 file=http://x.com/file2 hint=BDMV/STREAM/00001.m2ts  \
 file=http://x.com/file3 hint=/BDMV/PLAYLIST/0001.mpls

```

**Comment by wiiaboo** [comment]
Probably not with that weird syntax.
And that would be a request to libbluray, not mpv.

**Comment by themihai** [comment]
I didn't put much thought into the syntax. I will look into libbluray.

**Comment by themihai** [comment]
@wiiaboo  I've been thinking about this for a while and I came up with the conclusion that the best way to support remote bluray content (or any other format<i.e. DVD>  that needs "folders") would be to add support in the player for a protocol that supports remote "folders" such ftp, smb or webdav. We could have a command/syntax like this
`/mpv bd:// --bluray-device="ftp://127.0.0.1:2010/Users/themihai/my_bd_folder"`

Let me know if you think otherwise and if not where should a such feature be supported? In mpv or libbluray ?

**Comment by wiiaboo** [comment]
Yeah, no, I don't think so. That's what user-space filesystem mounts are good for.
