### ISSUE TITLE
Stat screen showing wrong output levels?

### ISSUE THREAD

**Issue by mHasel** [mpv-player/mpv#5561]
### mpv version and platform
Windows 10, latest windows build by shinchiro

### Reproduction steps
Run file with video-output-levels=full

### Expected behavior
Stat screen to say levels are full instead of limited

### Actual behavior
Stat screen says limited levels, video is actually running at full levels. Can check by input cycle video-output-levels. Not sure if this is an actual bug or it's referring to something different.

### Log file
http://0x0.st/sAbD.txt

### Sample files
![image](https://user-images.githubusercontent.com/34315744/36586716-d87b3734-1893-11e8-9df4-fc950048cb50.png)

**Comment by haasn** [comment]
That information screen is displaying the **file**'s metadata (i.e. input). `--video-output-levels` only affects the **display** (i.e. output).

**Comment by mHasel** [comment]
Ok thanks, it confused me and I couldn't find anything online about it.
