### ISSUE TITLE
Foscam H264 Recording but playback to fast but displays fine without

### ISSUE THREAD

**Issue by francisuk1989** [mpv-player/mpv#5564]
Hey, Dos any know how i can fix the recording playback issue from the mpv when --record-file to a file?

Also when playing in mpv normally without --record-file it plays smoothly like so:

mpv rtsp://username:password@192.168.0.252/11

Playing: rtsp://user:pass@192.168.0.252/11
 (+) Video --vid=1 (h264 1280x720)
 (+) Audio --aid=1 (pcm_alaw 1ch 8000Hz)
File tags:
 Title: 11
AO: [pulse] 8000Hz mono 1ch s16
No video PTS! Making something up. using 25.000000 FPS.
VO: [gpu] 1280x720 yuv420p
Invalid video timestamp: 0.160000 -> 0.160000
AV: 00:00:20 / 00:00:24 (81%) A-V:  0.000 Cache:  4s+289KB

### mpv version and platform

Ubuntu 16.04.3, Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

mpv --version
mpv git-2018-02-01-7f3c710-dirty Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Thu Feb 22 12:49:39 UTC 2018
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.7.100
   libswscale      5.0.101
   libavfilter     7.11.101
   libswresample   3.0.101
ffmpeg version: git-2018-02-01-b1af0e2

If you're not using git master or the latest release, update.

Im uisng mc3man's PPA https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests

### Actual behavior

mpv --record-file BackDoorCamera.mkv rtsp://user:pass@192.168.0.252/11

### Log file

mpv --record-file BackDoorCamera.mkv rtsp://user:pass@192.168.0.252/11
Playing: rtsp://user:pass@192.168.0.252/11
 (+) Video --vid=1 (h264 1280x720)
 (+) Audio --aid=1 (pcm_alaw 1ch 8000Hz)
File tags:
 Title: 11
[recorder] This is an experimental feature. Output files might be broken or not play correctly with various players (including mpv itself).
[recorder] Source stream misses DTS on at least some packets!
[recorder] If the target file format requires DTS, the written
[recorder] file will be invalid.
No video PTS! Making something up. using 25.000000 FPS.
AO: [pulse] 8000Hz mono 1ch s16
VO: [gpu] 1280x720 yuv420p
Invalid video timestamp: 0.161000 -> 0.161000
AV: 00:00:01 / 00:00:06 (28%) A-V:  0.000 Cache:  4s+276KB
[ffmpeg] matroska: Timestamps are unset in a packet for stream 1. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
[ffmpeg] matroska: Encoder did not produce proper pts, making some up.
AV: 00:00:25 / 00:00:30 (84%) A-V:  0.000 Cache:  4s+300K

**Comment by lachs0r** [comment]
Well, your camera does not send timestamps as part of the stream. Only way to 
handle this more or less correctly would be by taking the wallclock time of 
received frames as timestamp source…

Or, if your camera captures at a (known) fixed frame rate, you can pass it to 
mpv using the --fps option (possibly along with --no-correct-pts).

**Comment by kevmitch** [comment]
see also #5419

**Comment by francisuk1989** [comment]
Fair as i know https://github.com/mpv-player/mpv/issues/5419 is Motion JPEG and the source comes from aaxis camera and not H.264 but ill take another look at this this week.

**Comment by Akemi** [comment]
stale issue.
