### ISSUE TITLE
quit-watch-later does not save/restore fullscreen monitor

### ISSUE THREAD

**Issue by xnoreq** [mpv-player/mpv#5567]
At least on Windows, using the latest release or git version (doesn't matter as it's the same in older versions), quit-watch-later saves/restores fullscreen but does not save/restore on which monitor mpv was on in fullscreen.

So if you move mpv to monitor 2, go fullscreen, quit-watch-later, open the file again, mpv now goes into fullscreen on monitor 1.

**Comment by wm4** [comment]
Nope, it doesn't even try to restore the window position.

**Comment by xnoreq** [comment]
So let me make a feature request with an argument for consistency:
either save/restore window state (position, size, minimized/maximized, monitor, fullscreen, ontop .. are the ones I can think right now) or don't save any of them.
