### ISSUE TITLE
How to enable codecview filter for motion vector visualisation?

### ISSUE THREAD

**Issue by Maltragor** [mpv-player/mpv#5569]
### mpv version and platform
Linux Mint 18

mpv git-2018-02-01-7f3c710-dirty Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
built on Thu Feb 22 12:49:39 UTC 2018
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.9.100
   libavformat     58.7.100
   libswscale      5.0.101
   libavfilter     7.11.101
   libswresample   3.0.101
ffmpeg version: git-2018-02-01-b1af0e2

### Question
I'm trying to activate the ffmpeg filter codecview for motion vectors in mpv but it does not work.
The video is played, no errors are displayed but the arrows are missing.

For ffplay the syntax is:
ffplay -flags2 +export_mvs video.mkv -vf codecview=mv=pf+bf+bb

For mpv I tried:
mpv video.mkv --vd-lavc-o=flags2=+export_mvs --vf lavfi=[codecview=mv=pf+bf+bb]

So what I'm doing wrong?

**Comment by Maltragor** [comment]
Thank you, even if I would rather have heard that I only used the wrong parameters ;-)

**Comment by wm4** [comment]
I'll probably implement something to keep the data.
