### ISSUE TITLE
MPV loads multiple artwork images in reverse order

### ISSUE THREAD

**Issue by ErikMinekus** [mpv-player/mpv#5570]
### mpv version and platform
mpv 0.27.2 on macOS High Sierra 10.13.3.

### Reproduction steps
Play an audio file with multiple artwork images.

### Expected behavior
The artwork images should be loaded in the order that they were saved into the file, so that the GUI displays the first image, just like other programs.

### Actual behavior
The GUI displays the last image. The console output lists the last image as the first video track:

```
Playing: /Volumes/Music/Other/ID&T Trance/DJ Tiësto - Lethal Industry.mp3
 (+) Video --vid=1 [P] (mjpeg 600x489)
     Video --vid=2 [P] (mjpeg 600x532)
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
```

### Log file
https://pastebin.com/0gqid5g7

**Comment by wm4** [comment]
Real sample file needed.
