### ISSUE TITLE
Feature Request Rotate when playing

### ISSUE THREAD

**Issue by iamCristYe** [mpv-player/mpv#5574]
Is it possible to add this feature so that I can use a binding key to rotate the video?

**Comment by haasn** [comment]
You should read the manual before opening issues on an issue tracker asking about basic functionality.

**Comment by wm4** [comment]
Video rotation is an option and property that can be changed normally at runtime. I'm using this in input.conf:
```
ctrl+r cycle-values video-rotate 0 90 180 270
```

**Comment by iamCristYe** [comment]
@wm4 Thank you
@haasn Sorry, it's just that I thought I can only use command line at the beginning to set the value.
