### ISSUE TITLE
Waf can't compile mpv git version

### ISSUE THREAD

**Issue by mariojuniorjp** [mpv-player/mpv#5575]
### mpv version and platform

Mpv Git + Crux Linux 3.3 x64

### Reproduction steps

Execute ./waf configure, ./waf build and ./waf install

### Expected behavior

Configure, build and install mpv.

### Actual behavior

Doesn't build.  Waf reports that the project is not configured and asks me to run the "waf configure" command first.

### Log file

https://pastebin.com/JwYFRx15

**Comment by wiiaboo** [comment]
Your log doesn't show any problem.

**Comment by CounterPillow** [comment]
>Checking for FFmpeg/Libav present                                    :no ('libavcodec' not found)

You need ffmpeg git for mpv git

**Comment by mariojuniorjp** [comment]
Both are installed.

**Comment by CounterPillow** [comment]
Evidently not.

**Comment by lachs0r** [comment]
Your system lacks development headers and/or pkg-config files for mpv’s 
dependencies. You need FFmpeg *git master*, not the ancient 3.4 release. You 
also want Lua (either 5.1/5.2 or luajit), or else the OSC, youtube-dl support 
and user scripts won’t work.
