### ISSUE TITLE
mpv not displaying Opus tags when album cover is added

### ISSUE THREAD

**Issue by Ypnose** [mpv-player/mpv#5577]
### mpv version and platform

mpv 0.27.2 on GNU/Linux

### Reproduction steps

Playing an Opus file including **METADATA_BLOCK_PICTURE** comment prevents mpv from displaying other tags like Album, Artist or Title.

Playing a FLAC file with tags and album cover:
![mpv FLAC](https://framapic.org/IXmVrzPQhGrB/XzkkNWkUN8Ea.png)

Playing an Opus file with tags and album cover, encoded with ```opusenc```:
![ mpv Opus cover](https://framapic.org/lZzgjFV6x5Gb/CIehhBGkJ8HF.png)

Playing an Opus file with tags and without album cover, encoded with ```opusenc```:
![mpv Opus no cover](https://framapic.org/2925w7CdZfYq/660UfmOKwNyh.png)

### Expected behavior

mpv should display album cover and other tags (like FLAC files)

### Actual behavior

Tags in Opus files are only displayed if **METADATA_BLOCK_PICTURE** comment is missing.

### Log file

Logs with Opus with album cover:
https://framabin.org/?09b86d440caf49ef#ojvifYADkU1BLu5oeHUiCz16b6H1SWO0g0Gjcvizm8g=

Logs with Opus without album cover:
https://framabin.org/?36162452e1ea57fd#wMyQdDWdqSyOcEttimj639bWMLjq87TyBjoiyHX1g5M=

### Sample files

Tests were done using FLAC file sample from Sony and Opus files encoded with ```opusenc``` (from the same FLAC):
http://helpguide.sony.net/high-res/sample1/v1/en/index.html#musicDlDetail

**Comment by wm4** [comment]
Can I have a real sample file? Otherwise I won't look at this.

**Comment by wm4** [comment]
Above PR should fix it. Also, please use a less awful file hoster next time.

**Comment by Ypnose** [comment]
Thank you! The cover and the tags are now correctly displayed.
