### ISSUE TITLE
Too fast audio playblack DD+ & audio-spdif=eac3

### ISSUE THREAD

**Issue by alfrix** [mpv-player/mpv#5578]
mpv x64 Git (lastest)
windows 10 16299.125 (fall creators update)
iGPU Intel HD4600

[Using this demo](http://www.demo-world.eu/download-2d-trailers/?file=dolby_digital_plus_channel_check_lossless-DWEU.mkv&pic=dolby_digital_plus_channel_check_lossless.jpg) audio playback was too fast, when using audio-spdif=eac3

Log
https://gist.github.com/alfrix/c89c946fbb19f252f04eae877d0ed097

**Comment by wm4** [comment]
> audio playback was too fast

What does this mean?

**Comment by alfrix** [comment]
That audio is faster than it should be, have a listen:

[Audio recording 2018-02-28 11-01-07.zip](https://github.com/mpv-player/mpv/files/1767364/Grabacion.de.audio.2018-02-28.11-01-07.zip)

**Comment by alfrix** [comment]
I should remark that this happens on that file which is 29.97 fps and doesn't in a clip of GoT @ 23.976 (also EAC3/DD+)

and it seems isolated to DD+, other formats like Atmos and TrueHD are not affected

**Comment by wm4** [comment]
Do you have samples for working and broken eac3 files?

**Comment by alfrix** [comment]
https://kodi.wiki/view/Samples
works ok
1.Dolby Digital Plus 5.1 (M2TS @ 1080p/29.970) (thanks wesk05)
 problems if using audio-spdif=eac3
2.Dolby Digital Plus 7.1 Channel Check (MKV @ 1080p/29.970)

**Comment by wm4** [comment]
Likely fix in the PR linked above.
