### ISSUE TITLE
Possible to add a line break to an OSD message/show text?

### ISSUE THREAD

**Issue by TrendaFet** [mpv-player/mpv#5584]
Terribly sorry for the noob question, but is it possible to add a line break? For example, my `osd-playing-msg` is currently set to:

`osd-playing-msg="${playlist-pos-1}/${playlist-count} - ${filename}"`

Which outputs:

`1/1 - Filename.ext`

I want to add a line break so it would instead output:

```
Filename.ext
1/1
```

**Comment by Hrxn** [comment]
From..
`osd-playing-msg="${playlist-pos-1}/${playlist-count} - ${filename}"`

To..
`osd-playing-msg="${playlist-pos-1}/${playlist-count}\n${filename}"

**Comment by TrendaFet** [comment]
Perfect. Thank you very much.
