### ISSUE TITLE
Cycling editions causes mpv to crash

### ISSUE THREAD

**Issue by h633537** [mpv-player/mpv#5587]
### mpv version and platform
mpv 0.28.0-318-g3263f47d33 Linux

### Reproduction steps
Play an mkv file with multiple editions, press shift E to change edition.

### Expected behavior
Edition changes.

### Actual behavior
mpv crashes

```
mpv: ../filters/filter.c:737: mp_filter_create: Assertion `parent' failed.
Aborted (core dumped)
```

### Log file
https://pastebin.com/raw/prhphDad

### Sample files
https://my.mixtape.moe/lufydi.mkv

**Comment by wm4** [comment]
Should also be fixed now in my random PR.
