### ISSUE TITLE
green blocks appear on m4v file playback

### ISSUE THREAD

**Issue by GijsTimmers** [mpv-player/mpv#5588]
### mpv version and platform
```
$ mpv --version
mpv git-2017-10-14-b299a3f (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Tue Oct 17 01:30:07 UTC 2017
ffmpeg library versions:
   libavutil       55.79.100
   libavcodec      57.108.100
   libavformat     57.84.100
   libswscale      4.9.100
   libavfilter     6.108.100
   libswresample   2.10.100
ffmpeg version: git-2017-10-14-0655810
```

### Reproduction steps
just play the sample file with mpv

### Expected behavior
video gets played normally

### Actual behavior
green blocks appear, video unclear

### Log file
https://0x0.st/sm-Z.txt

### Sample files
https://0x0.st/sm-K.m4v

**Comment by wm4** [comment]
Works here. with and without vdpau-copy Probably a hwdec issue (did you try without), i.e. driver bug.

**Comment by GijsTimmers** [comment]
Yes. Fixed it by putting

```
opengl-backend=wayland
```

in `~/.mpv/config`.

Thanks for your help.

**Comment by wm4** [comment]
That solution makes no sense, but if it works for you, nice.

**Comment by GijsTimmers** [comment]
Got it from https://wiki.archlinux.org/index.php/mpv#In_GNOME_Wayland

**Comment by CounterPillow** [comment]
Arch Wiki is garbage, don't trust it. The reason why this "works" is because it fails to use hwdec on Wayland. The real fix is to just remove hwdec from your config file.

**Comment by mc4man** [comment]
If you're using what it appears based on versions then you're simply using wrong options for wayland & vaapi. ( no idea about vdpau/wayland & no real interest in wayland anyhow..
If you have a common dock then open mpv, ck. the desktop actions quicklist by r. clicking on icon, there would be a small text file on vaapi in wayland. 
If not, 1 of the 3 options (vaapi without deco)
`mpv --gpu-context=wayland --hwdec=vaapi  /path/to/file`
or if screen going to sleep on longer files is an issue, until mutter adds support (don't hold breath) you can try prepending command as such
`gnome-session-inhibit mpv --gpu-context=wayland --hwdec=vaapi  /path/to/file`
