### ISSUE TITLE
Can I make spacebar play from start again when it is pausing at the end of playback?

### ISSUE THREAD

**Issue by kybin** [mpv-player/mpv#5597]
When I set loop-playlist it does automatically loop n times.

But I want it to loop only once when I hit spacebar at the end of the playback.

Is there a config option for that?

Quicktime player works in this way, and it was convinient I think.

**Comment by haasn** [comment]
You mean like pausing at the end of playback?

**Comment by kybin** [comment]
Yes, I turned on keep-open.

**Comment by Akemi** [comment]
you can use a script for that.
