### ISSUE TITLE
Improvement of MPV's updater

### ISSUE THREAD

**Issue by hl2guide** [mpv-player/mpv#5598]
Please consider my improved installer/updater.ps1 changes:
- Improved visibility and colours.
- Made the messages more polite
- Cleaned up some messages
- Added clear beginning and end messages

Download Link:
https://www.dropbox.com/s/btljd88a18sf2tg/updater.ps1?dl=0

**Comment by CounterPillow** [comment]
Wrong repository, mpv has no official updater

**Comment by wiiaboo** [comment]
Wrong repository, like said above. https://github.com/shinchiro/mpv-winbuild-cmake
