### ISSUE TITLE
[vo/gpu/vaapi-egl] vaAcquireSurfaceHandle() failed (the requested function is not implemented)

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#5601]
### mpv version and platform
git-2018-03-03-ad3f6d2
ffmpeg version: git-2018-03-03-dd3f1e3
linux (debian/ubuntu
VA-API version: 1.1 (libva 2.1.0)
Mesa 18.0.0-rc4
Hybrid graphics device (nvidia 755m 
### Reproduction steps
use vaapi
### Log file
https://0x0.st/sm14.log

Doesn't appear to cause any issue, just curious if this is some deficiency in libva/mesa in use or whatever..

**Comment by Gusar321** [comment]
That's the new interface for EGL interop. If you're on Intel, it's harmless, mpv will simply fallback to the older interface, vaAcquireBufferHandle(). If you're on AMD, you're screwed :), because the older interface doesn't work there.

You need libva-2.1 for the new interface. Also intel-vaapi-driver-2.1 if you're on Intel, or mesa-18.1 (not yet released) if you're on AMD.

**Comment by laichiaheng** [comment]
@aufkrawall I have installed `mpv-build-git` from AUR, `mesa-git`, and `libva-2.1`, but the vaapi is still not working for my AMD RX460.
```
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Mesa Gallium driver 18.1.0-devel for AMD Radeon (TM) RX 460 Graphics (POLARIS11 / DRM 3.23.0 / 4.15.7-1-ARCH, LLVM 7.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```
