### ISSUE TITLE
[Concept] Add E-GPU Support . 

### ISSUE THREAD

**Issue by Co2333** [mpv-player/mpv#5605]
![a3af075f-049e-4ffc-968e-35aa7f46ace2](https://user-images.githubusercontent.com/25259084/37028257-c4d3864e-216e-11e8-922a-adacf450d852.png)
You know what, it's like ppt when watching something. It's not good.
Maybe add metal/opengl/opencl/cuda support?

**Comment by Akemi** [comment]
> Maybe add metal/opengl/opencl/cuda support?

then i suggest, start working on it.

**Comment by Akemi** [comment]
basically a duplicate of #3653. he got his eGPU to work. so either your setup doesn't work properly or apple broke something. duplicate of #5088 and #5571. [apple](https://forums.developer.apple.com/thread/94837) seems to have broken/changed something. then there is also [this](https://egpu.io/forums/mac-setup/wip-nvidia-egpu-support-for-high-sierra/). don't ignore the issue template.

if the eGPU is not utilised with a proper setup, it's (most likely) not mpv's problem.

**Comment by CounterPillow** [comment]
>Maybe add metal/opengl/opencl/cuda support?

mpv already uses OpenGL, compute shaders (but not on macOS because it's a garbage OS) and cuda as a hwdec. You've put zero research into this.
