### ISSUE TITLE
Can't watch yuv444p 10bit video

### ISSUE THREAD

**Issue by tuanden0** [mpv-player/mpv#5611]
### mpv version and platform

mpv 0.28.0-346-gad3f6d2f97

### Actual behavior

I got the green screen when playing yuv444p 10bit video.
Here's a error img: https://i.imgur.com/MXekQHG.png
The video information:

> Video
> ID                          : 1
> Format                      : AVC
> Format/Info                 : Advanced Video Codec
> Format profile              : High 4:4:4 Predictive@L4.1
> Format settings             : CABAC / 9 Ref Frames
> Format settings, CABAC      : Yes
> Format settings, ReFrames   : 9 frames
> Codec ID                    : avc1
> Codec ID/Info               : Advanced Video Coding
> Duration                    : 24 min 39 s
> Bit rate                    : 430 kb/s
> Maximum bit rate            : 5 894 kb/s
> Width                       : 1 280 pixels
> Height                      : 720 pixels
> Display aspect ratio        : 16:9
> Frame rate mode             : Constant
> Frame rate                  : 23.976 (24000/1001) FPS
> Chroma subsampling          : 4:4:4
> Bit depth                   : 10 bits
> Scan type                   : Progressive
> Bits/(Pixel*Frame)          : 0.019
> Stream size                 : 75.8 MiB (89%)
> Title                       : GOSICK - 01 [720p]
> Encoded date                : UTC 2017-01-22 11:02:55
> Tagged date                 : UTC 2017-01-22 11:02:56

### Log file

https://pastebin.com/b0u5XS4d

**Comment by wiiaboo** [comment]
Try with https://mpv.io/manual/master/#options-vd-lavc-assume-old-x264

**Comment by wiiaboo** [comment]
Since there's no x264 information in that mediainfo paste, it's likely this is the same issue as https://github.com/mpv-player/mpv/issues/4807 and https://github.com/mpv-player/mpv/issues/4559.
