### ISSUE TITLE
Support home key?

### ISSUE THREAD

**Issue by SoniEx2** [mpv-player/mpv#5614]
### mpv version and platform

0.27.2 (this seems to be an actively maintained version still)

### Reproduction steps

Press "Home" key

### Expected behavior

Video would restart

### Actual behavior

`[input] No key binding found for key 'HOME'.`

### Log file

Not applicable

### Sample files

Not applicable

**Comment by sfan5** [comment]
Put `HOME seek 0 absolute-percent` into your input.conf, this is what it's for.

**Comment by SoniEx2** [comment]
shouldn't it be built-in?

**Comment by sfan5** [comment]
Doesn't look like an essential feature to me.

**Comment by kevmitch** [comment]
you could always add it to #973
