### ISSUE TITLE
autoload.lua Loads files incorrectly and behaves erratically

### ISSUE THREAD

**Issue by TrendaFet** [mpv-player/mpv#5618]
### mpv version and platform
mpv 0.28.0 on Windows 10 x64

### Reproduction steps

Have autoload.lua active and place video files in a folder with different names and extensions, for example:
```
Video of - 2 Trees & a swing.avi
Beach day on - Friday 2014.mp4
534235.avi
421353.flv
462114.mp4
Video - File.wmv Day around CITY.LAM.mp4
Finding the #lost tire ~around _city.LAM.flv
G_31_In the box_-_in_the_house.avi
TT_1343566771321.MP4
TT_56524664fAFG4.MP4
Test_file#4313; Phase one_b.MP4
Cave_in_(2012) --Street 43.flv
...etc
```

### Expected behavior
Video files would play one after the other, in order.

### Actual behavior
Random order of playing, and the same files are appended over and over to the playlist if you keep triggering "play next" a few times. So let's say the folder contains 300 video files, with "play next" a few times, it plays in random order or completely restarts order, then the playlist will indicate that it now contains 600 entries, then 900 and so on.

I keep track of playlist by displaying `${playlist-pos-1}/${playlist-count}` in the OSD.

### Log file

https://paste.ubuntu.com/p/SKJfRNCd4G/

### autoload.lua
Currently using the latest stable release of autoload.lua, unmodified.

### Further explanation:
The reason I listed examples of the filenames is because I'm not really sure what's causing the problem, different extensions, specific characters used in filenames, the number of files or a mixture of all.

I've tried to represent some of the weird filenames exactly because there are definitely weirdly named files in there, though the total files is 305 in one of my folders, but it occurs in other folders as well with more files.

**Comment by wiiaboo** [comment]
Maybe a log file with the script actually doing some work, preferably?

**Comment by TrendaFet** [comment]
Ah, my bad.

Here is an update. I have a folder with 64 video files, the name syntax is normal. Example: `Fullmetal Alchemist BrotherHood 01.mkv` goes up to 64. It plays in order, but playlist keeps getting bigger and bigger.

Same behavior as I mentioned earlier, all with the same file extension and normal file names.

### Log file:
https://0x0.st/sm0E.txt

### Preview of behavior: (Screen Capture - MP4 - 1.7 MB)
https://0x0.st/sm0U.mp4

**Comment by TrendaFet** [comment]
Just wanted to add a note, this behavior isn't constant in all folders. By that I mean, in other folders/files it behaves normally.

Not sure if that would be of any help identifying the issue.

**Comment by TrendaFet** [comment]
It is, yes. Since you implied it could be a network mount issue, I copied that folder to my E: drive (HDD), and the problem didn't occur. Everything works well.

I guess this happens over network mounts. (tested on Windows 10 and Debian Stretch)

**Comment by wiiaboo** [comment]
Run [this](http://0x0.st/smGY.txt) version of autoload with log-file as well. I can't reproduce it here.

**Comment by TrendaFet** [comment]
Done. Problem still occurs.

Log file: https://0x0.st/smGg.txt

**Comment by TrendaFet** [comment]
Also, just in case, this is my [mpv.conf](https://0x0.st/smGE.txt).

**Comment by wiiaboo** [comment]
Could you run [this](http://0x0.st/smGl.txt) version? Should be the last one needed.

**Comment by TrendaFet** [comment]
Done.

Log: https://0x0.st/smG0.txt

Problem still occurs.

I'm up for testing as many files as you'd need. If this is a problem not just isolated to me, I'll gladly help.

**Comment by wiiaboo** [comment]
I guess it's because the sort order comes all random from `readdir()`. @rossy any idea if this is a bug in readdir or autoload.lua just needs to sort the files table too?

**Comment by wiiaboo** [comment]
Wait, nevermind, files are already sorted, but for some reason when you change to episode 04 it thinks it's still in position 3.

Run [this](http://0x0.st/smGh.txt) version again, please.

**Comment by TrendaFet** [comment]
Still occurs.

Log: https://0x0.st/smDi.txt

The behavior is really odd. When I start the first file, the playlist only consists of that file (1/1). When I trigger play next the playlist then gets generated correctly in the correct position (2/64).

When I reach the third file (fourth on Linux) the playlist gets bigger, from 64 to 128, 187 and so on.

**Comment by wiiaboo** [comment]
I wonder if it's because you move to the next playlist item before the script finishes. It takes a whole second to run `readdir()` probably because it's a network mount. Could you try waiting like 3 seconds before changing to the next file and see if it still triggers the issue?

**Comment by wiiaboo** [comment]
I'll try to move some things around in order to not be affected by readdir speed.

Could you check if it still happens with [this](http://0x0.st/smDm.txt) version and fast cycling?
And if it still happens, then try with [this one](http://0x0.st/smDa.txt).

**Comment by wiiaboo** [comment]
No need for logfiles, thanks for testing. I went with the first one. Less changes and less global variable usage.

**Comment by thisisshihan** [comment]
Still happens when fast cycling in Linux,
![screenshot from 2018-11-11 22-00-29](https://user-images.githubusercontent.com/38727829/48317061-3c8a8e00-e5fd-11e8-99ce-3b2889dd8212.png)

**Comment by wiiaboo** [comment]
The screenshot doesn't specify what version you're using.

**Comment by thisisshihan** [comment]
> The screenshot doesn't specify what version you're using.

I'm using version 0.29.0-88-317d3ac266 in Windows, in windows also i'm having same issue.

Thanks,

**Comment by thisisshihan** [comment]
Linux version - git-2018-07-22-45beb70
