### ISSUE TITLE
CLI Screenshot Wrong resolution..

### ISSUE THREAD

**Issue by ne0ark** [mpv-player/mpv#5619]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Using following Parameters to take a screenshot:

```args = [ Settings.MpvPath,
			"--no-config",
			"--no-audio",
			"--no-sub",
			"--start", str( int( timeInSeconds ) ),
			"--frames", "1",
			"--screenshot-format", "png",
			"--screenshot-png-compression", "9", # doesn't seem to be working
			"--vf", "scale=0:0", # 0: scaled d_width/d_height
			"--o", outputPngPath,
			self.InputVideoPath ]```

```
MediaInfo
```
Video
ID : 224 (0xE0)
Format : MPEG Video
Format version : Version 2
Format profile : Main@Main
Format settings, BVOP : Yes
Format settings, Matrix : Custom
Format settings, GOP : Variable
Duration : 20mn 47s
Bit rate mode : Variable
Bit rate : 6 071 Kbps
Maximum bit rate : 9 800 Kbps
Width : 720 pixels
Height : 480 pixels
Display aspect ratio : 16:9
Frame rate : 23.976 fps
Standard : NTSC
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Scan order : 2:3 Pulldown
Compression mode : Lossy
Bits/(Pixel*Frame) : 0.733
Time code of first frame : 00:20:31:14
Time code source : Group of pictures header
Stream size : 903 MiB (88%)
```

### Expected behavior

Screenshot resolution should be  853x480.

### Actual behavior

Screenshot resolution is 720x480

Few version back it seems to work properly now it's broke.

### Log file

NA

### Sample files

https://0x0.st/sm05.VOB

**Comment by kevmitch** [comment]
Looks like it's outputting the image scaled to the correct aspect ratio, rather than a pixel-wise representation of the input. Probably an artifact of the new renderer screenshot mechanism.

**Comment by Hrxn** [comment]
Try it without `"--vf", "scale=0:0", # 0: scaled d_width/d_height` maybe?
Why would you want to use this for screenshots in the first place?

**Comment by wm4** [comment]
Definitely a bug, it should take the screenshot using the correct aspect ratio. Simple regression due to the screenshot change.

**Comment by h633537** [comment]
@wm4 
The screenshot is the right resolution now but the image is wrong. The video is stored at 720x428 and displayed at 1024x428.
https://i.imgur.com/ioDxKNZ.jpg
It also happens to any video when you change to a different aspect ratio with shift+A.

**Comment by signedout** [comment]
I have a file whose full mediainfo output shows:

Width                                    : 764
Width                                    : 764 pixels
Height                                   : 576
Height                                   : 576 pixels
Stored_Width                             : 768
Sampled_Width                            : 764
Sampled_Height                           : 576
Pixel aspect ratio                       : 1.003

If I take a screenshot of it during playback using mpv, I get a file with a width of 766. Should be 764...
