### ISSUE TITLE
OSC not works In multi-monitor configurations

### ISSUE THREAD

**Issue by kanabird** [mpv-player/mpv#5620]
### mpv version and platform

HEAD-c15af66  build on 2018/3/10
MacOS 10.13.3
 
### Reproduction steps
In multi-monitor configurations
add option "screen=0" in mpv.conf

### Expected behavior
OSC works

### Actual behavior
OSC not works

**Comment by Akemi** [comment]
it works here as expected. try again by not ignoring crucial parts of the issue template.
