### ISSUE TITLE
fullscreen leads into coil whine/spulenfiepen

### ISSUE THREAD

**Issue by conautica** [mpv-player/mpv#5626]
mpv version: Windows build by lachs0r 2017-12-25 | 64-bit
testsystem: Windows 10 1709 | Amd Vega 56 Driver: 18.3.1

Starting mpv and switch into full screen is enough.
The Vega 56 coil whine/Spulenfiepen.
The lights onboard offer the graphics card is used.
Neutral i hit 1 light... mpv in fullscreen hit 4.

I checked the power consumption and usage with hwinfo.
The card is not used any more than before.

The error occurs without load a file , i have no idea what I could contribute else.

**Comment by wiiaboo** [comment]
We aren't your GPU manufacturer. mpv uses your GPU.

**Comment by haasn** [comment]
For me, coil whine happens when the GPU is loaded to the max (e.g. vsync disabled). But that shouldn't be happening with mpv, unless your vsync is messed up for some reason?

**Comment by dnmTX** [comment]
i can also confirm that there is a coil whine when switching to full screen.Been like this for a while,i was blaming my system more then the player to be honest.
mpv version: Windows build by shinchiro (latest one)
testsystem: Windows 10 1607 LTSB | NVIDIA GTX 1080 Driver: 391.01

**Comment by wm4** [comment]
Fullscreen => more GPU load => your shitty GPU or PSU whines.

**Comment by lachs0r** [comment]
Your GPU of questionable build quality probably always whines very loudly and it’s just that this specific load brings it down into the audible frequency spectrum. If you’re curious, you can record it with a microphone set to a very high sampling rate (96 kHz or higher) while looking at a spectrogram.

**Comment by conautica** [comment]
I test four games and no coil whine. mpv is the only application i run into this issue. because of that i create this report.

**Comment by wm4** [comment]
I really want to know what goes on in your little brain that we're somehow either responsible for your graphic card's physical state, or why you think that we can fix it, instead of the card producer. Do you think we're fucking electricians?
