### ISSUE TITLE
Image glitches with VA-API zero copy if chroma upscaling algorithm is better than bilinear for 4K HDR 60fps video.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#5627]
The information has been updated!
### mpv version and platform
```
mpv 0.28.0-583-gfae9d7744c Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.18.102
   libavcodec      58.19.104
   libavformat     58.17.100
   libswscale      5.2.100
   libavfilter     7.24.100
   libswresample   3.2.100
ffmpeg version: N-91172-gebf85d3190
```
inxi -G:
```
Graphics:  Card-1: AMD Baffin [Radeon RX 460/560D / Pro 450/455/460/560] driver: amdgpu 
           v: kernel 
           Display: x11 server: X.Org 1.20.0 driver: amdgpu unloaded: modesetting 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: AMD Radeon RX 460 Graphics (POLARIS11 / DRM 3.25.0 / 
           4.17.0-mainline LLVM 6.0.0) 
           v: 4.5 Mesa 18.0.4
```

vainfo:
```
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: mesa gallium vaapi
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```
### Reproduction steps
`mpv --no-config --video-sync=display-resample --fs --log-file=vaapi_cscale.txt --gpu-context=x11egl --hwdec=vaapi --cscale=bicubic_fast sample.mkv`
### Expected behavior
No glitch.
### Actual behavior
There are shattered flickering glitch on the top left corner of the image.
### Log file
https://0x0.st/s_mb.txt
### Sample files
Any 4K HDR 60fps video.

**Comment by laichiaheng** [comment]
They all happens to 60fps video, no matter 1080p or 720p.

**Comment by aufkrawall** [comment]
Screenshot? I don't notice any problem.
Try building mesa with llvm 6 if not already the case.

**Comment by hrzhu** [comment]
What do you mean by image glitch. I see no obvious difference between the 3 options you provides and `mpv --no-config`. I've also tried playing the sample with MPC/Lav on Windows. I don't notice any obvious difference from mpv on Linux. Regarding the `flickering` thing, I do feel some flickering (or tearing? I don't know how to describe it) at the start of the video, when the guy running, with both MPC and mpv.

**Comment by laichiaheng** [comment]
@aufkrawall @hrzhu Like these:
cscale=bicubic: https://0x0.st/sa1F.mkv
glsl-shades: https://0x0.st/sa1C.mkv
I installed the mesa-git from the unofficial repo in the archwiki
```
Name            : llvm-svn
Version         : 327535-1
Description     : Low Level Virtual Machine (svn version)
Architecture    : x86_64
URL             : http://llvm.org
Licenses        : custom:University of Illinois
Groups          : mesagit
Provides        : llvm
Depends On      : llvm-libs-svn=327535  perl
Optional Deps   : None
Required By     : clang-svn  lib32-llvm-svn  llvm-ocaml-svn
Optional For    : None
Conflicts With  : llvm
Replaces        : None
Installed Size  : 165.55 MiB
Packager        : Laurent Carlier <lordheavym@gmail.com>
Build Date      : Thu Mar 15 02:22:38 2018
Install Date    : Thu Mar 15 21:43:31 2018
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : SHA-256 Sum
```

**Comment by laichiaheng** [comment]
@aufkrawall with deband, it happens in fullscreen, too.
https://0x0.st/sajK.mkv

**Comment by aufkrawall** [comment]
Have you tried an ewa scaler (for both chroma and luma)? I don't seem to have this issue with jinc + deband + interpolation.

**Comment by haasn** [comment]
Looks like a synchronization issue. I'd suspect the underlying hwdec code.

**Comment by wm4** [comment]
Maybe @fhvwy knows something about this. Some forgotten synchronization call? Driver bug?

**Comment by laichiaheng** [comment]
@aufkrawall If I add `--video-sync=display-resample`, it reduces most of the glitches for the 23.976fps movie, but still have problem with the 1080p60fps video.

**Comment by aufkrawall** [comment]
It seems using interpolation is a good workaround for this, I haven't seen the corruption with it once.
Perhaps use a refreshrate above 60Hz to avoid it with 60fps video (most displays allow 1-2Hz OC) and perhaps also use tscale=linear to stay closer to the original look in motion and waste less GPU resources than with default mitchell.

**Comment by laichiaheng** [comment]
@aufkrawall There are glitches too if I use gpu-hq for the 720p60fps video.

**Comment by aufkrawall** [comment]
It seems we are lucky and this issue already disappeared with Linux 4.17. At least it did for me.

**Comment by laichiaheng** [comment]
@aufkrawall Yes, it is really solved by updating to Linux 4.17, thanks for the information!

**Comment by laichiaheng** [comment]
There is a new problem now, if I disable deband in fullscreen mode, the image of 4K HDR 60fps video is broken and juddering.

**Comment by laichiaheng** [comment]
@aufkrawall It still happens to 4K HDR 60fps if the chroma upscaling algorithm is better than bilinear.

**Comment by aufkrawall** [comment]
With that setting, I could also see it in a 1080p 60fps video.

**Comment by aufkrawall** [comment]
I can't see it anymore with 4.17.12. Can you recheck?

**Comment by aufkrawall** [comment]
I can't see it anywhere anymore with 4.21-wip and RX 580 (not 560 anymore).

**Comment by laichiaheng** [comment]
Glad to hear that, I'll try it if it becomes a RC kernel.

**Comment by Akemi** [comment]
seems like this issue has been fixed.
