### ISSUE TITLE
Build "with ZSH" option is broken

### ISSUE THREAD

**Issue by aitte2** [mpv-player/mpv#5629]
This issue exists in `git-master` as of today. I don't think it matters that I am on OS 10.12. It seems to be a generic issue about a lack of parameters being sent to zsh.pl.

Steps to reproduce:

```
git clone https://github.com/mpv-player/mpv.git
cd mpv
./bootstrap.py
./waf configure --enable-zsh-comp
./waf
./waf install
```

Result:
```
[223/223] Compiling TOOLS/zsh.pl
Couldn't find any options at mpv/TOOLS/zsh.pl line 30.

Waf: Leaving directory `mpv/build'
Build failed
 -> task in '_mpv' failed with exit status 255 (run with -v to display more information)
```

By looking at zsh.pl https://github.com/mpv-player/mpv/blob/master/TOOLS/zsh.pl#L30 you can see that the error comes from calling that script without any arguments.

I don't understand how that's even possible. I searched the code for "zsh.pl" and everywhere it's being called it seems to be given parameters. The main location seems to be here:

https://github.com/mpv-player/mpv/blob/12b90e744dd220a3386a8977138fba28708c8d21/waftools/generators/sources.py#L8-L10

https://github.com/mpv-player/mpv/blob/12b90e744dd220a3386a8977138fba28708c8d21/waftools/generators/sources.py#L49-L55

I think this build option worked 1-2 months ago... so it may have broken recently, but I looked at the history of zsh.pl and the generator and can't see any changes that would affect this... Hopefully someone is smart enough to figure it out. ;)

**Comment by qmega** [comment]
It's not about calling the script without arguments. It's saying it can't find any options in the output of `mpv --list-options`. Given your other issue, I think it's just because your mpv is crashing. Once you've fixed that, I bet this will work too. If by some chance it doesn't, please post the output of `./build/mpv --list-options`.

**Comment by aitte2** [comment]
Ohhh. So zsh.pl tries to run the mpv binary to list all options? Okay then it's definitely related to my other issue, since the mpv binary can't start at all (not even console text output).

Moving this to #5631.
