### ISSUE TITLE
Segfault when playing audio file with jpeg image with VDPAU filters enabled

### ISSUE THREAD

**Issue by LinAGKar** [mpv-player/mpv#5637]
### mpv version and platform

0.27.2-22.1 from openSUSE Tumbleweed main repo

### Reproduction steps

Play an audio file with an embedded JPEG image, tested with `mpv --no-config --vf=vdpaupp=deint-mode=temporal-spatial "https://aphid.fireside.fm/d/1437767933/a30d94d6-67ee-4b58-8802-acf467c78c63/12b31b96-4657-4f34-b442-968872bac224.mp3"`.

### Expected behavior

The file is played normally.

### Actual behavior

Segmentation error.

### Log file

Log file: https://0x0.st/saqM.txt
Backtrace: https://0x0.st/saq1.txt

**Comment by wm4** [comment]
Can't reproduce a crash in git, but it was broken anyway. #5635 includes a fix.
