### ISSUE TITLE
--ao overrides --audio-device

### ISSUE THREAD

**Issue by archenemies** [mpv-player/mpv#5640]
### mpv version and platform

        $ mpv --version
        mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
         built on Wed Feb 14 14:00:12 CET 2018
        ffmpeg library versions:
           libavutil       55.78.100
           libavcodec      57.107.100
           libavformat     57.83.100
           libswscale      4.8.100
           libavfilter     6.107.100
           libswresample   2.9.100
        ffmpeg version: 3.4.2

        $ uname -a
        Linux thutmose 4.14.22-1-lts #1 SMP Sun Feb 25 15:13:49 CET 2018 x86_64 GNU/Linux

### Reproduction steps

    $ mpv --no-config  --ao=pulse --audio-device=alsa t.mp3
    Playing: t.mp3
    (+) Video --vid=1 [P] (mjpeg 500x500)
    (+) Audio --aid=1 (mp3 2ch 44100Hz)
    ...
    AO: [pulse] 44100Hz stereo 2ch s16
    AV: 00:00:00 / 00:03:14 (0%)

    Exiting... (Quit)

The man page says "User-specific options override system-wide options and options given on the command line override either." However, if the config file specifies `ao=pulse` then any --audio-device command line argument seems to be ignored. That's a bug.

I don't think that the man page ever says whether later options should override earlier ones (if it doesn't, that would be a documentation bug). However, I have checked that if I specify two --audio-device options then the second one overrides the first.

I would expect that --audio-device and --ao should interact in the same way.

If --ao is intentionally overriding --audio-device, then please document this and explain why it is useful.

#5249 reports the same bug and I'm not quite sure why it was closed. Surely if the user's `--audio-device` syntax was incorrect, then correct behavior would be to report a syntax error or bad argument. When mpv ignores command line options without issuing an error or warning, it becomes very difficult to debug problems that I encounter with it.

**Comment by wm4** [comment]
> The man page says "User-specific options override system-wide options and options given on the command line override either." 

That counts only per-option. --ao and --audio-device are not the same option. --ao always takes priority.

**Comment by archenemies** [comment]
Can we come up with a sensible warning? Why not warn or error every time --ao and --audio-device are both specified in the same command line?

**Comment by archenemies** [comment]
Thanks for the man page patch. I am lacking closure a bit because there are still several unanswered questions.

* If --ao is intentionally overriding --audio-device, then please document this and *explain why it is useful*.

* ... Surely if the user's --audio-device syntax was incorrect, then *correct behavior would be to report a syntax error or bad argument*.

* Why not warn or error every time --ao and --audio-device are both specified in the same command line?
