### ISSUE TITLE
Subtitle rendering artifact when using --gpu-context=winvk

### ISSUE THREAD

**Issue by boodies** [mpv-player/mpv#5641]
### mpv version and platform

mpv-x86_64-20180310-git-c15af66 shinchiro Windows build

### Reproduction steps

Play some .mkv file with subtitles attached to it with `--gpu-context=winvk` option

### Expected behavior

Subtitles displayed correctly

### Actual behavior

There are some rendering artifact in the end of subtitles line. Because `ctrl+S` didn't work according to #4972, I used Windows full desktop screenshot to show the issue.

Windows screenshot: https://files.catbox.moe/k78t1r.png
mpv `s` key screenshot: https://files.catbox.moe/wc099i.jpg

### Log file

https://files.catbox.moe/39jn8u.txt

### Sample files

https://files.catbox.moe/qfbem1.mkv

**Comment by wiiaboo** [comment]
Can't reproduce it here. Does it also happen without that option?

**Comment by boodies** [comment]
No, it's not happen without `--gpu-context=winvk`. It also not happen when using `--gpu-context=d3d11`.

It is persist throughout the duration of the subtitle. It happen often when subtitle ends with Non-alphanumeric characters such as `.`, `!`, or `?`

I suspect it was a driver issue, especially AMD.

**Comment by shinchiro** [comment]
Or might be text encoding issue with your computer since I saw it misprinted `Copyright © 2000-2018` as `Copyright Â© 2000-2018` in the logfile

**Comment by wm4** [comment]
@shinchiro I doubt that, because the text rendering code is exactly the same as for other backends. The only difference is texture allocation and upload etc. (rendering the bitmaps that were rasterized by the common code).

CC @haasn

**Comment by boodies** [comment]
After further testing, the issue seems to happen to OSD in general. It shows on OSD message like this one:

https://files.catbox.moe/93jdcs.png

It actually happen too in pseudo-gui mode when there aren't any file loaded like this:

https://files.catbox.moe/zvmd05.png

Notice there are some artifact left behind on the very end of the line, I assumed it is from "yes" that was drawn before.

**Comment by wm4** [comment]
Of course, it's all the same code.

Can you confirm that this never happens in GL? Try playing with changing the window size etc. (while OSD is visible). That forces the OSD texture to reallocate, which may or may not have to do with it.

**Comment by boodies** [comment]
mpv actually crashed when I try resizing window when OSD visible.
Logfile when crashing: https://files.catbox.moe/od6a41.txt

**Comment by haasn** [comment]
A backtrace on the crash would be more helpful

For the OSD, it's possible that we might be doing some operation out-of-bounds? But I can't think of any reason why it should be the case for the OSD in particular, since that's a trivial fragment shader.

**Comment by wm4** [comment]
Backtraces are rather hard in Windows. CC @jeeb @avih @rossy for secret mingw debugging dark magic.

**Comment by wm4** [comment]
Also one possibility is that uploading a small partial rectangle somehow goes wrong. That is messy code that is not used for anything else.

**Comment by shinchiro** [comment]
@boodies If that crash happen with my build, you can download matching debug-symbol for the archive [here](https://sourceforge.net/projects/mpv-player-windows/files/debug-symbol/) and use drmingw to capture the stack trace (tutorial also there)

**Comment by haasn** [comment]
Actually now that I think about it, I remember there being some obscured code that had to do with OSD texture uploading. I thought that one was fixed already, but now I don't remember. iirc, the bug was already present on the higher level (i.e. outside of the RA, the texture it was trying to upload was already too small or something). I forgot why the other RAs were unaffected, but I think the normal symptom was that vulkan would either assert or segfault. May be unrelated.

**Comment by haasn** [comment]
> some obscured code

some obscure bug*

**Comment by boodies** [comment]
https://files.catbox.moe/rscty1.txt

Is that enough? Sorry I'm not accustomed to debugging

**Comment by shinchiro** [comment]
That looks weird.

Could you try with mpv-x86_64-20180120-git-dba143d.7z archive. It might be possible binutils 2.30 screw up debug symbols

**Comment by boodies** [comment]
Here it is with **mpv-x86_64-20180120-git-dba143d.7z**

https://files.catbox.moe/qa9e3k.txt

**Comment by shinchiro** [comment]
Well, probably this is amd driver bug after all. There is new driver for your amd card this month. Try that

**Comment by rossy** [comment]
Yeah, it looks like it's crashing in a driver thread, so it's hard to tell what's going on from the stacktrace.

**Comment by boodies** [comment]
I can't update to newer AMD driver in the near future because newer driver tends to break my device. Anyway it's seems the issue is not from mpv so I think I can close this. Sorry for the trouble.

**Comment by boodies** [comment]
So I have updated the AMD driver.

```
[vo/gpu/vulkan] Chose device:
[vo/gpu/vulkan]     Device Name: AMD Radeon (TM) R5 M330
[vo/gpu/vulkan]     Device ID: 1002:6660
[vo/gpu/vulkan]     Driver version: 8388628
[vo/gpu/vulkan]     API version: 1.1.70
```

Just a heads up that with that version of Vulkan, this issue is not happening.
