### ISSUE TITLE
Am I Safe????

### ISSUE THREAD

**Issue by baraa272** [mpv-player/mpv#5646]
### mpv version and platform

latest release 0.28.2

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

The question Is Am i Safe For 10 bit ???

my settings 

hwdec=d3d11va-copy 
gpu-api=opengl 
i have read before that using gpu-api=d3d11 compined with gpu-context=win can lead hevc 10 bit files to be rounded to 8 bit 
but the problem my system cant handle both gpu-api=d3d11 gpu-context=d3d11
so im using hwdec=d3d11va-copy with gpu-api=opengl without specifying gpu-context 
am i safe now ???

**Comment by wiiaboo** [comment]
No. If you want to be "safe" you shouldn't use hwdec ever. Only use hwdec if your CPU can't keep up with real-time decoding.
