### ISSUE TITLE
[Feature Request] stop video playback relative to end of video time command line option

### ISSUE THREAD

**Issue by kevbroch** [mpv-player/mpv#5647]
Just as there is a `--start=<relative time>`
It would be nice to have `--end-relative-end=<relative time>`
which would stop the video based on a relative time from the end of the video.

This would be useful to remove a standard outro on a video (just as --start is for intros) but where the length of the video is variable.

**Comment by wiiaboo** [comment]
`--end` also supports relative time. What do you mean?

**Comment by kevbroch** [comment]
https://mpv.io/manual/master/#options-end

```
--end=<time>
Stop at given absolute time. Use --length if the time should be relative to --start. See --start for valid option values and examples.
```

Not sure what you mean?

So if I had many video, and I wanted each of them to stop 10s from the end, I do not believe that is possible.

This `mpv --end=10 *.mp4` would stop each video after 10s of play from the start (not the end).  `--length` doesn't help either.

**Comment by wiiaboo** [comment]
> So if I had many video, and I wanted each of them to stop 10s from the end, I do not believe that is possible.
`--end=-10`?

**Comment by kevbroch** [comment]
Thanks for clarification and update to doc: https://github.com/mpv-player/mpv/commit/38e5b141c69526808ed23807cc1012ea0c7630c0
