### ISSUE TITLE
How to incorporate options per file from c # to libmpv

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5648]
### mpv 0.28

good morning, reading the manual mpv, I saw that you can add options per file through libmpv adding the special per-file markers - {and -}
as for example: mpv --a file1.mkv --b - \ {--c file2.mkv --d file3.mkv --e - \} file4.mkv --f
How can I incorporate this from c #?
Since when entering the {the solution generates an error.

**Comment by wiiaboo** [comment]
Use [`file-local-options`](https://mpv.io/manual/master/#command-interface-file-local-options/%3Cname%3E)? Also, the option is `--{`. The escaping is meant for console use.

**Comment by EzeKees** [comment]
thank you very much, of course, now I try that and I'll mention it here, if someone else needs it, thank you very much for your response!

**Comment by wm4** [comment]
Actually just pass the options as additional `loadfile` argument, see manpage.
