### ISSUE TITLE
Weird colors for certain JPEGs

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#5653]
### mpv version and platform

```
mpv 0.28.0-398-gfbcf2bf207 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Mar 18 10:53:18 CET 2018
ffmpeg library versions:
   libavutil       56.10.100
   libavcodec      58.14.100
   libavformat     58.10.100
   libswscale      5.0.102
   libavfilter     7.13.100
   libswresample   3.0.101
ffmpeg version: N-90348-g08e0f45cc8

Linux tornado 4.15.2-2-ARCH #1 SMP PREEMPT Thu Feb 8 18:54:52 UTC 2018 x86_64 GNU/Linux
```

### Reproduction steps

Open the sample file: `mpv --no-config https://0x0.st/sa6n.jpg`

### Expected behavior

I should see a normal sunset

![20180318_111840_jlj](https://user-images.githubusercontent.com/1045476/37564831-204fe99e-2a9e-11e8-9cd9-d5ae2fe66a92.png)

### Actual behavior

I am seeing unsettling black sun

![20180318_111818_ucl](https://user-images.githubusercontent.com/1045476/37564834-2496df62-2a9e-11e8-9ba1-c4d437f3057f.png)

<small>(These are roughly cropped screenshots of a large panorama, which is why the viewports are not aligned.)</small>

### Log file

https://0x0.st/sa6d.txt

### Sample files

https://0x0.st/sa6n.jpg

**Comment by wm4** [comment]
I think your drivers refuse to create a texture this big, which leaves only the chroma planes visible. Works for me though.

**Comment by rr-** [comment]
Seems that's the case, `-vo=x11` renders the image properly.
