### ISSUE TITLE
Render API: add a dummy render function or similar

### ISSUE THREAD

**Issue by Akemi** [mpv-player/mpv#5655]
libmpv and the render API expects a corresponding `mpv_render_context_render` call to every update callback to work properly. otherwise it will lead to reported dropped frames and a [wait](https://github.com/mpv-player/mpv/blob/7ee01860d9c16f2d9d9ea3f5ae5c2a699c7cf1f9/video/out/vo_libmpv.c#L366) of up to 0.2 seconds. though there are situations where actually rendering isn't needed and would just waste resources or isn't possible at that moment. obviously mpv can't detect such cases and only the libmpv user can. so it would be helpful to have a way to signal that to mpv. such cases are mostly off-screen situation like a minimised window or a different space/virtual desktop that isn't active on any display.

just not calling `mpv_render_context_render` will cause problems with for example `--video-sync=display-resample` and will just deactivate it after a short time, so this is not an option. so a way to tell mpv that the update callback was received but it doesn't need to render anything would be helpful, eg a dummy render function or similar. that way mpv wouldn't need to wait on anything, resources won't be wasted in situations an update isn't actually needed (no need to draw when not visible) and display-resample wouldn't be deactivated in situations `mpv_render_context_render` can't be called.

a use case for this would be cocoa-cb. atm i [force off-screen drawing](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa-cb/video_layer.swift#L222) because the CAOpenGLLayer and it's mechanism refuses to call its corresponding draw function (dropping the `mpv_render_context_render` call) when it thinks it's not needed (minimised, different space, video window not visible, etc). which isn't a bad thing imo but it just won't play well with libmpv atm. it's easy for me to detect this, eg a `display()` call doesn't have a corresponding  `draw(inCGLContext...)`.

**Comment by haasn** [comment]
This may be related to #5649, and reinforces my idea of making the DR generation part of the actual render function - the user will then be able to use the dummy render function (or set the dummy flag or whatever) on vsyncs where there's no new frame to render.

**Comment by haasn** [comment]
(Alternatively, it also reinforces the idea of providing an “update” function that gets called every vsync - then we could move the display sync timestamp update from the render() call to the update() call.)

**Comment by wm4** [comment]
Yeah, I think it'd be good if the user gets exact control over frame scheduling:
- whether there is a new frame
- when the new frame is supposed to be displayed
- decoupling rendering and vsync feedback
- skipping frames or redrawing

**Comment by Akemi** [comment]
added with https://github.com/mpv-player/mpv/commit/ce4d227986cf394a80fc687290bc732bbd8dbf22#diff-43ca065bbb561dc995393b06c73dc3a8
