### ISSUE TITLE
Option to ignore nested playlists

### ISSUE THREAD

**Issue by ae-g-i-s** [mpv-player/mpv#5656]
Version: mpv 0.27.2 (but probably applies to all)

I have a large collection of music folders on a network drive, making regular players unusable for performance reasons. Currently, I'm using a few scripts that select one or more of these folders, create a plaintext playlist for mpv and then start it using `mpv --playlist=<path>`.

About half of these folders contain m3u playlists, which have the annoying effect of being picked up by `mpv` as part of the playlist and causing it to play all songs in this folder twice - once because the "master" playlist contains this folder, and a second time because the m3u points to the individual files.

I've searched the docs for a feature that would allow me to exclude certain file types or, more specific to my issue, cause mpv to ignore nested playlists, but haven't found anything. Is there such an option? If not, it'd be great to have. 

The only workaround I can think of is specifying every individual file in my plaintext playlist, which makes it about 10x larger and might lead to a different order of tracks being played.

**Comment by wiiaboo** [comment]
Use the same script(s) to ignore m3u?

**Comment by ae-g-i-s** [comment]
The playlists contain folders, not individual files.

**Comment by wiiaboo** [comment]
Exactly, instead of adding another option why not make whichever scripts you're already using glob through those directories you're adding and ignore m3u/cues there?

**Comment by ae-g-i-s** [comment]
It's a usable workaround, but being able to exclude files when playing a folder would still be great.

**Comment by guidocella** [comment]
You can exclude `m3u`s with a script that excludes files by extension like https://github.com/mpv-player/mpv/issues/2595#issuecomment-1454746798

**Comment by Dudemanguy** [comment]
>Actually was fixed by https://github.com/mpv-player/mpv/commit/f266eadf1eae920d645477b9658c6847aca47ff5. You can use --directory-mode=ignore now and it should work.

This was wrong actually but maybe the option could include anything that gets interpreted as playlist (currently not the case).

**Comment by na-na-hi** [comment]
This was fixed by #15551. `--directory-filter-types` supports playlist type.
