### ISSUE TITLE
Load multiple MPV instances with SVP!

### ISSUE THREAD

**Issue by Bananamax** [mpv-player/mpv#5657]
Greetings ladies and gentlemen.

What I would like to do is run more than 1 instance of MPV using SVP. SVP uses the mpv pipe for the specific mpv.exe (apparently ^^).
Now when I start MPV and use SVP it works perfectly. When I start MPV for a second time the second movie I play isnt recognized by SVP only the first one.
Months ago I somehow got it to work by creating a second mpv folder with a renamed mpv2.exe and another mpvpipe-name and added it to SVP and so on....and it worked. I could open 2 different mpv.exe files and load 2 different moviefiles and had 2 working MPV-SVP instances.

For your info SVP is a frame interpolation software to smooth things out :)

I would appreciate some help on this on how to get it to work properly.

God bless you all
Bananamax

**Comment by wiiaboo** [comment]
Use a differently named socket? If a socket already exists and mpv's using, a second mpv can't also use it.

**Comment by wm4** [comment]
Yeah, SVP or whatever scripts involved choose the socket name, not mpv.

**Comment by Bananamax** [comment]
I have the mpv64 folder and added it to python (necessary for SVP). I created a second folder called mpv642 and added it to python as well. In mpv64 there is a mpv.exe and a mpv.conf where I have this: input-ipc-server=mpvpipe
In the mpv642 folder I renamed the exe to mpv2.exe and in the mpv2.conf file I have this: input-ipc-server=mpvpipe2
Added mpvpipe and mpvpipe2 to SVP and also the location of both the exe files. However its not working (anymore?!). Cant remember what I have done differently months ago. But after an update it stopped working if I remember correctly.

**Comment by wiiaboo** [comment]
Renaming the executable doesn't do anything except waste space.

**Comment by Bananamax** [comment]
Yeah well ok but doesnt matter anyway SVP acknowledges the first mpv instance and the second one not even though I got 2 folders with 2 conf files and 2 different ipc-server names.

**Comment by Argon-** [comment]
I guess the problem here is you can only specify one `input-ipc-server=mpvpipe`? Maybe a pattern like used for vo=image (increasing a number) could help?

**Comment by Bananamax** [comment]
How do you mean exactly? As far as I know I can add more than one with "," in between. That also worked when adding mpc-qt besides mpv.

**Comment by wm4** [comment]
This is not the bug tracker for SVP. Go to the SVP bug tracker.

**Comment by Argon-** [comment]
Ah, I didn't know that comma works with `input-ipc-server` and assumed the problem is mpv can't specify multiple socket names for different instances. But of course, when this is possible it's a problem of SVP not checking for multiple socket names.

**Comment by wm4** [comment]
Well it doesn't.

**Comment by Bananamax** [comment]
It somehow worked months ago. If it wasnt "," well .....I tried it all ";" ":" "/" "&" "&&" nothing works

**Comment by wiiaboo** [comment]
Well, unlike SVP, mpv is open source and it never accepted multiple paths for the socket, looking at the commit log.

**Comment by Bananamax** [comment]
I need the good stuff to work some things seem too normal not to work. 2 instances doesnt sound difficult it has to work somehow.

**Comment by wiiaboo** [comment]
Go ask it to SVP then. They're launching mpv so they should be using different names for different instances.

**Comment by Bananamax** [comment]
Well of course I am working all angles but so far no mas! Very unfortunate

**Comment by wjax** [comment]
Hi there.

I know this is a closed issue but I have tumbled with it while having a similar problem.
I need to use the same socket from another application (a recorder). However MPV always opens UDP sockets in exclusive use. Why is that?
It should be possible to choose to reuse a listener udp socket. It is just a flag in the socket.

Can someone please guide me to the source line? I really do not find it.

Many thanks

**Comment by Bananamax** [comment]
So apparently it seems to work now with this:
https://github.com/wis/mpvSockets
But I have no idea how to get it to work. Put the lua in the scripts folder ofc but it doesnt work. Tried to edit the conf but it doesnt work.
