### ISSUE TITLE
vaapi on radeon: deinterlacing not working

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#5658]
### mpv version and platform
mpv 0.28.0-400-ga04ac8204f 
mesa-git  100961.e1b2e5667c-1
libva 2.1

### Reproduction steps
Play an interlaced video with vaapi and enable deinterlacing.

### Expected behavior
It should deinterlace (vdpau works).

### Actual behavior
It fails with
> [vavpp] vaRenderPicture() failed (invalid VASurfaceID)
> [vavpp] failed to output frame
> Disabling filter userdeint because it has failed.

### Log file
https://pastebin.com/u5QUTtii

### Sample files
Any interlaced video.

**Comment by laichiaheng** [comment]
It works for me if the `vo=vaapi`, but poor quality.

**Comment by aufkrawall** [comment]
Yeah, it's probably not using vpp.

**Comment by aufkrawall** [comment]
Not implemented in driver:
https://bugs.freedesktop.org/show_bug.cgi?id=105145
-> closed
