### ISSUE TITLE
Adding youtube video liking support

### ISSUE THREAD

**Issue by JuanPotato** [mpv-player/mpv#5659]
```mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed Feb 14 14:00:12 CET 2018
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.2
```

Hey all, I was wondering if it would be possible to implement the liking of youtube videos. And I'm not sure if this would be more appropriate in youtube-dl or here since I'm not sure how much is handled where. I currently listen to a lot of music on youtube through mpv and would like to like some videos. It seems [youtube's api](https://developers.google.com/youtube/v3/docs/videos/rate) allows for this, but I'm not sure where I would add this feature or see if it is possible.

**Comment by wiiaboo** [comment]
Wrong place -> https://github.com/rg3/youtube-dl

**Comment by wiiaboo** [comment]
Also, mpv can't directly make requests to the network with lua/javascript, so it wouldn't be possible in mpv even with youtube-dl giving us the URL to do it.

Find some CLI app that uses youtube api and do it through there.

**Comment by JuanPotato** [comment]
It doesn't have to be lua or js. It's just a bit of http requests so in reality any language with an http library should be fine. Anyway, I'll take this over to youtube-dl. thanks!
