### ISSUE TITLE
Integrate mvtools to enable Motion interpolation

### ISSUE THREAD

**Issue by nilsboy** [mpv-player/mpv#566]
It would be cool to have a more fluid picture like TV-sets have nowadays.
The mvtools implement that:
http://avisynth.org.ru/mvtools/mvtools2.html

See also: the svp project which uses mvtools:
http://www.svp-team.com/wiki/Main_Page

**Comment by haasn** [comment]
Small update, for the record: The issues above have mostly been resolved due to some vf_vapoursynth changes, and addition of a (less computationally expensive) block-based interpolation mode to the mvtools vapoursynth.

Here's the script I use these days, which works pretty fine at realtime:
```
import vapoursynth as vs
core = vs.get_core()

clip = video_in

# Skip interpolation for >1080p or 60 Hz content due to performance
if not (clip.width > 1920 or clip.height > 1080 or container_fps > 59):
    # Needed because clip FPS is missing
    clip = core.std.AssumeFPS(clip, fpsnum = int(container_fps * 1e8), fpsden = int(1e8))
    sup  = core.mv.Super(clip, pel=2, hpad=16, vpad=16)
    bvec = core.mv.Analyse(sup, blksize=16, isb=True , chroma=True, search=3, searchparam=1)
    fvec = core.mv.Analyse(sup, blksize=16, isb=False, chroma=True, search=3, searchparam=1)
    clip = core.mv.BlockFPS(clip, sup, bvec, fvec, num=60000, den=1001, mode=3, thscd2=12)

clip.set_output()
```

**Comment by Argon-** [comment]
Now that the displays Hz is reliably detected for Linux and OSX, might it be useful to pass this value to the vs filter like `container_fps`? This way one could get rid of the hard coded 60000/1001 and get more "portable" mpv vs scripts.

**Comment by excalibur1234** [comment]
@haasn : your vapoursynth script is not working anymore with the latest git version of mpv. can you update it?

version 0.7.3 of mpv worked perfectly with it!

**Comment by haasn** [comment]
Still working fine for me. Can you point me to the commit that breaks it on your machine?

**Comment by excalibur1234** [comment]
i have just rebuild from the latest git packages. still the same error:

i tried to start the movie "matrix reloaded". i do not see any video, but i can hear the sound. the movie works fine when i disable vapoursynth.

```
$ mpv Matrix\ Reloaded\ \(2003,\ 1920x800,\ de-ac3,\ en-ac3,\ x264.iNTERNAL-DARM\).mkv 
Playing: Matrix Reloaded (2003, 1920x800, de-ac3, en-ac3, x264.iNTERNAL-DARM).mkv
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 --alang=ger (*) (ac3)
     Audio --aid=2 --alang=eng (ac3)
Opening video filter: [vapoursynth file=~/.config/mpv/vapoursynth]
Trying to use hardware decoding.
AO: [alsa] 48000Hz stereo 2ch float
Using conversion filter.
Image formats incompatible or invalid.
Video filter chain:                                                                                                           
 [vd] 1920x800 vdpau Autoselect/Autoselect CL=mpeg2/4/h264                                                                    
 [in] 1920x800 vdpau BT.709 (HD)/TV CL=mpeg2/4/h264                                                                           
 [scale] ??? [a]   <---                                                                                                       
 [vapoursynth] ???                                                                                                            
 [out] ???                                                                                                                    
Cannot initialize video filters.                                                                                              
Error using hardware decoding, falling back to software decoding.                                                             
[vapoursynth] Script evaluation failed:                                                                                       
[vapoursynth] Python exception: No attribute with the name mv exists. Did you mistype a plugin namespace?                     
[vapoursynth] Traceback (most recent call last):                                                                              
[vapoursynth]   File "vapoursynth.pyx", line 1488, in vapoursynth.vpy_evaluateScript (src/cython/vapoursynth.c:25136)         
[vapoursynth]   File "/home/ex/.config/mpv/vapoursynth", line 10, in <module>                                                 
[vapoursynth]     sup  = core.mv.Super(clip, pel=2, hpad=16, vpad=16)                                                         
[vapoursynth]   File "vapoursynth.pyx", line 1109, in vapoursynth.Core.__getattr__ (src/cython/vapoursynth.c:19250)           
[vapoursynth] AttributeError: No attribute with the name mv exists. Did you mistype a plugin namespace?                       
[vapoursynth]                                                                                                                 
Video filter chain:                                                                                                           
 [vd] 1920x800 yuv420p Autoselect/Autoselect CL=mpeg2/4/h264                                                                  
 [in] 1920x800 yuv420p BT.709 (HD)/TV CL=mpeg2/4/h264                                                                         
 [vapoursynth] 1920x800 yuv420p BT.709 (HD)/TV CL=mpeg2/4/h264   <---                                                         
 [out] ???                                                                                                                    
Cannot initialize video filters.                                                                                              
Could not initialize video chain.                                                                                             
Video: no video                                                                                                               
A: 00:00:57 / 02:18:15 (0%)
```


when i have to guess which commit caused this, i would say:
https://github.com/mpv-player/mpv/commit/349067a6ab2d03024b3e984e80314f303dd14432

**Comment by Argon-** [comment]
I'm pretty sure this commit doesn't cause your problem as it just provides a new variable like `container_fps`.
VS works for me, using current vapoursynth HEAD and MVTools HEAD.
Have you updated vapoursynth (at least R26) or MVTools? I'd recommend updating both. There were a lot of changed during the last few days/weeks and some even broke compatibility between certain versions of them.

Regarding your error message: well, seems like VS doesn't know about MVTools. I assume haasn is using VS's plugin autoload; I for example don't, therefore loading the library with core.std.LoadPlugin('<path>')`. Unless the library isn't loaded, `core.mv` does not exist.
Maybe something in this regard changed for you?

**Comment by haasn** [comment]
Argon is right, I'm using the plugin autoload (via having a symlink to mvtools in /usr/lib/vapoursynth).

**Comment by nilsboy** [comment]
Thank you all so much for implementing this!

The picture looks very smooth and calm with this - especially - to my surprise - scenes with litte to medium motion.
Very fast motion don't seem to profit that much - I guess movement that's faster than the displays refresh rate is the problem.

I'm currently using a pretty slow low end celeron quad core so I hade to shrink the input to 1000 pixels horizontally with: --vf-add scale=1000:-2::::1: before adding vapoursynth.
