### ISSUE TITLE
JSON-IPC : observe_property time-pos udpates too often

### ISSUE THREAD

**Issue by niol** [mpv-player/mpv#5661]
### mpv version and platform

mpv 0.27 on Debian GNU/Linux

### Reproduction steps

When I send ```{ "command": ["observe_property", "time-pos"] }```, I get many ```property-change``` events per second. For my simple webapp controlling mpv, this is too much and stresses the IPC interface for no reason.

### Expected behavior

I would expect the ```property-change``` event to be generated at most once per second. Or another property that I can observe. Or some way to set the actual ```time-pos``` update frequency.

### Actual behavior

I need to use ```get_property``` instead and schedule it once per second.

**Comment by wiiaboo** [comment]
> I need to use get_property instead and schedule it once per second.

Seems like you got it, then.
