### ISSUE TITLE
no vo=gpu output option?

### ISSUE THREAD

**Issue by andysendo** [mpv-player/mpv#5665]
### mpv version and platform
mpv 0.26 / 0.27 debian9 
self compile v0.26 with debian9 stable
v0.27 installed from debian9 sid

### Reproduction steps
mpv -vo help

### Expected behavior
could enable vo=gpu

### Actual behavior
mpv -vo help no exist gpu option

**Comment by Hrxn** [comment]
You need v0.28.0... (or newer)
