### ISSUE TITLE
How to show taskbar (shown at bottom of video) at MPV opening

### ISSUE THREAD

**Issue by joejim123** [mpv-player/mpv#5668]
I am trying to show taskbar(time, duration, stop, play, etc..) when MPV opens.
Right now when MPV opens, I see title at top but nothing at bottom.
I have to move mouse over bottom part of video to show taskbar.
but if I move mouse away then taskbar disappears.
Sorry to compare but when I open VLC, taskbar is shown at bottom and title at top.

What command line can I enter in mpv.conf file?
I tried window-scale=1, and layout=bottombar, but they do nothing.

**Comment by joejim123** [comment]
here's a screenshot of MPV
![mpv taskbar](https://user-images.githubusercontent.com/37353631/37764690-49ddeba0-2dfd-11e8-9804-c384fec6b065.jpg)

**Comment by wiiaboo** [comment]
https://mpv.io/manual/master/#on-screen-controller-visibility

**Comment by joejim123** [comment]
https://mpv.io/manual/master/#on-screen-controller-visibility  ?????
I tried several combinations.  NONE worked.
osc-visibility always, never, cycle
They all still make me move mouse over taskbar to show.
As soon as mouse is move away from taskbar then it disappears.

I want taskbar show permanently at bottom, and stay there.
Now I have to move mouse on taskbar to keep it showing.

Maye my command is wrong?
osc-visibility always ???

**Comment by wiiaboo** [comment]
Keep in mind osc options aren't in the same place as general mpv options: https://mpv.io/manual/master/#configuration

**Comment by wiiaboo** [comment]
The last link I pasted pointed exactly to the answer to those questions.

**Comment by joejim123** [comment]
ok, call me stupid.  I am not getting it.
I saw the link before you even sent me the link.  I still don;t understand how or where to enter the command?
I ask you again, can you just tell me EXACTLY what command, where I need to put it?
I told you all the options I tried to enter in mpv.conf

I repeat...
SO do I need to add a command line in mpv.conf file?
or in other file?
or execute a command somewhere?
How or what do I need to do?
Can you tell me EXACTLY what to do?
Maybe I am missing something so simple and so obvious?

**Comment by wiiaboo** [comment]
> The OSC offers limited configuration through a config file lua-settings/osc.conf placed in mpv's user dir and through the --script-opts command-line option.

So you either create `lua-settings/osc.conf` file and place `visibility=always` there or add `script-opts=osc-visibility=always` to mpv.conf.

**Comment by joejim123** [comment]
script-opts=osc-visibility=always
That did it.  I was missing = between opts and osc. Why I missed that?
I knew it so simple and obvious, so so close.
Thanks for your patience. THANK YOU. :):):)

**Comment by joejim123** [comment]
Just for fun. If you know this already, don;t spend time researching.
On taskbar times showing, on right side shows time remaining, count down timing.
How can I change that to total length(time) of video?
Again, I probably missed a simple letter or a symbol on command line.

**Comment by wiiaboo** [comment]
https://mpv.io/manual/master/#on-screen-controller-timetotal

**Comment by joejim123** [comment]
That's the answer.
Again, I knew I was so close.
THANKS again.
Bless you. Have a nice day.

**Comment by joejim123** [comment]
FYI
Neither timetotal=no or timetotal=yes works
NO is default to Show total time instead of time remaining.
but default seem to be time remaining., and can't change to total time.
Maybe not available yet?
NO big deal.
