### ISSUE TITLE
Video info (info stats) not shown when using lavfi-complex

### ISSUE THREAD

**Issue by k10kan** [mpv-player/mpv#5670]
Info stats (invoked by pressing i/I) show both:

    * file info - total cache and size
    * video info - frames, fps, timings, res, ar, pix_fmt, game, filter...

with:

mpv video.mkv --vf=vflip
mpv video.mkv --vf="lavfi=[vflip]"
mpv video.mkv --vf="lavfi=[split=2[a][b];[a][b]hstack]"

but show only file info - total cache and size with:

mpv video.mkv --lavfi-complex="[vid1]vflip[vo]"
mpv video.mkv --lavfi-complex="[vid1]split=2[a][b];[a][b]hstack[vo]"

Is it possible to implement/fix this [feature request]/[bug] when using lavfi-complex, or is it impossible to implement it by design [wontfix]?

**Comment by wm4** [comment]
This happens because the `video` (aka `vid`) property returns `no`, which in turn happens because this is indeed not a video track selection via ``--vid``. ``--lavfi-complex`` uses another (internal) track selection mechanism. Video tracks selected this way don't even have to go to the VO, and also multiple can be selected (considering stacking multiple videos). This is a bit silly from the perspective of `stats.lua`. It could probably use `video-out-params` or so to check whether the VO is used for video output (I think).

**Comment by k10kan** [comment]
Thanks for explaining this situation.

Just to add that if in above stated examples audio track is present, then audio info - sample rate, channels and bitrate are shown.

On the other hand, in an example where video+audio tracks are present in media file, and if --lavfi-complex is used on only audio track, video info is shown and audio info is not shown:

mpv video_audio.mkv --lavfi-complex="[aid1]aecho=0.8:0.88:60:0.4[ao]"

It looks like a similar problem. I hope there is a solution for these problems. Fingers crossed for video-out-params check on VO and audio-out-params check on AO patches to land in master, if possible of course.

**Comment by wm4** [comment]
The takeaway is that:
- lavfi-complex can select multiple video tracks even if there is no VO (in theory)
- lavfi-complex can output to a VO even if there are no video tracks selected
- stats.lua considers only the situation without lavfi-complex

Also, some properties probably don't work as expected in the lavfi-complex case.

You should just use --vf or --af instead of lavfi-complex is you only want to filter audio/video separately.

CC @Argon-

**Comment by Argon-** [comment]
Currently, a check of `video` and `audio` are used to determine whether there is audio/video at all. I was not aware there could be video/audio without the `video`/`audio` properties being set.

Would `video-out-params` work as a drop-in replacement or does it have slightly different semantics from `video`? To be precise: when `video-out-params` is available, am I guaranteed there is a video? And is it possible to have a situation where `video` is available and `video-out-params` is unavailable?

**Comment by k10kan** [comment]
I am using --lavfi-complex to filter both video and audio and it is not a major problem not to have video/audio info. For only video/only audio filtering, --vf/--af are working like a charm.

Thinking about what you have said that "some properties probably don't work as expected in the lavfi-complex case" - not all have to be present on osd (they could be very different if mixing from different files). And that brings the question - is --lavfi-complex on par with ffmpeg's -filter_complex?

Most importantly, is --lavfi-complex capable of using video/audio tracks from different files?

I tried naive version:

mpv file1.mkv file2.mkv --lavfi-complex="[vid1][vid2]hstack[vo]"

without success, with double error "Pad vid2 is not connected to anything.".

If --lavfi-complex is not capable of such feat., then, there is a faint possibility things might work after all.

And to answer argon - you can make a video using a special filter like showspectrum that convert input audio to a video output, representing the audio frequency spectrum like eg.:

mpv file.wav --lavfi-complex="[aid1]asplit[ao][spec];[spec]showspectrum[vo]"

**Comment by wm4** [comment]
> I was not aware there could be video/audio without the video/audio properties being set.

Until lavif-complex was added this was true.

> Would video-out-params work as a drop-in replacement or does it have slightly different semantics from video? To be precise: when video-out-params is available, am I guaranteed there is a video (and corresponding video properties such as estimated-vf-fps are available)?

Mostly yes.

>  And is it possible to have a situation where video is available and video-out-params is unavailable?

Yes, if no video frame was decoded yet and the VO not initialized. Obscure but possible.

**Comment by wm4** [comment]
> Most importantly, is --lavfi-complex capable of using video/audio tracks from different files?

RTFM

**Comment by wm4** [comment]
OK, although TFM provides examples, it doesn't provide a full example command line, I guess I'll fix that.

**Comment by k10kan** [comment]
No need to be rude. I guess --external-files / --external-file is made for that job. That rules out possibility to display source video/audio codecs as part of video info, because it would be a mix of various video/audio tracks that could differ; if it is possible to do av info with --lavfi-complex in first place. But final video resolution, current framerate would be very welcome.

This does the trick making -lavfi-complex on par wit ffmpeg's -filter_complex:

mpv video1.mkv --external-file=video2.mkv --lavfi-complex="[vid1][vid2]hstack[vo]"

Thanks for offering to extend the reference manual.

**Comment by wm4** [comment]
That's not rude, just the standard reply if something is in the manual and a shorter version of "look into the manual". It wasn't directly in it (so I added another hint), but there were plenty of references that could be found by searching for lavfi-complex.

**Comment by k10kan** [comment]
If you say so... In any case, thanks for looking into this issue, investing your time and knowledge.

**Comment by k10kan** [comment]
Thank you Argon-, works great.

There is only one thing preventing this to be a perfect solution.

When using mpv with --lavfi-complex, video and audio labels are not present, probably because video/audio codecs are unknown at that time, very difficult to parse/join or something else. But is there a chance to preserve "Video:" and "Audio:" labels with no codecs info, just as a section title?

```
Currently:                       Preferred:
==========                       ==========

File:                            File:                   
  Total Cache ...                  Total Cache ...
  Size: ...                        Size: ...
  A-V: ...                       
  Dropped Frames: ...            Video:
  Display FPS: ...                 A-V: ...
  FPS: ...                         Dropped Frames: ...
  Frame Timings: ...               Display FPS: ...
    ...                            FPS: ...
    ...                            Frame Timings: ...
  Native Resolution: ...             ...
  Window Scale: ...                  ...
  Aspect Ratio: ...                Native Resolution: ...
  Pixel Format: ...                Window Scale: ...
  Primaries: ...                   Aspect Ratio: ...
  Gamma:                           Pixel Format: ...
  Sample Rate: ...                 Primaries: ...
  Channels: ...                    Gamma:
  Bitrate: ...                   
                                 Audio:
                                   Sample Rate: ...
                                   Channels: ...
                                   Bitrate: ...
```

When using mpv without --lavfi-complex everything is unchanged, as it should be:

```
File:                   
  Total Cache ...
  Size: ...

Video: <video codec>
  A-V: ...
  Dropped Frames: ...
  Display FPS: ...
  FPS: ...
  Frame Timings: ...
    ...
    ...
  Native Resolution: ...
  Window Scale: ...
  Aspect Ratio: ...
  Pixel Format: ...
  Primaries: ...
  Gamma:

Audio: <audio codec>
  Sample Rate: ...
  Channels: ...
  Bitrate: ...
```

**Comment by Argon-** [comment]
Ah damn. That case wasn't possible before. Will fix this eventually. There's still a considerable problem with the solution I suggested (see PR), will have to work that out first.

**Comment by k10kan** [comment]
Somewhat unrelated to this issue, but could you incorporate displaying of lavfi-complex filter content? Something like:

```
File:                   
  Total Cache ...
  Size: ...

Video:
  A-V: ...
  Dropped Frames: ...
  Display FPS: ...
  FPS: ...
  Frame Timings: ...
    ...
    ...
  Native Resolution: ...
  Window Scale: ...
  Aspect Ratio: ...
  Pixel Format: ...
  Primaries: ...
  Gamma: ...
  Bitrate: ...
  Filters: vflip

Audio:
  Sample Rate: ...
  Channels: ...
  Bitrate: ...
  Filters: aeval=val(ch)/2:c=same

Complex filter:
  [vid1]hflip[vo];[aid1]aecho=0.8:0.88:60:0.4[ao]
```

**Comment by Argon-** [comment]
Not enough space, really. We are quite limited in height.
Also I'm not sure about the use case. You specified the lavi filter yourself, so you know what it is. The purpose of this script is mainly showing file stats like a built-in `mediainfo` or other information not easily accessible.

**Comment by wm4** [comment]
If you want to go through the effort, you could make a separate stats page with filter infos or so.

**Comment by k10kan** [comment]
If it is inconsistent with how you see stats.lua then that is that. Inspecting player/lua/stats.lua reveals that there is commented `o.key_page_3` with `filter_stats` (no idea what that was planned for). Maybe something could be crafted there.

I will just point out that, as far as I have tested, `append_property` does not spend 1px if `property_item` returns empty string. That is why video "Filter:", audio "Filter:", and future "Complex filter" do not/would not show up, preventing using expensive screen real estate.

But I am in no position nor do I want to force on you anything you feel uncomfortable.

I can only say that after hacking this support locally, at 720p there is enough room for all:

```
mpv video720p.mkv --vf=vflip --af="aeval=val(ch)/2:c=same" \
--lavfi-complex="[vid1]hflip[vo];[aid1]aecho=0.8:0.88:60:0.4[ao]"
```

with approx. 20-25% of height left unused at the bottom in this scenario:

```
File:                   
  Title: ...
  Chapter: ...
  Total Cache ...
  Size: ...

Video:
  A-V: ...
  Dropped Frames: ...
  Display FPS: ...
  FPS: ...
  Frame Timings: ...
    ...
    ...
  Native Resolution: ...
  Window Scale: ...
  Aspect Ratio: ...
  Pixel Format: ...
  Primaries: ...
  Gamma: ...
  Bitrate: ...
  Filters: vflip

Audio:
  Sample Rate: ...
  Channels: ...
  Bitrate: ...
  Filters: aeval=val(ch)/2:c=same

Complex filter: [vid1]hflip[vo];[aid1]aecho=0.8:0.88:60:0.4[ao]
```

Do note that resolution was `1280x720`, with displayed `title` and `chapter`, both video and audio `bitrates`, and all filters (`vf`, `af` and `lavfi-complex` - that usually do not get displayed; by usually I mean when unused, that is 99% of use cases), as well as with restored `Video:` and `Audio:` section titles all with `new lines`.

People "with DS activated on a HDR movie in a 16:9 window" use cases would not see the difference.

And as a final argument, as of right now, this `Complex filter:` is always one liner depending how one looks at it :) :
```
    append_property(stats, "lavfi-complex",
                    {prefix=o.nl .. o.nl .. "Complex filter:", nl="", indent=""})
```
Of course, we do not live in a perfect world.

**Comment by Argon-** [comment]
That's a lot of text just to see the option you specified on the command line yourself on the screen afterwards. ;)

> I will just point out that, as far as I have tested, append_property does not spend 1px if property_item returns empty string. That is why video "Filter:", audio "Filter:", and future "Complex filter" do not/would not show up, preventing using expensive screen real estate.

Of course, that's the point. However, you can't assume this to happen. You have to assume the worst case and this only allows us 2 more lines. But I don't even intend to use them because something really useful/important might show up in the future and then I don't want to change the whole layout just to get the needed vertical space.
That's also headroom I want to keep for users that might use different fonts (with unusual vertical height) or narrow aspect ratios.

> If you want to go through the effort, you could make a separate stats page with filter infos or so.

> Inspecting player/lua/stats.lua reveals that there is commented o.key_page_3 with filter_stats (no idea what that was planned for).

Uh, I actually managed to forget about that...
Back when implementing these "pages" I wanted to have a detailed list of all currently active filters and applied profiles. However, so far nobody was interested. There was one guy who implemented the video/audio filters* and I suggested to use a dedicated page instead (where he has all the space he needs) but he declined because it would be too much effort.
Well, guess we can do that now. I can't give you an ETA though, mainly because I'm on a conference next week and on vacation afterwards.

* Note that the rationale here was that there are filters that get automatically injected, therefore, it can be useful to make this visible for users.
