### ISSUE TITLE
issue with arabic subtitle 

### ISSUE THREAD

**Issue by rekoam** [mpv-player/mpv#5672]
hi
i faced a problem and i couldn’t finding any solution.
why their are G on the last letter .. i facing this problem with every arabic subtitle
and also there are squares
![1941727c-64b3-41cf-9200-b2441cc3a9d7](https://user-images.githubusercontent.com/37669884/37788490-a1df7b9c-2e12-11e8-88c5-bc33ffd91c18.jpeg)
![d28339cc-7a2e-430a-9e42-e42af394954b](https://user-images.githubusercontent.com/37669884/37788491-a214d080-2e12-11e8-9873-e84eeee807c8.jpeg)
![0a580476-45aa-45f0-b22a-70e817bfcac0](https://user-images.githubusercontent.com/37669884/37788492-a2447ea2-2e12-11e8-9275-2fce46009123.jpeg)

**Comment by rekoam** [comment]
why did you ignore the issue template?

**Comment by CounterPillow** [comment]
that label is to say that you ignored the issue template, which you've done. You know, that text in the box that was pre-filled and you just deleted? That template.
