### ISSUE TITLE
Subtitles omissions (Timed Text format)

### ISSUE THREAD

**Issue by Nes-si** [mpv-player/mpv#5675]
Versions: mpv 0.28.2, macOS 10.11.6

When I play file with subtitles in TTXT-format, some of titles may be lost. Probably it happens when the titles are frequent and have a small gaps.
Here is a [sample](https://0x0.st/sB_w.zip). It includes MP4-file with TTXT-subtitles and SRT-file with same subtitles which you can attach to see the difference. Also you can play MP4-file with, for example, VLC player, when the problem doesn't appear.

[Log file](https://0x0.st/sB_g.txt)

**Comment by wiiaboo** [comment]
> [   4.070][e][ffmpeg] mov_text: Invalid UTF-8 in decoded subtitles text; maybe missing -sub_charenc option

May be related.

**Comment by wm4** [comment]
Either broken file or ffmpeg bug. After decoding, ffmpeg sees utf-8 text with errors. This is the result: https://0x0.st/sB9i.txt
It discards any lines with broken utf-8. There's some chance the file is fine and ffmpeg just produces garbage.  How did you create the srt or mp4 file?

**Comment by wiiaboo** [comment]
It looks like the \r is cutting the unicode characters. And since VLC shows the whole line italicized and without broken characters it's probably a FFmpeg bug.

**Comment by wiiaboo** [comment]
https://i.fsbn.eu/br_7_text.srt - srt as extracted by `mp4box -srt`
https://i.fsbn.eu/br_7_text.ttxt - gpac ttxt as extract by `mp4box -ttxt`
https://i.fsbn.eu/br_track7.tx3g - `mp4box -raw`
https://i.fsbn.eu/gpac-srt.ass - ffmpeg output from gpac srt

**Comment by wm4** [comment]
Anyway, seems definitely like a ffmpeg bug. Probably an off by one error or so.

**Comment by wm4** [comment]
Sent a patch to ffmpeg-devel.

**Comment by wiiaboo** [comment]
Both this and #5676 should be fixed with https://github.com/FFmpeg/FFmpeg/commit/b0644c3e1a96397ee5e2448c542fa4c3bc319537.
