### ISSUE TITLE
Italic text with subtitles in Timed Text format

### ISSUE THREAD

**Issue by Nes-si** [mpv-player/mpv#5676]
Versions: mpv 0.28.2, macOS 10.11.6

There are strange text styling with some subtitles in TTXT-format — first letters are italic:
![br mp4 - mpv 2018-03-24 06-54-21](https://user-images.githubusercontent.com/5188972/37860124-397d7526-2f30-11e8-9665-1696c7feb711.png)

Here is a [sample](https://0x0.st/sB_w.zip). You can play MP4-file with, for example, VLC player, when the problem doesn't appear.

[Log file](https://0x0.st/sB_g.txt)

**Comment by wiiaboo** [comment]
Maybe you're using a different VLC, but it sure is almost exactly the same here.
![image](https://i.fsbn.eu/qICG.png)
At most, it's a bug in FFmpeg's ttxt decoder. mpv doesn't do anything special with it.

**Comment by wiiaboo** [comment]
This bug is related to #5675.

**Comment by Nes-si** [comment]
In VLC, the whole phrase is italic. It's right.
In MPV, only the part of the phrase (even the part of the word!) is italic.
It's very strange that you don't see this.
