### ISSUE TITLE
API - error accessing property. Lua.

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#5678]
I want to get color of subtitles `print(mp.get_property("sub-color"))`, but get `nil error accessing property`.
But I can set it without issues.
`mp.set_property("sub-color", '#ff1111')`

**Comment by wm4** [comment]
OK

**Comment by wiiaboo** [comment]
You need git master at least as new as https://github.com/mpv-player/mpv/commit/70b2be3cf7cececd1c4114f21e80189360643a52#diff-402ab6c3293b9e1a0cca2f13ab57aa37.
