### ISSUE TITLE
Changelog-like updates?

### ISSUE THREAD

**Issue by shevegen** [mpv-player/mpv#5682]
Hello mpv-devs,

I update mpv every some months or so, unless some issue arises prior. So perhaps
every 2-3 months.

Now, after that time, I am wondering "What important updates have happened since then?"
to mpv. And I am not sure if this question can easily be answered.

There are logs on github for changes but there seems to be no easy way to know
which updates are there. A changelog would be nice but this may be too much 
work.

Ruby has a news entry where the devs mention major changes:

https://github.com/ruby/ruby/blob/trunk/NEWS

FFMPEG has an entry called news here:

https://www.ffmpeg.org/index.html#news

Though that seems to be updated like once a year or so. ;-)

Anyway, I hope you folks know what I mean here.

I have no specific suggestion as to what the mpv-team could
or should use, that's entirely up to them. Ideally it would be a
lightweight format so that updates and additions and changes
to it would be super-simple, without any real additional 
complexity.

A problem may be in "when to update" since mpv may not 
follow regular release cycles. I think in this case, it may be
best to just pick any random time - say, once a year. Be it
xmas, or new year or in the middle of the year. That is when
a new news file (or similar) is started; and the old one can
be tagged with the specific date aka "NEWS-dd.mm.yyyy.md"
or any other format.

Old news entries could be kept, or removed - isn't important
to me which one. Keeping may be interesting for others who
may want to see older changes.

This would help external users (like me) to keep track as to
what has changed in mpv - I don't need any full changelog,
just the more important hallmark changes that have some
kind of relevance. I think other mpv users may also benefit
from this (perhaps).

I hope I could explain what I meant here. No idea if the mpv
team considers it worthwhile to have, but either way thank
you for reading.

Please feel free to close this issue request at any moment in time.

**Comment by lachs0r** [comment]
https://github.com/mpv-player/mpv/blob/master/RELEASE_NOTES
