### ISSUE TITLE
avi file distorted on iPad 3 iOS 9.3.5

### ISSUE THREAD

**Issue by nabeelahmed87** [mpv-player/mpv#5684]
### mpv version and platform
git-c226bc7616

### Reproduction steps
Sample play attached avi file in iPad 3 , iOS 9.3.5

### Expected behavior
Should play without distortion

### Actual behavior
File played with distortion

### Sample files

[SaMple.avi.zip](https://github.com/mpv-player/mpv/files/1851551/SaMple.avi.zip)

**Comment by Akemi** [comment]
if the issue still persists, please open a new issue.
