### ISSUE TITLE
[IPC] [Linux] Wrong path returned for screenshot-directory property, if it’s not set

### ISSUE THREAD

**Issue by deterenkelt** [mpv-player/mpv#5686]
### mpv version and platform

mpv 0.28.2 on Gentoo Linux

### Reproduction steps

1. Make sure you don’t have `screenshot-directory` set in your mpv config, and have set `ipc-input-server`:

```
$  grep screenshot-dir ~/.config/mpv/mpv.conf
$
$  grep input-ipc-server ~/.config/mpv/mpv.conf
input-ipc-server=/tmp/mpv-socket
```
2. Launch a video file from a file manager with mpv
3. Query the `screenshot-directory` property
```
$  path=$( echo '{ "command": ["get_property_string", "screenshot-directory"] }' | socat - /tmp/mpv-socket | jq -r .data )
```
4. Check it and see, that it’s not empty, but is not a valid path either.
```
$  [ "$path" ] && { test -d "$path" && echo 'Valid path' || echo 'Invalid path.'; }
Invalid path.
$  echo "$path"
~~desktop/
```

### Expected behavior

Retrieve either an empty string (as it was never set, actually) or the value of `working-directory` property, as this is where screenshots actually go.

**Comment by lachs0r** [comment]
~~desktop/ is a valid path to mpv, but that is not very useful to clients. Would have to be expanded.

**Comment by deterenkelt** [comment]
> ~~desktop/ is a valid path to mpv

**Comment by sfan5** [comment]
Because mpv considers `~~desktop` to refer to the homedir:
https://github.com/mpv-player/mpv/blob/master/osdep/path-unix.c#L64

**Comment by jeeb** [comment]
Closing as it seems like we changed the behavior and return an empty string for this property now.
