### ISSUE TITLE
Extra window padding

### ISSUE THREAD

**Issue by somejavadev** [mpv-player/mpv#5687]
### mpv version and platform

Ubuntu 16.04 LTS

mpv git-2018-03-22-a04ac82 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Mar 23 22:46:33 UTC 2018
ffmpeg library versions:
   libavutil       56.11.100
   libavcodec      58.15.100
   libavformat     58.10.100
   libswscale      5.0.102
   libavfilter     7.13.100
   libswresample   3.0.101
ffmpeg version: git-2018-03-22-ed0e0fe

### Reproduction steps

Hi,  
I am trying to create a video wall of RSTP feeds using mpv. This is a 3x2 row, I am using --geometry and --autofit to accomplish this. When I set the Y axis of video 4 (--geometry=0:**362** ) I would expect the video to match up with the bottom of video 1 ( --autofit=568x**362**). Using the --no-border option I would expect that the 2 video feed windows will touch each other but for some reason there is a noticeable gap between the video almost as if there is opaque padding.

```
1) mpv  --keepaspect-window --stop-screensaver  --no-border --autofit=568x362 --geometry=0:0 rtsp://test
2) mpv  --keepaspect-window --stop-screensaver  --no-border --autofit=568x362 --geometry=568:0 rtsp://test
3) mpv  --keepaspect-window --stop-screensaver  --no-border --autofit=568x362 --geometry=1136:0 rtsp://test
4) mpv  --keepaspect-window --stop-screensaver  --no-border --autofit=568x362 --geometry=0:362 rtsp://test
5) mpv  --keepaspect-window --stop-screensaver  --no-border --autofit=568x362 --geometry=568:362 rtsp://test
6) mpv  --keepaspect-window --stop-screensaver  --no-border --autofit=568x362 --geometry=1136:362 rtsp://test

``` 

### Expected behavior

I am expecting Video 1) and Video 4) windows touching each other with the --no-border option specified and the --autofit and --geometry Y axis being set the same. The 2 videos should match up to each other on the Y axis perfectly.

### Actual behavior

There is an opaque gap/padding in between the windows as if the border is still there.

### Log file

[Feed1's logs](https://gist.github.com/somejavadev/ceda4a5bac979e2ac1735ac83f76a0e1)    
[Feed4's logs](https://gist.github.com/somejavadev/c1bafeb29f424500748747627bcf211b)

**Comment by mc4man** [comment]
The gap is because you're not resizing to 362, more like 319

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
