### ISSUE TITLE
Muting and volume adjustments don't work immediately

### ISSUE THREAD

**Issue by HybridDog** [mpv-player/mpv#5692]
### mpv version and platform

2:0.27.0+git2~zzartful

### Reproduction steps
press space to pause, then press m to mute, after that press space to unpause
After unpausing the sound is played a bit before becoming muted.

The same deferring happens when changing volumes.

### Expected behavior
muting and volume adjustments should happen immediately

### Actual behavior
muting and volume changes are a bit deferred

**Comment by CounterPillow** [comment]
That is because mpv delegates these things to the operating system's audio mixer IIRC, which has a certain buffer size. You can use `ao-volume` to change the volume on its side instead, but beware that this can be buggy on some setups.

**Comment by sfan5** [comment]
Apparently this is not considered a bug: https://github.com/mpv-player/mpv/issues/4911#issuecomment-331611196)
