### ISSUE TITLE
Resizing window with vulkan enabled causes the entire system to stutter and freeze

### ISSUE THREAD

**Issue by kiroma** [mpv-player/mpv#5693]
### mpv version and platform
mpv 0.28.0-420-ge3e2c794ef on Kubuntu 17.10
### Reproduction steps
1. Launch a video with --gpu-api=vulkan
2. Attempt to resize the window by dragging border
### Expected behavior
The window gets resized and nothing else happens.
### Actual behavior
The window attempts to resize but freezes and causes the entire system to freeze as well.
### Log file
[http://0x0.st/sMAm.txt](http://0x0.st/sMAm.txt)
### Sample files
Not needed / works on anything

**Comment by sfan5** [comment]
The log file should show the problem occuring, not just `mpv -v`.

**Comment by kiroma** [comment]
The issue does not produce any output in the console.

**Comment by haasn** [comment]
Nvidia driver version?

**Comment by kiroma** [comment]
384.111, from official repos.

**Comment by haasn** [comment]
Try updating if you can

**Comment by shinchiro** [comment]
I also faced similar problem in nvidia GT1030 (391.01) on windows though it happens randomly

**Comment by kiroma** [comment]
Upgraded to 390.48 from graphics-drivers ppa and it works.
