### ISSUE TITLE
Scaling with ewa_lanczossharp stopped working

### ISSUE THREAD

**Issue by FireDK** [mpv-player/mpv#5695]
### mpv version and platform
mpv 0.28.0-420-ge3e2c794ef x64 (via https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20180331-git-e3e2c79.7z by shinchiro) on Windows 10 x64, nVidia driver version 391.5

### Reproduction steps
1. Set scale=ewa_lanczossharp in mpv.conf
2. Open a file in mpv and resize the player to be bigger than the file resolution

### Expected behavior
1. Playback should continue uninterrupted

### Actual behavior
1. Playback freezes (both video and audio)
2. mpv becomes unresponsive and the gui is no longer showed on mouseover
3. mpv begins using about 15% CPU and can only be stopped by killing it's process

I've noticed that playing around with the scale and cscale algorithms produces similar results:
- scale=ewa_lanczos, cscale=ewa_lanczos - works without issues
- scale=ewa_lanczossharp, cscale=ewa_lanczos - works while at original resolution or smaller, crashes when going at higher resolution
- scale=ewa_lanczossharp, cscale=ewa_lanczossharp/ewa_lanczossoft - crashes in every situation, the playback does not even start

The problem is not present using the previous build mpv-x86_64-20180324-git-b4c6fb0 so I'm assuming it is caused by some change between the two commits.

### Log file
https://pastebin.com/eW5x1qNk

**Comment by DeadSix27** [comment]
Exactly the same behavior, but with an AMD GPU and latest driver, so not nvidia driver specific probably.

log-file: https://0x0.st/sMur.txt

**Comment by shinchiro** [comment]
I also tested with `--gpu-api=vulkan`, it freezes when entering fullscreen. Most probably the fault came from shaderc

**Comment by haasn** [comment]
Can you figure out what thread/function is taking 15% CPU? (Attach a debugger after it freezes and get a backtrace)

**Comment by quilloss** [comment]
I have this bug too on my own build.

I think it is due to this https://github.com/google/shaderc/commit/2a0f3a3e348072ad6a9e53874188146b895705ba. Previously optimizing for size in shaderc only unify constants, now it does it exactly as spirv-tools.

The `CreateLocalMultiStoreElimPass` seems to be the optimization that breaks for me. Commenting it out of spirv-tools makes mpv work again. The bug is probably in spirv-tools side.

**Comment by dnmTX** [comment]
Screen is freezing even with ewa_lanczos here(when switching to full screen) with the latest shinchiro build.Definitely there is a bug with shaderc that needs to be looked at.
On another note playing .avi files(software decoding-yuv420p) with --video-sync=display-resample results to a poor performance,high cpu usage and display sync goes from 59.99 to 40 with high jitter.

**Comment by quilloss** [comment]
> Can you figure out what thread/function is taking 15% CPU? (Attach a debugger after it freezes and get a backtrace)

Don't know how to do a back trace but it freezes for a couple of minutes at `DeadInsertElimPass::EliminateDeadInsertsOnePass` (https://github.com/KhronosGroup/SPIRV-Tools/blob/master/source/opt/dead_insert_elim_pass.cpp#L180). Specifically in the `Mark all live inserts` loop.

I was mistaken about `CreateLocalMultiStoreElimPass` it wasn't the cause of the freeze it just seems to trigger it when used with `CreateDeadInsertElimPass`.

**Comment by nshtg** [comment]
```
scale=ewa_lanczossharp
cscale=ewa_lanczossoft
```

Will make mpv freeze without resizing. `mpv 0.28.0-427-gb0951d71f8` built on Sat Apr  7 01:35:41 CEST 2018.

**Comment by FireDK** [comment]
I've tested this after the changes to shaderc using mpv 0.28.0-487-g65f0825315 and the scaling with ewa_lanczossharp seems to work correctly now. There is no more freezing nor excessive CPU usage, so I would consider the problem fixed. Thanks for the support to everyone that got involved.

**Comment by aufkrawall** [comment]
Uhm, anybody else now just getting a blue window after clearing shadercache?
