### ISSUE TITLE
April Fool's Day

### ISSUE THREAD

**Issue by Damianonymous** [mpv-player/mpv#5696]
A great joke with page redirection :)  Ie. I hope it's a joke because I do not know English and Japanese ;)

**Comment by pigoz** [comment]
冗談でわない。だってVLCというものは最高ですよ。このプロジェクトは止める方がいいよと思います。

**Comment by lachs0r** [comment]
同感だ。libplaceboによってVLCはHDRビデオを再生できるからもうmpvは必要ないと思う。

**Comment by Hrxn** [comment]
Am I the only one around here who does not speak Japanese?
/meme
