### ISSUE TITLE
Error when upgrading from 27.2 to 28

### ISSUE THREAD

**Issue by StylinGreymon** [mpv-player/mpv#5698]
mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects                                                                                          
built on Wed Feb 14 14:00:12 CET 2018
Manjaro Linux

Both installing via AUR and building it myself result in error.

### Log file
https://pastebin.com/2tBLz6HG

**Comment by sfan5** [comment]
Update your ffmpeg, this API was added [recently](https://github.com/FFmpeg/FFmpeg/blob/02ae52db87270715bb81ddb912a2e3968e973d1f/doc/APIchanges#L62).
Though I'm not sure why waf let you build like this (it's supposed to check version compatibility).
