### ISSUE TITLE
Audio normalization settings

### ISSUE THREAD

**Issue by FECUPO** [mpv-player/mpv#5700]
Hello. I'm using mpv-x86_64-20171225 for Windows. Could someone please give me some settings to normalize the mpv audio? I tried this setting on mpv.conf but it doesn't do what I want it to do: 

`--audio-normalize-downmix=yes`

What is the best setting for voices in movies to be at the same volume as sounds?
Thank you.

**Comment by richardpl** [comment]
Try `-af loudnorm` or `-af dynaudnorm` see relevant documentation for more info.
