### ISSUE TITLE
reduce film grain

### ISSUE THREAD

**Issue by unculcated** [mpv-player/mpv#5701]
im using brew installed mpv on high Sierra

How can I reduce film grain. Thanks

**Comment by Hrxn** [comment]
https://ffmpeg.org/ffmpeg-filters.html#removegrain

**Comment by unculcated** [comment]
thanks but what is the way to right this into a conf file.

**Comment by Hrxn** [comment]
https://mpv.io/manual/master/#options-lavfi-complex , probably..

**Comment by unculcated** [comment]
kind of doesn't come together for me. Maybe post a small example?

**Comment by unculcated** [comment]
Ive been playing with debanding

**Comment by Argon-** [comment]
There are a dozen denoisers in ffmpeg, no idea which one is best. One possibility would be `--vf=lavfi=[hqdn3d]`, or `--vf=lavfi=[removegrain]`, or ...
You can also assign this to a key and toggle it using that key: `a vf toggle "lavfi=[hqdn3d]"`

**Comment by unculcated** [comment]
im getting this [ffmpeg] Impossible to convert between the formats supported by the filter 'src' and the filter 'auto_scaler_0'
[lavfi] Can't configure libavfilter graph.
wit this : a vf toggle "lavfi=[hqdn3d]"
I get
/Users/ss/.config/mpv/mpv.conf:36: unparseable extra characters: 'vf toggle "lavfi=[hqdn3d]"'

**Comment by Argon-** [comment]
Naturally, key bindings do not go to mpv.conf.

**Comment by unculcated** [comment]
lavfi is just not working. no matter what I try. Im using mpv 0.27.2 hombre edition

**Comment by sfan5** [comment]
You need to disable hwdec for these filters, or use `hwdec=auto-copy`.

**Comment by unculcated** [comment]
here is my mpv conf


################
# Video Output #
################




# Defaults for all profiles
hidpi-window-scale=yes
cocoa-force-dedicated-gpu=yes
profile=opengl-hq
--hwdec=vdpau
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
--script=/Users/ss/.config/mpv/scripts

opengl-shaders=/Users/ss/.config/mpv/shaders/LumaSharpenHook.glsl

blend-subtitles=yes

scale-antiring=0.7
dscale-antiring=0.7
cscale-antiring=0.7
deband=yes
deband-iterations=3
deband-threshold=60
deband-range=16
deband-grain=0
volume=95
hwdec=videotoolbox
correct-downscaling=yes
sigmoid-upscaling=yes
border=no
autofit-larger=100%x95% 

autofit-larger=100%x95%
