### ISSUE TITLE
MPV hangs when you drag the second monitor to the screen

### ISSUE THREAD

**Issue by seamail311** [mpv-player/mpv#5704]
### mpv version and platform
mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
Manjaro Linux Xfce x86-64, kernel - 4.4, video -intel Gl965 (xf86-video-intel+mesa)

Good afternoon. I connect my laptop to TV via s-video cable. When drag and drop on monitor viewing window mpv player (for viewing movie) - mpv player hangs. How to fix this problem? When playing files only on a laptop - there are no problems. 
There is also no problem in mplayer when you connect to the TV. 
Sincerely, Karen.

[output.txt](https://github.com/mpv-player/mpv/files/1874833/output.txt)
[mpv.log](https://github.com/mpv-player/mpv/files/1874842/mpv.log)

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
