### ISSUE TITLE
Error with AAC HE at encode

### ISSUE THREAD

**Issue by celciusb** [mpv-player/mpv#5712]
Hi,

I having problems on my final output audio. I'm ussing --oacopts="profile=+6" but when the final file is muxed the profile is nulled.

So I tried only with the audio to an .aac file and I get this error:
```
[encode-lavc] Opening output file: mpv-x86_64-20171225\op-1.aac
[encode-lavc] Opening muxer: ADTS AAC (Advanced Audio Coding) [adts]
[ffmpeg] adts: MPEG-4 AOT 7 is not allowed in ADTS
```

I tried same with the lastest build of here too https://sourceforge.net/projects/mpv-player-windows/files/64bit/ but I get the same error.

Attachment I send my log file.

[log.txt](https://github.com/mpv-player/mpv/files/1885241/log.txt)

**Comment by wiiaboo** [comment]
Well, either don't use that option or don't use .aac, use .m4a/mp4 instead?
That isn't a mpv issue either way.
