### ISSUE TITLE
mpv show wrong style of ASS subtitles

### ISSUE THREAD

**Issue by tuanden0** [mpv-player/mpv#5715]
### mpv version and platform
mpv 0.28.0-420-ge3e2c794ef

I try to play *.mkv file with the ass subtitles using mpv. But mpv show wrong style of the subtitles. I tried to use another player and it show correctly.

### Expected behavior
https://i.imgur.com/RNWuc3J.png
### Actual behavior
https://i.imgur.com/rNQy494.png
### Log file
https://pastebin.com/YFaaGZim

**Comment by CounterPillow** [comment]
Try `--sub-ass-vsfilter-blur-compat=no`

**Comment by tuanden0** [comment]
@CounterPillow  I tried and it didn't work :'(

**Comment by Akemi** [comment]
a sample would probably be helpful. i also had a similar problem where the window size was smaller than the actual video size and at a specific size blur started to scale wrongly. i meant to look at that file but i kinda lost it.

**Comment by tuanden0** [comment]
@Akemi You're right. Hope someone can fix it

**Comment by DeadSix27** [comment]
@Akemi I've encountered a very similar issue, but only when resizing the video below it's original resolution:
Playing at 720p:
![image](https://user-images.githubusercontent.com/1492505/39560983-e587eb94-4ea2-11e8-9f70-3a8d05e3b39b.png)
Playing below 720p (down scaling):
![image](https://user-images.githubusercontent.com/1492505/39561020-2e4b91f0-4ea3-11e8-8132-6d3b5fe64b1a.png)

A short cut out of the anime having this issue:
https://0x0.st/s12c.mkv

I've tested all vsfilter compat option on and off and they make no difference, I also ran mpv with -no-config
Here is a log file just in case:
https://0x0.st/s12T.txt

I used shin's latest windows build as well as my own (from master).

**Comment by Jj0YzL5nvJ** [comment]
I can reproduce @DeadSix27 issues. However, the interesting part is that only with **x11**,  **gpu** and **vdpau**. **xv** and **vaapi** are unaffected.

**Comment by Akemi** [comment]
probably because the latter two always render the subs at the video resolution.

**Comment by wm4** [comment]
This is a libass problem, not a mpv one.

**Comment by Akemi** [comment]
i reported the bug to libass https://github.com/libass/libass/issues/309.
