### ISSUE TITLE
Scrubbing causes loss of audio for a short time

### ISSUE THREAD

**Issue by TPDesigned** [mpv-player/mpv#5719]
### mpv version and platform
Version 0.28.2, OSX 10.13.3, retina MBP 15in, M370X.

### Reproduction steps
1. Open any video file (.mp4 or .mkv).
2. Scrub using arrow keys to go forward/backward.
3. Observe loss of audio for a short time before it turns back on.

### Expected behavior
It should scrub without any loss of audio.

### Actual behavior
Loss of audio is observed. Almost like the audio scrubbing part is lagging behind the video scrubbing by a few seconds.

### Log file
https://gist.github.com/TPDesigned/1c5a8c95b64aa753c5afbbb289ef572e

### Sample files

They are kind of big. Let me know if you need them, and I can upload them down the road.

Thanks!

**Comment by Dudemanguy** [comment]
Can't reproduce and also very, very old issue so closing. Please make a new one if the issue still occurs.
