### ISSUE TITLE
How to run from OS X command line

### ISSUE THREAD

**Issue by hyperknot** [mpv-player/mpv#572]
I've downloaded the highly recommended ChrisK build for OS X.
http://sva.wakku.to/~chris/mpv_builds/

The problem is that everything is bundled in an app, and now I don't know any way to call it from command line.

Can you document a way for calling mpv from command line on OS X?

Maybe the best solution is similar to Sublime Text, which tells you to create a link if you'd like to call it from command line, using the `subl` command.
`ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" ~/bin/subl`
reference: http://www.sublimetext.com/docs/2/osx_command_line.html

**Comment by ArjixGamer** [comment]
I know this issue has been dead long since, but I wanted to say that its funny.
