### ISSUE TITLE
Make Apple-Remote able to change mpv volume again in OSX 10.13

### ISSUE THREAD

**Issue by hector** [mpv-player/mpv#5721]
I have been able to change the internal volume of mpv in using an Apple-remote with no problems with mac versions prior to High Sierra (OSX 10.13). With the update to High Sierra all buttons kept working except up/down for volume.
It seems Apple might have changed the mapping of those buttons as I have found other users reporting the same problem for other media players. I copy the links I have found about the issue:

https://discussions.apple.com/thread/8106033
https://forums.plex.tv/discussion/289570/mac-mini-osx-updated-to-high-sierra-and-remote-problem

The second link contains references on how other open source projects (Kodi, openPHT) have solved it.

I have also checked that VLC was having this problem and now it is working fine, but I cannot confirm if it is something VLC has solved or something that Apple changed on the last OSX 10.13.4 update. Anyway, the problem persists for MPV on OSX 10.13.4.

**Comment by Akemi** [comment]
if you can try since i don't have an Apple Remote, does this [branch](https://github.com/Akemi/mpv/commits/macOS_hidremote) fix it?

**Comment by hector** [comment]
Is it more or less easy for you to provide a release or a runnable? The compiling process is quite complex :S

**Comment by Akemi** [comment]
you can try your luck with [this](https://0x0.st/sutV.zip).

**Comment by hector** [comment]
Works like a charm, thanks!

**Comment by Akemi** [comment]
will be fixed with #5736.
