### ISSUE TITLE
Loading external audio/subs ignores --alang / --slang settings.

### ISSUE THREAD

**Issue by schneckenschnabel** [mpv-player/mpv#5725]
Loading external files in mpv seems to always be the default selected track while playing something. And thus settings like 'alang' and 'slang' are completely ignored. I have some videos with external audio in German, and those tracks always get selected by default instead of my alang=eng,en settings. I don't want to disable external files since I also use them from time to time.

**Comment by zc62** [comment]
#5433 #5127
