### ISSUE TITLE
Help with vf command

### ISSUE THREAD

**Issue by AxelTerizaki** [mpv-player/mpv#5730]
Hello.

I'm trying to display a picture over a video with filters.

Right now I manage to do it when loading the file like that : 
```[   0.031][d][cplayer] Run command: loadfile, flags=0, args=[D:\dev\toyundamugen-app\app\backgrounds\2.jpg, replace, lavfi-complex=movie=\'D:/dev/toyundamugen-app/app/temp/qrcode.png\'[logo]; [logo][vid1]scale2ref=128:128[logo1][base];[base][logo1] overlay=19:12[vo]]```

This works pretty well, and the background 2.jpg is loaded with a QR code in the upper left.

To apply this to a video though, I'm trying to do it via the IPC but lavfi-complex doesn't seem to work there : 

```[   8.399][d][cplayer] Run command: vf, flags=0, args=[set, lavfi-complex="movie=\'D:/dev/toyundamugen-app/app/avatars/blank.png\'[logo];[logo][vid1]scale2ref=256:256[logo1][base];[base][logo1]overlay=256:144[vo]"]
[   8.400][f][lavfi] filter 'complex' not found or failed to allocate
[   8.400][e][user_filter_wrapper] Creating filter 'complex' failed.
```

Is there something I'm missing? Why doesn't it recognize the filter like this, but does when I load up another file? Is there something else I should do or another way to call it?

Thanks in advance for your help.

**Comment by wiiaboo** [comment]
lavfi-complex isn't a filter, it's a property/option. You're trying to use it as if it was a filter where there's something that considers `lavfi-<filter>` as you wanting to use a ffmpeg/libav filter instead of mpv's.

Since you didn't show how called it through IPC, I don't know how to help you.

**Comment by AxelTerizaki** [comment]
Thanks for your quick reply.

Here's what I sent : 

```
{"command":["vf","set","lavfi-complex=\"movie=\\'D:/dev/toyundamugen-app/app/avatars/blank.png\\'[logo];[logo][vid1]scale2ref=256:256[logo1][base];[base][logo1]overlay=256:144[vo]\""]}
```

Since this is through an API which talks with mpv, I don't know if it's the exact IPC command being sent, but other commands (like show-text) work very fine that way.

**Comment by wiiaboo** [comment]
You want set-property or something like that, not `vf set`.

**Comment by AxelTerizaki** [comment]
Sorry to re-open this but this is not completely answering my question.

I tried to set a property "vf" to something and got this : 

```
[  24.384][v][cplayer] Set property: vf="lavfi-complex=\u0022movie='D:/dev/toyundamugen-app/app/avatars/blank.png'[logo];[logo][vid1]scale2ref=256:256[logo1][base];[base][logo1]overlay=256:144[vo]\u0022" -> 0
```

However, nothing happens on screen when the property is set. Do I need to issue a command after that? 

Sorry if my question seems stupid but the manual lacks some examples on how to do something like that...

**Comment by wiiaboo** [comment]
Re-read what I wrote. You're using the wrong command. lavfi-complex isn't a filter. Stop using vf.

**Comment by AxelTerizaki** [comment]
What I don't get is what property should I set then?

**Comment by wiiaboo** [comment]
lavfi-complex.

**Comment by AxelTerizaki** [comment]
Looks like it took the property into account : 

```
[  12.731][v][cplayer] Set property: lavfi-complex="movie='D:/dev/toyundamugen-app/app/avatars/blank.png'[logo];[logo][vid1]scale2ref=256:256[logo1][base];[base][logo1]overlay=256:144[vo]" -> 1
```

However, it's not producing anything on screen, and it disabled the ASS subtitles ont he video for some reason I can't seem to explain.

I did get another error though in the logs : 
```
[  12.730][e][ffmpeg] Parsed_movie_0: Failed to avformat_open_input 'D'
[  12.730][e][ffmpeg] AVFilterGraph: Error initializing filter 'movie' with args 'D:/dev/toyundamugen-app/app/avatars/blank.png'
[  12.730][f][lavfi] parsing the filter graph failed
```

I'll have to find out how I have to escape the path to the image file, or am I doing something wrong?

Any idea would be appreciated.

**Comment by AxelTerizaki** [comment]
Okay found out I had to escape the : 

However, I still need to reenable ASS subtitles though...

**Comment by AxelTerizaki** [comment]
I fail to understand how this works exactly. I observed the lavfi-complex property and it was empty before I changed it. 

When I change it, subs disappear but my picture appears where I want it (which is good, thank you for explaining it to me.)

When I change it back to empty `''` to make the image disappear,  it makes all video disappear completley instead, only sound is still active.

**Comment by AxelTerizaki** [comment]
After a good night's sleep and some more testing I found something hidden deep in the mpv's documentation : there are special labels which are used with lavfi-complex filter.

* [vo] is the video output as is
* [sid1] is the first subtitle track (just like [aid1]/[vid1] are audio/video tracks.

Adding [sid1] after the last [vo] seems to work. After you want to reset the filter, set the property lavfi-complex to [vo][sid1] to have your video and subtitles only on screen.

I have another problem at the moment with the latest mpv version but will make a separate issue for that.

**Comment by AxelTerizaki** [comment]
Actually this doesn't work at all. I retried it and I must have triggered something earlier that made subtitles appear (likely something that broke the chain and made mpv not apply it)

My issue remains : I can't seem to keep the subtitles on screen after applying a lavfi-complex filter chain.

I'd like the issue to be re-opened since I still have trouble with this and could need some help, please.
