### ISSUE TITLE
Can no longer play videos with `ytdl://`

### ISSUE THREAD

**Issue by MitchWeaver** [mpv-player/mpv#5733]
**mpv version and platform**: latest

I used to use this to play the first result of a youtube search:

`mpv --no-video --ytdl-format=bestaudio ytdl://ytsearch:"$@"`

However this no longer works as of a [commit in January](https://github.com/mpv-player/mpv/commit/e6e6b0dcc7e9b0dbf35154a179b3dc1fcfcaff43). 

It fails with "ignoring potentially unsafe url -" and then the video link identifer.

----

Playing videos with a specific youtube link works as normal.

**Comment by wiiaboo** [comment]
That's not the commit that affected it.
You need `--script-opts=ytdl_hook-try_ytdl_first=yes` for mpv to try opening with the script first.
