### ISSUE TITLE
Wish - An option to decrease volume when "icy-title" sets to a specific keyword

### ISSUE THREAD

**Issue by maxxsch28** [mpv-player/mpv#5735]
### mpv version and platform
mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mar 20 2018
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.2

### Reproduction steps
Sorry for use this bug tracker to send you a wish. I use mpv to listen a streamig of the most important AM stations of Argentina (https://buecrplb01.cienradios.com.ar/Mitre790.aac).

I ran mpv on command line of opensuse Linux, and today I found that shows extra information about the station, like:

> icy-title: ADSWIZZ
> A: 05:27:24 / 00:00:00 Cache: 10s+145KB
> File tags:
>  icy-title: CONTENT
> A: 05:41:07 / 00dd:00:00 Cache: 10s+130KB

Then, I just think that an option to automagically decrease the volume when ici-title sets to "ADSWIZZ" would be wonderful, when the advertisements starts always the volume decrease a few points...

Thanks for everything, sorry for my english.

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by sfan5** [comment]
That's doable using a script.

**Comment by maxxsch28** [comment]
Do you have any kind of example? 
Or a link to find it?

**Comment by CounterPillow** [comment]
Here's a real simple one that could work for you, it just sets the volume to 50% if the title is "ADSWIZZ" and otherwise sets it to 100%. Place inside `~/.config/mpv/scripts/`

```lua
function check_title_and_set_vol(name, value)
    if value == "ADSWIZZ" then
        mp.set_property("volume", 50)
    else
        mp.set_property("volume", 100)
    end
end

mp.observe_property("media-title", "string", check_title_and_set_vol)
```

**Comment by maxxsch28** [comment]
For the record, I solve my wish thanks to @CounterPillow :+1: 
```
function check_title_and_set_vol(name, value)
    if value == "ADSWIZZ" then
        mp.set_property("volume", 65)
    else
        mp.set_property("volume", 100)
    end
end

mp.observe_property("metadata/icy-title", "string", check_title_and_set_vol)
```
