### ISSUE TITLE
[Question] How to make screenshot in CLI with screenshot-template?

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#5738]
Something like this (doesn't work):
`mpv i.mp4 --no-audio --start=60 --frames=100 --screenshot-template="%P"`
`mpv i.mp4 --no-audio --start=60 --frames=100 -o "%P.jpg"`
Instead of this:
`mpv i.mp4 --no-audio --start=60 --frames=100 -o %03d.jpg`

I also wouldn't mind video frame number in filename instead of time position.

**Comment by Akemi** [comment]
use the json ipc.
