### ISSUE TITLE
[Functionality Improvement] When seeking audio streams, don't actually seek when paused.

### ISSUE THREAD

**Issue by LichenSymbiont** [mpv-player/mpv#5740]
I like to play long audio files just from the terminal. So last night I could hear the HDD's every seeking step as I was seeking to my desired location in the file, even when paused. And I think that's unessesary behaviour.

It's not big, but it's a bit distracting now that I know that it does unessesary seeks.

**Comment by wm4** [comment]
Write a script to implement the wanted behavior.

**Comment by LichenSymbiont** [comment]
But it's truly unessesary behaviour, is it not? so why not fix it in the code?

**Comment by wm4** [comment]
It's not unnecessary. If you tell it to seek, it seeks. Why would it ignore the seek? That would be unexpected.

**Comment by LichenSymbiont** [comment]
It's jumping around on the drive, reading data into the buffer without it having to play it. It's unessesary. Though there are sometimes broken audio-files that have an incorrect length, which is only corrected after seeking and loading the audio data. So it might not work. It's no big deal, just a potential optimization.
