### ISSUE TITLE
MPV stopped loading files in Multiple Instances after latest Mac OS X update

### ISSUE THREAD

**Issue by xMikasa** [mpv-player/mpv#5747]
i updated mac recently and after the update mpv stopped opening files in multiple instances of itself.

### mpv version and platform
mpv - 27.2 MacOS X - 10.13.4
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Open media file X then open another one Y. Files were opened through finder via app bundle and not terminal.
### Expected behavior
2 separate instances of MPV with X and Y both open.
### Actual behavior
1 instance of MPV. 
### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Akemi** [comment]
mpv never opened multiple instances when double clicking files. only at a small period of time when 10.13 introduced a bug that was fixed (#4926).

what you describe is not expected behaviour and not how macOS Apps are supposed to work. what could be expected is one instance multiple windows.
