### ISSUE TITLE
Jump to next keyframe while playing choppy video (big distance between timestamps)

### ISSUE THREAD

**Issue by brachna** [mpv-player/mpv#5748]
### mpv version and platform

mpv-x86_64-20180414-git-9efb027
Windows 8.1 64bit

### Reproduction steps

1. record choppy HLS stream using streamlink
2. remux it into MKV using ffmpeg to preserve original duration ( ffmpeg -i %1 -c:v copy -c:a copy -copyts -start_at_zero "%~n1.mkv" )
3. play it

### Expected behavior

Once encountered with timestamps that have long distance between them - jump to next keyframe.

### Actual behavior

mpv waits however long required time is before going to the next keyframe, unless user manually seeks further.

### Log file

[output.zip](https://github.com/mpv-player/mpv/files/1920723/output.zip)

### Sample files

[sameda_2018.04.16_14.11.41_UTC [ffmpeg, copyts]_splitted.zip](https://github.com/mpv-player/mpv/files/1920724/sameda_2018.04.16_14.11.41_UTC.ffmpeg.copyts._splitted.zip)

---

I realize it's not a bug at all, but a correct, expected behavior of mpv.
What I'm asking is - is it possible to tell mpv to not wait so long and instead jump to next keyframe in case of choppy videos?
In the uploaded sample video playback "freezes" at 00:00:17 and then waits quite a while until getting to 00:04:57.

**Comment by wm4** [comment]
Define "long distance" in a way that doesn't break anything.
Have fun.

**Comment by wm4** [comment]
Also not going to touch that garbage file hoster.

**Comment by brachna** [comment]
Files are uploaded to GitHub.

Long distance, like from 00:00:17 to 00:04:57. Obviously not hardcoded value, but something that's adjustable by user.
I'm not even asking to add something like this to player, I'm asking if mpv already has something like this.
If it's not, ok.

**Comment by wm4** [comment]
Yeah, so we consider it some sort of extreme VFR. And sometimes this is what you actually want. (There are such "slide show" files out there.)

**Comment by brachna** [comment]
Alright.
