### ISSUE TITLE
I am not able to use properties in MPV player?

### ISSUE THREAD

**Issue by sagar14rocks** [mpv-player/mpv#5754]
i am working on a project in which i am using mpv for playing multistream udp, in which i have to select and play the streams, i say that vid option is changing at runtime so i am not able to get stream id and play it properly, as well as i want to use property like track-list but i don't know how to use property. Please tell me how to select vid at runtime and play the proper stream, as well as please tell me how to use propertiies with example, thanks

**Comment by myfreeer** [comment]
Post minimal code that reproduces that then

**Comment by lachs0r** [comment]
This is described in the manual and also done in our existing code examples.
