### ISSUE TITLE
radv: crash when using cscale=ewa_lanczos

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#5756]
### mpv version and platform
mpv 0.28.0-476-ge7e06a47a0
mesa 18.1.0_devel.101783.6754c2e83d
shaderc-git r465.5fd1b25.glslang_r2706
RX 560 on Xorg

### Reproduction steps
Play any file with this config:
gpu-api=vulkan
cscale=ewa_lanczos

### Expected behavior
File should play fine (it does with cscale=lanczos or gpu-api=opengl).

### Actual behavior
mpv crashes instantly.

Note: I actually experienced the crash problem only after seeking, so I dubbed down my config to find which setting is faulty. Though I suspect that it comes down to the ewa scaler (compute shader?) problem anyway.

### Log file
https://pastebin.com/ZsGxvkPk

### Sample files
Happens with any video.

**Comment by haasn** [comment]
Can't reproduce. What version of mesa/libdrm/kernel/amdgpu are you on?

**Comment by haasn** [comment]
Nvm, just saw your comment. Either way, I can't reproduce this with an RX 560 and kernel 4.16 + mesa git.

**Comment by aufkrawall** [comment]
Thanks, it looks like I'm screwed then. :(

I tried:
-3 different kernels (4.16, 4.17rc and 4.18 drm-next-wip)
-Mesa 17.3 (LLVM 5), 18.0 (LLVM6 ) and 18.1rc (LLVM 6)
-officially endorsed mpv-build script instead of modified pkgbuild for Arch

I suppose it must have been some change in either mpv or one dependency, since I could use mpv + radv for quite some time without issues. Vulkan games work fine too.

Would there be any chance to get some kind of crashdump or debug logs?

**Comment by Worfhard** [comment]
### mpv version and platform
mpv 0.28.0-524-gdc16d85379
mesa 18.0.1
shaderc-git r465.5fd1b25.glslang_r2706
AMD RX 480 X.Org
### Reproduction steps
Same as OP
### Expected behavior
Same as OP
### Actual behavior
mpv crashes instantly.
### Log file
https://paste.ubuntu.com/p/Jj3MGGBbXt/
### Sample files
All videos

**Comment by haasn** [comment]
> Would there be any chance to get some kind of crashdump or debug logs?

Run in gdb, print backtrace. But from the log it seems like it crashes during shader compilation, which probably makes this a driver issue. (But not definitely, which is why a backtrace would be helpful)

**Comment by aufkrawall** [comment]
I hope this comes near to what you've requested:
https://pastebin.com/P9fTNDfk

**Comment by haasn** [comment]
It does seem like it's crashing within the vulkan driver, not mpv. Although the lack of debug symbols makes it pretty useless overall.

**Comment by aufkrawall** [comment]
So I need to rebuild mpv with debug support on Arch. Maybe/likely at the end of the week.

**Comment by haasn** [comment]
> So I need to rebuild mpv with debug support on Arch. Maybe/likely at the end of the week.

And libvulkan_radeon.so

**Comment by aufkrawall** [comment]
It crashes with amdvlk (open source) too.

**Comment by aufkrawall** [comment]
Here we go with debug symbols enabled for llvm, mesa and mpv:
https://pastebin.com/AKjhsgrv

**Comment by haasn** [comment]
Seems like an upstream issue. Can you report it to mesa? (Include the shader dump)

**Comment by aufkrawall** [comment]
Does the shader get dumped together with the crashed process in RAM when I run gdb dump...?

**Comment by haasn** [comment]
Well yeah, because it's still resident in memory while mpv is trying to compile the thing. It also gets logged though.

**Comment by aufkrawall** [comment]
Alright, I'll report back when the Mesa devs respond. Thanks so far!

**Comment by aufkrawall** [comment]
Somebody else went ahead, it's already fixed in mesa-git.:
https://bugs.freedesktop.org/show_bug.cgi?id=106090
Closing.
