### ISSUE TITLE
help with opening multiple files simultaneously 

### ISSUE THREAD

**Issue by dsumo99** [mpv-player/mpv#5757]
I downloaded mpv from the mpv website and it was the OS X builds by stolendata. I have the latest stable build. after an update, i haven't been able to play multiple files at the same time. Could someone help me out. is there any way to fix this? i don't use any commands, just play the files as is from the player. I have Mac OS highsierra 10.13.4.
I don't have any knowledge in command lines and terminal.
Thanks.

**Comment by Akemi** [comment]
you are not supposed to ignore the issue template.
