### ISSUE TITLE
Regression: Cannot play some archive formats

### ISSUE THREAD

**Issue by Forcer78** [mpv-player/mpv#5759]
### mpv version and platform

mpv 0.28.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0

Homebrew on macOS 10.12.6, built with --with-libarchive.

### Reproduction steps

Use mpv to play a rar, zip, 7z, or other archive file containing playable media.

### Expected behavior

The media within are played.

### Actual behavior

Many zip and rar archives do not play, some do; no 7z files tested have played. According to the file utility, the v2.0 rars that I've tried work, but v4 rars likely will not play (but still may). Zips of both v1.0 and v2.0 are failing, with a few random successes.

All tested archives previously worked when played with mpv 0.27.2 and earlier. The version of libarchive has not changed since last July.

### Log file

Log file attempting to play test.rar and test.zip: https://0x0.st/sQHl.log

### Sample files

rar: https://0x0.st/sQH0.rar
zip: https://0x0.st/sQHU.zip

**Comment by wm4** [comment]
Probably locale bullshit. Not our problem, report to Apple or libarchive.

**Comment by Forcer78** [comment]
As noted, the files worked on previous versions of mpv/ffmpeg, and no other factor (OS, libarchive) has changed. Given what's known, I don't see how the problem can lie elsewhere.

**Comment by wm4** [comment]
1e70e82baa9193f6f027338b0fab0f5078971fbe

Maybe your OSX doesn't like the locale we try. Anyway, I won't fix this, ask libarchive to fix their API, or find out how to make Apple accept the locale (or whether that is the problem at all).

**Comment by Forcer78** [comment]
> Last but not least, the UTF-8 locale name is apparently not even
standardized. At the moment I'm trying to use "C.UTF-8", which is
apparently glibc _and_ Debian specific. Got to use every opportunity to
make correct usage of UTF-8 harder. What luck that this commit is only
for some optional relatively obscure mpv feature.
>- Use the "C.UTF-8" locale, which is probably not 100% standards
  compliant, but works on my system, so it's fine.

So you suspected that this locale was specific to your system and used it anyway, actively breaking functionality on other platforms for a personal corner case, and now refuse to fix it in order to stick it to the POSIX man.

@richfelker was correct in that commit thread. Replacing that line with something like

`mpa->locale = newlocale(LC_CTYPE_MASK, "en_US.UTF-8", (locale_t)0);`

should work more widely, and on macOS restores archive playback in general and for Unicode filenames in zip files. Unicode filenames in the rar archives I've tried don't work, but considering that the filename is properly displayed in the error I suspect there's a separate bug preventing that.

**Comment by Akemi** [comment]
yeah macOS doesn't accept `C.UTF-8` as the locale. the most appropriate equivalent seems to be `en_US.UTF-8`. a list of all supported locales via `locale -a` at the bottom. do we have a preferred way to fix this, i suppose #if directives are out of the questions?
```
af_ZA
af_ZA.ISO8859-1
af_ZA.ISO8859-15
af_ZA.UTF-8
am_ET
am_ET.UTF-8
be_BY
be_BY.CP1131
be_BY.CP1251
be_BY.ISO8859-5
be_BY.UTF-8
bg_BG
bg_BG.CP1251
bg_BG.UTF-8
ca_ES
ca_ES.ISO8859-1
ca_ES.ISO8859-15
ca_ES.UTF-8
cs_CZ
cs_CZ.ISO8859-2
cs_CZ.UTF-8
da_DK
da_DK.ISO8859-1
da_DK.ISO8859-15
da_DK.UTF-8
de_AT
de_AT.ISO8859-1
de_AT.ISO8859-15
de_AT.UTF-8
de_CH
de_CH.ISO8859-1
de_CH.ISO8859-15
de_CH.UTF-8
de_DE
de_DE.ISO8859-1
de_DE.ISO8859-15
de_DE.UTF-8
el_GR
el_GR.ISO8859-7
el_GR.UTF-8
en_AU
en_AU.ISO8859-1
en_AU.ISO8859-15
en_AU.US-ASCII
en_AU.UTF-8
en_CA
en_CA.ISO8859-1
en_CA.ISO8859-15
en_CA.US-ASCII
en_CA.UTF-8
en_GB
en_GB.ISO8859-1
en_GB.ISO8859-15
en_GB.US-ASCII
en_GB.UTF-8
en_IE
en_IE.UTF-8
en_NZ
en_NZ.ISO8859-1
en_NZ.ISO8859-15
en_NZ.US-ASCII
en_NZ.UTF-8
en_US
en_US.ISO8859-1
en_US.ISO8859-15
en_US.US-ASCII
en_US.UTF-8
es_ES
es_ES.ISO8859-1
es_ES.ISO8859-15
es_ES.UTF-8
et_EE
et_EE.ISO8859-15
et_EE.UTF-8
eu_ES
eu_ES.ISO8859-1
eu_ES.ISO8859-15
eu_ES.UTF-8
fi_FI
fi_FI.ISO8859-1
fi_FI.ISO8859-15
fi_FI.UTF-8
fr_BE
fr_BE.ISO8859-1
fr_BE.ISO8859-15
fr_BE.UTF-8
fr_CA
fr_CA.ISO8859-1
fr_CA.ISO8859-15
fr_CA.UTF-8
fr_CH
fr_CH.ISO8859-1
fr_CH.ISO8859-15
fr_CH.UTF-8
fr_FR
fr_FR.ISO8859-1
fr_FR.ISO8859-15
fr_FR.UTF-8
he_IL
he_IL.UTF-8
hi_IN.ISCII-DEV
hr_HR
hr_HR.ISO8859-2
hr_HR.UTF-8
hu_HU
hu_HU.ISO8859-2
hu_HU.UTF-8
hy_AM
hy_AM.ARMSCII-8
hy_AM.UTF-8
is_IS
is_IS.ISO8859-1
is_IS.ISO8859-15
is_IS.UTF-8
it_CH
it_CH.ISO8859-1
it_CH.ISO8859-15
it_CH.UTF-8
it_IT
it_IT.ISO8859-1
it_IT.ISO8859-15
it_IT.UTF-8
ja_JP
ja_JP.eucJP
ja_JP.SJIS
ja_JP.UTF-8
kk_KZ
kk_KZ.PT154
kk_KZ.UTF-8
ko_KR
ko_KR.CP949
ko_KR.eucKR
ko_KR.UTF-8
lt_LT
lt_LT.ISO8859-13
lt_LT.ISO8859-4
lt_LT.UTF-8
nl_BE
nl_BE.ISO8859-1
nl_BE.ISO8859-15
nl_BE.UTF-8
nl_NL
nl_NL.ISO8859-1
nl_NL.ISO8859-15
nl_NL.UTF-8
no_NO
no_NO.ISO8859-1
no_NO.ISO8859-15
no_NO.UTF-8
pl_PL
pl_PL.ISO8859-2
pl_PL.UTF-8
pt_BR
pt_BR.ISO8859-1
pt_BR.UTF-8
pt_PT
pt_PT.ISO8859-1
pt_PT.ISO8859-15
pt_PT.UTF-8
ro_RO
ro_RO.ISO8859-2
ro_RO.UTF-8
ru_RU
ru_RU.CP1251
ru_RU.CP866
ru_RU.ISO8859-5
ru_RU.KOI8-R
ru_RU.UTF-8
sk_SK
sk_SK.ISO8859-2
sk_SK.UTF-8
sl_SI
sl_SI.ISO8859-2
sl_SI.UTF-8
sr_YU
sr_YU.ISO8859-2
sr_YU.ISO8859-5
sr_YU.UTF-8
sv_SE
sv_SE.ISO8859-1
sv_SE.ISO8859-15
sv_SE.UTF-8
tr_TR
tr_TR.ISO8859-9
tr_TR.UTF-8
uk_UA
uk_UA.ISO8859-5
uk_UA.KOI8-U
uk_UA.UTF-8
zh_CN
zh_CN.eucCN
zh_CN.GB18030
zh_CN.GB2312
zh_CN.GBK
zh_CN.UTF-8
zh_HK
zh_HK.Big5HKSCS
zh_HK.UTF-8
zh_TW
zh_TW.Big5
zh_TW.UTF-8
C
POSIX
```

**Comment by Forcer78** [comment]
I'm not sure conditional switching is necessary. The change mentioned above,

`mpa->locale = newlocale(LC_CTYPE_MASK, "en_US.UTF-8", (locale_t)0);`

should take the user's existing locale and modify it by only changing the character encoding, cross-platform. Using LC_CTYPE instead of LC_ALL keeps the existing locale settings for collation et al., and en_US.UTF-8 is presumably widely supported: the character set should be the same between all *.UTF-8 locales (all except Ethiopian are symlinked to the same file on my Mac), and en_US is defined as present on the macOS/Debian/BSD systems I've done light testing on (in the sense that they return valid locales, not necessarily full mpv compilation).

That said:
- I have no experience with locales.
- I haven't checked other mpv target platforms or locales.
- I have no example archive files that were broken before this patch that work afterwards, as opposed to vice versa. If @wm4 has one to upload, that would help.

**Comment by jameshilliard** [comment]
Try [this](https://github.com/mpv-player/mpv/pull/6438), I've tested it as part of a different application on a system without a `C.UTF-8` locale and it worked. Make sure you have a valid `UTF-8` locale set(such as `en_US.UTF-8`) for your system when running it.
