### ISSUE TITLE
[Question] Can I inject AviSynth script to mpv without write file?

### ISSUE THREAD

**Issue by MinorMole** [mpv-player/mpv#5763]
Can I inject AviSynth script to mpv without write file? In the document there are many protocols but I don't know how to use it.

Thank in advance!

**Comment by qyot27** [comment]
If you mean playing back AviSynth scripts, just open it like any other video file.  If you mean using the script as some kind of filtering template, I think that's only possible with VapourSynth.

**Comment by wm4** [comment]
I don't think avs even has I/O abstraction. Otherwise you could just use memory:// or hex://.

**Comment by MinorMole** [comment]
@wm4, thank for your reply. Can you explain to me, how to use memory:// or hex:// and the example command? Thank in advance!

**Comment by wm4** [comment]
I told you that it's not possible because avisynth doesn't support it. You should use something better. (I could dig out my vapoursynth wrapper for ffmpeg...)
