### ISSUE TITLE
New version of mpv? (Lasch0r)

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5765]
MPV 0.28 By lasch0r

Good morning, I wanted to ask a question, ffmpeg released a new version (FFmpeg 4.0 "Wu") I had previously been told here that there would be new stable versions of MPV from lasch0r when FFMPEG is updated. Will there be a new version of MPV with that update of FFMPEG?
I ask why the last MPV version of lash0r is from December of last year. Thank you very much!!

**Comment by wm4** [comment]
The only purpose of releases is to make Linux distros happy, which then will distribute old builds outdated by years with no security patches and bug fixes.

Use git master if you want something uptodate.

**Comment by lachs0r** [comment]
Calm down, I’ll get to it. Been working on new build infra. Windows build page will get revamped too.
