### ISSUE TITLE
Make touchbar optional on OS X

### ISSUE THREAD

**Issue by tonycpsu** [mpv-player/mpv#5766]
There are times when I would prefer that mpv did not use the touchbar, or at least hid the seek bar.  My particular use case is watching baseball games where I'd rather not know how much time is left in the game, but I'm sure there are others who would rather not get a visual indicator of how long the video is.

A simple command-line / config switch for enabling / disabling the touchbar would be fine for my purposes.

**Comment by Akemi** [comment]
that's what the touch bar config menu is for. other than that, the touch bar is created at a point (of time) where we can't read any options (yet).
