### ISSUE TITLE
Wayland video output missing

### ISSUE THREAD

**Issue by yeahnope** [mpv-player/mpv#5767]
### mpv version and platform

Build from master: 0.28.0-487-g65f0825315
Running on debian buster

### Reproduction steps

1. Install dependencies:
`apt-get install libwayland-dev libxkbcommon-dev libegl1-mesa-dev`
2. Build with mpv-build

### Expected behavior

`--vo=help ` contains `wayland`

### Actual behavior

`--vo=help `lists
```
Available video outputs:
  libmpv           render API for libmpv
  gpu              Shader-based GPU Renderer
  vdpau            VDPAU with X11
  xv               X11/Xv
  vaapi            VA API with X11
  x11              X11 (slow, old crap)
  null             Null video output
  image            Write video frames to image files
  tct              true-color terminals
  caca             libcaca
  drm              Direct Rendering Manager
```

even though wayland is mentioned in `mpv -v`:
`[cplayer] List of enabled features: 52arch alsa asm atomics build-date caca cdda cplayer cplugins debug-build drm dvdnav dvdread dvdread-common egl-drm egl-helpers egl-x11 encoding fchmod ffmpeg gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack jpeg lcms2 libaf libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm librt libsmbclient linux-fstatfs lua openal optimize oss-audio posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rubberband stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vt.h wayland wayland-protocols x11 xv zlib zsh-comp`

### Log file

[mpv --no-config -v logfile](https://0x0.st/sQJv.log)

**Comment by linkmauve** [comment]
This vo has been removed in 980116360b0f393e16064ec3b7a4ef9efb14372e, use `--gpu-context=wayland` with the (default) gpu vo if you want to use mpv natively on Wayland.
