### ISSUE TITLE
[Question] How to format JSON command for loadfile with multiple options

### ISSUE THREAD

**Issue by 00SteinsGate00** [mpv-player/mpv#5770]
### MPV Version and OS 

MPV 0.28.2 on Mac OS 10.13.4

### Problem

I hope you don't mind me skipping the rest of the form because it's just a simple question and probably not a bug.

I'm the author of [Node-MPV](https://github.com/00SteinsGate00/Node-MPV), a Node-JS library that controls MPV through the JSON API.

I have a problem with loading a file or stream and using multiple options. I checked the reference on [mpv.io](mpv.io) but I am unable to find out how to format the JSON string. I tried the following  versions of which none worked

#### 1

```JavaScript
{"command": ["loadfile", "/some/song.mp3", "replace", "replaygain-fallback=20.0", "force-window=yes"]}
```

MPV says that **loadfile** takes only 3 options, makes sense

#### 2

```JavaScript
{"command": ["loadfile", "/some/song.mp3", "replace", ["replaygain-fallback=20.0", "force-window=yes"]]}
```

`Command loadfile: argument 3 has incompatible type.`

#### 3
```JavaScript
{"command": ["loadfile", "/some/song.mp3", "replace", "options": ["replaygain-fallback=20.0", "force-window=yes"]]}
```

`malformed JSON received`

#### 4

```JavaScript
{"command": ["loadfile", "/Users/wuschel/Documents/Code/Node-MPV/promises.mp3", "replace", ["replaygain-fallback": 20.0, "force-window": "yes"]]}
```

`malformed JSON received`

#### 5

```JavaScript
{"command": ["loadfile", "/Users/wuschel/Documents/Code/Node-MPV/promises.mp3", "replace", "options": ["replaygain-fallback": 20.0, "force-window": "yes"]]}
```
`malformed JSON received`

Unfortunately I have no idea what to try further. Would be highly appreciated if you could help out with this :)

**Comment by wm4** [comment]
2-5 use invalid json, because you use object syntax inside an array.

What you want is:

> {"command": ["loadfile", "/Users/wuschel/Documents/Code/Node-MPV/promises.mp3", "replace", {"replaygain-fallback": "20.0", "force-window": "yes"}]}

The 20.0 has to be a string, because the internal type is a string dict, not native option types. (Which is a shortcoming of the "loadfile" command.)

**Comment by 00SteinsGate00** [comment]
Works, thanks a ton for the quick response!
