### ISSUE TITLE
use sparkle updater for macOS updates

### ISSUE THREAD

**Issue by foss-** [mpv-player/mpv#5776]
mpv all versions / macOS

Currently there is no way macOS users are notified of new releases. Please implement sparkle updates to offer users a) getting notified and b) having a simply way to update mpv.

Sparkle is here: https://github.com/sparkle-project/Sparkle

**Comment by Akemi** [comment]
we have no official builds, so no.

**Comment by Argon-** [comment]
To clarify: mpv (this project here) does neither offer official builds nor host binaries, so what you desire isn't even possible.
You need to ask the people that made your built for that. The place where you downloaded your mpv.

**Comment by foss-** [comment]
thanks for the info. just in case others stumple upon this issue: https://github.com/lhc70000/iina is opensource, uses mpv and has an updater.
