### ISSUE TITLE
Black desktop when exiting a full screen video

### ISSUE THREAD

**Issue by Oscar65** [mpv-player/mpv#5778]
Hi

This is the mpv version:

$ mpv --version
mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Wed Feb 14 14:00:12 CET 2018
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.2

This is the kernel version of archlinux:
$ uname -r
4.16.4-1-ARCH

### Reproduction steps
1-Play a video
2-Press the f key
3-Wait some time
4-Press q key

### Expected behavior
Exit and see correctly the desktop like MPlayer SVN-r38017 (C) 2000-2018 MPlayer Team.

### Actual behavior
When I play a video maximized in GNOME 3 or openbox and exit with q key the desktop goes black and the monitor goes sleep. This issue happens sometimes. This issue does not happen with mplayer.

### Log file
https://0x0.st/s1HX.log

### Sample files
Any video

Regards
Oscar

**Comment by wm4** [comment]
Try `--vo=vdpau,xv`

**Comment by Oscar65** [comment]
It looks that `--vo=vdpau,xv` solve this issue in my PC.

**Comment by wm4** [comment]
This proves that it's an issue with your GL drivers or compositor.

**Comment by Oscar65** [comment]
Then I will close this issue, thanks.

**Comment by roundoutandabout** [comment]
Worth mentioning that the same issue happens on Nvidia driver version 470.74 with G-Sync enabled.
Apparently there is some bug in Nvidia driver.
