### ISSUE TITLE
Can't exit fullscreen mode when "no-borde" option is used in Ubuntu 18.04LTS(Gnome)

### ISSUE THREAD

**Issue by mozhs** [mpv-player/mpv#5783]
### mpv version and platform
I'm using Ubuntu 18.04LTS, but **not** the latest release version, since the newest version can't  be found in my `apt source`. I don't want to install lost of dependencies to compile it, sorry.

I had read commit descriptions of latest release version, but don't get any usage fixed points about this bug, so **I think this problem is caused by Gnome3**.

Just report an issue...

```bash
# mpv --version 
mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.2-2

# uname -a
Linux mozhos 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# cat /usr/share/gnome/gnome-version.xml 
<?xml version="1.0" encoding="UTF-8"?>
<gnome-version>
 <platform>3</platform>
 <minor>28</minor>
 <micro>1</micro>
 <distributor>Ubuntu</distributor>
 
</gnome-version>%

```

### Expected behavior
Get normally behaviors like Ubuntu 16.04LTS do, after use `no-border` option in `~/.config/mpv/mpv.conf`.

### Actual behavior
Player run in fullscreen mode and **can't exit fullscreen mode**

**Comment by mc4man** [comment]
Well you semi-ignored the issue template so while I don't use gnome-shell nor that version of mpv,
If you're using xorg then your problem is local
If you're using wayland then  there certainly could be issues with that old version of mpv with the combo of  fs & no-border options.
In any event not a mpv or gnome(3) bug

**Comment by Akemi** [comment]
please open a new issue, use an up to date mpv and fill out the issue template properly (log file) in the case the issue still persist.
