### ISSUE TITLE
Crackles with ao_pulse after commit 66810c1

### ISSUE THREAD

**Issue by daschiller** [mpv-player/mpv#5794]
### mpv version and platform

Debian Stretch (built using mpv-build helper scripts)

mpv 0.28.0-UNKNOWN Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Wed May  2 21:27:16 UTC 2018
ffmpeg library versions:
   libavutil       56.18.100
   libavcodec      58.19.100
   libavformat     58.13.100
   libswscale      5.2.100
   libavfilter     7.21.100
   libswresample   3.2.100
ffmpeg version: 3.4.git

### Reproduction steps

Play any audio using pulse AO and USB DAC as sink.

### Expected behavior

Crackle-free, smooth audio (as with the old default of 250 ms buffer). Manually setting the buffer with --pulse-buffer=250, fixes the issue completely.

### Actual behavior

Crackles, drop outs. This could very well just happen with my particular combination of hardware, but https://github.com/mpv-player/mpv/issues/5751 seems to suggest that others have similar problems.

**Comment by jeeb** [comment]
It would be interesting to get some stats on when you start getting underruns, as well as what sort of PA configuration/version is being utilized. I mean, if it's not limited to mpv (as @cmdrkotori seems to hint at) then it might be a problem with how PA gets configured, but it would still be interesting to see how large buffers you tend to require with various devices.

**Comment by daschiller** [comment]
Since no one else has the same issue, I'm closing this.
