### ISSUE TITLE
mpv freezes after suspend and uses 100% of a single CPU core

### ISSUE THREAD

**Issue by nick-s-b** [mpv-player/mpv#5796]
### mpv version and platform
_This is the latest git version. Compiled few min before the filing time of this report._

mpv 0.28.0-564-g11289d5238 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.18.100
   libavcodec      58.19.100
   libavformat     58.13.100
   libswscale      5.2.100
   libavfilter     7.21.100
   libswresample   3.2.100
ffmpeg version: N-90936-gdc7a8f7310

Linux n 4.16.6-1-ARCH #1 SMP PREEMPT Wed May 2 17:13:18 EDT 2018 x86_64 GNU/Linux
Nvidia binary driver: 390.48

### Reproduction steps
1) Open a video using mpv and pause it
2) Suspend the machine
3) Wake up
4) Try to play the video

### Expected behavior
Resume play as normal.

### Actual behavior
There is no video. OSD doesn't show up. Occasionally, sound does play if you try to resume play by right-clicking on the `mpv` window. Killing the `mpv` window itself leaves `mpv/vo` process still running and consuming 100% of the CPU core.

I don't know if this is video-driver related but I suspect it could be. Maybe someone else with Nvidia binary can confirm or disprove.

**Comment by Akemi** [comment]
please provide a log file.
