### ISSUE TITLE
Failed to build armv7

### ISSUE THREAD

**Issue by ldwardx** [mpv-player/mpv#5797]
### mpv version and platform
mpv v0.27.2 on macOS 10.13.4 with Xcode 8.3.3:

clang -v output:
```
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode8.3.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
xcode-select -p output:

`/Applications/Xcode8.3.3.app/Contents/Developer`

### Console print error message:
```
../video/out/opengl/gl_headers.h:135:19: error: typedef redefinition with different types ('ptrdiff_t' (aka 'int') vs 'intptr_t' (aka 'long'))
typedef ptrdiff_t GLsizeiptr;
                  ^
/Applications/Xcode8.3.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/gltypes.h:37:18: note: previous definition is here
typedef intptr_t GLsizeiptr;
                 ^
```

In addition, arm64 can be built correctly.

**Comment by CounterPillow** [comment]
During compilation of what mpv source file does it run into this? It looks like there's been some system headers left in accidentally, which conflict with mpv's internal opengl headers.

**Comment by ybma-xbzheng** [comment]
Error when compiling source file video/out/gpu/context.c.
And,git master has the same problem.

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
