### ISSUE TITLE
MPV will cache the whole file instead of respecting the "cache=" configuration

### ISSUE THREAD

**Issue by DrReD** [mpv-player/mpv#5799]
### Description of problem:
When the cache is set >=32kB MPV will cache the whole file instead of respecting the configuration.

### Version-Release:
mpv-0.28.2-4.fc28.x86_64

### How reproducible:
Consistently (at least under mate)

### Steps to Reproduce:
1. put eg. "cache=100" in .config/mpv/mpv.conf
2. open a video with mpv

### Actual results:
the Whole file is cached

### Expected results:
Only 4 megabytes of cache are used

### Log file
Attached as [output.txt](https://github.com/mpv-player/mpv/files/1976473/output.txt)

**Comment by sfan5** [comment]
https://github.com/mpv-player/mpv/issues/5359#issuecomment-355709332
