### ISSUE TITLE
no video display with mpv in windows10

### ISSUE THREAD

**Issue by uNouss** [mpv-player/mpv#5800]
I installed mpv on windows 10 64bits in two different ways but I have the same problem with both.
- from here https://mpv.srsfckn.biz/
- with chocolatey
the video never show up, I just have the audio when I play a video
here are the logs with --no-ytdl and without
### mpv version and platform
- **plateform**: Windows 10 64bits, version 1709
- **mpv-version**:
> mpv 0.28.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon Dec 25 01:09:58 CET 2017
ffmpeg library versions:
   libavutil       56.7.100
   libavcodec      58.8.100
   libavformat     58.3.100
   libswscale      5.0.101
   libavfilter     7.7.100
   libswresample   3.0.101
ffmpeg version: N-89595-g40d4b13228

### Reproduction steps
- Install mpv from https://mpv.srsfckn.biz/  or with chocolatey
- launch mpv like this: `mpv --no-ytdl http://sebsauvage.net/galerie/photos/videos/ublock-killer.mp4` or `mpv http://sebsauvage.net/galerie/photos/videos/ublock-killer.mp4`

### Log file
- `mpv --no-ytdl --log-file=mpv.log STUFF.mp4` -> https://paste.debian.net/1023177/
- `mpv --log-file=mpv.log STUFF.mp4` -> https://paste.debian.net/1023174/

### Sample files
__demo__ https://framadrive.org/s/YXCiXCskgRQr5eL
https://videobin.org/+sbr/x3o.html

**Comment by shinchiro** [comment]
It can play well on my windows10. Using git master and new youtube-dl (2018.05.01).

**Comment by uNouss** [comment]
how can i use git master for mpv ? i don't see any exe file. 
youtube-dl is the latest release.

i have the same issue for remote video or local  video

**Comment by shinchiro** [comment]
You could try using [my build](https://sourceforge.net/projects/mpv-player-windows/files/64bit/) to see whether the problems still persists or not

**Comment by Akemi** [comment]
seems like this is resolved.
