### ISSUE TITLE
target-prim discarded at first key frame

### ISSUE THREAD

**Issue by hofst** [mpv-player/mpv#5802]
### mpv version and platform

mpv-x86_64-20180505-git-11289d5 on windows

### Reproduction steps

- Open bt.2020 video with no further settings on adobeRGB monitor => oversaturated colors
- Open bt.2020 video with "target-prim=adobe" on adobeRGB monitor => colors look normal until first cut (probably until first keyframe). After that the setting appears to be ignored and colors are oversaturated again.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/1977763/log.txt)

**Comment by jeeb** [comment]
Made a binary of git-11289d5238 with additional logging in the shaders, search in logs for "color mapping": [here](https://kuroko.fushizen.eu/mpv_binaries/2018-05-06-mpv-primaries_checking-g11289d5238.7z)

Applied changes:
```diff
diff --git a/video/out/gpu/video_shaders.c b/video/out/gpu/video_shaders.c
index 19fb0ccde8..750071d3a1 100644
--- a/video/out/gpu/video_shaders.c
+++ b/video/out/gpu/video_shaders.c
@@ -758,6 +758,9 @@ void pass_color_map(struct gl_shader_cache *sc,
                     bool gamut_warning, bool is_linear)
 {
     GLSLF("// color mapping\n");
+    GLSLF("// source primaries: %s (%d), destination primaries: %s (%d)\n",
+          m_opt_choice_str(mp_csp_prim_names, src.primaries), src.primaries,
+          m_opt_choice_str(mp_csp_prim_names, dst.primaries), dst.primaries);
 
     // Some operations need access to the video's luma coefficients, so make
     // them available

```

**Comment by hofst** [comment]
Sorry for the late reply - for some reason, I wasn't notified about your comment. Your build doesn't have the problem I had with 11289d5 originally. From looking at your diff, I can't tell if you only added logging or also solved the problem as a side effect..?

**Comment by jeeb** [comment]
That just added logging into the shaders so that you could see what the in/out primaries at that point were. No other code changes.

**Comment by hofst** [comment]
OK, since you compiled the exact same version of mpv, did you maybe compile with a different version of a third party component/compiler/... than your usual nightly builds?

**Comment by ValZapod** [comment]
Is this still a bug?

**Comment by Dudemanguy** [comment]
Not sure if this was actually fixed or not. Closing for now (feel free to reopen if needed).
