### ISSUE TITLE
buffering speed of opening YT 4k 60fps with youtube-dl is too slow

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#5806]
### mpv version and platform
mpv 0.28.0-564-g11289d5238
Windows / Linux 

### Reproduction steps
Play a YT video with 4k 60fps.
For example, use this:
ytdl-format="((bestvideo[vcodec=vp9.2]/bestvideo[vcodec=vp9]/bestvideo)+(bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec=aac]/bestaudio))/best"
with this:
https://www.youtube.com/watch?v=aqz-KE-bpKQ

### Expected behavior
mpv should fill buffers sufficiently.
When the video is actually downloaded with youtube-dl (so not opened in mpv), the download speed here is ~20MB/s. Opened in mpv, it downloads much slower and so just buffers ~12s of data ahead.

### Actual behavior
Unlike playing the video in browser, the buffer doesn't get filled quickly enough and playback usually stalls after about a minute or two.

Since downloading the video with youtube-dl transfers the data much faster, there may be a way to also speed up buffering when playing in mpv?

### Log file
https://pastebin.com/GDR14RaC
(I cut some bloat in the middle)

**Comment by CounterPillow** [comment]
@dnmTX no, this isn't a good place, since that's an entirely separate issue and likely comes down to the python interpreter's atrocious startup times with anything that imports a few modules as youtube-dl does, and probably some of the HTTP request to grab the manifest to then have the URLs to the segments circus that's involved.

**Comment by dnmTX** [comment]
@CounterPillow  sure thing,i'll open a new issue.I was just trying to reduce the clutter.

**Comment by kevinlekiller** [comment]
I'm facing the same issue.

From what I can understand, recently (the past 4 months or so), google has started throttling DASH uploads to clients to ~ 2.38 MiB/s (~20 Mb/s) on 2160p videos (~8 Mb/s for 1080p ?).

If you look at the youtube-dl list of issues or on various subreddits, r/datahoarders for example, you will see people reporting similar issues around the same time (January / February 2018).

youtube-dl has supposedly pushed a fixed a while back, although I've been facing this issue using mpv (compiled myself from the git master branch multiple times a week, with the most recent version of youtube-dl) for months.

As a workaround, I set the cache in mpv very high and let the video buffer for a few minutes on pause every time before watching a video, which is not ideal.

**Comment by rmanne** [comment]
I don't see this mentioned but youtube-dl doesn't have this problem right now, but mpv for some reason still does.

I manually ran `youtube-dl '...'` and it was dling at 100Mbps consistently. Yet when I play with mpv,  it constantly fails to keep up with 2x video playback. So for the time being, I'm solving the problem by just waiting for the whole video to download first, which is not ideal, but it at least works.

**Comment by aufkrawall** [comment]
Yeah, that's exactly what I meant.

**Comment by Hrxn** [comment]
Depends.. youtube-dl has everything integrated that is required for downloading.
So it's a question of the site, and the distribution method, etc.
But for YouTube, in most cases (if not all) youtube-dl does the download and does not utilize ffmpeg here.

**Comment by dnmTX** [comment]
@Hrxn  ok,i see....then coupling youtube-dl with aria2c should solve that problem(based on what you saying).I personally tried and when using youtube-dl+aria2c only(whithout MPV involved) got intense download speeds but there was no difference when using the same scenario with MPV. Further research on my part showed that when youtube-dl is coupled with MPV can not use external downloaders for some reason and this is based on explanation date states that youtube-dl isn't the downloader but just passing the info.

**Comment by tyngdekraften** [comment]
https://github.com/rg3/youtube-dl/commit/e2e18694dbcd5963f2044837af0e566667d14347
https://github.com/rg3/youtube-dl/pull/11476

**Comment by tyngdekraften** [comment]
https://github.com/rg3/youtube-dl/commit/ba515388b8dc608a07b4390b601e227c1fce6fa9

**Comment by wm4** [comment]
Good look trying to get this into lavf's http client.

**Comment by ReekyMarko** [comment]
Sorry to revive an old discussion but I just noticed that when I use [youtube-viewer](https://github.com/trizen/youtube-viewer) (mpv as my video player of course), a 1080p video will start in below 2 seconds, whereas using straight mpv on the same video, it will start in +5 seconds. I guess youtube-viewer is not using youtube-dl then.

**Comment by Hrxn** [comment]
Well, apparently youtube-viewer is Perl, while youtube-dl is Python, so yeah..

**Comment by mc4man** [comment]
Doesn't appear to be an issue anymore, youtube 4k vids buffer quickly here and well ahead of playback.

**Comment by aufkrawall** [comment]
Can confirm this on both Windows and Linux, thus closing.
