### ISSUE TITLE
Please add a proxy parameter 

### ISSUE THREAD

**Issue by StevensNJD4** [mpv-player/mpv#5807]
It is very cumbersome to set an environment variable while programming. It would make more sense and easier for everyone if there was something like `--http-proxy`.

Please consider adding it

**Comment by wiiaboo** [comment]
You can use `--stream-lavf-o=http_proxy=http://proxy` too. If there were an option it'd set the same thing.

**Comment by StevensNJD4** [comment]
Thank you 
Using the latest version on Ubuntu, I get 
$ mpv --stream-lavf-o-append=http_proxy=http://127.0.0.1:8080
Error parsing option stream-lavf-o-append (option not found)
Setting command line option '--stream-lavf-o-append=http_proxy=http://127.0.0.1:8080' failed.

same thing without -append

**Comment by wiiaboo** [comment]
What version is that?

**Comment by 20NE** [comment]
Version: 0.34.0_31_gc478a1efba-1
'''
$ mpv --stream-lavf-o-append=http_proxy=http://127.0.0.1:8080
'''
no error, but doesn't work.

**Comment by Jimmy-Z** [comment]
can confirm `--stream-lavf-o-append=http_proxy=` works for me, on windows
```
mpv 69ced64 Copyright © 2000-2024 mpv/MPlayer/mplayer2 projects
 built on Sep 26 2024 14:51:42
libplacebo version: v7.349.0
FFmpeg version: git-2024-09-26-a3ec1f8
FFmpeg library versions:
   libavcodec      61.20.100
   libavdevice     61.4.100
   libavfilter     10.5.100
   libavformat     61.8.100
   libavutil       59.40.100
   libswresample   5.4.100
   libswscale      8.4.100
```
