### ISSUE TITLE
[youtube-dl] noticeable delay on start up

### ISSUE THREAD

**Issue by dnmTX** [mpv-player/mpv#5808]
### mpv version and platform
mpv 0.28.0-564-g11289d5238 (latest build by @shinchiro+latest youtube-dl 2018.05.01)
Windows 10 x64 1607 LTSB

### Reproduction steps
Playing any video that require youtube-dl
(most of the time the videos are from openload.co and for this domain only "phantomjs.exe" is required also)

### Expected behavior
video to start playing within 1-3 sec.

### Actual behavior
Usually takes up to 10 sec. to start 
(this doesn't include the 5 sec. cache delay that i set up in my conf. file)

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/1980878/log.txt)

### Sample 
https://openload.co/f/-F7EiDZQp08
(the video will not play without "phantomjs.exe" )

**Comment by wiiaboo** [comment]
Well, youtube-dl is taking at least 5.147 seconds to gives us the information. Plus 2-6 seconds for FFmpeg to start opening it.
mpv can't do anything about those, afaik. The rest of the time until playback start is shaders being compiled and the biggest delay on that depends on your VO and gpu-api.

**Comment by dnmTX** [comment]
@wiiaboo  i'm on Windows and therefore using the .exe one.Running youtube-dl with --list-extractors shows all of them so i'm guessing that depend on the site the specific one(extractor) kicks-in or they are just listed and are not in use and if it's the latter i couldn't find any argument in documentation to choose certain extractor.

> mpv can't do anything about those, afaik. The rest of the time until playback start is shaders being compiled and the biggest delay on that depends on your VO and gpu-api
I have no problems on that part,if youtube-dl is not involved the video starts right away,there is not even slight delay.

**Comment by avih** [comment]
> the dependency on phantomjs

I find this hard to believe considering the windows exe is 2.7M after stripping and 900k compressed with 7z.

**Comment by wiiaboo** [comment]
What does size have to do with complexity?

**Comment by avih** [comment]
I wasn't saying it's not complex, just that to me it seems unlikely that it uses phantomjs, considering how small the executable is.

**Comment by bitraid** [comment]
I think the delay is because the javascript phantomjs executes on openload.co, waits for 5 seconds before getting the link (like when clicking the `Download` button on the page).

**Comment by dnmTX** [comment]
Thanks for pitching in guys.About the phantomjs,i had to download it and place it in the same directory as youtube-dl. Is there a better faster alternative that could work with youtube-dl? I assumed that pahntomjs slowing down the whole process but without it it's just not possible to watch anything from openload.co. So far changing the format from bestvideo+bestaudio/best to mp4/best kind of reduced the loading times to about 6-7 sec. or could be just placebo,still researching though.

**Comment by wiiaboo** [comment]
No idea. Ask in youtube-dl, since it's up to them. I just know they require phantomJS for openload.
I'd assume if there were any faster way of doing it they would already be using it. 5 seconds isn't that long anyway. Crunchyroll takes much longer because of the subtitles being encrypted/encoded too, even if you're not going to use them.

**Comment by lachs0r** [comment]
On Tuesday, May 8, 2018 7:29:02 PM CEST Ricardo Constantino wrote:
> No idea. Ask in youtube-dl, since it's up to them. I just know they require
> phantomJS for openload. I'd assume if there were any faster way of doing it
> they would already be using it. 5 seconds isn't that long anyway.
> Crunchyroll takes much longer because of the subtitles being
> encrypted/encoded too, even if you're not going to use them.

Crunchyroll actually only takes that long because their backend/API is slow as 
hell and youtube-dl insists on grabbing more info than is typically needed for 
playback.

**Comment by FadhilAF** [comment]
I do have the same kind of problem, but for me it took 3-4 minute for the log to say `[ytdl_hook] youtube-dl succeeded!`. I have redownloaded mpv, youtube-dl, and even try to change with yt-dlp. Is it my connection? but when the youtube video already playing I can watch the whole video in 1080p without buffering.

**Comment by FadhilAF** [comment]
> I do have the same kind of problem, but for me it took 3-4 minute for the log to say `[ytdl_hook] youtube-dl succeeded!`. I have redownloaded mpv, youtube-dl, and even try to change with yt-dlp. Is it my connection? but when the youtube video already playing I can watch the whole video in 1080p without buffering.

I get the pattern, when this problem will occur. I was trying to play a whole playlist to the play-with-mpv server. Then after I shut off the server and run it again, it take 3-4 minute for a youtube video to start playing. If I wait one video that take 3-4 minute to open and watch the video till the end, that problem is no more.
