### ISSUE TITLE
How to play a playlist with options per file with mpv?

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#5810]
### mpv shinchiro (last version)

Good afternoon, I hope you can help me.
I want to create a file (.txt or .m3u) as a playlist using the "loadlist" command.
By writing the paths of the multimedia files in the file, mpv reproduces it correctly.
My question is, how can I **set different options (such as "start", "end", "vid", etc.) in that playlist file?**
so that when playing it mpv does it automatically.
I read that it can be done with the escape characters "{" but it does not work.
Of course, many thanks and congratulations for this great repoductor!

### Sample files (I leave this example, so that it is better understood to lol that I mean)
[lista de ejemplo.txt](https://github.com/mpv-player/mpv/files/1981125/lista.de.ejemplo.txt)

**Comment by paulguy** [comment]
The --{ and --} per file option brackets are only for the command line.  According to the man page, you'd need to write a script to set a hook for on_load then set file-local-options/<name>.  It doesn't look like there's a way to set mpv options from a playlist other than to just specify everything on the command line to mpv.  Someone more familiar might know an easier solution though.

**Comment by EzeKees** [comment]
hello, thank you very much, but how would I have to do the .conf file?
Inside the file I enter the mpv commands like "--start" and "--end"?
Something like that?

**Comment by EzeKees** [comment]
like, how do I separate different options within the .conf file? by only I can establish an option, when entering several options, mpv takes it as invalid, auqnue I am only separating it with a comma ","

**Comment by lachs0r** [comment]
Sounds like what you want is EDL functionality. See the documentation:

https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst
