### ISSUE TITLE
Can't unbind or rebind default window-scale keybinds on OSX, Cmd+1 Cmd+2 

### ISSUE THREAD

**Issue by hobbldygoop** [mpv-player/mpv#5811]
mpv 0.28.2, OSX 10.13.4 (17E202)

On OSX the CMD+1 and CMD+2 shortcuts set the window-scale to 1 and 2 respectively by default, no matter what I've tried I can't seem to unbind them.

input.config:
```
Alt+1 ignore
Ctrl+1 ignore
Meta+1 ignore
	
Alt+2 ignore
Ctrl+2 ignore
Meta+2 ignore

Alt+2 set window-scale 1.0
Ctrl+2 set window-scale 1.0
Meta+2 set window-scale 1.0

Meta+3 multiply window-scale 0.91
Meta+4 multiply window-scale 1.1
```
When pressing any Cmd+Anything combination it shows it as `Meta` in the verbose output so I'm pretty sure Meta should be OSX's Command key, but just for testing I also ignored Alt and Ctrl but that didn't work either.

Event with disabling all defaults.

`mpv --input-default-bindings=no testfile.ts` 

All the other keybinds are definitely gone after that and it shows `No key binding found for key` for everything else I do after that but just the two CMD+1, CMD+2 keybinds just don't go away, they always work.
The Meta+3 and Meta+4 from my input.conf above also work perfectly when I do Cmd+3 or Cmd+4.

From the man page it seems those are special to OSX, is there any way to unbind them? I've tried mpv installed via macports and self compiled but both act the same.

**Comment by Akemi** [comment]
yeah that is expected. every shortcut used in the menu bar can't be rebound, they are hardcoded. you have to change the `key` value of [these](https://github.com/mpv-player/mpv/blob/master/osdep/macosx_menubar.m#L287-L300) 3 dicts to an empty string and build mpv yourself.

is there any specific use case why you want them unbound?

**Comment by Akemi** [comment]
if you use the bundle something like this will work to unbind the keys:
`defaults write io.mpv NSUserKeyEquivalents -dict-add "Normal Size" "nil"`

you could probably also use karabiner or BetterTouchTool to unbind any shortcut from any App's menu.

**Comment by hobbldygoop** [comment]
No specific use case, just muscle memory from other programs messing me up after switching to mpv and I just couldn't figure out where they were coming from.

The `defaults` work perfectly, thank you for the help!

**Comment by hany** [comment]
I'm facing this issue too. I had an older version of mpv which allowed these keys to be overwritten. I have a custom Lua script that relies on re-binding these keys. I've upgraded to the latest version and found that they are now hardcoded. I use `brew` to install mpv. Are there any other options to allow these keys to be unbound?

**Comment by Akemi** [comment]
i believe the keybindings for those were always hardcoded in the way they are now. so nothing really changed.  

otherwise, with that incomplete info you provide it's really hard to help in any way.

**Comment by Akemi** [comment]
i don't really know what you are doing, but i can't unbind the those keys via input.conf on 0.20 either.

be more specific what you are exactly doing.

**Comment by hany** [comment]
Sorry about that. Basically I'm loading a Lua script which binds several keys to functions. In my case, I bind all the `Meta+<number>` keys to various functions in the script:

```lua
mp.add_key_binding('Meta+1', 'remove-first-tag', function() remove_first_tag( mp.get_property('path') ) end)
mp.add_key_binding('Meta+2', 'remove-second-tag', function() remove_second_tag( mp.get_property('path') ) end)
```

These key bindings worked previously with the older version of MPV, and has been that way for a few years. When upgrading to the latest version of mpv, these particular bindings no longer work and map to the window-scale functions.

Is this enough information?

**Comment by Akemi** [comment]
that doesn't work either with 0.20. my test script:
```
function test_func()
    mp.commandv('show-text', 'test', 2000)
end

mp.add_key_binding('Meta+1', 'test_func1', test_func)
mp.add_key_binding('Meta+3', 'test_func2', test_func)
```

`Meta+3` works, `Meta+1` doesn't. if this works for you then you did something else.

**Comment by hany** [comment]
I may have been mistaken about the exact version of MPV I was running. Looking closer, I was using a `HEAD` version of mpv (via `brew`) from June 2016. My custom key bindings were working 100% with that version (and all previous versions I was using prior).

Besides using different key bindings for my script, do you have any suggestions for ways to make it work with `Meta+1`/`2`?

**Comment by Akemi** [comment]
even the releases before 0.20 and a few after have the exact same code for those bindings. i can only imagine you used what i suggested previously [here](https://github.com/mpv-player/mpv/issues/5811#issuecomment-387675047), changing the binding via `defaults`. i am just going to say it again for the case it was missed, this only works when **used with the bundle**. whether you use it via double click, open with, etc or calling the binary inside the bundle.

what is the reason why you don't use the `defaults` method?

**Comment by hany** [comment]
OK, I have recompiled mpv with `--with-bundle` via `brew`, located the binary, and ran the `defaults` method and can confirm it works! Thanks for your help and sorry for the confusion.

**Comment by vorou** [comment]
`defaults` works for me, but only if launch mpv from the Applications folder. if I run it from the shell the goddamn binding is still there. even though the mpv in the path points to the same executable it looks like:

```
╰─>$ readlink (which mpv)
/Applications/mpv.app/Contents/MacOS/mpv
```

is there a way to get rid of the binding when launching from the shell?
