### ISSUE TITLE
mpv keeps running in background after finishing the file

### ISSUE THREAD

**Issue by orschiro** [mpv-player/mpv#5817]
Dear all, 

Hopefully someone can help me here. I play a file. mpv finishes the playback and closes the main window. 

But it's still running in background as I can see from GNOME Notifications and also the system monitor. 

Can anyone provide me some insights why this is happening?

Thank you! :-)

### mpv version and platform

```
[orschiro@X230 ~]$ mpv --version
mpv 0.28.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0
```

### Reproduction steps

Play a file and let the playback finish.

### Expected behavior

I expect mpv not to remain running in background. 

### Actual behavior

mpv remains running in background. Actually even multiple instances if I launch several different files.

### Log file

https://gist.github.com/orschiro/1d3937254622e327e781c59e3f1cd5c9

### Screenshots

![image](https://user-images.githubusercontent.com/170947/39956470-5641d152-55e1-11e8-811d-df0114c68c85.png)

![image](https://user-images.githubusercontent.com/170947/39956483-9449cb1c-55e1-11e8-99d3-790e76be129d.png)

**Comment by heelsleeh** [comment]
try comment like this
# keep-open=yes
# keep-open=always

**Comment by orschiro** [comment]
Let me try and see if keeping the window open helps!

**Comment by orschiro** [comment]
I am closing this as invalid. I think it's not actually a mpv issue but more related to the [mpris](https://github.com/hoyon/mpv-mpris) script I am using. Now I switched to gnome-mpv and the notifications look unique and well. :-)
