### ISSUE TITLE
[Qt/QML] Compiling for android

### ISSUE THREAD

**Issue by forelabs** [mpv-player/mpv#5825]
Hi there,
the issue I am reporting does not have to do with the player itself,
but with using it within an application. I am not quite sure if this is the right place to ask for,
but maybe you can help me or name a place, where to look for help.

I have written a tiny qt qml application with a browser, where the application communicates whe the mpv player which is part of the qt application. I used the example integration of the player from here: https://github.com/mpv-player/mpv-examples/tree/656341a0f52cc7e7f4404865c63c9339ea05f181/libmpv/qml

Now, this works fine on linu. I am trying to build the same for android right now, but it removes the mpv lib from the PKGCONFIG, so it does not work. 
Is this even possible with the qml application?
It says: "Cross compiling without sysroot. Disabling pkg-config." and next step (because of disabled pkg-config) "mpv development package not found".

I know there is https://github.com/mpv-android/mpv-android, which is based on the default android/java implementation, but we want to have a single code base.
I will also try to reach the qt community, but maybe someone here has already an idea.
Would be great, thanks!

**Comment by davtoro** [comment]
@forelabs 
Hi,
Did you solve this problem? I am thinking too about bundling libmpv with Qt/QML app on Android.

**Comment by ayhan9494** [comment]
Hi,
Did you solve this problem?
