### ISSUE TITLE
Player freezes when playing 3D MVC remux of a bluray, mk3d extension

### ISSUE THREAD

**Issue by shpitz461** [mpv-player/mpv#5830]
### mpv version and platform

Running Windows 7, using Emby Theatre 3.0.0 which uses MPV as its internal player.
Product version of mpv.exe is "0.28.0-401-gb4c6fb0f52"

### Reproduction steps
Playing 3D MVC mk3d file will play great for ~26 minutes, then the player would freeze and have to terminate the app. Tried with several mk3d movies.

### Actual behavior

Movie plays fine in MPC-HC and PowerDVD18. Other 2D bluray remuxes play fine as well. 
Player freezes when playing mk3d 3D MVC file.

I tried using latest nightly build from today but same freezing.

### Log file

The log file produced for a single movie play is 19MB, can't paste it into pastebin.com, so uploaded here:

https://www98.zippyshare.com/v/8zKbsJd8/file.html

This is the mediainfo for the file: https://pastebin.com/N9AP4Xwq

### Sample files

Movie is 26GB, not sure if a sample would be enough?

**Comment by Akemi** [comment]
> The log file produced for a single movie play is 19GB, can't paste it into pastebin.com, so uploaded here:

just on a side note, the log isn't 19GB but 19MB. i reuploaded it [here](https://0x0.st/seSp.log).

**Comment by shpitz461** [comment]
LOL, sorry, yeah, 19MB, not GB :)
The same thing happened with several other mk3d bluray remuxes, playing in 2D in Emby Theatre 3.0.0.

**Comment by wm4** [comment]
There's nothing in the log where it supposedly freezes, so a sample is required. Unless you know how to debug mingw on windows. Also try some git build of mpv.

**Comment by shpitz461** [comment]
It froze almost at the end of the log since I had to kill Emby Theatre.
How do I make a sample from the whole movie?
I tried latest nightly build from 2 days ago and it froze just the same.

**Comment by wm4** [comment]
Also disable hardware decoding.

**Comment by shpitz461** [comment]
Will try without h/w decoding, thanks!

**Comment by shpitz461** [comment]
Tried without h/w decoding, still freezes.
I am working with an Emby team member Doofus, he was able to reproduce the freeze. It happens within MPV.exe executed by Emby Theatre, when played directly in MPV.exe the movie plays fine.
He's investigating further.
Thanks for all the help guys!

**Comment by shpitz461** [comment]
Yeah, I have no idea how they communicate. Should I close the ticket since it's not really mpv's fault?

**Comment by wm4** [comment]
Seems like it actually uses json IPC, which shouldn't really have this problem (even if the other side doesn't read all data correctly). So I don't really know what the issue could be with this little information.

**Comment by shpitz461** [comment]
Yeah, Emby is investigating the issue, so hopefully they'll have a solution in the next few days.
Playing the same file in MPV.exe directly works fine.

**Comment by shpitz461** [comment]
Hi,
here are 2 logs from mpv, playing Kung Fu Panda 3D MVC mk3d:
1. Playing directly on mpv.exe - no issues, movie plays great throughout
2. Playing via Emby Theatre on Windows 7 - movie freezes at the 00:26:25 mark, consistently, also tested by other users.

https://www89.zippyshare.com/v/OHncCaG7/file.html

I noticed the timestamp in the log when the freeze happens increases rapidly while in the 'good' log it says NaN a lot and the timestamp is fairly stable.

Does anything jump out at you?

If anyone is interested, I can upload a 30 minute clip of the movie (10GB), so just let me know where.

**Comment by wm4** [comment]
Can someone upload the logs to a non-scam file hoster like 0x0.st?

**Comment by shpitz461** [comment]
I can upload it anywhere, went to 0x0.st but all I see is some text. How do I upload to 0x0?

**Comment by shpitz461** [comment]
Figured it out, used ShareX to upload to 0x0:

http://0x0.st/sek9.7z

**Comment by wm4** [comment]
It's better to upload them separately, instead of putting them into a .7z.

Anyway, nothing comes to mind. The log just stops.

The not working case plays with hardware decoding from a network drive, so try again with hw decoding disabled and from a local file.

The nan thing in the working case is incredibly suspicious though, and shouldn't happen. Maybe ffmpeg forgot some FPU state reset thing.

**Comment by shpitz461** [comment]
Thanks for looking.
I tried playing with hardware decoding off but it would still freeze at 26:25.
The file is played from same location in both cases, Emby uses the UNC while the direct play was through a shared drive.

**Comment by Doofussy2** [comment]
So here's something. Whether I use hwdec or not, I see this in the log

`[     nan][e][ffmpeg/video] h264: sps_id 1 out of range`

The only time I don't see that, is only if I use cuda-copy (I can't test cuda, as it presently doesn't work, in windows). In Emby Theater, if I use cuda-copy, it plays to the end without issue. 

Here's the section of the log that seems to be the crux

[   0.115][v][vd] Codec list:
[   0.115][v][vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[   0.115][v][vd]     h264_cuvid (h264) - Nvidia CUVID H264 decoder
[   0.115][v][vd] Opening decoder h264
[   0.115][v][vd] Looking at hwdec h264_cuvid-cuda-copy...
[   0.251][v][vd] Trying hardware decoding via h264_cuvid-cuda-copy.
[   0.251][v][vd] Using underlying hw-decoder 'h264_cuvid'
[   0.251][v][vd] Pixel formats supported by decoder: cuda nv12
[   0.251][v][vd] Codec profile: unknown (0xffffff9d)
[   0.251][v][vd] Requesting pixfmt 'cuda' from decoder.
[   0.254][d][ffmpeg/video] h264_cuvid: CUVID capabilities for h264_cuvid:
[   0.254][d][ffmpeg/video] h264_cuvid: 8 bit: supported: 1, min_width: 48, max_width: 4096, min_height: 16, max_height: 4096
[   0.254][d][ffmpeg/video] h264_cuvid: 10 bit: supported: 0, min_width: 0, max_width: 0, min_height: 0, max_height: 0
[   0.254][d][ffmpeg/video] h264_cuvid: 12 bit: supported: 0, min_width: 0, max_width: 0, min_height: 0, max_height: 0
[   0.255][v][vd] Pixel formats supported by decoder: cuda nv12
[   0.255][v][vd] Codec profile: unknown (0xffffff9d)
[   0.255][v][vd] Requesting pixfmt 'cuda' from decoder.
[   0.255][d][ffmpeg/video] h264_cuvid: Formats: Original: cuda | HW: cuda | SW: nv12
[   0.282][v][vd] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)

**Comment by Doofussy2** [comment]
If it's of any interest, here's the thread in the Emby forum that I've been posting the results of my shenanigans

 https://emby.media/community/index.php?/topic/58705-emby-theater-desktop-playback-of-3d-movie-remuxes-mk3d-or-mkv-containers-freezes-after-26-minutes/?p=632290

**Comment by shpitz461** [comment]
I can provide a sample from the movie if anyone cares to test using Emby Theatre for Windows, currently on Theatre v3.0.3.
Running Windows 7 Ultimate with a NUC i5-4250U. The playback just stops after 26 minutes but mpv.exe keeps running. Happens on a consistent basis and can reproduce easily. This happens with many mk3d remuxes that have MVC (2 streams) video tracks. If I rename the file to .mkv the freezing still happens. It's as if mpv.exe encountered an access violation of sorts but nothing shows up on the screen or the log.

**Comment by Akemi** [comment]
if this problem still persists, please open a new issue.
