### ISSUE TITLE
vf changes are not applied until seek

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#5831]
### mpv version and platform

mpv 0.28.0-567-ge5b2af0a80
Linux x86_64

### Reproduction steps

test.lua:
```lua
mp.observe_property("video-dec-params", "native", function()
  mp.command("vf add vflip")
end)
```

* `mpv --no-config --script=test.lua https://0x0.st/seMa.flac`
* observe how cover art is not flipped
* seek anywhere
* cover art is now flipped as expected

### Log file

https://0x0.st/seMB.txt

**Comment by wm4** [comment]
Can you confirm the fix works as intended?

**Comment by sfan5** [comment]
Works.

**Comment by Hrxn** [comment]
(Friendly closing reminder?)

**Comment by sfan5** [comment]
The "referenced this issue" notification is misleading, the fix for this isn't merged yet.

**Comment by Hrxn** [comment]
Okay, then please disregard.
