### ISSUE TITLE
esc. key does not work instantly in console

### ISSUE THREAD

**Issue by Arnaudv6** [mpv-player/mpv#5833]
### mpv 0.27.2 with linux, Xorg
(because 0.28.2 depends on ffmpeg4, which is hard blocked in gentoo)

### Reproduction steps
1. under linux and Xorg, open a terminal (sakura in my case)
2. edit mpv/input.conf to bind an action to ESC in console for instance add this line:
`ESC quit`
3. play a file in console, for instance:
`mpv --no-video file.mp3`
4. press [Esc.] key.

### Expected behavior
This should work. (quit for instance)

### Actual behavior
User has to press [Esc.] twice, or hold it an instant before expected action occurs.
(Due to linux terminals, delaying escape key presses so as to catch special keycodes AFAIK.)

### Log file
https://0x0.st/seuk.txt

**Comment by wm4** [comment]
So this should be fixed now.
