### ISSUE TITLE
waf configure with prefix installs the binary to $PWD$prefix

### ISSUE THREAD

**Issue by shlomif** [mpv-player/mpv#5836]
### mpv version and platform

git master on mageia v7 x86-64

### Reproduction steps

```
waf configure --prefix="/home/shlomif/apps/mpv"
waf
waf install
```

### Expected behavior

`mpv` binary to be installed in `home/shlomif/apps/mpv/bin/mpv`

### Actual behavior

```
+ install /home/shlomif/Download/unpack/multimedia/mpv/mpv/home/shlomif/apps/mpv/bin/mpv (from build/mpv)
```

It otherwise is working fine.

**Comment by qmega** [comment]
it looks like you're using a system-installed version of waf, which doesn't guarantee compatibility across versions, so older *or* newer versions might be a problem. Try `./bootstrap.py` and then use `./waf` instead of `waf`. Works for me. If not, you could probably workaround this particular problem by giving `--destdir=/` to the install command.

**Comment by shlomif** [comment]
On Fri, 18 May 2018 19:44:22 -0700
Philip Sequeira <notifications@github.com> wrote:

> it looks like you're using a system-installed version of waf, which doesn't
> guarantee compatibility across versions, so older *or* newer versions might
> be a problem. Try `./bootstrap.py` and then use `./waf` instead of `waf`.
> Works for me. If not, you could probably workaround this particular problem
> by giving `--destdir=/` to the install command.
> 

I'll try and let you know - thanks! Also:

shlomif@telaviv1:~$ rpm -q waf
waf-2.0.7-1.mga7


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
Buffy Factoids - http://www.shlomifish.org/humour/bits/facts/Buffy/

I also have versions of this code in COBOL.NET, Intercal, PDP‐10 Assembly, J,
APL, Windows NT 4.0 Batch script and Autocad Lisp — I’m sure you can handle
all of them because none of them is Perl. ;-).

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
@qmega : this procedure with `./bootstrap.py` seems to work fine.
