### ISSUE TITLE
load_scripts and script options don't work in a profile

### ISSUE THREAD

**Issue by nickbudi** [mpv-player/mpv#5837]
### mpv version and platform

latest windows build by schinchiro (1b19ba6) on Windows 10 Pro (version 1803)

### Reproduction steps
```
[extension.mp3]
load-scripts=no
script=scriptname.lua
```

### Expected behavior
scripts in ~~/scripts should not be loaded when the profile is active.
scripts specified with the `script` option should be loaded.

### Actual behavior
scripts are still loaded when `load-scripts=no` is in an active profile
scripts aren't loaded when `script=scriptname.lua` is in an active profile

### Log file
```
[   0.019][i][cplayer] Auto-loading profile 'extension.mp3'
[   0.019][d][cplayer] Setting option 'load-scripts' = 'no' (flags = 116)
[   0.019][e][cplayer] Error parsing option scripts-append (option parameter could not be parsed)
```

**Comment by wm4** [comment]
Runtime changes are not supported, profiles are runtime changes.

**Comment by nickbudi** [comment]
Thanks for the quick reply. Besides loading scripts as command line options or using separate configs, is there a better way to achieve loading different scripts per extension?

Is it possible for a script to query the active profile and load another script?

**Comment by wm4** [comment]
You could run a script that loads other scripts with the load-script command.
