### ISSUE TITLE
Autoload Subtitles / mpv + mozplugger / youtube

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#5840]
### mpv version and platform

mpv via PPA, kubuntu 14.04.01

### Reproduction steps

am trying to autoplay subtitles via mpv on youtube using mozplugger

can you please show how to implement autoloading of embedded subtitles ?

i can play video thanks to this guide

https://wiki.archlinux.org/index.php/Browser_plugins#MozPlugger

but it would not load subtitles.

### Log file
rich@rich-desktop:~$ mpv -v
[cplayer] Command line options: '-v'
[cplayer] mpv baead23-amended (C) 2000-2017 mpv/MPlayer/mplayer2 projects       
[cplayer]  built on Sat Aug 19 03:38:56 UTC 2017                                
[cplayer] ffmpeg library versions:                                              
[cplayer]    libavutil       55.69.101                                          
[cplayer]    libavcodec      57.102.100                                         
[cplayer]    libavformat     57.76.100                                          
[cplayer]    libswscale      4.7.101                                            
[cplayer]    libavfilter     6.97.100                                           
[cplayer]    libswresample   2.8.100                                            
[cplayer] ffmpeg version: git-2017-08-04-44e9783                                
[cplayer]                                                                       
[cplayer] Configuration: ./waf configure --enable-pdf-build --enable-dvbin --enable-dvdread --enable-dvdnav --prefix=/usr --confdir=/etc/mpv                    
[cplayer] List of enabled features: 52deb alsa asm atomics avutil-content-light-level avutil-icc-profile avutil-imgcpy-uc build-date cplayer cplugins cuda-hwaccel debug-build drm dvbin dvdnav dvdread dvdread-common egl-helpers egl-x11 encoding fchmod gl gl-x11 glibc-thread-name glob glob-posix gnuc iconv is_ffmpeg jack jpeg lcms2 libass libass-osd libav libavcodec libavdevice libbluray libdl libm librt linux-fstatfs lua nanosleep optimize oss-audio posix posix-or-mingw posix-spawn pthreads pulse rubberband shm termios uchardet vaapi vaapi-egl vaapi-glx vaapi-hwaccel vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel vt.h x11 xv zlib                                                                            
[global] config path: '' -> '/home/rich/.config/mpv'                            
[global] config path: 'encoding-profiles.conf' -/-> '/home/rich/.config/mpv/encoding-profiles.conf'                                                             
[global] config path: 'encoding-profiles.conf' -/-> '/home/rich/.mpv/encoding-profiles.conf'                                                                    
[global] config path: 'encoding-profiles.conf' -> '/etc/mpv/encoding-profiles.conf'                                                                             
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf                   
[global] config path: 'mpv.conf' -/-> '/home/rich/.config/mpv/mpv.conf'         
[global] config path: 'config' -/-> '/home/rich/.config/mpv/config'             
[global] config path: 'mpv.conf' -/-> '/home/rich/.mpv/mpv.conf'                
[global] config path: 'config' -/-> '/home/rich/.mpv/config'                    
[global] config path: 'mpv.conf' -/-> '/etc/mpv/mpv.conf'                       
[global] config path: 'config' -/-> '/etc/mpv/config'                           
[cplayer] Setting option 'v' = '' (flags = 8)                                   
[global] config path: 'input.conf' -/-> '/home/rich/.config/mpv/input.conf'     
[global] config path: 'input.conf' -/-> '/home/rich/.mpv/input.conf'            
[global] config path: 'input.conf' -/-> '/etc/mpv/input.conf'                   
[osc] Loading lua script @osc.lua...                                            
[global] config path: 'scripts' -/-> '/home/rich/.config/mpv/scripts'           
[global] config path: 'scripts' -/-> '/home/rich/.mpv/scripts'                  
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'                         
[osc] loading mp.defaults                                                       
[osc] loading @osc.lua                                                          
[global] config path: 'lua-settings/osc.conf' -/-> '/home/rich/.config/mpv/lua-settings/osc.conf'                                                               
[global] config path: 'lua-settings/osc.conf' -/-> '/home/rich/.mpv/lua-settings/osc.conf'                                                                      
[global] config path: 'lua-settings/osc.conf' -/-> '/etc/mpv/lua-settings/osc.conf'                                                                             
[osc] lua-settings/osc.conf not found.                                          
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1                                                     
[cplayer] mouse_leave script-binding osc/__keybinding2                          
[cplayer] , force]                                                              
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]                                                            
[cplayer] Run command: define-section, flags=0, args=[input, mouse_btn0 script-binding osc/__keybinding3                                                        
[cplayer] shift+mouse_btn0 script-binding osc/__keybinding4                     
[cplayer] mouse_btn2 script-binding osc/__keybinding5                           
[cplayer] mouse_btn3 script-binding osc/__keybinding6                           
[cplayer] mouse_btn4 script-binding osc/__keybinding7                           
[cplayer] axis_up script-binding osc/__keybinding8                              
[cplayer] axis_down script-binding osc/__keybinding9                            
[cplayer] mouse_btn0_dbl ignore                                                 
[cplayer] shift+mouse_btn0_dbl ignore                                           
[cplayer] mouse_btn2_dbl ignore                                                 
[cplayer] , force]                                                              
[cplayer] Run command: enable-section, flags=0, args=[input, ]                  
[cplayer] Run command: define-section, flags=0, args=[input_osc, del script-binding osc/__keybinding10                                                          
[cplayer] , default]                                                            
[cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]                                                           
[cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]                                                    
[cplayer] Done loading @osc.lua.                                                
[ytdl_hook] Loading lua script @ytdl_hook.lua...                                
[global] config path: 'scripts' -/-> '/home/rich/.config/mpv/scripts'           
[global] config path: 'scripts' -/-> '/home/rich/.mpv/scripts'                  
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'                         
[ytdl_hook] loading mp.defaults                                                 
[cplayer] Run command: disable-section, flags=0, args=[input]                   
[global] config path: 'fonts' -/-> '/home/rich/.config/mpv/fonts'               
[global] config path: 'fonts' -/-> '/home/rich/.mpv/fonts'                      
[global] config path: 'fonts' -/-> '/etc/mpv/fonts'                             
[osd/libass] Shaper: FriBidi 0.19.6 (SIMPLE) HarfBuzz-ng 0.9.27 (COMPLEX)       
[global] config path: 'subfont.ttf' -/-> '/home/rich/.config/mpv/subfont.ttf'   
[global] config path: 'subfont.ttf' -/-> '/home/rich/.mpv/subfont.ttf'          
[global] config path: 'subfont.ttf' -/-> '/etc/mpv/subfont.ttf'                 
[global] config path: 'fonts.conf' -/-> '/home/rich/.config/mpv/fonts.conf'     
[global] config path: 'fonts.conf' -/-> '/home/rich/.mpv/fonts.conf'            
[global] config path: 'fonts.conf' -/-> '/etc/mpv/fonts.conf'                   
[osd/libass] Setting up fonts...                                                
[ytdl_hook] loading @ytdl_hook.lua                                              
[global] config path: 'lua-settings/ytdl_hook.conf' -/-> '/home/rich/.config/mpv/lua-settings/ytdl_hook.conf'
[global] config path: 'lua-settings/ytdl_hook.conf' -/-> '/home/rich/.mpv/lua-settings/ytdl_hook.conf'
[global] config path: 'lua-settings/ytdl_hook.conf' -/-> '/etc/mpv/lua-settings/ytdl_hook.conf'
[ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]
[cplayer] Run command: hook-add, flags=0, args=[on_preloaded, 2, 10]
[cplayer] Done loading @ytdl_hook.lua.
[cplayer] mpv baead23-amended (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sat Aug 19 03:38:56 UTC 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       55.69.101
[cplayer]    libavcodec      57.102.100
[cplayer]    libavformat     57.76.100
[cplayer]    libswscale      4.7.101
[cplayer]    libavfilter     6.97.100
[cplayer]    libswresample   2.8.100
[cplayer] ffmpeg version: git-2017-08-04-44e9783
[cplayer] 
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer] 
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer] 
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer] 
[ytdl_hook] Exiting...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osc] Exiting...
### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by mrkapqa** [comment]
whenever i toggle "j" on youtube, it would say "no subtitles"

![bildschirmfoto1](https://user-images.githubusercontent.com/12947465/40246849-9e58b990-5aca-11e8-99eb-77f024fff09c.png)

**Comment by wiiaboo** [comment]
What if you open the URL in mpv instead?
Try updating mpv and ffmpeg. Those builds are almost a year old.
What's youtube-dl's version? If it's not the latest version from pip, it's too old.

**Comment by mrkapqa** [comment]
Yes, then it works, but i would like to load the subtitles also when the video is embedded, somehow, if possible.
When i got through mpv --list options   the subtitle options seem to refer to files being loaded like .mkv or .mp4 and have not found options related to streams.

**Comment by mrkapqa** [comment]
On the other hand, when i would use "mplayer"  via gecko-mediplayer plugins, it would say "subtitles visible" but not load them (comment not related to mozplugger, though)

**Comment by mrkapqa** [comment]
Trusty via PPA Mpv-Tests
gives   2:0.28.0+git2~trusty1 

https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests?field.series_filter=trusty

**Comment by wm4** [comment]
Stop wasting our time if you don't want to give the information we asked for.

**Comment by mrkapqa** [comment]
sorry am back on wheezy, will tell you later should i get the info.

**Comment by wiiaboo** [comment]
Maybe mozplugger is just broken or passing the wrong arguments to mpv? If it works with plain mpv, then it's not a mpv problem.

**Comment by wiiaboo** [comment]
Why are you now using an even older mpv? The youtube-dl version is fine.

**Comment by mrkapqa** [comment]
Zitat von Ricardo Constantino <notifications@github.com>:

> Why are you now using an even older mpv? The youtube-dl version is fine.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/mpv-player/mpv/issues/5840#issuecomment-390474152


jessie features only such version i think, and mpv-test is PPA only  
for ubuntu, it seems.

only option on debian is to use deb-multimedia backports for newer mpv  
on jessie, or compile itself.

**Comment by wiiaboo** [comment]
Well, why don't you compile it yourself then? First thing you should've read when opening an issue is that we don't support anything but the latest version or git master. Distro build get supported by the distros.

**Comment by jeeb** [comment]
Also Mozplugger will be dead soon enough ([August 28th](https://blog.mozilla.org/futurereleases/2018/01/11/announcing-esr60-policy-engine/)), please try to figure out something different for yourself. As ESR 52 dies, NPAPI will do so with it.

**Comment by mrkapqa** [comment]
Thank you wilaboo, i did not know that. Thank you all for your help. Has been interesting.
