### ISSUE TITLE
[feature request] please add option for vo fallback to gpu rather than to software-only.

### ISSUE THREAD

**Issue by enihcam** [mpv-player/mpv#5841]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
There are some cases that VAAPI/VDPAU do not support larger resolution (e.g. 4K/8K);
There are some cases that VAAPI/VDPAU do not support HEVC.
In these cases, vo=vaapi/vdpau will fallback to software-only, which is too aggressive. Per my test, vo=gpu still has better performance than software-only.

### Expected behavior
vo=vaapi/vdpau fallback to vo=gpu

### Actual behavior
vo=vaapi/vdpau fallback to software-only

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by lachs0r** [comment]
Append the other VOs to try with a `,`, e.g. `--vo=vdpau,gpu`. Also, gpu is *always* the preferred VO, even if you want to use hardware decoding. You should not use the other ones unless you’re absolutely sure you have to.
