### ISSUE TITLE
PLAYPAUSE media key not recognized

### ISSUE THREAD

**Issue by desbma** [mpv-player/mpv#5843]
### mpv version and platform

Version 0.28.2, Arch Linux x64 up to date.

### Reproduction steps

Run `mpv --input-test --idle`, focus mpv window, hit [`PLAYPAUSE`](https://github.com/mpv-player/mpv/blob/v0.28.2/etc/input.conf#L130) media key.

### Expected behavior

A line shows the key stroke was detected.

### Actual behavior

No event is shown.

Note that other media keys like `HOMEPAGE` generate an event as expected.

My keyboard has nothing fancy and is a cheap Logitech K200.

**Comment by wm4** [comment]
Depends on his entire desktop configuration, which the didn't provide. Most likely some shitty desktop daemon catches it.

**Comment by desbma** [comment]
I'm using Cinnamon 3.8.2 as a desktop environment.

The Clementine audio player has no issue handling this key. MPV fails to catch it even if no other application is running.

**Comment by wm4** [comment]
Clementine won't get that key either. Instead it'll use that one shitty dbus API. mpv won't use dbus, unless there's a dbus client API that's not ridiculous trash.

**Comment by wm4** [comment]
Also here's an unsupported third-party plugin to provide said shitty dbus API (that your DE is most likely using): https://github.com/hoyon/mpv-mpris

This still won't let you make a direct key binding, because the DE never gives us the actual key input.

**Comment by desbma** [comment]
`mpv-mpris` mostly does what I wanted, thanks.
Not as clean as a proper key binding, but that works.

You seem to be very "passionate" about DBus, I don't know much about the internals but isn't it required to pass special key to application not having focus?

**Comment by haasn** [comment]
> Most likely some shitty desktop daemon catches it.

For the record, `xev` can be used to test this. If `xev` doesn't see it, mpv won't either.

**Comment by Akemi** [comment]
if this is still an issue please open a new issue.
