### ISSUE TITLE
Beside gpu-hq, please create (or recommend here) a profile for battery saver.

### ISSUE THREAD

**Issue by enihcam** [mpv-player/mpv#5845]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
MPV on laptop/phone/mobile devices with battery only.

### Expected behavior
A profile optimized for longer battery life.

### Actual behavior
no such profile

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by haasn** [comment]
The default settings (i.e. no gpu-hq) are already optimized for performance (= power savings). Or do you have an example of a specific setting that you'd expect to be present?

**Comment by enihcam** [comment]
For example:
```
vd-lavc-fast
vd-lavc-skiploopfilter=all
no-embeddedfonts
sub-ass-shaper=simple
sub-auto=fuzzy

```

**Comment by medhefgo** [comment]
Probably the best one could do for battery saving (profile) is to use hardware decoding.

**Comment by dnmTX** [comment]
@enihcam  you know you can create your own profile and load it whenever you want,and it will be customized for your needs.For example(in conf. file):
at the end of conf.file:
[my-profile]
vd-lavc-fast
vd-lavc-skiploopfilter=all
no-embeddedfonts
at the beginning of conf. file:
profile=my-profile

**Comment by haasn** [comment]
Not sure what those subtitle settings are supposed to accomplish, but yeah, I guess `vd-lavc-fast` and `vd-lavc-skiploopfilter=all` are two ways to improve performance at the cost of quality. That being said, I'm not sure if those two alone are enough to justify a profile - especially given that users of these options should at the very least be aware of the consequences of enabling them. (Potentially ruining the picture, especially for e.g. non-4:2:0).

But yeah, for battery lifetime using zero-copy hwdec is probably going to be beneficial - and less damaging than the vd-lavc options you proposed. If anything, we should set `hwdec=auto` in that case, but now we've reduced it down to a single option.

Perhaps a FAQ entry would be better than a profile?

**Comment by aufkrawall** [comment]
d3d11va-zero-copy=yes definitely helps by huge margins on my x5-Z8300 Atom. I never had any problems with it, but the last time I checked, it was only faster on Intel and AMD. On Nvidia, it showed higher CPU load instead (driver not doing shit natively?).

**Comment by wiiaboo** [comment]
```
[lowpower]
hwdec=auto
deband=no
glsl-shaders-clr
interpolation=no
vd-lavc-dr=yes
```
is what I use on my ultrabook, but I've never measured power draws.

**Comment by Dudemanguy** [comment]
The question appears to have been answered.
