### ISSUE TITLE
Cache in mpv 0.28.2 is unlimited? by default, consumes arbitrary amounts of ram

### ISSUE THREAD

**Issue by xpue** [mpv-player/mpv#5847]
Most noticeable on long youtube streams. With default settings cache bloats to gigabytes very fast. Funniest thing is, my internet is fast enough, mpv works fine with cache disabled. No need to waste so much ram.

Same happens on linux and windows.

**Comment by sfan5** [comment]
see https://github.com/mpv-player/mpv/issues/5359#issuecomment-355709332

**Comment by xpue** [comment]
Memory consumed without need, profit and reason is wasted memory, stolen from other apps and system.

**Comment by haasn** [comment]
> Memory consumed without need, profit and reason is wasted memory, stolen from other apps and system.

I agree.

From your log, what I noticed is that there are like 40,000 lines of matroska demuxing output. That seems highly suspect, and would be the first thing I'd investigate in order to figure out where these gigabytes of RAM went. @wm4 probably knows more about this.

**Comment by wm4** [comment]
That seems to be roughly 1 GB of cache. With the default settings and 2 streams that's an expected value. The default size was reduced in mpv git. the excessive Matroska logging is @haasn's fault, but was fixed in git master.

> mpv works fine with disabled cache. 

Then disable it, how much of an idiot are you?
