### ISSUE TITLE
Shift+TAB not working on mpv window, on Linux

### ISSUE THREAD

**Issue by TheAMM** [mpv-player/mpv#5849]
### mpv version and platform
```
mpv 0.28.0-562-g7d8eee3 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Thu May  3 01:38:48 EEST 2018
ffmpeg library versions:
   libavutil       56.15.100
   libavcodec      58.19.100
   libavformat     58.13.100
   libswscale      5.2.100
   libavfilter     7.18.100
   libswresample   3.2.100
ffmpeg version: N-90776-gfbfee6a
```
On Ubuntu (`Ubuntu 14.04.5 LTS`, yes, old), with lightdm or gnome or whatever the desktop is called. IRC also confirmed the same for an xfce desktop and Linux Mint Cinnamon.
### Reproduction steps
Open mpv with `mpv --idle --input-test --force-window`, press Shift+TAB (with focus on the mpv window)
### Expected behavior
Console prints
```
[input] Key Shift+TAB is bound to:
[input] (nothing)
```
### Actual behavior
Nothing is logged in the console. `TAB` works, `Ctrl+TAB` works, but `Shift+TAB` will not show.
Focusing on the terminal and pressing `Shift+TAB` *will* work, but focusing the window won't.
### Log file
https://0x0.st/s2-P.log (the `TAB` presses are plain `TAB` presses, to show that key events are handled at all)

**Comment by wm4** [comment]
I don't think X11 even has a way to signal whether a key was "consumed" or not. WMs either have to grab keys globally, or accept the facts that applications get them when their window is focused.

**Comment by wm4** [comment]
Nevermind, I confused something. Can reproduce.

**Comment by TheAMM** [comment]
Forgot to mention that `xev` does display the events (shift-down, TAB-down, TAB-up, shift-up)
```
KeyPress event, serial 37, synthetic NO, window 0x3e00001,
    root 0xc0, subw 0x0, time 863492285, (-17,506), root:(795,558),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 37, synthetic NO, window 0x3e00001,
    root 0xc0, subw 0x0, time 863492898, (-17,506), root:(795,558),
    state 0x1, keycode 23 (keysym 0xfe20, ISO_Left_Tab), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3e00001,
    root 0xc0, subw 0x0, time 863493007, (-17,506), root:(795,558),
    state 0x1, keycode 23 (keysym 0xfe20, ISO_Left_Tab), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x3e00001,
    root 0xc0, subw 0x0, time 863493630, (-17,506), root:(795,558),
    state 0x1, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Although the keysym is different from what plain TAB and Ctrl+TAB show:
```
KeyRelease event, serial 37, synthetic NO, window 0x3e00001,
    root 0xc0, subw 0x0, time 863670464, (-577,366), root:(235,418),
    state 0x4, keycode 23 (keysym 0xff09, Tab), same_screen YES,
    XLookupString gives 1 bytes: (09) "	"
    XFilterEvent returns: False
```

**Comment by wm4** [comment]
Yeah, I looked at xev output too.

**Comment by haasn** [comment]
```
λ xmodmap -pk | grep Tab
     23    	0xff09 (Tab)	0xfe20 (ISO_Left_Tab)	0xff09 (Tab)	0xfe20 (ISO_Left_Tab)	
```

God only knows why xmodmap binds shift+tab to a different tab (?) by default, but that does mean a work-around exists:

```
λ xmodmap -e 'keycode  23 = Tab Tab Tab Tab'
λ mpv --input-test --force-window --itle
     input: Key Shift+TAB is bound to:
     input: (nothing)
```

(Seems like a proper solution would be teaching mpv that ISO_Left_Tab = Tab, obviously)
