### ISSUE TITLE
Feature Request: multiple titles on command line

### ISSUE THREAD

**Issue by elitak** [mpv-player/mpv#5858]
Currently (v0.28.2), I can pass multiple `--title="my title"` arguments on the command line, but only the last applies, and to the entire window, forever. What I'd like is a way to invoke e.g. `mpv file1.mp4 --title="file1's title" file2.mp4 --title="file2's title"`, indefinitely. It's possible I've missed the trick for doing this.

I realize this could probably be done with ad-hoc playlists, but I think being able to construct simple file:title pairs on the command line would be very useful.

**Comment by Akemi** [comment]
should be doable by per file options like:
`mpv --\{ file1.mkv --title="Title 1" --\} --\{ file2.mkv --title="Title 2" --\}`

**Comment by elitak** [comment]
That works. I missed the per-file stuff in the manpage, sorry. Thanks very much for the quick tip.
