### ISSUE TITLE
Right seek pausing

### ISSUE THREAD

**Issue by undport** [mpv-player/mpv#5859]
### mpv version and platform
mpv-0.28.2 macOS

### Reproduction steps
Right seek 5 seconds

### Expected behavior
move 5 seconds ahead in video file and play continuously 

### Actual behavior
move 5 seconds ahead in video file pause for 0.5 seconds and play 

### Log file
https://www.file.io/404.html

### Sample files
https://my.mixtape.moe/tglbus.mkv

**Comment by j605** [comment]
Your log is a link to 404 page.
