### ISSUE TITLE
Some bug with subtitles 

### ISSUE THREAD

**Issue by weebo221** [mpv-player/mpv#5864]
### mpv version and platform
2017-12-25 Build 64bit, Windows 10 professional

### Reproduction steps
Just opened the video with my own subs from .ass file
### Expected behavior
subs on the bottom should look like this https://prnt.sc/jn8v4o
### Actual behavior
actually in mpv it look like this https://prnt.sc/jn8w1r

**Comment by wiiaboo** [comment]
Why are you using a build from last year?

**Comment by weebo221** [comment]
I thought that's the newset https://prnt.sc/jn91ld  ;-;

**Comment by wiiaboo** [comment]
I'd forgotten that was the last release done. But screenshots don't really help anything. Sample .ass files would be much more useful.

Try with VLC. If it's the same there, it's a libass compatibility issue.

**Comment by weebo221** [comment]
I checked and vlc have the same problem.

**Comment by wiiaboo** [comment]
This is right place to inquire about that issue then: https://github.com/libass/libass/issues

**Comment by Akemi** [comment]
related to #5715.
