### ISSUE TITLE
vulkan: VK_NV_glsl_shader deprecated in Nvidia Vulkan drivers

### ISSUE THREAD

**Issue by sl1pkn07** [mpv-player/mpv#5867]
Hi

Seems VK_NV_glsl_shader extension is now deprecated in the Nvidia Vulkan drivers, and in the near future, in the official drivers

Upstream: https://devtalk.nvidia.com/default/topic/1035880/linux/vulkan-396-24-02-and-older-missing-vk_nv_glsl_shader

greetings

**Comment by wm4** [comment]
Support for the extension was removed from mpv.
