### ISSUE TITLE
mpv >= 0.28 : Severe freeze if open without --player-operation-mode=pseudo-gui from file manager.

### ISSUE THREAD

**Issue by z0z0z** [mpv-player/mpv#5876]
## mpv version and platform
Arch, mpv 0.28.2, ffmpeg 4.0, AMDGGPU/mesa, Openbox

### Reproduction steps
Run mpv with terminal=yes, happens on Openbox but possibly many other window managers or systems effected.

### Actual behavior
Open some files, it might happen the first file you open, it might not, it seems completely random. The type of file or individual file you choose seems to have no relevance. But it will happen after a few files.

It completely freezes Xorg. You have to either ctrl+a+f2 to a tty and pkill -u <user>, or reboot your machine.

I've never had this happen until an update to mpv 0.28, 

There was no kernel or mesa or xorg upgrade, or anything else relevant, it happened directly after this ffmpeg/mpv update.

I've opened thousands of files with terminal=yes before this mpv update, with no problem.

I must have had my desktop freeze a hundred times, while changing my mpv settings and trying to figure out what was wrong.

### Log file
N/A

There was amazingly nothing relevant in the log file.

**Comment by sfan5** [comment]
Have you tested git master?

**Comment by lachs0r** [comment]
Most likely one of mpv’s parent processes (file manager → WM/whatever manages your session) is at fault because that’s what gets the terminal spam and redirects it god knows where. Can’t be mpv’s fault. Openbox is a likely candidate. Could also be rare undefined behavior in the graphics stack.

**Comment by oltodosel** [comment]
I have the same problem on Openbox. Narrowed it down to the option _terminal_
terminal=yes # freezes sometimes
terminal=no # does not

**Comment by oltodosel** [comment]
It happens in >= 0.28, the same as @z0z0z has stated.

**Comment by sfan5** [comment]
My question wasn't whether it works in 0.27.0, I'm asking you to find out if 8977fe5ed9d73dd56441d5071a0c2732636e7be3 causes this bug.

**Comment by oltodosel** [comment]
Tested.
Yes, it also causes Xorg to freeze.

**Comment by z0z0z** [comment]
Glad to see someone else is speaking up.

Since I have posted this, I have also long since narrowed it down to mpv's terminal option.

**Comment by sfan5** [comment]
Is this even a bug?

`player-operation-mode=pseudo-gui` implies `terminal=no`, I assume it does so for a reason.
What do you expect to be fixed when the solution to "using \<X> when it shouldn't be used causes \<Y> to freeze" is "don't use \<X>"?

**Comment by z0z0z** [comment]
You're saying that mpv shouldn't have terminal output unless you want Xorg to freeze, and that's not a bug to you?

It didn't used to happen in mpv, after mpv update it does, apparently after that commit.

**Comment by z0z0z** [comment]
How many people do you think have been, or will be effected by this bug, but never find out how to "workaround" it?

They don't know to check github issues, might not search the right keywords, etc. Do you realize how hard it is to experience this bug and then find out on your own what is causing it?

I'm not convinced that the code in that mpv commit was implemented correctly. If you can prove that this mpv code is correctly implemented, and any other system that conflicts with it are just wrong, that'd be a different story.

**Comment by Dudemanguy** [comment]
Very old issue that may or may not still occur and mpv probably wasn't at fault in the first place.
