### ISSUE TITLE
youtube-dl.exe error on Windows — streaming fails

### ISSUE THREAD

**Issue by Warblefly** [mpv-player/mpv#5881]
### mpv version and platform

Latest Git master, on Windows 10 64 bit build 17682, cross-compiled with gcc-7.3.0 from MinGW, 3rd June 2018

### Reproduction steps

Attempt to play a YouTube video, with latest nightly youtube-dl.exe installed, but it fails.
E.G: 
`mpv  -v --msg-level=all=trace https://www.youtube.com/watch?v=XOacA3RYrXk`
### Expected behavior

This used to work perfectly.

### Actual behavior

Program can't open the stream, claiming that youtube-dl.exe can't be executed (see log).
The program youtube-dl.exe from its own website is in place, and can be executed normally i.e. when I run it by copying-and-pasting the command line from mpv's debug log below, the program correctly returns the stream URLs for mpv to play.

### Log file

```
...
[cplayer] Opening failed or was aborted: ytdl://https://www.youtube.com/watch?v=XOacA3RYrXk
[global] config path: 'fonts' -/-> 'C:\Users\john\AppData\Roaming/mpv/fonts'
[cplayer] Running hook: ytdl_hook/on_load_fail
[global] config path: 'fonts' -/-> 'C:/Program Files/ffmpeg/bin/fonts'
[global] config path: 'youtube-dl.exe' -> 'C:\Users\john\AppData\Roaming/mpv/youtube-dl.exe'
[ytdl_hook] found youtube-dl at: C:\Users\john\AppData\Roaming/mpv/youtube-dl.exe
[global] config path: 'fonts' -/-> 'C:/Program Files/ffmpeg/bin/mpv/fonts'
[ytdl_hook] Running: C:\Users\john\AppData\Roaming\mpv\youtube-dl.exe --no-warnings -J --flat-playlist --sub-format ass/srt/best --format bestvideo+bestaudio/best --all-subs --no-playlist -- https://www.youtube.com/watch?v=XOacA3RYrXk
[osd/libass] Raster: FreeType 2.9.1
[ytdl_hook] youtube-dl failed: not found or not enough permissions
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE)
[osd/libass] Initialized
[cplayer] finished playback, loading failed (reason 4)
[cplayer]
[cplayer]
[cplayer] Exiting... (Errors when loading file)
...
```

**Comment by dnmTX** [comment]
Link plays fine here with the latest youtube-dl (218-06-04) and mpv (latest shinchiro's build).
Windows 10 x64 Enterprise LTSB. It's just showing some weird error in console:

[ffmpeg/demuxer] hls,applehttp: keepalive request failed for 'https://r6---sn-q4f7sn7l.googlevideo.com/videoplayback/id/XOacA3RYrXk.4/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/cmbypass/yes/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/r6---sn-q4f7sn7l.googlevideo.com/ei/WkkUW7rkNYrNNoO3uZgP/gcr/us/playlist_type/DVR/initcwndbps/12040/mm/32/mn/sn-q4f7sn7l/ms/lv/mv/m/pl/16/keepalive/yes/mt/1528056081/disable_polymer/true/ip/70.119.252.169/ipbits/0/expire/1528077755/sparams/ip,ipbits,expire,id,itag,source,requiressl,ratebypass,live,cmbypass,goi,sgoap,sgovp,hls_chunk_host,ei,gcr,playlist_type,initcwndbps,mm,mn,ms,mv,pl/signature/43AF5C47835491DBE1461CE4139FF58000C2885F.98FE2B60858BC07B18A1BE6AA9C1DB25927B42B3/key/dg_yt0/playlist/index.m3u8/sq/191489/goap/clen%3D81238%3Blmt%3D1528056550199743/govp/clen%3D1474997%3Blmt%3D1528056550199743/dur/5.000/file/seg.ts', retrying with new connection: I/O error

**Comment by Smithy3** [comment]
Install https://www.microsoft.com/en-US/download/details.aspx?id=5555 and see if it fixes the problem.
