### ISSUE TITLE
Moving Away from Github

### ISSUE THREAD

**Issue by Hyleus** [mpv-player/mpv#5883]
Could it be considered to move to an alternative platform? With the recent news of Microsoft acquiring Github, I believe MPV should also consider moving to a different platform, which is FOSS, like the Gitlab software and isn't harmful in general like Microsoft.

Gitlab is probably growing now due to these news.

**Comment by Akemi** [comment]
since nothing 'harmful' happened yet and don't see a reason for moving. i am closing this since to me it just seems like generalised microsoft 'hate'.

**Comment by CounterPillow** [comment]
QUICK GUYS LET'S KNEE-JERK

**Comment by Hyleus** [comment]
I know you all have your own opinions, it was just a friendly suggestion. No need to get so worked up about it. I just thought FOSS projects would like the idea on being hosted on a platform that is itself FOSS.

**Comment by recruit-jp** [comment]
Plus one for this. Definitely it should be moved.

**Comment by avoidr** [comment]
Yes, it should be moved away from microsoft. The bad thing that will happen is that they're going to profit off this platform, and then use that money to harm freedom. Do you want to be responsible for that?

**Comment by Hrxn** [comment]
QUICK THEY'RE TAKING AWAY OUR FREEDOM

**Comment by CounterPillow** [comment]
>The bad thing that will happen is that they're going to profit off this platform, and then use that money to harm freedom. Do you want to be responsible for that?

mpv has already "harmed freedom" by moving from GPL to LGPL, we're basically Hitler at this point.

**Comment by avoidr** [comment]
We seem to not have a common ground for discussion. I'll try and clarify.

What is free software? — The Free Software Definition: http://www.gnu.org/philosophy/free-sw.html
>The four essential freedoms
>
>A program is free software if the program's users have the four essential freedoms: [1]
>
>- The freedom to run the program as you wish, for any purpose (freedom 0).
>- The freedom to study how the program works, and change it so it does your computing as you wish (freedom 1). Access to the source code is a precondition for this.
>- The freedom to redistribute copies so you can help others (freedom 2).
>- The freedom to distribute copies of your modified versions to others (freedom 3). By doing this you can give the whole community a chance to benefit from your changes. Access to the source code is a precondition for this.

There is no issue with the LGPL freedom-wise; both the GPL and LGPL give the user the four essential freedoms, therefore making mpv—and any other program licensed that way—free software.

Free software is about community values. It's about sharing, helping each other, and working on a common goal, for the good of the community. Those values are what makes us human.

Microsoft on the other hand opposes those values completely. Here is how:
http://stallman.org/microsoft.html
http://www.gnu.org/proprietary/malware-microsoft.html

I hope this helps clear up any confusion/misconception on that topic, and that it helps future communication to be more efficient.

**Comment by Argon-** [comment]
How would MS profit from this platform? IIRC Github was never profitable as a company. They were constantly dependent on investors and were actually running out of those - a chance MS took to acquire them.
This is more of a PR stunt, if you ask me.

**Comment by CounterPillow** [comment]
I believe it's time to lock this before the software vegans start burning churches.

**Comment by avoidr** [comment]
QUICK GUYS LET'S LOCK THIS BEFORE HE COMES BACK WITH REAL ARGUMENTS

**Comment by lachs0r** [comment]
There are no plans to transition to anything else right now, but we are ready for self-hosting in case shit hits the fan.
