### ISSUE TITLE
[vo/gpu/vulkan] vkEnumeratePhysicalDevices(vk->inst, &num, NULL): VK_ERROR_INITIALIZATION_FAILED when trying out vulkan

### ISSUE THREAD

**Issue by qutetemp** [mpv-player/mpv#5884]
### mpv version and platform
https://www.archlinux.org/packages/community/x86_64/mpv/
mpv 0.28.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon May 14 09:49:30 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0

### Reproduction steps
- use this config file http://0x0.st/s_cV.conf and try playing anything

### Expected behavior
- mpv running using vaapi and vulkan

### Actual behavior
 - mpv outputs this error https://pastebin.com/raw/nMQdEGJx

### Log file
http://0x0.st/s_c4.txt

### Sample files
I got the the log by using this video for example:

https://m.youtube.com/watch?v=QcdqGbJN0wM&itct=CDcQpDAYBCITCIT-95W6utsCFZfuVQod9IwHkjILYzQtdmlkZW9zLXVaGFVDLWxISlpSM0dxeG0yNF9WZF9BSjVZdw%3D%3D&client=mv-google&hl=en&gl=US

The url is like this because I force m.youtube.com on my machine.
I would also like to specify that I'm using the modesetting intel driver.

**Comment by haasn** [comment]
Does `vulkaninfo` work? If no, not an mpv bug.

**Comment by qutetemp** [comment]
I don't have vulkaninfo

**Comment by qutetemp** [comment]
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.73

/build/vulkan-loader-layers/src/Vulkan-LoaderAndValidationLayers-sdk-1.1.73.0/demos/vulkaninfo.c:3141: failed with VK_ERROR_INITIALIZATION_FAILED

Ignore the previous comment.
What should I do form here ?
