### ISSUE TITLE
No regular flag equivalent of --no-audio-display

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#5886]
Typing out --no-audio-display is pretty long, especially given how often I use this flag. And looking in the man page, there's no regular one-letter flag equivalent. This makes mpv not as ergonomic to use as it could be.
Being able to type something like
mpv -n file.mp3
would be nice.  The letter n is available, among many others.

**Comment by paulguy** [comment]
Might be useful but in the mean time you could do something like in your config file
```
[extension.mp3]
audio-display=no
```
or just setting the flag globally.

**Comment by lxbarbosa** [comment]
What about aliasing it? `player = 'mpv --no-audio-display'` :D

**Comment by wm4** [comment]
An alias is the way to go for such things. mpv doesn't have short options.
