### ISSUE TITLE
Subtitle stays on screen for too long

### ISSUE THREAD

**Issue by whoinoi** [mpv-player/mpv#5887]
### mpv version and platform

v0.28.2
macOS 10.13.5

### Reproduction steps

Take a movie with subtitles and take a scene where there is a conversational part and then a quiet part. During the conversation switch from "no subtitles" to "subtitle" and then back to "no subtitle". When the conversation is over and the quiet part is playing, switch again to "subtitle".

### Expected behavior

There should be no subtitle text visible since the part is quiet.

### Actual behavior

The subtitle text from when the subtitle was turned off the last time during the conversation part is visible. The subtitle text stays visible until a new conversational part begins and updates the subtitle text.

This issue was first submitted [here](https://github.com/lhc70000/iina/issues/1716) for IINA. Also the issue has appeared only recently (1-2 months) and wasn't present in earlier releases (I know this because I've used IINA since before and it didn't always have this problem).

**Comment by Akemi** [comment]
i can't reproduce that with the most recent version. neither with text subs nor with image subs. you need to provide more info, at least a log and a sample file.

**Comment by whoinoi** [comment]
@Akemi [Here](https://streamable.com/bmrvi) is a screencast demonstrating the bug.

Ignore the second subtitle `#2` and focus only on no subtitle `#0` and subtitle `#1`. Also in this clip there is no one speaking if his mouth is not visible, which makes it easy to see when subtitles should be shown and when not. I cycle through the subtitles using a keyboard shortcut in IINA.

I started the movie with no subtitle `#0` switched on and then activated `#1`. In the middle of the conversation I switched back to `#0`. After the conversation is over (when she walks off) I switched on `#1` again and it showed the last text that was displayed when it was switched off. Switching subtitles on and off again doesn't help as you can see when I repeatedly switch from `#0` to `#1`.

Logs for the sequence from the screencast: [mpv.log](https://github.com/mpv-player/mpv/files/2108093/mpv.log)
Sample file: [sample.mkv](https://mega.nz/#!T7ZRBSBZ!NmTe5taGGnLjJOmOZc01xjXplWrBTpHtVmwPO-LUba8)

**Comment by Akemi** [comment]
thx, i can reproduce your problem with that file.

**Comment by Dudemanguy** [comment]
The sample seems to be dead now. Is this still a problem?

**Comment by Dudemanguy** [comment]
Please open a new issue if this is still a problem on 0.36.
