### ISSUE TITLE
Slow memory leak with streamlink and Twitch

### ISSUE THREAD

**Issue by bennyhillthebest** [mpv-player/mpv#5889]
### Log file https://0x0.st/s_u3.txt

The log file talks about a "slow/stuck network connection" but on this occasion i made sure that the stream would not freeze or stop because of low cache, so i'm not sure what is the reason of this warning.

**Comment by CounterPillow** [comment]
are you sure this isn't just the backwards cache filling?

**Comment by bennyhillthebest** [comment]
On this instance the mpv RAM usage went from 100 megabytes to 280 megabytes, but i saw it other times going even to 600 megabytes. To me it looks exactly like a memory leak.

**Comment by j605** [comment]
Like @CounterPillow said, it is possibly just cache settings. Try with the mpv-git which has smaller cache defaults.

**Comment by bennyhillthebest** [comment]
You're right, with `demuxer-max-back-bytes` and `demuxer-max-bytes` the RAM usage at some point becomes constant. 

But i tried as a value for the two options 10 megabytes at 360p (which should be good considering that the incoming cache uses at maximum 1-2 megabytes at 360p) and the final RAM usage was still 270 megabytes. 

Limiting (and by a lot) the cache definitely helped, but in the end not that much. I'm kinda disappointed with this behaviour, because on local files mpv is great.
