### ISSUE TITLE
[ao/alsa] Device underrun detected

### ISSUE THREAD

**Issue by orbea** [mpv-player/mpv#5891]
### mpv version and platform

OS: `Slackware64-current`
mpv commit: bca5951
ffmpeg commit: https://github.com/FFmpeg/FFmpeg/commit/318d0fcbfe5637013342d53d44bb7ea8867fb4d0

### Reproduction steps

1. mpv --ao alsa https://angellore.bandcamp.com/album/la-litanie-des-cendres
2. Skip to about 10 seconds before the first track ends and wait for the next track to start.
3. It should print `[ao/alsa] Device underrun detected.` as the next track starts.
4. Note this will not happen if you directly skip to the next track and seems to occur with any bandcamp link. I have not seen it with local content.

### Expected behavior

It should not experience a device underrun with alsa.

### Actual behavior

It will prints the follow warning when starting the next track on the playlist, but not when skipping directly to the next track.
```
[ao/alsa] Device underrun detected.
```

I bisected this to the following commit.
```
9ee9313465ca49f2cfdd407797febed7692e1144 is the first bad commit
commit 9ee9313465ca49f2cfdd407797febed7692e1144
Author: wm4 <wm4@nowhere>
Date:   Thu Apr 12 17:30:31 2018 +0200

    ao_alsa: actually report underruns to user
    
    Print them as a warning.
    
    Note that there may be some cases where it underruns, without being a
    bad condition. This could possibly happen e.g. if the last chunk is
    written, and then it resumes playback some time after that. Eventually I
    want to add more code to avoid such spurious warnings.

:040000 040000 9ddf00115a92c6d748e5b3a7886e13ed31901ab0 28e6c323ef90222e4b73e14c5abdcc0022d8b6fc M	audio
```
9ee9313465ca49f2cfdd407797febed7692e1144

It looks like this commit did not introduce the issue so much as it actually started to warn about it.

### Log file

https://0x0.st/s_S4.txt

For the other alsa errors see issue https://github.com/mpv-player/mpv/issues/5890.

### Sample files

This bandcamp link will reproduce it.
https://angellore.bandcamp.com/album/la-litanie-des-cendres

**Comment by orbea** [comment]
Another way to reproduce this underrun.

1. When playing a video, press `Ctrl+Z` in the terminal to suspend mpv.
2. Now type `fg` in the same terminal to resume mpv.
3. Mpv will print an underrun.

**Comment by orbea** [comment]
With the current master and reaching the end of file or when being suspended mpv will now print
```
[ao/alsa] ALSA XRUN hit, attempting to recover...
```
When being suspended and not a local file such as the bandcamp example link it will also print.
```
[ao/alsa] Audio device reports unaligned available buffer size.
```
or
```
[ao/alsa] Device underrun detected.
```

**Comment by orbea** [comment]
I further asked about this in #alsa and received this reply.
```
16:31 <debianuser> orbea: "This issue is still current though
https://github.com/mpv-player/mpv/issues/5891 " -- hm... it says "Another way to reproduce
this underrun: press Ctrl+Z to suspend mpv, type fg to resume mpv", and... well... it's
expected! I mean you're _expected_ to get XRUN in any audio app, if you suspend/resume it.
It's not a fatal error, of course, but it's expected, it's not a bug.
16:32 <debianuser> (Getting XRUN when switching between tracks is not expected, however, but
it's up to the application if it's a bug or not. And in any case the app must not crash when
XRUN happens, it)
16:33 <debianuser> (..., it's supposed to resume automatically and continue working)
```

**Comment by porsager** [comment]
I've been experiencing this with an [icecast mp3 stream](http://live-icy.gslb01.dr.dk:80/A/A05H.mp3). The sound will begin chopping up in a continuous loop until I exit mpv. 
```
```

**Comment by orbea** [comment]
This video also consistently reproduces XRUN and underrun messages during the last few seconds.
```
$ mpv https://www.youtube.com/watch?v=8hlEShsDl3U
Playing: https://www.youtube.com/watch?v=8hlEShsDl3U
 (+) Video --vid=1 (*) (h264 1280x720 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) 'DASH audio' (opus 2ch 48000Hz) (external)
AO: [alsa] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 => 1280x799 yuv420p
AV: 00:05:16 / 00:05:20 (98%) A-V:  0.075 DS: 2.000/1 Cache:  3s+208KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:16 / 00:05:20 (98%) A-V: -0.006 DS: 2.000/1 Dropped: 1 Cache:  3s+196KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:16 / 00:05:20 (98%) A-V: -0.069 DS: 2.000/1 Dropped: 1 Cache:  3s+195KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:16 / 00:05:20 (98%) A-V:  0.253 DS: 2.020/2 Dropped: 1 Cache:  3s+191KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:16 / 00:05:20 (98%) A-V:  0.154 DS: 2.000/2 Dropped: 2 Cache:  3s+181KB
[ao/alsa] Device underrun detected.
AV: 00:05:16 / 00:05:20 (98%) A-V:  0.119 DS: 1.980/2 Dropped: 3 Cache:  3s+179KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:16 / 00:05:20 (98%) A-V:  0.026 DS: 1.960/2 Dropped: 4 Cache:  3s+178KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (98%) A-V:  0.005 DS: 1.950/2 Dropped: 5 Cache:  3s+167KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (98%) A-V: -0.051 DS: 1.950/2 Dropped: 5 Cache:  3s+166KB
[ao/alsa] ALSA XRUN hit, attempting to recover...

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:05:17 / 00:05:20 (98%) A-V:  0.904 Dropped: 6 Cache:  3s+153KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (98%) A-V:  1.010 Dropped: 6 Cache:  2s+150KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (98%) A-V:  1.081 Dropped: 7 Cache:  2s+145KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  1.238 Dropped: 8 Cache:  2s+135KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  1.309 Dropped: 8 Cache:  2s+134KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  1.471 Dropped: 9 Cache:  2s+126KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  1.538 Dropped: 9 Cache:  2s+119KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  1.644 Dropped: 9 Cache:  2s+116KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  1.716 Dropped: 10 Cache:  2s+111KB
[ao/alsa] Device underrun detected.
AV: 00:05:17 / 00:05:20 (99%) A-V:  1.769 Dropped: 10 Cache:  2s+110KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  1.842 Dropped: 11 Cache:  2s+109KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  1.893 Dropped: 11 Cache:  2s+105KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  1.967 Dropped: 12 Cache:  2s+100KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  2.076 Dropped: 12 Cache:  2s+97KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  2.143 Dropped: 13 Cache:  2s+93KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  2.196 Dropped: 13 Cache:  2s+92KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:17 / 00:05:20 (99%) A-V:  2.269 Dropped: 14 Cache:  2s+91KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:19 / 00:05:20 (99%) A-V:  0.000 Dropped: 45 Cache:  1s+28KB
[ao/alsa] ALSA XRUN hit, attempting to recover...
AV: 00:05:20 / 00:05:20 (99%) A-V:  0.000 Dropped: 45 Cache:  0s


Exiting... (End of file)
```

**Comment by jeeb** [comment]
Unfortunately I cannot repro it so you'll have to take a poke at my now-rebased [extra logging spam branch](https://github.com/jeeb/mpv/commits/alsa_fixups_with_extra_logging_sauce) with a log file (`--log-file=mpv_sucks.log` or so). I additionally recommend setting start time at something like the 5 min point (`--start=300`) so you don't have too much stuff to plow through.

For the record, what I tested with was `mpv --msg-level=ao=debug --ao=alsa --audio-device=alsa/front --start=300 --log-file=margherita2.log 'https://www.youtube.com/watch?v=8hlEShsDl3U'` and youtube-dl seemed to pick an H.264 video track as well as an opus audio track (which seems to match your case).

**Comment by orbea** [comment]
I built your `alsa_fixups_with_extra_logging_sauce` and tested the video with `--start=315` since the issue only occurs at the very end. Here is the resulting log.

https://0x0.st/sYtj.log

**Comment by jeeb** [comment]
Thanks. Seems like we're doing the waiting game here too. Given that `5120 / 48000 ~= 0.10666...` there's quite some points there where we wait for almost 0.20 seconds to push the following samples in.

We will have to look at where the synchronization started going awry, or just see if we can make a pull-based ALSA output in which we just read our buffer when ALSA requests it, as opposed to feeding it periodically.

**Comment by jeeb** [comment]
Poking the ALSA buffering parameters can most likely help work around the spamming, but this is indeed a bug within mpv one way or another. I just made it really visible (together with the default buffer size downsizing by wm4). :)

**Comment by jeeb** [comment]
For the record, this is how on my system ALSA ao gets configured.

It uses 4800 sample buffers with a 9600 sample soft-buffer. 
```
[ao] Trying audio driver 'alsa'
[ao] Using preferred device 'front'
[ao/alsa] requested format: 48000 Hz, stereo channels, floatp
[ao/alsa] using ALSA version: 1.1.6
[ao/alsa] opening device 'front'
[ao/alsa] PCM setup:
[ao/alsa] ---
[ao/alsa] Soft volume PCM
[ao/alsa] Control: PCM Playback Volume
[ao/alsa] min_dB: -51
[ao/alsa] max_dB: 0
[ao/alsa] resolution: 256
[ao/alsa] Slave: Hardware PCM card 0 'HDA Intel PCH' device 0 subdevice 0
[ao/alsa] ---
[ao/alsa] Start HW params:
[ao/alsa] ---
[ao/alsa] ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
[ao/alsa] FORMAT:  S16_LE S32_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: [16 32]
[ao/alsa] FRAME_BITS: [32 128]
[ao/alsa] CHANNELS: [2 4]
[ao/alsa] RATE: [44100 192000]
[ao/alsa] PERIOD_TIME: (41 11888617)
[ao/alsa] PERIOD_SIZE: [8 524288]
[ao/alsa] PERIOD_BYTES: [32 8388608]
[ao/alsa] PERIODS: [2 32]
[ao/alsa] BUFFER_TIME: (83 23777234)
[ao/alsa] BUFFER_SIZE: [16 1048576]
[ao/alsa] BUFFER_BYTES: [64 16777216]
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] HW params after rate:
[ao/alsa] ---
[ao/alsa] ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
[ao/alsa] FORMAT:  S16_LE S32_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: [16 32]
[ao/alsa] FRAME_BITS: [32 128]
[ao/alsa] CHANNELS: [2 4]
[ao/alsa] RATE: [44100 192000]
[ao/alsa] PERIOD_TIME: (41 11888617)
[ao/alsa] PERIOD_SIZE: [8 524288]
[ao/alsa] PERIOD_BYTES: [32 8388608]
[ao/alsa] PERIODS: [2 32]
[ao/alsa] BUFFER_TIME: (83 23777234)
[ao/alsa] BUFFER_SIZE: [16 1048576]
[ao/alsa] BUFFER_BYTES: [64 16777216]
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] HW params after access:
[ao/alsa] ---
[ao/alsa] ACCESS:  RW_INTERLEAVED
[ao/alsa] FORMAT:  S16_LE S32_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: [16 32]
[ao/alsa] FRAME_BITS: [32 128]
[ao/alsa] CHANNELS: [2 4]
[ao/alsa] RATE: [44100 192000]
[ao/alsa] PERIOD_TIME: (41 11888617)
[ao/alsa] PERIOD_SIZE: [8 524288]
[ao/alsa] PERIOD_BYTES: [32 8388608]
[ao/alsa] PERIODS: [2 32]
[ao/alsa] BUFFER_TIME: (83 23777234)
[ao/alsa] BUFFER_SIZE: [16 1048576]
[ao/alsa] BUFFER_BYTES: [64 16777216]
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] trying format float/14
[ao/alsa] trying format double/16
[ao/alsa] trying format s32/10
[ao/alsa] HW params after format:
[ao/alsa] ---
[ao/alsa] ACCESS:  RW_INTERLEAVED
[ao/alsa] FORMAT:  S32_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: 32
[ao/alsa] FRAME_BITS: [64 128]
[ao/alsa] CHANNELS: [2 4]
[ao/alsa] RATE: [44100 192000]
[ao/alsa] PERIOD_TIME: (41 5944309)
[ao/alsa] PERIOD_SIZE: [8 262144]
[ao/alsa] PERIOD_BYTES: [64 4194304]
[ao/alsa] PERIODS: [2 32]
[ao/alsa] BUFFER_TIME: (83 11888617)
[ao/alsa] BUFFER_SIZE: [16 524288]
[ao/alsa] BUFFER_BYTES: [128 8388608]
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] HW params after channels:
[ao/alsa] ---
[ao/alsa] ACCESS:  RW_INTERLEAVED
[ao/alsa] FORMAT:  S32_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: 32
[ao/alsa] FRAME_BITS: 64
[ao/alsa] CHANNELS: 2
[ao/alsa] RATE: [44100 192000]
[ao/alsa] PERIOD_TIME: (83 5944309)
[ao/alsa] PERIOD_SIZE: [16 262144]
[ao/alsa] PERIOD_BYTES: [128 2097152]
[ao/alsa] PERIODS: [2 32]
[ao/alsa] BUFFER_TIME: (166 11888617)
[ao/alsa] BUFFER_SIZE: [32 524288]
[ao/alsa] BUFFER_BYTES: [256 4194304]
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] HW params after rate-2:
[ao/alsa] ---
[ao/alsa] ACCESS:  RW_INTERLEAVED
[ao/alsa] FORMAT:  S32_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: 32
[ao/alsa] FRAME_BITS: 64
[ao/alsa] CHANNELS: 2
[ao/alsa] RATE: 48000
[ao/alsa] PERIOD_TIME: (333 5461334)
[ao/alsa] PERIOD_SIZE: [16 262144]
[ao/alsa] PERIOD_BYTES: [128 2097152]
[ao/alsa] PERIODS: [2 32]
[ao/alsa] BUFFER_TIME: (666 10922667)
[ao/alsa] BUFFER_SIZE: [32 524288]
[ao/alsa] BUFFER_BYTES: [256 4194304]
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] Going to set final HW params:
[ao/alsa] ---
[ao/alsa] ACCESS:  RW_INTERLEAVED
[ao/alsa] FORMAT:  S32_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: 32
[ao/alsa] FRAME_BITS: 64
[ao/alsa] CHANNELS: 2
[ao/alsa] RATE: 48000
[ao/alsa] PERIOD_TIME: 25000
[ao/alsa] PERIOD_SIZE: 1200
[ao/alsa] PERIOD_BYTES: 9600
[ao/alsa] PERIODS: 4
[ao/alsa] BUFFER_TIME: 100000
[ao/alsa] BUFFER_SIZE: 4800
[ao/alsa] BUFFER_BYTES: 38400
[ao/alsa] TICK_TIME: ALL
[ao/alsa] ---
[ao/alsa] Final HW params:
[ao/alsa] ---
[ao/alsa] ACCESS:  RW_INTERLEAVED
[ao/alsa] FORMAT:  S32_LE
[ao/alsa] SUBFORMAT:  STD
[ao/alsa] SAMPLE_BITS: 32
[ao/alsa] FRAME_BITS: 64
[ao/alsa] CHANNELS: 2
[ao/alsa] RATE: 48000
[ao/alsa] PERIOD_TIME: 25000
[ao/alsa] PERIOD_SIZE: 1200
[ao/alsa] PERIOD_BYTES: 9600
[ao/alsa] PERIODS: 4
[ao/alsa] BUFFER_TIME: 100000
[ao/alsa] BUFFER_SIZE: 4800
[ao/alsa] BUFFER_BYTES: 38400
[ao/alsa] TICK_TIME: 0
[ao/alsa] ---
[ao/alsa] channel map reported by ALSA: FL FR
[ao/alsa] which we understand as: stereo
[ao/alsa] which is what we requested.
[ao/alsa] hw pausing supported: yes
[ao/alsa] buffersize: 4800 samples
[ao/alsa] period size: 1200 samples
[ao/alsa] device buffer: 4800 samples.
[ao/alsa] using soft-buffer of 9600 samples.
AO: [alsa] 48000Hz stereo 2ch s32
```

**Comment by rogerxxxx** [comment]
Getting this bug using a WEWS news stream, at each commercial break.  Upon resuming after commericals, video continues but audio is silent.

AV: 00:02:13 / 26:06:30 (0%) A-V: -0.000 Cache: 1.1s/132KB                                                                                                                                         
Invalid audio PTS: 133.504000 -> 93988.846656                                                                                                                                                      
                                                                                                                                                                                                   
Audio/Video desynchronisation detected! Possible reasons include too slow                                                                                                                          
hardware, temporary CPU spikes, broken drivers, and broken files. Audio                                                                                                                            
position will not match to the video (see A-V status field).                                                                                                                                       
                                                                                                                                                                                                   
AV: 00:02:13 / 26:06:30 (0%) A-V:93855.343 Cache: 1.1s/130KB                                                                                                                                       
Reset playback due to audio timestamp reset.                                                                                                                                                       
(...) AV: 00:00:00 / 26:06:30 (0%) A-V:  0.000 Cache: 0.1s/39KB                                                                                                                                    
[ao/alsa] Device underrun detected.                                                                                                                                                                
AV: 26:06:34 / 26:06:37 (99%) A-V: -0.000 Cache: 3.2s/306KB

**Comment by wm4** [comment]
That is unrelated. The timestamp reset (which are vile, and mpv handles them badly... maybe for most HLS streams, and if ffmpeg didn't suck (cc @richardpl) and propagated the discontinuity marker, it could be handled better, but in general you could always concatenate some ts files and have a mess) resets decoding and probably discards some audio, which of course leads to an audio underrun.

**Comment by philipl** [comment]
I made a fix in ffmpeg to mark the hls demuxer as one that can produce discontinuities (like the mpeg ts demuxer is marked) and this helps a bit. But it still doesn't propagate markers, and it turns out that propagating markers is really hard because the hls demuxer constructs an mpegts stream by concatenation and passes that to the mpegts demuxer to handle. And as the discontinuity markers in hls are not actual mpegts packets, they get lost. We'd need to inject synthetic markers into the new mpegts stream to preserve the semantics. I decided I had better things to do with my time at that point. But try with a new enough ffmpeg with my change. It might help.

**Comment by wm4** [comment]
That will probably trigger weird heuristics in mpv that shouldn't be triggered with hls...

**Comment by philipl** [comment]
I did some testing when I made the change and the heuristics helped.

**Comment by orbea** [comment]
I can no longer reproduce this maybe after the recent changes to the bandcamp site which broke youtube-dl (Still broken) as reproduced using the yt-dlc fork which has a fix for bandcamp.

**Comment by ilf** [comment]
@orbea: You did report the issue, with bandcamp. But others here have reproduced this issue, with other sites than bandcamp, too. Are you sure it's your call to close this now? Best

**Comment by orbea** [comment]
@ilf The icecast stream plays fine for me, but the youtube video (https://www.youtube.com/watch?v=8hlEShsDl3U) still shows issues in the last few seconds. As this is an isolated case maybe the video is broken?

Do you know any other examples?

**Comment by ilf** [comment]
@orbea: I don't recall where I ran into this (this issue is over two years old afterall), but I have experienced this somewhere other than Bandcamp or YouTube, likely without streaming via HTTP(S) at all. Maybe others know their examples?

**Comment by Igetin** [comment]
Just dropping by quickly to say that I’ve encountered this with both local files and HLS streams with recent-ish versions of mpv. Don’t have any examples right now.

**Comment by antonl05** [comment]
this happens frquently in termux; maybe its depended on the device and os?
