### ISSUE TITLE
autoload: ts file extension not included in EXTENSIONS array

### ISSUE THREAD

**Issue by Samillion** [mpv-player/mpv#5895]
I needed an extensions array for a small script I was making and I remembered autoload.lua has one in there, however, I noticed that the ts file extension wasn't included.

Was the reason for exclusion that it isn't a popular extension used in video libraries and downloads?

**Comment by wiiaboo** [comment]
You can just add it, it's not a built-in script.

**Comment by Samillion** [comment]
Thanks. I was just curious if there was a reason it wasn't added, as I mentioned.

Closing.

**Comment by Samillion** [comment]
Thank you very much for the answer.
