### ISSUE TITLE
cache-file doesn't work as expected with live streams

### ISSUE THREAD

**Issue by wjtk4444** [mpv-player/mpv#5897]
### mpv version and platform
git master, windows

### youtube-dl version and platform
git master, windows

### Reproduction steps
mpv.conf:
`cache-file=path/to/myfile.ext`

case 1:
-start mpv
-open an youtube url leading to uploaded video

case2:
-start mpv
-open a twitch url leading to live stream

### Expected behavior
case 1:
`myfile.ext` contains the video

case 2:
`myfile.ext` contains the livestream

### Actual behavior
Case 1 works as expected, `myfile.ext` grows as video is being downloaded (buffered). 
Case 2 creates an (empty? several kilobytes in size) file. Seeking back is available only in backbuffer cache.

### Log file
--

### Sample files
https://www.youtube.com/
https://www.twitch.tv/

### Other notes

I have noticed that `cache-file` property is being ignored if `cache=no` is used. I don't see any reason for `demuxer-max-bytes` to not be 0 in this case, both in forward and back directions. The only issue would be the disappearance of "cache bar" on osd. 
Currently, as a workaround to both `cache-file` not working with network streams and the fact that I would like to know how much of the video/livestream is buffered, I use the following profile:
```
[network-stream]
cache=yes
cache-secs=36000
cache-backbuffer=10000000
cache-default=10000000
demuxer-max-bytes=2147483647
demuxer-max-back-bytes=2147483647
```
The ram usage gets ridiculous as I used the highest values that would not be ignored my mpv. It is currently the only configuration that allows me to buffer the whole video / live stream, pause it for as long as I want and go back as far as I want. Technically, not as far as I want to, but almost 2 gigabytes back and forth. 

How about adding a new option, `cache=file-only` for example. Memory would not be used for caching (or at least, only a small amount) and the file would be scanned for contents, so that "cache bar" on osd could show how much is buffered (both back and forward) and where the possible gaps (zeros) are (demuxer seems to do that, but It loads everything to memory which, in this case, is most definitely an unwanted behavior). I believe that most of the mpv and youtube-dl users who either watch lots of live streams or just have a really slow internet connection would benefit from this option.

Obviously, I could just download the video / live stream with youtube-dl and even start playing it with mpv as it is still downloading, but it would still require me to have `demuxer-max-bytes` set to an unreasonable amount if I wanted to see "cache bar" on osd.

**Comment by wjtk4444** [comment]
My profile caches them just fine, the only problem is all of it going to my RAM. And yes, You're right, there's an error.
`[file-cache] can't cache unseekable stream`

Still, I see no reason why it wouldn't work for live (unseekable) streams, the only different thing would be not knowing the length of the video/audio. But mpv seems to handle it just fine. It could take some additional work, such as treating cache files specially (maybe by forcing a certain file extension and hard-coding a profile for it), but I don't think that it would be impossible to do.

[From manual](https://mpv.io/manual/master/#options-cache-file):
> this file cache will be used to store whatever is read from the source stream.

>The resulting file will not necessarily contain all data of the source stream. For example, if you seek, the parts that were skipped over are never read and consequently are not written to the cache. The skipped over parts are filled with zeros. This means that the cache file doesn't necessarily correspond to a full download of the source stream.

**Comment by Akemi** [comment]
--cache-file was removed. https://github.com/mpv-player/mpv/commit/8b83c8996686072bc743b112ae5cb3bf93aa33ed#diff-578ae666bf30f2fb3d4eab198d7d785b
