### ISSUE TITLE
Mpv Build Issue

### ISSUE THREAD

**Issue by Ahmedbutt** [mpv-player/mpv#5898]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
./bootstrap.py
./waf configure

### Expected behavior
Build without Error

### Actual behavior
<img width="1275" alt="screen shot 2018-06-08 at 4 52 00 pm" src="https://user-images.githubusercontent.com/5628406/41156698-77b30246-6b3c-11e8-8862-72aee9125886.png">

**Comment by lachs0r** [comment]
It says right there what’s wrong. You need recent FFmpeg with development headers, at least 4.0.
