### ISSUE TITLE
macOS mpv build issue

### ISSUE THREAD

**Issue by Ahmedbutt** [mpv-player/mpv#5900]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
./waf
### Expected behavior
Successful build
### Actual behavior
<img width="1269" alt="screen shot 2018-06-08 at 5 56 31 pm" src="https://user-images.githubusercontent.com/5628406/41159254-541bc01c-6b45-11e8-8256-9d77bc6c08ba.png">

**Comment by Akemi** [comment]
build log would have been much appreciated.

**Comment by Ahmedbutt** [comment]
@Akemi here is log file...
[output.txt](https://github.com/mpv-player/mpv/files/2084506/output.txt)

**Comment by Akemi** [comment]
how come that log doesn't throw any errors? what about a configure log? also try with a folder name without a space in it. you need to be a bit more cooperative, especially not just ignoring the issue template.

**Comment by Ahmedbutt** [comment]
I am trying my best. Can u tell me command in macOS for creating config
file?

Regards

**Comment by Akemi** [comment]
the first time you ran `./waf` it probably told you to run `./waf configure` beforehand. there is also a `config.log` in the `build` folder, which is a bit less readable than configure output. maybe you should read **Compilation** of our readme.

**Comment by Argon-** [comment]
`pip install docutils` or `pip3 install docutils`

**Comment by Ahmedbutt** [comment]
I have already tried this command but same error.

**Comment by Argon-** [comment]
Then there's something wrong with your environment. Without debugging this, you can work around it by configuring with `--disable-pdf-build --disable-manpage-build`.

**Comment by Ahmedbutt** [comment]
I have tried following command but still same error.

./waf --disable-pdf-build --disable-manpage-build
