### ISSUE TITLE
pre built Libraries of mpv for iOS application

### ISSUE THREAD

**Issue by Ahmedbutt** [mpv-player/mpv#5902]
hi,
I want to build an application based on mpv player. is there any pre built libraries which I can use to embed this library in my project. Any help or direction? I have tried to build this project using following command as given in project:

./bootstrap.py
./waf configure
./waf
./waf install

I also used mpb-build scripts to build it but I am unable to build mpv.

Regards

**Comment by Argon-** [comment]
This repo doesn't provide binaries at all. You need to find some other source.
Maybe search within the issues here because there have been some iOS related issues about failed builds before but you will only see problems here, not success stories (as it's the nature of a bug tracker).

**Comment by ybma-xbzheng** [comment]
Maybe this will help friends who want to build mpv on the iOS platform.
[mpv-build-mac-iOS](https://github.com/ybma-xbzheng/mpv-build-mac-iOS)
