### ISSUE TITLE
"At least OpenGL 2.1 or OpenGL ES 2.0 required." message shown inappropriately or repeatedly

### ISSUE THREAD

**Issue by AstroSnail** [mpv-player/mpv#5903]
Somewhat related to #5915

### mpv version and platform

mpv 0.28.2
Arch Linux x86_64

```
mpv 0.28.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon May 14 09:49:30 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0
```

### Reproduction steps

Have an old computer which supports only really old OpenGL versions (in my case, OpenGL 1.4 and OpenGL ES 2.0)
**OR**
(if you use mesa) Use the `MESA_GL_VERSION_OVERRIDE` and `MESA_GLES_VERSION_OVERRIDE` environment variables to change reported OpenGL(ES) versions
**THEN**
Play videos with `--vo=gpu --gpu-api=opengl`

### Expected behavior

When the computer does not meet the playback requirements (ie OpenGL <2.1 **AND** OpenGL ES <2.0), the error message "At least OpenGL 2.1 or OpenGL ES 2.0 required." should appear once, and then (after following context creation failure errors) mpv should exit with an error status. Otherwise, the error message should not appear and playback should happen normally (other errors notwithstanding).

### Actual behavior

The error message is displayed whenever the computer's OpenGL version isn't at least 2.1, even if the OpenGL ES remark is irrelevant (ie OpenGL ES is not selected, or the version is sufficient for playback). The error message can appear as many as 3 times consecutively.

### Log file

`mpv --vo=gpu --gpu-api=opengl --opengl-es=no` https://0x0.st/s_UG.txt
`mpv --vo=gpu --gpu-api=opengl --opengl-es=yes` https://0x0.st/s_UD.txt

### Sample files

Happens with every file I tried so far, so I'm fairly sure I don't need to upload samples.

**Comment by AstroSnail** [comment]
Probably should go in another issue, but when I set environment variables as follows:
```
MESA_GL_VERSION_OVERRIDE=2.1
MESA_GLES_VERSION_OVERRIDE=1.0
```
(I use mesa)
... and use `--opengl-es=yes`, mpv plays video without complaint, suggesting it disregards the argument and uses OpenGL when available.

Also, the manual is unclear about this, but `--opengl-es=auto` also fails in a normal run, as if it only tries OpenGL (I'd think mpv is supposed to try both OpenGL and OpenGL ES?)

**Comment by AstroSnail** [comment]
Did a git bisect, and found that the first bad commit was 65979986a923a8f08019b257c3fe72cd5e8ecf68
Before it, there was no `--vo=gpu --gpu-api=opengl`, so I used `--vo=opengl` for testing (which is exactly what the commit was deprecating), and I got the expected results (bar my comment about `--opengl-es=auto`, that behaviour remains the same).

**Comment by Dudemanguy** [comment]
Old issue, but not really sure if this is fixable. Most likely what is happening is simply that mpv's render loops tries to paint the first frame a few times and it takes a while for it to actually appear on the screen. Those initial 2-3 runs through the playloop before you actually get a picture is probably what causes that message to print.

**Comment by AstroSnail** [comment]
Thanks for reminding me about this three-year-old issue! I tested just now with mpv 0.33.1 and the issue no longer occurs! In other words, mpv now behaves exactly as outlined in Expected behavior, with a slightly interesting note that if `--opengl-es=yes` is selected, then the message doesn't appear at all, but context creation fails as expected.
