### ISSUE TITLE
Dropped frames with 59.94 fps video

### ISSUE THREAD

**Issue by markojurkovic** [mpv-player/mpv#5906]
### mpv version and platform

mpv 0.28.2, Ubuntu 18.04, Intel HD 630 Graphics

### Reproduction steps

Play 720p video with 59.94 fps

### Expected behavior

Smooth playback, no dropped frames

### Actual behavior

Periodic dropped frames, quite noticeable

### Log file

https://0x0.st/s_wN.txt

### Sample files

https://mega.nz/#!jREAxYgb!MtjBIh1oSJJBZgLT7AcdG88hGCFG-ak7pC2AyjrsaIQ

As can be seen in the logs, I changed the scaling algorithms to even faster ones to eliminate that as a factor, even though it makes no difference in behavior compared with the default mpv configuration.

Also tried using --opengl-early-flush=no, same thing. Ditto when using --vo=vaapi. VLC plays videos without any drops.

**Comment by aufkrawall** [comment]
Have you tried disabling GPU power saving features and disabling compositor (won't work with Gnome)?
When I tried mpv with Intel on Linux the last time, it was very prone to stuttering because of both.
Also, don't use default intel_pstate=powersave CPU clock governor, it's rubbish.

**Comment by slinky3** [comment]
Xubuntu 16.04.4 on Intel Skylake is also affected.  video-sync=display-resample also triggers it regardless of framerate.

I've narrowed it down to a kernel update.
4.13.0-41 works fine. 4.13.0-43 is when the frame-dropping began.

Things I've tried:
compositor (enabled and disabled)
Option "TearFree" "true" - via xorg
TLP (enabled and disabled)
mpv git, 0.28.2 and 0.27.2

As suggested I disabled intel_pstate and tried conservative, ondemand and performance governors.

MPV seems to be the only program negativly affected. Kodi and VLC are working fine.

**Comment by Jj0YzL5nvJ** [comment]
Isn't this the expected behaviour on IGPs when you use "hwdec=xxx" instead "hwdec=xxx-copy"?
In any case, IGPs do all the work in RAM...

**Comment by aufkrawall** [comment]
It does work fine on Windows.

Maybe one of the options mentioned here might be helpful:
https://gist.github.com/Brainiarc7/aa43570f512906e882ad6cdd835efe57

**Comment by slinky3** [comment]
Ubuntu just pushed a kernel update 4.15.0-24 that has solved the issue for me.  I'm not the OP but I think this can be closed.

**Comment by markojurkovic** [comment]
The issue still exists for me using kernel version 4.18 on Ubuntu 18.04.

**Comment by mattia-b89** [comment]
can you share a much smaller test file?
