### ISSUE TITLE
Stats always true when --no-video on (mpv youtube-dl show titles music only)

### ISSUE THREAD

**Issue by necronoise** [mpv-player/mpv#5907]
### mpv version and platform
mpv 0.28.2 (C) 2000-2017 and manjaro i3 (bash and urxvt)

### Trouble
I like to use mpv as my music player, so I did a shell script to listen my playlist in youtube, the problem is, everytime I start the script I need to press the key I to make the stats overlay permanent. How I can make this always true when --no-video on or only audio is playing? I already read a lot (man mpv, youtube-dl mpv, arch wiki, etc) and still cant figured out how to do it.

Some sites I found but I was not capable of making work: https://unix.stackexchange.com/questions/298492/make-mpv-display-name-of-youtube-link-when-playing-just-audio
https://github.com/fbriere/mpv-scripts/blob/master/scripts/audio-file-keys.lua
https://www.semicomplete.com/projects/xdotool/
https://unix.stackexchange.com/questions/14879/how-to-inject-keystrokes-via-a-shell-script (looks like mpv does not capture input from stdin and directly from the terminal)
https://github.com/mpv-player/mpv/issues/1419

**Comment by concatime** [comment]
Same question. If you have an answer, share it :)

**Comment by concatime** [comment]
With the help of awesome fellows on IRC@Freenode, I was able to make a solution.
```lua
-- ~/.config/mpv/scripts/info-on-no-video.lua
if not mp.get_property_bool('vid') then
	mp.register_event("file-loaded", function()
		mp.command('script-binding stats/display-stats') end)
end
```

**Comment by necronoise** [comment]
I love you @concatime oh my god HAHAH cant believe this is actually working <3

**Comment by concatime** [comment]
It’s a pleasure :)
Feel free to close this thread.

**Comment by UnixCro** [comment]
MPV is the best audio player ever but the biggest snot once video is added. Is there any way to force mpv to never show cover art or video?
Many Thanks
