### ISSUE TITLE
OSC still interactive when hidden

### ISSUE THREAD

**Issue by Celmor** [mpv-player/mpv#5910]
### mpv version and platform
Versions reproduced with:

- `0.28.0-611-gbca59516cc` compiled via mpv-build
- `0.28.2` from distros repo

uname/platform: `4.16.12-1-MANJARO #1 SMP PREEMPT Fri May 25 18:39:04 UTC 2018 x86_64 GNU/Linux`

### Reproduction steps

1. Open a video
2. Press del (delete) button twice to set OSC visibility to never (aka hidden)
3. click where the pause on-screen button or seek bar used to be

### Expected behavior
Nothing happens when clicked while OSC is hidden
### Actual behavior
Video is paused / skipped in time line according to where you clicked while OSC is hidden
### Log file
`https://pastebin.com/raw/tj55q8A1`

### notes
When started with `--script-opts=osc-visibility=never` OSC first needs to be enabled once and then hidden again to reproduce this issue.

**Comment by avih** [comment]
Can't reproduce this. It's probably been fixed. Please open a new issue if it still exists.
