### ISSUE TITLE
Build mpv for iOS

### ISSUE THREAD

**Issue by Ahmedbutt** [mpv-player/mpv#5913]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
./waf configure --disable-cplayer --disable-lcms2 --disable-lua --enable-libmpv-static --enable-ios-gl --enable-gl
./waf build
### Expected behavior
Successfuly build mpv

### Actual behavior
<img width="856" alt="screen shot 2018-06-10 at 4 41 54 am" src="https://user-images.githubusercontent.com/5628406/41197004-bbb6b1d6-6c68-11e8-905c-a381fcbd5a51.png">

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Ahmedbutt** [comment]
One solution is that i can disable building of documentation but I don't know command for it. Please any suggestion.

**Comment by xantoz** [comment]
1) install docutils
2) acquire rst2man
3) ???
4) PROFIT!

**Comment by tmm1** [comment]
Use `./waf --help` to see all the available options. To disable documentation you need `--disable-manpage-build`.

The problem in your case is that you don't have a working `rst2man`/`python` installation on your system.
