### ISSUE TITLE
7.1 playback (Dolby TrueHD Atmos) works only once on OSX

### ISSUE THREAD

**Issue by andrewclevine** [mpv-player/mpv#5916]
### mpv version and platform

0.28.2
Mac OSX 10.11.6

### Reproduction steps

Install mpv on a system for the first time, play back a MKV containing a 7.1 audio track

### Expected behavior

You hear surround sound
Quit mpv, let the mac sleep, wake it and try again…

### Actual behavior

Audio is down-mixed to stereo

### Log file

I should have 32 channels I/O…

[   2.033][v][ao/coreaudio] using soft-buffer of 9600 samples.
[   2.033][i][cplayer] AO: [coreaudio] 48000Hz stereo 2ch s32
[   2.033][v][cplayer] AO: Description: CoreAudio AudioUnit
[   2.033][v][af] Removing filter lavrresample 
[   2.033][v][af] Adding filter lavrresample 
[   2.033][v][lavrresample] Remix: 7.1 -> stereo
[   2.033][v][af] Audio filter chain:
[   2.033][v][af]   [in] 48000Hz 7.1 8ch s32
[   2.033][v][af]   [lavrresample] 48000Hz stereo 2ch s32 [a]
[   2.033][v][af]   [out] 48000Hz stereo 2ch s32
[   2.033][v][af]   [ao] 48000Hz stereo 2ch s32

**Comment by andrewclevine** [comment]
Here I have some more information:

[   2.028][v][ad] Opening audio decoder truehd
[   2.028][v][ad] Requesting 1 threads for decoding.
[   2.028][v][ad] Selected audio codec: truehd (TrueHD)
[   2.028][v][cplayer] Starting playback...
[   2.029][v][af] Adding filter lavfi 
[   2.029][d][af] Setting option 'graph' = 'aformat=sample_fmts=s32|s32:channel_layouts=5.1' (flags = 0)
[   2.029][d][ffmpeg/video] h264: Reinit context to 1920x1088, pix_fmt: yuv420p
[   2.033][d][ffmpeg] src: tb:1/48000 samplefmt:s32 samplerate:48000 chlayout:0x63f
[   2.033][v][lavfi] lavfi: create graph: 'aformat=sample_fmts=s32|s32:channel_layouts=5.1'
[   2.034][e][ffmpeg] Duplicate formats in ff_merge_formats detected
[   2.034][d][ffmpeg] Parsed_aformat_0: auto-inserting filter 'auto_resampler_0' between the filter 'src' and the filter 'Parsed_aformat_0'
[   2.034][d][ffmpeg] auto_resampler_0: ch:8 chl:7.1 fmt:s32 r:48000Hz -> ch:6 chl:5.1 fmt:s32 r:48000Hz
[   2.034][v][af] Audio filter chain:
[   2.034][v][af]   [in] 48000Hz 7.1 8ch s32
[   2.034][v][af]   [lavfi] 48000Hz 5.1 6ch s32
[   2.034][v][af]   [out] 48000Hz 5.1 6ch s32
[   2.034][v][af]   [ao] 48000Hz 5.1 6ch s32
[   2.034][v][ao] Trying audio driver 'coreaudio'
[   2.035][v][ao/coreaudio] requested format: 48000 Hz, 5.1 channels, s32
[   2.059][v][ao/coreaudio] selected audio output device: MHLink Audio [000759009ce1] (65)
[   2.059][v][ao/coreaudio] input channel layout:
[   2.059][v][ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <32>
[   2.059][v][ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 2: label <3, 2>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 3: label <4, 3>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 4: label <5, 4>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 5: label <6, 5>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 6: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 7: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 8: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 9: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 10: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 11: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 12: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 13: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 14: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 15: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 16: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 17: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 18: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 19: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 20: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 21: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 22: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 23: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 24: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 25: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 26: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 27: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 28: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 29: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 30: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 31: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio] layout has too many descriptions (32, max: 16)
[   2.059][v][ao/coreaudio] input channel layout:
[   2.059][v][ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[   2.059][v][ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   2.059][v][ao/coreaudio] mp chmap: stereo
[   2.059][v][ao/coreaudio] Channel layouts:
[   2.059][v][ao/coreaudio]  - stereo
[   2.059][v][ao/coreaudio]  - mono
[   2.059][v][ao/coreaudio] result: stereo
[   2.113][v][ao/coreaudio] Latency property cntl: 0 frames
[   2.113][v][ao/coreaudio] Latency property zisf: 512 frames
[   2.113][v][ao/coreaudio] Latency property tfas: 136 frames
[   2.113][v][ao/coreaudio] audiounit latency [us]: 0
[   2.113][v][ao/coreaudio] device latency [us]: 13500
[   2.113][v][ao/coreaudio] using soft-buffer of 9600 samples.
[   2.113][i][cplayer] AO: [coreaudio] 48000Hz stereo 2ch s32
[   2.113][v][cplayer] AO: Description: CoreAudio AudioUnit
[   2.114][d][ffmpeg] src: tb:1/48000 samplefmt:s32 samplerate:48000 chlayout:0x63f
[   2.114][v][lavfi] lavfi: create graph: 'aformat=sample_fmts=s32|s32:channel_layouts=5.1'
[   2.114][e][ffmpeg] Duplicate formats in ff_merge_formats detected
[   2.114][d][ffmpeg] Parsed_aformat_0: auto-inserting filter 'auto_resampler_0' between the filter 'src' and the filter 'Parsed_aformat_0'
[   2.114][d][ffmpeg] auto_resampler_0: ch:8 chl:7.1 fmt:s32 r:48000Hz -> ch:6 chl:5.1 fmt:s32 r:48000Hz
[   2.114][d][ffmpeg] src: tb:1/48000 samplefmt:s32 samplerate:48000 chlayout:0x63f
[   2.114][v][lavfi] lavfi: create graph: 'aformat=sample_fmts=s32|s32:channel_layouts=5.1'
[   2.114][e][ffmpeg] Duplicate formats in ff_merge_formats detected
[   2.114][d][ffmpeg] Parsed_aformat_0: auto-inserting filter 'auto_resampler_0' between the filter 'src' and the filter 'Parsed_aformat_0'
[   2.114][d][ffmpeg] auto_resampler_0: ch:8 chl:7.1 fmt:s32 r:48000Hz -> ch:6 chl:5.1 fmt:s32 r:48000Hz
[   2.114][v][af] Adding filter lavrresample 
[   2.114][v][lavrresample] Remix: 5.1 -> stereo
[   2.114][v][af] Audio filter chain:
[   2.114][v][af]   [in] 48000Hz 7.1 8ch s32
[   2.114][v][af]   [lavfi] 48000Hz 5.1 6ch s32
[   2.114][v][af]   [lavrresample] 48000Hz stereo 2ch s32 [a]
[   2.114][v][af]   [out] 48000Hz stereo 2ch s32
[   2.114][v][af]   [ao] 48000Hz stereo 2ch s32

**Comment by andrewclevine** [comment]
OK, problem solved. mpv could not handle the 32 output channels. Reducing to 8 in the driver-control takes care of the issue :-)

[   3.604][v][ad] Codec list:
[   3.604][v][ad]     truehd - TrueHD
[   3.604][v][ad] Opening audio decoder truehd
[   3.604][v][ad] Requesting 1 threads for decoding.
[   3.604][v][ad] Selected audio codec: truehd (TrueHD)
[   3.604][v][cplayer] Starting playback...
[   3.605][v][af] Audio filter chain:
[   3.605][v][af]   [in] 48000Hz 7.1 8ch s32
[   3.605][v][af]   [out] 48000Hz 7.1 8ch s32
[   3.605][v][af]   [ao] 48000Hz 7.1 8ch s32
[   3.605][v][ao] Trying audio driver 'coreaudio'
[   3.605][d][ffmpeg/video] h264: Reinit context to 1920x1088, pix_fmt: yuv420p
[   3.605][v][ao/coreaudio] requested format: 48000 Hz, 7.1 channels, s32
[   3.632][v][ao/coreaudio] selected audio output device: MHLink Audio [000759009ce1] (65)
[   3.632][v][ao/coreaudio] input channel layout:
[   3.632][v][ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <8>
[   3.632][v][ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   3.632][v][ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   3.632][v][ao/coreaudio]  - description 2: label <3, 2>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   3.632][v][ao/coreaudio]  - description 3: label <4, 3>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   3.632][v][ao/coreaudio]  - description 4: label <5, 4>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   3.632][v][ao/coreaudio]  - description 5: label <6, 5>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   3.632][v][ao/coreaudio]  - description 6: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   3.632][v][ao/coreaudio]  - description 7: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   3.632][v][ao/coreaudio] mp chmap: fl-fr-fc-lfe-bl-br-na-na
[   3.633][v][ao/coreaudio] input channel layout:
[   3.633][v][ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[   3.633][v][ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   3.633][v][ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[   3.633][v][ao/coreaudio] mp chmap: stereo
[   3.633][v][ao/coreaudio] Channel layouts:
[   3.633][v][ao/coreaudio]  - fl-fr-fc-lfe-bl-br-na-na
[   3.633][v][ao/coreaudio]  - stereo
[   3.633][v][ao/coreaudio]  - mono
[   3.633][v][ao/coreaudio] result: fl-fr-fc-lfe-bl-br-na-na
[   3.685][v][ao/coreaudio] Latency property cntl: 0 frames
[   3.685][v][ao/coreaudio] Latency property zisf: 512 frames
[   3.685][v][ao/coreaudio] Latency property tfas: 112 frames
[   3.685][v][ao/coreaudio] audiounit latency [us]: 0
[   3.685][v][ao/coreaudio] device latency [us]: 13000
[   3.685][v][ao/coreaudio] using soft-buffer of 9600 samples.
[   3.685][i][cplayer] AO: [coreaudio] 48000Hz fl-fr-fc-lfe-bl-br-na-na (5.1) 8ch s32
[   3.685][v][cplayer] AO: Description: CoreAudio AudioUnit
[   3.685][v][af] Adding filter lavrresample 
[   3.685][v][lavrresample] Remix: 7.1 -> 5.1
[   3.685][v][af] Audio filter chain:
[   3.685][v][af]   [in] 48000Hz 7.1 8ch s32
[   3.685][v][af]   [lavrresample] 48000Hz fl-fr-fc-lfe-bl-br-na-na (5.1) 8ch s32 [a]
[   3.685][v][af]   [out] 48000Hz fl-fr-fc-lfe-bl-br-na-na (5.1) 8ch s32
[   3.685][v][af]   [ao] 48000Hz fl-fr-fc-lfe-bl-br-na-na (5.1) 8ch s32

**Comment by hmedia1** [comment]
I don't really think this solves the problem at the source, since not all drivers have the ability to reduce their number of IO through software settings.

It should be perfectly legal to send 8 channels to a 32 channel interface (or, 32 channels for that matter)
