### ISSUE TITLE
iOS:rmvb format video will appear briefly blurred during seek.

### ISSUE THREAD

**Issue by ldwardx** [mpv-player/mpv#5920]
### mpv version and platform

mpv 0.27.2
FFmpeg 3.4.2
platform iOS 10.3.3

### Reproduction steps

Play a rmvb format video and then seek.

### Expected behavior

not blurred.

### Actual behavior

Blurred, like a mosaic.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/2097520/mpv.log)

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
