### ISSUE TITLE
White flickering and flashing during stream playback

### ISSUE THREAD

**Issue by yuvadm** [mpv-player/mpv#5926]
### mpv version and platform
```
mpv 0.28.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on Mon May 14 09:49:30 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0
```

### Reproduction steps

1. Open the stream `https://vimmi.hs.llnwd.net/Channel511LLRepeat/channel511/smil:channel511.smil/chunklist_b5564000.m3u8` for viewing. This is the `ffprobe` data for this stream:

```
  Duration: N/A, start: 82684.291311, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt2020nc/bt2020/arib-std-b67), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:2: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
```

### Expected behavior

No flickering

### Actual behavior

White flickering / flashing appears constantly.

### Log file

https://gist.github.com/yuvadm/df3e102a07abda6e3ae918f208d4d67b

**Comment by wm4** [comment]
Stream disappeared, ancient issue, closing.

**Comment by yuvadm** [comment]
Indeed this is an old stream and I don't believe I've seen this issue since. Will reopen with an updated stream if I ever do.
