### ISSUE TITLE
Deinterlacing causes many dropped frames in 720p live tv stream.

### ISSUE THREAD

**Issue by Doofussy2** [mpv-player/mpv#5927]
Git release 2018-06-10 (and previous)

I have deinterlace=yes, in my mpv.conf. When watching live streams, the 1080i is deinterlaced, correctly. But if I switch to a channel that is 720p, it starts dropping hundreds of frames. This doesn't happen with 720p, videos. In the log, I toggle deinterlacing on, after playback begins. I thought that might illustrate it more clearly. Also, disabling hardware acceleration, doesn't change it.

No frame dropping.

[720p frame dropping.txt](https://github.com/mpv-player/mpv/files/2105077/720p.frame.dropping.txt)

I have a sample recording, but I'll confess to not knowing how to upload it to https://0x0.st/

**Comment by lifespeed1** [comment]
I also see this issue.  deinterlace=yes causes problems with regular progressive content, particularly 24fps content.  I see it with MKV files as well, both 1080p and 720p.  This causes the rather painful requirement to manually reconfigure MPV for interlaced (usually live TV) content vs. progressive as it appears to be unable to handle this gracefully on it's own.  This is with an nVidia GTX 770 GPU.

**Comment by Doofussy2** [comment]
Ok, so I have an alternative that works. Even though deinterlace=yes is supposedly the same as yadif, if I use vf=lavfi=yadif instead, I get the desired result, and no dropped frames.

**Comment by Doofussy2** [comment]
Unfortunately, when using copyback with nvdec, cuda and d3d11 with some 4k content, causes considerable framedropping. dxva2-copy (auto-copy), works better, but still some framedropping at the start of playback.

**Comment by Doofussy2** [comment]
Solution found. An auto-profile

[Interlaced]
profile-desc=cond:p["video-frame-info/interlaced"]
vf=lavfi=yadif

**Comment by Doofussy2** [comment]
Another update on this. Using deinterlace=yes in this profile, instead of yadif, works very well. But I just can't use deinterlace=yes, on it's own.

[Interlaced]
profile-desc=cond:p["video-frame-info/interlaced"]
deinterlace=yes

**Comment by Argon-** [comment]
For reference, you also need a inverted profile. Imagine you watch a playlist with two videos, the first interlaced the second not. Now the first video will trigger this profile and set `deinterlace=yes`. This option will also be active for the second video. Therefore, you need a profile to "deactivate" deinterlacing again for videos that don't need it:

    [Progressive]
    profile-desc=cond:not p["video-frame-info/interlaced"]
    deinterlace=no

**Comment by Doofussy2** [comment]
Thanks, I'll add that. Would an empty profile also work? Or does it specifically need to be the antithesis?

**Comment by Argon-** [comment]
What would an empty profile accomplish? The point is that in the mentioned scenario `deinterlace` is still set to `yes`. Nobody is going to set it to `no` for you, you have to do it yourself.

**Comment by Doofussy2** [comment]
That's what I thought. I had it suggested that an empty profile might work, so I just wanted to confirm what is necessary.

**Comment by Doofussy2** [comment]
@Argon- having those two profiles in the mpv.conf creates havoc when playing a video. I think it's alternating between the two.

[Portable mpv log.txt](https://github.com/mpv-player/mpv/files/2373339/Portable.mpv.log.txt)

**Comment by Doofussy2** [comment]
Thanks, but the same result. No deinterlacing and the frame rate is jacked up. Lots of jerkiness. Looking at the stats, the frame timings are going nuts. I have an interlaced .TS file that is a TV recording that I'm testing with.

**Comment by Doofussy2** [comment]
I have a workaround for my issue. It's with my HEVC 4k HDR and Live TV 720p content that it causes an issue. So I just added the HEVC profile with deinterlace=no. So that fixes one issue. I may need to make a profile specifically for 720p, with deinterlace=no. Any thoughts on the best profile for that?

The devs really need to work on the deinterlacing. As a general setting, it's unusable.

**Comment by Doofussy2** [comment]
I believe I have the right mix of profiles, now.

[HEVC]
profile-desc=cond:p["video-format"]=="hevc"
deinterlace=no

[Interlaced]
profile-desc=cond:p["video-frame-info/interlaced"]
deinterlace=yes

[720p]
profile-desc=cond:p["width"]==1280
deinterlace=no

**Comment by lqvnguyen** [comment]
Try adding either to mov.conf
`vf=yadif:mode=1:deint=1`
For Intel VA-API on Linux try `vf=vavpp:deint=motion-compensated:interlaced-only=yes`

**Comment by lqvnguyen** [comment]
This is due to this commit:
https://github.com/mpv-player/mpv/commit/830f0aed97da7257e1cbe30a367144bc51ec52d2

**Comment by Doofussy2** [comment]
> Try adding either to mov.conf
> `vf=yadif:mode=1:deint=1`
> For Intel VA-API on Linux try `vf=vavpp:deint=motion-compensated:interlaced-only=yes`

It was happening before that commit, but thanks for the suggestion.

**Comment by Doofussy2** [comment]
One this that I'm curious about, is that yadif has been removed and needs the lavfi wrapper, so how is that working without the wrapper?

**Comment by lqvnguyen** [comment]
@doofussy2
I was not aware it was removed. I see it triggering in the logs still with the vf applied. What build was it removed in?

**Comment by Doofussy2** [comment]
@lqvnguyen 
Almost a year ago. But maybe not from @shinchiro's builds? 

https://mpv.srsfckn.biz/changes/2017-12-25/

**Comment by wm4** [comment]
And the conclusion to this is what? Closing anyway. Deinterlacing was changed to always deinterlace intentionally (as opposed to earlier mechanisms, where it was at least partially skipped depending on frame flags).
