### ISSUE TITLE
Where can I change shortcuts in mpv-player?

### ISSUE THREAD

**Issue by pavilion** [mpv-player/mpv#5930]
Hi, I would like to change shortcuts in mpv-player. I am trying to find the config file but I'm having no luck. Went to the documentation and searched for "shortcut" and "config", but couldn't find anything related to it. Thanks.

**Comment by Argon-** [comment]
https://mpv.io/manual/master/#input-conf
The default is this: https://github.com/mpv-player/mpv/blob/master/etc/input.conf
