### ISSUE TITLE
Please resupport BD Menu

### ISSUE THREAD

**Issue by liyuxi** [mpv-player/mpv#5933]
In VLC 3.0,it implemented mature Blu-ray support，if I install Java VM ,the BD-J can work normally.
mpv has removed BD Menu support not long before,I hope it back.

**Comment by wiiaboo** [comment]
BD Menu was never supported at all in mpv.

**Comment by legluondunet** [comment]
Do you plan to implement it? It's far more pleasant to access the BR menu before to launch the movie, to choose language, subtitles or bonus.

**Comment by CounterPillow** [comment]
Do you plan to implement it, @legluondunet?

**Comment by darealshinji** [comment]
I would like that too.

**Comment by wm4** [comment]
This won't happen unless someone steps up and goes implement it in a non-intrusive manner (which is hard in addition to BD menu stuff being hard).

I myself wasted far too much time on optical disc crap. In my experience, this menu stuff never works well (even in other players), and will always be something buggy, complex, and refuses to be properly modularized.

> BD Menu was never supported at all in mpv.

Actually it was. It was added in mpv times, but removed together with DVD menus.
