### ISSUE TITLE
unknown / unknown flashed in place of timestamp.

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#5934]
### mpv version and platform
mpv 0.28.2
linux 4.16.13
### Reproduction steps
When switching to a new file in a playlist while timestamp is still visible after seeking, like `00:04:35 / 00:22:51 (20%)`
### Actual behavior
For a fraction of a second I get flashed with `unknown / unknown` in place of a timestamp, before I get actual timestamp that holds on the screen until time limit of `osd-duration` runs out.

If I have set `osd-playing-msg`, I get the same `unknown / unknown` for a fraction of a second before the `osd-playing-msg` is shown.

**Comment by Akemi** [comment]
if this issue still persists, please open a new issue.
