### ISSUE TITLE
glGetString(GL_VERSION) returned NULL.

### ISSUE THREAD

**Issue by ybma-xbzheng** [mpv-player/mpv#5938]
### mpv version and platform

mpv 0.27.2
FFmpeg 3.4.2
platform iOS 9.3.5
device iPad 2

### Reproduction steps
Play any video.

### Actual behavior
```
...
[   0.214][f][opengl-cb] glGetString(GL_VERSION) returned NULL.
[   0.214][f][opengl-cb] OpenGL not initialized.
...
```
### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/2118964/mpv.log)

### Some info
This bug is currently found on the iPad 2.
I think it may be related to the following information:
- iPad 2 uses OpenGL ES 2.0.
- iPad 2 uses the armv7 processor.

**Comment by Akemi** [comment]
are you actually setting a current context? without your code it's hard to tell. this is most likely not our bug. you should also use our current release or master.

**Comment by ybma-xbzheng** [comment]
Thanks for your attention.
My code is very simple, mostly mpv API.
```objc
static void *get_proc_address(void *ctx, const char *name)
{
    CFStringRef symbolName = CFStringCreateWithCString(kCFAllocatorDefault, name, kCFStringEncodingASCII);
    void *addr = CFBundleGetFunctionPointerForName(CFBundleGetBundleWithIdentifier(CFSTR("com.apple.opengles")), symbolName);
    CFRelease(symbolName);
    return addr;
}

- (void)createMPV {
    _mpv = mpv_create();
    
    //set some option
    mpv_set_option_string(_mpv, MOOSDLevel, "0");
    mpv_set_option_string(_mpv, MOInputAppleremote, noStr);
    mpv_set_option_string(_mpv, MOSubAuto, noStr);
    mpv_set_option(_mpv, MONoEmbeddedfonts, MPV_FORMAT_NONE, NULL);
    mpv_set_option_string(_mpv, MOSubAssOverride, "strip");
    mpv_set_option_string(_mpv, "sub-scale-with-window", noStr);
    [self setInt:MOVolumeMax value:100];

#if DEBUG
    NSString *basePath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES).firstObject;
    mpv_set_option_string(_mpv, "log-file", [[basePath stringByAppendingPathComponent:@"mpv.log"] cStringUsingEncoding:NSUTF8StringEncoding]);
    mpv_request_log_messages(_mpv, MLLTrace);
#endif
    
    //event
    _eventQueue = dispatch_queue_create("com.qiyi.universalplayer.mpvevent", DISPATCH_QUEUE_SERIAL);
    mpv_set_wakeup_callback(_mpv, wakeup, (__bridge void *)self);
    
    mpv_observe_property(_mpv, 0, MOPause, MPV_FORMAT_FLAG);
    mpv_observe_property(_mpv, 0, MPTrackListCount, MPV_FORMAT_INT64);
    
    //init mpv
    mpv_initialize(_mpv);
    
    mpv_set_option_string(_mpv, MOHWDec, "auto");
    mpv_set_property_string(_mpv, MOVO, "opengl-cb");
    mpv_set_property_string(_mpv, MOKeepAspect, yesStr);
    
    //opengl context
    mpv_opengl_cb_context *mpvGL = mpv_get_sub_api(_mpv, MPV_SUB_API_OPENGL_CB);
    
    [_drawView display];
    _drawView.mpvGL = mpvGL;
    
    //init opengl
    mpv_opengl_cb_init_gl(mpvGL, NULL, get_proc_address, NULL);
    mpv_opengl_cb_set_update_callback(mpvGL, glupdate, (__bridge void *)self.drawView);
}
```
The function `mpv_get_sub_api()` returned a non-NULL object, but `mpv_opengl_cb_init_gl()` returned `-18 (MPV_ERROR_UNSUPPORTED)`

The same code runs on arm64 architecture devices such as iPad mini 4 and iPhone 6 plus without any problems.

**Comment by Akemi** [comment]
if that's all, you don't create an opengl context. you need to initialise a CGLContextObj, NSOpenGLContext, NSOpenGLView, CAOpenGLLayer or similar and set it to current from the thread you are calling the CB functions from (also see and read(!) the [old API doc](https://github.com/mpv-player/mpv/blob/v0.27.2/libmpv/opengl_cb.h#L89) that you still use). see our example [here](https://github.com/mpv-player/mpv-examples/blob/master/libmpv/cocoa-openglcb/cocoa-openglcb.m#L41) or [how its done within mpv](https://github.com/mpv-player/mpv/blob/master/video/out/cocoa-cb/video_layer.swift#L65).

**Comment by ybma-xbzheng** [comment]
You are right!
The `_drawView` in the above code is an instance of `GLKView`, but I incorrectly initialized its context to OpenGL ES 3 only, causing OpenGL ES 2.0-only devices to fail to initialize the context.
I will check the old API problem.
Thank you very much for your help. I will try to avoid this kind of low-level error.

**Comment by hoonlee-twdev** [comment]
MUST I have the same problem...
Could you show me your solutions in detail?

mpv 0.29.1
FFmpeg 4.2.1
platform iOS 12.4.3
device iPhone 6

```
[  34.356][f][libmpv_render] glGetString(GL_VERSION) returned NULL.`
[  43.568][f][libmpv_render] OpenGL not initialized.`
```

I'm trying to build an example from [https://github.com/mpv-player/mpv-examples/tree/master/libmpv/ios](https://github.com/mpv-player/mpv-examples/tree/master/libmpv/ios).

Thank you.

**Comment by wm4** [comment]
The error message is probably correct, and you have no OpenGL context initialized and set "current". Not sure if the example does it correctly; it seems to assume the GUI stuff already has a context initialized (but I can't tell). Possible that iOS doesn't initialize OpenGL by default anymore or so (or maybe they dropped OpenGL entirely).
