### ISSUE TITLE
Color Management (OS X): Use system configured display profile automatically

### ISSUE THREAD

**Issue by UliZappe** [mpv-player/mpv#594]
**Note:** I can argue for OS X only, but of course, the issue might be relevant for the other platforms, too.

Now that color management works correctly :-) , it would certainly make sense from a usage point of view to offer an option to automatically use the system configured ICC display profile automatically, instead of having to configure it explicitly for **mpv**.

I.e. something like _:icc-profile=auto_ should automatically use whatever display profile the user has set in the OS X System Preferences.

I will provide the code to figure out the path of the system’s display profile below, but I have too little insight in **mpv**’s architecture to know how to integrate this functionality correctly.

I can see two major architectural questions:

**1. Can the color management LUT table be changed during playback?**

If yes, **mpv** could adjust its color if the user changes its display profile during playback. (It would register to get a notification whenever the user changes the display profile for a screen, which is easy to implement.)

This is probably not the most important feature, but it _could_ be useful. For instance, I use two different display profiles for daylight and artificial light. If I start watching a movie during the day, pause it, and continue in the night, such intelligent adaptation would be useful. Again, not the most important feature, but one that would make the integration in the OS "perfect". (**QuickTime Player Pro X** does it.)

**2. In a multi-display configuration, can the user change the display during playback?**

If yes, then point 1.) – the possibility to change the display profile during playback – would basically become mandatory, since different displays will almost certainly have different display profiles. And if I understand the _--screen_ and _--fullscreen_ options correctly, this is indeed the case.

The specific API of the function that provides the path of the display profile will probably depend on the answer to these two questions.

If no change of the display profile during playback is required and only the display profile of the currently used display needs to be set at launch, the following function is sufficient:

```
 Boolean get_screen_profile(char *pathBuffer, size_t maxPathSize)
{
    CFUUIDRef displayUUID = CGDisplayCreateUUIDFromDisplayID(kCGDirectMainDisplay);
    if (CFGetTypeID(displayUUID) == CFNullGetTypeID()) {MP_ERR(s, "Cannot get display UUID.\n"); return false;}

    CFDictionaryRef displayInfo = ColorSyncDeviceCopyDeviceInfo(kColorSyncDisplayDeviceClass, displayUUID);
    if (!displayInfo) {MP_ERR(s, "Cannot get display info.\n"); CFRelease(displayUUID); return false;}
    CFRelease(displayUUID);
    CFDictionaryRef customProfileInfo = CFDictionaryGetValue(displayInfo, kColorSyncCustomProfiles);
    if (!customProfileInfo) {MP_ERR(s, "Cannot get display profile info.\n"); CFRelease(displayInfo); return false;}

    CFURLRef customProfileURLs[CFDictionaryGetCount(customProfileInfo)];
    CFDictionaryGetKeysAndValues(customProfileInfo, NULL, (const void **)customProfileURLs);
    if ((void*)customProfileURLs[0] == kCFNull) {MP_ERR(s, "Cannot get display profile URL.\n"); CFRelease(displayInfo); return false;}
    Boolean result = CFURLGetFileSystemRepresentation(customProfileURLs[0], true, (UInt8*)pathBuffer, maxPathSize);
    CFRelease(displayInfo);

    if (!result) MP_ERR(s, "Cannot get display profile path.\n");
    return result;
}
```

(Note that I’m unsure about the log levels you would consider adequate.)

You can directly insert this function as is in **video/out/cocoa_common.m**, or even in **video/out/gl_lcms.c** if you additionally add

```
#include <ApplicationServices/ApplicationServices.h>
```

You would call the function as follows:

```
char buffer[PATH_MAX];
Boolean result = get_screen_profile(buffer, PATH_MAX);
```

If successful, _buffer_ will contain the path to the ICC display profile of the current display, which can then be used for the _load_file()_ call in _mp_load_icc()_.

However, if the profile must be changeable during playback, you’ll probably need an API similar to this in **video/out/cocoa_common.m** (EDIT: updated code for retrieving the display ID):

```
static Boolean get_screen_profile(struct vo *vo, Boolean fullscreen, char *pathBuffer, size_t maxPathSize)
{
    struct vo_cocoa_state *s = vo->cocoa;
    NSScreen *screen = fullscreen? s->fs_screen : s->current_screen;
    const char *screenstring = fullscreen? "full screen " : "";

    CGDirectDisplayID displayID = (CGDirectDisplayID)[[[screen deviceDescription] valueForKey:@"NSScreenNumber"] unsignedLongValue];
    CFUUIDRef displayUUID = CGDisplayCreateUUIDFromDisplayID(displayID);
    if (CFGetTypeID(displayUUID) == CFNullGetTypeID()) {MP_ERR(s, "Cannot get %sdisplay UUID.\n", screenstring); return false;}

    CFDictionaryRef displayInfo = ColorSyncDeviceCopyDeviceInfo(kColorSyncDisplayDeviceClass, displayUUID);
    if (!displayInfo) {MP_ERR(s, "Cannot get %sdisplay info.\n", screenstring); CFRelease(displayUUID); return false;}
    CFRelease(displayUUID);
    CFDictionaryRef customProfileInfo = CFDictionaryGetValue(displayInfo, kColorSyncCustomProfiles);
    if (!customProfileInfo) {MP_ERR(s, "Cannot get %sdisplay profile info.\n", screenstring); CFRelease(displayInfo); return false;}

    CFURLRef customProfileURLs[CFDictionaryGetCount(customProfileInfo)];
    CFDictionaryGetKeysAndValues(customProfileInfo, NULL, (const void **)customProfileURLs);
    if ((void*)customProfileURLs[0] == kCFNull) {MP_ERR(s, "Cannot get %sdisplay profile URL.\n", screenstring); CFRelease(displayInfo); return false;}
    Boolean result = CFURLGetFileSystemRepresentation(customProfileURLs[0], true, (UInt8*)pathBuffer, maxPathSize);
    CFRelease(displayInfo);

    if (!result) MP_ERR(s, "Cannot get %sdisplay profile path.\n", screenstring);
    return result;
}
```

A pseudo code example to call this function would be:

```
void vo_cocoa_update_screen_profile_info(struct vo *vo)
{
    char buffer[PATH_MAX];
    if (get_screen_profile(vo, false, buffer, PATH_MAX)) printf("current screen profile: %s\n", buffer);
    if (get_screen_profile(vo, true, buffer, PATH_MAX)) printf("current fullscreen profile: %s\n", buffer);
}
```

This code example simply prints out the ICC profile paths for the screen and the fullscreen display. I’m not too sure about how **mpv** uses the _vo_cocoa_state_ struct and about the meaning of its _fs_screen_ and _current_screen_ members, and how an update of its values would be triggered during playback.

What do you think?

**Comment by pigoz** [comment]
I implemented the in memory ICC loading in https://github.com/mpv-player/mpv/compare/memory_icc

Seems to work ok here (I still need to split this in two commits and write proper commit messages).

**Comment by UliZappe** [comment]
**:–)**
