### ISSUE TITLE
Parallel prefetch

### ISSUE THREAD

**Issue by juanfra684** [mpv-player/mpv#5940]
I'm using  `--prefetch-playlist=yes` to prefetch the next video on the background while I'm watching the current video. My biggest problem with this feature is that the background download only starts when the download of the current video is ended. Sometimes I give a few urls to mpv and start to watch a video and then I skip the video with [Enter] when I'm not interested. Some servers limits the download speed to the bitrate of the video, so I always need to wait for the initial buffering when I skip the video because the previous video didn't finished the download.

I would like an option to prefetch 2 videos in parallel. The video you are watching and the next video in the list. Maybe with an additional cache to avoid problems with the parallel threads writing data to the main cache. I don't need support for ytdl urls.

**Comment by wm4** [comment]
This should work though? Try with git master.

**Comment by juanfra684** [comment]
I've tried with 0.30 and master. mpv only starts the prefetch when the current video finishes the download.

I've used this command for the tests:
```plain
$ mpv --no-ytdl --prefetch-playlist=yes https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_720p_stereo.ogg http://127.0.0.1:9000/2.webm
```

`2.webm` is in a local server (`python3 -m http.server --bind 127.0.0.1 9000`). The server doesn't show any activity until the current video ends the download.

Can you reopen this issue?.

**Comment by CounterPillow** [comment]
Works for me, I see a request several seconds before the new video starts.
