### ISSUE TITLE
Seeking fails with afir audio filter

### ISSUE THREAD

**Issue by berkley4** [mpv-player/mpv#5941]
### mpv version and platform
mpv 0.28.0-610-g8479449d14
ffmpeg version: N-91217-g2bd24d4a37

Debian unstable 32-bit, running a 64-bit kernel.

### Reproduction steps
Play an audio file with the -start option to trigger an immediate seek...

mpv -v -start=0:10 -external-file s9in.wav -lavfi-complex='[aid1] [aid2] afir [ao]' Guerrilla_Music_-_Elemint.ogg

```
[cplayer] Starting playback...
[lavf] queuing seek to 10.000000
[lavf] queuing seek to 10.000000
[lavf] execute seek (to 10.000000 flags 32)
[lavf] execute seek (to 10.000000 flags 0)
[lavf] seek done
[lavf] seek done
[cplayer] hr-seek, skipping to 10.000000
[lavf] EOF reached.
[lavfi] error on filtering (-22)
```

### Expected behavior
A normal seek.

### Actual behavior
Playback stops as shown above. Manual seeking similarly fails and disabling hr-seek seems to have no effect.

If the file is played without any seeking (ie omitting -start=0:10) then the impulse response filter appears to do its job and the file is played normally.

I would guess that an external file is normally subjected to a seek, and since the impulse response filter is <0.5s in length we get an instant EOF and subsequent filter error.

I've put a link below to the s9in.wav filter from above, which I've designed to emphasise frequencies below 375Hz (and therefore should be obviously audible on headphones).

### Log file
[https://0x0.st/s9XM.txt](https://0x0.st/s9XM.txt)

### Sample files
[https://0x0.st/s9in.wav](https://0x0.st/s9in.wav)
[https://upload.wikimedia.org/wikipedia/commons/0/0d/Guerrilla_Music_-_Elemint.ogg](https://upload.wikimedia.org/wikipedia/commons/0/0d/Guerrilla_Music_-_Elemint.ogg)

**Comment by mfcc64** [comment]
Try this:
mpv -v -start=0:10 -lavfi-complex='amovie=s9in.wav [ir]; [aid1][ir] afir [ao]' Guerrilla_Music_-_Elemint.ogg

**Comment by richardpl** [comment]
As @mfcc64 pointed out you are supposed to use amovie filter.

**Comment by berkley4** [comment]
Thanks @mfcc64, that works perfectly. I'll now close this issue.
