### ISSUE TITLE
stereo3d’s irl/irr requires video-unscaled because scale is done after filters

### ISSUE THREAD

**Issue by galex-713** [mpv-player/mpv#5942]
I own a passive 3D monitor, interlaced (where one row of pixels out of two is polarized differently), but when using filter “stereo3d” in order to convert standard side-by-side video input to interlaced output, the interlace of pixel lines is done on the native resolution of the video, rather than on the resolution of the display / the output / the video output driver.

So for it to have any meaning, it must be used with the video-unscaled option (I took several months before realizing it / having this idea), but then, I can’t just make the video fullscreen, I must watch it at its native resolution, and hope it is not too far from the one of my screen…

Wouldn’t there a way to apply that filter *after* the scaling made by mpv? so one pixel out of two *of my screen* is from the right side of the video.

Otherwise, would there be a way to implement a such feature? so mpv can support displaying natively 3D on any screen itself, without needing an external application or hardware switch (my monitor can convert SBS to interlaced, but only on hdmi, and my laptop only has vga…).

### Sample files

The first image is in the same format I use to find most 3D video on the internet (movies, youtube videos, etc.), the others are the output of the ffmpeg stereo3d filter in irl mode, given respectively sbsl and sbs2l input (I don’t know what would most commonly be the right one given that input ratio). As you can see, if displayed with mpv, by default, each pixel row of these images is 1,5 pixel of the screen (at least it is on my computer), so I get green, yellowish, red, green, yellowish, red, and each color is equally seen by each eye, on average… which is not what is expected (each eye should see only one color, since one is on odd and the other on even rows).

![rg](https://user-images.githubusercontent.com/34247033/41759098-f69d2e64-75ec-11e8-9053-9f34875c1cdd.png)
![rg-sbs2l](https://user-images.githubusercontent.com/34247033/41759099-f6e0dc9a-75ec-11e8-995c-10e526c41bed.png)
![rg-sbsl](https://user-images.githubusercontent.com/34247033/41759101-f73e76b6-75ec-11e8-8297-9377b7d5be72.png)

**Comment by sfan5** [comment]
stereo3d was deprecated (removed?) in 23d9dc5457c52408533c498c685ad9dd6fd2cee0
