### ISSUE TITLE
mpv --loop=4 *.png # seems to me loop 4 only the first.

### ISSUE THREAD

**Issue by enricoT** [mpv-player/mpv#5943]
### mpv version and platform
 pacman -Qi mpv-rpi
Name            : mpv-rpi
Version         : 1:0.28.2-2
Description     : mpv with Raspberry Pi support
Architecture    : armv7h
URL             : https://mpv.io/
Licenses        : GPL3
Groups          : None
Provides        : mpv
Depends On      : desktop-file-utils  ffmpeg-mmal  hicolor-icon-theme  jack  lcms2  libarchive  libcaca
                  libcdio-paranoia  libdvdnav  libgl  libva  libxinerama  libxkbcommon  libxrandr  libxss  libxv
                  lua52  rubberband  smbclient  uchardet  vulkan-icd-loader  wayland  xdg-utils
Optional Deps   : youtube-dl: for video-sharing websites playback [installed]
Required By     : None
Optional For    : None
Conflicts With  : mpv
Replaces        : None
Installed Size  : 3.65 MiB
Packager        : Unknown Packager
Build Date      : Mon Jun 4 21:33:24 2018
Install Date    : Mon Jun 4 21:42:45 2018
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
mpv option --loop 4  *.png # loop 4 only the ifirst png
### Expected behavior
loop all files
### Actual behavior
loop only first time i suspect same behaviour for many options like speed= ....
### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Argon-** [comment]
https://mpv.io/manual/master/#options-loop-playlist

**Comment by jameds** [comment]
I wanted to loop each file in the playlist (which is also my impression of what OP wanted); `--loop-playlist` loops the entire playlist--so each file still only plays once in order.

To illustrate my point:

* `--loop-file=1` - A A B C
* `--loop-playlist=2` - A B C A B C
* What I thought `--loop-file=1` would do - AA BB CC

**Comment by guidocella** [comment]
Use `--loop-file=1 --reset-on-next-file=loop-file`
