### ISSUE TITLE
Not loading subtitle 

### ISSUE THREAD

**Issue by conualfy** [mpv-player/mpv#5946]
### mpv version, platform, what happens
I use Smplayer (latest Ubuntu release from the PPA) with MPV  and I do not know why, but for a specific movie, my subtitles are not loaded. I opened the file, seems to be ok, but for some reason, it does not work. In VLC it works, so it might be a bug in SMplayer. I am attaching the subtitle as .txt file. I have version Smplayer v. 18.5.0 in Ubuntu Linux.

I posted this as a Smplayer bug report and someone posted that is is a MPV bug, deleting the first 3 lines might fix it. But that is actually not a fix, it should just work. This might help. Thank you. 

[Goliath.S02E02.720p.WEB.x26.txt](https://github.com/mpv-player/mpv/files/2130211/Goliath.S02E02.720p.WEB.x26.txt)

**Comment by Akemi** [comment]
instead of filling out the issue template, you just deleted it. also this is not an smplayer support forum.

**Comment by conualfy** [comment]
Might not be, but if Smaplayer uses MPV and this is triggered by MPV, it means it is an MPV issue. But I might be wrong.
