### ISSUE TITLE
Can't play m3u8 until all .ts files are fully downloaded

### ISSUE THREAD

**Issue by evildog1** [mpv-player/mpv#5947]
### mpv version and platform
2017-12-25 by lachs0r
mpv-x86_64-20180617-git-cd89362.7z by shinchiro
Windows 10 1803 x64

### Reproduction steps
Open non live .m3u8. Try sample file below

### Expected behavior
Should play video now while downloading in background like other players, VLC, Kodi etc.

### Actual behavior
Waiting until all .ts files are fully downloaded. This will take 40 min to fully download and I don't want to wait
This same behavior also happen on SVP 4 that is using custom mpv player. If you open m3u8 video from the list on SVPtube 2, mpv player doesn't open but downloads in the background

![image](https://user-images.githubusercontent.com/40234794/41813647-5fbbbfb6-773a-11e8-8cef-87f5d87dbdd9.png)

Only live m3u8 works as i know so far.

### Log file
I executed `mpv.exe -v`
The log is very long because it just downloading. it doesn't open the player
https://pastebin.com/33qeQUwi

### Sample files
Use US VPN if it doesn't work.
[m3u8.zip](https://github.com/mpv-player/mpv/files/2130227/m3u8.zip)

**Comment by tmm1** [comment]
The log shows many errors:

```
[ffmpeg] https: Protocol 'https' not on whitelist 'file,crypto'!
[ffmpeg] crypto: Unable to open resource: https://URL_REMOVED/I00000114.ts?pbs=3fba7a5e6f7b4534b1b8d2e0b77f1fb0&si=0
[ffmpeg/demuxer] hls,applehttp: Failed to open segment 276 of playlist 0
```

FFmpeg is failing to open the segments, which is why it keeps trying each one in the list. Maybe your FFmpeg was not compiled with SSL support.

**Comment by evildog1** [comment]
Are you sure it's ffmpeg related? I tried re-install Win10 and it got same behavior without ffmpeg installed.

MPV can play the main m3u8, no problem with the playback but the problem is it choosed the lowest quality. Very annoying and no open to choose the resolution/quality. There should be an option to select resolution of `#EXT-X-STREAM-INF` written in m3u8

A workaround is to open m3u8 in Notepad++, grab the highest quality of m3u8 file and open it but doesn't work. The behavior I explained above.
This is the URL I grabbed 
![image](https://user-images.githubusercontent.com/40234794/41978863-fc498d00-7a22-11e8-8c7f-cf380d18e5c5.png)

A second workaround is to edit the main m3u8 using Notepad++, remove all other resolutions except 1080p and save. It worked!
I know it's complicated but this is only a way to play the highest quality
This is how the edited main m3u8 looks like with only one `UPLYNK-MEDIA0` and `#EXT-X-STREAM-INF`
```
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",NAME="English",LANGUAGE="en",AUTOSELECT=YES,DEFAULT=YES
#UPLYNK-MEDIA0:1920x1080x30,high-40,2x48000
#EXT-X-STREAM-INF:PROGRAM-ID=1,RESOLUTION=1920x1080,BANDWIDTH=5483210,CODECS="mp4a.40.5,avc1.640028",FRAME-RATE=30.000,AUDIO="aac",AVERAGE-BANDWIDTH=5193753
https://URLREMOVED/i.m3u8?tc=1&exp=1530107386&rn=1131048704&ct=a&cid=06d237baa4c045b3a13190fc46bbb142&ad.pingf=3&ad.customer_id=&ad.nw=&ad.prof=&ad.csid=&ad.vip=xxx.xxx.xxx.xxx&pp2ip=0&ad.cping=1&ad=fw&rays=cdefghiba&v=2&sig=75662a3665690773a7c37cb59affc74e227df8d9656a893a47c22c33c3bee941&pbs=b3bc9dc93262483d8d167c3cdc5cde59
```
