### ISSUE TITLE
[Question] Can we record desktop screen using mpv?

### ISSUE THREAD

**Issue by shishtpal** [mpv-player/mpv#5948]
Hi

Can We record desktop screen using mpv?
I know that we can record desktop screen using ffmpeg, I was thinking the same about mpv.

Thanks

**Comment by Akemi** [comment]
not that i know of. i don't think this is something that should fall into mpv's responsibilities anyway.

**Comment by Hrxn** [comment]
Yeah, this is out of scope, I'd say.

Use something like SimpleScreenRecorder or ScreenToGif, depending on OS, or one of the countless other programs.

**Comment by lachs0r** [comment]
Pretty sure this works with `av://` and the appropriate capture avdevice for your platform though. See https://ffmpeg.org/ffmpeg-devices.html
