### ISSUE TITLE
Chapter-skipping should trigger the "end-file eof" event in Lua, not "end-file stop"

### ISSUE THREAD

**Issue by wynnsyt** [mpv-player/mpv#5949]
### mpv version and platform
mpv 0.28.2
macOS 10.13.5

### Reproduction steps
Play a video with chapter info embedded. Continue to press PGUP until the end of the video.

### Expected behavior
A Lua script with `mp.register_event('end-file', fn)` should trigger the function, with the reason `eof`.

### Actual behavior
The current reason for `end-file` is `stop`, which happens when
> Playback was ended by a command.

Skipping to the end of a video is not any command to stop playback, and mpv treats it as reaching the end of the video by resetting progress and advancing to the next video in the playlist.

It is worth noting that regular seeking does count as reaching EOF. I can't see how this should be any different, as the description of `end-file eof` states that 
> The file has ended.

### Log file
N/A

### Sample files
N/A

**Comment by wm4** [comment]
This should behave exactly like going to the next playlist entry manually (playlist-next command). I'm relatively sure that this works, because it uses the same code. If it doesn't, open a new issue.
