### ISSUE TITLE
Some Arabic Fonts show up in Boxes

### ISSUE THREAD

**Issue by OmrSi** [mpv-player/mpv#5952]
### mpv version and platform
The latest version, Win 10 Pro.
I noticed the issue when using mpv-1.dll with Subtitle Edit, and tested it then noticed it is in MPV.exe for Windows as well.
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
use the font...
[DIMNREG.zip](https://github.com/mpv-player/mpv/files/2139559/DIMNREG.zip)
[AF_Jizan Normal Traditional.zip](https://github.com/mpv-player/mpv/files/2140831/AF_Jizan.Normal.Traditional.zip)

### Expected behavior
Characters showing normally.

### Actual behavior
Showed as boxes.

**Comment by Akemi** [comment]
related to #6456
