### ISSUE TITLE
[Feature Request] Extracting media urls while streaming online media

### ISSUE THREAD

**Issue by potholiday** [mpv-player/mpv#5954]
Let say I can only see videos streaming in a MPV player and terminal is hidden. Is there any way to extract urls for the streaming videos from mpv player itself.

**Comment by j605** [comment]
Use a key binding to show the relevant information in `input.conf`
```
<key> show-text "${path}"
```

**Comment by potholiday** [comment]
@j605  is there a way to copy it in clipboard?

**Comment by Argon-** [comment]
See https://github.com/mpv-player/mpv/issues/4695#issuecomment-318997604
