### ISSUE TITLE
Non-existent mp3 stream is shown when playing Blu-ray with "demuxer-readahead-secs" set

### ISSUE THREAD

**Issue by macdavis** [mpv-player/mpv#5955]
### mpv version and platform
mpv version: 861c102
platform: MacOS 10.13.5 (17F77)

### Reproduction steps
Play some certain Blu-ray with "`demuxer-readahead-secs=100`"

### Actual behavior
mpv shows a mp3 stream that doesn't exist. 
### Log file

[BD_demuxer-readahead-secs.log](https://0x0.st/sprW.log)
[BD_normal.log](https://0x0.st/spr4.log)

### Sample files
Can't provide the Blu-ray ISO.

**Comment by wm4** [comment]
The logs disappeared. Even so I believe this is a ffmpeg issue.
