### ISSUE TITLE
Video rendering delayed indefinitely when other video app is running

### ISSUE THREAD

**Issue by mzso** [mpv-player/mpv#5957]
### mpv version and platform

0.28.0 x86-64 Windows 8.1
Graphics adapter: NVIDIA GeForce GTS450 (NVIDIA GeForce GTS450)

### Reproduction steps
-Have a mediaplayer or a tuner app running
-open a file with mpv
-audio plays, nothing is shown. Audio/Video desynchronization warning is shown.

### Expected behavior
Show video immediately when playback starts

### Actual behavior
The appearance of the video window is delayed. Several seconds at least. Sometimes it seems to be delayed indefinitely.
Pausing the other player or even resizing it's window makes the video appear for mpv immediately.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/2149646/output.txt)

Here's the log from an occasion when this issue presented itself. Started playback. After several seconds of not showing video I resized the other app's window. The video immediately appeared. It showed video in fast forward, for a second or so. Then played normally. After which I closed mpv.

**Comment by mzso** [comment]
Another log:
[output.txt](https://github.com/mpv-player/mpv/files/2149687/output.txt)

This time I waited for a full four minutes. The audio eventually stopped playing (probably the whole playback), but otherwise it was the same. Fast forwarding of the video of course lasted much longer because of the the longer before it caught up to the point where the audio stopped.

**Comment by mzso** [comment]
It's still happening with 0.29.1.

It may have even gotten worse. At least I didn't notice a jarring invisible full screen window before, while MPV was hung, and unable to show video.

**Comment by mzso** [comment]
Due to my recent tinkering with settings it seems like only the "gpu" renderer is affected and not "direct3d".
It seems like I don't experience delays with the latter at all.

**Comment by mzso** [comment]
It also seems like only directd11 is affected. The issue doesn't seem to present itself when using other gpu-context options that function (win, dxinterop).

**Comment by Dudemanguy** [comment]
Does this issue still occur?

**Comment by mzso** [comment]
Uncertain.
I changed the vo to GPU and api to d3d11, and I experienced no huge delays

However it was years ago and the circumstances changed, I'm not using the GTS 450, or an Nvidia card at all. Now I have an RX580. I'm also on Windows 10 now.

**Comment by Dudemanguy** [comment]
Will close this for now given the uncertainty.
