### ISSUE TITLE
OSD gives wrong info about video-aspect

### ISSUE THREAD

**Issue by iamCristYe** [mpv-player/mpv#5959]
### mpv version and platform
git-861c102 on Windows 10

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
open a 16:9 video
Use Shift a to change the aspect ratio for several times

### Expected behavior
OSD displays the correct aspect ratio:
1.333 2.350 1.778

### Actual behavior
OSD displays:
1.333 2.350 2.349

Note: This might be related with the default input.conf
`#A cycle-values video-aspect "16:9" "4:3" "2.35:1" "-1"`

**Comment by leigh123linux** [comment]
I see the same

```
$ rpm -q mpv
mpv-0.29.0-1.fc29.x86_64
```

```
$ inxi -S
System:    Host: localhost.localdomain Kernel: 4.18.0-0.rc7.git0.1.fc29.x86_64 x86_64 bits: 64 
           Desktop: Cinnamon 3.8.8 Distro: Fedora release 29 (Rawhide) 
```

**Comment by wm4** [comment]
This was changed, please test again with mpv git master.
