### ISSUE TITLE
MPV freezes when constantly creating and destroying multiple videos with PureData

### ISSUE THREAD

**Issue by fitipe** [mpv-player/mpv#5964]
### mpv version and platform

mpv 0.27.0 running on a RaspBerry Pi 3 B

### Story

I've been using a software called puredata to call mpv and play videos randomly. What it does is to periodically send a message ( mpv  /my/file/directory/file.mov  ) to an object called shell that throws it into the terminal.

I also set --speed,  --start, --length with randomly generated values. 

It plays beautifully for 5 to 10 minutes and then it freezes on a frame. Puredata keeps running behind and I can hear the audio of the videos, still selected ramdomly, but all I can see is the same frozen image. Another problem ( always present ) is that while any videos are played with this mechanism, I have no interactive controls. So, when it freezes, I have no option left than pulling the raspberry's energy plug and turn it on again. 
It does not necessarily always freezes at the same video - the problem is not on the file.

Trying to figure out possible causes, I accessed the raspberry through a vnc server and launched the program using my notebook connected with a network cable, leaving the hdmi to the television. So I could watch the videos running on the tv and visualize puredata's patch at the same time. So, on the tv there were the videos playing one after another and, on the notebook's screen, there was only the patch running.

It froze again but, unexpectedly, mpv was forced to switch it's main VO option and begun to run it into the vnc-server's screen, on my notebook. And never froze at this one. The audio kept been played on the television! Also, on the vnc-server's screen, I have all the interactive controls back.

I found out that, when it freezes, mpv is no longer capable of setting the video output to "rpi". Instead, it tries to set it to a bunch of options and the only possible one is "x11" - which runs on the vnc server, opened on my notebook. I've tried it with two different Tvs.

Do someone have any ideias? 

I have no understanding on coding, but I've been digging around a lot trying to find it out ...

Thanks a lot!!

### Expected behavior

Running videos randomly using puredata.

### Actual behavior

It runs for a while, then it freezes on a single frame.

### Log file

Is it possible to make a log file when I'm using another program ( PureData ) to call an mpv command?

### Sample files

![captura de tela 2018-07-05 as 03 57 56](https://user-images.githubusercontent.com/39530456/42308032-bdeb7120-800a-11e8-8783-516ec1d668c7.png)

![captura de tela 2018-07-03 as 20 13 44](https://user-images.githubusercontent.com/39530456/42254780-adc4ce50-7f1e-11e8-9ffb-0d6998a3160c.png)

**Comment by lachs0r** [comment]
First, make sure you actually do something about the warnings that mpv prints. Your graphics stack is broken. Install the proprietary VC4 stuff and try again. Also, mpv with X11 or Wayland on RPi is not going to be pretty or fast. You can only expect it to perform somewhat okay-ish when it has exclusive display access. I’m afraid you are wasting your time with this garbage hardware.

**Comment by COOLIRON2311** [comment]
@lachs0r This 'garbage hardware' supports 3D Blu-ray disks.
