### ISSUE TITLE
distorted display - MAC High Sierra w/ iTerm2

### ISSUE THREAD

**Issue by janskey** [mpv-player/mpv#5967]
OS: Mac 10.13.5 High Sierra; iTerm2

When I play a youtube link, the display is distorted. I use this command:

> DISPLAY= mpv --log-file=/Users/kickr/output.txt -vo caca https://youtu.be/mRf3-JkwqfU?t=11s

![screen shot 2018-07-06 at 6 56 17 pm](https://user-images.githubusercontent.com/11430512/42375655-ca4711dc-814e-11e8-9e51-c52984f16a06.png)

I've installed MPV via brew:

> brew install mpv --with-libca

**Comment by lachs0r** [comment]
I’m not sure what you expect when using caca. That video output is meant to do just that.

**Comment by janskey** [comment]
how to play inside the terminal without using "caca"? by the way, attached log:

> https://gist.github.com/janskey/8b1c4a18cd6442c8d8352e6b635d88a9

**Comment by janskey** [comment]
what do you mean by "kitty and alacritty"? what is the syntax or how to execute them?
