### ISSUE TITLE
git master compile error on macOS 10.12.6

### ISSUE THREAD

**Issue by liberize** [mpv-player/mpv#5968]
### mpv version and platform

HEAD, macOS 10.12.6

### Reproduction steps

build mpv with `--enable-libmpv-shared`

### Expected behavior

build success

### Actual behavior

build failed with error:
ld: framework not found ColorSync for architecture x86_64

### Log file

https://gist.github.com/liberize/bed5f58c06bf753979e3f0a77ade3d8d

### Additional Infomation

1. Remove `--enable-libmpv-shared`, it compiles.

2. Latest release 0.28.2 doesn't have this problem.

3. Tried add `LDFLAGS='-F/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks'`, the error message become:

Undefined symbols for architecture x86_64:
  "_MTLCopyAllDevicesWithObserver", referenced from:
      __T05Metal29MTLCopyAllDevicesWithObserverSaySo9MTLDevice_pG7devices_So8NSObjectC8observertySoAC_p_SC0G16NotificationNameVtc7handler_tF in libswiftMetal.a(Metal.o)
  "_NSURLVolumeAvailableCapacityForImportantUsageKey", referenced from:
      __T010Foundation17URLResourceValuesV40volumeAvailableCapacityForImportantUsages5Int64VSgfg in libswiftFoundation.a(Foundation.o)
  "_NSURLVolumeAvailableCapacityForOpportunisticUsageKey", referenced from:
      __T010Foundation17URLResourceValuesV44volumeAvailableCapacityForOpportunisticUsages5Int64VSgfg in libswiftFoundation.a(Foundation.o)
  "__dispatch_source_type_data_replace", referenced from:
      __T0So14DispatchSourceC0A0E019makeUserDataReplaceB0So0abdeF0_pSo0A5QueueCSg5queue_tFZ in libswiftDispatch.a(Dispatch.o)
ld: symbol(s) not found for architecture x86_64

**Comment by liberize** [comment]
@Akemi Confirmed. Thanks.

**Comment by Akemi** [comment]
we can close this when the PR is applied.
