### ISSUE TITLE
HDR tone mapping (kind of) broken

### ISSUE THREAD

**Issue by madshi** [mpv-player/mpv#5969]
### mpv version and platform

Problem occurs with any of the newer shinchiro Windows builds (e.g. July, 1st 2018). Builds from early May work better.

### Reproduction steps

Play Mad Max Fury Road, timecode 0:28:27, using default settings.

### Expected behavior

Should show nicely tone mapped image.

### Actual behavior

Tone mapped image looks rather ugly (dark gray explosion).

### Sample files

Here are 2 screenshots, showing May vs July build. Early May build look ok. Not great but ok. July build is screwed up. This explosion is supposed to be red(ish), not gray.

![mpv0518_100nits](https://user-images.githubusercontent.com/977539/42413287-bd5b2fec-821d-11e8-9074-ea64a9335472.png)
![mpv0718_100nits](https://user-images.githubusercontent.com/977539/42413288-bd743d16-821d-11e8-93fd-ae597c551087.png)

**Comment by lachs0r** [comment]
Please post the logs, or at least the exact commit hashes from mpv’s terminal output.

**Comment by madshi** [comment]
I'm sorry, I'm a total mpv noob. How do I get the commit hashes or the log? In any case, it should be easy for you to verify/double check, using any newer mpv build on any platform. Personally, it's not important for me if you fix this or not. Just wanted to let you guys know about the problem, as a common courtesy.

P.S: To give you a reference, here's how the same frame looks like when using:

target-peak=4000
tone-mapping=clip

So this shows how the explosion is actually encoded in the movie file. It's supposed to be red/orange, not gray or purple-ish red.

![mpv_4000nits_clip](https://user-images.githubusercontent.com/977539/42413501-21dbd5a8-8222-11e8-9c78-c27c1fce4ed3.png)

**Comment by jeeb** [comment]
I think this might be up to the SPIR-V compiler version (or shaderc, or a combination of these).

I just had @rossy ask me if the brightness calculation had ever worked yesterday, which from mpv's side most definitely did.

Most easily detectable if there's a difference between `--gpu-context=win` and the default (d3d11).

**Comment by jeeb** [comment]
As for logs, `log-file=mpv_sucks.log` should write one in the current working directory (or you can define a full path)

**Comment by madshi** [comment]
Haha, cool file name...  :)

Here are the log files for May and July builds. Using "--gpu-context=win" doesn't seem to change anything.

[mpv_May.log](https://github.com/mpv-player/mpv/files/2172978/mpv_May.log)
[mpv_July.log](https://github.com/mpv-player/mpv/files/2172979/mpv_July.log)

**Comment by Akemi** [comment]
seems like the only relevant commit that [changed](https://github.com/mpv-player/mpv/compare/11289d5238...861c10268d) something related to tone-mapping is [this](https://github.com/mpv-player/mpv/commit/5056777b861230abb45c66b50bd2198846915f29).

if it isn't related to the spirv compiler or shaderc version.

**Comment by jeeb** [comment]
OK, if there's a difference with `gpu-context=win` then that's generally the part with the least amount of things in the middle (native opengl as opposed to shaders getting recompiled to HLSL and then shown with a d3d11 swap chain). The difference in mpv's own code between those two versions is [as follows](https://github.com/mpv-player/mpv/compare/11289d5238...861c10268d).

The two commits that pop out of that area for tone mapping are 5056777b861230abb45c66b50bd2198846915f29 and 05b392bc949e918aaedb6383193edfd667bba646 .

Most likely it is the former, which was reviewed [here](https://github.com/mpv-player/mpv/pull/5848), where I poked it against a few of the things I have at hand.

**Comment by jeeb** [comment]
Anyways, I will try to get my hands on a sample of that clip and see how it fares, as I don't really have a too wide collection of HDR samples and they all seemed to tone map relatively nicely for me (Sony/LG PQ sample clips, TravelXP HLG test airing clip, and UHD BDs of Shin Godzilla and Your Name).

@haasn does have another set of clips, against which he has been developing both mpv's gpu vo and libplacebo.

**Comment by madshi** [comment]
FWIW, some of these Mad Max scenes make for a really hard workaround for a tone mapping algorithm, so I think it's worth having in your sample collection.

**Comment by haasn** [comment]
According to [the metadata here](http://up-cat.net/p/259cd966), the mad max movie is mastered like this:

```
Mastering display luminance              : min: 0.0050 cd/m2, max: 4000 cd/m2
Maximum Content Light Level              : 9918 cd/m2
Maximum Frame-Average Light Level        : 3241 cd/m2
```

That's just insane, and I think also explains why mpv's tone mapping has a hard time with it - those numbers are an order of magnitude higher than what the tone mapping algorithm was tested/developed for.

**Comment by jeeb** [comment]
So I received my copy of this UHD BD in the mail today, and... yea, there's no way this movie is mastered like this other than to maximize brightness. Loudness wars became... brightness wars? Except if you actually showed this thing at its actual brightness it'd make you quite blind.

I am not sure how simple it'd be to notice such content and minimize/disable desaturation for it (for now one can manually set `--tone-mapping-desaturate=0` to disable desaturation).

**Comment by haasn** [comment]
I mean in theory the mpv desaturation algorithm already changed once to avoid over-desaturating very bright content like this, but apparently that change wasn't enough?

**Comment by madshi** [comment]
It's not just the desaturation, though. Newer mpv builds also render the luminance of the explosion much too dark. It's barely brighter than the rest of the frame. See screenshots. Older mpv builds handled this scene somewhat better. Well, at least the luminance looked ok with older mpv builds.

**Comment by Doofussy2** [comment]
FWIW I find the HDR/PQ picture generally too dark. Now I use tone-mapping=mobius, and the picture is notably better.

**Comment by madshi** [comment]
Looking ok now with the latest mpv changes.
