### ISSUE TITLE
Tearing and jitter in h.264 stream with HW-decoding using AMD RX550 vaapi or vdpau

### ISSUE THREAD

**Issue by aro234** [mpv-player/mpv#5971]
### mpv version and platform
mpv built on Jul  8 2018 using mpv-build
  commit 4bf9a78b364483f2c4f0ee429510f32f891932bc (HEAD -> master, origin/master, origin/HEAD)
  Author: Jan Ekström <jeebjp@gmail.com>
  Date:   Sun Jul 8 02:59:17 2018 +0300
    wscript_build: fixup swift include parameter to point to source root

Debian testing 
Linux 4.16.16
libva 2.1.0
libvdpau 1.11
Mesa 18.1.3

### Reproduction steps
When playing the following stream

  https://derste247livede.akamaized.net/hls/live/658317/daserste_de/master.m3u8 
    (this is german government/tax funded TV "ARD" aka "Das Erste Programm")

with mpv using vaapi or vdpau HW decoding supplied by a AMD RX550 with 
the picture exhibits jitter, corruption and non-horizontal tearing.

The OS is Linux 4.16.16 (Debian testing aka "Buster").

Since my PC has an Intel core i5 3550 CPU with on-chip graphics HD2500
I can alternatively use HD2500 for HW decoding by selecting option --hwdec=vaapi-copy.
Using Intel HD2500 HW decoding, the issue is NOT seen.

So the flaw is very likely either 
 - in mpv code that interfaces with AMD vaapi and vdpau HW decoding
or 
 - in the AMD RX 550 HW decoding firmware (and has to be re-assigned to AMD).

Command lines to reproduce the bug:
mpv --no-config --hwdec=vaapi --vo=gpu --gpu-context=x11egl --fs https://derste247livede.akamaized.net/hls/live/658317/daserste_de/master.m3u8

mpv --no-config --hwdec=vdpau --vo=gpu --fs https://derste247livede.akamaized.net/hls/live/658317/daserste_de/master.m3u8

The issue is very prominent while using -hwdec=vaapi --vo=gpu --gpu-context=x11egl, 
and if the mpv window is full screen.
My monitor has a resolution of 3840x2160 (Ultra HD in aspect ratio 16:9), the stream is 1280*720

Using vdpau, the issue is seen less frequently.

### Expected behavior
flawless picture

### Actual behavior
tearing, corruption and jitter as described above

### Log file

arohde@debi2 ~/SW > /home_SG2000/arohde_cache/SW/mpv/mpv-build/mpv/build/mpv --no-config --hwdec=vaapi --vo=gpu --gpu-context=x11egl --fs --msg-level=vd=v,vo=v https://derste247livede.akamaized.net/hls/live/658317/daserste_de/master.m3u8                                                                                                  

Playing: https://derste247livede.akamaized.net/hls/live/658317/daserste_de/master.m3u8
[ffmpeg/video] h264: Increasing reorder buffer to 2
[ffmpeg/video] h264: Increasing reorder buffer to 2
[ffmpeg/video] h264: Increasing reorder buffer to 2
[ffmpeg/video] h264: Increasing reorder buffer to 2
[ffmpeg/video] h264: Increasing reorder buffer to 2
[ffmpeg/video] h264: Increasing reorder buffer to 2
[ffmpeg/video] h264: Increasing reorder buffer to 2
[ffmpeg/video] h264: Increasing reorder buffer to 2
[ffmpeg/video] h264: Increasing reorder buffer to 2
[ffmpeg/video] h264: Increasing reorder buffer to 2
     Video --vid=1 'bitrate 365773' (h264 320x180 50.000fps)
     Video --vid=2 'bitrate 365773' (h264 320x180 50.000fps)
     Video --vid=3 'bitrate 534956' (h264 480x270 50.000fps)
     Video --vid=4 'bitrate 534956' (h264 480x270 50.000fps)
     Video --vid=5 'bitrate 873321' (h264 512x288 50.000fps)
     Video --vid=6 'bitrate 873321' (h264 512x288 50.000fps)
     Video --vid=7 'bitrate 1550052' (h264 640x360 50.000fps)
     Video --vid=8 'bitrate 1550052' (h264 640x360 50.000fps)
     Video --vid=9 'bitrate 2575721' (h264 960x540 50.000fps)
     Video --vid=10 'bitrate 2575721' (h264 960x540 50.000fps)
     Video --vid=11 'bitrate 3500939' (h264 960x540 50.000fps)
     Video --vid=12 'bitrate 3500939' (h264 960x540 50.000fps)
 (+) Video --vid=13 'bitrate 4933704' (h264 1280x720 50.000fps)
     Video --vid=14 'bitrate 4933704' (h264 1280x720 50.000fps)
     Audio --aid=1 'bitrate 365773' (aac 2ch 48000Hz)
     Audio --aid=2 'bitrate 365773' (aac 2ch 48000Hz)
     Audio --aid=3 'bitrate 534956' (aac 2ch 48000Hz)
     Audio --aid=4 'bitrate 534956' (aac 2ch 48000Hz)
     Audio --aid=5 'bitrate 873321' (aac 2ch 48000Hz)
     Audio --aid=6 'bitrate 873321' (aac 2ch 48000Hz)
     Audio --aid=7 'bitrate 1550052' (aac 2ch 48000Hz)
     Audio --aid=8 'bitrate 1550052' (aac 2ch 48000Hz)
     Audio --aid=9 'bitrate 2575721' (aac 2ch 48000Hz)
     Audio --aid=10 'bitrate 2575721' (aac 2ch 48000Hz)
     Audio --aid=11 'bitrate 3500939' (aac 2ch 48000Hz)
     Audio --aid=12 'bitrate 3500939' (aac 2ch 48000Hz)
 (+) Audio --aid=13 'bitrate 4933704' (aac 2ch 48000Hz)
     Audio --aid=14 'bitrate 4933704' (aac 2ch 48000Hz)
[vo/gpu/opengl] Initializing GPU context 'x11egl'
[vo/gpu/x11] X11 opening display: :0
[vo/gpu/x11] X11 running at 3840x2160 (":0" => local display)
[vo/gpu/x11] Assuming DPI scale 2 for prescaling. This can be disabled with --hidpi-window-scale=no.
[vo/gpu/x11] Detected wm supports NetWM.
[vo/gpu/x11] Detected wm supports ABOVE state.
[vo/gpu/x11] Detected wm supports BELOW state.
[vo/gpu/x11] Detected wm supports FULLSCREEN state.
[vo/gpu/x11] Detected wm supports STAYS_ON_TOP state.
[vo/gpu/x11] Display 0 (DisplayPort-2): [0, 0, 3840, 2160] @ 59.996625 FPS
[vo/gpu/x11] Current display FPS: 59.996625
[vo/gpu/opengl] EGL_VERSION=1.5 (DRI2)
[vo/gpu/opengl] EGL_VENDOR=Mesa Project
[vo/gpu/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES 
[vo/gpu/opengl] Trying to create Desktop OpenGL context.
[vo/gpu/opengl] chose visual 0x21
[vo/gpu/opengl] GL_VERSION='4.5 (Core Profile) Mesa 18.1.3'
[vo/gpu/opengl] Detected desktop OpenGL 4.5.
[vo/gpu/opengl] GL_VENDOR='X.Org'
[vo/gpu/opengl] GL_RENDERER='Radeon RX 550 Series (POLARIS12, DRM 3.23.0, 4.16.0-2-amd64, LLVM 6.0.1)'
[vo/gpu/opengl] GL_SHADING_LANGUAGE_VERSION='4.50'
[vo/gpu/opengl] Loaded extension GL_NV_vdpau_interop.
[vo/gpu] Testing FBO format rgba16
[vo/gpu] Using FBO format rgba16.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Assuming 59.996625 FPS for display sync.
[vd] Container reported FPS: 50.000000
[vd] Codec list:
[vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     h264_v4l2m2m (h264) - V4L2 mem2mem H.264 decoder wrapper
[vd] Opening decoder h264
[vd] Looking at hwdec h264-vaapi...
[vo/gpu] Loading hwdec driver 'vaapi-egl'
[vo/gpu/vaapi-egl] Trying to open a x11 VA display...
[vo/gpu/vaapi-egl/vaapi] libva: VA-API version 1.1.0
[vo/gpu/vaapi-egl/vaapi] libva: va_getDriverName() returns 0
[vo/gpu/vaapi-egl/vaapi] libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
[vo/gpu/vaapi-egl/vaapi] libva: Found init function __vaDriverInit_1_1
[vo/gpu/vaapi-egl/vaapi] libva: va_openDriver() returns 0
[vo/gpu/vaapi-egl/vaapi] Initialized VAAPI: version 1.1
[vo/gpu/vaapi-egl] using VAAPI EGL interop
[vo/gpu/vaapi-egl] Supported formats:
[vo/gpu/vaapi-egl]  nv12
[vo/gpu/vaapi-egl]  p010
[vo/gpu/vaapi-egl]  yuv420p
[vo/gpu/vaapi-egl]  bgra
[vo/gpu/vaapi-egl]  rgba
[vo/gpu/vaapi-egl]  bgr0
[vo/gpu/vaapi-egl]  rgb0
[vo/gpu] Loading hwdec driver 'vdpau-glx'
[vo/gpu] Loading failed.
[vd] Trying hardware decoding via h264-vaapi.
[vd] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[vd] Pixel formats supported by decoder: vdpau vaapi_vld yuv420p
[vd] Codec profile: High (0x64)
[vd] Requesting pixfmt 'vaapi_vld' from decoder.
Using hardware decoding (vaapi).
[vd] Decoder format: 1280x720 vaapi[nv12] bt.709/bt.709/bt.1886/limited/auto CL=mpeg2/4/h264 (auto 0.000000/0.000000/0.000000)
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1280x720 vaapi[nv12]
[vo/gpu] reconfig to 1280x720 vaapi[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vo/gpu/x11] not waiting for MapNotify
[vo/gpu] Resize: 2560x1440
[vo/gpu] Window size: 2560x1440
[vo/gpu] Video source: 1280x720 (1:1)
[vo/gpu] Video display: (0, 0) 1280x720 -> (0, 0) 2560x1440
[vo/gpu] Video scale: 2.000000/2.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
[vo/gpu] Testing FBO format rgba16
[vo/gpu] Using FBO format rgba16.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Resize: 3840x2160
[vo/gpu] Window size: 3840x2160
[vo/gpu] Video source: 1280x720 (1:1)
[vo/gpu] Video display: (0, 0) 1280x720 -> (0, 0) 3840x2160
[vo/gpu] Video scale: 3.000000/3.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
AV: 00:00:00 / 00:00:02 (0%) A-V:  0.000 Cache:  2s+1MB
[vo/gpu/x11] Disabling screensaver.
AV: 00:00:00 / 00:00:02 (0%) A-V:  0.000 Cache:  2s+1MB
[vo/gpu/x11] Disabling screensaver failed (4). Make sure the xdg-screensaver script is installed.
AV: 00:00:02 / 00:00:09 (27%) A-V:  0.000 Cache:  7s+3MB
[vd] Uninit decoder.
[vo/gpu/x11] Enabling screensaver.

Exiting... (Quit)

### Sample files
  https://derste247livede.akamaized.net/hls/live/658317/daserste_de/master.m3u8 
    (this is a live stream, german government/tax funded TV "ARD" aka "Das Erste Programm")

**Comment by aro234** [comment]
The issue is also reproducible with videos from 
http://jell.yfish.us/

I see triangular tearing in the upper right of the picture with this video:
http://jell.yfish.us/media/jellyfish-10-mbps-hd-hevc-10bit.mkv
using following options for VAAPI:
   --no-config --hwdec=vaapi --vo=gpu --gpu-context=x11egl --fs

**Comment by Jj0YzL5nvJ** [comment]
TearFree to auto sucks, at least on xorg. Force the activation using `xrandr`. Example:
`xrandr --output DisplayPort-0 --set TearFree on`

 Replace "DisplayPort-0" with your output pointed out by xrandr.

**Comment by aro234** [comment]
Hi  Jj0YzL5nvJ ,

tearfree is enabled in xorg.conf.

You might have overlooked the following sentence:
   "Using Intel HD2500 HW decoding, the issue is NOT seen."

To be more accurate:  
   "Using Intel HD2500 HW decoding _and AMD RX 550 for X11_, the issue is NOT seen."

Please also pay attention to
  "I see **triangular tearing** in the upper right of the picture with this video: "

Normal tearing lines (without using tearfree mode of AMD or Intel Xorg drivers or a compositor)
**always horizontal**.

Did you try to play the URL stream or the jellyfish movies I referenced?

**Comment by Jj0YzL5nvJ** [comment]
> tearfree is enabled in xorg.conf.

I used to do that long ago, but that disabled KMS Pageflipping (I don't give a dime). But now I can have both sacrificing nothing.

> Did you try to play the URL stream or the jellyfish movies I referenced?

```
jellyfish-250-mbps-4k-uhd-h264.mkv
jellyfish-110-mbps-hd-hevc.mkv
jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
```
Those three are part of my test to look for regressions, along with many others.

Out there exist many similar reports to this: #4873 #5305 #5711 #5298
The only thing I can say is that I don't share your issue. I don't have such problem ...[I have others](https://github.com/mpv-player/mpv/issues/5711#issuecomment-389349661).
What I can do is give you info to help you to figure out how to solve your problem.

### mpv version and platform
Xbuntu 16.04.5 LTS / AMD64
mpv 0.28.0-638-g08a6827b3d
$ ffmpeg -version
```
ffmpeg version N-91498-g9888a19db4 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8 (Ubuntu 8.1.0-5ubuntu1~16.04)
configuration: --prefix=/usr/local --arch=amd64 --cpu=amd64 --cc=gcc-8 --cxx=g++-8 --extra-ldflags=-L/usr/local/lib --enable-gpl --enable-nonfree --enable-shared --enable-libfdk-aac --enable-libmp3lame --enable-librtmp --enable-libtls --enable-opengl --enable-libpulse --disable-debug --enable-libass --enable-libbluray --enable-libcaca --enable-libcdio --enable-libvpx --enable-libvorbis --enable-libtheora --enable-libopus --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
libavutil      56. 18.102 / 56. 18.102
libavcodec     58. 21.105 / 58. 21.105
libavformat    58. 17.101 / 58. 17.101
libavdevice    58.  4.101 / 58.  4.101
libavfilter     7. 26.100 /  7. 26.100
libswscale      5.  2.100 /  5.  2.100
libswresample   3.  2.100 /  3.  2.100
libpostproc    55.  2.100 / 55.  2.100
```
$ vainfo
```
libva info: VA-API version 0.40.1
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.40 (libva 1.8.4.pre1)
vainfo: Driver version: Mesa Gallium driver 18.2.0-devel for Radeon RX 560 Series (POLARIS11, DRM 3.23.0, 4.15.0-29-generic, LLVM 6.0.1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

### Log file
The only functional and relevant "hardware decoding" that currently works on MY BUILD using `gpu` with **8-bit H.264** videos
[vdpau](https://0x0.st/sVow.txt)
[vdpau-copy](https://0x0.st/sVox.txt)
[x11vk + vdpau-copy](https://0x0.st/sVo3.txt)
[vaapi-copy](https://0x0.st/sVoY.txt)
[x11vk + vaapi-copy](https://0x0.st/sVog.txt)

### Sample files
http://www.jell.yfish.us/
`jellyfish-250-mbps-4k-uhd-h264.mkv`

**Comment by aro234** [comment]
Hi Jj0YzL5nvJ,
thanks for your time and help.

> The only functional and relevant "hardware decoding" that currently works on MY BUILD using gpu with > 8-bit H.264 videos

**My main point is actually to get the only one working HW decoding mode for 10bit HEVC videos fixed:
    --hwdec=vaapi --vo=gpu --gpu-context=x11egl** 

Now for some important new finding:

**I just noticed that deactivating mpv's internal anti-tearing/vsync mode by using
  --opengl-swapinterval=0 --vulkan-swap-mode=immediate
while using AMDGPU tearfree mode _seems_ to fix the problem for
  --hwdec=vaapi --vo=vaapi
  --hwdec=vdpau --vo=vdpau
and all flavors of 
  --hwdec=vaapi-copy ... 
  --hwdec=vdpau-copy ...** 

**However it does _not_ fix the issue for
   --hwdec=vaapi --vo=gpu --gpu-context=x11egl**

So the bug report is still valid.

Please note: I wrote "_seems_" above since I haven't found the time to test it thoroughly.

This finding implies that mpv's default anti tearing mode
  --opengl-swapinterval=1 --vulkan-swap-mode=auto
is either buggy or might clash with the AMD drivers's tearfree option.

It might be useful to disable mpv's anti-tearing mode in case a compositor
or driver using Vsync/tearfree is detected. 
The stupid part here is that xrandr does not support  to query the mode
(there's is no --get <property>). I did not check for all possible compositors.

I have rebuild mpv yesterday to enable Vulkan support.
mpv build options are: 
     --enable-lua --lua=luajit --enable-shaderc

mpv was trying to use the Shader Compiler 'nvidia' instead of 'shaderc',
 ( see   mpv/video/out/gpu/spirv.c )
which AFAIK works only for NVidia cards.

Since Debian testing lacks a shaderc package, I also had to build 
   Google shaderc (https://github.com/google/shaderc)
myself to make mpv option
  --gpu-context=x11vk  
work. 

Above results were using : 
 /home/arohde/SW/mpv/mpv-build/mpv/build/mpv -V
mpv 0.28.0-638-g08a6827b3d Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sat Jul 21 14:47:09 CEST 2018
ffmpeg library versions:
   libavutil       56.18.102
   libavcodec      58.21.106
   libavformat     58.17.101
   libswscale      5.2.100
   libavfilter     7.26.100
   libswresample   3.2.100
ffmpeg version: N-91502-g9617178800

**Comment by aro234** [comment]
Accidentally hit "Close and comment" instead of "Comment"

**Comment by Jj0YzL5nvJ** [comment]
$ cat /var/log/Xorg.0.log | grep -i tear
`[    17.247] (==) AMDGPU(0): TearFree property default: auto`
$ cat /var/log/Xorg.0.log | grep -i page
`[    17.247] (II) AMDGPU(0): KMS Pageflipping: enabled`
$ cat /var/log/Xorg.0.log | grep -i shadow
null
$ cat /var/log/Xorg.0.log | grep -i swap
```
[    17.520] (II) AIGLX: enabled GLX_INTEL_swap_event
[    17.521] (II) AIGLX: enabled GLX_SGI_swap_control and GLX_MESA_swap_control
```

**Comment by aro234** [comment]
All,

**Linux Kernel 4.17.8 was made available for Debian testing yesterday and FIXED the issue.**

**If you see the issue descibed above and run 4.16 (or maybe 4.15): 
   upgrade to Linux 4.17 and give it a try!**

@  Jj0YzL5nvJ :  

Regarding _tearfree vs KMS Pageflipping:_
your distro seems to be quite a bit older than Debian testing. 
Both features can coexist, see 
https://cgit.freedesktop.org/xorg/driver/xf86-video-amdgpu/log/?ofs=50
following commits (and others for DRI3 I think):
2017-08-22 | Always allow DRI2 page flipping with TearFree | Michel Dänzer | 2 | -6/+2
2017-08-22 | Always allow Present page flipping with TearFree | Michel Dänzer | 4 | -23/+152

With tearfree enabled I occasionally see 
[  3923.544] (WW) AMDGPU(0): flip queue failed: Device or resource busy
[  3923.544] (WW) AMDGPU(0): Page flip failed: Device or resource busy
[  3923.544] (EE) AMDGPU(0): present flip failed

It does not seem to be a real issue.

The AMDGPU driver supports both DRI2 and 3:
[    24.437] (II) glamor: OpenGL accelerated X.org driver based.
[    24.447] (II) glamor: EGL version 1.5 (DRI2):
    :         :  
[    24.458] (==) AMDGPU(0): DRI3 enabled

Thank you very much!
