### ISSUE TITLE
[Question] how to reset volume between playlist tracks

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#5973]
currently i set playlist to not auto play
then i interrogate mpv every 100mS for paused state (end of song)
then i reset volume and un pause.

but this is unreliable.

is there a better method, maybe using a lua script or some other way?

(windows envir.)

**Comment by mia-0** [comment]
Looks like no one bothered to reply in 2 years but in case anyone else runs across this issue: 

See the [--reset-on-next-file](https://mpv.io/manual/master/#options-reset-on-next-file) option.
