### ISSUE TITLE
Scaling in the MPV as in MPС-HC

### ISSUE THREAD

**Issue by UnknownGod4** [mpv-player/mpv#5976]
Hello! I apologize in advance, because I do not know English and use Google translator.
I would like to know how I can scale the video in MPV to get rid of the black bars from below and from above?
In MPC-HC, I use the Pan & Scan setting - Set the aspect ratio to 16: 9 TV.
And MPC used zoom only in height.
How can I adjust the zoom in MPV so that it does the same?
I hope the screenshots help to clarify.

![775](https://user-images.githubusercontent.com/40965862/42423470-7004de96-8303-11e8-8528-d149b7233479.png)
![776 _li](https://user-images.githubusercontent.com/40965862/42423471-70269536-8303-11e8-8470-b00b57064162.jpg)

**Comment by wiiaboo** [comment]
[`--no-keepaspect`](https://mpv.io/manual/master/#options-no-keepaspect)

**Comment by wiiaboo** [comment]
Or [`--video-aspect=16:9`](https://mpv.io/manual/master/#options-video-aspect) if that Russian's supposed to read "always stretch to 16:9".

**Comment by UnknownGod4** [comment]
@wiiaboo but "--no-keepaspect" ingored in fullscreen mode.

my mpv.conf
# High quality video rendering for fast computer. 
profile=gpu-hq 
deband=no 
--video-aspect=16:9 

and the video is still with black stripes

**Comment by wiiaboo** [comment]
Remove the `--`.
If your screen isn't 16:9 use the appropriate one, then. If it's 2560/1680, that's `32:21`.

**Comment by UnknownGod4** [comment]
@wiiaboo write "video-aspect = 16: 9", yes? Everything is the same as before.
My monitor is 2560x1440 resulution. But MPC scale video to 2560x1680 to remove the stripes. How zoom mpv only height?

**Comment by wiiaboo** [comment]
If the black bars are part of the video you'd just have to crop them or use pan-scan. Otherwise, --video-aspect=16:9 should be enough.

**Comment by UnknownGod4** [comment]
@wiiaboo Yes, I think the black bars are part of the video, since it's not a 16: 9 format. But how crop or pan-scan in mpv? To the result was MPC. "Panscan=1" not work. Panscan=1 work only 4:3 to 16:9

**Comment by wiiaboo** [comment]
You have https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua and also pan-scan, look in the manual.
