### ISSUE TITLE
Windows 10bit output & Infinite contrast ICC Profile

### ISSUE THREAD

**Issue by sat4all1** [mpv-player/mpv#5980]
### mpv version and platform
mpv-x86_64-20180701-git-861c102
Windows 10 x64 1803

### Reproduction steps
- 10/12bit output issue:
Nvidia control panel: 12bit for 23...30hz
using autospeedwin with mpv to match the video refresh rate.
- ICC Profile issue:
My LG OLED is set to 2.4 gamma, wide color gamut, 100nit

### Expected behavior
- mpv output 10 or 12bit
- mpv use bt.1886 2.4 gamma when using my oled profile.
I'm using the same profile to create 3dlut for other player and it works perfect.

### Actual behavior
- mpv still report 8bit as display bitdepth
- mpv detect infinite contraste and fall to 1000, which make the picture look washed out like using 1.9 gamma. 
I've tried icc-contrast=100000 and 1000000, but it crashes blacks and look very dim.

### Log file
https://pastebin.com/SACVbdq7

**Comment by zc62** [comment]
10 bit issue, see #5237

**Comment by sat4all1** [comment]
If i understand correctly, 10bit output isn't supported yet?
About the icc profile issue, i think i found the sweet spot for my display "icc-contrast=9969", but there are still problems. when using icc profile i get pinkish tint
mpv icc profile on
![profile](https://user-images.githubusercontent.com/17810555/42838026-9595e4f2-89f7-11e8-80e1-c4483edf8db7.jpg)
mpv icc profile off
![no profile](https://user-images.githubusercontent.com/17810555/42838228-18d89882-89f8-11e8-831b-4c3776c11557.jpg)
madvr 3dlut on "The 3d-lut was created from the same profile i'm using with mpv"
![westworld - s02e02 - reunion web-dl mkv_snapshot_00 50_ 2018 07 17_19 09 19](https://user-images.githubusercontent.com/17810555/42838422-b03c3710-89f8-11e8-948e-542bf52072ac.jpg)

[log.txt](https://github.com/mpv-player/mpv/files/2202907/log.txt)

**Comment by haasn** [comment]
> If i understand correctly, 10bit output isn't supported yet?

It's supported on Linux, but apparently not (yet?) on Windows or OS X (?).

> About the icc profile issue, i think i found the sweet spot for my display "icc-contrast=9969", but there are still problems. when using icc profile i get pinkish tint

Can you upload the profile?

**Comment by sat4all1** [comment]
@haasn 
 
here
[my lg oled.zip](https://github.com/mpv-player/mpv/files/2202943/my.lg.oled.zip)

thanks

**Comment by Akemi** [comment]
> It's supported on Linux, but apparently not (yet?) on ... OS X (?).
there is only an open PR (#5623) for 10bit support on macOS.

**Comment by sat4all1** [comment]
@haasn

 any hint?

**Comment by sat4all1** [comment]
@haasn 

Is it possible to allow infinite contrast because even with icc-contrast set to 1000000 i lose perfect blacks.

**Comment by zc62** [comment]
Made a commit in my fork: https://github.com/zc62/mpv/commit/96c3f8a16cc60b75d6a370d765a2af6560c7ed04. Use `--icc-contrast=inf` to bypass the code that modifies the black point.

Is this what you really want? Could you test how this is compared to madVR + 3dlut (which software did you use to generate that 3dlut from the profile?), and can you really tell the difference between `--icc-contrast=inf` and `--icc-contrast=1000000`?

**Comment by sat4all1** [comment]
Anywhere to download windows build based on your fork?

**Comment by zc62** [comment]
I wrote and compiled the code in Linux. It is a bit tedious to make a fully static build to let others directly use the compiled binary, so I am expecting you to follow the guide (https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md) to compile it on your own. It is actually not that hard to compile mpv in MSYS2. Then you can directly run mpv from the MSYS2 shell.

**Comment by sat4all1** [comment]
Now with icc-contrast=inf i have perfect blacks, and no visual difference compared to madvr + 3d-lut generated using displaycal.
Hope you can push this to master branch.

Thanks much

**Comment by zc62** [comment]
Well, I was actually thinking `inf` should not make too much difference from `1000000`.  Probably that's because I don't own an OLED TV. Will make it a PR.
