### ISSUE TITLE
Multiple instances of mpv with multiple output files = Heart Attack

### ISSUE THREAD

**Issue by morphological** [mpv-player/mpv#5981]
Hi there!

**mpv version & platform**

Ubuntu 18.04 
Kernel: 4.18 rc3
GTX 1050 TI
I5 4660K
mpv 0.27.2 (C) 2000-2017 
ffmpeg library versions:
ffmpeg version: 3.4.2-2

**reproduction steps**
I use the following command to transcode with mpv:
`mpv sintel.mkv -o output --input-ipc-server=mpvencodepipe --vf=vapoursynth:/home/name/60fps.vpy:4:16 --of=matroska --ovc=h264_nvenc --ovcopts=b=19055051,rc=vbr_hq,preset=slow,profile=high,threads=16`

I want to execute this command against 5 separate mp4 files in /clips with a script, and keep getting errors.
`mpv /clips/*.mp4` works, but I fail at renaming the individual outputs, before they are overwritten.

Any ideas how I could get that working?

**Comment by mc4man** [comment]
You really need to take such questions to a proper venue like a linux forum or a stack exchange site or irc as this is an issue tracker.
Depending on what you want achieved can be easily done via a script or at it's simplest thru a for loop command.
``for f in *.mp4; do mpv "$f" -o "${f%.mp4}.mkv"  options; done``

**Comment by wiiaboo** [comment]
This is neither an issue nor a question directly related to mpv.
