### ISSUE TITLE
Is it possible to add MPV-EASY Player to the 【Applications using mpv】 page?

### ISSUE THREAD

**Issue by 422658476** [mpv-player/mpv#5982]
Hello mpv developers, everyone:
I wrote a player front end called MPV-EASY Player, which is based on mpv.
This player front end took me a lot of time and effort.

Now it is a full-featured video player under Windows.

It combines mpv, other people's lua scripts on github, my own lua scripts, js scripts, and lots of c++ code and other code.

Now I think it is stable enough and the function is comprehensive enough. It is time to share it for more users who like mpv for free. I don't know if I can put it into the [Applications using mpv] page.

Some parts of MPV-EASY Player have been open sourced on github. If you are interested, you can refer to some of the code I modified and wrote. If you find it useful, you are welcome to add it to mpv.

The home page of MPV-EASY Player on github is：
https://github.com/422658476/MPV-EASY-Player

MPV-EASY Player greatly improved the osc style, added theme support for your osc, mpv support for lua script in Chinese path, osd style.

MPV-EASY Player has a variety of operating modes,and you can selectively use the mpv native gui you developed and my own gui.

I also very much hope that this player front end will bring more inspiration to you to develop mpv, I hope it can play a little positive role.

In this player front end, all the mpv extensions you developed are fully compatible, because it was originally designed to be compatible with the features of mpv itself, so I have read the documentation you wrote over and over again. As long as I can understand the above content.

MPV-EASY Player's official website： http://www.rjno1.com/mpv-easy-player.html

You may also be very disappointed, because a large part of the MPV-EASY Player is not open source. But there is also a reason for this.

All my code writing skills are self-study (part of the documentation and examples, QT is from the video,MPV-EASY Player is even the first qt program I wrote.), because I am not from computer science, my code writing style is very bad, this even me I know that because I write all the code in almost a single text, you know, the consequences of the code without modules are so serious, and I don't know how to use git. I have seen a joke on the Internet: Why the code is not open source, not because it is not willing, but because it is not dare, because the code is too ugly. You may think this is a joke, but it is really happening to me, but being able to write it is better than not writing it :(

I also know that this kind of behavior may violate the agreement, or has violated the agreement, but I feel that it is better to maintain the current situation.

For me, as long as I have time to maintain this software, then I will always share it for free, just like the smplayer I have been using for more than a decade.

Thank you very much for spending so much time reading these words. My English is very bad. This is google translation. There may be a lot of grammatical errors and incomprehensible statements. I am very sorry.

**Comment by wiiaboo** [comment]
No.
But you can add it [here](https://github.com/mpv-player/mpv/wiki/Applications-using-mpv).

**Comment by EzeKees** [comment]
Your website has advertising

**Comment by 422658476** [comment]
thank you，I have added it manually.

==================================================

If you want to access, please close your adblock because the server needs advertising to maintain.
If you don't want to close, then browse the page on github, basically the same, and also download to the program.
