### ISSUE TITLE
Balance in slave mode

### ISSUE THREAD

**Issue by kriom** [mpv-player/mpv#5985]
### mpv version and platform
**MPlayer 1.3.0 (Debian), built with gcc-7 (C) 2000-2016 MPlayer Team**
**Ubuntu 18.04**

This is not really an issue but I would like to know if there is a way to change the _audio device balance_ rather than change the _balance_ in **slave mode**.

I can change the balance in the way that all the sound from the left or right is send to my 2 stereo speakers but I cannot mute a speaker because I send all the sound to the other one.

### Reproduction steps
```
mkfifo /tmp/abcd
mplayer -slave -input file=/tmp/abcd main.mp3

echo "set_property balance -1" >> /tmp/abcd
echo "set_property balance 1" >> /tmp/abcd
```
With a stereo audio file this mix the channels.
With a mono audio file this have no effect.

### Expected behavior

I would like a property that allow to move sound between right and left speakers.
For example: 
- if the value is 0 right and left speaker are not muted,
- if the value is -1 right speaker is muted,
- if the value is 1 left speaker is muted,
- if the value is 0.5 right speaker is stronger than left speaker.

Best regards,

If I am not in the right place for my request, please let me know.

**Comment by Akemi** [comment]
this is not the mplayer support forum.

**Comment by kriom** [comment]
Of course, thank you and sorry

**Comment by kriom** [comment]
Hi @Akemi,

If I may, I think that control of the balance in slave, _mode or not_, is a must have feature _(obviously, need it)_. At least for stereo audio device and for audio with only one channel.

I mean the capability to do this during audio reading (https://www.youtube.com/watch?v=e8ODm-F9-IM).

As the **VLC** player does not support it  neither (https://trac.videolan.org/vlc/ticket/18546), I'm sure it's easier said than done, so if you don't create a feature request, I won't bother you anymore about it. 

Thank you for your great work.

Best regards,

**Comment by Akemi** [comment]
with mpv:
left speaker muted `--af=lavfi=[pan="stereo|c0=c0"]`
right speaker muted `--af=lavfi=[pan="stereo|c1=c1"]`
left speaker is louder `--af=lavfi=[pan="stereo|c0=0.9*c0|c1=0.1*c1"`
right speaker is louder `--af=lavfi=[pan="stereo|c0=0.1*c0|c1=0.9*c1"`
i hope you get the idea.

[see](https://ffmpeg.org/ffmpeg-filters.html#pan-1) ffmpeg doc for explanation for the pan filter.

**Comment by Akemi** [comment]
i overlooked that you had mono audio. then you have to do something like this for muting the left speaker:
`--lavfi-complex="[aid1] asplit [a1] [a2]; [a1] [a2] amerge [a3]; [a3] pan=stereo|c0=c0 [ao]"`

just change the pan arguments to what i posted in my previous comment.
