### ISSUE TITLE
bink 2 file play error (maybe the bink decoder should be updated)

### ISSUE THREAD

**Issue by cq01** [mpv-player/mpv#5986]
### mpv version and platform
mpv 0.28.0-624-g861c10268d Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Jul  1 02:45:36 UTC 2018
windows 10 1803 x64
from https://sourceforge.net/projects/mpv-player-windows/files/64bit/

### Reproduction steps
1.play the bad_OP.bk2
2.play the good_OP.bk2
### Expected behavior
files should be play normally
### Actual behavior

good_OP.bk2 is normal,
with output
```
Playing: .\good_OP.bk2
 (+) Video --vid=1 (binkvideo 1920x1080 23.976fps)
 (+) Audio --aid=1 (binkaudio_dct 2ch 44100Hz)
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1920x1080 yuv420p
AV: 00:00:00 / 00:01:50 (0%) A-V: -0.487 ct: -0.079
Invalid audio PTS: 0.043537 -> 0.783673
AV: 00:00:01 / 00:01:50 (1%) A-V:  0.120 ct:  0.054


Exiting... (Quit)
```

but when playing bad_OP.bak, mpv exit straightly
the powershell output
```
Playing: .\bad_OP.bk2
[ffmpeg/demuxer] bink: Bink 2 video is not implemented
[ffmpeg/demuxer] bink: Could not find codec parameters for stream 0 (Video: none (KB2j / 0x6A32424B), none, 1920x1080): unknown codec
[ffmpeg/demuxer] Consider increasing the value for the 'analyzeduration' and 'probesize' options
 (+) Video --vid=1 ( 1920x1080 29.970fps)
 (+) Audio --aid=1 (binkaudio_dct 2ch 48000Hz)
Failed to initialize a decoder for codec ''.
Video: no video


Exiting... (Errors when loading file)
```

### Log file
[bad_OP.bk2.txt](https://github.com/mpv-player/mpv/files/2189094/bad.txt)
[good_OP.bk2.txt](https://github.com/mpv-player/mpv/files/2189095/good.txt)

###extra
bad_OP.bk2 is the op of the game steins;gate 0, at the \SteamLibrary\steamapps\common\STEINS;GATE 0\USRDIR\movie\1920x1080\OP.bk2
bink2w32.dll is at the \SteamLibrary\steamapps\common\STEINS;GATE 0\bink2w32.dll
good_OP.bk2 was the bad_OP.bk2 plus Chinese  subtitle(just a little different from the bad_OP.bk2)

### Sample files
[bink2w32.zip](https://github.com/mpv-player/mpv/files/2189291/bink2w32.zip)
the first 10MB of the good_OP.bk2 [good_OP.zip](https://github.com/mpv-player/mpv/files/2189306/good_OP.zip)
the first 10MB of the bad_OP.bk2 [bad_OP.zip](https://github.com/mpv-player/mpv/files/2189293/bad_OP.zip)

**Comment by jeeb** [comment]
Even though the file name says bk2, the first one is not Bink2. Bink2 video's not supported by FFmpeg (yet). That's why it works.

Someone needs to reverse engineer the Bink2 variants :) .

**Comment by richardpl** [comment]
If you can provide different variants of bink 2 videos, I'm interested in writing full decoder.

**Comment by cq01** [comment]
>If you can provide different variants of bink 2 videos, I'm interested in writing full decoder.


The bk2 official decoder.[RADTools.zip](https://github.com/mpv-player/mpv/files/2409455/RADTools.zip)
bk2 vedios(including 1280x720 and 1920x1080 ver)
https://0x0.st/s32P.bk2
https://0x0.st/s32N.bk2

https://0x0.st/s32b.bk2
https://0x0.st/s32c.bk2

https://0x0.st/s32m.bk2
https://0x0.st/s32a.bk2

https://0x0.st/s32B.bk2
https://0x0.st/s32M.bk2

https://0x0.st/s32u.bk2
https://0x0.st/s32S.bk2

https://0x0.st/s32Q.bk2
https://0x0.st/s321.bk2
