### ISSUE TITLE
mpv drops frames at VO for specific AV1 WebM

### ISSUE THREAD

**Issue by CounterPillow** [mpv-player/mpv#6001]
### mpv version and platform

```
mpv 0.28.0-638-g08a6827b3d Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Jul 20 19:07:42 CEST 2018
ffmpeg library versions:
   libavutil       56.18.102
   libavcodec      58.21.105
   libavformat     58.17.101
   libswscale      5.2.100
   libavfilter     7.26.100
   libswresample   3.2.100
ffmpeg version: N-91498-g9888a19db4
```

Arch Linux x86_64

### Reproduction steps

1. Play back `mpv --no-config https://fratti.ch/tmp/wanderers.webm`
2. Watch the VO frame drops
3. Try a different VO, notice how it drops there too

### Expected behavior

Don't drop frames, like vlc, Chromium and ffplay do.

### Actual behavior

Severe VO framedrops

### Log file

https://0x0.st/sVHf.log

### Sample files

* https://fratti.ch/tmp/wanderers.webm
* mp4 remux exhibiting the same issue: https://0x0.st/sVHO.mp4

**Comment by Hrxn** [comment]
With which Chromium versions is this supposed to work?

**Comment by CounterPillow** [comment]
@Hrxn ones which have a devendored ffmpeg that supports AV1, like the one Arch Linux ships.

**Comment by aufkrawall** [comment]
I only get one frame drop in the very beginning (nothing unusual) and video plays fine otherwise for me on Windows and Linux.

**Comment by aufkrawall** [comment]
Odd thing: I'm getting lots of delayed frames with lachs0r's build, but not with shinchiro's.

**Comment by aufkrawall** [comment]
Yep, fine now.

**Comment by Hrxn** [comment]
@lachs0r 

Small nit, don't want to open an issue for this:
```powershell
PS F:\Tools> mpv --V
mpv 0.29.0 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.18.102
   libavcodec      58.22.100
   libavformat     58.17.101
   libswscale      5.2.100
   libavfilter     7.26.100
   libswresample   3.2.100
ffmpeg version: 4.1+809.g269daf5985

PS F:\Tools> mpv
mpv 0.29.0 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
```

> built on UNKNOWN

Not sure, but probably not intentional? Older builds definitely had their date in that place..

**Comment by CounterPillow** [comment]
@Hrxn that's to make the builds reproducible, AFAIU.

**Comment by Hrxn** [comment]
Good to know, thanks.

Then please disregard..or maybe scrap the `built on UNKNOWN` line entirely?

**Comment by CounterPillow** [comment]
@lachs0r I've built aom with optimisations now and that didn't change a thing about mpv's framedrops.

**Comment by qyot27** [comment]
Since this didn't go through last night when I tried to post it:

`--disable-build-date` is what results in 'built on UNKNOWN'. I think it was one of the Debian maintainers that wanted to be able to disable it for determinism reasons or something. Point releases may or may not default to using that option, hence that output. Git builds show the date.

Some years back there was a bug report that wanted it to be more comprehensive and if the `--disable-build-date` option was used, for the 'built on' line to be omitted completely. I didn't particularly care to open a pull request just for that, but I did [whip up a patch to do it](https://github.com/qyot27/mpv/commit/09f4491cf15936b2ba0838825e875853ef1d9ac1).

**Comment by mc4man** [comment]
Seems rather finicky about dropped frames. The linked vid was pretty short so did some local encodes of a bit longer. Seems minor changes to encoding options can create more or less dropped frames in mpv, don't have any other player to compare.
As ex. these 2 vids - the 30 sec one I get no dropped, the 45 sec. I get 11. If I encode diffently the dropped can increase for both.
Both done thru ffmpeg, multithreaded encoding,  about 30% of orig. bitrate/file size, 2 pass. 2nd pass options for 30 sec,  - 

``ffmpeg -hide_banner -nostdin -y -i "file:/home/doug/Videos/Special Edition Trailer-avatar-specialeditiontrailer.mov" -map 0:v:0 -map 0:a:0 -threads 8 -c:v libaom-av1 -cpu-used 4 -strict experimental -tile-columns 3 -tile-rows 3 -b:v 3814k -auto-alt-ref 1 -lag-in-frames 25 -g 128 -pix_fmt yuv420p -c:a libopus -b:a 128k -f webm -pass 2 -passlogfile /tmp/boram-198764pEX5Nbjj2ik -metadata title=Avatar "file:/home/doug/Desktop/Special Edition Trailer-avatar-specialeditiontrailer.webm"
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'file:/home/doug/Videos/Special Edition Trailer-avatar-specialeditiontrailer.mov' `` 

https://0x0.st/sxjk.tar
(- both files in a .tar folder, if uploaded & then downloaded as .webm files then both showed increased frame drops when played, from the downloaded/extracted .tar they behave as the local ones, ..no idea why that

**Comment by Kagami** [comment]
I have the same issue with AV1 1080p of [this video](https://www.youtube.com/watch?v=k2qgadSvNyU) from [AV1 Beta Launch Playlist](https://www.youtube.com/playlist?list=PLyqf6gJt7KuHBmeVzZteZUlNUQAVLwrZS).

```bash
$ mpv --version            
mpv 0.29.0-30-g6eb59fea2f-dirty Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Sep 16 23:58:12 MSK 2018
ffmpeg library versions:
   libavutil       56.19.101
   libavcodec      58.30.100
   libavformat     58.18.101
   libswscale      5.2.100
   libavfilter     7.32.100
   libswresample   3.2.100
ffmpeg version: N-91961-g5109c38162
$ aomdec --help | grep av1
    av1    - AOMedia Project AV1 Decoder 1.0.0-590-g6fa400604
```

```
$ youtube-dl -f 399 -o dua.mp4 k2qgadSvNyU
$ time ffmpeg -v warning -i dua.mp4 -frames:v 250 -f null -
269% cpu 4.216 total
```

As you can see, it takes only 4.2 seconds to decode 10 seconds of video (25 fps) on my machine but when I'm trying to play it with mpv I get a lot of VO frame drops.

**Comment by aufkrawall** [comment]
This issue is still present with latest ffmpeg + mpv builds (both Windows & Linux).
Open
mpv https://www.youtube.com/watch?v=2nXYbGmF3_Q
with
ytdl-format="((bestvideo[vcodec=av01.0.05M.08]/)+bestaudio)/best"
and notice stutter and frames reported as mistimed.

**Comment by richardpl** [comment]
Why this is still open, mpv does not have own decoders any more...

**Comment by Kagami** [comment]
Because ffmpeg decodes video faster than realtime but there are frame drops in mpv?

**Comment by CounterPillow** [comment]
@richardpl maybe you should actually try to reproduce this before making a stupid comment; other applications using the same decoder work fine, and mpv drops frames at vo.

**Comment by aufkrawall** [comment]
Issue disappears when using libdav1d instead of libaom.

**Comment by richardpl** [comment]
Off course.... I told you so.

**Comment by CounterPillow** [comment]
Closing this, since it's probably a combination of the following:

- libaom is slow
- framedrops appear as VO instead of decoder because mpv in recent versions doesn't drop frames at the decoder anymore (my main source of confusion attributing this to mpv)
- Chromium/ffplay probably don't properly implement frame dropping or something

With dav1d I still get stutters but they're less severe, so I guess it is just the decoder after all.

**Comment by aufkrawall** [comment]
Do you get any anomalies reported? If I'm not mistaken, libdav1d is entirely free of stutter for me. Would have to test this more thoroughly though.

**Comment by CounterPillow** [comment]
I still get delayed frames, but that's likely because this is a 2 core 4 thread laptop.

**Comment by sergeevabc** [comment]
mpv 0.32.0-515-g685bd6a5f5
https://x0.at/HKo.mp4 AV1, 720p, 5.5 MiB
gpu-hq, deband=no
getting frame drops… aggrrrhhh

**Comment by aufkrawall** [comment]
Plays fine on Windows here. Open a new ticket and don't ignore the issue template, thanks.

**Comment by sergeevabc** [comment]
For anyone looking for a quick solution, ```vd-queue-enable=yes``` helped in my case.
Further investigation revealed a few [threads][1] with the same, and even [tuned][2], solution.
However that amateur tuning seems to a bit of overkill, official advice would be appreciated.

[1]: https://old.reddit.com/r/AV1/comments/gm0cp5/av1_decoding_on_vlc_3_i56300u_golly/
[2]: https://old.reddit.com/r/AV1/comments/gjq2mv/drastically_improving_av1_playback/

**Comment by wm4** [comment]
Is suspect using a higher value for --vd-lavc-threads=N has the same or better effect.
