### ISSUE TITLE
MPV / libarchive fails to playback/seek videos in archives (rars)

### ISSUE THREAD

**Issue by mac010** [mpv-player/mpv#6002]
### mpv version and platform
mpv.x86_64  0.28.2-4.fc28 (fedora28 version from rpmfusion)

### Reproduction steps
mpv anyfile.rar (also split rars eg rar r01 r02 etc)

### Expected behaviour
play and seek through file (as has worked in all previous versions)

### Actual behaviour
Following error message appears, usually half way through playback:
[libarchive] possibly unsupported seeking - switching to reopening

**Comment by jeeb** [comment]
I can only do something if sample file(s) are provided.

With a quick look it seems like `archive_seek_data` from **libarchive** returns less-than-zero, which it shouldn't unless there's an error/seeking is unsupported. So this is most likely to be E_NOT_OUR_PROBLEM.
