### ISSUE TITLE
0.29.0 won't launch on Windows 10

### ISSUE THREAD

**Issue by Doofussy2** [mpv-player/mpv#6003]
Not much to add, here. Double clicking on the mpv.exe, nothing happens. Every other build I've got, works as expected. I've tried re-downloading, but no change.

**Comment by lachs0r** [comment]
Yeah, something’s not right with those builds. Can you try and see if it works with `--gpu-context=win`?

**Comment by Doofussy2** [comment]
Putting gpu-context=win, in the mpv.conf, it still won't launch.

**Comment by lachs0r** [comment]
Should be fixed now.

For the record: This was a combination of GCC bugs and broken stack smashing protection. The executables worked with Wine, but did not even run on native Windows, hence I didn’t notice. It also only affected 64-bit. I’ll try to make sure this doesn’t happen again.

**Comment by Doofussy2** [comment]
Yup, it works now. Thanks
