### ISSUE TITLE
mpv should not show non-forced subtitles when --sub-forced-only is set

### ISSUE THREAD

**Issue by Identifier** [mpv-player/mpv#6006]
### mpv version and platform

0.28.0 on Windows 10

### Reproduction steps

Use the --sub-forced-only flag to play an .MKV file with a default subtitle track (or the first track matching --slang) but without any Forced flags set on the subtitle tracks nor any Forced subtitles within the tracks themselves.

### Expected behavior

No subtitles should be displayed, since none of the tracks nor the individual subtitles are Forced.

### Actual behavior

All of the subtitles in the subtitle track are displayed.

### Log file

[cplayer] Command line options: '-v' '--sub-forced-only' 'Seinfeld Season 01 Episode 01 - The Seinfeld Chronicles.mkv'
[cplayer] mpv 0.28.0 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Mon Dec 25 01:09:58 CET 2017
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.7.100
[cplayer]    libavcodec      58.8.100
[cplayer]    libavformat     58.3.100
[cplayer]    libswscale      5.0.101
[cplayer]    libavfilter     7.7.100
[cplayer]    libswresample   3.0.101
[cplayer] ffmpeg version: N-89595-g40d4b13228
[cplayer]
[cplayer] Configuration: /home/lachs0r/mingw-w64-cmake/buildroot/build64/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-encoding --enable-egl-angle-lib --enable-lua --enable-javascript --enable-libarchive --enable-libass --enable-libbluray --enable-dvdread --enable-dvdnav --enable-uchardet --enable-vulkan --enable-shaderc --enable-rubberband --enable-lcms2 --prefix=/home/lachs0r/mingw-w64-cmake/buildroot/build64/prefix/mingw
[cplayer] List of enabled features: asm atomics build-date cplayer crossc cuda-hwaccel d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths drmprime dvdnav dvdread dvdread-common egl-angle egl-angle-lib egl-angle-win32 egl-helpers encoding ffmpeg gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gnuc gpl iconv javascript jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libm libmpv-shared lua luajit mingw noexecstack optimize plain-gl posix-or-mingw rubberband shaderc shaderc-static static-build stdatomic uchardet vulkan wasapi win32-desktop win32-internal-pthreads win32-pipes zlib
[cplayer] Reading config file C:\Users\live\AppData\Roaming/mpv/mpv.conf
[ifo] Opening C:\Users\live\AppData\Roaming/mpv/input.conf
[ifo_dvdnav] Opening C:\Users\live\AppData\Roaming/mpv/input.conf
[bdmv/bluray] Opening C:\Users\live\AppData\Roaming/mpv/input.conf
[file] Opening C:\Users\live\AppData\Roaming/mpv/input.conf
[input] Parsing input config file C:\Users\live\AppData\Roaming/mpv/input.conf
[input] Input config file C:\Users\live\AppData\Roaming/mpv/input.conf parsed: 0 binds
[osc] lua-settings/osc.conf not found.
[ytdl_hook] lua-settings/ytdl_hook.conf not found.
[osd/libass] Shaper: FriBidi 0.19.8 (SIMPLE) HarfBuzz-ng 1.7.4 (COMPLEX)
[osd/libass] Setting up fonts...
[stats] lua-settings/stats.conf not found.
[osd/libass] Using font provider directwrite
[osd/libass] Done.
[cplayer] Playing: Seinfeld Season 01 Episode 01 - The Seinfeld Chronicles.mkv
[cplayer] Running hook: ytdl_hook/on_load
[ifo] Opening Seinfeld Season 01 Episode 01 - The Seinfeld Chronicles.mkv
[ifo_dvdnav] Opening Seinfeld Season 01 Episode 01 - The Seinfeld Chronicles.mkv
[bdmv/bluray] Opening Seinfeld Season 01 Episode 01 - The Seinfeld Chronicles.mkv
[file] Opening Seinfeld Season 01 Episode 01 - The Seinfeld Chronicles.mkv
[demux] Trying demuxers for level=normal.
[mkv] Found the head...
[mkv] + a segment...
[mkv] Parsing seek head...
[mkv] |+ segment information...
[mkv] | + muxing app: libebml v0.7.7 + libmatroska v0.8.1
[mkv] | + writing app: mkvmerge v2.0.2 ('You're My Flame') built on Feb 21 2007 23:40:55
[mkv] | + timecode scale: 1000000
[mkv] | + duration: 1329.600s
[mkv] | + segment uid a4 3a 72 1c d5 5b fc 78 80 6c 2c 90 77 06 d5 78
[mkv] |+ segment tracks...
[mkv] | + a track...
[mkv] |  + Track number: 1
[mkv] |  + Track type: Video
[mkv] |  + Video track
[mkv] |   + Display width: 4
[mkv] |   + Display height: 3
[mkv] |   + Pixel width: 704
[mkv] |   + Pixel height: 528
[mkv] |  + Codec ID: V_MPEG4/ISO/AVC
[mkv] |  + CodecPrivate, length 131
[mkv] |  + Language: eng
[mkv] |  + Default flag: 1
[mkv] |  + Forced flag: 0
[mkv] |  + Default duration: 40.000ms ( = 25.000 fps)
[mkv] | + a track...
[mkv] |  + Track number: 2
[mkv] |  + Track type: Audio
[mkv] |  + Audio track
[mkv] |   + Sampling frequency: 48000.000000
[mkv] |   + Channels: 2
[mkv] |  + Codec ID: A_AAC
[mkv] |  + CodecPrivate, length 5
[mkv] |  + Language: eng
[mkv] |  + Default flag: 1
[mkv] |  + Forced flag: 0
[mkv] |  + Default duration: 21.333ms ( = 46.875 fps)
[mkv] | + a track...
[mkv] |  + Track number: 3
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_TEXT/UTF8
[mkv] |  + Language: nor
[mkv] |  + Default flag: 1
[mkv] |  + Forced flag: 0
[mkv] | + a track...
[mkv] |  + Track number: 4
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_TEXT/UTF8
[mkv] |  + Language: swe
[mkv] |  + Default flag: 0
[mkv] |  + Forced flag: 0
[mkv] | + a track...
[mkv] |  + Track number: 5
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_TEXT/UTF8
[mkv] |  + Language: dan
[mkv] |  + Default flag: 0
[mkv] |  + Forced flag: 0
[mkv] | + a track...
[mkv] |  + Track number: 6
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_TEXT/UTF8
[mkv] |  + Language: eng
[mkv] |  + Default flag: 0
[mkv] |  + Forced flag: 0
[mkv] Parsing chapters...
[mkv] New edition 0
[mkv] Default edition flag: 0
[mkv] Chapter 0 from 00:00:00.000 to 00:00:00.000, Chapter 1
[mkv] Chapter 1 from 00:00:57.000 to 00:00:00.000, Chapter 2
[mkv] Chapter 2 from 00:11:34.000 to 00:00:00.000, Chapter 3
[mkv] Chapter 3 from 00:21:42.400000000 to 00:00:00.000, Chapter 4
[mkv] Chapter 4 from 00:22:08.000 to 00:00:00.000, Chapter 5
[mkv] |+ found cluster
[mkv] Seeking to 243898219 to read header element 0x1c53bb6b.
[mkv] Parsing cues...
[mkv] Seeking to 243901956 to read header element 0x114d9b74.
[mkv] Parsing seek head...
[mkv] All headers are parsed!
[demux] Detected file format: Matroska
[cplayer] Opening done: Seinfeld Season 01 Episode 01 - The Seinfeld Chronicles.mkv
[find_files] Loading external files in .
[cplayer] Running hook: ytdl_hook/on_preloaded
[mkv] select track 0
[mkv] select track 1
[mkv] select track 2
[cplayer]  (+) Video --vid=1 (*) (h264 704x528 25.000fps)
[cplayer]  (+) Audio --aid=1 --alang=eng (*) 'AAC 128 Kbps' (aac 2ch 48000Hz)
[cplayer]  (+) Subs  --sid=1 --slang=nor (*) 'Norsk' (subrip)
[cplayer]      Subs  --sid=2 --slang=swe 'Svensk' (subrip)
[cplayer]      Subs  --sid=3 --slang=dan 'Dansk' (subrip)
[cplayer]      Subs  --sid=4 --slang=eng 'Engelsk' (subrip)

### Notes

Note 1: The same problem can be seen even if there is not a default subtitle track (i.e. all of the subtitle tracks are set to Default: 0), if you set the --slang setting then the matching track will be treated as a Default track and this same behavior will occur.  So for example if someone sets slang=en,eng in their mpv.conf file then English subtitles will *always* be shown whenever there is a matching en/eng subtitle track even if --sub-forced-only is set.  This could lead one to set --no-sub-visibility by default which would cause them to potentially miss out on forced subtitles that are actually necessary during foreign-spoken scenes.  (See related issue #4271).

Note 2: --sub-forced-only actually works correctly if there *are* individual subtitles within the track that are marked individually as Forced.  In that case, only the individual subtitles within the track that are forced will be shown.  But if none of the subtitles are forced then *all* of the subtitles are displayed, which is the core of this issue.

Ideal behavior: A person should be able to set slang=<their natural language> and sub-forced-only=yes in their mpv.conf file to cause subtitles to be shown if and only if they are Forced.  In fact, I'd suggest that this should be the default behavior of mpv.  Thanks for your consideration to this issue.

**Comment by dnmTX** [comment]
@Identifier did you try `--sid=no`? It disables the subtitle decoding but they are still available if you need them.All of them are.I'm not sure that in this case you can select by language or whatever but it's an option nevertheless.

**Comment by Identifier** [comment]
@dnmTX that would get rid of the subtitles altogether, including the forced ones that are supposed to appear during foreign-language dialog.  See also issue #4271

**Comment by dnmTX** [comment]
@Identifier i know,but basically you can turned them on manually.What i suggested was more like a workaround then solution.I know that the issue exist and needs to be fixed and as you see from #4271 it's been a year already and no progress yet,unfortunately.Hopefully this time somebody would start working on it.

**Comment by wm4** [comment]
Sample file?

**Comment by diegocr** [comment]
@wm4 No need for a sample file, it does happens with every single one as long `slang` is also provided.

**Comment by wm4** [comment]
Oh I get it. The option only works for certain image subtitles, by design (probably).
