### ISSUE TITLE
mpv --vid=no throws an error since upgrade to 0.29

### ISSUE THREAD

**Issue by gbstan** [mpv-player/mpv#6008]
### mpv version and platform
mpv 0.29
OS X 10.13.6

### Reproduction steps
mpv --vid=no 'https://www.youtube.com/watch?v=lFcSrYw-ARY&frags=pl%2Cwn'

### Expected behavior
mpv should play the audio only

### Actual behavior
mpv --vid=no 'https://www.youtube.com/watch?v=lFcSrYw-ARY&frags=pl%2Cwn'

[redacted]:~> Playing: https://www.youtube.com/watch?v=lFcSrYw-ARY%2Cwn
**Pad vid1 is not connected to anything.**
[ffmpeg] https: Will reconnect at 131072 in 0 second(s), error=End of file.

Exiting... (Errors when loading file)

**Comment by Akemi** [comment]
i get similar errors, though it works. i also quoted the URL because of the %. otherwise it started as a background process.

**Comment by gbstan** [comment]
I have added the quotes around the youtube address and updated the output.

**Comment by CounterPillow** [comment]
Looks like you have some filters in your config file, and with 0.29 the way filters work internally was rewritten.

**Comment by gbstan** [comment]
No filter that I know of.
The only thing I have in mpv.conf is as follows:
# Video
hwdec=auto

# youtube-dl settings
ytdl-format=bestvideo[height<=?1080][fps<=?30]+bestaudio/best

Where would other filters be, just to make sure there is no other filter that I am unaware of anywhere?

**Comment by CounterPillow** [comment]
a log file of this generated with `--log-file=yourfilehere.txt` would be a good start

**Comment by gbstan** [comment]
I found the problem: one of the mpv userscripts called "visualizer.lua" is causing the problem. I removed the script and now it works.
The offending script is here: https://github.com/mfcc64/mpv-scripts/blob/master/visualizer.lua

**Comment by lachs0r** [comment]
Report an issue there, then. This change is documented in `DOCS/interface-changes.rst` (unconnected filter pads are no longer allowed).
