### ISSUE TITLE
mpv 0.29: AVHWFramesContext: Failed to write image to surface (the requested function is not implemented)

### ISSUE THREAD

**Issue by alium** [mpv-player/mpv#6014]
### mpv version and platform
mpv-0.29.0 (newly compiled version 0.28.2 works without problems)
ffmpeg-4.0.2
libva 2.2.0
Archlinux, Haswell CPU

### Reproduction steps
install mpv-0.29 and play some mp4/mkv  video 

Error:
[autoconvert] HW-uploading to vaapi
[hwupload] upload yuv420p -> yuv420p (p010)
[ffmpeg] AVHWFramesContext: Failed to write image to surface 0x4000000: 20 (the requested function is not implemented).
[ffmpeg] AVHWFramesContext: Failed to write image to surface 0x4000001: 20 (the requested function is not implemented).
mpv: ../intel-vaapi-driver/src/gen75_vpp_vebox.c:1023: hsw_veb_surface_state: Assertion `obj_surf->fourcc == VA_FOURCC_NV12 || obj_surf->fourcc == VA_FOURCC_YUY2 || obj_surf->fourcc == VA_FOURCC_AYUV || obj_surf->fourcc == VA_FOURCC_RGBA' failed.
Neúspěšně ukončen (SIGABRT)

### Log file
https://file.io/7mqzow

**Comment by mvf** [comment]
Try `mpv --vd-lavc-dr=no`. The default for that setting was changed in 0.29, breaking video playback on some Intel GPUs.

**Comment by alium** [comment]
@mvf: 
no effect,
[alois@notebook Videa]$ mpv --vd-lavc-dr=no Taylor\ Swift\ -\ Shake\ It\ Off\ in\ the\ Live\ Lounge.mp4 
Playing: Taylor Swift - Shake It Off in the Live Lounge.mp4
 (+) Video --vid=1 (*) (h264 1920x1080 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[autoconvert] HW-uploading to vaapi
[hwupload] upload yuv420p -> yuv420p (p010)
[ffmpeg] AVHWFramesContext: Failed to write image to surface 0x4000000: 20 (the requested function is not implemented).
[ffmpeg] AVHWFramesContext: Failed to write image to surface 0x4000001: 20 (the requested function is not implemented).
mpv: ../intel-vaapi-driver/src/gen75_vpp_vebox.c:1023: hsw_veb_surface_state: Assertion `obj_surf->fourcc == VA_FOURCC_NV12 || obj_surf->fourcc == VA_FOURCC_YUY2 || obj_surf->fourcc == VA_FOURCC_AYUV || obj_surf->fourcc == VA_FOURCC_RGBA' failed.
Neúspěšně ukončen (SIGABRT)

**Comment by CounterPillow** [comment]
Where's the full log file? Your link is a 404.

**Comment by mvf** [comment]
@alium: Ah well, it was worth a shot. The quickest way to find this is probably for you to bisect.

**Comment by alium** [comment]
@CounterPillow before 18 days was link to log functional ;-)

**Comment by alium** [comment]
@mvf : i try the bisect

**Comment by alium** [comment]
log: https://file.io/qZ0azU

**Comment by alium** [comment]
log: https://pastebin.com/raw/ik62W3AP

**Comment by CounterPillow** [comment]
You can probably make it work by removing `vf=vavpp` from your config file. A git bisect could be useful in determining whether this was accidental breakage.

**Comment by haasn** [comment]
This caught my attention:

> [hwupload] upload yuv420p -> yuv420p (p010)

and

> mpv: ../intel-vaapi-driver/src/gen75_vpp_vebox.c:1023: hsw_veb_surface_state: Assertion `obj_surf->fourcc == VA_FOURCC_NV12 || obj_surf->fourcc == VA_FOURCC_YUY2 || obj_surf->fourcc == VA_FOURCC_AYUV || obj_surf->fourcc == VA_FOURCC_RGBA' failed.

The assertion, which seems to come from the intel driver, is trying to assert that the fourcc is one of nv12, yuy2, ayuv or rgba. However, it seems like mpv is maybe trying to use p010 (a 10-bit format), which is not on that list. I'm not entirely sure without reading the source how to read that log line, but p010 definitely seems out-of-place, given that yuv420p should fit just fine into nv12, there should be no need for mpv to be even attempting p010 - unless it wants extra headroom for vavpp or something? (but even then, the 2 extra bits from p010 is not exactly a lot, a 16-bit format would be better)

**Comment by wm4** [comment]
mpv uses the FFmpeg API to try to determine the list of possible formats, which in turn uses vaapi... somehow.
The combination which mpv tries makes no sense, but it probably wasn't its own idea, and the driver certainly shouldn't crash.
Reopen if this happens with latest ffmpeg, mpv, libva, and Intel drivers.
