### ISSUE TITLE
Is there a way to control volume for right/left channel separately?

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#6018]

**Comment by Akemi** [comment]
`--af=lavfi=[pan="stereo|c0=1.0*c0|c1=0.1*c1"]`

https://ffmpeg.org/ffmpeg-filters.html#pan-1

**Comment by Maigre** [comment]
Hi sorry to bump this,
but i'd like to adjust pan using IPC
I guess it should be something similar to this:

`{ "command": ["set_property", "af", 'lavfi=[pan="stereo|c0=1.0*c0|c1=0.1*c1"]' ] }`

But the last part seems wrong.. 
Thanks !

**Comment by Maigre** [comment]
as @garoto mentioned, this was a quotation issue.

sending `{"command": ["set_property", "af", "lavfi=[pan=stereo|c0=1.0*c0|c1=0.1*c1]"]}`

works well on debian / raspbian.

Thanks
