### ISSUE TITLE
GUI doesn't show up with some mp3 files that have a cover image

### ISSUE THREAD

**Issue by EvgenyOrekhov** [mpv-player/mpv#6025]
### mpv version and platform

mpv version: 0.29.0

`mpv --version`:

```text
mpv git-2018-07-22-45beb70 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Thu Jul 26 15:04:40 UTC 2018
ffmpeg library versions:
   libavutil       56.18.102
   libavcodec      58.21.106
   libavformat     58.17.101
   libswscale      5.2.100
   libavfilter     7.26.100
   libswresample   3.2.100
ffmpeg version: git-2018-07-26-a8ce6fb
```

OS: Lubuntu 18.04.1 (64-bit)

### Reproduction steps

1. Download SoundCloud mp3 from here: https://www.startalkradio.net/show/the-state-of-space-exploration-now-with-bill-nye/
2. `mpv STR-S09E26-the-state-of-space-exploration-now-with-bill-nye.mp3`

### Expected behavior

mpv's GUI should show up, the playback should start, and there should be no errors in the console.

### Actual behavior

The sound is playing, but the GUI doesn't show up, and there are the following errors in the console:

```text
[hwupload] non-mod 2 input frames unsupported
[hwupload] failed to upload frame
Disabling filter vdpaupp.00 because it has failed.
```

### Log file

https://0x0.st/sVDw.txt

### mpv.conf

```ini
vo=gpu
hwdec=auto
profile=gpu-hq
vf-add=vdpaupp:sharpen=0.2
vd-lavc-dr=yes
scale=ewa_lanczossharp
video-sync=display-resample
volume=100
alang=English,eng,en
slang=English,eng,en
sub-auto=fuzzy
fullscreen=yes
```

### Sample files

- https://www.startalkradio.net/show/the-state-of-space-exploration-now-with-bill-nye/
- https://www.startalkradio.net/show/the-geekiverse-with-kevin-smith/

**Comment by EvgenyOrekhov** [comment]
Additional info: if I press any arrow key on my keyboard to seek the track, the GUI shows up! This works only if mpv was launched from the command line.

**Comment by Hrxn** [comment]
Does it work with `mpv --no-config ..... `?

**Comment by EvgenyOrekhov** [comment]
@Hrxn Yes.

**Comment by EvgenyOrekhov** [comment]
@CounterPillow Removing `vf-add=vdpaupp:sharpen=0.2` from the config solves the issue.

**Comment by mc4man** [comment]
You should keep in mind that with that mpv build & while using nvidia drivers hwdec=auto will use nvdec/cuda so that -vf option is generally useless.  (- unless you specify to use hwdec=vdpau..

**Comment by EvgenyOrekhov** [comment]
@mc4man I compiled my config using the "trial and error" approach. It makes mpv use GPU acceleration and a sharpen filter, but I guess it's not optimal. What options would you recommend me to change considering that I have an AMD video card, use Ubuntu's default AMD driver, want to use GPU acceleration and a sharpen filter, and I want to get the best image quality?

**Comment by mc4man** [comment]
Then ignore me, I somehow assumed you were on nvidia, my mistake, sorry..

**Comment by EvgenyOrekhov** [comment]
@mc4man Still, you are onto something, since I get `Cannot load libcuda.so.1` in the console every time I play something, which is strange considering that I use AMD video card. But it's off-topic.

**Comment by mc4man** [comment]
Nah, it just a bit of useless info mpv has a habit of providing, in this 
case if you enable hwdec unspecified.

**Comment by wm4** [comment]
> vf-add=vdpaupp:sharpen=0.2

Just remove that.

**Comment by EvgenyOrekhov** [comment]
@wm4 I want that when I watch video.

**Comment by wm4** [comment]
vo_gpu has its own sharpen option. You're only hurting yourself by forcing vdpau involvement.

**Comment by EvgenyOrekhov** [comment]
So the answer is: use `sharpen=2` (or whatever value you prefer) instead of `vf-add=vdpaupp:sharpen=0.2`. Thanks, @wm4!

**Comment by blueray453** [comment]
I am using 

```
$ mpv --version
mpv 0.35.1 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 30 03:02:11 2023
FFmpeg library versions:
   libavutil       57.28.100
   libavcodec      59.37.100
   libavformat     59.27.100
   libswscale      6.7.100
   libavfilter     8.44.100
   libswresample   4.7.100
FFmpeg version: 5.1.2
```
I had the same issue for mp3 files.

I added [visualizer.lua](https://github.com/mfcc64/mpv-scripts/blob/master/visualizer.lua)

No the issue is gone.

**Comment by blueray453** [comment]
One issue remains though. When I use https://github.com/cyl0/ModernX , [The volume control is greyed out](https://github.com/cyl0/ModernX/issues/53).

**Comment by Keith94** [comment]
> One issue remains though. When I use https://github.com/cyl0/ModernX , [The volume control is greyed out](https://github.com/cyl0/ModernX/issues/53).

Can you open an issue in case the devs don't see this??

**Comment by blueray453** [comment]
@Keith94 

> Can you open an issue in case the devs don't see this??

There are

https://github.com/mfcc64/mpv-scripts/blob/master/visualizer.lua
https://github.com/cyl0/ModernX
https://github.com/mpv-player/mpv

I am not sure where to open this issue? However, I have opened an issue cyl0/ModernX and the link is in my previous comment. If you create an issue in mfcc64/mpv-scripts or mpv-player/mpv then please let us know.
