### ISSUE TITLE
mpv playlist generation and dynamics 

### ISSUE THREAD

**Issue by shirishag75** [mpv-player/mpv#6026]
```
$ mpv -version
mpv 0.28.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0.2-1
```

This is somewhat related to https://github.com/mpv-player/mpv/issues/6016 but more of a general related inquiry. I use mpv as a random playlist of songs. I usually use it something like 

`~/Video-songs/hindi-songs$ mpv . `

and it does a fantastic job of being a random playlist. 

I just wonder if mpv makes an internal playlist each time it does that ? 

Would that be the best way to have the playlist as it gets generated on the spot as videos/songs are added or deleted or is there a better way of doing it ?

**Comment by paulguy** [comment]
My understanding is shuffle just moves the entries around but keeps a note of where they were so they can be unshuffled, and additional entries are simply appended if you use the loadfile ... append command and will just remain in its spot if shuffle is set to no.  Not sure if there's a direct way to insert an entry randomly.

**Comment by qmega** [comment]
It doesn't actually keep a note of the original order. If you turn shuffle off (bind a key to `cycle shuffle` to try this), the playlist will stay in the last shuffled order.

There are two ways to shuffle from the user's point of view:
* The `--shuffle` option. If this is on, the playlist is shuffled in-place when first starting and whenever the playlist loops. This results in the interesting property that turning shuffle on while playing will not actually shuffle until you get to the end of the playlist and it loops. Turning it off while playing will not un-shuffle either, but will stop it from re-shuffling when it loops.
* The `playlist-shuffle` command. You can run this at any time and it will shuffle the playlist in-place once. If the playlist loops after that, it will use the same order (shuffled, but not shuffled again) -- unless the `shuffle` option is set by that time.

Essentially, having `shuffle` on just calls `playlist-shuffle` every time the playlist starts. Other than that, the playlist doesn't know whether it's "shuffled" or not and doesn't act any differently. If you add a new entry to the playlist, it will be added to the end.

If you wanted to actually add a new entry at a random position, I think you'd have to use a Lua (or JS) script (you could use the `playlist-move` command after adding). But if you're already using shuffle, you presumably don't care about preserving any particular shuffled order, so you could probably "cheat" by doing `loadfile ... append ; playlist-shuffle`, which would have the effect of the new entry having a random position, with the side-effect of all the other entries also being re-shuffled.
