### ISSUE TITLE
Petition to add Qsync to mpv decoding

### ISSUE THREAD

**Issue by baraa272** [mpv-player/mpv#6031]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

i actually have both MadVr and mpv configured by myself and i was testing smooth motion ????
i have intel hd graphics 4400 + amd r5 230m
**only using intel**
### Reproduction steps

mpv with interpolation (display-resample) with --no-config for normal 1080p 30fps h264 youtube video
tscale=oversample
### Expected behavior

delicious crispy smooth motion as **MadVr** on **MPC-HC** with **Qsync**

### Actual behavior

dxva2: 100% killing my gpu?????
dxva2-copy= 44% gpu and 15% cpu but still see shadows of movement and not that smooth
d3d11va=40% gpu and 12% cpu  same as dxva2-copy 
d3d11va-copy = same as d3d11va

### Log file

Make a log file made with -v or --log-file=output.txt
[output.txt](https://github.com/mpv-player/mpv/files/2238210/output.txt)
, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by zc62** [comment]
Assuming you are using a regular 60Hz monitor, then `tscale=oversample` won't affect how a 30fps video looks like, since doubling the frame rate easily does the job. I don't know if madvr's smooth motion will interpolate a 30fps video or not, but I think you still can play with the `tscale` parameter.

**Comment by baraa272** [comment]
sometimes yes 
sometimes no
but its better to use intel graphics directly through QS
d3d11 actually pretty heavy on both cpu/gpu
dxva2 suffers from bad quality

**Comment by tomty89** [comment]
Does "directly through QS" even make any sense though? As far as I know you always have access to it via an interface that the driver supports (and on Windows it's DXVA). I think that's how MPC-HC (or whatever component it makes use of) does it as well.

A more "direct" way might be using a "non-free" ffmpeg build that were built with support for it:
https://www.intel.com/content/www/us/en/architecture-and-technology/quick-sync-video/quick-sync-video-installation.html
I don't think you need any modification in mpv for that. Perhaps you need to rebuild though.

**Comment by baraa272** [comment]
windows here
so??????

**Comment by aufkrawall** [comment]
QuickSync makes only sense for encoding, not decoding. It might be possible to select any GPU in the system for decoding with D3D11VA one day (LAV Filters already support this btw.).

**Comment by tomty89** [comment]
> QuickSync makes only sense for encoding

I don't think that is true though. The pdf on the page I linked (or even its wikipedia page) tells you otherwise.

**Comment by aufkrawall** [comment]
I wrote "doesn't make sense", not "is not possible". It's slower than d3d11va zero copy and thus useless.

**Comment by tomty89** [comment]
Does d3d11va not use the Quick Sync "SIP core" though? (If not, what does it use behind the scene on Intel?)

**Comment by CounterPillow** [comment]
There's currently no indication that quicksync isn't just a marketing term surrounding a proprietary API that accesses the same hardware as the standard interfaces for this do. If you disagree, you can still compile your ffmpeg with QS support and specify the decoder manually.
