### ISSUE TITLE
no deband or color control on d3d9

### ISSUE THREAD

**Issue by baraa272** [mpv-player/mpv#6032]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases
MadVr with d3d9 working all features 
mpv d3d9 only interpolation working ?????????????????
### Reproduction steps

these settings : 
deband=yes
hwdec=d3d11va
interpolation=yes
video-sync=display-resample
gpu-context=angle
d3d11-flip=yes
d3d11va-zero-copy=yes
angle-d3d11-warp=yes
angle-renderer=d3d9 **FORCING ON D3D9 because d3d11 heavy**
tscale=bicubic

i'm using angle to force use d3d9
i tried change some color settings like 
saturation=10 BUT NOTHING HAPPENS to color of video 
### Expected behavior

all features working like how actually **madVr working flawlessly with d3d9**

### Actual behavior

deband and other settings not working 
only thing working is interpolation 

### Log file
[output2.txt](https://github.com/mpv-player/mpv/files/2238321/output2.txt)

**Comment by CounterPillow** [comment]
>MadVr with d3d9 working all features

how is this relevant lmao

**Comment by Akemi** [comment]
i think it's the best for us all that you stick with madVR.

**Comment by Hrxn** [comment]
> angle-renderer=d3d9 FORCING ON D3D9 because d3d11 heavy

What?

**Comment by zc62** [comment]
Unless you are using Windows XP, otherwise I can't find a good reason to prefer d3d9. You can try vulkan as well, if you graphic card supports it.

If you are talking about performance issues, maybe you can check your power management settings, especially when using NV/AMD cards on laptops (if you set mpv to use them).

**Comment by avih** [comment]
> Unless you are using Windows XP, otherwise I can't find a good reason to prefer d3d9

There is a good reason on a low end system or if power consumption is a factor.

While d3d9 won't use shaders and other useful features (nice scalers etc), it's measurably more conservative on power.

If you're with a laptop away from a power socket, then double digits percentage diff in overall CPU power consumption (assuming iGPU) is not negligible, and depending on your priorities, might be well worth the potential visual degradation.

**Comment by zc62** [comment]
> There is a good reason on a low end system or if power consumption is a factor.

Indeed. [Manual says](https://mpv.io/manual/master/#options-angle-renderer)
> Normally there is no reason to force a specific renderer, though `--angle-renderer=d3d9` may give slightly better performance on old hardware.

I guess d3d11 with `--gpu-dumb-mode` may produce similar consumption? Anyway, if the computational effort is really an issue, then one would not activate deband from the very beginning.

**Comment by avih** [comment]
> Anyway, if the computational effort is really an issue, then one would not activate deband from the very beginning.

Indeed, but that's besides the point about a valid good reason to use d3d9.

**Comment by baraa272** [comment]
Actually d3d11 heavy on my whole system 
Cpu i3-4005u 
Intel 4400
Is there any way to produce good quality with d3d9 like what madvr do???

**Comment by baraa272** [comment]
Also zc62 
I have depand put on highest on madvr without any problem on d3d9 
I can even use lanczos on madvr up to 1080 30fps video

**Comment by zc62** [comment]
Not sure. Is madVR also restricted to use iGPU only? (Why don't you use your AMD card?)
