### ISSUE TITLE
Precompiled self-contained binary for Linux

### ISSUE THREAD

**Issue by eloyesp** [mpv-player/mpv#6038]
There are multiple ["packages"](https://mpv.io/installation/) for different distros, but it would be awesome to have a single precompiled file to download and run on linux, could it be possible to make a self-contained binary, to use on certain environments where one does not want to make a full install?

**Comment by Akemi** [comment]
we don't provide any official builds or binaries. if anyone is up to the task of doing something like this though, we can also link it on our homepage.
