### ISSUE TITLE
Fails to compile on macOS without OpenAL extension

### ISSUE THREAD

**Issue by Enzime** [mpv-player/mpv#6039]
### mpv version and platform

mpv 0.29.0 on macOS High Sierra 10.13.6 

### Reproduction steps

Attempt to build mpv with `--enable-openal`.

### Expected behavior

In an environment without the `AL_SOFT_source_latency` OpenAL extension, `audio/out/ao_openal.c` should still compile correctly.

### Actual behavior

`audio/out/ao_openal.c` fails to compile due to `use of undeclared identifier` found in the code block at lines [404 and 410](https://github.com/mpv-player/mpv/blob/5532a3da1ee058443d3162582b601f19b59377c2/audio/out/ao_openal.c#L404-L410).

```
../audio/out/ao_openal.c:406:28: error: expected ';' after expression
        LPALGETSOURCEDVSOFT alGetSourcedvSOFT = alGetProcAddress("alGetSourcedvSOFT");
                           ^
                           ;
../audio/out/ao_openal.c:406:9: error: use of undeclared identifier 'LPALGETSOURCEDVSOFT'
        LPALGETSOURCEDVSOFT alGetSourcedvSOFT = alGetProcAddress("alGetSourcedvSOFT");
        ^
../audio/out/ao_openal.c:406:29: error: use of undeclared identifier 'alGetSourcedvSOFT'
        LPALGETSOURCEDVSOFT alGetSourcedvSOFT = alGetProcAddress("alGetSourcedvSOFT");
                            ^
../audio/out/ao_openal.c:407:9: error: implicit declaration of function 'alGetSourcedvSOFT' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        alGetSourcedvSOFT(source, AL_SEC_OFFSET_LATENCY_SOFT, offsets);
        ^
../audio/out/ao_openal.c:407:9: warning: this function declaration is not a prototype [-Wstrict-prototypes]
../audio/out/ao_openal.c:407:35: error: use of undeclared identifier 'AL_SEC_OFFSET_LATENCY_SOFT'
        alGetSourcedvSOFT(source, AL_SEC_OFFSET_LATENCY_SOFT, offsets);
```

### Potential solution

Use preprocessor directives to prevent the code block from being included in compilation.

**Comment by lachs0r** [comment]
See also: #4645

Using other OpenAL implementations than openal-soft, especially Apple’s, is discouraged.

**Comment by fefe17** [comment]
I'm compiling mpv on Linux with openal-soft and I get the same error.
Do you need to do something special to compile openal-soft?

**Comment by Enzime** [comment]
Due to the merge of #6074, `mpv` now compiles on macOS when `--enable-openal` is specified and `OpenAL-Soft` is available 🎉
