### ISSUE TITLE
mpv 0.29.0 crashes on OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by sumyungguy** [mpv-player/mpv#6041]
### mpv version and platform
mpv 0.29.0 from @stolendata https://laboratory.stolendata.net/~djinn/mpv_osx/
(either July 23 or July 26 builds)
OS X 10.10.5 (with all current updates)

### Reproduction steps
Start mpv, with no options in mpv.conf except log-file, by double-clicking it.

### Expected behavior
An empty video window opens.

### Actual behavior
Crash.

If you set `force-window=no` in mpv.conf, mpv starts up. But if you try to play a video, it crashes.

### Log file
https://0x0.st/sWmb.txt

Here's the output from trying to play a video file from the command line (inside the app bundle):
https://0x0.st/sWmT.txt
Which shows this error:
> 2018-07-30 14:35:39.040 mpv[2045:116152] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[macOS_swift.VideoLayer setColorspace:]: unrecognized selector sent to instance 0x7fce9ad61780'

**Comment by Cpuroast** [comment]
Is this an all patched up 10.10.5 install?
Does stolendata's mpv-0.28.2.tar.gz build work?

Also, it might be worth upgrading to at least macOS 10.11(El Capitan) as 10.10(Yosemite) is no longer supported by Apple.

10.11(El Capitan) can still be obtained here: https://support.apple.com/en-nz/HT206886
10.12(Sierra) can still be obtained here: https://support.apple.com/en-us/HT208202

**Comment by Akemi** [comment]
probably fixed with #6041, though untested for mentioned reasons.

**Comment by sumyungguy** [comment]
[**@Cpuroast**](https://github.com/Cpuroast) commented on [Jul 30, 2018, 5:12 PM GMT+2](https://github.com/mpv-player/mpv/issues/6041#issuecomment-408898545 "2018-07-30T15:12:02Z - Replied by Github Reply Comments"):
> Is this an all patched up 10.10.5 install?  Does stolendata's mpv-0.28.2.tar.gz build work?

Yes and yes.

> Also, it might be worth upgrading to at least macOS 10.11(El Capitan) as 10.10(Yosemite) is no longer supported by Apple.

I know, thanks, but it's just an old box for movies and I can't because [cool story deleted] and I don't have time for that.

**Comment by j605** [comment]
> I don't have time for that.
Don't you think it is a bit rude to expect an opensource project to support an old OS that isn't even supported by the vendor.

**Comment by Akemi** [comment]
i still passively support 10.10 as long as it doesn't get in the way, and i don't really consider that one line fix 'in the way'.

at least 10.10 was the last macOS version where a layer-less opengl context worked somewhat properly.
