### ISSUE TITLE
[bug] multiple file selection problem

### ISSUE THREAD

**Issue by D1mon** [mpv-player/mpv#6042]
### mpv version and platform
1:0.29.0-1 (Manjaro x64)

this command works fine:
`mpv "/path/to/file1" "/path/to/file2" ...`

But if the arguments are substituted from the script (command), then MPV takes it as one argument:
`mpv '"/path/to/file1" "/path/to/file2"'`
pay attention to single quotes

**Comment by CounterPillow** [comment]
>But if the arguments are substituted from the script (command), then MPV takes it as one argument

what? What do you mean by "from the script (command)"? Also I hope you realise that spaces being there to separate arguments is something your shell does, and not mpv

**Comment by D1mon** [comment]
mpv "$(cat ~/list | fzf -e -m | awk '{print "\""$0"\""}')"

**Comment by CounterPillow** [comment]
@D1mon that's not an mpv issue, that's you not understanding how quotation rules work on shells.

`mpv "a b c"` is going to pass in one argument `a b c`.

`mpv a b c` is going to pass in three arguments `a`, `b` and `c`.

**Comment by D1mon** [comment]
I know how the arguments are passed, I have been using it for years. If you do not understand why I wrote this, then you do not know how the arguments are passed and why I wrote as I wrote. Sorry if I offended. But you are wrong. I repeat the first example of a worker !! And the second is not present.

**Comment by CounterPillow** [comment]
If you think mpv would split arguments it gets by spaces again then you clearly do not know how any command line tool ever works.

Seriously, replace `mpv` with any other application there. See how they handle it.

**Comment by tomty89** [comment]
@D1mon
```
$ cat test
a.mp3
b.m4a
c.wav
$ stat "$(cat test)"
stat: cannot stat 'a.mp3'$'\n''b.m4a'$'\n''c.wav': No such file or directory
$ stat $(cat test)
stat: cannot stat 'a.mp3': No such file or directory
stat: cannot stat 'b.m4a': No such file or directory
stat: cannot stat 'c.wav': No such file or directory
$ cat test2
abc 123.mp3
def 456.mp4
ghi 789.wav
$ stat "$(cat test2)"
stat: cannot stat 'abc 123.mp3'$'\n''def 456.mp4'$'\n''ghi 789.wav': No such file or directory
$ stat $(cat test2)
stat: cannot stat 'abc': No such file or directory
stat: cannot stat '123.mp3': No such file or directory
stat: cannot stat 'def': No such file or directory
stat: cannot stat '456.mp4': No such file or directory
stat: cannot stat 'ghi': No such file or directory
stat: cannot stat '789.wav': No such file or directory
$ (IFS=$'\n'; stat $(cat test2))
stat: cannot stat 'abc 123.mp3': No such file or directory
stat: cannot stat 'def 456.mp4': No such file or directory
stat: cannot stat 'ghi 789.wav': No such file or directory
$
```

**Comment by D1mon** [comment]
@tomty89 but you did not forget to create the files ??? because it works for me:
```
cat /tmp/test 
a.mp3
b.m4a
c.wav
```

```
stat $(cat test)
  File: a.mp3
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 2bh/43d Inode: 26          Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   dimon)   Gid: ( 1000/   dimon)
Access: 2018-07-31 10:08:49.347622000 +0300
Modify: 2018-07-31 10:08:49.347622000 +0300
Change: 2018-07-31 10:08:49.347622000 +0300
 Birth: -
  File: b.m4a
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 2bh/43d Inode: 27          Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   dimon)   Gid: ( 1000/   dimon)
Access: 2018-07-31 10:08:49.347622000 +0300
Modify: 2018-07-31 10:08:49.347622000 +0300
Change: 2018-07-31 10:08:49.347622000 +0300
 Birth: -
  File: c.wav
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 2bh/43d Inode: 29          Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   dimon)   Gid: ( 1000/   dimon)
Access: 2018-07-31 10:08:49.347622000 +0300
Modify: 2018-07-31 10:08:49.347622000 +0300
Change: 2018-07-31 10:08:49.347622000 +0300
 Birth: -
```

```
stat "$(cat test)"
stat: cannot stat 'a.mp3'$'\n''b.m4a'$'\n''c.wav': No such file or directory
```

**Comment by bitraid** [comment]
@D1mon i think you are missing the point.
He was just showing you how you can/can't pass arguments form a text file list, including file names with and without spaces, using the cat command from a posix shell. Ofcourse if the files exist the command will work (where its supossed to). And if you replace `stat` with `mpv` the files will play.

**Comment by D1mon** [comment]
@bitraid Thank you. This is suitable, but not quite. It does not work if there are spaces in the file name. Single and double quotes do not help. And you need to specify the full path to the file.

**Comment by bitraid** [comment]
But it does:

```
>cat list
dir with spaces/file with spaces.mp4

>(IFS=$'\n'; mpv $(cat list))
   cplayer: Playing: dir with spaces/file with spaces.mp4
```

**Comment by D1mon** [comment]
@bitraid I have long been trying to solve this problem (problem), but it did not work. Thank you so much. Everything worked!
