### ISSUE TITLE
mpv crashes with ANGLE GPU context

### ISSUE THREAD

**Issue by Venoox** [mpv-player/mpv#6045]
### mpv version and platform
I'm using the latest git master (mpv 0.29.0-5-g5532a3da1e) on Windows 10 64-bit
### Reproduction steps
I tried compiling mpv with msys2. I followed all instructions in the docs and built it.
### Expected behavior
It should be able to play any video.
### Actual behavior
I tried playing any video and it was all the same error:

```
mpv.com 37080096_206645276699779_7584969119003114461_n.mp4
Playing: 37080096_206645276699779_7584969119003114461_n.mp4
 (+) Video --vid=1 (*) (h264 640x1204 30.000fps)
VO: [gpu] 640x1204 yuv420p
Assertion failed!

Program: C:\msys64\mingw64\bin\mpv.exe
File: ../src/libANGLE/Context.h, Line 1601

Expression: mSavedArgsType->hasDynamicType(T::TypeInfo)
```

### Log file

[https://0x0.st/sWO8.txt](https://0x0.st/sWO8.txt)

### Sample files

Any video file

I'm sorry if I'm doing this wrong, I'm new to this and didn't know where else to ask...

**Comment by lachs0r** [comment]
Looks like an ANGLE bug. I don’t even build with ANGLE anymore because it kept breaking randomly (along with its build system).

**Comment by Chesster1883** [comment]
This issue still occurring nearly 10 months on

Is it possible to update the DOCS to compile mpv with msys2 to work around this bug? I'm completely new and can't work out how to get the "simple.c" example from here working on Windows: https://github.com/mpv-player/mpv-examples/blob/master/libmpv/simple/simple.c

**Comment by morphogo** [comment]
This isn't a mpv issue. The version of libangle with mys2 is too old. I tested the git master of libangle compiled with visual studio 2019 and this issue no longer occurs.

**Comment by wm4** [comment]
Closing as this seems to be an old and fixed ANGLE bug or broken build.
