### ISSUE TITLE
Install by Brew but nothing in /Applications : Linkapps not working 

### ISSUE THREAD

**Issue by Hoangmlp** [mpv-player/mpv#6049]
dear , 
I install MPV by Brew and found nothing in /Application . 
in /usr/local/Cellar/mpv/[version]/  also don't have Mpv.app there . 

try to use Linkapps but not working . 

How can i have this Mpv.app with full code from Brew ? 

Thank you very much .

**Comment by Akemi** [comment]
btw we are not the homebrew issue tracker.

though you can either do `brew install --with-bundle mpv` and then create a symlink of the bundle from the brew build folder or just copy it, or us `brew cask`.
