### ISSUE TITLE
[Wishlist] Change audio device

### ISSUE THREAD

**Issue by copywrong** [mpv-player/mpv#605]
It's not possible to change audio DEVICE without stopping playback and editing mpv config.

**Comment by wm4** [comment]
Actually this is implemented now (and has been for a while) - it's done by writing to the `audio-device` property for example.

**Comment by lachs0r** [comment]
There’s a user script for that:
https://gist.github.com/bitingsock/ad58ee5da560ecb922fa4a867ac0ecfd

**Comment by hoover67** [comment]
Thanks for the link! What would I need to set the audio device to on
Windows and Linux ("pulseaudio" for the latter, I assume)?

All the best, Uwe

**Comment by slrslr** [comment]
I am missing this too, built in support would be nice, but on my computer there is many audio devices listed, not sure how switching would be done, unless cycling through like 15 devices. @mia-0 workaround [is not working for me](https://gist.github.com/bitingsock/ad58ee5da560ecb922fa4a867ac0ecfd#gistcomment-3777958). How about reopening this?

**Comment by vassilisw** [comment]
> PS: why would you want that anyway? Normally, you pick an AO that works for you (or even just use the autoselected AO), and be done with it.

Many people have multiple audio devices, e.g. default speakers, audio interface of a hardware mixer, etc. I would like to see movies using the one audio device and do teams, skype, etc using the internal speakers.
