### ISSUE TITLE
[coreaudio_exclusive] Failed to switch audio format

### ISSUE THREAD

**Issue by macdavis** [mpv-player/mpv#6050]
### mpv version and platform
mpv git 5532a3d
MacOS 10.13.6 (17G65)

### Reproduction steps
Set ao to "coreaudio_exclusive". Play attached "out_24.flac". During playing, drag "16_bit.flac" into the player.

### Actual behavior

> [ao/coreaudio_exclusive] could not check whether device is alive (jbo[33]/560947818)
[ao/coreaudio_exclusive] device is not alive
[ao/coreaudio_exclusive] failed to set hogmode (jbo[33]/560947818)
[ao/coreaudio_exclusive] could not get number of streams (jbo[33]/560947818)
[ao/coreaudio_exclusive] can't remove format change listener (jbo[33]/560947818)
[ao] Failed to initialize audio driver 'coreaudio_exclusive'
[cplayer] Could not open/initialize audio device -> no sound.

### Log file
[https://0x0.st/sWwc.txt](https://0x0.st/sWwc.txt)

### Sample files
[out_24.flac](https://0x0.st/sWwA.flac)
[16_bit.flac](https://0x0.st/sWwa.flac)

**Comment by Dudemanguy** [comment]
Does anyone know if this still is a problem?

**Comment by macdavis** [comment]
Confirming this issue has been fixed in the lateset version. Thanks all for your help!
