### ISSUE TITLE
Series version of file-specific mpv.conf

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#6051]
I'm aware that if I have a folder with, say, Titanic.mkv and a mpv.conf file, the attributes of mpv.conf will be applied to Titanic.mkv (in my case, I use it to pre-select audio and subtitle channel). My problem is that I want to apply this to series, were I'll have one folder with 50 episodes, that I wouldn't be able to move into individual folders because of torrent-related conflicts (mainly seeding errors).

How can I resolve this? Any chance for something like "filename.conf" getting picked up?

**Comment by zc62** [comment]
https://mpv.io/manual/master/#file-specific-configuration-files

**Comment by firewater2** [comment]
I can't believe they're actually called file-specific configuration files, I really just hacked in that wording before submitting. Thanks.
