### ISSUE TITLE
Specific mkv files. Audio is played 300ms faster. It happens only with mpv.exe.

### ISSUE THREAD

**Issue by mpvtester** [mpv-player/mpv#6056]
### mpv version and platform

mpv all version.
windows 10 pro 64bit.

### Reproduction steps

Uploaded Specific mkv files(*).
Audio is played 300ms faster.

It happens only with mpv.exe. Other Movie Players (Including mplayer.exe) will not have this problem.

There is no problem converting the MKV container to MP4, but when you return to MKV again, problems arise.

(*)
Japanese live streaming site(http://live.nicovideo.jp/).
TimeShift file.
downloaded flv(rtmp). (not encode)
cut by mkv. (not encode)

### Sample files

http://fast-uploader.com/file/7089018041817/
Download from the bottom link "このファイルをダウンロードする"

**Comment by Akemi** [comment]
if this still happens, please open a new issue.
