### ISSUE TITLE
Video is greenish and UI elements are black

### ISSUE THREAD

**Issue by lsvy97** [mpv-player/mpv#6060]
### mpv version and platform

MPV version: mpv-i686-20180804-git-5532a3d by shinchiro;
OS: Windows 7 Home Premium;
Netbook: Asus Eee PC 1005P.

### Reproduction steps

Launch any video.

### Expected behavior

Video color is correct and UI elements are white.

### Actual behavior

Video color is broken (mostly greenish) and UI elements are black (also look like shadow or outline)

### Log file

https://0x0.st/s4j_.txt

### Sample files

Sample video in WMP:

![wmp](https://user-images.githubusercontent.com/32693465/43839701-f4b0195a-9b48-11e8-8d58-d3c6598cc610.png)

Same video in MPV:

![mpv](https://user-images.githubusercontent.com/32693465/43839700-f4851750-9b48-11e8-8264-15b562d11f0c.png)

**Comment by CrisBRM** [comment]
This has to do with the hwdec being picked. I had a similar problem on my old eee pc.

**Comment by lsvy97** [comment]
@CrisBRM changing hardware decoding didn't solve anything, but changing video output drivers did. I've set `vo=direct3d` and it works, thanks for pointing in the right direction.
![mpv2](https://user-images.githubusercontent.com/32693465/43846998-d22af74a-9b59-11e8-8491-7ee7b39339ce.png)

**Comment by shinchiro** [comment]
Did you have graphic driver installed? Since the log told otherwise. Also `vo=direct3d` is not recommended to use.
```
[   0.199][v][vo/gpu] Probing for best GPU context.
[   0.199][v][vo/gpu/d3d11] Initializing GPU context 'd3d11'
[   0.202][d][vo/gpu/d3d11] Failed to create 12_0+ device, trying 11_1
[   0.202][d][vo/gpu/d3d11] Failed to create 11_1+ device, trying 11_0
[   0.351][v][vo/gpu/d3d11] Using Direct3D 11 feature level 9_1
[   0.351][v][vo/gpu/d3d11] Device Name: Software Adapter
[   0.352][v][vo/gpu/d3d11] Device ID: 0000:0000 (rev 00)
[   0.352][v][vo/gpu/d3d11] Subsystem ID: 0000:0000
[   0.352][v][vo/gpu/d3d11] LUID: 00000000000072fc
[   0.353][v][vo/gpu/d3d11] Initializing SPIR-V compiler 'shaderc'
[   0.354][v][vo/gpu/d3d11] Using Direct3D 11.0 runtime
[   0.354][v][vo/gpu/d3d11] Maximum Texture2D size: 4096x4096
[   0.364][v][vo/gpu/d3d11] D3DCompiler version: 10.0.17134.12
[   0.434][v][vo/gpu/d3d11] Using DXGI 1.1
[   0.434][v][vo/gpu/d3d11] Using bitblt-model presentation
```

**Comment by lsvy97** [comment]
@shinchiro
Well, that netbook is just from service center and I had to install again all the drivers. Luckily, all of them are present on the official site. Reinstalled the graphic driver again, result is the same. There is another (older) driver on the site, will try when get access to Internet.

**Comment by lsvy97** [comment]
@shinchiro

Tried to install another driver, tried auto-upgrade it from device manager, but video is still greenish without `vo=direct3d`.

**Comment by Doofussy2** [comment]
try gpu-api=opengl

I'm not sure if this relates to an experience I'm having. I use an LED backlighting system called [DreamScreen](https://www.dreamscreentv.com/). The LEDs respond to the video colors, and with many of my movies the LEDs are all green, with gpu-api=d3d11. Changing to opengl, they respond correctly. So I think there may be an issue with the d3d11 api.
