### ISSUE TITLE
Unexpected crash on waking from sleep

### ISSUE THREAD

**Issue by chinnnki** [mpv-player/mpv#6062]
### mpv version and platform

mpv version: current master + #5953
Platform: macOS 10.14 beta (18A353d)

### Reproduction steps

Playback on external display (connected via HDMI), in fullscreen mode and paused.
Leave the devices idle for several minutes for the system to go to sleep.
Wake the MacBook up to find that mpv has crashed.

### Expected behavior

Playback window remains intact after waking up.

### Actual behavior

Playback window crashes.

### Log file

System crash report: https://0x0.st/s4f9.txt

### Sample files

None.

**Comment by Akemi** [comment]
yeah i noticed that recently too when i watched something on my TV. i will look into it this evening when i get back from work.

**Comment by Akemi** [comment]
should be fixed with #6064.
