### ISSUE TITLE
cp1250 encoded subtitle file shows bad diacritics

### ISSUE THREAD

**Issue by slrslr** [mpv-player/mpv#6065]
### mpv version and platform

mpv 0.14.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
LUbuntu 16.04 LTS

### Reproduction steps

Download .srt file with czech language subtitles encoded in CP1250 (it is encoding common for czech charset files. Example [this](https://www.titulky.com/idown.php?R=1533926034&titulky=0000145694&zip=&histstamp=&toUTF=0&T=1-1533926043338) (direct link) or indirect link [here](https://www.titulky.com/Greta-145694.htm)

When i play movie, it shows bad characters instead ones with diacritics. But when i open .srt file and save it as UTF-8 then the subtitles are right. Please kindly support CP1250 .srt files with czech characters like: ěščřžýáíé

Thank You

**Comment by Akemi** [comment]
update your mpv.

**Comment by CounterPillow** [comment]
the one that uninstalls ubuntu

Your mpv is from 2015, because all packages in Ubuntu 16.04 are that outdated.

**Comment by Akemi** [comment]
update your OS, 0.14 is from 2015 for gods sake. alternatively use [mpv-build](https://github.com/mpv-player/mpv-build) or one of the packages [here](https://mpv.io/installation/). we can't be taken responsible for outdated OS' or packages.

**Comment by MarkShuttlecock** [comment]
Ubuntu 16.04 is a long-term-support release, so you are legally obligated to provide support for it. Re-open this issue right now or I will contact my team of lawyers.

**Comment by slrslr** [comment]
@Akemi @CounterPillow "Lubuntu 16.04 LTS will be supported until April 2019, with three years of support." ([source](https://lubuntu.me/xenial-released/))

When i do $ ubuntu-support-status --show-all, it says mpv is within group "Podporováno do duben 2021 (Community - 5y):" which translates into: Supported to april 2021 (Community - 5y)
Can anyone please update mpv in that repository (i have main universe restricted multiverse)? Or what is the issue? that the LTS release has mpv from 2015?
https://www.ubuntu.com/info/release-end-of-life

**Comment by CounterPillow** [comment]
We are not "the Ubuntu community". You're at the wrong place here. If you want a bug fixed in Ubuntu, report it to their bugtracker.

**Comment by slrslr** [comment]
Hello, I have found a tutorial that contained following commands i executed:

> sudo add-apt-repository ppa:mc3man/mpv-tests
> sudo apt update && sudo apt install mpv

resulting installed package now is: mpv/xenial,now 2:0.28.0+git7~xenial3 i386

But the video with subtitles continue having bad characters. When i open the .srt file, all characters are good and Save As shows Encoding CP1250 and CR+LF (unsure if it means it is current state of the file)

So please where is the problem that MPV do not properly read the .srt file? @CounterPillow @Akemi
