### ISSUE TITLE
hwdec:vaapi shifting colours?

### ISSUE THREAD

**Issue by kyyu** [mpv-player/mpv#6066]
### mpv version and platform

```
[cplayer] mpv 0.29.0 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Jul 22 21:06:23 CEST 2018
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.14.100
[cplayer]    libavcodec      58.18.100
[cplayer]    libavformat     58.12.100
[cplayer]    libswscale      5.1.100
[cplayer]    libavfilter     7.16.100
[cplayer]    libswresample   3.1.100
[cplayer] ffmpeg version: 4.0
4.16.13-1-ARCH x64
```

### Reproduction steps
hwdec=auto in mpv.conf
open sample mpeg2video video (hwdec:vaapi)
video displays with shifted colours

options tested:
hwdec=vaapi = same result
w/ vo=gpu = same result
w/ vo=vaapi = same result
RESULT: see Actual behavior

However with hwdec=no in mpv.conf, opening sample mpeg2video video (no hwdec) yields Expected behavior

### Expected behavior
video displays normally
https://0x0.st/s4l6.jpg

### Actual behavior
video displays with shifted colours
https://0x0.st/s4lE.jpg

### Log file
https://0x0.st/s4lv.txt

### Sample files
https://0x0.st/s4l4.ts

**Comment by CounterPillow** [comment]
Works for me on newer intel hardware and vaapi version 1.2 (libva 2.2.0), I think it may be a bug in VAAPI itself and not mpv.

**Comment by lachs0r** [comment]
Blows my mind that Intel can’t even get something as basic as not flipping the chroma planes right. Probably only affects older chips though. I can’t reproduce this on Haswell or Skylake. And my eeePC 900 is too old to even support VA-API (but even that one manages to play this stream without hwdec, so I think we should just un-whitelist mpeg2video again).

**Comment by aufkrawall** [comment]
"un-whitelist" means no hwdec by default for mpeg2?
I wouldn't really like this, since hwdec can also be beneficial on fast CPUs when you run demanding background tasks while watching a video. It also allows vaapi-deinterlacing.

**Comment by lachs0r** [comment]
About this far.
