### ISSUE TITLE
Disabling OSD bar border

### ISSUE THREAD

**Issue by FatherOfAlways** [mpv-player/mpv#6067]
Hello.

Is there a way to disable the border of the OSD bar?

I tried setting `--osd-border-size` to 0 and `--osd-back-color` to 0.0/0.0/0.0/0.0 (basically transparent color) but I'm still getting a 1px border around the bar: https://0x0.st/sJrd.png

I'm running 0.29.0 on macOS 10.13.6

**Comment by Akemi** [comment]
no.
