### ISSUE TITLE
[lavf] error reading packet.

### ISSUE THREAD

**Issue by shez2** [mpv-player/mpv#6069]
mpv git-2018-07-22-45beb70
Ubuntu 18.04.1 LTS (Bionic Beaver)

v4l2-ctl --list-devices
ezcap U3 capture: ezcap U3 capt (usb-0000:00:15.0-1):
	/dev/video0

(EM2860/SAA711X Reference Design (usb-0000:00:15.0-3):
	/dev/video1)

When mpv exits I do:
modprobe -v -r uvcvideo
modprobe -v uvcvideo
and hope for the best.

V: 02:03:35 / 02:03:35 (99%)
[ffmpeg/demuxer] video4linux2,v4l2: Dequeued v4l2 buffer contains 1843192 bytes, but 1843200 were expected. Flags: 0x00012001.
[lavf] error reading packet.
V: 02:03:36 / 02:03:36 (99%)
[ffmpeg/demuxer] video4linux2,v4l2: Dequeued v4l2 buffer contains 1843192 bytes, but 1843200 were expected. Flags: 0x00012001.
[lavf] error reading packet.
V: 02:03:42 / 02:03:42 (99%)
[ffmpeg/demuxer] video4linux2,v4l2: Dequeued v4l2 buffer contains 1843192 bytes, but 1843200 were expected. Flags: 0x00012001.
[lavf] error reading packet.
V: 02:03:42 / 02:03:42 (100%)
[ffmpeg/demuxer] video4linux2,v4l2: Dequeued v4l2 buffer contains 1843192 bytes, but 1843200 were expected. Flags: 0x00012001.
[lavf] error reading packet.
Exiting... (End of file)

**Comment by shez2** [comment]
mpv av://v4l2:/dev/video0

**Comment by shez2** [comment]
Ok put /usr/share/X11/xorg.conf.d/20-intel.conf

Section "Device"
Identifier "Intel Graphics"
Driver "intel"
Option "TearFree" "true"
Option "VSync" "1"
Option 	    "AccelMethod" "sna"
Option 	    "DRI" "2"
EndSection
Section "Module"
Load  "dbe"
EndSection

and run:
mpv av://v4l2:/dev/video0 --keep-open --untimed

No errors so far...

**Comment by wm4** [comment]
> Few errors so far...

Closing because it works for the user?
