### ISSUE TITLE
Keyboard input default config missing

### ISSUE THREAD

**Issue by sabvente** [mpv-player/mpv#6073]
### mpv version and platform

mpv 0.29.0 Windows build by lachs0r
Windows 10

### Reproduction steps

Running mpv from command line:
`mpv file.mkv --o=\\.\pipe\mypipe --of=matroska`

### Expected behavior

To be able to use keyboard input from terminal with the default input config.

### Actual behavior

Warning messages after button press like this:
`[input] No key binding found for key 'RIGHT'.`

I've tried setting the following options without luck:
`--input-terminal`
`--input-conf=<filename>`
`--player-operation-mode=pseudo-gui`
### Log file
http://0x0.st/sJVU.txt

**Comment by sfan5** [comment]
With `-o` encoding mode is enabled and no keybindings will work. This is on purpose.

**Comment by sabvente** [comment]
I'm trying to split the audio and the video output with `--o=\\.\pipe\mypipe`.

Use `[...] mypipe | mpv -` to display the video locally, and use `[...] mypipe | ffmpeg {stream}` to stream the audio to a remote.

This setup works, but I can't control the media (pause, play, etc.).

Do you know a possible way to achive this with MPV? Or can I force the keybindings to work even with `-o` mode?

**Comment by sfan5** [comment]
Your best bet is to play the video normally using mpv and grab the audio that is being played (Windows calls this "Stereo Mix") with ffmpeg to stream it somewhere else

**Comment by garoto** [comment]
Possibly related with #5005?

**Comment by wm4** [comment]
Using encode mode as "editor" won't really work well. Alternatively, you could for example write a Lua script that creates an EDL file on keyboard input, and then encode the EDL file to get something that can be consumed by other players.
