### ISSUE TITLE
When running with --osd-level=3, pressing 'O' has no effect the first time

### ISSUE THREAD

**Issue by arschficken** [mpv-player/mpv#6080]
### mpv version and platform
mpv 0.27.2, Kubuntu 18.04 on amd64

### Reproduction steps
Play a video with --osd-level=3, then press 'O' (Shift+o) several times.

### Expected behavior
Since the display is already in OSD level 3, the first press of 'O' should switch to OSD level 1.

### Actual behavior
The first press of 'O' seems to re-enter the already active OSD level 3. In practice, nothing happens. Subsequent presses work as expected, cycling between OSD levels 1 and 3.

### Log file
[cplayer] Command line options: '--osd-level=3' '-v' '/home/user/video/test.mp4'                                   
[cplayer] mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects                
[cplayer]  built on UNKNOWN                                                     
[cplayer] ffmpeg library versions:                                              
[cplayer]    libavutil       55.78.100                                          
[cplayer]    libavcodec      57.107.100                                         
[cplayer]    libavformat     57.83.100                                          
[cplayer]    libswscale      4.8.100                                            
[cplayer]    libavfilter     6.107.100                                          
[cplayer]    libswresample   2.9.100                                            
[cplayer] ffmpeg version: 3.4.2-2                                               
[cplayer]                                                                       
[cplayer] Configuration: ./waf configure --prefix=/usr --libdir=/usr/lib/x86_64-linux-gnu --confdir=/etc/mpv --zshdir=/usr/share/zsh/vendor-completions --enable-cdda --enable-dvdnav --enable-dvdread --enable-encoding --enable-libmpv-shared --enable-libsmbclient --enable-sdl2 --enable-sndio --enable-zsh-comp --disable-build-date --enable-dvbin                                                        
[cplayer] List of enabled features: 52arch alsa asm atomics avutil-content-light-level avutil-icc-profile avutil-imgcpy-uc avutil-spherical caca cdda cplayer cplugins cuda-hwaccel debug-build drm dvbin dvdnav dvdread dvdread-common egl-drm egl-helpers egl-x11 encoding fchmod gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc iconv is_ffmpeg jack jpeg lcms2 libass libass-osd libav libavcodec libavdevice libbluray libdl libm libmpv-shared librt libsmbclient linux-fstatfs lua nanosleep optimize oss-audio plain-gl posix posix-or-mingw posix-spawn pthreads pulse rubberband sdl2 shm sndio stdatomic termios uchardet vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-hwaccel vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vdpau-hwaccel vt.h wayland x11 xv zlib zsh-comp            
[global] config path: '' -> '/home/user/.config/mpv'                             
[global] config path: 'encoding-profiles.conf' -/-> '/home/user/.config/mpv/encoding-profiles.conf'                                                              
[global] config path: 'encoding-profiles.conf' -/-> '/home/user/.mpv/encoding-profiles.conf'                                                                     
[global] config path: 'encoding-profiles.conf' -> '/etc/mpv/encoding-profiles.conf'                                                                             
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf                   
[global] config path: 'mpv.conf' -/-> '/home/user/.config/mpv/mpv.conf'          
[global] config path: 'config' -/-> '/home/user/.config/mpv/config'              
[global] config path: 'mpv.conf' -/-> '/home/user/.mpv/mpv.conf'                 
[global] config path: 'config' -/-> '/home/user/.mpv/config'                     
[global] config path: 'mpv.conf' -> '/etc/mpv/mpv.conf'                         
[global] config path: 'config' -/-> '/etc/mpv/config'                           
[cplayer] Reading config file /etc/mpv/mpv.conf                                 
[cplayer] Setting option 'hwdec' = 'vaapi' (flags = 4)                          
[cplayer] Setting option 'osd-level' = '3' (flags = 8)                          
[cplayer] Setting option 'v' = '' (flags = 8)                                   
[global] config path: 'input.conf' -/-> '/home/user/.config/mpv/input.conf'      
[global] config path: 'input.conf' -/-> '/home/user/.mpv/input.conf'             
[global] config path: 'input.conf' -/-> '/etc/mpv/input.conf'                   
[osc] Loading lua script @osc.lua...                                            
[global] config path: 'scripts' -/-> '/home/user/.config/mpv/scripts'            
[global] config path: 'scripts' -/-> '/home/user/.mpv/scripts'                   
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'                         
[osc] loading mp.defaults                                                       
[osc] loading @osc.lua                                                          
[global] config path: 'lua-settings/osc.conf' -/-> '/home/user/.config/mpv/lua-settings/osc.conf'                                                                
[global] config path: 'lua-settings/osc.conf' -/-> '/home/user/.mpv/lua-settings/osc.conf'                                                                       
[global] config path: 'lua-settings/osc.conf' -/-> '/etc/mpv/lua-settings/osc.conf'                                                                             
[osc] lua-settings/osc.conf not found.                                          
[cplayer] Run command: define-section, flags=0, args=[showhide, mouse_move script-binding osc/__keybinding1                                                     
[cplayer] mouse_leave script-binding osc/__keybinding2                          
[cplayer] , force]                                                              
[cplayer] Run command: enable-section, flags=0, args=[showhide, allow-hide-cursor+allow-vo-dragging]                                                            
[cplayer] Run command: define-section, flags=0, args=[input, mbtn_left script-binding osc/__keybinding3                                                         
[cplayer] shift+mbtn_left script-binding osc/__keybinding4                      
[cplayer] mbtn_right script-binding osc/__keybinding5                           
[cplayer] wheel_up script-binding osc/__keybinding6                             
[cplayer] wheel_down script-binding osc/__keybinding7                           
[cplayer] mbtn_left_dbl ignore                                                  
[cplayer] shift+mbtn_left_dbl ignore                                            
[cplayer] mbtn_right_dbl ignore                                                 
[cplayer] , force]                                                              
[cplayer] Run command: enable-section, flags=0, args=[input, ]                  
[cplayer] Run command: define-section, flags=0, args=[input_osc, del script-binding osc/__keybinding8                                                           
[cplayer] , default]                                                            
[cplayer] Run command: enable-section, flags=0, args=[input_osc, allow-hide-cursor+allow-vo-dragging]                                                           
[cplayer] Run command: define-section, flags=0, args=[input_forced_osc, , force]
[cplayer] Run command: enable-section, flags=0, args=[input_forced_osc, allow-hide-cursor+allow-vo-dragging]                                                    
[cplayer] Done loading @osc.lua.                                                
[ytdl_hook] Loading lua script @ytdl_hook.lua...                                
[global] config path: 'scripts' -/-> '/home/user/.config/mpv/scripts'            
[global] config path: 'scripts' -/-> '/home/user/.mpv/scripts'                   
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'                         
[ytdl_hook] loading mp.defaults                                                 
[cplayer] Run command: disable-section, flags=0, args=[input]                   
[global] config path: 'fonts' -/-> '/home/user/.config/mpv/fonts'                
[global] config path: 'fonts' -/-> '/home/user/.mpv/fonts'                       
[global] config path: 'fonts' -/-> '/etc/mpv/fonts'                             
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.7.2 (COMPLEX)        
[global] config path: 'subfont.ttf' -/-> '/home/user/.config/mpv/subfont.ttf'    
[global] config path: 'subfont.ttf' -/-> '/home/user/.mpv/subfont.ttf'           
[global] config path: 'subfont.ttf' -/-> '/etc/mpv/subfont.ttf'                 
[global] config path: 'fonts.conf' -/-> '/home/user/.config/mpv/fonts.conf'      
[global] config path: 'fonts.conf' -/-> '/home/user/.mpv/fonts.conf'             
[global] config path: 'fonts.conf' -/-> '/etc/mpv/fonts.conf'                   
[osd/libass] Setting up fonts...                                                
[ytdl_hook] loading @ytdl_hook.lua                                              
[global] config path: 'lua-settings/ytdl_hook.conf' -/-> '/home/user/.config/mpv/lua-settings/ytdl_hook.conf'                                                    
[global] config path: 'lua-settings/ytdl_hook.conf' -/-> '/home/user/.mpv/lua-settings/ytdl_hook.conf'                                                           
[global] config path: 'lua-settings/ytdl_hook.conf' -/-> '/etc/mpv/lua-settings/ytdl_hook.conf'                                                                 
[ytdl_hook] lua-settings/ytdl_hook.conf not found.                              
[cplayer] Run command: hook-add, flags=0, args=[on_load, 1, 10]                 
[cplayer] Run command: hook-add, flags=0, args=[on_preloaded, 2, 10]            
[cplayer] Done loading @ytdl_hook.lua.                                          
[global] config path: 'scripts' -/-> '/home/user/.config/mpv/scripts'            
[global] config path: 'scripts' -/-> '/home/user/.mpv/scripts'                   
[global] config path: 'scripts' -/-> '/etc/mpv/scripts'                         
[global] config path: 'watch_later' -> '/home/user/.config/mpv/watch_later'      
[cplayer] Playing: /home/user/video/test.mp4
[cplayer] Running hook: ytdl_hook/on_load
[osd/libass] Using font provider fontconfig                                     
[osd/libass] Done.                                                              
[cplayer] Run command: hook-ack, flags=0, args=[on_load]                        
[ifo] Opening /home/user/video/test.mp4                                                                            
[ifo_dvdnav] Opening /home/user/video/test.mp4                                                                     
[bdmv/bluray] Opening /home/user/video/test.mp4                                                                    
[file] Opening /home/user/video/test.mp4                                                                           
[file] Stream opened successfully.                                              
[demux] Trying demuxers for level=normal.                                       
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.                  
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)             
[cplayer] Opening done: /home/user/video/test.mp4                                                                  
[find_files] Loading external files in /home/user/video/test                                                       
[global] config path: 'sub' -/-> '/home/user/.config/mpv/sub'                    
[global] config path: 'sub' -/-> '/home/user/.mpv/sub'                           
[global] config path: 'sub' -/-> '/etc/mpv/sub'                                 
[cplayer] Running hook: ytdl_hook/on_preloaded                                  
[cplayer] Run command: hook-ack, flags=0, args=[on_preloaded]                   
[cplayer]  (+) Video --vid=1 (*) (h264 1920x1080 60.000fps)
[cplayer]  (+) Audio --aid=1 --alang=und (*) (mp3 2ch 44100Hz)
[vo/opengl] Initializing OpenGL backend 'wayland'
[vo/opengl/wayland] failed to connect to a wayland server: check if a wayland compositor is running                                                             
[vo/opengl] Initializing OpenGL backend 'x11probe'                              
[vo/opengl/x11] X11 opening display: :0                                         
[vo/opengl/x11] X11 running at 1920x1200 (":0" => local display)                
[vo/opengl/x11] Detected wm supports NetWM.                                     
[vo/opengl/x11] Detected wm supports FULLSCREEN state.                          
[vo/opengl/x11] Detected wm supports ABOVE state.                               
[vo/opengl/x11] Detected wm supports BELOW state.                               
[vo/opengl/x11] Detected wm supports STAYS_ON_TOP state.                        
[vo/opengl/x11] Display 0 (HDMI-2): [0, 0, 1920, 1200] @ 59.950171 FPS          
[vo/opengl/x11] Current display FPS: 59.950171                                  
[vo/opengl] GLX chose FB config with ID 0xa9                                    
[vo/opengl] GLX chose visual with ID 0xf0                                       
[vo/opengl] Creating OpenGL 4.4 context...                                      
[vo/opengl/x11] X11 error: GLXBadFBConfig                                       
[vo/opengl/x11] Type: 0, display: 0x7f289823a970, resourceid: 160, serial: 42   
[vo/opengl/x11] Error code: b3, request code: 9b, minor code: 22                
[vo/opengl] Creating OpenGL 4.3 context...                                      
[vo/opengl/x11] X11 error: GLXBadFBConfig                                       
[vo/opengl/x11] Type: 0, display: 0x7f289823a970, resourceid: 160, serial: 45   
[vo/opengl/x11] Error code: b3, request code: 9b, minor code: 22                
[vo/opengl] Creating OpenGL 4.0 context...                                      
[vo/opengl/x11] X11 error: GLXBadFBConfig                                       
[vo/opengl/x11] Type: 0, display: 0x7f289823a970, resourceid: 160, serial: 48   
[vo/opengl/x11] Error code: b3, request code: 9b, minor code: 22                
[vo/opengl] Creating OpenGL 3.3 context...                                      
[vo/opengl] GL_VERSION='3.3 (Core Profile) Mesa 18.0.5'                         
[vo/opengl] Detected desktop OpenGL 3.3.                                        
[vo/opengl] GL_VENDOR='Intel Open Source Technology Center'                     
[vo/opengl] GL_RENDERER='Mesa DRI Intel(R) Sandybridge Mobile '                 
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='3.30'                                  
[vo/opengl] Loaded extension GL_ARB_get_program_binary.                         
[vo/opengl] Loaded extension GL_ARB_buffer_storage.                             
[vo/opengl] Loaded extension GL_ARB_arrays_of_arrays.                           
[vo/opengl] Loaded extension GLX_SGI_swap_control.                              
[vo/opengl] Loaded extension GLX_SGI_video_sync.                                
[vo/opengl] Loaded extension GL_ARB_debug_output.                               
[vo/opengl] No vdpau support found - probing more things.                       
[vo/opengl/x11] uninit ...                                                      
[vo/opengl] Initializing OpenGL backend 'x11egl'                                
[vo/opengl/x11] X11 opening display: :0                                         
[vo/opengl/x11] X11 running at 1920x1200 (":0" => local display)                
[vo/opengl/x11] Detected wm supports NetWM.                                     
[vo/opengl/x11] Detected wm supports FULLSCREEN state.                          
[vo/opengl/x11] Detected wm supports ABOVE state.                               
[vo/opengl/x11] Detected wm supports BELOW state.                               
[vo/opengl/x11] Detected wm supports STAYS_ON_TOP state.                        
[vo/opengl/x11] Display 0 (HDMI-2): [0, 0, 1920, 1200] @ 59.950171 FPS          
[vo/opengl/x11] Current display FPS: 59.950171                                  
[vo/opengl] EGL_VERSION=1.4 (DRI2)                                              
[vo/opengl] EGL_VENDOR=Mesa Project                                             
[vo/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES                                    
[vo/opengl] Trying to create Desktop OpenGL context.                            
[vo/opengl] chose visual 0x21                                                   
[vo/opengl] GL_VERSION='3.3 (Core Profile) Mesa 18.0.5'                         
[vo/opengl] Detected desktop OpenGL 3.3.                                        
[vo/opengl] GL_VENDOR='Intel Open Source Technology Center'                     
[vo/opengl] GL_RENDERER='Mesa DRI Intel(R) Sandybridge Mobile '                 
[vo/opengl] GL_SHADING_LANGUAGE_VERSION='3.30'                                  
[vo/opengl] Loaded extension GL_ARB_get_program_binary.                         
[vo/opengl] Loaded extension GL_ARB_buffer_storage.                             
[vo/opengl] Loaded extension GL_ARB_arrays_of_arrays.                           
[vo/opengl] Loaded extension GL_ARB_debug_output.                               
[vo/opengl] swap_control extension missing.                                     
[vo/opengl] Testing FBO format rgba16                                           
[vo/opengl] Create FBO: 16x16 (16x16)                                           
[vo/opengl] Using FBO format rgba16.                                            
[vo/opengl] No advanced processing required. Enabling dumb mode.                
[vo/opengl] Loading hwdec driver 'vaapi-egl'                                    
[vo/opengl/vaapi-egl] Trying to open a x11 VA display...                        
[vo/opengl/vaapi-egl/vaapi] libva: VA-API version 1.1.0                         
[vo/opengl/vaapi-egl/vaapi] libva: va_getDriverName() returns 0                 
[vo/opengl/vaapi-egl/vaapi] libva: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so                                                               
[vo/opengl/vaapi-egl/vaapi] libva: Found init function __vaDriverInit_1_1       
[vo/opengl/vaapi-egl/vaapi] libva: va_openDriver() returns 0                    
[vo/opengl/vaapi-egl/vaapi] VA API version 1.1                                  
[vo/opengl/vaapi-egl/vaapi] 9 image formats available:                          
[vo/opengl/vaapi-egl/vaapi]   YV12                                              
[vo/opengl/vaapi-egl/vaapi]   I420                                              
[vo/opengl/vaapi-egl/vaapi]   NV12                                              
[vo/opengl/vaapi-egl/vaapi]   YUY2                                              
[vo/opengl/vaapi-egl/vaapi]   UYVY                                              
[vo/opengl/vaapi-egl/vaapi]   422H                                              
[vo/opengl/vaapi-egl/vaapi]   RGBX                                              
[vo/opengl/vaapi-egl/vaapi]   BGRX                                              
[vo/opengl/vaapi-egl/vaapi]   P010                                              
[ffmpeg] AVHWDeviceContext: Matched "Intel i965 driver for Intel(R) Sandybridge Mobile - 2.1.0" as known driver "Intel i965 (Quick Sync)".                      
[vo/opengl/vaapi-egl] using VAAPI EGL interop                                   
[vo/opengl/vaapi-egl] Supported formats:                                        
[vo/opengl/vaapi-egl]  nv12                                                     
[vo/opengl/vaapi-egl]  p010                                                     
[vo/opengl] Reported display depth: 8                                           
[vo/opengl] Assuming 59.950171 FPS for display sync.                            
[vd] Container reported FPS: 60.000000                                          
[vd] Codec list:                                                                
[vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10                       
[vd]     h264_crystalhd (h264) - CrystalHD H264 decoder                         
[vd]     h264_v4l2m2m (h264) - V4L2 mem2mem H.264 decoder wrapper               
[vd]     h264_cuvid (h264) - Nvidia CUVID H264 decoder                          
[vd] Opening video decoder h264                                                 
[vd] Probing 'vaapi'...                                                         
[vd] Trying hardware decoding.                                                  
[vd] Selected video codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)     
[ad] Codec list:                                                                
[ad]     mp3 - MP3 (MPEG audio layer 3)                                         
[ad]     mp3float (mp3) - MP3 (MPEG audio layer 3)                              
[ad] Opening audio decoder mp3                                                  
[ad] Requesting 1 threads for decoding.                                         
[ad] Selected audio codec: mp3 (MP3 (MPEG audio layer 3))                       
[cplayer] Starting playback...                                                  
[af] Audio filter chain:                                                        
[af]   [in] 44100Hz stereo 2ch s16p                                             
[af]   [out] 44100Hz stereo 2ch s16p                                            
[af]   [ao] 44100Hz stereo 2ch s16p                                             
[ao] Trying audio driver 'pulse'                                                
[ao/pulse] requested format: 44100 Hz, stereo channels, s16p                    
[ao/pulse] Library version: 11.1.0                                              
[ao/pulse] Proto: 32                                                            
[ao/pulse] Server proto: 4294967295                                             
[ao/pulse] Channel layouts:                                                     
[ao/pulse]  - #fl                                                               
[ao/pulse]  - #fr                                                               
[ao/pulse]  - #fc                                                               
[ao/pulse]  - #lfe                                                              
[ao/pulse]  - #bl                                                               
[ao/pulse]  - #br                                                               
[ao/pulse]  - #flc                                                              
[ao/pulse]  - #frc                                                              
[ao/pulse]  - #bc                                                               
[ao/pulse]  - #sl                                                               
[ao/pulse]  - #sr                                                               
[ao/pulse]  - #tc                                                               
[ao/pulse]  - #tfl                                                              
[ao/pulse]  - #tfc                                                              
[ao/pulse]  - #tfr                                                              
[ao/pulse]  - #tbl                                                              
[ao/pulse]  - #tbc                                                              
[ao/pulse]  - #tbr                                                              
[ao/pulse] result: stereo                                                       
[ao/pulse] device buffer: 5513 samples.                                         
[ao/pulse] using soft-buffer of 8820 samples.                                   
[cplayer] AO: [pulse] 44100Hz stereo 2ch s16
[cplayer] AO: Description: PulseAudio audio output
[af] Adding filter lavrresample                                                 
[af] Audio filter chain:                                                        
[af]   [in] 44100Hz stereo 2ch s16p                                             
[af]   [lavrresample] 44100Hz stereo 2ch s16 [a]                                
[af]   [out] 44100Hz stereo 2ch s16                                             
[af]   [ao] 44100Hz stereo 2ch s16                                              
[vd] Pixel formats supported by decoder: vdpau vaapi_vld yuv420p                
[vd] Codec profile: High (0x64)                                                 
[vd] Requesting pixfmt 'vaapi_vld' from decoder.                                
[ffmpeg/video] h264: Reinit context to 1920x1088, pix_fmt: vaapi_vld            
[vd] Using hardware decoding (vaapi).
[vd] Decoder format: 1920x1080 vaapi[nv12] bt.709/auto/bt.1886/limited CL=mpeg2/4/h264 (auto 0.000000/0.000000/0.000000)                                        
[vd] Using container aspect ratio.                                              
[vf] Video filter chain:                                                        
[vf]   [in] 1920x1080 vaapi[nv12] bt.709/bt.709/bt.1886/limited SP=1.000000 CL=mpeg2/4/h264                                                                     
[vf]   [out] 1920x1080 vaapi[nv12] bt.709/bt.709/bt.1886/limited SP=1.000000 CL=mpeg2/4/h264                                                                    
[cplayer] VO: [opengl] 1920x1080 vaapi[nv12]
[cplayer] VO: Description: Extended OpenGL Renderer
[vo/opengl] Resize: 1920x1080                                                   
[vo/opengl] Window size: 1920x1080                                              
[vo/opengl] Video source: 1920x1080 (1:1)                                       
[vo/opengl] Video display: (0, 0) 1920x1080 -> (0, 0) 1920x1080                 
[vo/opengl] Video scale: 1.000000/1.000000                                      
[vo/opengl] OSD borders: l=0 t=0 r=0 b=0                                        
[vo/opengl] Video borders: l=0 t=0 r=0 b=0                                      
[vo/opengl] Testing FBO format rgba16                                           
[vo/opengl] Create FBO: 16x16 (16x16)                                           
[vo/opengl] Using FBO format rgba16.                                            
[vo/opengl] No advanced processing required. Enabling dumb mode.                
[vo/opengl] new shader program:                                                 
[vo/opengl] [  1] color.r = 1.000000 * vec4(texture(texture0, texcoord0)).r;    
[vo/opengl] [  2] color.gb = 1.000000 * vec4(texture(texture1, texcoord1)).rg;  
[vo/opengl] [  3] color = color.rgbr;                                           
[vo/opengl] [  4] color.rgb = mat3(colormatrix) * color.rgb + colormatrix_c;    
[vo/opengl] [  5] color.a = 1.0;                                                
[vo/opengl] [  6] // color mapping                                              
[global] config path: 'fonts' -/-> '/home/user/.config/mpv/fonts'                
[global] config path: 'fonts' -/-> '/home/user/.mpv/fonts'                       
[global] config path: 'fonts' -/-> '/etc/mpv/fonts'                             
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.7.2 (COMPLEX)        
[global] config path: 'subfont.ttf' -/-> '/home/user/.config/mpv/subfont.ttf'    
[global] config path: 'subfont.ttf' -/-> '/home/user/.mpv/subfont.ttf'           
[global] config path: 'subfont.ttf' -/-> '/etc/mpv/subfont.ttf'                 
[global] config path: 'fonts.conf' -/-> '/home/user/.config/mpv/fonts.conf'      
[global] config path: 'fonts.conf' -/-> '/home/user/.mpv/fonts.conf'             
[global] config path: 'fonts.conf' -/-> '/etc/mpv/fonts.conf'                   
[osd/libass] Setting up fonts...                                                
[osd/libass] Using font provider fontconfig                                     
[osd/libass] Done.                                                              
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf, 0, DejaVuSans                                                 
[osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular                                                       
[vo/opengl] Reallocating OSD texture to 1024x256.                               
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf, 0, DejaVuSans                                                 
[vo/opengl] new shader program:                                                 
[vo/opengl] [  1] color = vec4(ass_color.rgb, ass_color.a * texture(osdtex, texcoord).r);                                                                       
[vo/opengl] [  2] // color mapping                                              
[cplayer] first video frame after restart shown                                 
[cplayer] starting audio playback                                               
[cplayer] playback restart complete                                             
[vo/opengl] Resize: 1879x1057                                                   
[vo/opengl] Window size: 1879x1057                                              
[vo/opengl] Video source: 1920x1080 (1:1)                                       
[vo/opengl] Video display: (0, 0) 1920x1080 -> (0, 0) 1879x1057                 
[vo/opengl] Video scale: 0.978646/0.978704                                      
[vo/opengl] OSD borders: l=0 t=0 r=0 b=0                                        
[vo/opengl] Video borders: l=0 t=0 r=0 b=0                                      
[vo/opengl/x11] Disabling screensaver.
[statusline] AV: 00:00:01 / 00:03:37 (0%) A-V:  0.000
[cplayer] Run command: cycle-values, flags=8, args=[osd-level, 3, 1]
[cplayer] Set property: osd-level=3 -> 1
[statusline] AV: 00:00:03 / 00:03:37 (1%) A-V:  0.000
[cplayer] Run command: cycle-values, flags=8, args=[osd-level, 3, 1]
[cplayer] Set property: osd-level=1 -> 1
[statusline] AV: 00:00:05 / 00:03:37 (2%) A-V:  0.000
[cplayer] Run command: quit, flags=9, args=[0]
[cplayer] EOF code: 6  
[ad] Uninit audio decoder.
[af] Removing filter lavrresample 
[vd] Uninit video.
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Quit)
[ytdl_hook] Exiting...
[osc] Exiting...
[ao/pulse] draining...
[vo/opengl/x11] Enabling screensaver.
[vo/opengl] flushing shader cache
[vo/opengl/x11] uninit ...

### Sample files
Not required. The problem occurs with any video.

**Comment by garoto** [comment]
Fixed in 7dd69ef

**Comment by arschficken** [comment]
Wonderful! Thanks for finding this. I'm marking this ticket closed.
