### ISSUE TITLE
--hdr-compute-peak=yes shows blocky corruption with --dscale=ewa_lanczos

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#6083]
### mpv version and platform
mpv 0.29.0-21-gd2d7dba6ee Windows 10

### Reproduction steps
Play any HDR video downscaled with
dscale=ewa_lanczos
hdr-compute-peak=yes

### Expected behavior
It should work fine.

### Actual behavior
It shows severe blocky corruption:
https://abload.de/img/hdrblockysuifn.png

Happens with D3D11, OpenGL and Vulkan.
Doesn't happen with --hdr-compute-peak=no.
It's obviously related to EWA scalers, as it doesn't occur with --dscale=lanczos either.

### Log file
https://pastebin.com/T7VYNTqd

### Sample files
It occurs with any HDR video.

**Comment by haasn** [comment]
Pretty sure this happens when both passes try enabling compute shaders at the same time, presumably with different block sizes. I'll fix it soon-ish (not today, too hot to think).

**Comment by aufkrawall** [comment]
Sure, no hurry. Thanks for responding in such a timely manner.

**Comment by aufkrawall** [comment]
All good now, thank you.
