### ISSUE TITLE
about "qscale"

### ISSUE THREAD

**Issue by keinth** [mpv-player/mpv#6088]
### mpv version and platform

mpv 0.29
platform win10&win7 

### Actual behavior
encoding 
mpeg4
see the pics
### Log file
![0111](https://user-images.githubusercontent.com/42676817/44591457-5d0e2d80-a7f0-11e8-9c4a-55c95e12a1f9.JPG)
![0112](https://user-images.githubusercontent.com/42676817/44591458-5d0e2d80-a7f0-11e8-991a-8cba4b01c5d5.JPG)
![0113](https://user-images.githubusercontent.com/42676817/44591460-5da6c400-a7f0-11e8-8f1c-fee3380fbad0.JPG)

**Comment by mc4man** [comment]
Seems to have worked in a package i have that's,
mpv git-2018-04-15-c647516
ffmpeg version: git-2018-04-16-3c1ecb0

And broken a couple of weeks later with 
mpv git-2018-04-29-6bd2bdc
ffmpeg version: git-2018-04-29-6e95d80

In between were a bunch of commits for encoding on 04/21 > 04/22, try looking at them first..

https://github.com/mpv-player/mpv/commit/bfc33da250e4fdb6bb57bdf051ad666570ae985f
https://github.com/mpv-player/mpv/commit/6c8362ef54f4e90476553cb6b64996cc414da06d
https://github.com/mpv-player/mpv/commit/05e75e794623754f6e1e77ea20f46629bc71882b

**Comment by olifre** [comment]
The first of those commits appears to have removed support for emulation of `qscale`, so now only the usual approach for library calls works. 
That means the following should be equivalent to `--ovcopts=qscale=5`:
```
--ovcopts=global_quality=5*QP2LAMBDA,flags=+qscale
```
