### ISSUE TITLE
Segmentation fault in audio filter due to array out of bounds

### ISSUE THREAD

**Issue by Tomeeeee** [mpv-player/mpv#6092]
### mpv version and platform

Current master branch (rev 91786fa99c, 8/16/2018) on Windows 7 64-bit,
but the problem started in v0.27.

### Reproduction steps

Play a stereo file on a system with quad speakers (so that an audio filter
is used to map the channels) and seek repeatedly.  The problem is rare, so
I created a LUA script to seek back and forth, and this usually causes the
problem within 10 minutes:

	sign = 1
	mp.add_periodic_timer(0.1, function()
	    mp.command(string.format("seek %d", sign * 20))
	    mp.command(string.format("seek %d", sign * 10))
	    mp.command(string.format("seek %d", sign * 20))
	    sign = -sign
	    end)

### Expected behavior

Play the file

### Actual behavior

Segmentation fault or other crash, typically due to a bad pointer in
av_free()

### Diagnosis

I bisected this problem to revision 3a2d5e68ac from 9/21/2017:

    audio: move libswresample wrapper out of audio filter code

The problem is in the reorder_planes planes routine in the audio filter
(aconverter.c or f_swresample.c).  It calculates the number of planes by
using the number of channels in the channel map, which is four for my test
case:

    if (!mp_aframe_set_chmap(mpa, newmap))
        return false;

    int num_planes = newmap->num;
    uint8_t **planes = mp_aframe_get_data_rw(mpa);
    uint8_t *old_planes[MP_NUM_CHANNELS];

Then it copies the four data pointers from the extended_data array in the
av_frame to the old_planes array, and then back again (since reorder map is
one to one).  However, the av_frame was allocated like this:

    out = mp_aframe_create();
    mp_aframe_config_copy(out, p->pool_fmt);
    if (mp_aframe_pool_allocate(p->out_pool, out, samples) < 0)
        goto error;

mp_aframe_pool_allocate does this:

    int planes = mp_aframe_get_planes(frame);
    ...
    av_frame->extended_data =
        av_mallocz_array(planes, sizeof(av_frame->extended_data[0]));

The problem is that mp_aframe_get_planes returns 1 because the format of
the frame is not planar.

    return af_fmt_is_planar(mp_aframe_get_format(frame))
           ? mp_aframe_get_channels(frame) : 1;

Thus, the extended_data array is only one element long, not four.  The copy
back is overflowing the array bounds and clobbering random memory.  Since
the array is usually being overwritten with its previous contents, this
doesn't cause a problem unless another thread uses the clobbered memory
between the time of the copy out and copy back.  Seeking causes several
threads to be spawned which allocate and free memory, and that tends to
provoke the problem.

**Comment by zc62** [comment]
Seems hard to reproduce, since I have only stereo systems. Anyway, made a PR, which should fix the segfault.

**Comment by Tomeeeee** [comment]
Thank you, that fixes the problem for me, and my test case now passes.

**Comment by zc62** [comment]
Well, probably should wait until the PR gets reviewed and merged, then this issue will get closed automatically on merging. Could you reopen this?

**Comment by zc62** [comment]
Never mind... It now got merged.
