### ISSUE TITLE
Choose audio device (headphones or speakers)

### ISSUE THREAD

**Issue by tobiaslp12** [mpv-player/mpv#6093]
mpv 0.29.0 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.18.102
   libavcodec      58.22.100
   libavformat     58.17.101
   libswscale      5.2.100
   libavfilter     7.26.100
   libswresample   3.2.100
ffmpeg version: 4.1+809.g269daf5985
**Windows 10**

Hello,

i want to know how to choose the audio device if i have for example these two audio devices named by Windows-Sounds:
VB-Audio VoiceMeeter VAIO
High Definition Audio-Device (i know this is not the name to address the speaker but i dont know what is)

So what is the command or config setting in order to change the audio device?

Thanks in advance

Tobias

**Comment by Akemi** [comment]
[--audio-device](https://mpv.io/manual/master/#options-audio-device)

**Comment by tobiaslp12** [comment]
Thank you
