### ISSUE TITLE
feature request: toggle input levels via button

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#6094]
It would be nice if we could switch between different options how to treat source's levels with a hotkey, e.g. "untouched, TV, PC, TV 2x, TV 3x".
This is extremely helpful when a source is wrongly flagged/converted and black looks gray (or vice versa: black crush). Sometimes there are also temporarily wrong levels for a source inside a source etc.

**Comment by Akemi** [comment]
`L cycle-values vf "format=colorlevels=limited" "format=colorlevels=full" ""`

something like this or did i misunderstand something? otherwise a simple script could do that too.

**Comment by aufkrawall** [comment]
Thanks a lot, that's exactly what I wanted.

However, having additional options for expanded TV levels would be nice, which means:
Not Level 16 is defined as black, but 32 or 48. As explained, this can be helpful for some idiotic sources.

**Comment by Akemi** [comment]
then you probably need to play with the ffmpeg [colorlevels](https://ffmpeg.org/ffmpeg-filters.html#colorlevels) filter. if i didn't switch them around i believe this is 'nearly' equivalent to setting the format=colorlevels to limited/full. just replace the min/max values accordingly.

```
botched source crushed blacks/whites (full)
--vf=colorlevels=romin=16/255:gomin=16/255:bomin=16/255:romax=235/255:gomax=235/255:bomax=235/255

botched source too grayish blacks/whites (limited)
--vf=colorlevels=rimin=16/255:gimin=16/255:bimin=16/255:rimax=235/255:gimax=235/255:bimax=235/255
```

**Comment by aufkrawall** [comment]
Should this work ootb? I'm getting this:

`[ffmpeg] Impossible to convert between the formats supported by the filter 'mpv_src_default_in' and the filter 'auto_scaler_0'
[lavfi] failed to configure the filter graph
Disabling filter colorlevels.00 because it has failed.`

**Comment by Akemi** [comment]
it does here at least. i am not sure what the `auto_scaler_0` filter is, a log might help. maybe it's the fault of hwdec if you use it?

**Comment by aufkrawall** [comment]
Yeah, it doesn't seem to work either with nvdec nor d3d11va.
With software decoding, --vf=colorlevels seems unacceptable slow while range conversion should basically be for free.

**Comment by Akemi** [comment]
then you should be able to use the `-copy` hwdecs instead. the filter doesn't seem slow here at all. otherwise a shader could probably do the same and would be a lot faster.

**Comment by aufkrawall** [comment]
The software decoding performance is fine without --vf=colorlevels. Instead, --vf=colorlevels seems to be maxing out just one CPU thread and my 6700k is too slow for this with 4k 60fps content.

So it seems, unlike format=colorlevels=, --vf=colorlevel doesn't run on the GPU.

**Comment by aufkrawall** [comment]
Ok, I didn't know that it could simply be achieved by using tagging (which is a great thing).
But vf=colorlevel unfortunately seems to be entirely impractical if even the single threaded performance of a 6700k isn't enough.

Would it be possible to implement that tagging functionality also for TV levels double/triple extended?
mpc-hc has HLSL shaders for range conversion, if this any helpful:
https://github.com/mpc-hc/mpc-hc/tree/7f14b47cf225102b162d61c9cfa74186e1fe5e80/src/mpc-hc/res/shaders/external

**Comment by Akemi** [comment]
if i am not wrong `limited` and `full` are the only available options for tagging (since they are the only valid cases), so it can't be implemented by that mechanism.

those two shaders should be easily convertible to mpv usable shaders. i might give it a try tomorrow.

**Comment by Akemi** [comment]
full -> limited (reduces range)
```
//!HOOK MAINPRESUB
//!BIND HOOKED

const float min = 16.0 / 255.0;
const float max = (235.0 - 16.0) / 255.0;

vec4 hook()
{
    return (HOOKED_texOff(0) * max) + min;
}
```

limited -> full (expands range)
```
//!HOOK MAINPRESUB
//!BIND HOOKED

const float min = 16.0 / 255.0;
const float max = 255.0 / (235.0 - 16.0);

vec4 hook()
{
    return (HOOKED_texOff(0) - min) * max;
}
```

one could probably also hook into `LUMA` and `CHROMA` separately. though for chroma one should use 240 instead of 235, since the upper limit is 240 there.

as for a keybinding i would probably use something like this. it chains the shader up to two times, if the source's range was really reduced twice.
```
l cycle-values glsl-shaders "" "~~/hooks/level.hook" "~~/hooks/level.hook:~~/hooks/level.hook"
```

otherwise you could also change the `min` and `max` values in the shader itself (if you know the exact upper and lower limit). though keep in mind just using for example 32 as `min` and 215 as `max` is not the same as applying the shader twice.

**Comment by aufkrawall** [comment]
Wow, that's very cool. Thanks a lot!

Hm, unfortunately applying the shader twice either doesn't happen or doesn't lead to the desired result.
When I press the hotkey the first time, OSD reports that the shader was applied and the result confirms this. But when I press the hotkey the 2nd time, it probably seeks for a file "~~/hooks/level.hook:~~/hooks/level.hook" instead of applying it twice, and the result looks like no shader was applied:
https://abload.de/img/2x74e2q.png

**Comment by Akemi** [comment]
try with a `,` or `;` instead of a `:`. i not sure which one was the right one.

**Comment by aufkrawall** [comment]
Yey, a ; does he trick (I should btw. get a read about GitHub text formatting, sorry about that.).

Would it be possible to include these shaders by default, since they are extremely lightweight?

**Comment by Akemi** [comment]
i don't think these two shaders have any chance to get integrated into mpv, but i am not the one who would make that decision.

@jeeb, @haasn what do you think about this?

**Comment by aufkrawall** [comment]
I tested on Linux and there a ":" is needed instead of a ";". Is this difference between platforms intended?

**Comment by Akemi** [comment]
probably because `:` can be part of the path on windows (eg `C:`) but not on on unix/linux. on the other hand `;` can be part of the path on unix/linux but not on windows.

**Comment by aufkrawall** [comment]
Maybe someone finds this a bit interesting: I tested how expensive the level conversion shader is on my painfully slow Atom x5-Z8300 GPU: Well, it's basically for free, increases GPU load by ~3% or so. It apparently didn't disable dumb-mode, which saves an enormous amount of performance with this garbage GPU.
