### ISSUE TITLE
Sometimes backward ~3 seconds hr-seek is too slow (~1-2 seconds). Is it okay?

### ISSUE THREAD

**Issue by kelciour** [mpv-player/mpv#6095]
I'm not sure is it expected behaviour or not, but I often replay previous subtitle and use exact/hr/precise backward ~3-5 seconds seek to do it, but sometimes it takes ~1-2 seconds to complete.

I tried to enable cache for local files but it didn't seem to have any effect in this case. I've attached log.txt with mpv log output and keyframes.txt with keyframe timestamp information from ffprobe.

It seems that either cache contains only keyframes or hr-seek ignores cache and skips to the nearest keyframe and decodes video again to get to the actual frame and that takes time.

This is fast 3 sec. backward hr-seek:

```
[   8.871][d][cplayer] Run command: script-binding, flags=9, args=[seek_test/replay]
[   8.872][d][cplayer] Run command: seek, flags=0, args=[-3.000000, exact, unused]
[   8.872][v][mkv] queuing seek to 53.139000
[   8.872][v][mkv] cached range 0: 47.616000 <-> 356.731000 (bof=0, eof=0)
[   8.872][v][mkv] ...using this range for in-cache seek.
[   8.873][v][mkv] seeking stream 0 (video) to packet 52.594000/-9223372036854775808.000000
[   8.874][v][mkv] seeking stream 1 (audio) to packet 53.120000/-9223372036854775808.000000
[   8.875][d][ao/wasapi] Thread Reset
[   8.875][v][cplayer] hr-seek, skipping to 53.139000
[   8.881][d][ffmpeg/video] h264: Reinit context to 1280x720, pix_fmt: yuv420p
[   8.935][v][vd] Decoder format: 1280x720 [0:1] yuv420p bt.709/auto/auto/limited/auto CL=mpeg2/4/h264 (auto 0.000000/0.000000/0.000000)
[   8.935][v][vd] Using container aspect ratio.
[   9.017][d][cplayer] Run command: script-binding, flags=9, args=[seek_test/replay]
[   9.098][v][cplayer] first video frame after restart shown
[   9.098][v][cplayer] starting audio playback
[   9.098][d][ao/wasapi] Thread Resume
[   9.098][d][ao/wasapi] Thread Reset
[   9.099][v][cplayer] playback restart complete
[   9.134][i][seek_test] 0.233155 
```

0.233155 is how much time took hr-seek to complete
52.594000 is the nearest keyframe from keyframes.txt

This is slow 3 sec. backward hr-seek:
It usually happens when there's a keyframe/scene change between current playback position and position that are 3 seconds earlier.

```
[  18.311][d][cplayer] Run command: script-binding, flags=9, args=[seek_test/replay]
[  18.313][d][cplayer] Run command: seek, flags=0, args=[-3.000000, exact, unused]
[  18.313][v][mkv] queuing seek to 59.354000
[  18.313][v][mkv] cached range 0: 47.616000 <-> 365.323000 (bof=0, eof=0)
[  18.313][v][mkv] ...using this range for in-cache seek.
[  18.314][v][mkv] seeking stream 0 (video) to packet 52.594000/-9223372036854775808.000000
[  18.315][v][mkv] seeking stream 1 (audio) to packet 59.328000/-9223372036854775808.000000
[  18.315][d][ao/wasapi] Thread Reset
[  18.326][v][cplayer] hr-seek, skipping to 59.354000
[  18.332][d][ffmpeg/video] h264: Reinit context to 1280x720, pix_fmt: yuv420p
[  18.388][v][vd] Decoder format: 1280x720 [0:1] yuv420p bt.709/auto/auto/limited/auto CL=mpeg2/4/h264 (auto 0.000000/0.000000/0.000000)
[  18.388][v][vd] Using container aspect ratio.
[  18.454][d][cplayer] Run command: script-binding, flags=9, args=[seek_test/replay]
[  19.338][v][cplayer] first video frame after restart shown
[  19.338][v][cplayer] starting audio playback
[  19.338][d][ao/wasapi] Thread Resume
[  19.338][d][ao/wasapi] Thread Reset
[  19.338][v][cplayer] playback restart complete
[  19.340][i][seek_test] 1.025632 
```

The same packet (52.594000) but skipping is much farther (59.328000) than before (53.139000) and it takes more time (1.025632) than before (0.233155).

### mpv version and platform

mpv 0.29.0 build by lachs0r
Windows 7

### Reproduction steps

I've added these options in mpv.conf but there's no difference in seek time either with or without them.
```
cache=204800
cache-backbuffer=102400
demuxer-max-back-bytes=104857600
```
And I've used this script to print how much time takes backward hr-seek to complete.
```lua
function replay()
    t = mp.get_time()
    mp.commandv("seek", -3, "exact")
end

function on_playback_restart()
    if t ~= nil then
        print(mp.get_time() - t)
    end
end

mp.register_event("playback-restart", on_playback_restart)

mp.add_key_binding("ctrl+f", "replay", replay)
```

### Expected behavior

Backward hr-seek within cache range takes ~0.5 seconds or less.

### Actual behavior

Sometimes backward hr-seek within cache range takes ~1-2 seconds.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/2333744/output.txt)
[keyframes.txt](https://github.com/mpv-player/mpv/files/2333849/keyframes.txt)

**Comment by wm4** [comment]
It's probably fine. The "exact" seeking mode requires decoding video until the target time, which takes a while, depending on the source file. Keyframe seeking mode doesn't have this issue, but may miss the seek target time.
