### ISSUE TITLE
[Lua] observe_property does not work for vf-metadata

### ISSUE THREAD

**Issue by darrenswhite** [mpv-player/mpv#6100]
### mpv version and platform

mpv-x86_64-20180818-git-d2d7dba on Windows 10

### Reproduction steps

Use the sample script provided below. This should observe the lavfi cropdetect y value.

### Expected behavior

The cropdetect filter y value should log when changed.

### Actual behavior

Nothing is logged when the value changes.

### Log file

[Log file](https://0x0.st/stIO.txt)

Line 1452 and 1453 is where the cropdetect y value changes.

### Sample files

[autocrop.lua](https://0x0.st/stIW.lua)

**Comment by wm4** [comment]
This was fixed recently.
