### ISSUE TITLE
Memory leak with lua scripts number >11

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#6101]
### mpv version and platform
Linux lom 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux
mpv 0.29.0

### Reproduction steps
To have more then 11 lua scripts in ~/.config/mpv/scripts/
When I go through playlist one file after another, memory consumption steadily rises with each file.
Completely independent of the actual scripts, if they are just empty files file.lua - same thing.

Edit:
In mpv.conf cache value also has to be set. Doesn't matter whether it's 99 or 99999.
cache=99

### Log file
https://0x0.st/stIw.txt

**Comment by wm4** [comment]
Log file died. Open a new issue if this still happens with mpv master.
