### ISSUE TITLE
Window movement lag on linux while playing videos

### ISSUE THREAD

**Issue by startas** [mpv-player/mpv#6106]
### mpv version and platform
MPV v0.29.0, linux x64, any DE (for example, xfce or cinnamon), ryzen 2700x, nvidia gtx 1080.

### Reproduction steps
Open any local or internet stream video to play and try to move around mpv or any other opened window.

### Expected behavior
While video plays, i should be able to move any window smoothly.

### Actual behavior
Window movement is super laggy, like 5 fps or less.

### Log file
Will provide later.

Also, this is not an issue with intel graphics, only with nvidia.
Also, this issue exists only with mpv program, internet browsers can play videos just fine and there is no window movement lag with them, will try other video players later.

**Comment by heelsleeh** [comment]
1. have you installed proprietary nvidia driver?
2.  about the laggy thing, it's common on gnome-shell with Xorg,  maybe wayland can be better in  the furture, i tested all the DEs, only enlightenment and KDE5 give me the best experience about this problem.

**Comment by startas** [comment]
Yes, i am using proprietary nvidia driver. There was a small update few days ago, gonna try it, but i doubt it fixes anything.
Well, its a bit surprising that so far only this one program makes the lag, but not any other program.

**Comment by aufkrawall** [comment]
Have you tried without compositor?
Proprietary Nvidia driver basically doesn't work well with any compositor but tweaked KWin, and has terrible performance drops when new Xorg windows open in general.

**Comment by Jj0YzL5nvJ** [comment]
I can't reproduce on Xubuntu 16.04.5 LTS x86_64... surprising not even by resizing the window. Even the `mesa-utils` demos drop frames by resizing the window, but not mpv O.o!
https://0x0.st/sv23.txt

 Only 144 FPS videos drop frames by resizing, and are insignificant (4-5 FPS).

 P.S: 8-bit H.265/HEVC videos now works using gpu+vdpau too!!
https://0x0.st/sv2Y.txt

**Comment by startas** [comment]
I updated my linux distro, and the situation improved - the big lag is gone, but window movement is still not very smooth.

**Comment by aufkrawall** [comment]
That's not mpv's fault.

**Comment by lachs0r** [comment]
Yeah. Known NVIDIA problem. Using a compositor may improve things, but in general the driver seems to prioritize OpenGL and Vulkan rendering over *every* other operation, including window management.

**Comment by aufkrawall** [comment]
Well, I can move windows (including mpv during playback, also when using nvdec) completely free of stutter with KWin.

But what really bums me is that scrolling in Firefox becomes choppy when mpv is using nvdec. I notice something similar on Windows with any hwdec. In that regard, my RX 560 worked best on Linux.
