### ISSUE TITLE
jack-port mpv.conf stereo output

### ISSUE THREAD

**Issue by fxkrait** [mpv-player/mpv#6108]
I am trying to make mpv output to two jack ports, which is required for stereo audio.

The only configuration option is jack-port (singular). 
This works, but it only output a left channel.
Working Left Channel EX: `jack-port="Non-Mixer/mpv:in-1"`

in MPD, I can do  `destination_ports "Non-Mixer/mpd:in-1,Non-Mixer/mpd:in-2"` which outputs to a left and right channel.

How do I do such a thing in mpv?

**Comment by bmayton** [comment]
I was looking for the answer to this myself, so I dug into the code to see if it was possible.  The argument of `--jack-port` is passed to `jack_get_ports()` in libjack, which interprets it as a POSIX Extended regular expression and returns the ports that match.  So it's possible to do, for example, `--jack-port="system:playback_(21|22)"`, which results in the left channel getting connected to system:playback_21 and the right channel to system:playback_22.  When multiple ports match, they are connected in the order that they were returned from libjack (so generally in increasing order).

In the past I've accidentally discovered that a substring match works as well, so `--jack-port="Non-Mixer/mpv:in"` might do what you want.

**Comment by fxkrait** [comment]
Dude. Awesome. That works! Thanks @bmayton.

**Comment by fxkrait** [comment]
I was listening to some music, where it was flanging from right to left channel, and in MPV it would just fade in and out, instead of panning to each right/left track. So, I believe the above config command by @bmayton , outputs mono to both right and left channels. Correct me if I'm wrong. I'm playing the same track in mplayer, and I hear the panning effect.

I'll re-open this, so that hopefully a stereo jack port output can be added, or explained.

**Comment by bmayton** [comment]
You can see what JACK connections have been made with `jack_lsp -c`, or a GUI tool that shows JACK connections, such as Patchage, Carla, or qjacktctl.  Is the issue that mpv is patching incorrectly, or that both output ports carry the same mono audio?  Are you sure that you're not inadvertently downmixing to mono later in your signal chain (e.g. if you feed some other known working stereo source into the ports where you're patching mpv, can you confirm that you indeed get stereo?)

If I do:

    mpv -ao jack --jack-port="system:playback_(3|4)" stereo_test.wav

I am definitely getting stereo coming out of channels 3 and 4 of my audio interface.

**Comment by fxkrait** [comment]
Just tried a left-right audio test, I am definitely getting Mono.
Using: jack-port="Non-Mixer/mpv:in"
Catia Routing: https://www.imgpaste.net/image/wjGzX

**Comment by fxkrait** [comment]
Well, I just routed my MPV to those of the MPD, and it gets stereo audio. I guess somethings not configured right with the that mixer channel then. So @bmayton you're right, stereo works on MPV's end. Thanks man.
