### ISSUE TITLE
mpv 0.29 doesn't work on Weston 5.0

### ISSUE THREAD

**Issue by TestMode1** [mpv-player/mpv#6110]
### mpv version and platform

mpv 0.29, Archlinux

mpv compiled with wayland and egl support and without x11 support doesn't work on the latest Weston
Fails with
`[vo/gpu/wayland] Compositor doesn't support the required xdg_wm_base protocol!`

mpv 0.28 with same compilation settings works great

### Expected behavior

For it to work on the reference wayland compositor.

**Comment by ERYuyNIrbNKrsc** [comment]
mpv 0.29.0-29-g48c38f730d  Kubuntu 18.10
when upgraded to Wayland 1.15.0 also stopped working

**Comment by jcowgill** [comment]
This is probably because Weston 5.0 doesn't support stable xdg-shell (which mpv now requires).

**Comment by linkmauve** [comment]
Weston 6.0 will get released on Wednesday, and it supports xdg-shell proper, as do every other Wayland compositors in their current version.
