### ISSUE TITLE
Playing zip files

### ISSUE THREAD

**Issue by rudevdr** [mpv-player/mpv#6114]
MPV is awesome media player. But it doesn't support playing files inside zip or rar directly without uncompressing first. Its very well implemented and works out-of-the-box in VLC Media Player? Is it possible to implement this in MPV?

**Comment by CounterPillow** [comment]
mpv supports this if it is compiled with libarchive support.

**Comment by rudevdr** [comment]
Well then that's awesome. Thanks!
