### ISSUE TITLE
[Request] Show OSC at start

### ISSUE THREAD

**Issue by Nojevah** [mpv-player/mpv#6115]
### mpv version and platform
mpv 0.29.0 (Windows builds by lachs0r)
Windows 10 x64

### Reproduction steps
Double click on some file

### Expected behavior
Display OSC from 1 second (in order to view the total time of video for example)

### Actual behavior
No information at all. I have to move mouse to access information.

So my request would be a setting like "osc-atstart" with value in ms. 0 by default in order not to change actual behavior. And I would use 1000 in my case.

**Comment by garoto** [comment]
`mpv --osd-playing-msg=${duration} file`

https://mpv.io/manual/master/#options-osd-playing-msg

**Comment by avih** [comment]
Save this as `osc-onload.lua` in your scripts dir:
```lua
-- When a new file is loaded -> wait 0.5s, then displays the OSC for 5 seconds
local OSC_SECONDS = 5
mp.add_hook("on_preloaded", 100, function()
    mp.add_timeout(0.5, function()
        mp.command("script-message osc-visibility always no-osd")
        mp.add_timeout(OSC_SECONDS, function()
            mp.command("script-message osc-visibility auto no-osd")
        end)
    end)
end)
```

**Comment by Nojevah** [comment]
Nice ! That's it !

**Comment by fritzrehde** [comment]
Is there an easier way to always show the osc indefinitely when starting a video? I couldn't find anything in the manpage.

**Comment by guidocella** [comment]
`--script-opts-append=osc-visibility=always`
