### ISSUE TITLE
Stuttering problem on Manjaro

### ISSUE THREAD

**Issue by alxpettit** [mpv-player/mpv#6117]
My friend is having trouble with her laptop playing back 1080p videos with MPV. They play alright in VLC, but in MPV there is stuttering and lag.

_uname -a:_ `Linux turqoise 4.14.67-1-MANJARO #1 SMP PREEMPT Fri Aug 24 16:33:26 UTC 2018 x86_64 GNU/Linux`

[Here](https://gist.github.com/alxpettit/c1b94f3eca42e46972aa441497eccef2) is the ffprobe output of file in question (though this problem extends to *many* files -- almost any 1080p video). And [here](https://gist.github.com/alxpettit/e1a4084151f51f51a3ed0a817dd16070) is the MPV log file.

Some potentially relevant software versions on her machine:
```
vlc 3.0.3.r1-2
mpv 1:0.29.0-1 (via 
syncplay 1.5.6.Beta2-1
ffmpeg 1:4.0.2-2
```

**Comment by lachs0r** [comment]
Seems like your GPU is too old/slow to run mpv’s default video output. You can try `--vo=vdpau` or `--vo=xv` instead, both of which have drawbacks but might work better on old machines.

**Comment by alxpettit** [comment]
@lachs0r  The first one caused A/V desync, and the second one caused even worse stuttering... any other ideas?
