### ISSUE TITLE
Crash in g_utf8_validate

### ISSUE THREAD

**Issue by szotsaki** [mpv-player/mpv#6118]
### mpv version and platform
 v0.29.0
 built on Jul 22 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0.2

### Reproduction steps

Start a radio stream which reports "icy-title" (what's currently played) and have an invalid UTF-8 character in there. In my case it was, perhaps, in another encoding.

### Expected behaviour

mpv skips the invalid character.

### Actual behaviour

mpv crashes with the following message:

```
A: 01:09:21 / 01:09:37 (99%) Cache: 16s+498KB
File tags:
 icy-title: NEK - LAURA NON C�

(process:15290): GLib-CRITICAL **: 15:09:02.059: g_variant_new_string: assertion 'g_utf8_validate (string, -1, NULL)' failed
dbus[15290]: arguments to dbus_message_iter_append_basic() were incorrect, assertion "_dbus_check_is_valid_utf8 (*string_p)" failed in file dbus-message.c line 2754.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
```
I also use the [MPRIS plugin](https://github.com/hoyon/mpv-mpris).

**Comment by CounterPillow** [comment]
Looks like a problem in the mpris plugin, as mpv by itself does not use dbus.
