### ISSUE TITLE
Sporadic "[vo/gpu] Dropping unrendered frame" during seeking with "--gpu-context=wayland" switch on kwin_wayland

### ISSUE THREAD

**Issue by Valmar33** [mpv-player/mpv#6123]
### mpv version and platform

MPV 0.29.0 on Arch Linux.

Running Mesa master and LLVM master from AUR.

### Reproduction steps

1. Enable [kde-unstable] and [testing] repos.
2. Install latest `mpv`, along with `kwin`, `xwayland`, etc.
3. Start `kwin_wayland`.
4. Start `konsole`.
5. Play a video file with the `--gpu-context=wayland` switch.
6. Seek randomly throughout the video file with keyboard and mouse.

### Expected behavior

No "[vo/gpu] Dropping unrendered frame" or video output freezing.

### Actual behavior

"[vo/gpu] Dropping unrendered frame" will occur on and off, without rhyme or reason, along with the video output freezing, while audio plays normally. Video output will randomly freeze and unfreeze as you seek.

### Log file

https://paste.kde.org/pbt40jnke

**Comment by Orochimarufan** [comment]
I'm having the same issue except it happens whenever the video is playing, not just when seeking. Everything's fine when it's paused though.

I'm running Arch as well, with: mpv 0.29.1, kwin git (because of xdg_wm_base), plasma 5.14 + kf 5.51, Intel Mesa 18.2.2

**Comment by Dudemanguy911** [comment]
Can anyone confirm if this happens with a newer version of plasma (5.16 or whatever it is now) and mpv git master? I attempted to try it myself but I couldn't even get the compositor to run in tty or nested so I gave up.

**Comment by nrdxp** [comment]
yes its still happening on master mpv, although I am using sway not plasma.

**Comment by Dudemanguy911** [comment]
It definitely shouldn't be happening in sway. You'll get "Dropping unrendered frame" if you switch desktops or something where the mpv window is not visible, but just normal seeking and playback should be fine.

**Comment by nrdxp** [comment]
well I dunno what to tell you, its happening in sway, although only when I am using the youtube-dl feature to play youtube videos from a url. So perhaps it is not exactly the same issue as op but...

 I get a lot of `dropping undrendered frame` messages and the video frequently locks up until I switch workspaces, and then it magically starts again. I'll see if I can run a debug build and find anything useful.

**Comment by Dudemanguy911** [comment]
What are your config file settings? It sounds like to me you are using settings too powerful/intensive for your hardware in which case you would, of course, drop frames.

Switching workspaces isn't a fix. It just stops all rendering so when you switch back, the video appears to run smoothly again. Unless you're saying that switching workspaces magically fixes the problem completely and you never get anymore lock ups/dropped frames again.

**Comment by nrdxp** [comment]
my config is pretty minimal:
```
hwdec=vaapi
vo=gpu
hwdec-codecs=all
gpu-context=waylandvk
gpu-api=vulkan
```

**Comment by Dudemanguy911** [comment]
Have you tried it with `--no-config`? There shouldn't be any issues with the default settings for most video.

You probably shouldn't set `hwdec-codecs` at all. Enabling all of them might be causing something weird to happen. The default for that option should be fine. `hwdec=vaapi` should be OK, but try it without that one set to see if it makes any difference. Another possibility is that your GPU's vulkan drivers are bad and you shouldn't use vulkan at all.

**Comment by nrdxp** [comment]
it *was* the 'hwdec-codecs=all', it was an artifact from a time earlier in my configuration history when mpv wouldn't launch without, forgot it was there. Thank you.

**Comment by Dudemanguy911** [comment]
#7037 got merged which majorly changes how the wayland renderloop works. The "Dropping unrendered frame" behavior doesn't even exist anymore. This doesn't necessarily guarantee you are problem free, but if you have a problem it's going to be something else completely. Closing this. Feel free to open up a new issue if needed.
