### ISSUE TITLE
With "--gpu-api=vulkan", MPV complains that it cannot find SPIRV, despite spirv-tools being installed

### ISSUE THREAD

**Issue by Valmar33** [mpv-player/mpv#6124]
### mpv version and platform

MPV 0.29.0 on Arch Linux.

Running Mesa master and LLVM master from AUR.

### Reproduction steps

1. Install mpv and spirv-tools.
2. Play a video file using the "--gpu-api=vulkan" switch.

### Expected behavior

Detects spirv, and plays video with Vulkan backend. (what binary is it expecting, anyways?)

### Actual behavior

Complains with "[vo/gpu/vulkan] Failed initializing SPIR-V compiler!" for both X11 and Wayland backends

### Log file

https://paste.kde.org/pgufj4akv

**Comment by Valmar33** [comment]
I see... thanks @haasn :)

**Comment by aufkrawall** [comment]
Is shaderc widely available in distribution repos? Would be great if this didn't strip people from using Vulkan in mpv, at least that's the case with Arch Linux. :)

**Comment by haasn** [comment]
Now that shaderc have adopted a SOVERSION and are possibly thinking about fixing their other packaging errors (e.g. vendored libraries, lack of pkg-config, wrong .so name, ...) it might be more likely to see shaderc packaged.

**Comment by laichiaheng** [comment]
> This happens because your mpv is compiled without support for libshaderc, which is the only SPIR-V backend that mpv supports for now (apart from the deprecated nvidia-only `VK_NV_glsl_shader` which we will be dropping support for eventually). To solve the issue you will need to install libshaderc and make sure mpv is built against it.
> 
> Note: It wouldn't be too difficult to support using `glslang` directly instead of `shaderc`. I have already written a C wrapper for glslang for this purpose for a different project; if you want to try merging it to mpv I could offer some pointers. That said, using shaderc is still preferred to glslang since it means you (i.e. we) get better diagnostics.
How to do it by using the mpv-build.git in Ubuntu?

**Comment by baryluk** [comment]
No shaderc in Debian or Ubuntu yet. There was a plan to do it, but currently it looks nobody is working on it - : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890472

If there is some other well known user of shaderc, maybe that would provide a better motivation to expedite the packaging of shaderc into Debian.

Other than that, you can build it yourself from shaderc git repo.
