### ISSUE TITLE
Can´t compile in Manjaro

### ISSUE THREAD

**Issue by RBNXI** [mpv-player/mpv#6125]
Hi, I tried to compile mpv with vapoursynth in Manjaro, but in the AUR repositories the package don´t works, anyone can tell me how to compile it with the git release and vapoursynth activated?. I have seen any forums that only says "install app repositorie or from AUR", but nothing works in Manjaro, explain me how to do it please.

**Comment by Jj0YzL5nvJ** [comment]
First, make `vspipe -v` work...
In my case, I have use `sudo ldconfig` after install VapourSynth and declare "PYTHONPATH" on the user. Example:

Puting `export PYTHONPATH=/usr/local/lib/python3.5/site-packages` on `.bashrc`.

**Comment by laichiaheng** [comment]
Try the `mpv-build-git` in AUR

**Comment by RBNXI** [comment]
> Try the `mpv-build-git` in AUR
> Just do `yaourt -S mpv-build-git`

Solved it, thank you.
