### ISSUE TITLE
MPV on windows playing from a named pipe

### ISSUE THREAD

**Issue by mannis17** [mpv-player/mpv#6131]
No matter what I do I cannot get MPV to play a stream from a named pipe on windows

> mpv.exe \\.\pipe\test.ts

> [file] cannot open filoe '\\pipe\test5.ts' : Resource tenmporarily unavailable
> Failed to open \\pipe\test5.ts

> Exiting.... (Errors when loading file)

 \\\pipe\test.ts is being created by another program. I see the request to connect to the named pipe arrive and but before it starts to write to the pipe MPV throws the error above.

Of note is that this works in mPlayer

Any help would be appreciated

**Comment by Jj0YzL5nvJ** [comment]
Try with:
mpv "\.\pipe\test.ts"
mpv \\.\\pipe\\test.ts
mpv /\./\pipe/\test.ts
mpv ^\.^\pipe^\test.ts

**Comment by mannis17** [comment]
None of those worked BUT this worked:

mpv file://\\pipe\test5.ts

**Comment by bitingsock** [comment]
I am experiencing this problem. My only other lead is this streamlink issue from 2.5 years ago https://github.com/streamlink/streamlink/pull/739
has any one attempted to use named pipes on windows since closing the issue here?

**Comment by beardypig** [comment]
I know I'm necro-posting, but `file://\\.\pipe\pipename` is what worked for me.
