### ISSUE TITLE
Please provide a key to toggle scaletempo while playing

### ISSUE THREAD

**Issue by joshtriplett** [mpv-player/mpv#6132]
### mpv version and platform

```
~$ mpv --version
mpv 0.29.0 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0.2-1+b1
```

Most of the time, I speed up videos with the default pitch correction enabled, which works very well (thank you for that!). Occasionally, however, when playing back a video, I need to change the video speed *without* pitch correction, most commonly because whoever made the video did some video editing and sped up or slowed down part of the video (without pitch correction) and I want to be able to understand what they said.

I currently do this by noting where I am in the video, re-launching mpv with `--audio-pitch-correction=no` and a seek option, listening, and then doing the same again minus that option to re-enable pitch correction for the remainder of the video.

Could you please provide a key that toggles the scaletempo filter off and on while playing back a video? That would make this far easier, without having to relaunch and seek.

Thank you.

**Comment by haasn** [comment]
You can make such a keybinding yourself, e.g. `x cycle audio-pitch-correction`. Now pressing `x` during playback will toggle audio pitch correction or of off.

**Comment by joshtriplett** [comment]
Ah, I didn't know about `cycle`, thanks!

That solved 90% of the problem. I did find that even after toggling audio-pitch-correction, that setting didn't take effect until I modified the playback rate again. However, I managed to fix that with the following `~/.config/mpv/input.conf`:

`\ cycle audio-pitch-correction ; add speed 0`

That solves the problem perfectly, thank you.

This seems like a sufficiently obscure use case that I'm not going to suggest this become a default keybinding. I appreciate you pointing me in the right direction!

**Comment by haasn** [comment]
FWIW it works for me without the `add speed 0`.

**Comment by joshtriplett** [comment]
@haasn Interesting. If you change the playback rate (hit `]` a few times), then toggle audio-pitch-correction off, does the pitch immediately become un-corrected? For me, it stayed corrected until I changed the playback rate.

**Comment by haasn** [comment]
> @haasn Interesting. If you change the playback rate (hit ] a few times), then toggle audio-pitch-correction off, does the pitch immediately become un-corrected? 

Yes, that's what I meant.

**Comment by joshtriplett** [comment]
@haasn Strange. Any idea what might be different that would cause that to not work here? (Happy to dig for more information if you have an idea of where to start.)
