### ISSUE TITLE
High CPU Usage with deinterlace enabled on Intel 620 hardware

### ISSUE THREAD

**Issue by denny09** [mpv-player/mpv#6133]
### mpv version and platform
mpv 0.29 on Windows 10 x64bit 

### Reproduction steps
enabling in mpv.conf  
deinterlace=yes 

Watch 1080i h264 video and on lower end hardware i7-7200u  the CPU usages spikes up on high motion scenes and it struggles in fast moving scenes. 

### Expected behavior
1080i h264 video to play smoothly 

### Actual behavior
The video is not playing smoothly and it  is dropping frames. When I look at the cpu usage it goes over 50% and that is when you can see pauses and dropped frames. Even with deinterlacing disabled the cpu usage is close to 20% on HD videos.  So something is not clearly right with mpv on intel hardware I am using the latest intel drivers windows updates but it has persisted for a long time now that I can't use mpv with interlaced content.   Using vlc and wmc the cpu usage is very low under 10% with deinterlaced content.

### Log file

https://pastebin.com/gf2vBs5V

[mpvlog.txt](https://github.com/mpv-player/mpv/files/2390940/mpvlog.txt)

### Sample files

https://1drv.ms/v/s!Ap2CKhsbDnkAgYQALKSW3-J_zXvOkw

Thank you

**Comment by superlbr** [comment]
same, i5 with Intel Iris Plus Graphics 650. while quicktime player less than 18% cpu usage.

**Comment by Akemi** [comment]
if this is still the case please open a new issue.
