### ISSUE TITLE
Video crashes after some seconds of playback

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#6134]
### mpv version and platform

The latest build as of now, "2018-07-31". Windows 8.

### Reproduction steps

Play the video.

### Expected behavior

Plays the video to the end.

### Actual behavior

"mpv has stopped working" after 3 seconds of playback.

### Log file

Something odd is that a few times while I opened it from cmd, it played fine, past the 3 seconds (and presumably until the end, had I left it playing).

This is from mpv -v:

Playing: C:\Users\James\Video\Hollis Frampton\The Death of Magellan - Gloria!\The Death of Magellan - Gloria!.mkv
 (+) Video --vid=1 (*) 'x264 | 9596 Kbps | 23.976 fps | 1.33:1' (h264 1440x108023.976fps)
 (+) Audio --aid=1 --alang=eng (*) 'DTS | 768 Kbps | 24 bits | 48 KHz | mono' (dts 1ch 48000Hz)
File tags:
 Title: The Death of Magellan: Day YYY: 3 Jan: Gloria! 1979 - Criterion Blu-ray
AO: [wasapi] 44100Hz stereo 2ch float
VO: [gpu] 1440x1080 yuv420p
AV: 00:00:03 / 00:09:40 (0%) A-V:  0.000
[autodeint] interlaced with bff field dominance: setting deinterlace property
AV: 00:00:04 / 00:09:40 (0%) A-V:  0.000
[ao/wasapi] Under-run: Device delay: -0.1 us

This is from Windows's crash screen:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	mpv.exe
  Application Version:	2.0.0.0
  Application Timestamp:	00000000
  Fault Module Name:	mpv.exe
  Fault Module Version:	2.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	00000000023b9620
  OS Version:	6.2.9200.2.0.0.256.48
  Locale ID:	2057
  Additional Information 1:	9c42
  Additional Information 2:	9c427d2c2a036b8838f2cf3d7b9d9c27
  Additional Information 3:	494e
  Additional Information 4:	494e1e91d5f0dab8d851de2ba2813b08

### Sample files

https://mega.nz/#!HUNkTaJS!UnTFQW-Usav2dSyZtLoPmXg1dT6CJeLzOcxxB-w9IUA

**Comment by garoto** [comment]
Try `mpv --no-config <file>`

**Comment by firewater2** [comment]
Indeed it works if I do that. Here's my mpv.conf:

# Window
title="${filename/no-ext}"
fullscreen
no-osc
keep-open=always

# Playback
#profile=gpu-hq
#scale=ewa_lanczossharp
#cscale=ewa_lanczossoft
#interpolation
#tscale=linear
#video-sync=display-resample
#glsl-shader="~~/FineSharp.glsl"
audio-file-auto=all

# Subtitle
slang=en
sub-file-paths=srt:ass:sub:subs:subtitles
no-sub
demuxer-mkv-subtitle-preroll
sub-ass-override=force
sub-auto=all
sub-pos=90
sub-font-size=54
sub-border-size=2
sub-border-color="#000000"
sub-font="Helvetica"
sub-shadow-offset=0
sub-shadow-color="#33000000"
sub-color="#dadada"

# OSD
osd-font="Helvetica"
osd-color="#dadada"
osd-font-size=54
osd-border-size=2
osd-align-x=center
osd-margin-y=105
osd-shadow-offset=0
osd-shadow-color="#33000000"
osd-bar-w=50
osd-bar-h=3
osd-bar-align-y=0

# Miscellaneous
screenshot-format=jpeg
screenshot-jpeg-quality=100
screenshot-template="%F %P"
screenshot-directory="C:/Users/James/Unorganized/Unorganized/Reference/"
no-input-default-bindings
use-filedir-conf
cursor-autohide=always

**Comment by garoto** [comment]
I think it might be the fault of the `autodeint` Lua script. Try removing it and test again.

**Comment by Akemi** [comment]
no reply. please open a new issue if the issue still persists.
