### ISSUE TITLE
Refresh youtube-dl source link if timed out

### ISSUE THREAD

**Issue by Nealefelaen** [mpv-player/mpv#6138]
### mpv version and platform

mpv 0.29.0 - arch linux

### Reproduction steps
Play any youtube video (that is long enough to not fit in cache all at once)
Pause the video
Leave it for several hours (for the streaming link to expire)
Play the rest of the video

### Expected behavior
The video plays through to the finish, reconnecting ( and/or re-running youtube-dl) if required.

### Actual behavior
The video plays out the cache, but doesn't finish (due to the streaming link changing).

### Log file
[ffmpeg] tls: Error in the pull function.
[ffmpeg] https: Will reconnect at 784433857 in 0 second(s), error=Input/output error.
[ffmpeg] https: HTTP error 403 Forbidden
[ffmpeg] tls: The specified session has been invalidated for some reason.

**Comment by aufkrawall** [comment]
Thanks for reporting this, I always wondered what was causing it. Imho this is a real convenience killer.

**Comment by arza-zara** [comment]
See ffmpeg issue [#6423](https://trac.ffmpeg.org/ticket/6423).

**Comment by aufkrawall** [comment]
It seems this is fixed. Can you confirm @Nealefelaen ?

**Comment by Nealefelaen** [comment]
I just left a video for 24+ hours and then it played through past the end of the buffer. So it looks fixed from the one test I've done, yes.
