### ISSUE TITLE
Is script comparison operator broken?

### ISSUE THREAD

**Issue by brachna** [mpv-player/mpv#6143]
### mpv version and platform

Latest shinchiro build: mpv-x86_64-20180916-git-6eb59fe.7z
Windows 8.1 64bit

### Reproduction steps

1. Write following JavaScript file:
```

var timestamp_array = [];

function add_timestamp_to_array( time ){
    var log_text = "array.length: " + timestamp_array.length.toString();

    if ( timestamp_array.length > 0 ){
        log_text = log_text + "\ntimestamp: " + time.toString() + "\narray[-1]: " + timestamp_array[timestamp_array.length-1].toString();
    }
    else {
        log_text = log_text + "\ntimestamp: " + time.toString();
    }

    if ( timestamp_array.length == 0 ){
        log_text = log_text + "\nadd first timestamp";
        timestamp_array.push( time );
        mp.osd_message( log_text, 5.0 );
        return;
    }
    else if ( time > timestamp_array[timestamp_array.length-1] ){
        log_text = log_text + "\ntime > array[-1], push new timestamp";
        timestamp_array.push( time );
        mp.osd_message( log_text, 5.0 );
        return;
    }
    else {
        log_text = log_text + "\ntime < array[-1], skipped";
        mp.osd_message( log_text, 5.0 );
        return;
    }
}

function get_current_timestamp(){
    var time = mp.get_property( "time-pos" );
    add_timestamp_to_array( time );
}

mp.add_key_binding( "y", "something", get_current_timestamp );
```
2. Register it.
3. Open any video file.
4. Press 'y' to add first timestamp, then skip further, press again, repeat...

### Expected behavior

Since further captured timestamp is always bigger than last captured one, operator '>' should recognize that and execute underlying block which will push new timestamp into an array.
So ( 1734.0 > 687.0 ) should always be true.

### Actual behavior

Instead operator '>' behavior seems to be random.
Expression like (1734.0 > 687.0) can evaluate to false.

### Log file

[output.zip](https://github.com/mpv-player/mpv/files/2405223/output.zip)

### Sample files

Happens with every video file I tried.

PS. I rewrote script into Lua and it has exact same behavior.

**Comment by avih** [comment]
> var time = mp.get_property( "time-pos" );

`mp.get_property` returns a string, therefore you're pushing strings into your array, and later compare strings. As strings, `( "1734.0" > "687.0" )` is indeed false.

Either use `mp.get_property_native` to read it as a native value (number for the `time-pos` property), or convert it to a number yourself.

Also note that the value of the `time-pos` property is not always numeric, e.g. before any file is playing it still doesn't have a value.

**Comment by brachna** [comment]
Wow, sorry, didn't know that.
Thanks for explanation!
