### ISSUE TITLE
mpv 0.29 - No video output on 4k video on Raspbian Stretch Lite

### ISSUE THREAD

**Issue by Galvo87** [mpv-player/mpv#6144]
### Reproduction steps
Playing a .mkv x264 UHD 4k video shows no output on screen.
Same file resized to FullHD plays smooth as butter.

### Expected behavior
Expecting the video to play fine, while dropping some frames.

### Actual behavior
No video output, even when using --no-config

### Log file
`Playing: uhd-4k.mkv
 (+) Video --vid=1 (*) (h264 3840x2160 25.000fps)
 (+) Audio --aid=1 --alang=eng (*) 'Stereo' (aac 2ch 48000Hz)
Using hardware decoding (mmal).
AO: [alsa] 48000Hz stereo 2ch float
VO: [rpi] 3840x2160 mmal
[vo/rpi] Could not create EGL surface!
[vo/rpi] EGL/GLES initialization for OSD renderer failed.
Could not initialize video chain.
Video: no video
A: 00:00:01 / 00:12:14 (0%)`

Playing the same file with ffplay gives this output:
`
ffplay version 4.0.2 Copyright (c) 2003-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --prefix=/usr --enable-gpl --enable-nonfree --enable-static --enable-libtheora --enable-libvorbis --enable-omx --enable-omx-rpi --enable-mmal --enable-libxcb --enable-libfreetype --enable-libass --enable-gnutls --disable-opencl --enable-libcdio --enable-libbluray --extra-cflags='-march=armv8-a+crc -mfpu=neon-fp-armv8 -mtune=cortex-a53' --enable-libx264 --enable-libfdk-aac --enable-libmp3lame
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Could not initialize SDL - No available video device
(Did you set the DISPLAY variable?)`

**Comment by CounterPillow** [comment]
give us a full log with `--log-file=yourloghere.txt`

I'm pretty sure the problem is that the rpi's shitty GPU simply isn't able to allocate a buffer this large for the OSD.

**Comment by lachs0r** [comment]
Can’t believe you’re even trying to do this with that piece of junk.

You didn’t ask for my financial advice but folks, stop buying Raspberry Pis, it’s a complete waste of resources. If you absolutely have to waste money on a shitty ARM board, make sure it’s at *least* as good as the Tinker Board.

**Comment by lachs0r** [comment]
Also, make sure you have enough RAM allocated to the GPU. See https://www.raspberrypi.org/documentation/configuration/config-txt/memory.md
