### ISSUE TITLE
MPV V0.29 can't play JPEG2000 mxf file smoothly

### ISSUE THREAD

**Issue by sylar88889** [mpv-player/mpv#6154]
### mpv version and platform
MPV V0.29
Mac OS 10.13.6 
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Expected behavior
play J2k mxf file smoothly
### Actual behavior

info about the file . codec :JPEG2000, wrapper :MXF, resolution :HD, frame rate :25p
MPV player can decode the file . but can not play it smoothly 

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Akemi** [comment]
without a log and a sample file no one will look at this.

**Comment by lachs0r** [comment]
MXF/DCP is the most vile garbage I’ve ever seen and JPEG2000 is just very slow to decode in software. I’m not aware of any effort to further optimize FFmpeg’s decoder, so you’ll have to get a (much) faster CPU if you want to play these files with mpv.

**Comment by sylar88889** [comment]
Thanks for your info Martin




| |
Sylar Ma
邮箱：mmzsh126@126.com
|

Signature is customized by Netease Mail Master

On 10/01/2018 08:30, Martin Herkt wrote:

MXF/DCP is the most vile garbage I’ve ever seen and JPEG2000 is just very slow to decode in software. I’m not aware of any effort to further optimize FFmpeg’s decoder, so you’ll have to get a (much) faster CPU if you want to play these files with mpv.
