### ISSUE TITLE
[feature] Specify youtube-dl binary location

### ISSUE THREAD

**Issue by Tajnymag** [mpv-player/mpv#6155]
### mpv version and platform
0.23.0 Raspbian Stretch

### Reproduction steps
* uninstall system-wide youtube-dl
* put youtube-dl binary in .local/bin/
* load .local/bin into PATH in Bash
* try to play any youtube url through mpv without

\# or
* install using "pip install --user youtube-dl"

### Expected behavior
mpv successfully finds youtube-dl and starts playing the video/audio from youtube

### Actual behavior
mpv throws:
```
[ytdl_hook] youtube-dl failed, trying to play URL directly ... 
[ffmpeg] tls: The TLS connection was non-properly terminated.
Failed to recognize file format.
```

### Suggested solution
enable user to specify youtube-dl location in mpv.conf

**Comment by pink-mist** [comment]
mpv does look in the PATH for youtube-dl. However, 0.23.0 is so incredibly ancient that it cannot make use of recent versions of youtube-dl, hence why the hook fails. Upgrade mpv and it'll work. Downgrade youtube-dl A LOT and it will work.

**Comment by Tajnymag** [comment]
Ah, my bad then. Thank you
