### ISSUE TITLE
[Feature Request] Seek next 'chapter or file' (as alternative to add chapter 1/-1 or playlist-next/prev)

### ISSUE THREAD

**Issue by Rabcor** [mpv-player/mpv#6157]
When you keybind something to seek next chapter, if the file has no chapters you just get a prompt that says:

> Chapter: unavailable

It would be preferable if it would just seek to the next file instead, or at least if there was an option for such a command for example something like 'seek next' and 'seek prev' which would seek the next chapter or if no chapter is available, next file, and the reverse for seek prev.

**Comment by paulguy** [comment]
I'd like this to be an option if it were to be implemented.  I have a combination of videos with and without chapters which some I use to skip openings and i frequently mix up which ones do and don't have them and it'd be quite annoying to skip whole episodes of things by accident.

**Comment by Argon-** [comment]
There's a script for that https://gist.github.com/Hakkin/4f978a5c87c31f7fe3ae
This is properly listed among the other user scripts.

**Comment by vitormathews** [comment]
> There's a script for that https://gist.github.com/Hakkin/4f978a5c87c31f7fe3ae This is properly listed among the other user scripts.

How to make the script works for files with no chapters as well?
