### ISSUE TITLE
Enabling mute while paused and then unpausing causes audio output

### ISSUE THREAD

**Issue by afcady** [mpv-player/mpv#6159]
### mpv version and platform

    mpv 0.23.0 (C) 2000-2016 mpv/MPlayer/mplayer2 projects
     built on UNKNOWN
    ffmpeg library versions:
       libavutil       55.34.101
       libavcodec      57.64.101
       libavformat     57.56.101
       libswscale      4.2.100
       libavfilter     6.65.100
       libswresample   2.3.100
    ffmpeg version: 3.2.12-1~deb9u1

    Linux fifty 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux

### Reproduction steps

1. Play a video, e.g. run `mpv video.mp4`

2. Press `space` to pause

3. Press `m` to mute

4. Press `space` to unpause

### Expected behavior

No audio is output.

### Actual behavior

A fraction of a second of audio is output.

**Comment by Akemi** [comment]
update your mpv, 0.23 is was too old to be supported.

**Comment by MarkShuttlecock** [comment]
It's only 2 years old, I've eaten yogurt older than that. Granted it grew a bit of a fur, but so did my cat and I ate that one too.

**Comment by afcady** [comment]
But is the bug actually fixed in a newer version?   I don't need support, just trying to help out `mpv` by reporting the observation.

**Comment by afcady** [comment]
I'm just using the version of mpv in Debian stable, by the way.  I'm not going to compile mpv to verify whether the bug exists in the latest source but someone who already has a compiled mpv of that version can check whether the bug still exists very quickly.
