### ISSUE TITLE
mpv shouldn't honor italics styling in mp4 files

### ISSUE THREAD

**Issue by YamashitaRen** [mpv-player/mpv#6160]
### mpv version and platform
```
$ mpv --version
mpv 0.29.0-35-g9c184078a6 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Thu Sep 27 16:00:46 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: n4.0.2
```
OS : Archlinux x86_64

### Reproduction steps
1) Download Big Buck Bunny : http://download.blender.org/peach/bigbuckbunny_movies/
2) Here's a subtitle for the movie :
```
1
00:00:00,000 --> 00:05:00,000
[Dramatic music throughout but no speaking] 

2
00:05:00,000 --> 00:10:00,000
<i>[Dramatic music throughout but no speaking]</i>
```
3) Mux them in a mp4 using ffmpeg or a tool of your choice : 
`ffmpeg -i big_buck_bunny_480p_h264.mov -i big_buck_bunny_480p_h264.srt -map 0:0 -map 0:1 -map 1:0 -c: copy -c:s mov_text big_buck_bunny_480p_h264.mp4`
4) Play the resulting mp4 in mpv

### Expected behavior
Subtitles should honor my mpv.conf preferences. Italics subtitles included.

### Actual behavior
Subtitles honor my mpv.conf preferences the 5 first minutes. The 5 next minutes, they use a different style for italics subtitles.
VLC doesn't have this issue.

### Log file
Relevant part of the log file :
```
[sub/ass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, DejaVuSans
[sub/ass] fontselect: (sans-serif, 400, 100) -> /usr/share/fonts/TTF/DejaVuSans-Oblique.ttf, 0, DejaVuSans-Oblique
[sub/ass] fontselect: (Serif, 400, 100) -> /usr/share/fonts/TTF/DejaVuSerif-Italic.ttf, 0, DejaVuSerif-Italic
```

Here's what I get with another file I "found" on internet : 
```
[sub/ass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, DejaVuSans
[sub/ass] fontselect: (sans-serif, 400, 100) -> /usr/share/fonts/TTF/DejaVuSans-Oblique.ttf, 0, DejaVuSans-Oblique
[sub/ass] fontselect: (Arial, 400, 100) -> /usr/share/fonts/WindowsFonts/ariali.ttf, 0, Arial-ItalicMT
```
Nice Arial : https://pix.louiz.org/o/sMHgl.png
Should have looked like the next subtitle (but in italics) instead : https://pix.louiz.org/o/WqCEL.png

**Comment by CounterPillow** [comment]
And what are your mpv.conf preferences?

**Comment by YamashitaRen** [comment]
Nothing out of the ordinary.
http://ix.io/1nIQ

**Comment by YamashitaRen** [comment]
Another example, this time on the movie "The Game" : 
https://pix.louiz.org/o/AEaQh.png

**Comment by haasn** [comment]
Sounds like a libass issue to be honest. I don't think anything in mpv would suddenly "forget" to set options just because of some italics tags in the text. (mpv doesn't even look at the subtitle text)

But I could be wrong

**Comment by haasn** [comment]
Also, I can't reproduce. Works fine for me - displays exactly the same for both, including all styling. (Using your exact config)

**Comment by haasn** [comment]
Never mind, I can reproduce. Happens only when the sub format is exactly `mov_text`, doesn't happen for more common formats like subrip / srt. Also, `--sub-italic` still doesn't break it - only the `<i>` tag does.

Most likely libass issue.

**Comment by haasn** [comment]
Turns out it's an ffmpeg issue, you can confirm just having ffmpeg transcode the mov_text subtitle to ass generates a line like this:

```
Dialogue: 0,0:01:00.00,0:03:00.00,Default,,0,0,0,,{\i1}{\fs18}{\fnSerif}[Dramatic music throughout but no speaking]
```

Doing the same for srt yields:
```
Dialogue: 0,0:01:00.00,0:03:00.00,Default,,0,0,0,,{\i1}[Dramatic music throughout but no speaking]{\i0}
```
