### ISSUE TITLE
save playlist position on quit

### ISSUE THREAD

**Issue by aeosynth** [mpv-player/mpv#6164]
Hi, there is `save-position-on-quit` to save your position in a single file; I'd like a similar option eg `save-playlist-position-on-quit` which, naturally, saves your position in the playlist.

while searching the issues i found an implementation idea:

https://github.com/mpv-player/mpv/issues/2045#issuecomment-150624487

> Maybe playlists should be treated like one long concatenated video, with a single position

**Comment by haasn** [comment]
mpv will already restore your position in the playlist if there exists a watch_later config for any file in the playlist. So this feature request is not needed to solve the problem you seem to be describing.

The comment you linked is talking about something very different.

**Comment by orbea** [comment]
This feature works fine for me, I just press `shift+q` and it starts where I left off next time I play the playlist file.

**Comment by aeosynth** [comment]
oh, i didn't know that's what watch later meant
