### ISSUE TITLE
Color Issues 

### ISSUE THREAD

**Issue by mrttrance** [mpv-player/mpv#6175]
I've got a UHD.mkv file I wanted to watch. I usually use the MPC-HC Player, but this time, it showed me very pale colors, i knew these colors could not be right.
So I downloaded MPV, and well, the picture was amazing! The only thing i noticed is dynamic contrast/gamma auto-adjusting. I found the command (hdr-compute-peak), and set it to "no".
The result was, that it fixed the dynamic auto-adjust, but it gave me less greater colors, but still better than MPC-HC. The Thing I don't understand is, that Windows 10 new Movie Player App, shows the best colors. Unfortunately, it can't play the audio, and video stops also after couple of minutes. 

I attached a comparison screenshot, so you can see clearly what I mean. 
Bottom-Left: MPC-HC
Bottom-Right: MPV
Above: Windows 10 MP

I'm using latest release.

![howissthispossible](https://user-images.githubusercontent.com/43733532/46264234-7d7d8600-c51a-11e8-8fee-13b45170c23f.png)

**Comment by haasn** [comment]
Log? Sample file?
