### ISSUE TITLE
Mpv volume is less than normal volume

### ISSUE THREAD

**Issue by 422658476** [mpv-player/mpv#6177]
Hi, I am the author of MPV-EASY Player, MPV-EASY Player is an mpv based player，my project page is:

https://github.com/422658476/MPV-EASY-Player

Recently when I was testing MPV-EASY Player, I found that when the volume is adjusted below 100%, the set volume will be much smaller than the actual volume.When the volume is 100%, the volume is normal.

For example, when you adjust the volume to 50%, the volume you hear is estimated to be only 30%. When you adjust the volume to 30%, the sound is too small to hear.

At first I thought it was caused by some settings added by MPV-EASY Player, but when I played the video directly using mpv (without using any configuration files, all default states), the problem remains the same.

And use mpv to play any video. When you adjust the volume between 100% and 50%, you can obviously feel the volume change, and the volume is very small when the volume is 50%.

When the volume is adjusted between 50% and 0%, there is basically only a small change, basically a very small sound.

I used to do a test using the video on the video site. When playing video directly in the browser and using 50% volume, the sound is still very loud, but when you download this video to the local, use mpv to play, the volume is adjusted to At 50%, the volume emitted by mpv after comparison is much smaller.

I don't know if this is a common phenomenon. If you use it as well, does this mean a bug, of course I am not sure if this is a bug, or this is a bug in the volume adjustment algorithm.

**Comment by Argon-** [comment]
Afaik mpv is not using a linear volume control. However, this is on purpose: https://www.dr-lex.be/info-stuff/volumecontrols.html
Many programs use a linear volume control which is in theory wrong. But maybe people are used to it.

**Comment by 422658476** [comment]
It turned out to be the case, thank you very much for your answer. This made me grow my knowledge again and I am very grateful.
