### ISSUE TITLE
Error with streaming bandcamp [ffmpeg] tls: Creating security context failed (0x80090302)

### ISSUE THREAD

**Issue by Shaaah** [mpv-player/mpv#6178]
### mpv version and platform

mpv 0.29.1
With this build : https://mpv.srsfckn.biz/
On Windows 7 x64

### Reproduction steps

mpv https://furi.bandcamp.com/

### Expected behavior

No tls error and streaming audio.
This error is somewhat surprising, I don't get any problems when I try to download the album with youtube-dl.

### Actual behavior

$mpv https://furi.bandcamp.com/                            
Playing: https://furi.bandcamp.com/                        
                                                           
Playing: https://furi.bandcamp.com/track/time-to-wake-up
[ffmpeg] tls: Creating security context failed (0x80090302)
Failed to open https://t4.bcbits.com/stream/138624ab722f683490c644557b677d32/mp3-128/177410958?p=0&ts=1538606915&t=f80a37ae80b05cdcafa9bf1a8f14c861ca1a8a04&token=1538606915_8609243746c43b370173d19338de2d900d5dc370.         

### Log file

https://pastebin.com/vmw4Zczk

**Comment by Dudemanguy** [comment]
Very old so it may not even occur anymore and not really an mpv issue.
