### ISSUE TITLE
There is caching (buffering) despite --no-cache

### ISSUE THREAD

**Issue by roderick1980** [mpv-player/mpv#6179]
### mpv version and platform
mpv 0.29.0-30-g6eb59fe Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Sep 11 17:26:50 UTC 2018
ffmpeg library versions:
   libavutil       56.19.101
   libavcodec      58.29.100
   libavformat     58.18.100
   libswscale      5.2.100
   libavfilter     7.29.100
   libswresample   3.2.100
ffmpeg version: N-91874-g44ee858

### Reproduction steps
DISPLAY=:0.0 mpv --vo=vdpau --hwdec=vdpau --hwdec-codecs=all --hwdec-image-format=yuv420p --no-audio --no-cache --cache=no --cache-default=no --framedrop=vo --speed=50 --rtsp-transport=udp --no-config --profile=low-latency --fs rtsp://xxxx:yyyy@x.y.z.k:554/media/video3

### Expected behavior
(A value of 0 for cache)
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:54 / 00:00:54 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:55 / 00:00:55 (99%) x50.00 Cache:  0s
V: 00:00:56 / 00:00:56 (99%) x50.00 Cache:  0s
V: 00:00:56 / 00:00:56 (99%) x50.00 Cache:  0s
V: 00:00:56 / 00:00:56 (99%) x50.00 Cache:  0s
V: 00:00:56 / 00:00:56 (99%) x50.00 Cache:  0s
V: 00:00:56 / 00:00:56 (99%) x50.00 Cache:  0s

### Actual behavior
(A value different from 0 for cache)
V: 00:00:54 / 00:00:54 (100%) x50.00 Cache:  1s+99KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+97KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+95KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+93KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+91KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+89KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+87KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+85KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+83KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+102KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+100KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+98KB
V: 00:00:54 / 00:00:56 (97%) x50.00 Cache:  1s+96KB
V: 00:00:54 / 00:00:56 (98%) x50.00 Cache:  1s+94KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  1s+92KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  1s+70KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+68KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+66KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+67KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+65KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+63KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+60KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+59KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+56KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+54KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+52KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+50KB
V: 00:00:55 / 00:00:56 (98%) x50.00 Cache:  0s+48KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+46KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+46KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+44KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+42KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+40KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+38KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+36KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+34KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+32KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+30KB
V: 00:00:55 / 00:00:56 (99%) x50.00 Cache:  0s+28KB
V: 00:00:56 / 00:00:56 (99%) x50.00 Cache:  0s+28KB
V: 00:00:56 / 00:00:56 (99%) x50.00 Cache:  0s+6KB
V: 00:00:56 / 00:00:56 (99%) x50.00 Cache:  0s+4KB
V: 00:00:56 / 00:00:56 (99%) x50.00 Cache:  0s+2KB
V: 00:00:56 / 00:00:56 (99%) x50.00 Cache:  0s

**Comment by rgaufman** [comment]
Any solution to this? - I'm getting the same

**Comment by wm4** [comment]
> --speed=50 

Well, obviously it'll get behind real time, so the leftover data buffers up. Obviously you should not set speed, or rather you should set it to higher than realtime, so small clock deviations don't lead to getting behind (I guess ideally mpv should provide a synchronization method that "keeps up" with such realtime streams). For non-network streams, I sometimes use --untimed.

To further debug this issue, use git master and open a new issue if it persists.
