### ISSUE TITLE
There are artifacts while playing the mpeg2video format video with vaapi and vaapi-copy

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#6180]
### mpv version and platform

```
mpv 0.29.0-56-g9f6147a56f Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.19.101
   libavcodec      58.31.102
   libavformat     58.18.103
   libswscale      5.2.100
   libavfilter     7.33.100
   libswresample   3.2.100
ffmpeg version: N-92086-gd702769213
```

CPU: i5-4460
GPU: AMD RX460
Distro: Manjaro with linux4.18

### Reproduction steps
Play the DVD iso image with vaapi
`mpv --no-config --hwdec=vaapi --gpu-context=x11egl --profile=gpu-hq --fs --start=01:24 --pause --log-file=vaapi_blocks sample.ISO`
### Expected behavior
Normal
### Actual behavior
There are so many blocks.
### Log file
With vaapi:
Log file: https://0x0.st/sYxu.txt
![vaapi_blocks](https://user-images.githubusercontent.com/9532105/46398845-d0c52380-c728-11e8-84b5-774e6d965e30.png)

With vaapi-copy:
Log file: https://0x0.st/sYxS.txt
![vaapi-copy_blocks](https://user-images.githubusercontent.com/9532105/46398856-d7539b00-c728-11e8-979b-3b3b4a6c3c4a.png)

Without HW acceleration:
Log file: https://0x0.st/sYxQ.txt
![novaapi](https://user-images.githubusercontent.com/9532105/46398867-dde21280-c728-11e8-9a6f-20a8f40449b4.png)

**Comment by zc62** [comment]
Then just do not hwdec mpeg2. See 3dd59dbed06a55eed00ad68d0a953f39188e3647.

**Comment by laichiaheng** [comment]
@zc62 So it's the hardware problem?

**Comment by lachs0r** [comment]
Yes, very likely a hardware issue. It could be a VA-API bug as well, but I didn’t bother with filing an issue because hwaccel for MPEG2 is pointless in this day and age.
