### ISSUE TITLE
No video on macOS Mojave

### ISSUE THREAD

**Issue by wsc96** [mpv-player/mpv#6182]
### mpv version and platform

mpv stable 0.28.2 via homebrew
macOS Mojave 10.14 on late 2013 MacBook Pro

### Reproduction steps

Clean install of macOS Mojave 10.14. Install only homebrew and then mpv and attempt to play video file. Was working before drive was wiped and clean/upgraded version install of macOS.

### Expected behavior

Expect video and audio to play.

### Actual behavior

Only audio is played. Video window is drawn to correct size/resolution but no video is displayed. 

### Log file

https://0x0.st/sYUw.log

### Sample files

Sample file is 

https://www.youtube.com/watch?v=SbsJaRiZjQM
 
Appears to be the same with any file/stream though. Also, mplayer is working fine if this helps...

**Comment by Akemi** [comment]
this is fixed in master and 0.29.1. if not just report back.

**Comment by wsc96** [comment]
Thanks Akemi. Running the HEAD version and all working now.
