### ISSUE TITLE
Gnome Wayland: mpv only hides the cursor if I move it

### ISSUE THREAD

**Issue by simonbcn** [mpv-player/mpv#6185]
```
Arch Linux 
GNOME Shell 3.30.0 on Wayland

$ mpv --version                                          
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Oct  2 22:30:49 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: n4.0.2

$ cat ~/.mpv/mpv.conf
hwdec=auto
gpu-context=wayland
cursor-autohide=100
fullscreen=yes
monitoraspect=16:9
osd-level=0
save-position-on-quit=yes
hr-seek=yes
volume=100
```

### Reproduction steps
I play any movie file

### Expected behavior
Hide the cursor after 100 ms 

### Actual behavior
It doesn't hide the cursor **until I move it**.

### Remark
If I put in config file `cursor-autohide=always`, it doesn't hide the cursor never even if I move the cursor.

### Log file
https://hastebin.com/zanipuhipi

**Comment by qmega** [comment]
This reminds me of #1166. Maybe the player's idea of cursor visibility is out of sync with the WM's. What happens if you set `cursor-autohide` to a time?

**Comment by simonbcn** [comment]
It seems related.

**Comment by t-8ch** [comment]
The same happens on the sway window manager. According to their devs, the application is responsible for resetting the pointer surface on each "cursor enter" event. However mpv currently only applies it pointer-hiding logic on cursor move events.

**Comment by t-8ch** [comment]
The [documentation of wayland](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_pointer) says for `wl_pointer::enter`:

    When a seat's focus enters a surface, the pointer image is undefined and a client should respond to         this event by setting an appropriate pointer image with the set_cursor request. 

This should probably handled in `wayland_common.c:pointer_handle_enter()`.
So far I did not find a way in which a VO could force mpv to reconfigure its cursor instantly.
