### ISSUE TITLE
NVDEC HW acceleration does not work

### ISSUE THREAD

**Issue by multiflexi** [mpv-player/mpv#6186]
The main issue is that when playing H.264 (1) video using VDPAU is fine and the CPU usage is very low, around 5% but when switching to NVDEC (2) it raises to 20-30% and does not say it is using hardware decoding. When playing unsupported codec AV1 it behaves exactly the same as when playing supported one.
It also surprised me that in manual it states "nvdec: | requires --vo=gpu (Any platform CUDA is available)". I do not understand how is this related to CUDA because Nvidia describes NVDEC as "dedicated hardware video decoder". NVDEC should not be renamed CUVID but successor of VDPAU with support for newer codecs like VP9 which VDPAU does not support. Of course I can be mistaken but that is how Nvidia presents it.

### mpv version and platform
mpv 0.29.0 on Ubuntu Cosmic, driver 396.54, NVIDIA GTX 960

### Reproduction steps
1) mpv --ytdl-format=137 --hwdec=vdpau https://www.youtube.com/watch?v=PiWyCQV52h0
2) mpv --ytdl-format=137 --hwdec=nvdec https://www.youtube.com/watch?v=PiWyCQV52h0
3) mpv --ytdl-format=399 --hwdec=nvdec https://www.youtube.com/watch?v=PiWyCQV52h0

### Expected behavior
1) decoding using GPU
2) decoding using GPU
3) error in terminal and then software playback
### Actual behavior
1) decoding using GPU
2) software decoding
3) software decoding
### Log file
1)
```
Playing: https://www.youtube.com/watch?v=PiWyCQV52h0
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
Using hardware decoding (vdpau).
VO: [gpu] 1920x1080 vdpau[yuv420p]
V: 00:00:01 / 00:01:39 (1%) Cache: 31s+10MB
```
2)
```
Playing: https://www.youtube.com/watch?v=PiWyCQV52h0
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
VO: [gpu] 1920x1080 yuv420p
V: 00:00:01 / 00:01:39 (1%) Cache: 31s+10MB
```
3)
```
Playing: https://www.youtube.com/watch?v=PiWyCQV52h0
 (+) Video --vid=1 (*) (av1 1920x1080 23.976fps)
VO: [gpu] 1920x1080 yuv420p
V: 00:00:02 / 00:01:39 (2%) Dropped: 18 Cache: 31s+13MB
```

**Comment by Doofussy2** [comment]
https://github.com/mpv-player/mpv/issues/5978#issuecomment-414055277

**Comment by mc4man** [comment]
Use this build & you'll be ok.
https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests

**Comment by leigh123linux** [comment]
Example 2 works fine here

```
$ mpv --ytdl-format=137 https://www.youtube.com/watch?v=PiWyCQV52h0
Playing: https://www.youtube.com/watch?v=PiWyCQV52h0
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
Using hardware decoding (nvdec).
VO: [gpu] 1920x1080 cuda[nv12]
V: 00:00:01 / 00:01:39 (1%) Cache: 32s+11MB
```

Example 3 in verbose mode reveals

```
[vd] Container reported FPS: 23.976025
[vd] Codec list:
[vd]     libaom-av1 (av1) - libaom AV1
[vd] Opening decoder libaom-av1
[vd] Not trying to use hardware decoding: codec av1 is not on whitelist.
[vd] Using software decoding.
[vd] Detected 8 logical cores.
[vd] Requesting 9 threads for decoding.
[ffmpeg/video] libaom-av1: 1.0.0-654-gd0076f507
[vd] Selected codec: libaom-av1 (libaom AV1)
[vf] User filter list:
[vf]   (empty)
```

**Comment by mc4man** [comment]
As far as hwdec for av1 the limitation is in the hardware itself, as in currently there is none.

At least here those google vc1  encodings can be decoded but many playback pretty shitty, ie. considerable dropped frames on higher res ones. Maybe because they use the reference encoder which, at least here, mpv doesn't handle well & only seems to use single threaded decoding. 
By comparison av1 done via libaom-av1 performs ok here on mpv with multi-threaded decoding.

There will be another decoder arising (dav1d) that could show better user performance..

**Comment by multiflexi** [comment]
AV1 decoding is fine, I mentioned it as an example of unsupported codec to show that it behaves exactly the same in case of H.264 (supported codec). I will test mentioned version from ppa soon, sadly there is no version for cosmic yet.

**Comment by multiflexi** [comment]
I must confirm that the version from mpv-tests PPA works great. CPU usage is around 5-15% with VP9 UHD 60fps YouTube video and around 10-20% when playing H.265 UHD 24fps movie. Now even with my CPU heavily underclocked the video plays fine.
