### ISSUE TITLE
Using hwdec=vaapi-copy on PRIME laptop powers up discreet card

### ISSUE THREAD

**Issue by FireBurn** [mpv-player/mpv#6187]
### mpv version and platform

MPV 0.27.2 on Gentoo Linux

### Reproduction steps

Play a video using vo=opengl & hwdec=vaapi-copy

See this in dmesg:

<starts video>

[ 2790.346846] [drm] PCIE GART of 1024M enabled (table at 0x000000F400000000).
[ 2790.444873] [drm] UVD initialized successfully.
[ 2790.656006] [drm] VCE initialized successfully.

<stops video>

[ 2802.570324] amdgpu 0000:01:00.0: GPU pci config reset

If I use hwdec=vaapi this doesn't happen

### Expected behavior

For the AMDGPU card not to be powered up

### Actual behavior

Card powers up for the duration of a video

### Log file

fireburn@axion ~ $ DISPLAY=:0 mpv --vo=opengl --hwdec=vaapi-copy Video/test.mp4
Playing: Video/test.mp4
 (+) Video --vid=1 (*) (h264 1280x720 29.969fps)
 (+) Audio --aid=1 --alang=und (*) (aac 2ch 44100Hz)
Using hardware decoding (vaapi-copy).
VO: [opengl] 1280x720 nv12
AO: [pulse] 44100Hz stereo 2ch float
AV: 00:00:01 / 00:32:02 (0%) A-V:  0.000 Dropped: 5
Invalid audio PTS: 1.973469 -> 3.993605

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:07 / 00:32:02 (0%) A-V:  0.297 ct:  1.723 Dropped: 5

Exiting... (Quit)

fireburn@axion ~ $ DISPLAY=:0 mpv --vo=opengl --hwdec=vaapi Video/test.mp4
Playing: Video/test.mp4
 (+) Video --vid=1 (*) (h264 1280x720 29.969fps)
 (+) Audio --aid=1 --alang=und (*) (aac 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
Using hardware decoding (vaapi).
VO: [opengl] 1280x720 vaapi[nv12]
AV: 00:00:01 / 00:32:02 (0%) A-V:  0.000
Invalid audio PTS: 1.973469 -> 3.993605

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

AV: 00:00:17 / 00:32:02 (0%) A-V:  0.000 ct:  2.020

Exiting... (Quit)

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by FireBurn** [comment]
So as of 0.29.0 https://github.com/mpv-player/mpv/commit/e3e2c794efcff035615ac93f8a4cd9ab2cef4d97 added the feature to be able to specify the vaapi-device, it used renderD128 as default which is the discreet card in most PRIME sytems, with renderD129 being the Intel graphics

Is there a way to get MPV to detect which it should be using automatically

Also what are the differences between vaapi-copy and vaapi?

**Comment by xantoz** [comment]
Since it isn't possible to be able to tell which render node should be use for VAAPI copy (at least not in a generic way), I guess manually specifying using --vaapi-device is the way to go.

**Comment by Akemi** [comment]
one can probably write a script for that.
