### ISSUE TITLE
Set path to youtube-dl

### ISSUE THREAD

**Issue by miagile** [mpv-player/mpv#6189]
I'm bundling mpv in a OSX .app bundle. The issue is that mpv is looking for youtube-dl somewhere in `/user/local/bin` and most of the people don't have youtube-dl installed.

   How can I make mpv  to use a different path (i.e. a path within the .app directory) when it invokes youtube-dl  instead of /usr/local/bin ?

**Comment by Akemi** [comment]
i believe you can put the binary within the `X.app/Contents/Resources/` folder, mpv should look in there too.
