### ISSUE TITLE
Hang up with growing commit size upon opening Youtube URL

### ISSUE THREAD

**Issue by satnatantas** [mpv-player/mpv#6190]
### mpv version and platform

mpv 0.29.0-35-g9c184078a6
W7x64SP1

### Reproduction steps
download lachs0r (shinchiro does same, I checked) build and youtube-dl, place into same folder
run `mpv -v https://www.youtube.com/watch?v=GgIGq_LGT6I`

### Expected behavior
Video is played

### Actual behavior
No window appears, commit size grows indefinitely with physical usage being around 100MB and slowly growing. When run from console, I get this information: https://paste.ee/p/jKF7S
Downloading same video and playing it from HDD works.

### Log file

https://paste.ee/p/jKF7S

**Comment by haasn** [comment]
For some reason that video produces a JSON output (via youtube-dl) that's 34,172 lines long. (For comparison, typical videos produce maybe several hundreds of lines at most)

I expect it's parsing all of this information that takes absolutely forever.

**Comment by haasn** [comment]
Looking at the JSON a bit, it doesn't appear as though the video in particular has more formats than usual, but the formats that it does have seem to be split up into a high number of individual fragments for some reason.

**Comment by satnatantas** [comment]
It changed for some reason.
https://paste.ee/p/ulOh5

**Comment by satnatantas** [comment]
I have
`ytdl-format=bestvideo[height<=1080]+bestaudio/best[height<=1080]/bestvideo+bestaudio/best`
in my config if that matters.

**Comment by satnatantas** [comment]
Updated youtube-dl today, it's fixed.
