### ISSUE TITLE
GUI - allow custom aspect ratio for the video

### ISSUE THREAD

**Issue by slrslr** [mpv-player/mpv#6192]
Hello, i am using Ubuntu 16.04 and mpv git-2018-05-17-05b392b

i am opening a video thru Linux graphical interface and the video is mpeg4 576x432, aspect ratio 1.33

I can use Shift+A shortcut to toggle original and wide screen aspect ratio. None shows image right.
More close to reality is the original aspect ratio. I need the video to be slightly less wide / slightly more height. I wish mentioned keyboard shortcut can toggle more modes or other way i simply customize the ratio via GUI, not by needing to open command line, find the file and define the aspect ratio parameter while i do not understand which ratio i should use (i see i may use "--no-keepaspect" parameter to the mpv command, which will always stretch the video to window size also there is other parameter: no-video-aspect), i think user should be able to define right video dimensions easily via GUI. i am missing any button or hint in GUI that would tell me the keyboard shortcuts that i can use or how to call some menu or options. Where user can easily click what to do with the video.

**Comment by Jj0YzL5nvJ** [comment]
Try using `--no-keepaspect`.

**Comment by zc62** [comment]
mpv does not have a GUI. See #5500. So currently using CLI/mpv.conf/input.conf/scripts is expected.

If it is the problem that Shift + A cannot give you the correct 1.33 aspect ratio, then it is related to #6068 and #6287.

**Comment by Akemi** [comment]
related issue was fixed.
