### ISSUE TITLE
Playing Youtube video without sound

### ISSUE THREAD

**Issue by satnatantas** [mpv-player/mpv#6193]
### mpv version and platform

mpv 0.29.0-35-g9c184078a6
W7x64SP1

### Reproduction steps
download lachs0r build and youtube-dl, place into same folder
add `ytdl-format=bestvideo[height<=1080]+bestaudio/best[height<=1080]/bestvideo+bestaudio/best` to config
run `mpv -v https://www.youtube.com/watch?v=9-yG3D3JBRs`

### Expected behavior
Video is played with sound.

### Actual behavior
Video is played without sound.
Downloading same video and playing it from HDD works.

### Log file

https://paste.ee/p/niefd
(opened, played few seconds, paused, ctrl+c)

**Comment by haasn** [comment]
Works for me. Try updating youtube-dl?

**Comment by satnatantas** [comment]
Works for me too now.
