### ISSUE TITLE
ServusTV live stream doesn't work when loaded directly with mpv

### ISSUE THREAD

**Issue by RedirectCleaner** [mpv-player/mpv#6194]
### mpv version and platform
mpv 0.27.2

### Reproduction steps
mpv https://www.servus.com/at/tv/jetzt-bei-servus-tv/

### Expected behavior
the player plays the stream

### Actual behavior
the video doesn't start and mpv directly exits, seems the problem is related to the duration youtube-dl reports

[timeline] Timeline segments:                                                                                                          
[timeline]   0:     0.000000 [70253.451556] (0 1) 0:'https://liveservustv-i.akamaihd.net/hls/live/270998/ServusTV_AT/master_2192.m3u8' 
[timeline] Total duration: 0.000000   

but starting the video with
youtube-dl https://www.servus.com/at/tv/jetzt-bei-servus-tv/ -o - | mpv -
works

### Log file
https://nopaste.xyz/?4220ed0349a82ef6#yjGwxK825lg6AHo8+pDWGFn176d7AC4LpIiENtoeBgc=

**Comment by garoto** [comment]
Your mpv is too old perhaps.

Works for me thru a german proxy using `mpv 0.29.0-21-gd2d7dba6ee` together with `youtube-dl 2018.09.10`.

![image](https://user-images.githubusercontent.com/11768175/46625843-d09f9c00-cb0b-11e8-9241-fadef784abad.png)

**Comment by Akemi** [comment]
yeah, i can also confirm it working.

**Comment by RedirectCleaner** [comment]
thanks i can confirm it too.
