### ISSUE TITLE
how to get mpv to display thousand of a second on a video ?

### ISSUE THREAD

**Issue by shirishag75** [mpv-player/mpv#6195]
By default mpv shows hh:mm:ss on the bottom bar/OSD . I want it to also display the thousand of a second as well i.e. hh:mm:ss:sss . How can I do that ?

I want the hh:mm:ss of what is being played as well as of the total duration (if possible). 

I am on Debian testing and using the latest release i.e. 0.29.1 

and have the following config file - 

```
~/.config/mpv$ cat mpv.conf 
alang=eng,en,english
slang=en,eng, english
sub-scale=1.50
save-position-on-quit
```

**Comment by garoto** [comment]
Just mouse click once on the OSD current time display (the left-most one).

![image](https://user-images.githubusercontent.com/11768175/46635955-8844a600-cb2c-11e8-89a1-167853dc514f.png)

**Comment by shirishag75** [comment]
nice, that's handy. I just checked it out, but is there a way to make it a permanent feature using the .config file or something ?

**Comment by Argon-** [comment]
https://mpv.io/manual/master/#options-osd-fractions
There's no dedicated option for permanent OSC fractions.
There's also no dedicated option for having other time values displayed in the OSC. For the OSD, you can change https://mpv.io/manual/master/#options-osd-status-msg and put the desired properties in there.
