### ISSUE TITLE
Automatically replace old screenshots with new screenshots

### ISSUE THREAD

**Issue by bluefiberbread** [mpv-player/mpv#6198]
I still have the original videos and a timestamp in the old screenshot's filename, so I'm wondering if it's possible to automatically replace old screenshots with new screenshots, maybe with a script or something. I'm not exactly tech savvy, so I don't know much about programming, but I have a bunch of old screenshots from mpv and I want to take new screenshots with my new settings because I realized default settings butchered the quality of the screenshot. It would save me so much time, because in my case, re-watching videos and taking new screenshots would literally take several years. Does such a script exist, and if it doesn't, would it be possible to make one with mpv?

**Comment by zc62** [comment]
Would be better if you can provide some samples, otherwise we do not even know where to start from. Does the folder look like the following?
```
├── folder1/
│   ├── video1.mp4
│   ├── video1-04:32:89.png
│   ├── video1-05:11:30.png
│   ├── video2.mp4
│   ├── video2-03:41:22.png
│   ├── video1-12:43:21.png
```
Which OS are you using? Do you plan to use mpv's built-in screenshot or use PRINTSCREEN?

**Comment by haasn** [comment]
I have a script [here](https://github.com/haasn/mpv-unit/blob/master/run.sh) that should help to get you started. You should be able to change that into a form where you now just need to emit the right sequence of `load`, `cmd seek` and `save` commands. I'm sure it wouldn't be too difficult to parse the filenames in a loop and do this.
