### ISSUE TITLE
INstall not working? why

### ISSUE THREAD

**Issue by ochoocho** [mpv-player/mpv#6204]
### mpv version and platform

mpv-MEDIA PLAYER INSTALL x86_64-20181002
Latest October18 Win64 install (windows 7), but it also does the same on older installs

I have unzipped the files with 7zip to a folder, but when launching the install (mpv.exe), nothing happens.
This wasn't happening on other computers, but my main computer doesn't seem to launch the install for some reason.

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
It's not an installer.

**Comment by ochoocho** [comment]
Where is the installer so?
Looking for a straighforward way to install this on a pc
Or if that's not possible, how do you go about it. It all seems pretty cryptic

**Comment by CounterPillow** [comment]
Please read what's written on the page you've downloaded it from: https://mpv.srsfckn.biz/

Specifically:

>To set up file type associations and AutoPlay handlers, use mpv-install.bat.
