### ISSUE TITLE
[Learning] Learn mpv source code

### ISSUE THREAD

**Issue by ybma-xbzheng** [mpv-player/mpv#6205]
Is there any material that can help with learning mpv source code? Such as architecture diagrams, documentation, or some other useful things.

**Comment by CounterPillow** [comment]
https://github.com/mpv-player/mpv/blob/master/DOCS/tech-overview.txt

**Comment by haasn** [comment]
If you're interested in the video output side of things there are some semi-useful infodumps on the wiki:

- https://github.com/mpv-player/mpv/wiki/Video-output---shader-stage-diagram (probably somewhat out of date)
- https://github.com/mpv-player/mpv/wiki/Display-synchronization
- https://github.com/mpv-player/mpv/wiki/Interpolation
- https://github.com/mpv-player/mpv/wiki/Upscaling
