### ISSUE TITLE
AUDIO EQUALIZER

### ISSUE THREAD

**Issue by johnthecracker** [mpv-player/mpv#6210]
### mpv version and platform

mpv-i686-20181007-git-2b0b9bb.7z
windows 10

### Reproduction steps

mpv.exe http://radio.pauta.cl/playlist/stream.m3u8

### Expected behavior

use audio equalizer with MPV on command line or config file

### Actual behavior

using MPV without equalizer, missing a lot on sound quality

### More details

I can set audio equalizer with mplayer on command line like this, works like a charm:
```
mplayer.exe %url% -af equalizer=8:4:-3:-1:0:1:2:3:2:3
```
Can this be translated to mpv switch?

If not, then how do I get audio equalizer setting with mpv in config file or command line?

I looked at documentation and couldn't figure it out.

Thanks to anybody who replies.

**Comment by lachs0r** [comment]
Most filters have been moved to libavfilter, so they are not documented in mpv’s own manual. See https://ffmpeg.org/ffmpeg-filters.html for documentation.

**Comment by johnthecracker** [comment]
Thank you for this quick reply.
This is something that I did not expect, to get it with ffmpeg switches.
Could it then work with ffplay.exe as well?
It would be magic!
Could you please post one real life example how you set that equalizer with mpv or ffplay?

**Comment by lachs0r** [comment]
Works like any other filter, so e.g. `-af superequalizer=2b=15:4b=13`. This syntax works with both mpv and ffplay.

**Comment by johnthecracker** [comment]
Thank you.
Now I have to work on that to make it work, it will take me some time.
It is great that I have right guidance for the start.
When I get it done I'll post working example here.
Audio equalizer is good to have with player like mpv.

**Comment by keshavbhatt** [comment]
how to reset superequalizer at runtime ??

**Comment by johnthecracker** [comment]
with some sort of GUI interface.
I don't see how to play the script once it runs.

**Comment by garoto** [comment]
in input.conf: `F1 af toggle "superequalizer=2b=15:4b=13"`

**Comment by keshavbhatt** [comment]
I 

> how to reset superequalizer at runtime ??

in slave mode :
`echo  '{"command": ["af" ,"set",""]}' | socat - /tmp/mpvserver `

**Comment by victoriastuart** [comment]
For reference only (re: this thread & my personal use): e.g., I have not yet tweaked these dynamic ranges ...

```
# https://www.mltframework.org/plugins/FilterAvfilter-superequalizer/
# https://github.com/mpv-player/mpv/issues/6210#issuecomment-507040866
# https://ffmpeg.org/ffmpeg-filters.html#superequalizer
#   * SUPEREQUALIZER
#    ** Apply 18 band equalizer
#    ** Parameters: av.1b - av.18b; e.g.:
#    av.1b
#       description: set 65Hz band gain
#       type: float
#       readonly: no
#       required: no
#       minimum: 0
#       maximum: 20
#       default: 1
F2  af toggle "superequalizer=1b=4:2b=12:4b=10:9b=10:16b=12"
F3  af toggle "superequalizer=1b=2.9:2b=0.0:3b=2.4:4b=3.3:5b=3.3:6b=3.3:7b=2.4:8b=1.4:9b=1.4:10b=1.4"
# F2  af toggle "superequalizer=-2.9:0.0:2.4:3.3:3.3:3.3:2.4:1.4:1.4:1.4"       ## live [https://advantage-bash.blogspot.com/2013/05/mplayer-presets.html]
```

**Comment by keshavbhatt** [comment]
I have implemented equalizers and superequalizer both together[ here ](https://github.com/keshavbhatt/olivia) 

![ Equalizers in Olivia ](https://pbs.twimg.com/media/EA003j1UYAAT5-m?format=jpg)

**Comment by johnthecracker** [comment]
Men, these are great news!
Can somebody tell me how to implement 18 band equalizer settings to sound the same as 10 band setings ?
For example my settings for Audacious are:

8 4 -3 -1 0 1 2 3 2 3

and I would like to get the same sound with ffplay or mpv equalizer, 18 band.
Or where to find some tutorial to tell me how to figure out comparable settings ?
So far, no luck with my experiments.

<a href='https://postimg.cc/TyBkbZNF' target='_blank'><img src='https://i.postimg.cc/TyBkbZNF/Screen-Shot.jpg' border='0' alt='Screen-Shot'/></a>

**Comment by keshavbhatt** [comment]
not sure how you will be doing this in audacious but mpv, mplayer and ffplay can use these, example check fireequalizer.lua script in mpv user script github repo.

**Comment by johnthecracker** [comment]
I am struggling to get 18 band equalizer settings right and would like to
replicate the sound I currently have with 10 band equalizer.
VLC has 10 band equalizer but some other numbers than audacious and I can't set VLC's numbers right either.
It is simpler with numers 1 to 10 than frequency numbers.

I would like these 10 numbers 8 4 -3 -1 0 1 2 3 2 3

written in 18 numbers to use them in 18 band equalizer to get the same sound.

18 settings like these ( 2b=15:4b=13 ) to sound like these 10 settings ( 8 4 -3 -1 0 1 2 3 2 3 )

**Comment by keshavbhatt** [comment]
these equalizers tgings are from ffmpeg read the documentation of ffmpeg for appropriate values. you can also take reference from my code look equalizer.cpp

**Comment by johnthecracker** [comment]
Yes. it tells me how to construct command line argument to use in scripts or on command line,
but the sound I hear is something I have to make with my numbers.

This question is answered about with how to do it and I don't get level values with 
18 band like with 10 band. Some musician who understands frequency values would maybe
answer how 8 4 -3 -1 0 1 2 3 2 3 translates in frequences.

**Comment by keshavbhatt** [comment]
those 18 bands are not equalizers in true sense they are more like audio filters. yes they are called super.eq but they act like filters. i tested this and audio use to stop as you change the value of any one band. values are from 0-20 .

**Comment by johnthecracker** [comment]
You obviously know more than me about this topic.
Values 0-20 is something that works in audacious like -10 to 10 in every one of 10 settings.
Another problem is my ears.
You give me gui and I simply have to listen to how am I sliding those controls and get it.
VLC has 10 controls and however I slide I don't get it like in audacious.
Now, I face 18 sliders for mpv equalizer. 
In the end I will have to keep on sliding and hoping I get close to  ( 8 4 -3 -1 0 1 2 3 2 3 ) settings.
This is not really something specific about mpv, solutions are here and you provide gui
on top of all solutions here.
Maybe I should find some mplayer and audacious board and enquire what frequencies are their ( 8 4 -3 -1 0 1 2 3 2 3 ) ?

Your quote:

2b is band name and 15 is its value. values are from 0-20

Set every band to 10 in "filters" would be like setting every band to 0 on audacious "equalizer".
If I am right here I learned something new today. This is a good starter
to set filter values all to 10 and go digit by digit up or down.

So to speak, ( 8 4 -3 -1 0 1 2 3 2 3 ) would be ( 18 14 7 9 10 11 12 13 12 13 )
would there be 10 bands only in mpv, but there are 18.
This is already one half ot the problem solved for me here if I am right.
If yes, than all those numbers in filters make sense to me after reading your last post.
Now I can start with mpv filter's 18 bands all set to 10 and I should be on good starting point,
called "flat" in vlc.

**Comment by johnthecracker** [comment]
I am on square one again.
I tried following setting and it is nowhere near "flat" setting.
At least code is correct at this point.

```
set file="Robert Fairchild Jr. - As the Deer-kfyRB_GpHQY.mkv.mka"

set equalizer="--af=superequalizer=1b=10:2b=10:3b=10:4b=10:5b=10:6b=10:7b=10:8b=10:9b=10:10b=10:11b=10:12b=10:13b=10:14b=10:15b=10:16b=10:17b=10:18b=10"

mpv.exe %equalizer% %file%
```
If anyone has "flat" setting for command line for superequalizer please correct this setting:

```
--af=superequalizer=1b=10:2b=10:3b=10:4b=10:5b=10:6b=10:7b=10:8b=10:9b=10:10b=10:11b=10:12b=10:13b=10:14b=10:15b=10:16b=10:17b=10:18b=10
```

**Comment by richardpl** [comment]
gains should be 1 for flat

**Comment by johnthecracker** [comment]
Just checked this:

```
--af=superequalizer=1b=1:2b=1:3b=1:4b=1:5b=1:6b=1:7b=1:8b=1:9b=1:10b=1:11b=1:12b=1:13b=1:14b=1:15b=1:16b=1:17b=1:18b=1
```
These are flat settings. 
Now we have a starting point for everyone to tweak equalizer to his liking.

**Comment by victoriastuart** [comment]
[See my earlier comments, above, for background.]

I'm basically interpreting these superequalizer settings as gains (range 0-20); they are quite severe.  As an experiment I plotted (paper here: https://incompetech.com/graphpaper/lite/) these settings -- which on my videos are less satisfactory than the default MPV audio settings (on downloaded videos: TV shows, ...), but which may be useful under some viewing circumstances.

Here is a link to my plot, from which I derived the following filters (added to input.conf).

![mpv_superequalizer_settings](https://user-images.githubusercontent.com/2575920/62326751-ae448980-b463-11e9-894b-c924a1e6b8cb.png)

```
#Linear (lower bass | higher treble):
F1  af toggle "superequalizer=1b=1.0:2b=1.5:3b=2.0:4b=2.7:5b=3.1:6b=3.7:7b=4.1:8b=4.7:9b=5.2:10b=5.8:11b=6.3:12b=6.8:13b=7.4:14b=7.8:15b=8.4:16b=9.0:17b=9.5:18b=10.0"
# Sinusoidal:
F2  af toggle "superequalizer=1b=2.0:2b=3.6:3b=3.8:4b=5.5:5b=6.0:6b=6.4:7b=6.6:8b=6.4:9b=6.0:10b=5.2:11b=4.0:12b=3.2:13b=3.0:14b=3.2:15b=3.8:16b=4.4:17b=5.2:18b=6.5"
```

**Comment by victoriastuart** [comment]
[See my earlier comments, above, for background.]

I'm basically interpreting these superequalizer settings as gains (range 0-20); they are quite severe.  As an experiment I plotted (paper here: https://incompetech.com/graphpaper/lite/) these settings -- which on my videos are less satisfactory than the default MPV audio settings (on downloaded videos: TV shows, ...), but which may be useful under some viewing circumstances.

Here is a link to my plot, from which I derived the following filters (added to input.conf).

![mpv_superequalizer_settings](https://user-images.githubusercontent.com/2575920/62326751-ae448980-b463-11e9-894b-c924a1e6b8cb.png)

```
#Linear (lower bass | higher treble):
F1  af toggle "superequalizer=1b=1.0:2b=1.5:3b=2.0:4b=2.7:5b=3.1:6b=3.7:7b=4.1:8b=4.7:9b=5.2:10b=5.8:11b=6.3:12b=6.8:13b=7.4:14b=7.8:15b=8.4:16b=9.0:17b=9.5:18b=10.0"
# Sinusoidal:
F2  af toggle "superequalizer=1b=2.0:2b=3.6:3b=3.8:4b=5.5:5b=6.0:6b=6.4:7b=6.6:8b=6.4:9b=6.0:10b=5.2:11b=4.0:12b=3.2:13b=3.0:14b=3.2:15b=3.8:16b=4.4:17b=5.2:18b=6.5"
```

---

```
# Linear: shallower, punctuated (only odd bands altered):
F3  af toggle "superequalizer=1b=1.0:2b=0:3b=1.4:4b=0:5b=1.8:6b=0:7b=2.4:8b=0:9b=2.8:10b=0:11b=3.3:12b=0:13b=3.75:14b=0:15b=4.3:16b=0:17b=4.75:18b=0"
# Lowered bass:
F4  af toggle "superequalizer=1b=1:2b=1:3b=1:4b=1:5b=2:6b=2:7b=2:8b=2:9b=2:10b=2:11b=2:12b=2:13b=2:14b=2:15b=2:16b=2:17b=2:18b=2"

```

**Comment by johnthecracker** [comment]
WOW Victoria !
You make my head spin !
I'll need some time to test what I can from this feedback.

I worked my Audacious settings by taking one preset that looked good and then
set bass - last 2 settings high.

Now when I look for which Audacious preset it was that I started with I can't find presets
in neither Windows version nor Ubuntu Studio version.
Presets were probably installed by default in some old Lubuntu Audacious version
which I ran until Lubuntu became crap.

Setting bands one by one I get nowhere. I'll have to find one good sounding preset
and just increase bass. I aim to hear high mid and bass all properly
as I have Technics speakers and amplifier and M-Audio sound card.
M-AUDIO AUDIOPHILE 24/96 is a waste without good equalizer settings.

Cheers!

**Comment by victoriastuart** [comment]
Audacious rocks (I tried it briefly when Clementine | Strawberry were acting up: freezing, quitting) but I prefer the playlist management, sidebar etc. available in Strawberry (a lightweight Clementine fork)!  ;-)  Nonetheless, my general preference is for simple, solid performant programs, like Audacious!  :-)

**Comment by johnthecracker** [comment]
MPV pros: can play nearly everything

AUDACIOUS cons: for audio files only.
pros: easy equalizer. ( I'll install old lubuntu to see if I find presets... )
can even play internet radio stations !  ( via streamlink... )

https://github.com/streamlink/streamlink/issues/2111

**Comment by keshavbhatt** [comment]
check olivia https://github.com/keshavbhatt/olivia its based on mpv and can play audio video internet radio. have nice equalizers, themes, audio visualizations, etc

**Comment by johnthecracker** [comment]
Without having a look first..
equalizer is pain in the neck. 
I'll have a look later to see if I can borrow something from it's equalizer,
it would contribute this thread and topic.

**Comment by richardpl** [comment]
You can use dB as units for bands.

**Comment by johnthecracker** [comment]
Thank you for this tip.
I hear of this for the first time, so I have to take a close and detailed look.

**Comment by lukaszgryglicki** [comment]
This sounds good for me with rock/metal-like sound: `--af=superequalizer=1b=3:2b=4:3b=5:4b=6:5b=5:6b=4:7b=3:8b=2:9b=1:10b=1:11b=2:12b=3:13b=4:14b=5:15b=6:16b=7:17b=8:18b=7`

**Comment by johnthecracker** [comment]
It depends on what hardware you use. As you say, it works somewhere.
By the way, on what hardware setup ?
I have amplifier Technics SU-V300, speakers Technics SB-F911 and sound card M-Audio Delta Audiophile 24/96.
With my equipment your setting renders distorted sound.
My audacious or mplayer equalizer works with gospel, country, rock or any other kind of music.
When I listen to speech I set bass to MIN and treble to MAX with my amplifier's bass control knob 
with equalizer or without it.

It is good that we started somewhere and I'll post some samples as well when I get them.

**Comment by lukaszgryglicki** [comment]
Hey, I'm a total sound newbie (I'm just a programmer). Old-time metal fan (born in 1982). I just have plain iMac without any additional hardware. That setting makes [this](https://www.youtube.com/watch?v=chV95J2WrRU) sound good to me.

**Comment by richardpl** [comment]
Not using dB units will give strange equalizer output.

**Comment by johnthecracker** [comment]
I have a problem with decibels.
I found decibels in VLC equalizer and they tell me nothing.
For example each control line measures -20 to +20 dB.
16 KHz line = -20 dB to +20 dB
14 KHz line = -20 dB to +20 dB
12 KHz line = -20 dB to +20 dB.
From this finding I can't figure out how decibels work without KHz.
VLC eq. settings look much different than AUDACIOUS settings for similar sound
and with VLC I have least of luck.
If I had decibels settings given to me, how to use them with af=superequalizer ?

**Comment by richardpl** [comment]
Please consult documentation, there is khz listed for each superequalizer band.
If you have decibels setttings: use af=superequalizer=5dB:2dB:-1dB:.... etc
You can also use firequalizer which unlike superequalizer can use minimal phase filters.

**Comment by johnthecracker** [comment]
I'll try to put VLC and MPV bands and KHz side by side and see if I can compare something between those two.

**Comment by diegocr** [comment]
Thank you @victoriastuart, your post was inspiring!

I ended up using the following after struggling with this for a while myself:

```
af=lavfi=[loudnorm=I=-18:TP=-3:LRA=4:linear=false:offset=2],superequalizer=1b=2.0:2b=1.3:3b=1.6:4b=2.0:5b=1.2
```

anyone's feedback is welcome :-)

**Comment by mohamad0074** [comment]
> check olivia https://github.com/keshavbhatt/olivia its based on mpv and can play audio video internet radio. have nice equalizers, themes, audio visualizations, etc

how use application?

**Comment by amariami** [comment]
try to listen from https://www.youtube.com/watch?v=edlLhh8qVxM, super equalizer distort my earbuds

read FFmpeg filter documentation I found:
[`--af-add=lavfi=[stereotools=phasel=true:phaser=true:phase=180:bmode_out=power] #set phase degree allowed range is from 0 to 360, My preference 30/60/90/180/360`](https://ffmpeg.org/ffmpeg-filters.html#stereotools)
and
[`--af-add=lavfi=[asoftclip=type=quintic:threshold=1:output=1:oversample=16 ##type set to "hard" "tanh" "atan" "cubic" "exp" "alg" "quintic" "sin" "erf"`](https://ffmpeg.org/ffmpeg-filters.html#asoftclip)

**Comment by borisorlov21** [comment]
--af=superequalizer=1b=1:2b=3:3b=3:4b=3:5b=3:6b=4:7b=3:8b=2:9b=3:10b=3:11b=2:12b=3:13b=2:14b=5:15b=4:16b=7:17b=3:18b=7

**Comment by richardpl** [comment]
superequalizer is old filter, modern approach is to use afir filter with combination of afireqsrc or single firequalizer filter.

**Comment by headfog** [comment]
> superequalizer is old filter, modern approach is to use afir filter with combination of afireqsrc or single firequalizer filter.

afireqsrc seems to exist only since recently and finding a working example is proving difficult at the moment. Would you mind expanding a bit ?

**Comment by zhouxinghong** [comment]
👍

**Comment by richardpl** [comment]
What you mean by "individual"? Also note that gains are better with mean removed, so if you set each band to >0 (its in dB): and 3 bands with gains 1 2 3, it should be -2 -1 0 instead. Otherwise you get pointless full volume boost for all bands.
If you want dynamic configuration via GUI of equalizer, need to write lua plugin script for mpv. I also use lavfi-preview app I developed. But as ffmpeg currently does not support options as arrays the only interface to those numbers are strings.

**Comment by zhouxinghong** [comment]
It would be perfect if any friend could transplant the full low...treble of vlc. I found that the sound effect of this filter is very good😜

**Comment by borisorlov21** [comment]
The individuality of the equalizer settings depends on the technical features of the audio equipment that you use; acoustic systems all play sounds differently.
I adjusted it to suit my acoustics

**Comment by zhouxinghong** [comment]
> The individuality of the equalizer settings depends on the technical features of the audio equipment that you use; acoustic systems all play sounds differently.
> I adjusted it to suit my acoustics

Can you let me hear the sound quality after you modified it? 😜

**Comment by richardpl** [comment]
vlc equalizer is IIR based, with 10 bands usually: you can find bands center frequencies and gains per band in this file: [equalizer_presets.h](https://github.com/videolan/vlc/blob/master/modules/audio_filter/equalizer_presets.h). Conversion to mpv/ffmpeg syntax is trivial.

**Comment by zhouxinghong** [comment]
> vlc equalizer is IIR based, with 10 bands usually: you can find bands center frequencies and gains per band in this file: [equalizer_presets.h](https://github.com/videolan/vlc/blob/master/modules/audio_filter/equalizer_presets.h). Conversion to mpv/ffmpeg syntax is trivial.
Thank you for your help and sharing! But I don't know how to apply it to mpv, can you give an example, thank you very much! 😜

**Comment by headfog** [comment]
VLC "full bass and treble" would be 
`mpv x.wav -af "lavfi=[anull[a];afireqsrc=preset=custom:gains=7.2 5.6 -7.2 -4.8 1.6 8.0 11.2 12 12:bands=60 170 600 1000 3000 6000 12000 14000 16000[ir];[a][ir]afir=dry=4dB]"`

**Comment by headfog** [comment]
This was my assumption indeed, thanks for pointing it out. The filter is now corrected

**Comment by zhouxinghong** [comment]
Thank you very much to the teachers for their help and guidance! 🎉😜👍I compared the sound effects of this filter with the native sound effects of vlc and found that there is still a lot of room for improvement:
1. The sound effect of vlc is fresh and bright in the treble band, while it is delicate, soft, tough and powerful in the bass band.

2. Our sound effect sounds very muddy and dull, and it should need further improvement to match the sound effect of vlc.

**Comment by headfog** [comment]
Yes, all i did is a litteral "translation" to give you the snippet to play with and adjust the parameters to your liking. As far as i know there is no way to convert exactly an IIR filter to FIR. The best one can achieve is approximation.

**Comment by richardpl** [comment]
fresh/muddy/dull/bright are not science terms, so it is just your very limited experience.
I think that just overall mpv gain is lower than what vlc outputs by default. But unlikely to ever get any reproducible numbers from such extremely lazy users that can not write mpv graphs on their own.

**Comment by zhouxinghong** [comment]
Thanks to the teachers for their guidance! 👍😜 Unfortunately, I don’t know anything about audio knowledge. I just rely on my listening experience. If I know the role of each parameter in the audio, then I will try to transfer this as much as possible according to the existing audio parameters of vlc. Go to the mpv platform.

**Comment by richardpl** [comment]
I may post frequency response of that vlc equalizer filter and that preset. To see what it actually does to your sound.
mpv can also use various IIR filters from libavfilter.

**Comment by zhouxinghong** [comment]
> I may post frequency response of that vlc equalizer filter and that preset. To see what it actually does to your sound. mpv can also use various IIR filters from libavfilter.

Very cool! 🎉👍😜❤

**Comment by richardpl** [comment]
Just got frequency response for that VLC equalizer preset, and its completely different from one user sets via preset or knobs.
The mpv/ffmpeg response using those numbers almost match actual config. Just note that above dry setting is invalid.
The preamp for VLC equalizer is used in following manner: irgain=-preamp. So full corrected cli command looks like this:

`mpv x.wav -af "lavfi=[anull[a];afireqsrc=preset=custom:gains=7.2 5.6 0 -7.2 -4.8 1.6 8.0 11.2 12 12:bands=60 170 310 600 1000 3000 6000 12000 14000 16000[ir];[a][ir]afir=irgain=-4dB:irnorm=-1]"`

To get exact match with settings get latest librempeg build instead of ffmpeg, as I fixed silly bug in afireqsrc filter there. (gains for higher frequencies where not properly attenuated - they were mostly ignored)

**Comment by zhouxinghong** [comment]
@richardpl 
Thank you so much teacher for all your hard work! 🎉👍😜
Can you please tell me how to get and use the latest librempeg in mpv? 

PC environment:
Windows 10 19044
i5 processor

**Comment by richardpl** [comment]
Currently only by compiling it yourself.

**Comment by zhouxinghong** [comment]
Compiling it yourself is a difficult problem for us, and it is difficult for non-professionals to do it!😂

**Comment by richardpl** [comment]
You need to be more detailed. What kind of audio bass bosting? The equalizer one? The firequalizer/afir/shelf iir/bass filters can do it already and many more other solutions in librempeg exist! Do you need perceptual bass boost including additional harmonics generation? See lv2, ladspa and clap plugins, etc....
