### ISSUE TITLE
In version 0.29.1 on macOS, double-clicking on the title bar does not make the player zoom

### ISSUE THREAD

**Issue by yan12125** [mpv-player/mpv#6223]
### mpv version and platform

* mpv 0.29.1 built from source. Configuration flags can be found at https://github.com/macports/macports-ports/blob/7e33a86819a2579cc99f941362148e2f0f959d41/multimedia/mpv/Portfile#L66
* macOS Mojave
* Screen resolution: 1440x900
* Hardware: MacBookAir7,2
* The value of System Preferences -> Dock -> "Double-click a window's title bar to" is "zoom"

### Reproduction steps

1. Play a video file
2. Double-click on the title bar

### Expected behavior
The player zooms to fit the screen size, but is still in the original screen. It's the behavior for my previous mpv version, 0.28.2.

### Actual behavior
It becomes full-screen.

### Log file

https://0x0.st/sEGE.txt

### Sample files
This issue should be reprodicible with any video file. In case you need the exact one I tested, I uploaded it here: https://dl.chyen.cc/%e6%a1%83%e8%8a%b1%e7%b5%90.mp4

**Comment by Akemi** [comment]
fixed with #6225.
