### ISSUE TITLE
mpv 0.29.1 creates smaller video window

### ISSUE THREAD

**Issue by eblanca** [mpv-player/mpv#6230]
### mpv version and platform
Using mpv release 0.29.1 on Linux Mint Debian Edition 3 (aka Cindy) 64 bit.
Hw: intel core i5 6200u including HD520 graphics with external Radeon HD 8670A/8670M/8690M / R5 M330 / M430 (this reported by lshw)

### Reproduction steps
System booted clean, I open the terminal, then attach a secondary display.
Drag the terminal into the (larger) secondary display and run mpv.

### Expected behavior
I expected the video to be showed as large as the screen allows (mplayer did).

### Actual behavior
The video window is created as small as it was showed into the primary smaller display.

### Log file

[mpv_stranezza.log](https://github.com/mpv-player/mpv/files/2499598/mpv_stranezza.log)

**Comment by lachs0r** [comment]
Your log file indicates that your window manager is resizing the window.
Does not seem to be mpv’s fault, but probably a bug in how the WM handles 
aspect ratio hints (it wouldn’t be the first time some GNOME-related WM fails 
to do it correctly). Try --no-keepaspect-window.

**Comment by eblanca** [comment]
Mmmhhh, no. This new log is from a mpv run with same options as above, adding '--no keepaspect-window' but the window size still is far from the display size. Not a critical bug, indeed, just annoying one
[mpv_no_window_resize.log](https://github.com/mpv-player/mpv/files/2507406/mpv_no_window_resize.log)
.

**Comment by eblanca** [comment]
Thank you
