### ISSUE TITLE
mpv dynamic library static links libswft* libraries

### ISSUE THREAD

**Issue by gazsiazasz** [mpv-player/mpv#6232]
### mpv version and platform
0.29.1

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Build the dylib and drop into a swift project.
### Expected behavior
The project compiles without a bunch of warning messages.
### Actual behavior
The project compiles with a bunch of warning messages.
### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Akemi** [comment]
a log file of configure and build would have been nice.

**Comment by gazsiazasz** [comment]
Hi Akemi,

here is the log file from the build:

https://0x0.st/s6MN.txt

and a bunch of warning messages like this one in Xcode:

`objc[12778]: Class _TtCE6AppKitVSo17NSAnimationEffectP33_9E6F1C1DB126EBCC5B18B8BAC8A387CC26_CompletionHandlerDelegate is implemented in both /Users/gazsiazasz/Library/Developer/Xcode/DerivedData/VideoPlayerTest-cjvrkagsppqdmtgfutlhvywwfdzc/Build/Products/Debug/VideoPlayerTest.app/Contents/Frameworks/libswiftAppKit.dylib (0x102c05b98) and /Users/gazsiazasz/CLionProjects/untitled/x86_64/lib/libmpv.1.dylib (0x101e5a148). One of the two will be used. Which one is undefined.`
