### ISSUE TITLE
[CRASH] segfaults on some flv file

### ISSUE THREAD

**Issue by hiiamboris** [mpv-player/mpv#6233]
### mpv version and platform
`mpv 0.29.0-66-g0f3e25cb0a`
`Win7 x64 [Version 6.1.7601]`

Detected on an older build, tried latest w64 builds:
This one https://mpv.srsfckn.biz/mpv-x86_64-20181002.7z
And this https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20181019-git-0f3e25c.7z/download

### Reproduction steps
just play the file

### Expected behavior
avplay/ffplay both work fine latest versions

### Actual behavior
it tries to read from unallocated memory and crashes before playing anything at all

### Log file
https://pastebin.com/vqthrhu9

### Sample files
http://0x0.st/s6PD.flv

**Comment by shinchiro** [comment]
If you've used my build, grab the [debug symbols](https://sourceforge.net/projects/mpv-player-windows/files/debug-symbol/) for that binary and scroll down to the bottom for instruction on how to catch the segfault

**Comment by hiiamboris** [comment]
ok thanks for the tip @shinchiro ☺
here's the result: https://pastebin.com/nrvCtY7e

**Comment by jeeb** [comment]
Thanks for the help, although I'd prefer a full back trace from gdb (you can get the binary I usually use from [here](https://kuroko.fushizen.eu/random/gdb_builds/gdb-8.0.1.7z)).

Quickstart:
1. `gdb mpv`, wait for it to tell you if it was able to load the debug symbols. Stop if the debug symbols were not loaded.
2. `run --your --params` , starts mpv with those parameters.
3. Wait for it to do this.
4. `bt full` gives full backtrace.

**Comment by jeeb** [comment]
I will, of course, attempt to repro this myself as well. Interesting how you're using the direct3d renderer.

**Comment by hiiamboris** [comment]
@jeeb good guess. Just tried, `vo=gpu` - works okay. I have `vo=direct3d` in my config, probably left from the times when it was either that or `opengl-hq` which was buggy or slow or smth.

**Comment by hiiamboris** [comment]
@jeeb for what it's worth - https://pastebin.com/LzEWsvwQ

**Comment by Dudemanguy** [comment]
Ancient one, but this crash looks like it's in ffmpeg? Closing it for now. Feel free to make a new issue if this is still a problem.
