### ISSUE TITLE
wayland: use presentation-time

### ISSUE THREAD

**Issue by emersion** [mpv-player/mpv#6236]
On Wayland, the [presentation-time](https://github.com/wayland-project/wayland-protocols/blob/master/stable/presentation-time/presentation-time.xml) protocol allows to request feedback about the precise timestamp at which a frame has been displayed (from the GPU driver). It also exposes the number of nanoseconds till next vsync.

All this information could probably be used for [display-sync](https://github.com/mpv-player/mpv/wiki/Display-synchronization#display-sync).

(Probably somewhere near: https://github.com/mpv-player/mpv/blob/802f594a857c703ac88e946d14b69cd3b6eb6006/video/out/vo.c#L475)

Some relevant commits:
* vo_gpu: glx: use GLX_OML_sync_control for better vsync reporting https://github.com/mpv-player/mpv/pull/6158/commits/e2e795cbae8c9b0877e3777f2f589e9c429d44e8
* vo, vo_gpu, glx: correct GLX_OML_sync_control usage https://github.com/mpv-player/mpv/pull/6158/commits/54f1669d1daeb37413a9e8555dd721fef1fc841a
* vo: use a struct for vsync feedback stuff https://github.com/mpv-player/mpv/pull/6158/commits/5642d19a33d226b0dd9b954bc286b2f9e891fad4

**Comment by atomnuker** [comment]
This is where you'd feed the information to:

https://github.com/mpv-player/mpv/blob/802f594a857c703ac88e946d14b69cd3b6eb6006/video/out/vo.c#L870-L876

**Comment by emersion** [comment]
Ah, thanks. I'll look into this.

Note that you also get the vsync sequence number, which is useful to know when you drop some vsyncs.
