### ISSUE TITLE
Seeking forward in web video but no new request to server

### ISSUE THREAD

**Issue by jiangzihao** [mpv-player/mpv#6238]
### mpv version and platform

version: 0.29.1
platform: Windows 10 1803

### Reproduction steps
options:
--force-seekable=yes
--hr-seek=yes
--msg-level=all=trace

I built a file server which supports range request, when I was using mpv to watch the video on it and seeking forward, there's no new request to my server depends on the log from my server, it seems still keep caching and play until it has cached my seeking position. But when I try to seek backward, my server's log shows that mpv would send a new request.

### Log file

[Log File](http://0x0.st/s6TM.txt)

**Comment by Akemi** [comment]
if this problem still persists, please open a new issue.
