### ISSUE TITLE
Use firequalizer as audio equalizer in mpv 

### ISSUE THREAD

**Issue by rayandben2000** [mpv-player/mpv#6239]
I read issues #6210 and ffmpeg document.
I try to use firequalizer as audio equalizer in mpv.

I set audio equalizer with mpv on command line like this, and it's example in ffmpeg document
`./mpv -video=no -af firequalizer=gain_entry='entry(1000,0); entry(1001, -INF)'` GOLD.mp3

But it not work, and show error message like this:
`Error parsing option af (option parameter could not be parsed)`
`Setting commandline option --af=firequalizer=gain_entry=entry(1000,0); entry(1001, -INF) failed.`

I looked at documentation and couldn't figure it out.
Thanks to anybody who replies.

**Comment by sfan5** [comment]
`mpv -af "lavfi=[firequalizer=gain_entry='entry(1000,0); entry(1001, -INF)']" file.mp3`

**Comment by rayandben2000** [comment]
It's work!
Thank you for your reply.
