### ISSUE TITLE
How to configure MPV to play lower resolution of network stream other than YT?

### ISSUE THREAD

**Issue by ZaxonXP** [mpv-player/mpv#6242]
### mpv version and platform

latest from Debian 9.5 stretch

mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.58.100
   libavcodec      57.89.100
   libavformat     57.71.100
   libswscale      4.6.100
   libavfilter     6.82.100
   libswresample   2.7.100
ffmpeg version: 3.3.8

### Reproduction steps
My `~/.config/mpv/mpv.conf` has such entry

`ytdl-format=bestvideo[height<=?480][fps<=?30][vcodec!=?vp9]+bestaudio/best`

This works with youtube videos displaying me the max 480p high videos (I have old netbook with 1024x600 screen resolution). However it does not display the lover resolution for the CDA.PL videos.

1) try with YT videos: `mpv https://www.youtube.com/watch?v=xLCn88bfW1o`
2) try with CDA videos: ` mpv https://www.cda.pl/video/269311815`

There are lower resolution versions on CDA.PL. If I check the video with `youtube-dl -F` I got such results:

`youtube-dl -F https://www.cda.pl/video/269311815
[CDA] 269311815: Downloading webpage
[CDA] 269311815: Downloading 720p version information
[CDA] 269311815: Downloading 1080p version information
[info] Available formats for 269311815:
format code  extension  resolution note
lq           mp4        480p       
sd           mp4        720p       
hd           mp4        1080p      (best)
`

I think it is matter of configuration on mpv.config file, but I could not find what to put there to make both YT and CDA.PL videos be retreived in 480p format.

### Expected behavior
1) Plays 480p
2) Plays 480p

### Actual behavior
1) Plays 480p
2) Plays 1080p

### Log file

1) `mpv https://www.youtube.com/watch?v=xLCn88bfW1o
Playing: https://www.youtube.com/watch?v=xLCn88bfW1o
 (+) Video --vid=1 (*) (h264 854x480 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) 'DASH audio' (opus 2ch 48000Hz) (external)
AO: [pulse] 48000Hz stereo 2ch float
VO: [opengl] 854x480 yuv420p
AV: 00:00:01 / 00:03:14 (0%) A-V:  0.000 Cache:  1s+0KB
`

2) `mpv https://www.cda.pl/video/269311815
Playing: https://www.cda.pl/video/269311815
 (+) Video --vid=1 (*) (h264 1920x1080 29.970fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 1920x1080 yuv420p
AV: 00:00:00 / 00:06:10 (0%) A-V:  0.470 Dropped: 9 Cache:  0s+0KB
`

### Sample files
1) mpv https://www.youtube.com/watch?v=xLCn88bfW1o
2) mpv https://www.cda.pl/video/269311815

**Comment by paulguy** [comment]
bestvideo+bestaudio are for selecting separate video and audio only tracks, which that stream doesn't use, so it just falls back to the next one, being "best".

**Comment by ZaxonXP** [comment]
so what should I have instead to only lower the video resolution?

**Comment by paulguy** [comment]
If you want the audio stream of a higher quality one and the video stream of a lower quality one, you're stuck downloading both of them then remuxing the audio and video together in to another file.  Youtube-dl can only download the full muxed audio+video streams from that site and the site may only provide streams in that form.

**Comment by sfan5** [comment]
you can apply the same options to the "best" part of the format string
<pre>
ytdl-format=bestvideo[height<=?480][fps<=?30][vcodec!=?vp9]+bestaudio/best[height<=?480][fps<=?30]
</pre>

**Comment by ZaxonXP** [comment]
I discovered that the example video I gave from CDA.PL had 720p resolution but the metadata has info about 480p. So it was working from beggining. The better sample is here `mpv https://www.cda.pl/video/269515507`

But I found what the `/` means and now I can list more alternative formats to try before mpv will give up. 

Thanks for helping!
