### ISSUE TITLE
mpv.app warns that it requires Mac OS X 10.12 or later when launching on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by kkdd** [mpv-player/mpv#6245]
Hello,
Is it intended that mpv.app warns ``` mpv.app requires Mac OS X 10.12 or later``` when launching on Mac OS X 10.11.6?

### mpv version and platform

mpv and mpv.app are installed as follows:

```console
$ brew install --with-bundle mpv
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
$ mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Thu Oct 25 20:30:41 JST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0.2
```
 
 
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

When launching mpv.app, it warns ```mpv.app requires Mac OS X 10.12 or later```.

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Cpuroast** [comment]
It's possible that the brew version of mpv requires 10.12+

You could try the pre-built binary for macOS from: https://mpv.io/installation
which is "built on macOS 10.12 (sierra) with OS X 10.10 (yosemite) as minimum requirement"

**Comment by Akemi** [comment]
i can't reproduce this with stolendata's builds. my guess, since i have no way of telling how your bundle was built, it's #5771 again. so not our bug.

otherwise it's a build error since the deployment target was set wrongly.
