### ISSUE TITLE
#6029 is not merged into master

### ISSUE THREAD

**Issue by dantas** [mpv-player/mpv#6247]
https://github.com/mpv-player/mpv/blob/ba2dee38fbd33adcb5405e0726f5baaa75128ccc/waftools/generators/sources.py#L97

The following pull request was not merged into master. We had to manually apply it in order to compile libmpv on OSX with static linking.

#6029 

@Akemi I believe that the merge failure has been forgotten so I'm just bumping this issue to remember that it should probably be brought back into master/develop

**Comment by Akemi** [comment]
for such things it's probably better to poke us on irc in the dev channel. it hasn't been forgotten, looking at PRs just takes a bit more time atm.
