### ISSUE TITLE
"focus" command and/or property

### ISSUE THREAD

**Issue by vankasteelj** [mpv-player/mpv#6252]
Hi, 

I would love for this player to have a command or a property allowing to set the "focus" to the rendering window.

I know this is possible with other applications (example: http://docs.nwjs.io/en/latest/References/Window/#winfocus), and it is extremely useful when using CLI or spawning MPV (binaries, not the lib) from another program.

Is such a feature possible?

**Comment by Akemi** [comment]
it depends on the platform but in general it would be possible. whether anyone wants to implement it is another thing though.

**Comment by vankasteelj** [comment]
Yep, but if this can stay open, it maximizes the chances though. I sadly don't know any C to make it happen myself

**Comment by Akemi** [comment]
i don't plan to close it, otherwise i wouldn't have tagged it as a feature request.

**Comment by Dudemanguy** [comment]
I think this was implemented in all the relevant platforms (x11, wayland, win32, and mac).
