### ISSUE TITLE
"mp_write_watch_later_conf" should not be based on the source of the stream

### ISSUE THREAD

**Issue by vankasteelj** [mpv-player/mpv#6253]
### mpv version and platform
win32 (x64), latest windows build from your website (0.29 31/07/2018)

### Reproduction steps
1. use `--save-position-on-quit` 
2. play a downloading "myfile.mkv" file (let's say your hosting it on `localhost:9000` while downloading). 
3. quit that, and download "myfile2.mkv" (that's also hosted on `localhost:9000` while downloading).

### Expected behavior
"myfile2.mkv" will start at 00:00:00 as it has never been played before

### Actual behavior
"myfile2.mkv" starts at the time I stopped watching "myfile.mkv"

### More
I'm assuming that this happens because both sources are `localhost:9000`. But they are not similar at all. 

proposition: 
- MPV should not base its "watch_later" MD5 files on the source, but take in account more factors, like the total time, the bitesize (unless the bitesize of a stream is always the same... idk), or even the title (forced with `title` and `force-media-title` in my case). So you don't have this kind of problem, mistaking two different things that just happen to be played from the same source.

**Comment by lvml** [comment]
The example source `localhost:9000` you mentioned is exactly one where information like "total time" "the bytesize" or a "title" may not be available or unique to a specific content at all.
mpv cannot know if the URL you provided refers to one specfic, persistently stored video - rather than some live-stream or some arbitrarily changing content.

**Comment by wm4** [comment]
Yes, it's based on the URL. This is just how it works. Otherwise you'd have to create an unique ID of the file, which either would _also_ betray user's expectations, or would have false positives, or would make opening of _any_ URL slower, or would raise the complexity.
