### ISSUE TITLE
(windows) drag youtube link to mpv > how choose video format?

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#6254]
### mpv version and platform

quite latest+youtube-dl , windows 7

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

i am opening mpv and drag youtube link from browser into mpv window -
it starts streaming, but highest quality.

would like have option to insert into link code for choosing streaming quality like 360p for 7Mbit ADSL connection

### Expected behavior

play lower quality stream instead of best quality

### Actual behavior

plays best quality

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

![stream](https://user-images.githubusercontent.com/12947465/47607414-03a8c180-da20-11e8-80a1-03bd4e21235d.png)

**Comment by Skibicki** [comment]
To find formats use 'youtube-dl -F, --list-formats'. Use the format codes with the ytdl-format option of mpv. If this stops working, the format codes may have changed.
A detailed explanation is in this topic: https://github.com/mpv-player/mpv/issues/4241

**Comment by Skibicki** [comment]
This method does not need a terminal, the options can be added to a config file (mpv.conf) and mpv will always use them when dropping links. 
https://github.com/mpv-player/mpv/blob/master/DOCS/man/mpv.rst#configuration-files
https://github.com/mpv-player/mpv/blob/master/DOCS/man/mpv.rst#files-on-windows

**Comment by adisib** [comment]
If you don't want to mess with the config file either, this userscript looks like it may be of use:
https://github.com/jgreco/mpv-youtube-quality

**Comment by mrkapqa** [comment]
ok, thanks, with the Terminal it is doable, your link solved it for me

can be closed!

**Comment by mrkapqa** [comment]
> 
> 
> If you don't want to mess with the config file either, this userscript looks like it may be of use:
> https://github.com/jgreco/mpv-youtube-quality

thanks, i will try that out, too.
last time i tried .lua script for thumbnails in mpv it broke however the keybindings (eg. Cmd+T no longer made window Sticky; hope this can be avoided with this one)
