### ISSUE TITLE
Feature request: on top while playing

### ISSUE THREAD

**Issue by elahn** [mpv-player/mpv#6255]
```
--ontop-while-playing
    Makes the player window stay on top of other windows while media is playing.
```

While using mpv on Linux, I really miss this feature of MPC-HC on Windows. While watching, I do other tasks during unimportant sections and pause when I get to "the good stuff" or when I need the full screen/all my attention for the task.

**Comment by Akemi** [comment]
look at the [user scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts) in our wiki. there is a script called [ontop-playback](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/ontop-playback.lua).

**Comment by elahn** [comment]
Thank you! I missed those while looking around.
