### ISSUE TITLE
[vo/gpu] player using cuda by default even though cuda is not selected

### ISSUE THREAD

**Issue by dnmTX** [mpv-player/mpv#6256]
mpv 0.29.0-77-gba2dee38fb (latest build by @shinchiro as of 10.27.2018)
Windows 10 1607 LTSB x64

### Reproduction steps
Play any video with --vo=gpu --gpu-context=d3d11 --hwdec=d3d11va

### Expected behavior
not to see any CUDA errors in console or log file as CUDA hasn't been selected
### Actual behavior
![capture](https://user-images.githubusercontent.com/34774426/47610475-e96ce480-da1b-11e8-8fed-9e1b17f10e36.PNG)

Looks like there is a problem with the latest build,no such a errors in any of the previous bulds

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/2522331/log.txt)

### Sample files
There is a link in the log file that i used to test it.Not sure how long will be active though.

**Comment by philipl** [comment]
Nothing has changed in terms of hwdec selection. If you look through the log, you'll see that mpv probes all the hwdecs before choosing one (and this process is done whether you select a specific hwdec on the command line or use auto. It happens to be the case the the cuda hwdec is generating errors as part of the probe process, and you are seeing these. This is the first build with cuda/vulkan interop in it, and there were changes in how base hwdec loading happens, so it's possible there's something where it's trying to pop after an error and there's nothing to pop. I assume you don't have an NVIDIA gpu?

**Comment by philipl** [comment]
You do have an nvidia gpu. Looking at the code, I can clearly see why you get one of those errors, and I can reproduce it by faking a failure in the init code. The other one isn't obvious to me, but I'll try and do some adjustments to the error path here and we'll see what happens.

**Comment by dnmTX** [comment]
Thanks for looking in to it @philipl. Besides the mentioned error(s) the player is working fine on my end but just in case to report it,that's all.

**Comment by dnmTX** [comment]
@philipl,you mentioned that this is the first build with cuda/vulkan interop. Does that mean that i can do hardware acceleration with Vulkan or it's not yet implemented under Windows?

**Comment by philipl** [comment]
Yes. If you use vulkan as your gpu backend, you can use nvdec as your hwdec. It should work in the build you have.
