### ISSUE TITLE
How to always auto play videos

### ISSUE THREAD

**Issue by marconii2002** [mpv-player/mpv#6257]
Now when I drop or open using this script https://github.com/rossy/mpv-open-file-dialog new video if current video is paused new video is paused. I want play dropped or opened video if current video is paused. How to do this ?

**Comment by Akemi** [comment]
write a script for it.

**Comment by jgreco** [comment]
@marconii2002 this script should do it for you.

```
mp.add_hook("on_load", 5, function ()
    if(mp.get_property_bool("pause") == true) then
        mp.set_property_bool("pause", false)
    end
end)
```

https://github.com/jgreco/mpv-scripts/blob/master/unpauser.lua

**Comment by marconii2002** [comment]
@jgreco Thanks but I already write my own script 

```
function autoplay()
	if mp.get_property_bool("pause") then
		mp.set_property_native("pause", false)
	end
end

mp.register_event("file-loaded", autoplay)
```

**Comment by h633537** [comment]
reset-on-next-file=pause
