### ISSUE TITLE
(debian,powerpc64) garbled  video, segmentation fault upon <skip forward>

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#6259]
### mpv version and platform
mpv 0.29.0-80-g865627d , debian 7.11 powerpc64

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

i compiled mpv for debian on powerpc64,
however, screen image is garbled and playback would stop then skip forward or backward (segmentation fault) 

### Expected behavior

play normally

### Actual behavior

garbled video image,  stops playback when skip forward

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by mrkapqa** [comment]
https://drive.google.com/open?id=1fO14r5-3r64_SY7HHR3hFU9rSLpF3r_5

**Comment by CounterPillow** [comment]
Where's the log? Where's the full backtrace from the segfault? Nobody else owns ppc64 machines.

**Comment by mrkapqa** [comment]
https://drive.google.com/open?id=1ag6esmpUuODlJMwdec_eHV6xVLBIDehm

hope this is is any useful

one line is missing in the log i write it here namely

Speicherzugriffsfehler

**Comment by mrkapqa** [comment]
graphics card is 

geforce gtx 7800 256mb

**Comment by mrkapqa** [comment]
maybe it could work with an older version of mpv like 0.25?

**Comment by CounterPillow** [comment]
To know where the segfault happened, one would need a backtrace obtained with e.g. gdb.

The messed up video output is probably due to ppc64 endianness weirdness, I don't think an older version would help with that at all.

I recommend not using a 12 year old system.

**Comment by CounterPillow** [comment]
I've found someone who could test this on ppc64 on a PowerMac G5 and it works fine with a radeon card, so if you see any graphics issues that's likely the fault of nouveau.

**Comment by q66** [comment]
yep, this really seems like a nouveau brokenness; my powermac g5 has a geforce 6600 in it and was getting garbled video and segfaults with random videos (though not necessarily on seeking), changing to radeon fixed the problems

**Comment by mrkapqa** [comment]
thanks, this is good news.
the only option for pcie powermac g5's (if one likes to dualboot macosx and linux) seem the ati x1900 then () which i tried already and unfortunately i very, very loud for my taste.
other option would be to use a geforce for macos and a newer ati/amd radeon for linux, probably. not optimal, but worth a try. has someone already tried a good newer ati/amd card which is supported on ppc linux?

**Comment by mrkapqa** [comment]
i meant, also the other geforce cards allow for dualbooting, of course, but to use radeon driver on linux and still allow for dualboot with macosx, it seems only ati 1900xt has been released as pcie option for the laters powermac g5's.
with the agp powermac's there is fortunately a bigger choice, 9600xt, 9650 xt ,9800xt or pro, x800 probably, but atleast with debian wheezy the 9600xt is a rather poor choice because the firmware is not really supported for the 3d acceleration (or i have not figured out how to get it properly working)

**Comment by CounterPillow** [comment]
This isn't a forum for your general tech troubleshooting questions, this is an issue tracker for the mpv project.
