### ISSUE TITLE
mpv not opening youtube links

### ISSUE THREAD

**Issue by engraze** [mpv-player/mpv#6265]
### mpv version and platform

I have the latest mpv (built with https://github.com/mpv-player/mpv-build) and youtube-dl downloaded from pip. I am running this on Ubuntu Mate 18.04.1 LTS 64-bit, 4.15.0-38-generic kernel.

mpv can't open links directly but it sort of work if I read the output with mpv
( `youtube-dl -o - https://link.com/ | mpv -` )
unfortunately, this means i can't choose quality without downloading the entire file and having to wait for it to dl. that or I can stream some shitty quality version

> **$ mpv -V**
> mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
>  built on Wed Oct 31 17:36:05 WET 2018
> ffmpeg library versions:
>    libavutil       56.21.100
>    libavcodec      58.34.100
>    libavformat     58.19.102
>    libswscale      5.2.100
>    libavfilter     7.39.100
>    libswresample   3.2.100
> ffmpeg version: N-92314-g323c2cfd38

> **$ youtube-dl --version**
> 2018.10.29

### Reproduction steps

mpv https://link-to-youube-video.com/

### Expected behavior

Launching mpv and streaming the video with youtube-dl.

### Actual behavior

"Failed to recognize format" assuming I'm pointing towards a file, I guess.

> **$ mpv "https://www.youtube.com/watch?v=-O5kNPlUV7w"**
> Playing: https://www.youtube.com/watch?v=-O5kNPlUV7w
> Failed to recognize file format.

### Log file

https://0x0.st/sIZH.log

**Comment by sfan5** [comment]
Your mpv is built without Lua, which is required for youtube-dl.

**Comment by engraze** [comment]
tried building it with lua5.3 which didn't work but lua5.2 did. thank you for that near-instant reply
