### ISSUE TITLE
Fonts not working on greek characters

### ISSUE THREAD

**Issue by peterthunder** [mpv-player/mpv#6267]
### mpv version and platform
Version: mpv-x86_64-20181027-git-ba2dee3
Platform: Windows 10

### Reproduction steps
I have a .mkv anime episode that contains .ass subtitles and the fonts do not work on the greek characters when using mpv.

### Expected behavior
How it should look like: https://cdn.discordapp.com/attachments/507680995311616000/507681693956571147/unknown.png
The font only works on the english characters.

### Actual behavior
How it actually looks like:
https://cdn.discordapp.com/attachments/507680995311616000/507681810734514176/unknown.png

### Log file
Log file can be found here: https://0x0.st/sIS8.txt

### Sample file
A sample of the video can be found here: https://mega.nz/#!tFYRSYKC!ennXFJ7osIvzisl4RGtNfS2syw0NQPwzV6b0R9KvPZo

**Comment by Akemi** [comment]
that's a [libass](https://github.com/libass/libass) problem. you have to report that to them.
