### ISSUE TITLE
JSON IPC: unproper serialization of double

### ISSUE THREAD

**Issue by Ryaler** [mpv-player/mpv#6269]
### mpv version and platform
0.29.1
### Reproduction steps
* Set system locale to any that uses a comma in double (de_DE.UTF-8)
* Get any double property (time-pos)
### Expected  behavior
`0.345`
### Actual behavior
`0,345`

**Comment by CounterPillow** [comment]
I also can't reproduce when I set `LC_ALL=de_DE.UTF-8`, using g104b510774

**Comment by Akemi** [comment]
same.
