### ISSUE TITLE
Weston: MPV does not hide Mouse Cursor

### ISSUE THREAD

**Issue by mweinelt** [mpv-player/mpv#627]
The mouse cursor stays visible during video playback on Weston.

weston 1.3.0
mpv 0.3.4-1

on Ubuntu 14.04

**Comment by simonbcn** [comment]
```
Arch Linux 
GNOME Shell 3.22.3 on Wayland
```

I have the same issue. This is the output of `WAYLAND_DEBUG=1 mpv...`: http://pastebin.com/7HCuE9W9
I have to move the mouse after it starts playing so that mpv hides the pointer.
