### ISSUE TITLE
Frame Drops with "video-sync=display-resample"

### ISSUE THREAD

**Issue by Nojevah** [mpv-player/mpv#6271]
### mpv version and platform
Shinchiro nightly Windows x64 build: 0.29.0.77 - 27/10/2018
Windows 10 x64 1803
Geforce 750

### Reproduction steps
First, I don't think it's a bug, but I prefer to ask here in order to understand:

1) Use "video-sync=display-resample"
2) Play this video: https://drive.google.com/open?id=1qiSbjLt3dTILnfhoQ-EHx1Dm786HABbb (85MB; temp link I'll removed when I'll get explanation)
Sorry, it is a Google Drive link. :/
3) Look at stats

### Expected behavior
No frame drops

### Actual behavior
I have frame drops

### Log file

https://pastebin.com/fv2jPrRX

### Sample files
Screenshots with dropped frames:
https://i.imgur.com/uAjvHU5.jpg

**Comment by dnmTX** [comment]
@Nojevah  yours is kind of fine,it's normal to see some frame drops at the beginning of the video when using d3d11(based on my observations).
It's much worse when using:
`gpu-api=vulkan`
`gpu-context=winvk`
`hwdec=nvdec`
`vulkan-swap-mode=fifo`
combined with:
`video-sync=display-resample`
![capture](https://user-images.githubusercontent.com/34774426/47936417-8fe93780-deab-11e8-8780-f89de9e8a167.PNG)

I might have to go back using d3d11 as the frame drops are not constant and the jitter is much less(when in full screen)

**Comment by Nojevah** [comment]
Let's close this. I guess it's the file which is badly encoded, since I haven't met another video having the same behavior.
