### ISSUE TITLE
Allow users to change default OSC Interface mousebindings via config

### ISSUE THREAD

**Issue by Jtasiu** [mpv-player/mpv#6291]
From what I can see there isn't an easy way to control or change the default OSC Interface keybindings/mousebindings. Options for changing the mousebindings for these would be very helpful

**Comment by wiiaboo** [comment]
There is not, at the moment.
What would you change them to?

**Comment by Jtasiu** [comment]
For my use I would like to change all the bindings that require shift+click (which requires using keyboard and mouse) to just use the mouse such as middle button click or mouse side button clicks.

**Comment by wiiaboo** [comment]
This could be left as a feature request, but I could add mbtn_mid as alias to shift+mbtn_left meanwhile. How's that?

**Comment by Jtasiu** [comment]
Sure, that works for me.

**Comment by zaza42** [comment]
There is a script for this: https://github.com/wiiaboo/mpv-scripts/blob/master/zones.lua
