### ISSUE TITLE
Audio params showing as unavailable

### ISSUE THREAD

**Issue by sebast889** [mpv-player/mpv#6293]
### mpv version and platform

Using shinchiro version on WIN

### Expected behavior

Put ${audio-params/samplerate} for example on a key bind in input.conf. When that key bind is toggled it should output the audio sample rate.

### Actual behavior

Put ${audio-params/samplerate} for example on a key bind in input.conf.  When that key bind is toggled it shows as unavailable/error. None of the audio-params options/properties work

**Comment by zc62** [comment]
https://mpv.io/manual/master/#command-interface-show-text
`a show-text ${audio-params/samplerate}`

**Comment by sebast889** [comment]
Interesting, just tried and it seems:

`a show-text ${audio-params/samplerate}` works
but
`a cycle audio ; show-text ${audio-params/samplerate}` doesn't work

**Comment by Akemi** [comment]
it shows `unavailable`. i guess the samplerate is not yet available after immediately switching audio. probably possible to do it with a script.

**Comment by Dudemanguy** [comment]
There doesn't appear to be any bug here. Simply that you tried to access the property before it was available.
