### ISSUE TITLE
Allow scripts-opts in multiple lines

### ISSUE THREAD

**Issue by sebast889** [mpv-player/mpv#6294]
Currently if you use the `scripts-opts=...` in mpv.conf it only allows the options to be specified in this one line. 

Please allow multiple scripts-opts= lines to take effect so that specific scripts-opts can be used in different profiles as well as easier reading of the options.

**Comment by wiiaboo** [comment]
Use `-add` and/or `-append`: https://mpv.io/manual/master/#list-options

**Comment by sebast889** [comment]
It works when doing everything globally but for some reason it doesn't work for me when doing the following in mpv.conf:

script-opts-append=osc-layout=box #globally

[extension.mp4]
script-opts-append=osc-layout=bottombar

When I play a .mp4 it still shows the box layout

**Comment by wiiaboo** [comment]
I think you can't change OSC options after opening the player, since the OSC script reads them only once at the start. It works with ytdl_hook because it's run on-demand, not constantly like the OSC.

**Comment by sebast889** [comment]
But if they're defined in mpv.conf shouldn't all options in it be read at the start? Or are profile settings interpreted differently that they are read after player start?

**Comment by wiiaboo** [comment]
I haven't read the code, but I'd assume the options in a profile aren't applied at the start, only after you've opened a .mp4.

**Comment by sebast889** [comment]
In that case can I request for script-opts to be applied at the start so that profiles can make use of specific script-opts that are set before opening the media file? Unless it is too big a design change..
