### ISSUE TITLE
[extension.~mp4] type option

### ISSUE THREAD

**Issue by sebast889** [mpv-player/mpv#6295]
Is it possible to have a `[extension.~mp4]` option? That is that anything under this is applied to all extensions except mp4. I'm currently creating multiple `[extension.xxx]` profiles with specific settings I want to apply to common media/other files but not a certain extension like .mp4 but it is messy and makes my mpv.conf a lot longer with lot of redundancy since I can't use a  [extension.~mp4]` like option.

**Comment by wiiaboo** [comment]
Set the option globally and then override it in [extension.mp4]?

**Comment by sebast889** [comment]
What if the option is something that is custom and not a yes/no one?

Say I set `title=random text' globally. How would I set the default `title=` mpv uses for the profile [extension.mp4]?

**Comment by sebast889** [comment]
What if the option is something that is custom and not a yes/no one?

Say I set title=random text globally. How would I set the default title= mpv uses for the profile [extension.mp4]?

**Comment by wiiaboo** [comment]
Use autoprofiles.lua, probably. If you're creating that many profiles you might as well be using it.

**Comment by sebast889** [comment]
The reason I created those profiles is because I want everything except [extension.mp4] to have the same specific settings not because I want those profiles. A global set option and one override option in [extension.mp4] like you said is what I would want but it only works with options that have a easy yes/no override rather than those with custom titles where I want [extension.mp4] to fallback to mpv default rather than the global set option (like the title example above). Not sure how autoprofiles would help here since I want to use less profiles (preferably only [extension.mp4] where the settings would differ from the global settings)..

**Comment by haasn** [comment]
True, but that means we could also solve this problem by adding a way to "unset" options.

In this case you can just set `title=${?media-title:${media-title}}${!media-title:No file} - mpv` manually, since that's the default setting. (Might need some extra escaping, haven't tested)

**Comment by sebast889** [comment]
Title was just an example but it can also be options which mpv doesn't use by default (like filters). An unset option would definitely be a good addition it would solve this. Something like `optionname=unset` to fall back to using mpv default setting if applicable or if mpv doesn't have a default setting for the optionname it will not use that option at all (e.g. if vf=randomfilter is set globally but under [extension.mp4] there is vf=unset the vf=unset will take priority and since mpv doesn't have a vf=... setting by default no vf option will be applied)

**Comment by zc62** [comment]
`--vf-clr`: https://mpv.io/manual/master/#video-filters-vf-clr
