### ISSUE TITLE
Source files in other directories don't work in EDL files

### ISSUE THREAD

**Issue by mattsches** [mpv-player/mpv#6297]
### mpv version and platform

0.29 on Ubuntu Linux 18.04

### Reproduction steps

Contents of `/home/mattsches/mpv/playlist.edl`
```
# mpv EDL v0
/home/mattsches/mpv/podcast.mp3,0,1,timestamps=chapters
/home/mattsches/music/artist - album/01 - artist - song.flac
/home/mattsches/mpv/podcast.mp3,1,2,timestamps=chapters
```

```bash
$ cd /home/mattsches/mpv
$ mpv playlist.edl
```

### Expected behavior
Play first chapter of podcast, then play song, then play second chapter of podcast.

### Actual behavior

```
Playing: playlist.edl
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: stream 0, timescale not set
[file] Cannot open file './01 - artist - song.flac': No such file or directory
Failed to open ./01 - artist - song.flac.
EDL: Could not open source file './01 - artist - song.flac'.
No video or audio streams selected.


Exiting... (Errors when loading file)
```

### Log file

https://0x0.st/sIRL.txt

**Comment by mc4man** [comment]
From /usr/share/doc/mpv/edl-mpv.rst.gz
`` Usage of relative or absolute paths as well as any protocol prefixes may be
    prevented for security reasons.``

From demux_edl.c  line 335
// For security, don't allow relative or absolute paths, only plain filenames. 
// Also, make these filenames relative to the edl source file.
ect..

**Comment by mc4man** [comment]
`` how could I not see this? ``
Well it's not in the man page, you'd need to look in /usr/share/doc/mpv for other included docs
(any decent text editor can open .gz files without extracting.

**Comment by mattsches** [comment]
Or here https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst ;)

**Comment by mattsches** [comment]
> You can try `mpv --playlist playlist.edl`

No, this does not work at all.

**Comment by haasn** [comment]
Oh, I see - EDL isn't a playlist format, it's a "virtual file" format.
