### ISSUE TITLE
Warning about deprecated options in a `.pls` stream

### ISSUE THREAD

**Issue by chrisfinazzo** [mpv-player/mpv#6298]
### mpv version and platform

0.29.1 (macOS 10.13.6)

### Reproduction steps

I have a line in my `.bash_aliases` which is simply used to play a `.pls` stream. Invoking this alias plays the stream.

### Expected behavior

The stream loads and plays.

### Actual behavior

The stream plays, but there are a number of deprecations which also appear. I am using mpv via Homebrew, so I  don't _think_ I have a config file to share. Do these options need to be removed in a future version of mpv?

### Log file

[log file](https://0x0.st/sI7Y.txt)

**Comment by Akemi** [comment]
the file in our repo is up to date, if it's just the file on your system.

see https://github.com/mpv-player/mpv/commit/a469554594759c7833630b81b312efa5f4c0924a.
