### ISSUE TITLE
Error decoding audio with --audio-channels=<2 and EAC3

### ISSUE THREAD

**Issue by m0qui** [mpv-player/mpv#6300]
### mpv version and platform
- 0.29.1, compiled with ffmpeg-release (4.1) and mpv-release
- git 2018.11.04.317d3ac, compiled with ffmpeg-master and mpv-master
- on Ubuntu Xenial 64bit (latest updates)

### Reproduction steps
Play file with EAC3 audio (MKV container) and --audio-channels=2 or --audio-channels=1 (works just fine with --audio-channels>=3)

### Expected behavior
Sound.

### Actual behavior
Silence and "Error decoding audio." in log (both 0.29.1 and 2018.11.04.317d3ac)

### Log file
https://0x0.st/slii.txt (v0.29.1)
https://0x0.st/sli_.txt (git 2018.11.04.317d3ac)

### Additional information
Works fine on 0.29.1 and git 2018.11.04.317d3ac with --audio-channels>=3; and mpv 0.28.0/ffmpeg N-89595-g40d4b13 with --audio-channels=n

**Comment by cdown** [comment]
I'm also experiencing the same issue, please let me know if there's anything I can do to help debug.

**Comment by DaarkWel** [comment]
Same here. Any news about repairing?

**Comment by wm4** [comment]
Try to bisect the mpv or ffmpeg version that causes this, post media sample.

**Comment by DaarkWel** [comment]
I don't know how to bisect, sorry.

Media sample: http://www.filedropper.com/eac3test

**Comment by wm4** [comment]
Please use one of the recommended ways to upload sample files.
I hate these dumb near-criminal sites.

**Comment by DaarkWel** [comment]
Where can I find recomendations for upload samples? I didn't notice it in wiki or readme.

**Comment by wm4** [comment]
Right, we only list https://0x0.st/ in our issue template. That should be good enough, but anything that has direct linking will work.

**Comment by DaarkWel** [comment]
ok, thanks. https://0x0.st/icAU.mka

**Comment by wm4** [comment]
Does this file contain silence only? (And some very low level noise.)

**Comment by DaarkWel** [comment]
Yes. But irrelevant, it produces "Error decoding audio" error.

**Comment by wm4** [comment]
Yes. Anyway, it seems to be libavcodec which returns this error, and we have no control over that.
You can use --ad-lavc-downmix=no to avoid this. I change the default of this option to no just now.
