### ISSUE TITLE
Control pan-and-scan by height and width 

### ISSUE THREAD

**Issue by Jtasiu** [mpv-player/mpv#6303]
The option to be able to control pan-and-scan by increasing/decreasing height and width separately using keybinds would be very useful especially when I want to watch a video that has hardcoded black bars and other methods like cropping, stretching or AR options don't work. As far as I know the current pan and scan options don't provide a way to do this. The MPC variants have this in their pan-and-scan settings if it helps to understand what function I'm asking.

**Comment by xingmiye** [comment]
I also want this feature because I just want to stretch only in height or only in width with very little value such as 0.01 by using hotkey.
There is a player called Potplayer which provide this feature. We could use numpad 8 and 2 to increase/decrease height size, or use numpad 6 and 4 to increase/decrease width size. It's very useful.

**Comment by wm4** [comment]
What is this useful for? I mean, it'd be trivial to implement, but I really fail to see what for.

**Comment by xingmiye** [comment]
> What is this useful for? I mean, it'd be trivial to implement, but I really fail to see what for.

I think it's more useful than the command "video-pan-x/y". Because there are many unprofessional video producer who produce the irregular videos. Some of videos might be stretch only in height or only in width. We need to fix when play these video.

**Comment by wm4** [comment]
There's normally shift+A for changing the aspect ratio though.

**Comment by xingmiye** [comment]
> There's normally shift+A for changing the aspect ratio though.

Shift+A just for the common aspect ratio. I found the aspect ratio in some videos actually are 16:8.7, or 16:8.5, or 16:8.8, or 16:8.3, but export within 16:9 in order to make the people in the video looks taller. But I think it's irregular and I want to fix them.

**Comment by wm4** [comment]
I could implement it as multiplicator (i.e. linear) for the video size, with separate options for width/height. Does that sound good?

**Comment by xingmiye** [comment]
Thank you very much

**Comment by wm4** [comment]
Implemented. You need to add key bindings yourself.

**Comment by xingmiye** [comment]
> Implemented. You need to add key bindings yourself.

Thank you! It's works now. Thank you very much!
