### ISSUE TITLE
Options from filedir-conf doesn't overwrite the same options from current profile

### ISSUE THREAD

**Issue by YurikaL** [mpv-player/mpv#6306]
### mpv version and platform

mpv 0.29.1, Arch Linux

### Reproduction steps

- Create a profile in the default user `mpv.conf` file and add some options to this profile. For example: 
```
[Extra]
screenshot-directory="~/Images/Screenshots/Extra"
```
- Also add `use-filedir-conf=yes` to the same profile.
- Open a directory with video files and place another `mpv.conf` into this directory.
- Add to that filedir config the same option that was added to the previously created profile, but with another value. For example `screenshot-directory="~/Images/Extra/filedirScreens"`
- Play video from this directory with mpv using this `[Extra]` profile.

### Expected behavior

All values from filedir `mpv.conf` will overwrite any other values of the same options, including options from current profile. So in example listed above screenshots from videos in this directory will be placed in `~/Images/Extra/filedirScreens`

### Actual behavior

Only those values from filedir `mpv.conf` are used, which options are not present in the current profile. Options that match those contained in profile are ignored, and values from the profile is still used instead. So screenshots in this example are placed in `~/Images/Screenshots/Extra`.

### Log file
https://0x0.st/slTT.txt
In this log `mute` option are loaded from filedir `mpv.conf`, but another two options are ignored, as described above.

### Sample files
[Default user `mpv.conf`](https://0x0.st/slTM.conf)
[Filedir `mpv.conf`](https://0x0.st/slTS.conf)

**Comment by haasn** [comment]
This is because the `--profile Extra` was put onto the command line, which is assumed to have the highest priority - above any configuration file. What you want is for the configuration file to take priority over the command line. You can just as easily put yourself into the shoes of somebody in the opposite scenario, who wants to override an option that comes from a config file using the command line. And I vote in favor of the latter. The command line *should* be the highest priority.

Maybe there's a better solution to your actual problem? Maybe you could try appending `--include=./mpv.conf` to your command line as well, after the `--profile=Extra`. It coming second will then cause it override the profile again. (In theory)

Alternatively, you could try using something like auto profiles or a lua script to set this option, since the logic you seem to want is obviously more complicated than what the vanilla profile system is equipped to handle.

**Comment by Hrxn** [comment]
> [..] And I vote in favor of the latter. The command line should be the highest priority.

Yes, definitely. Maybe an unwritten rule, but definitely a de facto standard of all software anywhere..

**Comment by YurikaL** [comment]
Well, I definitely agree that at least single command line options should be the highest priority. But passing command line options is the only common method to select a certain profile (besides auto-profiles), isn't it? So I want one specific configuration file to take priority over _another_, more general configuration file, not configuration file over the command line. In my example, I'm not trying to override the selected from command line profile **itself** - just some options including in this profile. In other words, I'm not trying to put `profile=somethingElse` into filedir config while `--profile=Extra` comes from the command line.

> Maybe you could try appending `--include=./mpv.conf` to your command line as well, after the `--profile=Extra`.

In my case, current working dir is not the same as directory with video files, so it unfortunately will not work for me.

...

Maybe mpv would handle profiles in filedir config files too? Something like:
```
[Extra]
screenshot-directory="~/Images/Extra/filedirScreens"
```
This hypothetical filedir config should override options only from `Extra` profile, if it selected - something like `profile-extra.conf.d`, which is another standart de-facto for (some) software. (Not the exact equivalent, though.)

**Comment by haasn** [comment]
A long time I once proposed a config system where the config structure itself would be "hierarchical", with the mpv base config / built-in defaults being at the top of the hierarchy and each subsequent layer below having the opportunity to either define an option (thus overriding the layer above it) or leaving it unset.

In such a world, one could easily imagine something like "config-priority=N" in a config file section giving that config file its own priority in this hierarchy. That could certainly solve your problem and many like it (e.g. extension-based profiles or auto-profiles having a too-high priority).

But actually implementing that would be a headache, and I think at this point the only person who once semi-understood the option code in mpv has gone inactive.

**Comment by Dudemanguy** [comment]
Looks like a workaround was found. As for overhauling how the config file works there's an old issue about it which I can't find at the moment but it's somewhere.
