### ISSUE TITLE
Discerning between Cache and Demuxer buffer

### ISSUE THREAD

**Issue by Gfurst** [mpv-player/mpv#6307]
### mpv version and platform

Archlinux
mpv 0.29.0-77-gba2dee38fb

### Understanding

Forgive me for opening an issue like this, since its mostly a question of better understanding the current system. But please feel free to discuss it as well.

The misunderstanding comes from meddling with these options, both the demuxer and cache ones. And don't get me wrong the default settings sure work fine for most people and use cases.

Part of the confusion I think comes from the default settings when streaming something, so cache comes on and so does the `cache-secs` option, which according to the descriptions is only limited to the `demuxer-max-bytes` option. Which is my first point about the confusion, on the pseudo interface the cache number and bar seems to be actually representative of the demuxer buffer, for whatever that means, and also a rather large value at default settings.

Another point is the use of the cache itself, and what the left fingerprint on memory is, on one specific test I've set both the cache to 32MiB and the demuxer for 32MiB, for forwards and backwards. Then mpv reported to me, in the detail info screen, that the cache totaled 48MiB, which just adds to confusion whether the cache add to the demux buffer, if it adds only to one direction, if the cache is kept despite the buffer, or whatever might be happening.

And my final point, is about what are real differences between keeping muxed or demuxed cache, which are the advantages and disadvantages about it. From what I can see at least, mpv can navigated seamlessly between either of them, so this is why I'm asking these points.

Again sorry if this was not a appropriate place for a question like, I just felt the documentation didn't quite explain it well. But my thanks for taking the in this regardless.

**Comment by Hrxn** [comment]
Not a comment on the question at hand, but I feel this might be an appropriate opportunity to remind the general public ("PSA") of the existence of a specific outlet for asking the mpv project questions of any kind:
The `#mpv` channel on `irc.freenode.net`.

**Comment by wm4** [comment]
The stream cache is gone, only the demuxer cache is left.
