### ISSUE TITLE
autoload.lua not working and mpv.exe not found running .bat

### ISSUE THREAD

**Issue by Silmarilias** [mpv-player/mpv#6308]
### mpv version and platform
mpv 0.29.1 build by lachs0r
Windows 10

### Actual behavior
First, autoload doesn´t seem to be working (not create any playlist).
Second, when I run mpv-install.bat as administrator shows "mpv.exe not found", although is on the same folder.

### Expected behavior
Create a playlist with autoload, and install mpv correctly.

### Log file
https://pastebin.com/q4DgxFgp

**Comment by bitingsock** [comment]
on line 25 of autoload there is a list of file extensions. make sure the filetype you are trying to load is in that list. also it will only files in the same directory level as the file you choose(i.e. doesn't search up or down directory levels.
(2)Can you provide a screen shot of your mpv folder?

**Comment by zc62** [comment]
```bash
[   0.039][f][autoload] Lua error: cannot open C:/Users/user/Programas/mpv 02-10-2018 (x64)/scripts/autoload.lua: No such file or directory
```
Not sure if it is related to #4903. Does the path `C:/Users/user/Programas/mpv 02-10-2018 (x64)/` contain non-UTF8 characters?

I'd suggest trying to put the entire mpv folder directly under `C:\`, making it something like `C:\mpv\`, and `mpv.exe` should be `C:\mpv\mpv.exe`. Then put `mpv.conf` and `scripts/` in `C:\mpv\portable_config`.

**Comment by Akemi** [comment]
seems like issue was solved.
