### ISSUE TITLE
Most of Live streams don't works anymore since iOS 12.1 (Sample project)

### ISSUE THREAD

**Issue by skrew** [mpv-player/mpv#6310]
### Reproduction steps
Play some (live) streams, audio fail, making video stop.

This problem only exists since iOS 12.1 (and actual iOS beta 12.1.x)
Tested with the same sample project, working fine on iOS 12.0 and earlier

It's look like something changed with AVAudioSession, which seem to kick out a session containing errors or maybe making too long time to start (i don't really know, have looked into, but without success)

If i start the stream without sound, it's works everytime.

In the same project, you have 3 test cases (line 188+ in ViewController.m)

Got errors, not always the same, like:

```
AVAudioSessionUtilities.h:112:GetProperty: AudioSessionGetProperty ('colt') failed with error: '!ini'
```
-> This mean AudioSession is not initialized, but it's a singleton now !

```
AudioSessionSetProperty_Priv is passing a serverPID of 0 to CheckRPCError!
```
-> This one is unknown from google !!!! :)

This is what you can see from sample project with main debug:
```
[cplayer] v: starting audio playback
[ao/audiounit] warn: can't start audio unit ([206][255][255][255]/-50)
[cplayer] v: playback restart complete
```

I'm digging for 2 days now, without success (working around ao_audiounit.m)

Thanks !

Edit: link removed, working now! 

**Edit 2: This problem only occur on a real device, that's works on simulator.**

**Edit 3: it's was the time parsing the stream. Issue closed (but i don't thanks Apple)**

**Comment by BarkhaArora** [comment]
how did you resolve this?
