### ISSUE TITLE
Could not create GLX context, floating point exception

### ISSUE THREAD

**Issue by theheen** [mpv-player/mpv#6312]
### mpv version and platform
v0.29.1, but git master also does not work.

### Reproduction steps
Try to play a file with mpv

### Expected behavior
File plays

### Actual behavior
```
$ mpv --log-file=mpvcrash.log /media/LargeStore/in/Movies/bbb_sunflower_1080p_60fps_normal.mp4
Playing: /media/LargeStore/in/Movies/bbb_sunflower_1080p_60fps_normal.mp4
 (+) Video --vid=1 (*) (h264 1920x1080 60.000fps)
 (+) Audio --aid=1 (*) (mp3 2ch 48000Hz)
     Audio --aid=2 (*) (ac3 6ch 48000Hz)
File tags:
 Artist: Blender Foundation 2008, Janus Bager Kristensen 2013
 Comment: Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
 Composer: Sacha Goedegebure
 Genre: Animation
 Title: Big Buck Bunny, Sunflower version
[vo/gpu/x11] X11 error: BadValue (integer parameter out of range for operation)
[vo/gpu/x11] Type: 0, display: 0x7f475027d5a0, resourceid: 0, serial: 67
[vo/gpu/x11] Error code: 2, request code: 96, minor code: 3
[vo/gpu] Could not create GLX context!
libEGL warning: DRI2: failed to authenticate
[vo/gpu/opengl] Suspected software renderer or indirect context.
[vo/gpu/x11] X11 error: BadValue (integer parameter out of range for operation)
[vo/gpu/x11] Type: 0, display: 0x7f475025d030, resourceid: 0, serial: 67
[vo/gpu/x11] Error code: 2, request code: 96, minor code: 3
[vo/gpu] Could not create GLX context!
[vo/gpu/vulkan] vkEnumeratePhysicalDevices(vk->inst, &num, NULL): VK_ERROR_INITIALIZATION_FAILED
[vo/vdpau] Error when calling vdp_device_create_x11: 1
Floating point exception (core dumped)
```
### Log file

https://0x0.st/slOb.log

### Sample files
Has worked with any file tried

**Comment by CounterPillow** [comment]
>[   0.131][v][vo/gpu/opengl] GL_RENDERER='llvmpipe (LLVM 7.0, 128 bits)'

why are you using software rendering?

**Comment by theheen** [comment]
> why are you using software rendering?

No idea. Here's logs from building the release using mpv-build if that helps any: https://0x0.st/slOL.log

**Comment by CounterPillow** [comment]
It's not an issue with the mpv build I think, but rather with your drivers. Did you update mesa without rebooting? I've seen that break OpenGL in the past.

**Comment by theheen** [comment]
Dang, that could be it. Fedora upgrade led to updating pretty much everything.

**Comment by haasn** [comment]
It's still a bug, I think?

**Comment by CounterPillow** [comment]
fwiw, when I do `LIBGL_ALWAYS_SOFTWARE=1 mpv --no-config --profile=gpu-hq --vo=gpu foo.mkv` I don't get any crash.

**Comment by haasn** [comment]
Same for me. Can't reproduce. Post a backtrace if you want us to investigate this further.
