### ISSUE TITLE
Unexpectedly quits when opening Itunes exported m3u8 with CR line endings

### ISSUE THREAD

**Issue by anohren** [mpv-player/mpv#6319]
### mpv version and platform

mpv 0.29.1
macos 10.14.1

### Reproduction steps
Open the attached playlists. One should crash, one should play. Compare them with tool of choice. 

They only have different line endings. The one that crashes was exported by itunes, and I removed all #EXTM3U info from it to illustrate that the problem exists even when only the line endings differ.

### Expected behavior
Both should play.

### Actual behavior
One plays, the other makes the application quit.

### Sample files

[sample playlists.zip](https://github.com/mpv-player/mpv/files/2585280/sample.playlists.zip)

**Comment by zc62** [comment]
I think this is pretty much expected. Without any `<LF>`, the whole file is considered as just one line, which surely breaks the playback.

> Many older Mac applications use "Mac-style” line endings. This means that each line in a text file ends with a carriage return character (character 13/0xD, often abbreviated CR).

What is your itunes version? If it is the latest, complain to apple. They should update itunes to let it use `<LF>` as the line ending when exporting plain text files.

**Comment by anohren** [comment]
Crashing on bad input is expected? Ok, that goal has been reached.

**Comment by zc62** [comment]
If you run mpv from the terminal, or enable the `log-file` option to really have a look at the log file, then you will find mpv didn't crash. It just could not resolve the bad url and decides to terminate the playback, since there is nothing else that mpv is told to do. Do you expect it staying idle if given broken input?

**Comment by anohren** [comment]
Yeah you're right that there's no crash reporting happening, etc. so I guess it's basically just quitting on its own without explanation. 

Yes, if the application has a window open with no file loaded — which seems to be a valid state — it should revert back to that state if the operation fails. Remaining open is what the app has been told to do when it was being launched. Otherwise it 1) assumes (incorrectly) that I want to quit immediately on error while in reality it just leaves me wondering what just happened, and 2) gives itself no opportunity to inform me that an error occurred at all.

**Comment by zc62** [comment]
That's probably because mpv is designed to be a CLI program. The user is expected to read the terminal output. Since it has no GUI, there will be no GUI notification about the errors. FYI, #5500

**Comment by anohren** [comment]
Thanks for the clarification and link.

> The user is expected to read the terminal output.

Can't argue with that. I guess I've been launching it wrong.
