### ISSUE TITLE
mpv window is unfocused upon starting up if hwdec is used (Windows)

### ISSUE THREAD

**Issue by transient-sepia** [mpv-player/mpv#6324]
### mpv version and platform

mpv 0.29.0-86-g880c59d189
Windows 10 Pro 1803

### Reproduction steps

When you use `hwdec` option (tested with `auto` and `d3d11va`), it makes mpv window unfocused upon starting up in Windows. Removing or commenting out that option fixes it.

### Expected behavior

Player window has focus.

### Actual behavior

Player window in unfocused and you have to click it to make it focused.

### Log file

https://hastebin.com/fipetodefe.md

### Sample files

N/A, this happens when you open any file.

**Comment by aufkrawall** [comment]
I suspect this is caused by something else at your end, I never had this with any hwdec on Windows 10.

**Comment by transient-sepia** [comment]
**aufkrawall**, thank you for your help, you were correct. Rivatuner Statistics Server was the culprit. Disabling application detection for `mpv.exe` fixed this inconvenience.
