### ISSUE TITLE
watch_later files when opening a directory

### ISSUE THREAD

**Issue by rightaway** [mpv-player/mpv#6325]
If I do `mpv file1 file2 file3` then the files in `watch_later` are as expected, but if I open a directory then I get many extra files saying "redirect entry" with each part of the path to the video, one part per file in watch_later.

I like to have a clean history in watch_later but sometimes it's easier to open a directory directly, for example when you're in a file explorer you can just right click on the directory (or the command line version for something like `ranger`) and send it to mpv and it'll start playing.

**Comment by dskrad** [comment]
+1

**Comment by wm4** [comment]
That's just how it is implemented, didn't find a better way.

**Comment by rightaway** [comment]
Obviously that's how it's implemented. Which is why I created the feature request. 🤦‍♂️
