### ISSUE TITLE
scaletempo is acting strangely.

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#6333]
I think that somehow the way scaletempo and audio-pitch-correction interacts has been changed (broken with my point of view).
It seems like now audio-pitch-correction, not only inserts scaletempo filter, when set to yes, but also make scaletempo ineffective if explicitely disabled.
One consequence is that now i'm unable to change pitch, while preserving tempo.

### mpv version and platform
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Oct  5 08:08:09 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: n4.0.3
```

### Reproduction steps
```
1) mpv --audio-pitch-correction=no --af-add=scaletempo=speed=pitch  mp3.mp3 -speed=2
2) mpv --audio-pitch-correction=no --af=scaletempo=speed=tempo  mp3.mp3 -speed=2
```

### Expected behavior
(According to manpage about scaletempo and audio-pitch-correction)
1) normal tempo, pitch doubled
2) double tempo, same pitch

### Actual behavior
1) double tempo, double pitch.
2) double tempo, double pitch.

### Log file
https://pastebin.com/a1e7g4E0

**Comment by kokoko3k** [comment]
Similar, don't know if the same, issue, happened 3 years ago:
https://github.com/mpv-player/mpv/issues/1653

**Comment by ManuelBarrioLinares** [comment]
There hasn't been an update to this issue. Am I right to assume there's no "only pitch" correction available in mpv?

**Comment by richardpl** [comment]
Build mpv with rubberband support

**Comment by kokoko3k** [comment]
Yes, with rubberband it works, but imho, it produces worse results; where scaletempo produces (imho not-audible) audio skips, rubberband gives you phasing artifacts.
So i'd really prefer scaletempo.

**Comment by richardpl** [comment]
scaletempo is awful from any point of view.

**Comment by kokoko3k** [comment]
Not the point of view of my ears  :)

**Comment by richardpl** [comment]
Have you tried all rubberband options for this phasiness you describe?

**Comment by kokoko3k** [comment]
I tested them extensively, but i still hear a sort of flanger.
Best results i've ever had with rubberband is by setting crisp transients, indipendent phase, long window.
that way i can get a clean sound, but unfortunately it doesn't work well with music, because as soon as there is a percussion sound, the sound seems to go down in amplitude for a little while, even with little pitch variations.
Scaletempo, on the other side works very whell where there are more sound mixed, but exposes his limits when there are long sounds that changes amplitude (i admit is really distracting in piano solos), because the algorithm is unable to find a right sample to cut in.
I think scaletempo and rubberband are complementary; by their nature they works better or worse depending on the content.

**Comment by richardpl** [comment]
You could play with atempo before/after asetrate,aresample combination to adjust audio pitch.

**Comment by kokoko3k** [comment]
Was this closed because the issue is actually fixed or because there's no intention to fix? I can't find any related commit.
In both cases, the man pages still states:
```
                 mpv --af=scaletempo=scale=1.2:speed=pitch audio.ogg
                        Would play media at 1.2x normal speed, with audio at normal pitch.  Changing playback speed would change pitch, leaving audio tempo at 1.2x.
```
...which is not what happens.

Also, from the man page:
```              speed=<tempo|pitch|both|none>
                     Set response to speed change.

                     tempo  Scale tempo in sync with speed (default).

                     pitch  Reverses effect of filter. Scales pitch without altering tempo.  Add this to your input.conf to step by musical semi-tones:

                               [ multiply speed 0.9438743126816935
                               ] multiply speed 1.059463094352953

                            WARNING:
                               Loses sync with video.

                     both   Scale both tempo and pitch.

                     none   Ignore speed changes.
```
...but the speed parameter seems to be completely ignored; all of the followings produces the very same output:
```
mpv audiofile.mp3  --af=scaletempo=scale=2:speed=both
mpv audiofile.mp3  --af=scaletempo=scale=2:speed=pitch
mpv audiofile.mp3  --af=scaletempo=scale=2:speed=tempo
mpv audiofile.mp3  --af=scaletempo=scale=2:speed=none
```
...which is: tempo doubled",pitch preserved
--audio-pitch-correction=yes|now does not change anything.

**Comment by Akemi** [comment]
it was closed because rubberband was suggested as a replacement and i did some issue grooming. if you feel that is not working out for you feel free to open a new issue.

**Comment by kokoko3k** [comment]
It is not that it is not working for me, it is that scaletempo just doesn't do what the man page states.

**Comment by Akemi** [comment]
then please open a new issue and your preferred way of fixing it.

you read that wrong. just imaging, i went trough 700 issues the past few days, reading the comments, trying to understand the problems, tagging them properly, finding duplicates, etc. it's possible that i closed some issues that might still be relevant. this also serves as a way to find out if people are still interested in the issues itself.

**Comment by kokoko3k** [comment]
Right, thanks for (all of you) your hard work then.

**Comment by orivej** [comment]
Looking at the source code it seems that:
1. User filters (`-af`, `-af-add`) form a [different](https://github.com/mpv-player/mpv/blob/v0.32.0/filters/f_output_chain.c#L481-L482) chain from the builtin filters (internal scaletempo), so the first `-af-add` without `-af` is equivalent to `-af`: either one adds the specified filters to the initially empty user chain.
2. `audio-pitch-correction=no` completely disables the effect of speed on user filters: they are configured with a constant speed of [1](https://github.com/mpv-player/mpv/blob/v0.32.0/player/audio.c#L62). You should keep `audio-pitch-correction=yes`: the builtin scaletempo will be effectively [ignored](https://github.com/mpv-player/mpv/blob/v0.32.0/filters/f_output_chain.c#L479) as long as any user filter can respond to a speed change. (The last such filter will be configured with the actual speed, the others with the speed of 1.)

**Comment by kokoko3k** [comment]
>     2. `audio-pitch-correction=no` completely disables the effect of speed on user filters: they are configured with a constant speed of [1](https://github.com/mpv-player/mpv/blob/v0.32.0/player/audio.c#L62). You should keep `audio-pitch-correction=yes`: the builtin scaletempo will be effectively [ignored](https://github.com/mpv-player/mpv/blob/v0.32.0/filters/f_output_chain.c#L479) as long as any user filter can respond to a speed change. (The last such filter will be configured with the actual speed, the others with the speed of 1.)

I'm not sure i understood, but changing pitch while retaining tempo is still impossible despite the argument given to audio-pitch-correction.
