### ISSUE TITLE
How to make mpv resize larger videos to monitor resolution?

### ISSUE THREAD

**Issue by catzybluphish** [mpv-player/mpv#6340]
I can make mpv play videos at their original resolution but if they're larger than my monitor height (e.g. video is 1100px high but monitor only 1080), they will overlap off the screen so the remaining 20px will not be visible. This wouldn't be the case if mpv was tiled (I'm using bspwm) but I've set mpv to always start as floating and tiling expands videos than my resolution so they'd look bad. Can I resize larger videos to the native resolution on start? I have nothing in my mpv config.
Cheers.

**Comment by CounterPillow** [comment]
`--autofit-larger`

**Comment by catzybluphish** [comment]
> `--autofit-larger`

Appreciate it!
