### ISSUE TITLE
Loop pauses between runs

### ISSUE THREAD

**Issue by graywolf** [mpv-player/mpv#6341]
### mpv version and platform

```
+   $ mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Thu Nov 15 11:19:15 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1

+   $ uname -a
Linux ws 4.19.2-arch1-1-ARCH #1 SMP PREEMPT Tue Nov 13 21:16:19 UTC 2018 x86_64 GNU/Linux

+   $ lscpu | grep 'Model name'
Model name:          Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz

+   $ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
```

### Reproduction steps

```
mpv --really-quiet --no-audio --loop-file=inf --no-stop-screensaver yoshino_screensaver_short.mkv
```

### Expected behavior

Video loops seamlessly without black pause.

### Actual behavior

Video has black screen for about 1s (my guess).

### Log file

Log file is made with `--msg-time` as suggested in #4066 since it's probably
same (or similar issue):

http://0x0.st/s01H.log

### Sample files

http://0x0.st/s01X.mkv

This mkv was created using ffmpeg (`mpeg -ss 0 -i yoshino_ending.mkv  -c copy -t 10 yoshino_screensaver_short.mkv`).

**Comment by CounterPillow** [comment]
FYI, it doesn't pause, you just have 1 second of black video at the start. Could be due to the stream copy producing a messy or broken file.

**Comment by graywolf** [comment]
Oh... sorry for wasting your time then. :/ You are right, when I do `-f segment` instead for the ffmpeg each part plays correctly (except start of first and end of last).
