### ISSUE TITLE
Slow start-up disables video-sync

### ISSUE THREAD

**Issue by daed-alus** [mpv-player/mpv#6342]
### mpv version and platform

mpv 0.29.1
windows 10 x64

### Reproduction steps
play a file with interpolation & video sync activated.
### Expected behavior
mpv plays the file without a warning and enables video sync & interpolation.
### Actual behavior
mpv immediately detects A-V desynchronization and disables display sync and so interpolation

```
[ 1.246][w][cplayer] Audio/Video desynchronisation detected! Possible reasons include too slow
[ 1.246][w][cplayer] hardware, temporary CPU spikes, broken drivers, and broken files. Audio [ 1.246][w][cplayer] position will not match to the video (see A-V status field).
[ 1.246][w][cplayer]
[ 1.246][v][cplayer] Change display sync audio drift: 1
[ 1.270][v][cplayer] Video sync mode disabled.
```

running mpv with interpolation deactivated leaves display sync enabled and plays as expected

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/2613013/mpv.log)

**Comment by haasn** [comment]
Does it happen with `--no-config --no-audio --video-sync=display-desync --interpolation`?

**Comment by laichiaheng** [comment]
It happens a lot in the beginning of the video. I need to adjust the progress bar to activate it.

**Comment by Akemi** [comment]
if it only happens at start up then it's somewhat related to #5882 (just ignore the hwdec part).

see a workaround and how to test it in my comment https://github.com/mpv-player/mpv/issues/5882#issuecomment-394300514, starting the player paused and manually un-pausing it a bit later.

maybe the shaderc shader compilation is at fault here (being a tad too slow)? i see it doing compilations from sec 0.132 to 1.687. the desync and deactivation happens in-between at 1.348 secs. if this causes many dropped frame at the beginning that's one reason why this happens.

**Comment by daed-alus** [comment]
here there are ~20 dropped frames when it happens
starting paused and un-pause later fixes it for now

**Comment by Akemi** [comment]
somewhat related, i've seen similar things in macOS and slow start up/backend init.

if my assumptions is right, then possible fixes are to make the desync/deactivation logic less strict on startup or somehow delay the playback after everything is properly initialised (so we don't experience any dropped frames). maybe there is a better way to fix this.

**Comment by AstralStorm** [comment]
Same issue with certain heavy glsl shader combinations that take a while for GPU to actually load and run, e.g.

gpu-api=d3d11
gpu-context=d3d11
tscale=box
tscale-window=sphinx
tscale-radius=1.05
tscale-clamp=0.0
fbo-format=rgba16hf
scale=ewa_lanczos
#dscale=ewa_lanczos
dscale=gaussian
cscale=ewa_lanczos
scaler-resizes-only=no
vf-clr
glsl-shaders-clr
glsl-shaders-append=~~/FSRCNNX_x4_16-0-4-1.glsl
glsl-shaders-append=~~/FSRCNNX_x3_16-0-4-1.glsl
glsl-shaders-append=~~/FSRCNNX_x2_8-0-4-1.glsl
glsl-shaders-append=~~/SSimDownscaler.glsl
glsl-shaders-append=~~/KrigBilateral.glsl

On my Vega FE, toggling SSimDownscaler is enough to not cause the sync to be disabled but initial FPS gets interpolated unnecessarily still.

Running with --pause then unpausing does not help as the shader is still not fully rolled in. Pause + seek + unpause actually works.

Seems like we need some sort of start preroll.

**Comment by zc62** [comment]
Probably we can have an option set the presentation queue count, then delay the start of playback until certain number of frames are decoded and rendered (and ready to present). (madVR has such an option. When I first migrated from it, I was missing the capability of changing queue sizes.)

**Comment by daed-alus** [comment]
i think i found that this only happens with _gpu-api=d3d11_
_opengl_ or _vulkan_ seem not to be affected

i have _gpu-api_ on _default/(auto)_ and _d3d11_ gets automaticlly selected

**Comment by zc62** [comment]
It is 100% sane to default to d3d11 on windows. I have been using that for quite long.

It looks like you have a lot of shaders enabled. Probably you can try to set [`gpu-shader-cache-dir`](https://mpv.io/manual/master/#options-gpu-shader-cache-dir)  to speed up the shader loading. Another thing you can try is to set mpv to use 'adaptive power' (instead of default energy saving option) in Nvidia control panel. d3d11 seems to be heavily affected by this option.

**Comment by daed-alus** [comment]
not using any shader at all
graphic cards powerplan is and always was on adaptive

**Comment by zc62** [comment]
mpv built-in scalers generate shaders as well. `gpu-shader-cache-dir` help that too.

**Comment by Akemi** [comment]
the behaviour was changes in https://github.com/mpv-player/mpv/commit/273cc3055cb5829fe62dce88e596c21ae85ef1c2
