### ISSUE TITLE
Quiet dialog when playing 5.1 audio on a 2.0 system

### ISSUE THREAD

**Issue by mrxdst** [mpv-player/mpv#6343]
### mpv version and platform

mpv 0.29.1
Arch Linux

### Reproduction steps

The vast majority of all dialog is quiet when playing 5.1 media to stereo speakers.
Music and sound effects are usually much louder.
This is true for practically any movie or tv-show. Some are passable while others are essentially inaudible.

I have my computer connected to my tv via hdmi. The system audio configuration (PulseAudio) is set to stereo output.

I have tried the `--audio-channels` option. Setting it to `2.0` and `stereo` as well as leaving it as default but it makes no audible difference. The stats osd says 2 channels instead of 6 but dialog is still very quiet.
I have also tried changing the `--audio-normalize-downmix` option without luck.

One example file i'm trying to play uses the eac3 codec.

### Expected behavior

To be able to hear dialog without constantly having to changing the volume.

### Actual behavior

Very quiet dialog.

### Log file
https://0x0.st/s02J.txt

### Sample files
Can provide if needed.  

----

This feels like something that should be pretty straight forward but after spending quite some time reading essentially every audio related option of mpv and searching the internet i can't find anything useful other than mentioned above.

I would very much appreciate any insight on how to solve this.

**Comment by tomty89** [comment]
See if `--ad-lavc-downmix=no` help. Only then would `--audio-normalize-downmix=yes` make a difference I think. Now `--audio-channels=stereo` might be necessary if you want to make sure mpv is the one who do the downmix as well. Otherwise pulse or so might be the one doing the job.

**Comment by mrxdst** [comment]
Thanks for the response.
so --ad-lavc-downmix=no and --audio-channels=stereo means that mpv will always do the downmixing instead of letting the decoder or pulse do it.

I also found a libavfilter [dynaudnorm](https://www.ffmpeg.org/ffmpeg-filters.html#dynaudnorm) that seems promising after some quick test. So i added `--af=dynaudnorm`
The result isn't perfect but it is a big improvement.

I will close this issue however if i discover anything more useful I might update for others to find

**Comment by norcalli** [comment]
I've found that dynamic range compression helps as well, but sometimes results in distortion. I think there is a sweet spot of tuning after downmixing and setting to stereo channels that should be an approximate solution, but I haven't spent the time to do so yet.

**Comment by zc62** [comment]
See https://github.com/mpv-player/mpv/issues/6563#issuecomment-473523126

**Comment by qyot27** [comment]
I have it as separate profiles, one for stereo and one for downmixing (works with 5.1 and 7.1):
```
>mpv -show-profile audionorm
Profile audionorm:
 af=lavfi="acompressor=10"

>mpv -show-profile downmix
Profile downmix:
 af=lavfi="pan=stereo|FL < 0.5*FC + 0.3*FLC + 0.3*FL + 0.3*BL + 0.3*SL + 0.5*LFE | FR < 0.5*FC + 0.3*FRC + 0.3*FR + 0.3*BR + 0.3*SR + 0.5*LFE",lavfi="acompressor=10"
```

**Comment by alexryndin** [comment]
Good discussion and explanations, helped me a lot
https://superuser.com/questions/852400/properly-downmix-5-1-to-stereo-using-ffmpeg

**Comment by potato6502** [comment]
Are these pan filters possible with mpv, or only with ffmpeg? I am using SMPlayer which has two engines: mplayer and mpv. With mplayer, pan filters are possible, but not with mpv, not that I know of. I would like to be able to set pan filters in the mpv audio filter command line in advanced options. I am under Windows.

**Comment by cheater** [comment]
Are these pan filters possible with mpv, or only with ffmpeg? I am using SMPlayer which has two engines: mplayer and mpv. With mplayer, pan filters are possible, but not with mpv, not that I know of. I would like to be able to set pan filters in the mpv audio filter command line in advanced options. I am under Windows.

**Comment by tomjaguarpaw** [comment]
Yes, you can use them with mpv. See https://github.com/mpv-player/mpv/issues/6563#issuecomment-1013721647.
