### ISSUE TITLE
Failed to build project with libmpv.a, linker command failed

### ISSUE THREAD

**Issue by macrohard** [mpv-player/mpv#6344]
### mpv 0.29.1 and ios 12

In MacOS14, XCode10 environment, build libmpv.a successfully
The build parameters:
./waf configure --disable-cplayer --disable-lcms2 --disable-lua --enable-libmpv-static --enable-ios-gl --enable-gl

And use the lipo command to merge the x86_64, armv7, arm64 architectures together.
But after adding to the Xcode project, my build failed.

### lipo command result
```
lipo -info libmpv.a
Architectures in the fat file: libmpv.a are: armv7 x86_64 arm64
```

### Build log file
```
Undefined symbols for architecture armv7:
  "_avfilter_pad_count", referenced from:
      _print_help in libmpv.a(vf_lavfi.c.19.o)
  "_avfilter_next", referenced from:
      _print_help in libmpv.a(vf_lavfi.c.19.o)
  "_ass_set_use_margins", referenced from:
      _configure_ass in libmpv.a(sd_ass.c.19.o)
  "_ass_set_shaper", referenced from:
      _configure_ass in libmpv.a(sd_ass.c.19.o)
  "_ass_set_selective_style_override", referenced from:
      _configure_ass in libmpv.a(sd_ass.c.19.o)
  "_ass_set_line_spacing", referenced from:
      _configure_ass in libmpv.a(sd_ass.c.19.o)
  "_ass_read_styles", referenced from:
      _mp_ass_add_default_styles in libmpv.a(sd_ass.c.19.o)
  "_ass_set_pixel_aspect", referenced from:
      _get_bitmaps in libmpv.a(sd_ass.c.19.o)
  ........
  "_av_log_set_callback", referenced from:
      _init_libav in libmpv.a(av_log.c.19.o)
      _uninit_libav in libmpv.a(av_log.c.19.o)
  "_av_version_info", referenced from:
      _mp_property_ffmpeg in libmpv.a(command.c.19.o)
      _print_libav_versions in libmpv.a(av_log.c.19.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by macrohard** [comment]
I re-downloaded git master and built static libraries of armv7, arm64, x86_64 architecture respectively.
Here is their configuration and build log

[armv7 configuration log](https://0x0.st/s0w_.txt)
[armv7 build log](https://0x0.st/s0wu.txt)

[arm64 configuration log](https://0x0.st/s0wp.txt)
[arm64 build log](https://0x0.st/s0wQ.txt)

[x86_64 configuration log](https://0x0.st/s0wf.txt)
[x86_64 build log](https://0x0.st/s0w1.txt)


By the way, in order to build correctly, I modified two places.
The first is line 135 of gl_headers.h
Typedef ptrdiff_t GLsizeiptr;
change into
Typedef intptr_t GLsizeiptr;

The second is line 97 of sources.py
@TaskGen.after_method('do_the_symbol_stuff')
change into
@TaskGen.after_method('process_source', 'process_use', 'apply_link', 'process_uselib_local', 'propagate_uselib_vars', 'do_the_symbol_stuff')

**Comment by macrohard** [comment]
The reason for modifying gl_headers.h is because there is a definition conflict when building the armv7 architecture static library.

The reason for modifying souces.py is because the python script reports an error when building a x86_64 architecture static library. 
AttributeError: 'task_gen' object has no attribute 'link_task'

**Comment by Akemi** [comment]
just some general question that might help us find the problem. did it work with previous versions of mpv? if yes which version started to make problems? does it work without using lipo to merge and just using one static lib? if yes which configuration of the merging makes problems?

@tmm1 and @ybma-xbzheng bot successfully build libmpv for iOS and used it, maybe they know the cause of the problem and a solution ?

**Comment by macrohard** [comment]
This is my first attempt to use libmpv for iOS, and the problem persists when using unmerged static libraries.

**Comment by ePirat** [comment]
What did you mean by 

> But after adding to the Xcode project, my build failed.

From the missing symbols errors it just looks like you forgot to add dependent static libraries like ffmpeg (libavformat, libavcodec, ...) and libass.

**Comment by macrohard** [comment]
Just compiling the libmpv for iOS static library is not enough?
Also need to compile libavformat for iOS, libass for iOS, etc.?

**Comment by ePirat** [comment]
Yes, you need to build all dependencies, else it can't work.

**Comment by macrohard** [comment]
I am a newbie. Is there any information or article on which dependent libraries libmpv needs and how to build them?

**Comment by Akemi** [comment]
with `otool -L /PATH/TO/(mpv/libmpv)` you can list all **direct** dependencies. though you also have to gather the indirect ones, eg all the libs that the direct dependencies depend on.

as an example for an actual macOS app i would say look at [iina](https://github.com/lhc70000/iina) and how it [gathers libs](https://github.com/lhc70000/iina/blob/develop/other/change_lib_dependencies.rb) and which it [uses](https://github.com/lhc70000/iina/tree/develop/deps/lib).

@ybma-xbzheng has some [scripts](https://github.com/ybma-xbzheng/mpv-build-mac-iOS) for building for iOS, including some dependencies.

otherwise mpv also has some scripts for gathering all [needed](https://github.com/mpv-player/mpv/blob/master/TOOLS/osxbundle.py#L83) [libs](https://github.com/mpv-player/mpv/blob/master/TOOLS/dylib-unhell.py).
