### ISSUE TITLE
vflip and hflip filters interact to cause incorrect orientation when toggling

### ISSUE THREAD

**Issue by sammoth** [mpv-player/mpv#6345]
When `vf=vflip,hflip` or `vf=hflip,vflip` and then the filter first in the chain is toggled, the result is incorrect.

For example using:
```
cat input.conf
v vf toggle vflip
h vf toggle hflip
```
If you run `mpv --no-config --input-conf=input.conf -vf hflip,vflip <file>`, if you press `h`, the image will flip vertically, so that is it only horizontally flipped. If you then press `v` it will go back to normal. If, on opening, you instead press `v` then `h`, it works as expected.

```
mpv 0.29.0-102-g8b6064de76 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Mon Nov 26 22:16:33 GMT 2018
ffmpeg library versions:
   libavutil       56.24.101
   libavcodec      58.40.100
   libavformat     58.23.100
   libswscale      5.4.100
   libavfilter     7.46.100
   libswresample   3.4.100
ffmpeg version: N-92529-g2ddaaaf595
```
log, from where I ran the above command and pressed `h, q`: https://0x0.st/s0yC.txt
On pressing `h` the UI shows 'Video Filters: vflip[]', but the log shows hflip

**Comment by sammoth** [comment]
It looks like the problem is caused by the `compare_filter` function: https://github.com/mpv-player/mpv/blob/802f594a857c703ac88e946d14b69cd3b6eb6006/filters/f_output_chain.c#L507

When `mp_output_chain_update_filters` is comparing hflip and vflip filters, neither have `label` or `attribs` set, they only differ by their `name` field. compare_filter doesn't compare names of its arguments, so it returns true comparing vflip and hflip. Should it be comparing `name`s?

**Comment by Dudemanguy** [comment]
Followed the steps in the OP and it worked as expected (flipped horizontally first and then it flipped vertically). If this is still an issue on your platform, feel free to reopen.
