### ISSUE TITLE
Question: How to define the total duration in the protocol av://lavfi? 

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#6348]
### mpv version and platform

mpv 0.29 build (shinchiro) mpv-dev-x86_64-20181125-git-8b6064d

--------
I try to reproduce a filter of ffmpeg through mpv (specifically any filter of the series allrgb, allyuv, color, haldclutsrc, nullsrc, pal75bars, pal100bars, rgbtestsrc, smptebars, smptehdbars, testsrc, testsrc2, and uvtestsrc) but I can not set its duration.
How should I do this?
Thank you

FFmpeg reference: https://www.ffmpeg.org/ffmpeg-all.html#allrgb_002c-allyuv_002c-color_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc

**Comment by richardpl** [comment]
mpv av://lavfi:smptebars=d=5

**Comment by EzeKees** [comment]
thanks!!
