### ISSUE TITLE
Artifacts in fullscreen when playing Youtube videos

### ISSUE THREAD

**Issue by benjaminglass1** [mpv-player/mpv#6351]
### mpv version and platform

Platform: Arch Linux, latest updates

`mpv --version` output:

```
mpv 0.29.0-103-gb6a431ec55 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Wed Nov 28 13:09:51 CST 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1
```

### Reproduction steps

Watch Youtube video (known broken example: https://www.youtube.com/watch?v=Erp8IAUouus) with `mpv https://www.youtube.com/watch?v=Erp8IAUouus`. Turn fullscreen mode on.

### Expected behavior

Video should play without artifacts. This occurs in windowed mode:

![windowed](https://user-images.githubusercontent.com/3344239/49259335-9ad9ae00-f3fe-11e8-8fff-0787de04bbfa.png)

### Actual behavior

Video has artifacts in fullscreen mode. These generally occur around the bottom-center to bottom-right of the window. They appear for the duration of the video.

![fullscreen](https://user-images.githubusercontent.com/3344239/49259336-9ad9ae00-f3fe-11e8-837c-9d78272759dd.png)

### Log file

[https://0x0.st/sGsR.txt](https://0x0.st/sGsR.txt)

**Comment by LaserEyess** [comment]
Works On My Machine™

Also Arch Linux, fully updated with nvidia proprietary drivers

```
$ mpv --version
mpv 0.29.0-88-g317d3ac266 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.23.101
   libavcodec      58.39.100
   libavformat     58.22.100
   libswscale      5.4.100
   libavfilter     7.43.100
   libswresample   3.4.100
ffmpeg version: N-92391-g07bc603757
```
With, 
```
mpv --no-config --fullscreen https://www.youtube.com/watch?v=Erp8IAUouus --log-file=wew.txt
```
I get https://0x0.st/sGzN.txt. 

Only difference is about 20 commits, so it could potentially be a regression.

**Comment by LaserEyess** [comment]
```$ mpv --version
mpv 0.29.0-103-gb6a431ec55 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.24.101
   libavcodec      58.40.100
   libavformat     58.23.101
   libswscale      5.4.100
   libavfilter     7.46.101
   libswresample   3.4.100
ffmpeg version: N-92559-gb87063c06d
```

I still don't see artifacts

**Comment by benjaminglass1** [comment]
> Works On My Machine™
> 
> Also Arch Linux, fully updated with nvidia proprietary drivers
> 
> ```
> $ mpv --version
> mpv 0.29.0-88-g317d3ac266 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
>  built on UNKNOWN
> ffmpeg library versions:
>    libavutil       56.23.101
>    libavcodec      58.39.100
>    libavformat     58.22.100
>    libswscale      5.4.100
>    libavfilter     7.43.100
>    libswresample   3.4.100
> ffmpeg version: N-92391-g07bc603757
> ```
> With,
> 
> ```
> mpv --no-config --fullscreen https://www.youtube.com/watch?v=Erp8IAUouus --log-file=wew.txt
> ```
> I get https://0x0.st/sGzN.txt.
> 
> Only difference is about 20 commits, so it could potentially be a regression.

Strangely, the issue disappeared on my machine when I tried the video again. Which is surprising to me, because it happened the last 5 or 6 times I played that video. Seems to be sporadic. However, every time it does appear is linked to the specific set of circumstances I mentioned.

**Comment by haasn** [comment]
I can think of almost no circumstances that could plausibly cause that exact issue (a random block of black near the bottom right), more so if it only happens in fullscreen mode.

I'd say this is out of our hands, unless you manage to narrow it down to something more specific that triggers it.
