### ISSUE TITLE
Can't switch audio tracks when using lavfi-complex option

### ISSUE THREAD

**Issue by CreamyCookie** [mpv-player/mpv#6354]
### mpv version and platform

```
mpv git-2018-07-22-45beb70 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Sep 18 04:05:07 UTC 2018
ffmpeg library versions:
   libavutil       56.18.102
   libavcodec      58.21.106
   libavformat     58.17.101
   libswscale      5.2.100
   libavfilter     7.26.100
   libswresample   3.2.100
ffmpeg version: git-2018-07-26-a8ce6fb
```

Ubuntu 18.04

### Reproduction steps
Run mpv (on a video file with multiple audio tracks) with `--lavfi-complex="[aid1] dynaudnorm [ao]"` which allows for dynamic range compression (without causing av sync problems).

### Expected behavior
To be able to change the audio track.

### Actual behavior
Can't change the audio track. The console outputs this (in red): 
`Can't switch away from complex filter output.`

### Log file

https://gist.githubusercontent.com/CreamyCookie/9be9acc9c69f7c3addbc55c436e55bb7/raw/75aa9604e922202177e38ea1ecb0b883da910bfd/mpv-track-switch-with-lavfi-complex.log

**Comment by CreamyCookie** [comment]
Ohh... oops. Thanks. Using `-af` seems to work now. In the past it caused av desync. Just out of curiosity (and the case I'm getting sync issues again), what would the lavfi-complex option look like without hardcoded track (just removing `[aid1]` doesn't work. results in `Pad in0 is not connected to anything.` error)?

**Comment by richardpl** [comment]
Via lua scripting and replacing [aidX] where X is track numer...
