### ISSUE TITLE
Desync on seek with VSync set to Off in Nvidia control panel

### ISSUE THREAD

**Issue by maniak1349** [mpv-player/mpv#6356]
### mpv version and platform

lachs0r's Windows x64 build 0.29.1 from 2018-10-02
Windows 7 x64
Nvidia drivers 416.94

### Reproduction steps
1. Set Vertical sync in 3D setting in Nvidia control panel to Off.
2. Have in mpv configuration:
```
gpu-context=win
video-sync=display-resample
```
3. Play any video.

### Expected behavior
Correct playback.

### Actual behavior
On the beginning of the file and every time after seeking there is a desync for a second. (Accompanied by the usual desync message "Audio/Video desynchronisation detected!" etc.) Video rushes for a bit then stops until audio will catch up. After that playback goes fine.

### Log file
https://pastebin.com/raw/xRWEkyWn

**Comment by CounterPillow** [comment]
`video-sync=display-resample` relies on working vsync. As far as I know, forcing vsync off in the control panel makes the buffer swap non-blocking without the application being able to stop that from happening.

**Comment by dnmTX** [comment]
@maniak1349  set the Vertical sync in NVCP to "Use the 3D application setting"
add **vo=gpu** to your config file
try Vulkan instead of Win32/WGL (change to **gpu-context=winvk**)
Update your driver to the latest 417.22
See how it goes....

**Comment by maniak1349** [comment]
@dnmTX 
Setting the Vertical sync to "Use the 3D application setting" (which is default) or "On" fixes the problem. 
Adding `vo=gpu` does not help. Isn't it default anyway?
Adding `display-fps=60` does not help. Not sure if it's related at all here.
Changing `gpu-context` to `winvk` does not help. `dxinterop` and `d3d11` are working fine though.
I'd rather prefer to avoid updating to 417.22 if it is not absolutely necessary since I've heard a lot of bad things about it. I can try downgrading though.

**Comment by dnmTX** [comment]
@maniak1349 

> Setting the Vertical sync to "Use the 3D application setting" (which is default) or "On" fixes the problem
Then what is the problem? Is there a any other reason to be off?

> Adding vo=gpu does not help. Isn't it default anyway?
It's not the default and if you don't add it all the graphics acceleration is done by your CPU instead of GPU.Your GPU is very much capable of doing it and should produce better results.

> Adding display-fps=60 does not help. Not sure if it's related at all here
Unrelated indeed

> Changing gpu-context to winvk does not help. dxinterop and d3d11 are working fine though
Sorry to see that,i'm kind of enjoying Vulkan lately(better colors) now that hardware acceleration is finaly available. Stick to d3d11 then,i was using it for a long time with little to no issues.

> I'd rather prefer to avoid updating to 417.22 if it is not absolutely necessary since I've heard a lot of bad things about it. I can try downgrading though
It varies from system to system.I personally have no issues but others do(reading trough the forums).
Try 399.24,from what i've read,the best driver before the 4xx.xx branch.

**Comment by haasn** [comment]
> It's not the default and if you don't add it all the graphics acceleration is done by your CPU instead of GPU.Your GPU is very much capable of doing it and should produce better results.

The default is an empty list, which means to auto-probe the VO, trying `vo=gpu` first with highest priority. Therefore this information is simply wrong.

> Sorry to see that,i'm kind of enjoying Vulkan lately(better colors

Vulkan and OpenGL run the exact same rendering code..

**Comment by haasn** [comment]
@dnmTX his log shows him using `vo=gpu`

> OpenGl was always choosing my iGPU,it's like seeing Chrome implemented in the player,same stupid behavior

OpenGL doesn't let you choose. Vulkan does, which is why it works better for you. I don't see how this is relevant to @maniak1349.

**Comment by CounterPillow** [comment]
dnmTX is a forum monster shitting up issues with barely relevant attempts at tech support, I thought we've all already established this. The fat tux avatar reveals him to be a complete plonker.

**Comment by dnmTX** [comment]
@CounterPillow  how about **PISS THE FUCK OFF**. Stupid **DEGENERATE**

**Comment by Akemi** [comment]
since this issue went kinda downhill, please open a new one if the problem still persists.
