### ISSUE TITLE
mpv - video4linux2 (v4l2) - use MJPG instead of YUYV

### ISSUE THREAD

**Issue by colemickens** [mpv-player/mpv#6359]
I was looking for information about how to use MJPG instead of YUYV when using mpv to play my webcam stream.

After a bunch of searching, I discovered that avoptions could be passed through, and I wound up figuring out something that worked:

```
mpv \
  --demuxer-lavf-format=video4linux2 \
  --demuxer-lavf-o-set input_format=mjpeg \
  /dev/video4
```

I'm now writing this here in the hopes that it's picked up by Google, as I only have one other spot that would be useful to share this out ([the Arch Wiki](https://wiki.archlinux.org/index.php/Webcam_setup#mpv)).

Also, is there a better/easier/more memorable way to do this? I'm not sure about other webcams, but:
- the webcam seems to remember a preference. mine is set to mjpg/1080. mpv respects the remembered aspect ratio, but not the pixelformat, from my testing. I think this behavior is inherited from `ffmpeg`/`libav`, which does the same thing
- my webcam offers a variety of resolutions/formats, but the only really usable one is the MJPG/1080p@30FS stream, but `mpv`'s default behavior picks the best FPS for YUYV, which is actually **5 FPS**.

Thanks!

**Comment by colemickens** [comment]
Correction, I miswrote an important sentence at the end. It is meant to say:

> the only really usable format is the MJPG@1080p@30FS stream, but `mpv`'s default behavior picks YUYV format, and then the highest FPS available, which for my webcam, is actually **5 FPS**."

**Comment by colemickens** [comment]
Since `ffmpeg` does the same thing, and I can't easily find the code in mpv, I've gone ahead and filed this against ffmpeg: https://trac.ffmpeg.org/ticket/7596#ticket

**Comment by 532910** [comment]
Why is this closed, while not fixed?

**Comment by CounterPillow** [comment]
@532910 what is there to be fixed here?

**Comment by nikp123** [comment]
It doesn't need to fixed, it just needs to be documented more.
Spent about 15 minutes searching for this.

**Comment by rubyFeedback** [comment]
I just found this via Google.

I found a similar command:

    mpv --demuxer-lavf-format=video4linux2 --demuxer-lavf-o-set=input_format=mjpeg av://v4l2:/dev/video

I wonder why the one I found used av:://v4l2 etc...

Is that leading to a different quality? I have no idea right now.

It would be nice if someone could point to an explanation of these options.

**Comment by CounterPillow** [comment]
@rubyFeedback 
> I wonder why the one I found used av:://v4l2 etc...

specifying /dev/video*n* without the av://v4l2: prefix uses a special code path inside ffmpeg to implicitly assume the v4l2 demuxer based on the filename specified. It's better to be explicit rather than implicit, but otherwise there is no difference.

Please see https://github.com/mpv-player/mpv/wiki/Video4Linux2-Input for more information.

**Comment by dreamlayers** [comment]
It seems the new option format is `--demuxer-lavf-o-set=input_format=mjpeg`. Using a space instead of the first `=` does not work in mpv 6.1.1. This is very helpful with an MS2109 HDMI capture dongle, giving a much better frame rate.

**Comment by ohhai** [comment]
For those who also need how to specify resolution as well: it’s documented here
https://github.com/mpv-player/mpv/wiki/Video4Linux2-Input

For web cameras, autoselected max resolution sometimes comes with not-the-max FPS. In this case, need to lower the video size if need more FPS.
