### ISSUE TITLE
Ability to reload input.conf

### ISSUE THREAD

**Issue by NightMachinery** [mpv-player/mpv#6362]
I like to be able to assign a keybinding to reload input.conf. It can have two modes, one loading the file on top of the current config, another one on top of the default config.
(Related issue: https://github.com/mpv-player/mpv/issues/4718)

**Comment by Akemi** [comment]
you should probably tell us your use-case, maybe your problem can be solved differently.

**Comment by NightMachinary** [comment]
I add hotkeys the first time I need them,  and I appreciate if I don’t have
to restart the app.

**Comment by Akemi** [comment]
we could probably use [mpv_load_config_file](https://github.com/mpv-player/mpv/blob/master/libmpv/client.h#L567), though it will just load a **new** config and keeps everything that was loaded before. so it doesn't reset anything.

**Comment by Argon-** [comment]
As a workaround: you can quit-watch-later, then mpv will resume where it left (within a file and playlist)

**Comment by NightMachinary** [comment]
This solves my use case. I don’t need to reset things.

**Comment by frozenpandaman** [comment]
Very old issue here, but this would be cool to see added.

**Comment by garoto** [comment]
This is one of the very few (perhaps niche) feature requests I would like to see eventually implemented.
