### ISSUE TITLE
Video play slowly with gitter for H264 on OSX: Urgent!

### ISSUE THREAD

**Issue by rstardev** [mpv-player/mpv#6364]
### mpv version and platform

v0.29.1

### Reproduction steps

My Machine : MacBook Pro: Processer-3GHz Intel Core i7, Memory-8GB 1600MHz DDR3, 
Video file: h264 3840x2160 59.940fps, 02:46s 

https://www.dropbox.com/s/0x025bdhzbdl03t/150mm%205.MOV?dl=0

When I play this video, video plays very slowly (takes more 5 mins, this is less than 3 mins) with lag and jitter.
What is the best config options I can use?

**Comment by Hrxn** [comment]
You should probably try to enable hwdec..
You can see possible options here with running `mpv --hwdec=help`.
I don't know what's usually the best for macOS. `videotoolbox` probably..

**Comment by CounterPillow** [comment]
Honestly I doubt the decoding is too slow, I think the likelier issue is that the rendering is dropping frames, but since you didn't post a full log nobody knows what options you've set.

Also, videotoolbox is failing in your case because your hardware decoder doesn't support 4K resolutions.

**Comment by Jj0YzL5nvJ** [comment]
The video itself is weird, in my case (Xubuntu 16.04.5 LTS) `vdpau` is clearly dropping frames, even if **mpv says that everything is alright**, it is not. Using `vaapi` the video plays perfectly.
 Only that video gives me such problem.

**Comment by Akemi** [comment]
i can reproduce the hwdec problem (just green frames), which is most likely an ffmpeg problem. VLCs videotoolbox decoder doesn't have that problem. we already have similar issues reported and i also reported them to ffmpeg.

quicktime and vlc both play this fine here and mpv doesn't have a problem here either with sw decoding. though i probably have a faster system. it uses around 50% CPU here. my mid 2010 macbook pro can't play it without major lag/jitter/dropped frames (hwdec also properly falls back to swdec).

i want to mention this file has a massive average bitrate of [~140Mbps](https://0x0.st/sD29.png) and it's quite possible that your system just hits its limit.

that's about as much as i can say with the information provided.

**Comment by rstardev** [comment]
Hi @Akemi, So is it working fine on your machine without hardware decorder?
What is your machine spec?

**Comment by Akemi** [comment]
yeah it's working fine here. the CPU is an i7-6700k. no specific mac since it's a hackintosh, but it's equivalent to a 5K iMac Late 2015 (iMac17,1 ).

**Comment by rstardev** [comment]
@Akemi, 
You mentioned this file has a massive average bitrate of ~140Mbps and it's quite possible that your system just hits its limit.
But this file works perfectly on VLC or QuickTime Player even on the lower spec machine.
My machine has Core i7, 3GHz CPU and 8GHz Ram.

**Comment by Akemi** [comment]
core i7 and frequency doesn't say much, the generation of it is important. maybe you got an i7-4578U? dunno, i don't really like guessing.

it probably uses hwdec with quicktime and vlc, same as on my system. sadly like you noticed, and i confirmed, hwdec in mpv doesn't work on this file. this needs to be fixed in ffmpeg.

**Comment by rstardev** [comment]
@Akemi, So you mean, the hardware decoder issues need to be fixed in ffmpeg, not in mpv?

**Comment by Akemi** [comment]
yes. one can verify it with, `fmpeg -hwaccel videotoolbox -i "150mm 5.MOV"  -f null -`. it throws the same errors.

**Comment by rstardev** [comment]
@Akemi, Then there is no way to solve it before the ffmpeg team solve it?
Can you give me the link of ffmpeg issue? thanks

**Comment by Akemi** [comment]
i mean ti reported the ones that were already reported before. this might be related to them. anyway all the ffmpeg videotoolbox issues are [here](https://trac.ffmpeg.org/query?status=!closed&keywords=~videotoolbox). you could probably report this issue there too.
