### ISSUE TITLE
Is possible to remove volume bar osc when changing the volume?

### ISSUE THREAD

**Issue by kaiteck** [mpv-player/mpv#6365]
When changing volume, there will be a volume bar and volume percentage appeared. 

Honestly speaking, the volume bar is reluctant and is blocking the view of the video. Is there a way in .conf to disable that bar?

**Comment by CounterPillow** [comment]
You can do this with `--no-osd-bar`.

**Comment by Argon-** [comment]
This will disable the bar completely. You can also configure it on a per-keybinding basis in input.conf, e.g. 

    9      no-osd add volume -2

And then there's also https://mpv.io/manual/master/#options-osd-on-seek
