### ISSUE TITLE
[dvb] Wrong dvbin-card range 

### ISSUE THREAD

**Issue by parkerlreed** [mpv-player/mpv#6371]
### mpv version and platform

Linux
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1
```
### Reproduction steps

1. Run `mpv --dvbin-card=0 dvb://<some-channel>`
2. Error returned stating 0 is not a valid input

### Expected behavior

mpv uses the first card at 0 index

### Actual behavior

mpv checks the input and specifies 1 though 4 must be used. 

Cards are 0 indexed but the option parser validates only 1 though 4

If nothing is specified for dvbin-card, 0 is used anyways.

### Log file

http://ix.io/1vKE

**Comment by olifre** [comment]
I think we actually should accept anything from 0 to `MAX_ADAPTERS`-1 here. 
I'll prepare a PR shortly.
