### ISSUE TITLE
HEVC crash with videotoolbox hwdec

### ISSUE THREAD

**Issue by sergiou87** [mpv-player/mpv#6375]
### mpv version and platform

mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Nov  6 17:30:25 GMT 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1

macOS 10.14.2 (18C54)

### Reproduction steps

Play this file in macOS or iOS using videotoolbox hwdec: [hevc_crash_mpv.mkv.zip](https://github.com/mpv-player/mpv/files/2669873/hevc_crash_mpv.mkv.zip)

`mpv hevc_crash_mpv.mkv --hwdec=yes`

### Expected behavior

It should play.

### Actual behavior

It crashes.

Other HEVC files work with videotoolbox hwdec. And it plays fine without hwdec.

### Log file

[mpv-crash-log.txt](https://github.com/mpv-player/mpv/files/2669883/mpv-crash.txt)

Stack trace on iOS:
```
* thread #9, name = 'mpv/mpv core', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x000000010900227f example-mpv-ios`ff_videotoolbox_hvcc_extradata_create + 47
    frame #1: 0x0000000109002f17 example-mpv-ios`videotoolbox_start + 423
    frame #2: 0x000000010900280b example-mpv-ios`videotoolbox_common_init + 171
    frame #3: 0x0000000108d09578 example-mpv-ios`ff_get_format + 744
    frame #4: 0x0000000108eb20cc example-mpv-ios`decode_nal_unit + 1388
    frame #5: 0x0000000108eb0ccb example-mpv-ios`hevc_decode_frame + 779
    frame #6: 0x0000000108d074ff example-mpv-ios`decode_receive_frame_internal + 415
    frame #7: 0x0000000108d07311 example-mpv-ios`avcodec_send_packet + 209
  * frame #8: 0x0000000108a3f9fa example-mpv-ios`do_send_packet(vd=0x00006000000e3c40, pkt=0x000060c00017c780) at vd_lavc.c:965 [opt]
    frame #9: 0x00000001089de4f5 example-mpv-ios`lavc_process(f=0x00006000000e3c40, eof_flag=0x00007f90d5315a2d, send=(example-mpv-ios`send_packet at vd_lavc.c:993), receive=<unavailable>) at f_decoder_wrapper.c:713 [opt]
    frame #10: 0x00000001089e6952 example-mpv-ios`mp_filter_run(filter=<unavailable>) at filter.c:194 [opt]
    frame #11: 0x00000001089e6b20 example-mpv-ios`mp_pin_out_request_data [inlined] filter_recursive(f=<unavailable>) at filter.c:151 [opt]
    frame #12: 0x00000001089e6aff example-mpv-ios`mp_pin_out_request_data(p=0x000060400011ae00) at filter.c:256 [opt]
    frame #13: 0x00000001089e6dee example-mpv-ios`mp_pin_out_read(p=0x000060400011ae00) at filter.c:269 [opt]
    frame #14: 0x0000000108a27d34 example-mpv-ios`write_video at video.c:471 [opt]
    frame #15: 0x0000000108a27ada example-mpv-ios`write_video(mpctx=<unavailable>) at video.c:994 [opt]
    frame #16: 0x0000000108a23c00 example-mpv-ios`run_playloop(mpctx=0x00007f90d5806640) at playloop.c:1099 [opt]
    frame #17: 0x0000000108a1e3f4 example-mpv-ios`mp_play_files [inlined] play_current_file(mpctx=<unavailable>) at loadfile.c:1365 [opt]
    frame #18: 0x0000000108a1d936 example-mpv-ios`mp_play_files(mpctx=0x00007f90d5806640) at loadfile.c:1530 [opt]
    frame #19: 0x0000000108a08130 example-mpv-ios`core_thread(p=0x00007f90d5806640) at client.c:524 [opt]
    frame #20: 0x000000010f558305 libsystem_pthread.dylib`_pthread_body + 126
    frame #21: 0x000000010f55b26f libsystem_pthread.dylib`_pthread_start + 70
    frame #22: 0x000000010f557415 libsystem_pthread.dylib`thread_start + 13
```

### Sample files

[hevc_crash_mpv.mkv.zip](https://github.com/mpv-player/mpv/files/2669873/hevc_crash_mpv.mkv.zip)

**Comment by sergiou87** [comment]
It looks very similar to https://github.com/mpv-player/mpv/issues/5052#issuecomment-340893210

@tmm1 any idea what could it be? 😅

**Comment by sergiou87** [comment]
Ok, seems to be a ffmpeg bug. My friend @rcombs has a patch that seems to fix the issue (🙇🙇🙇🙇🙇🙇🙇🙇🙇), we're going to test it a bit more and submit it to ffmpeg 😄

**Comment by tmm1** [comment]
Was the patch submitted to ffmpeg-devel?

**Comment by sergiou87** [comment]
No idea, tbh, I have to check with @rcombs

**Comment by tmm1** [comment]
http://ffmpeg.org/pipermail/ffmpeg-devel/2019-January/238651.html

**Comment by sergiou87** [comment]
Yes! That's the one 😄

**Comment by gunnarmarten** [comment]
Ping @tmm1 . Looks like this patch wasn't merged into ffmpeg master yet.
