### ISSUE TITLE
Create an official Flatpak and publish it on Flathub

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#6378]
I think it's a good idea for the project owners to own the repository on Flathub. After an initial release the community can help bumping versions.

http://docs.flatpak.org/en/latest/introduction.html
https://github.com/hadess/flatpak-fusion/blob/master/io.mpv.app.json.in
https://github.com/FaithBeam/flatpak-chatty/blob/master/chatty.json
https://github.com/flathub/io.github.GnomeMpv
https://github.com/flathub/org.videolan.VLC/blob/master/org.videolan.VLC.json
https://github.com/var512/flatpak-packages/blob/master/test.flatpak.MediaCenter/test.flatpak.MediaCenter.json
https://github.com/ozmartian/vidcutter/blob/master/_packaging/flatpak/com.ozmartians.VidCutter.json

**Comment by haasn** [comment]
Do you volunteer to maintain this flatpak?

**Comment by JohnOsxW** [comment]
I would but I don't have a GitHub account

**Comment by hyiltiz** [comment]
They should really call it FatPack

**Comment by wm4** [comment]
There's another open issue for FatPack.
