### ISSUE TITLE
libmpv crash on mpv_render_context_create

### ISSUE THREAD

**Issue by doubleaa93** [mpv-player/mpv#6379]
### mpv version and platform
 0.29.1 windows 10x64

### Reproduction steps
Run the SDL example from https://github.com/mpv-player/mpv-examples/blob/master/libmpv/sdl/main.c

`if (mpv_render_context_create(&mpv_gl, mpv, params) < 0) `

Throws an exception 
`Exception has occurred.
Segmentation fault`
### Expected behavior
To run the example fine
### Actual behavior
Crash

**Comment by Akemi** [comment]
does it work with https://github.com/mpv-player/mpv-examples/pull/17?
