### ISSUE TITLE
Question when you use --hwdec do you need to specify --vd manually?

### ISSUE THREAD

**Issue by omen23** [mpv-player/mpv#6381]
### mpv version and platform

mpv-0.29.0 Kubuntu 18.10 <- most recent package in ubuntu ecosystem

 ### Reproduction steps

`mpv --hwdec=yes <input>`

### Expected behavior

mpv will play the movie hardware accelerated with the codec `h264_cuvid hevc_cuvid` , etc ..
with `mpv --hwdec=yes --vd=h264_cuvid <input>`

https://0x0.st/skTC.log

### Actual behavior

mpv will play the movie with NVDEC but uses the `h264` codec not `h264_cuvid`

https://0x0.st/skTI.log

### Question
Does this yield the same outcome or not?
Same applies for VP9 videos from youtube
does

`mpv https://youtu.be/D7lkth34rgM --ytdl-format=248+251 --hwdec=yes --vd=vp9_cuvid -v`
or
`mpv https://youtu.be/D7lkth34rgM --ytdl-format=248+251 --hwdec=yes -v`
make a difference .. if I specify `vp9_cuvid` I get this
```
...
[vd] Trying hardware decoding via vp9-nvdec.
[vd] Using underlying hw-decoder 'vp9'
[vd] Selected codec: vp9_cuvid (Nvidia CUVID VP9 decoder)
...
```
if I dont specify it I get this
```
...
[vd] Trying hardware decoding via vp9-nvdec.
[vd] Selected codec: vp9 (Google VP9)
...
```
***But CPU/RAM usage and memory usage on the graphics card seems to be the same – I GUESS***

### Edit:
after chaning my `/etc/mpv/mpv.conf` to
```
hwdec=yes
vd=h264_cuvid,hevc_cuvid,mjpeg_cuvid,mpeg1_cuvid,mpeg2_cuvid,mpeg4_cuvid,vc1_cuvid,vp8_cuvid,vp9_cuvid
ad=libfdk_aac
```
everything is working fine but does it make a difference if nvdec loads `vp9` codec by google or `vp9_cuvid` (same for `h264` vs `h264_nvenc`) IIRC you need to combine these so the underlying hw-decoder gets activated.

**Comment by CounterPillow** [comment]
no, you don't need to specify `--vd` manually. The stats overlay (by default, `i` and `I` for toggle) will show the hwdec next to the decoder if hwdec is used.

**Comment by omen23** [comment]
Hey,
I just testet it, when I put `vd=h264_cuvid,hevc_cuvid,mjpeg_cuvid,mpeg1_cuvid,mpeg2_cuvid,mpeg4_cuvid,vc1_cuvid,vp8_cuvid,vp9_cuvid` to my `mpv.conf` the `I toggle` looks like this:
![withvd](https://user-images.githubusercontent.com/1809702/65368538-c4d8b700-dc42-11e9-8704-e457fbcf8e34.png)
When this line is commented out, the status overlay looks like this:
![novd](https://user-images.githubusercontent.com/1809702/65368547-df129500-dc42-11e9-8e45-d49c807ae24f.png)

Does this make a difference?
Kind Regards
