### ISSUE TITLE
Playing video in tty without fullscreen

### ISSUE THREAD

**Issue by edn9** [mpv-player/mpv#6382]
### mpv version and platform
mpv 0.29.1
Arch Linux, kernel 4.19.8-arch1-1-ARCH
bspwm

### Reproduction steps
In tty, open a video with:
**mpv —vo=drm videohere.mp4**

### Expected behavior
Is there any way to play it without fullscreen? Like in mplayer:
**mplayer -vo fbdev2 -vf scale=665:384 -geometry 725:0 videohere.mp4**
Example: https://i.imgur.com/NjHUtml.jpg
Font: https://www.reddit.com/r/unixporn/comments/a6ee0l/tty_playing_youtube_while_coding_without_xorg/

![teste](https://user-images.githubusercontent.com/28832216/50044693-a8ce3680-006e-11e9-8d3c-3ea6bbf2552d.png)

### Actual behavior
Video just play in fullscreen, even with --geometry=800x600+500+0, which work fine in xorg, but I want to do it in tty like mplayer do.

**Comment by wm4** [comment]
I doubt drm allows this kind of concurrent access.

**Comment by schrmh** [comment]
It has been a few years but this is still an issue.
OP did not ask about a drm specific solution but the feature in general.
Now with some recent developments regarding fbdev, would mpv consider adding it back so that there is feature-parity with mplayer (which mpv was a fork of)?
