### ISSUE TITLE
Failed to open VDPAU backend libvdpau_nvidia.so

### ISSUE THREAD

**Issue by ivan18m** [mpv-player/mpv#6385]
### mpv version and platform
Installed from pacman
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1
```
### Reproduction steps
Linux with wayland
GPU is RX580
config
```
profile=gpu-hq
gpu-api=vulkan
gpu-context=wayland
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample

audio-file-auto=fuzzy
volume-max=200

alang=eng,en,hr
slang=eng,en
sub-auto=fuzzy

stop-screensaver=yes
screenshot-format=jpg
screenshot-jpeg-quality=100
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes
screenshot-jpeg-source-chroma=yes
```
start video with mpv filename

### Expected behavior
No errors

### Actual behavior
Video loads and it's very laggy

### Log file
```
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[vo/xv] Warning: this legacy VO has bad quality and performance, and will in particular result in blurry OSD and subtitles. You should fix your graphics drivers, or not force the xv VO.
AO: [pulse] 48000Hz 5.1 6ch float
VO: [xv] 1920x1080 yuv420p
AV: 00:00:00 / 01:10:04 (0%) A-V: -0.031 DS: 2.667/0 Cache: 161s+64MB
[vo/xv] X11 can't keep up! Waiting for XShm completion events..
```

**Comment by CounterPillow** [comment]
"Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory" is a red herring here, and not the actual problem at hand.

The real issue is that your Vulkan context is failing to work, so it falls back on xv. If you've upgraded your Mesa without rebooting, try doing that. Otherwise a full log file might help (generate one with `--log-file=yourlogfile.txt`).

**Comment by CounterPillow** [comment]
@Jj0YzL5nvJ that must be something with either your system or your mpv build, since I'm on X11 and do get a waylandvk context option.

I think @ivan18m should try `--gpu-context=waylandvk` instead of `--gpu-context=wayland` and see if that gets him something other than xv.

**Comment by CounterPillow** [comment]
Okay, that sounds like your wayland compositor doesn't support the stable xdg-shell protocol.

**Comment by Jj0YzL5nvJ** [comment]
His build is missing [crossc](https://github.com/rossy/crossc) ¬¬u

**Comment by CounterPillow** [comment]
I'm pretty sure crossc isn't needed on Linux, glslang is.

**Comment by Akemi** [comment]
style issue, open a new one if you still have problems.
