### ISSUE TITLE
[Question] Send scaled video to another application

### ISSUE THREAD

**Issue by lmoe** [mpv-player/mpv#6387]
### mpv version and platform
Arch Linux mpv 1:0.29.1-5 (x86_64)

I've searched around, but didn't found something helpful, so I'm asking my question here.

Is it possible to pipe the current video in a lower scaled (64x64px or so) version to another application?
What I want to accomplish is an ambilight feature for Mpv. I need to get the colors of each side. 
But there are no extensions for mpv, and a the global X11 hook from Hyperion/.ng dropps too much frames in mpv while running.

I don't think I can accomplish this with simple lua, would I have to write an application around it and do the computation on my own?

Thanks in advance!

**Comment by haasn** [comment]
What I would try doing is writing an ffmpeg filter that computes the
ambilight colors and sends them off somewhere else, then use this with
`-vf` at runtime. (The filter wouldn't have to modify the actual data, so
it wouldn't break DR - it can just pass frames through unmodified)

It will run on the CPU though. If you want the downscaling to happen on
the GPU, we'd need some sort of shader-based solution involving readback
at runtime.

**Comment by lmoe** [comment]
Thank you!

That sounds easier than expected. A filter sounds promising. 
I'm just thinking about what brings a better performance. Calculating the colors from a 4k image directly, or sampling down the image first, then calculate the colors.

It seems like, to get it right, i have to code the ambilight on my own. Hyperion for example has a black border detection. I would have to implement this on my own, probably into the filter, because constantly streaming 4k images to an application doesn't sound that great at all. 

A shader scaling solution would be prettier I guess ..
