### ISSUE TITLE
Subtitle performance issue

### ISSUE THREAD

**Issue by jazmac** [mpv-player/mpv#6388]
### mpv version and platform

mpv-x86_64-20181216-git-d6d6da4
Windows 10 Pro 64-bit

### Reproduction steps

Running certain subtitles containing effects such as ones that overlay over objects in a scene through coordinates positioning (typically found in animated tv shows) will sometimes result in frames dropping. I've reproduced this problem on 3 different computers all with varying builds and with different media files containing similar effects and it's tied directly with the power of the CPU as a 4th build utilizing an i7-8600k did not drop frames under the same load.

I've ran these files both with a vanilla build of mpv and with changing settings within the mpv.conf such as the gpu api and subtitle blending etc. to try and rectify the problem but have been unable to fix it thus far.

Running at 4k resolution will increase the chances of the issue showing up but it will still occur (albeit rarely) even at 1080p, the problem was reproducible on an i7-970, an i5-3570 and a Ryzen 5 2600, the number of frames dropped for a given scene is consistently the same but will vary between different CPUs.

I had a friend run through the same media on two of his machines and he witnessed the same issues independently from me.

If the subtitles are turned off, then the issue disappears completely and normal playback occurs.

I'm reporting this as a bug because it seems unreasonable that a subtitle effect should cause this kind of detrimental impact to playback at 1080p on even newer mid-range CPUs.

### Expected behavior

smooth playback while subtitles are displayed.

### Actual behavior

Varying frame drops when specific subtitles are shown.

### Log file

https://nofile.io/f/gu0ECJv0yyg/mpv.log

apologies for the other link, fixed it.

**Comment by CounterPillow** [comment]
As far as I know, this would be an issue with libass. libass renders all the subtitles on the CPU, though it does try to make use of SIMD in some cases. One idea that has been proposed before was that mpv should render subtitles a few frames ahead so it has a bit of buffer if there are very expensive to render effects popping up suddenly.

>http://192.168.0.21:8080/share.cgi?ssid=0vDC6Km

Thanks that's an extremely useful link for everyone outside of your LAN.

**Comment by jazmac** [comment]
> As far as I know, this would be an issue with libass. libass renders all the subtitles on the CPU, though it does try to make use of SIMD in some cases. One idea that has been proposed before was that mpv should render subtitles a few frames ahead so it has a bit of buffer if there are very expensive to render effects popping up suddenly.
> 
> > http://192.168.0.21:8080/share.cgi?ssid=0vDC6Km
> 
> Thanks that's an extremely useful link for everyone outside of your LAN.

https://nofile.io/f/gu0ECJv0yyg/mpv.log

Sorry about that.

**Comment by laichiaheng** [comment]
Same here on my old HTPC, it can't render the srt subtitle without dropping frames.

**Comment by laichiaheng** [comment]
@CounterPillow 
> One idea that has been proposed before was that mpv should render subtitles a few frames ahead so it has a bit of buffer if there are very expensive to render effects popping up suddenly.
Are they able to do it?

**Comment by CounterPillow** [comment]
@laichiaheng please file a separate issue with a log and a sample file and information about your hardware instead of speculating.

**Comment by astiob** [comment]
For reference, the follow-up issue opened by the second reporter appears to be #6433.

**Comment by zc62** [comment]
I think they are irrelevant. Ass subtitles are handled by libass, while srt subtitles use libavcodec in ffmpeg.

**Comment by astiob** [comment]
I believe SRT is converted to ASS at run-time and rendered through libass.

Regardless, that is likely a separate issue. The reason I mention it is because it is mentioned above, but no link was provided.

**Comment by Akemi** [comment]
no example was provided and libass issue.
