### ISSUE TITLE
mpv.app hangs on startup when accessibility permissions are given

### ISSUE THREAD

**Issue by yndi** [mpv-player/mpv#6389]
### mpv version and platform

```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Dec 18 00:13:15 JST 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1

Configuration: waf configure --prefix=/usr/local/Cellar/mpv/0.29.1_1 --enable-html-build --enable-javascript --enable-libmpv-shared --enable-lua --confdir=/usr/local/etc/mpv --datadir=/usr/local/Cellar/mpv/0.29.1_1/share/mpv --mandir=/usr/local/Cellar/mpv/0.29.1_1/share/man --docdir=/usr/local/Cellar/mpv/0.29.1_1/share/doc/mpv --enable-zsh-comp --zshdir=/usr/local/Cellar/mpv/0.29.1_1/share/zsh/site-functions
```
The player is run on macOS Mojave 10.14.2

### Reproduction steps

* install mpv through `brew install --with-bundle mpv`
* copy `mpv.app` to /Applications
* launch the app and let it be added to Accessibility list under Security & Privacy once asked by the OS
* open any media file by either double-clicking on it or through `open` command in a terminal emulator
* experience a 2-20 second delay before the player window appears 

### Expected behavior

The player should start instantaneously. 

### Actual behavior

There's a semi-random delay between starting the process and starting the playback, it can be about 2 seconds, it can be about 20 seconds. The behavior is very strange, the animation of the app and the media file being opened gets hung, the Dock wouldn't respond, even `htop` running in background wouldn't redraw. Obviously, it's not a player fault, something is happening deeply inside the OS.

I found https://github.com/mpv-player/mpv/issues/5478 and https://github.com/mpv-player/mpv/issues/5511 which seemed closely related to this issue. The first thing I tried was choosing different a video output (gpu, libmpv, null), but it didn't help. I also tried disabling throttling (no effect) with
```
sudo sysctl debug.lowpri_throttle_enabled=0
```
I was actually going to file a ticket asking for help, but playing around with the system, I could find a fix of the problem (it doesn't fix the cause though, whatever it is). Once I removed `mpv.app` from the Accessibility list under Security & Privacy setting in System Preferences the app had asked me to put itself into, everything started working as smoothly as expected.

I also played a little bit with the app itself deleting the bundled mpv as well as its libraries inside the app and replacing the `mpv-bundle` executable with a symbolic link to the actual mpv under `/usr/local/Cellar/mpv/...` (which should be exactly the same), that actually seemed to help even with `mpv.app` staying in the Accessibility list. My guess would be there's some kind of system-wide protection that tries to make sure the app doesn't do anything fishy, but my knowledge of how modern macOS works is close to zero.

A slightly annoying thing which probably deserves its own ticket but most probably directly related to this issue is that the pseudo-gui version of the player launched via `mpv.app` consumes two-three times as much CPU (~30% vs. ~10%) as `mpv` launched from a terminal emulator even when it doesn't have any Accessibility rights (Apple explains the list as "allow the apps below to control your computer"), when both versions have hardware acceleration enabled (and it actually works according to the logs), and even when all  the app does is launch `mpv` via a symlink. 

### Log file

I'm attaching two logs, the "[bad](https://0x0.st/skYM.log)" one created by opening a file with `mpv.app` by double-clicking on it in Finder, and the "[good](https://0x0.st/skYu.log)" one created by opening the same file with `mpv` in iTerm. Both instances used the default (empty) `mpv.conf`. I also trimmed everything after the libmpv_render initialization. Frankly, it I don't think the logs are any useful, because it's obviously not a player problem. The only amusing part is the the "bad" log contains such a time shift:
```
   0.051][d][osc] reading options for osc 
[   0.051][d][global] config path: 'script-opts/osc.conf' -/-> '/Users/yndi/.config/mpv/script-opts/osc.conf'
[   0.051][d][global] config path: 'script-opts/osc.conf' -/-> '/Users/yndi/.mpv/script-opts/osc.conf'
[   0.051][d][global] config path: 'script-opts/osc.conf' -/-> '/Applications/mpv.app/Contents/Resources/script-opts/osc.conf'
[   0.051][d][global] config path: 'script-opts/osc.conf' -/-> '/usr/local/etc/mpv/script-opts/osc.conf'
[   0.051][v][osc] script-opts/osc.conf not found. 
[   0.051][d][global] config path: 'lua-settings/osc.conf' -/-> '/Users/yndi/.config/mpv/lua-settings/osc.conf'
[   0.051][d][global] config path: 'lua-settings/osc.conf' -/-> '/Users/yndi/.mpv/lua-settings/osc.conf'
[   0.051][d][global] config path: 'lua-settings/osc.conf' -/-> '/Applications/mpv.app/Contents/Resources/lua-settings/osc.conf'
[   0.051][d][global] config path: 'lua-settings/osc.conf' -/-> '/usr/local/etc/mpv/lua-settings/osc.conf'
[   0.051][v][osc] lua-settings/osc.conf not found. 
[  18.757][v][libmpv_render] GL_VERSION='4.1 INTEL-12.4.7'
[  18.757][v][libmpv_render] Detected desktop OpenGL 4.1.
[  18.757][v][libmpv_render] GL_VENDOR='Intel Inc.'
[  18.757][v][libmpv_render] GL_RENDERER='Intel(R) HD Graphics 615'
[  18.757][v][libmpv_render] GL_SHADING_LANGUAGE_VERSION='4.10'
[  18.757][d][libmpv_render] Combined OpenGL extensions string:
[  18.757][d][libmpv_render]  GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier
[  18.757][v][libmpv_render] Loaded extension GL_APPLE_rgb_422.
```
And the "good" one does exactly the same thing with no delay:
```
[   0.065][d][osc] reading options for osc 
[   0.065][d][global] config path: 'script-opts/osc.conf' -/-> '/Users/yndi/.config/mpv/script-opts/osc.conf'
[   0.065][d][global] config path: 'script-opts/osc.conf' -/-> '/Users/yndi/.mpv/script-opts/osc.conf'
[   0.065][d][global] config path: 'script-opts/osc.conf' -/-> '/usr/local/etc/mpv/script-opts/osc.conf'
[   0.065][v][osc] script-opts/osc.conf not found. 
[   0.065][d][global] config path: 'lua-settings/osc.conf' -/-> '/Users/yndi/.config/mpv/lua-settings/osc.conf'
[   0.065][d][global] config path: 'lua-settings/osc.conf' -/-> '/Users/yndi/.mpv/lua-settings/osc.conf'
[   0.065][d][global] config path: 'lua-settings/osc.conf' -/-> '/usr/local/etc/mpv/lua-settings/osc.conf'
[   0.065][v][osc] lua-settings/osc.conf not found. 
[   0.136][v][osx/cocoacb] Created CGL pixel format with attributes: kCGLPFAOpenGLProfile, kCGLOGLPVersion_3_2_Core, kCGLPFAAccelerated, kCGLPFADoubleBuffer, kCGLPFABackingStore, kCGLPFAAllowOfflineRenderers, kCGLPFASupportsAutomaticGraphicsSwitching
[   0.147][v][libmpv_render] GL_VERSION='4.1 INTEL-12.4.7'
[   0.148][v][libmpv_render] Detected desktop OpenGL 4.1.
[   0.148][v][libmpv_render] GL_VENDOR='Intel Inc.'
[   0.148][v][libmpv_render] GL_RENDERER='Intel(R) HD Graphics 615'
[   0.148][v][libmpv_render] GL_SHADING_LANGUAGE_VERSION='4.10'
[   0.148][d][libmpv_render] Combined OpenGL extensions string:
[   0.148][d][libmpv_render]  GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier
[   0.148][v][libmpv_render] Loaded extension GL_APPLE_rgb_422.
```
It might seem the problem is in the libmpv_render initialization part, but it behaves the same with `vo=null` as long as `mpv.app` is present in the Accessibility list (at least in my case). That being said, I don't expect this problem to be solved quickly, nor do I understand how much effort it'd require, but I hope there's some kind of programmatic workaround at least.

**Comment by Akemi** [comment]
i also get a small delay with the bundle, though i thought it was related to something else on my system. the culprit is most likely [this](https://github.com/mpv-player/mpv/blob/ada4f7c6006fc60189987b3ee012e7f4ced9926e/osdep/macosx_events.m#L188) line. if you can comment it and try again that would be helpful.

if this is really the reason it's possible that something changed within macOS since Apple introduced a more modern replacement API for it, or something is just blocking which wasn't before.

**Comment by Akemi** [comment]
if you can try running the mpv.app in "Instruments".

add a "Counter" (click + in top right), add an app target (top left drop down and chose target), and the click on the record button (top left). when mpv starts and you could reproduce the problem immediately quit mpv. then lock at the statistics at the bottom and see where it spent the most time.

**Comment by yndi** [comment]
I feel a need to apologize, it appears the machine I was testing the player on was actually under severe load, so all numbers became exaggerated. However, the problem is still there, it is just less severe. And unfortunately, commenting out media key initialization does not help. I do not have Xcode installed on that particular box, and I could not reproduce the issue with macOS 10.13.3 where there is one. I may play with Instruments on Mojave a bit later.

**Comment by Akemi** [comment]
just some further information. the hang actually happens in the `[NSApplication sharedApplication]` call. it's kinda a blackbox because. we don't really know what happens internally when the application i initialised.

this is me just guessing since it happens with the bundle only:
- it might be related to code signing
- it might be related to app sandboxing
- it might be related to some app bundle setting
- it's definitely related to the accessibility permissions, since removing them removes the hang
- it's not related to the old event tap
