### ISSUE TITLE
How to use devices own Equalizer instead of MPV's

### ISSUE THREAD

**Issue by smolseok** [mpv-player/mpv#6391]
### mpv version and platform
Latest Android Version

### Expected behavior
Uses devices equalizer and lets me listen to my sweet bassy music

### Actual behavior
No change.

### Log file
uhhhhh....

I'm using MPV on an Android Device and I want to use the devices default equalizer.. like if I change something come back and play a file through MPV there's no change in the Audio.. I've tried the same thing through using VLC and MX Player and they can use the devices equalizer perfectly.. but I don't use them because I like MPV more.. so is there anyway I could change this?  Or can I change around MPV's audio equalizer?

**Comment by CounterPillow** [comment]
This is probably an issue for https://github.com/mpv-android/mpv-android

**Comment by smolseok** [comment]
@CounterPillow right you are my good sir... Sorry for this!
