### ISSUE TITLE
mpv failed to play local H.264 video on Mac.

### ISSUE THREAD

**Issue by rstardev** [mpv-player/mpv#6394]
### mpv version and platform

mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Nov  6 17:30:25 GMT 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1

![image](https://user-images.githubusercontent.com/45319190/50196978-4af86200-0380-11e9-9392-f09dbe3f789c.png)

![screenshot 2018-12-19 11 18 39](https://user-images.githubusercontent.com/45319190/50197005-5cda0500-0380-11e9-95a2-4fe3d800a710.png)

### Reproduction steps
mpv /Users/enterprise/Dropbox/1200mm\ 1500\'\ tracks\ IS\ on.MP4 --log-file=/Users/enterprise/Documents/output.txt --hwdec=auto

show green screen, failed to decode using hardware.

![screenshot 2018-12-19 11 24 03](https://user-images.githubusercontent.com/45319190/50197700-4d0ff000-0383-11e9-91d8-8599220d504f.png)

![screenshot 2018-12-19 11 24 28](https://user-images.githubusercontent.com/45319190/50197711-5436fe00-0383-11e9-849b-c3f6043ebb11.png)

### Log file

[output1.txt](https://github.com/mpv-player/mpv/files/2693180/output1.txt)

### Reproduction steps
mpv /Users/enterprise/Dropbox/1200mm\ 1500\'\ tracks\ IS\ on.MP4 --log-file=/Users/enterprise/Documents/output.txt --hwdec=videotoolbox-copy

video works but very slowly and gitter, play one second video during 1.5~2 seconds.

![screenshot 2018-12-19 11 47 50](https://user-images.githubusercontent.com/45319190/50197863-0c64a680-0384-11e9-9538-6294edfc65ac.png)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/2693187/output.txt)

### Sample files

https://www.dropbox.com/s/3k6jqjqkaoenv5a/1200mm%201500%27%20tracks%20IS%20on.MP4?dl=0

https://www.dropbox.com/s/0x025bdhzbdl03t/150mm%205.MOV?dl=0

**Comment by Akemi** [comment]
ffmpeg ticket https://trac.ffmpeg.org/ticket/8736#ticket
