### ISSUE TITLE
OSX specify --screen with multiple workspaces and multiple screens per monitor

### ISSUE THREAD

**Issue by prankousky** [mpv-player/mpv#6398]
Hi everybody,

I run mpv `0.29.1` on `macOS 10.14 Mojave`. The macbook is closed and displaying on two external monitors.

This is the command I run `mpv --no-config --geometry=100%+0+0 --screen=0 --ontop <url>` to view an HTTP .ts-stream within my local network.

I use `iTerm2` as my terminal, which runs fullscreen on my left monitor. Upon running the command, mpv will open a new window on the left monitor (which is screen 0), using the "nearest" workspace not displaying a fullscreen app.

My left monitor workspace kinda looks like this

* Workspace 0: iTerm2, fullscreen
* Workspace 1: Telegram, Plex, not fullscreen
* Workspace 2: LibreOffice doc1, fullscreen
* Workspace 3: LibreOffice doc2, fullscreen

I always work with this layout, and it is always the same until I restart my macbook (and then have to recreate this layout).

Now, Workspace 1 is the only workspace not displaying fullscreen content, so mpv will put the video there. My current solution (I *just* started using mpv for displaying these streams; before, I only used mpv as a player for videos on my harddrive and viewed those streams on my Android phone) is to manually create `Workspace 4` with nothing on it, then drag all mpv windows -only two at the moment- onto Workspace 4. This works, but it would be so much more convenient if there was a way to tell mpv to use (*or create*, if it does not exist yet!) ~~Workspace 4~~ **a new workspace** for these streams.

Similar to how tmux allows you to address a specific session, window, and pane by (syntax not correct, just an example) `<command> -<parameter> <session>:<window>.<pane>`. Is this possible in mpv? Something like `mpv (...) --screen=0:4`, `--screen=0.4`, or similar (those commands do not work, so if there is a parameter for this, it must be different)?

Thanks in advance for your help 👍

**Comment by ePirat** [comment]
Afaik there is no API that allows to do this on macOS. The only thing I know that controls this a little bit is the `NSWindowCollectionBehavior` but that still does not help much for what you want.

**Comment by Akemi** [comment]
yeah, Apple doesn't provide an (official/public) API for this. so it's impossible to do. you should send you request to Apple.
