### ISSUE TITLE
Error parsing option cdrom-device (option not found)

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#6399]
### mpv version and platform
mpv 2:0.29.1+git~ amd64 on Ubuntu 16.04.5 LTS
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
`mpv cdda:// --cdrom-device=/dev/cdrom`
### Expected behavior
The audio CD is played
### Actual behavior
```
Error parsing option cdrom-device (option not found)
Setting commandline option --cdrom-device=/dev/cdrom failed.

Exiting... (Fatal error)
```
### Log file
[cdda_output.txt](https://github.com/mpv-player/mpv/files/2701103/cdda_output.txt)

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
You compiled without cdda support.

**Comment by sebma** [comment]
@CounterPillow With `--enable-cdda` ?

**Comment by CounterPillow** [comment]
Yes, though you need to have the necessary dependencies installed for that to succeed.

**Comment by mc4man** [comment]
In regards to the build(s) you are using,
I removed cdda support  in march 2017, you're the 1st to complain since then. I guess i could add back next build though won't do builds specifically for that.
Honestly you'd have to search far & wide to find a worse audio cd player than mpv..

**Comment by sebma** [comment]
@mc4man I use `mpv` because it's the fastest and one of the best player in my opinion. I use to play any audio/video file type :-)

**Comment by uralets** [comment]
> @mc4man I use `mpv` because it's the fastest and one of the best player in my opinion. I use to play any audio/video file type :-)

fanboism would be a poor driver behind software development.
