### ISSUE TITLE
Screen tearing in fullscreen, not in windowed (Windows 10)

### ISSUE THREAD

**Issue by rikkarudo** [mpv-player/mpv#6402]
I'm experiencing screen tearing when in fullscreen, I'm on Windows 10 64 bit.

I'm using the latest build, I tried other and older builds but I still get the tearing only in fullscreen.
I tried other players and I don't get the tearing.
I tried putting `edwmflush=windowed` line in the .conf file, also `tried vo=opengl`, `angle` and `backgend=dxinterop`.

**Comment by zc62** [comment]
Use `--log-file` (https://mpv.io/manual/master/#options-log-file) to generate a full log and attach to your issue, otherwise this issue is most likely to be labeled as 'ignored-issue-template' and closed/ignored.

**Comment by flesti** [comment]
Having the same problem in Win 7
Tearing only in full screen. Tried various configurations.

Win 7 SP1 x64
gtx 960
amd 6300

[mpv.log](https://github.com/mpv-player/mpv/files/2962226/mpv.log)

**Comment by zc62** [comment]
Generate the log while playing an actual file in fullscreen mode. I'd guess it is related to some configurations in the Nvidia control panel. Make sure you have it set to vsync there.

**Comment by flesti** [comment]
I played a little with the vsync options and it completely disappeared. With some gpu load tax, but nothing important.  
I didn't know those sync options were there. 
Thank you.

[mpv.log](https://github.com/mpv-player/mpv/files/2962759/mpv.log)

**Comment by geart891** [comment]
> I played a little with the vsync options and it completely disappeared. With some gpu load tax, but nothing important.
> I didn't know those sync options were there.
> Thank you.
> 
> [mpv.log](https://github.com/mpv-player/mpv/files/2962759/mpv.log)

Do you mind sharing your settings, my mpv tearing when fullscreen and Im struggling to find a fix.

**Comment by flesti** [comment]
> Do you mind sharing your settings, my mpv tearing when fullscreen and Im struggling to find a fix.

Unfortunately I run on to several other problems and decided to quit the player back then. I don't have my settings anymore.

**Comment by YellowOnion** [comment]
Both "off unless application specified", "on unless application specified", cause tearing, why the app is explicitly turning vsync off.

I can force it in my control panel and it works, but why? like why would you ever need vsync disabled in a video app, I have vsync off by default because it causes input lag in video games, but no other app like VLC or Kodi has issues with vsync.

perhaps consider using a fullscreen window too, since everyone is doing that these days and doesn't cause weird flickering when going full screen.

**Comment by refriedfood** [comment]
I have this exact same problem right now. Is there something specific in the conf files I can put to prevent this?

**Comment by ElasticBind** [comment]
> I have this exact same problem right now. Is there something specific in the conf files I can put to prevent this?

`video-sync=display-resample` seems to work.

**Comment by refriedfood** [comment]
> `video-sync=display-resample` seems to work.
Unfortunately, that didn't do anything for me.
