### ISSUE TITLE
Screen tearing in fullscreen, not in windowed (Ubuntu 18.10) (60fps with gpu-hq and vaapi)

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#6404]
### mpv version and platform
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.23.101
   libavcodec      58.39.100
   libavformat     58.22.100
   libswscale      5.4.100
   libavfilter     7.44.100
   libswresample   3.4.100
ffmpeg version: 4.1.git
```
`Linux 4.20.0-042000-generic`
```
Graphics:  Device-1: AMD Baffin [Radeon RX 460/560D / Pro 450/455/460/555/560] driver: amdgpu 
           v: kernel 
           Display: x11 server: X.Org 1.20.1 driver: amdgpu resolution: 1920x1080~60Hz 
           OpenGL: renderer: AMD Radeon RX 460 Graphics (POLARIS11 DRM 3.27.0 
           4.20.0-042000-generic LLVM 8.0.0) 
           v: 4.5 Mesa 19.0.0-devel - padoka PPA
```
### Reproduction steps
play 4K 60fps video with vaapi in fullscreen with gpu-hq
### Expected behavior
No screen tearing
### Actual behavior
Screen Tearing in the top right corner.
### Log file

https://0x0.st/sdwn.json
[log.zip](https://github.com/mpv-player/mpv/files/2707435/log.zip)

**Comment by CounterPillow** [comment]
If you've got it enabled, try disabling fullscreen unredirection in your compositor.

**Comment by laichiaheng** [comment]
@CounterPillow How to do it? I'm using Gnome3 desktop.

**Comment by CounterPillow** [comment]
I don't use GNOME3 so I can't help you there, but the alternative is setting the "TearFree" option in your xorg configuration to force the driver to vsync even if the compositor doesn't.

**Comment by laichiaheng** [comment]
@CounterPillow I do enable the TearFree option for amdgpu
```
/etc/X11/xorg.conf.d/20-amdgpu.conf
Section "Device"
     Identifier "AMD"
     Driver "amdgpu"
     Option "TearFree" "true"
     Option "DRI" "3"
EndSection
```

**Comment by haasn** [comment]
I think I have this bug too. It's sporadic, and when it happens it can usually be fixed by disabling and re-enabling TearFree (using xrandr)

**Comment by aufkrawall** [comment]
> I think I have this bug too. It's sporadic, and when it happens it can usually be fixed by disabling and re-enabling TearFree (using xrandr)

I suspect in this case, TearFree might be actually causing the tearing. At least I noticed such behavior with radv. I found amdvlk (and radeonsi) driver to work better with it.

Regarding tearing with Gnome: I think Gnome's unredirect for fullscreen windows is notoriously broken, it e.g. regularly fails to re-enable after alt + tabbing out of fullscreen windows.
Who knows what else might be broken, I'd give other DEs with optional compositor (e.g. Xfce) a try for troubleshooting.

**Comment by laichiaheng** [comment]
@aufkrawall None of the option of `--x11-bypass-compositor` fix the problem, `vaapi-copy` is the temporary solution for me now.

**Comment by aufkrawall** [comment]
I forced my display via edid to exact 60Hz and played a 4k 60fps juddertest video in mpv with gpu-hq profile + vaapi, doesn't show any tearing nor other anomalies here with RX 580 (not even on Gnome).

**Comment by laichiaheng** [comment]
@aufkrawall It only appears on the top right corner of the video, other part of the video are fine.

**Comment by aufkrawall** [comment]
Yeah, I paid attention to that as well.

**Comment by laichiaheng** [comment]
@aufkrawall What kernel are you using? I'm on 4.20 now.

**Comment by aufkrawall** [comment]
Yep, 4.20. I also tested both amdgpu.dc=1 and 0.

**Comment by laichiaheng** [comment]
@aufkrawall I tried it on Wayland, there is no such problem in Wayland, however, mpv performs worse on Wayland than Xorg.

**Comment by laichiaheng** [comment]
@aufkrawall I tested it on XFCE4, it still happens, then I test the 4K60fps video with vdpau hwdec, it works perfectly, however, vdpau doesn't support the HDR content, vaapi is the only option for me.

What distro are you using? Arch?

**Comment by aufkrawall** [comment]
I'm on Arch. If this is distro specific, it's probably neither the driver's nor mpv's fault.
Can't say anything about the output format, I'm with RGB anyway due to DL-DVI.

**Comment by laichiaheng** [comment]
@aufkrawall After I switch my GPU to RX580, problem is solved.

**Comment by aufkrawall** [comment]
Really weird, before the 580 I also used a 560 without problems.
There are btw. quite some fixes in git-master of the xf86-video-amdgpu DDX driver vs. the latest stable version.

**Comment by laichiaheng** [comment]
@aufkrawall Maybe it's the hardware specific problem? They have worse support on older hardware
