### ISSUE TITLE
no sound using ao=coreaudio_exclusive mode

### ISSUE THREAD

**Issue by oxnatun** [mpv-player/mpv#6406]
### mpv version and platform

build by stolendata
mpv-0.29.1
OS X

### Reproduction steps
With empty config file all works fine
All audio interfaces works fine 

configuring mpv.conf file in this way:
ao=coreaudio_exclusive

All works fine with built-in audio device
All works fine with AVID MBOX3 audio interface
No sound with UAD Apollo x16 interface, no sound at any video or audio file format, no audio tracks can be switched
### Expected behavior
That UAD Apollo x16 works with exclusive mode
### Actual behavior
No sound with Universal Audio Apollo x16 thunderbolt interface when exclusive mode is on
### Log file

Track switched:
 (+) Video --vid=1 (*) (h264 1920x800 23.976fps)
     Video --vid=2 [P] (png)
     Video --vid=3 (mjpeg 640x266 0.003fps)
 (+) Audio --aid=1 --alang=rus (*) (aac 2ch 48000Hz)
     Audio --aid=2 --alang=rus (aac 2ch 48000Hz)
     Audio --aid=3 --alang=rus (aac 2ch 48000Hz)
     Audio --aid=4 --alang=ukr (aac 2ch 48000Hz)
     Audio --aid=5 --alang=eng (aac 2ch 48000Hz)
     Audio --aid=6 --alang=eng (aac 2ch 48000Hz)
     Audio --aid=7 --alang=rus (ac3 6ch 48000Hz)
     Audio --aid=8 --alang=rus (ac3 6ch 48000Hz)
     Audio --aid=9 --alang=rus (ac3 6ch 48000Hz)
     Audio --aid=10 --alang=ukr (ac3 6ch 48000Hz)
     Audio --aid=11 --alang=eng (ac3 6ch 48000Hz)
 (+) Subs  --sid=1 --slang=rus (*) (mov_text)
     Subs  --sid=2 --slang=ukr (mov_text)
     Subs  --sid=3 --slang=rus (mov_text)
     Subs  --sid=4 --slang=rus (mov_text)
     Subs  --sid=5 --slang=ukr (mov_text)
     Subs  --sid=6 --slang=eng (mov_text)
     Subs  --sid=7 --slang=eng (mov_text)
[ao/coreaudio_exclusive] unsupported number of channels: 36 > 16.
[ao] Failed to initialize audio driver 'coreaudio_exclusive'
Could not open/initialize audio device -> no sound.
Audio: no audio

Exiting... (Quit)

### Sample files

any video file

**Comment by Akemi** [comment]
probably related to #5042.
