### ISSUE TITLE
Drop-outs with TrueHD bitstreaming.

### ISSUE THREAD

**Issue by Mitzsch01** [mpv-player/mpv#6407]
### mpv version and platform
mpv-git - mpv 0.29.0-106-g5bcac8580d

### Reproduction steps
Play a file that has a TrueHD (Atmos) track and exceeds 11 Mbits in some scenes. 
(EDIT) Test file
https://streams.videolan.org/ffmpeg/incoming/truehd_11mbit_bug.mkv

### Expected behavior
mpv should passthrough the TrueHD track fine. The file should play without drop-outs.

### Actual behavior
On high bitrate parts, playback stops immediately. (but only on these parts where the bitrate goes beyond 11 Mbits. When skipping over these parts playback continues just fine) 

### Log file
[Log-File.log.txt](https://github.com/mpv-player/mpv/files/2710137/Log-File.log.txt)

### Equivalent Issue 
-> it is exactly the same situation.
https://github.com/Nevcairiel/LAVFilters/issues/208

Really an FFmpeg bug?

**Comment by wm4** [comment]
```
[ffmpeg] spdif: Too large TrueHD frame of 2618 bytes is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[ffmpeg] spdif: If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
```
You could have read the log output. FFmpeg bug, closing.

**Comment by Mitzsch01** [comment]
You are right! That´s why I have opened an FFmpeg bug report 9 months ago and forgotten to close this one here.
-> https://trac.ffmpeg.org/ticket/7731
