### ISSUE TITLE
[Feature Request] Play from clipboard

### ISSUE THREAD

**Issue by narimiran** [mpv-player/mpv#6408]
It would be nice to have an option to play a video/URL which is in clipboard — this would allow making a keybinding/shortcut which would make 'play in MPV' one-click option. See below:

### Current workflow

1. Find video
1. Copy URL address
1. Open terminal
1. Type `mpv "`
1. Paste address
1. Type `"`
1. When finished, close terminal

### Proposed workflow

1. Find video
1. Copy URL address
1. Press a key combination of your choice, which would call `mpv --from-clipboard` and play the video

### New feature

Flag `--from-clipboard` should be added, which would basically append `"<clipboard content>"`.

If such behaviour is already possible, please let me know because I couldn't find it in the [mpv manual](https://mpv.io/manual/stable/).

**Comment by j605** [comment]
How about using `mpv $(xclip -o)`.

**Comment by CounterPillow** [comment]
Or if you don't have xclip but xsel installed, you can do mpv $(xsel -bo).

What I think might be useful thought is a play from clipboard keybinding for the pseudo-gui, mostly on Windows, since drag-and-dropping URLs can be a bit awkward for those people.

**Comment by narimiran** [comment]
Thank you @j605 and @CounterPillow! Your suggestions work like charm!

I'll leave this open for now, but if somebody wants to close it, be my guest.
