### ISSUE TITLE
[vo/gpu/vaapi-egl] vaAcquireSurfaceHandle() failed (invalid VASurfaceID)

### ISSUE THREAD

**Issue by arvidjaar** [mpv-player/mpv#6411]
### mpv version and platform
Installed: 2:0.29.1+git1~zzbionic
### Reproduction steps
Just try to play video
### Expected behavior
No error message
### Actual behavior
Error message as in title

I am aware of https://github.com/mpv-player/mpv/issues/5601, but error is different (and I am on libva and intel-vaapi 2.1):

i965-va-driver:amd64	2.1.0-0ubuntu1
libva2:amd64	2.1.0-3

There is also https://github.com/intel/media-driver/issues/415 which suggests that vaAcquireSurfaceHandleis not actually implemented (although provided) and recommends using vaExportSurfaceHandle instead.

**Comment by philipl** [comment]
The [error message](https://github.com/mpv-player/mpv/blob/master/video/out/opengl/hwdec_vaegl.c#L352) says `vaAcquireSurfaceHandle` but it's actually caling `vaExportSurfaceHandle`, as it should.

This happens as part of the probing loop that is done to establish which surface formats work with the hwdec. IIRC, it's yuv422 that fails. So ultimately it's harmless, but perhaps suggests that the message level of this error should be reduced so it doesn't appear by default (most hwdec init errors do not appear by default so there isn't a mess of errors when probing through multiple hwdecs to find one that works)

**Comment by tomty89** [comment]
```
[vo/gpu] Loading hwdec driver 'vaapi-egl'
[vo/gpu/vaapi-egl] Trying to open a x11 VA display...
[vo/gpu/vaapi-egl/vaapi] libva: VA-API version 1.3.0
[vo/gpu/vaapi-egl/vaapi] libva: va_getDriverName() returns 0
[vo/gpu/vaapi-egl/vaapi] libva: Trying to open /usr/lib/dri/i965_drv_video.so
[vo/gpu/vaapi-egl/vaapi] libva: Found init function __vaDriverInit_1_3
[vo/gpu/vaapi-egl/vaapi] libva: va_openDriver() returns 0
[vo/gpu/vaapi-egl/vaapi] Initialized VAAPI: version 1.3
[vo/gpu/vaapi-egl] using VAAPI EGL interop
[vo/gpu/vaapi-egl/vaapi] libva: vaExportSurfaceHandle: fourcc 48323234 is not supported for export as separate planes.
[vo/gpu/vaapi-egl] vaAcquireSurfaceHandle() failed (invalid VASurfaceID)
[vo/gpu/vaapi-egl] Supported formats:
[vo/gpu/vaapi-egl]  yuv420p
[vo/gpu/vaapi-egl]  yuv420p
[vo/gpu/vaapi-egl]  nv12
[vo/gpu/vaapi-egl]  rgb0
[vo/gpu/vaapi-egl]  bgr0
[vo/gpu/vaapi-egl]  p010
```
Wonder why yuv420p is listed twice.

**Comment by rien333** [comment]
@philipl  any way to suppress this message, or any progress on suppressing it? Although I understand that's harmless, it's clutter and it gives me a little fright every time I see it (which is quite often),
