### ISSUE TITLE
No video playback with gpu-api=vulkan in Ubuntu 18.10

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#6416]
### mpv version and platform

```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.23.101
   libavcodec      58.39.100
   libavformat     58.22.100
   libswscale      5.4.100
   libavfilter     7.44.100
   libswresample   3.4.100
ffmpeg version: 4.1.git
```

### Reproduction steps
`mpv --no-config --vo=gpu --gpu-api=vulkan --hwdec=vaapi --gpu-context=x11vk video.mp4`
### Expected behavior
No problem
### Actual behavior
```
[vo/gpu/vulkan] Failed initializing SPIR-V compiler!
[vo/gpu] Failed initializing any suitable GPU context!
Error opening/initializing the selected video_out (--vo) device.
Video: no video
```
### Log file

https://0x0.st/s5CA.txt

**Comment by mc4man** [comment]
See https://github.com/mpv-player/mpv/issues/6124

**Comment by mc4man** [comment]
If you'd like there is a now a build in the pa that has **shaderc shaderc-shared vulkan** enabled. It's atm only for 18.04.
https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests
I don't use vulkan nor can test whether it works fine, bad or not at all.
(- or the shaderc package there is generically dependent, you could likely use in 18.10 & build from there.
