### ISSUE TITLE
vobsub scaling?

### ISSUE THREAD

**Issue by cdown** [mpv-player/mpv#6417]
Let me know if there's a preferred place to ask questions about mpv, but I've been looking through the documentation and didn't come up with anything.

Is there some way to scale vobsub/dvd_subtitle with mpv? I know it's essentially just a bunch of images, but it would be nice if it could at least be manually upscaled and realigned on top of the video being played if desired.

I saw `--sub-scale`, but it seems it only works with textual formats where the text is rendered by mpv.

**Comment by zc62** [comment]
Where should the upscaled image be placed? Just fixing the center position may make large subtitles go outside the bottom of the screen, if the original subtitle is placed close enough to the bottom.

**Comment by cdown** [comment]
I suppose there should also be an equivalent ability to bind a key to move the subtitle vertically or horizontally, indeed.

The general problem of overrunning the bounds still exists with srt/ass subtitles, though, with a high enough font size and long enough line. I see this in Chinese subtitles fairly frequently.

**Comment by zc62** [comment]
Made a PR. Could you test it?

**Comment by Akemi** [comment]
implemented in https://github.com/mpv-player/mpv/commit/0cd8ba72fe47d11b196adc2ad1f64b1243312d2e
