### ISSUE TITLE
libmpv: none of the scale filters work on iOS

### ISSUE THREAD

**Issue by stps** [mpv-player/mpv#6418]
I’ve been playing with libmpv on iOS and am noticing some issues trying to use the scale filters. I know iOS isn’t well supported but figure this might still be worth posting in case anyone recognizes these symptoms:

### mpv version and platform

Using libmpv 0.29.1 on iOS 12.

### Reproduction steps

Playing a video using vo=libmpv and all default options, it looks normal. However, if I try playing it with a scale filter besides bilinear (e.g. `mpv_set_option_string(mpv, “scale”, "spline36”)`) I notice aliasing. The other filters besides bilinear don’t seem to be working at all since when I compare them (tried most from the list) they all appear visually the same, with the same issues.

### Expected behavior

Filters should work correctly... unless I'm overlooking something about expected compatibility.

### Actual behavior

If I do `mpv_set_option_string(mpv, “scale”, "bilinear”)`, it looks normal. If I replace bilinear with anything else, I get poor looking output with aliasing.

### Log file

Debug log file: https://0x0.st/sRie.log

### Sample files

Here are some comparisons:
https://0x0.st/sRi_.png
https://0x0.st/sRi2.png

**Comment by haasn** [comment]
Can you try [this test file](https://0x0.st/sRoa.png)?

**Comment by haasn** [comment]
It's possible the issue is something else, not scaling. Maybe it's chroma scaling that's causing you issues? Try a different `cscale` setting.

Also, the first thing you should try doing when investigating quality issues is setting `--profile=gpu-hq`. That sets a bunch of related options to their sane "quality" defaults. If it ends up too slow, try disabling debanding (`--deband=no`).

**Comment by haasn** [comment]
But for the record, I agree that something looks wrong about your screenshots. So I do believe there's something broken somewhere, especially if it only happens on iOS. It just means we need to dig deeper.

**Comment by stps** [comment]
Alright I just looked at things a bit more. I tried `profile=gpu-hq` on my iPad (A9), and it works and has good performance, but the visual issue is still there.

However, when I tried it on my iPhone (A11) with the same file, the video is completely black (though it still shows styled subtitles) whenever `deband=yes`.

I noticed there is a GPU trace feature for iOS that shows all the textures in the rendering pipeline, so I'll try to see what info I can get out of that.

**Comment by stps** [comment]
@haasn I was able to export some textures, and I think this reveals the scale filter issue:

https://0x0.st/sRT6.zip (.zip of 15 texture PNGs from `profile=gpu-hq` render)

It looks like texture6->texture8 and texture10->texture12 both get nearest-neighbor scaled (or similar) in only their height. I’m guessing those are the scale and cscale happening...

And in the trace that there are `glDrawArrays(GL_TRIANGLES, 0, 6)` calls happening involving those textures and the distorted looking ones (7 and 11).
