### ISSUE TITLE
Improving/extending the mpv-identify.sh script

### ISSUE THREAD

**Issue by birdie-github** [mpv-player/mpv#6420]
Since `mplayer` is more or less dead it would be great to replace it with `mpv-identify.sh` for all supported file formats however at the moment for audio files it doesn't output any relevant info, like `title`, `artist`, `album`, `album_artist`, `genre`, `year`, `track number`, etc. etc. etc. E.g. M4A files contain a whole lot of tags I'm willing to see.

I'm curious if this script could output _all the tags and information_ without hiding or omitting anything.

Thank you!

**Comment by wm4** [comment]
See --display-tags.
