### ISSUE TITLE
Freezing MJPG video when stepping back frame-wise or jumping in playback with the progress bar

### ISSUE THREAD

**Issue by Pascal-H** [mpv-player/mpv#6422]
### mpv version and platform
mpv 0.27.2
Ubuntu 18.04.1 LTS

### Reproduction steps
For a project, I am trimming video files from Guvcview-webcam recordings with frame-wise precision. In mpv, I use the OSC to get the milliseconds timestamps for the frames at which I cut (thanks to osc.conf: timems=yes). This works like a charm for videos in H.264 and I love mpv for its support of frame-wise stepping.
[ffmpeg info: Video: h264 (High), yuv420p(progressive), 1280x1024; Audio: pcm_f32le]

Additionally to H.264 encoded files, I also have files from Guvcview in the raw MJPEG format (quite a specific use-case, I know).
[ffmpeg info: Video: mjpeg (MJPG / 0x47504A4D), yuvj422p(pc, bt470bg/unknown/unknown), 1280x1024; Audio: pcm_f32le, 44100 Hz, mono]

With these files, I have some trouble for frame-wise stepping in mpv.

### Expected behavior
In the raw MJPEG files, I want to step frame-wise forwards and backwards with the '.' and ',' shortcuts. The respective frames should be displayed in the player window. I also want to click the part of the progress bar to which I want to jump.

### Actual behavior
Stepping forwards with '.' works fine.
If I step back with ',' however, not the respective frame is displayed, but the previous one is frozen in the player window. Even if I step forwards again with '.' or try to continue playing with space bar, frame stays frozen, even though the audio and time stamps  in the  the OSC keep progressing.
When I then start the player anew, stepping forwards works again.

When I use the progress bar in the OSC and click at an arbitrary position to jump there with the playback, the same as above happens: the frame before jumping is frozen and playback of audio and timestamps commences without the video progressing.

I'd be very grateful for help, since I enjoy the workflow with mpv quite a lot so far :)

### Log file
mpv --log-file=~~/output.txt my_video-27.mkv generates the following log:
https://0x0.st/sRpF.txt

The following line catches my eye:
[ffmpeg/video] mjpeg: unable to decode APP fields: Invalid data found when processing input

### Sample files
A sample video recorded with Guvcview:
https://0x0.st/sRfz.mkv

**Comment by CounterPillow** [comment]
```[   5.843][d][cplayer] video EOF (status=5)```

@jeeb (or anyone else who works on FFmpeg) do you know if this could be another 0 != EOF confusion inside FFmpeg?

**Comment by haasn** [comment]
Can confirm the bug.

**Comment by wm4** [comment]
This is because the mjpeg video packets are not marked as keyframes. I consider this a broken file. ``--demuxer=lavf`` works for whatever reasons (something sets the keyframe flags after the actual demuxer). In mpv it works if you add ``track->require_keyframes = true;`` to the video track if the codec is mjpeg. (There is obviously no such thing as non-keyframe mjpeg frames, so this should always work.)
