### ISSUE TITLE
Problem with sub-shadow-offset and sub-back-color 

### ISSUE THREAD

**Issue by H9j8** [mpv-player/mpv#6425]
I have problem with **sub-shadow-offset** and **sub-back-color** will make subtitle line overlap the other if two lines have a match time. How can I fix that?

**Example mpv.conf:**

sub-font-size=36
sub-font='Georgia'
sub-shadow-offset=15
sub-back-color='#000000'

**Example subtitle file:**

```
1
00:00:00,000 --> 00:00:05,000
Lorem Ipsum is simply dummy text of the printing and typesetting industry. 

2
00:00:02,000 --> 00:00:07,000
Neque porro quisquam est qui 
dolorem ipsum quia dolor.

3
00:00:04,000 --> 00:00:09,000
Sed ut perspiciatis unde omnis iste natus error 
sit voluptatem accusantium.
```

*Result:*

![download](https://user-images.githubusercontent.com/12744590/50732753-81711200-11b3-11e9-989d-b16c5113641c.png)

**Comment by zc62** [comment]
Can reproduce with the following ass subtitle:
```
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Georgia,60,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,3,30,0,2,30,30,30,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:05.00,Default,,0,0,0,,Lorem Ipsum is simply dummy text of the printing and typesetting industry.
Dialogue: 0,0:00:02.00,0:00:07.00,Default,,0,0,0,,Neque porro quisquam est qui dolorem ipsum quia dolor.
Dialogue: 0,0:00:04.00,0:00:09.00,Default,,0,0,0,,Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.
```

This is what mpv shows:
![mpv](https://user-images.githubusercontent.com/17048823/53612557-d40def80-3ba0-11e9-86a2-382c6d4038b5.png)

This is what MPC-BE+XySubFilter shows:
![mpc](https://user-images.githubusercontent.com/17048823/53612588-f6a00880-3ba0-11e9-9bc0-cd61c1a56803.png)

Should be a libass issue. File the issue [here](https://github.com/libass/libass/issues).

**Comment by zc62** [comment]
I reported it. See the link above.

**Comment by wm4** [comment]
Yeah, definitely a libass issue.
