### ISSUE TITLE
can't brew install mpv --with-uchardet --with-libbluray --with-vapoursynth

### ISSUE THREAD

**Issue by yangbao93** [mpv-player/mpv#6426]
I want to install svp for mac, first need to install mpv, but I use the command installation, need to install youtube-dl, I can download this file, but when the installation will report an error, this how to solve?
![image](https://user-images.githubusercontent.com/8946052/50734478-c2305180-11da-11e9-91cb-e42497605c8b.png)

**Comment by Akemi** [comment]
report it to homebrew not to us. though downloading youtube-dl forme exactly that url via homebrew works here. so it's a problem on your end.
