### ISSUE TITLE
Re-build in windows like (https://mpv.srsfckn.biz/)

### ISSUE THREAD

**Issue by Mitijz** [mpv-player/mpv#6429]
Hi, I`m beginner and have an issue with re-build Mpv player(https://mpv.srsfckn.biz/)

I did all (https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#native-compilation-with-msys2) and Installing MSYS2 and ...
At the end, I have Mpv.exe and Mpv.com in /mingw64/bin

But it is just 13Mb(The Original is 53Mb) and when I open it, It`s instantly closed.And when I want to change the dir to another folder, It shows some error that depends to .Dll and doesn`t open at all.

Can you help me complie a version same as (https://mpv.srsfckn.biz/)?
In (https://mpv.srsfckn.biz/ we have Mpv.exe that Open alone and every where)

I`m using windows.Is it possible?

**Comment by Mitijz** [comment]
> https://github.com/shinchiro/mpv-winbuild-cmake
> https://github.com/shinchiro/mpv-packaging

Untill `cmake -DTARGET_ARCH=x86_64-w64-mingw32 -G Ninja ..` every things right.
![1](https://user-images.githubusercontent.com/45237738/50775770-574f4b00-12ac-11e9-9e16-35d1c4b5f60d.jpg)

And how can I build toolchain? I don`t know what is it.

**Comment by zc62** [comment]
I recommend using a real linux to do it, or at least [archlinux wsl](https://github.com/yuk7/ArchWSL).

**Comment by Mitijz** [comment]
> I recommend using a real linux to do it, or at least [archlinux wsl](https://github.com/yuk7/ArchWSL).

![image](https://user-images.githubusercontent.com/45237738/50797789-335f2a00-12eb-11e9-8982-81bc1d91799b.png)
I copy the cmakelists.txt(https://github.com/shinchiro/mpv-winbuild-cmake/blob/master/CMakeLists.txt) to root folder

**Comment by zc62** [comment]
...Make sure you clone the entire project, not just downloading a single file. Follow the instructions closely.

**Comment by Mitijz** [comment]
> ...Make sure you clone the entire project, not just downloading a single file. Follow the instructions closely.

Thank you a lot.I`m here yet,
![image](https://user-images.githubusercontent.com/45237738/50799949-79b88700-12f3-11e9-9139-8aea6dd21e69.png)

**Comment by Mitijz** [comment]
I cant understand 
> First, you need to build toolchain. By default, it will be installed in install folder. This take ~20 minutes on my 4-core machine.


I will continue tomorrow and I am getting your help, thank you!

**Comment by Mitijz** [comment]
I will continue tomorrow and I am getting your help, thank you!

**Comment by Mitijz** [comment]
![image](https://user-images.githubusercontent.com/45237738/51073306-082a6100-1684-11e9-977f-9f949aca1fae.png)
I got this error.

> First, you need to build toolchain. By default, it will be installed in install folder. This take ~20 minutes on my 4-core machine.

>  what should I do, with ninja gcc toolchain install automatically?
