### ISSUE TITLE
gpu vo on wayland with default (X11) context drops lots of frames for videos above 60 FPS

### ISSUE THREAD

**Issue by YaLTeR** [mpv-player/mpv#6431]
### mpv version and platform
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1
```

Arch Linux x64, sway `1.0-beta.2-136-g14cab786 (Jan  9 2019, branch 'master')`, 144 Hz screen.

### Reproduction steps
Open a video above 60 FPS.

### Expected behavior
The video plays back smoothly.

### Actual behavior
Lots of frames are dropped, depending on the actual FPS. 72 FPS clips consistently drop some frames, 144 FPS clips drop lots. As though mpv is getting force-vsynced to 60 FPS or something and drops all faster frames. Using `--video-sync=display-resample` makes mpv play back a 144 FPS video in slow motion at first (I guess it tries to play back at 60 FPS frame by frame), then it resorts back to dropping frames.

It's worth noting that using `-vo=xv` results in smooth playback in an X11 window, and using `-gpu-context=wayland` results in smooth playback in a Wayland window.

### Log file
<https://gist.github.com/YaLTeR/b1041f91a319d864e1ce02e7b6b5e747>

### Sample files
<https://0x0.st/s7Qc.mp4> 144 FPS

**Comment by haasn** [comment]
Does disabling vsync in mpv help? (`--opengl-swapinterval=0`)

**Comment by YaLTeR** [comment]
Yeah, that also seems to give smooth playback.

**Comment by haasn** [comment]
So a couple of notes/questions:

1. Do you only see the dropped frames count going up, or does it actually look less smooth to your eye than in the case with `swapinterval=0`? In theory, the VO dropping frames when the source framerate exceeds the VO framerate is normal and/or expected. When you enable triple buffering, the frames that mpv would end up dropping are the same ones that end up never displaying due to the triple buffering. (Except that with triple buffering, we also waste GPU time rendering them)

2. Using `display-resample` on a 60 Hz vsynced display works fine for me. Again, the dropped frame skyrockets, but it doesn't disable DS or anything.

**Comment by YaLTeR** [comment]
It actually stutters the playback, yeah. The issue seems that the default configuration (gpu/x11 on wayland) seems to sync to 60 Hz incorrectly when the actual refresh rate is 144 Hz.

**Comment by haasn** [comment]
Oh, I see the issue. Your display is actually 144 Hz, so it shouldn't be vsyncing to 60 Hz to begin with. Never mind my previous comments.

Honestly, I'm not sure if this is an mpv bug. We don't do anything that would affect the refresh rate (other than enabling vsync), and mpv detects the monitor refresh rate correctly. Likely candidates are either the mesa wayland<->opengl WSI, or the wayland compositor. Can you test other compositors and see if the issue persists?

**Comment by YaLTeR** [comment]
I'm seeing the same behavior on weston.

**Comment by haasn** [comment]
What happens when you run `glxgears`? (Although that doesn't explicitly set swapinterval to 1, so it's at the mercy of what your opengl defaults are)

**Comment by YaLTeR** [comment]
`glxgears` draws at slightly lower than 60 FPS:
```
295 frames in 5.0 seconds = 58.923 FPS
293 frames in 5.0 seconds = 58.447 FPS
293 frames in 5.0 seconds = 58.416 FPS
```

**Comment by haasn** [comment]
Okay, then it's not an mpv bug. Closing here in favor of the other issue.

**Comment by aufkrawall** [comment]
This is one of those utterly stupid xwayland limitations, it's by its terribly stupid design that it renders at fixed fake 60Hz when vsync is enabled.
At least Mutter on Wayland now supports real vsync, maybe this is a good sign also for this issue.
