### ISSUE TITLE
Frame drops with SRT subtitle.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#6433]
### mpv version and platform
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.23.101
   libavcodec      58.39.100
   libavformat     58.22.100
   libswscale      5.4.100
   libavfilter     7.44.100
   libswresample   3.4.100
ffmpeg version: 4.1.git
```
### Reproduction steps
Play video with srt subtitle
### Expected behavior
Play smoothly
### Actual behavior
It drops frames when the subtitle appears.
### Log file
https://0x0.st/s7WP.txt
### Spec
`Linux HTPC 4.20.0-042000-generic #201812232030 SMP Mon Dec 24 01:32:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
`Intel(R) Core(TM)2 Quad CPU    Q8200  @ 2.33GHz`
`AMD Radeon RX 460`

**Comment by laichiaheng** [comment]
Someone says that it could be caused by `glTexImage2D`, isn't it?

**Comment by zc62** [comment]
Does it happen with any srt file or do you have a particular example? Could you upload the srt file that causes problems? Since I cannot reproduce this with srt files at my hand.

**Comment by laichiaheng** [comment]
@zc62 It happens to every srt file, but no problem with SUP file.

**Comment by zc62** [comment]
Well, still cannot imagine how this could even happen. Could you upload a smallest example (video piece + subtitle) that reproduces the issue. Also, what does the stats info say? (the rendering time when the subtitle is present). CPU/memory usage would probably be useful as well.

**Comment by astiob** [comment]
@Akemi Pretty sure this has nothing to do with upstream. SRT subtitles are extremely simple. This seems to be a rendering issue, which is entirely on mpv. But this could not have been debugged without the OP’s involved help, so closing this issue was probably right—just not the labels.

**Comment by Akemi** [comment]
since all info is gone, we and you can't even know if they were really srt subtitles. those lables might be appropriate. no this doesn't need to be an issue with just displaying. there can be other reasons.
