### ISSUE TITLE
Constant paused state

### ISSUE THREAD

**Issue by timidpimp** [mpv-player/mpv#6435]
### mpv version and platform

mpv-0.29.1 (2018-Oct-05) running on Mac OS 10.11.6

### Reproduction steps

Literally out of the blue video is in a constant paused state.  I can scrub through it fine, but the video never actually plays. Same with Mplayer Extended.  VLC performs perfectly.  The spacebar, the menu commands....  nothing gets the video to actually play.

### Expected behavior

Normal playback like always.

### Log file

None.  As there are no crashes or logged issues to speak of.

**Comment by CounterPillow** [comment]
Without a log file generated with `--log-file=mpvsucks.log` there's little chance of anyone being able to debug this.
