### ISSUE TITLE
Problems with many youtube videos. Behaviour changes when -v option added.

### ISSUE THREAD

**Issue by Barafu** [mpv-player/mpv#6440]
### mpv version and platform

mpv 0.29.0-107-gd6d6da4711  Windows 10, Nvidia 1080 Ti. 

### Reproduction steps

Since last year, I started to have problems with Youtube videos in mpv , including the ones I watched before without problems. Videos stutter, or sometimes video stops while audio goes on (no audio problems whatsoever). 
Interestingly, problems go away when I add -v option to mpv. Timing errors? Race condition? Voodoo?
Below are two Youtube links to videos that have problems, with timings about 1 minute before the problem part. 

### Expected behavior

A procrastinational bliss of Youtube. 

### Actual behavior

Videos halt and force me to write bug reports on GitHub. 

### Log file

My config: 
https://pastebin.com/8Um149Aa

The log with -v says:
https://pastebin.com/1kHF71zq

The log without -v:
https://pastebin.com/09fiiwYf

### Sample files
https://youtu.be/_-VEgf57Ie8?t=367 - fails every time
https://youtu.be/sWs5ogzzd0o - fails sometimes after 22 minute.

**Comment by garoto** [comment]
and your `youtube-dl.exe` is what version

**Comment by Barafu** [comment]
`youtube-dl.exe -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.01.10
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17763
[debug] exe versions: ffmpeg N-92621-g953bd58861, ffprobe N-92621-g953bd58861
[debug] Proxy map: {}`

I update them both with the script in Windows release.

**Comment by garoto** [comment]
> or sometimes video stops while audio goes on [...]
This happens for me when I left a YT video in a paused state for too long, so when resuming playback, mpv will play the remaining content already cached (150MiB by default IIRC) but the YT token for that session has already expired, so no more content can be fetched from the same `googlevideo` URL location anymore. I suspect audio keeps playing because it is, most of the time, loaded as an external source to the video (as DASH) and not accounted for on the cache display of the OSC. Plus, audio streams are much smaller bytewise and maybe they are fetched 100% and buffered in memory in less than a minute.

But otherise, the videos you posted both "works for me" using:
```
mpv 0.29.0-107-gd6d6da4711 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 30 11:01:30 DST 2018
ffmpeg library versions:
   libavutil       56.25.100
   libavcodec      58.42.104
   libavformat     58.25.100
   libswscale      5.4.100
   libavfilter     7.46.101
   libswresample   3.4.100
ffmpeg version: git-2018-12-29-fccba32b
```
And:
```
> youtube-dl.exe --version
2018.12.09
```
Both with my config and yours.

**Comment by Barafu** [comment]
So it is not a generic issue, but I still reliably get the first video stop every time at the exact spot. There is no difference whether I start the video from beginning, or from the middle with the time code. My log clearly shows some problems, and I'd be happy to provide any debug info needed. 
Even if the root cause is in the Youtube videos themselves, other videoplayers seem to deal with it.

**Comment by garoto** [comment]
Well, maybe try other `--ytdl-format` options, like `--ytdl-format="best"` to maybe narrow it down to specific formats or format combos.

`youtube-dl.exe --list-formats <URL>` to get a numeric code for all video+audio streams and then, e.g: `mpv --ytdl-format="243+251" "https://www.youtube.com/watch?v=_-VEgf57Ie8#t=367"

Another possibility is that your ISP google content cache is crapping up on specific formats for specific videos (have seen that happen more than once).

**Comment by garoto** [comment]
Here's my `--log-file` "https://www.youtube.com/watch?v=_-VEgf57Ie8#t=367" till the end of playback output for your perusal: https://0x0.st/s753.log

**Comment by Barafu** [comment]
Other formats, yes. I will do the testing and report in a day or two.

**Comment by haasn** [comment]
What happens if you download those videos (using `youtube-dl`) and play back the downloaded versions? (What if you download the video and audio streams separately and combine them with `--audio-file`?)

**Comment by Akemi** [comment]
please open a new issue if this still happens.
