### ISSUE TITLE
SMPlayer plays 60fps youtube videos at 30fps (but in 2k)

### ISSUE THREAD

**Issue by NKSHV** [mpv-player/mpv#6442]
### mpv version and platform
18.10.0 9144 64bit windows 10

### Reproduction steps
Open any youtube video with 60fps quality
### Expected behavior
Play video at 60 fps
### Actual behavior
Plays video at 30 fps

**Comment by Akemi** [comment]
we are not the smplayer support.

**Comment by NKSHV** [comment]
Wait i didn't post this yet how did you comment

**Comment by CounterPillow** [comment]
:ghost:
