### ISSUE TITLE
mpv automatically exits Split View on macOS

### ISSUE THREAD

**Issue by wwalexander** [mpv-player/mpv#6443]
### mpv version and platform

mpv 0.29.1 (via MacPorts), also reproduced with [stolendata.net's latest build (sha256:45d176bc884dfa84ce5226f53bc0809e2054984837e16a1518061e5493700f21)](
https://laboratory.stolendata.net/~djinn/mpv_osx/)

macOS 10.14.2

### Reproduction steps

* Open a new mpv window (either the "No file" screen or an actual file)
* Open another window capable of full-screen mode
* Add the two windows to a [Split View](https://support.apple.com/en-us/HT204948); either
    * hold down on the green full-screen button in the titlebar on either window, then select the other window, or
    * make either window full-screen (including by starting mpv with --fs), open [Mission Control](https://support.apple.com/en-us/HT204100), and drag the other window on top of the first window's Space

### Expected behavior

The two windows stay open in Split View.

### Actual behavior

mpv immediately exits the Split View, returning to a regular desktop window at full size.

### Log file

[Making another window full-screen, then adding mpv to the Split View](http://0x0.st/shBi.txt)
[Making mpv full-screen, then adding another window to the Split View](http://0x0.st/shBr.txt)
[Holding down the full-screen button](http://0x0.st/shaF.txt)
[Using mpv --fs](http://0x0.st/shah.txt)

**Comment by Akemi** [comment]
yeah i noticed. i fixed that once (https://github.com/mpv-player/mpv/commit/2b0b9bb6a1000a6f3aecabb628bb7e7246c4795b#diff-2854dc1202f3397c7dbda181ae3beb31), wonder when it broke again. maybe it's even a new behaviour of macOS 10.14.

feel free to bisect it, maybe i can fix it faster at weekend that way.

**Comment by Akemi** [comment]
just on a side note, that change isn't even in a release yet. the issue still occurs but only in certain cases.

**Comment by Akemi** [comment]
should be fixed with #6451.
