### ISSUE TITLE
How to secure video encrypted from Memory Dumping

### ISSUE THREAD

**Issue by BlackRouter** [mpv-player/mpv#6444]
hi guys
i have problem on play video Encrypted with FFmpeg.

**1: i will play video with mpv via this options:**
`mpv --demuxer-lavf-o=decryption_key=76a6c65c5ea762046bd749a2e632ccbb test.LKA
`
**Problem:**
when mpv play video with decryption key video stream on Physical Memory and video can dumped.
very easy find Decryption key with memory dumping.

How to fix this problem with mpv Options and secure video encrypted from dumping?

**Comment by CounterPillow** [comment]
I don't see this as being a problem. DRM is bad.

**Comment by haasn** [comment]
If you're playing back the video, that implies decrypting the video contents anyway? So the user could just as well dump those. Or the contents of the textures used for rendering. Or the framebuffer.

**Comment by lachs0r** [comment]
This is a platform problem, not an mpv problem. The operating system and hardware must be built to prevent memory dumping in the first place. In general, it helps to view DRM like a physical lock. It can never offer perfect protection. People *will* find a way around it.
