### ISSUE TITLE
CUDA device not recognized on Optimus systems

### ISSUE THREAD

**Issue by ehegnes** [mpv-player/mpv#6446]
### mpv version and platform
Version
```
mpv 0.29.0-112-g73fe0611b3-dirty Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Thu Jan 17 07:38:01 EST 2019
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1
```
Platform
```
Linux localhost 4.14.83-gentoo #1 SMP Tue Jan 8 23:37:23 EST 2019 x86_64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz GenuineIntel GNU/Linux
```

### Reproduction steps
`mpv --hwdec=cuda` and `mpv --hwdec=nvdec` fail to detect a CUDA device when run with `optirun` or `primusrun`.

### Expected behavior
`mpv` properly detects an appropriate CUDA device and offloads hardware decoding.

### Actual behavior
`mpv` fails to detect any CUDA devices.

### Log file
`primusrun mpv --no-config --hwdec=nvdec`: https://0x0.st/shep.txt
`primusrun mpv --no-config --hwdec=nvdec-copy`: https://0x0.st/sheW.txt

### Notables
`ffmpeg` successfully detects CUDA devices when run with `optirun` or `primusrun`. I checked this behavior with both `-hwaccel cuda` and `-hwaccel nvdec`.

`nvdec-copy` and `cuda-copy` work, but I am too unfamiliar with the internals to speculate accurately about this. #4262 does give me the impression that this could be an issue where the display device, X11, etc is using a `mesa` OpenGL implementation rather than nvidia's.

**Comment by lachs0r** [comment]
Looks like Bumblebee does not allow CUDA-OpenGL interop.

On the practical side, using CUDA for decoding on Optimus devices (laptops?) seems pointless, as these are usually paired with hwdec-capable Intel CPUs and just having the NVIDIA GPU powered on may add 10 W to the power consumption.

Anyway, I do have an Optimus laptop here for testing, but I’d have to install NVIDIA’s drivers. I currently have the NVIDIA GPU disabled at all times because Bumblebee bottlenecks it so much that it’s just as slow as the Intel integrated one. All it does is draw more power.

**Comment by ehegnes** [comment]
Despite a few conflicting sources in the bumblebee issues, I can confirm that CUDA/OpenGL interop does not work on bumblebee. Thank you for noting that! I was confused when `ffmpeg` worked, but it wasn't doing interop, so that makes sense.

Practically, I'm trying to upscale in realtime with GLSL shaders ([FSRCNN](https://github.com/igv/FSRCNN-TensorFlow) in particular), and I suspected it would run quicker on the discrete card, although I couldn't find any evidence of that online.

**Comment by CounterPillow** [comment]
>Practically, I'm trying to upscale in realtime with GLSL shaders (FSRCNN in particular), and I suspected it would run quicker on the discrete card, although I couldn't find any evidence of that online.

Probably, but that's unrelated to using CUDA for hardware decoding. The shader pipeline is unrelated to the decoding, aside from getting a buffer from some decoder (be it hardware or software uploaded to GPU)
