### ISSUE TITLE
mpv shouldn't attempt to find subtitles when playing from stdin

### ISSUE THREAD

**Issue by pxia** [mpv-player/mpv#6450]
### mpv version and platform

```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Nov  6 20:01:20 PST 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1
```

### Reproduction steps

1. `cd` into some directory that contains subtitle files whose name contains the character `-`.
2. pipe some video stream into `mpv -`. (Can be triggered by watching twitch stream via `streamlink`)

### Expected behavior

Shouldn't auto match any subtitles

### Actual behavior

`mpv` thinks the filename is `-` and matches subtitle files that contains the character `-`.

**Comment by garoto** [comment]
Can reproduce. `--sub-auto=fuzzy` seems to be the culprit. Tested with a YT video with no dashes in its filename or URL, and neither in the video title.
