### ISSUE TITLE
Question: should mpv be compiled with pie in linux?

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#6455]
Sorry to ask here, no good at irc..
In past when building pie/fpie was automatically added so for ex. would see this - 

$ hardening-check /usr/bin/mpv
/usr/bin/mpv:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: yes (some protected functions found)
 Read-only relocations: yes
 Immediate binding: yes

Due to a recent change in compiler this is no longer the case, i.e

hardening-check /usr/bin/mpv
/usr/bin/mpv:
 Position Independent Executable: no, normal executable!
 Stack protected: yes
 Fortify Source functions: yes (some protected functions found)
 Read-only relocations: yes
 Immediate binding: yes

I'm curious as to thoughts on whether pie should be used?

**Comment by lachs0r** [comment]
It should be used. And Linux distributions should enable PIE for packages by default.
