### ISSUE TITLE
Arabic Subtitle issue (squares and G letters)

### ISSUE THREAD

**Issue by Sir-Doyle** [mpv-player/mpv#6456]
### mpv version

mpv 0.29.1 on macOS Mojave 10.14.2

### Reproduction steps

Open movie with Arabic subtitle SRT

### Expected behavior

Font should be readable without any squares or G letters .. like this (please see the screenshot):
https://goo.gl/fq5TXr

### Actual behavior

there is issue on subtitle: there are squares and G letters ... like this (please see the screenshot):
https://goo.gl/Pc2tqw

### Log file

Log file at this link: https://goo.gl/ZjdtQw

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

for the test ... please download these file:
- srt file for the test with 7sec long (https://goo.gl/fX8kjn)
- blank video file mp4 (https://goo.gl/Wqrb5t)

**Comment by instagramtest** [comment]
Similar issue on the Windows version. Some Unicode characters are shown as boxes. https://vgy.me/HVyJaa.png

**Comment by haasn** [comment]
It works on my end. Some differences I spotted: (on my end)

```
osd/libass: Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.2.0 (COMPLEX)
...
   sub/ass: fontselect: (Liberation Sans, 400, 0) -> /usr/share/fonts/liberation-fonts/LiberationSans-Regular.ttf, 0, LiberationSans
   sub/ass: Glyph 0x623 not found, selecting one more font for (Liberation Sans, 400, 0)
   sub/ass: fontselect: (Liberation Sans, 400, 0) -> /usr/share/fonts/dejavu/DejaVuSans.ttf, 0, DejaVuSans
```

Maybe you need to try a different font, or a newer version of harfbuzz?

**Comment by Sir-Doyle** [comment]
> It works on my end. Some differences I spotted: (on my end)
> 
> ```
> osd/libass: Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.2.0 (COMPLEX)
> ...
>    sub/ass: fontselect: (Liberation Sans, 400, 0) -> /usr/share/fonts/liberation-fonts/LiberationSans-Regular.ttf, 0, LiberationSans
>    sub/ass: Glyph 0x623 not found, selecting one more font for (Liberation Sans, 400, 0)
>    sub/ass: fontselect: (Liberation Sans, 400, 0) -> /usr/share/fonts/dejavu/DejaVuSans.ttf, 0, DejaVuSans
> ```
> Maybe you need to try a different font, or a newer version of harfbuzz?

I know that it works with different font (Arabic font) ... the issue with a default config (without select a font)

**Comment by Sir-Doyle** [comment]
with other player if you leave it with a default font or select any font does not have Arabic characters, it will show you a default Arabic font without any issue.

here in mpv if you select font does not have Arabic characters, it will show you a default Arabic font with this issue (squares and G letters)

**Comment by haasn** [comment]
It works for me even with `--no-config`.

**Comment by Sir-Doyle** [comment]
> It works for me even with `--no-config`.

Could you please tell me your os and ver of mpv?

is the above log without config?

thanks

**Comment by Sir-Doyle** [comment]
please, any update?

**Comment by Jj0YzL5nvJ** [comment]
**mpv version and platform**
mpv 0.29.0-107-gd6d6da4711 / Xubuntu 16.04.5 LTS
`$ ffmpeg -version`
```
ffmpeg version N-92720-g63977ac38f Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 8 (Ubuntu 8.1.0-5ubuntu1~16.04)
configuration: --prefix=/usr/local --arch=amd64 --cpu=amd64 --cc=gcc-8 --cxx=g++-8 --extra-ldflags=-L/usr/local/lib --enable-gpl --enable-nonfree --enable-shared --enable-libfdk-aac --enable-libmp3lame --enable-librtmp --enable-libtls --enable-opengl --enable-libpulse --disable-debug --enable-libass --enable-libbluray --enable-libcaca --enable-libcdio --enable-libvpx --enable-libvorbis --enable-libtheora --enable-libopus --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg
libavutil      56. 24.101 / 56. 24.101
libavcodec     58. 42.102 / 58. 42.102
libavformat    58. 24.101 / 58. 24.101
libavdevice    58.  6.101 / 58.  6.101
libavfilter     7. 46.101 /  7. 46.101
libswscale      5.  4.100 /  5.  4.100
libswresample   3.  4.100 /  3.  4.100
libpostproc    55.  4.100 / 55.  4.100
```

**Actual behavior**
https://0x0.st/zzDf.jpg
https://0x0.st/zzDO.jpg
https://0x0.st/zzDV.jpg

**Log file**
https://0x0.st/zzDW.txt

**Comment by Sir-Doyle** [comment]
I know it works with Linux. it des not work on macOS, iOS and Apple TV; it works if I change the font or add (sub-text-font="") in configure file without specify the font name

Actually,  I'm using [emby](https://emby.media/).

[According to the developer, it used mpv in their client App (emby for ios and apple tv)](https://emby.media/community/index.php?/topic/68576-arabic-subtitle-issue/)

The developer want to use the system font of iOS to support all language. (with no config)

The mpv player is embedded in emby client app so I can not modify it.

Please try to fix this issue.

**Comment by Akemi** [comment]
works on macOS too with `--no-config`. must be a problem of the build used(?).
![screenshot 2019-02-17 at 18 45 13](https://user-images.githubusercontent.com/680386/52916797-32ef8100-32e4-11e9-9884-327c47d47a67.png)

**Comment by Sir-Doyle** [comment]
> works on macOS too with `--no-config`. must be a problem of the build used(?).
> ![screenshot 2019-02-17 at 18 45 13](https://user-images.githubusercontent.com/680386/52916797-32ef8100-32e4-11e9-9884-327c47d47a67.png)

I use this [https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-latest.tar.gz](https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-latest.tar.gz)

Could you please send the log file?

**Comment by Akemi** [comment]
sure, https://0x0.st/ziPa.log

**Comment by zc62** [comment]
Works here, no "Glyph not found" error. (Windows build)
```
[   0.218][v][sub/ass] Shaper: FriBidi 1.0.5 (SIMPLE) HarfBuzz-ng 2.3.1 (COMPLEX)
[   2.332][v][sub/ass] fontselect: (sans-serif, 400, 0) -> ArialMT, 0, ArialMT
```

Two macOS logs both contain something like:
```
[   3.458][v][sub/ass] fontselect: (sans-serif, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
[   3.459][v][sub/ass] Glyph 0x623 not found, selecting one more font for (sans-serif, 400, 0)
[   3.470][v][sub/ass] fontselect: (sans-serif, 400, 0) -> /System/Library/Fonts/GeezaPro.ttc, -1, GeezaPro
```
So `GeezaPro.ttc` is responsible for that character. Probably not related to HarfBuzz? (Akemi's build even does not have HarfBuzz?)

> it works if I change the font or add (sub-text-font="") in configure file without specify the font name

Could you provide corresponding logs? What if you specify `Helvetica.ttc` or `GeezaPro.ttc`?

**Comment by Sir-Doyle** [comment]
> Works here, no "Glyph not found" error. (Windows build)
> 
> ```
> [   0.218][v][sub/ass] Shaper: FriBidi 1.0.5 (SIMPLE) HarfBuzz-ng 2.3.1 (COMPLEX)
> [   2.332][v][sub/ass] fontselect: (sans-serif, 400, 0) -> ArialMT, 0, ArialMT
> ```
> Two macOS logs both contain something like:
> 
> ```
> [   3.458][v][sub/ass] fontselect: (sans-serif, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
> [   3.459][v][sub/ass] Glyph 0x623 not found, selecting one more font for (sans-serif, 400, 0)
> [   3.470][v][sub/ass] fontselect: (sans-serif, 400, 0) -> /System/Library/Fonts/GeezaPro.ttc, -1, GeezaPro
> ```
> So `GeezaPro.ttc` is responsible for that character. Probably not related to HarfBuzz? (Akemi's build even does not have HarfBuzz?)
> 
> > it works if I change the font or add (sub-text-font="") in configure file without specify the font name
> 
> Could you provide corresponding logs? What if you specify `Helvetica.ttc` or `GeezaPro.ttc`?

- using: sub-text-font="Geeza Pro" - same issue (https://bit.ly/2F99h3v)
- using: sub-text-font="Helvetica" - same issue (https://bit.ly/2HGYkJr)
- using: without any configuration - same issue (https://bit.ly/2TFMzdt)
- using: sub-text-font="Arial" - it works (https://bit.ly/2W5Yk9K)
- using: sub-text-font="" - it works (https://bit.ly/2TKfa12)

Thanks

**Comment by zc62** [comment]
I think the difference either in the "Geeza Pro" font (looks like an Arabic font) or the build you used. Do you have a chance to try other builds? Maybe you can try to use homebrew to compile the latest git master.

**Comment by Sir-Doyle** [comment]
> I think the difference is either in the "Geeza Pro" font (looks like an Arabic font) or the build you used. Do you have a chance to try other builds? Maybe you can try to use homebrew to compile the latest git master.

I have installed mpv using homebrew

`brew install mpv`

open video:

`mpv "Blank Video.mp4"`

unfortunately, same issue :(

log file: https://goo.gl/qGjiuK

**Comment by zc62** [comment]
Is there any way to verify that "Geeza Pro" on your machine really works or not? Could you test with other software to let "Geeza Pro" show those problematic characters?

**Comment by Sir-Doyle** [comment]
> Is there any way to verify that "Geeza Pro" on your machine really works or not? Could you test with other software to let "Geeza Pro" show those problematic characters?

- I do fresh install of macOS in Virtual Machine (Parallels Desktop), it has same issue
- I verify that my "Geeza Pro" works in my mac using Apple Pages  (screenshot: https://goo.gl/3Q7RrL)
- This is my "Geeza Pro" (Download: https://goo.gl/Dx8N5Z)

Also, could you please give me your "Geeza Pro" to test it in my mac

**Comment by zc62** [comment]
I don't own a mac. Maybe @Akemi

**Comment by Sir-Doyle** [comment]
> I don't own a mac. Maybe @Akemi

I think there is an issue in mpv, because the exactly same issue also there in [emby](https://emby.media/community/index.php?/topic/68576-arabic-subtitle-issue/)

**Comment by zc62** [comment]
Just tried the "Geeza Pro" you uploaded. Works perfectly here. I am afraid this is not a mpv issue. Try one more time reinstall mpv and its dependencies with current git HEAD.

Also, mpv is not responsible for displaying the subtitle. It is libass that renders the subtitle. You can try other players that use libass, for example VLC, to see if there is an issue.

**Comment by Akemi** [comment]
i have the exact same font installed, checked via hash.

no idea how you conclude that this is an mpv problem. it could be your system, it could be your build of mpv or it could be libass since the font provider is within libass. the warning is also [coming from libass](https://github.com/libass/libass/blob/98727c3b78f44cb3bbc955fcf5d977ebd911d5ca/libass/ass_font.c#L497).

**Comment by Sir-Doyle** [comment]
> Just tried the "Geeza Pro" you uploaded. Works perfectly here. I am afraid this is not a mpv issue.
> EDIT: sorry, I could not really test this in windows since windows does not support ttc fonts. It just falls back to Arial.
> 
> Try one more time reinstall mpv and its dependencies with current git HEAD.
> 
> Also, mpv is not responsible for displaying the subtitle. It is libass that renders the subtitle. You can try other players that use libass, for example VLC, to see if there is an issue.

I have used VLC and MPlayer OSX Extended, they work.
but IINA Player has same issue


> i have the exact same font installed, checked via hash.
> 
> no idea how you conclude that this is an mpv problem. it could be your system, it could be your build of mpv or it could be libass since the font provider is within libass. the warning is also [coming from libass](https://github.com/libass/libass/blob/98727c3b78f44cb3bbc955fcf5d977ebd911d5ca/libass/ass_font.c#L497).

I did fresh install of macOS and then install fresh mpv using homebrew with same issue.
I think there is something updated/installed on your system that I dont have it. I'm sure if you do fresh install of macOS you see the issue.

Anyway I'm ready to try anything you ask me to solve this issue.

I think as you said it's from libass ... how I can check libass ver in my mac?

Appreciate your support :)

**Comment by Akemi** [comment]
`brew info libass` will tell you the version of libass that you have installed.

as long as you use homebrew you probably won't get a "good" build of mpv. they got way to restricted with their standard homebrew formulas and shits.

i am pretty sure i won't see the issue since i have a 'fresh' install of mpv and dependencies.

**Comment by Sir-Doyle** [comment]
> i am pretty sure i won't see the issue since i have a 'fresh' install of mpv and dependencies.

I have installed mpv using these steps:

`git clone  https://github.com/mpv-player/mpv/`
`cd mpv`
`./bootstrap.py`
`./waf configure`
`./waf build`
`./waf install`

then I run mpv from "build" folder:
`~/mpv/build/mpv video.mp4`

same issue :(

Am I missing something?

I'll do a fresh install of macOS 10.14.3 again...Could you please tell me the brief steps to do a fresh install of mpv and dependencies?

Thanks

**Comment by Akemi** [comment]
sure you missed to update your dependencies. nah i am not spoon feeding you the steps. for starters make sure to get an up-to-date (preferably master: `brew install --HEAD FORMULA_NAME`) ffmpeg and libass. the latter is more important. afterwards rebuild mpv.

i just retested with and still everything fine:
ffmpeg https://github.com/FFmpeg/FFmpeg/commit/e704070f61e830064ea5c13e9562d7c455a3729d
libass https://github.com/libass/libass/commit/fa49852cd7fbab79653e62e1e52cedeb33a536ea
mpv https://github.com/mpv-player/mpv/commit/fcb320fd3fd3b1fc5549c009f23fc831bd37a495

**Comment by wm4** [comment]
Reporter didn't respond to the last steps that surely would have solved this issue; it's also a libass isuee, closing.
