### ISSUE TITLE
skip play

### ISSUE THREAD

**Issue by xiaolongren101** [mpv-player/mpv#6457]
How do I skip several intervals when playing a video? I know the "mpv --start=30 --end=40 <file-name>" command can skip the start and end of the video but I also want to skip the middle of the video. Is there any way to do this?

**Comment by garoto** [comment]
https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst

**Comment by garoto** [comment]
btw, the EDL parser on Windows only accepts files wih `LF` endings. `CRLF` ended ones fail with `[cplayer] Failed to recognize file format.`

**Comment by xiaolongren101** [comment]
> https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst
> 
> `mpv edl://file1.mp4,60,10;file1.mp4,120,10;file1.mp4,180,15`

This is exactly what I need. Thanks a lot.

**Comment by garoto** [comment]
> This is exactly what I need. Thanks a lot.

Appreciate it, but thanks should go for @wm4 for coding the mpv `edl` specs.
