### ISSUE TITLE
geometry doesnt work in input.conf

### ISSUE THREAD

**Issue by dusty071** [mpv-player/mpv#6472]
### mpv version and platform
0.29.0-112-g73fe0611b3
windows 10 64bit

### Reproduction steps
starting mpv from console with "mpv --geometry=50%:50% C:\somevideo.mp4" works, but when i keybind "set geometry 50%:50%" to a hotkey only writes out the command on screen and does not move the mpv player

**Comment by Akemi** [comment]
duplicate of #3872.
