### ISSUE TITLE
Playing mpv on an external device

### ISSUE THREAD

**Issue by unculcated** [mpv-player/mpv#6473]
How can I play mpv on my Mac and have it mirror the film onto a projector (4k)?, large file, mkv. I don't know of any external boxes that you can plug in a usb or SD card and play a 30 gig 4k mkv file. (if there is one please tell me)..
Hence my question.

**Comment by unculcated** [comment]
There is handbrake that converts mpv to mp4 just fine. There is a bit of quality lost. I wouldn't know how to play MPV to a thunderbolt connector (then convert both to HDMI). Is there a command to play to that output? You can mirror easily with LG monitors, but that is it.

**Comment by unculcated** [comment]
Maybe airplay will work. Sounds good.

**Comment by zc62** [comment]
Connect the projector to your Mac with whatever cable. Open the media file with mpv. Drag the mpv window to the screen that the projector is showing. Toggle fullscreen and resume playback. Done.

Just google "H.265 media player". There are plenty of boxes that can stream 4K files.
