### ISSUE TITLE
How to stop a video?

### ISSUE THREAD

**Issue by flatusv** [mpv-player/mpv#6475]
### mpv version and platform
mpv: mpv-full 0.29.1-4 on Arch Linux

How can i stop a video?  vlc has this rectangle, which pauses a video and jumps to the beginning.
![image](https://user-images.githubusercontent.com/16192241/52066447-e2082a80-2578-11e9-88b5-ecd49cfd353b.png)

What are the keybinds?

**Comment by EzeKees** [comment]
Pause + seek to 0s

**Comment by flatusv** [comment]
> Pause + seek to 0s
This is what i put in input.conf, but it doesnt't work
S pause + seek to 0s

**Comment by Hrxn** [comment]
I think this should work as well (`input.conf`):
`S stop`

**Comment by garoto** [comment]
`seek 0 absolute ; set pause yes`

**Comment by jimmy-1000** [comment]
> 
> 
> > seek 0 absolute ; set pause yes
> 
> That's what i was looking for. Couldn't find it anywhere, thanks.

It's correct, sadly that option doesn't exist 😞

**Comment by garoto** [comment]
[**@jimmy-1000**](https://github.com/jimmy-1000) commented on [Jun 4, 2021, 11:58 PM GMT-3](https://github.com/mpv-player/mpv/issues/6475#issuecomment-855172671 "2021-06-05T02:58:21Z - Replied by Github Reply Comments"):
> > > seek 0 absolute ; set pause yes
> > 
> > That's what i was looking for. Couldn't find it anywhere, thanks.
> 
> It's correct, sadly that option doesn't exist

That's supposed to be an input command, so set a keybind for it in your `input.conf`.

**Comment by jimmy-1000** [comment]
@garoto  But is not the same. That is "go to the beginning and pause". The current video is still there, we can see it.
 The _stop function_ in all players is "stop and exit from de current video and keep the playback window open", normally
 in black screen. I could't do that in mpv.

**Comment by garoto** [comment]
This seems to work when the player is started in [`pseudo-gui`](https://mpv.io/manual/master/#pseudo-gui-mode) mode:

`END    no-osd set idle yes ; stop ; show-text "Stop"`

**Comment by jimmy-1000** [comment]
> 
> 
> This seems to work when the player is started in [`pseudo-gui`](https://mpv.io/manual/master/#pseudo-gui-mode) mode:
> 
> `END no-osd set idle yes ; stop ; show-text "Stop"`

Thanks again @garoto you are right, it works in combination to pseudo gui.
I added --profile=builtin-pseudo-gui to mpv.conf

**Comment by garoto** [comment]
>  I added --profile=builtin-pseudo-gui to mpv.conf

If you never use the Windows CLI to launch mpv, I guess you don't really need that line in your conf. mpv will always start in `pseudo-gui` mode when double-clicking media in explorer or when launched from other GUI-based applications (AFAIK).

**Comment by jimmy-1000** [comment]
> 
> 
> > I added --profile=builtin-pseudo-gui to mpv.conf
> 
> If you never use the Windows CLI to launch mpv, I guess you don't really need that line in your conf. mpv will always start in `pseudo-gui` mode when double-clicking media in explorer or when launched from other GUI-based applications AFAIK.

You are right again, I tested it only thru Windows CLI and mpv closes its windows.
But do this directly click on video it works correctly without code in mpv.conf.. Thanks 👌
