### ISSUE TITLE
Stats overlay dosen't update video bitrate per second correctly

### ISSUE THREAD

**Issue by lextra2** [mpv-player/mpv#6477]
### mpv version and platform
- mpv 0.29.0
- Windows 10 Pro x64 1803

### Reproduction steps
Open any video and press Shift+I to see the stats overlay.

### Expected behavior
The video bitrate should update every second.

### Actual behavior
Most h264 files will update every second while most h265 files will take much longer to update.
The video birate update frequence is based on GOP size (assumption). I've tested videos with a high GOP size (240) & with a small GOP size (1) and the bitrate would only update with the GOP and not per second.

### Log file
https://www111.zippyshare.com/v/XaeV3C4E/file.html

### Sample files
[Gop size 1](https://drive.google.com/open?id=1hMY2b2Ko55nbcL2TYrvJqFDxs1ewK9BP)
[Gop size 240](https://drive.google.com/open?id=1K-GEfrGJYwT58vOAtQ237MJBaxZucZa2)

**Comment by Argon-** [comment]
(Not an issue of the stats script: it doesn't produce or calculate this value, only displays what mpv provides in form of properties)

**Comment by lextra2** [comment]
> (Not an issue of the stats script: it doesn't produce or calculate this value, only displays what mpv provides in form of properties)

So is there a way to get the videos bitrate to update every second? Having it update only every other second is pretty misleading to me.

**Comment by wm4** [comment]
This behavior is intentional, anyway.
