### ISSUE TITLE
Question: How to use External EDL file

### ISSUE THREAD

**Issue by Cuervo-Nefasto** [mpv-player/mpv#6479]
i'm using mpv-x86_64-20190120-git-73fe061
windows 10 64 bits

i have in the same folder test2.mkv and test2.edl

This is my edl file:
# mpv EDL v0
test2.mkv,40,50

in CMD tried: mpv test2.edl 

and i get::

Playing: test2.edl
Failed to recognize file format.

Exiting... (Errors when loading file)

if i do in CMD:
mpv edl://test2.mkv,40,50

works perfect

Please i need help!!

**Comment by garoto** [comment]
You need to convert your `test2.edl` file line endings from the Windows default `CRLF` to *nix-like `LF` only, then it'll work.

**Comment by Akemi** [comment]
works here. you won't get help if you ignore the issue template.

on a side node your fle should like like this, with a leading #:
```
#mpv EDL v0
test2.mkv,40,50
```

**Comment by Cuervo-Nefasto** [comment]
Thanks garoto!!!.
Akemi I'm sorry for the template( my first time in github) Thank you
