### ISSUE TITLE
cue sheet for file longer than 99minutes

### ISSUE THREAD

**Issue by MiNH0** [mpv-player/mpv#6481]
### Reproduction steps
Play provided cue file using MPV - you must place a video file of your choice with length over  ~101minutes [any movie will work]. Rename the file to "test.avi" or edit test.cue and replace "test.avi" with your filename in there.

### Expected behavior
I wanna be able to jump to time greater than 99minutes using cue file. Provided cue file works without problem in VLC/PotPlayer/MPC-BE.

### Actual behavior
MPV doesn't even see [or ignores?] time greater than 99min in cue. I know that cue is "designed" to be max 99m99s75f long, but if it works in other players why not in MPV...

### Sample file
[test.cue.txt](https://github.com/mpv-player/mpv/files/2827824/test.cue.txt)
you need to rename the test.cue.txt to test.cue.

**Comment by zc62** [comment]
Made a PR. See if it works for you.
