### ISSUE TITLE
ppa with VapourSynth does not include av1 even though its v0.29 and should support it

### ISSUE THREAD

**Issue by matu3ba** [mpv-player/mpv#6482]
Documentation Issue, notifying would be nice.
### mpv version and platform
no mpv needed, ubuntu 18.04.1 LTS
### Reproduction steps
Installing via ppa.
`mpv -ovc help -ovcopts help -oac help -oacopts help -of help -ofopts help | grep av
### Expected behavior
does contain av1 and upon testing av1 should be found by vcodec option
### Actual behavior
does not contain av1 and upon testing no av1 is found by vcodec option (it is ignored)

**Comment by sfan5** [comment]
We do not maintain third-party packages, complain to the owner of the PPA instead.

**Comment by mc4man** [comment]
I would suspect the ppa owner would enable in due course.
If unable to wait i keep an vapoursynth enabled mpv in this ppa, it's only occasionally updated. As it was overdue I added av1 support for decoding only via dav1d.(- there is no good reason to use mpv to encode av1 (aom)  that I can see & libaom is a poor decoder choice for mpv.

https://launchpad.net/~mc3man/+archive/ubuntu/bionic-media

You would however have to use the ppa itself as mpv there uses the shared ffmpeg libs in the ppa as does the libvapoursynth package. Note that the shared ffmpeg there has no GPLv3 or nonfree elements..

**Comment by matu3ba** [comment]
@mc4man I could not reach him or the ppa owner did not reply to my mail/message.
Thanks for your effort, but I used the testing version and have not issues for far.
Its just abit annoying to use within firejail due to the inconsistend naming.
