### ISSUE TITLE
mpv can not open files with os file dialog box from gui

### ISSUE THREAD

**Issue by medialove** [mpv-player/mpv#6483]
There seems to be no way to open a video from the gui with the expected operating system file dialog. 
I did not find any information about how to open a file in the manual. None of te expected keyboard shortcuts do work. No right-click menu, no hint whatsover about how to open a file. 

There are many situations when users end up with a mpv window on the desktop, e.g. starting mpv from the menu. Then there is no way obvious way to open a file dialog box to feed some videos into mpv. 

This kind of basic functionality is expected since the early 90s for all kind of computer programs - it would be great if mpv would also support this modern operating system feature of easily adding files to a program via the operating system file dialog box.

**Comment by TheAMM** [comment]
mpv has no real GUI, and it doesn't try to have one. You may drag and drop files to the window, or start mpv with the files you want to play. While mpv does have a window, you could argue that it's primarily 
used on the command line, as all of the options and flags are there; few if any available without the terminal (or editing the config).

>no hint whatsover about how to open a file

![image](https://user-images.githubusercontent.com/6820963/52406976-a8cf3d80-2ad7-11e9-9706-b834aeed1f77.png)

**Comment by medialove** [comment]
Yes, there is no basic gui functionality, this was what I was asking for - thank you for your confirmation, I was not sure if anything is broken on my system but came to the conclusion that it must be a missing feature of this software. Lost the whole morning with this awkwardness.   

Please add at least the possibility to open a file dialog box - it is grotesque to not have this absolutely basic and expected feature in a desktop media player in 2019. 

Thank you very much for your attention!

**Comment by CounterPillow** [comment]
>Please add at least the possibility to open a file dialog box - it is grotesque to not have this absolutely basic and expected feature in a desktop media player in 2019.

idk works fine for me. There's a script for this if you absolutely need it.

**Comment by zc62** [comment]
https://github.com/mpv-player/mpv/wiki/User-Scripts

Windows: https://github.com/rossy/mpv-open-file-dialog
KDE: https://gist.github.com/ntasos/d1d846abd7d25e4e83a78d22ee067a22

**Comment by Akemi** [comment]
#5500 and besides those scripts macOS also has native support for this.

**Comment by hopeseekr** [comment]
Any idea how to get this for Gnome 3?

I was shocked to find out I couldn't open files.

And people really think this is a VLC alternative?!?

**Comment by wm4** [comment]
mpv doesn't support GNOME. Bugger off.

**Comment by hopeseekr** [comment]
I don't need it to support Gnome 3. I just want a way to open the next fucking file, asshole.

**Comment by CounterPillow** [comment]
Shift+Drag onto window to append to end of playlist, drag onto window to play immediately. If you really want an open file dialog for some reason, then I'd use the KDE one even on GNOME, since KDE's filechooser has infinitely better UX than the Gtk filechooser.

**Comment by garoto** [comment]
Even Windows users have no problem with the absence of a native "Open File" dialog, I don't get it why Linux Desktop users are bitching. So odd.

**Comment by garoto** [comment]
>I just want a way to open the next fucking file, asshole.

Perusing the [User-Scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts) wiki goes a long way in helping solve potentially usability annoyances btw: https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua

**Comment by bitsper2nd** [comment]
> I don't need it to support Gnome 3. I just want a way to open the next fucking file, asshole.

Use Celluloid. That is the GUI that Gnome made for mpv.

**Comment by spinninbiribin** [comment]
> mpv doesn't support GNOME. Bugger off.

Look ma, I posted it again. :^)
