### ISSUE TITLE
Startup stuck at [osd/ass] Setting up fonts...

### ISSUE THREAD

**Issue by daed-alus** [mpv-player/mpv#6486]
### mpv version and platform
**mpv 0.29.1** and **mpv 0.29.0-118-gf2e7e81bda**
win 10 1809 x64

### Reproduction steps
playing video file with subrip (srt) subtitle

### Expected behavior
not hanging on startup

### Actual behavior
hanging on startup for 10+ seconds

### Log file
```
[   0.766][v][sub/ass] Setting up fonts...
[  16.008][v][sub/ass] Using font provider directwrite
[  16.008][v][sub/ass] Done.
[  16.008][v][cplayer] Starting playback...
```

**Comment by zc62** [comment]
How many fonts did you install? And what kind of hard drive do you use?

**Comment by zc62** [comment]
Try this https://github.com/mpv-player/mpv/issues/6447#issuecomment-473525045

**Comment by Akemi** [comment]
duplicate of #6447
