### ISSUE TITLE
"Failed to recognize file format." when opening archive

### ISSUE THREAD

**Issue by drstorm81** [mpv-player/mpv#6488]
### mpv version and platform

mpv 0.29.1
Arch Linux amd64

libarchive 3.3.3-1

### Reproduction steps

Launch:
mpv archive.zip

### Expected behavior

mpv opening archive and playing file inside.

### Actual behavior

mpv reports 'Failed to recognize file format.'

### Log file
https://0x0.st/zzBL.txt

Tried zip, rar i tar.gz archives, multiple files, mp4 and wmv formats.

I have no idea what i'm doing wrong. I even tried to recompile mpv from source, same issue.
I believe it worked as expected before but i didn't need that feature for some time so i didn't notice when it stopped working. I saw that there were reports in the past related to libarchive version, maybe it somehow doesn't detect archives properly?

**Comment by zc62** [comment]
Probably related to #5759. See if #6438 fixes that.
