### ISSUE TITLE
Windows 10 Standard App

### ISSUE THREAD

**Issue by ximbary** [mpv-player/mpv#6490]
Hello!

VLC is a joke compared to MPV, so I want to register MPV as standard app for video files on w10.

But that's not freaking possible. In W10 you can't just navigate to a random .exe file and register it for a file extension.

![grafik](https://user-images.githubusercontent.com/47530719/52571621-3089b480-2e16-11e9-9969-1ea83a14884d.png)

How do I register mpv.exe so that W10 will recognize it as a standard app to do things?

Thanks

**Comment by garoto** [comment]
https://github.com/rossy/mpv-install

**Comment by ximbary** [comment]
Thank you, I didn't find that.

It should definitely be added to https://mpv.io/installation/

**Comment by lachs0r** [comment]
Well it is mentioned (in bold) on my Windows build page.
