### ISSUE TITLE
Hardware decoding?

### ISSUE THREAD

**Issue by niksfirefly** [mpv-player/mpv#6493]
### mpv version and platform
Ubuntu 18.04.2 LTS with Intel HD Graphics 510

mpv git-2018-11-18-ce2253b Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Jan 22 20:08:09 UTC 2019
ffmpeg library versions:
   libavutil       56.24.101
   libavcodec      58.42.102
   libavformat     58.24.101
   libswscale      5.4.100
   libavfilter     7.46.101
   libswresample   3.4.100
ffmpeg version: git-2018-12-16-de5e71f

### Log file

vainfo
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns -1
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
vaInitialize failed with error code -1 (unknown libva error),exit

mkv output
[vo/gpu/x11] X11 error: BadValue (integer parameter out of range for operation)
[vo/gpu/x11] Type: 0, display: 0x7f8b54232fa0, resourceid: 0, serial: 42
[vo/gpu/x11] Error code: 2, request code: 9a, minor code: 3
[vo/gpu] Could not create GLX context!
[vo/gpu/x11] X11 error: BadValue (integer parameter out of range for operation)
[vo/gpu/x11] Type: 0, display: 0x7f8b5424b3c0, resourceid: 0, serial: 42
[vo/gpu/x11] Error code: 2, request code: 9a, minor code: 3
[vo/gpu] Could not create GLX context!
[vo/vdpau] Error when calling vdp_device_create_x11: 1
[vo/xv] No Xvideo support found.
[vaapi] libva: va_getDriverName() failed with unknown libva error,driver_name=(null)
[vaapi] Failed to initialize VAAPI: unknown libva error
[vo/x11] Warning: this legacy VO has bad performance. Consider fixing your graphics drivers, or not forcing the x11 VO.
Using hardware decoding (vaapi-copy).

### Actual behavior
I am getting slow hardware decoding with only one working option
--hwdec=vaapi-copy
I think i got all required packages, tried also vapoursynth mpv same results.
Is there any addidtional steps to run hardware decoding for mpv? X concig ?
regards

**Comment by lachs0r** [comment]
Please post the *entire* log file.

**Comment by niksfirefly** [comment]
[log.txt](https://github.com/mpv-player/mpv/files/2860278/log.txt)

**Comment by sfan5** [comment]
OpenGL does not work on your system <i>at all</i>, fix that first.

**Comment by niksfirefly** [comment]
hmm how?
I followed the steps
http://tipsonubuntu.com/2019/02/08/install-mesa-graphics-driver-18-3-3-ubuntu-18-04/
and nothing changes

**Comment by CounterPillow** [comment]
What is the output of glxinfo?

Have you tried rebooting your system?

**Comment by niksfirefly** [comment]
After reboot
glxinfo
name of display: :0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  37
  Current serial number in output stream:  38

**Comment by CounterPillow** [comment]
Not an mpv issue then, fix your system. You've somehow completely broken all graphics acceleration.

**Comment by mc4man** [comment]
You should likely just do a fresh install. If you want to ck. if your hardware isn't the issue then boot to a live session.
mpv using vaapi hwdec can be run in a live session, you just need to enable the universe & multiverse repos first before installing mpv.. If it works you did something, if not then your hardware is the issue for one reason or the other.

Be aware that newer  isn't always better, for example the 18.3.x mesa  in the ppa you have will break vaapi in a wayland session  with your current libva2 & intel-vaapi-driver (not that it appears you are using wayland.

**Comment by niksfirefly** [comment]
Thank you for suggestions.
I found solution so I leave here for the others
```
apt-get purge nvidia*
apt-get install --reinstall xserver-xorg-video-intel libgl1-mesa-glx libgl1-mesa-dri xserver-xorg-core
reboot
```
I think old nvidia drivers mess all things up.
regards
