### ISSUE TITLE
No VA-API with AMD ARUBA

### ISSUE THREAD

**Issue by Heiko-L** [mpv-player/mpv#6495]
### mpv version and platform

mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100 (runtime 56.22.100)
   libavcodec      58.18.100 (runtime 58.35.100)
   libavformat     58.12.100 (runtime 58.20.100)
   libswscale      5.1.100 (runtime 5.3.100)
   libavfilter     7.16.100 (runtime 7.40.101)
   libswresample   3.1.100 (runtime 3.3.100)
ffmpeg version: 4.1-1

vainfo
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/r600_drv_video.so
libva info: Found init function __vaDriverInit_1_3
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.4 (libva 2.2.0)
vainfo: Driver version: Mesa Gallium driver 18.3.2 for AMD ARUBA (DRM 2.50.0 / 4.19.0-2-amd64, LLVM 7.0.1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileNone                   :	VAEntrypointVideoProc

### Reproduction steps

Play big_buck_bunny_1080p_h264.mov with vaapi on AMD A8-5600K APU with Radeon(tm) HD Graphics

### Expected behavior

Hardware acceleration is being used

### Actual behavior

[vo/gpu] Loading hwdec driver 'vaapi-egl'
[vo/gpu] Loading failed.

### Log file

https://0x0.st/zzxY.txt

### Sample files

https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_h264.mov

**Comment by lachs0r** [comment]
Read the manual before setting options. The vaapi hwdec requires the EGL OpenGL backend. Try `--hwdec=auto` or `--hwdec=vaapi-copy` instead, or try setting `--opengl-backend=x11egl`.

**Comment by Heiko-L** [comment]
> The vaapi hwdec requires the EGL OpenGL backend.

?
Mesa EGL (libEGL) is installed.
OpenGL seems to be intact:

Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD ARUBA (DRM 2.50.0 / 4.19.0-2-amd64, LLVM 7.0.1) (0x9904)
    Version: 18.3.2
    Accelerated: yes
    Video memory: 512MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.3
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1

> Try `--hwdec=auto` 

uses vdpau :(

> or `--hwdec=vaapi-copy` instead

works.

> or try setting `--opengl-backend=x11egl`.

`mpv --no-config --hwdec=auto --opengl-backend=x11egl -v ~/Downloads/big_buck_bunny_1080p_h264.mov`

[cplayer] Warning: option --opengl-backend was replaced with --gpu-context and might be removed in the future.
[...]
[ffmpeg] AVHWFramesContext: Failed to create surface: 2 (resource allocation failed).
[ffmpeg] AVHWFramesContext: Unable to allocate a surface from internal buffer pool.

But it works and uses vaapi hwdec.

Why x11egl isn't used automatically?

**Comment by lachs0r** [comment]
I think that’s because it’s broken in a few ways with various drivers. Notably NVIDIA.

Anyway, this looks like it’s working as intended.
