### ISSUE TITLE
Core Dumped when trying to play video using vulkan

### ISSUE THREAD

**Issue by Precrisk** [mpv-player/mpv#6496]
### mpv version and platform
mpv git-2018-11-18-ce2253b Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Jan 22 20:08:09 UTC 2019
ffmpeg library versions:
   libavutil       56.24.101
   libavcodec      58.42.102
   libavformat     58.24.101
   libswscale      5.4.100
   libavfilter     7.46.101
   libswresample   3.4.100
ffmpeg version: git-2018-12-16-de5e71f

####Platform: 
OS: Linux Mint 19.1 Tessa
Mesa latest git (as of 12/02/19) w/ vulkan packages installed (Oibaf ppa)
Kernel 4.20

[mpv.txt](https://github.com/mpv-player/mpv/files/2864417/mpv.txt)

### Reproduction steps
Run:
>  mpv --vo=gpu --gpu-api=vulkan <video file> 

### Expected behavior
Video should run as normal using vulkan.

### Actual behavior
https://pastebin.com/5f3Wz5Yp

mpv crashes with error isl_lower_storage_image_format: Assertion `!"Unknown image format"' failed.

### Log file

https://pastebin.com/ev9XC7T8

### Sample files

No sample files required

**Comment by CounterPillow** [comment]
A backtrace would be helpful.

Do `gdb mpv`, and then type `run --gpu-api=vulkan ./avengers.age.of.ultron.2015.2160p.uhd.bluray.x265-terminal.mkv --no-config`. Once it crashes, follow it up with `bt full`. Give us the full output of the bt full command. After that you can quit with `quit` and confirming you want to kill mpv.

**Comment by Precrisk** [comment]
I recently moved from Linux mint to opensuse tumbleweed.

Seems like mpv doesn't provide tumbleweed packages will have to compile it manually and check myself.

Will report back in few days

**Comment by lachs0r** [comment]
Tumbleweed does have packages for mpv. In the main repository. To get debug symbols to use with gdb, you might have to enable the debug repository and install mpv-debuginfo.
For full codec support you need to install the FFmpeg libraries (libav*, libswscale etc.) from Packman, however. See instructions here: https://en.opensuse.org/Additional_package_repositories

**Comment by Precrisk** [comment]
Yeah but it seems opensuse tumbleweed mpv isn't built against vulkan, it throws some spir-v errors

**Comment by haasn** [comment]
Before investigating further, make sure #6476 doesn't fix it. Also, always test with `--gpu-debug` when debugging graphics-related issues. (Which will most likely require #6476)

**Comment by Precrisk** [comment]
Yeah but it seems opensuse tumbleweed mpv isn't built against vulkan, it throws some spir-v errors

**Comment by Precrisk** [comment]
Ok I will build latest mpv now

**Comment by Precrisk** [comment]
Ok, I tried today's latest git. it compiled once i downloaded many dev packages. 
But the vulkan performance is lot worse than opengl performance.

**Comment by zc62** [comment]
Performance can be related to many things. Providing a full log file is always better than nothing. And, isn't this issue about mpv crashes when using vulkan API? Do you mean with current git HEAD the issue went away? Then probably you can close this issue and open another issue.

**Comment by Akemi** [comment]
ig this issue still persists, please open a new issue.
