### ISSUE TITLE
How do I manage external-files and track-list?

### ISSUE THREAD

**Issue by rr-** [mpv-player/mpv#6497]
### mpv version and platform
```
Linux Arch

mpv 0.29.0-118-gf2e7e81bda Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Mon Feb  4 23:53:08 CET 2019
ffmpeg library versions:
   libavutil       56.26.100
   libavcodec      58.46.100
   libavformat     58.26.100
   libswscale      5.4.100
   libavfilter     7.48.100
   libswresample   3.4.100
ffmpeg version: N-93083-g8522d219ce
```

(I've discarded the issue template as it's a question rather than a bug report, and its sections don't apply here.)

I want to play the audio track from one file and the video from another with libmpv. Sometimes there will be no video available, and sometimes no audio. I figured the best way to do it is to fiddle with `external-files`, as `loadfile` is too blunt and doesn't offer much control. Then I either use `--lavfi-complex` to render the tracks I want, or simply fiddle with `--vid` and `--aid`.

But, in order to know which stream to select, I need to know the track list itself first.

The thing is that setting `external-files` doesn't seem to do anything useful. The track list doesn't change, and the files are not parsed. So I have no way to know what `--vid` and `--aid` to supply. I tried to `loadfile null://`, but it doesn't seem to change anything.

What is the correct approach to do this? Thanks

**Comment by EzeKees** [comment]
how do you select the tracks with --lavfi-complex?

**Comment by rr-** [comment]
`--lavfi-complex='[vid1] copy [vo]; [aid2] acopy [ao]'`

**Comment by EzeKees** [comment]
Thanks!!!

**Comment by vjtooth** [comment]
Can some one help me with loop logo animation with external-file or external-files. My logo animation play once and stop. But i want to play it non stop, looped.
 
mpv.exe ^
C:\path to video folder\ ^
--external-file ^
"C:\path to logo animation with alpha chanel in mov" ^
--lavfi-complex "[vid1][vid2]overlay@myoverlay[vo]"
