### ISSUE TITLE
how to stop Dropped Cache post to terminal

### ISSUE THREAD

**Issue by unculcated** [mpv-player/mpv#6498]
playing: /Volumes/storage/Isle Of Dogs 2018 1080p WEB-DL AAC H264-CMRG[TGx]/Isle Of Dogs 2018 1080p WEB-DL AAC H264-CMRG.mkv
 (+) Video --vid=1 (*) (h264 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
GVA info: Successfully connected to the Intel plugin, offline Gen95 
Using hardware decoding (videotoolbox).
AO: [coreaudio] 48000Hz stereo 2ch floatp
VO: [libmpv] 1920x1072 videotoolbox[nv12]
[ffmpeg/video] h264: Increasing reorder buffer to 1
AV: 00:00:00 / 01:41:24 (0%) A-V:  0.071 
Dropped: 1 Cache: 86s+40AV: 00:00:00 / 01:41:24 (0%) A-V:  0.034 
Dropped: 2 Cache: 87s+41AV: 00:00:00 / 01:41:24 (0%) A-V: -0.000 
Dropped: 3 Cache: 87s+41AV: 00:00:00 / 01:41:24 (0%) A-V: -0.000 
Dropped: 3 Cache: 88s+42AV: 00:00:00 / 01:41:24 (0%) A-V: -0.000 
Dropped: 3 Cache: 92s+47AV: 00:00:00 / 01:41:24 (0%) A-V: -0.000 
Dropped: 3 Cache: 96s+52AV: 00:00:00 / 01:41:24 (0%) A-V: -0.000 
[----------+----------------------------------------------------

here is my conf file; (note; I like the way the videos look) but something is wrong,

################
# Video Output #
################

# Defaults for all profiles

vo=libmpv
cache-default=1000000
cache=1000000
demuxer-readahead-secs=300
--cocoa-force-dedicated-gpu=yes
border=no # Hide the window title bar
term-osd-bar # Display a progress bar on the terminal
hwdec=videotoolbox # Enable hardware decoding if available.

scale=ewa_lanczossharp # Luma upscale
dscale=sinc # Luma downscale
cscale=ewa_lanczossharp # Chroma upscale

deband=yes
deband-iterations=2
deband-threshold=13 # Deband strength (More = Less banding, but more detail loss)
deband-range=36 # Deband range (More = Less banding, but higher GPU cost)
deband-grain=0 # Dynamic Grain (More = More dynamic grain)

temporal-dither
--script=/Users/ss/.config/mpv/scripts

glsl-shaders="/Users/ss/.config/mpv/shaders/LumaSharpenHook.glsl"

# Anti-Ringing
scale-antiring=0.3 # Luma upscale deringing (Higher = Less ringing, but more detail loss)
dscale-antiring=0.4 # Luma downscale deringing (Higher = Less ringing, but more detail loss)
cscale-antiring=0.3 # Chroma upscale deringing (Higher = Less ringing, but more detail loss)

**Comment by Argon-** [comment]
Can you test without `term-osd-bar`? IIRC that's the cause.

**Comment by unculcated** [comment]
Worked, Thanks!
