### ISSUE TITLE
font not loaded with multi-segment mkv files

### ISSUE THREAD

**Issue by fr3aker** [mpv-player/mpv#6503]
### mpv version and platform

tested with version 0.27.2 and latest master (8b563a034604ff5ab2ad92d12c63e806f45d1bb6) on linux

### Issue overview

When playing a multi-segment mkv container video (one that references a different mkv file within its chapters) with ssa subtitles, mpv ignores attached fonts in the included mkv container and only loads fonts from the main mkv container. This causes mpv to use a fallback font even though the correct font is available. Attaching the font to `main.mkv` causes the correct font to be used.

### Reproduction steps
Play `main.mkv` (see sample files) with mpv

### Expected behavior
mpv uses "Indie Flower" font for the external part, attached to `included.mkv`

### Actual behavior
mpv does not detect attached font in `included.mkv` and uses fallback to a default font

note: playing `included.mkv` by itself will use the correct font

### Log file

* playing `included.mkv` on its own (working correctly): [included.log](https://github.com/mpv-player/mpv/files/2875601/included.log)
* playing `main.mkv` which includes `included.mkv` (broken): [main.log](https://github.com/mpv-player/mpv/files/2875602/main.log)

### Sample files

[mpv demo.zip](https://github.com/mpv-player/mpv/files/2875603/mpv.demo.zip)

**Comment by zc62** [comment]
See if the PR works for you.

**Comment by qmega** [comment]
This looks like the same issue as #6009. I made a very similar PR in #6019.

**Comment by zc62** [comment]
Cool. Was not aware of your PR. Closed mine. (Hope we can get more people reviewing the PRs...)

**Comment by fr3aker** [comment]
Thank you both for your responses! I must have overlooked #6009, sorry about that!
