### ISSUE TITLE
mpv 0.29 does not inhibit monitor power management when running under Xwayland

### ISSUE THREAD

**Issue by glaubersm** [mpv-player/mpv#6506]
### mpv version and platform
mpv 0.29, Arch Linux

### Reproduction steps
use a linux distribution running KDE Plasma or Gnome desktop environments
start KDE Plasma Wayland or Gnome Wayland sessions
play some video with mpv running under Xwayland, not running natively under Wayland
do NOT use any input device (mouse, keyboard) until timeout of monitor power management is reached

### Expected behavior
mpv inhibts monitor power management during video playback
### Actual behavior
monitor turns off during video playback if video length is greater than timeout of monitor power management configured in Plasma/Gnome settings.
### Log file

https://0x0.st/zi1K.txt

**Comment by lachs0r** [comment]
Do you have the xdg-screensaver program installed? Otherwise mpv can only use the Xss extension, which might not work with XWayland.

**Comment by glaubersm** [comment]
There is no xdg-screensaver package in Arch repositories.
Are you talking about xscreensaver?
If so, it does not solve the problem.

**Comment by lachs0r** [comment]
On Tuesday, February 19, 2019 9:57:34 PM CET Strangiato wrote:
> There is no xdg-screensaver package in Arch repositories.
> Are you talking about xscreensaver?
> If so, it does not solve the problem.

It should be in xdg-utils.

**Comment by glaubersm** [comment]
xdg-utils is already installed.

**Comment by lachs0r** [comment]
Then file a bug against xdg-screensaver and possibly XWayland. Power management inhibition is incredibly messy, which is why we delegate that work to an external program in the first place. Every DE uses and supports different interfaces for that.

**Comment by glaubersm** [comment]
https://gitlab.freedesktop.org/xdg/xdg-utils/issues/144

**Comment by gthreepw00d** [comment]
https://gitlab.freedesktop.org/xorg/xserver/issues/675

**Comment by gthreepw00d** [comment]
> there are already some other simpler solutions that would work with GNOME (again, I haven't looked at what KDE uses):
> 
>     mpv could use xdg-screensaver suspend <xid>
> 
> or
> 
>     GNOME should implement the DBUS method SimulateUserActivity used by xdg-screensaver reset
> 
> Both options would work regardless of Xwayland.

**Comment by gthreepw00d** [comment]
<details>
<summary>workaround extension, tested in Wayland session of Gnome</summary>
<p>

```lua
--prerequisites: xdg-screensaver wmctrl perl-Net-DBus perl-X11-Protocol

local wmid
local timer

function get_wmid()
	k=io.popen("wmctrl -l 2>/dev/null")
	for s in k:lines() do
		wmid=s:match("([^ ]+) .*mpv$")
		if wmid then
			break
		end
	end
end
function on_file_loaded()
	if not wmid then
		get_wmid()
	end
	if wmid then
		os.execute("xdg-screensaver suspend "..wmid)
	end
end
function on_end_file()
	if timer and timer.is_enabled() then
		timer.kill()
	end
	if wmid then
		os.execute("xdg-screensaver resume "..wmid)
	end
end

--window doesn't exist at file-loaded yet
mp.register_event("file-loaded", function() timer=mp.add_timeout(3, on_file_loaded); end)
mp.register_event("end-file", on_end_file)
```

</p>
</details>
