### ISSUE TITLE
libmpv: mpv_render_context_create crashes if failed to get opengl function pointer

### ISSUE THREAD

**Issue by lhc70000** [mpv-player/mpv#6507]
### mpv version and platform

mpv 0.29.1
macOS 10.14.3

### Reproduction steps

When using the render.h API, call `mpv_render_context_create` when OpenGL is unavailable or not ready. It can be reproduced by simply returning `NULL` in the function provided for `get_proc_address`.

#6249 and #6379 might be related.

### Expected behavior

`mpv_render_context_create` should return the error code if cannot get the OpenGL entry point.

### Actual behavior

`mpv_render_context_create` crashes (EXC_BAD_ACCESS) at: https://github.com/mpv-player/mpv/blob/e5c41640885bafb11513f1cada7a462ee79b0aee/video/out/vo_libmpv.c#L300

Seems that the resource is freed twice (the first time at https://github.com/mpv-player/mpv/blob/e5c41640885bafb11513f1cada7a462ee79b0aee/video/out/vo_libmpv.c#L194), if `err` returned by `ctx->renderer->fns->init` is less than zero.

### Log file

N/A

### Sample files

N/A

**Comment by wnoun** [comment]
See #6540
