### ISSUE TITLE
AV-1 rendering errors

### ISSUE THREAD

**Issue by CoffeeFlux** [mpv-player/mpv#6508]
Buggy AV-1 rendering, this screenshot being an example: https://i.imgur.com/JNTApKx.png

Sample file here: https://sharex.thevacuumof.space/2019/02/av1.mkv

Platform is Windows, with the latest build off https://sourceforge.net/projects/mpv-player-windows/files/64bit/

Seems to be fine in the last stable, and bisecting:
mpv-x86_64-20181103-git-880c59d.7z renders properly
mpv-x86_64-20181110-git-317d3ac.7z crashes
mpv-x86_64-20181118-git-edbe25f.7z renders buggy (and onward)

Log for the crash: https://gist.github.com/CoffeeFlux/6074b02cb90e07fb6b928497c24070c2
Log for the buggy rendering: https://gist.github.com/CoffeeFlux/f7b609ae2bf80e5ad8409ac735d840b2

**Comment by CounterPillow** [comment]
This seems like a dav1d bug to me, so it may be best if you report it to them.

**Comment by CounterPillow** [comment]
Just tested with the latest git HEAD of dav1d and it still shows corruption there. Report the corrupted output here with the sample, and mention that libaom decodes it correctly: https://code.videolan.org/videolan/dav1d

**Comment by zc62** [comment]
> mpv-x86_64-20181103-git-880c59d.7z renders properly

```
[   0.156][v][vd] Codec list:
[   0.156][v][vd]     libaom-av1 (av1) - libaom AV1
[   0.156][v][vd] Opening decoder libaom-av1
```

> mpv-x86_64-20181110-git-317d3ac.7z crashes

```
[   0.139][v][vd] Codec list:
[   0.139][v][vd]     libdav1d (av1) - dav1d AV1 decoder by VideoLAN
[   0.139][v][vd] Opening decoder libdav1d
```

1103 was not built against dav1d so it worked. Probably should have bisected dav1d?

@shinchiro https://github.com/shinchiro/mpv-winbuild-cmake/commit/35a1c6f19fc06f47fe25b064b82a373201ce98c3 Should mpv be built with libaom until this is fixed?

**Comment by CoffeeFlux** [comment]
Done: https://code.videolan.org/videolan/dav1d/issues/252

**Comment by CoffeeFlux** [comment]
Supposedly fixed upstream, I'm out of town and can't verify for myself. Closing under the assumption the fix works.

**Comment by CounterPillow** [comment]
Can confirm this has been fixed upstream.
