### ISSUE TITLE
Can you port deband shader to hlsl?

### ISSUE THREAD

**Issue by DanillaTech** [mpv-player/mpv#6509]
Hello! Sorry, it's not exactly mpv request, but it's your algothithm. Usually windows video players use hlsl shaders. Your deband shaders works better and much  faster than MadVR (on intel hd 4000 with motion SVP interpolation MadVR is glitchy). On windows it has release in https://github.com/crosire/reshade-shaders/blob/master/Shaders/Deband.fx . It's hlsl-like shader, I think there is only difference that reshade has his own random generator.

So, it works better than madvr, but only in frame doubling (output frame rate is about ~24x2, not 60fps) mode. Without motion interpolation, for example, player+reshade uses ~50% GPU, mpv (on windows) uses about ~40% on same 1080p. I hope that ported clean hlsl shader gives better perfomance.

So, if you can or can give advice how can I make this, please help.

**Comment by DanillaTech** [comment]
Comparison
![image](https://user-images.githubusercontent.com/8999560/53102162-31b89100-353c-11e9-8d89-32a5892a192b.png)

**Comment by Akemi** [comment]
it's not exactly an issue, so i am closing this. if anyone feels like porting it they can do it.

haasn still has the shaders in his repo [here](https://github.com/haasn/gentoo-conf/tree/xor/home/nand/.mpv/shaders). which are based on flash3kyuu_deband. they are probably a bit easier to port than trying to get the shaders out of mpv source.
legacy: https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/shaders/deband-sin.glsl
newer: https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/shaders/deband.glsl
newest: https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/shaders/deband-pre.glsl

**Comment by CounterPillow** [comment]
just use mpv

**Comment by DanillaTech** [comment]
I need too much else)
