### ISSUE TITLE
show youtube playlist

### ISSUE THREAD

**Issue by flatusv** [mpv-player/mpv#6510]
If i play a youtube playlist with mpv how can i see all the different videos? 
I do:
> mpv https://www.youtube.com/watch?v=DamuE8TM3xo&list=PLGLfVvz_LVvQ9S8YSV0iDsuEU8v11yP9M

this gives me only the first video as can be seen with 

> CTRL+p script-message osc-playlist

**Comment by garoto** [comment]
Either:
`mpv --ytdl-raw-options="yes-playlist=" https://www.youtube.com/watch?v=DamuE8TM3xo&list=PLGLfVvz_LVvQ9S8YSV0iDsuEU8v11yP9M`

Or:
Feed mpv the the actual `playlist` link from youtube in the form of `https://www.youtube.com/playlist?list=<id>`

**Comment by donut** [comment]
Relevant issue for IINA (which uses mpv): https://github.com/iina/iina/issues/2328

**Comment by wiiaboo** [comment]
This is working as intended, it's not a bug.

**Comment by jimmy-1000** [comment]
> ...
Hi garoto.  I use **F2 script-message osc-playlist 3**. This is show me the playlist 3 seconds when I press F2. I would like to press the same F2 key to disappear the playlist instead to wait the 3 seconds (or if I need more time). I tried some commands but I couldn't'. I used combinations with _toggle_ and _cycle_ but nothing worked. Some help?

**Comment by jimmy-1000** [comment]
> You can use this script:
> 
> ```lua
> local duration = 3
> local time
> 
> mp.add_key_binding('F2', function ()
>     if time and mp.get_time() - time < duration then
>         mp.command('script-message osc-playlist 0')
>         time = nil
>     else
>         mp.commandv('script-message', 'osc-playlist', duration)
>         time = mp.get_time()
>     end
> end)
> ```
> 
> It should be placed in `~~/scripts` with a `.lua` extension.

Thanks but sadly it doesn't have what I looking for. This script has the same function that  **F2 script-message osc-playlist 3**.  I want to press F2 to show playlist and press F2 again to quit from such playlist (no timer)

**Comment by guidocella** [comment]
That's literally what this script does. Did you remove F2 from input.conf?

**Comment by jimmy-1000** [comment]
> That's literally what this script does. Did you remove F2 from input.conf?

Yes, even I edited your lua and changed the key binding to another, for example "a" key and the result is the same, the playlist last 3 seconds and quit.

**Comment by guidocella** [comment]
```lua
local enabled = false

mp.add_key_binding('F2', function ()
    mp.commandv('script-message', 'osc-playlist', enabled and 0 or 999)
    enabled = not enabled
end)
```

**Comment by garoto** [comment]
Damn, this version is super neat.

**Comment by Hrxn** [comment]
What's the purpose of `and 0 or 999`?

**Comment by jimmy-1000** [comment]
> ```lua
> local enabled = false
> 
> mp.add_key_binding('F2', function ()
>     mp.commandv('script-message', 'osc-playlist', enabled and 0 or 999)
>     enabled = not enabled
> end)
> ```

Thanks! This works perfect 👌
Oh  I need to learn Lua language.

**Comment by guidocella** [comment]
> What's the purpose of `and 0 or 999`?

It evaluates to a playlist duration or 999 seconds if it's not enabled, or 0 if it's already enabled, thus hiding it.
