### ISSUE TITLE
AMD Enhanced Sync and video-sync=display-resample

### ISSUE THREAD

**Issue by Druneau** [mpv-player/mpv#6514]
### mpv version and platform
mpv-x86_64-20190218-git-8b563a0
Windows 10 1809
AMD RX 560

### Reproduction steps
Use MPV Option video-sync=display-resample
Enable AMD "Enhanced Sync" from the driver's control pannel
Open any video file and switch to fullscreen
Issue gets worse after seeking through the file (not sure on this one)

### Expected behavior
Smooth playback with low VSYNC jitter
Display FPS "estimated" value to hover around "specified" value

### Actual behavior
Non-smooth playback
Stuttering when seeking
Tearing of frames

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/2889087/output.txt)

### Sample files
I can reproduce with any file I have.

### Some extra information
Initially i thought the issue started out of nowhere.  But it seems at some point the Radeon Settings app sugggested I apply some "reccomended settings".  I believe that is the point where "Enhanced Sync" was enabled and I started having issues.

I did not know anything about Enhanced sync when trying to fix the issue.  I played around with my config, different MPV versions, etc...  After failling I updated my video drivers, there was only one new version available.  The driver's release notes noted "Enhanced sync" and I was curious so I took a look at the feature.  That's when It clicked that it could be causing the issues I was experiencing with MPV.  I turned it off and it fixed it.

So for me, I will just run with normal VSync setting.  But I wanted to report that Enhanced Sync from AMD Radeon cards was causing issues for me on windows with latest MPV.

Thanks for an amazing program.

**Comment by Akemi** [comment]
it seems like [enhanced sync](https://www.amd.com/en/technologies/radeon-software-enhancedsync) is counter productive to any kind of video playback, because it's supposed to improve the case where 'media refresh rate' is higher than the display refresh rate. the linked page even mentioned "loccasional tearing" on lower frame rates and it also says:

> Does Enhanced Sync support multimedia applications?
> No, Enhanced Sync does not support multimedia applications and may cause flicker or other undesirable behaviors. If you experience issues with multimedia playback, please add the application to game manager and disable enhanced sync or enable enhanced sync specifically within the games you play.

besides that, it tries to time frames better to the monitor's refresh rate, that's what display-resample also does. so both modes possibly interfere with each other.

so, it's absolutely expected behaviour and not mpv's fault.

**Comment by Druneau** [comment]
Thanks for the explanation.  I agree mpv's not at fault.

At the very least I hope posting it here will help others that fall in the same trap (where the drivers automatically enable enhanced sync) figure out what suddenly went wrong with their setup since I couldn't find any traces/warnings through mpv logs as to why the VSync Ratio was going crazy.

Thanks again,

**Comment by lachs0r** [comment]
NVIDIA’s Adaptive VSync causes the same issues, by the way.

**Comment by haasn** [comment]
I assume vulkan is unaffected? (Since we can control the swapchain mode
in vulkan explicitly)

OpenGL needs to die already..
