### ISSUE TITLE
ASS Subtitle font border and shadow offset is scaled in anamorphic Video

### ISSUE THREAD

**Issue by Araynilmar** [mpv-player/mpv#6517]
### mpv version and platform
v0.29.0-g8b563a0346, Win10

### Video resolutions & aspect ratio
```
Native pixel resolutions: 720x440,
Display resolutions: 1050x440, 1920x805(Fullscreen)
Original display aspect ratio: 2.40:1
```

### ASS Subtitle Script Info
```
[Script Info]
ScriptType: v4.00+
Collisions: Normal
PlayDepth: 0
PlayResX: 1920
PlayResY: 805
**ScaledBorderAndShadow: No**
WrapStyle: 2

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Often,54,&H00FFFFFF,&H00FFFFFF,&H19333333,&H910E0807,0,0,0,0,100,100,0,0,1,3.0,2.0,2,10,10,10,1
```

### Actual behavior

![img_url](https://s2.ax1x.com/2019/02/23/khXX1e.jpg)

**Original size screenshot**
The frist screenshot captured by Potplay,  the subtitle is normally.
The second screenshot by MPV, defined "**_sub-ass-vsfilter-aspect-compat=no_**" in mpv.conf, the subtitle is normally.
The third screenshot by MPV, without "**_sub-ass-vsfilter-aspect-compat=no_**" in mpv.conf, the subtitle is stretched, and the font size and border width and shadow offset is scaled.

![img_url](https://s2.ax1x.com/2019/02/23/khXj6H.jpg)
**Fullscreen size screenshot**
The frist screenshot captured by Potplay,  the subtitle is normally.
The second screenshot by MPV, defined "**_sub-ass-vsfilter-aspect-compat=no_**" in mpv.conf, the subtitle font size is normally, but the font border width and shadow offset is scaled.

How to fix this problem?

**Comment by lachs0r** [comment]
Also set `sub-ass-vsfilter-blur-compat=no`.

**Comment by Araynilmar** [comment]
> sub-ass-vsfilter-blur-compat

Thx. It's works. 
Btw,
```
sub-ass-vsfilter-blur-compat=no
sub-ass-vsfilter-aspect-compat=no
```
Does disabling these options will cause any compatibility issues?
