### ISSUE TITLE
Question: How to play every video from a playlist at a new random starting time with random length?

### ISSUE THREAD

**Issue by 22i** [mpv-player/mpv#6519]
i am trying to play a folder of videos. And every video in the playlist should start at a random starting point with a random length bigger than 4 and and up to 8.

For example video1 could start at random 03:42 and last for 5 seconds then next video video2 starts playing with random starting time lets say 08:22 and lasts fro 8 seconds then goes to next video and it does the same all the way till the end of the playlist.

How can this be done?

**Comment by zc62** [comment]
Write a lua script.

https://mpv.io/manual/master/#lua-scripting
https://mpv.io/manual/master/#properties
https://mpv.io/manual/master/#events
https://mpv.io/manual/master/#list-of-input-commands

**Comment by Hrxn** [comment]
Or try a EDL file, i.e. as described [here](https://github.com/mpv-player/mpv/blob/2e7f60c38691fddfa67da07ac5ca2ad15dc84097/DOCS/edl-mpv.rst).

**Comment by haasn** [comment]
Or use a Lua script to generate an EDL file

**Comment by denisgarnett** [comment]
if i understood you correctly, and you are mac user, you can try Elmedia player for this, you just choose firstly the video and then put bookmarks on the place you want video begin to play, read more here https://www.eltima.com/wiki/user-guides/elmedia-mac/controls.html
