### ISSUE TITLE
Subsync support

### ISSUE THREAD

**Issue by haarp** [mpv-player/mpv#6520]
Greetings,

I'd like to request integration of [subsync](https://github.com/smacke/subsync).

It's a tool that automatically synchronizes subtitles to a video, which sounds like a very nice thing to have.

mpv doesn't have any interface/script to use it yet (as of today's git), but it shouldn't be too hard to implement, seeing as it's merely a command-line tool to be called.

Thanks!

**Comment by zc62** [comment]
Looks like no special interface is needed. A simple lua script will suffice.

**Comment by v-fox** [comment]
This probably would be much more efficient if it was done right in subtitle-handling subsystem of mpv. Like using better timing, working for SSA/ASS, maybe even automatically breaking up annoying fused lines where later part actually goes seconds after the beginning.

How many moments were spoiled by dramatic revelation being done in crappy subtitles before it actually was told by a character ? Although, that wouldn't work when spoken and written languages differ, where it really counts.

**Comment by wm4** [comment]
Anyone is free to write a script.
