### ISSUE TITLE
MPV cannot play youtube music videos

### ISSUE THREAD

**Issue by Krishna16** [mpv-player/mpv#6521]
I just installed MPV player on ubuntu and I noticed that normal youtube videos play just fine, but when I choose a music video, such as Rap God by Eminem or any other music video, it throws this error, "[ytdl_hook] youtube-dl failed: unexpected error occurred. Failed to recognize file format."

Anyone else facing this same issue and have found a workaround for it??

Thanks in advance.

**Comment by CounterPillow** [comment]
1. what mpv version
2. what youtube-dl version
3. where's your full log file generated with `--log-file=mpv.log`?
4. why did you ignore the issue template?

**Comment by Krishna16** [comment]
> what mpv version
> what youtube-dl version
> where's your full log file generated with --log-file=mpv.log?
> why did you ignore the issue template?

mpv version: mpv git-2018-11-18-ce2253b
youtube-dl version: 2016.02.22

Can you tell me more on how I can get the log file and the issue template??

**Comment by CounterPillow** [comment]
> youtube-dl version: 2016.02.22

Your youtube-dl is severely out of date, this is what's causing the issue. Please update.

>how I can get the log file

from the command line, run `mpv --log-file=mpv.log youryoutubeurlhere` with youryoutubeurlhere replaced by the URL, and then you'll have an `mpv.log` in your current working directory.

>the issue template??

that's the thing you deleted out of the text box when you opened the issue

**Comment by Krishna16** [comment]
> youtube-dl version: 2016.02.22
> 
> Your youtube-dl is severely out of date, this is what's causing the issue. Please update.
> 
> how I can get the log file
> 
> from the command line, run mpv --log-file=mpv.log youryoutubeurlhere with youryoutubeurlhere replaced by the URL, and then you'll have an mpv.log in your current working directory.
> 
> the issue template??
> 
> that's the thing you deleted out of the text box when you opened the issue

Thank you so much for your time and effort. It's up and running now. I just updated youtube-dl to the latest 2019 version. Do you still want the log file and the issue template??

Thanks a lot once again!!

**Comment by mc4man** [comment]
You should be updating youtube-dl every month or so, repo packages are usually outdated by the release of which ever ubuntu release you're using. 
In your case the ppa page would have told you that...

If you are using a dock that supports desktop actions (quicklists) then r. clicking on the mpv icon when it's there or locked to dock will give that info also plus 7 or 8 other useful links.

If you don't want to have to update youtube-dl manually & if you have snapd installed there is now a youtube-dl snap that auto updates every 2 weeks or so. (edge version 
There is full instructions on this alt. means in one of the quicklist entries.
