### ISSUE TITLE
Cannot seek back to the beginning of the file with cache enabled

### ISSUE THREAD

**Issue by gunnarmarten** [mpv-player/mpv#6522]
### mpv version and platform

mpv 537006965e Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 ffmpeg library versions:
    libavutil       56.22.100
    libavcodec      58.35.100
    libavformat     58.20.100
    libswscale      5.3.100
    libavfilter     7.40.101
    libswresample   3.3.100
 ffmpeg version: 4.1.1

Running on OSX 10.14.3

### Reproduction steps

To reproduce enable the cache and play the sample file until the cache range is updated (12 seconds into the movie) then press pause (just to have time to trigger the seek) and do a seek to 0.0. It fails with a normal seek and hr-seek.

When the cache range is updated once more (soon after the first update) the seeking to the beginning works as expected.

For testing purpose add a keybinding in the input.conf:

`e     osd-msg-bar seek +0  absolute exact`
`w     osd-msg-bar seek -12  relative keyframe`

Play the file with:

`
mpv --cache=yes test.mp4 --log-file=seek_bug.txt
`

And soon after the cache range is updated (look at the indicator of the osd) press the key and it always seek to the start of the cache range (2.000 seconds)

### Expected behavior

Seeks to the beginning of the file.

### Actual behavior

Seeks to the beginning of the cache range. In this case:

```
[  24.685][d][cplayer] Run command: seek, flags=14, args=[0.000000, absolute, exact]
[  24.685][v][lavf] queuing seek to 0.000000
[  24.685][v][lavf] cached range 0: 2.000000 <-> 20.066667 (bof=1, eof=1)
[  24.685][v][lavf] ...using this range for in-cache seek.
[  24.685][v][lavf] seeking stream 0 (video) to packet 2.000000/1.966667
[  24.704][v][cplayer] hr-seek, skipping to 0.000000
```

and the video plays from second 2.000.

As seen in the logfile the bof flag looks suspicious. It probably should indicate if the range is the beginning of the file but in this case the range is not. So my guess is there's something broken with the bof flag.

### Log file

https://0x0.st/z-p3.txt

### Sample files

https://0x0.st/z-pl.mp4

**Comment by Akemi** [comment]
works here without problems with `--no-config --cache=yes`. mpv is master and ffmpeg is d8ebfd1bdf.

**Comment by CounterPillow** [comment]
Also works for me with no problems, mpv mpv 0.29.0-134-g8b563a0346 and ffmpeg version: N-93214-g7e4d3dbe18

**Comment by gunnarmarten** [comment]
The timing is important here. You have to seek right after the first time the cache range is adjusted.

But I found another way to trigger the bug. So when I use the loop-ab functionality I can trigger it every time.

We want to loop the sample file from 0.0-12.5 sec:

`mpv -v --cache=yes --no-config --ab-loop-a=0.0 --ab-loop-b=12.5 test.mp4`

The result is mpv loops from 2.0-12.5 sec. (not that easy to see in the sample video because the beginning is mostly black but you can see it in the status line too)

With `--cache=no` it works as expected from 0.0-12.5 sec.

**Comment by Akemi** [comment]
yeah, with that exact timing i can reproduce your issue.

**Comment by zc62** [comment]
Tried on a piece of 4K video file and fine tuned ab-loop a/b positions to make the cache start from a non-zero point before seeking to zero, but mpv still works. Log:
```
[lavf] queuing seek to 0.000000
[lavf] cached range 0: 4.938272 <-> 54.454454 (bof=0, eof=0)
[lavf] execute seek (to 0.000000 flags 32)
[lavf] seek done
[cplayer] hr-seek, skipping to 0.000000
[cache] Dropping cache at pos 48, cached range: 208830422-229310422.
[cache] Seeking underlying stream: 229310422 -> 48
```
mpv a127912345 windows build.

**Comment by gunnarmarten** [comment]
For the record, I tested in the meantime with PR #6360 which has some demux fixes and also with wm4's fork (https://github.com/wm4/mpv_backup.git) which has even more fixes but both have the same issue. (any plans on merging these?)

Then I digged into the demux code and I think I found the bug. I will file a PR soon.
