### ISSUE TITLE
input command "loadlist <playlist> append" does not trigger "file-loaded" event

### ISSUE THREAD

**Issue by blue-sky-r** [mpv-player/mpv#6523]
### mpv version and platform

[cplayer] mpv 0.29.1+git-f2e7e81 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Thu Jan 31 01:41:44 UTC 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.24.101
[cplayer]    libavcodec      58.42.102
[cplayer]    libavformat     58.24.101
[cplayer]    libswscale      5.4.100
[cplayer]    libavfilter     7.46.101
[cplayer]    libswresample   3.4.100
[cplayer] ffmpeg version: git-2018-12-16-de5e71f
[cplayer]
[cplayer] Configuration: ./waf configure --enable-pdf-build --enable-dvbin --enable-dvdread --enable-dvdnav --enable-html-build --enable-cdda --prefix=/usr --confdir=/etc/mpv
[cplayer] List of enabled features: 52deb alsa asm atomics build-date cdda cplayer cplugins cuda-hwaccel debug-build drm dvbin dvdnav dvdread dvdread-common egl-helpers egl-x11 fchmod ffmpeg ffnvcodec gl gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack javascript jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm librt linux-fstatfs lua optimize oss-audio posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rubberband uchardet vaapi vaapi-egl vaapi-glx vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vt.h x11 xv zlib                                                                                                                           

### Reproduction steps

mp.commandv("loadlist", playlist, "append")

### Expected behavior

[name] load_playlist(live-ski-sk.m3u8, replace)
[name] on_playlist_change(playlist, {{"filename" = "#EXTINF:0,Biela ...
[name] name:playlist-count, val:128
[name] on_playlist_change(playlist, {{"filename" = "#EXTINF:0,Biela ...
[name] file_loaded

### Actual behavior

[name] load_playlist(live-ski-sk.m3u8, replace)
[name] on_playlist_change(playlist, {{"filename" = "#EXTINF:0,Biela ...
[name] name:playlist-count, val:128
[name] on_playlist_change(playlist, {{"filename" = "#EXTINF:0,Biela ...

### Sample files

Please note that "loadlist <playlist> replace" correctly triggers "file-loaded" event,
however "loadlist <playlist> append" does not. The parsing process of appending
larger playlist can take significant amount of time and "file-loaded" event is the only
meaningful way to know the playlist has been appended. In my opinion 
 loadlist file append
 loadlist file replace
should behave consistently and trigger "file-loaded" event

**Comment by zc62** [comment]
The `file-loaded` event you see in `loadlist "<playlist>" replace` does not indicate the playlist file is loaded. It means the first media file in the new playlist is loaded. In the `append` case, which file are you expecting mpv to load? The current file is still playing.

**Comment by blue-sky-r** [comment]
Oh, OK ... I see, file-loaded event is related to the media-file only, not the playlist. 
Thank You for the clarification, so closing the issue ...

**Comment by zc62** [comment]
@blue-sky-r Did you really find that appending large playlists can take long time? Because once I played with a playlist that have around 400k entries (when testing something for another issue), and it loaded nearly instantly. In what kind of situation do you find such validation is needed?

**Comment by blue-sky-r** [comment]
Let me explain. I've been loading (live ip cameras from local ski resorts) m3u8 playlist via:

mp.commandv("loadlist", playlist, "append")

The Playlist contains approx 100 iptv stream addresses, that means approx 200 lines (as each stream entry has 2 lines). It takes a few seconds to parse/load this playlist (3-5 sec). Maybe it takes this longer time due to url addresses and #EXTINF lines in the playlist ...

As "loadlist playlist" is not blocking (async) the script continues executing the code and it executes a lot of code in this 3-5 sec time. Therefore I used descriptive "significant amount of time" as from computer point of view. It is definitely not minutes or anything like that. But as the code after "loadlist playlist" expects the valid/loaded playlist I was looking for either something like blocking (sync) "loadlist playlist" or waiting for some event when playlist is loaded to continue.

**Comment by zc62** [comment]
https://mpv.io/manual/master/#command-interface-async
> Note that only a few commands will support this (usually this is explicitly documented). Some commands are asynchronous by default (or rather, their effects might manifest after completion of the command).

Looks like `loadlist` isn't documented to support asynchronous execution, but according to your description, it is asynchronous by default. Probably you can open a new issue to request the ability to turn off `async` in `loadlist`, and possibly make the document clearer.

**Comment by blue-sky-r** [comment]
It looks I have found another problem as I was assuming that the playlist to append should not start with #EXTM3U identifier. When I added #EXTM3U to the beginning of playlist being appended it actually loads quite quickly. Will do more testing of presumably async behaviour of loadlist command later and post results.

Thanks for your time and help ...

**Comment by zc62** [comment]
It turns out that the current `loadlist` implementation is indeed **not** async. The async one is here: https://github.com/mpv-player/mpv/pull/6360/commits/76dc5d9aa92f5c91c728004214f7b08c3a85a5f6. So not sure what really happened when you felt the commands following `loadlist` were executed before `loadlist` could finish.
