### ISSUE TITLE
keep-open=no not being followed

### ISSUE THREAD

**Issue by sprite-1** [mpv-player/mpv#6524]
### mpv version and platform
```
mpv git-2019-02-24-5370069 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Wed Feb 27 17:55:35 UTC 2019
ffmpeg library versions:
   libavutil       56.26.100
   libavcodec      58.47.102
   libavformat     58.26.101
   libswscale      5.4.100
   libavfilter     7.48.100
   libswresample   3.4.100
ffmpeg version: git-2019-02-27-4571c7c
```
elementary OS 5.0 | I installed using [this repo](https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests) provided on the mpv.io website.

### Reproduction steps
1. Add `keep-open=no` into your `mpv.conf` file
2. Open a video file from the file manager
3. Wait for it to finish
4. Instead of exiting, mpv player just shows the default window

### Expected behavior
It should exit after the video finishes playing

### Actual behavior
It brings me back to this window
![image](https://user-images.githubusercontent.com/33685433/53519954-6f568480-3b0f-11e9-89cc-b7c306ca9970.png)

It was working fine in an older version though

### Log file
When I run mpv with the `-v` flag, or just generally from the Terminal, it seems to work properly so I'm not sure how I'm going to debug it if it's only happening when I run it by double clicking a video file in the file manager.

**Comment by Hrxn** [comment]
An issue with the `pseudo-gui-mode` settings?

**Comment by sprite-1** [comment]
These are the only options in my `mpv.conf` file

```
autofit-larger=100%x80%
cursor-autohide=250
cursor-autohide-fs-only
keep-open=no
no-input-default-bindings
osd-font-size=28
osd-scale-by-window=no
screenshot-directory=~/Pictures/mpv/
screenshot-format=png
screenshot-template=mpv_%tY-%tm-%td_%tH%tM%tS
script-opts=osc-vidscale=no
volume-max=150
pause=no
```

**Comment by CounterPillow** [comment]
put `log-file=/tmp/mpvsucks.log` into your config, reproduce the issue, and then give us mpvsucks.log

**Comment by sprite-1** [comment]
Here's the generated log file

[mpvrocks.log](https://github.com/mpv-player/mpv/files/2912301/mpvrocks.log)

At the near end of the file, at the [75.XXX] mark is when I manually closed the mpv window because it showed me the default screen again.

**Comment by CounterPillow** [comment]
Normally we'd see the configuration options mpv loads in the log file, but that isn't inside yours. Why is that? Did you manually cut it out?

**Comment by sprite-1** [comment]
I didn't edit the file whatsoever :thinking: that was how it came fresh from the `/tmp/` folder

**Comment by mc4man** [comment]
Most users I provide for want the window (psuedo-gui) to stay open so mpv is configured that way.
If you don't want that then  in mpv.conf
[pseudo-gui]
idle=once

or idle=no   (same diff I believe

It tells you this in the ppa page, when using a ppa it's a good idea to go to the page & read..

**Comment by sprite-1** [comment]
> It tells you this in the ppa page, when using a ppa it's a good idea to go to the page & read..

Thank you and sorry, I've had mpv installed for a while using your repo and my configuration worked without this issue. It just came out of the blue one day so I just assumed it was a bug since I didn't change anything in my settings. :sweat_smile:

**Comment by mc4man** [comment]
Hmm, I've been changing the default of idle=once to idle=yes since mid september 2016. There's a possibility that in one or two of the 50 or so builds since then I may have forgotten to do so as I also change some of the osc defaults to more useful values (to me
Keep in mind this only affects the pseudo-gui, by default cli always closes, the keep-open= option is for cli.

**Comment by sprite-1** [comment]
> There's a possibility that in one or two of the 50 or so builds since then I may have forgotten to do so

That's probably when I started to use mpv lol

> the keep-open= option is for cli

Oh okay, I didn't realize this, thanks!
