### ISSUE TITLE
Add video to playlist from clipboard with help of nircmd

### ISSUE THREAD

**Issue by Dimsok** [mpv-player/mpv#6527]
I did try SmartCopyPaste.lua for that purpose, but i use win xp, so it can't read from clipboard. Can someone create lua script, which does it with nircmd?

**Comment by zc62** [comment]
Request it in the original SmartCopyPaste.lua repository. I guess just replace the powershell code with nircmd.

**Comment by CounterPillow** [comment]
>but i use win xp

:thinking:
