### ISSUE TITLE
demux_edl: Issue with commenting out valid EDL

### ISSUE THREAD

**Issue by xM8WVqaG** [mpv-player/mpv#6529]
### mpv version and platform

```
OS: Windows 7 64-bit
```

First found it in lachs0r's from release build, but reproduced in shinchiro's from HEAD build (used for reproduction in this ticket).

```
>mpv.com --version
mpv 0.29.0-135-ga127912345 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Feb 24 10:59:22 DST 2019
ffmpeg library versions:
   libavutil       56.26.100
   libavcodec      58.47.102
   libavformat     58.26.101
   libswscale      5.4.100
   libavfilter     7.48.100
   libswresample   3.4.100
ffmpeg version: N-45600-gfc32e08941
```

### Reproduction steps

Make an EDL file of any file that normally plays in mpv.

```
# mpv EDL v0
sample.mp3,0,40,title=chapter_1
sample.mp3,40,50,title=chapter_2
sample.mp3,90,50,title=chapter_3
sample.mp3,140,20,title=chapter_4
sample.mp3,160,title=chapter_5
```

#### Final Line Comments

Comment out the last entry and it still gets added to the timeline but if you attempt to play that part of the timeline mpv closes

```
# mpv EDL v0
sample.mp3,0,40,title=chapter_1
sample.mp3,40,50,title=chapter_2
sample.mp3,90,50,title=chapter_3
sample.mp3,140,20,title=chapter_4
# sample.mp3,160,title=chapter_5
```

When launched from the command line:

![last-commented](https://user-images.githubusercontent.com/44505331/53682701-1b56c600-3cf0-11e9-8e68-33ea0104d44a.png)

```
C:\debug>mpv.com sample.edl
[osprofile] Attempting to load [windows] profile
Playing: sample.edl
[ffmpeg/demuxer] mp3: Estimating duration from bitrate, this may be inaccurate
[file] This is a directory - adding to playlist.
EDL: source file '.' has unknown duration.
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
File tags:
 Date: 2017
AO: [wasapi] 44100Hz stereo 2ch float
^C 00:00:14 / 00:02:41 (9%) Cache: 144s+5MB
```

When launched by drag-and-dropping the EDL onto an open mpv window:

![last-commented-gui](https://user-images.githubusercontent.com/44505331/53682862-011de780-3cf2-11e9-99f6-c4db51f0193d.png)

#### Adjacent Line Comments

If you comment out two or more adjacent lines then mpv fails to play the EDL:

```
# mpv EDL v0
sample.mp3,0,40,title=chapter_1
sample.mp3,40,50,title=chapter_2
# sample.mp3,90,50,title=chapter_3
# sample.mp3,140,20,title=chapter_4
sample.mp3,160,title=chapter_5
```

```
C:\debug>mpv.com sample.edl
[osprofile] Attempting to load [windows] profile
Playing: sample.edl
[ffmpeg/demuxer] mp3: Estimating duration from bitrate, this may be inaccurate
[file] Cannot open file './# sample.mp3': No such file or directory
Failed to open ./# sample.mp3.
EDL: Could not open source file './# sample.mp3'.
No video or audio streams selected.


Exiting... (Errors when loading file)
```

The exception to the "no adjacent comments" is line 2, I guess the first line containing the specification declaration is treated differently.

```
# mpv EDL v0
# sample.mp3,0,40,title=chapter_1
sample.mp3,40,50,title=chapter_2
sample.mp3,90,50,title=chapter_3
sample.mp3,140,20,title=chapter_4
sample.mp3,160,title=chapter_5
```

The above *works fine*.

### Expected behavior

I should be able to comment out adjacent lines as part of my edl workflow and still be able to play the file. I should also be able to comment out the final line without the final line still appearing in the timeline.

### Actual behavior

See reproduction steps.

### Log file

Logfile for final line comments timeline issue: https://0x0.st/zo-R.txt
Logfile for the adjacent lines playback failure: https://0x0.st/zo-n.txt

**Comment by garoto** [comment]
Unrelated to the bug, but what sort of line endings your `sample.edl` file have?

**Comment by xM8WVqaG** [comment]
> 
> 
> Unrelated to the bug, but what sort of line endings your `sample.edl` file have?

`LF`. If you try and use `CRLF` then mpv won't play the file - but [that's in the spec](https://github.com/mpv-player/mpv/blob/master/DOCS/edl-mpv.rst#syntax-of-mpv-edl-files) so it's working as intended.

I've been using this script to build EDL files: https://gitlab.com/dasime/mpv-create-edl which handles EoL correctly on Windows.

**Comment by garoto** [comment]
> You must use UNIX line breaks.

fucking hell, never noticed that bit of information /facepalm

> I've been using this script to build EDL files: https://gitlab.com/dasime/mpv-create-edl

Nice, thx for that.

**Comment by garoto** [comment]
So as a test, I hexedited a `sample.edl` and erased the `0x0D` byte of the header, while leaving all the 
remaining line endings as `CRLF` and the file was parsed successfully this time.

https://github.com/mpv-player/mpv/blob/9c684b8691e9a4d7029543af3ff90f66b6c9ae76/demux/demux_edl.c#L36

Is it enough to change the line above to `\r\n` for it to start working on Windows natively?

**Comment by xM8WVqaG** [comment]
Thanks for following up on this and for such a rapid fix @qmega and @sfan5!

**Comment by qmega** [comment]
@xM8WVqaG Thanks for a thorough report with useful test cases. :)

> So as a test, I hexedited a `sample.edl` and erased the `0x0D` byte of the header, while leaving all the
> remaining line endings as `CRLF` and the file was parsed successfully this time.
> 
> Is it enough to change the line above to `\r\n` for it to start working on Windows natively?

No, that wouldn't be enough to make it work in general. My guess is that all the lines in your test file had titles at the end, so the CRs were treated as part of the titles, which you might not have noticed. A line like `sample.mp3,40,50\r` would still fail to parse. Anyway, changing the header definition like that would make it *only* accept CRLF files, so it wouldn't be a good idea regardless.

**Comment by garoto** [comment]
> My guess is that all the lines in your test file had titles at the end, so the CRs were treated as part of the titles

Indeed, I copied the format posted by xM8WVqaG because convinience. Once I remove `,title=chapter_x` from all the lines, mpv errors out with:
```
   cplayer: Playing: sample.edl                                                                                                     
     demux: Error in EDL.                                                                                                           
   cplayer: No video or audio streams selected.
```
