### ISSUE TITLE
libmpv: race condition using simple SDL example at shutdown

### ISSUE THREAD

**Issue by cus** [mpv-player/mpv#6531]
### mpv version and platform

git master, linux

### Reproduction steps

1. Compile the SDL example: gcc -o main main.c \`pkg-config --libs --cflags mpv sdl2\` -std=c99
2. Run valgrind --tool=drd --show-confl-seg=no --trace-cond=yes  ./main av://lavfi:testsrc
3. Close the window when the video is already running

### Expected behavior

No "condition variable has not been initialized" or "Mutex not locked" errors.

### Actual behavior

Almost at the end the following is shown:

[...]
==24285== [2] cond_post_wait  cond 0xe0054c8
==24285== [1] cond_post_wait  cond 0xdf96ca0
==24285== [1] cond_broadcast  cond 0xdf96d10
==24285== [1] cond_destroy    cond 0xdf96ca0
==24285== [1] cond_destroy    cond 0xdf96d10
==24285== [1] cond_pre_wait   cond 0xdc5fcb8
==24285== [2] cond_destroy    cond 0x1c235d90
==24285== [2] cond_destroy    cond 0xe0054c8
==24285== [2] cond_broadcast  cond 0xdc5fcb8
==24285== [2] cond_signal     cond 0xdff2ea0
==24285== [2] cond_signal     cond 0xdff2ea0
==24285== [2] cond_broadcast  cond 0xdc5fcb8
==24285== [2] cond_broadcast  cond 0xdc5fcb8
==24285== [2] cond_broadcast  cond 0xdf96ca0
==24285== Thread 2:
==24285== condition variable has not been initialized: cond 0xdf96ca0
==24285==    at 0x4C3A885: pthread_cond_broadcast@* (in /usr/lib64/valgrind/vgpreload_drd-amd64-linux.so)
==24285==    by 0x5091527: kill_cb (vo_libmpv.c:254)
==24285==    by 0x501EFE6: mp_dispatch_queue_process (dispatch.c:281)
==24285==    by 0x504B747: mp_wait_events (playloop.c:60)
==24285==    by 0x504D851: run_playloop (playloop.c:1130)
==24285==    by 0x5048388: play_current_file (loadfile.c:1365)
==24285==    by 0x5048388: mp_play_files (loadfile.c:1530)
==24285==    by 0x5033B3F: core_thread (client.c:524)
==24285==    by 0x4C34DA3: ??? (in /usr/lib64/valgrind/vgpreload_drd-amd64-linux.so)
==24285==    by 0xB1E9558: start_thread (in /lib64/libpthread-2.26.so)
==24285==    by 0x70F581E: clone (in /lib64/libc-2.26.so)
==24285== 
==24285== Mutex not locked: mutex 0xdf96c78, recursion count 0, owner 0.
==24285==    at 0x4C38AB3: pthread_mutex_unlock (in /usr/lib64/valgrind/vgpreload_drd-amd64-linux.so)
==24285==    by 0x501EFE6: mp_dispatch_queue_process (dispatch.c:281)
==24285==    by 0x504B747: mp_wait_events (playloop.c:60)
==24285==    by 0x504D851: run_playloop (playloop.c:1130)
==24285==    by 0x5048388: play_current_file (loadfile.c:1365)
==24285==    by 0x5048388: mp_play_files (loadfile.c:1530)
==24285==    by 0x5033B3F: core_thread (client.c:524)
==24285==    by 0x4C34DA3: ??? (in /usr/lib64/valgrind/vgpreload_drd-amd64-linux.so)
==24285==    by 0xB1E9558: start_thread (in /lib64/libpthread-2.26.so)
==24285==    by 0x70F581E: clone (in /lib64/libc-2.26.so)
==24285== mutex 0xdf96c78 was first observed at:
==24285==    at 0x4C37A63: pthread_mutex_lock (in /usr/lib64/valgrind/vgpreload_drd-amd64-linux.so)
==24285==    by 0x5091514: kill_cb (vo_libmpv.c:252)
==24285==    by 0x501EFE6: mp_dispatch_queue_process (dispatch.c:281)
==24285==    by 0x504B747: mp_wait_events (playloop.c:60)
==24285==    by 0x504D851: run_playloop (playloop.c:1130)
==24285==    by 0x5048388: play_current_file (loadfile.c:1365)
==24285==    by 0x5048388: mp_play_files (loadfile.c:1530)
==24285==    by 0x5033B3F: core_thread (client.c:524)
==24285==    by 0x4C34DA3: ??? (in /usr/lib64/valgrind/vgpreload_drd-amd64-linux.so)
==24285==    by 0xB1E9558: start_thread (in /lib64/libpthread-2.26.so)
==24285==    by 0x70F581E: clone (in /lib64/libc-2.26.so)
==24285== 
[...]

### Comments

The conditinal and mutex which is referenced by thread 2 is already destroyed by thread 1.

It is possible that you have to try 3-4 times to hit this with valgrind.

The issue seems realtively harmless but I suspect this is the root cause of some hangs I am seeing occasionally with libmpv.

**Comment by wm4** [comment]
Should be fixed now.
