### ISSUE TITLE
Another `Refusing to load potentially unsafe URL from a playlist` error

### ISSUE THREAD

**Issue by aleprovencio** [mpv-player/mpv#6532]
### mpv version and platform
$mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.1

### Reproduction steps
this works as expected:
` youtube-dl https://g1.globo.com/rj/rio-de-janeiro/carnaval/2019/noticia/2019/03/03/folia-do-setor-popular-da-sapucai-conhece-camarote-parece-que-estou-vivendo-um-sonho.ghtml`

while this does not:
`mpv https://g1.globo.com/rj/rio-de-janeiro/carnaval/2019/noticia/2019/03/03/folia-do-setor-popular-da-sapucai-conhece-camarote-parece-que-estou-vivendo-um-sonho.ghtml`

### Expected behavior
mpv should play the video

### Actual behavior
returns the following error

### Log file
https://0x0.st/zoTv.txt

**Comment by sfan5** [comment]
<pre>
[   1.535][v][cplayer] Set property: stream-open-filename="memory://#EXTM3U\u000aytdl://globo:7426766" -> 1
</pre>
It appears youtube-dl is turning your URL into a playlist of 1 item, it probably shouldn't do this, especially with `--no-playlist`.

**Comment by wm4** [comment]
Probably fixed, who knows.
