### ISSUE TITLE
--target-peak behaves erratically

### ISSUE THREAD

**Issue by wsldankers** [mpv-player/mpv#6533]
### mpv version and platform

mpv f2e7e81 (git master) built on Sat Feb  9 23:29:38 CET 2019

Ubuntu 16.04 amd64 nvidia proprietary graphics driver

### Reproduction steps

Move `~~/config` out of the way so existing settings don't interfere.

Add bindings to enable/disable glsl-shaders and sigmoid-upscaling, for instance:

`b cycle-values glsl-shaders ~~/ravu.hook ""`
`B cycle sigmoid-upscaling`

Start `mpv --target-peak=300` on a (non-hdr) video that is less than display size. Fullscreen the video so the scaler kicks in.

Toggle glsl-shaders and sigmoid-upscaling using the keybindings.

### Expected behavior

The brightness is always approximately at 1/3rd of the display brightness, no matter the activation of glsl-shaders or sigmoid-upscaling.

### Actual behavior

At first, toggling sigmoid-upscaling seems to completely enable/disable target-peak.

Then, after enabling and immediately disabling glsl-shader, toggling sigmoid-upscaling now switches between dark and extra dark.

### Log file

[https://www.fruit.je/mpv-target-peak.log](https://www.fruit.je/mpv-target-peak.log)

### Sample files

It seems to trigger on all files I try.

**Comment by haasn** [comment]
Can you test a more recent master? That should fix at least one of your issues, if not all.

**Comment by wsldankers** [comment]
It does fix the quirk where toggling glsl-shaders affects subsequent sigmoid-upscaling behavior. However, sigmoid-upscaling (and linear-upscaling) now simply toggle between dark and extra dark. In an attempt to make my explanation less confusing:

Just dark:
- sigmoid-upscaling
- linear-upscaling

Extra dark:
- upscaling in gamma light
- unscaled video
- video scaled using ravu

I wish I had a way to tell which of these two is the ‘correct’ one.

**Comment by haasn** [comment]
Can you post a separate log of both cases? (If possible, using command line options instead of toggling the option at runtime)

**Comment by haasn** [comment]
By the way, you can use `--no-config` instead of moving `~~/config` out of the way.

**Comment by wsldankers** [comment]
Separate logs at: [https://www.fruit.je/mpv-6533/](https://www.fruit.je/mpv-6533/)

**Comment by wsldankers** [comment]
Some screenshots:

```mpv --no-config --image-display-duration=inf --screenshot-format=png --window-scale=2 apples.jpg```
![mpv-shot0001](https://www.fruit.je/mpv-6533/mpv-shot0001)

```mpv --no-config --image-display-duration=inf --screenshot-format=png --window-scale=2 --target-peak=300 apples.jpg```
![mpv-shot0002](https://www.fruit.je/mpv-6533/mpv-shot0002)

```mpv --no-config --image-display-duration=inf --screenshot-format=png --window-scale=2 --target-peak=300 --linear-upscaling apples.jpg```
![mpv-shot0003](https://www.fruit.je/mpv-6533/mpv-shot0003)

```mpv --no-config --image-display-duration=inf --screenshot-format=png --window-scale=2 --target-peak=300 --sigmoid-upscaling apples.jpg```
![mpv-shot0004](https://www.fruit.je/mpv-6533/mpv-shot0004)

**Comment by haasn** [comment]
For the record, the bottom two were correct. The top one was too dark, because it didn't linearize before multiplying in the target peak.
