### ISSUE TITLE
Image renders black when resolution is same as the geometry

### ISSUE THREAD

**Issue by lionep** [mpv-player/mpv#6539]
### mpv version and platform

Version `mpv git-2019-02-24-5370069` from mc3man mpv-tests respository
Platform : `ubuntu 16.04` on Intel NUC6CAYH

### Reproduction steps

Open an image (png or jpg) with a window geometry at the exact resolution of the image :
```
mpv --no-border --geometry=1920x1000+0+0 image_1920x1000.png
```

This also occurs if the image resolution is the same as the exact display resolution and running with `--fullscreen` option.
EDIT : It seems it occurs also when the geometry has the same scale of the image (960x500 for a content at 1920x1000)

This is not reproduced on Ubuntu 18.04 with same mpv version.

### Expected behavior

The image should be rendered in the box defined by geometry param.

### Actual behavior

A black window at the size of the geometry box is displayed, and at the top left of the box, a piece of the image that should be displayed.

### Log file

[Log file](https://0x0.st/zo0J.txt)

### Sample files

[Sample file used in command](https://0x0.st/zo0y.png)

**Comment by zc62** [comment]
Isn't this a compositor bug? What happens if you use `feh` to view the image with the same geometry specified?

**Comment by lionep** [comment]
Just had a try, I have no problem with feh.

**Comment by mc4man** [comment]
Can not reproduce with 16.04.6 using compiz, works fine with your sample command & file. Tried with both Intel & Nvidia drivers

**Comment by zc62** [comment]
Is this reproduced with xfwm4 on Ubuntu 16.04? Since you said xfwm4 solved your other issue.

**Comment by lionep** [comment]
I couldn't test on ubuntu 16.04 + xfwm4, but it's reproduced on 18.04 with gnome-shell, with two different hardware : Intel NUC7CJYH and Intel NUC8I3BEH

**Comment by wm4** [comment]
I'll just assume these are compositor bugs.
