### ISSUE TITLE
mpv runs in background

### ISSUE THREAD

**Issue by vitlib** [mpv-player/mpv#6543]
### mpv version and platform
mpv 0.23.0 Raspbian Stretch

### Reproduction steps
launch mpv with a link to a bandcamp album

### Expected behavior
Streaming the album, letting control the program

### Actual behavior
Mpv runs in background

### Log file
http://0x0.st/zodJ.txt

**Comment by zc62** [comment]
> mpv 0.23.0

That's over two years ago. Update to current git HEAD, or at least the latest release from the official repository or any ppa you prefer.

**Comment by zc62** [comment]
And probably you want `--force-window=yes`

**Comment by vitlib** [comment]
I installed it with `apt-get install mpv`, what ppa should I use?
Also, I'm using it via CLI.

**Comment by zc62** [comment]
Well, that is what raspbian stretch is providing... The best idea might be building mpv from source. Anyway, `--force-window` should work for you for this particular issue.
