### ISSUE TITLE
ALSA: Not being able to resume (or restart!) playback after it has been paused for some time

### ISSUE THREAD

**Issue by davidhq** [mpv-player/mpv#6544]
I spent last month fighting with this bug/issue, wasn't sure how and why this is happening but now I isolated the problem and it's most likely ALSA problem on RaspberryPi, not even mpv's. Nonetheless I ask for advice here since there is a chance:

- either issue can be resolved in some additional handling inside mpv
- you could give advice on how to debug this further and report to the right place
- you could also suggest a "hack" I could implement in my controller process which is starting and then communicating with mpv over ipc... I'm thinking of for example increasing and decreasing the volume by 1 point every few minutes... I'm not sure it would help, it's quite ugly and I decided to stop with my experiments here and share the story with someone else now (you, here).

So, what happens:

When playback is held on pause for around ~12h (maybe less, maybe a bit more), it's impossible to get anything to play again (unpause, even loading a next song) until mpv instance is restarted.

The issue doesn't happen on the same version of mpv on macOS (CoreAudio).

### mpv version and platform

```
mpv 0.29.0 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built by the RPi_Mike script on Tue Feb 26 09:53:13 CET 2019
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0.2
```

```
Distributor ID: Raspbian
Description:  Raspbian GNU/Linux 9.4 (stretch)
Release:  9.4
Codename: stretch
```

### Reproduction steps

Play something, pause it, return in ~12h, unpause looks ok in logs but no sound is produced. Same with loadfile.

### Expected behavior

It should "just work"

### Actual behavior

It is frustrating.

### Log file

https://gist.github.com/davidhq/9771b0f1fef2d844279eb230d1a83e25

**Comment by zc62** [comment]
Does this happen with other players? What's the version of ALSA? Your mpv looks recent enough, but AFAIK, raspbian ships software that are pretty ancient.

**Comment by davidhq** [comment]
Alsa version:
```
Advanced Linux Sound Architecture Driver Version k4.14.79-v7+.
```

I compiled mpv myself after suspecting it might be an issue with older version that gets installed with `apt-get install` ... turns out this behavious is exactly the same on `0.23`, `0.27` and finally `0.29`.

Other players: haven't tried, will do it for `mpg123` and report back.

pulseaudio: Also haven't explored but I will... in any case I'd like to get alsa to work regardless .. will report back how it goes with pulse.. but as I said: not sure if this is very relevant, I want to use alsa, if pulseaudio testing hints at a problem with alsa, then it's quite worth testing, if not, I don't think so... I can play with pulseaudio later for some other reason, not the focus is to fix this one outstanding glitch with alsa play.

**Comment by davidhq** [comment]
PS: I also tested on another device with updated firmware (`rpi-update`):

```
Advanced Linux Sound Architecture Driver Version k4.19.25-v7+.
```

same issue!

**Comment by cus** [comment]
Well, if you are in for hacks, then you can try to setting `audio-device` property to `null` on pause, and then back to `alsa` on resume.

**Comment by davidhq** [comment]
I report that `mpg123` when left in the paused state for ~15h resumed playback just ok.

I'm now testing `mpv` but directly - command line, not in the background and via ipc communication as I'm using it / need to use it.

I'm for the hacks sometimes "_" but here it would be great to come to the bottom of this and meanwhile if this hack works, it will be welcome so I can still enjoy music while I continue investigating for the proper cause and fix for this. I see one problem with it: it probably will introduce more checks because alsa is only used on linux... this then becomes not so sustainable to keep in as a permanent potential fix.

**Comment by davidhq** [comment]
I have an important update:

Something is for sure wrong with `mpv` interaction with the system since `mpg123` worked ok and now when I tested the basic mpv use (directly, not via background process + ipc), the problem is very visible. 

I left the play on pause overnight:

[code]
Playing: UB40 - Greatest Hits (Full Album)-oCl_y9wMMK0.mp3
 (+) Audio --aid=1 (mp3 2ch 48000Hz)
File tags:
 Artist: Compilations
 Album: Reggae
 Title: UB40 - Greatest Hits (Full Album)-oCl_y9wMMK0
AO: [alsa] 48000Hz stereo 2ch float
(Paused) A: 00:06:32 / 01:22:58 (7%) Cache: 4585s+144MB
[/code]

Then after around ~12h, I tried to unpause, what happens is:

Last line changes to:

[code]
A: 00:06:32 / 01:22:58 (7%) Cache: 4585s+144MB
[/code]

and seconds don't move, nothing is playing... when I try more pause/unpause iterations, nothing ever happens except occasionally seconds move forward by one.

**Comment by davidhq** [comment]
In the meantime I implemented your suggested hack and discovered I can use `auto` instead of `alsa`, so the special edge case for macOS is not relevant anymore... The hack did not seem to cause any weird issues or delays during normal operation... if it solves the problem in question, this is great... 

I would still like to help the project and try to drill down and figure out why the problem in the first place... so apart from "suggestions for fix", I could use some guidance on how to troubleshoot and investigate this further with more and more info each time. Could also try to recompile the latest version of mpv for RPi... now I used this great script from someone which compiles specific commit, not sure if it would still work for the latest one. Thank you for now and will report how the hack is working.

**Comment by davidhq** [comment]
@cus seems that your suggestions solves the issue and is a good workaround for the problem, thank you very much!

It still holds that it would be better not to have to use it so if there is any input from anyone in the next weeks / months, I'll be happy to help investigate / solve this.

**Comment by davidhq** [comment]
Update: issue wasn't solved, moved to PulseAudio. Now everything reasonably ok, mpv plays fine all the time.

**Comment by wm4** [comment]
Yes, that sounds strange. Pulse might close the audio device if paused long enough or so.
Does this situation recover if you disable and enable audio again with '#'?

**Comment by eichblatt** [comment]
I am having the exact same issue. I will try implementing this workaround and let you know if it works. Thank you for posting this.
