### ISSUE TITLE
Wrong color range when using hardware decoding on macOS

### ISSUE THREAD

**Issue by inflation** [mpv-player/mpv#6546]
### mpv version and platform
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Mar  5 11:38:41 EST 2019
ffmpeg library versions:
   libavutil       56.26.100
   libavcodec      58.47.103
   libavformat     58.26.101
   libswscale      5.4.100
   libavfilter     7.48.100
   libswresample   3.4.100
ffmpeg version: git-2019-03-04-db33283
```

### Reproduction steps
This issue happened when I was doing some experiments regarding to color matrix and color range. I used a jpeg image as source and encoded it into a 10 bit HEVC mp4 with BT.601, full color range, and MPEG1 chroma placement. Then I tried it using mpv with hardware decoding.

After further investigation, the color matrix transaction is correct, but the color range display is wrong. 

Encoding command:
```
x265 --y4m -D 10 - \
    --preset veryslow --lossless --me 1 --subme 0 --merange 0 \
    --colormatrix bt470bg --range full --chromaloc 1 \
    --output "$temp/video.265"
```
### Expected behavior
Mpv with software decoding and QuickTime Player produce the correct color range.
### Actual behavior
Mpv with hardware decoding (videotoolbox) squeezes the color range and makes it less contrastive.
### Log file
https://0x0.st/zHay.log

### Sample files

Source image: https://0x0.st/zHaw.jpg
Video file: https://0x0.st/zHa3.mp4
Screenshot (videotoolbox): https://0x0.st/zHaY.jpg

**Comment by zc62** [comment]
Maybe similar to #6369. FFmpeg/Apple bug.

**Comment by inflation** [comment]
That's a different issue. This one QuickTime Player does the right job. Could because of ffmpeg though.

**Comment by haasn** [comment]
```
[   0.499][i][vd] Using hardware decoding (videotoolbox).
[   0.499][v][vd] Decoder format: 1920x1080 [0:1] videotoolbox[nv12] bt.601/auto/auto/full/auto CL=unknown (auto 0.000000/0.000000/0.000000)
[   0.500][v][vf] [in] 1920x1080 videotoolbox[nv12] bt.601/bt.709/bt.1886/full/display SP=1.000000 CL=mpeg1/jpeg
[   0.500][v][vf] [userdeint] 1920x1080 videotoolbox[nv12] bt.601/bt.709/bt.1886/full/display SP=1.000000 CL=mpeg1/jpeg
[   0.500][v][vf] [userdeint] (disabled)
[   0.500][v][vf] [autorotate] 1920x1080 videotoolbox[nv12] bt.601/bt.709/bt.1886/full/display SP=1.000000 CL=mpeg1/jpeg
[   0.500][v][vf] [autorotate] (disabled)
[   0.500][v][vf] [convert] 1920x1080 videotoolbox[nv12] bt.601/bt.709/bt.1886/full/display SP=1.000000 CL=mpeg1/jpeg
[   0.500][v][vf] [convert] (disabled)
[   0.500][v][vf] [out] 1920x1080 videotoolbox[nv12] bt.601/bt.709/bt.1886/full/display SP=1.000000 CL=mpeg1/jpeg
```

So mpv thinks it's full range, but the video data it's getting appears to be limited range. Does videotoolbox always transform the video to limited range before giving it to us (why??)? If so, the bug is most likely a missing override in FFmpeg to force the output range to limited range when using videotoolbox.

The proper solution, of course, is to not use videotoolbox.

**Comment by Akemi** [comment]
flagging this as an ffmpeg videotoolbox bug for now.

**Comment by Akemi** [comment]
i added the necessary full range pixel formats to ffmpeg in my branch https://github.com/Akemi/FFmpeg/tree/vt_10bit (last three commits), which fixes this problem. i will send the patches to ffmpeg soonish.

**Comment by Akemi** [comment]
https://github.com/FFmpeg/FFmpeg/commit/2a9d461abcc88ab74f2143aada1e366a0961830c

fixed with ffmpeg.
