### ISSUE TITLE
Unknown/unsupported CodecID or missing/bad CodecPrivate data

### ISSUE THREAD

**Issue by Hello71** [mpv-player/mpv#6547]
### mpv version and platform

0.29.1

### Reproduction steps

Play files with strange CodecIDs in ffplay and mpv.

### Expected behavior

They get played with both.

### Actual behavior

They play in ffplay but not mpv.

**Comment by jeeb** [comment]
Not helpful without any further information.

**Comment by Hello71** [comment]
msmpeg4v3 is not handled anywhere.

**Comment by Hello71** [comment]
```
ffmpeg -f lavfi -i testsrc=duration=1:rate=30 -c msmpeg4v3 testsrc.mkv
mpv testsrc.mkv
```

**Comment by jeeb** [comment]
Alright, so "V_MPEG4/MS/V3" to AV_CODEC_ID_MSMPEG4V3
