### ISSUE TITLE
Honor Youtube URL sort parameter

### ISSUE THREAD

**Issue by anohren** [mpv-player/mpv#6548]
### mpv version and platform
0.29.1
macos 10.14.3

### Reproduction steps

- Go to complete video listing of a youtube channel
- Sort videos by oldest first
- Copy the url
- Open the url in mpv

### Expected behavior
The oldest video is put first in the playlist.

### Actual behavior
The most recent video is put first in the playlist.

### Sample files

ElectroBOOM sorted by date in ascending order:
https://www.youtube.com/user/msadaghd/videos?sort=da&view=0&flow=grid

**Comment by zc62** [comment]
I guess it's `youtube-dl` that ignores `sort=` completely.

```
https://www.youtube.com/user/msadaghd/videos?sort=da
```
has no difference from
```
https://www.youtube.com/user/msadaghd/videos
```
Same for
```
https://www.youtube.com/user/msadaghd/videos?sort=dd
```
and
```
https://www.youtube.com/user/msadaghd/videos?sort=p
```
Possibly related to https://github.com/ytdl-org/youtube-dl/issues/2405. Not a mpv issue then.

**Comment by anohren** [comment]
It wasn't meant as a bug report, just a feature request.

**Comment by zc62** [comment]
Probably there is no way to implement this in mpv. Request it in youtube-dl instead.

**Comment by anohren** [comment]
> Probably there is no way to implement this in mpv. Request it in youtube-dl instead.

Oh ok, got it!

I was hoping it'd be possible to use `--playlist-reverse` on ascending ordering, but perhaps it doesn't fit in well. I'll try over at youtube-dl instead.

**Comment by garoto** [comment]
```
mpv --ytdl-raw-options="playlist-reverse=" https://www.youtube.com/user/msadaghd/videos
```

**Comment by anohren** [comment]
> ```
> mpv --ytdl-raw-options="playlist-reverse=" https://www.youtube.com/user/msadaghd/videos
> ```

This doesn't honor the URL parameter, it just reverses whichever arbitrary ordering it happens to have by default.
