### ISSUE TITLE
Streaming .torrent video

### ISSUE THREAD

**Issue by FedeDP** [mpv-player/mpv#655]
Hi!
It would be great if mpv could stream videos from .torrent files, just like popcorntime or peerflix (https://github.com/mafintosh/peerflix) .
Something like mpv http://x/y.torrent .
Well, i don't really know if this task should belong to the media player, but it would be really great!

**Comment by l29ah** [comment]
> I would also like to add that this is a blatant misuse of the Torrent protocol and can destroy the swarm. Please do not use torrent for this purpose, and please do not use, support or recommend broken clients like these.

Can you elaborate please? BitTorrent swarm makes a great CDN.

**Comment by Akemi** [comment]
probably because sequential downloading files from the beginning is not beneficial for the swarm.

one of the first google explanation because i am lazy. there are probably more/better ones. https://wiki.vuze.com/w/Sequential_downloading_is_bad

also please don't necro such old issues.
