### ISSUE TITLE
Why does my bar look so weird and "mushy"?

### ISSUE THREAD

**Issue by fwanky** [mpv-player/mpv#6555]
My bar just looks really frickin weird and blurry, as seen in the  
https://0x0.st/zX-p.png
https://0x0.st/zX-f.png

mpv ver; 0.29.1

my conf: http://0x0.st/zX-W.conf

**Comment by CounterPillow** [comment]
Where's your log file? It's possible mpv is falling back to xv for you.

**Comment by fwanky** [comment]
How do I get a logfile?

**Comment by CounterPillow** [comment]
Yep, just as I thought. Your 3D acceleration (probably Mesa judging by `GPU 0: Intel(R) Haswell Desktop (integrated)`) is completely non-functional, so the GPU VO is never successfully picked. Fix your system.

**Comment by fwanky** [comment]
Oh jeez, that cant be good :0

**Comment by fwanky** [comment]
hah, nvm a reboot fixed this.

**Comment by haasn** [comment]
You (or your system's automatic update system) probably updated your graphics drivers but either didn't reload the kernel module or didn't restart X after reloading the kernel module.
