### ISSUE TITLE
[Feature Request] show source file in explorer

### ISSUE THREAD

**Issue by AlexanderEvans** [mpv-player/mpv#6560]
Current behavior:
So, currently, mpv shows the file name when you hit 'i', but there doesn't seem to be a way to show it in the explorer.

Request:
Add some way(hotkey or something?) to show that file in file explorer.

Use Cases:
1.  I have a folder of 1000+ music vids, some of them hours long.  I have gotten tired of a few of them/some downloaded improperly(eg no audio in the file, or video got glitchy) and the issue is with the file, not mpv, and I want to remove this file.  I listen on shuffle.  The bad file is now somewhere among hundreds of hours of video, and I have no good way to quickly find and delete these.

2.  I am watching video and a friend wants a copy.  Similar problem.  Really annoying to find.

3.  I want to change the track(aka file) name.  

It is really apparent when these handfuls of videos come up in my playlist, but tracking down around 200 videos among over 1000 is daunting.  Would be really nice to have someway to easily access or delete the file from the folder directly in mpv.

I hope this is the right place to make a feature request, thanks for your time.

**Comment by avih** [comment]
Add to your `input.conf`:
```
ctrl+e run explorer /select, "${path}"
```

**Comment by AlexanderEvans** [comment]
So, I added the line, and it now opens file explorer, but it just opens to the default, "This PC".  Is there a way to get it to got to the path?  Because `ctrl+e run explorer /select, ${path}` doesn't seem to do that on windows...  Unless I'm missing something?  Is there a doc file on it somewhere?  Sorry if this is something really basic.  I also tried `ctrl+e run explorer /select, "${path}"` but it still just opened the file explorer to "This PC"

**Comment by zc62** [comment]
I can confirm that command works perfectly for me, windows 7 here. How did you open the file? Command line or open-file-dialog script? See what
```
ctrl+e show-text ${path}
```
shows when you press Ctrl+e.

**Comment by AlexanderEvans** [comment]
@zc62  I used Auto Hot Key to open the folder like this:
```
	:*:_playmusic::
		send, {escape}
		run, "D:\Program Files Custom\MPV\mpv.exe" "D:\Users\Anonymous\Videos\Music videos" --shuffle --no-border --autofit=700x700 --geometry=3000:900
	return
```

I'm running in windows 10 pro if that makes a difference.  Here's a screenshot of what displays when I use` ctrl+e show-text ${path}`
https://prnt.sc/mzag21

**Comment by zc62** [comment]
I think it is because you opened a folder with mpv, and mpv mixes `\` and `/`, but `explorer.exe` apparently does not support `/`.

**Comment by AlexanderEvans** [comment]
So, I tried changing all the '\'s to '/'s and that does seem to have changed how it is listed with
`ctrl+e show-text ${path}`
however even with all them going the same direction it fails...

**Comment by zc62** [comment]
It is not just the last separator. mpv will use `/` for all the separators following the path that it received, if sub-directories exist, something like `D:\Users\Anonymous\Videos\Music videos/subdir/file1.mp4`.

You need to file a new issue to request this. On Windows use `\` only as the separator when printing paths.

**Comment by AlexanderEvans** [comment]
> 
> 
> It is not just the last separator. mpv will use `/` for all the separators following the path that it received, if sub-directories exist, something like `D:\Users\Anonymous\Videos\Music videos/subdir/file1.mp4`.
> 
> You need to file a new issue to request this. On Windows use `\` only as the separator when printing paths.

Thanks for explaining, will do.

**Comment by CogentRedTester** [comment]
You can also use powershell to change the forward slashes to backslashes in `input.conf`:

```
ctrl+e run powershell.exe -command `!explorer.exe '/select,' ( "${path}" -replace '/', '\' )!`
```

Note that this is using the custom quote syntax with the backtick ` character.

**Comment by stax76** [comment]
The [custom quotes](https://mpv.io/manual/master/#flat-command-syntax) feature is good to have and good to know. I was wondering if it would be doable without this feature, and found that it is:

```
ctrl+e run powershell -command "explorer.exe '/select,' ( '${path}' -replace '/', '\\' )"
```

**Comment by stax76** [comment]
The powershell solution works except when the file name has a dollar sign.

Maybe the task is better suited for a Lua script, there was a script in the wiki, unfortunately it's gone.

@Sneakpeakcss

https://github.com/mpvnet-player/mpv.net/issues/580

**Comment by stax76** [comment]
New Lua code can be found [here](https://github.com/mpvnet-player/mpv.net/issues/580#issuecomment-1817863995).

**Comment by lamborghinipth** [comment]
> The [custom quotes](https://mpv.io/manual/master/#flat-command-syntax) feature is good to have and good to know. I was wondering if it would be doable without this feature, and found that it is:
> 
> ```
> ctrl+e run powershell -command "explorer.exe '/select,' ( '${path}' -replace '/', '\\' )"
> ```
> 
> edit:
> 
> needs more escaping to support file names that contain single quotes:
> 
> ```
> ctrl+e run powershell -command "explorer.exe '/select,' ( \"${path}\" -replace '/', '\\' )"
> ```
I do not want to use Windows Explorer by default. Instead of explorer.exe, I use Tablacus.
However, it didn't work when I replace explorer.exe by Tablacus.exe path.

Could you help me?

**Comment by stax76** [comment]
There are some old scripting (IDispatch) interfaces that allow to control explorer. AutoHotkey might also be useful to do this. I don't know if it's possible and how hard it is. Here is something related:

https://www.autohotkey.com/boards/viewtopic.php?f=82&t=123320
