### ISSUE TITLE
Bg audio too loud and speech too quiet

### ISSUE THREAD

**Issue by smolseok** [mpv-player/mpv#6563]
### mpv version and platform

Most recent version

### Expected behavior

To play video with bg sound same volume as speech 

### Actual behavior

Bg sound is overwhelmingly loud compared to speech.

### Sample files

Does anyone know how to normalize audio on mpv, it's really annoying having to turn down the volume everytime there are explosions and turning it up when they speak.

**Comment by garoto** [comment]
One of these:

`mpv --af=lavfi=dynaudnorm [...]`
`mpv --af=lavfi=loudnorm [...]`

https://ffmpeg.org/ffmpeg-filters.html

**Comment by Akemi** [comment]
just search the issue tracker (https://github.com/mpv-player/mpv/issues/3979). there are various ways with the help of ffmpeg filters. some examples that might still work.

```
af=drc=2
af=lavfi=[dynaudnorm=g=5:f=250:r=0.9:p=0.5]
af=lavfi=[loudnorm=I=-16:TP=-3:LRA=4]
```

**Comment by smolseok** [comment]
The first one just disabled my audio completely, the second one works but I think third one sounds best. Thank you so much.

**Comment by bedrin** [comment]
This one causes dropped frames for me (output)

```
af=lavfi=[loudnorm=I=-16:TP=-3:LRA=4]
```

This one works great:
```
af=lavfi=[dynaudnorm=g=5:f=250:r=0.9:p=0.5]
```

**Comment by tomjaguarpaw** [comment]
None of the above worked for me, but via https://github.com/mpv-player/mpv/issues/6343#issuecomment-756087388 I found [a SuperUser question](https://superuser.com/questions/852400/properly-downmix-5-1-to-stereo-using-ffmpeg/1410620#1410620) which introduced the FFMpeg `pan` filter. Playing around, the following seems OK for me:

```
mpv '-af=pan="stereo|FL=0.707*FC+0.3*FL+0.1*BL+0.1*LFE|FR=0.707*FC+0.3*FR+0.1*BR+0.1*LFE"' <filename>
```

**Comment by flipflop133** [comment]
I think [this](https://mpv.io/manual/master/#options-audio-channels) should better fit your needs.

**Comment by tomjaguarpaw** [comment]
Thanks, but the first thing I tried was `--audio-channels=stereo`, with and without `--ad-lavc-downmix=yes`, but it didn't seem to have any effect.

**Comment by flipflop133** [comment]
What does the log says when you run mpv from the terminal? It should say something like this if it works:
`AO: [pulse] 192000Hz stereo 2ch float`

**Comment by tomjaguarpaw** [comment]
Yes it does say that, but the result in the audio is indistinguishable from when I omit `--audio-channels=stereo` (in which case the output says `AO: [pulse] 48000Hz 5.1(side) 6ch float`). In both cases the speech/dialogue is drowned out by the background noise/music. On the other hand, with

```
-af=pan="stereo|FL=0.707*FC+0.3*FL+0.1*BL+0.1*LFE|FR=0.707*FC+0.3*FR+0.1*BR+0.1*LFE"
```

or even, for 1980s mono recording, something as stark as

```
-af=pan="stereo|FL=1*FC|FR=1*FC"
```

the speech/dialogue comes across very clearly over the background noise/music.

**Comment by flipflop133** [comment]
Maybe you should open another issue then if you think that --audio-channels=stereo isn't working.
Also on thing you can try that really helps with inaudible voices is this setting:
`af=lavfi=[loudnorm=I=-16]`  equivalent to  `--af=lavfi="loudnorm=I=-16"`

**Comment by cheater** [comment]
@flipflop133 this already exists in #6343

**Comment by flipflop133** [comment]
What about this note in FFmpeg [documentation](https://ffmpeg.org/ffmpeg-filters.html#pan-1)  about the pan filter: 

> Note that ffmpeg integrates a default down-mix (and up-mix) system that should be preferred (see "-ac" option) unless you have very specific needs. 
Isn't the -ac the same as `--audio-channels=stereo`?

**Comment by cheater** [comment]
@flipflop133 this needs to work with mpv as well, not just ffmpeg.

**Comment by wolph** [comment]
Perhaps a useful addition for some, if you put the following lines in your `input.conf`, you can use the `F1` and `F2` keys to toggle the filters:
```
F1 af toggle "lavfi=[loudnorm=I=-16]"
F2 af toggle 'pan="stereo|FL=0.707*FC+0.3*FL+0.1*BL+0.1*LFE|FR=0.707*FC+0.3*FR+0.1*BR+0.1*LFE"'
```

**Comment by mzakomorny** [comment]
> Perhaps a useful addition for some, if you put the following lines in your `input.conf`, you can use the `F1` and `F2` keys to toggle the filters:
> 
> ```
> F1 af toggle "lavfi=[loudnorm=I=-16]"
> F2 af toggle 'pan="stereo|FL=0.707*FC+0.3*FL+0.1*BL+0.1*LFE|FR=0.707*FC+0.3*FR+0.1*BR+0.1*LFE"'
> ```
Make sure to use escape characters for the quotes on the second line, otherwise mpv says "Changing filters failed!". The following works:

`F2 af toggle "pan=\"stereo|FL=0.707*FC+0.3*FL+0.1*BL+0.1*LFE|FR=0.707*FC+0.3*FR+0.1*BR+0.1*LFE\""`
