### ISSUE TITLE
Use proper slash seperator for windows file paths

### ISSUE THREAD

**Issue by AlexanderEvans** [mpv-player/mpv#6565]
### mpv version and platform
Windows 10

### Reproduction steps
Add
`ctrl+e run explorer /select, ${path}`
to input.conf in windows 10

### Expected behavior
On Windows use '\\' only as the separator when printing paths so that it can be passed to file explorer to open the explorer with the file selected properly.

### Actual behavior
mpv outputs the path using '/'s instead for sub-directories which apparently confuses windows' file explorer.

### Alternate reproduction method
This behaviour can be very clearly observed why playing a folder of files in windows with a command such as:
`mpv.exe "<path to music folder>/Music videos folder" --shuffle`
and adding 
`ctrl+e show-text ${path}`
to input.conf

Then just press ctrl+e and observe the mixed `\ `and `/`

This was discussed more in this thread if it is unclear: https://github.com/mpv-player/mpv/issues/6560

**Comment by avih** [comment]
> mpv outputs the path using '/'s instead for sub-directories which apparently confuses windows' file explorer.

No, it outputs exactly the value you used when running mpv .

If you want paths to contain only `\`, call mpv with paths with only '\`, or write a script to normalize the path either on load or when you invoke explorer.

**Comment by AlexanderEvans** [comment]
> 
> 
> > mpv outputs the path using '/'s instead for sub-directories which apparently confuses windows' file explorer.
> 
> No, it outputs exactly the value you used when running mpv .
> 
> If you want paths to contain only `\`, call mpv with paths with only `\`, or write a script to normalize the path either on load or when you invoke explorer.
> 
> edit: mpv does seem to use `/` to append items when creating a playlist from a directory. Not sure it should normalize the path because it works for mpv needs, but some external programs (explorer) could be more picky. But a script can still trivially do it for you.

Can you point me to some documentation to how I can hook into mpv with a script to do that?  I really don't understand much of anything about how input.conf works or what it is, and explorer doesn't seem to like the way mpv spits our the path by default...

**Comment by avih** [comment]
[The manual](https://mpv.io/manual/master/) has sections about scripting in lua/js.

This should work also for directory playlist items: save this text as `show-in-explorer.js` at your `scripts/` folder:
```
mp.register_script_message("show-in-explorer", function(path) {
    mp.commandv("run", "explorer", "/select,", (path || ".").replace(/\//g, "\\"));
});
```

Then in your `input.conf` add:
```
ctrl+e script-message show-in-explorer ${path}
```

**Comment by AlexanderEvans** [comment]
> 
> 
> [The manual](https://mpv.io/manual/master/) has sections about scripting in lua/js.
> 
> This should work also for directory playlist items: save this text as `show-in-explorer.js` at your `scripts/` folder:
> 
> ```
> mp.register_script_message("show-in-explorer", function(path) {
>     mp.commandv("run", "explorer", "/select,", (path || ".").replace(/\//g, "\\"));
> });
> ```
> 
> Then in your `input.conf` add:
> 
> ```
> ctrl+e script-message show-in-explorer ${path}
> ```

Ty, this works exactly as I needed.  I had no idea that mpv could be extended like this.  I will keep this in mind going forward.  Still might want to consider changing how mpv appends slashes to paths in windows, but this is good enough for me.  Ty again. 😄

**Comment by zc62** [comment]
See #6570

**Comment by Akemi** [comment]
since the PR was closed this idea is off the table.

**Comment by CogentRedTester** [comment]
> @CogentRedTester
> 
> Powershell is a bit slow, in most use cases fast enough, to be exact the startup is 200 ms when it was started before, for pwsh it's 400 ms. I try your solution and use it if it works.

Oh yea it's very slow compared to cmd or bash, but if you're just trying to open `explorer.exe` then I doubt even a 1 second delay matters much.

**Comment by stax76** [comment]
I confirm that it works perfectly, and the delay is no problem for this use case.

**Comment by stax76** [comment]
@CogentRedTester 

I'm not understanding the explanation marks in the command line, what do I have to google to find the documentation for it?

**Comment by CogentRedTester** [comment]
> @CogentRedTester
> 
> I'm not understanding the exclamation marks in the command line, what do I have to google to find the documentation for it?

[flat-command-syntax](https://mpv.io/manual/master/#flat-command-syntax), the 5th paragraph on custom quotes. I should probably change the example to use two backticks instead of `! though.

**Comment by stax76** [comment]
Thanks!
