### ISSUE TITLE
No option to specify port for sftp

### ISSUE THREAD

**Issue by aeioumania** [mpv-player/mpv#6566]
### mpv version and platform
0.29.1

### Reproduction steps
Attempt to view a video via sftp:// with a non-default port.

### Expected behavior
Some sort of option allows a port other than 22 to be selected.

### Actual behavior
mpv cannot connect  because the port is different, and exits.

**Comment by garoto** [comment]
Maybe `mpv "sftp://user:pass@ipaddress:port/path/to/file"`

**Comment by aeioumania** [comment]
@garoto 
That doesn't seem to work. I also tried adding a colon after the port, but they both failed to connect.

**Comment by garoto** [comment]
https://ffmpeg.org/ffmpeg-protocols.html#libssh

**Comment by zc62** [comment]
I can confirm what @garoto says works for me. Does sftp work for you before you changed to a non-default port? What is the error message (or a full log will be better, erase the sftp server information manually)?
