### ISSUE TITLE
frame-back-step for APNG jumps to file beginning

### ISSUE THREAD

**Issue by kissaev** [mpv-player/mpv#6567]
### mpv version and platform
mpv 0.29.1
### Reproduction steps
frame-step working good but when i press "," for frame-back-step command APNG file always jumps to the first frame
### Expected behavior
Expected work like for GIFs, frame-step and frame-back-step work as it should
### Actual behavior
frame-step jumps to 1 frame forward, frame-back-step DON'T jump 1 frame backward
[cplayer] Backstep failed. < from -v output

**Comment by zc62** [comment]
Works here.

Provide a full log generated by [`--log-file`](https://mpv.io/manual/master/#options-log-file) and upload the sample file that mpv fails to work with.

**Comment by kissaev** [comment]
[apng.txt](https://github.com/mpv-player/mpv/files/2982299/apng.txt)
![elephant](https://user-images.githubusercontent.com/5376567/54591459-f32acf00-4a32-11e9-834e-f4f81472616f.png)
Sample file and generated log file

**Comment by zc62** [comment]
Still works here. Can you try mpv git master and ffmpeg git master? Might be an already resolved ffmpeg issue.

**Comment by kissaev** [comment]
where i can find links for mpv git master and ffmpeg git master? I'm need to build it myself?

**Comment by CounterPillow** [comment]
This works for me even in mpv 0.29.1.

**Comment by kissaev** [comment]
Thanks all, i reinstalled mpv, ffmpeg and many dependencies from homebrew and now it works like a charm!
