### ISSUE TITLE
Short lag after trigger an overlay

### ISSUE THREAD

**Issue by Ninelpienel** [mpv-player/mpv#6569]
### mpv version and platform

mpv-x86_64-20190316-git-dd83b66 (from shinchiro)

### Reproduction steps

Open a file and do something that trigger an overlay like changing the volume or enabling a filter.

### Expected behavior

No lag.

### Actual behavior

A short lag for 1 second.

### Log file

https://pastebin.com/Wt89ZBGD

### Issue

When I open any video file the first time I change the volume or enabling a filter the player lags for a second. I have this issue with lachs0r's and shinchiro's Windows builds. I have Windows 10 Pro x64, an Intel I7 6700k, a Nvidia GeForce GTX 970 and 16 GB DDR4 ram.

**Comment by zc62** [comment]
```
[  14.681][v][osd/libass] Shaper: FriBidi 1.0.5 (SIMPLE) HarfBuzz-ng 2.3.1 (COMPLEX)
[  14.682][v][osd/libass] Setting up fonts...
[  15.070][v][osd/libass] Using font provider directwrite
[  15.071][v][osd/libass] Done.
[  15.073][v][osd/libass] fontselect: (sans-serif, 400, 0) -> ArialMT, 0, ArialMT
[  15.075][v][osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
```
The same issue as #6447 (and several other similar ones). See if https://github.com/mpv-player/mpv/issues/6447#issuecomment-473525045 helps.
