### ISSUE TITLE
Playback position on seek bar is inaccurate with OPUS audio

### ISSUE THREAD

**Issue by guixxx** [mpv-player/mpv#6571]
### mpv version and platform
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.1
```

### Reproduction steps
1. Download this OPUS song: https://0x0.st/z8Wv.opus
2. Play it with mpv.

### Expected behavior
The seek bar to be "empty", like so:

![mpv-correct](https://user-images.githubusercontent.com/27077338/54636726-d2c83800-4a65-11e9-8693-61eb17eb5258.png)

### Actual behavior
The Seek bar is "filled" by about 25%, even though the song is still at 00:00:00:

![mpv](https://user-images.githubusercontent.com/27077338/54636773-e83d6200-4a65-11e9-8e92-3e5a75eedbec.png)

It also makes seeking inaccurate

### Log file

https://0x0.st/z8Wg.txt

### Sample files

https://0x0.st/z8Wv.opus

**Comment by ebm539** [comment]
Also seeing this on vorbis files, such as http://www.piano-midi.de/ogg/beethoven/elise.ogg
![2019-04-24-191337_1920x1080_scrot](https://user-images.githubusercontent.com/25342857/56639568-13e6e400-66c5-11e9-89bf-3d6d344f18bf.png)

The seek bar is wrongly filled much more (comparable to screenshot in above comment) when the vorbis file has an image included.

For reference, an MP3 file, such as http://www.piano-midi.de/mp3/beethoven/elise.mp3 is not affected
![2019-04-24-191508_1920x1080_scrot](https://user-images.githubusercontent.com/25342857/56639676-5b6d7000-66c5-11e9-9861-6d8deab20571.png)
