### ISSUE TITLE
Can't get multimedia keys to work (Bluetooth keyboard with multimedia keys) WIN64

### ISSUE THREAD

**Issue by 44vince44** [mpv-player/mpv#6572]
Bluetooth Keyboard with Multimedia keys working with WMP, Foobar and others. It doesn't work in mpv. Platform Windows 10 x64.

I have those lines in my key bindings:
PLAY cycle pause
PAUSE cycle pause
PLAYPAUSE cycle pause
STOP quit
FORWARD playlist-next
REWIND playlist-prev

I add this in mpv.conf
input-media-keys=yes

Still doesn't work... 
Thanks everybody for any help!!

**Comment by Akemi** [comment]
try with "mpv --input-test --force-window --idle" and see if the keys are actually recognised. this command should open a new mpv window and when you hit any kind of key it will show the internal key name and what is bound to it in the top left corner.

**Comment by 44vince44** [comment]
Thanks Akemi, I've just tried what you told me to do. It seems that those keys are not recognized because nothing is being displayed when I press those keys. I pressed other keys (not multimedia) and I get the display of the binding(s) of the key.
I've also tried another bluetooth keyboard with multimedia keys, the same thing happens: multimedia keys are recognized by WMP and foobar, but not mpv.

**Comment by Akemi** [comment]
just to make sure, do you have a recent version of mpv?

**Comment by 44vince44** [comment]
No I didn't and sorry for not having checked.
Indeed with latest build, the multimedia keys are working fine!
Thanks !!

**Comment by Akemi** [comment]
for next time, you can close your open issues yourself.
