### ISSUE TITLE
ask before just quitting using q key

### ISSUE THREAD

**Issue by treaki** [mpv-player/mpv#6573]
### mpv version and platform
0.27.0 on debian testing

hi there, a way to add an are you sure question before quitting by just pressing the q button. i do that much to often while trying to adjust contrast (1 and 2) or panscan (w and e) in the dark. So it would be a huge improvement for me...

is there maybe a way to map q not to its default function but to some lua script that dose thinks like it should? or just deactivate q completely, i like to use Q even more...

thanks in advance.

### Reproduction steps
watch a video and press q by mistake
### Expected behavior
are you sure dialog
### Actual behavior
just quits and makes it hard to find back file and position
### Log file/  Sample files
not necessary

**Comment by garoto** [comment]
in your `input.conf`: 
```
q ignore
```

**Comment by Akemi** [comment]
you can use add_key_binding via a lua script to bind q to a function and do your logic in there. linux most likely has a way to open a dialogue box via command line, that also returns which button you pressed.

**Comment by zc62** [comment]
See https://github.com/mpv-player/mpv/issues/6023#issuecomment-408386578.
