### ISSUE TITLE
keep old resume file after resume

### ISSUE THREAD

**Issue by treaki** [mpv-player/mpv#6574]
### mpv version and platform
0.27.0 on debian testing

hi there, i like quitting mpv using the capital Q instead of just q because it remembers the position where i stopped. But when it resumes that it automatically deletes the resume file. IMHO it would be much better to keep the resume file as long as i am through with one video or ask if i want to delete it. Or even better updating the resume file while playing any x minutes (but prevent updating them when i press and hold up key or so by mistake)...
thanks in advance

### Reproduction steps
watch a video till some capture and press Q, resume watching afterwards but then close mpv by mistake. 
### Expected behavior
old resume file exist until video is watched through the end 
### Actual behavior
Resume watching again but have to find position back from the beginning.
### Log file/  Sample files
not necessary

**Comment by Akemi** [comment]
you can use a lua script for that. use the "add_periodic_timer" function and use command("write-watch-later-config"), to periodically save a resume file. you can also bind to the "start-file" event at, for example, and write the watch later config file at the start of every file.

**Comment by zc62** [comment]
There is a lua script for this. https://gist.github.com/Hakkin/5489e511bd6c8068a0fc09304c9c5a82. It is listed on the [wiki](https://github.com/mpv-player/mpv/wiki) User Scripts page.

#3169 might be related.
