### ISSUE TITLE
playlist-prev jumps multiple files

### ISSUE THREAD

**Issue by pumbur** [mpv-player/mpv#6576]
something related to `playback_short` results in `playlist-prev` jumping multiple files even when it shouldnt.

**Comment by anongit** [comment]
I had this problem with image playlists, "fixed" it with `--mf-fps 0.1`, which sets image duration to 10s, kind of, the actual display duration is still 1s, but `playback_short` no longer applies.

**Comment by pumbur** [comment]
yeah, currently it skips every item that previously reached end of file in less than second.
evident on stills or short videos, but can be done on hour-long movies too, if you fast enough.

i just have another patch commeting out that part.

**Comment by dermoth** [comment]
Using `--mf-fps 0.1` fixes this for the default display duration only (`--image-display-duration=1`) , but not if you do something like `--image-display-duration=0` or `--image-display-duration=0.1`.

This can be a great way to scan through a lot of images - i.e. don't delay for anything more that the image loading time. If if behaved properly we could stop (_spacebar_) and go back and forth to find the desired image.

Right now it goes back to the first image instead.

BTW if it's indeed a matter of images being too "short", the time should be cumulative at the very least; then maybe we'd go back a bunch of images but not all the way to the first.

**Comment by jaimet** [comment]
I have this same problem using mpv to view security camera mp4 video clips produced by "[motion](https://motion-project.github.io/)" (the clips' lengths vary between a few seconds and a few minutes each).

Does anyone know why this bug only occurs in 1 direction ("playlist-prev" sometimes skips clips, but "playlist-next" always seems to behave correctly)?

Also, is there anything that I can add to the command line (just "`mpv *`" at the moment) to "work round" this bug?

TIA.

**Comment by dermoth** [comment]
I've noticed that if I only go forward/backward using `>` / `<` keys or let it play normally through files It works properly, but when fast-forwarding through multiple files with arrow keys it doesn't.

I like to use MPV as an image viewer as it's much faster to load pictures and quickly browse them (even better when disabling auto forward and quit after last file), and this is the same issue as short videos. It's very annoying but the workaround is easy.

BTW you can also advance to next with the `Enter` key, probably easier on US keyboards unless you also do a lot of back and forth (and for that I love my cf layout, `<` and `Enter` are next to each others, no modifier keys needed!).

**Comment by defaultxr** [comment]
I made a simple workaround for this issue. Create a file named `playlist_prev_workaround.lua` (or anything as long as it ends in `.lua`) in your mpv scripts directory (for me, on Linux, this is `~/.config/mpv/scripts/`) and save it with the following content:

```lua
function playlist_prev_workaround()
    -- Go to the previous item in the playlist.
    -- This is a workaround for the built-in playlist-prev command, which suffers from an issue that causes it to occasionally skip multiple files; see the bug report here: https://github.com/mpv-player/mpv/issues/6576 , "playlist-prev jumps multiple files"
    local pos = mp.get_property_native("playlist-pos")
    if pos ~= 0 then
        local new_pos = pos - 1
        mp.set_property("playlist-pos", new_pos)
    end
end

mp.add_key_binding(nil, "playlist-prev-workaround", playlist_prev_workaround)
```

Then edit your mpv `input.conf` (for me this is located at `~/.config/mpv/input.conf`) and add a line like the following:

```
< repeatable script-message playlist-prev-workaround
```

This will override the default action of the `<` key so that it uses the workaround function instead. For me, the workaround doesn't exhibit the behavior of the built-in `playlist-prev` command and only ever goes back one item in the playlist.

**Comment by jaimet** [comment]
I confirm that @defaultxr's [workaround](https://github.com/mpv-player/mpv/issues/6576#issuecomment-992109756) does indeed work around this bug.

Also, I attach a zip file which contains video files for anyone who wants to reproduce this bug. The durations of the contained video files are:

```
1.mp4: 2.0 seconds
2.mp4: 0.8 seconds
3.mp4: 0.8 seconds
4.mp4: 0.8 seconds
5.mp4: 0.8 seconds
6.mp4: 0.8 seconds
7.mp4: 0.8 seconds
8.mp4: 0.8 seconds
9.mp4: 10.0 seconds
```

 Hence, if you:

1. unzip the zip file
2. run `mpv *.mp4`

then...
*without* @defaultxr's [workaround](https://github.com/mpv-player/mpv/issues/6576#issuecomment-992109756), `playlist-prev` jumps from `9.mp4` straight back to `1.mp4`, whereas...
*with* @defaultxr's [workaround](https://github.com/mpv-player/mpv/issues/6576#issuecomment-992109756), `playlist-prev-workaround` correctly jumps backwards from `9.mp4`, playing each preceding file.

HTH.

[files.zip](https://github.com/mpv-player/mpv/files/7782176/files.zip)

**Comment by kllmanu** [comment]
I still have this issue on v0.38.0 on Archlinux. `playlist-next` works without an issue, but with `playlist-prev` i'm unable to to to the previous playlist item. If I hold it down for a few seconds it jumps back several items.

**Comment by sfan5** [comment]
Open a new issue.

**Comment by kllmanu** [comment]
sorry i was wrong, my fault, everything works as expected
