### ISSUE TITLE
frame-step with osd-bar displayed feature?

### ISSUE THREAD

**Issue by kissaev** [mpv-player/mpv#6579]
### mpv version and platform
0.29.1

### Reproduction steps
i use keybinding
`LEFT osd-bar frame-back-step ; show-text "Frame: ${estimated-frame-number} / ${estimated-frame-count}"`
and
`RIGHT osd-bar frame-step ; show-text "Frame: ${estimated-frame-number} / ${estimated-frame-count}"`
for frame-backward and frame-forward and osd-bar don't show in that case 

### Expected behavior
Is there a way to show osd-bar when doing frame-step and frame-back-step for navigation?

### Actual behavior
no osd-bar is displayed

**Comment by zc62** [comment]
You can let mpv display the progression bar by using the `show-progress` command.

Use
```
LEFT frame-back-step ; osd-bar show-progress ; show-text "Frame: ${estimated-frame-number} / ${estimated-frame-count}"
RIGHT frame-step ; osd-bar show-progress ; show-text "Frame: ${estimated-frame-number} / ${estimated-frame-count}"
```

**Comment by kissaev** [comment]
Wow, thanks, that's exactly what i want!
