### ISSUE TITLE
[Solved, with a plugin] create ipc socket per mpv instance

### ISSUE THREAD

**Issue by wis** [mpv-player/mpv#6580]
### mpv version and platform
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.1
```
`Linux aarch 5.0.3-arch1-1-ARCH #1 SMP PREEMPT Tue Mar 19 13:09:13 UTC 2019 x86_64 GNU/Linux`

### Reproduction steps
```input-ipc-server=/tmp/mpvsocket"${filename}"```
or
```input-ipc-server="/tmp/mpvsocket${filename}"```
in mpv.conf
### Expected behavior
make a `/tmp/mpvsocket<filename/optimally escaped filepath>` socket file

### Actual behavior
makes a /tmp/mpvsocket"${filename}" or /tmp/mpvsocket${filename} socket file

### Log file
[link](http://0x0.st/zKZa.txt) to it.

### Sample files
mpv.conf
``` mpv.conf
profile=top #Top level area, load top
#ontop=yes                 #Always on top

[top]
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample
#af=rubberband
af=scaletempo=stride=28:overlap=.9:search=25
input-ipc-server=/tmp/mpvsocket"${filename}"

[cam]
no-osc
no-input-default-bindings
input-conf=/dev/null
geometry=-0-0
autofit=30%
title="mpvfloat"
```

### problem i'm trying to solve
the commands to the socket are sent to the last file opened with mpv, I want to send commands to other files opened with mpv, having one socket per file/escaped path is a solution.

**Comment by avih** [comment]
`mpv.conf` is not a command interface where properties are expanded, and the ipc server is for the mpv instance, and won't change when playlist items are iterated, for instance.

If you always invoke mpv with one file and want the socket name to be based on that file name, wrap your invocation with a shell script which adds the argument based on the file name it plays.

**Comment by wis** [comment]
thanks for the reply, is there an API for plugins to modify/override options, specifically "[input-ipc-server](https://mpv.io/manual/master/#options-input-ipc-server)" 
here's the code that's not working so far:
``` lua
-- dynamically set --input-ipc-server

require 'mp.options'

local char_to_hex = function(c)
  return string.format("%%%02X", string.byte(c))
end

local function urlencode(url)
  if url == nil then
    return
  end
  url = url:gsub("\n", "\r\n")
  url = url:gsub("([^%w ])", char_to_hex)
  url = url:gsub(" ", "%%20")
  return url
end

local hex_to_char = function(x)
  return string.char(tonumber(x, 16))
end

local urldecode = function(url)
  if url == nil then
    return
  end
  url = url:gsub("+", "%%20")
  url = url:gsub("%%(%x%x)", hex_to_char)
  return url
end

function loaded_handler()
        fn = mp.get_property("path")
        fnu = urlencode(fn)
        os.execute("echo '" .. fnu  .. "'")
        os.execute("notify-send '" .. fnu  .. "'")
        spath = "/tmp/" .. fnu
        local options = {
            ["--input-ipc-server"] = spath
        }
        read_options(options, "test")
        print(options["--input-ipc-server"])
end

mp.register_event("file-loaded", loaded_handler)
--mp.register_event("shutdown", shutdown_enable)

```

**Comment by wis** [comment]
I've created a [plugin](https://github.com/wis/mpvSockets) for creating a socket for each instance, no mpv wrapping needed.
it took me too much time reading the docs only not to find what I was looking and then reading other plugins' to find out that [`mp.set_property("options/<property-name>", "val")`](https://mpv.io/manual/stable/#lua-scripting-mp-set-property(name,-value)) can add options/arguments not passed in.

**Comment by wis** [comment]
I've created a [plugin](https://github.com/wis/mpvSockets) for creating a socket for each instance, no mpv wrapping needed.
it took me too much time reading the docs only not to find what I was looking and then reading other plugins' to find out that [`mp.set_property("options/<property-name>", "val")`](https://mpv.io/manual/stable/#lua-scripting-mp-set-property(name,-value)) can add options/arguments not passed in.
