### ISSUE TITLE
window resized to fullscreen if geometry is over a specific window size

### ISSUE THREAD

**Issue by lionep** [mpv-player/mpv#6582]
### mpv version and platform

Platform is Intel NUC8i3 on ubuntu 18.04 with gdm3, with an UHD display.
mpv version 2:0.29.1+git4~bionic4
also reproduced with mpv 0.27.2

### Reproduction steps

```
mpv --geometry=3800x2100+0+0 --no-border full_hd_video.mp4
```

### Expected behavior

The video should be rendered in a rectangle 3800x2100 in the top left corner of the desktop.

### Actual behavior

The video is resized to fullscreen.

### Log file

https://0x0.st/zK2v.txt

**Comment by zc62** [comment]
Probably you should test with `--no-config`. A log with current git master, or at least 0.29.1 release will be helpful, not the 0.27.2 one.

**Comment by lionep** [comment]
Sorry for the bad logs, here is the one with `--no-config` and version 0.29.1 https://0x0.st/zK9w.log  
I have the same behavior.

**Comment by zc62** [comment]
```
[   0.106][v][vo/gpu] Resize: 3200x2100
[   0.222][v][vo/gpu] Resize: 3840x2132
```
Resize appeared twice. I suspect this is a compositor bug or driver bug. Just tried with `x11egl`, on a 2560x1440 screen, `geometry=2500x1400+0+0` works as expected on my end.

**Comment by lionep** [comment]
Okay, it seems to be a compositor bug, not reproduced with xfwm4

**Comment by lionep** [comment]
I found the reason : it's due to mutter with default parameter `auto-maximize` set to `true`.

To solve the issue : 
```
gsettings set org.gnome.mutter auto-maximize false
```
