### ISSUE TITLE
unlike mpv, libmpv requires hwdec=vaapi-copy

### ISSUE THREAD

**Issue by kupiqu** [mpv-player/mpv#6584]
### mpv version and platform

mpv 0.29.1
KDE neon 18.04
Intel graphics

### Reproduction steps

1. I configured mpv.conf as follows:
```
vo=gpu
hwdec=vaapi
```
2. mpv and smplayer using these options work fine (hardware acceleration)
3. dragon player using phonon-mpv (via libmpv) fails to benefit from hardware acceleration.
4. I need to use instead `hwdec=vaapi-copy` to enable hardware acceleration (but I think it's less efficient, isn't it?)

### Expected behavior

I should be able to set `hwdec=vaapi` in libmpv, or am I missing sth?

### Actual behavior

To workaround the issue for now I use mpv.conf:
```
vo=gpu
hwdec=auto
```

**Comment by mc4man** [comment]
As gnome-mpv uses vaapi via libmpv it sounds like your issue is with phonon-mpv

**Comment by kupiqu** [comment]
> As gnome-mpv uses vaapi via libmpv it sounds like your issue is with phonon-mpv

I guess I can check it out myself in gnome-mpv to confirm it uses vaapi instead of vaapi-copy...

**Comment by mc4man** [comment]
This suggests it should work if enabled in  ~/.config/Phonon/mpv.conf
https://github.com/OpenProgger/phonon-mpv/commit/172feb02685092c620a7372ad6a6b20f97c13510

**Comment by kupiqu** [comment]
Well, that's exactly what I use, but it doesn't work as expected, only the
copy one is recognized

**Comment by kupiqu** [comment]
> As gnome-mpv uses vaapi via libmpv it sounds like your issue is with phonon-mpv

I confirm this is working as expected. I'll mention this to the dev of phonon-mpv. Thank you!
