### ISSUE TITLE
Desktop visible in fullscreen if window was pinned

### ISSUE THREAD

**Issue by Keith94** [mpv-player/mpv#6585]
### mpv version and platform

mpv-x86_64-20190324-git-fcb320f
Windows 10  version 1809 (OS build 17763.316)

### Reproduction steps

1. Open a video in mpv
2. Pin the mpv window to side of monitor by dragging
3. Go fullscreen

### Expected behavior
mpv window should cover entire screen

### Actual behavior
Desktop is still visible behind the window (top, left, and right) because its dimensions are reduced. Sometimes the taskbar is on top of the window, too

### Log file

https://pastebin.com/8qSeuJLR

### Other

Bug reproduced: https://i.imgur.com/jxRyXYB.gifv

**Comment by zc62** [comment]
Cannot reproduce with either win10 1803 or win7, same build. See if others can reproduce this with win10 1809 or 1903.

**Comment by 44vince44** [comment]
Could not reproduce either, here on win10 1809

**Comment by Doofussy2** [comment]
I can reproduce this. My taskbar remains on top, and I see the desktop on left and right. Win 10 1809

**Comment by Keith94** [comment]
Can't reproduce anymore.
