### ISSUE TITLE
Fullscreen mode doesnt work in Wayland in Ubuntu 18.10

### ISSUE THREAD

**Issue by kentherzz** [mpv-player/mpv#6591]
When using Wayland and enabling fractional display scaling (125%) MPV does not behave properly. When entering full screen, it goes back to windowed mode when navigating the playlist. It does not stay fullscreen. Disabling fractional scaling solves the problem.

**Comment by mc4man** [comment]
Useless issue post, you ignored template completely
Additionally wayland fractional scaling in Gnome just recently landed in 19.04-dev so unlikely it's in 18.10 officially, you fail to mention how you're doing..

**Comment by Akemi** [comment]
if this issue still persist please open anew one with the issue templated filled out.
