### ISSUE TITLE
DIsplay OSC when Paused

### ISSUE THREAD

**Issue by SPDurkee** [mpv-player/mpv#6592]
Is there anyway to have the OSC show when pausing?
Maybe through scripting?

**Comment by Akemi** [comment]
yes, something along [these](https://github.com/mpv-player/mpv/issues/4896#issuecomment-330458533) lines. observe the pause property, and the set osc-visibility to either always or auto.

**Comment by SPDurkee** [comment]
For reference if anyone finds this in a search. I adding the following script in a osc-custom-pause.lua script file located at ~/.config/mpv/scripts

**Comment by TheBestPessimist** [comment]
I have an updated version of @SPDurkee's script, where the messages `OSC visibility: always/auto` are not displayed:


```lua
-- from https://github.com/mpv-player/mpv/issues/6592#issuecomment-488269456
function on_pause_show_osc(name, value)
    if value == true then
        mp.command("no-osd set osd-level 0; script-message osc-visibility always")
        reset_osd()
    else
        mp.command("no-osd set osd-level 0; script-message osc-visibility auto")
        reset_osd()
    end
end

-- For some reason `set osd-level 0; script-message osc-visibility always; no-osd set osd-level 1` does not work.
-- The OSC messages `OSC visibility: always/auto` are still displayed.
-- It's as if `no-osd set osd-level 1` runs before `script-message osc-visibility always` is run/displayed.`¯\_(ツ)_/¯`
-- As a workaround, I have to make the osd visible after a 1 second timeout.
-- Why? No idea. Bugs?`¯\_(ツ)_/¯`
function reset_osd()
    mp.add_timeout(1,
        function()
            mp.command("no-osd set osd-level 1")
        end
    )
end

mp.observe_property("pause", "bool", on_pause_show_osc)

```

**Comment by ppw0** [comment]
> I have an updated version of @SPDurkee's script, where the messages `OSC visibility: always/auto` are not displayed:
> 
> ```lua
> -- from https://github.com/mpv-player/mpv/issues/6592#issuecomment-488269456
> function on_pause_show_osc(name, value)
>     if value == true then
>         delayed(0, "no-osd set osd-level 0")
>         delayed(0.1, "script-message osc-visibility always")
>         delayed(0.3, "no-osd set osd-level 1")
>     else
>         delayed(0, "no-osd set osd-level 0")
>         delayed(0.1, "script-message osc-visibility auto")
>         delayed(0.3, "no-osd set osd-level 1")
>     end
> end
> 
> -- For some reason `set osd-level 0; script-message osc-visibility always; no-osd set osd-level 1` does not work.
> -- The OSC messages `OSC visibility: always/auto` are still displayed.
> -- It's as if `no-osd set osd-level 1` runs before `script-message osc-visibility always` is run/displayed.`¯\_(ツ)_/¯`
> -- As a workaround, I have to run all the commands with an increasing delay.
> -- Why? No idea. Bugs?`¯\_(ツ)_/¯`
> function delayed(t, c)
>    mp.add_timeout(t, function() mp.command(c) end)
> end
> 
> mp.observe_property("pause", "bool", on_pause_show_osc)
> ```

Hi there, thanks for this script, but unfortunately, frame stepping still causes the OSD to popup with messages about OSC visibility. Any way to alleviate that?

**Comment by TheBestPessimist** [comment]
How do you repro that?  maybe i missed something. The script, as above,  works for me with mpv.net.

**Comment by ppw0** [comment]
> How do you repro that? maybe i missed something. The script, as above, works for me with mpv.net.

1. pause the video.
2. frame step (usually by holding ".").
3. see the visibility message popping up, shifting between 'always' and 'auto'.

**Comment by TheBestPessimist** [comment]
@ppw0, sorry, i cannot reproduce it. For me it works as expected: when the video is paused, the OSC is displayed and i can tap or hold `.` without a problem. The message never appeared.

**Comment by ppw0** [comment]
> @ppw0, sorry, i cannot reproduce it. For me it works as expected: when the video is paused, the OSC is displayed and i can tap or hold `.` without a problem. The message never appeared. Could it be that you have other settings which conflict with this?

That's entirely possible, but I don't how to diagnose that. Maybe it's related to this other script that's active, show_osc_on_seek.lua?

`local function show_osc_helper()
  if show_osc == nil then
    require "@osc.lua"
  end
  show_osc()
end

if mp.get_property_bool("osc") then
  mp.register_event("start-file", show_osc_helper)
  mp.register_event("seek", show_osc_helper)
  mp.observe_property("pause", "bool", function(name, enabled) if enabled then show_osc_helper() end end)
end
`

**Comment by ppw0** [comment]
Just to note - I've solved this by rewriting the script to

```
function on_pause_show_osc(name, value)
	if value == true then
		mp.commandv('script-message','osc-visibility','always','no-osd')
	else
		mp.commandv('script-message','osc-visibility','auto','no-osd')
	end
end

mp.observe_property("pause", "bool", on_pause_show_osc)
```

**Comment by TheBestPessimist** [comment]
@ppw0 the version just above does not work for me at all (at least in mpv.net).
