### ISSUE TITLE
Flash back in Macos

### ISSUE THREAD

**Issue by jiaojiaozhimi4** [mpv-player/mpv#6594]
### mpv version and platform
mpv 0.29.1  MACOS Mojave

### Reproduction steps
1. set all .flv open with MPV
2. double-click the .flv file in Finder

### Expected behavior
the mpv should be opened 

### Actual behavior
the mpv appear in Dock but flash back at once

**Comment by jiaojiaozhimi4** [comment]
but if I open MPV first and pull the file into mpv, it will be work.

**Comment by Akemi** [comment]
no log, no test file.
