### ISSUE TITLE
loop a-b loops only once and stops, when audio is spdif (windows)

### ISSUE THREAD

**Issue by 44vince44** [mpv-player/mpv#6596]
mpv build mpv-x86_64-20190324-git-fcb320f

win 10 x64

Context of the bug:
- using audio-spdif=ac3,dts in mpv.conf
- playing mkv film with ac3 or dts audio track
- system audio (windows selected audio output) is set to use the spdif output and 
  audio is effectively passed through

Bug description:
When you set loop a-b, the range will loop once then it freezes. and to get out of the frozen position, you need to cancel the loop.

Note that if you don't use spdif-audio passthrough, the loop a-b works perfectly.

This has been tested with several mkv files with ac3 and dts audio tracks.

**Comment by lachs0r** [comment]
Please do not omit the log file.

Also, are you using Windows’ built-in sound drivers or hardware vendor drivers? The latter are almost always buggy, so you could try uninstalling them to see if that fixes your issue.

**Comment by 44vince44** [comment]
I use windows drivers and they get updated (vendor drivers are outdated). I will perform a test with another computer and put the results tomorrow, with the logs.

**Comment by 44vince44** [comment]
Here is the log using spdif-passthrough: 
https://pastebin.com/adUAG7c4
check around line 930 of the log:
[d][cplayer] video EOF (status=5) repeats till line 2957 when I cleared the ab-loop.

Note that looping all the file (L) works perfectly. This problem happens only with ab-loop.

**Comment by 44vince44** [comment]
I performed the same test on 2 additional computers with different set-ups and hardware, and soundcards.
one is Win7 32 and one is Win10x64 as the first test I made. They all give same result. And the log is the same. So it seems there is a problem, that only affects spdif when using ab-loop.

**Comment by wm4** [comment]
Was probably fixed.

**Comment by 44vince44** [comment]
I confirm upon testing that it has been fixed. Thank you!
