### ISSUE TITLE
Occasional loss of audio on resume

### ISSUE THREAD

**Issue by Doofussy2** [mpv-player/mpv#6597]
### mpv version and platform

 mpv 0.29.0-280-gdd83b66652 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sat Mar 16 10:30:45 DST 2019
 ffmpeg library versions:
 libavutil       56.26.100
 libavcodec      58.47.103
 libavformat     58.26.101
 libswscale      5.4.100
 libavfilter     7.48.100
 libswresample   3.4.100
 ffmpeg version: N-45276-g6cfa173303

### Reproduction steps

Often when pausing for a short time and then resuming, there is no audio. It's not every time, but often. Maybe when working in a different window??

### Expected behavior

Audio to resume, correctly

### Actual behavior

Occasional loss of audio/audio device

### Log file

[Portable mpv log.txt](https://github.com/mpv-player/mpv/files/3026205/Portable.mpv.log.txt)

**Comment by qmega** [comment]
Try `--audio-stream-silence`.

**Comment by Doofussy2** [comment]
Thanks. I'll try that.

**Comment by Doofussy2** [comment]
> Try `--audio-stream-silence`.

This does appear to have stopped it happening.

**Comment by qmega** [comment]
This can be closed then, right? This is an A/V receiver over HDMI, as seen in the log, so this is pretty much expected, and exactly why that option exists. Could add something to the FAQ, but I doubt anyone would actually look for it there.

**Comment by Doofussy2** [comment]
Yeah, I'll close it.
