### ISSUE TITLE
mpv fails to go fullscreen

### ISSUE THREAD

**Issue by startas** [mpv-player/mpv#6599]
### mpv version and platform
mpv 0.29.1, manjaro linux, kernel 5.0.5, DE xfce 4.13, gpu nvidia 1080, nvidia driver 418.43.

### Reproduction steps
Double click opened video of press "f" to go fullscreen.

### Expected behavior
mpv goes fullscreen.

### Actual behavior
Sometimes (maybe 1 out of 20-50) times, mpv doesnt actually go fullscreen, but removes the mpv window border, and aligns the video with right bottom corner of the screen. So, if the video is 1080p, and my monitor is 1440p, then i see desktop on the left and top sides of the screen.
I also noticed this kind of behaviour only during the last month, so i wonder if mpv is at fault here.

### Log file
https://0x0.st/zPuq.txt
I tried going fullscreen few times, the last time it failed to go fullscreen, look for that.

### Sample files
Any video file. Best to use lower resolution video than desktop resolution, that makes it super easy to spot.

**Comment by lachs0r** [comment]
Sounds like you are dragging the window while double clicking and your window manager is handling the fullscreen hint incorrectly.

**Comment by startas** [comment]
When in failed fullscreen state, mpv doesnt have window borders at all, plus the video is over the taskbar, which is at the bottom on my pc, so it definitely enters broken fullscreen mode. Last version of mpv was released quite some time ago, and i noticed this bug only during last month or so, thats why i said that it could be something else.

**Comment by lachs0r** [comment]
Well, your WM claims to support the fullscreen hint, and mpv uses that. The spec for that hint says:

> _NET_WM_STATE_FULLSCREEN indicates that the window should fill the entire screen and have no window decorations. Additionally the Window Manager is responsible for restoring the original geometry after a switch from fullscreen back to normal window. For example, a presentation program would use this hint.

Which makes this a WM bug.
