### ISSUE TITLE
Regression: OpenAL surround output is incorrect

### ISSUE THREAD

**Issue by Forcer78** [mpv-player/mpv#6601]
### mpv version and platform

```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1.2
```

Built through Homebrew on macOS 10.12.6, using openal-soft.

I tracked the problem down to commit c59ebbe. Any version before this, such as 9efb027 or v0.28.2, does not exhibit this issue.

### Reproduction steps

Play a surround-sound file with `--ao=openal`, preferably using headphones.

### Expected behavior

The audio output is spatialized to virtual speakers and includes the LFE channel.

### Actual behavior

The output is indistinguishable from the default stereo `ao` driver: Front Left and Left Surround channels are squashed to undistinguished Left (ditto the Right channels), and LFE is entirely absent.

### Log file

v0.29.1 (no spatialization): https://0x0.st/zPtw.txt
v0.28.x (expected output): https://0x0.st/zPtv.txt

### Sample files

https://www2.iis.fraunhofer.de/AAC/ChID-BLITS-EBU.mp4

**Comment by Akemi** [comment]
we removed the openal support on macOS, after 0.29.1 and it should fallback to openal soft now. try with master instead.

see #4645 and #6074.

**Comment by Forcer78** [comment]
I filed the initial report that those issues reference (https://github.com/mpv-player/mpv/issues/3763). I'm aware of the deficiencies in macOS's native OpenAL, and have been patching it out of my mpv builds in favor of openal-soft since 2016. It's good that master has followed suit, but that issue is unrelated to this one: the series of commits that broke OpenAL predated the v0.29.0 release, and so also the v0.29.1 removal (which didn't affect me).

**Comment by Forcer78** [comment]
To reiterate: the mentioned removal of native OpenAL has nothing to do with this issue.

**Comment by wm4** [comment]
My standpoint is that you shouldn't use OpenAL. If you insist on using it, make a PR to fix it.

**Comment by LAGonauta** [comment]
Next time you can ping me ;)
I got back to reading the repository because of d27ad9654218463694093697e3d09f8983b4ccf3 that broke OpenAL (just updated my local mpv build to newest commit)

Was `direct_channels` set to true or false on your tests? I need to update it to use this newer OpenAL Soft extension: https://openal-soft.org/openal-extensions/SOFT_direct_channels_remix.txt
