### ISSUE TITLE
How can I disable "maxmize" effect?

### ISSUE THREAD

**Issue by CaledoniaProject** [mpv-player/mpv#6603]
### mpv version and platform

MacOS, binary release v0.29.1

### Problem

When I press `F` the mpv window maxmized with a transition effect, how can I disable it?

**Comment by CounterPillow** [comment]
Ask Apple.

**Comment by zc62** [comment]
https://apple.stackexchange.com/a/293926

**Comment by Akemi** [comment]
there is `--macos-fs-animation-duration` and `--native-fs`.
