### ISSUE TITLE
duplicated monitor fullscreen not working

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#6604]
### mpv version and platform

build from 2019-03-24

### Reproduction steps

1. Windows 10
2. NVIDIA GT 1030 card
3. dual monitor with duplicate mode
4 vo=gpu

now the second screen (LG UHD TV) is broken, out of proportion and green, it's happening only in fullscreen mode, with vo=direct3d it's fine, when I disable the primary screen (LG UHD monitor) it's still not working. When I extend the screen instead of duplicate it, it works fine. I've also tried to make the TV the primary screen but the issue is still always on the TV and never on the monitor.

log file: https://pastebin.com/Cj8PfKWP

I've also tried disabling hwdec but didn't help.

**Comment by zc62** [comment]
> when I disable the primary screen (LG UHD monitor) it's still not working.

Do you mean even if only the TV is connected (thus no such thing as duplicate or extend), fullscreen still does not work? If the monitor is still connected to the video card and you just turned it off, I'm afraid that is not going to make any difference. Test when only the TV is connected.

I can hardly imagine this being a mpv issue. Currently mpv does not even have exclusive fullscreen, which may cause issues. You can try some other d3d11 programs in fullscreen windowed mode.

**Comment by stax76** [comment]
The issue is only when the monitor is turned off, when the monitor is disconnected then it's fine. I figured that using extended mode instead of duplicating don't have a disadvantage for me so from now on I use extended mode.

Extended mode is more comfortable with:

screen = 1
fullscreen = yes

This doesn't work in mpv, in my mpv.net it's fine, took me some time to implement, the primary display has negative coordinates! It probably doesn't help but here is my implementation:

https://github.com/stax76/mpv.net/blob/master/mpv.net/MainForm.cs#L50

**Comment by zc62** [comment]
libmpv uses opengl only. And MPC, which uses EVR by default, does not necessarily use d3d11. My guess is this could be a driver bug or MS bug related to d3d11, so it would be nice to see if other d3d11 programs works for you or not to narrow down the source of the bug.

**Comment by stax76** [comment]
I don't know any d3d11 apps. Today I started a video before turning on my TV so it started on the desktop, after the TV was on I dragged it from the desktop to the TV and there was the issue again. When the TV is on before the player is started the player will start directly on the TV screen and there is no issue.

**Comment by zc62** [comment]
Since you have used MPC, you could try madVR with d3d11 enabled. (Remember to disable exclusive fullscreen to get the same fullscreen windowed behavior as mpv.)

**Comment by stax76** [comment]
Same issue with madVR.

With gpu-context = angle it's fine, is angle a good choice quality and feature wise?

**Comment by zc62** [comment]
Then this is not a mpv issue. Most likely broken OS or driver. Did you update your driver? What's the OS version? 1903?

`angle` is an opengl backend, which I believe does not have as good performance as d3d11. You can use it, though. The image quality won't be affected, and it should support shaders as well. You may also try `gpu-api=vulkan`, before MS or NVIDIA fixes the bug.

**Comment by stax76** [comment]
I updated my OS driver not longer than 3 weeks ago because Firefox is broken on my system, tab switching takes 2-3 seconds, my CPU is an old i3-3220, I migrated to Chrome because of it.

gpu-api=vulkan uses 100% 3D in task manager, with gpu-context=angle it's 70% and without 50%.

I'll report this to NVIDIA.

**Comment by stax76** [comment]
It seems to be fixed since I updated to Win 10 1903.
