### ISSUE TITLE
Invalid audio PTS: -1.245312 -> -1.125313 when playing Opus test vectors

### ISSUE THREAD

**Issue by calestyo** [mpv-player/mpv#6606]
$ mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100 (runtime 56.22.100)
   libavcodec      58.18.100 (runtime 58.35.100)
   libavformat     58.12.100 (runtime 58.20.100)
   libswscale      5.1.100 (runtime 5.3.100)
   libavfilter     7.16.100 (runtime 7.40.101)
   libswresample   3.1.100 (runtime 3.3.100)
ffmpeg version: 4.1.1-1

Debian sid

Just a notice about the following. When playing back the Opus test vector files from https://people.xiph.org/~greg/opus_testvectors/ I get the following:
```
$ mpv correctness_trimming_nobeeps.opus
Playing: correctness_trimming_nobeeps.opus
 (+) Audio --aid=1 (opus 1ch 48000Hz)
Invalid audio PTS: -1.245312 -> -1.125313
Invalid audio PTS: -1.125313 -> -1.005313
Invalid audio PTS: -1.005313 -> -0.885313
Invalid audio PTS: -0.885313 -> -0.765312
Invalid audio PTS: -0.765312 -> -0.645312
Invalid audio PTS: -0.645312 -> -0.525312
Invalid audio PTS: -0.525312 -> -0.405312
Invalid audio PTS: -0.405312 -> -0.285312
Invalid audio PTS: -0.285312 -> -0.165312
Invalid audio PTS: -0.165312 -> -0.045313
AO: [pulse] 48000Hz mono 1ch float
A: 00:00:11 / 00:00:12 (97%)


Exiting... (End of file)
```

The playback itself seems totally fine and the beeps (listen to the opus file for explanation) are not heard (which is the correct behaviour).

There are just these spurious:
`Invalid audio PTS: -1.245312 -> -1.125313`
messages.

**Comment by zc62** [comment]
These are just warning messages.
https://github.com/mpv-player/mpv/blob/6c913149001b242aa777d6a1e67f62162c1e6694/filters/f_decoder_wrapper.c#L411-L415
What is the reason not to show these warnings?

**Comment by calestyo** [comment]
Nothing... usually a warning just means something is not fully ok... but since playback seemed to be just fine, I wanted to point to the matter, so that the devs can check whether anything needs to be done :)

If you think it's ok, we can close the issue from my side.

**Comment by wm4** [comment]
I don't get any messages in mpv git master.

**Comment by fidodido48** [comment]
Ive had just the exact same issue yesterday with a video file and it caused a high-cpu usage which was making playback laggy and finally mpv gave up freezing video completely (only rewinding back/forth or restarting mpv fixed it for a while until it froze again). Tried to re-enc. the file w/ ffmpeg using many diff. opts (+genpts+ignoredts, -af 'resample=async=1,startpts=STARTPTS using aac/mp2 codecs and such...) to fix it, but couldnt get rid of this issue.
