### ISSUE TITLE
ASS stop getting resized after cycling through sub-ass-override.

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#6607]
### mpv version and platform
mpv 0.29.1
Linux 5.0.5-arch1-1-ARCH x86_64

### Reproduction steps
Any video with stylized (ASS) subtitles.
Switching back and forth value of `sub-ass-override` - default 'u' key.
Resizing subtitles with `x add sub-scale +0.01` / `z add sub-scale -0.01`

### Expected behavior
Stylized subtitles to be resizable.

### Actual behavior
Stylized subtitles stop getting resized after switching back to not overridden value. Overridden are still resized without any issue.
To be able to resize ASS again only restarting the player helps. Even going forth through playlist Stylized subtitles' resizing is still non-responsive.

**Comment by zc62** [comment]
Because the default values is `yes`, while `force` and `no` are cycled.

**Comment by oltodosel** [comment]
Thanks. Added to _input.conf_
`u cycle-values sub-ass-override yes force`
