### ISSUE TITLE
Crash with lavfi-complex on some files

### ISSUE THREAD

**Issue by Forcer78** [mpv-player/mpv#6608]
### mpv version and platform

```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1.2
```

This is FFmpeg, since it is used below:
```
ffmpeg version 4.1.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
```

Both built through Homebrew on macOS 10.12.6.

### Reproduction steps

Unpack the attached sample archive and run the included script:
```
cd sample
sh script.sh
```

The script runs the exact same simple `--lavfi-complex` filter in both FFmpeg and mpv on two files, pass.mp3 and fail.mp3.

Both pass.mp3 and fail.mp3 are CBR 320kbps MP3s with embedded cover art. Every track from their respective albums follows their examples in behavior. `--af=lavfi` has not crashed in this manner so far.

### Expected behavior

FFmpeg converts the files and mpv plays them with the filter applied.

### Actual behavior

FFmpeg successfully converts both files.
mpv filters and plays pass.mp3, but crashes with a segfault on fail.mp3.

### Log file

Log file for fail.mp3: https://0x0.st/zP5A.txt
Crash log for fail.mp3: http://0x0.st/zP5j.txt

### Sample files

http://0x0.st/zP5M.zip

This zip contains pass.mp3, fail.mp3, and script.sh.

**Comment by Forcer78** [comment]
This may or may not be related to https://github.com/mpv-player/mpv/issues/5732: that issue is claimed not to crash on v0.27.0, but my issue does. The FFmpeg version is different, of course.

**Comment by AxelTerizaki** [comment]
I just noticed this issue since mine has bee nclosed just now. 

I recently downloaded a nightly version of mpv for Windows and the issue does not seem to be present anymore. Have you tested with a nightly build?

**Comment by Akemi** [comment]
if it still persists i will reopen this one.

**Comment by Forcer78** [comment]
I just tested with the latest build from https://laboratory.stolendata.net/~djinn/mpv_osx/ (2019-Nov-03 22:44, mpv-0.30.0) and it immediately segfaulted on the fail.mp3 sample file.

Were the sample files I uploaded not tested once in 7 months?

**Comment by Akemi** [comment]
would you mind opening a new issue? it might be beneficial to push it up and have someone to look at it again.
