### ISSUE TITLE
I want .cue navigation on Android

### ISSUE THREAD

**Issue by michael466722** [mpv-player/mpv#6613]

**Comment by felipe19930** [comment]
I want to be rich

**Comment by Hrxn** [comment]
MeToo

**Comment by michael466722** [comment]
And I want navigation between files in folder when one file opened.

**Comment by michael466722** [comment]
If the work is divided into files only they should be in folder and they should be connected in viewer by folder.

**Comment by zc62** [comment]
If you mean mpv-android, then probably you should ask here: https://github.com/mpv-android/mpv-android

(TBH no matter how you edited your comment, I still could not understand it at all. Be more specific, do not ignore the issue template, what's the software version you are using, where you got it, what's the current behavior, better with a screenshot to illustrate, what's the feature you think is good to be implemented, and what's the relationship between ".cue navigation" in your title and "linearly connected, etc." in your comment....)

**Comment by michael466722** [comment]
This is for Android. I get here through mpv.io: Want a feature? Post a patch or request it! I think in player should be buttons to switch on adjacent files and player should switch to the next file when current ends.
