### ISSUE TITLE
MPV Mac Builds Fail Following Apr 1st Commits

### ISSUE THREAD

**Issue by classicjazz** [mpv-player/mpv#6614]
I haven't had an issue with + brew install mpv --HEAD mpv
until the April 1st commits. Now they consistently fail. 

See:

`+ brew install mpv --HEAD mpv
==> Cloning https://github.com/mpv-player/mpv.git
Updating /Users/mike/Library/Caches/Homebrew/mpv--git
From https://github.com/mpv-player/mpv
   6c91314900..e9fae413fd  master     -> origin/master
==> Checking out branch master
Already on 'master'
Your branch is behind 'origin/master' by 3 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at e9fae413fd options/path: fix url detection per RFC3986
==> ./bootstrap.py
==> python3 waf configure --prefix=/usr/local/Cellar/mpv/HEAD-e9fae41_3 --enable
==> python3 waf install
Last 15 lines from /Users/mike/Library/Logs/Homebrew/mpv/03.python3:
/private/tmp/mpv-20190405-84728-18mdp1m/video/out/cocoa_cb_common.swift:256:29: warning: 'init(_:)' is deprecated: replaced by 'init(truncating:)'
        let lux = Int(ceil( Double((term4 + term3 + term2 + term1 - 0.19) as NSNumber)))
                            ^
/private/tmp/mpv-20190405-84728-18mdp1m/video/out/cocoa_cb_common.swift:256:29: note: use 'init(truncating:)' instead
        let lux = Int(ceil( Double((term4 + term3 + term2 + term1 - 0.19) as NSNumber)))
                            ^
                                   truncating: 
/private/tmp/mpv-20190405-84728-18mdp1m/video/out/cocoa_cb_common.swift:335:39: error: cannot call value of non-function type '[NSScreen]'
        let screens = NSScreen.screens()
                      ~~~~~~~~~~~~~~~~^~
                                      

Waf: Leaving directory `/private/tmp/mpv-20190405-84728-18mdp1m/build'
Build failed
 -> task in 'osdep/macOS_swift.o,osdep/macOS_swift.h,osdep/macOS_swift.swiftmodule' failed with exit status 1 (run with -v to display more information)

`

**Comment by Akemi** [comment]
don't ignore the issue template. most likely, you updated xcode too and with that to swift 5, which removed swift 3 compatibility. you need to downgrade xcode or you command line tools.

see issue #6470 and PR #6612.

**Comment by classicjazz** [comment]
I thought what I posted above was more specific than the issues template.  But, it wasn't clear to me that the issue was Swift 3.

Since the purpose of both homebrew and Apple's Software Update is to push out the latest versions, I would expect this to be an increasing problem for more Mac users. 

I recommend prioritizing committing PR #6612 (if that solves the issue) since mpv is now unusable.
