### ISSUE TITLE
Youtube-dl questions

### ISSUE THREAD

**Issue by fwanky** [mpv-player/mpv#6616]
mpv 0.29.1 Arch Linux
mpv conf; https://0x0.st/zZay.txt
When using youtube-dl to watch a video I only get 30fps playing when I have it in my config to set 60, is mpv not able to stream load 60 fps into mpv?
Another question while i'm here, will is it possible for mpv to just force use the best option if 1080p isn't actually avaliable?

**Comment by CounterPillow** [comment]
>When using youtube-dl to watch a video I only get 30fps playing when I have it in my config to set 60, is mpv not able to stream load 60 fps into mpv?

Is the video you're watching actually 60fps?

>Another question while i'm here, will is it possible for mpv to just force use the best option if 1080p isn't actually avaliable?

That's what your config does with `ytdl-format=bestvideo[height<=?1080][fps<=?60]+bestaudio/best`

**Comment by fwanky** [comment]
Yeah, the video IS 60, which is why i'm super duper confused 

the video's here; https://youtu.be/6mLbwWdOGDA

and as you can see, it's playing at the highest quality, awesome! but 30 and not 60?
https://0x0.st/zZaw.txt

**Comment by CounterPillow** [comment]
Looks to be a youtube-dl bug with `[fps<=?60]`, the 60fps video is selected fine without it. Not an mpv issue at any rate.

**Comment by fwanky** [comment]
Does the same thing happen for you? Just to be sure, should I make an issue on youtube-dl or? what's the best way to go

**Comment by CounterPillow** [comment]
The same thing happens for me with that specific format selector.

Yes, this is something to report to youtube-dl.

**Comment by mc4man** [comment]
You could lose the 'less than' (<) and probably get what you want with that vid and similar. However in some cases there may be unintended results with vids that don't have a 60fps version.
Otherwise you could could specify formats desired on a per vid basis from cli, ex.
mpv --ytdl-format=298+140 https://youtu.be/6mLbwWdOGDA
