### ISSUE TITLE
mpv fails with video-sync=display-resample and PNG images with data appended to end

### ISSUE THREAD

**Issue by z0z0z** [mpv-player/mpv#6618]
- Linux x86_64 
- mpv 1:0.29.1-5 (Arch repo)

I have a very strange bug for you. 

### Reproduction steps
Set `video-sync=display-resample` and open a PNG file with data appended to the end of it.

Can do something like this `echo $RANDOM >> image.png`

### Expected behavior
Image still displays

### Actual behavior
It don't. mpv doesn't open a window and stays running forever.

### Log file
[mpv-log.txt](https://github.com/mpv-player/mpv/files/3051234/mpv-log.txt)

 ffplay, `magick display`, firefox, GIMP, and feh, can all still open and display these PNG files. 

mpv also used to be able to display these PNG files, even with `video-sync=display-resample`.

It's not the biggest problem, but it is a strange one. People do in fact do stuff like this to image files to change MD5 hashes and I've found these images online.

I ran into this because I use mpv as my image viewer, and display-resample happened to be enabled in my global mpv configuration.

**Comment by zc62** [comment]
Put in your `mpv.conf`
```
[extension.png]
video-sync=audio
```
