### ISSUE TITLE
Pixel Shader from MPC-HC, how to use it to convert in glsl?

### ISSUE THREAD

**Issue by orator89** [mpv-player/mpv#6622]
Hi, I have this shader code (.hlsl) from  a shader in MPC-HC and want to use it in MPV, the code is:

```
sampler s0 : register(s0);

#define const_1 ( 16.0 / 255.0)
#define const_2 (255.0 / 219.0)

float4 main(float2 tex : TEXCOORD0) : COLOR
{
	// original pixel
	float4 c0 = tex2D(s0, tex);

	return ((c0 - const_1) * const_2);
}
```

is there any chance to translate in .glsl/.hook for command: 

`glsl-shaders-append==.....`

?

Thanks in advance

**Comment by paulguy** [comment]
I imagine you'd just have to rewrite it, at least for something simple like that.  For more complex stuff I think there are programs which will try to translate them (as something like Wine would try to do) but probably better to just port them over.

**Comment by wm4** [comment]
You can probably pay @haasn to do it?

**Comment by haasn** [comment]
Try `--vf=format:colorlevels=limited`.

Your shader appears to be fixing a problem that shouldn't be present to begin with, i.e. TV/PC range mismatch.

**Comment by Akemi** [comment]
https://github.com/mpv-player/mpv/issues/6094#issuecomment-417704852
i think i ported "full -> limited (reduces range)" and "limited -> full (expands range)" shaders here before.
