### ISSUE TITLE
[Question] Is it able to output YCbCr444 format directly instead of RGB format?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#6626]
I was trying to ask question on the irc channel, and it kept showing me that it was SASL access only, so here is the only place to ask my question.
### mpv version and platform
```
mpv 0.29.0-303-g8b114e574a Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Apr  5 22:09:49 CST 2019
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.2
```
### Expected behavior
To output YCbCr444 instead of converting to RGB.
AMDGPU outputs the YCbCr format via HDMI by default, I was able to force it to output RGB format by editing the EDID profile with wxEDID, but it doesn't work anymore on my new monitor.

**Comment by lachs0r** [comment]
Well this is terrible. What appears to be the offending code: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm.c?id=dc4060a5dc2557e6b5aa813bf5b73677299d62d2#n2767

So a proper fix is planned, apparently. In the meantime you can modify your distro’s kernel package with a patch to remove this code (lines 2768 to 2774).
