### ISSUE TITLE
[vapoursynth] poor performance with 4K+

### ISSUE THREAD

**Issue by chainikdn** [mpv-player/mpv#6627]
mpv copies every input frame into the vapoursynth context and then copies every output frame back. The problem is copying is **single-threaded**. 
Considering 4K+10bit 24 fps input, motion interpolated into 4K+10bit 60 fps output, the performance of single-threaded copying is just not enough even on the top-end CPUs.
Please see #6262.

**Comment by Akemi** [comment]
we saw your ping on the PR itself the first time.
