### ISSUE TITLE
screenshot-template wrong behaviour 

### ISSUE THREAD

**Issue by OrangePy** [mpv-player/mpv#6628]
### Reproduction steps
Take a screenshot
I have this template: "screenshot-template=mpvsnap-%n". Which is basically the standard except for the initial string. I have also changed the default folder.
### Expected behaviour
A screenshot with a number greater than the ones in the folder.
### Actual behaviour
The "%n" is supposed to give me a greater number every time I take a screenshot, but it does not. If I delete some snaps whit smaller numbers, newer screenshots will fill the gaps before.
The manual explicitly states to use the optional sign '#' to have this behavior (which I don't want) so I guess this is a sort of bug.
### Log file
https://0x0.st/zNNn.txt
### Sample files
Just any file really

I can get around it ordering the folder by Date Added. I just thought there might be someone who would want this kind of thing.

**Comment by Akemi** [comment]
briefly tested this and it only happens when restarting the player for me. while playing back in the same instance it doesn't fill the gaps.

**Comment by wm4** [comment]
Not a bug. Saving this state would increase complexity (currently the player doesn't save _any_ state, which is actually a feature). You could write a script that saves screenshots using some persistent number stored somewhere else and the `screenshot-to-file` command.
