### ISSUE TITLE
--keep-open is ignored when a srt file is on the playlist.

### ISSUE THREAD

**Issue by Blast-City** [mpv-player/mpv#6630]
### mpv version and platform
0.27.2-1ubuntu1
Ubuntu Bionic (18.04) repository.
### Reproduction steps
"folder_1" contains the files "video.mkv" and "video.srt".

1- `mpv --no-config --keep-open folder_1/`
### Expected behaviour
mpv should not add the srt file to the playlist and not exit when the file ends.
### Actual behaviour
mpv exits because the srt file causes the player to return an error: "No video or audio streams selected." (exit code 3).

**Comment by zc62** [comment]
https://mpv.io/manual/master/#options-keep-open

> Also, if errors or unusual circumstances happen, the player can quit anyway.

This is somewhat expected. Probably an additional option is needed to ignore errors.

**Comment by Akemi** [comment]
for ignoring error one could just use `--idle`. otherwise your actual behaviour is expected, as per docs. for not adding srt files to the playlist, it's your responsibility to pass mpv what you want to play. in you case the whole folder is played.

you could either pre filter what you was to mpv via find(?), or write a script that removes unwanted files from your playlist.

**Comment by Blast-City** [comment]
> for ignoring error one could just use `--idle`. otherwise your actual behaviour is expected, as per docs. for not adding srt files to the playlist, it's your responsibility to pass mpv what you want to play. in you case the whole folder is played.
> 
> you could either pre filter what you was to mpv via find(?), or write a script that removes unwanted files from your playlist.

Hi.

The option --idle still quits the last file, but makes the mpv player stay open on the "drop files to play here" image.

The problem is with folders that have a lot of files with different formats (mkv, mp4, avi, etc...). It's much easier to just drop the folder on mpv. Maybe an option to only add to the playlist files that mpv can play.
The zc62 could also work.

I understand, though.

Thanks.

**Comment by Akemi** [comment]
obviously it doesn't play the last file because it can't play an srt file, but at least the player stays open.
mpv doesn't know beforehand which files it can play, it has to open them.

like i mentioned a script would be the easiest way, but guess what someone already [did that work](https://github.com/occivink/mpv-scripts#blacklist-extensionslua).

a file extension whitelist/blacklist could be added to mpv itself, though i believe it was proposed before and rejected.

**Comment by Blast-City** [comment]
> obviously it doesn't play the last file because it can't play an srt file, but at least the player stays open.
> mpv doesn't know beforehand which files it can play, it has to open them.
> 
> like i mentioned a script would be the easiest way, but guess what someone already [did that work](https://github.com/occivink/mpv-scripts#blacklist-extensionslua).
> 
> a file extension whitelist/blacklist could be added to mpv itself, though i believe it was proposed before and rejected.

Thanks for the link.

That script seems to do what i want, but unfortunately I can't make it work.

I've put the file blacklist-extensions.lua inside mpv/scripts/ and blacklist_extensions.conf inside mpv/script-opts/ and run mpv, but it continues to add srt files to the playlist. Is there something that I'm missing?

Thanks.

**Comment by Akemi** [comment]
for starters update your mpv, it's ancient (over 1 1/2 years old). but really how can anyone tell without any kind of information? look at the log.

**Comment by Blast-City** [comment]
> for starters update your mpv, it's ancient (over 1 1/2 years old). but really how can anyone tell without any kind of information? look at the log.
> 
> [edit]
> i tested it and it works.

Thanks. I found out what was happening.

If anyone finds this issue this is how it works on the 0.27.2 version:

1- Create two folders:
/home/user/.config/mpv/scripts/
/home/user/.config/mpv/lua-settings/

2- Inside the scripts/ folder create a file called blacklist-extensions.lua with the following content:
https://raw.githubusercontent.com/occivink/mpv-scripts/master/scripts/blacklist-extensions.lua

3- Inside the lua-settings create a file called blacklist_extensions.conf with the following content:
https://raw.githubusercontent.com/occivink/mpv-scripts/master/script-opts/blacklist_extensions.conf
