### ISSUE TITLE
Doubletap with visible cursor always ignored

### ISSUE THREAD

**Issue by tserhii-gh** [mpv-player/mpv#6633]
### mpv version and platform
mpv: `0.29.1`
OS: `Archlinux`
libinput: `1.13.1`

### Reproduction steps
0. Open video file
1. Doubletap with touchpad to enter fullscreen while cursor is visible
2. Doubletap with touchpad to enter fullscreen while cursor is invisible

### Expected behavior
Enter fullscreen mode independently of cursor visibility

### Actual behavior
Doubletap with visible cursor always ignored on libinput >1.12.6

### Log file
[logfile.txt](https://0x0.st/zNeT.txt)

### Sample files

Any video file

**Comment by Dosprogs** [comment]
Works fine for me on the same config with a mouse. This might only apply to touchpads.

**Comment by uzvermode** [comment]
Only touchpad issue, my wired and wireless mouse are working just perfect.

**Comment by JonAziz1** [comment]
Any update on this issue anyone got a solution?

**Comment by uzvermode** [comment]
No solution so far(

**Comment by glaubersm** [comment]
Same problm with mpv 0.29.1 on Arch Linux + Gnome 3.32.2 Wayland session + libinput 1.14.0.
In fact it's almost the same problem because on my system double-tap to enter/leave full screen mode fails regardless cursor is visible or not.
celluloid player is also affected.
https://github.com/celluloid-player/celluloid/issues/455

**Comment by aufkrawall** [comment]
Could anybody check how the situation is on Windows/Mac?

**Comment by Akemi** [comment]
on mac it works, though i don't know how this is related?

**Comment by aufkrawall** [comment]
I can't judge. However, I could try on a Windows touch display and also here double tap goes horribly wrong: It usually fails to enter fullscreen and instead just hides the window decorations etc.

**Comment by magiblot** [comment]
I'm experiencing something similar to what @aufkrawall describes (mpv fails to enter fullscreen, sometimes it just hides the window decorations), but on Plasma Wayland (not X11) and with mouse click (touchpad tap makes no difference). Should I open a new issue?

**Comment by Dudemanguy** [comment]
>Plasma Wayland (not X11) and with mouse click

Double click works on GNOME wayland so I think this one is a Plasma issue.

**Comment by magiblot** [comment]
> Double click works on GNOME wayland so I think this one is a Plasma issue.

Does mpv have any debug option that might be useful for a Plasma bug report?

**Comment by Dudemanguy** [comment]
It's not an mpv option but using WAYLAND_DEBUG=1 and providing the log from that would probably be appreciated.

**Comment by Dudemanguy** [comment]
Did a quick test on plasma (kwin 6.0.5) with master and yeah it works fine.
