### ISSUE TITLE
[Question] Open MPV on the latest video played

### ISSUE THREAD

**Issue by yassinebridi** [mpv-player/mpv#6638]
How can i open the MPV player with the latest video played on it
*I'm sorry if this is not the place to ask such question, feel free to redirect me to the right place.

**Comment by TheAMM** [comment]
mpv doesn't have this sort of functionality built-in. On Windows you can hover over the mpv icon (if it's in your taskbar) to see latest files.

The right place is to ask the community on IRC - https://mpv.io/community/
