### ISSUE TITLE
Opening 4K files is something like 10K on my iMac

### ISSUE THREAD

**Issue by solelylove** [mpv-player/mpv#6641]
Hey there,

My apologies is my question sounds really stupid. But basically, I am having a problem with opening 4K files from my Panasonic GH5 on the MPV player. When I open a 4K file, it is MASSIVE, larger than my 5K screen. I have no idea how or where to make a config file and what it should consist of.

Is there anyone that's able to help me?

**Comment by lachs0r** [comment]
This is because you are likely using a high-DPI display. The default behavior on macOS is to scale the video so that it appears as it would on a low-DPI display. You can disable this behavior using the [`--no-hidpi-window-scale`](https://mpv.io/manual/master/#options-no-hidpi-window-scale) option.

You might also want to check out the [`--autofit-larger`](https://mpv.io/manual/master/#options-autofit-larger) option so you never end up with windows larger than your display.

**Comment by solelylove** [comment]
When I type the -- into my text editor in Mac, it combines them into a single longer -, any idea how to fix this?

**Comment by solelylove** [comment]
<img width="512" alt="Screen Shot 2019-04-16 at 1 10 55 PM" src="https://user-images.githubusercontent.com/48652754/56230013-4c454d00-6049-11e9-9d75-1a5f098a6109.png">
<img width="180" alt="Screen Shot 2019-04-16 at 1 11 26 PM" src="https://user-images.githubusercontent.com/48652754/56230014-4c454d00-6049-11e9-92dd-b222ba97c1be.png">

**Comment by lachs0r** [comment]
That could be just font rendering. You can also omit the leading dashes in mpv.conf; the options will work regardless. Dashes are only required on the command line.

**Comment by solelylove** [comment]
It still hasn't worked, any idea why?

**Comment by Akemi** [comment]
probably because you are doing something wrong, but we can't know without more information. might be because TexEdit saves the files as rtf instead of plain text (hidden extension), you saved the file in the wrong place, your mpv is too old...

not ignoring the issue template would have been beneficial too.

**Comment by solelylove** [comment]
mpv 0.29.1 and the config file is a .conf file, not .rtf.

**Comment by solelylove** [comment]
The file has been saved where the Preferences opens the folder to

**Comment by Akemi** [comment]
then do what the issue template said and make a logfile with `--log-file=PATH`. the binary to call it via the terminal is in ⁨`mpv⁩ ▸ ⁨Contents⁩ ▸ ⁨MacOS⁩ ▸ mpv`.

**Comment by solelylove** [comment]
Copying mpv⁩ ▸ ⁨Contents⁩ ▸ ⁨MacOS⁩ ▸ mpv into my terminal leaves me with command not found

**Comment by solelylove** [comment]
How do I properly call it in terminal?

**Comment by Akemi** [comment]
because it was supposed to be a relative path from your app bundle, eg `PATH/TO/mpv.app/Contents⁩/MacOS⁩/mpv`. since i have no clue about your setup i just guessed you are using an app bundle. if you are mpv is in your PATH you can just call `mpv` normally.

**Comment by solelylove** [comment]
I am a 100% noob to all of this, including terminal. 
Can you spell it out for me what I must do?

**Comment by solelylove** [comment]
ahhhhh, I get it now. I had to navigate to the mpv > contents > macos > mpv and click on it. Alright, I'm there now.

**Comment by solelylove** [comment]
<img width="585" alt="Screen Shot 2019-04-16 at 4 13 16 PM" src="https://user-images.githubusercontent.com/48652754/56240917-94249e00-6062-11e9-9559-8d9f3bdd7ad8.png">

It's stuck on this, it won't let me type --log-file=PATH

**Comment by solelylove** [comment]
<img width="616" alt="Screen Shot 2019-04-16 at 4 14 55 PM" src="https://user-images.githubusercontent.com/48652754/56241022-cb934a80-6062-11e9-8b4e-cbbf6850e3f2.png">

**Comment by Akemi** [comment]
not clicking. just drag'n'drop the mpv binary into the terminal window, so the path of it is in there. then add `--log-file=PATH/TO/DEKSTOP/mpv.log PATH/TO/FILE/movie.mkv`. hit enter, exit mpv and upload the log somewhere for us to look at. it will look similar to this:

![Screenshot 2019-04-16 at 22 18 04](https://user-images.githubusercontent.com/680386/56241194-89cfc780-6095-11e9-9e36-8fc42bce21b7.png)

you can also test `--no-hidpi-window-scale` like that. just add that option to the command line invocation. if it works, something is wrong with your conf file.

**Comment by solelylove** [comment]
<img width="586" alt="Screen Shot 2019-04-16 at 4 36 39 PM" src="https://user-images.githubusercontent.com/48652754/56242241-d69baa00-6065-11e9-9329-5c51dedb71c5.png">
[mpv.log](https://github.com/mpv-player/mpv/files/3086806/mpv.log)

**Comment by solelylove** [comment]
And yes with the --no-hidpi-window-scale placed in terminal with the file, it works perfectly. Something must be wrong with the config file. How do I know what though?

**Comment by Akemi** [comment]
it's says your conf is malformed in the terminal output. first line, "unparseable extra character: 'op'"

**Comment by Akemi** [comment]
seems like you wrote `--no-hidpi-window-scale op` instead of just `--no-hidpi-window-scale`. your screenshot is unreadable in that regard.

**Comment by solelylove** [comment]
Nope, because in the photo I sent I didn't even type the --no-hidpi line, I only did the video file

**Comment by solelylove** [comment]
In a separate instance I did the mpv player with the --no-hidpi and the clip and it worked fine

**Comment by Akemi** [comment]
the error is in your bloody config file like said. like the first bloody screenshot you posted. the one that is so blurry it's basically illegible.
<img width="180" alt="Screen Shot 2019-04-16 at 1 11 26 PM" src="https://user-images.githubusercontent.com/48652754/56230014-4c454d00-6049-11e9-92dd-b222ba97c1be.png">

it' say in bloody red "/Users/slf/.config/mpv/mpv.conf:1: unparseable extra characters: 'op'".

**Comment by solelylove** [comment]
Hey, it works perfectly now! Thanks for the help!
