### ISSUE TITLE
add background image programmatically while playing audio file

### ISSUE THREAD

**Issue by merkle-root** [mpv-player/mpv#6645]
I want to be able to add video (image) tracks from within lua. Ie. Basically, `audio-add` command but for video. Please let me know if this is already possible by other means.

In other words, I want to be able to do this programmatically:

     mpv --external-file album-cover.png --force-window --image-display-duration=inf --vid=1 song.mp3

This plays song.mp3 with the image as as a background. All of these parameters can be set from lua after launch, apart from `--external-file`. I want to be able to add an external video (image) file after launch.

**Comment by zc62** [comment]
Why don't you load the video/image first then `audio-add` the audio file.

**Comment by merkle-root** [comment]
Because the image doesn't exist yet. It get generated by lua once I play the file.

**Comment by merkle-root** [comment]
@zc62 another issue with this solution is that the progress bar wouldn't work, because it's showing progress for the "video" (which is only 1 frame) and not the audio track.

**Comment by zc62** [comment]
I'm not sure if you are saying the lua script will generate different random images each time the audio file is played. If they don't change, just generate them once and attach the images to the audio file, since mpv supports album cover art: https://mpv.io/manual/master/#options-audio-display

**Comment by merkle-root** [comment]
Yes, I am saying that. I specifically want to generate the image from within lua and then add it as a video track, in the same way `--external-file works`. My use case isn't limited to an album art scenario - that was just an example. Also, I work with WAVs a lot, so embedding images isn't an option.

In #3548, @wm4 mentioned the possibility of adding a `video-add` command, so I assumed it would be trivial. Would it be as simple as adding another `cmd_track_add` element to the [`mp_cmds` struct](https://github.com/mpv-player/mpv/blob/199aabddcc0105b504cc8e0cb240bc3c89288c1a/player/command.c#L6010) in  but with `STREAM_VIDEO`?

**Comment by merkle-root** [comment]
@jeeb I checked out the blame for command.c and noticed you've done a lot of work in it. Could you provide insight into how easy it would be to add a `video-add` command?

**Comment by merkle-root** [comment]
Would be solved with #6671

**Comment by po5** [comment]
#6671 has been merged, this should be closed.
