### ISSUE TITLE
lua not recognized in build config

### ISSUE THREAD

**Issue by thrisp** [mpv-player/mpv#6649]
I had retry building mpv after discovering I couldnt run any youtube-dl options 

LuaJIT 2.1.0-beta3 is installed, but not recognized in the config process

How can I build, ensuring lua is recognized?

### mpv version and platform

git master

### Reproduction steps

./waf configure

### Expected behavior

Checking for Lua                                                  : yes (installed luajit version)

### Actual behavior

Checking for Lua                                                  : no ('luajit >= 2.0.0' not found)

**Comment by qmega** [comment]
mpv finds lua using pkg-config. Try in a terminal:
```
pkg-config --libs --cflags 'luajit >= 2.0.0'
```
It may give you some more insight into why luajit isn't being recognized.

If you can't figure it out from that, upload `build/config.log` and tell us what OS/distro you're on.

**Comment by thrisp** [comment]
hmm yeah the dev package was not installed and should have been my first thought, thanks.
