### ISSUE TITLE
Unable to zoom in with caca or tct

### ISSUE THREAD

**Issue by aeioumania** [mpv-player/mpv#6650]
### mpv version and platform

0.29.1

### Reproduction steps

With a keybinding for zooming, attempt to zoom in or out while playing a video with --vo=tct or --vo=caca.

### Expected behavior

The video zooms in or out.

### Actual behavior

Nothing occurs (visually, at least).

### Log file

i used --vo=tct for this log. I attempted to zoom in, then out after pausing.

https://0x0.st/zq4M.txt

**Comment by CounterPillow** [comment]
FYI, those are joke VOs.
