### ISSUE TITLE
mpv no window under Sway WM dual screen setup with autofit & autofit-larger options

### ISSUE THREAD

**Issue by Mel34** [mpv-player/mpv#6653]
### mpv version and platform
Arch Linux
Sway WM 1.0
`Version         : 0.29.1`
### Reproduction steps
Use dual screen setup in sway defined as:
`    output HDMI-A-2 resolution 2560x1080 position 0,0 background $wallpaper fill`
`    output DVI-D-1 resolution 1920x1080 position 2560,0 background $wallpaper fill`

Set vo=gpu
Set gpu-context=wayland
Set autofit-larger or autofit in mpv.conf

### Expected behavior

mpv wndow is visible
### Actual behavior

mpv window doesn't spawn but audio playback can be heard
### Log file

https://0x0.st/zqYa.txt

### Sample files

Reproducible with any video file or simply using --player-operation-mode=pseudo-gui

### Additional notes

Turning off the second monitor spawns mpv window normally.

Posting here to make you aware of the bug and so I can reference this in sway bugreport

**Comment by Mel34** [comment]
Update:
https://github.com/swaywm/sway/issues/4076#issuecomment-509901446

**Comment by Mel34** [comment]
This is no longer an issue with a build from master. I can't pinpoint the commit that fixed it, but it's fixed in git master. I recommend you close this once you push a new version out.

**Comment by Dudemanguy911** [comment]
I can't reproduce this with Sway or Weston in current git master. Could you try updating it and trying it again? Does the bug only happen for you with `autofit`? #6949 is possibly the same issue although he didn't need to specify `autofit`.

**Comment by Mel34** [comment]
[Here's a video](https://drive.google.com/open?id=1pUXvpCZJ4r0xaFyejQAUEnOe4OcvacG4)
To clarify what's going on: I run the player on two display setup in sway, uncomment `autofit-larger`, run it again and windows doesn't show up. I `ctrl+c` it, comment `autofit-larger` again and mpv window is again spawning normally.
There is a display not included in the recording (output DVI-D-1). If I disable that display, mpv window is drawn normally even if I have `autofit-larger` set.

**Comment by Mel34** [comment]
To add to this, I'm running sway from master but 1.2 from repo does the same thing. I've also tried mpv from git and the issue is present there as well.

**Comment by Dudemanguy911** [comment]
Ah, now I can actually reproduce this. It only happens to me with `autofit-larger` and not `autofit` though. The output selecting part of the code must be lacking something.

**Comment by Mel34** [comment]
```
#autofit=70%x70%                                                                                                                                            
#autofit-larger=90%x90%
```
Both of these trigger the bug for me. It's probably part of the code they share. `autofit-smaller` works fine.
