### ISSUE TITLE
Colors seem to be wrong on default mpv

### ISSUE THREAD

**Issue by bluefiberbread** [mpv-player/mpv#6654]
Default mpv on Windows (probably the same on any other OS)
https://i.imgur.com/PkSCeRV.jpg
What it's supposed to look like
https://i.imgur.com/Gofg2wo.jpg

Is this intended or is it a bug because the colors look awful on mpv.
I'm using the latest compiled mpv from here https://sourceforge.net/projects/mpv-player-windows/files/64bit/

**Comment by bluefiberbread** [comment]
Why should I fill in the "issue template" when I'm asking a question

Is your reading comprehension that bad?

**Comment by Akemi** [comment]
your questions can't be answered like that. hence why more information is needed. though i doubt anyone is going to answer it now with that kind of attitude.

**Comment by bluefiberbread** [comment]
Someone who is powertripping and struggling with reading comprehension is trying to lecture me about attitude issues. Jesus fucking Christ

**Comment by Hrxn** [comment]
Can you really be so dense?

**Comment by lachs0r** [comment]
99% of the time issues with color reproduction in mpv are someone else’s fault. Bad file metadata, other players doing it incorrectly, shitty hardware decoding APIs etc.
