### ISSUE TITLE
Segfault with --vo=gpu on Tinker Board S (Rockchip MPP)

### ISSUE THREAD

**Issue by herbmillerjr** [mpv-player/mpv#6662]
Trying to get hardware accelerated playback working on a Tinker Board S running Tinker OS. Build is using master branch for mpv, ffmpeg, and mpp (they call it "release" branch). Unfortunately I'm getting a segfault. Xv output with rkmpp hwdec works fine, but I can't get gpu rendering to work.

### mpv version and platform

mpv: master
ffmpeg: master
mpp: release

### Reproduction steps

Run mpv with following options:
`/usr/local/bin/mpv --vo=gpu --hwdec=rkmpp --gpu-api=opengl --gpu-context=drm /home/linaro/test.mp4`

### Expected behavior

Plays video with fully hardware accelerated pipeline, or at least doesn't crash.

### Actual behavior

Crashes with segfault.

### Log file

https://hastebin.com/kelixuxuno.txt

### Sample files

Any .h264 encoded MP4 will reproduce.

**Comment by xantoz** [comment]
Does the problem occur before 537006965e98255deb6c433c3f715738d9092946? c151fae054d12ef9b392f5b6dcc1bafe894005b0 ? 

Also can you attach a gdb backtrace? Preferrably, can you also note the commit hashes of mpv, rkmpp and ffmpeg (for posterity)?

Have you tried experimenting with the --drm-draw-plane and --drm-drmprime-video-plane options? IIRC for hwdec to work you should use: `--drm-draw-plane=overlay --drm-drmprime-video-plane=primary` (and `--drm-osd-plane-id=1 --drm-video-plane-id=0` prior to c151fae054d12ef9b392f5b6dcc1bafe894005b0)

**Comment by herbmillerjr** [comment]
rkmpp commit: 90b2a3838ce89464531ac091ae76b7afb8b8f096

Does the problem occur before 5370069? Yes
Does the problem occur before c151fae? Yes

backtrace: https://hastebin.com/oqanavehep.txt

**Comment by xantoz** [comment]
The pastebin links seem dead. Is this still an issue? If so, can you repost them?

**Comment by wm4** [comment]
No response -> closing.
