### ISSUE TITLE
 Support WebP as screenshot format

### ISSUE THREAD

**Issue by Kattus** [mpv-player/mpv#6663]
### mpv version and platform
mpv 0.29.1
Arch Linux

### Reproduction steps
set `screenshot-format=webp` in mpv.conf

### Expected behavior
save screenshots in webp format

### Actual behavior
`Invalid value for option screenshot-format: webp`

It would be greatly appreciated if it were possible to save screenshots as webp, as either lossless or a set quality (configurable).

**Comment by Akemi** [comment]
implemented with #6832.
