### ISSUE TITLE
Laggy playback on the Android version.

### ISSUE THREAD

**Issue by xDevi69** [mpv-player/mpv#6664]
### mpv version and platform
mpv-android 2019-04-18-alpha (Shield TV)

### Reproduction steps
Playing any 4K HDR content on a SDR screen.

### Expected behavior
Smooth playback, HDR to SDR tonemapping.

### Actual behavior
Laggy playback.

### Log file

Can't find a way to make a log file on Android.

### Sample files

Any 4K HDR HEVC video file.

**Comment by xDevi69** [comment]
If this is not An issue and the problem is my shield that is not powerful enough, How can I improve the performance of the app?

**Comment by CounterPillow** [comment]
https://github.com/mpv-android/mpv-android

**Comment by sfan5** [comment]
As already noted, this is the wrong repository for mpv-android issues.
You can produce a logfile on Android using [`logcat`](https://developer.android.com/studio/command-line/logcat)

That said, I'm guessing the GPU just can't handle the tonemapping shaders.
