### ISSUE TITLE
Stuttering at start of a stream from ZDF Mediathek, sometimes with YT

### ISSUE THREAD

**Issue by mielouk** [mpv-player/mpv#6665]
### mpv version and platform
mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Apr 19 20:49:51 UTC 2019
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.3

System specs: https://8n1.org/15035/b857

### Reproduction steps
Start the link found down below, with a mpv instance. Watch the first few minutes till the video hangs for 1-2 seconds.

### Expected behavior
No stutter 

### Actual behavior
Stuttering at the beginning of the video.

### Log file

https://8n1.org/15034/d2d0

### Sample files
https://www.zdf.de/show/bares-fuer-rares/bares-fuer-rares-vom-25-april-2019-100.html

**Comment by lachs0r** [comment]
I can’t reproduce this.

Can you paste another log file with `--log-file`? That will include timestamps for each log message.
Or can you tell us whether it happened after playing for roughly 1 second, i.e. where libass initializes the font provider according to your log?
If so, please update fontconfig to git master or apply this patch: https://build.opensuse.org/package/view_file/M17N/fontconfig/fontconfig-do-not-remove-UUID-file.patch?expand=1

This is a known issue and Arch Linux hasn’t applied a fix yet. Further symptoms include Firefox being extremely slow when opening new tabs.

**Comment by mielouk** [comment]
Maybe it is correlated with a one minute skip in the beginning. 

Steps to reproduce:

- start the link via the command line
- press the arrow up to skip one minute forward
- video plays normally from ~1:04
- at 1:14 watch video hang vor 1-2 seconds, while sound is still audible and in sync 
- video starts playing again, but plays faster till it is back in sync with audio

Log File https://8n1.org/15038/75df

**Comment by wm4** [comment]
The link is dead so I can't reproduce, plus the issue is pretty old. Make new issue if the problem still happens with master.
