### ISSUE TITLE
Playlist non pause but single file pause

### ISSUE THREAD

**Issue by cyberpunkbln** [mpv-player/mpv#6666]
Hello,
only a short question/problem. I have set in the config all https streams/playlists to pause, when loading.

[protocol.https]
pause

But when i load a playlist (as example a youtube playlist) mpv pause after every playlist index.

When i can mpv get with config or other to only take the pause command in the config-section for the first file/index it will be great. And if this not possible that i can control mpv with an config or option to ignore pause in https-playlists.

thx

**Comment by Akemi** [comment]
you can use a script for that.

**Comment by cyberpunkbln** [comment]
Thx @Akemi,
do you have an example for this script, scripting with mpv is an new field for me;).
thx

**Comment by Akemi** [comment]
we have a whole page dedicated to scripts: https://github.com/mpv-player/mpv/wiki/User-Scripts

otherwise the docs:
https://github.com/mpv-player/mpv/blob/master/DOCS/man/lua.rst
https://github.com/mpv-player/mpv/blob/master/DOCS/man/javascript.rst

**Comment by cyberpunkbln** [comment]
thx @Akemi for doc links
