### ISSUE TITLE
Mpv not opening after quitting video with shift+q

### ISSUE THREAD

**Issue by lynoxy** [mpv-player/mpv#6667]
### mpv version and platform

mpv 0.29.0-306-g4e9dc60d9e
Windows 10

### Reproduction steps

1- quite video with shift+q
2- open same video

### Expected behavior

video resume with last position

### Actual behavior

mpv not opening

### Log file
```
[cplayer] Command line options: '-v'
[cplayer] mpv 0.29.0-306-g4e9dc60d9e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Apr 21 09:46:50 DST 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.26.100
[cplayer]    libavcodec      58.52.100
[cplayer]    libavformat     58.27.103
[cplayer]    libswscale      5.4.100
[cplayer]    libavfilter     7.49.100
[cplayer]    libswresample   3.4.100
[cplayer] ffmpeg version: N-45512-gd8245cff16
[cplayer]
[cplayer] Configuration: /home/shinchiro/build/build64/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-lua --enable-javascript --enable-libarchive --enable-libass --enable-libbluray --enable-dvdread --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --enable-openal --enable-vapoursynth --prefix=/home/shinchiro/build/build64/install/mingw
[cplayer] List of enabled features: asm atomics build-date cplayer crossc cuda-hwaccel d3d-hwaccel d3d11 d3d9-hwaccel debug-build direct3d dos-paths drmprime dvdnav dvdread dvdread-common egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win32 gnuc gpl iconv javascript jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libm libmpv-shared lua luajit mingw noexecstack openal optimize plain-gl posix-or-mingw rubberband shaderc shaderc-static static-build stdatomic uchardet vapoursynth vapoursynth-core vapoursynth-lazy vulkan wasapi win32-desktop win32-internal-pthreads win32-pipes zlib
[cplayer] Reading config file C:/Users/Seth/scoop/apps/mpv-git/current/portable_config/mpv.conf
[ifo] Opening C:/Users/Seth/scoop/apps/mpv-git/current/portable_config/input.conf
[ifo_dvdnav] Opening C:/Users/Seth/scoop/apps/mpv-git/current/portable_config/input.conf
[bdmv/bluray] Opening C:/Users/Seth/scoop/apps/mpv-git/current/portable_config/input.conf
[file] Opening C:/Users/Seth/scoop/apps/mpv-git/current/portable_config/input.conf
[input] Parsing input config file C:/Users/Seth/scoop/apps/mpv-git/current/portable_config/input.conf
[input] Input config file C:/Users/Seth/scoop/apps/mpv-git/current/portable_config/input.conf parsed: 24 binds
[cplayer] mpv 0.29.0-306-g4e9dc60d9e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Apr 21 09:46:50 DST 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.26.100
[cplayer]    libavcodec      58.52.100
[cplayer]    libavformat     58.27.103
[cplayer]    libswscale      5.4.100
[cplayer]    libavfilter     7.49.100
[cplayer]    libswresample   3.4.100
[cplayer] ffmpeg version: N-45512-gd8245cff16
[cplayer]
[cplayer] Usage:   mpv [options] [url|path/]filename
[cplayer]
[cplayer] Basic options:
[cplayer]  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
[cplayer]  --no-audio        do not play sound
[cplayer]  --no-video        do not play video
[cplayer]  --fs              fullscreen playback
[cplayer]  --sub-file=<file> specify subtitle file to use
[cplayer]  --playlist=<file> specify playlist file
[cplayer]
[cplayer]  --list-options    list all mpv options
[cplayer]  --h=<string>      print options which contain the given string in their name
[cplayer]
[ytdl_hook] script-opts/ytdl_hook.conf not found.
[ytdl_hook] lua-settings/ytdl_hook.conf not found.
[ytdl_hook] Exiting...
[stats] Exiting...
```

after disable-enable my config file entries i found that hwdec = dxva2  causes this issue and it only happens with mkv files.

(sorry for my bad english)

**Comment by zc62** [comment]
The log file you should upload is not the log file when you open an idle mpv window. It should be generated exactly when you are reproducing the issue.

**Comment by sethazazel** [comment]
okay,sorry for that  [ybin.me](https://ybin.me/p/5b87324b75d19c08#O0RVvzjTS365+ZPo2GFt8RJgG1EtlD/C29Xq/PdvmF4=)

**Comment by zc62** [comment]
The log does not seem to indicate `hwdec=dxva2` is doing any harm. But the log is incomplete. Did the mpv window freeze? Segfault? You can run in powershell `mpv your_video_file.mkv` to see the terminal output.

**Comment by sethazazel** [comment]
`PS C:\Users\Seth\Downloads\Tamamlandı\Series\ReLIFE\ReLIFE> mpv '.\ReLIFE - 01 - Kaizaki Arata (27), İşsiz.mkv'
[osd_clock] interval:15m, format:%H:%M:%S
Resuming playback. This behavior can be disabled with --no-resume-playback.
Playing: .\ReLIFE - 01 - Kaizaki Arata (27), İşsiz.mkv
[autoload] Adding ReLIFE - 02 - İletişim Becerisi 'Sıfır'.mkv
[autoload] Adding ReLIFE - 03 - Artık Amca Oldunuz.mkv
[autoload] Adding ReLIFE - 04 - Düşüş.mkv
[autoload] Adding ReLIFE - 05 - Üst Üste.mkv
[autoload] Adding ReLIFE - 06 - Bu İlk Değil.mkv
[autoload] Adding ReLIFE - 07 - Denek 001 » 002.mkv
[autoload] Adding ReLIFE - 08 - Çatlak.mkv
 (+) Video --vid=1 (*) (hevc 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) (opus 2ch 48000Hz)
 (+) Subs  --sid=1 --slang=tur (*) (ass)
[autoload] Adding ReLIFE - 09 - İntikam.mkv
[autoload] Adding ReLIFE - 10 - İnsanların Bencil Arzuları.mkv
[autoload] Adding ReLIFE - 11 - Geçmişe Yolculuk.mkv
[autoload] Adding ReLIFE - 12 - Çifte Panik.mkv
[autoload] Adding ReLIFE - 13 - İtiraf.mkv
Using hardware decoding (dxva2).
AO: [wasapi] 48000Hz stereo 2ch float
`

mpv window not opening.nothing happens. after deleting watch_later it normally works. but not working with shift+q

**Comment by Dudemanguy** [comment]
Very old and in theory shouldn't happen. Please open a new issue if this problem still exists.
