### ISSUE TITLE
words of appreciation

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#6670]
I just want to let you know that I had a very good experience using libmpv. No real problems, everything worked wonderfully. The API was straightforward to use and everything I could wish for was supported by libmpv.

I hope it's OK that I use the name mpv.net and that I've copied various things. I'm not good at writing anything that isn't code. Please let me know if there is anything that I can help or improve.

https://mpv-net.github.io/mpv.net-web-site/

**Comment by Akemi** [comment]
i am not sure what you copied but the most obvious was the logo. technically it's probably okay to do it, since it's LGPL 2.1 (https://github.com/mpv-player/random-stuff/tree/master/icon).

maybe you can clarify on your page that mpv.net is an application that uses libmpv as the backend, or something.

maybe someone else has something to say too.

**Comment by stax76** [comment]
I made a basic new icon now:

https://mpv-net.github.io/mpv.net-web-site/

What I've copied is the description on the main page because it's very good and I'm bad at writing.

> mpv.net is a modern media player for Windows that looks and works just like mpv.
> 
> Based on libmpv
> mpv.net is based on libmpv which offers a straightforward C API that was designed from the ground up to make mpv usable as a library and facilitate easy integration into other applications.
> 
> CLI options
> mpv.net has a basic CLI parser to support mpv's CLI options.
> 
> High quality video output
> libmpv has an OpenGL based video output that is capable of many features loved by videophiles, such as video scaling with popular high quality algorithms, color management, frame timing, interpolation, HDR, and more.
> 
> On Screen Controller
> mpv.net uses mpv's OSC offering play controls with a modern flat design.
> 
> GPU video decoding
> libmpv leverages the FFmpeg hwaccel APIs to support DXVA2 video decoding acceleration.
> 
> Active development
> mpv.net is under active development, focusing on user feedback. Want a feature? Post a patch or request it!
