### ISSUE TITLE
Question Re: libplacebo

### ISSUE THREAD

**Issue by mc4man** [mpv-player/mpv#6672]
### mpv version and platform
Latest git linux (Ubuntu
It seems libplacebo 1.8 can build using either shaderc or glslang. Is one preferred over the other for use in mpv?
In the presence of both it skips glslang for shaderc so guess would be shaderc, would like to confirm..

**Comment by philipl** [comment]
Yes. shaderc is the preferred choice.

**Comment by ePirat** [comment]
For the future, such a question probably fits better in the libplacebo bugtracker at https://code.videolan.org/videolan/libplacebo/issues

IIRC libplacebo first had support for shaderc (which internally uses glslang) but as it is a bit complex to build and its license can be a problem in some cases, @haasn added the ability to just use glslang directly without shaderc.
