### ISSUE TITLE
I like this features

### ISSUE THREAD

**Issue by michael466722** [mpv-player/mpv#6673]
### mpv version and platform
0.23.0-2+deb9u2. Debian.
### Expected behavior
When file is opened in player there should be two buttons for switching to neighboring files and player should switch to next neighboring file when current file ends.
For example Geeqie Image Viewer has similar features.
### Actual behavior
Opposite.

**Comment by sfan5** [comment]
> 0.23.0-2+deb9u2

This version is 3 years old, it is not supported.

> When file is opened in player there should be two buttons for switching to neighboring files

Look into [user scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts), autoload.lua provides this functionality.

**Comment by michael466722** [comment]
Thanks.
