### ISSUE TITLE
[libplacebo] OSD crash

### ISSUE THREAD

**Issue by shinchiro** [mpv-player/mpv#6677]
### mpv version and platform
git 71ad1e2f4c on Windows 10 x64

### Reproduction steps
Seek the sample file to around 16 seconds.

### Expected behavior
mpv renders subtitle's kfx correctly and OSD didn't crash.
 
### Actual behavior
OSD crashed and subtitle disappeared.

### Log file
https://0x0.st/zcMe.txt

### Sample files
https://0x0.st/zcMj.mkv

**Comment by lachs0r** [comment]
Cannot reproduce on Linux. 037cbacb8, libplacebo 1.18, AMD RADV VEGA10 (LLVM 7.0.1).

**Comment by haasn** [comment]
What does "OSD crash" mean?

**Comment by DeadSix27** [comment]
The full OSD disappears after a few frames of the Karaoke Subs appear.

OSD Being the osc.lua, the subtitles and things like "show-text" stop working.

The video keeps playing.

Here is a video showing the issue, you can see some of the karaoke subs appearing very briefly then every OSD element disappears:

https://0x0.st/zToN.webm

**Comment by shinchiro** [comment]
Getting assertion error. Anyway, here's the trace log for vo/gpu from beginning until the error came.
[trace-log.zip](https://github.com/mpv-player/mpv/files/3158151/trace-log.zip)

**Comment by shinchiro** [comment]
Getting assertion error. Anyway, here's the trace logs for vo/gpu from beginning until the error came.
[trace-log.zip](https://github.com/mpv-player/mpv/files/3158165/trace-log.zip)

**Comment by haasn** [comment]
Oops, that assertion should have been removed by the patch.

Updated: (only difference is the removed line)
```patch
commit 40e431c3d166820dbbaa99d277108cdf2a9bd10a
Author: Niklas Haas <git@haasn.xyz>
Date:   Wed May 8 14:05:05 2019 +0200

    vulkan: don't force large vertex buffers to be host visible
    
    The current logic could end up with a buffer that needs to be both
    device-local (for vertex information) and host-visible (for updates).
    This is obviously nonsensical, so work around this case instead.
    
    The ideal solution is to use a separate staging buffer, but that
    requires more logic changes than this workaround, and the only
    difference is that this might be possibly slower.

diff --git a/src/vulkan/gpu.c b/src/vulkan/gpu.c
index 7d4ebec..7cb4dfb 100644
--- a/src/vulkan/gpu.c
+++ b/src/vulkan/gpu.c
@@ -1307,7 +1307,6 @@ static void vk_buf_write(const struct pl_gpu *gpu, const struct pl_buf *buf,
         memcpy((void *) addr, data, size);
         buf_vk->needs_flush = true;
     } else {
-        pl_assert(size <= 64 * 1024);
         struct vk_cmd *cmd = vk_require_cmd(gpu, buf_vk->update_queue);
         if (!cmd) {
             PL_ERR(gpu, "Failed updating buffer!");
@@ -1319,11 +1318,24 @@ static void vk_buf_write(const struct pl_gpu *gpu, const struct pl_buf *buf,
 
         // Vulkan requires `size` to be a multiple of 4, so we need to make
         // sure to handle the end separately if the original data is not
+        const size_t max_transfer = 64 * 1024;
         size_t size_rem = size % 4;
         size_t size_base = size - size_rem;
         VkDeviceSize buf_offset = buf_vk->slice.mem.offset + offset;
 
-        vkCmdUpdateBuffer(cmd->buf, buf_vk->slice.buf, buf_offset, size_base, data);
+        if (size_base > max_transfer) {
+            PL_TRACE(gpu, "Using multiple vkCmdUpdateBuffer calls to upload "
+                     "large buffer. Consider using buffer-buffer transfers "
+                     "instead!");
+        }
+
+        for (size_t xfer = 0; xfer < size_base; xfer += max_transfer) {
+            vkCmdUpdateBuffer(cmd->buf, buf_vk->slice.buf,
+                              buf_offset + xfer,
+                              PL_MIN(size_base, max_transfer),
+                              (void *) ((uint8_t *) data + xfer));
+        }
+
         if (size_rem) {
             uint8_t tail[4] = {0};
             memcpy(tail, data, size_rem);
@@ -1440,8 +1452,9 @@ static const struct pl_buf *vk_buf_create(const struct pl_gpu *gpu,
         bufFlags |= VK_BUFFER_USAGE_TRANSFER_DST_BIT;
         align = pl_lcm(align, vk->limits.optimalBufferCopyOffsetAlignment);
 
-        // Large buffers must be written using mapped memory
-        if (params->size > 64 * 1024)
+        // Large buffers should be written using mapped memory for performance,
+        // unless this is not possible due to buffer memory type restrictions
+        if (params->size > 64 * 1024 && mem_type != PL_BUF_MEM_DEVICE)
             memFlags |= VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT;
     }
```

**Comment by shinchiro** [comment]
Tested the second patch. While it fixed the issue with provided sample, it randomly gave error with same kfx sequence in other clips. For example, https://0x0.st/zTtK.mkv will straight away gave error when pass `gpu-api=vulkan` and `osc=no` in mpv.conf

Some errors that I saw:
```
[vo/gpu/vulkan/libplacebo] Failed acquiring swapchain image: VK_ERROR_VALIDATION_FAILED_EXT
[vo/gpu/vulkan/libplacebo] vkAcquireNextImageKHR signals 000000000caf4060
```
and
![Annotation 2019-05-09 033317](https://user-images.githubusercontent.com/9623615/57404151-e3975d80-720d-11e9-91b5-84893d21ce53.png)

Not sure if trace log is useful here

**Comment by haasn** [comment]
`VK_ERROR_VALIDATION_FAILED_EXT` tells us that a validation layer was complaining about something. We'll need the actual error from the layer in question for that. A full log would be helpful.

The assertion failure seems like a bug in the failure path, I'll look into it tomorrow.

**Comment by DeadSix27** [comment]
Trace log: https://0x0.st/zT3o.log

If it helps, apparently `vulkan-async-compute` affects these, with it on, I only get the error device lost message:  https://0x0.st/zT38.log

Sometimes it doesn't crash at all and sometimes it crashes without an assert error (apart from the ones in the trace log).

Hope those help.

**Comment by haasn** [comment]
Hmm weird, it seems there's no actual validation error in these logs, but it seems like the validation layer may simply be guarding us from a previous `VK_ERROR_DEVICE_LOST` here.

It seems like we don't correctly handle the "device lost" error case in at least one of `{mpv, libplacebo}`.

P.s. For future reference, it's enough to do `--msg-level=vo=trace`, a full trace log just interferes with debugging due to the size of the resulting log.

**Comment by haasn** [comment]
Also, what's particularly strange is that it only signals `VK_ERROR_DEVICE_LOST` on the compute queue, not the graphics queue. That probably explains why `vulkan-async-compute` seems to make a difference.

We may need to communicate better "upstream" that the device got lost, so that mpv can ideally recreate the entire device.

**Comment by shinchiro** [comment]
Here's my trace log when passing only `--gpu-api=vulkan --osc=no`. This error can be produced consistently.
https://0x0.st/zTGZ.txt

**Comment by haasn** [comment]
Have you tried adding `--gpu-debug=yes`?

**Comment by shinchiro** [comment]
Here's the log with `--gpu-api=vulkan --osc=no --gpu-debug=yes`
https://0x0.st/zTD4.txt

**Comment by Dudemanguy** [comment]
@shinchiro: Is this still an issue?

**Comment by shinchiro** [comment]
Probably already fixed, I guess
