### ISSUE TITLE
The problem with some YouTube videos

### ISSUE THREAD

**Issue by flijloku** [mpv-player/mpv#6678]
mpv  -v https://www.youtube.com/watch?v=ShDKwDH_-Mw
[cplayer] Command line options: '-v' 'https://www.youtube.com/watch?v=ShDKwDH_-Mw'
[cplayer] mpv 0.29.0-318-g71ad1e2f4c Copyright c 2000-2019 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Apr 28 09:51:47 DST 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.26.100
[cplayer]    libavcodec      58.52.100
[cplayer]    libavformat     58.27.103
[cplayer]    libswscale      5.4.100
[cplayer]    libavfilter     7.50.100
[cplayer]    libswresample   3.4.100
[cplayer] ffmpeg version: N-45574-g8019395889
[cplayer]
[cplayer] Configuration: /home/shinchiro/build/build64/packages/mpv-prefix/src/mpv/waf configure --e
nable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-lua --
enable-javascript --enable-libarchive --enable-libass --enable-libbluray --enable-dvdread --enable-d
vdnav --enable-uchardet --enable-rubberband --enable-lcms2 --enable-openal --enable-vulkan --enable-
vapoursynth --prefix=/home/shinchiro/build/build64/install/mingw
[cplayer] List of enabled features: asm atomics build-date cplayer crossc cuda-hwaccel d3d-hwaccel d
3d11 d3d9-hwaccel debug-build direct3d dos-paths drmprime dvdnav dvdread dvdread-common egl-angle eg
l-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glob glob-win3
2 gnuc gpl iconv javascript jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libav
device libbluray libm libmpv-shared libplacebo lua luajit mingw noexecstack openal optimize plain-gl
 posix-or-mingw rubberband shaderc shaderc-static static-build stdatomic uchardet vapoursynth vapour
synth-core vapoursynth-lazy vulkan wasapi win32-desktop win32-internal-pthreads win32-pipes zlib
[cplayer] Reading config file C:\Users\Александр\AppData\Roaming/mpv/mpv.conf
[cplayer] Invalid value for option cache: 1000000
[cplayer] Valid values are:
[cplayer]     no
[cplayer]     auto
[cplayer]     yes
[cplayer] Error parsing option cache (option parameter could not be parsed)
[cplayer] C:\Users\Александр\AppData\Roaming/mpv/mpv.conf:5: setting option cache='1000000' failed.
[cplayer] Invalid value for option cache: 123400
[cplayer] Valid values are:
[cplayer]     no
[cplayer]     auto
[cplayer]     yes
[cplayer] Error parsing option cache (option parameter could not be parsed)
[cplayer] C:\Users\Александр\AppData\Roaming/mpv/mpv.conf:21: setting option cache='123400' failed.
[ifo] Opening C:\Users\Александр\AppData\Roaming/mpv/input.conf
[ifo_dvdnav] Opening C:\Users\Александр\AppData\Roaming/mpv/input.conf
[bdmv/bluray] Opening C:\Users\Александр\AppData\Roaming/mpv/input.conf
[file] Opening C:\Users\Александр\AppData\Roaming/mpv/input.conf
[input] Parsing input config file C:\Users\Александр\AppData\Roaming/mpv/input.conf
[input] Input config file C:\Users\Александр\AppData\Roaming/mpv/input.conf parsed: 2 binds
[cplayer] Waiting for scripts...
[stats] script-opts/stats.conf not found.
[ytdl_hook] script-opts/ytdl_hook.conf not found.
[stats] lua-settings/stats.conf not found.
[ytdl_hook] lua-settings/ytdl_hook.conf not found.
[osc] script-opts/osc.conf not found.
[osc] lua-settings/osc.conf not found.
[cplayer] Done loading scripts.
[cplayer] Playing: https://www.youtube.com/watch?v=ShDKwDH_-Mw
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook
[osd/libass] Shaper: FriBidi 1.0.5 (SIMPLE) HarfBuzz-ng 2.4.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider directwrite
[osd/libass] Done.
[ytdl_hook] not a ytdl:// url
[ffmpeg] Opening https://www.youtube.com/watch?v=ShDKwDH_-Mw
[ffmpeg] Mime-type: 'text/html; charset=utf-8'
[demux] Trying demuxers for level=normal.
[lavf] No format found, try lowering probescore or forcing the format.
[demux] Trying demuxers for level=unsafe.
[lavf] No format found, try lowering probescore or forcing the format.
[cplayer] Opening failed or was aborted: https://www.youtube.com/watch?v=ShDKwDH_-Mw
[cplayer] Running hook: ytdl_hook/on_load_fail
[ytdl_hook] full hook
[ytdl_hook] youtube-dl succeeded!
[edl] [demux] Trying demuxers for level=request.
[demux] Detected file format: Edit decision list
[demux] Stream is not seekable.
[demux] Opening segment 0...
[ffmpeg] Opening https://r1---sn-8ph2xajvh-n8ve.googlevideo.com/videoplayback/id/ShDKwDH_-Mw.1/itag/
140/source/yt_live_broadcast/requiressl/yes/playlist_type/DVR/ei/0GHIXNTeIIWFpASR2qOIAg/force_finish
ed/1/gcr/ru/ratebypass/yes/cmbypass/yes/mime/audio%2Fmp4/live/1/gir/yes/noclen/1/dur/5.000/disable_p
olymer/true/ip/83.220.239.116/ipbits/0/expire/1556657712/sparams/cmbypass,dur,ei,expire,force_finish
ed,gcr,gir,id,initcwndbps,ip,ipbits,itag,live,mime,mm,mn,ms,mv,noclen,pcm2cms,pl,playlist_type,rateb
ypass,requiressl,source/signature/4C680380518C27FA6CC5448F79CD9A654FE40E4F.67203962782F5517BE63F359C
3607FCC96BC208F/key/cms1/initcwndbps/1680/mm/32/mn/sn-8ph2xajvh-n8ve/ms/lv/mt/1556636068/mv/m/pcm2cm
s/yes/pl/24/sq/0/lmt/1556401274359798
[ffmpeg] Mime-type: 'audio/mp4'
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[demux] Opening segment 1...
[ffmpeg] Opening https://r1---sn-8ph2xajvh-n8ve.googlevideo.com/videoplayback/id/ShDKwDH_-Mw.1/itag/
140/source/yt_live_broadcast/requiressl/yes/playlist_type/DVR/ei/0GHIXNTeIIWFpASR2qOIAg/force_finish
ed/1/gcr/ru/ratebypass/yes/cmbypass/yes/mime/audio%2Fmp4/live/1/gir/yes/noclen/1/dur/5.000/disable_p
olymer/true/ip/83.220.239.116/ipbits/0/expire/1556657712/sparams/cmbypass,dur,ei,expire,force_finish
ed,gcr,gir,id,initcwndbps,ip,ipbits,itag,live,mime,mm,mn,ms,mv,noclen,pcm2cms,pl,playlist_type,rateb
ypass,requiressl,source/signature/4C680380518C27FA6CC5448F79CD9A654FE40E4F.67203962782F5517BE63F359C
3607FCC96BC208F/key/cms1/initcwndbps/1680/mm/32/mn/sn-8ph2xajvh-n8ve/ms/lv/mt/1556636068/mv/m/pcm2cm
s/yes/pl/24/sq/1/lmt/1556401299360158
[ffmpeg] Mime-type: 'audio/mp4'
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[demux] EDL: entry 1 uses 5.032000 seconds, but file has only 5.013333 seconds.
[demux] Opening segment 2...
[ffmpeg] Opening https://r1---sn-8ph2xajvh-n8ve.googlevideo.com/videoplayback/id/ShDKwDH_-Mw.1/itag/
140/source/yt_live_broadcast/requiressl/yes/playlist_type/DVR/ei/0GHIXNTeIIWFpASR2qOIAg/force_finish
ed/1/gcr/ru/ratebypass/yes/cmbypass/yes/mime/audio%2Fmp4/live/1/gir/yes/noclen/1/dur/5.000/disable_p
olymer/true/ip/83.220.239.116/ipbits/0/expire/1556657712/sparams/cmbypass,dur,ei,expire,force_finish
ed,gcr,gir,id,initcwndbps,ip,ipbits,itag,live,mime,mm,mn,ms,mv,noclen,pcm2cms,pl,playlist_type,rateb
ypass,requiressl,source/signature/4C680380518C27FA6CC5448F79CD9A654FE40E4F.67203962782F5517BE63F359C
3607FCC96BC208F/key/cms1/initcwndbps/1680/mm/32/mn/sn-8ph2xajvh-n8ve/ms/lv/mt/1556636068/mv/m/pcm2cm
s/yes/pl/24/sq/2/lmt/1556401299360162
[ffmpeg] Mime-type: 'audio/mp4'
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[demux] Opening segment 3...
[ffmpeg] Opening https://r1---sn-8ph2xajvh-n8ve.googlevideo.com/videoplayback/id/ShDKwDH_-Mw.1/itag/
140/source/yt_live_broadcast/requiressl/yes/playlist_type/DVR/ei/0GHIXNTeIIWFpASR2qOIAg/force_finish
ed/1/gcr/ru/ratebypass/yes/cmbypass/yes/mime/audio%2Fmp4/live/1/gir/yes/noclen/1/dur/5.000/disable_p
olymer/true/ip/83.220.239.116/ipbits/0/expire/1556657712/sparams/cmbypass,dur,ei,expire,force_finish
ed,gcr,gir,id,initcwndbps,ip,ipbits,itag,live,mime,mm,mn,ms,mv,noclen,pcm2cms,pl,playlist_type,rateb
ypass,requiressl,source/signature/4C680380518C27FA6CC5448F79CD9A654FE40E4F.67203962782F5517BE63F359C
3607FCC96BC208F/key/cms1/initcwndbps/1680/mm/32/mn/sn-8ph2xajvh-n8ve/ms/lv/mt/1556636068/mv/m/pcm2cm
s/yes/pl/24/sq/3/lmt/1556401307067799
[ffmpeg] Mime-type: 'audio/mp4'
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[demux] Opening segment 4...
[ffmpeg] Opening https://r1---sn-8ph2xajvh-n8ve.googlevideo.com/videoplayback/id/ShDKwDH_-Mw.1/itag/
140/source/yt_live_broadcast/requiressl/yes/playlist_type/DVR/ei/0GHIXNTeIIWFpASR2qOIAg/force_finish
ed/1/gcr/ru/ratebypass/yes/cmbypass/yes/mime/audio%2Fmp4/live/1/gir/yes/noclen/1/dur/5.000/disable_p
olymer/true/ip/83.220.239.116/ipbits/0/expire/1556657712/sparams/cmbypass,dur,ei,expire,force_finish
ed,gcr,gir,id,initcwndbps,ip,ipbits,itag,live,mime,mm,mn,ms,mv,noclen,pcm2cms,pl,playlist_type,rateb
ypass,requiressl,source/signature/4C680380518C27FA6CC5448F79CD9A654FE40E4F.67203962782F5517BE63F359C
3607FCC96BC208F/key/cms1/initcwndbps/1680/mm/32/mn/sn-8ph2xajvh-n8ve/ms/lv/mt/1556636068/mv/m/pcm2cm
s/yes/pl/24/sq/4/lmt/1556401312424886
[ffmpeg] Mime-type: 'audio/mp4'
[demux] Trying demuxers for level=normal.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[ffmpeg] tls: read failed: No error
[ffmpeg] https: Will reconnect at 81596 in 0 second(s), error=I/O error.
[ffmpeg] tls: read failed: No error
[ffmpeg] https: Will reconnect at 81596 in 1 second(s), error=I/O error.
[ffmpeg] tls: read failed: No error
[ffmpeg] https: Will reconnect at 81596 in 3 second(s), error=I/O error.
[ffmpeg] tls: read failed: No error
[ffmpeg] https: Will reconnect at 81596 in 7 second(s), error=I/O error.

**Comment by CounterPillow** [comment]
I for one get a ton of warnings like

```
EDL: entry 1 uses 5.032000 seconds, but file has only 5.013333 seconds.
EDL: entry 5 uses 4.967000 seconds, but file has only 4.949333 seconds.
EDL: entry 9 uses 5.000000 seconds, but file has only 4.992000 seconds.
EDL: entry 12 uses 5.000000 seconds, but file has only 4.992000 seconds.
EDL: entry 13 uses 5.000000 seconds, but file has only 4.992000 seconds.
EDL: entry 17 uses 5.000000 seconds, but file has only 4.992000 seconds.
EDL: entry 18 uses 5.000000 seconds, but file has only 4.992000 seconds.
EDL: entry 21 uses 5.000000 seconds, but file has only 4.992000 seconds.
EDL: entry 23 uses 5.000000 seconds, but file has only 4.992000 seconds.
EDL: entry 26 uses 5.000000 seconds, but file has only 4.992000 seconds.
EDL: entry 30 uses 4.999000 seconds, but file has only 4.992000 seconds.
EDL: entry 33 uses 5.000000 seconds, but file has only 4.992000 seconds.
EDL: entry 36 uses 5.000000 seconds, but file has only 4.992000 seconds.
EDL: entry 37 uses 5.000000 seconds, but file has only 4.992000 seconds.
```

maybe an FFmpeg edit list problem?

**Comment by flijloku** [comment]
Perhaps this is an unusual video. It does not appear in the "all videos" category. only in "completed live broadcasts". Perhaps there are some errors.

**Comment by disco0** [comment]
Crashes for me when opening with --no-config, but it plays fine otherwise—here's everything related to yt in my mpv.conf:
```
ytdl-format=bestvideo+bestaudio/best
script-opts=ytdl_hook-try_ytdl_first=yes
script-opts=ytdl_hook-use_manifests=yes
ytdl-raw-options=config-location="~//.config//mpv//youtube-dl.conf"
```
The youtube-dl.conf in raw options:
```
--cookies '~/.config/mpv/cookies'
--no-check-certificate
--mark-watched   #Probably not relevant here
```

**Comment by flijloku** [comment]
I do not know what happened, but the video is now playing. And displayed in "all videos".
