### ISSUE TITLE
Question : priority of forced subtitles over default can't be changed?

### ISSUE THREAD

**Issue by 44vince44** [mpv-player/mpv#6679]
When there is a "DEFAULT" subtitle stream and a "FORCED" subtitle stream in an mkv file, and the
sub visibility is yes, mpv will select the "FORCED" subtitles automatically when playing the mkv file.

Is there a way to make mpv play the "DEFAULT" subtitles automatically instead?
I couldn't find any option in the manual...

**Comment by Akemi** [comment]
none built in flags. one could probably write a script for that.
