### ISSUE TITLE
No window (sound works) without compton

### ISSUE THREAD

**Issue by axelfischer** [mpv-player/mpv#6680]
### mpv version and platform

mpv 0.29.1 on Gentoo

### Reproduction steps

Use EXWM (Emacs Window Manager), kill the compton process and play any video file in mpv.

### Expected behavior

The mpv window opens and the video gets shown.

### Actual behavior

The sound plays but no mpv window opens. When running Compton, everything works as expected.

### Log file

https://pastebin.com/LykDWNsS

**Comment by zc62** [comment]
https://mpv.io/manual/master/#video-output-drivers-vaapi
> Note that there is absolutely no reason to use this, other than compatibility. This is low quality, and has issues with OSD.

Do not use `vo=vaapi`. Try `--no-config` first.

**Comment by axelfischer** [comment]
Thank you! That worked. I read through the documentation now and fixed the issues in my configuration.
