### ISSUE TITLE
Error parsing option ytdl-format (option not found)

### ISSUE THREAD

**Issue by ZaxonXP** [mpv-player/mpv#6682]
### mpv version and platform

Installed using `mpv-build` script.

### Reproduction steps
```
git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build
./rebuild -j2
```
### Expected behavior
No `Error parsing option ytdl-format (option not found)` will be displayed.

### Actual behavior
Error parsing option ytdl-format (option not found)

### Log file
https://0x0.st/zcGz.txt

### Sample files

n/a

What configure options should I provide in order to get the `ytdl` related options be present in the builded `mpv` executable?

Regards,
Piotr

**Comment by CounterPillow** [comment]
Compile with lua support. It should be picked up automatically if lua 5.1, lua 5.2 or luajit library + headers are found.
