### ISSUE TITLE
How to disable hwdec?

### ISSUE THREAD

**Issue by windywater** [mpv-player/mpv#6687]
I would playback without GPU decoding, but I cannot find a switch in --vo and --hwdec to turn it off.

**Comment by j605** [comment]
It is disabled by default. `hwdec=no` explicitly disables it.

**Comment by windywater** [comment]
> It is disabled by default. `hwdec=no` explicitly disables it.

I used hwdec=no, but GPU was still working when play videos.
The version of MPV is 0.29.0-107-gd6d6da4711

**Comment by Argon-** [comment]
mpv runs it's shaders on the GPU (scaling etc). This has nothing to do with "hardware decoding".
