### ISSUE TITLE
Window decorations are missing with --gpu-context=waylandvk

### ISSUE THREAD

**Issue by hayspat** [mpv-player/mpv#6689]
### mpv version and platform
Arch Linux, Gnome 3.32 with wayland session.

mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Apr 19 20:49:51 UTC 2019
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.3

### Reproduction steps
Open a video with --gpu-api=vulkan --gpu-context=waylandvk in wayland session.
### Expected behavior
mpv opens with window decorations and borders
### Actual behavior
Window decorations and borders are missing
-gpu-context=wayland works fine. Is there any reason to use waylandvk over wayland?

Edit:
-vo=gpu --gpu-api=vulkan --gpu-context=waylandvk  / Decorations are missing
-vo=vaapi --gpu-api=vulkan --gpu-context=waylandvk / Works as expected
-vo=vdpau --gpu-api=vulkan --gpu-context=waylandvk / Works as expected

mpv --vo=gpu --gpu-api=vulkan --gpu-context=wayland / Crashes 
[vo/gpu] Failed initializing any suitable GPU context!
Error opening/initializing the selected video_out (--vo) device.

**Comment by philipl** [comment]
`--vo=vaapi` and `--vo=vdpau` are X11 only and the `gpu` config options are only used by `--vo=gpu`.

Your last error is because `--gpu-context=wayland` implies opengl and when you force the api to vulkan, you create an incompatible combination.

So your behaviour is all as expected.

**Comment by hayspat** [comment]
Thanks for clarifying! In the end if i go full wayland route with --vo=gpu --gpu-api=vulkan --gpu-context=waylandvk, are missing decorations normal behaviour?

**Comment by philipl** [comment]
They are normal behaviour. gnome doesn't implement server-side decorations, so we get no decorations (In contrast, KDE would provide them).

**Comment by hayspat** [comment]
Thanks for your help. I'm marking this as closed.
