### ISSUE TITLE
Can't use deinterlacing options.

### ISSUE THREAD

**Issue by mzso** [mpv-player/mpv#6690]
###mpv 0.29.1 Windows 8.1 x64

### Reproduction steps
I tried setting up deinterlacing in the config file as per the manual, via:
`vf=vavpp:deint=motion-adaptive:interlaced-only=yes`
for "gpu" renderer.
and
`vf=d3d11vpp:deint=yes:mode=bob`
for direct3d
Neither succeeded.
I got:
`[user_filter_wrapper] Creating filter 'd3d11vpp' failed.`

and
```
[lavfi] filter 'vavpp' not found or failed to allocate
[user_filter_wrapper] Creating filter 'vavpp' failed.
```
### Expected behavior
Use the the deinterlacing filters specified

### Actual behavior
mpv fails to start with errors.

### Log file
[log-dx.txt](https://github.com/mpv-player/mpv/files/3145696/log-dx.txt)
[log-gpu.txt](https://github.com/mpv-player/mpv/files/3145697/log-gpu.txt)

**Comment by CounterPillow** [comment]
vavpp is Linux only. Why aren't you just hitting `d` to enable deinterlacing?

**Comment by CounterPillow** [comment]
Also, d3d11vpp isn't working because you're not using d3d11 hardware decoding, which the manual says is required for d3d11vpp. Again, just press d. mpv will do the right thing for you.

**Comment by mzso** [comment]
[**@CounterPillow**](https://github.com/CounterPillow) commented on [2019. máj. 5. 18:13 CEST](https://github.com/mpv-player/mpv/issues/6690#issuecomment-489440358 "2019-05-05T16:13:08Z - Replied by Github Reply Comments"):
> vavpp is Linux only. Why aren't you just hitting `d` to enable deinterlacing?

Didn't see such claim in the manual. It only said that it only works with vaapi and opengl.


[**@CounterPillow**](https://github.com/CounterPillow) commented on [2019. máj. 5. 18:27 CEST](https://github.com/mpv-player/mpv/issues/6690#issuecomment-489441513 "2019-05-05T16:27:24Z - Replied by Github Reply Comments"):
> Also, d3d11vpp isn't working because you're not using d3d11 hardware decoding, which the manual says is required for d3d11vpp. Again, just press d. mpv will do the right thing for you.

I didn't notice that. I guess I'll have to figure out how to enable that.

> vavpp is Linux only. Why aren't you just hitting `d` to enable deinterlacing? Again, just press d. mpv will do the right thing for you.
And how do I configure it to only activate for interlaced frames? Or specify the deinterlacing algorithm? Which is unspecified and unknown to me. Using plainly the d hotkey or -deinterlace doesn't seem to have any options.

**Comment by CounterPillow** [comment]
>Didn't see such claim in the manual. It only said that it only works with vaapi and opengl.

You should look up what VA-API is.

>And how do I configure it to only activate for interlaced frames? Or specify the deinterlacing algorithm? Which is unspecified and unknown to me. Using plainly the d hotkey or -deinterlace doesn't seem to have any options.

In this case, mpv will most likely insert yadif, which is the one you'll want anyway. From the manual:

>Enabling this typically inserts the yadif video filter in order to deinterlace the video, or lets the video output apply deinterlacing if supported.

yadif is documented [over at the ffmpeg filters documentation](https://ffmpeg.org/ffmpeg-filters.html#yadif-1). If you want it to only apply to frames which are correctly tagged as interlaced (a lot of media files don't tag interlacing properly, hence why hitting d just forces deinterlacing on), you'll have to specify your own vf line with yadif.

>And how do I configure it to only activate for interlaced frames?

For yadif, deint=1

**Comment by mzso** [comment]
@CounterPillow 
I see. Well, I rather don't like the results with yadif in some instances: https://drive.google.com/file/d/1JNTd0AwlY4xEMRSQS124vAtMbfazOjWe/view

That's why I was looking at these deinterlace filters, apart from the apparent lack of configurability.

Rather disappointing that d3d11vpp is tied to HW decoding for some reason, because in my experience it's a lot slower than cpu decoding.

**Comment by CounterPillow** [comment]
With some luck it might only require d3d11 to be the API used, and hardware decoding theoretically being available but not necessarily enabled. Instead of `--vo=direct3d`, use `--vo=gpu --gpu-context=d3d11` and try that filter then.

**Comment by mzso** [comment]
[**@CounterPillow**](https://github.com/CounterPillow) commented on [2019. máj. 5. 19:22 CEST](https://github.com/mpv-player/mpv/issues/6690#issuecomment-489445915 "2019-05-05T17:22:28Z - Replied by Github Reply Comments"):
> With some luck it might only require d3d11 to be the API used, and hardware decoding theoretically being available but not necessarily enabled. Instead of `--vo=direct3d`, use `--vo=gpu --gpu-context=d3d11` and try that filter then.

Thanks for the suggestion! It seems to work, based on the log:
```
[   0.095][v][vd] Codec list:
[   0.095][v][vd]     mpeg2video - MPEG-2 video
[   0.095][v][vd]     mpegvideo (mpeg2video) - MPEG-1 video
[   0.095][v][vd]     mpeg2_cuvid (mpeg2video) - Nvidia CUVID MPEG2VIDEO decoder
[   0.095][v][vd] Opening decoder mpeg2video
[   0.095][v][vd] No hardware decoding requested.
[   0.095][v][vd] Using software decoding.

[   0.602][v][vd] Codec list:
[   0.602][v][vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[   0.602][v][vd]     h264_cuvid (h264) - Nvidia CUVID H264 decoder
[   0.602][v][vd] Opening decoder h264
[   0.602][v][vd] No hardware decoding requested.
[   0.602][v][vd] Using software decoding.
```

**Comment by mzso** [comment]
[**@mzso**](https://github.com/mzso) commented on [2019. máj. 5. 20:36 CEST](https://github.com/mpv-player/mpv/issues/6690#issuecomment-489451642 "2019-05-05T18:36:08Z - Replied by Github Reply Comments"):
> [**@CounterPillow**](https://github.com/CounterPillow) commented on [2019. máj. 5. 19:22 CEST](https://github.com/mpv-player/mpv/issues/6690#issuecomment-489445915 "2019-05-05T17:22:28Z - Replied by Github Reply Comments"):
> > With some luck it might only require d3d11 to be the API used, and hardware decoding theoretically being available but not necessarily enabled. Instead of `--vo=direct3d`, use `--vo=gpu --gpu-context=d3d11` and try that filter then.
> 
> Thanks for the suggestion! It seems to work, based on the log:

Too bad that because of #5957 I still have to choose between two bads.

**Comment by mzso** [comment]
It seems like d3d11vpp wouldn't work anymore. God knows why.
[deint-fail2.txt](https://github.com/mpv-player/mpv/files/3896894/deint-fail2.txt)
