### ISSUE TITLE
Passthrough Help

### ISSUE THREAD

**Issue by wingedonezero** [mpv-player/mpv#6696]
I'm using the latest 29 git master from a mpv ppa.

I'm trying and have been for a few weeks to get pass through working Ive read countless previous tickets on it and what articles i could find.

And Ive been over the manual several times. And there's a few things i don't understand from it.

And i quote from manual the info
---------------------------------------------------------------------------------------------------------
--audio-spdif=<codecs>

    List of codecs for which compressed audio passthrough should be used. This works for both classic S/PDIF and HDMI.

    Possible codecs are ac3, dts, dts-hd, eac3, truehd. Multiple codecs can be specified by separating them with ,. dts refers to low bitrate DTS core, while dts-hd refers to DTS MA (receiver and OS support varies). If both dts and dts-hd are specified, it behaves equivalent to specifying dts-hd only.

    In earlier mpv versions you could use --ad to force the spdif wrapper. This does not work anymore.

    Warning

    There is not much reason to use this. HDMI supports uncompressed multichannel PCM, and mpv supports lossless DTS-HD decoding via FFmpeg's new DCA decoder (based on libdcadec).
-------------------------------------------------------------------------------------------------------

Now im using hdmi attached to a Denon 1400x avr running linux Ubuntu 18.04 to be exact.
Now what i understand from this is that it auto does pass-through now. But i feel like some kind of re-sampling is being done.

On TrueHd,Flac files stats says s32 as codec i couldn't find much info on this codec/ Other then its sox or something.
On ac3,Dts,eac3 the output codec is floatp it says

These we just a short list of ones ive tested. Any help to direct me would be appriciated its been frustrating. Ive tried the whole use pavucontrol to switch to stero mode to enable passthrough there but no success. Im currently set to 5.1 surround in kde using pulse also set to avoid resample.

I was looking for a way to force all output to pcm or something with out any conversion or audio tamperings. But no options i could find did that.

Ill attach my mpv config below as well.

[mpv.txt](https://github.com/mpv-player/mpv/files/3150207/mpv.txt)

**Comment by CounterPillow** [comment]
>I was looking for a way to force all output to pcm or something with out any conversion or audio tamperings. But no options i could find did that.

floatp/s32 is PCM. floatp is packed floats, s32 is 32-bit sample data.

**Comment by wingedonezero** [comment]
> > I was looking for a way to force all output to pcm or something with out any conversion or audio tamperings. But no options i could find did that.
> 
> floatp/s32 is PCM. floatp is packed floats, s32 is 32-bit sample data.

So does that mean its not tampering with anything if its outputting to that then? My concern is if it altering the audio at all or any resampling.

**Comment by CounterPillow** [comment]
No, it should not be altering it, it's decoding the audio and putting out the decoded PCM.

**Comment by haasn** [comment]
Why don't you just test and see if you can hear any signal degradation?

**Comment by rogerxxxx** [comment]
The proper command line argument/parameter should be written as without quotes:
"-audio-spdif=ac3,dts,dts-hd,eac3,truehd"
