### ISSUE TITLE
Force mono on stereo

### ISSUE THREAD

**Issue by windcask** [mpv-player/mpv#6697]
Oftentimes I will listen to Youtube videos with bad stereo mixes, with one strong channel and one weak channel. My current routine for handling this is to youtube-dl the video, open it in Audacity and downmix the audio to mono, and then re-render it as a mono file, which allows playback of mono in the center of my headphones. It would be nice to shortcut this routine and just play centered mono audio.

`--audio-channels=1` almost gets there. The output only comes out of the left channel and it would be nice to pan it to center.

**Comment by garoto** [comment]
Put this in your input.conf:
`<keybind> af toggle "lavfi=[pan=1c|c0=1*c0+1*c1]" ; show-text "Audio mix set to Mono"`

**Comment by windcask** [comment]
This worked perfectly. Would have worked better had I put the actual key to be bound in the configuration file rather than literally using "<keybind>". Appreciate it.

**Comment by garoto** [comment]
`<keybind> af toggle "lavfi=[pan=1c|c0=0.5*c0+0.5*c1]" ; show-text "Audio mix set to Mono"`
The above is more sane for a 1:1 volume level when downmixing.

**Comment by kevmitch** [comment]
`--audio-channels=mono` works for me

**Comment by Tsuchimikado** [comment]
> `--audio-channels=mono` works for me

Thank you. Added `Shift+m cycle-values audio-channels "auto-safe" "mono"` to input.conf to cycle between default and mono audio.

**Comment by Svnipni** [comment]
Apologies to revive this old thread. I tried to use the above suggestions, but on many files, it causes dialogue to become virtually inaudible. This also happens in vlc and haruna.
