### ISSUE TITLE
Taking two screenshots when I press the button once

### ISSUE THREAD

**Issue by tsukari** [mpv-player/mpv#6699]
### mpv version and platform
mpv-x86_64-20190428
Windows

### Reproduction steps
Press screenshot button

### Expected behavior
Take one screenshot

### Actual behavior
Takes two screenshots

### Log file
https://pastebin.com/DV6PiiSy

**Comment by llyyr** [comment]
Only one screenshot was taken according to the log file. Use mpv with the `--no-config` flag and see if it still happens.
