### ISSUE TITLE
⌘H no longer hides mpv

### ISSUE THREAD

**Issue by Forcer78** [mpv-player/mpv#6700]
### mpv version and platform

```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Mon Apr  1 23:40:01 EDT 2019
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1.3
```

macOS 10.12.6.

### Reproduction steps

Play a movie and press ⌘H.

### Expected behavior

The movie player hides (as used to work in mpv).

### Actual behavior

No response except a console log:
`[input] No key binding found for key 'Meta+h'.`

**Comment by Akemi** [comment]
works here with the same version on 10.14. also you didn't attach a log. try with --no-config. also post a screenshot of the mpv menu where the hide item is located.

**Comment by Forcer78** [comment]
Log: [log.txt](https://0x0.st/zTvo.txt)

Screenshot: <img width="275" alt="menu" src="https://user-images.githubusercontent.com/17772853/57410026-b324d480-71b7-11e9-90e2-9bdad65e09b6.png">

**Comment by Akemi** [comment]
does the "hide others" shortcut work? if yes i assume something on your end is blocking it, or it might be a bug in the deprecated and not supported vo=gpu cocoa backend.

**Comment by Forcer78** [comment]
Yes, "Hide Others" works. If something on my end is blocking it, it's selectively blocking only mpv.

My mpv falls back to vo=gpu because vo=libmpv is prevented by `--disable-swift`, which is needed to work around [this crashing issue](https://github.com/mpv-player/mpv/issues/6191).

**Comment by Akemi** [comment]
i tried on 10.12.6 and it works for me there too. since it's apparently a regression for you try to find out which version/commit caused the problem. so we can at least narrow it doen.

**Comment by Forcer78** [comment]
The Hide command and shortcut returned after I quit Safari. Nothing else was changed.

I have no explanation for this.
