### ISSUE TITLE
How to align only lines of dialogue that begin with"-"to the left?

### ISSUE THREAD

**Issue by Araynilmar** [mpv-player/mpv#6701]
### mpv version and platform
mpv 0.29.0-282-gfcb320fd3f
Windows x64 10.0.17134.706 (Win10 RS4 [1803] April 2018 Update)

### Reproduction steps
My mpv.conf about sub-justify
`
sub-justify=left
sub-ass-justify=yes
`

This setting causes all multi-line subs aligned to left.

However, I just want the dialogue multi-lines starting with "-" aligned to the left and the rest centered. How to do that?

### Expected behavior
![img_url](https://res.cloudinary.com/aray/image/upload/v1557431354/Screenshots/Black.Hawk.Down.2001.EXTENDED.REMASTERED.1080p.BluRay.x264.DTS-SWTYBLZ_002131.499_Dialogue.Justify.Left.jpg)

### Actual behavior
![img_url](https://res.cloudinary.com/aray/image/upload/v1557431354/Screenshots/Black.Hawk.Down.2001.EXTENDED.REMASTERED.1080p.BluRay.x264.DTS-SWTYBLZ_002305.592_Justify.Center.jpg)

**Comment by Dosprogs** [comment]
It's probably possible to do this with a lua script that yanks the subtitles, filters out ones that begin with a dash, and then aligns those to the left.

**Comment by wm4** [comment]
I don't think you can do this with Lua scripting (it can't change subtitles). Your only choice is probably to write an external script that processes a subtitle file this way. I also had this idea of implementing some sort of subtitle filtering facility, which could be used for something like this, but don't count on this.
