### ISSUE TITLE
[Help] Need help playing HD (Mbps video bitrate) mp4 videos on slow hardware

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#6706]
### mpv version and platform

mpv 0.29.1 on Ubuntu LTS

### Reproduction steps

Play any 720p (or higher) local video with one Mbps video bit-rate (or higher) : 

```bash
wget -c https://cdn.sermons.love/mp4/Joseph%20Prince/Joseph%20Prince%20-%20The%20Heart%20of%20the%20Father%20Revealed.mp4
mpv --fs --no-config "Joseph Prince - The Heart of the Father Revealed.mp4"
```

### Expected behavior

This is not a bug, I just need help while waiting for a faster hardware.

### Actual behavior

Averagely 24 out of 29.97 frames get dropped ever second and the A-V delay is of 4 seconds after playing the first 10 seconds of this video.

### Log file

[Issue_#6706.txt](https://github.com/mpv-player/mpv/files/3169025/Issue_.6706.txt)

### Sample files

https://cdn.sermons.love/mp4/Joseph%20Prince/Joseph%20Prince%20-%20The%20Heart%20of%20the%20Father%20Revealed.mp4

**Comment by sfan5** [comment]
take a look at `vd-lavc-fast` and more notably `vd-lavc-skiploopfilter`

**Comment by CounterPillow** [comment]
You might also want to try hardware decoding, since this is Baseline H.264 so even the crappiest hwdec should work. Check whether with your driver either vaapi or vdpau works, or let mpv try the first one that works with `hwdec=auto`.

**Comment by sebma** [comment]
Thanks guy, I'll look into it tonight.

**Comment by sebma** [comment]
@sfan5 Hi,
With `--vd-lavc-fast`, the ratio of deleted frames is roughly the same (24.2/29.96=80%) and the delay is of 3.82s on a 10s segment of the video.

I'm not sure which value to add to the parameter `--vd-lavc-skiploopfilter=` because I don't know which type of frames to skip for faster decompression (B-Frames ?, keyframes ?, reference-frames ?)

Can I use both `--vd-lavc-fast` and `--vd-lavc-skiploopfilter` options at the same time ?

**Comment by sfan5** [comment]
> because I don't know which type of frames to skip for faster decompression (B-Frames ?, keyframes ?, reference-frames ?)

test `vd-lavc-skiploopfilter` = `nonref`, `nonkey` and `all` and see which is works

> Can I use both --vd-lavc-fast and --vd-lavc-skiploopfilter options at the same time ?

yes

**Comment by sebma** [comment]
@sfan5 Thanks a lot, man !
The `vd-lavc-skiploopfilter=nonref` parameter did the job, with a much smaller delay of 0.1s for 10s of playing.

The `vd-lavc-fast` does not improve the result when the previous parameter is used.

**Comment by sebma** [comment]
@sfan5 I've put this parameter in a dedicated profile in my `~/.config/mpv/mpv.conf` :)

One last question to you : Is it possible for `mpv` to trigger this profile when a video with a bitrate higher than a specific a specific value or a resolution >= 1080p ?
