### ISSUE TITLE
[Help] mpv's color managment and DisplayCAL's Profile Loader

### ISSUE THREAD

**Issue by xXedgelordXx** [mpv-player/mpv#6709]
### mpv version and platform
0.29.1 Windows 10 1809

I have a question about mpv's color managment and DisplayCAL's Profile Loader.
Should I reset the video card gamma table in the DisplayCal's Profile loader every time I use mpv?
Because if I don't reset it the video looks darker than madvr with a 3dlut.
If I don't reset the video card gamma table looks like the gamma is being applied two times to the video. 

[mpv1.log](https://github.com/mpv-player/mpv/files/3170404/mpv1.log)

**Comment by haasn** [comment]
The ICC profiles generated by DisplayCAL assume the gamma table from the profile is loaded.

**Comment by xXedgelordXx** [comment]
So should I reset the video card gamma table every time I use mpv or not?

**Comment by haasn** [comment]
I assume by "resetting" you mean "clearing"? If so, that does sound wrong.
