### ISSUE TITLE
YouTube: Is it possible to "copy video URL at current time" as on the website?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#6710]
youtube.com video context menu:

![2019-05-12 22_29_24-Angry Video Game Nerd Adventures - Castlevania Stage 'Assholevania' (No Damage w](https://user-images.githubusercontent.com/14923168/57586913-76354680-7505-11e9-99e2-1383887ddada.png)

**Comment by LaserEyess** [comment]
This could be easily done with a script. Make a function that returns the original URL and just appends `#t=XXXs` to it. Where `XXX` is a seconds only timestamp returned from [this property](https://mpv.io/manual/master/#command-interface-time-pos)

**Comment by haasn** [comment]
I wonder if this is in-scope for the ytdl hook. But probably not, seeing as accessing the clipboard is highly OS dependent anyway.

**Comment by Akemi** [comment]
i would say no, exactly because of that.
