### ISSUE TITLE
Can't open using i3 binding

### ISSUE THREAD

**Issue by mvrozanti** [mpv-player/mpv#6715]
### mpv version and platform
`mpv -V`

```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.2
```

`uname -mrs`:
`Linux 5.0.6-arch1-1-ARCH x86_64`

I'm using the mpv version in community repositories.

### Reproduction steps
`[cplayer] Command line options: '--no-config' '-v' 'https://www.youtube.com/watch?v=5HjaJbW8OfM'`

### Expected behavior
youtube video starts playing

### Actual behavior
youtube video doesn't start playing

### Log file
http://ix.io/1J2b

### Sample files
youtube url

### Description
For some reason, I can only reproduce this behaviour inside an i3 hotkey binding. I'm sure this was working before but I've been having no luck for about a month now.

Is it possible the problem is with `youtube-dl`?

Thanks

**Comment by CounterPillow** [comment]
Update the youtube-dl that is picked in this environment. It's possible whatever you do within i3 selects a different youtube-dl than the one in your PATH when you open a terminal.

**Comment by mvrozanti** [comment]
Spot on. I forked `youtube-dl` and forgot it was installed

Thanks!
