### ISSUE TITLE
Auto-rotate during playback MKV/Matroska videos

### ISSUE THREAD

**Issue by Wakagithub** [mpv-player/mpv#6718]
Hello. Please add the ability to auto-rotate during playback, MKV/Mataroska videos which have the ROTATE tag inside. Other players like MPC-HC (the very first one), MPC-BE (2nd), and PotPlayer (3rd), can auto-rotate MKV's with such simple XML rotation tags.

Putting such XML rotation tags into multiple MKV's can be done for example by MKVToolNix CLI exe's (eg. using BATCH to handle many, many MKV's easily). Could also be later edited by chapterEditor. One advantage, since MKV supports many formats, then for example VP9 and VP8 can be auto-rotated too while inside an MKV. Another, the wanted rotation is lossless as they are only simple metadata tags, no re-encoding needed.

For example, a simple ROTATE tag with a string value of 90, to rotate at 90 degrees, can be put into the video track of the MKV during remuxing.

A sample MKV with the ROTATE tag can be found [here](https://sites.google.com/site/dp79lakas/home/allpurpose/sample.mkv?attredirects=0&d=1).

The sample video is normal horizontal, but due to the ROTATE metadata, it should be auto-rotated to the right (90 degrees) when played by MPC-HC, MPC-BE, and PotPlayer.

Thank you in advance.

**Comment by wm4** [comment]
Can someone murder the idiot who invented this rotate tag?
What the fuck is the point of EBML if they keep stuffing garbage into tags?
I refuse to implement this.

**Comment by Argon-** [comment]
I can actually imagine one (imo valid) use case for supporting this: videos made with smartphones. IIRC the first and only time I've ever seen such a tag was in a video recorded with a smartphone where the phone was rotated multiple times while recording.
But this was mp4, not mkv. So maybe a different tag.

**Comment by wm4** [comment]
Of course there's a use-case for this, and mpv supports it for e.g. mpv. But the way this was implemented in mkv (at least this manifestation, it's not like it's standardized) is just disgusting.
