### ISSUE TITLE
Having mpv play specific item on m3u file.

### ISSUE THREAD

**Issue by elohssa69** [mpv-player/mpv#6719]
### mpv version and platform
0.29.1 Android(Termux)

I don't really have an issue with mpv player at this point.  I am just wondering if it is at all possible to have mpv player play only one specific item in an m3u file.  If not, that's fine.  If it is, could someone please tell me how to do that?  Thanks in advance.

**Comment by Akemi** [comment]
--playlist-start for the item you want to play, and then maybe listen in script to file end event and do whatever you want then.
