### ISSUE TITLE
Skip Chapters

### ISSUE THREAD

**Issue by smolseok** [mpv-player/mpv#6720]
Is there any way to skip chapters with names? Like set up MPV to automatically skip chapters named op and ed on any file. Is there something I could just slip into the conf. file and have it work perfectly?

**Comment by Akemi** [comment]
no, but there is a [script](https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/scripts/avail/skipchapters.lua) for that.

an incomplete list of [mpv scripts](https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst).

**Comment by smolseok** [comment]
So I just save that and slip it into the same directory as mpv, I'm on Windows so will it work like that.?

**Comment by Akemi** [comment]
please read the docs. the location of scripts is mentioned [here](https://github.com/mpv-player/mpv/blob/master/DOCS/man/lua.rst) at the beginning or more specifically [here](https://github.com/mpv-player/mpv/blob/fcb320fd3fd3b1fc5549c009f23fc831bd37a495/DOCS/man/mpv.rst#files) and the chapter below for windows.

**Comment by smolseok** [comment]
Woah, it actually works damn. Thank you so much man, much appreciated I'm very much a noob so it was real nice of you to help me out.
