### ISSUE TITLE
Question about display of overlapping srt subtitle

### ISSUE THREAD

**Issue by OliverLew** [mpv-player/mpv#6721]
I have a .srt subtitle that has overlapping (in time) lines, like (not in srt format):
```
00:00 - 00:10 AAAAA
00:05 - 00:15 BBBBB
00:10 - 00:20 CCCCC
```
So at 00:10 the first line is replaced by the third line as from
```
AAAAA
BBBBB
```
to
```
CCCCC
BBBBB
```
But I would like the subtitle to behave like scrolling, which is like
```
BBBBB
CCCCC
```
In short, what comes later will be put at bottom, can I achieve that?

**Comment by Akemi** [comment]
no, that would be a feature request for libass i suppose.

**Comment by mrfragger** [comment]
40:03:11.653 --> 40:03:16.213
more and more 1

40:03:16.213 --> 40:12:32.523
persistently display for 8 mins

40:03:24.933 --> 40:03:29.573
more and more 3

40:03:30.373 --> 40:03:34.133
more and more 4

script handles vtt and srt and changes it like so fixing the timecode overlapping issue

40:03:11.653 --> 40:03:16.213
more and more 1

40:03:16.213 --> 40:03:24.933
persistently display for 8 mins (FIXED)

40:03:24.933 --> 40:03:29.573
more and more 3

40:03:30.373 --> 40:03:34.133
more and more 4

```
#!/bin/bash
cd ~/datampv/editing
for f in *.vtt
do ffmpeg -i "$f" "${f%.*}"_overlapping.srt
done
for f in *_overlapping.srt
do awk '
  BEGIN {
    RS = "";
    OFS = FS = "\n";
    getline;
    n = split($0, prev_rec);
    split($2, prev_time, / --> /);
  }
  {
    split($2, a, / --> /);
    if (a[1] < prev_time[2])
      prev_rec[2] = prev_time[1]" --> "a[1];
    for (i=1;i<=n;i++)
      print prev_rec[i];
    printf("\n");
    n = split($0, prev_rec);
    split($2, prev_time, / --> /)
  }
  END {
    print
  }' "$f" > "${f%_overlapping.*}"_overlapfixed.srt
  done
  for f in *_overlapfixed.srt
  do ffmpeg -i "$f" "${f%.*}".vtt
  done 
  rm -f *_overlapping.srt
```
