### ISSUE TITLE
File size not updated after playback starts

### ISSUE THREAD

**Issue by jal-frezie** [mpv-player/mpv#6723]
### mpv version and platform
e.g., 0.29.1 linux 
### Reproduction steps
Play a video file while it is recording or downloading
### Expected behavior
Playback to continue until end of file is reached
### Actual behavior
Playback stops at the point where the file ended when playback started

Would it be possible to start playing a file with mpv as it starts arriving on a machine, and continue until playback 'catches up' with the end of the file?

**Comment by bitraid** [comment]
>Playback stops at the point where the file ended when playback started

That doesn't happen for every file type. For example, you can play fine a [matroska video](https://sample-videos.com/video123/mkv/720/big_buck_bunny_720p_30mb.mkv) while the file is being downloaded. The same x264 video stream in [mp4 container](https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_30mb.mp4) (with the moov atom at the end of the file) won't play at all untill the download has finished (mpv could still play the video from the url, if the server supports byte-range requests).

**Comment by jal-frezie** [comment]
You're right -- by playing the raw .ts that is delivered from the tuner, the progress bar adjusts correctly as the file size increases, but the 'time to play' figure to the right of the progress bar is wrong. That's not serious though.

**Comment by zc62** [comment]
Probably related: #6465
