### ISSUE TITLE
mpv won't open or play any media files

### ISSUE THREAD

**Issue by vexxe** [mpv-player/mpv#6725]
### mpv version and platform
v0.29.1 - Windows 10 1903 18895.1000 Insider Preview

### Reproduction steps
Double click as usual on any media files e.g. .mp3, .flac, .mkv, .mp4, etc.

### Expected behavior
Play the media files

### Actual behavior
mpv player won't open and playing the selected media files.

**Comment by CounterPillow** [comment]
Where your log file?

**Comment by bitraid** [comment]
To have mpv play videos by double clicking on the files on Windows 10, you must first register the file extensions with [mpv-install.bat](https://github.com/rossy/mpv-install) and then select mpv as the default video player from `Settings -> Apps -> Default apps`.

**Comment by Matrix8781** [comment]
> Where's your log file?
where is my log file ?     I can’t open it, nothing happens when I click
