### ISSUE TITLE
Call [profile] on main mpv.conf from filedir-conf

### ISSUE THREAD

**Issue by firewater2** [mpv-player/mpv#6729]
I'm looking for a way to group a series of settings, and then append them to an mpv.conf file.

My use-case is that I maintain two styles of subtitles, one for live-action content, and one for cartoons. My main mpv.conf specifies my default, live-action style. I then have an individual mpv.conf file next to every cartoon, which has (among other settings) the cartoon subtitle style specified, overriding then the default. The inconvenience comes when I tweak this style, since to apply it to all the cartoon files requires to go through each of those mpv.conf and modify the subtitle lines.

Is there a way to have a line in the vein of `include=cartoon.conf`, that would make updating these dynamic, and instant?

**Comment by firewater2** [comment]
Oh, apparently this exists and it's called profiles. I'm too tried to try it now, but I trust this is what I meant.

**Comment by firewater2** [comment]
Actually, I don't think it's what I want. On my main mpv.conf file I created
```
[animation]
sub-font=Open Sans Bold
sub-border-size=3
sub-blur=0
osd-font=Open Sans Bold
osd-border-size=3
osd-blur=0
```
then, on a specific video's mpv.conf I added `profile=animation`, and nothing happened.

**Comment by zc62** [comment]
You first need to write [`use-filedir-conf`](https://mpv.io/manual/master/#options-use-filedir-conf) (which is not enabled by default) in your main `mpv.conf`. Carefully read https://mpv.io/manual/master/#file-specific-configuration-files

Also, you might be interested in this script: https://github.com/fbriere/mpv-scripts/blob/master/scripts/tree-profiles.lua

**Comment by firewater2** [comment]
Hmm. I do have it enabled, yeah. However this is not exactly my case.

> For this, mpv first tries to load a mpv.conf from the same directory as the file played and then tries to load any file-specific configuration.

Meaning it will load mpv.conf next to evangelion.mkv, and then evangelion.conf for evangelion.mkv, right? Can I point it to some other file beside those two, so that evangelion.mkv loads anime.conf?

Thanks for the suggestion, but the script doesn't serve my personal case as I don't maintain a separate directory for anime and whatnot (I use "Movie"/"Series" at large). In fact, I have no commonality for these files that could be taken advantage of by an automatized approach. I do make the mpv.conf regardless of this issue, for each file, so I'd like some way to refer to the configuration file from there.

Sorry if I got it wrong, maybe I'm confused.

**Comment by zc62** [comment]
There might be some confusion. To be clear, there are three config files loaded (and in this order, I guess).
1. The **master** `mpv.conf`. I don't know your platform, `~/.config/mpv/mpv.conf` for example, in *nix. Refer to the manual if you use other OS.
2. File-specific `mpv.conf` for the files in the entire folder. For example, `~/anime/mpv.conf`.
3. File-specific config for just one file. Here we do not put it in `~/.config/mpv/`. Just in the same directory: `~/anime/evangelion.mkv.conf`

> then evangelion.conf for evangelion.mkv

Wrong. Should be `evangelion.mkv.conf`.

As very clearly written in https://mpv.io/manual/master/#file-specific-configuration-files,
> If you wish to have a configuration file for a file called 'video.avi', create a file named **'video.avi.conf'** with the file-specific options in it

Another possible error might be you accidentally put `use-filedir-conf` in `~/anime/mpv.conf`, which must be written in the **master** `mpv.conf` (`~/.config/mpv/mpv.conf`).
Then feel free to define the profiles in master `mpv.conf` or directory-specific `mpv.conf`. Call it from the file-specific config. 

I don't have any issue on calling the profile defined in higher level `mpv.conf`s. If you really do, please do not ignore the issue template, and provide a full log file.

**Comment by firewater2** [comment]
Sorry if I haven't been precise. To be clear, neither evangelion.mkv.conf, nor evangelion.conf, serves my case. I don't want file-specific configs as recalled by being under the name of the given file. I'm looking to employ a more standard method, using two files: the master mpv.conf, and the mpv.conf placed next to each video.

This is my setup:

**master** mpv.conf

```
# Window
title="${filename/no-ext}"

# Playback
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossoft
tscale=linear
video-sync=display-resample
audio-file-auto=all
sub-auto=all
demuxer-mkv-subtitle-preroll

# Subtitle
sub-font="HelveticaRoundedLTStd-BdCn"
sub-font-size=58
sub-color="#ffffff"
sub-border-size=2
sub-shadow-color="1/1/1/1"
sub-blur="20"
sub-pos=90

# OSD
osd-font="HelveticaRoundedLTStd-BdCn"
osd-font-size=58
osd-color="#ffffff"
osd-border-size=2
osd-shadow-color="1/1/1/1"
osd-blur="20"
osd-margin-y=105
osd-align-x=center

# Screenshot
screenshot-jpeg-quality=100
screenshot-template="%F %P"

# Miscellaneous
use-filedir-conf

[animation]
sub-font=Open Sans Bold
sub-border-size=3
sub-blur=0
osd-font=Open Sans Bold
osd-border-size=3
osd-blur=0
```

This is an mpv.conf I create and place next to every video:

```
aid=
sid=
sub-delay=
audio-delay=
```

It is on this second mpv.conf, that I'd like to append the profile from the first, presumably with  `profile=animation`.

**Comment by zc62** [comment]
Try to explicitly apply the profile from the command line,
```
mpv --profile=animation evangelion.mkv
```
to see if the profile really works.

Also, if you could provide a full log file, all these lengthy discussions would not have been necessary to come to a final conclusion.

**Comment by firewater2** [comment]
It does work indeed work to call a profile on master mpv.conf from a filedir one, and I didn't even need to call if by terminal. How odd, I must have made a typo of the other times I tried. Anyhow, thanks for bearing with me!
