### ISSUE TITLE
The gpu-context of Vulkan is waylandvk on Xorg.

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#6732]
### mpv version and platform

mpv 0.29.0-330-g6e4971f697 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.28.100
   libavcodec      58.52.102
   libavformat     58.27.103
   libswscale      5.4.101
   libavfilter     7.53.101
   libswresample   3.4.100
ffmpeg version: N-93894-gecc096513c

### Reproduction steps
mpv --no-config --gpu-api=vulkan "sample"
### Expected behavior
Play the movie
### Actual behavior
It crashes.
### Log file
https://0x0.st/zm6m.txt

**Comment by haasn** [comment]
Crash dump? But most likely a bug with your environment/driver/loader.

**Comment by philipl** [comment]
Pass --gpu-context=x11vk so that it doesn't try to probe wayland at all. The intention is that probing wayland will fail and it then try X11 but the segfault is probably driver specific.

**Comment by haasn** [comment]
Crash dump revealed this to actually crash in the wayland uninit function, not the wayland vulkan init function (as the log misled me to believe).

So not a driver bug, just a simple oversight by the recent wayland memory leak changes.
