### ISSUE TITLE
(libmpv/Windows) custom icon shown on start screen

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#6739]
I would like to request being able to show a custom icon on the start screen.

**Comment by Akemi** [comment]
draw one yourself like the [OSC does it](https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L2212-L2239). hell you are using libmpv just load an image file or something.

**Comment by stax76** [comment]
Loading an image file would have too many implications in my application unfortunately.

Is there a clean way to draw my icon with Lua?

**Comment by Akemi** [comment]
depending if you have a vector or a raster graphic following scripts can convert them to ASS. you can also use the "overlay-add" command to overlay raw image data.

https://github.com/TypesettingTools/AI2ASS
https://gist.github.com/SAPikachu/5711198
https://github.com/lyger/Aegisub_automation_scripts/blob/master/macros/lyger.Image2ASS.lua

**Comment by stax76** [comment]
I'll be using overlay-add, libmpv never disappoints, thanks!
