### ISSUE TITLE
Fixed Playback Speed w/o Decay to x1.0

### ISSUE THREAD

**Issue by Stannks** [mpv-player/mpv#6742]
### mpv version and platform
0.29.1
Windows 10
### Reproduction steps
Adjust playback speed via keybind to x1.5
### Expected behavior
The video plays at x1.5 speed until it is finished.
### Actual behavior
Very slowly and gradually, the player tries to get it back down to x1.0 speed. This is observed by watching the amount of time left on the video, ever increase as you watch.
<br>
I'm not sure if this is the intended behaviour for a good reason. But I'd like to know if it is possible to disable/avoid this, as I want to actually save time when watching particular videos.

**Comment by Stannks** [comment]
My bad. Plugin related...

**Comment by Akemi** [comment]
on a side note, that's why the issue template demands a log file.  please don't ignore that next time, otherwise none can really help you in such cases.
