### ISSUE TITLE
Newbie with Mac question...Seconds, not hh:mm:ss

### ISSUE THREAD

**Issue by andymilder** [mpv-player/mpv#6743]
I'm on the latest Mac OS stable release, which is 0.29.

When I press the letter "O" on my keyboard, the time pops up as hh:mm:ss:sss. This is nice, but I would love to have it just in seconds, or ss:sss.

Is that possible? I'm very slow, so any help (and great detail) is appreciated.

Thanks in advance,

Andy

### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Akemi** [comment]
nope, not on the OSC without modifying it.
