### ISSUE TITLE
Add -reuse-socket option

### ISSUE THREAD

**Issue by wjax** [mpv-player/mpv#6744]
As far as I know MPV does not support reuse socket. 
It is a useful option. Mplayer does support it.

There are multiple uses cases where it is a must. Obviously only applicable to UDP.

Can it be added? 

Regards

**Comment by wjax** [comment]
Diving into the ffmpeg code, I realized that by default, when multicast is used, socket is opened with SO_REUSEADDR.
Mpv could expose a reuse_flag that can be passed to ffmpeg.

**Comment by wm4** [comment]
You can pass options to ffmpeg with --demuxer-lavf-o or --stream-lavf-o (depending on which layer uses this).
