### ISSUE TITLE
slow performance of amdvlk vs. radv

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#6745]
Benchmark setup: Scale 4k 60fps 8 bit H.264 down to ~1440p with

 > hwdec=vaapi-copy
gpu-api=vulkan
gpu-context=x11vk
dither-depth=8
sigmoid-upscaling
linear-downscaling
correct-downscaling
cscale=ewa_lanczos
scale=ewa_lanczos
dscale=ewa_lanczossharp
deband
 >

> audio=no
untimed=yes
video-sync=display-desync
vulkan-swap-mode=immediate
osd-msg1="FPS: ${estimated-display-fps}"
 >

Resulting in
radv: ~168fps
amdvlk: ~108fps

Since games usually run fast with amdvlk these days, this a bit odd. CPU usage is low in both cases, compositor is turned off.
Likely an issue in amdvlk, but chances to get it fixed are probably higher if we could provide information about what might be wrong.

mpv log:
[output.txt](https://github.com/mpv-player/mpv/files/3228234/output.txt)

mpv 0.29.0-329-g64cdc3694e
amdvlk v-2019.Q2.4
mesa-git as of today

**Comment by laichiaheng** [comment]
Isn't RADV usually better than AMDVLK?

**Comment by aufkrawall** [comment]
Depends on the game, the amount of titles where amdvlk is faster is increasing though. And of course a difference of >50% is exceptional anyway.

**Comment by haasn** [comment]
Can you try both with `vulkan-async-transfer=no` and `vulkan-async-compute=no`?

**Comment by aufkrawall** [comment]
Setting `vulkan-async-compute=no` makes amdvlk a few percent faster, but still far away from radv.
`vulkan-async-transfer=no`leads to a slower result on both drivers. radv apparently profits by both `vulkan-async-compute` and `vulkan-async-transfer`, at least with this 8 bit video. Somehow `vulkan-async-compute` isn't beneficial with a 10 bit video (but neither hurts).

**Comment by barolo** [comment]
@aufkrawall amdvlk isn't better across the board, check this [phoronix bench amdvlk vs radv](https://lnk.skro.pl/8)

**Comment by aufkrawall** [comment]
Hm, performance is normal with the amdgpu-pro Vulkan driver, so it's probably an issue in the patched LLVM that the open amdvlk uses.

**Comment by Akemi** [comment]
if the issue still persists, please open a new issue.
