### ISSUE TITLE
Entering/exiting fullscreen while playing files disables Nvidia ULMB

### ISSUE THREAD

**Issue by kaa5** [mpv-player/mpv#6748]
### mpv version and platform
shinchiro windows build mpv 0.29.0-329-g64cdc3694e
Windows 10 1903 64bit
Nvidia driver 430.86/430.64/430.39
Monitor: Dell S2716DG @120HzULMB

### Reproduction steps
1. Turn on Nvidia ULMB (Ultra Low Motion Blur) mode on the monitor
2. Open video file in mpv
3. Enter fullscreen
4. Exit fullscreen

### Expected behavior
The monitors display setting/mode should remain unchanged.

### Actual behavior
Exiting fullscreen turns off the ULMB mode on the monitor and you have to manually turn it back on using the monitors settings menu. 
Entering fullscreen again may sometimes turn ULMB back on, but exiting fullscreen turns the mode off 100% of the time. Quitting mpv without exiting the fullscreen mode first causes this behavior as well.
This happens regardless of the config settings I've tried, for this bug report I have used the --no-config option. Tested with .mkv, .webm, .mp3 and .mp4 files on the Nvidia drivers  430.86, 430.64 and 430.39. 
This is very noticeable since the monitors brightness in ULMB mode is about 50% compared to the default display mode (or the g-sync mode for that matter).

This only happens when a file is loaded, entering/exiting fullscreen without loading or playing a file in mpv first does not change the monitors display mode.

I remember other applications that use the exclusive fullscreen mode causing the same behavior in the past, which is why I use the borderless fullscreen mode wherever I can. However this seems to be an mpv bug, entering and exiting fullscreen in other media players (VLC, MPC-HC/BE) does not cause this issue.

### Log file
https://0x0.st/zBov.txt

Edit: On second thought, this is probably the same old ULMB/exclusive fullscreen bug rather than a bug in mpv specifically. I haven't found an option to use a borderless fullscreen mode in the mpv manual, that would likely get rid of the issue.

**Comment by CounterPillow** [comment]
thanks for reporting nvidia bugs to mpv?

**Comment by rossy** [comment]
That's a strange bug. mpv's d3d11 backend actually uses borderless fullscreen. This _might_ be to do with optimisations Windows makes for borderless fullscreen apps. Try `--no-d3d11-flip`.

You could also try using a different backend, eg. `--gpu-api=vulkan`.

**Comment by kaa5** [comment]
After doing some quick testing, running mpv with --no-d3d11-flip seems to resolve the issue, Thank you!
