### ISSUE TITLE
macOS libmpv videotoolbox hardware acceleration for concurrent processes

### ISSUE THREAD

**Issue by img2tab** [mpv-player/mpv#6749]
### mpv version and platform
0.29.1
macOS 10.13.6, Intel HD Graphics 3000
Windows 10 1903, Intel HD Graphics 3000
Various Linux distros, Intel HD Graphics 3000

### Reproduction steps
Play more than one h264 video concurrently with libmpv videotoolbox hardware acceleration

### Expected behavior
All streams play with hardware acceleration

### Actual behavior
Only one stream plays with hardware acceleration, other streams report hardware acceleration is not available:
```
[   7.840][d][ffmpeg/video] h264: VideoToolbox session not available.
[   7.840][e][ffmpeg/video] h264: Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.
```
On Windows and Linux on the same hardware, all concurrent streams play with hardware acceleration (obviously not through VideoToolbox)

### More information
I've read [issue 5741](https://github.com/mpv-player/mpv/issues/5741) and it seems to say hardware acceleration on macOS is only available for a single process at a time. Is this true? Is there a way to enable libmpv videotoolbox hardware acceleration for concurrent processes?

**Comment by Akemi** [comment]
it's apparently a limit of the videotoolbox API, yes. so no it's not possible.

**Comment by img2tab** [comment]
Checked with VLC, same error: `videotoolbox decoder warning: vt session error: 'kVTVideoDecoderNotAvailableNowErr'`
Unfortunate.
