### ISSUE TITLE
Facebook videos (supported by youtube-dl) do not play on mpv anymore

### ISSUE THREAD

**Issue by pitsi** [mpv-player/mpv#6751]
### mpv version and platform
Mpv 0.29.1, ffmpeg 4.1.3 on debian testing x64 and with these options in ~/.config/mpv/mpv.conf
```
vo=vdpau,xv
hwdec=vdpau
ao=alsa
sub-codepage=iso-8859-7
sub-font="Tahoma Bold"
sub-font-size=48
stop-screensaver=yes

ytdl-format=bestvideo[height<=?720]+bestaudio/best
#ytdl-format=bestvideo[height<=?720][vcodec!=vp9]+bestaudio/best

audio-display=no
```

### Reproduction steps
Play a facebook video from a terminal like so
`mpv https://www.facebook.com/downshiftaus/videos/418766325569703/`

### Expected behavior
Video should play as usual

### Actual behavior
Video does not play, although youtube-dl seems to work as it should, "isolating" the video file and passing it to mpv.

### Log file
http://paste.debian.net/1085396/
(available for 7 days)

### Sample files
(none)

**Comment by sfan5** [comment]
> [   0.021][v][cplayer] ffmpeg library versions:
[   0.021][v][cplayer]    libavutil       56.14.100 (runtime 56.22.100)
[   0.021][v][cplayer]    libavcodec      58.18.100 (runtime 58.35.100)
[   0.021][v][cplayer]    libavformat     58.12.100 (runtime 58.20.100)
[   0.021][v][cplayer]    libswscale      5.1.100 (runtime 5.3.100)
[   0.022][v][cplayer]    libavfilter     7.16.100 (runtime 7.40.101)
[   0.022][v][cplayer]    libswresample   3.1.100 (runtime 3.3.100)

Mismatching library versions are not supported, your distro was <i>nice</i> enough to patch the check out though.
Post a log file with a properly built mpv and this issue can be reopened.

**Comment by CounterPillow** [comment]
Can confirm with a properly built mpv. Interestingly, `curl` on the same URL succeeds.

**Comment by jeeb** [comment]
@CounterPillow if curl works, then it's quite likely one of the two following:
* user agent
* FFmpeg HTTPS bug

Also check if it's using HTTP or HTTP/2 for the connection?

The user agent part should be tested first, and then it should be looked at if we can get more data on the issue.

**Comment by CounterPillow** [comment]
`--msg-level=all=trace` isn't very helpful either:

```
[ffmpeg] Opening https://video-frx5-1.xx.fbcdn.net/v/t42.1790-2/60500791_2355206054560943_48095803989819392_n.mp4?_nc_cat=1&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNDI2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfYXVkaW8ifQ==&_nc_ht=video-frx5-1.xx&oh=6e013f59072277194641fca4467436c9&oe=5CF2E618
[cplayer] Run command: disable-section, flags=64, args=[input]
[global] config path: 'fonts' -/-> '/home/fratti/.config/mpv/fonts'
[global] config path: 'fonts' -/-> '/home/fratti/.mpv/fonts'
[global] config path: 'fonts' -/-> '/usr/local/etc/mpv/fonts'
[osd/libass] Raster: FreeType 2.10.0
[osd/libass] Shaper: FriBidi 1.0.5 (SIMPLE) HarfBuzz-ng 2.5.0 (COMPLEX)
[osd/libass] Initialized
[global] config path: 'subfont.ttf' -/-> '/home/fratti/.config/mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/home/fratti/.mpv/subfont.ttf'
[global] config path: 'subfont.ttf' -/-> '/usr/local/etc/mpv/subfont.ttf'
[global] config path: 'fonts.conf' -/-> '/home/fratti/.config/mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/home/fratti/.mpv/fonts.conf'
[global] config path: 'fonts.conf' -/-> '/usr/local/etc/mpv/fonts.conf'
[osd/libass] Setting up fonts...
[ffmpeg] https: Setting default whitelist 'http,https,tls,rtp,tcp,udp,crypto,httpproxy'
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[ffmpeg] tcp: Original list of addresses:
[ffmpeg] tcp: Address 185.60.216.16 port 443
[ffmpeg] tcp: Address 2a03:2880:f02d:f:face:b00c:0:1823 port 443
[ffmpeg] tcp: Interleaved list of addresses:
[ffmpeg] tcp: Address 185.60.216.16 port 443
[ffmpeg] tcp: Address 2a03:2880:f02d:f:face:b00c:0:1823 port 443
[ffmpeg] tcp: Starting connection attempt to 185.60.216.16 port 443
[ffmpeg] tcp: Successfully connected to 185.60.216.16 port 443
[stream] Failed to open https://video-frx5-1.xx.fbcdn.net/v/t42.1790-2/60500791_2355206054560943_48095803989819392_n.mp4?_nc_cat=1&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNDI2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfYXVkaW8ifQ==&_nc_ht=video-frx5-1.xx&oh=6e013f59072277194641fca4467436c9&oe=5CF2E618.
[cplayer] Opening failed or was aborted: https://video-frx5-1.xx.fbcdn.net/v/t42.1790-2/60500791_2355206054560943_48095803989819392_n.mp4?_nc_cat=1&efg=eyJ2ZW5jb2RlX3RhZyI6ImRhc2hfdjNfNDI2X2NyZl8yM19tYWluXzMuMF9mcmFnXzJfYXVkaW8ifQ==&_nc_ht=video-frx5-1.xx&oh=6e013f59072277194641fca4467436c9&oe=5CF2E618
```

Changing https to http works. ffplay behaves like mpv here, so this is an FFmpeg HTTPS bug.

**Comment by jeeb** [comment]
@sfan5 has posted a log of it working for him as HTTPS, so while I might agree that it's quite possibly a FFmpeg bug, but it's probably not as simple as it seems :) .

**Comment by shinchiro** [comment]
Works fine here with libressl

**Comment by CounterPillow** [comment]
Looks like the deciding factor between working and not working is whether one uses an ffmpeg built with gnutls, which doesn't work. wget with gnutls works, so I'm fairly confident this is an FFmpeg+gnutls issue within FFmpeg.

**Comment by jeeb** [comment]
Since ffplay (and probably ffmpeg.c) behave similarly I think it's worthwhile to bring this to the FFmpeg side.

Will poke people a bit

@pitsi , unfortunately this seems to not be our bug. Would you like to create a bug on FFmpeg's side at trac.ffmpeg.org by explaining how to get the URL from youtube-dl and testing the URL with ffprobe or ffmpeg.c since those should share behavior?

**Comment by CounterPillow** [comment]
ffmpeg patch https://patchwork.ffmpeg.org/patch/12492/ fixes this issue in ffplay for me, which should also fix it in mpv.

**Comment by pitsi** [comment]
For the libraries part, I will ask the maintainer of deb-multimedia.org for more info and on what he can do about them. Also, I have libssl 1.1.1b installed. Could that be the issue? My distro also provides 1.1.1.c.

As for the rest, I do not know anything that would help resolve the problem so as to make a new report on trac.ffmpeg.org. If anyone wants to do it for me, please do it.

**Comment by LaserEyess** [comment]
Facebook does not serve any content on http so that's just going to redirect to https anyway. Debian builds ffmpeg with gnutls, so having a more up to date openSSL won't do much for you. I get the same results as CounterPillow when building ffmpeg with that patch, this is an ffmpeg bug.

**Comment by pitsi** [comment]
Ok so I am informing the deb-multimedia maintainer now and you can close the issue here. Thanks for your help :)

**Comment by jeeb** [comment]
@pitsi the issue seems to be with the handshake process and I have now reviewed a patch that was posted for it in March in FFmpeg.

https://patchwork.ffmpeg.org/patch/12492/

This should fix the issue.

**Comment by pitsi** [comment]
I contacted the maintainer of deb-multimedia.org and he built fresh packages of ffmpeg and its libs, applying the forementioned patch, so now the videos work as they should.

Thank you once more :)

**Comment by pitsi** [comment]
Semi-offtopic.
I found out that dailymotion videos fail to play as well, although they are parsed by youtube-dl correctly. Here is the relevant log
http://paste.debian.net/1085507/

I will open a new issue report if you decide that it different from the facebook issue.

p.s. I had not used dailymotion for 5+ years, but someone sent me that video some days ago and yesterday I had the idea to check it against mpv.

**Comment by zc62** [comment]
It's already reported. See #6675.

**Comment by marillat** [comment]
> I contacted the maintainer of deb-multimedia.org and he built fresh packages of ffmpeg and its libs, applying the forementioned patch, so now the videos work as they should.

I didn't applied the ffmpeg patch. I simply rebuild ffmpeg with openssl enabled and gnutls disabled.

Christian

**Comment by pitsi** [comment]
> > I contacted the maintainer of deb-multimedia.org and he built fresh packages of ffmpeg and its libs, applying the forementioned patch, so now the videos work as they should.
> 
> I didn't applied the ffmpeg patch. I simply rebuild ffmpeg with openssl enabled and gnutls disabled.
> 
> Christian
Thanks for the clarification. 
It works now, and that is what matters the most ;)

**Comment by CounterPillow** [comment]
>I simply rebuild ffmpeg with openssl enabled and gnutls disabled.

AFAIK this results in a non-free build, just FYI.

**Comment by mc4man** [comment]
Orig. link & any other facebook video I can find works fine with gnutls here.
mpv - git 71ad1e2
ffmpeg git-2019-04-28-3dee6c0
gnutls28 (libgnutls30
