### ISSUE TITLE
After cache recent update, prefetch-playlist does not work.

### ISSUE THREAD

**Issue by Samillion** [mpv-player/mpv#6753]
### mpv version and platform

```
Windows 10 x64 1809

mpv 0.29.0-329-g64cdc3694e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun May 19 23:01:58 DST 2019
ffmpeg library versions:
   libavutil       56.28.100
   libavcodec      58.52.101
   libavformat     58.27.103
   libswscale      5.4.101
   libavfilter     7.53.101
   libswresample   3.4.100
ffmpeg version: N-45774-gfbdb3aa179
```

### Reproduction steps
Add `prefetch-playlist=yes` and adjust cache settings in `mpv.conf` with `cache=yes` and `demuxer-max-bytes=800000KiB` only, leaving any other cache settings as default.

### Expected behavior
The next file in a local playlist would be prefetched into cache.

### Actual behavior
After the recent update that removed stream cache options and now relying on demuxer, files do not get prefetched even with the option enabled.

### Log file
https://0x0.st/zM3i.txt

**Comment by Samillion** [comment]
Updated to Windows 10 x64 1903, and mpv:

```
mpv 0.29.0-331-g4d001bb30d Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Jun  2 15:11:22 DST 2019
ffmpeg library versions:
   libavutil       56.28.100
   libavcodec      58.52.102
   libavformat     58.27.103
   libswscale      5.4.101
   libavfilter     7.55.100
   libswresample   3.4.100
ffmpeg version: N-45843-g415886588f
```

Config file: [GitHub Link](https://raw.githubusercontent.com/Samillion/mpv-conf/master/mpv.conf)

Prefetch still doesn't work. I'm honestly not sure if it's a bug or just how demuxer is supposed to work unlike stream cache or if it's that at all.

**Comment by bitingsock** [comment]
When I first wrote https://gist.github.com/bitingsock/f9a87ea158035d4a36899b559d611228
I'm certain that it was because the caching code at the time made it so prefetched files actually got cached. I soon realized that it was almost useless because the new code didn't cache. I too, noticed this regression(?) but wasn't really sure that anything had changed. 
I'm know wondering what the point of prefetching is given this regression.

**Comment by wm4** [comment]
Should be mostly trivial to fix by enabling all streams and starting readahead after opening. Not an argument to resurrect the stream cache. Prefecthing with the stream cache didn't work in many other situations (like mp4 or mkv files with header data at the end of the file).

**Comment by wm4** [comment]
Report if any problems occur or if it doesn't actually work.
