### ISSUE TITLE
MOV are played different when bt2020 is requeried

### ISSUE THREAD

**Issue by EsmeraldaQuintero** [mpv-player/mpv#6754]
### On MVP  release 20190602 by shinchiro and Windows 10 Enterprise

An MOV video could or not be played with the required color space, color transfer and color primary.

### Reproduction steps
I create a video with the next command and a tiff image of 1920x1080:
`ffmpeg.exe -f image2 -framerate 1 -i image001.tiff -c:v prores_ks -profile:v 3 -pix_fmt yuv422p10le -color_primaries bt2020 -colorspace bt2020_ncl -color_trc smpte2084 -movflags +write_colr -strict experimental -an output_bt2020.mov`

With this ffmpeg versions:
[old ffmpeg-3.2-win64-static.zip](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-3.2-win64-static.zip)
[latest ffmpeg-20190607-1e7a8b9-win64-static.zip](https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-20190607-1e7a8b9-win64-static.zip)

The result video has the next properties in both cases:
`colour_primaries_Original                : BT.2020`
`transfer_characteristics_Original        : PQ`
`matrix_coefficients_Original             : BT.2020 non-constant`
Note: I have used MediaInfo

### Expected behavior
When I play the videos in MPC(MediaPlayerClassic) they looks equals, but when I play the videos in MPV the one created with the ` ffmpeg-20190607-1e7a8b9-win64-static.zip` looks different to the one created with `ffmpeg-3.2-win64-static.zip`.

What I expected is that the BT.2020 options was applied and that's true with the video created with the old version of ffmpeg but no with the new version of ffmpeg (that video looks like in MPC).

### Actual behavior

So, the MOV videos created with the latest version of ffmpeg are not played correctly when the color transfer, color primary or color space are customized.

Note: If I try with MP4 videos the issue didn't happend, the video is played with the bt2020 options.

### Log file

I have no log file, sorry.

### Sample files

I can't provide the videos but in `Reproduction steps` section is specified how I create them.

**Comment by haasn** [comment]
I'll need either a sample clip or a log file to look at this. Some random windows binary doesn't help me.

**Comment by Akemi** [comment]
no file, no log.
