### ISSUE TITLE
MPV opens, shows a white screen, then exits.

### ISSUE THREAD

**Issue by waffleman1230** [mpv-player/mpv#6755]
I have mpv 0.29.0-331-g4d001bb30d, and I'm using the latest update on Windows 10.
Whenever I try to open MPV, it just shows a white screen for a second, and then exits.

Log @ https://shrib.com/?v=nc#MisYWA_tvpkGU1l51GIA

Thanks in advance!

**Comment by lachs0r** [comment]
Try without the config file (which is full of garbage that doesn’t even make sense).

**Comment by CounterPillow** [comment]
First of all, remove `hwdec=videotoolbox`, that's macOS specific.

Secondly, I see you're using `Intel(R) HD Graphics 630`, so I recommend that instead of trying to use vulkan you use d3d11.
