### ISSUE TITLE
File started with --start parameter automatically moves next video in playlist to --start position

### ISSUE THREAD

**Issue by matthew-stafford** [mpv-player/mpv#6756]
### Reproduction steps
I am creating a program which uses MPV to create a playlist of files. It asks mpv to start on a specific file and then uses set_property playlist and the json IPC to build the playlist. If i set the first file to use --start parameter to set the start seek position, every file in the playlist afterwards will also start at this seek position. For example, 2019-01-01T00:00:00.mp4 start at 59:00. The next file in the playlist, 2019-01-01T01:00:00 will start at 00:59:00 too which I assume is unexpected? 
### Expected behavior
Reset the --start seek position after loading file
### Actual behavior
--start position is set for every file in the playlist and cannot be unset

**Comment by qmega** [comment]
It's expected that `--start` applies to every file if you set it as a global option. You can use file-local options to set a start time for an individual file.

On the command line, this is done with `--{` and `--}`, e.g. `mpv --{ file1 --start=50 --} file2` (the --start option applies to file1 and not file2). If you're using a shell you'd have to escape them such as `--\{` and `--\}`.
If you're loading a file with the `loadfile` command, you can give it a third argument for file-local options: `{ "command": ["loadfile", "<path>", "<replace/append/append-play>", "start=50,some-other-option=..."] }`
If you're using lua scripting, you can hook `on_load` and set the property `file-local-options/start`.

**Comment by matthew-stafford** [comment]
Thank you, this wasnt clear in the documentation but your examples and solutions provided really helped and I have fixed the issue.
