### ISSUE TITLE
How to set background colour while displaying image using mpv ?

### ISSUE THREAD

**Issue by superuser789** [mpv-player/mpv#6760]
I am currently running mpv  v0.29 on my raspberry pi 3.  I  am using it to display image ::
`mpv  rpi-background=yes --image-display-duration=inf  --window-scale=1  IMAGE.jpg`

It displays the image well but the console screen is also visible, Setting background to black using "rpi-background=yes" or  "--background=#000000" does not work.
Could you guide me on how to set black background for image ?
Thanks.

**Comment by chuckn408** [comment]
I'm not quite sure what you're talking about, but when I tried   ::
`mpv rpi-background=yes --image-display-duration=inf --window-scale=1 https://avatars3.githubusercontent.com/u/30214233?s=460.png
It displays the normal white background of the image itself. Could you be a bit more specific?

**Comment by Akemi** [comment]
please open a new issue if you still have an issue.
