### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by tipiratio** [mpv-player/mpv#6761]
### mpv version and platform
0.29.1, Windows

### Reproduction steps
Open the same youtube video in mpv and vlc, check the task manager

### Expected behavior
Same resources usage while decoding same video

### Actual behavior
mpv's CPU load is 3-5 times higher, 10 times higher while moving mouse in OSC, even if video quality limited through
'''
ytdl-format="bestvideo[height<=?480][fps<=?30][vcodec!=?vp9]+bestaudio/best"
'''
and VLC's is unlimited.
Also the memory and cpu load for mpv doesn't depend on quality limit through ytdl-format - it's almost the same for 480p and 1080p.

Always thought mpv is much more lightweight without huge qt and with almost the same codecs as vlc.

**Comment by Akemi** [comment]
no log, no help.
