### ISSUE TITLE
libmpv issue on Windows

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#6762]
Maybe I'm the only libmpv user on Windows who use libmpv's built-in OSC. For me it's working fine except in very rare cases something window/message related breaks, it can be fixed easily by resizing the window for instance, very rare cases like every other day, I don't care and can't fix it anyway. There is a user who reports that he has issues more often then me. Since it's not really reproducible it can hardly be debugged.

I pass the handle of my main window to wid and libmpv creates a child window (mpv does not use a child window), this child window is created with WS_DISABLED so it's not getting user input messages. So far I simply forward various messages to the mpv child window which makes most things work, few other things require sending commands.

Because there is this bug report and I don't know what to do about it I did some investigation today and decided to try another approach, I removed the WS_DISABLED style from the mpv child window so it receives all user input, there is a problem now I probably can't overcome, when the left mouse button is down and the mouse moves the mpv child window moves because libmpv thinks it's the main window that needs to be moved.

Questions:

Is it possible that libmpv don't create a child window but use my main window like mpv?

Could libmpv be changed not to move the child window, it doesn't make sense, or even better move the parent/main instead.

Maybe I can find a way to prevent the window being moved.

https://github.com/stax76/mpv.net

**Comment by rossy** [comment]
> Is it possible that libmpv don't create a child window but use my main window like mpv?

Kind of. You can use the render_context stuff from the client API to make mpv render to your window, but it only supports OpenGL at the moment. To be a full replacement for --wid, it would have to be improved to support D3D11 and Vulkan as well.

> Could libmpv be changed not to move the child window, it doesn't make sense, or even better move the parent/main instead.

If you set window-dragging to "no", that should prevent the window from being moved. As for making the child window move the main window, that's more complicated and would probably require window hooks or something. It would probably be easier to fix the original bug that your user found and re-enable WS_DISABLED than to do that, (but it's a weird bug.)

**Comment by stax76** [comment]
That was very helpful, thanks!
