### ISSUE TITLE
libmpv threading problem with stop command

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#6767]
Maybe there is something wrong with the stop command, following (C#) code works only when using Thread.Sleep after the stop command.
```
mp.commandv("stop"); // clears the playlist
Thread.Sleep(50);
foreach (string file in files)
    mp.commandv("loadfile", file, "append"); // appends files to playlist
mp.set_property_int("playlist-pos", 0); // starts playback at pos 0
```

**Comment by Akemi** [comment]
with that kind of example it's impossible to help you.

**Comment by stax76** [comment]
I could try if it's reproducible in a JavaScript.

**Comment by stax76** [comment]
I'm not able to reproduce it in JavaScript because 'stop' will terminate mpv, is there a setting that prevents 'stop' to terminate mpv?

My use case is the following in mpv.net:

There are a couple of files in the playlist and one is currently playing,

- I want to remove all files from the playlist including the currently playing
- I want to add several files to the playlist
- I want the first file to play

right now I do it like so:

https://github.com/stax76/mpv.net/blob/master/mpv.net/mpv/mp.cs#L563

There is a user that reports having sometimes problems, it never happened to me, since I cannot reproduce it the problem can be anything.

https://github.com/stax76/mpv.net/issues/25

**Comment by Akemi** [comment]
`--force-window=yes --idle`
