### ISSUE TITLE
Key map to modify window geometry

### ISSUE THREAD

**Issue by BladeMight** [mpv-player/mpv#6776]
### mpv version and platform

0.29.0-341-gc9e7473d67
Windows 7

### Reproduction steps

Tried to map key to set geometry to 50%x50%, etc. in `input.conf`:
```conf
1 set geometry "50%x50%"
2 set geometry "100%x100%"
3 set geometry "640x360"
```

### Expected behavior

To be able to change window size by key press.

### Actual behavior

Actually pressing those keys didn't change the window size.

### Question

Is it even possible?

**Comment by BladeMight** [comment]
I've been able to make it possible to scale window size by using `window-scale` option:
```config
1 set window-scale 0.5
2 set window-scale 1.0
```
and now the only thing thats left is: to set it to desired WxH? this one:
```
3 set geometry "640x360"
```

**Comment by garoto** [comment]
`geometry` is only parsed once during init. There's no `input.conf` facilities to reposition mpv window during runtime.

https://github.com/mpv-player/mpv/issues?utf8=✓&q=is%3Aissue+sort%3Aupdated-desc+in%3Atitle+geometry

**Comment by Akemi** [comment]
duplicate of #3872.

**Comment by ThoshHub** [comment]
Hi,
was this ever resolved? 
Or are there any plans to implement this?
3872 was locked so I am unable to comment on it, this is the most recent duplicate issue so I figured I'd try my luck here

**Comment by Akemi** [comment]
the last comment on that issue should answer the question.

**Comment by porsager** [comment]
@Akemi is there any chance that the features mentioned in #3872 (now locked) could be implemented? Would you recommend a new issue to track it? If anyone is up for it, I'd be willing to pay / donate to make it happen.

**Comment by Akemi** [comment]
not impossible. feel free to open a new feature request.

**Comment by porsager** [comment]
Thanks for the quick response. Opened here https://github.com/mpv-player/mpv/issues/8379
