### ISSUE TITLE
The autoselected NVDEC or CUDA doesn't work on GeForce 820M

### ISSUE THREAD

**Issue by JpegXguy** [mpv-player/mpv#6777]
### mpv version and platform

mpv 0.29.1, Arch Linux

My NVIDIA GPU is a GeForce 820M, and while it's listed as CUDA-capable [in NVIDIA's site](https://developer.nvidia.com/cuda-gpus), under "CUDA-Enabled GeForce and TITAN Products", with a compute capability of 2.1, it doesn't seem to support NVDEC. We'll see why in a moment.

I mention this because of these 2 lines in the `hwdec` documentation of mpv:
```
cuda: | requires --vo=gpu (Any platform CUDA is available)
nvdec: | requires --vo=gpu (Any platform CUDA is available)
```

### Reproduction steps
Set `hwdec=auto`. (`vo=gpu`)
Let's use mpv to open a file encoded in H264.

### Expected behavior
Achieving hwaccel, which in my card's case is seems to be only through VDPAU.

### Actual behavior
If I use `hwdec=auto` or `hwdec=nvdec` (similar output if using `hwdec=cuda`)

```
[ffmpeg/video] h264: Cannot load cuvidGetDecodeStatus
[ffmpeg/video] h264: Failed loading nvcuvid.
[ffmpeg/video] h264: Failed setup for format cuda: hwaccel initialisation returned error.
```

That's fine by me, forcing VDPAU works (`hwdec=vdpau` or `vo=vdpau`) but I remember that it used to work with `hwdec` set to `auto`. That is, mpv would, seeing my card, select `vdpau` as the hardware decoding method of choice. Now it tries to use `nvdec` (evident by the fact that I get the same log if I use 'hwdec=nvdec') which **fails**.

Is there a way to make autodetection work in my card's case? I would just force the `hwdec=vdpau` in the config file, but I also have an intel card and I want to avoid having to specify it when running mpv or change the config every time I switch between cards.

I remember mpv working seamlessly, autoselecting `hwdec` to be `vaapi` for my intel and `vdpau` for my NVIDIA card.

**Comment by mc4man** [comment]
I believe the way it stands now if you want vdpau you need to explicitly do so. 
(- could get worse than that in the future..
Atm the only way you'd get vdpau with --hwdec= or hwdec=auto is if you build mpv without cuda-hwaccel/ffnvcodec support.

If you want cuda/nvdec then you must meet min. required driver version. Each time nv-codec-headers releases a new version it tends to up the min required based on the newer corresponding SDK version.
So if arch is using nv-codec-headers 9.0.18 then min. for linux is 418.30

**Comment by JpegXguy** [comment]
I am forced to use legacy 390xx drivers because that's where Fermi NVIDIA support ends. Maybe mpv could use vdpau for these cards?

**Comment by mc4man** [comment]
> I am forced to use legacy 390xx drivers because that's where Fermi NVIDIA support ends. Maybe mpv could use vdpau for these cards?

I don't think so, you can use any of the 4xx linux drivers. This machine i'm on right now has a 755m and uses 4.30.26 just fine.
Go here, pick your Gpu series and specific device and search, you'll see ..
https://www.geforce.com/drivers

**Comment by JpegXguy** [comment]
I'm telling you because I've tried. It's very specific in dmesg. NVIDIA is wrong if they're showing the driver as available in geforce.com. Your GPU is not Fermi, it's Kepler, so it works.

https://www.nvidia.com/object/IO_32667.html

**Comment by Doofussy2** [comment]
Try using `--gpu-api=opengl`

**Comment by JpegXguy** [comment]
> Try using `--gpu-api=opengl`

The behavior remains unchanged. It is a good idea for me to check the mpv manual though.

**Comment by JpegXguy** [comment]
Success! The autodetection problem is mentioned in the manual itself:

> nvdec is a newer implementation of CUVID/CUDA decoding, which uses the FFmpeg decoders for file parsing. **Experimental, is known not to correctly check whether decoding is supported by the hardware at all.** [...]

I found a workaround: setting `cuda-decode-device=999` (or some other wrong number, anything other than 0 in my case) prevent autodetection from selecting cuda-nvdec, falling back to vdpau on my nvidia gpu.

But this should be solved by autodetection, so I don't think the issue should be closed. This is, as mentioned, a workaround.

**Comment by philipl** [comment]
The problem is that 390.xx drivers are only supported by video sdk 8.1 and older. Your mpv binary was built against a newer sdk. If you build your own binary using the 8.1 branch of nv-codec-headers, then nvdec should work

**Comment by JpegXguy** [comment]
NVIDIA always finds a way to make things worse for linux... You don't get older chips "unsupported" on open-source drivers, which is the best. Anyhow, I don't mind using vdpau but surely mpv could detect whether nvdec is available before choosing it? I mean, it doesn't try to use vaapi for an NVIDIA GPU, does it?

**Comment by philipl** [comment]
It's because the probing mechanism doesn't account for hardware that would work except that a too new sdk version was used for the driver that's in use.

**Comment by JpegXguy** [comment]
IT does fail successfully though, so to speak. It even outputs to stderr. Maybe when it fails with an NVIDIA GPU and hwdec=auto it should try vdpau instead

**Comment by philipl** [comment]
Please attach your full log. The point is that it's not failing during probing but during the decode, when it's too late to pick a different hwaccel

**Comment by JpegXguy** [comment]
```
Playing: bbb_sunflower_1080p_60fps_normal.mp4
 (+) Video --vid=1 (*) (h264 1920x1080 60.000fps)
 (+) Audio --aid=1 (*) (mp3 2ch 48000Hz)
     Audio --aid=2 (*) (ac3 6ch 48000Hz)
File tags:
 Artist: Blender Foundation 2008, Janus Bager Kristensen 2013
 Comment: Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
 Composer: Sacha Goedegebure
 Genre: Animation
 Title: Big Buck Bunny, Sunflower version
[ffmpeg/video] h264: Cannot load cuvidGetDecodeStatus
[ffmpeg/video] h264: Failed loading nvcuvid.
[ffmpeg/video] h264: Failed setup for format cuda: hwaccel initialisation returned error.
VO: [gpu] 1920x1080 yuv420p
AO: [pulse] 48000Hz stereo 2ch float
AV: 00:00:01 / 00:10:34 (0%) A-V:  0.007 Dropped: 4
[osd/libass] fontselect: Using default font family: (Source Sans Pro, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, DejaVuSans
[osd/libass] fontselect: Using default font family: (Source Sans Pro, 700, 0) -> /usr/share/fonts/TTF/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold
```

**Comment by philipl** [comment]
Please get a full verbose log, so we can see the probe output (not that I expect any surprises).

But yes, the whole point of probing is to decide what is a working, or not working, hwdec. In case case of cuda/nvdec, it might fail in probing because the hardware lacks any cuda capabilities, for example. If that happened, mpv would note that nvdec doesn't work but that vdpau does and then it would probably do the right thing.

here the failure happens when loading the cuvid symbols - there's a new symbol that isn't present in the older drivers. If mpv and ffmpeg had been built with the right sdk that matches your driver, it wouldn't be looking for that symbol and things would work. But the new SDK assumes a new enough driver and so you get this failure.

**Comment by JpegXguy** [comment]
How verbose? Is one `-v` enough?

**Comment by philipl** [comment]
One `-v` is enough.

**Comment by JpegXguy** [comment]
```
[cplayer] Command line options: '-v' 'bbb_sunflower_1080p_60fps_normal.mp4'
[cplayer] mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri Apr 19 20:49:51 UTC 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.22.100
[cplayer]    libavcodec      58.35.100
[cplayer]    libavformat     58.20.100
[cplayer]    libswscale      5.3.100
[cplayer]    libavfilter     7.40.101
[cplayer]    libswresample   3.3.100
[cplayer] ffmpeg version: n4.1.3
[cplayer] 
[cplayer] Configuration: ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --enable-libsmbclient --enable-tv --enable-zsh-comp
[cplayer] List of enabled features: 52arch alsa asm atomics audio-input build-date caca cdda cplayer cplugins cuda-hwaccel debug-build drm drmprime dvbin dvdnav dvdread-common egl-drm egl-helpers egl-x11 fchmod ffmpeg ffnvcodec gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm libmpv-shared librt libsmbclient libv4l2 linux-fstatfs lua optimize oss-audio plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rubberband shaderc shaderc-shared stdatomic tv tv-v4l2 uchardet vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 videodev vt.h vulkan wayland wayland-protocols x11 xv zlib zsh-comp
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] Reading config file /home/leo/.config/mpv/mpv.conf
[cplayer] Waiting for scripts...
[stats] script-opts/stats.conf not found. 
[stats] lua-settings/stats.conf not found. 
[ytdl_hook] script-opts/ytdl_hook.conf not found. 
[ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[osc] script-opts/osc.conf not found. 
[osc] lua-settings/osc.conf not found. 
[cplayer] Done loading scripts.
[cplayer] Playing: bbb_sunflower_1080p_60fps_normal.mp4
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[ifo] Opening bbb_sunflower_1080p_60fps_normal.mp4
[ifo_dvdnav] Opening bbb_sunflower_1080p_60fps_normal.mp4
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.5.3 (COMPLEX)
[osd/libass] Setting up fonts...
[bdmv/bluray] Opening bbb_sunflower_1080p_60fps_normal.mp4
[file] Opening bbb_sunflower_1080p_60fps_normal.mp4
[demux] Trying demuxers for level=normal.
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[cplayer] Opening done: bbb_sunflower_1080p_60fps_normal.mp4
[find_files] Loading external files in .
[cplayer] Running hook: ytdl_hook/on_preloaded
[lavf] select track 0
[lavf] select track 1
[cplayer]  (+) Video --vid=1 (*) (h264 1920x1080 60.000fps)
[cplayer]  (+) Audio --aid=1 (*) (mp3 2ch 48000Hz)
[cplayer]      Audio --aid=2 (*) (ac3 6ch 48000Hz)
[display-tags] File tags:
[display-tags]  Artist: Blender Foundation 2008, Janus Bager Kristensen 2013
[display-tags]  Comment: Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
[display-tags]  Composer: Sacha Goedegebure
[display-tags]  Genre: Animation
[display-tags]  Title: Big Buck Bunny, Sunflower version
[vo/gpu] Probing for best GPU context.
[vo/gpu/opengl] Initializing GPU context 'x11probe'
[vo/gpu/x11] X11 opening display: :0
[vo/gpu/x11] X11 running at 1366x768 (":0" => local display)
[vo/gpu/x11] Detected wm supports NetWM.
[vo/gpu/x11] Detected wm supports FULLSCREEN state.
[vo/gpu/x11] Detected wm supports ABOVE state.
[vo/gpu/x11] Detected wm supports BELOW state.
[vo/gpu/x11] Display 0 (eDP-1-1): [0, 0, 1366, 768] @ 60.006681 FPS
[vo/gpu/x11] Current display FPS: 60.006681
[vo/gpu/opengl] GLX chose FB config with ID 0x17e
[vo/gpu/opengl] GLX chose visual with ID 0x98
[vo/gpu/opengl] Creating OpenGL 4.4 context...
[vo/gpu] GL_VERSION='4.4.0 NVIDIA 390.116'
[vo/gpu] Detected desktop OpenGL 4.4.
[vo/gpu] GL_VENDOR='NVIDIA Corporation'
[vo/gpu] GL_RENDERER='GeForce 820M/PCIe/SSE2'
[vo/gpu] GL_SHADING_LANGUAGE_VERSION='4.40 NVIDIA via Cg compiler'
[vo/gpu] Loaded extension GLX_SGI_swap_control.
[vo/gpu] Loaded extension GLX_SGI_video_sync.
[vo/gpu] Loaded extension GL_NV_vdpau_interop.
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] Assuming 60.006681 FPS for display sync.
[vd] Container reported FPS: 60.000000
[vd] Codec list:
[vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     h264_v4l2m2m (h264) - V4L2 mem2mem H.264 decoder wrapper
[vd]     h264_cuvid (h264) - Nvidia CUVID H264 decoder
[vd] Opening decoder h264
[vd] Looking at hwdec h264-nvdec...
[vo/gpu] Loading hwdec driver 'vaapi-egl'
[vo/gpu] Loading failed.
[vo/gpu] Loading hwdec driver 'cuda-nvdec'
[vo/gpu] Loading hwdec driver 'vdpau-glx'
[vo/gpu] Loading hwdec driver 'drmprime-drm'
[vo/gpu/drmprime-drm] Failed to retrieve DRM fd from native display.
[vo/gpu] Loading failed.
[vd] Trying hardware decoding via h264-nvdec.
[vd] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[vf] User filter list:
[vf]   (empty)
[ad] Codec list:
[ad]     mp3float (mp3) - MP3 (MPEG audio layer 3)
[ad]     mp3 - MP3 (MPEG audio layer 3)
[ad] Opening decoder mp3float
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: mp3float (MP3 (MPEG audio layer 3))
[af] User filter list:
[af]   (empty)
[cplayer] Starting playback...
[vd] Pixel formats supported by decoder: vdpau cuda vaapi_vld yuv420p
[vd] Codec profile: High (0x64)
[vd] Requesting pixfmt 'cuda' from decoder.
[ffmpeg/video] h264: Cannot load cuvidGetDecodeStatus
[ffmpeg/video] h264: Failed loading nvcuvid.
[ffmpeg/video] h264: Failed setup for format cuda: hwaccel initialisation returned error.
[vd] Pixel formats supported by decoder: vdpau vaapi_vld yuv420p yuv420p
[vd] Codec profile: High (0x64)
[vd] Requesting pixfmt 'yuv420p' from decoder.
[vd] Falling back to software decoding.
[vd] Detected 4 logical cores.
[vd] Requesting 5 threads for decoding.
[vd] Using software decoding.
[vd] Decoder format: 1920x1080 yuv420p auto/auto/auto/auto/auto CL=mpeg2/4/h264 (auto 0.000000/0.000000/0.000000)
[vf] [in] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] (disabled)
[vf] [autorotate] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [autorotate] (disabled)
[vf] [convert] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [convert] (disabled)
[vf] [out] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[cplayer] VO: [gpu] 1920x1080 yuv420p
[cplayer] VO: Description: Shader-based GPU Renderer
[vo/gpu] reconfig to 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vo/gpu/x11] not waiting for MapNotify
[vo/gpu] Resize: 1173x660
[vo/gpu] Window size: 1173x660
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 1173x660
[vo/gpu] Video scale: 0.610938/0.611111
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
[vo/gpu] Texture for plane 0: 1920x1080
[vo/gpu] Texture for plane 1: 960x540
[vo/gpu] Texture for plane 2: 960x540
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] DR enabled: yes
[vo/gpu] Dither to 8.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, DejaVuSans
[cplayer] first video frame after restart shown
[af] [in] 48000Hz stereo 2ch floatp
[af] [userspeed] 48000Hz stereo 2ch floatp
[af] [userspeed] (disabled)
[af] [convert] 48000Hz stereo 2ch floatp
[ao] Trying audio driver 'pulse'
[ao/pulse] requested format: 48000 Hz, stereo channels, floatp
[ao/pulse] Library version: 12.2.0
[ao/pulse] Proto: 32
[ao/pulse] Server proto: 4294967295
[ao/pulse] Channel layouts:
[ao/pulse]  - #fl
[ao/pulse]  - #fr
[ao/pulse]  - #fc
[ao/pulse]  - #lfe
[ao/pulse]  - #bl
[ao/pulse]  - #br
[ao/pulse]  - #flc
[ao/pulse]  - #frc
[ao/pulse]  - #bc
[ao/pulse]  - #sl
[ao/pulse]  - #sr
[ao/pulse]  - #tc
[ao/pulse]  - #tfl
[ao/pulse]  - #tfc
[ao/pulse]  - #tfr
[ao/pulse]  - #tbl
[ao/pulse]  - #tbc
[ao/pulse]  - #tbr
[ao/pulse] result: stereo
[ao/pulse] device buffer: 4800 samples.
[ao/pulse] using soft-buffer of 9600 samples.
[cplayer] AO: [pulse] 48000Hz stereo 2ch float
[cplayer] AO: Description: PulseAudio audio output
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 48000Hz stereo floatp -> 48000Hz stereo float
[af] [out] 48000Hz stereo 2ch float
[cplayer] starting audio playback
[cplayer] playback restart complete
[vo/gpu/x11] Disabling screensaver.
[osd/libass] fontselect: (mpv-osd-symbols, 400, 0) -> mpv-osd-symbols-Regular, 0, mpv-osd-symbols-Regular
[vo/gpu] Reallocating OSD texture to 2048x128.
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.5.3 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, DejaVuSans
[osd/libass] fontselect: Using default font family: (Source Sans Pro, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, DejaVuSans
[osd/libass] fontselect: (Source Sans Pro, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, DejaVuSans
[osd/libass] fontselect: Using default font family: (Source Sans Pro, 700, 0) -> /usr/share/fonts/TTF/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold
[osd/libass] fontselect: (Source Sans Pro, 700, 0) -> /usr/share/fonts/TTF/DejaVuSans-Bold.ttf, 0, DejaVuSans-Bold
[vo/gpu] Reallocating OSD texture to 1024x512.
[cplayer] Set property: pause -> 1
[vo/gpu/x11] Enabling screensaver.
[cplayer] EOF code: 5  
[ad] Uninit decoder.
[vd] Uninit decoder.
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Quit)
[ytdl_hook] Exiting...
[osc] Exiting...
[stats] Exiting...
[ao/pulse] draining...
[vo/gpu/x11] uninit ...
```

**Comment by philipl** [comment]
Yeah, that's all as expected. Are you in a position to recompile and try with the right SDK version?

**Comment by JpegXguy** [comment]
So I used the package[ ffnvcodec-headers8.1](https://www.archlinux.org/packages/community/any/ffnvcodec-headers8.1/).
Compiled mpv once, result: no cuda backend at all available in `-v`, straight to vdpau

Then I modified the PKGBUILD of `ffnvcodec-headers8.1` to remove the patch that changes the directory where the headers get installed (so they look normal)
Compiled mpv, got cuda backend, but now the same error happens.

**Comment by philipl** [comment]
Yes. You need to build ffmpeg with the 8.1 headers. That's actually where the usage is coming from. (In fact, I suspect that if you only downgraded for ffmpeg and not for mpv, you'd get away with it, but obviously I would not recommend it)

**Comment by JpegXguy** [comment]
So I leave everything stock, and I only recompile ffmpeg with the 8.1 headers installed?

**Comment by philipl** [comment]
Yes, but like I said, you should use the recompiled mpv too to ensure you don't see other potential problems. And you already did it.

**Comment by JpegXguy** [comment]
UPDATE: After recompiling ffmpeg only, with the 8.1 headers **nvdec works**. I'm actually using the normal mpv (but I do have the one I compiled available for install. huh.

How cool would it be if there was an ffmpeg package available for this (I mean, the 8.1 headers do seem to exist as another package)

**Comment by Akemi** [comment]
already resolved.

**Comment by JpegXguy** [comment]
Unless some commit changed things, it's not resolved. It might be wontfix

**Comment by Akemi** [comment]
sry if i misunderstood something while grooming. but wasn't you issue resolved by recompiling ffmpeg with the right headers?

**Comment by JpegXguy** [comment]
It is more of an NVIDIA problem or an ffmpeg one than an mpv problem I guess. I won't be recompiling mpv for a card that I don't use that much, I use the Intel one most of the time. i'll stay with the workaround
