### ISSUE TITLE
is it possible to add a key binding using the client API?

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#6778]
Hello,

there is a user of mpv.net who wants to add a key binding with dotnet using the client API. I tried to achieve this and think it's only possible by generating and running JavaScript code and then communicate between JavaScript and dotnet via script-message command and client-message event, is there not an easier way?

**Comment by avih** [comment]
"easier" is relative. The lua and js code for key binding don't do any magic, they simply define the `mp.add_key_binding` functions as wrapper around other mpv commands, and use script messages to handle the callbacks. E.g. the JS binding is: https://github.com/mpv-player/mpv/blob/master/player/javascript/defaults.js#L141

Whether or not it's easier for you to utilize existing lua/js code and interface it to your dotnet thingy, or duplicate the wrapper yourself in dotnet - is up to you.

**Comment by stax76** [comment]
In defaults.js I found the command define-section and enable-section, I will try that, thanks.

**Comment by stax76** [comment]
Works great, thanks again!

**Comment by avih** [comment]
You're welcome.

Note that the `define-section` interface is subject to change: https://mpv.io/manual/master/#input-commands-that-are-possibly-subject-to-change , so if it does, your code might break (and similarly, the internal lua and js key bindings code would need to change as well).

**Comment by stax76** [comment]
Do you know why it might change?

**Comment by avih** [comment]
No, but I guess that whoever wrote it thought that it's not the cleanest interface and that in the future it could be replaced by something else. But that's a guess.

**Comment by Akemi** [comment]
i guess that was resolved.
