### ISSUE TITLE
I can't use my mouse to click on the osc anymore if mpv-webm is in my scripts.

### ISSUE THREAD

**Issue by ChocoBar9** [mpv-player/mpv#6779]
ver. 2.0.0.0 (mpv-x86_64-20181230-git-d6d6da4) Win10

Since the people who made the script weren't of any help I thought I'd ask here.  I recently added mpv-webm to my setup and it works and everything but the problem is now I can't access my osc with my mouse anymore, it pops up but I can't move the cursor or pause and play it. Tried updating the mpv.exe and it still won't work.
[log.txt](https://github.com/mpv-player/mpv/files/3335649/log.txt)

**Comment by garoto** [comment]
You have WAAAY too many scripts being loaded by default. It's your job to figure it out which script does OSC related interactions and go from there.

**Comment by Akemi** [comment]
update mpv. disable all scripts (besides the one you want to use) and use --no-config for testing.
