### ISSUE TITLE
Request - Need a Simple Lua Script

### ISSUE THREAD

**Issue by mortyobnoxious** [mpv-player/mpv#6780]
Hi, I know nothing about lua. I need a simple code (I believe it's simple), but I can't even understand lua tutorials on Youtube.
It would be great if someone helps me.

I have file names like this. This is standard btw. All the files are like this:
`Shaft.2019.1080p.tt4463894.mkv`

What I want is to

- press a key (`o` for example)
- get `tt4463894` this part from the file name
- create multiple URLs like this `https://www.imdb.com/title/tt4463894`
- open it with default browser

**Comment by CounterPillow** [comment]
So let me get this straight:

1. You are asking for a script very specific to your use-case that has no benefit to the wider mpv community,
2. this script shall be designed according to your specifications,
3. you are doing this to offload work from yourself.

This sounds an awful lot like you're trying to contract somebody to write code just for you. So, how much are you paying?

**Comment by mortyobnoxious** [comment]
I tried but couldn't figure lua out. This was the last resort.

You are right, though. Sorry for the inconvenience. Closing it.
