### ISSUE TITLE
left time

### ISSUE THREAD

**Issue by Vahid-Peivandi** [mpv-player/mpv#6783]
how to set permanently left time config all video show me all time video not negative left time and decrease that?
![Screenshot at 2019-07-01 09:05:49](https://user-images.githubusercontent.com/25903079/60410908-a46b0480-9bdf-11e9-81d3-aacf443d6571.png)
![Screenshot at 2019-07-01 09:05:56](https://user-images.githubusercontent.com/25903079/60410910-a46b0480-9bdf-11e9-9bda-ac75a4bf051b.png)

**Comment by Akemi** [comment]
https://github.com/mpv-player/mpv/blob/master/DOCS/man/osc.rst

`timetotal=yes` in `script-opts/osc.conf` or `script-opts=osc-timetotal=yes` in `mpv.conf`.
