### ISSUE TITLE
HEVC lags on Ubuntu 19.04

### ISSUE THREAD

**Issue by Agahx** [mpv-player/mpv#6785]
### mpv version and platform
mpv 0.29.1 on Ubuntu 19.04 (latest 5 kernel and everything else is up-to-date from repositories)
CPU Intel Core i7
RAM 8Gb
HDD

### Reproduction steps
Open MKV container with HEVC video inside and wait for about 4-5 minutes to start seeing lags. Wait 10 minutes to see even worse lags.
If you press "f" button twice (exit full screen and then enter fullscreen) - lag "timer" flushes, lags disappears but then re-appears after same time.

### Expected behavior
Smooth playback from start to finish

### Actual behavior
Video starts lagging after about 3-4-5 minutes of playback and becomes worse every minute. By the 11th minute it looks like a slideshow.

### Log file
https://0x0.st/z_Ja.txt

### Sample files
https://www.sendspace.com/file/mpx2r3
(link valid for 30 days)

**Comment by qyot27** [comment]
Right there in the log file:
```
[   0.206][v][vd] No hardware decoding requested.
[   0.206][v][vd] Using software decoding.
```

Turn on hardware decoding.

**Comment by stumpedatwork** [comment]
The GeForce GT 525M predates the HEVC standard.

**Comment by Agahx** [comment]
1. When I configured MPV before building it both vdpau libraries and nv-codec-headers were found, so I suppose hw decoding is always on.
Yes, according to Wikipedia GT525M has no HEVC acceleration.
2. --framedrop=vo works! 
Can I ask what exactly this option does? And how to make all files I open from Nautilus with double-click to use this option?

**Comment by Hrxn** [comment]
> And how to make all files I open from Nautilus with double-click to use this option?

Adjust your [configuration files](https://mpv.io/manual/master/#configuration-files) accordingly.

> Can I ask what exactly this option does? 

Dropping frames at the output? Not trying to render them in the first place?

**Comment by Agahx** [comment]
> Dropping frames at the output? Not trying to render them in the first place?
How this `--framedrop=vo` chooses which frames to drop and which to render? What's the algorithm?
