### ISSUE TITLE
geometry on raspbian 9

### ISSUE THREAD

**Issue by koyri** [mpv-player/mpv#6787]
### mpv version and platform
mpv 0.29.0 on Raspbian 9.9
Raspberry Pi 3B

### Reproduction steps
Tried to resize the window with video. The command looked like:
mpv --geometry=50%+10+10 /video/adress.mp4

### Expected behavior
As said in geometry option description, option value 50%+10+10 is supposed to set the video window to half the screen widths, and positions it 10 pixels below/left of the top left corner of the screen.

### Actual behavior
Video plays in fullscreen mode, no effect on it's window size or position

### Log file
https://paste.ofcode.org/LLY8TQtQ9WigMxbzQM8ab4

**Comment by lachs0r** [comment]
Do not use `--vo=rpi` if you need window management to work. The rpi video output uses the MMAL API, which bypasses any window manager. It is strongly recommended to use the default gpu video output instead.

If you are not using a window manager, the only way to get the desired behavior is to use the gpu VO and the video-zoom/pan options, or by inserting video filters for which the RPI is too slow.

If only the rpi video output is fast enough to play without judder, congratulations: You have wasted good money on an extremely bad computer.

**Comment by koyri** [comment]
Thanks for the answer. Could you please explain, if I will compile actual version of MPV with default options, will I be able to use window manager related options (i.e. geometry) and hardware accelerated decoding on Raspberry PI? Or probably you could give any recommendation on better choice of SBC to work with MPV?

**Comment by Gusar321** [comment]
The geometry setting should actually work with --vo=rpi. It's just that, depending on the version of mpv, it'll default to fullscreen. But then, just pressing "f" while mpv is running should do the trick. Or, much better, add --fs=no to the command-line.

Might also be possible that only some geometry commands work. Try this, I know for a fact this works: --vo=rpi --fs=no --geometry=+10+10 --autofit=50%-50%

**Comment by CounterPillow** [comment]
>It's just that, depending on the version of mpv, it'll default to fullscreen.

What?

**Comment by Gusar321** [comment]
> What?

https://github.com/mpv-player/mpv/commit/1aa2ae5404d134815eddcb3f146a9c1f8bbfc2e9

**Comment by CounterPillow** [comment]
This has been removed since 0.23 in https://github.com/mpv-player/mpv/commit/a8b8295f8d15b12d95ae25827831c4fc05a53bfa, so it doesn't apply to the OP.
