### ISSUE TITLE
[MacOS] How to keep mpv open when I close the video?

### ISSUE THREAD

**Issue by elsonwx** [mpv-player/mpv#6790]
I want the mpv player keep open when I close then video (with shortcut `q` or `command+q`) for opening next video file more quickly.

Is there any way to do this?

**Comment by Akemi** [comment]
yes, read the manual.

for command+q you have to map the menu item to another shortcut first with System Preferences > Keyboard > Shortcut. afterwards you can map your desired command to it in input.conf. same goes for q.

https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst

**Comment by elsonwx** [comment]
I want to keep mpv open when I close video.
Not care the quit shortcut.

**Comment by deus0ww** [comment]
@Akemi I think the OP ment keeping the MPV process running without a window. Is there a way to do that?

**Comment by Akemi** [comment]
the OP said he doesn't want mpv to quit when hitting the q or cmd+q. to quote him:
> I want the mpv player keep open when I close then video (**with shortcut q or command+q**).

@elsonwx dunno how you don't care about the shortcuts if you explicitly asked for them? maybe make yourself more clear. also read the fucking manual really,  `--keep-open=always`.

**Comment by elsonwx** [comment]
I have tried `--keep-open` and `--force-window` before commit this issue,it seems not my expect.
![](https://img.elsonwx.com/result20190709.gif)

**Comment by Akemi** [comment]
i love to repeat myself.

q, cmd+w or cmd+q are all bound to the quit command. hence mpv always quits even with keep-open etc. somehow you have to be able to close it after all.

like i said, you have to unbind the quit command from those keys or bind them to, for example 'stop' ([stop will clear the current playlist and stops playback](https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst), example `q stop` in input.conf). in combination with `--idle`  (and possibly `--force-window`), mpv will not close the current instance (q in that example), but rather just stops playback and clears the playlist.

if you want something else make yourself clear.

and for fucks sake, it's not so hard to read the manual yourself. i even linked both resources.

**Comment by elsonwx** [comment]
@Akemi Thanks for your patience.
`q stop`  in the input.conf and `idle=yes` in the mpv.conf works like a charm.
And `force-window=no` can hide the idle window.
I should read the manual more patience.
And I will enhance my English study in the future.

**Comment by elsonwx** [comment]
This my final configuration.
It may be helped for who encounter this issue later.
`input.conf`
```
q stop; set fullscreen no
CLOSE_WIN stop;set fullscreen no
```
`mpv.conf`
```
idle=yes
force-window=no
```
