### ISSUE TITLE
Using --cache=auto, the cache is not used for streaming.

### ISSUE THREAD

**Issue by mpvtester** [mpv-player/mpv#6792]
mpv-x86_64-2019**0316**-git-dd83b66.7z (windows 10 pro 64bit)

From this version, the default **--cache=auto** no longer uses the cache for streaming, and some streaming videos are now stuck.

Also, it seems that the following cache options have been removed from this version.

**--cache=<kBytes.>
--cache-default=<kBytes|no>**

Why did you delete it?

If **--cache=yes**, local files will also use the cache, and will use a large cache.

**Comment by sfan5** [comment]
The stream cache was removed in favor of the demuxer cache:
https://github.com/mpv-player/mpv/blob/master/DOCS/interface-changes.rst

**Comment by mpvtester** [comment]
I tested it.
The behavior is different from the past Ver., But it was good to solve it.

------------------------------------

--demuxer-readahead-secs=**1** (default)
When the seek and playback were repeated many times, the only video sometimes stopped periodically after the seek. **Default is very bad for me**.

--demuxer-readahead-secs=**2**
The video has not stopped repeatedly. However, sometimes there is only one stop after the seek. But because it is only once, this is usable. **I use this. good**.

--cache=auto option (ver.20190310)
The only video does not stop after the seek. But sometimes both video and audio could stop for a moment. good.

------------------------------------

**video URL and commands:**
mpv --ytdl-format="bestvideo[height<=?720]+bestaudio[ext=m4a]" https://www.youtube.com/watch?v=37uNY_1smyo

------------------------------------

**Memo:**

--demuxer-readahead-secs=**1**

"**Dropped:**" will **increase** after this

> [cplayer] Audio/Video desynchronisation detected! Possible reasons include too slow
> [cplayer] hardware, temporary CPU spikes, broken drivers, and broken files. Audio
> [cplayer] position will not match to the video (see A-V status field).

--demuxer-readahead-secs=**2**

"**Dropped:**" **does not increase**. Drop only once.
