### ISSUE TITLE
mpv abnormal exit or crash

### ISSUE THREAD

**Issue by toiron** [mpv-player/mpv#6793]
### mpv version and platform
mpv v0.29.1
windows10 1903 x64
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases
https://github.com/toiron/setest/blob/master/denyofservice.wav
### Reproduction steps
opening https://github.com/toiron/setest/blob/master/denyofservice.wav remotely or locally with a player will cause an abnormal exit.
### Expected behavior
opening https://github.com/toiron/setest/blob/master/denyofservice.wav remotely or locally with a player will cause an abnormal exit.
### Actual behavior
opening https://github.com/toiron/setest/blob/master/denyofservice.wav remotely or locally with a player will cause an abnormal exit.
### Log file
https://github.com/toiron/setest/blob/master/output.txt
Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files
https://github.com/toiron/setest/blob/master/output.txt
Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
I don't think it's an abnormal exit when you feed mpv a broken file and mpv refuses to play it due to it being a broken file.

If the file is actually valid, which I doubt, you can file an issue against ffmpeg as ffprobe fails to identify it.
