### ISSUE TITLE
How to enable motion interpolation in mpv on Windows ?

### ISSUE THREAD

**Issue by LightSunChen** [mpv-player/mpv#6795]
Hi all,

I put these lines on mpv.conf but I didn't see any difference, am I missing something ?
interpolation=yes
video-sync=display-resample
tscale=oversample

Thanks

**Comment by Doofussy2** [comment]
Is that your entire mpv.conf?

**Comment by zc62** [comment]
In most cases you shouldn't see obvious differences, as `tscale=oversample` is meant to reproduce sharp images with the least smoothness. See https://github.com/mpv-player/mpv/wiki/Interpolation `tscale=oversample` is the "smoothmotion" mentioned there. The idea is to reduce the motion judder produced by 3:2 pulldown when playing a 24fps video on a 60Hz screen. If you can't notice any motion judder with interpolation disabled, well, then you shouldn't expect any difference when you enable it. Motion judder might also be hard to tell with untrained eyes.

Other `tscale` settings might produce smoother motions but also increase blur. See #2685 for comparisons. Keep in mind that the motion interpolation methods implemented in mpv are different from others that you might know, such as SVP, AFM, mvtools, etc.
