### ISSUE TITLE
EDL doesn’t work with CRLF line endings

### ISSUE THREAD

**Issue by Lypheo** [mpv-player/mpv#6798]
### mpv version and platform

mpv 0.29.0-88-g317d3ac266
Windows 10

### Reproduction steps
Create an EDL file using CRLF line breaks, such as https://0x0.st/zL5L.txt, and try to play it with ``mpv edl://foo.edl``.
### Expected behavior
The edl is parsed and played correctly.
### Actual behavior
mpv throws this error:
``EDL: Could not open source file 'foo.edl'.
No video or audio streams selected.``
### Log file
https://pastebin.com/S5B62aG4

**Comment by Hrxn** [comment]
Correct me if I'm wrong, but the man page specifically mentions that EDL works with `LF` endings only.

**Comment by Lypheo** [comment]
You’re right, I missed that. I still think this is a unnecessary restriction though.
