### ISSUE TITLE
Changing default OSC from remaining time to total time

### ISSUE THREAD

**Issue by foguetes** [mpv-player/mpv#6799]
I'm running the latest version of mpv on Windows 10. By default the OSC shows the remaining time of the file. I have to left click it to change it to the total time.

Anyone knows what parameters needs to be added to the mpv.conf file to change the default to total time?

**Comment by CounterPillow** [comment]
Please see the manual about the OSC: https://mpv.io/manual/master/#on-screen-controller

put `timetotal=yes` into `script-opts/osc.conf`.
