### ISSUE TITLE
Play paused audio after changing volume plays a short burst at the previous volume

### ISSUE THREAD

**Issue by alex-tee** [mpv-player/mpv#6807]
### mpv version and platform
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Apr 19 20:49:51 UTC 2019
Parabola GNU/Linux-libre

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
play an audio at 100% volume, pause, lower to 30%, play

### Expected behavior
audio starts playing at 30%

### Actual behavior
audio plays a short burst at 100% and then continues to 30%

### Log file

Make a log file made with -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

### Sample files
Any mp3 file

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
AFAIK this is because at that point, the audio is already in the AO buffer, but this depends on the audio output I believe, so it would be helpful if you actually provided a log file like the issue template encouraged you to do.

**Comment by sfan5** [comment]
This has been a known "bug" on certain platforms (Linux/PulseAudio) since the removal of softvol=no, see also #5705.
If you prefer the old behaviour, you can get it back by adding volume keybinds that modify `ao-volume` and `ao-mute` instead.
