### ISSUE TITLE
software decoding performance worse after upgrade to Debian Buster

### ISSUE THREAD

**Issue by poisonsnak** [mpv-player/mpv#6809]
I just upgraded a couple of slower computers from Debian Stretch to Buster, and along with a bunch of other packages, mpv was upgraded from 0.23.0 to 0.29.1.  One of the computers can no longer play videos in software decoding that it used to be able to. GPU performance is unchanged.  I would just use hardware decoding, but I have files that won't play with hwdec.

Computer that has problems: Intel NUC7CJYH (J4005) (2C/2T 2.7GHz) with 8GB RAM
Computer with no problems: Intel m3-6Y30 (2C/4T 2.2GHz) with 8GB RAM

Playing h264 480p video on the NUC uses 70% CPU. 720p uses 190% and frames are dropped.  On the m3, 480p uses 40%, 720p uses 55%, 1080p uses 70%, no frame drops.  Back on the NUC, files that can be played with hwdec play smoothly when it's turned on (1080p, 10% CPU, no drops)

They both have the same mpv.conf (I've included it with my log below), the NUC used to use spline36 for scaling since it has a faster GPU, but I changed it to bilinear just to see with no improvement.

I checked and the CPU in the NUC is turboing up to 2.7GHz properly.  I'd been using the kernel and intel microcode patches from stretch-backports so I was already running that part of my system on buster, basically, so I don't think there's an issue there.

I know a lot happens with a distro upgrade, ffmpeg was upgraded of course, but I thought this would be a good place to start.  Thanks in advance for any advice.

### mpv version and platform
0.29.1,  Debian Buster
### Reproduction steps
play a file with hwdec turned off (or a file that can't be played with hwdec)
### Expected behavior
smooth playback
### Actual behavior
tons of frame drop
### Log file
http://0x0.st/z9VW.txt

**Comment by sfan5** [comment]
> I know a lot happens with a distro upgrade, ffmpeg was upgraded of course,

That's where you should look first.
You can test ffmpeg's decoding speed using `ffmpeg -benchmark -i file.mp4 -f null -`, `rtime` is the wall time spent in total.

**Comment by poisonsnak** [comment]
Thanks for the quick reply.  I ran the benchmark and for a 1080p video (the one I submitted the log for) it runs at 159 fps, using 185% CPU. rtime=17.810s for a 2 minute video.  So I guess this means ffmpeg isn't the problem? I've also tried turning subtitles off for videos that have them, but it didn't help.

**Comment by CounterPillow** [comment]
Does it drop any frames with `--vo=null`?

**Comment by haasn** [comment]
Try `vd-lavc-dr=no`.

**Comment by poisonsnak** [comment]
It does not drop any frames with `--vo=null`

`vd-lavc-dr=no` fixed the issue!  Thanks!  I still have some hitching/stuttering that I don't have on the m3. It's mostly noticeable in pans (the log doesn't show any dropped frames though), but it's way better than it was before.  CPU usage is down to about 50% for 1080p

Any idea what the cause is, is there something else I should look at to fix the root issue or anything else you want me to try?  The manual says vd-lavc-dr=yes requires at least OpenGL 4.4 or Vulkan and I am running OpenGL 4.5 according to the log.  Is the update to Mesa the issue?

**Comment by haasn** [comment]
This is a known issue with that option and I'm not sure there's anything we can necessarily do about it. It only seems to affect those low-end Intel Celerons used in NUCs etc. See #6314 for more info and some leads I had on how to fix it (either in mpv or mesa).

**Comment by poisonsnak** [comment]
Interesting, I read through that issue thread and I'm not sure what I could add, but if I figure anything out I will let you know (besides "don't buy a $150 NUC for an HTPC" haha).  Thanks again for the quick help, it's very much appreciated.
