### ISSUE TITLE
Add vidscale option for stats

### ISSUE THREAD

**Issue by agyild** [mpv-player/mpv#6811]
For better consistency with OSC's `vidscale` option, also add a `vidscale` option for stats. Current dynamic font size implementation causes stats to overflow when there are many shaders on the rendering chain, which might be also somehow alleviated with this option.

**Comment by Argon-** [comment]
Can't you achieve this by setting the font size? This is exposed as an option for this very reason. 
Or do you want the letters to stay big/small when the window size is decreasing/increasing?

**Comment by agyild** [comment]
> 
> 
> Can't you achieve this by setting the font size? This is exposed as an option for this very reason.
> Or do you want the letters to stay big/small when the window size is decreasing/increasing?

The problem is font size 8 for default windowed and fullscreen size is different. It is scaled according to the window size, which means you only have the correct font size for a single window dimension (tiny in one, proper size in another etc.). Yes, in other words the font size should be able to remain the same.

**Comment by Argon-** [comment]
>It is scaled according to the window size, which means you only have the correct font size for a single window dimension (tiny in one, huge in another etc.)

When you fix font size then the whole information/text only fits into the player window when it has a specific size. Is this really preferable?

**Comment by agyild** [comment]
> When you fix font size then the whole information/text only fits into the player window when it has a specific size. Is this really preferable?

Either isn't any better. You either have overflowing text or tiny text in that case. So it would be better if it was togglable. One might suit better depending on the use case, what one displays in the stats etc.

**Comment by Argon-** [comment]
Sounds reasonable. Alright, I'll see to it. However, can't give you an ETA since I'm abroad for work and rather busy. If someone wants to take care of it before I can -> feel free to it.
