### ISSUE TITLE
Frame timings are being displayed as 00000 with the stats plugin

### ISSUE THREAD

**Issue by CypherNL** [mpv-player/mpv#6812]
### mpv version and platform
mpv-x86_64-20190714-git-65b1c2d
Windows 10 LTSB 1607

### Reproduction steps
1. Get the latest mpv git release here:
https://sourceforge.net/projects/mpv-player-windows/files/64bit/ (first 7z file is the newest one)
 
2. Open a video file with that mpv build

3. Press "I" to see the stats of the render and video
### Expected behavior
The frame timings are displayed on how long it takes to complete a frame.

### Actual behavior
The frame timings are displayed as 00000 also on the 2nd stats page by pressing "2" when the stats page is shown.

### Log file
https://gist.github.com/CypherNL/000a782a260ae154c75c3ba4b18dfbd6

### Sample files
So far i can reproduce this with any video file. This doesn't matter if it's played from a local file or a YouTube video played with youtube-dl. 

If you can't reproduce this issue. Please let me know. I may give you sample files if necessary.
If you need more information. Please let me know.

**Comment by Argon-** [comment]
libplacebo doesn't support stats: https://github.com/mpv-player/mpv/issues/6688
