### ISSUE TITLE
[Request] Set as default image viewer, scroll through images in folder

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [mpv-player/mpv#6813]
Windows 10, Latest MPV

### Expected behavior

Double click image in folder
Opens image into mpv
Scroll through the rest of the images in that folder (Including gifs and videos)

### Actual behavior

Double click image in folder
Doesn't open image in mpv (Opens in whatever default img viewer is)
Try to scroll through images, it doesn't scroll it just stays on that image

(Maybe I'm missing something, or a keybind or something to actually scroll. But I can't figure out what that keybind is if so. Also that doesn't solve the issue of it not being the default image viewer.)

**Comment by Akemi** [comment]
https://github.com/mpv-player/mpv/wiki/User-Scripts
use the autoload script to automatically load consecutive files. you just need to add the right extensions.

for the other problem just register mpv as the default app for images (Open with, always).
