### ISSUE TITLE
mouse cursor freezes on Windows

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#6816]
When mpv is on the second screen in full screen and the video is paused then the mouse cursor freezes when the mouse moves over the mpv window.

- happens only on the second screen and not on the first/primary screen
- happens only in full screen mode and not with normal window size
- happens with default settings, `--config=no`
- happens only when the video is paused
- happens in both mpv and mpv.net

Command line used:

`mpv --config=no --log-file=log.txt test.mkv`

Now what's interesting, when it happens then on the first screen random UI elements of Windows File Explorer do flicker. When I play then the cursor moves normally but Explorer still flickers when the mouse moves over mpv on the second screen. Other apps like Firefox do not flicker, only Explorer.

Also interesting is that I had other issues that were happening only on the second screen and disappeared meanwhile, I think after a Win 10 update.

System:

Win 10 1903
NVIDIA GT 1030 Driver 26.21.14.3136 from 03.07.2019
i5-8400

log file was too long, I had to trim it to 3000 lines:

https://pastebin.com/nwrpq2R7

It exists since a long time, does not really bother me.

**Comment by lachs0r** [comment]
Graphics driver bug. Maybe try other values for `--gpu-context` to see if any of them don’t trigger this behavior.
