### ISSUE TITLE
bulges

### ISSUE THREAD

**Issue by Vahid-Peivandi** [mpv-player/mpv#6817]
what are many bulges in some videos?
![Screenshot at 2019-07-22 07:09:39](https://user-images.githubusercontent.com/25903079/61602814-5b432900-ac50-11e9-8d08-a200ebd10b34.png)

**Comment by lachs0r** [comment]
Chapter marks.

**Comment by Vahid-Peivandi** [comment]
> Chapter marks.

what is useful for?

**Comment by Vahid-Peivandi** [comment]
> Chapter marks.

please explain with example

**Comment by Vahid-Peivandi** [comment]
> Chapter marks.

please explain with an example

**Comment by Akemi** [comment]
for example to know when an opening/ending ends/starts, same for credits, inserts etc. you can jump to them with a shortcut. useful to skip for example endings or opening on series.

**Comment by Vahid-Peivandi** [comment]
> for example to know when an opening/ending ends/starts, same for credits, inserts etc. you can jump to them with a shortcut. useful to skip for example endings or opening on series.

thanks a lot 
but the last question :) how to add a chapter in MPV or terminal commands?

**Comment by CounterPillow** [comment]
see `--chapters-file`. You can also mux them into the container directly with e.g. mkvtoolnix

**Comment by Argon-** [comment]
You don't. Chapters are part of the video file, embedded in its metadata.

**Comment by Vahid-Peivandi** [comment]
> --chapters-file

I run this code:
mpv --chapters-file = Desktop/ebf07612d0cb252f6469ed5ea142755112475523-720p__18946.mp4
but don't understand how to create chapter tho this video?

**Comment by Hrxn** [comment]
You need a chapters file. You can't create chapters automagically.
