### ISSUE TITLE
Website: Manual for Git master not up-to-date for a long time

### ISSUE THREAD

**Issue by 86423355844265459587182778** [mpv-player/mpv#6822]
### Reproduction steps
1. Visit https://mpv.io/manual/master/#options-hwdec-codecs

### Expected behavior
The website should show `By default, this is set to h264,vc1,hevc,vp9.`, the same as [DOCS/man/options.rst](https://github.com/mpv-player/mpv/blob/master/DOCS/man/options.rst). (See 8f5a42b.)

### Actual behavior
The website shows `By default, this is set to h264,vc1,wmv3,hevc,mpeg2video,vp9.`.

**Comment by wiiaboo** [comment]
https://github.com/mpv-player/mpv/blob/master/TOOLS/travis-rebuild-website the initial condition wasn't updated after the transition to docker.
