### ISSUE TITLE
Trying to get a better understanding of mpv's terminal nature

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#6827]
I'm trying to get a better understanding of mpv's terminal nature.
As I understand it has the following use cases:

- For people who generally use the terminal only sometimes there are corner cases on when the terminal can be useful.

- People that prefer doing everything with the terminal can control all features with the terminal.

- Having status display on the terminal.

- It's possible to control mpv via key bindings not only with the main window but also with the terminal.

- When coding js/lua scripts errors are shown on the terminal and debug messages can be printed

Writing js/lua scripts there is no debugger support for stepping through the code, correct?

As I understand it there is no repl functionality on the terminal, correct? For me I think this would be more useful than the status display. There is however a repl script repl.lua, I just discovered it.

Why are two separate files on Windows needed, mpv.exe and mpv.com, what is their relation, where do I find the code for mpv.com?

In mpv.net I added calls to AttachConsole and FreeConsole, with --terminal=yes I get the status on the terminal and what's important for me I get the js/lua messages I need for js/lua coding. Only problem I got is when I exit mpv.net, the caret/prompt are in front of and mixed with the status text. It's broken but for me it's OK, I can live with it. Maybe this is the reason for why a separation between mpv.exe and mpv.com is needed? On Linux there is only one executable?

I hope this wasn't too many stupid questions, it's my first year I happen to like the terminal, mpv probably supported why I changed my mind.

**Comment by CounterPillow** [comment]
>Why are two separate files on Windows needed, mpv.exe and mpv.com, what is their relation, where do I find the code for mpv.com?

See
https://github.com/mpv-player/mpv/wiki/FAQ#On_Windows_why_does_mpvexe_not_attach_to_the_console_and_what_does_mpvcom_do

For the source, see https://github.com/mpv-player/mpv/blob/master/osdep/win32-console-wrapper.c

**Comment by stax76** [comment]
Very helpful, thanks. The console wrapper works for mpvnet without modification, how cool is that.

Do you know if there is debugger support for js/lua or do I have to get used to print debugging for js/lua coding?

**Comment by avih** [comment]
There's no debugger.

**Comment by stax76** [comment]
Thanks for the support!
