### ISSUE TITLE
using Vulkan in libmpv frontend in Windows

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#6833]
In my front end I can load a media file before my window is shown, gpu-api d3d11 and opengl have no problem with that, it does not work with vulkan.

My front end by default waits for MPV_EVENT_FILE_LOADED and then calls get_property_int("width"), get_property_int("height") in order to set the window size, this happens before the window is shown so it's shown with the size of the video resolution.

My test showed it's not enough the window handle was created, vulkan will only initialize successfully if the window was shown (is visible).

```
Samples> mpvnet '.\Blackmagic Pocket 4K.webm'
Playing: .\Blackmagic Pocket 4K.webm
 (+) Video --vid=1 (*) (vp9 3840x1620 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
Using hardware decoding (nvdec).
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 3840x1620 cuda[nv12]
[vo/gpu/vulkan/libplacebo] Failed resizing swapchain: unknown size?
[vo/gpu/vulkan/libplacebo] Failed (re)creating swapchain!
Could not initialize video chain.
[vo/gpu/vulkan/libplacebo] Failed resizing swapchain: unknown size?
[vo/gpu/vulkan/libplacebo] Failed (re)creating swapchain!
Error opening/initializing the VO window.
Video: no video
```

**Comment by stax76** [comment]
I use mingw as described here:

https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md#native-compilation-with-msys2

It seems vulkan is not enabled with that build instruction, is it difficult to enable vulkan here?

Does mpv generally call ShowWindow before any vo is initialized?

**Comment by avih** [comment]
> It seems vulkan is not enabled with that build instruction

The instructions don't cover building every possible dependency which mpv can make use of.

If mpv tries to autodetect vulkan and/or libplacebo (or if you enable them at `waf configure`) and it doesn't detect it, then you should look at `build/config.log` to figure out what prevents it.
