### ISSUE TITLE
possible memory leak using JavaScript

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#6836]
Using this simple JavaScript memory usage constantly grows in task manager playing mp3.

```
// this script sets the OSC to be always on for
// audio files and auto for non audio files
function OnFileLoaded() {
    var path = mp.get_property("path");
    var ext = path.split('.').pop();

    switch (ext)
    {
        case "mp3":
        case "m4a":
        case "opus":
        case "ogg":
        case "flac":
            if (visibility != "always") {
                mp.commandv("script-message", "osc-visibility", "always");
                visibility = "always";
            }
            break;
        default:
            if (visibility != "auto") {
                mp.commandv("script-message", "osc-visibility", "auto");
                visibility = "auto";
            }
            break;
    }
}

var visibility = "auto";
mp.register_event("file-loaded", OnFileLoaded);
```

**Comment by avih** [comment]
`OnFileLoaded` is called only once - when a new file is loaded. Playing it for 1s or 10 hours shouldn't matter at all if the function is only called once.

I find it quite unlikely that what you see is a memory leak. If you have a reduced test case with something which actually runs continuously and leaks memory, please share, otherwise, I tend to dismiss this claim.

**Comment by stax76** [comment]
I know it looks simple but try it and you will see, just take a look in task manager, memory grows very fast when you play mp3 using last sinshiro x64 build.

**Comment by stax76** [comment]
Here is a screenshot that shows that it's using 122 MB memory after playing 19 minutes mp3 music, at the beginning of the track it was 60 MB.

https://postimg.cc/cvXLkfPB

**Comment by avih** [comment]
And what makes you think it's related to JS? You didn't say that without this script it doesn't grow, or that when the OSC is in "always" (DEL cycles OSC modes) without this script then it doesn't grow.

It could be related to many things and not necessarily a leak. It could be libass cache, or some mpv cache, etc.

Again, a JS function which runs just once is very unlikely to be the cause for increasing memory usage, leak or not leak.

**Comment by stax76** [comment]
Sorry, I didn't think much far, it's caused by the OSC and not JavaScript.

Setting the OSC to always when mp3 plays makes the memory grow and setting it back to hiding the OSC will release the memory. I will try playing for 2 hours.
