### ISSUE TITLE
Please provide an appimage

### ISSUE THREAD

**Issue by keshavbhatt** [mpv-player/mpv#6843]
Appimage is universal Linux packaging format which allow almost every Linux distro run any app using one file. no installation, no dependencies, double click and run.
It would be nice to have an appimage for project like mpv. Since mpv is used by various other apps as well, appimage of mpv will help them deploy mpv into their appimage easily.
ty

**Comment by j605** [comment]
Have you looked into the previous issues regarding this. What does this issue achieve?
https://github.com/mpv-player/mpv/issues/4056
