### ISSUE TITLE
Live stream falls behind after screen blanking

### ISSUE THREAD

**Issue by mm191** [mpv-player/mpv#6846]
When streaming live (rtsp), the live stream works fine until the screen blanks (dpms). 
It is wanted to blank the screen, thus --no-stop-screensaver is used.
After the screen blanks and is then turned on again (with dpms force on or by e.g, moving the mouse), the live streaming falls behind. Interestingly enough, when displaying several live streams at the same time (using the same source), the streams will all fall behind but with different gaps to real time.

I played around with various command line options:
- cache=no
- untimed (showed some improvement but is not an option as - if used - frame rate will highly fluctuate)
- demuxer-readahead-secs=0
- no-resume-playback
- cache-secs=0
- speed=1.01

None of these helped.

Is there any way to make mpv play live streams correctly even when the screen blanks while streaming?

Problem occurs on Linux Mint 19.2, mpv and all packages up-to-date as of Aug 8th.
Problem occurs on different hardware.

**Comment by CounterPillow** [comment]
Where's your logfile?

>mpv and all packages up-to-date as of Aug 8th

doesn't mean anything on a distro with a stable release cycle

**Comment by mm191** [comment]
> Where's your logfile?
> 
> doesn't mean anything on a distro with a stable release cycle

I will provide this information as soon as I have again access to the PC in question. Sorry for letting people willing to help wait.
