### ISSUE TITLE
Different HDR tone mapping

### ISSUE THREAD

**Issue by lucellent** [mpv-player/mpv#6847]
Hello. I'm using the latest version of MPV for Windows 10.
I'm sorry if this post doesn't belong to the right place but I couldn't find a fix.

I basically want to change how it converts HDR 10bit videos to regular SDR 8bit. Comparing the colors to VLC, for example, which has this feature by native, the yellows I noticed are much more orange in MPV. There could be other color differences but that's what I saw for now.

So, is it possible to change this? And please be noob friendly, I saw some programming codes (I'm not sure) about this but I wasn't sure how to change it. I'm really new to this.

**Comment by lucellent** [comment]
Actually, my issue is the same as this - https://github.com/mpv-player/mpv/issues/6405

**Comment by haasn** [comment]
Just mirroring it here for reference, the suggestion would be to try setting `--tone-mapping-desaturate=1 --tone-mapping-desaturate-exponent=0` if you prefer that kind of look.
