### ISSUE TITLE
Exception 0xc0000005 @ 0x000000000014b257

### ISSUE THREAD

**Issue by markfilipak-windows** [mpv-player/mpv#6848]
### mpv version and platform
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.19.101
   libavcodec      58.30.100
   libavformat     58.18.100
   libswscale      5.2.100
   libavfilter     7.31.100
   libswresample   3.2.100
ffmpeg version: 4.1+1209.ge320f9576a

Win10-1803. Intel HD Graphics 530 & NVIDIA GeForce GTX 980M

### Reproduction steps
mpv --player-operation-mode=pseudo-gui
### Expected behavior
Run
### Actual behavior
Throws exception

### Log file
Faulting application name: mpv.exe, version: 2.0.0.0, time stamp: 0x00000000
Faulting module name: nvwgf2umx.dll, version: 10.18.13.5900, time stamp: 0x5646ca81
Exception code: 0xc0000005
Fault offset: 0x000000000014b257
Faulting process id: 0x1048
Faulting application start time: 0x01d54ca635e4c7c8
Faulting application path: d:\D\Setup\Video\Win players\mpv-x86_64-20181002\mpv.exe
Faulting module path: C:\WINDOWS\SYSTEM32\nvwgf2umx.dll
Report Id: 4f20be56-d4da-43a4-9bd2-772c850db339
Faulting package full name: 
Faulting package-relative application ID:

**Comment by CounterPillow** [comment]
> Faulting module path: C:\WINDOWS\SYSTEM32\nvwgf2umx.dll

driver bug

**Comment by markfilipak-windows** [comment]
Video driver?

**Comment by CounterPillow** [comment]
Assuming "nv" stands for "nvidia", probably.

**Comment by markfilipak-windows** [comment]
Thanks. I'll reinstall.

**Comment by Hrxn** [comment]
Yup, that's a part of the nVidia D3D driver..
