### ISSUE TITLE
mpv is blocking building of FFmpeg 4.2

### ISSUE THREAD

**Issue by retokromer** [mpv-player/mpv#6850]
```
Error: 1 problem in 1 formula detected
ffmpeg:
  * Non-executables were installed to "/usr/local/opt/ffmpeg/bin"
    The offending files are:
      /usr/local/opt/ffmpeg/bin/python
```

>I believe the failure is the python binding to mpv when it's built/compiled. You could submit a bug report to mpv on GH.

See: https://github.com/Homebrew/homebrew-core/pull/42827

**Comment by lachs0r** [comment]
Not our fault.

**Comment by retokromer** [comment]
If `ffmpeg` 4.2 is installed, then `mpv` doesn’t work:

<img width="809" alt="Screenshot 2019-08-08 at 17 04 03" src="https://user-images.githubusercontent.com/3246607/62714687-52e43f80-b9ff-11e9-8ad5-e6ecc5e8272a.png">

If `mpv` is reinstalled, then it wishes the old `ffmpeg` 4.1.4_1:

<img width="809" alt="Screenshot 2019-08-08 at 17 05 09" src="https://user-images.githubusercontent.com/3246607/62714843-9ccd2580-b9ff-11e9-8415-562c0117e442.png">

**Comment by CounterPillow** [comment]
```
✓ fratti@archbook ~ $ /usr/bin/mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Aug  6 14:50:47 CEST 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2
```

Guess I'm a fucking wizard then.

This is homebrew's problem.

**Comment by retokromer** [comment]
>This is homebrew's problem.

Which a new release could solve. Please understand that I cannot make an official release of mpv.

**Comment by jbeich** [comment]
mpv v0.29.1 is API-compatible with ffmpeg n4.2 but not ABI-compatible (see [ABI history](https://abi-laboratory.pro/tracker/timeline/ffmpeg/)). Can't you force-rebuild mpv package? See [FreeBSD update](https://github.com/freebsd/freebsd-ports/commit/76a8e58f8ee2be9d62f2ff53c7fb8b257c25b2ed) as an example.

**Comment by CounterPillow** [comment]
@retokromer if you think making ABI bump releases is the upstream mpv project's duty, you're incredibly ignorant of how software packaging works.

**Comment by retokromer** [comment]
@CounterPillow I’m just a Jew.

**Comment by CounterPillow** [comment]
Excuse me, what?

**Comment by Cpuroast** [comment]
In the mean time, as a workaround, you are free to use the mpv cask(from "brew cask install mpv"), which pulls from:
https://laboratory.stolendata.net/~djinn/mpv_osx, which is referenced by https://mpv.io/installation

**Comment by retokromer** [comment]
>In the mean time, as a workaround, you are free to use the mpv cask (from "brew cask install mpv")

Thank you, that’s useful indeed!
