### ISSUE TITLE
mpv crashes when using hwdec=auto with nVidia 430.26 and 430.40 binary drivers

### ISSUE THREAD

**Issue by truckershitch** [mpv-player/mpv#6852]
### mpv version and platform

libmpv.so.1.103.0 compiled this morning from mpv-build script (I assume this uses master).
mpv 0.29.0-369-g639ee55df7 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Wed Aug  7 09:05:52 EDT 2019
ffmpeg library versions:
   libavutil       56.33.100
   libavcodec      58.55.100
   libavformat     58.30.100
   libswscale      5.6.100
   libavfilter     7.58.100
   libswresample   3.6.100
ffmpeg version: N-94483-g98e419cbf5

Fedora Linux 30 x86_64
nVidia GTX 760
nVidia binary drivers 430.26 and also 430.40

Problem does not occur with version 418.74 driver

See this bug report: https://devtalk.nvidia.com/default/topic/1055558/linux/nvdec-segfaults-with-430-xx-drivers-on-gk104/post/5354102/#5354102

### Reproduction steps

Running without hwdec=auto plays videos fine.  Videos also play fine in Kodi.  I have VDPAU decoding enabled in Kodi.

With Plex Media Player 2.38.xxx, Video crashes.  Turning off hardware decoding solves the problem.
This also occurs with regular RpmFusion mpv program and libraries.

### Log file

https://0x0.st/zOyQ.log

**Comment by CounterPillow** [comment]
Pro tip, if a segfault happens 7 stack frames deep in the nvidia driver, you probably shouldn't complain to mpv about it.

**Comment by truckershitch** [comment]
Ok, thanks.

I'm not too good with stack traces.  Hopefully, someone at nVidia will work on it.  For now, I'll just disable the HW decoding.
