### ISSUE TITLE
player becomes unresponsive when switching between window and fullscreen

### ISSUE THREAD

**Issue by sinatosk** [mpv-player/mpv#6853]
mpv - 0.29.1
Operating System - Linux 64bit 5.2.2 to 5.2.7 ( Arch Linux )
Video drivers - mesa 19.1.2 to 19.1.4 ( 32bit and 64bit )
Laptop - HP Pavilion 15-cw1507sa
CPU - AMD Ryzen 5 3500U
GPU - Radeon Vega 8 Graphics ( integrated )

### Reproduction steps
Open video using command line like so

> $ mpv --log-file=output.txt Big_Buck_Bunny_1080p_surround_frostclick.com_frostwire.com/Big_Buck_Bunny_1080p_surround_FrostWire.com.avi

while the video is paused or playing just continuously switch the player between full screen and window mode and eventually the player stops responding

changing mpv to use OpenGL or OpenGLES works fine but I get dropped frames ( don't know why )continisouly

### Expected behavior
Video play after going from window mode to full screen

### Actual behavior
When I put the player in window mode from full screen ( doesn't matter if the video is playing or paused ) sometimes after going from full screen to window mode and then back a few times... the contents of the mpv window don't update ( just black ), audio stops after about 1 second and becomes unresponsive, in the terminal saying ( this text is red )

> [vo/gpu/vulkan] Failed acquiring swapchain image: VK_SUBOPTIMAL_KHR

and sometimes before I see the above message after resizing the window ( this text is orange )

> [vo/gpu/vulkan] Requested width 1918 does not match current width 1920continisouly
> [vo/gpu/vulkan] Requested height 1078 does not match current height 1080

I've also tried clearing mesa shader cache

I eventually just have to kill the process

I'm aware of issue #5695 and tried stuff based on that and made no difference

I updated the video drivers for mesa to 19.1.4 thinking [this issue](https://bugs.freedesktop.org/show_bug.cgi?id=111097) might be related but still a no go

### Log file

https://0x0.st/zOxb.txt

### Sample files

while this happens with any video file ( doesn't matter if it's h264 or h265 and I don't have any other encoded files yet )

I used the big buck bunny in this example downloaded from [blender's website](https://peach.blender.org/download/) and the [torrent file](http://www.frostclick.com/torrents/video/animation/Big_Buck_Bunny_1080p_surround_frostclick.com_frostwire.com.torrent) I used

and my [mpv.conf file](https://0x0.st/zOxj.conf)

**Comment by sinatosk** [comment]
I've compiled and install mesa ( 32bit and 64bit ) version 19.2.0-devel from [git repo e2d761de037](https://gitlab.freedesktop.org/mesa/mesa/tree/e2d761de0377391c34c3c2fcc098292066dc0581) and so far it's not happening anymore so I guess it's a bug in mesa 19.1.x?

**Comment by sinatosk** [comment]
I was wrong, issue still there. I thought I was using vulkan at the time I made my last post

sorry...

**Comment by Kryohi** [comment]
Happens to me as well.
Arch Linux, Mesa 19.1.4, radeon R9 380.
[mpv.conf](url)
