### ISSUE TITLE
[sub/ass] Error decoding subtitle

### ISSUE THREAD

**Issue by yurivict** [mpv-player/mpv#6854]
Subtitles file: https://people.freebsd.org/~yuri/John%20Adams.S01E01.720p.HDTV.x264.smi

**Comment by yurivict** [comment]
mpv-0.29.1_6,1 on FreeBSD 12.

**Comment by CounterPillow** [comment]
Probably because the text encoding of that subtitle file is completely scuffed. Did you build with uchardet? That's needed to auto-detect subtitle encoding IIRC. Knowing whether you've built with uchardet is another reason as to why we ask for a log file in the issue template you've conveniently ignored.

**Comment by yurivict** [comment]
It is built with UCHARDET=on in the FreeBSD package.

---------------------

> issue template you've conveniently ignored

They happen to be very annoying.

**Comment by lachs0r** [comment]
Looking at FFmpeg’s SAMI decoder, I can’t see how it could possibly work.

**Comment by CounterPillow** [comment]
ffplay with `ffplay -vf subtitles=path-to-file.smi,charenc=euc-kr somevideo` doesn't play the subtitles either, so this appears to be a bug in ffmpeg.

**Comment by richardpl** [comment]
your arguments are wrong, filter options separator is : and not ,

**Comment by CounterPillow** [comment]
@richardpl your counter-argument is wrong, that's what I actually tried, I just typed the wrong separator into the github message to illustrate what I was using.

**Comment by richardpl** [comment]
If you used ffmpeg to convert this subtitle to ass, you would notice that it needs also "-sub_charenc euc-kr" as input option.

**Comment by wm4** [comment]
No response -> closing.
