### ISSUE TITLE
Properties and list of events

### ISSUE THREAD

**Issue by xerostomus** [mpv-player/mpv#6860]
Dear Sirs, 
I read 
https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst#id5
and the links to Properties and List of events are not working. 
Where can I find them?
Thank you for your advice!
:-)

**Comment by TheAMM** [comment]
https://github.com/mpv-player/mpv#external-links

**Comment by Akemi** [comment]
https://mpv.io/manual/master/#json-ipc
https://github.com/mpv-player/mpv/tree/master/DOCS/man in input.rst

**Comment by philippludwig** [comment]
This is the correct link at the moment: https://mpv.io/manual/master/#properties

**Comment by wm4** [comment]
The rst rendering in github doesn't work because... it's github. The manual rendering on mpv.io is the correct one.

**Comment by philippludwig** [comment]
Yes, I just posted the link for other people who stumble across this issue :) Thanks for all the hard work!
