### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by khaosgrille** [mpv-player/mpv#6861]
Hi,

### mpv version and platform

i use mpv 0.29.1 (0.29.1-r1 is the package version) on gentoo. 
I have the following use flags: 
X alsa cdda cli drm dvd egl iconv jpeg lcms libass libmpv lua luajit opengl pulseaudio tools uchardet wayland xv zlib zsh-completion 

And i use Python 3.6 with 2.7 as fallback
PYTHON_TARGETS="python2_7 python3_6 -python3_5 -python3_7")

### Actual behavior
it has a segmentation fault
### Log file

http://dpaste.com/33CEXDT
This is the only error message without -v:
[vo/gpu/opengl] Suspected software renderer or indirect context.

Thank you for your help

**Comment by lachs0r** [comment]
A backtrace would help but it looks like your graphics stack is broken.

**Comment by xantoz** [comment]
Yes, you should probably not be getting a software renderer if you have a GPU of some sort (what is your HW?), so that sounds like something is strange with your graphics stack. Have you put your video card in VIDEO_CARDS in /etc/portage/make.conf ?

OTOH even with a software renderer we shouldn't be getting a segfault, so that might be interesting to investigate.

**Comment by khaosgrille** [comment]
i recompiled it without drm but got still the same issue. i have an integrated intel graphic card and my hardware is an old thinkpad t420. i added my video card not to my make.conf 

recompiling mesa may take some while so lets see what it will do

**Comment by xantoz** [comment]
The drm use flag is unrelated (it controls the feature where mpv can
display in a raw VT) to your problem.

What is your VIDEO_CARDS variable?

2019年8月11日(日) 11:40 khaosgrille <notifications@github.com>:

**Comment by khaosgrille** [comment]
it is

VIDEO_CARDS="intel"

**Comment by xantoz** [comment]
I think you need to put i965 in VIDEO_CARDS as well. This is the name of
the driver in mesa.

2019年8月11日(日) 14:20 khaosgrille <notifications@github.com>:

**Comment by khaosgrille** [comment]
> I think you need to put i965 in VIDEO_CARDS as well. This is the name of the driver in mesa. 

this seems to be it. now everything works fine thank you
