### ISSUE TITLE
Lastest FFmpeg snapshot compiled from source not detected by Waf help script

### ISSUE THREAD

**Issue by c4tzz** [mpv-player/mpv#6862]
Hi. I try to compile mpv from source on baremetal hypervisor Xen Dom0 Fedora 25.

FFmpeg version N-94492-gc29d81e (lastest snapshot)
Guide here :
https://trac.ffmpeg.org/wiki/CompilationGuide/Centos

But waf script can't detect FFmpeg/Libavcodec headers.
Waf - version 2.0.9
(libavcodec not found)

All libs store at /usr/local/lib and /usr/lib

How to fix it?

**Comment by lachs0r** [comment]
Sounds like pkg-config does not look in your /usr/local prefix. Make sure to either package FFmpeg properly for your distribution and install it in the correct prefix, or set the PKG_CONFIG_* environment variables, or use our [mpv-build](https://github.com/mpv-player/mpv-build) helper scripts (which can automatically build mpv and the minimum set of dependencies for you).

**Comment by CounterPillow** [comment]
I'll assume this is resolved with proper pkg-config wrangling, since latest ffmpeg works just fine for me.
