### ISSUE TITLE
I can make this example better: run "/bin/sh" "-c" "echo ${title} > /tmp/playing"

### ISSUE THREAD

**Issue by safinaskar** [mpv-player/mpv#6863]
### mpv version and platform
git master, i. e. 639ee55df7cc1ecf7ea5dcfa7ecc5551b6b7312d

DOCS/man/input.rst says:
```
        ``run "/bin/sh" "-c" "echo ${title} > /tmp/playing"``

        This is not a particularly good example, because it doesn't handle
        escaping, and a specially prepared file might allow an attacker to
        execute arbitrary shell commands. It is recommended to write a small
        shell script, and call that with ``run``.
```
I can fix security problem (if I understand mpv config syntax and mpv rules for expanding `${title}` correctly):
```
run "/bin/sh" "-c" "printf '%s\\n' \"$1\" > /tmp/playing" dummy-argv0 "${title}"
```
Please, don't trust me! I know how UNIX shell works, so I know that from shell view point code above is correct. But I don't know all details about your mpv syntax, so I could make some mistake. Also, I didn't test code above

**Comment by lachs0r** [comment]
Unfortunately, this is not as easy to understand, which is the point of this example.
