### ISSUE TITLE
display-tags not updating on stream when tracks change

### ISSUE THREAD

**Issue by pleasantarmour** [mpv-player/mpv#6864]
The metadata for tracks are not changing with an ogg stream. It resets the playback position when tracks change and just prints a warning. This occurs with this stream: http://allstream.rainwave.cc:8000/all.ogg

### mpv version and platform
mpv version 0.29.1 on macOS and Linux.

### Reproduction steps
`mpv http://allstream.rainwave.cc:8000/all.ogg`
Wait for a track to finish playing and for another track to start.

### Expected behavior
When tracks change, the file tags should update.

### Actual behavior
The first track to play will display metadata, but the file tags do not update when tracks change and a warning appears: `Invalid audio PTS`

### Log file
https://0x0.st/zVNb.log
57.082 is where the track change occurs. This was logged on a Mac, but also occurs on Linux.

**Comment by wm4** [comment]
This is probably fixed in master. At least I've recently successfully tried an ogg webstream.

**Comment by pleasantarmour** [comment]
Right, I just tried 0.30.0 and can verify this works. Thank you!
