### ISSUE TITLE
Research open >1 video simultaneously

### ISSUE THREAD

**Issue by ldexterldesign** [mpv-player/mpv#6865]
### mpv version and platform

mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Oct  5 00:01:23 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: 4.0.2

macOS

--
https://github.com/mpv-player/mpv/issues/1377
https://github.com/mpv-player/mpv/issues/4463
https://github.com/mpv-player/mpv/issues/4926
https://github.com/mpv-player/mpv/issues/5747

Hi,

Hope you're well

Thanks for software

I'm researching a way to open >1 video simultaneously. I do this to compare quality so need them playing in sync (i.e. side by side).

To-date I've been using the following wearisome shell command:
```
open -n foo.mkv & open -n bar.mp4 & open -n baz.mp4
```

Before I script something I wondered if there's an option I've missed to help solve my use case?

🍼 Disclaimer, I'm learning zsh

Hope to hear back

Cheers

**Comment by zc62** [comment]
If the goal is to compare videos, there are other more reliable ways. (Use vapoursynth to convert these videos from YUV to RGB, then compare them frame by frame in the vsedit preview window.)

AFAIK one mpv instance can't create more than one `vo`, even for only one video, see #5844. You can try to use [syncplay](https://syncplay.pl/) to sync multiple mpv instances. Though it is designed to work over the network, probably it should work on the same machine as well.

**Comment by ldexterldesign** [comment]
FYI Encrypt All Sites Eligible is ON (which I believe is OFF by default because I've only just discovered it) seems to fix this issue

**Comment by ldexterldesign** [comment]
Hi @zc62,

Thanks for reply

> If the goal is to compare videos, there are other more reliable ways. (Use vapoursynth to convert these videos from YUV to RGB, then compare them frame by frame in the vsedit preview window.)

That's a novel solution but IMO it's easier to compare video quality by watching video rather than comparing stills

> AFAIK one mpv instance can't create more than one vo, even for only one video, see #5844. You can try to use syncplay to sync multiple mpv instances. Though it is designed to work over the network, probably it should work on the same machine as well.

Will give SP a shot

+1 for having this functionality native though!

Cheers

**Comment by Akemi** [comment]
i would suggest to use open like that
```
open -n PATH/TO/mpv.app --args file1.mp4 & open -n PATH/TO/mpv.app --args file2.mkv
```
or rather use the mpv binary like that, since that is its intended use.
```
PATH/TO/mpv.app/Contents/MacOS/mpv --args file1.mp4 & PATH/TO/mpv.app/Contents/MacOS/mpv --args file2.mkv
```
or just use two different terminal windows.

since you already linked issue #1377, you got your answer.

**Comment by ldexterldesign** [comment]
iina has the following [f]eature which solves my use case

Can I confirm this feature is iina-specific, not present in mpv?

Yours hopefully

f: https://github.com/iina/iina/issues/2562#issuecomment-520621056

**Comment by Akemi** [comment]
obviously this is an iina feature. i can only repeat myself. mpv does not support this, other than launching separate instances. #1377 is still open after all.
