### ISSUE TITLE
H.264-to-H.265

### ISSUE THREAD

**Issue by markfilipak-windows** [mpv-player/mpv#6866]
Oops. The topic of this post was supposed to be HandBrake. I screwed up, but I'm going to leave it here at MPV because it may be of interest, and someone here may wish to comment.

I seek a general MPV discussion platform. There appears to be none, so I am here. Kindy excuse me if you think this is an inappropriate venue, and if so, kindly suggest a more appropriate venue.

Probably everyone who reads this understands I-frames & P-frames & B-frames and decoding and all that. Decoding is fairly straightforward. The result of decoding is video frames, audio, and subtitles (content). The fundamental function of HandBrake is to encode that content according to the user's choice of encoder.

The objective is to produce an encoded stream that matches the content & no better. I write "no better" because one cannot improve on the source -- I of course disregard file size because I seek the best transcode and "no better"; I don't want loss at all but I don't want file-size waste, either.

It occurs to me that if I take a 1080p24 H.264 M2TS source and transcode it to a 1080p24 H.265 MKV target, there is only one set of HandBrake settings that can do it with 100% fidelity and "no better". In fact, the source (1080p24 H.264 M2TS) really shouldn't matter. Whatever the source, given the decoded content, there should be a set of HandBrake settings that will produce the best (100%?) encode & "no better".

What are those HandBrake settings?

Of course there are many details involving filtering & block size-v-motion compensation &tc., nonetheless, assuming that I only transcode 'up' (H.264-to-H.265, for example), I contend that once the source has been decoded and a target codec has been chosen, there is one & only one set of HandBrake settings that will duplicate the source content & "no better".

Now, I can suppose that it's theoretically impossible to duplicate the source, even when transcoding 'up'. Is that so? I can suppose that I can only approach the source asymptotically; 98% ... 99% ... 99.9% ... 99.99% ... Is that so? It's easy to say that's so, but is it really so?

Now, suppose I knew how the source's H.264 encode was set up. Would I then be able to duplicate those settings for a transcode to H.265? Is there an H.264-to-H.265 correspondance? Does HandBrake know what the H.264 settings were? I suspect not. But can HandBrake infer what the H.264 settings were based on metadata? I suspect so.

Currently, I have QP and the "Optimize Video" knobs to twiddle. They are mysterious to me and I'm tiring in the attempt, based on perceived video quality of test runs, to reverse engineer what they do.

Do 'you' have any thoughts? comments?

Again, please excuse this post if this is not the proper (best) venue.

**Comment by Akemi** [comment]
if you transcode you will lose some details. you can either use high enough settings that make the encode transparent, with a possible big impact on bitrate/file size, or use a lossless encoding setting.

h264 to h265 is not an up, it's just a difference. newer is not always 'better'.

yes, you can improve upon the source. it's called filtering. obviously a theoretically 'perfect' source can't be improved. though no source is 'perfect'.

closing for obvious reasons.

**Comment by Akemi** [comment]
since the obvious reasons aren't as obvious as i thought.

- unrelated to mpv, the question was meant for handbreak and not mpv
- this is an issue tracker and only issues/feature requests/etc should stay open
- the issue has been answered as good as possible
- there are no "one setting fits them all" it's content dependent
- ... i could go on
