### ISSUE TITLE
mpv cant play av1 video downloaded from youtube by jdownloader

### ISSUE THREAD

**Issue by rezad1393** [mpv-player/mpv#6868]
### mpv version and platform

mpv 0.29.1
archlinux x64

### Expected behavior
should play them

### Actual behavior
mpv ./Brushed\ DC\ Motors\ and\ How\ to\ Drive\ Them\ \(ElectroBOOM\)\ 360p\ 30fps\ AV1\ AAC128-2019.01.25-20m_32s\ \(yO9xIVv8ryc\).mp4
Playing: ./Brushed DC Motors and How to Drive Them (ElectroBOOM) 360p 30fps AV1 AAC128-2019.01.25-20m_32s (yO9xIVv8ryc).mp4
 (+) Video --vid=1 (*) (av1 640x360 29.971fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
File tags:
 Artist: ElectroBOOM
 Comment: https://www.youtube.com/watch?v=yO9xIVv8ryc
 Date: 2019
 Title: Brushed DC Motors and How to Drive Them
[ffmpeg/video] libaom-av1: Failed to decode frame: Corrupt frame detected
Error while decoding frame!
[ffmpeg/video] libaom-av1: Failed to decode frame: Corrupt frame detected
[ffmpeg/video] libaom-av1:   Additional information: Keyframe / intra-only frame required to reset decoder state                                     
Error while decoding frame!
[ffmpeg/video] libaom-av1: Failed to decode frame: Bitstream not supported by this decoder
[ffmpeg/video] libaom-av1:   Additional information: Buffer -1 does not contain a decoded frame                                                      
Error while decoding frame!
[ffmpeg/video] libaom-av1: Failed to decode frame: Corrupt frame detected
[ffmpeg/video] libaom-av1:   Additional information: Reference frame containing this frame's initial frame context is unavailable.                   
Error while decoding frame!
[ffmpeg/video] libaom-av1: Failed to decode frame: Bitstream not supported by this decoder
[ffmpeg/video] libaom-av1:   Additional information: Buffer -1 does not contain a decoded frame  

the video codec used by video
Video
ID                                       : 1
Format                                   : AV1
Format/Info                              : AOMedia Video 1
Format profile                           : Main@L2.1
Codec ID                                 : av01
Duration                                 : 20 min 32 s
Bit rate                                 : 310 kb/s
Width                                    : 640 pixels
Height                                   : 360 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.045
Stream size                              : 45.6 MiB (70%)
Title                                    : ISO Media file produced by Google Inc. Created on: 01/25/2019.
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : av1C

### Log file

https://0x0.st/zVEL.txt

### Sample files

any av1 video I download from youtube by jdownloader
example 
https://www.youtube.com/watch?v=yO9xIVv8ryc

**Comment by CounterPillow** [comment]
Works with libdavid as the av1 decoder, and the file also doesn't play in ffplay with libaom as the decoder. I strongly suspect this is either a libaom or an ffmpeg issue.

**Comment by mc4man** [comment]
Don't use shared ffmpeg here but in the case where shared ffmpeg libs are built with both libaom and libdav1d support then  libaom will unfortunately be the default decoder.
Can be worked around in mpv  with this cli option
--vd=libdav1

**Comment by richardpl** [comment]
Spotted typo there.

**Comment by qyot27** [comment]
> Don't use shared ffmpeg here but in the case where shared ffmpeg libs are built with both libaom and libdav1d support then libaom will unfortunately be the default decoder.

Considering that libaom is the reference software, it being the default if present is the expected behavior, IMO (even though it also alphabetically comes before libdav1d).  And yeah, it has nothing to do with how the libs were built.  Static or shared, it will be the one defaulted to if it's been linked into FFmpeg.

I'd put `vd=libdav1d` into mpv's config file so the user doesn't have to explicitly remember this every time (of course, this is obvious to long-time mpv users, I'm pointing it out for those not well-acquainted with the fact that any cli option can be set in `config`).
