### ISSUE TITLE
Unable to play any stream from any online source, including Youtube.

### ISSUE THREAD

**Issue by Samillion** [mpv-player/mpv#6871]
### mpv version and platform

```
mpv 0.29.0-369-g639ee55df7 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Aug 10 10:57:42 +08 2019
ffmpeg library versions:
   libavutil       56.33.100
   libavcodec      58.55.100
   libavformat     58.30.100
   libswscale      5.6.100
   libavfilter     7.58.100
   libswresample   3.6.100
ffmpeg version: git-2019-08-10-c29d81e7

Windows 10 x64 1903
```

### Reproduction steps

Try to run any Youtube video

`mpv https://www.youtube.com/watch?v=GCscb_zmoIA`

### Expected behavior

Stream plays

### Actual behavior

```
 ytdl_hook: youtube-dl failed: unexpected error ocurred
   cplayer: Failed to recognize file format.
   cplayer: Exiting... (Errors when loading file)
```

### Log file

https://0x0.st/zVDL.txt

### Config file

https://github.com/Samillion/mpv-conf/blob/master/mpv.conf

**Comment by CounterPillow** [comment]
Is your youtube-dl up to date?

**Comment by Samillion** [comment]
Yes it is, and because of your question I discovered why it wasn't working. Completely my fault. I didn't install Microsoft Visual C++ 2010 SP1.

When I tried to run `youtube-dl --version` to show you exact version it informed me.

Closing issue.
