### ISSUE TITLE
Change subtitles position if osc is visible. Similar to Youtube.

### ISSUE THREAD

**Issue by Blast-City** [mpv-player/mpv#6872]
It would be nice if the subtitle position would change when the OSC is visible so that is not hidden beneath the OSC.

Youtube does this when subtitles are enabled.

P.S: Sorry if this as been brought before.

**Comment by wm4** [comment]
Note quite the same, but there is now the "boxvideo" OSC option. Together with --sub-use-margins=no that should have the effect that subtitles are not covered by the OSC.

**Comment by wm4** [comment]
No response, solution suggested -> closing.
