### ISSUE TITLE
Get window position/size? Or window-moved/resized event?

### ISSUE THREAD

**Issue by TheOddler** [mpv-player/mpv#6875]
Is there a way to get the current window position and size, or an event that fires when they are changed?

In the log it is logged when the windows is moved:

    [  34.308][d][vo/gpu/win32] move window: 1953:48

And resized:

    [  37.990][v][vo/gpu] Resize: 1810x1004
    [  37.990][v][vo/gpu] Window size: 1810x1004

Is there a way to get these values or callbacks in a (javascript) script? I couldn't find the event in the documentation sadly, or did I just miss it?

Only thing I could find were `dwidth` and `dheight`, but these represent only the size of the video, not the entire window as I understand it.

**Comment by bitingsock** [comment]
I guess you could just monitor the log message. I couldn't find any exposed values that it stores to.

**Comment by bitingsock** [comment]
But I think those log messages would only be video size too

**Comment by TheOddler** [comment]
> I guess you could just monitor the log message. I couldn't find any exposed values that it stores to.
> edit: mp.get_osd_size() is what the osc uses to scale. it returns the same value as the log messages

Aha, thanks! Though that only gives the size, and then aparently not that of the window, but indeed the same as the size in the log. But still no position.

I was thinking that it might be possible to use `mp.utils.subprocess` and `utils.getpid()` to use some external script to get the position and size. Though haven't figure out yet how :(

**Comment by Akemi** [comment]
you can get window size:
https://github.com/mpv-player/mpv/blob/master/DOCS/man/input.rst dwidth, dheight
or what the osc is doing most likely
https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua mp.get_osd_size()

you can most likely observe the properties or a the reconfigure event.

the mpv core doesn't know about the position of the window. so you can't get that.

**Comment by TheOddler** [comment]
I've been working on this today, and figured out a way using `mp.utils.subprocess` to run some powershell script. It's a bit slow, so I might be looking into other ways, but it does work:

```
Add-Type @"
using System;
using System.Runtime.InteropServices;
public class Window {
    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static extern bool GetWindowRect(IntPtr hWnd, out RECT lpRect);
}
public struct RECT
{
    public int Left;
    public int Top;
    public int Right;
    public int Bottom;
}
"@

$Handle = (Get-Process -Id $Args[0]).MainWindowHandle
$WindowRect = New-Object RECT
$GotWindowRect = [Window]::GetWindowRect($Handle, [ref]$WindowRect)
ConvertTo-Json($WindowRect)
```

This then gives you a json object that has the position and size of the window. You can then use `GetWindowRect` in a similar way to set the position again. Note that this rect doesn't correspond to the thing you would set with `geometry`, as the rect also includes the title bar and such.

**Comment by trappedinspacetime** [comment]
echo '{ "command": ["get_property", "geometry"] }' | socat - /tmp/mpvsocket | jq .data | tr '"' ' ' | cut -d'.' -f 1

**Comment by partap** [comment]
@trappedinspacetime I've tried this, but it only returns the value of --geometry passed in at startup...it doesn't appear to return the actual current window size/position.

Also, if you set the value using `set_property`, it updates the value returned by `get_property` but doesn't actually change the window size or position.

...on MacOS, at least...I haven't actually tried on Linux, but I need a cross-platform method to get/set window position programmatically
