### ISSUE TITLE
[Feature request] Support flat playlist containing title as comments

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#6879]
### mpv version and platform

mpv v0.29.1+git3~trusty on Ubuntu Trusty 64

### Reproduction steps

I have a flat playlist file containing URLs and their corresponding titles (like shell comments for the latter) : 
```
url1 # title of video1
url2 # title of video2
url3 # title of video3
...
```

### Expected behavior

The comments are ignored and only the URLS are used.

### Actual behavior

```
$ command mpv --no-config --ytdl-raw-options='ignore-config=' --playlist smallville__videa_hu.urls 
[playlist] Reading plaintext playlist.
Playing: http://videa.hu/videok/vicces/smallville-season-1-episode-pilot-clark-kent-cult-vCOdZcepD8attVUK # Smallville season 1, episode 1, clark kent, cult, episodes - Videa
[ffmpeg] http: HTTP error 400 Bad Request
Failed to open http://videa.hu/videok/vicces/smallville-season-1-episode-pilot-clark-kent-cult-vCOdZcepD8attVUK # Smallville season 1, episode 1, clark kent, cult, episodes - Videa.
[ytdl_hook] ERROR: Could not find XML element video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[ytdl_hook] youtube-dl failed: unexpected error ocurred 
```

**Comment by LaserEyess** [comment]
You can do this with an [m3u playlist](https://en.wikipedia.org/wiki/M3U#Examples)

**Comment by zc62** [comment]
There is no such thing as a "flat playlist". `#` may mean "comments" to you, but it does not to URLs, to file paths, etc. I think one can easily find cases that ignoring space plus `#` (and following contents) introduces troubles. Just follow standard formats.

**Comment by sebma** [comment]
@zc62 You're right, I could find it [here](https://en.wikipedia.org/wiki/Playlist#Types_of_playlist_files) so I'm closing this issue right away.
