### ISSUE TITLE
the "--video-unscaled=yes" option scales if a video is bigger than my screen

### ISSUE THREAD

**Issue by beroal** [mpv-player/mpv#6880]
### mpv version and platform

ArchLinux
pacman -Q mpv
mpv 1:0.29.1-8

### Reproduction steps

I have a monitor of resolution 1680x1050. I run `mpv --video-unscaled=yes ${FILE}` on a video of size 1920x816.

### Expected behavior

The player should crop the video on the left and on the right.

### Actual behavior

The player scales down the video, so the whole frame is visible. I confirmed this behavior on other videos of size 1980p. This option worked some time ago, but I cannot tell when it stopped working. A video which is **smaller** than my monitor resolution (for example, 720p) is not scaled with this option.

### Log file

[mpv.log](http://www.beroal.in.ua/prg/linux/mpv.log)

**Comment by CounterPillow** [comment]
Does it work with the gpu VO rather than the vdpau VO?

**Comment by beroal** [comment]
> Does it work with the gpu VO rather than the vdpau VO?

Yes! Thank you. I guess I need to remove `vo=vdpau` from my “mpv” configuration.
