### ISSUE TITLE
AAC multichannel output? [question]

### ISSUE THREAD

**Issue by tomeq82** [mpv-player/mpv#6882]
### mpv version and platform
Platform: Windows 10 build 1903
[cplayer] mpv 0.29.0-372-g80552ab28e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Tue Aug 20 16:57:49 +08 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.33.100
[cplayer]    libavcodec      58.55.100
[cplayer]    libavformat     58.31.101
[cplayer]    libswscale      5.6.100
[cplayer]    libavfilter     7.58.100
[cplayer]    libswresample   3.6.100
[cplayer] ffmpeg version: git-2019-08-18-cff30909
[cplayer]
[cplayer] Configuration: /home/shinchiro/build/build64/packages/mpv-prefix/src/mpv/waf configure --enable-static-build --enable-pdf-build --disable-manpage-build --enable-libmpv-shared --enable-lua --enable-javascript --enable-libarchive --enable-libass --enable-libbluray --enable-dvdread --enable-dvdnav --enable-uchardet --enable-rubberband --enable-lcms2 --enable-openal --enable-spirv-cross --enable-vulkan --enable-vapoursynth --prefix=/home/shinchiro/build/build64/install/mingw

### Reproduction steps

Try to play any file which has audio encoded as AAC mutlichannel (6 channels)

### Expected behavior

File would be played with PCM 6 channel output OR if it is possible, bitstream AAC 6 channels

### Actual behavior

File is played as PCM stereo, no matter what is in the configuration file.

This issue is more like question, is there any specific configuration that is needed to be added to mpv.config to have AAC multichannel audio being output as PCM multichannel?

My audio section of the configuration looks like this:
ao=wasapi
audio-spdif=ac3,dts,dts-hd,eac3,truehd
audio-channels=2.0,5.1,7.1,2.1
#ad-lavc-downmix=no

I tried changing "audio-channels" to auto, ad-lavc-downmix to "no" or "yes". No change. I still get just PCM stereo on AAC multichannel files. 

All other, DTS, DTS-HD, AC3, Dolby TrueHD works like a charm as a bitstream. I understand that AAC bitstreaming might be difficult (some audio processors do support it though) I would like to receive decoded AAC 6-ch stream as PCM 6-ch stream.  

Is it possible? Am I missing something?

**Comment by zc62** [comment]
log file?

Probably you should write the `audio-channels` in a way that stereo does not appear first. Just like what the manual writes:
```
audio-channels=7.1,5.1,stereo
```
and with
```
ad-lavc-downmix=no
```

**Comment by CounterPillow** [comment]
>Probably you should write the `audio-channels` in a way that stereo does not appear first.

I've read some of the code relating to how the best audio channel mapping is chosen from the set, and in theory, it shouldn't be dependant on the order, since it iterates them comparing the currently best to the next, and if the next is better as determined by several checks it sets currently best to that.

I think a clue here might be that all other multichannel ones he tried work as a passthrough bitstream, so maybe something with the AO is wonky. A log file generated with `--log-file` would indeed be useful.

**Comment by tomeq82** [comment]
Log file is here: [https://0x0.st/zWWT.log](url)

I tried messing with:
`ad-lavc-downmix=no`

but this did just nothing at all. 

What is interesting, when I put "aac" as a format to bitstream I got silence on my receiver. That is correct as my Yamaha RX-V483 doesn't support AAC over HDMI.

**Comment by CounterPillow** [comment]
```
[   1.459][d][ao/wasapi] Probing formats
[   1.469][v][ao/wasapi] Trying 5.1 float (32/32 bits) @ 48000hz (shared) -> ok
[   1.469][v][ao/wasapi] Closest match is stereo float (32/32 bits) @ 48000hz
[   1.469][v][ao/wasapi] Accepted as stereo float @ 48000hz -> stereo float (32/32 bits) @ 48000hz (shared)
```

Ok, so I guess there really is something up with the AO. The relevant wasapi code is here https://github.com/mpv-player/mpv/blob/802f594a857c703ac88e946d14b69cd3b6eb6006/audio/out/ao_wasapi_utils.c#L464-L496

Something makes it think that stereo is the closest match, and looking at the code this could be if the ao channel map is invalid somehow? (line 472-473)

Either way, best to check your Windows audio output device settings, namely those of the device "Panasonic-TV (NVIDIA High Definition Audio)". I'm not exactly sure what to look for though.

**Comment by tomeq82** [comment]
Thanks for the suggestion, I have checked the Windows audio settings and again set it up to "5.1" setup (this is what I have despite the receiver can do 7.1) and.... issue fixed? :) It looks like it does 6 channels now. 

Log file after change of the settings in Windows: [https://0x0.st/zWWu.log](url)

**Comment by CounterPillow** [comment]
```
[   0.911][v][ao/wasapi] Accepted as 5.1 float @ 48000hz -> 5.1 float (32/32 bits) @ 48000hz (shared)
```

Yep, appears to work now. Congrats!
