### ISSUE TITLE
How to use `mp.utils.subprocess`?

### ISSUE THREAD

**Issue by TheOddler** [mpv-player/mpv#6883]
I've been trying out some scripting for mpv, currently in javascript since I need to write/read files. Now I was trying to use `mp.utils.subprocess`, so I tried to test it with a simple `echo` command, however in the log I get `"error": "init", "killed_by_us": false` indicating the process couldn't be started.

    var reply = mp.utils.subprocess({args: ["echo", "testtest123"]});
    dump(reply);

So what am I doing wrong? Or how does subprocess work?

Note: I'm using Windows 10.

Thanks!

**Comment by TheOddler** [comment]
I found that running echo directly doesn't work, however using subprocess to run powershell does work:

    mp.utils.subprocess({args: ["powershell", ...

Is that the best way to run these kinds of scripts? I'm trying to run a ps1 file do to some stuff mpv can't.

**Comment by CounterPillow** [comment]
is `echo` even a separate binary on Windows or is it just a builtin shell command?

As far as I know, subprocess does not run your command in a shell with shell parsing and shell builtins.

**Comment by TheOddler** [comment]
> 
> 
> is `echo` even a separate binary on Windows or is it just a builtin shell command?
> 
> As far as I know, subprocess does not run your command in a shell with shell parsing and shell builtins.

I think you might be right, but I'm not sure. In the documentation it indeed says that subprocess doesn't run the command in a shell, so seems like you're right.
