### ISSUE TITLE
Resuming playback with G-Sync causes stutter

### ISSUE THREAD

**Issue by rkfg** [mpv-player/mpv#6884]
### mpv version and platform
0.29.1

### Reproduction steps
Have a G-Sync compatible monitor, have it enabled. Play a video, pause it, then resume.

### Expected behavior
Video resumes smoothly, like in VLC.

### Actual behavior
Video FPS is very low during the first 1-2 seconds after resuming, then it's back to normal.

### Log file

https://pastebin.com/Mwg4tfLp

I tried this with an empty home directory to make sure my configs don't affect this. It happens nevertheless. I suspect the problem is that after pausing the video MPV stops redrawing the screen completely (i.e. there are 0 FPS) and it stalls the G-Sync module. After resuming it starts adapting to FPS from 0 to 60 and it takes a noticeable time. I realize that it might be an issue with just my monitor (Dell S2417DG @ 165 Hz) but I'd like to be able to fix this. It doesn't happen in VLC, for example, that reduces the refresh rate to 10 FPS when paused (I enabled the NVIDIA's graphics API visual indicator that also shows FPS).

When the video is paused in MPV the indicator shows 60 FPS but it's not correct because the screen doesn't refresh so it's just an old frame. If I start moving the mouse and the OSD appears the FPS is just 3-4 but if I unpause the video while moving the mouse it resumes smoothly. So I'm pretty sure it's because of this. I'd be happy to somehow force the screen refresh when the video is paused at 1-4 FPS, maybe using a Lua script or something.

I had to disable G-Sync for MPV for now because of this issue.

**Comment by eXmendiC** [comment]
Same issue for me, but I figgured out some stuff.
The issue only happens for me when I use "video-sync=display-resample" and when I have G-Sync enabled (on any monitor) in the nvidia control panel. 

I also noticed something very weird.
When I'm on my TV (second monitor without G-Sync) the problem happens as well, even when my G-Sync screen is off or unplugged. A workaround that worked for me is to plug / turn on my G-Sync monitor and disable G-Sync at all, then enable it back with just "Enable for full screen mode".

**Comment by haasn** [comment]
I don't know if this is relevant for the original problem, but I wanted to point out that using display sync and g-sync at the same time does not make a lot of sense (they're trying to solve the same problem in incompatible ways).

I'd love to help test and debug all this stuff but I don't have a g/free/adaptive-sync capable monitor to test on.

**Comment by rkfg** [comment]
I didn't use display sync, I explicitly stated that I used a new home directory to be sure no config options I might have set affect this behavior so this is what I see with the default options. I'm pretty sure making force screen refresh at low FPS when the video is paused would fix this. I just don't know how to do that except showing the OSD with mouse move.

**Comment by wm4** [comment]
In normal (non display-sync) mode, mpv doesn't do anything special. You might have to report this to nvidia instead. Does it happen with --vo=sdl or --vo=vdpau?

**Comment by rkfg** [comment]
Same issue with SDL but starts smoothly with vdpau. With vdpau output G-Sync isn't used at all, there's no indicator and I can tell by moving the mouse cursor that the monitor runs at full 165 Hz. The movement is choppy when G-Sync is active because it switches to 30 Hz if the video has 30 FPS.

I fully realize this is not a bug or an issue with MPV per se, just a corner case of G-Sync, driver or my monitor (probably the latter as not everyone who commented here experiences this). I was just asking for help to make MPV redraw the screen when video is paused so that the G-Sync module doesn't stall.

**Comment by philipl** [comment]
Did you try using vulkan instead of opengl? My experience with g-sync has been that vulkan plays back better than opengl. I can't really reproduce your behaviour (and I have a freesync monitor here in GSync compatibility mode).

**Comment by rkfg** [comment]
I tried to use Vulkan but hit #6124 and I don't feel like rebuilding it all. I don't think it would solve anything because the issue is more low level than just API.  I tried `mplayer2` and it shows the same issue so it's very likely just my monitor.

**Comment by rkfg** [comment]
For some reason now Vulkan works with MPV for me. I didn't change anything, just updated the system a couple of times, maybe the current MPV 0.30.0-dmo1 from Debian Multimedia included Vulkan to the build. Nevertheless, the issue persists.

**Comment by rkfg** [comment]
Now, another interesting thing is GPU context. By default MPV chooses `x11egl` and in this mode the NVIDIA visual indicators don't work so I can't see the graphics API used, FPS and whether G-Sync works or not (it does because the cursor movement is not smooth but there's no "GSYNC" green label in the top right corner). I can see all those indicators switching to `x11` context with `--gpu-context=x11` (or `gpu-context=x11` in the config file). Also, it's only possible to turn G-Sync off selectively (per process) from `nvidia-settings` for OpenGL but not Vulkan. But that's up to NVIDIA to fix/implement of course.

**Comment by ValZapod** [comment]
> now Vulkan works with MPV for me. I didn't change anything, just updated the system a couple of times

Vulkan maybe works because it is VRR API aware API ;) , i.e. does support actual manipulation of G-sync and may "just work". OpenGL on the on the hand is not VRR aware.

**Comment by wm4** [comment]
> Vulkan maybe works because it is VRR API aware API ;) , i.e. does support actual manipulation of G-sync and may "just work". OpenGL on the on the hand is not VRR aware.

Uh, no.

**Comment by Dudemanguy** [comment]
If this is still a problem with 0.36, please open a new issue.
