### ISSUE TITLE
How to choose Traditional Chinese subtitle automatically?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#6885]
### mpv version and platform
mpv 0.29.0-372-g80552ab28e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.33.100
   libavcodec      58.55.100
   libavformat     58.31.101
   libswscale      5.6.100
   libavfilter     7.58.100
   libswresample   3.6.100
ffmpeg version: N-94597-g74e6800381
### Reproduction steps
slang=chi
### Expected behavior
Choose Tradtional Chinese
### Actual behavior
Choose Simplified Chinese

**Comment by qyot27** [comment]
https://www.loc.gov/standards/iso639-2/php/code_list.php

The ISO 639-2 character code for Traditional Chinese is *zho*.

**Comment by laichiaheng** [comment]
Nobody uses the zho for Traditional Chinese, they use chi by adding a name "Traditional" behine it.

**Comment by CounterPillow** [comment]
Sounds like Chinese pirates should conform to ISO standards then instead of abusing track titles for something they're not for.

**Comment by laichiaheng** [comment]
It doesn't look like Chinese pirates at all.

**Comment by qyot27** [comment]
It looks like I misinterpreted that table earlier, sorry.  From a little more digging, there is no ISO 639-2 (or even 639-3, maybe?) code to differentiate between the writing forms of Chinese.  What *chi* and *zho* actually are, are simply codes designating the ISO's internal English-based organizational system for the language codes (*chi*), and one that's based on the native name for the language (*zho*, at least I guess for some dialects).

This is actually a known issue with the language selection in the Matroska format itself:
https://gitlab.com/mbunkus/mkvtoolnix/wikis/Chinese-not-selectable-as-language

So yeah, putting 'Traditional' or 'Simplified' in the title tags looks like a necessary kludge until the Matroska specifications update to allow setting that distinction.

**Comment by zc62** [comment]
Probably you can write a script to detect the track title (through this property: https://mpv.io/manual/master/#command-interface-track-list/n/title) to auto-select the TC track. Otherwise if multiple `chi` tracks exist, mpv chooses the one with smaller track id (in your case the one who made the mkv file chose to put SC before TC). 

Or just write a folder-specific/file-specific `mpv.conf` to manually set the `sid`.

**Comment by laichiaheng** [comment]
@zc62 I don't understand, what does the N suppose to mean in `track-list/N/lang`
Is the syntax correct?
```
local utils = require 'mp.utils'
local msg = require 'mp.msg'
mp.get_property_native(track-list/N/chi)
```

**Comment by zc62** [comment]
No. You should first query the total number of tracks: [`track-list/count`](https://mpv.io/manual/master/#command-interface-track-list/count), then loop it.
> Replace N with the 0-based track index.

See https://mpv.io/manual/master/#command-interface-track-list

In the loop of `N` from `0` to `count-1`, compare string property obtained from `track-list/N/title` with string `Traditional`, or other words you see that people use to mark TC tracks.

**Comment by zc62** [comment]
I just wrote one. @laichiaheng 

```lua
mp.register_event("file-loaded", function()
    local count = mp.get_property_native("track-list/count")
    for N = 0,count-1,1 do
        local type = mp.get_property_native("track-list/" .. tostring(N) .. "/type")
        if type == "sub" then
            local lang = mp.get_property_native("track-list/" .. tostring(N) .. "/lang")
            if lang == "chi" then
                local title = mp.get_property_native("track-list/" .. tostring(N) .. "/title")
                if title == "Traditional" then
                    local id = mp.get_property_native("track-list/" .. tostring(N) .. "/id")
                    mp.commandv("set", "sid", id)
                    return
                end
            end
        end
    end
end)
```
Change the line
```lua
if title == "Traditional" then
```
to
```lua
if title == "Traditional" or title == "繁体中文" then
```
if you want.

**Comment by CounterPillow** [comment]
Perhaps it would be worth it to have a `--stitle` option which selects a more specific track if the `--slang` selection has no unambiguous one result, may be useful for more than just differentiating between traditional and simplified Chinese.

**Comment by laichiaheng** [comment]
@zc62 How do you get this syntax: `"track-list/" .. tostring(N) .. "/type"`

**Comment by laichiaheng** [comment]
> ```lua
> if title == "Traditional" or title == "繁体中文" then
> ```

By the way, it should be "繁體中文"

**Comment by CounterPillow** [comment]
What `..` does is it joins two strings, in other programming languages this is usually done with `+` but Lua uses `..` for string concatenation.

**Comment by zc62** [comment]
@CounterPillow I actually had a similar feature request, see #5133.
I mentioned
> Even for built-in PGS subtitles, slang alone can also have troubles. For example, Simplified Chinese and Traditional Chinese share the code chi.

**Comment by zc62** [comment]
@laichiaheng Just try if my script works or not. If you want to learn scripting for mpv, learn lua first.

**Comment by laichiaheng** [comment]
@zc62 Yes, it works.

**Comment by Akemi** [comment]
see #5133.

**Comment by teohhanhui** [comment]
There's https://github.com/CogentRedTester/mpv-sub-select which is already listed on https://github.com/mpv-player/mpv/wiki/User-Scripts

Seems like the best solution without having to write your own script.
