### ISSUE TITLE
mpv --hwdec doesn't work when my discrete nvidia card is enabled

### ISSUE THREAD

**Issue by lilydjwg** [mpv-player/mpv#6888]
### mpv version and platform

mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Aug  6 14:50:47 CEST 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2

on Arch Linux.

### Reproduction steps

On my ThinkPad T470p laptop, I have:
```
>>> lspci | grep -E 'VGA|3D'
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 630 (rev 04)
02:00.0 3D controller: NVIDIA Corporation GM108M [GeForce 940MX] (rev a2)
```

After `modprobe nvidia` the following no longer works (it works when nvidia is not loaded / enabled).

```
mpv --hwdec=auto some_video
```

### Expected behavior

It works as before, or at least I can pass some argument to make it work.

### Actual behavior

With `--hwdec=auto|vaapi|vdpau|nvdec`, errors occur and I get a black video output.

With `--hwdec=auto-copy|vaapi-copy|vdpau-copy|nvdec-copy` it manages to play the video, at a higher CPU usage (~80% for a 4K video, ~35% for a 1080p).

It seems that mpv insists to use my discrete GPU, which is known to not work. My integrated Intel GPU works fine but I haven't find a way to tell mpv to use that.

DIsabling the nvidia GPU should recover mpv, but I failed to do so due to mysterious "module is in use" errors (I used my nvidia GPU to do some CUDA computing and then found myself unable to watch video while keeping my fan quiet).  

### Log file

https://0x0.st/zWkH.txt

### Sample files

It happens to all video files I've tested.

**Comment by j605** [comment]
You just have an old card.
```
[   0.915][e][ffmpeg/video] hevc: Hardware is lacking required capabilities
```

**Comment by lilydjwg** [comment]
> You just have an old card.

Yes, that nvidia card doesn't support video acceleration. But my integrated one does.

**Comment by philipl** [comment]
We're missing a bunch of the story here. Your log says that x11probe is returning an nvidia glx context. If you are booting into X without the nvidia card configured and then doing `modprobe nvidia`, that will enable cuda but it will not enable any X integrations, and the intel will drive your desktop. From what I see here, your nvidia chip is driving your desktop, which means that it will prefer nvdec/vdpau and vaapi won't work.

Probably the best thing you can do, ignoring the battery life implications, is to use the new prime offload capability in the latest nvidia driver.

http://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html

It will let you drive the desktop with the intel gpu and selectively use the nvidia one for other programs. I've used this successfully and can switch from nvdec on nvidia to vaapi on intel.

**Comment by lilydjwg** [comment]
I'm sorry I realize that my X was running on nvidia. I forgot about a reboot and things had changed.
Thanks for the link, it looks nice.
