### ISSUE TITLE
Black artifacts at top of screen when playing any video.

### ISSUE THREAD

**Issue by rigopoui** [mpv-player/mpv#6889]
### Reproduction steps
Play any video file, with any -vo

### Expected behavior
File playing without artifacts (had been fine up until 1-2 months ago)

### Actual behavior
Flickering black artifacts mostly near the top of the screen

### Log file

https://pastebin.com/mtttuC9u

Here's a screenshot: https://imgur.com/njLmylR

Anyone else had a similar problem to this? I've tried downgrading mpv, ffmpeg and intel drivers, nothing solved my issue.

By the way, this issue still occurs even when I run mpv with the GDK_PLATFORM=x11 flag enabled and running it in Xwayland, so it doesn't seem to be a wayland issue.

**Comment by CounterPillow** [comment]
Does it still happen if you disable hwdec?

**Comment by rigopoui** [comment]
Doesn't occur when hwdec is disabled.

**Comment by rigopoui** [comment]
Compiling and installing the mpv-git package from the AUR instead of the prebuilt mpv package seems to have fixed the issue. My guess would be that the prebuilt version was compiled with some outdated buggy library, though I don't know which one.
