### ISSUE TITLE
Follow the issue template. Namely, provide a log file. It doesn't help when you're referencing an issue refering to vdpau when you are on Windows, a platform that doesn't use vdpau.

### ISSUE THREAD

**Issue by markfilipak-windows** [mpv-player/mpv#6892]
Follow the issue template. Namely, provide a log file. It doesn't help when you're referencing an issue refering to vdpau when you are on Windows, a platform that doesn't use vdpau.

_Originally posted by @CounterPillow in https://github.com/mpv-player/mpv/issues/6891#issuecomment-524725189_

**Comment by markfilipak-windows** [comment]
What sort of log file?

And I don't know what 'vdpau' is. I'm just trying to report that the issue exists in the current version of MPV. Would it be better to report it by chat?

**Comment by CounterPillow** [comment]
The issue template, which you will see when opening a new issue through the "new issue" button, will tell you how to generate a log file. Don't use the "Reference in new issue" function. Right now all you're doing is spamming our issue tracker with useless noise.

**Comment by markfilipak-windows** [comment]
If "Reference in new issue" is not the appropriate way to continue a closed issue, then it shouldn't exist. It's not my fault that github is a user-hostile environment.

**Comment by CounterPillow** [comment]
Ok dude if you don't actually want to have anything fixed then please just leave instead of wasting our time.

**Comment by markfilipak-windows** [comment]
Don't worry. I won't come back to report bugs. Goodbye.
