### ISSUE TITLE
mpv native on wayland: unable to play a video

### ISSUE THREAD

**Issue by tristelune1** [mpv-player/mpv#6895]
Hello,

I'm trying to play some videos under wayland, but I can only listen to music. If it's not the right place to ask, please tell me where I can ask. I can't see an error which could help me. 

### mpv version and platform

Mpv 0.29.1 
Crux Linux 3.5
Sway 1.2 with wayland

### Reproduction steps

I try to watch a video with:

    mpv --gpu-context=wayland -v When\ not\ knowing\ Math\ can\ cost\ you\ \$15,000-BbX44YSsQ2I.mkv

and unfortunately I get an error.

### Expected behavior

The video should be played. 

### Actual behavior

The following error is given:

````
Playing: When not knowing Math can cost you $15,000-BbX44YSsQ2I.mkv
 (+) Video --vid=1 (*) (h264 320x240 11.988fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
Error opening/initializing the selected video_out (--vo) device.
Video: no video


Exiting... (Errors when loading file)
````

### Log file

The full log file is here: [http://pastebin.fr/58075](http://pastebin.fr/58075)

### Configuration

I compiled mpv with the following options:

	./waf configure ${PKGMK_MPV} \
		--prefix=/usr \
		--disable-sdl \
		--enable-libarchive \
		--enable-wayland \
		--enable-wayland-protocols \
		--enable-wayland-scanner \
		--enable-vaapi-wayland \
		--enable-gl-wayland \
		--enable-libmpv-shared \
		-j ${JOBS-1}

The packages wayland and wayland protocols are installed. There is no problem with Xorg or Xwayland. But I would like to get mpv native on wayland. 

Thank you!

**Comment by Dudemanguy911** [comment]
>vo/vdpau/x11

Do you have `vo=vdpau` or something set somewhere in your config? I don't think vdpau works on wayland. va-api apparently does so maybe try that if you need hardware decoding. Regardless, mpv probably should just display some error and fail in this case instead of continuing to run without any video.

**Comment by CounterPillow** [comment]
@Dudemanguy911 He doesn't have anything in the config, the vdpau VO is one of the fallbacks if gpu doesn't work

**Comment by CounterPillow** [comment]
@tristelune1 please use `--log-file=somefilenamehere.txt` to generate a log file, that way we can see what config options are applied.

**Comment by tristelune1** [comment]
I didn't set `vo=vdpau` somewhere, or without knowing it. I have the standard config files as far as I know. 

The full log file is here: [http://pastebin.fr/58088](http://pastebin.fr/58088)

**Comment by Dudemanguy911** [comment]
Well that's a whole different story then. What version of wlroots are you using? I'll see if I can reproduce this on my end.

**Comment by haasn** [comment]
Is mesa built with wayland support?

**Comment by tristelune1** [comment]
> Is mesa built with wayland support?

It was the problem. I compiled mesa with

````
	meson build \
		--prefix=/usr \
		--sysconfdir=/etc \
		-Dllvm=true \
		-Dgbm=true \
		-Dgles1=true \
		-Dgles2=true \
		-Dosmesa=gallium \
		-Dgallium-xa=true \
		-Dgallium-vdpau=true \
		-Dshared-llvm=true \
		-Dplatforms=x11,drm \
		-Dgallium-drivers=r300,r600,svga,swrast,radeonsi,nouveau \
		-Dvulkan-drivers=amd,intel \
		-Dglvnd=true
````

And under platforms I forgot `wayland`. It should be:

````
	-Dplatforms=x11,wayland,drm \
````

Now it works, thank you!

**Comment by NicTanghe** [comment]
Trying on fedora gives me the following error
```
❯ mpv Losless.mov
 (+) Video --vid=1 (*) (dnxhd 1920x1080 48.000fps)
 (+) Audio --aid=1 (*) (pcm_s24le 2ch 48000Hz)
[vo/gpu/wayland] GNOME's wayland compositor lacks support for the idle inhibit protocol. This means the screen can blank during playback.
VO: [gpu] 1920x1080 yuv444p10
AO: [pulse] 48000Hz stereo 2ch s32
AV: 00:00:00 / 00:00:41 (0%) A-V:  0.008 Dropped: 1

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).


AV: 00:00:00 / 00:00:41 (0%) A-V:  1.009 Dropped: 2
[lavf] Too many packets in the demuxer packet queues:
[lavf]   video/0: 86 packets, 157856096 bytes
[lavf]   audio/1: 0 packets, 0 bytes
AV: 00:00:02 / 00:00:41 (7%) A-V:  0.010 Dropped: 11
Audio device underrun detected.
AV: 00:00:05 / 00:00:41 (13%) A-V:  0.000 Dropped: 83

Exiting... (Quit)
```
