### ISSUE TITLE
Directory recursion off

### ISSUE THREAD

**Issue by kickerofelves** [mpv-player/mpv#6902]
How do I turn off directory recursion? When I issue `mpv *` and there is one or more directories in the path, I want mpv to skip them and not search them for playable files. I searched the man page for several terms but found nothing.

**Comment by CounterPillow** [comment]
You can use `mpv $(find . -maxdepth 1 -type f)` instead I guess

**Comment by Argon-** [comment]
Not sure if this is within scope of mpv. After all, you explicitly feed directories to it but want it to ignore them. The right way to go is not feeding mpv directories when you don't want mpv to look at them. In case of zsh this can be accomplished with `mpv *(.)`.

**Comment by kickerofelves** [comment]
A directory is not a playable file.  Mplayer which mpv is based on, did not do it.  It is a design choice of mpv to recurse directories. So it is entirely within the scope of mpv.

**Comment by Argon-** [comment]
Well, mplayer is a different piece of software and when it decides not to act on directories then that's its choice.

I'm not aware of an option to prevent mpv from adding directory content to its internal playlist, I'm afraid.

**Comment by Akemi** [comment]
can be worked around with a script or the shell.

**Comment by UnixCro** [comment]
`mpv $(find . -maxdepth 1 -type f)` doesn´t work. But `mpv*(.)` works without problems. 

Many thanks

**Comment by 07416** [comment]
An option not to recurse into _subdirectories_ would be useful in some instances. I currently pipe fd or find output to mpv when needed:

    $ fd --max-depth 1 --type file . ~/Videos/ | mpv --playlist=-

**Comment by guidocella** [comment]
`--directory-mode=lazy`

**Comment by Hrxn** [comment]
But this still opens subdirectories, no?

What you want is probably `--directory-mode=ignore`?

**Comment by 07416** [comment]
> But this still opens subdirectories, no?
> 
> What you want is probably `--directory-mode=ignore`?

Yes, `--directory-mode=lazy` recurses into subdirs. `--directory-mode=ignore` does not, only reads the parent directory.
