### ISSUE TITLE
Topbar OSC spacing issue

### ISSUE THREAD

**Issue by cvod** [mpv-player/mpv#6904]
version: 0.29.0-373-gb539eb222b (Windows)
log: https://pastebin.com/raw/0m6UeGNm

The spacing on the OSC between the time remaining and audio track selection changes whether "layout=topbar" or "layout=bottombar" is used in osc.conf. The "topbar" causes there to be a gap that is not present with "bottombar."

visual: https://imgur.com/a/hnc3D0i

**Comment by Akemi** [comment]
can reproduce that before and after the recent OSC changes. @medhefgo are you interested in fixing this?

**Comment by medhefgo** [comment]
I can't reproduce

**Comment by wm4** [comment]
Not reproducible, old version -> closed.

**Comment by Akemi** [comment]
i can still reproduce this issue with current master.

https://0x0.st/z3YQ.log
