### ISSUE TITLE
Keeping Res Changes locked to position on desktop

### ISSUE THREAD

**Issue by FunkiPorcini** [mpv-player/mpv#6906]
### mpv version and platform
mpv 2.0.0.0

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
snap-window on, and run a m3u8 stream via streamlink/livestreamer, etc.

### Expected behavior
When video is resize3d within the stream (say a commercial break at a different res) it should not resize the window, and if it does, it there should be an option to select what corner it shrinks or grows from, i.e. top right corner. So that when it goes back to the program it returns to its position and size without moving.

### Actual behavior
Resizes via center screen to resolution

### Log file
N/A

I'm not sure if this is actually possible. I've tried no-keepaspect and video-align-y/x, but neither seem to do the trick. When I watch a stream via vlc or mpchc, the commercial breaks that aren't 1280x720 simply zoom the res to the locked main stream res of 1280x720. In mpv, the commercial brings the entire mpv window down to 900x576, and then back to 1280x720 afterward, and I have to reposition the window again because it's gone off the edge of the screen. I think this can be corrected if I either a) the new res zooms into the main res like the other players, or b) if I can have it resize/lock from the top right corner, thus when it changes back to the original res it goes outward and stays in the top right corner of my monitor.

**Comment by Akemi** [comment]
there is no mpv 2.0.0.0. also no log, that way we could at least know the real mpv version.

i believe @TheAMM had a script for keeping the size. otherwise could use --geometry/--autofit option to lock the video size.

there is no way to resize to a corner.

**Comment by FunkiPorcini** [comment]
There's no mpv 2.0.0.0... https://i.imgur.com/V7fkYa8.jpg excuse me if I don't believe anything you write.

**Comment by zc62** [comment]
There is no mpv 2.0.0.0, for absolutely sure. That's just the "File Version" that I don't know why would appear to be 2.0.0.0. See mine:
![xx](https://user-images.githubusercontent.com/17048823/64152027-afb5f880-cdf9-11e9-9f2b-b2d838f245e5.png)
Current version is 0.29.

According to the date, yours is wayyyyyyy outdated. Why log file is N/A? Because you don't know how to generate a log?

**Comment by TheAMM** [comment]
The script @Akemi mentioned: https://gist.github.com/TheAMM/5e07ad787dd95d76131b61840f403a79

**Comment by CounterPillow** [comment]
I'm glad you're gone. :tada:
