### ISSUE TITLE
[Feature Request] Open file chooser if an user left clicks on the "Drop files to play here." screen.

### ISSUE THREAD

**Issue by Blast-City** [mpv-player/mpv#6910]
On Github, when an user clicks on the "Attach files by dragging & dropping. selecting or pasting them." area of the text box, the file chooser opens and file(s) to upload can be selected.

What if mpv had a similar feature when an user pressed the left click on the "Drop files to play here." screen?

This way it wouldn't be required to open two apps to play files on mpv.

**Comment by qmega** [comment]
Take a look at the [User Scripts](https://github.com/mpv-player/mpv/wiki/User-Scripts). Looks like a few that might do what you want, depending on what platform you're on.

Opening the system file picker like GitHub does would require the use of some kind of UI library or specific per-platform UI code. That kind of stuff is generally out of scope for core mpv and is unlikely to be added. If you can't get what you want by scripting or you want more of a full GUI experience, you could try [Applications using mpv](https://github.com/mpv-player/mpv/wiki/Applications-using-mpv).
