### ISSUE TITLE
How to get a media file to play at a certain resolution 

### ISSUE THREAD

**Issue by shirishag75** [mpv-player/mpv#6911]
I am using the following mpv version - 

```
$ mpv --version
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.14.100 (runtime 56.22.100)
   libavcodec      58.18.100 (runtime 58.35.100)
   libavformat     58.12.100 (runtime 58.20.100)
   libswscale      5.1.100 (runtime 5.3.100)
   libavfilter     7.16.100 (runtime 7.40.101)
   libswresample   3.1.100 (runtime 3.3.100)
ffmpeg version: 4.1.4-1+b2
```

This is on Debian testing/bullseye machine - 

```
$ lsb_release -da
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
```

I am trying to figure out how to get a certain resolution on a media file ?

For instance if I want to output a video to 1280x720p even though it has higher resolution . I did look at the man page 

I did look at https://mpv.io/manual/master/#video-output-drivers but didn't find anything which would help me. Looking to know more.

**Comment by qmega** [comment]
https://mpv.io/manual/stable/#options-geometry

```
mpv --geometry=1280x720 your-video-here
```

**Comment by shirishag75** [comment]
@Akemi thank you :)
