### ISSUE TITLE
Toggling Full-Screen Bug

### ISSUE THREAD

**Issue by mortyobnoxious** [mpv-player/mpv#6912]
When i quickly toggle between _Full Screen Mode_ and _Windows Mode_, top rigt icons turns into Windows 7 icons.

![0b6fe3f74442130](https://user-images.githubusercontent.com/42044258/64336595-0ed86080-cfe6-11e9-95af-87b6d50e7dfe.gif)

using latest Windows builds by shinchiro (git).

**Comment by zc62** [comment]
Can't reproduce, and you don't have a log. It should be related to your (Windows) settings and/or is a windows bug.

**Comment by mortyobnoxious** [comment]
did you do this while playing a video?

**Comment by zc62** [comment]
Seems to occur in rare conditions (like once every 50+ switches). I still don't think this is a mpv bug. At least if you don't post a log and don't point out where the log looks wrong, there is no way to get this "fixed".

**Comment by blackarcher21** [comment]
this is happened only with gpu-api=vulkan as far as I can see.

**Comment by wm4** [comment]
No information -> closed.
