### ISSUE TITLE
[Question] how to create mp_image and draw osd?

### ISSUE THREAD

**Issue by ksharindam** [mpv-player/mpv#6915]
I want to replace OpenGL ES layer of osd with a dispmanx layer.
Because that OpenGL ES does not work in raspberry pi when GL driver is enabled.

I want to get an image buffer with drawn osd over it.
So I want to create a blank mp_image, then draw the osd over it with osd_draw_on_image()
 function. Then display the image buffer with dispmanx.
This method will work even when the Gl driver is enabled.

How to create a blank transperant mp_image and set required parameters?
After drawing osd how to get the image buffer pointer?
What is the image format of the buffer ARGB32 or something else?

**Comment by wm4** [comment]
This was actually done in the past, until it was determined that GLES rendering is faster. The old dispmanx-only code was thrown away. You need to follow the vo_rpi git history to find it.
Though vo_rpi should be able to use GL too. It frankensteins the vo_gpu code (that runs on anything from GLES 2 to desktop GL 4), it's a quite disgusting hack.

Please try if you can also use --vo=gpu --hwdec=mmal, which I _think_ should create a mmal overlay. If it logs "Using HW-overlay mode.", it works.

**Comment by ksharindam** [comment]
The problem with vo_gpu is , mpv automatically  selects the first available backend. So it chooses rpi backend. but rpi backend does not work in raspberry pi when the GL driver is enabled and mpv quits. x11 backend works when GL driver is enabled but there is no way to choose the backend manually. So I disable the rpi backend of vo_gpu, which allows me to use vo=gpu x11 backend when gl driver is enabled and use vo=rpi when gl driver is disabled.

However forget about vo_rpi. I am asking a vo independent question.
how can i create a mp_image and set appropriate parameters, so that I can use osd_draw_on_image() fuction to draw osd over it.

**Comment by wm4** [comment]
You can select the backend with --gpu-context.

Normally the OSD code returns a list of images in various formats (though you can make it return RGBA images only, which is lower but may be more convenient). osd_draw_on_image() does the same, but blends them to an image. The size and format of this image is almost arbitrary, but note that I don't think target images with alpha are well-supported (so you probably can't get a large RGBA OSD overlay, if that's what you want, unless you adjust the code). There are plenty of uses of mp_image throughout the source code, including cases where they're newly allocated etc..

**Comment by wm4** [comment]
PS: stating what exactly you want to do anyway would probably be more productive.

**Comment by ksharindam** [comment]
Thanks for answering
