### ISSUE TITLE
opening videos from jdownloader doesnt work.

### ISSUE THREAD

**Issue by rezad1393** [mpv-player/mpv#6916]
### mpv version and platform

Name            : mpv
Version         : 1:0.29.1-8
Description     : a free, open source, and cross-platform media player
Architecture    : x86_64
archlinux

### Reproduction steps
use jdownloader to download a video (from youtube or anywhere)
open video from inside jdownloader gui.
### Expected behavior
video should play in mpv
### Actual behavior
nothing happnes.

### Log file

cant make a log file because no mpv can be run seperately.

### more data.
I think this is a change that can be from jdownloader or mpv or kde.
if I set the default player for videos to vlc or anything else, opening the video from jdownloader works for that programs.

even weirder is that for sometime if I opened a folder from jdownloader it would open normally in dolphin file manager but opening the video from that instance of dolphin didn't open them in mpv (nothing happened). but opening an instance of dolphin from outside jdownloader everything works correctly.

again I don't think this is just mpv issue but trying with other application as default video player works correctly for this issue in jdownloader.

**Comment by CounterPillow** [comment]
>cant make a log file because no mpv can be run seperately.

Then put `log-file=/tmp/somefilename.log` in your mpv.conf

**Comment by rezad1393** [comment]
it doesnt launch the mpv do I get no log.
the weird thing is that it launches the mpv sometimes but rarely.
but vlc launches everytime.

**Comment by Hrxn** [comment]
> open video from inside jdownloader gui.

How am I supposed to reproduce this?

**Comment by rezad1393** [comment]
you are right.
I am sorry but it is all I have.
I am not even 100% sure this is mpv fault and the only reason I posted here is because if I set the default app for video to anything else, it works.

feel free to close this if you want.
