### ISSUE TITLE
commit "vo/gpu: fix check on src/dst peak mismatch" broke osd

### ISSUE THREAD

**Issue by esgwpl** [mpv-player/mpv#6917]
### mpv version and platform
https://github.com/mpv-player/mpv/commit/4b25ec3a9d43638812adab38fe6177a57f81785a
mpv 0.29.0-382-g4b25ec3a9d on Arch Linux

### Reproduction steps
play a video
move the mouse cursor to the lower region or do anything that triggers the osd like muting the sound
video turns blue

### Expected behavior
osd displays

### Actual behavior
mpv renders blue screen as soon as the mouse cursor is moved to the lower region, sound continues to play

### Log file
https://0x0.st/zJOG.txt

### Sample files
happens on all videos

I'm currently running the previous commit (external_files: add .lrc subtitle extension) as a workaround
Edit: I also tried --no-config but it still happens

**Comment by haasn** [comment]
Two thoughts:

1. We can make this shader work even on GLSL versions that don't have bvec mix. There's a simple work-around we could do (cast the bvec to vec before doing the mix). That being said,

2. Looking at the generated shader, both dst and src peak should be 1.0 in this case, so I'm not sure why it's triggering. Maybe we don't properly normalize src/dst under all circumstances?

**Comment by CounterPillow** [comment]
#6918 looks like the same issue

**Comment by CounterPillow** [comment]
Can also confirm this fixes it. To reproduce on modern hardware, one can set the following environment variables:
`MESA_GLSL_VERSION_OVERRIDE=120`
`MESA_GL_VERSION_OVERRIDE=2.1`

**Comment by tsjnachos117** [comment]
FYI, the workaround posted by @CounterPillow doesn't work on an Intel i915 video card on an Intel M 520 on Ubuntu 18.04 (x64 version). IDK if that knowledge does anyone any good.
