### ISSUE TITLE
blue screen when mouse is moved

### ISSUE THREAD

**Issue by bdantas** [mpv-player/mpv#6918]
Reproduction steps:
1. Build latest git on Debian Stretch (with gcc 4:6.3.0-4) using these steps:
```
$ git clone https://github.com/mpv-player/mpv-build.git
$ cd mpv-build
$ ./rebuild -j$(nproc)
```
2. Play a video
3. Move mouse into mpv window

Expected behavior:
I expect pseudogui bar to show up at the bottom of the window.

Actual behavior:
Video disappears, replaced by solid blue. Audio continues. Error shows up in terminal ending with "linking with uncompiled shader".

Log here: 
https://pastebin.com/9CGXwkvM

What am I doing wrong? There are no errors during compilation. Maybe a critical package is missing?

**Comment by CounterPillow** [comment]
Your GPU driver doesn't implement a `mix` function that accepts 3-component vectors and outputs a 3-component vector boolean. Technically what mpv is doing (different output genType from input genType) isn't allowed by the GLSL 1.2 spec, but most drivers seem to implement it just fine:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/308818/64493177-1ebda200-d27d-11e9-8ebd-5969ec742c8c.png">

**Comment by CounterPillow** [comment]
Looks like this is a regression that happened before but turned up again now: https://github.com/mpv-player/mpv/commit/0165ab5402c3ec472e877042b38cc03c952ac54c

cc @haasn

**Comment by bdantas** [comment]
Good to know it's not my fault.

Is there a workaround--config setting or compilation option--that would allow me to use current version?

**Comment by CounterPillow** [comment]
`--vo=vaapi` or `--vo=xv` might give you a suboptimal but workable result. Alternatively, you could try `--opengl-es=yes`, maybe that will fix the GPU VO for you, but I doubt it.

**Comment by bdantas** [comment]
Thank you. Either `--vo=vaapi` and `--vo=xv` make the problem go away. `--opengl-es=yes` does not help.

I tried compiling on a totally different machine (an out-of-date Arch linux system with glibc 2.22) and then copied binary and .so files from that machine onto my main Debian Stretch laptop. Interestingly, problem goes away. Log is here in case it helps: https://pastebin.com/CFqPcgdz

**Comment by tsjnachos117** [comment]
FWIW, pressing "i" (lowercase "i" as in "me, myself, and **b**") causes the same issue.
