### ISSUE TITLE
[help]  show video controls all the time and how to change the seek time?

### ISSUE THREAD

**Issue by mrjayviper** [mpv-player/mpv#6921]
1. How do I show the video controls all the time? At the moment, it keeps on disappearing after X seconds. 
2. How do I change the seek times (shift + left/right cursor keys) to less than 1second?

-----

These are the contents of my mpv.conf

```
hr_seek=yes

geometry=50%

osd-bar=yes
osd-duration=86400000
osd-level=2

slang=en

vo=gpu
```

**Comment by CounterPillow** [comment]
>How do I show the video controls all the time? At the moment, it keeps on disappearing after X seconds.

Create a `script-opts/osc.conf` with the contents `visibility=always`.

>How do I change the seek times (shift + left/right cursor keys) to less than 1second?

Put something like this in your input.conf:
```
Shift+RIGHT no-osd seek  0.5 exact
Shift+LEFT  no-osd seek -0.5 exact
```
