### ISSUE TITLE
some videos seem to load correctly but there is no playback

### ISSUE THREAD

**Issue by bdantas** [mpv-player/mpv#6922]
### mpv version and platform
mpv version: 0.29.1 **portable version** (with bundled shared libraries)
platform: an old x86_64 arch linux machine with linux 4.1.6-1-ARCH

### Reproduction steps
Start playing video.

### Expected behavior
Video should play unless I pause it.

### Actual behavior
Most videos play fine. Some videos, however, immediately freeze when opened (I can see a frame, but no movement and no sound). I can scroll to different frames using the pseudogui, but no there is no playback.

Here are details of one affected video: https://pastebin.com/TyqVWn9v

Playing the affected video on a different (newer) machine using same mpv bundle works fine, so video file is not corrupt.

I use `-v` and watch the terminal. Here is an example of what appears in the terminal while keep pressing pause/play in the hopes that there will be playback (note the lack of change in statusline time when video is unpaused):
```
[cplayer] first video frame after restart shown
[cplayer] starting audio playback
[cplayer] playback restart complete
[vo/gpu/x11] Disabling screensaver.
[statusline] AV: 00:03:09 / 00:58:57 (5%) A-V: -0.000
[vo/gpu/x11] Enabling screensaver.
[cplayer] Set property: pause -> 1
[statusline] (Paused) AV: 00:03:09 / 00:58:57 (5%) A-V: -0.000
[vo/gpu/x11] Disabling screensaver.
[cplayer] Set property: pause -> 1
[statusline] AV: 00:03:09 / 00:58:57 (5%) A-V: -0.000
[cplayer] Set property: pause -> 1
[statusline] (Paused) AV: 00:03:09 / 00:58:57 (5%) A-V: -0.000
[vo/gpu/x11] Enabling screensaver.
[statusline] (Paused) AV: 00:03:09 / 00:58:57 (5%) A-V: -0.000
[vo/gpu/x11] Disabling screensaver.
[cplayer] Set property: pause -> 1
[statusline] AV: 00:03:09 / 00:58:57 (5%) A-V: -0.000
[cplayer] Set property: pause -> 1
[vo/gpu/x11] Enabling screensaver.
[statusline] (Paused) AV: 00:03:09 / 00:58:57 (5%) A-V: -0.000
[cplayer] Set property: pause -> 1
[vo/gpu/x11] Disabling screensaver.
[statusline] AV: 00:03:09 / 00:58:57 (5%) A-V: -0.000
```

### Log file
Here is log file of mpv during trouble:
https://pastebin.com/gEECbdDB

You guys probably don't support portable versions, but any hint at would the problem might be would be extremely helpful.

**Comment by bdantas** [comment]
I found a pattern: All affected videos have ac3 audio with 6 channels. Problem does not occur if audio is something other than ac3 (or ac3 with 2 channels). 

Any ideas what may be causing this?

**Comment by bdantas** [comment]
Ok, found a fix: Running `mpv --audio-channels=2 /path/to/video` makes the portable mpv play any video I throw at it, even when running in this ancient machine.
I'm still curious as to why this is necessary. Please educate me if you know.

**Comment by CounterPillow** [comment]
Probably because your years out of date pulse fails to downmix, chokes up somewhere, and mpv doesn't get any timing info from the audio to which to sync the video playback, and since pulse technically is accepting the audio mpv never falls back to syncing to the system time.

**Comment by bdantas** [comment]
Thank you, CounterPillow. That sounds quite probably. Interesting.

Also, congratulations to the mpv team for creating such an elegant and hardy player. I put mpv through all kinds of abuse (I compile it on a recent GNU/Linux box, bundle it up with shared libraries, then run it on a dinosaur) and only minimal tweaks are required for it to run perfectly. Amazing.
