### ISSUE TITLE
Is there better way to have virtual surround sound with MPV on Linux?

### ISSUE THREAD

**Issue by laichiaheng** [mpv-player/mpv#6925]
I have tried sofalizer, but it doesn't sound good, I just can't have better surround experience on it, I also have tried the hrir method (https://forum.manjaro.org/t/howto-setting-up-virtual-surround-sound-for-headphones/55918), I can pick the best sample to sound the most like surround sound, but it only supports 5.1 channel, and it also always resample all the audio to its sample rate when I'm not using it.
### mpv version and platform
```
mpv 0.29.0-385-g6e6ec33168 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.35.100
   libavcodec      58.56.101
   libavformat     58.32.104
   libswscale      5.6.100
   libavfilter     7.58.102
   libswresample   3.6.100
ffmpeg version: N-94826-g558265d4bc
```
### Reproduction steps
Try both method to have better experience on my headphone.
### Expected behavior
Hear more depth on my headphone, shorter response time in MPV.
### Actual behavior
Sofalizer is really slow in MPV, both method are not good enough to emulate the multichannel audio.

**Comment by richardpl** [comment]
Sofalizer is slow only on slow CPUs. And its method is perfect, adjust its options correctly instead (trying only some sofa files is bad idea) . This bug report should be closed as it have nothing to do with mpv.

**Comment by laichiaheng** [comment]
@richardpl I think Ryzen7 3700X is fast enough. Is there any better sofa files, I only have ClubFritz1-12.sofa

**Comment by richardpl** [comment]
There is hundreths of sofa files, i cant guess how your torso/head/ears look like to help you. People cant even describe their problem in proper words. Like is volume set too low so you think sofalizer is worse and so on... Or they cant explain in words speed issues they get.

**Comment by laichiaheng** [comment]
Where to get the hundreds of sofa files?

**Comment by richardpl** [comment]
https://www.sofaconventions.org/mediawiki/index.php/Files
