### ISSUE TITLE
Provide option for large, round-robbin decode buffer.

### ISSUE THREAD

**Issue by rkjnsn** [mpv-player/mpv#6926]
I have several machines that are all able to decode 4k h265 content above real time *on average*. (Specifically, they average about 1.3x decoding on most movies.) Unfortunately, when there's a high-complexity segment, the decoding can't quite keep up, and they playback gets choppy until things settle down again. What these machines do have, though, is plenty of RAM (16-32 GiB).

On most movies, I can achieve smooth playback by specifying `--vd-lavc-threads=200` on the command-line. Because each thread gets its own set of decode buffers, this results in enough decoded frames being in memory to weather segments where the decoder can't quite maintain real-time decoding. However, this is obviously inefficient both memory-wise (as the memory overhead for a whole decoding thread is going to be quite a bit higher than just storing a single decoded frame) and CPU-wise (as the CPU now has to context switch between 200 different threads rather than just running one thread per core).

It would be great if I could specify, e.g., `--decode-buffer-size=10G` or `--decode-buffer-frames=300` and have mpv allocate a large block of memory into which the decode threads would decode in a round-robin fashion. That way, smooth playback could be maintained even with the occasional high-complexity scene.

**Comment by wm4** [comment]
I'll consider it. Tracking the total buffer size is rather hard. I don't think each thread gets its own set of decode frames, rather each thread will increase the total frame usage by 1  (and then maybe some more, as the total latency and the total number of reference frames that needs to be preserved grows).

**Comment by rkjnsn** [comment]
If it makes implementation easier, I don't need to be able to specify an exact size of the decode buffer, just a way to make it bigger without also increasing the thread count. E.g., an option like `--decode-buffer-factor=15` (to hold approximately 15 times as many decoded frames in RAM) would be fine.

**Comment by sgmihai** [comment]
I really hope this gets implemented, in whatever way is the easiest to do. It would be good even for modern machines that can't yet play next-gen codecs. For example av1 10bit at 1080p and higher.

**Comment by wm4** [comment]
Did you try --vd-lavc-threads?

I'll probably implement something like what's requested eventually, but I don't expect it to be too useful.

**Comment by sgmihai** [comment]
Yes I did try vd-lavc-threads=[200-300], and while it does make things a bit better, it still stutters on high bitrate scene with latest dav1d decoder on 10bit encodes. I did not use any tiles in my encode so that makes it not multi thread friendly to decode.. and why I need things to pre-decode in advance, 5 seconds should be safe I think.

**Comment by wm4** [comment]
Let me know whether it helps.

**Comment by sgmihai** [comment]
This works. But when closing mpv while playing.. it takes some time to actually close. Like it waits to fill the set buffer size with decoded data before closing. Not good.
Also I notice you must set all of the params ( --vd-queue-max-bytes=10000MiB --ad-queue-max-bytes=10000MiB --vd-queue-max-samples=200000 --ad-queue-max-samples=30000 --vd-queue-max-secs=50 --ad-queue-max-secs=50) for this to work. Would it be possible to be able to enable it using just one ? Like 10 seconds worth of buffer, or the byte size of the free RAM you have. Why do I have to also set the audio  for video to work ?

**Comment by rkjnsn** [comment]
I also found I had to specify all of the options, but it successfully avoided all of the frame drops I usually see in the first few minutes of the UHD blu-ray I tested.

**Comment by wm4** [comment]
> This works. But when closing mpv while playing.. it takes some time to actually close. Like it waits to fill the set buffer size with decoded data before closing. Not good.

That is the same as the seeking issue mentioned in the manpage. I might improve this if there's evidence that enough people are using this.

> Also I notice you must set all of the params ( --vd-queue-max-bytes=10000MiB --ad-queue-max-bytes=10000MiB --vd-queue-max-samples=200000 --ad-queue-max-samples=30000 --vd-queue-max-secs=50 --ad-queue-max-secs=50) for this to work. Would it be possible to be able to enable it using just one ? Like 10 seconds worth of buffer, or the byte size of the free RAM you have.

Because it's utterly idiotic to use a 10GB buffer for audio, or to attempt to decode all video frames in a file in one go. You can set options in the config file to avoid having them to specify on the command line every time you start mpv.

> Why do I have to also set the audio for video to work ?

You don't, why did you make this up?

**Comment by sgmihai** [comment]
My bad about needing audio options for video to be buffered, I was mistaken.
Those were parameter values just random numeric examples, to show that you need all of them for the buffering system to engage. I have found it uses the smallest/first limit to be encountered out of those 3. Would be great if it worked if just one/two of them was specified.

**Comment by wm4** [comment]
Each option restricts the queue size by another criteria. But the defaults allow some size, for video about 2 seconds of video in common cases. Only --vd-queue-enable must be set to enable the mechanism.

**Comment by wm4** [comment]
Using this queue option actually disables direct rendering and zero-copy (or "less-copy") hardware decoding, so I might fix that later, with predictable consequences.
