### ISSUE TITLE
Add support for AVS2

### ISSUE THREAD

**Issue by 6hzzz** [mpv-player/mpv#6927]
November 6th, 2018, FFmpeg 4.1 "al-Khwarizmi"

 *   AVS2 video decoder via libdavs2

CCTV4K.HLG.AVS2.AC3.CB.08-27.ts 757.7 MB
https://mega.nz/#!Lp8EASaI!ItH-KhONaQaYFfYvG_h58AmEiseSDMB9DCirb5wGZbc

**Comment by CounterPillow** [comment]
Even with an ffmpeg that is built against libdavs2 and claims to be able to decode AVS2, the codec used for this sample is not detected by ffplay or ffprobe, so I think this isn't mpv's bug just yet.

**Comment by CounterPillow** [comment]
Please report this to ffmpeg, see https://ffmpeg.org/bugreports.html
