### ISSUE TITLE
libshaderc_shared.so.1 undefined symbol

### ISSUE THREAD

**Issue by ColorOfSilence** [mpv-player/mpv#6929]
### mpv version and platform

mpv 1:0.29.1-8
Arch Linux

### Reproduction steps

trying to run mpv but does not run

### Actual behavior
when running
`mpv`
it throws out this error
`mpv: symbol lookup error: /usr/lib/libshaderc_shared.so.1: undefined symbol: _ZN7glslang8TProgram5mapIOEPNS_14TIoMapResolverE`

**Comment by jelly** [comment]
This is not an upstream issue, it's an Arch Linux packaging issue https://bugs.archlinux.org/task/63720
