### ISSUE TITLE
libmpv: 4 byte memory leak on mpv_terminate_destroy with PulseAudio 13.0

### ISSUE THREAD

**Issue by Aanok** [mpv-player/mpv#6937]
### mpv version and platform
mpv 0.29.1 (libmpv 1.101)
Arch Linux x86_64 kernel version 5.2.14-arch1-1-ARCH
**libpulse 12.99**, that is PulseAudio 13.0. It is important to note this is the latest version and was just released earlier today. The bug does not manifest with the previous version of PA.

### Reproduction steps
Create and initialize an `mpv_handle`, load a file for playback, eventually call `mpv_terminate_destroy` on the handle.
An edit of the `simple.c` example that is enough to illustrate the behavior and produce a log is attached below.

### Expected behavior
The handle is destroyed without leaking memory.

### Actual behavior
The handle leaks 4 bytes of memory.
Here is the output of Leak Sanitizer:
```
==230776==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x555e494ad708 in calloc (/home/aanok/simple/simple+0x105708)
    #1 0x7f7adcb6719f in pa_xmalloc0 (/usr/lib/libpulse.so.0+0xe19f)

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
```
So, it seems like it should be a problem on PulseAudio's side.

### Log file
[log.txt](https://0x0.st/zyKg.tx) (as produced by running the attached program on a sample file)

### Sample files
[simple.c](https://0x0.st/zyKE.c)

**Comment by wm4** [comment]
Try to get a better backtrace. If it's pulseaudio, report to them. If mpv is responsible, re-report.
By the way, it's not unusual that libraries leak tons of stuff. xlib and ALSA leak half the world, the to point of sabotaging valgrind's usefulness.

**Comment by Aanok** [comment]
Fair enough, I will look into building PA from source with debug symbols and into the issue further. I confess I was hoping to pass the onus of forwarding this to you mpv devs if required, since I'm not really familiar with libpulse internals and wouldn't really know quite what to put in a bug report for that. I fear if I just reported a problem with mpv they might simply point the finger at you.

Apologies if the issue wasn't informative enough. Thanks for your time :-)
