### ISSUE TITLE
Excessive frame drops on HFR video when using hardware decoding

### ISSUE THREAD

**Issue by Vestaia** [mpv-player/mpv#6940]
### mpv version and platform
0.29.1_3 - MacOS 10.14.5
Macbook Pro 2019 15" - i7 9750H - Apple T2 (A10 Variant) Hardware decoder - Radeon 555X

### Reproduction steps
Play 240 FPS video (attached) encoded in x264 using the VideoToolBox hardware decoder on a Macbook Pro 2019 15"
`mpv 240.mkv --hwdec-codecs=all --hwdec=auto`

### Expected behavior
Decodes and plays video with either dropping frames to match refresh rate (60hz) or no dropped frames

### Actual behavior
Drops most frames resulting in stuttering (averaging ~10-20 fps) when using hardware decoding. However, playback is smooth at 60fps with software decoding.
VideoToolBox
`AV: 00:00:07 / 00:00:08 (98%) A-V:  0.000 Dropped: 1635`
VideoToolBox-copy
`AV: 00:00:07 / 00:00:08 (98%) A-V:  0.000 Dropped: 1832`
CPU (hwdec=no)
`AV: 00:00:07 / 00:00:08 (98%) A-V:  0.000 Dropped: 1453`

The system is fast enough to decode 720p video at 240fps. Benchmark with ffmpeg on the same video gives 414fps using the hardware decoder.
`frame= 1898 fps=414 q=-0.0 Lsize=N/A time=00:00:08.03 bitrate=N/A speed=1.75x    
video:993kB audio:1384kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
bench: utime=1.097s stime=0.858s rtime=4.603s
bench: maxrss=78372864kB`

### Log file
https://0x0.st/zyQV.txt

### Sample files
https://0x0.st/zyQy.mkv

**Comment by haasn** [comment]
The slowdown might be in the download/upload path imposed by copyback mode. Not sure how you tested this in ffmpeg, but it probably isn't as pathologic about it. I haven't seen the videotoolbox code but it might also be imposing blocking copyback which would make this whole situation even worse since it would lead to GPU stalling.

Try `--hwdec=auto` instead of `--hwdec=auto-copy`.

**Comment by kokowang** [comment]
There are fewer dropped frames using --hwdec=auto instead of --hwdec=auto-copy
Though it's still noticeably stuttering. 
on the 8 second video, VTB displayed 263 frames (36fps)
VTB Copy displayed 95 frames (12fps)
CPU displayed 474 frames (59fps)

**Comment by haasn** [comment]
Other things you can try is using `-vo null` to see if the performance matches. Specifically, try these options:

```
--vo null --no-audio --untimed
```

See how fast that decodes. (Sadly, there's afaik no easy way to calculate the actual estimated FPS when using `-vo null`)

**Comment by kokowang** [comment]
`time mpv /Users/koko/Desktop/240.mkv --hwdec=videotoolbox --vo null --no-audio --untimed`
`Playing: /Users/koko/Desktop/240.mkv
 (+) Video --vid=1 (*) (h264 1280x720 240.000fps)
     Audio --aid=1 (*) (aac 2ch 44100Hz)
VO: [null] 1280x720 yuv420p
V: 00:00:07 / 00:00:08 (98%)

Exiting... (End of file)

real	0m1.009s
user	0m7.214s
sys	0m0.457s
`

**Comment by kokowang** [comment]
7.965 seconds
```time mpv /Users/koko/Desktop/240.mkv --hwdec=auto --vo null --no-audio --untimed
Playing: /Users/koko/Desktop/240.mkv
 (+) Video --vid=1 (*) (h264 1280x720 240.000fps)
     Audio --aid=1 (*) (aac 2ch 44100Hz)
Using hardware decoding (videotoolbox-co).
VO: [null] 1280x720 nv12
V: 00:00:07 / 00:00:08 (98%)


Exiting... (End of file)

real	0m7.965s
user	0m1.839s
sys	0m1.249s
```

**Comment by wm4** [comment]
Is that faster or slower than ffmpeg?

**Comment by Akemi** [comment]
ffmpeg `-benchmark -hwaccel videotoolbox -i file -f null -`
```
real	0m6.419s
user	0m1.053s
sys	0m0.751s
```

mpv vt-copy `--vo null --no-audio --untimed --hwdec=videotoolbox-copy`
```
real	0m6.447s
user	0m1.196s
sys	0m0.671s
```

mpv sw `--vo null --no-audio --untimed`
```
real	0m1.038s
user	0m5.307s
sys	0m0.272s
```

mpv vt `--no-config --hwdec=videotoolbox`
```
AV: 00:00:07 / 00:00:08 (98%) A-V:  0.000 Dropped: 1436 ~60.5fps
```

mpv vt-copy `--no-config --hwdec=videotoolbox-copy`
```
AV: 00:00:07 / 00:00:08 (98%) A-V:  0.000 Dropped: 1623 ~37.125fps
```

mpv sw `--no-config`
```
AV: 00:00:07 / 00:00:08 (98%) A-V:  0.000 Dropped: 1421 ~62.375fps
```

for me videotoolbox is fine decoding speed wise. -copy is significantly slower with mpv and vo=gpu/libmpv, in comparison to none-copy, vo=null and ffmpeg. vo=gpu and vo=libmpv perform the same.

**Comment by wm4** [comment]
Does ffmpeg copy? If it just decodes the frames and discards them, the result doesn't matter.

You may need to use the hwdownload filter, or whatever it's called, if you can figure out how.

**Comment by Akemi** [comment]
i didn't get -vf hwdownload to works. getting

```
Impossible to convert between the formats supported by the filter 'graph 0 input from stream 0:0' and the filter 'auto_scaler_0'
Error reinitializing filters!
Failed to inject frame into filter network: Function not implemented
Error while processing the decoded data for stream #0:0
```

**Comment by Dudemanguy** [comment]
Please open a new issue if this still persists on 0.36.
