### ISSUE TITLE
How to enable deinterlacer on mac  with videotoolbox ?

### ISSUE THREAD

**Issue by aeeq** [mpv-player/mpv#6943]
### mpv version and platform
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Sep  6 22:58:44 PDT 2019
ffmpeg library versions:
   libavutil       56.35.100
   libavcodec      58.56.101
   libavformat     58.32.104
   libswscale      5.6.100
   libavfilter     7.58.102
   libswresample   3.6.100
ffmpeg version: N-94802-g4857688

### Reproduction steps
play a BD Disc with hwdec deinterlace 
mpv --hwdec=videotoolbox bluray:////Volumes/xxxx/ --vo=gpu deinterlace=yes
### Actual behavior
can't activate deinterlacer
the error message is [deint] no deinterlace filter available for this format
if using software decode is ok
### Log file
`[cplayer] Command line options: '--hwdec=videotoolbox' 'bluray:////Volumes/xxxx/' '--vo=gpu' '--scale=bilinear' '-v'
[cplayer] mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Fri Sep  6 22:58:44 PDT 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.35.100
[cplayer]    libavcodec      58.56.101
[cplayer]    libavformat     58.32.104
[cplayer]    libswscale      5.6.100
[cplayer]    libavfilter     7.58.102
[cplayer]    libswresample   3.6.100
[cplayer] ffmpeg version: N-94802-g4857688
[cplayer] 
[cplayer] Configuration: ./waf configure
[cplayer] List of enabled features: 51deb apple-remote asm atomics bsd-fstatfs build-date cocoa coreaudio cplayer cplugins debug-build drmprime dvdnav dvdread dvdread-common fchmod ffmpeg gl gl-cocoa glob glob-posix gnuc gpl iconv javascript libaf libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm lua macos-cocoa-cb macos-touchbar optimize osx-thread-name posix posix-or-mingw posix-spawn posix-spawn-native pthreads stdatomic uchardet videotoolbox-gl videotoolbox-hwaccel zlib
[cplayer] Reading config file /usr/local/etc/mpv/encoding-profiles.conf
[cplayer] Reading config file /Users/aeeq/.config/mpv/mpv.conf
[ifo] Opening /Users/aeeq/.config/mpv/input.conf
[ifo_dvdnav] Opening /Users/aeeq/.config/mpv/input.conf
[bdmv/bluray] Opening /Users/aeeq/.config/mpv/input.conf
[file] Opening /Users/aeeq/.config/mpv/input.conf
[input] Parsing input config file /Users/aeeq/.config/mpv/input.conf
[input] Input config file /Users/aeeq/.config/mpv/input.conf parsed: 2 binds
[stats] script-opts/stats.conf not found. 
[stats] lua-settings/stats.conf not found. 
[ytdl_hook] script-opts/ytdl_hook.conf not found. 
[ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[osc] script-opts/osc.conf not found. 
[osc] lua-settings/osc.conf not found. 
[libmpv_render] GL_VERSION='4.1 INTEL-10.36.25'
[libmpv_render] Detected desktop OpenGL 4.1.
[libmpv_render] GL_VENDOR='Intel Inc.'
[libmpv_render] GL_RENDERER='Intel Iris Pro OpenGL Engine'
[libmpv_render] GL_SHADING_LANGUAGE_VERSION='4.10'
[libmpv_render] Loaded extension GL_APPLE_rgb_422.
[libmpv_render] GL_*_swap_control extension missing.
[libmpv_render] Testing FBO format rgba16f
[libmpv_render] Using FBO format rgba16f.
[libmpv_render] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0).
[libmpv_render] No advanced processing required. Enabling dumb mode.
[libmpv_render] Loading hwdec driver 'videotoolbox'
[cplayer] Waiting for scripts...
[cplayer] Done loading scripts.
[cplayer] Playing: bluray:////Volumes/xxxxx/
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[osd/libass] Shaper: FriBidi 1.0.5 (SIMPLE)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider coretext
[osd/libass] Done.
[bd] Opening bluray:////Volumes/xxxxx/
[bd] List of available titles:
[bd] idx:   0 duration: 00:00:00 (playlist: 00000.mpls)
[bd] idx:   1 duration: 00:54:06 (playlist: 00001.mpls)
[bd] idx:   2 duration: 00:11:13 (playlist: 00002.mpls)
[bd] idx:   3 duration: 00:07:02 (playlist: 00003.mpls)
[bd] Blu-ray successfully opened.
[demux] Trying demuxers for level=force.
[disc] reset to time: 0.000000
[demux] Trying demuxers for level=force.
[lavf] Found 'mpegts' at score=50 size=2048.
[lavf] avformat_find_stream_info() finished after 3133440 bytes.
[demux] Detected file format: mpegts (libavformat)
[demux] Stream is not seekable.
[demux] Detected file format: CD/DVD/BD wrapper
[cplayer] Opening done: bluray:////Volumes/xxxxx/
[cplayer] Running hook: ytdl_hook/on_preloaded
[disc] select track 0
[disc] select track 1
[cplayer]  (+) Video --vid=1 (h264 1920x1080 29.970fps)
[cplayer]  (+) Audio --aid=1 --alang=jpn (pcm_bluray 2ch 48000Hz)
[lavf] select track 0
[lavf] select track 1
[vo/gpu] Probing for best GPU context.
[vo/gpu/opengl] Initializing GPU context 'cocoa'
[vo/gpu] can't find an ambient light sensor
[vo/gpu] opengl cocoa backend is deprecated, use vo=libmpv instead
[vo/gpu] GL_VERSION='4.1 INTEL-10.36.25'
[vo/gpu] Detected desktop OpenGL 4.1.
[vo/gpu] GL_VENDOR='Intel Inc.'
[vo/gpu] GL_RENDERER='Intel Iris Pro OpenGL Engine'
[vo/gpu] GL_SHADING_LANGUAGE_VERSION='4.10'
[vo/gpu] Loaded extension GL_APPLE_rgb_422.
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0).
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Assuming 60.000002 FPS for display sync.
[vd] Container reported FPS: 29.970030
[vd] Codec list:
[vd]     h264 - (null)
[vd] Opening decoder h264
[vd] Looking at hwdec h264-videotoolbox...
[vo/gpu] Loading hwdec driver 'videotoolbox'
[vd] Trying hardware decoding via h264-videotoolbox.
[vd] Selected codec: h264 ((null))
[vf] User filter list:
[vf]   (empty)
[ad] Codec list:
[ad]     pcm_bluray - (null)
[ad] Opening decoder pcm_bluray
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: pcm_bluray ((null))
[af] User filter list:
[af]   (empty)
[cplayer] Starting playback...
[af] [in] 48000Hz stereo 2ch s16
[af] [userspeed] 48000Hz stereo 2ch s16
[af] [userspeed] (disabled)
[af] [convert] 48000Hz stereo 2ch s16
[vd] Pixel formats supported by decoder: videotoolbox_vld yuv420p
[vd] Codec profile: unknown (0x64)
[vd] Requesting pixfmt 'videotoolbox_vld' from decoder.
[vd] Using hardware decoding (videotoolbox).
[vd] Decoder format: 1920x1080 videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/auto CL=mpeg2/4/h264 (auto 0.000000/0.000000/0.000000)
[vf] [in] 1920x1080 videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] 1920x1080 videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264

**[deint] no deinterlace filter available for this format**

[vf] [userdeint] (disabled)
[vf] [autorotate] 1920x1080 videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [autorotate] (disabled)
[vf] [convert] 1920x1080 videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [convert] (disabled)
[vf] [out] 1920x1080 videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[ao] Trying audio driver 'coreaudio'
[ao/coreaudio] requested format: 48000 Hz, stereo channels, s16
[ao/coreaudio] selected audio output device: X1S USB DAC Output (39)
[ao/coreaudio] input channel layout:
[ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio]  - description 0: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio]  - description 1: label <4294967295, 64>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio] mp chmap: unknown2
[ao/coreaudio] input channel layout:
[ao/coreaudio] layout: tag: <0>, bitmap: <0>, descriptions <2>
[ao/coreaudio]  - description 0: label <1, 0>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio]  - description 1: label <2, 1>,  flags: <0>, coords: <0.000000, 0.000000, 0.000000>
[ao/coreaudio] mp chmap: stereo
[ao/coreaudio] Channel layouts:
[ao/coreaudio]  - stereo
[ao/coreaudio]  - mono
[ao/coreaudio] result: stereo
[ao/coreaudio] Latency property cntl: 48 frames
[ao/coreaudio] Latency property zisf: 512 frames
[ao/coreaudio] Latency property tfas: 49 frames
[ao/coreaudio] audiounit latency [us]: 0
[ao/coreaudio] device latency [us]: 12687
[ao/coreaudio] using soft-buffer of 9600 samples.
[cplayer] AO: [coreaudio] 48000Hz stereo 2ch s16
[cplayer] AO: Description: CoreAudio AudioUnit
[af] [convert] (disabled)
[af] [out] 48000Hz stereo 2ch s16
[cplayer] VO: [gpu] 1920x1080 videotoolbox[nv12]
[cplayer] VO: Description: Shader-based GPU Renderer
[vo/gpu] reconfig to 1920x1080 videotoolbox[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vo/gpu] Resize: 1920x1080
[vo/gpu] Window size: 1920x1080
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 1920x1080
[vo/gpu] Video scale: 1.000000/1.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Resize: 1920x1080
[vo/gpu] Window size: 1920x1080
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 1920x1080
[vo/gpu] Video scale: 1.000000/1.000000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[osd/libass] fontselect: (sans-serif, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
[cplayer] first video frame after restart shown
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 48050Hz stereo s16 -> 48000Hz stereo s16
[af] [convert] (enabled)
[cplayer] starting audio playback
[cplayer] playback restart complete
[cplayer] Change display sync audio drift: -1
[statusline] AV: 00:00:01 / 00:54:06 (0%) A-V: -0.009 DS: 2.140/0
[cplayer] EOF code: 5  
[ad] Uninit decoder.
[vd] Uninit decoder.
[cplayer] finished playback, success (reason 3)
[cplayer] 
[cplayer] 
[cplayer] Exiting... (Quit)
[osx] Exiting...
[ytdl_hook] Exiting...
[stats] Exiting...
[osc] Exiting...`

**Comment by wm4** [comment]
Not possible. For other hwdecs, we use the OS-provided facilities, but macOS has none. Would require implementing our own deinterlacer as shader. You can try the -copy variant.

**Comment by Akemi** [comment]
i was under the impression that macOS does provide some with https://developer.apple.com/documentation/videotoolbox/kvtdecompressionproperty_deinterlacemode_temporal

**Comment by Akemi** [comment]
also see #3939
