### ISSUE TITLE
Distorted screenshots when video is rotated 90 or 270

### ISSUE THREAD

**Issue by Vrihub** [mpv-player/mpv#6945]
### mpv version and platform

0.29.1 Linux (Debian 10 buster)

### Reproduction steps

1. `mpv --video-rotate 90 video.mp4`
1. Take a screenshot with `s`

### Expected behavior

The screenshot image should have the same aspect as the video.

### Actual behavior

The screenshot image is distorted. Looks like width and height got somehow swapped in the process.

The result is similar with `--video-rotate 90`, while `--video-rotate 180` works as expected.

Of course screenshots taken with `Ctrl-s` are not affected.

### Log file

https://0x0.st/zyv8.txt

### Sample files

OK screenshot without `--video-rotate`: https://0x0.st/zyvK.jpg

Buggy screenshot  with `--video-rotate 90`: https://0x0.st/zyvP.jpg

Video available with:
`youtube-dl -f 18 https://youtube.com/watch?v=6XnNv9xi3Jk`

**Comment by Akemi** [comment]
fixed with #6839 i believe. try with git master and report back if the problem still persists.

**Comment by Vrihub** [comment]
Yes, I confirm git-master fixes the bug.
Sorry for the noise, but I only searched within issues, so I missed #6839 (hey at least the video was funny!)
