### ISSUE TITLE
--stream-dump not working (Assertion `buf_valid + chunk <= TOTAL_BUFFER_SIZE')

### ISSUE THREAD

**Issue by schieni** [mpv-player/mpv#6948]
Are https://github.com/mpv-player/mpv/commit/162e0f5ad92116d1a4fb740d087da2a152686b73 and related changes possible reasons?

By the way: Thanks for this great player!

### mpv version and platform
mpv 0.29.0-415-g0abe34ed21 (up to date) on Arch Linux (Kernel 5.2.14)
https://termbin.com/32b8r

### Reproduction steps
> nobody@workstation ~ (0) $ mpv dvb://zdf --stream-dump=zdf.ts
> Auto-loading profile 'protocol.dvb'
> Playing: dvb://zdf
> [dvbin] dvb_tune DVB-C ANNEX A Freq: 338000000
> mpv: ../stream/stream.c:405: stream_peek: Assertion `buf_valid + chunk <= TOTAL_BUFFER_SIZE' failed.
> Aborted (core dumped)

### Log file
https://termbin.com/1clj

**Comment by wm4** [comment]
It doesn't happen here with a simple file. Is it dvb specific?

**Comment by wm4** [comment]
Could reproduce by randomizing stream_file read returns. This looked fairly critical. I hope it works now.

**Comment by schieni** [comment]
After a few tests, it seems to be working now again. 

Thanks for your quick response and...

...greetings from a city, where trains hanging on rails, not just standing on them -> https://en.wikipedia.org/wiki/Wuppertal_Suspension_Railway
