### ISSUE TITLE
"--o" gives worst saving quality

### ISSUE THREAD

**Issue by TonyStark** [mpv-player/mpv#6950]
### mpv version and platform

> mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
>  built on Tue Aug  6 14:50:47 CEST 2019
> ffmpeg library versions:
>    libavutil       56.31.100
>    libavcodec      58.54.100
>    libavformat     58.29.100
>    libswscale      5.5.100
>    libavfilter     7.57.100
>    libswresample   3.5.100
> ffmpeg version: n4.2
> 
Well i m streaming one url "http://url/123.m3u8" it gives good quality while streaming
but when i want to save that streaming video data using --o parameter it gives me worst/blurry video quality

Is that possible to save same streaming quality into .mp4 or .ts
thank you

**Comment by Akemi** [comment]
`--o` is for encoding mode, you either have to tweak you encoding settings if you really want to reencode or use `--stream-dump=` instead.

**Comment by wm4** [comment]
--stream-record is the new way intended to handle this.

**Comment by TonyStark** [comment]
@wm4 wel stream-record option not found
@Akemi however --stream-dump doesn't redirect from multiple .ts file. it just only m3u8 and exit

**Comment by Akemi** [comment]
that's why wm4 said to use --stream-record. you have to update your mpv version to git master.

**Comment by TonyStark** [comment]
okay
