### ISSUE TITLE
[feature request] Write MPV version # to titlebar

### ISSUE THREAD

**Issue by markfilipak-windows** [mpv-player/mpv#6953]
MPV version # is very hard to determine. Though 'mpv.exe', StringFileInfo, FileVersion = "0.29.1", most people will not know how to find it. Total Commander reports "File version: 2.0.0.0" but that's not the program version.

Suggestion: Write the MPV version # to the titlebar.

**Comment by wm4** [comment]
Log file, command line (the way how mpv is supposed to use), you can use `title=${mpv-version}` etc.

Using mpv without command line is not recommended, because you don't see warnings and errors.
