### ISSUE TITLE
How to use filename's with accented characters

### ISSUE THREAD

**Issue by elriba** [mpv-player/mpv#6954]
### Reproduction steps
I have a test video called: video áéíóúñü.mp4

If I try to display a clip from it:
mpv --start=13:20 --length=10 "video áéíóúñü.mp4"

I get the following error:
[file] Cannot open file 'video ßÚÝ¾·±³.mp4': No such file or directory

Surely this must be a mistake on my part, but I thought I should post this here anyhow.

**Comment by elriba** [comment]
I found what I was doing wrong....   
I was saving the batch file using ANSI instead of DOS encoding.
It is working now!

**Comment by wm4** [comment]
Yeah, though that is all down to Windows itself. mpv simply uses the UTF-16 command line arguments Windows provides.
