### ISSUE TITLE
MJPEG stream won't open

### ISSUE THREAD

**Issue by mvrozanti** [mpv-player/mpv#6964]
### mpv version and platform
`Linux 5.2.9-arch1-1-ARCH x86_64`
```
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Tue Aug  6 14:50:47 CEST 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2
```

### Reproduction steps
`mpv http://192.168.0.52:8080/video/mjpeg `

### Expected behavior
Open window with stream playing

### Actual behavior
Outputs `Playing: http://192.168.0.52:8080/video/mjpeg` and does nothing else.
VLC plays the stream fine.

### Log file
http://ix.io/1W6w

**Comment by wm4** [comment]
Requires sample.

**Comment by mvrozanti** [comment]
https://file.io/mxqqlj

**Comment by wm4** [comment]
Link results in a 404 error.

**Comment by mvrozanti** [comment]
First website just holds the upload until the it's been downloaded once. Please check the updated link.

**Comment by wm4** [comment]
Can't you just upload to the site mentioned in the issue template?
We might also need the headers the request to your mjpeg-serving webserver returns (curl can do that).

**Comment by mvrozanti** [comment]
https://0x0.st/ztpv.avi

Headers:

`curl -vLI http://192.168.0.52:8080/video/mjpeg`

```
*   Trying 192.168.0.52:8080...
* TCP_NODELAY set
* Connected to 192.168.0.52 (192.168.0.52) port 8080 (#0)
> HEAD /video/mjpeg HTTP/1.1
> Host: 192.168.0.52:8080
> User-Agent: curl/7.65.3
> Accept: */*
>
* Empty reply from server
* Connection #0 to host 192.168.0.52 left intact
curl: (52) Empty reply from server
```

**Comment by wm4** [comment]
It is not. It seems to reject your request, but I couldn't imagine why.

Your sample file is an avi file, is that right? It plays, even with mpv 0.29.1.

**Comment by mvrozanti** [comment]
Maybe VLC has some tricks to get the stream to work and it passed it on to the file.

I got a piece of the stream directly by calling 
`curl -sv http://192.168.0.52:8080/video/mjpeg > movie.idontknowwhatthefuckthisis`
http://0x0.st/ztpl.idontkn

**Comment by wm4** [comment]
Seems like a ffmpeg bug. It's correctly detected as MIME multipart mjpeg stream, but it returns only 1 packet. You can test with this:
```
 ffprobe  ztpl.idontkn  -show_packets
```
Both ffprobe and mpv actually detect the format correctly (`mpjpeg`). It just doesn't seem to find the next packet correctly, but I didn't debug it further.

**Comment by CounterPillow** [comment]
fwiw, VLC doesn't play that sample for me either.

**Comment by wm4** [comment]
vlc doesn't do much useful for me on the file, but it seems to show some more frames.

**Comment by wm4** [comment]
Anyway, you can report this to ffmpeg, although I bet nobody in ffmpeg cares.

**Comment by wm4** [comment]
Just to be sure, try ffprobe on the http URL too. There might be HTTP headers that affect it or so.

**Comment by mvrozanti** [comment]
`ffprobe http://192.168.0.52:8080/video/mjpeg`
```
ffprobe version n4.2 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 9.1.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
```

**Comment by wm4** [comment]
By running ffprobe I meant with `-show_packets`.

vlc very certainly has its own parser for this format, and many others. They usually use ffmpeg for decoding only. That is, the stage after demuxing/parsing input files. mpv traditionally has moved as much as possible to ffmpeg, which means we get all their bugs.

**Comment by mvrozanti** [comment]
weird flex but ok
