### ISSUE TITLE
Leave softvol=no active

### ISSUE THREAD

**Issue by IsarRadler** [mpv-player/mpv#6966]
### mpv 0.27.2 on LMDE

I use mpv as video player with bit true audio output to SPDIF. This works great and I can enjoy music without resampling on the machine.
If you remove the possibility to set softvol=no in the config file I again have a resampling in the audio channel.
Please continue this possibility!

**Comment by wm4** [comment]
Use https://mpv.io/manual/master/#command-interface-ao-volume
