### ISSUE TITLE
[wayland] VDPAU depends on X11 even if building only for Wayland

### ISSUE THREAD

**Issue by kennylevinsen** [mpv-player/mpv#6968]
### mpv version and platform

master (6111f57ef9269b46e19ca6f1f20c8b61f2ea7a6b), Arch Linux, Wayland

### Reproduction steps

- Disable X11 (either voluntarily, or due to missing various X dependencies, such as libXss).
- Enable VDPAU

### Expected behavior

Successful build

### Actual behavior

wscript lists x11 as a vdpau dependency, and fails the build. If the dependency is removed, it becomes apparent that vo_vdpau.c calls into vo_x11*, so building without x11 is not possible.

**Comment by philipl** [comment]
VDPAU requires x11; it cannot work any other way. So disabling X11 and enabling vdpau creates an impossible scenario and wscript is correct to error out.

**Comment by kennylevinsen** [comment]
Ah, okay. Thought it was just an accidental dependency on X11 as I often run into in other projects.

Thanks for the explanation!

**Comment by akostadinov** [comment]
hmm, not possible to accelerate encoding/decoding without a graphical interface?
