### ISSUE TITLE
Add volume control to On Screen Controller?

### ISSUE THREAD

**Issue by anovicecodemonkey** [mpv-player/mpv#697]
I am wondering if it is desirable to others/possible to add basic volume controls to the  On Screen Controller? Importantly, it wouldn't take up much extra room and I believe it would be a useful addition.

**Comment by Xylemon** [comment]
Although binding keys to change volume will do, I still think it would be a useful addition to have volume on the OSC.

**Comment by robin007bond** [comment]
I don't find it necessary. For people that want a more advanced front-end, there's always baka-mplayer or boki. Volume control should be handled by the system.

@rezad1393 
You can also map volume changes to use buttons on your mouse.

**Comment by aflavio** [comment]
I think it necessary. Especially because I play videos only using mouse and not keyboard.

**Comment by Hrxn** [comment]
You can still bind `add volume 1` and `add volume -1` to the mouse wheel or buttons on the mouse.

**Comment by aflavio** [comment]
Great.  Worked fine!!!

**Comment by AiQLee** [comment]
= 		   add volume 2
- 		   add volume -2

**Comment by jkldgoefgkljefogeg** [comment]
Very useful feature indeed. I find unintended scrollwheel to seek/rewind very annoying.
input.conf only works in ~/.mpv/ not ~/.confg/mpv/ on Ubuntu, is there a recent change to this behavior? archlinux wiki still says ~/.confg/mpv/

**Comment by aflavio** [comment]
I'm using debian and here is working fine.

Put the config file in: ~/.config/mpv/input.conf

Bye.


Augusto Morais


On Mon, May 23, 2016, 21:40 kjeojfeofjgeofkjodfioejo <
notifications@github.com> wrote:

> Very useful feature indeed. I find unintended scrollwheel to seek/rewind
> very annoying.
> input.conf only works in ~/.mpv/ not ~/.confg/mpv/ on Ubuntu, is there a
> recent change to this behavior? archlinux wiki still says ~/.confg/mpv/
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mpv-player/mpv/issues/697#issuecomment-221136254>
>
-- 
Augusto Morais
Gerente de Projetos | SCM ZCE
 aflavio@gmail.com
 31 9157-9706
LINKEDIN.com/in/moraisaugusto

**Comment by wm4** [comment]
> input.conf only works in ~/.mpv/ not ~/.confg/mpv/ on Ubuntu, is there a recent change to this behavior?

You just need a mpv version which hasn't been unmaintained for years.
