### ISSUE TITLE
Automatically 'autocrop' video

### ISSUE THREAD

**Issue by jbarry786** [mpv-player/mpv#6973]
Say you have certain videos where you want to remove a part at the bottom. A visual example,
![image](https://user-images.githubusercontent.com/30951795/65379234-c3e46b80-dcbc-11e9-82e9-8e2714399c06.png)

When watching them, you you want to omit the yellow part like the above. Is it possible to automatically crop a part of a video? 

I currently use the autocrop script to manually do it. Ideally I'd like it to be done automatically. and I suppose it could even be possible to have a ratio where the area is cropped proportionally to the height of the video (depending on whether it's 432p, 576p, 720p or 1080p).

If there's no elegant solution, I would be happy enough to get an idea how one could just manually edit in the script the crop dimensions and then have the sript just run the crop based on those values. This would work for me since the area I want to crop is the same.

**Comment by Akemi** [comment]
https://github.com/occivink/mpv-scripts#croplua
https://github.com/aidanholm/mpv-easycrop

those scripts or you can adapt them to do something automagically.

**Comment by jbarry786** [comment]
@wiiaboo Ricardo, fellow tuga here, podes-me ajudar a editar manualmente os valores no [https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua](url) More seriously, if you ever have a second, read my question above and give me some pointers on what's the best path to achieve it. basically, you know the width and the height of the area you want to crop out, how do I do it automatically for a set of videos, that's my question. Thanks

**Comment by wiiaboo** [comment]
If it's just a static crop, just copy the values from doing the autocrop once to a vf line in a profile.
If it depends on the video width/height, https://ffmpeg.org/ffmpeg-filters.html#toc-crop accepts some basic math, so you can also do it proportionally.
