### ISSUE TITLE
Can't seek backwards in Ogg Opus file

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#6974]
### mpv version and platform
<pre>
mpv 0.29.0-701-g61b46d101e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Sep 21 23:34:29 CEST 2019
ffmpeg library versions:
   libavutil       56.35.100
   libavcodec      58.58.101
   libavformat     58.32.104
   libswscale      5.6.100
   libavfilter     7.58.102
   libswresample   3.6.100
ffmpeg version: N-94982-gea673a0edb
</pre>

### Reproduction steps
Attempt to seek backwards

### Expected behavior
Backward seek occurs.

### Actual behavior
A few warnings are thrown and the playback restarts a few seconds later than before.

This is a recent regression and worked pre `new_master` (on e5c1cf2e3e76deb32532d213d9b6a48a2b7cf242).

### Log file
https://0x0.st/ztOP.log

### Sample files
https://0x0.st/ztOZ.ogg
bug is not reproducible when playing from HTTP (demuxer cache?)

**Comment by Dudemanguy911** [comment]
Bisected it to 27fcd4dd.

**Comment by Dudemanguy911** [comment]
Yup it works with ``--demuxer-lavf-linearize-timestamps=no`` like the commit message suggests. Not really sure if that option should default to yes.
