### ISSUE TITLE
Run bat file on startup and quit in scripts directory?

### ISSUE THREAD

**Issue by TheOddler** [mpv-player/mpv#6975]
I have two bat files that I need to run, one on startup and one on shutdown. I'm currently doing this with `mp.utils.subprocess`:

```
function on_start() {
    var result = mp.utils.subprocess({ args: [path_to_bat, param1], cancellable: false })
    dump(result)
}
mp.register_event("start-file", on_start)
```

And similar for the `shutdown` event.

This works fine. However, the bat file calls a program in the scripts folder. But this gives an error, because the bat file's working directory is the folder of the file being played by mpv.

So now I have two questions:

1) Can I change the working directory of the bat file I run with `subprocess`?
2) Is there a better way of running a bat file on startup/shutdown?

Thanks!

**Comment by paulguy** [comment]
Can you have the bat `cd` in to the directory you'd want or make a shortcut to the bat file and set the working directory there and execute that with `start whatever.bat`?

Also can you just use subprocess outside of a function so maybe it's just executed when the script loads while mpv is loading?  I suppose that may effectively run it on mpv's startup.

**Comment by TheOddler** [comment]
Fair enough, I'll indeed change the cd in the bat file itself then. Thanks!
