### ISSUE TITLE
How to use mp.command_native?

### ISSUE THREAD

**Issue by TheOddler** [mpv-player/mpv#6979]
I've been using `mp.utils.subprocess` to call a bat file in the same folder as my plugin script, and it works fine. However, the documentation says that `subprocess` is a legacy wrapper, and I should be using `mp.command_native`. So I tried doing that, but I can't seem to figure out how to use it.

This works:

    utils.subprocess({ args = {bat_path, pid}, cancellable = false })

But my `command_native` version doesn't:

    mp.command_native({ name = "subprocess", args = {bat_path, pid}, playback_only = false })

What am I doing wrong?

**Comment by avih** [comment]
It looks ok. What exactly doesn't work? are there any errors or warnings logged?

**Comment by avih** [comment]
Also, which version of mpv are you using? you know, the issue report template is there for a reason, which would have saved us time by being able to answer those questions by simply looking at the log.

**Comment by TheOddler** [comment]
When I use following code to print the error:
    local result, error = mp.command_native({ name = "subprocess", args = {bat_path, pid}, playback_only  = false })
    print(result)
    print(error)

Then it just shows `nil ` and `invalid parameter` in the log for those two prints.

**Comment by avih** [comment]
> Also, which version of mpv are you using? you know, the issue report template is there for a reason, which would have saved us time by being able to answer those questions by simply looking at the log.

**Comment by TheOddler** [comment]
You're right, excuse me. I'm using the https://mpv.srsfckn.biz/ 2018-10-02 64bit build.

**Comment by avih** [comment]
> You're right, excuse me. I'm using the https://mpv.srsfckn.biz/ 2018-10-02 64bit build.

This version doesn't include the native command which replaces subprocess. If you look at `doc/mpv.html` inside the file which you downloaded you'll see that it's _not+ saying that `utils.subprocess` is deprecated.

**Comment by TheOddler** [comment]
Oh no, I've been looking at the wrong documentation the whole time then. Thanks, and sorry for the stupid mistake!

**Comment by avih** [comment]
No worries. Please don't disregard the issue report template next time.
