### ISSUE TITLE
swapinterval=1 should be ignored if dwm composition is enabled

### ISSUE THREAD

**Issue by xnoreq** [mpv-player/mpv#698]
swapinterval=1 (vsync) should be ignored if dwm composition is enabled, because the dwm does vsync itself.

GLFW notices:
"Swap interval setting is also by default disabled by GLFW on Windows Vista and later version when using DWM (Aero), as setting the swap interval there leads to severe jitter on some hardware. "

So if swapinterval=1 is configured by the user, it should be ignored if DwmIsCompositionEnabled() is true. Additionally, during playback of a video swapinterval should be reconfigured if the composition changes (message WM_DWMCOMPOSITIONCHANGED).

http://msdn.microsoft.com/en-us/library/windows/desktop/dd388199%28v=vs.85%29.aspx

In fullscreen dwm composition should be ignored, because I've tested on both Win 7 and 8.1: in fullscreen there is tearing (no vsync) even though DwmIsCompositionEnabled() returns true.

**Comment by wm4** [comment]
Actually, there's a dwm-something suboption now. It's probably suboptimal, but supposedly its implementer didn't find a better solution.
