### ISSUE TITLE
hwdec=vdpau loading failed

### ISSUE THREAD

**Issue by spvkgn** [mpv-player/mpv#6980]
### mpv version and platform
```
mpv-git --version
mpv 0.29.1+git20190919-257534e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Fri Sep 20 04:24:38 UTC 2019
ffmpeg library versions:
   libavutil       56.35.100
   libavcodec      58.58.100
   libavformat     58.32.104
   libswscale      5.6.100
   libavfilter     7.58.102
   libswresample   3.6.100
ffmpeg version: 4.2.git20190920-179e15d
```
```
$ uname -a
Linux ubuntu-pc 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ inxi -G
Graphics:  Card: NVIDIA GF119 [GeForce GT 520]
           Display Server: x11 (X.Org 1.19.6 ) drivers: nvidia (unloaded: modesetting,fbdev,vesa,nouveau)
           Resolution: 1280x1024@75.02hz
           OpenGL: renderer: GeForce GT 520/PCIe/SSE2 version: 4.6.0 NVIDIA 390.116
```
### Reproduction steps
Play h264 encoded video with `hwdec=vdpau`
### Expected behavior
Use hardware decoding as in 0.29.1:
```
[vo/gpu] Probing for best GPU context.
[vo/gpu/opengl] Initializing GPU context 'x11probe'
[vo/gpu/x11] X11 opening display: :0
[vo/gpu/x11] X11 running at 1280x1024 (":0" => local display)
[vo/gpu/x11] Detected wm supports NetWM.
[vo/gpu/x11] Detected wm supports FULLSCREEN state.
[vo/gpu/x11] Detected wm supports ABOVE state.
[vo/gpu/x11] Detected wm supports BELOW state.
[vo/gpu/x11] Display 0 (DVI-I-1): [0, 0, 1280, 1024] @ 75.024675 FPS
[vo/gpu/x11] Current display FPS: 75.024675
[vo/gpu/opengl] GLX chose FB config with ID 0x10d
[vo/gpu/opengl] GLX chose visual with ID 0x27
[vo/gpu/opengl] Creating OpenGL 4.4 context...
[vo/gpu] GL_VERSION='4.4.0 NVIDIA 390.116'
[vo/gpu] Detected desktop OpenGL 4.4.
[vo/gpu] GL_VENDOR='NVIDIA Corporation'
[vo/gpu] GL_RENDERER='GeForce GT 520/PCIe/SSE2'
[vo/gpu] GL_SHADING_LANGUAGE_VERSION='4.40 NVIDIA via Cg compiler'
[vo/gpu] Loaded extension GLX_SGI_swap_control.
[vo/gpu] Loaded extension GLX_SGI_video_sync.
[vo/gpu] Loaded extension GL_NV_vdpau_interop.
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Assuming 75.024675 FPS for display sync.
[vo/gpu] Loading hwdec driver 'vaapi-egl'
[vo/gpu] Loading failed.
[vo/gpu] Loading hwdec driver 'cuda-nvdec'
[vo/gpu] Loading hwdec driver 'vdpau-glx'
Using hardware decoding (vdpau).
```
### Actual behavior
Loading failed and mpv use software decoding.
```
[vo/gpu] Probing for best GPU context.
[vo/gpu/opengl] Initializing GPU context 'x11egl'
[vo/gpu/x11] X11 opening display: :0
[vo/gpu/x11] X11 running at 1280x1024 (":0" => local display)
[vo/gpu/x11] Detected wm supports NetWM.
[vo/gpu/x11] Detected wm supports FULLSCREEN state.
[vo/gpu/x11] Detected wm supports ABOVE state.
[vo/gpu/x11] Detected wm supports BELOW state.
[vo/gpu/x11] Display 0 (DVI-I-1): [0, 0, 1280, 1024] @ 75.024675 FPS
[vo/gpu/x11] Current display FPS: 75.024675
[vo/gpu/opengl] EGL_VERSION=1.4
[vo/gpu/opengl] EGL_VENDOR=NVIDIA
[vo/gpu/opengl] EGL_CLIENT_APIS=
[vo/gpu/opengl] Trying to create Desktop OpenGL context.
[vo/gpu/opengl] chose visual 0x2b
[vo/gpu/opengl] GL_VERSION='4.4.0 NVIDIA 390.116'
[vo/gpu/opengl] Detected desktop OpenGL 4.4.
[vo/gpu/opengl] GL_VENDOR='NVIDIA Corporation'
[vo/gpu/opengl] GL_RENDERER='GeForce GT 520/PCIe/SSE2'
[vo/gpu/opengl] GL_SHADING_LANGUAGE_VERSION='4.40 NVIDIA via Cg compiler'
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Assuming 75.024675 FPS for display sync.
[vo/gpu] Loading hwdec driver 'vaapi-egl'
[vo/gpu/vaapi-egl] VAAPI hwdec only works with OpenGL or Vulkan backends.
[vo/gpu] Loading failed.
[vo/gpu] Loading hwdec driver 'cuda-nvdec'
[vo/gpu] Loading hwdec driver 'vdpau-glx'
[vo/gpu] Loading failed.
```
### Log file
http://sprunge.us/iU0RUJ
[mpv.txt](https://github.com/mpv-player/mpv/files/3639692/mpv.txt)

**Comment by CounterPillow** [comment]
Try with `--gpu-context=x11`

**Comment by jeeb** [comment]
We recently switched from GLX to EGL by default in x11. VDPAU is the only thing that still requires specifically GLX. Everything else (VAAPI, NVDEC) seems to require EGL.

If you really require VDPAU (older nvidia hardware that doesn't support nvdec etc), then you can utilize the GLX back-end as @CounterPillow has noted. Additionally, I would recommend you request a feature from VDPAU developers to add EGL interop.

**Comment by jeeb** [comment]
Basically, checking which hwdec you might have picked as a hint is kind of iffy to do from the x11 context creation. We'd rather not do that.

Before we used to check for the VDPAU extension etc., but
a) that was also implemented by the AMD drivers (which would break VAAPI as that needed EGL).
b) would also pick GLX with nvdec, which also isn't optimal.

**Comment by wm4** [comment]
Does --hwdec=auto work?
Why did you force hwdec=vdpau?

**Comment by mc4man** [comment]
The Op here built mpv with ffnvcodec but their driver version is too low for nvdec/cuda (a min. of 396.24 is required for SDK version 8.2.15 which is what they likely used..
It may be that their GPU can't use anything better than the 390.xx they're using, don't know..
So hwdec=auto won't work.

**Comment by philipl** [comment]
Yeah, we had another report of that. If you rebuild at a sufficiently low sdk version, nvdec would work.

**Comment by wm4** [comment]
OK, broken build as far as I'm concerned.

**Comment by mc4man** [comment]
If a user wanted to use the 390 driver for ffnvcodec then they'd need to use 8.1.24.x sdk but then they'd need to use an older mpv source as current in wscript is 8.2.15.7

**Comment by spvkgn** [comment]
@wm4 
@mc4man 
Nvidia dropped support for GT 500 series in recent drivers, so I have to use 390 version

**Comment by spvkgn** [comment]
@wm4 
@mc4man 
Nvidia dropped support for GT 500 series in recent drivers, so I have to use 390 version

Using `--gpu-context=x11` solved the problem.

**Comment by mc4man** [comment]
Seeing as though you're building your own, if you wanted nvdec/cuda support you could easily do.
ffmpeg supports nv-codec-headers 8.1.24.9 which can be used with "390.25 or newer"
Mpv bumped it's min for ffnvcodec for vulkan and then again for libplacebo.
So if you have no use for vulkan then just remove libvulkan-dev and libplacebo-dev from your build enviroment, edit wscript > 
'func': check_pkg_config('ffnvcodec >= 8.1.24.9'),
and build, will work fine.
When and if nv-codec-headers 8.1 sdk releases 8.1.24.10 and if ffmpeg  bumps to it then just replace your current nv-codec-headers with the new release if doing a new mpv with a new ffmpeg source..
