### ISSUE TITLE
Stuck in buffering after cycling subs

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#6986]
### mpv version and platform
`mpv 0.29.0-715-gb6def652a4 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects`

### Reproduction steps
1. Watch sample file over HTTP so the demuxer cache is active (doesn't happen otherwise)
2. Pause
3. Disable and reenable subs
4. Unpause

### Expected behavior
Playback resumes.

### Actual behavior
Eternally stuck buffering

### Log file
https://0x0.st/ztnr.txt

### Sample files
https://0x0.st/ztdh.mkv

**Comment by wm4** [comment]
Another condition was that the file was fully buffered before doing proceeding with step 3.
