### ISSUE TITLE
Problems Audio Video Desync and audio stuttering with mpv and mpd dash live files

### ISSUE THREAD

**Issue by stifani** [mpv-player/mpv#6989]
### Reproduction steps
run command:
mpv "https://live2-mediaset-it.akamaized.net/Content/dash_d0_clr_vos/live/channel(fu)/manifest.mpd"

### Expected behavior
playing video smoothly without any problem

### Actual behavior
A-V desync after about 1 minute and half (2 minutes) of playing and getting various error messages:
"[cplayer] Audio/Video desynchronisation detected"
"[ad] Invalid audio PTS: xxx -> yyy"
and also:
audio gets stuttering and video slows down

### Log file
https://pastebin.com/XDJSCnsK

### Sample files
None needed

tnx

**Comment by wm4** [comment]
It's exceedingly likely that ffmpeg's often-broken mpd demuxer causes this. Most sites will have a HLS alternative, so use that.

**Comment by stifani** [comment]
ok thanks. And do you know if ffmpeg programmers, are going to fix that? To me it's important to have mpd dash stream working correctly.

Anyway I've found the hls version of this stream. It took me a while to discover it, but here it is the hls version:

https://live3-mediaset-it.akamaized.net/Content/hls_h0_clr_vos/live/channel(fu)/index.m3u8

This stream it's working smoothly.

But do you know if there is any work around or any option to use with mpv to avoid that problem? I've tried --no-correct-pts, --correct-pts, --fps, and more, but none of them worked.

tnx

**Comment by wm4** [comment]
It's almost certain that the ffmpeg dash demuxer returns nonsense and mpv can do nothing about it. The ideal solution would probably involve implementing dash input directly in mpv, but it doesn't look like anyone is interested in it.

The relevant ffmpeg source file and its authors are here: http://git.videolan.org/?p=ffmpeg.git;a=history;f=libavformat/dashdec.c;h=7713ee8907ca10e64ce2e1edfd11fe629624811d;hb=HEAD

Looks like @sfan5 messed with it sometime.

**Comment by sfan5** [comment]
> And do you know if ffmpeg programmers, are going to fix that?

DASH livestreams have been broken since the first time I worked with the dashdec code.
Don't get your hopes up.

**Comment by richardpl** [comment]
Can not fix it if link is forbidden here.

**Comment by stifani** [comment]
> > And do you know if ffmpeg programmers, are going to fix that?
> 
> DASH livestreams had been broken already the first time I worked with the dashdec code.
> Don't get your hopes up.


Tnx @sfan5 . Much appreciated :smile:

---



> Can not fix it if link is forbidden here.


@richardpl 
Unfortunately I discovered afterwards that this link was georestricted to only italian's ip, while I was discussing with wm4. I didn't know that. Anyway it's an italian channel (Focus) which talks about technology and science.

Maybe you can use a vpn to connect to that stream, while in the meantime I'll try to find another similar mpd stream which presents the same problem and I will post here to help you guys to fix the problem.

tnx

**Comment by richardpl** [comment]
It is not ffmpeg bug.

**Comment by wm4** [comment]
It is ffmpeg bug.

**Comment by stifani** [comment]
Hello,

I did not have the time to find some other mpd sources which are not geo-restricted to post here. I've been busy. Sorry about that. But I can agree with wm4. It is definitely a ffmpeg bug.

Here I will post a complete dump of ffmpeg using the latest git build from Zeranoe `ffmpeg version git-2019-10-25-b78227e Copyright (c) 2000-2019 the FFmpeg developers` and running the following command line:

`ffmpeg`
`-user-agent "Mozilla/5.0 (Windows NT 10.0; Win64;x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3554.0 Safari/537.36"`
`-i "https://live2-mediaset-it.akamaized.net/Content/dash_d0_clr_vos/live/channel(fu)/manifest.mpd"`
`-loglevel trace`
`-c copy`
`dump.ts > stdout.txt 2> stderr.txt`

and the result with the complete dump.ts:

https://anonfile.com/pcV9m797nb/ffmpeg_dashmpd_dumpts_completetracelog_rar

I hope this will help you guys to fix the problem. :+1: 


``
``
PS. To wm4,
now `ab-loop-dump-cache`  is working on those hls stream multitrack :smile: Thanks :+1: I'm doing more tests to other hls stream but since now everything is fine. Nice job.

**Comment by zotanmew** [comment]
Apologies for the necrobump but if anyone is still having this issue, could you test if building ffmpeg with the patch https://code.ffmpeg.org/FFmpeg/FFmpeg/pulls/21480.patch fixes the issue for you? I was debugging the same problem, went on a deep dive in ffmpeg's dashdec.c and this change fixed it for me.
