### ISSUE TITLE
[RFC] Support for client-server style scripting

### ISSUE THREAD

**Issue by pigoz** [mpv-player/mpv#6992]
This is a new project I'd like to work on, and I would like to gather some initial feedback before I start.

After working a bit on some mpv scripts, I've come to realize how the DX is not optimal and encourages bad practices (slow virtual machine at least on js side discourages using libraries, automated testing is hard, heavy computations in the scripts lead to bad user experience).

To work around some of it, I've noticed many more complex scripts tend to fork a server-side component and communicate with it. That's quite suboptimal since each script author has to come up with an application-level communication protocol.

To make this style of writing scripts more pleasant to deal with, I'm thinking of is working on a very light set of options on the mpv side, that leverages the existing JSON API, and makes mpv fork and manage script subprocesses.

Example CLI: `mpv --client-script='node test-script.js'`

**This would make mpv create a socket, exec "node test-script.js" passing the socket path either as an argument or ENV variable. The script would then interact with mpv's JSON IPC protocol connecting to that socket.**

I still have to figure out how to deal with CLI options. The simple way would be passing all the options of all the scripts, and the server script then decides which ones it's interested in. I'm open to better ideas. It's a bit meh security-wise.

### Benefits

 - Scripting language agnostic
 - Script code is testable using the target language automated testing libraries
 - Better access to system calls, filesystem, etc
 - Better performance for code-heavy scripts

### Cons

 - Client-server architecture can be harder to deal with, but scripts can hide most of the complexity with a client library.

Any feedback or suggestion is welcome :)

**Comment by avih** [comment]
What's "DX"?

Do you have example use cases? I believe the one I know of (osc thumbnails) uses ffmpeg rather than another instance of mpv. Will your approach cover it too?

If the only issue is non responsiveness of your "main" script, then could this be solved with launching another "worker" script which will communicate with the main script using messages? E.g. here's an experimental commit which allows launching a new JS script by specifying it literally as `"memory://<script-content-goes-here>"`: https://github.com/avih/mpv/commit/981d62a

**Comment by pigoz** [comment]
> What's "DX"?

Developer experience

> Do you have example use cases? I believe the one I know of (osc thumbnails) uses ffmpeg rather than another instance of mpv. Will your approach cover it too?

My approach covers anything, a client script running in a separate process can do anything it wants: create threads, more processes, access files, open sockets, run a webserver, do API calls, etc. It's a separate application after all, you could even write it in Rust, or other systems languages.

Performance is not my main concern BTW, just an added benefit. I'm more interested in being able to automatically test scripts mocking away mpv, and use the target language library ecosystem in an easier way.

**Comment by pigoz** [comment]
> > With some code on the mpv side to display png images on top of the video, it could even be used to draw custom UI without using libass (this is outside of my scope for now, but something I'd like to look at later).
> 
> I mean you can create RGBA overlays (from raw memory or files), though that's old and inefficient code.

Cool, I was not aware. Is that available through a command?

**Comment by wm4** [comment]
>Cool, I was not aware. Is that available through a command?

overlay-add etc.
