### ISSUE TITLE
Any tricks to achieve VLC like hdr tone mapping？

### ISSUE THREAD

**Issue by Vampers** [mpv-player/mpv#6993]
Sorry to bother, just want to know if there are any tricks can be made to let mpv handle hdr tone mapping like VLC and produce a similar output picture quality.

From my perspective, after lots of comparisons made, VLC does probably the best job in hdr tone mapping (compared with madVR, mpv, etc.). 

EDIT: hdr to sdr

**Comment by Doofussy2** [comment]
You should use the icc you made in DisplayCal, in mpv with `--icc-profile=`. Maybe use either reinhard or mobius with your target-peak set to your white point. I use mobius with a param of 0.2, but my display is HDR.

**Comment by Vampers** [comment]
> You should use the icc you made in DisplayCal, in mpv with `--icc-profile=`. Maybe use either reinhard or mobius with your target-peak set to your white point. I use mobius with a param of 0.2, but my display is HDR.

Whether a monitor is HDR or SDR matters a lot when config things like this.

**Comment by Vampers** [comment]
> You should still use your icc.

Yes, I have been using it since I calibrated my monitor and I do know how to use icc in mpv.

**Comment by Doofussy2** [comment]
We talked about this, here

https://github.com/mpv-player/mpv/issues/6072

https://github.com/mpv-player/mpv/issues/6405#issuecomment-472554577

**Comment by haasn** [comment]
We need more information about what you're doing in VLC. What video output module are you using and what are your settings for it?

**Comment by Vampers** [comment]
After some tests, mpv can make it by the following configs:
```
## hdr to sdr
hdr-compute-peak=no
tone-mapping=hable  
tone-mapping-desaturate=1  
tone-mapping-desaturate-exponent=0
```
Very similar for general viewing, however, when using a precise test pattern, VLC produces a bit more detailed image and minor color differences exist.

**Comment by Vampers** [comment]
> We need more information about what you're doing in VLC. What video output module are you using and what are your settings for it?

I use the Windows version of VLC, the settings are the default and the video output module in VLC is set to "auto" by default.

**Comment by Doofussy2** [comment]
What OS and what version of mpv?

**Comment by Vampers** [comment]
> What OS and what version of mpv?

```
mpv 0.29.0-703-gcb32ad68f3 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Sep 22 17:27:27 +08 2019
ffmpeg library versions:
   libavutil       56.35.100
   libavcodec      58.58.101
   libavformat     58.33.100
   libswscale      5.6.100
   libavfilter     7.58.102
   libswresample   3.6.100
ffmpeg version: git-2019-09-21-ba24b24a
```

**Comment by Doofussy2** [comment]
If you use reinhard or mobius, they can be tuned to give you more control. For instance, my present HDR config, looks like this:

```
hdr-compute-peak=no
tone-mapping=mobius
tone-mapping-param=0.2
tone-mapping-desaturate=1
icc-profile=C:\Windows\System32\spool\drivers\color\Adobe RGB (1998) D65 WP 2.2 Gamma.icc
target-peak=200
```

I'm working making an icc for HDR tonemapping, with the same tools as you.

**Comment by Vampers** [comment]
> If you use reinhard or mobius, they can be tuned to give you more control. For instance, my present HDR config, looks like this:
> 
> ```
> hdr-compute-peak=no
> tone-mapping=mobius
> tone-mapping-param=0.2
> tone-mapping-desaturate=1
> icc-profile=C:\Windows\System32\spool\drivers\color\Adobe RGB (1998) D65 WP 2.2 Gamma.icc
> target-peak=200
> ```
> 
> I'm working on making an icc for HDR tone-mapping, with the same tools as you.

Yeah, as described in the documentation, `--tone-mapping=reinhard --tone-mapping-param=0.24` is roughly equivalent to `--tone-mapping=hable`. However, I prefer a simple way and get tired of finding out the exact differences between 0.23, 0.24 and 0.25.

**Comment by Vampers** [comment]
Basically the point is, if you want to make it look like VLC's hdr tone mapping, you should add `hdr-compute-peak=no`.

**Comment by haasn** [comment]
VLC on Windows does no tone mapping, it just passes it through to the windows compositor. See #5804

**Comment by Vampers** [comment]
> VLC on Windows does no tone mapping, it just passes it through to the windows compositor. See #5804

```
Changes between 3.0.0 and 3.0.1:
Video output:
* Fix HDR tone mapping in Direct3d11

Changes between 3.0.1 and 3.0.2:
Video output:
 * Important improvements of the D3D11 video output to use less memory
   and less GPU for HDR tone-mapping

Changes between 3.0.4 and 3.0.5:
Video Output:
 * Fix Direct3D11 tone-mapping when HDR is displayed on an SDR screen

Changes between 3.0.7 and 3.0.7.1:
Video Output:
 * Improve direct3d11 HDR support
```
ref: https://www.videolan.org/developers/vlc-branch/NEWS

**Comment by ValZapod** [comment]
@mabodofutk 

But VLC is complete garbage when decoding YCbCr.

https://code.videolan.org/videolan/vlc/-/issues/25651
https://code.videolan.org/videolan/vlc/-/issues/22731
https://code.videolan.org/videolan/vlc/-/issues/20359
https://code.videolan.org/videolan/vlc/-/issues/25118

**Comment by haasn** [comment]
@mabodofutk I see. I looked at the code and it looks like it does a very trivial per-channel `hable()` operator and nothing else.

In theory, mpv with `--tone-mapping=hable --hdr-compute-peak=no --tone-mapping-desaturate=1 --tone-mapping-desaturate-exponent=0` should produce exactly identical results.
