### ISSUE TITLE
Mpv wayland freeze

### ISSUE THREAD

**Issue by quantmint** [mpv-player/mpv#7007]
### mpv version and platform

Arch Linux, Gnome wayland, Latest mpv, Intel Graphics 4400, i7-4500U

### Reproduction steps

Just open any video with mpv with wayland enabled.
### Expected behavior

Smooth playback
### Actual behavior

The playback freezes for 1 second every 3-4 seconds.
The problem don't occur with another pc with same software but different hardware(i7 2600k,amd vega 56)

**Comment by Dudemanguy911** [comment]
Possibly the same thing as #6484? Does the same thing happen in Weston?

**Comment by quantmint** [comment]
> Possibly the same thing as #6484? Does the same thing happen in Weston?

No, with weston is fine. I also noticed that the problem is worst with high bitrate videos. With x11 all is fine.

**Comment by Dudemanguy911** [comment]
Ah, it's definitely that GNOME bug then. I see that this [issue](https://gitlab.gnome.org/GNOME/mutter/issues/457) is still open. Unfortunately there's not anything we can do here, although it's somewhat interesting that apparently the bug is somewhat hardware-depending.
