### ISSUE TITLE
mpv crashes while trying to use waylandvk context under X

### ISSUE THREAD

**Issue by v-fox** [mpv-player/mpv#7019]
### mpv version and platform
mpv 0.29.0~git20191002T183845 on openSUSE Tumbleweed

### Reproduction steps
Have this in mpv.conf and run it under X:
gpu-api=vulkan
fs=no
autofit=70%x60%
### Expected behavior
Work as always.
### Actual behavior
Crash during trying to use waylandvk instead of x11vk
### Log file
mpv  --profile=HSF-hq --msg-level=vo=v \<video>:
```
[vo/gpu] Probing for best GPU context.
[vo/gpu/vulkan] Initializing GPU context 'waylandvk'
[vo/gpu/vulkan/libplacebo] Creating vulkan instance with extensions:
[vo/gpu/vulkan/libplacebo]     VK_KHR_get_physical_device_properties2
[vo/gpu/vulkan/libplacebo]     VK_KHR_external_memory_capabilities
[vo/gpu/vulkan/libplacebo]     VK_KHR_external_semaphore_capabilities
[vo/gpu/vulkan/libplacebo]     VK_KHR_surface
[vo/gpu/vulkan/libplacebo]     VK_KHR_wayland_surface
mpv: ../ta/ta.c:335: ta_dbg_check_header: Assertion `h->canary == CANARY' failed.
[1]    10493 abort (core dumped)  mpv  --profile=HSF-hq --msg-level=vo=v
```
### Workaround
gpu-context=x11vk
### Cause
Probably https://github.com/mpv-player/mpv/issues/7011 and related commit https://github.com/mpv-player/mpv/pull/7012

**Comment by sfan5** [comment]
Can't reproduce, no crash here. Do you have a complete logfile?

**Comment by Dudemanguy911** [comment]
I can. It's still my fault but I think it's c669a43. Oddly it doesn't crash on opengl just vulkan.
