### ISSUE TITLE
automatically drop-buffers on rtsp playback resume

### ISSUE THREAD

**Issue by rhetr** [mpv-player/mpv#7022]
### mpv version and platform

mpv git-2019-09-22-4a2f239 xubuntu 18.04.3

I am running a camera livestream on an occasionally spotty wireless connection. Currently when connection is lost and then restored, playback resumes where it left off, but I would like for it to drop-buffers or seek to the latest footage--I can manually do this by pressing the right arrow key but how can I make this happen automatically?

**Comment by wm4** [comment]
In theory, you could actually just use --untimed, which essentially sets the playback speed to infinite. It should have the effect that it always catches up to the most recent frame sent by the camera. This will also prevent desync over time if the PC plays video at slightly lower rate than the camera sends it. Not recommended if there's also an audio stream.

Though it's not really clear to me how this reconnecting works?

**Comment by rhetr** [comment]
it's typically automatic. --untimed seems to work, I will continue to test and reopen if necessary.
