### ISSUE TITLE
Mpv does not send playing line text

### ISSUE THREAD

**Issue by 422658476** [mpv-player/mpv#7023]
### mpv version and platform
mpv-i686-20190922 for windows

Hello, I am the author of mpv-easy player. When I use mpv-i686-20190922 as the backend, I found that mpv does not send the text of the playing line from the named pipe when opening a single video file.
At first I tried to be compatible with this new change, but finally found it difficult to update the video file name when remembering the playback progress, unless I always send a command to get the file name to mpv and receive the result (command": ["get_property_string", "filename"]), but this is very inefficient, so I think this is a bug.

Open files in versions prior to 20190922 will send this information：

**Playing: Y:\move\xxxx.mkv**

 (+) Video --vid=1 (*) (h264 1920x1080 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)

Using hardware decoding (d3d11va).
VO: [gpu] 1920x1080 d3d11[nv12]

In 20190922, the text of the playing line is not sent, and it becomes like this.

 (+) Video --vid=1 (*) (h264 1920x1080 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)

Using hardware decoding (d3d11va).
VO: [gpu] 1920x1080 d3d11[nv12]

**Comment by Dudemanguy911** [comment]
You don't always have to always send a command. I don't know how mpv-easy player works, but I assume you use the client API in some way (C, lua, or whatever). You can just register an event (for example wait for a "file-loaded" event) and then update the filename when that happens.

**Comment by wm4** [comment]
Yes, not a bug. Use the event. The JSON API requires you to explicitly enable the event with another command.

**Comment by 422658476** [comment]
Thank you very much, after reading the manual.pdf again, I have started to use the observe_property to solve this problem, I believe it can be completely solved.

But I still think this is a bug. On the surface, what you said is completely correct, but in the deeper sense, the reason for this problem is definitely because of the modification of the recent code of mpv.

The reasons are as follows:

1. I started making mpv-easy player (for surely more than 1.5 years). I used the text of the playing line to get the name of the video file. Every time I open the video file, I can get the text of playing. I never get it. Not until the mpv-i686-20190922 for windows version.

2, mpv-i686-20190922 for windows this version：

-   a. Play a single file, this line of playing is not available

-  b. But when you run a playlist file, the playing line will be displayed, just like the previous version.

-   c. Play a single file on the network drive, the playing line will be displayed, same as the previous version

So I have good reason to believe that not showing the playing line is a bug, and it appears from the 20190922 version. I know that you are very familiar with the mpv code. I hope you can analyze it further. All I can do is report this problem.

Thank you again for your message, thank you very much.

**Comment by wm4** [comment]
Scripts etc. are not supposed to parse terminal output. If you do so, you need to deal with breakages yourself; we don't consider them incompatible changes. The status line changes its format every other month or so. There's more than enough API that is explicitly provided so that you don't parse the output intended for human users.

I removed the message myself here: https://github.com/mpv-player/mpv/commit/a80f63cb9a889a4fc5f32fb17de5d9e2eedb3e7f

**Comment by 422658476** [comment]
I don't know much about git, but as you can see from a80f63c, you removed the playing line code on May 16. I was amazed at why the changes were only in the 20190922 version that was a few months late.

The text description on the a80f63c page is basically the same as the result of my test. The play line will still be displayed when running a playlist file.

Perhaps this line is for you: This is just redundant and slightly annoying.

But the playing line is very important and even crucial for beginners like me.

Because when I started making the initial version of the mpv-easy player, I didn't know what a named pipe was. When I tested the mpv-easy player, I stumbled upon the qt creator's debug interface constantly popping up the playing line and the information below. There is even time in another pipeline.

Nothing wrong, this information was even stumbled upon in the qt creator. When I found this, I started to try to capture the code myself from qt, and finally I went from:
readAllStandardOutput()
readAllStandardError()
Successfully found them. This is still unforgettable.

In fact, when you capture the information in these two pipes, plus the send cmd command, you can make a very good player front end, at least all the controls and information are no problem.

Perhaps the information in the two pipes is as you said: Scripts etc. are not supposed to parse terminal output. If you do so, you need to deal with breakages yourself.

But for us beginners, these are good things, because you don't need to go through and learn QLocalSocket, that is, you don't need to build a pipeline to start making the player front end, and the information is completely enough.

In fact, all the important information in the player is the same as what you said. I have filtered from these two pipes.

When I started to master QLocalSocket, I still didn't change the code because they worked fine and I don't need to improve them.

Until this time, I thought I had all the necessary code skills, and even had everything in manual.pdf that should be up, but I still ignored the observe_property.

I said so much, what I actually want to say is that making a player front end is actually very complicated for most people and needs to learn a lot. If you have less knowledge, you can make the initial version, which is a great encouragement for beginners, which can greatly enhance their confidence, and then continue to improve and learn the missing knowledge. If there is no initial version, then there is nothing.

If you deleted the playing line display code a few years ago, then the player front end that I am making now is impossible to exist because I don't have enough ability to get the video name, and I can't finish all the knowledge before I start making it.

If you can add this line again from the beginner's point of view, I believe it can help many people who love code, mpv, and player.

Thank you again.

Through communication with you and observe_property, I have improved all the code, even better than before, and now only need to remove the useless code and fix the bug.

Many thanks.

**Comment by wm4** [comment]
It may have helped you once, but that doesn't mean that everyone makes this experience, nor that it's a good idea to keep it.
