### ISSUE TITLE
Subprocess immidiately killed when idle

### ISSUE THREAD

**Issue by jonniek** [mpv-player/mpv#7025]
### mpv version and platform
Reproduced on the following builds and platforms:
mpv 0.29.0-343-gc379950ce0 on windows 10
mpv 0.29.1 on Linux Slackware 14.2

### Reproduction steps
1. open any file with `--idle`
2. verify that a script with subprocess works
3. let the file end and wait for mpv to enter idle
4. run the script again

Sample script:
```lua
local utils = require 'mp.utils'
mp.add_key_binding("a", function()
  -- {'powershell', 'echo', 'test'} for windows
  local args = {'echo', 'test'}
  local res = utils.subprocess({ args = args })
  print(utils.to_string(res))
end)
```

### Expected behavior
Subprocess after entering idle will execute without failing: `{"status" = 0, "stdout" = "test", "error_string" = "", "killed_by_us" = false}`

### Actual behavior
Subprocess fails immidiately: `{"stdout" = "", "status" = -2, "error" = "killed", "killed_by_us" = true, "error_string" = "killed"}`

### Additional information
  - if mpv is launched with no file and --idle, the script works as expected

### Log file
https://0x0.st/zwNy.log

**Comment by jonniek** [comment]
I actually thought cancellable was false on default. So this can be fixed by giving the subprocess `cancellable = false`. However, the behavior is not immediately clear from documentation:

> cancellable
> Optional. If set to true (default), then if the user stops playback or goes to the next file while the process is running, the process will be killed.

I think idle before a file and idle after a file should have the same behavior or then the documentation could be clarified a bit.

**Comment by wm4** [comment]
This is the current documentation: https://mpv.io/manual/master/#command-interface-subprocess
It says:
>  If enabled, stopping playback will automatically kill the process, and you can't start it outside of playback.

**Comment by wm4** [comment]
Also I agree that the default should have been different, but too late.

**Comment by jonniek** [comment]
> can't start it outside of playback

Maybe it should also fail then on initial idle when opening mpv with no file.

**Comment by wm4** [comment]
> Maybe it should also fail then on initial idle when opening mpv with no file. 

If it doesn't do that then it's a bug.

**Comment by avih** [comment]
Maybe it should have something like `cancellable=onexit` meaning playback or changing files won't affect it (as well as allowing to start when idle), and it would only get cancelled on mpv exit?

**Comment by wm4** [comment]
> Maybe it should have something like cancellable=onexit meaning playback or changing files won't affect it (as well as allowing to start when idle), and it would only get cancelled on mpv exit?

I think that happens anyway.

**Comment by wm4** [comment]
I think the commits above should clarify this.
