### ISSUE TITLE
Implement code quality and confomity checks on the CI

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#7027]
We have CI integration (e.g. https://github.com/mpv-player/mpv/blob/master/.travis.yml), which mostly checks whether the code still builds.

We should implement further checks. For example, we there are various code quality tests we could run (static analysis and so on). Or we could add checks whether changes added by a pull request conform to the project's coding style.

Anyone who wants is invited to pick this up and to implement it. I created this issue in case there's interest. Feel free to make suggestions in this issue or to ask questions.

**Comment by nitish091** [comment]
I want to take this.

**Comment by wm4** [comment]
It's available. Can you join IRC to discuss this?

**Comment by nitish091** [comment]
I have joined #mpv-devel as raw_nitish

**Comment by wm4** [comment]
Well, I'm on IRC. Feel free to contact me any time, including any questions etc. you might have.

**Comment by wm4** [comment]
So to detail what would encompass this:
- you write a script or such that analyzes the mpv source code
- what or how it analyzes the code is mostly up to you (but I can provide suggestions and advice)
- this script will run on the CI (might be called from travis.yml directly or indirectly)
- the script needs to report back whether there is anything bad (and you need to find out what mechanisms travis/github provide to do so)

As an initial simple thing, you could implement checks for trailing spaces. A trailing space is a space at the end of the line and that has no function. The script would iterate over every source file, check every line, and raise an error if a trailing space is found anywhere.

**Comment by Dudemanguy** [comment]
Not that this wouldn't be nice to have, but well wm4 isn't around anymore of course and we use github actions these days so closing this as "severely dated".
