### ISSUE TITLE
Failed to append fragmented mp4  .m4s files

### ISSUE THREAD

**Issue by hanguofu** [mpv-player/mpv#7029]
### mpv version and platform

mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.6-0ubuntu0.18.04.1

platform : Ubuntu 18.04.3 LTS

### Reproduction steps
I modified simple.c at libmpv/example as follows : 

const char *cmd[] = {"loadfile", "/home/hanguofu/frag_speed8/init.mp4", NULL};
const char *cmd2[] = {"loadfile", "/home/hanguofu/frag_speed8/segment_1.m4s", "append" , NULL };
const char *cmd3[] = {"loadfile", "/home/hanguofu/frag_speed8/segment_2.m4s", "append"  , NULL  };

   check_error(mpv_command(ctx, cmd));
     check_error(mpv_command(ctx, cmd2));
     check_error(mpv_command(ctx, cmd3));

### Expected behavior
play the above fragmented mp4

### Actual behavior
failed to recognize all m4s files.
### Log file

[  19.163][i][cplayer] Playing: /home/hanguofu/frag_speed8/segment_1.m4s
[  19.164][v][ifo] Opening /home/hanguofu/frag_speed8/segment_1.m4s
[  19.166][v][ifo_dvdnav] Opening /home/hanguofu/frag_speed8/segment_1.m4s
[  19.166][v][bdmv/bluray] Opening /home/hanguofu/frag_speed8/segment_1.m4s
[  19.167][v][file] Opening /home/hanguofu/frag_speed8/segment_1.m4s
[  19.167][v][file] Stream opened successfully.
[  19.169][v][demux] Trying demuxers for level=normal.
[  19.183][v][lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=8192.
[  19.183][w][ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding track id 1
[  19.183][e][ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding trex
[  19.183][e][ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: error reading header
[  19.183][e][lavf] avformat_open_input() failed
[  19.186][v][demux] Trying demuxers for level=unsafe.
[  19.199][v][lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=8192.
[  19.199][w][ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding track id 1
[  19.199][e][ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: could not find corresponding trex
[  19.199][e][ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: error reading header
[  19.199][e][lavf] avformat_open_input() failed
[  19.204][v][cplayer] Opening failed or was aborted: /home/hanguofu/frag_speed8/segment_1.m4s
[  19.204][v][cplayer] finished playback, unrecognized file format (reason 4)
[  19.204][e][cplayer] Failed to recognize file format.
[  19.204][i][cplayer]
[  19.204][v][global] config path: 'watch_later' -> '-'

### Sample files
Not avail.

The reason I did not  put all these m4s files into a mpd file is because mpv fetch these segments in a rush , which put heavy load at my media server. Of couse , mpv plays all of them smoothly if I put them into a mpd file.  For this reason , I modified libmpv/sample/simple.c to feed libmpv with these m4s files at a constant interval. However , it seems fail to recognize them.

**Comment by CounterPillow** [comment]
>mpv 0.27.2

update
