### ISSUE TITLE
Dual monitor fullscreen glitches

### ISSUE THREAD

**Issue by xnoreq** [mpv-player/mpv#703]
mpv on Windows, 2 monitors:
a) notebook monitor (1920x1080), to the right
b) external monitor (1920x1080), primary, to the left

A little test program (mi is MONITORINFO):
printf("%d %d %d %d\r\n", mi.rcMonitor.top, mi.rcMonitor.bottom, mi.rcMonitor.left, mi.rcMonitor.right);

Outputs for monitor
a) -106 974 1920 3840
b) 0 1080 0 1920

Going into fullscreen on b) works, but on a) it leads to a black screen with small area where the actual video appears and there's even a black mpv window. There's nasty flickering, as if mpv tries to change window size for each frame or something..

**Comment by bendem** [comment]
I see that happening on linux (fedora 22) too.
Playing a movie on one screen, scrolling in firefox or having a terminal outputing text on the other screen makes mpv flicker.
When mpv in in fullscreen, it doesn't flicker but stutter instead.
```
~ $ mpv --version
mpv 0.13.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100

~ $ uname -a
Linux bendem 4.2.8-200.fc22.x86_64 #1 SMP Tue Dec 15 16:50:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
If I can provide any more useful information, just tell me.

**Comment by wm4** [comment]
I doubt this is related.

**Comment by bendem** [comment]
I don't know if it is. I can open an new issue if you prefer.

**Comment by kevmitch** [comment]
A lot has changed since last update. reopen if problems persist.
