### ISSUE TITLE
Compilation failure: waf incorrectly detects vulkan availability

### ISSUE THREAD

**Issue by mlindner** [mpv-player/mpv#7034]
### mpv version and platform

latest master branch - 1ff77102ee8

### Reproduction steps

On Arch Linux try to build mpv with default configuration without --disable-vulkan.

### Expected behavior

Vulkan is detected despite not having headers installed. It should not be detected.

### Actual behavior

[141/248] Compiling video/out/vulkan/utils.c
[142/248] Compiling stream/stream.c
In file included from ../video/out/vulkan/common.h:26,
                 from ../video/out/vulkan/utils.h:2,
                 from ../video/out/vulkan/utils.c:2:
/usr/include/libplacebo/vulkan.h:26:10: fatal error: vulkan/vulkan.h: No such file or directory
   26 | #include <vulkan/vulkan.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

### Log file

https://0x0.st/zwW8.txt

Of note the output of the pkg-config that is ran:
➜  mpv git:(master) ✗ /usr/bin/pkg-config vulkan --libs --cflags vulkan
-lvulkan

**Comment by sfan5** [comment]
Not an mpv bug, when pkg-config finds vulkan it is assumed that vulkan <i>actually exists</i>.
Upstream issue: https://bugs.archlinux.org/task/56238 (closed wontfix)

**Comment by wm4** [comment]
There's nothing we can do against broken setups. If the .pc file is present, compilation should not fail when trying to use the include files and lib files provided by it. That's the whole point of .pc files. Sad to see that the arch maintainers are too ignorant or uncaring to see this.

**Comment by mlindner** [comment]
@wm4 Can we keep this open. I'll re-raise this with arch linux.

**Comment by wm4** [comment]
Doesn't make sense to keep it open, because we can't act upon it. This is arch's problem.
