### ISSUE TITLE
Youtube video doesn't show cache status

### ISSUE THREAD

**Issue by paulguy** [mpv-player/mpv#7038]
### mpv version and platform

mpv 0.29.0-822-g68bbc55eda
Arch Linux

### Reproduction steps
` $ mpv --no-config --log-file=mpvlog.txt https://www.youtube.com/watch?v=8Uz9mYJAD58`

### Expected behavior
Show how much video is cached and the segment lines on the timeline.

### Actual behavior
No cache information displayed, as if it's a local file.  This happens with certain youtube videos but not all.

### Log file
https://0x0.st/zw0c.txt

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wm4** [comment]
Seems like the DASH thing prevents that it's detected as network source. That's a big one. I never noticed because I enabled the cache by default for everything.

**Comment by wm4** [comment]
Actually it's just that thing youtube does immediately after a video is uploaded.
