### ISSUE TITLE
[feature request] youtube thumbnail support

### ISSUE THREAD

**Issue by mat8913** [mpv-player/mpv#7041]
### mpv version and platform

0.29.1 on NixOS

### Reproduction steps

Run `mpv --audio-display=attachment --ytdl-format=bestaudio $ANY_YOUTUBE_URL`.

### Expected behavior

Show the youtube thumbnail from `youtube-dl --get-thumbnail $ANY_YOUTUBE_URL`, similarly to how mpv will show embeded images in audio files.

### Actual behavior

No image is shown at all.

### Sample files

Any youtube video will do.

**Comment by wm4** [comment]
Does youtube-dl -J (JSON output) report a URL for the thumbnails somewhere?

**Comment by mat8913** [comment]
Indeed it does, `.thumbnails` is an `Array<{url: string, id: string}>`.

**Comment by mat8913** [comment]
For youtube videos, youtube-dl will always output only a single thumbnail image. Other ytdl-supported sites can vary, for example vimeo will give the same thumbnail in multiple different sizes, xvideos will give multiple different thumbnails.

Also, what I wrote above is slightly inaccurate. It turns out that `url` is the only required field, `id` is optional and there are other optional fields too. Source: https://github.com/ytdl-org/youtube-dl/blob/aaf9d904aa77bfe60714393c0ab413c32cca8a39/youtube_dl/extractor/common.py#L217

**Comment by wm4** [comment]
It seems they don't have timestamps either. This feature request is about video thumbnails, right?
I know HLS and mp4 have mechanisms for this, but I guess streaming sites will roll their own web.-based crap.

**Comment by wm4** [comment]
At least that would be easier to implement. Still much of a corner case.

**Comment by mat8913** [comment]
For the thing you were talking about, perhaps the [invidious](https://github.com/omarroth/invidious) API would be useful? You can get lowres previews for any youtube video from `https://invidio.us/api/v1/storyboards/$VIDEO_ID?height=90`.

**Comment by avih** [comment]
> perhaps the invidious API would be useful?

That looks neat in general, and also specifically for timeline thumbnails. Thanks.
