### ISSUE TITLE
Supress video-sync cancellation 

### ISSUE THREAD

**Issue by SairesArt** [mpv-player/mpv#7048]
I'm a big fan of --video-sync=display-resample and it's smoothness, slowing down 60fps video to playback on a 59.95hz display without frame dups is awesome.
Seemingly, when playback starts hitching, failing and dropping frames, then video-sync is disabled. This behavior clashes with usability. My GPU can't playback video smoothly when in a window, but fullscreen it's great
When I go out of fullscreen, alt-tab even for a short time, video-sync is apparently canceled because of slow playback. When I return to fullscreen, it remains canceled. There should be a way to suppress this. Maybe there already is?

mpv 0.29.1, linux

**Comment by wm4** [comment]
It gives up if the timings are too extreme. Disabling this mode is supposed to avoid that playback is ruined; there's not much of a point to continue this way if timings make no sense.

There's nothing to reenable this mode on the fly. This would require either "retrying" it after a while (can and will lead to stupid periodical playback glitches if it can't recover), or always "repeating" frames to collect timing statistics (can and will lead to pointless GPU usage, especially if vsync doesn't work - good way to heat up your GPU).

We could also refrain from disabling it. It would lead to degraded playback, i.e. stuttering video, and audio would get maximally resampled for no gain. With audio disabled it'd probably be worse.

Whatever it is what users want.

**Comment by Akemi** [comment]
also related to #6342. 

possibly an option to try reenabling it n-times in the next x seconds after it was forcibly disabled? a command to reenable it might be good, for possible user scripts that could define their own behaviour?

**Comment by wm4** [comment]
Curious how this will work out for you. Now the bad/stuipid effects of a desync will be more severe and obvious.

**Comment by aufkrawall** [comment]
Thanks @wm4 . I always felt uncomfortable with the possibility of breakage after heavy resizing on Windows ra d3d11. I'll test for oddities with shinchiro's next build.
