### ISSUE TITLE
Twitch after first OSD appearance

### ISSUE THREAD

**Issue by Sebastian69** [mpv-player/mpv#7050]
### mpv version and platform

Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
Kernel:         4.15.0-65-generic

```
$ mpv -v
[cplayer] Command line options: '-v'
[cplayer] mpv git-2019-04-25-71ad1e2 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
[cplayer]  built on Sun Jun  9 20:21:48 UTC 2019
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.26.100
[cplayer]    libavcodec      58.52.100
[cplayer]    libavformat     58.27.103
[cplayer]    libswscale      5.4.100
[cplayer]    libavfilter     7.50.100
[cplayer]    libswresample   3.4.100
[cplayer] ffmpeg version: git-2019-04-28-3dee6c0
[cplayer] 
[cplayer] Configuration: ./waf configure --enable-pdf-build --enable-dvbin --enable-dvdread --enable-dvdnav --enable-javascript --enable-html-build --enable-cdda --enable-zsh-comp --zshdir=/usr/share/zsh/vendor-completions --prefix=/usr --confdir=/etc/mpv
[cplayer] List of enabled features: 52arch alsa asm atomics build-date cdda cplayer cplugins cuda-hwaccel debug-build drm dvbin dvdnav dvdread dvdread-common egl-drm egl-helpers egl-x11 fchmod ffmpeg ffnvcodec gbm gbm.h gl gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack javascript jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm librt linux-fstatfs lua optimize oss-audio posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rubberband stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vt.h x11 xv zlib zsh-comp
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] Reading config file /home/sebastian/.config/mpv/mpv.conf
[cplayer] Warning: option --subcp was replaced with --sub-codepage and might be removed in the future.
[cplayer] Error parsing option cache-default (option not found)
[cplayer] /home/sebastian/.config/mpv/mpv.conf:52: setting option cache-default='4000000' failed.
[cplayer] Error parsing option cache-backbuffer (option not found)
[cplayer] /home/sebastian/.config/mpv/mpv.conf:53: setting option cache-backbuffer='500000' failed.
[ifo] Opening /home/sebastian/.config/mpv/input.conf
[ifo_dvdnav] Opening /home/sebastian/.config/mpv/input.conf
[bdmv/bluray] Opening /home/sebastian/.config/mpv/input.conf
[file] Opening /home/sebastian/.config/mpv/input.conf
[input] Parsing input config file /home/sebastian/.config/mpv/input.conf
[input] Input config file /home/sebastian/.config/mpv/input.conf parsed: 47 binds
   cplayer: mpv git-2019-04-25-71ad1e2 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
   cplayer:  built on Sun Jun  9 20:21:48 UTC 2019
   cplayer: ffmpeg library versions:
   cplayer:    libavutil       56.26.100
   cplayer:    libavcodec      58.52.100
   cplayer:    libavformat     58.27.103
   cplayer:    libswscale      5.4.100
   cplayer:    libavfilter     7.50.100
   cplayer:    libswresample   3.4.100
   cplayer: ffmpeg version: git-2019-04-28-3dee6c0
   cplayer: 
   cplayer: Usage:   mpv [options] [url|path/]filename
   cplayer: 
   cplayer: Basic options:
   cplayer:  --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
   cplayer:  --no-audio        do not play sound
   cplayer:  --no-video        do not play video
   cplayer:  --fs              fullscreen playback
   cplayer:  --sub-file=<file> specify subtitle file to use
   cplayer:  --playlist=<file> specify playlist file
   cplayer: 
   cplayer:  --list-options    list all mpv options
   cplayer:  --h=<string>      print options which contain the given string in their name
   cplayer: 
 ytdl_hook: script-opts/ytdl_hook.conf not found. 
 ytdl_hook: lua-settings/ytdl_hook.conf not found. 
     stats: script-opts/stats.conf not found. 
     stats: lua-settings/stats.conf not found. 
 ytdl_hook: Exiting...
     stats: Exiting...
       osc: script-opts/osc.conf not found. 
       osc: lua-settings/ is deprecated, use directory script-opts/ 
       osc: Exiting...
```

### Reproduction steps
Start video (in fresh mpv instance), then press any valid hotkey on keyboard.

### Expected behavior
Execute hotkey action without any twitch.

### Actual behavior
Both video and audio stops for a about 2-3 seconds (play/pause button doesn't toggle), then action is executed and video continues playing.

Then any other hotkey doesn't cause the twitch, even when new video file is loaded into the existing window.

Also when no hotkey is pressed (or mpv is controlled with mouse), video plays as expected without any twitch.

Happens with any file.

Full log file: https://pastebin.com/Z46Djnmh

### Log file

> Warning: option --subcp was replaced with --sub-codepage and might be removed in the future.
> Error parsing option cache-default (option not found)
> /home/sebastian/.config/mpv/mpv.conf:52: setting option cache-default='4000000' failed.
> Error parsing option cache-backbuffer (option not found)
> /home/sebastian/.config/mpv/mpv.conf:53: setting option cache-backbuffer='500000' failed.
>        osc: lua-settings/ is deprecated, use directory script-opts/ 
>    cplayer: Resuming playback. This behavior can be disabled with --no-resume-playback.
>    cplayer: Playing: passengers - let her go.mp4
>    cplayer:  (+) Video --vid=1 (*) (h264 1920x1080 25.000fps)
>    cplayer:  (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
>    cplayer: AO: [pulse] 44100Hz stereo 2ch float
>    cplayer: VO: [gpu] 1920x1080 yuv420p
> statusline: AV: 00:06:40 / 00:20:31 (32%) A-V:  0.000 Cache: 829s+110MB
> [----------------------------------------------------+--------------------------------------------------------------------------------------------------------------]
>    cplayer: Saving state.
>    cplayer: 
>    cplayer: 
>    cplayer: Exiting... (Quit)

**Comment by CounterPillow** [comment]
>0.14

Update.

**Comment by Sebastian69** [comment]
@CounterPillow Updated, I have also updated the logs. Problem persists.

**Comment by CounterPillow** [comment]
I still can't reproduce. Post a full log file generated with `--log-file=filenamehere.log`.

**Comment by Sebastian69** [comment]
Yes, Sir. Here you go: https://pastebin.com/Z46Djnmh

Thank you for your effort.

**Comment by CounterPillow** [comment]
Does the issue also occur with `--no-config`? This will prevent the loading of scripts and config files.

**Comment by Sebastian69** [comment]
Yes, it does occures even when launched with `--no-config` option.

**Comment by avih** [comment]
This could be related to first rendering of the OSD. IIRC this can be caused by libass trying to resolve fonts things at the first time it has to display text.

Does the issue persist if you use `--osd-level=0` ?

**Comment by Sebastian69** [comment]
@avih You're absolutely right, it doesn't happen when OSD is turned off!

**Comment by avih** [comment]
Well, changing `--osd-level` is not a great solution, because IIRC it can also happen the first time subtitles are displayed, or first time the OSC (with the play/pause/etc buttons) is displayed.

I suggest maybe to select a specific OSD font in your configuration to speed it up a little.

AFAIK this typically can happen only on linux, but not 100% sure.

**Comment by Sebastian69** [comment]
I have had **Source Sans Pro** as an osd-font, tried to changed it to Open Sans, Ubuntu, Verdana, nothing seems to help. Is there any particular font to select?

**Comment by avih** [comment]
I don't think some fonts load faster than others, but I thought that specifying a specific font could help - but apparently it didn't.

I don't have other ideas, sorry. Maybe others know more or have more useful suggestions.

**Comment by mc4man** [comment]
with 16.04 & same package don't see this behavior. Main diff I see in log is I don't use or have ~/.font/
Instead just use the default which is /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf

**Comment by Sebastian69** [comment]
@mc4man You're right, if I rename `.fonts` folder to `.fonts_`, it doesn't happen!

My .fonts folder has about 120 MB, 460 files inside. Could this be related? However, specifying `DejaVu Sans` didn't help, either the full path `/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf` (font file does exist).

**Comment by haasn** [comment]
Does `fc-match "Source Sans Pro"` also take forever?

**Comment by DanOscarsson** [comment]
mpv does create many objects the first time they are needed. This includes libass objects and shaders. Both can be very heavy and take longer then the time between two frames.
To avoid this mpv could, for heavy vo related objects, try to create them before first first frame is submitted to the vo. When OSD or a subtitle track is activated mpv creates the libass object with initialisation which can take a long time and that can delay when a frame can be displayed.
If instead mpv created them during vo creation/initialisation (keeping them even if not needed at the moment) this can be avoided. Same can be said for shaders and other cpu/time heavy objects - if they can be created before first frame is submitted to vo, the risk of audio/video issues is reduced.

**Comment by Sebastian69** [comment]
@haasn Yes, exactly the same time (2-3 seconds)! The output is:

> $ fc-match 'Source Sans Pro'
> SourceSansPro-Regular.ttf: "Source Sans Pro" "Regular"

**Comment by CounterPillow** [comment]
Do you by any chance have an ungodly amount of fonts installed on your system? Like thousands of them?

If `fc-match` takes this long something is going on with your fontconfig

**Comment by haasn** [comment]
If `fc-match` reproduces the bug then it is probably not an mpv bug.
