### ISSUE TITLE
hwdec=d3d11 no longer works with current version of libangle

### ISSUE THREAD

**Issue by morphogo** [mpv-player/mpv#7054]
### mpv version and platform

Mpv git master + debug build of libangle git master compiled with vs2019  + windows 10 x64 / msys2 

Mpv git master +  libangle from  Google Chrome browser 77.0.3865.120    + windows 10 x64 / msys2 

### Reproduction steps

The extension `EGL_ANGLE_stream_producer_d3d_texture_nv12` required by  `video/out/opengl/hwdec_d3d11egl.c` no longer exists in libangle. It seems to be replaced by `EGL_ANGLE_stream_producer_d3d_texture`.

[EGL_ANGLE_stream_producer_d3d_texture.txt](https://github.com/google/angle/blob/master/extensions/EGL_ANGLE_stream_producer_d3d_texture.txt)

#6386 hwdec=dxva2 is also broken with the current version of libangle

PS: You can just grab `egl.dll` , `libglesv2.dll` and `d3dcompiler_47.dll` from your Google Chrome browser installation if don't want to build libangle yourself,  assuming your mpv is already built with libangle support.

**Comment by wm4** [comment]
Yes, they renamed it in nov. 2017 (angle 3dddccff31be90fe), and mass renamed all identifiers.

A typical change is removing all mentions of nv12:
```
-    valid ID3D11Texture2D object of the format DXGI_FORMAT_NV12 that is owned
+    valid ID3D11Texture2D object of a supported format that is owned
```

I guess here's the list of supported formats: https://github.com/google/angle/blob/master/src/libANGLE/renderer/d3d/d3d11/StreamProducerD3DTexture.cpp#L40

Should be easy to fix, and in a way that supports 10 bit.

**Comment by wm4** [comment]
Well, I tried to get a dev setup going, but everything was against me. (How can anyone stand using this turd of an OS?)
Will remove all traces of ANGLE from mpv tomorrow, unless someone stops me.

**Comment by rossy** [comment]
If it's just a case of renaming identifiers, and some simple fixes for 10-bit, I could take a look. I'm happy to see hwdec_d3d11eglrgb gone though.

**Comment by wm4** [comment]
Changed it. I hate Windows, ANGLE, Google, and Intel, so on the next issue I might really remove ANGLE support.
P010 is untested, but if it doesn't work you fortunately won't report it due to the aforementioned threat, I hope.

**Comment by rossy** [comment]
> Though I just don't see why you'd put further effort into ANGLE. We already have 3 backends that work on windows (native GL, vulkan, d3d11), where the latter should be superior to ANGLE anyway.

I just assumed we were keeping ANGLE support around to give a good option to libmpv/Qt embedders. I could take or leave the ANGLE VO itself, but it's not the part that's causing trouble at the moment. Anyway, thanks for fixing it (despite Windows' horribleness.) I suppose I should look into D3D11 embedding for libmpv.

**Comment by wm4** [comment]
True, Qt embedding is the only actual use case left, but I wouldn't be too sad if that got lost. In my opinion, it's the problem of Qt embedders, and _they_ should work towards native d3d11 support or whatever. I think Qt can also do vulkan now.

**Comment by morphogo** [comment]
Thanks for fixing `hwdec=d3d11`. Any chance, #6386  `hwdec=dxva2` can be fixed too ?

**Comment by wm4** [comment]
What for?
