### ISSUE TITLE
"auto-profiles.lua" for replaygain info ?

### ISSUE THREAD

**Issue by denmapanter001** [mpv-player/mpv#7055]
OS:win10  x64
If MPV get RG file(replaygain info),like this

[replaygain]
profile-desc=cond:p["metadata"]
af-del=lavfi=loudnorm
replaygain=album
volume=100
audio-exclusive=yes
audio-fallback-to-null=yes

How do you think ?

**Comment by wm4** [comment]
I think nobody knows what you mean. You can already detect presence of replaygain by looking at the track-list property. The profile you pasted looks like from auto-profiles.lua and the issue title has that too (how do you even know this script), but that should be able to handle it too. Not sure if replaygain runtime switching works.

**Comment by denmapanter001** [comment]
Thank you for your comments.
The purpose is that the profile(auto-profiles.lua) works depending on the presence of Replaygain information.
I'm not going to listen to audio files on MPV, but I watch music video files.
So I'm bypassing like this
  ##AO##
af=lavfi=loudnorm
volume=75
audio-channels=stereo
audio-fallback-to-null=yes
[extension.mka]
af-del=lavfi=loudnorm
replaygain=album
volume=100
audio-exclusive=yes
audio-fallback-to-null=yes
[extension.m4a]
profile=extension.mka

If you can avoid that purpose by specifying a specific folder, please let me know.

**Comment by denmapanter001** [comment]
For example,Lossy audio codecs(mp3,aac,oups,,,)
On Win10 with WASAPI and Sound Card 24bit 192hz

If Exclusive mode
[MPV]
floatp > s32
[MPC-BE's audio render]
16bit integer >16bit integer

If Shred mode
[MPV]
floatp > floatp
[MPC-BE's audio render]
16bit integer >32bit float

Because I use for audio files with Foobar2000's ASIO driver
and I hope to use for music video files with MPV's Exclusive mode.
