### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by AlexeyMihaylov** [mpv-player/mpv#7057]
### mpv version and platform
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
Kernel: 5.0.0-31-generic
mpv: 0.26.0

Program crashes with message: "Segmentation fault (core dumped)" . Unfortunately, as far as I understand, it happens before making any logs. However, if it creates any dumps I`m ready to provide them.

![Screenshot from 2019-10-14 23-21-24](https://user-images.githubusercontent.com/56562484/66780760-52be5f80-eeda-11e9-9048-18cbfd135e6b.png)

Here is gdb output, if it can make any use:

alexey@host:~$ gdb mpv
GNU gdb (Ubuntu 8.2.91.20190405-0ubuntu3) 8.2.91.20190405-git
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mpv...
(No debugging symbols found in mpv)
(gdb) run --version
Starting program: /snap/bin/mpv --version
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7d5a700 (LWP 4889)]
[New Thread 0x7ffff7559700 (LWP 4890)]
[New Thread 0x7ffff6d58700 (LWP 4891)]
[New Thread 0x7ffff6557700 (LWP 4892)]
[Detaching after vfork from child process 4893]
[Thread 0x7ffff6557700 (LWP 4892) exited]
[Thread 0x7ffff6d58700 (LWP 4891) exited]
[Thread 0x7ffff7559700 (LWP 4890) exited]
[Thread 0x7ffff7d5a700 (LWP 4889) exited]
process 4885 is executing new program: /snap/core/7917/usr/bin/snap
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7d5a700 (LWP 4895)]
[New Thread 0x7ffff7559700 (LWP 4896)]
[New Thread 0x7ffff6d58700 (LWP 4897)]
[New Thread 0x7ffff6557700 (LWP 4898)]
[Detaching after vfork from child process 4899]
[Detaching after vfork from child process 4901]
[Thread 0x7ffff6557700 (LWP 4898) exited]
[Thread 0x7ffff6d58700 (LWP 4897) exited]
[Thread 0x7ffff7559700 (LWP 4896) exited]
[Thread 0x7ffff7d5a700 (LWP 4895) exited]
process 4885 is executing new program: /snap/core/7917/usr/lib/snapd/snap-confine
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
need to run as root or suid
[Inferior 1 (process 4885) exited with code 01]
(gdb)

**Comment by jeeb** [comment]
Yes, that snap is unofficial and old. Even the [packaged version](https://packages.ubuntu.com/disco/mpv) in 19.04 is newer than that.

**Comment by AlexeyMihaylov** [comment]
> Yes, that snap is unofficial and old. Even the [packaged version](https://packages.ubuntu.com/disco/mpv) in 19.04 is newer than that.

Removed snap version. Installed packaged one (0.29.1) . Works fine.
