### ISSUE TITLE
mpv closes itself when I'm trying to resize window or exit from full-screen [windows]

### ISSUE THREAD

**Issue by runo280** [mpv-player/mpv#7059]
### Reproduction steps
Most of the time when I do one of these actions mpv closes itself:

- Double click to full screen and then double click to exit from full screen
- Try to resize the mpv window size

I tried many versions (from [here](https://mpv.srsfckn.biz/) or [here](https://sourceforge.net/projects/mpv-player-windows/files)), all have this issue for me.

### Log file
https://0x0.st/zxxi.txt

**Comment by CounterPillow** [comment]
```
[   6.708][v][cplayer] Set property: fullscreen -> 1
[   6.708][d][cplayer] Run command: quit, flags=73, args=[4]
```

what are your keybinds?

**Comment by runo280** [comment]
Keybinds 🤔 How should I found this? I didn't change anything.

Another thing, resizing window always cause this issue.
Toggling full screen using keyboard shortcut [F] is fine always, but toggling it using mouse double click some times cause this.

**Comment by runo280** [comment]
There is no input.conf for mpv, I added it from mplayer and mpv.net, but the issue is still there:

#### mplayer:
- input.conf https://0x0.st/zxg-.conf
- log https://0x0.st/zxgH.txt

#### mpv.net:
- input.conf https://0x0.st/zxYh.conf
- log https://0x0.st/zxgi.txt

**Comment by Ckath** [comment]
can you still reproduce the issue with `--no-config` or/and `--no-load-scripts`? it might also be coming from your scripts since I see a bunch of
```
[   0.014][d][cplayer] shift+mbtn_left script-binding osc/__keybinding4
[   0.014][d][cplayer] mbtn_right script-binding osc/__keybinding5
[   0.014][d][cplayer] mbtn_mid script-binding osc/__keybinding6
[   0.014][d][cplayer] wheel_up script-binding osc/__keybinding7
[   0.014][d][cplayer] wheel_down script-binding osc/__keybinding8
```
in your first log

**Comment by CounterPillow** [comment]
Also, please don't add random input.conf from other projects. That's dumb.

**Comment by runo280** [comment]
Still exiting `.\mpv.exe --log-file=output.txt --no-config --no-load-scripts VIDEO_PATH`

Toggle full screen using mouse double click : https://0x0.st/zxlQ.txt

Resize window : https://0x0.st/zxlj.txt

**Comment by morphogo** [comment]
Does `--no-osc` change anything ?

**Comment by runo280** [comment]
> 
> 
> Does `--no-osc` change anything ?

Nope ☹

**Comment by Dudemanguy** [comment]
Ancient issue that appears to be a configuration error.
