### ISSUE TITLE
Linux: GTX 1060/GPU driver is not capable of outputting 4K 60fps video at locked power save mode

### ISSUE THREAD

**Issue by birdie-github** [mpv-player/mpv#7067]
### mpv version and platform

Fedora 30 64
mpv 0.29.1
ffmpeg: 4.2.1

CPU: AMD Ryzen 7 3700X
GPU: NVIDIA GTX 1060 6GB with proprietary drivers 440.26 with this xorg.conf option:
```
Option          "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerLevel=0x3; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3"
```

### Reproduction steps

mpv https://www.youtube.com/watch?v=LXb3EKWsInQ or any 4K 60fps video

### Expected behavior

Smooth playback

### Actual behavior

Up to 20 frames lost for each second of the clip.

### Log file

[output.txt.gz](https://github.com/mpv-player/mpv/files/3741319/output.txt.gz)

### Sample files

https://www.youtube.com/watch?v=LXb3EKWsInQ

### Found workarounds

With `-vo vdpau` everything is silky smooth.

**Comment by wm4** [comment]
Your computer is too slow. You could try to enable hw decoding, or just use --vo=vdpau (but which doesn't treat the HDR in this video correctly).

**Comment by CounterPillow** [comment]
Works fine on my mobile intel GPU with the gpu VO and vaapi as hwdec. Try enabling hwdec (do note that 10-bit video won't work right with vdpau, so use nvdec).

If you still get bad performance we can rule out the software decoder, and can start to look into why the VO is being slow. Check for example your GPUs power state while it's trying to draw the video; if it's dropping frames on the VO side while the GPU is at low power then something's seriously wrong.

**Comment by wm4** [comment]
Indeed, if I set my AMD GPU into the lowest state, it's not real time, but with unrestricted power it is. (I have a worse CPU btw., but hwdec might still help with the CPU->GPU copy.)

**Comment by birdie-github** [comment]
> Your computer is too slow. You could try to enable hw decoding, or just use --vo=vdpau (but which doesn't treat the HDR in this video correctly).

With `-vo=vdpau` everything is fine. Also, I have less than 10% CPU load across all cores (over 150% combined but it doesn't matter).

**Comment by birdie-github** [comment]
> Check for example your GPUs power state while it's trying to draw the video; if it's dropping frames on the VO side while the GPU is at low power then something's seriously wrong.

I have my GPU pegged to the lowest power state by using this option:

```
Option          "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerLevel=0x3; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3"
```

but I presumed that GTX 1060 even at this mode is more than capable of simply outputting 4K frames. I will try without it and will let you know.

**Comment by birdie-github** [comment]
> Works fine on my mobile intel GPU with the gpu VO and vaapi as hwdec. Try enabling hwdec (do note that 10-bit video won't work right with vdpau, so use nvdec).

BTW in drivers 440.26 NVIDIA added the support for hardware decoding of VP9 but it looks like something is missing on my system and hw decoding doesn't work.

Oh, wait, I've just understood what's missing. My version of libvdpau doesn't support VP9 - it's only possible using master: https://gitlab.freedesktop.org/vdpau/libvdpau/commit/4475d106fdd00d74ac84c78691b13db7bd323a8c

**Comment by sfan5** [comment]
> Frame Timings:
> (last/average/peak  μs)
> 11659 / 13029 / 24437 

It's obvious that it would drop frames with these timings.

Works on my machine (with worse specs).
Did you test mpv git? The non-beta NVIDIA driver?

**Comment by birdie-github** [comment]
OK, without this option everything works as intended however GPU consumes around **29W** instead of using just **9W** with `-vo=vdpau` and hard power save mode.

I've now have two questions:

1) I'm not a programmer but I presume that sending static video frames to the GPU to output on the screen shouldn't be such a taxing task, no? Why does it require so much GPU power? Are there any ways to optimize the GPU/OpenGL output driver in mpv? Have there been any commits past 0.29.1 to improve OpenGL output in mpv?

2) Are there any pitfalls to using `vo=vdpau` by default? I'm not persuaded by the GPU driver since it consumes over three times as much power as the vdpau driver.

**Comment by birdie-github** [comment]
> Works on my machine (with worse specs).

Try using:
```
Option          "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerLevel=0x3; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3"
```
:-)

(for this option to take effect it requires either a full reboot, or shutting down the X.org server and reloading nvidia kernel modules).

**Comment by philipl** [comment]
This kind of stream is an HDR stream, which `vo=vdpau` doesn't support (your colours will be all washed out) and `hwdec=vdpau` doesn't work for 10bit content (if you updated your lib, and patched ffmpeg, you'd still not get supported because it's 8bit only).

The only way to fully accelerate this playback and display it correctly is to use `hwdec=nvdec` and `vo=gpu` and deal with the power level you get. There may be intermediate power levels you can force between the one you are forcing today and the one it wants to use - that might let you conserve a little bit more power.

**Comment by birdie-github** [comment]
> This kind of stream is an HDR stream, which vo=vdpau doesn't support (your colours will be all washed out) 

I've noticed that - looks like using vo=vdpau by default is not a viable option :-(

> The only way to fully accelerate this playback and display it correctly is to use hwdec=nvdec and vo=gpu and deal with the power level you get. There may be intermediate power levels you can force between the one you are forcing today and the one it wants to use - that might let you conserve a little bit more power.

I'm currently totally OK with this video being decoded by my CPU only. What this bug is about is the power consumption/requirements to **render** it on my GPU. I think they are a little bit exaggerated.

**Comment by CounterPillow** [comment]
>I'm not a programmer but I presume that sending static video frames to the GPU to output on the screen shouldn't be such a taxing task, no?

It needs to run a full shading pipeline to actually make them look correct. It's not a simple "lol just copy the buffer"

>Are there any ways to optimize the GPU/OpenGL output driver in mpv?

no

>Also I'm almost sure there's no such issue for Windows 10 with the D3D driver (but that has to be tested of course).

Both use the same code, so this is wrong.

**Comment by wm4** [comment]
Regarding why vdpau is faster for you than vp_gpu: this is heavily implementation dependent. On my AMD GPU system, vdpau is actually much slower than vo_gpu (even with hq profile enabled).

Reasons why vdpau is faster/needs less power on nvidia might include any of the following:
- maybe it has dedicated fixed-function hardware
- maybe it interacts with adaptive power management better
- maybe it does significantly less work (since vo_gpu still performs tone mapping and dithering at least)
- maybe the driver implements vdpau via shaders, but they did a much better job at optimization than us

But ultimately, you'd have to ask nvidia.

**Comment by birdie-github** [comment]
@wm4 

Thank you for your comprehensive explanation!

> But ultimately, you'd have to ask nvidia.

I'd be glad to but it's generally near impossible to contact them directly and they chose to reply only to selected threads on [their forums](https://devtalk.nvidia.com/default/board/98/linux/).

**Comment by mc4man** [comment]
Your gpu has very limited support for hwdec of vp9, for slightly? better you'd need a  cheaper (1030/1050) or for better a much newer card (20 series best bet). Decoding capabilities were downgraded for 1060/1070 and some 1080 for some reason..
Don't think vdpau will give you much of anything, nvdec is better though only 8bit. 
(not sure why watching such vids as linked on a regular monitor..
Ex. on 1060
```
$ vdpauinfo
VP9_PROFILE_0                   1 262144  8192  8192
VP9_PROFILE_1                  --- not supported ---
VP9_PROFILE_2                  --- not supported ---
VP9_PROFILE_3                  --- not supported --- ```


$ nvdecinfo
Device 0: GeForce GTX 1060
-----------------------------------------------
Codec | Chroma | Depth | Max Width | Max Height
-----------------------------------------------
MPEG1 |    420 |     8 |      4080 |       4080
MPEG2 |    420 |     8 |      4080 |       4080
MPEG4 |    420 |     8 |      2032 |       2032
  VC1 |    420 |     8 |      2032 |       2032
 H264 |    420 |     8 |      4096 |       4096
MJPEG |    400 |     8 |     32768 |      16384
MJPEG |    420 |     8 |     32768 |      16384
MJPEG |    422 |     8 |     32768 |      16384
MJPEG |    444 |     8 |     32768 |      16384
 HEVC |    420 |     8 |      8192 |       8192
 HEVC |    420 |    10 |      8192 |       8192
 HEVC |    420 |    12 |      8192 |       8192
  VP9 |    420 |     8 |      8192 |       8192 ```
