### ISSUE TITLE
an option for CLI subprocess running and releasing the terminal？

### ISSUE THREAD

**Issue by Justsoos** [mpv-player/mpv#7071]
0.29 mpv 
MacOS 10.13

Searching this issues and mpv.io over and tried `no-terminal` option, `mpv URL` run from shell or by Python `subprocess.run("mpv URL")`, the terminal was still occupied by MPV while running, unless by `mpv URL &` to release the terminal, even that users have to click return key for several times.

**Comment by Akemi** [comment]
works with `--no-terminal` here.

**Comment by Justsoos** [comment]
works?
no ...
![mpv](https://user-images.githubusercontent.com/3480043/67140307-dafe8500-f28b-11e9-9213-aae502235c1b.gif)

**Comment by Akemi** [comment]
tough luck for you, i guess. you ignored the issue template and didn't even try to provide necessary information. like that none is going to help you.

**Comment by Justsoos** [comment]
I am also a developer, so I don't need to do so many tricks. This is not a help to me, but a defect of MPV

**Comment by Justsoos** [comment]
iina, a skin of MPV, already achieved releasing from shell without push enter key for several timeeees, it is some a shame of MPV

**Comment by CounterPillow** [comment]
you didn't even background the process with `&`

**Comment by wm4** [comment]
I have absolutely no idea why you think mpv should "background" itself here. But I don't want to know either, and mpv won't change the behavior. Use the damn shell, it was invented so you can background anything instead of having it to implement in the programs that are being invoked.

**Comment by Akemi** [comment]
![Screenshot 2019-10-19 at 12 39 33](https://user-images.githubusercontent.com/680386/67143623-8f3ce300-f26d-11e9-8273-e0a72929a189.png)

@Justsoos i dunno if anyone ever told you, but your english is incomprehensible. i have a feeling it's impossible to hold a proper conversation with you because of a language barrier.

before anyone here can be helpful, you have to start to be helpful yourself. a start is, not ignoring the issue template, write comprehensible english that is not coming out of ~~google~~baidus's ~~ass~~ translator, and give us all the info needed.

**Comment by Justsoos** [comment]
@CounterPillow 
at least both in Win10 and MacOS, with `&` by shell provides a bad user experience, users need click enter key for several times to escaping. 

@Akemi  
and what ever english you learn, you could also have sth knonw frome GIF-video, it is clear!

**Comment by Justsoos** [comment]
Add description of GIF-video for England-insufficient:
1, before MPV quit by Ctrl-C in terminal or push 'Q' key on MPV, the shell was occupied by MPV process 
2, with '&', user need to click enter key several times to escape to shell prompt
3, both Win 10 and MacOS

**Comment by Akemi** [comment]
can't reproduce, works as intended, and can't deal with this anymore.
