### ISSUE TITLE
request of backbuffer stats

### ISSUE THREAD

**Issue by Justsoos** [mpv-player/mpv#7072]
now MPV only shows cache stats, and backbuffer is also important in network live stream, and backbuffer is not counted in cache stats, it might be a careless mistake.
tests show backbuffer occupies memory too but not counted in cache stats.

**Comment by wm4** [comment]
No idea what a backbuffer is.

**Comment by wm4** [comment]
Oh, that backbuffer. Enough information is exported, and displayed e.g. on page 3 of the stats screen.

**Comment by Justsoos** [comment]
![image](https://user-images.githubusercontent.com/3480043/67128851-82999a00-f22f-11e9-8888-48ea9984af0d.png)
