### ISSUE TITLE
Using LUA, can I check if ytdl hook is used and if URL is Youtube?

### ISSUE THREAD

**Issue by Samillion** [mpv-player/mpv#7075]
Trying to create a personal use script to ease my experience a bit, and I apologize if this question is beginner/noob level. I'm still learning.

Basically I want to check if the ytdl hook is used, if yes, is the URL Youtube? A kind of pseudo representation of what I want is this:

```lua
-- First check if YTDL hook is triggered
if ytdl == true
	-- Is it Youtube URL?
	if ytdl url = "youtube.com"
		mp.set_property("ytdl-format", "bestvideo[height<=?480][fps<=?30][vcodec!=?vp9]+bestaudio/best[height<=480]")
		msg.info("Youtube URL. Quality limited to 480p, 30 FPS. No VP9.")
	end
	
	-- Add other ytdl triggered conditions here.
else
	msg.info("The ytdl hook hasn't been triggered")
end
```

So basically the `if ytdl == true` and `if ytdl url = "youtube.com"` are the parts I'm having a hard time figuring out.

I again apologize if this wasn't the appropriate place to ask such question.

**Comment by wm4** [comment]
There's no proper way to detect this currently. ytdl_hook.lua _probably_ did something if `stream-open-filename` is different from `path`. The former property is undocumented, will probably fix that later. What ytdl_hook.lua does is redirecting the web URL to the actual media URL, which is achieved by setting `stream-open-filename`.

**Comment by Samillion** [comment]
Thank you very much for that, I'll definitely look into it.

If anyone's interested, I've created a script to auto change `ytdl-format` for specific domains:
https://github.com/Samillion/mpv-ytdlautoformat/blob/master/ytdlautoformat.lua

Issues: My pattern fails to match `youtu.be` domain.
