### ISSUE TITLE
raw data returned by screenshot_raw doesn't seem to be correct when vf crop filters are in use.

### ISSUE THREAD

**Issue by dfaker** [mpv-player/mpv#7076]
### mpv version and platform

libmpv mpv-dev-x86_64-20191013-git-a85fa2d windows

### Reproduction steps

Calling using https://github.com/jaseg/python-mpv/blob/master/mpv.py - so slightly indirect i'm afraid.

```python
import mpv
player = mpv.MPV(ytdl=True)
player.play('test.mp4')
player.command('vf','set', "crop=in_w-5:in_h-5:0:0")
time.sleep(10)
img = player.screenshot_raw()
```

### Expected behavior
🔲  w and h are reduced by the amount expected that the crop
🔲 returned image data is of a length matching the expected crop
🔲 data returned by screenshot_raw is correctly aligned.

### Actual behavior

✔️ w and h are reduced by the amount expected that the crop
✔️ returned image data is of a length matching the expected crop
❌ data returned by screenshot_raw is correctly aligned.

w and h are correct, and the image data is of the correct length (in_h-5\*in_w-5\*d) but when converting them to an image the image is distorted as if the unfiltered frame width is being used internally (in_h\*in_w\*d)  even though the return value is the correct filtered width and the final data length is truncated at (in_h-5\*in_w-5\*d)

**Comment by dfaker** [comment]
I'd note that images saved by `cmd_screenshot_to_file` don't show this same distortion.

**Comment by wm4** [comment]
You need to use the ``stride`` field instead of width*4 for the byte size of a scanline.
vf_crop works by changing the start pointer and the image size, no data is copied.
So this looks like it's not a bug.

**Comment by dfaker** [comment]
Ah yes that's perfect, thank you, i'll offer a patch to the other project.
