### ISSUE TITLE
[Feature request] Add support for webp screenshots

### ISSUE THREAD

**Issue by XCanG** [mpv-player/mpv#7078]
Add support for mpv taking screenshots in webp format, you can use [libwebp](https://github.com/webmproject/libwebp) for that.

Adjustable parameters I would like to configure for this format:
```
  -q <float> ............. quality factor (0:small..100:big), default=75
  -preset <string> ....... preset setting, one of:
                            default, photo, picture,
                            drawing, icon, text
     -preset must come first, as it overwrites other parameters
  -z <int> ............... activates lossless preset with given
                           level in [0:fast, ..., 9:slowest]

  -m <int> ............... compression method (0=fast, 6=slowest), default=4
  -size <int> ............ target size (in bytes)

  -f <int> ............... filter strength (0=off..100), default=60
  -sharpness <int> ....... filter sharpness (0:most .. 7:least sharp), default=0
  -sharp_yuv ............. use sharper (and slower) RGB->YUV conversion
  -crop <x> <y> <w> <h> .. crop picture with the given rectangle
  -resize <w> <h> ........ resize picture (after any cropping)
  -mt .................... use multi-threading if available
  -noalpha ............... discard any transparency information
  -lossless .............. encode image losslessly, default=off
```
May be add variable like `screenshot-webp-custom-parameters` would be nice idea. E.g.: `screenshot-webp-custom-parameters=-f 50 -sharp_yuv -noalpha`

A few examples on command for anime screenshot:
```
cwebp -preset drawing -m 6 -mt -strong -q 80 -af -sharpness 0 -sharp_yuv -noalpha -o 01.webp -- 01.png
cwebp -preset drawing -m 6 -mt -strong -f 50 -sharp_yuv -noalpha -o 01.webp -- 01.png
```

**Comment by LaserEyess** [comment]
You need to update mpv, webp has been supported as of this commit https://github.com/mpv-player/mpv/pull/6832

As for the filtering, you should be able to apply arbitrary `--vf` to do whatever you need.

**Comment by wm4** [comment]
if these filtering options refer to codec-internals, they might have to be exposed.

**Comment by XCanG** [comment]
Ok, sorry for not checking Pull requests, I just didn't find that option in [manual](https://mpv.io/manual/stable/#screenshot), so I don't think it was already supported, but it is possible to add parameters for control filter strength and sharpness? It would significantly help for anime screenshots without bumping up quality and file size.

**Comment by LaserEyess** [comment]
You were looking at the wrong manual, that's for stable, this is master: https://mpv.io/manual/master/#options-screenshot-format

Also, I don't know why you're taking filtered screenshots to reduce filesize, that doesn't really make sense and webp lossy has pretty good compression. If you're trying to show what the video looks like then using lossy, filtered images is pretty disingenuous. If you're just trying to store them for personal use then the webp defaults have the best quality/compression ratio.

That being said, mpv has a [sharpen filter](https://mpv.io/manual/master/#options-sharpen) as well as [arbitrary filtering](https://mpv.io/manual/master/#video-filters-vf) via libavfilter. So for now if you need to filter screenshots that's definitely possible.
