### ISSUE TITLE
switching workplaces on Sway causes extreme vsync jitter with OpenGL

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#7079]
Discussed in https://github.com/mpv-player/mpv/pull/6988

### mpv version and platform
mpv 027ca4fb855f3dff4cba1c907c92c509b82e6fe8
Linux Wayland
most recent sway/wlroots git-master to date

### Reproduction steps
Play a video in a Sway Wayland session with `--gpu-api=opengl` and `--video-sync=display-resample`. While playback is running, switch to a different workspace of Sway and back.

### Expected behavior
Playback should continue normally after switching back. It does so when using `--gpu-api=vulkan`.

### Actual behavior
There is stutter caused by extreme vsync jitter, recovering from it takes several seconds.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/3748111/output.txt)

**Comment by Dudemanguy** [comment]
Well this is embarrassing. I must have accidentally part of the commit that actually adds presentation time to vulkan (it's not actually using it). The problem is fortunately simple and an oversight on my part. Oops.
