### ISSUE TITLE
lua scripts not working correctly

### ISSUE THREAD

**Issue by grill05** [mpv-player/mpv#7083]
### mpv version and platform
mpv 0.29.0-UNKNOWN Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Oct 19 21:31:20 +0630 2019
ffmpeg library versions:
   libavutil       56.35.101
   libavcodec      58.59.102
   libavformat     58.33.100
   libswscale      5.6.100
   libavfilter     7.63.100
   libswresample   3.6.100
ffmpeg version: 4.2.git

### Reproduction steps
try this lua script (adapted from https://gist.github.com/ekisu/04924e899648e84f2e18)
```
local utils = require 'mp.utils'
if mp.get_property_bool("option-info/vo/set-from-commandline") == true then
    return
end
t = {}
t.args = {"/bin/cat", "/sys/class/power_supply/ACAD/online"}
res = utils.subprocess(t)
if res.stdout ~= "1\n" then
    mp.msg.info("On battery, setting low-quality options.")
    mp.set_property("options/scale", 'ginseng')
    mp.set_property("options/glsl-shaders", '')
end
```
### Expected behavior
Lua script should only print the info message based on file value (battery status) of /sys/class/power_supply/ACAD/online

### Actual behavior
The script will always print the info message, irrespective of whether the file is 0 or 1. It seems file value (/sys/class/power_supply/ACAD/online) is not being read by the lua script

#### Log files
running with --msg-level=all=v, shows this
```
[cplayer] Waiting for scripts...                  
[stats] script-opts/stats.conf not found.                                           
[stats] lua-settings/stats.conf not found.                                      
[ytdl_hook] script-opts/ytdl_hook.conf not found.         
[ytdl_hook] lua-settings/ytdl_hook.conf not found.                                              
[change_on_battery] On battery, setting low-quality options.
```

**Comment by TheAMM** [comment]
The problem lies with your code, not with mpv.
Consider not using a subprocess to read the file (lol), check the actual value read (you seem to be expecting something else but don't tell what and blame it on mpv?) and convert it to a number to be safe, (you'll avoid the newline hassle).

**Comment by CounterPillow** [comment]
Pro tip:
```lua
function get_sys_value(variable)
    local f = assert(io.open(variable, "r"))
    local val = string.gsub(f:read("*all"), "\n", "")
    f:close()
    return val
end
```

**Comment by grill05** [comment]
@CounterPillow thanks. I used you code with `get_sys_value("/sys/class/power_supply/ACAD/online")` , and now battery status (that file's value) is checked correctly.
