### ISSUE TITLE
Random stutter/low fps when playing HDMI inputs (or when changing HDMI). "Invalid video timestamp: 0.000000 -> 0.000000"

### ISSUE THREAD

**Issue by sirisian** [mpv-player/mpv#7086]
Tested with latest release. (Using the mpv dll). Also I've tested with older releases a few months ago and it still happens.

### Reproduction steps
Connect an Atmosphere device, Apple TV, computer HDMI source, cable box, really anything. (I've tested this with everything I have available and it seems easy to reproduce). Run MPV player a few times until it stutters/renders low fps (it looks like half the fps?). I'd say about 80% of the time it plays fine with no outputted problems and the video stream is smooth. This is using a Blackmagic Intensity Pro 4K input device and mpv.js (to display the stream in Chrome which I don't think has anything to do with this).

While just restarting mpv randomly reproduces it I've noticed if you just pull the HDMI cable out and put it back in it'll reproduce randomly also.

Basic Settings:
```
set_property_string 'demuxer', 'lavf'
set_property_string 'demuxer-lavf-o', 'video_size=1920x1080:pixel_format=yuv422:framerate=59.94:rtbufsize=702000k'
loadfile 'av://dshow:video=Decklink Video Capture:audio=Decklink Audio Capture'
```
I've tried playing with the following and didn't see any changes:
```
fflags=+genpts:fflags=+igndts:use_wallclock_as_timestamps=1
```
Also tried pixel format 'yuv422p' randomly which doesn't do anything different. (Not sure what that is. Saw it mentioned online).

### Expected behavior

Consistent fps.

### Actual behavior

Random low fps playback. When it happens it starts right when mpv player starts and never goes away. When it doesn't happen it's smooth forever and can play for days with no issues.

It's like it starts in an odd state or maybe reads something wrong (like the timestamp) and this changes the fps or something with the playback maybe?

### Log file

Using log level "v" it outputs JSON (over the IPC socket connection) either:

```
{"event":"log-message","prefix":"cplayer","level":"warn","text":"Invalid video timestamp: 0.000000 -> 0.000000\n"}
```
or
```
{"event":"log-message","prefix":"cplayer","level":"warn","text":"Invalid video timestamp: -0.000000 -> -0.000000\n"}
```

This displays many times over and over when the stuttering/low fps happens.

For anyone else that gets this I've realized I could probably just parse the incoming JSON logs, detect "Invalid video timestamp" then restart mpv as a quick fix. Obviously not ideal.

**Comment by wm4** [comment]
Why do you think the message is related to the problem?
Make a log file by setting the log-file option.

**Comment by sirisian** [comment]
> Why do you think the message is related to the problem?

It's the only thing output from the logs that changes when it's in the low fps state.

> Make a log file by setting the log-file option.

I downloaded the latest mpv player and ran:

```
mpv.exe --log-file=logs.txt -v --demuxer "lavf" --demuxer-lavf-o "video_size=1920x1080:pixel_format=uyvy422:framerate=59.94:rtbufsize=702000k" "av://dshow:video=Decklink Video Capture:audio=Decklink Audio Capture"
```
On the third time running it I saw the low fps and captured this log:
[stutteringfulllogs.txt](https://github.com/mpv-player/mpv/files/3773621/stutteringfulllogs.txt)

**Comment by wm4** [comment]
Not sure to be honest. If this is a "live" stream, using --untimed might be better anyway. Except that won't work with audio, but you could still try for the sake of debugging.

**Comment by sirisian** [comment]
Woah, yeah that is night and day. untimed works perfectly and the problem went away on all my devices. I'll test more next week. The examples I have setup at the moment all have ambient audio so I can't tell if there are any audio issues. I assume you mean the audio is desynced with the video.

**Comment by sirisian** [comment]
I'm going to close this as untimed seemed to have solved all my issues and I don't notice any audio issues.

**Comment by wm4** [comment]
I don't remember the details about how A/V sync works. This might become a problem in the long run. --untimed is not really intended to be used "in production", at least if audio is enabled.

**Comment by sirisian** [comment]
You were right by the way. untimed does not play with rtp and rtsp streams well at all. I to had to toggle it based on capture card vs rtp/rtsp.
