### ISSUE TITLE
Windows 0.30.0 build?

### ISSUE THREAD

**Issue by Doofussy2** [mpv-player/mpv#7088]
Will there be an official Windows build? I see the new release by sfan5, but there is no Windows build from @lachs0r. Sorry for asking in this manner.

**Comment by Akemi** [comment]
they are not really official. i think @lachs0r said he would stop supporting windows at some point? so you might not see another release build from him.

**Comment by Doofussy2** [comment]
Thanks @akemi. I hope Windows continues to be supported. You guys have a great piece of software.

**Comment by NotTsunami** [comment]
See https://github.com/shinchiro/mpv-winbuild-cmake

**Comment by wm4** [comment]
If lachs0r stops doing builds, we should probably remove the link from the website.
