### ISSUE TITLE
Resolved: release the tty from MPV's occupation

### ISSUE THREAD

**Issue by Justsoos** [mpv-player/mpv#7092]
Issues post: https://github.com/mpv-player/mpv/issues/7071
1. enable the switch on your mpv config, mine is `~/.config/mpv/mpv.conf`
```
no-terminal
```
2. set up a wrapper script file at your will, like ~/bin/mpv.sh:
```
#!/bin/bash

URI=$@
/Applications/mpv.app/Contents/MacOS/mpv $URI
```
> /Applications/mpv.app/Contents/MacOS/mpv

is my mpv install place, change it with yours

3. set `chmod +x mpv.sh` and delete the original mpv link, and link mpv.sh to your system path:
```
$ln -s /User/USER/bin/mpv.sh /usr/local/bin/mpv 
```

Well, with such a chore, MPV is finally no longer taking up your tty while running or exiting.
including calls from python

**Comment by Justsoos** [comment]
BTW, the official solution is setting the `no terminal` and run mpv calling with end `&`, it does not work.

**Comment by Akemi** [comment]
it still works as intended without the wrapper script for me, eg using `&` works without hitting enter once. you are still ignoring the issue template and you still didn't provide any kind of useful information.

**Comment by Justsoos** [comment]
**This is left to other victims on the Internet who cannot find a solution and are ignored by the authorities of MPV.

If you're still serious about the problem, fix it, not block it**

**Comment by CounterPillow** [comment]
fuck off already

**Comment by Justsoos** [comment]
> CounterPillow: fuck off already

leave to Internet memory, your ass hole face

**Comment by Akemi** [comment]
how do we ignore you? i asked you a few times, very politely, to give us more information about how to reproduce your problem, because no one can reproduce it. it's either an edge case or you are doing something wrong.

but instead of you being helpful, you completely ignore the issue template and refuse to give helpful informations. first of all you should work on your attitude instead of blaming us for being uncooperative.

**Comment by Justsoos** [comment]
@akemi Thanks for your patient reply, this is a tty and father-son process issue, which was resolved by wrapped child calling, It's not something big enough for you to study.

and if you do not thnik it is a bug, yes, clicking Return key several times could save the tty token up by MPV and it's father process.

Is it so necessary to abuse by English? what a manner!?

**Comment by Akemi** [comment]
i still think there is some kind of language barrier or something.

i never said it's not a bug. i am saying no one can reproduce it besides you atm. it works on my end. doing it your way, look at this screen recording: https://0x0.st/zYqC.mov there is no need to hit the return key several times.

we can't do anything more without proper reproduction steps and the things asked for in th eissue template.

**Comment by wm4** [comment]
What this person really wants is apparently OSX's ``open`` program, which is supposed to run GUI programs in a detached way. Not sure why he's not using that.

This won't lead to anything, so I'll lock it.
