### ISSUE TITLE
Annotating audios and videos

### ISSUE THREAD

**Issue by jcguu95** [mpv-player/mpv#7094]
This is a feature request. I wonder if `mpv` is close to be versatile. It is fast, light-weight, and so wonderful that I can't even imagine living without it! A feature that I've always been dreaming is to annotate audios and videos with `mpv` smoothly.

Currently, `mpv` can mark and jump to some specific time in a file. By annotating a file with `mpv`, I actually mean to annotate with respect to the time-mark. This way, it will be much easier to take notes and review! I imagine it won't be too hard to enhance `mpv` so that it will read a meta-file along with the file:

```
./ep5-integration.mp3
./.ep5-integration.mp3.mpv_meta
```
where `.mpv_meta` is a plain text file that looks like the following

```
file="ep5-integration.mp3"
md5sum="9e3303146ea19e6682b605cad3990681"
length=00:03:12
other-meta-data="..."

timestamps={
[00:01:00], "Professor stressed the importance of fundamental theorem of calculus!"
[00:02:52], ".. did not really understand this point.. listen to this again"
}
```
and there will be a way to navigate from timestamp to timestamp with a convenient view of the annotations! This should work both with audios and videos, and I expect this to largely enhance the efficiency of absorbing information from a audio/video file. 

Alas, I am still pretty new to programming, and am not sure if this dream is actually implementable. Is there a plan about this already for developing `mpv`? Or is this something that is just not that important to other people? If I would like to contribute to this feature, are there any suggestions? Thank you!

**Comment by wm4** [comment]
The standard suggestion would be that someone (not me, but preferably the one who requested this feature) implements this as lua script.

**Comment by paulguy** [comment]
I dunno about doing it within mpv but you can write out a subtitle file and use CTRL+left and CTRL+right to seek to the previous or next subtitle. Subtitle files are generally pretty human-readable and there's stuff like aegisub which have a lot of very useful tools for writing subtitles.

**Comment by Dudemanguy** [comment]
As said above, doing this within mpv is not appropriate. This is something for a lua script.
