### ISSUE TITLE
Using display-resample, mpv doesn't attempt to re-sync large AV desync

### ISSUE THREAD

**Issue by ixxbxxx** [mpv-player/mpv#7095]
### mpv version and platform

Windows 10 latest Shinchiro build

### Reproduction steps

video-sync=display-resample
framedrop=decoder

1. stress the decoder e.g. increase playrate to 8x
2. reset playrate to something the system can handle e.g. 1x

### Expected behavior

1. A-V value will increase to some absurb number e.g. 10 secs as decoder can't keep up with requested playrate
2. A-V goes back to 0 (i.e. audio-video syncs)

### Actual behavior

1. A-V value will increase to some absurb number e.g. 10 secs
2. A-V doesn't go back towards 0 instead will remain constant at last value i.e. 10

Using video-sync=display-resample-vdrop, same behaviour as above.

Using framedrop=vo, what instead happens is that at step 1, the video output freezes and at step 2, remains frozen (with sound playing in the background)

### Log file

https://pastebin.com/LW6BT4KP

**Comment by wm4** [comment]
Works here.

**Comment by ixxbxxx** [comment]
I've attached a log file for your perusal. Essentially what is happening is that the desync value ('A-V') doesn't go back to 0 when the playrate goes back to 1x (or any rate that the decoder can handle) i.e. there will be a constant offset between A-V.

**Comment by wm4** [comment]
According to your log, display-resample isn't enabled.

**Comment by ixxbxxx** [comment]
Thanks - how do i tell if display-resample is enabled? I see this in the log when the file starts playing back at default playrate:
Change display sync audio drift: 1

And it changes to -1 when the playrate is increased/desync occurs.

All this while I am assuming display-resample is activated when Vsync Ratio and Jitter is displayed on the OSD which doesn't appear if video-sync=audio is used. In the past, if there is massive desync, display-resample reverts to audio and the Vsync Ratio/Jitter disappears from OSD however after you had removed this hack recently, I see Vsync Ratio/Jitter remain on the OSD despite massive desync.

**Comment by wm4** [comment]
Your log doesn't set these options, but it's correct that the log line you point out happens only with display-resample, and it appears in that log. Either you edited the log, or there's some bug with --log-file discarding output, or I'm missing something.

**Comment by ixxbxxx** [comment]
Nope I pasted it wholesale, no edits. I've generated a fresh log, again pasted wholesale.

https://pastebin.com/FyhaZq7m

**Comment by wm4** [comment]
Normally it logs the options that are set, why doesn't it do that for you? The log is useless this way.
Anyway, if you really set framedrop=decoder, it's perfectly clear why this happens. It can't drop frames correctly, so it can't catch up.

**Comment by ixxbxxx** [comment]
> Normally it logs the options that are set, why doesn't it do that for you? The log is useless this way.
> Anyway, if you really set framedrop=decoder, it's perfectly clear why this happens. It can't drop frames correctly, so it can't catch up.

Even if frames can't be dropped, using video-sync=display-resample  shouldn't the expected behaviour be that audio speed be adjusted to compensate/sync?

**Comment by wm4** [comment]
Audio and video speed is only changed up to the configured threshold. Disabling VO framedropping in addition does what it says and stops dropping these frames to catch up. Decoder framedrop mode has issues, and not all frames can be dropped anyway. If decoding is too slow, it will simply not catch up. (There are ways it could resume anyway, such as hard packet dropping or seeking, but it wouldn't be pretty.)

**Comment by ixxbxxx** [comment]
@wm4 Thank you okk let's assume no framedropping by vo or decoder (framedrop=no), when there's a large desync, I would assume the expected behaviour for video-sync=display-resample is to slow down audio until sync is achieved again. However this is not the case regardless how large the threshold (video-sync-max-audio-change) I set. It therefore appears to me that even if video-sync=display-resample, audio still doesn't sync to video as expected but instead plays to specified playrate. Is this behaviour what you intended or am I understanding this wrongly?

**Comment by wm4** [comment]
I don't quite remember; I think the audio resample ratio is computed from the "ideal" rate computed from video and display FPS, not A/V desync.

**Comment by ixxbxxx** [comment]
Is it therefore possible to force audio playrate to adjust to vo throughput? A use case here is for users like me using playrate to fast forward instead of seeking so for example i 'fast-forward' via playrate 8x however for example the video decoder/output throughput is only say 6x for a specific video resulting in a hugh desync (framedropping=no) so the smart fix here will be to automatically reduce audio playrate to 6x instead of the specified 8x playrate. Dropping frames here is not ideal because it stutters to much it might as well be seeking instead. Your thoughts?

**Comment by wm4** [comment]
If the decoder is too slow to deliver the requested rate, you're out of luck, it simply doesn't handle this. This has nothing to do with display-resync either. mpv could be extended to do one of the following:
- hard-drop incoming video data until the next resume point ("keyframe")
- pause playback until video has caught up
- issue a seek (essentially like a mix of the above two)
- slow down audio playback to give video time to catch up

But currently none of this is done.

**Comment by ixxbxxx** [comment]
> slow down audio playback to give video time to catch up

I think this would be a good feature to have as in addition to my use case (playrate as fast forward), also consider users with systems that are too slow to play a certain file - it would be good to have the option of either playing it with choppy video (framedropping to retain 1x playrate) or a 2nd option which is to play it at the system's best throughput smoothly at a dynamic playrate (when throughput is less than 1x) via slowing down audio with framedropping=no.
