### ISSUE TITLE
OSC breaks on vertical videos since latest commit

### ISSUE THREAD

**Issue by Kattus** [mpv-player/mpv#7098]
### mpv version and platform
mpv 0.30.0-34-g00c9a6c237 on Arch Linux

### Reproduction steps
1. Compile and run commit 00c9a6c237e445469df8daeb455669e80b756749
2. Play vertical video
3. See OSC being placed in the middle of the video

### Expected behavior
The OSC not being placed in the middle of the video.

### Actual behavior
The OSC being placed in the middle of the screen.

### Log file
https://0x0.st/zY2s.txt

### Sample files
https://0x0.st/zY2z.mp4

**Comment by Akemi** [comment]
pinging @medhefgo
