### ISSUE TITLE
MPV does not play certain wav files

### ISSUE THREAD

**Issue by parkmino** [mpv-player/mpv#7099]
### mpv version and platform
git-2019-10-26-8e50d7a

### Reproduction steps
Play the attached wav file.
### Actual behavior
Noise and stop
### Sample files
Attached.
[Error Wav.wav.zip](https://github.com/mpv-player/mpv/files/3781627/Error.Wav.wav.zip)

**Comment by Akemi** [comment]
log file please.

**Comment by CounterPillow** [comment]
Looks like FFmpeg for some reason misdetects this as 32000 Hz MPEG-1 audio, when it is in actuality 32-bit float 44100 Hz wav.

It does use the correct demuxer, but then chooses the wrong format.

@richardpl any thoughts?

**Comment by richardpl** [comment]
mp1 is picked beacuse of extra probing in case of pcm_s16 codec. Somehow start of audio looks like mp1. Need fixing mp1 probing.

**Comment by Kattus** [comment]
The same happens with ffplay, so isn't this ffmpeg's problem?

**Comment by wm4** [comment]
If only we had kept mplayer's wav demuxer.

**Comment by CounterPillow** [comment]
>The same happens with ffplay, so isn't this ffmpeg's problem?

It is, so someone should report this upstream and if they're feeling even more generous, write a patch to fix it.

**Comment by richardpl** [comment]
This have been fixed in FFmpeg commit c22665ae691ca313793330bfa7c9a2b70d53cbdf
