### ISSUE TITLE
python-mpv: Non-C locale detected. This is not supported.

### ISSUE THREAD

**Issue by marioortizmanero** [mpv-player/mpv#7102]
### mpv version and platform
```
❯ mpv --version
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Oct 26 19:32:35 UTC 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.1
```

```
❯ uname -a
Linux glowarch 5.3.7-arch1-2-ARCH #1 SMP PREEMPT @1572002934 x86_64 GNU/Linux
```

### Reproduction steps

Warning: this code snippet is haunted because it makes no sense at all:

Run `python -m unittest test_haunted` after saving the snippet in a file named `test_haunted.py`. You'll need PySide2 installed.

```python
import os
import unittest

import PySide2.QtWidgets
from mpv import MPV


class HauntedTest(unittest.TestCase):
    def setUp(self):
        super().setUp()

        # Creating the first app instance
        print("Qt")
        self.app = PySide2.QtWidgets.QApplication()

        print("Mpv")
        self.mpv = MPV()

    def test_wtf(self):
        print("In test")


if __name__ == '__main__':
    unittest.main()

```

### Actual behavior

Output:

```
Qt
Mpv
Non-C locale detected. This is not supported.
Call 'setlocale(LC_NUMERIC, "C");' in your code.
zsh: segmentation fault (core dumped)  python3 -m unittest test_haunted
```

Fun stuff:

* If you remove the PySide2 part, it doesn't crash
* If you remove the Mpv part, it doesn't crash

### Log file

I can't even log it because `self.mpv = MPV("--log-file=output.txt -v")` doesn't create any files nor print anything else.

**Comment by wm4** [comment]
Qt changes the locale, and libmpv does not support this. See: https://github.com/mpv-player/mpv-examples/blob/master/libmpv/qt/qtexample.cpp#L217
This cannot be solved, unless Qt stops doing stupid things like this, or mpv ships its own C standard library.

**Comment by marioortizmanero** [comment]
Should I post this on the PySide forums @wm4?

**Comment by kodosexe** [comment]
Hey, is there any update on this? You'd think someone had found a workaround by now..
