### ISSUE TITLE
is there any hardware accelerated optimization swith except "hwdec"?? high CPU, low GPU usage!

### ISSUE THREAD

**Issue by Justsoos** [mpv-player/mpv#7103]
play the same stream, compare with IINA, MPV's CPU usage and GPU usage are all worse. MPV‘s CPU usage also becomes unstable over time.

already set "hwdec on" in mpv.conf.

![image](https://user-images.githubusercontent.com/3480043/67834881-87a9f380-fb23-11e9-90ac-d9fde2f068e3.png)

![image](https://user-images.githubusercontent.com/3480043/67834887-8c6ea780-fb23-11e9-84fb-3bce4a391dda.png)

https://github.com/Justsoos/mpv/issues/2
https://github.com/mpv-player/mpv/issues/7061

**Comment by Dudemanguy** [comment]
>already set "hwdec on" in mpv.conf.

"on" is not a valid value for hwdec nor is "hwdec on" proper syntax. Please read the manual. It explains how to properly set options in your config file. Also don't ignore the template when making issues.

**Comment by Justsoos** [comment]
what a funny thing!
the English "set "hwdec on"" means exactly what I write in `mpv.conf`????

your MPV member so funny develop community members, someone can not read English, someone abuse dirty words, and all of you do close issues.

**Comment by Tsubajashi** [comment]
"Hwdec on" is still not correct. Its either "hwdec=yes" or "hwdec=auto" or "hwdec=auto-copy". Its in the Documentation. Its not their fault if you cant Follow guidelines how to use something.

**Comment by wm4** [comment]
"set hwdec auto" might be valid syntax when run as command (e.g. input.conf), but not in a config file (like mpv.conf) or on the command line.

The worst about this is that we even have a default key binding to enable hw decoding at runtime (ctrl+h).

Anyway, blocked him from the mpv org. He behaves like a bad troll, and dealing with him is exhausting.
