### ISSUE TITLE
temporary garbled window content when resizing due to unflushed VRAM content

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#7105]
Not really a bug report, rather a cosmetic suggestion:
The RadeonSI driver doesn't flush previous window content which causes ugly artifacts for a brief moment when resizing.
As a workaround, mpv can be started with `AMD_DEBUG=zerovram`. Though it'd be more elegant if mpv flushed content of previous frames by itself in such cases.

Otherwise we should suggest to add mpv to the compatibility workaround list of Mesa to enable flushing by default there.

**Comment by wm4** [comment]
Yeah, I noticed this, e.g. on startup. It happens with EGL, but didn't happen with GLX.
Is it even possible for the application to fix this? VRAM doesn't exist.

**Comment by aufkrawall** [comment]
It'd be weird if not (but dunno), as afaik the driver behaves that way to strictly meet the OGL spec.
Though lots of applications show these artifacts with window operations.

As mpv often isn't started via XDG .desktop entry, one can also set this up in e.g. `~.drirc`
```
<driconf>   <device driver="radeonsi">
    <application name="mpv" executable="mpv">
        <option name="radeonsi_zerovram" value="true">
    </application>
</driconf>
```

**Comment by wm4** [comment]
The OGL spec. doesn't mention "vram" and doesn't deal with X11.
Isn't this more of a X11 thing, where window contents remain undefined if the application doesn't redraw quickly enough?
Do you have anything informed to say, or are you just guessing? (Not that I'm not guessing either.)

**Comment by wm4** [comment]
That seems very unlikely and I'm just going to say this is not the case, unless someone can disprove it with apitrace.

**Comment by aufkrawall** [comment]
@wm4 It's gone for me when starting mpv, but it still occurs when switching into fullscreen the first few times during playback. The `radeonsi_zerovram` flag "fixes" that as well.
Definitely driver specific, never seen it with Intel i965.

**Comment by wm4** [comment]
At least it removes the startup annoyance.
Any chance you could report this to Mesa? Maybe with API traces before and after this commit.

**Comment by aufkrawall** [comment]
> Any chance you could report this to Mesa? Maybe with API traces before and after this commit.

Likely this weekend.

**Comment by aufkrawall** [comment]
@wm4 mesa report: https://gitlab.freedesktop.org/mesa/mesa/issues/2085

**Comment by wm4** [comment]
Thanks.

**Comment by aufkrawall** [comment]
Seems it is not going anywhere. Perhaps a simple MR to put mpv on that exception list would just do the trick for the time being?
