### ISSUE TITLE
Often starts with low priority

### ISSUE THREAD

**Issue by zoqaeski** [mpv-player/mpv#7107]
### mpv version and platform

0.30.0 on Arch Linux

### Reproduction steps

I'm not sure if this is an mpv bug or something wrong with my configuration, but when starting mpv from the terminal, it often starts with a low priority (niceness value of 5). There's no way to reset the niceness to 0 without using `sudo renice`. In particular, [my `mpvctl` script to control mpv using the JSON-IPC interface](https://gist.github.com/zoqaeski/9a99c87e6ef0811791317a964c67743a) _always_ starts with a low priority, but a plain `mpv <video>` invocation often doesn't.

### Expected behavior

MPV will start with the default 0 niceness regardless of how it's invoked.

### Actual behavior

MPV starts with a low priority sometimes.

### Log file

[Here are the logs](https://gist.github.com/zoqaeski/3d356959d5ae96fb3e7e3101e461141f) from a test run of both `mpv` and `mpvctl` on the same video from Youtube.

### Sample files

The video I used to test this issue was this one: https://www.youtube.com/watch?v=4xcUqagJdpw , but it occurs with any video and the `mpvctl` script I wrote.

**Comment by qmega** [comment]
Put `setopt no_bg_nice` in your script (or startup file). Zsh by default runs background jobs (started with `&` as in your script) with lower priority.
