### ISSUE TITLE
--start and --end ignored in --loop

### ISSUE THREAD

**Issue by giampierosalvi** [mpv-player/mpv#7108]
Hi,
I would like to loop only a segment of a file. I tried with the following command:
```mpv --start=1:45 --end=3:27 --loop=inf file.mp3```
However, the start and end parameters are only used the first time the file is played, from the second time on, the whole file is reproduced.

Is this a bug? Is there a way around it?
Thank you!
Giampiero

### mpv version and platform
mpv 0.27.2 (C) 2000-2017 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       55.78.100
   libavcodec      57.107.100
   libavformat     57.83.100
   libswscale      4.8.100
   libavfilter     6.107.100
   libswresample   2.9.100
ffmpeg version: 3.4.6-0ubuntu0.18.04.1

**Comment by Akemi** [comment]
use `--ab-loop-a and `--ab-loop-b` instead or the lowercase "L" keybinding.

also update your mpv and don't ignore the issue template.
