### ISSUE TITLE
Video plays too fast with video-sync=display-resample on NVIDIA drivers with __GL_SYNC_TO_BLANK=0

### ISSUE THREAD

**Issue by DragoonAethis** [mpv-player/mpv#7110]
### mpv version and platform

- mpv 0.30.0
- Linux (Arch)
- NVIDIA GPU w/ 435.21 proprietary drivers
- Environment variable `__GL_SYNC_TO_VBLANK` set to `0`
- Setting `video-sync` set to `display-resample`

### Reproduction steps

Play any video file on a Linux box with NVIDIA GPU and 435.21 drivers: `__GL_SYNC_TO_VBLANK=0 mpv video.mkv --no-config --video-sync=display-resample`

### Expected behavior

The video plays normally, at the expected speed, A/V synchronized.

### Actual behavior

Video plays ridiculously fast (probably as fast as mpv is able to decode it) instead of waiting for v-blank. Audio plays at the standard speed.

### Log file

- Logs available here: https://0x0.st/zgze.log
- Samples not required, the problem reproduces with any video file.

### Note

I don't really expect this issue to be fixed, but I wanted to document it in case anyone encounters it in the future. Please close it right away if you don't want to do anything with it either.

**Comment by wm4** [comment]
display-resample synchronizes video on vsync, and the environment variable you use disables vsync. So it's not surprising that it doesn't work.

Depending on how quickly video frames are rendered, playback will either be severely degrade in quality, slowly desync, or just explode like in your case.

Nvidia drivers AFAIK do not provide a way to implement this in any other way either. Vsync blocking is required.
