### ISSUE TITLE
save position-on-quit doesn't seem to work in MS-Windows. 

### ISSUE THREAD

**Issue by shirishag75** [mpv-player/mpv#7113]
### mpv version and platform

mpv 0.3.0 x64
Windows 10 x64

### Reproduction steps

Have mpv.conf in C:\Users\generation2\Downloads\mpv-0.30.0-x86_64\portable_config\

The content of the file is - 

```
blend-subtitles=yes
save-position-on-quit
volume=100
volume-max=150
```

### Expected behavior

It should save position on quit. 

### Actual behavior

Wherever I stop the video, the next time I click on the media file, it should start playing from there. Currently, it does not :(
### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

Providing a log file is strongly encouraged. It is very helpful for reproducing
bugs or getting important technical context. Without a log it might not be
possible to analyze and fix certain bugs, and your bug report will be closed
or ignored.

I have no log files. And trying to find how to make one under MS-Windows has not been worthwhile so far :(

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by shirishag75** [comment]
@sfan5 would love to know how to do logging for mpv under MS-Windows. I haven't been able to get any instructions from the wiki. https://github.com/mpv-player/mpv/wiki/

**Comment by sfan5** [comment]
> Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or a similar site, and replace this text with a link to it.

You can do this by running mpv from the Windows Command Prompt.

**Comment by shirishag75** [comment]
@sfan5 thank you, was able to do the same, please see - 

https://paste.debian.net/1113203/

and 

https://paste.debian.net/1113204/

the difference between the two files are just the names of the two log files. As can be seen, in the second example, it reverted the media file to the beginning instead of starting from minute 01:30 seconds where I had left. I had similar experiences with other media files as well of the same behavior.

**Comment by CounterPillow** [comment]
Your log file shows that you didn't actually put "save-position-on-quit" in your config file. Your config file is probably called `mpv.conf.txt` instead of `mpv.conf` because you have known file extensions hidden.

**Comment by shirishag75** [comment]
@CounterPillow you are right, how do I change it to mpv.conf and it should haven't the .txt file bit.

**Comment by CounterPillow** [comment]
Change your windows explorer settings to show known file extensions.

**Comment by shirishag75** [comment]
@CounterPillow done. Now it works as advertised. MS-Windows is still such a mess :(

**Comment by Hrxn** [comment]
Pro Tip: Rename files from within `CMD`, or better, `PowerShell`. 
That way you don't have to change the Explorer view settings.

**Comment by shirishag75** [comment]
> 
> 
> Pro Tip: Rename files from within `CMD`, or better, `PowerShell`.
> That way you don't have to change the Explorer view settings.

didn't know you could do that, how ? I find powershell much more preplexing than plain unix . An example would be nice.

**Comment by Hrxn** [comment]
You can do this in Pwsh for example:
```PowerShell
PS D:\Test\temp> ls


    Directory: D:\Test\temp

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        03.11.2019    18:33              0 mpv.conf.txt

PS D:\Test\temp> ren mpv.conf.txt mpv.conf
PS D:\Test\temp> ls


    Directory: D:\Test\temp

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        03.11.2019    18:33              0 mpv.conf

PS D:\Test\temp>
```

**Comment by shirishag75** [comment]
ah cool, so in some manners, it does resemble linux/unix, although we use `mv`

**Comment by Hrxn** [comment]
Yeah, it has built-in aliases for common commands etc., so that users familiar with Windows `CMD.exe` or Unix feel at home with interactive shell usage.

**Comment by shirishag75** [comment]
@Hrxn let me know if you know of some basic tutorials of for pwsh .  The only thing I have used it is for is for running DOS commands (very few) and of course now using youtube-dl although that took quite sometime to figure out how things work under pwsh. I probably will be in my beloved unix environment in couple of days but still information is power so it never gets wasted.
