### ISSUE TITLE
hwdec video corruption with some videos on Android

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#7115]
### mpv version and platform

`mpv 0.29.0-904-g5d5fdb77e9` (or later)
I have bisected the bug to 5d5fdb7.

### Reproduction steps

1. Play sample file

### Expected behavior

2. Observe no video corruption

### Actual behavior

2. Observe video corruption

### Log file

On the broken commit: https://0x0.st/zgoR.txt
Before the broken commit: https://0x0.st/zgo5.txt

Notably, the `[vd:warn] could not consume packet` messages are gone.

### Sample files

https://0x0.st/zgoh.mkv

**Comment by wm4** [comment]
Hm, I suppose if the decoder exhibits unexpected data flow, this could have broken.
Can you try to trace how the packets were consumed before and after? Try to do it when the lavc calls are made, rather than all the weird mpv layers in between.
