### ISSUE TITLE
VDPAU breakage in 0.30.0 with radeon open source drivers

### ISSUE THREAD

**Issue by mgorny** [mpv-player/mpv#7117]
### mpv version and platform

Confirmed with 0.30.0 and git master. Bisected to 0abe34ed21023b83c7311d85ea317f3af7b5b89c.

I suppose this means I should switch from vdpau to vaapi. However, I think this should be documented better because I couldn't figure it out from RELEASE_NOTES, and mpv doesn't output any errors or warnings. That said, if I pass totally random string to `-hwdec`, it doesn't report errors either.

### Reproduction steps

1. Use open-source radeon drivers.
2. `mpv -vo gpu -hwdec vdpau movie.mkv` on a h264 movie

### Expected behavior

In earlier versions, the movie played smoothly with minimum CPU use (<15% on htop).

### Actual behavior

The CPU use is between 50%-100% on htop, and the playback is shoddy at times.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/3802212/mpv.log)

### Sample files

I've fetched the sample movie from http://www.html5videoplayer.net/html5video/mp4-h-264-video-test/

**Comment by wm4** [comment]
Not a bug, see commit message.

**Comment by mgorny** [comment]
Do you really believe users should read all commit messages when upgrading to a new release? A clear 'I killed vdpau, switch to vaapi' message somewhere in RELEASE_NOTES would be appreciated. Or even better, an error message or a warning when using it.

**Comment by CounterPillow** [comment]
We've already added a note that says hwdec=vdpau requires gpu-context=x11 to the vdpau documentation.

>I killed vdpau, switch to vaapi

we didn't kill vdpau, we just default to EGL now. nvidia killed vdpau.

>Or even better, an error message or a warning when using it.

Had you used hwdec=auto, this wouldn't be an issue for you. During probing for the right hwdec, errors are expected, so adding huge annoying error messages for every failed hwdec would be more confusing to users.

**Comment by CounterPillow** [comment]
Also, this is documented for 0.30 in https://github.com/mpv-player/mpv/blob/master/DOCS/interface-changes.rst

**Comment by wm4** [comment]
In general, users should only use the auto option for --hwdec, everything else is for debugging or corner cases. Tried to update the manpage a little.

**Comment by wm4** [comment]
OK, in mpv 0.31.0, you won't need to force GLX on radeon. Mesa actually implements vdpau just fine on EGL. I'll push a commit later that can make use of it. I don't know about nvidia; if they didn't change it, the situation will remain the same on nvidia.
