### ISSUE TITLE
On Windows how to build libmpv using the ffmpeg static library

### ISSUE THREAD

**Issue by wxz879526** [mpv-player/mpv#7119]
follow the tutorial On window  i can build the lipmpv,but it depend the ffmpeg dll... 
![QQ截图20191104123002](https://user-images.githubusercontent.com/7566672/68099724-eb0a9b80-fefe-11e9-9d61-802d5f11e0c4.png)

**Comment by avih** [comment]
You need to build (configure) ffmpeg with static libs: `./configure --enable-static --disable-shared ...`, and then mpv will link to those.

**Comment by wm4** [comment]
Or you build mxe using the static configuration. Most time it's better to just bundle the DLLs though.
