### ISSUE TITLE
If you are going to remove the v4l support then please remove the references to this in the code

### ISSUE THREAD

**Issue by jam3st** [mpv-player/mpv#7120]
Version 0.30 has remove all t he v4l2 code. This wasn't used just for old analog tuners but also for UVC cameras. I have a USB microscope mpv was the only thing that would work with it. guvview and other crap didn't work.

For some reason you have removed v4l2 support. Please remove the last reference to this in the docs too
in DOCS/man/mpv.rst

**Comment by sfan5** [comment]
After 0.30, you can still use the v4l2 support that comes with ffmpeg, like this:
`mpv av://v4l2:/dev/video0`

**Comment by jam3st** [comment]
I will give it a go. ffmpeg is working with a pipe so I think that it should work. Thanks

**Comment by wm4** [comment]
I improved the manpage, removed old mentions of tv://, and added a replacement example.

**Comment by jam3st** [comment]
yeah thanks that works quite well. I use these options too mpv -profile=low-latency --untimed --demuxer-lavf-o-set input_format=yuyv422 --demuxer-lavf-o-set video_size=1280x720 --demuxer-lavf-o-set framerate=25 av://v4l2:/dev/videoX which is what I was used to using before. The size was a hassle but thank again.

**Comment by wm4** [comment]
--demuxer-lavf-o-set doesn't accumulate. Each use overwrites the previous one.

**Comment by jam3st** [comment]
Thanks. This works for my camera mpv -profile=low-latency --untimed --demuxer-lavf-o=input_format=yuyv422,framerate=25,video_size=1280x720 av://v4l2:/dev/video
