### ISSUE TITLE
Some \k and \kf ASS subtitle effects rendered with delay/lag

### ISSUE THREAD

**Issue by AxelTerizaki** [mpv-player/mpv#7121]
### mpv version and platform

```mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Nov  2 12:14:42 +08 2019
ffmpeg library versions:
   libavutil       56.35.101
   libavcodec      58.60.100
   libavformat     58.33.100
   libswscale      5.6.100
   libavfilter     7.66.100
   libswresample   3.6.100
ffmpeg version: git-2019-11-01-53c21c2d
```

### Reproduction steps

Load the sample files listed below and see for yourself how the karaoke subs are desynced.

### Expected behavior

Captured using mpv 0.29 : 

https://cdn.discordapp.com/attachments/324208228680466434/640862388169736219/2019-11-04_11-36-40.mp4

### Actual behavior

Captured using mpv 0.30

https://cdn.discordapp.com/attachments/324208228680466434/640858951549714432/2019-11-04_11-22-27.mp4

As you can see the subtitles effect \k / \kf aren't synced properly anymore, as if there was some kind of lag.

### Log file

Here is a log : 

https://pastebin.com/AmzdQrbr

### Sample files

- Video : https://kara.moe/downloads/medias/ENG%20-%20Dokidoki!%20PreCure%20-%20OP%20-%20Glitter%20Force%20Doki%20Doki%20Theme%20Song.mp4
- Subfile : https://kara.moe/downloads/lyrics/ENG%20-%20Dokidoki!%20PreCure%20-%20OP%20-%20Glitter%20Force%20Doki%20Doki%20Theme%20Song.ass

Thanks in advance ! :)

**Comment by wm4** [comment]
If there's really a difference, it's hard to see. Can you point out a timestamp where this happens? Use ``--start=3 --pause --osd-fractions --osd-level=2`` for useful display. Look at the timestamp in the OSD, and set the ``--start`` argument to it, with a timestamp where you see a difference with mpv 0.29 and 0.30 without unpausing.

**Comment by Tsubajashi** [comment]
> If there's really a difference, it's hard to see. Can you point out a timestamp where this happens? Use `--start=3 --pause --osd-fractions --osd-level=2` for useful display. Look at the timestamp in the OSD, and set the `--start` argument to it, with a timestamp where you see a difference with mpv 0.29 and 0.30 without unpausing.

around the 4th second. the "our" is extremely quick unlike in 0.29. didnt test myself, only by the example videos.

**Comment by wm4** [comment]
Exact timestamp?
And which one is correct, i.e. confirmed by a third reference?

**Comment by Akemi** [comment]
related to the problems mentioned here https://github.com/libass/libass/pull/343 maybe? it's most likely an upstream bug and should be reported to libass.

from those two recordings for example, the "way" already starts rendering the karaoke effect before the "our" even started. don't know what is intended couldn't look that the ass file yet.
actual:
![2019-11-04_11-22-27_(00-00-03 200)_01](https://user-images.githubusercontent.com/680386/68151431-fb903580-ff41-11e9-8e90-cc7fcb433ec3.png)
expected:
![2019-11-04_11-36-40_(00-00-02 633)_01](https://user-images.githubusercontent.com/680386/68151433-fb903580-ff41-11e9-8a43-5d4ab1894265.png)

**Comment by AxelTerizaki** [comment]
Thanks for the research. Should I copy/paste this into a new issue on libass/libass ?

**Comment by wm4** [comment]
Yes.

**Comment by Akemi** [comment]
since it has been reported to libass.

**Comment by AxelTerizaki** [comment]
Is there any chance that the update to libass that caused this on mpv could be reverted in a future release if libass doesn't fix it sometime soon? I'm stuck with 0.29.x so far because of this issue since the software I use mpv with is for karaoke.

I'd understand if this would be an issue and you prefer to wait for libass to update first.

**Comment by Akemi** [comment]
making a release is 'completely' independent from libass and we can't revert anything. if you use a prebuilt binary one has to link against a different version of libass.

**Comment by wm4** [comment]
Shouldn't be a problem to use mpv with old libass, even if not recommended.
Maybe better to try to get libass to release a new version with the fix or so.

**Comment by AxelTerizaki** [comment]
Understood, thanks for the replies :)

I use a static version of mpv so not sure how I could achieve that. I suppose I can wait for an updated libass.

**Comment by AxelTerizaki** [comment]
Just a heads up since I had a case of someone running mpv 0.32 on macOS and reporting no issue at all on \kf tags, while users on Windows still experience the problem on mpv 0.32. Dunno if these two versions are linked against different libass versions though.
