### ISSUE TITLE
libmpv: observing frame based properties with mpv_observe_property is broken

### ISSUE THREAD

**Issue by gunnarmarten** [mpv-player/mpv#7122]
### mpv version and platform

MacOS 10.14.6
mpv: HEAD-f043d73
ffmpeg: git-master

### Reproduction steps

As a reference see Issue #4195. I could not reopen this issue so I'am opening a new one.
It was broken for a long time got fixed by #6642 and is now broken again on master.

I bisected this to commit d66eb93e which broke observing again.

To reproduce:
Use the sdl example from https://github.com/mpv-player/mpv-examples.git

Observe the property:

```
mpv_observe_property(mpv, 0, "playback-time", MPV_FORMAT_DOUBLE);
```

and wait for property changed events in the event loop, like this:

```
if (mp_event->event_id == MPV_EVENT_PROPERTY_CHANGE) {
    mpv_event_property *prop = (mpv_event_property *)mp_event->data;
    printf("MPV_EVENT_PROPERTY_CHANGE %s\n", prop->name);
    if (strcmp(prop->name, "playback-time") == 0 && prop->format == MPV_FORMAT_DOUBLE) {
        double pos = *(double*)prop->data;
        printf("playback-time: %f\n", pos);
    }
}
```

### Expected behavior

Should update the frame based properties like `playback-time` every frame.

### Actual behavior

Does update `playback-time` only once at the beginning.

### Log file

Before commit d66eb93e:
mpv log: http://sprunge.us/5liGvC
Output log from the sdl mpv example:
http://sprunge.us/NcJAl3

After commit d66eb93e:
mpv log: http://sprunge.us/xEymNJ
Output log from the sdl mpv example:
http://sprunge.us/pANhS0

### Sample files

Any video file

**Comment by wm4** [comment]
This definitely works for me and I can't reproduce. Tried both the sync and async paths.

**Comment by wm4** [comment]
I tried on Linux of course. git tree or just a complete paste of the example program might be helpful.

**Comment by gunnarmarten** [comment]
Hmm, ok. Haven't tried it on Linux myself. Will test that later.
Here's the source: http://sprunge.us/AxCMSl
 (maybe not the right way to share, but the quickest atm.)

**Comment by wm4** [comment]
Can't reproduce with that sample. Maybe upload a test file too for more reproducible testing, and maybe force ao=null for the same reason.

**Comment by gunnarmarten** [comment]
I did a test on Linux and the behaviour differs from MacOS.
On MacOS I don't receive any update events. On Linux I do get updates for the observed properties, see output log on Linux from the sdl mpv example:
Before commit d66eb93: http://sprunge.us/NcJAl3
After commit d66eb93: http://sprunge.us/U9iG9O

Still the output looks a bit more aligned before the change. Before commit d66eb93 you can see for every frame of the video, which is 25fps, I get an event. After the commit there are sometimes 'holes' where I don't receive an update for 3-5 frames.

Also I forced ao=null on both Linux and MacOS but the behaviour didn't change.

For the reference this is the test video I use: https://0x0.st/zgOy.mp4

**Comment by wm4** [comment]
Still can't reproduce. It doesn't actually need to be aligned with draw calls, since they're asynchronous and scheduled to happen in the future.

You could try to force the synchronous code path by making ``if (atomic_load_explicit(&ctx->clients->uses_vo_libmpv, memory_order_relaxed)) {`` in client.c always take the else branch. But the asynchronous path seems to work on Linux.

Clearly there's some missed wakeup or UB going on.

**Comment by gunnarmarten** [comment]
As I already observed here #4195, the execution order differs between Linux and MacOS. Can't say much about the locks and wakeups, there might be something fishy going on that changes the behaviour on these systems.

But I did debug the issue and found that the different execution order on MacOS triggers a bug.


On Linux the function calls look like this:
```
draw frame
mark_property_changed playback-time
gen_property_change_event: prop: playback-time changed: 1
dispatch update_prop_async
re-update later when the changed value comes in
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
gen_property_change_event: prop: playback-time changed: 0
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
update_prop_async done. Cause it to re-check the property async_value_valid: 1
draw frame
mark_property_changed playback-time
gen_property_change_event: prop: playback-time changed: 1
dispatch update_prop_async
re-update later when the changed value comes in
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
gen_property_change_event: prop: playback-time changed: 0
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
draw frame
update_prop_async done. Cause it to re-check the property async_value_valid: 1
gen_property_change_event: prop: playback-time changed: 1
update_prop changed: 1
MPV_EVENT_PROPERTY_CHANGE playback-time
playback-time: 3.120000
mark_property_changed playback-time
gen_property_change_event: prop: playback-time changed: 1
dispatch update_prop_async
re-update later when the changed value comes in
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
gen_property_change_event: prop: playback-time changed: 0
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
draw frame
update_prop_async done. Cause it to re-check the property async_value_valid: 1
mark_property_changed playback-time
gen_property_change_event: prop: playback-time changed: 1
dispatch update_prop_async
re-update later when the changed value comes in
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
gen_property_change_event: prop: playback-time changed: 0
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
update_prop_async Cause it to re-check the property async_value_valid: 1
draw frame
gen_property_change_event: prop: playback-time changed: 1
update_prop changed: 1
MPV_EVENT_PROPERTY_CHANGE playback-time
playback-time: 3.200000
```

And on MacOS it looks like this:
```
draw frame
mark_property_changed playback-time
draw frame
mark_property_changed playback-time
draw frame
mark_property_changed playback-time
gen_property_change_event: prop: playback-time changed: 1
dispatch update_prop_async
re-update later when the changed value comes in
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
gen_property_change_event: prop: playback-time changed: 0
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
draw frame
update_prop_async done. Cause it to re-check the property async_value_valid: 1
mark_property_changed playback-time
draw frame
mark_property_changed playback-time
draw frame
mark_property_changed playback-time
gen_property_change_event: prop: playback-time changed: 1
dispatch update_prop_async
re-update later when the changed value comes in
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
gen_property_change_event: prop: playback-time changed: 0
gen_property_change_event: prop: volume changed: 0
gen_property_change_event: prop: loop-file changed: 0
draw frame
update_prop_async done. Cause it to re-check the property async_value_valid: 1
mark_property_changed playback-time
draw frame
mark_property_changed playback-time
draw frame
mark_property_changed playback-time
gen_property_change_event: prop: playback-time changed: 1
dispatch update_prop_async
re-update later when the changed value comes in
```

As you can see (I hope the output is somewhat understandable) on MacOS the mark_property_changed is called more frequently and gen_property_change_event is called less frequently. Also the calling order is different.
On MacOS after update_prop_async() is done, there is always a call of mark_property_changed() before gen_property_change_event() gets called which calls update_prop() again.
This leads to prop->async_change_ts always gets incremented before update_prop() and so a new async property update is triggered and the function returns 'false' without checking the already updated async_value. Which then always prevents the property change event.

PR #7125 fixes this. Not sure if its the proper way though.

**Comment by Akemi** [comment]
i tested this on macOS. with the posted SDL2 example i can reproduce it. within mpv and cocoa-cb though it works as intended.
log: https://0x0.st/zgYn.txt
patch: https://0x0.st/zgY7.diff

**Comment by wm4** [comment]
One thing worth tracking down is whether the SDL event wakeup actually works. This could be OS-specific, and maybe it's broken on OSX, and/or it doesn't work like the original author of the example (me) thought it works.

Another possibility is that we give up the current way how property notifications are done, and instead update the value on the main thread (so the client simply reads the new value without having to jump through hoops). But probably better to track down the cause of this, instead of throwing away everything again.

**Comment by wm4** [comment]
Meanwhile there was another OSX bug (old cocoa backend was waiting on main thread, which deadlocked), so I removed the sync. code path from the "new" code. Which means I'll probably rewrite this thing anyway (and then again, until it's vaguely efficient and simple and I'm happy).
But I still think your issue is that SDL somehow doesn't perform the wakeup as expected on OSX. So if you still care about this issue, this is what to debug next.

**Comment by gunnarmarten** [comment]
@wm4 You are probably right, it looks like an underlying SDL issue but I never found the time to debug it.

Anyway, with the current master the issue is gone in both my application and the SDL2 libmpv example I used in this ticket.
Your rewrite in 2c5cb2c did the trick. Much appreciated, thanks!

**Comment by wm4** [comment]
That's probably just a coincidence, maybe by not triggering the suspected SDL race so often anymore. Or at least I didn't find anything wrong with the notification behavior of the old code.
