### ISSUE TITLE
mpv running with `--screen 0` plays with no audio on macOS Catalina

### ISSUE THREAD

**Issue by duckpuppy** [mpv-player/mpv#7126]
### mpv version and platform
macOS Catalina (10.15)

mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  3 20:28:56 CET 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.1

### Reproduction steps

Play a video using `mpv --screen 0 <video_file>`.

### Expected behavior

Video plays properly on screen 0 (laptop screen in my case)

### Actual behavior

Video plays on screen 0, but audio is not present and an error is displayed concerning a failure to initialize coreaudio.

```
2019-11-06 07:52:32.473 mpv[69543:317465] This NSLayoutConstraint is being configured with a constant that exceeds internal limits.  A smaller value will be substituted, but this problem should be fixed. Break on BOOL _NSLayoutConstraintNumberExceedsLimit(void) to debug.  This will be logged only once.  This may break in the future.
   cplayer:  (+) Video --vid=1 (*) (h264 1920x1080 29.970fps)
   cplayer:  (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
   cplayer: AO: [coreaudio] 44100Hz stereo 2ch floatp
ao/coreaudio: could not check whether device is alive (invalid device?) (jbo[33]/560947818)
ao/coreaudio: failed to select device (jbo[33]/560947818)
        ao: Failed to initialize audio driver 'coreaudio'
        ao: This audio driver/device was forced with the --audio-device option.
        ao: Try unsetting it.
   cplayer: Could not open/initialize audio device -> no sound.
   cplayer: Audio: no audio
   cplayer: VO: [libmpv] 1920x1080 yuv420p
statusline: V: 00:00:01 / 00:03:49 (0%)
```

Despite what the error says, the command line I used did not contain the `--audio-device` option. Simply changing the command line to `mpv --screen 1 <video_file>` plays fine with no issues, except it's not on the screen that I wanted it to start on. I use the `--screen` option to launch videos on screen 0 (laptop screen) when an external monitor is attached.

Using `--screen 1` plays just fine, only when trying to use `--screen 0` do I have this issue. I did not have this issue prior to upgrading to Catalina.

It seems to be related to picking an audio device... when playing on screen 1, the logs show:

```
[   0.224][v][ao] Trying audio driver 'coreaudio'
[   0.224][v][ao/coreaudio] requested format: 44100 Hz, stereo channels, floatp
[   0.230][v][lavf] stream 1: resize index to 256
[   0.248][v][ao/coreaudio] selected audio output device: External Headphones (83)
```

### Log file

https://0x0.st/zgx4.txt

### Sample files

I've not found a source that doesn't have this issue.

**Comment by wm4** [comment]
> [   0.198][v][cplayer] Set property: audio-device="coreaudio/AppleHDAEngineOutput:1B,0,1,1:0" -> 1

Actually this option is set. The `auto-audio-device.lua` script sets it (whatever it is). Though I'm not sure why the failure is happening.

**Comment by duckpuppy** [comment]
Interesting... moving that script out of the way does fix things.  It seems that it's working differently now in Catalina. It's script I don't use much, so I can move that script out of my config (I mostly forgot it's existence at this point)... I can close the ticket since it's not necessarily a bug in mpv, just a change in behavior across OS versions.

**Comment by Argon-** [comment]
Is this my script? (https://github.com/Argon-/mpv-config/blob/master/scripts/auto-audio-device.lua) 
It makes mpv switch to one of my display's attached audio output when I move it across my screens. 
The entry that is triggered for internal MBP screens is here: https://github.com/Argon-/mpv-config/blob/master/scripts/auto-audio-device.lua#L9
The audio device name might have changed. Not sure, don't use Catalina. You could test that.
