### ISSUE TITLE
NVENC error when trying to encode

### ISSUE THREAD

**Issue by FlappyFalcon** [mpv-player/mpv#7127]
mpv version:
[   0.007][v][cplayer] mpv 0.30.0-73-g00838fe0c3 Copyright Â© 2000-2019 mpv/MPlayer/mplayer2 projects
[   0.007][v][cplayer]  built on Sat Nov  2 12:02:39 +08 2019
[   0.007][v][cplayer] ffmpeg library versions:
[   0.007][v][cplayer]    libavutil       56.35.101
[   0.007][v][cplayer]    libavcodec      58.60.100
[   0.007][v][cplayer]    libavformat     58.33.100
[   0.007][v][cplayer]    libswscale      5.6.100
[   0.007][v][cplayer]    libavfilter     7.66.100
[   0.007][v][cplayer]    libswresample   3.6.100
[   0.007][v][cplayer] ffmpeg version: git-2019-11-01-53c21c2d
If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

As the title says I keep getting an error when trying to encode with nvenc
[log.txt](https://github.com/mpv-player/mpv/files/3817216/log.txt)

**Comment by wm4** [comment]
nvenc wants you to set the target level, as the error indicates.

**Comment by FlappyFalcon** [comment]
I'm not sure what you mean?

**Comment by wm4** [comment]
Going by the error message, nvenv (or libavcodec) has an option to control the h264/h265 level, which you or that script probably didn't set, or didn't set properly.

**Comment by mc4man** [comment]
Pretty sure that you can't use encoding level 3 in this case.
Additionally not too sure you can even change the encoding level when using mpv so try losing the 
--ovcopts-add=level=3
