### ISSUE TITLE
MPV Web plugin for Firefox. 

### ISSUE THREAD

**Issue by greyrat116** [mpv-player/mpv#7128]
### mpv version and platform

All

In Firefox, Chrome and other older browsers, you can use the plug-in NPAPI to view Youtube videos on the web page. Example for Windows Media Player https://hsto.org/webt/l_/xe/te/l_xete617aiczjysc6slmi_gsg4.jpeg
NPAPI support removed in Firefox quantum and Chrome

Please make MPV plugin for new browsers, Windows and Linux

**Comment by wm4** [comment]
Open an issue on the bug trackers of all browser vendor to provide an adequate API. Once they provide one, we can add such a plugin.
