### ISSUE TITLE
Audio doesn't play through speakers when connected via USB-C hub

### ISSUE THREAD

**Issue by jarbus** [mpv-player/mpv#7135]
### mpv version and platform
mpv version 0.30.0, Manjaro Linux, Kernel 5.3.8-3

### Reproduction steps
Plug laptop to speakers with 3.5mm connection via USB-C hub
Play media
### Expected behavior
Audio plays through speakers.
### Actual behavior
Audio plays through laptop. All other applications play through speakers with the exception of mpv. Plugging speakers directly into laptop works fine, but over USB they fail to play.

### Log file
http://0x0.st/zEX9.txt

**Comment by wm4** [comment]
It just seems to use pulse normally. Try ``--no-config --ao=pulse --audio-client-name=something`` to be sure.

**Comment by jarbus** [comment]
This resolved the issue, thank you very much!
