### ISSUE TITLE
gnome 3.34, wayland no window

### ISSUE THREAD

**Issue by soloturn** [mpv-player/mpv#7136]
with mpv-0.30.0 the window border is missing, with v0.29.1 it is working, just like #3350, on arch linux, gnome 3.34, wayland. on X it is always working.

**Comment by CounterPillow** [comment]
Follow the actual issue template or we won't be able to help you.

**Comment by soloturn** [comment]
mpv does not show a window border in weston-7.0.0 just like it does not in gnome, i adjusted the title, @CounterPillow.

**Comment by Dudemanguy** [comment]
Weston also doesn't support xdg-decoration protocol. In their case, it's just a reference compositor so it's a reasonable choice to make. Regardless, mpv is not in the business of drawing window decorations. It's up to the compositor to support this.

**Comment by soloturn** [comment]
@Dudemanguy thank you for the pointer, now i found the relevant piece in gnome mutter:
https://gitlab.gnome.org/GNOME/mutter/issues/217

@fmuellner was commenting that applications not supporting client side decorations are not following the wayland specification. citing out of https://github.com/wayland-project/wayland-protocols/blob/master/unstable/xdg-decoration/xdg-decoration-unstable-v1.xml 

```
This interface allows a compositor to announce support for server-side
decorations.

[...]

If compositor and client do not negotiate the use of a server-side
decoration using this protocol, clients continue to self-decorate as they
see fit.

[...]

The decoration object allows the compositor to toggle server-side window
decorations for a toplevel surface. The client can request to switch to
another mode.

[...]

The compositor can decide not to use the client's mode and enforce a
different mode instead.
```

enlightment, gnome, weston did not implement server side decorations up to now. if it is not in the specification, it might be a little complicated to argue with gnome persons and tell them that it is a bug, @CounterPillow . but i understand your position, now than i read @BearOso, @jwrdegoede, @rcgordon in the resp gnome ticket.

**Comment by CounterPillow** [comment]
>if it is not in the specification, it might be a little complicated to argue with gnome persons and tell them that it is a bug, 

Server side decorations [are part of the spec](https://github.com/wayland-project/wayland-protocols/tree/master/unstable/xdg-decoration).

GNOME just wants everyone to use GTK, there is no other reason for them not supporting it.

**Comment by soloturn** [comment]
@Dudemanguy @CounterPillow would https://gitlab.gnome.org/jadahl/libdecoration be an option?

**Comment by Dudemanguy** [comment]
There's actually CSDs now thanks to #7186.

**Comment by Rafostar** [comment]
@soloturn You can get decorations by forcing mpv to use XWayland via `--gpu-context=x11egl` option. This also works with hardware acceleration.

**Comment by soloturn** [comment]
@Dudemanguy @philipl to do this via OSC, https://mpv.io/manual/master/#on-screen-controller, is extremely cool. works great.

**Comment by soredake** [comment]
https://github.com/libsdl-org/SDL/pull/4068

**Comment by soredake** [comment]
Can mpv support this through https://gitlab.gnome.org/jadahl/libdecoration?

**Comment by Akemi** [comment]
can, sure. want, probably not. we already have CSD now.

**Comment by Dudemanguy** [comment]
Nobody really wants to incur a dbus dependency so almost certainly no.
