### ISSUE TITLE
[Build system] Would it be possible to specify some option to bootstrap.py to not download waf, if a local recent version of waf is available?

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#7137]
### mpv version and platform

Latest 0.30 release from the releases URL on the github entry here of mpv.

Heya folks.

I have waf installed locally. The version it reports is this:

waf 2.0.18 (314689b8994259a84f0de0aaef74d7ce91f541ad)

So, I have waf here.

When trying to compile mpv 0.30, I tried this step:

    ./bootstrap.py

Not sure if this is necessary or not but I used to do so in the past.

This tries to download waf though:

Downloading https://waf.io/waf-2.0.9...
Download failed.
Downloading http://www.freehackers.org/~tnagy/release/waf-2.0.9...
Download failed.
Could not download waf-2.0.9.

I think I know why it failed; I have a local problem with openssl and
fixing this requires some more time. (Multiple different ssl versions
here, in different directories; cleaning this up takes a bit longer
though, can't solve it in the next days due to lack of time mostly).

When I noticed this error, though, I wonder if I really need waf
2.0.9. Are the differences that big? Could waf-2.0.8 suffice?

That led me to this question:

Would it be possible to the bootstrap.py to first check whether
a local version of waf is available, or perhaps specify some
documented configure flag that allows us to re-use an existing
waf? The use case would be primarily due to being able to
avoid situations like the above, e. g. where waf is already
installed, and a new re-download may fail due to any reason.

"./bootstrap.py  --help" does not work so I assume it really
does not do a whole lot. Perhaps that could be added too
if someone would like to extend it.

Anyway this is just a suggestion, low priority indeed. I mention
it in the event that someone may want to consider it and
perhaps has too much time available on his or her hand,
too. :)

**Comment by avih** [comment]
`bootstrap.py` doesn't do anything other than downloading waf. You don't need to use it if you already have waf installed. Just run `waf configure && waf build` instead of `./waf configure && ./waf build`.
