### ISSUE TITLE
Crash with lavfi-complex

### ISSUE THREAD

**Issue by Forcer78** [mpv-player/mpv#7141]
### mpv version and platform

Latest build from https://laboratory.stolendata.net/~djinn/mpv_osx/:

```
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  3 20:28:56 CET 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.1
```

Platform macOS 10.12.6.

### Reproduction steps

Unpack the attached sample archive and run the included script:

```
cd sample
sh script.sh
```

The script runs the exact same simple `--lavfi-complex` filter in both FFmpeg and mpv on two files, pass.mp3 and fail.mp3.

Both pass.mp3 and fail.mp3 are CBR 320kbps MP3s with embedded cover art. Every track from their respective albums has the same behavior as these examples. `--af=lavfi` has not crashed in this manner so far.

This issue is a requested repost of https://github.com/mpv-player/mpv/issues/6608.

### Expected behavior

FFmpeg converts/filters the files and mpv plays them with the filter applied.

### Actual behavior

FFmpeg successfully converts both files.
mpv filters and plays pass.mp3, but crashes with a segfault on fail.mp3.

### Log file

These logs are from mpv v0.29.1, which crashes in the same way:

Log file for fail.mp3: https://0x0.st/zP5A.txt
Crash log for fail.mp3: http://0x0.st/zP5j.txt

### Sample files

http://0x0.st/zP5M.zip

This zip contains pass.mp3, fail.mp3, and script.sh.

**Comment by wm4** [comment]
It crashes because a filter gets unaligned input.

I'm just tired of this ffmpeg piece of shit...
