### ISSUE TITLE
[vo/gpu/vulkan/libplacebo] Failed creating instance: VK_ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by l29ah** [mpv-player/mpv#7142]
### mpv version and platform

git master on Gentoo GNU/Linux.

### Reproduction steps
--gpu-api=vulkan

### Expected behavior
worky

### Actual behavior
not worky, even though vulkan works in wine
[vulkaninfo.txt](https://github.com/mpv-player/mpv/files/3828293/vulkaninfo.txt)

### Log file

```
[vo/gpu] Probing for best GPU context.
[vo/gpu/vulkan] Initializing GPU context 'x11vk'
[vo/gpu/vulkan/libplacebo] Available instance extensions:
[vo/gpu/vulkan/libplacebo] Available layers:
[vo/gpu/vulkan/libplacebo] Creating vulkan instance with extensions:
[vo/gpu/vulkan/libplacebo]     VK_KHR_get_physical_device_properties2
[vo/gpu/vulkan/libplacebo]     VK_KHR_surface
[vo/gpu/vulkan/libplacebo]     VK_KHR_xlib_surface
[vo/gpu/vulkan/libplacebo] Failed creating instance: VK_ERROR_INITIALIZATION_FAILED
[vo/gpu/vulkan/libplacebo] Failed initializing vulkan instance
```

[log.txt](https://github.com/mpv-player/mpv/files/3828292/log.txt)

**Comment by haasn** [comment]
Are you sure mpv and vulkaninfo are running in the same environment and
loading the same version of vulkan drivers? It's extremely suspicious
that your log file reports a vulkan loader with no instance extensions.
That's practically impossible.

It might be useful to strace mpv, or to gdb it and break on
vkCreateInstance and just see where it's going.

**Comment by l29ah** [comment]
Thank you, it turned out mpv was not allowed to use vulkan stuff by apparmor.
