### ISSUE TITLE
mpv 0.30 issue with rar video playback latest libarchive

### ISSUE THREAD

**Issue by mac010** [mpv-player/mpv#7144]
### mpv version and platform
Fedora 31
mpv 0.30
libarchive 3.4.0-1

### Reproduction steps
Play video in multi-part rar file.
[libarchive] possibly unsupported seeking - switching to reopening
No video window opens.
Happens on about half of rar'd video out there.

### Expected behavior
Playback of rared videos as was possible with 0.29 with older libarchive.

### Actual behavior
No video window.

**Comment by CounterPillow** [comment]
no log, no sample
