### ISSUE TITLE
No longer removes mouse pointer; even in fullscreen (x11)

### ISSUE THREAD

**Issue by hills** [mpv-player/mpv#7145]
### mpv version and platform

0.30.0 and b5894e760d tested as bad.
0.29.1 works ok.

Slackware 14.2 x86_64
xorg-server-1.18.3-x86_64-5_slack14.2

### Reproduction steps

env DISPLAY=:0 mpv vsync-test.mp4 

### Expected behavior

Video plays full screen in X11, with no mouse pointer.

### Actual behavior

The mouse pointer is still visible, over the top of the video.

### Log file

working ok; no mouse pointer: [0.29.1.txt](https://github.com/mpv-player/mpv/files/3833477/0.29.1.txt)
broken; mouse pointer visible: [git-master.txt](https://github.com/mpv-player/mpv/files/3833475/git-master.txt)

### Notes

I use a simple X11 server running on :0 with no window manager connected to a projector.
Since upgrading from 0.29.1 to 0.30.0, the mouse pointer is still visible during playback.
Repeated tests switching versions and the behaviour is consistent and reproducable.

The same behaviour whether "-fs" is used or "f" is pressed during playback.

With v0.29., when exiting full screen the pointer would be visible for a few seconds, then hidden.

There is also a problem which is perhaps related; on exiting mpv does not always return to the X11 background; the video stays on the screen.

**Comment by wm4** [comment]
Works for me on x11.

**Comment by CreamyCookie** [comment]
for me the mouse cursor is moved to the top right of the screen..

**Comment by Dudemanguy** [comment]
Old and possibly doesn't happen anymore. Please open a new issue if this still occurs.
