### ISSUE TITLE
mpv seems to skip the first frame in loops.

### ISSUE THREAD

**Issue by crocket** [mpv-player/mpv#7150]
### mpv version and platform

Gentoo Linux

```
> mpv --version
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: 4.1.3
```

### Reproduction steps

* Play any short gif or a short video in mpv
* Play the same file in a web browser
* Compare the two

### Expected behavior

mpv shows every frame

### Actual behavior

mpv seems to skip the first frame in loops. I don't know whether it drops the last frame in other animated image files or videos when it's in loops.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/3846951/log.txt)

### Sample files

![123](https://user-images.githubusercontent.com/748856/68865494-424a1080-0736-11ea-81cd-a506815fccf4.gif)

**Comment by wm4** [comment]
Strangely happens in audio-sync mode only.

**Comment by crocket** [comment]
`--initial-audio-sync=no` doesn't affect the issue.
