### ISSUE TITLE
Change AV1 video decoder based on bit-depth (8-bit/10-bit)

### ISSUE THREAD

**Issue by grill05** [mpv-player/mpv#7151]
### mpv version and platform

mpv 0.30.0-UNKNOWN Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Nov  9 20:38:53 +0630 2019
ffmpeg library versions:
   libavutil       56.35.101
   libavcodec      58.60.100
   libavformat     58.34.101
   libswscale      5.6.100
   libavfilter     7.66.100
   libswresample   3.6.100
ffmpeg version: 4.2.git

### Reproduction steps
This is specifically about decoding "AV1" encoded videos. For AV1, ffmpeg (and thus mpv) defaults to using the libdav1d decoder. Now libdav1d is very efficient for 8-bit decoding, but libaom-av1 is much faster for 10-bit videos.
I would like to "switch" between the decoders depending on the bitdepth. So I want to use libdav1d for 8-bit decoding and libaom-av1 for 10-bit.
In ffmpeg, I can do this by specifying
`ffmpeg -c:v libaom-av1 -i <input-video>`
which tells ffmpeg to use the libaom decoder instead of the defautl (dav1d). 
Is there a way to do this in mpv ?

**Comment by wm4** [comment]
You can manually select the video decoder with --vd.
