### ISSUE TITLE
EGL initialization fails with mesa 19.3.0 rc3

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#7154]
Workaround: setting `EGL_PLATFORM=x11` as environment variable supposedly makes it work. `gpu-context=x11`` (uses GLX) probably also works.

**Comment by NiLuJe** [comment]
Yeah, plain old GLX worked just fine on my end. I'll give your latest commit a try in the next 24h, thanks!

**Comment by barolo** [comment]
> Yeah, plain old GLX worked just fine on my end. I'll give your latest commit a try in the next 24h, thanks!

wouldn't that break vaapi which uses EGL? on amdgpu?

**Comment by NiLuJe** [comment]
Yup, which was one of the reason I 1. noticed it in the first place, as I almost never use hwdec, 2. tried to figure out what was happening.

**Comment by barolo** [comment]
> Yup, which was one of the reason I 1. noticed it in the first place, as I almost never use hwdec, 2. tried to figure out what was happening.

I'm on the other side, I always use hwdec, because cpu usually is hogged with something and it just wouldn't play smoothly [occasional 4k hdr content is not very pleasant without hwdec too ]

**Comment by barolo** [comment]
@wm4 
Just confirming that your changes fixed it. Thanks!

**Comment by NiLuJe** [comment]
Yep, that did the trick ;).

**Comment by aqxa1** [comment]
Breaks for me with Mesa too. I was using a week old Mesa-git without problems, but updating today and now have the issue. I also updated LLVM10-git at the same time (which was 2 weeks old), along with xf86-video-amdgpu-git (3 weeks old).

The issue also affects LookingGlass (which uses EGL by default).

The workaround also works for me.

**Comment by Dudemanguy** [comment]
The EGL stuff changed a lot and it appears fixed? Closing for now.
