### ISSUE TITLE
Unnecessary nvidia GPU probing with vo=gpu creates slow down and error message

### ISSUE THREAD

**Issue by rien333** [mpv-player/mpv#7157]
### mpv version and platform

```
$ mpv --version
mpv 0.30.0-153-gba370e9599 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 17 00:40:47 CET 2019
ffmpeg library versions:
   libavutil       56.35.101
   libavcodec      58.62.100
   libavformat     58.35.100
   libswscale      5.6.100
   libavfilter     7.66.100
   libswresample   3.6.100
ffmpeg version: N-95734-gbfa8272f40
$ uname -a
Linux hostname 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux
```

#### GPU info 
I'm using a laptop with an intel GPU and a nvidia GPU. I have the latest stable versions of cuda and the nvidia drivers, but do not have them loaded, and the nvidia GPU is turned off using bbswitch.  As for my intel GPU  related packages, I run X11 over xf86-video-intel-git, and have intel-media-driver and intel-hybrid-codec-driver installed. 

### Reproduction steps

``` 
$ mpv --no-config --vo=gpu --hwdec=vaapi file.mkv 
[vo/gpu/cuda-nvdec] cu->cuInit(0) failed -> CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 1920x1040 vaapi[nv12]
AV: 00:00:00 / 01:26:25 (0%) A-V: -0.001
```

### Expected behavior

Something similair in speed as when using `--vo-vaapi`, with  no errors about non-findable GPUs.

``` 
$ mpv --no-config  --vo=vaapi --hwdec=vaapi 
[vo/vaapi] Warning: this compatibility VO is low quality and may have issues with OSD, scaling, screenshots and more.
[vo/vaapi] vo=gpu is the preferred choice in any case and includes VA-API support via hwdec=vaapi or vaapi-copy.
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz stereo 2ch float
VO: [vaapi] 1920x1040 vaapi[nv12]
```

### Actual behavior

The above `--vo=gpu` based command  runs noticeably slower compared to the (deprecated)  `--vo=vaapi` variant (although it has significantly improved in recent times).   As you can see from the logs, the majority of the start-up time is spend on the nvdec-related error. In contrast, playing with `--vo=vaapi` is instantaneous. 

 Moreover, I would expect mpv to not probe a different, disabled GPU if I'm running from another intel one and am using intel-specific options (e.g. --hwdec=vaapi).

### Log file

https://0x0.st/z6QN.txt

### Sample files

Seems to happens with all video files.

**Comment by wm4** [comment]
It isn't "probing GPUs". It's only initializing hardware decoding interop modes. It won't do so without hw decoding. If it's slow, it's a driver issue.

Yeah, cuda waits 0.3seconds for nothing. Complain to nvidia, or uninstall the drivers, or disable it at mpv build time. Not our problem.

**Comment by rien333** [comment]
Thanks for the suggestions and your work on mpv. I'm guessing no, but given that mpv doesn't _always_ need to initialize the cuda interop mode (and same for some of the other modes), is there anyway to tell mpv "hey, I only care about this mode now, and just fail if that mode initializes unsuccessfully?" It feels a bit weird to check for other modes if a perfectly fine one exists/is already found. 

But yeah, if nothing can be done at runtime, I guess I'll try compiling without nvidia support.

**Comment by wm4** [comment]
All interop modes are initialized, because otherwise we'd have to keep hardcoded information about what is "supposed" to work, and have more complicated interaction with the decoder.
Nvidia have other places where they apparently have sleep() calls for no reason, again, not our problem. This kind if stuff has absolutely no reason to wait half an eternity.

**Comment by varagnac** [comment]
> All interop modes are initialized, because otherwise we'd have to keep hardcoded information about what is "supposed" to work, and have more complicated interaction with the decoder.
> Nvidia have other places where they apparently have sleep() calls for no reason, again, not our problem. This kind if stuff has absolutely no reason to wait half an eternity.

It not only slows the startup down but also somehow causes strange excessive power consumption. 
I am now prime-offloading the nvidia card, so without `prime-run` nvidia card should not be turned on. And it is not turned on (nvidia-smi doesn't show it is taking part in the rendering of mpv related stuff).
However it seems that the probing itself makes nvidia card or the pci controller active. With -vo=vaapi there's no issue. With vo=gpu there'll be about 8W of excessive power consumption present, even with the video playing paused, and it'll be gone as soon as mpv is closed.

**Comment by haasn** [comment]
> is there anyway to tell mpv "hey, I only care about this mode now, and just fail if that mode initializes unsuccessfully?"

https://mpv.io/manual/master/#options-gpu-hwdec-interop might help?
