### ISSUE TITLE
Subtitles without spaces do not break to a new line when overfull

### ISSUE THREAD

**Issue by svenper** [mpv-player/mpv#7158]
### mpv version and platform
```text
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Mon Nov 11 15:23:10 UTC 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.1
```
Void Linux
linux 5.3.11
musl 1.1.24

### Reproduction steps

* have a screen resolution of 2560x1600 with a DPI of 227
* `mpv https://www.viki.com/videos/1143425v-the-legend-of-hao-lan-episode-17 --sub-font-size=85 --sub-font="Source Han Sans" --slang=zh --log-file=/tmp/mpv.log`
* at 10:04, note the subtitle "一定不愿意看到你带着如此刻薄的仇恨去生活" / "she would definitely not want to see you live your life with such deep-rooted hostility"

### Expected behavior

Subtitle lines without spaces (Chinese, Japanese, etc.) wrap automatically when too long.

### Actual behavior

Such lines extend outside the window, with characters cropped.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/3855129/mpv.log)

**Comment by Akemi** [comment]
report it to libass. i downloaded the vtt subs and converted them to ass with ffmpeg. 
```
ffmpeg -i 17-1143425v.zh.vtt sub.ass
```
the result. .txt extension instead of .ass because github only allows text files with txt extension. add those subs to the libass issue.
[sub.txt](https://github.com/mpv-player/mpv/files/3855514/sub.txt)

**Comment by Akemi** [comment]
closing since it was reported upstream.

**Comment by escape0707** [comment]
This seems solved by both `libass` and the shown PR. But I think I'm facing this issue again with some long Japanese subtitles I generated from OpenAI/Whisper. Could it be that I'm using `gpu-next`? Maybe I should submit a separate issue report?

**Comment by llyyr** [comment]
> Could it be that I'm using `gpu-next`?

I don't see why this would affect anything, but you could simply switch to vo=gpu to confirm...

**Comment by escape0707** [comment]
I just gave it a try with `vo=gpu` and yes, the subtitles are still not getting separated into multiple lines... I'm using mpv-git on Arch Linux, so I guess the fixes should have been included. And the undesired behavior also appears for me with mpv-android.

**Comment by llyyr** [comment]
Open a new issue with samples and follow the template
