### ISSUE TITLE
Strange audio playing behavior

### ISSUE THREAD

**Issue by snylonue** [mpv-player/mpv#7167]
It may not be an issue

### mpv version and platform

```
mpv 0.30.0-153-gba370e9599 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Nov 17 08:17:28 +08 2019
ffmpeg library versions:
   libavutil       56.35.101
   libavcodec      58.62.100
   libavformat     58.35.100
   libswscale      5.6.100
   libavfilter     7.66.100
   libswresample   3.6.100
ffmpeg version: git-2019-11-17-eeab1832
```

### Reproduction steps
open an audio file with no output device
### Expected behavior
the audio plays as usual with no voice
### Actual behavior
mpv exits
### Log file

```
 (+) Video --vid=1 [P] (mjpeg 1423x1412)
 (+) Audio --aid=1 (flac 2ch 44100Hz)
File tags:
 Artist: CHiCO with HoneyWorks
 Album: 世界は恋に落ちている
 Album_Artist: CHiCO with HoneyWorks
 Comment: 2014.08.06
 Date: 2014
 Genre: アニメ
 Title: color (Instrumental)
 Track: 04
Displaying attached picture. Use --no-audio-display to prevent this.
[ao/wasapi] There are no playback devices available
AL lib: (WW) Failed to open playback device: Device init failed: 0x80070490
AL lib: (WW) Error generated on device 0000000000000000, code 0xa004
[ao/openal] could not open device
[ao] Failed to initialize audio driver 'openal'
Could not open/initialize audio device -> no sound.
Audio: no audio
```

**Comment by CounterPillow** [comment]
Please post a full log generated with `--log-file`, the one you posted doesn't show mpv exiting.

**Comment by wm4** [comment]
How would audio play if there's no output device?

**Comment by CounterPillow** [comment]
@wm4 I don't think he's expecting audio to play. He wants the video track to be shown, i.e. the cover art picture, for the duration of the audio track.

**Comment by wm4** [comment]
Without audio, coverart is going to be interpreted as an image, and --image-display-duration will determine how long to show it (at least on git master). No way around it.

**Comment by snylonue** [comment]
So mpv will exit when there's no output device? Pasue might be a better choice
