### ISSUE TITLE
Libmpv failed to destroy instance. (randomly)

### ISSUE THREAD

**Issue by EzeKees** [mpv-player/mpv#7169]
### mpv version and platform
mpv 0.30.0-153-gba370e9599 (lastest shinchiro build) 
Windows 10 1909 x64

### Expected behavior
Play any video with MPV through the .NET framework.

### Actual behavior
random crash when destroying libmpv instance (mpvDestroy):
![Captura](https://user-images.githubusercontent.com/25028878/69274855-0261ae00-0bba-11ea-9228-a785b6cdde22.PNG)

### Log file
https://pastebin.com/m7zJQEXm

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it. If the issue is a build failure, upload build/config.log instead.

If this is a normal runtime bug, and no log is provided, the issue will be
closed for ignoring the issue template. This is because analyzing a bug without
a log file is harder than necessary. Low quality bug reports are noise.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wm4** [comment]
Any chance for a backtrace? Does the same happen with the CLI player?

**Comment by EzeKees** [comment]
> Any chance for a backtrace? Does the same happen with the CLI player?

Only in Visual Studio do I receive "External Code" in the stacktrace.
This does not happen in the CLI player.

**Comment by EzeKees** [comment]
close this. the error was mine, it did not synchronize the accesses and I was getting deadlocks.
