### ISSUE TITLE
vo_gpu has no drm/vulkan GPU context

### ISSUE THREAD

**Issue by blaah2200** [mpv-player/mpv#7170]
Can there be? I see drm/egl but no vulkan. Why not.

**Comment by philipl** [comment]
It's a bunch of work but it can be done, in theory.

**Comment by Akemi** [comment]
is that a question or a feature request? should this be closed?

**Comment by blaah2200** [comment]
Its both..

**Comment by Dudemanguy** [comment]
There's the `displayvk` context now. Strictly speaking, it's not technically drm (it's only vulkan) but that should accomplish basically the same thing.
