### ISSUE TITLE
(mpv,ubuntu18.04) scrambled, pixelated video

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#7177]
### mpv version and platform

mpv --version
mpv git-2019-10-26-8e50d7a Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Tue Nov  5 15:23:07 UTC 2019
ffmpeg library versions:
   libavutil       56.35.101
   libavcodec      58.60.100
   libavformat     58.33.100
   libswscale      5.6.100
   libavfilter     7.65.100
   libswresample   3.6.100
ffmpeg version: git-2019-10-26-1054752

on ubuntu 18.04. lts
mpv installed from here (ppa)
https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests

### Reproduction steps

playing video 

### Expected behavior

audio + video should play normal

### Actual behavior

audio normal, video totally scrambled and pixelated, color shifts; in fullscreen blinking.

### Log file

[vulkaninfo.zip](https://github.com/mpv-player/mpv/files/3881457/vulkaninfo.zip)
[output.txt](https://github.com/mpv-player/mpv/files/3881482/output.txt)

**Comment by mc4man** [comment]
With that build and subsequent see no issues with vulkan though only can test with intel and nvidia, both with x11vk or waylandvk.
Your log doesn't show any attempt to use vulkan..

**Comment by Akemi** [comment]
yeah don't see any vulkan either.

**Comment by mrkapqa** [comment]
thanks ,

i don't know what happened, really, this time,
but in the meantime had to reinstall the OS (Ubuntu 18.04) and undertook some steps:

1) installed on fresh system AMDGPU-PRO driver
2) installed on top of it Vulkan SDK (as suggested by AMD Homepage in the Notes; to use the Vulkan Driver stack, this is needed to install)

all this i did to be able to enable the AMD VCE engine in Handbrake as per manual on their homepage
https://handbrake.fr/docs/en/latest/technical/video-vce.html

the handbrake manual does not mention the vulkan driver SDK thing, but on my computer it was necessary to get the AMD VCE option to show up in Handbrake.

Said this, when i then try to install MPV via ppa, it seems that on top of it there get installed some additional packages, which mess up the whole thing, so that i can't use a Video player anymore and MPV gives segmentation fault.

> sudo apt-get install mpv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libdav1d3 libfdk-aac1 liblua5.2-0 libmodplug1 libmysofa0 libplacebo18
  libuchardet0 libzimg2 **mesa-vulkan-drivers**
The following NEW packages will be installed:
  libdav1d3 libfdk-aac1 liblua5.2-0 libmodplug1 libplacebo18 libuchardet0
  libzimg2 mesa-vulkan-drivers mpv
The following packages will be upgraded:
  libmysofa0
1 upgraded, 9 newly installed, 0 to remove and 4 not upgraded.
Need to get 12,4 MB of archives.
After this operation, 37,9 MB of additional disk space will be used.
Do you want to continue? [Y/n] 

So, when i uninstall MPV from PPA, the Handbrake thing works, but i cannot use the MPV bleeding edge anymore (probably the mesa-vulkan-driver package interfers with the AMDGPU-PRO drivers?=)
At this moment , i am trying to preserve the initial configuration (AMDGPU-PRO + Handbrake) and install/compile a MPV myself.
I never had good luck with mpv versions from Debian/Ubuntu that came with the distro since probably ever (resorted initally to Debian Multimedia, later compiled myself with the help of some pages or used PPA when on Ubuntu).

**Comment by mrkapqa** [comment]
well, i installed the MPV now from the Bionic repository, and it seems to function well.
Thanks for your help!
(If you know a good script on how to compile for Debian Buster / latest Ubuntu), please share it here!
I was lately still using this guide here
https://nyxi.eu/compiling-mpv-on-debian.html

**Comment by mc4man** [comment]
The mesa-vulkan-drivers package can be removed, it's only a recommend.
Noted on the ppa that they can be removed, i was only aware of possible interference with nvidia gpu only machines...
