### ISSUE TITLE
[Feature Request] Restore invisible GUI when "_" has been pressed

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#7178]
### mpv version and platform
mpv v2:0.29.1+git3~tr on Ubuntu Linux

### Reproduction steps
Example video : https://www.youtube.com/watch?v=HwbRkSnPpm8

I've accidentally pressed `_` (the underscore key) and `mpv` has switched to the audio track making the GUI invisible and no accesible anymore even by pressing "_" again because the calling terminal is closed : 

```bash
$ mpv --ytdl-format 18 https://www.youtube.com/watch?v=HwbRkSnPpm8 &
[1] 11009
$ Playing: https://www.youtube.com/watch?v=HwbRkSnPpm8
 (+) Video --vid=1 (*) (h264 480x360 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
VO: [gpu] 480x360 yuv420p
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
AO: [pulse] 44100Hz stereo 2ch float
Track switched:
     Video --vid=1 (*) (h264 480x360 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)

$ exit
```

Can you please implement a signal trap to catch a signal (SIGUSR2 for example) to switch `mpv` back to the first video track when this signal is sent to the `mpv` process : 
```bash
$  pgrep -f "https://www.youtube.com/watch\?v=HwbRkSnPpm8" -a
11009 /usr/bin/mpv --ytdl-format 18 https://www.youtube.com/watch?v=HwbRkSnPpm8
$ kill -SIGUSR2 $(pgrep -f "https://www.youtube.com/watch\?v=HwbRkSnPpm8")
```

**Comment by CounterPillow** [comment]
You could either use `force-window=yes` or have it always open some IPC socket that you can use the JSON IPC to communicate with.

**Comment by wm4** [comment]
Yeah, I'd also suggest force-window, or enabling pseudo-GUI mode (which does something similar).

**Comment by sebma** [comment]
The pseudo-GUI mode seems to keep the window open even if the video playing is finished.

I'll stick with the `force-window=yes` in my `mpv.conf`

Thanks a lot guys !
