### ISSUE TITLE
MPV Player stop working after last update

### ISSUE THREAD

**Issue by ocu7** [mpv-player/mpv#7179]
I want to start by saying please excuse my post because it may be wrong or maybe it doesn't follow some rules. I'm a beginner in linux and this is actually my first post on github or other forums so please excuse my mistakes and my poor english.
After the last update my mpv player stopped working completely.
Please help, my main use of the computer is watching movies and the only player that I can do that with is the wonderful MPV Player, until now.
### mpv version and platform
MPV version it was from what i remember 0.19xx and after last update was 0.20xx
I have added the following to my PPA list, so my updates are done automatically: 
"deb http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu bionic main"
Linux Mint 19.2 Cinnamon
Video card: NVIDIA Corporation G92 [GeForce 9800 GT]
NVIDIA Driver Version: 340.107
### Reproduction steps
When trying to start application nothing happens
### Expected behaviour
Playing movie files.
### Actual behaviour
Not running at all. When writing in terminal "mpv" the next line I get is: 
"mpv: symbol lookup error: mpv: undefined symbol: eglGetPlatformDisplay"
mpv -v doesn't work, nothing works, anything starting with mpv i get the same result:
"mpv: symbol lookup error: mpv: undefined symbol: eglGetPlatformDisplay"

Thanks for your help, and again, sorry if I made too many mistakes.

**Comment by CounterPillow** [comment]
Try with `--gpu-context=x11`, your old driver for your old GPU seems to be lacking EGL

**Comment by jeeb** [comment]
Basically what is happening is:
1. We link the application against this symbol (currently in both wayland and x11 EGL paths).
2. Thus the binary requires this symbol to start up.
3. Your driver is unfortunately old enough to not have that.
4. The binary doesn't start.

Now the alternatives are:
1. We make the loading dynamic a la `context_{angle,drm_egl}`.
2. We require this symbol to exist in the driver even though we support non-EGL GL.

I'd side with 1. probably since the change shouldn't be too big. Make a helper file or utilize an existing one, make the function load the symbol up when needed. Could attempt to throw up a patch for that this week-end.

**Comment by jeeb** [comment]
(Note: I'm not for adding immense amounts of dynamic loading into mpv, just that this specific case seems relatively simple and shouldn't gather too much pain given that eglGetProcAddress doesn't seem to be a problem?)

**Comment by jeeb** [comment]
@ocu7 would it be possible for you to build a binary and check if this patch applied would work?
```diff
diff --git a/video/out/opengl/context_wayland.c b/video/out/opengl/context_wayland.c
index 2dd8cdec29..3dfee376d1 100644
--- a/video/out/opengl/context_wayland.c
+++ b/video/out/opengl/context_wayland.c
@@ -163,8 +163,8 @@ static bool egl_create_context(struct ra_ctx *ctx)
     struct priv *p = ctx->priv = talloc_zero(ctx, struct priv);
     struct vo_wayland_state *wl = ctx->vo->wl;
 
-    if (!(p->egl_display = eglGetPlatformDisplay(EGL_PLATFORM_WAYLAND_KHR,
-                                                 wl->display, NULL)))
+    if (!(p->egl_display = mpegl_get_platform_display(EGL_PLATFORM_WAYLAND_KHR,
+                                                      wl->display, NULL)))
         return false;
 
     if (eglInitialize(p->egl_display, NULL, NULL) != EGL_TRUE)
diff --git a/video/out/opengl/context_x11egl.c b/video/out/opengl/context_x11egl.c
index e86b99bb36..e7ad548274 100644
--- a/video/out/opengl/context_x11egl.c
+++ b/video/out/opengl/context_x11egl.c
@@ -104,8 +104,8 @@ static bool mpegl_init(struct ra_ctx *ctx)
     if (!vo_x11_init(vo))
         goto uninit;
 
-    p->egl_display = eglGetPlatformDisplay(EGL_PLATFORM_X11_KHR,
-                                           vo->x11->display, NULL);
+    p->egl_display = mpegl_get_platform_display(EGL_PLATFORM_X11_KHR,
+                                                vo->x11->display, NULL);
     if (!eglInitialize(p->egl_display, NULL, NULL)) {
         MP_MSG(ctx, msgl, "Could not initialize EGL.\n");
         goto uninit;
diff --git a/video/out/opengl/egl_helpers.c b/video/out/opengl/egl_helpers.c
index 29057614b2..fed26abdd9 100644
--- a/video/out/opengl/egl_helpers.c
+++ b/video/out/opengl/egl_helpers.c
@@ -51,6 +51,8 @@ struct mp_egl_config_attr {
 
 #define MP_EGL_ATTRIB(id) {id, # id}
 
+static PFNEGLGETPLATFORMDISPLAYPROC mp_egl_get_platform_display = NULL;
+
 static const struct mp_egl_config_attr mp_egl_attribs[] = {
     MP_EGL_ATTRIB(EGL_CONFIG_ID),
     MP_EGL_ATTRIB(EGL_RED_SIZE),
@@ -277,3 +279,13 @@ void mpegl_load_functions(struct GL *gl, struct mp_log *log)
     if (!gl->SwapInterval)
         gl->SwapInterval = swap_interval;
 }
+
+EGLDisplay mpegl_get_platform_display(EGLenum platform, void *native_display, const EGLAttrib *attrib_list)
+{
+    if (!mp_egl_get_platform_display &&
+        !(mp_egl_get_platform_display = mpegl_get_proc_address(NULL, "eglGetPlatformDisplay"))) {
+        return NULL;
+    }
+
+    return mp_egl_get_platform_display(platform, native_display, attrib_list);
+}
\ No newline at end of file
diff --git a/video/out/opengl/egl_helpers.h b/video/out/opengl/egl_helpers.h
index df489daf0c..92bb47e0bf 100644
--- a/video/out/opengl/egl_helpers.h
+++ b/video/out/opengl/egl_helpers.h
@@ -29,4 +29,6 @@ bool mpegl_create_context_cb(struct ra_ctx *ctx, EGLDisplay display,
 struct GL;
 void mpegl_load_functions(struct GL *gl, struct mp_log *log);
 
+EGLDisplay mpegl_get_platform_display(EGLenum platform, void *native_display, const EGLAttrib *attrib_list);
+
 #endif
```

**Comment by ocu7** [comment]
@CounterPillow:I have tried to run `mpv --gpu-context=x11` and got the same result, **but** you gave me the idea to change the video driver from Driver Manager, which I did, and now it works. Curently I'm running `x11 server: X.Org 1.19.6 driver: nouveau`
Now, idk what is EGL and why is lacking on nvidia driver. The nvidia driver version i was running was 340.107 which is "(the recommended)" one and the last one available in Driver Manager and before update it seem to work.
Is it possible to get MPV Player to work with the nvidia driver?
Thanks for your response and for promptitude.

@jeeb I'm **way** too noob to understand what you have said. Can tell me exactly what to do?
I have zero coding experience and my linux experience is almost zero as well. I'm so sorry!
I have made this account to github just to post this thread because MPV Player not working is a really big problem for me, MPV Player being my main use program and watching movies my main activity on PC.
Thanks for your response though.

**Comment by ocu7** [comment]
@jeeb How can I build a binary? And what should I do with it? Sorry for my silly questions!

**Comment by wm4** [comment]
@jeeb I tried exactly the same thing, but determined it'd be too hard to be 1.4 standard compliant (at least "by the letter"). So far I hoped falling back to the GLX backend would be fine for ancient installs.

**Comment by jeeb** [comment]
Alas, you cannot fall back if the symbol cannot be found in the driver. This is not for 1.4 compliance but rather just to make the binary launch at all with a driver that doesn't have that symbol.

**Comment by wm4** [comment]
Symbol not found => shit shouldn't link or build.

**Comment by jeeb** [comment]
In this case it was built against whatever EGL header/library providing library there was in Ubuntu. Probably mesa. 

That doesn't mean that the user would have the same driver.

**Comment by wm4** [comment]
Not My Problem™

**Comment by mc4man** [comment]
This is old hardware.
It's possible the poster could build mpv locally in the absence of libegl1-mesa-dev & it would run for their env.

**Comment by jeeb** [comment]
Yes, but I see this as something not limited to just this user.

Distros or other systems building for various users are bound to want to build with the kitchen sink, and if it's just this symbol it doesn't seem too bad to let people on this 2018 driver actually run the binary and be able to utilize GLX just like they had before.

**Comment by wm4** [comment]
Broken build. mpv was built against EGL 1.5, but at runtime you get EGL 1.4.

**Comment by wm4** [comment]
@jeeb I guess we could somehow try to work this around this way, but then I think it should always error out if it finds that EGL is not at least 1.5.
Generally, building something against a newer lib version but running it with an old one is always undefined behavior, and will crash (in the best case), and I don't see why mpv should behave differently, but I guess old nvidia drivers are a "good" argument for workarounds.

**Comment by ocu7** [comment]
I have read all the posts but I must confess I didn't understood that much. What should I do to get MPV Player working again? Is there maybe a possibility to revert to the previous version? Thanks for your help!

**Comment by wm4** [comment]
Building with --disable-egl-x11 will probably help.

**Comment by ocu7** [comment]
Should I get the new version in Linux Mint Updates or should I download it from somewhere else and install it from there? Sorry for my probably silly questions but i'm new to the linux world.

**Comment by mc4man** [comment]
To put straight - the build is not broken.
Ubuntu 18.04.x provides EGL 1.5, at least as determined by mpv.
The build log for package shows that  - Checking for EGL 1.5                                                      : yes
As does a current mpv source build on 18.04.1 image updated , no ppa's, no HWE packages - 
Checking for EGL 1.5                                                      : yes
Whether linux mint does no idea, the current min. (no HWE) mesa packages for 18.04  are
19.0.8-0ubuntu0~18.04.3 (bionic-updates)

**Comment by ocu7** [comment]
So what should I do then?

**Comment by wm4** [comment]
> To put straight - the build is not broken.

Yes, it's  "broken". If the EGL version the driver provides is 1.4, you need to build mpv against EGL 1.4 headers. A bit impractical if you want to make builds that work "everywhere" (complain to nvidia?), but I guess I'm not opposed to a workaround that would force it to use GLX, if it works.

> So what should I do then?

There doesn't seem to be quick solution, so revert to an old build/commit.

**Comment by mc4man** [comment]
@jeeb  Tested  patch as posted (didn't see commit stuff), tried with an install that I put 340 drivers on.
Seems to work fine in limited testing, both with or without hwdec (vdpau) log avail.
@ocu7 
If you wish to try see this ppa, full instructions on ppa page, read fully
https://launchpad.net/~mc3man/+archive/ubuntu/test1-build
Note that patch required mesa 19.2.x to compile..

**Comment by ocu7** [comment]
WOW! It works again.
@mc4man Thanks a lot man, you are a life saver. This is a big thing for me, because, as I said earlier, the only program that I can watch movies is MPV Player, the other just suck, and my main activity on PC is watching movies, so thank you for making that possible again. From now on, to be on the safe side, do you recommend to blacklist MPV Player, so that auto-update will not mess it up again, or from this PPA is safer to update?
I must confess I didn't understood much of discussion going on here but I want to thank all for the interest you have manifested.

**Comment by mc4man** [comment]
Accept any future updates from that ppa, you'll be fine..

**Comment by wm4** [comment]
Try #7207. It attempts to fix this correctly, but no idea if it actually is.
