### ISSUE TITLE
VAAPI not working since update

### ISSUE THREAD

**Issue by lk900** [mpv-player/mpv#7181]
Hi,

Since latest update running with HWDEC=VAAPI doesn't work. 

Lubuntu 18.04
Amd Ryzen 7 with Vega 10 GPU

VAINFO output:
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Mesa Gallium driver 19.2.0-devel for AMD RAVEN (DRM 3.33.0, 5.0.0-36-generic, LLVM 9.0.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc

### mpv version and platform

 mpv --version
mpv git-2019-11-17-a714ab0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Nov 23 14:58:36 UTC 2019
ffmpeg library versions:
   libavutil       56.36.100
   libavcodec      58.62.100
   libavformat     58.35.100
   libswscale      5.6.100
   libavfilter     7.66.100
   libswresample   3.6.100
ffmpeg version: git-2019-11-17-315a449

### Reproduction steps
 mpv --hwdec=vaapi test.mp4

### Expected behavior
Video to play
### Actual behavior
 mpv --hwdec=vaapi test.mp4
 (+) Video --vid=1 (*) (h264 720x400 23.976fps)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
File tags:

mesa: for the   --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the   --global-isel-abort option: may only occur zero or one times!
Cannot load libcuda.so.1
ac: Unknown GPU, using 0 for raster_config
Segmentation fault (core dumped)
[log.txt](https://github.com/mpv-player/mpv/files/3883649/log.txt)

**Comment by mc4man** [comment]
If not already try a reboot.
If no better I'd suggest building current mpv source locally, i.e using your installed libraries.
If it still fails on vaapi then some issue with your driver and mpv..
(- here have tested current mpv with all avail. mesa versions for 18.04.x (19.0.x, 19.2.x, 20.0.x) , see no issues whatsoever though can only test on Intel and Nvidia hardware.

**Comment by CounterPillow** [comment]
I own a Vega 10 laptop and vaapi works fine on it.

> Segmentation fault (core dumped)

A backtrace of this with debug symbols would be useful. Considering the last line in your log is about probing GPU interop with vdpau (all interops are probed regardless of which hwdec is set), my bet is on some vestigial broken vdpau thing on your system.

**Comment by barolo** [comment]
I'm also on RAVEN and there was this recently https://github.com/mpv-player/mpv/issues/7154 [ fixed in master ]
Also, why is it loading nvidia stuff?

**Comment by EinarMostad** [comment]
I have the same problem on Arch even after setting hwdec=vaapi in mpv.conf. My gpucontext=wayland and vo=gpu. I have also tried vo=gpu-hq with the same result. My vainfo gives me this:
vainfo: VA-API version: 1.11 (libva 2.11.1)
vainfo: Driver version: Mesa Gallium driver 21.0.3 for AMD Radeon(TM) Vega 10 Graphics (RAVEN, DRM 3.40.0, 5.11.16-arch1-1, LLVM 11.1.0)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc

There is also a Reddit thread about this problem when using Intel graphics, so it does not seem to be hardware specific: https://www.reddit.com/r/archlinux/comments/lz9p1u/mpv_says_cannot_load_libcudaso1_when_watching_a/

**Comment by CounterPillow** [comment]
@EinarMostad, this is expected. It still needs to probe the hwdec<->gpu interop to use, which includes an attempt to load cuda. This error message is of no consequence, and expected.

**Comment by EinarMostad** [comment]
Thank you for the explanation! I am sorry for wasting your time by not understanding how this works.

**Comment by CounterPillow** [comment]
It's okay, my post probably came across as a bit more aggressive/annoyed than I intended. We could add some code to try and make warnings during probing less prominent (e.g. only appear in log files or with `-v`), but I haven't looked into how much additional complexity this would add for basically just a non-issue.

**Comment by EinarMostad** [comment]
No problem. I did not read you as aggressive. Maybe a fix is to add something to the man page that makes it clear that this output is expected and why.

**Comment by Dudemanguy** [comment]
The original poster did not reply but VAAPI should certainly work + it's an old issue.
