### ISSUE TITLE
RAR playback is slow to the point of being useless in 0.30.0

### ISSUE THREAD

**Issue by 5t3f4n** [mpv-player/mpv#7182]
### mpv version and platform
0.30.0 on macOS 10.15.1

### Reproduction steps
Open RAR file(s) (with video inside obviously)

### Expected behavior
Instant playback.
Seeking works.

### Actual behavior
Takes anywhere between a couple seconds to a full minute to start playing.
Seeking doesn't work half the time.

In my highly unscientific testing it seems the problem is worst on X265/UHD movies but it could have to do with the size/resolution of the movie as well, not sure. Or purely coincidental.

Can you please revert to the previous RAR solution you had which was instant and flawless 100% of the time? The new implementation is so slow I don't see the point in having it at all. Might as well just use UnRAR first then play it back.

**Comment by jeeb** [comment]
1. Please verify which version of libarchive is being utilized by your binary.
2. Please post a log file from `--log-file=mpv.log`

Before the copied-from-Videolan implementation was removed, I had indeed heard good things about the internal implementation compared to libarchive. That said, if it is possible to see this improved from libarchive's side I'd definitely prefer that :) .

**Comment by Akemi** [comment]
before something is blindly reverted, it's better to actually find the offending commit or change instead and go on from that point. also you shouldn't omit the log file.

**Comment by jeeb** [comment]
Or an alternative is that in both cases (the old and new version of mpv build you have) libarchive is utilized, but the version is different and the performance went down.

@5t3f4n , can you verify the version of libarchive utilized before (since the libarchive module was there before, too) and possibly get a log for comparison from there, too?

**Comment by wm4** [comment]
> The new implementation is so slow I don't see the point in having it at all. Might as well just use UnRAR first then play it back.

Yes, do that, or nag the libarchive devs about it (they won't fix it though).

**Comment by 5t3f4n** [comment]
https://pastebin.com/raw/XG74Xtmt

**Comment by 5t3f4n** [comment]
> Yes, do that, or nag the libarchive devs about it (they won't fix it though).

Why switch to this solution if you know the devs are stubborn and won't fix it?

**Comment by wm4** [comment]
The old implementation did not support compressed rar, and was even less maintained than libarchive. libarchive is maintained and supports more formats. This should not be hard to understand.

**Comment by 5t3f4n** [comment]
If the old solution already worked perfectly it doesn't matter how maintained it is. But I can see supporting compressed RAR is good. But can't we have have the best of both worlds then? Use old solution for uncompressed RAR only.

**Comment by jeeb** [comment]
Also can we just verify that indeed the internal RAR reader was utilized in the older binary you were utilizing?

Before, like, jumping too far into conclusions.

**Comment by 5t3f4n** [comment]
https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-0.29.1.tar.gz

Here is the build I used previously which worked fine.
I do not know how to check what RAR reader it has.

**Comment by jeeb** [comment]
You can just similarly do `--log-file=mpv.log`.

Anyways, what seems to take long now is to read the seeking cues from the end of the Matroska file. What seems to happen is:
1. We attempt to seek to that point with libarchive.
2. libarchive tells us we failed to seek.
3. Our libarchive module goes _"Oh well, this sucks. I guess I have to start reading A->B"_.
4. We use ~5 seconds to read through the contents of all those parts.

**Comment by 5t3f4n** [comment]
The current version has something called libarchive.13.dylib inside its lib folder. Previous version doesn't have that at all.

But also I noticed something weird in the log.
It says it cannot find can't find/open the .r75 file but the archive doesn't have an .r75 file.
It seems to always do this. Tried a couple more and it always fails on n+1 file. Does it not know beforehand how many parts there is? Does it just do +1 until it fails?

**Comment by mac010** [comment]
Same issue here too

Also maybe worth mentioning vast majority of rar'd videos found online won't have compressed rars (as this is not allowed by groups who share videos like this).

**Comment by mac010** [comment]
Just noticed this is closed?
This is a really important feature for lots of us, if there is anyway this could be fixed would  be amazing! I dont want to go back to VLC =-(

**Comment by Hrxn** [comment]
Never heard of that before, to be honest. Where would one find such rar'd videos? Is that really a thing?

**Comment by wm4** [comment]
What's wrong with extracting the damn file?
Also tell the idiots who produce such files to fuck themselves.

**Comment by garoto** [comment]
> Is that really a thing?

https://scenerules.org/n.html?id=2011_X264.2.nfo

**Comment by wm4** [comment]
It makes me happy that at least some of them might go to prison for doing that.
Fucking idiots and their bullshit rules.

**Comment by garoto** [comment]
File spliting rules served a very specific purpose for the longest time.

**Comment by garoto** [comment]
@wm4 Would you give it some thought about the removal of the exclusive RAR demuxer if I take my time and open a well documented issue with plenty of logs and with full samples demonstrating how `libarchive` is not a decent alternative when dealing with (old and new) uncompressed RARs of any sort?

**Comment by wm4** [comment]
>open a well documented issue with plenty of logs and with full samples demonstrating how libarchive is not a decent alternative when dealing with (old and new) uncompressed RARs of any sort?

What would that help? We already know this.

**Comment by garoto** [comment]
Well, the issues I've seen lately dealing with libarchive+RARs are below par in detailing things.

**Comment by garoto** [comment]
I mean, if the old RAR C code becomes rot due to lack of maintenance, so be it, right?

**Comment by wm4** [comment]
Get me a library that handles rar better (since libarchive's rar support is beyond terrible anyway), and the problem would be solved.

**Comment by Argon-** [comment]
What about asking libarchive to improve their rar support?

**Comment by garoto** [comment]
> Get me a library that handles rar better [...]

Does it need to be a library? The removed mpv RAR demuxer C code was working more than "just fine", it was pretty much flawless as far as I was able to test it. It worked even better than the ancient but excellent "DirectShow" RAR demuxer by OctaneSnail (https://github.com/mirror/rarfilesource).

> What about asking libarchive to improve their rar support?

When `libarchive` was made the default lib for all compressed material in `mpv` , I started following their repo to get a general feel of it (before filing an issue and whatnot) , and well, it's obvious those dudes have zero interest in anything RAR. I'm not a programmer, but from the many issues I've read there, it seems like a huge mess.

**Comment by Hrxn** [comment]
> What about asking libarchive to improve their rar support?

> > The new implementation is so slow I don't see the point in having it at all. Might as well just use UnRAR first then play it back.
> 
> Yes, do that, or nag the libarchive devs about it (they won't fix it though).

¯\\_(ツ)_/¯

> https://scenerules.org/n.html?id=2011_X264.2.nfo

Ah, those old rules. But you're right, they exist for historic reasons and for dealing with technical limitations etc. 
But the question still stands, they are packed for transmission, but why not simply extract the files on the end-user side? What are the benefits for keeping them as RAR, there's no storage capacity to save for personal archiving?

**Comment by wm4** [comment]
@garoto only something that has better compressed rar support than libarchive, otherwise it's pointless.

**Comment by mac010** [comment]
> > What about asking libarchive to improve their rar support?
> 
> > > The new implementation is so slow I don't see the point in having it at all. Might as well just use UnRAR first then play it back.
> > 
> > 
> > Yes, do that, or nag the libarchive devs about it (they won't fix it though).
> 
> ¯\_(ツ)_/¯
> 
> > https://scenerules.org/n.html?id=2011_X264.2.nfo
> 
> Ah, those old rules. But you're right, they exist for historic reasons and for dealing with technical limitations etc.
> But the question still stands, they are packed for transmission, but why not simply extract the files on the end-user side? What are the benefits for keeping them as RAR, there's no storage capacity to save for personal archiving?

The volume this happens in is immense, the archives some people/sites must have nowadays must be giant (as historically those who collected and shared this way stored a lot lot more data than Bob P2P did).

Reasons for keeping RAR's:
- To retain in original format with nfo file and checksums (there is historic value in in these now, like old comics or whatever).
- To reshare in original format.
- The shear immense task of extracting on mass scale (reason rescene isn't used by many).

If you ever downloaded and watched a movie that wasn't available where you live, half chance it came from a group who does things this way.

**Comment by mac010** [comment]
> @garoto only something that has better compressed rar support than libarchive, otherwise it's pointless.

I visited the MPV IRC channel the last time RAR playback broke, and you guys promised to retain support =-(

**Comment by wm4** [comment]
> I visited the MPV IRC channel the last time RAR playback broke, and you guys promised to retain support =-(

rar playback still works and always did.

I tried to improve it a bit. It probably makes it a bit better, but libarchive still seems to insist on opening all volumes before even returning control to the API user. You are thus fucked.

**Comment by wm4** [comment]
And here's my answer for all future questions about this: https://github.com/mpv-player/mpv/wiki/FAQ#What_is_the_rar_file_format_and_why_is_it_stupid

**Comment by wm4** [comment]
Reported some libarchive bugs.
I will now ignore anything related to this, unless libarchive bother with improving their support.
Another possibility is if someone finds or writes a library specifically for rar support. It should provide a libarchive-like interface (see mpv stream/stream_libarchive.c). This could use the source dump by rarlabs too, though that would have to be modified to support I/O callbacks, and would ahve to be dlopen'ed for license reasons.

**Comment by wm4** [comment]
I was able to prevent the opening of all rar volumes on opening (see commit above). This works only if the demuxer does not seek (for many sub-optimally muxed mkv/mp4 files it will still seek to the end, and open all volumes while doing so). User initiated seeking might also trigger something like this.

Not sure if this brings the level of rar support back to pre-0.30.0, but it should be much better now in git master.

**Comment by wm4** [comment]
Add https://github.com/libarchive/libarchive/issues/1321 to the list of problems.
