### ISSUE TITLE
Hardware decoding not working with NVIDIA/VDPAU/Linux in mpv 0.30.0

### ISSUE THREAD

**Issue by birdie-github** [mpv-player/mpv#7183]
### mpv version and platform
0.30.0, Fedora 30 64
### Reproduction steps
mpv --hwdec=vdpau any H.264 video
### Expected behavior
HW decoding enabled via VDPAU
### Actual behavior
Software decoding
### Log file
mpv 0.29.1 log: [29.txt](https://github.com/mpv-player/mpv/files/3883978/29.txt) **(works)**
mpv 0.30.0 log: [30.txt](https://github.com/mpv-player/mpv/files/3883979/30.txt) **(doesn't)**
### Sample files
Any H.264 will do.

Also, there's literally nothing about NVIDIA in [your wiki](https://github.com/mpv-player/mpv/wiki/Hardware-decoding-on-Linux). Has NVIDIA hardware decoding been removed/deprecated/whatever? Why?

**Comment by jeeb** [comment]
1. The default for X11 contexts got switched from GLX (`gpu-context=x11`) to EGL (`gpu-context=x11egl`).
2. This was to enable more hardware decoding APIs to work (nvidia's nvdec and AMD/intel VAAPI)
3. For these newer nvidia chipsets we recommend nvdec to vdpau. That also works by default with EGL. This does require both FFmpeg and mpv to be built with nvdec, though. You can see if you have it by checking the list `--hwdec=help`.
4. If you really need to utilize VDPAU for now, `gpu-context=x11` is a workaround.

**Comment by wm4** [comment]
Use --hwdec=auto. Select anything else, and you have to know what you're doing, as indicated in the manpage.

**Comment by birdie-github** [comment]
With --hwdec=auto HW decoding of H.264 videos work however it doesn't work for VP9 videos:

```
[vaapi] libva: va_getDriverName() failed with unknown libva error,driver_name=(null)
[ffmpeg/video] vp9_v4l2m2m: Could not find a valid device
[ffmpeg/video] vp9_v4l2m2m: can't configure decoder
Could not open codec.
```

```
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Resizing texture: 16x16
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Assuming 60.000000 FPS for display sync.
[vd] Container reported FPS: 30.000000
[vd] Codec list:
[vd]     vp9 - Google VP9
[vd]     vp9_v4l2m2m (vp9) - V4L2 mem2mem VP9 decoder wrapper
[vd] Opening decoder vp9
[vd] Looking at hwdec vp9-vaapi...
[vo/gpu] Loading hwdec driver 'vaapi-egl'
[vo/gpu/vaapi-egl] VAAPI hwdec only works with OpenGL or Vulkan backends.
[vo/gpu] Loading failed.
[vo/gpu] Loading hwdec driver 'vdpau-glx'
[vo/gpu] Loading failed.
[vo/gpu] Loading hwdec driver 'drmprime-drm'
[vo/gpu/drmprime-drm] Failed to retrieve DRM fd from native display.
[vo/gpu] Loading failed.
[vd] Could not create device.
[vd] Looking at hwdec vp9-vaapi-copy...
[vaapi] libva: VA-API version 1.6.0
[vaapi] libva: va_getDriverName() returns -1
[vaapi] libva: va_getDriverName() failed with unknown libva error,driver_name=(null)
[vd] Could not create device.
[vd] Looking at hwdec vp9_v4l2m2m-v4l2m2m-copy...
[vd] Trying hardware decoding via vp9_v4l2m2m-v4l2m2m-copy.
[vd] Using underlying hw-decoder 'vp9_v4l2m2m'
[ffmpeg/video] vp9_v4l2m2m: driver 'uvcvideo' on card 'UVC Camera (046d:081d)'
[ffmpeg/video] vp9_v4l2m2m: driver 'uvcvideo' on card 'UVC Camera (046d:081d)'
[ffmpeg/video] vp9_v4l2m2m: Could not find a valid device
[ffmpeg/video] vp9_v4l2m2m: can't configure decoder
[vd] Could not open codec.
[vd] Falling back to software decoding.
[vd] Detected 16 logical cores.
[vd] Requesting 16 threads for decoding.
[vd] Selected codec: vp9 (Google VP9)
[vf] User filter list:
[vf]   (empty)
```

**Comment by wm4** [comment]
Your build doesn't include the nvidia hardware decoder support (cuda/nvcodec).

**Comment by birdie-github** [comment]
Can't VPDAU be used for this like it's already used (and working) for H.264/H.265 videos? I don't see how VP9 is different from other codecs in this regard.

**Comment by birdie-github** [comment]
@Akemi @wm4 

Can't VPDAU be used for this like it's already used (and working) for H.264/H.265 videos? I don't see how VP9 is different from other codecs in this regard.

**Comment by jeeb** [comment]
Please read my initial comment.

**Comment by wm4** [comment]
> In general I would recommend you push your distribution towards enabling nvdec in FFmpeg/mpv and thus you get not only EGL support, but also such features quicker.

Yes, that's what we generally expect for "full" builds. It's not hard either, it just requires the ffmpeg nv headers repo (you don't need to install the nvidia cuda SDK or whatever stupid thing there is).

**Comment by philipl** [comment]
Assuming you are correcting using the GLX api context, then the problem indicates that your libvdpau is too told (and not exposing the vp9 support - either at runtime or at ffmpeg build time) or the files is not an 8bit vp9 file (10bit is not supported by vdpau).

**Comment by birdie-github** [comment]
For VP9 HW decoding using VDPAU a GIT version of ffmpeg is currently required.

ffmpeg 4.2.1 does **not** support it.
