### ISSUE TITLE
OSD font size increased in mpv 0.30.0 despite no changes in config/system

### ISSUE THREAD

**Issue by birdie-github** [mpv-player/mpv#7184]
### mpv version and platform
0.30.0 Fedora 31

Looks like mpv 0.30.0 now renders OSD fonts differently (they look twice as big). According to logs everything is the same:

0.29.1:
```
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] fontselect: (Tahoma, 400, 0) -> /usr/share/fonts/tahoma.ttf, 0, Tahoma
```

0.30.0
```
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] fontselect: (Tahoma, 400, 0) -> /usr/share/fonts/tahoma.ttf, 0, Tahoma
```

How can I get the old fonts sizes back?

Example:

0.29.1:
![0 29 1](https://user-images.githubusercontent.com/4958603/69499642-22f87380-0eec-11ea-9161-cac103344782.png)

0.30.0:
![0 30 0](https://user-images.githubusercontent.com/4958603/69499644-22f87380-0eec-11ea-8bae-4af83dea2741.png)

**Comment by sfan5** [comment]
The font was changed in cb51dfa76a8, this is not a bug.

**Comment by birdie-github** [comment]
I have `osd-font = Tahoma` specified in my config :(

**Comment by birdie-github** [comment]
@sfan5 

I have `osd-font = Tahoma` specified in my config :(

I have also tried specifying osd-font-size but that didn't have any effect.

**Comment by Akemi** [comment]
you have to change the font of the [stats](https://github.com/mpv-player/mpv/blob/master/DOCS/man/stats.rst).

**Comment by birdie-github** [comment]
```
cat ~/.mpv/script-opts/stats.conf 
font = Tahoma
font_size = 8
```
mpv log:

[stats] script-opts/stats.conf:1 unknown key font , ignoring 
[stats] script-opts/stats.conf:2 unknown key font_size , ignoring 

@Akemi 
@sfan5

**Comment by sfan5** [comment]
<pre>
font=Tahoma
font_size=8
</pre>
Do not put spaces inbetween.
