### ISSUE TITLE
Seeking in broken(?) streams occasionally crashes with nvdec

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#7185]
### mpv version and platform

<pre>
mpv 0.30.0-140-gdcc3c2eb38 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
</pre>

### Reproduction steps

1. Seek forwards and backwards in bluray randomly
The suspicion here is that this is not related to bluray, but rather to the broken stream mpv sees when seeking.

### Expected behavior

2. Hwdec works, or it doesn't and falls back to software.

### Actual behavior

2. Assertion failure.
<pre>mpv: ../video/decode/vd_lavc.c:1059: decode_frame: Assertion `mpi->planes[0] || mpi->planes[3]' failed.</pre>

### Log file

[mpv logfile](https://github.com/mpv-player/mpv/files/3887564/repro.txt)

[backtrace](https://github.com/mpv-player/mpv/files/3887567/bt.txt)

### Sample files

Irrelevant(?) and hard to provide anyway

**Comment by wm4** [comment]
Need to find out whether mpv's logic is broken, or libavcodec's. If it's the latter, it returns a "successfully" decoded frame that has no plane pointers, which is not allowed.
Try with git master in any case.

**Comment by philipl** [comment]
I can't trivially reproduce. This is an m2ts file loaded directly? the bluray:// demuxer? Are you using a non-keyframe seek?

**Comment by wm4** [comment]
Yeah, seeking via bluray:// could be rather different from seeking in a file, and for example might restart decoding on weird boundaries.

**Comment by sfan5** [comment]
The exact steps were these:
1. `mpv --no-config --hwdec=nvdec <path to a bluray folder structure>` (will use the bluray demuxer)
2. hold down mouse and keep dragging the seekbar back and forth

I've tried this a few times, it can take multiple minutes until something actually happens and in 5/6 cases it correctly falls back to software decoding.

**Comment by philipl** [comment]
I tried it for a while here without triggering a software fallback. There's a lot of unhappiness from both the video and audio decoders because it's seeking into the middle of packets, but ultimately, it's not managing to trigger any hwdec problem.

Seems like we should be making the bluray seek keyframe aligned independent of anything else. Is that hard? I've never looked at any of this code.

**Comment by wm4** [comment]
It's using libbluray's seek-by-time function. That's it. As of recently, the demuxer may also have some data or packets from before the seek.

**Comment by wm4** [comment]
I think we determined that this is a libavcodec problem. Basically it violates its own API. We could special-case it and add a fallback for this case, but I think it's better to fix this in libavcodec. (Checking whether this case happens and returning an error if it does, all in libavcodec, would be sufficient.)
