### ISSUE TITLE
Seeking in an audio file whose size has been altered triggers a timeout every time

### ISSUE THREAD

**Issue by ripdog** [mpv-player/mpv#7187]
### mpv version and platform

mpv-dev-x86_64-20191124-git-b31f2f6.7z

This is the windows library build from sourceforge.

### Reproduction steps

I'm using the python bindings to mpv-1.dll. My application downloads songs from a web server to the filesystem. After enough bytes are downloaded, the file path is sent to MPV to play. This works fine. However, for the entirety of the playback of that song, mpv will enter a timeout when a seek is requested. mpv generally reports

>warn file File is apparently being appended to, will keep retrying with timeouts.

most times a seek is requested. There is then a timeout of about 4 seconds, making seeking a confusing and unpleasant experience for the user. Note that this continues to happen long after the song is complete on disk. The download completes with 5-10s in my setup.

### Expected behavior

Ideally I'd like some way to control the behaviour around file writing detection. For example, a command to tell MPV that the file is now complete, so perhaps after receiving that command, mpv could reread parts (?) of the file to enable normal seek behaviour and also to remove the timeout which happens at the end of the track.

Obviously I don't know if I'm asking something reasonable, so I hope you can advise me on my options. Many thanks for your attention.

(If there's no path forward here, I guess I could provide the URLs directly to mpv - but then caching would become impossible, offline playback would disappear and gapless playback would (presumably) no longer work. Unless there could be a way to extract the streamed song data from mpv? Heh :))

**Comment by wm4** [comment]
Trying to play a growing file isn't sane. A demuxer would encounter packets that are cut off all the time (unless you disable caching). The heuristic that detects appended files simply waits if the demuxer tries to read a part of the file that doesn't exist yet.

You can
1. Copy the file instead passing it directly
2. Play the URL directly and use mpv's stream recording to write it
3. Use the stream_cb API to get full control over input
4. Set the demuxer cache large enough so seeks within cached regions will not trigger I/O (in case the seeks you're talking about are the demuxer trying to read the non-existing end of the file or so)

**Comment by ripdog** [comment]
@wm4, thank you for your reply. I appreciate it. Disabling the cache seems to have fixed seeking reliably(?). However, there is still a 'file appended' timeout at the end of the track, even though it's long since complete. A configuration option for mpv to stop those timeouts unconditionally would be fantastic.

>Copy the file instead passing it directly

Can you be more specific? I'm not sure what you mean.

>Use the stream_cb API to get full control over input

This sounds ideal to me, but I'm a braindead programmer who can't grok C. If the kind soul who develops python-mpv implemented this, I'd be set...

>Play the URL directly and use mpv's stream recording to write it

I investigated this, thanks for the tip. It seems to work fine, but I wouldn't have a reliable way to change the recording filename if I used mpv's playlist. I'd have to take over playlist functionality myself, leading to presumably even longer delays between songs...
