### ISSUE TITLE
Show OSC when seeking

### ISSUE THREAD

**Issue by tonycpsu** [mpv-player/mpv#7189]
### mpv version and platform

git master (7c65704)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

With an out-of-box mpv config, moving the mouse shows/hides the OSC, but seek commands don't.  I'm aware that input command prefixes (osd-bar, no-osd, etc.) can affect whether the OSD appears, but I'm not aware of any solution for the OSC.  As a stopgap, I'd be fine with a config/script-based solution (if one exists), but I feel like the OSC should have an option for "auto" visibility to be triggered on both mouse moves and keybindings (at least ones that affect the seek position.)

**Comment by Akemi** [comment]
duplicate #3826.
