### ISSUE TITLE
Failed to open certain mp4 file

### ISSUE THREAD

**Issue by iamCristYe** [mpv-player/mpv#7190]
### mpv version and platform
latest, Windows 10

### Reproduction steps
Open attached file

### Log file
(attached)

### Sample files
(attached)

[test.zip](https://github.com/mpv-player/mpv/files/3895012/test.zip)

**Comment by Akemi** [comment]
that seems suspicious:

```
[   2.869][f][vo/gpu/d3d11] Couldn't resize swapchain: GPU …Ë±∏ µ¿˝“—æ≠‘›Õ£°£ π”√ GetDeviceRemovedReason “‘»∑∂®œ‡”¶µƒ¥Î ©°£ (0x887a0005)
```

also don't ignore the issue template. at least write the actual behaviour down. since the file works here and it doesn't fail to open the file (in your case) as far as i can see.

**Comment by iamCristYe** [comment]
> that seems suspicious:
> 
> ```
> [   2.869][f][vo/gpu/d3d11] Couldn't resize swapchain: GPU …Ë±∏ µ¿˝“—æ≠‘›Õ£°£ π”√ GetDeviceRemovedReason “‘»∑∂®œ‡”¶µƒ¥Î ©°£ (0x887a0005)
> ```
> 
> also don't ignore the issue template. at least write the actual behaviour down. since the file works here and it doesn't fail to open the file (in your case) as far as i can see.
> 
> [edit]
> it fails at the swap chain resize. might be worth trying a different GPU context, eg opengl, for testing.

Thanks for your quick reply.
Sorry for not writing down the actual behaviour: sometimes mpv doesn't show window but sound goes on, sometimes mpv shows but there'e no video.

Also, after deleting hwdec=auto in config file, the file is ok to open. As this my related to hwdec, I can provide more info about my hardware:
[DxDiag.txt](https://github.com/mpv-player/mpv/files/3895663/DxDiag.txt)

**Comment by rossy** [comment]
The error is DXGI_ERROR_DEVICE_REMOVED, which probably means something to do with hwdec is making the graphics drivers crash. Make sure your drivers are up to date. You could try going directly to Intel's site for new drivers, though that doesn't always work, since some laptop vendors make it hard to replace the vendor drivers with generic drivers.

We should also probably fix how that error message is logged.
