### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by icebluey** [mpv-player/mpv#7191]
### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it. If the issue is a build failure, upload build/config.log instead.

If this is a normal runtime bug, and no log is provided, the issue will be
closed for ignoring the issue template. This is because analyzing a bug without
a log file is harder than necessary. Low quality bug reports are noise.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

./waf configure
'configure' finished successfully (3.928s)

./waf -v build
[216/216] Linking build/mpv
20:35:41 runner ['/usr/bin/cc', '-rdynamic', '-Wl,-z,noexecstack', '-pthread', '-rdynamic', '-Wl,-version-script', '-Wl,mpv.def', 'osdep/main-fn-unix.c.20.o', 'audio/aframe.c.19.o', 'audio/audio_buffer.c.19.o', 'audio/chmap.c.19.o', 'audio/chmap_sel.c.19.o', 'audio/decode/ad_lavc.c.19.o', 'audio/decode/ad_spdif.c.19.o', 'audio/filter/af_format.c.19.o', 'audio/filter/af_lavcac3enc.c.19.o', 'audio/filter/af_scaletempo.c.19.o', 'audio/fmt-conversion.c.19.o', 'audio/format.c.19.o', 'audio/out/ao.c.19.o', 'audio/out/ao_lavc.c.19.o', 'audio/out/ao_null.c.19.o', 'audio/out/ao_oss.c.19.o', 'audio/out/ao_pcm.c.19.o', 'audio/out/ao_pulse.c.19.o', 'audio/out/pull.c.19.o', 'audio/out/push.c.19.o', 'common/av_common.c.19.o', 'common/av_log.c.19.o', 'common/codecs.c.19.o', 'common/common.c.19.o', 'common/encode_lavc.c.19.o', 'common/msg.c.19.o', 'common/playlist.c.19.o', 'common/recorder.c.19.o', 'common/tags.c.19.o', 'common/version.c.19.o', 'demux/codec_tags.c.19.o', 'demux/cue.c.19.o', 'demux/cache.c.19.o', 'demux/demux.c.19.o', 'demux/demux_cue.c.19.o', 'demux/demux_disc.c.19.o', 'demux/demux_edl.c.19.o', 'demux/demux_lavf.c.19.o', 'demux/demux_mf.c.19.o', 'demux/demux_mkv.c.19.o', 'demux/demux_mkv_timeline.c.19.o', 'demux/demux_null.c.19.o', 'demux/demux_playlist.c.19.o', 'demux/demux_raw.c.19.o', 'demux/demux_timeline.c.19.o', 'demux/ebml.c.19.o', 'demux/packet.c.19.o', 'demux/timeline.c.19.o', 'filters/f_autoconvert.c.19.o', 'filters/f_auto_filters.c.19.o', 'filters/f_decoder_wrapper.c.19.o', 'filters/f_demux_in.c.19.o', 'filters/f_hwtransfer.c.19.o', 'filters/f_lavfi.c.19.o', 'filters/f_output_chain.c.19.o', 'filters/f_swresample.c.19.o', 'filters/f_swscale.c.19.o', 'filters/f_utils.c.19.o', 'filters/filter.c.19.o', 'filters/frame.c.19.o', 'filters/user_filters.c.19.o', 'input/cmd.c.19.o', 'input/event.c.19.o', 'input/input.c.19.o', 'input/ipc.c.19.o', 'input/ipc-unix.c.19.o', 'input/keycodes.c.19.o', 'misc/bstr.c.19.o', 'misc/charset_conv.c.19.o', 'misc/dispatch.c.19.o', 'misc/json.c.19.o', 'misc/natural_sort.c.19.o', 'misc/node.c.19.o', 'misc/rendezvous.c.19.o', 'misc/ring.c.19.o', 'misc/thread_pool.c.19.o', 'misc/thread_tools.c.19.o', 'options/m_config.c.19.o', 'options/m_option.c.19.o', 'options/m_property.c.19.o', 'options/options.c.19.o', 'options/parse_commandline.c.19.o', 'options/parse_configfile.c.19.o', 'options/path.c.19.o', 'player/audio.c.19.o', 'player/client.c.19.o', 'player/command.c.19.o', 'player/configfiles.c.19.o', 'player/external_files.c.19.o', 'player/loadfile.c.19.o', 'player/main.c.19.o', 'player/misc.c.19.o', 'player/osd.c.19.o', 'player/playloop.c.19.o', 'player/screenshot.c.19.o', 'player/scripting.c.19.o', 'player/sub.c.19.o', 'player/video.c.19.o', 'stream/cookies.c.19.o', 'stream/stream.c.19.o', 'stream/stream_avdevice.c.19.o', 'stream/stream_cb.c.19.o', 'stream/stream_concat.c.19.o', 'stream/stream_edl.c.19.o', 'stream/stream_file.c.19.o', 'stream/stream_lavf.c.19.o', 'stream/stream_memory.c.19.o', 'stream/stream_mf.c.19.o', 'stream/stream_null.c.19.o', 'sub/ass_mp.c.19.o', 'sub/dec_sub.c.19.o', 'sub/draw_bmp.c.19.o', 'sub/filter_sdh.c.19.o', 'sub/img_convert.c.19.o', 'sub/lavc_conv.c.19.o', 'sub/osd.c.19.o', 'sub/osd_libass.c.19.o', 'sub/sd_ass.c.19.o', 'sub/sd_lavc.c.19.o', 'video/csputils.c.19.o', 'video/decode/vd_lavc.c.19.o', 'video/filter/refqueue.c.19.o', 'video/filter/vf_fingerprint.c.19.o', 'video/filter/vf_format.c.19.o', 'video/filter/vf_sub.c.19.o', 'video/filter/vf_vdpaupp.c.19.o', 'video/fmt-conversion.c.19.o', 'video/hwdec.c.19.o', 'video/image_loader.c.19.o', 'video/image_writer.c.19.o', 'video/img_format.c.19.o', 'video/mp_image.c.19.o', 'video/mp_image_pool.c.19.o', 'video/out/aspect.c.19.o', 'video/out/bitmap_packer.c.19.o', 'video/out/dither.c.19.o', 'video/out/dr_helper.c.19.o', 'video/out/drm_atomic.c.19.o', 'video/out/drm_common.c.19.o', 'video/out/drm_prime.c.19.o', 'video/out/filter_kernels.c.19.o', 'video/out/gpu/context.c.19.o', 'video/out/gpu/error_diffusion.c.19.o', 'video/out/gpu/hwdec.c.19.o', 'video/out/gpu/lcms.c.19.o', 'video/out/gpu/libmpv_gpu.c.19.o', 'video/out/gpu/osd.c.19.o', 'video/out/gpu/ra.c.19.o', 'video/out/gpu/shader_cache.c.19.o', 'video/out/gpu/spirv.c.19.o', 'video/out/gpu/user_shaders.c.19.o', 'video/out/gpu/utils.c.19.o', 'video/out/gpu/video.c.19.o', 'video/out/gpu/video_shaders.c.19.o', 'video/out/opengl/common.c.19.o', 'video/out/opengl/context.c.19.o', 'video/out/opengl/context_glx.c.19.o', 'video/out/opengl/context_x11egl.c.19.o', 'video/out/opengl/egl_helpers.c.19.o', 'video/out/opengl/formats.c.19.o', 'video/out/opengl/hwdec_drmprime_drm.c.19.o', 'video/out/opengl/hwdec_vdpau.c.19.o', 'video/out/opengl/libmpv_gl.c.19.o', 'video/out/opengl/oml_sync.c.19.o', 'video/out/opengl/ra_gl.c.19.o', 'video/out/opengl/utils.c.19.o', 'video/out/vo.c.19.o', 'video/out/vo_drm.c.19.o', 'video/out/vo_gpu.c.19.o', 'video/out/vo_image.c.19.o', 'video/out/vo_lavc.c.19.o', 'video/out/vo_libmpv.c.19.o', 'video/out/vo_null.c.19.o', 'video/out/vo_tct.c.19.o', 'video/out/vo_vdpau.c.19.o', 'video/out/vo_x11.c.19.o', 'video/out/vo_xv.c.19.o', 'video/out/win_state.c.19.o', 'video/out/x11_common.c.19.o', 'video/sws_utils.c.19.o', 'video/zimg.c.19.o', 'video/vdpau.c.19.o', 'video/vdpau_mixer.c.19.o', 'osdep/terminal-unix.c.19.o', 'osdep/io.c.19.o', 'osdep/threads.c.19.o', 'osdep/timer.c.19.o', 'osdep/timer-linux.c.19.o', 'osdep/polldev.c.19.o', 'osdep/path-unix.c.19.o', 'osdep/semaphore_osx.c.19.o', 'osdep/subprocess.c.19.o', 'osdep/subprocess-posix.c.19.o', 'ta/ta.c.19.o', 'ta/ta_talloc.c.19.o', 'ta/ta_utils.c.19.o', '-o/tmp/mpv/build/mpv', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-llcms2', '-lavcodec', '-lpulse', '-lXv', '-lzimg', '-lrt', '-lEGL', '-ldrm', '-lm', '-ldl', '-lavdevice', '-lvdpau', '-lavutil', '-lavcodec', '-lavformat', '-lswscale', '-lavfilter', '-lswresample', '-lavutil', '-lz', '-lX11', '-lXss', '-lXext', '-lXinerama', '-lXrandr', '-lGL', '-lass']

video/out/opengl/context_x11egl.c.19.o: In function `mpegl_init':

/tmp/mpv/build/../video/out/opengl/context_x11egl.c:107: undefined reference to `eglGetPlatformDisplay'

collect2: error: ld returned 1 exit status

Waf: Leaving directory `/tmp/mpv/build'
Build failed
 -> task in 'mpv' failed with exit status 1:

**Comment by CounterPillow** [comment]
Please provide your `build/config.log`.

The problem likely is that your graphics driver does not provide EGL 1.5. We should be checking for this to avoid build failures (it seems like the check is broken for you, so we need to know why it is broken), but in the meantime you can try building with `--disable-egl15`.

**Comment by icebluey** [comment]
[config.log](https://github.com/mpv-player/mpv/files/3898875/config.log)

./waf configure
...
Checking for EGL 1.5      : yes
...

It's weird.

**Comment by wm4** [comment]
Seems like headers are EGL 1.5, but libs are EGL 1.4.

**Comment by CounterPillow** [comment]
You apparently have a `/usr/include/libdrm/EGL/egl.h` that defines `EGL_VERSION_1_5`, but the library it picks up from your system do not match this header.

My guess is that you're on an old nvidia GPU for which nvidia has stopped updating their drivers, and you have some other driver's dev headers installed (your package manager should be able to tell you what package owns that file).

**Comment by wm4** [comment]
> /usr/include/libdrm/EGL/egl.h

Should be just /usr/include/EGL/egl.h.

**Comment by CounterPillow** [comment]
According to the config.log:
```
Checking for EGL 1.5
['/usr/bin/pkg-config', 'egl', '--libs', '--cflags', 'egl']
out: -I/usr/include/libdrm -lEGL
```

Am I misinterpreting why pkg-config is outputting a `-I` here? (It doesn't for me)

**Comment by wm4** [comment]
It does it for me too. No idea why. It would make sense if the EGL headers included DRM headers recursively, but they don't. Either this is a mistake, or Mesa somehow expects that clients messing with DRM is a common use case or so?

**Comment by mc4man** [comment]
Your waf configure is checking via .pc files so it found the system 'egl' which was 1.5, ect.
However you likely have a legacy nvidia driver install which installs some of it's own libs inc libEGL.so files and at least here diversions are created to these nvidia installed files.
So you'll pass the configure but fail the build.
So get newer drivers/hardware, or maybe configure out egl or just use the 0.30 release.

The cflag to libdrm is expected as libdrm is listed on the Requires.private: line in egl.pc

**Comment by icebluey** [comment]
Maybe should check .h files and .so files both to determine if EGL 1.5 available.

**Comment by Akemi** [comment]
if the problem still persists please open a new issue.
