### ISSUE TITLE
inserting a GPU-shader into mpv's encoding pipeline 

### ISSUE THREAD

**Issue by grill05** [mpv-player/mpv#7193]
### mpv version and platform

mpv 0.30.0-UNKNOWN Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Fri Nov 22 19:58:21 +0630 2019
ffmpeg library versions:
   libavutil       56.36.100
   libavcodec      58.62.100
   libavformat     58.35.100
   libswscale      5.6.100
   libavfilter     7.66.100
   libswresample   3.6.100
ffmpeg version: 4.2.git

### Reproduction steps
`mpv  input.360p.mkv --glsl-shaders=~~/prescalers/FSRCNNX_x16.glsl --vf="scale=w=1280:h=720" --oac=libopus --oacopts=b=32000 --ovc=libx264 --ovcopts="preset=faster:crf=21" --o=output.720p.mkv`

### Expected behavior
Here the FSRCNNx shader (or any other shader for that matter) is in ~~/prescalers. input.360p.mkv is a 360p input. output.720p.mkv is a 720p output. 
My GPU is too slow to use the FSCRNNx shader. So I'm trying to see if it is possible to somehow use mpv's encoding functionality to add the shader to the filter-pipeline. If that can be done, then I can upscale the input video "offline", and watch the upscaled version later

### Actual behavior
The above command was an attempt to do this. But the output video doesn't seem to have used the shader at all. Is this even possible? If so, could you please give a sample command

**Comment by wm4** [comment]
No, this is currently not possible. The user shader arguments are used only with --vo=gpu (encoding implicitly uses vo=lavc).

Although I guess it wouldn't be hard to hook it up as filter by changing the code.

**Comment by grill05** [comment]
@w3m thanks.

**Comment by nawtkins** [comment]
@wm4 Would this allow for hdr-compute-peak to be used for encoding as well? Is that not a built-in shader?

**Comment by Akemi** [comment]
added with https://github.com/mpv-player/mpv/commit/90df6c79c9400d3f1c711ef5696324908a5126ce.

**Comment by nawtkins** [comment]
https://github.com/mpv-player/mpv/commit/90df6c79c9400d3f1c711ef5696324908a5126ce seems to be limited to X11 though? What about systems without it e.g windows.

**Comment by wm4** [comment]
Actually it works with any system that has EGL that somehow supports rendering with a "default" display. My ifdef is pretty dangerous because it doesn't match with the one in the build scripts, and could make a build fail.

But yeah, this won't work on Windows this way.

**Comment by nawtkins** [comment]
Should I open a separate issue for Windows?
Also, do you even have any plans to further expand vf_gpu to work with other systems?

**Comment by wm4** [comment]
No I don't.

**Comment by grill05** [comment]
@wm4 could you please provide a working sample command to use with vf_gpu. Would the FSRCNNX examples from the first post work "as is" now ?
