### ISSUE TITLE
Rendering to file/stdout with --vo=gpu

### ISSUE THREAD

**Issue by grill05** [mpv-player/mpv#7194]
### mpv version and platform

mpv 0.30.0-UNKNOWN Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
built on Fri Nov 22 19:58:21 +0630 2019
ffmpeg library versions:
libavutil 56.36.100
libavcodec 58.62.100
libavformat 58.35.100
libswscale 5.6.100
libavfilter 7.66.100
libswresample 3.6.100
ffmpeg version: 4.2.git

### Reproduction steps

This is related to issue https://github.com/mpv-player/mpv/issues/7193. Some features (shaders etc) are only available in `--vo-gpu` mode. However, sometimes the gpu may not be powerful enough to run upscaling/sharpening shaders etc in real-time ( when watching the video). 

In such cases, it might be useful to somehow render-to-file. Alternatively the full-screen output could be written-to-stdout (y4m) for piping to ffmpeg for futher processing. The idea is to use the features available in `-vo=gpu` in an "offline" manner. The fullscreen output produced can then be watched later.

This would allow even weak/less-capable gpus to use interesting shaders (like FSRCNNx16/32) that they would otherwise not have been able to use without frame-drops.

**Comment by wm4** [comment]
One problem with that is that the renderer always outputs RGB, which would have to be converted back to YUV for most codecs (which involves software chroma scaling).

**Comment by grill05** [comment]
@w4m I'm not sure where the RGB-YUV conversion would take place. But speed is less important in this context, since the idea is do this "offline"

**Comment by grill05** [comment]
@wm4 @Akemi using the vf_gpu with FSRCNNX seems to work ok. But `radeontop` shows this on AMD stoney
![rtop](https://user-images.githubusercontent.com/56592753/69900418-89c0d580-13a1-11ea-8026-6cde233cc72e.png)

It seems some gpu capabilities remain completely unused. Is this because of the specific shader, or it this a side-effect of off-screen rendering ?

**Comment by wm4** [comment]
Oh god, it's that kind of user who would also complain that there's not enough black smoke in their new motorbike's exhaust gases.

**Comment by Argon-** [comment]
When all you are doing is summing up values, would you also complain about your CPU's multiplication capabilities not being fully used?

**Comment by grill05** [comment]
@wm4 @Argon- thanks for answering. I was just curious to see the `radeontop` output.

**Comment by monarc99** [comment]
i tried the vf_gpu filter with dvd material. (anamorphic 720x576 16/9)
@wm4 Does vf_gpu scale the picture? I get extra black rows at the bottom/top.

i tried to set --video-aspect-override=0 for encoding. The picture was not changed by vf_gpu (extra black rows at the top/bottom), but the aspect ratio was not set on the file.

I get a normal picture with:
--video-aspect-override=0 --ovcopts-add=sar=65/45

**Comment by wm4** [comment]
RTFM

**Comment by monarc99** [comment]
D'tWMT
