### ISSUE TITLE
cocoa_cb_common.swift: mpv.app becomes active forcibly whenever dimension of video changes

### ISSUE THREAD

**Issue by aerobounce** [mpv-player/mpv#7195]
### mpv version and platform
`mpv 0.30.0-210-g7c6570402b-dirty`
`ffmpeg version: git-2019-11-17-f7ad9a6`
`macOS 10.14.6 (18G1012)`

### Reproduction steps
First of all, this is macOS specific behavior, I suppose.
And here I am talking about behaviors of mpv.app GUI for macOS, not CLI.

- To reproduce, you need at least 2 any media files that contains `video`.
- Note that each file's **video dimension** **must be different**.

`mpv --no-config --vid=no --force-window 01\ Gravity.mp3 01\ Low\ Frequency.mp3`

- 01 Gravity.mp3
- 01 Low Frequency.mp3

^ In my case audio files are used. Those have different size of artworks embedded.

1. From Terminal, launch mpv like above.
2. As mpv.app launches, its window becomes visible. CMD+M to Minimize into Dock. CMD+H to hide the app.
2. Press return on Terminal, to play next track.
3. mpv.app becomes active, and its window gets out of Dock, gets brought back to the front.

### Expected behavior
mpv.app should not be activated implicitly, plus its window should not be back if it's minimized as it is the state an user intended to (In my case, as a BGM player).

### Actual behavior
No matter what configuration you use, if the next file in playlist has a different size of video, mpv.app gets activated or minimized window brings back.

### Log file
```
mpv --no-config --vid=no --force-window --log-file=~/Desktop/playlog.txt ~/Music/iTunes/iTunes\ Media/Music/Metrik/Gravity/01\ Gravity.mp3 ~/Music/iTunes/iTunes\ Media/Music/Culture\ Shock/Low\ Frequency/01\ Low\ Frequency.mp3
```
http://ix.io/235F

### Sample files
This can be reproducible with at least 2 any media files that has `video` in condition those files has different dimension video sizes.

----

### Suspicious lines of code
So, video size changes, then:
https://github.com/mpv-player/mpv/blob/f09570664fd870cbd7403575c8f2a31e34d4c570/video/out/cocoa_cb_common.swift#L146-L157
gets called, and:
https://github.com/mpv-player/mpv/blob/f09570664fd870cbd7403575c8f2a31e34d4c570/video/out/cocoa_cb_common.swift#L154-L156
Those 3 lines of codes inside the function above get evaluated, and app's window is back.

----

https://github.com/mpv-player/mpv/blob/f09570664fd870cbd7403575c8f2a31e34d4c570/video/out/cocoa_cb_common.swift#L155

- If you comment out this line, problem will be solved, which I did – built, tested and confirmed. But the point is whether this behavior is intended or not. If it is, there should be an option to disable the behavior I reckon.
- And I'm just curious why the window should be made front if it's not visible state?

**Comment by Akemi** [comment]
i will have a look at the weekend. it has/had a reason why it is there. could be, due to refactoring, the reason is gone now. probably also should remove the atomic drawing.

**Comment by aerobounce** [comment]
FYI, for particularly this swift file though, I’ve checked its history and this was implemented from the initial commit. 
I’m not sure if the equalevant was there before Swift.

**Comment by Akemi** [comment]
it's a swift backend specific mechanism, it wasn't in the old backend.

**Comment by aerobounce** [comment]
Right.

Well, I've been testing mpv.app with modification like below:
```swift
func updateWindowSize(_ vo: UnsafeMutablePointer<vo>) {
    let opts: mp_vo_opts = vo.pointee.opts.pointee
    guard let targetScreen = getScreenBy(id: Int(opts.screen_id)) ?? NSScreen.main else {
        libmpv.sendWarning("Couldn't update Window size, no Screen available")
        return
    }

    // let wr = getWindowGeometry(forScreen: targetScreen, videoOut: vo)
    // if !(window?.isVisible ?? false) {
    //     window?.makeKeyAndOrderFront(nil)
    // }
    layer?.atomicDrawingStart()
    // window?.updateSize(wr.size)
}
```
Apart from the app & its window activation, this also realizes **Picture in Picture** alike behavior since it keeps its' window size a user specified. The problem is that causes black borders to be shown if aspect ratio is changed, though.
And I'm loving it, this is the behavior I wanted for so long time.

But... should this be discussed in other issue / feature request? What do you think?

**Comment by aerobounce** [comment]
Right.

Well, I've been testing mpv.app with modification like below:

```swift
func updateWindowSize(_ vo: UnsafeMutablePointer<vo>) {
    let opts: mp_vo_opts = vo.pointee.opts.pointee
    guard let targetScreen = getScreenBy(id: Int(opts.screen_id)) ?? NSScreen.main else {
        libmpv.sendWarning("Couldn't update Window size, no Screen available")
        return
    }

    // let wr = getWindowGeometry(forScreen: targetScreen, videoOut: vo)
    // if !(window?.isVisible ?? false) {
    //     window?.makeKeyAndOrderFront(nil)
    // }
    layer?.atomicDrawingStart()
    // window?.updateSize(wr.size)
}
```
Apart from the app & its window activation, this also realizes Picture in Picture alike behavior since it keeps its' window size a user specified. This cannot be reproduced by option like `autofit` nor `geometry`.
The problem is that causes black borders to be shown if aspect ratio is changed, though.
And I'm loving it, this is the behavior I wanted for so long time.

But... should this be discussed in other issue / feature request? What do you think?

**Comment by Akemi** [comment]
regarding your off-topic question, i think your use case is talked about in the recently opened RFC #7204.

also your use case is handled by this script https://gist.github.com/TheAMM/5e07ad787dd95d76131b61840f403a79 i believe

**Comment by aerobounce** [comment]
Yes, that’s exactly what I noticed after posting. #7204. As opener said in the issue, more options == more complexity. totally agreed so I’m organizing my thoughts...
And the script! Thanks for this I've never seen that one. However kind of could achieve that with
```
autofit-larger=25%x25%
geometry=25%x25%+100%+0%
```
Though it's pinned to MaxX, MinY though. Nah off-topic again sorry.

And.. how is `window?.makeKeyAndOrderFront(nil)` thing going, any reasons salvaged?

**Comment by Akemi** [comment]
nothing yet, though didn't have time to look at it yet (had to finish the other two PRs). i will try to look at it till this weekend.

**Comment by aerobounce** [comment]
Not hurrying you up, take your time please.

**Comment by Akemi** [comment]
okay that part of the code is there to make the window visible again when you have a playlist item without a video track in-between. 

would be nice if you could try #7260. sorry it took so long.

**Comment by aerobounce** [comment]
In other words, to prevent a window to be released in that situation?

Thanks for this, will try in a few days. No need to be sorry at all.

**Comment by Akemi** [comment]
i meant the parts you mentioned intially, eg `window?.makeKeyAndOrderFront(nil)`.

**Comment by aerobounce** [comment]
Yes, I know but I didn't see why it's bad if you don't make a window `makeKeyAndOrderFront` in that situation ↓
> when you have a playlist item without a video track in-between

----

Okay, I did several tests with [cocoa-cb_minimize branch](https://github.com/Akemi/mpv/tree/cocoa-cb_minimize).

**Conditions**
1. Play an audio playlist (each has different size artwork embedded) with mpv.app GUI.
2. Play the next track by waiting for EOF and by manually seeking (Both tested).
3. Launch mpv binary in Terminal.
4. Seeking / any controls are done in Terminal.

- Minimize window && (Hide the App || Keep the App active)
  - ✅ The window doesn't come back nor the app become active. Natural.
- Keep window visible && Hide the App
  - ❓ The app becomes active state in the background (doesn't come front though).

Was the latter intended?

**Comment by Akemi** [comment]
1. Start mpv via terminal with two file. first one with a video track second without one.
2. minimise mpv while playing the first file
3. change to the next file while being minimised
4. click on the mpv icon to deminimize

with your approach a window is deminimised (which should be gone) with a last rendered frame and/or a black frame. with my patch you can't deminimise a window that is not supposed to be there.

besides that one should aviod as many conditions as possible.

is there a problem with my patch or does it behaviour in an undesired way?

**Comment by aerobounce** [comment]
You're right, I was aware of that minimized window is kept in Dock no matter if a file doesn't have a video...

> is there a problem with my patch or does it behaviour in an undesired way?
No, no, I didn't mean that way, but:

1. Play mpv in Terminal. 3 files, video / no video / video.
2. Hide mpv.app (Don't minimize)
3. When you play the 3rd file, mpv.app becomes unhidden.

I felt a bit strange with 3. Except that everything was natural with several tests.

**Comment by aerobounce** [comment]
> is there a problem with my patch or does it behaviour in an undesired way?

Ah well, I didn't want to be a bug-complaining-troll and was eager to contribute at least a bit.
And yes, this issue is half-solved with your patch:

1. Play mpv in Terminal. 3 files, video / no video / video.
2. Hide mpv.app (Don't minimize)
3. When you play the 3rd file, mpv.app becomes unhidden.

I feel a bit of strangeness with 3 — app being activated by the app itself.
Which is one of the reason I opened this issue.

Except that, everything was fine and natural with several tests.
Minimized window behavior part is fixed with your current patch.

**Comment by aerobounce** [comment]
> is there a problem with my patch or does it behaviour in an undesired way?

Yes, this issue is half-solved with your current patch. (And I wanted to contribute at least something, failed though)
As you described in #7260:

1. Play mpv in Terminal: 3 files, `video > no video > video`.
2. **Hide mpv.app** or/and **minimize its window**
3. When you play the 3rd file, **mpv.app becomes Unhidden** and its **Window comes out of Dock**.

Let's make it clear, in the condition above:

1. mpv.app becomes **Active even if it was hidden state**.
2. mpv.app's **Window comes out of Dock**.

### 1.
I think **1.** is essential, this is the most reason I opened this issue.
It'd be better if it works with vanilla config, `no-config`. Using workaround `--force-window` for this feels a bit strange for me.
I've written a tweak for this: https://gist.github.com/aerobounce/7276c4cb5401e6e47893c2f801f56bea
Would you consider about this please.

### 2.
**2.** might be kind of natural. Because in your patch, window is closed by the app and new window is created again. So keeping miniaturized state might be strange (I'm not quite sure. Personally, I want it.). Using `--force-window` for this maybe natural.
However, for the record, I've written fix for this too: https://gist.github.com/aerobounce/175dde6409a08a43a69d5cff3f420135
If you don't think it's strange, I'd like you to include this fix too.

**Comment by aerobounce** [comment]
@Akemi , if I've failed to convince you, please proceed #7260, then I'm happy to close this issue.
Since if my claims/requests are against mpv's behavior policy, it should not be adopted anyways.

**Comment by Akemi** [comment]
my PR also still has the issue with hidden windows and i would like to fix that too properly.

personally i think your changes are a bit too much of a special case since they work around a somewhat expected macOS behaviour, and since --force-window works around it i would say it's also not worth adding that kind of complexity.

**Comment by aerobounce** [comment]
Oh. I see.
In case you need testing, I'd happily do.

> personally i think your changes are a bit too much of a special case since they work around a somewhat expected macOS behaviour, and since --force-window works around it i would say it's also not worth adding that kind of complexity.

Well, yeah... good point. I'm beginning to think that way by myself when I read what I've written. Calling `window.makeKeyAndOrderFront` and suppressing its effect makes no sense, kind of fighting against API, which is often said it's bad.
