### ISSUE TITLE
mpv 0.30 issue with rar video playback latest libarchive (cant provide sample to large)

### ISSUE THREAD

**Issue by mac010** [mpv-player/mpv#7198]
mpv version and platform:

Fedora 31
mpv 0.30
libarchive 3.4.0-1

Reproduction steps:

Play video in multi-part rar file.
[libarchive] possibly unsupported seeking - switching to reopening
No video window opens.
Happens on about half of rar'd video out there.
mpv -v reveals each rar is being slowly opened, so the video window does eventually open, but not instantly as previous versions.

[log.log](https://github.com/mpv-player/mpv/files/3906464/log.log)

Expected behaviour:

Playback of rared videos instantaneous  as was possible with 0.29 with older libarchive.
Actual behavior

Cant upload sample as multi part rar file needed, common size 4gb+ (small sample would open near instantly)

**Comment by Akemi** [comment]
closing because of #7182.
