### ISSUE TITLE
Build fails with "error: expected specifier-qualifier-list before ‘GLsync’" from ../video/out/opengl/common.h:193

### ISSUE THREAD

**Issue by Lotus907efi** [mpv-player/mpv#7201]
### mpv version and platform
Pulled latest from git as of yesterday 11/29/2019
On Ubuntu 14.04 with many updated libraries.

### Reproduction steps
unpack source
./waf configure --enable-dvdnav --enable-cdda
./waf -v build
### Expected behavior
builds mpv without errors
### Actual behavior
In file included from ../video/out/opengl/context.h:5:0,
                 from ../video/out/opengl/context_glx.c:42:
../video/out/opengl/common.h:193:5: error: expected specifier-qualifier-list before ‘GLsync’
     GLsync (GLAPIENTRY *FenceSync)(GLenum, GLbitfield);
     ^
### Log file
config.log file
https://0x0.st/zlr8.log

output of waf build
https://0x0.st/zlrZ.txt

**Comment by wm4** [comment]
Your headers are simply too old. I guess that's what you get for using an OS that's outdated by 5.5 years. If my hack doesn't work, update your damn installation (which I bet is already broken beyond repair anyway).

**Comment by Lotus907efi** [comment]
My open GL headers are from a fairly recent NVidia driver install.

and you said "If my hack doesn't work. blah blah blah" but you don't actually give any details of what the "hack" is.

**Comment by Lotus907efi** [comment]
Also when I was research this before submitting this report I found two other pastebin instances with the same error so I am not the only one encountering this. I am just the only one bothering to submit a report.

https://pastebin.com/J9SVhK0G

**Comment by wm4** [comment]
> My open GL headers are from a fairly recent NVidia driver install.

100% doubt it. Your install is probably just a broken mess, from your description. (Ubuntu from 2014 + "newer" libs.)

> and you said "If my hack doesn't work. blah blah blah" but you don't actually give any details of what the "hack" is.

Helps if you can read.

**Comment by Lotus907efi** [comment]
I have looked through the wiki, the faq and the mpv/DOCS material and I fail to see anything that I think is related to a "hack" for build issues. Why not just give me a pointer to the information and stop being cryptic?

**Comment by wm4** [comment]
The commit which closed this?

**Comment by wm4** [comment]
Also sorry if I seem annoyed. That's because I'm actually annoyed, but I appreciate that you reported the bug anyway.
It's just that I'm still convinced this is just a semi-broken installation, and this causing more work for everyone, including yourself and myself. Yes, I get upset over this.

**Comment by Lotus907efi** [comment]
Sorry but when I read the contents of this bug report the was no evidence of any commit until you added it just now. This is why I was puzzled.

**Comment by wm4** [comment]
I meant this one: https://github.com/mpv-player/mpv/commit/fa9a1ff0a0f2ec0c37e27c30ad71ba814c7ada89
The one I added above a few minutes ago is a second one.
Yes, github makes commits that _close_ an issue less visible than commits that only _mention_ it.

**Comment by Lotus907efi** [comment]
Ah HA! I just checked out fresh source so I got your earlier "hack" and now the build succeeds! Thank you!

**Comment by wm4** [comment]
Well at least it works. But it just confirms that your GL headers are somehow very old.

**Comment by Lotus907efi** [comment]
I understand. Thank you for the changes that helped in this case.

**Comment by CounterPillow** [comment]
FYI, Ubuntu 14.04 has been EOL since April.

**Comment by Lotus907efi** [comment]
Again I am sorry if this took valuable developer time to do but isn't one side benefit of the changes in fa9a1ff that the mpv code is now more tolerant of "unusual" systems?

**Comment by wm4** [comment]
It'll be tolerant against outdated GL headers that GLX might pull in. (And possibly other backends.) We had this since spring 2017, but never any bug reports.
