### ISSUE TITLE
Next file is not played when using exact seeking

### ISSUE THREAD

**Issue by orion1vi** [mpv-player/mpv#7206]
### mpv version and platform

Since 6bcda94cbc86bd1ab710546816b019e86bc92ec9, macOS 10.14.6

### Reproduction steps

input.conf:
AXIS_UP    seek 0.05 relative+exact
AXIS_DOWN  seek -0.05 relative+exact

Open picture or video file and scroll to the end.

### Expected behavior

Exact seeking plays next file EOF.

### Actual behavior

Exact seeking does not play next file EOF.

This change introduces inconsistent behaviour where normal seeking plays next file while exact does not, except for audio files with no embedded art.

**Comment by wm4** [comment]
Doesn't it go to the next file if you stop seeking?

**Comment by orion1vi** [comment]
If the file is playing it does, I'm just used to seeking through files, if this is intended behaviour it's alright, I'll adjust.

**Comment by orion1vi** [comment]
Sorry for late response, with this (57fbc9c) change I can now seek beyond video time and have to unseek all of the overseek to move back.

Example:
Video is 3 seconds.
Pause video, scroll to end and keep scrolling forward.
To move to second 2 of video I would have to un scroll all the forward scrolling I did first.

At first sight the difference I see in output is that `[mkv] queuing seek to X.X` used to restart on the next scroll if it's beyond length of video, where now it's kept where it last stoped even if it's out of video time bounds.
