### ISSUE TITLE
FRAME STEP BACK inaccurate on high FPS videos

### ISSUE THREAD

**Issue by WAZAAAAA0** [mpv-player/mpv#7208]
Frame step back skips too many frames on high FPS video files. The higher the frame rate, the more frames get skipped.
Frame step forward doesn't seem to be affected.

I've made a couple of sample files with just a frame counter in them, ranging from 1 to 1000 FPS across multiple codecs/containers to easily reproduce the behavior: [fps_test_files.zip](https://github.com/mpv-player/mpv/files/3907675/fps_test_files.zip)

Log of myself playing 1000.mkv, stopping the video, using backstep 5 times, stepping forward 3 times, and quitting: https://pastebin.com/raw/xCdPiiHv

Tested on both Linux and Windows, with MPV 0.30.0-195-gb31f2f6cb9, using default parameters, on 2 different 60 Hz monitors if that matters.

**Comment by wm4** [comment]
mpv relies on timestamp for seeking. mkv typically uses millisecond timestamp resolution, so at around 1000 fps timestamps start being non-unique, so backstep (or any sort of seek) will not work correctly.
Try a different container.

**Comment by WAZAAAAA0** [comment]
> 
> 
> mpv relies on timestamp for seeking. mkv typically uses millisecond timestamp resolution, so at around 1000 fps timestamps start being non-unique, so backstep (or any sort of seek) will not work correctly.
> Try a different container.

I've tried 3 containers (MKV MP4 AVI) with a different video codec in each, and they have all exhibited the same issue. The "backframe skipping" issue also starts as low as 200 FPS or even 180

**Comment by wm4** [comment]
Don't insult me with avi.
mp4 can do it, but of course you need to make sure the input timestamps are correct at all.

**Comment by WAZAAAAA0** [comment]
I don't know dude... I just tried the 200 FPS video on 4 additional containers, OGV MPG FLV WMV, generated using FFmpeg on the default settings, and they all acted the same with the skips.

"MPC-BE" has the same issue but it starts happening from an higher framerate, like 1000 FPS. A different kind of program, Avidemux, works just fine.

How do I "make sure the input timestamps are correct"? I suppose FFmpeg would handle that by default.

**Comment by wm4** [comment]
Could also be because mpv has a 5ms "tolerance" on seeking, which I think is supposed to allow it to hit the target if you specify the seek target as time string.

**Comment by wm4** [comment]
^ does this help?

**Comment by WAZAAAAA0** [comment]
It helps, that solved it completely.
I checked various high framerate files up to 1 million FPS and the backstep skips no longer occured, good job @wm4


compiled Win64 mpv-x86_64-20191205-git-000c045 binaries for those who want to double check: https://x0.at/Mu1.7z
absurdly high FPS test files: https://x0.at/lD4.7z
