### ISSUE TITLE
MPV suddenly stopped working

### ISSUE THREAD

**Issue by TacosWillEatUs** [mpv-player/mpv#7209]
### mpv version and platform
mpv 0.30.0-195-gb31f2f6cb9 - Windows 10 Pro

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Whenever I try to launch any video
### Expected behavior
It should play
### Actual behavior
It does nothing, if I open MPV and drag a file in, it just closes
### Log file
https://pastebin.com/bwuYRfA9

I've tried uninstalling, windows updates, and even video card drivers, but no fix so far. It was working fine last night (That was on an older version, I tried all sorts of releases, even the stable build and no luck

**Comment by wm4** [comment]
Initializing wasapi fails mysteriously, and then I guess it crashes when trying openal as fallback (no idea why openal is enabled though).
Maybe changing the default audio device in Windows or so helps.

**Comment by TacosWillEatUs** [comment]
@wm4 Thanks a million, I spent the last 2 hours trying to figure this out and switching the default audio device fixed it.
