### ISSUE TITLE
stream selection by stream id as opposed to index

### ISSUE THREAD

**Issue by phkarmur** [mpv-player/mpv#7211]
select stream id instead of stream index in --lavfi-complex because stream index can change in each mpv run and we can not select stream which we want while we have MPTS or multiple audio streams.

**Comment by jeeb** [comment]
With a quick thought this could be accomplished by:
1. Getting the value from `AVStream.id`
2. Passing it to our stream struct in some entry.
3. Passing that then onto the track struct (which is utilized for stream/track selection as far as the player is concerned).
4. Adding a property/whatever like `{v,a,s}pid` (since "id" is already taken for the index).
5. If mapping it to lavfi-complex requires extra work, that would also need to be done?

Something like that?

**Comment by wm4** [comment]
A script can already sort of do this by setting a ``on_preloaded`` hook, getting the track list, reading the ID, and selecting what it wants.

**Comment by jeeb** [comment]
I did check the definition of `struct track` and it seemed like it only contained `ff_index`  as something taken from the libavformat layer? Which if I understand it correctly is the index, not the id.

Basically, the order of AVStreams is dependent on when you get the first packet for that stream, but the stream id (basically the packet ID (PID) in MPEG-TS for example), is static with a live input.

**Comment by wm4** [comment]
It's demuxer_id, see get_track_entry.

**Comment by jeeb** [comment]
Oh, I thought by the name that it was the identifier of our internal demuxer :D .Lel.

**Comment by phkarmur** [comment]
is there anything already done on this? if yes, can anyone please tell me how to select pid (stream id)?

**Comment by phkarmur** [comment]
@wm4 from what i understood from your statement that we can make lua script or c plugin and pass required details to script and in script we have to find track details using this property [https://mpv.io/manual/master/#command-interface-track-list](url).

But when i tried to get property using jsonIRC, i didnt get stream_id (pid)  i got something different value not even stream_index.  But i might take wrong meaning for your statement. So can you please explain it more?

`[root@mGPU-server-19 test]# echo '{ "command": ["get_property", "track-list"]}' | socat - /tmp/server_0_1`

> { 
   "data":[ 
      { 
         "id":1,
         "type":"video",
         "src-id":0,
         "albumart":false,
         "default":false,
         "forced":false,
         "dependent":false,
         "visual-impaired":false,
         "hearing-impaired":false,
         "external":false,
         "selected":true,
         "ff-index":0,
         "decoder-desc":"h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)",
         "codec":"h264",
         "demux-w":854,
         "demux-h":480,
         "demux-fps":25.000000
      },
      { 
         "id":1,
         "type":"audio",
         "src-id":0,
         "audio-channels":2,
         "albumart":false,
         "default":false,
         "forced":false,
         "dependent":false,
         "visual-impaired":false,
         "hearing-impaired":false,
         "external":false,
         "selected":true,
         "ff-index":1,
         "decoder-desc":"aac (AAC (Advanced Audio Coding))",
         "codec":"aac",
         "demux-channel-count":2,
         "demux-channels":"stereo",
         "demux-samplerate":44100
      },
      { 
         "id":1,
         "type":"sub",
         "src-id":0,
         "albumart":false,
         "default":true,
         "forced":false,
         "dependent":false,
         "visual-impaired":false,
         "hearing-impaired":false,
         "external":false,
         "selected":true,
         "ff-index":2,
         "codec":"eia_608"
      },
      { 
         "id":2,
         "type":"video",
         "src-id":0,
         "title":"h264.png",
         "albumart":false,
         "default":false,
         "forced":false,
         "dependent":false,
         "visual-impaired":false,
         "hearing-impaired":false,
         "external":true,
         "selected":true,
         "external-filename":"codecs/h264.png",
         "ff-index":0,
         "decoder-desc":"png (PNG (Portable Network Graphics) image)",
         "codec":"png",
         "demux-w":332,
         "demux-h":150,
         "demux-fps":1.000000
      },
      { 
         "id":2,
         "type":"sub",
         "src-id":0,
         "title":"h264.png",
         "albumart":false,
         "default":true,
         "forced":false,
         "dependent":false,
         "visual-impaired":false,
         "hearing-impaired":false,
         "external":true,
         "selected":false,
         "external-filename":"codecs/h264.png",
         "ff-index":1,
         "codec":"eia_608"
      },
      { 
         "id":3,
         "type":"video",
         "src-id":0,
         "title":"aac.png",
         "albumart":false,
         "default":false,
         "forced":false,
         "dependent":false,
         "visual-impaired":false,
         "hearing-impaired":false,
         "external":true,
         "selected":true,
         "external-filename":"codecs/aac.png",
         "ff-index":0,
         "decoder-desc":"png (PNG (Portable Network Graphics) image)",
         "codec":"png",
         "demux-w":332,
         "demux-h":150,
         "demux-fps":1.000000
      },
      { 
         "id":3,
         "type":"sub",
         "src-id":0,
         "title":"aac.png",
         "albumart":false,
         "default":true,
         "forced":false,
         "dependent":false,
         "visual-impaired":false,
         "hearing-impaired":false,
         "external":true,
         "selected":false,
         "external-filename":"codecs/aac.png",
         "ff-index":1,
         "codec":"eia_608"
      }
   ],
   "request_id":0,
   "error":"success"
}

**Comment by wm4** [comment]
The src-id entry in track-list apparently works only for mpegts/mpeg, because it's whitelisted.

**Comment by phkarmur** [comment]
yes, its working for mpegts and sorry i was looking for hls and thats why i was getting src-id 0 in all streams

**Comment by wm4** [comment]
^ this probably doesn't help (since you mentioned hls), but then I think hls has only relatively random IDs from the underlying mpegts, that don't really help on this level.

**Comment by phkarmur** [comment]
yes yes, I totally get it. I was working on HLS so i just checked for HLS only and thats why I wasnt working and it should not work too like you said. And in hls we can pass chunk's m3u8 (each profile's link from menifest file) and I requested this for MPTS (UDP) specially.

**Comment by wm4** [comment]
Not sure what you're trying to say. What's a MPTS?

**Comment by phkarmur** [comment]
multi program transport stream(MPTS)
