### ISSUE TITLE
question about playing avisynth and vapoursynth scripts

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#7213]
I'm maintaining a GUI for AviSynth and VapourSynth called StaxRip, this GUI has two dialogs that show video, the rendering is .NET WinForms GDI based and needs to be replaced because it's painful slow, like 200 ms for one UHD image... My current plan is to replace it using Direct2D. I wonder however if libmpv could be used. Requirements are:

1. opening avs and vpy files, it seems currently vpy files cannot be opened, this would be a highly valuable feature for both of my apps StaxRip and mpv.net (MPC-BE supports it out of the box).

2. accurate frame access must be guaranteed

3. it must be possible to place Win32 controls on top of the video window, building it with Lua for me would be a challenge, I'm not sure if it would make sense to learn Lua only because of that, as enthusiastic mpv user it's certainly a great skill to have but learning a complete programming language is never an easy task.

Might libmpv fulfill these three requirements?

**Comment by Akemi** [comment]
1. vapoursynth is supported.
2. mpv doesn't know about frames only timestamps. frame within mpv are just an estimate and will not be accurate for example with vfr videos.
3. that can be done.

**Comment by stax76** [comment]
Following command lines don't work:

`mpv test.vpy`

`mpv --vf=vapoursynth=D:\Samples\test.vpy`

shinchiro built from today.

**Comment by Argon-** [comment]
... have you built mpv with vapoursynth?

**Comment by stax76** [comment]
I can build a Visual Studio project by pressing F6 but setting up the build environment for a project like mpv probably takes 3 days without having much experience for the task, and then it probably takes 2 hours to build. I download both mpv and libmpv builds from shinchiro.

**Comment by qyot27** [comment]
mpv's support for vapoursynth is as a video filter.  That video filter, AFAIK, does not play the scripts the way you're expecting.  Its most prominent use is probably to apply motion-compensated frame interpolation via vapoursynth-mvtools or some hodge-podge way of getting SVP to work with it.

libavformat's support for vapoursynth are as demuxer(s), and FFmpeg deliberately does not allow execution of those scripts as video files unless you force the demuxer (*-f vapoursynth* before the input).  If mpv was built against an FFmpeg that has vapoursynth support enabled, it will play the scripts back as video as long as you do the same thing you have to do in FFmpeg: force the demuxer when you invoke mpv (*--demuxer-lavf-format=vapoursynth*).

**Comment by stax76** [comment]
Thank you, I try to contact shinchiro.

**Comment by stax76** [comment]
I've requested it now:

https://github.com/shinchiro/mpv-winbuild-cmake/issues/54

**Comment by stax76** [comment]
> Get latest Vapoursynth with same type (32/64-bit) as mpv. Download portable version and extract it in same folder as mpv.exe.

> Get Python 3.7.x. Download the embeddable file and extract it in same folder as mpv.exe

I don't think I can do that for several reasons. I need to eat my own dog foot so the mpv.net build I use for my playback is also my debug developer build and release build (I release debug builds), I can't just put everything in one directory because that would be an unmanageable mess, things have to be separated in sub folders. I can try to set the process wide Path variable and see if a sub folder works.

There are other reasons why it's a no go for me, people are already complaining that both StaxRip and mpv.net need too much download and disk space (they call it bloat), so I and the users of mpv.net and StaxRip need vpy playback in the same way as **all other apps work, using the installed Python and VapourSynth**, in MPC-BE and dozens of other apps it just works out of the box and by default.

**Comment by stax76** [comment]
I give this issue another go.

https://forum.doom9.org/showthread.php?t=180433
