### ISSUE TITLE
wishlist: vtt: support styling

### ISSUE THREAD

**Issue by pan93412** [mpv-player/mpv#7214]
### mpv version and platform
```
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Tue Nov 12 00:20:16 CET 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.1
```

- System: Arch Linux (testing / kde-unstable) x86-64
- System Language: zh_TW.UTF-8
- Desktop Environment: Plasma 5.17.3 / KDE Frameworks 5.64.0 / Qt 5.14
- Font: Noto Sans CJK TC
- `youtube-dl` installed

### Reproduction steps
1. open terminal (in my case is `konsole`)
2. `mpv https://youtu.be/S8dmq5YIUoc`
3. switch the subtitle to `zh_TW`

### Expected behavior
![Playing on YouTube](https://user-images.githubusercontent.com/28441561/69917571-70538280-14a2-11ea-9365-de85e28b82e2.png)
When playing this video with zh_TW subtitle on YouTube Web. (0:14)

### Actual behavior
![Playing on mpv](https://user-images.githubusercontent.com/28441561/69917601-9c6f0380-14a2-11ea-981d-0440b50f836b.png)
When playing this video with zh_TW subtitle on mpv + youtube-dl. (0:14)

### (For developers) some reference of styling
- Text Color: <https://www.w3.org/TR/webvtt1/#default-text-color>
- Cue settings, like alignment, position and etc.: <https://www.w3.org/TR/webvtt1/#cue-settings>

### Log file
Omitted.

### Sample files
- [The zh_TW subtitle of that video](https://github.com/mpv-player/mpv/files/3908491/AIAIAI-zh-TW-subtitle-raw.zip)

**Comment by jeeb** [comment]
Now, I haven't looked at the sample yet, but I do know that we have two possible parts here:
1. I know some youtube VTT things do things in a non-standard way.
2. FFmpeg handles the WebVTT parsing and converts it to ASS internally.

1. Is unfortunate, but the last time someone brought up stuff like karaoke etc that didn't seem to work in a standard way.
2. If the VTT file seems standard, you can check with ffmpeg.c (the FFmpeg command line app) whether doing something like
```bash
ffmpeg -v verbose -i INPUT.vtt -c:s ass out.ass
```
has the styling.

If not, then this is an FFmpeg issue.

If it has, then mpv is dropping the styles. I think there was some argument before regarding mpv dropping the generated styles that FFmpeg provides.

I think currently as far as styles

**Comment by wm4** [comment]
It drops the ASS style section. Not doing so in unacceptable, because for most formats, the ffmpeg default style is just arbitrary, and it makes no sense to force that on users.

**Comment by pan93412** [comment]
> ```shell
> ffmpeg -v verbose -i INPUT.vtt -c:s ass out.ass
> ```

```
$ mpv --sub-file=out.ass AIAIAI.mkv
```

![image](https://user-images.githubusercontent.com/28441561/69917763-90844100-14a4-11ea-99d2-075839fca6f7.png)

**Comment by jeeb** [comment]
Alright, feel free to create a ticket on https://trac.ffmpeg.org/ regarding it.

**Comment by pan93412** [comment]
Ok :) I'll do it later

**Comment by Akemi** [comment]
let us know when you reported it, so i can close this issue.

**Comment by pan93412** [comment]
@Akemi @jeeb @wm4 Ok I reported this to upstream: https://trac.ffmpeg.org/ticket/8410#ticket

Could you guys take a look? thanks! :)

**Comment by Akemi** [comment]
closed since it was reported upstream.

**Comment by Slider-Whistle** [comment]
Hope they can do it, ASS is just such a terrible, unreadable subtitle format.

**Comment by wm4** [comment]
> Hope they can do it, ASS is just such a terrible, unreadable subtitle format.

What does that help us? Besides webvtt is more terrible than ASS.

Anyway, if anyone wants to implement a webvtt parser/renderer in mpv, you're welcome.

**Comment by Totorrr** [comment]
Hi everyone, 

vlc has vtt files displaying with styling working. Can mpv copy/integrate vlc's parser/renderer in mpv's code?

Thanks,

**Comment by sergeevabc** [comment]
@ghost, could you elaborate why you believe VTT is a terrible format?
Compared to SRT, it looks cleaner to me and surely takes up less space.

@Totorrr, came here to say the same after a few attempts to output colored text.
Actually, for the first time in my memory it seems that VLC outperforms MPV.

**Comment by pan93412** [comment]
> @ghost, could you elaborate why you believe VTT is a terrible format?
> Compared to SRT, it looks cleaner to me and surely takes up less space.
> 
> @Totorrr, came here to say the same after a few attempts to output colored text.
> Actually, for the first time in my memory it seems that VLC outperforms MPV.

@ghost = deleted users. Tagging it takes no effect.

**Comment by CounterPillow** [comment]
VTT is a terrible format because it requires a full browser engine to render properly. mpv will not ship a full web browser to render subtitles.

**Comment by Slider-Whistle** [comment]
It's just CSS and a bit of XML, isn't it? Little details aside, what makes that
so different from the ASS subtitle format? An XML interpreter is hardly a "full
web browser".

**Comment by CounterPillow** [comment]
It's a full DOM, with JS scriptability, and a whole CSS layout engine.

**Comment by AtticFinder65536** [comment]
A workaround for YouTube subtitles (which is SRV3/YTT, I think it's non-standard WebVTT?) is to use [YTSubConverter](https://github.com/arcusmaximus/YTSubConverter) to convert it to ass which can be played in mpv. It should largely resemble the subtitles you'll see in the YouTube player.

**Comment by Nicryc** [comment]
So if I understand correctly WebVTT colouring will never be supported by MPV because it needs too much to work (a complete web browser engine)

**Comment by dhouck** [comment]
The [W3C spec](https://www.w3.org/TR/webvtt1/#obtaining-css-boxes "WebVTT spec section 7.3") says
> For the purpose of resolving URLs in STYLE blocks of a WebVTT file, or any URLs in resources referenced from STYLE blocks of a WebVTT file, if the URL’s scheme is not "data", then the user agent must act as if the URL failed to resolve.
So, thatʼs still an almost-full CSS renderer and most of the problems that come with it, and I understand not wanting to include that, *but* no HTTP requests are necessary, and none of the security or blocking problems associated with those.

That can still be a lot of extra effort, of course, but not nearly as bad as implied.

**Comment by dhouck** [comment]
I think that would take more than 5 lines of bash, and I am in no way a maintainer or anything, but I bet if you did write that script people would be willing to use it.

**Comment by Tama47** [comment]
> A workaround for YouTube subtitles (which is SRV3/YTT, I think it's non-standard WebVTT?) is to use [YTSubConverter](https://github.com/arcusmaximus/YTSubConverter) to convert it to ass which can be played in mpv. It should largely resemble the subtitles you'll see in the YouTube player.

How to convert VTT to ASS? From their description:
> YTSubConverter is primarily an .ass → .ytt converter. You can create .ass subtitles using [Aegisub](https://github.com/wangqr/Aegisub/releases).

**Comment by MasterInQuestion** [comment]
Too many things wrong from the very beginning.
    The concept of the whole presentation scheme is initially mal-defined:
    Scenes (slicing) and overlays (filtering) are important elements of raw media.
    Not only those straight captured (e.g. directly from camera).

    Somewhat related:
    [ https://github.com/MasterInQuestion/talk/discussions/3#discussioncomment-9376594](https://github.com/MasterInQuestion/talk/discussions/3#discussioncomment-9376594)
    https://trac.ffmpeg.org/ticket/5309#comment:16
    https://trac.ffmpeg.org/ticket/11055#comment:201
    (more complete review to be done)

**Comment by solomoncyj** [comment]
found a few libs we could use : https://github.com/alexa/webvtt https://github.com/caitp/webvtt https://github.com/WebKit/WebKit/blob/main/Source/WebCore/html/track/WebVTTParser.cpp

**Comment by llyyr** [comment]
Parsing is the easy part, the hard part is converting it to ASS so libass can render it for us.

**Comment by solomoncyj** [comment]
try this https://github.com/zezo010/Elgindy-VTT-to-SRT-Subtitle-Converter
