### ISSUE TITLE
Audio filter gets disabled when pausing/resuming or when opening new content

### ISSUE THREAD

**Issue by realnc** [mpv-player/mpv#7220]
### mpv version and platform
Built with mpv-build.
```
mpv 0.30.0-259-gb6f605285c Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Mon Dec  2 23:19:26 EET 2019
ffmpeg library versions:
   libavutil       56.36.101
   libavcodec      58.64.101
   libavformat     58.35.100
   libswscale      5.6.100
   libavfilter     7.67.100
   libswresample   3.6.100
ffmpeg version: N-95944-g968c4cbf22
```

### Reproduction steps
* Add `af-add=@dynrange:!compand=0:1:-90/-900|-70/-70|-30/-9|0/-3:6:0:0:0` in `mpv.conf`.
* Add `n af toggle @dynrange` to `input.conf`.
* Load a video.
* Press `n` to activate the filter.
* Press space to pause, then again to resume.

The filter gets disabled.

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/3917024/log.txt)

**Comment by stifani** [comment]
I was just posting something like this, but related to `video filters` (`vf`). 
The video filter table gets cleared when pausing some video.
And if you try to apply filters again, when the video is paused, then it gets cleared again.
You can try with simple filters like `hflip` or `vflip`

**Comment by realnc** [comment]
Oh, and I just found out that it also happens when you change the audio volume.

**Comment by wm4** [comment]
Regression from the option change thing, any change will reset filters.
