### ISSUE TITLE
input-ipc-server regression/change - sending stop + loadfile stops playback

### ISSUE THREAD

**Issue by mk-fg** [mpv-player/mpv#7225]
### mpv version and platform

mpv-0.30.0 on Arch Linux.

### Reproduction steps

1. Start mpv playing any arbitrary file (e.g. "track1.mp3") with --input-ipc-server socket option.

2. Send following two commands on IPC socket in quick sequence:

    ```
    {"command":["stop"],"request_id":313}
    {"command":["loadfile","track2.mp3","replace"],"request_id":314}
    ```

    Note: playback of some other file running at the time is important here.

3. Receive IPC socket responses, observe whether playback stops or switches to "track2.mp3".

### Expected behavior

track2.mp3 starts playing, as a result of "loadfile" command executed after "stop".
This is what happened in mpv-0.29 and earlier versions.

### Actual behavior

Playback stops completely, mpv goes into idle state.

### Log file

Attached [output.log](https://github.com/mpv-player/mpv/files/3929566/output.log)

This is what mpv sends back on --input-ipc-server socket immediately after two above commands:
```
{"data":null,"request_id":313,"error":"success"}
{"data":null,"request_id":314,"error":"success"}
{"event":"audio-reconfig"}
{"event":"tracks-changed"}
{"event":"end-file"}
{"event":"audio-reconfig"}
{"event":"idle"}
```

### Sample files

Any files seem to produce such effect.

### Note

Haven't seen ordering of such somewhat-conflicting commands documented, so no idea if it can be considered bug/regression as such. Could've missed it in the docs though.

Noticed due to bug report for mpv emms (emacs music player) backend, which does quick stop/start at the high level to switch tracks, resulting in such sequence of commands to mpv backend.

Fixed it in the emms backend already (by waiting for "end-file" event after stop before issuing "loadfile" command), but wanted to report here in case it might be a legitimate and undesirable regression which might affect other users.

If it was intentional change, unimportant implementation detail or an otherwise known thing, please feel free to just close as invalid.

Thanks!

**Comment by wm4** [comment]
Probably regression due to --demuxer-termination-timeout?

**Comment by mk-fg** [comment]
> Probably regression due to --demuxer-termination-timeout?

Was likely not addressed to me, as I'm not familiar enough with the code to say, but just tried setting it to 0 and 0.5 via ~/.mpv/config and these values didn't seem to affect mentioned ipc behavior, at least with simple mp3 files.
