### ISSUE TITLE
feature propose: in case the --drm-connector flag is not given, iterate over all /dev/dri/cards*

### ISSUE THREAD

**Issue by kamomil** [mpv-player/mpv#7226]
Hi,
Currently, if the --drm-connector flag is not given, then `/dev/dri/card0` is used by default
but card0 may not support `drmModeGetResources` while other `/dev/dri/card*` do support.
I suggest to add a code that iterates over `/dev/dri/card*` until a suitable one is found.
I can send a patch for that.

thanks,
Dafna

**Comment by xantoz** [comment]
Not a bad idea.
I've also considered splitting out the card selection from drm-connector to become its own option, says "--drm-device" or "--drm-card" that'd just take the path to the devnode in question.

**Comment by Dudemanguy** [comment]
I believe this was fixed by #8502.
