### ISSUE TITLE
Viewing window

### ISSUE THREAD

**Issue by robrt1010101** [mpv-player/mpv#7232]
Hello I'm posting this to request a fix to a viewing problem with mpv. When I view a video taken from a iPhone that is vertical it extends beyond the upper & lower boundaries of my monitor. Also when I view 4K videos the video extends into my other monitor. Can you fix these issues so that a video is contained within the monitor that I'm viewing it on? I'm using mpv 0.30.0 on OS X 10.14.6 Thanks.

**Comment by Akemi** [comment]
--autofit=100%x100%
