### ISSUE TITLE
how to find the temporary cache folder?

### ISSUE THREAD

**Issue by Moriand** [mpv-player/mpv#7238]
## Question
 - I use Windows 8.1
How can I find the temporary cache folder when using **mpv player**
>**`C:\Users\Name>`mpv --ytdl link_youtube**

Well using from the **cmd**, it doesn't tell me what folder the files are in and my question is that I want to know where the caches or files are stored.

**Comment by wm4** [comment]
It doesn't cache anything on disk by default, and if it does (which doesn't cache like a webserver and doesn't result in playable files), it's in a location explicitly configured by the user.
