### ISSUE TITLE
How to load scripts folder recursively?

### ISSUE THREAD

**Issue by snowman** [mpv-player/mpv#7249]
I have tons of mpv-scripts, and I want to organize them to respective folder from [User Scripts · mpv-player/mpv Wiki](https://github.com/mpv-player/mpv/wiki/User-Scripts). How to organize them to more readable?

```lua
-- $HOME/.config/mpv/scripts/custom.lua

mp.set_property("pause", "yes")
```

into 

```lua
-- $HOME/.config/mpv/scripts/custom/index.lua

require("pause_at_startup");
```

```lua
-- $HOME/.config/mpv/scripts/custom/pause_at_startup.lua

mp.set_property("pause", "yes");
```

**Comment by wm4** [comment]
No such thing is implemented.

**Comment by snowman** [comment]
If not implemented, this could be done in some way. so let's try it, why mpv not loading my subdirectories script?

```bash
$ cat $HOME/.config/mpv/scripts/custom/pause_at_startup.lua
mp.set_property("pause", "yes")
```

but this script does not load when starting mpv.
```bash
$ mpv --load-scripts=yes some.mp4
````

if I move `pause_at_startup.lua` one folder up, the script work. anything I have missing?

documentation:
[--load-scripts](https://mpv.io/manual/stable/#options-load-scripts)
[FILES -- ~/.config/mpv/scripts/](https://mpv.io/manual/stable/#files-~/-config/mpv/scripts/)
```text
--load-scripts=<yes|no>
If set to no, don't auto-load scripts from the scripts configuration
subdirectory (usually ~/.config/mpv/scripts/). (Default: yes)

~/.config/mpv/scripts/
All files in this directory are loaded as if they were passed to
the --script option. They are loaded in alphabetical order, and
sub-directories and files with no .lua extension are ignored. The
--load-scripts=no option disables loading these files.
```

**Comment by morphogo** [comment]
Sounds like a job for a script.

**Comment by snowman** [comment]
They are loaded in alphabetical order, and
sub-directories and files with no .lua extension ARE ignored.

`scripts` subdirectory not `scripts` subdirectories!

so you should write your own script to do the job.
