### ISSUE TITLE
0.3.8 - Laggy & Locking Up Crashing Coming Out Of Fullscreen

### ISSUE THREAD

**Issue by ghost** [mpv-player/mpv#725]
Hi,
These are my specs;

Slackware 14.1 x86_64
Openbox 3.5.2
GTX660 - driver 33.167
compton (git version)
xorg-server-1.14.3

I noticed if I have compton enabled using vdpau and I use f to go into full screen then press f again to come out, most of the time mpv then locks up and freezes.

If I disable compton it doesn't lock up freeze, but in 0.3.7 I was able to use compton ok without any problems, so I wanted to report this.

I've also been told it's better to use opengl so for now I've opted for that option with this in my config and it seems to work great;

vo=opengl
hwdec=vdpau

Keep up the great work!

**Comment by piedar** [comment]
I used to experience this issue too, but it appears to be fixed now after upgrading to

- media-video/mpv-0.9.2-r1
- x11-drivers/nvidia-drivers-352.30
- x11-libs/libvdpau-0.9

Thanks to whomever put in the work!
