### ISSUE TITLE
Is it possible to change the require(id) search path of javascript module?

### ISSUE THREAD

**Issue by snowman** [mpv-player/mpv#7250]
document
[CommonJS modules and require(id)](https://mpv.io/manual/stable/#commonjs-modules-and-require-id)

> A .js file extension is always added to id, e.g. require("./foo") will
load the file ./foo.js and return its exports object.
>
> An id is relative (to the script which require'd it) if it starts with
./ or ../. Otherwise, it's considered a "top-level id" (CommonJS
term).
>
> Top level id is evaluated as absolute filesystem path if possible
(e.g. /x/y or ~/x). Otherwise, it's searched at scripts/modules.js/ in
mpv config dirs - in normal config search order. E.g. require("x") is
searched as file x.js at those dirs, and id foo/x is searched as file
foo/x.js.

```text
$ tree $HOME/.config/mpv/scripts/mpv-tools
$HOME/.config/mpv/scripts/mpv-tools
├── Blackbox.js
├── Colorbox.js
├── Gallerizer.js
├── Leapfrog.js
├── auto-keep-gui-open.lua
├── cycle-video-rotate.lua
├── modules.js  <-- How to add "$HOME/.config/mpv/scripts/mpv-tools/modules.js" to js module search path?
│   ├── AssFormat.js
│   ├── MicroUtils.js
│   ├── Options.js
│   ├── PathIndex.js
│   ├── PathTools.js
│   ├── PlaylistManager.js
│   ├── PseudoRandom.js
│   ├── RandomCycle.js
│   ├── SelectionMenu.js
│   └── Stack.js
├── multi-command-if.lua
└── quick-scale.lua
```

**Comment by avih** [comment]
Currently the modules search path is fixed to the config dirs, and it's not possible to add custom search paths.

**Comment by morphogo** [comment]
You can also try overriding the require function so that if the module id doesn't start with a `.` or `/` it looks inside certain directories.

**Comment by avih** [comment]
> You can also try overriding the require function

While possible, it's not trivial, and that would have to account for modules which require other modules too, as there are multiple instances of the `require` function (there's one global, and one for each loaded module - with its own base path so that relative `require` would work also for modules at any path).

**Comment by morphogo** [comment]
Ah, okay. I didn't know that. In my setup, I just have a bootstrap script that loads all the other scripts.

**Comment by snowman** [comment]
Thanks for the replies, I would fix all up-stream scripts `require("blah")` function to make it relative `require("./blah")`.

**Comment by avih** [comment]
FWIW, I have a prototype which allows changing the modules search dirs via `mofule.paths` - currently singletone shated by all the `require` instances, and which the main script can modify too. Still not sure if it's worth adding, but I might.

**Comment by avih** [comment]
It's now possible to change the paths via `mp.module_paths`. See https://github.com/mpv-player/mpv/commit/4fc5cd32d022fbc898052bbc5beda2e618137aa4

**Comment by snowman** [comment]
Finally, it adds the feature which I loved. :heart: 

This means that I can download all the scripts from https://github.com/mpv-player/mpv/wiki/User-Scripts into a respective directory and require them when needed.
