### ISSUE TITLE
video-sync audio does not drop frames properly, works with display-vdrop

### ISSUE THREAD

**Issue by e00E** [mpv-player/mpv#7253]
### mpv version and platform

```
$ mpv --version
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.1
```
### Reproduction steps

On a machine with a slow processor and a 60 Hz display, play a 720p 60fps file. The processor is `Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz`.

### Behavior with an empty config file

`mpv --video-sync=audio` (default video-sync) does not keep audio and video and sync. The status line shows a growing A-V desync that keeps growing as long as the file is played.

`mpv --video-sync=display-vdrop` also shows a growing A-V desync but when it reaches roughly 0.02 a frame is dropped (which is displayed in the status bar) and the desync is reset to 0, slowly growing again. This repeats and keeps the audio and video in sync.

The reference mentions

> Although it should have the same effects as audio, the implementation is very different.

I am reporting this bug because the behavior is different. The behavior of `display-vdrop` is correct. The default behavior is incorrect.

### Log file

I am letting the file play for 30 seconds. Note that the log file does not contain the info from the status line. In the audio case the desync was 0.149 near the end and in the display-vdrop case there were 9 dropped frames.

audio: http://0x0.st/zUU_.txt

display-vdrop: http://0x0.st/zUU9.txt

**Comment by wm4** [comment]
Does the desync actually keep growing to significant values?
Could you try git master?

**Comment by e00E** [comment]
0.15 is already significant. I have seen it be > 1 and still growing. Still hapens on master. I used `mpv-git` from AUR to build.

**Comment by Dudemanguy** [comment]
I wonder if it's the combination of EGL 1.4 + wayland doing something weird. Does it still happen if you use `--gpu-context=x11egl`?

**Comment by e00E** [comment]
The problem goes away with `gpu-context=x11egl`, meaning it correctly drops frames.

**Comment by wm4** [comment]
Sounds like a wayland issue then. I wonder how this happens, since the framedrop logic should be relatively fool-proof. Maybe rendering just takes increasingly long for some weird reason or so.

**Comment by e00E** [comment]
> Maybe rendering just takes increasingly long for some weird reason or so.

When using `display-vdrop` on wayland I notice that even with 30 fps video (which does not drop frames) the *number of estimated number of vsyncs which took too long* grows steadily. With `gpu-context=x11egl` this does not happen.

**Comment by wm4** [comment]
What is too slow on your computer? Decoding or display?

**Comment by e00E** [comment]
How do I find out?

**Comment by wm4** [comment]
--vo=null to test whether the decoder delivers frames quickly enough.
For testing display... not sure. But if decoding is fast enough, below your display FPS, and the VO drops frames, it's probably slow display.

**Comment by e00E** [comment]
No frame drops with `vo=null`.

**Comment by Dudemanguy** [comment]
I've changed wayland a million times since the original report so this may or may not still occur. Feel free to open a new issue if the problem still exists.
