### ISSUE TITLE
Suggestion: Convert watch-later temporary files to m3u files

### ISSUE THREAD

**Issue by morphogo** [mpv-player/mpv#7254]
Currently watch-later temporary files are file-specific configuration files contain the `start` option.
 
But if the watch-later temporary files can be changed to m3u files, playback can be resumed by just playing the m3u files in the watch-later directory.

The `#EXT-X-START` tag can be used to specify the offset in seconds to start playback but is not yet supported by mpv.

The following is an example of an m3u file that starts playback 300 seconds into the file.

```
#EXTM3U
#EXT-X-START:300
/path/to/the/media/file/to/watch/later

```

**Comment by wm4** [comment]
I don't see any advantage in that. The watch later files are currently mpv config files, can store other options, and explicitly don't contain the filename by design, a m3u file would provide none of that.

**Comment by morphogo** [comment]
Okay. I get your point.
 
I see the watch-later files as a kind of bookmarks/savepoint I can set and which I want to go back and resume from.

But I guess in your design you see them as a kind of user history and you specifically want to protect your privacy.
