### ISSUE TITLE
How can i config to show rihgt chapter-list?

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#7255]
### mpv version and platform

mpv 0.30.0 newest x64 build in 
https://sourceforge.net/projects/mpv-player-windows/files/

### Reproduction steps

I play some mp4 with chapter-list have japanese name
And i only see garbled text like below
https://i.imgur.com/xMX3yHw.jpg

Where it can show correctly on MPC-BE 1.53
https://i.imgur.com/ZVE3h3t.jpg

How can i config the setting show chapter-lsit correctly in mpv?
Thank you for your watching.

**Comment by wm4** [comment]
This is probably just a mp4 with a broken charset or so. Do you have a sample file?

**Comment by kesdoputr** [comment]
Oh, the file is too big, how can i make a sample file just contain chapter-list?

**Comment by kesdoputr** [comment]
2wm4
I just reenocde file for start part and upload to bitsend(file size about 2mb only)
https://bitsend.jp/download/b11915c741b2a7788aabb88e19559713.html

May you take a look? Thank you. The chapter name display incorrect in mpv but normal in MPC-BE.

**Comment by wm4** [comment]
```
ffprobe output.mp4  2>&1|grep -a title|uchardet 
SHIFT_JIS
```
That answers the question. mpv always assumes UTF-8. Not sure what mp4 allows, and/or whether the character set is stored anywhere.

In theory, mpv could try to detect the charset automatically, but I'm somewhat worried about misdetections.

**Comment by kesdoputr** [comment]
Thanks for your reply, or it's possible to add an option on/off the charset detect?
If off then mpv use UTF-8
