### ISSUE TITLE
HEVC 4k is not using hardware decoding on MacOS

### ISSUE THREAD

**Issue by MaximKraev** [mpv-player/mpv#7256]
### mpv version and platform
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  3 20:28:56 CET 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.1

MacOS: 10.15.2 (19C57)
mpv is installed using homebrew, the same behavior with https://laboratory.stolendata.net/~djinn/mpv_osx/

### Reproduction steps
`mpv --no-config -v --hwdec=auto  LG\ New\ York\ HDR\ UHD\ 4K\ Demo.ts`
### Expected behavior
hardware acceleration working 

### Actual behavior
```
[ffmpeg/video] hevc: Unknown sw_format.
[ffmpeg/video] hevc: Failed setup for format videotoolbox_vld: hwaccel initialisation returned error.
```
### Log file

https://0x0.st/zURC.txt

### Sample files
Have that issies with any 4k hevc codec, including samples from https://4kmedia.org/lg-new-york-hdr-uhd-4k-demo/

**Comment by Akemi** [comment]
that file works here as intended with hwdec. either your build is broken, ffmpeg version is somehow broken or too old, or it's an ffmpeg issue.

also see the various [videotoolbox](https://github.com/mpv-player/mpv/issues?q=is%3Aopen+is%3Aissue+label%3Ahwdec%3Avideotoolbox) issues we have that are all ffmpeg related. if you can try with ffmpeg directly and it doesn't have issue, it's mpv related.

```
ffmpeg -hwaccel videotoolbox3 -i LG\ New\ York\ HDR\ UHD\ 4K\ Demo.ts -f null -
```

**Comment by MaximKraev** [comment]
`ffmpeg` with `-hwaccel videotoolbox` works fine
ffmpeg info:
```
ffmpeg --version      12.6s  Sat 14 Dec 23:55:53 2019
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.8)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.1_2 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/include/darwin -fno-stack-check' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
```

**Comment by MaximKraev** [comment]
compile mpv from source is solving the issue, but it is bringing others with the bundle.

**Comment by Akemi** [comment]
> ..., but it is bringing others with the bundle.

i hope you are not planning to make me guess?

**Comment by MaximKraev** [comment]
> i hope you are not planning to make me guess?

I am sorry, wasn't intended, I will report them separately as soon will be able to provide more details and logs. For now, I have strange freezes and higher CPU utilization on 1080p, but not something for investigation.
