### ISSUE TITLE
Unable to export movie to image

### ISSUE THREAD

**Issue by faxotherapy** [mpv-player/mpv#7258]
### mpv version and platform
MacOS Mojave

```
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Dec  7 12:46:46 GMT 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.1
```

### Reproduction steps
```
mpv --start=60 --sstep=1 --end=-60 --vo-image-outdir=Images Film.mp4
```

### Expected behavior
skip 1 min from beginning, skip 1 min from end, take snapshot every one sec, and export to Images dir under same folder where Film is located.

### Actual behavior
Export to images.

### Log file

Ouput log available at [here](https://privatebin.net/?3f884d20e040d0dd#2vysoPvaYUP681Ko8jQWengxMhARuWzwgiA6EvuYJdH5).

Another output log reported by MacOS Mojave itself (via Crash Reporter) available at [there](https://privatebin.net/?2513bb2d503def88#G1oDVv7P2ZMWcFTtXLfq3TGvi2PzMNXW1dM3tv7hPWwn).

I choose a random video for testing: this one from [here](https://www.youtube.com/watch?v=hb2yTNT2rBU) (downloaded it first using _youtube-dl_).

**Comment by wm4** [comment]
You need --vo=image.

**Comment by faxotherapy** [comment]
this is the error then:
```
[cplayer] Error parsing option vo-image (option not found)
[cplayer] Setting commandline option --vo-image=Images failed.
[cplayer]
[cplayer] Exiting... (Fatal error)
```
