### ISSUE TITLE
high CPU usage with --demuxer-thread=yes for live streams

### ISSUE THREAD

**Issue by myspaghetti** [mpv-player/mpv#7259]
### mpv version and platform
mpv 0.30.0-302-g2dbe33ce83 (git master) Windows x86_64
mpv 0.30.0 (release stable) Windows x86_64
OS: Windows 10 Home / Pro 1909 64-bit
CPU: Intel i7-8565U / Intel i7-7700HQ
GPU: Intel UHD Graphics 620 / Intel HD Graphics 630 / NVIDIA GeForce GTX 1050

### Reproduction steps
Play an h264 live video stream with default settings (demuxer-thread=yes) and no cache pause so the playback is on the very latest received frame. May depend on OS or CPU hwdec or GPU hwdec.

High CPU usage (10%-20%):
`mpv --demuxer-thread=yes --cache-pause=no --speed=2 --hwdec=auto rtsp://0.0.0.0:554/path/to/live/video.h264`
Normal CPU usage (0%-1%):
`mpv --demuxer-thread=no --cache-pause=no --speed=2 --hwdec=auto rtsp://0.0.0.0:554/path/to/live/video.h264`

### Expected behavior
`--demuxer-thread=yes` and `--demuxer-thread=no` should have the same CPU usage, around 0%-1%.

### Actual behavior
`--demuxer-thread=yes` results in 10%-20% CPU usage when playback reaches the very latest received frame from the h264 stream.

### Log file

[demuxer-thread-yes.txt](https://github.com/mpv-player/mpv/files/3965074/demuxer-thread-yes.txt)
[demuxer-thread-no.txt](https://github.com/mpv-player/mpv/files/3965075/demuxer-thread-no.txt)

### Sample files

Cannot attach sample file, but any live rtsp h264 stream should be able to be used to reproduce the issue.

**Comment by myspaghetti** [comment]
If you don't have a live stream you can fake one with `pv`

### Reproduction steps
Reproduced with theora file rate-limited with `pv`:
`pv -L 50k test4.mkv | 'mpv' --demuxer-thread=yes --input-terminal=yes - # 10%-20% CPU usage`
`pv -L 50k test4.mkv | 'mpv' --demuxer-thread=no --input-terminal=yes - # 0%-1% CPU usage`

### Log file
[fake-stream-demuxer-thread-yes.txt](https://github.com/mpv-player/mpv/files/3965279/fake-stream-demuxer-thread-yes.txt)
[fake-stream-demuxer-thread-no.txt](https://github.com/mpv-player/mpv/files/3965278/fake-stream-demuxer-thread-no.txt)

### Sample files
Sample h264 file from here: https://github.com/Matroska-Org/matroska-test-files/blob/master/test_files/test4.mkv

https://github.com/Matroska-Org/matroska-test-files/raw/master/test_files/test4.mkv

**Comment by wm4** [comment]
Is that all with --no-cache-pause?

The limited bandwidth isn't high enough for test4.mkv to play properly. 

Anyway, I can confirm that something seems to make CPU usage explode, maybe wakeup-ping-pong between the threads.

**Comment by myspaghetti** [comment]
Real streams require `--no-cache-pause`, otherwise the video pauses while the stream buffers to cache and there's no high CPU usage. Fake stream doesn't require `--no-cache-pause` because it doesn't buffer.

**Comment by wm4** [comment]
There's no such thing as "real" or "fake" streams. If you want to reduce buffering and latency, you probably don't want that mechanism enabled, sure.

**Comment by myspaghetti** [comment]
>There's no such thing as "real" or "fake" streams

I was just making a distinction between a network stream (a "real" stream) which is cached by default and a slowly-loading local file (a "fake" stream) which isn't cached by default.

>--cache=<yes|no|auto>

>Decide whether to use network cache settings (default: auto).

>The auto choice enables this depending on whether the stream is thought to involve network accesses or other slow media (this is an imperfect heuristic).

Either way the cache is tangential to the issue. Thanks for the really quick bugfix!
