### ISSUE TITLE
Assertion failure in vd_lavc when using vaapi with interpolation

### ISSUE THREAD

**Issue by LaserEyess** [mpv-player/mpv#7261]
### mpv version and platform
OS: GNU/Linux x86_64
CPU: Intel i7-7500U
GPU: Intel HD 620
mpv:
```
$ mpv --version
mpv 0.30.0-307-g0de881fa72 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Dec 15 10:25:44 EST 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.1 
```
Using mesa 19.3.0 and libva 2.5.0
### Reproduction steps
`mpv --no-config --hwdec=vaapi --video-sync=display-resample --interpolation shitty_anime.mkv`

### Expected behavior
Plays some god awful anime

### Actual behavior
Assertion failure while playing some really shitty anime: 
```mpv: ../video/decode/vd_lavc.c:1060: decode_frame: Assertion `mpi->planes[0] || mpi->planes[3]' failed.```

### Log file
log: https://0x0.st/z0oJ.log
backtrace: https://0x0.st/z0ov.txt

### Sample files
https://0x0.st/z0ow.mkv

Vulkan or opengl doesn't seem to matter. I did not try with X, only wayland. Even using `--video-sync=display-resample` without `--interpolation` seems to trigger it. This could easily be a broken file as well, I'm not sure. But the fact that it fails with this specific set of options is interesting.

**Comment by sfan5** [comment]
Same assertion failure as #7185, though these issues are likely unrelated.

**Comment by philipl** [comment]
I was able to reproduce after we established that the `iHD` va driver was in use. It does not fail when `vaapi-copy` is used, so it's presumably an issue with the interop code - which has happened before with `iHD`. Good times.

**Comment by philipl** [comment]
So we've established that the assert is buggy. `0` is a valid VA surface ID and is getting used in this case. We can't blindly assert that planes[3] is not `0` for valid hw surfaces.
