### ISSUE TITLE
Video multitrack   with .mkv extension 

### ISSUE THREAD

**Issue by Moriand** [mpv-player/mpv#7262]
### mpv version and platform

Ultimate
windows 8.1

### Question
Hi, I have a **video where you have 3 video tracks**.
 - **The first** clue is taken from an angle.
 - **The second** of another angle and **the third** also.

In MPV I have not seen an icon that makes this type of change, is there any keyboard shortening that fulfills this function

**Comment by wm4** [comment]
There's "_", but it also rotates through disabling video, which could be confusing.

**Comment by Moriand** [comment]
Excelent, in keyboard
**shift + _**
