### ISSUE TITLE
Window doesn't stay maximized if aspect ratio is changed.

### ISSUE THREAD

**Issue by Samillion** [mpv-player/mpv#7265]
### mpv version and platform

```
mpv 0.30.0-284-gb2b15d4e6e Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  8 09:12:39 +08 2019
ffmpeg library versions:
   libavutil       56.36.101
   libavcodec      58.64.101
   libavformat     58.35.101
   libswscale      5.6.100
   libavfilter     7.68.100
   libswresample   3.6.100
ffmpeg version: git-2019-12-07-e1d836d2

Windowx 10 x64 1909
```

### Reproduction steps

- Open a video file
- Maximize the window
- Change aspect ratio with a keybind (ie: Ctrl+a)

### Expected behavior

Window stays maximized.

### Actual behavior

Window doesn't stay maximized, it reverts to a smaller windowed mode.

Issue #386 kind of had a similar behavior but with a different scenario, is this the same case here?

If window is reset on aspect ratio change to accommodate for window size based on ratio, is that needed with a maximized window?

**Comment by Akemi** [comment]
if this issue still persists please open a new issue.

**Comment by avih** [comment]
I can still reproduce the issue:
- Run `mpv --no-config av://lavfi:testsrc=size=500x500`
- Maximize the window (NOT fullscreen), e.g. by double-clicking the title-bar.
- Press `shift-a` to change aspect ratio.

Expedted behavior: window stays maximized.

Actual behavior: window exits maximized and becomes a normal window.

Log: https://gist.github.com/avih/650844fdc9e30d3958c214c07f14c8fe

**Comment by Samillion** [comment]
Auto-profile as a workaround for this:
```INI
[Maximized]
	profile-desc=No window resizing when maximized
	profile-cond=window_maximized and vid
	profile-restore=copy-equal
	auto-window-resize=no
```
