### ISSUE TITLE
Audio playback stuck at audio EOF reached when using overlay filter-complex.

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#7266]
### mpv version and platform
```mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
built on Tue Nov 12 00:20:16 CET 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.1
```
### Reproduction steps
```mpv http://wpage.unina.it/aorefice/sharevari/sample.mp3 --start=99%   --lavfi-complex="[aid1]asplit=3[azero][auno][ao];[azero]showspectrum[spectrum];[auno]showwaves[waves];[spectrum][waves]overlay[vo]"```

### Expected behavior
mpv should exit.

### Actual behavior
mpv hangs maximizing one core.

### Log file
https://0x0.st/z0K7.log

### Sample files
Uploaded.

Not all files give the problem.

**Comment by kokoko3k** [comment]
Seems that overlay=repeatlast=0 fixes it.
However, it worked without it in the past, and setting overlay=eof_action=endall or overlay=shortest=1 does not.

**Comment by wm4** [comment]
The original command always exits for me.

**Comment by kokoko3k** [comment]
Weird, when it is stuck, i see a infinite calls to getpid
```
[pid 468236] getpid()                   = 468236
[pid 468236] getpid()                   = 468236
[pid 468236] getpid()                   = 468236
[pid 468236] getpid()                   = 468236
[pid 468236] getpid()                   = 468236
```

**Comment by wm4** [comment]
--ao=null and --ao=alsa work for me.

**Comment by wm4** [comment]
Anyway, would love to fix, but no reproduction, so I'll close this.
