### ISSUE TITLE
Recording cache while playing back a stream using `stream-record` with the JSON IPC

### ISSUE THREAD

**Issue by ipatch** [mpv-player/mpv#7275]
### mpv version and platform

```
mpv --version
mpv 0.30.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sun Nov  3 20:28:56 CET 2019
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.1
```

- Installed via homebrew on macOS 10.13.6 with all patches applied

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

run the below command from an interactive bash session

```shell
echo '{ "command": [ "set_property", "stream-record" "/path/to/store/file.ts" ] }' | socat - /tmp/mpvsocket | jq -r '.data'
```

The above command will begin recording the current mpv instance that is connected to the current mpv socket, I believe only one running mpv instance can connect to the `/tmp/mpvsocket` which is how I'm using mpv.

I use mpv to playback various internet audio streams throughout the day.  Sometimes I rewind the stream to hear something again, and even sometimes I like to record the playback that I'm listening too.

### Expected behavior

I'd like to be able to rewind ie. seek backwards in the cache of a currently playing back stream that I'm listening too, and then start a recording using the above mentioned shell command to start recording the playback at the current position that I rewound the stream too.

### Actual behavior

However, I rewind the stream to a certain position within the cache / history of the stream and then begin recording the stream, the recording **does not** start recording where I rewond too, but rather where the current stream is in the buffer (not sure I can explain that better)

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it. If the issue is a build failure, upload build/config.log instead.

If this is a normal runtime bug, and no log is provided, the issue will be
closed for ignoring the issue template. This is because analyzing a bug without
a log file is harder than necessary. Low quality bug reports are noise.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wm4** [comment]
That's as designed. the manpage suggests to use the ``dump-cache`` command to record specific parts of the cache.
- if you just want to make excerpts of a live stream or so, use dump-cache (and possibly the disk-cache so you can cache large amounts of data without needing too much RAM)
- if you want to fully record a live stream, use --stream-record
