### ISSUE TITLE
mpv doesn't play audio from hdmi

### ISSUE THREAD

**Issue by fmarzocca** [mpv-player/mpv#7276]
### mpv version and platform
0.27.2 on LInux Mint 19.3

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
start a video (any format)

### Expected behavior
getting sound and video from HDMI

### Actual behavior
No sound

### Log file
attached
[output.txt](https://github.com/mpv-player/mpv/files/3991466/output.txt)

**Comment by CounterPillow** [comment]
>0.27.2 on LInux Mint 19.3

update

**Comment by fmarzocca** [comment]
sudo apt install mpv
[sudo] password di fabio:
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze
Lettura informazioni sullo stato... Fatto
mpv è già alla versione più recente (0.27.2-1ubuntu1).

It means that it is at latest version available.

**Comment by CounterPillow** [comment]
We don't care if it's the latest version your distro packages, it's not the latest version that we released. We have no control over the years out of date versions that Linux Mint is giving you.

**Comment by fmarzocca** [comment]
Thank you.
your crude response is not much appreciated. Next time, try to be kinder

**Comment by fmarzocca** [comment]
> We don't care if it's the latest version your distro packages, it's not the latest version that we released. We have no control over the years out of date versions that Linux Mint is giving you.

And I don't care about your software. I am not going to mess up my system for you. There are tons of alternatives.

**Comment by CounterPillow** [comment]
lol bye
