### ISSUE TITLE
[Win]Some video can't play correctly

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#7277]
### mpv version and platform
mpv 0.30.0 x64 newest build at 
https://sourceforge.net/projects/mpv-player-windows/files/
system is Windows 7 SP1 x64

### Reproduction steps
The problem confused me for long time, I have some video that can't play correctly with mpv
I can only see mosaic in display and many error in the console.

But today i try to use old version at 
https://mpv.srsfckn.biz/

I found that when i use 0.25.0 and previous version
https://mpv.srsfckn.biz/mpv-x86_64-20170423.7z
The video can be show correctly

Screenshot when use 0.25.0, it's normal
https://i.imgur.com/iTAxM6I.jpg
Screenshot when use after 0.25.0(0.30.0 on picture), i only can see mosaic.
https://i.imgur.com/bgeAgrF.png

Is there an option i can let new version play the video correctly? Thank you.

Here is the sample video
https://bitsend.jp/download/82e93982ae93ed807129a54abf1b1ffd.html
Thanks for your watching.

**Comment by bitraid** [comment]
That's because  the (latest) ffmpeg h264 decoder finds errors in the stream for some reason (use `-v`):
```
[h264 @ 00000289786711c0] top block unavailable for requested intra mode
[h264 @ 00000289786711c0] error while decoding MB 66 0, bytestream 48442
[h264 @ 00000289786711c0] concealing 8143 DC, 8143 AC, 8143 MV errors in P frame
[h264 @ 000002897792bf80] gray chroma
[h264 @ 000002897792bf80] error while decoding MB 36 0, bytestream 26345
[h264 @ 000002897792bf80] concealing 8160 DC, 8160 AC, 8160 MV errors in P frame
[h264 @ 000002897792a8c0] concealing 8097 DC, 8097 AC, 8097 MV errors in P frame
[h264 @ 000002897792bb00] concealing 6836 DC, 6836 AC, 6836 MV errors in B frame
[h264 @ 000002897792c440] concealing 7800 DC, 7800 AC, 7800 MV errors in B frame
[h264 @ 000002897792b680] Reference 3 >= 3 1716KB sq=    0B f=0/0
[h264 @ 000002897792b680] error while decoding MB 21 0, bytestream 47825
[h264 @ 000002897792b680] concealing 8160 DC, 8160 AC, 8160 MV errors in P frame
[h264 @ 0000028977928d80] top block unavailable for requested intra mode -1
[h264 @ 0000028977928d80] error while decoding MB 77 0, bytestream 13856
[h264 @ 0000028977928d80] concealing 8132 DC, 8132 AC, 8132 MV errors in B frame
[h264 @ 000002897792a440] gray chromaB vq= 1654KB sq=    0B f=0/0
[h264 @ 000002897792a440] error while decoding MB 68 12, bytestream 7516
...
```

**Comment by CounterPillow** [comment]
The problem is that this video was encoded with an old buggy version of x264, but had its SEI stripped so ffmpeg can't detect this version. You can manually set `--vd-lavc-assume-old-x264=yes` to work around this.

**Comment by kesdoputr** [comment]
Thanks for your reply, vd-lavc-assume-old-x264=yes works fine :)
