### ISSUE TITLE
[Win] Program crashed when use metadata-codepage

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#7279]
### mpv version and platform
mpv 0.30.0 x64 newest build at 
https://sourceforge.net/projects/mpv-player-windows/files/
system is Windows 7 SP1 x64

### Reproduction steps
I report an issue
https://github.com/mpv-player/mpv/issues/7255
And commit 8448fe0 add an option --metadata-codepage=

But when i try --metadata-codepage=auto or --metadata-codepage=SHIFT_JIS
I get mpv crashed as below
https://i.imgur.com/8lS9dVM.png

Thaks for your watching.

**Comment by wm4** [comment]
Sample file?

**Comment by wm4** [comment]
Never mind.
