### ISSUE TITLE
"copy" output codecs when encoding

### ISSUE THREAD

**Issue by ghedo** [mpv-player/mpv#728]
avconv supports using the special "copy" audio/video codecs, that simply copy (duh!) the streams from input to output without doing any decoding/encoding, so I've looked into adding something similar for mpv.

My idea was to add acopy/vcopy flags into encode_lavc_context, dec_audio and dec_video so that ad/vd_lavc would stuff the read AVPacket somewhere instead of decoding it, and ao/vo_lavc would read that packet and write it to the output as is.

I haven't done anything yet though, because looking into the code there are a few things that I don't understand. E.g. what happens if audio/video_decode() return an empty buffer?

Or maybe there's a better way to do this...

**Comment by wm4** [comment]
Nobody even maintains our encoding mode, so I guess this is hopeless anyway.
