### ISSUE TITLE
How do I catch osd-msg3 event in Lua?

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#7280]
I want `osd-msg3` to show time taking playback speed into consideration.
Something like this `osd-msg3="${duration}/${speed}"` only to do the division.

**Comment by wm4** [comment]
You can set osd-msg3 as property from a Lua script. You need to get the other properties yourself, perform the division, and set the result as string.

**Comment by oltodosel** [comment]
But how do I force `osd-msg3` to change?
In the snippet below `osd-msg3` only gets value once and then shows the same result every time.
```lua
function osd3()
	return mp.get_property("time-pos")
end

function started()
	mp.set_property("osd-msg3", osd3())
end

mp.register_event("file-loaded", started)
```

**Comment by wm4** [comment]
What you have is just a function call on the file-loaded event. It's not called at any other time. There's also no way to get a Lua function called when the "osd-msg3" property is read.
So you need to update the "osd-msg3" property manually whenever your value changes.
