### ISSUE TITLE
mpv fails to build with --disable-swift flag

### ISSUE THREAD

**Issue by orion1vi** [mpv-player/mpv#7282]
### mpv version and platform

Since c8cc203735d73f62def2692d1027f45ac10c03db, macOS 10.14.6

### Reproduction steps

./waf configure --enable-libmpv-shared --enable-lua --disable-libbluray --disable-rubberband --disable-swift
./waf

### Expected behavior

./waf builds successfully with --disable-swift

### Actual behavior

./waf fails to build with --disable-swift successfully

### Log file

Building on 0eabc6614a0d7c5d8d57a8a74d7b7447677038cd
> [225/413] Compiling common/msg.c
> ../osdep/macosx_application.m:195:13: error: use of undeclared identifier 'vo_sub_opts'
>     return &vo_sub_opts;

**Comment by Akemi** [comment]
feel free to test #7283 and let me know if this fixes it for you.

**Comment by orion1vi** [comment]
yes, this fixes the problem, thanks

**Comment by Akemi** [comment]
thx for testing.
