### ISSUE TITLE
cycling osc from input.conf fails

### ISSUE THREAD

**Issue by rien333** [mpv-player/mpv#7284]
### mpv version and platform

```console
$ mpv --version
mpv 0.30.0-396-g86d24b069b Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Mon Dec 23 13:07:41 CET 2019
$ uname -mor
5.4.6-arch1-1 x86_64 GNU/Linux
```

### Reproduction steps

1. Add `o cycle osc` to `input.conf`.
2. Press <kbd>o</kbd>.

### Expected behavior

mpv cycles the osc visibility (based on [this part of the manual](https://mpv.io/manual/master/#options-osc)). This used to work (I think it still worked for me with a build from yesterday?), but probably fails due to commits to the osc code that have been happening over the last day or so. 

That said, I'm not sure if this is the appropriate way to cycle the osc anyway. 

### Actual behavior

When pressing <kbd>o</kbd> (i.e. running `cycle osc`), mpv displays:
```
[osc] Command osd-overlay: argument res_x has incompatible type.
```

The osc visibility is not toggled, either. 

### Log file

https://0x0.st/zGr7.txt

### Sample files

Happens for all files.

**Comment by rien333** [comment]
Well, this seemed to have been fixed in the course of writing this issue.

**Comment by wm4** [comment]
Yeah, it was broken on master for about 1 or 2 hours.
