### ISSUE TITLE
odd behavior, sometimes loads the cover image and sometimes not.

### ISSUE THREAD

**Issue by Fitap** [mpv-player/mpv#7288]
### mpv version and platform
gentoo media-video/mpv-0.29.1-r1

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
From dolphin click on flac files.

### Expected behavior
Load cover art

### Actual behavior
Sometimes loads cover art, but also, sometime doesn;t load cover art.
### Log file

[output.txt](https://github.com/mpv-player/mpv/files/3999611/output.txt)

**Comment by Dudemanguy** [comment]
Pretty old issue but it was probably just that sometimes the flac files had cover art embedded in them and sometimes they didn't. Master mpv loads cover art files by default (based on a whitelist) so this shouldn't be an issue anymore.
