### ISSUE TITLE
How to create a shortcut key to change frames per sec to 2 fps or 1 fps

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#7289]
### mpv version and platform
$ mpv --version 
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.2

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
I want to create a shortcut key by which i can change the frame rate from actual to 2fps and again back to actual. 
I added in the input.conf

Shift+s set fps 2

### Expected behavior
And in the mpv player tried Shift+s and expecting the framerate to change to 2 fps

### Actual behavior
Frame rate does not changes
### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it. If the issue is a build failure, upload build/config.log instead.

If this is a normal runtime bug, and no log is provided, the issue will be
closed for ignoring the issue template. This is because analyzing a bug without
a log file is harder than necessary. Low quality bug reports are noise.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wm4** [comment]
There's no native way to do this. You could try to use the "vf toggle" command with the ffmpeg ``fps`` filter.
