### ISSUE TITLE
How to get screenshots of the entire video @6fps

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#7290]
### mpv version and platform
$ mpv --version                                       
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Sun Dec  9 16:21:27 CET 2018
ffmpeg library versions:
   libavutil       56.22.100
   libavcodec      58.35.100
   libavformat     58.20.100
   libswscale      5.3.100
   libavfilter     7.40.101
   libswresample   3.3.100
ffmpeg version: n4.1.2

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
mpv --vo=image --sstep=0.15 test_g_shop.mp4
### Expected behavior
I was expecting a screenshot every 0.15sec 
### Actual behavior
$  mpv --vo=image --sstep=0.25 file.mp4 
Resuming playback. This behavior can be disabled with --no-resume-playback.
Playing: file.mp4
 (+) Video --vid=1 (*) (h264 1280x960 6.000fps)
[nextfile] file.mp4 
[nextfile] file.mp4 
VO: [image] 1280x960 yuv420p
[vo/image] Saving 00000001.jpg
V: 00:00:18 / 01:38:46 (0%)
[vo/image] Saving 00000002.jpg
V: 00:00:41 / 01:38:46 (0%)
[vo/image] Saving 00000003.jpg
V: 00:01:23 / 01:38:46 (1%)
[vo/image] Saving 00000004.jpg
V: 00:02:05 / 01:38:46 (2%)
[vo/image] Saving 00000005.jpg
V: 00:02:46 / 01:38:46 (2%)
[vo/image] Saving 00000006.jpg
V: 00:03:28 / 01:38:46 (3%)
[vo/image] Saving 00000007.jpg
V: 00:04:10 / 01:38:46 (4%)
[vo/image] Saving 00000008.jpg
V: 00:04:51 / 01:38:46 (4%)
[vo/image] Saving 00000009.jpg
V: 00:05:33 / 01:38:46 (5%)
[vo/image] Saving 00000010.jpg
V: 00:06:15 / 01:38:46 (6%)
[vo/image] Saving 00000011.jpg
V: 00:06:56 / 01:38:46 (7%)
[vo/image] Saving 00000012.jpg
V: 00:07:38 / 01:38:46 (7%)
[vo/image] Saving 00000013.jpg
V: 00:08:20 / 01:38:46 (8%)
[vo/image] Saving 00000014.jpg
V: 00:09:01 / 01:38:46 (9%)
[vo/image] Saving 00000015.jpg
V: 00:09:43 / 01:38:46 (9%)
[vo/image] Saving 00000016.jpg
V: 00:10:25 / 01:38:46 (10%)
[vo/image] Saving 00000017.jpg
V: 00:11:06 / 01:38:46 (11%)
[vo/image] Saving 00000018.jpg
V: 00:11:48 / 01:38:46 (11%)
[vo/image] Saving 00000019.jpg
V: 00:12:30 / 01:38:46 (12%)
[vo/image] Saving 00000020.jpg
V: 00:13:11 / 01:38:46 (13%)
[vo/image] Saving 00000021.jpg
V: 00:13:53 / 01:38:46 (14%)
[vo/image] Saving 00000022.jpg
V: 00:14:35 / 01:38:46 (14%)
[vo/image] Saving 00000023.jpg
V: 00:15:16 / 01:38:46 (15%)
[vo/image] Saving 00000024.jpg
V: 00:15:57 / 01:38:46 (16%)
[vo/image] Saving 00000025.jpg
V: 00:16:39 / 01:38:46 (16%)
[vo/image] Saving 00000026.jpg
V: 00:17:20 / 01:38:46 (17%)
[vo/image] Saving 00000027.jpg
V: 00:18:02 / 01:38:46 (18%)
[vo/image] Saving 00000028.jpg
V: 00:18:44 / 01:38:46 (18%)
[vo/image] Saving 00000029.jpg
V: 00:19:21 / 01:38:46 (19%)
[vo/image] Saving 00000030.jpg
V: 00:20:03 / 01:38:46 (20%)
[vo/image] Saving 00000031.jpg
V: 00:20:44 / 01:38:46 (21%)
[vo/image] Saving 00000032.jpg
V: 00:21:05 / 01:38:46 (21%)
[vo/image] Saving 00000033.jpg
V: 00:21:46 / 01:38:46 (22%)
[vo/image] Saving 00000034.jpg
V: 00:22:28 / 01:38:46 (22%)
[vo/image] Saving 00000035.jpg
V: 00:23:10 / 01:38:46 (23%)
[vo/image] Saving 00000036.jpg
V: 00:23:51 / 01:38:46 (24%)
[vo/image] Saving 00000037.jpg
V: 00:24:33 / 01:38:46 (24%)
[vo/image] Saving 00000038.jpg
V: 00:25:15 / 01:38:46 (25%)
[vo/image] Saving 00000039.jpg
V: 00:25:56 / 01:38:46 (26%)
[vo/image] Saving 00000040.jpg
V: 00:26:10 / 01:38:46 (26%)
[vo/image] Saving 00000041.jpg
V: 00:26:52 / 01:38:46 (27%)
[vo/image] Saving 00000042.jpg
V: 00:27:34 / 01:38:46 (27%)
[vo/image] Saving 00000043.jpg
V: 00:28:15 / 01:38:46 (28%)
[vo/image] Saving 00000044.jpg
V: 00:28:47 / 01:38:46 (29%)
[vo/image] Saving 00000045.jpg
V: 00:29:29 / 01:38:46 (29%)
[vo/image] Saving 00000046.jpg
V: 00:30:10 / 01:38:46 (30%)
[vo/image] Saving 00000047.jpg
V: 00:30:52 / 01:38:46 (31%)
[vo/image] Saving 00000048.jpg
V: 00:30:57 / 01:38:46 (31%)
[vo/image] Saving 00000049.jpg
V: 00:31:39 / 01:38:46 (32%)
[vo/image] Saving 00000050.jpg
V: 00:32:21 / 01:38:46 (32%)
[vo/image] Saving 00000051.jpg
V: 00:33:02 / 01:38:46 (33%)
[vo/image] Saving 00000052.jpg
V: 00:33:44 / 01:38:46 (34%)
[vo/image] Saving 00000053.jpg
V: 00:34:26 / 01:38:46 (34%)
[vo/image] Saving 00000054.jpg
V: 00:35:07 / 01:38:46 (35%)
[vo/image] Saving 00000055.jpg
V: 00:35:15 / 01:38:46 (35%)
[vo/image] Saving 00000056.jpg
V: 00:35:56 / 01:38:46 (36%)
[vo/image] Saving 00000057.jpg
V: 00:36:38 / 01:38:46 (37%)
[vo/image] Saving 00000058.jpg
V: 00:37:20 / 01:38:46 (37%)
[vo/image] Saving 00000059.jpg
V: 00:38:01 / 01:38:46 (38%)
[vo/image] Saving 00000060.jpg
V: 00:38:41 / 01:38:46 (39%)
[vo/image] Saving 00000061.jpg

Where as if i try again it only gets screenshot of 1 image

$ mpv --vo=image --sstep=0.25file.mp4 
Resuming playback. This behavior can be disabled with --no-resume-playback.
Playing: file.mp4
 (+) Video --vid=1 (*) (h264 1280x960 6.000fps)
[nextfile] file.mp4 
[nextfile] file.mp4 
VO: [image] 1280x960 yuv420p
[vo/image] Saving 00000001.jpg
(Paused) V: 01:38:46 / 01:38:46 (99%)
Saving state.

Exiting... (Quit)

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it. If the issue is a build failure, upload build/config.log instead.

If this is a normal runtime bug, and no log is provided, the issue will be
closed for ignoring the issue template. This is because analyzing a bug without
a log file is harder than necessary. Low quality bug reports are noise.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wm4** [comment]
Either a script or a config file option is probably interfering, can't tell more because no log file.
