### ISSUE TITLE
Proposal: playlist-shuffle [off], external complex shuffles

### ISSUE THREAD

**Issue by himdel** [mpv-player/mpv#7294]
Right now, the shuffle behaviour is not really handling 3 use cases:

* no way to go the the next or previous file (in original order) when running shuffled  
I often run  `mpv -shuffle **/*.*`, but sometimes, you hit a random episode of something and want to skip to the next episode of the same show, but there's no way to undo the shuffle.

* pick something random, and then play it in order, and then pick something else
Useful when playing music and you want the whole album in order, but then go to random album.

* deal with two-parters (or multipart in general)  
Even with `-shuffle`, "2x03-Whatever, Part 1.mp4" and "2x04-Whatever, Part 2.mp4" should be played together  although that one really depends on the users naming convention.

---

For the first, I propose adding an optional `on|off` param to the `playlist-shuffle` binding, thus allowing to use both separate keybindings (`S playlist-shuffle`, `s playlist-shuffle off`), and cycling (`S cycle-values playlist-shuffle on off`).

The `off` behaviour could just `playlist-clear`, restore the playlist to a copy created before shuffling for the first time, move the current file to the right position (I guess expanding unexpanded folders to *find* the right position), and dedup it.

----

For the second, *perhaps* `playlist-shuffle folders` could be used, create a list of folders from all the files in the playlist, uniq and shuffle, then sort the playlist by the folder order, using a stable sort.

*But* the third would necessarily have to deal with conventions like `_1` and `_2` or `Part 1`, or `1a parte`, or `(3/4)`... And would thus need the user to provide regexes to match these conventions and the right ordering, which sounds *too* complex.

=> For the second and third, proposing a `shuffle-command` option, which allows external programs to deal with the shuffling logic.  
Such command would be run every time the playlist needs to be shuffled, with each playlist item as a separate line on standard input, and would output the shuffled list on standard output.

Thus, `shuffle-command="tac"` would reverse the playlist instead of shufling, while something like `shuffle-command=" while read foo; do echo $foo `dirname $foo`; done | sort -R -k2 | awk '{ print $1 }' "` actually works for shuffling folders (solves the second issue, except it's a bad example because it won't handle spaces).

WDYT? :)

**Comment by Ckath** [comment]
while your requests don't fully overlap, something similar was briefly discussed before in #2491, and everything mentioned there still applies(afaik). for the other usecases you listed, they seem fairly specific to me, as in I doubt anyone would use this besides yourself, but others might think different of that. 

that said, you could probably get pretty far realizing some of that behavior with a script.

**Comment by wm4** [comment]
Like said in the other issue, shuffling reorders the playlist. It does not mean that the next playlist entry is chosen randomly; instead the playlist is shuffled and then played in order.

If this were a player with some more advanced playlist management, it'd be reasonable to make shuffle just select random playlist entries, and to have separate commands to navigate the play history and going to the "next" playlist entry. We'd probably have some in-player playlist editor. While I wouldn't mind having that, mpv's playlist handling is primitive, and it doesn't look like it's going anywhere. It's probably better left to GUIs using libmpv and implementing their own playlist handling.

So at best, we could probably have a "playlist-unshuffle" command, which could use an integer indicating the original order or so, and then hope for the best that it somehow matches what people want.

Unless someone volunteers to redesign and rewrite mpv's playlist handling?

We certainly don't want to call the shell in mpv for playlist shuffling. A more reasonable thing to do would be to make the "playlist" property writable (so Lua scripts could implement their own shuffle command). There's also a ``playlist-move`` command, which could be used by scripts for shuffling (but would be quite painful to use).

**Comment by wm4** [comment]
There's some sort of unshuffle command now. A "toggle" (like changing the ``shuffle`` option/property at runtime) is still not possible because shuffling modifies the playlist.

**Comment by himdel** [comment]
Right, so, as far as I can tell, the consensus here is that for 2) and 3), this is out of scope of the project, and I'm better off implementing those in a custom frontend.

But unshuffling is possible, a dup of https://github.com/mpv-player/mpv/issues/2491,
and ... implemented in https://github.com/mpv-player/mpv/commit/5a261507173d28c762ba4f605d7983d928d4bf24 ?

I'm fine with that, thanks! :)

---

As far as the rest, I'm currently using an ancient wrapper script (originally written for mplayer) - https://github.com/himdel/dotfiles/blob/master/bin/mpl , which does implement those sorting options.. but it's impossible to unshuffle without converting it from a wrapper to something that uses mpv commands to sync the playlist, but I guess I'll try that.

Should we close the issue?
