### ISSUE TITLE
Cant select GPU device (index) while using cuda-copy

### ISSUE THREAD

**Issue by phkarmur** [mpv-player/mpv#7295]
https://github.com/mpv-player/mpv/blob/master/video/decode/vd_lavc.c#L431

add this after line: 431
`            AVBufferRef* ref = NULL;`
`            struct vd_lavc_params *opts = ctx->opts;`
`            char **kv = opts->avopts;`
`            char *cu_gpu = NULL;`
`            for (int n = 0; kv && kv[n * 2]; n++) {`
`                char *k = kv[n * 2 + 0];`
`                char *v = kv[n * 2 + 1];`
`                if(strcmp("gpu", k) == 0){`
`                    cu_gpu = v;`
`                    break;`
`                }`
`            }`
`            av_hwdevice_ctx_create(&ref, hwdec->lavc_device, cu_gpu, NULL, 0);   //av_hwdevice_ctx_create(&ref, hwdec->lavc_device, NULL, NULL, 0);`
`            return ref;`

**Comment by wm4** [comment]
The right way to do this is to add a< handler to ``hwcontext_fns[]`` in hwdec.c. Probably requires messing with the GL-specific handling of "--cuda-decode-device". hwcontext_fns_vaapi should make a good example.
CC @philipl maybe

**Comment by phkarmur** [comment]
@wm4 you are right, but according to manual people will use **--vd-lavc-o=gpu=<0..>** . so i made changes like this.
https://mpv.io/manual/master/#options-cuda-decode-device

**Comment by philipl** [comment]
Once upon a time, this worked using pass-through config because cuviddec would initialise its own hw context using its own config options.

More recently, but still a long time ago, we changed how initialisation worked so that if a decoder could be initialised with a hw context, we would provide one. At that point, the option stopped having any effect. @wm4 is right that the best way to reintroduce the capability is to use `hwcontext_fns` and forget about keeping the original option syntax working. I'll think about it for a bit.

**Comment by phkarmur** [comment]
Thanks @philipl 
And one more question, its not relevant to this question but still,
Closed captions isnt working in cuda-copy, and ffmpeg's -resize (--vd-lavc-o=resize=1920x1080) avoption isn't working in nvdec-copy.
So is it normal or bug? And both copy decoder using ####_cuvid decoders of ffmpeg or any other?
And can i close this issue or wait for patch?

**Comment by philipl** [comment]
That's normal. `cuviddec` is a full decoder and doesn't extract closed captions. And the resize option is specific to the `cuviddec` decoder. You shoudn't use `cuvidded` under normal conditions, and why are you using `copy` instead of normal `nvdec`.

**Comment by phkarmur** [comment]
well, i am using copy decoders because normal nvdec/cuda arent working, may be because im using dummy display in my headless centos 7 for video play. [https://techoverflow.net/2019/02/23/how-to-run-x-server-using-xserver-xorg-video-dummy-driver-on-ubuntu/](url) 

And im making video monitoring system like attached image using showvolume filter but the problem in this is, when video resolution is low at that time overlay'ed showvolume filter's output will be lowered resolution too. so I have to rescale/resize source video to full hd and then overlay showvolume, to make each volumebars identical. 
And I want to display CC too, but -resize and CC arent working together! 

![test](https://user-images.githubusercontent.com/16241179/71552303-6df03400-2a20-11ea-83fa-04ac53e1d6b3.png)

**Comment by philipl** [comment]
That's a complex scenario. How are you viewing the results of this? Are you using mpv as a recorder? Are you using a remote display protocol to view the desktop? You can run the nvidia driver in headless mode, which would be a strict improvement if you cared about viewing the desktop contents.

**Comment by phkarmur** [comment]
Im using ffmpeg to encode screens and output that to udp multicast. So we can view and monitor from anywhere. And moreover mpv has json ipc so we can control everything from remote too. :)
And i dont need to desktop contents so ffmpeg screen encoding is enough for now.

**Comment by philipl** [comment]
@phkarmur You really want to use `nvdec-copy` rather than `cuda-copy`. That will get captions working. Then your question is scaling - and I don't really understand what's not working for you, because I don't understand where mpv is sending the output in your configuration. Certainly you can use a scale filter: `--vf scale=1920x1080` for example. There is also a cuda accelerated scale filter in ffmpeg which you can use, but that means using `nvdec` and explicit downloading back to system memory.

So something like:

`mpv --hwdec=nvdec --vf scale_cuda=w=960:h=540,format=nv12`

This will use the full hwaccel, allowing it to be connected to the accelerated scale filter, and then downloaded back to system memory.

But at a first thought, I'm surprised mpv makes sense for the use case you have. I'd imagine a headless transcode pipeline with ``ffmpeg`` would give you an encoded stream, and that would open things up for using nvenc on the encoding side, etc - but I definitely don't pretend to understand your full context.

**Comment by phkarmur** [comment]
@philipl arent `scale_cuda` and `scale_npp` removed from ffmpeg? because I cant find them in ffmpeg filter or mpv fitler!
` ffmpeg -filters | grep scale`
`ffmpeg version git-2019-12-08-9f7b2b3 Copyright (c) 2000-2019 the FFmpeg developers`
 ` built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-39)`
  `configuration: --enable-gpl --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-nonfree --enable-version3 --enable-pic --enable-libfreetype --enable-libfdk-aac --enable-openssl --enable-shared --enable-libass --enable-libvpx --enable-libx265 --enable-libtwolame --enable-libpulse`
  `libavutil      56. 36.101 / 56. 36.101`
 ` libavcodec     58. 64.101 / 58. 64.101`
 ` libavformat    58. 35.101 / 58. 35.101`
  `libavdevice    58.  9.101 / 58.  9.101`
 ` libavfilter     7. 68.100 /  7. 68.100`
  `libswscale      5.  6.100 /  5.  6.100`
  `libswresample   3.  6.100 /  3.  6.100`
 ` libpostproc    55.  6.100 / 55.  6.100`
 `... alphaextract      V->N       Extract an alpha channel as a grayscale image component.`
 `... extractplanes     V->N       Extract planes as grayscale frames.`
` ..C scale             V->V       Scale the input video size and/or convert the image format.`
` ... scale_vaapi       V->V       Scale to/from VAAPI surfaces.`
 `..C scale2ref         VV->VV     Scale the input video size and/or convert the image format to the given reference.`

but i see cuvid/nvenc encoders and decoders in ffmpeg.
and from this [https://trac.ffmpeg.org/wiki/HWAccelIntro](url), we just need to install `nv-codec-headers`, right?

**Comment by phkarmur** [comment]
@philipl i have updated mpv to 0.31.0 and tried to select GPU using `--cuda-decode-device=1` but it still using GPU 0!
But i think, your changes only affects on openGL backend, while i am using `vo/x11`
`[vo/x11/x11] X11 opening display: :0`

logfile: [gpu_test.log](https://github.com/mpv-player/mpv/files/4009512/gpu_test.log)

**Comment by philipl** [comment]
I pushed the change yesterday. It’s not in 0.31...

**Comment by philipl** [comment]
Separately, to get `scale_cuda` and other cuda filters, you need to have `clang` installed to build the cuda kernels. (or the nvidia cuda sdk to use `nvcc` but that's considered to produce non-free output for dubious reasons).

**Comment by phkarmur** [comment]
@philipl i have compiled ffmpeg with `nvcc` and get scale_cuda and scale_npp filters. but somehow filter arent working 
it gives me this error: `[ffmpeg] Impossible to convert between the formats supported by the filter 'mpv_src_default_in' and the filter 'auto_scaler_0'`

command: `DISPLAY=:0 mpv --hwdec-codecs=all --hwdec=nvdec-copy --vf scale_cuda=w=960:h=540,format=nv12 udp://235.1.1.131:387 --msg-level=all=debug -log-file=scale_cuda_test.log --load-scripts=no`

logfile:  [scale_cuda_test.log](https://github.com/mpv-player/mpv/files/4010602/scale_cuda_test.log)

**Comment by phkarmur** [comment]
> I pushed the change yesterday. It’s not in 0.31...
ok, thank you.
and i tried to use scale_cuda and scale_npp in ffmpeg too but getting same filter error.
ffmpeg config: `--enable-gpl --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-nonfree --enable-version3 --enable-pic --enable-libfreetype --enable-libfdk-aac --enable-openssl --enable-shared --enable-libass --enable-libvpx --enable-libx265 --enable-libtwolame --enable-libpulse --enable-cuda-sdk --enable-cuvid --enable-nvenc --enable-nonfree --enable-libnpp --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64`

**Comment by philipl** [comment]
> @philipl i have compiled ffmpeg with `nvcc` and get scale_cuda and scale_npp filters. but somehow filter arent working
> it gives me this error: `[ffmpeg] Impossible to convert between the formats supported by the filter 'mpv_src_default_in' and the filter 'auto_scaler_0'`
> 
> command: `DISPLAY=:0 mpv --hwdec-codecs=all --hwdec=nvdec-copy --vf scale_cuda=w=960:h=540,format=nv12 udp://235.1.1.131:387 --msg-level=all=debug -log-file=scale_cuda_test.log --load-scripts=no`
> 
> logfile: [scale_cuda_test.log](https://github.com/mpv-player/mpv/files/4010602/scale_cuda_test.log)

As I wrote, you need to use `--hwdec=nvdec` without the `copy`. The format filter triggers a download back to system memory so the rest of your pipeline works.

**Comment by phkarmur** [comment]
but im not able to work `nvdec`! and i even dont know exact reason why its not working.
do you have any idea, why its not working and how to make it work?!

really appreciate your help 🙏

**Comment by philipl** [comment]
That's fair - you need the `vo_gpu` output for `nvdec` to work and you are using the dummy xserver, so it won't. In that case, you will have to do cpu scaling.

So: `mpv --hwdec-nvdec-copy --vf scale=960x540` etc.

**Comment by wm4** [comment]
In theory something could be done to provide the hwdec device without the VO doing that, but it's messy.

**Comment by phkarmur** [comment]
thank you @philipl  @wm4 for you help
@wm4 can you please explain more about getting support of hwdec without VO? your suggestion will help me to get better start to implement and learning.

**Comment by wm4** [comment]
Well, someone would have to implement it. It'd load all available hwdec device contexts in the VO. Then the normal code can be reused to provide it to filters and the decoder. Probably.

**Comment by phkarmur** [comment]
thank you @wm4
