### ISSUE TITLE
waf configure fails

### ISSUE THREAD

**Issue by dawidmyk** [mpv-player/mpv#7297]
I downloaded mpv source by "apt source mpv" in ubuntu. I realised that it should be compiled with waf builder. But when I typed "./waf configure" in console, it couldnt see some stuff it depends on. Even when I installed them, it couldnt see them.
![luajit](https://user-images.githubusercontent.com/25805064/71544051-bead5180-297a-11ea-9ce2-159d221e60a4.png)

**Comment by CounterPillow** [comment]
>mpv 0.14

We do not support out of date versions. The current most recent release is 0.31. Please contact Ubuntu for problems relating to any of the software they ship.
