### ISSUE TITLE
export subtitle from e.g. dvd

### ISSUE THREAD

**Issue by saufnix** [mpv-player/mpv#7302]
### mpv version and platform
mpv 0.30.0 on void-linux Kernel 5.2.21_1 / x86.

### Reproduction steps / try1
mpv --no-audio --no-video --slang de --stream-record output.sub dvd://

### Actual behavior / try1
Error-Message with
No video or audio streams selected.

### Log file / try1
https://0x0.st/zDno.txt

### Reproduction steps / try2
mpv --ao=null --vo=null --slang de --stream-record output.sub dvd://

### Actual behavior / try2
Zero length file output.sub

### Log file / try2
https://0x0.st/zDnX.txt

### Expected behavior / all tries
Extracted subtitle in output.sub

### Note
Is there any other way to extract subtitle with mpv? I searched the Internet but didn't find any useful information.
I tried also --stream-dump, but only got whole video+audio dump despite using --no-video or --vo=null

**Comment by CounterPillow** [comment]
`--no-audio`/`--no-video` only affect playback output, not `--stream-record`. What you'd want is encode mode (`-o`), but mpv is ill-suited to the task of extracting subtitles from a quick glance at the manpage.

What you actually want is something like ffmpeg:
`ffmpeg -i inputfile -map 0:s:0 out.sub`

**Comment by wm4** [comment]
mpv is not a DVD ripping tool. Neither is ffmpeg, strangely. Maybe try mplayer or mencoder (which pretends to support this), but maybe there are better tools around.

>--no-audio/--no-video only affect playback output, not --stream-record. 

Actually, stream record is probably something else than you think. It remuxes, and only streams that are enabled, so --no-audio will for example disable the audio track and not remux it into the target file.

What he could do is leaving audio and video enabled, and then using ffmpeg or mkvmerge to extract the subtitle track only. (Assuming it gets correctly muxed, which is doubtable.)

>What you'd want is encode mode (-o), but mpv is ill-suited to the task of extracting subtitles from a quick glance at the manpage.

No, encode mode always renders subtitles into video. It does not output files with subtitle tracks.

All in all, mpv is the wrong tool.
