### ISSUE TITLE
Screenshot each frame is slow

### ISSUE THREAD

**Issue by r4dius** [mpv-player/mpv#7305]
### mpv version and platform

mpv 0.31.0-11-g49cbc5017c / Windows 10

### Reproduction steps

Run mpv and press alt+s for each frame screenshot :

mpv --no-audio --framedrop=no --screenshot-directory=C:\test\ --screenshot-format=webp --screenshot-webp-lossless=yes

or rescale to 1080p

mpv --no-audio --framedrop=no --screenshot-directory=C:\test\ --screenshot-format=webp --screenshot-webp-lossless=yes --scale=spline36 --vf crop=3840:1606,scale=1920:802

### Expected behavior

Faster screenshot save ?

### Actual behavior

Depending on the picture size / complexity, for a 1080p movie it takes little less than ~1sec per screenshot (at ~700KB per file) with that setting, on 4k size it takes ~4sec (~5MB file), if choosing a lossy format it's way faster,
I'm reading and writing on an nvme ssd so write speed should not be the problem, the cpu is mostly unused, tested on slower disk too does not change the speed.

### Log file

Including a file for 4k screenshot and one for 1080p
[output4k.txt](https://github.com/mpv-player/mpv/files/4008760/output4k.txt)
[output1080p.txt](https://github.com/mpv-player/mpv/files/4008761/output1080p.txt)

**Comment by wm4** [comment]
Well, we can't magically make it faster. Use a different screenshot format and/or different screenshot encode settings.
