### ISSUE TITLE
Several keybindings do not work on macOS with --vo gpu

### ISSUE THREAD

**Issue by toonn** [mpv-player/mpv#7316]
### mpv version and platform

Built using nix:
```
mpv 0.31.0 Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.1
```

On macOS High Sierra:
```
System Version: macOS 10.13.6 (17G8030)
Kernel Version: Darwin 17.7.0
```

### Reproduction steps

When playing any video several keybindings do not work, `f` for fullscreen for example.
`Cmd-0` for half-size works but `Cmd-1` and `Cmd-2` for normal and double size don't.

### Actual behavior

No noticeable change whatsoever.

### Log file

[mpv-cocoa.log](https://github.com/mpv-player/mpv/files/4019168/mpv-cocoa.log)

In #mpv I was told this doesn't occur with `--vo libmpv` but that doesn't work for me: 
[mpv-libmpv.log](https://github.com/mpv-player/mpv/files/4019176/mpv-libmpv.log)

### Sample files

This happens regardless of the video, I noticed this while watching an [LTT youtube video](https://www.youtube.com/watch?v=TAaTbf13ipg).

**Comment by avih** [comment]
libmpv not working for you is a separate issue. Next time please file it as such, though thanks for the log anyway.

**Comment by wm4** [comment]
That backend is unmaintained. Just don't set --vo.

**Comment by toonn** [comment]
@wm4 I'm not explicitly setting it and `--vo libmpv` doesn't work for me, as I stated.

**Comment by wm4** [comment]
Oh, and it doesn't work for you because it's built without Swift.

**Comment by Cpuroast** [comment]
Try the macOS build available here:

https://mpv.io/installation

Listed under "OS X builds by stolendata"

**Comment by toonn** [comment]
@Cpuroast, I'd rather fix the nix build. I'm having a hard time finding out how to build mpv with swift though. And also confusing information about swift not being necessary for libmpv, according to @Akemi.

**Comment by Cpuroast** [comment]
That's fine, but it doesn't hurt to try a pre-built known good version with your config, to confirm that something is wrong with yours.

**Comment by wm4** [comment]
vo_libmpv is its own thing, the swift backend merely happens to use it. So vo_libmpv does not require swift, but using mpv cli with the swift backend (that uses vo_libmpv) obviously requires swift.

**Comment by toonn** [comment]
@wm4, so there's no way to use libmpv from mpv cli without swift?

How do I enable swift in the mpv build? Can't find documentation on the available flags.

**Comment by toonn** [comment]
@Cpuroast, with the 0.31.0 binary from stolendata `f` works. `Cmd-1` and `Cmd-2` still don't. I'm not sure how to check whether it uses libmpv.

**Comment by Cpuroast** [comment]
I just tested cmd-0, cmd-1 and cmd-2 with the stolendata 0.31 binary, they all work.

**Comment by toonn** [comment]
Even when running the binary in the app from the command line with `--no-config` `Cmd-1` and `Cmd-2` don't work for me. Maybe you're on a more recent version of macOS? I can't upgrade because apple considers my machine too old.

**Comment by Cpuroast** [comment]
I'm also on macOS 10.13.6, I'm simply running from the app bundle, not the command line.
