### ISSUE TITLE
vo-delayed-frame-count rises steadily under wayland

### ISSUE THREAD

**Issue by e00E** [mpv-player/mpv#7323]
### mpv version and platform
mpv 0.31.0, arch linux, wayland, sway

### Reproduction steps
Play any video with `video-sync=display-resample` and `gpu-context=wayland` or `gpu-context=waylandvk`. Does not happen with `gpu-context=x11` (going through xwayland). The video I am playing has 30 fps. I have the same problem with all videos I have tried (24 and 60 fps).

### Expected behavior
`vo-delayed-frame-count` as seen in the status line stays 0 because my hardware is fast.

### Actual behavior
`vo-delayed-frame-count` rises steadily at a rate of 15 per second. If I set my monitor to 60 Hz down from 144 then the rate is 6 per second. There are no dropped frames.

I do not notice any visual issues, just the count increasing.

### Log file
[wayland.txt](https://github.com/mpv-player/mpv/files/4022569/wayland.txt)
[waylandvk.txt](https://github.com/mpv-player/mpv/files/4022573/waylandvk.txt)
[x11.txt](https://github.com/mpv-player/mpv/files/4022572/x11.txt)

**Comment by e00E** [comment]
I have commented on this observation previously https://github.com/mpv-player/mpv/issues/7253#issuecomment-565712059 . In the linked issue I was using a low end machine but here I am using a high end one.

**Comment by wm4** [comment]
Sway version?

**Comment by e00E** [comment]
sway version 1.2

**Comment by e00E** [comment]
I have tried this again with mpv, sway, wlroots from master. The issue is gone. Feel free to close the issue.

**Comment by Dudemanguy** [comment]
Ah sway/wlroots has a fix to presentation time not present in 1.2. That's probably the cause of this.
