### ISSUE TITLE
Version 31 Breaks Scaling when video is larger than display resolution

### ISSUE THREAD

**Issue by kungfubeaner** [mpv-player/mpv#7327]
### mpv version and platform

Arch Linux and Windows 10
Version 31

### Reproduction steps

Open a 1080p video on a monitor with a resolution of 1600x900
or just smaller than 1080p and try to scale it with alt+shift+k using
this lua script:

function shrink_window()
	scale = mp.get_property_number("window-scale")
	H = mp.get_property_number("dheight")
	nscale = ((scale * H) - 10) / H
	mp.set_property_number("window-scale", nscale)
end

mp.register_script_message("Shrink_Window", shrink_window)

and add this to input.conf

Alt+Shift+k repeatable script-message Shrink_Window

### Expected behavior

behavior should be the same as it was with version 30 and scaling
should still work even if the video is larger than the monitor resolution

### Actual behavior

shrinking the video window via the script doesn't work as it did with version 30

**Comment by CounterPillow** [comment]
from interface-changes.rst:
```
   - the "window-scale" property now strictly returns the value of the option,
     instead of the actual size of the window. The new "current-window-scale"
     property needs to be queried to read the value as indicated by the current
     window size. This is a breaking change.
```

The problem is in your script, downscaling still works just fine.
