### ISSUE TITLE
Crash on certain video

### ISSUE THREAD

**Issue by medhefgo** [mpv-player/mpv#7329]
The following file crashes mpv when starting playback on latest stable and master (with --no-config). ffplay can start playback perfectly fine.

`mpv --no-config https://0x0.st/znU2.avi`

**Comment by CounterPillow** [comment]
Doesn't crash for me.

**Comment by wm4** [comment]
Works here, can't reproduce.

**Comment by medhefgo** [comment]
Updating to arch testing repo fixed it. Sorry for the noise.
