### ISSUE TITLE
play in a circle

### ISSUE THREAD

**Issue by nadsugifka** [mpv-player/mpv#7330]
how do I enable a file to play in a circle (loop file)  ???

### mpv version and platform

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it. If the issue is a build failure, upload build/config.log instead.

If this is a normal runtime bug, and no log is provided, the issue will be
closed for ignoring the issue template. This is because analyzing a bug without
a log file is harder than necessary. Low quality bug reports are noise.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by CounterPillow** [comment]
hit shift+l

**Comment by nadsugifka** [comment]
thanks a lot bro
