### ISSUE TITLE
How to get A-B Repeat, loop and playlist mpv or mpv Android?

### ISSUE THREAD

**Issue by JoinnA** [mpv-player/mpv#7331]
Hi,

I use the current mpv Android version: 2019-11-03-alpha on my Android 9 device and mpv Windows version: https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20200105-git-9eb3991.7z/download

I have 2 videos that I have recorded.

The file name:

- test m part1.mp4

- testpart2.mp4

I want to use this function together at the same time.

1. Playlist (add the 2 videos to playlist)
2. Then A-B Repeat
3. And finally the loop function

How does it work exactly?

if not possible, AB Repeat is sufficient.

**Comment by Akemi** [comment]
lower case `L` shortcut or, `--ab-loop-a=<time>` and `--ab-loop-b=<time>`. otherwise you can probably do something you desire with https://github.com/mpv-player/mpv/blob/05fb6f906de25016faff2bdedd1f47f1e4077554/DOCS/edl-mpv.rst.

**Comment by JoinnA** [comment]
@Akemi 
how do I do that on mpv android?

Do you have real examples with 2 video files?

Could you help me?

L for loop I have done and it works. but how with AB-Repeat exactly?

Can you give me a real example where it really worked.

**Comment by Akemi** [comment]
for mpv android ask there https://github.com/mpv-android/mpv-android

i have no idea what you mean with `A-B Repeat + normal loop`? if you A-B Repeat in a file you won't ever get to the end of that file, and never go to the next playlist item.

obviously it doesn't work on android because you used `--ab-loop-a=` twice instead of `--ab-loop-=`. also get rid of the `<` and `>`.

**Comment by JoinnA** [comment]
@Akemi 
Is there a possibility for ab loop to repeat only twice, as with `--loop=2`?

**Comment by Akemi** [comment]
nope. see #7360.

**Comment by JoinnA** [comment]
> nope. see #7360.
can you add this to mpv?

**Comment by Akemi** [comment]
i personally, no. someone else, possibly. that's what the feature request is for.
