### ISSUE TITLE
Is closing the mpv window, in paused state, possible?

### ISSUE THREAD

**Issue by SietseAchterop** [mpv-player/mpv#7332]
### mpv version and platform
0.29.1    debian/buster

Hello list,
I use mpv via python-mpv in my application, and need the following functionality:
A video is shown via mpv, usually in the paused state.
Then I want to do something else in the app and close the mpv window.
But later I want to open/restart it again with usually another video.

I can't figure out how to do it. I can't find a "un-load file" so to speak.
Is something like this possible?
  Thanks in advance, Sietse

**Comment by CounterPillow** [comment]
>0.29.1 debian/buster

We do not support outdated versions.

Sounds like you are looking either for the `quit` or the `stop` command.

**Comment by SietseAchterop** [comment]
I was hoping that using 'quit' would leave mpv running to load a file again later.
I now do 'quit', delete the socket and start mpv again.
Problem solved, thanks.
   Sietse
