### ISSUE TITLE
Compile problems with `archive_read_support_format_rar5`

### ISSUE THREAD

**Issue by Cqoicebordel** [mpv-player/mpv#7334]
### mpv version and platform

git master, 
Linux 5.0.0-38-generic #41-Ubuntu x86_64 GNU/Linux (Kubuntu 19.04)
libarchive-dev 3.3.3-4ubuntu0.1

### Reproduction steps

compile using mpv-build, with libarchive enabled

### Expected behavior

A nice compile

### Actual behavior

Warning as error `implicit-function-declaration` on `archive_read_support_format_rar5`
https://github.com/mpv-player/mpv/blob/28650e116a1435aed73a21fc5dd006e8f6fa8159/stream/stream_libarchive.c#L273
(-Werror=implicit-function-declaration)

I tried to remove those warnings flags, but got a compile error on the same line. At that point I gave up, and added `--disable-libarchive` to `mpv_options`

I hesitated to file a bug, because I think there is a 70% probability that I don't have the right libs (I'm relatively new at compiling myself mpv). But just in case ¯\_(ツ)_/¯

### Notes

mpv_options : 
```
--enable-dvdnav
--enable-cdda
--enable-libsmbclient
--enable-dvbin
```
And cc @wm4 as you were the last to modify this area.

**Comment by CounterPillow** [comment]
Looks like the wscript version check for libarchive is wrong, it should be 3.4.0 and not 3.3.3 from what I can see: https://github.com/libarchive/libarchive/commit/087319f7060842233e0a705654d855e77ec71ff7#diff-1a4da7d5b21972d97fbfcfb76dc720f7

**Comment by wm4** [comment]
I've changed it to 3.4.0. Could probably have had added ifdeffery to support old versions (without rar5), but why bother.
