### ISSUE TITLE
VRAM leak when changing tone-mapping-param at runtime if an ewa scaler is used and dither-depth is set

### ISSUE THREAD

**Issue by MoSal** [mpv-player/mpv#7335]
### mpv version and platform

```
% mpv --version                                                                                                              :(
mpv 0.30.0-279-gb36e8569a1-dirty Copyright © 2000-2019 mpv/MPlayer/mplayer2 projects
 built on Sat Dec  7 17:33:58 EET 2019
ffmpeg library versions:
   libavutil       56.36.101
   libavcodec      58.64.101
   libavformat     58.35.101
   libswscale      5.6.100
   libavfilter     7.68.100
   libswresample   3.6.100
ffmpeg version: N-95988-g70e292becf
```

```
% uname -orm                                                                                                                 :(
5.4.6-arch3-1 x86_64 GNU/Linux
```

```
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 570 Series (POLARIS10, DRM 3.35.0, 5.4.6-arch3-1, LLVM 9.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.3.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```

```

```

### Reproduction steps

```
mpv --no-config \
  -dither-depth auto \
  -scale ewa_lanczos \
  -tone-mapping-param 0.38 \
  --input-conf <(echo -e "g add tone-mapping-param -.01\nh add tone-mapping-param +.01") \
  $video_file
```

And pressing `gggggghhhhhhggggggggghhhhhhh`.

### Expected behavior

No large continual increase in VRAM usage. If  `-dither-depth auto` is not set, or a non-ewa scaler is used, the VRAM usage stays sane. Note that `dither-depth=auto` can be indirectly set by the `gpu-hq` profile.

### Actual behavior

Large continual increase in VRAM usage, leading to possible unexpected performance degradation.

**Comment by wm4** [comment]
I think this is a Mesa or driver bug. Somehow it depends on whether you pass a data pointer to glTexImage2D (its last argument).

So with your test case, if you change ``params->initial_data`` to ``NULL`` here: https://github.com/mpv-player/mpv/blob/bcc921bd2fc6bcd1cf45279a8497b230f8ebc700/video/out/opengl/ra_gl.c#L345 ...the leak goes away. In this case, it affects only the dither texture, so this won't be much visible. Your case doesn't actually change anything with the renderer configuration. But the dither texture is recreated anyway, which seems to leak a lot in VRAM. There don't seem to be any leaks on the mpv level. We definitely destroy the dither texture, for example.

It's notable that completely deinitializing the VO with ``_`` doesn't free this VRAM memory. This even closes the X connection, so I'd expect Mesa and the driver to free anything it still holds on.

We could work this around, but I think it's better if you report this to Mesa instead.

It's funny how we use almost the same software and hardware:
```
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.35.0, 5.4.5, LLVM 9.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.3.1
```

**Comment by MoSal** [comment]
I [reported the issue](https://gitlab.freedesktop.org/mesa/mesa/issues/2330) to the Mesa devs and they fixed it.

Thank you @wm4 for pointing me in the right direction.
