### ISSUE TITLE
HEVC 10bit encode

### ISSUE THREAD

**Issue by XPRAMT** [mpv-player/mpv#7338]
How to encode HEVC 10bit video with NVENC?
I don't see some command about bitdepth

**Comment by Akemi** [comment]
probably something along the lines of `ovcopts-add = pix_fmt yuv420p10le`

**Comment by XPRAMT** [comment]
But I try this code "ovcopts-add = pix_fmt yuv420p10le" 
Output Video still 8bit

**Comment by mc4man** [comment]
Use a video filter instead (an earlier way was pixel_format= which produces garbage now with x264 and likely x265
Put it before input..,
mpv  --vf=format=yuv420p10le input options output
