### ISSUE TITLE
MPV_EVENT_PROPERTY_CHANGE event does not occur with playlist-move

### ISSUE THREAD

**Issue by orion1vi** [mpv-player/mpv#7339]
### mpv version and platform

Since 2c5cb2c53f38580696af4085bb257f0112e92a42, macOS 10.14.6

### Reproduction steps

I use mpv_set_wakeup_callback to observe events, then use playlist-move command to modify playlist.

### Expected behavior

MPV_EVENT_PROPERTY_CHANGE event occurs when playlist is modified with playlist-move command.

### Actual behavior

MPV_EVENT_PROPERTY_CHANGE event does not occur when playlist is modified with playlist-move command.

**Comment by wm4** [comment]
Not sure if this fixes it (I have no test case), please test.

**Comment by orion1vi** [comment]
It works, thanks.
