### ISSUE TITLE
[vo/gpu/vaapi-egl] vaQueryConfigEntrypoints() failed (the requested VAProfile is not supported)

### ISSUE THREAD

**Issue by Paviluf** [mpv-player/mpv#7340]
I have this error message `[vo/gpu/vaapi-egl] vaQueryConfigEntrypoints() failed (the requested VAProfile is not supported)` and I was wondering what does it mean and if it's important or not ?

If you need more infos, please tell me what you need. Thanks

**Comment by CounterPillow** [comment]
Your hardware does not support the used codec's profile, you can list the supported profiles of your hardware with `vainfo`.

For example, if your hardware does not support VAProfileHEVCMain10, then you cannot hardware decode 10-bit main profile HEVC.

**Comment by Paviluf** [comment]
Well, I didn't have this message before. I tried all video format on youtube (I don't have local video) and I still have that message. I wonder if there is something broken ? What do you think.

My CPU is an Intel(R) Core(TM) i5-4300U with iGPU
```
mpv 'https://www.youtube.com/watch?v=dO1pLi2Dedw'
 (+) Video --vid=1 (*) (h264 1280x720 25.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
[vo/gpu/vaapi-egl] vaQueryConfigEntrypoints() failed (the requested VAProfile is not supported)
Cannot load libcuda.so.1
Using hardware decoding (vaapi).
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 1280x720 vaapi[nv12]
AV: 00:00:01 / 00:39:58 (0%) A-V:  0.001 Cache: 177s/22MB
```

**Comment by CounterPillow** [comment]
You did not provide any of the information required to help you, so we cannot help you.

**Comment by Akemi** [comment]
maybe try using the proper issue template. it asks for a lot of things we need to debug issues. i have no idea why you opened an issue with the question template if you clearly have a bug/issue.

**Comment by Paviluf** [comment]
I wasn't sure it was a problem. I will open a proper bug report and we will see. Thank you
