### ISSUE TITLE
Mpv doesn't save position in playlist with non-seekable items

### ISSUE THREAD

**Issue by acroobat** [mpv-player/mpv#7342]
### Important Information

- 0.31
- Gentoo

### Reproduction steps

>cat streams.m3u
https://www.twitch.tv/silvername
https://www.twitch.tv/kvyzee
https://www.twitch.tv/gorgc

>mpv --save-position-on-quit streams.m3u 

Then press ">" to play next item. Next item start playing. Then press Shift+Q to exit.
Mpv exits with message.

>Not seekable - not saving state

### Expected behavior

Next time i run this playlist it have to start from second saved position(https://www.twitch.tv/kvyzee).

### Actual behavior

It starts from begining(https://www.twitch.tv/silvername).

**Comment by wm4** [comment]
Probably fixed in master.
