### ISSUE TITLE
Subtitles showing only inside the video.

### ISSUE THREAD

**Issue by 13b-t** [mpv-player/mpv#7343]
Is there anyway to force the subtitles to render on top of the black bars on the sides which compensate for the ratio differences? I have tried various options from the manual, including different vos, even options which only seem tangentially related to the issue with no luck. The following screenshot illustrates better what I'm talking about.
The top instance is mplayer and how I wish to make the subtitles appear, bottom is mpv. Both are using stock configuration.
![comp](https://user-images.githubusercontent.com/59744580/72178162-03a99d00-33eb-11ea-8319-0c950176a34b.jpg)

**Comment by Akemi** [comment]
if not `--stretch-image-subs-to-screen=yes` then no.
