### ISSUE TITLE
Property expansion only works for JSON IPC when sending input.conf style show-text command

### ISSUE THREAD

**Issue by mrxdst** [mpv-player/mpv#7344]
### Important Information

- mpv version: 0.31.0
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: Arch Linux repository
- If known which version of mpv introduced the problem: No
- Window Manager and version: n/a
- GPU driver and version: n/a
- Possible screenshot or video of visual glitches: n/a

### Reproduction steps

```
mpv --no-config --idle --force-window --input-ipc-server=/tmp/mpvsocket

# Displays (unavailable) as expected
echo 'show-text ${playback-time}' | socat - /tmp/mpvsocket

# Displays ${playback-time}
echo '{"command": ["show-text", "${playback-time}"]}' | socat - /tmp/mpvsocket
```
Start a mpv instance with no config and input-ipc-server.  
Send command in "input.conf style text-only" style and JSON formatted.

### Expected behavior

That the same text is displayed for both commands as they should be identical.

### Actual behavior

The property `${playback-time}` isn't expanded then sending JSON formatted command.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/4047632/log.txt)

### Sample files

Not needed to reproduce

**Comment by wm4** [comment]
Works as designed and as advertised. You can use the corresponding command prefix to force expansion, or query the property yourself.
