### ISSUE TITLE
VAAPI doesn't work for certain H.264 interlaced file

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#7348]
### Important Information

Provide following Information:
- mpv-git-0.31.0_60_ga3ddddff3a-1
- Arch recent custom
- self-compiled mpv build
- If known which version of mpv introduced the problem: nope
- mesa-git 59d30fd4bc60f3562ca4c8247340389e97e494ae
- tested on Polaris and Gemini Lake with same result.

### Reproduction steps
Play the file with `--hwdec=vaapi`.

### Expected behavior
Ideally, VAAPI should work, as it does in VLC with this file. VDPAU works too with AMD. VAAPI works well for other files in mpv.

### Actual behavior
mpv uses software decoding without further verbosity in terminal.
It works after reencoding the file (still interlaced), so the original file probably is flawed in some way (apart from being interlaced).

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/4049586/output.txt)

### Sample files
https://0x0.st/zRGB.mkv
From Kodi samples:
https://kodi.wiki/view/Samples

**Comment by wm4** [comment]
I suspect it's because the file's profile is "Baseline", which is not supported by most hw decoders. Maybe it still happens to work if you pretend it's constrained baseline (would probably need temporary code changes or something to edit the h264 bitstream to do that).

**Comment by philipl** [comment]
Yeah.

```
[   0.117][d][ffmpeg/video] h264: Codec h264 profile 66 not supported for hardware decode.
[   0.117][v][vd] Hardware decoding of this stream is unsupported?
```

**Comment by aufkrawall** [comment]
Thanks. I wonder if it exists like that on the BD or if the uploader for the Kodi wiki did it wrong.

**Comment by wm4** [comment]
Actually such an option exists: `--vd-lavc-check-hw-profile=no`
Sample appears to work, didn't check fully.

**Comment by aufkrawall** [comment]
Can confirm that, the file plays fine that way via VAAPI.
