### ISSUE TITLE
Subtitle font size shortcut key

### ISSUE THREAD

**Issue by johnpatrick9** [mpv-player/mpv#7356]
Hello,Is it possible to add a shortcut key to change font size?
### Expected behavior of the wanted feature 
we should be able to change the font size of subtitle using a shortcut key

### Alternative behavior of the wanted feature
and is it possible to change the font style temporarily,while watching the video?
I apologize for any inconvenience as I am a noob to this

**Comment by CounterPillow** [comment]
put something like this in your input.conf:
```
u add sub-font-size 1
U add sub-font-size -1
```

**Comment by johnpatrick9** [comment]
thanks and is it possible to change the font style temporarily,while watching a video? @CounterPillow

**Comment by garoto** [comment]
If by style you mean font-face, then:
`Ctrl+s cycle-values sub-font "fontA" "fontB" "fontC" [...]`

**Comment by johnpatrick9** [comment]
oh and the "u" key shortcut seems to be for ass subtitle style override that is forcing into default size/font,could you please help me out?I would just like to increase my subs fonts,as they are to small to read @garoto @CounterPillow

**Comment by CounterPillow** [comment]
You can change the keybind to whatever you want. The point is to put this into your input.conf.

Read the manual.

**Comment by johnpatrick9** [comment]
I have set the keybind to b and n but the font's in the subtitles doesn't seem to be increasing/decreasing,what should I do? @CounterPillow

**Comment by CounterPillow** [comment]
post a log file generated with `--log-file=mpv.log` wherein you try to press b and n.

**Comment by johnpatrick9** [comment]
is this okay? @CounterPillow 
[mpv log.txt](https://github.com/mpv-player/mpv/files/4059468/mpv.log.txt)

**Comment by CounterPillow** [comment]
You didn't create an `input.conf`. You likely created an `input.conf.txt` because Windows explorer hides known file extensions by default.

**Comment by johnpatrick9** [comment]
Oh sorry, I have created it now and it's still isn't increasing/decreasing and here is the log
[mpv log.txt](https://github.com/mpv-player/mpv/files/4064257/mpv.log.txt)

**Comment by shabahengam** [comment]
@johnpatrick9  you should press `u` to override default style then you can change font size.

**Comment by garoto** [comment]
Alternatively, `sub-scale` will work with both `srt` and `ass` type subs afaik.
```
KP7			add sub-scale -0.05
KP8			set sub-scale 1.0
KP9			add sub-scale +0.05
```

**Comment by johnpatrick9** [comment]
> 
> 
> Alternatively, `sub-scale` will work with both `srt` and `ass` type subs afaik.
> 
> ```
> KP7			add sub-scale -0.05
> KP8			set sub-scale 1.0
> KP9			add sub-scale +0.05
> ```
ok,where should I do add these?and which shortcut key should I press to use them? @garoto

**Comment by johnpatrick9** [comment]
Can anyone help me out on how to add the above commands to mpv? @CounterPillow  @garoto

**Comment by garoto** [comment]
> Can anyone help me out on how to add the above commands to mpv?

input.conf and the keys `KP{0-9}` are the numpad numbered ones.

**Comment by johnpatrick9** [comment]
oh ok thank you so much for the help @garoto and by any chance do you know how to change fonts?

**Comment by CounterPillow** [comment]
read the manual

**Comment by johnpatrick9** [comment]
there is nothing about changing the font style of the subtitles in the manual other than overriding the subs using u keybind and that is why I am asking if anyone could help me out? @CounterPillow

**Comment by CounterPillow** [comment]
![image](https://user-images.githubusercontent.com/308818/72682183-b902e180-3aca-11ea-924e-1158405388cc.png)

no, you are asking because you're a support vampire draining our collective time. This was ctrl+f sub-font second match.

**Comment by johnpatrick9** [comment]
woah there in no need to be rude and as I have said earlier I am a noob to this and I have no idea what was that supposed to mean in the manual that is why I have asked for anyone if they could help me out,
if you find me annoying then tell me I will create a new issue/help thread and remember there is no one in this who knows everything by birth and I am willing to learn but what should I do if there is no one is going to help me out in these matters.
And finally I just created this thread/issue post for requesting a feature i.e., subtitle size inc/dec shortcut keys which you and others have helped me for that I am thankful and I just wanted know how to change font style in mpv temporarily that is all if you find that annoying then please tell me what should I do?

P.S **I do know you and others help the new users out of your free time and wish,I was never rude to you in any of my posts,so I do apologize for long post.**
@CounterPillow

**Comment by fxmarty** [comment]
Thanks @CounterPillow  for the suggestion, it is working. Does anybody has an idea as to how to change the size of only one subtitle when two are used (using the secondary-sid option)?

**Comment by wm4** [comment]
That's not possible, other than editing the source code.
