### ISSUE TITLE
Playing multiple audio channels concurrently

### ISSUE THREAD

**Issue by Keltyx** [mpv-player/mpv#7358]
I have a video file with the 1 audio channel playing the soundtrack of the video and another channel playing associated commentary. If I play the file in mpv I can switch between these using the # keyboard shortcut. Is there anyway I can output both audio channels at once?

I have been using the command below which according to the documentation and other examples I have seen should work. When I run this command nothing happens, mpv does not load but I also get no errors on the output (the video file is in the same folder as mpv in this example):
mpv.exe --lavfi-complex='[aid1] [aid2] amix [ao]' test5.mkv

When played from the commandline I can see the following information output:
Playing: f:\Swap\test5.mkv
 (+) Video --vid=1 (*) (h264 1024x576 24.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 48000Hz)
     Audio --aid=2 --alang=eng 'Commentary' (aac 1ch 44100Hz)
 (+) Subs  --sid=1 --slang=eng (*) (subrip)
     Subs  --sid=2 --slang=hun (subrip)
     Subs  --sid=3 --slang=ger (subrip)
     Subs  --sid=4 --slang=fre (subrip)
     Subs  --sid=5 --slang=spa (subrip)
     Subs  --sid=6 --slang=ita (subrip)
     Subs  --sid=7 --slang=jpn (subrip)
     Subs  --sid=8 (subrip)
File tags:
 Comment: Matroska Validation File 8, secondary audio commentary track, misc subtitle tracks
 Title: Big Buck Bunny - test 8
AO: [wasapi] 48000Hz stereo 2ch float
VO: [gpu] 1024x576 yuv420p

**Comment by Dudemanguy** [comment]
Works fine here. Run it with the `--lavfi-complex` command again but generate a log file too `--log-file` and post it.

**Comment by Keltyx** [comment]
Log file as below:
[mpv.log](https://github.com/mpv-player/mpv/files/4053980/mpv.log)

**Comment by Dudemanguy** [comment]
>[   0.008][v][cplayer] Command line options: '--lavfi-complex='[aid1]' '[aid2]' 'amix' '[ao]'' '.\test5.mkv' '--log-file=C:\temp\mpv.log'

That's not the same syntax as what was in the OP. I don't know window-isms too well, but the lavfi-complex argument should only need one set of quotes (`--lavfi-complex='[aid1] [aid2] amix [ao]'`).

**Comment by Keltyx** [comment]
I believe that the logging has added those quotes to the log file, I have linked a screenshot of the command line below which shows the exact command context and output:
https://prnt.sc/qn2lyf

**Comment by Dudemanguy** [comment]
Hmm, must be a windows thing. My log doesn't do that. What happens if you use double quotes instead of single quotes?

**Comment by Keltyx** [comment]
Ah, nice one, double quotes has resolved the issue, I will close this ticket.

Many thanks for your help Dudemanguy!
