### ISSUE TITLE
Support for ab-loop additional commands

### ISSUE THREAD

**Issue by fr5gh** [mpv-player/mpv#7360]
Hello,

please supports `--ab-loop=<N|inf|no>`

**Comment by sions124** [comment]
@thebombzen

Hello,

I regularly use the A-B repeat loop function but I usually only look for two or three repetitions and not infinitely.

It would be very good if exactly as with --loop could be added.

**Comment by wm4** [comment]
This would be very simple to implement, but I don't know what the user interface is supposed to look like. Normally, setting the A/B points should make the player loop immediately. What if the loop count is 0 at this point? Then it would do nothing, which would be strange.

**Comment by sions124** [comment]
> This would be very simple to implement, but I don't know what the user interface is supposed to look like. Normally, setting the A/B points should make the player loop immediately. What if the loop count is 0 at this point? Then it would do nothing, which would be strange.

I can tell you that if I set the counter to 0 in loop there is no repeat when the playback is over.

That means that if A/B points and ab-loop counter (is 0) are set, it means there will be no repetition. Same if "no" would be set.

I'd also love it if you could add ab-loop playlist. Same as loop.

**Comment by sions124** [comment]
Hello,

I have tested it and it does not work. I set the A/B points first and set the counter to 2.

It happens exactly that: 
1. A/B points is executed first (as always).
2. now comes the counter function. The A point time is taken and the playback runs to the end and is stopped. There is no B point time taken to repeat the A/B points twice.
3. It is not the same behaviour as with --loop=N.

Note: Step 2 same problem when the counter is set to inf. The exact same result.

Here, something different:
I also miss this command ab-loop-playlist, the same behaviour as with loop-playlist= N or inf

You can reopen the report here.

**Comment by Akemi** [comment]
please open a proper issue with all asked information. this here is a feature request and the feature was implemented. from my short testing it works as expected, so it seems there is some other problem.

**Comment by sions124** [comment]
@wm4

I'm sorry. I haven't exactly tested it, but it works. I re-edited the answer. I want playback to exit at the B point time. Can you fix this?
———

There is a command missing, like for loop, so reopen the report.
Because there is a Feature Request report for ab loop, I also wrote here because of ab loop playlist. Thank you.

**Comment by Akemi** [comment]
i like being ignore. just additionally set `--start=` and `--end=`.

**Comment by sions124** [comment]
Thank you for this. now ab loop playlist is still missing as with loop.

Do I have to create a new report or should this report be opened again?

**Comment by Akemi** [comment]
just use loop playlist. it should do exactly what you want in that case.
