### ISSUE TITLE
scripts: mp.command(...) with single quotes doesn't behave correctly

### ISSUE THREAD

**Issue by oltodosel** [mpv-player/mpv#7362]
When starting mpv with `mpv --audio-device='alsa/hdmi:CARD=MID,DEV=0' --ao=alsa z.mkv` - audio goes into HDMI
But when starting mpv with pulse and calling by a hotkey `mp.command("set audio-device 'alsa/hdmi:CARD=MID'; set ao alsa; ")` it doesn't work.

Also there's a difference in terminal output:
when works -> `AO: [alsa] 48000Hz stereo 2ch s32`
when doesn't -> `AO: [alsa] 48000Hz stereo 2ch float`

I rarely have to switch to HDMI and until recently(before the last update I suppose) it worked.

**Comment by Argon-** [comment]
And when you set the property directly using `mp.set_property("audio-device", ...)`? (Like I do here https://github.com/Argon-/mpv-config/blob/master/scripts/auto-audio-device.lua#L27)

**Comment by oltodosel** [comment]
@Argon- , thanks. This made it work again.

**Comment by avih** [comment]
So what's the issue with `mp.commane(...)`? that it has multiple commands? that there's a redundant semicolon at the end of it?

**Comment by avih** [comment]
Hmm.. this works:
```javascript
mp.command("cycle fullscreen; cycle border; ")
```
Note the extra semicolon and space like at the OP command.

However, this doesn't work at all - doesn't cycle fullscreen nor border:
```javascript
mp.command("cycle 'fullscreen'; cycle 'border'; ")
```

So I'd say the original issue is of quoting.
@oltodosel could you try your original command without the quotes? this specific command doesn't need quoting I think.

**Comment by oltodosel** [comment]
Tried without quotes - works.

**Comment by avih** [comment]
@oltodosel bext time please keep the issue open even if there's a workaround, because the original issue may (and does in this case) still exist.

**Comment by avih** [comment]
Hmm.. single quotes also don't seem to work at `input.conf`. This doesn't work at all:
```
ctrl+b cycle 'border'; cycle 'fullscreen'; 
```

**Comment by avih** [comment]
Well, it's documented at the input.conf syntax section:
> String arguments need to be quoted with "

and `mp.command(...)` at scripts seemingly has the same requirements. Closing as known and documented behavior.
