### ISSUE TITLE
Subtitle support in tct

### ISSUE THREAD

**Issue by basxto** [mpv-player/mpv#7363]
### Expected behavior of the wanted feature

Show subtitles in or under the video.
Subtitles would block off two pixels per character, but that is okay.
This would allow to watch movies on devices without proper video audio and video output.

**Comment by CounterPillow** [comment]
tct is a joke VO, it is not meant for actual use. If your device does not have audio and video output, you should find a different device to use to consume audio and video on. If you really do want subtitles below your tct output, you can probably do this with a script.

**Comment by avih** [comment]
> you can probably do this with a script

I don't think that's possible with a lua/js script. But I think the tct output can read and display the "sub-text" property. Probably not too much work, but also probably not high priority for any of the devs...
