### ISSUE TITLE
Remember window size?

### ISSUE THREAD

**Issue by Bodyx** [mpv-player/mpv#7364]
Something I've always hated about many media players is that they don't remember the window size I give them out of full screen. 

I want the window to remember the size I last made it when not in full screen, is there a way to do this on MPV currently or in the future?

**Comment by shabahengam** [comment]
something like [this](https://gist.github.com/TheAMM/5e07ad787dd95d76131b61840f403a79)?

**Comment by wm4** [comment]
mpv won't remember the window size across multiple instances of the player, but sim ply entering fullscreen and then leaving fullscreen again should restore the previous window size/position. If not, it's a bug (but for which not enough information is available to find and fix it).
