### ISSUE TITLE
Play resume when FaceTime call is received

### ISSUE THREAD

**Issue by mthld** [mpv-player/mpv#7365]
### Important Information
- mpv 0.31.0
- macOS Version 10.15.2 (19C57)
- Source of the mpv binary: [Homebrew Casks](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/mpv.rb)

### Reproduction steps
1. Open a video file
2. Make it pause
3. Get a FaceTime call
4. The video automatically resume

### Expected behavior
When receiving a FaceTime call the video paused shouldn't resume automatically.

### Actual behavior
The video resume automatically

### Log file
https://paste.clic2000.net/413172

Thanks in advance!

**Comment by qmega** [comment]
Seems like the OS is telling mpv to pause when a call comes in, and mpv takes it as "toggle pause state".

Some brief research suggests that macOS might use media keys for that, and mpv is not the first program to have this problem.

I don't have a Mac so can't test myself, but try this:

In your `input.conf`, put:
```
PLAY set pause no
PAUSE set pause yes
```
Currently the default input.conf sets both to `cycle pause`, so it will pause if currently playing, but play if currently paused. The above probably makes more sense. If it fixes your problem, we should probably change the defaults. There is already a separate PLAYPAUSE button which I presume is what the relevant button on a remote would map to.

**Comment by mthld** [comment]
Hi Philip,

Many thanks for your answer, it makes totally sense.
I tried to add the settings mentioned to my `input.conf`, now when I get a call and MPV is paused it doesn't resume: it's good! However, when the call is done, the open MPV window resume. I guess it's not a "problem" from MPV but the way macOS handle the calls, the same thing happen with Apple Music...

So, I think it would still be an improvement to change the current defaults to this. 👍🏻

**Comment by Akemi** [comment]
and here i was wondering what's going on since i am pretty sure i mapped the keys to the proper [MP_KEY_* events](https://github.com/mpv-player/mpv/blob/master/osdep/macos/remote_command_center.swift#L28-L63).

i planned to have a look at it soonish. maybe something additional can be done too.

**Comment by Akemi** [comment]
i opened a PR #7380 for this issue. this will also properly update the playback state to prevent future breakages if system logic depends on it.

**Comment by mthld** [comment]
Thanks! 🙌🏻
