### ISSUE TITLE
write-watch-later-config causes playlist to restore from the first entry instead of the most recent entry

### ISSUE THREAD

**Issue by AN3223** [mpv-player/mpv#7366]
- mpv version: 0.31.0
- Linux Distribution and Version: void linux current
- Source of the mpv binary: void repos
- Window Manager and version: sway-1.2
- GPU driver and version: xf86-video-amdgpu-19.1.0

### Reproduction steps

1. Create a directory
2. Place two audio files in the directory
3. $ mpv \<directory\>
4. Call write-watch-later-config on the first file
5. Call playlist-next to skip to the second file
6. Call write-watch-later-config on the second file
7. ^C to quit out of mpv
8. $ mpv \<directory\>
### Expected behavior
Playback should resume at the beginning of the second file
### Actual behavior
Playback will resume at the first file

[Terminal session for reference](https://github.com/mpv-player/mpv/files/4072931/mpvlog.txt)

If I understand this correctly, this happens because the old write-watch-later-config entry is kept around, even after the file is finished. When the playlist is resumed mpv will play from the first write-watch-later-config entry it finds, rather than the most recent. Maybe mpv should provide a way to delete write-watch-later-config entries, or (an option to) delete write-watch-later-config entries at the end of file playback?

**Comment by wm4** [comment]
Well, why do you think write-watch-later-config is not the default behavior, and instead the default behavior is something that works?
You could compute the watch later config filename yourself and delete it manually.
