### ISSUE TITLE
Hable correct exposure

### ISSUE THREAD

**Issue by age1988** [mpv-player/mpv#7369]
Hi!
Hable tone mapping operator produces darker output when used "correctly" to tonemap to 100nits, comparable with the 2390 tm curve at 200 nits.
A dirty trick would be multiply by 2 the exposure bias.

For example for hdr10 1000nits the values in 0-10 range have to be multiplied by 2 and the W parameter has to be set to 20.

[http://www.framecompare.com/image-compare/screenshotcomparison/D66GPNNX](url)

**Comment by laichiaheng** [comment]
The default setting for HDR of MPV is definitely not watchable, because the dark scene is dark as hell.

**Comment by Doofussy2** [comment]
Try using `--tone-mapping-max-boost`

https://mpv.io/manual/master/#options-tone-mapping-max-boost

**Comment by laichiaheng** [comment]
> Try using `--tone-mapping-max-boost`
> 
> https://mpv.io/manual/master/#options-tone-mapping-max-boost

Thanks, `--tone-mapping-max-boost=10.0` looks more natural now.

**Comment by laichiaheng** [comment]
> Try using `--tone-mapping-max-boost`
> 
> https://mpv.io/manual/master/#options-tone-mapping-max-boost

It seems like this option is depend on the brightness of the monitor. On my TV (TH-L42B12W), the decay of the brightness makes the dark scenes too dark. On my PC monitor (EW277HDR), the default setting looks very nice with 100% backlight.

**Comment by laichiaheng** [comment]
![2020-02-22 12-20-54 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/75086342-e6c9c300-556d-11ea-8846-9ff9dce0fa1c.png)
She looks horrible in Knives out.

**Comment by Doofussy2** [comment]
What is the exact time for that scene?

**Comment by laichiaheng** [comment]
@Doofussy2 Start from 01:17:37

**Comment by Doofussy2** [comment]
> ![2020-02-22 12-20-54 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/75086342-e6c9c300-556d-11ea-8846-9ff9dce0fa1c.png)
> She looks horrible in Knives Out.
> Does anyone have the SDR version to compare with?

Here's a crappy photo of all three, juxtaposed. On the far left (yours), middle (actual HDR), far right (the SDR version). Be aware that there is overexposure, so it looks brighter than it actually is. But you get the idea. Your output is very good. Remember that HDR is also very dark as well a very bright.

![IMG_20200221_211510](https://user-images.githubusercontent.com/15950919/75087061-952f2300-54f0-11ea-8c2e-0af30e87d6b1.jpg)

**Comment by Doofussy2** [comment]
Here's a direct screen capture of the HDR. It's 8 bit, so it's a little lighter due to not having the 10 bit depth, but again you get the idea.

![Knives out](https://user-images.githubusercontent.com/15950919/75087446-24d6d080-54f5-11ea-9b4f-e74fd9eaff65.jpg)

And here's the SDR
![Knives out (2)](https://user-images.githubusercontent.com/15950919/75087460-7aab7880-54f5-11ea-9756-4adb1183f668.jpg)

**Comment by Doofussy2** [comment]
And I should mention that I'm using Windows 10, so these screenshots are from the d3d presenter level (desktop), not the mpv screenshot. HDR isn't captured by mpv.

**Comment by Doofussy2** [comment]
SDR screenshot directly from mpv
![mpv-shot0001](https://user-images.githubusercontent.com/15950919/75087766-3d48ea00-54f9-11ea-9cb6-e47acf874635.jpg)

**Comment by laichiaheng** [comment]
@Doofussy2 I have enabled the icc-profile, so her skin color looks washed out, and becomes more like black and white, I think that is why it makes me feel unnatural.

**Comment by Doofussy2** [comment]
> @Doofussy2 I have enabled the icc-profile, so her skin color looks washed out, and becomes more like black and white, I think that is why it makes me feel unnatural.

I think you have a disparity between your screenshot and what you're seeing on your display. Your screenshot on my display is pretty good.

**Comment by KloudKoder** [comment]
Related?

[](https://github.com/mpv-player/mpv/issues/7742#issuecomment-703169275)
