### ISSUE TITLE
Error when use streamlink with mpv

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#7370]
### Important Information

Provide following Information:
- mpv version
0.31.0 x64 and git version
- Windows Version
Windows7 SP1 x64 
- Source of the mpv binary
https://sourceforge.net/projects/mpv-player-windows/files/

### Reproduction steps

I use streamlink with mpv to play some live stream and work great with stable 0.31, but i found i get error when use git version after 63bf362, i tried last 3 git build
●normal：stable and 9eb3991
●error：63bf362
●error：ee7be62

Status is normal with stable and 9eb3991(and before)：
https://i.imgur.com/wVHxm0A.png

Z:\test\mpv>streamlink.exe -p mpv.exe https://www.huya.com/520888 best
[cli][info] Found matching plugin huya for URL https://www.huya.com/520888
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: mpv.exe

Status is error with build after 63bf362
https://i.imgur.com/PrzIzkf.png

Z:\test\mpv>streamlink.exe -p mpv.exe https://www.huya.com/520888 best
[cli][info] Found matching plugin huya for URL https://www.huya.com/520888
[cli][info] Available streams: live (worst, best)
[cli][info] Opening stream: live (hls)
[cli][info] Starting player: mpv.exe
error: Failed to start player: mpv.exe (Process exited prematurely)
[cli][info] Closing currently open stream...

**Comment by garoto** [comment]
https://github.com/streamlink/streamlink/issues/2769#issuecomment-575253213

**Comment by Akemi** [comment]
since it has already been fixed upstream.

**Comment by Kein** [comment]
The issue is back on Feb build and streamlink 2.0

**Comment by CounterPillow** [comment]
@Kein works for me.
```
✓ fratti@archbook ~ $ streamlink -V
streamlink 2.0.0
✓ fratti@archbook ~ $ streamlink --player-fifo https://twitch.tv/scotchcarb
[cli][info] Found matching plugin twitch for URL https://twitch.tv/scotchcarb
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[plugins.twitch][info] Will skip ad segments
[plugins.twitch][info] Low latency streaming (HLS live edge: 2)
[cli][info] Creating pipe streamlinkpipe-117318
[cli][info] Starting player: mpv --profile=twitch
[cli][info] Player closed
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

Please do not pollute old issues with thinly veiled requests for unrelated tech support.

**Comment by Kein** [comment]
https://github.com/streamlink/streamlink/issues/3568
