### ISSUE TITLE
Unable to cycle through multiple values, several being identical

### ISSUE THREAD

**Issue by Dupond** [mpv-player/mpv#7371]
Hello !
I'm trying to cycle through subtitle styles with a single keybind.
I have set the following keybind in my input.conf file :
`Ctrl+1 no-osd cycle-values sub-font "Sans" "Sans" "Serif" "Serif" "Serif" "Sans"; no-osd cycle-values sub-color "#FFFF00" "#FFFF00" "#FFFFFF" "#FFFFFF" "#FFFF00" "#FFFF00" "#FFFFFF"; no-osd cycle-values sub-shadow-color "#000000" "#FFFFFF" "#000000" "#000000" "#FFFFFF" "#000000"; no-osd cycle-values sub-ass-override "force" "force" "force" "force" "force" "force"`
What I expect this keybind to do, is cycling through the following values :
- Sans serif font, yellow, with black border ;
- Sans serif font, yellow, with white border ;
- Serif font, white, with black border ;
- Serif font, yellow, with black border ;
- Serif font, yellow, with white border ;
- Sans serif font, white, with black border (so go back to default).

But it doesn't work : the keybind simply has no effect at all.
It seems to be because some values are identical ; if I set 6 different fonts, with 6 different colors, then it works... but I don't understand why.
Could someone help me with this ?
Thanx in advance,
Best regards !

**Comment by Akemi** [comment]
this is clearly an issue and not a question. please use the proper template for this.
