### ISSUE TITLE
flutter & dart pakage

### ISSUE THREAD

**Issue by irdeveloper89** [mpv-player/mpv#7373]
Mpv has any flutter or dart pakage ?

**Comment by wm4** [comment]
Probably not?

**Comment by FireMasterK** [comment]
There seems to be https://pub.dev/packages/libmpv or https://github.com/alexmercerind/libmpv.dart

**Comment by alexmercerind** [comment]
Hello @javad-zobeidi,

I recently started working (3 weeks ago) on [libmpv.dart](https://github.com/alexmercerind/libmpv.dart) as mentioned by @FireMasterK. A 100% Dart binding to libMPV's C API complete with event streams etc.
It is still a work in progress.

I'm creating really easy to use high-level interface.

```dart
import 'package:libmpv/libmpv.dart';

Future<void> main() async {
  await MPV.initialize();
  final player = Player()
    ..streams.playlist.listen((event) {
      print(event);
    })
    ..streams.index.listen((event) {
      print(event);
    })
    ..streams.position.listen((event) {
      print(event);
    });
  player.open(
    [
      Media(
        'https://p.scdn.co/mp3-preview/2312e9b4429d32218bf18778afb4dca0b25ac3f5?cid=a46f5c5745a14fbf826186da8da5ecc3',
      ),
      Media(
        'https://p.scdn.co/mp3-preview/feb4812ccf46114e71085c2e1a5159b1b992e9c3?cid=a46f5c5745a14fbf826186da8da5ecc3',
      ),
      Media(
        'https://p.scdn.co/mp3-preview/e2f3e698deaf0f09ed49436a7ab6abf6a989edfc?cid=a46f5c5745a14fbf826186da8da5ecc3',
      ),
      Media(
        'https://p.scdn.co/mp3-preview/3f794acc211c14f5bbaef6ff44aa57b02b69bd9d?cid=a46f5c5745a14fbf826186da8da5ecc3',
      ),
    ],
  );
}
```

I have worked on [dart_vlc](https://github.com/alexmercerind/dart_vlc), [libwinmedia](https://github.com/harmonoid/libwinmedia & [flutter_audio_desktop](https://github.com/alexmercerind/flutter_audio_desktop) in past & I have great idea of what I'm doing.

Thanks.

**Comment by Dixeran** [comment]
> Hello @javad-zobeidi,
> 
> I recently started working (3 weeks ago) on [libmpv.dart](https://github.com/alexmercerind/libmpv.dart) as mentioned by @FireMasterK. A 100% Dart binding to libMPV's C API complete with event streams etc. It is still a work in progress.
> 
> I'm creating really easy to use high-level interface.
> 
> ```dart
> import 'package:libmpv/libmpv.dart';
> 
> Future<void> main() async {
>   await MPV.initialize();
>   final player = Player()
>     ..streams.playlist.listen((event) {
>       print(event);
>     })
>     ..streams.index.listen((event) {
>       print(event);
>     })
>     ..streams.position.listen((event) {
>       print(event);
>     });
>   player.open(
>     [
>       Media(
>         'https://p.scdn.co/mp3-preview/2312e9b4429d32218bf18778afb4dca0b25ac3f5?cid=a46f5c5745a14fbf826186da8da5ecc3',
>       ),
>       Media(
>         'https://p.scdn.co/mp3-preview/feb4812ccf46114e71085c2e1a5159b1b992e9c3?cid=a46f5c5745a14fbf826186da8da5ecc3',
>       ),
>       Media(
>         'https://p.scdn.co/mp3-preview/e2f3e698deaf0f09ed49436a7ab6abf6a989edfc?cid=a46f5c5745a14fbf826186da8da5ecc3',
>       ),
>       Media(
>         'https://p.scdn.co/mp3-preview/3f794acc211c14f5bbaef6ff44aa57b02b69bd9d?cid=a46f5c5745a14fbf826186da8da5ecc3',
>       ),
>     ],
>   );
> }
> ```
> 
> I have worked on [dart_vlc](https://github.com/alexmercerind/dart_vlc), [libwinmedia](https://github.com/harmonoid/libwinmedia) & [flutter_audio_desktop](https://github.com/alexmercerind/flutter_audio_desktop) in past & I have great idea of what I'm doing.
> 
> Thanks.

Will the libmpv.dart use #7852 and some TextureRegister with flutter? I'm just guessing because the link to your repo seems missing, and dart_vlc looks like using a similar approach with a VideoFrameCallback.

**Comment by FireMasterK** [comment]
I can't find the libmpv.dart repo anymore, it's been gone for a couple of weeks now, what happened?

**Comment by FireMasterK** [comment]
> I don't have any personal reasons to implement video playback yet. But if I will, then it will be hardware accelerated this time, no pixel buffer texture.

I am interested in implementing video playback, however I know little about C and Dart, but I'm willing to learn. Do you know what's a good place to start at?

**Comment by alexmercerind** [comment]
> > I don't have any personal reasons to implement video playback yet. But if I will, then it will be hardware accelerated this time, no pixel buffer texture.
> 
> I am interested in implementing video playback, however I know little about C and Dart, but I'm willing to learn. Do you know what's a good place to start at?

Currently, being 100% there are no official docs or examples. You can look at their unit tests or my dart_vlc implementation (but it will again have to be a software renderer because Flutter just supports pixel buffer texture currently). Everything is so new at desktop side of Flutter (and I regret choosing it).
I started to work at this: https://github.com/flutter/flutter/issues/31713#issuecomment-1047250128 but I'm again very out of interest.
