### ISSUE TITLE
What latency reducing methods does mpv use 

### ISSUE THREAD

**Issue by Consti10** [mpv-player/mpv#7379]
Hello,

We are looking for methods to reduce video latency in our OS project [FPV_VR_OS](https://github.com/Consti10/FPV_VR_OS).

We tested one example stream and it has significantly lower latency when viewed in mpv-player-android.
Therefore, we are wondering - do you use any bit-stream manipulation (e.g. modifying NALUs) with low-latency hacks enabled ?

Best regards,
Constantin

**Comment by wm4** [comment]
It doesn't specifically try to reduce latency. On the opposite, there are some things that make latency worse by default in exchange for more buffering and better decoding performance.
