### ISSUE TITLE
High VSync Jitter with gpu-api=vulkan when fullscreen

### ISSUE THREAD

**Issue by Silver-Fullbuster** [mpv-player/mpv#7381]
### Important Information

- mpv version
```
Microsoft Windows [Version 10.0.18363.592]

mpv 0.31.0-79-gee7be62dbc Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Jan 19 12:49:48 +08 2020
ffmpeg library versions:
   libavutil       56.38.100
   libavcodec      58.66.100
   libavformat     58.35.104
   libswscale      5.6.100
   libavfilter     7.71.100
   libswresample   3.6.100
ffmpeg version: git-2020-01-19-f8990c5f4
```

- Source of the mpv binary
Latest Shinchiro build (`mpv-x86_64-20200119-git-ee7be62.7z`) 

Playing a video file with interpolation and `gpu-api=vulkan` causes high (~0.3) VSync Jitter when fullscreen. When windowed, jitter remains low (~0.02)

When I try to repeatedly look at the stats using keybind (i), the jitter goes back to almost 0 (~0.005), without it, the jitter goes back high. Issue not present with `gpu-api=d3d11`

Graphics:
Intel HD Graphics 620 

### Reproduction steps

1. `mpv --no-config --gpu-api=vulkan  --video-sync=display-resample <videofile>`
2. Go to fullscreen using keybind

### Expected behavior

VSync Jitter remains low/same as windowed

### Actual behavior

VSync jitter is much higher than windowed (0.3 vs 0.02)

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/4097770/output.txt)

**Comment by Silver-Fullbuster** [comment]
No longer have the system, so closing the issue may be better

**Comment by Jules-A** [comment]
Explanation of why it occurs: https://github.com/mpv-player/mpv/issues/8008#issuecomment-821880784
