### ISSUE TITLE
MPV can't detect my vapoursynth while building on Linux

### ISSUE THREAD

**Issue by Rorshachk** [mpv-player/mpv#7383]
### mpv version and platform versions
mpv: 0.310
platform: manjaro KDE 18.1.5
vapoursynth: R44-2

### Reproduction steps & Behavior
I want to compile a mpv with zimg and vapoursynth enabled.

But when I excute:
` ./waf configure --enable-zimg --enable-vapoursynth`

It complains:
```
Checking for VapourSynth filter bridge                                    : no ('vapoursynth >= 24 vapoursynth-script >= 23' not found) 
You manually enabled the feature 'vapoursynth', but the autodetection check failed.
```
After searching in google, I found this [`issue`](https://github.com/mpv-player/mpv/issues/1737). It says that might be caused by the lack of vapoursynth.pc, however, there is a vapoursynth.pc in `/usr/lib/pkgconfig`, and to make sure this directory is in PKG_CONFIG_PATH, I add it manually:
`export PKG_CONFIG_PATH=/usr/lib/pkgconfig`

But it still doesn't work.

And I also try to copy the pc file into `/usr/local/lib/pkgconfig`, where is zimg.pc located, and add the directory into PKG_CONFIG_PATH. It doesn't change anything, either.

I also try to build mpv-full automaticaly from aur source and it reports the same issue.

**Comment by CounterPillow** [comment]
Please provide the `config.log` in the `build/` subdirectory.

**Comment by Rorshachk** [comment]
@CounterPillow 
Thank you for reminding me! I check this config.log myself and found that is because it requires python3.7, but my current python version is 3.8, so I downgrade it and solve the problem.

**Comment by qyot27** [comment]
It's a really old build of VapourSynth. R44 is from July 2018.
