### ISSUE TITLE
cdda:// fails to play CD

### ISSUE THREAD

**Issue by parkerlreed** [mpv-player/mpv#7384]
### Important Information

Provide following Information:
- mpv version: 1:0.31.0-2
- Linux Distribution and Version: Arch Linux
- Source of the mpv binary: Repo package

### Reproduction steps

* Insert audio CD into drive
* Run `mpv cdda://`

### Expected behavior

Audio CD is played

### Actual behavior

```
[cdda] Switched to track 1
 (+) Audio --aid=1 (pcm_s16le 2ch 44100Hz)
AO: [pulse] 44100Hz stereo 2ch s16
A: 00:00:00 / 00:00:00 (81%) Cache: 0.0s


Exiting... (End of file)
```

### Log file

http://ix.io/286R

**Comment by mc4man** [comment]
Appears to have been broken for quite a while. Guess shows how lightly used it is.
Probably https://github.com/mpv-player/mpv/commit/f37f4de8496556afaa024e39e2efb433eb1680d4

**Comment by wm4** [comment]
Why would that commit affect it?

**Comment by CounterPillow** [comment]
I actually bought an external DVD drive just to bisect this and will get around to it once I have the time. The things I do for memes.

**Comment by wm4** [comment]
I have an external DVD drive that I never used.

**Comment by mc4man** [comment]
Here, with an external drive, that is the 1st bad commit.

**Comment by qyot27** [comment]
I can reproduce it on Windows 10 as well.  ASUS BW-16DHT, with a SATA/USB3 adapter.  mpv from December 31st.

It only affects the `cdda://` method; using `av://` to access avdevice's libcdio still works:
```
mpv --start=00:00:00.0000000 av://libcdio:i:
```

The `av://` method of talking to libcdio actually has a couple benefits that `cdda://` does not.  The only real drawbacks are the need to explicitly seek (which isn't mpv-specific; FFmpeg needs -ss to be used for any output to file to work) and the somewhat less intuitive invocation.

**Comment by biergaizi** [comment]
@qyot27  Thanks for the workaround, you just saved me from wasting time to apply the patch and rebuild it. I can confirm that `mpv --start=00:00:00.0000000 'av://libcdio:/dev/sr0'` works on affected versions on Linux.
