### ISSUE TITLE
"Step Forward" and "Step Backward" don't work in macOS "Playback" menu

### ISSUE THREAD

**Issue by mindfulsource** [mpv-player/mpv#7387]
### Important Information

- mpv version: **0.31.0 (latest release)**
- macOS Version: **macOS Catalina 10.15.2**
- Source of the mpv binary or bundle: **Unofficial third-party build by stolendata (but also with the Homebrew version, used here to produce the log)**
- If known which version of mpv introduced the problem: **N/A**
- Possible screenshot or video of visual glitches: **N/A**

### Reproduction steps

Open a file with MPV on macOS then try to perform "Step Forward" or "Step Backward" from the "Playback" menu. (Only works via keyboard arrows.)

### Expected behavior

It should go forward or back in time.

### Actual behavior

It doesn't go forward or back in time.

### Log file

[https://0x0.st/irJu.txt](https://0x0.st/irJu.txt)

### Sample files

N/A

**Comment by Akemi** [comment]
you do realise that "Step Forward" and "Step Backwards" are bound to 1 frame forward and backward respectively, it is not equivalent to what the arrows do?

it does work here and your log also says:

```
[   4.982][d][cplayer] Run command: frame-step, flags=73, args=[]
[   7.464][d][cplayer] Run command: frame-back-step, flags=73, args=[]
```

**Comment by mindfulsource** [comment]
Oh, my bad. Thanks for pointing out.

**Comment by Akemi** [comment]
do you want/were searching for a seek forwards/backwards menu items? i could add them if wanted.

**Comment by mindfulsource** [comment]
Yes, this would be great. Please add forward and back seeks to perform whatever the default config applies to right arrow and left arrow keybindings (five seconds?).

This way, scripting such an MPV action in AppleScript will be far superior by using menu item selection, as right now you have to use a very hacky way to do it in AppleScript which forces MPV window to become the foreground application for a brief second using a scripted keypress.

**Comment by Akemi** [comment]
i am not sure what you are doing but there is most likely a better way for that. via the JSON IPC you can send arbitrary command to mpv.

https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst

if that isn't an option for you i will just add those two menu items with 5 sec seek backwards and forward. for defaults see https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L46-L47

**Comment by mindfulsource** [comment]
AWESOME!

That method does it all for me.

In case this helps anyone on search engines, this is how you do can control playback of MPV with AppleScript while MPV is minimised in the background:

1. First: `brew install socat` and `brew install --HEAD mpv`

2. Start a file with homebrew's MPV like this: `mpv --input-ipc-server=/tmp/mpvsocket file.mp4`

3. Applescript example to rewind five seconds: `do shell script "echo 'seek -5' | /usr/local/bin/socat - /tmp/mpvsocket"`

MPV is more amazing than I ever thought.

BTW I think [that page](https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst) may be broken / missing a section, the [`List of Input Commands`_](https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst#id3) link doesn't bring anything up. Should it link to [this](https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L46-L47) or something similar?

So anyway, no need to add the menu item for me, but doing so may help others who didn't find the method I worked out with your helpful pointers along the way. I don't like UI clutter either (goodbye VLC), but it'd always be hidden in that macOS menu.

Thx for the help.

**Comment by Akemi** [comment]
great i could help you find a better way for it.

the `List of Input Commands_` hook doesn't work since it links to a different doc i believe. it works on the fully build manual on our site https://mpv.io/manual/master/#list-of-input-commands. which is most likely the preferred way of looking at the manual.

i personally think adding the seek commands to the menu is a bit useless right now. because they wouldn't be configurable (5 secs might be useless to many) and it doesn't show the current key binding (what is defined in input.conf). the latter might come some day and i will most likely rework the menu at that time. for now i will keep this closed because your issue could be solved in a better way and there is no need for those items anymore for now.
