### ISSUE TITLE
How to set up icc-profile-auto in a c++ Qt program using libmpv?

### ISSUE THREAD

**Issue by Protostars** [mpv-player/mpv#7389]
It seems that ```mpv::qt::set_option_variant(mpv, "icc-profile-auto","yes");``` has no effect

**Comment by wm4** [comment]
With window embedding (with the "wid" option) it should work automatically. If you use the render API (aka opengl-cb), in which case you need to read the current ICC profile manually and set it with MPV_RENDER_PARAM_ICC_PROFILE.
