### ISSUE TITLE
webp support

### ISSUE THREAD

**Issue by inca-viewer** [mpv-player/mpv#7390]
webp screenshot may work
but could mpv ever open webp image like it does for jpg
since i use mpv as an excellent image viewer

**Comment by sfan5** [comment]
mpv can already do that, FFmpeg added webp decoding a while ago.

**Comment by Cpuroast** [comment]
Latest mpv version is 0.31, your version may simply need an update.

**Comment by inca-viewer** [comment]
i'm using  mpv-x86_64-20200119-git-ee7be62
but .webp images still don't open ..

**Comment by CounterPillow** [comment]
Post a log file generated with `--log-file`. My guess is that you simply don't have a file association set for .webp and therefore think mpv won't open them when in fact it does.

**Comment by inca-viewer** [comment]
i'm sure it's something simple, but can't figure it out
the mpv app just closes instantly any way i try

![Annotation 2020-01-26 113916](https://user-images.githubusercontent.com/51750604/73134643-e4d51880-4030-11ea-994d-5d5fbdd6d075.jpg)

**Comment by CounterPillow** [comment]
You still haven't posted a log file so I cannot help you.

**Comment by inca-viewer** [comment]
i can't get mpv to respond to any commands in dos box
ffmpeg -h    no problem
mpv -h or --h or h or /h or -help ... or any command . no response 
mpv.exe --log-file=c:   etc etc   no response .

i understand your time is valuable so am ok to leave this unresolved 
since everything else in mpv works so perfectly

**Comment by CounterPillow** [comment]
>in dos box

what? do you mean cmd.exe? cmd.exe is not "dos box"

**Comment by inca-viewer** [comment]
i type in search    dos
press    command prompt 
(ffmpeg switches work ok here)
![Annotation 2020-01-26 144644](https://user-images.githubusercontent.com/51750604/73136950-338fac00-404b-11ea-9343-6155af497b58.jpg)

**Comment by wm4** [comment]
You're missing mpv.com: https://github.com/mpv-player/mpv/wiki/FAQ#On_Windows_why_does_mpvexe_not_attach_to_the_console_and_what_does_mpvcom_do

**Comment by inca-viewer** [comment]
thank you for your patience
mpv -h works now
mpv sample.jpg works now
mpv sample1.webp says exiting   Failed to recognize file format.
i'll try to get log file working....

**Comment by inca-viewer** [comment]
cannot get log file to recgnise any path
--log-file
--log-file=C:
--log-file=C:\
--log-file=C:\text.txt
--log-file=C:\Users\-\Pictures\
--log-file=C:\Users\-\Pictures\text.txt
always --- "error cannot recognize path"

**Comment by wm4** [comment]
mpv doesn't print such a message.

**Comment by inca-viewer** [comment]
sorry, wrong wording
![Annotation 2020-01-26 154647](https://user-images.githubusercontent.com/51750604/73137729-502fe200-4053-11ea-9d47-b0842772dbdb.jpg)

**Comment by Hrxn** [comment]
Append `logfile.log`, please..

**Comment by garoto** [comment]
`--log-file=` needs a filename after the equal sign. Gee.

**Comment by inca-viewer** [comment]
![Capture](https://user-images.githubusercontent.com/51750604/73139035-60e75480-4061-11ea-8dc4-5b32b14f4e25.JPG)

**Comment by inca-viewer** [comment]
ok finally got it working by removing path
C:\Users\-\Pictures>mpv sample1.webp --log-file=test.txt
[test.txt](https://github.com/mpv-player/mpv/files/4113848/test.txt)

**Comment by CounterPillow** [comment]
can you upload the sample image too?

**Comment by garoto** [comment]
[**@inca-viewer**](https://github.com/inca-viewer) commented on [Jan 26, 2020, 2:29 PM GMT-3](https://github.com/mpv-player/mpv/issues/7390#issuecomment-578524015 "2020-01-26T17:29:27Z - Replied by Github Reply Comments"):
> [![Capture](https://user-images.githubusercontent.com/51750604/73139035-60e75480-4061-11ea-8dc4-5b32b14f4e25.JPG)](https://user-images.githubusercontent.com/51750604/73139035-60e75480-4061-11ea-8dc4-5b32b14f4e25.JPG)

Unrelated, but not sure why you're getting that `--log-file` error message in the screenshot above. Windows10 `cmd.exe` idiosyncrasy perhaps? 

![screenshot-0697-26-01-2020](https://user-images.githubusercontent.com/11768175/73140838-17483b00-405c-11ea-9ebf-8db88c33047c.png)

**Comment by inca-viewer** [comment]
this web page wont allow .webp upload
so i changed ext to .txt , you need to change it back to .webp
[sample1.txt](https://github.com/mpv-player/mpv/files/4116224/sample1.txt)

**Comment by bitraid** [comment]
This is actually a jpeg, and strangely enough the demuxer fails if a jpeg has a `webp` extension. I also noticed different behaviour when a jpeg has a `jpg`/`jpeg` extension, and when it has any other extension (except `webp`) or no extension at all.

A jpeg with no extension, or any(?) extension other than `jpg`,`jpeg`,`webp`:
```
[   0.015][v][demux] Trying demuxers for level=normal.
[   0.015][d][demux] Trying demuxer: disc (force-level: normal)
[   0.015][d][demux] Trying demuxer: edl (force-level: normal)
[   0.015][d][demux] Trying demuxer: cue (force-level: normal)
[   0.015][d][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.016][d][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.016][d][demux] Trying demuxer: mkv (force-level: normal)
[   0.016][d][demux] Trying demuxer: libarchive (force-level: normal)
[   0.016][d][demux] Trying demuxer: lavf (force-level: normal)
[   0.040][v][demux] Detected file format: jpeg_pipe (libavformat)
```

A jpeg with `jpg` or `jpeg` extension:
```
[   0.025][v][demux] Trying demuxers for level=normal.
[   0.025][d][demux] Trying demuxer: disc (force-level: normal)
[   0.025][d][demux] Trying demuxer: edl (force-level: normal)
[   0.025][d][demux] Trying demuxer: cue (force-level: normal)
[   0.025][d][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.025][d][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.025][d][demux] Trying demuxer: mkv (force-level: normal)
[   0.025][d][demux] Trying demuxer: libarchive (force-level: normal)
[   0.025][d][demux] Trying demuxer: lavf (force-level: normal)
[   0.031][d][demux] Trying demuxer: mf (force-level: normal)
[   0.031][d][demux] Trying demuxer: playlist (force-level: normal)
[   0.031][d][demux] Trying demuxer: null (force-level: normal)
[   0.031][v][demux] Trying demuxers for level=unsafe.
[   0.031][d][demux] Trying demuxer: disc (force-level: unsafe)
[   0.031][d][demux] Trying demuxer: edl (force-level: unsafe)
[   0.031][d][demux] Trying demuxer: cue (force-level: unsafe)
[   0.031][d][demux] Trying demuxer: rawaudio (force-level: unsafe)
[   0.031][d][demux] Trying demuxer: rawvideo (force-level: unsafe)
[   0.031][d][demux] Trying demuxer: mkv (force-level: unsafe)
[   0.031][d][demux] Trying demuxer: libarchive (force-level: unsafe)
[   0.032][d][demux] Trying demuxer: lavf (force-level: unsafe)
[   0.037][d][demux] Trying demuxer: mf (force-level: unsafe)
[   0.037][v][demux] Detected file format: image files (mf)
```
A jpeg with `webp` extension:
```
[   0.023][v][demux] Trying demuxers for level=normal.
[   0.023][d][demux] Trying demuxer: disc (force-level: normal)
[   0.023][d][demux] Trying demuxer: edl (force-level: normal)
[   0.023][d][demux] Trying demuxer: cue (force-level: normal)
[   0.023][d][demux] Trying demuxer: rawaudio (force-level: normal)
[   0.023][d][demux] Trying demuxer: rawvideo (force-level: normal)
[   0.023][d][demux] Trying demuxer: mkv (force-level: normal)
[   0.023][d][demux] Trying demuxer: libarchive (force-level: normal)
[   0.023][d][demux] Trying demuxer: lavf (force-level: normal)
[   0.029][d][demux] Trying demuxer: mf (force-level: normal)
[   0.029][d][demux] Trying demuxer: playlist (force-level: normal)
[   0.029][d][demux] Trying demuxer: null (force-level: normal)
[   0.029][v][demux] Trying demuxers for level=unsafe.
[   0.029][d][demux] Trying demuxer: disc (force-level: unsafe)
[   0.029][d][demux] Trying demuxer: edl (force-level: unsafe)
[   0.029][d][demux] Trying demuxer: cue (force-level: unsafe)
[   0.029][d][demux] Trying demuxer: rawaudio (force-level: unsafe)
[   0.029][d][demux] Trying demuxer: rawvideo (force-level: unsafe)
[   0.029][d][demux] Trying demuxer: mkv (force-level: unsafe)
[   0.029][d][demux] Trying demuxer: libarchive (force-level: unsafe)
[   0.030][d][demux] Trying demuxer: lavf (force-level: unsafe)
[   0.034][d][demux] Trying demuxer: mf (force-level: unsafe)
[   0.034][d][demux] Trying demuxer: playlist (force-level: unsafe)
[   0.034][d][demux] Trying demuxer: null (force-level: unsafe)
```

**Comment by inca-viewer** [comment]
thank you for all your support
mpv does now work on true .webp files
the problem seems to be firefox or reddit marking images as webp incorrectly when saved

**Comment by wm4** [comment]
> This is actually a jpeg, and strangely enough the demuxer fails if a jpeg has a webp extension.

Probably partially because ffmpeg's jpg probing sucks ass (CC @richardpl, ffmpeg sucks).

**Comment by richardpl** [comment]
ffplay worls fine with that file, mpv sucks.

**Comment by inca-viewer** [comment]
https://www.reddit.com/r/RoomPorn/comments/eupiyu/chiesa_san_giuseppe_arbedocastione_switzerland/

example image above saves as webp in firefox on windows 10
not mpv problem

**Comment by wm4** [comment]
@richardpl that .txt link? No it doesn't. Even worse.. it plays it as "tty"! That's beyond ridiculous. FFmpeg sucks.

**Comment by richardpl** [comment]
Renamte it to webp. mpv sucks

**Comment by Akemi** [comment]
on a side note. the sample1.txt renamed with a .webp extension works for me in ffplay. though an older version:
```
ffplay /Volumes/AkemiData/Downloads/sample1.webp 
ffplay version git-2019-11-06-fc7b6d5 Copyright (c) 2003-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.8)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/HEAD-fc7b6d5 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-nonfree --enable-hardcoded-tables --enable-avresample --cc=/usr/bin/clang --host-cflags='-Os -w -pipe -march=nehalem -Xclang -target-feature -Xclang -aes -mmacosx-version-min=10.14 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers/' --host-ldflags='-L/usr/local/opt/openssl/lib -L/usr/local/opt/libxml2/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk' --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libgme --enable-libass --enable-libbluray --enable-libbs2b --enable-libgsm --enable-libsoxr --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libxml2 --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I/usr/local/Cellar/openjpeg/2.3.1/include/openjpeg-2.3 --enable-openssl --enable-libopus --enable-librtmp --enable-librubberband --enable-ffplay --enable-libsnappy --enable-libspeex --enable-libtesseract --enable-libtheora --enable-libwavpack --enable-libwebp --enable-libx265 --enable-lzma --enable-libzmq --enable-libzimg --enable-videotoolbox --enable-opencl
  libavutil      56. 35.101 / 56. 35.101
  libavcodec     58. 60.100 / 58. 60.100
  libavformat    58. 34.101 / 58. 34.101
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 66.100 /  7. 66.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, image2, from '/Volumes/AkemiData/Downloads/sample1.webp':
  Duration: 00:00:00.04, start: 0.000000, bitrate: 40250 kb/s
    Stream #0:0: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1920x1037 [SAR 1:1 DAR 1920:1037], 25 tbr, 25 tbn, 25 tbc
[swscaler @ 0x7fe390020000] deprecated pixel format used, make sure you did set range correctly
  28.43 M-V:  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
```

**Comment by CounterPillow** [comment]
Works for me in ffplay n4.2.2 and N-96528-g26c7f91e66 (current git HEAD)

Notable mpv output to maybe explain the discrepancy:
```
[lavf] Found 'image2' at score=50 size=2048.
[lavf] Format blacklisted.
[lavf] No format found, try lowering probescore or forcing the format.
```

**Comment by CounterPillow** [comment]
mpv indeed blacklists the autoprobed image2 format, which was done in https://github.com/mpv-player/mpv/commit/d0fee0ac33a02e3dcb6c4b27b554be70e6b64e7a

**Comment by philipl** [comment]
I guess that when the extension is wrong, it takes a different path through `image2`, which would ultimately get to the right place if we let it.

**Comment by wm4** [comment]
Yeah, the image2 demuxer may be the reason why ffplay can open the file in this case, but the demuxer is unacceptable for other reasons. It's basically ffmpeg.c's command line handling of what mpv has as "mf://", except it's used on any filename. FFmpeg sucks.

**Comment by richardpl** [comment]
image2 have also probe code, mpv sucks.

**Comment by wm4** [comment]
image2 doesn't actually have probe code (img_read_probe does not read from the probe buffer, only checks the provided filename, that's inacceptable in addition to the filename pattern interpretation image2 forces). FFmpeg devs don't know their code, FFmpeg sucks.

**Comment by CounterPillow** [comment]
why are mommy and daddy fighting

**Comment by garoto** [comment]
[**@CounterPillow**](https://github.com/CounterPillow) commented on [Jan 28, 2020, 3:06 PM GMT-3](https://github.com/mpv-player/mpv/issues/7390#issuecomment-579380073 "2020-01-28T18:06:09Z - Replied by Github Reply Comments"):
> why are mommy and daddy fighting

Wait, isn't @ddevault your mommy? I'm confused. But who am I to judge how many mommies one have nowadays.

**Comment by richardpl** [comment]
@wm4 neither mpv mf code does it, so mpv sucks.

**Comment by wm4** [comment]
mpv needs mf for normal files only because ffmpeg sucks and fails to probe certain image files by content. ffmpeg sucks.

**Comment by Hrxn** [comment]
Attention, attention, the daycare will close in 15 minutes!

**Comment by richardpl** [comment]
ffmpeg have probe function for image codecs, just not for image2, patch welcome, mpv really sucks.

**Comment by wm4** [comment]
mpv uses these probe function. ffmpeg always says "patch welcome" when their shit breaks horribly for its API users. ffmpeg really sucks.

**Comment by richardpl** [comment]
I wrote tty probe function, to make mpv play those nice ans,art,asc,diz,ice,nfo,txt,vt files. Mpv will suck until it supports great tty demuxer again.

**Comment by wm4** [comment]
Seems like a rather weak probe function. In this case I'd still prefer mpv to suck for nfo lovers.

**Comment by richardpl** [comment]
join ffmpv fork team, we do care about mpv missed features.

**Comment by shankarsivarajan** [comment]
So reading between the sniping, the solution is simply to change the .webp extension? That's an easy enough fix. Thanks.

**Comment by iiiGerardoiii** [comment]
It seems it has trouble playing animated webp images. (ANIM and ANMF chunks), I'm guessing this more of a ffmpeg problem?

This is the image I'm testing: https://files.catbox.moe/k1yzuv.webp

**Comment by guidocella** [comment]
Correct: https://trac.ffmpeg.org/ticket/4907

**Comment by garoto** [comment]
This issue is peak gh mpv. Should be pinned.

**Comment by davehorner** [comment]
webp support is still an issue.

try creating some animated webp using https://developers.google.com/speed/webp/docs/img2webp
mpv and ffplay both do not play them.
chrome and irfanview support the animated webp just fine.

**Comment by GunGunGun** [comment]
Same, try to open this image (+18) in mpv and you will get:
```
[ffmpeg/video] webp: skipping unsupported chunk: ANIM
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: ANMF
[ffmpeg/video] webp: skipping unsupported chunk: XMP
```
With gallery-dl getting popular, not being able to read webp in mpv kinda sucks, because the whole idea of using gallery-dl with mpv is for skipping ads and stuffs.

https://files.catbox.moe/4mmcmz.webp

**Comment by guidocella** [comment]
Until ffmpeg implements supports you can use `magick foo.webp -coalesce webm:- | mpv -`

**Comment by GunGunGun** [comment]
> Until ffmpeg implements supports you can use `magick foo.webp -coalesce webm:- | mpv -`

Tried it, it kinda works but I'm not pleased because it uses a tons of CPU to transcode webp to webm, I'll wait for ffmpeg to fix it because currently it sucks.

**Comment by Rabcor** [comment]
> webp support is still an issue.
> 
> try creating some animated webp using https://developers.google.com/speed/webp/docs/img2webp mpv and ffplay both do not play them in my testing. chrome and irfanview support the animated webp just fine. given some direction; I'm willing to spend some time on this.

yes, but by the sound of it wouldn't this be more an ffmpeg issue than an mpv one? Although mpv is indeed affected. ffmpeg webp support seems lacking.

**Comment by Rabcor** [comment]
> Is this ffmpeg issue ? I don't even know how to view their bug reports lmao. A summary progress on this issue is welcome plz.

it is an ffmpeg issue (i mean just try to work with webp in ffmpeg, it'll fail)

but ffmpeg is a big projects with an insanely huge backlog of issues, so the progress is nil even if it was reported i believe years ago.

Sure, mpv could technically implement it's own webp support, but it doesn't seem like it'd be worth the hassle when they can just wait a few years for ffmpeg devs to fix their shit.

**Comment by GunGunGun** [comment]
It'll probably take forever for ffmpeg to implement this, we better just steal Google's libwebp because it's the best anyway.
