### ISSUE TITLE
Subtitle font based on the language

### ISSUE THREAD

**Issue by mjuzikfrik** [mpv-player/mpv#7391]
Hello, 
I'd like to ask if it's possible to have a different font for different languages. For example one for all European languages and one for Japanese. I tried to do it with auto profiles script but I can't find a property to make it work or am doing something wrong.

**Comment by lachs0r** [comment]
This is actually something your operating system should take care of, through font fallback (in practice, a locale-dependent list of fonts that get used when the primary one does not cover glyphs that are going to be displayed). On Linux, this is configurable through fontconfig.

If you want to use auto-profiles: The `slang` property should be the one you’re looking for.

**Comment by mjuzikfrik** [comment]
Yeah, the system fallback font looks ugly in my opinion and I'd prefer not to change system settings.

I added this to my config but it doesn't seem to work. I always get Netflix font for Japanese subtitles.

[JPSubsProfile]
profile-desc=cond:p["slang"]=="jpn" or p["slang"]=="jp" or p["slang"]=="jap" or p["slang"]=="Japanese"
sub-font=A-OTF シネマレター Std L

[JPSubsProfile-Revert]
profile-desc=cond:p["slang"]~="jpn" or p["slang"]~="jp" or p["slang"]~="jap" or p["slang"]~="Japanese"
sub-font=Netflix Sans

**Comment by mjuzikfrik** [comment]
It does work when I use match.string and the sid parameter but not slang for some reason. Of course sid is kind of useless unless the subtitle id is always the same.

[JPSubsProfile]
profile-desc=cond:string.match(p["sid"], "36")~=nil
sub-font=A-OTF シネマレター Std L

[JPSubsProfile-Revert]
profile-desc=cond:string.match(p["sid"], "36")==nil
sub-font=Netflix Sans

**Comment by Akemi** [comment]
my guess is, slang is just what you set in your config and not what was actually selected. you can try this for testing, that should print the current value of it.

```
X show-text "${slang}"
```

**Comment by mjuzikfrik** [comment]
I'm sorry but I don't know where to put it. Just anywhere in the mpv.conf or replace with something in the code I provided?

**Comment by Akemi** [comment]
that was a keybinding, so it should go into the input.conf

my best bet to do this, is getting the track-list, iterate over it, test for type sub and get the lang property. since the cond of auto profiles is a lua expression it should be possible(?), though i think your own script might be better and easier to read.

an example of getting the data of the third track bound to the `F` key
```
function test()
    local tracktable = mp.get_property_native("track-list", {})
    mp.osd_message(tracktable[3].type .. " " .. tracktable[3].lang .. " " .. tostring(tracktable[3].selected))
end

mp.add_key_binding("F", "test", test)
```

example how the track-list can look like:
```
{
    [1] = {
        ["ff-index"] = 0,
        ["forced"] = false,
        ["hearing-impaired"] = false,
        ["external"] = false,
        ["decoder-desc"] = h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10),
        ["codec"] = h264,
        ["selected"] = true,
        ["type"] = video,
        ["visual-impaired"] = false,
        ["albumart"] = false,
        ["id"] = 1,
        ["dependent"] = false,
        ["demux-h"] = 574,
        ["demux-par"] = 1,
        ["title"] = Toaru Kagaku no Railgun: Much More Railgun I,
        ["demux-fps"] = 23.976024167641,
        ["demux-w"] = 1024,
        ["src-id"] = 1,
        ["lang"] = jpn,
        ["default"] = true,
        } 
    [2] = {
        ["ff-index"] = 1,
        ["forced"] = false,
        ["hearing-impaired"] = false,
        ["external"] = false,
        ["src-id"] = 2,
        ["codec"] = flac,
        ["demux-samplerate"] = 48000,
        ["selected"] = true,
        ["type"] = audio,
        ["visual-impaired"] = false,
        ["albumart"] = false,
        ["id"] = 1,
        ["dependent"] = false,
        ["demux-channels"] = unknown2,
        ["default"] = true,
        ["demux-channel-count"] = 2,
        ["decoder-desc"] = flac (FLAC (Free Lossless Audio Codec)),
        ["audio-channels"] = 2,
        ["lang"] = jpn,
        ["title"] = FLAC,
        } 
    [3] = {
        ["ff-index"] = 2,
        ["type"] = sub,
        ["visual-impaired"] = false,
        ["albumart"] = false,
        ["id"] = 1,
        ["dependent"] = false,
        ["src-id"] = 3,
        ["forced"] = false,
        ["codec"] = ass,
        ["default"] = true,
        ["external"] = false,
        ["hearing-impaired"] = false,
        ["selected"] = true,
        ["lang"] = eng,
        ["title"] = toayuku,
    }
}
```

example in the osc code https://github.com/mpv-player/mpv/blob/master/player/lua/osc.lua#L326-L348
