### ISSUE TITLE
Add lrby support

### ISSUE THREAD

**Issue by 2secslater** [mpv-player/mpv#7392]
### Expected behavior of the wanted feature
I would like to be able to play a video by executing the following:
`mpv lbry://@MH#5/Why-I-Quit-YouTube#d`
which would play the same video as you would be able to play by visiting:
https://lbry.tv/@MH:5/Why-I-Quit-YouTube:d in a web browser

**Comment by sfan5** [comment]
mpv uses [youtube-dl](https://github.com/ytdl-org/youtube-dl) to "parse" websites into playable video URLs, consider asking there.

**Comment by philipl** [comment]
For the record: https://github.com/ytdl-org/youtube-dl/issues/23695
