### ISSUE TITLE
Mouse pointer invisible

### ISSUE THREAD

**Issue by epsilontheta** [mpv-player/mpv#7395]
### Important Information

Provide following Information:
- mpv version: 0.31.0
- Linux Distribution and Version: Fedora 31
- Source of the mpv binary: ?
- If known which version of mpv introduced the problem
- Window Manager and version: Gnome Shell 3.34.3 (wayland)
- GPU driver and version: amdgpu, kernel 5.4.13
- Possible screenshot or video of visual glitches

### Reproduction steps

* play a video
* toggle to fullscreen by double clicking
* mouse pointer is gone and does not reappear when moving the mouse
* toggle back to window mode by double clicking
* window moves to second monitor (not always)
* mouse pointer is still invisible when mouse pointer is over window

### Expected behavior
* mouse pointer is visible again after moving the mouse

### Actual behavior
* mouse pointer remains invisible

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/4113449/mpv.log)

### Sample files

**Comment by CounterPillow** [comment]
try with the latest git version, there were changes related to this.

**Comment by Dudemanguy** [comment]
Yeah it should be fixed in the latest git.

**Comment by CounterPillow** [comment]
Then I'll close this since we're about to cut a release anyway.
