### ISSUE TITLE
Ability to change path property

### ISSUE THREAD

**Issue by noctuid** [mpv-player/mpv#7397]
I have a script that uses hooks to play magnet links using peerflix. I want to be able to change `path` to be the path that peerflix downloads the video to or at least change `media-title` or `filename` to the video's name, but trying to set any of these properties has no effect. I had a request to set the path (noctuid/mpv-peerflix-hook#3), so that an autosub plugin that looks at the path will work.

**Comment by garoto** [comment]
> [...] or at least change `media-title` [...]

`force-media-title`
