### ISSUE TITLE
Unable to cycle through multiple values, several being identical

### ISSUE THREAD

**Issue by Dupond** [mpv-player/mpv#7398]
### Important Information

- mpv version : 1:0.31.0-2 (latest version available in the Arch repos)
- Linux Distribution and Version : Arch Linux 5.4.15
- Source of the mpv binary : Arch "Commuinity" repos
- GPU driver and version : ATI RV770 [Radeon HD 4850]

### Reproduction steps

In `input.conf`, set up :
`V no-osd cycle-values sub-font "Sans" "Sans" "Serif" "Serif" "Serif" "Sans"; no-osd cycle-values sub-color "#FFFF00" "#FFFF00" "#FFFFFF" "#FFFF00" "#FFFF00" "#FFFFFF"; no-osd cycle-values sub-shadow-color "#000000" "#FFFFFF" "#000000" "#000000" "#FFFFFF" "#000000"; no-osd cycle-values sub-ass-override "force" "force" "force" "force" "force" "force"`
Open a file with SRT subtitles in `mpv`, then when a subtitle appears, press `V` to cycle through subtitle styles.

### Expected behavior

It should allow to cycle through subtitle styles with a single keybind, instead of having one for the font, another one for the colour, and another one for the shadow color. So it should cycle through the following values :
- Sans serif font, yellow, with black border ;
- Sans serif font, yellow, with white border ;
- Serif font, white, with black border ;
- Serif font, yellow, with black border ;
- Serif font, yellow, with white border ;
- Sans serif font, white, with black border (so go back to default).

### Actual behavior

The keybind does nothing ; it simply has no effect at all, and nothing is displayed in the console.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/4114340/output.txt)

**Comment by haasn** [comment]
This is probably about the level of complexity where a script would be needed. The `cycle_values` command is notoriously difficult to get right for all use cases, and the current solution we've settled on effectively prevents you from having the same value multiple times inside the same cycle list.

**Comment by Dupond** [comment]
OK, I understand that. I haven't seen this information in the man page, though. Maybe it could be added ?
Furthermore, I have no idea as to how a script could be written to accomplish this. Or does it already exist somewhere ?
Thanx for the help !

**Comment by CogentRedTester** [comment]
I did attempt to write a script ([here](https://github.com/CogentRedTester/my-mpv-settings/blob/master/scripts/cycle-commands.lua)) which could do that some time ago. I'm pretty new to Lua so it's a bit messy, and I can't guarantee it'll work in every scenario, but it should work for something like this.

**Comment by Dupond** [comment]
This is nice ! I'm new to Lua too, but I'd like to give it a chance ;)
So, I'm not sure I understand how it works; it would be :
`V script-message cycle-commands 'sub-font "Sans" ; sub-color "#FFFF00" ; sub-shadow-color "#000000" ; sub-ass-override "force" | sub-font "Sans" ; sub-color "#FFFF00" ; sub-shadow-color "#FFFFFF" ; sub-ass-override "force" | sub-font "Serif" ; sub-color "#FFFFFF" ; sub-shadow-color "#000000" ; sub-ass-override "force" | sub-font "Serif" ; sub-color "#FFFF00" ; sub-shadow-color "#000000" ; sub-ass-override "force" | sub-font "Serif" ; sub-color "#FFFF00" ; sub-shadow-color "#FFFFFF" ; sub-ass-override "force" | sub-font "Sans" ; sub-color "#FFFFFF" ; sub-shadow-color "#000000" ; sub-ass-override "force"`
Am I right ?

**Comment by CogentRedTester** [comment]
The script assumes everything separated by spaces is a string, so you don't need to use quotation marks inside the string.

Also the reason you're getting that message is that sub-color is the property you're changing, not the command. You need to use the 'set' command first in order for the script to change the property. I changed it to this and it seems to work on my end:

`V script-message cycle-commands "set sub-font Sans ; set sub-color #FFFF00 ; set sub-shadow-color #000000 ; set sub-ass-override force | set sub-font Sans ; set sub-color #FFFF00 ; set sub-shadow-color #FFFFFF ; set sub-ass-override force | set sub-font Serif ; set sub-color #FFFFFF ; set sub-shadow-color #000000 ; set sub-ass-override force | set sub-font Serif ; set sub-color #FFFF00 ; set sub-shadow-color #000000 ; set sub-ass-override force | set sub-font Serif ; set sub-color #FFFF00 ; set sub-shadow-color #FFFFFF ; set sub-ass-override force | set sub-font Sans ; set sub-color #FFFFFF ; set sub-shadow-color #000000 ; set sub-ass-override force"`

**Comment by Dupond** [comment]
Now it works great, indeed ! Thank you very much !
