### ISSUE TITLE
On the deprecation of video-sync=display-adrop and audio passthrough.

### ISSUE THREAD

**Issue by kokoko3k** [mpv-player/mpv#7400]
Hello,
i just noticed that video-sync=display-adrop has been deprecated and can be removed anytime.
It is a bad news to me, and i think to everyone relying on audio passthrough, because afaik it is the only way to modify audio so that video can play smoothly from the start to the end of the stream when refresh rates don't match.
It is super useful when playing Video+DTS or ac3 content on 23.976hz TVs or vice-versa.
(As a side and probably less important note, when using *-adrop with my tv set, i can even play 23.976 videos on 60hz and have it interpolate the missing frames without stuttering; 
That unfortunately don't work using other resample methods that produces stuttering every 8 seconds, but it may be specific to my Tv)

Can you please reconsider?

Thank you for your attention.

**Comment by xantoz** [comment]
Stuttering every 8 seconds sounds a bit similar to https://github.com/mpv-player/mpv/issues/6037 . Are you perhaps using the intel driver with xf86-video-modesettiong? I've mainly observed it with 60 FPS video, however.

**Comment by kokoko3k** [comment]
Thanks, but no; i'm testing from nvidia ION; stuttering is expected because refresh rates don't match, so cutting audio here and there helps (nio audible clicks/pops)

**Comment by xantoz** [comment]
Stuttering is not to be expected with e.g. video-sync=display-resample. It should try slow down/speed up the video and audio to match the screens refresh rate.

**Comment by kokoko3k** [comment]
You cannot  slow down/speed up the video **and audio**  when you're using audio passthrough unless you'r using video-sync=display-adrop.
This is what this 'thread' is about; the deprecation of video-sync=display-adrop.

**Comment by xantoz** [comment]
Yes, but the first message implied that it stutters with all other video-sync methods (even the ones that are incompatible with passthrough).

**Comment by kokoko3k** [comment]
I tried to create 48hz and 72hz modelines, but unfortunately the Tv rejected them.

**Comment by xantoz** [comment]
Probably because those are too far off from what the TV actually supports. The idea is to take the 23.976 Hz modeline from the TVs EDID and then tweak it little by little while staying inside the TVs supported range.

**Comment by wm4** [comment]
Not particularly fond of passthrough. It's also only needed with horrible hardware like TV (I would never use that).
So if I get to rewrite mpv's audio path one day, either reimplementing or dropping the audio drop feature would be required... probably the former.

**Comment by kokoko3k** [comment]
I own a 5.1 audio decoder feeded with dts or ac3 streams; audio goes undecoded directly to it.
The TV itself is not responsable, if not for the inhability to be programmed with custom modelines.

**Comment by xantoz** [comment]
@kokoko3k Seems like your situation is quite similar to mine then.
Might I suggest the following workaround from my mpv config:
```
[audio-ac3]
audio-device="alsa/ac3hdmi"
audio-channels="5.1(alsa)"
alsa-buffer-time=1000000
alsa-periods=1000
```
And the following in .asoundrc:
```
pcm.a52hdmi {
    type a52
    slavepcm "hdmi:CARD=PCH,DEV=2,AES0=6"
    bitrate 640
    channels 6
}

pcm.ac3hdmi {
    type plug
    slave.pcm "a52hdmi
}
```

Tweak the `slavepcm` line as needed.

When I run ```mpv --profile=audio-ac3``` This will encode to ac3 on the fly and send it over HDMI (there is a HDMI muxer later in the chain that extracts the audio as SPDIF). That way I can play 5.1 audio with `--video-sync=display-resample` at the cost of an extra generation of compression (less of an issue these days as sound is increasingly lossless in the source file).


There also exists `--af=lavcac3enc` in mpv, but sadly it can't be used at the same time as `video-sync=display-resample` at the moment, even though it should be possible in theory, so I resorted to using the a52 plugin in alsa instead.

**Comment by xantoz** [comment]
Another simpler workaround could be to matrix the sound as Pro Logic II, which I've used previously.

```
[dplii]
audio-swresample-o=matrix_encoding=dplii
audio-channels=5.1
```

With this you only send a matrixed stereo signal, so it is harder to have something go wrong. The audio quality is a lot worse, however.

**Comment by kokoko3k** [comment]
Thanx, xantoz, but unfortunately:
1. my Tv set supports 24hz and 50hz, but refuses 48hz and 23.976 modelines, meh.
2. my cpu power on the htpc is extremely limited, i used --speed parameter (no need to set any video-sync method, try it) with ac3 encoding on the fly in the past; it works, but it makes the entire system sluggish and i've stutters because of it, eheh :)

**Comment by wm4** [comment]
video-sync=display-adrop is now undeprecated. Hopefully behaves similar for passthrough (hard to test), but for PCM it'll be worse. It makes no sense to use with PCM anyway.

**Comment by wm4** [comment]
> There also exists --af=lavcac3enc in mpv, but sadly it can't be used at the same time as video-sync=display-resample at the moment, even though it should be possible in theory,

That could be fixed by adding lavcac3enc automatically in the filter chain, and after the resampler. (Probably in auto filters or so?) But still problematic.
