### ISSUE TITLE
How to pass options to ffmpeg used by mpv ?

### ISSUE THREAD

**Issue by superuser789** [mpv-player/mpv#7402]
I am trying to stream hls link using mpv. The Link needs specific http headers which I have passed to mpv using ` --http-header-fields='field1=value1','field2=value2'`.  The hls file also has key links to decrypt the video chunks.  The key file link is opened by ffmpeg but due to the absence of specific http headers, it shows  `HTTP error 403 Forbidden`.

How can I give those specific http headers to mpv so that these are passed to the ffmpeg as well ?
Here is the output ::
```
[ffmpeg] https: HTTP error 403 Forbidden
[ffmpeg/demuxer] hls: Unable to open key file https://HLS_URL/file.key
[ffmpeg/demuxer] hls: Error when loading first segment 'http://HLS_URL.ts'
[lavf] avformat_open_input() failed
```

**Comment by CounterPillow** [comment]
Try settings `--demuxer-lavf-o=headers=` to ["a string encoding the headers."](https://ffmpeg.org/ffmpeg-protocols.html#http) (whatever that means, maybe adding `\n` in between headers)
