### ISSUE TITLE
[regression] build 1:0.32 broken --audio-files option

### ISSUE THREAD

**Issue by bugandy** [mpv-player/mpv#7403]
After update mpv to 1:0.32 trough pacman cmi options "--audio-files" do not work anymore, always end with: "Error parsing commandline option audio-files: option requires parameter", of course I passing at least one parameter to it.

Downgrade to 1:0.31 solve issue.

**Comment by CounterPillow** [comment]
Stop using legacy option syntax with new-style options. Instead of a space after `--audio-files`, use a `=`. This is documented in interface-changes.rst.

Also don't ignore the issue template.

**Comment by bugandy** [comment]
Thank you for info.

I've read option from --list-options without, ehmm, reading the man. :-\

Sorry.
