### ISSUE TITLE
mpv 0.32 build fails

### ISSUE THREAD

**Issue by TCH68k** [mpv-player/mpv#7404]
### mpv version and platform versions

Devuan 2 AMD64
MPV 0.32
FFMPEG 4.1
GCC 7.3.0

### Reproduction steps

wget https://github.com/mpv-player/mpv/archive/v0.32.0.tar.gz
tar -xzvf v0.32.0.tar.gz
cd mpv-0.32.0/
./bootstrap.py
./waf configure --disable-pulse
./waf

### Expected behavior

Build.

### Actual behavior

Fails.

### Log file

[mpv_build.log](https://github.com/mpv-player/mpv/files/4119639/mpv_build.log)

**Comment by sfan5** [comment]
Upload `build/config.log` too.

**Comment by CounterPillow** [comment]
Builds fine with ffmpeg 4.1 for me.

**Comment by TCH68k** [comment]
[config.log](https://github.com/mpv-player/mpv/files/4121571/config.log)

**Comment by TCH68k** [comment]
I have updated FFMPEG to the latest 4.2.2. No change. I have tried to compile earlier MPV releases down to 0.28.2 (which is not FFMPEG4 dependent) all of them failed. Can it be a GCC issue? I use GCC 7.3.0.

I've done another test compiling, this time with the verbose flag. All the build flags mentioned in the last failed command are working otherwise.

[mpv_build_verbose.log](https://github.com/mpv-player/mpv/files/4122729/mpv_build_verbose.log)

**Comment by wm4** [comment]
That's a linker error. Maybe something is wrong with the ffmpeg build or installation.

**Comment by CounterPillow** [comment]
>`out: -I/usr/local/include -L/usr/local/lib`

Seems like you have a random FFmpeg in `/usr/local/lib`, is this intentional?

**Comment by TCH68k** [comment]
@wm4 
What could it be? FFMPEG itself is working.

@CounterPillow 
Not random. Devuan 2 is Debian 9 which ships FFMPEG 3.2.14, so i compiled FFMPEG 4.2.2, that is in `/usr/local/lib`.

**Comment by CounterPillow** [comment]
if your ffmpeg library isn't exporting those symbols then it's a broken build. We don't know how you compiled ffmpeg, so you're the one who has to figure this out.

**Comment by TCH68k** [comment]
My current MPV installation (which was built earlier) works with it.

I compiled FFMPEG with these options:
`./configure --enable-gpl --disable-debug --disable-doc --enable-gnutls --enable-nonfree --disable-libfontconfig --disable-filter='ass,drawtext,coreimage,coreimagesrc' --disable-avdevice --enable-static --disable-shared --enable-libass --enable-opengl`

**Comment by CounterPillow** [comment]
>My current MPV installation (which was built earlier) works with it.

but also

>I have tried to compile earlier MPV releases down to 0.28.2 (which is not FFMPEG4 dependent), all of them failed.

so your currently compiled mpv version is <= 0.28.2 but builds against ffmpeg 4.2.2?

**Comment by TCH68k** [comment]
No. Earlier i built FFMPEG 4.1 and MPV 0.29.1 and it worked. It still worked yesterday, when i tried to build MPV 0.32.0 and that failed. Then i updated FFMPEG to 4.2.2. The build still fails, but the already built MPV is still works. So, something else is broken in my system, than FFMPEG.

**Comment by CounterPillow** [comment]
You made a static ffmpeg build. The mpv you compiled does not load any objects from that ffmpeg directory. Your current mpv is not influenced by what's in that directory at all.

**Comment by TCH68k** [comment]
Then why did the former build work? I did exactly the same as then.

**Comment by CounterPillow** [comment]
Because you didn't do exactly the same as then, probably changed something in your toolchain or other jenga tower of local builds, and now things no longer work as expected.

If you find an actual problem in mpv or its build system feel free to report it, but I am afraid we are not veteran enough sysadmins to debug your Devuan system for you.

Personally I'd start with `objdump -t libavcodec.a` and grep for the symbols. The ones that the linker fails to resolve appear to be fairly important ones so I think something is seriously screwed up.

**Comment by TCH68k** [comment]
You seem to be right about the missing symbols:
`objdump -t /usr/local/lib/libavcodec.a | grep mp_image_to_av_frame` gives back nothing.
Can you tell me please what is wrong with my FFMPEG configuration line?

**Comment by CounterPillow** [comment]
I don't see anything wrong with your configure line so I'm fairly sure the problem is something stateful that you'd best rectify by getting rid of your ffmpeg build and source tree and trying from scratch. First I'd check that `/usr/local/lib/libavcodec.a` is actually what you just compiled, and not something from another time. You can do this easily by removing it first.

**Comment by TCH68k** [comment]
Yes, i have already checked that, `/usr/local/lib/libavcodec.a` is from the package i built today. However i already deleted that package and my former MPV build still works without any FFMPEG installed in the system. Now, i have "libavcodec57" installed, but that is from FFMPEG 3.2.14 and MPV 0.29 depends on FFMPEG 4, isn't it?

**Comment by CounterPillow** [comment]
>and my former MPV build still works without any FFMPEG installed in the system.

please actually read my comments and you'll understand why.

**Comment by TCH68k** [comment]
Whoops, sorry, i am half asleep already. I think i'll continue tomorrow. Thanks for the help.

**Comment by TCH68k** [comment]
Okay, rebuilt FFMPEG 4.2.2 again. `/usr/local/lib/libavcodec.a` is there again.
I've grepped for 'avcodec_receive_frame' this time:
```0000000000001540 g     F .text  0000000000000325 avcodec_receive_frame
0000000000000000         *UND*  0000000000000000 avcodec_receive_frame```

**Comment by TCH68k** [comment]
Okay, i've eradicated all libavxxx and all related libraries from my system and then i've recompiled FFMPEG 4.2.2 as dynamic. Then i discovered that there are some leftover libavxxx shared objects in `/usr/local/lib` which were installed earlier under Debian Jessie but then were simply superseded on Devuan ASCII, but somewhy were not deleted. Now that those were removed and FFMPEG 4 is recompiled as dynamic, MPV 0.32.0 compiles without any problem.

Thanks for the help again.
