### ISSUE TITLE
Add stop-after-current input command

### ISSUE THREAD

**Issue by sudo-nice** [mpv-player/mpv#7407]
### Expected behavior of the wanted feature
After the `stop-after-current` command is implemented, one could stop playback right at the end of the currently playing file. I use MPV as an audio player and I miss the feature badly. Would be nice to be able to trigger the `stop-after-current` command both with a keypress or sending command via socket.

### Alternative behavior of the wanted feature
None.

**Comment by wm4** [comment]
"playlist-clear" should have the same effect.

**Comment by sudo-nice** [comment]
That's a nice hack, thanks a lot!
