### ISSUE TITLE
Extremely slow cache when playing from cifs shares in 0.30, 0.31, 0.32, master

### ISSUE THREAD

**Issue by LennertVA** [mpv-player/mpv#7408]
Identical symptoms as https://github.com/mpv-player/mpv/issues/7152. When playing a file from a cifs share, cache fills at ~300KB/sec, whereas copying the same file directly from the cifs share gets ~35MB/sec. For higher bitrate files the cache cannot keep up and the video stutters.

- Debian unstable on amd64
- Window manager: Cinnamon (packaged, 4.2.4-2)
- GPU: Intel Corporation Iris Plus Graphics G7 (rev 07)
- mpv built from source (git)

Problem was not present in 0.29.1 (previous Debian package version), present in the new package version (0.30) as well as git master. Logfile attached as requested.
[mpv.log](https://github.com/mpv-player/mpv/files/4122803/mpv.log)

Used git bisect to see where the problem was introduced:

```
$ git bisect good
559a400ac36e75a8d73ba263fd7fa6736df1c2da is the first bad commit
commit 559a400ac36e75a8d73ba263fd7fa6736df1c2da
Author: wm4 <wm4@nowhere>
Date:   Fri Aug 31 12:48:36 2018 +0200

    demux, stream: rip out the classic stream cache
    
    The demuxer cache is the only cache now. Might need another change to
    combat seeking failures in mp4 etc. The only bad thing is the loss of
    cache-speed, which was sort of nice to have.

 DOCS/man/input.rst         |  32 --
 DOCS/man/options.rst       | 100 +-----
 demux/demux.c              |  54 ++-
 demux/demux.h              |   3 +-
 demux/demux_disc.c         |   7 +-
 demux/demux_mkv_timeline.c |  10 -
 options/options.c          |   3 -
 options/options.h          |  12 -
 player/command.c           | 134 --------
 player/core.h              |   2 -
 player/loadfile.c          |   1 -
 player/misc.c              |  18 -
 player/osd.c               |  32 +-
 player/playloop.c          |   7 +-
 stream/cache.c             | 809 ---------------------------------------------
 stream/cache_file.c        | 158 ---------
 stream/stream.c            |  97 ------
 stream/stream.h            |  27 --
 stream/stream_avdevice.c   |   1 -
 stream/stream_dvb.c        |   1 -
 stream/stream_dvdnav.c     |   1 -
 stream/stream_edl.c        |   1 -
 stream/stream_file.c       |   1 -
 stream/stream_memory.c     |   1 -
 stream/stream_mf.c         |   1 -
 stream/stream_tv.c         |   1 -
 wscript_build.py           |   2 -
 27 files changed, 49 insertions(+), 1467 deletions(-)
 delete mode 100644 stream/cache.c
 delete mode 100644 stream/cache_file.c
```

**Comment by aufkrawall** [comment]
I don't think I have this issue on Arch/Manjaro.

**Comment by LennertVA** [comment]
As asked by people in #mpv IRC, --stream-buffer-size does not make any difference (tested with 2M, 4M, 8M). Stutter is instant and doesn't go away, cache fill rate remains at ~300KB/sec.

**Comment by wm4** [comment]
Fairly sure that's just a problem in the filesystem implementation. I have no idea why the old code behaved better, the difference as far as the filesystem layer is concerned are minimal. (Unless your cache is not growing when e.g. pausing.)

**Comment by LennertVA** [comment]
The cache does grow, but very slowly (pausing doesn't change the cache fill rate, as far as I can tell). Filesystem is cifs using automount with fairly default mount options other than the username and uid:

```
//10.1.0.10/data on /media/pinksock/data type cifs (rw,relatime,vers=3.1.1,cache=strict, 
username=alver,uid=1000,forceuid,gid=0,noforcegid,addr=10.1.0.10,file_mode=0755, 
dir_mode=0755,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304, 
bsize=1048576,echo_interval=60,actimeo=1)
```

Can't say I've noticed any difference in behaviour in any other applications so far - most of the stuff I do is copying via shell, and that goes at line speed.

**Comment by LennertVA** [comment]
Small test with two other available media players on my system, playing the same file as tested above:
MPlayer 1.3.0
VLC version 3.0.8 Vetinari (3.0.8-0-gf350b6b5a7

Both behave as expected, cache fills at normal speeds and playback works.

**Comment by wm4** [comment]
Is anyone willing to do some extensive tests, that would require building mpv from a branch?

**Comment by LennertVA** [comment]
> Is anyone willing to do some extensive tests, that would require building mpv from a branch?

Absolutely. I'll have to look into how to do that, but before last week I wasn't aware of git bisect either so not too worried 😁

I'm abroad now so no access to my workstation; starting Wednesday I can get testing.

**Comment by wm4** [comment]
I made two branches:

https://github.com/mpv-player/mpv/compare/read_stats_new
https://github.com/mpv-player/mpv/compare/read_stats_old

The "new" one is based on master, while the "old" one is a commit before the one you found as breaking commit via bisect. These are just for collecting information. The new one should behave like master (i.e. show broken behavior), while the old one should work as it used to.

Run both under exactly the same conditions (same file etc.), but make sure the expected behavior happens. In both cases, add something like ``--dump-stats=/tmp/stats.log`` (the filename will be overwritten with some sort of log). Then post the logs for each case. You can stop playback as soon as the expected problem or non-problem happens. The log should go to a fast filesystem (preferably tmpfs, maybe use /dev/shm if /tmp/ isn't), or it will interfere with the test.

**Comment by LennertVA** [comment]
Done. Both are ~5 seconds actual runtime (5 seconds media played time in _old, 1-2 seconds in _new). Same media file and location, logs were written to tmpfs.

[read_stats_new.log](https://github.com/mpv-player/mpv/files/4167953/read_stats_new.log)
[read_stats_old.log](https://github.com/mpv-player/mpv/files/4167954/read_stats_old.log)

**Comment by wm4** [comment]
Can't see much. The old code mostly reads in 64KB steps, sometimes less (probably when the ring buffer wraps), while the new code tries much larger reads.

Can you try this branch: https://github.com/mpv-player/mpv/tree/stream_shit
With ``--stream-force-buffer=yes --stream-buffer-size=128k --stream-log-debug=yes``. This won't produce a useful log with ``--dump-stats``, so don't use that, but the normal log might be useful (then best to get it with ``--log-file=/tmp/log.txt``). Also try half or double the buffer size. This is an old branch, not sure if it's bug-free.

**Comment by LennertVA** [comment]
Done; did it with 64, 128 and 256k. All three have the same stutter; smaller buffer size starts playing slightly faster (which I suppose is expected since it is full faster - the fill speed is the same from what I can tell from my network monitor).

[stream_shit-64k.log](https://github.com/mpv-player/mpv/files/4172676/stream_shit-64k.log)
[stream_shit-128k.log](https://github.com/mpv-player/mpv/files/4172678/stream_shit-128k.log)
[stream_shit-256k.log](https://github.com/mpv-player/mpv/files/4172680/stream_shit-256k.log)

**Comment by wm4** [comment]
No, the file isn't reopened. And with this last test, it read pretty much in 64k blocks, the same as with the old cache. There must be a timing issue, which seems absurd.
You could try how this behaves: ``cat yourfile | mpv -``.

**Comment by LennertVA** [comment]
Looks like you're onto something:

```$ cat /path/to/test.mkv | ./mpv-stream_shit/build/mpv -```

Loads the file over the wifi link at 35MB/sec (max speed). Without cat, 250-300KB/sec.

**Comment by wm4** [comment]
It still makes no sense to me. The only thing I can think of is that the new code might wait slightly longer before calling the ``read()`` syscall again, which somehow causes problems. When using a pipe, the kernel will buffer some data over the pipe (I think Linux defaults to 64KB?), which is consistent with this theory.

I maintain that this is just a bug in the cifs implementation.

**Comment by LennertVA** [comment]
But how is it that only mpv > 0.30 shows this behaviour, and zero other apps? I've been trying all kinds of different applications - video, audio, imagery, PDF - none show anything like this.

Going to do some test runs with the file on NFS instead of cifs too, just for kicks.

**Comment by wm4** [comment]
I really have no idea. I don't think mpv is doing anything special, and I specifically tried to emulate the read pattern of the previous versions with that older branch. Or maybe there's something I'm not seeing, such as mpv possibly making larger pauses or performing stream-level seeks during normal demuxing (or just something I'm not seeing).

Here's another test: https://github.com/mpv-player/mpv/compare/absurd_test
No logs needed. Run it in the normal use case. Could contain major bugs, it was quickly put together and not intended for merge. This one tries to always keep one read "in flight", don't know if it works as intended.

**Comment by LennertVA** [comment]
Well, absurd_test works fine for this test at least - cache fills at max line speed. :-)

**Comment by wm4** [comment]
Does it happen with this branch too: https://github.com/mpv-player/mpv/tree/absurd_test2

Anyway, this would confirm my suspicion. Can you report it to the developers of the filesystem driver?

**Comment by LennertVA** [comment]
Yes, absurd_test2 also works just fine. 

I just finished testing with an NFS (v3, UDP) mount to the same filesystem. All mpv builds I have (all tests from this thread, master, plus packaged versions) work fine with it. Line speed is slower (~27MB/sec instead of 35MB/sec on cifs) but that's consistent for shell access too, so probably related to using default non-optimized mount options.

What seems to be the cause then? What should I report? And can the in-flight as done in absurd_test read be applied to the master as a workaround, or would that cause other issues? Odds of getting something changed in a fundamental package like cifs (especially since it seems to be very difficult to trigger it) are pretty low. I'm wondering whether changing the mount options for cifs could make a difference too - I'll have to run a batch of tests with alternating mount options too.

**Comment by wm4** [comment]
Another test: https://github.com/mpv-player/mpv/tree/absurd_test3
(I'm reducing the concurrency on each test, maybe this is the the last one.)

Not sure whether the branches are bug free. You probably shouldn't run it for "production".

In my opinion, the problem is with the CIFS driver, because it should not be that sensitive to application timing differences on ``read()`` syscalls. This is only if my theory is correct.

**Comment by bitraid** [comment]
> I don't think I have this issue on Arch/Manjaro.

Works fine here, too. Can anyone else reproduce this?

**Comment by wm4** [comment]
Might as well be a configuration issue. Is this a kernel driver or something via FUSE?

**Comment by bitraid** [comment]
Its kernel.

**Comment by bitraid** [comment]
You can mount a cifs share that runs localy: install samba server, modify smb.conf to enable a shared directory that contains videos, start the service and mount: `mount -t cifs -o user=username //127.0.0.1/share /mnt`

**Comment by wm4** [comment]
Can anyone actually reproduce it with a local share?

**Comment by LennertVA** [comment]
absurd_test3 works too. 

It's kernel indeed. I'm wondering if it could have something to do with the (default) options that are used for the cifs mount - will try to test with different ones, and also with a local share.

**Comment by wm4** [comment]
> absurd_test3 works too.

Oh, that makes no sense to me. I assume mpv from git master is still broken?

**Comment by LennertVA** [comment]
> > absurd_test3 works too.
> 
> Oh, that makes no sense to me. I assume mpv from git master is still broken?

mpv 0.32.0-50-g18070f7405 (just refreshed and rebuilt) still shows the broken cache fill behaviour from the remote server share indeed.

But, update: local samba share **with the exact same mount options** does **not** have the issue. Could this be triggered only because of the slightly higher latency? The server here is stable at ~1.9ms, which should be plenty low.

**Comment by bitraid** [comment]
If you have access to the server and it can run mpv, try testing there (with a local mount).

**Comment by LennertVA** [comment]
> If you have access to the server and it can run mpv, try testing there (with a local mount).

It's my server, but it's running headless (and a CentOS 7 on ARM64). I could make up some concoction with remote X11 but not sure how that would influence the test.

**Comment by bitraid** [comment]
You could just connect with ssh and run mpv with `--vo=null`.

**Comment by LennertVA** [comment]
> You could just connect with ssh and run mpv with `--vo=null`.

Mmmm. The machine doesn't have a build chain, and I would only be able to tell the effect by looking at the cache fill rate as displayed by mpv itself. I'll see what I can do.

**Comment by wm4** [comment]
Anyway, my technical analysis is as follows (if you want to report the bug to wherever):
- the git master branch is slow with mounted CIFS shares, while the absurd_test3 branch works properly
- normally, mpv reads and fills the cache as quickly as possible, however, the cache is on a higher level, so there's a minor amount of CPU time between the raw ``read()`` calls
- this CPU time is normally just things like demuxing (parsing the file); tthis may even depend on the file format being played
- the absurd_test3 branch adds a thread that starts another ``read()`` once a 64KB buffer has been fully read by the higher level (the next higher level is a byte ring buffer meant to reduce the frequency of small ``read()`` syscalls, so it's somewhat likely the whole 64KB get read)
- I conclude that it's something about the timing of the ``read()`` syscalls, and most likely performance gets ruined if there's a slight pause while the CPU processes the read data

Still doesn't make too much sense to me. And I don't see any possible fix, other than reintroducing a thread that does nothing but call ``read()`` in a loop, which would be a waste of resources since there's already a dedicated thread for demuxing.

**Comment by LennertVA** [comment]
Okay, I feel stupid for not thinking of this. I accidentally overwrote my manually-downgraded mpv 0.29 (which works fine for the all cases I've been testing with before) with the system-default 0.32, and **it actually works for many other files**. I only noticed the unwanted version bump after a while.

And then I read your "this may even depend on the file format being played".

I need to start eliminating to see what causes it to trip, but so far the files that fail are all 10bit HEVC. I've yet to find a h264 file that fails, but I also throw in a bunch of jellyfish (http://jell.yfish.us/) test files and so far even their HEVC 10bit samples work with mpv master (under reserve - haven't tried them all). The cache speeds are wildly different between them; all are sufficient, but they vary between ~4MB/sec and max line speed.

There's something in certain HEVC files that makes mpv drop its cache speed as described above. Could something in such files cause the demuxing to interfere with the reads? Further down the rabbit hole.

**Comment by LennertVA** [comment]
For info, this is the mediainfo output of the test mkv I've done all tests in this thread with:

```
Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L4.1@High
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 12 min
Bit rate                                 : 6 933 kb/s
Width                                    : 1 920 pixels
Height                                   : 800 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.188
Stream size                              : 6.39 GiB (56%)
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
```

**Comment by wm4** [comment]
The container format is probably more important than the bitrate of the files, because it determines what demuxer is used. And the codecs don't matter.

**Comment by wm4** [comment]
PS: if it's the bitrate, the --stream-force-buffer option of the old test branch may make a difference. If this option is disabled and mkv is used, read() calls may be larger and try to read entire packets. mp4 fully uses libavformat, which may be different again.

I assumed you always tested with the same file, a mkv file?

**Comment by LennertVA** [comment]
Yes, mkv, same file everywhere. Bitrate is negligible as you could see. I'll post full mediainfo output of files that trigger the ultra slow cache fill - but like I said, with mpv master, the cache fill speeds vary between files; some get a steady 4MB/sec, others 8, others 20, others 35 (and some don't get enough).

Full mediainfo of the testfile I've used everywhere:
[test_mediainfo.txt](https://github.com/mpv-player/mpv/files/4177954/test_mediainfo.txt)

**Comment by wm4** [comment]
Yeah, that's most likely because of the different read patterns.

**Comment by LennertVA** [comment]
Found two more files that trigger the problem. Both are 10bit HEVC, but 4k this time. A handful others with similar file size, resolution and bitrate do work just fine in master. All work fine in 0.29.

[test2_mediainfo.txt](https://github.com/mpv-player/mpv/files/4178154/test2_mediainfo.txt)
[test3_mediainfo.txt](https://github.com/mpv-player/mpv/files/4178155/test3_mediainfo.txt)

Can also confirm that all jellyfish samples up to 160Mbps work in master.

**Comment by wm4** [comment]
The mkv demuxer tries to read large packets at once, basically with a single read() size. This is part of why I think bitrate might matter. But --stream-force-buffer=yes should exclude this case. Could also just be that larger packets mean more CPU work and a higher delay between read() calls.

**Comment by LennertVA** [comment]
Did some checks on the failing (and working) files.
- Failing files are MKVs, version 4, written by various mkvmerge versions (v31, v33, v41). Many working files are too.
- Failing files are HEVC 10bit for video stream. Many working files are too.
- Bitrate, file size nor resolution seem to be involved. 

There is one peculiar common item between the failing files: they have Dolby TrueHD Atmos as first audio track. I've yet to find a working file that has that.

If I remux the testfile and kick out that audio track, it works. Might be a red herring, but... something with TrueHD Atmos + HEVC 10bit?

**Comment by wm4** [comment]
Hm, I see. An interesting fact about TrueHD is that it has extremely small packet sizes. The demuxer actually reassembles the packets, which makes things worse. This may really be something about high CPU usage causing "disadvantageous" timing.

Can you try to remux a single TrueHD to a mkv file (i.e. without video), and play it?

**Comment by LennertVA** [comment]
> Can you try to remux a single TrueHD to a mkv file (i.e. without video), and play it?

Just did it, and can confirm that just the audio track also gets only 200KB/sec (and thus, lags, since the stream is ~5Mbps).

**Comment by wm4** [comment]
Made another test branch, just for retrieving debugging infos: https://github.com/mpv-player/mpv/tree/stream_debug_stuff
Can you run this with the audio only file, and use ``--dump-stats=/tmp/log.txt`` and post the resulting file?

**Comment by LennertVA** [comment]
Done!
[mpv-stream_debug_stuff.log](https://github.com/mpv-player/mpv/files/4195726/mpv-stream_debug_stuff.log)

Much appreciated that you're putting in so much effort to track this down, by the way.

**Comment by wm4** [comment]
From the log, it seems like it mostly does nothing. I assume the cache was actually enabled?
Can you upload the audio file?

> Much appreciated that you're putting in so much effort to track this down, by the way.

That's because you're going through with every test I request.

**Comment by LennertVA** [comment]
> From the log, it seems like it mostly does nothing. I assume the cache was actually enabled?

I would think so - I went with standard options, so that seems to be using 128k for buffer. Retried with 512k, didn't make a difference. The --stream-force-buffer option isn't present in this branch, correct? If I should re-test with different options, let me know.


>  Can you upload the audio file?

I've cut the audio-only files to 30 seconds, should be plenty to test with (the full audio-only file is multiple gigabytes). Tested and confirmed to have the same behaviour as the "full" file. 

[test_onlyatmos_short.zip](https://github.com/mpv-player/mpv/files/4203378/test_onlyatmos_short.zip)

**Comment by wm4** [comment]
It seems to spend a lot of time on CPU. With a bitrate this low, there are only about 8 read calls per second of audio (and packets are unusually small and high in number because TrueHD is stupid), so it's somewhat clear that there's a lot of demuxer overhead. A lot of that is probably just memory allocation. Still, that means it spend ~1ms between read calls to parse the file, even in the completely local build. (With an unoptimized ubsan-enabled debug build though.)

Also in the profiler there are frequent calls to lseek, which is used to query the file size. Maybe this happens a little too often; definitely not a problem but I changed it slightly in git master. Still would be hilarious that the seek (the only way to determine file size) somehow interacted with CIFS's read-ahead logic.

Other than that, I conclude that CIFS has bad or no read-ahead/prefetching for linear reads.

**Comment by LennertVA** [comment]
Mhmmm. I don't know about the cifs read-ahead - I believe by default it is (or was?) 16KB, but who knows (haven't looked at the internals since samba 3, and we're already at 4.something ...).

Current master (0.32.0-97-g7d11eda72e) gets 16-22MB/sec for the test files used before. Awesome!

**Comment by wm4** [comment]
> Current master (0.32.0-97-g7d11eda72e) gets 16-22MB/sec for the test files used before. Awesome!

Eh, really? Maybe it really was the seek call, that is used to check the file size.  Didn't really expect it, though towards the end that seemed more and more like a possibility. Maybe I should consider using fstat() for the file size...

Can you try this branch: https://github.com/mpv-player/mpv/compare/stream_no_size_caching
It's just master with size caching disabled.

So if it's this, then that would mean read-ahead is disturbed on seeks (even if there are no non-linear reads), or the seek calls trigger additional network traffic.

**Comment by LennertVA** [comment]
The stream_no_size_caching branch does not work (still ~200KB/sec), and spews a new warning (I suppose you added this specifically):

```AV: 00:00:00 / 02:12:00 (0%) A-V:  0.000 Cache: 0.0s
Audio device underrun detected.
AV: 00:00:00 / 02:12:00 (0%) A-V:  0.000 Cache: 0.0s
Audio device underrun detected.
AV: 00:00:00 / 02:12:00 (0%) A-V:  0.000 Cache: 0.0s
Audio device underrun detected.
AV: 00:00:00 / 02:12:00 (0%) A-V:  0.000 Dropped: 1 Cache: 0.0s
Audio device underrun detected.
AV: 00:00:00 / 02:12:00 (0%) A-V:  0.000 Dropped: 1 Cache: 0.0s
Audio device underrun detected.
AV: 00:00:01 / 02:12:00 (0%) A-V:  0.000 Dropped: 1 Cache: 0.0s
Audio device underrun detected.
AV: 00:00:01 / 02:12:00 (0%) A-V:  0.000 Dropped: 1 Cache: 0.0s
Audio device underrun detected.
```

**Comment by wm4** [comment]
Hm I guess this confirms the theory. Hold on, I want to try something else.

**Comment by wm4** [comment]
Please try these two branches:

https://github.com/mpv-player/mpv/compare/stream_size_fstat
https://github.com/mpv-player/mpv/compare/stream_size_fstat_nocache

The audio underrun message might be new on some AOs, and happens when the audio buffer is empty when the audio device requested new data.

**Comment by LennertVA** [comment]
stream_size_fstat: max line speed - faster than anything I've seen so far, I'd say. Pushing 40MB/sec even.

**Comment by LennertVA** [comment]
stream_size_fstat_nocache: dito. I can't see any difference with the previous branch, cache-fill-speed wise. Crazy fast.

**Comment by wm4** [comment]
Very nice. I would never have thought that this is the solution. The CIFS source code even seems to have some code to deal with the common SEEK_END pattern to check the file size (but maybe I misread), so I find it pretty surprising that fstat works better. Probably will drop the file size caching, or do something similar.

Thanks for testing, I would never have found this if you hadn't tested anything I threw at you so readily. I'll push the fstat change as commit that fixes and closes this issue.

**Comment by wm4** [comment]
And done, I hope I didn't add any new bugs.

**Comment by LennertVA** [comment]
Awesome. Thanks!

**Comment by mmowchenko** [comment]
I've been following this since the beginning and just wanted to say thank you for resolving this!

**Comment by nshtg** [comment]
Thank you for hunting down and fixing this bug! I encountered this too on Arch mounting a SMB share using CIFS.
