### ISSUE TITLE
'add aspect' no longer works

### ISSUE THREAD

**Issue by inca-viewer** [mpv-player/mpv#7409]
latest mpv version 26th jan 2020
latest windows 10
mpv-x86_64-20200126-git-ae0520c binary

was using mpv version from 07-04-19
updated to current 26-01-20

5 add aspect -0.01
6 add aspect 0.01
no longer works

this is my input.conf file contents

MOUSE_BTN3 ignore
MOUSE_BTN4 ignore
AXIS_UP ignore
AXIS_DOWN ignore
F11 cycle fullscreen

= run "cmd.exe" "/d" "/c" "echo ${playback-time}/${duration}/${core-idle}/${playlist-pos}/${estimated-frame-number}/${estimated-frame-count}|clip"   # pass to clipbaord
1 set pause no
2 set pause yes
3 set mute no
4 set mute yes		               # rem adding Shift key to most options causes instability
5 add aspect -0.01
6 add aspect 0.01
7 af set rubberband=pitch-scale=1.04
8 af set rubberband=pitch-scale=1
9 add video-zoom -0.04
0 add video-zoom 0.04
a multiply speed 0.99
b multiply speed 1.01

e seek  0.5
f seek -0.5
g add video-pan-y 0.004
h add video-pan-y -0.004

k set osc yes ; set cursor-autohide no
l add video-zoom -0.005

**Comment by Akemi** [comment]
`video-aspect-override`

see https://github.com/mpv-player/mpv/commit/cb95ce75b5c114b6fd2c6b37ac6941b6848c8014

**Comment by Akemi** [comment]
both of them work for me
```
X add video-aspect-override 0.01
X add video-aspect 0.01
```

the former only works correctly when `video-aspect-override` was previously set properly since it start at `-1`.

**Comment by inca-viewer** [comment]
Thank you, that fixed everything

Keith
