### ISSUE TITLE
Next spoken subtitle broken on MPV 0.31+ (CTRL+SHIFT+LEFT/RIGHT ARROW)

### ISSUE THREAD

**Issue by j0sk** [mpv-player/mpv#7413]
### Important Information

- mpv version: **0.31, 0.32**
- Linux Distribution and Version: **Debian Testing** / **Also tested on oSX, broken there as well**
- Source of the mpv binary: **Debian Multimedia Testing repository 0.31 / Debian SID repository 0.32** / **On oSX installed via https://laboratory.stolendata.net/~djinn/mpv_osx/**
- If known which version of mpv introduced the problem: **Started with 0.31**
- Window Manager and version **KDE**
- GPU driver and version **INTEL HD**
- Possible screenshot or video of visual glitches : **I will provide test files**

### Reproduction steps

Download following test files (original source of files: https://mkvtoolnix.download/samples/)
[test.mkv](https://mega.nz/#!qnozCCqY!Zx9v2eWlZ3GlQZrLh4GxsGbIyO1_8YXiC8o-zFRcOIo) 
[test.srt](https://mega.nz/#!n7gVwK5L!-h2M2xDLbJRrZ2_1Jgv0lszjdUWq9IVgbu43fBled5o)

Open MKV file with MPV 0.31 or 0.32 and press CTRL+SHIFT+LEFT/RIGHT ARROW to view next or previous subtitle line. Only thing you can see is the OSD: SUBDELAY: xxxxx MS message but you cannot see the next spoken subtitle line same time as you press that CTRL+SHIFT+ARROW RIGHT key combination. The subtitle timing cannot be done anymore as this doesn't work like it should be. This same problem exist at least on Linux and osX.

### Expected behavior

Open MKV file with MPV 0.30 and press CTRL+SHIFT+LEFT/RIGHT ARROW and you see right away next or previous subtitle line and you can correct the timing. Also the OSD shows the SUBDELAY xxxxx MS message.

### Actual behavior

Only OSD message SUBDELAY xxxxxx MS is viewed but you cannot anymore view subtitle line same time as you press the CTRL+SHIFT+LEFT/RIGHT ARROW key combination.

### Log file

[output.txt](https://mega.nz/#!yu5X3YhA!ZEVW6SeSVwpGd-QeAAG0PNEZgnhZTbkNm8d0Blu0Rjg)

On the log you can see that I have pressed CTRL+SHIFT+ARROW LEFT/RIGHT

[   4.350][d][cplayer] Run command: sub-step, flags=73, args=[-1]
[   4.517][d][cplayer] Run command: sub-step, flags=73, args=[-1]
[   4.725][d][cplayer] Run command: sub-step, flags=73, args=[-1]

### Sample files

[test.mkv](https://mega.nz/#!qnozCCqY!Zx9v2eWlZ3GlQZrLh4GxsGbIyO1_8YXiC8o-zFRcOIo) 
[test.srt](https://mega.nz/#!n7gVwK5L!-h2M2xDLbJRrZ2_1Jgv0lszjdUWq9IVgbu43fBled5o)

**Comment by Akemi** [comment]
i dunno what you tested. i can reproduce it with 0.31 but not with 0.32. https://github.com/mpv-player/mpv/commit/d26b5daf3ed32136540d39614afe7ef631a1319f this commit fixed the issue.

**Comment by j0sk** [comment]
> i dunno what you tested. i can reproduce it with 0.31 but not with 0.32. [d26b5da](https://github.com/mpv-player/mpv/commit/d26b5daf3ed32136540d39614afe7ef631a1319f) this commit fixed the issue.
> 
> [edit]
> btw your linux log is with mpv 0.31 not 0.32

I reinstalled mpv 0.32 and now it worked with that. Thank you for helping me.

**Comment by lazaronixon** [comment]
https://github.com/mpv-player/mpv/issues/7411#issuecomment-917551170
