### ISSUE TITLE
showing problem with WINDOWS-1255 encoded Hebrew subtitles

### ISSUE THREAD

**Issue by yoelion** [mpv-player/mpv#7415]
### Important Information

Provide following Information:
- mpv version
0.32
- Linux Distribution and Version
updated archlinux

Since 0.31 [and 0.30 too maybe] mpv can't recoding non-UTF8 Hebrew subtitles. This show in Gibbirish

```
mpv file.mp4 
[lavf] Using subtitle charset: WINDOWS-1255
[lavf] Error recoding text with codepage 'WINDOWS-1255'
[lavf] Using subtitle charset: WINDOWS-1255
[lavf] Error recoding text with codepage 'WINDOWS-1255'
```

also `sub-codepage=hebrew` doesn't work

**Comment by CounterPillow** [comment]
Please provide sample files and a full log file generated with `--log-file=file.log`.

**Comment by yoelion** [comment]
Sorry. this was wrong srt file
