### ISSUE TITLE
contacts

### ISSUE THREAD

**Issue by 1223745302** [mpv-player/mpv#7419]
Hello, the developer of MPV, I come from a wechat group that gathers a lot of front-line staff in the film and television industry. There are film and television colorists, photographers, lighters, etc. in the group, I'd like to invite you to our group to exchange, such as HDR.
MPV 的开发者你好，我来自一个聚集了很多影视行业一线工作人员的微信群，群里有影视调色师、摄影师、灯光师等，我先邀请您到我们的群来交流，比如交流HDR

**Comment by wm4** [comment]
You can report bugs/ask questions on this issue tracker, or talk on IRC, but I don't think anyone of us will appear on wechat.

**Comment by laichiaheng** [comment]
@1223745302 路過請教一下，市面上的 HDR 電視在 SDR 模式下能夠啟用到電視的最大峰值亮度與廣色域嗎？如果不行，那麼 mpv tone-mapping 後的 SDR 訊號輸出豈不是會對畫質產生負面影響？
