### ISSUE TITLE
ytdl_hook should respect youtube-dl's config file

### ISSUE THREAD

**Issue by rndusr** [mpv-player/mpv#7422]
I have this line in my `~/.config/youtube-dl/config`:

    --format bestvideo[height<=720][vcodec!*=av01]+bestaudio/bestvideo[height<=1080][vcodec!*=av01]+bestaudio/best[height<=720][vcodec!*=av01]/best[height<=1080][vcodec!*=av01]/best

It should pick a non-av01 video if possible. If I run `youtube-dl <YouTube URL>`, this works as expected. But if I run `mpv <YouTube URL> --msg-level ytdl_hook=trace`, I can see that `youtube-dl` is called with `--format bestvideo+bestaudio/best`.

1. According to the man page, `bestvideo+bestaudio/best` is already the default: "Since the end of April 2015 and version 2015.04.26, youtube-dl uses -f bestvideo+bestaudio/best as the default format selection (see #5447 (https://github.com/ytdl-org/youtube-dl/issues/5447), #5456 (https://github.com/ytdl-org/youtube-dl/issues/5456))."

2. ytdl_hook should respect my preferences.

It also enforces `--sub-format ass/srt/best` and `--all-subs`, which I would leave to the user to configure.

I could fix this by adding `ytdl-raw-options ...` to my `~/.config/mpv/mpv.conf`, but then I'd have to maintain the same settings in two different files.

**Comment by wiiaboo** [comment]
It could be argued that you might not want the same settings to download videos as well as streaming them.

We would need to stop setting a default format, since we're for sure not going to check if youtube-dl.conf exists and has a `format` line, as the path for it changes for all platforms, or even doing `youtube-dl` and parsing the debug output.

Other than `format` ytdl_hook respects your youtube-dl.conf as it's directly calling `youtube-dl` without `--ignore-config`. We just need to set format to set some sane defaults.

At most I'd agree with a way to prevent ytdl_hook from setting those defaults if `--ytdl-format` is also unset.

**Comment by rndusr** [comment]
You are making good points. I haven't thought about people using different formats for downloading vs streaming.

I guess there is no scenario in which nobody has to have special settings for mpv. That's probably why --ytdl-format exists.

ytdl_hook.lua already seems to not set youtube-dl's --format option if --ytdl-format is given, but it doesn't work for me:

    $ mpv --ytdl-format='video[height<=360]' 'https://www.youtube.com/watch?v=y-fLkdVRMwE'

mpv should fail like youtube-dl does:

    $ youtube-dl --format 'video[height<=360]' 'https://www.youtube.com/watch?v=y-fLkdVRMwE'
    [...] requested format not available

But it plays the video in 720p instead.


Also, one tiny nitpick: The man page says for --ytdl-format:

    Default: youtube-dl's default, currently bestvideo+bestaudio/best

That's practically true, but technically wrong because "bestvideo+bestaudio/best" is hardcoded in ytdl_hook.lua.

**Comment by wiiaboo** [comment]
Yes, it's **copied** from youtube-dl's default, not actually using youtube-dl's default.

**Comment by wiiaboo** [comment]
> mpv should fail like youtube-dl does: $ youtube-dl --format 'video[height<=360]' 'https://www.youtube.com/watch?v=y-fLkdVRMwE' [...] requested format not available

If you use a bad format value, ytdl's `-J` still returns all the formats and defaults to 'bestvideo+bestaudio/best` for the `requested_url` or `requested_formats` key. That's youtube-dl's intended behavior of `-J`, not an issue in ytdl_hook or youtube-dl.

**Comment by wm4** [comment]
There were also some cases mpv couldn't handle, while youtube-dl could (since youtube-dl has its own code for dash etc.).

**Comment by rndusr** [comment]
Oops, I was wrong about the --ytdl-format.
Forgot I still had ytdl-raw-options set in my mpv.conf.

I guess this can be closed now.

**Comment by sergeykish** [comment]
Release 0.33.0 adds

    --ytdl-format=ytdl

> The ``ytdl`` value does not pass a ``--format`` option to youtube-dl at all, and thus does not override its default. Note that sometimes youtube-dl returns a format that mpv cannot use, and in these cases the mpv default may work better.

https://github.com/mpv-player/mpv/commit/43c13e5ea23230edca38426d4a9eed049a70890e

This includes default format too, no `--format bestvideo+bestaudio/best`:

    $ cat .config/mpv/mpv.conf 
    ytdl-format=ytdl
    $ mpv  --msg-level=ytdl_hook=trace ...
    ...
    [ytdl_hook] Running: youtube-dl --no-warnings -J --flat-playlist --sub-format ass/srt/best --all-subs --no-playlist -- ...



Thank you!
