### ISSUE TITLE
mpv aborts - dyld error

### ISSUE THREAD

**Issue by ghender3** [mpv-player/mpv#7423]
### Important Information

- mpv version 0.32.0
- macOS 10.13.6 High Sierra
- homebrew, brew install - no errors during installation. All dependencies installed.
 - don't know when this issue started. I am fairly certain that mpv was working on the system about a year ago

### Reproduction steps

Installed ffmpeg 4.2.2 and all its dependencies (brew install ffmpeg)

Then installed mpv (current version) and all its dependencies (brew install mpv)

Then tried to play a video. Then tried to see output of mpv --help

### Expected behavior

mpv --help , expect to see usage information

mpv /path to video - expect video to attempt to play

### Actual behavior

Following abort trap error - 

mpv --help
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /usr/local/bin/mpv
  Reason: image not found
Abort trap: 6

### Log file

mpv -v gives exactly the same dyld message as above

I did a global search of the system for libswiftAVFoundation. Found two slightly different versions - one in Library/Developer/Command Line Tools and one in System/Library/PrivateFrameworks/Swift. The one in Command Line Tools dated to 2018, the one in System/Library/PrivateFrameworks/Swift was created and modified 12/4/2019. Probably placed there by my latest security update. 

### Sample files

No sample file

**Comment by Akemi** [comment]
my guess is, you need to install https://support.apple.com/kb/DL1998?viewlocale=en_US&locale=en_US. if you installed the bottled brew version than it's their responsibility to package all the dependencies needed.

though i believe mpv doesn't depend on `libswiftAVFoundation.dylib`. can't say much without the build log.

**Comment by ghender3** [comment]
I installed the Swift 5 libraries, and they were installed in the same location as they are in Mojave. No longer in /System/PrivateFrameworks/Swift, so I had high hopes. Unfortunately, I am getting the exact same error message upon attempting to run mpv. I will probably now try brew uninstall of mpv and all dependencies, and attempt a reinstall with the Swift 5 libraries in place before I start. Very frustrating. I will also attempt to get the build log.

**Comment by Akemi** [comment]
if you just do `brew install mpv` it will use (pour) a bottle and there won't be a build or configure log sinc eit uses a pre-built binary. that's a problem with homebrew.

make sure to call `brew doctor` and fix any problems that it reports.

**Comment by ghender3** [comment]
I tried running brew doctor, and fixed everything it reported. Didn't affect my problem at all. I did do a brew install --verbose --debug of mpv, but I guess you feel that isn't especially useful. It's quite lengthy, but it probably did exactly what it did the last time, as you've said. Should I be taking this up with a forum somewhere with the Homebrew project? I'm about to throw in the towel with the CLI version of mpv. At least on High Sierra. As I said, this was all working about a year ago, but I did a clean install of High Sierra and just assumed homebrew would "do the right thing" in the future. Thanks for your help and patience.

**Comment by Akemi** [comment]
either bring it up with homebrew or install from source via `brew install --head mpv`. if the latter fails i can most likely help you you further.

you can also use homebrew cask and get a pre compiled bundle instead, which will also install/link the binary to you path.

**Comment by ghender3** [comment]
brew install --HEAD mpv installed a different build that actually works! All of the homebrew documentation I could find said --HEAD, not --head. Don't know if there is actually any difference. Build was something line 30a47.

**Comment by Akemi** [comment]
yeah i actually meant `--HEAD`. sry about that. it doesn't install a different build. like i said it will build/compile mpv from source instead of downloading an already built binary (bottle) from somewhere, which in this case is apparently broken.
