### ISSUE TITLE
mpv fails to play cue files with non-breaking spaces

### ISSUE THREAD

**Issue by elenril** [mpv-player/mpv#7429]
mpv version 0.32.0 exits with
 `[cue] error parsing input file!`
  `Failed to recognize file format.`
on trying to play a CUE playlist that uses non-breaking space (U+00A0) indentation. Sample at https://0x0.st/izgn.cue
Replacing those with plain spaces fixes playback, but still would be nice if it was playable as-is.

**Comment by wm4** [comment]
What created such terribleness?

**Comment by wm4** [comment]
What's even more terrible: while A0 is the codepoint for breaking space, this file is neither UTF-8 nor UTF-16. Yet it uses Latin1 (where NBSP is obviously encoded as A0).

**Comment by elenril** [comment]
No idea what wrote the file, I got it from http://cuenation.com/?page=tracklist&folder=upliftingonly&filename=Ori+Uplift+-+Uplifting+Only+360+%28Jan+2%2C+2020%29+%28Tune+of+the+Year+Vote+2019+-+Top+20+Countdown%29+v2.cue

**Comment by wm4** [comment]
If someone feels bored: write a scraper, and feed every file to mpv to see if it breaks.
