### ISSUE TITLE
playlist-pos no longer working

### ISSUE THREAD

**Issue by inca-viewer** [mpv-player/mpv#7430]
latest mpv version 26th jan 2020
latest windows 10
mpv-x86_64-20200126-git-ae0520c binary
was using mpv version 07-04-19
updated to current 26-01-20

this type command no longer works 
Run mpv --playlist-pos=0

Run %inca%\apps\mpv --fullscreen=no --cursor-autohide=no --osc=yes --keep-open=always  --playlist-pos=%pos% --input-ipc-server=\\.\pipe\mpv_music "%inca%\cache\lists\songlist.m3u"

**Comment by CounterPillow** [comment]
https://github.com/mpv-player/mpv/commit/e2e6bb496e615ab33b55d2218d289d969b103ae8

read the changenotes

**Comment by inca-viewer** [comment]
thank you.

**Comment by wm4** [comment]
That doesn't mean to read the entire commit log. Reading interface-changes.rst on each update, and paying attention to the log messages output by mpv at runtime is enough.
