### ISSUE TITLE
screenshot each-frame's timestamp is always wrong

### ISSUE THREAD

**Issue by pencilbook** [mpv-player/mpv#7433]
The timestamp with `%P` and `screenshot each-frame `is always wrong. It will always give you the timestamp for the frame before it. This is caused by the video player itself, and not by custom configurations related to it.

`f screenshot each-frame`
`screenshot-template='C:\1\%F\%F (%P) %n'`

Example: the timestamp for this frame should be "00_09_39.120", but it's "00_09_39.079"
https://i.imgur.com/NPKeUkO.jpg

**Comment by pencilbook** [comment]
Provide following Information:
- mpv version 0.31.0-67-g63bf362d11
- Windows Version 10

### Reproduction steps
Bind "screenshot each-frame" to something and tap the key 

### Expected behavior
Correct timestamp

### Actual behavior
The timestamp with %P and screenshot each-frame is always wrong. It will always give you the timestamp for the frame before it. This is caused by the video player itself, and not by custom configurations related to it.

f screenshot each-frame
screenshot-template='C:\1\%F\%F (%P) %n'

Example: the timestamp for this frame should be "00_09_39.120", but it's "00_09_39.079"
https://i.imgur.com/NPKeUkO.jpg

**Comment by CounterPillow** [comment]
What I really wanted was a log file, but okay.

**Comment by wm4** [comment]
The problem is that (strictly speaking) it doesn't use the frame timestamp, but the higher level playback time, which may be lagging behind. Probably.

**Comment by pencilbook** [comment]
@wm4 So it's intended for the timestamp to be a couple of seconds behind when the frame isn't? 

@CounterPillow Follow the reproduction steps then. log-file= doesn't work on shinchiro's build. Now remove the priority:ignored label.

**Comment by wm4** [comment]
No, I'd expect at most dozens of milliseconds (at normal framerates).

**Comment by garoto** [comment]
> [...] log-file= doesn't work on shinchiro's build. Now remove the priority:ignored label.

False.

**Comment by pencilbook** [comment]
@garoto I've had `log-file="K:\mpv\logs\fillet.log"` in my config for many years and it never works with his builds which is what I am using atm, so no, it's not fake news.

**Comment by garoto** [comment]
Which is more likely: that lachs0rs/shinchiro's github hosted, cross-compile build system will produce mpv binaries where the `--log-file` functionality is broken everytime for _many years_ and you are the first one to notice it **OR** that you done goofed somewhere else in your mpv setup.

**Comment by zc62** [comment]
Try `log-file="~~desktop/mpv.log"`. Probably you didn't create the directory `K:\mpv\logs` first, so mpv is unable to find that folder to write log files to.

**Comment by wm4** [comment]
> @wm4 So it's intended for the timestamp to be a couple of seconds behind when the frame isn't?

This is definitely wrong and never happened.
