### ISSUE TITLE
Drop UDP while the player is paused

### ISSUE THREAD

**Issue by niXman** [mpv-player/mpv#7434]
Hi,

Let me ask you a question.

When viewing a real-time video stream and pausing the player I want the player to not cache the video while it is paused.
But at the same time I want the player to immediately continue playing when it be unpaused.

Any ideas?

`mpv 0.28.0`

thanks!

**Comment by niXman** [comment]
the best thing I've achieved is to add the following options to the URL: `overrun_nonfatal=1&fifo_size=2000`

but I do not like this solution...

any ideas?

**Comment by wm4** [comment]
Not sure what you mean at all. You can disable the cache or set it to a very small size, then it won't be active while paused.

**Comment by niXman** [comment]
> You can disable the cache or set it to a very small size, then it won't be active while paused.

I can't because `--cache=no --cache-pause=no` has no effect, the same behavior.

**Comment by wm4** [comment]
You still see the cache growing? Anyway, there is by far not enough information about what you're doing, and I hate trying to pull it out of people's noses, so I'm closing this.
