### ISSUE TITLE
Movie title in playlist instead of URL

### ISSUE THREAD

**Issue by de-arl** [mpv-player/mpv#7438]
Hello

How can I get a playlist made by the umpv script display the movies' titles instead of the URL (see screenshot top right)?

Thanks for help
![umpv_playlist](https://user-images.githubusercontent.com/25202540/73878182-66f7e500-485a-11ea-9737-b950a8f3d993.jpg)

**Comment by wm4** [comment]
Could be done in theory, but only for playlist entries that were already opened (in the same mpv instance and playlist).

**Comment by Samillion** [comment]
This should do it, save it as a lua script ie (urltitle.lua).

```lua
local msg = require 'mp.msg'
local utils = require 'mp.utils'

local function urlOSDTitle()
	local path = mp.get_property('path', '')

	if string.match(string.lower(path), "^(%a+://)") then
		mp.set_property("osd-playing-msg", "${media-title}")
		msg.info('URL detected. Displaying media-title instead of filename.')
	else
		msg.info('Not URL, osd-playing-msg unchanged.')
	end
end

mp.register_event('start-file', urlOSDTitle)
```

**Comment by de-arl** [comment]
Hi Sam


Thanks for the script, though it does something else then what I am looking for. The script you wrote displays the title of the video for one second (top left) when jumping to next video in playlist. Still playlist entries are the URLs. It's within the playlist where I try to get the titles displayed. If you maybe know wether that can be set via property and which property therefor has to be set, your script would maybe truly work for that too. I'd be great if you knew.


Regards,

Andreas

________________________________
Von: Sam <notifications@github.com>
Gesendet: Donnerstag, 13. Februar 2020 01:20:40
An: mpv-player/mpv
Cc: Laible, Andreas; Author
Betreff: Re: [mpv-player/mpv] Movie title in playlist instead of URL (#7438)


This should do it, save it as a lua script ie (urltitle.lua).

local msg = require 'mp.msg'
local utils = require 'mp.utils'

local function urlOSDTitle()
        local path = mp.get_property('path', '')

        if string.match(string.lower(path), "^(%a+://)") then
                mp.set_property("osd-playing-msg", "${media-title}")
                msg.info('URL detected. Displaying media-title instead of filename.')
        else
                msg.info('Not URL, osd-playing-msg unchanged.')
        end
end

mp.register_event('start-file', urlOSDTitle)

**Comment by Black-Semargl** [comment]
You may add entry as
... watch?v=IkmNYijB7Ok# Retro stream White Castle 2001
text after # ignored for download

**Comment by Akemi** [comment]
closing since this was a question and it's not possible.
