### ISSUE TITLE
Audible periodic click with 1fps video

### ISSUE THREAD

**Issue by desbma** [mpv-player/mpv#7440]
- mpv version
```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.2
```
- Linux Distribution and Version

Arch Linux x64 up to date.

- Source of the mpv binary

https://www.archlinux.org/packages/community/x86_64/mpv/

### Reproduction steps

Generate a video with a low framerate (1fps in my case), with some audio, and play it with mpv.

I'm using a complex FFmpeg pipeline to generate the video, with many video filters, so I can't post the command to generate the video, but see the sample attached file.

### Expected behavior

The video should play normally.

### Actual behavior

A periodic audible "click" distortion can be heard every 1s or so.

The issue seem to disappear if the generated video has a framerate of 5.

Other players like `ffplay` do not produce this distortion. Also if I extract the audio from the video, and play it alone `mpv` does not exhibit this issue.

### Log file

https://0x0.st/iiq5.txt

### Sample files

~30s video: https://0x0.st/iiqR.mkv~

~The clicks are especially audible at the beginning.~

EDIT: A much more obvious sample: https://0x0.st/iiaq.mkv

Thanks

**Comment by wm4** [comment]
I don't hear any clicks, but this sample is pretty bad for demonstrating introduced audio distortion issues.

**Comment by desbma** [comment]
Yup, I'll try to find a quieter audio.

**Comment by desbma** [comment]
I tried generating audio with `anoisesrc` or `anullsrc` and the clicks are not audible, so it might be related to the fact that the original audio is already clipping.

**Comment by desbma** [comment]
There you go, a quieter sample: https://0x0.st/iibN.mkv

The clicks are very audible between 1:10 and 1:20 when the big guitar chord fades out.

**Comment by wm4** [comment]
Still no. Maybe you can try to record the pulse audio output or so, then we know whether I just don't hear them or if they don't happen here.

**Comment by wm4** [comment]
Everyone on IRC agrees that it's impossible to tell whether any supposed click is due to the music (which sounds highly distorted in the first place) or an audio artifact introduced during playback. This bug report might as well be a troll.

I suggest you make the same test with an audio file that's a regular sine wave.

**Comment by desbma** [comment]
I tried reproducing the issue with artificial sounds, but failed.

I think the issue only occurs when the original audio has clipping, and makes it worse with periodic clicks.

I'm well aware the audio is very distorted, but its still bug, made obvious by the fact that `mpv` plays the audio fine without the video, or with a higher frame rate.

I'll try to generate a sine wave, and add a ton of gain to make it clip and reproduce the issue.

**Comment by wm4** [comment]
Are you sure it's not caused by some sort of resampling? Maybe pusleaudio resamples when audio arrives too late or whatever. mpv in your case and judging by the log shouldn't apply dynamic resampling though. (But it does insert a "resampler" that reinterleaves audio and might do something to it.)

**Comment by desbma** [comment]
Here is a sample with a 440 Hz sine wave : https://0x0.st/iiaq.mkv

The clicks are very obvious every second, they feel almost as loud as the sine. If you don't hear it, then your system has definitely not the issue.

**Comment by Dudemanguy** [comment]
I can't hear it here. I only use ALSA on this machine though. Possibly pulseaudio?

**Comment by wm4** [comment]
I also hear nothing, but I also use ALSA only.

**Comment by Dudemanguy** [comment]
Just tried it on my laptop with pulse and I still don't hear it.

**Comment by haasn** [comment]
Can't reproduce with `-ao jack` or `-ao pulse` on my end. Can you record it somehow? (e.g. with `parecord` on the monitor, or something)

**Comment by desbma** [comment]
Here is a recorded sound of my audio (made with `ffmpeg -i alsa ...`), playing the previous sine sample file: https://0x0.st/iijb.flac

**Comment by wm4** [comment]
A bit subtle, but I can hear them. Definitely wouldn't hear them on your original sample.
Still not sure what would cause this. Maybe you can try setting larger audio buffers.

**Comment by haasn** [comment]
Yeah that's extremely obvious to me and I would definitely hear that if it happened on my end, no matter the sample.

Does it still happen if you stop pulse and use `-ao alsa` direclty?

**Comment by desbma** [comment]
> Does it still happen if you stop pulse and use -ao alsa direclty?

No more clicks at all with `-ao alsa`.

I don't know anything at all about the mpv internals, but how is that related to the video frame rate?

**Comment by desbma** [comment]
`--profile=low-latency` also makes the issues go away, so I tried all the options listed by `mpv --show-profile=low-latency` and the winner is: `--vd-lavc-threads=1`.

Using that option alone fixes this issue.

**Comment by wm4** [comment]
In this case, audio isn't changed in any way, and it should play as if there was no video track. Video decoding blocks the same thread that decodes audio though, so if video somehow takes too long, the audio buffer could underflow and cause a click artifact. Normally, video decoding is buffered by threading, so it rarely happens that video decoding blocks the main thread for a longer time. Why disabling threads improves this, I have no idea. It shouldn't.

Like I suggested before, try a larger audio buffer.

**Comment by desbma** [comment]
The issue is unaffected by `--audio-buffer=10`.

**Comment by wm4** [comment]
There's also --pulse-buffer, and maybe options on the pulseaudio side.

**Comment by desbma** [comment]
- `--pulse-buffer=10` => still clicks
- `pavucontrol` open => still clicks
- `-vo=null` => still clicks

**Comment by avih** [comment]
If these are underruns, shouldn't the log have some evidence of it? but AFAICT the log doesn't show underruns...

**Comment by desbma** [comment]
To summarize:

Reproducible with:
* 1fps video + audio
* `--audio-buffer=10`
* `--pulse-buffer=10`
* `pavucontrol` open
* `-vo=null`

Not reproducible with:
* 5 fps video
* audio only
* `-ao alsa`
* `--vd-lavc-threads=1`

Thank you all for you help and time so far.

**Comment by wm4** [comment]
Try: --pulse-buffer=1000

**Comment by desbma** [comment]
Still clicking with ` --pulse-buffer=1000`.

**Comment by mc4man** [comment]
I've pulse and the current sample in 1st post shows this clearly, a little 'bop' every second or so. 
As I keep all builds I upload to ppa it was easy to see this was a fairly recent thing in mpv.
This is commit that 1st shows this behaviour.
https://github.com/mpv-player/mpv/commit/9efdb0368eaed754f690dc61cb5d8592d3438830

**Comment by wm4** [comment]
Does ``--cache-pause=no`` help?

**Comment by mc4man** [comment]
--cache-pause=no works fine here on the sample file, no click, bop or whatever.

**Comment by desbma** [comment]
Same here, `--cache-pause=no` is another option that makes the symptoms disappear.

**Comment by wm4** [comment]
Should have been obvious with log messages like this:
```
[   9.249][v][cplayer] End buffering (waited 0.001132 secs) [1.000000s].
```
If a new frame comes, video is suddenly awfully behind. Low framerate means high frame durations, so when the new frame is finally displayed, it needs to get another one, and needs to go through a lot of audio packets. Basically the cache jumps to 0 and it needs to refill the cache. This is detected as cache underflow. But there's actually no problem, and the cache refills very quickly, without causing underruns in audio or video output. So playback is paused because of the underflow, but then immediately unpaused. ao_alsa does not have the problem, because it reports underflows on the level of the output, while ao_pulse does not.

**Comment by wm4** [comment]
Please retest with git master.

@mc4man thanks for the hint.

**Comment by mc4man** [comment]
That fixes here

**Comment by desbma** [comment]
Same here, it's fixed on git master branch.

Thank you all for looking into this.
