### ISSUE TITLE
wayland: 'add video rotate' problems with 'autofit' or 'autofit-larger'

### ISSUE THREAD

**Issue by bitraid** [mpv-player/mpv#7441]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.32.0-26-g2aaf531720 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Thu Feb  6 18:30:52 EET 2020
ffmpeg library versions:
   libavutil       56.39.100
   libavcodec      58.67.101
   libavformat     58.37.100
   libswscale      5.6.100
   libavfilter     7.74.100
   libswresample   3.6.100
ffmpeg version: N-96645-g31d7b17c46
```
- Linux Distribution and Version
`ArchLinux 5.5.2-arch1-1`
- Source of the mpv binary
`Built from git-master`
- If known which version of mpv introduced the problem
`No`
- Window Manager and version
`sway version 1.4-46561fc9 (Feb  6 2020, branch 'master')`
- GPU driver and version
`i915 KMS`

### Reproduction steps

This only happens when mpv is running as a floating wayland window, and the `add video-rotate` command is given when `autofit` or `autofit-larger` is set:
- Play a video/picrure: `mpv --no-config --image-display-duration=inf --autofit-larger=90% /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_2048x1536.png
`
-Open mpv console (<kbd>~</kbd>) and give: `add video-rotate 90`
### Expected behavior
The video should rotate.
### Actual behavior
The window doesn't rotate, and stops updating its contents. Switching to fullscreen, the video plays ok, with the rotation applied.
### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/4166997/mpv.log)

**Comment by Dudemanguy** [comment]
Interestingly enough, this only happens in opengl not vulkan.
