### ISSUE TITLE
Disable "donation" of cache size

### ISSUE THREAD

**Issue by Jeeaaasus** [mpv-player/mpv#7442]
Is it possible to disable this feature?
>--demuxer-max-back-bytes=`<bytesize>`
..
If the end of the file is reached, the remaining unused forward buffer space is "donated" to the backbuffer ..

Basically when watching streams through streamlink right now it's possible to forward cache 1GiB but it's not possible to also back cache 100MiB and only 100MiB.

I want to set `--demuxer-max-back-bytes` to a value and have it always be that value regardless of the forward buffer.

**Comment by wm4** [comment]
Is there any specific reason why you think this "donation" is bad? Normally it will reduce the backbuffer as soon as the forward buffer grows.

**Comment by Jeeaaasus** [comment]
I don't think the feature is bad, but there are instances when you might want to disable it. But that is no possible right now, correct?

My use case for when I want to disable it is:

When watching a live stream, it's nice to have the back buffer to be able to rewind a bit, 
and it's nice to be able to pause and then later have the forward buffer to be able to continue watching.

But right now to be able to forward buffer any decent amount (let's say 5GiB) you must **also** back buffer that amount, which means mpv is always using 5GiB (in back buffer) even though I only really want it to use that memory when paused and forward buffering.

Am I making sense?

**Comment by wm4** [comment]
When I added this, the idea was that mpv would use that much memory anyway. The "donating" would actually prevent that you have to set the caching too high, so you can keep the whole thing bounded, and the player wouldn't have to discard data even though it's below the maximum.
Anyway, at most I could add a new option that would control this.

**Comment by haasn** [comment]
If only operating systems had some kind of way to "opportunistically" use memory that could get automatically freed up for higher-priority use by other applications when memory pressure gets too high..

**Comment by wm4** [comment]
Android has been messing around with this for at least a decade. Is there nothing upstream yet?

**Comment by Jeeaaasus** [comment]
@wm4 I would love the option to disable the "donation" feature. 👍
