### ISSUE TITLE
Navigation controls big

### ISSUE THREAD

**Issue by dougg0k** [mpv-player/mpv#7444]
Hello,

I am having issues with the navigation controls in mpv, they are big and out of place. Check screenshot.

Any ideas on why?

- mpv 0.30
- Ubuntu 19.10

![](https://i.postimg.cc/jscQgR2c/Screenshot-from-2020-02-07-09-31-19.png)

Thanks!

**Comment by dougg0k** [comment]
I just checked something I did yesterday to fix emoji fonts in Chrome, since I was getting blank boxes in many websites, it seems that fix was the cause for breaking the controls in mpv.

What I did was create a file called **01-emoji.conf** at **~/.config/fontconfig/conf.d** with the content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <alias>
    <family>serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
  <alias>
    <family>monospace</family>
    <prefer>
      <family>Noto Color Emoji</family>
    </prefer>
  </alias>
</fontconfig>
```
And rebuild the font cache with **fc-cache -f**

**Comment by CounterPillow** [comment]
Usually trying to install emoji fonts like this replacing all font types with an emoji font will lead to breakage, yes. You'd also get wrong fonts in subtitles and so forth. It's just not a good idea to do this.

**Comment by CounterPillow** [comment]
Just to add some clarification: Missing glyphs should be pulled from fallback fonts anyway, so there is no need to force your emoji fonts to be used through fontconfig. Just have them installed without the fontconfig part and missing glyphs should be pulled from them as needed.

Also, update your mpv you're two versions behind.

**Comment by dougg0k** [comment]
They are installed, yet, it was broken in Chrome 80 for whatever reason. I will find a common ground  for both.

I am using the latest version in Ubuntu 19.10.

https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests apt still have 0.30 for eoan.

**Comment by dougg0k** [comment]
Just tried something and worked, I have selected the emoji font directly in chrome and removed the font config file and everything is working.

**Comment by CounterPillow** [comment]
>I am using the latest version in Ubuntu 19.10.

We have no influence over what is packaged by Ubuntu, just because it's the latest Ubuntu ships doesn't mean we support it because currently it is not the latest that we released.

**Comment by dougg0k** [comment]
Surely. I was saying due to be using the ppa.
