### ISSUE TITLE
0.32.0 no longer works on macOS with --disable-swift

### ISSUE THREAD

**Issue by Midar** [mpv-player/mpv#7449]
### Important Information

Provide following Information:
- mpv version: 0.32.0
- macOS Version: 10.15.3
- Source of the mpv binary or bundle: Built from pkgsrc
- If known which version of mpv introduced the problem: 0.32.0
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

Try to play any video file.

### Expected behavior

mpv shows a window and plays a file.

### Actual behavior

```
 (+) Video --vid=1 (*) (vp9 2560x1440 60.000fps)
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)
Assertion failed: (group_index >= 0), function m_config_cache_alloc_internal, file ../options/m_config.c, line 1461.
```

### Log file

http://ix.io/2b9z

In the case of a crash please provide the macOS Crash Report (Backtrace).

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Midar** [comment]
When using --vo=tct, it does work.

However, --vo=gpu shows the error above.
--vo=sdl gives:
```
Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1894.30.142/AppKit.subproj/NSView.m, line 13568.
```

And libmpv gives:
```
[vo/libmpv] No render context set.
Error opening/initializing the selected video_out (--vo) device.
Video: no video
```

Resulting on zero usable video outputs on macOS.

**Comment by Midar** [comment]
It seems that building without --disable-swift makes it work, so it seems the ObjC code is broken.

Is the ObjC version still being maintained, or should it just be removed?

**Comment by jeeb** [comment]
It has been brought up that the cocoa context is no longer anyone's favourite, so I expect that unless someone comes up as a maintainer, it is going to get progressively first deprecated and then removed.

**Comment by Midar** [comment]
Ok, I'll see then to move pkgsrc off of --disable-swift (it was added because the Swift one would not build for a while due to Swift breaking backwards compat)

**Comment by Akemi** [comment]
the cocoa gpu backend is deprecated since quite a while already and it also warns about it. though hat assertion shouldn't happen and also doesn't on my end on master.

the swift backend (cocoa-cb) is what should be used and is actively maintained.

**Comment by dardo82** [comment]
I have the same issue with macports,
I have submitted a ticket to them here:
https://trac.macports.org/ticket/60518
