### ISSUE TITLE
getting seg fault while using lavfi-complex

### ISSUE THREAD

**Issue by phkarmur** [mpv-player/mpv#7452]
when i use lavfi-complex, mpv getting segmentation fault error while closing. I have tested this in cli, c plugin and libmpv and was getting same error. (i was getting access violation error in gdb)

And I think, I was getting this error because of these two talloc_free() calls:
[https://github.com/mpv-player/mpv/blob/master/player/loadfile.c#L1150](url)
[https://github.com/mpv-player/mpv/blob/master/player/loadfile.c#L1647](url)

Because these variables (pointers) weren't allocated using talloc so I commented out both and it seems working fine after these.
But still, im not sure if its correct solution or not!

**Comment by wm4** [comment]
These free calls seem to be correct, even if admittedly unintuitive.
Please post a simple reproduction of this bug.

**Comment by phkarmur** [comment]
command and log: https://pastebin.com/chumYi5a
c plugin code: https://pastebin.com/YP4ZwxzX

**Comment by wm4** [comment]
I ran the command line in your first link (with udp replaced by a local file), and it doesn't seem to crahs in any situation.

**Comment by phkarmur** [comment]
what about when you quit (ctrl+c) mpv? because normally i am not getting any error, i am getting error when i close mpv
and i have developed c plugin to quit mpv when it find sync loss in udp stream so you can try that too

**Comment by wm4** [comment]
I tried both quitting during playback, and normal EOF.

Maybe you should try to update both mpv and ffmpeg.

**Comment by phkarmur** [comment]
mpv is latest, may be i need to update ffmpeg 
but anyway above solution fixes my issue so im gonna close this issue.

Thank you.

**Comment by wm4** [comment]
Commenting the talloc_free calls just skips deinitialization of the filter.
