### ISSUE TITLE
mpv.conf stopped working - unparseable extra characters

### ISSUE THREAD

**Issue by sheddup** [mpv-player/mpv#7453]
### Important Information

Provide following Information:
0.32.0 - mpv version
Win10 1909 - Windows Version
[Source of the mpv binary](https://sourceforge.net/projects/mpv-player-windows/files/stable/mpv-0.32.0-x86_64.7z/download) 
If known which version of mpv introduced the problem - Unknown, tried year old mpv version but didn't fix the issue
- ![a](https://user-images.githubusercontent.com/5480335/74152003-1b2dad00-4c59-11ea-9a54-fd8427c66c6f.png)

### Expected behavior
mpv parses config command `r cycle-values video-rotate 0 90 180 270` with no errors which then lets me rotate the player window with a hotkey
### Actual behavior
mpv can't parse the config resulting in this error and the inability to rotate with a hotkey `mpv.conf:1: unparseable extra characters: 'cycle-values video-rotate 0 90 180 270'`
### Log file
[output.txt](https://github.com/mpv-player/mpv/files/4180902/output.txt)

**Comment by avih** [comment]
It didn't stopped working, it never worked. The line `r cycle values...` belongs at `input.conf` and not at `mpv.conf`.

**Comment by avih** [comment]
@sheddup next time please don't delete your original post. It's possible others would have the same "issue" and can benefit from reading the description and solution.
