### ISSUE TITLE
Change video speed during the playback without action keys

### ISSUE THREAD

**Issue by fitipe** [mpv-player/mpv#7454]
Hi there!

I'm looking for a way to change the playback speed, while the video is already been played, based on incoming information from a sensor. So, unfortunately, neither the option --speed nor the keyboard controls will work for this.

Is there a way to do so? I'm quite new to programing .... x.x

In the actual project, I'll be using a raspberrypi and a distance sensor, but now I'm on win10 with a python code generating random values ( to simulate the sensor ) for testing purposes.

Thanks a lot!

**Comment by Akemi** [comment]
you can send arbitrary command to mpv via the json ipc https://github.com/mpv-player/mpv/blob/master/DOCS/man/ipc.rst

**Comment by CounterPillow** [comment]
Yes, you can set the `speed` property using the [JSON IPC](https://mpv.io/manual/master/#json-ipc).

**Comment by fitipe** [comment]
Thanks!
I'll check that out
