### ISSUE TITLE
How to resize the on-screen display?

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#7459]
![Untitled](https://user-images.githubusercontent.com/14923168/74497967-c6539600-4ee7-11ea-833b-e8bc1e78c3c9.png)

I would prefer scaling down to 1/2 or 1/3 of the current size. I haven't found the variable in [ the manual](https://mpv.io/manual/master/).

**Comment by CounterPillow** [comment]
`osd-font-size`, `osd-bar-w` and `osd-bar-h`. You can find them documented in the page you linked.

**Comment by 07416** [comment]
It should be noted that osd-scale doesn't affect the progress bar (I don't if there are other OSD elements aside from the timer).
