### ISSUE TITLE
Adjust contrast/brightness in linear color space

### ISSUE THREAD

**Issue by y-fujii** [mpv-player/mpv#7462]
In my understanding, mpv adjusts contrast/brightness in non-linear color space by default.
`--linear-*scaling` does not change this behavior.

For example, `mpv --brightness=50 --contrast=-50` gives the same results as using this shader:
```
//!HOOK MAIN
//!BIND HOOKED
vec4 hook() {
	vec4 v = HOOKED_tex(HOOKED_pos);
	return 0.5 + 0.5 * v;
}
```
but I cannot find the way to get the same result as `//!HOOK LINEAR`.
It there any way to do it in linear color space without a custom shader?

**Comment by wm4** [comment]
If you're asking about the current situation, I don't think so. Though I don't know how it's even supposed to work.

**Comment by y-fujii** [comment]
Thank you for your answer.
