### ISSUE TITLE
possible to implement auto copyback for yadif with nvdec?

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#7465]
No bug report, more a feature request: Since the AMD driver was so bad with VAAPI deinterlacing, @wm4 implemented an auto copyback feature when `--deinterlacing` is triggered with `--hwdec=vaapi`.

Would it be possible to do the same for nvdec? @philipl implemented a cuda filter for ffmpeg, but afaik you need to build ffmpeg with full cuda build environment and under a proprietary license. Current situation is that deinterlacing fails when triggering `--deinterlacing` with `--hwdec=nvdec`.

**Comment by wm4** [comment]
Should be possible.

**Comment by wm4** [comment]
Don't know if it works, but if nvdec-copy works, there's no reason why it wouldn't.

**Comment by aufkrawall** [comment]
Uh, it seems it doesn't try further after it doesn't find yadif_cuda?

```
[lavfi] filter 'yadif_cuda' not found or failed to allocate
[deint] Creating filter 'yadif_cuda' failed.
[deint] creating deinterlacer failed
[autoconvert] HW-downloading from cuda
Disabling filter userdeint because it has failed.
```
Normal yadif works with nvdec-copy.

**Comment by philipl** [comment]
Note that yadif_cuda doesn't require the cuda sdk and licensing problems anymore. You just need clang installed now and ffmpeg will use that instead.

**Comment by wm4** [comment]
Does it work now?

**Comment by aufkrawall** [comment]
Yep, thanks for implementing!

@philipl That's good to know. Does ffmpeg's build config adapt automatically when clang is available? At least it's doesn't work by just installing clang together with ffmpeg from the Arch repository. I'm not sure if maintainers would add clang as a hard dependency for ffmpeg just for this case. :(

**Comment by philipl** [comment]
It's a build time dependency - there's no runtime component. So if you have clang around at build time, it should work automatically if you're already building with `--enable-cuda`.

**Comment by aufkrawall** [comment]
I can confirm that it works that way with clang as just a build dependency, very cool. I've always preferred yadif over d3d11va/vaapi implementations, so having it on the GPU is great.

Arch PKGBUILD contains `--enable-gpl --enable-version3` and adding `--enable-cuda` worked without additional verbosity.  Is this an indicator that it's still GPL3 compliant? I haven't found that information on the ffmpeg or CUDA licensing FAQ.

**Comment by philipl** [comment]
It is compliant - that's why the clang work was a big deal - it removed the cuda sdk dependency.

**Comment by aufkrawall** [comment]
Great, then I'm going to propose to enable it for the Arch repo build.

**Comment by aufkrawall** [comment]
Report to Arch:
https://bugs.archlinux.org/task/65521

@shinchiro Would it be possible to compile also the Windows builds that way?

**Comment by Doofussy2** [comment]
Sorry to horn in, here. But I was recently testing different deinterlacing options, and found that several didn't work. Maybe someone could confirm, deny or correct me on these? As reported, yadif_cuda doesn't work, but also these:

Windows 10, RTX 2060

![Annotation 2020-02-16 114631](https://user-images.githubusercontent.com/15950919/74611589-154d2700-50b2-11ea-8530-bc95d862840a.jpg)


```
hwdec=cuda-copy
vd-lavc-o=deint=adaptive
```

```
gpu-api=opengl
hwdec=cuda
vd-lavc-o=deint=adaptive
```

And when using the variations of `--d3d11vpp` (mode=<blend|bob|adaptive|mocomp|ivctc>) with interlaced test patterns, there is no observable difference. Am I missing something?

I can provide logs, if required.

**Comment by aufkrawall** [comment]
CUDA deinterlacing works for me. No idea if `gpu-context=win` is always automatically picked in this case.

I can confirm your findings that I could never spot noteable differences with the different d3d11vpp deinterlacers either (apart from some not working).

**Comment by Doofussy2** [comment]
It won't work at all, for me. What parameters are you using? And are you using shinchiro's latest build?

**Comment by Doofussy2** [comment]
Oh, disregard. It won't work in a profile. It has to run at launch. Will that be the same with `--vf=yadif_cuda` ?

**Comment by aufkrawall** [comment]
No, it can be toggled by pressing d during playback by default.

**Comment by Doofussy2** [comment]
Great! I look forward to testing it if @shinchiro can roll it in to his builds.

**Comment by wm4** [comment]
Is the old cuda full-stream decoder obsolete now (as far as the FFmpeg ecosystem goes)? This post processing it provides, like deinterlacing, seems to be fairly popular. Having Yadif is nice, but are the nvidia provided algorithms somehow available?

**Comment by philipl** [comment]
It's effectively obsolete, although we haven't declared it as such because there are a couple of edge cases.
- Maybe you really really want nvidia's deinterlacing algorithm. This is the only way to get access to it. We had asked them if they'd expose it in a way that it could be decoupled from cuvid and they made some noises then disappeared. (The cuvid api actually describes a mode where you can feed it raw video which could enable its use as a filter, but this mode isn't actually supported).
- It has a way of doing scaling as part of the decode step. Theoretically, this is the most efficient way to scale if you don't care about the scaling algorithm. It has little use for media player use-cases, but seems to attract people doing multi-stream transcoding trying to maximise hardware utilisation.

**Comment by Doofussy2** [comment]
I just thought I'd post screenshots for different deinterlacers, and alternate frames. In motion, the native cuda deinterlacer I think looks the best.

`--vf=yadif` `--hwdec=d3d11va-copy`
![yadif 01](https://user-images.githubusercontent.com/15950919/74613973-7da70300-50c8-11ea-945a-f7249b597b59.jpg)

![yadif 02](https://user-images.githubusercontent.com/15950919/74613978-83044d80-50c8-11ea-877e-51bd073c8fbc.jpg)


`--vf=bwdif` `--hwdec=d3d11va-copy`
![bwdif 01](https://user-images.githubusercontent.com/15950919/74614006-bb0b9080-50c8-11ea-8e89-046413280273.jpg)

![bwdif 02](https://user-images.githubusercontent.com/15950919/74614010-c1017180-50c8-11ea-847c-28fbb9a5b4f1.jpg)


`--d3d11vpp` `--hwdec=d3d11va-copy`
![d3d11vpp 01](https://user-images.githubusercontent.com/15950919/74614021-f1491000-50c8-11ea-95f1-7775c30ac897.jpg)

![d3d11vpp 02](https://user-images.githubusercontent.com/15950919/74614023-f73ef100-50c8-11ea-92e4-a9db0ca13f35.jpg)


`--vd-lavc-o=deint=adaptive` `--hwdec=cuda-copy`
![cuda 01](https://user-images.githubusercontent.com/15950919/74614043-44bb5e00-50c9-11ea-81bc-a19aacc956de.jpg)

![cuda 02](https://user-images.githubusercontent.com/15950919/74614046-49801200-50c9-11ea-8d1d-d86e3ef9a605.jpg)

**Comment by wm4** [comment]
Does a --d3d11vpp option really exist?

**Comment by Doofussy2** [comment]
> Does a --d3d11vpp option really exist?

It appears to be, but none of the variations seem to work. While choosing between bob and adaptive for cuda give you very different results. Is it possible that --d3d11vpp is just using the inverse telecine on the Nvidia GPU?

**Comment by shinchiro** [comment]
Thankfully getting clang installed is relatively easy. Next build should yadif_cuda enabled.

**Comment by aufkrawall** [comment]
@shinchiro 
> Thankfully getting clang installed is relatively easy. Next build should yadif_cuda enabled.

It works without issues, thank you!

**Comment by Doofussy2** [comment]
It won't work for me with my RTX 2060

```
[   0.224][i][vd] Using hardware decoding (nvdec-copy).
[   0.224][v][vd] Decoder format: 720x576 [64:45] nv12 auto/auto/auto/limited/auto CL=mpeg2/4/h264
[   0.224][v][vf] [in] 720x576 [64:45] nv12 bt.601/bt.601-625/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[   0.224][v][vf] [userdeint] 720x576 [64:45] nv12 bt.601/bt.601-625/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[   0.224][v][vf] [userdeint] (disabled)
[   0.224][v][vf] [lavfi-yadif_cuda] 720x576 [64:45] nv12 bt.601/bt.601-625/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[   0.224][d][ffmpeg] mpv_src_default_in: w:720 h:576 pixfmt:nv12 tb:1/1000000 fr:25/1 sar:64/45
[   0.225][d][ffmpeg] auto_scaler_0: w:iw h:ih flags:'bilinear' interl:0
[   0.225][d][ffmpeg] filter: auto-inserting filter 'auto_scaler_0' between the filter 'mpv_src_default_in' and the filter 'filter'
[   0.225][e][ffmpeg] Impossible to convert between the formats supported by the filter 'mpv_src_default_in' and the filter 'auto_scaler_0'
[   0.225][f][lavfi] failed to configure the filter graph
[   0.225][e][vf] Disabling filter lavfi-yadif_cuda.00 because it has failed.
```

[Portable mpv log.txt](https://github.com/mpv-player/mpv/files/4242063/Portable.mpv.log.txt)

**Comment by wm4** [comment]
This is because you're using copy-back, while the cuda filter requires a hardware format.

**Comment by Doofussy2** [comment]
I tried that, and hwdec was not enabled. I assumed it was because it didn't support MPEG2, but I appear to not be able to make nvdec work with anything... hmmm.... This is a separate issue...

```
gpu-api=opengl
hwdec=nvdec
vf=yadif_cuda
```

**Comment by philipl** [comment]
You are using vo=gpu? You have to.

**Comment by Doofussy2** [comment]
> You are using vo=gpu? You have to.

Yes, I just made a new issue report

https://github.com/mpv-player/mpv/issues/7483

**Comment by aufkrawall** [comment]
`--deinterlace`?
