### ISSUE TITLE
0.31 to 0.32: Can no longer use "--playlist -"

### ISSUE THREAD

**Issue by fatalis** [mpv-player/mpv#7466]
### Important Information

Provide following Information:
- mpv version: 0.32
- Platform and Version: Arch Linux
- Source of the mpv binary: AUR mpv-full

### Reproduction steps

cat playlist.m3u8 | mpv --playlist -

### Expected behavior

Works  as in 0.31

### Actual behavior

> Error parsing commandline option playlist: option requires parameter

**Comment by sfan5** [comment]
Option parsing was changed, you need to use `--playlist=-`.
