### ISSUE TITLE
Fetch subtitles request

### ISSUE THREAD

**Issue by intre4si32** [mpv-player/mpv#747]
It would be really nice to be able to fetch subtitles from sites such as opensubtitles.org based on movie's hash  and triggered  by custom hotkey. I am spoiled with such feat from smplayer and wish mpv had this. Will feature like this be any time soon in the scope of mpv progress?

**Comment by robin007bond** [comment]
Someone made a Lua script for this feature.

https://gist.github.com/selsta/ce3fb37e775dbd15c698

It uses subliminal for subtitle downloading.

**Comment by wm4** [comment]
And that's how it should be done. This script is good and simple enough as that it could be included under TOOLS in the mpv git repo, too. (Except for the hardcoded path.)

**Comment by rrooij** [comment]
This issue can be closed in my opinion, since this is already done by a nice script.

**Comment by wm4** [comment]
Indeed, it's listed somewhere here: https://github.com/mpv-player/mpv/wiki/User-Scripts#lua
