### ISSUE TITLE
Hi, I don’t know if this is a question or an issue, but when I extract captures from an interlaced footage (i.e. vhs captured tapes) and I type “D” for deinterlace, I get interlaced saved images. Is there a way to “solve” this?

### ISSUE THREAD

**Issue by nihelmasell** [mpv-player/mpv#7470]
Don't ask questions about issues, errors or problems you have and instead open
a proper issue with the right template from the previous selection.

This template is meant for questions about the workings of mpv, to clarify about
unspecified behaviour of options or command, or anything else that is not well
described and needs clarification.

Before asking a question make sure it hasn't been asked or answered yet.
https://github.com/mpv-player/mpv/labels/meta%3Aquestion

**Comment by wm4** [comment]
Why didn't you type your question into the text field instead of the title?

Normally screenshots should look exactly like on the mpv video window. If not, it might be a bug.
