### ISSUE TITLE
there is no option to remove recent files eg mp3s from history

### ISSUE THREAD

**Issue by Unixware** [mpv-player/mpv#7473]
The history is displayed on the win10 start menu : mpv icon while pinned on start :recent files
there is no option to remove them, only manualy.

**Comment by wm4** [comment]
mpv doesn't do that. There is no API call to add anything to the history. Maybe explorer.exe or whatever launches mpv does.

**Comment by Ozkanozsm** [comment]
this isn't an mpv feature but a feature added by shinchiro's mpv bootstrapper.
