### ISSUE TITLE
How can I get a log file that only has warning messages (warn)?

### ISSUE THREAD

**Issue by canlang** [mpv-player/mpv#7474]
The option '--log-file' means default verbose, but I wanna save just error/more fatal case. 
When I use 'msg-level' options, it wasn't working with the log file. 
e.g., log-file=~~/mpv.log and 'quiet, no-terminal, really-quiet' not work too
I think it only works on the terminal. Is there any way I want?

Thanks,

**Comment by Cpuroast** [comment]
According to the manual, --msg-level also affects --log-file.

https://mpv.io/manual/stable/#terminal

So something like --msg-level=all=warn, would only show warnings or worse for all modules.

**Comment by Akemi** [comment]
```
--log-file=<path>
Opens the given path for writing, and print log messages to it. Existing files will be truncated. The log level is at least -v -v, but can be raised via --msg-level (the option cannot lower it below the forced minimum log level).
```
from the docs. it can't be lowered. i guess the terminal redirect is the only way.

**Comment by canlang** [comment]
@Akemi Thanks for your help
