### ISSUE TITLE
(mpv+vaporsynth/minimum build) no audio

### ISSUE THREAD

**Issue by mrkapqa** [mpv-player/mpv#7476]
Hello ,

i used this guide to build mpv with vaporsynth

https://www.svp-team.com/wiki/SVP:Linux

mpv with Vapoursynth support

# install dependencies: add more if you want additional ffmpeg/mpv codecs and features
sudo apt-get install python-minimal libssl-dev libfribidi-dev libluajit-5.1-dev libx264-dev xorg-dev libegl1-mesa-dev 

git clone https://github.com/mpv-player/mpv-build.git
cd mpv-build

# minimal install, feel free to add more options to ffmpeg_options and mpv_options
echo --enable-libx264 >> ffmpeg_options
echo --enable-vapoursynth >> mpv_options
echo --enable-libmpv-shared >> mpv_options
./rebuild -j4
sudo ./install
cd ..

The video plays fine in 60fps , but there is no audio.

Whenever i click "i" during playback, info on video codecs is shown, but no info on audio.

Thanks

**Comment by mrkapqa** [comment]
sorry,

 i use

Devuan Beowulf 64Bit (based on Debian Buster i think),


mpv 0.32.0-116-g6d8b4ca742 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Wed Feb 19 19:57:19 CET 2020
FFmpeg library versions:
   libavutil       56.41.100
   libavcodec      58.70.100
   libavformat     58.38.101
   libswscale      5.6.100
   libavfilter     7.76.100
   libswresample   3.6.100
FFmpeg version: N-96778-gbb01baae26

**Comment by mrkapqa** [comment]
Thanks, the answer was most probably found here

https://askubuntu.com/questions/1171327/mpv-plays-no-audio-when-watching-a-video/1172046


> 

Fixed it using these additional ffmpeg configs 

`//dependencies
sudo apt-get install libx264-dev libmp3lame-dev libfdk-aac-dev

// type these commands in the folder where you build mpv
echo --enable-libx264 >> ffmpeg_options
echo --enable-libmp3lame >> ffmpeg_options
echo --enable-libfdk-aac >> ffmpeg_options
echo --enable-nonfree >> ffmpeg_options`

**Comment by wm4** [comment]
Why did you ignore this part in the issue template:
```
### Log file

Upload build/config.log or ./waf configure output to https://0x0.st/ or attach
it to the github issue, and replace this text with a link to it.

The issue will be closed for ignoring the issue template.
```

**Comment by mrkapqa** [comment]
sorry, i did not see this.

solution was found here

https://www.svp-team.com/forum/viewtopic.php?id=5532
