### ISSUE TITLE
Set window-scale has no effect when gpu-backend=wayland

### ISSUE THREAD

**Issue by mweinelt** [mpv-player/mpv#7477]
### Important Information

```
❯ mpv -v
[cplayer] Command line options: '--script=/nix/store/zr347ip95p9ar8k1p0hspkbxl912y7y2-mpv-mpris-0.3.so' '-v'
[cplayer] mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] ffmpeg library versions:
[cplayer]    libavutil       56.31.100
[cplayer]    libavcodec      58.54.100
[cplayer]    libavformat     58.29.100
[cplayer]    libswscale      5.5.100
[cplayer]    libavfilter     7.57.100
[cplayer]    libswresample   3.5.100
[cplayer] ffmpeg version: 4.2.2
```

NixOS 20.03
Sway 1.4
i915 (modesetting) on Linux 5.5.4

### Reproduction steps

1. Start a video on wayland using `--gpu-backend=wayland`
2. Ensure the window is floating, not fullscreen
3. Try to rescale the window using `Alt+0`, `Alt+1`, `Alt+2`

### Expected behavior

The window should resize to 50%, 100% and 200% of the original videos resolution.

### Actual behavior

The video stays at 100% while the OSD and logs indicating that resizing happened.

### Log file

https://gist.github.com/mweinelt/cbc84dedb6c1e1c7cbd20f78807bd061

### Sample files

n/a

**Comment by Dudemanguy** [comment]
Yeah 0.32 has a bug that affects Sway and causes this not to work, but it works in the master branch. If for some reason it doesn't, feel free to open this up again.
