### ISSUE TITLE
Fail to build macOS bundle.

### ISSUE THREAD

**Issue by Tsukimeizi** [mpv-player/mpv#7480]
### Important Information

Provide following Information:
- mpv version
git master

- macOS Version
10.15.4 Beta (19E234g)

- Source of the mpv binary or bundle
git master

- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

$python3 TOOLS/osxbundle.py build/mpv

Creating Mac OS X application bundle (version: 0.32.0-UNKNOWN)...
> copying bundle skeleton
> copying binary
> create bundle symlink
> generating Info.plist
> bundling dependencies
/bin/sh: TOOLS/dylib-unhell.py: Permission denied

done.

**Comment by wm4** [comment]
Is that the actual terminal output?

**Comment by Tsukimeizi** [comment]
> Is that the actual terminal output?

Yes, see attached screen capture.
<img width="802" alt="截屏2020-02-21 下午8 48 50" src="https://user-images.githubusercontent.com/8336506/75035963-b17c9100-54eb-11ea-80cf-04fb1220805f.png">

**Comment by Tsukimeizi** [comment]
after re-clone the git master, now it is ok.
