### ISSUE TITLE
nvdec failing (invalid argument)

### ISSUE THREAD

**Issue by Doofussy2** [mpv-player/mpv#7483]
### Important Information

Windows 10

```
mpv 0.32.0-157-g57ecfb4da2 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
  built on Sun Feb 23 19:31:07 +08 2020
  FFmpeg library versions:
  libavutil       56.41.100
  libavcodec      58.73.101
  libavformat     58.39.101
  libswscale      5.6.100
  libavfilter     7.76.100
  libswresample   3.6.100
FFmpeg version: git-2020-02-22-c48e5431c
```

### Reproduction steps

Enable nvdec with:
```
gpu-api=opengl
hwdec=nvdec
```
### Expected behavior

nvdec to be used to decode the video

### Actual behavior

Decoder fails due to invalid argument
```
[   0.368][v][vo/gpu] Loading hwdec driver 'cuda-nvdec'
[   0.454][v][vd] Trying hardware decoding via h264-nvdec.
[   0.455][v][vd] Pixel formats supported by decoder: cuda dxva2_vld d3d11va_vld d3d11 yuv420p
[   0.455][v][vd] Codec profile: High (0x64)
[   0.455][v][vd] Requesting pixfmt 'cuda' from decoder.
[   0.456][d][ffmpeg/video] h264: NVDEC capabilities:
[   0.456][d][ffmpeg/video] h264: format supported: yes, max_mb_count: 65536
[   0.456][d][ffmpeg/video] h264: min_width: 48, max_width: 4096
[   0.456][d][ffmpeg/video] h264: min_height: 16, max_height: 4096
[   0.456][e][ffmpeg/video] h264: decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_INVALID_VALUE: invalid argument
[   0.457][w][ffmpeg/video] h264: Using more than 32 (67) decode surfaces might cause nvdec to fail.
[   0.457][w][ffmpeg/video] h264: Try lowering the amount of threads. Using 1 right now.
[   0.457][e][ffmpeg/video] h264: Failed setup for format cuda: hwaccel initialisation returned error.
```
### Log file

[Portable mpv log.txt](https://github.com/mpv-player/mpv/files/4242192/Portable.mpv.log.txt)

**Comment by Doofussy2** [comment]
CUDA works, but not nvdec.

**Comment by philipl** [comment]
That just seems wrong. Can you attach the full config you are using?

**Comment by Doofussy2** [comment]
> That just seems wrong. Can you attach the full config you are using?

```
## GENERAL ##
log-file="D:\mpv logs\Portable mpv log.txt"
msg-level=v
screenshot-format=jpg
screenshot-high-bit-depth=yes
d3d11-output-csp=auto
save-position-on-quit=yes


## VIDEO ##
vo=gpu
gpu-api=opengl
hwdec=nvdec
hwdec-codecs=all
opengl-pbo=yes
scale=spline36
cscale=spline36
sigmoid-upscaling=yes
glsl-shader="D:\mpv\FSRCNNX_x2_16-0-4-1.glsl"
dither-depth=auto
deband=yes
deband-iterations=1
deband-grain=0
saturation=5
brightness=0
contrast=8
gamma=14



## AUDIO ##
audio-channels=7.1
audio-exclusive=yes
audio-stream-silence=yes
audio-device=wasapi/marantz (NVIDIA High Definition Audio)
audio-spdif=ac3,eac3,dts,dts-hd,truehd
audio-buffer=1
af=surround:chl_out=7.1:lfe_low=80


## STREAM ##
demuxer-readahead-secs=3
demuxer-seekable-cache=yes
force-seekable=yes
hwdec-extra-frames=60


## SUBTITLES ##
sub-create-cc-track=yes
sub-pos=90


## AUTO-PROFILES ##

[Interlaced]
profile-desc=cond:p["video-frame-info/interlaced"]
hwdec=d3d11va-copy
vf=bwdif



[Surround Upmix]
profile-desc=cond:p["audio-codec-name"]=="aac" or p["audio-codec-name"]=="mp3"


[720p]
profile-desc=cond:p["video-params/w"]==1280


[HDR]
profile-desc=cond:p["video-params/primaries"]=="bt.2020"
dither-depth=auto
deband=yes
deband-iterations=1
contrast=0
saturation=0
brightness=0
gamma=0
fs
```

**Comment by philipl** [comment]
Get rid of the (crazy) `hwdec-extra-frames=60`. It's probably failing to allocate those frames and bailing.

**Comment by Doofussy2** [comment]
I thought about that. I'll give it a try, later.

**Comment by Doofussy2** [comment]
> Get rid of the (crazy) `hwdec-extra-frames=60`. It's probably failing to allocate those frames and bailing.

Ok, that works, but now I have a question. @philipl Considering that all the other decoders work just fine with that, do you consider this a bug with nvdec or a normal/satisfactory limitation?

**Comment by philipl** [comment]
This setting has nothing to do with seeking. It is setting how many frames to allocate in the GPU-side pool of frame buffers for the decoding pipeline. For a basic decoding scenario, you need however many the decoder has to hold on to for references. If you are doing GPU filtering, you may need a few more. You'd never ask for more than a small single digit number of extra frames in the pool. It is not buffering from any sort of network stream perspective. That kind of buffering is all done pre-decode. So it's simply wrong to set it in that way.

As to why you don't see any effect on other hwdecs, it depends on how the ffmpeg hwaccel is implemented, but it's not a sane config value for any of them.

**Comment by Doofussy2** [comment]
I understood what it was for/doing. Where I placed it in my config is just a place holder. I suppose I should have put it in general or video, but again, just a place holder. 

I'd only just started experimenting with it. But thanks for a more detailed explanation of it's function. For now, I'll just remove it.

And to report, vf=yadif_cuda, now works :)  

I'll close this

**Comment by garoto** [comment]
`--no-config` should be the first thing to try when troubleshooting.

**Comment by Doofussy2** [comment]
But a config needs to be used to enable ndvec.

**Comment by garoto** [comment]
Not really. `mpv` is CLI player by its own definition.

**Comment by Doofussy2** [comment]
Oh, I see what you're saying. I would adjust the config or remove it, to achieve the same objective. I tend to test a battery of files. Using a config is much easier. What threw me off was that everything else worked, and I made a wrong assumption. But I did start to suspect that it may have been that line. I'm always looking to better understand, through experimentation.
