### ISSUE TITLE
Negative sub delay doesn't seem to work properly

### ISSUE THREAD

**Issue by menma1234** [mpv-player/mpv#7484]
### Important Information

Provide following Information:
- mpv version: 64-bit git 57ecfb4
- Windows Version: Windows 10 v1909
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20200223-git-57ecfb4.7z/download
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches:
    - https://puu.sh/FdNQ2/286d75d517.mp4 (with negative shift using mpv)
    - https://puu.sh/FdNVH/84e8eab508.mp4 (expected behaviour, subtitles modified externally to be shifted by the same amount)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

1. Open an MKV file with ASS subtitles
2. Set sub delay to a large negative value (e.g. -5s)
3. Observe subtitles after the video plays for a while

### Expected behavior

The subtitles' start and end times should be shifted by that amount.

### Actual behavior

It looks like only the end time is shifted by that amount. This results in subtitles that are on screen for shorter than the shift to not show up at all. Seeking backwards seems to "fix" it and the subtitles that have been previously seen are all properly shifted but then this bugged behaviour happens again for all new lines.

### Log file

https://pastebin.com/sYhTmVTr

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wm4** [comment]
This is because it doesn't read-ahead enough to see the subtitle packets. They are read as the video/audio is read, so they're "too late". Past subtitles are usually cached, so that's why seeking back makes it work. In theory we could add some code to force the read-ahead, but not sure if I should bother, since a simple --cache=yes should also work this around.

**Comment by menma1234** [comment]
Can confirm that adding `--cache=yes` does get around the issue, so good to know about it. Would definitely be nice if this worked out of the box though, since I was definitely confused for a while.
