### ISSUE TITLE
Setting --stream-lavf-o=seekable=0 does not always remove the Range header

### ISSUE THREAD

**Issue by szescxz** [mpv-player/mpv#7485]
### Important Information

- mpv version: 0.32.0-167-gc418aa3807
- Platform and Version: Debian 10
- Source of the mpv binary: self-compiled without source modification

### Reproduction steps

_The actual stream I'm running trouble into is similar to https://trac.ffmpeg.org/ticket/6125, except that an empty `Range` header does not work in my case (therefore specifying `--http-header-fields` is not an option). Since I'm not at liberty to share the stream in question, I'll just use a publicly available one to demonstrate here._
Running mpv with
`$ mpv --stream-lavf-o=seekable=0 --demuxer-lavf-o=seekable=0 --msg-level=ffmpeg=trace --log-file=mpv.log "https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8"`

### Expected behavior

All requests should not contain the `Range` header at all, i.e. identical to requests made by `$ ffmpeg -seekable 0 -i "https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8" -c copy -y /dev/null -v trace` (ffmpeg.log:L39,L77,L105,L133,L161,L189,L217,L245).

### Actual behavior

Only request to master HLS playlist does not contain the `Range` header (mpv.log:L172,L237), all of the following requests contains the `Range` header (mpv.log:L287,L326,L365,L404,L443,L482,L521).

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/4243143/mpv.log)
[ffmpeg.log](https://github.com/mpv-player/mpv/files/4243142/ffmpeg.log)

### Additional comments
This issue also happens on recent Windows builds from https://sourceforge.net/projects/mpv-player-windows/files; however, it does not happen on an old Windows build I have (0.28.0-215-g59f9547fb5).

**Comment by wm4** [comment]
You could use a debugger, set a break point on the code that adds the Range header, and check why it's done.

**Comment by szescxz** [comment]
Rebuilding with source code from Debian 10 repository (`apt-get source mpv`, build dependency installed with `mk-build-deps`) and the issue seems gone. mpv version there is a bit old though (0.29.1).
I'm not interested in debugging at the moment so I'll close this issue for now.

**Comment by wm4** [comment]
Probably a change in the ffmpeg code?
