### ISSUE TITLE
Temporary options for screenshots

### ISSUE THREAD

**Issue by mrnoname1000** [mpv-player/mpv#7486]
There should be a way to enable options temporarily while taking a screenshot and reset them afterwards. Two use cases I can think of quickly are dithering, where error-diffusion algorithms might be too expensive for realtime, yet desirable for quality and filesize (i.e. atkinson); and interpolation, where you just want a screenshot of the original image. Basically I just want to quickly jack up the quality settings for screenshots and capture the best image I can get.

This could be done like ytdl-raw-options, i.e.:
```
screenshot-options=interpolation=no,dither=error-diffusion,error-diffusion=atkinson
```

This is especially painful now since you either have to bind a key beforehand for each setting you want to change, or change the setting on the command line or config file before taking a screenshot, then take the reverse action.

**Comment by TheAMM** [comment]
Maybe just make a script to toggle the settings, screenshot and revert automatically.

**Comment by Akemi** [comment]
i think this should be done with a script.
