### ISSUE TITLE
Seeking beyond end of video

### ISSUE THREAD

**Issue by ZhenyaHanson** [mpv-player/mpv#7487]
I use mpv for research purposes, where I need the video to stay open even when the end has been reached. For this reason I set keep-open=always in my mpv.conf. With this setting, it appears that when I seek beyond the end of the video with SHIFT + RIGHT ARROW KEY, the internal seeking timestamp goes past the video, and when seeking with SHIFT + LEFT ARROW KEY it will seek within this false time region. Seeking with LEFT ARROW KEY will seek like normal within the actual time range of the video.

It seems low priority since it doesn't crash anything and mostly requires me to not hold down the SHIFT + RIGHT ARROW KEY shortcut when seeking, but it seems like a bug none the less. It's interesting that this problem is only with the shift version of the right arrow key seek and not the regular right arrow key seek, I wonder what the difference between their seeking is.

I am on windows, and provide my mpv.conf, input.conf, and a link to some sample output when running mpv with -v below.

mpv.conf:
```
keep-open=always
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
osd-fractions
screenshot-directory=.
screenshot-template=mpv-shot%P
screenshot-format=png
no-osd-bar
autofit=95%x90%
#window-maximized=yes
fs
#geometry=100%x100%+0+14
#osd-font-size=25
osd-font-size=55
pause
osd-level=3

[eye-cancer]
sharpen=5
```

input.conf:
```
; seek -0.0015 exact
' seek 0.0015 exact
WHEEL_UP seek 0.0015 exact
WHEEL_DOWN seek -0.0015 exact
Shift+Ctrl+s cycle-values screenshot-template "mpv-shot%P" "mpv-shot%n"
Shift+Ctrl+Alt+s  cycle-values screenshot-format "jpg" "png"
Shift+Ctrl+o cycle-values osd-font-size "25" "15" "55"
Ctrl+o cycle-values osd-bar "yes" "no"
```

 the `mpv -v` output, the pertinent bits seem to be towards the end (for instance, jump the line `[lavf] queuing seek to 13.998000`)
[mpvSampleOutput.txt](https://github.com/mpv-player/mpv/files/4248801/mpvSampleOutput.txt)

**Comment by wm4** [comment]
And what is the bug/problem?

**Comment by ZhenyaHanson** [comment]
The behavior of SHIFT+RIGHT ARROW KEY followed by SHIFT+LEFT ARROW KEY doesn't match the behavior of RIGHT ARROW KEY followed by LEFT ARROW KEY when the end of the video has been reached.

For example (using abbreviations), holding down RA at the end of the video will do nothing, and pressing LA once will seek backwards into the video 5 seconds; holding down SRA at the end of the video will seem to do nothing, but then pressing SLA will also seem to not do anything until it has been pressed enough times to cancel out the prior SRA presses.

Looking at the sample output I provided from running mpv with -v, it looks like some kind of seeking is being done in timestamps that exist past the end of the video. Maybe this is intended behavior or a limitation of seeking with exact?

**Comment by wm4** [comment]
This "internal" timestamp is just the last seek target. It's used as base for relative seeks if no audio/video timestamp is available. This in turn happens you seek fast enough, or when all audio/video was skipped. I attempted to fix it for the keep-open case, but due to what I just said there's course still some short moments in which a non-existent timestamp is shown.
