### ISSUE TITLE
cannot set font for console and stats

### ISSUE THREAD

**Issue by blackarcher21** [mpv-player/mpv#7496]
### Important Information

mpv version
mpv 0.32.0-157-g57ecfb4da2 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects  built on Sun Feb 23 19:31:07 +08 2020
FFmpeg library versions:
   libavutil       56.41.100
   libavcodec      58.73.101
   libavformat     58.39.101
   libswscale      5.6.100
   libavfilter     7.76.100
   libswresample   3.6.100
FFmpeg version: git-2020-02-22-c48e5431c

Windows 10 1703 64-bit

### Reproduction steps

Since I can't get script-opts work from command line, so I create mpv.conf with only osd-font="Segoe UI", console.conf and stats.conf with font (and font_mono) option with font="Courier New" to test.
With all those config, play video, it looks that console and stats using font from osd-font

### Expected behavior
Console and stats uses font from its own config

### Actual behavior
Console and stats uses font from mpv.conf osd-font 

### Log file

https://pastebin.com/y9FMt0EZ

**Comment by deus0ww** [comment]
In console.conf and stats.conf, try setting the font property without quotation marks (i.e. font=Courier New). This works for me. Also, there's no 'font_mono' for console.conf.

**Comment by blackarcher21** [comment]
yes, I know font_mono is only for stats.lua.
and yes, setting the font without quotation marks works.
thank you. regards.

**Comment by garoto** [comment]
Can't say if it's a specifc issue to `mpv's` implementation or a general `libass` thing **and** if restricted to Windows builds, but apparently calling a font-family simply  by `sans` isn't recognized as a proper font-family in Windows. From my testings, a font-family needs to be declared as `sans-serif` either directly in `stats.lua` or in `stats.conf` for mpv/libass to actually be able to pick a proper `sans-serif` font, otherwise the font specified in `osd-font` (if any) will _leak_ to `stats.lua` rendered output.

Log bit when drawing `stats.lua` and when ***not*** using a specific font declaration in `stats.conf` (`IBMPlexMono-Text` is my configured `osd-font` in the text below):
```
[   2.402][d][cplayer] Run command: enable-section, flags=64, args=["input_forced_stats", "allow-hide-cursor+allow-vo-dragging"]
[   2.404][i][osd/libass] fontselect: Using default font family: (sans, 700, 0) -> IBMPlexMono-Text, 0, IBMPlexMono-Text
[   2.404][v][osd/libass] fontselect: (sans, 700, 0) -> IBMPlexMono-Text, 0, IBMPlexMono-Text
[   2.405][i][osd/libass] fontselect: Using default font family: (sans, 400, 0) -> IBMPlexMono-Text, 0, IBMPlexMono-Text
[   2.405][v][osd/libass] fontselect: (sans, 400, 0) -> IBMPlexMono-Text, 0, IBMPlexMono-Text
[   2.405][v][osd/libass] fontselect: (monospace, 400, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   2.405][v][osd/libass] Glyph 0x3BC not found, selecting one more font for (sans, 400, 0)
[   2.406][v][osd/libass] fontselect: (sans, 400, 0) -> ArialMT, 0, ArialMT
[   2.429][v][vo/gpu] Reallocating OSD texture to 1024x1024.
[   2.472][d][cplayer] Run command: script-binding, flags=73, args=["stats/display-stats-toggle"]
[   3.720][d][cplayer] Run command: script-binding, flags=73, args=["stats/2"]
[   3.723][v][osd/libass] fontselect: (monospace, 200, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   3.723][v][osd/libass] fontselect: (monospace, 345, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   3.723][v][osd/libass] fontselect: (monospace, 700, 0) -> CourierNewPS-BoldMT, 0, CourierNewPS-BoldMT
[   3.723][v][osd/libass] fontselect: (monospace, 368, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   3.724][v][osd/libass] fontselect: (monospace, 450, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   3.724][v][osd/libass] fontselect: (monospace, 511, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   3.724][v][osd/libass] fontselect: (monospace, 567, 0) -> CourierNewPS-BoldMT, 0, CourierNewPS-BoldMT
[   3.724][v][osd/libass] fontselect: (monospace, 569, 0) -> CourierNewPS-BoldMT, 0, CourierNewPS-BoldMT
[   3.725][v][osd/libass] fontselect: (monospace, 304, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   3.852][d][cplayer] Run command: script-binding, flags=73, args=["stats/2"]
[   4.404][v][osd/libass] fontselect: (monospace, 319, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   4.404][v][osd/libass] fontselect: (monospace, 399, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   4.404][v][osd/libass] fontselect: (monospace, 475, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   4.405][v][osd/libass] fontselect: (monospace, 505, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   4.405][v][osd/libass] fontselect: (monospace, 547, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   4.405][v][osd/libass] fontselect: (monospace, 566, 0) -> CourierNewPS-BoldMT, 0, CourierNewPS-BoldMT
[   4.405][v][osd/libass] fontselect: (monospace, 317, 0) -> CourierNewPSMT, 0, CourierNewPSMT
[   4.692][d][cplayer] Run command: list, flags=0, args=[]
```

Related commit:
https://github.com/mpv-player/mpv/commit/cb51dfa76a8760fc0d67de9ee90f692ee02fc247
