### ISSUE TITLE
audio stops when audio track is changed-2

### ISSUE THREAD

**Issue by lvmm** [mpv-player/mpv#7498]
### Important Information

mpv git-2020-02-01-f304a79
5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Reproduction steps

start playing the attached file
press # to change audio track

### Expected behavior

new audio track should've continued playing

### Actual behavior

audio stops

### Log file

A repeat of #7306. Short jump usually helps. 100% reproducible with the attached file. Always happened when playing MPEG-2 TS. Reproducible with https://0x0.st/iq-n.ts. Note: with the first 32M or 64M of the original file the issue couldn't be reproduced, but with this 128M file sound stops when switching audio tracks.

[cplayer] Command line options: '-v' '2.ts'
[cplayer] mpv git-2020-02-01-f304a79 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer] built on Fri Feb 21 02:24:22 UTC 2020
[cplayer] ffmpeg library versions:
[cplayer] libavutil 56.38.100
[cplayer] libavcodec 58.67.100
[cplayer] libavformat 58.37.100
[cplayer] libswscale 5.6.100
[cplayer] libavfilter 7.72.100
[cplayer] libswresample 3.6.100
[cplayer] ffmpeg version: git-2020-02-01-843c24a
[cplayer]
[cplayer] Configuration: ./waf configure --enable-pdf-build --enable-dvbin --enable-dvdnav --enable-html-build --enable-javascript --enable-cdda --zshdir=/usr/share/zsh/vendor-completions --prefix=/usr --confdir=/etc/mpv
[cplayer] List of enabled features: 52arch aligned_alloc alsa asm atomics build-date cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm drmprime dvbin dvdnav egl egl-drm egl-helpers egl-x11 fchmod ffmpeg ffnvcodec gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack javascript jpeg lcms2 libarchive libass libass-osd libav-any libavcodec libavdevice libavutil libbluray libdl libm libplacebo librt linux-fstatfs lua memfd_create optimize oss-audio posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 vt.h vulkan wayland wayland-protocols x11 xv zimg zlib
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /etc/mpv/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /home/lvm/.config/mpv/mpv.conf
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'fs' = 'yes' (flags = 4)
[cplayer] Setting option 'volume-max' = '256' (flags = 4)
[cplayer] Setting option 'sub-visibility' = 'no' (flags = 4)
[cplayer] Setting option 'sub-scale' = '0.5' (flags = 4)
[cplayer] Setting option 'cursor-autohide' = 'always' (flags = 4)
[cplayer] Setting option 'cursor-autohide-fs-only' = 'yes' (flags = 4)
[cplayer] Setting option 'save-position-on-quit' = 'no' (flags = 4)
[cplayer] Setting option 'sub-visibility' = 'no' (flags = 4)
[cplayer] Setting option 'osc' = 'no' (flags = 4)
[cplayer] Setting option 'audio-channels' = 'stereo' (flags = 4)
[cplayer] Setting option 'ad-lavc-downmix' = 'yes' (flags = 4)
[cplayer] Setting option 'screenshot-format' = 'png' (flags = 4)
[cplayer] Setting option 'cache' = 'yes' (flags = 4)
[cplayer] Setting option 'stop-screensaver' = '' (flags = 4)
[cplayer] Setting option 'hidpi-window-scale' = 'no' (flags = 4)
[cplayer] Setting option 'title' = '${filename}' (flags = 4)
[cplayer] Setting option 'hwdec' = 'vdpau' (flags = 4)
[cplayer] Setting option 'vo' = 'vdpau' (flags = 4)
[cplayer] Setting option 'v' = '' (flags = 8)
[ifo_dvdnav] Opening /home/lvm/.config/mpv/input.conf
[bdmv/bluray] Opening /home/lvm/.config/mpv/input.conf
[file] Opening /home/lvm/.config/mpv/input.conf
[input] Parsing input config file /home/lvm/.config/mpv/input.conf
[input] Input config file /home/lvm/.config/mpv/input.conf parsed: 56 binds
[cplayer] Waiting for scripts...
[cplayer] Done loading scripts.
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook
[ytdl_hook] not a ytdl:// url
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.7.2 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[ifo_dvdnav] Opening 2.ts
[bdmv/bluray] Opening 2.ts
[file] Opening 2.ts
[demux] Trying demuxers for level=normal.
[lavf] Found 'mpegts' at score=50 size=2048.
[file] stream level seek from 1703936 to 133967728
[ffmpeg/demuxer] mpegts: PES packet size mismatch
[ffmpeg/demuxer] mpegts: Packet corrupt (stream = 0, dts = 5932801).
[ffmpeg/demuxer] mpegts: PES packet size mismatch
[ffmpeg/demuxer] mpegts: Packet corrupt (stream = 1, dts = 5897520).
[ffmpeg/demuxer] mpegts: PES packet size mismatch
[ffmpeg/demuxer] mpegts: Packet corrupt (stream = 2, dts = 5897520).
[ffmpeg/demuxer] mpegts: PES packet size mismatch
[ffmpeg/demuxer] mpegts: Packet corrupt (stream = 3, dts = 5897520).
[file] stream level seek from 134217728 to 0
[lavf] avformat_find_stream_info() finished after 0 bytes.
[demux] Detected file format: mpegts (libavformat)
[cplayer] Opening done: 2.ts
[find_files] Loading external files in .
[cplayer] Running hook: ytdl_hook/on_preloaded
[lavf] select track 0
[lavf] select track 1
[cplayer] (+) Video --vid=1 (h264 1920x1080 25.000fps)
[cplayer] (+) Audio --aid=1 --alang=eng (mp2 2ch 48000Hz)
[cplayer] Audio --aid=2 --alang=eng (mp2 2ch 48000Hz)
[cplayer] Audio --aid=3 --alang=eng (mp2 2ch 48000Hz)
[vo/vdpau/x11] X11 opening display: :0
[vo/vdpau/x11] Display 0 (HDMI-0): [0, 0, 1920, 1200] @ 59.950171 FPS
[vo/vdpau/x11] Current display FPS: 59.950171
[vo/vdpau] Warning: this compatibility VO is low quality and may have issues with OSD, scaling, screenshots and more.
[vo/vdpau] vo=gpu is the preferred choice in any case and includes VDPAU support via hwdec=vdpau or vdpau-copy.
[vo/vdpau] Assuming 59.950171 FPS for display sync.
[vd] Container reported FPS: 25.000000
[vd] Codec list:
[vd] h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd] h264_v4l2m2m (h264) - V4L2 mem2mem H.264 decoder wrapper
[vd] h264_cuvid (h264) - Nvidia CUVID H264 decoder
[vd] Opening decoder h264
[vd] Looking at hwdec h264-vdpau...
[vd] Trying hardware decoding via h264-vdpau.
[vd] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[vf] User filter list:
[vf] (empty)
[ad] Codec list:
[ad] mp2 - MP2 (MPEG audio layer 2)
[ad] mp2float (mp2) - MP2 (MPEG audio layer 2)
[ad] Opening decoder mp2
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: mp2 (MP2 (MPEG audio layer 2))
[af] User filter list:
[af] (empty)
[cplayer] Starting playback...
[af] [in] 48000Hz stereo 2ch s16p
[af] [userspeed] 48000Hz stereo 2ch s16p
[af] [userspeed] (disabled)
[af] [convert] 48000Hz stereo 2ch s16p
[ao] Trying audio driver 'pulse'
[ao/pulse] requested format: 48000 Hz, stereo channels, s16p
[ao/pulse] Library version: 11.1.0
[ao/pulse] Proto: 32
[ao/pulse] Server proto: 4294967295
[ao/pulse] Channel layouts:
[ao/pulse] - #fl
[ao/pulse] - #fr
[ao/pulse] - #fc
[ao/pulse] - #lfe
[ao/pulse] - #bl
[ao/pulse] - #br
[ao/pulse] - #flc
[ao/pulse] - #frc
[ao/pulse] - #bc
[ao/pulse] - #sl
[ao/pulse] - #sr
[ao/pulse] - #tc
[ao/pulse] - #tfl
[ao/pulse] - #tfc
[ao/pulse] - #tfr
[ao/pulse] - #tbl
[ao/pulse] - #tbc
[ao/pulse] - #tbr
[ao/pulse] result: stereo
[ao/pulse] device buffer: 4800 samples.
[ao/pulse] using soft-buffer of 9600 samples.
[cplayer] AO: [pulse] 48000Hz stereo 2ch s16
[cplayer] AO: Description: PulseAudio audio output
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 48000Hz stereo s16p -> 48000Hz stereo s16
[af] [out] 48000Hz stereo 2ch s16
[vd] Pixel formats supported by decoder: vdpau cuda vaapi_vld yuv420p
[vd] Codec profile: High (0x64)
[vd] Requesting pixfmt 'vdpau' from decoder.
[vd] Using hardware decoding (vdpau).
[vd] Decoder format: 1920x1080 vdpau[yuv420p] bt.709/bt.709/bt.1886/limited/auto CL=mpeg2/4/h264
[vf] [in] 1920x1080 vdpau[yuv420p] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] 1920x1080 vdpau[yuv420p] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] (disabled)
[vf] [autorotate] 1920x1080 vdpau[yuv420p] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [autorotate] (disabled)
[vf] [convert] 1920x1080 vdpau[yuv420p] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [convert] (disabled)
[vf] [out] 1920x1080 vdpau[yuv420p] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[cplayer] VO: [vdpau] 1920x1080 vdpau[yuv420p]
[cplayer] VO: Description: VDPAU with X11
[vo/vdpau] reconfig to 1920x1080 vdpau[yuv420p] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[ffmpeg/demuxer] mpegts: PES packet size mismatch
[ffmpeg/demuxer] mpegts: Packet corrupt (stream = 0, dts = 5932801).
[ffmpeg/demuxer] mpegts: PES packet size mismatch
[ffmpeg/demuxer] mpegts: Packet corrupt (stream = 1, dts = 5897520).
[lavf] EOF reached.
[vo/vdpau] Window size: 1920x1080 (Borders: l=0 t=0 r=0 b=0)
[vo/vdpau] Video source: 1920x1080 (1:1)
[vo/vdpau] Video display: (0, 0) 1920x1080 -> (0, 0) 1920x1080
[vo/vdpau] Video scale: 1.000000/1.000000
[vo/vdpau] OSD borders: l=0 t=0 r=0 b=0
[vo/vdpau] Video borders: l=0 t=0 r=0 b=0
[vo/vdpau] Window size: 1920x1200 (Borders: l=0 t=0 r=0 b=0)
[vo/vdpau] Video source: 1920x1080 (1:1)
[vo/vdpau] Video display: (0, 0) 1920x1080 -> (0, 60) 1920x1080
[vo/vdpau] Video scale: 1.000000/1.000000
[vo/vdpau] OSD borders: l=0 t=60 r=0 b=60
[vo/vdpau] Video borders: l=0 t=60 r=0 b=60
[vo/vdpau] Recreating vdpau video mixer.
[cplayer] first video frame after restart shown
[vo/vdpau] Window size: 1920x1200 (Borders: l=0 t=0 r=0 b=0)
[vo/vdpau] Video source: 1920x1080 (1:1)
[vo/vdpau] Video display: (0, 0) 1920x1080 -> (0, 60) 1920x1080
[vo/vdpau] Video scale: 1.000000/1.000000
[vo/vdpau] OSD borders: l=0 t=60 r=0 b=60
[vo/vdpau] Video borders: l=0 t=60 r=0 b=60
[cplayer] audio sync: sync_to_video=1, offset=-0.000000
[cplayer] starting audio playback
[cplayer] playback restart complete @ 0.000000
[vo/vdpau/x11] Disabling screensaver.
[statusline] AV: 00:00:00 / 00:01:06 (0%) A-V: 0.000
[vo/vdpau] Frame shown late (30 ms)
[statusline] AV: 00:00:01 / 00:01:06 (2%) A-V: 0.000
[ao/pulse] draining...
[lavf] deselect track 1
[lavf] select track 2
[lavf] can't issue refresh seek
[ad] Codec list:
[ad] mp2 - MP2 (MPEG audio layer 2)
[ad] mp2float (mp2) - MP2 (MPEG audio layer 2)
[ad] Opening decoder mp2
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: mp2 (MP2 (MPEG audio layer 2))
[af] User filter list:
[af] (empty)
[cplayer] Track switched:
[cplayer] (+) Video --vid=1 (h264 1920x1080 25.000fps)
[cplayer] Audio --aid=1 --alang=eng (mp2 2ch 48000Hz)
[cplayer] (+) Audio --aid=2 --alang=eng (mp2 2ch 48000Hz)
[cplayer] Audio --aid=3 --alang=eng (mp2 2ch 48000Hz)
[cplayer] Set property: aid -> 1
[cplayer] Set property: audio -> 1
[statusline] AV: 00:00:01 / 00:01:06 (2%) A-V: 0.000
[af] filter input EOF
[af] [userspeed] (disabled)
[af] [convert] (disabled)
[af] filter output EOF
[cplayer] audio EOF without any data
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.7.2 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf, 0, DejaVuSans
[vo/vdpau] Allocating a 1024x256 surface for OSD bitmaps.
[statusline] AV: 00:00:02 / 00:01:06 (4%) A-V: 0.000
[cplayer] EOF code: 5
[cplayer] finished playback, success (reason 3)
[cplayer]
[cplayer]
[cplayer] Exiting... (Quit)
[vo/vdpau/x11] Enabling screensaver.

**Comment by wm4** [comment]
Same post I posted last time, without the last sentence.

**Comment by wm4** [comment]
Looked at the file, and yes it's a similar situation. I'll explained it last time, but you apparently completely ignored the explanation.

Anyway, deeper reason:
1. there is at least one packet which has no timestamp at all
2. there is at least one packet that has the same byte position as a previous packet

The former is probably because the start of the stream is broken or something. The latter must be because libavcodec's parser "splits" a packet. Both lead to the problem that mpv can't refill the part of the cache that was lost due to track switching. Blame ffmpeg.

**Comment by SimpelMe** [comment]
As long as v0.33.0 isn't released I have a dirty workaround. Using option `--no-initial-audio-sync` plays audio immediatly while switching audio. But in the first played second there can be small gaps.

**Comment by wm4** [comment]
That is something unrelated then.
