### ISSUE TITLE
playlist-pos suggestion

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#7501]
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

If the new position is identical with the old then the file is restarted, in that case I would prefer ignoring.

If the requested position is higher than the count then it's ignored, I think it would be better if it would go to the end. In vBulletin forums you can navigate to the last page of a thread that way, example:

https://forum.doom9.org/showthread.php?t=174841&page=1000000

**Comment by wm4** [comment]
It's completely unclear what you're asking for. That forum thread doesn't help either, it's about multiple topics.

**Comment by stax76** [comment]
Yes, I know I'm not good in writing English (allgemein kein guter Schreiber, leider). How can someone move to the last playlist track (without writing code)?

From the docs:

> Current position on playlist. The first entry is on position 0. Writing to the property will **restart** playback at the written entry.

If the current pos is 0 and you execute `set playlist-pos 0` then a restart happens which nags me a bit since I would prefer that nothing happens in this case.

It's not really important since I can write code, I just though you guys might agree with the idea. Don't know if that's boring work, I don't have any wishes for something more advanced like rendering, works perfect. 😀

**Comment by wm4** [comment]
Whether the property should work this way or not is rather unclear. There are various pros- and cons, and it's just a mess, so I neither want to touch it, nor should you rely on any specific behavior. (I guess I'll remove or reword that sentence in the manpage.)

**Comment by stax76** [comment]
Alright

**Comment by wm4** [comment]
I decided to "deprecate" the old behavior (see e9e93b4dbe748c), but until it can be changed, a few releases will have to pass. We can't change the behavior suddenly, even the longer deprecation period is probably too short and will probably not be appreciated by whatever people.

**Comment by stax76** [comment]
Thanks, can the console message be disabled?

> Behavior of playlist-pos when writing the same value will change (currently restarts, it will stop doing this).
