### ISSUE TITLE
Don't wipe progress ("save-position-on-quit") when playback fails

### ISSUE THREAD

**Issue by 07416** [mpv-player/mpv#7504]
When [save-position-on-quit](https://mpv.io/manual/master/#options-save-position-on-quit) is used the position to my knowledge always resets when playback fails — for instance, if my server isn't mounted and try to resume playback with `mpv <path>`, the progress resets.

Please only update the position for played files.

**UPDATE**: I don't  have the feature enabled, I only save the position manually with Shift+Q. I'm not fully certain yet if this makes a difference.

**Comment by 07416** [comment]
If anyone knows how to _only_ update the position when Shift+Q is used, that would be a partial solution (but not optimal since then older, finished videos would unnecessarily remain in memory). Quitting a video normally (by closing mpv) clears the saved position.

**Comment by wm4** [comment]
There's a PR that probably does some of what you want, but there are problems.

**Comment by 07416** [comment]
> 
> 
> There's a PR that probably does some of what you want, but there are problems.

I see, can you link?

**Comment by garoto** [comment]
There are only 15 open pull requests. You can't miss it.

**Comment by wm4** [comment]
#7367

**Comment by Dudemanguy** [comment]
Should have been fixed by 6a365b258ac77d7e4759e0ae14ccc9e882c4c86f
