### ISSUE TITLE
Arabic Subtitle issue with parentheses

### ISSUE THREAD

**Issue by OmrSi** [mpv-player/mpv#7507]
### Important Information
Using windows 10, I am a normal MPV user, not a developer, I use libmpv with Subtitle Edit, which is where I noticed this issue, but it's present in the player version as well.

I have an old version of the player which doesn't have this issue and the latest one which does.
The old version is from 2018.

In libmpv, every version before 22/9 doesn't have this issue, while every version after that does.
So it happened between 22/9 and 6/10.

This is a line written in Arabic and the punctuation marks are reversed to show up correctly.

### Reproduction steps
Open the file with a video. See the line.

### Expected behavior
The line should show up like this:
![image](https://user-images.githubusercontent.com/20923700/75904414-d8bc5200-5e4b-11ea-8bea-9703d2da6b19.png)
As it does in the old version.

### Actual behavior
The line shows up like this:
![image](https://user-images.githubusercontent.com/20923700/75904444-e4a81400-5e4b-11ea-8f42-453d5c84967b.png)

### Log file
Old (From 2018): [output.txt](https://github.com/mpv-player/mpv/files/4289025/output.txt)
New (Latest): [output.txt](https://github.com/mpv-player/mpv/files/4289056/output.txt)

### Sample files
[Test.zip](https://github.com/mpv-player/mpv/files/4288644/Test.zip)
You can also notice this with any line that starts with a word in parentheses, like `(عمر) قال`
which will show up as `قال (عمر)` before reversing. (You can see the difference by coying these two)

**Comment by Akemi** [comment]
yes, since we ask for a log file you should also provide one. also providing a log with the working version might help narrowing it down.

it's most likely either a libass issue or something related to harfbuzz.

**Comment by OmrSi** [comment]
Okay, I've added the logs.

**Comment by Akemi** [comment]
seems like this is an ffmpeg issue. if i convert (`ffmpeg -i Test.srt Test.ass`) the srt file to ass i get this.

```
[Script Info]
; Script generated by FFmpeg/Lavc58.73.101
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,0,100,100,0,0,1,1,0,2,10,10,10,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.00,0:00:04.44,Default,,0,0,0,,،(الظاهرية)، (جنوب الخليل)"\N"السلطة الفلسطينية

```

**Comment by OmrSi** [comment]
So the change in ffmpeg version between the 22/9 and 6/10 version is what caused this?

**Comment by wm4** [comment]
So the problem is that these two text parts are swapped? Seems rather surprising that ffmpeg would even touch the text, but I guess @OmrSi could try with the corresponding ffmpeg CLI versions to confirm this.

**Comment by OmrSi** [comment]
Well, I downloaded this https://ffmpeg.zeranoe.com/builds/
And tested with it using the same command: `ffmpeg.exe -i Test.srt Test.ass` and got:
`Dialogue: 0,0:11:06.32,0:11:10.76,Default,,0,0,0,,"(الظاهرية)، (جنوب الخليل)،\Nالسلطة الفلسطينية"`
Which is the way it should be.

**Comment by wm4** [comment]
In that case it's probably just confusion due to different software rendering it differently.

You should open an issue on the libass repo. Maybe someone can identify the problem.

The only thing mpv could possibly have done to change this behavior is to change the vsfilter compatibility RTL setting or so. (Don't know if this affects this case.)

**Comment by Akemi** [comment]
on my end they are switched around. though due to the right to left reading direction my text editors behave quite funky. i edited my comment above.
![Screenshot 2020-03-04 at 21 52 49](https://user-images.githubusercontent.com/680386/75922043-8c304100-5e62-11ea-87e8-2250515d3abb.png)

**Comment by OmrSi** [comment]
Here is how you ass file look here:
![image](https://user-images.githubusercontent.com/20923700/75922170-2b593680-5e6b-11ea-8be7-e09439cef8d1.png)

**Comment by wm4** [comment]
>  Something must have happened between 22/9 and 6/10 to cause this.

No, this is completely incorrect and misleading. Your build changed, and you didn't say which versions you built, with which configuration, and most likely it's just some 3rd party build anyway (about which we know even less).

**Comment by OmrSi** [comment]
Okay, let me be clear.
I use `mpv-1.dll` to view the video with subtitles inside Subtitle Edit.
This did not use happen in the version dated `2019-09-22` here https://sourceforge.net/projects/mpv-player-windows/files/libmpv/ but it started happening in the version dated `2019-10-06`

**Comment by Akemi** [comment]
dates are pointless. a build from 22.9 can be newer, version wise, than a build done later. it all depends on the version, tag, commit it was build from. the causing commit can also fall outside these date ranges. it's even less conclusive if you changed the source of the lib/binary between.

to properly narrow it down we would need the actual libass versions that (lib)mpv version was linked to. in the case it is a libass issue.

**Comment by OmrSi** [comment]
So, anything I can do to test on different libass versions?

**Comment by OmrSi** [comment]
Maybe I can test this on another player that uses libass to check?

**Comment by shabahengam** [comment]
actually fribidi cause the problem.check this commit in libass ( [Use FriBiDi 1.x API when available](https://github.com/libass/libass/commit/df7c00c95ec6e526bf85e6bc8296eaca66f5db8d) )
mpv built with libass commit [8088d2d](https://github.com/libass/libass/commit/8088d2dcfb8e3c0631ea4f065a1a1f9975f75fdd)
![2020-03-05_21-54](https://user-images.githubusercontent.com/53096747/76012768-185a6b00-5f2c-11ea-9c11-c35439c5ed17.png)

mpv built with libass commit [df7c00c](https://github.com/libass/libass/commit/df7c00c95ec6e526bf85e6bc8296eaca66f5db8d)
![2020-03-05_21-50](https://user-images.githubusercontent.com/53096747/76012778-1d1f1f00-5f2c-11ea-9534-c508e50a9167.png)

**Comment by wm4** [comment]
Interesting. I think all discussion should continue in https://github.com/libass/libass/issues/374 .
