### ISSUE TITLE
Subtitle file crashes MPV

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#7510]
### Important Information

Provide following Information:
- mpv version git-2020-02-01-843c24a
- Linux Distribution and Version Ubuntu 18.04
- Source of the mpv binary ppa
- If known which version of mpv introduced the problem NA
- Window Manager and version Compiz
- GPU driver and version Nvidia 340
- Possible screenshot or video of visual glitches NA

### Reproduction steps
run the subtitle file supplied below
mpv --sub_file=bad_file.txt any_video.mp4
and it crashes with a segfault (it is an ass file but Github does not like ass extension)

The file is badly broken, I created it when timing a supplied translation, but still, it should not crash MPV, should it?

### Expected behavior
No crash
### Actual behavior
Crash
### Log file
[logfile.txt](https://github.com/mpv-player/mpv/files/4299345/logfile.txt)
### Sample files
[bad_file.txt](https://github.com/mpv-player/mpv/files/4299338/bad_file.txt)

**Comment by wm4** [comment]
Doesn't crash here.

**Comment by felagund** [comment]
I see. Any idea how what could be specific to my system that causes the crash? I have three external monitors and the system is a rather old (Thinkpad W530) but have no idea how that could be relevant.

**Comment by wm4** [comment]
Maybe you could get a backtrace in gdb? Also what libass version id this using? I tried with master.

**Comment by mc4man** [comment]
Assuming you're using ppa then try new version in about an hr or so (mpv_0.32.0+git2~bionic2), how it works with your file/sub file wouldn't know but shouldn't crash on that sub file you posted..

(-  file crashed with libass thru 0.14 release here so added back the git master to mpv itself..

**Comment by felagund** [comment]
Indeed, this fixes the issue, it no longer crashes, thank you!

**Comment by wm4** [comment]
Probably one of the fixes that was made in the recent years. Really should make libass to make a new release.
