### ISSUE TITLE
[master branch] Could not initialize Lua when luajit < 2.1.0 installed on macOS Catalina

### ISSUE THREAD

**Issue by jnozsc** [mpv-player/mpv#7512]
### mpv version and platform versions
`master` branch, Mac OS X 10.15.33 

### Reproduction steps

this behavior happens after https://github.com/mpv-player/mpv/commit/d852ad2ae76c97fce710e41064c863842db87035 

and only happens when both `luajit` and `lua@5.1` are installed from Homebrew
```bash
brew install luajit
brew install lua@5.1
```

### Expected behavior

in my `mpv.conf`, I added one line as 
```
script-opts=osc-layout=box
```

from tag `release/0.32.0` or any commit before https://github.com/mpv-player/mpv/commit/d852ad2ae76c97fce710e41064c863842db87035 

I can get the OSC show up when I move my cursor

<img width="1648" alt="Screen Shot 2020-03-07 at 08 30 21" src="https://user-images.githubusercontent.com/470215/76147247-1fc66500-604f-11ea-93b2-9cc5b5c90f52.png">
 

### Actual behavior

But when I build from https://github.com/mpv-player/mpv/commit/d852ad2ae76c97fce710e41064c863842db87035  or any commit after this commit on master branch. The OSC could never show up

<img width="1648" alt="Screen Shot 2020-03-07 at 08 31 19" src="https://user-images.githubusercontent.com/470215/76147258-47b5c880-604f-11ea-8d60-179b811dd9c6.png">

### Log file

https://0x0.st/iT9G.txt

The issue will be closed for ignoring the issue template.

### My thought

This issue ONLY happens when BOTH `luajit` and `lua@5.1` are installed from Homebrew.

Before https://github.com/mpv-player/mpv/commit/d852ad2ae76c97fce710e41064c863842db87035 , the build script will pick up `lua@5.1` first, after this commit, it will pick up `luajit`

I try to uninstall `luajit` from my local and build from `master` again,  the OSC comes back.

I try to revert this commit on my local and build it again with both `luajit` and `lua@5.1` installed,  the OSC works well.

I am not sure whether it is a compatible issue or a configuration issue.

A quick fix is revert this commit https://github.com/mpv-player/mpv/commit/d852ad2ae76c97fce710e41064c863842db87035 , or at least move `lua@5.1` on the top of `luajit` . I can create this PR if necessary. 

A long term solution seems like require some time to investigate further.

cc @wm4

**Comment by CounterPillow** [comment]
So to sum it up: Your OSC isn't working with luajit, but working with every other version of lua?

Can you post a log file of the player generated with `--log-file`?

**Comment by jnozsc** [comment]
Thanks for this sum up, I install `lua@5.1` from Homebrew. Homebrew only provide [lua@5.1](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lua@5.1.rb) and [lua](https://github.com/Homebrew/homebrew-core/blob/master/Formula/lua.rb)(5.3), which may not back  compatible.


here is the link for the log file you mentioned (both `luajit` and `lua@5.1` are installed)
https://0x0.st/iTpa.txt

it seems I get some message as `Could not initialize Lua`

**Comment by jeeb** [comment]
Yes, that seems like a borked lua setup. Which is either a build system issue, or just broken libraries. Also that should be broken whether or not you set that script option I would guesstimate.

Well, the build system should be able to pick just one. The fact that you have both installed only means that in theory either one of them could get picked. The commit you point towards switches the priority to 5.2 and luajit over 5.1. Which makes sense. You can still override the selection to lua 5.1 specifically should you want that.

- You can validate which got pulled on the library side on macOS with `otool -L ~/path/to/your/mpv` (as long as the library is a shared one).
- You can fully clean your git repository and configre & build from a clean build root. In case it is any leftovers from lua 5.1 in a build that is now getting built with luajit.
- If nothing else depends on lua 5.1, attempt removing it just for testing purposes.

On the mpv development channel there's at least one person utilizing luajit with mpv, and for him both with and without that option work (specifically on macOS).

**Comment by jnozsc** [comment]
Thank Jeeb

Here are some update
```
otool -L /usr/local/bin/mpv | grep lua
	/usr/local/opt/luajit/lib/libluajit-5.1.2.dylib (compatibility version 2.0.0, current version 2.0.5)
```

then I remove my local repo folder, `git clone` into a new folder and build again from `master` branch HEAD, I still have the same issue.

I run `otool -L ` command again, still same `luajit` 2.0.5

I try to install `luajit` 2.1 beta to figure out whether it is a version issue or my local environment issue, but  I can not install version 2.1 for now https://github.com/Homebrew/homebrew-core/issues/51272

**Comment by jeeb** [comment]
Great that you were able to poke around and have something work. For the record, the person on IRC is also utilizing luajit master/2.1 branch.

So yes, it could just be that luajit's current release is borked on macOS (or how Homebrew builds it, I lay no blame on either side). Given that I heard random issues about luajit on macOS before I wouldn't be surprised with that luajit release having issues, although this is most likely the first time I've heard that it wouldn't load at all.

**Comment by jnozsc** [comment]
Thanks again for confirming this info.

Since the developer is using master/2.1 branch,
may I suggest to bump this line
https://github.com/mpv-player/mpv/blob/faf24a286fb69ef6b93522a4678fad81b6e989f6/waftools/checks/custom.py#L65

to 
```python
 ( 'luajit', 'luajit >= 2.1.0' ),
```

I modify this line from my local and build it again, `mpv` is using `@executable_path/lib/libluajit-5.1.2.dylib (compatibility version 2.1.0, current version 2.1.0)` and the OSC works fine.

I can create the PR if you guys are busy

**Comment by jeeb** [comment]
The problem is that macOS is the only one having issues. Blanket heightening the version doesn't really make sense.

**Comment by jnozsc** [comment]
Agree. A dirty solution will looks like
```
        (
            "luajit",
            "luajit >= 2.1.0"
            if ctx.env.DEST_OS == "darwin"
            and tuple(ctx.env.MACOS_SDK_VERSION.split(".")) >= (10, 15, 0)
            else "luajit >= 2.0.0",
        ),
```

**Comment by jnozsc** [comment]
some note before I close this issue:

1. This is an upstream issue from `luajit`
2. `luajit` is totally silent https://github.com/LuaJIT/LuaJIT/issues/563 , so there won't be a bugfix stable release soon
3. There are some activity forks of `luajit`, such as `moonjit` and `luajit2`. I hope `luajit2` could get a stable release. https://github.com/openresty/luajit2/issues/80
4. I commit to `homebrew` https://github.com/Homebrew/homebrew-core/pull/51335 to force it building `mpv` with `lua51`, so that next release of `mpv` won't be broken for people who install it from `homebrew`
5. For people who build the mpv by themselves, please try to use `luajit` >= `2.1.0` if you reproduce this issue.

Thank all
