### ISSUE TITLE
--hwdec=auto together with --gpu-api=vulkan on Windows 8.1 doesn't work properly

### ISSUE THREAD

**Issue by apa420** [mpv-player/mpv#7513]
### Important Information
Provide following Information:
- mpv version
0.32.0-53-g1881698543
- Windows Version
Windows 8.1 64-bit Home, latest version
- Source of the mpv binary
https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20200301-git-e7bab00.7z/download
- If known which version of mpv introduced the problem
No idea
- Possible screenshot or video of visual glitches

![](https://i.nuuls.com/KNjOA.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps
Adding `--gpu-api=vulkan --hwdec=auto` casues this issue. With just `--gpu-api=vulkan` it works as well as with just `--hwdec=auto`.  Only adding them together it displays a mess on screen. My friend tried the exact same settings on windows 10 and did not run into these issues.

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

### Expected behavior
The video displaying properly while using the vulkan api with the proper hardware decoding.
https://i.nuuls.com/xT9w4.mp4
### Actual behavior
It does not display properly.
https://i.nuuls.com/4U6IA.mp4
### Log file
With `--gpu-api=vulkan --hwdec=auto` (Doesn't work)
https://i.nuuls.com/2j_Cb.txt
With `--gpu-api=vulkan` (works)
https://i.nuuls.com/pLe_L.txt
With `--hwdec=auto` (works)
https://i.nuuls.com/6MMZj.txt

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files
Not needed.
Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by philipl** [comment]
What's your goal? When you run with `--hwdec=auto`, it's doing hardware decoding via the `d3d11va` decode API and presenting with `d3d11` which is generally the recommended configuration on windows.

All that said, what you're trying should work - it's using vulkan and then nvdec for decoding, but I've never tried it on windows 8.1

**Comment by apa420** [comment]
I dualboot my pc and tried the exact same setup using arch which worked without issues. So it seems like it's an OS issue or the versions are off.

**Comment by amariami** [comment]
> 
> 
> I dualboot my pc and tried the exact same setup using arch which worked without issues. So it seems like it's an OS issue or the versions are off.

`--vo=gpu`
`--hwdec=auto-copy-safe`
`--hwdec-codecs=all`
`--angle-renderer=auto`                  # d3d9/d3d11/auto 

This might help D3D11 rendering seems enough, not hurt your system rather than Vulkan
`--vo=gpu`
`--gpu-api=d3d11`
`--d3d11-adapter=...`                       # adapter name https://github.com/mpv-player/mpv/wiki/FAQ#windows
`--d3d11-output-format=auto`        # auto/rgba8|bgra8/rgb10_a2/rgba16f
`--d3d11-output-csp=srgb`             # auto/srgb/linear/pq/bt.2020
`--d3d11-exclusive-fs=no`
`--d3d11-sync-interval=1`                # "0" Up to "4", "0" is disabled
`--d3d11-warp=auto`                       # yes/no/auto
`--angle-d3d11-warp=auto`             # yes/no/auto

**Comment by Dudemanguy** [comment]
Really old issue but does anyone happen to know if this is still a problem?

**Comment by Dudemanguy** [comment]
Please open a new issue if this is still a problem on 0.36.
