### ISSUE TITLE
Pls add kbd shortcut for window size zoom

### ISSUE THREAD

**Issue by thinkpanzer** [mpv-player/mpv#7514]
It is common to wind up with a window geometry where 1x size just exceeds a display's size, but 1/2x makes no sense. Currently I manually go to Window>Zoom and the window resizes optimally, but it would be nice to have a kbd shortcut to do this.

### Expected behavior of the wanted feature

When using the kbd shortcut, have the window do the same thing as Window>Zoom.

**Comment by Akemi** [comment]
just add your own `X cycle window-maximized`.
