### ISSUE TITLE
How to Play Video Frames as Fast as I Get Them? No buffering, fps throttling, etc

### ISSUE THREAD

**Issue by mczarnek** [mpv-player/mpv#7517]
I'm streaming video over RTSP and displaying with MPV. Which works great but I need to play back the video at higher speeds. However, MPV seems to always be throttling how quickly the frames are displayed.

I've tried to get around this using the "untimed" property, setting the fps really high plus the no-correct-pts (not that I'm able to set that second flag), and changing the speed property. I've also tried  changing the timestamps of the video frames before I stream them out from the other side over an RTSP stream. Nothing seems to really change it, maybe it'll get a 2x speedup but seems like something is preventing it from going any higher.

I'm running in low latency mode  and with hwdec = auto if that matters.

Any ideas for how I can do this?

Thank you!

**Comment by wm4** [comment]
Disable hwdec, disable vsync, you already tried the other things.

**Comment by mczarnek** [comment]
Thanks wm4, mpvPlayer.API.SetPropertyLong("opengl-swapinterval", 0) and mpvPlayer.API.SetPropertyString("vulkan-swap-mode", "immediate") did the trick. Luckily still using hwdec.
