### ISSUE TITLE
Overrides ignored in SSA file

### ISSUE THREAD

**Issue by g8ecj** [mpv-player/mpv#7518]
### Important Information

Provide following Information:
- mpv version  
     mpv git-2020-03-03-24acddb
- Linux Distribution and Version 
      lubuntu-18.04.3
- Source of the mpv binary  
     ppa:mc3man/mpv-tests
- If known which version of mpv introduced the problem 
     same as mpv_0.27.2-1ubuntu1_amd64.deb
- Window Manager and version 
    LXDE
- GPU driver and version
    intel built-in

### Reproduction steps
Testing with the Ultimate Subtitle SSA file from http://budmansite.com/Subtitle.html against a video file of 3 minutes created using ffmpeg from a single blank jpeg image (so I could read the subtitles)

 - no difference with --no-config

### Expected behavior
VLC works correctly with the same file

### Actual behavior
I find that all override commands are ignored.
\a alignment
\c primary colour
\N new line
Probably others but I can't find any documentation that defines them!

### Log file
Nothing in the log pertaining to the errors

### Sample files
[subdemo.ssa.gz](https://github.com/mpv-player/mpv/files/4309678/subdemo.ssa.gz)

**Comment by Akemi** [comment]
my guess is because of the Shift-JIS encoding.

**Comment by g8ecj** [comment]
That was it - well spotted. I assumed that since the character set was logged correctly, mpv was actually handling it OK. My bad...
Well pleased with it now ;)
