### ISSUE TITLE
FFmpeg reports Error number -138 occurred while playing youtube videos

### ISSUE THREAD

**Issue by snylonue** [mpv-player/mpv#7519]
### Important Information

Provide following Information:
- mpv version 
```
mpv 0.32.0-233-g28ea1ed296 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Mar  8 17:59:18 +08 2020
FFmpeg library versions:
   libavutil       56.42.100
   libavcodec      58.73.102
   libavformat     58.39.101
   libswscale      5.6.100
   libavfilter     7.77.100
   libswresample   3.6.100
FFmpeg version: git-2020-03-07-cb3c77cfe
```
- Windows Version `Win10 1909(18363.693)`
- Source of the mpv binary https://sourceforge.net/projects/mpv-player-windows

### Reproduction steps
Run `mpv "https://www.youtube.com/watch?v=sY3peHvDN8I" --ytdl-raw-options-append=proxy="http://127.0.0.1:1080" --script-opts=ytdl_hook-try_ytdl_first=yes --no-config`

I have to use a proxy, or I can't even visit youtube

With youtube-dl(2020.03.06), I can download the video
```
youtube-dl "https://www.youtube.com/watch?v=kVUfvxVQDUs" --proxy http://127.0.0.1:1080
[youtube] kVUfvxVQDUs: Downloading webpage
[youtube] kVUfvxVQDUs: Downloading video info webpage
[download] Destination: 約束 _ リリィ、さよなら。-kVUfvxVQDUs.f247.webm
[download] 100% of 12.81MiB in 03:19
[download] Destination: 約束 _ リリィ、さよなら。-kVUfvxVQDUs.f251.webm
[download] 100% of 4.81MiB in 00:33
[ffmpeg] Merging formats into "約束 _ リリィ、さよなら。-kVUfvxVQDUs.webm"
Deleting original file 約束 _ リリィ、さよなら。-kVUfvxVQDUs.f247.webm (pass -k to keep)
Deleting original file 約束 _ リリィ、さよなら。-kVUfvxVQDUs.f251.webm (pass -k to keep)
```
I have read some similar issues like unosquare/ffmediaelement#301 and ytdl-org/youtube-dl#18178 and tried to solve it by changing firewall settings but it doesn't work

### Expected behavior

The video can be played

### Actual behavior

FFmpeg reports error

### Log file

https://paste.ubuntu.com/p/T4DnyFTgqF/

### Sample files

Any youtube video like [this](https://www.youtube.com/watch?v=sY3peHvDN8I)

**Comment by garoto** [comment]
Unless something changed recently, IIRC the `youtube-dl` proxy settings don't apply to the ffmpeg http downloader which mpv uses. Try setting a `$https_proxy` var. beforehand.

**Comment by snylonue** [comment]
Yes, it will work if I set an environment variable.

> This is useful for geo-restricted URLs. After youtube-dl parsing, some URLs also require a proxy for playback, so this can pass that proxy information to mpv.
> [cplayer] Set property: file-local-options/stream-lavf-o={"http_proxy":"http://127.0.0.1:1080"} -> 1

I thought the proxy was set by mistake with the manual and log

**Comment by garoto** [comment]
```
[...] and https URLs also bypass the proxy. This is a limitation in FFmpeg.
```
Note that all YT video delivery methods make use of HTTPS nowadays. So yeah, setting a temporary `$HTTPS_PROXY ` env. var seems to be the most straightforward way to deal with this.

Also, and perhaps worth of note, from the [--http-proxy](https://mpv.io/manual/master/#options-http-proxy) manual entry:

```
Proxies are not used for https URLs. Setting this option does not try to make the ytdl script
use the proxy.
```
