### ISSUE TITLE
Possible to (cross)-compile MPV with out of source build folder?  (i.e. do not build in source directory)

### ISSUE THREAD

**Issue by sofakng** [mpv-player/mpv#7520]
Is it possible to leave the mpv source directory untouched and configure/compile to another directory?

For example, the source is located at /usr/local/src/mpv.  

I'd like to create /usr/local/src/builds/win32/mpv and then execute ../../../mpv/waf configure.

However, it complains it can't find wscript in the current directory and I can't figure out a workaround.

**Comment by bitraid** [comment]
You have to use: `../../../mpv/waf -t ../../../mpv/ configure`

**Comment by bitraid** [comment]
Add `-o` to set the build dir.

**Comment by CounterPillow** [comment]
```
$ ./waf --help | grep "build dir"
    -o OUT, --out=OUT   build dir for the project
```
