### ISSUE TITLE
Fallback to PCM if Bitstreaming is not supported

### ISSUE THREAD

**Issue by guys101** [mpv-player/mpv#7527]
I use audio-spdif=ac3,dts,dts-hd,eac3,truehd to let my AV decode dolby atmos, dts, dtsX, it works fine but when I turn off my AV and to use my pc speakers, mpv broke, I need to disable that line for mpv to work with my PC speakers again.

LAV has a solution for this, I just need to enable "Fallback to PCM if Bitstreaming is not supported"

is there something like that in mpv?

**Comment by wm4** [comment]
There is an automatic fallback. If it doesn't work, it probably broke over time.

**Comment by wm4** [comment]
Just tried it with ao_alsa. Still works. Open a proper bug report if you care.
