### ISSUE TITLE
Problem looping a playlist. It loops the video

### ISSUE THREAD

**Issue by CHJ85** [mpv-player/mpv#7530]
Hi there. I have an m3u8 link that stops after a minute. So I tried using --loop in order to continue the stream. This works in VLC. In MPV however, this loops the .ts files within the playlist.
I also tried --loop-file, but with same result.
What would be the proper way to solve this?

**Comment by CounterPillow** [comment]
`--loop-playlist`

**Comment by CounterPillow** [comment]
Oh, and if this is an HLS stream (as in, the m3u8 keeps updating periodically with new MPEG-TS chunks), then m3u8 file opened over http(s) should be recognised as an HLS stream. I'm not sure if `--loop-playlist` will work in that case (i.e. whether it reloads the playlist on each loop). If it's not automatically recognised as an HLS stream, you'll have to manually bludgeon it into treating it as such with `--demuxer-lavf-format=hls
--stream-lavf-o-append="protocol_whitelist=file,http,https,tcp,tls,crypto,hls,applehttp"`

**Comment by CHJ85** [comment]
--loop-playlist worked like a charm.
But is there a way I can pre-cache (or whatever it's called) it so that it transitions more smoothly without the 1 second pause whenever it loops the playlist?

**Comment by CounterPillow** [comment]
https://mpv.io/manual/master/#options-prefetch-playlist

**Comment by CHJ85** [comment]
Thanks a bunch. But in conjunction with --loop-playlist, this skips and overlaps the last 1 or 2 seconds before looping the playlist.
So that's a bit annoying. I'll see if I can find other options.
Thanks again for your help.

**Comment by Shadesss** [comment]
> Thanks a bunch. But in conjunction with --loop-playlist, this skips and overlaps the last 1 or 2 seconds before looping the playlist. So that's a bit annoying. I'll see if I can find other options. Thanks again for your help.

did you ever figure this out?
