### ISSUE TITLE
Update Encoding Instructions to include using shaders

### ISSUE THREAD

**Issue by Tall-Lobster** [mpv-player/mpv#7532]
### Important Information

Provide following Information:
- mpv version: v0.32.0
- Windows and latest version
- github

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

I just can't follow the guide to encode videos using command line with mpv using glsl shaders

### Expected behavior
tutorial with steps to encode video with glsl shader applied

### Actual behavior
no info

### Sample files

help

**Comment by Akemi** [comment]
since this isn't really issue and none was up to the task till now i am closing. everyone is free to add a new wiki page for this.

**Comment by chris1892006** [comment]
How do I encode a video using shaders like Remap 16 235 & Unsharp Mask?

**Comment by haasn** [comment]
Just use `ffmpeg` with vf_libplacebo
