### ISSUE TITLE
mpv probably displays a bit too much information when listening/playing a radio stream

### ISSUE THREAD

**Issue by rubyFeedback** [mpv-player/mpv#7533]
I compiled mpv from source via git clone/checkout and it is working fine.

Now I am listening to BBC radio:

    mpv http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio1_mf_p

This also works fine.

The next two lines are this:

"Compiled without libass.
There will be no OSD and no text subtitles."

And I wonder about this a bit. Is this information necessary? In that case, 
I mean I won't have any OSD or text subtitles anyway since it is a "radio
stream" (oldschool). But even if it were a video, I wonder whether that
notification is necessary.

Perhaps it could be put somewhere else? Like "mpv status" or somewhere
else. To me it does not seem very necessary to display it.

It is a minor issue either way, so no problem if it remains the way it is. But
I am not sure if it makes a whole lot of sense - we as users sort of get
this every time mpv starts up (e. g. plays such an URL stream).

**Comment by wm4** [comment]
You have a broken build.
