### ISSUE TITLE
Console default font size not High DPI aware

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#7534]
The console default font size is not High DPI aware.

https://mpv.io/manual/master/#console-font-size

**Comment by stax76** [comment]
[display-hidpi-scale](https://mpv.io/manual/master/#command-interface-display-hidpi-scale) not being implemented on Windows might be the reason, my rendering settings are mostly defaults.

**Comment by stax76** [comment]
In my frontend I generate a default mpv.conf in case there is no mpv.conf and this now has a fix for the issue.

```
                        Graphics gx = Graphics.FromHwnd(IntPtr.Zero);
                        double scale = GetDeviceCaps(gx.GetHdc(), 88 /*LOGPIXELSX*/) / 96;

                        if (scale != 1)
                            conf = conf.Replace("console-scale=1", "console-scale=" + (int)(1 * scale));

                        gx.Dispose();
```

In another native app of mine code is the same.

```
    HDC screen = GetDC(NULL);
    g_DpiScale = GetDeviceCaps(screen, LOGPIXELSX) / (float)96;
    ReleaseDC(NULL, screen);
```

May I create another issue suggesting implementing High DPI reporting in the Windows default vo?

**Comment by Akemi** [comment]
you can. this issue was closed because you ignored the issue template.
