### ISSUE TITLE
Support _aligned_malloc?

### ISSUE THREAD

**Issue by catcafeplus** [mpv-player/mpv#7535]
wscript only checks for `aligned_alloc` that is not in MinGW.
But MinGW has `_aligned_malloc` that is similar to `aligned_alloc` but with parameter order swapped.
It should be sufficient to just add another check in wscript and more ifdeffery to the code that use it.

**Comment by sfan5** [comment]
`_aligned_malloc` requires allocated memory to be freed with `_aligned_free`, so it's not a drop-in replacement.

**Comment by catcafeplus** [comment]
Yes, it is not a drop-in replacement but it should be possible to support it.
MinGW also has `__mingw_aligned_malloc` and `__mingw_aligned_free`
But that has similar issues like you say.

**Comment by wm4** [comment]
`aligned_alloc()` is specified by C11, which allows use of ``free()``. I don't want to add special exceptions just because Microsoft is retarded.
