### ISSUE TITLE
How do you enable smooth motion in Mac OS?

### ISSUE THREAD

**Issue by thinsoldier** [mpv-player/mpv#7537]
I've tried commands from other github issues but they use --vo=gpu or opengl and those both give fatal errors.

**Comment by xantoz** [comment]
Same as on every platform. Put the following into your mpv config file (usually `~/.config/mpv/mpv.conf`):
```
video-sync=display-resample
interpolation=yes
tscale=oversample
```

**Comment by xantoz** [comment]
Closing because of ignored issue template.
