### ISSUE TITLE
lavf:// or ffmpeg:// protocol, lack of examples

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7539]
I'd like to add a static image with some background music and play it on a loop, as an item in a playlist.

I can easily do this with an ffmpeg command to create a video, but I'd like to be able to do this on-the-fly, within the context of mpv's playlist.

In the documentation there is mention of certain protocols (ie, ffmpeg:// and lavf://) that appear to be capable of doing this, however there are no examples on correct usage.

How can I pass any ffmpeg command via one of these protocols?
Or have I got the wrong idea?

**Comment by hedgehog90** [comment]
bump

Would really like to know how to correctly use these protocols.

**Comment by showermat** [comment]
Funny, I was just wondering the same thing.  I tried copying some examples from the FFmpeg website that work with ffplay, but I can't get them to work with mpv.  I'd appreciate some examples as well.

**Comment by wm4** [comment]
Look at `--lavfi-complex`, which might be somewhere close to what you actually want.
``lavf://`` (and ``ffmpeg://`` which is exactly the same) merely forces use of the libavformat input layer. ``av://`` is somewhat similar (``av://x:y`` is roughly ``ffmpeg -f x -i y`` or something).
