### ISSUE TITLE
Auto set --gpu-context to drm when playing videos in console

### ISSUE THREAD

**Issue by tomyang001** [mpv-player/mpv#7540]
OS: Debian testing. Version: 0.32.0
In console, mpv --gpu-context=auto will show Error: Failed initializing any suitable GPU context! While --gpu-context=drm works fine with hardware decoding. I wish it could auto detect console environment and set --gpu-context to drm. 

If I add gpu-context=drm in mpv.conf, the hardware decoding support will be broken in X11 gui environment. How do I edit the configuration file to make both environments work fine? I wish I can add something like gpu-context=x11egl,drm , which if the first option not working well, set to the second option.

**Comment by kevmitch** [comment]
Unfortunately, `--gpu-context=drm` will reliably crash a simultaneously running xserver when switching back to it. This is documented in #6184. There is currently not a satisfactory fix that does not require mpv gaining root privileges.

For this reason, users must explicitly acknowledge the consequences by adding `gpu-context=drm`.

**Comment by kevmitch** [comment]
see also #4384  #4382 from before the `gpu` refactor
