### ISSUE TITLE
window-scale (Alt-1,Alt-0) ignored.

### ISSUE THREAD

**Issue by DrZingo** [mpv-player/mpv#7541]
Window-scale shortcuts is ignored if previously set, and then manually changed.

- mpv version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects

- Linux Distribution and Version
Arch Linux 5.5.9-arch1-2

- Source of the mpv binary
Arch official package

- Window Manager and version
dwm-6.2

- GPU driver and version
Nvidia official 440.64

### Reproduction steps
Start a video
Press Alt-1 for window-scale:1.0
Resize window manually
press Alt-1

### Expected behavior
Window should resize accordingly to shortcut keys even when window size is changed manually before. 

### Actual behavior
OSD shows window-scale:1.000 but never updates the window size to 1.000

**Comment by Akemi** [comment]
https://github.com/mpv-player/mpv/commit/d07b7f068db56aa5fa7cf16b9d077721ff0a8452

> the "window-scale" property now strictly returns the value of the option,
>        instead of the actual size of the window. The new "current-window-scale"
>        property needs to be queried to read the value as indicated by the current
>        window size. This is a breaking chan

i guess this is an expected behaviour.

i believe this script fixes it: https://gist.github.com/garoto/920b7456d2bdd8f48aa8e7094a12ce47

**Comment by DrZingo** [comment]
How could this be expected, when pressing Alt-0 changes the window to 0.5 and then pressing Alt-1 then works as expected. mpv only sets the window size when another window size was set via keyboard shortcuts.
The script didn't change anything regarding this behaviour
