### ISSUE TITLE
What could cause mpv to play a file added with mode=append

### ISSUE THREAD

**Issue by j-holub** [mpv-player/mpv#7543]
Hey there again,

I have a difference in behaviour from something that should essentially be the same and I tried for hours to get to the gist of it, but I cannot find out what the problem is. Since you seem extremely knowledgable about **mpv** and the code base, it might be, that you happen to know the problem right away.

This code is NodeJs, I'm not sure how familiar you are with it, but even if not, I'm pretty sure you will understand what's going on pretty easily. Basically I start **mpv** in *idle* mode with the options visible in the code, connect to the unix socket and send a `loadfile` command using *append*.  This code works as expected. The file is added to the playlist and **NOT** played, which is expected behaviour. Setting `playlist-pos` to 0, as discussed in #7525 (thanks again) starts playback. So far so good.

```JavaScript
const mpv = spawn('mpv', ['--idle', '--input-ipc-server=/tmp/node-mpv.sock', '--no-audio-display', '--no-video', '--msg-level=ipc=v,cplayer=debug', '--no-config']);

setTimeout(() => {
    const socket = new net.Socket();
    socket.connect({path: '/tmp/node-mpv.sock'}, () => {
        socket.write('{"command": ["loadfile", "somesong.mp3", "append"], "request_id": "dsdfsd"}\n')
    });
}, 1000
```

My NodeJS library does pretty much exactly that in the background, but whenever I do the same things using my library, playback is started immediately. I have tried to only start **mpv** but send the `loadfile` command by hand, either using the NodeJS code above or **socat** from the command line. The result is always the same, playback is started immediately, allthough the mode is set to *append*. Using `--msg-level=cplayer=debug` I looked the message that arives at the **mpv** end over the socket, and in both cases (everything by hand vs using my library) the messages are exactly the same.

I stripped down every option or command I send to **mpv** in my library before calling `loadfile`, it shoud essentially be the exact same thing as the code above, just hidden behind some more convenient function calls. Just spawing **mpv** in *idle* mode and sending a `loadfile` command. Everything should be exactly the same, yet it isn't.

I am well aware, that the problem is most likely on my part, but I have tried for hours and cannot not get to the gist of it. Maybe, from your experience you just know what the problem could be, if not, sorry for wasting your time.

Thanks for doing such a great job maintaining **mpv**

### Log file

https://0x0.st/iaXu.txt

**Comment by wm4** [comment]
Does the behavior change when you wait for 1 second before sending loadfile?

**Comment by j-holub** [comment]
I wait for 1 second to give **mpv** time to start. In my library this is handled by promises, such that the code does not process unless **mpv** is successfully started or could not be started for some reason. 
But this code example works correctly and as expected, it's when I basically do the same thing inside my library (which would be just too much lines of code to ask you to waste your time on). But I start **mpv** the same way, with the same arguments and I send the exact same command. The log file is produced by an instance of **mpv** started by my library. I used `--msg-level=ipc=v,cplayer=debug`, if it helps to submit one using `--msg-level=all=debug` I can do that.

**Comment by wm4** [comment]
2 log files for working/broken might be useful.

**Comment by j-holub** [comment]
There you go:
  * working: https://0x0.st/iaX_.txt
  * *not* working: https://0x0.st/iaXu.txt

**Comment by wm4** [comment]
For some reason, the command in the non-working case is run before mpv is finished loading. So that means your script adds the playlist entry, then after a while mpv finishes loading and enters its main loop, and then sees the playlist is not empty, and thus plays it. mpv can't distinguish this case when the playlist entry was e.g. provided as file argument on the command line.

As you can probably tell by now, a non-empty playlist in idle mode is a strange thing that triggers some corner cases. (Although I'd agree that it shouldn't be.)

Not sure how exactly this should be solved. Suggestions welcome. As a workaround, you could observe the ``idle-active`` property, and send other commands to the player only once it has changed to true (didn't test that idea).

**Comment by j-holub** [comment]
Thanks, I think that got my closer to the problem. So what you're saying is, that I send the `loadfile` command before **mpv** finishes initialising? I just tried waiting a second before sending the first `loadfile` command and I can confirm, that resolves the issue. 

Thanks a lot, I think I can work with that. I will see if I can work `idle-active` idea and report back.. This basically told me that my method that starts the **mpv** process returns before **mpv** is actually started, which is a big problem, good that I discovered that. So far I waited for the `Listening to IPC socket` output on stdout to see if it finished loading. Guess that wasn't enough

**Comment by j-holub** [comment]
Waiting for the `idle` event before resolving the promise solved the problem, code wise it was easier than explicitly observing `idle-active`. According to the docs `idle-active` has been renamed from `idle`. Are you planning to do the same for the `idle` event?

Thanks a lot for your help, I finally got it working.

**Comment by wm4** [comment]
The idle event could happen before your client connects (by chance), so you have a race condition.

**Comment by j-holub** [comment]
I see, so manually polling `idle-active` until it’s true should be the preferred solution?

**Comment by wm4** [comment]
That doesn't sound great. But you could query the property in the beginning, and if it's false, wait for the event.

I'm also considering adding something that adds an explicit state for when idle-active==true and the playlist is not empty. Maybe a force-idle option or so, which would be true when ``idle-active==true && !playlist_empty``, and setting it to false would start playback. But hesitant to make an incompatible change.

**Comment by j-holub** [comment]
Yes I think that would work and is kinda how I thought to do it.

Yes that could be something useful as it might be a common use case. I don’t know how intuitive `force-idle` sounds, I would not have connected it with that circumstance if I heard it. Not finding any better name either though. But you want an actual event to be triggered if the player is idle but the playlist is not empty? Or just a property?

**Comment by wm4** [comment]
I think I fixed your original issue; there was actually a simple trick to make it work as expected (hopefully). You should be able to remove your workaround.

I also added some other stuff, including a command that explicitly starts playback at a playback entry without having to use the playlist-pos property.

**Comment by j-holub** [comment]
That's great to hear :) I will keep the workaround for now, as people don't always use the latest version of mpv, but I will remove it at some point.

Did you already add the new command to the documentation?

**Comment by wm4** [comment]
> Did you already add the new command to the documentation?

Yes.
