### ISSUE TITLE
show-progress shows only 1-2 seconds

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#7544]
https://github.com/mpv-player/mpv/labels/meta%3Afeature-request

It's currently only 1-2 seconds visible, maybe it can be increased to 3-4 seconds or a parameter can be added if it's not too much work.

**Comment by TheAMM** [comment]
Reading the manual can prove useful: https://mpv.io/manual/master/#options-osd-duration

**Comment by stax76** [comment]
Sorry, I read it all the time working on [mpv.net](https://github.com/stax76/mpv.net) but sometimes I miss or forget something.
