### ISSUE TITLE
Can i call osc-chapterlist with toggle mode?

### ISSUE THREAD

**Issue by kesdoputr** [mpv-player/mpv#7545]
Hello, i'm using mpv with a keybind to show chapterlist
**Ctrl+c script-message osc-chapterlist**
Is this possible to let it to a toggle mode? I want to show the list until i press the hotkey again.
I search in manual but it seems only can add a duration sec?

Thanks for your watching.

**Comment by stax76** [comment]
It might not be possible via input.conf without script, with script I guess it can be done.

**Comment by kesdoputr** [comment]
Oh it's sad, i will try to find if there a script can do it.

**Comment by sergeevabc** [comment]
@kesdoputr, have you found a more convenient way to show chapters and jump between them?

**Comment by thebombzen** [comment]
This may sound silly but can you *hide* the script before the duration passes? If so you might be able to set the duration to something stupidly high like 9999999 and then just hide it upon next push, if it's currently showing.

**Comment by Funami580** [comment]
Seems to be possible with a script, just like thebombzen suggested.
```lua
local is_enabled = false

mp.add_key_binding("ctrl+c", "osc-cycle-chapter", function()
    is_enabled = not is_enabled
    mp.command("script-message osc-chapterlist " .. (is_enabled and 31557600 or 0))
end)
```
And in `input.conf`:
```
ctrl+c script-binding osc-cycle-chapter
```
Works perfectly fine for me.

**Comment by Akemi** [comment]
fix/workaround available.

**Comment by Gutter-chan** [comment]
> Seems to be possible with a script, just like thebombzen suggested.
> 
> ```lua
> local is_enabled = false
> 
> mp.add_key_binding("ctrl+c", "osc-cycle-chapter", function()
>     is_enabled = not is_enabled
>     mp.command("script-message osc-chapterlist " .. (is_enabled and 31557600 or 0))
> end)
> ```
> 
> And in `input.conf`:
> 
> ```
> ctrl+c script-binding osc-cycle-chapter
> ```
> 
> Works perfectly fine for me.

This is perfect, thanks for the configs 😍

**Comment by tasnuva1** [comment]
Thank you It works perfectly.
