### ISSUE TITLE
x11->display_is_local is false which leads screen tearing

### ISSUE THREAD

**Issue by wg1989john** [mpv-player/mpv#7546]
### Important Information

Provide following Information:
- mpv version
newest
- Linux Distribution and Version
deepin 15.5
- Source of the mpv binary
github
- If known which version of mpv introduced the problem
not known
- Window Manager and version
dde
- GPU driver and version
not related
- Possible screenshot or video of visual glitches
not related

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

we are doing something like X11VNC server. We create a Xorg server for each remote user. The DISPLAY is always larger than 10. In video/out/x11_common.c file, 
    x11->display_is_local = dispName[0] == ':' &&
                            strtoul(dispName + 1, NULL, 10) < 10;
the display_is_local is false, which leads to use socket, instead of share memory, to trasnfer data to xserver, and then it splits the whole frame to several slices due to the socket packet limit without any sync tech.  Finally, screen tearing happens. 

I think it's not good that display_is_local depends on DISPLAY.

### Expected behavior
display_is_local is true, and screen tearing disappears.

### Actual behavior
display_is_local is false, and screen tearing happens.

### Log file

Make a log file made with -v -v or --log-file=output.txt, paste it to
https://0x0.st/ or attach it to the github issue, and replace this text with a
link to it.

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by wm4** [comment]
That is extremely old code. Do you know a better way to tell whether a display is local?

**Comment by wg1989john** [comment]
The display_is_local is only used to decide whether to use share memory or unix-socket. some code like this:
-    if (vo->x11->display_is_local && XShmQueryExtension(vo->x11->display)) {
-        p->Shmem_Flag = 1;
Why not delete display_is_local and just depends on XShmQueryExtension. The remote Xserver does not support Shm, right?

**Comment by wm4** [comment]
Only if you can confirm that a X server really does not advertise the extension on a remote connection.
