### ISSUE TITLE
'undefined' playlist item on adding a file to playlist?

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7548]
### Important Information
Version: mpv 0.32.0-258-g281f5c63c1
OS: Windows 10

### Reproduction steps

Possibly as a result of updating to the latest version, I now find that whenever I add a file to the playlist - either from the commandline or via an ipc interface - if I then check the playlist property I always have an item with the filename 'undefined'. It has no other properties.
If I try to play 'undefined', it immediately skips to the following file in the playlist.
I can remove the 'undefined' item from the playlist without any issue.
The undefined item is also counted with regards to the playlist-count property.

If I add my files through the commandline, the undefined item is placed after my files in the playlist.
If I add my files using the ipc load method, the undefined item is placed before my files in the playlist.

Firstly - I want to know why this mysterious item is being generated. It seems like a bug or an very unusual quirk... if the latter, what is its purpose? 
Secondly - How do I prevent it from being created in the first place, if that's possible?

**Comment by wm4** [comment]
"undefined" sounds like string conversion from an unset value in a scripting language.

mpv log required.

**Comment by hedgehog90** [comment]
Damn it.
Again, I don't know why I didn't think to check the log. Realised immediately what the problem was.
Spawning the process in a NodeJS script, my arguments array had an extra comma.
Thanks.
