### ISSUE TITLE
Skip loading scripts that don't have the .lua extension

### ISSUE THREAD

**Issue by mustaqimM** [mpv-player/mpv#7549]
- mpv version:
```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Mon Jan 27 15:24:28 UTC 2020
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.2
```
- Platform and Version:
```
Linux void 5.4.26_1 #1 SMP PREEMPT Wed Mar 18 12:43:43 UTC 2020 x86_64 GNU/Linux
```
- Source of the mpv binary
default repo

### Reproduction steps

1. Append `.BAK` to a script file: `~~scripts/skipchapters.lua.BAK`
2. Load a media file.

### Expected behavior
Don't attempt to load a script with the `.BAK` extension. Or anything other than `.lua`

### Actual behavior
An error is thrown showing(the media still plays):
```
Can't load unknown script: /home/mustaqim/.config/mpv/scripts/skipchapters.lua.BAK
```

### Log file

[Log](https://0x0.st/iaMd.txt)

**Comment by wm4** [comment]
That was changed this way. Use a `.` prefix or `.disable` suffix.
