### ISSUE TITLE
sub-scale-with-window still confusingly named and and inaccurate docs

### ISSUE THREAD

**Issue by felagund** [mpv-player/mpv#7551]
This regards the docs available here: https://mpv.io/manual/master/ so I am not following any template. I was told to open a new issue if this still persists: https://github.com/mpv-player/mpv/issues/2224

I do think it persists.

1) The docs for `sub-scale-with-window` say that the option is misnamed. Would it not be better to rename it so that it makes sense? I propose `sub-scale-with-video`, default to `no` and make ``no` behave like `yes` behaves now. So for the end user, nothing would change but it would all make a lot more sense (for example that it is confusing, just see https://github.com/mpv-player/mpv/issues/3158 )

(on a related note, it would then make more sense to rename `sub-scale-by-window` to `sub-scale-with-window` but that would probably break existing setups)

Also:
2)  The docs for `sub-scale-by-window` read:  "If this is disabled, changing the window size won't change the subtitle font size." but that is only true if `sub-scale-with-window` is set to yes. If it is set to `no` and one increases the vertical size of the window displaying the video (while keeping the horizontal size equal), the size of subtitles decreases.

**Comment by wm4** [comment]
I tend to rule this a libass issue. Will have to see. I'd prefer to get rid of all these options, and bind scaling to margins use instead.

**Comment by wm4** [comment]
You can try this (and accompanying mpv branch): https://github.com/libass/libass/pull/384

It makes two of the options no-op, and should generally make the behavior saner. Probably.
