### ISSUE TITLE
Video filters resulting in silent exit when using --o option

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7555]
### Important Information

Provide following Information:
- mpv version: 0.32.0-259-gcdd6eb0994-dirty (latest)
- Windows Version: 10
- If known which version of mpv introduced the problem: Recent git master commit... reverting to cdd6eb0994bc6aeb8aeb0326e5d8c61c06eb38eb is working.

### Reproduction steps

Running the following results in a silent exit before encoding starts:

`mpv pig.mkv --no-config --log-file=mpv.log --of=mpegts --ovc=libx264 --ovcopts=profile=main,preset=veryfast,level=4,crf=20,maxrate=5000k --vf-add=format=yuv420p --vf-add=scale=1280:720 --oac=aac --oacopts=ac=2,b=160k --o=out.mkv`

If I remove the scale filter it works.
Alternatively if I replace it with a pad filter, that also fails.

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/4366252/mpv.log)

### Sample files

pig.mkv:
https://0x0.st/ia4-.mkv

**Comment by wm4** [comment]
Probably fixed by 6169fba79679aff0c4b07fbae03ed30e9f6f7eb6.

**Comment by hedgehog90** [comment]
Fix confirmed.
Thanks!
