### ISSUE TITLE
Keyboard shortcut for scaling?

### ISSUE THREAD

**Issue by catzybluphish** [mpv-player/mpv#7561]
I run mpv with `--video-unscaled=downscale-big` which makes videos play at their resolution without scaling unless it's above the full monitor res. However, sometimes the videos may be too small so I'd rather them scale up to fit my full monitor height (1080) or width (1920). How can I use or make a keyboard shortcut so I can change this on the fly?

**Comment by sfan5** [comment]
`b cycle-values video-unscaled downscale-big no`
will switch between scaling video to window size and not doing so when you press `b`.
