### ISSUE TITLE
Documentation issue only: docs refer to "length" property (which was changed to "duration")

### ISSUE THREAD

**Issue by jaimet** [mpv-player/mpv#7564]
https://mpv.io/manual/stable/#terminal-status-line

says:

The total file duration (absent if unknown) (**length** property)

whereas it should say:

The total file duration (absent if unknown) (**duration** property)

(https://mpv.io/manual/stable/#command-interface-duration explains this change)

HTH (and apologies for not following the issue template - I hope you unserstand why)

**Comment by wm4** [comment]
Actually was fixed by someone in January. There simply hasn't been a new release since then, so docs were not updated (and will not until the next release).
