### ISSUE TITLE
Communicating with LUA script via external interface?

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7572]
I'd like to send commands to a custom LUA script with the utmost immediacy.
What would be the best way to do this? I can't find anything in the documentation relating to this.

I can set mpv properties and use an observe_property listener in the LUA script, but as far as I can tell it's not possible to establish a custom property to do this with.

**Comment by wm4** [comment]
You can use ``script-message-to`` for sending and ``mp.register_script_message`` for receiving.

**Comment by hedgehog90** [comment]
I can't get 'script-message-to' to work via the IPC JSON interface.
I assumed it would work like any other command...
Sending `{"command":["set_property", "pause", false],"request_id":...}` works.
Sending `{"command":["script-message-to", "script", "data"],"request_id":...}` does not work.
I've tried lots of variations, nothing works. mpv says "invalid parameter"
