### ISSUE TITLE
not enough permissions

### ISSUE THREAD

**Issue by s-alfahdawi** [mpv-player/mpv#7575]
➜  ~ sudo mpv --no-video https://www.youtube.com/watch\?v\=lwTDfGxtE8c
Password:
Playing: https://www.youtube.com/watch?v=lwTDfGxtE8c
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
Failed to recognize file format.

Exiting... (Errors when loading file)
➜  ~ mpv https://www.youtube.com/watch\?v\=lwTDfGxtE8c
Playing: https://www.youtube.com/watch?v=lwTDfGxtE8c
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
Failed to recognize file format.

Exiting... (Errors when loading file)
➜  ~ mpv https://www.youtube.com/watch\?v\=lwTDfGxtE8c
Playing: https://www.youtube.com/watch?v=lwTDfGxtE8c
[ytdl_hook] youtube-dl failed: not found or not enough permissions 
Failed to recognize file format.

Exiting... (Errors when loading file)
➜  ~

**Comment by Akemi** [comment]
please open a new issue with the issue templated filled out.
