### ISSUE TITLE
Generating a seekable video stream with a single image + audio in encoding mode (--o=...) within a playlist

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7576]
I have created a video-streaming script that outputs an mpv playlist to single a file or rtmp.
While encoding + streaming I can seek, rearrange the playlist, alter the volume, toggle subtitles, etc. all on-the-fly using a web-interface, and it works almost flawlessly. This is by design.
But with audio files I have an issue.
If I try to stream an audio file, a streaming service will most likely buffer for the duration as there is no video track.
As a workaround I want to show a logo when an audio file plays (within a playlist of mostly videos).
So far, I've managed to implement a lua script that creates a 30fps video stream and adds it to the current item when an audio file is preloaded:

```mp.commandv("video-add", "av://lavfi:color=c=black:s=1920x1080,fps=30[m1];movie=logo.png[m2];[m1][m2]overlay", "auto")```

This generates a never-ending video stream so I need to check 'time-pos' against 'duration' to call the command 'playlist-next'.
This might seem like a really odd way to achieve what I want, but remember mpv is in encoding mode and I've got a playlist of items with varying framerates to consider, so my commandline arguments have to be left pretty broad.

The common sense solutions do not appear to work.
If I add a video stream input with mf:// or edl:// protocols, the encoded output within a playlist is just black, I think because they only produce a single frame of video. If I was encoding a single item then I could use `--demuxer=lavf --demuxer-lavf-o=loop=1 --length=...` as specified [here](https://mpv.io/manual/stable/#options-image-display-duration) to make it work, but in a playlist I can't use these arguments without affecting other items.

There are so many ways to consider solving this (pretty minor) issue...
Perhaps there's a way to add a video stream that is not affected by seek.
Or a way to add a generative video filter on a dummy video track (because generative video filters do not work if there is not a preexisting video track)

Any ideas?
Apologies if this is confusing.

**Comment by thebombzen** [comment]
Have you considered using a custom configuration file, potentially with auto profiles, to enable `--demuxer=lavf --demuxer-lavf-o=loop=1` specifically for audio files?

**Comment by Akemi** [comment]
no reply. if the issue still persists please open a new issue with all the info we ask for.
