### ISSUE TITLE
I can guarantee you are wrong at history. C comes from B language and C++ comes from C and Smalltalk

### ISSUE THREAD

**Issue by expnkx** [mpv-player/mpv#7577]
https://en.wikipedia.org/wiki/BCPL
https://en.wikipedia.org/wiki/B_(programming_language)

Stop being ignorant, I am not your enemy tbh.

In general, fprintf is historically a mistake. Putting the error state into the stream solves nothing. In fact, clearerr for cleaning up EINTR makes things worse. Mistyped formatting fprintf("%s",NULL) is evil.

If you do not check the return code of printf, fprintf, the global errno states will be corrupted and you will never be able to see it again. Even glibc has bugs on fopencookie where it does not report error correctly since they are not doing the right thing.

**Comment by expnkx** [comment]
BTW. But hey, WG14 will add this into the C language and I guess you would love it :)

http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2289.pdf

**Comment by CounterPillow** [comment]
the fuck is this issue supposed to be
