### ISSUE TITLE
Correct way of calling 'script-message' via IPC JSON interface?

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7578]
I can't get or 'script-message' or 'script-message-to' to work via the IPC JSON interface.
I assumed it would work like any other command...
Sending {"command":["set_property", "pause", false],"request_id":...} works.
Sending {"command":["script-message-to", "script", "data"],"request_id":...} does not work.
I've tried lots of variations, nothing works. mpv says "invalid parameter"
'script-message' doesn't work either.

**Comment by avih** [comment]
Log please.

**Comment by hedgehog90** [comment]
Here's the log:

[mpv-2020-04-02-14-54-24.log](https://github.com/mpv-player/mpv/files/4421800/mpv-2020-04-02-14-54-24.log)

The only relevant part is this bit:

```[  17.081][e][ipc_0] Command script-message-to: argument 3 has incompatible type.```

And the 3rd argument (after script-message-to) was an interger.
I tried converting it to a string and it worked.
I guess it only accepts string arguments. It might help others if this was stated in the documentation.
