### ISSUE TITLE
Ways to run a python automated mpv script ONLINE?

### ISSUE THREAD

**Issue by fitipe** [mpv-player/mpv#7580]
Hi there!

I'm running a very basic python script that automatically, and in a loop, writes strings ( such as 'mpv --speed=1.7 --start=45% --length=30 x.mov' ) and drops it into a terminal, calling mpv over and over, changing the parameters every loop.

I need to put this to be run in a website, live and forever. Probably there are many ways to do so, but I have not much programing or web skills to begin find it out by myself. Could any good soul help me through it in these quarantine times?  

Thanks a LOT!

Be healthy, stay at home!

**Comment by fitipe** [comment]
finding* 

( I'm programming in python in a macbook pro from 2011 )

**Comment by Dudemanguy** [comment]
Sorry, but this is for mpv issues. We can't help you with webhosting.

**Comment by fitipe** [comment]
Please - where can I find help with that?
