### ISSUE TITLE
Latest MPV releases not available for eoan

### ISSUE THREAD

**Issue by adigourdi** [mpv-player/mpv#7581]
Not sure where to file release issues, so I'm reporting it here

### Important Information
Provide following Information:
- mpv version **0.30.0**
- Linux Distribution and Version **Ubuntu 19.10 eoan**
- Source of the mpv binary **ppa:mc3man/mpv-tests**

### Reproduction steps
Latest releases 0.31.0 and 0.32.0 not available in ppa for eoan
1. Use latest Ubuntu rolling 19.10 eoan
2. `sudo add-apt-repository ppa:mc3man/mpv-tests`
3. `sudo apt install mpv`
4. `mpv --version`

### Expected behavior
mpv returns version **0.32.0**
or
`sudo apt update` shows there's an update for MPV

### Actual behavior
mpv returns version **0.30.0**
and
`sudo apt update` shows all packages are up to date

### Aditional information
Releases are available/distributed for Ubuntu bionic

**Comment by jeeb** [comment]
Unfortunately mc3man is not part of the development team.

I have set up an Ubuntu VM so I will attempt to make snap builds this week-end. Hopefully that then provides another way of getting releases and nightly builds for mpv.

**Comment by adigourdi** [comment]
Thanks for the quick reply

I'd prefer it if the team provides an official PPA, as I suppose I'm not the only one who doesn't use snaps

**Comment by jeeb** [comment]
I will consider it, but so far it means having multiple generated packages etc which then get built for the separate distros.

Snap let you kind of skip that, as you get the base image integrated, and thus you don't have to build X different builds. Also looking at VLC's figures snap seems to be relatively popular.

**Comment by mc4man** [comment]
As far as I'm concerned these 9 month support releases of Ubuntu are hardly worth much time spent so I will only provide a few builds. 
Maybe eoan gets 1 more build, maybe not as it's a dead dog in a few months anyway.

Anyone else wants to provide builds feel free..

**Comment by adigourdi** [comment]
I suppose 2 builds should be enough
1. for the latest LTS
2. for the latest rolling, which is eoan right now

As of now, I see on the ppa a 0.32.0 build for focal which is scheduled for late April

If I were the publisher I'd prioritize the current stable, then jump to the next when released where users should be upgrading anyway

**Comment by mc4man** [comment]
"If I were the publisher.." , Well your not, as stated I see little value in these point in time interim releases past their dev.
They get from me 2-3 post release updates, no more. In contrast 20.04 already has 10 updates..
Normally I'd already done 1 post release update for 19.10 but as I'm smack dab in the middle of the US's virus hotzone so I've been a little pre-occupied ..  Though plenty of free time now...

A better way to address this would be a LP email request, too late there. I'll put a new build up but not particularly for you..

**Comment by adigourdi** [comment]
It's not for me, it's for all the rolling users who used your ppa

As stated above, there should be either LTS or rolling Ubuntu users, so it'd be 2 builds whatever time of the schedule, I'm not familiar with how the process goes .. so you do you 

And how many updates a release has got, doesn't mean it has more users

Good luck with current events, and thanks for effort
