### ISSUE TITLE
Equivalent of ffmpeg's -shortest flag?

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7583]
I've got a media file with 1 video track and multiple audio tracks.
The first audio track has the same duration as the video track, but every other audio track is 30 seconds longer than the video track duration but contains silence.
With one of these audio tracks selected the last 30 seconds of the media file is darkness and silence.

Also in encoding mode, when the video track ends it produces a bad encoding. If the encoded output is viewed in mpv any point after the video track causes mpv to exit.

fffmpeg's -shortest argument makes it so the end of the file is when the shortest track finishes.
Is there an option in mpv that is equivalent or similar to this? It needs to work on a playlist of media files.

**Comment by wm4** [comment]
No. What do you mean, it needs to work on a playlist? Such a flag would imply that encoding is aborted as soon as any of the streams end, i.e. the rest of the data of all other streams is discarded.

**Comment by hedgehog90** [comment]
I meant if there is an upcoming item in the playlist and a track in the current item finishes, skip to the next item in the playlist.

**Comment by hedgehog90** [comment]
Alternatively, is there a way to monitor mpv for the first track that reaches 'eof' so I can implement my own workaround?

**Comment by wm4** [comment]
I don't think there's API for that.

**Comment by hedgehog90** [comment]
May I suggest adding an 'eof-track' or 'end-track' event  for this?

**Comment by wm4** [comment]
Could probably add separate properties for video/audio that roughly equal to ``eof-reached``.

**Comment by wm4** [comment]
PS: and the fundamental problem with this is that audio and video will always and at slightly different times (if only due to different buffering), all while you don't know how much of the other track is really still available, so I doubt this is really useful?

**Comment by hedgehog90** [comment]
I'm aware of that, but I still think an event could be useful information.

The heart of the problem lies in the fact that if I'm encoding one of these media files with significantly mismatching audio / video stream durations in mpv, then it results in a bad encoding. If I play the output muxed into an mkv container in mpv it appears to pause at the end of the video. if I seek past this point then mpv closes. Similarly if I'm streaming to an rtmp server, the video playback on the site begins buffering when the video track ends.

I'm acting under the assumption that if I unload the file after the video track ends quickly enough (by detecting the event in the LUA api) then I won't encounter this issue.

**Comment by Akemi** [comment]
if the issue still persists please open a new proper issue the all the info we ask for.

**Comment by hedgehog90** [comment]
Since submitting this issue I wrote a boolean option '--end-on-eof' for my fork. With it enabled mpv will move onto the next playlist item as soon as the first eof in any stream is detected.
Let me know if I should submit a pull request with this feature, I've found it very useful.

**Comment by Akemi** [comment]
same as the other closed issue, it probably is the best to open a PR for it. we can discuss the details there.
