### ISSUE TITLE
lavfi-complex can't working

### ISSUE THREAD

**Issue by NeilTohno** [mpv-player/mpv#7584]
mpv-x86_64-20200329-git-bca917f

`MPV.exe --config-dir="C:\ZHD_PG\mpv\portable_config" "Y:\t1\01.avi" --external-file="Y:\t1\01.rmvb" --lavfi-complex='[vid1] scale=1280x720 [vid1_scale]; [vid2] scale=1280x720 [vid2_scale]; [vid1_scale][vid2_scale] hstack [vo]'`

I don't kown how to write the code, ⊙﹏⊙

https://pastebin.com/YwK0LYR3

https://github.com/mpv-player/mpv/issues/4962

`C:\ZHD_PG\mpv\MPV.exe "Y:\t1\01.avi" --external-file="Y:\t1\01.rmvb" --lavfi-complex="movie=\'Y:/t1/01.avi\'[vid1]; movie=\'Y:/t1/01.rmvb\'[vid2] scale=1280x720 [vid2_scale]; [vid1][vid2] hstack [vo]'`

Thanks.

**Comment by mia-0** [comment]
The closing quote (') doesn’t match the opening quote (") on your last command line argument.

(I don’t remember how escaping works in Windows’ command shell, though, so fixing the quotes might not be enough.)

**Comment by EzeKees** [comment]
Change the ' to double quote ""

Its works:
MPV.exe --config-dir="C:\ZHD_PG\mpv\portable_config" "Y:\t1\01.avi" --external-file="Y:\t1\01.rmvb" --lavfi-complex="[vid1] scale=1280x720 [vid1_scale]; [vid2] scale=1280x720 [vid2_scale]; [vid1_scale][vid2_scale] hstack [vo]"
