### ISSUE TITLE
hwdec: issue into vaapi stack

### ISSUE THREAD

**Issue by eblanca** [mpv-player/mpv#7585]
I use to build mpv with the script mpv-build, including ffmpeg also.
Yesterday on my laptop with intel i5 6200u I updated the whole vaapi stack made of: libva, gmmlib, media-driver and Media-SDK, each to latest git master (early some were "vanilla" from my distribution repositories but I don't remember which ones). Then, I re-built mpv including latest ffmpeg from branch 4.2.
Now, I see enabling de-interlace when using hardware decoding doesn't work anymore; instead previously when something in that software stack was older, de-interlacing used to work anyways.

My ffmpeg_options is
```
--enable-pic
--disable-debug
--enable-postproc
--enable-gpl
--enable-libdrm
```

and mpv_options is
```
--disable-debug-build
--enable-dvdnav
--enable-sdl2
--enable-dvbin
--enable-cdda
--enable-vaapi
--enable-libmpv-static
```

The full mpv log is here: https://0x0.st/iuSN.log
and in particular those statements:

```
[ffmpeg] AVHWFramesContext: Failed to read image from surface 0x4000015: 20 (the requested function is not implemented).
[hwdownload] Could not copy hardware frame to CPU memory.
[ffmpeg] mpv_src_default_in: w:1920 h:1080 pixfmt:vaapi_vld tb:1/1000000 fr:25/1 sar:1/1 sws_param:
[ffmpeg] auto_scaler_0: w:iw h:ih flags:'bilinear' interl:0
[ffmpeg] filter: auto-inserting filter 'auto_scaler_0' between the filter 'mpv_src_default_in' and the filter 'filter'
[ffmpeg] Impossible to convert between the formats supported by the filter 'mpv_src_default_in' and the filter 'auto_scaler_0'
[lavfi] failed to configure the filter graph
[vf] Disabling filter userdeint because it has failed.
```

I'm sure those are telling me the root cause is into some component ffmpeg is leveraging on but I can't understand what they say. My wish is pick the piece (library? driver?) causing this and file a bug report but I don't know where to look at.
Thank you.

**Comment by Doofussy2** [comment]
You probably need to use --hwdec=vaapi-copy

**Comment by eblanca** [comment]
Same failure: https://0x0.st/iuDw.txt
In particular, you can see more statements as above "[ffmpeg] AVHWFramesContext..."

**Comment by Lawstorant** [comment]
Something is wrong. vaapi no longer works under Arch linux. MPV uses vaapi-copy which is useless

**Comment by YoyPa** [comment]
@Lawstorant you can fix vaapi-copy by downgrading intel-media-driver to 19.4.0
https://archive.archlinux.org/packages/i/intel-media-driver/

**Comment by eblanca** [comment]
Fixed by removing any updated packages.
I just stay with stock versions from debian and deinterlace now works again with and without hardware decoding.
