### ISSUE TITLE
Unexpected crash on waking from sleep

### ISSUE THREAD

**Issue by maurocolella** [mpv-player/mpv#7587]
### mpv version and platform
mpv version: current master
Platform: 
Manjaro Linux 19.0.2
Kernel 5.5.13-1
64 bits
KDE Desktop with 
Qt: 5.14.1
KDE Frameworks: 5.68.0

### Reproduction steps
Playback on external display (connected via Nvidia/HDMI), in windowed mode.
Leave the devices idle for several minutes for the system to go to sleep.
Wake the desktop up to find that mpv has crashed. Sound output, through pulseaudio, also crashes. Pulseaudio must be restarted for the default sound output (HDMI) to be restored.

### Expected behavior
Playback window remains intact after waking up.

### Actual behavior
Playback window crashes.

**Comment by mia-0** [comment]
A log file would be useful, a gdb stack trace even more so. It does sound like an issue with NVIDIA’s driver, though, and there is probably nothing we can do about this.

**Comment by maurocolella** [comment]
Okay, I will do my best to get back with some logs.

**Comment by maurocolella** [comment]
So I finally got around to collecting some logs. It should be noted that `pulseaudio -k` by itself doesn't cause mpv to crash.

As for my mpv.conf, if that is relevant:
```
save-position-on-quit
sub-auto=fuzzy
osc=no
autofit=100%

profile=gpu-hq
gpu-api=vulkan

hdr-compute-peak=no
tone-mapping=hable
tone-mapping-param=0.5
target-peak=100
tone-mapping-desaturate=1.0
target-prim=bt.2020

hls-bitrate=max 						# Use max quality for HLS streams
icc-profile-auto
dither-depth=auto						# Enable dithering
hwdec=auto								# Enable hardware decoding if available. 
no-hidpi-window-scale

geometry=3840x2160						# Force 4k resolution output
scale=ewa_lanczossharp 					# Luma upscale
dscale=sinc 							# Luma downscale
cscale=ewa_lanczossharp					# Chroma upscale

# Debanding
# For opengl-hq, debanding is enabled by default
# deband=no 							# Deactivate debanding
deband-iterations=1 					# Deband steps (More = Better quality, but higher GPU cost)
deband-threshold=70 					# Deband strength (More = Less banding, but more detail loss)
deband-range=16 						# Deband range (More = Less banding, but higher GPU cost)
deband-grain=5 							# Dynamic Grain (More = More dynamic grain)


# Interpolation
interpolation=yes						# Enables motion interpolation
video-sync=display-resample				# Required if you enable interpolation
tscale=sinc								# Interpolation
```

I am also using a shader called "Anime4K", per-resolution, such as:
```
[full-hd]
# 1920x1080 (HDTV, Blu-ray)
profile-desc=cond:get('width', -math.huge) == 1920
glsl-shaders="~~/shaders/Anime4K_Adaptive_v1.0RC2.glsl"
```

**Comment by wm4** [comment]
The fix is probably removing vdpau from autoprobing.

**Comment by maurocolella** [comment]
As in `hwdec=no`?

I just tried. It doesn't appear to fix it, but the log and result are different.

```
[mpv_thumbnail_script_client_osc] The 'tracks-changed' event is deprecated and will be removed.
 (+) Video --vid=1 (*) (hevc 1920x1080 23.976fps)
 (+) Audio --aid=1 (*) (aac 6ch 48000Hz)
 (+) Subs  --sid=1 (*) (subrip)
[auto_profiles] Applying profile full-hd 
AO: [pulse] 48000Hz 5.1 6ch float
VO: [gpu] 1920x1080 yuv420p
[vo/gpu] Could not retrieve an ICC profile.
[mpv_thumbnail_script_client_osc] The 'tick' event is deprecated and will be removed.

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).

Saving state.

Exiting... (Quit)
```

This time around, I didn't pause before going to sleep. Once the computer was up again, sound picked up, but the picture didn't show (the window displayed garbage). In both instances I had to kill in order to exit.

**Comment by wm4** [comment]
That's probably a driver issue and nothing we can do about. Complain to Nvidia.

**Comment by maurocolella** [comment]
Ok, thanks. Will do. To the tune of "Blame Canada" ^_^

**Comment by wm4** [comment]
By the way, when I still used nvidia and software suspend, resuming normally worked, but all FBOs were corrupted. This could be fixed by unpausing or so. But in general it survived.

**Comment by maurocolella** [comment]
Ok, thanks. The window becomes unresponsive for me. It's not any kind of critical fault. Could it be that transfer over HDMI compounds the issue?

In any event: I have raised an issue with NVIDIA.
https://forums.developer.nvidia.com/t/hardware-video-decoding-crashes-on-resuming-from-sleep/122546

**Comment by Dudemanguy** [comment]
Is this still a problem?

**Comment by maurocolella** [comment]
@Dudemanguy I have switched back to Ubuntu fwiw, but thankfully it doesn't seem to be. A lot of the problems with both Nvidia drivers on Linux and pulseaudio are resolved.

I am still on KDE/X11 fwiw.

I have carried my full mpv config along. It's a slightly modified version of: https://github.com/classicjazz/mpv-config

I have to say that the overall rendering quality is stunning. Fwiw.

**Comment by Dudemanguy** [comment]
Good to hear. I'll go ahead and close this for now.
