### ISSUE TITLE
Lua: adding a path to playlist?

### ISSUE THREAD

**Issue by 097115** [mpv-player/mpv#7589]
With this lua command I can append an URL to the end of the current playlist -- and then play it:

    -- myURL being something like https://some.site/playlist.m3u
    mp.commandv("loadfile", myURL, "append-play")

And it works just great. However, if i try appending not an URL but a file path (like `/Users/me/Documents/movie.mp4`), it does add but after switching to it, just quits.

If after adding this entry to the playlist, I save the playlist , the added entry does look just like the regular entry there, nothing hints it can be treated mistakenly. So, why does it crashes then? Do I need some guards there? Or may be to escape it somehow?

Thank you.

macOS 10.11.6, mpv 0.32.0

**Comment by kevmitch** [comment]
We're going to need a log to know what's happening. We can't know why it "crashes" if we don't even know what that means.
