### ISSUE TITLE
Error parsing option script (option not found)

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7590]
### Important Information

Provide following Information:
mpv version: 0.32.0-259-gcdd6eb0994-dirty
Ubuntu 16.04

### Reproduction steps

I'm simply trying to start mpv with a --script argument and I can't get it to work.
On Windows with the same mpv build version and the same lua script it works, but not on Ubuntu.
Thought it might be the file permissions for the script file, so I set it to 775 and made sure the owner was correct.

Any lua script has the same issue. I've tried an empty lua file and I still get the error.
The log says 'option not found'. Is my mpv build missing LUA support?

```
[   0.005][v][cplayer] Setting option 'log-file' = 'logs/mpv-2020-04-07-00-35-01.log' (flags = 8)
[   0.005][e][cplayer] Error parsing option script (option not found)
[   0.005][f][cplayer] Setting commandline option --script=/home/delete/web/cabtv.co.uk/nodeapp/cabtv.lua failed.
[   0.005][i][cplayer] Exiting... (Fatal error)
```

[mpv-2020-04-07-00-35-01.log](https://github.com/mpv-player/mpv/files/4441429/mpv-2020-04-07-00-35-01.log)

EDIT:

Assuming I didn't have LUA enabled, I installed luajit.
I then added --lua=luajit to my mpv_options file in mpv-build

But on rebuilding I still got this message:

`Checking for Lua                                                          : no ('luajit >= 2.0.0' not found)`

And yet I have LuaJIT 2.0.4 installed.

**Comment by avih** [comment]
> `List of enabled features: aligned_alloc asm build-date cplayer cplugins debug-build ffmpeg glibc-thread-name glob glob-posix gpl iconv libass libavdevice libdl libm librt linux-fstatfs optimize oss-audio posix posix-or-mingw posix-spawn posix-spawn-native pthreads stdatomic vt.h zlib`

Your build is without lua support.

**Comment by hedgehog90** [comment]
Well that was helpful.

**Comment by avih** [comment]
> `Checking for Lua : no ('luajit >= 2.0.0' not found)`

If you insist on luajit, you should try with luajit 2.1 (beta). 2.0.x is fairly old. Otherwise you should try lua 5.2, and if you can't then lua 5.1 .

I'm not sure if luajit 2.0.x is really supported. It's also possible that its pkg-config file is missing at your system.

**Comment by hedgehog90** [comment]
Realised I needed to install libluajit-5.1-dev
Works now.
It would be helpful to mention this in the mpv-build README.

**Comment by jnozsc** [comment]
related with https://github.com/mpv-player/mpv/issues/7512
