### ISSUE TITLE
provide replacement for deprecated input-file option

### ISSUE THREAD

**Issue by schmorp** [mpv-player/mpv#7592]
### Expected behavior of the wanted feature

Currently, --input-file=fd://x is a simple and safe way to bring mpv
into slave mode for programs (e.g. with a unix domain socket). It's simple because all you need is to call socketpair, and it is safe because the communication is restricted to processes having direct access to the file descriptor- calling socketpair and executing mpv in a child process makes it easy to control access.

Unfortunately, this option is now deprecated, and there is no replacement with similar functionality.

The closest is --input-ipc-server, but this is programmatically many times harder to use: you need to find a safe place for the socket, e.g. by creating a temp directory, get permissions correct and so on - history has shown that programmers often get this wrong resulting in security issues).

### Alternative behavior of the wanted feature

An alternative option to pass an fd would be fine, too, of course, but would needlessly break compatibility with all programs embedding mpv and using --input-file.

### Log file

> Even if you think it's not necessary at first, it might help us later to find

I really don't know what log to provide for this case.

**Comment by wm4** [comment]
Wouldn't mind providing an option that takes a socket FD, as long as it doesn't have to work on Windows.

**Comment by schmorp** [comment]
I think windows is different enough w.r.t. embedding and remote controlling mpv that only having this option on systems supporting unix domain sockets wouldn't be an issue for programs.
