### ISSUE TITLE
Replacement for --tv-width/--tv-height options

### ISSUE THREAD

**Issue by kshpytsya** [mpv-player/mpv#7594]
### Important Information

Provide following Information:
- mpv version: 0.32.0
- Platform and Version: Gentoo Linux

### Reproduction steps

Before `tv://` has been removed, I used the following command line to open the laptop's built-in webcam as a mirror replacement:

```sh
mpv tv:// --vf=hflip --tv-device=/dev/video0 --tv-width=1280 --tv-height=720
```

Note the `--tv-width`/`--tv-height` options used as recommended in https://github.com/mpv-player/mpv/issues/3850.

Now, per man page, I use:

```sh
mpv --vf=hflip av://v4l2:/dev/video0 --profile=low-latency --untimed
```

which produces a low-res 640x480 stream.

### Expected behavior

There should be a documented replacement for the dropped `--tv-width`/`--tv-height` options. 

### Actual behavior

I find no documented way to specify v4l options.

**Comment by CounterPillow** [comment]
https://github.com/mpv-player/mpv/wiki/Video4Linux2-Input

What of this should be in the docs itself rather than the wiki is up for debate I guess.

**Comment by Akemi** [comment]
since the question was answered and there shouldn't be an issue any more, closing.
