### ISSUE TITLE
Build fail with latest Command_Line_Tools_for_Xcode_11.4.

### ISSUE THREAD

**Issue by Tsukimeizi** [mpv-player/mpv#7598]
### Important Information

Provide following Information:
- mpv version
git master

- macOS Version
10.15.4 (19E287)

- Source of the mpv binary or bundle
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches
git master

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

./waf install

### Actual behavior
see log fle
[mpv.log](https://github.com/mpv-player/mpv/files/4457574/mpv.log)

### Log file

Make a log file made with -v -v or --log-file=output.txt. If you use the Bundle
from a version later than 0.32 a default log is created for your last run at
~/Library/Logs/mpv.log. You can jump to that file via the Help > Show log File…
menu. Paste the log to https://0x0.st/ or attach it to the github issue, and
replace this text with a link to it.

In the case of a crash please provide the macOS Crash Report (Backtrace).

The issue will be closed for ignoring the issue template.

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

**Comment by Tsukimeizi** [comment]
Update to Command_Line_Tools_for_Xcode_11.4.1, build successfully now.

**Comment by Akemi** [comment]
great, so it was an upstream issue after all.
