### ISSUE TITLE
edl: support vf/af parameter

### ISSUE THREAD

**Issue by m45t3r** [mpv-player/mpv#760]
I don't know if this is possible already (but looking at DOCS/edl-mpv.rst, it doesn't seem so), it would be interesting to support passing filtering parameters to edl entries. Something like this:

```
# mpv EDL v0
# Oh god, this file is interlaced
interlaced-file.mkv,10,20,vf=yadif
# Need to remove crappy TV logo
late-anime-show.mkv,vf=delogo
# Better show my uber encoding skills
serie.mkv,vf=unsharp
```

So we could have a poor man's Avisynth/Vapoursynth on mpv without additional dependencies.

**Comment by wm4** [comment]
Cute idea, but effectively rejected. Don't need more complexity for really obscure things.
