### ISSUE TITLE
Macos10.12.1 can not upgrade mpv

### ISSUE THREAD

**Issue by exxfzc** [mpv-player/mpv#7601]
zilingdeMacBook-Pro:~ ziling$ brew upgrade mpv
Warning: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.

==> Upgrading 1 outdated package:
mpv 0.29.1_1 -> 0.32.0
==> Upgrading mpv 0.29.1_1 -> 0.32.0 
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or
https://developer.apple.com/download/more/.

==> Installing dependencies for mpv: openjdk, ant, libbluray, libsoxr, libvidstab, libogg, libvpx, opencore-amr, jpeg, libtiff, openjpeg, opus, rtmpdump, flac, libsndfile, libsamplerate, rubberband, sdl2, snappy, speex, autoconf-archive, libtool, giflib, webp, leptonica, tesseract, x264, x265, xvid, ffmpeg, libb2, lz4, zstd, libarchive, mujs, uchardet, zimg, vapoursynth and youtube-dl
==> Installing mpv dependency: openjdk
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or
https://developer.apple.com/download/more/.

==> Downloading https://hg.openjdk.java.net/jdk-updates/jdk13u/archive/jdk-13.0.
Already downloaded: /Users/ziling/Library/Caches/Homebrew/downloads/1124b500fc261f6d9be6193eca8c120f4dfb7ecd3470ac7d8edc1d04ecc5b345--jdk13u-jdk-13.0.2+8.tar.bz2
==> Downloading https://download.java.net/java/GA/jdk12.0.2/e482c34c86bd4bf8b56c
Already downloaded: /Users/ziling/Library/Caches/Homebrew/downloads/0c063c1db55c4b1323810e59dca242bbd1bedc828894003511e13362cc81291b--openjdk-12.0.2_osx-x64_bin.tar.gz
==> ./configure --without-version-pre --without-version-opt --with-version-build
Last 15 lines from /Users/ziling/Library/Logs/Homebrew/openjdk/01.configure:
checking for /mnt/c/Windows/System32/cmd.exe... no
checking build system type... x86_64-apple-darwin16.1.0
checking host system type... x86_64-apple-darwin16.1.0
checking target system type... x86_64-apple-darwin16.1.0
checking openjdk-build os-cpu... macosx-x86_64
checking openjdk-target os-cpu... macosx-x86_64
checking compilation type... native
checking for top-level directory... /private/tmp/openjdk-20200410-10035-ntedps/jdk13u-jdk-13.0.2+8
checking if custom source is suppressed (openjdk-only)... no
checking which debug level to use... release
checking which variants of the JVM to build... server
checking for sdk name... 
configure: error: No xcodebuild tool and no system framework headers found, use --with-sysroot or --with-sdk-name to provide a path to a valid SDK
/private/tmp/openjdk-20200410-10035-ntedps/jdk13u-jdk-13.0.2+8/build/.configure-support/generated-configure.sh: line 82: 5: Bad file descriptor
configure exiting with result code 1

Do not report this issue to Homebrew/brew or Homebrew/core!

These open issues may also help:
openjdk 14 https://github.com/Homebrew/homebrew-core/pull/51883
openjdk@11/11.0.6 symlink libjli.dylib broken https://github.com/Homebrew/homebrew-core/issues/51150

Error: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.

Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or
https://developer.apple.com/download/more/.

==> Checking for dependents of upgraded formulae...
==> No dependents found!

**Comment by avih** [comment]
mpv is still supposed to work on 10.12, however, nothing at your log is related to mpv. I don't get why brew tries to install java for mpv - mpv doesn't use java.

You should talk to the brew people, or try to build mpv yourself.

**Comment by ePirat** [comment]
This is unrelated to mpv, it fails to install OpenJDK which is needed for libbluray Java Menus. Not sure if thats even needed at all as I have no idea if mpv even supports that.

> configure: error: No xcodebuild tool and no system framework headers found, use --with-sysroot or --with-sdk-name to provide a path to a valid SDK

Regarding this error, verify you can run `xcodebuild` and `xcrun` successfully.

**Comment by Akemi** [comment]
sry, that is not our issue. it's entirely a homebrew problem. our CI build also build on 10.12, i made sure of it.

**Comment by Argon-** [comment]
Well, as your log says:

    Error: You are using macOS 10.12.
    We (and Apple) do not provide support for this old version.

Homebrew doesn't support 10.12 so you can't open a ticket there. But it is their problem (or rather, the problem of one of their formulas).
It isn't a mpv problem though. mpv works on 10.12 and needs no Java.

**Comment by exxfzc** [comment]
Thanks a lot!

**Comment by dotysan** [comment]
This bug is related to installing openjdk with --build-from-source since there is no longer bottles for 10.12/Sierra. Building openjdk requires the full Xcode--not just the command-line tools. Not sure why.

The solution is to make sure you have the full Xcode installed, then run `sudo xcode-select -s /Applications/Xcode.app` to activate it. Now the openjdk configure script won't error out.
