### ISSUE TITLE
MPV Read Wrong Tag

### ISSUE THREAD

**Issue by Sekkei** [mpv-player/mpv#7604]
MKV; Tags.xml/dtd
```
<?xml version="1.0"?>
<!-- <!DOCTYPE Chapters SYSTEM "matroskachapters.dtd"> -->
<Tags>
	<Tag>
		<Targets>
			<TargetTypeValue>60</TargetTypeValue>
		</Targets>
		<Simple>
			<Name>TITLE</Name>
			<String>A</String>
		</Simple>
	</Tag>
	<Tag>
		<Targets>
			<TargetTypeValue>70</TargetTypeValue>
		</Targets>
		<Simple>
			<Name>TITLE</Name>
			<String>B</String>
		</Simple>
	</Tag>
</Tags>
```

MPV reads the MKV Title tag as "B", but it should be "A" or atleast "A - B" but never "B" only
( e.g if. B would be the season, A would be the episode )

**Comment by wm4** [comment]
Missing context, sample files, etc. - sorry, I won't try to figure out what you're trying to say with just what was given.

**Comment by Sekkei** [comment]
The sample code IS the file in question? Just add it as xml to any mkv (with mkvtoolnix) and look at it in mpv. You will see the above described observation
"MPV reads the MKV Title tag as "B", but it should be "A" or atleast "A - B" but never "B" only"

**Comment by wm4** [comment]
I don't care. You analyzed it, created a sample file, etc., now you want me to the same and don't even provide details? Got better stuff to do.

**Comment by Sekkei** [comment]
Okay sorry, what info's would someone need to identify the error? But I think we misunderstood each other, the problem could be that mpv actually didn't read attached tags in mkv container? Or If should do it, changing the displayed ui output could help here. I do not know the code or anything about c++, so I can only report bugs or miss behavior. I clearly see the irrelevance's of this problem, but nonetheless, it's a flaw.

**Comment by haasn** [comment]
> Okay sorry, what info's would someone need to identify the error?

He's asking you to provide a sample file and mpv command line that can be used to recreate the error.

**Comment by wm4** [comment]
That, and an explanation why it's supposed to be wrong.
I know that mkvtoolnix takes XML for tags, but it's stored as EBML in the file, so I don't recognize much.

**Comment by Sekkei** [comment]
> He's asking you to provide a sample file and mpv command line that can be used to recreate the error.
https://www.mediafire.com/file/6qomsgj95p9i9zn/i-really-like-you-nawn-vlog-background-music-no-copyright-chill-royalty-free-music-instrumental.mkv/file
I downloaded royality free music, and repacked it with an xml 
Open it in MPV and press  the 'i' key for informations with the default shortcuts

**Comment by wm4** [comment]
Done, still don't know whatever the hell this is about, but whatever.
