### ISSUE TITLE
Provide a variable containing the original playlist url

### ISSUE THREAD

**Issue by Earnestly** [mpv-player/mpv#7605]
I have benefited since the addition of `write-filename-in-watch-later-config` as it allows me to keep track of the various youtube based playlists I've watched.

Another useful feature for me is the ability to reload a stream via the console using `loadfile ${path}` along with `write-watch-later-config` without having to quit mpv with `Q`.

The trouble I have is that the value of `${path}` refers to the current stream url and not the original playlist url provided.

Given that mpv appears to have knowledge of this original url, such that it can be written to the watch later config, is there perhaps a way to expose this with a variable like `${path}`?

The rationale for wanting this is that on occasion I have left a long video paused and only so much of it is buffered.  When that buffer runs out the video ends instead of attempting to request the rest from youtube (twitch doesn't seem to have this problem).

In such cases I would like to write a watch later config and then `loadfile ${path}` to reload the stream and have it continue where it left off without having to quit mpv, find the original playlist url, and start mpv with it once again.

If there is a better way of handling this situation I'd welcome any suggestions.

**Comment by Earnestly** [comment]
Hm, I didn't know labels were applied like this.  This is a feature request and not `os:linux`, sorry about that.

**Comment by garoto** [comment]
I use a variation of the below lua that writes everything the player tries to open to a  log file with contents like this: https://i.imgur.com/U654h2J.png

```lua
mp.add_hook("on_load", 20, function()
	local history = mp.command_native({"expand-path", "~~home/mpvhistory.log"})
	local title, logfile

	title = mp.get_property("media-title")
	title = (title == mp.get_property("filename") and "" or ("(%s)"):format(title))

	logfile = assert(io.open(history, "a+"))
	logfile:write(("[%s] %s %s\n"):format(os.date("%d/%b/%y %X"), mp.get_property("path"), title))
	logfile:close()
end)
```
