### ISSUE TITLE
visualizer background

### ISSUE THREAD

**Issue by peter-kl** [mpv-player/mpv#7614]
Information:
- mpv version : **1:0.32.0-3**
- Linux Distribution and Version: arch
- Window Manager and version: Xfce
- Possible screenshot or video of visual glitches
[imgur](https://i.imgur.com/LgaJCoT.png)
- Log: no errors
- Cmmd: 
_mpv --lavfi-complex='[aid1] asplit [ao] [v] ; [v] showwaves=mode=line:split_channels=1 [vo]' 'some file.mp3'_

- Question: How can I keep the black background with this visualizer - only audio?
Thanks!!

**Comment by richardpl** [comment]
mpv --lavfi-complex='[aid1] asplit [ao] [v] ; [v] showwaves=mode=line:split_channels=1,format=rgb0 [vo]' 'some file.mp3'

**Comment by Akemi** [comment]
on a side note: the log is not just there for errors. it gives us important informations, so don't just leave it out.

**Comment by peter-kl** [comment]
Thanks!!
[imgur-01](https://i.imgur.com/XgDS4VH.png)
[imgur-02](https://i.imgur.com/GURHehm.png)
[imgur-03](https://i.imgur.com/18glQ7l.png)
Great job.
