### ISSUE TITLE
mpv desynchronisation error after pausing/unpausing when using jack

### ISSUE THREAD

**Issue by Le-Brut** [mpv-player/mpv#7616]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.2
```
- Linux Distribution and Version
Arch Linux
- Source of the mpv binary
Arch official repository (community), through pacman
- Window Manager and version
i3 version 4.18 (2020-02-18)
- GPU driver and version
```
local/xf86-video-intel 1:2.99.917+899+gf66d3954-1 (xorg-drivers)
    X.org Intel i810/i830/i915/945G/G965+ video drivers
```

These may be relevant:

- jack version
```
local/jack2 1.9.14-1
    C++ version of the JACK low-latency audio server for multi-processor machines
```
- alsa version
```
local/a2jmidid 9-1 (pro-audio)
    A daemon for exposing legacy ALSA sequencer applications in JACK MIDI system.
local/alsa-lib 1.2.2-1
    An alternative implementation of Linux sound support
local/alsa-plugins 1.2.2-1
    Additional ALSA plugins
local/alsa-topology-conf 1.2.2-2
    ALSA topology configuration files
local/alsa-ucm-conf 1.2.2-1
    ALSA Use Case Manager configuration (and topologies)
local/alsa-utils 1.2.2-1
    Advanced Linux Sound Architecture - Utilities
local/lib32-alsa-lib 1.2.2-1
    An alternative implementation of Linux sound support (32 bit)
local/zita-alsa-pcmi 0.3.2-2
    The successor of clalsadrv, provides easy access to ALSA PCM devices.
```

- jack config

Since everything worked fine before jack, here's how I have configured jack:

```
# asound.conf
pcm.!default {
    type plug
    slave.pcm "jack"
    hint.description "Jack Audio"
}
```
I start it in .xinitrc with `jackd -d alsa &`.

### Reproduction steps

So, I have installed jack2, everything has been working fine, including youtube (in the browser), renoise (DAW) and mplayer.

With mpv, I have the following problem: when I pause and unpause the video, the sound disappears. If I jump to another location, the sound starts playing again. If I pause, jump to another location and unpause, the sound plays too.

Steps for me are:
- pause
- unpause

### Expected behavior

the sound plays

### Actual behavior

the sound doesn't play and I get the desynchonization error in the output (can be found in the log below)

### Log file

[mpv_log.txt](https://github.com/mpv-player/mpv/files/4477426/mpv_log.txt)

### Sample files

Any mp4 file seems to have the issue (if needed, will test other formats).

**Comment by megapink** [comment]
I have asked a question on the [arch forum](https://bbs.archlinux.org/viewtopic.php?id=254623) and was adviced to try `--ao=jack`. The flag eliminates all the problems!

**Comment by wm4** [comment]
That makes it use the jack API directly. By default, it uses ALSA - whether the problem is in mpv's ALSA code, or ALSA's jack code, no idea.

**Comment by megapink** [comment]
@wm4 If that helps any, mpv used to work well before I installed jack.

**Comment by Dudemanguy** [comment]
Going to chalk this one up to "weird compatibly layer issue" and the fix is to just use the native ao (jack). Also this is before the audio api was rewritten (another big variable).
