### ISSUE TITLE
SSA Subtitle Issue: Vollkorn Font Size Does Not Adhere to "\fs" tag (Renders Much Larger)

### ISSUE THREAD

**Issue by nedragrevev** [mpv-player/mpv#7618]
### Important Information:

- mpv version: 0.32.0-352-g530a0863b8 
- Windows Version: Windows 10 1909
- Source of the mpv binary: 20200412-git-530a086 (Windows build by shinchiro)

### Reproduction steps

Bug reproduced with --no-config command.
No specific steps needed to reproduce this bug as it seems to be present at all times.

### Expected behavior

The font size for "Vollkorn" (a readily available Google font) should adhere to the "\fs" override tag.

### Actual behavior

Vollkorn font renders double the size it should be (or at least significantly larger than it should be). That means, any TS signs using this font look completely out of place and just ugly.

It's quite a specific issue but it may affect other fonts. Other players (and devices like iPad/Nvidia Shield) do not suffer this issue.

### Log file

Attached. [output.txt](https://github.com/mpv-player/mpv/files/4479744/output.txt)

### Sample files

[Test_FontSize_Bug.zip](https://github.com/mpv-player/mpv/files/4479749/Test_FontSize_Bug.zip)
Test file includes 10 second mkv with both SSA sub file and fonts muxed in, and can be demuxed as required.

**Comment by Akemi** [comment]
without checking the actual legibility of that bug, this is an libass issue and you should report it there.

**Comment by nedragrevev** [comment]
I seem to going around in circles (initially posted this on mpv.net too) but you're right, I tried it with SMPlayer and the bug is reproduced there. It renders properly with VLC, which I thought used the libass subtitle renderer, too?

It looks like this bug has already been reported in the libass bug tracker page.

**Comment by wm4** [comment]
Definitely libass issue. Possibilities in differences between players include: different font backend, not picking up all fonts from mkv attachments, old or patched libass builds.
