### ISSUE TITLE
HDR 2086 dropped frames, 2094 files play fine

### ISSUE THREAD

**Issue by TRPB** [mpv-player/mpv#7619]
### Important Information

Provide following Information:
- mpv version 0.32.0
- Linux Distribution and Version Arch Linux
- Source of the mpv binary  official repos
- If known which version of mpv introduced the problem n/a
- Window Manager and version KDE/Plasma 5.18.4
- GPU driver and version Intel i915 (Latest from kernel 5.5.13)
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Open a UHD Bluray rip with SMPTE 2086  
Open a UHD Bluray rip  with SMPTE 2094

 The 2094 file plays absolutely perfectly on my CPU without GPU acceleration (GPU acceleration is choppy but shows no dropped frames for both files, I've been running without it fine for everything else) . A file with SMPTE 2084  drops about 6 frames per second.

Hardware:

Intel 8650u, 4k display

### Expected behavior

No dropped frames

### Actual behavior

Dropped frames. This is definitely a HDR issue. If I use mkvpropedit to remove the following  properties from the file:

colour-primaries
colour-transfer-characteristics
colour-matrix-coefficients

The file plays with washed out colours but no HDR. I tried to work out which of these properties causes the issue.

### Sample files

Sorry, I can't really provide sample files as they are copyrighted films from Bluray.

I can however, provide mediainfo output for both files. 

Plays flawlessly:

```
Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
HDR format                               : SMPTE ST 2094 App 4, Version 1
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 21 min
Bit rate                                 : 24.5 Mb/s
Width                                    : 3 840 pixels
Height                                   : 1 600 pixels
Display aspect ratio                     : 2.40:1
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.166
Stream size                              : 24.2 GiB (98%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 717 cd/m2
Maximum Frame-Average Light Level        : 642 cd/m2
```

Drops frames:

```
Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2 h 4 min
Bit rate                                 : 47.8 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.240
Stream size                              : 41.7 GiB (85%)
Language                                 : English
Default                                  : No
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2

```

I'll try playing around with mkvpropedit to see if I can see if it's a particular setting that causes MPV to struggle, but the major difference seems to be the HDR format and disabling HDR (by removing the properties, and thus getting mpv to play it washed out) stops dropping frames.

edit: The stream size and bit rate are wrong there. I tried compressing it using ffmpeg and although it required a bit of tweaking, a 9.4gb file with a much lower bitrate has the same problem. 

I'm wondering if it's possible to convert HDR formats in the file itself.

**Comment by haasn** [comment]
The second one also has over twice the bit rate.

**Comment by TRPB** [comment]
I tried compressing it down to a much lower bitrate using ffmpeg. It did need a bit of tweaking to do so, but it suffers the same problem.

The 24gb file plays fine. A 9.4gb file, with HDR enabled, drops frames.

**Comment by TRPB** [comment]
[output.log](https://github.com/mpv-player/mpv/files/4481724/output.log)

While playing, despite dropping frames, all 8 CPU cores are in use but they're all almost always below 50% usage. None ever reaches anywhere near 100%

**Comment by wm4** [comment]
You can "remove" HDR rendering properties with ``--vf=format=...`` (see https://mpv.io/manual/master/#video-filters-format for actual parameters which you must specify).

> While playing, despite dropping frames, all 8 CPU cores are in use but they're all almost always below 50% usage. None ever reaches anywhere near 100%

That's normal. You didn't think buying a 8 core CPU gives you 8 times the power of a single CPU, right?

Some claim this helps: https://mpv.io/manual/master/#options-vd-queue-enable (you may need to extend the queue size parameters)

**Comment by TRPB** [comment]
> That's normal. You didn't think buying a 8 core CPU gives you 8 times the power of a single CPU, right?

No, but I'd expect dropped frames if one or more core was hitting 100% constantly as obviously it wouldn't be fast enough to keep up with the video. With no cores above 50% usage, it's difficult to understand why frames are being dropped, there is plenty of room left for additional processing.

vd-queue made no difference

```
vd-queue-enable=yes
vd-queue-max-bytes=512MiB
```


> You can "remove" HDR rendering properties with --vf=format=... (see https://mpv.io/manual/master/#video-filters-format for actual parameters which you must specify).


Which format would you recommend trying? Using fmt=help gives a very long list of options:

```
Available formats: yuv444p yuv420p gray gray16 uyvy422 nv12 p010 nv24 argb bgra abgr rgba bgr24 rgb24 0rgb bgr0 0bgr rgb0 rgba64 rgb565 rgb30 vdpau vdpau_output vaapi dxva2_vld mmal videotoolbox drm_prime cuda yuyv422 yuv422p yuv410p yuv411p monow monob pal8 yuvj422p uyyvyy411 bgr8 bgr4 bgr4_byte rgb8 rgb4 rgb4_byte nv21 gray16be yuv440p yuvj440p yuva420p rgb48be rgb48 rgb565be rgb555be rgb555 bgr565be bgr565 bgr555be bgr555 vaapi_moco vaapi_idct yuv420p16 yuv420p16be yuv422p16 yuv422p16be yuv444p16 yuv444p16be rgb444 rgb444be bgr444 bgr444be ya8 bgr48be bgr48 yuv420p9be yuv420p9 yuv420p10be yuv420p10 yuv422p10be yuv422p10 yuv444p9be yuv444p9 yuv444p10be yuv444p10 yuv422p9be yuv422p9 gbrp gbrp9be gbrp9 gbrp10be gbrp10 gbrp16be gbrp16 yuva422p yuva444p yuva420p9be yuva420p9 yuva422p9be yuva422p9 yuva444p9be yuva444p9 yuva420p10be yuva420p10 yuva422p10be yuva422p10 yuva444p10be yuva444p10 yuva420p16be yuva420p16 yuva422p16be yuva422p16 yuva444p16be yuva444p16 xyz12 xyz12be nv16 nv20 nv20be rgba64be bgra64be bgra64 yvyu422 ya16be ya16 gbrap gbrap16be gbrap16 qsv d3d11va_vld yuv420p12be yuv420p12 yuv420p14be yuv420p14 yuv422p12be yuv422p12 yuv422p14be yuv422p14 yuv444p12be yuv444p12 yuv444p14be yuv444p14 gbrp12be gbrp12 gbrp14be gbrp14 yuvj411p bayer_bggr8 bayer_rggb8 bayer_gbrg8 bayer_grbg8 bayer_bggr16 bayer_bggr16be bayer_rggb16 bayer_rggb16be bayer_gbrg16 bayer_gbrg16be bayer_grbg16 bayer_grbg16be xvmc yuv440p10 yuv440p10be yuv440p12 yuv440p12be ayuv64 ayuv64be videotoolbox_vl p010be gbrap12be gbrap12 gbrap10be gbrap10 mediacodec gray12be gray12 gray10be gray10 p016 p016be d3d11 gray9be gray9 gbrpf32be gbrpf32 gbrapf32be gbrapf32 opencl gray14be gray14 grayf32be grayf32 yuva422p12be yuva422p12 yuva444p12be yuva444p12 nv42
```

**Comment by wm4** [comment]
None of them.

**Comment by haasn** [comment]
> [output.log](https://github.com/mpv-player/mpv/files/4481724/output.log)

And of the working version?

**Comment by Akemi** [comment]
another log was requested. if this problem still persists please open a new issue.
