### ISSUE TITLE
Using Vulkan api on Wayland does not use GPU

### ISSUE THREAD

**Issue by physkets** [mpv-player/mpv#7620]
### Important Information

Provide following Information:
- mpv version: 0.32.0
- Linux Distribution and Version: Archlinux
- Source of the mpv binary: Distribution repository
- If known which version of mpv introduced the problem: Don't know
- Window Manager and version: KWin Plasma (Wayland)
- GPU driver and version: mesa/vulkan-intel 20.0.4
- Possible screenshot or video of visual glitches N.A.

### Reproduction steps

Configuration is:

profile=gpu-hq
gpu-api=vulkan
gpu-context=wayland
hwdec=vaapi
audio-display=no

### Expected behavior

Will use the GPU to render

### Actual behavior

VO: [wlshm] 1920x1080 yuv420p

### Log file

[mpv_vulkan.log](https://github.com/mpv-player/mpv/files/4482662/mpv_vulkan.log)

**Comment by philipl** [comment]
You have to set `vo=gpu`. It's currently using the `wlshm` vo which has no GPU acceleration support.

**Comment by physkets** [comment]
Ya, but why doesn't it pick that by default? That is what was happening without `gpu-api=vulkan`, but the rest of the config., the same as above.

@Dudemanguy over at the IRC channel said I should set `gpu-context=waylandvk`, and with that, it does use the gpu, without having to set `vo=gpu`. I am attaching the log.

[mpv_vulkan.log](https://github.com/mpv-player/mpv/files/4482735/mpv_vulkan.log)

**Comment by wm4** [comment]
Your gpu-context and gpu-api conflict.
