### ISSUE TITLE
mpv segfaults with Debian Unstable and the Iris Driver

### ISSUE THREAD

**Issue by mrjpaxton** [mpv-player/mpv#7623]
Hi, I have ran into a rather interesting problem with Debian Unstable. This seems to happen with specifically Kernel 5.5.0-1, and not any previous kernels, like kernel 5.4 or 5.2. When I launch mpv, it will stall for about 10 seconds, then segfault and close.

After running `gdb mpv` and then running with `r <file>` it showed something interesting at the end:

```
(gdb) r testvid.mkv
Starting program: /usr/bin/mpv testvid.mkv
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe9675700 (LWP 35747)]
[New Thread 0x7fffe8e74700 (LWP 35748)]
[New Thread 0x7fffe3fff700 (LWP 35749)]
[New Thread 0x7fffe37fe700 (LWP 35750)]
[New Thread 0x7fffe2ffd700 (LWP 35751)]
[New Thread 0x7fffe27fc700 (LWP 35755)]
[Thread 0x7fffe27fc700 (LWP 35755) exited]
[New Thread 0x7fffe27fc700 (LWP 35756)]
[New Thread 0x7fffe1ffb700 (LWP 35757)]
[New Thread 0x7fffe17f3700 (LWP 35758)]
[New Thread 0x7fffe0ff2700 (LWP 35759)]
[New Thread 0x7fffc4ca1700 (LWP 35760)]
[New Thread 0x7fffbffff700 (LWP 35761)]
[New Thread 0x7fffbf7fe700 (LWP 35762)]
[New Thread 0x7fffbeffd700 (LWP 35763)]
[New Thread 0x7fffbe7fc700 (LWP 35764)]
[New Thread 0x7fffbdffb700 (LWP 35765)]
[New Thread 0x7fffbd7fa700 (LWP 35766)]
[New Thread 0x7fffbcff9700 (LWP 35767)]
[New Thread 0x7fffaffff700 (LWP 35768)]
[New Thread 0x7fffaf1fe700 (LWP 35800)]
[New Thread 0x7fffae9fd700 (LWP 35801)]

Thread 10 "mpv/vo" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe17f3700 (LWP 35758)]
0x00007fffcb4a59d8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
```

I could see the shared object causing the problem. I knew Iris was something Intel Graphics related, so I looked more into the problem, and caught a suggestion Online.

When I used this command prefix:

```
MESA_LOADER_DRIVER_OVERRIDE=i965 mpv <file>
```

It then works as expected. It leads me the believe something is wrong with Linux or Mesa's implementation of the Intel Iris Graphics and kernel 5.5 on Debian, or perhaps it is something with mpv, which is why I wanted to ask here first. Anyone else on another distro having this issue? I would be curious to know.

Also, I tried it with just audio files, and it works fine. Seems to be just video files are affected.

### Important Information

Provide following Information:
- mpv version: **mpv 0.32.0**
- Linux Distribution and Version: **Debian GNU/Linux Unstable**
- Source of the mpv binary: **/usr/bin/mpv**
- If known, which version of mpv introduced the problem: **N.B.**
- Window Manager and version: **i3 version 4.17.1**
- GPU driver and version: **libdrm-intel1:amd64 2.4.101-2**
- Possible screenshot or video of visual glitches: **Video does not show up.**

### Reproduction steps

Explained above.

### Expected behavior

Video plays back normally.

### Actual behavior

Segmentation fault.

### Log file

Link here: https://slexy.org/raw/s204fMkQPT?token=89b2dabbc90e40c644db4fc273dd7306620aade1c7b0b99ded68cb295bc4a741&ts=1587029626

**Comment by wm4** [comment]
Why do you think it's a mpv problem, or that mpv can do anything against it?

**Comment by linkmauve** [comment]
Because stack traces leading to the graphics driver are often caused by applications’ misuse of the OpenGL API.

Of course, without the actual stack trace and debug symbols that’s a bit useless, so please install the debug symbols for the relevant libraries (at least Mesa and mpv) and run `bt` in gdb to generate a usable stack trace.

**Comment by CounterPillow** [comment]
>caused by applications’ misuse of the OpenGL API.

In that case the OpenGL API should raise an error, not segfault in the driver stack, so even if this were the case it'd still be an Intel bug.

**Comment by mrjpaxton** [comment]
Aha! Okay, so I am sane in thinking that this is an upstream problem, seeing as @wm4 kind of implied that.

I suppose I should be reporting this to a different project? Which one and where, exactly?

In the meantime, I can do that stack trace you asked, @linkmauve. I'm back on Kernel 5.4 right now, let me reboot into 5.5 again and I'll install, and I'll update with a post about that in a minute....

Okay, after enabling the debug symbol repos and installing `mpv-dbgsym libdrm2-dbgsym libdrm-intel1-dbgsym` am I ready to start debugging? Sorry, I'm not a developer, though I do have basic knowledge of understanding C concepts and gdb. :p

**Comment by mrjpaxton** [comment]
Okay, I can't reproduce this error anymore since I've updated my system now. Maybe this should be closed in the meantime. Sorry about all this.
