### ISSUE TITLE
Segregate PAN and SCAN functions

### ISSUE THREAD

**Issue by akshayjauhari** [mpv-player/mpv#7624]
Overview Description:
PAN and SCAN functionality must be  separated with each other like that of Media player classic with k-lite mega codec on windows

Steps to Reproduce:

    Make PAN on numpad 8 and 2 to increase/decrease it.
    Make SCAN on numpad 6 and 4 to increase/decrease it.
    This will help configure PAN and SCAN functions separately.

Actual Results:
Currently both PAN and SCAN are linked to each other and with any increase it crops the sides of the videos.

Expected Results:
Please segregate both the functions so the user can customize according to its taste.

Additional Information:
I always like the videos to just increase the PAN which are not covering my full screen space without cropping any side screen video.

**Comment by CounterPillow** [comment]
Isn't what you're looking for zoom and the panning keys?

**Comment by akshayjauhari** [comment]
No. I know PAN/scan is configured on W and E keys to increase and decrease but it would be better if these both PAN and SCAN are not interlinked. If i want to perform only vertical stretch then that should be an option and if only horizontal stretch.  Currently PAN/SCAN function performs both simultaneously.

**Comment by CounterPillow** [comment]
panscan has nothing to do with stretching. The scan is the act of cropping the image, the pan is moving the cropped view to whatever part of the original frame that is important.

**Comment by akshayjauhari** [comment]
I am just saying once see the functions of PAN and SCAN in media player classic of windows which is also bundled with k lite mega codec. it performs with numpad 8,2,4 & 6 that too separately. if you see this you will understand. Though SCAN is the act of cropping. Horizontal and vertical cropping are performed separately. in mpv it is interlinked. First please see rather than commenting blindly. This is the problem with linux users scope of improvement is very less and it goes into an argument.

**Comment by wm4** [comment]
People who want to stretch video to non-native aspect ratios are not welcome here. You still can do it if you try, though.

**Comment by CounterPillow** [comment]
considering what you seemingly want can already be achieved I believe this issue is the result of you not reading the manual.

**Comment by akshayjauhari** [comment]
I have made a video for you people to understand what i mean rather than declaring of not reading the manual . please see the link and inform us if this function of PAN/SCAN can be achieved with mpv player. 

[https://www.dropbox.com/s/t7mjc27ucxfwieh/recorded.mkv?dl=0](url)

**Comment by xerone69** [comment]
did you find anything?

**Comment by guidocella** [comment]
It is possible with `--video-scale-x` and `--video-scale-y`.

**Comment by xerone69** [comment]
thank you
