### ISSUE TITLE
[build question] How to tell 'waf configure' where to look for zimg build?

### ISSUE THREAD

**Issue by emanruse** [mpv-player/mpv#7625]
On the distro I use zimg-devel version is 2.7.4 and `waf configure` seems to not like that and says `no ('zimg >= 2.9' not found) `.

I have built zimg 2.9.3 from source but I do not want to run `make install` as I don't want it to mess up with my distro-provided zimg. I just want to use that built zimg to build mpv.

My question is:

How do I tell `waf configure` to find the directory which contains zimg?

**Comment by jeeb** [comment]
*nix build systems 101

1. Utilize `--prefix=/home/you/ownapps/own_things_sysroot` with zimg (or any other dep)
2. Utilize `make install` and it will install, no root needed since it goes into a dir in your home directory.
2. Utilize `PKG_CONFIG_PATH=/home/you/ownapps/own_things_sysroot/lib/pkgconfig` when running the configure for the thing you're trying to build against something in your sysroot :)
3. ???
4. Profit!

**Comment by jeeb** [comment]
Alternatively you can also utilize a standard prefix, but utilize `make install DESTDIR=/home/you/ownapps/own_things_sysroot` to instead install into that prefix within DESTDIR.

But that also means that you need to utilize the sysroot option with pkg-config. Which is more effort in general :P .

**Comment by emanruse** [comment]
Exporting PKG_CONFIG_PATH directly worked. Thanks @jeeb !

May I also please ask how necessary are any of these (assuming mpv will be used on a Linux Desktop):

```
Checking for program 'windres'           : not found
Checking for linker support for --nxcompat --no-seh --dynamicbase         : no
Checking for Android environment                                          : no
Checking for tvOS environment                                             : no
Checking for BSD's fstatfs()                                              : no
Checking for Linux's memfd_create()                                       : no
Checking for Javascript (MuJS backend)                                    : no ('mujs >= 1.0.0' not found)
Checking for libarchive wrapper for reading zip files and more            : no ('libarchive >= 3.4.0' not found)
Checking for libav* is Libav                                              : no
Checking for RSound audio output                                          : no
Checking for OpenSL ES audio output                                       : no
Checking for CoreAudio audio output                                       : no
Checking for AudioUnit output for iOS                                     : no
Checking for Cocoa                                                        : no
Checking for libshaderc SPIR-V compiler (shared library)                  : no
Checking for libshaderc SPIR-V compiler (static library)                  : no
Checking for SPIRV-Cross SPIR-V shader converter (shared library)         : no ('spirv-cross-c-shared' not found)
Checking for SPIRV-Cross SPIR-V shader converter (static library)         : no ('spirv-cross' not found)
Checking for Raspberry Pi support                                         : no ('brcmegl' not found)
Checking for iOS OpenGL ES hardware decoding interop support              : no
Checking for libplacebo support                                           : no ('libplacebo >= 1.18.0' not found)
```
I just need to know what else I must build from source.

**Comment by jeeb** [comment]
The ones that you might be interested in:
* mujs (Javascript scripting for those who prefer that to lua)
* libarchive (if you need ZIP/RAR archive support for reading those media files in weird 50MiB RAR files)
* shaderc/libplacebo (if you want vulkan support that renders through libplacebo)

Otherwise it's Windows, Android, Apple related stuff.

**Comment by emanruse** [comment]
Thank you!

And one last question please:

How can I check which of all these were/weren't used when building the distro-provided mpv?
