### ISSUE TITLE
Does mpv have an argument like FFmpeg's "-localaddr"?

### ISSUE THREAD

**Issue by Helloooxs** [mpv-player/mpv#7628]
I need to play a udp multicast address media like "udp://224.0.0.1:8000".
The problem is that there are two networks(one Ethernet, one WLAN), so i need to appoint a netmask to receive the media data.
In ffmpeg, i can set the argument "-localaddr=LOCALADDR", but i can't find an argument in mpv like this.

**Comment by CounterPillow** [comment]
try `udp://224.0.0.1:8000?localaddr=addrhere`

**Comment by Helloooxs** [comment]
> try `udp://224.0.0.1:8000?localaddr=addrhere`

It works! Thx!
