### ISSUE TITLE
Height and width separation with PAN/SCAN

### ISSUE THREAD

**Issue by akshayjauhari** [mpv-player/mpv#7629]
I have made a video for you people to understand what i mean . please see the link and inform us if this function of PAN/SCAN can be achieved with mpv player.

[https://www.dropbox.com/s/t7mjc27ucxfwieh/recorded.mkv?dl=0](url)

**Comment by CounterPillow** [comment]
`--no-keepaspect` with the various options for modifying video geometry are what you're looking for, please don't spam the issue tracker.
