### ISSUE TITLE
VDA decode issue

### ISSUE THREAD

**Issue by xswqaz** [mpv-player/mpv#763]
Failed to hardware decode H.264 in OSX(Mavericks) like below error
How can I find out apps that using VDA?

failed to init VDA decoder: Generic error returned by the decoder layer. The cause can range from VDADecoder finding errors in the bitstream to another application using VDA at the moment. Only one application can use VDA at a givent time. (-12473)
Error while decoding frame!
Error using hardware decoding, falling back to software decoding.

**Comment by ainstushar** [comment]
Can we please open this issue? The fallback doesn't seem to work.

**Comment by pigoz** [comment]
It works here, is it broken on specific files? Did you try FFmpeg master?

**Comment by ainstushar** [comment]
@pigoz 
Error occurred when I was on FFMpeg 2.6.1, which didn't incorporate the commit https://github.com/FFmpeg/FFmpeg/commit/3e53211a578. I switched to master and it works just fine.

Just FYI: on FFMpeg 2.6.1, I was getting this error:

````
[ffmpeg/video] h264: hardware accelerator failed to decode picture
Assertion failed: (mpi->planes[0] || mpi->planes[3]), function decode, file ../video/decode/vd_lavc.c, line 647.
Abort trap: 6
````

I think it would be nice for mpv to switch to software decoding incase FFMpeg has issues with vda. Not sure if it's hard. Additional failsafe is completely unnecessary so you can feel free to ignore this.

In the meantime, thanks for putting time and effort in this project.

**Comment by pigoz** [comment]
It's not a VDA problem, the bug was in ffmpeg and has been fixed.. You could ask FFmpeg to backport it to a stable release I guess, if you wan't want to run on master for the time being.

The problem in this case is FFmpeg has problems decoding, but does not report so correctly.
