### ISSUE TITLE
libmpv: How to load Lua code from memory in Windows?

### ISSUE THREAD

**Issue by stax76** [mpv-player/mpv#7632]
Hello, is it possible to load Lua code using libmpv from memory/string in Windows with C or C#? It seems only a file and not code as string can be loaded. I tried if named pipes might work but was not able to read that with powershell get-content.

**Comment by wm4** [comment]
No such thing is currently implemented. There's the load-script command, but it requires a file on the filesystem.

**Comment by stax76** [comment]
I see, thanks. The load-script command is what I use so far with scripts located in the startup folder, I thought it would avoid some issues if I embed scripts in the executable instead, I can do something else. It doesn't seem Windows has an easy way to create some sort of virtual file, at least I could not find it.

**Comment by j605** [comment]
You can use embedded resources and build the executable with the script in it.

**Comment by stax76** [comment]
Yes, but I need the script code to be loaded by mpv and it must be high performance.

**Comment by j605** [comment]
You can put it into a stream which can be read like a file by mpv. I don't know about it affecting speed. I did this for passing an embedded resource to a function requiring a file.

**Comment by stax76** [comment]
I've various options, and they are OK.

1. Use another language like C# or PowerShell.

2. Continue to distribute Lua files.

3. Create temporary files.

I think I go with option 2, so far I was iterating over the files of the folder and showed and error for unknown files, there is a more simple way, hard coding the file names to be loaded, users need to read the docs and put user scripts not in the startup folder but in the config folder.

**Comment by j605** [comment]
> Can you point me to the code?
It is not open, sorry. What I did was put it in the resources and then access it to get the full string. Using the string, you can build a stream if you want a file like behaviour.

**Comment by stax76** [comment]
I think I understand, not sure it's the best solution for me but still good to know.

**Comment by avih** [comment]
FWIW, some time ago I implemented a hack which allows it (for JS). It _is_ a hack, and I do not recommend taking it as is - https://github.com/avih/mpv/commit/602db845

**Comment by stax76** [comment]
Good to know also. I've basic JS experience and zero Lua experience but learn it at the moment, for instance because I want to figure out why the osc top bar window buttons minimize, maximize and close do nothing in mpv.net, it's not sending `quit` or change `window-maximized`. So I learn Lua right now, so I will be able to understand osc.lua and other scripts.
