### ISSUE TITLE
[regression 0.30+] Image playlist stepping sticks intermittently, and then skips next image

### ISSUE THREAD

**Issue by jrodatus** [mpv-player/mpv#7636]
### Version Information

* mpv releases 0.30.0 to latest (builds from stolendata), as well as git master.
* macOS 10.15.4 (latest)

I wanted to find the offending commit, but on Catalina I can build only from f64c0115ae onward, so it's out of my range.

### Reproduction steps

Create a folder containing some moderately-sized images.
To reproduce, I used (20) 4k wallpapers between 2-4 MB each. See "Sample files" section.

(I was _not_ able to reproduce this using smaller images <1 MB.)

Run:
`mpv --loop-playlist=inf --pause /path/to/images/folder`

Then step through the playlist by pressing "Enter" after each image displays.
Do not move the mouse cursor.

### Expected behavior

Pressing "Enter" should reliably advance to the next image in the playlist.

### Actual behavior

Intermittently, every 5~30 images, mpv fails to advance to the next image.
From this "stuck" state, you can do either one of two things:

- A. Press "Enter" a second time, and it will glitch/flash the next image and skip over it.
- B. If in fullscreen mode or a _scaled_ window, you can move the mouse cursor and it will "unstick", updating to show the expected image. Or if windowed and _unscaled_, you can resize the window and it will likewise "unstick."

The issue may be more frequent when reading from a slow disk.

### Log file

https://pastebin.com/v6WBsKE8

Log is from running:
`mpv --loop-playlist=inf --pause --fullscreen /path/to/test-images`

This time, it stuck on image (12).
I then moved the mouse cursor to "unstick" it, advancing to image (13).

### Sample files

Test images (twenty 4k wallpapers, 2~4 MB each):
http://0x0.st/i1oV.7z

### Xcode Command Line Tools note

As of today (2020/04/18), installing them via
`sudo rm -rf /Library/Developer/CommandLineTools && xcode-select --install`

...installs only version 11.4, which fails per #7598 

The working version 11.4.1 is here:
https://developer.apple.com/download/more/?=xcode

**Comment by Akemi** [comment]
so 0.29 works?

**Comment by jrodatus** [comment]
> so 0.29 works?
Yeah!

I can install an older macOS later and find out what commit caused it. Just wanted to document it for now.

**Comment by Akemi** [comment]
you could most likely also just download an older xcode version and use` sudo xcode-select -s PATH/TO/XCODE_APP` to temporary change the build tools. `xcode-select -p` beforehand to copy the old path for switching back.

**Comment by jrodatus** [comment]
That sounded good. Xcode on Catalina w/ 723fd02 (0.29.1):
- **10.3**: invalid value 3 in '-swift-version 3' .. valid arguments are 4, 4.2, 5
- **10.2**: invalid value 3 in '-swift-version 3' ..
- **10.1**: No OpenGL video output found or enabled. (`--disable-gl` builds ok, but won't run..)
- **10.0**: No OpenGL video output found or enabled. (")
- **9.4**: gcc: unable to locate xcodebuild

10.2/3 with 3a8abbe had undefined symbols (object file .. built for newer OSX version (10.15) than being linked (10.14)).

I'll have more time later. tx

**Comment by jrodatus** [comment]
OK, it compiles fine on High Sierra.

Issue was reproduced with:
* macOS High Sierra 10.13.6
* Xcode 10.1

The breaking commit was 9e466ee621.

I'm surprised, in 2 years does no one else do slideshows? Or are people still using 0.29..
If no one else looks at it, maybe I will in a few weeks.

**Comment by Akemi** [comment]
i don't do any slideshows. though this could be a more fundamental problem which is within libmpv, or if lucky somewhere in the cocoa-cb backend a draw callback is somehow ignored.

**Comment by aerobounce** [comment]
Recently I started to use mpv as an image viewer, and encountered the same bug (?) too.
Try this option:
```
cocoa-cb-sw-renderer=yes
```
This resolved the problem for me.

**Comment by Akemi** [comment]
is this still reproducible with master?

**Comment by jrodatus** [comment]
> is this still reproducible with master?

Nice! Seems fixed by 0cea7b9ffb. Thanks for all you guys'es work 😀

ima close this.

**Comment by Akemi** [comment]
yeah, i kinda had a hunch that this commit might fix this one. thanks for testing.
