### ISSUE TITLE
Infer the watch_later filename for a m3u playlist

### ISSUE THREAD

**Issue by sebma** [mpv-player/mpv#7637]
I accidentally lost the playback position in my m3u playlist  because I hit ctrl+c while playing it.
Now if play it again, `mpv` goes back to the very first url :(

Luckily, I still have the `watch_later` file for that playlist on another computer : 
```bash
$ cd ~/.config/mpv/watch_later/
$ find . -xdev -type f -mmin -5
./E9A0553BCF8BA07FBF7EE5EE36136E4F
./D3A2A0FAC8E54C81466111B9302C027A
$ more ./E9A0553BCF8BA07FBF7EE5EE36136E4F ./D3A2A0FAC8E54C81466111B9302C027A
::::::::::::::
./E9A0553BCF8BA07FBF7EE5EE36136E4F
::::::::::::::
# https://ok.ru/video/1443211512573
start=14.166444
::::::::::::::
./D3A2A0FAC8E54C81466111B9302C027A
::::::::::::::
# redirect entry
# meurtres_au_paradis.m3u
```
I noticed the `watch_later` filename for the URL played is the uppercase md5sum of that url : 
```bash
$ printf https://ok.ru/video/1443211512573 | md5sum | awk '{print toupper($1)}'
E9A0553BCF8BA07FBF7EE5EE36136E4F
```
But then I don't know how to infer the `watch_later` filename for the m3u playlist, given here by this string `D3A2A0FAC8E54C81466111B9302C027A`

I'd like to infer the `watch_later` filename for the m3u playlist  so I can re-create it given the m3u filename and the last played URL.

Can you tell me how to do that ?

**Comment by sebma** [comment]
Workaround : I remove the watch later md5 file for the first item of the playlist to prevent playing the playlist from the beginning : 
```bash
$ rm -i ~/.config/mpv/watch_later/$(sed -n '3p' ~/mySeries/meurtres_au_paradis.m3u | tr -d "\n" | md5sum - | cut -d' ' -f1 | awk '{print toupper($0)}')
rm: remove regular empty file '/home/sebastien/.config/mpv/watch_later/FFDDE795F9A35EC31717B6D83D5CE316'? y
```

**Comment by wm4** [comment]
Not sure what's even the question. As you figured out, the watch later filename is the md5 of the URL in hex. Resuming a playlist works by checking every entry - the first entry with an existing resume file will be the entry to resume.

**Comment by sebma** [comment]
@wm4 Thanks :) :+1:
