### ISSUE TITLE
Increased black level with high target-peak, Hable and HDR output

### ISSUE THREAD

**Issue by quietvoid** [mpv-player/mpv#7638]
### Important Information

- mpv version: mpv-x86_64-20200412-git-530a086 (shinchiro)
- Windows Version: Windows 10 Pro, 1909, 18363.752

Using `tone-mapping=hable` with a high target-peak value in HDR causes black level as well as overall brightness to be increased. This affects shadow detail as well.

The easiest to see is the black level, since reference black is dim but visibly grey instead of black.
I tested this on an OLED TV, only `tone-mapping=hable` causes this issue (and it is the default).
Bars up to 120 are also brighter with hable than mobius.

Lowering `target-peak` seems to diminish the issue but it's still present (down to 100, where it's fine).
Disabling `hdr-compute-peak` has no effect.

### Reproduction steps

First, the output display needs to support HDR.
Windows HDR is not enabled, mpv triggers HDR when set into fullscreen.
Config:
> target-peak=700
> d3d11-output-csp=pq
> d3d11-output-format=rgb10_a2
> tone-mapping=hable

### Expected behavior

Reference black (64) should be completely black, 66 and 68 should be dimly flashing.

### Actual behavior

On the HDR display, reference black (64) is brighter than 66 and 68. Bars from 72 to 120 are also brighter with hable than mobius (which seems to be fine).
Should content lower than the target even be tonemapped, other than chroma?

### Log file

https://0x0.st/i1HE.txt

### Sample files

https://0x0.st/i1Hf.mp4

Pics (had to black out reflections), mobius and hable:
![mobius](https://user-images.githubusercontent.com/39477805/79671604-9e0f3e80-8199-11ea-8c5f-3fee6af1af93.jpg)
![hable](https://user-images.githubusercontent.com/39477805/79671606-a1a2c580-8199-11ea-8ff3-77e43ac15bb5.jpg)

**Comment by haasn** [comment]
I can't see the described effect in your photos (looking at them with a color picker, the reference black bar is definitely *not* brighter than the 66 and 68 bars) and I don't know how to reproduce this. Actual screenshots (i.e. framebuffer dumps) would be far more useful than camera photos, to rule out clipping due to other sources.

**Comment by quietvoid** [comment]
Right, the black level is not really visible in the photos but the other bars are visibly brighter.
I'll try to see if I can take some screenshots.

**Comment by quietvoid** [comment]
Just thought I'd update this, I tested the new `bt.2390` tone-mapping option and that looks fine.
Also, the issue is not specific to Windows and just happens with PQ `--target-trc`.

So it's reproducible with these settings:
>target-peak=700
target-trc=pq
tone-mapping=hable

And here are again screenshots of default Hable vs `--target-peak=700` Hable:
![hable-default](https://user-images.githubusercontent.com/39477805/84611216-26a11700-ae8b-11ea-9ed1-f4425eccb322.png)
![hable-peak-700](https://user-images.githubusercontent.com/39477805/84611219-29037100-ae8b-11ea-8821-042e11d29abc.png)

I took these with `mpv 0.32.0-553-gc9f6c458ea` on Linux.

**Comment by quietvoid** [comment]
This doesn't happen in `vo=gpu-next` anymore.

vo=gpu
![vo=gpu](https://user-images.githubusercontent.com/39477805/141684717-a69e89cf-767b-4d54-8312-7ee443632ad8.png)

vo=gpu-next
![vo=gpu-next](https://user-images.githubusercontent.com/39477805/141684721-394bb7fa-2de6-47cb-bb7b-ddd33779413f.png)

**Comment by quietvoid** [comment]
Closing this as it doesn't affect me anymore, with `gpu-next`.
