### ISSUE TITLE
avi container with h264/mp3 streams 'non monotonically increasing dts' in encoding mode (--o=...) & choppy playback in gui mode.

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7646]
### Important Information

Provide following Information:
- mpv version: mpv 0.32.0-383-ga09c7691d7 (latest release build)
- Platform and Version: Windows 10 + Ubuntu 16.04
- Source of the mpv binary: Sourceforge Windows Build

### Reproduction steps

When I try to encode a particular video, it fails after about a second, with lots of 'Invalid video timestamp' warnings and finally a 'non monotonically increasing dts' error, before exiting.
However, all the timestamps it shows are all equal, so I'm not sure what the problem is.

The same video also plays at about half the framerate in mpv (gui mode), but it plays fine in VLC.

It's also worth noting this file was encoded with the latest version of VirtualDub2.

If I remux the avi into another container prior to playing, then it plays just fine (in gui + encoding mode).

Sample command:

```
mpv --no-config --log-file=mpv.log --of=mpegts --ovc=libx264 --ovcopts=profile=main,preset=veryfast,level=4,b=5000k,maxrate=5000k,minrate=1000k,bufsize=5000k, --vf=lavfi=[format=yuv420p,scale=(iw*sar)*min(1920/(iw*sar)\,1080/ih):ih*min(1920/(iw*sar)\,1080/ih),pad=1920:1080:(1920-iw*min(1920/iw\,1080/ih))/2:(1080-ih*min(1920/iw\,1080/ih))/2] --oac=aac --oacopts=ac=2,b=160k --o=test.mkv "snippet.avi"
```

### Log file

[mpv.log](https://github.com/mpv-player/mpv/files/4504567/mpv.log)

### Sample files

https://0x0.st/i1Wb.avi
(Note: I've only uploaded the first 50MB because the original file is almost 4GB and they both exhibit the same behaviour. If you want I can upload the original file.)

**Comment by Akemi** [comment]
tbh sounds like a broken file. since the sample was taken down i am closing this issue. if the issue still persists please open a new issue.
