### ISSUE TITLE
Have a per-connection auto-quit flag to clean up mpv in slave mode

### ISSUE THREAD

**Issue by schmorp** [mpv-player/mpv#7648]
Problem Description:

I remote-control mpv as a slave in a number of programs, but recently, I had a case where mpv is not running embedded in another window but didn't itself react to keyboard or other commands. When the master crashes (as happens during development, and even sometimes outside development :) this results in the unpleasant situation of mpv still running, potentially blocking the session in fullscreen mode, but not easily being able to be exited as it doesn't react to any commands.

Other programs that support similar slave modes usually quit when the slave mode connection closes, but mpv happily continues. Other programs usually have a much more limited slave mode, while mpv can accept commands from a variety of sources, so it might make sense for mpv to not quit in most circumstances.

Solution Suggestion:

Therefore, I'd like to propose some kind of per-connection property, say, "auto-quit-on-close" that, when set to true, would cause mpv to automatically quit whenever the control connection closes. I use "property" in a general sense, not necessariloy meaning mpv properties - it could just as well be an ipc command.

I would additionally propose this property to be enabled by default for connections created via --input-ipc-file (or --input-file), the reason being that this avoids races when the master is incapable of setting the property fast enough, but for reasons of backwards compatibility (that hopefully don't exist with --input-ipc-file, as it is a new option) that might not be possible.

**Comment by wm4** [comment]
Would it make sense to set such a flag always for the --input-ipc-client connection internally, and not expose the flag to the user?

--input-file is no more.

**Comment by schmorp** [comment]
That would suit me just fine - I just hope it works for everybody. But seeing that --input-ipc-file is so new, that's probably the case.

**Comment by chainikdn** [comment]
Don't you think it must be an opt-in feature?
