### ISSUE TITLE
Crashing when loading a file that does not exist using mpv GUI

### ISSUE THREAD

**Issue by hacel** [mpv-player/mpv#7649]
- mpv version
0.32.0
- Platform and Version
Windows 10
- Source of the mpv binary
Scoop master

Although I have tested this on linux 0.29.1 as well with the same result.

### Reproduction steps
I have a script that uses `mp.command("loadfile")` and when this command is executed with a file that does not exist (file not found), mpv crashes if it was started through the GUI.
Crashes do not happen if mpv is started through the terminal, even with --force-window. It properly keeps running and gives an error message when trying to load a file that no longer exists.

### Expected behavior
Giving an error message without crashing.

### Actual behavior
Crashing.

### Log file
[mpvlog.log](https://github.com/mpv-player/mpv/files/4509929/mpvlog.log)

**Comment by CounterPillow** [comment]
What do you mean by "crashing"? Can you get an actual backtrace? Because from your log file it looks like it's just exiting normally.

**Comment by hacel** [comment]
Sorry, wasn't sure what was the right word to use. It does exit normally but it shouldn't exit.

**Comment by CounterPillow** [comment]
No, it should exit. If you want it to stay open, use `--idle`.

**Comment by Argon-** [comment]
There's also `--keep-open` for this https://mpv.io/manual/master/#options-keep-open

**Comment by wm4** [comment]
--keep-open is for the case when playback successfully started, though.
