### ISSUE TITLE
MPV: very sluggish while trying to navigate the video forward and backward.

### ISSUE THREAD

**Issue by sant527** [mpv-player/mpv#7653]
I have in my input.conf
RIGHT seek  3 exact
LEFT seek  -3 exact

I want to navigate the video (1GB+ and HD) quickly back and forth. SO i keep pressing the right or left arrow key. But it does not move fast at all. 

Where i opened the same file using mplayer it works very smoothly and also fast

### Log file
mpv log file
https://0x0.st/ij-C.txt

mplayer log
https://0x0.st/ijor.log

**Comment by CounterPillow** [comment]
The reason are probably your exact seek keybinds. Exact seeking is slower than the normal seeking behaviour.

**Comment by CounterPillow** [comment]
Also closing this because 0.29.1

**Comment by sant527** [comment]
Yes its exact. But any other ways to make exact seeking faster

**Comment by wm4** [comment]
mplayer doesn't have exact seeking. Non-exact seeking in mpv should be as fast as in mplayer.
