### ISSUE TITLE
Some ASS subtitles have thicker outline/shadow in mpv than in other players

### ISSUE THREAD

**Issue by enchained** [mpv-player/mpv#7654]
### Important Information
- mpv-x86_64-20200419-git-a09c769
- Windows 10

### Reproduction steps
I noticed this in some Erai-raws releases exclusively. Style example follows.

```
[V4+ Styles]
Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,Strikeout,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding
Style: main,Trebuchet MS,24,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,1,2,0010,0010,0018,0

Dialogue: 0,0:06:38.57,0:06:42.04,main,HEADON,0000,0000,0000,,The answer can always be found \Nat the top of the tower.
```

### Expected behavior
BorderStyle,Outline,Shadow
1,2,1 looks fine in players like mpc and potplayer:
![mpc](https://user-images.githubusercontent.com/6181674/80124836-82d97000-8599-11ea-9846-55de2c71e557.png)
![potplayer](https://user-images.githubusercontent.com/6181674/80124856-8b31ab00-8599-11ea-9237-30b382c92a8d.png)

### Actual behavior
But this is what it looks like in mpv (fresh download without any custom style settings)
![mpv](https://user-images.githubusercontent.com/6181674/80124900-9be22100-8599-11ea-8e6f-df409ee404da.png)

It looks like mpv displays this style with  BorderStyle,Outline,Shadow almost as if it was 1,6,3 instead.

Do I need to use some special settings to make it look like everywhere else? I looked throught the docs and couldn't find anything relevant. I don't want to use any ASS overrides if possible, I just want it to display as intended.

UPD: also SSA has these lines:
```
Collisions: Normal
PlayResX: 640
PlayResY: 360
Timer: 0.0000
WrapStyle: 0
```

While the video is 1080p.

I feel like this may be a scaling issue, and also I do not know which libraries are used in mpc and potplayer to render the subtitles. Tried to use some sub scaling options in mpv.conf, but nothing made changes.

**Comment by mia-0** [comment]
This is expected unless the ASS file has
```ScaledBorderAndShadow: yes```
because the lack of this property means the border/shadow size depends on the renderer resolution.

**Comment by enchained** [comment]
@mia I tried the` ScaledBorderAndShadow: yes` option, put it right after the `WrapStyle: 0` line, and weirdly it didn't affect anything in my case, the outlines were still bold. Even if I change PlayRes too, it just becomes smaller, but still has that noticeable thick outline.
Could you please reopen the issue?

**Comment by enchained** [comment]
@mia-0  I tried the` ScaledBorderAndShadow: yes` option, put it right after the `WrapStyle: 0` line, and weirdly it didn't affect anything in my case, the outlines were still bold. Even if I change PlayRes too, it just becomes smaller, but still has that noticeable thick outline.
Could you please reopen the issue?

**Comment by CounterPillow** [comment]
Does `--sub-ass-vsfilter-blur-compat=yes` make a difference?

**Comment by enchained** [comment]
@CounterPillow it doesn't, and I thought it wouldn't, since there weren't any \blur tags in the subtitles.
