### ISSUE TITLE
mpv crashes full Xorg session with full screen playback on Nouveau

### ISSUE THREAD

**Issue by krathalan** [mpv-player/mpv#7657]
### Important Information
- mpv version: 0.32.0
- Linux Distribution and Version: Arch Linux up-to-date as of April 23, 2020
- Source of the mpv binary: locally built to enable debug symbols; issue is also present on mpv package from Arch repos
- If known which version of mpv introduced the problem: not known
- Window Manager and version: i3-gaps, with and without picom compositor
- GPU driver and version: Nouveau from latest kernel 5.6.6 on NVIDIA Corporation GM200 [GeForce GTX 980 Ti] (rev a1)

### Reproduction steps
1. Start playing any video from command line. 
2. Enter full screen. 
3. Quit mpv while fullscreen or simply let the video end while fullscreen. 

Edit: this issue does not occur when video is closed/finished while NOT full screen.

### Expected behavior
mpv closes and I can continue using my computer.

### Actual behavior
My entire Xorg session crashes.

### Log file
mpv -v log: https://0x0.st/ij_t.txt
Xorg log: https://0x0.st/ij_w.old
GDB log: https://0x0.st/ij_J.txt

I cannot run "thread apply all backtrace" after the issue as the full Xorg session is closed.
Issue persists even with `--no-config` option.

**Comment by mia-0** [comment]
That is a bug in your graphics driver. Sorry, we can’t do anything about that. Please report the issue to the nouveau project instead.
