### ISSUE TITLE
toggle osc-playlist like osc-visibility

### ISSUE THREAD

**Issue by jkwnki** [mpv-player/mpv#7658]
Hello, 
could you add additional options like always, never, auto to osc-playlist to enable toggling like osc-visibility:
"key" script-message osc-visibility always
"key" script-message osc-visibility never 
?
could you aditionally add options for ignoring file extensions (like *.jpg, ...) in playlist?

thank you in advance.

**Comment by Dudemanguy** [comment]
It's not exactly the same but `osc-playlist` accepts a duration argument so you can use 0 to simulate "never" and then some super large number to simulate "always". As for ignoring certain file extensions in a playlist, the best way to do this is to just not load them in the first place.

**Comment by guidocella** [comment]
`cycle-values osd-msg1 "${playlist}" ""` is another solution.

To avoid loading images, see https://github.com/mpv-player/mpv/issues/2595#issuecomment-808723731

**Comment by Mobiacikaka** [comment]
> It's not exactly the same but `osc-playlist` accepts a duration argument so you can use 0 to simulate "never" and then some super large number to simulate "always". As for ignoring certain file extensions in a playlist, the best way to do this is to just not load them in the first place.

This work but the playlist won't change when the contents change. The playlist just stucks at the first time we press the button.

**Comment by Dudemanguy** [comment]
I didn't test it, but assuming that you left the `osc-playlist` on forever then yeah it is not going to automatically update itself. The osc script isn't smart enough to do that. If you turn it off and back on again it *should* update though.
