### ISSUE TITLE
Set initial window size after processing panscan

### ISSUE THREAD

**Issue by pintassilgo** [mpv-player/mpv#7659]
By default, at least on Windows 10, mpv opens with the original video size or the maximum screen area available. But as you know, 4K Blu-ray uses letterboxing (horizontal black bars are part of the video). My monitor is ultrawide (21:9, 2560×1080), so I use `panscan=1` to hide black bars. But mpv sets initial window size before applying panscan, so I end up with 1886×1050 window (my taskbar has 30px height). So there are black bars anyway and window width is much smaller than it should be.

### Expected behavior of the wanted feature

I think that there should be an option to calc initial window size **after** processing panscan. So in the case above, after hiding black bars with `panscan=1` the actual size of the video is ~3840×1636 (~2,35:1), so mpv window should use this aspect ratio instead of the original 16:9. So window should be expanded to my entire ultrawide screen, to 2560×1050 (leaving area for the taskbar, since I'm not in fullscreen).

### Alternative behavior of the wanted feature

Described in the first paragraph. Currently, window size is set using original video aspect ratio, before applying panscan. So in the case above window starts in 1886×1050, making panscan useless. I need to manually stretch the window or enter in fullscreen.

### Log file

https://pastebin.com/pxRpw4mZ

Edit: I just realized that it's impossible for mpv to know the "true" aspect ratio of videos with black bars (letterboxing), so you can't implement this. So maybe an option to set window size based on video size, since almost all my 3840×2160 videos are, without black bars, ~3840×1636. But probably there's already a way to do this with scripting. I think you can close this one, sorry.

**Comment by ValZapod** [comment]
> since almost all my 3840×2160 videos are, without black bars, ~3840×1636

It is not that simple. Some videos like latest Mission impossible are in part IMAX, so some **scenes** ARE 3840×2160 without black bars and some are not! So yes, I understand you confusion as on VLC you can just do cropping 2.39:1.

Now, you can just press schift+w many times in the beginning to crop it correctly like I do on my 3440x1440 display!

Now one can do cropping only on the active image area of the image data, after all that is how MaxFALL value is calculating, but it may be different to implement, yeah))

**Comment by Akemi** [comment]
yeah this is not possible. you should probably use the crop filter for this.
