### ISSUE TITLE
Unable to take a WebP screenshot

### ISSUE THREAD

**Issue by morning-paradigm** [mpv-player/mpv#7661]
### Important Information

- mpv 0.32.0
- macOS 10.14.5
- Homebrew installation

### Reproduction steps

1. Set `screenshot-format=webp` in mpv.conf
2. Try to take a screenshot
3. "Error writing screenshot!"

### Expected behaviour

mpv should save a webp screenshot (its support is confirmed in [#6832](https://github.com/mpv-player/mpv/pull/6832) and referenced in the manual).

### Actual behaviour

mpv fails to open libavcodec encoder (as can be seen in the log), leaving just a zero bytes webp file.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/4534898/output.txt)

Latest IINA based on mpv 0.32.0 behaves the same.
Taking a webp screenshot with FFmpeg in terminal works, so it's most likely an issue with mpv.

**Comment by Akemi** [comment]
works without problems on git master and `mpv --no-config --screenshot-format=webp`. try master instead and report back.

**Comment by morning-paradigm** [comment]
Master version worked, thanks.
