### ISSUE TITLE
Random hangs with high CPU usage after quickly traversing a youtube playlist

### ISSUE THREAD

**Issue by Earnestly** [mpv-player/mpv#7662]
* Distribution: Arch Linux (kernel 5.5.13)
* MPV Version:
```
mpv 0.32.0-386-g90737ec77d-dirty Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Thu Apr 23 12:11:12 BST 2020
FFmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
FFmpeg version: n4.2.2
```
* Window Manager: i3-wm (no compositor, X11 with xf86-video-intel)
* GPU: Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz

---

When using the following test case and mashing the playlist next (or clicking the playlist next button on the OSC) several times in quick succession mpv can (randomly) hang with 100% CPU usage:

```
mpv --no-config --vo=gpu 'https://www.youtube.com/playlist?list=PLFR78Uf6Xh3g9tmv0xcv98mDjhuHe_Ewm'
```

For quite some time now mpv often hangs with high CPU usage after skipping through several youtube playlist items quickly.  The source of the high CPU usage appears to be the thread `mpv/opener` which remains in an `R` state at 99%-100% usage (when viewed in `htop`).

Attempting to attach `strace` to the process only yeilds:

```
restart_syscall(<... resuming interrupted read ...>
```

The `mpv` process does not respond to `SIGTERM` but can be stopped with other signals such as `SIGALARM`.

### Expected behavior
Each playlist item should begin playing without causing mpv to hang.

### Actual behavior
mpv randomly hangs after jumping through multiple playlist items rapidly.  Either using the keybindings or clicking the OSC next/prev buttons.

### Log file
https://0x0.st/ijDq.txt

### Sample files
https://www.youtube.com/playlist?list=PLFR78Uf6Xh3g9tmv0xcv98mDjhuHe_Ewm

*PS: If you need more information please ask.  I'm not sure how to provide more meaningful details you may need.*

**Comment by wm4** [comment]
Most likely TLS shit.

**Comment by sfan5** [comment]
Switching ffmpeg to use `openssl` instead of `gnutls` might or might not help with this issue. Could be worth a try.

**Comment by Earnestly** [comment]
Try as I might, I can't reproduce this issue with `openssl`, so that seems like a solution, or at least points the issue at `gnutls`. Thanks for pointing me in the right direction.
