### ISSUE TITLE
seek in mp3 is slow

### ISSUE THREAD

**Issue by AxelTerizaki** [mpv-player/mpv#7663]
### Important Information

Provide following Information:
- mpv version : 0.32.0-410-g640db1ed3f
- Windows Version : 10 
- Source of the mpv binary : sourceforge
- Possible screenshot or video of visual glitches : https://cdn.discordapp.com/attachments/324208228680466434/704015140739088454/2020-04-26_19-03-10.mp4

I'm using mpv in an app of my own and communicate with it through the IPC socket.

When starting up a video or mp3, we use a lavfi-complex line (shown below) to display an avatar of the user who requested the video/mp3 in the right corner of the screen, durçing a limited time only.

When seeking (with the command `seek`) inside a mp3 (as shown in the video above) mpv takes a long time to actually get to the point in the mp3 file.

This does not happen on macOS.

This also does not happen on videos.

Using the keyboard arrows also produce this effect. (without using the IPC commands)

It happens on just any mp3 file.

It doesn't happen when disabling the avatar display (thus not using any lavfi-complex line)

### Reproduction steps

- Open an mp3 with a cover (haven't tried without one) and a subfile, as well as a lavfi-complex input : `lavfi-complex=nullsrc=size=1920x1080:duration=207[nl];[nl]setsar=1,format=rgba[emp];[vid1]scale=-2:1080[vidInp];[vidInp]pad=1920:1080:(ow-iw)/2:(oh-ih)/2[vpoc];movie=\\'J:/karaokemugen/app/avatars/29488d3e-4884-4535-bc7f-31828e86c430.circle.png\\'[logo];[logo][emp]scale2ref=w=(ih*.128):h=(ih*.128)[logo1][base];[vpoc][base]blend=shortest=0:all_mode=overlay:all_opacity=0[ovrl];[ovrl][logo1]overlay=x='if(between(t,0,8)+between(t,200,207),W-(W*29/300),NAN)':y=H-(H*29/200)[vo]`
- Try to seek inside

### Expected behavior

Should seek almost immediately to the desired point in the file.

### Actual behavior

As shown in my video, mpv seems to send back its seeking position littl eby little.

### Log file

https://pastebin.com/gRmu3rHQ

In ths long, a user starts the app, so it loads a background file, then the mp3 file. The subs are added then, and a `seek` command is sent.

### Sample files

mp3 file : https://kara.moe/downloads/medias/FRE%20-%20Aishite%20Knight%20-%20AUDIO%20IN%20-%20Freeway.mp3
ass file : https://kara.moe/downloads/lyrics/FRE%20-%20Aishite%20Knight%20-%20AUDIO%20IN%20-%20Freeway.ass

Thanks in advance for your help on this.

**Comment by AxelTerizaki** [comment]
I ran some more tests, apparently my mac user toggled off avatar display in my app, so it seems pretty normal that it does work on macOS. As soon as I can make him try to enable it again, I'll update the issue.

I apologize for the inconvenience, I'm still investigating from my side of things, but the issue still stands so far.

**Comment by AxelTerizaki** [comment]
My bad, it's not related to Windows at all, the same thing happens on mac.

The problem seems to lie into the lavfi-complex line, a friend is trying to look into making it better, but some help would be welcome.

**Comment by wm4** [comment]
Then it's probably because libavfilter has no concept of seeking. So the only way to get to the target timestamps is filtering (and discarding) all frames from time 0 to the target. It might be possible to add some sort of constant "repeating" video source (as demuxer or so) to mpv to compensate.

**Comment by AxelTerizaki** [comment]
Hmmm, what I don't quite understand is that it works just fine on videos, just not on audio files for some reason.

**Comment by Akemi** [comment]
duplicate and explanation: #8595
feature request: #8712
