### ISSUE TITLE
Hardware decoding not working with vulkan.

### ISSUE THREAD

**Issue by quantmint** [mpv-player/mpv#7666]
### Important Information

Provide following Information:
- mpv version
mpv 0.32.0
- Linux Distribution and Version
arch linux
- Source of the mpv binary
arch linux repo
- Window Manager and version
sway 1.4
- GPU driver and version
amdgpu kernel 5.6, amd vega 56

### Reproduction steps
Play any h264 or probably h265 file.
With this config h264 hardware decoding works:
```
profile=gpu-hq
scale=ewa_lanczossharp
dscale=mitchell
audio-device=pulse
audio-file-auto=exact
interpolation
video-sync=display-resample
tscale=oversample
gpu-api=opengl
gpu-context=wayland
hwdec=vaapi
```
with the same config, but:
```
gpu-context=waylandvk
gpu-api=vulkan
```
hardware decoding stops working.

### Log file
[withopengl.txt](https://github.com/mpv-player/mpv/files/4544274/withopengl.txt)
[withvulkan.txt](https://github.com/mpv-player/mpv/files/4544276/withvulkan.txt)

**Comment by haasn** [comment]
This is an [upstream issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/2854). The AMD vulkan drivers don't support vaapi yet.

There's nothing we can do about it except hard-coding undefined behaviour, but I don't want to.
