### ISSUE TITLE
mpv cannot play asx playlists

### ISSUE THREAD

**Issue by edmundlaugasson** [mpv-player/mpv#7667]
### Important Information

$ mpv --version
mpv git-2020-04-03-f9cc29e Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sat Apr  4 00:21:24 UTC 2020
FFmpeg library versions:
   libavutil       56.42.102
   libavcodec      58.77.101
   libavformat     58.42.100
   libswscale      5.6.101
   libavfilter     7.77.101
   libswresample   3.6.100
FFmpeg version: git-2020-04-03-a6e56d1

System:   Kernel: 5.3.0-46-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
           Desktop: MATE 1.22.2 info: mate-panel wm: marco 1.22.3 dm: LightDM 1.26.0 
           Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic

Graphics:  Device-1: NVIDIA GM107GLM [Quadro M2000M] vendor: Lenovo driver: nvidia v: 390.116 
           bus ID: 01:00.0 chip ID: 10de:13b0 
           Display: x11 server: X.Org 1.19.6 driver: nvidia unloaded: fbdev,modesetting,nouveau,vesa 
           compositor: marco v: 1.22.3 resolution: 2560x1440~60Hz 
           OpenGL: renderer: Quadro M2000M/PCIe/SSE2 v: 4.6.0 NVIDIA 390.116 direct render: Yes

Repository
           Active apt repos in: /etc/apt/sources.list.d/mc3man-mpv-tests-bionic.list 
           1: deb http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu bionic main
           2: deb-src http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu bionic main

### Reproduction steps
Tried with --no-config - didn't help.

Try to play following URLs:
http://somafm.com/wma128/deepspaceone.asx
http://somafm.com/wma128/groovesalad.asx
http://somafm.com/wma128/missioncontrol.asx

tried:
`mpv http://somafm.com/wma128/missioncontrol.asx`
... did not work at all

`mpv --playlist=http://somafm.com/wma128/missioncontrol.asx`
... not playing and giving errors, which are posted under logs

But:
`mplayer -playlist http://somafm.com/wma128/missioncontrol.asx`
... works! **Why mpv cannot play but mplayer can?**
```
$ mplayer -v
MPlayer 1.3.0 (Debian), built with gcc-7 (C) 2000-2016 MPlayer Team
```

### Expected behavior
Radio will play like with mplayer.

### Actual behavior

Radio will not play, bunch of garbage on command-line like seen in log.

### Log file

https://0x0.st/iefn.log - used the youtube-dl version available in Linux Mint 19.3 repository: 2018.03.14-1ubuntu18.04.1

https://0x0.st/ieOu.log - used latest youtube-dl, manually downloaded from https://yt-dl.org/downloads/latest/youtube-dl
```
$ youtube-dl --version
2020.03.24

```
### Sample files
No sample files available. Just logs.

**Comment by wm4** [comment]
Probably a WONTFIX. ASX is an ancient, Microsoft specific XML playlist format - it would require either a full XML parser, or the mess that mplayer had (which I removed from mpv 6 years aho and about which nobody ever complained about).

You can download and open the ASX files with a text editor, and extract the stream links manually.

**Comment by mc4man** [comment]
Those links are also ancient, that site doesn't really use anymore, they use .pls (mp3 & aac
Your wma128 asx actually are the 128-mp3 .pls offered from site.

**Comment by edmundlaugasson** [comment]
Well - mpv is a fork of MPlayer, right? MPlayer plays those "ancient" links easily - why not mpv? So far I understood that mpv is at least as powerful as mplayer and even more. But it seems like it is not.

**Comment by wm4** [comment]
ASX parsing was removed for security reasons, and not reimplemented because it was rare. mplayer has multiple inherent issues that make using playlists with it simply unsafe.

**Comment by edmundlaugasson** [comment]
I see. If there is no real solution for asx then what we can say....

**Comment by paulguy** [comment]
Write a script to convert them to .pls and have it run mpv pointing to it?

**Comment by edmundlaugasson** [comment]
Not a programmer, although some (bash) scripting I know. Currently it seems too challenging for me.

**Comment by CogentRedTester** [comment]
This seemed interesting, so I tried writing a script to do this. It's probably the most hacky thing I've ever written (it parses the file by running the loadlist command and treats each entry in the playlist as a new line), but it seems to work. There may well be security issues with this, I have no idea, depends if loading random asx files with the loadlist command can do anything.

There's probably an easier way to do this, but it doesn't look like anyone but you will ever use this script, so I don't want to spend much time on it.

Here: https://github.com/CogentRedTester/mpv-scripts/blob/master/asx.lua

**Comment by Akemi** [comment]
i think this is off the table, closing.
