### ISSUE TITLE
libmpv: add option to get subtitles with formatting

### ISSUE THREAD

**Issue by purringChaos** [mpv-player/mpv#7668]
### Expected behavior of the wanted feature
- Return the subtitles as before with ASS style information in order to style it, rather than stripping off the formatting.

**Comment by CounterPillow** [comment]
I'm not exactly sure how you expect mpv to return HTML from ASS subtitles.

**Comment by NamedKitten** [comment]
Not HTML exactly but some standard format that can be used to turn into HTML or some other format on my end. I can easily display ASS subtitles but I can't get them from MPV's API.

**Comment by NamedKitten** [comment]
Updated to make it more clear.

**Comment by wm4** [comment]
Implemented something in c6369933f1d9cd204b09be95ef7d4ed1351610e2. No idea if it's what you want. If it's not, I don't think it can be implemented in general.

**Comment by purringChaos** [comment]
looks about right, thank you
