### ISSUE TITLE
Add the ability to name --stream-record dynamically

### ISSUE THREAD

**Issue by yassinebridi** [mpv-player/mpv#7669]
### Expected behavior of the wanted feature
I play a lot of Youtube playlists, and i need to keep them saved in my PC.
The problem is, the `--stream-record` option hard-name them, without giving the option to dynamically fetch the title of the playing video and name it the recorded stream.
### Alternative behavior of the wanted feature
I have to write an external script that will hack through this.

**Comment by garoto** [comment]
>I play a lot of Youtube playlists, and i need to keep them saved in my PC. 

Shouldn't you be looking at using an application which exist for this purpose alone, like [youtube-dl](https://github.com/ytdl-org/youtube-dl)?

>the --stream-record option hard-name them [...]

Other than using a proper script with title fetching & text substitution and whatelse, this has the potential to create reasonably unique filenames if you really need to have a keybind set for it: `mpvclip-${percent-pos}%_${=time-pos}.{ts|mkv}`

**Comment by wm4** [comment]
Not sure about this. Screenshots have something like this, but do we really need it for this option? Maybe yes, maybe no.
A script could handle it for sure. To get all of the stream, it'd have to set a hook to run at a point before the demuxer is opened.

**Comment by yassinebridi** [comment]
I just thought it might be interesting, for someone who play a lot of videos, not necessarily a playlist.
This thought would definitely work for me, thanks.
>  this has the potential to create reasonably unique filenames if you really need to have a keybind setup: `mpvclip-${percent-pos}%_${=time-pos}.{ts|mkv}`

**Comment by garoto** [comment]
> Screenshots have something like this, but do we really need it for this option? Maybe yes, maybe no.

Can the screenshot filenaming routine be painlessly transporterted to the `--stream-record` one? If so, then that'd be pretty fricking neat.
