### ISSUE TITLE
Inconsitency between loop and loop-playlist

### ISSUE THREAD

**Issue by j-holub** [mpv-player/mpv#7676]
### Important Information

Provide following Information:
- mpv version: 0.32.0 
- Platform and Version: MacOS 10.15.3

Hey there,

while working my NodeJs Wrapper for mpv that uses the JSON IPC API, I stumbled upon an inconsistency between the properties `loop` and `loop-playlist`. I'm not sure if that is desired or expected behaviour (I can work around that easily) or an inconsistency that is probably the result of the evolution of the code.

### Reproduction steps

I hope it's okay that I'm not writing any code here but just simple instructions

```
set loop to 'inf'
set loop-playlist to 'inf'
get loop property
get loop-playlist property
```

### Expected behavior

This (preferably)
```
loop is true
loop-playlist is true
```
or this
```
loop is 'inf'
loop-playlist is 'inf'
```

### Actual behavior

```
loop is true
loop-playlist is 'inf'
```

**Comment by wm4** [comment]
Both are separate properties. loop is an alias to loop-file, which loops the currently playing file without reloading it (so it's different from loop-playlist even if there's only 1 playlist entry).

**Comment by j-holub** [comment]
Thanks for the quick response and clarification that this is expected/desired hebaviour.

I was aware that these are two different properties. I just find in unintuitive that if I set the one to 'inf' it returns true but the other one returns 'inf' if I set it to 'inf'. Then I will just work around this to make my wrapper's API consistent.

**Comment by wm4** [comment]
Oh, I didn't notice that part (even though you pointed it out clearly), and I guess my conclusion was too early.
So, it seems the true vs. "inf" is because internally, the "yes" choice is ordered before "inf" in loop-file, so the generic code converts it to a bool property. I _could_ change it, and the "yes" choice is only for compatibility anyway.
Any suggestions?

(I think making properties return different types depending on their values was a bad choice... proper sum types would have been pretty nice and clean, but nothing maps well to json anyway.)

**Comment by j-holub** [comment]
I mean I the type is ambiguous anyways, because you can set **loop** and **loop-playlist** to a number which loops for that amount of time. So if I set loop to 5, `get-property` for **loop** will return 5, an Integer. if I set **loop** to `inf` or `no` it will return *true* or *false*, a boolean.

In the case of **loop-playlist** it can return an Integer (like 2 or 5 times looping the playlist), a boolean *false* if **loop-playlist** is set to *off* (aka `no`) and a string *inf*, if **loop-playlist** is set to `inf`.

That's why I would prefer it in the style of **loop**, because then we only have two types and it seems more consistent. Is loop on? -> *true*, Is loop off? -> *false*, as opposed to Is loop on? -> `inf`, is loop off? -> *false*.

I agree that it is a weird choice to have properties return different types but I see the difficulty with primitive types.
