### ISSUE TITLE
Error encoding

### ISSUE THREAD

**Issue by FlappyFalcon** [mpv-player/mpv#7678]
- mpv version 20200426-git-640db1e
- Win10

I'm trying to encode using this plugin https://github.com/ekisu/mpv-webm .
I have added `additional_flags = "--vf-add=format=yuv420p --ovcopts-add=profile=high --ovcopts-add=level=4 --vf=fps=\"24000/1001\"",` into additional flags but I get an error. When I remove `--vf=fps=\"24000/1001\"` it encodes but I want the video to be at that fps. Log file attached
[log.txt](https://github.com/mpv-player/mpv/files/4571522/log.txt)

**Comment by bitraid** [comment]
The error that your log gives, is that you are using `high` profile for a 10 bit encode (should be `high10`).

**Comment by FlappyFalcon** [comment]
> The error that your log gives, is that you are using `high` profile for a 10 bit encode (should be `high10`).

Ah, that seems to have fixed the error. Though now the issue is that it encodes at only 1080p even though I select the output to be 480p.

**Comment by bitraid** [comment]
I suggest you first try to perform the encode directly with mpv, and if you find something wrong, then report the issue without skipping the template. Otherwise, report your problem to the script.

**Comment by Akemi** [comment]
fixed
