### ISSUE TITLE
How do I set cache size after updating mpv?

### ISSUE THREAD

**Issue by bpsib** [mpv-player/mpv#7679]
I have updated mpv to 0.32.0 but the option I used for setting the cache size no longer works. I now get the following error:
```
Invalid value for option cache: 60000
Valid values are:
    no
    auto
    yes
Error parsing option cache (option parameter could not be parsed)
Setting commandline option --cache=60000 failed.
```

There was no such problem with mpv 0.29.1

**Comment by CounterPillow** [comment]
`demuxer-max-bytes`

Please read https://github.com/mpv-player/mpv/blob/master/DOCS/interface-changes.rst

**Comment by bpsib** [comment]
> - with the removal of the stream cache, the following properties and options were
>      dropped: `cache`, `cache-size`, `cache-free`, `cache-used`, `--cache-default`,
>      `--cache-initial`, `--cache-seek-min`, `--cache-backbuffer`, `--cache-file`,
>      `--cache-file-size`
>    - the --cache option does not take a number value anymore

How can I increase the rewind buffer of live/stdin streams now these options are removed?
