### ISSUE TITLE
Incorrect OSD information about frame rate

### ISSUE THREAD

**Issue by hooke007** [mpv-player/mpv#7680]
- mpv version：latest
- Windows Version ：win10 1909
- related：vapoursynth-mvtools

Problem detail: https://github.com/dubhater/vapoursynth-mvtools/issues/46

After I succeeded to make a video  play at 60fps, it still shows the original frames rate.

**Comment by wm4** [comment]
Estimated FPS = what comes out of the filter chain.

**Comment by hooke007** [comment]
> Estimated FPS = what comes out of the filter chain.

However, it shows correct in Linux.
<a href="https://sm.ms/image/BVznETYpL3GJ1v2" target="_blank"><img src="https://i.loli.net/2020/05/04/BVznETYpL3GJ1v2.jpg" /></a>

**Comment by Akemi** [comment]
since you ignore the issue template it's hard to answer any questions or to find the cause of your problem. open a new issue with all infos provided.
