### ISSUE TITLE
How to overwrite key bindings set by third party lua script/conf files?

### ISSUE THREAD

**Issue by c02y** [mpv-player/mpv#7685]
I got several key bindings set by third party lua script/conf file, but I want to set those keys to the builtin commands of mpv in ~/.config/mpv/input.conf

How can I do this?

If the third party lua script/conf matters, It is 
~~~
mp.add_key_binding("p", "saveplaylist", save_playlist)
~~~
from https://github.com/jonniek/mpv-playlistmanager/blob/9f9f6fffb76e6c814a94b9f874f5dcd6e29490d7/playlistmanager.lua#L969

**Comment by CogentRedTester** [comment]
If you want to overwrite those keys just un-comment the relevant line in input.conf. input.conf has higher priority than the script bindings.

If you want to change these script keybinds [this](https://mpv.io/manual/master/#command-interface-script-binding) is the relevant command. Whenever you see these `mp.add_key_binding` calls in scripts the middle string is the name of the keybind, so that is what you would use with the command I linked.

**Comment by c02y** [comment]
> If you want to overwrite those keys just un-comment the relevant line in input.conf. input.conf has higher priority than the script bindings.
> 

I believed so, but I already used **p show-progress** in my input.conf, it doesn't work as expected, **p** is still using function set in thiry party lua script, so I posted an issue here.


> If you want to change these script keybinds [this](https://mpv.io/manual/master/#command-interface-script-binding) is the relevant command. Whenever you see these `mp.add_key_binding` calls in scripts the middle string is the name of the keybind, so that is what you would use with the command I linked.

It seems "mp.add_key_binding" in lua script cannot be overwritten in input.conf unless I modify the lua script directly.

**Comment by wm4** [comment]
Should work, unless it regressed. Check that.

**Comment by Argon-** [comment]
> It seems "mp.add_key_binding" in lua script cannot be overwritten in input.conf unless I modify the lua script directly.

This script is also calling https://mpv.io/manual/master/#lua-scripting-mp-add-forced-key-binding(-) but I didn't check for which keys.

**Comment by CogentRedTester** [comment]
I should mention that I am using that exact script, and i can rebind the key just fine.

**Comment by c02y** [comment]
Problem solved, the line **default-bindings start** in input.conf shouldn't be enabled.

Doesn't this line mean that the cofigs after this line should be enabled by default.

**Comment by garoto** [comment]
What's wrong with commenting the relevant Lua script bits? 

![screenshot-0696-06-05-2020](https://user-images.githubusercontent.com/11768175/81232993-4c094e00-8fcc-11ea-9911-eccbe2032894.png)

**Comment by wm4** [comment]
> Problem solved, the line default-bindings start in input.conf shouldn't be enabled.

No, it marks them as default, so they have lower priority than user bindings, and later default bindings (like from scripts) can override them.

**Comment by c02y** [comment]
> What's wrong with commenting the relevant Lua script bits?
> 
> ![screenshot-0696-06-05-2020](https://user-images.githubusercontent.com/11768175/81232993-4c094e00-8fcc-11ea-9911-eccbe2032894.png)

I just don't want to touch the third party lua script/config files since I need to update them in the future.

**Comment by blueray453** [comment]
In case of ` mp.add_key_binding("p", "saveplaylist", save_playlist)`

you have to add `p ignore` in `input.conf` file. Then to rebind it to another key, you have to do something like `Ctrl+p script-binding saveplaylist`

So the input.conf file entry will look like:

```
p ignore
Ctrl+p script-binding saveplaylist
```

**Comment by vanbang9710** [comment]
How to overwrite [forced keybind](https://[mpv.io](https://mpv.io/manual/master/#lua-scripting-mp-add-forced-key-binding(-))/manual/master/#lua-scripting-mp-add-forced-key-binding(-)) in input.conf?
