### ISSUE TITLE
[Q] Is there a way to buffer the glsl shaders so that we can use them on slower machines?

### ISSUE THREAD

**Issue by NightMachinary** [mpv-player/mpv#7686]
My 2016 Macbook Pro can't handle [anime4k](https://github.com/bloc97/Anime4K) shaders in realtime, but I think allowing it to build a buffer of like 5 minutes should make a realtime play of anime episodes possible.
([Same issue](https://github.com/bloc97/Anime4K/issues/86) filed on anime4k)

**Comment by Argon-** [comment]
But then, where do you draw the line? What if someone needs a buffer of 8 min or 12?
In this case, why don't you just make it a 25min buffer for the whole episode? This is nothing else than re-encoding the file and deleting the new encode after watching.
In your specific case: start a re-encode and begin watching the file after 5 min.

**Comment by wm4** [comment]
It's not possible.

**Comment by NightMachinary** [comment]
@Argon- Is there a way to reencode the file with these shaders using mpv? (I'm on macOS)

**Comment by wm4** [comment]
vf_gpu exists, but it doesn't work on osx.
