### ISSUE TITLE
Toggling sub-ass-override during runtime doesn't work

### ISSUE THREAD

**Issue by Silver-Fullbuster** [mpv-player/mpv#7689]
### Important Information

Toggling `sub-ass-override` to 'yes' or 'no' doesn't work during runtime (or works partially). Toggling to 'force' works but then `sub-ass-styles` (and possibly other options) don't take effect. Using `sub-ass-override` set to yes and playing mpv produces different results than opening mpv with `sub-ass-override` set to no and toggling to yes in runtime.

Provide following Information:
- mpv version - mpv-x86_64-20200426-git-640db1e
- Windows Version - Windows 10 v1909 64-bit [Version 10.0.18363.778]
- Source of the mpv binary - Shinchiro build

Images:
With `sub-ass-styles` set to a template ass file and `sub-ass-override` set to yes
![image](https://user-images.githubusercontent.com/22327220/81194181-f471df00-8fd9-11ea-846f-93956dbc5342.png)

With `sub-ass-styles` set to a template ass file and `sub-ass-override` set to no
![image](https://user-images.githubusercontent.com/22327220/81197151-90511a00-8fdd-11ea-9ebd-e3a7f031f24f.png)
Toggling sub-ass-override to yes during runtime produces no change.

### Reproduction steps

`mpv --no-config --sub-ass-styles="D:\template.ass" --input-conf="D:\input.conf" --sub-ass-override=no --logfile="D:\mpv.txt" <videofiile with embedded subtitles>`
input.conf is used to set keybind as: `u cycle-values sub-ass-override "yes" "no"`

### Expected behavior

Toggling `sub-ass-override` during runtime should render the same as mpv opening with the set value

### Actual behavior

Toggling `sub-ass-override` during runtime doesn't affect subtitle rendering

### Log file

[mpv.txt](https://github.com/mpv-player/mpv/files/4587677/mpv.txt) (of trying to change sub-ass-override during playback)

### Sample files

The ass file used for setting `sub-ass-styles`: 
[template.ass.txt](https://github.com/mpv-player/mpv/files/4587678/template.ass.txt)
(added .txt to workaround Github upload restrictions)

**Comment by thebombzen** [comment]
I can confirm on Linux using git master that in the provided scenario, toggling `sub-ass-override` at runtime does nothing in either case, but providing a different value on launch produces different results.

**Comment by thebombzen** [comment]
Upon further inspection, it appears that `sub-ass-override=yes` just adds the default styles from the provided file to the subtitle track. If one were to toggle it to `no` at runtime, sd_ass.c would need to purge the styles added from the file. I'm not sure if there's a better way to go about doing this, but I don't think there's an easy one-line fix.

**Comment by wm4** [comment]
Yes, that applies to --sub-ass-force-style and --sub-ass-styles. Probably fixable by going through full reinit, but I don't want to.

**Comment by wm4** [comment]
Changed my opinion. Looking at this some more, it appears the code should also react to sub-ass-override changing, but I didn't include that in the commit.
