### ISSUE TITLE
Stuttering on panning shots with a 1440p, 144hz monitor and a nvidia GPU

### ISSUE THREAD

**Issue by Unser395** [mpv-player/mpv#7690]
### Important Information

Provide following Information:
- mpv version = 0.32
- Linux Distribution and Version = Manjaro
- Source of the mpv binary = Manjaro repository
- If known which version of mpv introduced the problem = no
- Window Manager and version = i3
- GPU driver and version = nvidia 2080 rtx with 440.82 driver

### Reproduction steps

Here are the relevant parts of my config :
https://0x0.st/i2k9.conf
I use it on a 1440p monitor with a 144hz monitor.

I've been advised to modify FSRCNNX_x2_8-0-4-1.glsl in order to make the upscaling work.
Every lines mentioning the following in FSRCNNX : 
`//!WHEN OUTPUT.w LUMA.w / 1.4 > OUTPUT.h LUMA.h / 1.4 > `
Has been replaced with : 
`//!WHEN OUTPUT.w LUMA.w / 1.3 > OUTPUT.h LUMA.h / 1.3 > *
`
`ForceFullCompositionPipeline` has been enabled.
Picom is my compositor and the issue is not fixed even when it's disabled.
Vsync is actually disabled in Picom, but I've tried to put it on as well.
Everything that is mentioned in the "Tearing" part of the wiki has been tested.
I have no tearing in video games.

V-sync jitter is approximately at 0.340 when the monitor is put at 144hz.
When it is at 60hz, it improves but fluctuates between 0.008 and 0.120.

gpu-api=vulkan is not activated because v-sync jitter is worse, at 0.700-800.

The issue is still present with --no-config.

### Expected behavior

I want to have the best viewing experience with my setup and fix the fluidity issues I have during panning shots. Any help is welcome ! 

Unfortunately, I don't have any experience with programming but I'm comfortable with the terminal. I'll do my best.

### Actual behavior
Videos stutters/flickers/tears (don't know what's the right word for it, but I've included a sample file so you can see) when the camera is doing a panning shot or a tracking shot.

### Log file
https://0x0.st/i2ds.txt

EDIT : Here are the logs with --no-config, the first is with the monitor at 60hz, the other at 144hz : 
https://0x0.st/i_ql.txt
https://0x0.st/i_qU.txt

Let me know if you need a log file when the screen is at 60hz. It lowers v-sync jitter as I've said before, but it doesn't fix the issue.

### Sample files
https://0x0.st/i2dM.mkv
https://0x0.st/i2dj.mkv

First file looks better IRL.
I've never done that before so let me know if I need to re-record the sample files with a lower framerate. The videos have a 144 framerate. It's been recorded with simplescreenrecorder and it asks to disable flipping. 

Thank you very much.

**Comment by Akemi** [comment]
if it happens with --no-config you should make a log file with --no-config, so we can eliminate all unnecessary causes.

**Comment by haasn** [comment]
Your sample file has some pretty insane tearing. No doubt that's the first thing you should try fixing. The wiki has an article on this iirc.

Do you get tearing with `glxgears`?

**Comment by Unser395** [comment]
Hello, thanks to both of you for your answers, and very sorry for the delay, I'm quite busy these days but I'm always going to answer.

> if it happens with --no-config you should make a log file with --no-config, so we can eliminate all unnecessary causes.

Here are two log files with --noconfig, one with 60hz and the other with 144hz :
https://0x0.st/i_ql.txt
https://0x0.st/i_qU.txt

I'm going to add both to the OP.

> Your sample file has some pretty insane tearing. No doubt that's the first thing you should try fixing. The wiki has an article on this iirc. (Assuming that's not just an issue with the recording setup)

Yes, they are not close at all to what I see. Unfortunately, I don't find a way to record accurately what's showing on my monitor. I've tried simplescreenrecorder with placebo settings, and It's not really better with ffmpeg. If you have the time to share a command that would record my issue, i will run it !
> 
> Do you get tearing with `glxgears`?

I get absolutely no tearing with glxgears, it's smooth.
> 
> Edit: I see you already mentioned having gone through the wiki and stuff. I'm not sure if there's much else I can think of to help you, but make sure it's an mpv-exclusive issue. Also try using vulkan to see what happens.

Yes, I've tried everything that is on the wiki and i've tried adding nvidia-drm.modeset=1 to my grub. Vulkan doesn't improve the situation I'm afraid, I just get a higher jitter (0.600-700).

Is it possible that it's an issue with 144hz monitor ? I've plugged the 1440p monitor to a computer that is 100% AMD, chose gpu-api=vulkan, and even though the jittering was lower, panning shots where not perfectly smooth (I was using interpolation, video-sync=display-resample and tscale=oversample).

I've tried the same computer (AMD cpu and gpu) with a 1080p 144hz monitor, and it was still not perfect. Unfortunately, I don't have a 1080p 60hz monitor.

I finally tried the same settings on an old laptop which has an intel cpu and nvidia gpu and the panning shots were great. The monitor is 1080p, 60hz. 

Here's what I noticed : on the laptop, the V-sync jitter stayed at 0.02 all the time, the displayed estimated FPS where very consistent.
On my main config, both are not consistent at all. When the monitor is at 60hz, the lowest v-sync jitter is 0.08 but it often goes to 0.150. Estimated displayed FPS jumps have more variation as well.
When the monitor is at 144hz, it goes from 0.300 to 0.400 and lots of frames are mistimed and delayed.

Let me know if you need me to test any more things or need more information, I'll do my best. And thanks again for your time, I hope you both have a nice day !

**Comment by Hrxn** [comment]
You could try if you the same stuttering when running mpv + [SVP](https://www.svp-team.com/)

**Comment by haasn** [comment]
Can you make a log with interpolation enabled and `msg-level=vo=trace`? That should at least help us figure out what's actually being rendered by mpv.

**Comment by Unser395** [comment]
> You could try if you see the same stuttering when running mpv + [SVP](https://www.svp-team.com/)
Thanks for the suggestion but it's the same !

> Can you make a log with interpolation enabled and `msg-level=vo=trace`? That should at least help us figure out what's actually being rendered by mpv.

Here it is  : https://0x0.st/i_mJ.txt
I'm trying to find a way to correctly record what I'm seeing.

**Comment by haasn** [comment]
Your log shows a clean pattern. Every frame is repeated exactly 6 times, looking at a 1-second interval. No blends, no drops, no delays.

By all accounts there should be no visible stuttering being introduced by mpv here. Tempting to close this as "not an mpv bug" on that grounds alone.

Do panning shots play without stuttering in VLC or other video players?

**Comment by lextra2** [comment]
the screentearing/stuttering is literally encoded into your videostream. not the fault of mpv.

**Comment by Akemi** [comment]
if you mean the sample files, those are screen recordings to show the tearing. the actual played back file wasn't linked.

**Comment by lextra2** [comment]
> 
> 
> if you mean the sample files, those are screen recordings to show the tearing. the actual played back file wasn't linked.

yeah. my bad.

**Comment by Hrxn** [comment]
Well, just to be sure, try it with a different monitor, preferably 60 Hz.

**Comment by enkore** [comment]
For video consumption I'd advise to just use 120 Hz, since that enables a smooth pull-up from 30/60 fps video without requiring full frame rate conversion or introducing frame pacing issues. For movie consumption, use 144 Hz (144/24 = 6).

**Comment by Dudemanguy** [comment]
Does not appear to be an mpv issue judging from the conversation.
