### ISSUE TITLE
LIBMPV How to Configure From App

### ISSUE THREAD

**Issue by mysteryx93** [mpv-player/mpv#7691]
I'm using this wrapper to interface with LIBMPV from .NET
https://github.com/hudec117/Mpv.NET-lib-

I want to connfigure it with this audio filter

    --af=rubberband=pitch-scale=0.981818181818181

What would be the approach to configure this into the DLL version of MPV?

**Comment by Akemi** [comment]
if it uses libmpv it either has to set the property or load a config file from somewhere. how to do that is a question for that repo.

**Comment by mysteryx93** [comment]
For reference, found the solution here
https://github.com/mpv-player/mpv/blob/master/libmpv/client.h#L1128

SetPropertyString
