### ISSUE TITLE
OSC with touch screen

### ISSUE THREAD

**Issue by soloturn** [mpv-player/mpv#7693]
on arch linux, gnome 3-36, wayland, mpv is great to use with the mouse thanks to the auto-appearing OSC. finger touches are a little challenge though. i fail to forward the video, change the language.

at first OSC did not stay long enough to touch something else. thanks for help, @bpsib in #7652, to keep OSC on screen using the DEL key.

the following happens in the main window:
* touch, one finger: OSC appears
* double touch, one finger: toggle between full screen and normal size
* touch, two fingers: window sometimes jumps to a different position
* touch&move, one finger: nothing happens
* touch&move, two fingers: window moves
* touch&pinch, two fingers: window moves

in the progress bar, language selector, subtitle selector:
* touch, one finger, progress bar: time shows
* touch, one finger, language selector, subtitle selector: nothing happens.
* double touch, one finger: nothing happens
* touch&move, one finger: window resizes

```
$ mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.2
```

**Comment by Dudemanguy** [comment]
There's some touch-related code in wayland but I've never tested it. Some of this behavior definitely sounds less than ideal. I suppose the touch stuff could be smarter and try to distinguish between one finger and two fingers being down at the same time. It currently has the built in assumption that only one finger is down at max. I don't really know why the behavior would be different/weird in the osc section. That doesn't make sense to me.

**Comment by CogentRedTester** [comment]
I don't know anything about touch events, but if you want the osc to stay visible for longer you can use the osc-hidetimeout script-opt instead of toggling the visibility.

**Comment by wm4** [comment]
The core (and thus the OSC) was written for the mouse, so there's also an assumption that there's only at most 1 "touch" point.

**Comment by Dudemanguy** [comment]
Cool, I won't bother trying any fancy two-touch interactions with the OSC then. It would still be possible to implement something like a two touch pinch resize on the client side in wayland though.

One thing I did just remember was that gnome has no border by default so it triggers the osc-windowcontrols. What might be happening here with the osc touch issues is that you're triggering the osc-windowcontrols part of the code since it's so close to the border of the window (it would explain why touch & move resizes for instance). @soloturn: could you try touching the osc again but using `--script-opts=osc-windowcontrols=no`?

**Comment by Dudemanguy** [comment]
The above comment is wrong btw. The touch event actually uses the `--wayland-edge-pixels-touch` option which has nothing to do with the osc-windowcontrols. The default for that is 64 which is possibly way too big?

**Comment by Dudemanguy** [comment]
Old issue, but this should be reasonably functional now. If anyone wants some fancier touch feature, feel free to open a feature request.
