### ISSUE TITLE
Simple questions: Stretch to remove letterboxing and log.txt command 

### ISSUE THREAD

**Issue by Maikurosofuto** [mpv-player/mpv#7694]
As the title implies i have two simple questions. First, i tried to make a log file but i can't even use the console, and the command --log-file=<path> seems to not work with mpv.conf neither the console. Can someone explain a simple way to use it right? I even tried to use with CMD, but i just keep getting a invalid argument error.

The next question is about letterboxes in "4K" videos, i already know that is possible to zoom in/out or even move the video pos x/y, but it's possible to stretch the video to remove black bars? I mean, i have a 1080p monitor and looks like the so called "4K" movie is 3840x2160 with letterbox and 3840x1600 without it, is possible to just stretch until the bar's gone?

My conf: [mpv.txt](https://github.com/mpv-player/mpv/files/4591786/mpv.txt)

Example of what i'm getting:
![Bars](https://user-images.githubusercontent.com/36323363/81273609-8226ec00-9025-11ea-92d6-106ddd25d983.jpg)

Example of what i'm trying to achieve:
![NoBars](https://user-images.githubusercontent.com/36323363/81273754-bf8b7980-9025-11ea-8784-a7950c644298.jpg)

**Comment by Akemi** [comment]
something along the lines should work for fullscreen `--vf=crop=iw:ih-280*2:0:280 --no-keepaspect`. should also replace the `280` with your borders.

**Comment by Maikurosofuto** [comment]
> 
> 
> something along the lines should work for fullscreen `--vf=crop=iw:ih-280*2:0:280 --no-keepaspect`. should also replace the `280` with your borders.

Sorry for bothering, but could you tell me where to put these commands? Because, as said with log.txt, i can't make it work, either via mpv.conf or using the in-player console.
