### ISSUE TITLE
stats vs. OSD gap

### ISSUE THREAD

**Issue by mkoskar** [mpv-player/mpv#7695]
### Important Information

Provide following Information:
- mpv version: 
    ``mpv 0.32.0-429-g326c55a571`` 326c55a5713b9aa54317873554c1d11e4dfffe9f
- Linux Distribution and Version: 
    ``ArchLinux``
- Source of the mpv binary:
    built by https://aur.archlinux.org/packages/mpv-git/
- If known which version of mpv introduced the problem:
    same issue with ``v0.32.0`` release

### Reproduction steps

```
    $ mpv --no-config <file>

    * press O (set osd-level 3)
    * press I (stats/display-stats-toggle)
    * see screenshot1
    * press 2
    * see screenshot2
    * press 3
    * see screenshot3
```

### Expected behavior

There **shouldn't be** vertical gap in screenshot3 between OSD and stats output.

### Actual behavior

There **is** vertical gap in screenshot3 between OSD and stats output.

* screenshot1
![screenshot1](https://user-images.githubusercontent.com/4387891/81323049-18dec180-9095-11ea-8649-f6157e6ead30.png)

* screenshot2
![screenshot2](https://user-images.githubusercontent.com/4387891/81323057-1d0adf00-9095-11ea-8faa-23812da7de4b.png)

* screenshot3
![screenshot3](https://user-images.githubusercontent.com/4387891/81323063-1f6d3900-9095-11ea-8599-c4b7699d33e0.png)

**Comment by wm4** [comment]
What you mean is: stats page 2 has an empty line or so at the top.

**Comment by avih** [comment]
Is it related in any way to the OSD level? to me it seems that pages 3 and 4 of the stats just start a bit lower than pages 1 and 2. And when you you enable OSD level 3 then all pages move the same distance down, But that gap above pages 3 and 4 is there for me also without changing the OSD level.

**Comment by mkoskar** [comment]
Right @wm4 page 3 and 4 as @avih mentioned.

I'm not saying there should be any, 1 or 2 newlines, more like consistency. Just a minor thing I've noticed while playing along with OSD.

Btw. all of them start at the same level without OSD for me. It seems like extra prefix newlines are "squashed / ignored" without OSD. Not sure how to explain discrepancy between me and @avih. Ideas?

This seems to bring it at same level:

```diff
diff --git a/player/lua/stats.lua b/player/lua/stats.lua
index 8e1940d75f..da67e05319 100644
--- a/player/lua/stats.lua
+++ b/player/lua/stats.lua
@@ -631,7 +631,7 @@ local function perf_stats()
     eval_ass_formatting()
     add_header(stats)
     local page = pages[o.key_page_4]
-    append(stats, "", {prefix=o.nl .. o.nl .. page.desc .. ":", nl="", indent=""})
+    append(stats, "", {prefix=page.desc .. ":", nl="", indent=""})
     page.offset = append_general_perfdata(stats, page.offset)
     return table.concat(stats)
 end
@@ -649,7 +649,7 @@ local function cache_stats()
 
     eval_ass_formatting()
     add_header(stats)
-    append(stats, "", {prefix=o.nl .. o.nl .. "Cache info:", nl="", indent=""})
+    append(stats, "", {prefix="Cache info:", nl="", indent=""})
 
     local info = mp.get_property_native("demuxer-cache-state")
     if info == nil then
```

**Comment by Dudemanguy** [comment]
The resent stats changes fixed this I think (too lazy to find the actual commit but said gap isn't there anymore).
