### ISSUE TITLE
Subtitle files matching with language code issue

### ISSUE THREAD

**Issue by blackarcher21** [mpv-player/mpv#7702]
### Important Information

Provide following Information:
- mpv version - mpv 0.32.0-410-g640db1ed3f
- Platform and Version - Windows 10 1703 64-bit
- Source of the mpv binary - https://sourceforge.net/projects/mpv-player-windows/

### Reproduction steps
Files:
file.mp4
file 2.mp4
file.srt
file 2.srt
file 2.en.srt

Open the video files and see which subtitle is loaded
mpv plays **file 2.mp4** with **file 2.srt** and **file 2.en.srt** which is expected but there is problem with **file.mp4**

### Expected behavior
mpv plays **file.mp4** with **file.srt** only

### Actual behavior
mpv plays **file.mp4** with **file.srt** and **file 2.en.srt**

### Log file
[log.txt](https://github.com/mpv-player/mpv/files/4598281/log.txt)

**Comment by blackarcher21** [comment]
thanks for the fix but now I have another issue after this fix
1. subtitle file with language code like en_US or en-US (sometimes I found and grabbed them fromvlive or youtube) is not loaded unless I use --sub-auto=fuzzy but that will behave like issue above (which probably thats how --sub-auto=fuzzy works) 
[sub_auto_exact_after_file2_log.txt](https://github.com/mpv-player/mpv/files/4605771/sub_auto_exact_after_file2_log.txt)

2. subtitle files with language code is not displayed by default like before.

**Comment by wm4** [comment]
OK, but not sure if I care. There's probably multiple dozen language-code-in-filename conventions, against which we'd all fail to recognize at some point.
