### ISSUE TITLE
Hardware Decoding not working with YouTube.

### ISSUE THREAD

**Issue by Maikurosofuto** [mpv-player/mpv#7705]
### Important Information

Provide following Information:
- mpv version: mpv 0.32.0-410-g640db1ed3f
- Platform and Version: Windows 10 - 1909 (64-bit)
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/

### Reproduction steps

Downloaded video (tested only with .mkv format).
Apparently, any YouTube video. 

Open the downloaded video and use the shortcut **Ctrl+H** to enable hwdec (d3d11va in my case), works fine. Now, with YouTube, drag a random video link or a higher resolution one, try the same thing, **Ctrl+H**, shows enabled but don't seems to work, CPU still under some considerable use. 
Tried to test my GPU limit, playing a 8K 60fps YouTube video, seems to work only with Microsoft Edge, in Firefox and MPV the video just plays frame by frame. MPV in particular uses my CPU.

### Expected behavior

Low CPU usage and GPU video encode load. 

### Actual behavior

CPU still under notable use, instead of the GPU.

### Log file

[log.txt](https://github.com/mpv-player/mpv/files/4602636/log.txt)

### Sample files

My mpv.conf: [mpv conf.txt](https://github.com/mpv-player/mpv/files/4602639/mpv.conf.txt)

**Downloaded video:**
![MovieHWDEC](https://user-images.githubusercontent.com/36323363/81463804-d6031380-9192-11ea-8c1b-cd8b8ecc7061.png)

**YouTube video**
![YoutubeHWDEC](https://user-images.githubusercontent.com/36323363/81463809-ddc2b800-9192-11ea-913c-b3c3d405b342.png)

**Comment by Akemi** [comment]
the log is useless like that. you need to make a log while playing both samples, or at least the sample that doesn't work.

**Comment by Maikurosofuto** [comment]
> 
> 
> the log is useless like that. you need to make a log while playing both samples, or at least the sample that doesn't work.

Can you tell me how? Sorry, i'm not totally familiar with the player yet. I made that log via CMD, what's the next step?

**Comment by CounterPillow** [comment]
Add the `--log-file` option to your actual command to play the video, i.e. `mpv --log-file=mpv_sucks.log video-url-here`

**Comment by Maikurosofuto** [comment]
> 
> 
> Add the `--log-file` option to your actual command to play the video, i.e. `mpv --log-file=mpv_sucks.log video-url-here`
Done:
[mpv_rocks.log](https://github.com/mpv-player/mpv/files/4603216/mpv_rocks.log)

**Comment by Maikurosofuto** [comment]
> 
> 
> Add the `--log-file` option to your actual command to play the video, i.e. `mpv --log-file=mpv_sucks.log video-url-here`

Done:
[mpv_rocks.log](https://github.com/mpv-player/mpv/files/4603217/mpv_rocks.log)

**Comment by Maikurosofuto** [comment]
> 
> 
> Add the `--log-file` option to your actual command to play the video, i.e. `mpv --log-file=mpv_sucks.log video-url-here`

Here: 
[mpv_rocks.log](https://github.com/mpv-player/mpv/files/4603224/mpv_rocks.log)

**Comment by CounterPillow** [comment]
You don't actually have hwdec enabled because you put your hwdec option into a profile that you don't actually use. Just remove the `[vo]` line.

**Comment by Akemi** [comment]
from that log yes, but he said he activated hdwec via a shortcut at runtime (which most likely didn't happen in that last log).

for the log you should also activate hwdec otherwise we can't see what the issue is.

also is VP9 supported with windows hwdecs?

**Comment by Maikurosofuto** [comment]
> 
> 
> from that log yes, but he said he activated hdwec via a shortcut at runtime (which most likely didn't happen in that last log).
> 
> for the log you should also activate hwdec otherwise we can't see what the issue is.
> 
> also is VP9 supported with windows hwdecs?

As far as i know it does support VP9.
About the log, this might be the right one:
[txt.log](https://github.com/mpv-player/mpv/files/4603342/txt.log)

**Comment by Akemi** [comment]
it's most likely an ffmpeg issue. you need to report that to them.

also make sure to test it with ffmpeg first `ffmpeg -hwaccel d3d11va -loglevel verbose -i /PATH/TO/FILE.mp4 -f null`, if possible. ffmpeg wants that output too.

though since i am not on window i am not sure ig the hwaccel in ffmpeg is called `d3d11va`. might be something else.

```
[   6.902][v][decode_wrapper/vd] Looking at hwdec vp9-d3d11va...
[   6.902][v][decode_wrapper/vd] Trying hardware decoding via vp9-d3d11va.
[   6.902][v][cplayer] Set property: hwdec=auto -> 1
[   6.902][e][ffmpeg/video] vp9: Not all references are available
[   6.902][w][decode_wrapper/vd] Error while decoding frame (hardware decoding)!
[   6.902][e][ffmpeg/video] vp9: Not all references are available
[   6.903][w][decode_wrapper/vd] Error while decoding frame (hardware decoding)!
[   6.903][e][ffmpeg/video] vp9: Not all references are available
[   6.903][w][decode_wrapper/vd] Error while decoding frame (hardware decoding)!
[   6.903][w][decode_wrapper/vd] Falling back to software decoding.
```

**Comment by Maikurosofuto** [comment]
> ffmpeg -hwaccel d3d11va -loglevel verbose -i /PATH/TO/FILE.mp4 -f null

I'll report to them. Just to share, i got this error from CMD:
**C:\Program Files (x86)\MPV Player>mpv ffmpeg -hwaccel d3d11va -loglevel verbose -i C:\Users\Vinicius - PC\Downloads\Filmes\Godzilla II - Rei dos Monstros (2160p - HDR - BluRay).mkv -f null
Error parsing option hwaccel (option not found)
Setting commandline option --hwaccel= failed.
Exiting... (Fatal error)**

**Comment by Maikurosofuto** [comment]
> 
> 
> it's most likely an ffmpeg issue. you need to report that to them.
> 
> also make sure to test it with ffmpeg first `ffmpeg -hwaccel d3d11va -loglevel verbose -i /PATH/TO/FILE.mp4 -f null`, if possible. ffmpeg wants that output too.
> 
> though since i am not on window i am not sure ig the hwaccel in ffmpeg is called `d3d11va`. might be something else.
> 
> ```
> [   6.902][v][decode_wrapper/vd] Looking at hwdec vp9-d3d11va...
> [   6.902][v][decode_wrapper/vd] Trying hardware decoding via vp9-d3d11va.
> [   6.902][v][cplayer] Set property: hwdec=auto -> 1
> [   6.902][e][ffmpeg/video] vp9: Not all references are available
> [   6.902][w][decode_wrapper/vd] Error while decoding frame (hardware decoding)!
> [   6.902][e][ffmpeg/video] vp9: Not all references are available
> [   6.903][w][decode_wrapper/vd] Error while decoding frame (hardware decoding)!
> [   6.903][e][ffmpeg/video] vp9: Not all references are available
> [   6.903][w][decode_wrapper/vd] Error while decoding frame (hardware decoding)!
> [   6.903][w][decode_wrapper/vd] Falling back to software decoding.
> ```

I'll report to them. Just to share, i got this error from CMD:

**Error parsing option hwaccel (option not found)
Setting commandline option --hwaccel= failed.
Exiting... (Fatal error)**

**Comment by Akemi** [comment]
the notification mail was more complete:

> I'll report to them. Just to share, i got this error from CMD:
> C:\Program Files (x86)\MPV Player>mpv ffmpeg -hwaccel d3d11va -loglevel verbose -i C:\Users\Vinicius - PC\Downloads\Filmes\Godzilla II - Rei dos Monstros (2160p - HDR - BluRay).mkv -f null
> Error parsing option hwaccel (option not found)
> Setting commandline option --hwaccel= failed.
> Exiting... (Fatal error)

ffmpeg is separate command and not and is not called via mpv, not `mpv ffmpeg -hwaccel ...` but just `ffmpeg -hwaccel ...`. also you won't be lucky in the mpv install folder if ffmpeg is not installed or part of the that installation.
