### ISSUE TITLE
libmpv: show stats overlay, is it possible?

### ISSUE THREAD

**Issue by hjohn** [mpv-player/mpv#7706]
Is it possible while using libmpv to show the stats overlay (key: i) using a property for example?

Been searching for an hour through the docs, and I don't see how it could be done, so I suspect it might not be possible.  Is this PR related perhaps?  https://github.com/mpv-player/mpv/pull/6518

**Comment by wm4** [comment]
A command like ``script-binding display-stats`` should do it. That's actually in the stats secxtion of the manual. The PR you linked was never merged.

**Comment by hjohn** [comment]
Many thanks, I got it to work.  Was looking for a property instead of a command :)
