### ISSUE TITLE
Video playback stutter with x264 and x265

### ISSUE THREAD

**Issue by vikdean** [mpv-player/mpv#7707]
Hi,
I would like ask for assistance with a stuttering problem with some files in mpv. It happens occasionally, but I can't find the reason why... If I have 20 almost identical files 1 out of 10 will stutter for some reason. Happens mostly with x265, but not exclusively.

### My hardware:
Intel i9-9900K
GTX 1080Ti
16GB RAM
1440p (2560x1140) 144Hz Monitor

### My mpv config:
[mpv-config.txt](https://github.com/mpv-player/mpv/files/4603960/mpv-config.txt)

### Important Information
- mpv version: 0.32.0-410-g640db1ed3f
- Windows Version: Windows 10 Pro - 1909
- Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/
- GeForce driver: 445.87

### Reproduction steps
I've tried at least 20+ different configs, but to no avail.

### Expected behavior
To not stutter... I have the hardware to have a smooth playback, I think.

### Actual behavior
Random stuttering with dropped frames, around 500 in 10 minutes.

### Log file
[output.txt](https://github.com/mpv-player/mpv/files/4603956/output.txt)

### Media info
[media-info.txt](https://github.com/mpv-player/mpv/files/4603967/media-info.txt)

**Comment by Doofussy2** [comment]
Is it dropping frames?

**Comment by vikdean** [comment]
> Is it dropping frames?

Yes, around 500 in 10 minutes.

**Comment by ztarbugz** [comment]
Are you getting frame drops if you run mpv —no-config? This will skip your config and runs mpv default options. Maybe you can even try -v option for verbose output. If something is not working properly, it will be visible on cli during verbose

**Comment by vikdean** [comment]
> Are you getting frame drops if you run mpv —no-config? This will skip your config and runs mpv default options. Maybe you can even try -v option for verbose output. If something is not working properly, it will be visible on cli during verbose

`-v` gives no output at all.
`--no-config` does not work, nothing happens
`-no-config` does play the file, but doesn't ignore the config

**Comment by Doofussy2** [comment]
Well, you've got two different shaders and two scaling configs, all compounded. I use the `FSRCNNX_x2_8-0-4-1.glsl` shader, too. Why use the other shader? If you want to use the shaders, don't use the extra scale options, and just use the `profile=gpu-hq`.

I have an RTX 2060, and this is how I have mine configured:
```
vo=gpu
gpu-api=auto
hwdec=d3d11va-copy
hwdec-codecs=all
opengl-pbo=yes
scale=spline64
cscale=spline64
sigmoid-upscaling=yes
glsl-shader="G:\mpv\FSRCNNX_x2_8-0-4-1.glsl"
dither-depth=auto
deband=yes
deband-iterations=1
deband-grain=0
```

**Comment by vikdean** [comment]
> Well, you've got two different shaders and two scaling configs, all compounded. I use the `FSRCNNX_x2_8-0-4-1.glsl` shader, too. Why use the other shader? If you want to use the shaders, don't use the extra scale options, and just use the `profile=gpu-hq`.
> 
> I have an RTX 2060, and this is how I have mine configured:
> 
> ```
> vo=gpu
> gpu-api=auto
> hwdec=d3d11va-copy
> hwdec-codecs=all
> opengl-pbo=yes
> scale=spline64
> cscale=spline64
> sigmoid-upscaling=yes
> glsl-shader="G:\mpv\FSRCNNX_x2_8-0-4-1.glsl"
> dither-depth=auto
> deband=yes
> deband-iterations=1
> deband-grain=0
> ```
Among others (I've spend days looking at guides) I've used this one: https://kokomins.wordpress.com/2019/10/14/mpv-config-guide/
I've removed the FSRCNNX lines; I'll test it again.

**Comment by Doofussy2** [comment]
For using these shaders, this is a good resource, if you haven't seen it yet.

https://artoriuz.github.io/mpv_upscaling.html

**Comment by vikdean** [comment]
> For using these shaders, this is a good resource, if you haven't seen it yet.
> 
> https://artoriuz.github.io/mpv_upscaling.html
I came across this one too, but its too overwhelming for me and I don't understand it at all...

**Comment by lextra2** [comment]
testing with an empty config should always be the first thing you do once you run into any problems. just common sense imo.

**Comment by vikdean** [comment]
> testing with an empty config should always be the first thing you do once you run into any problems. just common sense imo.
> 
> also, x264 and x265 are the open source encoders, not the codecs. (avc/h264 & hevc/h265)

An empty config is OK for figuring out if the cause is because of the config, but beyond that, it doesn't help, since I have no idea what in my config is causing the issue...

**Comment by ztarbugz** [comment]
So is it dropping frames without config or empty one? What is if you disable the glsl shader SSimSuperRes.glsl? E.g. I have a AMD RX560X on my 27" iMac, which is mostly like a 1060, but running FSRCNNX_x2_8-0-4-1.glsl on a 1080p 60 frames video is dropping frames a lot, what is the reason why I did adjustments based on frame rate and resolution. Another fun fact is that on a x264 video (1080p, 8bit) which is encoded with level High@5 does not enable hw decoding on Apple devices (ffmpeg issue, found by running -v option).

My advice, as lextra2 said: try an empty config or from cli mpv --no-config -v to play video with mpv´s defaults. When this is running smooth, load your config and first disable all shaders. If it is still not running smooth, try to reduce scaler to spline36 or lower. Changing gpu-api from OpenGL to direct3d could help as well. Only a few ideas. And for the shader load at the end of your file, you have the auto-profiles.lua script in script folder?

**Comment by vikdean** [comment]
I've pretty much removed everything. This is whats left:
```
vo=gpu
profile=gpu-hq
gpu-api=auto
dither-depth=auto
hwdec-codecs=all
hwdec=auto
```
The stuttering in places still remains... could this have something to do with my 144Hz Monitor?

**Comment by Doofussy2** [comment]
Have you actually tested with no mpv.conf?

**Comment by adisib** [comment]
Have you tried `video-sync=display-resample`? I had really noticeable stuttering whether freesync was on or not until I added that recently, now with that added it is smooth. I'm also on a 144 Hz monitor on Windows (but I'm on an AMD card).

**Comment by vikdean** [comment]
> Have you tried `video-sync=display-resample`? I had really noticeable stuttering whether freesync was on or not until I added that recently, now with that added it is smooth. I'm also on a 144 Hz monitor on Windows (but I'm on an AMD card).

I did. I had some horrific tearing when that was on... Not much stuttering though, thats true, but the cure was worse then the disease...

This was the config:
```
video-sync=display-resample
interpolation=yes
tscale=box
tscale-window=quadric
tscale-clamp=0.0
tscale-radius=1.025
```

**Comment by vikdean** [comment]
> Have you actually tested with no mpv.conf?

I've tested with the video settings above. Removing everything makes mpv useless for me (no proper subtitle options, no audio normalization, etc), so I've kept what was essential.

**Comment by Doofussy2** [comment]
Try adding `opengl-pbo=yes` to speed things up

**Comment by vikdean** [comment]
> Try adding `opengl-pbo=yes` to speed things up

I've tried a different file now, x264:
``
General
Unique ID                   : ......
Complete name               : ......
Format                      : Matroska
Format version              : Version 4
File size                   : 18.2 GiB
Duration                    : 3 h 1 min
Overall bit rate mode       : Variable
Overall bit rate            : 14.4 Mb/s
Movie name                  : .....
Encoded date                : UTC 2019-07-31 23:34:19
Writing application         : mkvmerge v34.0.0 ('Sight and Seen') 64-bit
Writing library             : libebml v1.3.7 + libmatroska v1.5.0
Cover                       : Yes
Attachments                 : small_cover.jpg / small_cover_land.jpg / cover.jpg / cover_land.jpg / small_cover.jpg / small_cover_land.jpg / cover.jpg / cover_land.jpg

Video
ID                          : 1
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.1
Format settings             : CABAC / 5 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 5 frames
Codec ID                    : V_MPEG4/ISO/AVC
Duration                    : 3 h 1 min
Bit rate                    : 8 857 kb/s
Width                       : 1 920 pixels
Height                      : 808 pixels
Display aspect ratio        : 2.40:1
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.238
Stream size                 : 11.2 GiB (62%)
Writing library             : x264 core 158 r2984 3759fcb
Encoding settings           : cabac=1 / ref=5 / deblock=1:-3:-3 / analyse=0x3:0x133 / me=umh / subme=8 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=25 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=50 / rc=2pass / mbtree=1 / bitrate=8857 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=62500 / vbv_bufsize=78125 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Language                    : English
Default                     : Yes
Forced                      : No
```

Terribly stuttering, with huuuuge number of Dropped frames.
Its a lot better with `opengl-pbo=yes`, but there are still noticeable drops sometimes.

My mpv config:
```
profile=gpu-hq
gpu-api=auto
icc-profile-auto
scaler-resizes-only
sws-scaler=lanczos
scale=ewa_lanczossharp
cscale=ewa_lanczossoft
dscale=mitchell
dither-depth=auto
correct-downscaling=yes
sigmoid-upscaling=yes
deband=yes
hwdec=auto
opengl-pbo=yes
```

**Comment by traktori** [comment]
Try gpu-api=d3d11. It fixed my stuttering back in the day.

**Comment by Doofussy2** [comment]
On its face, it looks like there's some kind of latency. Maybe you're using something that requires software rendering?

**Comment by vikdean** [comment]
> On its face, it looks like there's some kind of latency. Maybe you're using something that requires software rendering, that's slowing things down?

Nah, I dont have anything else open... but even if I did, my i9-9900K should be able to handle it with ease. 
With this I don't have drops anymore, but there are still stutters:
```
gpu-api=d3d11
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
dscale=mitchell
dither-depth=auto
```
What's the recommendation btw, use hardware decoding or not?

**Comment by Hrxn** [comment]
I have a hunch that there is something weird going on with your system.
The hardware should definitely not be the issue here.
I don't know, something weird running in the background?

Also not sure about what kind of stutters you see... something like motion judder? Especially with motion in the scene or something?

**Comment by vikdean** [comment]
> I have a hunch that there is something weird going on with your system.
> The hardware should definitely not be the issue here.
> I don't know, something weird running in the background?
> 
> Also not sure about what kind of stutters you see... something like motion judder? Especially with motion in the scene or something?
> 
> > What's the recommendation btw, use hardware decoding or not?
> 
> Depends. Hardware decoding does not improve quality or something, so if it works fine without it..

I've triple checked my system already, there is nothing which could interfere... also, MPC-HC with maxed out madVR works fine...

Yes, its usually related to motion, panning scenes, where you can see a small micro-stutter, but it happens enough times to start bothering you. I've tried the interpolation config, which eliminates all stutter, but the audio is slipping because of it and it introduces some tearing when anything is moving.

I'm at a loss here... tried pretty much everything and spent days on this, but I'm still no closer to a solution.
I've been using mpv for a few years now; nothing like this every happened before and I haven't changed anything at all, apart from the regular mpv updates (which there were 2 already, since I've opened this thread).

**Comment by wm4** [comment]
Without more information we're in the dark too. E.g. what are the vsync jitter readings? Does playing with specific swapchain etc. parameters help.

I actually suspect it might have to do with power management. I got severe jitter with nvidia GPUs in adaptive power mode.

**Comment by ofitness** [comment]
從我的iPhone傳送

**Comment by vikdean** [comment]
> Without more information we're in the dark too. E.g. what are the vsync jitter readings? Does playing with specific swapchain etc. parameters help.
> 
> I actually suspect it might have to do with power management. I got severe jitter with nvidia GPUs in adaptive power mode.

Vsync jitter? Where is that? I dont see it in the statistics with Shift+i. Swapchain? Whats that?
My power management is set to "Optimal power".
I can provide output from anything if you let me know where to look.

**Comment by traktori** [comment]
Have you tried downgrading to the previous build and see if that fixes it? I had some issues with the latest sourceforge build.

**Comment by vikdean** [comment]
> Have you tried downgrading to the previous build and see if that fixes it? I had some issues with the latest sourceforge build.

Not yet, because it seemed okay with no mpv-config. But I guess, thats next.

**Comment by roberth1990** [comment]
Whats happens if you set the monitor to run in 60 hz?

**Comment by vikdean** [comment]
> Whats happens if you set the monitor to run in 60 hz?

Nothing, because I haven't bought a 144Hz monitor to use it at 60Hz...
Since the rollback it seems better, but I have to do more testing.

**Comment by Hrxn** [comment]
> Nothing, because I haven't bought a 144Hz monitor to use it at 60Hz...

Not permanently of course, just for testing purposes..

**Comment by CreamyCookie** [comment]
@vikdean 

I just had a lot of frame drops too, and it instantly disappeared once I removed the `loudnorm` audio filter.

The `dynaudnorm` one doesn't have that problem. I'm pretty sure that this wasn't a problem before.

**Comment by CreamyCookie** [comment]
@vikdean I seem to have had the same problem just now, and found out what it was causing for me.

I was playing a 1080p file, and had a ton of frame drops. Then I removed the  `loudnorm` audio filter, and the problem instantly disappeared.



**For the devs:** My graphics card is pretty recent and drivers up to date. I'm pretty sure that this wasn't a problem before. The `dynaudnorm` filter doesn't cause the issue.

**Comment by rijnhard** [comment]
Same problem, on my side it could be a lot of things (I'm running an AMD kaveri A10-7800 with amdgpu drivers and vulkan enabled which is pretty much as flakey as a bad dandruff condition) .

But this especially prevelant with Stremio. I do have pulseeffects running in the background with a few filters that I've used to construct my own normaliser.

My other half isn't complaining about it on mpv directly though.

So it could likely be a predefined setting in stremio which doesn't support setting mpv flags directly currently.

**Comment by CounterPillow** [comment]
@rijnhard please open your own issue instead of polluting this random completely different user's performance problem issue with your situation, we need a log file and version information as outlined in the issue template to provide any assistance.
