### ISSUE TITLE
libmpv loading script at runtime

### ISSUE THREAD

**Issue by hatharry** [mpv-player/mpv#7709]
### Important Information

Provide following Information:
- mpv version - 0.32
- Windows Version - 10
- Source of the mpv binary - windows build
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

set "script" property to "path to script"

add "mp.msg.verbose("script loaded")" to script

### Expected behavior

"script loaded" in log file

### Actual behavior

script is not loaded

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/4604944/mpv.log)

**Comment by avih** [comment]
https://mpv.io/manual/master/#command-interface-load-script
