### ISSUE TITLE
manipulate mpv window with devilspie2, wmctrl, or xdotool

### ISSUE THREAD

**Issue by spfeifer222** [mpv-player/mpv#7711]
I try to arrange two mpv windows in the left quarters of the screen, but fail with `devilspie2`, `xdotool`, and `wmctrl`. I've read about the issue https://github.com/mpv-player/mpv/issues/4739, but the exactly code 

`wmctrl -r mpv -e 1,500,500,-1,-1` 

(`500` substituted with my own values) does not work.

Now, I guess the reason to fail could be a property of mpv itself. Could you give any hint to solve the task? 

### Log file

no log

**Comment by biopsin** [comment]
Hi, I'm lately bitten by some odd positioning of mpv with wmctrl too, I swear I had this working fine 4-5 months ago, but after a reinstall of OS and even with same configs and wmctrl version, 
I seem to be unable to move mpv window to spesific coordinates.

// mpv.conf -> border=no, geometry=199x111-10+10,  force-window=no

$ wmctrl -SlG   (my monitor @ 3840x2160)
`0x01a00002  0 3631 10   199  111    ... - mpv`     (3840 - 199 -10 = 3631)

then if I move mpv some other place and run to reset
$ wmctrl - ia 0x01a00002 -e 0,3631,10,199,111
window moves to @ 0x... 0 1816 5    199  111 , then
after 10 runs it settles @ 0x... 0 2420 7    199  111 , consistently.
(a offset of 1420px horizontal and 3px vertical)

also settled position is different whereever I initialize mpv from the left/right/center/bottom/top of monitor.
There is no issue with scaling mpv window from one size to another, however it will settle on again a different position and never reach initial position.

Moving mpv with PekWM keybinds works fine, so i find this somehow weirdo today..

**Comment by Akemi** [comment]
please open a new issue with all the info we ask for if the problem still persists.
