### ISSUE TITLE
Very complex ASS subtiles doesn't get rendered correctly anymore

### ISSUE THREAD

**Issue by anounyym1** [mpv-player/mpv#7712]
### Important Information

Provide following Information:
- mpv version
mpv 0.32.0-456-g4e94b2177a
- Windows Version
Windows 10 LTSC
- Source of the mpv binary
https://sourceforge.net/projects/mpv-player-windows/
- If known which version of mpv introduced the problem
With mpv 0.29.1 (lachs0r) build there was no issues.
- Possible screenshot or video of visual glitches

### Reproduction steps
Play file with very complex ASS subtitles,  --no-config doesn't have effect.

### Expected behavior
![correct render](https://user-images.githubusercontent.com/1563598/81513865-48f7c000-9334-11ea-9c55-14a962f48b59.png)

### Actual behavior
![broken render](https://user-images.githubusercontent.com/1563598/81513917-9b38e100-9334-11ea-8dab-0f6e19eada43.png)

### Log file
[mpv 0.32.0.txt - Broken build](https://github.com/mpv-player/mpv/files/4606979/mpv.0.32.0.txt)

[mpv 0.29.1.txt - Working build](https://github.com/mpv-player/mpv/files/4606976/mpv.0.29.1.txt)

### Sample files

https://0x0.st/i_y5.mkv

**Comment by TheAMM** [comment]
As a hint for anyone taking a look at this, IIRC the images used alignment stacking to save on characters and decrease gaps. As in, (iirc) only the first pixel of the row has a `\pos` and the rest then stack against it, or something like that.

Here's a line (with some newlines to help to look at it) https://0x0.st/i_vz.txt - rows of pixels separated by `\N`, so looks like the linebreak is too fat in 0.32 for whatever reason.

**Comment by tleydxdy** [comment]
fwiw, works fine on GNU/Linux. Nice vid btw :)

```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.2
```

**Comment by Akemi** [comment]
this should reported to libass.

**Comment by Akemi** [comment]
the offending commit is https://github.com/libass/libass/commit/e8d98dafb8d4d1fd80e9d398cfbef7db1e2ccb73
![i_y5_(00-00-12 721)_01](https://user-images.githubusercontent.com/680386/81564105-87729680-9397-11ea-9575-de6d175a0519.jpeg)
with the commit before https://github.com/libass/libass/commit/67e55f13ccbca005540d34406fdc694b1748506d
![i_y5_(00-00-12 721)_02](https://user-images.githubusercontent.com/680386/81564120-8a6d8700-9397-11ea-918a-fbcdd199b0bd.jpeg)

**Comment by TheOneric** [comment]
The issue should have been fixed by astiob's patch, so this issue can probably be closed.

**Comment by anounyym1** [comment]
Yes, seems to work now.
Thank you!
