### ISSUE TITLE
Failed to call Inhibit

### ISSUE THREAD

**Issue by mathsen** [mpv-player/mpv#7713]
### Important Information

Provide following Information:
- mpv version: 0.32.0

- Linux Distribution and Version: Arch Linux

- Source of the mpv binary: official Arch binary from community repo

- Window Manager and version: awesome window manager 4.3

- GPU driver and version: intel integrated graphics driver from mesa

### Reproduction steps
If I execute:
`mpv --no-config video.mp4`
or
`mpv --version`
in a terminal I get:

> ** (gnome-session-inhibit:7254): WARNING **: 14:16:10.849: Failed to call Inhibit: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

If I open the same file in ranger, nautilus or via xdg-open (which calls mpv) the video is opened and played - as expected.
If I use Gnome 3 instead of awesome window manager everything works as expected.
I start awesome window manager via GDM.

**Comment by Dudemanguy** [comment]
mpv doesn't use dbus or any gnome stuff. I have no idea why you're getting that message in your terminal, but it's not an mpv issue.

**Comment by wm4** [comment]
Must be xdg-screensaver, if you use the mpv x11 backend.

**Comment by mathsen** [comment]
You were right, I solved the problem, I had set

`alias` mpv='gnome-session-inhibit mpv'

some time ago as a workaround for the blanking screen on wayland... Had completely forgotten this and without it everything works fine. Thanks for the help here.
