### ISSUE TITLE
mpv doesn't play well with partial files

### ISSUE THREAD

**Issue by NightMachinary** [mpv-player/mpv#7716]
### Important Information

Provide following Information:
- mpv version 
```
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue Apr  7 14:51:43 BST 2020
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: 4.2.2
```
- macOS Version: 10.15
- Source of the mpv binary or bundle: Homebrew

### Reproduction steps

The attached file is a partial download by `youtube-dl`. Seeking in this file to a not downloaded location causes a lot of error messages and slows mpv so much it is almost hanged. Also, when using cache settings
```
cache=yes
cache-secs=99999999
```
mpv mistakenly marks parts of the file as downloaded that are not (this test file only has 6MB out of 128MB, but look at this screenshot):
![image](https://user-images.githubusercontent.com/36224762/81726130-1bc62180-949c-11ea-85e5-b9645cc94474.png)

The parts of the file that are not downloaded are just zero bytes. mpv should handle such zero bytes smartly, i.e. it should notice that they are not-downloaded parts. 

Error messages of mpv when seeking:

```
...
[ffmpeg/video] h264: Invalid NAL unit size (0 > 263).
[ffmpeg/video] h264: Error splitting the input into NAL units.
Error while decoding frame!
[ffmpeg/video] h264: Invalid NAL unit size (0 > 241).
[ffmpeg/video] h264: Error splitting the input into NAL units.
Error while decoding frame!
[ffmpeg/video] h264: Invalid NAL unit size (0 > 700).
[ffmpeg/video] h264: Error splitting the input into NAL units.
Error while decoding frame!
[ffmpeg/video] h264: Invalid NAL unit size (0 > 858).
[ffmpeg/video] h264: Error splitting the input into NAL units.
Error while decoding frame!
[ffmpeg/video] h264: Invalid NAL unit size (0 > 1165).
[ffmpeg/video] h264: Error splitting the input into NAL units.
Error while decoding frame!
[ffmpeg/video] h264: Invalid NAL unit size (0 > 234).
[ffmpeg/video] h264: Error splitting the input into NAL units.
Error while decoding frame!
[ffmpeg/video] h264: Invalid NAL unit size (0 > 1095).
[ffmpeg/video] h264: Error splitting the input into NAL units.
Error while decoding frame!
[ffmpeg/video] h264: Invalid NAL unit size (0 > 148).
[ffmpeg/video] h264: Error splitting the input into NAL units.
Error while decoding frame!
[ffmpeg/video] h264: Invalid NAL unit size (0 > 756).
[ffmpeg/video] h264: Error splitting the input into NAL units.
Error while decoding frame!
...
```
[test.zip](https://github.com/mpv-player/mpv/files/4617438/test.zip)

**Comment by wm4** [comment]
This is just a broken file. Packets somewhere at the end are broken. There's also 6 MB of 0s at the end (not sure if that causes all the errors). Should be better in git master, because it doesn't block the entire player until all broken cached packets are decoded.
Generally, playing files that are being appended to is crazy and it should come to no surprise that this is happening. Disable all caching if you must play such files, or use ``appending://`` and make sure you're using a writer and an OS where appending atomically leads to valid data on readers, or pipe the output of whatever program directly to stdin.

**Comment by NightMachinary** [comment]
@wm4  Can we add an option to youtube-dl that outputs both to a file and to stdout at the same time? This way users get to keep the file for future use, and streaming works great. I know of `tee`, but that has the disadvantage of needing another youtube-dl call to get the name of the video.

**Comment by NightMachinary** [comment]
@wm4 I have written the following script to  stream to stdin, but mpv does not seek when reading from stdin. If seeking should not work, then using stdin is much much worse than `appending://`.

```
y-stream-pipe () {
    local url="$1"
    local out=("${(@f)$(ybase --get-url --no-part -f best --get-filename -o "%(title)s.%(ext)s" "$url")}")
    test -n "$out[1]" || {
        ecerr Could not get video\'s url. Aborting.
        return 1
    }
    test -n "$out[2]" || {
        ecerr Could not get video\'s name. Aborting.
        return 1
    }
    local name="$out[2]"
    \noglob youtube-dl --no-playlist --write-sub --sub-lang en --prefer-ffmpeg -f best "$url" -o - | tee "$name" | mpv -
}
```

**Comment by NightMachinary** [comment]
@wm4 I have tried this, too:
```
mpv-cache () {
    mpv --force-seekable=yes --cache=yes --cache-secs=99999999 "$@"
}
```
And it works until I seek to a location that has not been cached yet; Then mpv will no longer receives input from stdin and everything breaks. I think mpv should simply not seek when it knows cache is not available (or even when it guesses cache might not be available.)
