### ISSUE TITLE
af=lavcac3enc=no doesn't work

### ISSUE THREAD

**Issue by nemethdani** [mpv-player/mpv#7718]
### Important Information
- mpv version: 2:0.32.0+git4~bionic1
- Platform and Version x86_64
- Source of the mpv binary: http://ppa.launchpad.net/mc3man/mpv-tests/ubuntu bionic/main amd64

### Reproduction steps

Unconnect HDMI cable (though it doesnt seem to count whether it is plugged in or not)
Activate your built in speaker device in your os.
mpv --log-file=output.txt --no-config --af=lavcac3enc="no:384:2" 11sec.dts

### Expected behavior
Notebook speakers play the audio (which was encoded to ac3)

### Actual behavior
It doesn't play any audio. It seems to be trying to still send it to spdif
(Setting spdif=no and using an hdmi cable still doesnt produce output sound)

### Log file
https://0x0.st/iLHQ.txt

### Sample files
https://0x0.st/iLH2.dts

I am trying to use lavcac3enc  for dts audio, because it seems to handle downmixing better. With hdmi and spdif=yes it works fine, but I would like to use it when I am using the speakers of my notebook

**Comment by wm4** [comment]
This is for audio pass-through, a hack for shitty consumer products and to help the illegal Dolby(tm) patent racketeering scheme. The company which made your notebook speakers was probably too poor to pay the extortion money to Dolby(tm).
