### ISSUE TITLE
--profile=gpu-hq --video-sync=display-* flickers on Intel Skylake with Vulkan

### ISSUE THREAD

**Issue by jbeich** [mpv-player/mpv#7719]
### Important Information

- Regressed by c145c8008580629bd12a009678be16759f125e04
- mpv v0.32.0-460-g3451908a34 / ffmpeg n4.2.2 / libplacebo v2.43.0-70-g095fff1 / shaderc v2018.0 / vulkan sdk-1.1.108.0
- FreeBSD 13.0-CURRENT (r361000) amd64
- i915kms from drm-v5.1 / anv from mesa 20.2.0 (1bd38746d5a) / xf86-video-intel 2.99.917-906-g846b53da
- sway 1.5 (a8a6ed667d0f) / dwm 6.2 + picom v8 + xorg-server 1.20.8

### Reproduction steps

```
$ mpv --no-config --profile=gpu-hq --gpu-api=vulkan --video-sync=display-resample http://www.jell.yfish.us/media/jellyfish-3-mbps-hd-h264.mkv
```

### Expected behavior

No flickering and no libplacebo errors.

### Actual behavior
Severe flickering (screen remains black) accompanied by lots of
```
[vo/gpu/vulkan/libplacebo] Validation failed: src_fmt->internal_size == dst_fmt->internal_size (../src/gpu.c:545)
```
unless `--fbo-format=rgba8` is added or `--profile=gpu-hq` is dropped. Dropping `--video-sync` only reduces severity but flickering still occurs at playback start.

### Log file

- [wayland](https://github.com/mpv-player/mpv/files/4623049/mpv.wayland.txt)
- [x11](https://github.com/mpv-player/mpv/files/4623055/mpv.x11.txt)

**Comment by jbeich** [comment]
EDIT: added  `--fbo-format=rgba8` as a better workaround. According to `vulkaninfo` only B8G8R8A8 surface formats are supported on my GPU.

**Comment by haasn** [comment]
Hope this works for you. I can't really test.

**Comment by jbeich** [comment]
I confirm, mpv v0.32.0-464-g6d8b3f9333 has no flickering and no errors anymore.

**Comment by lavilao** [comment]
Hi, I have kind of the same problem, with this mpv -no-config -vo=gpu -hwdec=auto --spirv-compiler=auto --gpu-api=vulkan --vulkan-async-compute=yes --vulkan-async-transfer=yes -wayland-disable-vsync -gpu-context=waylandvk works flawlessly but as soon I add -profile=gpu-hq or -glsl-shader="~~/shaders/ravu-lite-r3.hook" starts to flicker, on opengl though it does not, I am new so if anyone could tell me how to upload the log it would be appreciated. Oh btw in case someone ask I already tried with -fbo-format=rgba8 alongside gpu-hq and ravu, it did not worked, am currently on manjaro gnome, wayland session, on a intel celeron n3050 with mesa 20.3.3 and vulkan-intel 20.3.3.
