### ISSUE TITLE
videos assigned with BT.1886 TRC are too dark when target-trc is srgb

### ISSUE THREAD

**Issue by jpark37** [mpv-player/mpv#7720]
### Important Information

mpv version: 0.32.0-456-g4e94b2177a
Platform and Version: Windows 10 2004 19041.264
Source of the mpv binary: https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20200510-git-4e94b21.7z/download

### Reproduction steps

I have a test video, gray26.mkv, that encodes an sRGB value of 26 as a Rec. 709 H.264 video, transforming the gray value to roughly 10.55.

Color values were grabbed with Print Screen, and mspaint eyedropper.

### Expected behavior

Command line: mpv gray26.mkv
Color value is 11, maybe 10. mpv intentionally ignores TRC settings and aliases colors by default.

Command line: mpv --target-trc=srgb gray26.mkv
Color value should be 26 after unwinding 709 TRC and applying sRGB TRC.

### Actual behavior

Command line: mpv gray26.mkv
Color value is 12. VLC seems to give back 11, but 12 is close.

Command line: mpv --target-trc=srgb gray26.mkv
Color value is 2.
avcol_trc_to_mp_csp_trc assigns BT.1886 TRC for 709, which is very different from H.264 spec.

### Log file

notargettrc.txt: https://0x0.st/iLKb.txt
srgbtrc.txt: https://0x0.st/iLKc.txt

### Sample files

gray26.mkv: https://0x0.st/iLKA.mkv

**Comment by jpark37** [comment]
@haasn wm4 in IRC told me to ping you.

**Comment by haasn** [comment]
The tl;dr is EOTF != OETF. The video being encoded with a BT.709 OETF does not mean the inverse BT.709 is the correct EOTF to be use. (As per ITU-R, BT.1886 is the correct EOTF to pair with the BT.709 OETF)

The reason your values don't round-trip the way you expect them to is because the implicit OOTF defined by the interaction of these two functions effectively constitutes a gamma drop.

**Comment by haasn** [comment]
Side note, you should probably enable dithering when testing the exact color values like these, since the difference between 11 and 12 might be down to rounding errors. I'd consider it a bug if you still measure a deviation from the calculated result when looking at the averaged dithered values.

**Comment by jpark37** [comment]
Seems like I have a lot of reading to do. I may be back later though. :)
