### ISSUE TITLE
assertion failure in sub/draw_bmp.c

### ISSUE THREAD

**Issue by LaserEyess** [mpv-player/mpv#7721]
### Important Information

Provide following Information:
```
mpv --version
mpv 0.32.0-463-g0ff839d467 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Wed May 13 12:42:43 EDT 2020
FFmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
FFmpeg version: n4.2.2
```
Arch Linux 5.6.11 with amdgpu
mesa 20.0.6

### Reproduction steps
`mpv --no-config --vo=wlshm --osd-msg1='string' video.mkv`
Afterwards, change the aspect ratio of the window so that the OSD needs to rescale the font.

### Expected behavior
No Crash

### Actual behavior

mpv crashes with 
```
mpv: ../sub/draw_bmp.c:160: blend_overlay_with_video: Assertion `x + w <= p->w' failed.
```

### Log file
Log: https://0x0.st/iLPp.txt
gdb: https://0x0.st/iLqR.txt (new backtrace without the extra crap)

Git bisected to c1a961ad78b6d1da339e622c723d753a80687824

**Comment by wm4** [comment]
Can't reproduce.

**Comment by LaserEyess** [comment]
I'm not sure what exactly is causing the crash itself. Fullscreening does not cause it, nor does changing the font size dynamically with `osd-font-size`. It seems to be a combination of changing the aspect ratio of the window as well as changing the font size.

On Sway, I have my windows tiled like this https://0x0.st/iLZN.png. You can see mpv is in the lower right. When I move it so that it's in the firefox tile, it crashes instantly. I can reproduce this for any video.

**Comment by Dudemanguy** [comment]
I kinda suspect it has something to do with vo_wlshm itself that needs to be changed because of the bmp rewrite.

**Comment by wm4** [comment]
That shouldn't be happening.

**Comment by LaserEyess** [comment]
Rebuilt with the couple of commits added that affected `draw_bmp.c`, still get the same crash, but now on line 174.

**Comment by shabahengam** [comment]
I can reproduce the problem without `--osd-msg1='string'`
mpv: git-master a58b2df
WM: sway 1.4
after resizing the window
```
mpv: ../sub/draw_bmp.c:260: mark_rect: Assertion `x0 >= 0 && x0 <= x1 && x1 <= p->w' failed.
```
or
```
mpv: ../sub/draw_bmp.c:261: mark_rect: Assertion `y0 >= 0 && y0 <= y1 && y1 <= p->h' failed.
```
after going to fullscreen I get `zsh: segmentation fault`.
this is from gdb
```
Thread 10 "mpv/vo" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe6ffd700 (LWP 13920)]
draw_ass_rgba (color=<optimized out>, h=64, w=644, src_stride=1024, src=0x7fffc826b700 "", dst_stride=5504, dst=0x7fffc874de9c "") at ../sub/draw_bmp.c:303
303	            unsigned int aa = a * v;
```

**Comment by Dudemanguy** [comment]
Right, that fails because if you resize with the mouse, you also render the osc which triggers this crash. It works if you use `--no-osc` for instance.

**Comment by Dudemanguy** [comment]
It looks like `mp_image_crop_rc(&dst, dst_rc);` (line 241 in `vo_wlshm.c`) crops `dst` to a bad value which later triggers various assertion failures (i.e. omitting that line makes it work again) with the osd rendering functions. Maybe someone can enlighten me on this, but is that needed at all? The other sws scalers don't crop the dst size. I assume the other `dst_rc` stuff is just wayland buffer optimizations.

**Comment by wm4** [comment]
Not really sure. Check whether moving/zooming around the video works correctly. The code looks a bit suspicious, and I don't know what it's trying to do (but maybe it's justified). It's strange that it has these align calls. It's also strange that it sometimes passes widths/heights to mp_image_clear(), even though that function takes start/end coordinates like mp_rect uses.

**Comment by Dudemanguy** [comment]
Pan and zoom don't work without triggering some other event like resizing the window, but they didn't work before either. Anyways, I'll just tag @linkmauve and @michaelforney since they're probably the most interested in this.

**Comment by michaelforney** [comment]
I'll try to take a closer look at this soon, but regarding the alignment stuff, see my comment in the original pull request: https://github.com/mpv-player/mpv/pull/6240#discussion_r227930233

**Comment by wm4** [comment]
In addition, draw_bmp.c's internals should assert much earlier if the passed in image is too small or so, plus the old code also would have had a problem.
It could be something else, such as inconsistent change_id values.

**Comment by wm4** [comment]
Regarding the alignment, this is not useful anymore, since libswscale is no longer called on the video when rendering OSD.

**Comment by michaelforney** [comment]
I managed to reproduce this issue with vo_drm (one of the references I used for vo_wlshm). If the video aspect ratio does not match the monitor's, and I seek to display the OSD, I get the same assertion failure.

Still trying to wrap my head around the different rectangles involved here, since it's been a while since I wrote this code.

**Comment by michaelforney** [comment]
Okay, the bug seems to be that `dst->w` and `dst->h` do not match `dst->params.w` and `dst->params.h`. This is because when the dimensions of the scaled video differ from the window (for instance with `--no-keepaspect-window`), those members are changed directly, and the params dimensions are left unchanged:
https://github.com/mpv-player/mpv/blob/master/video/out/vo_wlshm.c#L114-L116

The same issue exists with vo_drm:
https://github.com/mpv-player/mpv/blob/master/video/out/vo_drm.c#L324-L326

Changing these to use `mp_image_set_size` does seem to resolve the issue:

```diff
diff --git a/video/out/vo_wlshm.c b/video/out/vo_wlshm.c
index 40c5b0da0f..3583ce3e73 100644
--- a/video/out/vo_wlshm.c
+++ b/video/out/vo_wlshm.c
@@ -112,8 +112,7 @@ static struct buffer *buffer_create(struct vo *vo, int width, int height)
     buf->vo = vo;
     buf->size = size;
     mp_image_set_params(&buf->mpi, &p->sws->dst);
-    buf->mpi.w = width;
-    buf->mpi.h = height;
+    mp_image_set_size(&buf->mpi, width, height);
     buf->mpi.planes[0] = data;
     buf->mpi.stride[0] = stride;
     buf->pool = wl_shm_create_pool(wl->shm, fd, size);
```

I'll create a pull request to fix this in vo_wlshm and vo_drm.

**Comment by wm4** [comment]
That would definitely explain it. The setter exists because there are some redundant fields, and anything setting them must use the setter.

Why does it set them, instead of setting p->sws-dst->w/h to the correct values?

**Comment by michaelforney** [comment]
I'm not completely sure, but my understanding is that `p->sws->dst` is the scaled dimensions of the video, which doesn't necessarily match the dimensions of the window's buffer (for instance, with `--no-keepaspect-window`).

**Comment by wm4** [comment]
Well, it's the output of the software scaler. Normally I'd expect that it scales to exactly what you can see on screen. For example, zooming into the video should *not* allocate a huge image that is then cropped. So dst is always the visible video; the intersection of "scaled" video and window.

**Comment by michaelforney** [comment]
What about the case where the video is zoomed out and black borders are needed? Is there a way to get the software scaler to add those automatically?

**Comment by wm4** [comment]
No, but a utility function could do this using mp_image_clear().

**Comment by wm4** [comment]
PS: in general, it might be a good idea to factor all "rendering video to a framebuffer" code into a common helper. The question is only whether this wouldn't make further development of certain VOs more awkward, such as extending vo_drm with HW overlays, or vo_wlshm with wayland sub-surface stuff.
