### ISSUE TITLE
Allow user to input custom filename while taking screenshot

### ISSUE THREAD

**Issue by jallbrit** [mpv-player/mpv#7722]
## Current Behavior

When `s` or `S` is hit, currently, `mpv` uses the screenshot template it has been given to automatically name the screenshot and place it in the correct folder. However, I often wish to give the screenshot I just took a custom name. Let's say the image is of a character named John Smith. Right now, I have to `mv mpv-shotXXXX.png john-smith-walking.png`.

## Feature Proposal

This may seem trivial, but when dealing with large amounts of screenshots in the `mpv-shotXXXX.png` format, it becomes more difficult and time-consuming to custom-name the screenshots. It would be *significantly* easier if done right on the spot, at screenshot creation.

### Option 1: Non-default Option that Changes Behavior of `s`/`S`

Ideally, there would be a non-default option that allows users to put in a custom name upon hitting `s`/`S`. When those keys are pressed, there would be a prompt saying `Enter screenshot filename: `, and upon receiving the `Enter` key, it names it accordingly. Again, this would be non-default behavior.

### Option 2: Introduction of New Keybinding

There could always just be a new keybinding that, when pressed, prompts the user for the filename, then takes the screenshot and names it accordingly.

**Comment by Akemi** [comment]
that is either something a script should do, similar to the console, or maybe just changing the screenshot template prior to taking the screenshot (for example in the console) might work.

**Comment by wm4** [comment]
There's also a command that takes a target filename.

**Comment by jallbrit** [comment]
@Akemi you are correct, someone has already reached out and provided a script which I will leave here for future reference:

```lua
function named_ss()
    local cmd = 'echo | dmenu -p Filename:'
    local name = string.gsub(io.popen(cmd):read('*a'), '\n$', '')

    mp.commandv('screenshot-to-file', name)
end

mp.add_key_binding('s', 'named_ss', named_ss)
```

> You'll want to store that in ~/.config/mpv/scripts/whatever.lua, and then it should automatically be available the next time you launch.

> Unfortunately, mpv's scripting layer doesn't have a function for just requesting a line of input from the user, so instead of resorting to insane hacks, I just shell out—to dmenu in this case, but you could swap in something like zenity—to prompt for the filename.

**Comment by garoto** [comment]
I bet you will use this script half a dozen times and realize how non-productive it is.

**Comment by jallbrit** [comment]
@garoto I don't understand. I've already used it several times and it seems to do the trick. The only thing I've yet to figure out is how to place the screenshots in the correct directory. I assume that is possible with a simple edit or two, but I could be wrong.

What do you mean? I wish that instead of just criticism, you would explain.

**Comment by Akemi** [comment]
just that dmenu is not platform independent and needs X.

**Comment by CogentRedTester** [comment]
I've been experimenting with using console.lua as an inbuilt, cross-platform, way to request user input. Console.lua has a script-message that allows scripts to open the console with text already entered, so it's possible to load a script message command on a keypress. That means script a could theoretically setup a user input script message, and all the user has to do is press a button and append their input to the end as arguments for the script message.

@jallbrit For example I implementing the above script, but setup automatic file extensions and correct directory handling, using this method:

```
local screenshot_directory = mp.command_native({"expand-path", mp.get_property('screenshot-directory', "")})
local screenshot_format = mp.get_property('screenshot-format')

function named_ss()
    mp.commandv('script-message-to', 'console', 'type','script-message save-screenshot ')
end

mp.add_key_binding('s', 'named_ss', named_ss)

mp.register_script_message('save-screenshot', function(name)
    --this command is what closes the console
    mp.command("script-binding console/_console_1")
    mp.commandv('screenshot-to-file', screenshot_directory.."/"..name .."."..screenshot_format)
end)
```

It seems to work pretty well, though there may be some issue with it that I'm not noticing. If mpv were to implement an API for user input, this would seem like the easiest way.
