### ISSUE TITLE
mpv is not written in Rust

### ISSUE THREAD

**Issue by Akaricchi** [mpv-player/mpv#7724]
### Important Information

Provide following Information:
- mpv version: latest from git
- Platform and Version: N/A
- Source of the mpv binary: N/A

### Reproduction steps

In the mpv source directory, run `find -name '*.c'`, followed by `find -name '*.rs'`.

### Expected behavior

The first command (`find -name '*.c'`) should produce no output. The second command (`find -name '*.rs'`) should print a list of mpv's Rust source files.

### Actual behavior

The first command lists an alarming amount of `*.c` files. These are source code written in C, an obsolete and dangerous programming language. The second command produces no output at all, which suggests that mpv is, in fact, not written in Rust. Rust is a modern, safe programming language, featuring fearless abstractions and zero-cost concurrency. It's objectively superior to C and every other language in every way, therefore mpv should be rewritten in Rust as soon as possible.

### Log file

N/A

### Sample files

N/A

**Comment by wm4** [comment]
Can you make a PR to fix this issue?

**Comment by Akemi** [comment]
should totally be swift instead.

**Comment by nxtreaming** [comment]
PR is welcome.

**Comment by lordmauve** [comment]
> The first command (`find -name '*.c'`) should produce no output. 

`find` is not a tool the mpv maintainers support. This bug tracker is for issues with mpv. Perhaps you are looking for https://savannah.gnu.org/bugs/?group=findutils ?

**Comment by HowToJ4ck3t** [comment]
Hey troll, consider doing the same in [your own project](https://github.com/taisei-project/taisei/graphs/contributors) first.

**Comment by saagarjha** [comment]
While I’m not a mpv maintainer, I believe it is their intention to reduce the amount of undefined behavior in the codebase. C meets those goals nicely.

**Comment by wm4** [comment]
Seems like reddit founds this.

**Comment by wm4** [comment]
Also to the idiots in the reddit thread: we talked about this on an IRC channel, and Akaricchi opened this issue as a joke.

**Comment by lordkitsuna** [comment]
I can see this has been unlocked, and rightly so. MPV would benefit from this greatly. We already have support for using Vulkan, thats the first 100% performance increase. With Rust we could get the other 100% and kill memory bugs along the way. Sadly i lack the skills myself but if a maintainer takes up the task and has a patreon i would contribute. :+1:

**Comment by Akemi** [comment]
since we lack the manpower todo this and there wasn't really any discussion going on here any more, i am closing this. this doesn't mean it's completely off the table but we don't need an open issue for this.

**Comment by sudipghimire533** [comment]
If someone writing binding for mpv in rust. Let me know. I am re-writing [ytui-music](https://github.com/sudipghimire533/ytui-music)
