### ISSUE TITLE
Two mpv prints in the same terminal. How to prefix the output?

### ISSUE THREAD

**Issue by ZaxonXP** [mpv-player/mpv#7726]
mpv 0.29.1

I have some bash [scripts](https://github.com/ZaxonXP/youtube-viewer-scripts) which allows me the gapless playback of Youtube content. In short first song is played in first instance of mpv and the second instance caches the song being in pause mode. When first is ending then second is unpaused and next mpv is launched in pause mode.

My issue is that each mpv instance produces the output in the same terminal making it difficult to know what part of the output is from which instance. Is it possible somehow to prefix each instance output by some prefix? Hat command line can be used for this? Or is it some non existing feature?

**Comment by wm4** [comment]
Not possible.

**Comment by ZaxonXP** [comment]
Can it be then moved for the feature request?

**Comment by wm4** [comment]
Seems a bit too special. Instead you could emulate it via any of the following ways:
- pipe it through shell scripts or whatever that add a prefix
- implement whatever you're doing with libmpv and then grab and prefix the log messages
- disable terminal output and output them from a lua script that grab the log messages

**Comment by ZaxonXP** [comment]
Thanks for the suggestions. In fact I found a solution bit later and it is the first one suggested by @wm4 . Here is the Bash function to pipe the mpv process to:
```
prefix_echo () {
  perl -sne '$|=1; print "[$pre]\t\t$_"' -- -pre="$1"
}
```
And using it like this:
```
mpv file | prefix_echo "First" 
```
I added this in case somebody will look for it. :)
