### ISSUE TITLE
Support stat scroll on page 2

### ISSUE THREAD

**Issue by Shashank066** [mpv-player/mpv#7727]
Page 2 with 'Extended Frame Timings' needs scrolling. Currently only page 4 supports scrolling.
Some user shaders have extended output on page 2.

https://github.com/mpv-player/mpv/blob/master/DOCS/man/stats.rst

https://github.com/mpv-player/mpv/blob/master/player/lua/stats.lua

![stats](https://user-images.githubusercontent.com/8770783/82110378-94a6d100-975b-11ea-897c-11d3bbabb47f.jpg)

**Comment by Argon-** [comment]
There's a patch for that made by @avih . I will see to it getting applied this weekend.

**Comment by Shashank066** [comment]
That's great. Thanks.

**Comment by airward-svg** [comment]
> Page 2 with 'Extended Frame Timings' needs scrolling. Currently only page 4 supports scrolling.
> Some user shaders have extended output on page 2.
> 
> https://github.com/mpv-player/mpv/blob/master/DOCS/man/stats.rst
> 
> https://github.com/mpv-player/mpv/blob/master/player/lua/stats.lua
> 
> ![stats](https://user-images.githubusercontent.com/8770783/82110378-94a6d100-975b-11ea-897c-11d3bbabb47f.jpg)

Could you please explain why is a single shader being used multiple times and if you're supposed to get 2x resolution of the source media in the 1st page. I get 1080p being displayed in the first page and I can see that shaders are working in the 2nd page.

**Comment by Shashank066** [comment]
> > Page 2 with 'Extended Frame Timings' needs scrolling. Currently only page 4 supports scrolling.
> > Some user shaders have extended output on page 2.
> > https://github.com/mpv-player/mpv/blob/master/DOCS/man/stats.rst
> > https://github.com/mpv-player/mpv/blob/master/player/lua/stats.lua
> > ![stats](https://user-images.githubusercontent.com/8770783/82110378-94a6d100-975b-11ea-897c-11d3bbabb47f.jpg)
> 
> Could you please explain why is a single shader being used multiple times and if you're supposed to get 2x resolution of the source media in the 1st page. I get 1080p being displayed in the first page and I can see that shaders are working in the 2nd page.

It depends on the shader algorithm. The author of the shader can respond better about benefits of multiple times. AFAIK for upscaling it depends on the algorithm used. The end goal is to upscale/downscale the video to your monitor resolution. The shader could directly upscale it the display resolution, or double the video resolution and downscale it to display resolution, incase display resolution is less than 2x source.

Window-scale stat on 1st stat page can show how much upscaling is happening to the video source resolution. Rest the shader author or someone more familiar with these can correct.

**Comment by Argon-** [comment]
Those are not necessarily the same shaders. Authors can give an arbitrary name to their shaders and they could name all of their shaders all the same.
