### ISSUE TITLE
Seeking in multi-volume rar regression since update

### ISSUE THREAD

**Issue by pasztor** [mpv-player/mpv#7730]
### Important Information

Provide following Information:
- mpv version 0.32.0
- Linux Distribution and Version: Arch linux, just pacman -Syu -ed.
- Source of the mpv binary: pacman -Syu mpv
- If known which version of mpv introduced the problem: [2020-05-17 02:02] [ALPM] upgraded mpv (1:0.29.1-6 -> 1:0.32.0-4)
- Window Manager and version: marco (mate de's default)
- GPU driver and version:
[2020-05-17 02:02] [ALPM] upgraded mpv (1:0.29.1-6 -> 1:0.32.0-4)
firmware:       i915/bxt_dmc_ver1_07.bin
firmware:       i915/skl_dmc_ver1_27.bin
firmware:       i915/kbl_dmc_ver1_04.bin
firmware:       i915/glk_dmc_ver1_04.bin
firmware:       i915/cnl_dmc_ver1_07.bin
firmware:       i915/icl_dmc_ver1_09.bin
firmware:       i915/tgl_dmc_ver2_04.bin
firmware:       i915/skl_huc_2.0.0.bin
firmware:       i915/skl_guc_33.0.0.bin
firmware:       i915/bxt_huc_2.0.0.bin
firmware:       i915/bxt_guc_33.0.0.bin
firmware:       i915/kbl_huc_4.0.0.bin
firmware:       i915/kbl_guc_33.0.0.bin
firmware:       i915/glk_huc_4.0.0.bin
firmware:       i915/glk_guc_33.0.0.bin
firmware:       i915/kbl_huc_4.0.0.bin
firmware:       i915/kbl_guc_33.0.0.bin
firmware:       i915/cml_huc_4.0.0.bin
firmware:       i915/cml_guc_33.0.0.bin
firmware:       i915/icl_huc_9.0.0.bin
firmware:       i915/icl_guc_33.0.0.bin
firmware:       i915/ehl_huc_9.0.0.bin
firmware:       i915/ehl_guc_33.0.4.bin
firmware:       i915/tgl_huc_7.0.3.bin
firmware:       i915/tgl_guc_35.2.0.bin
X.Org X Server 1.20.8
[  1854.208] Build Date: 05 May 2020  05:08:17AM
[  1854.209] (II) Module ABI versions:
[  1854.209]    X.Org ANSI C Emulation: 0.4
[  1854.209]    X.Org Video Driver: 24.1
[  1854.209]    X.Org XInput driver : 24.1
[  1854.209]    X.Org Server Extension : 10.0
[  1854.223] (II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
[  1854.223] (II) Module intel: vendor="X.Org Foundation"
[  1854.223]    compiled for 1.20.8, module version = 2.99.917
[  1854.223]    Module class: X.Org Video Driver
[  1854.223]    ABI class: X.Org Video Driver, version 24.1
[  1854.225] (II) intel(0): Using Kernel Mode Setting driver: i915, version 1.6.0 20200114
[  1854.225] (II) intel(0): SNA compiled from 2.99.917-908-g7181c5a4
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Start play a longer multi-volume avi.
Try to seek with ctrl-pgup (jumps 10min fwd), multiple times.
Depends on the movie, after 3-4-5 jumps it will fail.
With the same movie, fails at the same point. You can jump in smaller steps, but after it reaches a critical point, you can not jump 10 mins again.
Possibly a libarchive regression.

### Expected behavior

Working seeking just like before.

### Actual behavior

libarchive] possibly unsupported seeking - switching to reopening
AV: 00:48:46 / 01:45:19 (46%) A-V:  0.000 Cache: 0.0s
[libarchive] Truncated RAR file data
[libarchive] fatal error received - closing archive
[libarchive] Seek failed (to 2195581626, size 4691393294)
[mkv] Corrupt file detected. Trying to resync starting from position 49964216...

Btw.: If I unrar the file, seek works properly. But I would avoid that if possible.

### Log file

https://0x0.st/iLd5.log

### Sample files

Nope, I don't have one :'(

**Comment by kevmitch** [comment]
Should be already fixed by 2aa5964b43fdd1d584b4f17899aa1ac5e886b7af in git master

**Comment by pasztor** [comment]
Is it possible to issue a hotfix release, like 32.0, or 32.1 which contains fixes for serius usage issues, like this?

**Comment by Akemi** [comment]
i doubt anyone will bother with a hotfix release for this. we would rather do a new full release.

**Comment by pasztor** [comment]
First of all: I did not meant to make a point release only for this. But I can imagine, there were several fixes since 26th of January, when 0.32.0 was released.

When can one expect the next release?

According to the release policy document releases can be expected "Once or twice a month".
Since 26th of January I haven't seen any fresh one.

0.31.0 was released in 28th of Dec.
0.30.0 was released in 25th of Oct.

So far it could be once in every 1 or 2 month, except 0.32.0 was released almost 4 months ago.

0.29.1 was released in 2nd of Oct.
0.29.0 was released in 22th of July.

Between 0.29.0 and 0.29.1 there was less than 3 months, to provide fixes.

Since 26th of January it was almost 4 months.
Can you provide an estimate, when 0.33.0 or 0.32.1 will be released?

**Comment by Akemi** [comment]
no. it's whenever some feels like doing one.

**Comment by CounterPillow** [comment]
>Between 0.29.0 and 0.29.1 there was less than 3 months, to provide fixes.

This was a special case for a security fix. mpv doesn't really do bugfix-only releases outside of special occasions. 

Just run the git version if you're in desperate need of this, releases are mostly just cut for the sake of distributions and git master will almost always be kept in a working state.

**Comment by pasztor** [comment]
I just forked this repo, issued a release on my fork, and built a fresh arch package out of the "release".
Well, it seems the regression is mitigated in a way, that it won't crash. But if you reach the "critical point", the seeking is still pain in the neck.
Looks like, when it reaches the critical poitnt it slows down. At least not crashes anymore.
There are archives when it reopens all volumes right after start, there are files, where you have to seek 5 times 10 minutes, before it reopens the volumes.
Reopens is reallllllllllly slow. Like it would read up the whole content of the rar volumes and from that point on seeking response in that multi-volume archive is quite stochastic.
By "from that point on" I don't mean after the critical point in the movie. I meant, once you open a multi-volume archive and once you reach a critical point in that, you are doomed, until the playback session of that multi-volume content lasts.

Are you interested in fresh debug logs, or should I rather open a fresh issue and post the fresh logs there, or what is the suggested course of actions?

As I said: earlier the seeking was flawless with these files.

**Comment by kevmitch** [comment]
If I understand correctly, you are referring to the fact that seeking backwards requires reopening and rereading the archive to that point, which can be slow. This was always the case and is a result of the fact that the libarchive library used to read rar files "on the fly" doesn't actually support seeking so it needs to be implemented by this hack.

Maybe the previous version in which "seeking was flawless" was with the old built-in uncompressed rar stream handler that was removed in a25b3d61a1c4b98183f7660bc3249321c13093d3. See also bug #7317. Since then, there have been improvements in the mpv's libarchive wrapper, but we can only do so much with the limitations of libarchive. This is why mpv outputs a warning message. That being said, I think behaviour is good enough until libarchive gets better support. Maybe seeking backwards is slow, but it works, and watching something all the way through has no problems at all. If you are really intent on scrubbing through something, it's probably better to decompress it first.

**Comment by CounterPillow** [comment]
Please also see https://github.com/mpv-player/mpv/wiki/FAQ#What_is_the_rar_file_format_and_why_is_it_stupid

**Comment by pasztor** [comment]
> If I understand correctly, you are referring to the fact that seeking backwards requires reopening and rereading the archive to that point, which can be slow. This was always the case and is a result of the fact that the libarchive library, used to read rar files "on the fly", doesn't actually support seeking, so it needs to be implemented by this hack.

Nope. I meant seeking forward. As I said, based on my experiences with multi-volume rar files there are a "critical point".
If you seek forward in 10 minute jumps, and let's say, the critical point is 5 jump, then when you do the fifh jump, it will re-read all the archives, and it seems, like it reads all the archive volumes. While on open it seems, just like some kind of header-check or something. In that case it usually start fast, and until you don't reach the critical point, it's okay. But after that it's -- pardon my french -- crap.
I would say, it's a valid use-case. You don't always have influence on what you get, and you don't want to occupy the disk space two times, to be able to seek. But you want to jump to the point where you left watching -> you are screwed.

> Maybe the previous version in which "seeking was flawless" was with the old built-in uncompressed rar stream handler that was removed in [a25b3d6](https://github.com/mpv-player/mpv/commit/a25b3d61a1c4b98183f7660bc3249321c13093d3). See also bug #7317. Since then, there have been improvements in the mpv's libarchive wrapper, but we can only do so much with the limitations of libarchive. This is why mpv outputs a warning message. That being said, I think behaviour is good enough until libarchive gets better support. Maybe seeking backwards is slow, but it works, and watching something all the way through has no problems at all. If you are really intent on scrubbing through something, it's probably better to decompress it first.

Was there a reason to remove that? Was it hard to maintain? To be honest, one thing I like open source, because I have a choice. Eg. In case of vo, you can define vo, vd, etc. order.

Can it be implemented like that? In my case, I would prioritize the old and flawless method, and in case of rar5s, which seems still rare I deal with the delay by bashing my head against the wall it initializes, and curse the idiot whom uploaded a stupidly distributed content.

**Comment by CounterPillow** [comment]
>Was there a reason to remove that? Was it hard to maintain?

yes, and no, the code is not coming back. Either stop using RAR or improve libarchive.
