### ISSUE TITLE
assertion failure in video/repack.c using vo=wlshm and vo=x11 with 8k video

### ISSUE THREAD

**Issue by LaserEyess** [mpv-player/mpv#7734]
### Important Information

Provide following Information:
```
mpv 0.32.0-486-g3cb9e93cdf Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun May 17 10:09:00 EDT 2020
FFmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
FFmpeg version: n4.2.2
````
Arch Linux 5.6.13 amdgpu
mesa 20.0.7
zimg 2.9.3 

### Reproduction steps
`mpv --no-config --vo={wlshm,x11} 8k_video.webm`

### Expected behavior

No crash
### Actual behavior
mpv crashes with:
```
mpv: ../video/repack.c:910: repack_line: Assertion `!(w & ((1 << first->fmt[0].chroma_xs) - 1))' failed.
```

### Log file
wlshm: https://0x0.st/iLhm.txt
x11: https://0x0.st/iLha.txt
gdb: https://0x0.st/iLhA.txt

git bisected to d8002f1dde94771952b301f4ebe331c52bc71871

### Sample files
I used two files to test this: 
1. `youtube-dl -f 272+251 https://www.youtube.com/watch?v=zCLOJ9j1k2Y`
2. `youtube-dl -f 272+251 https://www.youtube.com/watch?v=1La4QzGeaaQ`

**Comment by LaserEyess** [comment]
This crash does not occur if you add `--fullscreen`

**Comment by wm4** [comment]
I think this was just a zimg upstream bug, which was fixed just now.
