### ISSUE TITLE
[bash] Listen for eof event

### ISSUE THREAD

**Issue by guest271314** [mpv-player/mpv#7735]
The documentation includes reference to `eof` event https://mpv.io/manual/master/#command-interface-eof.

How to listen for `eof` event in `bash`, then do something when event is fired?

**Comment by guest271314** [comment]
`mpv $1 >> /dev/null 2>&1 | grep 'Exiting' && <do something>` appears to achieve expected result. Is there a canonical method to watch for the `end-file` event using `bash`?

**Comment by wm4** [comment]
No, and your method may randomly break if we adjust the terminal output. Write a Lua script, or use the JSON IPC.

**Comment by guest271314** [comment]
@wm4 Just noticed there is a JavaScript API. Will browse the code and documentation, attempt to build and then retry.
