### ISSUE TITLE
mpv keeps streaming audio when nothing is playing

### ISSUE THREAD

**Issue by WhyNotHugo** [mpv-player/mpv#7736]
### Important Information

```
$ mpv --version
mpv 0.32.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on UNKNOWN
ffmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
ffmpeg version: n4.2.2


$ uname -a
Linux aphrodite 5.6.12-arch1-1 #1 SMP PREEMPT Sun, 10 May 2020 10:43:42 +0000 x86_64 GNU/Linux

$sway --version
sway version 1.4
```

- Using the binaries from the official Arch repositories.
- I don't this this is a regression.
- GPU is an Intel, using the drivers that ship with the kernel.

#### Scenario 1

1. Play something with sound.
2. Pause it.

### Expected behavior

The stream to pulseaudio should stop.

### Actual behavior

The stream to pulseaudio is kept active:

```
$ pactl list sinks | grep -A 3 Sink
Sink #0
	State: RUNNING
	Name: alsa_output.pci-0000_00_1f.3.analog-stereo
	Description: Built-in Audio Analog Stereo
```

My headphones connect to both my laptop and phone, but since the laptop stream is still running, it won't switch to another device, so I can't play audio with my phone. I need to kill mpv (on my laptop!) to get audio from my phone.

More background on this pulseaudio issue where we narrowed down the cause: https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/892

### Expected results:

The audio stream should be suspended.

### Log file

[output.txt](https://github.com/mpv-player/mpv/files/4640733/output.txt)

### Sample files

Any file with audio will do.

**Comment by wm4** [comment]
We "cork" the stream, but nobody really knows how pulseaudio works (or is supposed to), so WONTFIX.

**Comment by wm4** [comment]
If PA don't solve this issue, I recommend uninstalling PA, and using ALSA. Works great.

**Comment by WhyNotHugo** [comment]
> We "cork" the stream, but nobody really knows how pulseaudio works (or is supposed to), so WONTFIX.

I'm happy to help figure out any specific questions, responses on the pulseaudio developer's side have been very helpful so far.

> If PA don't solve this issue, I recommend uninstalling PA, and using ALSA. Works great.

Changing the entire audio subsystem of my operating system is not a really feasable workaround for this kind of bug, that looks like a huge undertaking, if even possible (there's no guarantee that all my desktop applications would even work).

**Comment by wm4** [comment]
"Corking" is apparently PA's pausing mechanism, and we use it. That seems to be the native way to do it, and unless we get further input from a developer who knows the PA API, I don't know what else we'd do.
Maybe we could close the stream completely, but that fits badly into our architecture, so we won't do it. So that's a clean WONTFIX.
(Though you could write a script that deselects/reselects the audio stream on pausing. Not ideal but could work.)

**Comment by WhyNotHugo** [comment]
Thanks for the extra details. I'll keep following up trying to figure out what _can_ be done on the PA side.

Thanks for you work on mpv by the way, I've been very happily using it for so many years I've lost count!

**Comment by kevmitch** [comment]
This is what I use to release my audio device on pause and restore it on resume

```
mp.set_property_native("audio-fallback-to-null", true)

audio_device = nil
mp.observe_property("pause", "native", function(name, val)
    if val then
        audio_device = mp.get_property_native("audio-device")
        mp.set_property("audio-device", "null")
    elseif audio_device then
        mp.set_property_native("audio-device", audio_device)
    end
end)
```
