### ISSUE TITLE
DVD-menu and other dvd features support . DONT! ignore it please

### ISSUE THREAD

**Issue by AkshatJ05** [mpv-player/mpv#7737]
Hey mpv dev team vlc is trash your product is bonkers I love it but the only reason i have vlc is to play dvd-menu and also support Closed Captions are also good . Pls add it .

**Comment by CounterPillow** [comment]
Please read https://github.com/mpv-player/mpv/wiki/FAQ#Why_is_there_no_DVDBluray_menu_support_And_DVDBD_support_in_general

**Comment by AkshatJ05** [comment]
Is there a way I can Do that ?

**Comment by CounterPillow** [comment]
Yes, mpv is free and open software, anyone can get a copy of the source code from GitHub and modify and redistribute it in accordance with the GPL, as well as contribute changes back to the project after they undergo a code review.

**Comment by AkshatJ05** [comment]
> Yes, mpv is free and open software, anyone can get a copy of the source code from GitHub and modify and redistribute it in accordance with the GPL, as well as contribute changes back to the project after they undergo a code review.

I think I found The right match for me i.e. KODI from XBMC and mpv from mpv team will fulfil my forever needs , mpv's opening times are mind blowing even in hard drives . Keep up the good work & stay safe out there Fam.

**Comment by AkshatJ05** [comment]
Are you guys planning to release it on microsoft store as an UWP app ? Or not?

**Comment by Akemi** [comment]
we do not release any binaries.
