### ISSUE TITLE
`*out_display` get a value but `out_display` is checked in vaapi.c

### ISSUE THREAD

**Issue by qarmin** [mpv-player/mpv#7739]
https://github.com/mpv-player/mpv/blob/26f4f18c0629998a9b91e94722d166866d8b80a3/video/vaapi.c#L228-L232

I'm must delete issue template, because it is for me unnecessary, sorry.

For more potential bugs looks at https://qarmin.gitlab.io/-/mpv/-/jobs/557351376/artifacts/report/index.html

**Comment by wm4** [comment]
That is not a bug, if you thought so.

**Comment by qarmin** [comment]
I'm not sure if this is correct, because in other places `*out_display` was checked like in

https://github.com/mpv-player/mpv/blob/26f4f18c0629998a9b91e94722d166866d8b80a3/video/vaapi.c#L189-L192

**Comment by wm4** [comment]
Oh, you're right, I looked at a similar piece of code and got confused.
