### ISSUE TITLE
Setting value to variable clockid is useless because variable isn't used

### ISSUE THREAD

**Issue by qarmin** [mpv-player/mpv#7740]
clockid isn't used, probably this variable should be passed by reference

https://github.com/mpv-player/mpv/blob/ca531b1cb2324d8ebd7c6d2b6747e401989c4e01/video/out/wayland_common.c#L827-L834

**Comment by Dudemanguy** [comment]
Not sure what I was on when I originally wrote this part of the code, but it should have been a check to make sure clockid was `CLOCK_MONOTONIC`. Thanks for pointing this out.
