### ISSUE TITLE
av:// input + specifying duration

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7747]
Pretty simple, I just want to specify a duration for an av input like:

`mpv av://lavfi:color=c=red:size=640x480:rate=30`

I've tried adding something like `--stream-lavf-o=t=10` but it doesn't work, after 10 seconds it continues playing forever.

Any ideas?

**Comment by Akemi** [comment]
`mpv av://lavfi:color=c=red:size=640x480:rate=30:duration=1`

**Comment by hedgehog90** [comment]
Sorry, my example was a tad too simple.

This is my command and after 10 seconds it still continues indefinitely:

```
mpv "av://lavfi:color=c=black:s=1920x1080:duration=10,fps=30[m1];movie=\'logo.png\'[m2];[m1][m2]overlay[out0];anullsrc=channel_layout=stereo:sample_rate=44100[out1]" --stream-lavf-o=t=10
```

The movie filter doesn't have a duration property so it just goes on and on. The only way to kill it is with the -t arg in ffmpeg.

If you're wondering why I'm executing such an unusual command it's because it has to work in the context of encoding mode (--o=...). Providing an image input or using the mf:// protocol just doesn't work in a playlist as it only outputs 1 frame.

**Comment by Akemi** [comment]
that's an ffmpeg thing, so you should rather ask them. i would guess, either insert a trim filter somewhere or use --end=10 (which will probably not work in encoding mode).
