### ISSUE TITLE
Will MPV have a winget package?

### ISSUE THREAD

**Issue by rockisch** [mpv-player/mpv#7751]
So, windows now have a kind of an official package manager, [winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/). I was wondering if MPV is going to submit it's Windows builds to it, since it will be the one that will come by default on future Windows installs.

Seems like the process is really straightforward (see [here](https://github.com/microsoft/winget-pkgs)) and anyone can do it, but I don't think adding it to a package manager without consent would be a good idea.

**Comment by Akemi** [comment]
since we don't do that for any package manager on linux or macOS either, the answer is no. though this will not prevent individual people associated with our project to do it.

**Comment by CounterPillow** [comment]
windows is a deprecated OS

**Comment by hazre** [comment]
I'm sorry but you guys provide Chocolatey and Scoop packages but not Microsoft's official package manager?

**Comment by garoto** [comment]
> I'm sorry but you guys provide Chocolatey and Scoop packages [...]

This is all work of unvetted third-parties, and the funny bit is that they all use shinchiro's builds to populate this or that Windows package manager repo.

**Comment by CodeCubeNeo** [comment]
But still the official way is usualy better

**Comment by reyqn** [comment]
Those answers are quite pathetic to be honest. Your own documentation endorses those builds, why trash talk them? Also I'm not sure how Windows is a deprecated OS? Microsoft still seems to support it, or maybe you have a source on this? This is really childish behavior.

**Comment by kasper93** [comment]
> Those answers are quite pathetic to be honest.

Good way to start conversation.

> Also I'm not sure how Windows is a deprecated OS?

I'm always amazed how such low quality baits gets people...

> This is really childish behavior.

Good to see that your adult comment is eloquent and well-thought-out.

Back to the topic, go complain here. https://github.com/microsoft/winget-pkgs/issues/110881 We don't distribute packages on any platform, it is community effort to provide them. And you have big selection already.

Only official packages are build on CI and uploaded as artifacts connected to each comment, which you can find here (for the latest commit on master) https://nightly.link/mpv-player/mpv/workflows/build/master

If you are willing to sponsor effort to distribute and maintain packages for some platform, I'm sure we can arrange something. And you can always help directly by maintaining it yourself.

**Comment by reyqn** [comment]
> > Those answers are quite pathetic to be honest.
> 
> Good way to start conversation.

Read two comments up mine.

> > Also I'm not sure how Windows is a deprecated OS?
> 
> I'm always amazed how such low quality baits gets people...

It's an answer from someone marked as a "collaborator", like the one I was referencing in my first sentence. It's just in bad taste.

> > This is really childish behavior.
> 
> Good to see that your adult comment is eloquent and well-thought-out.
> 
> Back to the topic, go complain here. [microsoft/winget-pkgs#110881](https://github.com/microsoft/winget-pkgs/issues/110881) We don't distribute packages on any platform, it is community effort to provide them. And you have big selection already.
> 
> Only official packages are build on CI and uploaded as artifacts connected to each comment, which you can find here (for the latest commit on master) https://nightly.link/mpv-player/mpv/workflows/build/master
> 
> If you are willing to sponsor effort to distribute and maintain packages for some platform, I'm sure we can arrange something. And you can always help directly by maintaining it yourself.

You're right, my comment isn't helpful, and everything was said in the first answer to the issue, I shouldn't have given any interest to the rest of the comments which don't add anything useful.
