### ISSUE TITLE
geometry doesn't position some videos correctly

### ISSUE THREAD

**Issue by github-account1111** [mpv-player/mpv#7755]
### Important Information

Provide following Information:
- mpv version 0.32.0-484-g152b0e2a8c
- Windows Version LTSC 2018
- Source of the mpv binary https://sourceforge.net/projects/mpv-player-windows/files/64bit/
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches 
![Untitled](https://user-images.githubusercontent.com/5728319/82737506-f699a480-9d20-11ea-90ae-533986de5425.png)

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

1. Put `geometry=0:0` in `mpv.conf`.
2. Play a video by left-clicking or via the `Open with` menu. The issue only arises in some videos, can't figure out what's special about them, but it's around 30% of the videos I've tested.

### Expected behavior
Video snaps to top-left corner by default.
### Actual behavior
Video is positioned elsewhere on screen (see screenshot).
### Log file

[output.txt](https://github.com/mpv-player/mpv/files/4672318/output.txt)

The issue will be closed for ignoring the issue template.

### Sample files

This one has the issue and appears way off the screen:
https://www.youtube.com/watch?v=aqz-KE-bpKQ
(`youtube-dl https://www.youtube.com/watch?v=aqz-KE-bpKQ`).

**Comment by Skibicki** [comment]
Use snap-window and no-border, but disable geometry. This gives me centered video on Windows 8.1 but I don't know what Windows 10 will do.

The difference in some videos is from the resolution. mpv and youtube-dl have options to select other formats.
https://mpv.io/manual/master/#options-ytdl-format
https://github.com/ytdl-org/youtube-dl#format-selection

1080 Limit: `ytdl-format=bestvideo[ext=mp4][height<=?1080]+bestaudio`

**Comment by github-account1111** [comment]
I can snap the video to the top-left corner just fine _after_ it starts up. I want it to already be there on startup.

Also, this is a local file.

> Use snap-window and no-border, but disable geometry. This gives me centered video on Windows 8.1 but I don't know what Windows 10 will do.

Yes. It's the same way for me. If I don't use geometry, all the videos start centered. But that's not the behavior I want.

**Comment by garoto** [comment]
Play around with `--autofit-larger=[width]%x[height]%` or just `--autofit`

**Comment by wm4** [comment]
Didn't read most of this. Does it work if you pass a width and height too?

**Comment by github-account1111** [comment]
> Didn't read most of this. Does it work if you pass a width and height too?

Yup. Setting the size makes all the videos snap to top-left on startup.

**Comment by github-account1111** [comment]
> 
> 
> Play around with `--autofit-larger=[width]%x[height]%` or just `--autofit`

Oh hey, that fixes it I think! `autofit-larger=100%x100%`. I guess the issue was the taskbar, since only the videos that are 1080p in height had the problem!
