### ISSUE TITLE
If multiple subtitle with same language present, how to automatically choose subtitle with most lines ?

### ISSUE THREAD

**Issue by LazyGeniusMan** [mpv-player/mpv#7756]
Hi, how to automatically choose subtitle with most lines if multiple subtitle with same language present ?

For example, a video has 2 variant (only foreign and all dialogs) with same language. Let's say that I want to automatically choose all dialog variant that has most lines, is it possible ?

As far as I know automatically choose subtitle could be done with `slang=<lang>`, but it seems it didn't have advanced parameter/arguments.

**Comment by Akemi** [comment]
no that is not possible.
