### ISSUE TITLE
dynamic audio limiter/normaliser on clipping cases

### ISSUE THREAD

**Issue by Nes-si** [mpv-player/mpv#7761]
When I play the sample file, I hear a sound clipping (like it exceeds its maximum level). When I play it on VLC player, the distortion is almost inconspicuous.
[Sample file](https://0x0.st/ipyz.mkv) (it's very short)
I've analyzed the file's DTS track. It contains a main sound in L, R and C channels. No one of them clipps, but the signal levels are quite high, close to 0 dB. Seems like the clipping occurs during the 5.1->2.0 downmixing — the downmixing algorithm just summarizes C to L and to R, so the result has more than 0 dB levels that are just truncated. And VLC's algorithm is more intellegent and reduces levels before downmixing to avoid clipping.

- mpv version — 0.32.0
- macOS Version — 10.13.6
- Source of the mpv binary or bundle — build by stolendata
- Tried with --no-config
- [Log](https://0x0.st/ipyZ.txt)

**Comment by kevmitch** [comment]
`audio-normalize-downmix=yes` should fix it. 

Funny you mention VLC, we had previously adopted to `audio-normalize-downmix=no` to match VLC behaviour because people complained about the downmix being too quiet. Maybe we should rethink this.

**Comment by kevmitch** [comment]
Implicit in this is that VLC changed their default to at some point.
