### ISSUE TITLE
Display abnormal

### ISSUE THREAD

**Issue by rgbFrank** [mpv-player/mpv#7765]
### Important Information
Qt Creater 4.4.1 based on Qt5.9.2
Macbook air 10.13

mpv 0.32.0-521-gb1d16a2300 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Wed May 27 00:17:33 CST 2020
FFmpeg library versions:
   libavutil       56.31.100
   libavcodec      58.54.100
   libavformat     58.29.100
   libswscale      5.5.100
   libavfilter     7.57.100
   libswresample   3.5.100
FFmpeg version: 4.2.3
 
### Expected behavior
play video normal.

### Actual behavior
When play video on macbook air with macos 10.13, it only show left-bottom part video. But macbook pro 10.14 and 10.15 is work ok.

### Sample Code
This is mine mpv init code.

- MpvWidget::MpvWidget(QWidget *parent, Qt::WindowFlags f)
    : QOpenGLWidget(parent, f)
    ,isRunReceive(false)
{
    pauseFlag = false;
    muteFlag = false;

    m_isKeepRatio = true;
    m_zoomValue = 0;
    m_volume = 100;

    m_mpv = mpv::qt::Handle::FromRawHandle(mpv_create());
    if (!m_mpv)
        throw std::runtime_error("could not create mpv context");

    mpv_set_option_string(m_mpv, "msg-level", "all=no");
    if (mpv_initialize(m_mpv) < 0)
        throw std::runtime_error("could not initialize mpv context");

    // Make use of the MPV_SUB_API_OPENGL_CB API.
    mpv::qt::set_option_variant(m_mpv, "vo", "libmpv");
    mpv::qt::set_option_variant(m_mpv, "hwdec", "yes");

    mpv_observe_property(m_mpv, 0, "time-pos", MPV_FORMAT_DOUBLE);

    mpv_set_wakeup_callback(m_mpv, wakeup, this);

}

### Sample files
![01F06CD0-DB87-4D97-8D72-5B0120F0351B](https://user-images.githubusercontent.com/8362732/82983196-437fc280-a022-11ea-909b-4640c7679337.png)

**Comment by Akemi** [comment]
with that kinda of info i doubt anyone can help you. this looks more like related to the rendering code or whatever is used as a context (layer, opengl context/nsview/, openglview, etc). maybe highdpi related or whatever. since mpv uses the same api internally, and it most likely works with that, the problem must be on your end and code.
