### ISSUE TITLE
m3u8 http live streaming (hls) playback not using all offered parts

### ISSUE THREAD

**Issue by DonRichie** [mpv-player/mpv#7768]
Hello devs,

### Behaviour
I wrote a small Flask application giving me a http server providing an m3u8 file.
The idea of my program was to extend a given hls-URL with only 3 parts to one having all the parts, so I can play a live stream from the beginning. (You can find it here: https://paste.ricl.de/view/13bcbb96)

But when entering "mpv http://127.0.0.1:5000" only the last 3 parts of my file are playing.

My program gives the following text via http-GET using "application/x-mpegURL" as Mimetype:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:10
#EXTINF:10.00,
https://url/gear5_0.ts
#EXTINF:10.00,
https://url/gear5_1.ts
#EXTINF:10.00,
https://url/gear5_2.ts
#EXTINF:10.00,
https://url/gear5_3.ts
#EXTINF:10.00,
https://url/gear5_4.ts
[...]
```
(>800 parts in total)

### Problem and Expected Behaviour
- The expected behaviour was that mpv doesn't only play the last 3 parts (which is around part 800 in my example) but instead starts playing from the beginning with part 0. 
- If it starts to play at the end of the stream I would like to have a way to rewing the tape back to the start.

What led me to open an issue was that vlc is working as expected. If I open the URL via vlc the file starts playing from the first part and is dynamically searchable to any location up to the recent part.
Since it is working in VLC I would assume my m3u8 files syntax is correct. I also guarantee that every single file I included in the m3u8 is downloadable.

### Recommended Changes
- Make mpv not only play the last 3 files when the user provided m3u8-url offers more!
- If there is something wrong with my m3u8 file, I would like a log message saying what happened.

**Comment by wm4** [comment]
That's a ffmpeg issue. You can pass the libavformat option from mpv to the ffmpeg HLS code by using --demuxer-lavf-o. FFmpeg doesn't provide enough API as that we could handle this well.

**Comment by DonRichie** [comment]
Thank you @wm4 for pointing me to the right direction

**Comment by wm4** [comment]
Of course it would be good if ffmpeg just added the required API bits so mpv could do this on its own.

**Comment by adriel** [comment]
> That's a ffmpeg issue. You can pass the libavformat option from mpv to the ffmpeg HLS code by using --demuxer-lavf-o. FFmpeg doesn't provide enough API as that we could handle this well.

Are you able to elaborate on which libavformat option/s are needed? I'm not sure I get what I need to change.
I'm facing the same issue as the OP.
