### ISSUE TITLE
Libmpv only copy-back hwdec's work

### ISSUE THREAD

**Issue by hatharry** [mpv-player/mpv#7769]
### Important Information

Provide following Information:
- mpv version - 0.32
- Windows Version - 1909
- Source of the mpv binary - windows download

### Reproduction steps
Create a electron plugin using:
<mpv/render_gl.h>,<GLES2/gl2.h>, etc

### Expected behavior
Setting hwdec=auto defaults to d3d11va
or any non copy-back is selected

### Actual behavior
Setting hwdec=auto defaults to dxva2-copy
Setting hwdec=d3d11va produces this error:
[   0.828][v][vd] Looking at hwdec h264-d3d11va...
[   0.828][v][vd] Could not create device.
[   0.828][v][vd] No hardware decoding available for this codec.
[   0.828][v][vd] Using software decoding.

### Log file
[mpv.log](https://github.com/mpv-player/mpv/files/4692740/mpv.log)
[mpv-auto.log](https://github.com/mpv-player/mpv/files/4692744/mpv-auto.log)

**Comment by wm4** [comment]
The part of the log about libmpv renderer initialization is missing for some reason, so I can only guess. Old ANGLE dll?

**Comment by hatharry** [comment]
Using the same angle dll as electron

mpv exec:
[   2.703][v][vo/gpu] GL_VERSION='OpenGL ES 3.0.0 (ANGLE 2.1.0.362168eb695d)'
[   2.703][v][vo/gpu] Detected GLES 3.0.
[   2.704][v][vo/gpu] GL_VENDOR='Google Inc.'
[   2.705][v][vo/gpu] GL_RENDERER='ANGLE (Radeon RX 590 Series Direct3D11 vs_5_0 ps_5_0)'
[   2.705][v][vo/gpu] GL_SHADING_LANGUAGE_VERSION='OpenGL ES GLSL ES 3.00 (ANGLE 2.1.0.362168eb695d)'

libmpv:
[   0.017][v][libmpv_render] GL_VERSION='OpenGL ES 2.0 Chromium'
[   0.017][v][libmpv_render] Detected GLES 2.0.
[   0.060][v][libmpv_render] GL_VENDOR='Google Inc.'
[   0.063][v][libmpv_render] GL_RENDERER='ANGLE (Radeon RX 590 Series Direct3D11 vs_5_0 ps_5_0)'
[   0.070][v][libmpv_render] GL_SHADING_LANGUAGE_VERSION='OpenGL ES GLSL ES 1.0 Chromium'

The dll has OpenGL ES 3.0.0 but looks like the Pepper Plugin api only supports OpenGL ES 2.0.

**Comment by wm4** [comment]
Right, when you run under PAPI, libmpv gets the Chromium WebGL implementation, which is isolated from ANGLE. There is no way of getting direct hardware decoding with this, or anything better than GLES 2.0.
