### ISSUE TITLE
running mpv with --log-file generated 42GB log after an hour

### ISSUE THREAD

**Issue by hedgehog90** [mpv-player/mpv#7774]
### Important Information

Provide following Information:
mpv 0.32.0-456-g4e94b2177a
FFmpeg version: git-2020-05-10-5727b1f13

### Reproduction steps

The file I was playing was badly encoded and it generated over 500 million lines of this:

`[ao/lavc] audio frame pts went backwards (701101520 <- 657282675), autofixed`

Setting --msg-level to all=no or ao/lavc=no doesn't help.

How do I prevent this warning from being written to the log?

**Comment by CounterPillow** [comment]
`--msg-level` cannot force the verbosity below the one `--log-file` raises it to, this is documented in the manual for `--log-file`. If you are not actively trying to debug or report an issue, don't use `--log-file`.

**Comment by wm4** [comment]
log-file is enabled by default on OSX though. On the other hand, this is only with encoding mode.

**Comment by hedgehog90** [comment]
Due to the proneness of bugs in encoding mode it is necessary to enable a log file even in my 'production' build (running on my remote server).
At the very least there should be a limit to certain log messages to prevent this happening.

Not sure why the issue was closed. If I had left it running for a few more hours it would have filled my harddrive. This is a severe defect.

**Comment by wm4** [comment]
Well, what mpv does here is logging a serious issue. And apparently it's happening for each frame. Probably a bad corner case. I'd suspect wrong sample rate or otherwise broken audio timestamps. It'd probably better to fix the root cause.

**Comment by CounterPillow** [comment]
>Due to the proneness of bugs and quirks in encoding mode it is necessary to enable a log file even in my 'production' build

redirect the terminal output?

>(running on my remote server)
> os:win

oh no

**Comment by hedgehog90** [comment]
I run it locally on Windows 10, my remote server is Ubuntu 16.04
I'm encountering this problem a lot in encoding mode still. It's not an issue to do with corrupted files. It just occasionally happens when transitioning from one file in the playlist to another.

Like I said, encoding mode is not very robust (as evidenced by this warning overload) so it's necessary to use log files to keep track of certain issues.
This really needs to be addressed, I can't use log files otherwise.

**Comment by garoto** [comment]
`encoding mode` is currently deprecated for lack of maintainer. Use ffmpeg.

**Comment by wm4** [comment]
Likely for a similar reason as this message. I might reinstate and extend encoding mode if everything goes well (I know that _I_ don't want to be forced to use ffmpeg CLI). But yeah, right now it's marked as "broken shit".

**Comment by wm4** [comment]
On that note, maybe you should provide a sample file.

**Comment by hedgehog90** [comment]
I worked it out. I was using using the audio filter 'loudnorm'.
At the transition point between files, it goes nuts with 'audio frame pts went backwards' warnings.
Would appreciate it if someone could look into this.

```mpv 1.mkv 2.mkv --o=out.mkv --of=mpegts --ovc=libx264 --oac=aac --oacopts=ac=2,b=160k --audio-channels=stereo --ad-lavc-downmix=no --force-seekable=no --no-audio-display --af-add=@loudnorm1:lavfi=[loudnorm] --vf=lavfi=[scale=-2:480]```

**Comment by wm4** [comment]
Does this still have to do with encoding mode or is this a distraction attack?

**Comment by hedgehog90** [comment]
> Does this still have to do with encoding mode

Yes.
Just try running the command and observe the issue.
Running it in gui mode without the --o argument works fine.

**Comment by wm4** [comment]
I'm not getting any errors when encoding with loudnorm on.

**Comment by hedgehog90** [comment]
Just tested the latest mpv release and it appears the issue has been resolved.
I assumed I was reasonably well up-to-date with mpv-20200510-git-4e94b21.
Sorry about that.

I hope you don't decide to stop supporting encoding mode at some point. Although it occasionally has issues there is no other open source alternative that I'm aware of that is suitable for my purposes.

**Comment by wm4** [comment]
>Just tested the latest mpv release and it appears the issue has been resolved.

Must be a coincidence, or just random.

Personally, I like encoding mode too, but if there are too grave problems with it that require major effort to fix, I'd rather axe it than leaving it in a half-working state.

**Comment by wm4** [comment]
What mentally occupies me currently is the hacky and broken way audio PTS are passed from playloop to encoder. But that should be fixed with my audio rewrite (if it ever finishes...).
