### ISSUE TITLE
Player compatibility

### ISSUE THREAD

**Issue by prikshitgupta** [mpv-player/mpv#7775]
Will mpv player work with tvOS, iOS, mac catalyst? Is mpv player use metal?

**Comment by Akemi** [comment]
1. mpv currently no, libmpv does already
2. currently no, in the future most likely in some way

**Comment by prikshitgupta** [comment]
Sorry i am new to this. What is libmpv?

**Comment by wm4** [comment]
mpv as a library, unsurprisingly.
https://mpv.io/manual/master/#embedding-into-other-programs-libmpv

**Comment by prikshitgupta** [comment]
Oh ok thank you guys, i will look into it
