### ISSUE TITLE
Constant framedrops with hwdec=mediacodec-copy

### ISSUE THREAD

**Issue by sfan5** [mpv-player/mpv#7777]
### Important Information

<pre>
[cplayer:v] mpv 0.32.0-344-g6a13954d67 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
[cplayer:v]  built on Sat May 30 11:56:45 CEST 2020
[cplayer:v] FFmpeg library versions:
[cplayer:v]    libavutil       56.48.100
[cplayer:v]    libavcodec      58.87.101
[cplayer:v]    libavformat     58.43.100
[cplayer:v]    libswscale      5.6.101
[cplayer:v]    libavfilter     7.83.100
[cplayer:v]    libswresample   3.6.100
[cplayer:v] FFmpeg version: N-97930-gc7c8f141eb
</pre>

<b>This is a regression, which I have bisected to 6a13954d67143fb3c4ac8a4a7624c23e3ecb9a3c.</b>

Happens with `ao=opensles` too, doesn't happen if hwdec is disabled.

### Reproduction steps

Play a video in mpv-android with hwdec enabled.

### Expected behavior

1. No framedrops

### Actual behavior

1. Constant framedrops / choppy playback when there should be none:
![x](https://user-images.githubusercontent.com/1042418/83325892-29d3ba80-a270-11ea-92f8-9d0b2f28c317.gif)

### Log file

Nothing useful in there but here is it anyway: https://0x0.st/ifOe.txt

**Comment by wm4** [comment]
Speculative fix, please test.

**Comment by sfan5** [comment]
Works, thanks.
