### ISSUE TITLE
Command line code to display video from a capture card

### ISSUE THREAD

**Issue by thewebengine** [mpv-player/mpv#7778]
I am trying to access a capture card using the MPV command line, so I can display a video window of the capture card on Windows 10 Desktop.

Any suggestions please?

Thanks

**Comment by CounterPillow** [comment]
try `mpv av://dshow:video="capturecardname":audio="capturecardname"`, no clue whether this will work because of ffmpeg's wacky way of specifying the capture device with the dshow input but it's worth a try.

**Comment by garoto** [comment]
`ffmpeg -list_devices true -f dshow -i dummy` to get a list of names.

**Comment by garoto** [comment]
> no clue whether this will work [...]

Looks correct to me.

**Comment by thewebengine** [comment]
Thank you both,

This works a treat!

Much appreciated.
