### ISSUE TITLE
Show list of available languages with additional information about them

### ISSUE THREAD

**Issue by Pzixel** [mpv-player/mpv#7781]
I'm a huge fan of MPC-HC, but as you probably know this project is dead so I'm looking for a replacement. And I watch movies with multiple languages all the time. The problem here is in MPC I can make a decision which language I want to set but in MPV I cannot.

For example, this is my bought copy of Shrek movie. When I open it in MPC-HC I can choose between multiple languages and subtitles:

![image](https://user-images.githubusercontent.com/11201122/83340915-46123e80-a2e6-11ea-8b47-37c0c2414739.png)

Now, I can see that if I want to watch english in best quality I need to chose the latest, if I want to listen russian in best quality I need to chose # 12 and so on. The same point still for the subtitles.

Unfortunately, in MPV I only see languages count and I can't decide which one to use. Although I can switch between languages even in this case I have little information about the track:

![image](https://user-images.githubusercontent.com/11201122/83340958-d05aa280-a2e6-11ea-89d5-02291c797b0d.png)

So my UX is basically non-existing.

### Expected behavior of the wanted feature

I propose to add "list languages" and "list subtitles" hotkey (and hopefully, triggered by mouse right-click on relevant buttons as well), that should print list of languages (or subtitles) with short summary about each (bitrate is vital). Currently you can change languages so mouse click is working and you print currently selected language, so printing something on this action works too. It just need to print a list instead of one entry and include some details.

This feature is priceless for files with multiple languages and/or subtitles, and it seems to be relatively cheap (all the required features already exist in the player, you only need to shuffle them a bit), so I think this feature has quite a good net worth overall.

**Comment by wm4** [comment]
Yes, that might be nice.

There's no interactive and scrollable list GUI thing anywhere in the player, so that's a big bit missing. Someone would have to implement it.

Normally, you start the player from the terminal, where it lists all tracks and a good deal of information, and you'd just restart the player with the relevant track selection options if just cycling through doesn't cut it.

Not sure why you say that bitrate information is vital. That's certainly useless for subtitles.

**Comment by CounterPillow** [comment]
the track-list property sort of might work for you, it's by default shown by pressing F9. However, the OSD not knowing how big it is will most certainly cut off information if you have a lot of tracks.

**Comment by wm4** [comment]
Of course that's not interactive, and not scrollable.

**Comment by shabahengam** [comment]
maybe this project can help
https://github.com/darsain/uosc
select subtitles
![uosc-sub](https://user-images.githubusercontent.com/53096747/83343259-0f9bea00-a30d-11ea-8b7a-dfd68f1073c3.jpg)
select audio
![uosc-audio](https://user-images.githubusercontent.com/53096747/83343262-17f42500-a30d-11ea-8ede-40b32e4d1f64.jpg)

**Comment by Pzixel** [comment]
@wm4 I say bitrate is vital for audio.

> There's no interactive and scrollable list GUI thing anywhere in the player, so that's a big bit missing. Someone would have to implement it.

Although scrollable list would be nice it's good enough to just print it like this:

![image](https://user-images.githubusercontent.com/11201122/83350992-fc0e7480-a348-11ea-9b58-670e99da75f3.png)

So you just print it on the screen and then user can click "change language" N times (or probably there should be a hotkey to choose track by number).

@CounterPillow Right, something like F9, but which fits to the screen and has required details.

Scrollable option is preferable, but it's much harder to implement, and in this case all we need is calculate font size to make list fit into the screen and add additional information that affects language selection. This one doesn't provide enough info to make a decision:

![image](https://user-images.githubusercontent.com/11201122/83351064-8e167d00-a349-11ea-863f-5838725bff9c.png)

**Comment by Pzixel** [comment]
So... What do you think?

In the end I think maybe I could implement it although I'm a no expert in C and not sure if you accept such a change, but I really think this is a huge gap in the player.

**Comment by wm4** [comment]
As I said, I'm open to it. But someone has to do the work. (There's some chance I'll try it and produce something ugly.)

This would probably be implemented in Lua, not C. Most likely you'd just add it to osc.lua. (There might be better ways to do this, but for now it's what it is.) You could also just start by writing it as a new script, so you don't even need to be able to build the player.

**Comment by Pzixel** [comment]
Thanks, I'l try to grab it on weekends, I guess.

> You could also just start by writing it as a new script, so you don't even need to be able to build the player.

That's a cool proposal, but how do I check if it works if I don't build the player? I mean it's a script language, no types or anything, I'm feeling quite insecure when I can't even typecheck it. How can I make sure if I write something making sense?

**Comment by wm4** [comment]
> I mean it's a script language, no types or anything, I'm feeling quite insecure when I can't even typecheck it. How can I make sure if I write something making sense?

You check whether the script works or crashes. If you have any suggestions for a typed scripting language, I'm open to it. You could also write a C plugin in any language that can import C symbols (at least on Linux), but that probably goes too far.

Building isn't needed for normal external scripts. You can even take osc.lua and load it externally (use --no-osc to disable the internal copy).

**Comment by Pzixel** [comment]
Ahh, so I can run compiled player with my script and make it work that way? Cool.

> You check whether the script works or crashes. If you have any suggestions for a typed scripting language, I'm open to it.

No-no-no, lua is fine. I'm just saying that I need to check if things are working before creating a PR. It seems that I can do it with precompiled player.


P.S. Your avatar alvays make me nervous if something on the page didn't load correctly.

**Comment by kasper93** [comment]
Should be fixed by #15166 and other recent changes in this area, like select.lua.
