### ISSUE TITLE
Calling mp.set_property() over "file-local-options/"+list_option+action has no effect

### ISSUE THREAD

**Issue by fbriere** [mpv-player/mpv#7784]
- mpv version: master
- Platform and Version: Debian 10.4 (buster)
- Source of the mpv binary: self-built

In a Lua script, calling `mp.set_property()` over a list option using the `file-local-options/` prefix and an action suffix does not have any effect.  Here's a simple script that illustrates this (contrasting it with a working `change-list`):

~~~
-- Substitute any list option name/value which works best for you
option_name, value = "sub-files", "test.ass"

mp.add_hook("on_load", 50, function()
    file_local_option_name = "file-local-options/" .. option_name

    mp.set_property(file_local_option_name .. "-append", value)
    mp.msg.warn(mp.get_property(option_name))

    mp.commandv("change-list", file_local_option_name, "append", value)
    mp.msg.warn(mp.get_property(option_name))
end)
~~~

The first displayed value (after `mp.set_property()`) is empty, while the second (after `change-list`) is correctly set.

**Comment by wm4** [comment]
Using options like `...-append` as properties never worked, should have never worked, and will never work. Not sure what the confusion here is.

**Comment by fbriere** [comment]
(scratches head) I thought I had recalled seeing it work without `file-local-options/`, hence my report that it didn't work with it.  Not sure where that idea ever came from, but it was indeed mistaken.  Sorry for the noise.
