### ISSUE TITLE
Playlist on next image/video pan to the top

### ISSUE THREAD

**Issue by gin9980** [mpv-player/mpv#7789]
How do you get MPV to always reset the next file in the playlist to the top of the video player instead of centering it? 
Using MPV as a image viewer on a long pages I usually zoom in on them to read, going to the next image centres the video-pan-x,video-pan-y using reset-on-next-file. But how do I instead get it to pan to the top automatically on the next file? 
Video-pan also seems to ignore boundaries so its possible to hide the video/image off screen.

**Comment by wm4** [comment]
--reset-on-next-file resets options to the value set in the config file or on command line, so you can set these options as you want. What you seem to want sounds vaguely like --video-align-.... Use scripts to get any sort of specialized behavior.
