### ISSUE TITLE
Put mpv behind desktop icons in macOS

### ISSUE THREAD

**Issue by sheharyarn** [mpv-player/mpv#7791]
### Expected behavior of the wanted feature

Passing a flag that puts the mpv window **_behind_** all UI elements (like desktop icons, dock, menubar) in macOS. Essentially looking to get https://github.com/Akemi/mpv/commit/cb1fb23e8e573878850e09f5aad2afea4c3b4471 merged into master. (via #7790)

### Alternative behavior of the wanted feature

Ideally, this feature stops mpv from completely accepting focus as well, so that mpv is truly "running in the background" without any user interaction.

**Comment by Akemi** [comment]
on a side note, kinda for myself, this might need some adjustments for the window constrain code if one wants to place the window at the top underneath the menubar. 

probably needs this https://github.com/mpv-player/mpv/issues/7725.
also needs https://github.com/mpv-player/mpv/issues/6338 which was closed because there was no further interest in it. basically we need NSApp.setActivationPolicy(.accessory).

**Comment by Akemi** [comment]
please try #8090 if possible. this should do what you want:

```
mpv --ontop-level=desktop --ontop --geometry=100%x100% --macos-app-activation-policy=accessory
```

**Comment by Akemi** [comment]
preventing the focus is on a separate branch (#8087) for now. if you want you can test that PR too, with `--no-focus`.

**Comment by sheharyarn** [comment]
> please try #8090 if possible. this should do what you want:

Yes! This is super-close to what I had in mind (and also sorta solves the focus problem). For reference, this is what I used:

```shell
build/mpv darksouls.gif --ontop-level=desktop --ontop --macos-app-activation-policy=accessory --loop --really-quiet --no-config --no-audio --no-osc --no-border --no-input-cursor --no-input-default-bindings --cursor-autohide=no --fullscreen --no-native-fs --video-zoom=0.15
```

> preventing the focus is on a separate branch (#8087) for now. if you want you can test that PR too, with --no-focus.

Tried this too, but mpv is still grabbing focus on start. Maybe pairing this with the previous commands will make it feel more natural?

---

Thanks for all the amazing work!

**Comment by Akemi** [comment]
interesting that the focus branch doesn't work for you either like on #7725, but it does work for me. wondering what the difference is, diff OS and/or shell version? could you screen record it with the --no-focus, maybe i can see a difference in what i am doing differently?

**Comment by sheharyarn** [comment]
> could you screen record it with the --no-focus, maybe i can see a difference in what i am doing differently?

Here's the screen recording: https://0x0.st/iInt.mov

> what else would you need? since you mentioned it only super-close?

Sorry about the confusion. **The feature framed in this issue is 100% complete** I believe and can be closed, so thank you again for working on this!

I was referring to my real goal of using mpv for video wallpapers originally mentioned in #7790, which still requires me to figure out a couple more things:

 - Starting mpv as a wallpaper for each desktop on each monitor

 - Starting or killing an mpv process whenever a new desktop is added or removed

A few other very minor things I noticed which are unrelated to this (but let me know if you have any thoughts or pointers regarding them):

 - When desktop icons are visible as usual, clicking the background (mpv running as an accessory) behaves just like the desktop (can select icons, drag, nothing in touchbar either). But if the [desktop icons are hidden](https://apple.stackexchange.com/questions/79677/hide-files-icons-on-the-desktop-but-not-in-finder/120328), clicking the desktop still behaves the same with the only difference being that the touchbar switches to mpv (with the seekbar, etc.).

 - mpv shows up as a window in Mission Control (there's probably no way around this at all)

    <img width="1680" alt="image" src="https://user-images.githubusercontent.com/2355108/93500869-1ab36e00-f92e-11ea-91f0-af7f0ba6f98c.png">

**Comment by Akemi** [comment]
> clicking the desktop still behaves the same with the only difference being that the touchbar switches to mpv (with the seekbar, etc.).

yeah, i think this will not be easily doable.

> mpv shows up as a window in Mission Control (there's probably no way around this at all)

that can be done. the collectionBehavior of the window has to be set additionally (insert) to transient (https://developer.apple.com/documentation/appkit/nswindow/collectionbehavior/1419733-transient). if you want another option for that, would you mind opening a new issue/feature request for this?

**Comment by Akemi** [comment]
also just for me, https://github.com/mpv-player/mpv/pull/4051 this was the original PR for the window level with explanation to all the different window levels.

**Comment by Akemi** [comment]
also thank you for the screen recording.

**Comment by Akemi** [comment]
i pushed a fix to the focus branch/PR. if you want to test it again that would be nice. see my last comment here #7725 and if it still doesn't work, just leave me a comment on the other issue.

**Comment by forthrin** [comment]
I was going to request this, and it's already in, and it works perfectly out of the box. Fantastic!

My use case was to take notes while looking at videos. However, macOS Notes doesn't seem to have a native transparency setting. Does anyone know a way to make Notes (or any application window) transparent?

I found [this](https://apple.stackexchange.com/questions/192002/is-it-possible-to-change-opacity-of-an-application-window) and [this](https://apple.stackexchange.com/questions/192002/is-it-possible-to-change-opacity-of-an-application-window), but they all seem outdated or not relevant.
