### ISSUE TITLE
Changing Pitch with Best Quality

### ISSUE THREAD

**Issue by mysteryx93** [mpv-player/mpv#7792]
To change the pitch in SVP, there are currently 2 methods

Using Rubberband

    --af=rubberband=pitch-scale=0.981818181818181

Using Scaletempo (broken; it alters the speed when it shouldn't)

    --af=scaletempo=speed=pitch --speed=0.9818181818181818 --no-audio-pitch-correction

I'm not sure what is the algorithm of Scaletempo, but I've done plenty of tests between Rubberband and Soundtouch algorithms. Rubberband is said to have higher quality, but it boosts the bass and muffles the acoustics. Soundtouch in fact gives a result that is closer to the original.

Also, for max quality, I found that I first must resample from 44100hz to 48000hz in 32-bit, and THEN change the pitch with Soundtouch. I've achieved that with my own mini-player using NAudio+Soundtouch.

Is there a way to achieve this result with MPV? (other than loading an Avisynth script file that does these exact steps)

**Comment by wm4** [comment]
You could tune rubberband (there are lots of options), or fix scaletempo?
You could also contribute soundtouch support, but it's C++ only, so that would be a mess.

**Comment by mysteryx93** [comment]
I wonder how scaletempo compares to soundtouch... is that algorithm implemented elsewhere?

You say SoundTouch on its own could be a mess... then adding 48000hz resampling on top of it would further complicate things.

I have tons of things to program in my todo list so I wouldn't go into MPV source code; plus I'm primarily a .NET programmer.

Another option is to have my own player that loads the audio in a separate side-player ... there would be a slight performance loss for reading the source video file twice, and there could be sync issues... but maybe it could work...

**Comment by mysteryx93** [comment]
As an update, I found this [at the bottom of this page](http://scaletempo.sourceforge.net/0/task-list.html).

>SoundTouch library - inspiration for scaletempo

Considering ScaleTempo is based on SoundTouch, it "should" have at least the same quality.

Remains to fix the bug [in this ticket](https://github.com/mpv-player/mpv/issues/7677).

I can't really compare the quality until the bug is fixed.

**Comment by Akemi** [comment]
we have a new scaletempo algorithm now. if the issue still persists please open a new issue.

**Comment by mysteryx93** [comment]
> we have a new scaletempo algorithm now. if the issue still persists please open a new issue.
"Scales audio tempo without altering pitch"

Is there a way to use it to alter pitch? If so, what would be the syntax?

**Comment by nazarux** [comment]
The rubberband filter works great.
I’m interested in increase/decrease semitones: multiplying by 0.9438743126816935 decreases one semitone and by 1.059463094352953 increases a semitone.
A semitone is increased with the command 
    `mpv --af=rubberband=pitch-scale=1.059463094352953 /path/to/file`
What I’m trying to do is to create two key combinations (in input.conf) to increase and decrease semitones.
But after reading the manual and trying multiple syntax like this, in input.conf, I had no success…
```
    Ctrl+k multiply rubberband multiply-pitch 0.9438743126816935
    Ctrl+j multiply rubberband multiply-pitch 1.059463094352953
```
Any idea on how to put this to input.conf

**Comment by jnm** [comment]
In case it still helps:
> @abvincita, this is my current setting in mpv.conf: `af=@rb:!rubberband`
>
> And input.conf:
> `ALT+t af toggle @rb`
> `ALT+4 af-command rb multiply-pitch 0.9438743126816935`
> `ALT+5 af-command rb set-pitch 1.0`
> `ALT+6 af-command rb multiply-pitch 1.059463094352953`
>
> So "Alt+t" activates the rubberband filter (disabled by default).

https://github.com/mpv-player/mpv/issues/5037#issuecomment-379806482
