### ISSUE TITLE
Enable hdr-compute-peak for HEVC Main 10

### ISSUE THREAD

**Issue by mishurov** [mpv-player/mpv#7794]
- mpv version:  0.32.0
- Platform and Version: Debian 10
- Source of the mpv binary: Github

This is an excerpt from mediainfo.
```
Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@Main
Codec ID                                 : V_MPEGH/ISO/HEVC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
```

As I understand, technically it isn't HDR, it doesn't contain metadata and setting ```hdr-compute-peak``` has no effect. My LCD panel (LP133QD1-SPB2) isn't HDR. I use the correct Relative Colorimetric ICC profile which came from the manufacturer, it works ok with 8 bit videos but 10 bit videos are noticeable brighter and lose lots of details in overbrightened areas. I tried various algorithms and parameters for tone mapping, target-peak, etc, nothing helps. Is it possible to enable dynamic computing of brightness for such videos?

**Comment by Hrxn** [comment]
> Source of the mpv binary: Github

Eh, what? Where is this mythical mpv binary here on GitHub?

**Comment by mishurov** [comment]
@Hrxn I used the mpv-build repository with the helpers scripts to pull the release, to compile and to package the binary into a deb file. I thought that wouldn't be too hard to guess that, as opposed to packages from official and unofficial repositories.

**Comment by mishurov** [comment]
ffmpeg
```
Metadata:
    ENCODER         : Lavf58.41.100
  Duration: 01:39:41.19, start: 0.000000, bitrate: 6483 kb/s
    Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv), 3840x1606 [SAR 1:1 DAR 1920:803], 23.98 fps, 23.98 tbr, 1k tbn, 23.98 tbc (default)
    Metadata:
      ENCODER         : Lavc58.75.100 libx265
```

**Comment by Akemi** [comment]
please open a new issue with all the info we ask for if the problem still persists.
