### ISSUE TITLE
Building using msys2 on windows10: waf does not find libass

### ISSUE THREAD

**Issue by JayEff87** [mpv-player/mpv#7796]
### mpv version and platform versions

Checked out master branch, which looks like it's on v0.32.0

### Reproduction steps

* Install msys2 from https://msys2.github.io/
* run `pacman -Syu` and `pacman -Su`, closing the terminal in between as instructed
* open mingw64 shell
* run `pacman -S git python $MINGW_PACKAGE_PREFIX-{pkg-config,gcc}`
* run `pacman -S $MINGW_PACKAGE_PREFIX-{ffmpeg,libjpeg-turbo,lua51}`
* run `git clone https://github.com/mpv-player/mpv.git && cd mpv` directly on E:
* run `/usr/bin/python3 bootstrap.py`
* run `/usr/bin/python3 waf configure CC=gcc.exe --check-c-compiler=gcc --prefix=$MSYSTEM_PREFIX`

### Expected behavior

mpv is being configured

### Actual behavior

waf does not find libass, specifically, the last command aborts with the error:
```
Checking for SSA/ASS support                                              : no ('libass >= 0.12.1' not found)
Unable to find development files for libass, or the version found is too old. Aborting.
```

### Log file

Here's the build/config.log: [config.log](https://github.com/mpv-player/mpv/files/4718449/config.log)

### Final notes

I have found a much older issue [(from 2015)](https://github.com/mpv-player/mpv/issues/1716) with a very similar looking problem. Their solution, running autorebase.bat in the msys folder, did unfortunately not help me. 
`pkg-config --atleast-version 0.12.1 libass && echo $?`
results in no output, but
` pacman -S $MINGW_PACKAGE_PREFIX-libass` warns: 
`warning: mingw-w64-x86_64-libass-0.14.0-1 is up to date`

**Comment by avih** [comment]
Well, you installed git and ffmpeg and other stuff, but didn't actually install libass... so unless you expect it to be installed by default with MSYS2, why would it be there?

**Comment by avih** [comment]
Try running `pkg-config.exe --libs libass` and see what it prints. Note that you should be in mingw64 (or 32, depending on what you're trying to build) while running it - and while running `./waf`.

**Comment by JayEff87** [comment]
Hi, thanks for your quick response, sorry for responding so much later.
I'm following this guide here: https://github.com/mpv-player/mpv/blob/master/DOCS/compile-windows.md
In it, it says:
```
# Install the most important MinGW-w64 dependencies. libass and lcms2 are also
# pulled in as dependencies of ffmpeg.
pacman -S $MINGW_PACKAGE_PREFIX-{ffmpeg,libjpeg-turbo,lua51}
```
which is the command I've run, as it says in my first post.
Here's the output of the command you suggested I run:
```
$ pkg-config --libs libass
-LC:/msys64/mingw64/lib -lass
```
Checking that path, I find the files `libass.dll.a` and `libass.a` so unless I'm mistaken, the library is indeed installed, right? 
Lastly, I open the bash by typing mingw in the start menu of windows, and selecting "msys2 mingw 64 bit" - I checked the shortcut and it goes to the correct mingw installation too. For completeness' sake, it also says `Jay@Jay-PC MINGW64 /e/mpv` in the console.

**Comment by avih** [comment]
> `pkg-config --atleast-version 0.12.1 libass && echo $?` results in no output

> `$ pkg-config --libs libass`
> `-LC:/msys64/mingw64/lib -lass`

Hmm.. this is weird. so pkg-config does see that it has libass, but not the right version? (otherwise the first command should have printed 0 but it didn't print anything to you).

Can you please post the content of `/mingw64/lib/pkgconfig/libass.pc` ?

FWIW, for me it's:
```
prefix=/mingw64
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libass
Description: LibASS is an SSA/ASS subtitles rendering library
Version: 0.14.0
Requires: 
Requires.private: harfbuzz >= 0.9.5, fontconfig >= 2.10.92, fribidi >= 0.19.0, freetype2 >= 9.10.3
Libs: -L${libdir} -lass 
Libs.private: -lm -liconv -liconv
Cflags: -I${includedir}
```

and for me the first command does print `0`.

**Comment by avih** [comment]
Also, could you please try `pkg-config --print-errors --atleast-version 0.12.1 libass` ?
And if it doesn't show anything useful, try replacing `--print-errors` with `--debug`.

**Comment by JayEff87** [comment]
Hi and thanks again for your response, the file contents of libass.pc seem fine, but for completeness' sake:
```
prefix=/mingw64
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: libass
Description: LibASS is an SSA/ASS subtitles rendering library
Version: 0.14.0
Requires: 
Requires.private: harfbuzz >= 0.9.5, fontconfig >= 2.10.92, fribidi >= 0.19.0, freetype2 >= 9.10.3
Libs: -L${libdir} -lass 
Libs.private: -lm -liconv -liconv
Cflags: -I${includedir}
```
The `--print-errors` command was interesting: it says it can't find cairo, so I did a `pacman -S` and heureka, the `--atleast-version` command with the echo now prints 0. let's see what waf does...

Still a bunch of red things which I suppose is normal, as it prints "configure finished successfully". let's do the install... finished successfully, let's see if it runs... Yup, was able to play a video with it.

So it looks like pacman was supposed to pull all dependencies of ffmpeg, and it did pull libass, but libass depends on harfbuzz, and harfbuzz depends on cairo, and that was not pulled for some reason.

Fantastic! Thanks for all your help, always glad to learn new things. I suppose this can be closed then!

**Comment by avih** [comment]
Thanks for testing. This sounds like an MSYS2 package issue. I think you should report it to them so that we don't have to go through this again with the next user...

If you do, please post a link here too, thanks.

**Comment by JayEff87** [comment]
I've posted an issue here: https://github.com/msys2/MINGW-packages/issues/6553

**Comment by avih** [comment]
Thank you.
