### ISSUE TITLE
Shuffles should be somewhat non-deterministic

### ISSUE THREAD

**Issue by Mattwmaster58** [mpv-player/mpv#7797]
Before requesting a new feature make sure it hasn't been requested yet.

### Expected behavior of the wanted feature

Shuffle should use some sort of random function so the shuffling a list of files is somewhat non-deterministic. Currently the behavior is a deterministic (ie every time I run `mpv "<path>" --shuffle`, it shuffles it in the exact same way every time)

### Log file

Really don't think is necessary, available on request.

**Comment by CounterPillow** [comment]
It already shuffles completely random for me. Provide a log file.

**Comment by Mattwmaster58** [comment]
Indeed you are correct. In my naivety I was using an old mpv.net build. Thanks.
