### ISSUE TITLE
How to release memory manually?

### ISSUE THREAD

**Issue by levenies** [mpv-player/mpv#7798]
### Important Information

Provide following Information:
- mpv version：any version
- Windows Version : win7
- Source of the mpv binary
- If known which version of mpv introduced the problem
- Possible screenshot or video of visual glitches

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

When playing HTTP video, the memory will continue to rise. If the file is large and the playing time is long, the memory will be high and will not be released automatically. Is there a manual release interface?

**Comment by Akemi** [comment]
try lowering the various stream buffers. there is no manual release interface and it should not be necessary.
