### ISSUE TITLE
add workaround for AMD driver not handling D3D11VA/DXVA2 VP9 correctly?

### ISSUE THREAD

**Issue by aufkrawall** [mpv-player/mpv#7799]
### Important Information

Provide following Information:
- mpv-x86_64-20200531-git-102a083 by shinchiro
- current Windows versions with current AMD drivers

### Reproduction steps
Play a VP9 video with `--hwdec=d3d11va` or `--hwdec=dxva2` on an AMD GPU that supports it (e.g. Navi and likely also Raven Ridge/Renoir APUs).

### Expected behavior
It works on Intel and Nvidia since their drivers properly expose hwdec capabilities for the VP9 codec. It also works with AMD on Linux with VAAPI.

### Actual behavior

mpv/ffmpeg can't use hardware decoding for VP9 on AMD Windows. This is not mpv's fault, but clearly that of AMD's driver. The cause seems to be this:

> it reports that it only supports macroblock mode while you have to support raw bitstream mode so a correctly coded DXVA2 implantation will not use it. the problem is raw bitstream mode works totally fine they just flag it wrong mpc-be internal decoder isn't checking or ignoring it and it works fine.
https://forum.doom9.org/showpost.php?p=1911778&postcount=2580

In the meantime, also mpc-hc has added a workaround for it since AMD doesn't seem to care at all.

So, would it be possible to add a workaround also for mpv? I suppose also ffmpeg would have to be patched.

### Log file

Since the lack of an AMD GPU, I can't provide one myself.

### Sample files

Anything with VP9.

**Comment by wm4** [comment]
Wouldn't that be a ffmpeg thing?

**Comment by aufkrawall** [comment]
I can't judge if this can be resolved entirely in ffmpeg. If so, then you are of course right.

If there are no objections, I'd report it to ffmpeg then. I'd just be a bit worried that this might be considered too hacky to include it in master. Of course it sucks as well to expect mpv or its Windows maintainer (@shinchiro ) to resort to hacky workarounds instead...

**Comment by jeeb** [comment]
I had wished you had actually noticed which commit in nev's LAV or FFmpeg repo would have done the thing...  I will see on ffmpeg-devel and attempt to see who the hell are our AMD contacts, since this sounds like bullshit.

**Comment by aufkrawall** [comment]
Afaik the fix is only in mpc-hc (and mpc be using their own internal ffmpeg based stuff) and not LAV Filters upstream:
https://github.com/clsid2/LAVFilters/compare/90084b1822acd8afdf5c1cca2a73db6c1e183125...c6dffb48756539b4a5bbac933881ab975a5a39a2#diff-7bed46c5c61c0ac625cebf8a9922cc48

**Comment by wm4** [comment]
That doesn't seem very AMD specific. Potentially dangerous. I still don't think this can be worked around from mpv.

**Comment by jeeb** [comment]
```
18:01 <@nevcairiel> I know how to fix it, but I just don't care
18:02 <@nevcairiel> its an obvious spec violation from the AMD driver,
                    and if they cared, they should fix it
```

**Comment by aufkrawall** [comment]
Ok. Still it would be great if somebody who has a good connection to AMD could reach out to them (after reporting it to ffmpeg tracker?). I reported this back in December to AMD via their silly Windows driver feedback form, but of course only deafening silence followed.

Though it seems the workarounds for mpc-hc/be haven't caused any regressions. So I guess if one was willing to "take the risk", the ffmpeg build linked to the mpv Windows build could be patched accordingly (me preparing to dodge the hatchet..)?

**Comment by aufkrawall** [comment]
Works now, probably fixed in driver.
