### ISSUE TITLE
Restore --dumpaudio / --dumpvideo / --dumpstream

### ISSUE THREAD

**Issue by Nikoli** [mpv-player/mpv#78]
Commit 7059c15f4af047d29bed9ea8b17a3702980b8442 removed --dumpaudio / --dumpvideo / --dumpstream features, please restore them. They are very helpful for dvd ripping and remuxing.

**Comment by agoston** [comment]
Hello,

I've tried the following:
```
mpv 5223a4053ce608d40a6fb2d0bb1317a4.mp4 -o a.aac --no-video
```
to dump the audio of a presentation.

Got this:

```
[encode-lavc] Opening audio encoder: AAC (Advanced Audio Coding) [aac]
[encode-lavc]
[encode-lavc]
[encode-lavc]            ********************************************
[encode-lavc]            **** Experimental AUDIO codec selected! ****
[encode-lavc]            ********************************************
[encode-lavc]
[encode-lavc] This means the output file may be broken or bad.
[encode-lavc] Possible reasons, problems, workarounds:
[encode-lavc] - Codec implementation in ffmpeg/libav is not finished yet.
[encode-lavc]      Try updating ffmpeg or libav.
[encode-lavc] - Bad sound quality, noise, clicking, whistles, choppiness.
[encode-lavc]      Experiment with codec settings (--oacopts) to maybe still get the
[encode-lavc]      desired quality output at the expense of bitrate.
[encode-lavc] - Slow compression.
[encode-lavc]      Bear with it.
[encode-lavc] - Crashes.
[encode-lavc]      Happens. Try varying options to work around.
[encode-lavc] If none of this helps you, try another codec in place of aac.
[encode-lavc]
AO: [lavc] 48000Hz stereo 2ch floatp
[encode-lavc] Opening output file: a.aac
[encode-lavc] Opening muxer: ADTS AAC (Advanced Audio Coding) [adts]
A: 00:41:52 / 00:41:54 (99%) {0.0min 65.19x 39.3MB}
```

To me, this indicates that it decodes and re-encodes the audio stream, instead of just dumping it to the output file.

Is this correct? Is there a way to dump the actual audio stream?

**Comment by wm4** [comment]
mpv has encoding support, but no support for stream copy. mpv is not the right tool for this; use e.g. ffmpeg. (Plus I doubt the raw audio stream is actually useful. If you just want to remove the video stream from the file, something like mkvmerge would be better and easier.)

**Comment by agoston** [comment]
Agreed; ffmpeg is better suited for this. For future reference/google hits, this is how to dump audio from a video file:

ffmpeg -i input.mp4 -c:a copy -vn output.aac

**Comment by wm4** [comment]
Out of curiosity, what are you doing with the aac file?

**Comment by agoston** [comment]
Put it on a USB stick, listen to it while commuting from a sony car stereo.
But to stay on the safe side, I've ended up using -ao pcm && lame && mp3splt, as I like to be able to seek quickly so I split the podcasts into 3 minute long tracks. I didn't have a tool handy that splits aac files (which seems to be an mp4 container).

**Comment by LateAdopter** [comment]
Just for info:
A DVB-S satellite receiver PVR typically captures radio channels as mpeg1 layer2 in a PS or TS container, with no video.
A generic media player will play this correctly, but an MP3 player treats PS a normal audio stream so it plays back at slightly the wrong speed and is somewhat garbled. I haven't tried TS.
It is necessary to extract the audio stream from the container in order to play the mp2 audio in an mp3 player correctly.
There are other tools that can extract the stream without recoding so MPV doesn't need to.
