### ISSUE TITLE
git master fails to build

### ISSUE THREAD

**Issue by kattjevfel** [mpv-player/mpv#7802]
### mpv version and platform versions
07b0c18bad6cb168191d390f10db998eb7201b67 arch linux

### Reproduction steps
1. Build mpv-git 07b0c18bad6cb168191d390f10db998eb7201b67 from AUR
2.
```
../video/out/wayland_common.c:37:10: fatal error: generated/wayland/idle-inhibit-v1.h: No such file or directory
   37 | #include "generated/wayland/idle-inhibit-v1.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### Expected behavior
build success

### Actual behavior
build fail

### Log file
https://gist.github.com/1b5c92d8cec18b1c44e4e1e17c273fef

**Comment by kattjevfel** [comment]
@wm4 With c1fc5354c3c15b46d77adf4d27d38b8b27fa9dfd I instead get the following:
```
../player/lua.c:78:13: fatal error: player/lua/console.inc: No such file or directory
   78 | #   include "player/lua/console.inc"
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by wm4** [comment]
Try now.

**Comment by kattjevfel** [comment]
All is well again, thanks!
