### ISSUE TITLE
A new identity for MPV

### ISSUE THREAD

**Issue by clashg0ne** [mpv-player/mpv#7806]
I know that we can manually add a new icon, but I thought that MPV really needs a new official icon, as the actual one really seems old to me with this 3d effects. So I made this :
![IMG_20200605_183727](https://user-images.githubusercontent.com/66486556/83909758-a2071800-a769-11ea-98bf-abad67d8c4ce.jpg)
It's a modernized version of the actual icon. 
I want to know if you like it, what should I change and if it would make a great official icon.

And I think even with this developers did a great job to make this video player.

**Comment by CounterPillow** [comment]
holy shit that is ugly

**Comment by Akemi** [comment]
i don't see a reason to change our icon. especially not since our 'brand' is becoming more and more of a household name.

also that thin white line is a horrible idea. it's very aliased and on smaller sizes it's completely pointless. imo if the icon should be modernised we should at least pick up all the current unique characteristics of the icon, like the none cantered ring(s) and the shades of purple.

**Comment by mia-0** [comment]
Agreed. I don’t think we need to change it.

As far as modern/flat icons go, I like KDE’s Breeze icon theme. They already have an icon for mpv, but no low-res version of it.

**Comment by haasn** [comment]
I already own items branded with the old mpv logo, who will give me a refund if we change it? :(

**Comment by avih** [comment]
I actually quite like the current mpv logo. I think it should stay.

**Comment by Hrxn** [comment]
While we're at it: I'd like some new color, some azure blue or something.

**Comment by Argon-** [comment]
I think if the current logo as a part of the mpv "brand". Users connect both in their head with the actual program. Changing the logo is similar to changing mpv's name (although not as strong/drastic of course) and this also includes changing just the color. 

Personally, I would suggest not to change either (name, logo, color) and only do so in case a complete "restyling" is desired in the future. The current logo is still quite contemporary in its style. 

)Also what @CounterPillow said)

**Comment by clashg0ne** [comment]
After thinking of it i agree with your advice.


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Julian<mailto:notifications@github.com>
Envoyé le :samedi 6 juin 2020 02:32
À : mpv-player/mpv<mailto:mpv@noreply.github.com>
Cc : clashg0ne<mailto:MelvynBG@outlook.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [mpv-player/mpv] A new identity for MPV (#7806)


I think if the current logo as a part of the mpv "brand". Users connect both in their head with the actual program. Changing the logo is similar to changing mpv's name (although not as strong/drastic of course) and this also includes changing just the color.

Personally, I would suggest not to change either (name, logo, color) and only do so in case a complete "restyling" is desired in the future. The current logo is still quite contemporary in its style.

(Also what @CounterPillow<https://github.com/CounterPillow> said)
