### ISSUE TITLE
OSC box disappears after dragging the video window

### ISSUE THREAD

**Issue by jnozsc** [mpv-player/mpv#7807]
### Important Information

Provide following Information:
- mpv version
any version after `0.29.1`. can reproduce from `master` `HEAD` as well

- macOS Version
10.15.5 

- Source of the mpv binary or bundle
https://laboratory.stolendata.net/~djinn/mpv_osx/ or build by myself from git source

- If known which version of mpv introduced the problem
`0.29.1` works well, broken since `0.30.0`
may broken in any commit during these 2 release. https://github.com/mpv-player/mpv/compare/v0.29.1...v0.30.0
I try to find the actual commit, but when I try to build certain commit in this range, I have some local build issues which prevent me from figuring out which commit causes this issue

- Possible screenshot or video of visual glitches
`0.29.1`, works https://www.youtube.com/watch?v=pOLzjLK_shA
broken since `0.30.0` https://www.youtube.com/watch?v=Vu8Iea0KWug

If you're not using git master or the latest release, update.
Releases are listed here: https://github.com/mpv-player/mpv/releases

### Reproduction steps

> Try to reproduce your issue with --no-config first. If it isn't reproducible
with --no-config try to first find out which option or script causes your issue.

`--no-config` can not reproduce this issue, since by default, the OSC layout is `bottombar`. 
By using a config with only one line as `script-opts=osc-layout=box`, I can consistently reproduce this issue. 

> Describe the reproduction steps as precise as possible. It's very likely that
the bug you experience wasn't reproduced by the developer because the workflow
differes from your own.

When open a video,
the OSC box can display immediately on the video,
after several seconds, 
it disappears automatically, 
which is expected.
If I don't drag the window,
I can always trigger the OSC again by moving my mouse on the video

However, 
if I drag the video window, 
as you can see in these videos above, 
no matter how I move my mouse again on the video,
the OSC won't show up again.
A workaround is change the video window to full screen and change it back,
the OSC can show up,
but if I drag the video window again,
the OSC won't show again

### Expected behavior
OSC box appears when the mouse move over the video, even after dragging the video window

### Actual behavior
After dragging the video window, OSC box can not display any more, when the mouse move over the video

### Log file

Make a log file made with -v -v or --log-file=output.txt. If you use the Bundle
from a version later than 0.32 a default log is created for your last run at
~/Library/Logs/mpv.log. You can jump to that file via the Help > Show log File…
menu. Paste the log to https://0x0.st/ or attach it to the github issue, and
replace this text with a link to it.

In the case of a crash please provide the macOS Crash Report (Backtrace).

The issue will be closed for ignoring the issue template.

log file https://0x0.st/iOhl.log

### Sample files

Sample files needed to reproduce this issue can be uploaded to https://0x0.st/
or similar sites. (Only needed if the issue cannot be reproduced without it.)
Do not use garbage like "cloud storage", especially not Google Drive.

any video can reproduce this issue

**Comment by jnozsc** [comment]
this issue can be fixed by add `vo=gpu` into config.

`./mpv -vo=help`

gives me

```
Available video outputs:
  libmpv           render API for libmpv
  gpu              Shader-based GPU Renderer
  null             Null video output
  image            Write video frames to image files
  tct              true-color terminals
```

so I try to add `vo=libmpv` into config -> issue could be reproduced. 
`vo=gpu` -> no issue

**Comment by Akemi** [comment]
i can reproduce this with `--no-config` and the default layout too. on a side note, testing with `--vo=gpu` is kinda pointless since it uses completely different windowing code paths.

the problem is most likely in the title bar code and the mouseUp and mouseDown events that are caught there.
