### ISSUE TITLE
OSC time tooltip sluggish since build 20191222

### ISSUE THREAD

**Issue by StrangePeanut** [mpv-player/mpv#7808]
### Important Information

Provide following Information:
- **mpv version:** any build after 20191215
- **Windows Version:** 2004
- **Source of the mpv binary:** https://sourceforge.net/projects/mpv-player-windows/files/64bit/
- **If known which version of mpv introduced the problem:** 20191222
- **Possible screenshot or video of visual glitches:** https://streamable.com/m197kp (20191215 vs current)

### Reproduction steps

1. Open any file with any build after 20191215
2. Hover over the seek bar
3. The time tooltip appears sluggishly

The difference is like night and day on a high refresh rate monitor

### Expected behavior

The time tooltip follows the cursor smoothly as seen on build 20191215 and prior

### Actual behavior

The time tooltip appears sluggishly

### Log file

https://hastebin.com/ucupezozeb.md

### Sample files

Any media file can be used

**Comment by rossy** [comment]
I think this is because the OSC started using a timer to rate-limit updates, so it's intentional that it doesn't update more than once every 30ms, so no more than about 33fps. There's some reasoning for the change here: 48f906249ef3
