### ISSUE TITLE
macOS and Bootcamp (Windows 10) have differing performance

### ISSUE THREAD

**Issue by jameswilliamsmith** [mpv-player/mpv#7809]
- **mpv version**: 0.32.0
- **macOS Version**: 10.15.5
- **Device**: Macbook Pro 13 2017
- **Source of the mpv binary or bundle**: OS X builds by stolendata, shinichiro for W10

### Expected behavior
mpv.conf:
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp

Using mpv with the same config file on both OS should have the same performance

### Actual behavior
macOS performance is significantly slower than on my Windows 10 partition. macOS can handle gpu-hq with stable fps but adding scaling filters slows down fps considerably. I thought it was the limit of my hardware but I tried it on my Windows 10 partition and it handles the configuration at full speed. I can even add these lines to my configuration file without any issue:
video-sync=display-resample
interpolation
tscale=oversample

**Comment by Argon-** [comment]
macOS has brutally bad graphics drivers. This is to be expected.
It's the same for games and benchmarks. Windows graphics drivers are far superior in performance. Nothing that can be done here other than using Windows.

**Comment by jameswilliamsmith** [comment]
Ok thanks. Guess I'll have to skip the advanced configurations since it is also my main OS.
