### ISSUE TITLE
mpv completely hangs at random

### ISSUE THREAD

**Issue by Silver-Fullbuster** [mpv-player/mpv#7811]
### Important Information

Provide following Information:
- mpv version
```
mpv 0.32.0-547-g12415db3a6 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Sun Jun  7 21:26:43 +08 2020
FFmpeg library versions:
   libavutil       56.50.100
   libavcodec      58.90.100
   libavformat     58.44.100
   libswscale      5.6.101
   libavfilter     7.84.100
   libswresample   3.6.100
FFmpeg version: git-2020-06-07-d09c3567
```
- Windows Version - Windows 10 v1909 (Build 18363.836)
- Source of the mpv binary - Shinchiro 
- If known which version of mpv introduced the problem - mpv-x86_64-20200531-git-102a083

mpv window is completely frozen, including any OSD/OSC being shown when it happens. Unresponsive to any keybinds, the only option is to close it using Task Manager. Using "Win+D" to show the desktop works, and shows the minimize events in log, but nothing is logged about the sudden complete freeze. Happens at random, and within 5 mins of playback. Seeking the video seems to make it much more likely to occur

### Reproduction steps

I can try with --no-config if needed, but this should be a regression since the previous build works without any issues

1. Play any video on mpv
2. Wait for it to freeze

### Expected behavior

mpv should not freeze and have keybinds responding

### Actual behavior

mpv freezes, no keybinds work, OSD/OSC if being shown is stuck and there is no response to anything by the mpv window

### Log file
[mpvlog.txt](https://github.com/mpv-player/mpv/files/4743202/mpvlog.txt) (stopped using Ctrl+C)
[mpvlog.txt](https://github.com/mpv-player/mpv/files/4744318/mpvlog.txt) (stopped using Task Manager)

Not sure if how we stop matters, so uploaded both

**Comment by Silver-Fullbuster** [comment]
Just to clarify, the last working build by shinchiro is `mpv-x86_64-20200524-git-685bd6a.7z`, and the next weekly build `mpv-x86_64-20200531-git-102a083.7z` was broken. I assumed the commit d448dd5bf26408ccced1bd6df8f9eaf62a370c8e was the fix, and waited for the next build which released today (`mpv-x86_64-20200607-git-12415db.7z`) and the freeze still happens

**Comment by jeeb** [comment]
Tested with my build that I just recompiled from 0fb02f181f3df9e8336939b42c3412e01fb60427 with both my usual config and with just `--no-config` against an MP4 and Matroska file I have around. Played so far for 8 minutes, no problems.

Additionally, that log looks like there was no file opened at all?

**Comment by Silver-Fullbuster** [comment]
Yep, the log file was faulty, replacing after I reproduce

**Comment by shinchiro** [comment]
Weirdly, I cannot reproduce the problem with build `mpv-x86_64-20200607-git-12415db.7z`

**Comment by Silver-Fullbuster** [comment]
Reproduced and the log file is now the updated one. Also, I removed all of my scripts this time so this should be definitely related to mpv itself. mpv was closed using Ctrl+C since I ran it using command prompt

**Comment by Silver-Fullbuster** [comment]
Ok, I was trying to see how long it takes happens and if it's regular, and it's always close to 10 minutes.

From the timestamp using cmd, 19:59, 29:09, 41:58. Roughly every 10-12 mins.

**Comment by Silver-Fullbuster** [comment]
https://pastebin.com/AsNvnbJp

Is this gonna help? I used gdb to attach with mpv and got the backtrace using `thread apply all bt`

**Comment by wm4** [comment]
Would normally help a lot, but the backtrace seems corrupted. Possibly broken or wrong debug infos? Not sure what to do about this.
Once this is solved, you could also reduce the number of threads with something like ``--vd-lavc-threads=1 --no-load-scripts``.

**Comment by Silver-Fullbuster** [comment]
I guess I'll make another backtrace with the above options and see if that's any useful. I'll post it in a few hours. Meanwhile, if there's anything else I can do to make a better backtrace/provide better info, I'm willing to help

**Comment by shinchiro** [comment]
You could try [this build](https://filebin.net/7j08prupxgjdedot/mpv.rar?t=1zda2ykc) with debug infos intact.

**Comment by Silver-Fullbuster** [comment]
Without `--vd-lavc-threads=1 --no-load-scripts`: https://pastebin.com/n3CHpxuC
With `--vd-lavc-threads=1 --no-load-scripts`:  https://pastebin.com/7YfHDDmj

**Comment by kevmitch** [comment]
probably #7787

**Comment by kevmitch** [comment]
any better?

**Comment by Silver-Fullbuster** [comment]
Can't verify since I don't have a build environment. Will wait for shinchiro builds unless somebody else provides ones to verify

**Comment by shinchiro** [comment]
Got free time to compile. Can test it
[mpv-x86_64-20200618-git-ae5ac7e](https://filebin.net/jab4mqeyqwf9opfu/mpv-x86_64-20200618-git-ae5ac7e.rar?t=a6g9yf1w)

**Comment by mizunarei** [comment]
Seems to be fixed for me atleast. Had the same problem and the above build fixed it. Watched a video for 3 hours without freezing.

**Comment by Silver-Fullbuster** [comment]
Played mpv for total 2 hours in multiple sessions, should be fixed. Will re-open if it persists
